### ISSUE TITLE
NavigationBar RightButton runtime render

### ISSUE THREAD

**Issue by jaygarcia** [facebook/react-native#1000]
Any thoughts on if you guys are planning on adding the capability to inject/render RightButton programmatically? 

I'm thinking of the iOS music player "now playing button" (yeah, the bottom image is from android). It only appears when you've actually started playing music and go back to browsing.

I'd like to inject that type of feature into this Mod Player demo app that i've been working on.
![](http://i.imgur.com/kU2Oj8c.png)

Thanks =)

**Comment by jaygarcia** [comment]
And Oh snap. This is issue number 1000!

**Comment by sahrens** [comment]
Are you referring to this text in the NavigatorIOSExample?

```
            this.props.navigator.replace({
              title: 'New Navigation',
              component: EmptyPage,
              rightButtonTitle: 'Undo',
              onRightButtonPress: () => this.props.navigator.replace(prevRoute),
              passProps: {
                text: 'The component is replaced, but there is currently no ' +
                  'way to change the right button or title of the current route',
              }
            });
```

NavigatorIOS isn't really maintained by FB - maybe @eduardinni or @ide could help out?

**Comment by eduardinni** [comment]
I think you can achieve this behavior using a state var on the main route, and then play with `rightButtonTitle` and `onRightButtonPress` through props when push/replace new routes.

If you pass `null` to `rightButtonTitle` the button will not render.

**Comment by christopherdro** [comment]
@jaygarcia Did you get this resolved?
