### ISSUE TITLE
Image.getSize raising {"framesToPop":1,"code":"E_GET_SIZE_FAILURE"}

### ISSUE THREAD

**Issue by maraujop** [facebook/react-native#10002]
### Issue Description

Image.getSize fails randomly with error `{"framesToPop":1,"code":"E_GET_SIZE_FAILURE"}`
### Steps to Reproduce / Code Snippets

In my Moto G3, it happens way more often than in my Nexus 5X. If I render a component with an Image that calls to `getSize` and I render the same component with the same image twice, in my Moto G3 fails 90% of the times, so I think it could be related to reference closing in Android.

Sometimes it works and sometimes it fails for the very same image and component, functioning is erratic. I'm all the time loading local images.
#### Expected Results

Instead of raising an error, return the width and height
### Additional Information
- React Native version: 0.33.0
- Platform(s) (iOS, Android, or both?): Android Only 6.0 real device, in emulator doesn't happen (probably because images load faster)
- Operating System (macOS, Linux, or Windows?): macOS

**Comment by maraujop** [comment]
After upgrading to RN 0.34 Now I'm sometimes getting:

```
 { [Error: Pool hard cap violation? Hard cap = 75497472 Used size = 25063972 Free size = 0 Request size = 51916800] framesToPop: 1, code: 'E_GET_SIZE_FAILURE' }
```

**Comment by kosiakMD** [comment]
Have the same problem!

**Comment by nathanmalishev** [comment]
Having the same issue on RN 0.39. Works on iOS physical device & emulator. Works on android emulator. Breaks on android device (android 6.0.1)

Anyone found a work around?

**Comment by nathanmalishev** [comment]
Hi there. I managed to work around my issue.
Background:  I was getting images from S3, using pre signed urls. These images did not have file extensions and could be any size.

Issue: Android Physical device threw the E_GET_SIZE_FAILURE, when images did not have a file extension (but it was a hard error to pick up because the android simulator did not, neither did iOS devices). Secondly when the images where too large, the error was also thrown.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/imagegetsize-raising-framestopop1codeegetsizefailure-2

**Comment by sy-tian** [comment]
anyone has solution about this?

**Comment by ElielBarone** [comment]
+1

**Comment by landmass** [comment]
+1

**Comment by noahmalmed** [comment]
+1

**Comment by alejandroledesma** [comment]
+1

**Comment by douglasjunior** [comment]
For me still occurs on Android Emulator API 16.

**Comment by maraujop** [comment]
@hramos could you please reopen this ? 

It still happens with RN 0.55.3

**Comment by wikieswan** [comment]
+1

**Comment by hramos** [comment]
Please open a new issue

**Comment by pintocarlos** [comment]
+1 Also running into this issue.
