### ISSUE TITLE
Rotation handling doesn't work within UIExplorer demo

### ISSUE THREAD

**Issue by aksonov** [facebook/react-native#1001]
After rotation, list content disappear.

![ios simulator screen shot 24 2015 16 03 05](https://cloud.githubusercontent.com/assets/1321329/7320234/760a316e-ea9b-11e4-999d-11db0f4259d5.png)
![ios simulator screen shot 24 2015 16 02 20](https://cloud.githubusercontent.com/assets/1321329/7320233/7609e984-ea9b-11e4-8d8e-f4307808ab9b.png)

**Comment by tadeuzagallo** [comment]
Duplicate of #989
