### ISSUE TITLE
[Packager] Content-addressed module deduplication

### ISSUE THREAD

**Issue by aleclarson** [facebook/react-native#10012]
Any reasons not to dedupe modules that:
- share the same name (relative to their package)
- and share the same code (same package version?)
- but have different paths (eg: exist in two separate `node_modules` directories)

Or is there a recommended way to dedupe modules? (or maybe npm3 gets the job done?)

/cc @davidaurelio

**Comment by davidaurelio** [comment]
npm3 does a decent job of deduping modules with the same version (which usually works well with `^x.y.z`).

Identical modules are not deduped if there are multiple versions of a package in the tree, though.
Another problem are concurrent version that npm can only resolve by duplicating. E.g. your app uses `foo@^2.0.0`, but 10 of your dependencies use `foo@^1.x.y`. In that case, you will end up with ten copies of `foo@1`.

I think you have a very interesting idea. It might be a little bit too slow for development mode, but it is probably a good optimization for production builds. If you want to give it a shot, I can point you to the right files to change. I would be interested in the size reduction of the bundle, and the additional time spent building.

**Comment by aleclarson** [comment]
@davidaurelio I don't have the time to mess with it, at the moment. Just thought I would get the idea out in case anyone wants to tackle it before I get to it. 😄

**Comment by ide** [comment]
I'm not sure it would be that much slower to do this optimization. If it's say ~5% slower I'd strongly be in favor of doing it in development too so that there are fewer discrepancies between dev and prod that could surface bugs.

**Comment by ericnakagawa** [comment]
Hi @aleclarson, have you found a workable solution for this issue? Perhaps with the introduction of Yarn, this becomes less of a concern? Please close if you no longer require this issue to be tracked.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/packager-content-addressed-module-deduplication-2
