### ISSUE TITLE
react-native-fcm:compileReleaseJavaWithJavac FAILED

### ISSUE THREAD

**Issue by jitenderchand1** [facebook/react-native#10014]
```
/Users/jitendra/Desktop/hostmakerco/ops-mobile/node_modules/react-native-fcm/android/src/main/java/com/evollu/react/fcm/FIRMessagingModule.java:30: error: FIRMessagingModule is not abstract and does not override abstract method onActivityResult(int,int,Intent) in ActivityEventListener
public class FIRMessagingModule extends ReactContextBaseJavaModule implements LifecycleEventListener, ActivityEventListener {
       ^
/Users/jitendra/Desktop/hostmakerco/ops-mobile/node_modules/react-native-fcm/android/src/main/java/com/evollu/react/fcm/FIRMessagingModule.java:158: error: method does not override or implement a method from a supertype
    @Override
    ^
Note: /Users/jitendra/Desktop/hostmakerco/ops-mobile/node_modules/react-native-fcm/android/src/main/java/com/evollu/react/fcm/FIRMessagingModule.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
:react-native-fcm:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-fcm:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

**Comment by satya164** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-4** [comment]
Hey @jitenderchand1 and thanks for posting this! @satya164 tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.

**Comment by wiadev** [comment]
@jimthedev I'm having same error. did you find a solution?

**Comment by jitenderchand1** [comment]
which version of react native are you using

**Comment by wiadev** [comment]
@jimthedev Thanks for quick response.
"react-native": "0.31.0",
"react-native-fcm": "^1.1.0",

**Comment by jitenderchand1** [comment]
Then check your react-native-fcm version. The document says
If you are running RN < 0.33.0, you need to user react-native-fcm@1.1.0
so use npm install react-native-fcm@1.1.0

**Comment by wiadev** [comment]
@jitenderchand1 my bad. I was using @1.1.1 . downgraded to 1.1.0 and works like a charm. Thanks.

**Comment by bkhurjawal** [comment]
I got the same issue, I solved it by commenting @override files in
node_modules/react-native-twitter-signin/android/src/main/java/com/goldenowl/twittersignin/TwitterSigninPackage.java:28
 
<img width="794" alt="screen shot 2017-09-15 at 12 12 27 pm" src="https://user-images.githubusercontent.com/11212401/30469710-32a83012-9a0f-11e7-8977-a5c7eadd3cdc.png">

Hope it helps!
