### ISSUE TITLE
Native Modules using swift can't work

### ISSUE THREAD

**Issue by J1aDong** [facebook/react-native#10010]
#### When I try to export Native Module using Swift , it can't work.I've got a lot of information，but it's still no use.(Objective-C can work well )

![](https://raw.githubusercontent.com/J1aDong/ReactNative-StepByStep/master/imgs/Slice.png)

```
MyModule.swift

import Foundation
@objc(MyModule)
class MyModule: NSObject {
  @objc func sayHi(msg:String!) -> Void {
    NSLog(msg)
  }
}
```

```
MyModule.m

#import "RCTBridgeModule.h"

@interface RCT_EXTERN_MODULE(MyModule, NSObject)

RCT_EXTERN_METHOD(sayHi:(NSString *)msg)

@end
```

```
ReactNativeStepByStep-Bridging-Header.h

#import "RCTBridgeModule.h"
```

```
SwiftNativeModule.js

import {NativeModules} from 'react-native';

export default NativeModules.MyModule;
```

```
...
SwiftNativeModule.sayHi("Hello swift");
...
```

### environment
* macos 10.12
* xcode 8.0
* simulator iphone6 10.10

#### Please tell me what is the cause of the error, thx.

**Comment by radko93** [comment]
Ask this question on Stackoverflow.

**Comment by FengDeng** [comment]
hi @J1aDong ,
I get the same error,do you resolve it?

**Comment by J1aDong** [comment]
@FengDeng   你好，我就不说英文了，今天搞定了，我猜测是swift3的关系，你可以参考[Got “is not a recognized Objective-C method” when bridging Swift to React-Native](http://stackoverflow.com/questions/39692230/got-is-not-a-recognized-objective-c-method-when-bridging-swift-to-react-native)，在swift的实现方法中添加前缀"_ "，我自己这边是可以正常跑通了。然后这边确实是个不该问问题的地方，但我当时就觉得可能是版本的原因,而官方的swift原生方法调用确实跑不起，所以想来问问是不是我版本太新的问题。如果方便，能留个qq吗，我可能会遇到些ios方面的问题来请教你。
