### ISSUE TITLE
Reload JS and extra options not showing for Xiaomi Redmi Prime 2

### ISSUE THREAD

**Issue by AbhishekPriyankar** [facebook/react-native#10024]
Even though I running `adb shell input keyevent 82` it is not showing the options.
Here are the Screen shots before and after running the command.
![screenshot_2016-09-21-21-27-35_com demoproject 1](https://cloud.githubusercontent.com/assets/11740384/18718856/87f6237c-8042-11e6-8bed-159a65311ee9.png)
![screenshot_2016-09-21-21-27-42_com demoproject 1](https://cloud.githubusercontent.com/assets/11740384/18718834/7aab53e0-8042-11e6-8e78-d1594f1d25ca.png)

**Comment by sbycrosz** [comment]
https://github.com/facebook/react-native/issues/2754
🎉

**Comment by narychen** [comment]
打开悬浮窗选项。

**Comment by narychen** [comment]
Open up the floating dialog permission in your app settings.  Xiaomi don't allow floating dialog by default.

**Comment by ericnakagawa** [comment]
Closing this issue as it has been inactive for several months and looks to have been resolved.
