### ISSUE TITLE
[Debug JS Remotely] [iOS] RCTJSONStringify error: Invalid number value (infinite) in JSON when debugging JS remotely

### ISSUE THREAD

**Issue by jozan** [facebook/react-native#10020]
### Issue Description

When using Animated, PanResponder and `perspective` I get the following error:

```
RCTJSONStringify() encountered the following error: Invalid number value (NaN) in JSON write
```
### Steps to Reproduce / Code Snippets

Example code can be found in `index.ios.js`: https://github.com/jozan/react-native-animated-perspective-problem/blob/master/index.ios.js
1. Clone the repo
2. Run it in iOS Simulator: `react-native run-ios`
3. Turn on "Debug JS Remotely" from developer menu
4. Drag the card left or right

You can toggle "Debug JS Remotely" on and off to see the error disappear and appear.

While "Debug JS Remotely" is on comment out line 65 `{ perspective: 400 }` to see the error disappear.
#### Expected Results

Should not produce error.
### Additional Information
- React Native version: `0.33.0`
- Platform(s) (iOS, Android, or both?): `iOS`
- Operating System (macOS, Linux, or Windows?): `OS X El Capitan (10.11.6)`
- Remote debugger: `Latest Google Chrome stable (53.0.2785.116 (64-bit))`

**Comment by jozan** [comment]
A note, does not crash on Android.

**Comment by dragonwong** [comment]
I met the same error. It seems that if the element is rotated by **90 deg**, the error will happen.

**Comment by jozan** [comment]
Doesn't crash anymore which is good but this still produces `console.warn` messages when reaching `90deg` while dragging. As per original bug report this is seen only when using Debug JS Remotely. This new behaviour doesn't seem to be related to `perspective` value so this might be another issue altogether.

Produced warning at `90deg`:
```
The value `touchEvent.locationX` equals NaN or INF and will be replaced by `0`.
```

Code can be found here: https://github.com/jozan/react-native-animated-perspective-problem/blob/master/app.js

Video demonstrating the warning:
https://streamable.com/wr4hx

### Steps to Reproduce

1. Clone the repo and install deps:
```
git clone git@github.com:jozan/react-native-animated-perspective-problem.git
cd react-native-animated-perspective-problem
yarn
```
2. Run it in iOS Simulator: `react-native run-ios`
3. Turn on "Debug JS Remotely" from developer menu
4. Drag the card left or right to about `90deg`.

### Additional information
React Native version: `0.47.0-rc.4`
Platform: iOS
Operating System: OS X Sierra (10.12.5)
Remote debugger: Google Chrome stable (59.0.3071.115 (Official Build) (64-bit)

**Comment by shamil707** [comment]
It is working for me,
After i reseting the node modules and IOS generated files...
