### ISSUE TITLE
Possible Unhandled Promise Rejection (id: 0): undefined is not an object (evaluating 'this.state.amount')

### ISSUE THREAD

**Issue by jainmitesh09** [facebook/react-native#10029]
### Issue Description

I cannot access the state variable in the promise resolver section, says undefined. 

But if i use a local variable just before using my promise, I can.

2016-09-21 10:38:41.253 [warn][tid:com.facebook.react.JavaScript] Possible Unhandled Promise Rejection (id: 0):
undefined is not an object (evaluating 'this.state.amount')
http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:1524:18
tryCallOne@http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:30463:10
http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:30549:19
http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:13394:18
callTimer@http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:13174:9
callImmediatesPass@http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:13273:28
callImmediates@http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:13288:43
http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:11984:57
guard@http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:11862:3
__callImmediates@http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:11984:6
http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:11951:24
guard@http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:11862:3
invokeCallbackAndReturnFlushedQueue@http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:11949:6
invokeCallbackAndReturnFlushedQueue@[native code]

**Comment by satya164** [comment]
You've a bug in your code. Please post your code on stackoverflow.

**Comment by satya164** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-4** [comment]
Hey @jainmitesh09 and thanks for posting this! @satya164 tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.

**Comment by xanview** [comment]
Did you post this on StackOverflow? - Any chance of a link? -- I'm experiencing the same after running react-native upgrade
