### ISSUE TITLE
[Android] No global URL object

### ISSUE THREAD

**Issue by JakeCoxon** [facebook/react-native#10025]
### Issue Description

The global URL object does not exist on Android. It is useful for parsing urls

### Steps to Reproduce / Code Snippets

On iOS this logs an object.
On Android when debugging remotely this logs an object
On Android when not debugging remotely it shows an error saying `Cannot find variable: URL`

```
console.log(URL);
```

#### Expected Results

I would expect the object to be there on Android and iOS to be consistent. However I'm not sure on the details, maybe it is a DOM thing. I'm sure there are many global objects that aren't included

### Additional Information

* React Native version: 0.33
* Platform(s) (iOS, Android, or both?): Android
* Operating System (macOS, Linux, or Windows?): macOS

**Comment by JakeCoxon** [comment]
Actually URL isn't there on iOS when I build in release either. I suppose this means I shouldn't use the API at all

**Comment by Etheryte** [comment]
Is the API documented anywhere, I can't seem to find it? That would be a good indicator that it's an internal API.

**Comment by satya164** [comment]
@Etheryte https://developer.mozilla.org/en/docs/Web/API/URL

**Comment by cbrevik** [comment]
`URL` was most likely available on iOS because you were connected to the remote debugger on Chrome. One option is installing https://www.npmjs.com/package/url instead.
