### ISSUE TITLE
How to resolve this problem that dismiss React-native back to ios native?

### ISSUE THREAD

**Issue by aemoe** [facebook/react-native#10036]
### Issue Description

How to resolve this problem that dismiss React-native back to IOS Native
### Expected Results

Find a way that React-native app can back to IOS native through a back button.
### Additional Information

React Native version: 0.33.0
Platform(s) (iOS, Android, or both?): iOS
Operating System (macOS, Linux, or Windows?): OS X El Capitan (10.11.6)
Remote debugger: Latest Google Chrome stable (53.0.2785.116 (64-bit))

**Comment by ericnakagawa** [comment]
Hi @aemoe, the issue you provided seems incomplete. I'll be closing since it's been over 3 months since the issue was submitted. I'm hoping you've found a solution since then.
