### ISSUE TITLE
TextInput cursor is not in the middle when textAlign is center

### ISSUE THREAD

**Issue by brunolemos** [facebook/react-native#10030]
### Issue Description

When using `TextInput` with `textAlign: center`, the cursor is in the wrong position when the text is empty. It seems to be aligning with the placeholder.

The user experiences the cursor jumping when it starts typing:

![Gif showing cursor in the wrong position](http://s16.postimg.org/fyqm7z1ol/26uf08_XSt1zf_E9_Vv2.gif)
### Steps to Reproduce / Code Snippets

``` jsx
<TextInput placeholder='NAME' style={{flex: 1, textAlign: 'center'}}/>
```
#### Expected Results

Input cursor should not be related to placeholder text.
Input cursor should always starts at the center when the text is empty.
### Additional Information
- React Native version: 0.33.0
- Platform(s) (iOS, Android, or both?): iOS
- Operating System (macOS, Linux, or Windows?): macOS

**Comment by Anuj-786** [comment]
hey @brunolemos, The cursor is not on wrong position its default property when you use the placeholder, the cursor starts from the start point it should not align at center if you are using the `textAlign: 'center'`.

**Comment by strindhaug** [comment]
So is this going to be fixed, or what?
It looks really weird when the cursor starts at the wrong position and jumps back once you start typing.
