### ISSUE TITLE
shadow props of parent shouldn't inherit to children element...

### ISSUE THREAD

**Issue by MeKarina** [facebook/react-native#10049]
### Issue Description

take a look at this screenshot...

![simulator screen shot sep 23 2016 3 59 26 am](https://cloud.githubusercontent.com/assets/15459370/18766349/04e8f6c8-8144-11e6-9698-e80b59ca0364.png)

take a look at `row3` text... it inherit shadow props from parent component `<View />`...
### Steps to Reproduce / Code Snippets

``` html
<View 
  key={id} 
  style={styles.box}
  shadowOffset={{height: 10}}
  shadowColor='black'
  shadowOpacity={0.5}
>
  <Text style={styles.text}>{title}</Text>
</View>
```
#### Expected Results

shadow props of parent shouldn't inherit to children element...
### Additional Information
- React Native version: latest
- Platform(s) (iOS, Android, or both?): ios
- Operating System (macOS, Linux, or Windows?): mac

**Comment by ericnakagawa** [comment]
Hi @MeKarina, checking in on this open issue. I'm hoping an updated version of RN has resolved this issue for you. I'll be closing the issue. If it still persists reopen the issue and I'll find someone to review.

**Comment by simonmitchell** [comment]
@ericnakagawa Which version of RN solved this? I'm running 0.40.0 now and still experiencing the same issue.

**Comment by skrjon** [comment]
I can reproduce this with transparent or RBGA backgrounds on my view using RN 0.43.4

```
import React from 'react';
import {
  StyleSheet,
  Text,
  View,
} from 'react-native';

export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
      	<View style={ styles.withShadow }>
      		<Text style={styles.text}>HELLO WORLD solid</Text>
      	</View>

        <View style={[styles.withShadow,{backgroundColor:'transparent'}]}>
          <Text style={styles.text}>HELLO WORLD transparent</Text>
        </View>

        <View style={[styles.withShadow,{backgroundColor:'rgba(33,33,33,0.05)'}]}>
          <Text style={styles.text}>HELLO WORLD rgba</Text>
        </View>

        <View style={[styles.withShadow,{backgroundColor:'rgba(33,33,33,0.05)'}]}>
          <Text style={styles.text}>HELLO WORLD rgba</Text>
        </View>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
  },
  text: {
    fontSize:24,
    color:'white',
    textAlign:'center',
  },
  withShadow: {
    margin: 20,
    height: 150,
    width: 150,
  	backgroundColor: '#EEE',
    borderWidth:1,
    shadowColor: "#000000",
    shadowOpacity: 0.85,
    shadowRadius: 5,
    shadowOffset: {
      height: 0,
      width: 0
    }
  }
});
```

![simulator screen shot apr 24 2017 10 54 47 am](https://cloud.githubusercontent.com/assets/132868/25351111/764ad1f2-28dc-11e7-96be-a2e9ffcbf7ba.png)

**Comment by iversondave-raizlabs** [comment]
Can we reopen this? Child element still seem to inherit their parent's shadows.

**Comment by otoinsa** [comment]
I have the same issue on RN 0.51

**Comment by karloluis** [comment]
I'll throw my hat in, the issue persists to this day and no fixes have been found.

**Comment by janustoth** [comment]
I am also experiencing this issue. This should be reopened.

**Comment by bigsassy** [comment]
0.53 and I'm also experiencing this issue.

**Comment by sanderfish** [comment]
Same here.

**Comment by deepu** [comment]
Please re-open this issue. I am experiencing this on 0.55.2 . 
Thankfully @sanderfish provided a temporary fix.

**Comment by jnrepo** [comment]
Noticing that when using @sanderfish it will work with `Text` children, but if the child is an `ImageBackground` it will still inherit the shadow.

react-native: 0.55.3

**Comment by eugene-kim** [comment]
Can we re-open this issue. On React-Native 0.55.0 and experiencing this bug as well.

**Comment by daemir** [comment]
Experiencing this issue as well, please re-open.

**Comment by iRayan7** [comment]
Please re-open. Thanks.

**Comment by GhizlaneA** [comment]
Same issue on 0.55.4 version

**Comment by gmverdon** [comment]
Having this issue as well

**Comment by jmelendev** [comment]
Same Issue.
