### ISSUE TITLE
WebView properties don't work if the app is launched via a Push Notificaiton

### ISSUE THREAD

**Issue by fernsheldon** [facebook/react-native#10044]
### Issue Description

Our app uses a `WebView` to load some part of our app. But we've stumbled across a scenario where the WebView properties don't work if the app has a "cold start" (i.e the app isn't in memory) via a Push Notification
### Steps to Reproduce / Code Snippets

Code snippet that I'm refering to :

```
render() {
    return(
         <View style={ styles.iosPadding }>
           <WebView
             source={{uri: 'https://github.com/facebook/react-native'}}
             onLoadEnd={() => {
               alert("Webpage Loaded !");
             }}
           />
         </View>
    );
  }
```

**When the application is launched normally:** We get to the React Native page and once the page is done loading we get the alert created in `onLoadEnd`

**App is launched via a remote push notification:** When the app is removed from memory by double clicking the home button and swiping the app away, and the user clicks on a Push Notification which launches the app - The page loads perfectly fine **BUT** the function `onLoadEnd` does NOT run.
#### Expected Results

All the properties of WebView should work as intended regardless of how the app was launched. 
### Additional Information
- React Native version: 0.33 
- Platform(s) (iOS, Android, or both?): iOS
- Operating System (macOS, Linux, or Windows?): macOS

**Comment by tarunmarkose** [comment]
Facing the same issue...

**Comment by fernsheldon** [comment]
It could be related to issue [8580](https://github.com/facebook/react-native/issues/8580).  In that thread the authors were also facing issues when the application was launched (cold start) via a local/remote push notification.

**Comment by ericnakagawa** [comment]
Hi @fernsheldon, haven't seen any updates on this issue in a while. I'll be closing it, but if the issue still persists reopen and I'll try to find someone to review.
