### ISSUE TITLE
WebSocket onmessage event is not triggered when the app is in background

### ISSUE THREAD

**Issue by narychen** [facebook/react-native#10046]
When you push home button to make your app in background, the network will not be shut down immediately both on android and ios. On ios it will be 10 minutes and on android it will last to app being killed.
But react-native app could not receive any message from websocket when it is in background until you turn it to foreground and then the onmessage event will be triggered.
I don't know if this is the problem caused by JSC which may be stopped after the app is turned to background. If it is, how to solve this problem ? Because I want to do local notification with it.

**Comment by narychen** [comment]
I tested it on an Android 6.0 phone, it's OK. But on ios and Android 4.3 phone, the onmessage event cannot be emitted. Seems like the js code stop running in the background.

**Comment by narychen** [comment]
I finally figure out the ios system will suspend your app's threads after it moves to background.
[reference](https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html#//apple_ref/doc/uid/TP40007072-CH4-SW23)
It seems hard to make react-native JSC running in background with beginBackgroundTaskWithExpirationHandler: method. Anyone got any ideas ?

**Comment by mschipperheyn** [comment]
You're probably trying to fight against an iOS policy. It could be an option to integrate with iOS global event messaging system. This way, you don't have to worry about the websocket being active all the time. Probably more battery friendly also.
