### ISSUE TITLE
[Packager] naïve concatenation of JS files breaks things

### ISSUE THREAD

**Issue by michaelficarra** [facebook/react-native#1005]
See https://github.com/tvcutsem/harmony-reflect/issues/47#issuecomment-96027244. A safe way to concatenate JS files would be to join on `"\n;"`, but that is not robust against potential future additions to the language (such as allowing unclosed trailing multiline comments).

**Comment by amasad** [comment]
What's the ideal way to do it?

**Comment by michaelficarra** [comment]
For scripts, there's no reliable way to combine two into the same file and preserve all semantics. For modules, you can just parse both programs and append the module items of the latter program to those of the former.
