### ISSUE TITLE
Terminal react-native run-ios,run-android  not working

### ISSUE THREAD

**Issue by hnsylitao** [facebook/react-native#10056]
Terminal react-native run-ios,run-android  not working
- React Native version: [0.33.0]
- Platform(s) (iOS, Android, or both?): [IOS,Android]
- Operating System (macOS, Linux, or Windows?): [macOS]

**Comment by hnsylitao** [comment]
![image](https://cloud.githubusercontent.com/assets/17537749/18807730/90b09d6c-8281-11e6-9370-225426f5e01a.png)

**Comment by hnsylitao** [comment]
![image](https://cloud.githubusercontent.com/assets/17537749/18807733/b9bcded2-8281-11e6-869f-6a0f78da140e.png)

**Comment by Kuzmin** [comment]
Does the `react-native run-ios` command just hang like that or does it give error output after a while? Same question for `react-native run-android`? 

Have you recently upgraded to the latest macOS? I know this usually causes some terminal commands to stop working, so maybe it's something like that hidden underneath.

**Comment by hnsylitao** [comment]
![image](https://cloud.githubusercontent.com/assets/17537749/18808357/7ae4fb98-8292-11e6-9d82-3b1c7cc14a07.png)

**Comment by hnsylitao** [comment]
@Kuzmin 
![image](https://cloud.githubusercontent.com/assets/17537749/18808366/af7f2b80-8292-11e6-9bff-8528c66cf961.png)

**Comment by hnsylitao** [comment]
watchman 4.7.0 
After uninstall watchman run normal
But app opens the flash back

**Comment by hnsylitao** [comment]
uninstall watchman
![notwatchman](https://cloud.githubusercontent.com/assets/17537749/18808707/5c08806e-829c-11e6-96f4-f7831c97384d.gif)

**Comment by hnsylitao** [comment]
install watchman
![watchman](https://cloud.githubusercontent.com/assets/17537749/18808716/7e52f7bc-829c-11e6-8d97-2589be5d04f0.gif)

**Comment by hnsylitao** [comment]
https://github.com/facebook/watchman/issues/358
watchman v4.7.0

**Comment by Kuzmin** [comment]
Looks like it's some kind of issue with watchman then, I suppose. Good debugging, makes it easier for the dev team to fix! Now we just need to wait for them to see the issue. (I'm not actively contributing code, just trying to help out triaging issues.) 😄

**Comment by anggao** [comment]
saw the same issue

**Comment by nemophrost** [comment]
https://github.com/facebook/react-native/blob/9ee815f6b52e0c2417c04e5a05e1e31df26daed2/packager/react-packager/src/node-haste/FileWatcher/index.js#L20

`watchman version` functionality has changed in 4.7
the process doesn't end so the code never executes pas line 26

**Comment by pelle** [comment]
I was able to get it working using the instructions here https://github.com/facebook/watchman/issues/376 : 

```bash
sudo launchctl unload -F ~root/Library/LaunchAgents/com.github.facebook.watchman.plist
```

Don't know enough about watchman to understand why it was running as a service. But it worked anyway.

**Comment by amZotti** [comment]
Uninstalling and reinstalling Watchman fixed this issue for me.

**Comment by ivosabev** [comment]
This is retarded, `react-native` doesn't show any feedback on what is not working within its internals, there is no `--verbose` flag either.
