### ISSUE TITLE
[Android] ReadableNativeMap toHashMap cannot be used in unit tests

### ISSUE THREAD

**Issue by hey99xx** [facebook/react-native#10052]
### Issue Description

See https://github.com/facebook/react-native/issues/4655 . The way this unwrapping readablemap and readablearray are implemented cannot be used in unit tests as  the method is written in the class implementing the interface, but not in the interface.

In unit tests people should be able to test their native modules with JavaOnlyMap. But this commit forces people to cast a ReadableMap to ReadableNativeMap.

My comment to 4655

> The commit should have likely been on ReadableMap, not on ReadableNativeMap (same applies for the array equivalents). The way it's written means the user has to cast ReadableMap into ReadableNativeMap before calling toHashMap. Although this would normally be ok, for anyone using JavaOnlyMap in their unit tests to mock their native modules (like me) this is a huge annoyance.

At the bottom of https://github.com/facebook/react-native/pull/4658 this issue is also noted by @Kerumen and @yarivkenan
#### Expected Results

Should be used in unit tests, cannot be used in unit tests.
### Additional Information
- React Native version: All
- Platform(s) (iOS, Android, or both?): Android
- Operating System (macOS, Linux, or Windows?): All
- Severity: minor annoyance

**Comment by christopherdro** [comment]
@facebook-github-bot icebox

**Comment by Kerumen** [comment]
@christopherdro What is "icebox" ?

**Comment by cestarid** [comment]
What's stopping us from adding `toHashMap` and `toArrayList` to the `ReadableMap` and `ReadableArray` interfaces? It cannot be used for `JavaOnlyMap` and `JavaOnlyArray`, since the methods are in the `ReadableNative*` implementations only.

**Comment by igalmizrahi** [comment]
@dcestari has sent a PR to fix this in https://github.com/facebook/react-native/pull/14072/commits/06cf5d3add212d4855a2c2c9f55b5b1926888761
