### ISSUE TITLE
ReferenceError: Can't find variable require on device

### ISSUE THREAD

**Issue by ZakosDim** [facebook/react-native#10064]
Hello i am trying to run the sample app on my phone but i am facing some problems.
Firstly i start the server: react-native start
I install the app in my phone: react-native android run.
The app is installed. When i open the app from the phone i have a red screen that says no variable require. The ip and the port are correct.

![screenshot_2016-09-23-17-38-07](https://cloud.githubusercontent.com/assets/5075999/18789848/2cc322f6-81b5-11e6-8d40-d5c51dc8882b.png)

same thing in the emulator
![image](https://cloud.githubusercontent.com/assets/5075999/18795048/4948d388-81cb-11e6-8d1c-7c2214864423.png)

line 15:
'use strict';var _create=require('babel-runtime etc etc ...

**Comment by ZakosDim** [comment]
Any idea?

**Comment by ericnakagawa** [comment]
I am closing this issue since it's been inactive for several months. If the issue still persists please open a new issue with steps to reproduce.
