### ISSUE TITLE
onTouchStart, onTouchMove and onTouchEnd aren't true multi-touch

### ISSUE THREAD

**Issue by robclouth** [facebook/react-native#10068]
I'm using RN 0.33.
The onTouchStart, onTouchMove and onTouchEnd props of View aren't multi-touch. You can't control two at the same time which heavily restricts their usefulness!
For example, it's impossible to create two sliders that can be controlled independently.

**Comment by hey99xx** [comment]
They certainly are multi touch, they give you entire touch history on the screen. See https://facebook.github.io/react-native/docs/gesture-responder-system.html for more detailed information on touches including 

> changedTouches - Array of all touch events that have changed since the last event

> touches - Array of all current touches on the screen

Now creating two touchable sliders might a bit more difficult since if they are separate views, they would likely cancel each other. That's why React gives you ability to create your own native  view subclasses  and add your gesture events. The MapView example at https://facebook.github.io/react-native/docs/native-components-ios.html can certainly accept multi touch gestures.

**Comment by robclouth** [comment]
This is what I'm talking about sorry, multi-touch over separate views. The fact that you have to create a native view to be able to press two buttons at the same time seems like a fundamental limitation, and unnecessarily restricts the utility. So you're saying there's no pure RN way of reacting simultaneously to gestures on different view simultaneously?

**Comment by robclouth** [comment]
Sorry @hey99xx could you just confirm that there's no way to control two views at the same time with pure RN? It's not possible to bypass all the responder stuff and hook straight into touch events coming from the native views?

**Comment by hey99xx** [comment]
Hey Rob. I'm not a FB employee or a contributor, so don't take my word :)

With <Touchable> components, I'm pretty sure there is no way. They hook themselves into the global responder system and receive rejections / grants, so only one <Touchable> component will be receiving an event at all times.

Hooking straight into touch events might work. I've investigated a little into it earlier, but my problem was different (I was trying to find how to terminate responders from native side similar to how scroll view drag gesture works). 

If there is a way, you will likely need an extensive look at https://github.com/facebook/react/tree/15-dev/src/renderers/shared/stack/event and especially https://github.com/facebook/react/blob/15-dev/src/renderers/shared/stack/event/eventPlugins/ResponderEventPlugin.js where all responder rejections / grants etc happen.

**Comment by robclouth** [comment]
Yeah I know it's impossible with Touchables, but I've had some success with hooking into the onTouchX methods directly on Views. But this doesn't work on android.
Thanks for your help!

**Comment by aleclarson** [comment]
@robclouth Did you ever resolve your issue? Or could you confirm that multi-gesture support is not currently implemented?

Once @kmagiera finishes his work on [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler), that might be the solution (which is to not use React's JS responder system at all).

**Comment by robclouth** [comment]
Hey. Basically multiple touches on separate views works on iOS, using the ```onTouchMove``` View prop. But it doesn't work on android. I've had to make a native wrapper component.

**Comment by aleclarson** [comment]
That's not ideal, considering you don't get separate `on{Start,Move}ShouldSetResponder{Capture}` or `onResponder{Grant,End}` or terminate events.

I whipped up some commits to support multiple views handling gestures simultaneously:

[21d98bf](https://github.com/aleclarson/react/commit/21d98bf5499c95cfd1a4be83e8b2536daf1d0c4f) - Adds `ResponderCache` to [facebook/react](https://github.com/facebook/react)

[0116996](https://github.com/aleclarson/react-native/commit/01169966be4631f945c84318bbc82e9605093253) - Allows multiple JS responders in RCTUIManager

I haven't done anything on Android yet. And I haven't tested them with `PanResponder` or `Touchable`, so please let me know if things work for you. I'm currently testing the changes with my own JS gesture library.

**Comment by aleclarson** [comment]
Alright, I finished all the necessary work (no test suite yet) and updated the commit SHAs in the above comment. If you get the chance, let me know if `PanResponder` and/or `Touchable` work with the changes.

Cheers 🍻
