### ISSUE TITLE
RN 0.34.0 and Nuclide 0.170.0 : UI performance is so bad with Android and iOS (Device & Simulator)

### ISSUE THREAD

**Issue by JobsSteve** [facebook/react-native#10066]
### Issue Description

After upgrade my project with v0.31.0 react-native, my app runs slow in Android device.
But I found that the GridView scroll performance is OK. 
The click event and Navigator or TabbarNavigator is so so so slow to react.
I do not know why. It runs well in previous version.
Hope for your help! 
Thanks.
### Additional Information
- React Native version: 0.31.0
- Platform(s) (iOS, Android, or both?): Android
- Operating System (macOS, Linux, or Windows?): macOS

**Comment by JobsSteve** [comment]
I have also tested on iOS.
Same problem. The app has nothing but only UI components with Navigator and some Views.
It may run smoothly for a while, then the app stuck and slow.

**Comment by Kuzmin** [comment]
Do you think you could upgrade to 0.34 and see if this problem persists? It could help the developers diagnose if this is an existing problem or just a commit that needs to be backported.

**Comment by unuigbee** [comment]
I've recently upgraded to 0.34 and the UI response is really slow and not fluid at all e.g.For something like an onChange event on a TextInput reflecting in the UI as text changing within a Text View.

**Comment by satya164** [comment]
Can you provide a code sample please? I'm on `0.33` and performance is the same for me.

**Comment by JobsSteve** [comment]
I found out that the RAM is keeping upgrowing. Though I update to v0.34.0

**Comment by JobsSteve** [comment]
@Kuzmin

**Comment by slicejunk** [comment]
I use NavigationExperimental / RN 0.34.1 and the navigation is terribly slow with Android.
It seems ok with IOS.

**Comment by thedjinn** [comment]
Same issue here with RN 0.34.1 on iOS. Frame rate is about 1 fps, but it only happens when I compile in debug mode. Release mode builds have silky smooth animations.

**Comment by lacker** [comment]
I think if your app is slow then you have to profile it to figure out what's going on, or just add print statements. And then if an individual component is performing poorly or if you can generate poor performance from a really simple sample app then it would demonstrate the problem is in React Native itself and it's a bug. Until then I wish you luck but I think this issue is unactionable. Thanks for bringing this up though!
