### ISSUE TITLE
TaskQueue fetch undefined

### ISSUE THREAD

**Issue by gendeld** [facebook/react-native#10087]
React-Native v0.31

When trying to call fetch inside of  InteractionManager.runAfterInteractions, i get the following error:
<img src="https://lh4.googleusercontent.com/OyqsU9HjlY__i5O1ZdpauKg1uwNU_WWVWzlU4SmPI00ovU25iKBuB_7b1Dh7DpQDnseIVA4_=w1920-h950-rw" />

Code: 

```
 componentDidMount() {
    Orientation.lockToPortrait();
    this.state.screenHeight=Dimensions.get('window').height;
    this.state.screenWidth=Dimensions.get('window').width;
    InteractionManager.runAfterInteractions(() => {
      this.fetchData();
    });
  }

  fetchData() {
    fetch(REQUEST_URL)
      .then((response) => response.json())
      .then((responseData) => {
        for(var i=0; i<responseData.length; i++)
        {
          if(responseData[i].defType=="Movies")
          {
            this.setState({
              dataSource: responseData[i].defVal,
              loaded: true,
            });
            break;
          }
        }
      })
      .done();
  }
```

Thanks in advance for the help,
Daniel.

**Comment by lacker** [comment]
I think this got no response because the paste of the error is broken. I am going to close this issue for lacking sufficient information but if you do have a repro of this - I suggest a rnplay.org link - then feel free to open a new issue.
