### ISSUE TITLE
[Android] JS not being fully reloaded after user close the app via back button

### ISSUE THREAD

**Issue by sbycrosz** [facebook/react-native#10089]
### Issue Description

JS not being fully reloaded after user close the app via back button
### Steps to Reproduce / Code Snippets

``` js
// index.android.js

import React, { Component } from "react";
import { View, AppRegistry } from "react-native";

console.log("loading source..");

class Example extends Component {
  componentDidMount = () => {
    console.log("mounting example");
  };
  render() {
    return (
      <View>
      </View>
    );
  }
}

AppRegistry.registerComponent("example", () => Example);

```

The first time the user open the app, it will print both messages.
After the user closes the app via back button, and reopen the app, it will:
- on **RN0.33+** only prints `"mounting example"` message (which means the JavaScript sources was not fully reloaded.)
- on **RN0.32** it will print both messages.
#### Expected Results

I think both messages should be printed. because closing via back button should trigger the same effect as closing the app via app switcher (which make sure everything is clean as whistle). 

And also this will break some library that require setup before the element are rendered. 

e.g. 
- https://github.com/AlexanderZaytsev/react-native-i18n needs to load the i18n before rendering, so it could get the proper translation before the first component is rendered
- **Edit**: It would also break https://github.com/Microsoft/react-native-code-push because the new code-pushed bundle is not being reloaded at all (or at least until the app is killed)
### Additional Information
- React Native version: 0.33+
- Platform(s) (iOS, Android, or both?): Android
- Operating System (macOS, Linux, or Windows?): macOS

edit: This happens for both debug & release build

**Comment by ide** [comment]
> closing via back button should trigger the same effect as closing the app via app switcher

Is this true? My understanding was that Android keeps the app alive and backgrounds it when you tap the back button in order to conserve battery life and preserve application state.

**Comment by sbycrosz** [comment]
> > closing via back button should trigger the same effect as closing the app via app switcher

> Is this true? My understanding was that Android keeps the app alive and backgrounds it when you tap the back button in order to conserve battery life and preserve application state.

I'm only speaking in term of the initial view rendering process. Which on RN033+ looks like this:

- **Initial Launch:** "load JS bundle" -> render
- **After closing w/ back button:** "use JS bundle that've been loaded before w/o reloading" -> render

And also even though the app is still alive on background, the component will be unmounted and you'll want a freshly loaded JS bundle to render the next time anyway

**Comment by sbycrosz** [comment]
It seems code-push has a different issue all together..
I guess the most annoying thing with this issue is that developers need to make sure to clean up their singleton/globals when the root component is unmounted..

**Comment by saleeh93** [comment]
@sbycrosz @ide does it got fixed .?

**Comment by sbycrosz** [comment]
I've reverted to 0.32 for our latest release. But then I'm not really sure if this still an issue b/c the code-push one is a different issue all together.

Have you encountered this @saleeh93 ?

**Comment by saleeh93** [comment]
@sbycrosz I had different issues where i get my navigator gots unmounted and i was keeping the reference to the old navigator , I got fixed that by setting null on componentWillUnmount

**Comment by lacker** [comment]
It sounds like nobody is left with this issue so I am going to close it.
