### ISSUE TITLE
 syntaxError:Unexpected keyword 'import'      Import the react-native in the existing project.   ios

### ISSUE THREAD

**Issue by Bintong** [facebook/react-native#10096]
tip syntaxError:Unexpected keyword 'import'

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';

class SimpleApp extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit index.ios.js
        </Text>
        <Text style={styles.instructions}>
          Press Cmd+R to reload,{'\n'}
          Cmd+D or shake for dev menu
        </Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

AppRegistry.registerComponent('SimpleApp', () => SimpleApp);
### but user

'use strict';

var React = require('react-native');
var {
  Text,
  View
} = React;

var styles = React.StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'red'
  }
});

class SimpleApp extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <Text>This is a simple application.</Text>
      </View>
    )
  }
}
React.AppRegistry.registerComponent('SimpleApp', () => SimpleApp);

is ok ,
how to do

**Comment by hey99xx** [comment]
Please ask in Stackoverflow, you should use Github issues for feature requests / bug reports etc., not questions about your own debugging. It looks like your packager is not transpiling `import` into what it needs to be, but no one will be able to debug with this much information anyways.

**Comment by lacker** [comment]
Closing this issue - I think hey99xx's diagnosis is accurate here.
