### ISSUE TITLE
no simple way to provide executorClass to RCTBridge

### ISSUE THREAD

**Issue by jwyld** [facebook/react-native#1009]
The property can be set after -initWithBundleURL:moduleProvider:launchOptions:, but that requires a -reload which can't be performed until the original load from -setUp is finished.  That's a lot of latency.  

An initial reaction would be to subclass RCTBridge and set the executorClass early.  The problem here is that -setUp is called from the designated initializer which means the first safe time to set it is after it's use.

The next reaction would be to override -executorClass.  The problem is -setUp directly accesses the ivar instead of using the accessor.

**Comment by ide** [comment]
See issue #288 and PR #652.

**Comment by nicklockwood** [comment]
We have a solution in mind for this, but it's not really supported at the moment. Using @ide's PR is an good option if you need it right now.

I'm curious why you need it by the way? (just so I can keep track of the real-world requirements for when we do ship a solution).

**Comment by nicklockwood** [comment]
Ah, I'm guessing it relates to this: https://github.com/facebook/react-native/issues/1010

**Comment by brentvatne** [comment]
Can we close this @nicklockwood, @ide?

**Comment by jwyld** [comment]
Based upon changes on master (actually in latest release), things are good for my needs.

**Comment by brentvatne** [comment]
Thanks @jwyld!
