### ISSUE TITLE
lgnoring return value of function declared.....

### ISSUE THREAD

**Issue by XingdaLee** [facebook/react-native#10104]
![image](https://cloud.githubusercontent.com/assets/12740778/18824980/a1b26f00-83f8-11e6-95ea-cd5ea147fc46.png)
![image](https://cloud.githubusercontent.com/assets/12740778/18824984/a4c1edf6-83f8-11e6-89ae-f4435880451c.png)

**Comment by kisalove** [comment]
Just doubleclick on the RCTWebSocket project in your navigator and remove the flags under build settings > custom compiler flags

https://github.com/facebook/react-native/issues/8584

**Comment by ericnakagawa** [comment]
Hi @XingdaLee, I'm closing this issue since @euyuhz mentioned that this issue may be resolved and there hasn't been any activity on it in a couple month. If this issue still persists reopen and I'll track down someone to review.
