### ISSUE TITLE
Can't use React Native on Windows

### ISSUE THREAD

**Issue by grahammendick** [facebook/react-native#10107]
When I call `react-native init` I get the error `EPERM: operation not permitted, rename` (I'm using the latest Node version and have tried the standard fixes, like running the command window as Adminstrator, but with no luck). I suspect this is an npm issue because I've encountered it outside of React Native when running `npm install`. But I could always work around it before by repeatedly calling `npm install` with `npm cache clear` in between each call. But, with React Native I can't do that because the error is happening within the `react-native init` call.

Could you provide an alternative way to create a React Native project on Windows, please? Perhaps one that gives me a chance to issue `npm cache clear` calls between steps?

**Comment by rmevans9** [comment]
You could pull one of the many many boilerplates and then it would just be a simple 'npm install' call.

**Comment by grahammendick** [comment]
Thanks for the idea. I wondered about that myself, but there's more to it than the `npm install`. What about the other files that the `react-native init` command creates? If I took a 'HelloWorld' boilerplate and want to create a project called 'FooBar', can I safely find and replace HelloWorld with FooBar everywhere?

**Comment by rmevans9** [comment]
Yeah, you would have to change it in a few places. A thought there might actually be update package.json with the new project name and then run 'react-native upgrade' which basically wipes out all the projects and such and I believe it keys off the name from package.json. If that doesn't work then finding the name in all the right places (android, iOS, JS code, etc) should do the trick.

**Comment by grahammendick** [comment]
It would be good if the React Native docs could list the steps for a 'manual' installation in case the `react-native init` fails. But, I'll give the `react-native upgrade` a go.

**Comment by grahammendick** [comment]
Still no luck. I get the same error `EPERM: operation not permitted, rename` when I just run `npm install react-native`. Before the error happens, the console logs the following:
````
\> MyProject\node_modules\react-native\node_modules\yeoman-generator\node_modules\cross-spawn\node_modules\spawn-sync
\> node postinstall
````

**Comment by rmevans9** [comment]
Might want to check out a few other issues from other repos that had similar issues:

https://github.com/Medium/phantomjs/issues/19
https://github.com/npm/npm/issues/10826

**Comment by grahammendick** [comment]
Thanks. I've tried both npm cache clean and turning off anti-virus, but neither worked

**Comment by grahammendick** [comment]
Upgraded to npm v2.15 (comes with latest node) and still get `rename` error, but it's in a different place this time. The file it's renaming has changed from package.json to package.tgz as per https://github.com/npm/npm/issues/9696#issuecomment-208705601. (Reading through that issue suggests it only shows up on machines with slow I/O). 
Although this isn't strictly a React Native error, I think that React Native should provide a workaround so that many Windows users aren't excluded.

**Comment by grahammendick** [comment]
I've made some progress.

After updating npm to latest version (3.10.8) `react-native init` works.
But now `react-native run-android` fails.
It didn't help that the [Android setup instructions had been incorrectly removed](https://github.com/facebook/react-native/pull/9867). I had trouble following the instructions because Android Studio failed to install the Google APIs and Intel System Images under the SDK Platforms. But I don't think that's what's causing my current problem:

First off I got the error `failed to find target with hash string 'android-23'` but [I updated the build.gradle](https://github.com/facebook/react-native/pull/9867#issuecomment-249439631) to remove that error.

**But now I've got the `IllegalStateException: buildToolsVersion is not specified`. I thought I could fix this by [setting the buildToolsVersion in the build.gradle](https://github.com/facebook/react-native/pull/9867#issuecomment-249439631). I set it to 24.0.2, which matches my Android install from what I can see, but that didn't work.**

**Comment by grahammendick** [comment]
Finally got it working. Here's what I had to do:

* Install latest npm (anything < 3 doesn't work)
* Follow the mandatory steps in [Getting Started](http://facebook.github.io/react-native/releases/0.28/docs/getting-started.html). Note: this has crucial information not in the current online getting started guide
* Change compileSdkVersion from 23 to 24 in build.gradle in MyProject\android\app. It should match the number in the folder C:\Users\YourName\AppData\Local\Android\sdk\platforms\android-24
