### ISSUE TITLE
Since 0.34, every TextInput has unnecessary bottom border on Android

### ISSUE THREAD

**Issue by huston007** [facebook/react-native#10108]
### Issue Description

Every TextInput has unnecessary bottom border

### Steps to Reproduce / Code Snippets

Just try TextInput on android.
My styles: 
```
    height: 30,
    marginTop: 8,
    marginBottom: 8,
    backgroundColor: '#FFF',
    color: '#7E7E84',
    fontSize: 14,
    borderBottomColor: '#FE0082',
    borderBottomWidth: 1
```
That looks like this:
<img width="405" alt="screen shot 2016-09-26 at 12 31 34" src="https://cloud.githubusercontent.com/assets/4318513/18829564/850dddde-83e5-11e6-82c0-07556ad51cf4.png">

#### Expected Results

As before 0.34, TextInput should only has that border I described in styles, but not unnecessary own border.

### Additional Information

* React Native version: 0.34
* Platform(s): Android
* Operating SystemL macOS

**Comment by Kerumen** [comment]
It's the default on Android, if you want to disable it you can set `underlineColorAndroid` to `transparent`. From [the docs](http://facebook.github.io/react-native/releases/0.34/docs/textinput.html#textinput):

> `TextInput` has by default a border at the bottom of its view. This border has its padding set by the background image provided by the system, and it cannot be changed. Solutions to avoid this is to either not set height explicitly, case in which the system will take care of displaying the border in the correct position, or to not display the border by setting `underlineColorAndroid` to transparent.

**Comment by huston007** [comment]
@Kerumen Okay, sorry for bothering. Thank you, that works.
