### ISSUE TITLE
0.33 Android MainActivity.onActivityResult masks events from modules 

### ISSUE THREAD

**Issue by weixingsun** [facebook/react-native#10101]
Hi RN Developers,

The RN 0.33 breaks lots of modules due to the ActivityEventListener interface introduced.
Problem 1: 
  My app starts to crash until I override MainActivity.onActivityResult and implements ActivityEventListener, showing error like "abstract method: void com.facebook.react.bridge.ActivityEventListener.onActivityResult(android.app.Activity, int, int, android.content.Intent)", is this by design ?
Problem 2: 
  If it is by design, ok, let's move forward. Why my modules like image-picker cannot receive the event when I follow the instruction: http://facebook.github.io/react-native/releases/0.34/docs/native-modules-android.html#getting-activity-result-from-startactivityforresult
  It is supposed to be working since I added listener to my module: reactContext.addActivityEventListener(this);

  Interesting things happens when I remove MainActivity.onActivityResult method, I can see modules events are triggered in log files. (but my app crashed)
**MainActivity.java**
    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) { **//this is called**
        MainApplication.getCallbackManager().onActivityResult(requestCode, resultCode, data);
    }
    @Override
    public void onActivityResult(Activity activity, int requestCode, int resultCode, Intent data) { **//not called**
        MainApplication.getCallbackManager().onActivityResult(requestCode, resultCode, data);
    }

Problem 3:
  so if the above behaviors are all by design, so it means I have to rewrite every module for handling the onActivityResult function (move it into the MainActivity.onActivityResult right?) It's not so friend to add handler codes for every modules, and it'll breaks many existed module designs.

**Is there an example works for the Intent event solution?**

or maybe the workarounds should like either:
1. no need to implement ActivityEventListener.onActivityResult method in MainActivity. It may be the easiest way to keep all the old modules working
2. don't mask the event listened by modules, 

Thanks

**Comment by Vani-gurnani** [comment]
+1

**Comment by beast** [comment]
+1

**Comment by satya164** [comment]
Related - https://github.com/facebook/react-native/commit/fbd2e139103e3d520f6dfc009d6200f8b8168e35

cc @foghina

**Comment by bhaskarmurthy** [comment]
+1

**Comment by foghina** [comment]
For some reason my updated docs went out for version `0.35`. However, it seems I didn't update the long code example, only the first section:

http://facebook.github.io/react-native/releases/0.35/docs/native-modules-android.html#getting-activity-result-from-startactivityforresult

Off to updating the long code example as well, sorry about that.

Hints: extend `BaseActivityEventListener` instead of implementing `ActivityEventListener`. Do not override `onActivityResult` in your activity. Your `onActivityResult(Activity, int, int, Intent)` should then be called correctly.

**Comment by SilVdB** [comment]
I have the same problem at the moment, using [react-native-awesome-card-io](https://github.com/Kerumen/react-native-awesome-card-io). The onActivityResult in MainActivity.java is called in stead of the one in the module, and this is still the case when I use the change @foghina proposed above. Has anyone been able to find a fix already?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/033-android-mainactivityonactivityresult-masks-events-from-modules
