### ISSUE TITLE
Crash in RN 0.34.1

### ISSUE THREAD

**Issue by philipheinser** [facebook/react-native#10100]
### Issue Description

Crash during transition.
### Steps to Reproduce / Code Snippets

Happens when we transition to a route with a view pager.
#### Expected Results

no crash.
### Additional Information
- React Native version: 0.33.0-0.34.1
- Platform(s) (iOS, Android, or both?): Android
- Operating System (macOS, Linux, or Windows?): macOS

`
Error while updating property 'transform' of a view managed by: RCTView
updateViewProp
    ViewManagersPropertyCache.java:88
setProperty
    ViewManagerPropertyUpdater.java:123
updateProps
    ViewManagerPropertyUpdater.java:42
updateProperties
    ViewManager.java:34
updateProperties
    NativeViewHierarchyManager.java:121
execute
    UIViewOperationQueue.java:91
run
    UIViewOperationQueue.java:782
flushPendingBatches
    UIViewOperationQueue.java:829
access$1500
    UIViewOperationQueue.java:44
doFrameGuarded
    UIViewOperationQueue.java:868
doFrame
    GuardedChoreographerFrameCallback.java:32
doFrame
    ReactChoreographer.java:131
run
    Choreographer.java:869
doCallbacks
    Choreographer.java:683
doFrame
    Choreographer.java:616
run
    Choreographer.java:857
handleCallback
    Handler.java:751
dispatchMessage
    Handler.java:95
loop
    Looper.java:154
main
    ActivityThread.java:6077
invoke
    Method.java:-2
run
    ZygoteInit.java:865
main
    ZygoteInit.java:755

`

**Comment by philipheinser** [comment]
@facebook-github-bot label Android

**Comment by Rambos** [comment]
+1
0.33.0 have this problem

**Comment by rmevans9** [comment]
@philipheinser you have to be added to the IssueCommands text file to have the bot listen to you.

**Comment by rmevans9** [comment]
@facebook-github-bot label Android

**Comment by arilitan** [comment]
Having this problem as well

**Comment by lacker** [comment]
Hey, I think this issue does not have enough information to let people reproduce the problem. It has also been stale for a while. I am going to close this issue but if folks have a rnplay.org repro of the bug then I encourage them to open a new issue.
