### ISSUE TITLE
TextInput doesn't work with placeholderTextColor and conflict to transparent

### ISSUE THREAD

**Issue by ele828** [facebook/react-native#1011]
1. The placeholderTextColor props doesn't work.
2. When I set the `Input` 's style of backgroundColor to `transparent`, the Placeholder words is gone.
![image](https://cloud.githubusercontent.com/assets/8534639/7330959/aea24956-eb2e-11e4-9b52-17e1805688d3.png)

**Comment by brentvatne** [comment]
See #997 - try pulling down that diff to see if it fixes your problem

**Comment by ele828** [comment]
@brentvatne  Yes, it works well. Whether transparent or solid background. thanks

**Comment by drkibitz** [comment]
When using experiementing  with an earlier version of react-native I made an implementation of placeholder that was different than this, but find it useful. Basically `placeholder` propType is an object with shape of `{text: string, {fontSize: number, fontStyle: string, fontWeight: number, fontFamily: string}`. This way it's a unified prop. Then on the UIKit side, all font attributes default to properties in `self.font` or `defaultView.font`.

If anyone is interested in this, happy to make a PR.

**Comment by brentvatne** [comment]
cc @vjeux ^

**Comment by vjeux** [comment]
A more React Native-like api would be

<TextInput placeholderText="abc..." placeholderStyle={{ color: 'red' }} />

Where placeholderStyle overrides style attributes

**Comment by brentvatne** [comment]
Thanks @vjeux, that looks good to me

**Comment by bimawa** [comment]
I, too, is more like it. I could take up the implementation of styles for textInput.
