### ISSUE TITLE
<Text> lineHeight changes when onPress is called on a contained larger <View> element

### ISSUE THREAD

**Issue by bollogo** [facebook/react-native#10116]
### Issue Description

When having a View element within a Text element with a defined height, that is larger than the line height of the parent text element, and having an onPress function in the surrounding Text element, a click on the issue element changes the line-height for all text within the parent element.

Before click:
![textbug_before](https://cloud.githubusercontent.com/assets/18519861/18839283/b60770b0-840a-11e6-8208-cb721e7ded10.png)

After click:
![textbug_after](https://cloud.githubusercontent.com/assets/18519861/18839288/b94234c2-840a-11e6-96c0-a9945ddaff4f.png)

See images below:
### Steps to Reproduce / Code Snippets

The following Component reproduces this error. Simply start the iOS simulator and click on the red box element.

``` javascript
class TestComponent extends Component {
    constructor(props) {
        super(props);
    }

    _onRefresh() {
    }

    render() {
        return (<Text style={{width: 300}}>
                <Text>
                Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est.
                <Text>
                <Text onPress={this._onRefresh.bind(this)}>
                <View style={{width: 100, height: 100, backgroundColor: 'red'}}></View>
                </Text>
                </Text>
                </Text>
                </Text>);
}
```
#### Expected Results

The layout of the text should stay the same, only the line which contains the view have the line height equal to the view height.
### Additional Information
- React Native version: only tested on 0.32 so far
- Platform(s) (iOS, Android, or both?): only tested on iOS so far
- Operating System (macOS, Linux, or Windows?): macOS

**Comment by lacker** [comment]
It's not clear to me that the expected results are actually what's expected here. We basically do not document `View` inside `Text` and it seems to be not the behavior that people expect reasonably often. Not sure what to do to make progress here.

**Comment by bollogo** [comment]
What I find unexpected is the fact that when I press a button, the layout changes event though the same state produces a different layout on a user interaction.

**Comment by lacker** [comment]
I asked around and I think `View` inside a `Text` does not have well-defined behavior. I would recommend avoiding that sort of setup. Is it possible to implement this UI without having a view inside a text element? (We should really document this better, too.)

**Comment by bollogo** [comment]
Using `Views` inside of `Text` is nice for things such as buttons or embedding images. The issue is with text flowing nicely around the embedded view. Of course one can use an embedded html view, but that has other issues such as autoresizing. To solve this issue, I only used View elements in a new line and closed the text element before. That works on Android as well, since there is no support for a `View` inside of a `Text` element.

**Comment by lacker** [comment]
Yeah, it would be great if it totally worked, but it is currently sort of an unintentional feature that is not complete, which makes problems with this somewhat of a "wontfix". I'm glad you found a workaround here. I'm going to close this issue because there's a workaround and due to the View-inside-Text thing I would not consider this a bug, although if someone were interested in putting together a pull request to fix it that would be great.
