### ISSUE TITLE
Why is  CameraRoll.getPhotos called `getPhotos` if you can also retrieve videos?

### ISSUE THREAD

**Issue by philolo1** [facebook/react-native#10119]
### Issue Description

The function name getPhotos in CameraRoll is very misleading, it leads to think that one can only getPhotos, but one can also retrieve videos with it.
### Steps to Reproduce / Code Snippets

Look at the source code: https://github.com/facebook/react-native/blob/master/Libraries/CameraRoll/CameraRoll.js, its called getPhotos.
#### Expected Results

I would expect to have some information in the docs about video retrieval https://facebook.github.io/react-native/docs/cameraroll.html and ideally there would be some better name.

[FILL THIS OUT]
### Additional Information
- React Native version: current Master
- Platform(s) (iOS, Android, or both?): iOS
- Operating System (macOS, Linux, or Windows?): macOS

**Comment by lacker** [comment]
At this point changing the name or changing the behavior seems like it would be breaky for not that great a benefit. The docs you link do talk about videos, although the function isn't super-clearly documented. Would you be interested in sending a docs pull request? If not, I think it's ok to leave this as is.
