### ISSUE TITLE
Camera Roll works on the Simulator but not on the Device

### ISSUE THREAD

**Issue by xavicolomer** [facebook/react-native#10115]
### Issue Description

I am trying to create an application with a list all the images on my Camera Roll, the application works on the Simulator, but it does not on the Device.

I created a project repository to replicate the problem:
https://github.com/xavicolomer/react-native-cameraroll-empty
### Steps to Reproduce / Code Snippets

Download the project and run the app in the simulator and in the device
#### Expected Results

The images are listed in both environments, ONLY the simulator shows a few images.
### Additional Information
- React Native version: 0.34
- Platform(s) (iOS, Android, or both?): iOS 10 (Device iphone5)
- Operating System (macOS, Linux, or Windows?): macOS Sierra

**Comment by comountainclimber** [comment]
I think the issue might be that you didnt include a description for `NSPhotoLibraryUsageDescription` in info.plist

**Comment by xavicolomer** [comment]
Hi @comountainclimber 

I added a screenshot with the code on my project, but also a link to the repository I created to replicate the problem with the minimum code here:
https://github.com/xavicolomer/react-native-cameraroll-empty/blob/master/ios/CameraRollBug/Info.plist

As you can see in both NSPhotoLibraryUsageDescription has been set. If I hadn't added that it wouldn't work on the simulator either.

Thanks though

![screen shot 2016-09-29 at 11 43 39](https://cloud.githubusercontent.com/assets/1476272/18949086/094bdabe-863a-11e6-9be3-643e9e5bc6aa.png)

**Comment by lacker** [comment]
I think this is lacking enough information to reproduce. You might want to try getting this working using a non-React-Native app first and then porting over whatever you did? Because it seems likely to be a permissions-type issue rather than a React Native issue.

**Comment by clovs** [comment]
Hello @xavicolomer,

Did you find a Solution?
I got the same issue on my project.
Let me know ;-)

**Comment by xavicolomer** [comment]
Hi there @clovs 

Nope. Sorry, I had to postpone the project and I didn't had time to check it again.

**Comment by clovs** [comment]
Okay thanks for the feedback.

I resolved the issue by inspiring me with this Facebook example code:

https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/CameraRollView.js

Peace,

**Comment by CorinneKelly** [comment]
@clovs that link is dead =( do you mind posting what was causing the problem and how you were able to resolve it?

**Comment by clovs** [comment]
Go on the Github of react-native : https://github.com/facebook/react-native
Let click on find a file : "CameraRoll",

Let see some results like this : 
https://github.com/facebook/react-native/blob/master/RNTester/js/CameraRollExample.js
https://github.com/facebook/react-native/blob/master/RNTester/js/CameraRollView.js
