### ISSUE TITLE
[Android]: scrollView scrollTo doesn't do anything

### ISSUE THREAD

**Issue by fanyuRN** [facebook/react-native#10129]
componentWillMount() {
        const updateListener = Platform.OS === 'android' ? 'keyboardDidShow' : 'keyboardWillShow';
        const resetListener = Platform.OS === 'android' ? 'keyboardDidHide' : 'keyboardWillHide';
        DeviceEventEmitter.addListener(updateListener, this.keyboardDidShow.bind(this));
        DeviceEventEmitter.addListener(resetListener, this.keyboardDidHide.bind(this));
    }
  keyboardDidShow(){
    this.refs.mainScrollView.scrollTo(
                {y:100,x:160, animated:true}
     );
}

**Comment by hey99xx** [comment]
Looks good for a Stackoverflow post. But if you want help from anyone, please style the code properly, fill the issue template and write down which versions of React Native you've tested with on which devices.

**Comment by fanyuRN** [comment]
thx，okay，I will do these in the furture, I have solved the question

**Comment by windhost** [comment]
https://github.com/facebook/react-native/issues/11693
