### ISSUE TITLE
Android run Example AnimatedGratuitousApp error

### ISSUE THREAD

**Issue by zhonshu** [facebook/react-native#10128]
Error while updating property 'transform' of view managed By: RCTImageView  
![image](https://cloud.githubusercontent.com/assets/6829979/18868872/59fdc18e-84dc-11e6-9be1-a6d5ab0e160a.png)

**Comment by ds-aco** [comment]
my error is  RCTView ,  anyone know what's wrong with this?

**Comment by lacker** [comment]
I think this issue lacks enough information to reproduce so I am going to close it.
