### ISSUE TITLE
Duplicate zip entry error during Proguard task

### ISSUE THREAD

**Issue by lyahdav** [facebook/react-native#10124]
### Issue Description

After integrating React Native into an existing Android app, when I assemble the release build I get the following error:

`Warning: Exception while processing task java.io.IOException: Can't write [../app/build/intermediates/transforms/proguard/world/internal/jars/3/1f/main.jar] (Can't read [.../app/build/intermediates/exploded-aar/com.facebook.react/react-native/0.31.0/jars/libs/infer-annotations-1.5.jar(;;;;;;**/*.class)] (Duplicate zip entry [aib.class == infer-annotations-1.5.jar:com/facebook/infer/annotation/Assertions.class]))`
### Steps to Reproduce / Code Snippets

`./gradlew assembleRelease`
#### Expected Results

Build succeeds
### Additional Information
- React Native version: 0.31.0
- Platform(s) (iOS, Android, or both?): Android
- Operating System (macOS, Linux, or Windows?): macOS

It seems this error happens because the project already has a dependency on the `infer-annotations-1.0.0` library. I am able to workaround the issue for now by adding the following to the `app/build.gradle` file:

```
import com.android.build.gradle.internal.pipeline.TransformTask

def deleteDuplicateJniFiles() {
    def files = fileTree("${buildDir}/intermediates/exploded-aar/com.facebook.react/react-native/0.31.0/jars/libs/") {
        include "**/infer-annotations-1.5.jar"
    }
    files.each { it.delete() }
}

tasks.withType(TransformTask) { pkgTask ->
    pkgTask.doFirst { deleteDuplicateJniFiles() }
}
```

I imagine there's a better way to resolve this. At a minimum should there be documentation somewhere that when integrating React Native into an existing Android app this could happen and how to resolve it. Or is there a way to have React Native itself detect this situation and resolve it automatically?

**Comment by lacker** [comment]
I guess it depends how common this is. If this only happens fairly rarely then it would be reasonable for people to just Google for the error and then find something like this issue. If this is happening a lot then we would want to do something else. Maybe wait for a bit and see whether a bunch of folks upvote this issue or whether someone shows up with a better idea.

**Comment by christopherdro** [comment]
@facebook-github-bot icebox

**Comment by gengjiawen** [comment]
Sometimes Android Studio cache will go wrong, you can try to clean build by : `./gradlew clean assembleRelease`.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/duplicate-zip-entry-error-during-proguard-task

**Comment by lyahdav** [comment]
To anyone who runs into this issue, it was happening to me because the project I was integrating RN in already had a different version of Facebook's `infer-annotations` in the project. A couple other approaches to fix this:

1. Use Gradle's [Dependency Substitution Rules](https://docs.gradle.org/3.3/userguide/dependency_management.html#dependency_substitution_rules).
1. Go into your `node_modules/react-native/android/com/facebook/react/react-native/<version>` folder, extract the .aar file (it's a .zip), remove the .jar in the `libs` folder, and re-create the .aar. This will only work if you add the .aar to version control.
