### ISSUE TITLE
Panresponder  only supported on ios?

### ISSUE THREAD

**Issue by fanyuRN** [facebook/react-native#10123]
I don't konw if panresponder is suit for android.thx

**Comment by hey99xx** [comment]
It is supported.

**Comment by fanyuRN** [comment]
my version is  0.32，0.32？

**Comment by fanyuRN** [comment]
but I can't call onResponderRelease ,is onShouldBlockNativeResponder?  should I return false?

**Comment by fanyuRN** [comment]
oh, I get it,thx
