### ISSUE TITLE
Cannot set WebView height 

### ISSUE THREAD

**Issue by erikdung** [facebook/react-native#1013]
Hi,
I tried to use WebView to render video from youtube (url: 'https://www.youtube.com/embed/'+ video.videoId +"?autoplay=1&playsinline=1"). The problem is that I cannot set height of WebView component or View wrapper. Please help

**Comment by mjw56** [comment]
@erikdung How are you trying to set the height on the WebView? Can you post a gist with the issue?

**Comment by mydearxym** [comment]
+1

**Comment by christopherdro** [comment]
Here's a example with embedding a youtube video and setting the height and width of the content container.
https://rnplay.org/plays/6JolNQ

**Comment by brentvatne** [comment]
I highly recommend checking out @christopherdro's link! It solves the problem and is fun ;)
