### ISSUE TITLE
Webview get html content

### ISSUE THREAD

**Issue by alexsotocx** [facebook/react-native#10139]
Hello everyone, I know that this's not a Issue, but is there a way of getting the html content of the rendered view in the Webview?

I posted here because I can't find anything on google or stackoverflow

**Comment by damusnet** [comment]
@facebook-github-bot stack-overflow

**Comment by damusnet** [comment]
If you want the html from the url, you could fetch it without a webview.

If it's really the rendered html from the webview you want, I suppose you could [inject](http://facebook.github.io/react-native/docs/webview.html#injectedjavascript) a javascript function that fires on load end, and [posts](http://facebook.github.io/react-native/docs/webview.html#onmessage) the DOM content.

**Comment by HimaniLathiya** [comment]
@alexsotocx  i want the same thing , have you got any solution ? can you please paste your solution ?

**Comment by ducpt2** [comment]
+1 same thing.

**Comment by DeliDoktoru** [comment]
+1
