### ISSUE TITLE
[ListView] ListView Row's position wrong.

### ISSUE THREAD

**Issue by endpress** [facebook/react-native#10134]
##ListView postion wrong
run on RN 0.33
## When I click row and add a new section in listView. A row 's position wrong.
![simulator screen shot 2016 9 27 10 13 33](https://cloud.githubusercontent.com/assets/13311095/18877670/7db1cd90-8500-11e6-9758-c15233029297.png)

## scroll to bottom and click a row then my listView become this
![simulator screen shot 2016 9 27 10 13 58](https://cloud.githubusercontent.com/assets/13311095/18878189/4901e042-8502-11e6-89ea-6c0ed34a7289.png)
The row's position go wrong. I hope someone can fix this

**Comment by endpress** [comment]
this is my code

componentDidMount(){
    var list = this.getList();
    var sectionID = this.getSectionID(1);
    var rowId = this.getRowID(1);
    this.setState({
      dataSource: this.state.dataSource.cloneWithRowsAndSections(list, sectionID, rowId)
    });
  }

  getList() {
    var list = [];
    list['s_'] = 's_';
    for (var i = 0; i<20; i++) {
      list['s_' + i] = 's_' + i;
    }
    return list;
  }

  getSectionID(length) {
    var list = [];
    for (var i = 0; i<length; i++) {
      list.push('s_');
    }
    return list;
  }

  getRowID(length) {
    var list = [];
    for (var j = 0; j<length; j++) {
      list[j] = [];
      for (var i = 0; i<20; i++) {
        list[j].push(i);
      }
    }
    return list;
  }

  getList2() {
    var list = [];

    list['d_'] = 'd_';
    for (var i = 0; i<1; i++) {
      list['d_' + i] = 'd_' + i;
    }

    list['s_'] = 's_';
    for (var i = 0; i<19; i++) {
      list['s_' + i] = 's_' + i;
    }

    return list;
  }

  getSectionID2() {
    var list = [];
    list.push('d_');
    list.push('s_');
    return list;
  }
  getRowID2() {
    var list = [];
    list[0] = [];
    list[0].push(0);
    list[1] = [];
    for (var i = 0; i<19; i++) {
      list[1].push(i);
    }
    return list;
  }

  click(){
    var lst = this.getList2();
    var sID = this.getSectionID2();
    var rID = this.getRowID2();
    this.setState({
      dataSource: this.state.dataSource.cloneWithRowsAndSections(lst, sID, rID)
    });
  }

  renderRow(data, sectionID, rowID){
    return (
      <TouchableHighlight underlayColor="transparent"
              style={[styles.shareRowView]}
              onPress={this.click.bind(this)}>
        <View style={styles.shareRowView}>
          <Text style={styles.shareRowViewText}>
            {data}
          </Text>
        </View>
      </TouchableHighlight>
    );

  }

  renderSectionHeader(sectionData){
    return (
      <View style={styles.shareHeaderView}>
        <Text style={styles.shareHeaderViewText}>
          {sectionData}
        </Text>
      </View>
    );
  }

  render() {
    return (
      <ListView
        dataSource={this.state.dataSource}
        renderRow={this.renderRow.bind(this)}
        renderSectionHeader={this.renderSectionHeader}
        enableEmptySections={true}
        keyboardDismissMode='on-drag'
        style={styles.container}
      />
    );
  }
}

**Comment by endpress** [comment]
[index.ios.js.zip](https://github.com/facebook/react-native/files/495831/index.ios.js.zip)

**Comment by sharq1** [comment]
+1

Please see related issue: #9200
