### ISSUE TITLE
Modal on android tablets doesn't always respect orientation

### ISSUE THREAD

**Issue by thomasvm** [facebook/react-native#10132]
### Issue Description

I use the `Modal` component to render a modal with a dark transparent background. The background is rendered as 

`<View style={{ backgroundColor: '#000', opacity: 0.7, left: 0, top: 0, right: 0, bottom: 0, position: 'absolute' }} />`

On some tablets the width and height of the `Modal` always seem to be those of the wrong orientation. 

It is my belief that the error lies within the code of `ModalHostHelper.java` as you can find it [here](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/modal/ModalHostHelper.java)

That code uses [`getRotation()`](https://developer.android.com/reference/android/view/Display.html#getRotation%28%29) to determine whether the tablet is in portrait or landscape mode. But from the documentation it reads

> Returns the rotation of the screen from its "natural" orientation. The returned value may be Surface.ROTATION_0 (no rotation), Surface.ROTATION_90, Surface.ROTATION_180, or Surface.ROTATION_270. 

The "natural" orientation can vary, for some devices this is landscape for others this is portait. Hence it might be better to determine orientation based on the display's width and height.
### Steps to Reproduce / Code Snippets

Run the example from this gist on a Google Nexus 10 image inside Genymotion
https://gist.github.com/thomasvm/b59f2e46cb3c1be455289621f828fb7c

![2016-09-27_15-03-40](https://cloud.githubusercontent.com/assets/140572/18875197/ff8ecf0c-84c4-11e6-80c6-aae9775d7152.gif)
#### Expected Results

Transparent dark background should fill the screen
### Additional Information
- React Native version: 0.34
- Platform(s) (iOS, Android, or both?): Android, tablets
- Operating System (macOS, Linux, or Windows?): Windows

**Comment by thomasvm** [comment]
Also see issue #9731

**Comment by thomasvm** [comment]
Looks like this issue will be resolved in the next react-native release. I will test and report back once it is out. Thanks @davepack!

**Comment by thomasvm** [comment]
Tested this on 0.36.1 and the behavior is correct now.

**Comment by davepack** [comment]
Glad to have helped on this @thomasvm! Solving my own issue was a strong motivation of course
