### ISSUE TITLE
Can't enable Hot reload nor Debug react native app on Device.

### ISSUE THREAD

**Issue by frnk94** [facebook/react-native#10141]
Hello I just created an app using the `react-native-cli` and when it come to running this app on my phone it fetch a pre-bundle file. If I clicked `Debug Js Remotely` i got this error: 
![image](https://cloud.githubusercontent.com/assets/11723501/18900697/2fd9806a-8512-11e6-904d-a825696c64c7.png).

I build the App with Xcode & using the cli with:
`react-native run-ios --udid` & its seems that it founded my computer local IP address. Also accessing this address from my phone work so its not a firewall issue...

![image](https://cloud.githubusercontent.com/assets/11723501/18900741/88b4ad90-8512-11e6-8770-bd5321807cfb.png)

### Additional Information

* RN: 0.34.1
* Platform: Iphone 7 plus. IOS 10.1
* OS: macOs Sierra 10.12.

**Comment by Anuj-786** [comment]
hey @frnk94, if you are working with simulator then you should have to chorme browser essential in your devices I don't have complete idea on ios, but you can use the command to enable the console debugging in your terminal when you are using hot reloading: 
`react-native log-ios`
you can read the docs [https://facebook.github.io/react-native/docs/debugging.html](url)

**Comment by frnk94** [comment]
@Anuj-786 Simulator work fine! It fetch the bundle from `localhost:8081` and the hot reload is enable, but when it come to working on an actual device its always fetching from pre-bundle file so if i make any change to the code i need to rebuild and relaunch the app every time. It make it hard to debug things also the debugger give me an error. I can't really use the simulator since im using the camera inside the app and the simulator fail to simulate camera.

**Comment by frnk94** [comment]
I just updated macOs and it now working not sure what was the issue...

**Comment by Anuj-786** [comment]
Great !
