### ISSUE TITLE
Can navigator pop gesture be disabled?

### ISSUE THREAD

**Issue by syousif94** [facebook/react-native#1014]
I want to disable the swipe down to dismiss gesture for a navigator scene that's floated in from the bottom, but I can't figure out if it's possible.

Also, `componentWillUnmount()` does not fire if the view is dismissed with a gesture.

**Comment by mjw56** [comment]
@syousif94 I don't believe there is currently a way to do this. 

I was playing around with this and was able to get something working, but I'm not sure if it is the right fix. You would configure to disable it like so:

```javascript
var sceneConfig = Navigator.SceneConfigs.FloatFromBottom;
sceneConfig.gestures.pop.disabled = true;

this.props.navigator.push({
  title: 'Search',
  component: SearchList,
  sceneConfig: sceneConfig
})
```

I had to change one line in ```Navigator.js``` to get this to work:

Navigator.js:
```javascript
  _matchGestureAction: function(gestures, gestureState) {
    if (!gestures) {
      return null;
    }

    var sceneConfig = this.state.sceneConfigStack[this.state.presentedIndex];

    if (sceneConfig.gestures.pop.disabled || this.state.isAnimating) {
      return null;
    }
```

not sure about the ```componentWillUnmount()``` issue..

**Comment by ericvicenti** [comment]
The scene configs are objects with lots of overridable properties in them. If you want to start with `FloatFromBottom` and disable gestures, you can do this:

```
configureScene={() => ({
  ...Navigator.SceneConfigs.FloatFromBottom,
  gestures: {}, // or null
})
```

The component should unmount when dismissing with a pop gesture. That might be a bug

**Comment by syousif94** [comment]
@ericvicenti thank you!

**Comment by mjw56** [comment]
@ericvicenti awesome, that works!

So how about disabling only for a select few and not all screens? It seems like gestures would then need to be opt-in?

```javascript
configureScene={(route) => ({
  ...route.sceneConfig || Navigator.SceneConfigs.FloatFromBottom,
  gestures: route.gestures
})}
```

And then when pushing a route:

```javascript
// enable back gestures
this.props.navigator.push({
  title: 'Search',
  component: SearchList,
  sceneConfig: Navigator.SceneConfigs.FloatFromBottom,
  gestures: Navigator.SceneConfigs.FloatFromBottom.gestures
})
```

or ..

```javascript
// disable back gestures
this.props.navigator.push({
  title: 'Search',
  component: SearchList,
  sceneConfig: Navigator.SceneConfigs.FloatFromBottom,
  gestures: null // or just don't include this
})
```

**Comment by mjw56** [comment]
@ericvicenti this will call ```componentWillUnmount``` on gesture:

```javascript
if (transitionVelocity < 0 || this._doesGestureOverswipe(releaseGestureAction)) {
  this._transitionToFromIndexWithVelocity(transitionVelocity);
} else {
  this._handlePop();
  this._transitionToToIndexWithVelocity(transitionVelocity);
}
```

**Comment by syousif94** [comment]
@mjw56 you can extend objects like this

```
this.props.navigator.push({
  title: 'Search',
  component: SearchList,
  sceneConfig: {
    ...Navigator.SceneConfigs.FloatFromBottom,
    gestures: {}
  }
})
```

**Comment by mjw56** [comment]
@syousif94 ah, yes that works :+1: 

So then what does your ```configureScene``` look like for the ```Navigator``` component?

Right now I have this working:

```javascript
// extend off route.sceneConfig if provided, otherwise default to FloatFromRight
configureScene={(route) => ({
  ...route.sceneConfig || Navigator.SceneConfigs.FloatFromRight
})}
```

**Comment by syousif94** [comment]
@mjw56 same as yours essentially

**Comment by ericvicenti** [comment]
:+1:

@mjw56 , `Navigator` should call `componentWillUnmount` on a scene _after_ the pop transition completes. If that doesn't work, could you re-file as another issue?

**Comment by HendrikPetertje** [comment]
Hey guys.
In case you want to remove the anoying gesture

Check the code from here: https://rnplay.org/apps/HPy6UA
This is an attempt to change the animation and he in this case stretches the gesture space to the whole screen.. but you can remove the gesture to here.

Replace:

    var CustomSceneConfig = Object.assign({}, BaseConfig, {
      // A very tighly wound spring will make this transition fast
      springTension: 100,
      springFriction: 1,
      // Use our custom gesture defined above
      gestures: {
        pop: CustomLeftToRightGesture,
      }
    });

With:

    var CustomSceneConfig = Object.assign({}, BaseConfig, {
      gestures: {
        pop: null,
      }
    });

**Comment by shahankit** [comment]
Setting gestures to {} sometimes gave me error when using a scroll view in pushed view. I used the following and it solved all issues `sceneConfig.gestures.pop.edgeHitWidth = 0;`

**Comment by shahankit** [comment]
@mjw56 @ericvicenti @syousif94 Can you please help, There is a problem with my solution above and other specified don't work well somehow. I want to keep pop gesture for some screen and not for the rest. So for some I set edgeHitWidth to 0 and for the rest 30/150 depending on direction. After I push any component with nonzero edgeHitWidth all the others pushed with zero edgeHitWidth also now have pop gesture. Somehow only single of Navigator.SceneConfig.FloatFromXYZ is being used across all component. Changing in one persists the changes across all instead of assigning new sceneConfig to each component push.
