### ISSUE TITLE
Platform.Version is not implemented on IOS

### ISSUE THREAD

**Issue by rturk** [facebook/react-native#10149]
How to reproduce:

Call  Platform.Version from a IOS device returns `undefined`

Expected results:

`Phone1,1`, `Iphone7,2`, `iPad3,3`

**Comment by rturk** [comment]
Code reference:

Android:
https://github.com/facebook/react-native/blob/7c3364196a2a791a01e2a2d9d167bffb6f184ff6/Libraries/Utilities/Platform.android.js

IOS:
https://github.com/facebook/react-native/blob/7c3364196a2a791a01e2a2d9d167bffb6f184ff6/Libraries/Utilities/Platform.ios.js

**Comment by reneweb** [comment]
Sounds reasonable to add the version for IOS. However, when getting the version in Android it returns the Android sdk version, thus, to be consistent with Android we should return the IOS version and not the device type.

**Comment by rturk** [comment]
@reneweb makes sense.
