### ISSUE TITLE
How to post a json array in react native

### ISSUE THREAD

**Issue by vikiesakki** [facebook/react-native#10143]
I have a JSON array like this. I want to post it via fetch function. i didn't find any reference for this kind of problems

[
    {
        "id": 824233,
        "project_id": 1457,
        "issue_id": 123420,
        "activity_id": 71,
        "comments": "Testing",
    },
    {
        "id": 824234,
        "project_id": 1457,
        "issue_id": 123420,
        "activity_id": 188,
        "comments": "test",
    },
    {
        "id": 824235,
        "project_id": 1457,
        "issue_id": 123420,
        "activity_id": 188,
        "comments": "Test",
    }
]
I want to post this array

**Comment by rmevans9** [comment]
https://facebook.github.io/react-native/docs/network.html outlines how to make fetch calls. All you have to do is stringify it (example in docs) and post it to whatever URL you want.

**Comment by rmevans9** [comment]
@facebook-github-bot answered

**Comment by vikiesakki** [comment]
@rmevans9. thanks for the response ya i saw the document. but in document post the json array is not there i think
