### ISSUE TITLE
The ListView component render issue

### ISSUE THREAD

**Issue by aiDove** [facebook/react-native#10142]
I tried to click an item to enter the detail view from my listview. In the detail view, I tried to make a call with the Linking component. Unfortunately, after finishing the call and coming back to the listview through clicking "back" button in the detail view, I found the listview was empty and not reloaded items as expected, unless I touched the screen at that moment. 

I tried to recall "scrollTo", but it didn't work.

I want to know if there is anyone encountered the similar issue, and do me a favor.

BTW, this issue is only found in iOS. I can reproduced it in RN 0.29.0, 0.33.0, and 0.34.0.

Thanks!

**Comment by chadwatson** [comment]
I'm running into the exact same issue.

**Comment by chadwatson** [comment]
@aiDove [this suggestion](https://github.com/facebook/react-native/issues/8607#issuecomment-231371923) worked for me, although I have idea why, to be honest.

**Comment by aiDove** [comment]
@chadwatson Turning off removeClippedSubviews solves the issue for me. Thanks!

**Comment by clauderic** [comment]
`removeClippedSubviews` has performance implications though, so while it works as a temporary workaround, I wouldn't exactly consider that a solution in production 😕

**Comment by sooth-sayer** [comment]
Same issue for me

**Comment by lacker** [comment]
Can you provide a repro of this problem with rnplay.org?

**Comment by sahrens** [comment]
Has anyone tried moving to FlatList and seeing if this is resolved without disabling removeClippedSubviews?

**Comment by hramos** [comment]
Closing as ListView is deprecated in 0.43. Use FlatList.
