### ISSUE TITLE
Latest react-native app doesn't work ":CFBundleIdentifier", Does Not Exist for Xcode 8

### ISSUE THREAD

**Issue by gavinxyang** [facebook/react-native#10151]
This is existing bug which is closed. 
https://github.com/facebook/react-native/issues/7308#issuecomment-249492688

There is some workaround in that bug to solve the problem. But I create one push react team to get this fix. The thing should just work out of box.

Thanks

**Comment by joypatel04** [comment]
It looks like it's working now for me !!

**Comment by gavinxyang** [comment]
what is environment?

have you tried f8apps, the demo app?

**Comment by lacker** [comment]
It's fixed in RN 0.38 as per that thread you linked to.
