### ISSUE TITLE
My RN App always errors 'Thread 1：EXC_BAD_ACCESS(code=EXC_I386_GPFLT)'

### ISSUE THREAD

**Issue by wangchaoduo** [facebook/react-native#10162]
My RN App run on simulator always dead in a short time.It errors 'Thread 1：EXC_BAD_ACCESS(code=EXC_I386_GPFLT)' . I found  no solution in google.Will it errors if my redux store's data is too large?

**Comment by gre** [comment]
nothing to do with redux and probably not to any of your JavaScript.
the ios stacktrace would help. also it's probably because of https://github.com/facebook/react-native/issues/10145

**Comment by javache** [comment]
Duplicate of #10145.
