### ISSUE TITLE
Crash on device with xcode8 by RCTCustomScrollView refreshControl

### ISSUE THREAD

**Issue by PressEsc** [facebook/react-native#10165]
Hey guys, I got this problem for a week when i upgrade xcode7.3 to version 8 and i searched everywhere but nothing that i can do to fix it.
[![WechatIMG2.jpg](https://s10.postimg.org/p3x5es9m1/Wechat_IMG2.jpg)](https://postimg.org/image/j2zghpmzp/)

* React Native version: [0.24]
* Platform(s) (iOS, Android, or both?): [iOS]
* Operating System (macOS, Linux, or Windows?): [macOS]

**Comment by ide** [comment]
Xcode 8 fixes landed in a more recent version of React Native, I'm not surprised that 0.24 is broken. You'll have to upgrade to 0.34.

**Comment by PressEsc** [comment]
fixed by #8472
