### ISSUE TITLE
Webview makes Navbar translucent on Nexus 5 Android 6.0

### ISSUE THREAD

**Issue by klyment** [facebook/react-native#10173]
I configure a transition for navigator, for instance, 

> configureScene={()=>{return Navigator.SceneConfigs.FloatFromBottomAndroid}}

When a webview scene pops up somehow the navbar will become translucent. 

![Image of webview](http://i68.tinypic.com/2hi9t2u.png)

After trying for the second time, it recovers to black.

**Comment by lacker** [comment]
I think this issue lacks enough information to reproduce it, so I am going to close this issue. Please feel free to reopen if you have a sample app that reproduces this problem.
