### ISSUE TITLE
[iOS] [WebView] Error opening local video media (uri starting by file://)

### ISSUE THREAD

**Issue by tdurand** [facebook/react-native#10171]
### Issue Description

I'm trying to open a local video media in WebView, it's working as i see the video with the play button but after 0,5s i get an error **"WebKitErrorDomain , Plug-in handled load"** . Seems that somehow webview doesn't allow to open things from file://.

Full error log:

```
{
  canGoBack:false,
  canGoForward:false,
  code:204,
  description:"Plug-in handled load",
  domain:"WebKitErrorDomain",
  loading:false,
  target:155,
  title:"",
  url:"file:///Users/tdurand/Library/Developer/CoreSimulator/Devices/E2D725EC-A972-4BAC-8309-2D8A13535FAA/data/Containers/Data/Application/54A5EDAB-F950-4D7D-8995-3BD5755AF52F/tmp/trim.CF765039-D257-4DB8-A9A7-3925D495942F.MOV"
}
```

You can see that it's successfully reading the file before throwing the error:

![xo8exe3hut](https://cloud.githubusercontent.com/assets/533590/18898049/97cce982-84f4-11e6-9f5f-b6f0b696d482.gif)
### Steps to Reproduce / Code Snippets

Just try to open a local video file in webview:

``` jsx
<WebView source={{ uri: "file:///Users/tdurand/Library/Developer/CoreSimulator/Devices/E2D725EC-A972-4BAC-8309-2D8A13535FAA/data/Containers/Data/Application/54A5EDAB-F950-4D7D-8995-3BD5755AF52F/tmp/trim.CF765039-D257-4DB8-A9A7-3925D495942F.MOV" }}
                  style={{height: 150 ,width: 150}}
                />
```
#### Expected Results

Do not have the error thrown an being able to play the video.
### Additional Information
- React Native version: 0.34.1
- Platform(s) (iOS, Android, or both?): iOS
- Operating System (macOS, Linux, or Windows?): macOS

**Comment by damusnet** [comment]
Did you make any progress on that issue?

**Comment by christopherdro** [comment]
@facebook-github-bot icebox

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/ios-webview-error-opening-local-video-media-uri-starting-by-file

**Comment by gitbugr** [comment]
I was experiencing this issue (yes, it is still an issue.) and solved it in a somewhat hack-y way. 

I src the video in a html5 video tag within the WebView.

`<WebView style={{height:200}} source={{html:"<video style=' height:180;width:500;' controls src='VIDEO_LINK_HERE.m3u8'></video>"}} allowsInlineMediaPlayback={true} mediaPlaybackRequiresUserAction={true}}/>`

**Comment by cworsley4** [comment]
+1 here. Experiencing as well.

**Comment by coreform** [comment]
Here's a potential fix from another repo that ran into the issue with iOS' UIWebView. Perhaps RN needs this fix too?

https://github.com/brave/browser-ios/commit/e74eed9c11a408af5081477b827b5c05b669a60d
