### ISSUE TITLE
App crash on IOS at launch if turn on 4G

### ISSUE THREAD

**Issue by wangcpsnow** [facebook/react-native#10183]
Hi,
for my iphone 6s ,ios10,my application crash if I turn on 4G.But if in Wi-Fi then everything is working.

**Comment by senthilsivanath** [comment]
Are you connected to Debug Bundle (with localhost) in Release Mode ?

**Comment by wangcpsnow** [comment]
How to close Debug Bundle please?

**Comment by wangcpsnow** [comment]
ok, I have solved this. thks
