### ISSUE TITLE
Get Image error when upgrade to RN 0.34

### ISSUE THREAD

**Issue by cbcye** [facebook/react-native#10193]
Cannot be converted to an image. Did you forget to call resolveAssetSource() on the JS side?

![image](https://cloud.githubusercontent.com/assets/869074/19012840/1670b25e-87f3-11e6-8ab5-d0d5bb552d25.png)

**Comment by cbcye** [comment]
I think there must be some error when my upgrade RN, I use follow steps to upgrade RN and it is working

1. backup whole project include node_modules folder
2.  npm info react-native
3. npm install --save react-native@0.34
4. install the dependese module follow the warning message
5. react-native upgrade
6. rnpm link
7. use Beyond Compare to merge theo project file like : AppDelegate.m,Info.plist,Images.xcassets,Image.imageset/AppIcon.appiconset/Contents.json

暂时使用react-native run-ios会报错，使用xcode正常

**Comment by kagalenitin** [comment]
Hi, What did you do to resolve the issue? Is it related to 0.34? I am running into exactly the same issue.

**Comment by cbcye** [comment]
I don't find the real reason, but i resolve it through the steps as above.

**Comment by divyekhanna** [comment]
@kagalenitin were you able to resolve it?

**Comment by Alexoner** [comment]
Same issue, wondering how
