### ISSUE TITLE
CameraRoll.saveToCameraRoll() fatal error

### ISSUE THREAD

**Issue by kevinfreitas** [facebook/react-native#10190]
### Issue Description

With the CameraRoll library properly linked up I'm calling CameraRoll.saveToCameraRoll() to save an image from a URI and getting the following in xcode:

libsystem_kernel.dylib`__pthread_kill:
    0x107a53efc <+0>:  movl   $0x2000148, %eax          ; imm = 0x2000148 
    0x107a53f01 <+5>:  movq   %rcx, %r10
    0x107a53f04 <+8>:  syscall 
->  0x107a53f06 <+10>: jae    0x107a53f10               ; <+20>
    0x107a53f08 <+12>: movq   %rax, %rdi
    0x107a53f0b <+15>: jmp    0x107a4e7cd               ; cerror_nocancel
    0x107a53f10 <+20>: retq   
    0x107a53f11 <+21>: nop    
    0x107a53f12 <+22>: nop    
    0x107a53f13 <+23>: nop    

No error is caught by the promise -- the .then isn't firing so I can't get any info from a console.log

[FILL THIS OUT]

#### Expected Results

In iOS 9.3 the image is saved to the camera roll. In iOS 10 I get the above and, when not logging, my app crashes in the simulator.

### Additional Information

* React Native version: 0.34
* Platform(s) (iOS, Android, or both?): iOS 10
* Operating System (macOS, Linux, or Windows?): macOS

**Comment by JohnnyRuvac** [comment]
You have to add NSPhotoLibraryUsageDescription key to info.plist. https://github.com/facebook/react-native/issues/10115

**Comment by ericvicenti** [comment]
Closing this out as I'm improving the docs to reflect the permissions needs in iOS 10.

As far as I can tell, there still is a real CameraRoll crash that is being tracked in #10115
