### ISSUE TITLE
RTL is forced in android RTL devices

### ISSUE THREAD

**Issue by atlanteh** [facebook/react-native#10204]
### Issue Description

The new version of React Native has issued support for RTL devices: 
https://facebook.github.io/react-native/blog/2016/08/19/right-to-left-support-for-react-native-apps.html
However, it seems that in RTL android devices the RTL layout is forced and there's no way to change it so now all apps are broken for RTL devices.

I opened an issue in Stackoverflow [Here](http://stackoverflow.com/questions/39815309/rtl-is-forced-in-rtl-devices/39815324#39815324), and then managed to solve this problem by forcing LTR in android code like so:

``` java
import com.facebook.react.modules.i18nmanager.I18nUtil;

@Override
public void onCreate() {
    super.onCreate();

    // FORCE LTR
    I18nUtil sharedI18nUtilInstance = I18nUtil.getInstance();
    sharedI18nUtilInstance.allowRTL(getApplicationContext(), false);
    ....
}
```

But this is just a hack. Still, anyone who has react-native@0.34.0 will have his entire app flipped when used in RTL android devices even without actively allowing RTL.
### Steps to Reproduce / Code Snippets

``` jsx
import React from 'react';
import { View, Text } from 'react-native';

export default class App extends React.Component {
    render() {
        return (
            <View style={{flex: 1, alignSelf: 'stretch'}}>
                <Text style={{alignSelf: 'flex-start'}}>Left</Text>
                <Text style={{alignSelf: 'flex-end'}}>Right</Text>
            </View>
        );
    }
}
```
#### Expected Results

Left text to be on the left side & Right text to be on the right side.
#### Actual Results

Left text is on the right side & Right text is on the left side.
### Additional Information
- React Native version: 0.34.0
- Platform(s) (iOS, Android, or both?): android
- Operating System (macOS, Linux, or Windows?): Windows

**Comment by MoLow** [comment]
this happens to me to.
`right` and `left` in my code are reversed on the screen.

**Comment by kfiroo** [comment]
@MoLow @atlanteh I had the same issue, ended up calling the following when my app starts
`ReactNative.I18nManager.allowRTL(false);`

**Comment by DeDuckProject** [comment]
Isn't there a way to do this though the js code to work on both android and ios?
I'm not even sure if its a bug or a feature

**Comment by DeDuckProject** [comment]
@kfiroo It can't seem to resolve I18nManager
I'm on RN=0.33
Do you have an idea?
תודה
<img width="456" alt="screenshot 2016-11-28 16 34 29" src="https://cloud.githubusercontent.com/assets/10045034/20672048/8e6223c0-b588-11e6-8cdb-51369c4a60ac.png">

**Comment by kfiroo** [comment]
@DeDuckProject Sorry for the confusion, this is from my JS code
Something like this
```javascript
const ReactNative = require('react-native');
try {
    ReactNative.I18nManager.allowRTL(false);
} catch (e) {
    console.log(e);
}
```

**Comment by DeDuckProject** [comment]
@kfiroo thanks, works like a charm

**Comment by efratyo** [comment]
I'm sorry, @kfiroo can you please mention where this code should be paced? 
I'm now facing this problem

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/rtl-is-forced-in-android-rtl-devices

**Comment by p30arena** [comment]
@kfiroo its still not working on some devices, I used this instead:

https://stackoverflow.com/questions/39815309/rtl-is-forced-in-rtl-devices

```
MainApplication.java:

import com.facebook.react.modules.i18nmanager.I18nUtil;

public class MainApplication extends Application implements ReactApplication {
    @Override
    public void onCreate() {
        super.onCreate();

        // FORCE LTR
        I18nUtil sharedI18nUtilInstance = I18nUtil.getInstance();
        sharedI18nUtilInstance.allowRTL(getApplicationContext(), false);
        ....
    }
}
```

**Comment by dekelev** [comment]
All the solutions here do force LTR view, but do not resolve deep issues within components that lack proper support for RTL, such as the [react-native Slider](https://github.com/facebook/react-native/issues/11862), which still doesn't render correctly.

The solution for Android is to add `<item name="android:layoutDirection">ltr</item>` in Android _styles.xml_ file.

https://stackoverflow.com/questions/39817683/forcing-the-app-to-work-as-ltr

**Comment by hoorsa** [comment]
thanks @dekelev 

```
MainApplication.java:

import com.facebook.react.modules.i18nmanager.I18nUtil;

public class MainApplication extends Application implements ReactApplication {
    @Override
    public void onCreate() {
        super.onCreate();

        // FORCE LTR
        I18nUtil sharedI18nUtilInstance = I18nUtil.getInstance();
        sharedI18nUtilInstance.allowRTL(getApplicationContext(), false);
        ....
    }
}
```

does not forced ltr for `react-native-navigation` but `<item name="android:layoutDirection">ltr</item>` did.

**Comment by jamsch** [comment]
Went through the solutions and RTL is still forced on Text that starts with an Arabic character.

What worked for me (as a rather hacky solution) was adding in the Unicode character "LEFT-TO-RIGHT ISOLATE" at the start. 

```javascript
    <Text>{'\u2066'} أهْلًا وَسَهْلاً Ahlan wa Sahlan!</Text>
```

My attempts otherwise have been the following:

```javascript
// index.js
import {  I18nManager } from 'react-native';
I18nManager.allowRTL(false);
```

```xml
<!-- styles.xml -->
<resources>
     <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
       <item name="android:gravity">left</item>
       <item name="android:layoutDirection">ltr</item>
       <item name="android:textDirection">ltr</item>  
       <item name="android:textAlignment">textStart</item>
     </style>
</resources>
```

```xml
<!-- AndroidManifest.xml -->
<application
    android:supportsRtl="false"
    ....
```

As well as the example above to force I18n to go LTR on Java.
