### ISSUE TITLE
Broken link on README.md

### ISSUE THREAD

**Issue by jkomyno** [facebook/react-native#10209]
This link no longer works: https://facebook.github.io/react-native/docs/sample-application-movies.html

**Comment by hey99xx** [comment]
There are lots of documentation links that are broken over version updates. If you know the correct link, I'm sure Facebook team working on React native will appreciate a PR.

**Comment by lacker** [comment]
OK I just put up a PR to fix this at https://github.com/facebook/react-native/pull/12270 . Since this doesnt seem like the sort of rocket science we need an issue to discuss on, I'm going to close this issue ;-) Thanks for reporting it!
