### ISSUE TITLE
Loading Styles dynamically slows down the page transitions considerably

### ISSUE THREAD

**Issue by Nosherwan** [facebook/react-native#1020]
We have multiple pages in our react-native app. In one of the subsequent pages(not the first two) we are trying to load the styles object dynamically. The way we are doing this is by making an ajax call in the previous page, and then passing the styles field as a string to the next page like so:
```javascript
then(items =>
this.props.navigator.push({
    title    : “NextPage",
    component: ItemList,
    passProps: {
        ParentID: ParentId,
        items    : items,
        token   : tokenValue,
        styles : items.styles
    }
})
);
```
the style object is being dynamically combined with some default values and eventually loaded into a global variable like so:
```javascript
constructor(props) {
    super(props);

    var dataSource = new ListView.DataSource({
        rowHasChanged: (r1, r2) => r1.guid !== r2.guid
    });
    this.state = {
        dataSource: dataSource.cloneWithRows(this.props.items)
    };

    styleSheet = JSON.parse(this.props.styles);
    styleSheet = this._customiseStyle(styleSheet);
}

_customiseStyle(styleSheet){
    var combined = _.extend(styles,styleSheet);
    return StyleSheet.create(combined);
}
```
the styleSheet variable is then used inline within the page components to display the styling. This however really slows down the initial pages and the transitions happen very slowly. What I suspect from looking at the documentation is (https://facebook.github.io/react-native/docs/style.html) that as the styles are loaded during the initialisation of the app, hence the app is consistently hitting the styleSheet variable as it encounters it inline, and hence slows down the UI until it actually resolves the variable on the actual page, then the speed becomes normal.

1. I am looking for suggestions here as to what can we do to load the styles dynamically without impact on UI responsiveness.
2. Or is this currently not possible in the current version of react-native.
3. Will it ever be?

Custom styling is a major feature for us, hence if this doesn’t work out we may have to switch from react-native all together, so help would be really appreciated.

**Comment by sahrens** [comment]
Not sure I understand your problem or analysis of the problem - react-native shouldn't be fundamentally slower at using dynamic/downloaded styles like this than any other platform. Can you do more caching/prefetching?  Ideally you would send a request as soon as the app is launched that would fetch all your style info and cache it for fast access.  Are the styles themselves particularly large and/or complex?  Did you confirm that this global object isn't being re-generated unnecessarily?

**Comment by Nosherwan** [comment]
Thankyou for your validation, and pointing me in the right direction.
After debugging in detail there were two issues that I found. One was the request was returning 1500 records that was causing the page to wait for almost 20 seconds. Secondly an error on my part, I had accidentally ticked the slow animations option for the ios emulator that literally reduced the speed of the animations.
I will close the issue now.
