### ISSUE TITLE
[Android] Cannot toggle pointerEvents + opacity on View

### ISSUE THREAD

**Issue by joncursi** [facebook/react-native#10216]
I am trying to toggle an Overlay in and out over scene content. The below code works perfectly on iOS but will not show the overlay at all on Android. According to the react-native documentation: 
- [pointerEvents should work for both platforms](http://facebook.github.io/react-native/releases/0.34/docs/view.html#pointerevents),
- [as should opacity](http://facebook.github.io/react-native/releases/0.34/docs/view.html#style).

Thoughts?

``` jsx
import { View } from 'react-native';

...

<View
  pointerEvents={condition ? 'auto' : 'none'}
  style={{
    opacity: condition ? 1 : 0,
  }}
>
  <Text>This toggles properly on iOS, but never displays on Android. Bug?</Text>
</View>
```

I originally spotted this while attempting to animate via react-native-animatable (please see https://github.com/oblador/react-native-animatable/issues/57), but since the same issue is present on the normal `View` component, I believe this may be an issue with react native itself.

**Comment by gre** [comment]
How is your view an overlay? I don't see any `position: absolute` , but if you use that `position: absolute` you might also need to provide **width** and **height** unlike in iOS.
I've notice this difference when porting from iOS, the content seems to be overflow hidden otherwise.

**Comment by joncursi** [comment]
I stripped out all other styles for simplicity of the example, as I was able to narrow down the issue to the `pointerEvents` + `opacity` combination on Android. I have tried `absolute` positioning with calculated `height` and `width`, it doesn't change the result.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/android-cannot-toggle-pointerevents--opacity-on-view
