### ISSUE TITLE
Modal goes above inspector

### ISSUE THREAD

**Issue by MarkEstefanos** [facebook/react-native#10211]
### Issue Description

If you're using the modal component and the inspector, the modal will go on top of the inspector, and the inspector won't work.
### Steps to Reproduce / Code Snippets

Present a modal, and try to use the inspector (command + D => show inspector).
#### Expected Results

That the inspector functions correctly.
### Additional Information
- React Native version: .34
- Platform(s) (iOS, Android, or both?): iOS
- Operating System (macOS, Linux, or Windows?): MacOS

**Comment by ryankask** [comment]
Hi there. This is a known issue: https://github.com/facebook/react-native/issues/8193. There was a relatively recent pull request to fix the issue but it looks like it's stalled a bit.

**Comment by ryankask** [comment]
@facebook-github-bot duplicate #8193

**Comment by MarkEstefanos** [comment]
Thanks for the reply. Looks like a simple fix, I'll see if I can PR it in the next few days.

**Comment by christopherdro** [comment]
Fixes via https://github.com/facebook/react-native/commit/05de4dbb94a4f09fd9a23a423e8328038d7b9c01
