### ISSUE TITLE
Overriding the image for NavigationHeader.BackButton

### ISSUE THREAD

**Issue by EIrwin** [facebook/react-native#10212]
I feel like I must be missing something fairly important. Is there not a way to override the image that is used for the back button for `<NavigationHeader.BackButton>`? 

I have searched the source code and I see the following...

```
const NavigationHeaderBackButton = (props: Props) => (
  <TouchableOpacity style={styles.buttonContainer} onPress={props.onPress}>
    <Image style={styles.button} source={require('./assets/back-icon.png')} />
  </TouchableOpacity>
);

NavigationHeaderBackButton.propTypes = {
  onPress: React.PropTypes.func.isRequired
};
```

How come we cannot pass in the image for this? The color of the images is fixed and that doesn;t work for what I need? 

I am assuming I am missing something...

**Comment by satya164** [comment]
Just use your own `TouchableOpacity` with a custom icon or image.
