### ISSUE TITLE
minHeight behaves erroneously with non integral values

### ISSUE THREAD

**Issue by shahankit** [facebook/react-native#10217]
On providing minHeight with non integral values the children view with flex: 1, gets height = 0.
```
<View style={{minHeight: 1.23}}>
  <View style={{flex: 1, backgroundColor: 'red'}} />
</View>
```

* React Native version: 0.33
* Platform(s) (iOS, Android, or both?): both
* Operating System (macOS, Linux, or Windows?): Mac

**Comment by leeight** [comment]
It works fine on the master branch.

![image](https://cloud.githubusercontent.com/assets/104052/19039073/113805ca-89b1-11e6-8707-4be826b6fbe5.png)

**Comment by shahankit** [comment]
Okay then it might be solved.
