### ISSUE TITLE
Code examples hard to read in docs

### ISSUE THREAD

**Issue by vnctaing** [facebook/react-native#10228]
Hi,

I just started to look over React Native docs, am I the only one that find the code examples hard to read since the examples codes highlight is relatively weak ? Do you think we could improve the readability ?

i.e : [https://facebook.github.io/react-native/docs/statusbar.html](https://facebook.github.io/react-native/docs/statusbar.html)

**Comment by lacker** [comment]
We keep altering those styles, IMO it is kind of "bikesheddy". If you would like to send a PR tweaking it then we would take a look, but if we keep it as is I feel ok with that too.
