### ISSUE TITLE
Docs version out of sync with @latest

### ISSUE THREAD

**Issue by arthuralee** [facebook/react-native#1022]
The docs reflect `master` (since it's auto generated), so it is out of sync with `@latest` which is the latest tagged version. This is a problem because most users are on `@latest` when they `npm install` (or `react-native init`.

Could the website be generated from the latest tagged commit? Or maybe we could introduce some sort of version chooser for the docs site? The latter would be more complicated but probably useful in the long run.

**Comment by brentvatne** [comment]
@arthuralee - The tradeoff of generating from the most recent tagged commit is that we would have to create a new release every time we want to update docs. Version picker could be useful in the long run, at the moment but that could be tricky to implement properly - if you're up for that task feel free to give it a shot and open a PR!

This is not so hard to manage for docs that are generated from markdown files - we just only merge when the feature has been added - but for those that are automatically generated by comments it's a bit trickier.

A couple of ideas:
- Have something like a `/latest` path that exposes the docs from the latest tagged release
- Update markdown docs at any time, generate component docs only from latest tagged commit

**Comment by sahrens** [comment]
Yeah, many doc changes are essentially "bug fixes" which should go out immediately. Only pushing auto-gen docs from tagged releases but the rest from master seems like a good compromise.

**Comment by brentvatne** [comment]
@arthuralee - do you want to have a crack at implementing auto-gen docs from tagged releases and others from master?

**Comment by arthuralee** [comment]
Sounds like a good compromise. I initially brought this up because of issues like #1027. @sahrens' suggestion wouldn't fix those issues, but not being able to publish "bug fixes" of the doc is quite a significant tradeoff.

Would be happy to work on this over the next week :)

**Comment by brentvatne** [comment]
@arthuralee - yeah that must have just been a mistake to merge the docs before the functionality was released :smile: - great! thanks

**Comment by brentvatne** [comment]
@arthuralee - if you're still interested in doing this, feel free to open a PR! It would be very welcome. Closing the issue for now.

**Comment by arthuralee** [comment]
Absolutely. Didn't get time to work on this because I was busy finishing up
school.

On Friday, May 29, 2015, Brent Vatne <notifications@github.com> wrote:

> @arthuralee <https://github.com/arthuralee> - if you're still interested
> in doing this, feel free to open a PR! It would be very welcome. Closing
> the issue for now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/react-native/issues/1022#issuecomment-106932793>
> .
>


-- 
Arthur Lee

**Comment by brentvatne** [comment]
No problem, whenever you get the time :+1: Thanks @arthuralee
