### ISSUE TITLE
`snapToAlignment` and `snapToInterval` don't seem to do anything

### ISSUE THREAD

**Issue by ivanakimov** [facebook/react-native#10224]
### Issue Description

When trying to implement a ScrollView on iOS where childrens' widths are smaller than the parent, the paginated scrolling does not seem to work.

### Steps to Reproduce / Code Snippets

```javascript
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  ScrollView,
  Dimensions
} from 'react-native';

const styles = StyleSheet.create({
	slide: {
		margin: 10,
		backgroundColor: '#eee'
	}
});

class App extends Component {

  render() {

	const { width, height } = Dimensions.get('window');
	const smallerWidth = parseInt(width * .75, 10);

	return (
		<ScrollView
			horizontal
			pagingEnabled
			showsHorizontalScrollIndicator={false}
			snapToAlignment={'center'}
			snapToInterval={smallerWidth}
		>
			<View style={[styles.slide, { width: smallerWidth }]}><Text>One</Text></View>
			<View style={[styles.slide, { width: smallerWidth }]}><Text>Two</Text></View>
			<View style={[styles.slide, { width: smallerWidth }]}><Text>Three</Text></View>
			<View style={[styles.slide, { width: smallerWidth }]}><Text>Four</Text></View>
			<View style={[styles.slide, { width: smallerWidth }]}><Text>Five</Text></View>
			<View style={[styles.slide, { width: smallerWidth }]}><Text>Six</Text></View>
		</ScrollView>
	);

  }

}

AppRegistry.registerComponent('App', () => App);
```

#### Expected Results

The children should snap to proper length with smaller width when scrolling?

### Additional Information

* React Native version: `0.34.1`
* Platform(s) (iOS, Android, or both?): `iOS`
* Operating System (macOS, Linux, or Windows?): `macOS`

**Comment by antoxi4** [comment]
it is not work on Android, on IOS only)

**Comment by ivanakimov** [comment]
@antoxi4 that's why I said `iOS` in **Additional Information**

**Comment by antoxi4** [comment]
@ivanakimov if you want what ScrollView will work like ViewPagerAndroid use this code

```js
<ScrollView
 style={{ width: screenWidth }}}
 horizontal={true}
 onMomentumScrollEnd={this.handleHorizontalScroll}
 pagingEnabled={true}
 scrollsToTop={false}
 scrollEventThrottle={100}
 automaticallyAdjustContentInsets={false}
 directionalLockEnabled={true}
 showsHorizontalScrollIndicator={false}
 showsVerticalScrollIndicator={false}
 >
  <View style={[styles.slide, { width: screenWidth }]}><Text>One</Text></View>
  <View style={[styles.slide, { width: screenWidth }]}><Text>Two</Text></View>
  <View style={[styles.slide, { width: screenWidth }]}><Text>Three</Text></View>
  <View style={[styles.slide, { width: screenWidth }]}><Text>Four</Text></View>
  <View style={[styles.slide, { width: screenWidth }]}><Text>Five</Text></View>
  <View style={[styles.slide, { width: screenWidth }]}><Text>Six</Text></View>
</ScrollView>

```

**Comment by ivanakimov** [comment]
@antoxi4 I'm not exactly sure what that would give... How would that help? This is what it looks like:
![sn](https://cloud.githubusercontent.com/assets/1404596/19048289/95d33ebe-895a-11e6-83a4-47d5ade71819.png)

**Comment by antoxi4** [comment]
@ivanakimov Heh)) ScrollView width must be the same as that of the inner View.

**Comment by ivanakimov** [comment]
I think it's a bug somewhere in RN. I'm still hoping I did something wrong, as the basic example I gave above should work. I'm going over the docs to see if I've misread something, but in the meantime would be nice if someone from the core would comment.

**Comment by antoxi4** [comment]
@ivanakimov  I gave you a working example of my code. I can do a quick clean example for You)

**Comment by ivanakimov** [comment]
@antoxi4 Thank you for the example. Perhaps I'm missing something. If you've got the solution for a centered 75% slide (where the other 2 slides are showing a little bit on the sides), I'd love to see your clean example!

**Comment by antoxi4** [comment]
@ivanakimov Keep the code) https://github.com/antoxi4/ScrollViewAlign

**Comment by ivanakimov** [comment]
This is perfect @antoxi4, thank you :)

**Comment by antoxi4** [comment]
@ivanakimov i made some fixes.)) Enjoy)

**Comment by ivanakimov** [comment]
@antoxi4 I'm guessing there is no way to restrict it to scroll to only the next slide if you scroll hard enough? (most of the time it scrolls 2 or 3 slides...)

**Comment by antoxi4** [comment]
@ivanakimov you can set decelerationRate={'fast'} it will be srolled better)

**Comment by ivanakimov** [comment]
Welp, you're full of answers @antoxi4. Many thanks, all works as expected!
