### ISSUE TITLE
How to do base64 encoding

### ISSUE THREAD

**Issue by seanzarrin** [facebook/react-native#1023]
Hi,

I'm wondering if there is a recommended approach to doing base64 encoding. <code>new Buffer("string").toString('base64')</code> gives me a "cannot find variable Buffer" error. And I've also tried using <code>btoa()</code> https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/btoa but this only seems to work when I have the chrome dev tools open.

Thanks

**Comment by ide** [comment]
Try grabbing the "buffer" module from npm which is built on typed arrays and provides a mostly compatible API.

**Comment by seanzarrin** [comment]
That worked. Thanks!

**Comment by anupkale1984** [comment]
@seanzarrin could you please paste complete example. I am facing same issue. Unable to find correct Buffer npm module.

**Comment by ggcaponetto** [comment]
could you please provide a code snippet?

**Comment by iiitmahesh** [comment]
@seanzarrin how do solve this. could please share code snippet or steps to slove ?

**Comment by CorinneKelly** [comment]
@anupkale1984 @iiitmahesh @ggcaponetto this is probably too late and I don't have any code to share but it looks like he's referring to this module https://www.npmjs.com/package/buffer
