### ISSUE TITLE
ViewPagerAndroid undefined is not an object (evaluating '_this.props')

### ISSUE THREAD

**Issue by proudUzbek** [facebook/react-native#10235]
Hi Everyone!
### Issue Description

I'm new in react-native and i'm just gonna make pager in my app.
### Steps to Reproduce / Code Snippets

So I'm doing it as shown in documentation:

```
render() {
        return (
            <ViewPagerAndroid initialPage={0}>
                <View style={styles.pageStyle}>
                    <Text>First page</Text>
                </View>

                <View style={styles.pageStyle}>
                    <Text>Second page</Text>
                </View>
            </ViewPagerAndroid>
        );
    }
```

and I get this:

![screen shot 2016-10-04 at 16 07 29](https://cloud.githubusercontent.com/assets/4129169/19072404/7a75018a-8a4e-11e6-8e74-6bb47a36b13c.png)

Maybe i'm doing something wrong!

Thank you in advance,and sorry for my english!!
### Additional Information
- React Native version: 0.34.1
- Platform: Android
- Operating System: macOS

**Comment by leeight** [comment]
Perhaps the same issue as #9966

**Comment by faheem-daffodil** [comment]
Faced same issue in React Native0.35
Updated to React Native 0.36 and now working fine

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
