### ISSUE TITLE
stetho-okhttp depends on one or more Android Libraries but is a jar

### ISSUE THREAD

**Issue by ziggy42** [facebook/react-native#10233]
### Issue Description

I'm trying to include react-native in an existing android project. In this project, I'm already using `stetho`, specifically:

```
debugCompile 'com.facebook.stetho:stetho:1.4.1'
debugCompile 'com.facebook.stetho:stetho-okhttp3:1.4.1'
```

When I try to build the project I get an error:

```
Module 'com.facebook.stetho:stetho-okhttp:1.2.0' depends on one or more Android Libraries but is a jar
```

If I remove `stetho` from "the old app" this error goes away
### Additional Information
- React Native version: 0.34.1
- Platform(s) (iOS, Android, or both?): Android
- Operating System (macOS, Linux, or Windows?): Linux

**Comment by jatazoulja** [comment]
+0.35.0

**Comment by lacker** [comment]
Did you ever figure this out? In general it seems like React Native does not necessarily support using different versions of the dependencies that React Native uses itself, which is annoying.

**Comment by aem** [comment]
Was there a resolution? We can't get rid of our version of Stetho because we're using `okhttp3` in our API client. Would be nice to get some contributor help on this

**Comment by JuiceCrawl** [comment]
Having the same issue. Any updates?

**Comment by aem** [comment]
@JuiceCrawl et al - forgot to post, but for the sake of posterity we temporarily resolved as follows:
```
  compile ("com.facebook.react:react-native:0.41.2") {
    exclude group:'com.facebook.stetho', module:'stetho'
  }
```
not sure what side effects this has for RN debugging, but it was the only wait to get the build to pass

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/stetho-okhttp-depends-on-one-or-more-android-libraries-but-is-a-jar

**Comment by Balaji-Gopal** [comment]
Still having the same issue.
Module 'com.facebook.stetho:stetho-okhttp:1.2.0' depends on one or more Android Libraries but is a jar
Any one have the solution please ?
