### ISSUE TITLE
StatusBar is warning "Possible Unhandled Promise Rejection"

### ISSUE THREAD

**Issue by lovato** [facebook/react-native#10236]
### Issue Description

When I run the code below, it looks to work at first.
If I open the app for the first time, or with the app opened, click HOME and open the app again, it really is working.

But in the scenario I have the app in foreground, hit BACK on Android, and then click the app icon again, I see a few things:
a) On a release APK, the StatusBar simply gets GRAY, instead of BLACK (on release apk I tried with black)
b) On a debug APK, if I use blue, the StatusBar keeps blue, but I get a warning.
c) On a debug APK, if I use black the StatusBar gets GRAY on 2nd time, **WITHOUT** the warning.

![image](https://cloud.githubusercontent.com/assets/1213774/19073704/cc64e83e-8a12-11e6-8595-2fb081064253.png)
### Steps to Reproduce / Code Snippets

```
import React, { Component } from 'react';
var ReactNative = require('react-native');

var {
  AppRegistry,
  Text,
  View,
  StatusBar,
} = ReactNative;

export default class App extends Component {
  render() {
    return (
      <View style={{flex:1}}>
        <StatusBar
          backgroundColor="blue" // replace here for black, for testing
          barStyle="light-content"
        />
        <Text>Hi</Text>
      </View>
    )
  }
}

AppRegistry.registerComponent('FooBar', () => App);
```
#### Expected Results

Get a BLUE status bar, in all cases:
- App first run
- User press HOME button, then click on APP icon, app is restored
- User hits BACK button, and then click on APP, app is reopened (this is not working)

If I change from BLUE to BLACK, it gets GRAY and does not produce the warning.
My release APK was only tested with BLACK.
### Additional Information
- React Native version: 0.34
- Platform(s) (iOS, Android, or both?): Android
- Operating System (macOS, Linux, or Windows?): Linux

**Comment by leeight** [comment]
+1

**Comment by leeight** [comment]
After process the back key on the device or simulator, the app exit, take sometime to investigate this issue, i think the call stack can be simplified as following:

1. `ReactContext.java#onHostDestroy`  [Java Code]
2. `StatusBar.js#_updatePropsStack` [async JS Code]
3. `StatusBarModule.java#setColor` [Java Code]  (getCurrentActivity() return null which cause promise rejected)

If we wanna ignore this warning, perhaps should update `Libraries/Components/StatusBar/StatusBar.js` and add `.catch(ignore)` while calling `StatusBarManager.setColor`.

cc @satya164

**Comment by satya164** [comment]
Yeah, I think we should just catch this error in `<StatusBar />` component. This is not actionable by the dev and doesn't make much sense to keep warning. What do you think @janicduplessis ?

**Comment by ide** [comment]
Use .done() if there's nothing more to do with the promise.

**Comment by janicduplessis** [comment]
I think it's fine to ignore the error, we just have to make sure it stays updated properly. Maybe we could update the value of the statusbar again everytime the app comes back in the foreground.

**Comment by satya164** [comment]
@ide not all environments have `.done`. I'm not sure what's different in my RN environment, but I don't have `done`

**Comment by leeight** [comment]
As discuss in the PR, it looks like we should remove the Promise argument from StatusBarManager.java in order to make the API consistent with iOS behavior.

**Comment by marcshilling** [comment]
My status bar becomes hidden and does not return after I exit my app with the back button.

**Comment by leeight** [comment]
@marcshilling I think it has fixed on the master branch, could you test it?

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.

**Comment by davebro** [comment]
Still an issue in RN 0.53
