### ISSUE TITLE
LayoutAnimation with transform

### ISSUE THREAD

**Issue by MarkEstefanos** [facebook/react-native#10230]
There was an issue about this a year ago ([#1311](https://github.com/facebook/react-native/issues/1311)). I'm trying it now, and it still doesn't work. Has there been any progress, or is there a workaround?

**Comment by cshg** [comment]
+1

**Comment by ryancoughlin** [comment]
+1

**Comment by jamesreilly5** [comment]
+1 I don't know a good workaround for this

**Comment by jamesreilly5** [comment]
I ended up using a tweening library to do what I wanted

**Comment by MiLeung** [comment]
@jamesreilly5 Which library?  Does it use Core Animation?

**Comment by jamesreilly5** [comment]
@MiLeung, I used react-native-tween-animation and unfortunately not

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
