### ISSUE TITLE
Polyfills for File and Blob

### ISSUE THREAD

**Issue by brentvatne** [facebook/react-native#10240]
React Native should polyfill the File and Blob APIs so it can work with Parse and Firebase storage. This is a third party solution that solves the problem: https://github.com/wkh237/react-native-fetch-blob/tree/b98143d5d888f49abad43d50990c980ac3a7b4f7/src/polyfill -- but a polyfill like this I believe belongs in core.

**Comment by lacker** [comment]
Can you put this on Product Pains, rather than as an issue? I don't think the "community responsibility" tag has proven to be effective.
