### ISSUE TITLE
Unable to specify simulator iOS version with the `run-ios` cli?

### ISSUE THREAD

**Issue by lsps9150414** [facebook/react-native#10246]
This use to work perfectly: `react-native run-ios --simulator "iPhone 6 (9.3)"`

But it seams that RN 0.34 has disabled the ability to specify the iOS version of the simulator. The same command will return `Cound't find iPhone 6 (9.3) simulator` now.

**Comment by Amurmurmur** [comment]
Same problem, cannot specify the simulator version of iOS :(

**Comment by christopherdro** [comment]
Duplicate #10288
