### ISSUE TITLE
Android Studio 2.2 (SDK 24) -- packager cannot build

### ISSUE THREAD

**Issue by cjshawMIT** [facebook/react-native#10259]
Using a brand-new ReactNative (0.34.1) app with Android Studio 2.2, the package cannot find the Android SDK, because the SDK version number has bumped from 23 to 24.

```
JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> failed to find target with hash string 'android-23' in: /Users/username/Library/Android/sdk
```
### Steps to Reproduce / Code Snippets

```
react-native init TestAndroidProject
cd TestAndroidProject/
react-native run-android
```

Contents of my SDK directory:

```
ls /Users/username/Library/Android/sdk/platforms/
total 0
drwxr-xr-x  14 username  staff  476 Oct  5 14:47 android-24
```
#### Expected Results

App starts up in Android emulator, per the documentation
### Additional Information
- React Native version: 0.34.1
- Platform(s) (iOS, Android, or both?): Android Studio 2.2 / SDK 24
- Operating System (macOS, Linux, or Windows?): Mac OSX 10.11.5

**Comment by chrisjlee** [comment]
Is there a solution? Trying to figure this out.

**Comment by cjshawMIT** [comment]
Like the removed documentation says, I had to install SDK 23 in Android Studio, but it would have been nice if the documentation had said what version SDK the RN packager supports ...

**Comment by chrisjlee** [comment]
Agreed

**Comment by jiangqqlmj** [comment]
yes ,the same question，but i change api level to 23,it is success

**Comment by thienpow** [comment]
there's a simple solution to this.  Just use the latest Android Studio you are having there to open the android project in your react-native project.  Gradle will do the necessary fix for you, just click to fix it when it suggest you to do the fix or update.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/android-studio-22-sdk-24----packager-cannot-build
