### ISSUE TITLE
Width 100% height auto image

### ISSUE THREAD

**Issue by trongan** [facebook/react-native#10256]
I want to display image full width and height auto with style
{width:'100%', height:'auto'} but React Native not support.  I need help, thank you.

**Comment by sunkibaek** [comment]
Maybe you can try to use this: https://github.com/huiseoul/react-native-fit-image

**Comment by podrivo** [comment]
Why? Just why?
What is the best solution for this?

**Comment by IJMacD** [comment]
If you don't mind some cropping this works for me:

```
<Image
  resizeMode={'cover'}
  style={{ width: '100%', height: 200 }}
  source={{uri: temp}}
/>
```
> source: https://stackoverflow.com/a/45188904/1228394

**Comment by AngSin** [comment]
This issue should not be closed, it hasn't been solved yet

**Comment by viztor** [comment]
has not been resolved
