### ISSUE TITLE
PickerIOS does not accept testID from Picker

### ISSUE THREAD

**Issue by asu91** [facebook/react-native#10258]
### Issue Description

Picker.js docs show that it supports testIDs and passes it to its children. However, its children do not accept testIDs.
#### Expected Results

PickerIOS and PickerIOS.item should accept testIDs.

Thank you!

**Comment by lacker** [comment]
AFAICT the Picker docs do not currently express that children get test ids, just the Picker itself. https://facebook.github.io/react-native/docs/picker.html So as far as I can tell the docs are currently accurate here. I'm going to close this issue but please feel free to reopen if I am missing something here!
