### ISSUE TITLE
Navigator should call componentWillUnmount on a scene after the pop transition completes. 

### ISSUE THREAD

**Issue by mjw56** [facebook/react-native#1025]
As mentioned in #1014, after dismissing a scene via a gesture using Navigator, the dismissed component's ```componentWillUnmount``` lifecycle hook is not being called.

I have submitted a fix in #1018 which calls ```this._handlePop()``` when a gesture triggers a route change. The result is that the ```componentWillUnmount``` hook of the dismissed component is called. 

Any help to review this and make sure it is the right fix is appreciated. Thanks. :)

**Comment by brentvatne** [comment]
This is fixed now!
