### ISSUE TITLE
Support web workers

### ISSUE THREAD

**Issue by jsdevel** [facebook/react-native#10269]
I scoured the docs but couldn't find where Worker is exposed.

**Comment by Etheryte** [comment]
Perhaps a more general multi-threading API would be more fitting for RN? Though I can see the appeal, as web workers are very straightforward to both understand and use.

**Comment by lacker** [comment]
I think for now this is a "wontfix". Maybe if you have a specific proposal in mind it would be interesting to flesh it out in more detail and open a RFC-type issue? For now I am going to close this though.

**Comment by amadeus** [comment]
Shouldn't Workers be a JSCore feature, not specific to React Native?

**Comment by ide** [comment]
Workers are a Safari feature, not a JS feature. Some mechanisms like shared memory are JS features though.

**Comment by jsdevel** [comment]
> Workers are a Safari feature, not a JS feature. Some mechanisms like shared memory are JS features though.

Not sure what you mean by this @ide.  Web Workers are in the standards.  MDS shows all of the browsers supporting at least _some_ of the standard: https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers#Browser_compatibility

**Comment by amadeus** [comment]
@jsdevel I think what he means, is that workers are actually built into safari, not JSCore, the Js engine that React Native uses since it not loading up a browser.

So yes, they do exist in all browsers, but when it comes to the split of what the feature is apart of, it means that React Native actually doesn't have access to them.

**Comment by jsdevel** [comment]
I think the fact that safari has them built in is irrelevant.   All browsers support the WW spec to some extent.

RN has ported WebSocket, fetch, and GeoLocation.

**Comment by amadeus** [comment]
Well there are 2 discussions going on here. I was just asking about it being in JSCore which means it should be available. But it's probably not that trivial to add
