### ISSUE TITLE
Question: Best practice for CommandCenter -> ReactJS view comms?

### ISSUE THREAD

**Issue by jaygarcia** [facebook/react-native#1026]
I'm currently working on a Chiptunes mode player and am wiring in iOS CommandCenter.  CommandCenter is responsible for listening to events from the home screen, bottom drawer, USB command inputs (car audio controllers, etc) and headphone remotes.

The wiring needs to be complete so that I can wire up events such as play, pause, next and previous track. 

The current communication is as such:
CommandCenter -> ViewManager -> STOP

I'm having trouble figuring out how to publish events from the view manager to the view (there will only be one "Player" view ever.  

Does anyone have any strategies to overcome this?  Should I be thinking of app-level events?

Here's the command center hook if anyone's wondering:

```
    MCModPlayer *player = [MCModPlayer sharedManager];
    
    /** Remote control management**/
    MPRemoteCommandCenter *commandCenter = [MPRemoteCommandCenter sharedCommandCenter];
    
 
    [commandCenter.playCommand addTargetWithHandler:^MPRemoteCommandHandlerStatus(MPRemoteCommandEvent *event) {
        [player resume];
        
        NSLog(@"playCommand");

//        How does one emit an event to a view from the view controller (View Manager) when the VM doesn't know of a particular view?
//        [self.bridge.eventDispatcher sendInputEventWithName:@"topChange" body:body];

        return MPRemoteCommandHandlerStatusSuccess;
    }];
```

**Comment by nicklockwood** [comment]
Take a look at the implementation for RCTWebView, which solves a similar problem.

**Comment by nicklockwood** [comment]
Although, if your command center is a singelton, and doesn't have any UI of its own, should it perhaps just be a regular bridge module, rather than a view manager?

**Comment by nicklockwood** [comment]
It sounds like your problem is more similar to something like RCTReachability, or RCTLocationObserver, where the native module just has methods and sends events, but has no view of its own.

**Comment by jaygarcia** [comment]
I started down that route but could not figure out how to inform the Ui of a state change. :-/

Reading through the source, I found that the only way to go from bridge > view is to route events via react tag.  

I'm a newb. 

JG

 @moduscreate

:: sent from my mobile device ::

**Comment by jaygarcia** [comment]
I have not looked at that source.  I will after I get home.  :)

Many thanks. You guys flipping own for working on the weekends. 

JG

@moduscreate

:: sent from my mobile device ::

**Comment by jaygarcia** [comment]
@nicklockwood !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

You effing nailed it dude!  Thank you so much.

![](http://content.screencast.com/users/djliquidice/folders/Snagit/media/04f6b2f0-2ff7-480f-99dc-93ef9bb93a5f/2015-04-26_13-47-32.png)

**Comment by jaygarcia** [comment]
For those interested, here's the product of this effort: 

https://www.youtube.com/watch?v=VaZnJ-_R3rU

**Comment by sahrens** [comment]
Did you use an event emitter?

**Comment by jaygarcia** [comment]
@sahrens eventDispatcher. It's working like a friggin champ. 

```
 [commandCenter.previousTrackCommand addTargetWithHandler:^MPRemoteCommandHandlerStatus(MPRemoteCommandEvent *event) {
        //TODO: Handle previous track (have no idea what to do here atm);
        NSLog(@"previousTrackCommand");
        
       [_bridge.eventDispatcher sendDeviceEventWithName:@"commandCenterEvent" body:@{
            @"eventType" : @"previousTrack"
        }];
        return MPRemoteCommandHandlerStatusSuccess;
    }];
```

**Comment by brentvatne** [comment]
@jaygarcia - how about publishing a library that exposes this functionality to JS?
