### ISSUE TITLE
ScrollView is inconsistent in android on resume with keyboard open

### ISSUE THREAD

**Issue by atlanteh** [facebook/react-native#10260]
### Issue Description

As I understand, it's the App's responsibility to handle the keyboard events and to add padding\margin if the keyboard is open, and remove it when the keyboard is dismissed, and this seems to be the regular case for my ScrollView. However, when pressing the home button when the keyboard is open and then returning to the app, the ScrollView suddenly shrinks to the space left.
When combined with keyboardDidShow & keyboardDidHide this results in The margin of the keyboard height being shown on top of the keyboard.
### Steps to Reproduce / Code Snippets

Code:

``` jsx
import React from 'react';
import { View, Keyboard, TextInput, ScrollView } from 'react-native';

export default class App extends React.Component {
    constructor(props) {
        super(props);
        this.state = {};
    }

    componentWillMount() {
        // const handleKeyboardVisible = (e) => this.setState({keyboardHeight: e.endCoordinates.height});
        // const handleKeyboardHidden = () => this.setState({keyboardHeight: 0});
        // this.keyboardShowListener = Keyboard.addListener('keyboardDidShow', handleKeyboardVisible);
        // this.keyboardHideListener = Keyboard.addListener('keyboardDidHide', handleKeyboardHidden);
    }

    componentWillUnmount() {
        // this.keyboardShowListener.remove();
        // this.keyboardHideListener.remove();
    }

    render() {
        const {keyboardHeight} = this.state;
        return (
            <ScrollView style={{flex: 1, marginBottom: keyboardHeight, backgroundColor: 'orange'}} keyboardShouldPersistTaps>
                <View>
                    <TextInput style={{backgroundColor: 'green', marginBottom: 360}} />
                    <View style={{backgroundColor: 'red', alignSelf: 'stretch', height: 200}} />
                </View>
            </ScrollView>
        );
    }
}

```

Step 1:
This is a simple ScrollView with a TextInput at the top & a red view at the bottom
![screenshot_2016-10-05-22-47-39](https://cloud.githubusercontent.com/assets/3952700/19129256/5099d050-8b4f-11e6-81a6-67bb87a4306e.png)

When opening the keyboard, The ScrollView ignores the keyboard so you can't Scroll to the red View:
![screenshot_2016-10-05-22-47-47](https://cloud.githubusercontent.com/assets/3952700/19129282/7262624c-8b4f-11e6-9a7d-ae8d2b32e56e.png)

After pressing the Android home button & then returning back to the app, suddenly you can Scroll to the red View
![screenshot_2016-10-05-22-47-57](https://cloud.githubusercontent.com/assets/3952700/19129312/9923dc4e-8b4f-11e6-8e6c-39b4ef7c093d.png)

If you uncomment componentWillMount & componentWillUnnmount then the ScrollView does avoid the keyboard height. But then when pressing home button and returning, a keyboard size white screen shows up:
![screenshot_2016-10-05-22-48-27](https://cloud.githubusercontent.com/assets/3952700/19129623/a4c7fa2a-8b50-11e6-8f3a-4d20746f7838.png)

I tried reverting all the way to react-native@0.30.0 and it's all the same.
#### Expected Results

The ScrollView should ignore the keyboard even after app resume.
### Additional Information
- React Native version: 0.34.1
- Platform(s) (iOS, Android, or both?): Android
- Operating System (macOS, Linux, or Windows?): Windows

**Comment by hey99xx** [comment]
Not necessarily a solution to your problem, but there is a soft input mode settings on activities that sort of controls on screen keyboard interactions. Can you play around with https://developer.android.com/guide/topics/manifest/activity-element.html#wsoft and tell me if there's a solution through here? Another developer had a similar problem in my company and I believe he hacked around AndroidManifest to configure this mode.

**Comment by atlanteh** [comment]
This actually works!! setting android:windowSoftInputMode="adjustResize" solves it :)
thx!

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/scrollview-is-inconsistent-in-android-on-resume-with-keyboard-open
