### ISSUE TITLE
NavigationHeader doesn't call renderLeftComponent or renderRightComponent on state change

### ISSUE THREAD

**Issue by corracom** [facebook/react-native#10273]
### Issue Description

When a state or props change occurs without a scene change within a NavigationCardStack the renderHeader function is executed but the renderLeftComponent and renderRightComponent functions are not.
### Steps to Reproduce / Code Snippets
1. Define a renderHeader function for NavigationCardStack
2. Return a NavigationHeader component with a renderLeftComponent or renderRightComponent render function
3. place a console.log within the renderLeftComponent function
4. Change the parent components state
5. Observe that the renderLeftComponent function is not called

```
<NavigationHeader
      {...props}
          style={styles.navigationHeader}
      renderTitleComponent={this._renderTitleComponent}
          renderLeftComponent={this._renderLeftComponent}
      renderRightComponent={this._renderRightComponent}
                />
```
#### Expected Results

renderLeftComponent and renderRightComponent render functions should be called if the parent components state changes - the ability change left and right buttons on a NavigationHeader while on the same scene is basic functionality for an iOS app (for example changing an edit button to a save button). 
### Additional Information
- React Native version: 0.33.0
- Platform(s) (iOS, Android, or both?): iOS
- Operating System (macOS, Linux, or Windows?): MacOS

Strangely enough a solution for this is to add a view inside the NavigationHeader component like this:

```
<NavigationHeader
                    {...props}
          style={styles.navigationHeader}
                    renderTitleComponent={this._renderTitleComponent}
          renderLeftComponent={this._renderLeftComponent}
                    renderRightComponent={this._renderRightComponent}
            >
          //This is a hack to force re-render of navigation header components
          <View />
        </NavigationHeader>
```

I don't know why this works or whether it has performance implications but it will do for now.

**Comment by ryankask** [comment]
`NavigationHeader` implements `shouldComponentUpdate()` (https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/NavigationExperimental/NavigationHeader.js#L123) so unless the passed props change, it won't change.

There was commit a while back that removed `shouldComponentUpdate()` policies: https://github.com/facebook/react-native/commit/6c4d3c39c670e087930fcdae566e82db4b081113. It looks like this one remained.

**Comment by lacker** [comment]
Hi, thanks for reporting this! We are now working towards deprecating NavigationExperimental, so we are not fixing bugs there any more, and rather encouraging people towards https://github.com/react-community/react-navigation . I'm going to close this issue but if you are interested in checking out react-navigation it would be curious to see whether similar problems exist there, since it works pretty similarly.

**Comment by voidale** [comment]
@lacker finally a great navigation library cool thanks for referring me to it!
