### ISSUE TITLE
The LayoutAnimation example is broken in the open source docs

### ISSUE THREAD

**Issue by blairvanderhoof** [facebook/react-native#10279]
![image](https://cloud.githubusercontent.com/assets/833890/19175863/6d451e76-8bef-11e6-8f2d-588de551878f.png)
The LayoutAnimation example is broken in the open source docs.
https://facebook.github.io/react-native/docs/layoutanimation.html

**Comment by blairvanderhoof** [comment]
It would be good to do a pass through of all the examples and verify they work.

**Comment by christopherdro** [comment]
@facebook-github-bot bugfix

**Comment by lacker** [comment]
This looks like it's fixed now. Thanks for reporting this!
