### ISSUE TITLE
flag to open a new simulator

### ISSUE THREAD

**Issue by pvinis** [facebook/react-native#10284]
add a `-n` flag or something similar to the `react-native` cli, so that i can run `react-native run-ios --simulator "sim1" -n`, which is the same as without the `-n`, and it opens a simulator `sim1` that runs the app. afterwards, i can do `react-native run-ios --simulator "sim2" -n` and it opens a new simulator window, with my other simulator `sim2`, and runs some other app.

is there a way to do that now?

**Comment by rturk** [comment]
Duplicate: https://github.com/facebook/react-native/issues/10288
