### ISSUE TITLE
SwipeableListView Datasource Updating

### ISSUE THREAD

**Issue by alexcurtis** [facebook/react-native#10283]
### Issue Description

Updating a SwipeableListView + Datasource Re-Renders Incorrectly:

```
this.state = { dataSource: SwipeableListView.getNewDataSource() };`
...
getDataSource(){
  const items = this.props.items;
  return this.state.dataSource.cloneWithRowsAndSections({s1: items}, ['s1']);
}
...
<SwipeableListView
  dataSource={this.getDataSource()}
  ...
/>
```

If I remove an element from `items` (say the first in the array) and the component re-renderers, the last item in the list is always removed. It seems to be a problem with `SwipeableListView.getNewDataSource` as `List` seems to work fine.

I have tried adding keys to the rendered rows (using rowId) - but its not had any impact.

If I re-create the data source (`SwipeableListView.getNewDataSource()` within `getDataSource()` it works fine, but I'm concerned that it might not be very efficient.

**EDIT:** It seems to happen if I try and remove an item when it hasn't been previously swiped open
- React Native version: 0.35.0-rc.0
- Platform(s) (iOS, Android, or both?):  both
- Operating System (macOS, Linux, or Windows?):  macOS

**Comment by chirag04** [comment]
Make sure each of your items object is having an 'id' field

**Comment by alexcurtis** [comment]
@chirag04 Each one of the items has a unique id string

**Comment by alexcurtis** [comment]
Ah. I think I know what this is. It happens if I try and remove an item that has not already been swiped open:

Culprit:
```
return (
          (row1.id !== this._previousOpenRowID && row2.id === this._openRowID) ||
          (row1.id === this._previousOpenRowID && row2.id !== this._openRowID) ||
          params.rowHasChanged(row1, row2)
        );
```

**Comment by alexcurtis** [comment]
Looks to be if you set `bounceFirstRowOnMount`. It always returns false when calling `shouldComponentUpdate()` in SwipeableRow.js:

```
if (this.props.shouldBounceOnMount && !nextProps.shouldBounceOnMount) {
      // No need to rerender if SwipeableListView is disabling the bounce flag
      return false;
    }

    return true;
```

**Comment by lacker** [comment]
OK, so do you have a complete example of this bug happening? It is not clear to me whether you're saying "OK it's fixed for me now" or saying "OK I now have a clearer view of this bug".
