### ISSUE TITLE
`setNativeProps` does not work with `StatusBar` component 

### ISSUE THREAD

**Issue by SandroMachado** [facebook/react-native#10285]
### Issue Description

I am trying to use the `setNativeProps` function with the `StatusBar`
 component and it is not working. I tried with the `View` component and it works as expected. Am I missing something?

### Steps to Reproduce / Code Snippets

My `StatusView` in the render method.
```
<StatusBar
  ref={ component => this._statusBar = component }
  backgroundColor = { shadeStatusBarColor(this.pageArray[0].backgroundColor, -0.3) }
/>
```

The code to change the background color.
```
this._statusBar.setNativeProps({
  backgroundColor: shadeStatusBarColor(this.pageArray[index].backgroundColor, -0.3)
});
```
#### Expected Results

Change the color of the status bar, instead I get an error `this._statusBar.setNativeProps is not a function`. For the `View` component it works as expected.

### Additional Information

* React Native version: 0.34
* Platform(s) (iOS, Android, or both?): both
* Operating System (macOS, Linux, or Windows?): macOS

**Comment by ide** [comment]
Could you explain why you want to call setNativeProps instead of setting the props via JSX normally?

**Comment by SandroMachado** [comment]
I am trying to perform a workaround to by pass this [issue](https://github.com/FuYaoDe/react-native-app-intro/issues/38).

**Comment by hey99xx** [comment]
Where in the documentation did you see that `<StatusBar>` component has `setNativeProps` method. It's not a default react component method, not all react components implement it. Try using JSX instead. Also the documentation notes `backgroundColor` is only for Android, so you will probably be disappointed even when your code works.

**Comment by SandroMachado** [comment]
I know, the `backgroundColor` property only works for android. But the issue is in both platforms.

You can find in the documentation a place where says which componentes support the method `setNativeProps`?  I believe all the native components should support it.

**Comment by hey99xx** [comment]
> I believe all the native components should support it, is that right?

I don't think this is right. As far as I understand, some components have `setNativeProps` and other don't. @ide or an official contributor can enlighten us about this assumption.

There is also http://facebook.github.io/react-native/releases/0.34/docs/statusbar.html#setbackgroundcolor which might work.

**Comment by ide** [comment]
setNativeProps was introduced for quickly and directly setting props on native components when reconciliation would otherwise be too slow. There's little reconciliation to do with StatusBar though and the component wraps the imperative API anyway so you should either use JSX as suggested or the imperative API here: https://facebook.github.io/react-native/docs/statusbar.html#imperative-api

Generally you should not be calling setNativeProps unless you specifically want to bypass reconciliation. But if you're using it just because it seems convenient, there is usually another solution.

**Comment by SandroMachado** [comment]
I really need to bypass the reconciliation to fix the issue I mentioned above. So, I cannot use the JSX or the imperative API. 

I tried to use the imperative API in the reference, and I got the same issue `this._statusBar.setBackgroundColor is not a function`.

```
 this._statusBar.setBackgroundColor(shadeStatusBarColor(this.pageArray[index].backgroundColor, -0.3), false);
```

**Comment by ide** [comment]
The docs say to use static methods.

**Comment by SandroMachado** [comment]
@ide, shame on me! Using the static API it works. Thanks :)
