### ISSUE TITLE
ListView with section headers fails to re-render properly

### ISSUE THREAD

**Issue by ds300** [facebook/react-native#10298]
### Issue Description

When using ListView with sticky section headers, moving an item **up** in the list causes re-rendering to produce whack results. AFAICT moving an item **down** works just fine.

Here is an example with rows grouped by a period in time. Tapping on a row sets its time to 'Today' and should push it toward the top of the list.

![listviewbug](https://cloud.githubusercontent.com/assets/1242537/19212841/178e7618-8d5b-11e6-9a9e-52bc9b331b86.gif)

### Steps to Reproduce / Code Snippets

The source for the pictured example is available at [https://github.com/ds300/ListViewBug/blob/master/index.ios.js](https://github.com/ds300/ListViewBug/blob/master/index.ios.js)

Scroll to the bottom, tap one of the rows.

#### Expected Results

There should be no overlapping or duplicated rows, the tapped row should move to the 'Today' section.

### Additional Information

* React Native version: 0.34.1
* Platform(s) (iOS, Android, or both?): iOS
* Operating System (macOS, Linux, or Windows?): macOS

Possibly related to #10134 

This bug report was sponsored by [Futurice's Spice Program](http://futurice.com/blog/year-2015-in-company-sponsored-open-source).

**Comment by sharq1** [comment]
Please see related issue: https://github.com/facebook/react-native/issues/9200

**Comment by sharq1** [comment]
+1

**Comment by ds300** [comment]
Oh dang, I didn't find that issue when I searched. This is a duplicate, then. Apologies.
