### ISSUE TITLE
Text Shadow (elevation) for Android Support

### ISSUE THREAD

**Issue by larryranches** [facebook/react-native#10294]
### Issue Description

Text Component to apply Shadow (elevation) styles for Android is not working but is working in ios. Is this even supported for the Text component for Android?
### Steps to Reproduce / Code Snippets
- Apply `elevation: 3` style to a text component in Android
#### Expected Results
- Shadow should apply to text component in Android
### Additional Information
- React Native version: 0.33
- Platform(s) (iOS, Android, or both?): Android
- Operating System (macOS, Linux, or Windows?): OSX

**Comment by larryranches** [comment]
Any ideas or updates on adding shadow/elevation to the Text component Android? Would be much helpful

**Comment by rayshih** [comment]
I am using version 0.38. And it works

Seems like we need to at least specify `textShadowOffset`

ref: https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/text/ReactTextShadowNode.java#L166

**Comment by larryranches** [comment]
@rayshih Just tested this on rn 0.39 and textShadowOffset does work. Thanks!
