### ISSUE TITLE
[Android] PictureListener used in WebViews onContentSizeChanged is quite deprecated

### ISSUE THREAD

**Issue by eremzeit** [facebook/react-native#10293]
PictureListener has been deprecated since API 12.  

Used here:
https://github.com/facebook/react-native/blob/22de6550d63c16066e2fbd79906d255ff8c8fea1/ReactAndroid/src/main/java/com/facebook/react/views/webview/ReactWebViewManager.java#L417

Referenced here:
https://developer.android.com/reference/android/webkit/WebView.PictureListener.html

**Comment by eremzeit** [comment]
note: It has been deprecated since API 12.  I incorrectly originally said since 11.

**Comment by christopherdro** [comment]
@facebook-github-bot icebox

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/android-picturelistener-used-in-webviews-oncontentsizechanged-is-quite-deprecate
