### ISSUE TITLE
It seems something went wrong while linking.

### ISSUE THREAD

**Issue by tigerohuang** [facebook/react-native#10300]
rnpm-install ERR! It seems something went wrong while linking. Error: Expected "/*", "//" or "{" but "<" found. 
Please file an issue here: https://github.com/facebook/react-native/issues 

Expected "/*", "//" or "{" but "<" found.

**Comment by leeight** [comment]
#10032

**Comment by ryankask** [comment]
@facebook-github-bot duplicate #10032
