### ISSUE TITLE
NavigatorIOS titlebar height?

### ISSUE THREAD

**Issue by pvinis** [facebook/react-native#10309]
Hello. I am trying to use `NavigatorIOS` but i want my components to start right below the titlebar. is there a way to get the titlebar height? i have non-scrolling views that should stay below the titlebar always, and scrolling views that can go on the background of the titlebar. Thanks.

**Comment by ryankask** [comment]
`NavigatorIOS` uses the standard UINavigationBar. I'm not sure if the values are directly accessible from this component but the sizes are standard.

The status bar is 20pt and In portrait mode the navigation bar is 44pt, so 64pt in total. In landscape mode, the navigation bar is 32pt tall.

You could actually grab these values from `Navgiator` (except the landscape height): 

```
import NavigatorNavigationBarStylesIOS from 'NavigatorNavigationBarStylesIOS';

NavigatorNavigationBarStylesIOS.General.NavBarHeight         // === 44
NavigatorNavigationBarStylesIOS.General.StatusBarHeight      // === 20
NavigatorNavigationBarStylesIOS.General.TotalNavHeight       // === 64
```

Also, check out this document http://ivomynttinen.com/blog/ios-design-guidelines#nav-bar for more details.

This is also a helpful graphic: https://designcode.io/cloud/chapter1/Design-NavigationBar.jpg

**Comment by jacobp100** [comment]
You could also add a scroll view and disable scrolling.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/navigatorios-titlebar-height
