### ISSUE TITLE
RN 0.34 - Fetch CORS debug scheme on iOS 10 don't work 

### ISSUE THREAD

**Issue by davidck** [facebook/react-native#10307]
However, running it on iOS 9.3 simulator works on both debug and release schemes.  iOS 10 also works on release.

Issue is encountered only with iOS 10 sim on chrome debug.  It throws the same error as missing the ATS exceptions but they are defined.

**Comment by khanghoang** [comment]
@davidck I just tested RN 0.34.1 on simulator + chrome debug and it worked fine.

**Comment by davidck** [comment]
@khanghoang awesome, just upgrade it to 0.35 and it's resolved.  Thanks
