### ISSUE TITLE
Nested <Text> clicks

### ISSUE THREAD

**Issue by agentcooper** [facebook/react-native#1030]
Hey.

I want to render some hypertext, e.g
```js
var hypertext = 'this is <a href="http://facebook.com">facebook.com</a> link';
```

I tried programmatically splitting into
```jsx
<Text>
  <Text>this is </Text>
  <Text onPress={this.onLinkPress} style={{color: '#0000ff'}}>facebook.com</Text>
  <Text> link</Text>
</Text>
```

but obviously `onPress` wouldn't work, because nested text is [transformed](https://facebook.github.io/react-native/docs/text.html#nested-text).

1. Should a message be thrown if `onPress` is being set on the nested text?
2. Is there any good way to get a click handler on the link?

**Comment by brentvatne** [comment]
How abut this?

```
<View>
  <Text>this is </Text>
  <Text onPress={this.onLinkPress} style={{color: '#0000ff'}}>facebook.com</Text>
  <Text> link</Text>
</View>
```

**Comment by agentcooper** [comment]
@brentvatne but then text formatting would be incorrect (multiple lines). I tried yours example with `flexDirection: 'row'; flexWrap: 'wrap'`, but formatting is not the same.

**Comment by brentvatne** [comment]
Sorry that was silly of me, this should work just fine:

```javascript
            <Text>
              <Text>this is </Text>
              <TouchableOpacity onPress={() => { AlertIOS.alert('hi!') }}>
                <Text style={{color: '#0000ff'}}>facebook.com</Text>
              </TouchableOpacity>
              <Text> link</Text>
            </Text>
```

**Comment by vkurchatkin** [comment]
I think it's not possible currently, but could be implement with `NSLinkAttributeName`

**Comment by sahrens** [comment]
Yeah, we need to support this. cc @a2

**Comment by a2** [comment]
I can look at this more tomorrow, but I was under the impression that we supported inline `onPress` handlers (see [here](https://github.com/facebook/react-native/blob/89495635da993bed14456f4955c8b10c8e7372bd/Examples/UIExplorer/TextExample.ios.js#L56-L58)).

**Comment by agentcooper** [comment]
Ok, thanks everyone, this actually works fine, I was just passing wrong `this` :weary:
Made a small module as a result https://github.com/agentcooper/react-native-hypertext

**Comment by breadadams** [comment]
I know this is an old issue, but stumbled across it today after getting an error:

`views nested within a <Text> must have a width and height`

I got this from trying to insert a `<TouchableOpacity>` inside a text component. Like @brentvatne suggested.

For me, the correct solution was a mix of your two answers:

```javascript
<Text>
  <Text>{`This is `}</Text>
    <Text
        style={{color: '#0000ff'}}
        onPress={() => { AlertIOS.alert('hi!') }}>
        {`facebook.com`}
     </Text>
  <Text>{` link`}</Text>
</Text>
```
