### ISSUE TITLE
RN android crash if user lost connection

### ISSUE THREAD

**Issue by indie314** [facebook/react-native#10310]
Hello,

I'm using android and react-native + redux.

In my application I have a route **chat**, when this mounts I dispatch an action which fetch some data from the server.

chat.js
```
  componentDidMount() {
    this.props.actions.getThreads(this.props.token)
  }
```

actions.js
```
export const getMessages = (token) => ({
  types: [ types.GET_MESSAGES_PENDING, types.GET_MESSAGES_FULFILLED, types.GET_MESSAGES_REJECTED ],
  payload: {},
  promise: () => new Promise( (resolve, reject) => API.getMessages(token, resolve, reject) )
})
```
api.js
```
export const getMessages = (token, resolve, reject) =>
  API.get('messages', token)
    .then( res => res.json() )
    .then( json => json.error ? reject(json) : resolve(json.threads) )
    .catch( e => reject(e) )
```

My issue looks like this:

> user online -> user dispatch fetch -> user lost connection -> app crash

So its this a bug or I just do something wrong?

I want to catch if the connection is lost.

Thanks!

I'm using:
```
react-native-cli: 0.2.0
react-native: 0.31.0
```

**Comment by leeight** [comment]
You should post the exception stack trace...

**Comment by indie314** [comment]
no stack trace, app dosent crash if is in development mode.

**Comment by rturk** [comment]
@indie314 can you run in our device and debug via adb?
