### ISSUE TITLE
Random RCTNetworkTask Crashes on RN 0.34.1: EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by joncursi** [facebook/react-native#10316]
I've been getting intermittent app crashes due to some `RCTNetworkTask` issues ever since upgrading to RN 0.34.1. The app will randomly lock up and Xcode will point me to the following line:

<img width="1400" alt="screen shot 2016-10-09 at 5 10 23 pm" src="https://cloud.githubusercontent.com/assets/4974609/19223672/7f3fe8e4-8e43-11e6-828a-46a55f863eff.png">

`EXC_BAD_ACCESS`. As a JavaScript developer, this `*.m` code looks like gibberish to me. Any ideas on what this means and how I can go about fixing it? Thanks!

**Comment by magrinj** [comment]
Same problem for me, I got this crash a lot of time!

**Comment by gre** [comment]
dup https://github.com/facebook/react-native/issues/10274 , please check if the patch https://github.com/facebook/react-native/pull/10280 fix it for you and upvote the PR :)

**Comment by ryankask** [comment]
@facebook-github-bot duplicate #10274
