### ISSUE TITLE
Cannot resolve onPause method for React Native sample app

### ISSUE THREAD

**Issue by oliversisson** [facebook/react-native#10326]
### Issue Description

I try to implement https://facebook.github.io/react-native/docs/integration-with-existing-apps.html

but when I try to implement the activity lifecycle callbacks onPause, onResume and onDestroy, my Android Studio complains: cannot resolve method onPause.
### Steps to Reproduce / Code Snippets

https://facebook.github.io/react-native/docs/integration-with-existing-apps.html
#### Expected Results

Expecting mReactInstanceManager.onPause() to exist.
### Additional Information
- React Native version: 0.34.1 (see below)
- Platform(s) (iOS, Android, or both?): Android, existing app
- Operating System (macOS, Linux, or Windows?): macOS

npm list
├─┬ react@15.3.2
│ ├─┬ fbjs@0.8.5
│ │ ├── core-js@1.2.7
│ │ ├── immutable@3.8.1
│ │ ├── isomorphic-fetch@2.2.1
│ │ └── ua-parser-js@0.7.10
│ ├─┬ loose-envify@1.2.0
│ │ └── js-tokens@1.0.3
│ └── object-assign@4.1.0
└─┬ react-native@0.34.1

**Comment by lacker** [comment]
It doesn't seem like that doc refers to `onPause` any more, so I think this is a case where the docs have now been fixed.
