### ISSUE TITLE
overflow:visible is not working on Android devices

### ISSUE THREAD

**Issue by 12d** [facebook/react-native#10322]
Here is my test code:

`<View style={{height: 100,width:100,backgroundColor:'blue',marginTop: 100,overflow:'visible'}}>
                <View style={{height: 250,width:250,backgroundColor:'red',overflow:'visible', transform:[{translateY: -40}]}}></View>
            </View>`
result: The red box is cropped by the blue box

**Comment by gre** [comment]
see https://github.com/facebook/react-native/issues/3198

**Comment by ryankask** [comment]
@facebook-github-bot duplicate #3198

**Comment by ryankask** [comment]
@facebook-github-bot duplicate #3198

**Comment by stoffern** [comment]
@lacker this is a dupe, can be closed 😉
