### ISSUE TITLE
Keychain access?

### ISSUE THREAD

**Issue by a-warner** [facebook/react-native#1032]
Just wondering, do you have plans to add some kind of keychain API? If not, is there a suggested safe way to store user credentials (e.g. an auth token) or do I have to roll my own?

Thanks! Sorry if this is a repeat, I looked in the issues list and didn't find anything (did some googling around too / checked out [React.parts](http://react.parts/native-ios) and it doesn't seem like anyone else has built one).

**Comment by sahrens** [comment]
Nothing right now, but wouldn't be super tricky to build a module for it if you're so-inclined :)

**Comment by a-warner** [comment]
cool, thanks for the quick response

**Comment by lelandrichardson** [comment]
+1 for this. I was just looking for the same thing. If you end up making a module, could you let me know?

**Comment by nicklockwood** [comment]
I'm working on something now. Will keep you posted.

**Comment by a-warner** [comment]
Awesome!!

On Monday, April 27, 2015, Nick Lockwood <notifications@github.com> wrote:

> I'm working on something now. Will keep you posted.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/react-native/issues/1032#issuecomment-96648803>
> .
>


-- 
Andrew Warner
wwarner.andrew@gmail.com

**Comment by johanneslumpe** [comment]
@nicklockwood got something here? If not Ican write a module for it.

**Comment by nicklockwood** [comment]
We don't have one yet. I'm working on something, but I don't have an ETA yet, so feel free to make one.

**Comment by ardalann** [comment]
+1

**Comment by oblador** [comment]
I've done a very simple implementation available as [react-native-keychain](https://github.com/oblador/react-native-keychain) to fit my most urgent needs. Will add more API support soon, issues/PRs are welcome.

**Comment by brentvatne** [comment]
Nice one @oblador!
