### ISSUE TITLE
TextInput has error regarding max-length for Korean (unicode) characters

### ISSUE THREAD

**Issue by colus001** [facebook/react-native#10320]
### Issue Description

When `maxLength` is set to `TextInput`, Korean character with prop consonant is located just before max length unable to complete last character.
### Steps to Reproduce / Code Snippets
1. Create TextInput component.

```
<TextInput
  style={{ 
    fontSize: 18,
    fontWeight: '300',
    paddingBottom: 3,
  }}
  maxLength={5}
/>
```
1. Enter using 5 length Korean text `텍스트인풋` with keyboard.
   - copy and paste works fine.
   - after `인` you can not enter any character other than `ㅍ`
2. Result in TextInput will be `텍스트인ㅍ`
3. If the word before max length contains no prop constant such as `텍스트이풋`, result will be `텍스트이푸`.
   - prop constant considered to be something weird
4. `텍스트이푸` is fine.
#### Expected Results

Every character with consonant to be considered normally.
### Additional Information
- React Native version: 0.34.0
- Platform(s) (iOS, Android, or both?): iOS
- Operating System (macOS, Linux, or Windows?): macOS

**Comment by lacker** [comment]
This definitely seems like a problem. Are you interested in sending a pull request to fix it?

**Comment by christopherdro** [comment]
@facebook-github-bot no-reply
