### ISSUE TITLE
NavigationExperimental Android header title horzontal placement

### ISSUE THREAD

**Issue by larryranches** [facebook/react-native#10328]
### Issue Description

https://material.google.com/layout/structure.html#structure-app-bar

The Android default ActionBar behavior is to have left padding of 72 based on the link above. 

Is there a way in navigationalExperimental to either horizontally center the header title or total left align (get rid of left padding for certain routes)?

or can navigationExperimental have consistent styles from IOS to Android?
https://github.com/facebook/react-native/pull/3028

* React Native version: 0.33
* Platform(s) (iOS, Android, or both?): Android
* Operating System (macOS, Linux, or Windows?): OSX

**Comment by ericvicenti** [comment]
What do you think is the most sane default that would fit in with native Android apps?

A pull request would be appreciated for this!

**Comment by larryranches** [comment]
@ericvicenti Thank you for your reply!

The way its defaulted now (left align, with left padding of 72dp) is Native Android standard so it's definitely the most sane default.

It'd be nice to be able to customize the horizontal alignment of the Android Header title in any direction when needed or on demand. A use case would be, I'd like to center align the Android navigation header to create a consistent design between Android and ios.

**Comment by ericvicenti** [comment]
Would the height and other styles of the header match iOS, or just the text alignment? In either case, you may want to fork the header component and customize it for your needs.

If you want to add a title alignment prop that makes sense for both platforms, we can consider implementing it in NavigationHeader, but it may be tricky because of all the animation going on.

**Comment by larryranches** [comment]
`<NavigationHeader.Title textStyle={styles.navHeaderTitle}>`

`  navHeaderTitle: {
    color: '#ffffff'
    fontFamily: Font.mainBold,
    fontSize: 20
  },`

@ericvicenti The header text alignment seems to be the only thing needed. I'm passing in a style to the Navigation.Title component from the example above which handles text size, family, etc. If I apply textAlign: 'center' to this, it doesn't work, at least for Android.

A titleAlignment prop in the NavigationHeader component would be ideal in this situation which would control the horizontal alignment for both platform if provided. If not, defaults to it's native standard implementation.

**Comment by ericvicenti** [comment]
Are there cases where one page needs center text and other pages need left-alignment? That would make things more difficult

**Comment by larryranches** [comment]
No not in our case. We'd like to keep all of the navigation title consistent throughout the app so it's ideal to just have all of our views header titles to be centered on Android.

**Comment by ericvicenti** [comment]
Ok. Are there any changes needed to the header or the title?

**Comment by larryranches** [comment]
Just the horizontal alignment for the header title text as stated.

**Comment by ericvicenti** [comment]
Oh I misunderstood and thought the style prop was working for you.

Feel free to implement the `titleAlignment` prop for `NavigationHeader` as you need, we will happily accept the change!

**Comment by larryranches** [comment]
To be honest, I'm not to sure how to implement this to override the default android header text alignment. Could you provide some direction on how go about implementing this props?

**Comment by ericvicenti** [comment]
You can play around with the View and Text styles in NavigationHeader and NavigationHeaderTitle

**Comment by larryranches** [comment]
Passing in that style property textAlign: 'center' to NavigationHeader.Title is working now  in Android. Don't think it's necessary to create a NavigationHeader prop to do this anymore after looking deeper into the header code. @ericvicenti Thank for the guidance!
