### ISSUE TITLE
HMR not working all of a sudden "index.android.bundle?platform=android&dev=true&hot=false&minify=false"

### ISSUE THREAD

**Issue by justinireland** [facebook/react-native#10332]
Today I had to re`npm install` my node_modules folder again for a project I've been working on and now all of a sudden HMR isnt working. When I run react-native start I get the following:

> [10/10/2016, 7:53:44 PM] <START> Building Dependency Graph
[10/10/2016, 7:53:44 PM] <START> Crawling File System
[Hot Module Replacement] Server listening on /hot

> React  packager ready.

> [10/10/2016, 7:54:25 PM] <START> Requesting bundle: {"url":"/index.android.bundle?platform=android&dev=true&**hot=false**&minify=false"}

I don't know why hot=false since I never changed anything. I'm also unsure how to enable it if that is the case.

**Comment by sidnny** [comment]
In case anyone else runs into this issue, you can enter `adb shell input keyevent 82` at the command line and a menu will open up that will have, amongst other options, "Enable hot reloading".
