### ISSUE TITLE
Why are there so many Babel transformations, the runtimes seem to support the syntax?

### ISSUE THREAD

**Issue by WhyEvenTry** [facebook/react-native#10334]
Enabled transformations:
https://github.com/facebook/react-native/blob/master/babel-preset/configs/main.js#L16

From what I can see the runtimes support most of those already, so why are there transformations?

**Comment by ide** [comment]
The runtimes go back to iOS 8 which doesn't support all this syntax (or sometimes when it does, it's buggy). If you see some that aren't needed anymore on iOS 8 and JSC@r174650 (Android), send a PR with them removed.

**Comment by WhyEvenTry** [comment]
Okay. Just one more quick question:

Somebody said

> The JSC version that react native runs on Android is quite old, so I strongly suspect that you will need the babel transpiling for ES2015 code to work on Android.

Is this true, or is it only iOS 8?

**Comment by ide** [comment]
It's JSC@r174650 which is from the iOS 8 era  -- look at the actual WebKit code at that revision for the specifics.
