### ISSUE TITLE
Detecting WebView Keyboard Events & Focus

### ISSUE THREAD

**Issue by moaxaca** [facebook/react-native#10333]
I've been playing around with the Keyboard module but I haven't had any luck working with it against a webview. Is there any way to detect keyboard show & close when spawned from a webview?

**Comment by fernsheldon** [comment]
[RCTKeyboardObserver.m](https://github.com/facebook/react-native/blob/master/React/Modules/RCTKeyboardObserver.m), which is built-in.



```
'use strict'
import { Dimensions } from 'react-native'
import React, {View, DeviceEventEmitter} from 'react-native'
class SomeScene extends React.Component {
  constructor (props) {
    super(props)
    this.state = {
      visibleHeight: Dimensions.get('window').height
    }
  }

  componentWillMount () {
    DeviceEventEmitter.addListener('keyboardWillShow', this.keyboardWillShow.bind(this))
    DeviceEventEmitter.addListener('keyboardWillHide', this.keyboardWillHide.bind(this))
  }

  keyboardWillShow (e) {
    let newSize = Dimensions.get('window').height - e.endCoordinates.height
    this.setState({visibleHeight: newSize})
  }

  keyboardWillHide (e) {
    this.setState({visibleHeight: Dimensions.get('window').height})
  }

  render () {
    return (
      <View style={{height: this.state.visibleHeight}}>
       ...
      </View>
    )
  }
}
```

Also [StackOverflow](http://stackoverflow.com/questions/tagged/react-native) is a great place to ask such questions. 

Creating issues like this will make it harder for the devs to sort real issues with RN vs questions/doubts 😃

**Comment by moaxaca** [comment]
Thank you I will migrate the question :)
