### ISSUE TITLE
sendDeviceEvent not working in AppDelegate (or more specific, not working if called in 3rd API callback)

### ISSUE THREAD

**Issue by watsonwu9** [facebook/react-native#1033]
hi, guys. I am doing a project in which basically I need get an 3rd party API callback userinfo in appDelegate  before I send it to my js file.   I can make up a fake userInfo in my  
WeixinLoginManager.m and send it to my js successfully. But when i want to do it in the AppDelegate.m, it is not working. 

BTW I am also wondering it is a good practice to do it   in the AppDelegate.m? since the 3rd party library(wechat) asked me to receive the callback in AppDelegate.  I do not whether I can make it possible to receive this in other m file.

![2015-04-27 07 05 04](https://cloud.githubusercontent.com/assets/912960/7339744/6a305662-ecac-11e4-978d-327317069837.png)
![2015-04-27 07 05 52](https://cloud.githubusercontent.com/assets/912960/7339745/6a3a1468-ecac-11e4-9713-7c0081b92d05.png)
![2015-04-27 07 03 55](https://cloud.githubusercontent.com/assets/912960/7339746/6a4874a4-ecac-11e4-9a72-a296837ffeda.png)

please help.

**Comment by watsonwu9** [comment]
i also post the question at http://stackoverflow.com/questions/29884741/react-native-senddeviceevent-not-working-in-appdelegate
thx!

**Comment by jaygarcia** [comment]
Are you trying to emit the event before your JavaScript code has a chance to actually bootstrap?

**Comment by watsonwu9** [comment]
@jaygarcia ,can you be more specific? i am a newbie in react native.

**Comment by jaygarcia** [comment]
@watsonwu9,

If you look @ AppDelegate.m, you'll see where React Native's root view is initialized.

The question is: Are you firing the event before the root view is initialized?

**Comment by nicklockwood** [comment]
@watsonwu9 can you also post the code inside your AppDelegate?

If I understand correctly, when your JS application loads, you call sendAuthReqToWX to initialize the 3rd party API, and some time after that, it calls a delegate method on your App Delegate. In that App Delegate method, you then call sendUserInfoToJS on your module and send the user data back to the bridge - is that correct?

**Comment by watsonwu9** [comment]
@jaygarcia 
this is my appDelegate.m file. I have changed (BOOL)application:(UIApplication *)application handleOpenURL: and OpenURL methods and move all data processing methods into the weixinLogin
Manager.m file. 
![2015-04-27 21 59 32](https://cloud.githubusercontent.com/assets/912960/7349057/f1ce83a6-ed28-11e4-9873-2776f1ae9652.png)
![2015-04-27 21 59 17](https://cloud.githubusercontent.com/assets/912960/7349058/f1f32e7c-ed28-11e4-9c8b-2999f6c37cee.png)
![2015-04-27 21 59 25](https://cloud.githubusercontent.com/assets/912960/7349059/f27fc10c-ed28-11e4-99e9-cf800b4673d3.png)
![2015-04-27 21 59 10](https://cloud.githubusercontent.com/assets/912960/7349060/f29380a2-ed28-11e4-8c7e-5ee6274fdf4c.png)
![2015-04-27 21 59 37](https://cloud.githubusercontent.com/assets/912960/7349062/f415b9ae-ed28-11e4-9996-16617f38b47e.png)

**Comment by watsonwu9** [comment]
@nicklockwood hi, man. to make flow clear, I have moved all data processing methods to the weixinLoginManager.m file. And what strikes me is that 

if i call -(void)SendDataToJS from RCT_EXPORT_METHOD(sendAuthReqToWX) method [_bridge.eventDispatcher sendDeviceEventWithName  executes and the data did pass to 
js; all are doing great.
if i call -(void)SendDataToJS from -(void) onResp:(BaseResp*)resp ( a 3rd party API callback delegate method provided by wechat). the [_bridge.eventDispatcher sendDeviceEventWithName: method is not responding and nothing passes to the js.

your understanding is correct. Please help!


![2015-04-27 22 05 46](https://cloud.githubusercontent.com/assets/912960/7349146/a3cba228-ed29-11e4-9f40-15ead8d91ac3.png)
![2015-04-27 22 05 18](https://cloud.githubusercontent.com/assets/912960/7349147/a4288a06-ed29-11e4-9ca1-dfea05d54fe3.png)
![2015-04-27 22 05 27](https://cloud.githubusercontent.com/assets/912960/7349154/a6185d50-ed29-11e4-8ffe-bd7e81ffb088.png)
![2015-04-27 22 06 00](https://cloud.githubusercontent.com/assets/912960/7349153/a599abe0-ed29-11e4-9f70-552c8be0d909.png)
![2015-04-27 22 05 54](https://cloud.githubusercontent.com/assets/912960/7349155/a6660190-ed29-11e4-87df-14afa6e7ac3f.png)

**Comment by watsonwu9** [comment]
@nicklockwood hi, man. to make flow clear, I have moved all data processing methods to the weixinLoginManager.m file. And what strikes me is that

if i call -(void)SendDataToJS from RCT_EXPORT_METHOD(sendAuthReqToWX) method [_bridge.eventDispatcher sendDeviceEventWithName executes and the data did pass to 
js; all are doing great.
if i call -(void)SendDataToJS from -(void) onResp:(BaseResp*)resp ( a 3rd party API callback delegate method provided by wechat). the [_bridge.eventDispatcher sendDeviceEventWithName: method is not responding and nothing passes to the js.

![bug_meitu_0](https://cloud.githubusercontent.com/assets/912960/7350146/35136634-ed30-11e4-9975-16a80d1c6199.png)

**Comment by nicklockwood** [comment]
WeixinLoginManager should ideally not be a singleton (i.e. should not be accessed via a sharedInstance method). The RCTBridge creates its own instance of WeixinLoginManager, so if you try to access `[WeixinLoginManager sharedInstance]`, it won't be the same instance that the bridge is using.

Instead of calling `[WeixinLoginManager sharedInstance]`, use  `bridge.modules[@"WeixinLoginManager"]`.

To do this, you'll need to have a reference to the bridge somewhere in your app delegate.

**Comment by watsonwu9** [comment]
@nicklockwood thx! 
As you said,how can i  have a reference to the bridge somewhere in your app delegate? 
Should I set up the reference in the WeixinLoginManager.m file?

**Comment by nicklockwood** [comment]
Where do you set up your RCTRootView?

**Comment by watsonwu9** [comment]
@nicklockwood Should I set it up? it is a library file provided by react-native... what should i do with it?
sorry I am very newbie into react native.
![2015-04-27 23 52 42](https://cloud.githubusercontent.com/assets/912960/7351567/87116d5c-ed38-11e4-8f27-e13a4ce6f9d3.png)

**Comment by nicklockwood** [comment]
@watsonwu9 did you look at the example apps? Every app normally has an RCTRootView, which is typically set up in the AppDelegate. That's where your React Native app will appear on screen.

The RCTRootView has a bridge property, so if you set up your RCTRootView in the AppDelegate, you can store the bridge in a property in your AppDelegate and then use that to access you module.

**Comment by watsonwu9** [comment]
@nicklockwood ，it works! Many thanks!
