### ISSUE TITLE
react-native link error when using ${applicationId} on AndroidManifest.xml

### ISSUE THREAD

**Issue by guilhermebruzzi** [facebook/react-native#10331]
### Issue Description

Error on react-native link when use special variable ${applicationId} on AndroidManifest.xml, example:

``` xml
<manifest
    xmlns:tools="http://schemas.android.com/tools"
    package="${applicationId}">
        <!-- other info -->
</manifest>

```

On console, the error appear as:

rnpm-install ERR! It seems something went wrong while linking. Error: ENOENT: no such file or directory, open '<project_path>/android/app/src/main/java/${applicationId}/MainApplication.java'
Please file an issue here: https://github.com/facebook/react-native/issues
### Steps to Reproduce / Code Snippets

Include the ${applicationId} variable on your AndroidManifest.xml as explained above.
#### Expected Results

It should be able to replace ${applicationId} with it's value on app/build.gradle.

Another issue is that react-native link is finding the first AndroidManifest.xml of your source tree, so it is actually using our androidTest/AndroidManifest.xml instead of main/AndroidManifest.xml.

A workaround to solve the issue is setting your correct MainApplication.java path on your package.json:

``` json
"name": "YourAppName",
"version": "YourAppVersion",
...
"rnpm": {
    "android": {
      "mainFilePath": "src/main/java/<PathToMainApplication>/MainApplication.java"
    }
  },
...
```
### Additional Information
- React Native version: 0.34
- Platform(s) (iOS, Android, or both?): Android
- Operating System (macOS, Linux, or Windows?): macOS

**Comment by reneweb** [comment]
AFAIK it is generally not possible to use a placeholder for the `package` attribute in the android manifest (i.e. it's not support by the android build process). If you create a standard Android app and do the same, it will fail similarly. 
Have you tried using placeholders for attributes other than `package`, to see if it works for them?

**Comment by christopherdro** [comment]
@facebook-github-bot no-reply

**Comment by khacanh** [comment]
@guilhermebruzzi As it states here the `package` in the manifest must match the project base package name, so it's not possible to use a placeholder https://developer.android.com/studio/build/application-id.html 

I'm curious what do you want to achieve with that though

**Comment by guilhermebruzzi** [comment]
Hi guys @khacanh @reneweb, we used to specify on app/build.gradle a config like:

```
android {
    compileSdkVersion 23
    buildToolsVersion "23.0.3"
    ...

    defaultConfig {
        applicationId "com.my.app.name"
        ...
}
```

Then you can use ${applicationId} on any part of your AndroidManifest.xml file and it used to work for us, but now we changed to use the original package name explicit (which according to @khacanh  link it isn't required because it defaults to your applicationId value anyway).

So I think I can close this issue for now.
