### ISSUE TITLE
 ./gradlew assembleRelease error 

### ISSUE THREAD

**Issue by luisfpinto** [facebook/react-native#10342]
Hello! 

I'm running 
```
./gradelew assembleRelease error
```
to build my signed apk but on the compilation process I'm getting an error on app:processReleaseResources

>Executing task ':app:processReleaseResources' (up-to-date check took 0.019 secs) due to:
  No history is available.
All input files are considered out-of-date for incremental task ':app:processReleaseResources'.

Any help with this? Thank you!

**Comment by RobGu** [comment]
I try to  remove `node_modules/.bin/detect-newlin`. It works for me

**Comment by luisfpinto** [comment]
I found the problem so know I can find the solution. I advise everyone who do this step run the command like:
`
./gradelew assembleRelease --info `

So you will see what is the error and you will be able to solve it 😉
