### ISSUE TITLE
Switch to Yarn in docs and CI

### ISSUE THREAD

**Issue by ide** [facebook/react-native#10345]
cc @bestander 

Yarn is much faster than npm and more consistent by default so I lean towards recommending it in the docs and using it everywhere. In addition FB uses Yarn so it's better if more people's RN setups are aligned with FB's setup (and we are planning to use it more on Exponent).

Couple of things we could do:
- s/yarn/npm/ in the docs. We should still mention npm and that you can use it, but most users are going to have a better time with yarn. The time to seeing a new project on their phone should go down dramatically.
- Make `react-native init` use yarn instead of npm if yarn is in PATH.
  - Done by @mkonicek in https://github.com/facebook/react-native/pull/10626
- Make the CI builds use yarn. I'm split on whether we should include node_modules tarballs in this repo. I lean towards no for now, we can do that later.
- Ship yarn.lock. Someone from FB will need to do this and make sure the shipit filter doesn't blacklist it.

<img width="1156" alt="screenshot 2016-10-11 17 44 31" src="https://cloud.githubusercontent.com/assets/379606/19293599/a49a1a4a-8fda-11e6-8d45-3e937f0e9f80.png">

**Comment by bestander** [comment]
Currently we have yarn.lock internally but it refers offline modules instead of repo paths, so we can't have the same lock between OSS and fbsource until yarn fixes that.

**Comment by bestander** [comment]
> Make react-native init use yarn instead of npm if yarn is in PATH.

💯 

> Make the CI builds use yarn. I'm split on whether we should include node_modules tarballs in this repo. I lean towards no for now, we can do that later.

Yeah, I would not check them in for OSS project, too much trouble.

**Comment by ide** [comment]
@cpojer I noticed that Jest's repo has a yarn.lock file. Does the yarn.lock file on GitHub conflict with the yarn.lock file inside of FB's internal repo? (For RN, the internal and external yarn.lock files would differ, I'm wondering if you solved the same problem for Jest already.)

**Comment by cpojer** [comment]
GitHub is the source of truth for Jest nowadays.





On Fri, Nov 4, 2016 at 9:47 PM +0000, "James Ide" <notifications@github.com<mailto:notifications@github.com>> wrote:


@cpojer<https://github.com/cpojer> I noticed that Jest's repo has a yarn.lock file. Does the yarn.lock file on GitHub conflict with the yarn.lock file inside of FB's internal repo? (For RN, the internal and external yarn.lock files would differ, I'm wondering if you solved the same problem for Jest already.)

-

**Comment by lacker** [comment]
It seems useful to use yarn instead of npm if they have already installed yarn. But for someone who hasn't installed yarn yet, I wouldn't recommend that they install it as a prerequisite to installing React Native. There are just so many steps to getting started already, and the complexity and failure rate of that process is a much larger complaint than the time spent waiting for an `npm install`.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/switch-to-yarn-in-docs-and-ci
