### ISSUE TITLE
[iOS 10] crash when reload on the device:JavaScriptCore`WTF::CrashOnOverflow::crash:

### ISSUE THREAD

**Issue by flingInTheSky** [facebook/react-native#10346]
Steps:
1、react-native init demo
2、run the project on a iOS 10 device
3、refresh the react-native view for several times, then it crash.

Informations:
Xcode 8.0，iPhone5s iOS 10.0.2 
![d372d3ae-e246-4489-97b3-512d4d87ed00](https://cloud.githubusercontent.com/assets/22782965/19295498/780697d2-9067-11e6-80fb-cdc91f59b683.png)

I works OK in the Simulator.I have tried the react-native version witch  is higher than 0.31.0.

**Comment by lacker** [comment]
I can't reproduce this. It seems like something is very screwy on your device. I would try reinstalling everything, especially if this problem happens with a plain old "hello world" app.

**Comment by hlung** [comment]
I think if you have Safari web inspector opened for the JS app you are running (tvOS app), and then do a App.reload(), it will crash with this error.
