### ISSUE TITLE
Call argument isn't a string

### ISSUE THREAD

**Issue by ds-aco** [facebook/react-native#10348]
我想用中文更能表达清楚我的错误
直到昨天我用rn 0.31.0还能很好的运行在我的手机上(电脑上的模拟器由于android版本太低不支持TouchableNativeFeedback,会报backgroundAndroid ... :RCTView 这个错误,但是由于手机可以调试,我就没有管这个错误)
今天我想安装一个插件依赖 rn 0.33+ 所以就直接install了 0.35.0, 它给我报了如标题的错误,我没有运用chrome的debug ,不好追踪错误在哪里,
后来回滚到 rn 0.33.0  它给我报的错误是 (transform ... RCTView),看了一遍issue也许是没看懂,也可能没有正确的方法,看到有几个人升级到 rn 0.34.0这个错误会消失,但是对于我不管用,错误依旧在,不管 rn 0.35.0有没有消除前面的问题,我也想先把如标题的错误先解决了,哪位能告诉我或给我点提示,

**Comment by ds-aco** [comment]
![唯一的一张错误截图...]()

**Comment by ds-aco** [comment]
![唯一的一张错误截图](https://cloud.githubusercontent.com/assets/12523637/19300959/9a07358a-908f-11e6-9687-22c7713fbf3e.png)

**Comment by leeight** [comment]
In order to reproduce this problem, i think it's better post your code here.

**Comment by ds-aco** [comment]
i really want to post my code , but i don't know where is wrong in my code ,(我真不知道我的代码哪个地方出问题了,知道我就去找问题了....)
it's just run  react-native start and react-native run-android ,after this  it's report this error ,
don't have any body have this problem?  it's just only my mistake?...(我以为升级到0.35都会出这个问题呢难道只有我自己出问题了吗?)

**Comment by nihgwu** [comment]
paste the error stack in Logcat, try `adb logcat`, it would be more clear

**Comment by ochanje210** [comment]
I do have same problem here after updating react-native to 0.35.0
have no idea how to solve this..

**Comment by tioback** [comment]
Try killing the packager and running the project again.

I believe this only happens if you have the packager running for a project with different RN version.

This happened to me in the following scenario:

1. Run a project in RN 0.35.0
2. Run a project in RN 0.34.1

When I ran the second project, the packager from the first project was still running. This appears to cause the problem.

Killing the packager allowed me to run the second project (which restarted the packager). If I try running the first project with the packager started by the second project, I get the same crash as before.

**Comment by ds-aco** [comment]
@tioback  how can i kill packager, i can't find about this.......

**Comment by tioback** [comment]
Usually there's a terminal window with contents like this:

![screen shot 2016-10-13 at 01 21 16](https://cloud.githubusercontent.com/assets/13951017/19336620/616faf6e-90e3-11e6-976b-aa30853685fd.png)

You can simply close it.

If you're running Atom/Nuclide, go to `Nuclide > React Native > Stop Packager`.

You can also use the hints that refer to liberating the port on [Troubleshooting](https://facebook.github.io/react-native/docs/troubleshooting.html) to kill the Packager process.

Also, you might wanna look at [react-native-kill-packager](https://github.com/livioso/react-native-kill-packager), but beware, I haven't tested it.

**Comment by ds-aco** [comment]
i'm in windows and use sublime, after react-native start  , i try to find port 8082's PID and kill this PID,then
restart packager,  it's also report error, i think it's not work for me, so sad....    i think  some else can fixed by your method,  thank you very mush

**Comment by ds-aco** [comment]
@tioback 
i had rollback to rn 0.31.0 , it's work good,
if there is two version running cause this problem,  i can't success when i use rn 0.31.0 ,
so  i think my problem is not two version running for a project 
it's must have other reason

**Comment by suckbi** [comment]
我從0.34升級0.35 ，也遇到了同樣的問題，不過已經成功解決
我是用下列步驟解決
1.先將模擬器的APP刪除
2.打開cmd，再跑一次react-native run-android
重新安裝app後問題便解決了

**Comment by ds-aco** [comment]
@suckbi   可以的 ,我是从手机开发的    把所有的东西连带电脑里的app都删了 重新安装了一下
可以运行了 好吧,这个问题竟然是这么解决的...    谢谢你~

**Comment by tioback** [comment]
@suckbi and @ds-aco, can you please translate it, so other people with the same problem might use your solution?

**Comment by ds-aco** [comment]
@tioback it's so easy...
just delete the old app from emulator(in my case,i delete the app from my phone,and reinstall the apk),
and  restart  react-native,

**Comment by MathieuMailhos** [comment]
I just woke up and I find having this issue. 
Deleting the app doesn't work. Neither is `npm install`.

**Comment by tioback** [comment]
@MathieuMailhos, did you try killing the packager?
