### ISSUE TITLE
Android APK/Application size too large even for "Hello World" text using Angular2 + React Native

### ISSUE THREAD

**Issue by sweety-wo** [facebook/react-native#10350]
When i create APK with "Hello World" text using Angular2 + React Native, generated APK is of 4.00MB+ when using "splits enable true" and when i try installing that APK in some android device...application installed is of 24.00MB+.

So i am not sure what is taking this much space when i am just printing hello world text using this project. My main concern here is of installed application size..that really seems large to me.

Is it normal to create application with 24.00MB+ when APK size is of 4.00MB+?

Can you please let me know how can i reduce this APK/Application sizes?

Thanks.

**Comment by satya164** [comment]
You can enable proguard (check your `build.gradle` file) to reduce the app size by 1 MB further.

React Native on Android bundles JSC runtime which add to the file size. Also there's react and react-native JavaScript code and Java APIs bundled in the app.

**Comment by satya164** [comment]
@facebook-github-bot answered

**Comment by sweety-wo** [comment]
```
splits {
        abi {
            reset()
            enable true
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
		release {
			minifyEnabled true
            shrinkResources true
			proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
		}
    }
```

using this settings already..but why 4.00MB APK is taking 24.00MB size after installation?

**Comment by satya164** [comment]
@sweety-wo All apps take more size when installed. For example Facebook takes 362 MB on my phone.

**Comment by sweety-wo** [comment]
@satya164 yes i am getting your point...just wanted to know if i am on right track or not?? 4.00MB converted to 24.00MB was my main concern.. Thank you for your quick response.

**Comment by christopherdro** [comment]
@facebook-github-bot label Android
