### ISSUE TITLE
Disabled prop for Button component

### ISSUE THREAD

**Issue by ericvicenti** [facebook/react-native#10354]
A built-in Button component was introduced the other day:

https://github.com/facebook/react-native/commit/2ae73ffa002221fde8011b012ea5e57e22979232#commitcomment-19393782

It could use a `disabled` boolean prop to handle states where the button is visible but cannot be pressed. This is expected to look standard and native on iOS and Android.

Please test the documentation generation with the website to make sure the prop is correctly documented: https://github.com/facebook/react-native/tree/master/website

**Comment by christopherdro** [comment]
Fixed via https://github.com/facebook/react-native/commit/c32ab7e60820eeca4f13722e652251b3e67d795e
