### ISSUE TITLE
RCTHTTPRequestHandler.m missing

### ISSUE THREAD

**Issue by zhuzhuojiang** [facebook/react-native#10355]
I got below error 
error: no such file or directory: 'XXXXXX/react-native-master/Libraries/Network/RCTHTTPRequestHandler.m'
when I tried to run Examples

Look like RCTHTTPRequestHandler.m changed to RCTHTTPRequestHandler.mm, is it right?

**Comment by javache** [comment]
Fixed in https://github.com/facebook/react-native/commit/8802db3cc0c7643048facd480dd629e9c027d3c5
