### ISSUE TITLE
Animated - AnimatedValue.stopAnimation unresponsive touch

### ISSUE THREAD

**Issue by hamicornfury** [facebook/react-native#10359]
### Issue Description

When using [Animated](https://facebook.github.io/react-native/docs/animated.html) and [AnimatedValue](https://facebook.github.io/react-native/docs/animated.html#animatedvalue) to create tweens/etc. there appears to be a bug related to stopping the animation early and unmounting the component on which Animated operated. 

In the case where AnimatedValue.stopAnimation is used to stop the animation and then the component for which Animated was driving the animation is unmounted RN will not respond to the first press event. It will respond to subsequent press events. 

In the case that an animation runs to its "natural" completion and the component is removed RN responds to the first press event and all subsequent press events. 
### Steps to Reproduce / Code Snippets

This bug/issue was found in a much larger chunk of code that is hard to isolate for sharing for reproduction. I will update with a small project example as soon as I have time. 
#### Expected Results

I expect that RN will respond to press events irregardless of stopping an animation early and removing the component. 
### Additional Information

There are no exceptions or other catchable errors to report. 
- React Native version: react-native-cli: 1.0.0, react-native: 0.31.0
- Platform: Android
- Operating System: mac os x 0.11.6

**Comment by lacker** [comment]
I think we need a smaller project example to dig into this. I'm guessing you have moved on to other things so I am just going to close this issue but if you do have a reproduction then please feel free to reopen!
