### ISSUE TITLE
TextInput maxlength error

### ISSUE THREAD

**Issue by rodolfobarretoweb** [facebook/react-native#10353]
Hello, I'm using a text input element with maxlength of 500 characters and when i type close of the limit, the application get a fatal error.

Sorry about my english.

**Comment by reneweb** [comment]
I've tried it in Android and IOS and in both cases had no issues.
Can you provider some more context around the issue (which platform (IOS/Android), platform version, react-native version, the exact error message that you see, ...) and ideally an example that reproduces the issue.

**Comment by rodolfobarretoweb** [comment]
The version of react native is 34 and the platform is Android. Tomorow i Will check this issue and come back with more informations.
