### ISSUE TITLE
API to detect Swipe actions / common gestures?

### ISSUE THREAD

**Issue by iq-dot** [facebook/react-native#1035]
Hi guys,

I just wanted to check I missed anything and if we do have any APIs to detect swipe actions and / or common touch gestures? e.g. pinch, swipe etc? Sort of like a touchable highlight wrapper?

If so could someone point it towards me, if not towards any libraries, otherwise I guess I'll need to detect it myself based on touch events and responder system.

**Comment by sitestudio** [comment]
Here are a couple:
https://github.com/jlevine22/react-native-swipeable-element
and
https://github.com/leecade/react-native-swiper

**Comment by iq-dot** [comment]
brilliant I will check that out, the react-native-swipeable element seems a new one.

**Comment by hoangvuanhdevelopervn** [comment]
Can i open this problem, i can't find any libraries support detect swipe gestures in react native, it's so lazy.
