### ISSUE TITLE
"Cannot find entry file index.ios.js in any of the roots"

### ISSUE THREAD

**Issue by alwynsays** [facebook/react-native#10360]
Having trouble loading js bundle through packager while debugging on device. I can see the request come through from the device but packager sticks at "find dependencies". I can successfully retrieve the bundle in chrome using the same IP.

___

My jsCodeLocation:
```
jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"192.168.1.215:8081/index.ios" fallbackResource:nil];
```

I've added this to my Info.plist to no avail:
``` objective-c
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
</dict>
```

First request from chrome successful, second request from device unsuccessful

<img width="625" alt="screen shot 2016-10-12 at 11 41 46 pm" src="https://cloud.githubusercontent.com/assets/8174087/19338995/7d83b76c-90d5-11e6-9ce6-9ac89142d46c.png">

Error on device

![img_6717](https://cloud.githubusercontent.com/assets/8174087/19339010/99ef9934-90d5-11e6-993c-67d985fb0323.PNG)

### Additional Information

* React Native version: 0.32
* Platform(s) (iOS, Android, or both?): iOS 10
* Operating System (macOS, Linux, or Windows?): macOS Sierra

**Comment by alwynsays** [comment]
No longer needed IP prefix. Fixed by changing jsCodeLocation back to:
```
jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];
```

**Comment by emadd** [comment]
Getting this in 0.45.0, Mac OSX Sierra

**Comment by yinchonging** [comment]
Getting this in 0.45.0, Mac OSX Sierra

**Comment by mmckinley8** [comment]
Can someone reopen this? I didn't start seeing this until upgrading to 0.45.0 today.

**Comment by flyandi** [comment]
Still happening to me, too. Cleaned out everything. No go.

**Comment by parkerdan** [comment]
The path to the server is not found.  Just re-start the server manually by `cd { your project }` `npm start`
