### ISSUE TITLE
'Shake for dev menu' doesn't work after pod install 'React'

### ISSUE THREAD

**Issue by mazicky** [facebook/react-native#10366]
### Issue Description

I cannot show up dev menu, after pod install 'React'
### Steps to Reproduce / Code Snippets
1. react-native init [Project]
2. `cd ios/`
3. `pod init` and fill it with pod React

```
...
 pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTWebSocket', # needed for debugging
  ]
...
```
1. `pod install`
2. open with [Project].workspace, and bulid & run on device (iPhone)
3. Shake, but no response here
#### Expected Results

I want to show dev menu for debugging,

But I cannot open dev menu even on newly init project.

How can I open it? Anyone who is in this issue here?
### Additional Information
- React Native version: 0.35.0
- Platform(s) (iOS, Android, or both?): iOS
- Operating System (macOS, Linux, or Windows?): Mac

**Comment by seanders** [comment]
@mazicky Any luck resolving this issue?

**Comment by mazicky** [comment]
@seanders Yes. When I use 'React' with cocoapod, this issue happens.

I used cocoapod-React because of other pod-library's dependency.

So I manually import the library without cocoapod.

**Comment by Fatxx** [comment]
If I understood correctly, did you stopped using Pods, or did you manually imported React instead of doing it with Pods?

**Comment by mazicky** [comment]
@Fatxx I still use Pods. but I deleted 'React' and 'React'-dependency-libraries.
I'm using React which is automatically imported when I initialize the project with react-native.

**Comment by Fatxx** [comment]
@mazicky thanks

**Comment by roocell** [comment]
Thank you so much - this has been driving me nuts for days!
Just commented out the React pod in my podfile, reran "pod install" and reran my app.
Shake the phone and bam! menu.

**Comment by mazicky** [comment]
@roocell I glad to help you with my solution.

But it will be an issue when we use Pod-React dependency library.

I hope this will be fixed.

**Comment by jnrepo** [comment]
@mazicky sorry, but I'm confused as to what to do after removing `React` from my podfile.

**Comment by jeanregisser** [comment]
For those who upgraded to RN 0.43-rc and can't use the Dev Menu anymore when RN is installed with CocoaPods, you now have to explicitly add the `DevSupport` subspec in your `Podfile`.

Change was introduced by https://github.com/facebook/react-native/pull/12602

**Comment by sarahscott** [comment]
This and #13127 are duplicates.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/shake-for-dev-menu-doesnt-work-after-pod-install-react
