### ISSUE TITLE
borderXColor and borderRadius don't work at the same time 

### ISSUE THREAD

**Issue by fkilaiwi** [facebook/react-native#1036]
I am trying to draw a circle by setting borderRadius to half the dimension. As expected, its working fine !

Now, I am trying to give each border side a different color. When I do that, it doesn't work. Its like the BorderRadius value gets disabled and things go back to being a square.

**Comment by nicklockwood** [comment]
Yeah, that isn't supported currently. We rely on Apple's border drawing for rounded corners, and that doesn't support different colored sides.

The CSS border spec is actually amazingly complicated, with loads of really weird edge cases.

The good news is, @a2 has now managed to implement most of it, and his upgraded version should hopefully land sometime this week.

If that's not soon enough, you're probably best off using a background image.

**Comment by brentvatne** [comment]
[This works fine now](https://rnplay.org/plays/vx9deg?autoplay=true)

Thanks @a2 :smile:
