### ISSUE TITLE
android getting started documentation improvements

### ISSUE THREAD

**Issue by faassen** [facebook/react-native#10372]
Issue #9024 has a lot of comments, including by me, and in release 0.35.0 the installation documentation for Android was improved. It's however not perfect yet, so here are a few suggestions that can hopefully be implemented with less effort:
- Step 2 has you install Android 7 with API 24. But `react-native init` hardcodes API version 23. When you do `react-native run-android` it actually fails:  
  
  ```
  * What went wrong:
  A problem occurred configuring project ':app'.
  > failed to find target with hash string 'android-23' in: /mnt/tb/faassen/Android/Sdk
  ```
  
  I had to adjust various values in `android/build/app.gradle` to 24 instead of the default 23 to make that work:
  - `compileSdkVersion 24`
  - `buildToolsVersion "24.0.3"`
  - `targetSdkVersion 24`
  - `compile "com.android.support:appcompat-v7:24.0.0"`
  
  Unless this hardcoding can be lifted somehow, instructions to this effect need to be in the documentation, otherwise people will get stuck straight away and have to look up issues like this one. Alternatively you change the instructions to install a fixed Android version.
- Step 2 has the Android SDK manager. Then at step 4 there's a small print note saying that if you click on "Show Package Details" you can install missing images such as the actual Android emulator image. This seems to be a required step and it should just be presented in step 2, otherwise people have to backtrack to the Android SDK manager. Okay, I read in step 4 that this is only needed if the Android SDK manager _fails_ to install an AVD, which it always seems to do for me. So it should at least have people check for this image data here, right? If it's missing there can't be an AVD.
- Step 3 has you set up paths, but doesn't actually set up an essential path to `platform-tools` in the SDK, otherwise the `adb` tool cannot be found and you can't run `react-native run-android`:
  
  ``export PATH=${PATH}:${ANDROID_HOME}/platform-tools`
- Step 4 Talks about a common issue where Android Studio doesn't install an AVD. I seem to hit this issue then. It hasn't installed AVDs on two separate linux boxes already. It doesn't say it failed to install an AVD. Weird. 
- Testing your Android installation should, I think, just step 5, as it has you actually create a project in the first place. A few steps are missing:
  - It immediately throws you into a screen where you need to give screen overlay permissions for the application. If you don't, it doesn't seem to work.
  - if you don't close all apps after that, I believe there is some difficulty in getting it started too, but more testing is needed.
  - It often fails the first time with a scary red screen saying it can't connect telling people to look into network settings. This falsely leads people into thinking they need to fix network settings, but actually trying it again makes it work. So a note to that effect would be helpful.
  - I thought you needed to become developer by pressing build a lot of times, but apparently that's not required. I did this before thinking it fixed an issue, but I just tested with a new Android image and it's not required.

A useful command-line way to start the emulator:

```
$ emulator -avd Nexus_5X_API_24_x86
```
### Additional Information
- React Native version: 0.35.0
- Platform(s) (iOS, Android, or both?): Android
- Operating System (macOS, Linux, or Windows?): Linux

**Comment by christopherdro** [comment]
@facebook-github-bot label Android

**Comment by nogwater** [comment]
Thanks for these notes @faassen! I'm now able to get it to run on Windows.  One note: For me, the path to the file to change the version numbers is: android\app\build.gradle (backslashes 'cause Windows).

Another small thing that could use clarification:
> * Open index.android.js in your text editor of choice and edit some lines.
> * Press the R key twice or select Reload from the Developer Menu to see your change!

Like a dumbie, I hit RR and all it did was add two R's to index.android.js.  I figured out to select the emulator and hit RR there, which worked.  Is there another way to do it?  Also, what Developer Menu?

**Comment by hramos** [comment]
@faassen thanks for the detailed write up. Check out #10710 where I attempt to cover most of the feedback raised here. The feedback I haven't yet addressed is the one regarding your issues running the test project for the first time, so we still have some work to do here.

**Comment by hramos** [comment]
Looks like #10707 would cover the rest.

**Comment by lacker** [comment]
It looks like this issue has been resolved, now that the things Hector linked to are in. So I am going to close this. Thanks for reporting these documentation issues and please feel free to open more similar issues in the future!
