### ISSUE TITLE
Cannot build 0.35.0 due to missing CSSLayout-internal header file

### ISSUE THREAD

**Issue by janmonschke** [facebook/react-native#10388]
### Issue Description

I was trying to update a project to 0.35.0 and got the following error message when trying to build the app:

`error: [my app's directory]/node_modules/react-native/React/CSSLayout/CSSLayout-internal.h: No such file or directory`

We are using CocoaPods and had similar problems before.

Building an app worked fine on a clean project (without CocoaPods).

cc @alloy

**Comment by alloy** [comment]
@janmonschke Was this a non-issue after all?

**Comment by janmonschke** [comment]
@alloy The old `clean everything, delete derived data and setup the project fresh` did the trick :(

**Comment by alloy** [comment]
Ahh, yeah, that Xcode… Glad you got it sorted, though 👍

**Comment by magrinj** [comment]
I got the same problem with `react-native@0.36`, I try a lot of time to clean the project with Xcode, but I always got the same error, you solve it just by simply cleaning your project ?

**Comment by magrinj** [comment]
Forgot my question, I just solve the problem, I forgot to do a `pod install` to update react-native for some dependencies

**Comment by nrathi** [comment]
@janmonschke can you explain your steps in more detail? I did Product > Clean, Product > Clean Build Folder, Preferences > Locations > found the derived data and "Move to trash". What am I missing?
