### ISSUE TITLE
Some elements just don't render all the time

### ISSUE THREAD

**Issue by the-simian** [facebook/react-native#10380]
### Issue Description

Simply put ever since version 0.33, in certain situations in the application, elements which used to render sometimes will no longer render for no obvious reason. Reloading the application will sometimes result in them showing, other times, they are gone.
### Steps to Reproduce / Code Snippets

Unfortunate this is simply hard to reproduce since its totally intermittent. I also cant' seem to zero in on which elements will render, when. I will say that this seems to only be on android. The problem is that it worked find on versions before 0.32, and appears to be since the flexbox-updates.
#### Expected Results

Well due to the intermittent nature, I think its clear I'd expect consistent rendering. I'm mainly posting this issue to see if anyone else is experiencing this. I know the tracker is pretty full, but I'm looking for evidence and I didn't see any prior tickets about this. If I can zero in on more steps to reproduce I will.

I will say that for a long time we though it was a side effect of the Transform Matrix Helper introduced in 0.33. We did zero in on some bugs related to that and the translate property. However this seems to also happen on elements that don't use transform, translate props on their css.

Possibly unrelated, we've also noticed flickering on markers in react-native-maps and other anomalous behavior. Whatever is up, things are behaving really differently.
### Additional Information
- React Native version: [0.33-0.35]
- Platform(s) (Android only)
- Operating System (OSX/Genymotion emulator : Google Nexus 6P 6.0.0 API23)

**Comment by ericvicenti** [comment]
I have occasionally noticed <Text/> elements on Android not appearing, but as you say it is rare and hard to reproduce. Maybe this is the same problem.

**Comment by the-simian** [comment]
just to followup it looks like the blinking markers in particular were addressed in this issue : https://github.com/airbnb/react-native-maps/issues/683

and there is a PR here:
https://github.com/airbnb/react-native-maps/pull/728

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.

**Comment by the-simian** [comment]
I'd say its fine to close this, I haven't observed this in a long time
