### ISSUE TITLE
Android: findNodeHandle returns wrong react tag

### ISSUE THREAD

**Issue by adrianomelo** [facebook/react-native#10385]
The method `findNodeHandle` is returning a wrong react tag in Android.

I am writing a native module to change the behavior of a WebView. When the code uses the react tag returned by `findNodeHandle`, it is **not** able to find the WebView. However, when it uses the `target` property from `onNavigationStateChange` event, it can find the WebView.
### Steps to Reproduce / Code Snippets

Here you can find a project to reproduce the bug: https://github.com/adrianomelo/react-native-findnodehandlebug

``` javascript
import React, { Component } from 'react';
import {
  AppRegistry,
  View,
  WebView,
  NativeModules
} from 'react-native';
import {JSContext} from NativeModules;

export default class rn extends Component {
  _onNavigationStateChange(e) {
    const reactTag = ReactNative.findNodeHandle(this.refs['webView1']);

    JSContext.findWebView(e.target)
      .then(() => {
        console.log('e.target WebView found'); // this is printed
      })
      .catch((e) => {
        console.log('e.target WebView not found');
      });

    JSContext.findWebView(reactTag)
      .then(() => {
        console.log('findNodeHandle WebView found');
      })
      .catch((e) => {
        console.log('findNodeHandle WebView not found'); // this is printed
      });
  }

  render() {
    return (
      <WebView ref='webView1'
        source={{uri: 'http://duckduckgo.com/'}}
        onNavigationStateChange={this._onNavigationStateChange.bind(this)}
      />
    );
  }
}

AppRegistry.registerComponent('rn', () => rn);
```

``` java
package com.rn.modules;

/**
 * Created by amelo on 12/10/16.
 */

import android.webkit.WebView;


import com.facebook.react.bridge.Promise;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;
import com.facebook.react.uimanager.NativeViewHierarchyManager;
import com.facebook.react.uimanager.UIBlock;
import com.facebook.react.uimanager.UIManagerModule;

import java.util.HashMap;
import java.util.Map;



public class JSContextModule extends ReactContextBaseJavaModule {
    public JSContextModule(ReactApplicationContext reactContext) {
        super(reactContext);
    }

    @Override
    public String getName() {
        return "JSContext";
    }

    @Override
    public Map<String, Object> getConstants() {
        final Map<String, Object> constants = new HashMap<>();
        return constants;
    }


    @ReactMethod
    public void findWebView(final int reactTag, final Promise promise) {
        ReactApplicationContext reactContext = this.getReactApplicationContext();
        UIManagerModule uiManager = reactContext.getNativeModule(UIManagerModule.class);

        uiManager.addUIBlock(new UIBlock() {
            @Override
            public void execute(NativeViewHierarchyManager nativeViewHierarchyManager) {
                WebView view = null;

                try {
                    view = (WebView) nativeViewHierarchyManager.resolveView(reactTag);
                } catch (Exception e) {
                    promise.reject("Error", e.getMessage());
                    return;
                }

                promise.resolve(view.getUrl());
            }
        });
    }
}
```
### Additional Information
- React Native version: 0.35
- Platform(s) (iOS, Android, or both?): Android only
- Operating System (macOS, Linux, or Windows?): Mac OS X

**Comment by vasklund** [comment]
I had the same problem a few days ago. There's an undocumented method on the `WebView` component called `getWebViewHandle` that returns the correct handle.

I noticed advanced features like these aren't documented on the website, but they're quite visible in the source code:
https://github.com/facebook/react-native/blob/master/Libraries/Components/WebView/WebView.ios.js#L473

**Comment by christopherdro** [comment]
@facebook-github-bot label Android

**Comment by lacker** [comment]
Did this ever work? The docs are pretty unclear on the correct behavior here - https://facebook.github.io/react-native/docs/nativemethodsmixin.html just says `findNodeHandle` works on "most of the default components". If the right answer is that people should use `getWebViewHandle` then the solution is probably just improving the documentation.

**Comment by adrianomelo** [comment]
@lacker, good point. Improving the documentation of `<WebView />` would be okay for me. However, I am not sure what is expected to be the correct solution for this problem. I would expect to have access to some `view` from this code:

```java
view = nativeViewHierarchyManager.resolveView(reactTag);
```

However, it throws an error.
