### ISSUE TITLE
java.lang.AbstractMethodError: abstract method "void com.facebook.react.bridge.ActivityEventListener.onActivityResult(android.app.Activity, int, int, android.content.Intent)"

### ISSUE THREAD

**Issue by MarsHou** [facebook/react-native#10381]
I'm implements callback `onActivityResult(final int requestCode, final int resultCode, final Intent data) ` throw exception 
```java
E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.marsfirstapp, PID: 17015
java.lang.AbstractMethodError: abstract method "void com.facebook.react.bridge.ActivityEventListener.onActivityResult(android.app.Activity, int, int, android.content.Intent)"
 at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:226)
 at com.facebook.react.XReactInstanceManagerImpl.onActivityResult(XReactInstanceManagerImpl.java:616)
 at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:134)
 at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:77)
 at android.app.Activity.dispatchActivityResult(Activity.java:7137)
 at android.app.ActivityThread.deliverResults(ActivityThread.java:4929)
 at android.app.ActivityThread.handleSendResult(ActivityThread.java:4976)
 at android.app.ActivityThread.access$1600(ActivityThread.java:222)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1849)
 at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loop(Looper.java:158)
 at android.app.ActivityThread.main(ActivityThread.java:7237)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```
Guys have encountered such a problem?

**Comment by MarsHou** [comment]
solved。。。

**Comment by Cocoon-break** [comment]
@MarsHou how to solve it

**Comment by MarsHou** [comment]
@Cocoon-break upgraded version to 0.34.0 or last, and add param "Activity activity" on onActivityResult,as "onActivityResult(Activity activity,final int requestCode, final int resultCode, final Intent data)",then build ,is ok.

**Comment by lennyup** [comment]
Could you please speak clearly still don't know much about

**Comment by MarsHou** [comment]
@lennyup 就是react-native 升级之后，onActivityResult的回调增加了一个“Activity activity”的参数。用android studio打开工程 手动加上，build没问题就可以了。

**Comment by ShiLeiIt** [comment]
https://github.com/MarsHou
这个问题最终的解决办法又没有？
请大神们告知

**Comment by ShiLeiIt** [comment]
@MarsHou 你那加参数Activity ，行的通吗？

**Comment by MarsHou** [comment]
@ShiLeiIt ok的 问题出现是 react-native 升级 修改了回调函数的参数，不确定的话，可以打开android studio 删除这个回调，利用android studio的提示去重写。

**Comment by ShiLeiIt** [comment]
@MarsHou 我将ReactActivity.java 文件里面的onActivityResult方法添加Activity 的话就不是重写了的方法了，你所说的添加参数是在哪个里面进行添加？

**Comment by MarsHou** [comment]
@ShiLeiIt 我出现这个错误是在自定义module的类里（https://github.com/MarsHou/MarsFirstApp/blob/master/android/app/src/main/java/com/marsfirstapp/modules/LearnModule.java），实现了ActivityEventListener ，升级到0.34.0出的问题，你不应该改ReactActivity.java 文件，如果你没有自定module，那就不是同一个问题了，有可能是你引入的第三方框架没有及更新，项目使用的rn版本不一致导致的。

**Comment by ShiLeiIt** [comment]
@MarsHou 我自定义了module 并且在module中重写` @Override
    public void onActivityResult(Activity activity, int requestCode, int resultCode, Intent data) {
        if (requestCode == IMAGE_PICKER_REQUEST) {
            if (mPickerPromise != null) {
                if (resultCode == Activity.RESULT_CANCELED) {
                    mPickerPromise.reject(E_PICKER_CANCELLED, "Image picker was cancelled");

                } else if (resultCode == Activity.RESULT_OK) {
                    if (multiple) {

                        ClipData clipData = data.getClipData();
                        WritableArray result = new WritableNativeArray();

                        // only one image selected
                        if (clipData == null) {
                            result.pushArray(getImage(data.getData(), true));
                        } else {
                            for (int i = 0; i < clipData.getItemCount(); i++) {
                                result.pushArray(getImage(clipData.getItemAt(i).getUri(), true));
                            }
                        }

                        mPickerPromise.resolve(result);
                        mPickerPromise = null;
                    } else {
                        Uri uri = data.getData();

                        if (cropping) {
                            UCrop.Options options = new UCrop.Options();
                            options.setCompressionFormat(Bitmap.CompressFormat.JPEG);
                            options.setCircleDimmedLayer(cropperCircleOverlay);
                            options.setShowCropGrid(false);
                            options.setShowCropFrame(false);
                            configureCropperColors(options);

                            UCrop.of(uri, Uri.fromFile(new File(activity.getCacheDir(), UUID.randomUUID().toString() + ".jpg")))
                                    .withMaxResultSize(width, height)
                                    .withAspectRatio(width, height)
                                    .withOptions(options)
                                    .start(activity);
                        } else {

                            mPickerPromise.resolve(getImage(uri, true));
                            mPickerPromise = null;
                        }
                    }
                }
            }
        } else if (requestCode == CAMERA_PICKER_REQUEST) {

            cameraPickerResult(activity, requestCode, resultCode, data);
        } else if (requestCode == UCrop.REQUEST_CROP) {
            if (data != null) {

                final Uri resultUri = UCrop.getOutput(data);
                if (resultUri != null) {
                    mPickerPromise.resolve(getImage(resultUri, false));
                } else {
                    mPickerPromise.reject(E_NO_IMAGE_DATA_FOUND, "Cannot find image data");
                }
            } else {

                mPickerPromise.reject(E_NO_IMAGE_DATA_FOUND, "Image cropping rejected");
            }

            mPickerPromise = null;
        }

    }`
 "react-native": "^0.44.3",
 "react-native-image-crop-picker": "^0.15.1",
    "react-native-image-picker": "^0.26.4",
我都升级了，不知为什么还是抱错，或许与你的问题不同。还是得麻烦你看下。

**Comment by ShiLeiIt** [comment]
@MarsHou 这个问题我已解决了，原因是我的项目之前是0.26版本，现在升级到0.44.3版本。是另外一个组件引用有问题，在build.gralde`dependencies {
    compile 'com.facebook.react:react-native:0.20+'
}`改成compile 'com.facebook.react:react-native:+'
然后在自定义module中重写onActivityResult()和onNewIntent() 方法，就OK了

**Comment by ShiLeiIt** [comment]
@MarsHou 谢谢你的回复！
