### ISSUE TITLE
react-native init creates an app which doesn't run: Application XXX has not been registered

### ISSUE THREAD

**Issue by nikitph** [facebook/react-native#10382]
### Issue Description

react-native init creates an app which doesn't run: Application XXX has not been registered. This is either due to a require() error during initialization or failure to call AppRegistry.registerComponent. Started in ver 0.35 i think.

### Steps to Reproduce / Code Snippets

1. react-native init Drawrn 
2. react-native run-ios

  Application XXX has not been registered. This is either due to a require() error during initialization or failure to call AppRegistry.registerComponent.

here is the index.ios.js

`import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';

export default class Drawrn extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit index.ios.js
        </Text>
        <Text style={styles.instructions}>
          Press Cmd+R to reload,{'\n'}
          Cmd+D or shake for dev menu
        </Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

AppRegistry.registerComponent('Drawrn', () => Drawrn);`

#### Expected Results

to run succesfully

### Additional Information

* React Native version:     "react-native": "0.35.0"
* Platform(s) (iOS, Android, or both?): iOS
* Operating System (macOS, Linux, or Windows?): macOS

**Comment by nikitph** [comment]
needed a comp restart

**Comment by Bjvanminnen** [comment]
In case anyone else hits this, I ran into this same problem because I still had the react packager running in the background for a different react-native app (such that I suspect my new app was being server JS for the old app). Once I closed that, I was able to launch fine.

**Comment by huyntsgs** [comment]
I have this error, bundle loaded is successfully. So i think it is not from react packager.
![screen shot 2017-08-31 at 3 51 18 pm](https://user-images.githubusercontent.com/12619870/29915077-e12da13c-8e64-11e7-8b5d-302463c5b8bf.png)
![screen shot 2017-08-31 at 3 52 38 pm](https://user-images.githubusercontent.com/12619870/29915080-e384963e-8e64-11e7-8d41-7a0b78c5b51c.png)
