### ISSUE TITLE
[Fatal] Launch error "In 'methods.forEach', 'methods.forEach' is undefined"

### ISSUE THREAD

**Issue by tomfrew** [facebook/react-native#10391]
### Issue Description

On launch, the iOS app has a fatal error of:
`TypeError: methods.forEach is not a function. (In 'methods.forEach', 'methods.forEach' is undefined)`

This only happens in the simulator. The app on a device works fine.

Screenshot of error:

![screen shot 2016-10-14 at 12 52 52](https://cloud.githubusercontent.com/assets/845195/19391822/18350f80-9226-11e6-8012-79edb4ba8547.png)

This has been driving me crazy for days now so any suggestions would be greatly appreciated!
### Additional Information
- React Native version: 0.35.0
- Platform(s) (iOS, Android, or both?): iOS
- Operating System (macOS, Linux, or Windows?): Mac

**Comment by thurber** [comment]
I'm getting the same error, also 0.35.0, iOS, and Mac.

Interestingly, if I dismiss this error, open the dev menu, and enable remote js debugging, the error no longer occurs.

**Comment by skycocker** [comment]
Same error here, but on 0.34.1, iOS + Mac, but the problem happens only on real device, never on simulator. I would love to try the remote debugging as @thurber wrote, but it displays some outdated RCTWebSocketExecutor remote IP address in the connection error, even though I have cleaned up my xcode project.

**Comment by lacker** [comment]
Does this happen on a blank app? I think we need some steps for how to reproduce this.

**Comment by hfogelberg** [comment]
Same issue here. No idea if this helps you track down the problem, but here's what I did:

I use a Mac and was working on the iOS version. I used the simulator and haven't tried it on a device. I was in the terminal the whole time and started the app with react-native run-ios and did not open XCode.

The code worked on 0.32, but when I upgraded to 0.35 the issue appeared. I downgraded to 0.34.1 to see if it worked there, which it did. On a whim I ran npm install again set the version back to 0.35 again. Strangely it worked the second time.

**Comment by messutied-pf** [comment]
I fixed this issue on my project by running `react-native upgrade`... before, I ran it but skipped important upgrade changes to my Xcode project config files.

**Comment by thurber** [comment]
@messutied-pf thanks for the recommendation. I tried this but now run into #10498 :(

**Comment by thurber** [comment]
Nevermind, @messutied-pf 's suggestion resolved my issue. BUT the `react-native upgrade` removed symlinks to some supporting files. Once I tracked those down, I can run on simulator and device again.
