### ISSUE TITLE
Android UIExplorer Requiring unknown module "invariant". win10 0.35and 0.36 both have this problem

### ISSUE THREAD

**Issue by gitgzw** [facebook/react-native#10400]
One unknown is: at Examples\UIExplorer\js\CameraRollExample.js:38

**Comment by christopherdro** [comment]
@facebook-github-bot label Android

**Comment by leeight** [comment]
Could you find `invariant` in the `node_modules` directory?

**Comment by gitgzw** [comment]
Not found.But I want to ask that this invariant is same as the invariant which locates in "fbjs/lib/invariant"?

**Comment by gitgzw** [comment]
The example Movies is no problem.I found "var invariant = require('fbjs/lib/invariant');" in SearchScreen.js , do I have to copy the fbjs/lib/invariant.js into the node_modules directory?

**Comment by leeight** [comment]
Looks like it's a typo, you can change it to `fbjs/lib/invariant`
