### ISSUE TITLE
Docs for NavigationExperimental is a joke.

### ISSUE THREAD

**Issue by timpler** [facebook/react-native#10403]
Just want to say quality of docs for this scale of project is a joke.

eg. `NavigationCardStack`, `NavigationExperimental`.

`NavigationExperimental` is recommended, but it's still `Experimental`...

and all those `That's it -- so close to the finish line I can smell it. ` or `We're done! Bask in the glory of NavigationExperimental.` or `You are now an expert navigator. Take a look at NavigationExperimental in UIExplorer to learn how to implement other types of navigation hierarchies, such as a tabbed application with multiple navigation stacks.` in https://facebook.github.io/react-native/docs/navigation.html . Seriously? What I can smell after 2 days of trying to understand it is `NavigationExperimental` docs were written on coffee-break while it's one of main react-native components required for majority of apps.

**Comment by grabbou** [comment]
If you feel like documentation can be improved for certain components, feel free to submit PRs that will make it better. Docs are written in most cases by developers (however there's a lot of non-dev work going on on them, as recently like home page rewrite) and so it may feel a bit low-level in some places. 

To better understand NavigationExperimental or other bits of React Native, what I can suggest as an additional resource is Facebook Community, StackOverflow and looking for articles / guides on the internet (there are plenty of them coming out every day).

CC: @hedgerwang
