### ISSUE TITLE
react-native app doesn't work ":CFBundleIdentifier", Does Not Exist

### ISSUE THREAD

**Issue by xwartz** [facebook/react-native#10401]
On OS X Sierra

node --version v6.7.0
npm --v 3.10.8
react-native-cli: 1.0.0
react-native: 0.35.0
xcode 8.0

```
** BUILD SUCCEEDED **

Installing build/Build/Products/Debug-iphonesimulator/token.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/token.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
```

I tried all solutions [issues#7308](https://github.com/facebook/react-native/issues/7308), but nothing works.

Interestingly, everything works if I open the .xcworkspace in XCode and run it from there. But `react-native run-ios` still gives me the error.

**Comment by xwartz** [comment]
Fixed by https://github.com/facebook/react-native/issues/7308#issuecomment-226521882

**Comment by charlle** [comment]
In you are still trying to figure this out.  
If you've received this error, then you probably do not have the correct path for your application.
```
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist
```

React Native has hardcoded it as part of their run-ios command in runIOS.js
`build/Build/Products/${configuration}-${isDevice ? 'iphoneos' : 'iphonesimulator'}/${appName}.app`

Unfortunately Xcode has different build paths depending on your configuration and on whether you are using an Xcode Project or Workspace.  I believe the default path for an Xcode Project is `build/Products`.  
I submitted this pull request [11899](https://github.com/facebook/react-native/pull/11899) to give programmers more flexibility from the CLI.

**Comment by srt32** [comment]
After launching in Xcode I followed the steps in https://github.com/facebook/react-native/issues/11265#issuecomment-265663635 and was able to get the simulator to work

**Comment by florismettey** [comment]
I found how to solve the issue: do NOT use space in your project path! 🎉  😄

**Comment by hramos** [comment]
Duplicate of #14423

**Comment by gg444108853** [comment]
delete /Users/{{your username}}/.rncache
and reinstall depend node_modules
then run ```sh  react-native run-ios  ```
