### ISSUE TITLE
Modal not work on Android when using State to hide it in try/catch section

### ISSUE THREAD

**Issue by raminious** [facebook/react-native#10417]
### Issue Description

Modal component not worked on android when changing state to hide it in try/catch section
### Steps to Reproduce / Code Snippets

``` js
makeReauest = () => {
  this.setState({ loading: true })
  Media.request(url)
  .then(response => {
    // todo
  }, e => {
    this.setState({ loading: false })
  })
}

render() {
  return(
    <View>
      <Modal
          animationType={'slide'}
          transparent={false}
          visible={this.state.loading}
          onRequestClose={() => {} }
       >
        <View></View>
      </Modal>
      <Text onPress={this.makeRequest}>Do Magic</Text>
    </View>
  )
}
```
#### Result

![image](https://cloud.githubusercontent.com/assets/334716/19421156/e7a3ffba-9406-11e6-9731-bfbe503324b2.png)
### Additional Information
- React Native version: 0.35.0
- Platform: just Android
- Android Version: 5.1.0 on Google Nexus 6 (Genymotion Simulator)
- Operating System: macOS

**Comment by raminious** [comment]
when I changed catch section from
```js
e => {
  this.setState({ loading: false })
}
```
to:

```js
setTimeout(() => {
  this.setState({ loading: false })
}, 100)
```
then it's working.

**Comment by ying-huang** [comment]
I am having a similar problem in with iOS.

**Comment by santospatrick** [comment]
Can we reopen this please? setTimeout did not work for me, i am setting state of loading for false after async call and the Modal does not hide in standalone app, and does not throw any error. I tried to use timeout and restart my phone and nothing happens
