### ISSUE TITLE
Android - elevation style property does not work without backgroundColor.

### ISSUE THREAD

**Issue by niagr** [facebook/react-native#10411]
### Issue Description

The `elevation` style property on Android does not work unless `backgroundColor` has been specified for the element.

[RNPlay example](https://rnplay.org/apps/aksEvw)

With `backgroundColor` applied to `instructions` element:

![with-background-color](https://cloud.githubusercontent.com/assets/2101385/19416960/67c77888-93bd-11e6-8a6a-bb0e832c5b1d.png)

Without `backgroundColor` applied:

![without-background-color](https://cloud.githubusercontent.com/assets/2101385/19416963/7e22fd96-93bd-11e6-80c9-a40159988f77.png)
### Steps to Reproduce / Code Snippets
- Create a View
- Add `elevation` style property - notice it has no effect
- Add `backgroundColor` stype property - notice elevation is now applied
#### Expected Results

Unless I'm missing something elevation should get applied regardless of whether a view has a background color or not.
### Additional Information
- React Native version: 0.33
- Platform(s) (iOS, Android, or both?): Android
- Operating System (macOS, Linux, or Windows?): Linux

**Comment by leeight** [comment]
Maybe this is the related issue: https://code.google.com/p/android/issues/detail?id=78248

**Comment by leeight** [comment]
Checkout this question on Stackoverflow: <http://stackoverflow.com/questions/27477371/android-elevation-not-showing-a-shadow>

**Comment by leeight** [comment]
cc @janicduplessis @satya164 

How about add a new style property such as `outlineProvider` (https://developer.android.com/reference/android/view/ViewOutlineProvider.html), just like what we did in `Libraries/Components/View/ViewStylePropTypes.js`

```js
  /**
   * (Android-only) Sets the elevation of a view, using Android's underlying
   * [elevation API](https://developer.android.com/training/material/shadows-clipping.html#Elevation).
   * This adds a drop shadow to the item and affects z-order for overlapping views.
   * Only supported on Android 5.0+, has no effect on earlier versions.
   * @platform android
   */
  elevation: ReactPropTypes.number,

  outlineProvider: 'bounds' | 'padded_bounds' | 'background'
```

```
<View style={{elevation: 10, outlineProvider: 'bounds'}}
  ...
</View>
```

**Comment by leeight** [comment]
Looks bad

```
<View style={{alignItems: 'center', marginTop: 50, elevation: 10, outlineProvider: 'bounds'}}>
  <Text>Hello World</Text>
</View>
```
![image](https://cloud.githubusercontent.com/assets/104052/19586164/3ea116d2-9785-11e6-8beb-2401ed6c8614.png)

**Comment by Kishanjvaghela** [comment]
@niagr  I have implemented CardView for react-native with elevation, that support android(All version) and iOS. Let me know is it help you or not. https://github.com/Kishanjvaghela/react-native-cardview

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/android---elevation-style-property-does-not-work-without-backgroundcolor
