### ISSUE TITLE
webview error 'Encountered an error loading page @RN 0.34.1

### ISSUE THREAD

**Issue by micsay** [facebook/react-native#10410]
```
E/ReactNativeJS(27798):   'Encountered an error loading page', { canGoForward: false,
E/ReactNativeJS(27798):   code: -2,
E/ReactNativeJS(27798):   canGoBack: false,
E/ReactNativeJS(27798):   description: 'net::ERR_NAME_NOT_RESOLVED',
E/ReactNativeJS(27798):   loading: false,
E/ReactNativeJS(27798):   title: '',
E/ReactNativeJS(27798):   url: 'https://www.baidu.com/',
E/ReactNativeJS(27798):   target: 122 }
```

following my code://<Loading> component is custom.

```
                <WebView
                    scalesPageToFit={true}
                    renderLoading={()=><Loading value="XXX"/>}
                    renderError={()=><Loading value="XXX"/>}
                    onError={()=><Loading/>}
                    source={{uri: "https://www.XXX.com"}}
                    style={{padding: 10}}
                />
```

Who can help me?

**Comment by micsay** [comment]
I meet this error when I close network.

**Comment by naivehhr** [comment]
Are you set up a proxy?

**Comment by qianbaidu** [comment]
l have de same problem 
`Encountered an error loading page Object {domain: "WebKitErrorDomain", canGoBack: true, target: 10, code: 101, loading: true…}canGoBack: truecanGoForward: falsecode: 101description: "The URL can’t be shown"domain: "WebKitErrorDomain"loading: truetarget: 10title: "百度一下"url: "https://www.baidu.com/#0.26427529194080224;0.877470845104408%3Bthis.setHeight(1387)"__proto__: Object`

**Comment by leeight** [comment]
+1

**Comment by woshi82** [comment]
l  have the same problem too  +1

**Comment by woshi82** [comment]
I meet this error even when I do not close network.,
1、sometimes the page will show this problem and quickly show my nomal atticle page.
2、 sometimes the page will show this problem all the way,and do not have other changes.

**case 1 ,  most appeared,Probably accounted for 90%**

the pic below shows the error
![image](https://cloud.githubusercontent.com/assets/11312121/20509376/4a6870a0-b0a3-11e6-8476-7902d8b6864d.png)

and my english is poor, can you understand my describ?  ,i really really want to solve this problem,
Who can help me? thank you @naivehhr

**Comment by shivanikumar444** [comment]
Same here, does any one have a proper solution for this issue.

**Comment by LeonHwa** [comment]
I  solve this issue  by implementing `onShouldStartLoadWithRequest` . the error occur when the webView try to open a wrong url.  we can intercept the request before it happen.

**Comment by markortiz** [comment]
@LeonHwa do you have a sample on how you resolved this?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/webview-error-encountered-an-error-loading-page-rn-0341

**Comment by jackson-sandland** [comment]
Yes, this is still an issue. I'm seeing this on the latest react-native.

**Comment by jackson-sandland** [comment]
Perhaps, wait for a solution to be posted before closing the issue.

**Comment by bendellarocco** [comment]
+1

**Comment by titkov5** [comment]
+1

**Comment by declan4** [comment]
+1

**Comment by singhsurbhidaffodil** [comment]
+1

**Comment by beeremy** [comment]
+1

**Comment by hramos** [comment]
Please open a new issue and make sure to follow the template.
