### ISSUE TITLE
Duplicate interface error with RCT_EXTERN_MODULE

### ISSUE THREAD

**Issue by lukescott** [facebook/react-native#10428]
### Issue Description

I'm trying to export an existing class from a framework that I have no control over. The interface is fairly basic, so I shouldn't have any problem bridging it.

When using RCT_EXTERN_MODULE I get a compile error of:

`Duplicate interface definition for class 'WePay'`

If I try to use RCT_EXPORT_MODULE instead, I get:

`Attempted to register RCTBridgeModule class WePay for the name 'WePay', but name was already registered by class WePay`
### Steps to Reproduce / Code Snippets

First try

``` objc
#import "RCTBridgeModule.h"
#import <WePay/WePay.h>

@interface RCT_EXTERN_MODULE(WePay, NSObject)
@end
```

Second try

``` objc
#import "RCTBridgeModule.h"
#import <WePay/WePay.h>

@interface WePay (External) <RCTBridgeModule>
@end

@implementation WePay (External)
RCT_EXPORT_MODULE()
@end
```

I have this in my javascript code:

``` javascript
import {NativeModules} from "react-native";
console.log("wepay", NativeModules.WePay);
```
#### Expected Results

Something other than

```
wepay undefined
```

But I can't seem to get that far with it.
### Additional Information
- React Native version: 0.35.0
- Platform(s) (iOS, Android, or both?): iOS
- Operating System (macOS, Linux, or Windows?): macOS

This person is having almost the same exact issue about a month ago, but no one was able to help him:

http://stackoverflow.com/questions/39661686/swift-react-native-bridge-duplicate-interface

The difference is he is using a Swift class and I'm using an Objective C class. The documentation focuses on Swift classes, but mentions you can use private classes as well:

https://facebook.github.io/react-native/docs/native-modules-ios.html

**Comment by VTCoco** [comment]
Do not "#import <WePay/WePay.h>". It worked for me.

**Comment by christopherdro** [comment]
@facebook-github-bot answered

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/duplicate-interface-error-with-rctexternmodule
