### ISSUE TITLE
Android crash when network changes from Good to Bad

### ISSUE THREAD

**Issue by armadilio3** [facebook/react-native#10423]
### Issue Description

When there are fetch requests made on Android and the network changes from a good connection to a very bad connection, sometimes a crash occurs in RealBufferedSink.java:39.
### Steps to Reproduce / Code Snippets
1. Make constant fetch requests (Once every couple of seconds)
2. Switch between a good network connection and a very bad one (if an iPhone is available it can be used as a hotspot for the Android device and can switch between LTE and very Bad Network)

Switching between the networks should reproduce the problem fairly quickly.
#### Expected Results

The error:

> java.lang.IllegalStateException: closed
>         at okio.RealBufferedSink.write(RealBufferedSink.java:39)
>         at okio.ForwardingSink.write(ForwardingSink.java:35)
>         at com.facebook.react.modules.network.ProgressRequestBody$1.write(ProgressRequestBody.java:58)
>         at okio.RealBufferedSink.flush(RealBufferedSink.java:216)
>         at com.facebook.react.modules.network.ProgressRequestBody.writeTo(ProgressRequestBody.java:48)
>         at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:47)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
>         at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
>         at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
>         at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
>         at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
>         at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
>         at okhttp3.RealCall.access$100(RealCall.java:33)
>         at okhttp3.RealCall$AsyncCall.execute(RealCall.java:120)
>         at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
>         at java.lang.Thread.run(Thread.java:818)
### Additional Information
- React Native version: 0.41.0 (All previous version also have this issue)
- Platform(s) (iOS, Android, or both?): Android
- Operating System (macOS, Linux, or Windows?): macOS

**Comment by saleeh93** [comment]
@armadilio3 Same issue here. did you got that fixed .?

**Comment by armadilio3** [comment]
@saleeh93 still looking into it, maybe you could describe how you can replicate the crash since I am working on a fairly large project and I am only beginning to pinpoint the exact place of origin for this bug

**Comment by saleeh93** [comment]
@armadilio3 I am also working on large project and I never had that issue when I am testing it, I got those errors from Crashlytics. I didn't even understand when that is coming up

**Comment by saleeh93** [comment]
@armadilio3 Any updates ?

**Comment by LucasSouzaa** [comment]
Same issue here :(

**Comment by saleeh93** [comment]
@lucasfeliciano Still waiting to get this fixed

**Comment by armadilio3** [comment]
So, I have found a temporary solution to this problem which is based on catching the error. After some testing it seems that if you catch the OkHttp error the network request will fail but the app won't crash. So if anyone is interested here is the temporary solution:

Edit your **MainApplication.java**
```Java
    @Override
    public void onCreate() {
        super.onCreate();

        // Setup handler for uncaught exceptions.
        Thread.setDefaultUncaughtExceptionHandler (new Thread.UncaughtExceptionHandler()
        {
        @Override
        public void uncaughtException (Thread thread, Throwable e)
        {
            handleUncaughtException (thread, e);
        }
        });
    }

   public void handleUncaughtException (Thread thread, Throwable e)
    {

        if(e.getMessage() != "closed" || thread.getName() != "OkHttp Dispatcher"){
            //Kill the app
            System.exit(1);
        }else{
            //If the OkHttp error occurs we ignore it
            Log.e("OkHttp Exception","Received exception " + e.getMessage() + "From thread " + thread.getName());
        }
       
    }
```

When I have the time I will look into the root cause of this issue as this is a very poor fix. If I find a solution, will make PR.

**Comment by saleehk** [comment]
@armadilio3 You are tricky 😉

**Comment by yunlongz** [comment]
@armadilio3  I use yours,but It`s not running.

**Comment by LucasSouzaa** [comment]
@yunlongz are you building from source?
I use this "solution" and work fine.

**Comment by abrantes01** [comment]
@armadilio3's solution works fine for me. But does anyone have any news on this problems ?

**Comment by Tekosawa** [comment]
Anyone found a real fix ? Problem still exist.

**Comment by loiclouvet** [comment]
I tried @armadilio3 issue but I still have same crashes (maybe because I use react-native-fabric).

**Comment by arryanggaputra** [comment]
I got the same issue, and @armadilio3  solutions is better...

**Comment by pmachowski** [comment]
It's not stale it's real and happens in my app too as @armadilio3 described it.

**Comment by pmachowski** [comment]
seems related to this bug in okhttp: https://github.com/square/okhttp/issues/3521

That was fixed in okhttp 3.9 but react-native is using 3.6

**Comment by pavle93** [comment]
@pmachowski We have the same issue seems like there is a solution in [#11016](https://github.com/facebook/react-native/issues/11016) in the last post. We will test it tomorrow. Is there any finite solution to this problem?

**Comment by derakhshanfar** [comment]
Same issue for me.. any solution?

**Comment by derakhshanfar** [comment]
@pavle93 could you find a solution?

**Comment by DevilSoulcz** [comment]
@ pavle93   the same problem....  could you find a solution?

**Comment by nishantonline1** [comment]
@armadilio3's solution works fine for me. but there is an **error** in it, we have to import **android.util.log** in MainApplication.java.

**import android.util.Log;**  
@pmachowski Problem still in version 3.9.0

**Comment by nishantonline1** [comment]
@workostap that works for me too but the problem still persist sometimes.

**Comment by lorduriel** [comment]
To use the latest okhttp you should also upgrade your react native version.

You can also solve it by using 
`com.squareup.okhttp3:okhttp:3.5.0` or `com.squareup.okhttp3:okhttp:3.6.0`
with` com.facebook.react:react-native:0.48.X`

trying to combine higher versions with lower of each library will lead you to this error
`Undefined is not an object (evaluating 'Sn[e]')`

**Comment by kelset** [comment]
(quick update, we merged a fix for it and we'll probably cherry pick for 0.57-rc3)
