### ISSUE TITLE
MulticastLock status

### ISSUE THREAD

**Issue by luisfpinto** [facebook/react-native#10434]
Hello!

I'm developing an app which uses multicasts messages. The problem is that it doesn't work on all devices so maybe the problem is because Multicast is locked. Is there any way to change the multicast status like this? :

https://developer.android.com/reference/android/net/wifi/WifiManager.MulticastLock.html

Thanks!

**Comment by leeight** [comment]
I think you should write an NativeModule to do this. Please check out http://facebook.github.io/react-native/docs/native-modules-android.html

**Comment by christopherdro** [comment]
@facebook-github-bot answered

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/multicastlock-status
