### ISSUE TITLE
RCTImageLoader still crash

### ISSUE THREAD

**Issue by hnzlk2014** [facebook/react-native#10439]
@davidgruebl same on 0.36.0-rc.1 when fast scrolling is crash
custom Component from [https://github.com/wix/list-view-experiments](url)
![image](https://cloud.githubusercontent.com/assets/6149516/19474170/07d66768-9561-11e6-97a5-e01ad4a89825.png)
![screen shot 2016-10-18 at 6 40 54](https://cloud.githubusercontent.com/assets/6149516/19475003/8d0b02f6-9564-11e6-86ae-4ed2941f5417.jpg)

**Comment by lacker** [comment]
Hey, I don't think this issue has enough information to reproduce a problem. If you're using the wix library, you might want to file the issue there. If you can isolate the problem to something within React Native itself, then opening an issue here would be the right way to go.

**Comment by gre** [comment]
the problem definitely is linked to React Native. but also this is already raised in https://github.com/facebook/react-native/issues/10433
