### ISSUE TITLE
How to download or save file in to internal storage or external storage

### ISSUE THREAD

**Issue by thinnakrit** [facebook/react-native#10438]
## How to download or save file in to internal storage or external storage

Hi guys !.

How to download/save file to internal storage or external storage
by use 'react-native-fs' or other. 
'react-native-fs' and 'react-native-fetch-blob' don't worked.
#Android
Thank you for answer

**Comment by NameSDKz** [comment]
https://github.com/johanneslumpe/react-native-fs?files=1

**Comment by rmevans9** [comment]
@facebook-github-bot answered
