### ISSUE TITLE
OutOfMemoryError in Android WebSocketModule 

### ISSUE THREAD

**Issue by tepamid** [facebook/react-native#10437]
### Issue Description

We use two websockets simultaneous in our production app based on ReactNative. Exception tracking systems  Raygun and Google Analytics report that app crash sometimes with OutOfMemoryError while trying to create a new native thread in okhttp3.OkHttpClient. 

According to the OkHttpClient manual, "OkHttp performs best when you create a single OkHttpClient instance and reuse it for all of your HTTP calls." However in the WebSocketModule OkHttpClient is instantiated on EVERY call of connect method (which in turn is called in WebSocket.js constructor).

I see here two problems:
- If an app uses two websockets (like ours) OkHttpClient instance should be shared between websockets and likely with other networking communications done in WebSocketModule.
- If a websocket is occasionally disconnection due to absence of Internet connection, then after reconnect the same underlying OkHttpClient must be used in order to save memory.

At the same time in ReactAndroid there exists a specific OkHttpClientProvider class which enforces singleton-style usage of OkHttpClient in all other Networking communications (in NetworkingModule).

@foghina, @mkonicek, what do you think? Should we use the same OkHttpClient in WebSocketModule which is used in NetworkingModule, i.e. invoke OkHttpClientProvider.getOkHttpClient() instead of instantiating a new OkHttpClient?
Or probably at least create another OkHttpClientProvider for websockets which is to provide OkHttpClient with websocket-specific timeouts?
### Steps to Reproduce / Code Snippets

The issue is only reproduced in the production app deployed to Google Play on our customers' devices.
We could not reproduce it on neither of our developers devices.
#### Expected Results

WebSocketModule does not crash.
### Additional Information
- React Native version: issue reproduced in 0.32 (but in master branch WebSocketModule has the same code).
- Platform(s) (iOS, Android, or both?): Android
- Operating System (macOS, Linux, or Windows?): macOS

**Comment by greghe** [comment]
With each web socket using its own HTTP Client, and each client using its own connection pool, the number of threads in a React Native app can rapidly exceed 200:

![threads](https://cloud.githubusercontent.com/assets/5883925/20199667/1d82ab6e-a761-11e6-8a83-105dbd11b29c.png)

Granted, after five minutes a cleanup thread wakes up and starts to deallocate these pools and thereby reduces the number of threads to a reasonable number - but only temporarily. Once the cleanup finishes, the number of threads starts to increase rapidly again - until the next five minute cleanup - and so on - in a continuous cycle.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/outofmemoryerror-in-android-websocketmodule
