### ISSUE TITLE
[NavigationExperimental] disable pop gestures with horizontal direction

### ISSUE THREAD

**Issue by Fantasim** [facebook/react-native#10440]
Hey,

I would like to access to SceneConfigs to disable pop gestures with NavigationExperimental on React-Native.

Like that with old Navigator :

```
var sceneConfig = Navigator.SceneConfigs.FloatFromBottom;
sceneConfig.gestures.pop.disabled = true;

this.props.navigator.push({
  title: 'Search',
  component: SearchList,
  sceneConfig: sceneConfig
})

```

How can i do that with NavigationExperimental ?

* React Native version: 0.34.0
* Platform(s) (iOS, Android, or both?): iOS
* Operating System (macOS, Linux, or Windows?): macOS

**Comment by Exilz** [comment]
I managed to disable it with the prop `enableGestures` of the `CardStack` component.
I also have an array of blacklisted routes, that's checked during navigation by a middleware that will dispatch an action disabling the gestures in my Redux store.

My `CardStack` is connected to it, so I can change the prop dynamically.

It works fine for me.

**Comment by ericvicenti** [comment]
Yeah, as @Exilz said, you can disable the back gesture by setting `enableGestures` to false on your CardStack.

If you have a more specific question, feel free to tag me in another issue. Feel free to re-open this if I misunderstood your question.
