### ISSUE TITLE
How to programmatically go to home screen?

### ISSUE THREAD

**Issue by mykelaballe** [facebook/react-native#10445]
This is more of just a question. How can i go to the device's home screen programmatically, just like pressing the physical home button?

**Comment by ide** [comment]
There's no way to do this AFAIK. If you do find a way, you would write a native module to expose that behavior as described here https://facebook.github.io/react-native/docs/native-modules-ios.html.

**Comment by ide** [comment]
Looks like Android exposes this, so if you wanted this feature on only one platform this is the native code you would write and expose to JS: https://stackoverflow.com/questions/3724509/going-to-home-screen-programmatically
