### ISSUE TITLE
flex-grow

### ISSUE THREAD

**Issue by 7ynk3r** [facebook/react-native#1045]
Hello, I'm looking for a way to make an item grow. 

The idea is to have a container that fills the whole screen height and three items:
- one at the beginning
- one at the end
- one that grows to fill the the space between the first and the last item (this is the interesting one).

Something like this:

```
<View style={styles.container}>
  <View style={styles.firstItem}/>
  <View style={styles.growableItem}/>
  <View style={styles.lastItem}/>
</View>
[...]
container: {
  flex: 1,
}
```

I've tried `alignItems`, `alignSelf` and `justifyContent` with no success. 

Thanks!
JM

**Comment by ide** [comment]
Try putting `flex: 1` on growableItem. The value of the flex property specifies the ratio at which it grows relative to its siblings.

**Comment by 7ynk3r** [comment]
Hi @ide,

Thanks for the response!

I've made some progress in this but now I have a different problem.

I have this layout:
```
<ScrollView style={styles.container}>
  <View style={style.content}/>
  <View style={style.button}>
</ScrollView>
```
What I want to achieve is to set `button` always at the bottom of the screen. If `content` is larger than the screen's height, it will end up outside the viewport but I can scroll to it.

If I replace `ScrollView` with `View` I can use
```
container: {
  flex: 1,
  justifyContent: 'space-between',
},
```
but that doesn't work with `ScrollView`, I got the following error 
```
Cannot adjust current top of stack beyond available views.
``` 

I need `ScrollView` because `content` may exceed the screen's 

JM

**Comment by robertjpayne** [comment]
@7ynk3r why don't you set the button to `position: absolute` and snap it to the bottom of the screen? Does it need to be inside the scroll view?

**Comment by brentvatne** [comment]
@robertjpayne's solution could work - or you can just do something like this

```
   <View style={{flex: 1}}>
     <View style={{height: 50}}><Text>first item</Text></View>
     <ScrollView style={{flex: 1}}>
     </ScrollView>
     <View style={{height: 50}}><Text>last item</Text></View>
   </View>
```

Either way, this question is better suited for IRC as it's not really an issue, more of a "how to use Flexbox" type of inquiry :smile:

**Comment by 7ynk3r** [comment]
Thanks for the responses! 
Your ideas were really helpful. I've solved the problem I had.
JM
