### ISSUE TITLE
[Android] AppRegistry.runApplication was called twice when wake up the app

### ISSUE THREAD

**Issue by RobGu** [facebook/react-native#10452]
### Issue Description

It usually happens at the first time launch the new installed app.
### Steps to Reproduce / Code Snippets
1. remove the app installed before
2. install the app
3. set the app to background
4. wait a moment
5. wake up the app
### Additional Information
- React Native version: 0.35.0
- Platform(s) (iOS, Android, or both?): Android 4.2.1
- Operating System (macOS, Linux, or Windows?): macOS

**Comment by lacker** [comment]
How is this causing a problem for your application? Usually you would not be relying on `runApplication` directly in any way. Ie, what do you see in the "steps to reproduce" that you do not expect to see.

**Comment by RobGu** [comment]
When integrate with react-native-router-flux, it consoles "Key xxx is already defined!"

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/android-appregistryrunapplication-was-called-twice-when-wake-up-the-app
