### ISSUE TITLE
App crash while playing video in modal 

### ISSUE THREAD

**Issue by krishbhattacharyya** [facebook/react-native#10475]
## App crash while playing video in modal

Hi, I am facing problem while playing dynamic video in a single modal.  I have added a webview component in a modal where I pass "source={{ uri: dynmic path }}" and on every click I have assigned the " {{ uri: dynmic path }}". 

But the problem is that on the first click the video played well but when I want to close the pop up the app crashed ( One thing I hide the popup & passing blank on "source={{ uri:dynmic path }}". If I used the "uri" Without video it seems well but while sending the video ( only tested html5 video) it crashed. 

Am I wrong any where or it is an issue in webview. Can you suggest anything or solve my problem?

**Comment by krishbhattacharyya** [comment]
Sorry I have noticed now if the video loaded there is no issue for now but if not loaded properly when I close the popup then this is occurred.

**Comment by krishbhattacharyya** [comment]
Hi,
Last update is, it crashed in simulator not in device. After confirmation I will update my feedback.

**Comment by lacker** [comment]
Can you provide a rnplay.org link that reproduces this?

**Comment by krishbhattacharyya** [comment]
okay I am sending you the repo link very soon.

**Comment by krishbhattacharyya** [comment]
Thanks for giving me the response @lacker ,
Short demo in video play :
https://rnplay.org/apps/6S2vHQ

But I do not know why the video is not showing in rnplay where as the video is still there & also progress bar is working fine ( In my simulator & device the video is display properly).

This is not my objective. So as per my question why the simulator is crashed while playing the dynamic video in webview? 

Is the video working in all devices? And is there any video player like facebook with full screen? Can you suggest me?

**Comment by lacker** [comment]
Is this bug just happening totally within the `WebView` then? Maybe your app is running out of memory? It's pretty tough to figure it out if it's not reproducible in a different environment.

**Comment by krishbhattacharyya** [comment]
Thanks @lacker . Okay I understand the problem but the thing is that I have shared you the code. Is the code is wrong( though I have passed the video url with parameter in a small function )?

Can you suggest me for the modal video? I have already told you the last Comment. I need a modal with video play like facebook. How can  I do this? 

With the : 
https://github.com/react-native-community/react-native-video

Or is there any other way to do this which is not running out of memory.

**Comment by lacker** [comment]
Yeah if I were doing this I would try not using a WebView. That sort of just adds an extra layer of complexity. Try using https://github.com/react-native-community/react-native-video here.
