### ISSUE TITLE
[iOS] ListView crashes when updateClippedSubviews triggers RCTImageView.cancelImageLoad 

### ISSUE THREAD

**Issue by seph14** [facebook/react-native#10473]
### Issue Description

I have a ListView of small cells of products, when I pulled very fast to trigger the load more, there's a chance it crashes. It is especially frequent on slower devices: iPhone5 / iPhone6plus.  
If setting removeClippedSubviews to be false, it appears solve the problem.
### Steps to Reproduce / Code Snippets

![simulator screen shot 2016 oct 20 15 14 51](https://cloud.githubusercontent.com/assets/6417336/19549843/23d0cd04-96d9-11e6-936d-255fa5280e6d.png)
This is the list view. Sorry the full code seem to be a bit long but since I can reproduce this on several different listviews, this shouldn't be an special case. 

And this is the stack trace from Xcode:
![stacktrace](https://cloud.githubusercontent.com/assets/6417336/19551745/4fd216dc-96df-11e6-90c6-36b01056929c.png)

Looks like is rooted from the clipping process. 
#### Expected Results

Shouldn't crash
### Additional Information
- React Native version: 0.35
- Platform(s):iOS
- Operating System:OSX

**Comment by SunnyGurnani** [comment]
This is similar https://github.com/facebook/react-native/issues/10433

**Comment by SunnyGurnani** [comment]
@seph14 I tried setting removeClippedSubviews={false} but that didnt stopped the crashes.

**Comment by seph14** [comment]
@SunnyGurnani  I think the clipping action removes those invisible images which finally lead to the crash. You are right its a temporary hack and doesn't fix the root.

**Comment by hramos** [comment]
Closing as ListView is deprecated in 0.43. Use FlatList.
