### ISSUE TITLE
Forget to call free function

### ISSUE THREAD

**Issue by yang2012** [facebook/react-native#1047]
In method RCTBridgeModuleClassesByModuleID, there need to free the array with free() after calling objc_copyClassList

**Comment by nicklockwood** [comment]
Ah, well spotted. Thanks!

**Comment by ide** [comment]
This was fixed in https://github.com/facebook/react-native/commit/b99744a164f96be2989d686495a1c7d1afac737a#diff-e15318f48b6447f2d9936c5e047d882fR194
