### ISSUE TITLE
 Navigator component getting umounted some times 

### ISSUE THREAD

**Issue by saleeh93** [facebook/react-native#10481]
### Issue Description
Some times the push and pop to navigator is not working,
Its seems issue exist only in android ,getting the warning below
All other operations are working just fine 

Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Navigator component.

### Steps to Reproduce / Code Snippets

I am using navigator -> Android DrawerLayoutAndroid 

### Additional Information

* React Native version: 34.1
* Platform(s) (iOS, Android, or both?): Android
* Operating System (macOS, Linux, or Windows?): macOS

**Comment by saleeh93** [comment]
I wasn't using `componentWillUnmount` currently

**Comment by WaterEye0o** [comment]
I also met the same problem,how do you solve the final? @saleeh93

**Comment by saleeh93** [comment]
@WaterEye0o I was having a null reference on a component. So I have manually remove the reference on `componentWillUnmount`. Then it needs to add it again. then i got it fixed

**Comment by WaterEye0o** [comment]
how do you manually remove the reference on componentWillUnmount. @saleeh93

**Comment by jbrumwell** [comment]
@WaterEye0o I ran into this as well and from my experience I was holding a reference to an old `navigator` that was being passed down in the `renderScene` method. Removing this reference solved the issue for me.

```
renderScene={(route, navigator) => {
          if (! context.navigator) {
            context.navigator = navigator;
          }

          return (
            <Wrapper context={context}
                     handler={route.handler} />
          );
        }}
```

```
componentWillUnmount() {
    context.navigator = null;
  }
```

**Comment by WaterEye0o** [comment]
thank you @jbrumwell

**Comment by saleeh93** [comment]
@WaterEye0o Sorry I didn't saw the notification, I did the same way @jbrumwell did
