### ISSUE TITLE
dev server doesnt work on device

### ISSUE THREAD

**Issue by nickmacia** [facebook/react-native#10487]
I'm using React Native v0.35 after upgrading from v0.26. I can no longer use the dev server on my device like I used to. When it builds to my phone, connected on the same wireless ip as my macbook, it builds from a pre bundle instead of the server. I used to be able to just set the ip in the app delegate, but that's no longer an option. I just want to be able to develop on an actual device.

**Comment by lacker** [comment]
Can you get a new app to work with 0.35? I think testing that will determine whether the problem is with your machine, or with your codebase.

**Comment by nickmacia** [comment]
This is just with the standard "hello world" react native app. I create a new project via `react-native init`, open the xcode project, select my device that's connected by usb and on the same wifi network, and it still refuses to build the dev server. I'm at a loss.

**Comment by nickmacia** [comment]
I'm closing this issue because it has been patched for the upcoming release of RN. The auto ip code had issues with mac connections over wifi. Solution FIX #9617.
