### ISSUE TITLE
libc++abi.dylib: terminating with uncaught exception of type NSException

### ISSUE THREAD

**Issue by roysG** [facebook/react-native#10498]
react native version 0.35

output:
...
(null)] Output protocol disconnected
2016-10-21 18:09:56.829 NativeApp[11910:137448] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'bridge is not set. This is probably because you've explicitly synthesized the bridge in RCTNetworking, even though it's inherited from RCTEventEmitter.'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010f79234b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010e6a221e objc_exception_throw + 48
	2   CoreFoundation                      0x000000010f796442 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x000000010e26ee09 -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:] + 166
	4   NativeApp                           0x000000010dd7ce18 -[RCTEventEmitter sendEventWithName:body:] + 408
	5   NativeApp                           0x000000010de5ea75 __76-[RCTNetworking sendRequest:responseType:incrementalUpdates:responseSender:]_block_invoke.382 + 949
	6   NativeApp                           0x000000010de522fa __50-[RCTNetworkTask URLRequest:didCompleteWithError:]_block_invoke + 74
	7   NativeApp                           0x000000010de5104d -[RCTNetworkTask dispatchCallback:] + 77
	8   NativeApp                           0x000000010de52204 -[RCTNetworkTask URLRequest:didCompleteWithError:] + 356
	9   NativeApp                           0x000000010de60a18 -[RCTHTTPRequestHandler URLSession:task:didCompleteWithError:] + 184
	10  CFNetwork                           0x000000010f2ddfac __51-[NSURLSession delegate_task:didCompleteWithError:]_block_invoke.185 + 76
	11  Foundation                          0x000000010e1a62cd __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
	12  Foundation                          0x000000010e1a5faf -[NSBlockOperation main] + 101
	13  Foundation                          0x000000010e1a46ac -[__NSOperationInternal _start:] + 672
	14  Foundation                          0x000000010e1a05ef __NSOQSchedule_f + 201
	15  libdispatch.dylib                   0x000000011389f0cd _dispatch_client_callout + 8
	16  libdispatch.dylib                   0x000000011387ce6b _dispatch_queue_serial_drain + 236
	17  libdispatch.dylib                   0x000000011387db9f _dispatch_queue_invoke + 1073
	18  libdispatch.dylib                   0x000000011387e07f _dispatch_queue_override_invoke + 683
	19  libdispatch.dylib                   0x00000001138803b7 _dispatch_root_queue_drain + 720
	20  libdispatch.dylib                   0x000000011388008b _dispatch_worker_thread3 + 123
	21  libsystem_pthread.dylib             0x0000000113c4e746 _pthread_wqthread + 1299
	22  libsystem_pthread.dylib             0x0000000113c4e221 start_wqthread + 13
)
2016-10-21 18:09:56.830338 NativeApp[11910:141804] [] nw_endpoint_handler_cancel [7.2 104.28.2.45:80 initial path (null)]
2016-10-21 18:09:56.831162 NativeApp[11910:141804] [] nw_resolver_cancel_on_queue 0x608000113050
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by lacker** [comment]
I think this issue would need to have enough information to reproduce the problem, in order for us to help you out. Try posting an app that reproduces the problem, or a link to a sample project that has this problem. I'm going to close this issue but feel free to open a new one if you have that info.
