### ISSUE TITLE
Draw order is different for native views for ios and android.

### ISSUE THREAD

**Issue by anttitakalahti** [facebook/react-native#10496]
I have two native Views showing video from TokBox. 

The draw order in render() is as follows:
first the large video, 
then the red box and inside the red box the a small video.

When I disable the small video and replace it with an empty View and re-enable it the draw order changes so that the small video is hidden behind the large video but the View component with red background is shown on top of the large video but in place of small video there is to large video. So the red box is both on top of the background video and behind it.

the zIndex for video below is 1 and for the topmost video it is 3

![image showing the problem](https://cloud.githubusercontent.com/assets/837046/19600519/0caa188a-97ae-11e6-82e0-0181eefab408.jpg)

Using react-native: 0.35.0

**Comment by lacker** [comment]
Is this behavior specific to videos or does it happen for any sort of component?

A reproduction on rnplay.org would be pretty helpful here.

**Comment by anttitakalahti** [comment]
I think it needs a native component but I can try to reproduce it with a simpler view using the requireNativeComponent

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/draw-order-is-different-for-native-views-for-ios-and-android
