### ISSUE TITLE
Interpolated values not working inside transform matrix.

### ISSUE THREAD

**Issue by sankhadeeproy007** [facebook/react-native#10493]
I was trying out the transform matrix to achieve a 3D transform along a specified pivot. So far I've been able to set the axis for transforming using a matrix. However the matrix only accepts integers. Is there any way I can use an interpolated value inside the matrix? 
I can attach code samples if necessary but I think the question is descriptive enough.

**Comment by sankhadeeproy007** [comment]
Also I tried using an Animated.Value which failed too. How do you guys suggest I go about it?

**Comment by christopherdro** [comment]
@facebook-github-bot icebox

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/interpolated-values-not-working-inside-transform-matrix
