### ISSUE TITLE
react-native link fails for iOS if there are other projects in the main app folder

### ISSUE THREAD

**Issue by robclouth** [facebook/react-native#10494]
### Issue Description

```react-native link``` fails for iOS if there are other xcode projects in the main app folder. This is because in ```findProject.js```, the ```findProject(folder)``` method doesn't prioritise projects in the ```<root>/ios``` folder. This means that it picks the wrong project as the main project, and linking fails.

This is a problem when you have a git submodule that contains an xcode project.

### Steps to Reproduce / Code Snippets

Put another xcode project in the root app folder and run ```react-native link```.

### Additional Information

* React Native version: 0.35.0
* Platform(s): iOS
* Operating System: macOS

**Comment by robclouth** [comment]
```
module.exports = function findProject(folder) {
  const projects = glob
    .sync(GLOB_PATTERN, {
      cwd: folder,
      ignore: GLOB_EXCLUDE_PATTERN,
    })
    .filter(project => {
      return path.dirname(project) === IOS_BASE || !TEST_PROJECTS.test(project);
    });

  if (projects.length === 0) {
    return null;
  }

  return projects[0];
};
```
This is the code that tries to find the main app xcode project. It will find projects in the root app folder before those in the ```/ios``` folder, thus picking the wrong project when doing ```projects[0]```.

**Comment by leeight** [comment]
PR is welcome.

**Comment by robclouth** [comment]
Great, on the case

**Comment by lacker** [comment]
shipping https://github.com/facebook/react-native/pull/10495

**Comment by macelii** [comment]
Experiencing the same problem with RN 49 on iOS.
react-native link returns with success message but link actually fails and it requires a manual installation.
