### ISSUE TITLE
Packager stops and only returns "this is not defined"

### ISSUE THREAD

**Issue by kelvinaliyanto** [facebook/react-native#10491]
Hi, I have finally upgraded from RN 0.29.0 to RN 0.35.0, and also installed react@15.3.1 because its dependancy. After I run react-native upgrade, I try to run react-native start, but it prematurely stops. Here is when it stops:
### packager starts

Scanning 625 folders for symlinks in dir/project/node_modules (12ms)
 ┌────────────────────────────────────┐ 
 │  Running packager on port 8081.                                                                        │ 
 │                                                                                                                                │ 
 │  Keep this packager running while developing on any JS projects. Feel           │ 
 │  free to close this tab and run your own packager instance if you                    │ 
 │  prefer.                                                                                                                   │ 
 │                                                                                                                                │ 
 │  https://github.com/facebook/react-native                                                         │ 
 │                                                                                                                                │ 
 └────────────────────────────────────┘ 
Looking for JS files in
   dir/project

this is not defined
### packager ends

Anyone having this issue? Tried to init a new project, and I can run the react-native start command. It's too troublesome to delete and re-do the whole node_modules everytime I upgrade (at least I did it once before), as I have a lot of third-party npm plugin. Please help to advise.

**Comment by ericvicenti** [comment]
Sorry you're having troubles upgrading! Could you try isolating the issue to see what package causes the problem?

Are your npm packages up to date? Sometimes things change in react-native which causes breakages in dependencies. If you're using old versions of your packages, they may not work with the latest version of react-native.

**Comment by kelvinaliyanto** [comment]
Hi @ericvicenti , thanks for replying. Can you suggest on how to isolate the issue to see which package causes the problems? For now, I make a new project and copy the node-modules over to that project, and then copy the other npm package that I need from my previous node-modules folder. It works, just that it is too tedious.

**Comment by ericvicenti** [comment]
If the log output doesn't point to a specific package, then yes that would be a good approach. If you have a lot of modules you can eliminate half of them quickly by seeing which half of modules causes the error. Then repeat/bisect down to the package that is causing troubles.

You can also use yarn for your npm installs, which should allow you to test faster

**Comment by vinayr** [comment]
I resolved this issue by upgrading node to latest version (7.0.0)

**Comment by AdamJakiela** [comment]
@vinayr This resolved the issue for me. Thank you.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/packager-stops-and-only-returns-this-is-not-defined
