### ISSUE TITLE
Using TabBarIOS prevents Cmd-R from refreshing the app.

### ISSUE THREAD

**Issue by vijayst** [facebook/react-native#10505]
### Issue Description

Using TabBarIOS prevents Cmd-R from refreshing the app.

### Steps to Reproduce / Code Snippets

Do a Cmd-R to refresh the app.
Add a TabBarIOS component to the app.
Do a Cmd-R. App refresh stops working.

#### Expected Results

Cmd-R should continue to refresh the app after TabBarIOS is added.

### Additional Information

* React Native version: 0.32
* Platform(s) (iOS, Android, or both?): iOS
* Operating System (macOS, Linux, or Windows?): Mac / iPhone simulator.

**Comment by ericvicenti** [comment]
I cannot reproduce this issue with a fresh project on RN 0.35

If you have a way to reproduce this on the latest version, please re-open this issue!
