### ISSUE TITLE
When remote debugging is turned on, underlying error in promise rejection causes: NSError RCTJSONStringify: Invalid type in JSON write (NSError)

### ISSUE THREAD

**Issue by neilsarkar** [facebook/react-native#10506]
### Issue Description

Some native modules such as `NSFileManager` return an `NSError` that has an underlying `NSError` in the `userInfo` dictionary. React native handles this fine out of the box, but when the remote debugger is turned on, the websocket message sender chokes on attempting to stringify the second `NSError` into json.

I'm happy to help fix this, first time contributing so any pointers are welcome.

### Steps to Reproduce / Code Snippets

I've posted a repository with the minimal reproduction case here https://github.com/superseriouscompany/react-native-error-repro

The steps are: first, turn on remote debugging. Then implement the following code:

```objective-c
// objc
RCT_EXPORT_METHOD(triggerError:(NSString *)foo
                  resolver:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)
{
  NSError *underlyingError = [NSError errorWithDomain:@"underlyingDomain" code:419 userInfo:nil];
  NSError *err = [NSError errorWithDomain:@"domain" code:68 userInfo:@{@"NSUnderlyingError": underlyingError}];
  
  reject(@"foo", @"bar", err);
}
```

```js
// js
triggerError('anything').catch(err => { console.log(err)})
```

#### Expected Results

error is logged to console, execution continues.

#### Actual Results

<img src="https://cldup.com/8jLLb3j8ZX.png" />

### Additional Information

* React Native version: 0.35.0
* Platform(s) (iOS, Android, or both?): iOS
* Operating System (macOS, Linux, or Windows?): macOS

**Comment by lacker** [comment]
By the way I really appreciate that you are just sending a pull request to fix this! So props for that.

**Comment by fungilation** [comment]
I'm still hitting a similar error:
```
RCTJSONStringify() encountered the following error: Invalid type in JSON write (NSURL)
```

With `NSURL` in brackets instead.

I haven't been hitting this error until I upgraded RN from 0.37 to 0.41.

**Comment by miklschmidt** [comment]
@fungilation until or since? Because i still have it on 0.41.2.

**Comment by fungilation** [comment]
Until. I've never seen it on 0.37 and older. But that could just have been me testing less before.

**Comment by miklschmidt** [comment]
Okay, in my case it seems to be the AppTransportSecurityPolicy (or whatever it's called) that wasn't set to allow insecure connections. I had to hack RTCUtils.m:82 to print the JSON blob instead of the error. It seems like it's the userInfo object that's the cause of the issue.

**Comment by fungilation** [comment]
In my case, I've already set AppTransportSecurityPolicy allowed insecure connections.

**Comment by miklschmidt** [comment]
Try doing the same thing, the json blob will tell you what's wrong. It's a workaround for now at least.

**Comment by neilsarkar** [comment]
You can also disable Remote JS Debugging and read the logs from the XCode console in order to find out what the actual error is. 

So I could write the same kind of patch for an `NSError` containing an `NSURL` that I did for an `NSError` containing an `NSError`, but that feels like playing a game of whack-a-mole...theoretically any object could be returned from an error and we would have to keep special casing in this function to serialize the error.

Anyone with a little more objective c knowledge have a suggestion for a way to generically stringify (or, worst case, strip) any type of object that could be attached to an error?

**Comment by neilsarkar** [comment]
I was unable to reproduce with the following test:

```objc
- (void)testEncodingNSURL
{
  NSURL *url = [[NSURL alloc] initWithString:@"https://www.facebook.com"];
  
  NSError *err = [NSError errorWithDomain:@"domain" code:68 userInfo:@{@"url": url}];
  
  // An assertion on the full object would be too brittle since it contains an iOS stack trace
  // so we are relying on the behavior of RCTJSONParse, which is tested below.
  NSDictionary<NSString *, id> *jsonObject = RCTJSErrorFromNSError(err);
  NSString *jsonString = RCTJSONStringify(jsonObject, NULL);
  NSDictionary<NSString *, id> *json = RCTJSONParse(jsonString, NULL);
  XCTAssertEqualObjects(json[@"code"], @"EDOMAIN68");
  XCTAssertEqualObjects(json[@"message"], @"The operation couldn\u2019t be completed. (domain error 68.)");
  XCTAssertEqualObjects(json[@"domain"], @"domain");
  XCTAssertEqualObjects(json[@"userInfo"][@"url"], @"https://www.facebook.com");
}
```

so it may be a new or different error. can anyone provide steps for reproduction?
