### ISSUE TITLE
Conditional JSX does not re-evaluate when state changes

### ISSUE THREAD

**Issue by quadsurf** [facebook/react-native#10502]
When determining whether or not to display conditional JSX views, RN evaluates the condition once, and then renders views accordingly. But when I change my state's value that directly affects how the JSX conditional evaluates, the condition is not being re-evaluated. I have tried running forceUpdate() but that doesn't seem to work in RN like it does in browser-based React. Is there a work-around for this?

Is there a way to force my conditional JSX to be re-evaluated when state is updates or changed?

**Comment by lacker** [comment]
React does re-evaluate when state updates, you shouldn't need to run forceUpdate. There's probably a bug elsewhere in your code. I'm going to close this issue - if you have a repro app with code that shows state not updating, like on rnplay.org, then feel free to reopen or open a new one.
