### ISSUE TITLE
iOS TextInput keyboardappearance-prop doesn't update appearance if keyboard is open

### ISSUE THREAD

**Issue by ippa** [facebook/react-native#10501]
### Steps to Reproduce / Code Snippets

Using: https://facebook.github.io/react-native/docs/textinput.html#keyboardappearance

`<TextInput keyboardAppearance={this.props.isDark ? 'dark' : 'light'} />`

Toggling this.props.isDark true|false doesn't change the keyboard appearance if the keyboard is open. If I close the keyboard and open it again, the appearance has updated.
#### Expected Results

keyboard appearance should update right away even if it's open.
### Additional Information
- React Native version: 0.36.0-rc.1
- Platform(s) (iOS, Android, or both?): iOS
- Operating System (macOS, Linux, or Windows?): macOS

**Comment by christopherdro** [comment]
@facebook-github-bot answered

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/ios-textinput-keyboardappearance-prop-doesnt-update-appearance-if-keyboard-is-op
