### ISSUE TITLE
Expose SwipeableQuickActions & SwipeableQuickActionButton classes

### ISSUE THREAD

**Issue by Paul-Todd** [facebook/react-native#10509]
### Issue Description

SwipeableQuickActions & SwipeableQuickActionButton need to be exposed along with the already exposed SwipeableListView class
### Steps to Reproduce / Code Snippets

As per the documentation in the source file
import {.... SwipeableQuickActions, SwipeableQuickActionButton } from "react-native";
.....
 <SwipeableQuickActions>
         <SwipeableQuickActionButton text={"Edit"} style={{backgroundColor: 'blue'}} />
         <SwipeableQuickActionButton text={"Remove"} style={{backgroundColor: 'red'}} />
  </SwipeableQuickActions>
#### Expected Results

Running the application should not throw a "Element type is Invalid" exception/error
### Additional Information
- React Native version: 0.35.0
- Platform(s) (iOS, Android, or both?): Both
- Operating System (macOS, Linux, or Windows?): macOS

**Comment by lacker** [comment]
Hmm, we don't have any docs for SwipeableListView. It's not clear to me whether this is supposed to be exposed here. It is currently essentially an internal API.

**Comment by jamesjenner** [comment]
Have a look at: https://github.com/facebook/react-native/issues/8005. Stated on the 8th of June that doco will be landing soon (for a given definition of soon I presume). Goes on to state taht the following should be used for documentation for now: 

https://github.com/facebook/react-native/commit/381a0051c7ec5bde4c35967e336050c8dca6a677 

The above includes the following comment from the code:

```
/**
  * A thin wrapper around standard quick action buttons that can, if the user
  * chooses, be used with SwipeableListView. Sample usage is as follows, in the
  * renderQuickActions callback:
  *
  * <SwipeableQuickActions>
  *   <SwipeableQuickActionButton {..props} />
  *   <SwipeableQuickActionButton {..props} />
  * </SwipeableQuickActions>
  */
```
That to me implies that SwipeableQuickActions and SwipeableQuickActionButton should be available and not just internal.

**Comment by lacker** [comment]
Hmm, it doesn't seem like a great idea to put a component into "Experimental" and just open-source it without having it be clear whether it's supported or not. It seems kind of half-open-sourced at the moment. @fred2028 do you intend to finish up the SwipeableListView & be maintaining it? If not then I think we should hold off on exposing more functionality until there is an owner for the code. In the meantime @Paul-Todd it seems like you could even just make this into a separate module.

**Comment by Paul-Todd** [comment]
In the end I based the code off the code in the UIExplorer which offered more flexibility but I should have tried @jamesjenner 's answer I guess.
