### ISSUE TITLE
React Native Meetup Belgium

### ISSUE THREAD

**Issue by dejakob** [facebook/react-native#10508]
Hey guys,

I am (or we, FLAVR are) organising a React Native meetup on Wednesday and as far as I know it's the first one in Belgium. I have worked a lot with RN before and was just wondered if there were some things I should definitely mention or cannot forget.

I made a little hackathon project on a private GitHub repo including some basic Relay, Redux, Immutable, etc. As I don't want to share the solution publicly before the event, I will keep the repo private and will invite people in case you want to take a look. I already invited @nicklockwood and @vjeux to the repo. If you have any remarks on the project, feel free to let me know.

Greets,
dejakob

**Comment by hramos** [comment]
@dejakob I suggest you post this to the RN Community FB group, it's a better place to discuss this sort of topic. Feel free to tag me and we'll follow up there https://www.facebook.com/groups/react.native.community/
