### ISSUE TITLE
Viewstyle 's borderLeftcolor  or other pozitionColor attribute is never work?

### ISSUE THREAD

**Issue by aqnaruto** [facebook/react-native#10511]
![image](https://cloud.githubusercontent.com/assets/9067159/19625057/9cec3e6c-9940-11e6-86ea-6ffe83cd0e71.png)
I set those color,but no none worked!

**Comment by aqnaruto** [comment]
to additonal descript ,  only add the  **borderStyle** attri ,can cause this problem!

**Comment by ericvicenti** [comment]
Seems to be the same bug as https://github.com/facebook/react-native/issues/3159

What version of `react-native` are you using? Is it on iOS or Android?

Can you please provide a more specific description and say exactly what you expected to happen, in comparison to what actually happened?

**Comment by Gacnt** [comment]
What I'm trying to do

What's happening
[!What I'm trying to do]
(http://i.imgur.com/9ZVk72f.png)

What I'm trying to do
[!What I'm trying to do]
(http://i.imgur.com/37WOZLF.jpg)

Code

```
const styles = StyleSheet.create({
  titleSection: {
    flex: 1,
    borderBottomWidth: 1,
    borderBottomColor: 'black',
    borderStyle: 'dotted',
    flexDirection: 'row'

  },

 <View style={styles.titleSection}>
          <FAIcon name={this.state.collapsed ? "chevron-circle-right" : "chevron-circle-down"} style={styles.titleIcon} size={20} />
          <TouchableOpacity onPress={() => this._collapser()}>
            <Text style={styles.title}>{this.props.titleName}</Text>
          </TouchableOpacity>
        </View>
```

Running on `react-native run-ios`

**Comment by aqnaruto** [comment]
i am using version 3.2 ,i am sorry the latest vesion is worked .  thank your excellent work @ericvicenti @Gacnt

**Comment by Gacnt** [comment]
It's not working for me, latest version.

**Comment by aqnaruto** [comment]
u can try it on facebook rn website . @Gacnt

**Comment by ericvicenti** [comment]
@Gacnt, does it work when borderRadius is set? Do you get any warnings?

**Comment by Gacnt** [comment]
Here is a rnplayground

https://rnplay.org/apps/dMM6qA with my exact issue, uncomment line 30 in that playground and watch the border disappear.

**Comment by aqnaruto** [comment]
![image](https://cloud.githubusercontent.com/assets/9067159/19753973/ca248f30-9c3b-11e6-9f69-eb88524b3187.png)
yeah ,it is not work on rnplay.
here is sourcecode
` <View style={{ width: 230,
    height: 230, backgroundColor: '#fff',  borderBottomColor: '#f00',
    borderBottomWidth: 4, borderStyle:'dashed',}}>
        <Text style={styles.instructions}>
          test border color.
        </Text>

       </View>`

**Comment by liu-jian-neu** [comment]
any update?
