### ISSUE TITLE
Animating Images from scale 0 to 1

### ISSUE THREAD

**Issue by daniel-nagy** [facebook/react-native#10510]
### Issue Description

When using `Animated.event` to map the user's scroll position to the scale of an image, if the scroll position is such that the scale of the image is zero when the view is first rendered then the image will never be displayed.

Gifs speak a thousand words...

![d](https://cloud.githubusercontent.com/assets/1622446/19622524/e67e8372-9860-11e6-9870-c624e00dbfe8.gif)

The yellow box error is complaining about `fetch`,

`Unable to symbolicate stack trace: fetch is not a function`

Most likely because I am using Apollo Client, #9605
### Steps to Reproduce / Code Snippets

``` javascript
constructor(props) {
    super(props);

    this.state = {
      scrollY: new Animated.Value(SCROLL_MIN)
    };

    this.onScroll = Animated.event([{
      nativeEvent: {
        contentOffset: {
          y: this.state.scrollY
        }
      }
    }]);
  }

renderAvatar() {
    if(this.props.presentationStyle !== expanded) {
      return null;
    }

    const props = {
      style: [styles.avatar],
      source: {
        uri: this.state.business.avatar
      }
    };

    const interpolate = {
      inputRange: [SCROLL_MIN, SCROLL_MAX_AVATAR],
      extrapolate: 'clamp'
    };

    const scale = this.state.scrollY.interpolate({
      ...interpolate,
      outputRange: [1, 0]
    });

    const translateY = this.state.scrollY.interpolate({
      ...interpolate,
      outputRange: [0, TRANSLATE_AVATAR_MAX]
    });

    props.style.push({
      transform: [{translateY}, {scale}]
    });

    return <Animated.Image {...props} />
  }
```
#### Expected Results

The image should scale from 0 to 1 when the initial scale is 0.
### Additional Information
- React Native version: `0.35.0`
- Platform(s) (iOS, Android, or both?): IOS
- Operating System (macOS, Linux, or Windows?): OSX

**Comment by ericvicenti** [comment]
To help narrow the issue down, can you [listen to the animated value](https://facebook.github.io/react-native/docs/animated.html#addlistener) and tell us what it logs? This will tell us if the issue is with `Animated.event` or something wrong with `Animated.Image`

**Comment by daniel-nagy** [comment]
@ericvicenti It logs the current scroll position even when the image is not rendered so It seems like `Animated.event` is working as expected.

**Comment by ericvicenti** [comment]
Maybe we could simplify the example repro case. Does this issue also happen on Android?

**Comment by daniel-nagy** [comment]
I do not have an android device to test on. I can try to put together a simple app to reproduce the issue.

**Comment by ericvicenti** [comment]
Try rnplay.org, it should be an easy way to share the sample app and test on Android

**Comment by daniel-nagy** [comment]
I created a demo [app](https://rnplay.org/apps/ppDHJA) to reproduce this issue. The animation is really bad in the simulator but the image will scale from 0 to 1 as you scroll.

You will notice on IOS the image is never rendered. On Android the image will scale as you scroll but the initial scale is not correctly set to 0. It is initially rendered with a scale of 1 and as you begin scrolling the scale jumps to 0 and then increase back to 1.

**Comment by brentvatne** [comment]
cc @janicduplessis

**Comment by Daniel-Goodwin** [comment]
In the meantime set the initial scale value to 0.01, that will force it to be rendered but is not big enough to be visible.

**Comment by joerick** [comment]
Might not be related, but I've just debugged a problem where touch events were being swallowed because a view had `transform: {scale: 0}` (zero from an animated value). The -[UIWindow hitTest:withEvent:] method was returning this invisible view every time.

Doing an interpolate so that the minimum scale is 0.001 fixes the problem.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/animating-images-from-scale-0-to-1

**Comment by Noitidart** [comment]
What about using a scale of `0.00001`?

**Comment by kevinmcampos** [comment]
@Daniel-Goodwin you sir, has just saved my day!
