### ISSUE TITLE
I cant apply my code modification directly

### ISSUE THREAD

**Issue by yuda1124** [facebook/react-native#10512]
I fixed my code and reload, but my application is not accepted directly.
when i change my code, i have to rebuild.
it is very hard work and low performance.
please help me.

**Comment by markspolakovs** [comment]
Are you changing native (ObjC/Java) code or JavaScript? If it's native, then (to the best of my knowledge) there's nothing you can do. If you're changing JavaScript, though, it should be reloadable - in the simulator press Cmd+R or R twice and it should update the javascript.

**Comment by ericvicenti** [comment]
Feel free to re-open this if you have more details.

If you're having troubles reloading the JS in your app, make sure the simulator/device connect to the RN packager, and restart the packager if you're having troubles.
