### ISSUE TITLE
Large accuracy values

### ISSUE THREAD

**Issue by ghost** [facebook/react-native#10514]
Regarding the use of this react API, I have been facing a strange case of receiving high accuracy values. Is this is normal?

`<location latitude="37090240" longitude="-95712891" accuracy="1488703" timezone="-180" locale="en-GB" language="en"></location>`

**Comment by ericvicenti** [comment]
What API are you using, can you link to the documentation?

I've never seen the `<location` tag that you're referencing.

**Comment by christopherdro** [comment]
@facebook-github-bot no-reply

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/large-accuracy-values
