### ISSUE TITLE
Update to 0.4.1 - rendering not working for e.g. texts and images

### ISSUE THREAD

**Issue by PhilippKrone** [facebook/react-native#1051]
Hi,

I've just updated to 0.4.1 and each screen is rendering completely wrong, e.g. without images and texts.

Anyone else experiencing the same? After going back to 0.4.0, everything is working again.

Regards
Philipp

**Comment by finalquest** [comment]
I've just updated from 0.4 to  0.4.1 and everything works fine, texts and images

**Comment by PhilippKrone** [comment]
Ok, weird.

0.4.0:
![ios simulator screen shot 28 apr 2015 21 26 49](https://cloud.githubusercontent.com/assets/11861008/7378394/5a98f596-eded-11e4-8264-322d17d35eee.png)


0.4.1:
![ios simulator screen shot 28 apr 2015 21 28 31](https://cloud.githubusercontent.com/assets/11861008/7378422/89b2df4a-eded-11e4-9ac3-f4b790e1a195.png)


No other changes done in the source code.

**Comment by brentvatne** [comment]
@PhilippKrone - just a shot in the dark, did you try restarting XCode?

**Comment by PhilippKrone** [comment]
@brentvatne did not before, but just did - no success. I'll try to create a minimal example, let's see whether my weird behaviour can be localized. :-)

**Comment by PhilippKrone** [comment]
@brentvatne ok, I was able to figure it out, atleast to elimate the error, although I dont know the reason yet.

Old stylesheet (working under 0.4.0 and not working under 0.4.1)
````javascript
  container: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'stretch',
    backgroundColor: '#ffffff',
  },
````

New stylesheet (working under 0.4.0 and 0.4.1)
````javascript
  container: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    backgroundColor: '#ffffff',
  },
````


So it seems the interpretation of alignItems has changed from 0.4.0 to 0.4.1 - I can now fix the layout again for my app, but the root cause would be of interest for me anyway.

**Comment by brentvatne** [comment]
[Maybe this?](https://github.com/facebook/react-native/commit/d293bed5ab66c002beb5331304c8e94f5de41c49#diff-1f8c488dfdf16cdf6fa320584b3098d5L2)

**Comment by PhilippKrone** [comment]
Mhh, I have to deep dive into this change - from a first look this might be what has caused my issue. Thanks for the hint!

**Comment by brentvatne** [comment]
Perhaps not, it looks like that was just some dead code removal (unless it produces some side effects).

**Comment by PhilippKrone** [comment]
Mhh, currently checking:

https://github.com/facebook/react-native/commit/dd6f7743eb626a2b22e1d97130b3fea931f73b55

Anyway, priority is rather low as a solid "work around" / fix can be used.

**Comment by brentvatne** [comment]
@PhilippKrone - fair. Could you post the full code or something that will reproduce it so we can determine if the change was a fix or a regression? :smile:

**Comment by PhilippKrone** [comment]
@brentvatne  Sure thing! :)

1) Create a new RN project and add a static image in XCODE. I called it "Test" and added the following image: http://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/000080_Navy_Blue_Square.svg/2000px-000080_Navy_Blue_Square.svg.png

2) use the following source code:

````javascript
/**
 * Test app
 * https://github.com/facebook/react-native
 */
'use strict';

var React = require('react-native');
var {
  Navigator,
  Text,
  Image,
  View,
  AlertIOS,
  NetInfo,
  TouchableHighlight,
  AppRegistry,
  StyleSheet,
} = React;

var TestProject = React.createClass({
  render: function() {
    return (
      <View style={styles.container}>
       <Image
         style={styles.backdrop}
         source={require('image!Test')}>
         <View style={styles.ClearBackground}>
           <View style={styles.backdropView}>
               <Text style={styles.appNameText}>
                  SMIPE
               </Text>
            </View>
          </View>
        </Image>
     </View>
    );
  }
});

var styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    backgroundColor: '#ffffff',
  },
    backdrop: {
      flex: 1,
      marginTop: 0,
      alignItems: 'stretch',
    },
    backdropView: {
      backgroundColor: 'rgba(0,0,0,0)',
      alignItems: 'stretch',
      width: 250,
    },
    ClearBackground: {
      backgroundColor: 'rgba(0,0,0,0)',
      flex: 1,
      alignItems: 'center',
      marginTop: 130,
    },
    appNameText: {
      textAlign: 'center',
      fontSize: 48,
      fontFamily: 'Gill Sans',
      color: '#ffffff',
    },
});

AppRegistry.registerComponent('TestProject', () => TestProject);
`````

3) Following behaviour:
   RN 0.4.0. for both, "alignItems: 'center'," and "alignItems: 'stretch'" in the container style, it is working
   RN 0.4.1. only for "alignItems: 'center'," it is working, for 'stretch', the text is not visible (I think it is moved somewhere out of the screen as the image has a higher width than the screen?)

**Comment by tadeuzagallo** [comment]
It's actually related to `require`, you can test it by setting `width` and `height` on the image's style.

/cc @amasad

**Comment by amasad** [comment]
Might be a regression while we're working on #1043 cc @frantic

**Comment by PhilippKrone** [comment]
Indeed setting the width and height works. I just figured out a case in which I'm only setting the height of an image (and no width, as I want to have the same aspect ratio as the original image) and this is not working correctly as well. I'm now calculating the width as well by just multiplying the calculated height with the (known) aspect ratio and it's working again.

Thanks a lot for all your support!

**Comment by frantic** [comment]
We started to mix in image width/hight if they are not set on image style. Will probably have to reconsider this - use case when image is sized using flex is valid. @vjeux the layout guru, thoughts?

**Comment by JohnyDays** [comment]
@frantic or when image is sized using the parent's align-items:'stretch' property, that is also valid imo, and changing it would break my current use case.

**Comment by vjeux** [comment]
Erg yeah, I didn't think of this use case. As a workaround I think you can do style={{width: undefined}}

I'm not such a fan of auto injecting the dimensions but it's worth trying out and see how that works

**Comment by bimawa** [comment]
Guys i have similar troubles, after update on 0.4.1 all my root View flow by width
![06 05 15 20 35 08](https://cloud.githubusercontent.com/assets/1393809/7497646/40a0f99c-f435-11e4-82e1-af8b6874803c.png)
![06 05 15 20 35 11](https://cloud.githubusercontent.com/assets/1393809/7497647/40a11968-f435-11e4-9df8-01ec5de26140.png)
