### ISSUE TITLE
KeyboardAvoidingView padding bug

### ISSUE THREAD

**Issue by ivpusic** [facebook/react-native#10517]
### Issue Description

KeyboardVoidingView has wrong padding on android.
### Steps to Reproduce / Code Snippets

Create KeyboardAvoidingView with following view hierarchy

```
-> KeyboardAvoidingView
    -> ScrollView
    -> View (The one with this issue)
```

When keyboard is open last View has wrong padding
#### iOS (Correct)

<img width="441" alt="screen shot 2016-10-23 at 11 02 21 pm" src="https://cloud.githubusercontent.com/assets/450140/19629431/b9af75f2-9975-11e6-9c03-c6ff47d558c7.png">
#### Android (Wrong)

<img width="335" alt="screen shot 2016-10-23 at 11 07 53 pm 1" src="https://cloud.githubusercontent.com/assets/450140/19629428/b1ff94ea-9975-11e6-9861-a8de4add33e5.png">
<img width="443" alt="screen shot 2016-10-23 at 10 59 25 pm" src="https://cloud.githubusercontent.com/assets/450140/19629429/b5d0e6dc-9975-11e6-9045-f19695053fd5.png">
#### Expected Results

Padding should be set correctly
### Additional Information
- React Native version: 0.35.0
- Platform: Android

**Comment by lacker** [comment]
I'm not quite sure what code leads to that bug. Could you provide more specific repro code? A link to rnplay.org is the best because then we can see precisely what code maps to what visual error.

**Comment by magicismight** [comment]
Same issue.
But I cannot reproduce the bug every time on the simulator.
It happens occasionally.

**Comment by ivpusic** [comment]
@magicismight you can try https://github.com/facebook/react-native/pull/10531. After this change I cannot reproduce issue anymore. Can you?

**Comment by magicismight** [comment]
I don't know how to reproduce this, it happened randomly.
Sometimes just reboot the simulator and everything works fine.

**Comment by chapati23** [comment]
Also ran into this issue (react-native 0.38, Android 6.0 on Samsung Galaxy A3).

**Reproduce**
An app with 2 simple screens that have a `<TextInput autoFocus />` and a button that sticks to the bottom. Navigating back and forth causes weird behavior for me on Android because the Keyboard is never dismissed.

**Workaround**
Call `Keyboard.dismiss()` manually before navigating to the next screen (e.g. via a button's `onPress={() => { Keyboard.dismiss() }}`. That solves the issue for me and makes `KeyboardAvoidingView` behave basically like on iOS in my case.

**Comment by andreleon** [comment]
I also ran into this issue (react-native 0.42.0). To fix this I simply added a platform specific `keyboardVerticalOffset` to counter this issue.

```
<KeyboardAvoidingView
    behavior={'padding'}
    keyboardVerticalOffset={
        Platform.select({
            ios: () => 0,
            android: () => 30
        })()
    }>
    ...
</KeyboardAvoidingView>
```

I thought this workaround might help some people who encounter the same issue.

**Comment by dualcyclone** [comment]
I've encountered an issue with this whereby, if you have multiple text fields (eg, a username and password field), the view will jump around when navigating between the fields.

Nothing overly special settings wise, just ```<KeyboardAvoidingView behavior={'padding'} style={...}>```

And on first focusing a field in this arrangement, the first field will jump to the top of the screen initially

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/keyboardavoidingview-padding-bug

**Comment by voidstarfire** [comment]
Issue still exists version 49

**Comment by jjimenezlopez** [comment]
I'm having this same issue in version 0.54.1
