### ISSUE TITLE
ListView scrollTo rendering all rows when animated set to false?

### ISSUE THREAD

**Issue by labithiotis** [facebook/react-native#10525]
I can only confirm it happens in iOS;

RN: v0.35

With the ListView when using the scrollTo method (or contentOffset prop) with animated specifically set as FALSE, the rows in between are rendered and onScroll is called as if scrolling was animating. This is causing an issue with horizontal view that has 100+ "rows" each with their own complex ScrollViews. I would expect the scrollTo to just jump to exact point without rendering all 1-59 rows if I wanted to jump to page/view 60 (using x position).

This also happens with the iOS contentOffset ({x, y}) prop for initial position from ScrollView Component.

Should note that once the view is rendered scrolling via touch works perfectly, you can pan from start to finish, where if I offset in more than 30+ pages it crashes the app.

```
render() {
  const { items, item: { id } } = this.props;
  const ds = new ListView.DataSource({ rowHasChanged: (r1, r2) => r1.id !== r2.id });
  const dataSource = ds.cloneWithRows(items);
  const index = getIndexById(items, id); // returns an index to skip to, i.e. 10

  return (
    <ListView
      ref={(ref) => this.listView = ref}
      onLayout={({ nativeEvent: { layout: { width }}}) => {
        this.listView.scrollTo({ x: Math.floor(width * index), animated: false });
      }}
      pageSize={1}
      bounces={true}
      horizontal={true}
      initialListSize={5}
      pagingEnabled={true}
      dataSource={dataSource}
      removeClippedSubviews={true}
      showsHorizontalScrollIndicator={true}
      onScroll={() => {
        console.log('scrolling')
      }}
      renderRow={(ship) => {
        console.log('render row');
        const { width } = Dimensions.get('window');
         return (
          <View style={{ flex: 1, overflow: 'hidden', width }}>
            {ship.name}
          </View>
        );  
      })}
    />
  );
}
```

**Comment by lacker** [comment]
Would you mind creating a reproduction of this bug on rnplay.org? It isn't totally clear to me from this example code how the parts like ships, ship, and the id relate to each other.

**Comment by labithiotis** [comment]
@lacker I've made a rnplay example with more generic names: https://rnplay.org/apps/XDg1gg

**Comment by rbnquintero** [comment]
any news? i'm also having this issue

**Comment by labithiotis** [comment]
I'm using this module until it's fixed: https://www.npmjs.com/package/react-native-viewpager

**Comment by rodrigopivi** [comment]
I'm also experiencing this issue on android listview, using a `listView.scrollToEnd({ animated: false });` works fine on iOS, but fails at android.

Btw seems like nobody is assigned to this issue.

**Comment by hramos** [comment]
Closing as ListView is deprecated in 0.43. Use FlatList.
