### ISSUE TITLE
Android Alert title message cuts off after two lines

### ISSUE THREAD

**Issue by keertimaan** [facebook/react-native#10527]
### Issue Description

Android Alert title message cuts off after two lines
### Steps to Reproduce / Code Snippets

Add an Alert title which has more than 2 lines of content.
#### Expected Results

Alert title should not cut off and show ellipses. It should show the full content like on iOS.
### Additional Information
- React Native version: 0.32.0
- Platform(s) (iOS, Android, or both?): Android
- Operating System (macOS, Linux, or Windows?): macOS

**Comment by lacker** [comment]
I don't think you should be trying to stick arbitrarily long things into the title of an Alert. Why not put the longer message into the body of the alert?

**Comment by keertimaan** [comment]
Thanks Kevin for your quick response. Sure we can have workarounds to solve the issue, but the reason why i brought it up is because Native Android alert supports multi-line whereas RN is limiting it to 2 lines. So just trying to understand if this is done purposefully on RN or a bug.

**Comment by hramos** [comment]
Can you reproduce the issue on RNPlay?

**Comment by keertimaan** [comment]
@hramos - https://rnplay.org/apps/gex3lg

**Comment by hramos** [comment]
Thanks, that is very helpful. For reference, this is what the alert looks like on RN Android:

<img width="285" alt="screen shot 2016-10-26 at 4 18 00 pm" src="https://cloud.githubusercontent.com/assets/165856/19748619/d6d97a50-9b97-11e6-80d8-7c9def08f878.png">

@keertimaan you're saying on native Android, this alert would display the full title over more than two lines?

**Comment by keertimaan** [comment]
@hramos Thank you for updating the screenshot. I should have done that as a first step.

Native Android default behavior limits the title to 2 lines but we can set the TextView singleLine property to false to show the full content.

**Comment by satya164** [comment]
We just use the native Android Alert dialog's title property. We're not setting a custom textview, so we can't change the number of lines.

You should use `Modal` instead if you want more control over how your content gets displayed.

Though from a UX standpoint, more than 2 lines for a title seems really weird.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/android-alert-title-message-cuts-off-after-two-lines
