### ISSUE TITLE
<Text numberOfLines={1} ellipsizeMode="middle"> crashes on Android

### ISSUE THREAD

**Issue by ghengeveld** [facebook/react-native#10520]
### Issue Description

When using `<Text numberOfLines={1} ellipsizeMode="middle">`, this will [throw an error](https://cloud.githubusercontent.com/assets/321738/19646583/5cfcf35e-99fa-11e6-85ea-d94ef77d96fe.png) on Android in some situations.

I've tracked this to an [outstanding (but marked obsolete) issue](https://code.google.com/p/android/issues/detail?id=33868) in Android itself. People are suggesting to use singleLine=true rather than lines=1.

I think this can be fixed by changing `setNumberOfLines` in [ReactTextView.java](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/text/ReactTextView.java) to use setSingleLine() rather than setMaxLines(mNumberOfLines):

``` java
public void setNumberOfLines(int numberOfLines) {
  mNumberOfLines = numberOfLines == 0 ? ViewDefaults.NUMBER_OF_LINES : numberOfLines;
  if (mNumberOfLines == 1) {
    setSingleLine();
  } else {
    setMaxLines(mNumberOfLines);
  }
}
```

Unfortunately I'm [unable to compile my forked version of React Native](http://stackoverflow.com/questions/40217678/compiling-react-native-project-with-local-fork-ndk-project-path) so I can't test it. I'd love to contribute a fix though.
### Steps to Reproduce / Code Snippets

Create the following and run it on Android:

``` jsx
<View style={{width: 150}}>
  <Text numberOfLines={1} ellipsizeMode="middle">12345 12 12345678901234</Text>
</View>
```

This bug **only happens in very specific situations**. Both the size of the container and the length and proportion of word sizes matters. I haven't tested on different devices, but I wouldn't be surprised to find that screen resolution matters. I'm running this on a 5.0 inch 1920*1080 phone (~442 ppi) in portrait mode.
#### Expected Results

See https://cloud.githubusercontent.com/assets/321738/19646583/5cfcf35e-99fa-11e6-85ea-d94ef77d96fe.png
### Additional Information
- React Native version: 0.35
- Platform(s) (iOS, Android, or both?): Android 5.0
- Operating System (macOS, Linux, or Windows?): macOS

**Comment by filonovaa** [comment]
Same for numberOfLines={1} ellipsizeMode='head', appear in Android 4.1.1 720x1280

**Comment by lacker** [comment]
Thanks for the really detailed error report! So hmm it seems like Android should fix this? Besides that my main concern with your proposed fix is that the `singleLine` and `lines` behavior do not seem precisely the same because of the stuff about focus.

https://developer.android.com/reference/android/widget/TextView.html#attr_android:lines

https://developer.android.com/reference/android/widget/TextView.html#attr_android:singleLine

Maybe you could just not use `numberOfLines={1} ellipsizeMode="middle"` together? Or maybe `singleLine` should get exposed separately?

**Comment by ghengeveld** [comment]
I think exposing singleLine as a prop on Text would be a good solution, in fact better than what I proposed because it's less 'magic'.

**Comment by lacker** [comment]
OK - it would be great if you do figure out how to compile RN and then this seems like it would be a nice pull request!

**Comment by kkgelu** [comment]
RN 0.41:  I am having crashes with ellipsizeMode={'clip'}, as soon as I change to 'middle', 'tail' or 'head', the crash stops happening.
```
        <View style={{marginTop: 9,
                      height: 16,
                      width: 16,
                      borderRadius: 8,
                      justifyContent:'center',
                      backgroundColor:  badgeBackgroundColor,
                    }}>
          <Text numberOfLines={1} ellipsizeMode={'clip'}
              style={{
                color: textColor,
                fontSize: 12,
                alignSelf:'center',
                backgroundColor:'transparent'}}>
             {count}
          </Text>
       </View>
```

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/text-numberoflines1-ellipsizemodemiddle-crashes-on-android
