### ISSUE TITLE
Best Practices question: Animating a view

### ISSUE THREAD

**Issue by jaygarcia** [facebook/react-native#1052]
I have a view that I need to animate upwards. I'm trying to emulate the "Tracker" style of music "playing".

What are the suggestions for moving the view up? My only thought is to Set a "top" style via setState, but that feels dirty.  The movements need to be precise (not fluid).

![finally](https://cloud.githubusercontent.com/assets/180031/7377209/eca3df22-edb2-11e4-93ce-475d747e4530.gif)

Here's where I currently am with the project.
https://www.youtube.com/watch?v=kciU2dxFnYA

**Comment by sahrens** [comment]
using setState shouldn't be a big deal, and can work fine if you use componentShouldUpdate correctly to prevent excessive React re-rendering and reconciliation (and if the app is simple enough, you might not have to do anything at all to get adequate perf).

If it's still too slow, then one option is to set the state directly with `this.state.top = top;` then update the component manually with `refs.theView.setNativeProps({style: {top: this.state.top}});`.

**Comment by sahrens** [comment]
Another option is to use a transformMatrix.

**Comment by sahrens** [comment]
Hopefully a simple setState on top style works for you though ;)

**Comment by leecade** [comment]
:+1:

**Comment by jaygarcia** [comment]
Awwwwwwww yeah!!!


Runs sofaking well on iPhone6.

![aww yeah](http://i.imgur.com/SIBlL41.gif)
