### ISSUE TITLE
[Android] `opacity` should not be inherited.

### ISSUE THREAD

**Issue by magicismight** [facebook/react-native#10530]
### Description

On android the `opacity` will be inherited to the View's children, opacity should not be inherited.
iOS works fine.

### Reproduction

The children inside the parent view are not transparent, but if the parent set `{opacity: 0.5}`,the opacity will be inherited to its children.

```
<View
  style={{opacity: 0.5, height: 40, width: 40}}
>
  <View style={{
    backgroundColor: 'blue', height: 20, width: 20, position: 'absolute'
  }} />
  <View style={{
    backgroundColor: 'red', height: 40, width: 40, position: 'absolute'
  }} />
</View>
```

[RNPlay](https://rnplay.org/apps/n0BdxA)

Android:
![image](https://cloud.githubusercontent.com/assets/7693239/19670270/81838898-9a98-11e6-951d-6f32a2892e11.png)

iOS:
![image](https://cloud.githubusercontent.com/assets/7693239/19670275/8e50a362-9a98-11e6-88d2-2b8563fa7545.png)

### Additional Information

* React Native version: 0.35.0
* Platform: Android
* Operating System: MacOS

**Comment by lacker** [comment]
It does seem like iOS and Android should act the same way. Sorry if this is a dumb question, but how do you know the correct behavior is the iOS behavior rather than the Android behavior?

**Comment by magicismight** [comment]
The style in react-native should act like css in the web, and in most cases the transparency is not a property which should be inherited.

**Comment by janicduplessis** [comment]
Do setting `needsOffscreenAlphaCompositing` fixes this?

**Comment by magicismight** [comment]
@janicduplessis 
Thanks man. It works!
I'm closing this now.
