### ISSUE TITLE
React native flexbox not adapting correctly

### ISSUE THREAD

**Issue by federicobadini** [facebook/react-native#10539]
### Description

I’m developing a react native application with a three-column keyboard. I’ve based the keyboard on a vertical flex layout. Each row in the keyboard is configured with an horizontal flex layout. Buttons and the horizontal and vertical separators are simple views. 

On particular conditions it seems that the flex layout cannot correctly size views. 
For instance see the pictures below for iPhone 6 screen size: the three buttons are all equally sized to 123.5 width and a 0.5 blank space is clearly visible between the second and the third column.

<img height="400" alt="simulator screen shot 25 oct 2016 00 28 43" src="https://cloud.githubusercontent.com/assets/7805759/19681381/7796f46c-9aa9-11e6-9886-a07fdd285c57.png">

<img width="500" alt="screen shot 2016-10-25 at 11 23 05" src="https://cloud.githubusercontent.com/assets/7805759/19681457/c4b4cef4-9aa9-11e6-8087-2e9522740d45.png">

On iPhone 5 instead the gap opens between the second and the third row.

<img height="400" alt="simulator screen shot 25 oct 2016 11 26 22" src="https://cloud.githubusercontent.com/assets/7805759/19681398/848094f8-9aa9-11e6-8aad-f3157cc1d0a8.png">

I’ve found a comment in react-native RCTShadowView, stating that the native rounding should avoid this kind of issue (see lines 95 to 122 of https://github.com/facebook/react-native/blob/fe5c0d2d0696b4fc5cdd65f1f2198c4f4363e543/React/Views/RCTShadowView.m). 

Do you guys have any hypothesis on why does this happen?
### Reproduction

I’ve put some sample code here: https://rnplay.org/apps/Vl7nVg
In this example however the problem does NOT seem to appear but it uses react v0.31.

Trying to run the sample locally with v0.35 causes the problem.
### Additional Information
- React Native version: 0.35
- Platform: iOS
- Operating System: MacOS

**Comment by lacker** [comment]
Yeah this sort of bug isn't supposed to happen. That's pretty frustrating that it doesn't repro on rnplay. Are you sure it's exactly the same code between rnplay and your local bug repro?

If so, I guess the question is, is this a problem with the difference between your environment and the rnplay environment, or a problem with 0.31 vs 0.35. If you use React Native 0.31 locally do you still see this problem?

**Comment by federicobadini** [comment]
The code is almost the same between rnplay and locally. The unique difference is that in rnplay the app is registered through registerComponent from 'react-native-playground'.

To answer your question, I've set up a sample project on react@0.31. 
I had to solve a couple of issues preventing build, but I've managed to make it run (even though only launching from xCode). Here is the link for you to try:
https://github.com/federicobadini/flexboxBug-reactNative-0.31
 
However the problem is still there even in v.0.31

**Comment by lacker** [comment]
My suspicion is that there is a bug in the rounding logic. It's strange that it doesn't reproduce in rnplay, though. It looks like this is affecting a number of people from the thumbsup responses - does anyone else have a way to reproduce this consistently on rnplay?

**Comment by federicobadini** [comment]
Any news?

**Comment by javiercr** [comment]
I'm having the same problem when trying to build a calendar using flexbox with 7 cells per per row (one for each day of the week). Depending on the iOS device I test the borders appear in a different place:

![image](https://cloud.githubusercontent.com/assets/855995/21019697/b9cd0fb6-bd71-11e6-86b1-056695693ade.png)

![image](https://cloud.githubusercontent.com/assets/855995/21019730/dc8cf656-bd71-11e6-978f-533c43fb4fb4.png)

Using some paddingHorizontal I can make the borders disappear for some devices but not for all of them.

The only solution I can think of until the bug gets fixed is to use the `onLayout` callback, but that's gonna require another render cycle.

**Comment by javiercr** [comment]
In case it helps, it seems this other issue shows the same problem #5711

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.

**Comment by seanyusa** [comment]
This issue is still present. It happens both using flex and manually calculating styles.
