### ISSUE TITLE
npm update broke something relating to react-tools

### ISSUE THREAD

**Issue by jbhatab** [facebook/react-native#1053]
I just ran npm update react-native and it broke my project. Got this error,

Cannot find package main file for package: /Users/blaine/dev/native/evueIOS/node_modules/react-native/node_modules/react-tools/src

It could be something just related to me but thought I'd post it up.

**Comment by jbhatab** [comment]
I found out that it was my requiring another component in my app,

```
'use strict';

var React = require('react-native');

var {
  AppRegistry,
  StyleSheet,
  NavigatorIOS,
  Text,
  View,
} = React;

var Dashboard = require('./app/components/dashboard');

var evueIOS = React.createClass({
  render: function() {
    return (
      <NavigatorIOS
        style={styles.container}
        tintColor='#FF6600'
        initialRoute={{
          title: 'Dashboard',
          component: Dashboard,
        }}/>
    );
  }
});

var styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F6F6EF',
  },
});

AppRegistry.registerComponent('evueIOS', () => evueIOS);

module.exports = evueIOS;
```

It's the var Dashboard = require('./app/components/dashboard'); line that breaks it.

**Comment by jbhatab** [comment]
Ok so I figured out it had to do with the dashboard file itself. Only thing I could say is better error reporting. It told me I had an issue with some random dependency graph thing but it was really an error with a require in the dashboard file. You can close this if you guys know you need to improve that stuff.

**Comment by brentvatne** [comment]
:+1: thanks for the follow up, perhaps the error was with something inside of the dashboard component that lead to a dependency graph problem?

**Comment by jbhatab** [comment]
It was super deep in the chain. It was in the dashboard which called another component which called another which called another which had a bad piece of code. 

Definitely could use improved debugging for that in the long run. If this was a huge app that woulda been crazy hard to find.

and more specifically it was related to a non react native element. I was testing out a div. That may be a weird scenario but I bet other weird things could trigger that same type of error. 

Thanks for the response :)

**Comment by brentvatne** [comment]
Interesting, it could be worth opening an issue if you want to re-create the problem in public repo so we can consider what might be a more descriptive/useful error message :smile:

**Comment by jbhatab** [comment]
I may get to that at some point.
