### ISSUE TITLE
Android TV Support?

### ISSUE THREAD

**Issue by 9point6** [facebook/react-native#10544]
Are there any plans to add Android TV support?

**Comment by mkonicek** [comment]
Check out https://github.com/facebook/react-native/issues?q=tvos+is%3Aclosed

**Comment by mkonicek** [comment]
@facebook-github-bot stack-overflow

**Comment by lacker** [comment]
I am not aware of anyone who has Android TV plans. I had not even heard of Android TV before now. There is a bunch of Apple TV work in progress, though. If you're interested in getting more visibility into the Android-TV-in-React-Native cause, I suggest posting on Product Pains: https://productpains.com/product/react-native

**Comment by 9point6** [comment]
@mkonicek tvOS is Apple's TV operating system, Android TV is a completely different platform

**Comment by mkonicek** [comment]
@9point6 Yup, sorry I read the question too quickly! :)

**Comment by afilp** [comment]
@FezVrasta From our experience at www.smaf.tv there are various issues that need to be supported differently, on a cross-device setting. To name one, there is the need for mapping the remote keys to actions (like "RIGHT", "LEFT", "BACK", "GREEN", etc.), so that events can be captured and callbacks act on them. These need to be consistent along all Android TV setups (and remotes).

**Comment by FezVrasta** [comment]
I understand, but I wonder why shouldn't it compile at least? Someone could write a layer to make the directional keys work then.

**Comment by smhatre59** [comment]
React native components are easily rendered on Android TV without any necessary modifications and simple button elements go in and out of focus by clicking directional arrows from TV remote. 
Only issue is to handle click from directional pad to onPress event of currently focused Touchable elements. We are currently trying to map key button events from `[react-native-events](https://www.npmjs.com/package/react-native-keyevent)` to onPress handler of Touchable elements as the module provides key code 23 for click of center key on android TV remote. You can give it a try if you want to and I will post updates on this thread if any progress happens from my team's side

**Comment by tmm1** [comment]
@smhatre59 Did you have any luck with this?

**Comment by athornz** [comment]
Would love Android TV support too.

**Comment by 9point6** [comment]
Since I forgot to post the link before: https://react-native.canny.io/feature-requests/p/android-tv-support

**Comment by smhatre59** [comment]
No I am working on some other projects now. Will get back to this one when I get time
