### ISSUE TITLE
scheduleLocalNotification always triggered immediately

### ISSUE THREAD

**Issue by shishircc** [facebook/react-native#10540]
### Description

I used following code
```
var notification = {"fireDate":new Date().getTime()+60000, "alertBody":"Hello", userInfo:"Testing ONly",applicationIconBadgeNumber:10};
        PushNotificationIOS.checkPermissions((p)=>{
            console.log(JSON.stringify(p));
            PushNotificationIOS.scheduleLocalNotification(notification);
        });

```
and 

```
PushNotificationIOS.addEventListener('localNotification', (notification)=>{
            Alert.alert("Local notification","Message recived"+notification.getData().alertBody);
        });

```

The local notification always fires immediately instead of schedule. The strange thing is that the local notification works ok on new project but as soon as I include everything within application, the local notification stops working. 
### Reproduction

[FILL THIS OUT: Try to reproduce your bug on rnplay.org and provide a link. If you can't reproduce the bug on rnplay.org, provide a sample project.]

### Additional Information

* React Native version: 32
* Platform: iOS
* Operating System: Mac OSX Sierra

**Comment by lacker** [comment]
> The strange thing is that the local notification works ok on new project but as soon as I include everything within application, the local notification stops working. 

To me that seems like the next step is to get a reproduction. Basically at what point does this local notification stop working. If you can get it to work on a blank project, there must be one piece of functionality in your app that, when you add it, the local notification stops working. What is that one piece of functionality? Can you find it by e.g. removing half of your app logic, seeing if it still works, then binary searching to find the source of the bug?

**Comment by shishircc** [comment]
I found that it breaks if I add react-native-fcm, once I add firebase messaging pods.

**Comment by lacker** [comment]
This sounds like a problem specific to react-native-fcm, then. I suggest filing an issue with them. It's definitely possible for a library to bork the React Native environment so perhaps that is just what's happening here. Good luck!
