### ISSUE TITLE
Should provide a global 'uncaughtException' event like node.js

### ISSUE THREAD

**Issue by narychen** [facebook/react-native#10549]
In development mode  react-native will display a redbox when any uncaught exception error threw out, but in production nothing will happen. 
This will lead to a bad user experience when something bad in your app happens but you give no clues to user. 
And react-native often stops responding when an exception comes up from the native side.

So we should add a global 'uncaughtException' event to react-native  just as in node.js to give a final shot on the errors and bugs we didn't find in our own test before it released to our users.

**Comment by lacker** [comment]
That does seem like a pretty good idea. So we are using Product Pains for feature requests right now, and I encourage you to file this there: https://productpains.com/product/react-native We are just using issues for bugs. But if you want to add this to React Native then I think a pull request for it would be great! For now, I'm closing this issue though to keep the issues focused on bugs. Thanks!
