### ISSUE TITLE
Print: Entry, ":CFBundleIdentifier", Does Not Exist

### ISSUE THREAD

**Issue by shicang1990** [facebook/react-native#10545]
** BUILD SUCCEEDED **

Installing build/Build/Products/Debug-iphonesimulator/*.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by shicang1990** [comment]
I've tried:

* killing processes on port 8081
* changing the port
* running it with sudo
* updating react-native (I'm on the latest version)

but not work.

**Comment by shicang1990** [comment]
Finally, I've tried:
Just doubleclick on the RCTWebSocket project in your navigator and remove the flags like those under build settings > custom compiler flags

![](https://cloud.githubusercontent.com/assets/528287/17270862/0f397686-566d-11e6-8db5-76a17cbd620b.png)

**Comment by lacker** [comment]
How can I reproduce this error - are you just setting up React Native for the first time and it doesn't work?

**Comment by shicang1990** [comment]
I clone React Native project as [https://github.com/crazycodeboy/GitHubPopular](https://github.com/crazycodeboy/GitHubPopular) by steps:
* cd ...
* npm install
* react-native run-ios
Get these error.

> OS X 10.11.6 (15G1004)
> node: v6.9.1
> npm: v3.10.8
> react-native-cli: 1.0.0
> react-native: n/a - not inside a React Native project directory

**Comment by lacker** [comment]
Can you get a new blank project to work? Ie, is it a problem specific to this project, or is your whole React Native install borked?

**Comment by shicang1990** [comment]
@lacker 
I think so, it is a problem specific to this project. New project on react-native 0.36.0 version can work.
Thanks.

**Comment by ltwaia** [comment]
There are two files needed to be modified about port 8081:
1. react-native/local-cli/server/server.js - default 
2.react-native/React/React.xcodeproj/project.pbxproj - replace all 8081
above two, it's ok;

**Comment by hramos** [comment]
Duplicate of #14423
