### ISSUE TITLE
Image crash

### ISSUE THREAD

**Issue by xsdlr** [facebook/react-native#10553]
### Description

[error][tid:com.facebook.react.ImageLoaderURLRequestQueue][RCTNetworkTask.m:104] Missing request token for request: <NSMutableURLRequest: 0x600000008aa0> { URL: picture url  }

The url of picture have been checked and is working fine.
![Image](https://i.stack.imgur.com/lmEfU.png)
### Reproduction

Put some Network Images on the Page and reloading the application, you will see this error. But about roughly 3% of the time when loading or reloading the application, we are getting a crash. 
### Additional Information
- React Native version: 0.35
- Platform: iOS
- Operating System: MacOS

**Comment by lacker** [comment]
Hmm it seems like you have censored out a key part for reproducing this bug. Can you repro this using rnplay.org, and using an image that you feel okay sharing what it is?

**Comment by gre** [comment]
I also experience this when developing the app. I'm not sure if it's somehow related to https://github.com/facebook/react-native/issues/10433

**Comment by knyga** [comment]
![image](https://cloud.githubusercontent.com/assets/3603431/20466174/7947338a-af76-11e6-99b3-d74c00234a84.png)

Same on my side. Resource exists if I check the path.

**Comment by keeleycarrigan** [comment]
I'm experiencing pretty much the exact same thing today, intermittently.

**Comment by chrisharrison** [comment]
Also getting this, and it's causing some images not to display. The images were working fine before and the paths have not changed.

**Comment by perrosnk** [comment]
I am also getting this error

**Comment by chrisharrison** [comment]
For me, it happened when other remote image URLs on the same screen were
not responding. Once my image server was responding again, this exception
went away.

**Comment by perrosnk** [comment]
I just discovered that there was a similar issue with my server as well. Thank you @chrisharrison

**Comment by jaredtibs** [comment]
I am experiencing this as well. Anyone aware of a fix or workaround for this issue?

**Comment by Kowaio** [comment]
Hello guys,

upping this issue as I see it also in my app with an asset picture. I'm using RN 0.39.
If anybody found a workaround it'd be great!
Thanks!

**Comment by digitaldavenyc** [comment]
+1 for this issue happened after upgrading to RN 0.44

**Comment by timrc** [comment]
+1 Same issue happening here after RN 0.44. I'm using https://lorempixel.com images.

**Comment by tomazahlin** [comment]
Same here. We updated some time ago to RN 0.41. But on Friday it worked, today on Monday we get this error all the time. What is this???

**Comment by iwater** [comment]
same on RN 0.43.4, random happen

**Comment by chenyanji** [comment]
same on RN 0.44, random happen

**Comment by sunnylqm** [comment]
ping @ide  @javache

**Comment by shireen** [comment]
+1

**Comment by javache** [comment]
Commenting +1 is not useful, those comments will be deleted.

Please provide a sample app that reproduces the issue.

**Comment by jackqqxu** [comment]
same problem on RN0.38

**Comment by jinwei233** [comment]
same on RN 0.44, random happen

**Comment by LittleLiByte** [comment]
+1

**Comment by chrisharrison** [comment]
A lot of people are +1'ing this issue but how many are coming back to say how they resolved it? As I said earlier, I do not believe this is an RN bug per se, but happens when your app is making errnoneous network errors or a server you are calling is not responding correctly.

**Comment by jslz** [comment]
hello... I am getting it today for our splash image that has otherwise worked 100%. I am trying to get our foregrounding - backgrounding ux to work well, and am seeing this now. This is a dev build hitting the local packager for a resource that would be baked-in in production. What is extra weird is that it first shows the splash page on resume (because that is baked into the xcode app maybe?) and then says the error about the splash screen. weird. The file really does exist, I can ls it ok. RN 0.45.1 on Mac OS 10.12.5 with node 6.11.1.

<img width="363" alt="missingrequesttoken" src="https://user-images.githubusercontent.com/27701565/28549825-a940f756-7091-11e7-8540-8a8b60431b54.png">

**Comment by uiue** [comment]
same on RN 0.46, random happen

**Comment by txwh** [comment]
nothting

**Comment by uiue** [comment]
random happen.reload again

**Comment by vitorL** [comment]
Maybe you have to clear the cache, I was having the same issue.
Not sure if it is related to cache or AssyncStorage but i've reset both and the problem stoped.
Good Luck all

**Comment by spicyboiledfish** [comment]
Same on RN 0.39.2, random happen when continues refresh.

**Comment by valetarton** [comment]
This issue is occurring for me as well.
Happened after I did a build clean on iOS.

**Comment by wmonecke** [comment]
Started happening to me todays as soon as I started working on a component that has to fetch images dynamically (async). I had static images in my app before and I had never seen this error. **This is definitely coming from AJAX requests made by my app.**
As other users have noted this is error is not happening all the time but is on and off... When I do a fresh reload of the app, everything works fine. However, as soon as a component that has fetched images via AJAX **ALL** images have issues rendering, event static ones.

**Comment by Obooman** [comment]
Crash into this with detox.

**Comment by fredbt** [comment]
Also having this now.

**Comment by wmonecke** [comment]
Has anyone had any progress with this error?

**Comment by ray17n** [comment]
+1

**Comment by neetocode** [comment]
+1

**Comment by neetocode** [comment]
+1

**Comment by oluomoniyi** [comment]
+100 to this!

**Comment by ErkanSensei** [comment]
I am seeing this error as well now, RN 0.50

**Comment by fredbt** [comment]
Still happening here.

**Comment by heuism** [comment]
hi guys,

Is there anyone running into this one? This is really random. Sometimes it happens and fail the test. Sometimes it run normally. +9000

**Comment by HananeAlSamrout** [comment]
my issue was that i was using react-native-swiper and i was generating images dynamically inside it, i just generated these images outside the swiper in a variable, then gave the variable to the swiper as a children and the problem was gone.

**Comment by francisbrito** [comment]
I ran into this one while using RN 0.52.

It seems to happen consistently if an `Image` component has `flex: 1` set in its style.

**Comment by GuillaumeMunsch** [comment]
I still get the same error on RN 0.53

**Comment by Gentlee** [comment]
Issue appeared for me after i updated from `0.51.0` to `0.53.3`.

**Comment by DrJid** [comment]
Getting the same error now on 0.52...

**Comment by 1k2k** [comment]
Wow, anyone fixed this?

**Comment by AishwaryaSurana** [comment]
Facing the same issue 😞

**Comment by beormalte** [comment]
For me the issue only when I rapidly refresh the simulator. 
This is probably caused be the previous refresh not having a chance to complete the load, and then being aborted. 
So it's not a biggy in my case

**Comment by gadfil** [comment]
Facing the same issue  when very slow internet 
![image](https://user-images.githubusercontent.com/3535356/37475479-df95b9c2-2883-11e8-94a3-9bea72393c46.png)

**Comment by rendomnet** [comment]
Same error here "react-native": "0.54.2"
