### ISSUE TITLE
[Packager] can't resolve sha.js dependency (or any other with "." in name)

### ISSUE THREAD

**Issue by mvayngrib** [facebook/react-native#1055]
sha.js, bn.js, dns.js all result in errors like:

Requiring module "testdot/index.ios" with unresolved dependencies: testdot/index.ios is waiting for sha.js/index
sha.js/index is not defined

**Comment by christopherdro** [comment]
@mvayngrib did you ever get this resolved?

**Comment by mvayngrib** [comment]
yea, sadly I didn't have time to dig in too deep so i hacked https://github.com/facebook/react-native/blob/master/packager/react-packager/src/DependencyResolver/haste/DependencyGraph/index.js#L121

from
```js
var id = sansExtJs(name);
```

to

```js
var id = name;
```

and everything worked

**Comment by christopherdro** [comment]
@mvayngrib  How were you originally defining the requirements? Would you  be able to provide an example project where this error occurs. That would help out a lot.

**Comment by mvayngrib** [comment]
here's a sample project: https://github.com/mvayngrib/breakdotdep

all i did was:

```
react-native init breakdotdep
cd breakdotdep
npm install --save hash.js
open breakdotdep.xcodeproj
```

then hit Run and open Chrome Dev Tools and see:

```
index.ios.bundle:931 Error: 
 stack: Error: Requiring module "breakdotdep/index.ios" with unresolved dependencies: breakdotdep/index.ios is waiting for hash.js/lib/hash
hash.js/lib/hash is not defined
    at Error (native)
    at new ModuleError (http://localhost:8081/index.ios.bundle:107:18)
    at require (http://localhost:8081/index.ios.bundle:214:13)
    at Object.ErrorUtils.applyWithGuard (http://localhost:8081/index.ios.bundle:885:20)
    at require (http://localhost:8081/index.ios.bundle:196:25)
    at http://localhost:8081/index.ios.bundle:41408:2
 line: undefined
 message: Requiring module "breakdotdep/index.ios" with unresolved dependencies: breakdotdep/index.ios is waiting for hash.js/lib/hash
hash.js/lib/hash is not defined ModuleError
```

**Comment by amasad** [comment]
Fixed this internally, should go out in the next sync. Sorry for the delay.

**Comment by mvayngrib** [comment]
awesome!

**Comment by venocl** [comment]
Hi, I have the same problem with ddp.js even after applying the fix

**Comment by amasad** [comment]
@venocl This for sure works in the latest version 0.7.0-rc.2 I just installed `ddp.js` and double checked.
