### ISSUE TITLE
RCTImageLoader still crashing for long lists in 0.36.0

### ISSUE THREAD

**Issue by janmonschke** [facebook/react-native#10557]
### Description

As it was reported before in various other issues, when scrolling long lists with images the app would crash. Easier to reproduce with slower network connection.

### Reproduction

Create a list with a lot of images, change network speed to sth. like Edge (e.g. using [Network Link Conditioner](http://nshipster.com/network-link-conditioner/)). Scroll that list and it will eventually crash.

### Additional Information

* React Native version: 0.36.0
* Platform: iOS
* Operating System: MacOS

### Screenshots from XCode debugger

<img width="757" alt="screen shot 2016-10-26 at 12 47 12" src="https://cloud.githubusercontent.com/assets/68591/19723357/36a9cfa6-9b7b-11e6-8be1-d14b7b7e361d.png">

<img width="750" alt="screen shot 2016-10-26 at 12 47 27" src="https://cloud.githubusercontent.com/assets/68591/19723359/36adf7ac-9b7b-11e6-852b-b2bb92eca90d.png">

<img width="758" alt="screen shot 2016-10-26 at 12 47 48" src="https://cloud.githubusercontent.com/assets/68591/19723358/36ab44e4-9b7b-11e6-8b3d-26ac9a8efe44.png">

**Comment by ide** [comment]
Thanks for reporting this. It's being tracked in #10433; closing this issue just to dedupe them.
