### ISSUE TITLE
debuggerWorker.js contains code incompatible with node 5

### ISSUE THREAD

**Issue by ulitink** [facebook/react-native#10564]
### Description

It's impossible to use custom debugger running on node 5 because [debuggerWorker.js](https://github.com/facebook/react-native/commit/bbd1e455f391aef6dc8dfbd934377bf90016e35d#diff-a820b570f3cb0243dbc0bdb209ab75db) contains 'let' now. Changing 'let' to 'var' fixes the issue. 

Related issue: [WEB-23912](https://youtrack.jetbrains.com/issue/WEB-23912)

### Additional Information

* React Native version: 0.36
* Platform: both
* Operating System: all

**Comment by janicduplessis** [comment]
Fixed in a16d72842dc80cec3bb274080c57b4d98de26ddf
