### ISSUE TITLE
StatusBar.currentHeight returns undefined

### ISSUE THREAD

**Issue by stereodenis** [facebook/react-native#10561]
### Description

StatusBar.currentHeight returns undefined instead of real height
### Reproduction

console.log(StatusBar.currentHeight)
### Additional Information
- React Native version: "^0.35.0",
- Platform: Both
- Operating System: MacOS

**Comment by nicastelo** [comment]
Works fine on version 0.33

**Comment by rogchap** [comment]
Looks like the API only supports android: https://github.com/facebook/react-native/blob/master/Libraries/Components/StatusBar/StatusBar.js#L169

There is also more discussing here: #6195

TL;DR On iOS the StatusBar height is dynamic, so can't be a static constant

**Comment by brentvatne** [comment]
It looks like the documentation also shows this as only being available on Android:

<img width="568" alt="screen shot 2016-10-30 at 4 47 21 pm" src="https://cloud.githubusercontent.com/assets/90494/19837747/925ff3b4-9ec0-11e6-96b9-1aadb35d02b5.png">

But perhaps we should be more explicit about it and add it to a list of `StatusBar` constants in the docs, and make it obvious that it only works on Android. PR welcome for this!
