### ISSUE TITLE
Nested <Text> platform differences regarding background color

### ISSUE THREAD

**Issue by Benmidi** [facebook/react-native#10562]
### Description

Background color on iOS is filled in from edge to edge on all lines except the last line. On Android, it snuggly wraps the characters on all lines. _I would lobby to keep the Android implementation for selfish reasons._

<img width="849" alt="screen shot 2016-10-26 at 11 27 04 am" src="https://cloud.githubusercontent.com/assets/813586/19733252/70aa4c08-9b71-11e6-9dee-a3fba93009a1.png">
### Reproduction
1. Write this JSX

``` javascript
<Text>
  <Text style={styles.highlight}>Hello there, blah blah blah blah blah blah</Text>
</Text>
```
1. Style it

``` javascript
const styles = StyleSheet.create({
  highlight: {
    backgroundColor: 'yellow',
  },
});
```

Look at both Android and iOS:
https://rnplay.org/apps/M3MICA

<img width="316" alt="screen shot 2016-10-26 at 11 32 41 am" src="https://cloud.githubusercontent.com/assets/813586/19733283/8e742f38-9b71-11e6-82af-4ab5858e990a.png">
<img width="303" alt="screen shot 2016-10-26 at 11 33 25 am" src="https://cloud.githubusercontent.com/assets/813586/19733289/90b6db88-9b71-11e6-9aa2-9b8c9e58f8a5.png">
### Additional Information
- React Native version: 0.36
- Platform: Both
- Operating System: MacOS 10.11

**Comment by lacker** [comment]
Hmm, is this just proxying the underlying behavior of highlighted text on the two different platforms? We do want this to "feel native" on both of them.

**Comment by Benmidi** [comment]
That would be true if I were using a text highlight property. This is the backgroundColor CSS property. Shouldn't styling be consistent between elements and platforms? Like with layout, font*, border*

**Comment by lacker** [comment]
Well, the CSS is also just proxying the underlying platforms using css-layout. I think the right behavior would be whatever happens when you highlight in the native code, so that it feels native.

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.

**Comment by fauno** [comment]
It's more notorious on centered text, where the big chunk of color is at the start of the line:

![highlighted-centered](https://user-images.githubusercontent.com/468204/33230993-3c3c0118-d1cc-11e7-8a15-a1c9feb10b29.png)
