### ISSUE TITLE
NavigatorIOS::resetTo bug

### ISSUE THREAD

**Issue by daniel-nagy** [facebook/react-native#10576]
### Description

The `resetTo` method of the **NavigatorIOS** component calls `replaceAtIndex` followed immediately by `popToRoute`. The `replaceAtIndex` schedules a task to modify the `state` and the `popToRoute` reads from the `state`. The result is `this.state.routeStack` still points to the old stack when `popToRoute` is called.

One solution would be to provide a callback as a third parameter to the `replaceAtIndex` method to be called after the state is updated.

``` javascript
replaceAtIndex: function(route: Route, index: number, callback: () => void) {
  ...

  this.setState({
    idStack: nextIDStack,
    routeStack: nextRouteStack,
    makingNavigatorRequest: false,
    updatingAllIndicesAtOrBeyond: index,
  }, callback);

  ...
},

resetTo: function(route: Route) {
  ...
  this.replaceAtIndex(route, 0, () => {
    this.popToRoute(route);
  });
},
```
### Reproduction

Calling `navigator.resetTo` will produce the following error:

`Calling pop to route for a route that doesn't exist!`
### Additional Information
- React Native version: `0.35.0`
- Platform: IOS
- Operating System: MacOS

**Comment by ericvicenti** [comment]
`NavigatorIOS` hasn't seen much attention recently, thanks for highlighting this problem!

Because we want the native code to finish resetting the previous route before we start the pop, I think your proposed solution makes sense. Want to submit a pull request with that fix?

It would be even more modern if a promise was returned from `replaceAtIndex`!

**Comment by christopherdro** [comment]
@facebook-github-bot answered

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/navigatoriosresetto-bug
