### ISSUE TITLE
`MKTouchable' has no propType for native prop `MKTouchable.nativeForegroundAndroid` of native type `Map` 

### ISSUE THREAD

**Issue by GuelorEmanuel** [facebook/react-native#10579]
I recently upgraded react to version 15.3.2  and react-native to version  0.36.0.

When I run the simulator, this error popped up.

![14813286_10155460558533065_301059389_o](https://cloud.githubusercontent.com/assets/6937704/19754134/ba46d810-9bd8-11e6-99c2-e739af90a55a.png)

**Comment by satya164** [comment]
This is related to https://github.com/xinthink/react-native-material-kit

**Comment by timscott** [comment]
@GuelorEmanuel Did you solve this? I'm getting the same thing after upgrading react to 15.4.0.

**Comment by GuelorEmanuel** [comment]
@timscott Yes I did by updating the code on MKTouchable.js to the following  changes shown here https://github.com/xinthink/react-native-material-kit/pull/258/files#diff-baf96da6c3e386136d54a3847c06defd
