### ISSUE TITLE
Document that the corner-specific border radius props are unavailable for iOS's Image component

### ISSUE THREAD

**Issue by rigdern** [facebook/react-native#10570]
The corner-specific border radius props are ignored by iOS's `Image` component:
  - `borderTopLeftRadius`
  - `borderTopRightRadius`
  - `borderBottomLeftRadius`
  - `borderBottomRightRadius`

This fact should be documented.

**Comment by ppyupp** [comment]
me too

**Comment by brentvatne** [comment]
Agreed, either documented or fixed.
