### ISSUE TITLE
[Modal] View height is not working

### ISSUE THREAD

**Issue by pardeepbeniwal** [facebook/react-native#10584]
Hi All,
I am showing view in modal with given height to view but its not working. View in 'renderHabit' function in below code..
<TouchableOpacity style={styles.container_} onPress={() => this.setState({open: true})}>
               <Text>Open modal</Text>  
               <Modal
                  animationType={'slide'}
                  transparent={false}
                  visible={this.state.open}
                  onRequestClose={() => this.setState({open: false})}  
                >
               {this.renderHabit()}
            </Modal>

renderHabit(){
    return (
        <View style={styles.wrapperHabit}>
                  <Text style={{fontSize: 20, bottom: 110}}>Hello world!</Text>
                  <TouchableOpacity
                     style={{margin: 5}}
                     onPress={() => this.setState({open: false})}>
                     <Text>Close modal</Text>
                  </TouchableOpacity>
               </View>
    );
}

this is css:
 wrapperHabit: {
    borderRadius: 13,
    borderColor: '#fff',
    borderWidth: 2,  
    height:260,
    marginLeft: 0,
    marginBottom: 5,
    opacity:1,
    backgroundColor:'#ccc',
    flex: 1,
  },

**Comment by rogchap** [comment]
This is really hard to see what the issue is as there's no `code` formating for your snippet.
https://guides.github.com/features/mastering-markdown/

Where in the code are you using the `wrapperHabit` style?

I think this might be one for StackOverflow

**Comment by christopherdro** [comment]
@facebook-github-bot stack-overflow

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/modal-view-height-is-not-working
