### ISSUE TITLE
Build ReactNative  from source buidle fail 

### ISSUE THREAD

**Issue by DearDominic** [facebook/react-native#10580]
HI ,All 
MacOS 
ndk：android-ndk-r10e

I follow this page Step by step, also heppened this problems:
![image](https://cloud.githubusercontent.com/assets/8362319/19755595/9b6f7e58-9c49-11e6-9d29-d2c41ba3ee3e.png)

has anyone solve it ?

**Comment by leeight** [comment]
Need more logs ...

**Comment by DearDominic** [comment]
it's the error 
![image](https://cloud.githubusercontent.com/assets/8362319/19760327/d856d194-9c63-11e6-9c2e-8273b8aab436.png)

**Comment by leeight** [comment]
Check `ReactAndroid/src/main/jni/Application.mk`, and does this directories exist?

```
./ReactAndroid/src/main/jni/first-party
./ReactAndroid/src/main/jni
./ReactAndroid/build/third-party-ndk
./ReactCommon
```

**Comment by DearDominic** [comment]
Add this is 
![image](https://cloud.githubusercontent.com/assets/8362319/19762658/67c2f61a-9c6d-11e6-8f95-4737c8545e0e.png)

**Comment by DearDominic** [comment]
It's because the ReactCommon is not exist!  Copy it to ReactAndroid file, it's work
