### ISSUE TITLE
How can I get Image folder name in iOS? group_name is...

### ISSUE THREAD

**Issue by BROUDING** [facebook/react-native#10582]
I'm retrieving group_name in Android CameraRoll.getPhotos to sort all the pictures into Album folders.

It was easy since on Android since data.edges.node.group_name is holding all the album names.

But I found out on iOS, all the image's group_name is 'All Photos'....
So I cannot sort with the same logic.

What can I do to sort Images into different folders name in 'My Albums'...?
Those customized folders by different apps..

Thanks in advance !

**Comment by DanielMSchmidt** [comment]
@facebook-github-bot stack-overflow

**Comment by BROUDING** [comment]
StackOverFlow isn't helping, I need a comment from an author...;;
