### ISSUE TITLE
[iOS] Navigator Experimental freezes UI on Alert or Permission Dialog

### ISSUE THREAD

**Issue by K-Leon** [facebook/react-native#10598]
If an Alert or a Ask for Permission Dialog occurs while Navigator Experimental is transitioning the whole UI freezes until APP reload.
(Native Animations are disabled.)

This seems to be a newer Regression - everything works fine with an older version of navigation experimental. ( https://github.com/aksonov/react-native-experimental-navigation )
### Additional Information
- React Native version: 0.36+
- Platform: iOS
- Operating System: macOS

**Comment by anttimo** [comment]
@ericvicenti you mentioned in #10574 that this is a known problem. Do you have any extra information to add to this ticket that would help us get this fixed?

**Comment by hramos** [comment]
Navigation Experimental has been deprecated in favor of the [`react-navigation`](https://reactnavigation.org) library.
