### ISSUE TITLE
[Navigator] Event trigger after navigator push animation has finished

### ISSUE THREAD

**Issue by PhilippKrone** [facebook/react-native#1059]
Hello,

I'm currently trying to figure out which event to use to start doing something once the animation triggered by navigator.push() has finished. 
Background: I'm doing some quite complex ListView rendering which is starting already during the push()-animation, which makes the animation lag. My idea was to first of all have the basic layout pushed in by the navigator and once the animation is done, re-render the ListView and update the scene. During the time, some loading-animation will be shown or something similar..

Regards,
Philipp

**Comment by amccloud** [comment]
Same for me. I'm pushing a view that renders the `Camera` component from `react-native-camera`. I get major jitter when it is animating so for now i've use `setTimeout` to hide the camera. I've also noticed the jitter with simple list views also.

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by hufeng** [comment]
@PhilippKrone, try this,

```javascript
import React, {InteractionManager} from 'react-native';
const ListViewScene = React.createClass({
   componentDidMount() {
      InteractionManager.runAfterInteractions(() => {
         fetch(url).then....
      })
   },
   
   render() {
    //....
    } 
});
```

more about :) https://facebook.github.io/react-native/docs/interactionmanager.html#content

**Comment by chirag04** [comment]
``InteractionManager`` is great for complex view rendering. free to reopen if that does not solve your problem.
