### ISSUE TITLE
Animated TextInput Focus/Blur Bug

### ISSUE THREAD

**Issue by nickmacia** [facebook/react-native#10599]
There is a bug for RN v0.36.0 for ios dealing with Animated TextInputs. A TextInput has blur/focus methods attached to it via its ref (i.e. you can do this: `this.refs.myTextInputRefName.focus()` and it will focus the TextInput). However, if you animated the TextInput via `Animated.createAnimatedComponent(TextInput)` you lose these helpful methods and get the following error: 

![image](https://cloud.githubusercontent.com/assets/7825575/19785644/2bece93e-9c68-11e6-9843-ab4e499e2061.png)

It's intuitive to keep things consistent and allow for blur/focus methods to be called on an Animated Text Input. 

Here's some basic code to replicate the error: 

```

import React from 'react';
import {
  View,
  TextInput,
  Text,
  Animated,
  TouchableHighlight,
  StyleSheet
} from 'react-native';

const dismissKeyboard = require('dismissKeyboard');
const AnimatedTI = Animated.createAnimatedComponent(TextInput);

const test = React.createClass({
  getInitialState() {
    return {};
  },

  onKeyPress(key) {
    if (key === 'Enter') dismissKeyboard();
  },

  onPress() {
    this.refs.textInput.focus();
  },

  render() {
    return (
      <View>
        <AnimatedTI
          ref='textInput'
          autoFocus={false}
          multiline={true}
          blurOnSubmit={false}
          onKeyPress={(e) => {this.onKeyPress(e.nativeEvent.key)}}
          style={Styles.textInput} />

        <TouchableHighlight
          onPress={() => this.onPress()}
          style={Styles.touchable}>
          <Text> Touch to focus </Text>
        </TouchableHighlight>
      </View>
    );
  }
});

const Styles = StyleSheet.create({
 textInput: {
    height: 100,
    width: 200,
    backgroundColor: 'yellow',
    position: 'absolute',
    top: 100
  },
  touchable: {
    height: 100,
    width: 200,
    backgroundColor: 'red',
    position: 'absolute',
    top: 250
  }
});

module.exports = test;

```

**Comment by ericvicenti** [comment]
Good question! Based on [the implementation of Animated](https://github.com/facebook/react-native/blob/c9960817eea008b2703657066212002557e0d939/Libraries/Animated/src/AnimatedImplementation.js#L1777), I see that there is a `getNode()` method for this purpose. So if you want to call focus on an animated text input:

```
this.refs.textInput.getNode().focus();
```

Hope this helps!
