### ISSUE TITLE
Unhandled JS Exception: Invariant Violation in 0.36

### ISSUE THREAD

**Issue by goodhyun** [facebook/react-native#10593]
### Description

A usual upgrade and reload ended up with this red screen. 

![2016-10-27 9 29 02](https://cloud.githubusercontent.com/assets/4727708/19770155/278b3252-9c99-11e6-8263-495bda51cd9a.png)

### Reproduction

If we rolled back to 0.35, the symptom disappeared. 

### Additional Information

* React Native version: 0.36.0
* Platform: iOS
* Operating System: macOS

**Comment by rogchap** [comment]
Did you do all the usual "stuff"?
```
react-native upgrade
```
clear out watchman

restart packager

re-build:

```
react-native run-ios
```

**Comment by goodhyun** [comment]
Thanks for the comment @rogchap,
However, we took all those steps, but in vain. 

Thankfully, simultaneous upgrade toward 0.37.0-rc0 and Xcode/iOS 10.1 yesterday solved this issue.

**Comment by jsappme** [comment]
+1

**Comment by Aadesh05** [comment]
![simulator screen shot 10-apr-2017 6 28 59 pm](https://cloud.githubusercontent.com/assets/24405047/24862752/9b85ace2-1e1b-11e7-9dca-856ca471653c.png)
I am facing this issue can anyone help me solving it?

my package.json

{
  "name": "Project",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start"
  },
  "dependencies": {
    "react": "15.4.0",
    "react-native": "0.41.2",
    "react-native-splash-screen": "^2.0.0"
  }
}
