### ISSUE TITLE
AndroidTextInput throws error when color style is set to null

### ISSUE THREAD

**Issue by grubstarstar** [facebook/react-native#10602]
### Description

I have written a small component under "Reproduction" to describe this.

If you have a special style which is pushed onto a base style on a TextInput field, where the base style doesn't explicitly specify a "color" attribute but the special style does, then if the component re-renders from `[ baseStyle, specialStyle ]` to just `[ baseStyle ]` due to a `setState()` the following error is thrown. This happens only on the Android platform.

```
Error while updating property 'color' of a view managed by: AndroidTextInput
```
### Reproduction

```
import React, { Component } from 'react'

import {
    StyleSheet,
    TextInput
} from 'react-native'

export default class Test extends Component {

    constructor(props) {
        super(props)
        this.state = {
            text: '',
            special: false
        }
    }

    render() {
        let style = [ styles.baseStyle ]
        if(this.state.special) style.push(styles.specialStyle)
        return <TextInput
                    style={ style }
                    value={ this.state.text }
                    onChangeText={ (text) => this.setState({
                        text: text,
                        special: !this.state.special
                    }) } />
    }
}

const styles = StyleSheet.create({
    baseStyle: {
        height: 50,
        // color: 'blue' <-- uncomment this code to make the problem go away
    },
    specialStyle: {
        color: 'red'
    }
})
```
### Additional Information
- React Native version:
  $ react-native --version
  react-native-cli: 1.0.0
  react-native: 0.35.0
- Platform: Android
- Operating System: macOS Sierra

**Comment by leeight** [comment]
Can't reproduce it...

**Comment by grubstarstar** [comment]
Just tried it again with exactly the code I pasted above and get the attached error. It's using the standard Android emulator. It happens as soon as the the state changes back to `{ special: false }`, I.e. when you type the second letter in the text input.

<img width="525" alt="screen shot 2016-10-31 at 12 05 18 pm" src="https://cloud.githubusercontent.com/assets/1732170/19841603/4f048d12-9f62-11e6-87d1-8e016ffcfcea.png">

I just include it in the `index.android.js` as follows:

	import React, { Component } from 'react'
	import {
		AppRegistry
	} from 'react-native'


	import Test from './app/Test'

	export default class TheApp extends Component {
		render() {
			return (
				<Test />
			)
		}
	}

	AppRegistry.registerComponent('TheApp', () => TheApp)

as soon as I add a `color` attribute to the `baseStyle` it works fine.

**Comment by brentvatne** [comment]
I was able to reproduce with the above example. I enabled spy mode on the MessageQueue and checked logs to see what the issue was, it appears to be that the color cannot be set to null.

```
// After entering the first letter, a, we apply the "special" style and the text color becomes red
10-30 13:35:19.623 20202 20379 I ReactNativeJS: JS->N : UIManager.updateView([4,"AndroidTextInput",{"color":-65536,"text":"a"}])
```

```
// After entering the second letter, a again, we remove the "special" style and the text color becomes null
10-30 13:35:25.447 20202 20379 I ReactNativeJS: JS->N : UIManager.updateView([4,"AndroidTextInput",{"color":null,"text":"aa"}])
```

So, the easiest repro case is just to set the color on TextInput to `null`

**Comment by brentvatne** [comment]
@lacker - this could potentially cause issues in Facebook apps

**Comment by leeight** [comment]
@brentvatne But it looks like AndroidTextInput has already handled the null case: https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactTextInputManager.java#L308-L312

**Comment by lacker** [comment]
What do you expect to happen with color set to null?

**Comment by grubstarstar** [comment]
It just seems that if the React abstraction is trying to define the UI tree as a function of state then it should behave the same regardless of which state it's transitioned from. It renders successfully the first time without the color property so it should when it returns back to the same state. Perhaps my example should have had a button to toggle the styles instead.

**Comment by lacker** [comment]
Setting color to `null` is different from setting it to `undefined` though, so it is not actually returning back to the same state, is it?

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.

**Comment by trblandford4** [comment]
I recently ran into this issue. As stated by @grubstarstar above, I'm able to work around this issue by applying a base `color` style to the TextInput, however, it would be nice to see RN handle this in a future release. 

[Simple Repro Demo](https://github.com/trblandford4/RNAndroidTextInputColorError)

### Environment
Google Pixel Emulator
Android v7.1.1

`react-native -v` : `react-native-cli: 2.0.1` `react-native: 0.46.4`
`node -v` : `v7.7.2`
`npm -v` : `4.1.2`

**Comment by JuiceCrawl** [comment]
+1 
I am also able to reproduce this
react-native-cli: 2.0.1
react-native: 0.46.1
node -v: v6.11.3
npm -v: 3.10.10

**Comment by Jerameel** [comment]
+1
Having this issue when setting the color style of  TextInput to any value then triggering a button to hide that view with conditional rendering
react-native 0.51.0

![screenshot_1512819861](https://user-images.githubusercontent.com/15943153/33795280-714c79a2-dd19-11e7-9ef8-d5f7d3bf718f.png)

**Comment by grabcode** [comment]
We've experienced the same issue, and the work around is to define the `color` always. 
Example:
Not working:
