### ISSUE TITLE
[Android] ART LinearGradient in android show black?

### ISSUE THREAD

**Issue by zhonshu** [facebook/react-native#10604]
- React Native version: [0.33]

this code:
var nLinearGradient1 =
            new LinearGradient({
                    '1': '#6DB24778', //stop offsets and color
                    '0': '#FFFFFF',
                },
                "" + 128,  //x1
                "" + 0,  //y1
                "" + 128,  //x2
                "" + 16,  //y2
            );
<Surface style={{marginTop: 0,}} width={reactWidth1} height={32}>
      <Shape d={path1} stroke="#FFFFFF00" fill={nLinearGradient1} strokeWidth={0}/>
</Surface>

in iOS platform show shown correctly.

in Android platform show black.
ART is have React native Documentation Description and Usage or Sample for  Surface, Shape,fill,LinearGradient？

**Comment by leeight** [comment]
https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/art/ARTShapeShadowNode.java#L186-L187

**Comment by leeight** [comment]
Looks like only `SOLID_COLOR` was supported on Android.

**Comment by leeight** [comment]
Check this PR https://github.com/facebook/react-native/pull/5729

**Comment by brentvatne** [comment]
You could optionally use this library: https://github.com/react-native-community/react-native-linear-gradient/

**Comment by zhonshu** [comment]
@brentvatne  this PR #5729, When it can be merged into the master?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/android-art-lineargradient-in-android-show-black
