### ISSUE TITLE
index.ios.bundle is not updating

### ISSUE THREAD

**Issue by ostigley** [facebook/react-native#10601]
### Description

hitting CMD+R in the simulator does not pick up code / text changes in my app.  The simulator blinks, and the console reads that index.ios.bundle has been updated. 

```
[10/28/2016, 4:50:35 PM] <START> Requesting bundle: {"url":"/index.ios.bundle?platform=ios&dev=true&minify=false"}
[10/28/2016, 4:50:35 PM] <END>   Requesting bundle: {"url":"/index.ios.bundle?platform=ios&dev=true&minify=false"} (60ms)
```

The issue is consistent across all react-native apps running on my machine, so it is not application specific.  These repos/ apps work fine on other machines. I suspect it is an issue with Sierra 

I have tried re-installing watchman, and re-linking automake to no avail. 

Closing the react console, and re-running `react-native run-ios`, forces the bundle to pick up the changes.  
### Additional Information
- React Native version: react-native: 0.35.0
- React Version: 15.3.2
- Watchman VersionL: 4.7.0
- Platform: simulating ios: `react-native run-ios`
- Operating System: MacOS Sierra 10.12.1

**Comment by jaygarcia** [comment]
Question: If you attempt to view for the JS file in your browser, do you see the differences you make?

**Comment by ostigley** [comment]
You mean viewing the bundle? Where is that stored?

**Comment by brentvatne** [comment]
Try closing packager and running `watchman watch-del-all` then re-opening packager

**Comment by ostigley** [comment]
Sorry I have not had access to my laptop until now.  I have tried all the above, none make any difference.
