### ISSUE TITLE
Keyboard events not working on Android

### ISSUE THREAD

**Issue by marcshilling** [facebook/react-native#10613]
RN 0.36, Samsung Galaxy S6 running Android 6.0.1. 

```
componentDidMount() {
    this.keyboardDidShowListener = Keyboard.addListener('keyboardDidShow', this._keyboardDidShow);
    this.keyboardDidHideListener = Keyboard.addListener('keyboardDidHide', this._keyboardDidHide);
}
```

Logging in those methods, I can see that they are called on iOS, but not Android. I've read all the other issue threads regarding this but most of them are old at this point. I've added `android:windowSoftInputMode="adjustResize"` to my manifest. What am I missing?

**Comment by brentvatne** [comment]
Is this happening on a brand new project? Can you add breakpoints to see if these are ever called? https://github.com/facebook/react-native/blob/9ee815f6b52e0c2417c04e5a05e1e31df26daed2/ReactAndroid/src/main/java/com/facebook/react/ReactRootView.java#L302-L332

**Comment by brentvatne** [comment]
Tried this on a new 0.36 project and it works as expected:

![](http://i.giphy.com/3o7TKpjKFtN7GhsR44.gif)

```
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Keyboard,
  Text,
  TextInput,
  View
} from 'react-native';

export default class KeyboardTesting extends Component {
  state = {
    open: false,
  }

  componentDidMount() {
    this.keyboardDidShowListener = Keyboard.addListener('keyboardDidShow', this._keyboardDidShow);
    this.keyboardDidHideListener = Keyboard.addListener('keyboardDidHide', this._keyboardDidHide);
  }

  _keyboardDidShow = () => {
    this.setState({open: true});
  }

  _keyboardDidHide = () => {
    this.setState({open: false});
  }

  render() {
    return (
      <View style={styles.container}>
        <TextInput style={{width: 300, height: 50}} placeholder="Hello" />
        <Text>{this.state.open ? 'open' : 'closed'}</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

AppRegistry.registerComponent('KeyboardTesting', () => KeyboardTesting);
```

I'm not sure what is needed to make it work -- if you have a lot of custom Android code it might be worth creating a new project, copying the android directory in and overwriting everything and then painfully stepping over the diff to see what is missing. Let us know what you find!

**Comment by satya164** [comment]
Working fine for me too in an existing project.

**Comment by satya164** [comment]
I've not added anything to the manifest.

**Comment by marcshilling** [comment]
Investigating...standby...

**Comment by marcshilling** [comment]
Ok, figured out why it wasn't working. I was using the following code in `onCreate()` of `MainActivity.java` to make the status bar have a transparent background on launch:
```javascript
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
    getWindow().setFlags(WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS, WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS);
}
```

The keyboard events are way more important so I suppose I'll just find a different way of dealing with the status bar. Worth leaving this open to possibly support both cases or no?

**Comment by satya164** [comment]
@marcshilling You can just set transparent statusbar in the theme. Keyboard events worked fine with it last time I tried. Tough I'd recommend setting the `windowSoftInputMode` to `adjustResize` to have consistent keyboard behaviour in that case.

**Comment by marcshilling** [comment]
@satya164 yup, looks like `<item name="android:statusBarColor">@android:color/transparent</item>` in the theme does the trick (just requires API >= 21). Thanks for helping me track this down guys!

**Comment by bijubijoy** [comment]
i still cannot get the event working on RN42,
```
    componentDidMount(){
        this.kbe = Keyboard.addListener('keyboardDidShow', this.showMessage);
    }
   showMessage =()=> {
       alert('keyboardup');
    }

```

**Comment by ms88privat** [comment]
Having the same problem in v43.3

**Comment by jonas-arkulpa** [comment]
I've kind of the same issue.
The 'keyboardWillShow'/'keyboardWillHide' events don't get fired.
We're using the latest exponent sdk.
@brentvatne I successfully tested your example above, but as soon as I change the events from 'did' to 'will' it isn't working anymore.

**Comment by guigrpa** [comment]
@brentvatne I can confirm @jonas-arkulpa's findings. On iOS, both 'will' and 'did' are fired. On Android, only 'did'.

**Comment by brentvatne** [comment]
Indeed on Android `keyboardWillShow` does not exist: https://github.com/facebook/react-native/search?utf8=%E2%9C%93&q=keyboardWillShow&type=

Tracking here: https://github.com/facebook/react-native/issues/14275

**Comment by andresfcamacho** [comment]
@jonas-arkulpa  I'm also trying to get https://github.com/wix/react-native-keyboard-aware-scrollview to work on Android. I'm noticing another difference between the behavior of iOS and Android. 

It looks like 'keyboardDidShow' fires every time when entering a TextField on iOS even if the keyboard is up.  In Android it only fires once, that is if the keyboard is already up it doesn't fire when entering a TextField. The Android behavior seems more correct but unfortunately I actually want the iOS behavior. It would be great if the behavior was consistent.

**Comment by 12tp12** [comment]
Any update? @andresfcamacho

**Comment by RyanMitchellWilson** [comment]
Still an issue with react-native 0.50.0, is this being worked on?

**Comment by gabsschneider** [comment]
I am having the same issues with react-native 0.55.2. Keyboard listeners are not firing with android, not sure about ios though
