### ISSUE TITLE
[Getting started] Loads app but unable to update content

### ISSUE THREAD

**Issue by chhschou** [facebook/react-native#10618]
### Description

Created a new project "aaa" via react native cli
Expects a "welcome to react native..." but instead got in emulator a screen with "aaa" then "powered by react native"

Change index.ios.js, save or restart does not change the app content in emulator. 
### Reproduction

Create a new project via cli: 
react-native init aaa
cd aaa
react-native run-ios

In emulator (iphone 6) the screen prints "aaa" and "Powered by React Native" at the bottom. 
The index.ios.js has the usual "welcome to React native..." what is shown on screen do not match the js file content. Packager seems to be okay, visiting "http://localhost:8081/index.ios.js" the content looks right, again, does not match the app in emulator. The app in emulator is showing same content as the xlb file in xcode. 
### Additional Information
- React Native version: 0.36.0 (cli v1.0.0)
- Platform: IOS
- Operating System: MacOS Sierra

**Comment by brentvatne** [comment]
Hi there! It seems like the app is never actually loading. I would double check the logs in the packager to see that a request is coming through to it. Also you could try reseting both your computer and [reset content and settings](http://stackoverflow.com/a/9088416/659988) in the iOS simulator.

**Comment by chhschou** [comment]
@brentvatne I think you are right. An exception is throw and calls out issue with "bundleURL":

2016-10-31 22:21:43.033 [info][tid:main][RCTBatchedBridge.m:72] Initializing <RCTBatchedBridge: 0x608000185960> (parent: <RCTBridge: 0x6080000ad560>, executor: RCTJSCExecutor)
2016-10-31 22:21:43.035 aaa[9066:157000] *** Assertion failure in -[RCTBatchedBridge loadSource:](), /Users/cchou/dev/aaa/node_modules/react-native/React/Base/RCTBatchedBridge.m:189
2016-10-31 22:21:43.049 aaa[9066:157000] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'bundleURL must be non-nil when not implementing loadSourceForBridge'

When running in Xcode I noticed line 21 in Appdelegate.m jsCodeLocation is always nil, I don't know if that has anything to do with this.

**Comment by brentvatne** [comment]
Ah yes that seems to be a problem :| You might have to step through the code in Xcode to find out what is going wrong as it could be very particular to your machine, as nobody else has reported this issue. You could try [Exponent](http://getexponent.com/) as well, which would get you around this problem entirely because you don't need to compile anything with Xcode. (full disclosure: I work on Exponent)

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
