### ISSUE TITLE
I can't init the project

### ISSUE THREAD

**Issue by houyaowei** [facebook/react-native#10616]
when I run the command: react-native init ***, It took a long time and gave me no response.

China
Node: 5.10.0
npm: 3.8.3
Mac: macOs sirrea
How can I deal with the problem?
thanks
<img width="764" alt="screen shot 2016-10-29 at 11 54 35" src="https://cloud.githubusercontent.com/assets/3080429/19827033/86abc7ac-9dce-11e6-802d-3826d9293a6a.png">

**Comment by aqnaruto** [comment]
滚好么，别来拉低中国人的下限。这种问题不会百度 傻逼透顶

**Comment by aqnaruto** [comment]
你他妈懂不懂这叫issue 不是给你tm解决幼儿园问题的。别出来丢人现眼了行么。求你。

**Comment by nihgwu** [comment]
Because `npm install` is too slow and would fail at any time in China, it will take quite a long time to finish the init step.
You can use the taobao's registry. try `npm config set registry https://registry.npm.taobao.org/` before you run `react-native init`

**Comment by nihgwu** [comment]
@aqnaruto you are the one who disgraced us all
SHAME ON YOU

**Comment by nihgwu** [comment]
@aqnaruto This's the internet, to help you to remember your words 
![image](https://cloud.githubusercontent.com/assets/2595058/19829926/f9445f4e-9e1f-11e6-90cf-5aa4f7d17065.png)

**Comment by aqnaruto** [comment]
@nihgwu 我就在这里回应你，这种问题百度一下就可以解决的，这个题主把这个当成issue来提出来，你懂得issue 是什么吗？是这个项目的建议或者bug，这是在浪费rn宝贵开发人员的时间，这不是你国内的qq群。既然你又把我的留言贴了上来，那么我告诉你我没什么好shame的。我只是言论过激而已，而你，把提issue的地方当成了stackoverflow？ 浪费其他人员的机会懂吗。

**Comment by lipeiwei-szu** [comment]
@aqnaruto your issue about text attribute named "letterSpacing"(https://github.com/facebook/react-native/issues/10622) can be also searched on google or baidu, even i think you should get the answer from the react-native documents, because your "issue" is too simple. But what makes me angry is you attitude from the word on the screenshot, please don't do that again. Thanks to @nihgwu who provided the screenshot

**Comment by aqnaruto** [comment]
@lipeiwei-szu 提不提issue的界定应该是 你是帮助项目解决bug和使得项目变得更加完善 ，而不是让这个项目的工作人员替你解决小白问题。
我在提这个issue的时候，在本地多次测试反复验证求知确定才来提的，在rn下个版本或者若干个版本后应该会修复这个问题。
rn如果认为安卓上不支持那个属性 至少应该在源代码里注释说明下，或者warming一下，实际上没有，这说明这是一个遗漏。

在就事论事，我依然没有什么好shame的，应该shame的是楼主和自以为政治正确的你们？以为语言客气就可以堂而皇之的占用资源让别人为你解决问题而缺乏基本的动手和思考能力。这种问题百度半小时或者加几个qq群一问便知。rn的开发人员是有限的，如果所有人都按照楼主这样提小白问题，那么这个项目将彻底无法得到有效的反馈，认真提bug 提issue的人会被你们这种政治正确的问题所淹没。

再说几点个人的事
我爆了粗口，事后觉得不雅我已经删了，你依然要上纲上线以为抓住了我的小辫子，我告诉你这种做法毫无作用。爆粗口是我的人生乐趣之一,也许随着社会社交的需要，我的粗口会越来越少，但此时我依然要喷你，by the way，避免不雅我用别的方式喷：

`お前たちくちで偉そうに喋ってばかり、ぼくにみると馬鹿みだいなくずだけ、そんな暇があったら　もっと素晴らしい成果をみせとけ`
