### ISSUE TITLE
[RN 36+] Image module (iOS) Content-Type not honored by Image module

### ISSUE THREAD

**Issue by jaygarcia** [facebook/react-native#10612]
### Description
Seems that the Image module for iOS no longer pays attention to contentType.

The following image loads perfectly in browsers, and doesn't have an extension as part of the file name. 

[http://cdn-tp1.mozu.com/7979-10317/cms/10317/files/f4273799-ae7d-4924-9c70-83b32f3229b4?max=350](http://cdn-tp1.mozu.com/7979-10317/cms/10317/files/f4273799-ae7d-4924-9c70-83b32f3229b4?max=350)

Example issue: 

![image of issue](http://content.screencast.com/users/djliquidice/folders/Snagit/media/91d233b9-d872-4d6f-8485-a21ca763c703/2016-10-28_14-51-36.png)

### Reproduction

```
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  Image
} from 'react-native';

export default class ImageTest extends Component {
  render() {
    const uriOne = 'http://cdn-tp1.mozu.com/7979-10317/cms/10317/files/f4273799-ae7d-4924-9c70-83b32f3229b4?max=350',
          uriTwo = 'https://facebook.github.io/react/img/logo_og.png',
          size   = 150;

    return (
      <View style={styles.container}>
        <Image style={{height:size, width:size, borderWidth:1, resizeMode:'cover'}} source={{uri:uriOne}}/>
        <Image style={{height:size, width:size, borderWidth:1, resizeMode:'cover'}} source={{uri:uriTwo}}/>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

AppRegistry.registerComponent('ImageTest', () => ImageTest);

```

### Additional Information

* React Native version:  36
* Platform: iOS, Android
* Operating System: MacOS Sierra

**Comment by leeight** [comment]
It looks fine with the latest commit...
![image](https://cloud.githubusercontent.com/assets/104052/19825171/93b0ec3c-9da8-11e6-8ef5-40d4513b08e2.png)

**Comment by brentvatne** [comment]
Works for me as well @leeight!

Closing this @jaygarcia - if you have more info on how to repro it, another issue is of course welcome

**Comment by jaygarcia** [comment]
The image system seems to be a work in progress for iOS right now.  

@brentvatne Thanks for closing this. I'll await the next release.
