### ISSUE TITLE
Getting Start Project Throw Error When Start Debugging

### ISSUE THREAD

**Issue by terrence0488** [facebook/react-native#1061]
I'm following the Getting-Start tutorial form the React-Native site https://facebook.github.io/react-native/docs/getting-started.html#content

All seems to be good, Im able to init and run the AwesomeProject.
So WITHOUT changing anything, I try to debug.
in the IOS simulator window, I pressed cmd+D.
Chrome browser pop-up and showing :
Status: Waiting, press ⌘R in simulator to reload and connect

so i open up Chrome dev tool and press ⌘R in simulator. It jump to chrome,
Then, I see this error in Chrome dev tool console:
![error2](https://cloud.githubusercontent.com/assets/1990528/7391120/f8b1fdf4-eeb0-11e4-9a75-f6dad6c8bf48.jpg)

When I go back to simulator, it became this:
![error](https://cloud.githubusercontent.com/assets/1990528/7391131/1619e7a8-eeb1-11e4-91fd-8893a0474f64.jpg)

I tried to search through the internet, but couldn't find anything like this.
Please help.

Incase you want to check my code, get it here: https://app.box.com/s/gyqwtvxm5bud3r5ajhvko9i6ae579abp

**Comment by terrence0488** [comment]
Okay. I'm sorry for opening this issue. I have solved it myself.
The problem is with my Chrome browser.
I just uninstall it and re-install again. Problem solved!!

**Comment by jaygarcia** [comment]
@terrence0488 , please close this issue =)
