### ISSUE TITLE
Thoughts on Alpha blending?

### ISSUE THREAD

**Issue by jaygarcia** [facebook/react-native#1062]
Curious to learn what the FB team's head is at on alpha blending for Views?

**Comment by vjeux** [comment]
What does it mean? You can do `<View style={{opacity: 0.5}} />`.

**Comment by saltymule** [comment]
Do you mean UIViewGroupOpacity or rasterization ? http://stackoverflow.com/questions/8581994/ios-controlling-uiview-alpha-behaviour-for-subviews

**Comment by jaygarcia** [comment]
@vjeux  Yes i do.  I was half asleep when i posted this.


/me slaps self with a large trout.
