### ISSUE TITLE
::facebook::gloginit::initialize() not called, is it a typo?

### ISSUE THREAD

**Issue by leeight** [facebook/react-native#10621]
I'm using `LOG(WARNING) << "The log message"` on ReactCommon module, but can't get any log via `adb logcat`, after some investigation i found we should call `::facebook::gloginit::initialize()` to redirect the glog message to `adb logcat`.

If it's a typo, i'll send a PR to fix it.

**Comment by aqnaruto** [comment]
u should using  `console.log('what u want to log')`

**Comment by leeight** [comment]
cc @javache
