### ISSUE TITLE
Even On React 0.36 for android, all framework native modules are initialized on App Start [No Lazy initialization]

### ISSUE THREAD

**Issue by konark-hike** [facebook/react-native#10625]
### Description

As per release docs for React 0.36 ::
Add ability to lazy load Native Java Modules (797ca6c) - @AaaChiuuu
Android: add support for headless js tasks (3080b8d) - @foghina
Add flag to enable lazy view managers (1296cb2) - @AaaChiuuu

We have enabled setLazyNativeModulesEnabled(true) in code and have put logs in all native modules and even though my javascript code is not importing and using these native modules, they all are still getting initialised on app start.

Is there a way to not initialize native modules that are not imported and used in react java script bundle to save some space on Dalvik Heap

### Additional Information

* React Native version: 0.36
* Platform: Android
* Operating System: MacOS

**Comment by AaaChiuuu** [comment]
Lazy native modules is a project in testing right now:
If you like to take risks and gamble, and want to have this experimental lazy native modules in your app, there's a few things you need to do:
1. Make all ReactPackages in your app extend LazyReactPackage
2. annotate the new packages with @ReactModuleList
3. annotate all the native modules with @ReactModule
4. either build with buck to have ReactModuleSpecProcessor run or find a way to run ReactModuleSpecProcessor on the ReactPackages.

**Comment by brentvatne** [comment]
Thanks for more info @AaaChiuuu! Closing the issue

**Comment by konark-hike** [comment]
@AaaChiuuu Thanks for answering.
Have one follow-up question regarding the same :
Once the testing for Lazy native modules project gets completed , would this feature be supported by default in upcoming react-native versions and by which release and would it help in reducing memory footprint consumed by native modules on app initialization.

@AaaChiuuu It would be great if you can share some more information regarding this Lazy native modules project since there's not much documentation around it.

**Comment by AaaChiuuu** [comment]
yes, yes
Make annotations processor work with Gradle or switch from building your app with Gradle to BUCK.

There's not much documentation because it's in very early stages.

**Comment by priezz** [comment]
Hello, @AaaChiuuu. I am not sure I know how to switch from Gradle to Buck, make proper annotations and make all ReactPackages extend LazyReactPackage. Before we get some documentation on that, it would greatly help to learn if you share some app example (or it's pieces) with all that staff. I am sure you have something like that for development purposes.

**Comment by MarbleDev** [comment]
Same here. I'd love to know more information on how to switch from Buck to Gradle. I can't seem to get this to work. Can't make the reactprocessor run on react packages.

**Comment by miguelespinoza** [comment]
@AaaChiuuu.  Are there any plans on deprecating ReactPackage in favor of LazyReactPackage in the near future? 

I saw there was a TODO for this change: https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/LazyReactPackage.java#L30
