### ISSUE TITLE
Unable to perform - 'react-native start'

### ISSUE THREAD

**Issue by bozzmob** [facebook/react-native#10623]
I am unable to start react-native server - 'react-native start'
It says there is already a process running.
Is there a way to run the same on an alternate port?

There is this MACAFEE anti'virus' running on my Mac. And in no way I am able to kill it(Even though I should not be killing it, I tried it, and looks like it never dies! Sudo has no power after all!)

Referred to #7308 and this [stackoverflow](http://stackoverflow.com/questions/30216417/react-native-port-8081-already-in-use-packager-is-either-not-running-or-not-r)

It didn't help much.

Please suggest a way to run apps on a different port.

### Logs

```
bozzmob:Twitter bozzmobusr$ sudo lsof -n -i4TCP:8081 | grep LISTEN
macmnsvc 87518  mfe   24u  IPv6 0x935b5ff42ebea7bf      0t0  TCP *:sunproxyadmin (LISTEN)
bozzmob:Twitter bozzmobusr$ react-native start
Scanning 595 folders for symlinks in /Users/bozzmobusr/collection/work/github/reactnative/Twitter/node_modules (5ms)
 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  Running packager on port 8081.                                            │ 
 │                                                                            │ 
 │  Keep this packager running while developing on any JS projects. Feel      │ 
 │  free to close this tab and run your own packager instance if you          │ 
 │  prefer.                                                                   │ 
 │                                                                            │ 
 │  https://github.com/facebook/react-native                                  │ 
 │                                                                            │ 
 └────────────────────────────────────────────────────────────────────────────┘ 
Looking for JS files in
   /Users/bozzmobusr/collection/work/github/reactnative/Twitter 

[4:33:12 PM] <START> Building Dependency Graph
[4:33:12 PM] <START> Crawling File System
 ERROR  Packager can't listen on port 8081
Most likely another process is already using this port
Run the following command to find out which process:

   lsof -n -i4TCP:8081 

You can either shut down the other process:

   kill -9 <PID> 

or run packager on different port.

See http://facebook.github.io/react-native/docs/troubleshooting.html
for common problems and solutions.
bozzmob:Twitter bozzmobusr$ sudo kill -9 87518
bozzmob:Twitter bozzmobusr$ sudo lsof -n -i4TCP:8081 | grep LISTEN
macmnsvc 88265  mfe   24u  IPv6 0x935b5ff457ed6d3f      0t0  TCP *:sunproxyadmin (LISTEN)
bozzmob:Twitter bozzmobusr$ 
```

### Additional Information

* React Native version: 0.32.1
* Platform:  both
* Operating System: MACOS

**Comment by bozzmob** [comment]
Dug a lot deeper and found out the answer.
**--port=<port-value>** solved the issue.

`react-native start --port=8088`

**Comment by bozzmob** [comment]
But, I still see RED Screen of Death :( Need help.

What is happening - `react-native start --port=8088` works fine. Haste Map and Dependency Graph is getting generated. App gets installed fine when I do `react-native run-android`.
But, the red screen still shows up which says-

**Could not connect to development server**

**Comment by Ehesp** [comment]
Have you set the host/port up to point to the new non-default location in the app dev menu?

![image](https://cloud.githubusercontent.com/assets/842078/19832606/c487357e-9e1f-11e6-8d2a-6ad0ecebcb9a.png)

**Comment by brentvatne** [comment]
Hey there! It's probably best to post this to https://www.facebook.com/groups/react.native.community/ or StackOverflow :) If it turns out that this is actually a bug with React Native, feel free to repost here.

**Comment by bozzmob** [comment]
Raised a discussion here - https://www.facebook.com/groups/react.native.community/permalink/876065075862405

And here - http://stackoverflow.com/questions/40817009/could-not-install-the-app-on-the-device-on-react-native-run-android
