### ISSUE TITLE
Support linear-gradient as background option

### ISSUE THREAD

**Issue by rturk** [facebook/react-native#10627]
### Rational

Support linear gradients in the Core RN View

### Reference

https://developer.mozilla.org/en-US/docs/Web/CSS/linear-gradient

### Existing community code & discussion thread

https://github.com/react-native-community/react-native-linear-gradient
https://github.com/react-native-community/react-native-linear-gradient/issues/119

**Comment by brentvatne** [comment]
Hi there! A pull request would be welcome for this, I believe -- but if you aren't familiar with how to build this, can you repost this to ProductPains? We use this to prioritize features. https://productpains.com/product/react-native

Thanks!

**Comment by rturk** [comment]
Hi @brentvatne I've opened this to discuss if makes sense to create a PR. Also needs feedback regarding proper implementation.

Can you clarify your comment above `pull request would be welcome for this`? So makes sense to create one ? It will not be a trivial work and it will consume some time, specially considering tests. Before investing time I would like to get a better feedback from the RN team if this is a good feature for the core RN.

I wasn't expecting this to be closed so fast.. IMO productpains is the place that all issues go to die..

**Comment by Kielan** [comment]
let's re-open this issue to keep the discussion going. I may also take a crack at it depending on how much time I can allocate, I have been solving this problem on my own project and am exploring the solution further.

**Comment by ajonno** [comment]
hi, has there been any progress on this feature ? our UX folks have handed us a bunch of gradient filled buttons/views, this would be great to see in core RN if poss.
