### ISSUE TITLE
PushNotification + Parse

### ISSUE THREAD

**Issue by PhilippKrone** [facebook/react-native#1063]
Hello,

I'm currently trying to use PushNotificationIOS + Parse. However, the push notification is completely handled by Parse (and thus shown on the iphone, which means that the push notification arrives on the iphone successfully). The event in PushNotificationIOS is not triggered at all. Does anyone has experience with that? 

My current debugging state is that the following function in the file RCTPushNotificationManager.m is not called at all, and thus it is not transferred to RN:

- (void)handleRemoteNotificationReceived:(NSNotification *)notification
{
  [_bridge.eventDispatcher sendDeviceEventWithName:@"remoteNotificationReceived"
                                              body:[notification userInfo]];
}

Regards,
Philipp

**Comment by PhilippKrone** [comment]
I was able to fix it by adding the following code in appdelegate.m - however, I wonder why it is not working in RCTPushNotificationManager.m: 

- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo {
    [[NSNotificationCenter defaultCenter] postNotificationName:@"RemoteNotificationReceived"
                                                        object:self
                                                      userInfo:userInfo];
}

**Comment by jonaswindey** [comment]
I was looking for the exact same issue at the same time. 

Thanks for your tip, I'm also clueless why that method isn't called in RCTPushNotificationManager.m, but needs to be included in AppDelegate. Method signature is identical, and for instance initWithInitialNotification is called correctly (in RCTPushNotificationManager.m)

**Comment by dvdhsu** [comment]
I was working on this a week or two ago. IIRC, you should import "RCTPushNotificationManager.h" in AppDelegate. Then:

    - (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo     {
      [PFPush handlePush:userInfo];
      [RCTPushNotificationManager application:application didReceiveRemoteNotification:userInfo];
    }

**Comment by christopherdro** [comment]
This might help. http://stackoverflow.com/questions/29683720/react-native-push-notifications-parse

**Comment by andyyou** [comment]
@PhilippKrone seems u fix the problem. could you please teach me the detail?
I want to figure out, so if I use Parse(JS SDK) not iOS SDK so I do as follow could you help check it right?

1. Follow [Parse guide](https://parse.com/tutorials/ios-push-notifications until step 4.
2. Setup react-native [PushNotificationIOS](https://facebook.github.io/react-native/docs/pushnotificationios.html#content) 
3. Finally I can use Parse for send push and PushNotificationIOS can handle message.
