### ISSUE TITLE
React Native style attribute fontFamile Has no effect

### ISSUE THREAD

**Issue by TrustTheBoy** [facebook/react-native#10631]
OS :windows10
react native version：0.31~0.36（Start to the present）
react native style attribute fontFamile Has no effect？
I tried to go to stackoverflow to ask questions, but I did not get a satisfactory answer,
Once again, ask the discussion group for help and learn that they have also encountered this problem. And unresolved

Thank you

**Comment by brentvatne** [comment]
The attribute name is `fontFamily` and not `fontFamilie` :)

**Comment by TrustTheBoy** [comment]
@brentvatne Pre-submission problems due to careless fontFamily written by fontFamilie
