### ISSUE TITLE
Can't seem to use any node built in modules

### ISSUE THREAD

**Issue by Gacnt** [facebook/react-native#10630]
### Description

Trying to install certain node modules that use things like `EventEmitter` or `Buffer` and they're failing because they cannot find the module

### Reproduction

https://rnplay.org/apps/9k0nRQ

Here's a simple RNPlay that gives a quick example of trying to use Buffer to base64 encode

### Additional Information

* React Native version: [0.36.0]
* Platform: [FILL THIS OUT: iOS]
* Operating System: [MacOS]

**Comment by stovmascript** [comment]
This is because RN doesn't actually run on node (V8), but JSC. You can however use [rn-nodeify](https://www.npmjs.com/package/rn-nodeify) to get node stuff running in a RN app reasonably well.

**Comment by brentvatne** [comment]
@stovmascript - spot on
