### ISSUE TITLE
Unhandled promise rejection on Windows 10

### ISSUE THREAD

**Issue by briankabiro** [facebook/react-native#10649]
[Hot Module Replacement] Server listening on /hot

React packager ready.

[10/31/2016, 11:59:32 AM] <START> Requesting bundle: {"url":"/index.android.bundle?platform=android&dev=true&hot=false&minify=false"}
(node:3864) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Watcher took too long to load (NodeWatcher)

**Comment by brentvatne** [comment]
cc @rozele

**Comment by rozele** [comment]
Haven't seen this one in a while, there used to be a two minute time out for the node watcher to do its work, but I thought that was removed well before node-haste was copied into react-native.

**Comment by briankabiro** [comment]
I hadn't updated React in a while, worked after I updated react.
