### ISSUE TITLE
[Android] "onScroll" is not invoked

### ISSUE THREAD

**Issue by JChord** [facebook/react-native#10646]
I want to load JS bundle File form Remote by override the `protected String getJSBundleFile`, and the JS file is below:
```
import React, { Component } from 'react';
import {
    AppRegistry,
    StyleSheet,
    Text,
    View,
    ScrollView
} from 'react-native';

let List = [];
for (let i = 0; i < 20; i ++) {
    List.push('List item ' + i)
}

const RN_Demo = React.createClass({

    getInitialState: function() {
        return {
            count: 0
        }
    },

    onScroll: function() {
        this.setState({
            count: ++this.state.count
        })
    },

    render: function() {
        return (
            <View style={styles.container}>
                <View style={styles.bar}>
                    <Text style={styles.barText}>{this.state.count}</Text>
                </View>
                <ScrollView onScroll={this.onScroll} scrollEventThrottle={32}>
                    {
                        List.map(v => {
                            return <View key={v} style={styles.container}>
                                <Text style={styles.welcome}>
                                    {v}
                                </Text>
                            </View>
                        })
                    }
                </ScrollView>
            </View>
        );
    },

});

const styles = StyleSheet.create({
    container: {
        flex: 1
    },
    bar: {
        height: 64,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#F5FCFF'
    },
    barText:  {
        paddingTop: 16,
        fontSize: 20,
    },
    welcome: {
        fontSize: 20,
        textAlign: 'center',
        margin: 10,
    }
});

AppRegistry.registerComponent('RN_Demo', () => RN_Demo);
```
But the 'onScroll' method is not invoked.

When I load the same bundle file in local `assets` dir, it seems running well.

**Comment by brentvatne** [comment]
> I want to load JS bundle File form Remote by override the protected String getJSBundleFile
> When I load the same bundle file in local assets dir, it seems running well.

I don't think these things should be at all related, can you post a repository to Github that reproduces this? (including your override of `getJSBundleFile`)

**Comment by JChord** [comment]
Hi, @brentvatne  I have found the primary cause of the problem.
I am init the `ReactNativeHost ` out of `onCreate` of `Application`, when I moved it out of `onCreate` as the doc, it gone be normal.
If I am move the init method,  how could I load bundle dynamically? tks.
The repository is [RNDemo](https://github.com/JChord/RNDemo).

**Comment by brentvatne** [comment]
Not too sure about that, maybe @lelandrichardson knows

**Comment by lelandrichardson** [comment]
hmm. I'm not sure I understand how these two things would be related, either.  We load the bundle inside of `Application::onCreate` as well...  What is this `RNManager` you are using?

**Comment by JChord** [comment]
`RNManager ` is using to  init the `ReactNativeHost` object and download the remote bundle.
But there is two components named "cheniu_shop" and "workspace" not tirgger the `onScroll` method.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/android-onscroll-is-not-invoked
