### ISSUE TITLE
[ios] [ListView] performance of RELEASE is worse than DEBUG

### ISSUE THREAD

**Issue by lkj01010** [facebook/react-native#10645]
I put some rows in ListView with 'removeClippedSubviews' on. If row height is large enough, as 2~4 row in one screen, performance is ok. But when the count of row becomes to more then 5, Performance go worse , unlike native.

This occurs with release build. But When i set to debug build, the performance comes back to native like.

I wonder why.  And how can I get the performance as in debug with release build.

* React Native version: 0.35.0
* Platform: : iOS
* Operating System: iphone5

**Comment by brentvatne** [comment]
How are you evaluating performance? Can you share the exact metrics, or video recordings (perhaps slow-motion)? How do the metrics / videos differ if `removeClippedSubviews` is disabled? Is the data that you're looking at in release and debug exactly the same? Large images might impact scroll performance, for example.

**Comment by lkj01010** [comment]
![vid_20161031_201651](https://cloud.githubusercontent.com/assets/4750475/19854761/afde9dc8-9fab-11e6-89c2-2b119f29fe6a.gif)
![vid_20161031_202302](https://cloud.githubusercontent.com/assets/4750475/19854774/c3cd5626-9fab-11e6-8298-cc7f54ccfd5e.gif)

first - debug ,  second - release

 In release situation, scroll cross top items which is long enough , motion is smooth. Afterwards, there are some items with small 'height', showing 5 or more one screen, the motion becomes rough. 

With debug build, motion is always smooth. 
With removeClippedSubviews disable, motion is smooth in both situations.

**Comment by brentvatne** [comment]
thanks @lkj01010, that helps a bit. I personally have no idea why this would be different between debug and release, @ide - what do you think?

**Comment by brentvatne** [comment]
my only thought is that maybe you have some code that is executing in release mode but not in debug, maybe some analytics or something? maybe caching? something that could potentially be making the main thread busier than it would otherwise be in debug

**Comment by lkj01010** [comment]
@brentvatne there is no different code between the two modes, yet no analytics or logs ... 
as long as two months ago, using RN 0.30 I had meet this problem. At that time, I use Navigator, and when there is more than 3 row in one screen, the scrolling motion became rough( navigation was also rough) . Afterwards, I change to react-native-navigation, navigation and scrolling motion all became smooth.  I considered this was solved. 
But now, there is more than 4 row in one screen, scrolling motion problem comes back :(
I consider if there is difference in removeClippedSubviews algorithm between the two mode?  thanks

**Comment by lkj01010** [comment]
@brentvatne I made an empty RN 0.36 project and tested the nearly same ListView page. Motion performance between debug and release looks same. I will dive to my project to find problem.
thanks for reminding me
