### ISSUE TITLE
[NavigationExperimental] Add more transitioning animation styles on NavigationCardStack

### ISSUE THREAD

**Issue by yuya-fujimoto** [facebook/react-native#10647]
Any plan to add more animations on NavigationCardStack just like Navigator component has FloatFromLeft and HorizontalSwipeJump, etc?

Currently there're only vertical and horizontal for its transitioning animation.
I know it's possible by creating custom animation using NavigationTransitioner for my own use cases, but I guess it would be great for a lot of people if there're other animation styles in NavigationCardStack.

And my suggestion is to replace current direction props to configureScene props just as provided in Navigator component. (also keep it work if someone put direction props instead of configureScene for a while with a warning)

cc. @ericvicenti

**Comment by brentvatne** [comment]
Hi @yuya-fujimoto! This is not so much of an issue as it is a question, which would be better suited for https://www.facebook.com/groups/react.native.community or ProductPains. We try to keep issues for bugs.

**Comment by ericvicenti** [comment]
We don't have any plans for other animations right now, unless you want to build them!

**Comment by robcalcroft** [comment]
Is it possible to port animations from `Navigator`? I'm also looking for alternate animations like `PushFromRight`

**Comment by ericvicenti** [comment]
It is totally possible, but the animations are mostly unowned right now.

If you or anyone else in the community has the bandwidth to port over the animations from Navigator, or fine-tune them to look perfect on each platform, it would be a super valuable contribution! I'd be happy to review the code. Please make an issue (and tag me) ahead of time so we can discuss the ideal API before you build it out.

**Comment by dannycochran** [comment]
@ericvicenti what about an API that would allow for user defined animations on the JS thread? does that seem feasible?

**Comment by ericvicenti** [comment]
I think we should have NavigationCardStack take an optional prop that overrides the NavigationCard component. So you could provide `cardComponent={MyCustomCard}` to CardStack, where MyCustomCard is a fork of NavigationCard. Would that work for you?
