### ISSUE TITLE
ScrollView bounce stuck mid-animation when scrolling inertially on Android

### ISSUE THREAD

**Issue by stovmascript** [facebook/react-native#10653]
### Description

When you scroll in a ScrollView and it reaches its end, it will leave a small gap below the ScrollView (note the white space above the Android navigation bar). I think it's because the bounce animation gets cut off. It only happens when you scroll inertially - if you reach the end with your finger still on the screen, it works as expected. 

![screenshot_2016-10-31-12-22-22](https://cloud.githubusercontent.com/assets/14262802/19853283/8c73a9b6-9f68-11e6-9a5e-45373c61704c.png)

The size of the gap depends on how much inertia you give it:

![screenshot_2016-10-31-12-22-31](https://cloud.githubusercontent.com/assets/14262802/19853284/8fd942f0-9f68-11e6-911b-cfb2bb5c7cb4.png)

When you then interact with screen again (try to overscroll), the gap disappears:

![screenshot_2016-10-31-12-22-40](https://cloud.githubusercontent.com/assets/14262802/19853315/b79c90e4-9f68-11e6-9614-0a3bba50475b.png)

I also tried giving the ScrollView `flex: 1`, wrapping it in a View with `flex: 1`, disabling `removeClippedSubviews` - all the "tricks" I could find in other issues, but still no go.

I expect the ScrollView to have the same bounce effect at its start and its end and to not leave any gaps behind.

What's actually happening is that the ScrollView bounce effect only works at the top. At the bottom, it gets chopped off and leaves a gap behind.

### Reproduction

I couldn't reproduce it on rnplay, but I see it on all my devices (Android 5 & 6) and also in Genymotion VMs (Android 4 & 6). Here is a [sample project](https://github.com/stovmascript/sample-react-native-scrollview-issue):

```shell
$ git clone https://github.com/stovmascript/sample-react-native-scrollview-issue.git
```

Of course, it's also reproducible on ListViews, where I initially noticed it.

### Additional Information

* React Native version: 0.36.0
* Platform: Android
* Operating System: MacOS

**Comment by brentvatne** [comment]
My guess is that this is an Android bug. Can you try to verify it on a plain Android app?

If you set `backgroundColor` on the `ScrollView` directly, it solves the problem, eg:

```
export default class SampleScrollViewIssue extends Component {
  render() {
    return (
      <View style={{ flex: 1 }}>
        <ScrollView style={{ flex: 1, backgroundColor: 'green'}}>
          {Array.from({ length: 9 }).map((item, index) => (
            <View style={styles.container} key={index}>
              <Text style={styles.welcome}>
                Welcome to React Native!
              </Text>
              <Text style={styles.instructions}>
                To get started, edit index.android.js
              </Text>
              <Text style={styles.instructions}>
                Double tap R on your keyboard to reload,{'\n'}
                Shake or press menu button for dev menu
              </Text>
            </View>
          ))}
        </ScrollView>
      </View>
    );
  }
}
```

**Comment by stovmascript** [comment]
I'm not apt at Android development unfortunately.

Still seeing the same behaviour with `backgroundColor` set:

![screenshot_2016-10-31-15-56-19](https://cloud.githubusercontent.com/assets/14262802/19858903/8dd892f6-9f83-11e6-8555-3a90551573f3.png)

I'm pretty sure that it wasn't an issue with v0.30 (current production version of our app). I'm gonna back and test out the different versions of RN on the sample project and get back with the results.

**Comment by stovmascript** [comment]
Ok, so it seems to have been introduced with RN v0.32.0.

**Comment by brentvatne** [comment]
@stovmascript - any idea which commit might have done it?

**Comment by stovmascript** [comment]
@brentvatne Looks like there was a change to the ScrollView here:

> Fix ScrollView bounce back bug in open source (36ca1a0) - @astreet 

There are other commits since then, but some have been reverted, so this might be it?

**Comment by stovmascript** [comment]
As there are some comments regarding OEMs in these changes, think I should mention that I'm testing on:

- Huawei P8lite (ALE-L21, Android 5.0.1)
- LG Nexus 5 (stock Android 6.0.1)

**Comment by brentvatne** [comment]
looks like @astreet fixed this in https://github.com/facebook/react-native/commit/f2d3113c1db894097ef67ab1da84a508e39a3448 -- if it doesn't work then ping me and I can reopen @stovmascript

**Comment by astreet** [comment]
Thanks for the bug report! This should be fixed now in https://github.com/facebook/react-native/commit/f2d3113c1db894097ef67ab1da84a508e39a3448 (I verified it no longer repros with your sample app -- thanks for providing it!)
