### ISSUE TITLE
Switch component doesn't toggle. 

### ISSUE THREAD

**Issue by EJohnF** [facebook/react-native#10651]
### Description

>Launch the app
>Tap and hold on switcher
>Move switcher forward and back still Holding it
-The switcher will stuck in undefined state and you can't to change it.(It will always white or green with no reaction on taps) 

### Reproduction

https://rnplay.org/apps/Jatmhg

### Additional Information

* React Native version: "react-native": "^0.35.0"
* Platform: (try on) Android
* Operating System: MacOS

**Comment by brentvatne** [comment]
Thanks for the report! This isn't super easy to reproduce but it is possible, I found it's easier when you move it back and forth but also rather than releasing the touch, you move your finger off of the screen.

**Comment by christopherdro** [comment]
@facebook-github-bot icebox

**Comment by JeffreyLeeSpokeo** [comment]
Ok I think I know what the issue is. I encountered the same problem so I started removing properties from my Switch Component. Once I removed thumbTintColor, it works perfectly fine

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/switch-component-doesnt-toggle

**Comment by ellman121** [comment]
This is still happening on React-Native 0.45.1

**Comment by VasudevAkhil** [comment]
Hello @hramos 
  This issue is still happening in React-native 0.48 . I also tried removing all the properties on switch as suggested by @JeffreyLeeSpokeo but issue still persists.

**Comment by ragar90** [comment]
Same problem with react 0.47 and 0.49 this issue has to be reopen i tested in fresh new app and had the same issue

**Comment by BalalRaza** [comment]
This is still prevalent in RN 0.49. This issue should remain open.

**Comment by russhwolf** [comment]
Looks like it got reopened as #15632

**Comment by putuyoga** [comment]
same here 0.42

**Comment by darkmantle** [comment]
Getting it in 0.55.4 as well - huge problem!

**Comment by mnn** [comment]
Yep, confirming it being broken in 0.55.4. Even without any properties it still stays in one state state and cannot be changed (not by clicking, not by dragging). They seem to ignore it, maybe creating new issue would draw some attention?
