### ISSUE TITLE
Comprehensive ES2016+ audit

### ISSUE THREAD

**Issue by ide** [facebook/react-native#10661]
React Native supports some subset of ES2015 and ES2016 features (plus more), but there are still some confusing gotchas that we can fix. It'd be useful to have a test suite of JavaScript features that we support on iOS 8+ and Android and support as much of ES2016 as we can in a reasonable way. This would exclude features like Proxies and native behavior that is convoluted to replicate, but most of the behavior of for-of loops, Array.prototype.includes, the exponentiation operator, and so on is polyfillable in reasonable ways, for facebook's definition of reasonable.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/comprehensive-es2016-audit
