### ISSUE TITLE
`UIExplorer/CameraRollView.ios.js` images take about 10s-30s to load

### ISSUE THREAD

**Issue by plredmond** [facebook/react-native#1066]
Run the UIExplorer example, select the `<CameraRollView>` example. Wait 10 to 30 seconds for the images to load.

![screen shot 2015-04-29 at 1 29 03 pm](https://cloud.githubusercontent.com/assets/1078772/7400941/41c0c43a-ee75-11e4-8290-0ab86d32f47f.png)

**Comment by arthuralee** [comment]
+1. Related to #930?

**Comment by plredmond** [comment]
@arthuralee yep. same issue, i just wanted to provide a quick example-based repro.. we can close this as a dup if desired

**Comment by brentvatne** [comment]
Let's try to keep it to issue :smile: @plredmond thanks for the help, this issue will be forever linked to the other because of the above tag haha.
