### ISSUE TITLE
Modal.onRequestClose on iOS is never called

### ISSUE THREAD

**Issue by Paul-Todd** [facebook/react-native#10662]
--- Please use this template, and delete everything above this line before submitting your issue --- 

### Description

onRequestClose is never called when the dialog is dismissed on iOS. The documentation claims it is an optional callback on iOS.

Can someone clarify if the onRequestClose is supposed to be not implemented on iOS or if this is a bug? 

### Reproduction
Create a simple project with a modal
Add the onRequestClose property
````
onRequestClose={() => {alert("Modal has been closed.")}}
````

The alert is not fired after the dialog has closed.

### Additional Information

* React Native version: 0.35.0
* Platform:iOS
* Operating System: MacOS

**Comment by nihgwu** [comment]
Actually the description for **onRequestClose** is wrong for quite a long time, it's not **a function that will be called once the modal has been dismissed**, but **a function that will be called once you press the hardware back button**, so it's invalid on iOS.

I'll send a PR then.

**Comment by Paul-Todd** [comment]
Thanks, it would be nice to have a callback once the dialog is fully dismissed but I will use an alternative modal for now.

**Comment by rodrigoruiz** [comment]
@Paul-Todd what's the alternative you used?

**Comment by zenoven** [comment]
ah...got this issue too...

**Comment by Paul-Todd** [comment]
I put callbacks for the ok and cancel buttons in my modal and then used that to hide the modal. I think we should have the onRequestClose method also work on iOS so we can capture the post modal close scenario.

I would have liked to have it so I could display a toast once a record was deleted.

**Comment by journeyOS** [comment]
/**
     * The `onRequestClose` callback is called when the user taps the hardware back button.
     * @platform android
     */
    onRequestClose: Platform.OS === 'android' ? PropTypes.func.isRequired : PropTypes.func,

only for android

**Comment by euroclydon37** [comment]
I also couldn't listen for the 'menu' event in TVEventHandler. It never fired. It's like the modal is intercepting the menu button event and not propagating it.
