### ISSUE TITLE
[Android] <TextInput> secureTextEntry={true} broken on Android for phone-pad and email-address keyboard types

### ISSUE THREAD

**Issue by cbrevik** [facebook/react-native#10678]
### Description

As [nihgwu](https://github.com/facebook/react-native/issues/4090#issuecomment-239095975) notes in #4090, `secureTextEntry={true}` for `TextInput` on Android is broken if you use the cross-platform keyboardTypes `phone-pad` or `email-address`. Seems to be related to how [checkPasswordType in ReactTextInputManager](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactTextInputManager.java#L564) is implemented.

### Reproduction

Try the following in an Android RN component.

```javascript
 <TextInput
     onChangeText={(text) => this.setState({ phonePadText: text })}
     value={this.state.phonePadText}
     secureTextEntry={true}
     keyboardType="phone-pad"
  />
 <TextInput
     onChangeText={(text) => this.setState({ emailAddressText: text })}
     value={this.state.emailAddressText}
     secureTextEntry={true}
     keyboardType="email-address"
  />
```

### Additional Information

* React Native version: 0.35
* Platform: Android
* Operating System: MacOS

**Comment by panzer-planet** [comment]
I'm having the same problem. RN 0.35, Android, MacOS 10.12.1.

**Comment by Simbamoureux** [comment]
Same problem with RN 0.37, Linux Ubuntu 14.04

**Comment by mixophrygian** [comment]
Ditto RN 0.40 iOS, Sierra 10.12.4

**Comment by ItsNoHax** [comment]
secureTextEntry with keyboardType 'numeric' is also broken

**Comment by basequatro** [comment]
secureTextEntry with keyboardType 'email-address' is also broken.

RN: 0.43.1
Android
Samsung Galaxy S6

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/android-textinput-securetextentrytrue-broken-on-android-for-phone-pad-and-email-

**Comment by DanGDroid** [comment]
sorry, but it still does not work for android on v0.45.1

**Comment by Avinash-Setty** [comment]
It still does not work for Android on v0.47.0

**Comment by mleduque** [comment]
Still broken on 0.48.3

**Comment by edudel** [comment]
yeah .. still broken on the latest one. why is it closed ?

**Comment by erwan-lcs** [comment]
Yep broken, re-open please

**Comment by tomas-paronai** [comment]
Broken iOS RN 0.49.0

**Comment by kaushikdas0** [comment]
broken+1

**Comment by CheapSeth** [comment]
Still broken as of now

**Comment by DaniAkash** [comment]
Still broken in react native version 0.54.2

**Comment by skyl** [comment]
Using expo with my Android 0.55.X - not working for me.

**Comment by hramos** [comment]
Please open a new issue.

**Comment by JoostSlijkoort** [comment]
So it can be closed again?

**Comment by pedreviljoen** [comment]
Still broken...
