### ISSUE TITLE
Getting started guide has wrong android tool version

### ISSUE THREAD

**Issue by sadika9** [facebook/react-native#10672]
### Description

In [getting started](https://facebook.github.io/react-native/docs/getting-started.html) guide it instruct only to install Android 7.0 (Nougat) sdk. 
But `react-native run-android` failed with following error, as android project requires android 23 build tools and platform tools.

> failed to find target with hash string 'android-23' in: /home/<user>/Android/Sdk

### Reproduction

In android sdk manager remove all SDK platforms and install only Android 7 platform.
Create new RN project (`react-native init MyProject`)
Run android app using `react-native run-android`

* React Native version: 0.36.0
* Platform: Android
* Operating System: Linux

**Comment by hramos** [comment]
Known issue, see #10372. Closing as duplicate.
