### ISSUE TITLE
Live-reload gets disabled after reload

### ISSUE THREAD

**Issue by mbrgm** [facebook/react-native#1067]
Whenever I enable live-reload, it gets disabled immediately after the reload took place. Can anyone confirm this problem?

**Comment by dvdhsu** [comment]
Yes, can confirm this happens in 0.4.1.

**Comment by brentvatne** [comment]
Confirmed this, what's happening is that `_liveReload` and `_liveReloadPeriod` are being thrown away on each reload because the devmenu is dealloc'd when a reload occurs - other menu options don't have their state stored in a devmenu class instance variable.

**Comment by brentvatne** [comment]
Closing this as we are tracking it now in the aforementioned pull request! Thanks :smile:
