### ISSUE TITLE
[package manager bug] Changes do not appear on ios/android simulator or physical device - even when reload is initiated

### ISSUE THREAD

**Issue by emmajam** [facebook/react-native#10689]
### Description

react-native run-ios, successfully builds app and starts it on the iOS simulator.
react-native run-android on android av emulator successfully starts the app on the emulator.

However as I make changes to my code they do not appear on either simulator. When I reload with cmd+R the changes are still not shown. 

If I exit out of the simulator and start it back up again, the changes are shown.

### Reproduction

`react-native run-android` || `react-native run-ios` ... make live changes to code, see no change.

### Logs

In the iOS logs I get these errors which I believe to be related. Can't find much information on them online. Any fixes I've found do not work.

<img width="1107" alt="screen shot 2016-11-02 at 12 57 09 pm" src="https://cloud.githubusercontent.com/assets/21029500/19914104/0c5f209e-a0fc-11e6-8195-584b076de220.png">

### Additional Information

* React Native version: 0.36.0
* React Native Cli Version: 1.0.0
* Platform: both
* Operating System: MacOS Sierra 10.12.1
* Xcode version: 8.1
* Android SDK Manager Revision 25.2.2

**Comment by 1mike12** [comment]
I have the same exact problem but on windows 10. Are we supposed to be able to access the localhost:port address and see something like the 1st image in this issue? https://github.com/facebook/react-native/issues/10674

Because if so, when I visit my server at localhost:8081, chrome is perpetually trying to load without seeing a result, ie it never shows the screen "This site can't be reached".

**Comment by emmajam** [comment]
Hmmm. I get that image when I run `react-native start` and browse to the appropriate address.

<img width="306" alt="screen shot 2016-11-02 at 1 51 26 pm" src="https://cloud.githubusercontent.com/assets/21029500/19915022/8c1257f0-a103-11e6-8a8f-947df2340bdb.png">

**Comment by emmajam** [comment]
@1mike12  what does it say in your terminal when you run `react-native start`?

**Comment by 1mike12** [comment]
Actually, I do see that now and got it working. My issue may not be related to yours after all. I had to do a hack to FileWatcher that other windows folks figured out, https://github.com/facebook/react-native/pull/10690

Maybe you could try that same change and see what happens?

**Comment by emmajam** [comment]
Yeah already tried it. Didn't fix up my issue.
