### ISSUE TITLE
Can't find SDK despite setting ANDROID_HOME, windows 10 

### ISSUE THREAD

**Issue by 1mike12** [facebook/react-native#10687]
### Description

[FILL THIS OUT: Explain what you did, what you expected to happen, and what actually happens.]
Trying to build the initial project by doing
```
react-native init AwesomeProject
cd AwesomeProject
react-native run-android
```
But I get the error saying that environment variable not set, even though It is set

### Reproduction
Set the environment variable 
Verify variable set with `SET`
```
C:\Users\1mike12>SET
ALLUSERSPROFILE=C:\ProgramData
ANDROID_HOME=C:\Users\1mike12\AppData\Local\Android\sdk
APPDATA=C:\Users\1mike12\AppData\Roaming
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
...
```
retstart command prompt

Make the initial project
```
react-native init AwesomeProject
cd AwesomeProject
react-native run-android
```
Get error message 

```
...

Building and installing the app on the device (cd android && gradlew.bat installDebug...
Failed to notify ProjectEvaluationListener.afterEvaluate(), but primary configuration failure takes precedence.
java.lang.RuntimeException: SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROI
D_HOME environment variable.
... 
```

### Additional Information

* React Native version: 
react-native-cli: 1.2.0
react-native: 0.36.0

* Platform: Android
* Operating System: Windows 10

**Comment by emmajam** [comment]
run this from cmd line:
ANDROID_HOME="/usr/local/opt/android-sdk" react-native run-android

**Comment by 1mike12** [comment]
I actually had two problems, and it now works.

1.  I didn't have the right sdk tool version installed. (automatically only installed N sdk tools, but trying to run on a M device

2. I was running `react-native run-android` from the Android studio terminal, which apparently doesn't actually "close" despite the red X button. So it wasn't loading new environment variables I was changing. Had to restart AS.
