### ISSUE TITLE
Cannot use react-native upgrade when app is in sub directory

### ISSUE THREAD

**Issue by LoopIndigo** [facebook/react-native#10692]
### Description

I've been trying to update my react-native version. I've updated the react-native dependency in package.json and I've run `yarn install`.

However, I cannot get `react-native upgrade` to work as my app is in a sub directory (i.e. `android` and `ios` directories are not beside `package.json`). It is a very simple difference, `src/main/javascript/com/company/mobile/apps/app/[ios/android]`.

When I run `react-native upgrade` instead of upgrading my existing files, it creates new `ios` and `android` directories beside package.json.

With some other commands (e.g. `run-[android/ios]`) I can pass a root arg (ios=`--project-path`, android=`--root`). I've been trying to work out how to do that for `upgrade`. The best option I've come across is to create a `rn-cli.config.js` and specify `getProjectRoots()`. This doesn't seem to change the outcome of `upgrade` (even though my config does run, confirmed via logs).

### Reproduction

* Create a new project (i.e. `react-native init`).
* Move the source files (i.e. `android`, `ios`, `index.ios.js`, `index.android.js`, etc) to a sub directory (e.g. `src).
* Try to run `react-native upgrade`.

### Additional Information

* React Native version: 0.35.0, upgrading from 0.32.0
* Platform: both
* Operating System: MacOS

P.S.

I tried posting this question to stackoverflow when I was trying to find some way to pass a root (i.e. not knowing how to do it). But now that I've tried `rn-cli.config.js` I think it might qualify as a bug.

**Comment by MoOx** [comment]
Having the same issue. I can't find a way to "upgrade" with a different project-path that the root folder.
In addition to fixing the bug, I think upgrade command should have a "--project-path" option as well.

**Comment by hramos** [comment]
Minor nit, but this seems like an enhancement request (the functionality is not there) rather than a bug (X is not working as expected).

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.

**Comment by raduflp** [comment]
I found that temporarily moving the .gitignore and .gitattributes files in the subdirectory solved the upgrade issues for me.
