### ISSUE TITLE
[iOS] CameraRoll, 'group_name' is all the same...

### ISSUE THREAD

**Issue by BROUDING** [facebook/react-native#10691]
Okay, so I wanted to sort images by folders so I used 'group_name' parameter in fetchParams as below.

`CameraRoll.getPhotos(fetchParams) .then((data) => this._appendImages(data, changeGallery), (e) => console.log(e));`

in iOS, all the 'group_name' is 'All Photos' even though in my iPhone some picture is in some particular group name.  ex) Facebook_edited >> IMG0302.JPG

in Android, all the 'group_name' is all different as I expected.

Can you guys fix that issue~?

**Comment by lacker** [comment]
Hmm, isn't this just proxying through data from the underlying operating system? Do you get anything different from iOS directly in this situation?

**Comment by christopherdro** [comment]
@facebook-github-bot no-reply

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/ios-cameraroll-groupname-is-all-the-same
