### ISSUE TITLE
react-native run-ios not working after react-native init projectName

### ISSUE THREAD

**Issue by joshterrill** [facebook/react-native#10695]
I just created a new project by typing in `react-native init ReliefMobile`, then I typed `cd ReliefMobile/` and then I typed in `react-native run-ios` to try to run it in an ios emulator as per the docs. This is what I get:

![ReactNativeError](http://i.imgur.com/xWP2pEk.png)

The error on the emulator says something about making sure a node server is running, but I don't remember having to run a seperate node server from an instance of running the emulator. Regardless, I tried to run `npm start` like it says in the root of the `react-native` project, and it threw an error. Here's the log from that:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.10.8
3 info using node@v4.4.7
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle ReliefMobile@0.0.1~prestart: ReliefMobile@0.0.1
6 silly lifecycle ReliefMobile@0.0.1~prestart: no script for prestart, continuing
7 info lifecycle ReliefMobile@0.0.1~start: ReliefMobile@0.0.1
8 verbose lifecycle ReliefMobile@0.0.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle ReliefMobile@0.0.1~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/joshterrill/Projects/relief-os/ReliefMobile/node_modules/.bin:/java/apache-ant-1.9.7/bin:/java/apache-maven-3.2.5/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin
10 verbose lifecycle ReliefMobile@0.0.1~start: CWD: /Users/joshterrill/Projects/relief-os/ReliefMobile
11 silly lifecycle ReliefMobile@0.0.1~start: Args: [ '-c',
11 silly lifecycle   'node node_modules/react-native/local-cli/cli.js start' ]
12 silly lifecycle ReliefMobile@0.0.1~start: Returned: code: 11  signal: null
13 info lifecycle ReliefMobile@0.0.1~start: Failed to exec start script
14 verbose stack Error: ReliefMobile@0.0.1 start: `node node_modules/react-native/local-cli/cli.js start`
14 verbose stack Exit status 11
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:827:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid ReliefMobile@0.0.1
16 verbose cwd /Users/joshterrill/Projects/relief-os/ReliefMobile
17 error Darwin 16.1.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v4.4.7
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error ReliefMobile@0.0.1 start: `node node_modules/react-native/local-cli/cli.js start`
22 error Exit status 11
23 error Failed at the ReliefMobile@0.0.1 start script 'node node_modules/react-native/local-cli/cli.js start'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the ReliefMobile package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node node_modules/react-native/local-cli/cli.js start
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs ReliefMobile
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls ReliefMobile
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

I'm running node version `4.4.7` and npm version `3.10.8` on macOS Sierra 10.12.1.

-----

Edit: I'm going to try to install node version `7.0.0` via nodejs.org, update to the latest version of x-code (i'm one minor version behind), recreate the react-native project, and see if that changes anything.

-----

Edit 2: I am now running node version `7.0.0`, npm version `3.10.8`. I created a new project via `react-native init ReliefMobile`, went into the project and then typed `react-native run-ios`. This is what I get:

![ReactNativeError](http://i.imgur.com/wFAsx5k.png)

When I press on the ReliefMobile app on the phone, the splash screen comes up quickly, then it closes.

So I closed the terminals out and exited out of the emulator, opened up another terminal, and tried it again. And now I'm getting this again, this what I see:

![ReactNativeError](http://i.imgur.com/RWSOyQX.png)

I'm completely stumped.

**Comment by robcalcroft** [comment]
Looks like it can't watch the files properly, do you have [Watchman](https://facebook.github.io/watchman/docs/install.html) installed?

**Comment by joshterrill** [comment]
@robcalcroft That appeared to fix it. Thanks. I don't remember having to install watchman to get it to work previously, but I just saw it as a dependency in the docs. Are people who don't have homebrew installed still able to use this?

**Comment by robcalcroft** [comment]
Ah good. Yep [you can install from source](https://facebook.github.io/watchman/docs/install.html#installing-from-source)
