### ISSUE TITLE
Text - numberOfLines not working 

### ISSUE THREAD

**Issue by sachin-sable** [facebook/react-native#10698]
### Description

I have used Text component with numberOfLines and ellipsizeMode properties. I have even tried this here  : https://facebook.github.io/react-native/docs/text.html . I have tried editing it on the fly. But numberOfLines works only with value = {1} and not with any other numbers. Please advise if I am missing anything here. 

My requirement is to show max 3 lines of text and then truncate it with ellipsizeMode to tail.
Any working example would be appreciated. 

### Code
   `import React, { Component } from 'react';
import { AppRegistry, Text, StyleSheet } from 'react-native';

class TextInANest extends Component {
  constructor(props) {
    super(props);
    this.state = {
      titleText: "Bird's Nest",
      bodyText: 'This is not really a bird nest. Adding long text to see if it truncates after 3 lines and displays the truncation sign properly.'
    };
  }

  render() {
    return (
      <Text style={styles.baseText}>
        <Text style={styles.titleText} onPress={this.onPressTitle}>
          {this.state.titleText}<br /><br />
        </Text>
        <Text numberOfLines={3} ellipsizeMode ={'tail'}>
          {this.state.bodyText}
        </Text>
      </Text>
    );
  }
}

const styles = StyleSheet.create({
  baseText: {
    fontFamily: 'Cochin',
  },
  titleText: {
    fontSize: 20,
    fontWeight: 'bold',
  },
});

// App registration and rendering
AppRegistry.registerComponent('TextInANest', () => TextInANest);`
### Additional Information

* React Native version: 0.35
* Platform: both
* Operating System: Mac OS

**Comment by reneweb** [comment]
I've tested with your example and it does indeed not restrict the lines. The cause is that you have enclosed your text components with another text component (as the root one). If you change the root component from text to view and set the style directly on the nested text component it should all work as expected:

```
import React, { Component } from 'react';
import { AppRegistry, Text, StyleSheet } from 'react-native';

class TextInANest extends Component {
    constructor(props) {
        super(props);
        this.state = {
                titleText: "Bird's Nest",
                bodyText: 'This is not really a bird nest. Adding long text to see if it truncates after 3 lines and displays the truncation sign properly.'
              };
    }

    render() {
        return (
              <View>
                <Text style={styles.titleText} onPress={this.onPressTitle}>
                  {this.state.titleText}
                </Text>
                <Text numberOfLines={3} ellipsizeMode ={'tail'} style={styles.baseText}>
                  {this.state.bodyText}
                </Text>
              </View>
            );
    }
}

const styles = StyleSheet.create({
    baseText: {
      fontFamily: 'Cochin',
    },
    titleText: {
      fontSize: 20,
      fontWeight: 'bold',
    },
});

// App registration and rendering
AppRegistry.registerComponent('TextInANest', () => TextInANest);
```

**Comment by sachin-sable** [comment]
@reneweb Thanks for the Answer. I have tried your code and it works only with restricting to number of lines to {1} and not with any other values. :(

**Comment by nicsefer** [comment]
I have the same issue here.
`import React, { Component } from 'react';
import { AppRegistry, View, Text } from 'react-native';

class FlexDirectionBasics extends Component {
  render() {
    return (
      // Try setting `flexDirection` to `column`.
      <View style={{flex: 1, flexDirection: 'row'}}>
        <View style={{backgroundColor: 'powderblue'}}>
          <Text style={{width:200}} numberOfLines={2} ellipsizeMode={'tail'}>When true, no visual change is made when text is pressed down. By default, a gray oval highlights the text on press down.</Text>
        </View>
      </View>
    );
  }
};

AppRegistry.registerComponent('AwesomeProject', () => FlexDirectionBasics);`

**Comment by reneweb** [comment]
I've tried running my example above using rn 0.35 and 0.36 on ios 10.0 and nexus 5 and for all cases it worked as expected. 
Do you have any settings that could impact this? Might be also worth if you just try it with a fresh project and see if it works then.

**Comment by sachin-sable** [comment]
@reneweb I am still not able to find the solution. It's not even working with the editable examples given here. https://facebook.github.io/react-native/docs/text.html 
Any reason why those examples are not working when set with numberOfLines>1. ?

Thanks.

**Comment by digitalmaster** [comment]
This still doesnt work for me either.
