### ISSUE TITLE
Have to manually run react-native start on Windows each time

### ISSUE THREAD

**Issue by briankabiro** [facebook/react-native#10701]
Can this be added to the code base so that it starts automatically when I run react-native run-android

**Comment by hramos** [comment]
Can you provide more context?

**Comment by briankabiro** [comment]
Sure. 
Can 'react-native start' be bundled with 'react-native run-android/ios' instead of running the commands separately? 
Sort of how "adb reverse tcp:8081 tcp:8081" runs automatically with "react-native run-android"?

**Comment by hramos** [comment]
So this is only necessary on Windows as far as I can tell. Before bundling it with run-*, I guess my question would be *why* this doesn't work on Windows by default.

**Comment by briankabiro** [comment]
Personally I don't know why but I was thinking that if adb reverse could be bundled in, that could too. Preferably it would run after react-native run installs the app on the device

**Comment by briankabiro** [comment]
cc @hramos
