### ISSUE TITLE
ReactNative.I18nManager.localeIdentifier is undefined in iOS

### ISSUE THREAD

**Issue by kfiroo** [facebook/react-native#10709]
### Description

Android exposes `localeIdentifier` constant [I18nManagerModule.java#L48](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/modules/i18nmanager/I18nManagerModule.java#L48)
The iOS versions doesn't seem to expose it resulting in `undefined` [RCTI18nManager.m#L30](https://github.com/facebook/react-native/blob/master/React/Modules/RCTI18nManager.m#L30)

Is this for any specific reason?

* React Native version: 0.36.0
* Platform: iOS

Thanks

**Comment by lacker** [comment]
I doubt it. Do we even document this constant? Doesn't seem like we do. You might want to try using something like https://www.npmjs.com/package/react-native-locale . Anyway I am going to close this issue because we are trying to focus issues on bug reports, but thanks for reporting this!
