### ISSUE TITLE
Error in Props Tutorial

### ISSUE THREAD

**Issue by almadsen** [facebook/react-native#10700]
I'm getting errors from your tutorials at https://facebook.github.io/react-native/docs/

I do the process of "react-native init LotsOfGreetings" then alter the code in the index.ios.js file save and refresh in iOS-simulator and then I get an error:
"Application Greetings has not been registered. This is either due to a require() error during initialization or failure to call AppRegistry.registerComponent."

![skarmavbild 2016-11-02 kl 14 48 29](https://cloud.githubusercontent.com/assets/1423040/19931174/d7cda7b4-a10b-11e6-889f-7b0cd7419cc1.png)

I'm having the same problem with Blink. Can't really figure out what I'm doing wrong here.

* React Native version: 0.36.1
* Platform: iOS
* Operating System: MacOS

**Comment by mattisx** [comment]
Same with first example on: https://facebook.github.io/react-native/docs/animated.html
RN 0.36 (Android)
Error: "Attempted to assign readonly property".
+ a few warnings.

Tested code below:

```
import React, { Component } from 'react';
import {
	AppRegistry,
	StyleSheet,
	Text,
	View,
	Animated
} from 'react-native';

// import Hello from '/views/Hello';

export default class AnimatedTest extends Component {

	constructor(props) {
		super(props);
		this.state = {
			splash: true,
			currentOpacity: new Animated.Value(0)
		}
	}

	componentDidMount() {
		Animated.timing(this.state.currentOpacity, { toValue: 1 }).start();
	}

	render() {
		return (
			<View style={[styles.container, { opacity: this.state.currentOpacity }]}>
				<Text style={styles.titleText}>Hello hello!</Text>
			</View>
		);
	}
}

const styles = StyleSheet.create({
	container: {
		flex: 1,
		justifyContent: 'center',
		alignItems: 'center',
		backgroundColor: '#F5FCFF',
	},
	titleText: {
		fontSize: 20,
		textAlign: 'center',
		margin: 10,
	}
});

AppRegistry.registerComponent('AnimatedTest', () => AnimatedTest);
```

**Comment by hramos** [comment]
@almadsen can you include the exact code snippet that triggered this?

**Comment by almadsen** [comment]
I now created a project with " react-native init Greetings" and put this snippet in the index.ios.js:

import React, { Component } from 'react';
import { AppRegistry, Text, View } from 'react-native';

class Greeting extends Component {
    render() {
        return (
            <Text>Hello {this.props.name}!</Text>
        );
    }
}

class LotsOfGreetings extends Component {
    render() {
        return (
            <View style={{alignItems: 'center'}}>
                <Greeting name='Rexxar' />
                <Greeting name='Jaina' />
                <Greeting name='Valeera' />
            </View>
        );
    }
}

AppRegistry.registerComponent('LotsOfGreetings', () => LotsOfGreetings);

And got the error: "Application Greetings has not been registered. This is either due to a require() error during initialization or failure to call AppRegistry.registerComponent."

I then changed the moduleName in the AppDelegate.m from "Greetings" to "LotsOfGreetings"

Which seemed to do the job for this project.

**Comment by hramos** [comment]
So far it seems like this is working as expected. The `AppDelegate.m` was set up to load the "Greetings" module because that is what you set up when you ran `react-native init Greetings`.

If you, instead, run `react-native init LotsOfGreetings`, I would expect this to work out of the box.

**Comment by hramos** [comment]
For context, the above code was likely taken from the [Props Tutorial](https://facebook.github.io/react-native/docs/props.html).

**Comment by kidphys** [comment]
@hramos @almadsen Should the tutorial be corrected so that the module name is consistent in all sample code?

I encounter the same issue when trying the getting-started tutorial.

**Comment by hramos** [comment]
@kidphys the tutorial covers several small examples, it is not building towards one final app. Using one unique module name would imply all these examples go together in the same app, which would cause other issues.

I will be revisiting the whole tutorial workflow soon, and I will tackle this source of confusion
