### ISSUE TITLE
LayoutAnimation doesn't work

### ISSUE THREAD

**Issue by wzh19960613** [facebook/react-native#10719]
### Description

I have tried all kinds of ways to use the `LayoutAnimation`, but it never worked expected.
Futher more, I think the example and the doc of `LayoutAnimation` hasn't updated for a long time, isn't it

### Reproduction

This is a component should be animated, but it never be animated when the props changed.

#### collapse.js

```

'use strict'


import React, {Component} from 'react';

import {
    View,
    LayoutAnimation,
} from 'react-native';

export class Collapse extends Component {

    setNativeProps(nativeProps) {
      this._root.setNativeProps(nativeProps);
    };

    static defaultProps = {
        collapse: false,
    };

    static propTypes = {
        collapse: React.PropTypes.bool.isRequired,
    };

    constructor(props) {
        super(props);

        this.state = {
            view:[],
        };
    }

    componentWillReceiveProps(nextProps){
        LayoutAnimation.easeInEaseOut();
        this.setState({view: nextProps.collapse ? [] : this.props.children});
    }


    componentWillUpdate() {
        LayoutAnimation.easeInEaseOut();
    }

    render () {

        return(
            <View style = { this.props.style } ref={component => this._root = component} {...this.props}>
                {this.state.view}
            </View>
        )
    }
}

```

### Additional Information

* React Native version: 0.36.1
* Platform: Android 6
* Operating System: Windows

**Comment by nihgwu** [comment]
Please read the doc more carefully, on Android you need to turn on the Experimental to enable LayoutAnimation

**Comment by wzh19960613** [comment]
@nihgwu
OK...I got it...This is my fault.
I suggest that we should add this tip on the page of LayoutAnimation. It will more clearly.
