### ISSUE TITLE
RCTFatal + 104 for any error in the project

### ISSUE THREAD

**Issue by jrmcdona** [facebook/react-native#10713]
Hi All,
Any error I have is ending up in an RCTFatal + 104.   React native version .35.  The project will run fine if there are no errors.  But I can literally remove </View> tag and then Reload the simulator and the crash will hit.     Not only this, but the error screen is all white.  The only way I can see an error is if I select the error row with the mouse and the text turns gray so I can see it.   See screenshot.  Assume two separate issues but its very odd. I am not certain how the project got it this state.     Like I say, no matter what the error it seems like it goes Fatal on me.   Any ideas would be good!

<img width="280" alt="screen shot 2016-11-02 at 7 24 39 pm" src="https://cloud.githubusercontent.com/assets/4327773/19953395/539c2d0a-a13b-11e6-8b09-f605e7b6e58d.png">

**Comment by hramos** [comment]
Can you include a snippet of code? Does this happen on 0.36?

**Comment by brentvatne** [comment]
Please re-create this issue with a repro case and tested on the latest version, if it is still a problem :)
