### ISSUE TITLE
Offsetting RefreshControl on iOS via progressViewOffset

### ISSUE THREAD

**Issue by scarlac** [facebook/react-native#10718]
### Description

An object class check for `RefreshControl` is hard-coded into `ScrollView` making it impossible to offset the pull-to-refresh loader via JS. Tinkering with the `style` prop on `RefreshControl` can cause crashes and strange visual artifacts. A native solution seems the only near-term viable option besides re-implementing everything from scratch.

I have a fix locally to make the Android-only property `progressViewOffset` on `RefreshControl` work on iOS as well.

I will submit a PR as soon as possible. Please reply here if there is any disinterest in resolving this issue by adding iOS support via `progressViewOffset`

### Reproduction

1. Start a project
2. Set up a <ListView> component
3. Add the `refreshControl={<RefreshControl progressViewOffset={-13}/>}` property.
4. Run in iOS simulator
5. Pull-down while list is at top
6. An activity indicator will slowly appear as you pull down.

The indicator does not move according to the `progressViewOffset` property on `RefreshControl`.

### Additional Information

* React Native version: 0.36
* Platform: iOS 10.0
* Operating System: macOS 10.12.1

**Comment by brentvatne** [comment]
This would be nice to have! Looking forward to the PR @scarlac

**Comment by scarlac** [comment]
@brentvatne: Done. Should I include the documentation change in this PR as well?

**Comment by mountainmoon** [comment]
This is a very usefull feature, why it's merged till now ? @scarlac @brentvatne

**Comment by scarlac** [comment]
@mountainmoon Too long time passed so I had to move on. I'm now working on other projects, so I unfortunately don't have the time to fix the issue that was raised by @arsen

If you can fix the issue I think @hramos will be willing to reopen it

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/offsetting-refreshcontrol-on-ios-via-progressviewoffset

**Comment by Bonobomagno** [comment]
Still an issue on 0.55. The workarounds are pretty bad.

**Comment by hramos** [comment]
@Bonobomagno happy to re-open the issue if you are ready to send a PR.
