### ISSUE TITLE
Reload & Live Reload & Hot Reload stop working

### ISSUE THREAD

**Issue by magrinj** [facebook/react-native#10722]
Hi everyone,

I'm block on something really strange, my project stop detect file change and I don't know why because I didn't change anything since the last time I use it.

By example, if I start the packager by running `react-native start` or `npm start` and I change something in my sources files with `hot reload` and `live reload` enabled, nothing change and the packager doesn't detect the change, even if I hit `Command + R` to force reload.
The changes are only applied if I kill the packager and I run it again.

I don't really know from where the problem came, but for this kind of problem I think about `watchman`, so I try to `uninstall` and `install` it again but nothing change, I see some ticket about it, and nothing change with all the steps describe in those tickets.

I also try to restart my computer, and try with a totally new project and with all the following commands:

```
rm -rf $TMPDIR/react-*
watchman watch-del-all
rm -rf ios/build/ModuleCache/* 
rm -rf node_modules/
npm cache clean
npm i
```

But it's still the same...
If someone can help me! :) 

```
react-native-cli -> 1.2.0
react-native -> 0.36.1
xcode -> 8.1
node -> 6.3.1
watchman -> 4.7.0
```

**Comment by ksegla** [comment]
Hi
I had pretty much the same problem. I went through the older issues, found a fix. This SO answer is the most complete about it. It worked like a charm for me. 

http://stackoverflow.com/questions/40274012/react-native-reload-do-nothing

**Comment by magrinj** [comment]
@ksegla Thanks for your answer, but even with this solution it's still the same :/

**Comment by ksegla** [comment]
@magrinj 
Sorry about that. I hope you soon find a fix. Having to restart the package is a real productivity killer

**Comment by miquelfarre** [comment]
@magrinj 
Same happened to me today, 2 days lost. Try to uninstall watchman. 
rm -rf /usr/local/var/run/watchman/ && brew uninstall watchman && brew install watchman

**Comment by magrinj** [comment]
@miquelfarre Thank you very very muck!!!!
I had already try `brew uninstall watchman` and `brew install watchman` but without the `rm -rf` command, now it's working perfectly! 
I lost half a day on it, but thanks to you it's not more :D

**Comment by enisinanaj** [comment]
For those who still have this problem in iOS check that you have the following line in `AppDelegate.m`:
at about the 19th line
```
jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
```

which in case you want to archive the app, should become:
jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
```

```
