### ISSUE TITLE
Android - Text Selection doesn't go away after push route

### ISSUE THREAD

**Issue by zachrnolan** [facebook/react-native#10725]
### Description

![android-select-text](https://cloud.githubusercontent.com/assets/66614/19979913/5408f114-a1b9-11e6-9a0d-f6c94d311e31.png)

The keyboard remains visible and the select text dialog stays on the screen even though it was initiated on the previous screen.

### Reproduction

First screen has a text input that changes a listview below it. Using NavigationExperimental.

1. User types something in TextInput
2. User long presses text within TextInput causing the select text dialog to appear
3. User touches a listview row that takes them to another view
4. Select text dialog still remains on the screen.

### Additional Information

* React Native version: 0.36
* Platform: Android
* Operating System: MacOS

**Comment by brentvatne** [comment]
@ericvicenti - do you think we should dismiss the keyboard if it's open on every route change?

**Comment by christopherdro** [comment]
@facebook-github-bot no-reply

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/android---text-selection-doesnt-go-away-after-push-route
