### ISSUE TITLE
undefined is not an object (evaluating 'this._compo..., stack:)

### ISSUE THREAD

**Issue by fanyuRN** [facebook/react-native#10720]
**description**
Unhandled JS Exception: undefined is not an object (evaluating 'this._compo..., stack:
value@290:1355
value@290:725
unmountComponent@141:3508
unmountComponent@131:419
unmountComponent@141:3555
unmountComponent@131:419
unmountChildren@139:830
unmountChildren@136:2252
unmountComponent@116:361
unmountComponent@131:419
unmountComponent@141:3555
unmountComponent@131:419
unmountComponent@141:3555
unmountComponent@131:419
unmountComponent@141:3555
unmountComponent@131:419
unmountChildren@139:830
unmountChildren@136:2252
unmountComponent@116:361
unmountComponent@131:419
unmountComponent@141:3555
unmountComponent@131:419
unmountChildren@139:830
unmountChildren@136:2252
unmountComponent@116:361
unmountComponent@131:419
unmountComponent@141:3555
unmountComponent@131:419
unmountComponent@141:3555
unmountComponent@131:419
unmountChildren@139:830
unmountChildren@136:2252
unmountComponent@116:361
unmountComponent@131:419
unmountComponent@141:3555
unmountComponent@131:419
unmountComponent@141:3555
unmountComponent@131:419
unmountComponent@141:3555
unmountComponent@131:419
unmountComponent@141:3555
unmountComponent@131:419
unmountChildren@139:830
unmountChildren@136:2252
unmountComponent@116:361
unmountComponent@131:419
unmountChildren@139:830
unmountChildren@136:2252
unmountComponent@116:361
unmountComponent@131:419
unmountComponent@141:3555
unmountComponent@131:419
unmountComponent@141:3555
unmountComponent@131:419
unmountComponent@141:3555
unmountComponent@131:419
unmountComponent@141:3555
unmountComponent@131:419
unmountComponent@141:3555
unmountComponent@131:419
unmountChildren@139:830
unmountChildren@136:2252
unmountComponent@116:361
unmountComponent@131:419
unmountComponent@141:3555
unmountComponent@131:419
unmountComponent@141:3555
unmountComponent@131:419
_updateRenderedComponent@141:6572
_performComponentUpdate@141:6254
updateComponent@141:5531
receiveComponent@141:4634
receiveComponent@131:578
_updateRenderedComponent@141:6489
_performComponentUpdate@141:6254
updateComponent@141:5531
performUpdateIfNecessary@141:4850
performUpdateIfNecessary@131:768
l@128:767
perform@135:503
perform@135:503
B@128:2005
closeAll@135:1142
perform@135:590
batchedUpdates@217:456
s@128:1039
u@224:69
enqueueSetState@224:1050
setState@67:323
handleChange@384:4453
c@388:734
o@621:79
t@366:608
<unknown>@366:281
value@81:1271
value@35:3130
<unknown>@35:1292
y@35:599
value@35:1264

(null)
((
	0   CoreFoundation                      0x0000000182ce41d8 <redacted> + 148
	1   libobjc.A.dylib                     0x000000018171c55c objc_exception_throw + 56
	2   CoreFoundation                      0x0000000182ce4108 <redacted> + 0
	3   aggron                              0x10006e240 aggron + 451136
	4   aggron                              0x100068f94 aggron + 429972
	5   CoreFoundation                      0x0000000182cea160 <redacted> + 144
	6   CoreFoundation                      0x0000000182bddc3c <redacted> + 284
	7   CoreFoundation                      0x0000000182be26ec <redacted> + 60
	8   aggron                              0x10006c808 aggron + 444424
	9   aggron                              0x10008f9f0 aggron + 588272
	10  aggron                              0x10008f3a0 aggron + 586656
	11  libdispatch.dylib                   0x0000000181b6d200 <redacted> + 24
	12  libdispatch.dylib                   0x0000000181b6d1c0 <redacted> + 16
	13  libdispatch.dylib                   0x0000000181b7b444 <redacted> + 928
	14  libdispatch.dylib                   0x0000000181b709a8 <redacted> + 652
	15  libdispatch.dylib                   0x0000000181b7b940 <redacted> + 360
	16  libdispatch.dylib                   0x0000000181b7d38c <redacted> + 572
	17  libdispatch.dylib                   0x0000000181b7d0ec <redacted> + 124
	18  libsystem_pthread.dylib             0x0000000181d752c8 _pthread_wqthread + 1288
	19  libsystem_pthread.dylib             0x0000000181d74db4 start_wqthread + 4
)

- React Native version: RN 0.35

- Platform: Ios

**Comment by npomfret** [comment]
Is this the same issue https://github.com/facebook/react-native/issues/10635#issuecomment-258281700 ?

**Comment by ide** [comment]
Closing because this is a dupe

**Comment by fanyuRN** [comment]
@ide ,is a dupe?
