### ISSUE TITLE
Closing Modal and showing Alert simultaneously locks up app

### ISSUE THREAD

**Issue by jasonmerino** [facebook/react-native#10727]
### Description

What I did.
 - Had a Modal component visible and attempted to close it and show an Alert at the same time

What I expected to happen
- The Modal component to dismiss as the Alert is being shown

What actually happened
- The app locks up, refreshing the JS bundle doesn't change anything even though it shows the loading bar at the top of the screen.
- No visible error messages in Xcode or in Chrome debugger.

### Reproduction

Sample project with reproduction case is here: https://github.com/jasonmerino/ModalAlertCombo

### Additional Information

* React Native version: 0.36.0
* Platform: iOS only (simulator and iPhone) (the same code works on Android)
* Operating System: MacOS

----------------------------------

I've done a little debugging on my end and it looks like the issue is with the presenting controller that the Alert is being attached to. When you set a timeout to Alert after the Modal has been fully removed the `RCTPresentedViewController`method returns the `UIViewController` rather than the `RCTModalHostView`.

Not sure why it's functioning as it does, it doesn't crash or anything. It just locks up and the app is unusable.

**Comment by nihgwu** [comment]
dup of #10471

**Comment by jasonmerino** [comment]
Closing in favor of #10471
