### ISSUE TITLE
[Android] Impossible to scroll WebView inside a ScrollView that is already in scroll mode

### ISSUE THREAD

**Issue by ksegla** [facebook/react-native#10723]
### Description
[I did go through earlier issues and this is not what is depicted in Issue #4773]
I have a WebView inside a ScrollView. The WebView has a height and everything goes well (scrolling and all) 

```
<ScrollView style={{flex:1}}>
 
	<View> ... </View>  
         
	<WebView
		...
		style={{height:heightValue}}
	/> 

</ScrollView>
```

till the view above in the example have to display information that take more space. The scrolling of ScrollView then kicks in and deny WebView its Code-Given right to scroll :).

### Reproduction

```
 heightValue = 1000 // putting 100 will let the Webview scroll normally.

  <ScrollView style={{flex:1}}> 

	<View> <Text> Viewtiful </Text> </View>  
         
	<WebView
		source={{uri: 'www.reddit.com'}}
		style={{height:heightValue}}
	/> 

  </ScrollView>
````

### Additional Information

* React Native version: 0.34.1
* Platform: Android
* Operating System: Windows

**Comment by feisan** [comment]
@ksegla 

Did it work if you disabled the scroll within ScrollView?

```
<ScrollView scrollEnabled={false}> 
	<View> <Text> Viewtiful </Text> </View>  
         
	<WebView
		source={{uri: 'www.reddit.com'}}
		style={{height: heightValue}}
	/> 
</ScrollView>
```

**Comment by ksegla** [comment]
hi @feisan 
I just saw this. 
Yes, it works like that. Problem is I do need the scroll of ScrollView. I have another view  just after the webview which would have no chance of being seen if the scroll is disabled. 
In any case, thanks for the answer. I didn't think of that. The Webview not scrolling is worse than the 3rd view not showing. So I'll go with disabling the scroll while waiting for a solution to my problem.

**Comment by creativefull** [comment]
:+1:

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/android-impossible-to-scroll-webview-inside-a-scrollview-that-is-already-in-scro

**Comment by ryanzzff** [comment]
This issue still exists on Android.

React Native version: 0.44.2

**Comment by FuadBalashov** [comment]
Can we reopen this issue?
* I am seeing it with android on RN 0.49.3
* I do not have any other information to add to the original post but can respond to specific questions.
* I have not seen a PR already implementing this

**Comment by hramos** [comment]
I'd prefer if a new issue was opened, since we've added a new template with additional requirements since this issue was originally filed.
