### ISSUE TITLE
[RN 0.36] NetInfo.isConnected.addEventListener does not fire each time 

### ISSUE THREAD

**Issue by sylvain75** [facebook/react-native#10728]
Hi,
I am building a Network alert message using NetInfo. I test that on the simulator (ios10) by switching on/off the wifi.
It seems that my listener does not fire all the time when the connection changes.
May that come from how fast I toggle the wifi ?

```
componentWillMount() {
    NetInfo.isConnected.addEventListener(
      'change',(isConnected) => {
        console.log("isConnected......?", isConnected);
      }
    );
  }
```
I've also experienced the same issue if I set up the listener in ```componentDidMount```.

**Comment by brentvatne** [comment]
Can you provide more detail? How often does it not happen? Does it happen on device or just simulator? Is there any pattern to it? Does it happen when you only change it quickly or even if you wait?

**Comment by sylvain75** [comment]
Thanks for answering me.
It happens 20% of the time. There is no real pattern.
It can happen when I wait or not.
Only tested on simulator.
I know that does not help that much but if I have more to dig a bit more I let you know

**Comment by gre** [comment]
I can definitely reproduce this. on simulator and on phone.
If you are fast enough, you can disable/enable wifi and the "wifi" event don't comes.
I think it happens if you enable wifi **before** the network="none" even happened.

**Comment by gre** [comment]
I'm more talking about `NetInfo.fetch()` , but both are related.

**Comment by gre** [comment]
even if you setInterval "pull" `NetInfo.fetch()` it's still saying `"none"` even if I put wifi back. It's a dead end until you disable network again. and back one (without being too fast^^)

( in my company app, we have lot of users reporting they see "no internet connection" banner when they use mobile edge. even if they get network again. So I'm pretty sure it's not just simulator )

**Comment by sylvain75** [comment]
@gre  Thanks, I have the feeling not being alone anymore;)

**Comment by devbriguy** [comment]
I'm also experiencing this on simulator (iOS 10). I add the event listener at the top level parent and it only registers the 1st connectivity change and then nothing after. I do not remove the listener in the event listener handler.

**Comment by jpapillon** [comment]
We are also experiencing the exact same thing.

**Comment by devbriguy** [comment]
I just want to report that I am able to receive connectivity changes when running on iOS device.

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
