### ISSUE TITLE
Multiples Components best practices: sharing bridge?

### ISSUE THREAD

**Issue by finalquest** [facebook/react-native#1073]
Hi again.
The context first:

Im using RN as the V in MVC. I've created a JS with a RN component, created a UIView in the obj-c side, and use a RCTRootView (initWithBridge) as a subview.
Everything works fine.

Now the question.
Suppose that I have a two RN components, in two JS files (DetailView.js, SomeOtherView.js).
Is there a way to make a single JS file with the 2 components, so I can use only one bridge and share it. I dont really understand how can I achieve this, and use initWithBridge: moduleName:

Sorry if is a super noob question.
Thanks and regards

**Comment by nicklockwood** [comment]
Yes, you can create the bridge using

    RCTBridge *bridge = [[RCTBridge alloc] initWithBundleURL: moduleProvider: launchOptions:];

Then store that in a property somewhere (e.g. in your AppDelegate), and whenever you need to create a root view, say:

    RCTRootView *rootView = [[RCTRootView alloc] initWithBridge: moduleName:];

That way the JS code bundle is shared, and each root view runs its own component.

**Comment by finalquest** [comment]
Hi. thanks for the response.
What I dont really get it yet is how I can put multiple JS files in one single bundle?
Where every JS file is an independent component

**Comment by ssssssssssss** [comment]
Please see these two issues, it should address your previous question. 
Best practice to integrate existing app with React-Native #995
Forcing view refresh #1049

**Comment by brentvatne** [comment]
@finalquest - `react-native bundle` will do that for you, if you have any questions that aren't answered by this thread or the issues that @ssssssssssss mentioned let me know, closing until then

**Comment by dolmens** [comment]
hey guys, if i take it correctly, if i want to share the same bridge, then i need to bundle all the js files/functions to a big `bundle`, right? is there a way that i can still share the bridge but download every module every single time?

**Comment by brentvatne** [comment]
@dolmens - what's your use case?

**Comment by dolmens** [comment]
@brentvatne say i choose to place the js bundle on server side, and i have many react views, named v1, v2, ..., etc., corresponding to js module m1, m2, ..., etc., and i want to download these modules on demand, in other words, i don't download them only until i show the corresonding views.

**Comment by brentvatne** [comment]
@dolmens - Ah, interesting. As far as I know, this is not supported at the moment

**Comment by tadeuzagallo** [comment]
Yeah, @brentvatne is right, it's not possible yet... The bridge holds where to require the javascript bundle, the RootView just knows which module to require, but it has to be previously loaded by the bridge.

**Comment by grittymindy** [comment]
@brentvatne can you give some more details about how to put multiple JS files into a single bundle, using react-native bundle?
