### ISSUE TITLE
Single frame GIF with resizeMode="contain" not rendering on Android.

### ISSUE THREAD

**Issue by owcs** [facebook/react-native#10733]
### Description

Loading a single frame GIF from network and attempting to display it with resizeMode="contain" causes the image not to render.

### Reproduction

Sample app loading a GIF from network and attempting to display it with resizeMode="contain": https://rnplay.org/apps/e3sSDA

### Additional Information

* React Native version: 0.36.1
* Platform: Android
* Operating System: MacOS

**Comment by brentvatne** [comment]
cc @tyronen

**Comment by brentvatne** [comment]
erm @owcs - it seems to work for me? 

<img width="1265" alt="screen shot 2016-11-06 at 10 15 18 am" src="https://cloud.githubusercontent.com/assets/90494/20040330/efff45da-a409-11e6-90ba-1ec3362b6fd8.png">

**Comment by brentvatne** [comment]
@owcs - indeed contain works for gifs with multiple frames: https://rnplay.org/apps/WJj35g

I don't think this will be highly prioritized by React Native or Fresco teams as this is a pretty obscure edge case (please don't use single frame gifs, why?? :P), so if you want to try your hand at a fix that would be welcome.

**Comment by owcs** [comment]
@brentvatne The single frame GIF support is a requirement by the client. Will try to persuade the client to drop that requirement.

**Comment by brentvatne** [comment]
Seems better to just use png. It compresses a lot better than gifs.

**Comment by dasblitz** [comment]
I just faced the same problem. In my case the gifs come from a cms that I have little influence on and are already being used in other places too. I am agreeing with your arguments as to why png is a better choice than gif, so at least this gives me some leverage to get it changed :) 

Maybe it's good to mention this in the Image docs somewhere. Took some searching before I got here and found what caused this.

**Comment by wilomgfx** [comment]
Indeed not working on android, but as @brentvatne  suggested, lets go for a png :P

**Comment by vvvsrx** [comment]
So long has not solved this problem

**Comment by vvvsrx** [comment]
Share my solution:
use [react-native-photo-view](https://github.com/alwx/react-native-photo-view)

```javascript
{Platform.OS === "android"
            ? <PhotoView
                  style={{
                    width: 100,
                    height: 100
                  }}
                  source={{
                    uri: "https://abc.com/a.gif"
                  }}
                  androidScaleType="fitCenter"
                />
            : <Image
                style={{
                    width: 100,
                    height: 100
                }}
                source={{
                  uri: "https://abc.com/a.gif"
                }}
                resizeMode={"contain"}
              />}
```

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/single-frame-gif-with-resizemodecontain-not-rendering-on-android

**Comment by wilomgfx** [comment]
Inactive for a while, but still no fix.

_Sent from my Lge LG-H873 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by hramos** [comment]
As far as I can tell, no one is working on a fix.

**Comment by dracudakid** [comment]
Noone working on a fix @@
