### ISSUE TITLE
Component is taking time to load

### ISSUE THREAD

**Issue by pardeepbeniwal** [facebook/react-native#10737]
Hi All,
I am using 'Navigator' and rendering multiple component by route. I want to show loader (like any image or text 'Loading...') before render to component because those are taking time to load. Pleaes review my code and suggest me where should I use loader.
navigatorRenderScene(route, navigator) {
    _navigator = navigator;  
    switch (route.id) {		
       case 'Home':
        return (<Home navigator={navigator} title="Home"/>);
       case 'Tomo':
        return (<Tomo navigator={navigator} title="Tomo"/>);
      case 'Profile':
        return (<Profile navigator={navigator} title="Profile" />);
    }
  }

Thanks in Advance

**Comment by ide** [comment]
@facebook-github-bot stack-overflow
