### ISSUE TITLE
setTimeout(..., 0) doesn't work in 0.4.1

### ISSUE THREAD

**Issue by mikelehen** [facebook/react-native#1074]
I just followed the [Getting Started guide](https://facebook.github.io/react-native/docs/getting-started.html#content) and got react-native module version 0.4.1.

And for some reason, if I put this in my index.ios.js:

    setTimeout(function() {
      console.log('setTimeout!');
    }, 0);

I never get the console log, but if I change the timeout from 0 to 1, then I do.  This breaks one of the modules I was trying to use.

**Comment by brentvatne** [comment]
If you downgrade to 0.4.0 does it work for you?

**Comment by mikelehen** [comment]
Yes, looks like it works with 0.4.0 but not 0.4.1

**Comment by brentvatne** [comment]
Thanks!

**Comment by nicklockwood** [comment]
cc: @tadeuzagallo

**Comment by tadeuzagallo** [comment]
Yes, it was a regression, I'm sorry about the inconvenience. I'm working on fixing it right now.

**Comment by brentvatne** [comment]
[This works fine now](https://rnplay.org/plays/pALAlg?autoplay=true)
