### ISSUE TITLE
[RN 0.36.0] onLayout is returning 0 for view drawn in NavigationCardStack

### ISSUE THREAD

**Issue by robclouth** [facebook/react-native#10743]
[0a9b6be](https://github.com/facebook/react-native/commit/0a9b6bedb312eba22c5bc11498b1cc41363e5f27) (I'm guessing) has caused ```onLayout``` to return 0 for views returned in ```renderScene``` in a ```NavigationCardStack```. 

```
return (
  <View onLayout={e => console.log(e.nativeEvent.layout.height)}>
    <View style={{height: 100}} />
  </View>
)
```

This prints 0. In 0.35.0 it prints 100. Using ```onLayout``` inside ```NavigationCardStack``` is important for iOS style dynamically resizing settings popovers.

What's happening here?

**Comment by robclouth** [comment]
```
return (
  <View  style={{height: 100}} onLayout={e => console.log(e.nativeEvent.layout.height)}>
  </View>
)
```
returns 100. It seems to be ignoring children in the size computation.

**Comment by hramos** [comment]
cc @ericvicenti

**Comment by ide** [comment]
There have been quite a few changes to the layout implementation, perhaps the root cause is somewhere in there? cc @emilsjolander

**Comment by brentvatne** [comment]
Is this iOS or Android @robclouth? Does adding `collapsable={false}` to the container fix it? What if you add a width to the inner view?

**Comment by darkamenosa** [comment]
I faced the same issue. This happened on iOS (i don't check on android). 
@brentvatne I added collapsable={false}, but it doesnot work. Here is my code: 

`   <ScrollView
        ref="scrollview"
        contentOffset={{
          x: this.state.width * this.state.initialSelectedIndex,
          y: 0,
        }}
        style={[styles.scrollview, this.props.style]}
        horizontal={true}
        pagingEnabled={true}
        bounces={!!this.props.bounces}
        scrollsToTop={false}
        onScroll={this.handleHorizontalScroll}
        scrollEventThrottle={100}
        removeClippedSubviews={true}
        automaticallyAdjustContentInsets={false}
        directionalLockEnabled={true}
        showsHorizontalScrollIndicator={false}
        showsVerticalScrollIndicator={false}
        onLayout={this.adjustCardSize}>
        {this.renderContent()}
      </ScrollView>`

**Comment by darkamenosa** [comment]
Fixed!!! 
I wrapped the `ScrollView` by a `View` tag. Adding `style={{flex: 1}}` to the `View` tag solved the problem. :D :D

**Comment by ericvicenti** [comment]
Maybe the change in layout behavior means we need to change the `styles` of NavigationCardStack?

**Comment by robclouth** [comment]
@darkamenosa that's not the same issue. My component has the correct height when rendered, but onLayout reports a height of 0.

**Comment by robclouth** [comment]
Ok super weird, if I don't render the header onLayout in the children returns the correct height.

**Comment by robclouth** [comment]
Nope spoke too soon. I have listerally no ideas what's happening. Something has changed in either the layout code, NavigationCardStack or something and it's broken my code. Probably not a RN bug. I'll figure it out eventually.

**Comment by robclouth** [comment]
Ok if I set the component rendered in ```renderScene``` to ```position: absolute``` it measures the children correctly. What changed in 0.37.0 to cause this?

**Comment by ericvicenti** [comment]
@emilsjolander has been working on evolving RN's layout system, and might know more about this. Was this an intentional breaking change, or is it a bug?

**Comment by robclouth** [comment]
Yup, some layout stuff relating to ScrollViews and flex is listed as a breaking change in the release notes. I just couldn't figure out how this was related since I wasn't using either. I've resolved this on my end now and don't have time right now to look into it deeper, so I can close if you wanna clean up that ever growing issues list...

**Comment by ericvicenti** [comment]
Thanks!
