### ISSUE TITLE
NavigationExperimental's NavigationTransitioner will update its state after unmounting

### ISSUE THREAD

**Issue by archgrove** [facebook/react-native#10740]
### Description

We're building an app using `NavigationExperimental`'s `NavigationCardStack`, which itself uses `NavigationTransitioner`. We dynamically generate our cards, which can mean that the routes passed to the card stack "change" even though the content doesn't really alter.

This generally works fine. However, `NavigationTransitioner`'s `componentWillReceiveProps` will trigger an animation if the scenes are not identical before updates. When the animation finishes, the component runs `_onTransitionEnd` which updates the transitioner's `state`. If the transitioner unmounts before the animation ends, this produces the standard `Can only update a mounted or mounting component` warning.

I suspect the way we're generate pages isn't ideal, but that this could occur for any user of the component if they attempt to unmount a transitioner (or its ancestors) shortly after a route update. It can be "fixed" by guarding the state update in `_onTransitionEnd` with a check to see if the component is unmounted, though this feels suboptimal. 

If this is not considered a bug, could I beg some advice on best practice to avoid this? If it is a bug, advice on a better fix so I can create a PR would also be most welcome.

### Reproduction

Attempt to unmount a `NavigationCardStack` shortly after providing it with a `navigationState` containing new routes.

### Additional Information

* React Native version: v36
* Platform: Both
* Operating System: Primary development system is Mac/iOS

**Comment by archgrove** [comment]
Thinking on it, a marginly better method for fixing this may be similar to:

```@@ -101,12 +101,6 @@
     this._onTransitionEnd = this._onTransitionEnd.bind(this);
   }
 
-  componentWillUnmount() {
-    if (this.state.runningAnimations) {
-      this.state.runningAnimations.stop();
-    }
-  }
-
   componentWillReceiveProps(nextProps: Props): void {
     const nextScenes = NavigationScenesReducer(
       this.state.scenes,
@@ -172,18 +166,16 @@
     }
 
     // update scenes and play the transition
-    const runningAnimations = Animated.parallel(animations);
-    this.setState({ ...nextState, runningAnimations }, () => {
+    this.setState(nextState, () => {
       nextProps.onTransitionStart && nextProps.onTransitionStart(
         this._transitionProps,
         this._prevTransitionProps,
       );
-
-      runningAnimations.start(this._onTransitionEnd);
+      Animated.parallel(animations).start(this._onTransitionEnd);
     });
   }
 
-  render(): ReactElement<any> {
+  render(): React.Element<any> {
     return (
       <View
         onLayout={this._onLayout}
@@ -218,25 +210,23 @@
     this.setState(nextState);
   }
 
-  _onTransitionEnd({ finished }): void {
+  _onTransitionEnd(): void {
     const prevTransitionProps = this._prevTransitionProps;
     this._prevTransitionProps = null;
 
-    if (finished) {
-      const nextState = {
-        ...this.state,
-        scenes: this.state.scenes.filter(isSceneNotStale),
-      };
-
-      this._transitionProps = buildTransitionProps(this.props, nextState);
-
-      this.setState(nextState, () => {
-        this.props.onTransitionEnd && this.props.onTransitionEnd(
-          this._transitionProps,
-          prevTransitionProps,
-        );
-      });
-    }
+    const nextState = {
+      ...this.state,
+      scenes: this.state.scenes.filter(isSceneNotStale),
+    };
+
+    this._transitionProps = buildTransitionProps(this.props, nextState);
+
+    this.setState(nextState, () => {
+      this.props.onTransitionEnd && this.props.onTransitionEnd(
+        this._transitionProps,
+        prevTransitionProps,
+      );
+    });
   }
 }```

**Comment by archgrove** [comment]
I rewrote my navigation state route creation code to prevent the underlying problem from my side (we were storing way more in the route than was really needed). I'm no longer confident that this is a bug, as I can't be sure there's any sensible way to trigger it. I leave it open here for people more familiar with the experimental navigation to say.

**Comment by brentvatne** [comment]
Thanks for the detail & follow up @archgrove! I personally wouldn't recommend working with NavigationExperimental directly unless you have extremely specific and custom needs for your app's navigation. I'd personally recommend https://github.com/exponentjs/ex-navigation instead, it's a layer on top of NavigationExperimental that solves a lot of common problems for you.

Pinging @ericvicenti in case this issue is interesting to him, but going to close for now.

**Comment by richardgirges** [comment]
@archgrove would you mind sharing some specifics on how you managed to avoid this issue? We are seeing the same problem: `NavigationTransitioner.onTransitionEnd` is attempting to update the state despite the Transitioner becoming unmounted (we too were utilizing dynamically generated cards in our solution).

We have an extremely customized routing solution in our app that is heavily reliant on `NavigationExperimental` - it would not be practical to adopt a different navigation solution, but we've been dealing with this specific issue for a few days now. I too am not convinced it's a bug, but chalk it up my lack of knowledge on best practices with `NavigationExperimental`, so any information would be helpful.

Cheers

React Native version: v35
Platform: Both
Operating System: OSX
