### ISSUE TITLE
When rotating an app to landscape the statusbar is hidden

### ISSUE THREAD

**Issue by raffij** [facebook/react-native#10751]
### Description

An app loaded in portrait shows the statusbar and when rotated to landscape hides the statusbar. Rotating the app back to portrait shows the statusbar again.
An app loaded in landscape shows no statusbar. When rotated to portrait still shows no statusbar.

### Reproduction

react-native init ProjectName

### Additional Information

* React Native version: 0.36.1
* Platform: iOS
* Operating System: MacOS

**Comment by brentvatne** [comment]
I also noticed this! @lacker - any idea who to assign to?

**Comment by mmmulani** [comment]
does this repro in the UIExplorer or did something change with our initial config settings?

**Comment by raffij** [comment]
@mmmulani yes. It's something wrong in core.

When the following is done it happens.

```
git clone https://github.com/facebook/react-native.git
cd react-native
npm install
open Examples/UIExplorer/UIExplorer.xcodeproj
```

**Comment by mmmulani** [comment]
oh in that case, do you mind running a bisect? I'm a bit swamped with other work and won't get to look at it for a couple days

**Comment by mrpp01** [comment]
I would like to work on this bug. Any idea on how I should approach it?

**Comment by pvinis** [comment]
@mrpp01 just find out when this broke. do a git bisect and find out which commit broke it. that should make it easy to fix, or at least find out why.

**Comment by mrpp01** [comment]
@pvinis I have tried to identify a good version of react native where the error does not exist. But as far as version 0.14.2, the error still exists. I tried to test on older versions, but had not been able to make it run. I doubt that bisect would be helpful as the bug might exist since the beginning. Is there any other approaches that you think I should try?

**Comment by pvinis** [comment]
hm.. then i guess it was not broken. just never worked.. then if you still want to try to fix it, i would suggest to take a look at the statusbar api and the rotation detection for interface and for device api from apple. and maybe you can locate some thing with those.

**Comment by outaTiME** [comment]
Same here with react-native 0.41.

The status bar disappears in landscape mode, check out the dark blue bar on top in second image:

![img_0351](https://cloud.githubusercontent.com/assets/140472/23037431/1241a74a-f465-11e6-90b6-c18c35594d2f.PNG)

![img_0352](https://cloud.githubusercontent.com/assets/140472/23037441/17903b3a-f465-11e6-9d9a-9f722bd5931a.PNG)

**Comment by mzmiric5** [comment]
Is it possible that this happens due to the fact that, since iOS8 UIViewController’s implementation of prefersStatusBarHidden returns YES when its trait collection’s horizontal size class is compact?

> By default, this method returns false with one exception. For apps linked against iOS 8 or later, this method returns true if the view controller is in a vertically compact environment.

https://developer.apple.com/reference/uikit/uiviewcontroller/1621440-prefersstatusbarhidden

**Comment by ferrannp** [comment]
I am using `0.43.0` and this still happens.

**Comment by mzmiric5** [comment]
@ferrannp not sure if this will be resolve on the react-native end, but here is a solution that you can use

In your `AppDelegate.m` add the following lines in your `application didFinishLaunchingWithOptions`

```obj-c
[application setStatusBarHidden:YES withAnimation:UIStatusBarAnimationNone];
[application setStatusBarHidden:NO withAnimation:UIStatusBarAnimationNone];
```

and make sure that `UIViewControllerBasedStatusBarAppearance` is set to `false` in your app's `Into.plist`.

This will cause the status bar to be visible in landscape mode.

Hope this helps.

**Comment by ferrannp** [comment]
@mzmiric5 nice, this works, thank you! Although, I didn't know default behavior of iOS native apps was to hide it on landscape. I guess this could be documented somewhere if we do not want to add it to `StatusBar` but definitely this issue can be closed.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/when-rotating-an-app-to-landscape-the-statusbar-is-hidden

**Comment by jdspugh** [comment]
When rotating an app to landscape the statusbar is hidden. This is happening for me.

react-native: 0.45.1
device: iPhone5

**Comment by lihue** [comment]
Please reopen this bug since it is still not solved.

react-native: 0.46.3
Device iPhone 7

**Comment by hramos** [comment]
There's been several releases since 0.46.3 was cut. If you're still seeing this in master, please open a new issue.

**Comment by rangav** [comment]
This worked for me

```
Dimensions.addEventListener('change', () => {
     StatusBar.setHidden(false);
})
```

**Comment by ou2s** [comment]
I also have this bug on 0.52.1

please reopen the issue @hramos
