### ISSUE TITLE
Added 'react-d3-components' and it broke my app

### ISSUE THREAD

**Issue by jbhatab** [facebook/react-native#1075]
This may just be because the library is for web, but I was trying to use it in conjunction with react-native-svg. That parts fine but the error was peculiar.

![ios simulator screen shot apr 30 2015 11 02 48 am](https://cloud.githubusercontent.com/assets/2458718/7416984/b248ab42-ef28-11e4-9f59-c09ca2345700.png)

**Comment by brentvatne** [comment]
Better suited for the react-native-svg issues :smile: feel free to open there
