### ISSUE TITLE
Problems with documentation, presents an example that contains details that don't work (example also doesn't work)

### ISSUE THREAD

**Issue by smokinjoe** [facebook/react-native#10757]
### Description

There is the example scheme: https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/LinkingExample.js#L72

(linked from http://facebook.github.io/react-native/docs/linking.html specifically)

`<OpenURLButton url={'geo:37.484847,-122.148386'} />`

All my attempts to get this to work failed.  The simulator provided (that uses rnplay) also doesn't work. 

All I want to know is whether `geo:` is a valid scheme to utilize.

My code included:

    var url = 'geo:' + this.props.latitude + ',' + this.props.longitude;
    Linking.canOpenURL(url).then(supported => {
      if (!supported) {
        console.log('JOE: can not:');
      }
      else {
        return Linking.openURL(url);
      }
    }).catch(err => console.error('An error occurred', err));

And I tried defining an array `LSApplicationQueriesSchemes` with a `geo` string value within my plist (as suggested).  I consistently get the _can not_ console.log.

Someone else has run into this here: http://stackoverflow.com/questions/35967139/linking-map-in-react-native

And the answer links directly to the iOS documentation.  So was `geo:` never supported? Is `geo:` something that is provided by the ReactNative layer?  Is there some list where built-in schemes can be researched??

### Reproduction

https://rnplay.org/apps/MI6mnA

Scope out the code in the above link.  On lines 16 and 17 I have the two variants.  One works by bringing up Safari while the other doesn't.

### Additional Information

* React Native version: 0.31
* Platform: iOS
* Operating System: MacOS

**Comment by brentvatne** [comment]
@smokinjoe - I believe that `geo` is only supported on Android -- no built-in apps support it on iOS. And I believe that you can only query about certain url schemes being supported if they are for built-in apps, eg: [sms, tel, mailto](https://developer.apple.com/library/content/featuredarticles/iPhoneURLScheme_Reference/Introduction/Introduction.html).

The documentation referencing geo was added in https://github.com/facebook/react-native/commit/e33e6ab1f0999b3d972344a8ff33f7ee6fd1bb64 -- which made the `Linking` library cross-platform. Could you submit a PR to remove the example from the docs for geo and clarify this?

**Comment by smokinjoe** [comment]
Can do!  Thanks for the response

**Comment by smokinjoe** [comment]
@brentvatne - while fairly small/inconsequential of a change, do you have a wiki or faq with any conventions you want (branch name, commit message details, etc...) for a PR?

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
