### ISSUE TITLE
Debugging "JSON value '443' of type NSNumber cannot be converted to NSString" type errors

### ISSUE THREAD

**Issue by pavlelekic** [facebook/react-native#10762]
I get a bunch of these errors in the app, and I understand that it's some javascript value that should have been a string is sent over the bridge, however, some of these values are generated dynamically, how can I track down where this issue is originating in javascript?

**Comment by brentvatne** [comment]
Can you add a breakpoint to the place where this warning is being called on the native side? There is probably more context available there to help debug the issue.

**Comment by pavlelekic** [comment]
Thanks, that's a good point, but I'm only a js developer. I don't know Objective C, so it's all Spanish to me :(

So there isn't any way other than debugging the Objective C side to figure out what caused the error on the js side?

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
