### ISSUE TITLE
Problem linking Realm

### ISSUE THREAD

**Issue by daninaga** [facebook/react-native#10767]
### Description

I'm trying to link a realm database to use in my project using the instruction given on the tutorial: "react-native link realm", but for some reason it keeps on giving me the error:

rnpm-link ERR! It seems something went wrong while linking. Error: spawn UNKNOWN

### Additional Information

*Realm version: 0.14.3
* React Native version: 0.36.1
* rnpm version: 1.9.0
* Operating System: Windows 7

**Comment by berkaybeyaz1** [comment]
Can you try `rnpm link` ?

**Comment by brentvatne** [comment]
Please post to the Realm repo first, and if it turns out that the bug is with React Native and not the Realm library, then post re-create the issue here with a link to the one that explains why it is not a Realm bug. Thanks!
