### ISSUE TITLE
Huge React-Native (iOS) App size 

### ISSUE THREAD

**Issue by jainmitesh09** [facebook/react-native#10766]
So, I created simple apps for native iOS and R-N iOS integrating some dependent libraries.

To my surprise, the size of native iOS is ~750KB v/s R-N iOS which is 4 MB.

How do I reduce the size of the app ?

**Comment by brentvatne** [comment]
See: https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/AppThinning/AppThinning.html

There is a bit more overhead associated with a React Native app for sure - it provides a bunch of functionality that isn't built into the operating system, so that's to be expected. I wouldn't say 4mb is huge but you can make it smaller using app thinning as mentioned above.

**Comment by jainmitesh09** [comment]
@brentvatne But this is wrt iOS and has nothing to do with R-N. Can we get rid of some modules we dont use before exporting ? 

Does "doing less" section help in reducing app size ?

https://code.facebook.com/posts/895897210527114/dive-into-react-native-performance/

**Comment by jainmitesh09** [comment]
@brentvatne can you please re-open the issue ? Or please direct me to older issue that has addressed this problem with a solution in line with R-N instead iOS.

**Comment by brentvatne** [comment]
@jainmitesh09 - can you try using app thinning as suggested by apple and let me know what the binary size is then? if it can be solved using existing tools there is no need to make any changes to react native

**Comment by jainmitesh09** [comment]
@brentvatne Sure, let me see how I can do that and will let you know the results.

**Comment by jainmitesh09** [comment]
@brentvatne It doesn't help in my case. All I am doing is making a simple iOS and R-N app. R-N iOS app is 1MB in size and native iOS is 31KB. Is there a way I can trim the size down ? And I read online that the difference for Android is way larger. 

How can we reduce the size at the R-N end ?

**Comment by jainmitesh09** [comment]
A request if we can re-open this issue.

**Comment by nihgwu** [comment]
It's interesting you are still asking this, you should know that there are some support libraries needed by RN to work and you can't remove theme, what you can do would be only replace some of them such as fresco with other image library or such on Android 

And if you are still can't bear the size, you can just drop RN and use native entirely. Actually nowadays it's really common that the size of an app is more than 10M or even 100M, why are you still bothering on this. For large scaled app, RN can reduce the size dramatically 

So why not just keep this closed?

**Comment by ide** [comment]
I agree with @nihgwu, 1MB is very small, if you pull in a couple of basic CocoaPods you easily can reach 5MB, let alone 50MB which many apps these days are.

**Comment by jainmitesh09** [comment]
@nihgwu I wish there was a better start-off tone in responding to this.

I am completely in on the fact that it doesn't really matter in the size of 4MB. 

I was sort of doing some size comparisons and was hoping if I could slim down the size in anyway. I am aware of the fact you guys mentioning about the required modules. Not new to the environment.

**Comment by jainmitesh09** [comment]
@brentvatne Thanks though. Appreciate your earlier feedback. You can keep the issue closed.
