### ISSUE TITLE
COULD NOT CONNECT TO REMOTE DEBUGGER ANDROID RN 0.36!

### ISSUE THREAD

**Issue by cinder92** [facebook/react-native#10760]
We use GitHub Issues for bugs.
### Description

After install app into my tablet android (from china) im getting this issue

![screenshot_2016-11-05-01-48-17](https://cloud.githubusercontent.com/assets/4725556/20028244/e1dfc5e2-a2f1-11e6-88ae-4e6c7b94b188.png)

### Reproduction

- Install RN 0.36
- Run project into a real device android 4.4.2
- Reload JS with remote debugg

### Additional Information

* React Native version: 0.36
* Platform: Android
* Operating System: MacOs

**Comment by yezongyang** [comment]
adb devices? or wifi setting

**Comment by brentvatne** [comment]
Hi there! This seems to work as expected, please post to StackOverflow or [read docs about running on your device](https://facebook.github.io/react-native/docs/running-on-device-android.html).

**Comment by cinder92** [comment]
@yezongyang wifi settings in a real tablet android device

@brentvatne  i have done eveything that said in docs but is not working, i'm still receiving this error...
