### ISSUE TITLE
Border can't be applied to <Text> in nested <Text> component

### ISSUE THREAD

**Issue by messense** [facebook/react-native#10775]
### Description

I have a view like:

```jsx
<Text>
  <Text>text 1</Text>
  <Text style={{borderWidth: 1, borderColor: '#4285f4'}}>text 2</Text>
</Text>
```

I want `text 2` to have a border while the whole text in same line or wrap to next line if too long.

**Expected result**

![image](https://cloud.githubusercontent.com/assets/1556054/20044512/8d226444-a4d4-11e6-94cc-f98cf3b39ea5.png)

**Real result**

![image](https://cloud.githubusercontent.com/assets/1556054/20044570/e6f74dc2-a4d4-11e6-9bb0-5875683fcfce.png)

The border didn't show up.

I tried to use `View` to wrap them instead of nested `Text`, border works fine but it can't be layouted the way we want.

![image](https://cloud.githubusercontent.com/assets/1556054/20044611/2dc3fcdc-a4d5-11e6-9898-7696782f7423.png)

### Additional Information

* React Native version: 0.30
* Platform: Only tested on iOS
* Operating System: macOS

**Comment by brentvatne** [comment]
It looks like on Android, Text borders don't work even when not nested.

**Comment by afilp** [comment]
+1

With v0.32, some style properties on nested Text do nothing. For example, I added "padding" and "margin" and nothing happens (while "color" and "background color" works).

**Comment by chitezh** [comment]
Any fix for this yet?

**Comment by rheilgm** [comment]
+1

**Comment by neilzhengzx** [comment]
+1

**Comment by stobasan** [comment]
The solution that worked for me was to change the outer container component to View.
`<View>
      <Text style={styles.textWithBorder}>Lorem ipsum</Text>
      <Text style={styles.textWithBorder}>Foo Bar</Text>
</View>`

**Comment by tofishes** [comment]
unsolved bug in ios with 0.50 version

**Comment by sinhpn92** [comment]
i have same problem too

**Comment by rogchap** [comment]
We're trying to add `borderRadius` which also has no effect.

**Comment by mcarlucci** [comment]
It appears no styles work for nested `<Text>` except for font and font color related css attributes.

**Comment by hramos** [comment]
Nesting a Text component within a parent Text component is not supported. It just happened to work on iOS, but like Brent mentioned earlier this is not supported by Android. Going forward, iOS will no longer allow nesting Text components.

**Comment by tbergq** [comment]
We have an issue regarding this with nested text

![image](https://user-images.githubusercontent.com/7705041/37513392-489c3226-2905-11e8-9084-35c3e75700b1.png)


We would want the icon and size m2 to be wrapped on the same line as `One-Bedrom Apartament with Terrace` 

I guess the only solution for this is to nest text. But then we can no longer style the m2, so the number two appears on the bottom, the alignment of the icon is off. 

Now we have
```
<View style={styles.container}>
      <Text style={styles.title}>{title} </Text>
      <TextIcon style={styles.icon}>&#xe0a6;</TextIcon>
      <Text style={styles.sizeText}> {roomSize}m</Text>
      <Text style={styles.supText}>2</Text>
    </View>
```

change to this breaks styling of styles.icon and styles.supText.

```
<View style={styles.container}>
      <Text>
        <Text style={styles.title}>{title} </Text>
        <TextIcon style={styles.icon}>&#xe0a6;</TextIcon>
        <Text style={styles.sizeText}> {roomSize}m</Text>
        <Text style={styles.supText}>2</Text>
      </Text>
    </View>
```

@hramos Any suggestions how to solve this?

**Comment by hramos** [comment]
I don't have a suggestion other than wrapping this inside a Text is not supported anymore. I know it can be frustrating for people who were depending on this behavior. It was not meant to be used in this manner and moving away from this will allow us to solve more pressing issues with layout. Thanks for your understanding.

**Comment by rogchap** [comment]
@tbergq my solution (which is not ideal, but works for small amounts of text) is to tokenize every word; I.e. `.split(' ')` and then wrap each word in a `View`. Now you can use flex-wrap to display your sentence plus any icons etc.

Please note that this will create a lot of extra Views, which may cause perf issues; but in your use case it should be fine. You could always convert your view to an image if needed.

**Comment by Spoterest** [comment]
No luck, the nested issue still exist on iOS with version 0.55.

**Comment by diegolmello** [comment]
@hramos Any suggestions on how to implement markdown if nested Texts are not supported?
I'm using on my app and it's working fine, but I'm looking for border-radius for mentions.

See last message. `diego.mello2` should have border radius.
<img src="https://user-images.githubusercontent.com/804994/56958694-65f29400-6b21-11e9-96e2-0063af29f97a.png" width="350" />

Is there a better option for implementing markdown than nesting tokens on a root `<Text>`?
Thanks.

**Comment by BettyJJ** [comment]
> Nesting a Text component within a parent Text component is not supported. It just happened to work on iOS, but like Brent mentioned earlier this is not supported by Android. Going forward, iOS will no longer allow nesting Text components.

It is not what the doc says. https://facebook.github.io/react-native/docs/text The doc even gives specific examples about nested test and how to use them.

**Comment by BettyJJ** [comment]
Guys, I found a feature request here: https://react-native.canny.io/feature-requests/p/richer-styling-options-for-nested-text 
Please vote if you also need this improved.

**Comment by diegolmello** [comment]
@BettyJJ I don't think Canny is still relevant.
