### ISSUE TITLE
Intermitent "Network request failed" when request response status is 304

### ISSUE THREAD

**Issue by dabit1** [facebook/react-native#10770]
Hi guys, first of all, great job with React Native!

Last week I had a lot of headaches about a issue related with fetch() calls. I implemented ETag protocol on my fetch() requests but there is a strange error, so if I make a fetch call that returns 304 http status when I reload the app then the same call throw "Network request failed". If I reload again everything is ok, but If I reload one more time again throw "Network request failed", and so on. It seems is related with cache issues, but I can't find the solution.

Many thanks for your help!

David

**Comment by brentvatne** [comment]
Hi there! Please provide a reproducible example that we can clone, it is non-trivial for people to re-create the test case you describe so you're unlikely to get help without it.

**Comment by dabit1** [comment]
Hi! You are right, I'm sorry. I was making code to you and I note that the problem is only in my local server, then this is not a React Native bug. Many thanks and sorry for the inconveniences!!!

**Comment by nikolal** [comment]
@dabit1 

How did you solve this?

**Comment by dabit1** [comment]
@nikolal It was a very strange thing. I had a PHP file of the webservice which was ending with ?>. I removed the PHP close tag and everything worked.
