### ISSUE TITLE
broken link from in docs/GettingStarted.md

### ISSUE THREAD

**Issue by wsaile** [facebook/react-native#10771]
There is a link to an [image](https://github.com/facebook/react-native/blob/master/docs/img/react-native-sorry-not-supported.png) in [docs/GettingStarted.md](https://github.com/facebook/react-native/blob/master/docs/GettingStarted.md) which does not exist at that link or anywhere else in the repository, as far as I can tell.

**Comment by brentvatne** [comment]
cc @hramos

**Comment by hramos** [comment]
The image is at https://github.com/facebook/react-native/blob/master/website/src/react-native/img/react-native-sorry-not-supported.png and is served from https://facebook.github.io/react-native/img/react-native-sorry-not-supported.png when the site is deployed. You can see that it is displayed correctly at https://facebook.github.io/react-native/docs/getting-started.html#content by selecting "Windows" or "Linux" while "iOS" is selected.

You're probably seeing a broken link in the markdown file itself when rendered within GitHub, which is to be expected as the static site has not been generated yet.
