### ISSUE TITLE
[Text] DynamicType ([UIFont preferredFont......])

### ISSUE THREAD

**Issue by crylico** [facebook/react-native#1077]
I've made a simple native module to support DynamicType here: https://gist.github.com/crylico/d24ee57750fadc7e5f95

Are there any plans to integrate DynamicType support into React Native's core or would this be better suited as a "plugin"?

**Comment by nicklockwood** [comment]
It seems like it would make sense to make it a core feature. I'm not sure where it should go though - maybe in the RCTUIManager constants, so it's available globally, but we already jam too much stuff in there :-/

**Comment by nicklockwood** [comment]
Can this value potentially change while the app is running? If not, perhaps we could just bake support for these constants in +[RCTConvert UIFont:] so that they can be used as size values instead of passing numeric sizes.

**Comment by crylico** [comment]
The values /can/ change, but it's a pretty rare thing...Essentially the only way it would change is if the user opened Settings.app and changed their DynamicType there without restarting the app (I believe anyway, haven't done much testing).

This is explained in [Apple's Docs](https://developer.apple.com/library/ios/documentation/StringsTextFonts/Conceptual/TextAndWebiPhoneOS/CustomTextProcessing/CustomTextProcessing.html):

    It’s also important to observe the UIContentSizeCategoryDidChangeNotification so that you can re–lay out the text when the user changes the content size category

**Comment by nicklockwood** [comment]
Yeah, that's pretty much what I figured. I guess we can pass the notification through and let the app decide to re-render or not. I'll think about it.

**Comment by ide** [comment]
In addition to the font sizes, we should expose the font family, weight, etc. since iOS uses subtly different flavors of Helvetica Neue. Basically the entire descriptor if possible.

**Comment by crylico** [comment]
Yeah, I totally agree! The stuff I wrote was just a quick fix, but I'm not sure what the best way to integrate it would be

**Comment by brentvatne** [comment]
@crylico - any interest in following through on this? If so, perhaps turn your gist into a PR and we can give feedback there :smile:

**Comment by crylico** [comment]
Yeah! I'll work on it when I get a chance. I'll likely stick to the current
architecture (as a NativeModule), but exposing more of the font descriptor
for the initial PR. Once all the functionality is there, we can talk about
where it best belongs :)

**Comment by brentvatne** [comment]
@crylico - awesome, looking forward to it :smile:

**Comment by brentvatne** [comment]
@crylico - any updates here?

**Comment by crylico** [comment]
Oh man, I completely forgot about this.  I'd love to put time into it this week - before I begin, do you think a NativeModule is a good solution?

**Comment by nicklockwood** [comment]
Note that since was last discussed this, React Native has gained some support for scalable fonts in the form of RCTAccessibilityManager. It's by no means a complete solution, but worth familiarising yourself with it in case there's some overlap with what you're planning.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/text-dynamictype-uifont-preferredfont

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.

**Comment by sibelius** [comment]
@crylico how can I make the <Text /> to not change the font size when the user enable Dynamic Type?

**Comment by sibelius** [comment]
found the answer here: http://stackoverflow.com/a/35046629/2628278

`allowFontScaling={false}` fix this
