### ISSUE TITLE
#rrggbbaa Color format not working for borderTopColor.

### ISSUE THREAD

**Issue by ggsrivas** [facebook/react-native#10773]
I am trying to use #rrggbbaa formatted color code for borderTopColor property of my view and it's not working. 
e.g. I am using below style,
borderTopColor: "#e8e8e85a" for 35% opacity but it has no effect on opacity. When I use same style for backgroundColor, it works as expected. 
I found this problem on IOS 9.3.

Thanks!

**Comment by brentvatne** [comment]
iOS or Android?

**Comment by ggsrivas** [comment]
I faced this problem on IOS. Haven't tried on Android.
IOS version: 9.3
Device: Iphone 5s.

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
