### ISSUE TITLE
ListView scrolling accessibility

### ISSUE THREAD

**Issue by gibo** [facebook/react-native#10780]
### Description

- Set up a ListView 
- Turn on accessibility
- Swipe to scroll through the list

On getting to the last visible on screen element, swiping stops.

However the expected behaviour would be to scroll to the next ListView item, which would make the ListView scroll.

### Additional Information

* React Native version: 0.36.1
* Platform: iOS
* Operating System: 10

**Comment by mschipperheyn** [comment]
This is not a very clear issue

**Comment by gibo** [comment]
When we reach the last visible list view item, and voice over is turned on, the list view does not scroll.

**Comment by dac09** [comment]
I'm seeing the same issue, with voiceover enabled, swiping right till the last element works, and then the ListView doesn't scroll.

A three finger swipe down does however change to the next page.

Any tips for how to make the ListView scroll when the voiceover highlight reaches the last visible element? I'll try and post a video shortly.

**Comment by dac09** [comment]
Managed to solve it, the solution is to pass in accessibilityTraits to the underlying ScrollView

so for example:

```
<ListView
 renderScrollComponent="{this.renderScrollComponent}"
/>

renderScrollComponent(props){
 return <ScrollView accessibilityTraits="pageTurn"/>
}
```

Hope this helps!

**Comment by RebelliousUno** [comment]
I see the same thing

**Comment by hramos** [comment]
Closing as ListView is deprecated in 0.43. Use FlatList.
