### ISSUE TITLE
[CLI] react-native --help should work outside of a project

### ISSUE THREAD

**Issue by Fahrradflucht** [facebook/react-native#10784]
### Description
react-native-cli (not local-cli) should have a `--help` flag so that `react-native --help` would work outside of a project.

#### Current Behaviour
```
$ react-native --help
You did not pass any commands, did you mean to run `react-native init`?
````

#### Expected Behaviour 
At least this:
```
$ react-native --help

  react-native [options] [command]

  Commands:

  init                 generates a new react-native project

  Options:

    -h, --help             output usage information
    --config [string]  Path to the CLI configuration file
```

The flags that are available seem to be documented [here](https://github.com/facebook/react-native/blob/master/react-native-cli/index.js#L46).

### Additional Information

* React Native version: 0.36.1
* react-native-cli: 1.0.0
* Operating System: MacOS

**Comment by hramos** [comment]
I'm in favor of this, with the caveat that only `init` will be listed in this case as the local-cli wouldn't be available (as you hinted). Do you want to send in a PR?
