### ISSUE TITLE
Can't run react-native run-android

### ISSUE THREAD

**Issue by kfir91** [facebook/react-native#10787]
I opened android emulator 
of android studio,
i installed nodejs, python
i run this:
react-native init AwesomeProject
cd AwesomeProject
react-native run-android

but in react-native run-android

**i got errors:**

* What went wrong:
Execution failed for task ':app:installDebug'.
> com.android.builder.testing.api.DeviceException: java.lang.RuntimeException: N
o connected devices!

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 45.709 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

what to do?

**Comment by gorangajic** [comment]
`No connected devices!`

It's working you just don't have any devices connected to your computer. Start [emulator](https://developer.android.com/studio/run/emulator.html) or connect your android device through USB

**Comment by hramos** [comment]
Check out [Running on Device](http://facebook.github.io/react-native/releases/next/docs/running-on-device.html).
