### ISSUE TITLE
onLayout wrapped in specified Height component is not called when children height change

### ISSUE THREAD

**Issue by Liroo** [facebook/react-native#10785]
### Description

I was able to trigger onLayout view method by modifying his height on older versions but not anymore with this usecase.
```
....
    return (
      <Animated.View style={[this.props.style, { overflow: 'hidden' }, this.state.animatedHeight && { height: this.state.animatedHeight }]}>
        <View style={{overflow: 'hidden'}}>
          <View style={styles.absolute}>
            {this.renderActionsComponent()}
          </View>
          <Animated.View {...this._panResponder.panHandlers}
            onLayout={this._measureContainer.bind(this)}
            style={[{ transform: [{ translateX: this.state.translateX }] }, this.props.style]}>
            {this.props.children}
          </Animated.View>
        </View>
      </Animated.View>
    );
}
...
  _measureContainer({ nativeEvent }) {
    const { width, height } = nativeEvent.layout;
    this.setState({ width, height, animatedHeight: new Animated.Value(height) });
  }
```

Forget most of the code and focus on the `onLayout`. When I modify the children component `this.props.children`, onLayout should be called but it didn't... EXCEPT when the height is reducing...

`onLayout` is called when the children height is reducing but when it is growing.

I think the height of the parent component blocks the expansion of the children 
which suggests to native react that we should not call OnLayout where it would... but it happens only from 0.36.

Is this a bug, is there any way to do this ? It's important for us to maintain our transitions animations !

### Additional Information

* React Native version: 0.36
* Platform: Unfortunately both
* Operating System: MacOS

**Comment by Liroo** [comment]
There is a github repository where is the bug. It's really simple project, there is the index(.ios|.android).js and two files you can find in `src/`
https://github.com/Liroo/react-native-bug-onlayout
You will be able to reduce the height container using children but never to grow up him...

**Comment by Liroo** [comment]
Used LayoutAnimation but there is no actual way to do it so.. manual ?

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
