### ISSUE TITLE
Overflow hidden is broken on android 0.36

### ISSUE THREAD

**Issue by gorangajic** [facebook/react-native#10782]
### Description

Overflow hidden worked on android before as expected and after upgrade to 0.36 it's broken now. Overflow is visible, but it's not consistent sometimes on update `overflow` will work and on initial render will be broken. Also I have noticed if you put `backgroundColor: 'transparent'` it will work fine

Not sure what is changed, because I can't find anything in changelogs that will cause this to broke.

### Reproduction

It's showing like this

<img width="556" alt="screen shot 2016-11-07 at 1 20 43 pm" src="https://cloud.githubusercontent.com/assets/249310/20057671/196ba2e0-a4ed-11e6-8b83-36f4e68a5531.png">

but it should be like this

<img width="556" alt="screen shot 2016-11-07 at 1 22 01 pm" src="https://cloud.githubusercontent.com/assets/249310/20057688/317ca2c6-a4ed-11e6-8e78-1f1adde671e7.png">

```jsx
class OverflowTest extends Component {
  render() {
    return (
      <View style={{ overflow: 'hidden', width: 100, height: 100 }}>
        <Image
          source={{ uri: 'https://placeholdit.imgix.net/~text?txtsize=33&txt=200×200&w=200&h=200' }}
          style={{ position: 'absolute', width: 200, height: 200 }}
        />
      </View>
    );
  }
}
```
https://github.com/gorangajic/react-native-overflow-bug

### Additional Information

* React Native version: 0.36.1
* Platform: Only Android
* Operating System: MacOS

**Comment by Thomas101** [comment]
I'm seeing exactly the same, but thanks for finding the `backgroundColor: "transparent"` fix. That works a treat in the short term!

**Comment by stoffern** [comment]
Related to this: https://github.com/facebook/react-native/issues/3198

**Comment by lacker** [comment]
Closed because this one is a dupe

**Comment by gorangajic** [comment]
Just to note that this worked fine before the update, and it's broken now

**Comment by stoffern** [comment]
@gorangajic I think they know, the FB team are working on a fix that they will opensource soon.
