### ISSUE TITLE
Navigator rerenders scene when switches from it.

### ISSUE THREAD

**Issue by frmrgr** [facebook/react-native#10781]
### Description
When a route is pushed in Navigator, renderScene function is also called for previous view resulting in its rerender.

### Reproduction
[In this example](https://rnplay.org/apps/kTEvAw) it is clearly seen that scene is updated just before sliding left. This should not happen, because render might be quite heavy. As a workaround you can cache view in renderScene:

    route._scene = route._scene || <SomeComponent />
    return route._scene

### Additional Information
* React Native version: 0.36
* Platform: Android, didn't test iOS
* Operating System: All

**Comment by maluramichael** [comment]
Is your navigationbar flickering too?

**Comment by frmrgr** [comment]
@maluramichael I do not use navigationbar.

**Comment by maluramichael** [comment]
Thats too bad because i also noticed that the left button of the previous scene is getting rendered for one frame, then the current left button again and then current button is fading out.

**Comment by mhagmajer** [comment]
I'm getting the same issue. My workaround, however, is based on checking if `navigator.getCurrentRoutes().slice(-1)[0]` equals the route for scene being rendered in its `shouldComponentUpdate`.

It's worth noting that this solution will also prevent re-rendering inactive scenes if their own state changes.

**Comment by ericvicenti** [comment]
Yeah, this is expected with Navigator, which will be deprecated soon. Please consider moving to React Navigation, where this issue is already fixed!
