### ISSUE TITLE
App crashes when I'm trying to open developers menu in simulator, on iPad as target device

### ISSUE THREAD

**Issue by necinc** [facebook/react-native#10793]
### Description

To use whole iPad screen with react-native application I'm setting 'iPad' as target  device to deploy in general settings in xcode. Then after launching app in simulator I'm trying to open developer menu to enable hot/live reload and app crashes.

![target device](https://cloud.githubusercontent.com/assets/8607893/20072080/bb5b60ee-a52f-11e6-8985-9064ea471009.png)

### Reproduction

Repo with prepared default project, with setted iPad as target device
https://github.com/necinc/rn-ipad-bug

### Additional Information

* React Native version: 0.36.1
* Platform: iOS (iPad only)
* Operating System: MacOS

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.

**Comment by rcorrie** [comment]
I'm experiencing this as well

RN 0.46.0
Xcode Version 8.3.3 (8E3004b)
Simulator Version 10.0 (SimulatorApp-745.10) 

![jul-12-2017 11-25-37](https://user-images.githubusercontent.com/6488063/28125545-e4aabaf8-66f4-11e7-8807-3f05d5fda5a3.gif)

**Comment by hramos** [comment]
@rcorrie as this issue is closed, I suggest opening a new issue.

**Comment by rcorrie** [comment]
@hramos no need, restarting the computer fixed this issue 

¯\_(ツ)_/¯
