### ISSUE TITLE
babelHelpers.asyncGenerator.wrap not defined

### ISSUE THREAD

**Issue by arv** [facebook/react-native#10798]
### Description

When adding `transform-async-generator-functions` to `.babelrc` I'm getting an error:

```
undefined is not an object  (evaluating 'babelHelpers.asyncGenerator.wrap')
```

### Reproduction

.babelrc:

```json
{
  "presets": ["react-native"],
  "plugins": [
    "transform-async-generator-functions"
  ]
}
```

Js code:

```js
async function* f() {}
```

According to #4844 this seems to be because RN changes how babelHelpers works?

### Additional Information

* React Native version: 0.36
* Platform: both
* Operating System: macOS

**Comment by ErikCupal** [comment]
The problem is still present. 

- RN version 0.39.2
- transform-async-generator-functions version 6.17.0

**Comment by christopherdro** [comment]
@ErikCupal Still having issues?

**Comment by santiagofm** [comment]
Could you solve this issue @arv  ?

**Comment by arv** [comment]
I didn't. We ended up not using async generators after all.

**Comment by JulioC** [comment]
@santiagofm you can try the solution on https://github.com/facebook/react-native/issues/14933

In my case, using react-native 0.46.x, it was enough to just downgrade babel-preset-react-native to 2.0.0 and running `react-native start --reset-cache`
