### ISSUE TITLE
dso_lock open failed: EROFS (Read-only file system) on JS Context Init.

### ISSUE THREAD

**Issue by lelandrichardson** [facebook/react-native#10799]
### Description

We are getting a lot of crash reports with the following message:

```
Unable to create application com.airbnb.android.AppShell: java.lang.RuntimeException: java.io.FileNotFoundException: /mnt/expand/41f1f1bb-6721-4edd-840d-0df4bd0f9428/user/0/com.airbnb.android/lib-main/dso_lock: open failed: EROFS (Read-only file system)
```

We are seeing this at app start, when we are initializing the JS context. This is happening only in production.
The phones we are seeing it on are:
- Android 6.0 or greater
- ~50% of the events are happening on Motorola devices.

It's unclear to me what would cause this to happen. I think `dso_lock` is a file that has something to do with the ndk.

### Reproduction

I have not yet been able to reproduce on a device. This is apparently affecting a lot of users though :/

### Additional Information

* React Native version: 0.33
* Platform: Android
* Operating System: Mac OS

**Comment by lacker** [comment]
I feel for you. Can you tell if these bug reports are specific to a small set of countries, or if they are happening all over?

**Comment by christopherdro** [comment]
ping @lelandrichardson

**Comment by lelandrichardson** [comment]
@lacker @christopherdro it appears this crash went away when we upgraded to 0.38... I guess we can close for now. thanks!
