### ISSUE TITLE
Can't close developer menu Android

### ISSUE THREAD

**Issue by jqn** [facebook/react-native#10797]
### Description
I started experiencing a problem when testing React Native Apps on physical devices where the developer menu won't close and stay open. The background seems to flicker.

### Reproduction

Test any React Native app on a physical device. Im using a Samsung  Edge 6 Android version 6.0.1

### Additional Information

* React Native version: 0.31.0 and 0.36
* Platform: Android
* Operating System: MacOS

**Comment by charpeni** [comment]
@facebook-github-bot label Android

**Comment by charpeni** [comment]
Did it occurs on a freshly created project ?

**Comment by jqn** [comment]
It happens with old and new projects, I'm going to try and test it on other physical devices.

**Comment by hramos** [comment]
If this happens on 0.31, I am surprised it hasn't surfaced before. Let us know if it happens on other devices.

**Comment by jqn** [comment]
@hramos I was able to test for this bug on a different device and everything seemed to be working normally. I'm still experiencing the bug on my Samsung Galaxy S6 edge. I could be device related but it would be great to know if anyone else has experienced the same error.

**Comment by jqn** [comment]
I'm closing this issue because it has been inactive for a while. After testing on other several devices I think it's unique to my device.
