### ISSUE TITLE
[Component Idea] sticky navigation bar that scrolls off the top

### ISSUE THREAD

**Issue by ide** [facebook/react-native#108]
A lot of apps (Facebook, Instagram) have a navigation bar that gets pushed off the top as you scroll. This could be a useful component to provide.

**Comment by brentvatne** [comment]
Trying out moving these kinds of discussions over to discuss.reactjs.org - see [the discussion here](https://discuss.reactjs.org/t/react-native-components-that-you-want-to-see/523) - I linked to this issue there.
