### ISSUE TITLE
Unable to start Packager on Mac 10.12.1 and xcode 8.1

### ISSUE THREAD

**Issue by anupkale1984** [facebook/react-native#10801]
Since i updated my MAC OS to 10.12.1 i am unable to start Packager at all.
I tried all available option.
my system has following configuration:
Node: 7.0.0
NPM : 3.10.9
Watchman : 4.7.0
I cleared everything on wtachman. nothing running over there.
i tried npm start or react-native start it gives following error:

` ERROR  Packager can't listen on port 8081
Most likely another process is already using this port
Run the following command to find out which process:

   lsof -n -i4TCP:8081 

You can either shut down the other process:

   kill -9 <PID> 

or run packager on different port.`

* React Native version
react-native-cli: 1.0.0
react-native: 0.34.1
* Platform: Both
* Operating System:  MacOS

**Comment by wv1124** [comment]
lsof -n -i4TCP:8081
kill -9 <PID>
restart
