### ISSUE TITLE
ScrollView override onLayout() on Android result in the ViewPager in ListView can not scroll smoothly

### ISSUE THREAD

**Issue by doubleDdai** [facebook/react-native#10805]
### Description

I have an tabhost filled with fragments on Android, one fragment of it has a listview which has a viewpager as a cell.

When  I switch to anoth fragment,and then switch back, the viewpager can not scroll smoothly.

I tried to figure out, and I found that an variable in ViewPager named "mFirstLayout" was setted to "true" while the onAttachedToWindow() is called. "mFirstLayout" should be setted to "false" when the method onLayout() is called. But ReactScrollView overridding onLayout method calls the onLayout() in ViewPager not called.

Because "mFirstLayout" is true, the method "setCurrentItemInternal" in ViewPager does not call smoothScroll to next position.

**Comment by charpeni** [comment]
Can you provide some code samples ?

**Comment by doubleDdai** [comment]
@charpeni 
`
render() {
    if (this.state.dsItems) {
            return (<ListView
                removeClippedSubviews={false}
                refreshControl={refresh}
                dataSource={this.state.ds.cloneWithRowsAndSections(this._genRows({}))}
                renderRow={this._renderRow.bind(this)}
                onEndReached={this._toEnd.bind(this)}
                onEndReachedThreshold={10}
                showsVerticalScrollIndicator={false}
                automaticallyAdjustContentInsets={false}
                renderFooter={this._renderFooter.bind(this)} 
                />)
        }
}

_renderRow(rowData, sectionID, rowID, highlightRow) {
        if (sectionID == 0) {
            if (defaultFunNum == 2) {
                return this._showPageScrollView(sectionID, rowID, rowData);
            }
            else {
                return this._showFunctionView(sectionID, rowID, rowData);
            }

        }
}

_showPageScrollView(sectionID, rowID, rowData) {
        return <KIDPageScrollView key={`${sectionID}_${rowID}`}
            style={styles.KIDPageScrollView}
            itemArray={rowData.figure} />
 }

`

KIDPageScrollView
`

const properties = {
      style: styles.wrapper,
      showsButtons: false,
      height: screenWidth,
      autoplay: false,
      autoplayTimeout: 5.0,
      dot: dot,
      activeDot: activeDot,
      paginationStyle: {bottom: 10}
    };

return (
        <Swiper {...properties}>
          {itemViews}
        </Swiper>
    );
`

**Comment by hramos** [comment]
Closing as ListView is deprecated in 0.43. Use FlatList.
