### ISSUE TITLE
Applying borderRadius to <Text> ignores backgroundColor

### ISSUE THREAD

**Issue by albinhubsch** [facebook/react-native#10807]
### Description

Applying a borderRadius to a <Text> element with a border and a backgroundColor only affects the actual border. The backgroundColor stays square. If this is intended behaviour the documentation has to be changed cause it says <View> style applies to <Text> aswell [Text Style](https://facebook.github.io/react-native/docs/text.html#style) but this behaviour does not appear to a <View> element.

example
`<Text style={{ backgroundColor: '#f008', borderWidth: 1, borderColor: '#000', borderRadius: 12, padding: 8 }}>Test text</Text>`

produces
![image](https://cloud.githubusercontent.com/assets/4778987/20091121/63c746d8-a591-11e6-9225-483021273f7a.png)

according to my expectations, backgroundColor should be rounded corners aswell?

### Reproduction

Try this snippet to reproduce.
`<Text style={{ backgroundColor: '#f008', borderWidth: 1, borderColor: '#000', borderRadius: 12, padding: 8 }}>Test text</Text>`

### Additional Information

* React Native version: 0.36
* Platform: iOS, don't know about Android
* Operating System: MacOS

**Comment by steida** [comment]
Try overflow="hidden", it should help.

**Comment by christopherdro** [comment]
@facebook-github-bot answered

**Comment by stoffern** [comment]
Works on iOS not on Android.
Android has a issue on it here: https://github.com/facebook/react-native/issues/3198

as @christopherdro said: answered
this can be closed @albinhubsch @hramos 😉

**Comment by Gentlee** [comment]
@stoffern why this issue is closed if it is not fixed? It should work without hacks with overflow, same as for usual `View`. Should be reopened and fixed.

**Comment by neiker** [comment]
@hramos why this is closed? still a bug

**Comment by hramos** [comment]
See [above](https://github.com/facebook/react-native/issues/10807#issuecomment-302374921):

 <img width="322" alt="screen shot 2018-03-14 at 2 51 09 pm" src="https://user-images.githubusercontent.com/165856/37432876-2880109e-2797-11e8-8782-092ac3b67ae9.png">

Please open a new issue if this affects you.

**Comment by neiker** [comment]
I do not understand the logic behind this, a workaround not means to solved bug.

/cc @hramos

**Comment by stoffern** [comment]
As i Wrote: 

> Works on iOS not on Android.
> Android has a issue on it here: #3198
> 
> as @christopherdro said: answered
> this can be closed @albinhubsch @hramos 😉

Please refer to the original issue #3198

**Comment by neiker** [comment]
wat

**Comment by hramos** [comment]
Please open a new issue.
