### ISSUE TITLE
This method is not supported for ReactViewGroup instances

### ISSUE THREAD

**Issue by chichengjunma** [facebook/react-native#10806]
This method is not supported for ReactViewGroup instances
setBackground
ReactViewGroup.java:133

When I integrate React Native pages into Android Native Fragment Component,app crashed above 5.0 system！

    private ReactRootView mReactRootView;
    private ReactInstanceManager mReactInstanceManager;

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
            mReactRootView = new ReactRootView(mContext);
            mReactInstanceManager = ReactInstanceManager.builder()
                    .setApplication(getActivity().getApplication())
                    .setBundleAssetName("index.android.bundle")
                    .setJSMainModuleName("index.android")
                    .addPackage(new MainReactPackage())
                    .setUseDeveloperSupport(BuildConfig.DEBUG)
                    .setInitialLifecycleState(LifecycleState.RESUMED)
                    .build();
            mReactRootView.startReactApplication(mReactInstanceManager, "XXX", null);
        return mReactRootView;
}

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
