### ISSUE TITLE
ListView scroll postion is below last element

### ISSUE THREAD

**Issue by forki** [facebook/react-native#10810]
With react native v.30 up to v.36 we observe the following:

We use a ListView in the same react native page but change the data rather often. Sometimes if the user scrolls down the list and the data changes the newly rendered ListView keeps the scrollposition. Usually that is a good thing, but in our case this means the ListView is scrolled below the last element of the newly rendered ListView. Scrolling up manually works, but we think it should detect this case and automatically scroll to the top.

/cc @jayp33

**Comment by hramos** [comment]
Closing as ListView is deprecated in 0.43. Use FlatList.
