### ISSUE TITLE
Service keeps Activity alive

### ISSUE THREAD

**Issue by jankalfus** [facebook/react-native#10814]
### Description

I'm using a permanently-running Android Service in my React Native app. With React Native 0.35, there is a problem that the Activity is not terminated when closed (open task manager and swipe away). It keeps running and is not freed from memory. So when the Activity is opened next time, it starts much faster, but React Native is initialized incorrectly. I get "cannot change status bar when not attached to an Activity" warnings, the app slows down, I get multiple warnings from Redux saying that keys in Store already exist etc. From logging, I could see that `onPause `and `onDestroy` were being called. However, the Activity does not terminate after that. This does not happen when using React Native 0.32. With v0.32, it shuts down correctly.

### Reproduction

Create an Android Foreground Service, start it on first launch of Activity. Close the Activity from task manager. Open the app and you can see that it starts much faster than during the first run. This is because it is not terminated correctly.

### Additional Information

* React Native version: 0.35
* Platform: Android
* Operating System: Windows (unrelated)

Update: Still happens with React Native v0.37

**Comment by jankalfus** [comment]
Still happens with React Native v0.37

**Comment by lacker** [comment]
Is this actually a bug? I am not sure what component of the system is supposed to be committing to not shutting down a foreground service. At least when I check either the RN docs or the Android doc it is not clear to me that services must be shut down in this case.

**Comment by jankalfus** [comment]
It looks like this is caused by some static variable not being cleared up. I ran into a similar issue in a different context and it was caused by a static variable. The problem is that static variables don't get cleared up when the Activity is destroyed as the foreground service keeps them "alive".

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
