### ISSUE TITLE
Packager over-eagerly optimises `require` values

### ISSUE THREAD

**Issue by notjosh** [facebook/react-native#10816]
### Description

I'm trying to use [decimal.js](https://github.com/MikeMcl/decimal.js), which works fine in development. But when running the packager in production mode, it fails with:

```
Unable to resolve module crypto [/path/to]/node_modules/decimal.js/decimal.js: Module does not exist in the module map or in these directories:
[/path/to]/node_modules
```

### Reproduction

```
npm install decimal.js
react-native bundle --dev=false --platform=ios --entry-file=index.ios.js --bundle-output dist/Something.jsbundle --sourcemap-output dist/Something.jsbundle.map --assets-dest dist
```

### Additional Information

decimal.js uses a [relatively naive packager-buster](https://github.com/MikeMcl/decimal.js/blob/fb37ca6bde56676d6d5a98df2bf8721e8fa81085/decimal.js#L4783), but RN is is [folding the constants](https://github.com/facebook/react-native/blob/0b2d5317c419a78f2068437c18a0bf54c0ef325d/packager/react-packager/src/JSTransformer/worker/index.js#L34-L42).

As there's no standard way to omit requires from packagers (that I'm aware of), I've submitted a PR on their side (https://github.com/MikeMcl/decimal.js/pull/42) to thwart the RN packager - but that's a game of cat-and-mouse.

Ideally there'd be an annotation (`/* packager-ignore */` or similar) to prevent this from happening.

As this kind of thing exists in other npm modules also, would it make sense to perhaps remove folding of the constants?

* React Native version: 0.35.0
* Platform: iOS
* Operating System: macOS

**Comment by jonrh** [comment]
Just had this issue myself by having [math.js](https://github.com/josdejong/mathjs) v3.9.2 as a dependency (which relies on [decimal.js](https://github.com/MikeMcl/decimal.js) v5.0.8). Decimal.js has released a fix which makes it compatible with React Native (v7.0.0 and newer).

I created a sample React Native project which demonstrates this issue: <https://github.com/jonrh/react-native-mathjs-bug>. I've created [an issue](https://github.com/josdejong/mathjs/issues/797) in the math.js library asking if it would be possible for them to upgrade their decimal.js dependency, that might solve the problem short-term.

**Comment by ide** [comment]
The packager mandates that all requires are statically available, perhaps that could change in the future (cc @cpojer). In the meantime you could write a custom Babel plugin that removes the requires.

**Comment by jonrh** [comment]
Thanks for the insights @ide, wasn't aware that was the case. As to my own case this issue has [been solved](https://github.com/josdejong/mathjs/issues/797#event-973269447) with v3.9.2 in math.js thanks to the swift response of the maintainers. Thank you all for your brilliant work in the React Native repo!

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/packager-over-eagerly-optimises-require-values
