### ISSUE TITLE
RTL bug with Text component

### ISSUE THREAD

**Issue by alizahid** [facebook/react-native#10812]
### Description

When `I18nManager.forceRTL(true)` to test my RTL app, I came across a bug with the `<Text>` component.

When the app is LTR, multiline text in Arabic renders from right to left, with the subsequent lines starting from right as well.

![ltr-arabic](https://cloud.githubusercontent.com/assets/941775/20099645/018fc160-a5d3-11e6-8ece-c64f18d5c659.png)

However, if the app is RTL, this happens.

![rtl-arabic](https://cloud.githubusercontent.com/assets/941775/20099647/081dc446-a5d3-11e6-8ccf-61729b63152d.png)

I used `flexDirection: 'flex-start'` on the `<Text>` to make it start from the correct side. I tried using `textAlign: 'right'`, but had no luck.

### Reproduction

https://rnplay.org/apps/GfNikw

### Additional Information

* React Native version: 0.36.1
* Platform: iOS
* Operating System: MacOS

**Comment by grmmph** [comment]
+1
@alizahid did you figure out a way around?

**Comment by grmmph** [comment]
Okay obviously when you use `textAlign: right` on an rtl layout, it will flip it around:

https://github.com/facebook/react-native/pull/11035

**Comment by alizahid** [comment]
@grmmph Not for iOS, it doesn't. Look at the RNPlay link. Android works fine, iOS doesn't.

**Comment by grmmph** [comment]
Works great on my ios emulator

**Comment by alizahid** [comment]
@grmmph Did you look at the RN Play demo? What's your environment like? RN version? iOS version?

**Comment by grmmph** [comment]
@alizahid  Did you add this line into you `AppDelegate.m`
`   [[RCTI18nUtil sharedInstance] allowRTL:YES];`

**Comment by grmmph** [comment]
https://facebook.github.io/react-native/blog/2016/08/19/right-to-left-support-for-react-native-apps.html

**Comment by grmmph** [comment]
@alizahid did you managed to figure this out?

**Comment by alizahid** [comment]
@grmmph Yes. There's a `writingDirection` property for `Text` on iOS. I use it like this:

    <Text style={{writingDirection: I18nManager.isRTL ? 'rtl' : 'ltr'}}>مرحبا</Text>

**Comment by grmmph** [comment]
Cool.
I guess this still an issue, because this ideally should be abstracted in the the core `<Text>` component.

**Comment by bluetec** [comment]
iOS uses available languages to set text direction, simply add Arabic language using xCode in project configuration, and text will be rendered in correct direction.

**Comment by philjoseph** [comment]
This is indeed an important issue for all of us implementing RTL localizations.
All the documentation we have is the [great blog from Aug 16'](https://facebook.github.io/react-native/blog/2016/08/19/right-to-left-support-for-react-native-apps.html) from @MengjueW . But this an old article and I would be glad to have a guide in the documentation.

It shall includes @alizahid findings about writingDirection, it shall also clarify (at least for me) if we need to add the native code in AppDelegate.m and in MainActivity.java.

Looking forward to a new piece of documentation regarding RTL, Thanks!

**Comment by grmmph** [comment]
This issue makes me glad we Jews an Arabs finally found a common enemy!

**Comment by philjoseph** [comment]
I do not know how to write in arabic but I remember some good words from my grandma that was a arabic speaker (Jewish tunisian origin): Yatik sah'a @alizahid for the findings. I do believe that all RTL language speakers have true values in common.

**Comment by grmmph** [comment]
Yes. We all get our hands dirty from ink after writing.

**Comment by philjoseph** [comment]
@alizahid & @grmmph Do you have any idea how to resolve #7378 that seems to be very similar to this one but on TextInput ?

**Comment by moerabaya** [comment]
Is this still on?

**Comment by philjoseph** [comment]
We use the workaround suggested by @alizahid that works great for us

**Comment by moerabaya** [comment]
It's not working for some reason, maybe it will work fine in the production?

**Comment by alizahid** [comment]
@philjoseph @moerabaya Does [this](http://alizahid.net/post/157525270196/rtl-support-for-react-native) help?

**Comment by moerabaya** [comment]
@alizahid nope, it only works when the device language is arabic and there's another issue in react that the app won't change back to english (LTR) when the device language is changed to arabic!!

**Comment by alizahid** [comment]
@moerabaya Yeah, that's a good one. Only way you can _fix_ that is by using the `allowRTL` and `forceRTL` methods from `I18nManager`.

**Comment by kfir91** [comment]
@bluetec Hello, How can i add the arabic lang to my xcode project?

**Comment by bilalsyed001** [comment]
RN41.2: for me it only works when wrapping text with writing direction property.

`<Text style={{ writingDirection: I18nManager.isRTL ? 'rtl' : 'ltr' }}>
    <Text>مرحبا</Text>
</Text>`

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/rtl-bug-with-text-component

**Comment by ali-sao** [comment]
Hello guys , 

I had "Use of undeclared identifier" once I added : [[RCTI18nUtil sharedInstance] allowRTL:YES]; into AppDelegate.m . Any useful suggestions? 

Thanks

**Comment by shergin** [comment]
@alizahid Could you please confirm that the problem still exists?

**Comment by alizahid** [comment]
@ali-sao You need to import `RCTI18nUtil` first at the top

    #import <React/RCTI18nUtil.h>

**Comment by alizahid** [comment]
@shergin I'm not working on React Native iOS app right now. Let me confirm soon.

**Comment by iddan** [comment]
This issue is till relevant.

**Comment by coreform** [comment]
I see this problem for some Text views with RN 0.48.4 only on iOS. The problem manifests for both wrapped text and unwrapped text (i.e. text which does not fill the entire width of view).

**Comment by jamsch** [comment]
I kind of have the same issue, but it's regarding the inconsistencies when Arabic script text is mixed with non-script characters/words. 

Here's some of my observations of how it works on Android:
1. If the <Text> component starts with a single script character it's aligned right by default. Forcing it to align left and changing it's writing direction still puts the script on the right and there doesn't seem to be any way to change this as far as I'm aware.
2. Parent <Text> nodes with no configuration of RTL seem to override child <Text> nodes that are configured LTR.

Here's an example:
https://snack.expo.io/rk97V4Tgf

I really just want to get the text content looking like the WebView example.  Anyone have suggestions?

**Comment by mhemrg** [comment]
Just for a quick fix: do not set `textAlign: right` on `<Text />` component. It will work on Android.

**Comment by galkahana** [comment]
@jamsch note that writingDirection is ignored in Android. i think that your rtl settings are simply being ignored. same for me. i have mixed bidi text, and i know that bidi algos require writing direction to handle conflicting cases. so i reckon as long as this is not supported for Android, there's a limitation there.

**Comment by Gentlee** [comment]
Setting `textAlign: 'left'` works for me 😮

**Comment by 0xori** [comment]
Any updates on this one?
I'm using react-native 0.50.3 and it's still happening on ios.
tried to ``` 
I18nManager.allowRTL(true);
I18nManager.forceRTL(true);
```
and than reload.
Tried also to set this style: `{writingDirection: 'rtl' , textAlign: "right"}` to `Text` component.
And the text is still aligned to left.

any ideas?

**Comment by mtx62** [comment]
still facing the same issue
any way,

I converted the text to HTML and used `WebView` with `https://github.com/iou90/react-native-autoheight-webview `and problem solved, but still we need a solution!

**Comment by jamsch** [comment]
Appending the unicode character code: RIGHT-TO-LEFT-OVERRIDE works on Android.
Would be something like this:
```javascript
<Text>{`\u202E${text}`}</Text>
```

**Comment by 0xori** [comment]
I have managed to solve this using `alignSelf: 'flex-start'` for the Text component. Of course the parent view need to be flex and RTL must be on.

**Comment by Komeyl94** [comment]
@bluetec I've added Arabic to languages but it didn't change anything!
I did this:
![image](https://user-images.githubusercontent.com/8911387/39672616-ec5b79b6-5142-11e8-9a92-3ecd1a8b39fb.png)
what am I doing wrong?

**Comment by pashute** [comment]
Mine is probably a totally different problem but perhaps related. The app is in English but on a Hebrew Android (J7 or S7) it shows right to left instead of Left to Right regardless of the I18n RTL setting to true or false. Any pointers?

**Comment by michalchudziak** [comment]
Hello there 👋 this issue seems to have been inactive for the past few weeks. Because of this, it's likely that the issue is not a high priority anymore or it has been solved by OP; for these reasons, we'll close it. But please, if it's actually still an issue with 0.59 please comment below and we can reopen it or please send us a Pull Request with a fix 😊

**Comment by aliazizi** [comment]
I still have the prolbem in react `0.59.1`.

Also when I set align to left its work in some case

But when I put a element before text ( for example a icon from fontawsome ) the icon go to left side of text. I try to put icon after text and get the same result

I currenlty put align to left and find no way to put icon in right side of text

**Comment by AE0011** [comment]
I have a weird problem with textAlign attribute 
if i set it to right text goes to left and if i set it left it goes to right!!
and it happen only on android 8!! it work normal in android 5 and also ios!

```    "react": "16.8.3",
    "react-native": "0.59.5",```

**Comment by mg4u** [comment]
@AE0011  did you find a solution?

**Comment by AE0011** [comment]
@mg4u I downgraded react native to version 0.59.2 and problem solved. it seems that it is fixed in new release 0.59.8 but I didn't test it
https://github.com/facebook/react-native/releases

**Comment by calintamas** [comment]
Seems to be fixed in react-native `0.59.9`

**Comment by muhammadsr** [comment]
> @bluetec I've added Arabic to languages but it didn't change anything!
> I did this:
> ![image](https://user-images.githubusercontent.com/8911387/39672616-ec5b79b6-5142-11e8-9a92-3ecd1a8b39fb.png)
> what am I doing wrong?

For me, I actually forgot to add the localization on iOS. Once I added it, it worked

**Comment by us-22** [comment]
Setting textAligh: left works for me too!!. after forceRTL now left is the right and right is the left. very confused.

"react": "16.8.3",
   "react-native": "0.59.8",

**Comment by ds8k** [comment]
> I still have the prolbem in react `0.59.1`.
> 
> If set align to right, the text goes to left!
> 
> Also when I set align to left its work in some case
> 
> But when I put a element before text ( for example a icon from fontawsome ) the icon go to left side of text. I try to put icon after text and get the same result
> 
> I currenlty put align to left and find no way to put icon in right side of text
> 
> here is my code
> 
> `<Text style={[CommonStyles.normalText, { textAlign: "left", marginRight: 15, marginLeft: 15 }]}><FontAwesome5 name="clock" /> {__.formatDate(date)}</Text>`

I'm also having this problem. @aliazizi were you able to find a solution?

**Comment by aliazizi** [comment]
@ds8k I'm fix my problem with using text-align: end and text-align: start

**Comment by doctor-mosbat** [comment]
1.
`import {  I18nManager  } from 'react-native';`

2.
`I18nManager.forceRTL(true);`
