### ISSUE TITLE
RN 0.37.0: ScrollView "viewConfig" is not defined

### ISSUE THREAD

**Issue by joncursi** [facebook/react-native#10825]
Hi! I just upgraded to RN 0.37.0 and got this error when I booted up my app:

<img width="388" alt="screen shot 2016-11-09 at 4 19 55 am" src="https://cloud.githubusercontent.com/assets/4974609/20133028/cab2a9f8-a633-11e6-850b-fff7bbdf47ba.png">

I searched all of my javascript for any instances of `viewConfig` and couldn't find any, so this seems to be an issue inside React Native itself. Any suggestions?

**Comment by joncursi** [comment]
This seems to be an issue with react-native-animatable.

**Comment by sankhadeeproy007** [comment]
I am getting the same error and I'm not using `react-native-animatable`. I was executing some animations onScroll and now it's crashing.
