### ISSUE TITLE
APIs that are not available to extensions should be marked with NS_EXTENSION_UNAVAILABLE

### ISSUE THREAD

**Issue by shrutic** [facebook/react-native#10821]
### Description

We want to build an iMessage extension (available only in iOS 10+ and Xcode 8+) using React native. Cocoapods made some fixes in their 1.1.1 version that is causing React native pod integration to fail in iOS extensions. [Here](https://github.com/CocoaPods/CocoaPods/issues/6149#issuecomment-259237493)  is the issue logged against Cocoapods. 

In summary, Cocoapods made fixes to correctly check that the pods have marked _"its APIs that don't work for extensions as NS_EXTENSION_UNAVAILABLE"_. This change has disabled us from using the React native pod in iOS extensions. 

The errors are 

> sharedApplication" is unavailable on iOS(App Extension) - Use view controller based solutions when appropriate

### Reproduction

I dont have sample project and can work on getting one if necessary

### Additional Information

* React Native version:0.34
* Platform: iOS
* Operating System: MacOS
* Image of errors 
![image](https://cloud.githubusercontent.com/assets/4141641/20119160/49d064e6-a5bc-11e6-800d-429d04204c6c.png)

**Comment by hramos** [comment]
Thanks for filing the issue. This seems like something that should be fixed. Do you have a list of the particular APIs that need to be marked in this manner?

**Comment by hramos** [comment]
Closing this issue as we haven't heard back from the author.

**Comment by shrutic** [comment]
I have created multiple PRs for this purpose and one of them is pending.. Some got checked in and one of them is still pending. Let me go and see if I can find it. But I have been working around this by creating my own fork of react-native and pointing to it from my project

**Comment by hramos** [comment]
Thanks for letting us know! I didn't see them here. Can you update your PRs to mention this issue? That way they'll automatically close this issue when they're merged. It also helps others see that a particular issue may already have a proposed fix in the pipeline.

**Comment by shrutic** [comment]
Accepted PRs: 
https://github.com/facebook/react-native/pull/13328
https://github.com/facebook/react-native/pull/13227

Pending PR: 
Still need some time to find it as I think I created it from a different profile

**Comment by shrutic** [comment]
https://github.com/facebook/react-native/pull/14263 . Turns out this was closed due to some concern about wrapping APIs this fashion. It would be awesome if you could pursue an alternative way of fixing this issue so that I can upgrade to the facebook's react-native version, instead of using my forked version

Thanks for follow  up
