### ISSUE TITLE
debug on ios device, netowrk is down

### ISSUE THREAD

**Issue by tofrookie** [facebook/react-native#10826]
![img_0649](https://cloud.githubusercontent.com/assets/6767116/20134096/1373cac0-a6a5-11e6-9b95-5f1f825be2f0.PNG)
![img_0650](https://cloud.githubusercontent.com/assets/6767116/20134100/14f4532e-a6a5-11e6-870d-fe9d68caa074.PNG)

why.....

**Comment by tofrookie** [comment]
xcode log:
__nw_connection_get_connected_socket_block_invoke 61 Connection has no connected handler

**Comment by hramos** [comment]
There doesn't seem to be anything actionable in this issue. Please consider opening a new issue and filling out the template so we can help out!
