### ISSUE TITLE
RCTbridge not initializing when running on device

### ISSUE THREAD

**Issue by arjentienkamp** [facebook/react-native#10834]
### Description

Hi all,

I'm trying to run the RN app on my device (on the simulator it does work, or at least show me the first screen), but I'm getting the following error in xCode:

```
2016-11-09 17:31:49.453 [info][tid:main][RCTBatchedBridge.m:72] Initializing <RCTBatchedBridge: 0x17018e380> (parent: <RCTBridge: 0x1700ba940>, executor: RCTJSCExecutor)
(lldb) 

libsystem_kernel.dylib`__abort_with_payload:
0x183fa8d74 <+8>:  b.lo   0x183fa8d8c               ; <+32> Thread 4: signal SIGABRT.
```

Any help would be appreciated very much.

* React Native version: 0.36.1
* Platform: iOS
* Operating System: OSX

**Comment by hramos** [comment]
What RN app are you running? Have you successfully run a RN app on your device before?

**Comment by arjentienkamp** [comment]
Hi @hramos, thanks for your reply. It's an app consisting of a homescreen and a custom camera component. On this iPhone 6 device I have run multiple other apps before, without any problem.

**Comment by arjentienkamp** [comment]
It's solved. It seemed: 'Privacy - Camera Usage Description' was not set.
