### ISSUE TITLE
Hot Reloading crashes the app

### ISSUE THREAD

**Issue by joadr** [facebook/react-native#10836]
### Description

I've been working in my react-native app and today started with $ react-native run-android and then $ react-native start ... The application is working but when I Enable Hot Reloading the application crashes, showing the red background with this message:

```
ExceptionsManager.js:62 Requiring unknown module "./../../../../babel-preset-react-native/node_modules/react-transform-hmr/lib/index.js".If you are sure the module is there, try restarting the packager or running "npm install"
.handleException @ ExceptionsManager.js:62 handleError @ InitializeJavaScriptAppEngine.js:120reportFatalError @ error-guard.js:30guardedLoadModule @ require.js:60_require @ require.js:49(anonymous function) @ require-0.js:1executeApplicationScript @ debuggerWorker.js:20onmessage @ debuggerWorker.js:38
ExceptionsManager.js:62 Module AppRegistry is not a registered callable module (calling runApplication)
```

I've tried removing node_modules folder, then running npm install... also tried the same with yarn I get the same error but only with hot reloading. Any idea of what's going on?

### Reproduction
Here is the project on github:
https://github.com/joadr/federeichon/tree/master/app

### Additional Information

* React Native version: 0.36.1
* Platform: Android
* Operating System: Linux

**Comment by lacker** [comment]
That error message asks you to restart the packager if you're sure the file is there. In that situation I suggest restarting the packager, and also trying restarting watchman. Basically restarting all the different parts, they can kind of get wedged.

**Comment by joadr** [comment]
I've solved this by creating a new project, copying my sources files to the new project an then it worked, finally I didn't know what broke the project.
