### ISSUE TITLE
Build Failed: Cannot find module with tag 'folly' in import path [On building from source on deployment machine]

### ISSUE THREAD

**Issue by konark-hike** [facebook/react-native#10830]
Error that we are getting : 

For setup, have followed steps from building from source doc

Android NDK: /mnt/jenkins_jobs/jobs/react_IR/workspace/react-native/ReactAndroid/src/main/jni/first-party/fb/Android.mk: Cannot find module with tag 'folly' in import path    
Android NDK: Are you sure your NDK_MODULE_PATH variable is properly defined ?    
Android NDK: The following directories were searched:    
Android NDK:         
make: Entering directory `/mnt/jenkins_jobs/jobs/react_IR/workspace/react-native/ReactAndroid/src/main/jni/react/jni'
make: Leaving directory `/mnt/jenkins_jobs/jobs/react_IR/workspace/react-native/ReactAndroid/src/main/jni/react/jni'
/mnt/jenkins_jobs/jobs/react_IR/workspace/react-native/ReactAndroid/../ReactCommon/cxxreact/Android.mk:42: *** Android NDK: Aborting.    .  Stop.

Building from source is working fine on local deployment, am facing this issue on jenkins build deployment process.

Is there any other steps that needs to be performed on every developer machine and development server, after integrating react-native (that's built from source as per steps from doc) on an already running application

**Comment by dudeinthemirror** [comment]
I had the exact error while trying to build a react-native android app. In my case a funny solution fixed this. So, I was running

   ./gradlew clean assembleMyAppPRODRelease --stacktrace --refresh-dependencies

What I did instead (and got past this error):

    ./gradlew assembleMyAppPRODRelease
    ./gradlew clean assembleMyAppPRODRelease --stacktrace --refresh-dependencies

Basically run it without the `clean` first. As to why? Honestly I have no idea :)

**Comment by konark-hike** [comment]
Am still stuck at the above issue, have company's release cycle dependent on this, someone please guide for setting this up

**Comment by dudeinthemirror** [comment]
One other thing I tried was to create symlinks under the jni dir (in your case `/mnt/jenkins_jobs/jobs/react_IR/workspace/react-native/ReactAndroid/src/main/jni/react/jni`) to link to folly, glog, double-conversion, etc - basically all the ones under `third-party`. It goes past the `folly` error, but eventually it fails not finding a .so expected under `jsc`. Again, running w/o `clean` first fixed it for me. Hope this helps.

**Comment by ericvicenti** [comment]
It seems this issue has been re-opened over here. Closing this because it seems to be a duplicate

https://github.com/facebook/react-native/issues/10895
