### ISSUE TITLE
[JSContext] Provide a way to name the JSContext

### ISSUE THREAD

**Issue by ide** [facebook/react-native#1083]
Named JSContexts are easier to debug - some way to access the JSContext would be useful.

**Comment by ccheever** [comment]
:+1:

**Comment by nicklockwood** [comment]
How would this name be used?

There should only be one JSContext active at a time, so would it be sufficient for us to hardcode the name to something sensible?

**Comment by ccheever** [comment]
I can imagine some applications where applications have more than one RCTRootView and more than one JSContext. (Working on one right now...)

One way it comes up is when you connect a debugger to it, ex. the Safari debugger, it's quite useful to know which one is which.

Being able to set it to any string would be quite nice.

**Comment by nicklockwood** [comment]
We already support multiple root views running in a single bridge / context. That's probably a better approach in terms of memory usage, etc. Is there a particular reason you want seperate contexts?

**Comment by ccheever** [comment]
Isolation, expose different native capabilities to diff contexts/rootviews.

**Comment by nicklockwood** [comment]
OK, it should be possible. Rather than exposing new API though, what if we named the JSContext after the bundle loaded in it? Or maybe the actively running module(s)?

**Comment by ccheever** [comment]
Good enough for me.

**Comment by ide** [comment]
Reopening since there's a PR attached.
