### ISSUE TITLE
[Android]In Webview, alert isn't working. Android

### ISSUE THREAD

**Issue by akzhou** [facebook/react-native#10833]
[Android]In Webview, alert isn't working. Android

* React Native version: v0.36.1
* Platform: android
* Operating System:MacOS

**Comment by daemir** [comment]
Maybe you could provide some more information? Like some reproducable code?

**Comment by Darkhorse-Fraternity** [comment]
[Android]In Webview, alert isn't working. Android

React Native version: v0.44.3
Platform: android
Operating System:MacOS


 <WebView
                    ref={w => {
                        this.webview = w
                        this.props.getWebView && this.props.getWebView(w)
                    }}
                    automaticallyAdjustContentInsets={false}
                    style={styles.webView}
                    source={{uri: url,headers:headers}}
                    javaScriptEnabled={true}
                    domStorageEnabled={true}
                    decelerationRate="normal"
                    onShouldStartLoadWithRequest={this._onShouldStartLoadWithRequest.bind(this)}
                    //javaScriptEnabled={false}
                    onNavigationStateChange={this._onNavigationStateChange.bind(this)}
                    startInLoadingState={true}
                    scalesPageToFit={this.state.scalesPageToFit}
                    onError={this._onError}
                    onLoadStart={this._onLoadStart}
                    onLoad={this._onLoad} //
                    onMessage={this.invoke.listener}
                    //onMessage={()=>{}}
                    //onShouldStartLoadWithRequest={this._onShouldStartLoadWithRequest.bind(this)}//iOS,Android 咱么处理
                    //onLoadEnd
                    //injectedJavaScript=jsCode  //Sets the JS to be injected when the webpage loads.
                    renderLoading={this._renderLoading} //Function that returns a loading indicator.
                    renderError={this._renderError} //Function that returns a view to show if there's an error.
                />
