### ISSUE TITLE
Colors are inaccurately rendered.

### ISSUE THREAD

**Issue by joonhocho** [facebook/react-native#10841]
### Description

Colors are inaccurately rendered on both iOS simulator and devices. Haven't checked on Android.

![img_8662](https://cloud.githubusercontent.com/assets/930795/20162843/a39b7394-a6ac-11e6-8b45-d2c2c0eeb27c.PNG)

Hex codes from code:
Blue: #157efb
Black Text: #262626
Border: #b2b2b2
Background: #fafaff 

Hex codes from screenshot:
Blue: #2181f7 
Black Text: #191919 
Border: #b2b2b2
Background: #fafaff 

### Reproduction

Simply use colors.

### Additional Information

* React Native version: 0.35
* Platform: iOS, Not sure on Android
* Operating System: MacOS

**Comment by hramos** [comment]
Does this happen on a particular component, or across the board?

**Comment by joonhocho** [comment]
@hramos Across the board. It's not limited to text or buttons.

**Comment by udfalkso** [comment]
Maybe f.lux / nightshift?

**Comment by JakeCoxon** [comment]
Perhaps this is your display's colour correction. If you are using OSX try using chromes inspector to set this page's background to #157efb, using the OSX colour picker you'll get a different colour depending on the display profile in your OSX settings, I get #0A60FE

**Comment by marcosinigaglia** [comment]
I tested with MacOS Sierra and the colors are correct.

**Comment by hramos** [comment]
Sounds like a non-issue. Ping me if you think this should be re-opened.

**Comment by joonhocho** [comment]
@JakeCoxon Wow. You are right. I don't know why my display is rendering wrong colors.

**Comment by joonhocho** [comment]
For those who run into the same problem as me, change your color profile to sRGB on Mac.
