### ISSUE TITLE
ListView rows don't refresh when the state change.

### ISSUE THREAD

**Issue by yangjiayu** [facebook/react-native#10847]
RN: 0.35
It also exists in 0.37.0
I have two state. One is `rowId`, the other is `showRecord`. the `rowId` is types of Number, the `showRecord` is types of Boolean.  
when I press on the row, the `showRecord` is true to show the hidden view. the `rowId` to judge which row.
This is my renderRow.
```
  renderRow(data, sectionId, rowId) {
    let source;
    if (rowId === this.state.rowId && this.state.showRecord) {
      source = require('../../image/up_arrow.png')
    } else {
      source = require('../../image/down_arrow.png');
    }
   console.log('test====');
    return (
      <View>
        <TouchableOpacity
          style={styles.recordBtn}
          onPress={() => this.recordPress(rowId)}
        >
          <Text style={styles.recordTxt}>record</Text>
          <Text style={styles.recordTxt}>time</Text>
          <Image source={source}/>
        </TouchableOpacity>
        {rowId === this.state.rowId && this.state.showRecord ? <Text>this is a test </Text> : null}
      </View>
    )
  }

```

and there is my renderPress: 
```
  recordPress(rowId) {
    if (this.state.rowId != rowId) {
      this.setState({showRecord: true, rowId});
    } else {
      this.setState({showRecord: !this.state.showRecord, rowId})
    }
  }
```

And there is my issue: 
 when the row's length is 5, or 6 .  the code is  normal.
 when the row's length is more than 20, the state is change anyway.  but the code isn't normal. the row isn't refresh. there is a console.log, but it wont run.

**Comment by haibinyu** [comment]
You should update the list view datasource to let the row refresh.

**Comment by jjdp** [comment]
this happens to me too. previous versions of RN works, the individual rows rerender. refreshing the datasource won't be ideal.

**Comment by yangjiayu** [comment]
@haibinyu should I assign the `showRecord` and `rowId` to dataSource's rowData ? when i press the row, i get the rowId, and change the dataSource's showRecord by the rowId. oh...

**Comment by hramos** [comment]
Can you reproduce this on [rnplay.org](https://rnplay.org/)? Please provide a link.

**Comment by yangjiayu** [comment]
https://rnplay.org/apps/14G3XA
you can change the dataSource to `this.arr2` in the function `componentDidMount`, reload and tap the row,  you will see the issue.

**Comment by hramos** [comment]
Closing as ListView is deprecated in 0.43. Use FlatList.
