### ISSUE TITLE
Navigator.SceneConfigs

### ISSUE THREAD

**Issue by iwangx** [facebook/react-native#10842]
Hey, guys.
Can not provide some of the 'Navigator.SceneConfigs' jump page method, or the way to customize the page Jump style.

**Comment by mkonicek** [comment]
Hi, please open a new issue that has enough information to be able to repro: https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by mkonicek** [comment]
Is this a feature request to add a `jumpPage` method and customize style? From the issue template:

> If you have a feature request, post it on Product Pains: https://productpains.com/product/react-native/
