### ISSUE TITLE
[XMLHttpRequest] Unable to catch http status with fetch api

### ISSUE THREAD

**Issue by Nosherwan** [facebook/react-native#1084]
My react-native app is communicating with a node.js server app. I am able to receive response data but upon sending specific http response errors back to the fetch api calls, the catch handler just gives a generic error but does not pass back xhr.status (400, 500 etc).
Looking at the source for fetch line 261 seems like it is not being passed back:
```javascript
 xhr.onerror = function() {
        reject(new TypeError('Network request failed'))
      }
```

can this be modified to pass back the status? if not is there an alternate node module that can be installed and used instead for REST style calls.

**Comment by nicklockwood** [comment]
It seems like that code is just a stub and could do with some improvements. If you know what it should be doing, please feel free to change it and file a pull request.

**Comment by lelandrichardson** [comment]
@Nosherwan have you done anything with this?  If not, I may play around with it. Thanks.

**Comment by brentvatne** [comment]
@lelandrichardson - looks like there hasn't been any progress here, would be great for you to jump in if you're still willing

**Comment by lelandrichardson** [comment]
@brentvatne Looking closer at this, I think the current implementation is actually correct.  The `xhr.onerror` is only called if there is actually a hard-fail (ie, there was a network error) in which case there isn't actually an HTTP status code to inspect. In cases where there is an HTTP 500 or 404 etc, I believe the promise is resolved, not rejected, and the proper status code should be there in the resolve method. 

The only time this isn't true seems to be if the status code was less than 100 or greater than 599.

**Comment by brentvatne** [comment]
@lelandrichardson - that sounds acceptable to me, I believe a `.catch` chained on the promise should cover these errors so I'm going to close this issue, we can reopen if you change your mind or other people have this problem
