### ISSUE TITLE
PushNotificationIOS: Local notifications not working in iOS 10.

### ISSUE THREAD

**Issue by yorickr** [facebook/react-native#10846]
### Description

When using PushNotificationIOS, no notifications are displayed using presentLocalNotification in iOS 10. I expected a local notification to appear, while in reality nothing appeared at all. However, an event does come through under the 'localNotification' event listener.

After following [this tutorial](https://medium.com/@martco/triggering-ios-actionable-push-notifications-via-react-native-7990a6a3c3f4#.v13bawbxi) (basically, add a notification target, then use 'category' from presentLocalNotification to display it), then adding some missing code found [here](http://stackoverflow.com/questions/39490605/push-notification-issue-with-ios-10) (to be precise, [this](https://github.com/yorickr/PushNotificationIOS_Test/commit/a10afce581281f31d38e0d4e4a134b8bb99b172a) commit in my test repo), I managed to display a notification under iOS 10 (and 9).

HOWEVER, this means that the 'localNotification' event listener does not receive any notifications when they are clicked in the notification tray. I suspect because RCTPushNotificationManager is not being called with the notification object.

### Reproduction

This can all be seen working under [this](https://github.com/yorickr/PushNotificationIOS_Test) test repo I have made. 

As I have never done any Objective C programming, I would have no idea how to get this integrated in the PushNotificationIOS library, therefore I've made this issue, so that hopefully someone else can pick up and properly integrate this into the library.

### Additional Information

* React Native version: 0.37.0
* Platform: both
* Operating System: MacOS

**Comment by christopherdro** [comment]
Is your app foregrounded or backgrounded. If your app is foregrounded then you are responsible for handling the notification.

I can confirm that I am able to see local notifications fire when the app is backgrounded in iOS 10

**Comment by yorickr** [comment]
Indeed, I am able to see the local notifications pop up when the app is backgrounded. This also happens on iOS 9. However, one difference I noticed was that if you call presentLocalNotification on iOS 9, it leaves a notification in your notification tray, but on iOS, it doesn't.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/pushnotificationios-local-notifications-not-working-in-ios-10
