### ISSUE TITLE
React-Native 'CSSLayout/CSSLayout.h' file not found on Swift 

### ISSUE THREAD

**Issue by nguyenphong1301** [facebook/react-native#10843]
i have did follow the instruction of https://facebook.github.io/react-native/docs/integration-with-existing-apps.html and got a below issue

'CSSLayout/CSSLayout.h' file not found 

The errors code placed in library file 

#include <CSSLayout/CSSLayout.h>
#include <CSSLayout/CSSNodeList.h>

This is my package.json

> {
  "name": "123Phim",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "react": "^15.3.2",
    "react-native": "^0.33.0",
    "react-native-gallery": "0.0.17",
    "react-native-gifted-listview": "0.0.15",
    "react-native-gifted-spinner": "^0.1.0"
  }
}

Os: mac serria 
xcode : 8

**Comment by damusnet** [comment]
@facebook-github-bot duplicate #11272
