### ISSUE TITLE
BaseActivityEventListener.class missing from react-native-0.20.1.aar in maven central??

### ISSUE THREAD

**Issue by npomfret** [facebook/react-native#10854]
After upgrading to rn 0.38-rc, i got compile error saying that `BaseActivityEventListener` is missing.  Should appear in `/Users/nickpomfret/Documents/github/datr/app/pomochat/android/app/build/intermediates/exploded-aar/com.facebook.react/react-native/0.20.1/jars/classes.jar!/com/facebook/react/bridge`?

![screen shot 2016-11-10 at 10 24 17](https://cloud.githubusercontent.com/assets/5489469/20173141/f13e49a4-a72f-11e6-9ad4-2d9d8099cb68.png)

I downloaded [react native](http://central.maven.org/maven2/com/facebook/react/react-native/0.20.1/react-native-0.20.1.aar) from the maven repo and unzipped it.  The class file `BaseActivityEventListener.class` isn't in _classes.jar_:

![screen shot 2016-11-10 at 10 32 45](https://cloud.githubusercontent.com/assets/5489469/20173432/31cd561c-a731-11e6-973e-aca1f3ac8cbc.png)

I can see the java [file](https://github.com/facebook/react-native/blob/0.38-stable/ReactAndroid/src/main/java/com/facebook/react/bridge/BaseActivityEventListener.java) in the git repo.

And I can see the source file in my node_modules:

```
find node_modules -name BaseActivityEventListener.*
node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/BaseActivityEventListener.java
```

But it's not getting compiled when I build my app.  And it's not appearing on my class path for some reason.

What have I missed?

**Comment by dojiboy9** [comment]
What was the issue here? How did you fix it @npomfret ?

**Comment by npomfret** [comment]
I didn't fix it.  For some reason they're no longer publishing the binaries in maven.  You simply can't compile react-native native libraries in isolation.  

The way to work around it is to create a new react-native project, then import your project using package.json.  That's the only way I've found to do it, and I just can't come up with anything resembling a sensible work flow when developing native code.

Madness.
