### ISSUE TITLE
ScrollView bug with RTL setting

### ISSUE THREAD

**Issue by ronzilca** [facebook/react-native#10852]
### Description

I've got simple **ScrollView (horizontal)** with some thumbnails inside. My app is for both LTR and RTL users, so when user change his locale the style is responsive for his system choose.

Actually, in both LTR and RTL the **ScrollView** is get widen because there is more thumbnails than what can present in the frame - and its OK. **The problem is when my locale is set to RTL** - I can't see all my thumbnails, but only the thumbnails that fit in my screen. Again, the **ScrollView** is widen as he should be - but the thumbnails is missing.

### Reproduction

               `<ScrollView
                    ref={(view) => this.category_view = view}
                    horizontal={true}
                    showsHorizontalScrollIndicator={false}
                >
                    <Item title={'1'} />
                    <Item title={'2'} />
                    <Item title={'3'} />
                    <Item title={'4'} />
                    <Item title={'5'} />
                    <Item title={'6'} />
                </ScrollView>`

### Additional Information

* React Native version: 0.35.0
* Platform: Android
* Operating System: MacOS

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
