### ISSUE TITLE
【iOS8】Image form server can`t render correctly on iOS8~ help.

### ISSUE THREAD

**Issue by yangchao0033** [facebook/react-native#10851]
### Description

Image form server can`t render correctly, looks like render error.

####  iOS8.1 are looks like this. can`t render correctly。
![image](https://cloud.githubusercontent.com/assets/10287013/20170117/e7cc218a-a765-11e6-802b-4b593f4ba3ed.png)

#### Here are the normal edition on iOS10
![image](https://cloud.githubusercontent.com/assets/10287013/20170527/a78e8d40-a767-11e6-9017-311ed8efd272.png)

### Code like this
```
<Image source={{ uri: avatar }} style={styles.ios.userImage}/>
```

#### progress log loaded alwalys bigger than total bytes .

* React Native version: [0.36]
* Platform: iOS8.1]
* Operating System: [MacOS]

**Comment by hramos** [comment]
That's weird. What sort of testing have you done to determine this only reproduces on 8.1 devices, versus let's say a server side or network issue?

**Comment by yangchao0033** [comment]
@hramos We track the data content length, and found the image data "<NSMutableData> _data"  field length is bigger than the response`s expectedContentLength so that the image will not render correctly .looks like the URLSession work wrong.

**Comment by yangchao0033** [comment]
@hramos This is a hybrid Project.

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
