### ISSUE TITLE
Allow more styling for the new Button component

### ISSUE THREAD

**Issue by arthurvi** [facebook/react-native#10859]
First, thanks for the new RN Button component!

## Current situation
The current styles are:
Android: <img width="302" alt="screen shot 2016-11-10 at 14 58 39" src="https://cloud.githubusercontent.com/assets/3864426/20179398/3c54d09a-a756-11e6-80d3-8e5acffbc4d3.png">
iOS: <img width="115" alt="screen shot 2016-11-10 at 14 58 48" src="https://cloud.githubusercontent.com/assets/3864426/20179399/3c7c8608-a756-11e6-89a0-da1495786f2a.png">

We can only customise:
- iOS: Color of the text
- Android: Color of the background

## Wanted 
I would really like to be able to change the background color and text color on both platforms. Then we can make a more sophisticated button for iOS and a simpler button for Android.

Like this on Android:
<img width="355" alt="screen shot 2016-11-10 at 15 02 29" src="https://cloud.githubusercontent.com/assets/3864426/20179512/c3ba335e-a756-11e6-88ae-8d7c8705ba48.png">

And this on iOS:
<img width="359" alt="screen shot 2016-11-10 at 15 04 22" src="https://cloud.githubusercontent.com/assets/3864426/20179557/01abfefe-a757-11e6-8d7c-dc1a6f856a2d.png">

Or should we just allow a style prop? Would you accept a PR that adds more customisation? I know it can be done by using the `Touchableopactiy` and `TouchableNativeFeedback` etc. but it would be nice to have an out of the box solution for both platforms.

**Comment by hramos** [comment]
Hey @arthurvi! We do want to keep Button simple, but it's also not ideal to have people drop down to the Touchable components or use custom styles in order to implement basic native controls.

How would you implement the above example natively on iOS using UIButton? How about on Android?

**Comment by arthurvi** [comment]
See: https://github.com/facebook/react-native/blob/master/Libraries/Components/Button.js#L94

Now we can set a `color` prop. The Button component translates this to:
- on iOS to color of the text
- on Android to the color of the background

I propose to replace the `color` prop for the props `textColor` and `backgroundColor`.

**Comment by ericvicenti** [comment]
I think we should not do this for the button component in core, because there would be conflict between the `color` and `textColor` props on iOS. And conflict between `color` and `backgroundColor` on Android. We cannot remove the color prop because people may already rely on it. If you have a button with other styles, you can always publish it for others to use on npm.
