### ISSUE TITLE
viewConfig is not defined: 0.37 seems to have broken a lot of native modules

### ISSUE THREAD

**Issue by tuckerconnelly** [facebook/react-native#10857]
Creating an Animated component for a lot of packages throws a `viewConfig is not defined` error. Seems to be caused by https://github.com/facebook/react-native/commit/c9960817eea008b2703657066212002557e0d939

So far I've had it happen with https://github.com/react-native-community/react-native-video and https://github.com/react-native-community/react-native-svg

Should native modules be defining their own viewConfigs? (Don't seem to be docs on that?) Or is this something react-native should fix?

**Comment by leeight** [comment]
https://github.com/facebook/react-native/pull/10827
