### ISSUE TITLE
Alert bug in RN 0.36.0

### ISSUE THREAD

**Issue by aiDove** [facebook/react-native#10868]
Hi guys, we encountered a compatible issue on Alert control in RN 0.36.0. In the previous version (0.33.0), we have the following workflow in our hybrid app (RN and iOS native):

1. Launch the hybrid app and enter the native view firstly.
2. Switch to the JS view with the navigation menu afterwards.
3. Invoke an Alert control to display some messages from the JS view.

In the 0.33.0, the Alert control could be displayed correctly. However, it cannot be found on 0.36.0. After investigation, we found the Alert control hovering on the previous native view. We guess there could be something wrong with the context management.

* React Native version: [0.36.0, 0.36.1, 0.37.0]
* Platform: [iOS]
* Operating System: [MacOS]

Could you please help us to address it? Thanks!

**Comment by hramos** [comment]
Can you reproduce this on [rnplay.org](https://rnplay.org/)? Please provide a link.

**Comment by ericvicenti** [comment]
Sorry, I don't know what would cause this issue. Maybe you could narrow it down by checking which version of RN caused the breakage. Or you could check to see how the native code in RN changed in those versions, to see what changed. (Maybe something related to Alert or Window).

Unfortunately this is not very high-pri because a lot of app-specific things can go wrong in hybrid apps. If you want to help somebody fix it, maybe post a sample app where the issue can be observed?

**Comment by aiDove** [comment]
Hi, I write some sample code to demo this issue, which is posted in github:
[https://github.com/aiDove/AlertDemo](url)

You can find the screenshot GIF animation in github easily.
1. click "Alert" firstly, and you will see a popup dialog window correctly.
2. click "Create native window", then click "Open native window"; you will find a native view with a button "hide window" on it afterwards.
3. click "hide window" to hide the native window (note: it is just hidden, rather than closed/destroyed actually)
4. click "Alert" button on the RN window. Now the popup dialog window does not appear as expected.
5. click "Open native window" to switch to the native window in the background, we found that popup dialog window stayed there. It seems to be covered by the RN window in front.

This demo is based on RN 0.37.0 (iOS). However, the issue does not exist on RN 0.33.0 (iOS).

Could you please help fix it in the next RN release?

Thanks in advance!

**Comment by littlesome** [comment]
Hi, I use this 'global and topmost' alert impl, this works great for me. http://stackoverflow.com/a/30941356 
You can subclass the UIAlertController in RCTAlertManager.m 

If this works, could you or someone else help send a PR? Sorry for that I'm on a long travel

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
