### ISSUE TITLE
Error when I enable Hot Reloading

### ISSUE THREAD

**Issue by alexmngn** [facebook/react-native#10869]
### Description

When I enable the Hot Reloading tool, I get the following error:

Not sure how to fix this.

![simulator screen shot nov 11 2016 13 30 31](https://cloud.githubusercontent.com/assets/4203845/20206537/abc9dbba-a813-11e6-9952-092660924ea3.png)

### Additional Information

* React Native version: 0.36.1
* Platform: iOS
* Operating System: macOS

**Comment by hramos** [comment]
How did you create this project?

**Comment by damusnet** [comment]
@facebook-github-bot label Needs Response from Author
