### ISSUE TITLE
Dependency problem with creating a custom native android module

### ISSUE THREAD

**Issue by npomfret** [facebook/react-native#10862]
I'm trying to create a native module, but I notice that the mavencetnral repo and jcenter haven't been updated in a long time.  Without a recent react-native jar file my module won't even compile.  It seems like its quite a common problem, there seem to be quite a few open source modules out there that have a gradle dependency on rn 0.20.1 - and if you try and compile them they fail because their code relies on the app it's running in having a more recent version of react-native.

If someone wants to write a custom native android module (that compiles) what is the recommended approach with regard to the react-native dependency.

It doesn't seem to make sense to write something that can't compile because it needs a surrounding app to provide its dependencies.

**Comment by lacker** [comment]
What's wrong with writing something that can't compile because it needs a surrounding app to provide its dependencies? It seems like that is how most React Native components would work - there's nothing you can do with them without having an app to put them in.

**Comment by ide** [comment]
Is there a way to approach this the way Android does? Specifically, you can write an Android library that depends on Android APIs but obviously you don't need to include all of Android in your JAR/AAR file.

I'm not sure if this would work but could you tell the Android toolchain to look for the react-native Java sources or JAR/AAR under node_modules/react-native and not to include react-native's class files in your own JAR/AAR?

**Comment by npomfret** [comment]
> What's wrong with writing something that can't compile because it needs a surrounding app to provide its dependencies

Thanks for the replies, and I agree you need an app eventually, but...

Most of the code in these libraries, like 99% maybe, is pure java.  Some don't even need any android libraries to be present.  Yes they need a surrounding app at **runtime**, but at build time almost all the code can run and tested in isolation.  But only if is compiles.

It feels alien to me to be building a java project that has a gradle build associated to it, that can't be compiled. And as far as I can see, not for any good reason.  Most projects I've looked at put `compile 'com.facebook.react:react-native:+'` in there projects dependencies, and are therefor picking up some very old version of the react-native jar (which isn't used at runtime).  This jar is so old that a few of these project don't compile - so I'm wondering what's the point? Just delete it, just delete the whole embedded build even, it serves no purpose.  Where else is it common place to write java libraries, that have a gradle build, that intentionally don't compile?  What am I missing here?

The lack of a compiling project also affects your workflow, I don't even know what a _good_ workflow would be.  Say you want I want to make a change to a native RN library...  I'd like to just fork, clone, open my IDE, make the change and compile before I go an test it (either unit testing or putting inside an app).  But that process isn't possible at the moment.  You have to create a react-native project... and then what? monkey around with git inside the node_modules directory or something?  Maybe I've misunderstood, I must have - how do people build these things in practice?

**Comment by npomfret** [comment]
What was the reason for ceasing to put the react-native car files into the maven repo?  All I'm really after is an up to date compile time dependency.

**Comment by ide** [comment]
We want a single distribution mechanism and npm is the one that makes the most sense. It's much more streamlined and simple for the RN maintainers to package the JS, Android, and iOS dependencies together and send them off to npm together and have to worry about only one repository. Of course, you're free to set up your own Maven repo and publish to it the sources in `node_modules/react-native/ReactAndroid`, we'll meet you halfway by getting the code to npm.

**Comment by npomfret** [comment]
Does my point make any sense to people?  I feel like maybe I'm being stupid suggesting that having a working / compiling build for native android libraries is a good thing.

**Comment by jpshelley** [comment]
We would appreciate it hosted on jcenter preferably as well. The reason being:
* We created a separate library project with the standard react native init procedures
* We create a release using `react-native bundle` and host that ourselves
* In our main app we want to include the library project which relies on `compile 'com.facebook.react:react-native:0.37.0'` 
* However that dependency cannot be found because it lies in the npm node modules folder. I can clearly see the `.aar` in there and can host it myself, but that would require a manual upload each time we upgrade (or creation of a script).

Its not very difficult to upload the .aar directly to jcenter, and can be done via CI.

If we had a PR addressed to publish to JCenter, would the FB team be able to update Travis to upload to jcenter after the npm upload?

To better understand the approach we're taking, take a look at this post: https://artsy.github.io/blog/2016/08/24/On-Emission/

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/dependency-problem-with-creating-a-custom-native-android-module

**Comment by jpshelley** [comment]
I think this issue should be re-opened. Is it too much to ask facebook to host the artifact on jcenter? I'm assuming Facebook already has other artifacts on jcenter like their android sdk.
The next step would be as simple as running the gradle commands in https://github.com/facebook/react-native/blob/master/ReactAndroid/release.gradle during CI.

**Comment by hramos** [comment]
@ide, if @jpshelley sent a PR to to publish to JCenter, is that something we'd consider merging?

**Comment by ide** [comment]
I think we want the official release to be centralized (that is, distribute Java <-> JS <-> ObjC together), which is a fundamental difference between RN and other projects like the FB Android SDK. If someone else e.g. Artsy wants to put artsy-react-native on JCenter that seems like a good escape hatch that works for their workflow but I wouldn't want to encourage module authors to depend on this.

There is also this approach of using local Maven repos and `resolutionStrategy` that may work well too. Gradle allows the app author to control how Gradle resolves dependencies (like RN) listed in other Gradle files: https://github.com/SoftwareMansion/jsc-android-buildscripts#how-to-use-it-with-my-react-native-app

**Comment by jpshelley** [comment]
@ide thats understandable. What about standalone iOS or Android libraries, where using the default RN directory structure is somewhat overkill. Having a standard iOS or Android project using Cocoapods or Gradle might be better in those scenarios. I don't suppose that is something that Facebook/RN is willing to support?

**Comment by ide** [comment]
In the case of libraries, I'm thinking we want a concept similar to npm's peer dependencies -- specifically, a way for libraries to say, "I need React Native v0.44-v0.46 and it's your job to supply it." Then in your Gradle file or Podfile you'd tell Gradle/CocoaPods how to find RN and your app would build. Maybe what we need are some guides or example repos for how to author React Native modules (though for those that support more than one platform, I'd also recommend choosing a unified distribution mechanism like npm).

**Comment by jpshelley** [comment]
> Then in your Gradle file or Podfile you'd tell Gradle/CocoaPods how to find RN and your app would build

I think thats the hard part though, because right now need to have npm setup and download the artifacts via node modules, which most native developers aren't familiar with. If it was hosted on jcenter then most native developers would have no trouble including it.

If that is never going to happen, then instructions on how to create a `.aar` file from the repo and including it manually in an Android Studio project would be a nice next step as you suggested.

**Comment by ide** [comment]
If you're working on a React Native project you're going to have to learn how to use npm. At minimum the JS for RN itself comes from npm.

If you organizationally have a split between developers who write JS and those who don't for now (and somehow can get by without npm dependencies on their computers...), you could check in `node_modules/react-native` (but exclude `node_modules/react-native/node-modules`).
