### ISSUE TITLE
Android ART Package

### ISSUE THREAD

**Issue by ErreMalote** [facebook/react-native#10873]
I am trying to import the "new ARTPackage()" into my Android app but it seems that "import com.facebook.react.ARTPackage;" does not exist. As was referenced on this commit "https://github.com/facebook/react-native/commit/27ac04742ab4665cd529fe63fd68a30db9293b76".

**Comment by lacker** [comment]
This isn't documented so it's not clear to me that it is supposed to exist. I would try using react-native-svg.
