### ISSUE TITLE
No stack trace for thrown exceptions

### ISSUE THREAD

**Issue by JakeCoxon** [facebook/react-native#10875]
### Description

Currently when throwing an exception, the error message is logged in the chrome dev tools but not the full stack trace. It would be hugely beneficial if the stack trace was there as well. Not sure is this was always the behaviour.

### Reproduction

throwing an error on top level, or in a function called from top level, or a function called from component event handlers

```
function MyFunction() {
  throw new Error("Some error");
}
MyFunction();
```

I can see that the error is eventually passed to this function in ExceptionsManager.

```
    function handleException(e, isFatal) {
        if (!e.message) {
            e = new Error(e);
        }
        if (typeof console._errorOriginal === 'function') {
            console._errorOriginal(e.message);
        } else {
            console.error(e.message);
        }
        reportException(e, isFatal);
    }
```

![image](https://cloud.githubusercontent.com/assets/601264/20211356/b7cb5d72-a830-11e6-93cf-dfccfbf83a64.png)

If I log `e.stack` instead of `e.message` I get something better 
![image](https://cloud.githubusercontent.com/assets/601264/20211393/ea048228-a830-11e6-83d0-f91e4f257a65.png)

### Additional Information

* React Native version: 0.36.1
* Platform: iOS
* Operating System: OSX

**Comment by lacker** [comment]
That makes sense to me. Are you interested in sending a pull request to improve this?

**Comment by ide** [comment]
Two things to watch out for -- e.stack differs across JS VMs and it seems prudent to me to make sure the output looks good in JSC and V8 (tie-breaking in JSC's favor). Also the snippet `if (!e.message) { e = new Error(e); }` might be worth changing since `e.stack` is not going to be useful and it'd be clearer just to admit we don't have a stack trace.

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
