### ISSUE TITLE
When using RefreshControl and clicking status bar, RefreshControl goes into refreshing state after scroll to top

### ISSUE THREAD

**Issue by slavik0329** [facebook/react-native#10883]
### Description

By default in a ScrollView, when the status bar is clicked in IOS, the view will scroll to the top. When using a RefreshControl, the auto scroll to top causes the RefreshControl to go into a refreshing state with the indicator spinning, however, the onRefresh call never gets called and it just keeps spinning without updating any app state.

### Additional Information

* React Native version: 0.37
* Platform: IOS
* Operating System: OSX

**Comment by hramos** [comment]
Can you reproduce this on [rnplay.org](https://rnplay.org/)? Please provide a link.

**Comment by christopherdro** [comment]
@facebook-github-bot no-reply
