### ISSUE TITLE
Support client certificate authentication

### ISSUE THREAD

**Issue by huston007** [facebook/react-native#10885]
### Description

If you have to connect to server which is protected with client certificate authentication with React Native - you've lose, because there is no way. This authentication is popular in enterprise to protect sensetive servers from unauthorized access.

Here is some information about using client certificate in iOS and Android

http://stackoverflow.com/questions/3749429/how-to-use-client-certificate-authentication-in-ios-app
http://chariotsolutions.com/blog/post/https-with-client-certificates-on/

### Reproduction

Try to connect to HTTPS server which requires client certificate

**Comment by lacker** [comment]
You should be able to do this by writing a library to use client certificate authentication in native code, and then using `NativeModules` to call it from javascript. For example, if there's an iOS or Android library you like for this, you can just call it this way. So I think that categorizes this as a "feature request" and in general, feature requests are better suited for Product Pains. https://productpains.com/product/react-native I'm going to close this issue but I encourage you to post there with requests like how to make this easier.

**Comment by huston007** [comment]
Okay, there is already such feature request in product plans
https://productpains.com/post/react-native/support-tls-client-certificate-authentication-in-fetch-api-implementation
