### ISSUE TITLE
Error adding opacity to animated.view in react native 0.37

### ISSUE THREAD

**Issue by koraniar** [facebook/react-native#10888]
this code works perfectly on react native 0.35 or earlier, but after update to react native 0.36 and 0.37 it not works

````
class LoginViewComponent extends Component {
    constructor(props) {
        super(props);
        this.state = {
            scale: new Animated.Value(1.5),
            offset: new Animated.Value((window.height / 2) - (125)),
            opacity: new Animated.Value(0)
        };
    }

    componentDidMount() {
        setTimeout(() => {
            Animated.timing(
                this.state.offset,
                {
                    toValue: 0,
                    duration: 1000
                }
            ).start();

            Animated.timing(
                this.state.scale,
                {
                    toValue: 1,
                    duration: 1000
                }
            ).start();

            setTimeout(() => {
                console.log("it is really called");
                Animated.timing(
                    this.state.opacity,
                    {
                        toValue: 1,
                        duration: 500
                    }
                ).start();
            }, 800);
        }, 1200);
    }

    render() {
        var scale = this.state.scale;
        return (
            <View style={styles.container}>
                {/* this animated view works */}
                <Animated.View style={[{ alignItems: 'center', position: 'absolute', top: 0, left: 0, right: 0, bottom: 0 }, { transform: [{ scale }, { translateY: this.state.offset }] }]}>
                    <Image source={require('../Assets/Images/logotype.png')} style={styles.imageLogo} />
                </Animated.View>
                {/* this animated view do not works */}
                <Animated.View style={{ opacity: this.state.opacity }}>
                    <FinalView />
                </Animated.View>
                {/* I have tried too */}
                <Animated.View style={{ opacity: 1 }}>
                    <FinalView />
                </Animated.View>
            </View>
        )
    }
}
````

It only works if I remove Animated.View, but works without animation

**Comment by ericvicenti** [comment]
Is this on iOS, Android, or both?

**Comment by koraniar** [comment]
@ericvicenti only on Android, on ios the styles of '<FinalView />' are a bit different

**Comment by centaurreader** [comment]
I am running into the same issue on iOS

**Comment by ericvicenti** [comment]
cc @janicduplessis @ryangomba

**Comment by centaurreader** [comment]
Oops. Sorry I figured it out. I had some bad styles after updating. :(

**Comment by ericvicenti** [comment]
Ok so this may still be Android only. @koraniar, can you provide a simple example of this bug on rnplay.org ?

**Comment by janicduplessis** [comment]
@koraniar What exactly happens when it does not work? Is there an error or just no animation? Could you also provide a small example that reproduces the issue?

**Comment by koraniar** [comment]
@ericvicenti @janicduplessis this is the example https://rnplay.org/apps/u0mzZw , the animation just no works even when i set opacity in 1
`
<Animated.View style={{ opacity: 1 }}>
            <FinalView />
</Animated.View>
`
I am testing on a Nexus 5x with Android 7.0

**Comment by ryangomba** [comment]
I'm confused -- rnplay example seems to work for me?

**Comment by tuckerconnelly** [comment]
Yeah I'm running in to this to--views aren't visible on Android when animating opacity.

**Comment by tuckerconnelly** [comment]
It won't happen on rnplay because Exponent uses 0.36, not 0.37

**Comment by tuckerconnelly** [comment]
Got it--I think it has to do with `position: relative` and `position: absolute`: https://rnplay.org/apps/bOo6Gw

Here's a repo to play with: https://github.com/tuckerconnelly/RNAndroidOpacityBug

**Comment by LoopIndigo** [comment]
This seems to still be happening in 0.40 (can anyone else confirm?). In my case I use an interpolated `Animated.Value` to set my opacity. The initial value doesn't seem to work. Once it is changed via `Animated.timing` the opacity starts working again.

Has this been fixed for anyone else?

**Comment by binchik** [comment]
@LoopIndigo

It's happening for me in 0.41.2. Is there a way to find out what version of RN will include this PR?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/error-adding-opacity-to-animatedview-in-react-native-037

**Comment by dnaploszek** [comment]
Hi,
There is still something wrong with setting opacity as an AnimatedValue: 

    this.state = {    
        opacityValue: new Animated.Value(0),
    }
    animate() {
      Animated.sequence([
        Animated.timing(
          this.state.opacityValue,
          {
            toValue: 1,
            duration: 400,
            easing: Easing.linear,
            useNativeDriver: true,
          }
        ),
        Animated.timing(
          this.state.opacityValue,
          {
            toValue: 0,
            duration: 800,
            easing: Easing.linear,
            useNativeDriver: true,
          }
        ),
        Animated.delay(Math.floor(Math.random() * 10) * 100)
      ]).start(() => {
          this.animate();
      });
    }

And then on render:

    <Animated.Image
         style={{
             opacity: this.state.opacityValue,
         }}
         source={{ uri: this.props.techImages[this.state.shownImageIndex] }}
         resizeMode={'contain'}
    />

When i remove opacity: this.state.opacityValue or set it to a constant value (1), the view is rendered otherwise i get this cryptic error:
![image](https://user-images.githubusercontent.com/17772241/34297521-e047bf34-e718-11e7-9be0-08412ade593e.png)

This error is only reproduced on Android i confirmed that on IOS everything works fine. 
I had this error on react-native 0.51.0

**Comment by hramos** [comment]
Please open a new issue.
