### ISSUE TITLE
Image URI loading blocked

### ISSUE THREAD

**Issue by iceNuts** [facebook/react-native#1088]
Hi there,

I am using code below to load an image online:
```
return (
      <View style={styles.item}>
        <Image
          source={{uri: uri}}
          style={styles.thumbnail}
        />
      </View>
    )
```
This is really straight forward. However, the image is not loading, and seems blocking the whole app. This might be because the image is too big. Is there any good solution for this?

Thanks.

**Comment by nicklockwood** [comment]
Is it a local image uri, or remote? How big is the image?

**Comment by christopherdro** [comment]
@iceNuts Are you still having this issue?

**Comment by brentvatne** [comment]
Code example here is incomplete, seems like this works fine for myself and others. Ping me with the uri that doesn't work and I'll reopen this issue @iceNuts!
