### ISSUE TITLE
0.4.x - breaking changes?

### ISSUE THREAD

**Issue by voronianski** [facebook/react-native#1089]
I didn't make any progress with react-native for several weeks and the last version that I used was `0.3.11` which worked perfectly.

Unfortunately after update to `0.4.1` I have several issues. Official blog post doesn't say anything about breaking changes etc. - http://facebook.github.io/react/blog/2015/04/17/react-native-v0.4.html

## Styles are broken

That's what I have right now (before update it worked as fullscreen):

<img src="https://dl.dropboxusercontent.com/u/100463011/react-native-fullscreen-bug.png" width="250" />

Code is pretty straightforward - https://github.com/voronianski/EightTracksReactNative/blob/master/index.ios.js#L74

## Build empty screen

One more strange issue is happening with this demo app - https://github.com/voronianski/react-native-effects-view/tree/master/example/EffectsApp

After update it renders white screen in simulator.. Didn't have time to figure out what is going.

**Comment by romanonthego** [comment]
I believe it is `0.4.1` not `0.4.0` - i've updated my up to `0.4.0` without problem while `0.4.1` break something in styling (particulary in top navbars - but i'm using https://github.com/Kureev/react-native-navbar so i'm not where collision is happening).
Anyway, you may consider to rollback to `0.4.0` - this could work.

**Comment by nicklockwood** [comment]
I've checked on our latest codebase and this seems to be working correctly. Sorry for the breakage, but it should be fixed in the next update.

**Comment by lelandrichardson** [comment]
Just to provide additional data points, this broke some similar styles in my app as well... I've reverted back to 0.4.0

**Comment by bimawa** [comment]
Its similar trouble #1051 ?

**Comment by lelandrichardson** [comment]
@bimawa that was indeed the issue for me...

adding `width: undefined, height: undefined` to the styles applied to the image fixed it in my case.

**Comment by bimawa** [comment]
@lelandrichardson Waaahh It's helped for me Thx!!
