### ISSUE TITLE
'Reload' did not change in my android device when I modified a js file

### ISSUE THREAD

**Issue by omhybrid** [facebook/react-native#10894]
'Reload' did not change in my android device when I modified a js file 

i changed the file:
node_modules\react-native\packager\react-packager\src\node-haste\FileWatcher\index.js

to
_createWatcher(rootConfig) {
const watcher = new WatcherClass(rootConfig.dir, {
glob: rootConfig.globs,
dot: false,
});

return new Promise((resolve, reject) => {
  const rejectTimeout = setTimeout(
    () => reject(new Error([
        'Watcher took too long to load',
        'Try running `watchman version` from your terminal',
        'https://facebook.github.io/watchman/docs/troubleshooting.html',
      ].join('\n'))),
    MAX_WAIT_TIME
  );

  watcher.once('ready', () => {
    clearTimeout(rejectTimeout);
    resolve(watcher);
  });
});
}

and
const MAX_WAIT_TIME = 360000;

and still nothing changed...

* React Native version: 0.37.0
* Platform: Android
* Operating System:  Windows7

**Comment by bluefantasy728** [comment]
I have the same issue, with the same RN version, same android, same Windows7

**Comment by ericvicenti** [comment]
Reload is only meant to refresh your app's code. It will not update the code in the packager. To run new packager code (anything in react-native/packager), please kill and re-run the react native dev server.
