### ISSUE TITLE
Build failed on integrating with existing app : ReactAndroid:cleanReactNdkLib FAILED

### ISSUE THREAD

**Issue by konark-hike** [facebook/react-native#10895]
Build error ::

Android NDK: /mnt/jenkins_jobs/jobs/react_IR/workspace/react-native/ReactAndroid/src/main/jni/first-party/fb/Android.mk: Cannot find module with tag 'folly' in import path    
Android NDK: Are you sure your NDK_MODULE_PATH variable is properly defined ?    
Android NDK: The following directories were searched:    
Android NDK:         
make: Entering directory `/mnt/jenkins_jobs/jobs/react_IR/workspace/react-native/ReactAndroid/src/main/jni/react/jni'
/mnt/jenkins_jobs/jobs/react_IR/workspace/react-native/ReactAndroid/../ReactCommon/cxxreact/Android.mk:42: *** Android NDK: Aborting.    .  Stop.
make: Leaving directory `/mnt/jenkins_jobs/jobs/react_IR/workspace/react-native/ReactAndroid/src/main/jni/react/jni'
:ReactAndroid:cleanReactNdkLib FAILED

**Comment by konark-hike** [comment]
Someone please guide a solution for this, am badly stuck at above issue. Please let me know if any other debug information is required

**Comment by charpeni** [comment]
What are you trying to do? 

It seems you're trying to build React Native from source? If so, please follow these steps : https://facebook.github.io/react-native/docs/android-building-from-source.html

**Comment by konark-hike** [comment]
@charpeni Yes, tried with above steps and have verified them as per the doc but build is getting failed because of above error

**Comment by damusnet** [comment]
@facebook-github-bot stack-overflow

**Comment by evasyuk** [comment]
nice man @Leone90 created PR to fix this

https://github.com/facebook/react-native/pull/18404/files
