### ISSUE TITLE
Unable to select text of text component in ios

### ISSUE THREAD

**Issue by sar-app** [facebook/react-native#10897]
### Description
In ios, the text within Text component is not able to be selected

Is there a reason this has been left out for ios and only created for android?
Is there a temp work around?

**Comment by leeight** [comment]
1. https://github.com/facebook/react-native/pull/8028
2. https://productpains.com/post/react-native/support-selecting-text-within-text-elements-for-copypaste-etc

**Comment by ericvicenti** [comment]
Thanks @leeight!

@sar-app, feel free to vote this issue up on product pains so we might prioritize it. Or submit a pull request that fixes it- looks like a bunch of people would appreciate the contribution!
