### ISSUE TITLE
Webview functions

### ISSUE THREAD

**Issue by erikdung** [facebook/react-native#1090]
Hi,
is there any way to call webview function from react native?

**Comment by nicklockwood** [comment]
Which WebView functions do you want to call?

**Comment by erikdung** [comment]
In webview i load HTML page with javascript. I want to call JS function in React, is it possible? Thanks

**Comment by arthuralee** [comment]
I don't think this is possible at the moment, but it seems like it's something that could be added to RCTWebView pretty easily.

**Comment by brentvatne** [comment]
Seems like @oveddan will try to implement this, as per #1349
