### ISSUE TITLE
Build Failed : cleanReactNdkLib

### ISSUE THREAD

**Issue by konark-hike** [facebook/react-native#10912]
:clean UP-TO-DATE
:ReactAndroid:cleanReactNdkLib
Android NDK: /Users/konarkarora/Documents/ReactNewTry/node_modules/react/ReactAndroid/build/third-party-ndk/boost/Android.mk: Cannot find module with tag 'jsc' in import path    
Android NDK: Are you sure your NDK_MODULE_PATH variable is properly defined ?    
Android NDK: The following directories were searched:    
Android NDK:         
make: Entering directory `/Users/konarkarora/Documents/ReactNewTry/node_modules/react/ReactAndroid/src/main/jni/react/jni'
make: Leaving directory `/Users/konarkarora/Documents/ReactNewTry/node_modules/react/ReactAndroid/src/main/jni/react/jni'
/Users/konarkarora/Documents/ReactNewTry/node_modules/react/ReactCommon/cxxreact/Android.mk

**Comment by charpeni** [comment]
@facebook-github-bot duplicate #10895
