### ISSUE TITLE
[iOS] RefreshControl only appearing on top of first child in a horizontal ScrollView

### ISSUE THREAD

**Issue by fdnhkj** [facebook/react-native#10910]
### Description
I have a use case where I want to list horizontally cards.
I implemented it with a horizontal [ScrollView][1].

Then, for each card I want to implement the pull-to-refresh pattern to let the user manually refresh the data displayed in there.
I used therefore the [RefreshControl][2] component as an attribute of the ScrollView.

#### What I did

    <ScrollView
      contentContainerStyle={styles.container}
      horizontal
      pagingEnabled
      showsHorizontalScrollIndicator={false}
      directionalLockEnabled
      contentInset={{top: 1}}
      refreshControl={
        <RefreshControl
          refreshing={this.state.isRefreshing}
          onRefresh={this._onRefresh.bind(this)}
        />
      }
    >
      <Text style={styles.card}>First child</Text>
      <Text style={styles.card}>Second child</Text>
    </ScrollView>

#### What I expected
When the ScrollView is used horizontally, I would expect the RefreshControl component to appear on top of each child component (in this case a Card).

#### What happened
The issue is that on iOS, when I switch to another card than the 1st, I cannot see the RefreshControl component after doing the pull-to-refresh gesture (see gif below).
It looks related to this part of the code which explains that the RefreshControl is a child of the ScrollView: [Libraries/Components/ScrollView/ScrollView.js#L523-L529](https://github.com/facebook/react-native/blob/master/Libraries/Components/ScrollView/ScrollView.js#L523-L529)

[![horizontal scroll with refresh control iOS][3]][3] 

  [1]: https://facebook.github.io/react-native/docs/scrollview.html
  [2]: https://facebook.github.io/react-native/docs/refreshcontrol.html
  [3]: https://i.stack.imgur.com/7lSBM.gif

### Reproduction
https://rnplay.org/apps/sRXpEw

### Solution
No solution

### Additional Information
* More print screens: 
<img width="282" alt="capture d ecran 2016-11-13 a 15 33 16" src="https://cloud.githubusercontent.com/assets/5569608/20246513/841eb7ba-a9b8-11e6-9b66-514f7ba30048.png">

<img width="282" alt="capture d ecran 2016-11-13 a 15 33 16" 
src="https://cloud.githubusercontent.com/assets/5569608/20246533/de6cf3d0-a9b8-11e6-9ab4-20da5daf0842.png">

* React Native version: v0.37.0
* Platform: iOS
* Operating System: MacOS

**Comment by ericvicenti** [comment]
As far as I know, this is expected behavior of `refreshControl`- there is only supposed to be one. 

Would this work for your app?

```
<ScrollView
  contentContainerStyle={styles.container}
  horizontal
  pagingEnabled
  showsHorizontalScrollIndicator={false}
  directionalLockEnabled
  contentInset={{top: 1}}
>
  <ScrollView
    refreshControl={
      <RefreshControl
        refreshing={this.state.isRefreshing}
        onRefresh={this._onRefresh.bind(this)}
      />
    }><Text style={styles.card}>First child</Text></ScrollView>
  <ScrollView
    refreshControl={
      <RefreshControl
        refreshing={this.state.isRefreshing}
        onRefresh={this._onRefresh.bind(this)}
      />
    }><Text style={styles.card}>Second child</Text></ScrollView>
</ScrollView>
```

Feel free to re-open if you're sure this is a real bug. But keep in mind it is probably pretty low priority for anybody to fix. If you want to get it prioritized, please post on product pains so the community can vote on it!

**Comment by fdnhkj** [comment]
Indeed @ericvicenti I was wrong, my bad.
Thank you for the suggestion, it does the job 👍 

As I was not sure if it was a bug or an issue with my code, I posted [this question](http://stackoverflow.com/questions/40493187/refreshcontrol-only-appearing-on-top-of-first-child-in-a-horizontal-scrollview) also in stackOverflow.
Feel free to add your suggestion as an answer; I'll accept it!
Otherwise I can do it and mention this issue.
