### ISSUE TITLE
(Android) keyboardDidShow not called when TextInput in Modal

### ISSUE THREAD

**Issue by ivpusic** [facebook/react-native#10915]
I am trying to listen for keyboard events when clicking on TextInput which is rendered inside Modal window. On iOS this works great, but on Android works only if app is running in simulator. The device I am testing on is Samsung Galaxy S3.

Example which is not working: https://rnplay.org/apps/pHEDsg

* React Native version: 0.37
* Platform: Android Device

**Comment by lacker** [comment]
How exactly do I reproduce this problem from your example code? I clicked around but I could not find anything where the behavior seemed wrong.

**Comment by ivpusic** [comment]
When I run this code on Samsung Galaxy S3 then `alert('keyboard shown from modal');` is not called when clicking on TextInput which is located inside Modal window. On simulator as you can see it works.

**Comment by ivpusic** [comment]
update...ReactRootView#onGlobalLayout is not called when running on samsung galaxy s3, therefore there is no chance to trigger event. @lacker any ideas?

**Comment by lacker** [comment]
Is this only happening on a Samsung Galaxy S3 or can you also repro it on other Android devices?

**Comment by ivpusic** [comment]
currently only for s3.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/android-keyboarddidshow-not-called-when-textinput-in-modal
