### ISSUE TITLE
How to create absolute slide menu ?

### ISSUE THREAD

**Issue by kfir91** [facebook/react-native#10911]
Hello i want slide menu like this:
https://github.com/react-native-community/react-native-side-menu

Now when i click open button its push right  the content and open the menu
but i want that when i click open button its show the menu above the content without push it...

how to do it?

**Comment by Sommerfeld** [comment]
https://github.com/root-two/react-native-drawer provides different behaviors. Check the type property.

**Comment by kfir91** [comment]
@Sommerfeld tnx for your help,
i saw this and its very big code i need a simple one,
button that open menu and close above the content without anything...

**Comment by Sommerfeld** [comment]
Okay, i guess you could just initially position the sidemenu with position: 'absolute', left: -sideMenuWidth inside your uppest view in the hierarchy.

**Comment by charpeni** [comment]
@facebook-github-bot stack-overflow
