### ISSUE TITLE
requiring module "557", which threw an exception

### ISSUE THREAD

**Issue by omhybrid** [facebook/react-native#10921]
![screenshot_2016-11-14-11-06-39](https://cloud.githubusercontent.com/assets/22111807/20254474/fe4e81c6-aa5a-11e6-9536-c65c4ae436cb.jpeg)

* React Native version: 0.37.0
* Platform: Android
* Operating System:  Windows7

**Comment by ericvicenti** [comment]
Hey, thanks for reporting this issue!

What code is causing this error? Please post an example app on rnplay.org, if you can.

I am going to close this, but we can reopen if additional information is provided. Thanks!
