### ISSUE TITLE
Navigator swiping back gesture will cause jittering sometimes on Android

### ISSUE THREAD

**Issue by narychen** [facebook/react-native#10923]
I find this weird behavior on all of my android phones, but not on any of my iphones.
I use the debugging to finally track the code cause this in Libraries/CustomComponents/Navigator/Navigator.js. 
```
_handlePanResponderTerminate: function(e, gestureState) {
    if (this.state.activeGesture == null) {
      return;
    }
    var destIndex = this.state.presentedIndex + this._deltaForGestureAction(this.state.activeGesture);
    this._detachGesture();
    var transitionBackToPresentedIndex = this.state.presentedIndex;
    // slight hack: change the presented index for a moment in order to transitionTo correctly
    this.state.presentedIndex = destIndex;  //========>This line will cause the weird bug
    this._transitionTo(
      transitionBackToPresentedIndex,
      null,
      1 - this.spring.getCurrentValue()
    );
  },
```
Remove the line of 'this.state.presentedIndex = destIndex; ' will fix the bug.
And I tested a lot of times on android and ios and haven't seen anything wrong yet.
But I don't know why. This code exists in _handlePanResponderRelease also. It cannot be removed, delete it will break up the transition.
Anyone knows any ideas?

**Comment by ericvicenti** [comment]
Is this a new bug or has it always been there?

If this is just a minor visual glitch then I don't think we will be able to fix it, because we are now focusing on new navigation views like NavigationCardStack.

Feel free to send in a fix, if you can figure it out!
