### ISSUE TITLE
[iOS][TextInput] emoji after a new line make the line disappear

### ISSUE THREAD

**Issue by ahanriat** [facebook/react-native#10929]
### Description

On **controlled** `TextInput`, adding an emoji after a new line make the line disappear.
Adding whatever character after make the line appear again.

### Reproduction

The code https://rnplay.org/apps/XmdwqQ

![screen capture on 2016-11-14 at 11-58-02](https://cloud.githubusercontent.com/assets/1374161/20262350/2419afb4-aa62-11e6-8248-409e037747d4.gif)

### Additional Information

**React Native**: reproduced on `0.36.0`, `0.37.0` & `0.38.0-rc.0`
**Platform**: `iOS`
**Component**: `TextInput`

Thanks for your help 🚀 

## Edit 11/21/2016
The issue disappears when forcing the `lineHeight` of the `Text`. ( Thanks @linmic )

**Comment by vinch** [comment]
Same issue.

**Comment by linmic** [comment]
@ahanriat Use the `value` property instead? Is there any reasons should you wrap another `<Text>` in `<TextInput>`?

**Comment by vinch** [comment]
@linmic Indeed, if I use the `value` property instead of having a `<Text>` inside the `<TextInput>`, I don't have the problem anymore. I think I had to do that because font styles were not applied to `<TextInput>` but the bug seems to have been fixed since then: https://github.com/facebook/react-native/issues/2140
Thanks!

**Comment by ahanriat** [comment]
@linmic thanks for the tips (*lineHeight*), it fixes the issue for me.
I'll update the description of the issue to provide some hints to fix this for good.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/iostextinput-emoji-after-a-new-line-make-the-line-disappear

**Comment by KavithaSaras** [comment]
@ahanriat can you please share this plugin link?
