### ISSUE TITLE
react-native run-android command not working on mac sierra

### ISSUE THREAD

**Issue by ruci06** [facebook/react-native#10939]
* React Native version: 0.37.0
* Platform: Android
* Operating System: Mac sierra

I tried to run react-native app on my mobile phone SAMSUNG GALAXY A7.
Device's android version is 6.0.1.
I installed Android SDK through brew, and also installed Android SDK Tools, Platform-tools, Build-tools, APIs, SDK Platform for android 6.0(API23)
I checked device is connected via android file transfer.
I agreed usb debugging on my android phone.

When I try to run command run-android, there   @@was few DeperecatonWarning.
 
I attach log below.

`
(node:4265) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
(node:4265) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.
JS server already running.
Running adb -s ce0ee0d3 reverse tcp:8081 tcp:8081
Building and installing the app on the device (cd android && ./gradlew installDebug...
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment.
Go to https://facebook.github.io/react-native/docs/getting-started.html
and check the Android tab for setup instructions.
`

Is there anything I could try to run app on android phone?

**Comment by ericvicenti** [comment]
What happens when you run `adb list`?

Is your phone switched into developer mode?

**Comment by ruci06** [comment]
When I run `adb devices -l`
My mobile phone's information show up
`
ce0ee0d3               device usb:336670720X product:a7ltektt model:SM_A700K device:a7ltektt
`

I turned on developer mode and also let mac has usb debugging authority.

**Comment by ruci06** [comment]
* Update
I did success to run tutorial app on my phone,
But my custom app still failed to install on the device.

**Comment by ruci06** [comment]
* Update <br/>
I removed my custom app package from mac, and remake it with `react-native init customApp`<br/>
And restore `package.json` file and `index.android.js` file from previous package.<br/>
Then it worked! <br/><br/>
I recently buy macbook, and bring source code from windows 8 to mac via git.<br/>
Is there diffrence of gradle file generation between windows and mac?

**Comment by ericvicenti** [comment]
Glad you got it working! I'm not sure about differences in behavior with gradle. If you find any specific problems with it, please file a specific issue, with enough details for people to reproduce it.

**Comment by corymayer** [comment]
I got mine working by deleting the android folder and running `react-native upgrade`.

**Comment by connercms** [comment]
@corymayer This solution worked for me. Started project on Windows, source control to GitHub, purchased a MacBook and cloned the project. react-native run-android did nothing. Deleted android folder, ran react-native upgrade and it is working perfect now

**Comment by simba4everyoung** [comment]
@corymayer Thanks! Saved my day!
