### ISSUE TITLE
base64 does not work tried several npm packages

### ISSUE THREAD

**Issue by anupkale1984** [facebook/react-native#10937]
https://github.com/dankogai/js-base64
https://github.com/feross/buffer
Always get error for Buffer npm package.

**Comment by alekseykarpenko** [comment]
Same in RN 0.41.0, but cannot reproduce in 0.29.0

**Comment by alekseykarpenko** [comment]
Related to #4968

**Comment by alekseykarpenko** [comment]
Just run:
`npm install --save buffer`

Thx to @PaulBGD

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/base64-does-not-work-tried-several-npm-packages
