### ISSUE TITLE
Cannot find module './assets/empty-module.js'

### ISSUE THREAD

**Issue by ErkanSensei** [facebook/react-native#10938]
Whenever I try to run react-native I get this error: 

```
react-native run-ios
module.js:474
    throw err;
    ^

Error: Cannot find module './assets/empty-module.js'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.resolve (internal/module.js:27:19)
    at Object.<anonymous> (/Users/esen/Github/App/node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/ResolutionRequest.js:20:29)
    at Module._compile (module.js:573:32)
    at loader (/Users/esen/Github/App/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/esen/Github/App/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
```
* React Native version: 0.37.0
* Platform: Both
* Operating System: MacOS

**Comment by ErkanSensei** [comment]
Uninstalling and reinstalling react-native seems to have fixed the error.

**Comment by rjz** [comment]
Also ran into this; `touch`-ing <code title="a rose, by any other name...">empty-module.js</code> also seems to do the trick:

```
$ (
  cd node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/
  mkdir -p assets
  touch assets/empty-module.js
)

**Comment by rroehrig** [comment]
We had the same problem when using **yarn**. Creating the empty-module.js by hand is just a quickfix which was not an option for our build server.
Thanks to the yarn community it turned out to be a conflict with the `.yarnclean` file which contained the assets directory.

**Deleting the line `assets` in the `.yarnclean` solved the problem.**

**Comment by dsummersl** [comment]
I ran into this when I innadvertantly ran `yarn clean`. Uninstalling and reinstalling worked - touching the assets/empty-module.js ultimately did not (just ran into more missing files when running my app in the emulator).

**Comment by rroehrig** [comment]
Did you check the `.yarnclean` file which is automatically created when running `yarn clean`?

**Comment by dsummersl** [comment]
Since I didn't intend to run `yarn clean` I removed `.yarnclean` and reinstalled the module - sounds like removing `assets` from `.yarnclean` would work too.

**Comment by duduindo** [comment]
@dsummersl Thanks very much!

**Comment by pricetula** [comment]
directory doesnt exist >> node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/

**Comment by deot** [comment]
@rroehrig Thanks;

delete `.yarnclean` and reinstall
