### ISSUE TITLE
When the PagingEnabled is true,the HorizontalScrollView's paddingRight is invalid...

### ISSUE THREAD

**Issue by zy5123299** [facebook/react-native#10940]
### Description

ScrollView horizontal={true} pagingEnabled={true} contentContainerStyle={{paddingHorizontal : 40}}

### Solution

PaddingLeft(40) is valid，but PaddingRight is invalid，why?

### Additional Information

* React Native version: 0.37.0
* Platform: Android
* Operating System: Windows

![default](https://cloud.githubusercontent.com/assets/19965309/20299639/c5e68df4-ab56-11e6-80b4-9aa14c18656e.png)
![1](https://cloud.githubusercontent.com/assets/19965309/20299652/d04032d2-ab56-11e6-8564-c878348b69c6.png)

![2](https://cloud.githubusercontent.com/assets/19965309/20299695/fdf3bb4a-ab56-11e6-8ea7-8bc5c06591ba.png)

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
