### ISSUE TITLE
Open facebook Messenger Android error: Some dialogs are only supported starting API 14

### ISSUE THREAD

**Issue by RaphArbuz** [facebook/react-native#10959]
Hi everyone!

I'm opening a Facebook Messenger dialog with the following code:

```
MessageDialog.canShow(this.state.messageContent).then(function(canShow) {
       return MessageDialog.show(tmp.state.messageContent);
    }).then(function(result) {

      if (typeof result == "undefined")
        return;

      if (result.isCancelled) {
        alert('Share operation was cancelled');
      } else {
        alert('Share was successful with postId: ' + result.postId);
      }
    },
    function(error) {
      alert('Share failed with error: ' + error);
    }
  );
```
This works fine on Android 4, but not on Android 6. I get the following error message: "Share failed with error. Error: Unable to show the provided content via the web or the installed version of the Facebook app. Some dialogs are only supported starting API 14."

The latest version of the Facebook app is installed on the device and I'm using the latest facebook SDK (4.17).

Any help or fix would be greatly appreciated.

Many thanks.

Raphael

**Comment by RaphArbuz** [comment]
@ericnakagawa as discussed at FbStart, if you get a chance to have a look that would be great! Many thanks.

**Comment by RaphArbuz** [comment]
No one has a clue? Am I not posting in the right place? Any comment would help a lot. Many thanks!

**Comment by RaphArbuz** [comment]
Seems like it was because Facebook Messenger wasn't installed on the device. Calling the web function does not seem to work from Android 6.0.
The error message could be made clearer I think.

**Comment by mkonicek** [comment]
What is `MessageDialog`? Glad you resolved this in the end! Can you send a pull request to improve the error message please?

**Comment by RaphArbuz** [comment]
I think this is part of https://github.com/facebook/react-native-fbsdk will check how I can help.
