### ISSUE TITLE
Android: image-size internal Error code 500

### ISSUE THREAD

**Issue by abbasfreestyle** [facebook/react-native#10950]
This error is driving me mad!

My project was working perfectly a moment ago. I decided to create images to fit screen sizes accordingly image1@2x.png image2@2x.jpg etc.

when i do `react-native run-android` it builds successfully but i get this screen and this error in the Packager

![screenshot_20161115-144628](https://cloud.githubusercontent.com/assets/3793135/20310433/dec5e53a-ab43-11e6-952c-4e25b8421842.png)

`TypeError: unsupported file type
    at lookup (/Users/me/Apps/reactApp/node_modules/react-native/node_modules/image-size/lib/index.js:35:9)
    at /Users/me/Apps/reactApp/node_modules/react-native/node_modules/image-size/lib/index.js:93:22
    at /Users/me/Apps/reactApp/node_modules/react-native/node_modules/image-size/lib/index.js:50:9
    at /Users/me/Apps/reactApp/node_modules/react-native/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:82:15)`

i'm requiring my images like so `<Image source={require('image1.png')} />`

all image extensions are .png and .jpg . no filenames are using special characters

I've even recreated a fresh project and again i run into this.

I've even restored the images back to how it was working before and this error wont go away :(

* React Native version: 0.37
* Platform: Android 6.0.1
* Operating System: MacOS Sierra

**Comment by abbasfreestyle** [comment]
Resolved.

.jpg was the cause behind this.

I used 'Export As...' in photoshop for different suffix and strangely the file type was not supported

I manually used 'Save for web (Legacy)' and the EXACT .jpg files worked

This is a very strange issue. Maybe it doesn't read all .jpg types?

**Comment by antoinerousseau** [comment]
Same thing happened to me, thanks for the hint!
