### ISSUE TITLE
JS has only made partial progress to catch up to UIKit

### ISSUE THREAD

**Issue by jbhatab** [facebook/react-native#1095]
This was a really weird random error. I'll do my best to explain what happened. I have a 3 deep nested layout. So the first page is a list of models. then you click on the models to get master detail lists. When I click around a lot in the master detail page and go back to the dashboard, it gives me this error. 

I feel like it has to do with me clicking too fast and triggering things too fast, but how can I prevent this?

[error][tid:main][RCTNavigator.m:471] JS has only made partial progress to catch up to UIKit

![ios simulator screen shot may 1 2015 12 24 22 pm](https://cloud.githubusercontent.com/assets/2458718/7434096/212b62aa-effd-11e4-8968-f87b331e3af6.png)

**Comment by brentvatne** [comment]
[This has been reported a bunch already](https://github.com/facebook/react-native/issues?utf8=%E2%9C%93&q=JS+has+only+made+partial+progress), #65 being the earliest report of it :smile:

I'd recommend searching issues in the future when you run into issues like this, you might even find a solution that way!
