### ISSUE TITLE
[Android] RecyclerViewBackedScrollView + renderFooter scroll issue

### ISSUE THREAD

**Issue by tegon** [facebook/react-native#10955]
The issue is demonstrated here: https://rnplay.org/apps/-Z8HIQ.

If I render a ListView using the `RecyclerViewBackedScrollView` and a `renderFooter` function, the list is already scrolled on render, without any user interaction. This doesn't happen in iOS and with `ScrollView` as a render component.

Please note that the first item that appears is ID: 4, when it should be ID: 1. If you scroll up, you'll see the beginning of the list.

The code is basically this:

```javascript
<ListView
  dataSource={this.state.dataSource}
  renderRow={this.renderRow.bind(this)}
  renderFooter={this.renderFooter.bind(this)}
  renderScrollComponent={props => <RecyclerViewBackedScrollView {...props} />}/>
```

If I remove the render footer function or the render scroll component, It works correctly.
Also, this doesn't happen if the list doesn't have enough items to scroll. (Fits in the screen).

* React Native version: 0.36.1
* Platform: Android

**Comment by lacker** [comment]
That is quite odd. Do you have any idea why this bug is happening?

**Comment by tegon** [comment]
No idea. I was able to fix this by adding an `initialListSize={1}` to the list. Although I don't know if it is the best solution.
My guess is that is something with the footer, since I have an activity indicator on the end of the list, and by adding the initial list size I forced the list to re-render.

**Comment by jjdp** [comment]
+1

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/android-recyclerviewbackedscrollview--renderfooter-scroll-issue
