### ISSUE TITLE
onRegionChangeComplete is called multiple times for a single region change

### ISSUE THREAD

**Issue by RobinClowers** [facebook/react-native#10961]
### Description

Render a MapView with a region from state, then call `setState` with a different region. While the map is still moving, `onRegionChangeComplete` is called, then it is called again when it's actually done moving. According to the docs, it should only be called when the move is complete.

### Reproduction

I couldn't get my sample to run on rnplay.com, so here is a gist: https://gist.github.com/RobinClowers/13fe738fa9affee5a2b84ab09420e036.

### Solution

`onRegionChangeComplete` should only be called once per region update.

### Additional Information

* React Native version: 0.33.0
* Platform: iOS
* Operating System: MacOS

**Comment by RobinClowers** [comment]
I also tried upgrading to the react-native 0.37 and I still experienced the issue.

**Comment by christopherdro** [comment]
Hey @RobinClowers. 
Mapview has been deprecated and removed from the core library.

I would suggest trying this library as a replacement.
https://github.com/airbnb/react-native-maps
