### ISSUE TITLE
How to spaces at the end of placeholder text in TextInput?

### ISSUE THREAD

**Issue by binzailani3136** [facebook/react-native#10965]
### Description
`<TextInput
       placeholder = 'Email                     '     // I would like to add some spaces at the end of text 'Email'
       keyboardType = 'email-address'}/>
</TextInput >`

But when I put spaces at the end of Email                            like this, it doesn't work.
It seems that spaces are ignored.

![screen shot 2016-11-16 at 3 09 55 pm](https://cloud.githubusercontent.com/assets/20284956/20337896/c1708bae-ac0e-11e6-9145-5f8d66f382eb.png)

The reason why I want to do like this is - Centre position of Login button text and Email placeholder text, password placeholder text is not match.
You can see about that from the above screenshot.

Is there anyway to handle this issue?

Thanks

**Comment by mdamien** [comment]
You could use a [non-breaking space](https://en.wikipedia.org/wiki/Non-breaking_space), it's `'\xa0'`.

**Comment by binzailani3136** [comment]
Thanks for your reply.
But It seems it's not working....
I tried like this.
`placeholder = {"Email" + '\xa0' + '\xa0' + '\xa0' + '\xa0' + '\xa0'+ '\xa0'+ '\xa0'+ '\xa0'+ '\xa0'+ '\xa0'+ '\xa0'+ '\xa0'+ '\xa0'+ '\xa0'}`

**Comment by mdamien** [comment]
Looks like the expected way to use it inside `placeholder` is `placeholder="Email&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"`.

To be clear, I wouldn't suggest this a the best way to re-center your labels.

You can use `style={{ paddingRight: 40 }}` for example. Or make the icons overlap the TextInput while having a `paddingRight` on the TextInput.

**Comment by binzailani3136** [comment]
Thanks so much

**Comment by charpeni** [comment]
@facebook-github-bot answered
