### ISSUE TITLE
TextInput maxlength cuts Unicode caracters (Emojis)

### ISSUE THREAD

**Issue by jpolack** [facebook/react-native#10964]
Hello everyone,

yesterday i noticed that a TextInput has a problem displaying Emojis at the end of the fields maxlength. 
If i insert the "white happy man with black hair raising one hand" Emoji (iOS) at the position maxlength-1 it shows a square with an "A" in it instead.
If i insert the "white happy man with black hair raising one hand" Emoji (iOS) at the position maxlength-2 it shows a square with an "yellow happy woman with blonde hair raising one hand" in it instead.
If i insert the "white happy man with black hair raising one hand" Emoji (iOS) at the position maxlength-3 it shows a square with an "white happy woman with black hair raising one hand" in it instead.
If i insert the "white happy man with black hair raising one hand" Emoji (iOS) at the position maxlength-4 it shows a square with an "yellow happy woman with blonde hair raising one hand" and the square with an "A" in it instead.

Seems like the maxlength cuts the unicode sign at the end and causes to show different Emojis than inserted

* React Native version: 0.36
* Platform: iOS - tested on iOS 10.1.1

**Comment by ericvicenti** [comment]
Might be related to this?

https://github.com/facebook/react-native/issues/10929

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.

**Comment by euharrison** [comment]
This also happen with me. 

We have `maxLength={4}` and this is what happen in different cases:
- type: `mmmm` then works perfect
- type `mm😀` then it reach the limits (emojis count 2 characters)
- type `😀😀` then it reach the limits (emojis count 2 characters)
- type `m😀😀` then it breaks the limits with "5" characteres and bug cleaning all text


![ezgif-5-209c8d19ac](https://user-images.githubusercontent.com/557598/35055111-7f8181bc-fb95-11e7-9d6f-4503460d3955.gif)

**Comment by KavithaSaras** [comment]
@euharrison can you please share this plugin?
