### ISSUE TITLE
integrate with existing App, code didn't work

### ISSUE THREAD

**Issue by RockyAo** [facebook/react-native#10969]
I integrate react-native  in my App, but there are somethings  wrong here. 
* I set borderRadius ,but only three corner worked(Top left,bottom left and the bottom right)
* I use listView and scrollView ,but when the container overflow the screen , it still can't scrool.(I had set the father view  flex:1)

Two problems both happened in iOS system.

I don't know what happened to my code . so I create a New empty iOS project . And loaded the same Javascipt code .   All those code worked correct.So I think the there are some problem with my existing 
iOS project.But I don't know what cause these problems .  anyone known?

**Comment by ericvicenti** [comment]
Without more details on a specific issue, some example code, and a description of what you're trying to do, there's not much we can do to help.
