### ISSUE TITLE
Error while updating property 'numberOfLines' in shadow node of type: RCTText

### ISSUE THREAD

**Issue by testshallpass** [facebook/react-native#10979]
### Description

I am using `<Text />` component and I pass in `numberOfLines` and set it's value to `Number.SAFE_MAX_INTEGER` (actual value: 9007199254740991) and it crashes with message. 

### Reproduction

https://rnplay.org/apps/keDfsg

### Solution

Allow for large integers or let 0 be unlimited like iOS does.  

### Additional Information

* React Native version: 0.36.0
* Platform: Android
* Operating System: macOS

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
