### ISSUE TITLE
[Image + Packager] Warn when can't find require for images

### ISSUE THREAD

**Issue by umhan35** [facebook/react-native#1098]
Hello,

A very weird thing happened. I have code `<Image source={require('image!weather_ic_'+icon_code)} style={s.icon} />` where icon_code = '01', and I got an error saying 

```
Requiring unknown module "image!weather_ic_01". If you are sure the module is there, try restarting the packager.
```

But when I change `'image!weather_ic_'+icon_code` to `'image!weather_ic_01`, it works. But they are the same value...

I don't know why this happens. Probably the `require` function?

**Comment by ide** [comment]
`require` needs a string literal so the build tools can statically resolve the resources, as mentioned here https://facebook.github.io/react-native/docs/image.html#static-assets.

Perhaps the packager should warn if it finds `require()` calls that it can't resolve, although this might be too noisy when taking 3rd-party packages into account. Maybe a practical balance is just to warn for `custom!` resources. cc @amasad 

 If you have hundreds of images, I recommend writing a script / editor macro that generates a large lookup table of image sources. For example:
```
var imageSources = {
  '01': require('image!weather_ic_01'),
  '02': require('image!weather_ic_02'),
  '03': require('image!weather_ic_03'),
  ...
};
```
Then you can write `<Image source={imageSources['01']} />`.

**Comment by umhan35** [comment]
Oh, I see. I understand that better now. Thanks

**Comment by amasad** [comment]
>Perhaps the packager should warn if it finds require() calls that it can't resolve, although this might be too noisy when taking 3rd-party packages into account. Maybe a practical balance is just to warn for custom! resources. cc @amasad

Yeah, too noisy, we also have a few "unresolved" requires in core. warning for custom! resources sounds good.

**Comment by satya164** [comment]
Is this fixed?

**Comment by brentvatne** [comment]
We haven't heard back in a month so closing.
