### ISSUE TITLE
Native animations implementation on Android

### ISSUE THREAD

**Issue by Roconda** [facebook/react-native#10986]
### Description
Is there some example or documentation about implementing native animations on Android?

### Additional Information

* React Native version: 0.37.0
* Platform: Android
* Operating System: MacOS

**Comment by nihgwu** [comment]
Read the damn code
Check the example in UIExplorer

**Comment by mkonicek** [comment]
Yup, code and UIExplorer is the way to go.

**Comment by mkonicek** [comment]
If by implementing you mean writing Java. If you want to use native animated, just pass `useNativeDriver` to the animation.
