### ISSUE TITLE
BackAndroid can not add listener

### ISSUE THREAD

**Issue by anhuiliujun** [facebook/react-native#10987]
### Description

* I use react-native-router-flux to manage navigation，it has a default BackAndroid behaviour
```
componentDidMount() {
    BackAndroid.addEventListener('hardwareBackPress', this.handleBackAndroid);
  }
  componentWillUnmount() {
    BackAndroid.removeEventListener('hardwareBackPress', this.handleBackAndroid);
  }
```
* when i first open the app in android，it works as expected，and i use the back button to put the app running on background.
* but when i then make the app on foreground again，the back button just can not work。
* I debug into the code of BackAndroid.android.js。
```
RCTDeviceEventEmitter.addListener(DEVICE_BACK_EVENT, function() {
  var backPressSubscriptions = new Set(_backPressSubscriptions);
  var invokeDefault = true;
  var subscriptions = [...backPressSubscriptions].reverse();
  for (var i = 0; i < subscriptions.length; ++i) {
    if (subscriptions[i]()) {
      invokeDefault = false;
      break;
    }
  }

  if (invokeDefault) {
    BackAndroid.exitApp();
  }
});
```
and found that the code only run once。
### Solution
May be because the BackAndroid module only be import once? 

### Additional Information

* React Native version: 0.35.0
* Platform: Android
* Operating System: MacOS

**Comment by ericvicenti** [comment]
Hi, can you please put an example snippet on rnplay.org that demonstrates this issue?

**Comment by anhuiliujun** [comment]
I think it is my fault. I just do as follows, and it works.
```
rm -rf node_modules/
npm install
```
But I just do not know why.

**Comment by rafales** [comment]
I'm running into the same issue. Turns out that `Array.from(new Set([1, 2, 3]))` returns empty array for me (which is called when using spread operator to convert set to array (`[...something]`). Don't know why this happens. We have our dependencies shrinkwrapped so probably there is a fix to this in one of the dependencies already.

**Comment by rafales** [comment]
@anhuiliujun any idea how did you get this working again?

**Comment by sarahmarciano** [comment]
I met the same problem, @rafales did you solve it??

**Comment by rafales** [comment]
We created custom back android module which did not use sets under the hood.
