### ISSUE TITLE
[0.37] Issue with flexGrow replacing flex: 1.

### ISSUE THREAD

**Issue by ConnorJWilliams** [facebook/react-native#10988]
### Description

Since upgrading to 0.37, as noted within the commits, flex: 1 has now been replaced with flexGrow/flexBasis etc... Although, flexGrow doesn't seem to be behaving as it should, with flexGrow: 1 being on the parent View - I was expecting this to take the full height of the screen and/or available space - like flex: 1 did. Instead, flexGrow on the parent and child Views seem to be doing nothing and vise versa.

### Reproduction

Example code (excluding imports):

Container (called from an action): 

~~~~
return(
 <Activity />
)
~~~~

Page (excluding functions and custom component imports):
~~~~
<View>             
 <TitleBar pageTitle={title} rightIconName={this.state.showNavigation && !this.state.selectedItem ?  navigationActiveIcon : navigationDisabledIcon }
      secondaryIconName={secondaryIconName} secondaryIconPress={() => 
      ExternalAppUtils.openApp(config.urls.zendesk, 'zendesk')}
      rightIconPress={this.showNavigation.bind(this)}/>
       {(!!this.state.showNavigation && !this.state.selectedItem) && <ActivityNav style={{ padding: 15 }} />}


  { loading && !this.state.loadedInitial ? <Loading /> : (
     this.state.items.getRowCount() === 0 ? (
         <View style={{ flexGrow: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: 'red' }}>
             <Text style={{ fontSize: 21, color: 'black', fontWeight: '300' }}>There are no slips to display</Text>
           </View>
         ) : (
           <ScrollView
                  refreshControl={
                      <RefreshControl
                          refreshing={this.state.isRefreshing}
                            onRefresh={this.props.refresh}
                            />
                        }
                        ref="activityScroll" style={Styles.container}>
                            <ListView

                                initialListSize={7}
                                dataSource={this.state.items}
                                renderRow={this.renderActivityItem.bind(this)}
                            />
                    </ScrollView>
                    )
                )}
                
        </View>
        )
    }
~~~~

### Additional Information

* React Native version: 0.37.0
* Platform: Android
* Operating System: Linux

**Comment by ryankask** [comment]
Where are you reading that `flex: 1` is being replaced? I've run into some other issues related to this and `ScrollView` but 

```
<View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
  <Text style={{ fontSize: 21, color: 'black', fontWeight: '300' }}>There are no slips to display</Text>
</View>
```
should work fine.

**Comment by ConnorJWilliams** [comment]
The above code causes the component to disappear completely i.e. not even showing a backgroundColor to shown the View itself is being rendered, but not the Text for example.

**Comment by ryankask** [comment]
That's strange because it's working here.
<img width="100" alt="2016-11-17 at 10 32" src="https://cloud.githubusercontent.com/assets/81891/20385900/387e8e38-acb1-11e6-98ff-ec56dad751c6.png">

```
function MyComponent() {
    return (
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center', 'backgroundColor': 'lavender' }}>
        <Text style={{ fontSize: 21, color: 'black', fontWeight: '300' }}>There are no slips to display</Text>
      </View>
    );
  }
```

**Comment by ConnorJWilliams** [comment]
I've updated OP with a more accurate, but still stripped example of what the component looks like.

**Comment by ryankask** [comment]
It's really difficult to say given that it isn't a full example but you need to add `flex: 1` to the parent `View` which has no style at the moment.

**Comment by ConnorJWilliams** [comment]
Yeah I understand it's difficult. But for this component, that's all there is. When `flex:1 `is added to the parent `View`, it doesn't render the component. We've had to remove a lot of flex: 1 throughout the app since upgrading to 0.37 and use flexGrow instead. It's worked on all other pages bar this one. Hence why I thought this was an issue. 

I've added flex: 1 to all parent Views and flexGrow etc... in all different combinations. The 2 results are either the component stays clipped i.e the Text is at the top of the View, or the component doesn't render at all...

**Comment by ConnorJWilliams** [comment]
For the time being, I'm just going to set the height of the View via Dimensions. This is the only page where this issue occurs and seeing as this View only occurs when no results are found and is static, this should suffice for now. Thanks for your comments. :)

**Comment by ryankask** [comment]
Is there any reason you're `flex: 1` everywhere?  There was a change in 0.36 but it didn't require you replace it everywhere, only in cases where it didn't have any effect and when I upgraded the layout looked broken.

**Comment by ConnorJWilliams** [comment]
It wasn't so much everywhere - we just have a lot of pages and complex structures that required us setting flex: 1, then breaking components down via `flex: 0.3` etc... on flexDirections. We upgraded from 0.24 to 0.37 (yes a big jump). So we had a lot of old ways of doing things.

**Comment by ryankask** [comment]
Sorry I had a typo, I meant "Is there any reason you're *replacing* `flex: 1` everywhere?" I don't think there is an old/new way.

**Comment by ConnorJWilliams** [comment]
Ahh we had a lot of issues with the styling of the app when we upgraded. Components not rendering, shrunk down placements etc... which were tracked down to flex: 1 by my colleagues.
