### ISSUE TITLE
Packager server does not inherit REACT_NATIVE_APP_ROOT env

### ISSUE THREAD

**Issue by EmielM** [facebook/react-native#10992]
### Description

`REACT_NATIVE_APP_ROOT` is not inherited when `launchPackager.command` is run by `React.xcodeproj/project.pbxproj`. When using a custom app root, that means the Packager server does not serve from the custom app root, but always `../../` relative to `node_modules/react-native`.

### Additional Information

* React Native version: 0.37
* Platform: Mac
* Operating System: MacOS sierra

### Solution

React's `project.pbxproj` uses `open "$SRCROOT/../packager/launchPackager.command"`, and although `man 1 open` states that open should inherit environment variables, I suspect it does not do so because Terminal spawns a new shell from an existing base process.

Not sure how it should be fixed, writing these variables out to some file and re-reading them inside the launched script feels hacky.

### Context
I use a custom directory scheme for my project as follows:

```
root/
  node_modules/
  app/
    ios/
    android/
    reactNativeStuff..
  web/
  backend/
```
(in effect, node_modules is located one level up - for various reasons outside the scope here)

Now, the `react-native` cli has a bunch of assumptions that the app root is where `node_modules` is located, but I found that `REACT_NATIVE_APP_ROOT` env-var can be used to override the app root. Because `react-native` does not scan parent directories to find the cli entrypoint (is that wanted behavior maybe?), I have wrapped the cli logic in a custom `app/cli.js`:

```js
#!/usr/local/bin/node
let process = require('process');
process.chdir(__dirname);
process.env.REACT_NATIVE_APP_ROOT = __dirname;
require('../node_modules/react-native/cli.js').run();
```

All seems to work except the packager server that still serves from `root/` instead of `root/app` because `REACT_NATIVE_APP_ROOT` is unset in all processes in the new terminal window.

**Comment by lacker** [comment]
Is this actually supported behavior? I can't find anything about `REACT_NATIVE_APP_ROOT` in the docs.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/packager-server-does-not-inherit-reactnativeapproot-env
