### ISSUE TITLE
In addition to shaking there are other ways to reload it?

### ISSUE THREAD

**Issue by qiankunpig** [facebook/react-native#10995]
now we can use the shaking mobile to reload js,but that is so trouble.Is any other way to do?

**Comment by pvinis** [comment]
it would be nice if xcode could emulate a shake on a real device..

**Comment by linmic** [comment]
If you are on Mac. You might want to try https://github.com/niftylettuce/frappe.

**Comment by pvinis** [comment]
i will try it. even though i want it for ios devices.
is there a way to open the dev menu programmatically? so maybe i can make an overlay or something and tap that button. even though thats not the best solution.

**Comment by ohtangza** [comment]
I am developing activity recognition application based on RN, and this shake gesture conflicts with my core logic which makes use of accelerometer signals. This needs to be enhanced for the apps encompassing sensor utilization!

**Comment by mienaikoe** [comment]
Something more subtle would be great! The people at the coffee shop are starting to wonder about me.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/in-addition-to-shaking-there-are-other-ways-to-reload-it
