### ISSUE TITLE
when automaticallyAdjustContentInsets for android will be implemented?

### ISSUE THREAD

**Issue by jsappme** [facebook/react-native#10997]
for scrollview and listview

**Comment by ericvicenti** [comment]
I haven't heard of a plan to do this. Feature requests like this should be posted on product pains, so the community can vote on it. If it gets enough votes, the core team will know to prioritize it!

To see what we have prioritized, RN's public roadmap is here: https://github.com/facebook/react-native/wiki/Roadmap

**Comment by jsappme** [comment]
very sad for this
