### ISSUE TITLE
[Touchable] Support hit test slop for touchable components

### ISSUE THREAD

**Issue by ide** [facebook/react-native#110]
For example, if you have a small button it is useful to make it easier to touch by increasing the hit test bounds. See "Button Nodes" on http://asyncdisplaykit.org/guide/ for example.

**Comment by brentvatne** [comment]
@ide - did you ever look into this?

**Comment by ide** [comment]
Last I looked at the touch handler the easiest way would be to override the hit testing of views. I haven't experimented with this, just have been making my views bigger to compensate for now.

**Comment by sahrens** [comment]
I'm going to close this out - if you come up with an elegant solution, put up a PR?

**Comment by ide** [comment]
Reopening this since we're actively working on a hit-test slop API that works across iOS and Android, with iOS's hit-test semantics. Specifically, if there are two overlapping hit boxes, they are treated the exact same way as if you had two overlapping views -- the one that comes last in the view hierarchy receives the touch.

To get this same behavior on Android requires some extra work since the de facto way to adjust hit areas on Android ends up sending touch events to all views with overlapping hit boxes. It's confusing and inconsistent with how overlapping views function (where the hit box size == view size) so we're fixing that and working towards fixing this for RN Android so no one else has to. We're still a little bit away from sending a PR (need to do Android) but plan to when we have something working well.
