### ISSUE TITLE
0.37 module can't be resolved.

### ISSUE THREAD

**Issue by gviligvili** [facebook/react-native#11004]
### Description

While using ver 36, anything related to animations became so slow (The "slow animations" in simulator was off.)
so I thought to update everything, and now for some reason, I get this message:
![ErrorPic](https://cloud.githubusercontent.com/assets/8485006/20432178/a0cfc0d8-ada6-11e6-9d1d-18c41a2c2f5d.png)

which is weird because : 
![ExistsPic](https://cloud.githubusercontent.com/assets/8485006/20432147/7f132b4c-ada6-11e6-99c9-fc208711cdb2.png)

*** Followed - 
#4968 

tried : 
first this ( because I use yarn):
`rm -rf $TMPDIR/react-* && watchman watch-del-all && rm -rf ios/build/ModuleCache/* && rm -rf node_modules/ && yarn cache clean && yarn install`

and then I tried this
`rm -rf $TMPDIR/react-* && watchman watch-del-all && rm -rf ios/build/ModuleCache/* && rm -rf node_modules/ && npm cache clean && npm install`

Any help would be great, really clueless what's going on here.

### Additional Information

* React Native version: 0.37
* Platform: IOS
* Operating System: MacOS El Capitan

**Comment by klinkov** [comment]
same issue

**Comment by naineshg** [comment]
Having the same issue.

@nicklockwood @vjeux Can you look into this?

**Comment by naineshg** [comment]
@gviligvili I updated to latest RC React-Native release and it fixed the issue.

**Comment by avilyn** [comment]
Possibly related to React 15.4.0 being released a couple days ago?

**Comment by avilyn** [comment]
The new React version was definitely what was causing this for me. Some package dependencies were getting confused. Locking everything down to React 15.3.2 resolved this problem for me:

    "react": "15.3.2",
    "react-addons-shallow-compare": "15.3.2",
    "react-addons-test-utils": "15.3.2",
    "react-dom": "15.3.2",

**Comment by andrewnoh** [comment]
Wow, thanks a ton @avilyn . Spent way too many hours on this. 

I was upgrading from 15.3.1 and didn't know I needed react-dom...

```
    "react": "15.3.2",
    "react-addons-update": "15.3.2",
    "react-dom": "15.3.2",
    "react-native": "0.37.0",
```

**Comment by gviligvili** [comment]
For me - @naineshg  answer solved my case.
@avilyn  Thank you , I also tried the same before posting, I can't put my finger why it didn't work for me.
Either way - I'm closing the case because it's fixed in 38 RC.
