### ISSUE TITLE
Click threw PNG image transparencies

### ISSUE THREAD

**Issue by julesmoretti** [facebook/react-native#11005]
Is there anyways to get an png overlaid over other elements and have the bellow elements be clickable/draggable?

Basically how to interact through a png transparency?

Thank you.

**Comment by julesmoretti** [comment]
Anyone?

**Comment by ide** [comment]
You can allow clicks to go through the whole Image component with the pointerEvents prop, but there's no out-of-the box way to scan which pixels are transparent and allow touches through specific parts.
