### ISSUE TITLE
Navigator FloatFromLeft Scene Config 

### ISSUE THREAD

**Issue by hoodsy** [facebook/react-native#1100]
would it be possible to have a FloatFromLeft animation?

would b nice for the UX =]

**Comment by ide** [comment]
I believe you could write this without needing to make changes to the core project by writing a scene config that mirrors FloatFromRight and providing it to the Navigator.

**Comment by ericvicenti** [comment]
Yep, you can write custom scene configs for Navigator in your app. If you think others would be interested in `FloatFromLeft`, you could send a pull request to the default configs file:

https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/Navigator/NavigatorSceneConfigs.js

**Comment by hoodsy** [comment]
ok. thanks
