### ISSUE TITLE
NetInfo addEventListener is not working on Android 

### ISSUE THREAD

**Issue by JuSeonghyeok** [facebook/react-native#11012]
### Description

[My team is working on react-native with redux-saga project.  We tried to register NetInfo.addEventListener at redux-saga code. That means, NetInfo.addEventListener is not called from componentDidMount function and it worked properly on iOS.  However, on Android, this doesn't work as we expected.  On android, it seems like NetInfo event listener only works when we registered it on App.js componentDidMount function. ]

### Additional Information

* React Native version: [0.33.0]
* Platform: [Android]
* Operating System: [MacOS]

**Comment by mkonicek** [comment]
Can you provide a minimal amount of code to reproduce this on [rnplay.org](https://rnplay.org/)? This is necessary for people to be able to see and debug the issue being reported.

Closing this issue as it is not actionable. Please open a new one with an rnplay link (preferred), or link to a GitHub repo with clear instructions how to repro.
