### ISSUE TITLE
Webview not showing loading indicator when calling reload()

### ISSUE THREAD

**Issue by cfs5403** [facebook/react-native#11013]
### Description

Webview not showing loading indicator when calling reload() like below code, this only happen in android, IOS not problem.

this.refs[WEBVIEW_REF].reload();

### Reproduction

`render() {
    return (

      <View style={ { flex: 1 } }>
          <WebView
              ref={ WEBVIEW_REF }
              style={ { flex: 1, marginTop: 50 } }
              source={ { uri: this.props.url } }
              scalesPageToFit={ this.props.scalesPageToFit }
              startInLoadingState={ this.props.startInLoadingState } />
      </View>
      );
  };`

### Solution
Please fix the so when we call reload, it show the loading indicator

### Additional Information

* React Native version: 0.37.0
* Platform: android
* Operating System: MacOS

**Comment by mkonicek** [comment]
Does the Android WebView ever show a loading indicator? It might not be implemented. Please send a PR to fix this.

**Comment by cfs5403** [comment]
it showing for the first load but did not show when call with reload method

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.

**Comment by DracoBlue** [comment]
@hramos this is still an issue on android. We will try to fix this and send you a PR.

**Comment by DracoBlue** [comment]
Should be fixed with #15538
