### ISSUE TITLE
TouchableHighlight's onPress event is fired without touching the screen.

### ISSUE THREAD

**Issue by panzer-planet** [facebook/react-native#11015]
### Description
I have a modal which I present to the user. Upon clicking yes, the modal's text is changed and it displays the ActivityIndicator. 
`submit() {

    var summary = "Are you sure you want to submit attendance with "+this.getSummaryString()+ " children present?"

    this.props.dispatch(
      appActions.setModal({
      modalVisible: true,
      modalText:  summary ,
      modalMode: ModalMode.CONFIRM,
      modalOnPositive: () => {
        this.props.dispatch(appActions.setModal({
          modalVisible: true,
          modalText: "Getting location",
          modalMode: ModalMode.WAITING
        }))
        navigator.geolocation.getCurrentPosition((location) => {
          this.actions.submit(
            location,
            this.centreId,
            this.classId,
            this.attendanceData,
            this.token,
            this.props.navigator
          )
          this.props.dispatch(appActions.setModal({
            modalVisible: true, 
            modalText: "Uploading Data",
            modalMode: ModalMode.WAITING
          }))
        }, (error) => {
          this.props.dispatch(appActions.setModal({
            modalText: "Could not get location. Please ensure location is enabled on your phone.",
            modalMode: ModalMode.OKAY,
            modalVisible: true
          }))
        },{
          timeout: 5000
        })
      }
    }))

  }`

When the background network activity completes, the modal's state is set to visible = true throughout. Logging Redux revealed that the modal's this.close is being fired without the button being touched. In my WaitModal component
  
`close() {
    this.props.dispatch(appActions.setModal({modalVisible: false}))
  }

  onPositive(){
    if(this.props.onPositive)
      this.props.onPositive()
    this.close()
  }
                                                                                                            
  onNegative(){
    if(this.props.onNegative)
      this.props.onNegative()
    this.close()
  }
...
<TouchableHighlight style={{ borderRadius: 5 }}
              underlayColor={'white'}
              onPress={ () => this.onPositive() }
            >
              <View style={{
                padding: 15,
                borderRadius: 5,
                backgroundColor: Colours.primary ,
                alignItems: 'center',
                justifyContent: 'center',
                width: 200
              }}>
                <Text style={{color: 'white', fontWeight: 'bold', fontSize: FontSizes.p}}>Okay</Text>
              </View>
            </TouchableHighlight>`
### Solution

Perhaps there is a problem with my javascript, but I see no reason for the onPress event  to fire without me touching the screen so, onPositive()/onNegative() and close() should never run.

### Additional Information

* React Native version: 0.37.0
* Platform: Android
* Operating System: Mac OS X 10.12.1

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
