### ISSUE TITLE
Rotten Tomatoes API Key doesn't work

### ISSUE THREAD

**Issue by MarkPare** [facebook/react-native#11028]
Pretty sure that the API key and URL that come with this example Movies project don't work.  Debugging a Json parse error shows that response returned is html and says "Developer inactive".  

This seems to be confirmed when looking at the Movies tutorial at react-native site, where URL has been replaced:
https://facebook.github.io/react-native/releases/0.27/docs/sample-application-movies.html

Prob worth updating to save future unsuspecting developers the hassle.

**Comment by ericvicenti** [comment]
Related: https://github.com/facebook/react-native/pull/7025

Nobody is currently working on the movies app. Can you fix this for us?

**Comment by saigrandhi** [comment]
This would require creating a tutorial similar to the previous movies application, right? I would like to work on this. 

Do I still use a samplemovies.json file? It was used in the 0.27 version of documentation

**Comment by ravindraprasad75** [comment]
I am encountering the issue in accessing the API. Looks like Rotten Tomatoes changed their policies.

**Comment by saigrandhi** [comment]
@ericvicenti Can we use TheMovieDB.org api instead of RottenTomatoes? I can work on it.

**Comment by ericvicenti** [comment]
The movies sample has been removed from the core RN repo. Feel free to publish standalone example apps, and we can curate a list of them for the website.

**Comment by nomad609** [comment]
Hey Guys,
I am also facing same error: "Developer Inactive". My api key was generated but still it is showing status "Waiting". 

Can you please confirm how much time it will take to get activate?

Thanks,
Anil

**Comment by blaisesmith2018** [comment]
Hi Anil-Barnwal, Did you ever find out how to activate the API. I also have a key and secret but keep receiving the "Developer Inactive" message and my status still says "waiting". Did you have any luck with this problem? Thank you for any info you can share. Blaise

**Comment by Anil-Barnwal** [comment]
Sorry for late reply. It was not updated.

**Comment by DusuWen** [comment]
i have the same issue,waiting for two weeks ,no change
