### ISSUE TITLE
React Native has several bugs on linux android...

### ISSUE THREAD

**Issue by pdarde** [facebook/react-native#11024]
### Description

I'm a react developer and some days ago I've started with react-native framework.  Following the getting start page, I faced a lot of bugs. 

After that, I found some errors. Searching for a solution on the web, I landed on a [stackoverflow page](http://stackoverflow.com/questions/38870710/error-could-not-get-batchedbridge-make-sure-your-bundle-is-packaged-properly) that instructs several steps in order to solve these issues. It's required to create an "assets" folder within the path "MyProject/android/app/src/main/" and run bash commands.

### Reproduction

The bugs appear when I run "react-native run-android" after all environment set up.

The first one was related to the platform API, I had to change manually to android API 23.0.1.

The second one is a common bug that says "Could not get BatchedBridge".

### Solution

These are the steps for a possible solution:

1. Change the file "MyProject/android/app/build.gradle". Add the correct Android API supported version.
Under "dependencies" section I had to add the line 
"compile "com.android.support:appcompat-v7:23.0.1"

2. Create an "assets" folder under the "MyProject/android/app/src/main/"

3. On terminal run the following commands..
react-native start > /dev/null 2>&1 &
curl "http://localhost:8081/index.android.bundle?platform=android" -o "android/app/src/main/assets/index.android.bundle"
(cd android/ && ./gradlew assembleDebug)

sometimes it's required run npm start.

Actually, I loved the framework, but the documentation lacks that bug solutions and becomes the development work pain.

### Additional Information

* react-native-cli: 1.2.0
* react-native: 0.37.0
* Platform: Android API 23.0.1
* Operating System: Linux Elementary 8 (Ubuntu LTS based)

**Comment by vonovak** [comment]
Npm start is always required in development, that's why you're getting the 'could not get...' error

**Comment by sanjibnarzary** [comment]
For 1. You need to install Android SDK Platform tools. By default if you hit `react-native init AwesomeProject` it will configured with the platform target Android API 23.0.1. You need to install it using Android SDK Manager.

For 3: Make sure you have the running android emulator before hitting `react-native run-android`. I faced the same problem while trying to test react-native for the first time.

**Comment by pdarde** [comment]
Thanks @sanjibnarzary , for 3, I had my emulator running before, but did has no effect.

**Comment by pdarde** [comment]
Another important consideration about this issue, is: for linux user, watchman is not optional, is REQUIRED. It is very common the fs.inotify.max_user_watches has a small value, that impacts on the development process.

When I run "react-native start", and I get an Error such as...   ERROR  A non-recoverable condition has triggered.  Watchman needs your help!
The triggering condition was at timestamp=1480258961: inotify-add-watch

I need to increase my watches.. so, I should do the described on the page https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers

 and, reset my watchman as described on the page 

https://facebook.github.io/watchman/docs/troubleshooting.html#i-39-ve-changed-my-limits-how-can-i-clear-the-error

**Comment by mkonicek** [comment]
Interesting, thanks for reporting! This is useful as we all use Mac OS. It's strange you have to do 1. and 2., the Android build tool (Gradle) should work the same way on any OS.

@hramos do you know wrote and tested the Linux docs?

**Comment by hramos** [comment]
The Linux docs could use another round of tests to make sure they're current. We've mainly kept the content as-is in the recent rewrites. @pdarde would you be willing to open a PR against the doc in master with any suggested edits? https://github.com/facebook/react-native/blob/master/docs/GettingStarted.md

**Comment by pdarde** [comment]
Hey guys, after running some test, I found out that install watchman and increase my inotify watchers solve all problems. Also, it is not more required to do steps 1, 2, and 3. I opened a PR to suggest a little edition in the docs. Feel free do edit or reject it. [https://github.com/facebook/react-native/pull/11208](https://github.com/facebook/react-native/pull/11208).

Thanks for the help!
