### ISSUE TITLE
Rerendering view doesn't work properly (Image not displayed, etc.) caused by zIndex

### ISSUE THREAD

**Issue by jbuchermn** [facebook/react-native#11022]
Hello,

I've just recently started using React-Native and I am really happy with this amazing framework.

So I've been moving a React project to React-Native (Android, for now). This project uses Relay for the data layer, and since everything has been workingnicely on React, I'm quite confident concerning this layer. But I'm seeing weird behavior concerning React-Native after an update has been commited.

The Relay container does set the props of my Component, render() get's called, but than everything gets messy. I have an image positioned in the centered of the view, which doesn't get rendered after the update. Also I have a button which switches color and caption after the update. If the color's initially white, it gets blue, than after the next update white again, and so on. If it's initially blue, it stays blue for some reason. Nonetheless, the caption gets rendered correctly.

The whole thing is a bit too much to copy here, I'll just give the main structure

`<RelayContainer>
    <View>
        <View>
            <Image [doesn't get rendered after update] />
            [....]
        </View>
        <View>
            <TouchableNativeFeedback>
                <View [render with incorrect color]>[...]</View>
            </TouchableNativeFeedback>
        </View>
    </View>
</RelayContainer>`

Any idea what's happening here?

**Comment by jbuchermn** [comment]
UPDATE: I just realized, that both problems cease to exist, if I remove "zIndex: 2" from the image's style

Is this intended behavior?

**Comment by liamfd** [comment]
@jbuchermn is it possible this is the same issue reported [here](https://github.com/facebook/react-native/issues/8968)? Someone is working on a PR for the issue in that thread, so if it's the same one, hopefully this will be fixed soon.

**Comment by jbuchermn** [comment]
Yes it is, thank you!
