### ISSUE TITLE
Can't init a new react native project with "react-native init" command line

### ISSUE THREAD

**Issue by OUZICHENG** [facebook/react-native#11025]
### Description
system: mac os sierra,
node: V7.1.0,
react-native-cli: 1.2.0
yarn:0.17.6

I tried to run "react-native init reactNtivePro" to init my project. but it can't finish for a long time. about half an hour later, I canceled it and retried many times.

### Solution

1. I tried to reinstall my react-native-cli, and run the command line again. it mention me to install yarn will be faster.

2.I tried to run "brew install yarn", if didn't work, and I ran "npm install -g yarn" instead, and i install yarn 0.17.6  successfully.

3.tried "react-native init" again, mentioned using yarn installing react native, but can't finish just like before

4.I download the latest node and reinstall my node, reinstall my yarn and everything else, even my system, but nothing changed.

5.no matter how long it ran, only node_modules,package.json,yarn.lock in the project folder.

### Additional Information

* React Native version: [0.37] react-native-cli 1.2
* Platform: [FILL THIS OUT: iOS, Android, or both?]
* Operating System: [MacOS]

**Comment by nihgwu** [comment]
Have you try to use a VPN or Taobao's registry?
run `npm config set registry https://registry.npmjs.com/` before `react-native init`

**Comment by OUZICHENG** [comment]
I was using Tbao's registry, and I tried VPN at the same time. I will take you advice later. I cleaned everything in my computer and try to install mac os x. it will be a long time.

how do you know taobao's registry, are you chinese just like me?  if you can speek chinese, it will be great. thanks for your help.

**Comment by nihgwu** [comment]
Sorry I provided the wrong registry, should be `npm config set registry https://registry.npm.taobao.org/`

**Comment by OUZICHENG** [comment]
I got it, thanks any way.

**Comment by jaxondu** [comment]
I just wasted some time on "react-native init" stuck problem . Turn out it is "watchman" and is a common problem. Using the Terminal app inspector, check if the last process is "/usr/local/Cellar/watchman/4.7.0/libexec/bin/watchman version".  If it is, kill "react-native init" process and run the following:

rm -rf /usr/local/var/run/watchman/ && brew uninstall watchman && brew install watchman

**Comment by OUZICHENG** [comment]
@jaxondu  got it. tks

**Comment by ManalAbuelazaem** [comment]
It was solved for me by starting the process of installation on this link all over
[https://facebook.github.io/react-native/docs/getting-started.html](url)
