### ISSUE TITLE
`react-native install` is not using yarn

### ISSUE THREAD

**Issue by brunolemos** [facebook/react-native#11038]
React Native now uses yarn by default, but `react-native install` still doesn't. 

So if we want to install and link a package, we currently have to run two commands: 
`yarn add` and `react-native link`.

React Native version: 0.37.0

**Comment by neiker** [comment]
It's fixed in 0.38:
https://github.com/facebook/react-native/commit/94711bfb06e46a7742dbddf5b1b6c48ecf345495
