### ISSUE TITLE
Navigator not using passProps

### ISSUE THREAD

**Issue by kujohn** [facebook/react-native#1103]
The `Navigator` doesn't seem to pass the props to the component:
```
this.props.navigator.push({                    
    component: ActivityDetail,                 
    navigationBar: <ActivityDetailNavBar />,   
    passProps: {                               
        event: event                           
    }                                          
});                                            
```

I am using `Navigator` btw, but `NavigatorIOS` does work. Am I missing something?

**Comment by christopherdro** [comment]
Navigator works a bit differently. If I'm not mistaken the following should work.
```
navigationBar: <ActivityDetailNavBar event={event}/>
````
You should then be able to access that in your screen by using ```event: this.props.event```

Also, navigator uses renderScene to load the correct component rather than passing in ```component``` parameter like you have above.

Take a look at the docs and UIExplorer example to get a better understanding of how it works.

Hope this helps.

**Comment by ericvicenti** [comment]
@christopherdro is right, the API is different. Sorry about that. The renderScene technique allows us to squeeze a bit of additional performance by not loading a component until we need it.

The `renderScene={(route) => rendered}` and `navigationBar={<MyNavBar />}` APIs in `<Navigator>` are here to stay. If somebody wants to update the API of `<NavigatorIOS>` to be more consistent, that would be greatly appreciated!

**Comment by achang28** [comment]
I am having what I believe is the same issue as @kujohn, and given all the responses above I am not seeing any other way to pass props from one component to the destination component when using ".push( )" on the navigator object.

Using @kujohn's snippet above, while using React Native 0.5.0, I can successfully reference "this.props.route.passProps" in the ActivityDetail component.  In React Native 0.7.1, this is not the case -- "passProps" is no longer available via "this.props.route.passProps".  I am using the navigator object that is provided by the Navigator component (i.e. via ```renderScene={(route) => rendered}```)

**Comment by alvaromb** [comment]
@kujohn you can do this in your ``renderScene`` method:

```javascript
renderScene (route, navigator) {
  const Component = route.component
  return (
    <View style={{flex: 1}}>
      <Component navigator={navigator} route={route} />
    </View>
  )
}
```

And then while pushing:

```javascript
navigator.push({
  component: ComponentName,
  title: 'Title',
  passProps: {}
})
```

In your ``ComponentName``' ``route`` prop you'll have a ``passProps`` object. However, I would like to confirm that this is a good strategy because I'm using this all around my apps.

**Comment by ericvicenti** [comment]
@alvaromb, yep. You've described a great way to mimic the same API, although it looks like you forgot to actually use the `passProps`:

```
<Component navigator={navigator} route={route} {...route.passProps} />
```

**Comment by alvaromb** [comment]
You're absolutely right Eric, I forgot to pass the props to the component. Thanks for catching the bug in the comment!

Enviado desde mi iPhone
