### ISSUE TITLE
Animated view with TouchableOpacity Wrapping ListView crashes after animation

### ISSUE THREAD

**Issue by manggit** [facebook/react-native#11032]
### Description

**View structure**
```
<Animated.View>
  <TouchableOpacity>
    <ListView/>
  </TouchableOpacity>
</Animated.View>
```

When TouchableOpacity is pressed, I animated the parent view, the animation completes and then the app crashes without any errors. 

When linked to the remote chrome debugger, everything works fine, although rather slowly. This leads me to think there may be a timing issue, although that doesn't explain the solution I describe below.

This issues also occurs when I have a view structure like this
**View structure**
```
<Animated.View>
  <TouchableOpacity>
    <View>
      <View/>
      <ListView/>
    </View>
  </TouchableOpacity>
</Animated.View>
```

Pretty much it seems that a listView cannot be directly wrapped by a TouchableOpacity.

### Solution
Currently the app does not crash if I wrap the ListView in a normal view like so

**View structure**
```
<Animated.View>
  <TouchableOpacity>
    <View>
      <ListView/>
    </View>
  </TouchableOpacity>
</Animated.View>
```

Either update documentation or address the underlying issue as to why a crash occurs when a TouchableOpacity directly wraps a list view.

### Additional Information

* React Native version: 0.37
* Platform: iOS 10.0.1 iPhone 6 simulator
* Operating System: MacOS

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.

**Comment by garcia1994** [comment]
Tengo el mismo problema, si alguien sabe como resolver se lo agradeceria
