### ISSUE TITLE
Execution failed for task ':app:bundleReleaseJsAndAssets'

### ISSUE THREAD

**Issue by mvnnn** [facebook/react-native#11034]
After update my app to RN0.37, i get following error while Generating android APK
```
react:15.3.2
react-native:0.37.0
```
![error](https://cloud.githubusercontent.com/assets/12225578/20463056/06933584-af51-11e6-9fcf-cfff6896d85d.png)

**Comment by lacker** [comment]
It looks like you have some invalid code in your index.android.js - like you are writing `"foo" ="foo"` or somehow assigning to a string literal.

**Comment by lacker** [comment]
Could you provide a repro of this with a rnplay.org link?

**Comment by mvnnn** [comment]
This error happen because i set development mode in ```index.android.js```.

**Comment by kirakik** [comment]
@mvnnn Could you elaborate, please? What do you mean by setting the development mode? I'm getting the same issue.

**Comment by SirPhemmiey** [comment]
Any fix for this?

**Comment by GreenRidingHood** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command 'node'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 47s
12 actionable tasks: 7 executed, 5 up-to-date


Any fix, can we open that issue again?

**Comment by SirPhemmiey** [comment]
Try to delete `android/app/build` and `android/build` folders and run `react-native run-android` again

**Comment by GreenRidingHood** [comment]
@SirPhemmiey yep i did, and I get another error after I run "cd android && ./gradlew clean && ./gradlew assembleRelease"

* What went wrong:
Execution failed for task ':app:processReleaseResources'.
> Failed to execute aapt

 ... 2 days.. I am just trying to get "app-release.apk".  
I go over "https://facebook.github.io/react-native/docs/signed-apk-android.html" create keystore, and stuck at release step .. I don't know, so frustrating.. I go over stackoverflow, github issues but.. nope..
 
my app works on android studio emulator, working with "npm run android" with genymotion emulator,

**Comment by dengue8830** [comment]
i don't know if is the exact same problem, but i solved mine with [this](https://github.com/facebook/react-native/issues/18969)

> downgrading to "babel-preset-react-native": "4.0.0" in the package.json and running npm install
