### ISSUE TITLE
[Android] borderStyle does not work with specific borderWidth (borderBottomWidth, etc).

### ISSUE THREAD

**Issue by awitherow** [facebook/react-native#11042]
borderStyle does not work with specific borderWidth.

```
borderBottomWidth: 1,
borderBottomColor: '#979797',
borderStyle: 'dotted',
```

shows no dotted border.

**Comment by linmic** [comment]
I assume this is a duplicate of #8236.

**Comment by armres** [comment]
If set
`{
  borderWidth: 1,
  borderTopWidth: 0,
  borderLeftWidth: 0,
  borderRightWidth: 0,
  borderBottomColor: '#979797',
  borderStyle: 'dotted'
}`
It's work

**Comment by brentvatne** [comment]
:+1: repro'd this

**Comment by mkonicek** [comment]
Thanks for reporting. Any chance you could send a PR with a fix? :)

@brentvatne I believe this was owned by someone who doesn't work on RN anymore (possible to find out using blame info).

**Comment by brentvatne** [comment]
cc @ahmedre as you're likely the most knowledgable person about this

**Comment by ahmedre** [comment]
i am not really sure, but the border code in Android is [here](https://github.com/facebook/react-native/blob/1604f1088959428fab8cd4d3c451585d914464a9/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewBackgroundDrawable.java).

it looks like we have two cases - `drawRectangularBackgroundWithBorders` and `drawRoundedBackgroundWithBorders`. it seems that in this case, we go to the latter (because the style is not solid), which doesn't seem to support non-uniform borders. the easiest fix here would be to replace the if on line 105 with `if (!roundedBorders)`. this should work because styles can be applied on `Path`s, and `drawRectangularBackgroundWithBorders` also generates a `Path` to draw the borders now.

if no one gets to this before Tuesday, i can give it a shot.

**Comment by Lxxyx** [comment]
same problem.

**Comment by sospedra** [comment]
+1 why is this closed?

**Comment by RobTS** [comment]
+1 

Border turned solid after upgrading from RN 41.2 to 43.3. Styling:

```
  imagePlaceholder: {
    borderStyle: "dashed",
    margin: 10,
    padding: 30,
    alignItems: "center",
    borderColor: Colors.gray,
    borderWidth: 3
  },
```

**Comment by xiemeilong** [comment]
+1

**Comment by cgx9** [comment]
same problem. +1

**Comment by xsgkaka** [comment]
i got the same problem

**Comment by adrianlemess** [comment]
Same problem here, when I'm using borderTopRightRadius and to make a semi circle. When I'm put borderTopWidth, borderRightWidth and borderLeftWidth with value and borderBottomWidth 0, the border disappear. And if I'm just put borderWidth: value and borderBottomWIdth: 0 the border bottom showing again:
![image](https://user-images.githubusercontent.com/12432777/27046603-753a787e-4f7b-11e7-84d7-5b6d780ff347.png)
 and if I remove the borderTopRightRadius and borderTopLeftRadius: 
![image](https://user-images.githubusercontent.com/12432777/27046634-9508ac20-4f7b-11e7-9607-0926b317f887.png)

**Comment by zoharlevin** [comment]
still happening as you can see here
https://github.com/facebook/react-native/issues/13464

**Comment by MrSpeedR** [comment]
@adrianlemess Did you solve your problem? I have got same issue creating semi circle without bottom boarder.

**Comment by gregblass** [comment]
Anyone know if this issue still open or if it's been resolved? Looks like it may have originated over a year ago. I'm still on 0.44, so just wondering if this was addressed in any of the later releases?

I think I can workaround it by just adding a `<View>` element to act as a faux-border, but would rather avoid that if an upgrade to the latest RN will fix it.

**Comment by AlanChauchet** [comment]
@gregblass Still opened.
I have the same issue when using some style like
```
{ 
    backgroundColor: APP_COLOR,
    borderTopWidth: 4,
    borderRadius: 5,
}
```
As long as borderRadius is set, no top border at all

**Comment by wcandillon** [comment]
I can confirm that this issue is still present in version `0.50.4`.

**Comment by kerwin1** [comment]
I have the same problem(v0.47.2 on android)

**Comment by porluz** [comment]
+1  "react": "16.0.0", "react-native": "0.50.3".

**Comment by sadi304** [comment]
This issue needs to be addressed -__-. Been there for almost one and a half year

**Comment by sound2gd** [comment]
+1 "react": "16.0.0", "react-native": "0.51".

**Comment by LouisJS** [comment]
+1 "react": "16.2.0",
    "react-native": "0.52.0",

**Comment by orhanberamus** [comment]
+1
