### ISSUE TITLE
NetInfo.isConnected, it's "change" event should not trigger on componentWillMount

### ISSUE THREAD

**Issue by jinlong** [facebook/react-native#11041]
when component will mount,  two "console.log" are output. but i don't change the network

code as follow:

```js
componentWillMount() {
    NetInfo.isConnected.fetch().done(isConnected => {
        console.log('First, is ' + (isConnected ? 'online' : 'offline'));

    });
    
    NetInfo.isConnected.addEventListener('change', (isConnected) => {
        console.log('Then, is ' + (isConnected ? 'online' : 'offline'));
        
    });
    
}
```

run result:

```
11-21 18:30:28.285 14419-23251/com.android.browser I/ReactNativeJS: Then, is online
11-21 18:30:28.335 14419-23251/com.android.browser I/ReactNativeJS: First, is online
```

**Comment by mkonicek** [comment]
Can you provide a minimal amount of code to reproduce this on [rnplay.org](https://rnplay.org/)? This is necessary for people to be able to see and debug the issue being reported.

Closing this issue as it is not actionable. Please open a new one with an rnplay link (preferred), or link to a GitHub repo with clear instructions how to repro.
