### ISSUE TITLE
Android Emulator - app was working and now white screen

### ISSUE THREAD

**Issue by gotters** [facebook/react-native#11044]
React-native was working fine on my android emulator.
At some point in my recent development I switched to Remote debugging and the app loads up with a white screen! From that point I could no longer even load up the dev menu to turn off remote debugging.
I have no error messages in the console or on-screen.

If I run other apps they are working fine.

* React Native version: 
* Platform: Android
* Operating System: Windows

**Comment by sanjibnarzary** [comment]
You got white screen because your native app could not fetch the file from development server. Make sure JS packager is running. If it is not running by default then start by typing `npm start`.

**Comment by gotters** [comment]
Its definitely running. Its been working the whole time and I tried restarting it with the same results many times. 
Sometimes I first get a message that there was an error opening the app and then when i click to re-open it just white screens. But then subsequent build and deploys just go straight to white screen.
Is there anywhere I can see additional logs?

**Comment by maluramichael** [comment]
Do you set a breakpoint? I often find my self searching for a bug but then it is just a moved breakpoint at the beginning of the app after i changed bit of code.

**Comment by gotters** [comment]
No. No breakpoints

**Comment by tuckerconnelly** [comment]
Do you have a View with `position: 'absolute'` within a View with `position: 'relative'`?

**Comment by gotters** [comment]
No i dont.
I think it has something to do with react-native-navigation.
I just created a clean app and it ran (although I do see errors in the adb logs - lots of these)

> 11-22 11:56:30.949  3936  3959 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ModalHostShadowNode
> 11-22 11:56:30.949  3936  3959 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ReactProgressBarViewManager
> 11-22 11:56:30.951  3936  3959 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ProgressBarShadowNode
> 11-22 11:56:30.952  3936  3959 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactRawTextManager
> 11-22 11:56:30.953  3936  3959 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextShadowNode
> 11-22 11:56:30.955  3936  3959 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactScrollViewManager
> 11-22 11:56:30.956  3936  3959 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager
> 11-22 11:56:30.957  3936  3959 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager$Reac


When I then installed react-native-navigation I get the white screen. 

But still no idea how to fix it.

**Comment by mkonicek** [comment]
Looks like this is related to react-native-navigation rather than React Native?

Are you developing for Android or iOS?

**Comment by gotters** [comment]
Turns out the issue was an Android SDK that needed an update that for some reason was just breaking react-native apps that were using react-native-navigation

**Comment by arfianadam** [comment]
@gotters can you please elaborate? I am having the same issue

**Comment by JavaJamie** [comment]
I just had this same issue. I started the emulator via the integrated terminal in Visual Studio and the white screen appeared. As soon as I did run-android in a separate terminal everything displayed again.

**Comment by rcorrie** [comment]
@gotters thanks for the hint, but some more detail would have been much appreciated for other who have the same issue.
