### ISSUE TITLE
Failure to find callback when communicating from native code to Javascript

### ISSUE THREAD

**Issue by bhatti** [facebook/react-native#1104]
I am writing a native module which allows Javascript client to register for events with a callback and then receive events. I used examples from http://facebook.github.io/react-native/docs/nativemodulesios.html, e.g.

-(void)subscribe:(NSString *)event withCallback:(RCTResponseSenderBlock) callback;

and used RCT macros to expose those methods.

I then connected to the module from Javascript, e.g.
var SubscriptionManager = require('NativeModules').SubscriptionManager;
 SubscriptionManager.subscribe("type", function(error, events) {...});

When I run the app, I receive events for a few seconds and then the native code fails to send event with warning:

2015-05-01 18:59:12.904 [info][tid:com.facebook.React.JavaScript] "Warning: Cannot find callback with CBID 73. Native module may have invoked both the success callback and the error callback."

and the app crashes with error 
![crash](https://cloud.githubusercontent.com/assets/58455/7439557/47013ed6-f035-11e4-8189-14b28682f9c0.png)

Can someone suggest fix for this issue?

Thanks.

**Comment by ide** [comment]
Are you invoking the Obj-C block more than once? That would cause this error.

**Comment by cxfeng1** [comment]
@ide  if I want to invoke the response block more than once, how can I do?

**Comment by ide** [comment]
You can't and will have to fire events though DeviceEventEmitter instead (grep the native module docs for examples).

**Comment by bhatti** [comment]
The native code was calling callback block to pass events to Javascript. I can use DeviceEventEmitter but callback would have been easier as I can encapsulate logic within the block. Thanks.

**Comment by cxfeng1** [comment]
Agree with @bhatti ,  using callback in JS may be more intuitive. @vjeux @nicklockwood

**Comment by ide** [comment]
This might be possible if the callbacks are NSObjects instead of blocks, and in -[dealloc] they tell JS to free the corresponding JS closure. My sense is this feature is desirable but the implementation might feel a bit sketchy. Also building it on Android would require a different bag of tricks but might be possible with WeakReferences or finalize().

**Comment by bhatti** [comment]
I am switching to DeviceEventEmitter using
var DeviceEventEmitter = require('RCTDeviceEventEmitter');
and then calling addListener per your partial examples (I didn't see how you get hold of DeviceEventEmitter), however I am seeing following error when I launch the app:

 message: Requiring unknown module "RCTNativeAppEventEmitter". If you are sure the module is there, try restarting the packager."

I noticed https://github.com/facebook/react-native/issues/394 refers to this issue. Can I still use DeviceEventEmitter? I am using 0.4.0 version of the react-native library.
Thanks.

**Comment by bhatti** [comment]
FYI, I got it working when using sendDeviceEventWithName to publish events instead of sendAppEventWithName, which was suggested by examples (https://facebook.github.io/react-native/docs/nativemodulesios.html#content).
