### ISSUE TITLE
[TextInput] Vertical padding on a <TextInput> not correctly computed

### ISSUE THREAD

**Issue by ide** [facebook/react-native#1105]
A text field's height appears to be calculated as max(intrinsic height, vertical padding) instead of intrinsic height + vertical padding.

Repro: 
```
<View style={{flexDirection: 'row'}}>
  <TextInput style={{flex: 1, paddingBottom: 50, backgroundColor: '#ddd'}} value="hello" />
</View>
```
The text field is 50pt tall and the text is half-clipped at the top.

**Comment by brentvatne** [comment]
Is this collapsable into #1287 @ide?

**Comment by ide** [comment]
This is a different problem with the layout engine.

**Comment by brentvatne** [comment]
Ah okay, just wanted to be sure

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/textinput-vertical-padding-on-a-textinput-not-correctly-computed
