### ISSUE TITLE
[docs] Modal Doc Returning 404

### ISSUE THREAD

**Issue by joncursi** [facebook/react-native#11059]
The current URL used on the documentation website for the Modal component returns a 404:

https://facebook.github.io/react-native/docs/modal.html

<img width="851" alt="screen shot 2016-11-22 at 3 37 55 am" src="https://cloud.githubusercontent.com/assets/4974609/20516584/1be245c8-b065-11e6-9070-cbcfbb0537a3.png">

**Comment by odemolliens** [comment]
Fixed

**Comment by joncursi** [comment]
:+1:

**Comment by nicolas-t** [comment]
the main url https://facebook.github.io/react-native/ returns 404 
it's the first result on google for "react native"

I use https://facebook.github.io/react-native/docs instead

**Comment by fendy3002** [comment]
https://facebook.github.io/react-native/docs is also 404 from here.
As well as https://facebook.github.io/react-native/
