### ISSUE TITLE
Android Memory Allocations

### ISSUE THREAD

**Issue by jpshelley** [facebook/react-native#11053]
### Description

* What I did:
   * Created a new React Native project via the CLI
   * Ran the app on a 5x+23 API Emulator via `react-native run-android`
   * Opened the Android Monitors tab
* What I expected:
   * I expected the memory allocations to rise at app startup and then plateau.
* What actually happens:
   * Memory is slowly getting allocated even while the app is just sitting there without any user input.
   * When the memory hits the allocated threshold a garbage collection occurs.
   * Its good the memory can actually get garbage collected meaning there isn't a memory leak.
   * However why is memory always getting allocated??

### Reproduction

I have a screen recording uploaded here:
https://youtu.be/F3875gv6tAw

### Solution

* Figure out what is being allocated so often and stop it.
* Is this related to debug builds only or also release builds?

### Additional Information

* React Native version: 0.37.0
* Platform: Android (maybe others, untested)
* Operating System: MacOS
* Android OS: 23

**Comment by lacker** [comment]
Is the emulator actually a good representative of regular memory usage? Can you reproduce this on a real device as well? I think to be sure this is a problem we would want to check release build + real device.

**Comment by jpshelley** [comment]
I was able to reproduce it actually on a real device as well. Samsung Galaxy S4 (somewhat lower end testing), and a Nexus 6p (somewhat higher end testing).

From my understanding of memory allocation tracking, device shouldn't matter of the actual trend. Available memory might change but the following should raise a flag:
* Your app is static, but you see memory being allocated in the monitor.
* You see spikes of memory allocations in the monitor, but you don’t think there’s any app logic to cause this behavior.
* Excessive garbage collection events slow down the app, so minimize these.
* If the app runs out of memory, it would causes it to crash.

I think the first bullet point "static app, memory being allocated" is not good.

The one thing I haven't checked yet is a release build and can try to do that once we have one available. However I thought the Android Studio Monitors required a debuggable app to hook into.

**Comment by pinkelf** [comment]
I've met the same problem, too. The memory is slowly increased.

For a helloworld demo, I got something like this:

adb shell dumpsys meminfo -a com.rnhelloworld

                   Pss      Pss   Shared  Private   Shared  Private  Swapped     Heap     Heap     Heap
                 Total    Clean    Dirty    Dirty    Clean    Clean    Dirty     Size    Alloc     Free
        TOTAL    53298    10256    16928    37468    27532    10292    12764    48375    35871    12503
        TOTAL    53350    10260    16928    37516    27532    10296    12764    48381    35900    12480
        TOTAL    53446    10260    16928    37612    27532    10296    12764    48383    35776    12606

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/android-memory-allocations

**Comment by amahrt** [comment]
This is still a thing,
I've created a new project using react-native-create-project with these dependencies:

`
    "react": "16.0.0-alpha.12",
    "react-native": "^0.47.2"
`

And it still allocates memory.

![image](https://user-images.githubusercontent.com/4093898/29776561-41891cea-8c09-11e7-95e1-f6c9b6384a9c.png)

**Comment by pewh** [comment]
+1 any progress on this?

**Comment by amahrt** [comment]
So this issue seems to be not relevant enough to be resolved? :( Too bad

**Comment by asilvestre87** [comment]
I have the same issue in react-native 0.51.0.

**Comment by ashokkumar88** [comment]
I have still getting same issue in react-native 0.51.0

**Comment by Tomatoo** [comment]
still have same problem in 0.55.2
