### ISSUE TITLE
LayoutAnimation delete with scaleXY not working

### ISSUE THREAD

**Issue by rcaferati** [facebook/react-native#11066]
### Description

When using LayoutAnimation, the delete animation is working correctly with opacity but not with scaleXY.

### Reproduction

https://rnplay.org/apps/md44OA reproduces with scaleXY deletion (bugged)
https://rnplay.org/apps/BOVnlw reproduces with opacity deletion (working)

### Solution

On the RCTUIManager.m file, for some reason the CATransform3DMakeScale(0, 0, 0) with 0/0.0 value is breaking the animation. A possible workaround could be to use small values on the CATransform3DMakeScale like 0.001.

### Additional Information

* React Native version: v0.37.0
* Platform: iOS
* Operating System: MaxOS

**Comment by janicduplessis** [comment]
Closing this since your RP landed
