### ISSUE TITLE
Documentation clarification with Image component

### ISSUE THREAD

**Issue by danawoodman** [facebook/react-native#1106]
A thing that really caught me up (and I'm assuming many others) is that in order to get images to work as described in the docs, you have to drag them into the `Images.xcassets` directory in Xcode. I was trying to copy them into the `iOS` folder out of ignorance. Maybe an explicit message about this and screenshot would help others in the future?

![](http://cl.ly/aqID/Screen%20Shot%202015-05-01%20at%2011.37.49%20PM.png)

**Comment by brentvatne** [comment]
@danawoodman - you can add this if you like! PR is welcome

**Comment by brentvatne** [comment]
I updated the documentation here finally! Hurray
