### ISSUE TITLE
Is native "dialog list" implemented?

### ISSUE THREAD

**Issue by JonasJonny** [facebook/react-native#1107]
Hello. 
Firstly thank you for great work. React native is really fantastic!

My question is: "Is dialog list already implemented as part of react native?"
I don't know if I call it right and I can't find it. 
The screenshot is implementation from Facebook ads. 

Thank you for any help. 

![image](https://cloud.githubusercontent.com/assets/1771823/7440314/3b81d2ea-f0ae-11e4-8823-09decd5771d9.jpg)

**Comment by ide** [comment]
Check out RCTActionSheet/ActionSheetIOS

**Comment by JonasJonny** [comment]
Thank you @ide.
