### ISSUE TITLE
AccessibilityLabels are incorrectly read on Android

### ISSUE THREAD

**Issue by eulphean** [facebook/react-native#11077]
### Description

Based on the accessibility example at https://code.facebook.com/posts/435862739941212/making-react-native-apps-accessible/, I created a small RN play example to show this problem (please follow the link in repro). 

In the RN playground example, iOS reads the labels as "Label1 Label2 Button," which is the expected way. However, on Android, it is read as "Button Label1 Label2", which is highly confusing and doesn't follow the accessibility guidelines of announcing the component trait at the end. From React-Native code, an iOS view seems to go and combine all the accessibility labels from its subviews. But not on Android. 

### Reproduction

https://rnplay.org/apps/i_dweQ - Here is an RN play link to reproduce the issue. 

### Solution

Possibly implement a similar way on Android to go and read all the content descriptions of a subview for an accessible parent view. 

### Additional Information

* React Native version: 0.37
* Platform: Android
* Operating System: MacOS

**Comment by mkonicek** [comment]
In the rnplay example there's a button with two labels inside it. Can you explain why this should be read as "Label1 Label2 Button"?

**Comment by eulphean** [comment]
@mkonicek - Thanks for your reply. 

RNplay example announces Label1 Label2 Button on iOS and Button Label1 Label2 on Android. I was hoping for some parity. Is it a platform limitation or it's just not supported in React-Native? 

If I set the accessibilityLabel on accessible=true parent in RNPlay example rather than its children, then the screenreader reads correctly as Label1 Label2 Button. However, that feels limiting as we have a lot of scenarios where we have nested components wrapped inside and we'd like how iOS recursively combines the labels for a view's children and announces Label1 Label2 Button when a button has a nested hierarchy with a11y labels. 

I'm not an a11y android expert, but is there a way to achieve parity between iOS and Android to announce labels in the same order for buttons with nested views?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/accessibilitylabels-are-incorrectly-read-on-android
