### ISSUE TITLE
Alert bugg when using Modal

### ISSUE THREAD

**Issue by hedegren** [facebook/react-native#11084]
### Description

When having a view (Modal) on screen, and then display and Alert.alert(), things gets buggy. Alert will get dismissed, and the modal will stay on screen even after a reload, must restart the app in order to remove it. 

### Reproduction

```
componentDidMount() {
    setTimeout(() => {
	Alert.alert("alert"); // Alert will be dismissed right after displayed
        this.setState({ loading: false })
     }, 1000);
}

render() {
    return (
	<View>
            <Modal visible={this.state.loading}>
		<Text>Loading</Text>
	    </Modal>
        </View>
    )
}
```

### Additional Information

* React Native version: 0.37.0

**Comment by baurine** [comment]
yes, Alert and Modal have confliction in iOS seems after react-native 0.33, already has some discuss in #10471 .

my workaround way: 

```
Alert.alert("title", "msg", [
  { text: "ok", onPress: () => { this.setState{loading: false} }
])
```

**Comment by mkonicek** [comment]
Can you reproduce this on [rnplay.org](https://rnplay.org/)? Please provide a link.

**Comment by nihgwu** [comment]
@mkonicek I've provided a full demo in #10471 , I've pinged someone but no response still.

**Comment by mkonicek** [comment]
Closing as #10471 has more info.
