### ISSUE TITLE
How to enable press handling on View element?

### ISSUE THREAD

**Issue by ReadingSteiner** [facebook/react-native#1108]
```javascript
<View>
  <Text> a </Text>
  <Text> b </Text>
  <Text> c </Text>
</View>
```
I want to handle all press event on `Text` through the parent `View` , but press handling on `View` seems not supported.
What should I do? 
May be change the parent `View` to `Text`?

**Comment by ide** [comment]
Wrap the elements in <TouchableWithoutFeedback onPress={...}>.

**Comment by ReadingSteiner** [comment]
@ide  tried, but I found when 2 or more  `Text` in `TouchableWithoutFeedback`, an exception will be thrown.
```
[tid:com.facebook.React.ShadowQueue][RCTBridge.m:1294] Exception thrown while invoking updateView on target <RCTUIManager: 0x7fc025b67010> with params (
    "<null>",
    RCTView,
        {
        opacity = "0.9861111111111112";
    }
): Invalid moduleName '(null)'
```

**Comment by ide** [comment]
Try wrapping all the Texts in a View.

**Comment by ReadingSteiner** [comment]
@ide   It works now, thank u :)
