### ISSUE TITLE
[Docs] Does facebook allow translated Docs be merged?

### ISSUE THREAD

**Issue by Beomi** [facebook/react-native#11089]
Hello, I'd like to translate react native to my language(Korean).
Currently I working on my own directory and gh-pages.
But if you provide language selection on original react native github pages, it would be great!

If we use [transfix](https://www.transifex.com), it would be much easier too.
How do you think about this translation contribute?

-- update --
I've just noticed there was issue #1168 about PR translated docs.
But it seems like you're not allowing Translated docs, right?

**Comment by charpeni** [comment]
cc @hramos

**Comment by mkonicek** [comment]
The best way would be Fresco does this. See the Korean link here: https://github.com/facebook/fresco

Agree with the answer in https://github.com/facebook/react-native/issues/1168.

**Comment by mkonicek** [comment]
It would be awesome if you could translate the docs and keep them up to date in your language! People working on RN at fb don't have the bandwidth (or language skills besides Spanish I think?) to translate to other languages.
