### ISSUE TITLE
[Android] NavigationHeader displaying on top of previous header after upgrading from 0.36 to 0.37

### ISSUE THREAD

**Issue by sunilgautam** [facebook/react-native#11086]
### Description
We have a working navigation setup using `NavigationExperimental`'s `NavigationCardStack` & `redux` on RN 0.36.
But after upgrading to 0.37, for first time `NavigationHeader` displaying on top of previous header. Second time every thing working as previous.

![upgrade-issue-0 37](https://cloud.githubusercontent.com/assets/1942128/20557331/0dbce9d0-b191-11e6-8570-39188355f3c8.png)

### Additional Information

* React Native version: 0.37
* Platform: Android
* Operating System: MacOS, Linux

**Comment by mkonicek** [comment]
Can you reproduce this on [rnplay.org](https://rnplay.org/)? Please provide a link. That way we'll be able to repro this issue?

**Comment by sunilgautam** [comment]
I tried to reproduced this [https://rnplay.org/apps/xpMhjg](https://rnplay.org/apps/xpMhjg)

But rnplay not running latest RN version.
This problems occurs in version 0.37, 0.38.

After some trial I noticed that this problem is because of `enableGestures={false}` on `NavigationCardStack`.

Everything works after removing `enableGestures={false}`.

is `enableGestures={false}` not the right way to disable gestures ??

**Comment by bendman** [comment]
This issue seems to be preventing NavigationExperimental to work correctly if native animations are used, which is unfortunate because that would be much smoother.  I've reproduced the issue in this repo: https://github.com/bendman/rn-navigator-bug

**Comment by janicduplessis** [comment]
Can you try updating to RN 0.39? This commit fixed some issues with native animations on Android https://github.com/facebook/react-native/commit/6f5433febe2c6dab5cc7b5799db7b95fc9992a11

**Comment by sunilgautam** [comment]
Closing this issue as it is fixed in RN 0.39

**Comment by JAStanton** [comment]
I am on `0.39.2` and I'm seeing this. It's not very reproducible but when navigating around occasionally I'll get the previous header rendering on top of the current header.
