### ISSUE TITLE
Hope to add attribute （ keyboardType = numberSigned） to TextInput of android

### ISSUE THREAD

**Issue by wangzhen90** [facebook/react-native#11083]
In android,we can only choose keyboardType   from 'default, numeric, email-address'.
But when use the 'numeric' , react-native  can't distinguish between integer and decimal ,but native android can.

I hope you can modify this method -- setKeyboardType of ReactTextInputManager.
Thanks!

* Platform: [ Android]
* Operating System: [ MacOS]

**Comment by janicduplessis** [comment]
If someone would like to submit a PR for this it would be nice :)

**Comment by joshyhargreaves** [comment]
I'm going to take a look submitting a PR for this!

**Comment by janicduplessis** [comment]
@joshyhargreaves Cool, let me know if you need help with anything.

**Comment by joshyhargreaves** [comment]
@janicduplessis, thanks, will do :).

**Comment by joshyhargreaves** [comment]
@janicduplessis: What's the standard way of testing something like this? Using some internal test project located somewhere in the repo? Or creating a test-project and editing corresponding files as installed via node_modules?

**Comment by janicduplessis** [comment]
I usually use the UIExplorer example project that's in the repo. To run it you can just open the xcodeproj in Examples/UIExplorer for ios or run `./gradlew Examples:UIExplorer:android:app:installDebug` for Android. You also need to start the packager with `./packager/packager.sh`.

**Comment by joshyhargreaves** [comment]
@janicduplessis. I was actually building the UIExplorer app anyway actually, hadn't figured where you started the packager, so thanks :). 

Looks like this is the reason we're not distinguishing between number and decimal. https://github.com/facebook/react-native/blob/1b870d201976455303ee176c03a4824eac07e11b/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactTextInputManager.java#L71

Any thoughts on sensible property values for keyboardType? 'numberSigned', 'decimalSigned'? (should we do unsigned?) Are we doing anything similar on IOS?

**Comment by janicduplessis** [comment]
The current value is `numeric` which is decimal (unsigned) right?

So I'd keep this as is, so we don't make a breaking change and add something like `numeric-unsigned` for the new value.

**Comment by janicduplessis** [comment]
Actually the initial issue was about decimal vs integer so maybe add `integer`.

**Comment by joshyhargreaves** [comment]
Seems sensible! I'll do that.

**Comment by joshyhargreaves** [comment]
Just as a test I'm explicitly setting the InputType to numeric, which as far as I'm aware *should* not allow decimal input unless you bitwise or with InputType.TYPE_NUMBER_FLAG_DECIMAL. Strangely, the keyboard is still allows decimal input, unless there's something I'm missing?

![image](https://cloud.githubusercontent.com/assets/1807207/20641264/40b39728-b3ec-11e6-826d-38dacff17abe.png)

![image](https://cloud.githubusercontent.com/assets/1807207/20641265/4a423452-b3ec-11e6-9f26-6e5eb2d3c2b7.png)

**Comment by janicduplessis** [comment]
Not sure why we do this, if you remove the call to add the key listener does it work as you expect?

**Comment by janicduplessis** [comment]
Here's the commit that added this https://github.com/facebook/react-native/commit/fa4a5afe35af4e93059b089c3107af916a5b21ab. Maybe the reasoning is we'd rather have the logic for which key is allowed in JS by using a controlled component and filtering out keys that should not be allowed.

**Comment by joshyhargreaves** [comment]
A wow, very interesting; should have thought to look at the commit history of the file myself, now I think about it. Hmm, what do we think? Is this some logic we'd add to TextInput.js? Or, given that TextInput is a controlled input, do we say that this logic can be done externally?

**Comment by janicduplessis** [comment]
I think that if the flags don't affect the apparence of the keyboard then we can say that this logic can be done externally and not add new values to keyboardType. After all the prop is called keyboardType so it's more about what kind of soft keyboard is shown and not what values are allowed.

**Comment by joshyhargreaves** [comment]
Yep, I agree with this. Seems like something that could/should be done externally. Yes you're right, the prop is to do with the keyboard type and not which values are allowed :).

**Comment by joshyhargreaves** [comment]
@wangzhen90, can you confirm that there are no differences in the appearance of the keyboard, just what 'valid' characters can be entered?

**Comment by joshyhargreaves** [comment]
@wangzhen90 : bump :)

**Comment by Strayer** [comment]
A native way of filtering TextInput would be great. I'm trying to add a "integer" field too and have a not-so-great workaround that filters the entered value in onChangeText, causing the entered values to briefly appear, before the JavaScript was able to do its work. Even if the keyboard doesn't have unwanted characters (like number-pad on iOS), hardware keyboards still can input values that may be unwanted by the developer.

Maybe a property like "allowedCharacters" would make sense, so this could be filtered natively by the iOS and Android components before JavaScript is even involved.

**Comment by rajsuvariya** [comment]
Is this feature already implemented? Otherwise, I would like to try working on this feature.

**Comment by hramos** [comment]
Closing as this is a request for a new feature, rather than a bug report.
