### ISSUE TITLE
WebView Documentation

### ISSUE THREAD

**Issue by jacobp100** [facebook/react-native#11098]
The documentation isn’t clear on how the `source` prop works. It’s not controlled, like `value` in `input` components, and not only considered on initial mount, like `defaultValue`. It’s half-way between: if it changes, it’ll cause an update, otherwise it is allowed to be out-of-sync with the prop.

Is this normal in React? What is the intended behaviour of this prop?

I’m happy to document this if this is clarified.

**Comment by mkonicek** [comment]
Hi, what do you mean by "out-of-sync with the prop"? Can you please provide an rnplay link where it's out of sync?

**Comment by jacobp100** [comment]
If you set `source={{uri:'google.com'}}` and then use links in the page to end up on another site, your props no longer reflect the state of the web view.

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
