### ISSUE TITLE
Slow build process due to static analyzer

### ISSUE THREAD

**Issue by oNaiPs** [facebook/react-native#11107]
### Description

When building either for Debug or Release configurations, static analyzer also runs making the builds run for much longer.
This xcode flag makes React source files to be compiled twice, which doubles build time (if you don't have any native code in the project).

### Reproduction

1. Create a project with `react-native init myproject`
2. Build the project
3 . Observe `Analyzing files` when building.

<img width="488" alt="screen shot 2016-11-23 at 10 08 18 pm" src="https://cloud.githubusercontent.com/assets/374130/20588384/708d4bbc-b1c9-11e6-9a9c-49f2c4695a77.png">

### Solution

`Analyze During 'Build'` xcode configuration should be off.

### Additional Information

* React Native version: 0.38
* Platform: iOS
* Operating System: MacOS

**Comment by mkonicek** [comment]
There's an alternative: use `react-native run-ios` from the command line if you only write JS. That way Xcode is not running and no code is being analyzed.

**Comment by oNaiPs** [comment]
I don't only write JS (our codebase has over 30 source files and counting).
I'm making a case for it because if you put this into CI you have a couple minutes overhead for nothing.

Is there any use case for the developers doing the Analyze of react source code files? It seems to me it would only be interesting for people modifying the SDK.

**Comment by gastonmorixe** [comment]
I added this in `package.json` to stop static analyzer

```
  "scripts": {
   ...
    "postinstall": "sed -i '' '/RUN_CLANG_STATIC_ANALYZER/d;/CLANG_STATIC_ANALYZER_MODE/d;/CLANG_ANALYZER_NONNULL/d' ./node_modules/react-native/React/React.xcodeproj/project.pbxproj"
  }
```

**Comment by oNaiPs** [comment]
@gastonmorixe thanks for your input. I ended up doing something similar 👍
