### ISSUE TITLE
Simulating iPad renders strangely

### ISSUE THREAD

**Issue by cwahlfeldt** [facebook/react-native#11102]
### Description

I ran `react-native run-ios --simulator "iPad Air 2"` and I expected the app to utilize the entire windows space but it ended up running within a frame and theirs an extra control on the bottom right that I can shrink the window down.

![screen shot 2016-11-23 at 4 34 04 pm](https://cloud.githubusercontent.com/assets/4119720/20581374/17079f32-b19e-11e6-9b84-04b01a72ad4a.png)

I have tried this with iPad Retina, iPad Air, iPad Pro (9.7) & (12.9) with the exact same results.

### Reproduction

Simply run `react-native run-ios --simulator "iPad Air 2"` in a react-native project. Also try the other iPad models.

### Solution

Could it be that I'm missing a setting in xCode?

### Additional Information

* React Native version: react-native-cli: 1.2.0, react-native: 0.37.0
* Platform: iOS
* Operating System: Mac OS Sierra 10.12.1

**Comment by rodriguesbreno** [comment]
@cwahlfeldt Have you changed the Xcode project? 
You should set the app to universal. The default is only iPhone

**Comment by rodriguesbreno** [comment]
<img width="890" alt="ex1" src="https://cloud.githubusercontent.com/assets/19731692/20582669/588ec3f0-b1ca-11e6-9c8a-37ba0ff0e9ef.png">

<img width="806" alt="ex2" src="https://cloud.githubusercontent.com/assets/19731692/20582674/66080a8c-b1ca-11e6-9ca8-352e9766c814.png">

**Comment by cwahlfeldt** [comment]
This totally worked thanks!
