### ISSUE TITLE
Flex styles are not working for WebView

### ISSUE THREAD

**Issue by NoelBroda** [facebook/react-native#11101]
### Description
What I did: Check the `rnplay`
What is happening: Flex styles are not working for WebView
What should happens: Flex working for WebView

### Reproduction
https://rnplay.org/apps/K8tUAw

Check line 24 (`<WebView style={styles.webview} source={{uri: 'http://random.org'}}></WebView>`).
Replace that line for: `<View style={styles.webview}></View>` and you will see that the View is working with Flex values.

If you add a `width: 300` value in `styles.webview` (for the WebView component), you will see it will works.

### Solution
No idea.

### Additional Information

* React Native version: 
react-native-cli: 1.2.0
react-native: 0.37.0
* Platform: Both
* Operating System: MacOS

**Comment by mkonicek** [comment]
Here's a WebView stretched to fill its parent: https://rnplay.org/apps/z3g5qw

**Comment by mkonicek** [comment]
Check out https://css-tricks.com/snippets/css/a-guide-to-flexbox/

**Comment by keshavkaul** [comment]
I'm running react-native v 0.42.0 and am facing problems in laying out WebView with flex
```
<View style={{flex: 1, backgroundColor: 'red'}}>
                <WebView style={{flex: 10, backgroundColor: 'yellow'}} source={{
                    html: `
                    <html>
                        <head></head>
                        <body style="background-color: red;">
                            Hi this is a html body
                        </body>
                    </html>    
                    `
                }}/>
                <Text style={{flex:1, backgroundColor: 'blue'}}>
                    Hello There!
                </Text>
            </View>
```

In the above snippet, the WebView flex should cover more height as I have set `flex=10`. But that's not the case.
![simulator screen shot 31-mar-2017 7 24 04 pm](https://cloud.githubusercontent.com/assets/3319809/24553383/ba50ee42-1647-11e7-9b11-5cb271d6d426.png)

**Comparing the above to working flex example:**

```
<View style={{flex: 1, backgroundColor: 'red'}}>
                <Text style={{flex:10, backgroundColor: 'yellow'}}>
                    Hi Again!
                </Text>
                <Text style={{flex:1, backgroundColor: 'blue'}}>
                    Hello There!
                </Text>
            </View>
```
![simulator screen shot 31-mar-2017 7 23 31 pm](https://cloud.githubusercontent.com/assets/3319809/24553449/ebd9652a-1647-11e7-8300-56e702632a10.png)

**Comment by XeeshanAnsari** [comment]
I also facing problem like @mkonicek

**Comment by zfang6** [comment]
Is this issue addressed?

**Comment by LeeZC** [comment]
hi guys 。。。。i fixed in my case,like:

**Comment by LeeZC** [comment]
hi guys , i fixed in my case, like :

**Comment by LeeZC** [comment]
hi guys , i fixed in my case, by package a father view , like: 

<View style={{flex:10}}>
           <WebView  style={{flex:1}} />
</View>
<View style={{flex:1}}>
           <WebView  style={{flex:1}} />
</View>

**Comment by LeeZC** [comment]
hi guys , i fixed in my case, by package a father view , like: `
<View style={{flex:10}}>
           <WebView  style={{flex:1}} />
</View>
<View style={{flex:1}}>
           <WebView  style={{flex:1}} />
</View>`
