### ISSUE TITLE
Issues upgrading react-native

### ISSUE THREAD

**Issue by NoelBroda** [facebook/react-native#11104]
### Description
Following the "Upgrading" documentation (https://facebook.github.io/react-native/docs/upgrading.html), I'm not able to upgrade `react-native`

### Reproduction
Run `npm install --save react-native@0.38.0` having installed version `0.37.0`

You will see this log:
```
➜  xxx git:(master) ✗ npm install --save react-native@0.38.0
 npm WARN peerDependencies The peer dependency react@~15.4.0-rc.4 included from react-native will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
 
> spawn-sync@1.0.15 postinstall /Users/xxx/Personal/xxx/node_modules/react-native/node_modules/yeoman-generator/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

npm ERR! Darwin 16.1.0
npm ERR! argv "/Users/xxx/.nvm/versions/node/v4.4.5/bin/node" "/Users/xxx/.nvm/versions/node/v4.4.5/bin/npm" "install" "--save" "react-native@0.38.0"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react@15.3.2 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-native@0.38.0 wants react@~15.4.0-rc.4
npm ERR! peerinvalid Peer react-test-renderer@15.3.2 wants react@^15.3.2

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xxx/Personal/xxx/npm-debug.log

```

### Solution
Add information about how to upgrade properly `react-native`

### Additional Information

* React Native version: 0.37.0
* Platform: N/A
* Operating System: MacOS

**Comment by Ehesp** [comment]
Have you installed react 15.4?

```
"react": "15.4.0",
```

**Comment by mkonicek** [comment]
This is really confusing, sorry! Here's a PR for the docs:
https://github.com/facebook/react-native/pull/11123

We'll release a new upgrade tool soon where we should fix this.

**Comment by NoelBroda** [comment]
@mkonicek is there a PR related? Or is it something you are thinking right now?

If you want, you can give a clue about how/where to do it, and I can send a PR.

**Comment by mkonicek** [comment]
> If you want, you can give a clue about how/where to do it, and I can send a PR.

I'm not sure I understand. Send a PR for what exactly?

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
