### ISSUE TITLE
Inform about root component registering in docs

### ISSUE THREAD

**Issue by karuppiah7890** [facebook/react-native#11105]
### Description

[FILL THIS OUT: Explain what you did, what you expected to happen, and what actually happens.]

I was following the React Native Docs - the props tutorial

And the docs said that code regarding registering the root component were provided so that it could be copy pasted completely to run it and check. Some code like this : 

```javascript
AppRegistry.registerComponent('Bananas', () => Bananas);
```

And when I tried this out, I got some errors saying this : 
![react native](https://cloud.githubusercontent.com/assets/12808424/20586816/cc0208d4-b22d-11e6-93b7-56860c54391d.png)

When I meddled and changed the code to this : 

```javascript
AppRegistry.registerComponent('ReactNativeApp', () => ReactNativeApp);
```
it worked! I was just guessing it. Because the boilerplate code had this line and I changed the whole boilerplate code by copy pasting the one in the docs to check if it works and see what happens.

`ReactNativeApp` is the name of my App and is the project name. The one I used when I ran the `react-native init` command.

So, the docs should mention that the root component's name must be the same as the App name.

The github repo file for the props docs page 
https://github.com/facebook/react-native/blob/master/docs/Props.md

And the same occurs for `Hello World` tutorial too, I didn't notice it there since I was just changing the boiler plate code and not replacing the whole code in `index.android.js`

### Reproduction

Just change the name of the root component's name and set it to anything other than the App's name.

### Solution

I don't know how or why it is necessary to use the App's name as the root component's name while registering it. But since the docs said we would most probably have to use the `AppRegistry.registerComponent()` only once, and since it's the root component, it kind of makes sense.
But the docs need to tell the user to use the App's name as the root component's name in `AppRegistry.registerComponent()` instead of the one in the docs.

### Additional Information

* React Native version: React v0.38 and react-native CLI 1.2.0
* Platform: Android ( I think this issue occurs even in iOS. It's irrespective of platform )
* Operating System: Linux

**Comment by yueshuaijie** [comment]
If you change root component register name, you should change the corresponding name string in java code(not App's name)

**Comment by karuppiah7890** [comment]
Oh...well, then something has to be informed to the users to not get errors.

And what name string in Java ? And where ?

You mean change the `name` resource in `string.xml` resource file where it says something like this ? 

```xml
<string name="app_name">ReactNativeApp</string>
```

**Comment by mkonicek** [comment]
I see how this can be confusing! Could you please send a pull request to clarify this in the docs in a way that would make this obvious to you?

**Comment by karuppiah7890** [comment]
@mkonicek But I need to know more about this thing. And if I am gonna make that change or put up a note to inform users about this, then that note should be put up in every example. Or the user should be made aware that the note is applicable to all examples.

And may be there is an easier work around for this ? I don't know. But if there is, we could tell that to users.

And by the way, why close the issue when it's not solved ?
