### ISSUE TITLE
[NavigationExperimental] how to disable animation on reset route

### ISSUE THREAD

**Issue by Hitabis** [facebook/react-native#11114]
When Resetting the routes on NavigationExperimental with more then one route the navigator animates to the second route. How do I prevent this? I just want the second scene to be displayed.
For example: 
`resetRoutesTo([
{key: 'GroupsIndex', title: "Groups"}, 
{key: 'QuestionsIndex'}
])`
with this reducer.
```
    case RESET_ROUTES_TO:
      return NavigationStateUtils.reset(state,action.routes)
```
it still animates.

**Comment by mkonicek** [comment]
Can you reproduce this on [rnplay.org](https://rnplay.org/)? Please provide a link.

**Comment by Hitabis** [comment]
@mkonicek Somehow its not working in rnplay, but here is a short example:
https://rnplay.org/apps/q85Y1A
I want to reset the route to [Master,Detail] and Detail animates from the right. How can I prevent the animation?

**Comment by mkonicek** [comment]
Thanks! cc @ericvicenti who wrote AnimationExperimental.

**Comment by ericvicenti** [comment]
@skevy, any thoughts on how to handle disabling of animations?

My first thought is that we should add a prop like `enableAnimation` to NavigationCardStack, which will configure the animation to look instant. We can eventually offer nicer ways of changing this other than the prop.

**Comment by robcalcroft** [comment]
I'm also having this issue, I'm using `NavigationStateUtils.reset` to switch between nav tabs and I find there is a lag between when I press the tab and when the view is rendered, I'm assuming its because its running an animation before it renders?

**Comment by henrikra** [comment]
I also having this bug when I have for example 3 routes in state and then I have this reset action my reducer:
```
case RESET_ROUTES:
      return NavigationStateUtils.reset(state, [action.route]);
```
After this animates old routes out. I would also like to disable animation or do normal push animation but without these old animations to pop out :/

**Comment by hramos** [comment]
Navigation Experimental has been deprecated in favor of the [`react-navigation`](https://reactnavigation.org) library.

**Comment by sdg9** [comment]
Heads up for those migrating from navigation experimental to react-navigation the [same problem exists there](https://github.com/react-community/react-navigation/issues/738).
