### ISSUE TITLE
I'm failed when I  did start npm server  and I am using win10 os

### ISSUE THREAD

**Issue by SwainZhang** [facebook/react-native#11127]
D:\ReactNative\myfour>npm start

> myfour@0.0.1 start D:\ReactNative\myfour
> node node_modules/react-native/local-cli/cli.js start
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EINVAL
    at exports._errnoException (util.js:1022:11)
    at WriteStream.Socket._writeGeneric (net.js:715:26)
    at WriteStream.Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at WriteStream.Writable.write (_stream_writable.js:247:11)
    at WriteStream.Socket.write (net.js:661:40)
    at WriteStream.stream.write (D:\ReactNative\myfour\node_modules\ansi\lib\newlines.js:36:21)
    at Object.execFileSync (child_process.js:506:20)
    at Object.run (D:/ReactNative/myfour/node_modules/react-native/local-cli/cliEntry.js:159:16)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! myfour@0.0.1 start: `node node_modules/react-native/local-cli/cli.js start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the myfour@0.0.1 start script 'node node_modules/react-native/local-cli/cli.js start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the myfour package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/react-native/local-cli/cli.js start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs myfour
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls myfour
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\ReactNative\myfour\npm-debug.log

D:\ReactNative\myfour>npm bugs myfour

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "bugs" "myfour"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npm.taobao.org/myfour
npm ERR! 404
npm ERR! 404  'myfour' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\ReactNative\myfour\npm-debug.log

**Comment by mkonicek** [comment]
What are the contents of D:\ReactNative\myfour\npm-debug.log?

Can you try creating a new app with 'react-native init' and run that?

**Comment by DeltinoRosso** [comment]
Same Issue here,

as attachment you can find my npm-debug.log which I made with a new init as you adviced. 


[npm-debug.txt](https://github.com/facebook/react-native/files/629757/npm-debug.txt)

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
