### ISSUE TITLE
react-native install to use Yarn

### ISSUE THREAD

**Issue by theobouwman** [facebook/react-native#11122]
`react-native install` does not use Yarn if available

**Comment by mkonicek** [comment]
Hey, thanks for reporting this issue!

It's only supported in `react-native init`: http://facebook.github.io/react-native/blog/2016/11/08/introducing-button-yarn-and-a-public-roadmap.html

Good point, need to support it also in `react-native install`. Thanks!

**Comment by mkonicek** [comment]
PRs welcome! :)

**Comment by saigrandhi** [comment]
I would like to work on this issue. Which files should I look at to solve it?

**Comment by leeight** [comment]
@saigrandhi `local-cli/install`

**Comment by olingern** [comment]
I hope it's okay I've taken a stab at this. I help a little bit with Yarn, so I'd love to see it grow. 

A bit green to the project, and I didn't see an obvious way to invoke the `local-cli/install` command (a bin folder, for example). Could you point me toward testing this out?

I've opened a "rough draft" of a PR #11280.
