### ISSUE TITLE
ScrollView not scrolling when 'column-reverse' in flexDirection

### ISSUE THREAD

**Issue by vaibhawc** [facebook/react-native#11120]
ScrollView would scroll perfectly when using default 'column' in flexDirection but same wouldn't scroll at all when 'reverse' is used.
Is that how it is supposed to be? It lacks proper documentation.
Also, an observation : the items are rendered in order when 'reverse' is used in ScrollView, which is flip in View, why such a behavior? It's very confusing.

**Comment by mkonicek** [comment]
Can you reproduce this on [rnplay.org](https://rnplay.org/)? Please provide a link.

**Comment by mkonicek** [comment]
Can you reproduce this on [rnplay.org](https://rnplay.org/)? This is necessary for people to be able to understand and debug the issue being reported.

Closing this issue as it is not actionable. Please open a new one with an rnplay link (preferred), or link to a GitHub repo with clear instructions how to repro.
