### ISSUE TITLE
TouchableOpacity hangs when using navigator.push in onPress method

### ISSUE THREAD

**Issue by Clcll** [facebook/react-native#11132]
I am using ListView, each Item of ListView is TouchableOpacity component. onPress I need to navigate to another page. So onPress method I call _navigator(). But when I press on Item (TouchableOpacity element) its hangs on several seconds about 4-5s. Here an example of my code.
http://stackoverflow.com/questions/40770420/touchableopacity-hangs-inside-listview-when-i-am-using-navigation-in-onpress-met

Here short version of my cod jsfiddle.net/eczdpw1y 
Thank you

**Comment by younthu** [comment]
If you have enabled remote js debugger, it will hang for seconds some times, normally, there should be no hang.

**Comment by Clcll** [comment]
@younthu Thank you for response. It works this way in Release version, without debugger. When I removed navigate method from onPress TouchableOpacity works fine without hangs on response, but when i put navigate method back. I started hangs.

**Comment by mkonicek** [comment]
Can you reproduce this on [rnplay.org](https://rnplay.org/)? This is necessary for people to be able to understand and debug the issue being reported.

Closing this issue as it is not actionable. Please open a new one with an rnplay link (preferred), or link to a GitHub repo with clear instructions how to repro.
