### ISSUE TITLE
<TouchableOpacity> conflicts to PanResponder

### ISSUE THREAD

**Issue by ele828** [facebook/react-native#1113]
I wanna implement a side-menu function. The side-menu use ``PanResponder`` so as to slide out from left with finger moves.

And the content view is a ScrollView and it contains of some TouchableOpacity items.

The problem is that when I move from left to right, the ``PanResponder`` doesn't work, Instead, ``TouchableOpacity`` is activated.

Here is my project if needed:
https://github.com/leanote/leanote-ios

Thanks a lot :)

![](http://i1.tietuku.com/e64d481d5919f571.png)

**Comment by ele828** [comment]
I solved it use following method :P
```
handleMoveShouldSetPanResponder: function(e: Object, gestureState: Object) {
       var x = gestureState.dx;
       var y = gestureState.dy;
       if (x != 0 && y == 0) {
         return true;
       }
       return false;
  },
```

**Comment by iostalk** [comment]
This is awesome!酷毙了
