### ISSUE TITLE
0.34 is missing release notes

### ISSUE THREAD

**Issue by mikelambert** [facebook/react-native#11143]
https://facebook.github.io/react-native/versions.html lists many versions, each with release notes (including breaking changes)

But 0.34 doesn't link to any release notes, since it points at `0.34.0`. The release notes can only be found at `0.34.1`: https://github.com/facebook/react-native/releases/tag/v0.34.1

I went to try to submit a patch, but it's JS code that only points at `v0.xx.0` versions for release notes: https://github.com/facebook/react-native/blob/23331df5a40ad8ddff58f561af24d7401b62e330/website/src/react-native/versions.js#L39 ...so I decided to just file this issue instead.

**Comment by mkonicek** [comment]
Thanks! Fixed: https://github.com/facebook/react-native/releases/tag/v0.34.0

Checked release notes for all releases down to 0.26, hopefully no one uses older RN versions than that :)

**Comment by mikelambert** [comment]
So this appears to have broken again:
https://facebook.github.io/react-native/versions.html links to broken release notes for 42, 43, 44.

The correct (albeit unlinked) release notes can be found at:
https://github.com/facebook/react-native/releases/tag/v0.42.3
https://github.com/facebook/react-native/releases/tag/v0.43.4
https://github.com/facebook/react-native/releases/tag/v0.44.1
