### ISSUE TITLE
[React native 0.38]Invariant Violation: __fbBatchedBridgeConfig is not set, cannot invoke native modules 

### ISSUE THREAD

**Issue by lengocgiang** [facebook/react-native#11141]
I created new project by using `react-native init [project_name]`

This error apprear when i run `react-native run-android` 

![Image](http://imgur.com/download/Vv5ckfk)

`"dependencies": {
    "react": "15.4.1",
    "react-native": "0.38.0"
  },`

**Comment by mkonicek** [comment]
Is the packager running?

Try running 'npm start' in your app folder.

**Comment by lengocgiang** [comment]
@mkonicek : it works, thanks you bro
