### ISSUE TITLE
RCTBridge crashes in release build when moduleID or methodID is not found

### ISSUE THREAD

**Issue by artemyarulin** [facebook/react-native#1114]
Hi,

In the [RCTBridge.enqueueJSCall](https://github.com/facebook/react-native/blob/master/React/Base/RCTBridge.m#L1083) we have asserts that checks that moduleID and methodID are never null, however in a release build they will be skipped, so we will end up with a crash because arguments array cannot be created with null values.

**Comment by artemyarulin** [comment]
Here the pull request that fixes this issue. While I'm a bit concerned how we can create a unit-test for that.

And actually the bigger question is - should it be fixed? If yes, then we have to go through all RCTAssert and check that in never fails afterwards, but at the same time the whole point of RCTAssert is to tell that we faced unexpected. What it is your thoughts about it?

Thanks

**Comment by brentvatne** [comment]
Awesome, thanks for the report and patch @artemyarulin! Closing this issue as the discussion is being tracked in the PR now. :rocket:
