### ISSUE TITLE
Problems after upgrading to React Native 0.38.0

### ISSUE THREAD

**Issue by andrycodestuffs** [facebook/react-native#11147]
### Description

After upgrading from React Native 0.34 to 0.38 requiring custom components for navigation results in:
Requiring unknown module: "react/lib/ReactNativePropRegistry"

### Additional Information

* React Native version: 0.38.0
* Platform: Android
* Operating System: MacOS 10.12.1

**Comment by mkonicek** [comment]
I don't understand "requiring custom components for navigation results in". We'll need to see the code to debug this.

Can you reproduce this on [rnplay.org](https://rnplay.org/)? Please provide a link. That way it will be possible for others to reproduce and debug this issue.

Closing as this is not actionable. Please open a new issue with full code on rnplay to reproduce this.
