### ISSUE TITLE
Navigator.product set to gecko in versions 0.37/0.38

### ISSUE THREAD

**Issue by morsdyce** [facebook/react-native#11154]
### Description

When accessing navigator.product in react native versions 0.37 and 0.38 the output is Gecko instead of React native as changed in https://github.com/facebook/react-native/issues/1331

### Reproduction

To reproduce create a new app and add `console.log(navigator.product)` to the index file.

`react-native init myApp --version react-native@0.36` 
`console.log(navigator.product) -> 'ReactNative'`

`react-native init myApp --version react-native@0.37` 
`console.log(navigator.product) -> 'Gecko'`

`react-native init myApp --version react-native@0.38`
`console.log(navigator.product) -> 'Gecko'`

### Additional Information

* React Native version: 0.38
* Platform: iOS, did not test on android
* Operating System: MacOS 10.11.3

**Comment by leeight** [comment]
Fixed on https://github.com/facebook/react-native/commit/ad36c1af713dded38e3f0b25965e95d11088c82d
