### ISSUE TITLE
[android][0.37] scrollview, list view auto scroll to lastest position before app go to back ground

### ISSUE THREAD

**Issue by InnerPeace080** [facebook/react-native#11151]
i build a list view that will display new item at **top of list** .
when i scroll down list view and make app goto back ground , and i come back after that i scroll my list view to top (my list view fetch new item when it is at top)

When **receiver new item** and rerender list view , it **auto scroll** to **lastest position** before app goto back ground 

every thing fine if i push new item at bottom of listview. i spend my 3 day for this issue but don't know why . I place breakpoint in every scrollTo function when this happen but it not run to any breakpoint . Very confusing.

Please help me :(((

**Comment by mkonicek** [comment]
Can you provide a minimal amount of code to reproduce this on [rnplay.org](https://rnplay.org/)? This is necessary for people to be able to see and debug the issue being reported.

Closing this issue as it is not actionable. Please open a new one with an rnplay link (preferred), or link to a GitHub repo with clear instructions how to repro.
