### ISSUE TITLE
BaseActivityEventListener

### ISSUE THREAD

**Issue by erhutime** [facebook/react-native#11167]
Hi all：
   "dependencies": {
    "react": "15.4.1",
    "react-native": "0.38.0"
  },   
public class SuperRealModule extends ReactContextBaseJavaModule {
    private static final int IMAGE_PICKER_REQUEST = 467081;
    private Promise resultPromise;

    @Override
    public String getName() {
        return "SuperRealModule";
    }

    public SuperRealModule(ReactApplicationContext reactContext) {
        super(reactContext);
        reactContext.addActivityEventListener(listener);
    }

    @ReactMethod
    public void intentShowActivity(final Promise promise){
        if (mContext == null) {
            promise.reject("", "");
            return;
        }
        resultPromise = promise;
        try {
            Intent intent = new Intent(mContext, SuperManActivity.class);
            intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
            Bundle bundle =new Bundle();
            intent.putExtras(bundle);
          getCurrentActivity().startActivityForResult(intent, IMAGE_PICKER_REQUEST,bundle);
        } catch (Exception e) {
            resultPromise.reject(E_FAILED_TO_SHOW_PICKER, e);
            resultPromise = null;
        }
    }

    private BaseActivityEventListener listener = new BaseActivityEventListener(){
        @Override
        public void onActivityResult(Activity activity, int requestCode, int resultCode, Intent data) {
            super.onActivityResult(activity, requestCode, resultCode, data);
            if (requestCode == IMAGE_PICKER_REQUEST) {
                if (resultPromise != null) {
                    if (resultCode == RESULT_OK) {
                        Bundle b = data.getExtras();
                        String result =b.getString("result");
                        if (result.equals("2")) {
                            resultPromise.resolve(2);
                        } else {
                            resultPromise.reject("No image data found", "No image data found");
                        }
                    }
                    resultPromise = null;
                }
            }
        }
    };
}
当我执行此代码时，可以看出，先执行intentShowActivity，然后onActivityResult，然后执行完毕之后，跳转到下一个Activity页面中，或者还没有进入到下一个页面执行操作，onActivityResult方法就执行了。
大神们，有解决方法吗？

(translation: When I execute this code, it can be seen, first perform the intentShowActivity, then onActivityResult, and then after the completion of the jump to the next Activity page, or has not yet entered the next page to perform the operation, onActivityResult method is executed.
Great God, there are solutions?)

**Comment by lacker** [comment]
Let me see if I understand this problem - events are happening out of order from what you expect? What is the expected order of events, and the actual order of events? Also could you provide a rnplay.org link?

**Comment by erhutime** [comment]
I think the executive order is when I go to the next page and do something, and after the operation, return to this page, will be executed  onActivityResult。but , when i go to the next page , onActivityResult is executed or i jump to next page time.

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
