### ISSUE TITLE
The "right" way of doing push notifications in iOS??

### ISSUE THREAD

**Issue by npomfret** [facebook/react-native#11162]
Thanks for adding in the completionHandler callback to the iOS push notifications library.  I'm still having problems getting it to work adequately though.  Specifically there seems to be an issue around handling push notifications after the OS has terminated the app.  

It seems that when your app is in a background state, iOS will kill it at some point (presumably in order to free up memory for other processes).  And from my experiments it appears that iOS will terminate an app from the background state quite liberally - it's a very common thing.  However, if the OS does terminate your app from the background state, it will also revive it should a push notification arrive so long as that notification contains the important `content-available=1` flag, AND you've allowed _Remote Notifications_ in background modes for your app.   

As of RN0.38, if you receive a push notification that has the `content-available=1` flag, you MUST call the `finish` method which in turn invoke the _fetchCompletionHandler_.  If you don't invoke the _completionHandler_, the OS will penalise your app for taking up resources and will slow down (or stop) notification delivery - which it does (again quite liberally).  I believe you have around 30 seconds of wall clock time to call the _fetchCompletionHandler_, after which the OS will put you on its naughty list and your app will stop working properly. 

So, from the __terminated state__ I can see a push notification arriving, and I can see the OS starting my app. In my `AppDelegate` I have this:

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  UILocalNotification *remoteNotif = [launchOptions objectForKey: UIApplicationLaunchOptionsRemoteNotificationKey];
  
  if (remoteNotif) {
    NSLog(@"push notification when app is not open");
  }
  ...
```

And I see the message "push notification when app is not open" in the logs. All Good.  It works fine when the app is in the foreground and when it's in the background, but not so when terminated.

The next thing to happen is that `-application:didReceiveRemoteNotification:fetchCompletionHandler` get's called:

```
-(void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)notification fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler {
  NSLog(@"push-notification with content body => %@", notification);

  if(application.applicationState == UIApplicationStateInactive) {
    NSLog(@"push-notification app:Inactive");
  } else if (application.applicationState == UIApplicationStateBackground) {
    NSLog(@"push-notification app:Background");
  } else {
    NSLog(@"push-notification app:Active");
  }
  
  [RCTPushNotificationManager didReceiveRemoteNotification:notification fetchCompletionHandler:completionHandler];
}
```

And in the logs, as expected I see _"push-notification app:Background"_.  But, **immediately** after this line in the logs I see the following warning:

```
Nov 28 10:53:17 Tests-iPhone pomochat[1139] <Notice>: push-notification app:Background
Nov 28 10:53:17 Tests-iPhone pomochat(UIKit)[1139] <Notice>: Warning: Application delegate received call to -application:didReceiveRemoteNotification:fetchCompletionHandler: but the completion handler was never called.
```

From this it looks to me as if the app is not given any time at all to process the incoming push notification.  The warning that the _completionHandler_ was not called happens immediately and my JS code doesn't get a chance to run.  I do not see this message when the app is running in the foreground or background.

I suppose my question is - _how do you get a react-native app to gracefully handle an iOS push notification that arrives after the OS has terminated the app_? 

From the [apple docs](https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html#//apple_ref/doc/uid/TP40007072-CH4) I gather that an approach to this is to start a background task as soon as a notification arrives.  I don't see anywhere in the RN code base where a background task is started, and I'm now actually wondering how push notifications work when the app is in the background **without** starting a background task.

As an experiment I tried the following, it's a dirty hack, but my app started behaving better in this situation:

```
-(void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)notification fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler {
  NSLog(@"push-notification with content body => %@", notification);

  if(application.applicationState == UIApplicationStateInactive) {
    NSLog(@"push-notification app:Inactive");
  } else if (application.applicationState == UIApplicationStateBackground) {
    NSLog(@"push-notification app:Background");
  } else {
    NSLog(@"push-notification app:Active");
  }
  
  [RCTPushNotificationManager didReceiveRemoteNotification:notification fetchCompletionHandler:completionHandler];

//start hack
  self.pnBgTask = [application beginBackgroundTaskWithName:@"MyPNTask" expirationHandler:^{
    [application endBackgroundTask:self.pnBgTask];
    self.pnBgTask = UIBackgroundTaskInvalid;
  }];
  
  dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
    
    [NSThread sleepForTimeInterval:25.0f];//dodgy hack to give it a chance to complete the 'real' bg-task
    
    [application endBackgroundTask:self.pnBgTask];
    self.pnBgTask = UIBackgroundTaskInvalid;
  });
//end hack
}
```

With this change my app appears to work much better when running from xCode, but I haven't tried it out in _real deployed_ app yet.  

Thanks for any ideas.

By the way, in order to test this you either need to get iOS to terminate you app (which as far as I can see is close to impossible to do), or - either simply stop it form inside Xcode or [change the launch settings](https://medium.com/@milkservice/there-is-an-easier-way-in-scheme-settings-there-is-an-option-wait-for-executable-to-be-launched-b145d85d17e0#.hz4oaqage)  to use "Wait for executable to be launched", then send your push notification and the app will start from a terminated state.

**Comment by mkonicek** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.

**Comment by npomfret** [comment]
I really think this is an issue with react-native. The absence of a background task prevents RN apps from processing push notifications in certain situations.

**Comment by JAStanton** [comment]
Thank you for bringing this up @npomfret it appears I may not be handling every case of push notification waking up the app. I tested the scenario you listed and I got this:

```
11/28/16, 11:44:37 AM assertiond[66]: <BKNewProcess: 0x103e23720; com.convoy.driver.development; pid: 5153; hostpid: -1> has active assertions beyond permitted time: 
{(
    <BKProcessAssertion: 0x103e20f00> id: XX name: Background Content Fetching (240) process: <BKNewProcess: 0x103e23720; com.convoy.driver.development; pid: 5153; hostpid: -1> permittedBackgroundDuration: 30.000000 reason: backgroundContentFetching owner pid:57 preventSuspend  preventThrottleDownUI  preventIdleSleep  preventSuspendOnSleep 
)}
```

which makes me think the app was penalized. I added your hack and I didn't receive this but I was unsure if my app ran in the background after the app got the remote notification. Still some testing to do.

Another question I had is that what happens when the app is backgrounded but not suspended with this hack in place. If I call my completion handler will the app still remain awake because of the background task? Seems like thats a good place where the hack falls over. Thoughts?

**Comment by npomfret** [comment]
When the app is in the background will the OS immediately put it in a suspended state? If so, without the hack does the JS code get the opportunity to run at all?  I think it does get suspended but am not 100% sure of what the behaviour is when running from xCode... I do see this in the logs:

```
<Notice>: -CMSessionMgr- CMSession: Client myApp with pid '1321' is now Background Suspended. Background entitlement: YES
...
<Info>: 'myApp' task suspended: removing client
<Notice>: Client myApp disconnected
```

From my experiments it works in this state without the hack, but I quite don't understand why (maybe because it's not actually suspended?).  Given that processing the push notification is asynchronous, the `application:didReceiveRemoteNotification:fetchCompletionHandler` finishes without the _completionHandler_ being called, I would have thought that would result in a penalty (without the hack).  But so far, from my experiments it seems to work fine if you background the app and send it notifications.

The hack doesn't seem to affect the my app in a negative way when its backgrounded (but not terminated) from what I've seen so far.  I guess it's creating a background process that it doesn't need if the app is backgrounded but not suspended (given that the above seems to work) - so maybe yes: there's a process running that doesn't need to be.  BUT does this ever happen?  As far as I can see the OS suspends the app as soon as it's backgrounded.

I suppose an solution might be to start the background process in `RCTPushNotificationManager.handleRemoteNotificationReceived` and end it when the JS code calls the `finish` method.  This way there's always a background process running, regardless of state, that gets ended when the _completionHandler_ gets called.  My interpretation of the iOS docs is that starting another process is the _right_ thing to do (even when the app is in the foreground). Obviously my hack isn't the right way of doing it.

**Comment by JAStanton** [comment]
@npomfret were you able to verify the react JS was actually loading when you get a push notification and it's suspended?  (With your hack). I wasn't able to attach a logger in time to see my my app logs.

**Comment by npomfret** [comment]
I'm not sure I fully understand your question, but.. 

What I observe is that when backgrounding the app it appears as if the OS almost immediately puts the app into a _suspended_ state.  With or without the hack, when suspended, it seems to work and my JS code gets run when receiving a push notification (if it's got `content-available=1`).  I'm unsure how it works without the hack because that disagrees with the apple docs (as I've understood them), I think a background task is necessary.  Perhaps it will stop working after a while... needs more testing.

And from a terminated state, without the hack it doesn't work - no JS gets run.  But with the hack it does.

What do you think to starting and stopping a task to `RCTPushNotificationManager`?

**Comment by npomfret** [comment]
@JAStanton any more thoughts on getting this working?

**Comment by nevir** [comment]
Also, be aware that the OS can call `:didReceiveRemoteNotification:fetchCompletionHandler:` *twice* for notifications that display the notification UI:  Once when the notification is received (in the background), and again when the user taps the notification and the app is brought to the foreground.  You have to call the handler in both situations

**Comment by npomfret** [comment]
Not all notifications appear to the user.  This thread has been focusing on those that have `content-available=1` but no user facing content.  

I think we need to add a background task to RN.  Without it notifications stop working because the OS stops delivering them to the app.

**Comment by JAStanton** [comment]
But the notification calls the handler, so it does wake up the app, it just
shuts down for you immediately? My initial reaction was because there was a
weakref on the callback and UIKit just shutdown the app because it no
longer needed to do anything. But that shouldn't be the case. I'm at a
loss. I will be looking more into it next week but if this is the path I go
down I would make sure to cancel this background task when the app calls
back. Thats the only change I would do. But somethings not adding up
because I've never seen any other apps do this. Hopefully soon I can look
into this fully.

**Comment by npomfret** [comment]
Thanks for the reply.  Yes, I think that's all we need to do.  Start a background task and then stop it when the app calls the completion handler.

**Comment by JAStanton** [comment]
The issue I am having with this is that I don't know if the JS is actually booting up, I have a suspicion that it's not. Have you been able to get the app's JS to run and verify it ran after starting the app using the "Wait for executable to be launched" and sending it a "content-available: 1" push notification?

**Comment by npomfret** [comment]
If I understand your question correctly, yes I have.  

My app simply doesn't work without the _background process hack_ after the process has been stopped by the OS.  Without it, I see a bit of logging when the message is delivered to the OS but the JS app doesn't seem to get an opportunity to start.  

It's difficult (maybe impossible) to properly simulate, because getting the OS to terminate the app can't be done reliably.  This [page](https://medium.com/@milkservice/there-is-an-easier-way-in-scheme-settings-there-is-an-option-wait-for-executable-to-be-launched-b145d85d17e0#.vgpgjjv41) suggests a couple of way of achieving it.  Basically use Xcode to stop the app after its been started, or change the launch settings.

**Comment by npomfret** [comment]
@JAStanton I'm trying a less hacky way of dealing with this problem [here](https://gist.github.com/npomfret/7e33e9e88da1a4ae2bcf38a51e68f19d).  It also handles the issue of  a notification arriving and starting a background task while a background task is already running from a prior notification.  I'm still testing it...

**Comment by swl367** [comment]
I'm having the same issue where a push with "content-available: 1" is pretty much terminating my app after 30 seconds. All I'm doing is setting the badge icon from a backgrounded state using in-app code (react-native-push-notification), but I'm not sure why it would terminate my app after 30s.

Using the hacky fix, I'm no longer running into this issue.
