### ISSUE TITLE
Race condition in RCTBridge

### ISSUE THREAD

**Issue by artemyarulin** [facebook/react-native#1116]
1) `RCTBridge.setUp` is executing. On some moment module is created using `[[moduleClass alloc] init]`
2) `RCTReachability.m` subscribes to event in init method: `SCNetworkReachabilitySetCallback(_reachability, RCTReachabilityCallback, &context);`
3) `RCTBridge.setUp` continuing and calls `RCTLocalModulesConfig` 
4) `RCTReachabilityCallback` is called and executes `eventDispathed.sendDeviceEventWithName -> enqueueJSCall`
5) `enqueueJSCall` - crashes because there are no modules exists yet

**Comment by artemyarulin** [comment]
Here pull request which fixes this issue (actually I guess this is a real reason for #1114).

Now I'm thinking that it worth giving user a warning that his call is ignored because `RCTBridge` still initializing, what do you think?

**Comment by nicklockwood** [comment]
Cc: @tadeuzagallo, who's been working on a unified solution for these race conditions.

**Comment by tadeuzagallo** [comment]
Thanks @artemyarulin for raising that issue!

I had moved the `_loading` already, but after your comment I figured out a way so we never ignore any call, so we should it should be alright now.

The commit hasn't landed internally yet, but I'm working on it, shouldn't take long now.

**Comment by artemyarulin** [comment]
@tadeuzagallo Cool, thank you!

**Comment by nicklockwood** [comment]
Fixed in https://github.com/facebook/react-native/pull/1165
