### ISSUE TITLE
Debugger must be kept open in separate window to operate efficiently

### ISSUE THREAD

**Issue by DJSrA** [facebook/react-native#11175]
### Description

Debugger is painfully slow when opened in a browser window with other open tabs.

### Solution

If the Debugger is run in a separate background window, it has no speed issues. This really needs to get solved to not be dependent on a separate window.

### Additional Information

* React Native version: 0.38.0
* Operating System: MacOS - Sierra 10.12.1

**Comment by damusnet** [comment]
@facebook-github-bot duplicate #10559
