### ISSUE TITLE
ListView component not displaying all items

### ISSUE THREAD

**Issue by mykelaballe** [facebook/react-native#11173]
React Native: 0.32

Hi guys need help on this one. I've attached a screenshot with the UI, the array and the ListView code snippet. As you can see in the screenshot, there are items in the array that were not displayed in the ListView component. Appreciate all the help guys thanks!

![listview](https://cloud.githubusercontent.com/assets/22584900/20676569/1f6d2288-b5cb-11e6-9a5f-0d3334ca83b4.png)

**Comment by danieldms** [comment]
Hey mykelaballe, if you check https://facebook.github.io/react-native/docs/listview.html#pagesize the listview has a limit to show item row, can be that solve this problem.

**Comment by mykelaballe** [comment]
does this mean i can set the pagesize to the number of items to make it dynamc?

**Comment by danieldms** [comment]
Mykelaballe, how about the style?
Do you use seems like this?
Exemple:

 listview: {
    justifyContent: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap'
  },
  rowItem: {
    justifyContent: 'center'
  },

**Comment by damusnet** [comment]
@facebook-github-bot stack-overflow
