### ISSUE TITLE
Picker.Item doesn't support color property

### ISSUE THREAD

**Issue by Dolavs** [facebook/react-native#11170]
### Description

I tried to make a "color picker" for my IOS application. Each item is a name of a color and the text color are also the color itself. **Picker.Item** documentation explain to use **"color='blue'"** as a property:
`<Picker.Item label='blue' color='blue' value='blue' />`.
Unfortunately it doesn't work.
### Solution

Probably it doesn't implemented. Implement it can be the solution.

### Additional Information

* React Native version: 38.0
* Platform: IOS
* Operating System: MacOS

**Comment by janicduplessis** [comment]
Looks like it's not supported on iOS, only Android. We should at least update the doc to avoid confusion. It should also be relatively simple to implement. According to this SO post it should be possible to change the color on iOS too http://stackoverflow.com/questions/19232817/how-do-i-change-the-color-of-the-text-in-a-uipickerview-under-ios-7.

To do it we can pass the color prop here like we do on Android https://github.com/facebook/react-native/blob/master/Libraries/Components/Picker/PickerIOS.ios.js#L51 and use it here https://github.com/facebook/react-native/blob/master/React/Views/RCTPicker.m#L89

**Comment by JakeDawkins** [comment]
Is anyone actively working on this? I'd love to take a look at it.

**Comment by janicduplessis** [comment]
I don't think so, feel free to work on this and let me know if you need help with anything.

**Comment by joshyhargreaves** [comment]
@JakeDawkins 👍 . Good work :)
