### ISSUE TITLE
"No JSC registered" when starting Sampling Profiler

### ISSUE THREAD

**Issue by mdamien** [facebook/react-native#11171]
I tried to start the "Sampling Profiler". But when I start it, I get the "No JSC registered".

### Solution

I see that to register a Sampling Profiler, I need to use `registerHeapCapture`. Maybe that's left to a third-party library I need to include. In any case, if the solution is to implement a third-party heap capture, then that's what I'm gonna do.

EDIT: looks like that on iOS, I get a `JSC` in the perf monitor, but no way to start to Sampling Profiler
EDIT: looks like there's a android-jsc project, seems related ! 
https://github.com/facebook/android-jsc

### Additional Information

* React Native version: 0.37.0
* Platform: Android
* Operating System: Linux

**Comment by K-Leon** [comment]
Same for me...

**Comment by dustinosity** [comment]
Same problem here.

React Native version: 0.38.0
Platform: Android
Operating System: Mac OS X

**Comment by kosiakMD** [comment]
Mac OS X RN 0.36 - same

**Comment by MaFiaaaaAxD** [comment]
+1

React Native version: 0.40.0
Platform: Android
Operating System: Mac OS X

**Comment by brainbow91** [comment]
Same problem here.

React Native version: 0.42.0
Platform: Android
Operating System: Mac OS X

**Comment by MDDemirci** [comment]
Same problem here.

React Native version: 0.43.2
Platform: Android
Operating System: Mac OS X

**Comment by kotazi** [comment]
Same problem here.

React Native version: 0.43.2
Platform: Android
Operating System: Mac OS X

**Comment by kinop112365362** [comment]
Same problem here.

React Native version: 0.43.2
Platform: Android
Operating System: Mac OS X

**Comment by shahen94** [comment]
React Native version: 0.44
Platform: Android
Operating System: Mac OS X

**Comment by Alexandru-Cambose** [comment]
Same problem here.

React Native version: 0.47
Platform: Android
Operating System: Ubuntu 17.04

**Comment by modularity** [comment]
Same problem here.

React Native version: 0.47.1
Platform: Android
Operating System: Mac OS X

**Comment by OrDuan** [comment]
Same problem here.

React Native version: 0.47.1
Platform: Android
Operating System:  Ubuntu 16.04

**Comment by N1ghtly** [comment]
Same problem here.

React Native version: 0.48
Platform: Android
Operating System: Ubuntu 16.04

**Comment by maggialejandro** [comment]
Same problem here.

React Native version: 0.45.1
Platform: Android
Operating System: MacOS 10.12.6

**Comment by vladkolodka** [comment]
Same problem here.

React Native version: 0.47.0
Platform: Android
Operating System: Windows 10 1703

**Comment by haggholm** [comment]
Still persists in 0.49.3 and 0.50.4. Also happened for me when building with a custom JSC (https://github.com/SoftwareMansion/jsc-android-buildscripts/) with the profiler build flags enabled.

**Comment by john1jan** [comment]
any update on this issue?

**Comment by hramos** [comment]
Closing after a period of inactivity. Happy to reopen once more info is provided.

**Comment by luatnd** [comment]
+1
react-native@0.60.5
react@16.8.6
platform: Android
env MacOS
