### ISSUE TITLE
[DevMenu] won't show after cancel

### ISSUE THREAD

**Issue by fuchanglin** [facebook/react-native#11176]
### Description
 The dev menu will not show after the cancel.

### Reproduction
1. Shake the device
2. Click the Cancel
3. Shake the device again
4. The dev menu won't show
 
### Solution
In RCTDevMenu.m,
```
  if (_actionSheet || !_bridge || RCTRunningInAppExtension()) {
    return;
  }
```
Since it check _actionSheet everytime the dev menu is going to show, we need to release the previous _actionSheet instance in "Cacnel" action.
```
[_actionSheet addAction:[UIAlertAction actionWithTitle:@"Cancel" 
style:UIAlertActionStyleCancel handler:nil];
```
=>
```
[_actionSheet addAction:[UIAlertAction actionWithTitle:@"Cancel"
style:UIAlertActionStyleCancel  handler:^(__unused UIAlertAction * action) {
                                 _actionSheet = nil;
                           }];
```

### Additional Information

* React Native version: [0.38]
* Platform: [iOS]
* Operating System: [MacOS10.12]

**Comment by lacker** [comment]
That does sound like a bug. Are you interested in sending a pull request to fix this?

**Comment by fuchanglin** [comment]
it appears that this issue in already be fixed in current master.

**Comment by lacker** [comment]
Awesome
