### ISSUE TITLE
[Android] Network request failed when request response status is 304

### ISSUE THREAD

**Issue by brien-crean** [facebook/react-native#11185]
fetch is throwing `Network request failed`, when an API returns a 304 (Not Modified), on Android only. I am using fetch to poll an API for new real estate listings. This happens **every** time the API returns a 304.
If the fetch returns a 200 response it works as expected and logs the amount of new listings in my example below.
The exact same code works on iOS with no errors 
**Note: I am connecting to the API via its public IP. It is not running locally on my machine.**

**Fetch code**
```javascript
pollListings() {
  fetch(URL, {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json',
      'Accept' : 'application/json'
    }
  })
  .then(response => {
    if(response.status==200) {
      response.json().then(json => {
        console.log('Found '+json.length+' new listings')
      })
    } else if(response.status==304){
      console.log('Completed poll: no changes')
    }
  })
  .catch(error => {
    console.log(error)
  })
}

```

I listened to the `didReceiveNetworkResponse` event, which is emitted from Java native code from onResponseReceived() in ResponseUtil.java, using the DeviceEventEmitter in RN as below

```javascript
const nativeListener = DeviceEventEmitter.addListener('didReceiveNetworkResponse',
  (e)=>{
    console.log(e)
})
```
**Output**
```javascript
[
  //requestId
  0 : 15
  //response  
  1 : 304 
  // headers
  2 : {
        access-control-allow-credentials:"true"
        access-control-allow-headers:"Authorization"
        access-control-allow-methods:"POST,GET,PUT,DELETE,OPTIONS"
        access-control-allow-origin:"*"
        content-length:"29"
        content-type:"application/json; charset=UTF-8"
        date:"Tue, 29 Nov 2016 08:55:24 GMT"
        server:"cloudflare-nginx"
      }
  3 : "http://someapi/listings?filter=all&since=1480409715249"
]
```

It seems that React Native appears to be receiving the 304 response from the Native layer, but something is going wrong maybe in XMLHttpRequest.js ?

* React Native version: 0.38.0 (Tested and found to be an issue on 0.35.0 through 0.38.0)
* Platform: Android only
* Operating System: MacOS

**Comment by lacker** [comment]
Hmm, this sounds like a real problem. Can you stick a bunch of print statements in the code and figure out where the problem is, in XMLHttpRequest.js or elsewhere?

**Comment by r-bansal** [comment]
@brien-crean, @lacker - I am able to produce a 304 using curl/postman, however not via react-native (I receive 200s). Any ideas?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/android-network-request-failed-when-request-response-status-is-304
