### ISSUE TITLE
ENOENT: no such file or directory,

### ISSUE THREAD

**Issue by cheshuangchun** [facebook/react-native#11182]
We use GitHub Issues for bugs.

 ERROR  ENOENT: no such file or directory, lstat '/Users/csc/Desktop/ko/AwesomeProject/ios/build/ModuleCache/512LK817MVVS/modules.idx.lock'
{"errno":-2,"code":"ENOENT","syscall":"lstat","path":"/Users/csc/Desktop/ko/AwesomeProject/ios/build/ModuleCache/512LK817MVVS/modules.idx.lock"}
Error: ENOENT: no such file or directory, lstat '/Users/csc/Desktop/ko/AwesomeProject/ios/build/ModuleCache/512LK817MVVS/modules.idx.lock'

**Comment by rajkeshwar** [comment]
It fixed for me by running `rm -fr $TMPDIR/react-*`
