### ISSUE TITLE
PLEASE HELP : Error watching file for changes: EMFILE

### ISSUE THREAD

**Issue by nicolaselmir** [facebook/react-native#11193]
I tried everything on the web , I have the latest xcode , the latest watchman and siera.
Please help!

**Comment by hugheba** [comment]
Same position here, tried everything I could find.

Still getting..

```
2016-11-29 14:14 node[14211] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
{"code":"EMFILE","errno":"EMFILE","syscall":"Error watching file for changes:","filename":null}
Error: Error watching file for changes: EMFILE
    at exports._errnoException (util.js:1026:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1406:11)
 ERROR  Error watching file for changes: EMFILE
```


Mac OS 10.12.1
Node 7.2.0
package.json : ```
{
  "name": "test",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "15.4.1",
    "react-native": "0.38.0"
  },
  "jest": {
    "preset": "react-native"
  },
  "devDependencies": {
    "babel-jest": "17.0.2",
    "babel-preset-react-native": "1.9.0",
    "jest": "17.0.3",
    "react-test-renderer": "15.4.1"
  }
}
```

**Comment by mheimschild** [comment]
for me worked solution described in #10088

**Comment by hugheba** [comment]
@mheimschild  If you're referring to the ulimit, I've already tried that with no luck.

`% ulimit -n
1048576`

**Comment by lacker** [comment]
I would also try reinstalling watchman. The EMFILE is in general too many open files. http://stackoverflow.com/questions/32953838/react-native-error-error-watch-emfile might help too.
