### ISSUE TITLE
ToolbarAndroid Actions Disappear On Change With Input Focus

### ISSUE THREAD

**Issue by jaystramel** [facebook/react-native#11209]
### Description

The actions seem to disappear when they are updated if an input is focused.  Updating the actions seem to work as long as no inputs are focused.

This did not happen on version 0.29 but breaks on 0.38.  I think that there is a related crash on 0.37, but it's more difficult to recreate.

### Reproduction

https://rnplay.org/apps/jFEJew

### Solution

Unknown.

### Additional Information

* React Native version: 0.38
* Platform: Android
* Operating System: MacOS & Linux

**Comment by vonovak** [comment]
Not sure exactly why, but this works :D https://rnplay.org/apps/5TeqFg

have you tried not re-creating a new array every time, but change the array in-place?

**Comment by jaystramel** [comment]
I don't think so:  https://rnplay.org/apps/rEcEWw (unless I misunderstood what you meant).

**Comment by vonovak** [comment]
the link I attached does work for me, ie. the toolbar gets updated correctly. just by adding the `<Text/>`

**Comment by vonovak** [comment]
@DanielMSchmidt you were mentioned in the linked issues, so maybe you'd interested in this one since it provides a nicely isolated repro

**Comment by chenvan** [comment]
@jaystramel Do you find a solution?

**Comment by hirviid** [comment]
Had the same problem. Don't know why, but a hack like this seems to work:

```jsx
    <View style={style.root}>
        <ToolbarAndroid
          navIcon={leftItem && leftItem.icon}
          onIconClicked={leftItem && leftItem.onPress}
          title={title}
          titleColor={textColor}
          actions={actions}
          onActionSelected={this.handleActionSelected}
          overflowIcon={require('assets/mobile/more_vert.png')}
          style={style.toolbar}
        >
            {children}
        </ToolbarAndroid>
        {/* Added this Text component ↓ */}
        <Text style={{ height: 0, opacity: 0 }}>
            {JSON.stringify(actions)}
        </Text>
    </View>
```

**Comment by jaystramel** [comment]
@chenvan No.  I wrote a custom component for the two places we need this.  (Sorry the delay, never saw the notification.)

**Comment by chenvan** [comment]
@jaystramel Never mind. I just write a component which is similar to ToolbarAndroid to avoid this problem.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/toolbarandroid-actions-disappear-on-change-with-input-focus
