### ISSUE TITLE
cb() never called

### ISSUE THREAD

**Issue by yuhengZhu** [facebook/react-native#11207]
### Description

when I install react-native@xxx by npm, it does not work and shows me the information of  'nam ERR! cb() never called!'.  I had clean my nam cache , but it does not work. In addition , I can install Other project, for example react except react-native.

### Additional Information

* React Native version: many 
* Platform: all
* Operating System:  MacOS

**Comment by xuyingbokanwensi** [comment]
same ERR here ,
i do after that reinstall nodejs the error dismiss.

**Comment by ytqiu** [comment]
+1
