### ISSUE TITLE
Error when update state in modal

### ISSUE THREAD

**Issue by rodolfobarretoweb** [facebook/react-native#11202]
When I use state to update my form fields in modal component, the application reload (request to bundle) after type some text (email for example). 

PS: I test in dev mode using genny motion, In real device does not happen.

react-native version: 0.37.0
testing in android 5.0.0

**Comment by rodolfobarretoweb** [comment]
The problem happen when I press RR twice in DEV mode, RR is a shurtcut of the react native to bundle files [(](https://facebook.github.io/react-native/docs/debugging.html)

Coincidentally in my tests i type my email (rodolfobarretoweb@gmail.com)

**Comment by damusnet** [comment]
@facebook-github-bot expected
