### ISSUE TITLE
Can you please publish 0.39.0-stable version to npm as 0.38.0-stable is having code issue in error-guard.js

### ISSUE THREAD

**Issue by dilipkumar2k6** [facebook/react-native#11203]
### 0.38.0-stable is having code issue in error-guard.js which I see has been fixed in 0.39.0-stable however 0.39.0 version is not yet pushed to npm

The `const` use in the following file has been fixed in `0.39.0` version. Earlier I was using `0.35.0` version however after upgrade to `0.38.0` I started getting packaging error due to the use of `const`. 
https://github.com/facebook/react-native/blob/0.38-stable/packager/react-packager/src/Resolver/polyfills/error-guard.js

I even tried to installed `0.39.0` from github directly but its failing due to incompatible version of xcode project generated using `0.38.0`.

### Reproduction

I don't see `_inGuard read only` error in sample project created using `react-native` however I do get when I run my application project. I don't think I can share exact steps to re-produce excpet I figure out the problem which has been already resolved in `0.39.0`
### Solution
Publish `0.39.0-stable` version to npm

### Additional Information
* Operating System: MacOS

**Comment by Ehesp** [comment]
For the time being, why not just install the module via the branch directly?

**Comment by dilipkumar2k6** [comment]
I used `0.39.0-rc.0` for now. Will try to use github branch directly.
