### ISSUE TITLE
React Native Exists without warning

### ISSUE THREAD

**Issue by anassaeed72** [facebook/react-native#11205]
While running a react native project on android ( Ubuntu 16.06) it exists without warning

The output of the command react-native run-android( the server is already running using the start command).

JS server already running.
Running /home/user/Android/Sdk/platform-tools/adb -s emulator-5554 reverse tcp:8081 tcp:8081
adb server version (32) doesn't match this client (36); killing...
* daemon started successfully *
Building and installing the app on the device (cd android && ./gradlew installDebug...
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment.
Go to https://facebook.github.io/react-native/docs/getting-started.html
and check the Android tab for setup instructions.

**Comment by damusnet** [comment]
@facebook-github-bot stack-overflow
