### ISSUE TITLE
Android: The Thread leakage of Fresco in the react native

### ISSUE THREAD

**Issue by NextApp** [facebook/react-native#11216]
When I create the reactInstanceManager ,and the fresco module will be loaded. the fresco will create many threads and can't be cancelled by invoke the method destroy of reactInstanceManager.
 if i did it in the wrong way ?

**Comment by NextApp** [comment]
platform:Android 
react-native-version:0.27.0

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/android-the-thread-leakage-of-fresco-in-the-react-native
