### ISSUE TITLE
support i18n

### ISSUE THREAD

**Issue by metacortex** [facebook/react-native#1121]
How to do i18n/localize in react-native?

**Comment by brentvatne** [comment]
You can use the same approach that you would use in a browser :smile: - for example, http://blog.arkency.com/2015/03/use-your-gettext-translations-in-your-react-components/

**Comment by metacortex** [comment]
This is cool :-)
https://github.com/stefalda/ReactNativeLocalization

**Comment by brentvatne** [comment]
Great :smile:

**Comment by phlegx** [comment]
This is good: https://github.com/AlexanderZaytsev/react-native-i18n
