### ISSUE TITLE
'Couldn't follow symbolic link' when testing release build for Android

### ISSUE THREAD

**Issue by Naoto-Ida** [facebook/react-native#11212]
### Description

When following the [tutorials](https://facebook.github.io/react-native/docs/signed-apk-android.html#generating-the-release-apk) for generating the release APK for Android, I get the error described in **Reproduction** and cannot progress with build.

I don't recall modifying the `node_modules` folder manually, so not sure what happened to the symbolic link.

I've seen the same issue [here](https://github.com/facebook/react-native/issues/2743), but just wanted to point this out since my version (`0.34.1`) was released in September and **its unclear in the old issue as to why its safe to remove these symbolic links**.

Following the steps in the issue addressed above allowed me to build, but `/.bin/repeating` was also missing.

### Reproduction

1. Follow steps described in the documentation above up until creating the release build.
2. Run `cd android && ./gradlew assembleRelease` in project root folder.

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not list contents of '~/myapp/node_modules/.bin/detect-indent'. Couldn't follow symbolic link.

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED
```

### Additional Information

* React Native version: v0.34.1
* Platform: Android
* Operating System: MacOS

**Comment by damusnet** [comment]
Did you try removing your `node_modules` folder and installing dependencies again? What is the content of your package.json?

**Comment by Naoto-Ida** [comment]
Closing this as removing `node_modules/.bin/`, in addition to a few other package directories solved the issue.

**Comment by jqn** [comment]
Removing node_modules/.bin/ worked for me too.

**Comment by ghuh** [comment]
Issue still exists on RN v0.42.0.  Fixed by removing `node_modules/.bin/`

**Comment by JansenZ** [comment]
Removing `node_modules/.bin/` worked

**Comment by mihaisampaleanu** [comment]
emoving node_modules/.bin/ worked for me to

**Comment by cinder92** [comment]
its not working for me  :/

**Comment by johngoren** [comment]
I removed .bin and it's still happening. RN 0.47.1.

**Comment by lappalj4** [comment]
Removing `.bin` did not work, but `rm -rf node_modules && npm install` did the trick

**Comment by mtebele** [comment]
This worked for me: to delete the broken test-driver-link as follows

`unlink node_modules/react-native/third-party/glog-0.3.4/test-driver`

**Comment by cinder92** [comment]
@lappalj4  this make my day <3

**Comment by 337240552** [comment]
@lappalj4 works for me， thanks

**Comment by WhoJave** [comment]
@lappalj4  works for me, but several times later ,It's still the problem, I have to do  `rm -rf node_modules && npm install`  often

**Comment by mtx62** [comment]
I don't why but for some reason `yarn install` worked!

**Comment by rajat-np** [comment]
unlinking packages maybe not the solution for everyone , but 
```
rm -rf node_modules && npm install
```
is the way around.

**Comment by c-Brooks** [comment]
To proactively prevent this issue (if you're not ready to upgrade RN versions), you can pass the `--no-bin-links` flag to `npm install` or `yarn`.

From [the docs](https://docs.npmjs.com/cli/install):
> The --no-bin-links argument will prevent npm from creating symlinks for any binaries the package might contain.

**Comment by TunvirRahman** [comment]
have tried delete `node_modules` and then `npm install`.
This worked for me.
