### ISSUE TITLE
Listview in rapid scrolling when there will be problems

### ISSUE THREAD

**Issue by WaterEye0o** [facebook/react-native#11213]
### Description

Listview in rapid scrolling when there will be problems。

When each row has many sub-components. first of all you quickly scroll to the bottom of the listview, and then scroll to the middle you will find the view like this:

![b09252e4-3b29-4217-86a3-4cbe500dcbc1](https://cloud.githubusercontent.com/assets/15081830/20744325/4a0665c6-b716-11e6-8607-7f0d9aca7f07.png)

### Additional Information

* React Native version: 0.35
* Platform: Android
* Operating System: MacOS

**Comment by damusnet** [comment]
Performances issues with <ListView /> are well known and being worked on as possible. There is also [an issue on Product Pains](https://productpains.com/post/react-native/fix-various-listview-issues) you can follow and upvote. There are also alternative <ListView /> implementations you can look for that might better suit your needs.

**Comment by damusnet** [comment]
@facebook-github-bot answered
