### ISSUE TITLE
Cannot find entry file index.android.js in any of the roots

### ISSUE THREAD

**Issue by fanjunzhi** [facebook/react-native#11217]
`
{ 
"message": "Cannot find entry file index.android.js in any of the roots: [\"path/node_modules/.npminstall/react-native/0.26.3/react-native\"]",
"name": "NotFoundError",
"type": "NotFoundError",
"status": 404,
"errors": [
{}
]
}
`
browse http://localhost:8081/index.android.bundle,thanks

**Comment by lacker** [comment]
I can't repro this problem. If you just follow the "hello world" instructions from scratch on a new app does it work for you?

**Comment by rocxiay** [comment]
Not sure if this can help you.
http://stackoverflow.com/questions/29388704/react-cannot-find-entry-file-in-any-of-the-roots

**Comment by fanjunzhi** [comment]
"hello world" is work, thanks, i close it.
