### ISSUE TITLE
Packager not working on win10 

### ISSUE THREAD

**Issue by yeso126** [facebook/react-native#11211]
### Description
React-native packager not working on windows, I get the following logs:

[Hot Module Replacement] Server listening on /hot

```
React packager ready.

[2016-11-29 23:10:44] <START> Initializing Packager
[2016-11-29 23:10:44] <START> Building in-memory fs for JavaScript
[2016-11-29 23:10:44] <END>   Building in-memory fs for JavaScript (84ms)
[2016-11-29 23:10:44] <START> Building Haste Map
[2016-11-29 23:10:44] <END>   Building Haste Map (65ms)
[2016-11-29 23:10:44] <END>   Initializing Packager (1
```

This is a clean windows 10 installation, I just installed node, and react-native cli, the first time I run the app the packager works properly, this happens when I run react-native run-android or react-native start  a second time after having run react-native run-android the first time. 

* React Native version: 0.38.0
* Platform: Android 
* Operating System: Windows

**Comment by lacker** [comment]
So what exactly is not working, what sort of error or failure do you get?

**Comment by greatbsky** [comment]
I also got this on win7, there isn't errors. just hang at Initializing Packager...
I close an application named 'wi-fi.exe', 'react-native run-android' again then surprising, it's Requesting bundle....It's started!

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/packager-not-working-on-win10
