### ISSUE TITLE
Navigator should not care about initialRoute type

### ISSUE THREAD

**Issue by ColCh** [facebook/react-native#11219]
We have `20` (!!) screens in our app, and each screen has around `1-5` route transitions. And because of `imports`, we have a lot of cyclic dependencies.

And cyclic dependencies around screen Components brings a lot of bugs, because route sudently becomes `undefined`. Our solution is to abstract out routes from Components.

And simpliest solution is to use `string` type for routes, and custom translator `route-id <--> Component`

We use it, it works very well. But `<App />` throws proptype validation warning in `Navigator`.

```
ExceptionsManager.js:71Warning: Failed prop type: Invalid prop `initialRoute` of type `string` supplied to `Navigator`, expected `object`.
    in Navigator (created by App)
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
```

`initialRoute`... but it just proxies it to `renderScene`! We just wanted to use a string for routes - like

```
<Navigator
          initialRoute={'word-cards'}
          renderScene={renderScreen}
          sceneStyle={styles.scene}
        />
```

Our `renderScreen` is capable of mapping between `route-id <--> Component` translation with hashmap.

I've read source code of Navigator and provide proofs, that it __not uses__ `initialRoute` structure:
https://github.com/facebook/react-native/blob/8b199a7fd033f2a50edb60f0aaa0ad609f168d4b/Libraries/CustomComponents/Navigator/Navigator.js#L412...L436
I will copy code to this issue:
```js
    var routeStack = this.props.initialRouteStack || [this.props.initialRoute];
    invariant(
      routeStack.length >= 1,
      'Navigator requires props.initialRoute or props.initialRouteStack.'
    );
    var initialRouteIndex = routeStack.length - 1;
    if (this.props.initialRoute) {
      initialRouteIndex = routeStack.indexOf(this.props.initialRoute);
      invariant(
        initialRouteIndex !== -1,
        'initialRoute is not in initialRouteStack.'
      );
    }
    return {
      sceneConfigStack: routeStack.map(
        (route) => this.props.configureScene(route, routeStack)
      ),
      routeStack,
      presentedIndex: initialRouteIndex,
      transitionFromIndex: null,
      activeGesture: null,
      pendingGestureProgress: null,
      transitionQueue: [],
    };
  },
```

So, it just want's to:

* `props.initialRouteStack` to be an array
* and route stack should have values, which can be found by IndexOf: `initialRouteIndex = routeStack.indexOf(this.props.initialRoute);`

Really! It don't refers to route type, leave this type at consumers sake please.

**Comment by lacker** [comment]
I think what you are saying is that overall it would be a better design if Navigator worked differently. We agree and are working on a new recommended way to handle navigation. In the meantime you might want to look at ExNavigation. I am going to close this issue since it is a feature request rather than a bug, but I do agree that this is a good feature & it is on our roadmap to improve this.
