### ISSUE TITLE
ListView does not recalculate number of visible rows after orientation change

### ISSUE THREAD

**Issue by Mtnt** [facebook/react-native#11218]
### Description

I have a ListView with a header, several rows and separators.
My iPad is on landscape orientation at begin:

- Scroll to the bottom of the list
- Rotate the device to portrait orientation

what expect:
- a last row is at the bottom of the screen

what actualy is:
- the ListView do fill the screen
- but the last row is not at the bottom
- http://take.ms/6YV6Q

### Additional Information

* React Native version: 0.36.0
* Platform: iOS simulator (10.1), iPad Retina
* Operating System: MacOS

Маy be it relates with #10810

**Comment by lacker** [comment]
Can you provide a rnplay.org repro of this bug?

**Comment by Mtnt** [comment]
At the rnplay.org you could not rotate a "device". I made a public repo https://github.com/Mtnt/sample - just clone it, run it on landscape, scroll to bottom of the list, and rotate again

**Comment by mrpp01** [comment]
This also happens on iPhone. I was able to reproduce it. 
<img width="459" alt="screen shot 2016-12-04 at 4 53 28 pm" src="https://cloud.githubusercontent.com/assets/8869773/20869528/354af884-ba42-11e6-8d93-4aee31e84776.png">

**Comment by mrpp01** [comment]
I figure out the issue. Look at the first picture, the top row is row 7. When the view changes to landscape, the first row is still row 7 (pic 2). That means react-native layout visible row from the top.
<img width="423" alt="list bug 1" src="https://cloud.githubusercontent.com/assets/8869773/22832773/57f881a6-ef7d-11e6-8881-42c64f193945.png">
<img width="664" alt="list bug 2" src="https://cloud.githubusercontent.com/assets/8869773/22832774/57f82b5c-ef7d-11e6-8ea6-dbdee415752c.png">

Now when the list is at the bottom, and in landscape mode, the top row is row 26 (pic 3). When the phone change orientation, RN does not seem to recalculate the number of rows that should be on display. Thus, there are not enough rows to fill the entire view (pic 4)

<img width="664" alt="list bug 3" src="https://cloud.githubusercontent.com/assets/8869773/22833019/4fe99bb6-ef7e-11e6-8866-94545aea79bc.png">
<img width="423" alt="list bug 4" src="https://cloud.githubusercontent.com/assets/8869773/22833018/4fe84a90-ef7e-11e6-950d-c70b752496ea.png">

**Comment by lacker** [comment]
Oh, awesome. I updated the title a bit to make this more clear. Would you be interested in sending a PR to fix this?

**Comment by mrpp01** [comment]
I'm looking into it. I will send a PR soon.

**Comment by hramos** [comment]
Closing as ListView is deprecated in 0.43. Use FlatList.
