### ISSUE TITLE
Tutorial to install the cli on windows 10

### ISSUE THREAD

**Issue by lednhatkhanh** [facebook/react-native#11220]
I couldn't find any tutorial on the getting started page on how to install react native cli on windows 10.

**Comment by lacker** [comment]
Hmm this does appear to be a bug.

to repro:
https://facebook.github.io/react-native/docs/getting-started.html
click "windows" + "android"

It says "Node.js comes with npm, which lets you install the React Native command line interface." but then doesn't give you any examples. Does it work to just run `npm install -g react-native-cli` ?
