### ISSUE TITLE
react-native/docs/Performance.md > Development mode (dev=true) > dev=false?

### ISSUE THREAD

**Issue by julesmoretti** [facebook/react-native#11227]
Could you please include methods in your docs on how to turn off dev mode to test production flow for android ideally please?

Thank you.

**Comment by lacker** [comment]
Would you like to send a pull request improving these docs?

**Comment by julesmoretti** [comment]
@lacker - if I knew how to achieve the above (meaning which file or terminal command to run or alter) I would gladly update the docs

**Comment by charpeni** [comment]
@julesmoretti Thank you, you can find these documentation into the [Contributing guidelines](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md).

Furthermore, on each documentation page you can find a `You can edit the content above on GitHub and send us a pull request!` on the bottom which leads you to the right file.

**Comment by charpeni** [comment]
@facebook-github-bot label Documentation

**Comment by julesmoretti** [comment]
@charpeni - sorry for the confusion, I meant to ask, how do you turn off dev mode?

**Comment by damusnet** [comment]
@julesmoretti your best bet is to follow this guide: https://facebook.github.io/react-native/docs/signed-apk-android.html#testing-the-release-build-of-your-app

If you just want to test performance/speed/animations of your debug build, you can turn off "JS Dev Mode" from the "Dev Settings" (Android only) after you shake your device. There are other helpful options there too.

As to "how to turn __dev__ mode on/off for various releases arbitrarily", I too would love to know!

**Comment by hramos** [comment]
This will be taken care of in an upcoming PR.
