### ISSUE TITLE
react-native bundle --minify throws an error on new projects

### ISSUE THREAD

**Issue by slooker** [facebook/react-native#1123]
I've created a new project like so:

    react-native init TestProject

Once the project is created, I try to bundle it like so:

    react-native bundle --minify

This throws this error:

> 10ddb1e9b7c1:TestProject slooker$ react-native bundle --minify
> Building package...

> /Users/slooker/Downloads/TestProject/node_modules/react-native/node_modules/bluebird/js/main/promise.js:626
>            throw e;
>                  ^
> Error: EMFILE, open '/Users/slooker/Downloads/TestProject/node_modules/react-native/node_modules/react-tools/src/browser/ui/dom/ViewportMetrics.js'

**Comment by brentvatne** [comment]
@slooker - It seems like in #1096 this was fixed by installing node 0.12.2, could you try that and let me know if it works?

**Comment by slooker** [comment]
Woops.  You are correct.  That fixes the problem.  Sorry for not checking the old issues first.

**Comment by brentvatne** [comment]
Sure :smile: glad it was resolved
