### ISSUE TITLE
Fetch API headers not sent when end point redirects with HTTP 301

### ISSUE THREAD

**Issue by yonkshi** [facebook/react-native#11236]
### Description
When making requests with custom headers (such as `Authorization`), if the end point returns HTTP 302 FOUND, the fetch API will proceed to forward the request to a new URL however, the custom headers will not sent to the redirected URL. 
### Reproduction

1. Make a request to any REST API that requires custom header with HTTP 302 response header
2. Inspect the traffic
3. First request includes custom header
4. Forwarded request does not include custom header

### Solution

A. Include header in redirected requests
B. Add ability to intercept redirect responses

### Additional Information

* React Native version: 0.36
* Platform: Both
* Operating System: MacOS

**Comment by Jyrno42** [comment]
We also observed that this issue only occurs in IOS (android works).

**Comment by epzee** [comment]
We're experiencing the same issue on both platforms (using RN `0.42.3`)

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/fetch-api-headers-not-sent-when-end-point-redirects-with-http-301

**Comment by darkkase** [comment]
this issue is not fixed (2017-oct),  but if you know this, you only fix your url for not redirect 301 or 302  :<     i lose  some days wiht this bug.

**Comment by w-** [comment]
This issue is not fixed still.
I definitely lost a bunch of days because of this bug. Maddening because it works on android just not on ios.
