### ISSUE TITLE
File upload doesn't work on webview

### ISSUE THREAD

**Issue by BogdanHossu** [facebook/react-native#11230]
### Description

When I am pressing a input file button inside the webview, nothing happens.
I am trying somehow to fix the core webview because I am using a module on top of this webview but also that one has the same problem.

### Additional Information

* React Native version: 0.34
* Platform: Android
* Operating System: MacOS

**Comment by lacker** [comment]
Can you provide a sample app like a rnplay.org link that reproduces this? Especially if there is some error from the webview that would be helpful to know.

**Comment by BogdanHossu** [comment]
I have made a small example here https://rnplay.org/apps/JFUPjw so if you press choose file nothing will happen. I am expecting a file selector from the local files. And the module/package I am using for my webview is this https://github.com/alinz/react-native-webview-bridge.

**Comment by lacker** [comment]
Does this work if you just make a regular iOS app and use that WebView? It is not clear to me that regular web pages are supposed to get file-upload-request permissions inside mobile apps.

**Comment by BogdanHossu** [comment]
Yes, this does work in iOS app.

**Comment by hey99xx** [comment]
For Android; is it possible you need a permission to read files from the system? Or there might be a need for a native code to handle this. Reading http://stackoverflow.com/questions/24470932/html-file-upload-doesnt-show-gallery-on-android and https://code.google.com/p/android/issues/detail?id=62220 I'm not sure if the default WebView client supports this out of the box.

**Comment by the-ant** [comment]
this two works:

https://github.com/dongyaQin/react-native-webview-file-upload

https://github.com/lucasferreira/react-native-webview-android

**Comment by nhayfield** [comment]
@the-ant those might work but they don't have all the new onMessage functionality and are outdated

**Comment by the-ant** [comment]
@nhayfield At last, I decided to use the [crosswalk webview](https://github.com/jordansexton/react-native-webview-crosswalk)

**Comment by BogdanHossu** [comment]
In the end I used the code from [this repo](https://github.com/martinarroyo/react-native-webview-file-upload/). Where I have created my own webview so also the onMessage functionality is there and the file upload.

**Comment by nhayfield** [comment]
@the-ant  yeah i been looking at crosswalk but its still not fully functional for what i need yet. might have to put in some Pull Requests on it

**Comment by Oblongmana** [comment]
Over the weekend I needed this functionality on Android for a deadline, so I reworked one of the above repos into a library that can be installed into an existing project using the usual process (`npm install` plus manual linking) - https://github.com/Oblongmana/react-native-webview-file-upload-android. 

It still has the limitation of the original repo that it only works with image uploads from the gallery - but PRs to add other input handling are welcomed, and should be _relatively_ simple, the codebase has been stripped down significantly.

For anyone struggling with iOS, you only need to add the `NSPhotoLibraryUsageDescription` key and a description of why you need Photo Library access into your `info.plist`

**Comment by farazs** [comment]
See my PR for this on Android: https://github.com/facebook/react-native/pull/12807

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/file-upload-doesnt-work-on-webview

**Comment by farazs** [comment]
Not sure this should be closed. There is a working PR to fix it, that just needs to be reviewed and merged.

**Comment by hramos** [comment]
I'll comment on the PR as well, but my impression here is that WebView is one of those components that probably should be split out of core and provided as a separate package.

**Comment by negati-ve** [comment]
*bump* 
any update on this?
will react native support file upload from web view by default?

**Comment by SaKKo** [comment]
Is this issue resolved? I'm still having the same problem.

**Comment by hushicai** [comment]
I meet the same issue too...

**Comment by hushicai** [comment]
I make a sample project [here](https://github.com/hushicai/ReactNativeAndroidWebView), based on `react-native-webview-android `, but I  do not make a custom WebView, just extends the ReactWebViewComponent. Hope someone benefits from it.

**Comment by ysweid** [comment]
This is not fixed yet.

**Comment by alexstophel** [comment]
@hramos Can you provide any further insight into why this should be a separate package? Your argument on linked the PR seems to be that it's because it doesn't impact Facebook's internal use cases, but doesn't it seem odd to require a package to add functionality to Android that exists on iOS? It's likely that any such package would quickly become outdated and unmaintained to add insult to injury.

I would imagine that most people use it with the hopes of reducing device specific code and this separation seems to encourage device specific code.

**Comment by eugene-belkovich** [comment]
I'm also still having the same problem.

**Comment by sinanargun** [comment]
I'm having the same problem too. Anyone solved the problem?

**Comment by Lxxyx** [comment]
Same problem.File upload is an basic operation. This should add to the feature.

**Comment by hfqf** [comment]
m2 ,Help!

**Comment by tanviag** [comment]
I am facing this issue in iOS. Not tested in android.

**Comment by anhtukhtn** [comment]
Is the problem solved?. It's very basic operation.
Please help.

**Comment by fuxianwei** [comment]
the same issue too

**Comment by EguchiRyo** [comment]
Still happen

**Comment by 1uokun** [comment]
+1

**Comment by GabrielDuarteJr** [comment]
+1

**Comment by dlehdanakf** [comment]
+1

**Comment by farazs** [comment]
I have a PR that fixes this https://github.com/facebook/react-native/pull/12807 but it doesn't look like it's ever going to get merged because the facebook team would like webview moved out of the core repo.

You can still use the code from the PR in a forked react-native if you need this functionality.

**Comment by HosanaUFRRJ2014** [comment]
When will React Native Team make this funcionality available in the core repo? We need to upload files through WebView!!!!!!!! It's a shame it's not working yet. I'm very disappointed, once I'm spending a lot of time trying to fix what you should've fixed more than a year ago. 👎

**Comment by 1uokun** [comment]
Please be grateful@HosanaUFRRJ2014

**Comment by yasicmd** [comment]
any updates?

**Comment by ManvendraFlipkart** [comment]
I haven't got any solution from this conversation yet! Tried almost everything.
Anyone has any working solution?
Thanks in advance!

**Comment by ManvendraFlipkart** [comment]
Okay one solution finally worked for me :)
If you are using RN version 0.50+ then simple follow the instructions in the below link:
https://github.com/andreipfeiffer/react-native-webview-android-file-upload

Or else you will have to upgrade your RN version first (which turned out to be a tedious task for us)

Hope this helps!

**Comment by vitorreis** [comment]
+1 on this feature/bugfix

**Comment by viv3kk** [comment]
+1 for this feature as this is very native feature which should be included.
