### ISSUE TITLE
NativeAnimatedModule.addAnimatedEventToView is not a function

### ISSUE THREAD

**Issue by mxmtsk** [facebook/react-native#11247]
I tried to implement [the following](https://rnplay.org/apps/vWGQNg) example into my app but I'm getting the error on iOS:

NativeAnimatedModule.addAnimatedEventToView is not a function

as well as

NativeAnimatedModule.removeAnimatedEventFromView is not a function(…)

Did I miss something?

**Comment by janicduplessis** [comment]
What version or RN are you using? Also have you added the `RCTAnimation` native module? (http://facebook.github.io/react-native/docs/linking-libraries-ios.html#manual-linking)

**Comment by eshwartm** [comment]
Same issue. Probably old but I am using this in a react native project which has version `0.37.0`. And yes, I have added `RCTAnimation`.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/nativeanimatedmoduleaddanimatedeventtoview-is-not-a-function

**Comment by IrinaCodixis** [comment]
@eshwartm , did you manage to solve this issue? I am on the same version of react native and experiencing exactly the same error.

**Comment by eshwartm** [comment]
@IrinaCodixis nope. I don't quite remember what I did. Steps to reproduce would be better.

**Comment by IrinaCodixis** [comment]
@eshwartm I just have a project on react native 0.37.0 and I am trying to add react-native-scrollable-tab-view (https://github.com/skv-headless/react-native-scrollable-tab-view) to the project. Works good on Android, breaks on iOS with errors NativeAnimatedModule.addAnimatedEventToView is not a function AND NativeAnimatedModule.removeAnimatedEventFromView is not a function
