### ISSUE TITLE
ListView not updating. Only updates when triggering HOT reload

### ISSUE THREAD

**Issue by mykelaballe** [facebook/react-native#11242]
RN: 0.32

hi guys need help. The ListView is inside a Modal and the data are fetched from API. The items in my ListView has an onPress, so when you click on an item, the icon beside it will change. But in my case, it doesnt update the icon unless i trigger a hot reload. I have other ListViews not inside a Modal and are fetching data from API and they're working fine using the same strategy. And also a ListView inside a Modal but not fetching data from API, also working fine. Only ListView inside a Modal and are fetching data from API that is not working. It will only update once i trigger a HOT reload. Its really weird, been working for this on for almost a day already. Really need help guys :(

![listview_](https://cloud.githubusercontent.com/assets/22584900/20790108/ebb20fa2-b7f1-11e6-958d-b613ce6adc61.png)

**Comment by damusnet** [comment]
@facebook-github-bot stack-overflow

**Comment by damusnet** [comment]
Also, it's impossible to debug with only partial code. Can't see a `<Modal />` here, or where `getGuardians` is being called.

**Comment by mykelaballe** [comment]
already posted it in stackoverflow but still no response. if anyone is okay to have skype with me ill show you my code and the emulator to reproduce the issue. really desperate here

**Comment by damusnet** [comment]
I can take a look on [SO](http://stackoverflow.com/questions/40907989/listview-not-re-rendering-items). Just left a comment for you to provide more code.

**Comment by mykelaballe** [comment]
oh okay2 tnx a lot bro. been working on this for 2 days already. ill send you the code. i temporarily put it in one file
