### ISSUE TITLE
NavigationExperimental - New title renders before animation is complete

### ISSUE THREAD

**Issue by robcalcroft** [facebook/react-native#11244]
When using the `NavigationExperimental` component and navigating to a new component I see that the title component for the new route renders before the slide animation is complete and so the title component changes instantly then the identical title is then animated into place. Annoyingly I can't get an rnplay to work, but this should give you an idea of the code I'm using https://rnplay.org/apps/r0JCzg. http://sendvid.com/ioqxzrwy should show a video of this issue as well.

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
