### ISSUE TITLE
NavigationExperimental - Swipe from left gesture to go back doesn't work

### ISSUE THREAD

**Issue by robcalcroft** [facebook/react-native#11245]
When swiping back from the left to go back a scene, the scene animation happens but doesn't stick, when I let go it just falls back into place and the current views stays. Is there a prop to enable gesture swiping to go back?

**Comment by rmevans9** [comment]
Do you have the `onNavigateBack` prop on the navigator set?

**Comment by robcalcroft** [comment]
I do, it currently does:
```
if (this.props.navigation.index === 0) {
      return false;
    }
    this.props.popRoute();
    return true;
```

**Comment by rmevans9** [comment]
Might be a dumb few questions but just to cover the bases:

1. Are you sure this call is being made and not failing at some point (eg. does popRoute exist on props for sure?)
2. Does popRoute work in other places?

**Comment by robcalcroft** [comment]
`popRoute` works fine everywhere else and it's being called when the user clicks the back button in the top left. But the gesture doesn't seem to trigger any of the `popRoute` code I have.

**Comment by rmevans9** [comment]
Can you attach a debugger and put a breakpoint at the start of the `handleBackAction` function and ensure that the code is hitting and executing correctly?

**Comment by robcalcroft** [comment]
Yep it's hitting it fine. Where does the gesture swipe event attach to? It seems like the gesture isn't attached to my `handleBackAction` prop thats passed to all components

**Comment by rmevans9** [comment]
Can you show the code around the `NavigationCardStack`?

**Comment by robcalcroft** [comment]
```
<CardStack
        style={{ flex: 10 }}
        navigationState={this.props.navigation}
        onNavigate={this.handleNavigate}
        renderScene={this.renderScene}
        renderHeader={isRouteFullScreen(routes[routes.length - 1]) ? null : this.renderHeader}
      />
```

**Comment by robcalcroft** [comment]
thats the JSX, I don't know if that's what you were looking for?

**Comment by rmevans9** [comment]
```
<CardStack
        style={{ flex: 10 }}
        navigationState={this.props.navigation}
        onNavigateBack={this.handleBackAction}
        onNavigate={this.handleNavigate}
        renderScene={this.renderScene}
        renderHeader={isRouteFullScreen(routes[routes.length - 1]) ? null : this.renderHeader}
      />
```

You must add the `onNavigateBack` to the Card Stack

**Comment by robcalcroft** [comment]
That sorted it! Thanks for your help 😄
