### ISSUE TITLE
<Image> component loads image from absolute path in iOS but not Android

### ISSUE THREAD

**Issue by pedramsaleh** [facebook/react-native#11256]
--- Please use this template, and delete everything above this line before submitting your issue --- 

### Description

Pass the image uri as an absolute path string (e.g. /storage/emulated/0/app/image.jpg) to <Image> component to display an image. The code works on iOS and the image displays, but it does not work on the same code base on Android.

### Reproduction

render() {
    const {height, width} = Dimensions.get('window');
    return (
        <View style={styles.container}>
          <Image
            style={{
              height:height,
              width:width,
              position: "relative"
            }}
            source={{uri: "/storage/emulated/0/app/image.jpg"}
            resizeMode="cover"
          >
          </Image>
        </View>
    );
}

### Solution

It's expected that this will work on Android like it does on iOS. 

### Additional Information

* React Native version: 0.30.0
* Platform: Android
* Operating System: MacOS

**Comment by pedramsaleh** [comment]
It seems that you need to append "file://" to the path. So the above example would have to use "file:///storage/emulated/0/app/image.jpg" (note the 3 slashes at the beginning) to work.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/image-component-loads-image-from-absolute-path-in-ios-but-not-android

**Comment by joesonw** [comment]
@hramos, I seems run into a similar situation. I built a native photo viewer (in swift), it passes `PHAsset.localIdentifier` back to js, and js calls native method again to get file's path (something like `/var/mobile/Media/DCIM/100APPLE/IMG_0005.JPG`). 

And I then use it like following:

```
<Image style={{..}} source={{ url: url }} />
```

It works fine on simulator, but it does not display on a real iOS device.


iOS version: 10.3.2
React-Native version: 0.45.1
