### ISSUE TITLE
Pull to refresh ListView shows error for Android

### ISSUE THREAD

**Issue by simidaxu** [facebook/react-native#11267]
### Description

When I use refreshControl with listview, header shows in error position, as pic:
![333225077813017480](https://cloud.githubusercontent.com/assets/4651410/20828840/478bf550-b8b4-11e6-9785-0560e3e404a5.jpg)

The red region is pull to refresh header, but is shows over listview not the header of listerview.
When listview render all datasource, then pull to refresh UI could be normal, just when listview not render all datasource pull to refresh ui shows as pic as above.

Pull to refresh UI reference with [Native UI Components ](http://facebook.github.io/react-native/docs/native-components-android.html)
but the same refreshcontrol with ScrollView no such issue.

### Additional Information

* React Native version: [0.33]
* Platform: [Android]

**Comment by damusnet** [comment]
@facebook-github-bot stack-overflow
