### ISSUE TITLE
When re-render the listview , why the value in former <TextInput/> was kept?

### ISSUE THREAD

**Issue by sesky4** [facebook/react-native#11266]
Here's the code:

var FAKE_DATA = [
    {
        type: 0,
    },
    {
        type: 1,
    },
]

var FAKE_DATA_2 = [
    {
        type: 0,
    },
    {
        type: 1,
    },
    {
        type: 2,
    },
]
export default class testpage extends React.Component {
    constructor(props) {
        super(props)

        let listData = new ListView.DataSource({
            rowHasChanged: (p1, p2) => {
                p1 !== p2
            },
        });

        this.state = {
            data: listData.cloneWithRows(FAKE_DATA)
        }
    };

    render() {
        return (
            <View style={{ flex: 1 }}>
                <ListView
                    style={{ flex: 1 }}

                    dataSource={this.state.data}
                    renderRow={this.renderRow} />

                <TouchableOpacity
                    onPress={() => {
                        this.setState({
                            data: this.state.data.cloneWithRows(FAKE_DATA_2)
                        })
                    } }
                    style={{ height: 40, backgroundColor: 'green' }}
                    />

            </View>
        );
    }

    renderRow(data) {
        return (
            <TextInput style={{ height: 40, }} />
        )
    }
}

And when I typed something in textinput and click the button ,the listview was updated but the value in textinput remains in new textinput.Is it bug?Or just the way it works?How to avoid it?

**Comment by damusnet** [comment]
@facebook-github-bot stack-overflow

**Comment by damusnet** [comment]
What is the expected behavior? Your <TextInput /> component is not controlled: it takes no default prop, and its state is never updated. It seems normal its value never changes.
