### ISSUE TITLE
[Modal] can't close modal

### ISSUE THREAD

**Issue by mqy1023** [facebook/react-native#11279]
when i start to fetch data, i set loading state to true(Modal' s visible set as true),
as the fetch finish, i set loading state to false(Modal's visible set as false), 
but the loading modal sometime can close, sometime can't close 。

i open the debug logger, the loading state(true/false) logger of the whole fetch process  is absolute the same in this two kind of result。。

**Comment by feyy** [comment]
I encountered the same problem. What's your solution？

**Comment by mqy1023** [comment]
one page have mutil modal or modal+alert, the second modal(or alert) should delay  xxx millisecond to change state before the first modal close

for more detail u can see this link: http://blog.csdn.net/mqy1023/article/details/53447082

**Comment by feyy** [comment]
谢谢

**Comment by nihgwu** [comment]
#10471
