### ISSUE TITLE
render footer triggers onEndReached infinitely when it has state

### ISSUE THREAD

**Issue by jjdp** [facebook/react-native#11287]
if you have state changes in your render footer. the `onEndReached` event of listview triggers indefinitely.
I am using this because I wanted to show a loading view when the on end reached triggers but now I am forced to not use the `renderFooter` prop and separate this outside of my listview which overlays the bottom part and is kinda ugly.

    _renderFooter() {
    if(this.state.skip > 15 &&
      this.state.onEndReached && !this.state.refreshing && !this.state.isLoading) {
      const footer = {
        width: width,
        height: 40,
        backgroundColor: 'white',
        justifyContent: 'center',
        alignItems: 'center',
      };
      return <View style={footer}><Spinner type="Wave" /></View>;
    }
    return null;
    }

here is also my onEndReached:

    _onEndReached() {
    if(this.state.onEndReached || this.state.refreshing || this.state.isLoading) {
      return;
    }

    this.setState({
      onEndReached: true,
    });

    if (BaseView.hasInternet(this.props.connectionInfo)) {
      this.props.fetchAdditionalPhotos(this.props.user, this.state.skip).then((photos) => {
        if (photos.length > 0) {
          this.setState({
            skip: this.state.skip + photos.length,
          });
        }
        this.setState({
          onEndReached: false,
        });
      });
    } else {
      this.setState({
        onEndReached: false,
      });
    }
    }

happens on RN >=0.36.0
was fine on RN 0.35.0

**Comment by jjdp** [comment]
i have to add more safeguards for it to not render because of the behavior change

**Comment by superandrew213** [comment]
@jjdp how did you end up fixing this?

**Comment by jjdp** [comment]
```
_onEndReached() {
if(this.state.onEndReached || this.state.refreshing || this.state.isLoading) {
  return;
}
```

add more conditions there depending on your case
