### ISSUE TITLE
How can i build private version/local version of react-native?

### ISSUE THREAD

**Issue by younthu** [facebook/react-native#11284]
### Description
Our react-native android app crash for HTTP2 issue, see [Disable HTTP2 for android](https://github.com/facebook/react-native/issues/11283)?

I want to patch it with private fix before official solution(we are under pressure of release, can't wait too long for official fixing now).

The patch will happen in node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/modules/network/NetworkingModule.java

But it seems the file won't get compiled after i change it.

### Help wanted
How can i build react-native app with private patch for NetworkingModule.java?

### Additional Information

* React Native version: 0.38
* Platform: Android
* Operating System: Mac

**Comment by hey99xx** [comment]
The instructions to build the Android library on your own are at https://facebook.github.io/react-native/docs/android-building-from-source.html

**Comment by damusnet** [comment]
@facebook-github-bot answered
