### ISSUE TITLE
React Packager watching android folder makes it fail with EPERM lstat

### ISSUE THREAD

**Issue by pocesar** [facebook/react-native#11288]
### Description

When running `react-native run-android` on Windows 10 x64, Node 6.9.1, intermittently when rebuilding after doing changes to Java files and AndroindManifest.xml, the React Packager fails with:

```
 ERROR  EPERM: operation not permitted, lstat 'G:\www\cim-cadastramento\android\app\build\generated\source\r\debug\android\support\transition\R.java'
{"errno":-4048,"code":"EPERM","syscall":"lstat","path":"G:\\www\\cim-cadastramento\\android\\app\\build\\generated\\source\\r\\debug\\android\\support\\transition\\R.java"}
Error: EPERM: operation not permitted, lstat 'G:\www\cim-cadastramento\android\app\build\generated\source\r\debug\android\support\transition\R.java'
    at Error (native)
```

It's not a problem with permissions, no task or process is running with an elevated user. 

### Reproduction

1. Do a `react-native run-android`
2. Change or link new libraries
3. Repeat run-android

### Solution

An additional .rc file that the packager will read and ignore, like .gitignore. I also want it to ignore `.vscode` and `typings` folders

### Additional Information

* React Native version: 0.38.0
* Platform: Android, API LEVEL 23
* Operating System: Windows 10 x64

**Comment by pocesar** [comment]
A workaround for this problem (since every single time I do an `npm install` or `react-native run-android` it crashes with this error) is to run `react-native run-android`, as soon it opens the packager, kill it, wait for the `BUILD SUCCESSFUL` message to appear, then `node node_modules/react-native/local-cli/cli.js start`

**Comment by jbcullis** [comment]
Dealing with this same issue however a clean prior to building seems to fix the issue.

**Comment by jorgepcbraz** [comment]
same problem here.
however if I do a "gradlew clean" inside de android folder, it then works again
runnign as admin also doesn't solve the problem

**Comment by maobon** [comment]
Looking for JS files in
   D:\studiospace\AndroidRN


React packager ready.

Loading dependency graph, done.
warning: the transform cache was reset.
error: bundling: UnableToResolveError: Unable to resolve module `react/lib/ReactDebugCurrentFrame` from `D:\studiospace\AndroidRN\node_modules\react-native\Libraries\R
enderer\src\renderers\shared\fiber\ReactFiberContext.js`: Module does not exist in the module map or in these directories:
  D:\studiospace\AndroidRN\node_modules\react-native\node_modules\react\lib
,   D:\studiospace\AndroidRN\node_modules\react\lib

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.
    at ResolutionRequest._resolveNodeDependency (D:/studiospace/AndroidRN/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:394:11
)
    at tryResolveSync (D:/studiospace/AndroidRN/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:136:20)
    at tryResolveSync (D:/studiospace/AndroidRN/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:66:12)
    at ResolutionRequest.resolveDependency (D:/studiospace/AndroidRN/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:134:22)
    at dependencyNames.map.name (D:/studiospace/AndroidRN/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:145:59)
    at Array.map (native)
    at ResolutionRequest.resolveModuleDependencies (D:/studiospace/AndroidRN/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:145
:42)
    at module.read.then (D:/studiospace/AndroidRN/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:172:40)
    at process._tickCallback (internal/process/next_tick.js:109:7)
Bundling `index.android.js`  99.0% (402/404), failed.

**Comment by Venryx** [comment]
Note that for step 3, you can also call "react-native start --reset-cache" directly, which is a little more consistent with the usual commands. (eg. react-native run-android)

Also, note that if you're not currently using watchman, it might be worth switching (ie. installing watchman, then adding it to the path) -- especially if you're on Windows. For me, this was the only way I was able to fix the "EPERM: operation not permitted, lstat" errors.

Here's a thread with more people's dealing with this issue, and how I got it fixed for my project: https://github.com/facebook/react-native/issues/9136#issuecomment-306486102

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by pocesar** [comment]
it wasn't, don't close it @hramos

**Comment by nonameolsson** [comment]
This is not fixed yet. The workarounds mentioned in this articles are required on Windows for my colleague http://bitstopixels.blogspot.pe/2017/04/react-native-windows-10-eperm-operation.html
