### ISSUE TITLE
Permission SYSTEM_ALERT_WINDOW

### ISSUE THREAD

**Issue by jjdp** [facebook/react-native#11286]
I have noticed that every time we init using the RN cli this permission is in the manifest.
Does RN need this? What's the use for this?

**Comment by philipheinser** [comment]
@jjdp This only needed for debug mode to show the developer menu. You can safely disable this for your production build. For example by adding this as a production Manifest:

```
<manifest
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    >

    <!-- These are added by React Native for debug mode, but actually aren't needed in releasemode -->
    <uses-permission tools:node="remove" android:name="android.permission.SYSTEM_ALERT_WINDOW" />
</manifest>
```

**Comment by jjdp** [comment]
is there a flag in manifest to disable it in production? like __DEV__ in js?

**Comment by philipheinser** [comment]
You can add a second AndroidManifest.xml to your project to override the react native permissions. There is no flag that I know of.
