### ISSUE TITLE
Linker error introduced in 0.39-0.40 when building to device on release scheme

### ISSUE THREAD

**Issue by kicktheken** [facebook/react-native#11285]
### Description

On a blank project created by 0.39 or 0.40 using `react-native init <project_name>` and then switching the scheme from `Debug` to `Release` and building to a real iPhone 6s device, I get this linker error message:

```
Undefined symbols for architecture arm64:
  "___gxx_personality_v0", referenced from:
      _RCTDefaultLogFunction_block_invoke in libReact.a(RCTLog.o)
      _RCTFormatLog in libReact.a(RCTLog.o)
      ___RCTAddLogFunction_block_invoke in libReact.a(RCTLog.o)
      _RCTPerformBlockWithLogFunction in libReact.a(RCTLog.o)
      _RCTPerformBlockWithLogPrefix in libReact.a(RCTLog.o)
      RCTGetLocalLogFunction() in libReact.a(RCTLog.o)
      ___RCTPerformBlockWithLogPrefix_block_invoke in libReact.a(RCTLog.o)
      ...
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

It looks like it was introduced in this commit: [Cleanup display of C++ stack frames in redbox](https://github.com/facebook/react-native/commit/33deaad196834e77a507cad7b13039161258c059).

### Reproduction

* Run `react-native init project && open project/ios/project.xcodeproj`
* Hit `cmd <` in Xcode and change the build configuration from `Debug` to `Release`
* Set to run on your device (I used an iPhone 6s on iOS 10) and set up the appropriate device signing settings
* You should see a build failure with the above linker error

### Solution

~~I had to turn off **Dead Code Stripping** in `Build Settings` to get this to work. Ideally, I shouldn't need to do this because it was fine in 0.38.~~

**EDITED**: Add `-lc++` in **Other Linker Flags** to test target in release scheme

### Additional Information

* React Native version: 0.39, 0.40
* Platform: iOS 10, iPhone 6s
* Operating System: macOS Sierra

**Comment by ochanje210** [comment]
It worked for me. Thank you!

**Comment by larafale** [comment]
Thanks for tip, it worked for me.

**Comment by kicktheken** [comment]
Sadly, this fix is still required for 0.40 😞

**Comment by compojoom** [comment]
@kicktheken - thanks for providing a workaround!

**Comment by bangd** [comment]
Thanks for workaround, still with 4.0.0

**Comment by dimonge** [comment]
can't seem to get it to work with this solution.

**Comment by rh389** [comment]
This looks like the same issue as https://github.com/facebook/react-native/issues/11861

Interesting that turning off dead code stripping also solves the problem, but the solution now in master is to add `-lc++` to the `Other linker flags` (under Build Settings) of the `myProjectTests` target.

**Comment by dimonge** [comment]
Thanks @rh389. the link was helpful.

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
