### ISSUE TITLE
Accommodating different screen sizes 

### ISSUE THREAD

**Issue by laclance** [facebook/react-native#11295]
I am using flex to layout component which i thought it suppose to resize components to fit the screen? For example., all of my screens fit on an iphone 6 but some of them dont fit on an iphone 5 screen.
React Native version: 0.38.0
Operating System: MacOS

**Comment by Ehesp** [comment]
Please provide more information. Show examples/screenshots/code otherwise no-one can help you.

**Comment by laclance** [comment]
I didn't want too, because i would like to know how react-native handles different screen sizes because i cannot fin a solution that is not a 3rd party library. I created an example on rnplay where the buttons goes off the screen : https://rnplay.org/apps/OpZMxQ

**Comment by radko93** [comment]
It's a good question to post on StackOverflow, not here.

**Comment by laclance** [comment]
I did but didn't get a great response

**Comment by laclance** [comment]
Solved by scaling images, a few components and a few font sizes based on screen dimensions and making use of scrollview.
