### ISSUE TITLE
react-native run-ios fails: ENOENT no such file or directory, uv_chdir

### ISSUE THREAD

**Issue by jcollum** [facebook/react-native#11293]
I realize this has been asked before. #5054. That issue was closed. None of the fixes in there work for me. 

### Description

When I pull a repo, npm install then start the packager then run `react-native run-ios` it fails with error: ENOENT no such file or directory, uv_chdir

### Reproduction

Cloned this repo: https://github.com/jcollum/kishar-nine

npm install
start packager (last line: `[12/4/2016, 11:31:46 AM] <END>   Initializing Packager (336ms)` so it looks like it started fine

then: 

```
$ react-native run-ios

ENOENT: no such file or directory, uv_chdir
```

Attempted fixes: 

```
rm -rf node_modules
npm install 
rm -fr $TMPDIR/react-*
watchman watch-del-all
rm -fr $TMPDIR/npm*
rm -fr $TMPDIR/*.json.gzip
cat rn-cli.config.js 
# result: no file present

react-native run-ios 
# fails, same error
```
### Solution

Give some indication of what the real issue is. Is there a missing folder? Seems so, but shouldn't `run-ios` be creating it? 

### Additional Information

$  react-native --version
react-native-cli: 1.2.0
react-native: 0.38.0

Platform: ios

Operating System: OSX: Darwin Darwin Kernel Version 15.6.0

**Comment by gen4sp** [comment]
experience similar issue

**Comment by jcollum** [comment]
Sorry I forgot to update: my issue was that I hadnt put my ios folder into source control. That missing uv_chdir error means it can't find any ios files.

**Comment by TheChuckster** [comment]
Any updates on this? We just updated our Xcode today to Version 8.2.1 (8C1002), and now we're also seeing this issue. As feedback, actually naming the missing "file or directory" instead of just saying "no such file or directory" would be more helpful for us to diagnose the actual problem!

**Comment by 1c7** [comment]
same here

**Comment by pbojinov** [comment]
Seeing the same when following the `Integration With Existing Apps` guide http://facebook.github.io/react-native/releases/0.42/docs/integration-with-existing-apps.html

**Comment by dereknex** [comment]
Don't forgot modify `Info.plist`
http://facebook.github.io/react-native/releases/0.42/docs/integration-with-existing-apps.html#app-transport-security

**Comment by temitope** [comment]
try running `react-native init aProjectName` if you are forkinga n existing project and trying to run/test in simulator @1c7 @pbojinov @gen4sp

**Comment by pbojinov** [comment]
@dereknex you're right, issue was with `Info.plist`. 

I was editing it in Xcode and the `localhost` key didn't get added under `NSExceptionDomains`. Ended up editing it in text editor and solved the wrong key path.

That solved it! Thanks

**Comment by hovox** [comment]
I have followed [integration-with-existing-apps](http://facebook.github.io/react-native/releases/0.42/docs/integration-with-existing-apps.html) guide and seeing this error. Added localhost as exception domain. My files are not in ios directory may this be an issue?

**Comment by toureek** [comment]
I did follow the  [integration-with-existing-apps](http://facebook.github.io/react-native/releases/0.42/docs/integration-with-existing-apps.html), too. When I met this same issue,  I just renamed my original folder which contains the iOS source code.
I ran this half an hour ago: 
"mv originalFolderName ios" in the terminal before run "react-native run-ios", and it went well.

**Comment by hovox** [comment]
I have just started over, and it worked.

**Comment by tewodroswondimu** [comment]
For me I just do a `react-native upgrade` then `react-native run-ios` and it works

**Comment by mrkem598** [comment]
I was having the following issue ENOENT: no such file or directory, uv_chdir when i 

> run _react-native run-ios_
my error gone when i run 

> react-native upgrade
and then 

> react-native run-ios

**Comment by paranoidjk** [comment]
same problem here. any process?

**Comment by jeffreyrajanofficial** [comment]
For me I tried `react-native run-ios` code on a expo project. Try to open it in a expo XDE and run.

**Comment by marceloaraujo** [comment]
@tewodroswondimu Your solution works very well. Thank you!!

**Comment by joaootaviohuss** [comment]
Resolvi meu problema excluindo o conteúdo da pasta C:\Users\JoaoHuss\AppData\Local\Temp\, tinha uma biblioteca que foi adicionada em um projeto anterior com o mesmo nome, e ficou essa dependência dessa biblioteca salva nesse conteúdo dos arquivos temporários.

**Comment by himanshusingh2407** [comment]
I just restarted my system and it worked.
