### ISSUE TITLE
Animated.diffClamp doesn't work with interpolate value

### ISSUE THREAD

**Issue by nikitaMe1nikov** [facebook/react-native#11299]
### Description

In this example(https://rnplay.org/apps/og824Q) of Animated.diffClamp doesn't work with interpolate value, but works with Animated.multiply and regular animation value.

### Reproduction

Use example(https://rnplay.org/apps/og824Q)

### Additional Information

* React Native version: 0.39
* Platform: Android
* Operating System: Linux

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
