### ISSUE TITLE
Navigator push, view mount but not show

### ISSUE THREAD

**Issue by iceNuts** [facebook/react-native#1130]
It is a very weird bug, I use ```navigator.push(route);``` to push a child view. However, the view still stays at the parent page. I can see the logs from ```componentDidMount``` and ```render``` function. I use flux. Is this the reason?

Thanks.

**Comment by iceNuts** [comment]
It turns out because I have this issue: ```addListener: function(callback) {
    this.on('bar', callback(foo));
  },``` in store file. I want to pass data from one component to the other with callback. Is this working? If not, why react native doesn't show some errors but simply not work?

Thanks.

**Comment by ericvicenti** [comment]
I don't understand exactly what is going wrong. Could you post a simplified gist that demonstrates this issue, and describe what you expect to happen vs what is actually happening?

**Comment by iceNuts** [comment]
@ericvicenti Please close this issue. It looks like the way flux to pass data to some other components is simply add a few functions to return the objects. 

Thanks.
