### ISSUE TITLE
React-native doesn't reload ios application in simulator

### ISSUE THREAD

**Issue by cicibobo** [facebook/react-native#11303]
i have issue with reloading app,

react-native-cli: 1.2.0 
react-native: 0.37.0 
watchman: 4.7.0

index.ios.js file.

```
import React from 'react';
import ReactNative, {View,Text} from 'react-native';
import Header  from './src/components/header';

const App = () => {
    return (
        <View>
            <Header headerText={'Products '}/>
            <Text>Test</Text>
        </View>
    );
};

ReactNative.AppRegistry.registerComponent('ditrack', ()=> App);

```
then run command react-native run-ios. App simulator loaded but don't update any changes in code for ex.

` <Text>Test</Text> to <Text> OTHER Test</Text>`

I already reviewed several issues in stackoverflow and github but it did't helped me

**Comment by rockink** [comment]
Not exactly sure about ios, but in android they have reload option, which is the key 'r' or 'rr'. Doing that would update the render in the screen. I suspect there should be similar key in ios too!

**Comment by keeleycarrigan** [comment]
In the iOS simulator you can set it to auto reload when changes are made by hitting `command+D` and choosing "Enable Live Reload", but you can also manually reload with `command+R`.

**Comment by christopherdro** [comment]
Enable live reload is an option on both platform in dev mode. You can access it through the developer menu which is triggered by a shake gesture.
