### ISSUE TITLE
Option to Force Disable RTL

### ISSUE THREAD

**Issue by joncursi** [facebook/react-native#11308]
I have a dynamic Text component that sometimes renders a single Afghani / Qatari / etc. symbol (the currency unit) and RN sees that symbol and tries to automatically render the Text component RTL. This is problematic, because the majority of the Text component is still English.

I would like the following to read...

```
**symbol** **price** **english description**
```

But the RTL symbol ends up inverting this entirely:

Afghani symbol example:

<img width="377" alt="screen shot 2016-12-05 at 7 54 19 am" src="https://cloud.githubusercontent.com/assets/4974609/20885688/30f0cd30-bac0-11e6-80ff-73c3ca388240.png">

Qatari symbol example:

<img width="374" alt="screen shot 2016-12-05 at 8 19 10 am" src="https://cloud.githubusercontent.com/assets/4974609/20886353/ae2dd4fc-bac3-11e6-81f8-299976ee6dee.png">

**Comment by rneiss** [comment]
You should just be able to use the unicode control character for LTR: \u200E to force it the way you want -- 

\u200E+symbol+price+ " "+desc

**Comment by joncursi** [comment]
Brilliant! Thank you!
