### ISSUE TITLE
App crashed with java.lang.RuntimeException: Tried to get non-existent cookie

### ISSUE THREAD

**Issue by kevinTutu** [facebook/react-native#11302]
We catched a crashed which is about 'Tried to get non-existent cookie',we find this crash through a third platform ,the logcat as follow:

![](http://i.xiaohongchun.com/logcat.png)

And the device model as follow:

![](http://i.xiaohongchun.com/phoneModule.png)

The react-natvie version is 0.31.0
I find the same issue in #5944,but I didn't use the vysor(I don't know  whether the user use it,I guess the user is not smart enough),and this issue is not solved yet

**Comment by remch1990** [comment]
What is the solution to this problem?
RN: 0.33 Android
FATAL EXCEPTION: main
java.lang.RuntimeException: Tried to get non-existent cookie; no stack available (TouchEventCoalescingKeyHelper.java:75)

**Comment by cnsnake11** [comment]
+1

**Comment by shawnXiao** [comment]
+1

**Comment by 1097616819** [comment]
+1

**Comment by ldy441040480** [comment]
+1

**Comment by hkusb** [comment]
Have someone resolved it? I also meet this problem.

**Comment by JakeRawr** [comment]
+1

**Comment by hkusb** [comment]
I think I have resolved it in #12063.

**Comment by qq3061280** [comment]
+1

**Comment by WeweTom** [comment]
+1
RN 0.31

**Comment by cuitianze** [comment]
+1

**Comment by henrikra** [comment]
Please look at @hkusb 's pr since I got this crash too!

**Comment by sorcerdu** [comment]
+1

**Comment by stefanwuest** [comment]
+1

**Comment by the-mace** [comment]
+1 RN 0.38

**Comment by ptomasroos** [comment]
This is now fixed in https://github.com/facebook/react-native/commit/d2939eafbf56f99ea4da7374b9812ae6f54c1d3d should be closed @kevinTutu
