### ISSUE TITLE
Packager and live reload not picking up changes in node_modules

### ISSUE THREAD

**Issue by asciiman** [facebook/react-native#11310]
### Description

I just updated my project from RN 0.34.1 to 0.39.0.  We have a shared code base that we use between several projects that we include in the project.  When we make changes to that shared codebase we have a watch script which copies the transpiled files over into our project's node_modules folder.  With RN 0.34.1 and earlier this would trigger a live reload and the packager would pick up the file changes.  Now with 0.39 there is no live reload and if I manually reload it doesn't pick up any of the changes.

DOESN'T RELOAD 
Folder to shared code:
`project/node_modules/business-logic/lib/constants/session.js`

Imported into project via:
`import * as sessionConstants from 'business-logic/lib/constants/session';`

If I make a change directly in my project it works.  And if I make a change in core RN files in node_modules it works okay too.

What is causing this?  Is there some new caching of node_modules files somewhere?

### Additional Information

* React Native version: 0.39.0
* Operating System: MacOS
* watchman 4.5.0

**Comment by Ehesp** [comment]
Duplicate: https://github.com/facebook/react-native/issues/11301

**Comment by asciiman** [comment]
Thanks.
