### ISSUE TITLE
Illegal node ID set as an input for Animated.DiffClamp node

### ISSUE THREAD

**Issue by nihgwu** [facebook/react-native#11317]
![image](https://cloud.githubusercontent.com/assets/2595058/20914053/9e41ccde-bbb7-11e6-8666-84a9c9fb8009.png)

After I upgrade to RN0.40RC0( or perhaps it exists in RN0.39 as well, I will test it later) I get this error consistently, the only change is that I'm using native event(AnimatedScrollVIew) now, and it throw the error on both iOS and Android. 

I try to comment this line https://github.com/facebook/react-native/blob/e1577df1fd70049ce7f288f91f6e2b18d512ff4d/Libraries/NativeAnimation/Nodes/RCTDiffClampAnimatedNode.m#L56 and then it works as before.

There no other commits changed this DiffClamp implementation so I guess it's related to `AnimatedScrollVIew`, so any ideas? @janicduplessis

**Comment by magicismight** [comment]
0.42.0
```
    const translateX = Animated.diffClamp(animatedValue, 0, last).interpolate({
      inputRange: [0, 1],
      outputRange: [0, last * 11]
    });

    return (
      <View style={styles.commentIndicator}>
        <View style={styles.commentIndicatorContainer}>
          <Animated.View style={[styles.commentIndicatorDot, styles.commentIndicatorActive, {transform: [{translateX}]}]} />
        </View>
      </View>
    );

```

**Comment by arsenghazaryan** [comment]
@magicismight, @janicduplessis
When the component is getting unmounted it is throwing that error. Both android and iOS.

If you are using nativeDriver and Animated.diffClamp

**Comment by magicismight** [comment]
@arsenghazaryan I'm getting this error when the component is just mounted.

**Comment by arsenghazaryan** [comment]
Mounting works fine for me. 
Have you tried to mount the component and then update the styles and set the animation in styles.
e.g.
```
setTimeout(() => {
this.setState({ useAnimation: true });
}, 1000)

const animStyles = this.state.useAnimation ? { transform ....} : {};
```

**Comment by janicduplessis** [comment]
I'll have a look at this issue this week

**Comment by arsenghazaryan** [comment]
Hey @janicduplessis 
I was wondering if you had time to take a look into this issue?

Thanks :)

**Comment by janicduplessis** [comment]
Just did :) https://github.com/facebook/react-native/pull/12910

**Comment by arsenghazaryan** [comment]
Thanks a lot !!!

**Comment by melihberberolu** [comment]
@janicduplessis Which version corrected this bug ?
