### ISSUE TITLE
[TextInput] textAlign: center not consistent for (some) empty lines

### ISSUE THREAD

**Issue by aleclarson** [facebook/react-native#11319]
### Description

Inconsistent text alignment for new lines added to the top (instead of the bottom) of a `TextInput`.

- Create `TextInput` using `textAlign: center` and `multiline: true`
- Focus the `TextInput`
- Press the return key
- Tap the newest line
- Type something on the newest line
- Notice how **your text is not centered**

### Reproduction

![](http://i.imgur.com/8mxr9tW.gif)

### Additional Information

* React Native version: 0.37.0
* Platform: iOS (Android not tested)
* Operating System: MacOS

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.

**Comment by jgrancher** [comment]
I was having the same issue though 😢.  (With RN 0.40)

**Comment by CWright777** [comment]
Having this issue as well on RN .38.

**Comment by CWright777** [comment]
This might be an issue in iOS. 

But adding `textView.textAlignment = NSTextAlignmentCenter;` to 
react-native/Libraries/Text/RCTTextView.m under the line:
`- (BOOL)textView:(RCTUITextView *)textView shouldChangeTextInRange:(NSRange)range replacementText:(NSString *)text`
forces the text to center align (the cursor still jumps back to left justified when the line is empty but it is an improvement). However this will make all your multiline text inputs center aligned.
