### ISSUE TITLE
Android Image if Large -> Error: Pool hard cap violation?

### ISSUE THREAD

**Issue by kosiakMD** [facebook/react-native#11326]
Get Image remotely and want to show in full screen
iOS - OK! Android - some loading and showing, some just black screen (modal default background), some 'red' Errors, caused if failed Native Image.getSize

When show small - OK.

Not enough memory! Small - OK. Problem persists only when very large Images: Full HD - only not showing, but without Error, larger cause the error written previously

    Error: Pool hard cap violation? Hard cap = 75497472 Used size = 60880784 Free size = 0 Request size = 20072448

**Comment by kosiakMD** [comment]
It's real memory leak, and may be related with Fresco

**Comment by jacky-zf** [comment]
I hava the same problem.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/android-image-if-large---error-pool-hard-cap-violation
