### ISSUE TITLE
TabBarIOS.Item must has a child

### ISSUE THREAD

**Issue by StTraft** [facebook/react-native#11325]
### Description

[FILL THIS OUT: Explain what you did, what you expected to happen, and what actually happens.]
Hit an issue on `TabBarIOS.Item` if no child passed into it.
if I return something like this in `render`:
```
<View>
  <TabBarIOS>
    <TabBarIOS.Item selected={true}>
      <View style={shouldBeNull}/>
    </TabBarIOS.Item>
  </TabBarIOS>
</View>
```
It will be fine, but if I removed the child `<View style={shouldBeNull}/>`:
```
<View>
  <TabBarIOS>
    <TabBarIOS.Item selected={true} />
  </TabBarIOS>
</View>
```
It throws `React.Children.only expected to receive a single React element child` error.

### Reproduction

[FILL THIS OUT: Try to reproduce your bug on rnplay.org and provide a link. If you can't reproduce the bug on rnplay.org, provide a sample project.]

### Solution

`Libraries/Components/StaticContainer.js`
```
class StaticContainer extends React.Component {

  shouldComponentUpdate(nextProps: Object): boolean {
    return !!nextProps.shouldUpdate;
  }

  render() {
    const child = this.props.children;
    return (child === null || child === false) # should it include undefined?
      ? null
      : React.Children.only(child);
  }

}
```
### Additional Information

* React Native version: [0.37]
* Platform: [iOS]
* Operating System: [ MacOS ]

**Comment by hey99xx** [comment]
What's wrong with `TabBarIOS.Item` enforcing this rule though? Does it make sense to render a tab bar icon without an inner view, wouldn't that look strange?

**Comment by StTraft** [comment]
@hey99xx while I can have a `TabBarIOS.Item` fully rendered and functional with providing proper props (`title`, `icon`, `onPress`...), why can't it be a leaf and must be a branch?

**Comment by hey99xx** [comment]
Looking at the example https://facebook.github.io/react-native/docs/tabbarios.html `TabBarIOS.Item` is a wrapper around the entire tab above the tab bar, isn't it? So it's not just `title`, `icon` but the upper part as well. 

Anyways I guess if accepts `null` as a child, then maybe there's no point enforcing this rule. I'm not sure why it's enforced then.

**Comment by StTraft** [comment]
So I'm wondering should it include `undefined` in the checking of `this.props.children`

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.

**Comment by tristanbbq** [comment]
Got this error. I suggest this gets re-opened and re-investigated.

**Comment by StTraft** [comment]
@tristanbbq which version are you on?
it had been a year ago and now the `StaticContainer` now has render method equivalent to the solution above
it's hard to recall memory that's a year ago :P
