### ISSUE TITLE
this.state does't work at listView's renderRow

### ISSUE THREAD

**Issue by iahu** [facebook/react-native#1133]
I update the this.state.pressTest on my `onItemPress` method ([gist](https://gist.github.com/iahu/0e524f4612a8925f2f9c#file-index-ios-js-L118)), and hope can get the newly state of pressTest ([gist](https://gist.github.com/iahu/0e524f4612a8925f2f9c#file-index-ios-js-L98)).But, it does't work on my code.

why? thx.

**Comment by amitverma** [comment]
you're calling setState twice. doesn't this cause it to render twice as well? maybe a race is happening? 
```
that.setState({updatePressed: true});
that.setState({pressTest: 2});
```

**Comment by iahu** [comment]
`that.setState({pressTest: 2});` added to test. Maybe I would comment the first line.

**Comment by tadeuzagallo** [comment]
There's no problem in calling `setState()` more than once, although if it wasn't a test it'd be better to put then together.

The issue there is that `setState()` is async, and you're trying to access it on the next line. It doesn't mean it's not working, it means it wasn't evaluated yet. It'll just be evaluated at the end of the frame, when all the calls have been finished.

https://facebook.github.io/react/docs/component-api.html#setstate

**Comment by iahu** [comment]
I know the `setState` can't immediately update.
my problem is that, I can't get the newly state add `renderRow` ([gist](https://gist.github.com/iahu/0e524f4612a8925f2f9c#file-index-ios-js-L98))

**Comment by iahu** [comment]
`this.state.pressTest` (at line 98) always be 0 but not 2. At the same time, I can get it at line 82.

**Comment by tadeuzagallo** [comment]
Oh, I see, `renderRow` is never called again...

I had a look on the source, but I'm not sure what's the best solution here. /cc @vjeux

**Comment by ide** [comment]
Try always returning true from rowHasChanged. Better solution is not to access this.state/this.props/this.context/any non-constant instance variable or global variable from renderRow, and instead pass data through only the data source. The docs should probably mention this as a rule of thumb since there have been a couple similar issues opened.

**Comment by tadeuzagallo** [comment]
I tried the `rowHasChanged` trick, but it doesn't work. It's not called again either, since the row is already rendered and the data source hasn't change, it doesn't try to re-render.

**Comment by PhilippKrone** [comment]
I've tried to do the same thing as well some days ago and had no real luck. Some things a tried (which are kind of dirty though):
* put everything in the datasource objects (as ide suggested)
* re-create the datasource by changing a dummy value (so that the rows are re-rendered)
* create a new datasource with the same content and pass it to the ListView
* this.props.navigator.replace(<same screen again>)

I'm currently living with the last option, although it has probably some disadvantages. Had no time to investigate it any further.

**Comment by ide** [comment]
Good point, you need to force a data source update too. Option 3 of cloning a data source with the same content should provide the desired behavior.

For the API it would be easier if hasRowChanged were replaced with shouldComponentUpdate plus component pooling to avoid allocations. I haven't thought through the details but I think we want a React-style API instead of this UIKit-inspired one.

**Comment by dvdhsu** [comment]
I've also been having problems with this. For me, I was trying to render a list of notifications, each with a time associated. So, like like how tweets were labeled "2m ago". 

I initially tried calculating the relative times inside renderRow, but that didn't work. So, I ended up cloning notifications (via JSON.parse(JSON.stringify(notification)). That worked, but would spuriously cause some of my rows to become blank whenever the row changed enough (going from "4s ago" to "5s ago" was fine, but going from "9s ago" to "10s ago" wasn't). 

So, I then tried removing the time from my renderRow function, so it'd just render the notification. The time was still being updated in the background, it just wasn't being displayed. This, indeed, would make my rows more stable, and they no longer disappear randomly.

After reading @ide's suggestion above, then set put all my times into state, but still caused my rows to spuriously become blank. One again, removing the times fixed the issue. I'm still not sure why this is. Have you encountered these problems, @PhilippKrone?

**Comment by iahu** [comment]
clone the origin DS to force the renderRow render again works. Thans a lot.
```js
var _ds = JSON.parse(JSON.stringify(ds));
that.setState({
	dataSource: that.state.dataSource.cloneWithRows(_ds),
	updatePressed: true
});
```

**Comment by kevinzzz007** [comment]
@iahu could you share more details on this code?  What is the context?

**Comment by iahu** [comment]
@kevinzzz007 source code is here https://gist.github.com/iahu/0e524f4612a8925f2f9c

**Comment by kevinzzz007** [comment]
@iahu How did you manage to force the ListView to re-render?  I didn't see anywhere you created `_ds`...

**Comment by iahu** [comment]
OK, I have update my gist.

**Comment by kevinzzz007** [comment]
@iahu thanks!  That made it really clear.  So in my case, I got my data from ParseReact, here is my code:
```
var _ds = this.data.driver_available_times;
this.setState({
        dataSource: this.state.dataSource.cloneWithRows(_ds),
    });
```

**Comment by iahu** [comment]
You need to copy make a clone of you original datasource. That means it's must be a "immutable object".
So as your case, you can do that like me.
```
var _ds = JSON.parse(JSON.stringify(this.data.driver_available_times));
```

**Comment by kevinzzz007** [comment]
@iahu yeah, I tried that, an issue with that is my Parse object has date object in it, which if I run the object through 
`(JSON.stringify(this.data.driver_available_times));`, some data will be lost, so I had to use
`var _ds = this.data.driver_available_times;`

**Comment by iahu** [comment]
@kevinzzz007  try this code
```js
var d = this.data.driver_available_times;
var _ds = new Date(d); // d !== _ds, make a  clone of your Date object.
```

**Comment by kevinzzz007** [comment]
@iahu thanks!  I will give it a shot :-)

**Comment by fiowind** [comment]
re-create the datasource by changing a dummy value (so that the rows are re-rendered).
this fixed this propblem well.
look detail at http://stackoverflow.com/questions/29933546/updating-this-state-datasource-doesnt-update-listview

**Comment by fiowind** [comment]
this._dataSource[movie].imageurl="/dist/images/default_picture.jpg";
this.ds = new ListView.DataSource({rowHasChanged: (row1, row2) => row1 !== row2});
this.setState({
    dataSource: this.ds.cloneWithRows(this._dataSource),
    loaded: true,
});

**Comment by kevinzzz007** [comment]
@fiowind that makes sense, I might try this solution in the future, but I do think there should be an option for us to reload the `ListView`

**Comment by sahrens** [comment]
ListView is designed to have all data for renderRow come from the data source. I recommend putting the selection state in the row data of the data source and updating that with clone and setState. Does that work?

Sounds like some documentation improvements would help...

**Comment by rammi44** [comment]
this.state.todoItemArray = this.state.todoItemArray.**concat**({ 'Item': item, 'TodoItemstyle': todoItembgStyle });
             this.setState({
                todoItemArray: this.state.todoItemArray,
                isDeleteDefaultItem: true
            });

Use Concat.. it will work.. adding new list item to the datasource... Here TodoItemArray is my datasource..
