### ISSUE TITLE
Why are there no dynamic framework targets for React Native?

### ISSUE THREAD

**Issue by LeoNatan** [facebook/react-native#11337]
## Description

React Native has only static library targets. Any reason why there are no dynamic framework targets as well? 

![screen shot 2016-12-07 at 12 00 28](https://cloud.githubusercontent.com/assets/2270433/20963129/c9c2495c-bc74-11e6-820d-4f8f170c16e9.png)

I understand why this was done from the start, as RN supported iOS 7 (and possibly below) at some point, but since the project now has a deployment target of iOS 8, there really is nothing to prevent dynamic frameworks on the surface. Any underlying technical issues in supporting it?

Adding dynamic framework targets will finally allow stopping the `HEADER_SEARCH_PATHS` hell of sub-projects. Working with Swift projects will also be much simpler.

### Solution

There are two solutions I can think of; add dynamic frameworks targets directly and include all source files there, all headers in the headers phase. Or, create a dynamic framework wrapper that links with the static libs, but still exposes the headers in a headers phase. The former is more elegant, but the latter can be a little bit less work to maintain.

### Additional Information

* React Native version: Latest git source as of 2016-12-7.
* Platform: iOS
* Operating System: MacOS/Xcode

**Comment by LeoNatan** [comment]
CC @javache @emilsjolander

**Comment by ide** [comment]
There were some serious leaks (JSC wouldn't get cleaned up) when switching to a dynamic framework, anyone who tries to switch over should make sure to do a thorough audit and try it out in production before switching everyone else over.

**Comment by LeoNatan** [comment]
@ide Why would memory management / JSC GC be affected by how RN is linked into the binary?

**Comment by ide** [comment]
I'm not sure why but it was.

**Comment by javache** [comment]
The native code for RN should be pretty small. What would you gain by moving to frameworks?

I've also just redone how we export headers from the core libs, which should make integrating other libraries easier hopefully https://github.com/facebook/react-native/commit/59407f36608f52d4402d742d916f78acd3ca7152

**Comment by LeoNatan** [comment]
@javache Yes, your change will improve things considerably - for main RN projects only. However, an issue still remains for projects which extend the main project. For instance, including an open source component in the main project as a sub-project; since the sub-project cannot be linked against RN, a header search path hell still occurs for that sub-project. The headers phase is important, but not enough. 

If there were dynamic framework targets, each sub-project could be linked directly with RN, enjoying the same improved header management as the main project, while finally all linking against a single RN framework at the end. 

I am not sure what @ide means, but it sounds unrelated to how RN is linked. It is worth investigating, of course, since it is most likely an underlying issue.

**Comment by LeoNatan** [comment]
@javache Please see this article:
http://landonf.bikemonkey.org/code/ios/Radar_15800975_iOS_Frameworks.20140112.html

Would you be interested in a PR for this?

**Comment by kanekin** [comment]
>Or, create a dynamic framework wrapper that links with the static libs, but still exposes the headers in a headers phase. 

@LeoNatan Could you elaborate this? Is it possible to include static lib as a part of a dynamic framework?

**Comment by LeoNatan** [comment]
@kanekin Yes, it is possible. You create a dynamic framework target, link the static library / framework, and add `-ObjC -all_load` to your `OTHER_LDFLAGS` (other linker flags).

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/why-are-there-no-dynamic-framework-targets-for-react-native

**Comment by rodrigoelp** [comment]
The unfortunate part of this is, this feature request is so awesome and there has been some deal of people voting here but nobody bothered voting in canary: https://react-native.canny.io/feature-requests/p/why-are-there-no-dynamic-framework-targets-for-react-native

**Comment by dehlen** [comment]
I would love to see this happen. This way I could cache the whole RN dependency as a Carthage Framework.

**Comment by dehlen** [comment]
I already tried building a dynamic framework wrapper around the static lib but got stack exporting the headers in the correct way aswell as making the dynamic framework usable with swift (not objc) apps.
