### ISSUE TITLE
undefined is not a function (evaluating 'global.nativeCaptureHeap(path)')

### ISSUE THREAD

**Issue by zimengle** [facebook/react-native#11335]
hi , I want to use "capture heap" function to dump heap , but throw TypeError: undefined is not a function (evaluating 'global.nativeCaptureHeap(path)') when I click capture heap in dev menu，I find jni JSCMemory.cpp in ReactCommon/cxxreact implement nativeCaptureHeap function ,but looks like not link in project

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
