### ISSUE TITLE
Packager is not seeing changes

### ISSUE THREAD

**Issue by Maxwell2022** [facebook/react-native#11332]
### Description

When I run `npm start` I expect the packager to detect when files have changed and re-bundle the application. I'm using `watchman` version `4.7.0` else I have the famous FSEvent issue happening.

### Reproduction

run `npm start` and modify a `.js` file in the project folder.

### Additional Information

* MacBook Pro 2016
* react-native-cli: 1.3.0
* react-native: 0.38.0
* Operating System: macOS Sierra (10.12.1)
* Node version: 6.9.1

<img width="628" alt="screen shot 2016-12-07 at 12 47 48 pm" src="https://cloud.githubusercontent.com/assets/670701/20951694/66ca0f2c-bc7b-11e6-88a7-165fdb101c48.png">

**Comment by ugputu18** [comment]
Same problem. I tried to clear watchman cache and reinstall it. Did not work.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/packager-is-not-seeing-changes
