### ISSUE TITLE
borderBottomWidth issue on real device

### ISSUE THREAD

**Issue by nihgwu** [facebook/react-native#11340]
If the height of a `View` is large, the `borderBottomWidth` will be much larger then set in the style on a real iOS device, seems to be scaled with the height of the `View`

Demo:
```js
'use strict';

import React, { Component } from 'react';

import {
  StyleSheet,
  ScrollView,
  View,
} from 'react-native';

class Demo extends Component {
  render() {
    return (
      <ScrollView style={{flex: 1}}>
      	<View style={{height: 50000, backgroundColor: '#0f0', borderColor: '#f00', borderBottomWidth: StyleSheet.hairlineWidth}}>
      	</View>
      	<View style={{height: 5000, backgroundColor: '#0ff', borderColor: '#f00', borderBottomWidth: StyleSheet.hairlineWidth}}>
      	</View>
    	</ScrollView>
    );
  }
}


export default Demo;
```
on Simulator:
![simulator screen shot 2016 12 7 8 23 13](https://cloud.githubusercontent.com/assets/2595058/20967601/48539866-bcbb-11e6-93ef-73e295764ce7.png)

on real device(iPhone 6s):
![img_2079](https://cloud.githubusercontent.com/assets/2595058/20967644/75378edc-bcbb-11e6-8190-c9aed047937a.PNG)

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
