### ISSUE TITLE
cannot load main.jsbundle downloaded from server ?

### ISSUE THREAD

**Issue by xiekunRonaldo** [facebook/react-native#1134]
Everything works well When I put the `main.jsbundle` in iOS directory,But If I put it in the NSCachesDirectory and then get its' URL with the following code

```objc
  #define APP_CACHE                   [NSSearchPathForDirectoriesInDomains (NSCachesDirectory, NSUserDomainMask, YES) objectAtIndex:0]
  jsCodeLocation = [NSURL fileURLWithPath:[APP_CACHE stringByAppendingString:@"/js/main.jsbundle"]];
```
Build Failed!
main.jsbundle cannot download from the server and then executed?

**Comment by xiekunRonaldo** [comment]
I see ,'A bundleURL is required to create an RCTRootView' , But in the future is it possible to load main.jsbundle downloaded from server?

**Comment by brentvatne** [comment]
Sure, this is possible, check out https://github.com/jsierles/RNPlayNative for a demo. This app allows you to load bundles that are shared through a web app so that you can quickly preview and share.

**Comment by brentvatne** [comment]
@xiekunRonaldo - when you call `initWithBundleUrl` on `RCTRootView`, this is called to resolve the URL: https://github.com/facebook/react-native/blob/master/React/Base/RCTConvert.m#L67-L101 - you could try putting a breakpoint in here: https://github.com/facebook/react-native/blob/master/React/Base/RCTJavaScriptLoader.m#L34 to see what is returned from that and adjust accordingly

**Comment by xiekunRonaldo** [comment]
@brendanv YES! I did it successfully!!!Thanks!

**Comment by brentvatne** [comment]
@xiekunRonaldo - do you mind posting the full source for code related to the issue here in case somebody else has the same issue? :smile:
