### ISSUE TITLE
ListView Datasource rowHasChanged

### ISSUE THREAD

**Issue by rockink** [facebook/react-native#11344]
Can we just not do `rowHasChanged = true` or sth instead of the given below! 

Why can possibly be different than that?  Any examples that we really need to have something different than 
`{rowHasChanged: (r1, r2) => r1 !== r2}`.

```javascript
  constructor(props) {
    super(props);
    const ds = new ListView.DataSource({rowHasChanged: (r1, r2) => r1 !== r2});
    this.state = {
      dataSource: ds.cloneWithRows([
        'John', 'Joel', 'James', 'Jimmy', 'Jackson', 'Jillian', 'Julie', 'Devin'
      ])
    };
  }
```

Also, looking searching in GitHub about how rowHasChanged being used, one of the examples is this, 
` rowHasChanged: (r1, r2) => r1.id !== r2.id` from this [code](https://github.com/oxoooo/aja-ios/blob/e0e71bbccad647af11ee721a247e063671d0417f/src/lib/utils.js) 

So, based on that, it seems to mean that it will look into the array entries, and if it means comparing with ids, it will compare with ids (like in the file above)  , or if its string (like in the example above) compares the string! 

If that is the case, can we have more documentation on how `rowHasChanged` be used in a different way than what is shown in the example.

**Comment by scarlac** [comment]
Since you're using an arrow function to specify `rowHasChanged`, then you can access "this".
That means you could actually check the current state if you need to, e.g.:
```
const ds = new ListView.DataSource({rowHasChanged: (r1, r2) => {
  return this.state.forceRowUpdate || r1 !== r2
});
```
This method would be handy if you're using pure components and just once want to do a deep modification of the row data.

**Comment by hramos** [comment]
Closing as ListView is deprecated in 0.43. Use FlatList.
