### ISSUE TITLE
ScrollView with marginBottom doesn't scroll to the bottom on Android

### ISSUE THREAD

**Issue by jgkim** [facebook/react-native#11367]
### Description

When a `ScrollView` has `marginBottom` on Android, it doesn't scroll to the bottom.

### Reproduction

This is a known upstream Android issue.
Cf. http://stackoverflow.com/questions/15131962/scrollview-doesnt-scroll-to-the-bottom

### Solution

As a workaround, we can use `padding` instead of `margin`.

### Additional Information

* React Native version: 0.39
* Platform: Android
* Operating System: MacOS

**Comment by ddereszewski** [comment]
On version 0.40 both padding and Margin are causing the issue. Platform Android, IOS works fine.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/scrollview-with-marginbottom-doesnt-scroll-to-the-bottom-on-android
