### ISSUE TITLE
GIF images can not work with borderRadius

### ISSUE THREAD

**Issue by magicismight** [facebook/react-native#11363]
### Description

Animated GIF image on Android can not work properly with a borderRadius style.

### Reproduction
```
<Image
  style={{width: 40, height: 40, borderRadius: 20}}
  source={{uri: 'http://somedomain/xxx.gif'}} 
/>
```
The 4th image below is an Animated GIF image
![image](https://cloud.githubusercontent.com/assets/7693239/21003951/0516c588-bd69-11e6-8b25-0b1b1deac5a3.png)

### Additional Information

* React Native version: 0.39.0
* Platform: Android
* Operating System: MacOS

**Comment by nihgwu** [comment]
what about to add a wrapper? borderRadius for Image on Android is not supported well

**Comment by magicismight** [comment]
@nihgwu 
I have tried that and failed.
The Image will overflow outside the wrapper, even if the wrapper had set the `overflow: hidden`

**Comment by ptomasroos** [comment]
I've verified this as well. Impossible to get a border radius on a gif with all tricks.

**Comment by skv-headless** [comment]
I found a way. I need to set `overlayColor` style. It described here https://facebook.github.io/react-native/docs/image.html#style

**Comment by magicismight** [comment]
Thanks! 💯

**Comment by foggy1** [comment]
This isn't working for me with an animated gif as of 0.42.  Here's the Image's current style props 

  gifStyle: {
    width: 63,
    height: 62,
    marginLeft: 13,
    borderRadius: 8,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
    overlayColor: '#8E55FF' ##this is the same as the background color
  }

**Comment by talentedman** [comment]
if you hava a clear background color 
    overlayColor can solve this question
but
   sometime   the background color is a image 
the  overlayColor dont work
