### ISSUE TITLE
[Image] Add scale support for base64-encoded image

### ISSUE THREAD

**Issue by cxfeng1** [facebook/react-native#1136]
Now TabBar component support base64-encoded data-uris for the icon,  but it has a image scale problem. If I use 3X image, it will become too large for the tab bar.

![2015-05-04 10 08 31](https://cloud.githubusercontent.com/assets/1625893/7454838/2cffd232-f2aa-11e4-83b2-57a64ba8700e.png)

And if I use 1X image, it will become too fuzzy for the retina screen.

![2015-05-04 10 10 39](https://cloud.githubusercontent.com/assets/1625893/7454878/75e62276-f2aa-11e4-9bd9-167f75cf93ad.png)

The correct way should be like this:

![2015-05-04 10 17 43](https://cloud.githubusercontent.com/assets/1625893/7455048/9944708c-f2ab-11e4-80bc-6f787a52b694.png)

Maybe UIImage converter should support scale for base64-encoded image ,   let js tell the native what scale the image is, or just use 3X image and make the scale 3.0.

**Comment by vjeux** [comment]
Thanks for the very detailed issue! I think what needs to be done here is not to tell whether the image is 3x or 1x but what the scale independent size of the image should be.

**Comment by cxfeng1** [comment]
Any news about this?

**Comment by crysfel** [comment]
Same problem here, any work around?

**Comment by brentvatne** [comment]
@cxfeng1 @crysfel  - could either of you take a crack at this and submit a PR?

**Comment by cxfeng1** [comment]
@vjeux Since RCTTabBarItem uses UITabBarItem which is not able to set custom UIImageView，so you can not tell what size and content mode of the image should be. So the immediate solution may be to add scale support for base64-encoded image.

**Comment by cxfeng1** [comment]
@frantic  Thanks for the merging, this issue will be closed.
