### ISSUE TITLE
[Docs] Is Set, Map, WeakSet, WeakMap Available

### ISSUE THREAD

**Issue by jacobp100** [facebook/react-native#11368]
It seems like some of these are used in React Native—sometimes by `require('Map')`, sometimes not.

Are these available, and if so, they’ll need to be added to [JavaScript Environment)(https://facebook.github.io/react-native/docs/javascript-environment.html)—which I’m happy to do if I get confirmation.

**Comment by ide** [comment]
They're sometimes available and sometimes not because it depends if the underlying JSC version supports them. Currently on Android we use a version of JSC that is close to iOS 8's. So whatever iOS has supported at each of its releases is what we support.

**Comment by christopherdro** [comment]
@facebook-github-bot answered

**Comment by skovhus** [comment]
Note that you can polyfill these using https://github.com/zloirock/core-js

This solves my issue with some Android devices that are missing es6 features like `weakmap`:
`import 'core-js/es6'`
