### ISSUE TITLE
Error when react-native link installing fbsdk

### ISSUE THREAD

**Issue by DeDuckProject** [facebook/react-native#11375]
### Description

I tried install FBSDK using react-native link like here, and got this:
(Android was ok, ios not)...
```

rnpm-install info Android module react-native-fbsdk is already linked 
rnpm-install info Linking react-native-fbsdk ios dependency 
rnpm-install ERR! It seems something went wrong while linking. Error: buildSettings.LIBRARY_SEARCH_PATHS.push is not a function 
Please file an issue here: https://github.com/facebook/react-native/issues 

buildSettings.LIBRARY_SEARCH_PATHS.push is not a function

```

### Reproduction
above

### Solution

Don't know. its good if there will be a manual installation guide for FBSDK-ios, the manual ios trouble-shooting here https://github.com/facebook/react-native-fbsdk doesn't suffice...
### Additional Information

* React Native version: 0.38 / 0.34 (happened on both
* Platform: ios
* Operating System: macOS

**Comment by estemilia** [comment]
same here.
i use react-native-cli:1.3.0 / react-native 0.38.0 / platform ios.

i try to debug link function,
react-native/local-cli/link/link.js
 
...and find function stuck at 
react-native/local-cli/link/ios/registerNativeModule.js L39

project.addStaticLibrary(product, {
 target: project.getFirstTarget().uuid,
}); 

<react-native link log>
 rnpm-install info Android module react-native-image-crop-picker is already linked
 rnpm-install info Linking react-native-image-crop-picker ios dependency
 rnpm-install info 1
 rnpm-install info 2 product : libimageCropPicker.a + uuid : 8A43B34C19582D9100D9CB07

 rnpm-install ERR! It seems something went wrong while linking. Error: buildSettings.LIBRARY_SEARCH_PATHS.push is not a function
 Please file an issue here: https://github.com/facebook/react-native/issues

 buildSettings.LIBRARY_SEARCH_PATHS.push is not a function

**Comment by redpandatronicsuk** [comment]
Thanks @estemilia ! I think the problem is that the RN linking tool expects `LIBRARY_SEARCH_PATH` to be of type array, not string. So rather that removing all `LIBRARY_SEARCH_PATH="..."`, you can also change it to: `LIBRARY_SEARCH_PATH=("...")`, i.e. add () around the ".."

**Comment by ifalldev** [comment]
I tried both solutions, but transforming `LIBRARY_SEARCH_PATH` in a array _did not_ fix.

Instead I removed them all. Then when I ran `react-native link` it created a fresh new `LIBRARY_SEARCH_PATH` parameters.

In my case `LIBRARY_SEARCH_PATH` was empty so I could do that.

**Comment by msdark** [comment]
Looks like the issue is that this file `node_modules/react-native-fbsdk/ios/ios.xcodeproj` have an old version structure (XML) (react-native-fbsdk 0.6.1) and `react-native link` command is expecting the new format.
