### ISSUE TITLE
Fetch JSON parsing error: Unexpected token

### ISSUE THREAD

**Issue by kevinnguy** [facebook/react-native#11378]
### Description

Calling `fetch` on Android is returning back `Unexpected token  in JSON at position 0`. I've seen previous Github issues in the past involving JSON parsing on Android and it looked like it's been solved but for some reason, I'm running into this issue. This is how I'm using `fetch`:

```
const post = (url, body, success, error) => {
  let headers = new Headers({
    "Content-Type": "application/json",
    "Accept-Encoding": "gzip, deflate",
    "Accept": "application/json",
  });

  let bodyString = JSON.stringify(body);

  fetch(url, {
    headers,
    body: bodyString,
    method: 'POST',
  })
  .then((response) => {
    if (response.ok) {
      return response.json();
    }

    error(response);
  })
  .then((json) => {
    if (json) {
      success(json);
    }
  })
}
```

The unexpected token is `\u001F` http://www.fileformat.info/info/unicode/char/1f/index.htm

### Additional Information

* React Native version: 0.39.0
* Platform: Android
* Operating System: MacOS

**Comment by kevinnguy** [comment]
However, this works on iOS

**Comment by kevinnguy** [comment]
Fixed this by removing these fields from my `Headers` object.

```
"Accept-Encoding": "gzip, deflate",
"Accept": "application/json",
```

**Comment by franleplant** [comment]
gzip was creating the problem for me too

**Comment by escobar5** [comment]
Anybody knows how to fix this, Im getting the same error, tried with and without the accept-encoding header, always get the same error.

**Comment by outaTiME** [comment]
Hi guys, 
I'm here with react-native 0.45 and I'm still having problems (on android only) with JSON, here my code:

```js
fetchData = async small => {
  const start_time = Date.now();
  try {
    let uri = 'https://www.dropbox.com/s/dmrfa9b2043fa2t/catalog.json?raw=1';
    let response = await fetch(uri);
    console.log(
      'Download remote data took: ' + (Date.now() - start_time) + 'ms.'
    );
    const data = await response.json();
    console.log('Items in catalog: ' + data.length);
    this.setState({
      appIsReady: true,
      data: data,
    });
  } catch (error) {
    console.error(error);
  }
};
```

Here the exception:

```
[SyntaxError: JSON Parse error: Unrecognized token '?']
```

Thanks !!!

**Comment by lavarajallu** [comment]
I am Getting like [SyntaxError: JSON Parse error: Unrecognized token '<']

**Comment by lavarajallu** [comment]
var updateString = "{\"first_name\":\""+this.state.updateAccountValues.FirstName+"\",\"last_name\":\""+this.state.updateAccountValues.LastName+"\",\"email\":\""+this.state.updateAccountValues.Email+"\", \"password\":\""+this.state.updateAccountValues.Password+"\", \"billing\": {\"phone\": \""+this.state.updateAccountValues.MobileNumber+"\"}}"
      console.log("string:"+JSON.stringify(updateString))
      fetch('XXXXXXXXXXXXXXXXXXXXX/wp-json/wc/v2/customers/XXXXXX?consumer_key=XXXXXXXXXXXXXXXXXXXXXXXX&consumer_secret=XXXXXXXXXXXXXXXXXXXXXXXXX',{
        method:'PUT',
        headers:{
          'Accept':'application/json',
          'Content-Type':'application/json'
        },
        body:JSON.stringify(updateString)
      }).then((response)=>response.json()).then((responseData)=>{
            alert("Response:"+JSON.stringify(responseData))
            if(responseData.data.status == 404){
                Alert.alert("KOOPI", responseData.message)
              }
         }).catch((err)=>{
                          alert("err:"+JSON.stringify(err))
                        })

**Comment by guillermolpz** [comment]
Hi, I have this problem **JSON parser error: unrecognized token '<'**  in react native. my code is as follows.
`fetch('http://192.168.0.103:3000/dataCard',{`
            `method: 'POST',`
            `headers: {`
               ` 'Accept': 'application/json',`
               ` 'Content-Type': 'application/json'`
           ` }, `
               ` body: JSON.stringify({`
             `  username: this.state.username,`
               ` })`
        `})`
       ` .then((response)=> response.json())`
        `.then((res)=>{`
            `if(res.success === true){`
             `   var usercard = res.message;`
              `  this.setState({`
               `     tarjetas: usercard`
                `});`
           ` }else{`
            `    Alert.alert(`
             `       'Ha ocurrido un problema',`
              `      res.message,`
               ` );`
            `}`
        `})`
        `.done();`
    `}`
tomar encuenta que la respuesta de message es una cadena ya en archivo JSON consultada desde mysql, pero no enteiendo por que da este error

**Comment by CristianUbp** [comment]
@guillermolpz Tengo el mismo problema ya pudiste solucionarlo?

**Comment by JoshYuJump** [comment]
Same issue in `React Native 0.45.1`

**Comment by hellozhangran** [comment]
same issue in 
React Native 0.46.4 
iOS

**Comment by niices** [comment]
Same issue in React Native 0.45.1

**Comment by Ilario17** [comment]
Same issue in React Native 0.52.0 on Android

**Comment by atturnbull** [comment]
My team and I figured out a dissatisfactory workaround. We now have platform-specific encoding, as gzip, or deflate don't appear to work on Android. We've resorted to sending our data uncompressed to our Android platform, and preserving the normal encoding for iOS. I'd really like to see a fix to this, because it's making the API calls take up to 3 times as long.
