### ISSUE TITLE
React-native app,react-native run-ios,tips: doesn't work ":CFBundleIdentifier", Does Not Exist

### ISSUE THREAD

**Issue by yelongfei2008** [facebook/react-native#11382]
React-native app,react-native run-ios,tips: doesn't work ":CFBundleIdentifier", Does Not Exist?

The following build commands failed:

	CompileC /Users/james-ye/ReactNative_workPlace/hxjb_reactnative/ios/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64/RCTPlatform.o Base/RCTPlatform.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/hxjb_reactnative.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/hxjb_reactnative.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

What should I do？

**Comment by yelongfei2008** [comment]
I do have CFBundleIdentifier in the Info.plist as:

<key>CFBundleIdentifier</key>
<string>org.reactjs.native.example.$(PRODUCT_NAME:rfc1034identifier)</string>

I also tried：
Go to File -> Project settings
Click the Advanced button
Select "Custom" and select "Relative to Workspace" in the pull down
click done, done 

But it's no use.

**Comment by jiawang1** [comment]
your build process failed in RCTPlatform.m , seems the same with [11265](https://github.com/facebook/react-native/issues/11265).

you can check that one, hope can help.

**Comment by xudeheng** [comment]
I met this one issue too.

**Comment by xudeheng** [comment]
Does RN work well wieth xcworkspace ?

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.

**Comment by hramos** [comment]
Duplicate of #14423
