### ISSUE TITLE
 Possible Unhandled Promise Rejection (id: 0):

### ISSUE THREAD

**Issue by yianyang** [facebook/react-native#11385]
Possible Unhandled Promise Rejection (id: 0):
	Something went wrong on api server.
	http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:70413:16
	tryCallOne@http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:30445:10
	http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:30531:19
	callTimer@http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:7666:9
	callImmediatesPass@http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:7770:28
	callImmediates@http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:7785:43
	guard@http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:7307:3
	__callImmediates@http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:7475:6
	http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:7370:23
	guard@http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:7307:3
	callFunctionReturnFlushedQueue@http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:7368:6
	callFunctionReturnFlushedQueue@[native code]

when i do fetch post return this error, but fetch get work well, someone can help me?

**Comment by Eric-Andrade** [comment]
I've the same error, I'm using Exponent XDE and when I try to connect to my Node API from my iPad, it shows me the error. I've the correct localhost path in my fetch :/﻿
