### ISSUE TITLE
react-native init AwesomeProject SyntaxError :

### ISSUE THREAD

**Issue by MoonTahoe** [facebook/react-native#11384]
`react-native init AwesomeProject` no longer works for me. It did just a few hours ago. I am working on a macbook pro and I have tried:

- Restarting
- Removing and Reinstalling `react-native-cli`
- Installing Yarn
- Different node js versions with `nvm`

I always get the exact same error:

```
Last login: Thu Dec  8 17:07:25 on ttys000
192.168.0.104
javac 1.8.0_111
node version v6.9.2
npm version 3.10.9

~ => cd documents
documents => react-native init AwesomeProject
This will walk you through creating a new React Native project in /Users/alexbanks/Documents/AwesomeProject
Using yarn v0.17.10
Installing react-native...
/Users/alexbanks/Documents/AwesomeProject/node_modules/react-native/local-cli/util/Config.js:43
  cwd: string,
     ^
SyntaxError: Unexpected token :
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at loader (/Users/alexbanks/Documents/AwesomeProject/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/alexbanks/Documents/AwesomeProject/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/alexbanks/Documents/AwesomeProject/node_modules/react-native/local-cli/cliEntry.js:13:16)
```

**Comment by pzenger** [comment]
👍   Running into the same error.  Glad I'm not the only one.

**Comment by jiawang1** [comment]
face the same error with react native 0.39.1. seems caused by the syntax of 
const Config = {
  get(
    **cwd: string,**
    defaultConfig?: ConfigT | null,
    pathToConfig?: string | null,
  ): ConfigT {
    let baseConfig;
    // Handle the legacy code path where pathToConfig is unspecified
...........
inside config.js.
 looks like typescript...

**Comment by bruzenak** [comment]
Yep, I'm getting this as well, for basically any run of the react-native cli for a pre-existing project. Started with 0.39.

**Comment by matthewconstantine** [comment]
What was the last working version?

**Comment by iamtommcc** [comment]
I am also experiencing this issue after trying to upgrade a 0.35.0 project. 

0.38.0 appears to be the last working version. 0.39.0 and 0.39.1 both fail whenever trying to run any `react-native` CLI scripts. 

Tried switching between multiple different versions of `react-native-cli` to no avail.

**Comment by noprom** [comment]
Hi, I got the same error, but before it was ok.
Here is my trace error:
```
➜  Pro react-native init RNGank
This will walk you through creating a new React Native project in /Users/noprom/Documents/Dev/ReactNative/Pro/RNGank
Installing react-native from npm...
Consider installing yarn to make this faster: https://yarnpkg.com



/Users/noprom/Documents/Dev/ReactNative/Pro/RNGank/node_modules/react-native/local-cli/util/Config.js:43
  cwd: string,
     ^
SyntaxError: Unexpected token :
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at loader (/Users/noprom/Documents/Dev/ReactNative/Pro/RNGank/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/noprom/Documents/Dev/ReactNative/Pro/RNGank/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/noprom/Documents/Dev/ReactNative/Pro/RNGank/node_modules/react-native/local-cli/cliEntry.js:13:16)
```
My react-native version:
```
➜  Pro react-native -v
react-native-cli: 1.2.0
react-native: n/a - not inside a React Native project directory
```
My npm version:
```
➜  Pro npm version
{ npm: '3.10.9',
  ares: '1.10.1-DEV',
  cldr: '30.0.2',
  http_parser: '2.7.0',
  icu: '58.1',
  modules: '51',
  node: '7.2.1',
  openssl: '1.0.2j',
  tz: '2016g',
  unicode: '9.0',
  uv: '1.10.1',
  v8: '5.4.500.44',
  zlib: '1.2.8' }
```

**Comment by wee911** [comment]
same issue happended herer, i try proxy changes ,reinstall yarn , reinstall node.js, and nothing helps, seems like babel did`t transformed successful.

**Comment by rg1220** [comment]
+1
I received the same error as well.

**Comment by miho7031** [comment]
react-native init HelloWorld > Error
react-native init HelloWorld2 > No Error

:(

**Comment by gwmccull** [comment]
I was getting the same error.  I hit Cmd-D and clicked `Debug JS Remotely`.  The app refreshed and the syntax error was gone.

If I turn off remote debugging, the error returns.

**Comment by rg1220** [comment]
FYI - Until this gets resolved, you can use `rninit` (https://www.npmjs.com/package/rninit) to install using the previous version of react-native. This worked for me:
```rninit init mobile --source react-native@0.39.0```

**Comment by ddpdev** [comment]
me too. 
react-native 0.39.1 occured but solved    
1. package.json 
  "react": "15.3.2",
    "react-addons-shallow-compare": "15.3.2",
    "react-native": "0.38.0",
...
2. npm update
3. react-native -v 
react-native-cli: 1.3.0
react-native: 0.38.0
4. react-native run-ios

** BUILD SUCCEEDED **

...

**Comment by amin168** [comment]
+1，me too
react-native: 0.39.0 and 0.39.1 error
react-native: 0.38.0 is work

**Comment by namKolo** [comment]
I have the same issue with `react-native:  0.39.1`
<img width="391" alt="screen shot 2016-12-09 at 1 50 45 pm" src="https://cloud.githubusercontent.com/assets/16164170/21040726/31e9eca6-be19-11e6-8706-2c9c7e40c64d.png">

**Comment by sunnylqm** [comment]
fallback to 0.38 to resolve this.
react-native init MyProject --version 0.38.0

ping @grabbou

**Comment by riyanpratama** [comment]
On the same boat as @namKolo 
`react-native-cli: 1.3.0
react-native: 0.39.1`

**Comment by namKolo** [comment]
@riyanpratama  You can roll back to version 0.38.0 as @sunnylqm  said. It works for me

**Comment by riyanpratama** [comment]
@namKolo sadly, still had the same problem here.

**Comment by namKolo** [comment]
@riyanpratama  sorry it should be 0.38.1. 
![image](https://cloud.githubusercontent.com/assets/16164170/21044894/a69116da-be30-11e6-83bb-01c265e0d7fd.png)

**Comment by riyanpratama** [comment]
@namKolo created with `react-native init fukBS --version 0.38.1` and still got the same error.
![screen shot 2016-12-09 at 5 04 38 pm](https://cloud.githubusercontent.com/assets/4180343/21045163/c6a0dd74-be31-11e6-8cd2-ec6f6f7cf204.png)

**Comment by namKolo** [comment]
@riyanpratama  Please run `npm uninstall react-native` then `npm i react-native@0.38` 
I hope it will help you. But it is just a trick. Hope the bug wil be fixed soon !

**Comment by kumarryogeshh** [comment]
@namKolo The trick worked for me 👍

**Comment by MoonTahoe** [comment]
I just tried `react-native init AwesomeProject` again, without the trick... and it worked. I was able to create and run the project on both ios and android.

**Comment by noprom** [comment]
```
react-native init RNGank --version 0.38.0
```

This works for me.

**Comment by CmST0us** [comment]
in file "node_modules/react-native/Libraries/Core/InitializeCore.js" 
delete 'use strict';

and it works

**Comment by rabidaudio** [comment]
Interestingly, I get this error on an iPhone 4s simulator running 8.1 (and as @gwmccull mentioned it goes away on remote debugging), but not on an iPhone 6 simulator running 10

**Comment by damusnet** [comment]
@facebook-github-bot duplicate #11389
