### ISSUE TITLE
How do you disable scrollview vignettes for android?

### ISSUE THREAD

**Issue by julesmoretti** [facebook/react-native#11381]
Is there a way to disable scrollview's vignette that appears when hitting/pushing against the end of a scroll in react-native?

![screen shot 2016-12-08 at 3 42 49 pm](https://cloud.githubusercontent.com/assets/744300/21032294/7893ab90-bd5d-11e6-8c8e-3c8422410f10.png)

Thank you.

**Comment by hey99xx** [comment]
I believe this pull request https://github.com/facebook/react-native/pull/10905 will allow you to customize this behavior on Android.

What it basically takes is calling https://developer.android.com/reference/android/widget/ScrollView.html#setOverScrollMode(int) on the native side.

If you want this app-wide and not for a single scroll view, you might be able to also edit your AndroidManifest.xml file with this code http://stackoverflow.com/a/12639840 I didn't personally try it though.

**Comment by julesmoretti** [comment]
@hey99xx - #10905 does indeed look like what I am looking for. Looking forward to this integration :)

Thank you!

**Comment by Abzalbek** [comment]
if someone alive here, i am struggling with espresso test, and i need to create infrastructure for framework with ability to never overscrolling , just had a look at the code , and lost,  any clarification would be perfect for me . (hope this is gonna work) thanks
