### ISSUE TITLE
NavigationBar shows different style on Android and IOS

### ISSUE THREAD

**Issue by Zhu-Arthur** [facebook/react-native#11387]
I found navigationBar on android present different style compare to ios.(the title did not display on the middle of sceen)

I think the current android style of navigationBar's Title is more likely to design for BreadcrumbNavigationBar, so i removed `marginLeft` and changed `alignItems` to center.

I started a PR(https://github.com/facebook/react-native/pull/11318) but get some problem with circleci, i must modify the `circle.yml` to pass the test and i don't know whether should i modify it.

**Comment by nihgwu** [comment]
That's not a bug, it's just following the design specs, they have the different height too.
You can read the source code, there are different styles for iOS and Android platforms, but you can customize a NavigationBar to use a unified style

**Comment by alvaromb** [comment]
This should be the default behaviour @Zhu-Arthur, both platforms have different HIG.

**Comment by Zhu-Arthur** [comment]
Thanks for @nihgwu @alvaromb , i just thought the title should be showed on the middle of the screen.
It seems like i misunderstand the default design.
Anyway, thanks a lot for you two, again.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/navigationbar-shows-different-style-on-android-and-ios
