### ISSUE TITLE
Unhandled JS Exception: TypeError

### ISSUE THREAD

**Issue by sscaff1** [facebook/react-native#11396]
Hi, I just started a new project and I'm getting the following error. The project builds successfully - it's just this error.
<img width="373" alt="screen shot 2016-12-10 at 7 12 39 am" src="https://cloud.githubusercontent.com/assets/1554424/21073594/4f91d09a-bea8-11e6-8b74-5c17b9ddd4eb.png">

I created the project using the CLI. Below is my .babelrc and my package.json. Using RN 0.39. 

```
{
  "presets": ["react-native", "react-native-stage-0", "react-native-stage-0/decorator-support"]
}
```

```
{
  "name": "whateverProject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "15.4.1",
    "react-native": "0.39.0",
    "react-native-meteor": "^1.0.2",
    "react-native-scrollable-tab-view": "^0.7.0",
    "react-native-vector-icons": "^3.0.0"
  },
  "devDependencies": {
    "babel-jest": "17.0.2",
    "babel-preset-react-native": "1.9.0",
    "babel-preset-react-native-stage-0": "^1.0.1",
    "eslint": "^3.11.1",
    "eslint-config-airbnb": "^13.0.0",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-jsx-a11y": "^2.2.3",
    "eslint-plugin-react": "^6.8.0",
    "eslint-plugin-react-native": "^2.2.0",
    "jest": "17.0.3",
    "react-test-renderer": "15.4.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

I've tried cleaning my cache, dropping and reinstalling my node modules, and clearing watchman with no success. My app is just rendering the default screen currently.

**Comment by crobinson42** [comment]
Try removing `react-native-stage-0` since you're using the decorator instead (see https://github.com/skevy/babel-preset-react-native-stage-0/blob/master/decorator-support.js)

```
{
  "presets": ["react-native", "react-native-stage-0/decorator-support"]
}
```

**Comment by sscaff1** [comment]
I end up with the same error. I dropped my node modules, cleaned my cache, and cleared watchman to no avail.

**Comment by sscaff1** [comment]
I think the issue may have been with yarn. When I initially set up the project, I did it with yarn installed and that's what installed all of my dependencies. I uninstalled yarn have the exact same babel setup and now everything works under a different repo. Very strange but it's resolved.
