### ISSUE TITLE
setInterval and requestAnimationFrame do not work when scheme set to release

### ISSUE THREAD

**Issue by MiLeung** [facebook/react-native#11399]
version: 0.39

However, setInterval and requestAnimationFrame do work when in debug mode.

The function I am trying to repeatedly call is a redux action.

**Comment by EricPKerr** [comment]
@MiLeung I am experiencing a similar issue, but unsure if it's the same issue (also happen to be calling a redux action, but don't know if/why that would be the problem). Have you resolved this issue or have any more info?

**Comment by MiLeung** [comment]
@EricPKerr Unfortunately, other projects have occupied my time to find a solution for this problem.

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
