### ISSUE TITLE
WebView Illegal Argument Exception Crash

### ISSUE THREAD

**Issue by reactipsum** [facebook/react-native#11401]
My app is presenting content in Webview.

But nowadays i have an issue. My app is crashing due to cookie value.  I have shared stacktrace on below.

### Fatal Exception: java.lang.IllegalArgumentException Unexpected char 0xdc at 343 in Cookie value
okhttp3.Headers$Builder.checkNameAndValue (Headers.java:320)
okhttp3.Headers$Builder.set (Headers.java:300)
okhttp3.Request$Builder.header (Request.java:163)
okhttp3.internal.http.BridgeInterceptor.intercept (BridgeInterceptor.java:86)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:92)
okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept (RetryAndFollowUpInterceptor.java:124)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:92)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:67)
okhttp3.RealCall.getResponseWithInterceptorChain (RealCall.java:170)
okhttp3.RealCall.access$100 (RealCall.java:33)
okhttp3.RealCall$AsyncCall.execute (RealCall.java:120)
okhttp3.internal.NamedRunnable.run (NamedRunnable.java:32)

**Comment by JayElPo** [comment]
+1

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/webview-illegal-argument-exception-crash
