### ISSUE TITLE
Notification using eventemitter native to react-native

### ISSUE THREAD

**Issue by harish220** [facebook/react-native#11407]
*** Assertion failure in -[RCTEventEmitter sendEventWithName:body:](), /---/node_modules/react-native/React/Modules/RCTEventEmitter.m:42
 *** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSInternalInconsistencyException> bridge is not set. This is probably because you've explicitly synthesized the bridge in NativeEventBridge, even though it's inherited from RCTEventEmitter.

Am getting above log in Xcode and and am unable to connect js file from native ios.
Below is my native code:
RCT_EXPORT_MODULE();

- (NSArray<NSString *> *)supportedEvents {
  return @[@"Complete"];
}

- (void)videoComplete:(NSString *)time {
  [self sendEventWithName:@"Complete" body:@"test"];
}

**Comment by harish220** [comment]
Please can you help me fixing this issue...

**Comment by q858333** [comment]
resolve a problem？？？ please tell me

**Comment by stlemon** [comment]
@harish220 how resolve this problem?  please tell me . thank you very much!

**Comment by q858333** [comment]
use NSNotificationCenter

**Comment by q858333** [comment]
@stlemon

**Comment by stlemon** [comment]
@q858333 can you show me some codes about it ?
