### ISSUE TITLE
[cli] Ability to specify pre/post-link global hooks

### ISSUE THREAD

**Issue by grabbou** [facebook/react-native#11405]
For now, the `pre/post` link hooks are plugin specific. That means a plugin can specify an arbitrary code to run after its being linked (`postlink/prelink`). 

What we want is the ability to define it on a project level, so that it gets executed anytime `link` is run.

Setup:
```json
{
  "rnpm": {
     "commands": {
       "postlink": ""
    }
  }
}
```
which is exactly what a plugin can specify.

A simple use-case for that is you want to perform a custom tweak to your `AppDelegate.m` every time new dependency is added.

CC: @brentvatne @satya164

**Comment by brentvatne** [comment]
Sounds good to me, cc @jesseruder

**Comment by jesseruder** [comment]
Would be nice if the new dependency name was passed into the postlink command as an env var @grabbou

**Comment by Kureev** [comment]
👍

**Comment by grabbou** [comment]
@jesseruder good idea. Should be an array since `react-native link` can link multiple projects at once (when name is not passed explicitly).

**Comment by jack668000** [comment]
unbelievable

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
