### ISSUE TITLE
undefine is not an object (evaluation 'RNDeviceInfo.systemManufacturer')

### ISSUE THREAD

**Issue by jrmcdona** [facebook/react-native#11409]
### Description

All I have done here is:
react-native init myProject
cd myProject
react-native run-ios

I have done before and never seen this type of error.

* React Native version: 0.39
* Platform: ios
* Operating System: MacOS El Capitan

<img width="276" alt="screen shot 2016-12-11 at 3 19 38 pm" src="https://cloud.githubusercontent.com/assets/4327773/21083681/8f423f68-bfbb-11e6-977e-72436a53400a.png">

Thanks

**Comment by jrmcdona** [comment]
I have also tried this in xcode beta 8.1 also, same issue.   I have also tried this in ios 7 simulator, same thing.

**Comment by jrmcdona** [comment]
Rebooted the MAC and it is working now.

**Comment by suhabaobaid** [comment]
I believe this issue has to do the react-native not linked to the device info. I had this error and ran the command in the terminal `react-native link`

**Comment by MbF-Sathya** [comment]
no its not also working after react-native link step done

**Comment by Unforgiven-wanda** [comment]
Running into this issue when using an emulator (namely Genymotion)
Has this been solved?
