### ISSUE TITLE
getting started windows instructions missing `npm install -g react-native-cli`

### ISSUE THREAD

**Issue by 1mike12** [facebook/react-native#11414]
I'm not sure if something changed but I came back to react native on a new computer and trying to install and couldn't figure out where the cli installation came into play. 

Right now it only says "Node.js comes with npm, which lets you install the React Native command line interface."

Whereas the mac version is complete: 

Node.js comes with npm, which lets you install the React Native command line interface.

Run the following command in a Terminal:

npm install -g react-native-cli
If you get a permission error, try using sudo: sudo npm install -g react-native-cli.
If you get an error like Cannot find module 'npmlog', try installing npm directly: curl -0 -L http://npmjs.org/install.sh | sudo sh.

**Comment by 1mike12** [comment]
Also missing on the linux instructions.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/getting-started-windows-instructions-missing-npm-install--g-react-native-cli
