### ISSUE TITLE
onResponderRelease not working on Android

### ISSUE THREAD

**Issue by Piwaii** [facebook/react-native#11418]
### Description

onResponderRelease is not triggered in a ScrollView on Android, it works fine on IOS.

### Reproduction

Just bind something on the 'onResponderRelease', it will work on IOS, not on Android
Exemple here : https://rnplay.org/apps/2rkKsA

### Additional Information

* Tested on React Native version: 0.39
* Platform: ok on IOS, fails on Android

**Comment by Piwaii** [comment]
for information, this issue reopens this one : https://github.com/facebook/react-native/issues/8177

**Comment by shahen94** [comment]
https://github.com/facebook/react-native/issues/9447

**Comment by noobG** [comment]
Same problem here. I'm getting the onResponderGrant event just fine, but the onPanResponderRelease doesn't fire (at least not consistently; if I do fast jittery movements the event sometimes fires).

**Comment by alxyuu** [comment]
if you use `onShouldBlockNativeResponder={() => false}` the release will be triggered

**Comment by yoohoogun114** [comment]
+ 1 same here

**Comment by eggytronixx** [comment]
Has anyone found a work around yet?

**Comment by scotbond** [comment]
Should intercept the touch event before release can be intercepted.
Try this:

```
onStartShouldSetResponder={() => true}
onResponderRelease={() => this._onRowTap(prop)}
```

**Comment by zachrnolan** [comment]
+1

@scotbond tried setting onStartShouldSetResponder, but didn't fix it.

**Comment by t-benze** [comment]
same +1. I ended up using the following to keep track

>onScrollEndDrag={this.handleStartDragging}
>onScrollBeginDrag={this.handleEndDragging}

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/onresponderrelease-not-working-on-android

**Comment by JaxGit** [comment]
same with react-native@0.47.2
it seems that when swiping, onResponderGrant is fired, onResponderMove and onResponderRelease could only be tracked within a tiny distance. 
After swiping for a certain distance, onResponderMove stops first, then onResponderRelease will never be fired when release.

**Comment by AugustoAleGon** [comment]
This is still not working!

**Comment by jukben** [comment]
Same issue 0.49.3 :(

**Comment by jayasme** [comment]
Still not fixed on 0.51.0
When you guys notice this issue?

**Comment by kkkelicheng** [comment]
I want to use this feature to solve the problem that mapView inside scrollview .
I use onResponderRelease well on iOS,
but on android , onResponderRelease  sometimes not fire.
My RN version  0.44

**Comment by kkkelicheng** [comment]
here is some code I used , may help someone whose MapView in Scrollview.
my page rootView is scrollview , I use custom view contain mapView. then I put custom view in scrollview.

```
// In custom view 

// add some touch event
    @Override
    public boolean onInterceptTouchEvent(MotionEvent ev) {
        if (ev.getAction() == MotionEvent.ACTION_UP || ev.getAction() == MotionEvent.ACTION_CANCEL) {
            if(mySv != null){
                mySv.requestDisallowInterceptTouchEvent(false);
            }
        }
        if(ev.getAction() == MotionEvent.ACTION_DOWN){
            if(mySv != null){
                mySv.requestDisallowInterceptTouchEvent(true);
            }
        }
        return false;
    }

@Override
    public boolean onTouchEvent(MotionEvent event) {
        return true;
    }

// get ScrollView
    public ScrollView getParentView(ViewGroup view){
        ViewParent parent = view.getParent();
        if(parent == null){
            return null;
        }
        if(parent instanceof ScrollView){
            ScrollView sv = (ScrollView)parent;
            return sv;
        }
        else {
            if(parent instanceof ViewGroup){
                ViewGroup forceView = (ViewGroup)parent;
                return getParentView(forceView);
            }
            else {
                return null;
            }
        }
    }

//when init ，find out scrollview
 public CustomView(Context context) {
        // .........
        final CustomView thisView = this;
        this.getViewTreeObserver().addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
            @Override
            public void onGlobalLayout() {
                Log.w("getViewTreeObserver","layout donw");
                thisView.getViewTreeObserver()
                        .removeOnGlobalLayoutListener(this);
                ScrollView sv = thisView.getParentView(thisView);
                if(sv != null){
                    thisView.mySv = sv;
                }
            }
        });

    }
```

then In ReactNative , You need not handle touch event to block scollView scoll, otherwise It may cause error.
```
<ScrollView>
    <View style={styles.mapContainer}>
                            <MapView
                                style={styles.mapStyle}
                                ref={this.mapRef}
                            />
      </View>
</ScrollView>
```
