### ISSUE TITLE
`init` unhelpfully fails when run in an existing project directory

### ISSUE THREAD

**Issue by fcanas** [facebook/react-native#1141]
To reproduce:

From a directory that is set up as a React-Native project, or simply has content in `/node_modeuls/react-native`, run `react-native init NewProject`

Expected behavior:

Either 
1. create a new nested project in the present directory, *or*
2. inform the user that a new project cannot be created in the current directory

Observed Behavior:

```
$ react-native init AwesomeNewThing
Command `init` unrecognized
Usage: react-native <command>

Commands:
  start: starts the webserver
  install: installs npm react components
  bundle: builds the javascript bundle for offline use
$
```

I found this behavior particularly frustrating because the current directory didn't contain a functional React Native project, but rather a half-way created one that failed because I didn't have the correct versions of node. It appeared to me that I had yet another incorrectly configured environment for React Native development.

**Comment by frantic** [comment]
Thanks for reporting!
