### ISSUE TITLE
namedOrientationDidChange not supported on iOS

### ISSUE THREAD

**Issue by TLenahan** [facebook/react-native#11429]
### Description

Currently there is no implementation of the namedOrientationDidChange event for iOS. There is also an issue with Dimensions not correctly updating on rotation which there is a [Pull Request](https://github.com/facebook/react-native/pull/11181) out for. I am looking to be able to subscribe to the namedOrientationDidChange event on both platforms.

### Reproduction

Although I am unable to rotate the Simulator/Emulator on RNPlay, i have created an example app to demonstrate how I am using the namedOrientationDidChange event.
https://rnplay.org/apps/T7yq6A

### Solution

Will namedOrientationDidChange be implemented on the iOS side? Or is it suggested to use a third party library. I would prefer to not rely on a third party library if RN can provide a solution. 

### Additional Information

* React Native version: 0.39.0
* Platform: iOS
* Operating System: MacOS

**Comment by mroswald** [comment]
Are there any news on that? Did you check https://github.com/yamill/react-native-orientation ?

**Comment by idibidiart** [comment]
This needs fixing or we can't build universal apps with Expo...

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/namedorientationdidchange-not-supported-on-ios
