### ISSUE TITLE
View's onLayout not called for RN >= 0.37

### ISSUE THREAD

**Issue by peacechen** [facebook/react-native#11439]
### Description

Starting with RN 0.37 (possibly earlier), _onLayout_ is no longer firing for a custom expandable panel component.  I based the component off of [this article by Crysfel Villa](http://moduscreate.com/expanding-and-collapsing-elements-using-animations-in-react-native/).  See the Reproduction section for the JSX.

### Reproduction

```
    render(){
        return (
            <Animated.View
                style={[styles.container,{height: this.state.animation}]}>
                <View style={styles.titleContainer} onLayout={this._setMinHeight.bind(this)}>
                  <View style={styles.header}>{this.props.header}</View>
                  <TouchableHighlight
                      style={styles.button}
                      onPress={this.toggle.bind(this, true)}
                      underlayColor="#f1f1f1">
                      <Icon name={this.state.expanded? 'chevron-up': 'chevron-down'} size={30} color={this.props.buttonColor} />
                  </TouchableHighlight>
                </View>

                <View style={styles.body} onLayout={this._setContentHeight.bind(this)}>
                    {this.state.children}
                </View>

            </Animated.View>
        );
    }
```
__setMinHeight_ and __setContentHeight_ are never called.

### Solution

Tried the proposals in #10743 -- wrap content in a View with style flex:1.  Setting position:absolute is no good because the content doesn't place properly.
onLayout doesn't fire in either case.

### Additional Information

* React Native version: 0.39.2
* Platform: iOS
* Operating System: OSX 10.12 Sierra, XCode 8.1

**Comment by mschipperheyn** [comment]
Could you share the associated style definitions? One of the things I ran into is the changes that were made in how flex and flexgrow are processed that can lead to elements collapsing to zero height. Check the release notes of 0.36.

**Comment by peacechen** [comment]
Here's the stylesheet:

```
var styles = StyleSheet.create({
    container   : {
        backgroundColor: '#fff',
        margin:10,
        overflow:'hidden'
    },
    titleContainer : {
        flexDirection: 'row',
        alignItems:'center'
    },
    header       : {
        flex    : 1
    },
    button      : {
    },
    body        : {
        padding     : 10,
        paddingTop  : 0
    }
});
```

I'll take a look at RN 0.36's release notes again.  Didn't catch what changed the first time.

**Comment by lacker** [comment]
Does it ever fire? Based on your other issue, I am just wondering if the problem is really that the panel isn't going through layout.

**Comment by peacechen** [comment]
It never fires, even on first render.  Does Crysfel's github work for you using RN 0.39?

**Comment by kutyuit** [comment]
I get the same issue with [react-native-collapsible](https://github.com/oblador/react-native-collapsible) on React-Native 0.39.2

**Comment by nomoreboredom** [comment]
Adding  overflow: 'scroll' to parent container fixed the issue for me.

**Comment by ferbass** [comment]
@nomoreboredom thank you :)

**Comment by sudharsanmit** [comment]
Observed that it works with 0.41 straight. No workarounds needed.

**Comment by peacechen** [comment]
With RN 0.45.1, `onLayout` fires but the height always returns 0.  Bug?

**Comment by neerfri** [comment]
The problem could be the change in this commit: https://github.com/facebook/react-native/commit/d2723341864b92e7ad44e39aad2436cb1c9a3394

It changes the default `autoresizingMask` of `RCTRootView` to match that of a plain `UIView`.
This might be fixed by adding: `reactView.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;`. YMMV;
