### ISSUE TITLE
bundle fails on freshly initialized project

### ISSUE THREAD

**Issue by fcanas** [facebook/react-native#1143]
`bundle` fails when run on a freshly initialized project with no changes.

Steps to reproduce:

```
$ react-native init Base
...
$ cd Base/
$ react-native bundle
Building package...

/Users/fcanas/github/ReactNativeExperiments/Base/node_modules/react-native/node_modules/bluebird/js/main/promise.js:626
            throw e;
                  ^
Error: EMFILE, open '/Users/fcanas/github/ReactNativeExperiments/Base/node_modules/react-native/node_modules/react-tools/src/browser/ui/dom/ViewportMetrics.js'
```

Expected Results:

Not sure, as I've never gotten the `bundle` command to work, but I think I want to see a single `.js` file output suitable for providing to a React view in some sort of static fashion.

Actual results:
Error and no file output

Notes:
node v0.10.38
react-native-cli v1.4.28

**Comment by frantic** [comment]
Weird. See #1123 and #1096 for quickfix (update node)

**Comment by frantic** [comment]
Ok but the real problem is actually low ulimit :(
Run `ulimit -n 2560` from the terminal before `react-native bundle`. Fix coming

**Comment by fcanas** [comment]
Updating node works for me. I have no reason for running v0.10 other than that's what I ended up with after a long, blind, stumbling process of getting this up and running.

Thanks for your help!

**Comment by frantic** [comment]
Talked to @amasad - we are going to use something like graceful-fs in packager

**Comment by amasad** [comment]
This should be fixed now: see https://github.com/facebook/react-native/blob/07937620c0694afe016887df6a64e4d99e3426bb/packager/react-packager/index.js#L51-L62

reopen if it's still a problen
