### ISSUE TITLE
Undefined is not an object (evaluating 'dataSource.rowIdentities')

### ISSUE THREAD

**Issue by williamlk** [facebook/react-native#11436]
When I use ListView to show my data, a question occur to me. it throws Undefined is not an object (evaluating 'dataSource.rowIdentities'). Here is my code.

`    constructor(props) {
        super(props);
        this.handleChange = this.handleChangeFunc.bind(this);
        this._onCancel = this._onCancelFunc.bind(this);
        alert(21);
        var ds = new ListView.DataSource({ rowHasChanged: (oldRow, newRow) => oldRow !== newRow, });
        this.state = {
            textInputValue: '',
            dataSourse: ds.cloneWithRows(['row1', 'row2', 'row3']),
        };
    }
    ...
    render() {
        return (
                <ListView
                     dataSource={this.state.dataSource}

                     renderRow={(rowData) => <Text>{rowData}</Text>}
                   />
            </View>
        );
    }

`

**Comment by bdunn313** [comment]
@williamlk what was the resolution to this? I'm having the same issue

**Comment by bdunn313** [comment]
@williamlk not sure if it was the same for you, but it was a spelling error for me

```
<ListView
     datasource={this.statedatasource}
```

note the lack of capital `S` in `dataSource` `ListView` prop

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (61/60 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter01.reliabledns.org ([199.96.156.50]:43907)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1cHbhu-004H3E-0W
	for bunny@thumbmunkeys.com; Thu, 15 Dec 2016 19:28:47 +0000
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192] helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by filter01.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1cHbhs-000389-VP
	for bunny@thumbmunkeys.com; Thu, 15 Dec 2016 12:28:45 -0700
Date: Thu, 15 Dec 2016 11:28:44 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1481830124;
	bh=iIuFeD6Sdo5cOvDukKUnXlAEVCBgOi7orrDu3P/2jvA=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=lEhYtSzYnbvowqU6G/J2rWbVAi0bTDEbN2agT5B8TP8/B+giGLSSLba5qqQpFAPKZ
	 X2XXHJy+sxMPsa2CAg2WHaoFeIsBQeRnfCLcCFI0njQkbw6g5OpnjRaZTcyLHb164r
	 kijQzSH53ZjWcIp9XSveQAookFRcQQlUqoa5/X3Q=

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (64/60 (106%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter03.reliabledns.org ([69.175.33.179]:33604)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1cHbjM-004Hq8-6Y
	for bunny@thumbmunkeys.com; Thu, 15 Dec 2016 19:30:17 +0000
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193] helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by filter03.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1cHbjL-0007hS-Oe
	for bunny@thumbmunkeys.com; Thu, 15 Dec 2016 12:30:16 -0700
Date: Thu, 15 Dec 2016 11:30:10 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1481830215;
	bh=G4AQvv4vHxEYTfAUCKUtn3TjK2+ouc2wdyMavMAlA6A=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=kwbVzpizBagVCFeo231pft36Qt6gg3cd1qQ8uBtrSwxVFVRNmBiHXS35jK6YvFJyw
	 0tTDe2mSXTA95Jk3wIT2QvmjDafp4WBJPxPQ4ULwTmJKmdmb/9RSmdHefLtmjOsxYL
	 mIp1GQSmFQoT/ndUWVQa6/nx+7hF7qJWSOOe119k=

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (65/60 (108%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter03.reliabledns.org ([69.175.33.179]:33680)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1cHbjc-004I0v-GB
	for bunny@thumbmunkeys.com; Thu, 15 Dec 2016 19:30:33 +0000
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192] helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by filter03.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1cHbjc-0007kO-AY
	for bunny@thumbmunkeys.com; Thu, 15 Dec 2016 12:30:32 -0700
Date: Thu, 15 Dec 2016 11:30:29 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1481830231;
	bh=ahFe6yytxvoFfqFEZplHtn4wh0E/sWhUbcQX4z78Klo=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=eX1EsYF32jbLFnQDi2MqVQ0xuoXNFpC8ABa3HEcTC0Ybd4KDt4w63omsLxjCkfpYI
	 yADTCw0aAbf14a2VS7pna+ceWudPcSkFAd7fAzc7uVN+CWhZ0wBBFRoF1CQYHMcBWR
	 lX+n6ncg46E10CXAgu6qEhOEph7VnbTEVM8qOaqo=

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (66/60 (110%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter03.reliabledns.org ([69.175.33.179]:33700)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1cHbk1-004IDo-KK
	for bunny@thumbmunkeys.com; Thu, 15 Dec 2016 19:30:59 +0000
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198] helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by filter03.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1cHbk1-0007mh-9t
	for bunny@thumbmunkeys.com; Thu, 15 Dec 2016 12:30:58 -0700
Date: Thu, 15 Dec 2016 11:30:56 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1481830256;
	bh=Lds+LVeERdC9Qhr/Ay9Zb6jHH3u/UhULAlYQtKFx82I=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=uv5ha6vQX5jJkQ/wyrXtg901Q7fHqSgrWOxYixNMxVr4Xh6+M9WI8vmGiaOlyyZWR
	 5+sNChAVamTm/XA35VEbAI5STx3Tskiw3xTRUeWhghiM7njV9b/UbGq4agMoXBfy1Z
	 OBl+Zpuvbb+NTRpPxB/8ruu8yS0M79vj3rW+noow=

**Comment by williamlk** [comment]
@bdunn313    it was a spelling error for me too. 
this.state = {
textInputValue: '',
**dataSourse: ds.cloneWithRows(['row1', 'row2', 'row3']),**
};
}

should be 

this.state = {
textInputValue: '',
**dataSource: ds.cloneWithRows(['row1', 'row2', 'row3']),**
};
}
