### ISSUE TITLE
How to setState in AsyncStorage block with react native?

### ISSUE THREAD

**Issue by magic3584** [facebook/react-native#11435]
I want **setState** in **AsyncStorage** block but there is a error: **undefined is not an object(evaluating 'this.setState')**.

[http://stackoverflow.com/questions/41114460/how-to-setstate-in-asyncstorage-block-with-react-native](url)

**Comment by williamlk** [comment]
please show us your code

**Comment by williamlk** [comment]
I guess you did not use bind, if you invoke a function first you should use bind, in ES6 this does not ref to class instead ref to function, There are two solution to solve this issue.
`onPress={()=>{this.onClick();}}`
`onPress={this.onClick.bind(this)}`

**Comment by williamlk** [comment]
I guess you did not use bind, if you invoke a function first you should use bind, in ES6 this does not ref to class instead ref to function, There are two solution to solve this issue.
`onPress={()=>{this.onClick();}}`
`onPress={this.onClick.bind(this)}`

**Comment by magic3584** [comment]
It has been solved.[http://stackoverflow.com/a/41114902/4256995](url)
But thanks all the same.
