### ISSUE TITLE
[BackAndroid] RCTDeviceEventEmitter.addListener(DEVICE_BACK_EVENT) will not be invoked

### ISSUE THREAD

**Issue by Aaaaaashu** [facebook/react-native#11449]
### Description

Enter the application for the first time, everything is all right, as well as `RCTDeviceEventEmitter.addListener(DEVICE_BACK_EVENT)` is also work.  But by `BackAndroid` exit the application, back into the application again, `RCTDeviceEventEmitter.addListener(DEVICE_BACK_EVENT)` will not be invoked

### Reproduction

My code:
```js
constructor() {
  this.handleBackAndroid = this.handleBackAndroid.bind(this)
}

componentDidMount() {
  BackAndroid.addEventListener('hardwareBackPress', this.handleBackAndroid)
}

componentWillUnmount() {
  BackAndroid.removeEventListener('hardwareBackPress', this.handleBackAndroid)
}

handleBackAndroid() {
  const navigator = this.navigator
  if (navigator && navigator.getCurrentRoutes().length > 1) {
    navigator.pop()
    return true
  }

  if (this.lastBackPressed && this.lastBackPressed + 2000 >= Date.now()) {
    return false
  }

   this.lastBackPressed = Date.now()
   ToastAndroid.show('Again press to exit the application', ToastAndroid.SHORT)
   return true
 }
```

### Additional Information

* React Native version: [0.36]
* Platform: [Android]
* Operating System: [MacOS]

**Comment by AdamChrist** [comment]
@Aaaaaashu Hi,I\ had the same problem, how did you solve it?thank you

**Comment by Aaaaaashu** [comment]
@AdamChrist
This is my mistake. I remove the react native events listener in some code,
so result in the `BackAndroid `  failure.

AdamChrist <notifications@github.com>于2017年2月5日周日 下午3:59写道：
