### ISSUE TITLE
Can't find variable: React - React must be imported, even when not used

### ISSUE THREAD

**Issue by jamesaspence** [facebook/react-native#11448]
### Description

When attempting to run my app, if I do not import React AS WELL AS Component via `import React, {Component} from "react";`, I get an error: `Can't find variable: React`. Nothing within my module (is this case, index.ios.js) references React, short of Component (which I use to create my component of course), but it still throws the error.

I'm wondering if this is intentional, and why?

### Reproduction

1. Create new project w/ `react-native init test`
2. Open index.ios.js
3. Remove `React, ` from `import React, {Component} from "react";`
4. Run in simulator (using iOS simulator

### Solution

Preferably, I'd either like to have this not throw an error, or understand why exactly it does.

### Additional Information

* React Native version: 0.39.2 (1.0.0 CLI)
* Platform: iOS currently (have not tested android)
* Operating System: MacOS Sierra

**Comment by goshakkk** [comment]
You need to import `React` in every file that uses JSX. When you do `<Text>Something</Text>`, what actually happens is, this JSX is transformed to regular JS:

```javascript
React.createElement(Text, {}, 'Something')
```

You may find this article useful to understand how JSX works: https://facebook.github.io/react/docs/jsx-in-depth.html

**Comment by jamesaspence** [comment]
I see. No way for that to be auto-included as part of the compile step? It'd be nice if I could import just Component and have the compiler determine its own dependencies.

**Comment by goshakkk** [comment]
JSX is not a dependency of Component, and it can be customized on both per-file and project-wide basis what JSX is translated into (e.g. instead of `React.createElement` you can make it be `h` or `myElement` or anything); and the module bundler shouldn't know where that comes from.

Just don't forget to put `import React from 'react'` and you're gonna be cool.
