### ISSUE TITLE
Could not invoke HeadlessJsTaskSupport.notifyTaskFinished

### ISSUE THREAD

**Issue by JaneCheng00** [facebook/react-native#11447]
### Description

I want to use HeadlessJsTask for a prompt, but here is a mistake like "Could not invoke HeadlessJsTaskSupport.notifyTaskFinished".

### Additional Information

* React Native version: [0.36]
* Platform: [Android]
* Operating System: [Windows]

**Comment by JaneCheng00** [comment]
before “startHeadlessTask” in JS, you need to startservice, 
` @ReactMethod
    public void startService(){
        ReactApplicationContext reactApplicationContext = getReactApplicationContext();
        HeadlessJsTaskService.acquireWakeLockNow(reactApplicationContext);
        Intent service = new Intent(reactApplicationContext, MyTaskService.class);
        service.putExtra("key1", "value1");
        reactApplicationContext.startService(service);

    }`

**Comment by cosmith** [comment]
@facebook-github-bot close
