### ISSUE TITLE
Screen redraw problems / UI Collapse

### ISSUE THREAD

**Issue by mschipperheyn** [facebook/react-native#11441]
I'm on 0.39.2 (upgraded from 0.35) and since the upgrade I'm having screen redraw issues. It primarily seems to happen in lists with complex variable height elements. I use SGListView but have also verified this with the regular ListView.

The problem seems to manifest itself most but not always when the number of items in the list changes. It leads to elements looking garbled with pieces floating around in the wrong places and some heights collapsing to zero. I also sometimes see parts of the screen starting to flash constantly, seemingly trying to redraw. When this happens, there doesn't seem to be any other activity (such as actions being executed).

<img width="375" alt="screen shot 2016-12-13 at 14 24 02" src="https://cloud.githubusercontent.com/assets/384959/21148726/4f1eb4a8-c140-11e6-9bfa-d74c7eb1c506.png">

The upgrade I did of course, covers the change in the way flex box behaves (flex : 1 => flexGrow : 1) and I have dealt with a fair number of issues in this area. So I'm inclined to think it might be related to this. On the other hand, on first load, the items usually look normal (but not always). If a redraw of the screen is forced, for instance by doing a hot reload by saving a template, the screen seems to return to normal.

Some yellow box items and warnings I see are:
View #119 of type RCTView has a shadow set but cannot calculate shadow efficiently. Consider setting a background color to fix this, or apply the shadow to a more specific component.

Is there a way to track down the actual template based on this View id?

Warning: In next release empty section headers will be rendered. In this release you can use 'enableEmptySections' flag to render empty section headers.

**Comment by mschipperheyn** [comment]
I just went back to 0.38.1 and the problem is no longer reproducible (BTW, testing on iOS simulator). Just to be on the safe side, upgrade to 0.39.1, cleaned the cache and the problem is back again.

<img width="367" alt="screen shot 2016-12-13 at 15 38 21" src="https://cloud.githubusercontent.com/assets/384959/21151598/36f33408-c14a-11e6-863c-221c9053aa52.png">

**Comment by cyprusglobe** [comment]
https://github.com/facebook/react-native/commit/d63ba47b59e3261403800c1f741d979a089efb48 seems like this is at fault im pretty sure this landed in v38.0.0




here is the change log for 38.0.0

https://github.com/facebook/react-native/releases?after=v0.39.0

**Comment by oureta** [comment]
I encounter this problem on 0.39 but not on 0.38.1

**Comment by goodhyun** [comment]
We are also having this issue with `SwipeableListView` on 0.39.*
It redraws almost 10 times right after the first load, and even lost some items in it.

**Comment by carlosdelsol** [comment]
Same happens to me. When scrolling down a ListView all elements collapse. Only with 0.39.*

**Comment by mschipperheyn** [comment]
Glad I'm not alone! Any workarounds?

**Comment by mschipperheyn** [comment]
Made a screen gif from 0.38.1 where the problem occurs but seems to recover at the end of tha animation (somewhat, it reoccurs on scrolling). On 0.39.2, it doesn't recover. The poll on top executes a layout animation which seems to trigger the collapse.

![rn0 38 1](https://cloud.githubusercontent.com/assets/384959/21185003/148ebbb0-c1f6-11e6-9747-ce79fbac082d.gif)

**Comment by rneiss** [comment]
Seeing what I think is a similar bug -- also on 0.39.0 -- not present in 0.38.0. 

Content all initially loads properly -- in this case, clicking on the "more" button (which merely calls a function to change the state to show previously hidden content) causes the previously loaded content to disappear/collapse:

![img_2322](https://cloud.githubusercontent.com/assets/1596539/21196399/1ba53c2e-c1fd-11e6-934b-71b633170b3f.PNG)
![screen shot 2016-12-05 at 5 04 57 pm](https://cloud.githubusercontent.com/assets/1596539/21196405/1fff8d88-c1fd-11e6-91a8-cf367c635bad.png)

**Comment by mschipperheyn** [comment]
I have this problem from 0.38.1 onwards but not on 0.38

**Comment by goodhyun** [comment]
Aren't we having the same symptom on iOS ? The change in that commit only refers to .java ?

**Comment by sachinrekhi** [comment]
I'm seeing this frequent initial redraw issue as well with SwipeableListView only after upgrading React Native to 0.39.0. The rendering issue appears to be related to the rendering of the quick actions within the SwipeableListView in my case.

Any workarounds?

**Comment by mschipperheyn** [comment]
Yeah, I have only checked and experienced on ios but the change between 0.38.0 and 0.38.1, which seems the point of failure, I identified as this one. I might be wrong

**Comment by alexcurtis** [comment]
Can also confirm I am getting a flickering redraw with SwipeableListView on iOS simulator. Occurs on 0.39.2

**Comment by stinju** [comment]
If it helps, I resolved my instance of this issue by removing an inappropriate `flex: 1` in my row sub-container.  Most likely related to https://github.com/facebook/react-native/wiki/Breaking-Changes#039.

**Comment by sachinrekhi** [comment]
Thanks @stinju! I think you're spot on. I initially removed a bunch of unnecessary flex: 1 styles in the view hierarchy for my renderRow() implementation assuming it would resolve the issue as mentioned in the breaking changes release notes, but I still had the flickering issue.

However, I noticed that the implementation of SwipeableRow in SwipeableListView creates an outer <View/> above your own view hierarchy for renderRow and that had it's own flex: 1 style property set. Once I additionally removed that, the flickering appears to be removed.

Sounds like then the fix if you are experiencing the issue specifically with SwipeableListView requires modifying SwipeableRow to remove flex: 1 as well as any unnecessary flex: 1 in your own renderRow view hierarchy. @fred2028 is this something you might be able to help get fixed in SwipeableRow? Happy to contribute a PR to just remove the one line flex: 1, though would likely need support to get it through.

**Comment by sachinrekhi** [comment]
Just submitted a PR to resolve this issue specifically with folks using SwipeableListView. But main issue is definitely related to breaking changes introduced and documented in 0.39 here: https://github.com/facebook/react-native/wiki/Breaking-Changes#039. If you're usin

For others seeing the issue but not using SwipeableListView, as @stinju suggested, you need to remove all the unnecessary flex: 1 as suggested in the breaking changes documentation.

**Comment by mschipperheyn** [comment]
Given that all all containers are flexbox by default, I wonder what is the use of flex : 1 at this point? Would it make sense to replace all flex : 1 with flexGrow : 1?

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
