### ISSUE TITLE
No such file or directory libRCTAnimation.a after using react-native-git-upgrade

### ISSUE THREAD

**Issue by coderdave** [facebook/react-native#11440]
### Description

I'm upgrading react-native from `0.25.1` to `0.39.2` using the handy `react-native-git-upgrade`.

But when I go to run the project from xcode, I get the error:
`clang: error: no such file or directory: '/Users/davids/Library/Developer/Xcode/DerivedData/MyApp-bqzkklqamxyjkzckmlgptszoxwff/Build/Products/Debug-iphonesimulator/libRCTAnimation.a'`

How do I fix this?

### Reproduction

Upgrade react-native from `0.25.1` to `0.39.2` and run the project from xcode.

### Solution

No idea.

### Additional Information

* React Native version: 0.25.1 (originally)
* Platform: iOS
* Operating System: MacOS

**Comment by goshakkk** [comment]
A lot of Xcode related things can be fixed by

1. doing Product → Clean
2. File → Project/Workspace Settings, clicking that arrow icon next to DerivedData and deleting the folder in Finder
3. after the previous, restart Xcode and try building again

**Comment by ncuillery** [comment]
0.25.1 👉 0.39.2 is a pretty huge gap. Even if `react-native-git-upgrade` allows upgrade from any version to any version, I'd recommend you to go incrementally.

Upgrade to version X, verify your app is working, upgrade to version Y, verify your app is working, and so on...
