### ISSUE TITLE
Cannot configure react native app to use a local packager that is running on a non-default port

### ISSUE THREAD

**Issue by eladhayun** [facebook/react-native#11458]
### Description
Tried running the react native sample project (AwesomeProject) described [here](https://facebook.github.io/react-native/docs/getting-started.html)

With a local packager running on a non-default port
expected app to connect to the server running on the non-default port

what really happened is that the app tried connecting to the sever on the default port

documentation does state that you need to configure it in the in-app [Developer menu](https://facebook.github.io/react-native/docs/debugging.html#accessing-the-in-app-developer-menu)
But the app was never loaded in the first place to the simulator so no way to open it

In addition, even when i did manage to fix the issue and load it, the [Developer menu](https://facebook.github.io/react-native/docs/debugging.html#accessing-the-in-app-developer-menu) doesn't have menus as described [here](https://facebook.github.io/react-native/docs/troubleshooting.html)

### Reproduction

1. `react-native start --port 8088` to start a local packager on a non default port
2. `react-native run-ios` fails because the port 8081 is hard-coded in several places ['RCTBundleURLProvider.m', 'RCTWebSocketExecutor.m', and in the build phases script]

### Solution

i had to change: in **RCTBundleURLProvider.m**

`const NSUInteger kRCTBundleURLProviderDefaultPort = 8081; `
to 
`const NSUInteger kRCTBundleURLProviderDefaultPort = 8088;`

And in **RCTWebSocketExecutor.m** 
`port = [[[_bridge bundleURL] port] integerValue] ?: 8081;` 
to 
`port = [[[_bridge bundleURL] port] integerValue] ?: 8088;
`
And lastly: 
open the iOS project in Xcode, in the project navigator > Libraries > React.xcodeproj > Build Phases, change all occurrences of 8081 to 8088.

### Additional Information

* React Native version: 0.39.2
* Platform: iOS
* Operating System: MacOS

**Comment by lacker** [comment]
Huh, what happened to the menu? Did it change to just remove this option at some point?

**Comment by eladhayun** [comment]
Well, this is what it looks like, can't find any "Dev Settings → Debug server host for device"

<img width="364" alt="screen shot 2016-12-16 at 22 08 08" src="https://cloud.githubusercontent.com/assets/5832456/21276930/5db8f4f8-c3dc-11e6-8d70-364e2b4a48c6.png">

**Comment by bozzmob** [comment]
Any idea what has to be done for Android. I'm not able to work on this, on Android :(

**Comment by ericvicenti** [comment]
Yeah the option was removed at one point on iOS (I'm also not sure about Android). I think we should clean up the docs so people don't expect to have this capability.

When somebody adds the feature back in we can promote it then.

**Comment by hramos** [comment]
Cleaned up on #13687
