### ISSUE TITLE
Catching JS-exceptions in Native

### ISSUE THREAD

**Issue by fab1an** [facebook/react-native#11455]
Is there a way to catch the exceptions that might occur in JavaScript (like in `render()` or various event-handlers) in native?

My application logic is native, only the view/presentation logic is handled by react-native, so I need to pass on the error somehow. At the moment my production build just crashes when an exception occurs.

Congratulations to this awesome project!

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
