### ISSUE TITLE
Packager very slow on first run

### ISSUE THREAD

**Issue by ywongweb** [facebook/react-native#11457]
### Description
When I run`react-native run-ios`, the package takes a very long time(30+ seconds) to run `/bin/sh -c /Users/username/dev/myapp/ios/build/Build/Intermediates/myapp.build/Debug-iphonesimulator/myapp.build/Script-F8DA82EA1DF9468900363441.sh`.

### Observations  

- The slowdown only happens when I don't have the packager running already. If it's running, subsequent `react-native run-ios` is very fast.   
- There is no slowdown if I run the packager and reset it's cache `node_modules/react-native/packager/packager.sh --reset-cache`. But I have do the reset every time, also I need to manually refresh the iOS simulator twice to see the app.
- The slow down is happening even with a newly init react-native project (react-native 0.39.2), also happens on projects with older versions of react-native.
- I've tried removing `node_modules`, cleaning npm cache with `npm cache clean`, reinstalling `watchman` and `react-native cli`. Non of these work.

### Additional Information
content of `Script-F8DA82EA1DF9468900363441.sh`
```
#!/bin/sh
if [ -z "${RCT_NO_LAUNCH_PACKAGER+xxx}" ] ; then
  if nc -w 5 -z localhost 8081 ; then
    if ! curl -s "http://localhost:8081/status" | grep -q "packager-status:running" ; then
      echo "Port 8081 already in use, packager is either not running or not running correctly"
      exit 2
    fi
  else
    open "$SRCROOT/../packager/launchPackager.command" || echo "Can't start packager automatically"
  fi
fi
```

**Comment by ericvicenti** [comment]
Yeah, it is known that the packager is slower when it is run for the first time, because it has to do a lot more work. The main priority is to keep the packager fast while developing.

I'm going to close this for now because it isn't super actionable. If you have any suggestions to make the packager go faster, feel free to open an issue describing your proposed change. Or you can post on [product pains](https://productpains.com/product/react-native/). If the community upvotes the issue, the RN team will know to prioritize it.

**Comment by ywongweb** [comment]
I managed to found a work around for this problem base on the suggestions in this post https://github.com/facebook/react-native/issues/11291 

### Steps
1. Manually start the packager in the `SAME` directory as your project: 
`node_modules/react-native/packager/packager.sh`

2.  run `react-native run-xxx`

=============

Looks like the long wait at start up was caused by this line in the shell script: `nc -w 5 -z localhost 8081` waiting for the packager to start. Still have no clues on why my packager takes 2-3 minutes to launch as manually launching it before hand seem to work fine.

**Comment by license2e** [comment]
@ericvicenti I just started getting this issue, and changing the code to use `nc -w 5 -z 127.0.0.1 8081` launches the simulator almost instantly when built, and a lot faster when running the first time. 

I submitted a PR: https://github.com/facebook/react-native/pull/13565

**Comment by AggarwalAnkit** [comment]
@license2e packager is still taking time to star. Now emulator opens up very fast after changing localhost to 127.0.0.1:8081

**Comment by punksta** [comment]
Why react use `--reset-cache` in release builds? What issues can we face if we use cache in release build?
