### ISSUE TITLE
Cannot debug with Cmd-D when using react-native through CocoaPods

### ISSUE THREAD

**Issue by MartinMoizard** [facebook/react-native#1145]
I created a project from Xcode (not through the command line `react-native init ProjectName`) and installed react-native with CocoaPods (pod 'React' and pod 'React/RCTText').

It works however I am not able to debug using the CMD+D shortcut. When pressing it, nothing happens. Any idea why?

**Comment by ide** [comment]
If Cmd-R is not working there might be a problem with the first responder -- make the root view the first responder.

If Cmd-R is working but Cmd-D doesn't then I believe the issue is you need to pull in the web socket debugger subspec.

**Comment by MartinMoizard** [comment]
Cmd-R is working, but not Cmd-D. What do you mean by pulling the web socket debugger subspec? Thank you.

**Comment by ide** [comment]
https://github.com/facebook/react-native/blob/master/React.podspec#L77

**Comment by MartinMoizard** [comment]
Thanks :) I didn't notice that there was several subspecs.
