### ISSUE TITLE
[Android] Problem about build with latest NDK version.

### ISSUE THREAD

**Issue by desmond1121** [facebook/react-native#11456]
After I upgrade NDK version to **13.1.3345770**, it's toolchain version is 4.9. 

But react-native use toolchain v4.8 to build source code, then I've tried to upgrade `NDK_TOOLCHAIN_VERSION` to 4.9 and build with some error. 

All of them is the same error : 

> error: lambda capture initializers only available with -std=c++1y or -std=gnu++1y [-Werror]

### Solution

After edit all `CXX11_FLAGS` from `-std=c++11` =>  `-std=c++1y` and `-std=gnu++11` => `-std=gnu++1y` in `Android.mk`, it went well.

### Additional Information

* React Native version: commit f8f70d2 in master
* Platform: Android
* Operating System: MacOS

**Comment by oargaruna** [comment]
This is a good point raised by @desmond1121. What is the plan to officially build React Native with the latest NDK?

**Comment by lacker** [comment]
In general I don't think that we support building React Native with any NDK other than the default, so I think I should close this issue as "not supported". I wouldn't be surprised if this just didn't work, so I congratulate you for figuring out a way to get it to work. Good luck!

**Comment by desmond1121** [comment]
ok, thanks @lacker.
