### ISSUE TITLE
PushNotificationsIOS manual linking instructions code is not working

### ISSUE THREAD

**Issue by tristanbbq** [facebook/react-native#11467]
### Description

In `0.39` docs, instructions to link `PushNotificationIOS` library is not working properly.

When copying over code to `AppDelegate.m` implementation, code does not build. It is missing a closing bracket in `didReceiveRemoteNotification` implementation.

### Reproduction

Setup a new project and follow instructions from http://facebook.github.io/react-native/docs/pushnotificationios.html (version 0.39).

Actual behavior: Project is not building
Expected behavior: Project builds fine

### Solution

Need to add missing closing bracket to `didReceiveRemoteNotification` implementation in docs.

### Additional Information

* React Native version: 0.39
* Platform: Both
* Operating System: MacOS

**Comment by iramlg** [comment]
Having the same issue on a new project, probably due a new version of xcode (new mac install today), hope they update quickly!

**Comment by lacker** [comment]
Thanks for reporting this. It sounds like you have detected both the problem and how to fix it. Would you be interested in sending a pull request to fix this?

**Comment by tristanbbq** [comment]
@lacker: Can you guide me into where is that documentation located? Can't find it, but I'll be happy to fix the issue and submit a PR!

**Comment by lacker** [comment]
I believe those docs are located in https://github.com/facebook/react-native/blob/master/Libraries/PushNotificationIOS/PushNotificationIOS.js - the docs are generated from the comments in that file. Thanks for helping out!

**Comment by tristanbbq** [comment]
@lacker awesome, thanks for pointing that out, will submit a PR with the fix.

**Comment by tristanbbq** [comment]
Issue already existed and was fixed: https://github.com/facebook/react-native/issues/11150
