### ISSUE TITLE
setValue is appending "0" to the end of Animated.Values

### ISSUE THREAD

**Issue by grubstarstar** [facebook/react-native#11472]
### Description

I called setValue on an Animated.Value passing in a string. I expected the string to be the value that was output in the console from the listener (see reproduction below). A also expected the backgroundColor to be set to "red".

What actually happens is it seems top append a "0" to the end of the string. So I got "red0" in both cases. I am using it to try to animate an SVG path, so I need a string for the value. I can't use interpolation because the path relies on more than one other Animated.Value.

### Reproduction

```javascript
export default class Test3 extends PureComponent {

   constructor(props) {
      super(props)
      this._animatingString = new Animated.Value('blue')
      this._animatingString.addListener(({value}) => {
         console.log('value', value)
      })
   }

   render() {
      this._animatingString.setValue("red")
      return <Animated.View style={{
         width: 400,
         backgroundColor: this._animatingString
      }}>
         <Text>Something</Text>
      </Animated.View>
   }

}
```

### Solution

Not sure if this is just a misuse of the API and it is designed that it only accepts numbers. If not, I need to find another way to do it. Or just not use Animated at all and rerender through setState.

### Additional Information

* React Native version: 0.39.2
* Platform: Both
* Operating System: Mac OSX

**Comment by browniefed** [comment]
You shouldn't call `setValue` in render.

**Comment by grubstarstar** [comment]
Okay, thanks for the quick response. I suspected that might be it. I'm trying to create an svg path (using `react-native-svg`'s `Path` component) such as below, which relies on `dx`, `dy` and `largeArc`, which is why I can't use interpolation:

```javascript
`
  M ${this._segmentPoints.origin.x},${this._segmentPoints.origin.y}
  l ${this._segmentPoints.line.dx},${this._segmentPoints.line.dy}
  a ${this.props.radius},${this.props.radius} 0 ${largeArcFlag} 1 ${dx},${dy}
  L ${this._segmentPoints.origin.x},${this._segmentPoints.origin.y}
`
```

I tried using a simple setState, which works but is a little janky. I also tried using `setNativeProps` on the `Path` component's `d` property to avoid the re-renders, but it throws an error which I don't yet understand!

I guess I was looking for something like this, which i'm pretty sure isn't available:

```javascript
const animatedDx = new Animated.Value(0)
const animatedDy = new Animated.Value(0)
const animatedLargeArc = new Animated.Value(0)
// ...do various setValue calls on the above Animated.Values....
const animatedPath = Animated.interpolate(
  [animatedDx, animatedValueDy, animatedLargeArc], // the input
  (dx, dy, largeArc) => createPathString(dx, dy, largeArc) // the output
)
```

although if Animated.Values can't be anything other than numbers, its academic really.

**Comment by browniefed** [comment]
You can take numbers and interpolate to non numbers but output range needs to be parseable.
Generating a path string has been one of the issues w/ Animated and there has been talk about creating custom animated formulas that could do this.

If you really need to do this stuff and still use `Animated`, you could setup a listener with `addListener`, generate your string and call `setNativeProps`. 

This is what you said you tried, but without showing code you used and the error it returned I can't help much.

**Comment by grubstarstar** [comment]
Thanks for the info. I'm wondering if the limitation is in `react-native-svg`, as it errors when I try to call `setNativeProps` (the 'd' prop) on a ref to the `Path` component. I'll try a couple of things out. I was doing it in a basic setInterval but i'll try in a Animated.Value listener.

**Comment by grubstarstar** [comment]
I tried a few approaches this morning which I'll share with you. There approaches are as follows:

1. using `setState`
2. attempting to use `setNativeProps`
3. using interpolation

using `setState` works fine, but I just thought there would be a more performant way of doing it that having to re-render the tree each frame, which is why I attempted using `setNativeProps`. The error message I get for the second and third approach are the same, i'm assuming this is because `Animated.Value` just uses `setNativeProps` internally. This is the error message. It looks like it's on the native side (iOS) but I haven't investigated it any further.

<img width="487" alt="screen shot 2016-12-16 at 11 05 46 am" src="https://cloud.githubusercontent.com/assets/1732170/21246978/3b19262c-c380-11e6-8478-e4e4169c0270.png">

Here are the code snippets I used for each:

**using setState**
```javascript
export default class testing extends Component {

   constructor(props) {
      super(props)
      this._origin = { x: 100, y: 100 }
      this._radius = 50
      this.state = {
         arcEndX: Math.sin(0) * this._radius,
         arcEndY: Math.cos(0) * this._radius - this._radius,
         largeArcFlag: Math.sin(0) >= 0 ? 0 : 1
      }
      this.setArcEndFromRadians = this.setArcEndFromRadians.bind(this)
   }

   setArcEndFromRadians(radians) {
      this.setState({
         arcEndX: Math.sin(radians) * this._radius,
         arcEndY: Math.cos(radians) * this._radius - this._radius,
         largeArcFlag: Math.sin(radians) >= 0 ? 0 : 1
      })
   }

   componentDidMount() {
      let radians = 0
      let timer = setInterval(() => {
         radians += 0.02
         this.setArcEndFromRadians(radians)
      }, 16)
   }

   render() {
      return (
         <View>
            <Svg
               height="200"
               width="200">
               <Path
                  d={ `M ${this._origin.x},${this._origin.y} l 0,50 a 50,50 0 ${this.state.largeArcFlag} 0 ${this.state.arcEndX},${this.state.arcEndY} z` }/>
            </Svg>
         </View>
      )
   }
   
}
```

**using setNativeProps (for better performance, error thrown)**
```javascript
export default class testing extends Component {

   constructor(props) {
      super(props)
      this._origin = { x: 100, y: 100 }
      this._radius = 50
      this._arc = {
         arcEndX: Math.sin(0) * this._radius,
         arcEndY: Math.cos(0) * this._radius - this._radius,
         largeArcFlag: Math.sin(0) >= 0 ? 0 : 1
      }
      this.setArcEndFromRadians = this.setArcEndFromRadians.bind(this)
   }

   setArcEndFromRadians(radians) {
      let arcEndX = Math.sin(radians) * this._radius
      let arcEndY = Math.cos(radians) * this._radius - this._radius
      let largeArcFlag = Math.sin(radians) >= 0 ? 0 : 1
      this._thePath.setNativeProps({
         d: `M ${this._origin.x} ${this._origin.y} l 0 50 a 50,50 0 ${largeArcFlag} 0 ${arcEndX} ${arcEndY} z`
      })
   }

   componentDidMount() {
      let radians = 0
      let timer = setInterval(() => {
         radians += 0.02
         this.setArcEndFromRadians(radians)
      }, 16)
   }

   render() {
      return (
         <View>
            <Svg
               height="200"
               width="200">
               <Path
                  ref={ ref => this._thePath = ref }
                  d={ `M ${this._origin.x},${this._origin.y} l 0,50 a 50,50 0 ${this._arc.largeArcFlag} 0 ${this._arc.arcEndX},${this._arc.arcEndY} z` }/>
            </Svg>
         </View>
      )
   }

}
```

**using Animated interpolation (simplified to just drawing a line, rather than a circle, error thrown)**
```javascript
let AnimatedPath = Animated.createAnimatedComponent(Path)
export default class testing extends Component {

   constructor(props) {
      super(props)
      this._origin = { x: 100, y: 100 }
      this._radians = new Animated.Value(0)
      this._arcX = this._radians.interpolate({
         inputRange: [
            0,
            100
         ],
         outputRange: [
            `M ${this._origin.x},${this._origin.y} l 0,0`,
            `M ${this._origin.x},${this._origin.y} l 100,100`
         ]
      })
   }

   componentDidMount() {
      Animated.spring(this._radians, {
         toValue: Math.PI,
         friction: 5,
         tension: 135
      }).start()
   }

   render() {
      return (
         <View>
            <Svg
               height="200"
               width="200">
               <AnimatedPath
                  d={ this._arcX }/>
            </Svg>
         </View>
      )
   }

}
```

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
