### ISSUE TITLE
After upgrade Xcode to v8.2, RN complains "bundleURL must be non-nil when not implementing loadSourceForBridge".

### ISSUE THREAD

**Issue by jaggerwang** [facebook/react-native#11477]
### Description

Before updating, it works fine. It seems RN can not auto detect packager server's ip address anymore.

### Screenshot

![image](https://cloud.githubusercontent.com/assets/1255011/21217160/bdb8e180-c2e5-11e6-9570-306b3bd7f3cf.png)

### Additional Information

* React Native version: 0.39.2
* Platform: iOS
* Operating System: macOS

**Comment by jaggerwang** [comment]
Auto fixed after rebooting my MacBook Pro.

**Comment by jaggerwang** [comment]
Got the reason. It is because I enabled NSAppTransportSecurity, when change back to value NSAllowsArbitraryLoads, it's ok.

But it is still not working by add "localhost" to NSExceptionDomains. How can we resolve this problem, as Apple will not allow NSAllowsArbitraryLoads begin at the next month.

```
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSExceptionDomains</key>
		<dict>
			<key>zqc.dev</key>
			<dict>
				<key>NSIncludesSubdomains</key>
				<true/>
			</dict>
		</dict>
	</dict>
```

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
