### ISSUE TITLE
Print: Entry, ":CFBundleIdentifier", Does Not Exist

### ISSUE THREAD

**Issue by cylzh** [facebook/react-native#11479]
MacOS 10.12.1
react-native  0.39.2
xcode 7.2
react-native-cli: 2.0.0

i can working properly in xcode, but when i run with react-native run-ios 
...
** BUILD SUCCEEDED **
Installing build/Build/Products/Debug-iphonesimulator/test.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/test.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by hramos** [comment]
Duplicate of #14423
