### ISSUE TITLE
Deprecate AdSupport?

### ISSUE THREAD

**Issue by ptomasroos** [facebook/react-native#11482]
Shall we deprecate the AdSupport project in react-native?

Its not including a Andriod version to get Identifier for Advertising.
I've created a package to enable this on https://github.com/ptomasroos/react-native-idfa

**Comment by chirag04** [comment]
cc @lacker

**Comment by lacker** [comment]
@mkonicek is the deprecationmaster so let's ask him.

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
