### ISSUE TITLE
Debug JS remotely opens Chrome in Parallels Desktop before Chrome.app on macOS

### ISSUE THREAD

**Issue by habovh** [facebook/react-native#11480]
### Description

Enabling `Debug JS Remotely` on a macOS computer that has Parallels Desktop installed with Chrome on Windows as well as the macOS version of Chrome opens the Parallels Desktop Windows virtual machine to launch Google Chrome there instead of the macOS one.
Note that if the packager does not try to open the new tap (e.g. when Chrome is already opened on Mac-side with a tab existing to the default debugger-ui URL), it does not open Parallels Desktop and uses the already existing tab in Chrome on macOS.

This issue might not be directly related to RN itself, but in the way that the tab is opened specifically in Chrome.

### Reproduction

- Use a Mac
- Have Parallels Desktop with a Windows virtual machine and Chrome installed
- Start remote debugging
- Packager opens Parallels Desktop with Windows along with its Chrome app.

### Solution

Open Google Chrome on macOS with a tab opened on `http://localhost:8081/debugger-ui` before enabling Remote JS Debugging

### Additional Information

* React Native version: 0.34.1
* Platform: Mac
* Operating System: macOS Sierra 10.12.1

**Comment by lamjack** [comment]
i have the same problem too.

**Comment by wookiem** [comment]
One workaround is to go into Parallels Desktop and uncheck: Share Windows Applications with Mac OS X.

[http://superuser.com/questions/213122/how-to-disassociate-a-file-type-with-an-application-in-mac-os](http://superuser.com/questions/213122/how-to-disassociate-a-file-type-with-an-application-in-mac-os)

**Comment by habovh** [comment]
Thanks for the tip @wookiem! That's a very good information here, will save me a lot of RAM actually! But since it is not really a fix, I believe this issue should stay opened until someone figures out if the packager would eventually be able to open the browser from macOS, or if it is maybe the desired behavior not to "force" any browser in case the user actually would want to debug in Parallels? That'd be silly though. 🤔

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.

**Comment by iMagdy** [comment]
I'm gettings this too

![image](https://cloud.githubusercontent.com/assets/611426/26740936/cfa52eea-47d7-11e7-9f0a-0f766742a6eb.png)

**Comment by mateoc10** [comment]
@iMagdy i am having the same problem. Did you fix it?

**Comment by mateoc10** [comment]
@iMagdy I just found a solution to that problem. The problem was that I uninstalled parallel desktop long ago but some files where still in my computer. I deleted the folder "Applications (parallel)". It had lots of windows applications in it. Now it works perfectly

**Comment by chriscohoat** [comment]
@wookiem's solution worked for me..I needed to select the virtual machine's settings, click options, click applications, and then disable sharing of windows applications with Mac:

<img width="689" alt="screenshot 2017-06-09 12 28 33" src="https://user-images.githubusercontent.com/566461/26989220-7c5b010a-4d0f-11e7-8238-4392b9128bdf.png">

**Comment by johncrisostomo** [comment]
Funny this just happened to my project, I dunno what caused it though. Doing the solution above fixed it, however, I don't really know / understand why it happened.

**Comment by tbusot** [comment]
FYI the above never worked for me but then I noticed that it was calling to a VM that had been deleted. My current was "Windows 10", but it was calling for "Windows 8" version of Google Chrome. I located the folder Users > %me% > Applications (Parallels) > Windows 8 Applications > 
In there, I deleted Google Chrome and it fixed it right up. 
Hope this helps some other frustrated soul.
