### ISSUE TITLE
Unnecessary memory consumption of BugReporting module

### ISSUE THREAD

**Issue by gitim** [facebook/react-native#11484]
Hi! 
In our app we faced with ooms issues in our app and we made some investigation of memory leaks and app' memory footprint size. We noticed that in every `AppRegistry.runApplication` call `appParameters` are [stored](https://github.com/facebook/react-native/blob/master/Libraries/ReactNative/AppRegistry.js#L91-L98) as string into the [BugReporting](https://github.com/facebook/react-native/blob/master/Libraries/BugReporting/BugReporting.js), but the BugReporting is used nowhere, except `AppRegistry.runApplication`. It looks like unnecessary memory consumption if `appParameters` is big enough this extra memory consumption is noticeable. 

Is this module is really neceassary, does it used by somebody, could we just drop it?

**Comment by lacker** [comment]
Facebook code uses `BugReporting` a lot. It seems like the API is not documented so it's maybe not super useful to most people but I don't think we should remove it from RN core. You are of course welcome to hack up your local version of React Native, that might be a good solution for you. Good luck!

**Comment by gitim** [comment]
> It seems like the API is not documented so it's maybe not super useful to most people but I don't think we should remove it from RN core.

Moreover it is not even exposed: https://github.com/facebook/react-native/blob/master/Libraries/react-native/react-native.js
