### ISSUE TITLE
NavigationExperimental how push new route without Animation?

### ISSUE THREAD

**Issue by antoxi4** [facebook/react-native#11486]
How i can push new route or jump to route without animation in NavigationExperimental?

Addition Information: 
Operation System: OS X,
Platform: IOS, Android.

**Comment by ptomasroos** [comment]
```
 <NavigationTransitioner
        configureTransition={() => { return null; }}
       ....
```

**Comment by antoxi4** [comment]
@ptomasroos  thanks))

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (63/60 (105%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter01.reliabledns.org ([199.96.156.50]:44338)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1cHbjK-004HoV-HF
	for bunny@thumbmunkeys.com; Thu, 15 Dec 2016 19:30:16 +0000
Received: from github-smtp2-ext8.iad.github.net ([192.30.252.199] helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by filter01.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1cHbjH-0003eu-Tl
	for bunny@thumbmunkeys.com; Thu, 15 Dec 2016 12:30:14 -0700
Date: Thu, 15 Dec 2016 11:30:10 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1481830210;
	bh=hgTXY0kF+kcCcYgyMURiNIoiqfVPzOdu/361p4BbdFM=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=K7+oGHoTXAuOjVvtHZQf3oePI/v3vcKUeMUpw9PoPI9OQP3CgPCkup9dngsSpIWha
	 2BfGWmE5GWUjwLN0sgdGSfRReHIBnFC7Mg1ZTaBrXVO4HC1ONcaAFEK7X+UVC8HUwU
	 64P2p68TyRGy78NsuMzK2GQXj/DabNoU5ZH/JzTw=
