### ISSUE TITLE
View was rendered with explicitly set width/height but with a 0 flexBassis

### ISSUE THREAD

**Issue by mxmtsk** [facebook/react-native#11481]
### Description

I recently upgraded to the latest react-native version and parts of my application are not working anymore. I have a Timeline that loads more posts after a click on a button, but a certain post type is causing the error 

> View was rendered with explicitly set width/height but with a 0 flexBasis. (This might be fixed by changing flex: to flexGrow:) View: <RCTShadowView: 0x6080001bc620; viewName: RCTImageView; reactTag: 315; frame: {{0, 37}, {325, 150}}>

(It work on initial render, only the appended posts aren't working) I have no idea what this error means or how to fix it. The style attributes look alright to me. Strangly enough, when I dismiss the error, everything is rendered, except the height is incorrect, it's higher than what I set it to be.

### Reproduction

The problem is caused by a view with the following styles:
```
  playerYoutube: {
    flex: 1,
    height: 200,
    backgroundColor: 'black',
  },
```

### Additional Information

* React Native version: 0.39.2
* Platform: iOS
* Operating System: MacOS

**Comment by lacker** [comment]
Can you provide a minimal sample app that reproduces this? It doesn't seem like the styles you provided have enough info to reproduce the problem.

**Comment by hygkui** [comment]
@mxmtsk I have meet the same error, and I found the documents of break-changes in **0.36**, it says
you should remove 'flex: x' or replace with 'flexGrow: x', x may be 0, 1, or 2 whatever, and it will resolve most problems. 

the link is here: [Breaking-Changes](https://github.com/facebook/react-native/wiki/Breaking-Changes#fix-unconstraint-sizing-in-main-axis-0a9b6b---emilsjolander)

**Comment by pvpshoot** [comment]
How can i detect which component breaks ? 
http://take.ms/IiKoj

**Comment by andela-Jaderibigbe** [comment]
Any update on the issue? @mxmtsk were you able to fix it? If yes how? I have no idea how to fix this. I have changed 'flex: x' and replaced with 'flexGrow: x'. Still unresolved :(

**Comment by hygkui** [comment]
@andela-Jaderibigbe  x should be replaced with the real number such as 1.

**Comment by Taakn** [comment]
Same issue, same RN version (I cannot upgrade). Impossible to know what component is breaking.

**Comment by mxmtsk** [comment]
Hi,
this may not be applicable to everyone but in my specific case I went with this approach:

```
  youtubeVideo: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
  },
  playerYoutube: {
    flex: 1,
    paddingBottom: 200,
    backgroundColor: 'black',
  },
```

```JSX
<View style={styles.playerYoutube}>
  <YouTube
    ref="youtubePlayer"
    videoId={post.postable.gold.video_id} // The YouTube video ID
    play={false}           // control playback of video with true/false
    hidden={false}        // control visiblity of the entire view
    playsInline={true}    // control whether the video should play inline
    loop={false}          // control whether the video should loop when ended
    showinfo={false}

    style={styles.youtubeVideo}
  />
</View>
```

**Comment by Taakn** [comment]
@mxmtsk I ended up finding the missing flex that I had to replace by a flexGrow so it's working now. But really, thanks a lot for taking the time to reply a just few minutes after my post.

**Comment by Kerence** [comment]
I have encountered this issue, the reason is as follows:
view in a parent with flexDirection:'row'  sets flex:1 and width:value 
view in a parent with flexDirection:'column'  sets flex:1 and height:value 
In android, react native automatically skip flex:1 and uses the width/height value
In ios, react native detects the collision and throws an error.

**Comment by zhaolei1177** [comment]
@Kerence ,  i meet the same issue,and my code is:
posterPlayImg: {
        flex: 1,
        height: 48,
        resizeMode: 'contain'
    }

if i change it like the under code(**add the width prop**):

posterPlayImg: {
        flex: 1,
        height: 48,
        **width: 48,**
        resizeMode: 'contain'
    }

can it close my error?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/view-was-rendered-with-explicitly-set-widthheight-but-with-a-0-flexbassis
