### ISSUE TITLE
Unable to resolve module ReactElementType

### ISSUE THREAD

**Issue by Oxyaction** [facebook/react-native#11492]
### Description

Having an error while trying to run the project on ios or android.

<img src="https://cloud.githubusercontent.com/assets/1942242/21235853/311d104a-c301-11e6-971c-397f0aab1001.png" width="350" >

__Error message:__

(node:12029) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1366): UnableToResolveError: Unable to resolve module ReactElementType from /Users/alexandrkompaniets/web/age/walletclient/node_modules/react-native/Libraries/Renderer/src/renderers/shared/ReactDebugTool.js: Module does not exist in the module map or in these directories:
  /Users/alexandrkompaniets/web/age/walletclient/node_modules/react-native/node_modules
,  /Users/alexandrkompaniets/web/age/walletclient/node_modules

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.

I ran the following commands
```js
watchman watch-del-all
rm -rf ./node_modules
yarn cache clean
rm -rf $TMPDIR/react-*
yarn install
npm start -- --reset-cache
```
But it didn't help. Also, I tried to create a new project and copied src files, but still the same result.

__package.json__:
```js
"react": "^15.4.1",
"react-native": "^0.39.2",
```

**Comment by tedjames** [comment]
I'm getting the same error whenever I try to install and import _any_ new modules
<img width="1191" alt="bug5" src="https://cloud.githubusercontent.com/assets/13091675/21241328/174c3bc4-c2dd-11e6-9dfd-9abbf07ce7a8.png">

**Comment by tedjames** [comment]
Try this:
1. Click "Reset content and settings..." in the simulator's drop down menu and confirm
2. Close the simulator after it reloads
3. Close the terminal window running the watchman
4. Run the following commands within terminal inside of your project's directory:
```
watchman watch-del-all
rm -rf ./node_modules
npm cache clean
yarn cache clean
rm -rf $TMPDIR/react-*
yarn install
npm cache clean
yarn cache clean
yarn add uuid
```
5. Rebuild the project inside of Xcode and be sure to make any suggested modifications prior to running the app.

**Comment by Oxyaction** [comment]
Unfortunately, this solution didn't help. Looks like we facing different problems. In your case, you trying to make explicit import of the module which exists in `node_modules` while in my case `ReactElementType` is the file inside `node_modules/react/lib` and `ReactDebugTool` trying to import it directly `import type { ReactElement } from 'ReactElementType';`, like it laying in `node_modules` so seems there some kind of syntax sugar that allows such implicit imports and it doesn't work. 
Also `ReactElementType.js` is empty without any flowtype definitions so it becomes totally unclear.

**Comment by Oxyaction** [comment]
After long searches, I found that problem was in my `.babelrc`, more precisely - in `flow-react-proptypes` plugin, without it, everything works fine.

Breaking config:
```js
{
  "passPerPreset": true,
  "presets": [
    {
      "plugins": [
        "./build/babelRelayPlugin",
      ]
    },
    "react-native"
  ],
  "plugins": ["flow-react-proptypes"]
}
```
Working config:
```js
{
  "passPerPreset": true,
  "presets": [
    {
      "plugins": [
        "./build/babelRelayPlugin",
      ]
    },
    "react-native"
  ]
}
```
