### ISSUE TITLE
Animated not working with translate: Transform with key of "translateY" must be a number: {"translateY":0}

### ISSUE THREAD

**Issue by mxmtsk** [facebook/react-native#11503]
### Description

[FILL THIS OUT: Explain what you did, what you expected to happen, and what actually happens.]
I'm trying to animate Transform's Translate Values but I keep getting the error message _ExceptionsManager.js:63 Transform with key of "translateY" must be a number: {"translateY":0}_

### Reproduction

That is basically what I'm running onPress.
```Javascript
  openListView = () => {
    if (this.state.activeView !== 'ListView') {
      this.setState({
        activeView: 'ListView',
      });

      Animated.parallel([
        Animated.timing(
          this.state.mapViewOffset,
          {
            toValue: { x: 0, y: -Dimensions.get('window').height - Common.navBarHeight },
            easing: Easing.linear,
          },
        ),
        Animated.timing(
          this.state.listViewOffset,
          {
            toValue: { x: 0, y: 0 },
            easing: Easing.linear,
          },
        ),
      ]).start();
    }
  }
```

This is how I'm using it:

```Javascript
        <View
          style={[
            styles.searchMapView,
            { transform: [{ translateY: this.state.mapViewOffset.y }] },
          ]}
        >
```

### Additional Information

* React Native version: 0.39.2
* Platform iOS, Android not in use for my App
* Operating System: MacOS

**Comment by mxmtsk** [comment]
Nevermind... Animated.View is what I forgot

**Comment by endel** [comment]
That's right! I forgot the same thing. Maybe the error message should point this out?!

**Comment by arcarson** [comment]
@endel Completely agree - the error message could be a lot more helpful.

**Comment by ahmad2smile** [comment]
same thing ;)
