### ISSUE TITLE
Navigator, view mounted but not rendered

### ISSUE THREAD

**Issue by iceNuts** [facebook/react-native#1150]
Hi,

I come across a very weird bug: I use Navigator to push a child view, and see log shows the view is rendered but simulator doesn't. Before, I meet this situation too, and finally find some minor errors in the child view file. I am wondering if there is some tool to find out the bug more quickly?

Thanks.

**Comment by christopherdro** [comment]
Could you provide an example of your code and the bug that you are receiving?

**Comment by brentvatne** [comment]
@iceNuts - closing this because we haven't heard a followup, feel free to ping me if you're still having this issue, and if you can please post a runnable example repository or app on [rnplay.org](rnplay.org), thanks!
