### ISSUE TITLE
ndk-build binary cannot be found

### ISSUE THREAD

**Issue by jpshelley** [facebook/react-native#11500]
### Description

* Attempting to use my own fork for an Android patch located here: https://github.com/jpshelley/react-native/tree/0.39.0-AndroidSupportLibrary25.0.1
* Performed all the steps in https://facebook.github.io/react-native/docs/android-building-from-source.html
* Downloaded the correct NDK `android-ndk-r10e` and is set in my $ANDROID_NDK and $ANDROID_NDK_HOME and local.properties file.
* I do have a second module in my project that is a library module but there should be no reason it interferes.

HOWEVER. I keep getting the error mentioned in the title its coming from https://github.com/facebook/react-native/blob/master/ReactAndroid/build.gradle#L178

And my fork actually fixed a previous bug that couldn't find the `sdkHandler` property so I have an if check in place for that in my fork, now I ran into this bug.

### Reproduction

* Attempt to create a new React Native project `react-native init MyNewProject`
* Change the react-native dependency: `npm install --save github:jpshelley/react-native#0.39.0-AndroidSupportLibrary25.0.1` 
* Try to import the `android` folder into Android Studio 2.3.3

### Solution

* Figure out why its not picking up either the `$ANDROID_NDK` or the local.properties file..

### Additional Information

* React Native version: 0.39.2 -> https://github.com/jpshelley/react-native/tree/0.39.0-AndroidSupportLibrary25.0.1
* Platform: android
* Operating System: MacOS

**Comment by lacker** [comment]
Can you run the Android integration tests on your machine? Try pulling master and running the integration test script - I added some more checking-what's-wrong-in-your-config logic there and maybe it will help.

**Comment by jpshelley** [comment]
@lacker When running the `./scripts/validate-android-test-env.sh` script which unit and integration rely on I get the following:
```
Error: we can't use this Java version.
Currently, Java runs from /usr/bin/java.
The operating-system-provided Java doesn't work with React Native because of SIP protection.
Please install the Oracle Java Development Kit 8.
Check out http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html .
Be sure that you set JAVA_HOME and PATH correctly.
After installing Java, run 'buck kill' and 'buck clean'.
```
When I run `java -version` I get:
```
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
```
`which java` does return `/usr/bin/java` which as the script shows is what causes the error. I do have my `$JAVA_HOME` set correctly and as you can see the version it picks up is correct ^^

However, I think that might be a false check because it is a symlink http://stackoverflow.com/a/18144853/1784299

Am I missing something in my JAVA setup, or should that script be updated somehow?

(Running MacOS 10.12.1)

**Comment by lacker** [comment]
It's entirely possible that this script is missing an edge case - I tried it out on a few machines but the nature of this is that there's a zillion edge cases.

So, are you running the version of java that came preinstalled with OS X or did you install Java separately? The preinstalled version is Java 8, but it's modified in some way that makes it incompatible with building React Native from source, so you actually do need to install the JDK separately.

**Comment by jpshelley** [comment]
@lacker understandable. And no I installed the JDK from Oracles site and is now located at `/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home` even though my `which java` command shows otherwise.

**Comment by lacker** [comment]
Mmm, I see. Do you know of a better way to detect whether it's the right binary? - it seems like ideally that script would not just be checking for `/usr/bin/java`.

**Comment by jpshelley** [comment]
@lacker
1. I was able to get past the java related issues
2. I did have an error in my fork after running the integration tests script
3. Fixed the error and pushed my changes -> https://github.com/jpshelley/react-native/commit/0c868391485bad05a68300795d2e7b2c20cca135
4. Ran `rm -rf node_modules/; yarn cache clean; yarn` to get the latest commit from my fork
5. Invalidates caches in Android Studio and restarted, however the same error occurred:

```
Error:(181, 0) ndk-build binary cannot be found, check if you've set $ANDROID_NDK environment variable correctly or if ndk.dir is setup in local.properties
```

It is also worth noting that `react-native run-android` works completely fine and I was able to get it running on an emulator. So it seems to be an issue with Android Studio potentially.

**Comment by jpshelley** [comment]
@lacker Found the cause. Pulling in my fork works great from a new project that was created from `react-native init ...`, however when Using Studio it offers to upgrade the gradle plugin and wrapper and that is when the ndk-build binary cannot be found appears.

So something has broke since the gradle plugin has updated.

References:
* The project worked on the initial creation and inclusion of the fork: https://github.com/jpshelley/ReactNativeExampleForkedProject/commit/796ee2de089efcab36a637a41c40721be84b7e94
* The project then started getting the failure when I updated Gradle: 

Working Gradle:
* `classpath 'com.android.tools.build:gradle:1.3.1'`
* `distributionUrl=https\://services.gradle.org/distributions/gradle-2.4-all.zip`

Broken Gradle:
* `classpath 'com.android.tools.build:gradle:2.3.0-beta1'`
* `distributionUrl=https\://services.gradle.org/distributions/gradle-3.2-all.zip`

Any help would be appreciated but I'll keep digging once I get more time.

**Comment by jpshelley** [comment]
@lacker as an update I was able to update to the following:
* Gradle Plugin: `classpath 'com.android.tools.build:gradle:2.2.3' `
* Gradle Wrapper: `distributionUrl=https\://services.gradle.org/distributions/gradle-2.14.1-all.zip
View`

And it works again. Must have a bug in gradle 2.3.0+

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
