### ISSUE TITLE
RCTBridge crashes if invalidated before JSLoader completes

### ISSUE THREAD

**Issue by ide** [facebook/react-native#1151]
`-[RCTJavaScriptLoader loadBundleAtURL:]` should check if the bridge is valid in its URLSession handler. What seems to be possible is:

1. RCTBridge is created and starts loading the JS
2. RCTBridge is invalidated, which nils out `_modulesByName`
3. Response arrives and RCTJavaScriptLoader's handler runs `RCTSourceCode *sourceCodeModule = _bridge.modules[RCTBridgeModuleNameForClass([RCTSourceCode class])];` which fires an assert since `_modulesByName` is nil

**Comment by tadeuzagallo** [comment]
Thanks, that has already been fixed. There was actually a big refactoring on the bridge, should be out on the next sync.
