### ISSUE TITLE
 UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'message' of undefined

### ISSUE THREAD

**Issue by gavatoverflow** [facebook/react-native#11514]
Operating system  windows , react-native version 0.39.2
   I run into this error while running the application.  I created the application but I made no changes.
>**react-native run-android**

> JS server already running.
> Running C:\Users\tigin\AppData\Local\Android\sdk/platform-tools/adb -s fce7e07a reverse tcp:8081 tcp:8081
> Building and installing the app on the device (cd android && gradlew.bat installDebug)...
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem occurred configuring project ':app'.
> > failed to find Build Tools revision 23.0.1
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> BUILD FAILED
> 
> Total time: 22.563 secs
> Could not install the app on the device, read the error above for details.
> Make sure you have an Android emulator running or a device connected and have
> set up your Android development environment:
> https://facebook.github.io/react-native/docs/android-setup.html
> 
> (node:6556) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'message' of undefined

**Comment by lacker** [comment]
"failed to find Build Tools revision 23.0.1" seems like it might be the key problem there. Do you have revision 23.0.1?

**Comment by fkurutass** [comment]
Thanks. It worked after the update.
@lacker 
> 
> Android\sdk\tools > **android list sdk -a**
> Show lists of sdk 
> Find tools line and type the following entry in the line number.
> 12 - **Android SDK Platform-tools, revision 23.0.1**  
> and update
> Android\sdk\tools  >**android update sdk -a -u -t 12**

**Comment by ashutosh-akss** [comment]
I am facing same issue when generating signed apk, 
```
react-native run-android --variant=release
```

Following is the error message

```
BUILD FAILED

Total time: 2 mins 15.42 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

(node:13173) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'message' of undefined

```
 
without --variant=release it works fine

**Comment by mohit-pandey** [comment]
@ashutosh-akss , I am facing the same issue. Could you please help me to fix this.

**Comment by ashutosh-akss** [comment]
@mohit-pandey are you getting this only when generating signed apk? Or even while generating debug apk ? Its still not fixed for me. Waiting for fix. For now I am compiling it on mac

**Comment by mohit-pandey** [comment]
@ashutosh-akss , yeah , i am getting it while generating signed apk.
Is there any other way with which i can run the app on my android device?

**Comment by ashutosh-akss** [comment]
@mohit-pandey If you have android studio installed, just try importing android folder into android studio and generate signed apk from android studio. It works for me. You might get warning to upgrade gradle  you can ignore that

**Comment by Lesanjo** [comment]
I have the same issue. Using APK platform tools version 23 revision 3.

Also, even without --variant=release still doesn't solve the issue

**Comment by connelevalsam** [comment]
for singned apk. I just use android studio instead. Makes life easier.

**Comment by LautaroMed** [comment]
I have the same problem. I have an app in 2 pcs. I coded it in one and uploaded it to git and downloaded in the 2. The first pc can run it with no issues. The second one throws:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> at index 4

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 6.027 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

(node:3536) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'message' of undefined

Can anyone help me? I'm just starting with react-native. I use windows 10

**Comment by steveliles** [comment]
To find the actual error message, build directly with gradle and enable debug logging with --debug.

debug build -

```
cd android && ./gradlew assembleDebug --debug
```

release build -

```
cd android && ./gradlew assembleRelease --debug
```

I recommend that you first make sure to remove `./android/app/build` so that there's no remnants of a broken build that could influence the result. Also check that the broken build didn't leave anything in your android src tree. Mine had left behind a bunch of files in `./android/app/src/main/assets` and `./android/app/src/main/res`. I didn't notice these so I wasted time chasing the wrong problem.

In my case I had been switching my environment between java7 and java8 for a different project. When I came back to my entirely unmodified react-native project and tried to run the build with `react-native run-android --configuration Release`, it failed with the unhelpful error:

```
(node:3536) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'message' of undefined
```

I then tried to build directly with `./gradlew assembleRelease --debug` which came out with problems about duplicate resources (exactly the error messages reported by others in #5787 - for me this was because of the files left behind in my src tree, which I hadn't expected to be modified during the build and so didn't notice).

After cleaning `./android/app/build` and the source tree then building again directly with gradle, the _actual_ problem was reported:

```
12:14:13.098 [ERROR] [org.gradle.BuildExceptionReporter] > compileSdkVersion 'android-25' requires JDK 1.8 or later to compile.
```

Switched back to java8 and voila, successful build.

**Comment by zofe** [comment]
I'm using a meizu m3s  android version is 5.1 (Flyme 5.1.5.3G). 
for many project when i do this:
`react-native run-android`  it fails as in this issue.

but I solved  using:
`cd android && ./gradlew assembleDebug --debug` (build successful)
then
`adb install ./app/build/outputs/apk/app-debug.apk`

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/unhandledpromiserejectionwarning-unhandled-promise-rejection-rejection-id-2-type
