### ISSUE TITLE
[Android]why onTouchCancel is not exported as bubbling event on android ?

### ISSUE THREAD

**Issue by littlesome** [facebook/react-native#11510]
While looking into the source of android, I find onTouchCancel if not exported, is this a bug?

[TouchEventType](https://github.com/facebook/react-native/blob/9ee815f6b52e0c2417c04e5a05e1e31df26daed2/ReactAndroid/src/main/java/com/facebook/react/uimanager/events/TouchEventType.java#L19)
```
public enum TouchEventType {
  START("topTouchStart"),
  END("topTouchEnd"),
  MOVE("topTouchMove"),
  CANCEL("topTouchCancel");
```

[only START, END, MOVE are exported](https://github.com/facebook/react-native/blob/abb8ea3aea686e2cd881a61fbc66d137857ef422/ReactAndroid/src/main/java/com/facebook/react/uimanager/UIManagerModuleConstants.java#L42-L68)

[on iOS, 4 types are exported](https://github.com/facebook/react-native/blob/abb8ea3aea686e2cd881a61fbc66d137857ef422/React/Views/RCTViewManager.m#L82-L85)

**Comment by littlesome** [comment]
@mkonicek will you have a look?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/androidwhy-ontouchcancel-is-not-exported-as-bubbling-event-on-android
