### ISSUE TITLE
[TouchableMixin] Should cancel timers on unmount

### ISSUE THREAD

**Issue by spicyj** [facebook/react-native#1152]
In TouchableMixin, `touchableHandleResponderGrant` sets `this.touchableDelayTimeout` and `this.longPressDelayTimeout` but if the component is unmounted before the timer fires, an error may be thrown, depending on the definition of `touchableHandleActivePressIn`.

In particular, in TouchableHighlight's _showUnderlay, `this.refs[UNDERLAY_REF]` can be undefined if the component is unmounted and an exception is thrown. (And the conditional in _hideUnderlay is should be unnecessary after this change.)

**Comment by brentvatne** [comment]
@spicyj - it looks like TouchableMixin is vendored in react_contrib, is this something that we would change directly on the react-native repo or is there another repo for this? Happy to take a look

**Comment by spicyj** [comment]
Fairly sure this is the right repo to change it.

**Comment by ide** [comment]
MIght want to look into TimerMixin as well though I'm not familiar with mixins using mixins.

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
