### ISSUE TITLE
TouchableOpacity component sometimes get stuck at low opacity

### ISSUE THREAD

**Issue by sachinrekhi** [facebook/react-native#11522]
### Description

After frequent use of a TouchableOpacity item in the iOS Simulator, the TouchableOpacity element now gets stuck with a low opacity instead of properly returning to full opacity.

This is a new issue as this never used to occur. I only started experiencing it when I recently upgraded my project from Reactive Native 0.34.1 to 0.39.2. My guess is this regression was introduced as part of the transition of TouchableOpacity to use the new native animation capabilities.

### Reproduction

Repeatedly click on a TouchableOpacity element. After some time, you'll see that the TouchableOpacity element is stuck with a low opacity instead of returning to full opacity like it is supposed to.

In my case, here is what the normal state looks like for my sidebar toggle that is wrapped by a TouchableOpacity element:
![normal](https://cloud.githubusercontent.com/assets/192650/21284404/d969a736-c3ce-11e6-8f2a-4ce3907d2384.png)

And here is what it looks like after it gets stuck in a low opacity state:
![stuck](https://cloud.githubusercontent.com/assets/192650/21284406/e249b4c2-c3ce-11e6-9acb-3f87ae9910c4.png)

### Additional Information

* React Native version: 0.39.2
* Platform: iOS
* Operating System: MacOS

**Comment by jamielob** [comment]
Also seeing this on device but haven't been able to replicate on simulator.

- React Native version: 0.39.2
- Platform: iOS
- Operating System: MacOS

**Comment by ishbaid** [comment]
Also running into this - occurs quite frequently for me actually. Would love to hear if anyone is found a fix for this.

**Comment by MiLeung** [comment]
I just made another touchable* component called [TouchableElastic](https://github.com/MiLeung/touchable-elastic) since this issue doesn't seem to be resolved yet.  Instead of changing opacity, it changes scale.

**Comment by grundmanise** [comment]
In some 'medium sized' components I also have this issue.. If I place two `TouchableOpacity` on the screen with let's say `setState(...)` in `onPress` for both and then press them promptly with a finger, one of them stucks at low opacity. It is always the last `TouchableOpacity` that gets stuck at low opacity.

Part of my component for the reference:

```
    constructor(props) {
        super(props);
  
        this.state = {
          listVisible: false,
          itemList: [...]
        }

    }

    render() {
       return (
                <View style={styles.container}>
         
                    <View style={styles.scrollViewWrapper}>
                        <ScrollView
                            carouselStyle={[styles.scrollView, this.state.listVisible && styles.hidden]}
                            //rest props
                        >
                         {this.state.itemList.map(this.createSlides)}
                         //children > 20
                        </ScrollView>
                    </View>

                    <View style={{flexDirection: 'row'}}>
                            <TouchableOpacity style={{marginRight: 40, width: 40, height: 40, backgroundColor: 'white'}} onPress={this.showList}>
                            <Text> HIDE </Text>
                            </TouchableOpacity>
                            <TouchableOpacity style={{marginRight: 80, width: 40, height: 40, backgroundColor: 'red'}} onPress={this.showCarousel}>
                            <Text> SHOW </Text>
                            </TouchableOpacity>
                    </View>
         
                 </View>
               )
    }

    showCarousel = () => {
        this.setState({
            listVisible: true,
        });
    }

    showList = () => {
        this.setState({
            listVisible: false,
        });
    }
```

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/touchableopacity-component-sometimes-get-stuck-at-low-opacity
