### ISSUE TITLE
`fetch` undefined when running tests with jest

### ISSUE THREAD

**Issue by leifdenby** [facebook/react-native#11537]
### Description

In trying to run tests with `jest` I am finding that `fetch` isn't available when running the tests. This appears to have broken when the configuration for `react-native` was moved from the `jest` repo to the `react-native` repo, which I think is because the [`whatwg`-based fix](https://github.com/facebook/jest/pull/1424/commits/938a334f5442a0c7b19fc717cd7669fad5b59970)  which was added to `jest`[hasn't been copied across](https://github.com/facebook/react-native/commit/6a462fb085382b45b0de53275711adf223c327d4#diff-606adbd6a8c97d177b17baee5a69cdd9R65) when [it was removed from `jest`](https://github.com/facebook/jest/pull/2182/commits/9060c18d52752aa635c02b353f1d3e82507db5d3#diff-d69cce8339af1c7ad0d23540f9b069b1L75).

### Reproduction

Any test that uses `fetch` fails.

### Solution

Add back `fetch` into `jest/setup.js`

```
const {Response, Request, Headers, fetch} = require('whatwg-fetch');
global.Response = Response;
global.Request = Request;
global.Headers = Headers;
global.fetch = fetch;
```

### Additional Information

* React Native version: `0.39.0`
* Jest version: `18.0.0`
* Platform: to specific to iOS or Android
* Operating System: MacOS

**Comment by suparng-medallia** [comment]
I am seeing the same issue.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/fetch-undefined-when-running-tests-with-jest

**Comment by pbuda** [comment]
Having the same issue with
```
react-native-cli: 2.0.1
react-native: 0.47.1
jest: 20.0.4
```
The project is written in typescript. App works but jest tests fail due to missing fetch. When I import fetch from isomorphic-fetch tests work but app is not.

**Comment by vovkasm** [comment]
@hramos this issue definitely should be fixed rather that closed :-(
RN exposed fetch API, it is clearly stated in docs: http://facebook.github.io/react-native/docs/network.html#content
therefore react-native jest preset (hosted in RN repository now) should also provide the API!

**Comment by pbuda** [comment]
Since I posted my comment I was able to make it work.
Production code doesn't define fetch, because otherwise the app would crash. So in order for fetch to be available in jest tests I added `import "isomorphic-fetch"` in test files and it started working.

**Comment by vovkasm** [comment]
Yes, now I added to my jest-setup.js this:
```
const fetchPolifill = require('whatwg-fetch')
global.fetch = fetchPolifill.fetch
global.Request = fetchPolifill.Request
global.Headers = fetchPolifill.Headers
global.Response = fetchPolifill.Response
```
But I need specifically support objects `Request`, `Headers`, `Response`... Of course tests do not actually send any requests.

**Comment by pendar747** [comment]
Adding these in my setup file doesn't fix the issue
```js
// global-mocks.js
const fetchPolifill = require('whatwg-fetch')

global.fetch = fetchPolifill.fetch
global.Request = fetchPolifill.Request
global.Headers = fetchPolifill.Headers
global.Response = fetchPolifill.Respons
```
```json
// package.json
...
  "jest": {
    "preset": "jest-expo",
    "verbose": true,
    "rootDir": ".",
    "setupFiles": [
      "<rootDir>/global-mocks.js"
    ],
    "globals": {
      "__DEV__": true
    },
    "transform": {
      "^.+\\.js$": "babel-jest"
    },
    "transformIgnorePatterns": [
      "node_modules/(?!react-native|react-navigation|native-base)/"
    ]
  }
...
```

**Comment by vovkasm** [comment]
@pendar747 Note, that you use another jest preset! You use `jest-expo`. According to [jest-expo/src/setup.js](https://github.com/expo/jest-expo/blob/c3d5fd5c3c7eb84d0e0264d0e2f2d3d028339bf2/src/setup.js#L7-L11) jest already have `fetch` defined in `globals`, so you better to remove this from `global-mocks.js`. And according to stack-trace, your error originated from `jest-expo` module, so your better to report it to them ;-)
