### ISSUE TITLE
I can build without error in xcode, but can't build in terminal(occur error)

### ISSUE THREAD

**Issue by starcraft0429** [facebook/react-native#11531]
** BUILD FAILED **

The following build commands failed:
	CompileC /Users/~my_project~/ios/build/Build/Intermediates/RCTSettings.build/Debug-iphonesimulator/RCTSettings.build/Objects-normal/x86_64/RCTSettingsManager.o RCTSettingsManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/~my_project~/ios/build/Build/Intermediates/RCTAnimation.build/Debug-iphonesimulator/RCTAnimation.build/Objects-normal/x86_64/RCTFrameAnimation.o Drivers/RCTFrameAnimation.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

Thanks

**Comment by adrianotadao** [comment]
@starcraft0429 I have the same error. Are you solved it?

**Comment by starcraft0429** [comment]
@adrianotadao I didn't fix it.
and never need to fix it.
I think, It must include xcworkspace file so it can be compiled without error.
I am build by using .xcworkspace file
Regards

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.

**Comment by chrisrobbins** [comment]
I am getting a similar error.

ios/build/Build/Intermediates/RCTAnimation.build/Debug-iphonesimulator/RCTAnimation.build/Objects-normal/x86_64/RCTNativeAnimatedModule.o RCTNativeAnimatedModule.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Any ideas on how to get past this?

"dependencies": {
    "@remobile/react-native-splashscreen": "^1.0.7",
    "@remobile/react-native-toast": "^1.0.6",
    "axios": "^0.16.2",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "eslint-config-rallycoding": "^3.2.0",
    "firebase": "^4.2.0",
    "lodash": "^4.17.4",
    "react": "16.0.0-alpha.6",
    "react-native": "^0.44.0",
    "react-native-swipeable": "^0.6.0",
    "react-redux": "^5.0.5",
    "react-throttle": "^0.3.0",
    "redux": "^3.7.2",
    "redux-devtools-extension": "^2.13.2",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.2.0",
    "throttle-debounce": "^1.0.1"
  },
  "devDependencies": {
    "babel-preset-react-native": "^2.1.0",
    "babel-preset-stage-2": "^6.24.1"
  }
}
