### ISSUE TITLE
Custom Navigator.SceneConfig Documentation

### ISSUE THREAD

**Issue by richardkazuomiller** [facebook/react-native#11536]
Currently the `Navigator` documentation lists the default `SceneConfig`s (`PushFromLeft`,`FloatFromBottom`, etc) but is unclear when it comes to using other configurations than the included ones. Right now I'm doing this to use `PushFromRight` but disable the gesture to swipe back to the previous scene:

````
const noSwipeSceneConfig = {}
Object.assign(noSwipeSceneConfig,Navigator.SceneConfigs.PushFromRight)
noSwipeSceneConfig.gestures = null
````

Since I couldn't find any documentation regarding custom `SceneConfig`s and figured that out by digging around in the source code, I'm wondering if that's something I should be doing or if those are meant to be private and `Navigator` could be changed in future versions in some way that would break what I've done now.

**Comment by SupriyaKalghatgi** [comment]
+1

**Comment by ericvicenti** [comment]
We are planning on deprecating navigator and focus on documenting the newer navigation solution, based off of NavigationExperimental
