### ISSUE TITLE
UIExplorer example crashed at native animated examples.

### ISSUE THREAD

**Issue by kiok46** [facebook/react-native#11532]
### Description

Was going through UIExplorer example and it crashed at `Native Animated Examples`-> `translateX => Animated.decay` -> crashed on pressing the blue box.
<img width="325" alt="screen shot 2016-12-19 at 3 33 06 am" src="https://cloud.githubusercontent.com/assets/7335120/21296916/648ab782-c59c-11e6-9662-9131a530df0b.png">

Bug report:
<img width="322" alt="screen shot 2016-12-19 at 3 33 18 am" src="https://cloud.githubusercontent.com/assets/7335120/21296938/ce1912b6-c59c-11e6-8fe1-385e93317104.png">

### Reproduction
well, just run the Example/UIExplorer example.

### Solution

I can't really send a PR right now. sorry :)

### Additional Information

* React Native version: [react-native: 0.39.0, react-native-cli: 1.3.0 ]
* Platform: iOS - 5s 9.3 (Simulator)
* Operating System: MacOS OSX El Capitan version 10.11.5

If you need anything else, feel free to ask :)

**Comment by ericvicenti** [comment]
Is this still a problem? @janicduplessis, is this resolved?

**Comment by janicduplessis** [comment]
I don't think we added support for decay anims in native animated, not sure why there is an example and if it ever worked.

cc @ryangomba

**Comment by ryangomba** [comment]
It's implemented on android but not iOS

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.

**Comment by janicduplessis** [comment]
Decay is implemented on ios too now

**Comment by kiok46** [comment]
@janicduplessis Could you please provide a link to the PR which solved the issue?
@hramos Hey, If the issue is not solved then I don't think that it's a good idea to close only because it is inactive. :)

**Comment by janicduplessis** [comment]
https://github.com/facebook/react-native/pull/13368
