### ISSUE TITLE
[Navigator] API: componentWill/DidFocus & componentWill/DidBlur

### ISSUE THREAD

**Issue by ide** [facebook/react-native#1153]
These functions are similar to componentWill/DidAppear and componentWill/DidDisappear in UIKit in that they let you do things like pause tasks and hide the keyboard when a screen is no longer active. The navigator's semantics is a little different than UIViewController so the APIs don't need to be super identical -- I'm mainly looking to get notified when a screen will show / did show / will hide / did hide.

I'll put up some diffs that use `onWill/DidFocus` to achieve this with the help of a routing library I've written. It acts as a sort of test bed for these APIs that can either make their way into Navigator itself or Navigator's API can grow to accomodate these libraries.

Code I'm imagining:
```
class X extends React.Component {
  componentDidFocus() {
    this.refs.textInput.focus();
  }
}
```

**Comment by ericvicenti** [comment]
Oops, sorry I missed this. Feel free to cc me next time so I get emailed.

This looks like a good idea to me!

**Comment by skevy** [comment]
@ide any progress on this library? or any tips on how to do this?

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by ide** [comment]
The willfocus and didfocus events address this. Still could use blur but will open up new issues once the new Navigator work nears completion.
