### ISSUE TITLE
SwipeableListView does not allow custom getNewDataSource parameters

### ISSUE THREAD

**Issue by MrCeleryman** [facebook/react-native#11533]
### Description

Basically SwipeableListView does not allow for custom parameters in the getNewDataSource Method.
I've made changes locally to allow for this but am inexperienced with pull requests and the such so I'd rather bring it here for discussion first.

### Solution

```
 static getNewDataSource(): Object {
    return new SwipeableListViewDataSource({
      getRowData: (data, sectionID, rowID) => data[sectionID][rowID],
      getSectionHeaderData: (data, sectionID) => data[sectionID],
      rowHasChanged: (row1, row2) => row1 !== row2,
      sectionHeaderHasChanged: (s1, s2) => s1 !== s2,
    });
 }
```

And this is my local edit:

```
static getNewDataSource(params: ParamType): Object {
    return new SwipeableListViewDataSource({
	  getRowData: (params.getRowData) ?
	  	params.getRowData : (data, sectionID, rowID) => data[sectionID][rowID],
	  getSectionHeaderData: (params.getSectionHeaderData) ?
	  	params.getSectionHeaderData : (data, sectionID) => data[sectionID],
	  rowHasChanged: (params.rowHasChanged) ?
	  	params.rowHasChanged : (row1, row2) => row1 !== row2,
	  sectionHeaderHasChanged: (params.sectionHeaderHasChanged) ? 
	  	params.sectionHeaderHasChanged : (s1, s2) => s1 !== s2
    });
}
```

### Additional Information

* React Native version: 0.39.2
* Platform: Android
* Operating System: Windows

**Comment by MrCeleryman** [comment]
Updated to 0.42 and still the same issue, I just make the change locally each time and it works fine but still haven't got around to doing a proper PR could anyone else have a look at this?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/swipeablelistview-does-not-allow-custom-getnewdatasource-parameters
