### ISSUE TITLE
Changing the bundle ID breaks the upgrader

### ISSUE THREAD

**Issue by richardkazuomiller** [facebook/react-native#11543]
I've changed the bundle ID of my app to the usual `com.something.somethingelse` format but because of that `react-native-git-upgrade` fails. It writes a bunch of files to paths defined using the `name` in `package.json`, fails, then resets all the changes.

Is there any way to tell the upgrader what the bundle ID of the apps is supposed to be?

Another problem is that the thing that is supposed to show what part of the upgrade process is broken is apparently broken.

```
git-upgrade info Commit new version template 
git-upgrade info Generate the patch between the 2 versions 
git-upgrade info Save the patch in temp directory 
git-upgrade info Reset the 2 temporary commits 
git-upgrade info Apply the patch 
fatal: unrecognized input
git-upgrade WARN The upgrade process succeeded but there might be conflicts to be resolved. See above for the list of files that have merge conflicts. 
git-upgrade info Upgrade done 
```

^^^ Unfortunately, there is no `list of files` which I'm guessing has something to do with the fatal unrecognized input.

**Comment by g3r4n** [comment]
Got the same issue to upgrading from 0.39.2 to 0.40.0

**Comment by vinceprofeta** [comment]
@g3r4n were you able to fix the issue?

**Comment by srhise** [comment]
Unrelated to changing bundleID, i get this when upgrading to 0.40

**Comment by g3r4n** [comment]
@vinceprofeta I have delete the android and iOS folder. I run `react-native init` and `react-native link` ti recreate these folder.

**Comment by MatthiasDebaere** [comment]
@g3r4n 'not using react-native-git-upgrade' is not a fix. You would lose all manual changes in these folders, the kind of changes that react-native-git-upgrade should help with merging.

And yes, I get the same `fatal: unrecognized input` error with no extra info (even using --verbose).

**Comment by alnorris** [comment]
I'm getting the same from 0.37.0, any help to get around this one anyone?

**Comment by richardkazuomiller** [comment]
I understand people have priorities but the fact that no one involved with the project has replied makes me sad.

I thought the bundle ID had something to do with it because it was creating files in the wrong directory and stuff, but apparently it doesn't work at all for some people. There's a lot about this feature that is ... weird. I don't really understand all what's going on with all the tricky git stuff and I don't have time to look into it. I think it's a cool idea but needs a lot of polishing to get it to work.

I gave up and upgraded manually.

**Comment by mikaello** [comment]
I got the same problem, this worked for me: 

**Edit `~/.gitconfig` and change** 
```
[color]
	ui = always
```
to
```
[color]
	ui = auto
```

I figured this out by manually trying to git apply the patch-file in the folder printed at the end of `react-native-git-upgrade --verbose` (you have to use `--verbose` for this folder to be printed). This patch-file was color-coded because I had `ui = always`, and this was the reason git printed `fatal: unrecognized input`.

**Comment by g3r4n** [comment]
I correct the issue by upgrading the tools and RN

**Comment by ncuillery** [comment]
@richardkazuomiller, @vinceprofeta @srhise, @MatthiasDebaere, @alnorris Are you still able to reproduce this error using the recent version 0.2.6 of react-native-git-upgrade ?

**Comment by flyingace** [comment]
@ncuillery While I am not one of the previous posters you listed I came here b/c I was experiencing the reported issue with version 0.2.5 of react-native-git-upgrade
```
git-upgrade info Apply the patch 
fatal: unrecognized input
```
and was seeking a solution. I have now upgraded to react-native-git-upgrade 0.2.6 and I am still experiencing the same issue.

**Comment by MatthiasDebaere** [comment]
Getting an other error now:

```
git-upgrade info Commit new version template
[master 1e1ab7b] New version
git-upgrade info Generate the patch between the 2 versions
git-upgrade info Save the patch in temp directory
git-upgrade info Reset the 2 temporary commits
HEAD is now at 8ed1468 Project snapshot
git-upgrade info Apply the patch
error: unrecognized input
git-upgrade WARN The upgrade process succeeded but there might be conflicts to be resolved. See above for the list of files that have merge conflicts.
git-upgrade info Upgrade done
git-upgrade info Temporary working directory: C:\Users\debaema\AppData\Local\Temp\react-native-git-upgrade
```

and it resets to the project snapshot. Thing is, we have changed a lot of stuff in platform specific project files so I can understand updating RN would be difficult for a tool which checks for manual changes and doesn't want to overwrite them..

**Comment by wcandillon** [comment]
I'm also experiencing this issue with `"react-native-git-upgrade": "0.2.7"`

**Comment by wcandillon** [comment]
I found what was the issue for me. I had updated and installed the new react package I was looking for. I started again from scratch (just making sure that I was using `"react-native-git-upgrade": "0.2.7"`) and it worked nicely.

**Comment by RichardLindhout** [comment]
I run 0.2.7 and got the same error:

```
eact-native-git-upgrade
git-upgrade info Check for updates
git-upgrade info Read package.json files
git-upgrade info Check declared version
git-upgrade info Check matching versions
git-upgrade info Check React peer dependency
git-upgrade info Check that Git is installed
git-upgrade info Get information from NPM registry
git-upgrade info Upgrading to React Native 0.44.0, React 16.0.0-alpha.6
git-upgrade info Setup temporary working directory
git-upgrade info Configure Git environment
git-upgrade info Init Git repository
git-upgrade info Add all files to commit
git-upgrade info Commit current project sources
git-upgrade info Create a tag before updating sources
git-upgrade info Generate old version template
git-upgrade info Add updated files to commit
git-upgrade info Commit old version template
git-upgrade info Install the new version
npm WARN @shoutem/animation@0.8.10 requires a peer of react@^15.0.0 but none was installed.
npm WARN babel-loader@6.4.1 requires a peer of webpack@1 || 2 || ^2.1.0-beta || ^2.2.0-rc but none was installed.
npm WARN native-base-shoutem-theme@0.1.3 requires a peer of react@>=15.1.0 but none was installed.
npm WARN react-native-interactable@0.0.8 requires a peer of react@>= 15.4.1 but none was installed.
npm WARN react-native-svg@5.1.7 requires a peer of react@>=15.4.0 but none was installed.
npm WARN react-static-container@1.0.1 requires a peer of react@^0.13.0 || ^0.14.0 || ^15.0.0 but none was installed.
git-upgrade info Generate new version template
git-upgrade info Add updated files to commit
git-upgrade info Commit new version template
git-upgrade info Generate the patch between the 2 versions
git-upgrade info Save the patch in temp directory
git-upgrade info Reset the 2 temporary commits
git-upgrade info Apply the patch
fatal: unrecognized input
git-upgrade WARN The upgrade process succeeded but there might be conflicts to be resolved. See above for the list of files that have merge conflicts.
git-upgrade info Upgrade done

```

**Comment by RichardLindhout** [comment]
Crashed at this one: `git apply --3way ${patchPath}`
Fix: `git apply --3way --no-color ${patchPath}`

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/changing-the-bundle-id-breaks-the-upgrader

**Comment by pie6k** [comment]
Still having this issue

```
git-upgrade info Check for updates
git-upgrade info Using yarn 1.3.2
git-upgrade info Read package.json files
git-upgrade info Check declared version
git-upgrade info Check matching versions
git-upgrade info Check React peer dependency
git-upgrade info Check that Git is installed
git-upgrade info Get information from NPM registry
git-upgrade info Upgrading to React Native 0.53.0, React 16.2.0
git-upgrade info Setup temporary working directory
git-upgrade info Configure Git environment
git-upgrade info Init Git repository
git-upgrade info Add all files to commit
git-upgrade info Commit current project sources
git-upgrade info Create a tag before updating sources
git-upgrade info Generate old version template
git-upgrade info Add updated files to commit
git-upgrade info Commit old version template
git-upgrade info Install the new version
warning " > apollo-cache-inmemory@1.1.9" has incorrect peer dependency "graphql@0.11.7 || ^0.12.0".
warning " > apollo-client@2.2.5" has incorrect peer dependency "graphql@^0.11.0 || ^0.12.0".
warning " > graphql-tag@2.7.3" has incorrect peer dependency "graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0".
warning " > react-native-fbsdk@0.7.0" has unmet peer dependency "prop-types@15.x.x".
warning " > babel-jest@22.2.2" has unmet peer dependency "babel-core@^6.0.0 || ^7.0.0-0".
git-upgrade info Generate new version template
git-upgrade info Add updated files to commit
git-upgrade info Commit new version template
git-upgrade info Generate the patch between the 2 versions
git-upgrade info Save the patch in temp directory
git-upgrade info Reset the 2 temporary commits
git-upgrade info Apply the patch
error: unrecognized input
git-upgrade WARN The upgrade process succeeded but there might be conflicts to be resolved. See above for the list of files that have merge conflicts.
git-upgrade info Upgrade done
```

**Comment by hramos** [comment]
I advise opening a new issue, since this one was closed due to lack of a template + inactivity.
