### ISSUE TITLE
Navigator not updating view/scene after push.

### ISSUE THREAD

**Issue by ibrierley** [facebook/react-native#11544]
Navigator doesn't update the scene/view when given a new route via push.

I am trying the example given on SO at http://stackoverflow.com/questions/29335523/react-native-custom-navigation-with-navigator-component

Code is below...

If I click on feedview, it displays it in the console, but never any updated to the view/scene, so this feels like a bug ?

```import React, { Component } from 'react';
import { Text, Navigator, TouchableHighlight, View, AppRegistry } from 'react-native';

class App extends React.Component {
    render() {
        return (
            <Navigator
                initialRoute={{name: 'WelcomeView', component: WelcomeView}}
                configureScene={() => {
                    return Navigator.SceneConfigs.FloatFromRight;
                }}
                renderScene={(route, navigator) => {
                    console.log(route, navigator);

                    if (route.component) {
                        return React.createElement(route.component, { navigator });
                    }
                }}
             />
        );
    }
}

class FeedView extends React.Component {
  constructor( props ) {
    super( props );
    console.log('feedview');
  }



    render() {
        return (
            <View>
                <Text>
                    Feed View!
                </Text>
            </View>
        );
    }
}

class WelcomeView extends React.Component {
    onPressFeed() {
        this.props.navigator.push({
            name: 'FeedView',
            component: FeedView
        });
    }

    render() {
        return (
            <View>
                <Text>
                    Welcome View!
                </Text>

                <Text onPress={this.onPressFeed.bind(this)}>
                    Go to feed!
                </Text>
            </View>
        );
    }
}


AppRegistry.registerComponent('app', () => App);
```

react-native-cli: 1.3.0
react-native: 0.39.1
Linux Mint 18
Checking via Android-Studio
Android Emulator platform 6.0 API 23

**Comment by ian-workcircle** [comment]
Curiously this seems to work on my other pc which is running react-native-cli: 1.3.0
react-native: 0.39.2, trying to find out if there are any other differences

**Comment by ibrierley** [comment]
Curiously this seems to work ok on my other pc running react-native: 0.39.2

**Comment by ibrierley** [comment]
Looks like there was something odd with the avd. I ended up upgrading react-native to 0.39.2 (which I don't think made a difference, but including for completeness). Then I deleted the avd, created a new one (target name Android 6.0 Platform 6.0 API 23 Intel Atom x86_64) selected delete all user data, and then it seems to work.
