### ISSUE TITLE
Packager isn't detecting changes on node_modules

### ISSUE THREAD

**Issue by rseemann** [facebook/react-native#11549]
### Description

Making changes on files on `node_modules` does not trigger a change in the bundler, therefore the new changes are not bundled into the app unless the packager is restarted.

### Reproduction

Change a file at the `node_modules` folder and check that the bundler does not detect the file change (https://github.com/facebook/react-native/blob/ede04abf8f4463155c196c6cfb8ea47684e8c6b8/packager/react-packager/src/Server/index.js#L396 is never called). Older versions of react-native would detect this and mark the file as outdated.

### Solution
Reenable the watching of node files or allow a way to customise this via config/env variables

### Additional Information

* React Native version: 0.39.2
* Platform: iOS
* Operating System: MacOS

**Comment by rseemann** [comment]
Adding the package name [here](https://github.com/facebook/react-native/blob/72157cf99164d00c7a14b6b9ca51b406080b5265/packager/defaults.js#L36) seems to fix the problem. Is there a way to pass this parameter via command line or env variable?

**Comment by santervo** [comment]
Same here. Installing new modules with npm install are not picked by app. I need to stop the packager and restart it completely.

**Comment by farwayer** [comment]
duplicate https://github.com/facebook/react-native/issues/11301

**Comment by rseemann** [comment]
Close in favor of https://github.com/facebook/react-native/issues/11301
