### ISSUE TITLE
webview's new function on message not working

### ISSUE THREAD

**Issue by wzy535** [facebook/react-native#11552]
### Description

[FILL THIS OUT: webview's new function onmessage not working.]

### Reproduction

[FILL THIS OUT:  https://rnplay.org/apps/1RLF9A .]

### Solution

[FILL THIS OUT:]

### Additional Information

* React Native version: [0.39.2]
* Platform: [both]
* Operating System: [MacOS  Windows]

**Comment by caoyang819** [comment]
Above is ok now. but the webview can't load url now .

**Comment by caoyang819** [comment]
webview can't place in view label like this:

`import React, { Component } from 'react';
import { WebView,View } from 'react-native';

class MyWeb extends Component {
  render() {
    return (
<View>
      <WebView
        source={{uri: 'https://github.com/facebook/react-native'}}
        style={{marginTop: 20}}
      />
</View>
    );
  }
}`

this not working too.

React Native version: [0.40.0]
Platform: [both]
Operating System: [MacOS Windows]

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
