### ISSUE TITLE
Build operation failed without specifying any errors for React Native XCode project

### ISSUE THREAD

**Issue by AdrianZghibarta** [facebook/react-native#11557]
have a React Native project that works fine most of the time(Android and iOS). But sometimes out of nowhere I receive this error when I am trying to build the Xcode project (Xcode or react-native run-ios):

> Build operation failed without specifying any errors. 
Individual build tasks may have failed for unknown reasons.
One possible cause is if there are too many (possibly zombie)
processes; in this case, rebooting may fix the problem.
Some individual build task failures (up to 12) may be listed below.

How do I solve this? Push to a branch on git, fresh clone, npm install, and all is working fine for a period. And after that the problem will repeat. Making fresh clones of project each time is a pain and takes long time. Is there another way or something that I don't know?

Maybe a some files that are in .gitignore is causing the problems, and after a fresh clone that solves the problem. This is the .gitignore file for my iOS project:

>build/
*.pbxuser
!default.pbxuser
*.mode1v3
!default.mode1v3
*.mode2v3
!default.mode2v3
*.perspectivev3
!default.perspectivev3
xcuserdata
*.xccheckout
*.moved-aside
DerivedData
*.hmap
*.ipa
*.xcuserstate
project.xcworkspace

[stackoverflow link](http://stackoverflow.com/questions/41239452/build-operation-failed-without-specifying-any-errors-for-react-native-xcode-proj)

**Comment by MatthieuLemoine** [comment]
I have this issue too since updating to react-native 0.39 from 0.34 yesterday. Which version do you use @kingadrianzghibarta  ?

**Comment by kingadrianzghibarta** [comment]
@MatthieuLemoine I use version 0.38.1, on version 0.38.0 this issue was not present.

**Comment by kingadrianzghibarta** [comment]
@MatthieuLemoine I use version 0.38.1, on 0.38.0 this issue wasn't present.

**Comment by MatthieuLemoine** [comment]
@kingadrianzghibarta Have you tried to downgrade RN to 0.38.0 ?

**Comment by kingadrianzghibarta** [comment]
@MatthieuLemoine No, I am waiting  0.40 version.

**Comment by knot123** [comment]
any update? I have the same problem

**Comment by kingadrianzghibarta** [comment]
@knot123 no update at the moment. Now I am using 0.40 version and this problem appears only some times, and I think is somehow related to Android Studio, because very often this problem occurs after making some operations in AS.

**Comment by MatthieuLemoine** [comment]
@AdrianZghibarta i also think that it's related to Android Studio as it began to happen to me when i started to test my app on Android. I was only testing on iOS before that for several months without problems.

**Comment by MatthieuLemoine** [comment]
@Crash-- I definitely think that it's related to Android Studio as I had no issue for a week before i opened Android Studio again and build from it instead of building from CLI and then XCode build was broken again.

**Comment by MatthieuLemoine** [comment]
Nuking ``node_modules`` and avoiding to build with Android Studio seems to fix this issue.

**Comment by Crash--** [comment]
I still got this issue after upgraded to RN 0.42. Even with a fresh project. I had to copy/paste my node_modules every time I want to write some native Android Code... Pretty annoying :(

**Comment by jpamarohorta** [comment]
Any idea why this sometimes happens? I'm having the same problem and I usually develop iOS e Android +- at the same time

**Comment by robwalkerco** [comment]
@jpamarohorta Not sure why it happens, but I can fix it by deleting `node_modules` and re-running `yarn` (or `npm install`).

I can only guess that Android Studio is somehow changing stuff in `node_modules` but as I ignore the folder in git, I have not been able to see what. Perhaps we should try adding it to git, then see what has changed when the error occurs? Will report back what I find!

**Comment by nickkapoor** [comment]
Wtg @robwalkerco Thank you

**Comment by zhuyifan2013** [comment]
remove the React Native Bundle script from Build phase solves me.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/build-operation-failed-without-specifying-any-errors-for-react-native-xcode-proj
