### ISSUE TITLE
onNavigationStateChange after redirect url is incomplete on android

### ISSUE THREAD

**Issue by buptyyf** [facebook/react-native#11558]
when I use webview on android, after url redirect,I catch new url by onNavigationStateChange is incomplete,but on iOS is complete url.
such as the new right url is "https://github.com?token=xxxxx",android only return "https://github.com", don't have params.

**Comment by liuhong1happy** [comment]
+1

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/onnavigationstatechange-after-redirect-url-is-incomplete-on-android

**Comment by Vis24Freelancer** [comment]
Yes ,on Android it returns the previous url and its a huge bug i think. Please do something for it otherwise my whole effort of 2 months will be ruined. Please help me .
