### ISSUE TITLE
How to test my app in release mode on my real device?

### ISSUE THREAD

**Issue by benjaminb10** [facebook/react-native#11566]
Hi,
I'm having the bug with a brand new app.

When I am in debug mode I can run my app on my device with Xcode.
But when I change the mode to **release**, and edit product scheme also, I have the following error:

![screenshot_2016-12-20 18 16 00_sob7iw](https://cloud.githubusercontent.com/assets/2952678/21360487/64dae15e-c6e0-11e6-8fdc-e9aa70b74130.png)

My project configuration is:
![screenshot_2016-12-20 18 08 44_u9xdpg](https://cloud.githubusercontent.com/assets/2952678/21360269/81b0bb7e-c6df-11e6-9e09-88986f6f8caf.png)

And I've edited product scheme like that:
![screenshot_2016-12-20 18 18 18_7avn0v](https://cloud.githubusercontent.com/assets/2952678/21360566/b8d01e64-c6e0-11e6-946f-d46656b9eaca.png)

I've just followed the official documentation so I'm a bit confused.
Any help would be great :)

**Comment by benjaminb10** [comment]
I succeed it thanks to this answear: https://github.com/facebook/react-native/issues/2685#issuecomment-267544679

**Comment by tomchambers2** [comment]
Was having the same issue, managed to fix it by turning off dead code stripping as mentioned in the issue linked by @benjaminb10
