### ISSUE TITLE
Reloading the app in dev build incorrectly sets AppState

### ISSUE THREAD

**Issue by Ehesp** [facebook/react-native#11563]
### Description

We're currently using AppState to detect when the app is in either `active` or `background` state. This works as expected, however when running a debug build and "Reload"ing the JavaScript bundle, the AppState is set to `background`. When the app/bundle has reloaded, the AppState never sets back to `active`.

### Reproduction

```
componentDidMount() {
    AppState.addEventListener('change', this.handleAppStateChange);
}

handleAppStateChange = (state) => {
    console.warn('STATE', state)
}

```

Reload the app, in Android logs the `STATE` is set to `background` and never reset back to `active`.

### Solution

Assuming this is an issue, a current work around is to do:

```
componentDidMount() {
    AppState.addEventListener('change', this.handleAppStateChange);
    this.handleAppStateChange('active');
}
```

### Additional Information

* React Native version: 0.39
* Platform: Android
* Operating System: MacOS

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.

**Comment by Ehesp** [comment]
Depends if Facebook see it as a bug or nuisance :)
