### ISSUE TITLE
[CameraRollExample] R/W storage permissions are disabled on install

### ISSUE THREAD

**Issue by harokevin** [facebook/react-native#11577]
### Description
After successfully installing the UIExplorer example application on android devices I selected the CameraRoll list item. I expected the example to display images stored in device storage. The following error was displayed:

> console.error: "Error: "Could not get photos: need READ_EXTERNAL_STORAGE permission". Stack: createErrorFromErrorData@http://localhost:8081/Examples/UIExplorer/js/UIExplorerApp/android.bundle?platform=android&dev=true&hot=false&minify=false:4288:20

This error is thrown by [CameraRollManager.Java](https://github.com/facebook/react-native/blob/9ee815f6b52e0c2417c04e5a05e1e31df26daed2/ReactAndroid/src/main/java/com/facebook/react/modules/camera/CameraRollManager.java) around line 295.

### Reproduction
I was unable to recreate the project in rnplay.org but following the [UIExplorer README](https://github.com/facebook/react-native/tree/master/Examples/UIExplorer) will produce the same results. I was able to reproduce this bug on a Nexus 5 emulator(Android 6.0, API 23, RAM 2048, VM Heap 256, Internal Storage 200) and a physical Galaxy S5 (Android 6.0.1, API 23, RAM 2048).

### Solution
A temporary workaround is to manually go into the installed app's 'App info' menu>Permissions>Toggle Storage On. I believe an actual solution may be to include the READ_EXTERNAL_STORAGE permission into one of the many android manifests. I tried this but was faced with build errors such as: 

> * What went wrong:
> Execution failed for task ':Examples:UIExplorer:android:app:processDebugResources'.
>  java.io.IOException: Could not delete path 'C:\Users\superawesomeuser\Desktop\react-native\Examples\UIExplorer\android\app\build\generated\source\r\debug\android\support\v7'.

### Additional Information
* React version: [15.4.1]
* React Native version: [n/a -  nowhere in the file structure is it considered a project]
* React Native CLI version: [2.0.1]
* Platform: [Android]
* Operating System: [Windows 64-bit]

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
