### ISSUE TITLE
Unable to use scaleX, scaleY on <View>

### ISSUE THREAD

**Issue by amitverma** [facebook/react-native#1157]
I have been trying to use `scaleX` and `scaleY` on a `<View/>` component, but it is not working. Do I need to keep something in mind while using it?

**Comment by brentvatne** [comment]
@amitverma - the documentation seems to be a bit unclear about this, this is how you need to specify it:

```javascript
<View style={{flex: 1, transform: [{translateY: 50}, {scaleX: 0.5}, {scaleY: 0.5}]}}>
   <Text>Text here!</Text>
</View>
```

**Comment by brentvatne** [comment]
Updated docs to remove this, working on fixing up to better display those options under the `transform` prop

**Comment by amitverma** [comment]
thanks @brentvatne for clearing things up. would switching order between `scaleX` and `scaleY` also produce different results?

**Comment by brentvatne** [comment]
@amitverma - nope, those should be the same as they scale the X and Y axis independently and irrespective of aspect ratio. Another interesting thing to know is you can apply transforms multiple times:

`transform: [{scaleX: 0.5}, {scaleY: 1.5}, {scaleX: 1.5}]` :smile:

**Comment by brentvatne** [comment]
See #1181 for doc fix
