### ISSUE TITLE
On Android, when Location Services is disabled, geolocation.getCurrentPosition returns an error as a string, instead of an object according to spec

### ISSUE THREAD

**Issue by mwiley** [facebook/react-native#11587]
### Description/Reproduction

Disabling 'Location Services' in Android's system settings, and then calling navigator.geolocation.getCurrentPosition will result in an error, 'No available location provider.', instead of an object, where that's the value of message.

### Solution

In LocationModule.java, change this line:

    error.invoke("No available location provider.");

to this, to match the phrasing of the same error from startObserving

    emitError(PositionError.PERMISSION_DENIED, "No location provider available.");

### Additional Information

* React Native version: 0.39
* Platform: Android

**Comment by brentvatne** [comment]
pull request welcome!

**Comment by no-username** [comment]
Please resolve this issue

**Comment by mwiley** [comment]
I created a pull request, #11723.

**Comment by mwiley** [comment]
I created pull request #11723.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/on-android-when-location-services-is-disabled-geolocationgetcurrentposition-retu

**Comment by victorbadila** [comment]
I am using react-native version 0.47.1 and this issue is still there, has not been fixed. Think this might need to be reopened.

**Comment by quangtran9kz** [comment]
i am using rn v0.48 and this issue is still there.How to fix it ???

**Comment by paulbib** [comment]
I'm getting the same issue. error handler is never getting called. the app is hanging.

**Comment by jamesone** [comment]
I'm using `"react-native": "0.44.0",` & this is still occurring.

**Comment by choo737** [comment]
same here "react-native": "0.45.1"

**Comment by jamesone** [comment]
I worked around this using the following: I used a timeout function which runs a fallback location query if X seconds passes. I ensure that this only happens if `Platform.OS === 'android'`

**Comment by Schabaani** [comment]
same here "react-native": "0.53.0"

**Comment by 28harishkumar** [comment]
+1 with react-native: 0.55.4

**Comment by brentvatne** [comment]
you folks do know this is open source and you can open a PR to fix this, right? :)

**Comment by dulmandakh** [comment]
fix landed in 0.56.0 version (https://github.com/facebook/react-native/commit/226bff3ed0772ff3b9d69ea45fb57f3c0c930029), please check.
