### ISSUE TITLE
Cannot copy error message text in RN 0.39.2 + iOS simulator

### ISSUE THREAD

**Issue by jcollum** [facebook/react-native#11588]
### Description

Copy button in simulator does not work.

### Reproduction

1. Start an app in iOS 10.0 simulator. 
1. Hit an error. 
1. Try either of the following: Click "Copy" in lower right or Cmd-Opt-C. 
1. Try to paste text elsewhere

Result: Text is not copied. 

Screen grab: [2016-12-21_15-26-00.zip](https://github.com/facebook/react-native/files/667616/2016-12-21_15-26-00.zip)

### Additional Information

Logs: 

```
Dec 21 15:20:58 por-collumj-m pasted[20095] <Warning>: ...requesting pasteboard com.apple.UIKit.pboard.general completed. Error: (null)
Dec 21 15:20:58 por-collumj-m pasted[20095] <Warning>: Bundle ID com.apple.CoreSimulator.CoreSimulatorBridge from team (null) is requesting item 0 of type public.utf8-plain-text from pasteboard named com.apple.UIKit.pboard.general with UUID 0415C2E6-AEAA-4B3D-9D3A-05C68D491751
Dec 21 15:20:58 por-collumj-m pasted[20095] <Warning>: Loading item 0x7ff7d1403950 BA0368A0-DDDF-4D5A-ADBF-E6B50FDDD857 type public.utf8-plain-text from URL file:///Users/collumj/Library/Developer/CoreSimulator/Devices/9778FCC1-5BF9-4329-AFA8-CCC0BE5F7293/data/Library/Caches/com.apple.Pasteboard/eb77e5f8f043896faf63b5041f0fbd121db984dd/dbba4bc07418837167d9784fce175f0ddcd85ae5
Dec 21 15:20:58 por-collumj-m pasted[20095] <Warning>: ...item request completed. Error: (null)
Dec 21 15:20:58 por-collumj-m CoreSimulatorBridge[20078] <Warning>: Pasteboard change count 25 is updated with new types: (
	        (
	        "public.utf8-plain-text"
	    )
	)
```

Versions: 
```
$ versions
npm 3.10.8
node v6.9.1
OS:
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G31

```

Simulator: iPhone 6 - iOS 10.0

**Comment by TheChuckster** [comment]
Any updates on this?

**Comment by jcollum** [comment]
@shergin this is still happening in 0.43.2 

```
$ react-native -v
react-native-cli: 2.0.1
react-native: 0.43.2
```

It was reported 3 months ago. Is there any movement?

**Comment by Guacaswole** [comment]
Not just me then :(

**Comment by agersoncgps** [comment]
Happening to me to. Makes debugging harder.

**Comment by klvs** [comment]
Also experiencing this. It certainly did work at one point.

**Comment by jcollum** [comment]
Coming up on 6 months!

**Comment by klvs** [comment]
Notably, you can copy (at least in my case) errors from the packager terminal window. I'm going to take a look at why it doesn't work as expected when I get the chance.

**Comment by agersoncgps** [comment]
You can also turn on remote debugging and see the errors in the console. They are copiable from there.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/cannot-copy-error-message-text-in-rn-0392--ios-simulator

**Comment by jcollum-cambia** [comment]
It got moved to a "feature request"? This is a bug. It should stay here. 

>because it has been inactive for a while

It's been inactive because none of the devs have looked into it.

**Comment by hramos** [comment]
There's a handful of comments here already, so I am not sure what you mean by "none of the devs have looked into it". This is a community project, and anyone can submit a PR with a fix.

If you feel strongly about seeing this fixed, can I suggest editing the original post to follow the issue template? Providing all the information there will go a long way towards helping people who may want to work on a PR. Thanks!

**Comment by jcollum-cambia** [comment]
Will do if it happens again. Not working in RN lately, so it could be a while. Anyone else want to take care of it?
