### ISSUE TITLE
TouchableNativeFeedback - Error while Updating

### ISSUE THREAD

**Issue by PetrChalov** [facebook/react-native#11580]
### Description
When using this code:
`                <TouchableNativeFeedback
                    background={TouchableNativeFeedback.Ripple('#e2e9f6',false)}
                    delayPressIn={0}>
                    <View>
                        <Text>I'm button</Text>
                    </View>
                </TouchableNativeFeedback>
`
here Samsung Galaxy S2 device error occurs:
![image](https://cloud.githubusercontent.com/assets/13746723/21385401/d3c6e44e-c787-11e6-8a79-63136bf250e2.png)

If View not put into TouchableNativeFeedback, the error does not occur.

On Android 5.0 and above can not be played.

### Solution
Correct behavior View TouchableNativeFeedback on this platform.

### Additional Information

* React Native version: 0.39.2
* Platform: Android 4.1.1 API 16
* Operating System: Linux

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
