### ISSUE TITLE
Button components not aligned correctly with Flexbox layout

### ISSUE THREAD

**Issue by modularity** [facebook/react-native#11599]
### Description

I've been having issues with vertically stacking button components. There seem to be inconsistencies with button alignment in flexbox layouts. In the best case scenario, the buttons all cluster at the top of the screen even though it's specified as justifyContent: 'space-between'. Sometimes, none of the components render and the container is blank. 

### Reproduction

The following example is trying to render a vertical list of buttons that are evenly spaced on the screen. Unfortunately, this example only renders a blank screen aside from the navbar. 

If I revert to static pixel values in CSS, I can render the page correctly. It makes more sense to utilize flexbox for responsive design, so let me know if I'm missing something in the above example.

```

'use strict';
import React, { Component } from 'react';
import {
   Alert,
   Button,
   StyleSheet,
   Text,
   View
 } from 'react-native';

class ClickerQuestion extends Component {

_handlePress(btnValue) { Alert.alert("Thanks, button \"" +btnValue+ "\" has been pressed!"); };

render() {
  return (

   <View style={{flex: 1, flexDirection: 'column', justifyContent: 'center', alignItems: 'center',}}>
    <Button onPress={() => this._handlePress("B")}
              title="A"
              color="#214231" />

    <Button onPress={() => this._handlePress("B")}
              title="B"
              color="#214231" />

    <Button onPress={() => this._handlePress("C")}
              title="C"
              color="#214231" />

    <Button onPress={() => this._handlePress("D")}
            title="D"
            color="#214231" />

    <Button onPress={() => this._handlePress("E")}
            title="E"
            color="#214231" />
    </View>
   );
  }
 }
```

### Additional Information

* React Native version: 0.39.2
* Platform: Android
* Operating System: MacOS and Windows

**Comment by brentvatne** [comment]
Hi there! Please post these types of questions to StackOverflow. If it turns out that there is a bug, it would be helpful if it were compared to the exact behaviour in Chrome.
