### ISSUE TITLE
react-native running error

### ISSUE THREAD

**Issue by zhipengyue** [facebook/react-native#11603]
This error will always occur when i called about react-native on mac'cli. 
for example:
react-native -v;
react-native  init abdd
------------------------------------------------------------------
/usr/local/lib/node_modules/react-native-cli/index.js:266
  const rnPackage = options.version;
  ^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
--------------------------------------------------------------------
How can i fill it.

**Comment by killinit** [comment]
+1 samo problem on Mac os X Sierra

**Comment by bleeckerj** [comment]
+1 same problem on Mac OSX 10.11.16

**Comment by benjis** [comment]
+1 running in to the same issue on Mac OS X 10.10.5

**Comment by rh389** [comment]
Looks like there's a bug in the latest react-native-cli. Try `npm install -g react-native-cli@1.0.0`

**Comment by Fahrradflucht** [comment]
@zhipengyue @killinit @bleeckerj @benjis which node version (`node -v`) is this on?

**Comment by brentvatne** [comment]
Can someone update the getting started docs and suggest that everyone install at minimum the LTS release version? (currently 6.9.2 as per https://nodejs.org/en/)

Doc to be updated: https://facebook.github.io/react-native/docs/getting-started.html

**Comment by Fahrradflucht** [comment]
Well this already states node 4 or newer, which is exactly what is required.

**Comment by bleeckerj** [comment]
@Fahrradflucht `node -v` shows `v0.10.29`

**Comment by killinit** [comment]
node -v
v0.12.7

**Comment by killinit** [comment]
Installing nodejs from https://nodejs.org/en/download/
**solved the problem**
now I have 
node -v
v6.9.2

**Comment by zhipengyue** [comment]
At last,I reinstalled npm and nodejs. the problem was solved!

**Comment by aleakhtar** [comment]
Installing NodeJS separately, solves it. Thanks @killinit !
