### ISSUE TITLE
Why the ios native View No response

### ISSUE THREAD

**Issue by fuhongjie** [facebook/react-native#11619]
I had make a ios ViewManager  then use in the js-code, but the ios native view is show but no response ,i can't touch it. please help me thank you very match.

**Comment by fuhongjie** [comment]
import React, {Component, PropTypes} from 'react';
import {requireNativeComponent} from 'react-native';

// requireNativeComponent 自动把这个组件提供给 "MapScreen"
var RCTMapScreen = requireNativeComponent('MapScreen', MapScreen, {
    nativeOnly: {
        onChange: true,
        onMapReady: true,
        handlePanDrag: true,
    },
});

export default class MapScreen extends React.Component {

    render() {
        return <RCTMapScreen {...this.props}/> ;
    }

}

/**
 * 属性类型，其实不写也可以，js会自动转换类型
 */
MapScreen.propTypes = {};

module.exports = MapScreen;

**Comment by brentvatne** [comment]
Hi! Please post this to http://stackoverflow.com/ :) Happy holidays! 🎄

**Comment by fuhongjie** [comment]
thank you ,and I have solve this problem, I ever use XIB to build a view shitch return in the RTCViewManager,than it can not be touch,now I use code to build it ,it's OK. and merry christmas!!!
