### ISSUE TITLE
[Navigator & ListView & Image] Navigation Breaks Images

### ISSUE THREAD

**Issue by soheil** [facebook/react-native#1161]
If you push components two levels deep in the navigator and pop back to root if you had any images in the root component they no longer get updated if you change the image URL on the state.

```
              <Image
                source={{uri: rowData.posters.thumbnail}}
                style={styles.cellImage} />
```

if you change `rowData.posters.thumbnail` image does not update anymore.

**Comment by brentvatne** [comment]
Any chance you could post a minimal example of this?

**Comment by soheil** [comment]
There you go: https://gist.github.com/soheil/d96c86fa72b68317e73a

Also if you change the number of rows to less than 10 it won't refresh the rows after state changes.

**Comment by christopherdro** [comment]
@soheil Still having this issue?

**Comment by brentvatne** [comment]
Thanks @soheil! [I put that example on rnplay](https://rnplay.org/plays/In9Sbg?autoplay=true).

**Comment by dalinaum** [comment]
Oops. I had a mistake. Please remove my reference.

**Comment by dhlwing** [comment]
solve this problems?@soheil

**Comment by soheil** [comment]
i stopped using react native

**Comment by chirag04** [comment]
I think i'm hit by a similar issue. @brentvatne  Any ideas on this?

**Comment by satya164** [comment]
Is this still happening?

**Comment by brentvatne** [comment]
Haven't heard back in a month, closing.

**Comment by haomiaozhichen** [comment]
I meet the same issue，and  i solve it by reuse  'ds.cloneWithRows(carList)', then the listview refreshed.

more code:
    `    _renderCarListRow(rowData,sectionID,rowID){
        return(
            <div key={rowID} className="car-list flex align-items-center"
                onClick={()=> this.setState({selectCarIndex:rowID,carList:ds.**cloneWithRows**(carList)})}>
                <p className="car-list-p1">{rowData.CarTypeName}</p>
                <img src="images/car5.png"/>
                <p className="car-list-p2">&yen;{rowData.ActualMoney}</p>
                <p>{'selectCarIndex:'+ this.state.selectCarIndex}</p>
                <p>{'rowID:'+ rowID}</p>
                <img className="car-list-img2" src="images/radio_not_checked.png"/>
            </div>
        );
    }`
and 
`<ListView horizontal
                        style={{height: '3.95rem',margin: '1px auto'}}
                        dataSource={this.state.carList}
                        renderRow={this._renderCarListRow.bind(this)}
                    />`
