### ISSUE TITLE
Support adb remote host devices

### ISSUE THREAD

**Issue by jadbox** [facebook/react-native#11617]
The adb client supports connecting to another adb host to connect to remote devices/emulators. However, the `react-native run-android` command does not accept host and port of a remote adb instance to connect to.

I've started a PR to work on this. #11616

**Comment by jadbox** [comment]
The reason why I started to tackle this is that I'm working on a Windows host and have experienced all kinds of build issues. I've moved my development to a virtualbox Debian client but the android emulator cannot run inside virtualbox Debian image. My next step is to run the emulator on the Windows host and communicate to the host's adb server from inside the virtualbox linux guest. That works, but now I need react-native to work with adb in a way tells it to use the remote host.

You can see below `adb` parameters to specify a remote host to use when giving an action (like `devices` or `shell`):

```
 -H                            - Name of adb server host (default: localhost)
 -P                            - Port of adb server (default: 5037)
```

**Comment by lacker** [comment]
Can you run an ssh tunnel between the two machines to solve this?
