### ISSUE TITLE
WebView should handle onPermissionRequest for device resources

### ISSUE THREAD

**Issue by alioguzhan** [facebook/react-native#11610]
### Description

I need to use RN's WebView module in my Android app for WebRTC. But according to [here](https://developer.android.com/reference/android/webkit/PermissionRequest.html), there is a class named PermissionRequest, stands for allowing to use device resources:

> This class defines a permission request and is used when web content requests access to protected resources

And looks like RN's WebView does not handle this. So we cannot use device camera or microphone for WebRTC apps. Local camera and mic do not work in the webview.

### Solution

However, I created a native webview module extending `SimpleViewManager` and just put these 3 lines:

```
webview.setWebChromeClient(new WebChromeClient(){
        // Need to accept permissions to use the camera
        @Override
        public void onPermissionRequest(final PermissionRequest request) {
            request.grant(request.getResources());
        }
    });
```

With this, WebView just worked as expected. Device camera and microphone works flawlessly. 
I tried to extend RN's WebView and put these 3 lines but didn't go well. 

* React Native version: **0.39.2**
* Platform:  **Android**
* Operating System: **MacOS**

**Comment by LucasSouzaa** [comment]
Did you solve your problem?

**Comment by alioguzhan** [comment]
@LucasSouzaa No. i rewrote my own Android Webview App with my custom bridges and configuration. And replaced moved from react native to react for now. No one interested this issue so far :/

**Comment by alfonsodev** [comment]
@alioguzhan do you have your extended component in a repo ?

**Comment by andrewhine-gat** [comment]
Any update on this?

**Comment by dave-irvine** [comment]
@alioguzhan It would be great if you could share the solution that you did manage to get working.

**Comment by JJMoon** [comment]
Same Problem.

**Comment by AAGSICON** [comment]
can you please share your code?
My application have this issue.
I could not get any solution.
can you please share it.

**Comment by alioguzhan** [comment]
Hi, it's been long time. The project belongs to my previous company. I don't have access to the code anymore :/

**Comment by AAGSICON** [comment]
Are you have any idea about it?

**Comment by alioguzhan** [comment]
Not now. But i will check my previous projects when i am home, today. If i ll find any sample code related to this  issue, i will put it here.

**Comment by AAGSICON** [comment]
OK Thanks

**Comment by wysiecki** [comment]
Hi, my way ended also here, any help ?

**Comment by alioguzhan** [comment]
I couldn't find my custom webview's source code. If i have enough time, i can re-write it. It is not that complicated. But there is another issue i believe. 

I created this issue more than one year ago and people having this issue ended up here many times. @hramos labeled this issue as `icebox` which means they consider this is not priority. 

It would be great and helpful if someone from maintainers give us an explanation about this issue.

**Comment by diegolaciar** [comment]
+1, solution for this is welcome, I have the same issue

**Comment by Titozzz** [comment]
Please open an issue on react-native-community/react-native-webview as this won't get fixed here @diegolaciar
