### ISSUE TITLE
ListView doesn't render items when set to Horizontal

### ISSUE THREAD

**Issue by nicolabortignon** [facebook/react-native#11612]
### Description

I created a horizontal ListView. When I first display the component, I cannot see the inner items. When I click (and drag a bit) on the ListView, suddenly all the iteam appears.

Sometimes the component is rendered with 1 item, sometimes with 2, then after dragging over it, all the other appears. There is no consistency in this behaviour.

![dec-23-2016 20-49-39](https://cloud.githubusercontent.com/assets/883459/21461390/72804240-c951-11e6-9cfb-88839964bce6.gif)

![dec-23-2016 20-46-07](https://cloud.githubusercontent.com/assets/883459/21461394/7d7d5764-c951-11e6-8fe7-fe9cd32eaaaa.gif)

![dec-23-2016 21-12-45](https://cloud.githubusercontent.com/assets/883459/21462103/64ca7b0a-c958-11e6-87e3-f65efb11a4a2.gif)

(if you look at the last of the 3 gif, even by clicking to an external element, seems to trigger a new render. 

It does happen with any type of items (Text, Image, Complex View, etc). 
**Worth mentioning that the ListView is used as categoryHeader inside another ListView**
### Reproduction

I opened up my entire codebase, so feel free to download and compile.
One example of the implementation is here.

[https://github.com/PolyStyle/ReactNativeMobileClient/blob/master/app/containers/UserProfile/UserProfileContainer.js#L289-L305]

### Solution

Haven't figure out this yet :( 

When I remove             
`showsHorizontalScrollIndicator={false}`
from the ListView, seems that the time that the component renders properly are higher than the times that it doesn't. 
### Additional Information

* React Native version: 0.34.0
* Platform: iOS (not tested in Android)
* Operating System: Mac OsX

**Comment by brunolemos** [comment]
@nicolabortignon does it still happens if you render it in the `renderHeader` instead of `renderSectionHeader`?

**Comment by nicolabortignon** [comment]
hey @brunolemos , thanks for coming back to me,

no, no changes. 

here an example with both the same component rendered as renderHeader (first red block) and as renderSectionHeader (second red block).  


![dec-24-2016 08-41-59](https://cloud.githubusercontent.com/assets/883459/21465870/f8c73594-c9b4-11e6-92ea-f2d7bd73bfe5.gif)

When interacting for the first time with anything in that 'page' everything renders properly.

**Comment by brentvatne** [comment]
Try setting `removeClippedSubviews={false}` on the `ListView`

**Comment by nicolabortignon** [comment]
@brentvatne,  unfortunately no, doesn't seams to help


![dec-24-2016 21-51-43](https://cloud.githubusercontent.com/assets/883459/21468720/365a383e-ca23-11e6-8b80-dcb956d03d7a.gif)




Here another  example of how random is the behaviour

**Comment by nicolabortignon** [comment]
My bad, the change didn't go through while using the hot reload. After restarting the emulator the problem was finaly fixed.


So yes,
adding `removeClippedSubviews={false}` to the `renderSectionHeader` rendering function, fixed the problem.

Wonder why, now!

**Comment by Chren** [comment]
same issue here, but I don't have renderSectionHeader function,
how to fix it?

**Comment by nicolabortignon** [comment]
@Chren, mind sharing your code? 

Does it happen in renderHeader? Is the list view wrapped around anything else?

**Comment by Chren** [comment]
@nicolabortignon 
I finally fixed it by just add removeClippedSubviews={false} inside ListView.
However, isn't there memory issue with removeClippedSubviews = false? Since it won't remove subviews even it is scrolled to invisible region, and I have a long list of data.
