### ISSUE TITLE
Memory leak in hybrid app

### ISSUE THREAD

**Issue by dbof10** [facebook/react-native#11628]
I'm currently using React Native for our new homepage. After having added LeakCanary, I got a log below
https://gist.github.com/dbof10/8d961f7c16bf6056867c2d3940c77011#file-leakstacktrace.

My Activity is 
https://gist.github.com/dbof10/8d961f7c16bf6056867c2d3940c77011#file-mainactivity-java

**Comment by Trikke** [comment]
i'm having the same issue, any updates on this?

**Comment by konark-hike** [comment]
Have attached screenshot for the memory leak checked on getting heap dump for same issue. Can someone please suggest a way to get rid of this strong reference!! [screen shot 2017-02-09 at 3 29 38 pm](https://cloud.githubusercontent.com/assets/14922024/22778370/adb59c10-eedc-11e6-8377-90019720c100.png)

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/memory-leak-in-hybrid-app

**Comment by mkonicek** [comment]
@Trikke @konark-hike So sorry I missed the cc on this a long time ago! We were overloaded with GitHub issues. Some of them were questions, some potentially more serious like this one and we struggled to go through all issues and reply to all of them.

I found something that might be related:
https://github.com/wix/react-native-navigation/issues/1807

AirBnb, Instagram ([blog post](https://engineering.instagram.com/react-native-at-instagram-dd828a9a90c7)) and other apps are hybrid apps that use React Native on Android so I think if this was a real issue that happens in production it would have to be fixed.

However, I just saw reports from LeakCanary when working on my hybrid app just now. I will update here if I find out more.

**Comment by mkonicek** [comment]
Hi @dbof10, @Trikke, @konark-hike,

I added a JS screen to my native app, have been reloading JS, navigating away from that screen and back to it many times and memory usage stays flat, as shown by Android Studio:

![screen shot 2018-02-01 at 18 45 28](https://user-images.githubusercontent.com/346214/35697317-b3612990-0781-11e8-9823-fa043c95c23e.png)

I'm using LeakCanary in the app which occasionally shows "Dumping memory, app will freeze. Brr!" and writes a heap dump to disk.

After a while I get a notification saying "Leak analysis failed" and the reason it failed is an OOM in the heap analyzer: https://github.com/square/leakcanary/issues/484

I can't see your original gists anymore but from the memory usage graph above my app looks fine.

Here is my Activity (in Kotlin):

```
class MyActivity : AppCompatActivity(), DefaultHardwareBackBtnHandler {

    private var delegate = MyReactActivityDelegate(this, "MyJsApp")

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        delegate.onCreate(savedInstanceState)  // Run the JS app
    }

    override fun onPause() {
        super.onPause()
        delegate.onPause()
    }

    override fun onResume() {
        super.onResume()
        delegate.onResume()
    }

    override fun onDestroy() {
        super.onDestroy()
        delegate.onDestroy()
    }

    public override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent) {
        delegate.onActivityResult(requestCode, resultCode, data)
    }

    override fun onKeyUp(keyCode: Int, event: KeyEvent): Boolean {
        return delegate.onKeyUp(keyCode, event) || super.onKeyUp(keyCode, event)
    }

    override fun onBackPressed() {
        if (!delegate.onBackPressed()) {
            super.onBackPressed()
        }
    }

    override fun invokeDefaultOnBackPressed() {
        super.onBackPressed()
    }

    public override fun onNewIntent(intent: Intent) {
        if (!delegate.onNewIntent(intent)) {
            super.onNewIntent(intent)
        }
    }
}
```

I'm using all the standard handling from the `ReactActivityDelegate`. Just exposing its methods:

```
class MyReactActivityDelegate(activity: Activity, mainComponentName: String)
    : ReactActivityDelegate(activity, mainComponentName) {

    public override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
    }

    public override fun onPause() {
        super.onPause()
    }

    public override fun onResume() {
        super.onResume()
    }

    public override fun onDestroy() {
        super.onDestroy()
    }
}
```

And in my `Application` class, define a host to hold the React Native instance. The `ReactActivityDelegate` will use that host, via the `Activity` we passed to it:

```
    /**
     * Simple holder object, cheap to initialise.
     * On first run of JS (call to `getReactInstanceManager`) starts up the JS instance, loads JS from disk,
     * and holds the instance in memory. All the memory can be reclaimed using [{@link MyReactNativeHost#clear()}.
     * It's a good idea to reclaim the memory when the process is running low on memory
     * or when the app is in the background - this reduces chances the system will kill the app.
     */
    private MyReactNativeHost reactNativeHost = new ReactNativeHost(this);

    @Override public ReactNativeHost getReactNativeHost() {
        return reactNativeHost;
    }
```

And finally the host is quite simple:

```
class MyReactNativeHost(application: Application) : ReactNativeHost(application) {

    override fun getUseDeveloperSupport(): Boolean {
        return BuildConfig.DEBUG
    }

    override fun getPackages(): List<ReactPackage> {
        return mutableListOf(
                MainReactPackage(),
                MyReactPackageWithAdditionalModules())
    }

    override fun getJSMainModuleName(): String {
        return "index"   // JS filename, without extension
    }
}
```
