### ISSUE TITLE
IPV6 issue

### ISSUE THREAD

**Issue by Vinu-MysteriousTechVision** [facebook/react-native#11627]
### Description

App store submission rejected  due to ipv6 not supported. what changes i need to support ipv6 my application fetch request.

### Additional Information

* React Native version: 0.35.0
* Platform: iOS & Android
* Operating System: MacOS

**Comment by hey99xx** [comment]
How is this related to React Native?

**Comment by sunnylqm** [comment]
http://www.gamasutra.com/blogs/HyunjikBae/20160127/264465/Short_tips_for_resolving_Apples_IPv6_enforcement.php

**Comment by fgaleano** [comment]
@Vinu-MysteriousTechVision were you able to fix this?

**Comment by brunolemos** [comment]
@fgaleano were you?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/ipv6-issue

**Comment by Ethan0007** [comment]
Hi,

I'm having the same issue when submitting the app in Apple it's rejected because of the said problem.

![image](https://user-images.githubusercontent.com/12542052/29487378-85b6d992-852a-11e7-8296-1ccea6dda667.png)


RN 0.43 
OS: MacOS
 Platform: iOS & Android

#Thanks

**Comment by rafaelcorreiapoli** [comment]
I'm also having the same issue.

**Comment by teyou** [comment]
most cases likely are because your `api server` doesn't support ipv6.

**Comment by diego-morgenstern** [comment]
@teyou ... the cause of the problem is just because the server does not support ipv6?

**Comment by macelii** [comment]
I can confirm that the root cause is NOT that the api server does not support ipv6

We have an app that has been rejected for the same cause but the app barely makes api call to Apple Maps' service and Google Analytics, using react-native-maps and google-analytics-bridge.

I can only imaging a possible cause would be that some components that you use don't support ipv6

**Comment by petealves** [comment]
@maxschmeling I am having the exact same issue, NetInfo also isn't working for me with IPv6..
Do you find some way of solving this? Thanks!

**Comment by maxschmeling** [comment]
@petealves I just removed my use of `NetInfo` (which isn't ideal, but I'm just dealing with it for now). After removing the `NetInfo` check on startup, I was able to get through the App Store review with no problems.
