### ISSUE TITLE
Can't find variable: Headers

### ISSUE THREAD

**Issue by jtremback** [facebook/react-native#1162]
I'm trying to use the fetch api and getting `Can't find variable: Headers`. 

for context:

```js
module.exports = function fetch (bearer_token, input, init) {
  if (!init.headers instanceof Headers) {
    init.headers = new Headers()
  }

  init.headers.append('Authorization', `Bearer ${bearer_token}`)

  return fetch(input, init)
}
```

**Comment by brentvatne** [comment]
@jtremback - looks like this isn't exported: https://github.com/facebook/react-native/blob/master/Libraries/Fetch/fetch.js

Why not just pass the headers in like this? https://github.com/github/fetch#post-json

```javascript
fetch('/users', {
  method: 'post',
  headers: {
    'Accept': 'application/json',
    'Content-Type': 'application/json'
  },
  body: JSON.stringify({
    name: 'Hubot',
    login: 'hubot',
  })
})
```

**Comment by jtremback** [comment]
Yes, that's what I'm doing. Just a heads up for you guys, as I assume this could break higher level libs on top of fetch. Not currently a problem for me though.

**Comment by brentvatne** [comment]
cc @vjeux - any reason to not export some of the `fetch` internals such as `Header`?

**Comment by vjeux** [comment]
fetch is copy and pasted straight from https://github.com/github/fetch

It may be out of date though and we need to update it

**Comment by vjeux** [comment]
Oh now I understand. There's no reason but my ignorance that they actually existed. Feel free to send a pull request to add them

**Comment by brentvatne** [comment]
Being tracked in #1192 now, thanks @jtremback
