### ISSUE TITLE
Not able to reuse ReactRootView in RecyclerView.

### ISSUE THREAD

**Issue by oargaruna** [facebook/react-native#11622]
I need to embed a React Native view in my RecyclerView. I have created a simple wrapper layout which contains my `ReactRootView` which I inflate in the RecyclerView:

    <?xml version="1.0" encoding="utf-8"?>
    <FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
             android:layout_width="match_parent"
             android:layout_height="match_parent">
        <com.facebook.react.ReactRootView
            android:id="@+id/rootView"
            android:layout_height="40dp"
            android:layout_width="match_parent"/>
    </FrameLayout>

Here is how I inflate the View:

    @Override
    public ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        View view = LayoutInflater.from(mContext).inflate(R.layout.react_native_wrapper, null);
        return new ViewHolder(view);
    }

And render the ReactRootView

    @Override
    public void onBindViewHolder(ViewHolder holder, int position) {
        Bundle launchOptions = new Bundle();
        launchOptions.putInt("index", position);
        holder.reactRootView.startReactApplication(mReactInstanceManager, "HelloWorld", launchOptions);
    }

When the ViewHolder is reused and `onBindViewHolder` is called again, I get an exception here: `holder.reactRootView.startReactApplication(mReactInstanceManager, "HelloWorld", launchOptions)`.

The error message: `java.lang.AssertionError: This root view has already been attached to a catalyst instance manager`

How do I reuse the ReactRootView instance? I do not face this error when I create a new ViewHolder for each item, but that defeats the purpose of a RecyclerView.
### Additional Information

* React Native version: 0.39
* Platform: Android
* Operating System: MacOS

**Comment by littlesome** [comment]
It's not supported on android, I need this feature too (I send a [PR](https://github.com/facebook/react-native/pull/10112/), but not accepted)
here's the main change to support this (works for me, but not well tested):

ReactRootView.java
```Java
  public void startReactApplication(
      ReactInstanceManager reactInstanceManager,
      String moduleName,
      @Nullable Bundle launchOptions) {
    UiThreadUtil.assertOnUiThread();

    mJSModuleName = moduleName;
    mLaunchOptions = launchOptions;

    if (mReactInstanceManager != null) {
      if (mIsAttachedToInstance) {
        mReactInstanceManager.updateRootView(this);
      }

      return;
    }


    // TODO(6788889): Use POJO instead of bundle here, apparently we can't just use WritableMap
    // here as it may be deallocated in native after passing via JNI bridge, but we want to reuse
    // it in the case of re-creating the catalyst instance
    Assertions.assertCondition(
        mReactInstanceManager == null,
        "This root view has already been attached to a catalyst instance manager");

    mReactInstanceManager = reactInstanceManager;

    if (!mReactInstanceManager.hasStartedCreatingInitialContext()) {
      mReactInstanceManager.createReactContextInBackground();
    }

    // We need to wait for the initial onMeasure, if this view has not yet been measured, we set which
    // will make this view startReactApplication itself to instance manager once onMeasure is called.
    if (mWasMeasured) {
      attachToReactInstanceManager();
    }
  }
```


XReactInstanceManagerImpl.java
```Java
  @Override
  public void updateRootView(ReactRootView rootView) {
    UiThreadUtil.assertOnUiThread();

    if (mReactContextInitAsyncTask == null && mCurrentReactContext != null) {
      Systrace.beginSection(TRACE_TAG_REACT_JAVA_BRIDGE, "updateRootView");

      @Nullable Bundle launchOptions = rootView.getLaunchOptions();
      WritableMap initialProps = Arguments.makeNativeMap(launchOptions);
      String jsAppModuleName = rootView.getJSModuleName();

      WritableNativeMap appParams = new WritableNativeMap();
      appParams.putDouble("rootTag", rootView.getRootViewTag());
      appParams.putMap("initialProps", initialProps);
      mCurrentReactContext.getCatalystInstance().getJSModule(AppRegistry.class).runApplication(jsAppModuleName, appParams);
      Systrace.endSection(TRACE_TAG_REACT_JAVA_BRIDGE);
    }
  }
···

**Comment by oargaruna** [comment]
Why was it not accepted? 

I worked around this by raising an event the next time the ViewHolder was re-used. It's a hacky piece of code though:

    try {
        holder.reactRootView.startReactApplication(mReactInstanceManager, "HelloWorld", holder.launchOptions);
    } catch (AssertionError e) {
        WritableMap map = Arguments.fromBundle(holder.launchOptions);
        EventEmitter.GetInstance().emitEvent("NewProps", map);
    }

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/not-able-to-reuse-reactrootview-in-recyclerview
