### ISSUE TITLE
[Docs] Add more documentation for custom views based off of RCTView (Original title: Can't get custom UIViews to render)

### ISSUE THREAD

**Issue by barneyboo** [facebook/react-native#1163]
I've been able to export a custom UIView such that it's exposed in JS, and is being instantiated with props being passed through, etc. which is great. My only problem is I can't actually get anything to render! My drawing logic in drawRect() is never being called. 

I suspect I'm misunderstanding something fundamental about how to wire things up. I've tried implementing a minimum working example and still can't get anything to render. I have a RCTViewManager with a view method as:

```
-(UIView *) view
{
  SimpleView *view = [[SimpleView alloc] initWithFrame:CGRectZero];
  return view;
}
```

I assumed the view's frame might've been set by the framework based on the style dimensions, but it doesn't appear to. Even with an explicit frame set, nothing renders. My UIView is implemented in Swift, but seeing as my props are passed correctly I'd be surprised if this was the problem. I'm fairly sure I'm just overlooking something very very stupid. I'd really appreciate any guidance!

**Comment by brentvatne** [comment]
@barneyboo - can you post the full code of the simple example? Check out this extremely simple example of implementing a dashed border view here: https://github.com/brentvatne/react-native-dashed-border-example - very minimal, should hopefully answer your question.

**Comment by chirag04** [comment]
@brentvatne  I feel like a lot of people will want to extend uiView. A documented approach somewhere would be helpful.

**Comment by tadeuzagallo** [comment]
@chirag04 Have you looked into http://facebook.github.io/react-native/docs/nativecomponentsios.html#content ? If so, is it missing something or is there something on it that you think should be better explained?

**Comment by brentvatne** [comment]
@tadeuzagallo - one issue with it could be that it shows how to implement the manager class but if you want the manager to use a custom view class then you are on your own (although I do explain that here to some extent: http://brentvatne.ca/react-native-view-component-2/). We could maybe amend it to add a simple example like the above dashed border.

**Comment by tadeuzagallo** [comment]
Sounds good to me! Thanks for helping make the documentation so much better! :D

**Comment by chirag04** [comment]
@tadeuzagallo +1 to what brent mentioned. I had a tough time understanding manager using custom class. I feel we can mentioned dashed border example by brent somewhere in the doc.

**Comment by brentvatne** [comment]
Also noting some other feedback from Slack:

- CalendarManager name is confusing - doesn't indicate anything special for regular bridge modules, but it does for View managers.
- More details on conventions

**Comment by eduedix** [comment]
+1 @brentvatne

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/docs-add-more-documentation-for-custom-views-based-off-of-rctview-original-title-cant-get-custom-uiviews-to-render
