### ISSUE TITLE
Vulnerability: Regular Expression Denial of Service

### ISSUE THREAD

**Issue by kirkstrobeck** [facebook/react-native#11637]
Regular Expression Denial of Service

- Name: negotiator
- Installed: 0.5.3
- Vulnerable: <= 0.6.0
- Patched: >= 0.6.1
- Path: none@undefined > react-native@0.39.2 > connect@2.30.2 > compression@1.5.2 > accepts@1.2.13 > negotiator@0.5.3
- More Info: https://nodesecurity.io/advisories/106

**Comment by hey99xx** [comment]
What does this have to do with React Native?

**Comment by ide** [comment]
Seems like this would mostly be a problem if you were running the packager on a server so this doesn't seem urgent to me. If someone wants to submit a PR with a responsible upgrade plan for connect and test plan (please don't just upgrade connect blindly) I'll take a look.

**Comment by kirkstrobeck** [comment]
Correct. It isn’t high priority by any means. It’s noted because it makes `nsp check` fail without an exception.

**Comment by sarathspillai** [comment]
Regular Expression Denial of Service (DoS)

Vulnerable module: negotiator
Introduced through: react-native@0.43.4

Simillarily for 
Vulnerable module: qs
Introduced through: react-native@0.43.4

Could someone please advise whether this can be fixed by any means?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/vulnerability-regular-expression-denial-of-service
