### ISSUE TITLE
Unable to create child component of class Button from React native.

### ISSUE THREAD

**Issue by amourya-systango** [facebook/react-native#11639]
I want to create class like following code:

'use strict';

import {
  Button
} from 'react-native';

export default class MyButton extends Button {

  onPress(){
    
  }
}

Can you please let me know is it possible to create a child Button component?

**Comment by ide** [comment]
You should create a new component that renders a Button, don't extend it.

**Comment by amourya-systango** [comment]
Why can we not extends Button?

**Comment by hubciorz** [comment]
@amourya-systango 
Because a preferable workflow with React is composition of components (not class extension)
