### ISSUE TITLE
sourceContent empty when generate source map using cli with --dev false

### ISSUE THREAD

**Issue by evollu** [facebook/react-native#11646]
I'm trying to generate sourcemap for production code.
When I'm using bundle cli with --dev true, sourcemap has everything in sourcesContent. But if I do with --dev false, sourcemap only includes file path for source code, no content is included. Is it desired behavior?

I checked the source code of cli and find the cause being [here](https://github.com/facebook/react-native/blob/master/packager/react-packager/src/JSTransformer/worker/minify.js#L19). If I remove line 19, 20, 27, 28, all source code will be included in sourcemap again.

Is there any solution for the problem? @davidaurelio since you are the creator of the works

* React Native version: 0.39.0
* Platform: both
* Operating System: MacOS

**Comment by EmielM** [comment]
Same problem here! Any news @davidaurelio?

**Comment by mitsuhiko** [comment]
In case this comes up in the context of sentry we have a workaround in the sentry-cli tool whcih rewrites the sourcemaps before upload and that works quite well for us. 

It would be easy to extract the code there to make it standalone.

**Comment by EmielM** [comment]
I have now come up with a similar fixup tool. Simply assumes the sources are absolute filenames and enriches the data structure with the referenced files' content in `sourcesContent`:

```
#!/usr/bin/node
var fs = require('fs');
var sourceMap = JSON.parse(fs.readFileSync(process.argv[2], 'utf8'));
var count = 0;
function transform(map) {
        if (!map || !map.sources) return;
        map.sourcesContent = map.sources.map(function(file,i) {
                try {
                        var d = fs.readFileSync(file, 'utf8');
                        count++;
                        return d;
                } catch (e) {
                        if (map.sourcesContent && map.sourcesContent[i]) {
                                // we have an original
                                return map.sourcesContent[i];
                        }
                        console.error("unable to read", file);
                }
        });
};

transform(sourceMap);
(sourceMap.sections||[]).forEach(function(section) { transform(section.map); } );

process.stdout.write(JSON.stringify(sourceMap));

console.error("done, added", count, "sources");
```

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/sourcecontent-empty-when-generate-source-map-using-cli-with---dev-false

**Comment by V-Tom** [comment]
Sorry for reopen this issues.

Same issues here.

I want to restore origin non-minify and non-uglyfy code from production minify code accord by the sourcemap. ( `--dev` is false

Any news ? @evollu 

@EmielM I use the same method as you read a file to generate `sourcecontent`, Also use `babel-generator` to re-generator sourcemap. Also change this file [here](https://github.com/facebook/react-native/blob/0.39-stable/packager/react-packager/src/JSTransformer/worker/minify.js) on line 29 add such code to re-generator sourcemap :
```javascript
// add sourceContent in node worker
minifyResult.map.sourceContent = code;
```
but none of them run successfully.

@mitsuhiko I had also saw this [document](https://github.com/getsentry/react-native-sentry/blob/master/docs/sourcemaps.rst),Does `sentry-cli ` supposed rewrite sourcemap file on local directory and use custom consumer `sourceContentFor` ? just like [mozilla sourcemap](https://github.com/mozilla/source-map)

Is there any way to supposed to restore code ? better no change the `react-native` officially code.

Thanks.

**Comment by hramos** [comment]
Please open a new issue.
