### ISSUE TITLE
No visible @interface for 'RCTRootView' declares the selector 'setReactPreferredFocusedView:'

### ISSUE THREAD

**Issue by skv-headless** [facebook/react-native#11640]
### Description

`/Users/headless/tmp/AwesomeProject/node_modules/react-native/React/Views/RCTTVView.m:181:32: No visible @interface for 'RCTRootView' declares the selector 'setReactPreferredFocusedView:'`

related to that commit https://github.com/facebook/react-native/commit/c92ad5f6ae74c1d398c7cd93d5c4c50da0ca0430. Before that I don't have this error. 
@javache 

### Reproduction

1) Create new project with cocoapods and install react-native pod
2) [update react-native](https://github.com/skv-headless/AwesomeProject/blob/master/package.json#L11)

by [this tutorial](https://facebook.github.io/react-native/docs/integration-with-existing-apps.html)
https://github.com/skv-headless/AwesomeProject

### Solution

Still looking

### Additional Information

* React Native version: master
* Platform: [iOS simulator, iphone 5]
* Operating System: [MacOS]

**Comment by ptomasroos** [comment]
Maybe a solution to this would be to exclude TVView*s  from the podspec? And make that a separated target to include those

**Comment by ide** [comment]
@ptomasroos I think that is right, or wrap RCTTVView in pragmas so it's not included in non-tvOS builds.

**Comment by ptomasroos** [comment]
I've provided a fix in #11667

**Comment by ptomasroos** [comment]
This can now be closed. Solution is merged in master
