### ISSUE TITLE
Do not correct processing of wrong-url

### ISSUE THREAD

**Issue by EJohnF** [facebook/react-native#11642]
### Description

I need to decide, given URL is correct image-url, or not. 
But url like http://wrong%20link.tech/JFKblue.gif - can't be correctly process in RN, because an red Error screen are show, or onError callback in Image component doesn't raise. 

### Reproduction

1. Try to fetch URL:
`fetch('http://wrong%20link.tech/JFKblue.gif')
.catch((err)=>console.log('error', err));`
[got red screen error](https://yadi.sk/d/v2qC0h-A35L8wb)

2. Try to prefetch an Image
`Image.prefetch('http://wrong%20link.tech/JFKblue.gif')
                    .then(()=> console.log('success image downloaded'))
                    .catch(e => console.log('ERROR', e));`

in logs I don't see an 'ERROR' message 
(and <Image> component render nothing)

### Solution

in fetch need to add something like try-catch block, because I think the right behaviour is to send an error message to catch. 

in Image.prefetch need to carefully process url, and resolving in Promise. 

### Additional Information

* React Native version: 0.38.0
* Platform: Android (don't try on IOS)
* Operating System: MacOS

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
