### ISSUE TITLE
Chrome devtools not working

### ISSUE THREAD

**Issue by jlongster** [facebook/react-native#1164]
If I set a breakpoint in Chrome, it does properly pause, but the source never actually loads. All I see is this:

http://jlongster.com/s/upload/rn-chrome-debug.png

but it never comes up. I let it sit for a while (I'm guessing that message might show for 1 second while it's parsing sourcemaps), but it's just stuck for me.

**Comment by vjeux** [comment]
cc @frantic

**Comment by frantic** [comment]
Ok tracked down a little bit. I can repro if the breakpoint is in `getInitialState` of a component, but everything works fine in something like button tap handler. Looking...

**Comment by jlongster** [comment]
Great! In my case I set a breakpoint inside the render function that renders a row in a `ListView`.

**Comment by frantic** [comment]
Looks like when debugger hits breakpoint, it can't load source maps:

![image](https://cloud.githubusercontent.com/assets/192222/7482569/3a5bf9c8-f32d-11e4-92cb-641434f549ed.png)

Resolves only when I hit play again

![image](https://cloud.githubusercontent.com/assets/192222/7482585/4ceabb9c-f32d-11e4-9027-22685efcfef0.png)

**Comment by frantic** [comment]
cc @amasad - any ideas?

**Comment by frantic** [comment]
@jlongster - meanwhile you can try Chrome Canary as suggested in [this chromium issue](https://code.google.com/p/chromium/issues/detail?id=424191)?

**Comment by vjeux** [comment]
cc @paulirish

**Comment by frantic** [comment]
@jlongster - just checked, everything works fine in Chrome Canary. Note that you'll need to apply #1101 locally to make RN run any "Chrome" browser.

**Comment by jlongster** [comment]
Awesome, thanks! I'm doing a demo and figured out another place to use breakpoints that work, but this is good to know in the future

**Comment by frantic** [comment]
:cool: I'm going to close this for now then since it's a Chrome bug that is fixed and will ship soon.
