### ISSUE TITLE
error:RCTFatal + 104 

### ISSUE THREAD

**Issue by dujiepeng** [facebook/react-native#11652]
Unable to resolve module react-native/Libraries/Core/Devtools/parseErrorStack from /Users/dujiepeng/Enjoy/work/webim-react-native/node_modules/reactotron-react-native/dist/index.js: Module does not exist in the module map or in these directories:
  /Users/dujiepeng/Enjoy/work/webim-react-native/node_modules/react-native/Libraries/Core/Devtools

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.

RCTFatal + 104
-[RCTBatchedBridge stopLoadingWithError:] + 1138
__25-[RCTBatchedBridge start]_block_invoke_2 + 65
_dispatch_call_block_and_release + 12
_dispatch_client_callout + 8
_dispatch_main_queue_callback_4CF + 1054
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
__CFRunLoopRun + 2205
CFRunLoopRunSpecific + 420
GSEventRunModal + 161
UIApplicationMain + 159
main + 111
start + 1
0x0 + 1

react-native-cli: 2.0.1
react-native: 0.36.1

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
