### ISSUE TITLE
Jest - TypeError: Cannot read property 'Commands' of undefined

### ISSUE THREAD

**Issue by tobiasMeinhardt** [facebook/react-native#11659]
**Do you want to request a *feature* or report a *bug*?**

bug - related to jest

**What is the current behavior?**

The error `TypeError: Cannot read property 'Commands' of undefined` is thrown when i trigger a function that references a `<ListView/>` and calls the scrollTo method of the `<ListView/>` like below:

```javascript
// This is a react-native app
// MyComponentTest.js
it('test scrollTo', () => {
  const tree = renderer.create(<MyComponent/>).toJSON()
  tree.children[0].props.onPress()
})

// MyComponent.js
class MyComponent extends Component {
  _scrollToTop = () => {
    this.refs.listView.scrollTo({x:0,y:0})
  }

  render() {
    return (
      <View>
        <TouchableHighlight onPress={this._scrollToTop}/>
        <ListView 
          ref="listView"
          {...moreProps}
        />
      </View>
    )
  }
}
```

When i run the tests, the stack trace ends at 'Component.scrollResponderScrollTo (node_modules/react-native/Libraries/Components/ScrollResponder.js:380:24)'

The error is caused by the line 'this.refs.listView.scrollTo({x:0,y:0})'...

**Package Versions**

I run the react-native app with the following package configuration:
"react": "15.4.1"
"react-native": "0.39.2"
"babel-jest": "17.0.2"
"jest": "17.0.3"
"react-test-renderer": "15.4.1"
"babel-preset-react-native": "1.9.0"

**Comment by stevenyap** [comment]
I have the same issue as @tobiasMeinhardt

**Comment by fasibio** [comment]
A Workaround to fix the Problem with srcollTo: 
`jest.mock('ListView', () => {
  const RealComponent = require.requireActual('ListView')
  class ListView extends RealComponent {
    constructor(props){
      super(props)
    }
    scrollTo = () => {

    }
  }
  return ListView
})`

**Comment by stevenyap** [comment]
@fasibio thanks for the workaround!
The workaround also work for ScrollView:

```
jest.mock('ScrollView', () => {
  const RealComponent = require.requireActual('ScrollView')
  class ScrolLView extends RealComponent {
    scrollTo = () => {}
  }
  return ScrollView
})
```

**Comment by SudoPlz** [comment]
Or 

```javascript
jest.mock('ListView', () => {
  const RealComponent = require.requireActual('ListView');
  class ListView extends RealComponent {
    constructor(props) {
      super(props);
      this.scrollTo = () => {};
    }
  }
  return ListView;
});
```
for the ones that use the airbnb eslint configuration.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/jest---typeerror-cannot-read-property-commands-of-undefined

**Comment by anirudhjain75** [comment]
Im working on snapshot testing for my react native app, Im facing the same problem when testing the home page. I've used react-native-navigation from wix, and have made an single page application. 
```
$ jest
 FAIL  src/screens/__tests__/Home-test.js
  ✕ Home renders correctly (19ms)

  ● Home renders correctly

    TypeError: Cannot read property 'setOnNavigatorEvent' of undefined

      10 |             pinCode: ''
      11 |         };
    > 12 |         this.props.navigator.setOnNavigatorEvent(this.onNavigatorEvent.bind(this));
      13 |
      14 |     }
      15 |     onNavigatorEvent(event) {
```

**Comment by GokulDharumar** [comment]
+1 same issue
