### ISSUE TITLE
Failure trying to build UIExplorer on Android

### ISSUE THREAD

**Issue by dboydor** [facebook/react-native#11663]
Getting an error when trying to build Android version of UIExplorer.  iOS version worked fine.

./gradlew :Examples:UIExplorer:android:app:installDebug

* Where:
Build file '/Users/dboyd/mpp/workspace/client/react-native/ReactAndroid/build.gradle' line: 3

* What went wrong:
A problem occurred evaluating project ':ReactAndroid'.
> java.lang.UnsupportedClassVersionError: com/android/build/gradle/LibraryPlugin : Unsupported major.minor version 52.0

**Comment by helengray** [comment]
me too,the android studio require jre1.8

**Comment by helengray** [comment]
I solve the problem by change the gradle tools version:
`dependencies {
        classpath 'com.android.tools.build:gradle:2.1.3'
    }`

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/failure-trying-to-build-uiexplorer-on-android
