### ISSUE TITLE
RCTAnimationManager is undefined in AnimationExperimental.js

### ISSUE THREAD

**Issue by martco** [facebook/react-native#1166]
I'm trying to use  AnimationExperimental like this:

    var AnimationExperimental = require('AnimationExperimental');

    ...
    componentDidMount() {
       AnimationExperimental.startAnimation({
         node: this.refs['this'],
         duration: 400,
         easing: 'easeInQuad',
         property: 'opacity',
         toValue: 0
       });
    }

But i'm getting this error:

![image](https://cloud.githubusercontent.com/assets/420959/7485060/63fab8f6-f345-11e4-96df-e7de3a3a0891.png)

When I chase down the error in the [related file](https://github.com/facebook/react-native/blob/2c803b04e90b2e1b07c122fdc436658f77f57d2c/Libraries/Animation/AnimationExperimental.js) I noticed that `RCTAnimationManager` is undefined. 

    console.log(RCTAnimationManager === undefined);  // this evaluates to true
    
    RCTAnimationManager.startAnimation( {...} )

I thought about chasing it down further but thought that I would check here first. I really appreciate any help.

**Comment by ide** [comment]
You might not have the RCTAnimation library linked -- check in Xcode if your app includes it.

**Comment by martco** [comment]
![image](https://cloud.githubusercontent.com/assets/420959/7485104/faff8e7a-f345-11e4-85e0-22ea81c77446.png)

![image](https://cloud.githubusercontent.com/assets/420959/7485106/ff7d26f6-f345-11e4-8084-da7ac3798b80.png)

**Comment by martco** [comment]
I'm an idiot. I was linking in the build phase of `RCTAnimationExperimental`, not of my app target
