### ISSUE TITLE
[Android] TextInput where multiline is true doesn't allow to set returnKeyType

### ISSUE THREAD

**Issue by Liroo** [facebook/react-native#11669]
### Description

`returnKeyType` does not work on Android with multi line props set to `true`
`returnLabelType` seems to be the same. The problem is on iOS it works well, this is not persistent and be able to display a Text on multiple line without linebreak become too much hard.

### Reproduction

`<TextInput multiline={true} returnKeyType={"done"}/>` works on iOS but not on Android.

### Solution

I found some native solution on stackoverflow but nothing in JS:

- [sol1](http://stackoverflow.com/questions/5014219/multiline-edittext-with-done-softinput-action-label-on-2-3)

- [sol2](http://stackoverflow.com/questions/2986387/multi-line-edittext-with-done-action-button)

Maybe I am wrong and there is a solution to display a textinput on multiple line without carriage returns and action Done but I didn't find a solution...

### Additional Information

* React Native version: *
* Platform: Android
* Operating System: *

**Comment by Liroo** [comment]
@reneweb Just saw your PR. This should be fine with your changements.

I keep this issue open until PR merge !

**Comment by dannycochran** [comment]
Did this ever get merged into a release? I still see this on 0.45.0

**Comment by reneweb** [comment]
Nah, the pr is still open and it's been quite a while now (#11125). I don't know whats the hold up in merging this in...

**Comment by Frosty21** [comment]
Not sure im guessing there thinking that using Scrollview with KeyboardAwareView is good enough to solve the issue.

**Comment by maximilian-ruppert** [comment]
Hope this will be merged soon...
