### ISSUE TITLE
Multiline text does not wrap to the new line on space between `»` and `(`

### ISSUE THREAD

**Issue by f1qwase** [facebook/react-native#11673]
### Description
Text does not wraps to the new line on space between `»` and `(`. Replacing `»` or `(` other symbol, e.g. letter or adding new symbol to space the will fix the bug. Double space will not.
Check the sample on rnplay.org 

### Reproduction

https://rnplay.org/apps/8HDgKw

### Solution

The workaround is replacing space symbol with space symbol + &nbsp
```javascript
   bugText.replace(/» \(/, '»\u{200B} (')
```

### Additional Information

Reproduced on iPhone (RN 39.2) and rnplay.org (RN 33.0)

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
