### ISSUE TITLE
Looks like something transparent cover top left of WebView [android][0.39.2]

### ISSUE THREAD

**Issue by HaydnChen** [facebook/react-native#11678]
I have a button on the top left of my HTML page, but I cannot click it in WebView whatever the position of WebView is. Then I start to increase margin-left of my button in HTML, after set margin-left more than about 300px it happens to be clickable.
It is so strange, looks like something transparent cover top left of WebView.

**Comment by HaydnChen** [comment]
By the way react-native 0.35.0 hasn't this bug, haven't test other version yet.

**Comment by HaydnChen** [comment]
Verified 0.37.0 hasn't this bug either.

**Comment by Swordsman-Inaction** [comment]
Can you provide more details? like a simple example to reproduce it?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/looks-like-something-transparent-cover-top-left-of-webview-android0392
