### ISSUE TITLE
XMLHttpRequest upload 1G file has error

### ISSUE THREAD

**Issue by jimtang9527** [facebook/react-native#11672]
### Description 

when file size is 5G, use  XMLHttpRequest upload,has error.

```javascript
let progressCallback = (e) => {
                   let loaded = e.loaded//max size 966356656,file size 5261320910 byte
                   let total = e.total//max size 966356656,file size 5261320910 byte
}
let xhr = new XMLHttpRequest()
xhr.upload.onprogress = progressCallback
let form = new FormData()
form.append('file', file)
xhr.open('POST', 'https://xxxxx', true)
xhr.send(form)
```

### Solution

meybe stat file size overflow.same https://github.com/johanneslumpe/react-native-fs/issues/226

### Additional Information

* React Native version: 0.39.2
* Platform: [Android]
* Operating System: [MacOS]

**Comment by ericvicenti** [comment]
It looks like this issue would be resolved by handling the file upload with this new blob implementation:

https://github.com/facebook/react-native/pull/11417

If its not too much effort, would you mind trying this new code to see if it helps address your problem?

**Comment by satya164** [comment]
@ericvicent I think not currently. We currently load the whole blob into memory and I'm not sure if we can avoid that. But want to discuss it in the PR. Would be great if we can actually avoid it

**Comment by ide** [comment]
Regarding loading the whole blob vs. not -- the spec actually allows for either behavior. The spec says it is preferable to load the blob (or come up with some other way to make it appear to be snapshotted, you could use CoW for example) but that for performance reasons it's OK to give up atomicity:

<img width="894" alt="screenshot 2017-01-02 15 29 55" src="https://cloud.githubusercontent.com/assets/379606/21597491/603b6784-d100-11e6-8cb6-ced38f889b98.png">

https://www.w3.org/TR/FileAPI/#file

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
