### ISSUE TITLE
Padding/Margin does not work on Text inside another Text

### ISSUE THREAD

**Issue by brunolemos** [facebook/react-native#11685]
### Reproduction

```jsx
<Text>
  <Text style={{ padding: 100, backgroundColor: 'green' }}>
    It should have padding
  </Text>
</Text>
```
https://rnplay.org/apps/6ROkUg

### Additional Information

* React Native version: 0.33, 0.39
* Platform: iOS, Android
* Operating System: MacOS

**Comment by shahen94** [comment]
@brunolemos please read this doc to understand how nested text component works.
https://facebook.github.io/react-native/docs/text.html#nested-text . I don't think that's a bug
