### ISSUE TITLE
bug in android on ActivityIndicator!!

### ISSUE THREAD

**Issue by aqnaruto** [facebook/react-native#11682]
![image](https://cloud.githubusercontent.com/assets/9067159/21565730/455e9700-ced6-11e6-90bb-9ab40d9abdef.png)

when init the `ActivityIndicator  's animating` atrribute to be false , it will never be show if you rerender it .

here is source code
```
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  ActivityIndicator,
  View
} from 'react-native';

export default class AwesomeProject extends Component {

constructor(){
      super()
        this.state = {
             isloading:false,
        }
    }

  render() {
    return (


      <View style={{flex:1}}>
          <Text  onPress={()=>{
            this.setState({isloading:!this.state.isloading })
          }}>
          click-isloading</Text>
          <ActivityIndicator  animating={this.state.isloading}/>
        </View>
     
  

    );
  }
}


AppRegistry.registerComponent('AwesomeProject', () => AwesomeProject);
```
---
android 6.1 ,reactnative 0.39 ，the latest version

**Comment by johnryan** [comment]
By default the ActivityIndicator hides when it is stopped. See "hidesWhenStopped": [https://facebook.github.io/react-native/docs/activityindicator.html#hideswhenstopped](https://facebook.github.io/react-native/docs/activityindicator.html#hideswhenstopped)

**Comment by aqnaruto** [comment]
yeah,but when i setstate `animating :true` it is still hide . if you initial `false ` it is always be false @johnryan

**Comment by vonovak** [comment]
I have met similar bugs. Interesting is that this [rnplay](https://rnplay.org/apps/VGCqBw) works.
you can work around it by saying `{this.state.isloading && <ActivityIndicator/>}`

**Comment by knapeto** [comment]
I have same problem. Any solution?

**Comment by vonovak** [comment]
@knapeto have you tried what I suggested?

**Comment by aqnaruto** [comment]
great!!! ,thank you ,but why?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/bug-in-android-on-activityindicator

**Comment by babycannotsay** [comment]
I met the same problem on android device, but iphone not. 
@vonovak your method is perfect.

**Comment by agitnaeta** [comment]
Hey there ive some problem its want be loading event i change it on true when onPress or using other method ,,
