### ISSUE TITLE
Would you accept docs translation PR? 

### ISSUE THREAD

**Issue by dalinaum** [facebook/react-native#1168]
Hello.

React docs have been translated into [Korean](http://reactkr.github.io/react/docs/getting-started-ko-KR.html). We would like to translate React Native into Korean too. 
Would you accept docs translation PR?

**Comment by iostalk** [comment]
Yes, please

**Comment by brentvatne** [comment]
@dalinaum - Probably the easiest approach is what was done there - create a fork and keep it updated with what we have on the main repo. A lot of our docs are extracted directly from the code and it would add a lot of noise if we had inline translations :smile:

If you need a hand with anything docs related, ping me in irc or on Twitter - @notbrent. Looking forward to seeing what you come up with, thanks a lot!
