### ISSUE TITLE
[Android] Why use annotation-processing by default and only with buck (not with gradle)? 

### ISSUE THREAD

**Issue by desmond1121** [facebook/react-native#11689]
It just let me confuse when I'm diving into react-native android source code, you use java annotation-processor in bellowing position:

- [ReactPropertyProcessor](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/processing/ReactPropertyProcessor.java) for generate PropertySetter.
- [ReactModuleSpecProcessor](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/module/processing/ReactModuleSpecProcessor.java) for generate ModuleInfoProvider.

But it's not added for gradle java compile procedure, but added to buck. And they are not enabled by default, we can see:

- ViewManagerSetter has a FallbackViewManagerSetter with java reflect-based annotation parse when it not found processing generated class (which has a '$$PropsSetter` suffix). See code in [ViewManagerPropertyUpdater.java#L65](https://github.com/facebook/react-native/blob/57f6cbb3dc12d2dcc3eedd9712c36bb3d39149a5/ReactAndroid/src/main/java/com/facebook/react/uimanager/ViewManagerPropertyUpdater.java#L65).
- ModuleInfoProvider would only enabled in `mLazyNativeModulesEnabled` (see [XReactInstanceManagerImpl.java#L945](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/XReactInstanceManagerImpl.java#L945). But this value is never set true in source, so it would use reflect-based annotation too.

So why don't enable annotation-processing by default? Since react-native android import annotation-processing for almost a year and not a very new feature (commit [57f6cb](https://github.com/facebook/react-native/commit/57f6cbb3dc12d2dcc3eedd9712c36bb3d39149a5)), it's existence make your code more confusing.

**Comment by rigdern** [comment]
It looks like PR #10084 contains some code to enable the annotation processor for gradle. However, the PR was closed because its primary goal was to add an optimization that was determined not to be worth it. We could reuse pieces of #10084 to enable the annotation processor for gradle.

**Comment by desmond1121** [comment]
@rigdern Thank you for your explanation. I would keep track of it :)

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/android-why-use-annotation-processing-by-default-and-only-with-buck-not-with-gra
