### ISSUE TITLE
Image works on iOS, but not on Android 

### ISSUE THREAD

**Issue by luco** [facebook/react-native#11691]
This Image code loads a 500x500 image on iOS. Works pretty well. But not Android.

    <Image source={{uri: data.product.image}} style= {{ height:80, width: 80 }} resizeMode={Image.resizeMode.contain}/>

It seems that the image should be no more than 80 pixels, in this case. If I put a 80x80 image uri, it works.

Any tips?
Thanks

**Comment by ericvicenti** [comment]
Does this happen for every `resizeMode`, or just `contain`? Can you experiment a bit to figure out exactly when the image doesn't appear, then update the issue title?

**Comment by colin3dmax** [comment]
This issues is opened blew
[https://github.com/facebook/react-native/issues/10569](url)

**Comment by ericvicenti** [comment]
Ah ok it looks like the same issue. Closing this one so we can track it in https://github.com/facebook/react-native/issues/10569

**Comment by facuescobar** [comment]
This fixed this problem on my project!

```
android:largeHeap="true" 
```

https://github.com/facebook/react-native/issues/10569#issuecomment-279397116
