### ISSUE TITLE
The build hangs at :app:bundleReleaseJsAndAssets when "./gradlew assembleRelease" is used

### ISSUE THREAD

**Issue by ghprud** [facebook/react-native#11696]
### Description

[I just ran ./gradlew assembleRelease from the ../android folder. The expectation is for the build to finish, but the build hangs for indefinite amount of time and fails with FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory. This is a major blocker]

### Reproduction

[In the project root folder, cd android, ./gradlew assembleRelease]

### Solution

[A way to run the builds faster]

### Additional Information

* React Native version: [0.39] (I have noticed this in earlier versions too)
* Platform: [Android]
* Operating System: [MacOS]

**Comment by DanielMSchmidt** [comment]
@facebook-github-bot stack-overflow

**Comment by cbpetersen** [comment]
If you need a work around, i had issues with this as well and ended up bundling the js manually first with

```
react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output App/src/main/assets/index.android.bundle --assets-dest App/src/main/res/
```
and then ignoring the gradle task with

```
./gradlew assembleRelease -x bundleReleaseJsAndAssets
```

**Comment by AndrewJack** [comment]
You can limit the amount of React Native workers when bundling if you are having memory issues.

To set a limit add the following environment variable:
```sh
export REACT_NATIVE_MAX_WORKERS=2
```

http://stackoverflow.com/a/38201276

**Comment by AndrewJack** [comment]
@facebook-github-bot answered

**Comment by billpatterson** [comment]
This is NOT closed in the sense of "solved".  I have this problem, and setting the environment variable had no effect.

**Comment by luisfcofv** [comment]
I'm having the same issue

**Comment by g33ktony** [comment]
Same issue here on latest react-native 0.46.4 I don't have the realm files on project root
it just hangs on :app:bundleReleaseJsAndAssets I ran the command that @cbpetersen build succeeded but app stops when I open it

**Comment by eneskaya** [comment]
For me this issue only appears when I have a packager instance running and try to build the app via `react-native run-android`.

**Comment by NicegirlA** [comment]
I have same issue like this 
![image](https://user-images.githubusercontent.com/19236956/29607531-792a924a-882c-11e7-9df0-ec1d83d94f4e.png)

**Comment by jtewright** [comment]
Quitting the packager and react-native run-android worked for me rn 47

**Comment by TGPSKI** [comment]
Any updates? Having this issue for all 0.48.x revisions

**Comment by TGPSKI** [comment]
Hi, I ended up solving this issue, and turned what I learned into a medium article that addresses this and related issues.

https://medium.com/@paterw00t_17915/android-react-native-fastlane-working-with-multiple-build-types-a9a6641c5704

**Comment by SPATAN18** [comment]
Thanks, @cbpetersen, your suggestions worked with some minor changes.

**Comment by ThaJay** [comment]
My ubuntu just freezes sometimes at
`Building 92% > :app:bundleReleaseJsAndAssets`
and I have to hard reboot my laptop.
(sometimes as in about 25% of times I let it build a release version)

**Comment by LeVadim** [comment]
Where would you set this export `REACT_NATIVE_MAX_WORKERS=2` environment?
Thank you!

**Comment by jeremyeaton89** [comment]
Noticed this problem as well after mac OSX firmware security update where my machine bugged out when booting back up (saw multiple apple icons, and other jank). Not sure what the problem is but experiencing hang on bundle[buildType]JSAndAssets.

@LeVadim you could try placing `export REACT_NATIVE_MAX_WORKERS=2` in ~/.bashrc or ~/.bash_profile

**Comment by jeremyeaton89** [comment]
In addition, seems like i'm having issues with stuff being removed?

```
11:22:08.069 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :app:removeDanglingSymlinks (Thread[Daemon worker,5,main]) completed. Took 0.182 secs.
11:22:08.069 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :app:bundleStagingJsAndAssets (Thread[Daemon worker,5,main]) started.
11:22:08.070 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :app:bundleStagingJsAndAssets
11:22:08.070 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Starting to execute task ':app:bundleStagingJsAndAssets'
11:22:08.070 [DEBUG] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Determining if task ':app:bundleStagingJsAndAssets' is up-to-date
11:22:12.279 [INFO] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Executing task ':app:bundleStagingJsAndAssets' (up-to-date check took 4.209 secs) due to:
  Output file /Users/jeremyeaton/projects/taskrabbit/tasker/android/app/build/intermediates/assets/staging/index.android.bundle.meta has changed.
  Output file /Users/jeremyeaton/projects/taskrabbit/tasker/android/app/build/intermediates/res/merged/staging/drawable-mdpi/app_images_pausemessage.png has been removed.
  Output file /Users/jeremyeaton/projects/taskrabbit/tasker/android/app/build/intermediates/res/merged/staging/drawable-xxhdpi/app_images_trlogologin.png has been removed.
11:22:42.843 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] DaemonExpirationPeriodicCheck running
11:22:42.847 [DEBUG] [org.gradle.launcher.daemon.server.health.DaemonStatus] GC rate: 0.0/s
11:22:42.848 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
11:22:42.848 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired.
11:22:42.851 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
> Building 97% > :app:bundleStagingJsAndAssets
```

**Comment by jeremyeaton89** [comment]
Looks like rm -r default.realm.* did it for me

https://github.com/facebook/react-native/issues/10078#issuecomment-249337180

**Comment by saraswathirbt** [comment]
fastlane hangs on 
This might take a few minutes. Please don't interrupt the script 
can any one please help me
fastlane -v:2.80.0

**Comment by t133** [comment]
try this https://stackoverflow.com/a/48917899/3645698 
maybe will work. Just check your /res/ files if all is in good situation..
