### ISSUE TITLE
onContentSizeChange in textinput not getting height when text height changes.

### ISSUE THREAD

**Issue by yasicmd** [facebook/react-native#11692]
<TextInput
            multiline={true}
            onContentSizeChange={(event) => {
          this.setState({height: event.nativeEvent.contentSize.height});
        }}
            onChangeText={(value) => {
          this.setState({value});
        }}
            style={[{height: 40,borderWidth: 0.5,borderColor: '#0f0f0f',fontSize: 13,padding: 4,width:width-40}, {height: Math.max(40, this.state.height)}]}
            defaultValue={this.state.value}
          />

**Comment by cgilson** [comment]
Getting same issue, but only on Android. Event is fired on mount, but isn't fired on text height change. Identical code works fine for iOS: 

<TextInput
              editable = {true}
              multiline = {true}
              [...]
              onContentSizeChange={(event) => {
                  this.setState({height: event.nativeEvent.contentSize.height});
                }}
              style={{height: Math.max(35, this.state.height)}}
            />

**Comment by yasicmd** [comment]
onChange={(event) => {
                this.setState({
                    height: event.nativeEvent.contentSize.height,
                });
                this.props.onModalHeightChange((Math.max(40, this.state.height)>140)? 140+205: Math.max(40, this.state.height)+205)
              }}


this worked for me

**Comment by yasicmd** [comment]
instead of onContentSizeChange

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.

**Comment by shergin** [comment]
Actually, I am working on this right now. I hope is will fix very soon.

**Comment by shergin** [comment]
Fixed! 35393524a94e2ea2668494eac7c89521f75266cf

**Comment by amanthegreatone** [comment]
is this patched into a release version?

**Comment by kesha-antonov** [comment]
@shergin Tried 0.46-stable (0.46.2).
Still doesn't work.

**Comment by ramsestom** [comment]
using react native 0.46.4 on android, I can't get `contentSize` from the event fired by `onChange` from `TextInput`...
the event.nativeEvent fired only has properties `target`, `eventCount `and `text`

**Comment by shergin** [comment]
@ramsestom That's expected behaviour. You have to use `onContentSizeChange` instead.

**Comment by ramsestom** [comment]
onContentSizeChange is simply never fired (I change my input in my textfield but the event is never fired even when the number of lines increase)

**Comment by shergin** [comment]
@ramsestom Yes, it was breaking change. (But this feature was never documented.) And I made it... for goods. We had really good reasons for that. Sorry for the inconvenience!

Could you please create separate issue discussing inconsistent behaviour of `onContentSizeChange`?

**Comment by eli-isbell-h360** [comment]
Not sure if this has been moved to another issue yet, didn't see one anywhere... 

@shergin 
Testing on RN 0.47.1 (IOS), same use case as OP, I find `onContentSizeChange` is grabbing the initial height of the TextInput and continues to fire as text is entered, but never gets changes in height.

**Comment by shergin** [comment]
@eli-isbell-h360 Interesting, could you please create a snack?

**Comment by eli-isbell-h360** [comment]
@shergin Yessir, here it is: https://snack.expo.io/SJB1E3uOb

It looks like `onContentSizeChange` fails to read the correct height if the placeholder is changed by `onFocus` and/or `onEndEditing`. I was using these to clear the placeholder immediately `onFocus` instead of waiting for the value to change. It also seems like the height changes, but not correctly when a larger fontSize is used.

**Comment by shergin** [comment]
@eli-isbell-h360 
Thank you!
Why do you and reapply `contentSize` as `height`? It is unnecessary. If you need autogrowing <TextInput>, simply do not set `height` explicitly; you also can limit height specifying `maxHeight`.
This is true for iOS for now, but right now I am working on same feature for Android.

Besides this I will investigate this issue.

**Comment by eli-isbell-h360** [comment]
@shergin 
True! I believe I was attempting to control the `height` more directly because of unexpected behavior I was seeing with the custom fonts and fontSizes, but `maxHeight` with no explicit `height` is what I am using now.

Thanks for working on this!
