### ISSUE TITLE
Packager is caching old versions of my files

### ISSUE THREAD

**Issue by drpancake** [facebook/react-native#11695]
### Description

I'm using Exponent but I believe this to be caused by the React Native packager under the hood.

Quite frequently if I introduce an error to my code I'll get the red box (as expected). However, at that point the packager seems to freeze in time. Changing the affected file to fix the issue does nothing. I just get the same red box error.

Watchman seems to be working fine, the app attempts to refresh if I change the file. I've also tried clearing the Watchman cache.

If I wait for 1-2 hours the issue resolves itself. It seems to be a caching issue somewhere.

We're using MobX. Not sure if that's an important detail.

### Reproduction

This seems to happen randomly. Can't reproduce.

### Additional Information

* React Native version: 0.37.0
* Platform: both
* Operating System: Mac

**Comment by DanielMSchmidt** [comment]
Had the same problem when changing linked node modules. It was caused by the caching and restarting the packager with `npm start -- --reset-cache` fixed the problem at least a bit.

**Comment by colinramsay** [comment]
Possibly related to #4968?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/packager-is-caching-old-versions-of-my-files
