### ISSUE TITLE
Yoga now supports % widths

### ISSUE THREAD

**Issue by srhise** [facebook/react-native#11702]
Yoga just completed a feature to allow percentages as size units. How is Yoga versioned into RN? Should this be available by updating the underlying module or do we need to wait for a separate RN release?

https://github.com/facebook/yoga/pull/258

**Comment by ericvicenti** [comment]
cc @emilsjolander

**Comment by emilsjolander** [comment]
I'm already working on a diff. Hang tight :)

**Comment by srhise** [comment]
Is this available in RN yet?

**Comment by emilsjolander** [comment]
Yeah :) in master at least.

**Comment by srhise** [comment]
Nice, I'll check it out.

Thank you!

Sean Hise

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/yoga-now-supports--widths

**Comment by srhise** [comment]
And guess what, it works!!
