### ISSUE TITLE
ListView leaving gaps when re-rendering

### ISSUE THREAD

**Issue by ErkanSensei** [facebook/react-native#11704]
I have a ListView that dynamically changes data based on a filter. When the user presses a button on the side menu, the data will filter out some of the objects. However, when the ListView re-renders, it seems to leave large gaps. I feel that this is a bug, as I'm using a straightforward implementation.

```
 renderRow = (item) => {
                  const tempArray = []
              if (item.events.length) {
                tempArray.push(item)
              } else {
                return null
              }
              return (
                <View
                  style={[styles.listTitle, { backgroundColor: '#FFF', padding: 8}]} host="eventsList">
                  <Text>{tempArray[0].name}</Text>
                </View>
              )
}
```

```
<ListView
            style={{backgroundColor: 'white'}}
            name="eventsList"
            dataSource={this.state.dataSource}
            renderRow={this.renderRow}
            scrollRenderAheadDistance={200}
            renderDistance={100}
            pageSize={1}
            initialListSize={10}
            stickyHeaderIndices={[]}
            onEndReachedThreshold={100}
            removeClippedSubviews
            automaticallyAdjustContentInsets={false}
          />
```

React Native version: 0.39.0
![screen shot 2017-01-02 at 6 49 06 pm](https://cloud.githubusercontent.com/assets/17013914/21598141/dbc0df3a-d11c-11e6-9c06-57caad20b221.png)

**Comment by DanielMSchmidt** [comment]
Could you test if returning a `<Text>Foo</Text>` element in the else case instead of `null` fills the gap with "Foo"? If so I would say that returning `null` here has a different semantics than one would expect. To fix your problem you could filter the list before adding it as datasource. In general we could do a PR to the docs and add a little warning for this use case.

**Comment by ErkanSensei** [comment]
When I replace ```null``` with ```<Text>Foo</Text>```, this is what happens:


![screen shot 2017-01-03 at 2 12 22 pm](https://cloud.githubusercontent.com/assets/17013914/21621458/b78d4c6e-d1be-11e6-8e65-c177938d1a1a.png)

**Comment by ErkanSensei** [comment]
To anyone getting a similar error to me, I've fixed the issue by setting the data source to an empty array, and then re-rendering after a delay with the new data; however, I am going to leave this issue up, as I'm pretty sure this should not be happening in the first place.

**Comment by alexkendall** [comment]
Having this issue. Jibberish is printing.

**Comment by DylanVann** [comment]
I also see this issue when updating a large dataset. It seems to have to do with dropping frames while changing the data.

**Comment by tjkang** [comment]
I also had same issue when It re-render list view with updated data for datasource, it leaves large gap. It was working fine with RN 0.37 before but this happened after I updated to RN 0.39.2 so i downgraded to RN 0.38 it's working fine now. i am not sure if this will be fixed above RN 0.40~.

**Comment by DylanVann** [comment]
The problem actually went away for me when I stopped using sticky section headers.

Switching to using FlatList also works.

**Comment by JensDebergh** [comment]
I've had similar problems with huge datasets the only way I was able to make it work was clear the datasource.

First: `dataSource.cloneWithRows([]);`
Second run: `dataSource.cloneWithRows(items);`

This probably has a huge impact on performance but atleast my rows now render properly on multiple runs

**Comment by hramos** [comment]
Closing as ListView is deprecated in 0.43. Use FlatList.
