### ISSUE TITLE
Jest: react-native status bar HEIGHT of undefined error

### ISSUE THREAD

**Issue by JeroenNelen** [facebook/react-native#11701]
### Description
After updating all the dependencies in our project to their latest versions, all of our Jest snapshot tests for components that contain the statusbar fail with the following message:
`TypeError: Cannot read property 'HEIGHT' of undefined
      at Object.<anonymous> (node_modules/react-native/Libraries/Components/StatusBar/StatusBar.js:395:1823)
      at Object.StatusBar (node_modules/react-native/Libraries/react-native/react-native.js:55:24)`

When looking into the StatusBar.js file, HEIGHT occurs as attribute on the StatusBarManager:
`static currentHeight = StatusBarManager.HEIGHT;`

At the top, the StatusBarManager is defined as follows:
`const StatusBarManager = require('NativeModules').StatusBarManager;
`

### Reproduction

1. Create a component with statusbar (`import { StatusBar } from 'react-native';`
2. Create a snapshot test using Jest
3. Run the test using Jest
4. This error message will pop up:
`TypeError: Cannot read property 'HEIGHT' of undefined
      at Object.<anonymous> (node_modules/react-native/Libraries/Components/StatusBar/StatusBar.js:395:1823)
      at Object.StatusBar (node_modules/react-native/Libraries/react-native/react-native.js:55:24)`

Relevant package information:
`
 "react": "15.4.1",
 "react-native": "0.39.2",
 "babel-jest": "18.0.0",
 "jest": "18.1.0",
 "jest-react-native": "18.0.0",
  "react-test-renderer": "15.4.1",
`

### Solution

If anyone can point me in the right direction?
I previously had issues with other stuff failing in the tests but those were resolvable by adding additional mocks (for which I created a PRQ).

**Edit**: I currently use this as a work around in my jest/setup.js file, but it seems rather hacky to avoid it that way?
`jest.mock('../node_modules/react-native/Libraries/Components/StatusBar/StatusBar', () => 'StatusBar');
`

### Additional Information

* React Native version: 0.39.2
* Platform: both, during JEST test runs
* Operating System: MacOS

Kind regards!

**Comment by goncalomarques** [comment]
Same issue here.

**Comment by ericvicenti** [comment]
Can you check if it gets fixed by putting `HEIGHT: 42` on this line? If that fixes it, could you submit as a PR?

https://github.com/facebook/react-native/blob/master/jest/setup.js#L137

**Comment by MrCeleryman** [comment]
Same issue here and the workaround fixes the issue

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.

**Comment by gengjiawen** [comment]
Run into the same issue. @ericvicenti proposed fix works. Created a pr https://github.com/facebook/react-native/pull/19017.
