### ISSUE TITLE
Nested Touchables not receiving double-touches (two simultaneous touches)

### ISSUE THREAD

**Issue by breakeren** [facebook/react-native#11717]
### Description
I experience a problem, where double-touches (to simultaneous touches) within nested Touchables arrive at the parent Touchable instead.

In the example below, Touchables are nested three layers deep. When I press the deepest touchable (coloured blue), the console correctly prints "blue". It also behaves correctly when I press the other layers hence printing "green" and "red" respectively.

The weird behaviour arises when I do something with two simultaneous touches and release - then the touched layer's onPress does not get called at all. Instead the parent Touchable receives just a single touch when both touches are over.

Furthermore when i perform two simultaneous touches on the outermost layer (red with no parent touchable)- that layer will receive the touch. That seems more correct from my perspective, but deviates from the weird behaviour within the nested Tocuables described above.

### Reproduction

    <TouchableHighlight onPress={()=>{console.log("red")}}>
      <View style={{backgroundColor:"#FF0000", height:300}}>   
        <TouchableHighlight onPress={()=>{console.log("green")}}>
          <View style={{backgroundColor:"#00FF00", height:200}}>
            <TouchableHighlight onPress={()=>{console.log("blue")}}>
              <View style={{backgroundColor:"#0000FF", height:100}} />
            </TouchableHighlight>
          </View>
        </TouchableHighlight>
      </View>
    </TouchableHighlight>
</View>

### Additional Information

* React Native version: [0.38 cli 1.2 ]
* Platform: [Android]
* Operating System: [MacOS]

**Comment by TGPSKI** [comment]
Similar issues with nested Text components & the onPress prop on inner children: https://github.com/facebook/react-native/issues/11462

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/nested-touchables-not-receiving-double-touches-two-simultaneous-touches
