### ISSUE TITLE
Net Info Always Returns false in "react": "15.4.1", "react-native": "0.39.2"

### ISSUE THREAD

**Issue by imbudhiraja** [facebook/react-native#11714]
### Description
Net Info always return false.
### Reproduction
NetInfo.isConnected.fetch().then(isConnected => {
  console.log('First, is ' + (isConnected ? 'online' : 'offline'));
});
function handleFirstConnectivityChange(isConnected) {
  console.log('Then, is ' + (isConnected ? 'online' : 'offline'));
  NetInfo.isConnected.removeEventListener(
    'change',
    handleFirstConnectivityChange
  );
}
NetInfo.isConnected.addEventListener(
  'change',
  handleFirstConnectivityChange
);

* React Native version: 0.39.2
* Platform:  iOS, Android
* Operating System: MacOS

**Comment by endpress** [comment]
u should add listener first. 

NetInfo.isConnected.addEventListener(
'change',
handleFirstConnectivityChange
);
NetInfo.isConnected.fetch().then(isConnected => {
console.log('First, is ' + (isConnected ? 'online' : 'offline'));
});

**Comment by imbudhiraja** [comment]
@endpress i tried in that way but the result is same.

**Comment by ericvicenti** [comment]
Yeah this does seem to be a real bug, lets discuss it in #8615

**Comment by Su2294chi** [comment]
Where do you need to add this portion of code in you react native Application to make it work?

**Comment by Bharatchavan20** [comment]
NetInfo.isConnected.fetch().then(isConnected => {
  console.log('First, is ' + (isConnected ? 'online' : 'offline'));
});
function handleFirstConnectivityChange(isConnected) {
  console.log('Then, is ' + (isConnected ? 'online' : 'offline'));
  NetInfo.isConnected.removeEventListener(
    'connectionChange',
    handleFirstConnectivityChange
  );
}
NetInfo.isConnected.addEventListener(
  'connectionChange',
  handleFirstConnectivityChange
);

**Comment by GouthamKD** [comment]
@Su2294chi c

Please find below working snippet with life cycle methods , On where to put the code as you mentioned...



export default class App extends Component {

  constructor(props) {
    super(props);

    this.state = {
      isConnected: null,
    }
  }


  componentDidMount() {
    NetInfo.isConnected.addEventListener(
      'ConnectionChange',
      this._handleConnectivityChange
    );
    NetInfo.isConnected.fetch().done(
      (isConnected) => { this.setState({ isConnected }); }
    );
  }

  UNSAFE_componentWillUnmount() {
    NetInfo.isConnected.removeEventListener(
      'ConnectionChange',
      this._handleConnectivityChange
    );
  }

  _handleConnectivityChange=(isConnected) =>{
    this.setState({
      isConnected
    });
  }


  render() {
    return (
      <View style={styles.container}>
        <Text>{this.state.isConnected ? 'Online' : 'Offline'}</Text>
      </View>
    );
  }
}

+++
Thanks & Regards,
Goutham KD
