### ISSUE TITLE
Webview - mediaPlaybackRequiresUserAction is not true by default

### ISSUE THREAD

**Issue by julien-innovantic** [facebook/react-native#11724]
### Description

When a web page contains a video, this video is automatically	played in full screen, even if user has no touch the web player.

### Reproduction

Just create a simple project with a webview and open a site containing a video.
  
### Solution

To fix this issue, it should define default props value for **mediaPlaybackRequiresUserAction**
[In documentation](https://facebook.github.io/react-native/docs/webview.html#mediaplaybackrequiresuseraction), this props must be set to true by default but in fact, this props has not default value.
Some other props must be set to true by default but in code source i don't find this init on ios webview. (WebView.ios.js) in contrary with android webview (WebView.android.js)

` static defaultProps = {
    javaScriptEnabled : true,
    scalesPageToFit: true,
  };`

### Additional Information

* React Native version: 0.39.2
* Platform: IOS, no test on android.
* Operating System: MacOS

Thanks for any advice by advance.

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
