### ISSUE TITLE
How to get the progress of the downloaded Image?

### ISSUE THREAD

**Issue by xiekunRonaldo** [facebook/react-native#1172]
When use Image with the uri setting the network url,if the network is poor ,I want to get the progress of the downloaded image to the the progress view,is it possible?

**Comment by iostalk** [comment]
Watch

**Comment by unknownexception** [comment]
I've made a PR https://github.com/facebook/react-native/pull/1318 You could simply pass `onDownloadProgress` property to `Image` component.

**Comment by brentvatne** [comment]
@unknownexception's PR looks great, closing this as we are tracking the issue there!

@christopherdro #fridaytriage
