### ISSUE TITLE
unable to resolve module and doesn't exist

### ISSUE THREAD

**Issue by jy1989** [facebook/react-native#11729]
### Description

I installed the modules by: 

> npm install --save xxmodule

and import in the js, 
But it always show me the errors unable to resolve module because the module doesn't exist in node_modules. 
By opening the package.json and node_modules folder. I surely it installed right.
I've tried install few different react native components by this way. all showed that error.
So now I can do is copy the module from node_modules to the root folder. 

and import it by 
> import xxmodule from './xxmodule'

this is only way I can do for use the component.

--------------------------

And I just found that if I create a folder in root, and put the module in it. also fail to import

> import xxmodule from './lib/xxmodule'  

it said not found index in xxmodule folder

and I try import with require
>  let xxmodule =require('./lib/xxmodule')

it said not found index.js in xxmodule folder

---------------

And I found when I npm install
it shows the errors

> npm WARN enoent ENOENT: no such file or directory, open '/Users/chen/Documents/react-native/CloudPicker/node_modules/node_modules/package.json'

I dont know why it will point to node_modules/node_modules, so after I open the package.json in node_modules and add the dependencies.  and restart the node server by  

> npm start -- --reset-cache

it seems working now. I can use the compont by 

> import xxmodule from 'xxmodule'

------------

So what's the problem???!

### Additional Information

* React Native version: 
react-native-cli: 2.0.1
react-native: 0.40.0

* Platform: IOS
* Operating System: MacOS

**Comment by ericvicenti** [comment]
It sounds like you've fixed it. What module was it, and did they upgrade it for RN 0.40 ?

**Comment by jy1989** [comment]
@ericvicenti 
Hi

there are the modules:

"react-native-scrollable-tab-view": "^0.7.0",
"react-native-swiper": "^1.5.4"

I think they both not upgrade for RN0.40.

So the problem depend on the components' RN version?
