### ISSUE TITLE
DatePickerAndroid.open({mode: 'spinner'}) doesn't work.

### ISSUE THREAD

**Issue by chrbradley** [facebook/react-native#11727]
### Description
I'm running the example code, [https://facebook.github.io/react-native/docs/datepickerandroid.htm](https://facebook.github.io/react-native/docs/datepickerandroid.htm)l, on a Galaxy 5s, android version5.

When I select the spinner date picker, the calendar picker displays.

### Reproduction

[https://rnplay.org/apps/cZdKMw](https://rnplay.org/apps/cZdKMw)

### Solution

This can be resolved by displaying the spinner picker when `{mode: 'spinner']`.

### Additional Information

* React Native version: 0.39.2
* Platform: Android
* Operating System: MacOS

**Comment by chrbradley** [comment]
Just saw that this is fixed in 0.40.0.

**Comment by henriqamaral** [comment]
Hi,
I'm using version 0.41 and the problem continue.

**Additional Information**

React Native version: 0.41.2
Platform: Android (Emulator)
Android Version: 7.0
Operating System: MacOS

**Comment by vincentsong** [comment]
I am using 0.42 on Andriod7.0. Same problem.

**Comment by bennygenel** [comment]
TimePickerAndroid should have the same. DatePickerAndroid has the mode prop.
