### ISSUE TITLE
Duplicate interface definition for class 'RCTBridge'

### ISSUE THREAD

**Issue by brunolemos** [facebook/react-native#11725]
### Description

Can't build project after upgrading to 0.40.

PS1: Upgraded from 0.39 using react-native-git-upgrade.
PS2: I compared the diff with this [0.39..0.40 diff](https://github.com/ncuillery/rn-diff/compare/rn-0.39.2...rn-0.40.0) and they are identical, so the upgrade went fine.

### Additional Information

* React Native version: 0.40
* Platform: iOS
* Operating System: macOS 10.12.13

### Screenshot

[![screenshot](https://s30.postimg.org/4rgmzr0a9/Screen_Shot_2017_01_04_at_19_15_33.png)](https://postimg.org/image/sv7eo1ir1/)

**Comment by DesignMonkey** [comment]
Same happens with new installation with all the RN packages imported with react-native link

**Comment by brunolemos** [comment]
This was probably introduced by the [breaking change on 0.40](https://github.com/facebook/react-native/releases/tag/v0.40.0) that requires a "React/" namespace on header paths. Apparently all native modules will have to upgrade themselves to support RN >= 0.40, so... we better send them PRs!

**Comment by ericvicenti** [comment]
Yeah it seems that `react-native-webrct` hasn't upgraded for v0.40 yet. Sorry about the inconvenience

See here: https://github.com/oney/react-native-webrtc/search?utf8=%E2%9C%93&q=import+%22

A bunch of these need to be converted. If it says `#import "RCTConvert.h"`, it needs to change to `#import <React/RCTConvert.h>`

**Comment by xuechinahb** [comment]
same problem to me!

**Comment by Amurmurmur** [comment]
Probem with fbsdk, its the same :(

**Comment by SMJ93** [comment]
I tried what @ericvicenti said above and changed all `#import "RCTConvert.h"`  to `#import <React/RCTConvert.h>`, but I am still getting the error:
`/node_modules/react-native/React/Base/RCTBridge.h:65:1: Duplicate interface definition for class 'RCTBridge'`
 This is for https://github.com/wix/react-native-navigation.

**Comment by nihgwu** [comment]
@SMJ93  remove all the React Native related `Header Search Paths` in 3rd party libraries

**Comment by SMJ93** [comment]
@nihgwu my `header search paths` under `Build Settings` is empty, but I am still getting `Duplicate interface definition for class 'RCTBridge'` error.

**Comment by SMJ93** [comment]
Finally!! I managed to fix the error by `Find and Replace in Project` and change all `#import "RCTBridge.h"` to `#import <React/RCTBridge.h>` in addition to @ericvicenti's and @nihgwu  answer's above.

**Comment by christiangenco** [comment]
I got it working by [upgrading to the most recent github version of `react-native-fbsdk`](https://github.com/facebook/react-native-fbsdk/pull/322#issuecomment-271457311).

**Comment by georgiana-gligor** [comment]
A lot of the 3rd party libraries have yet to release stable versions with RN 0.40 fix, and it can get frustrating very quickly. We confronted with this problem as well, on several packages. I described [our approach](http://tekkie.ro/quick-n-dirty/support-react-native-0.40-ios-headers/) and am leaving the link here so that others can use it to continue working asap.

**Comment by franj0** [comment]
For me fix was:
`react-native upgrade`

hit **y** for all iOS files

**Comment by r01010010** [comment]
@nihgwu 'remove all the React Native related Header Search Paths in 3rd party libraries' how to do that?

**Comment by zhuozp** [comment]
@nihgwu @brunolemos the same problem happened for react native 0.43.4. It should be solved with correct process neither to change all #import "RCTBridge.h" to #import <React/RCTBridge.h>. This solution is pretty bad。So. hope for all your Answer. THX.
