### ISSUE TITLE
Reliable build on `^0.39.2` fails when upgrading to `^0.40.0`

### ISSUE THREAD

**Issue by kirkstrobeck** [facebook/react-native#11721]
```bash
** BUILD FAILED **


The following build commands failed:
	CompileC /XXX-FULLPATH-XXX/ios/build/Build/Intermediates/RCTSettings.build/Debug-iphonesimulator/RCTSettings.build/Objects-normal/x86_64/RCTSettingsManager.o RCTSettingsManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

**Comment by joncursi** [comment]
I am also running into trouble, with several "file not found" issues.

* React/RCTDefines.h
* React/RCTEventEmitter.h

<img width="1179" alt="screen shot 2017-01-04 at 1 10 46 pm" src="https://cloud.githubusercontent.com/assets/4974609/21653487/5668bc86-d27f-11e6-9e84-6c585b5f1e6a.png">

**Comment by nic** [comment]
Take a look on the release note:

https://github.com/facebook/react-native/releases/tag/v0.40.0

**Comment by SandroMachado** [comment]
I solved it doing this:

```
- In Xcode, go to the project scheme (Product -> Scheme -> Manage Scheme -> double click your project).

- Click on the 'Build' option at the left pane.

- Uncheck 'Parallelize Build' under Build Options.

- Then in Targets section, click '+' button then search for 'React'. Select it and click 'Add'.
'React' should now appear under Targets section. Click and drag it to the top so that it will be the first item in the list (before your project).

- Clean the project and build.
```

**Comment by stueynet** [comment]
@SandroMachado how is that the only solution here? RN 0.4 will break any project that has a dependency that uses the old import syntax in native modules. So its not possible to upgrade to 0.4 until all of the dependencies have upgraded to the new import syntax.

**Comment by melihberberolu** [comment]
Heeeeyyyy why you kill yourself ?

**Comment by luhui** [comment]
I have encounter same issue after upgrade from 0.39.2 to 0.40, but @SandroMachado 's workaround not work for me. 
use `react-native-git-upgrade` to upgrade, but no file change
Should I update the search path?  And how?

**Comment by pvinis** [comment]
how is disabling parallelization a good thing? isnt the packager slow enough, now we slow down xcode too? why? i really dont think this should be turned off.

this change happened here https://github.com/facebook/react-native/commit/e1577df1fd70049ce7f288f91f6e2b18d512ff4d

**Comment by binchik** [comment]
Hi!

I unchecked the parallelize build option, added React as a target to project's scheme, placed above other targets and it still says "<React/RCTLog.h> file not found". Although every third party dependency is converted to the new imports.

By the way, I'm using CocoaPods to include react-native in my project. May it cause the problem? The contents of my Podfile:

```
source 'https://github.com/CocoaPods/Specs.git'

target 'Tantalum' do
  pod 'React', :subspecs => [
    'Core',
    'ART',
    'yoga',
    'cxxreact',
    'jschelpers',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTText',
    'RCTWebSocket',
  ], :path => '../node_modules/react-native'
  pod 'Crashlytics'
  pod 'Fabric'
  pod 'Digits'
end
```

**Comment by kirkstrobeck** [comment]
I went thru https://github.com/ncuillery/rn-diff/compare/rn-0.39.2...rn-0.40.0 and moved over what seemed to be meaningful, but not what I assume to be compile results.

My remaining issues may be specific to my project, but also likely affect others.

![screen shot 2017-01-08 at 4 03 26 am](https://cloud.githubusercontent.com/assets/241963/21749624/749a2d68-d557-11e6-9919-9d77272902aa.png)
![screen shot 2017-01-08 at 4 03 52 am](https://cloud.githubusercontent.com/assets/241963/21749627/80e7fd84-d557-11e6-87ca-ec53ce528b1a.png)
![screen shot 2017-01-08 at 4 04 13 am](https://cloud.githubusercontent.com/assets/241963/21749630/8c272ada-d557-11e6-92c3-33b39ccb1215.png)

**Comment by patrickhaug** [comment]
Same for me. Release scheme stops working in every app, that worked before.

`Undefined symbols for architecture arm64:
  "___gxx_personality_v0", referenced from:
      _RCTDefaultLogFunction_block_invoke in libReact.a(RCTLog.o)
      _RCTFormatLog in libReact.a(RCTLog.o)
      ___RCTAddLogFunction_block_invoke in libReact.a(RCTLog.o)
      _RCTPerformBlockWithLogFunction in libReact.a(RCTLog.o)
      _RCTPerformBlockWithLogPrefix in libReact.a(RCTLog.o)
      RCTGetLocalLogFunction() in libReact.a(RCTLog.o)
      ___RCTPerformBlockWithLogPrefix_block_invoke in libReact.a(RCTLog.o)
      ...
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by joncursi** [comment]
@patrickhaug I ran into that same issue with release schemes failing to build, I read in a different issue tracker and can confirm that deleting your release scheme and re-creating it again in Xcode will get you past that problem

**Comment by patrickhaug** [comment]
@joncursi that seems to fix it! thank you sir!

**Comment by ncuillery** [comment]
> use react-native-git-upgrade to upgrade, but no file change

@luhui Maybe you have installed RN 0.40.0 before running the `react-native-git-upgrade`. It's important that the process starts while the old version of RN is installed in `node_modules`. See the [upgrading guide](https://facebook.github.io/react-native/blog/2016/12/05/easier-upgrades.html) for details.

**Comment by yoniji** [comment]
+1 @SandroMachado's solution. It worked for me. Thank you!

@binchik I have the same problem and https://github.com/facebook/react-native/issues/2685 fix my issue:
- In **Build Phases** - **Link Binary with Libraries**,  make sure `libReact.a` is listed
- In **Build Settings** - **All**,  find **Dead Code Stripping** option, and set to no
- In **Build Settings** - **All**, find **Other Linker Flags** option, and after add `-lc++` flag

**Comment by binchik** [comment]
@yoniji Thanks for the suggestion. I tried it, Xcode still can't find React libs :(

**Comment by MattFoley** [comment]
Xcode can help with this to some degree, at least the replacing of the imports. Xcode has a find and replace with regular expression option.

These regex will let you do find and replace on any files that are importing the wrong way:

Find: `(#import )(")(RCT.*.h)(")`

Replace: `$1<React/$3>`

![screen shot 2017-01-12 at 5 49 41 pm](https://cloud.githubusercontent.com/assets/1182042/21915562/7c736374-d8ef-11e6-8b0a-85770bfb60e2.png)

**Comment by alloy** [comment]
@rops Do the 3rd party libs' podspecs explicitly depend on `React`?

**Comment by rops** [comment]
Most of 3rd party libs don't have podspecs. They are usually distributed only as an XCode proj.

To add those, I just
- Drag SomeLibrary.xcodeproj to my xcode proj
- Add "libSomeLibrary.a" to "Link Binary Phases"

If I manually override the HEADER_SEARCH_PATH in SomeLibrary.xcodeproj  and make it point to MyProject/Pods/Headers/Public then it builds.

Is there maybe a way to include SomeLibrary in my Podfile even if there is no SomeLibrary.podspec? Or maybe just some XCode settings to propagate MyProject HEADER_SEARCH_PATH to its children projects?

**Comment by alloy** [comment]
@rops I’m getting confused. Is your issue really the same issue that this ticket was originally about?

With regards to your specific issue, there’s not much I can help you with. You can either create local podspecs for the libraries you’re using and have CP integrate them for you, or you’ll have to keep doing what you’re doing (adding the header search paths) which you can maybe [try to automate](https://guides.cocoapods.org/syntax/podfile.html#post_install).

**Comment by lanceharper** [comment]
is it possible to revert the effects of react-native-git-upgrade? just undoing the changed files seems to have left my project broken

**Comment by kirkstrobeck** [comment]
Circling back to this to try again.

I believe the https://github.com/facebook/react-native/issues/11721#issuecomment-270672904 has moved the issue along, but still seeing an issue. Anybody know how to address bringing other deps/libs along with the upgrade?

```bash
** BUILD FAILED **


The following build commands failed:

  CompileC <fullpath>ios/build/Build/Intermediates/RCTFBSDK.build/Debug-iphonesimulator/RCTFBSDK.build/Objects-normal/x86_64/RCTFBSDKShareButtonManager.o RCTFBSDK/share/RCTFBSDKShareButtonManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/project.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/project.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist


error Command failed with exit code 1.
```

**Comment by kirkstrobeck** [comment]
Additionally, if I run `./node_modules/.bin/react-native-git-upgrade` then I get the following:

```bash
./node_modules/.bin/react-native-git-upgrade
<FULLPATH>/project/node_modules/react-native-git-upgrade/cliEntry.js:9
'use strict';var checkForUpdates=function(){var _ref=_asyncToGenerator(regeneratorRuntime.mark(
                                                                       ^

ReferenceError: regeneratorRuntime is not defined
    at <FULLPATH>/project/node_modules/react-native-git-upgrade/cliEntry.js:9:72
    at Object.<anonymous> (<FULLPATH>/project/node_modules/react-native-git-upgrade/cliEntry.js:205:208)
    at Module._compile (module.js:571:32)
    at loader (<FULLPATH>/project/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (<FULLPATH>/project/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
```

**Comment by Igor10k** [comment]
From https://github.com/facebook/react-native/commit/e1577df1fd70049ce7f288f91f6e2b18d512ff4d description:

> To make Xcode copy headers phase work properly, you may need to add React as an explicit dependency to your app's scheme and disable "parallelize build".

Can somebody explain why it says "you **may** need"? Does it work for somebody without doing this? Why?

**Comment by steveccable** [comment]
The underlying issue is that the sub-projects like RCTVibration, RCTWebSocket, etc all depend on things in the React project, but do not have it as a build dependency, so it is possible for them to try to build before the things they depend on have built.

I actually found that if you make the React project a dependency of all the other RCT* sub-projects, you can turn parallel builds back on and it works fine.

To add the React project as a dependency, do the following:

```
1. Open up your project in XCode.
2. Open up the Libraries folder.  You should see React.xcodeproj and several RCT*.xcodeproj.
3. Drag the React.xcodeproj into each of the other projects.
4. Click on each project and navigate to the Build Phases tab.
5. Click on Target Dependencies and add React as a target dependency
```

If somebody could go through these steps and verify it solves the issue for them AND allows them to turn parallel builds back on, that would be greatly appreciated.  Once I verify that this works for other people's projects, I would be fine with making a PR against React Native to make this happen by default.

**Comment by heatnode** [comment]
@steveccable I can confirm your steps worked in my case. I went from RN 0.36 to 0.41 and resolved the dependency issues following your steps. Thanks for posting that. It was tedious, but it worked.

**Comment by pgarciacamou** [comment]
@steveccable please keep us posted if you do create a PR.

**Comment by tanmynguyen** [comment]
I see problem???

<img width="869" alt="screen shot 2017-02-28 at 12 28 25" src="https://cloud.githubusercontent.com/assets/11315567/23392915/73e55212-fdb1-11e6-8ef3-331eb2dcdb68.png">

**Comment by kirkstrobeck** [comment]
I just did a fresh project with the new version and ported over all the code. None of the above worked for me.

**Comment by kirkstrobeck** [comment]
Closing, because it looks like https://github.com/facebook/react-native/issues/11721#issuecomment-270672904 is solving for most folks.

**Comment by tanmynguyen** [comment]
@kirkstrobeck  you see warning???

<img width="869" alt="screen shot 2017-02-28 at 12 28 25" src="https://cloud.githubusercontent.com/assets/11315567/23393282/5f4fff66-fdb4-11e6-8aee-b5bdf9e0589b.png">

**Comment by kirkstrobeck** [comment]
@tanguyantoine would you please open a new issue and reference this one?

**Comment by tanguyantoine** [comment]
@kirkstrobeck I think you can :)

**Comment by kirkstrobeck** [comment]
^ ha! oops, I meant to mention @tanguyantoine

**Comment by kirkstrobeck** [comment]
^ ha! oops, I meant to mention @tanmynguyen

**Comment by codler** [comment]
If `Libraries/React.xcodeproj` are red in xcode then reinstall node_modules

> rm -rf node_modules && yarn

**Comment by GopiKrishna10** [comment]
Hi @kirkstrobeck tanguyantoine steveccable SandroMachado joncursi 

  I tried to upgrade the React-native 0.39.0 to 0.50.0 and React 15.3.1 to 16.0.0 facing errors in Xcode could you guys please help me
![screen shot 2017-12-13 at 9 58 46 pm](https://user-images.githubusercontent.com/15904913/33952736-bd9b43fa-e058-11e7-9e71-f83255a3b4e9.png)

**Comment by tanguyantoine** [comment]
do you mean @tanmynguyen ?

**Comment by GopiKrishna10** [comment]
@tanmynguyen Actually i saw the comments above and typed the names.If you know the solution for above comment.Could you please suggest the solution

**Comment by kirkstrobeck** [comment]
@GopiKrishna10 as mentioned at https://github.com/facebook/react-native/issues/11721#issuecomment-282948689, I could not resolve this. Hope you have better luck 👍

**Comment by GopiKrishna10** [comment]
Ok @kirkstrobeck Thanks.
