### ISSUE TITLE
Returning multiple components results in a libART error

### ISSUE THREAD

**Issue by Vikaton** [facebook/react-native#11728]
### Description

I am using the `react-native-chart` module to display charts in my app, and I wanted to add a touchable functionality to the the plotted dots on the chart, so I went into the library and tried to wrap this with a `<TouchableOpacity>` component: https://github.com/tomauty/react-native-chart/blob/master/src/LineChart.js#L168

When I tried running my app, I get these errors from xcode:

<img width="1135" alt="screen shot 2017-01-04 at 8 50 03 pm" src="https://cloud.githubusercontent.com/assets/9522710/21668722/8e8642b6-d2d2-11e6-9f61-9f62148fc12e.png">

<img width="1019" alt="screen shot 2017-01-04 at 11 06 53 pm" src="https://cloud.githubusercontent.com/assets/9522710/21668726/96ccc33c-d2d2-11e6-9985-1488262e7222.png">

### Reproduction

Install the `react-native-chart` module directly from github, and try wrapping the touchableOpacity component around https://github.com/tomauty/react-native-chart/blob/master/src/LineChart.js#L168

````
return (
        <View>
            <View style={{ position: 'absolute' }}>
                <Surface width={containerWidth} height={containerHeight}>
                    { multipleLines }
                    { multipleFills }
                </Surface>
            </View>
            <View style={{ position: 'absolute' }}>
                <Surface width={containerWidth} height={containerHeight} />
            </View>
            {(() => {
                if (!this.props.showDataPoint) return null;

                var multipleDataPoints = dataPoints.map( (dataPointSet, index) => {
                    let totalDataSet = dataPointSet.map((d, i) => {
                        return (
                            // <TouchableOpacity>
                              <Circle key={i} {...d} onPress={()=>alert(i)} />
                            // </TouchableOpacity>
                        );
                    });
                    return totalDataSet;
                });

                return (
                    <Surface width={containerWidth} height={containerHeight}>
                        { multipleDataPoints }
                    </Surface>
                );
            })()}
        </View>
    );
````

### Additional Information

* React Native version: 0.39.2
* Platform: iOS
* Operating System: MacOSX 10.12.2

**Comment by ericvicenti** [comment]
I'm closing this because it sounds like a bug with `react-native-chart`. I'm not sure this functionality is supported

Out of curiosity, does the same thing happen with `TouchableWithoutFeedback` ? It works in a different way and may be less fragile

**Comment by Vikaton** [comment]
Actually, adding any component in that return block will result in that error.

**Comment by ericvicenti** [comment]
Yeah, the library probably expects you to render specific things as children of Surface

**Comment by Vikaton** [comment]
Do you possibly know of a way to return multiple components?

**Comment by ericvicenti** [comment]
Sorry, I don't have any experience with `react-native-chart`
