### ISSUE TITLE
Navigator onItemRef never called

### ISSUE THREAD

**Issue by magrinj** [facebook/react-native#11734]
Hi guys,

I've a problem with `onItemRef` on `react-native@^0.36.1`, this function is never called anymore and I don't understand why :/ 
I use it in my navigator to add the following functions: `componentWillFocus`, `componentDidFocus`, `componentWillBlur` and `componentDidBlur`.

```javascript
            <Navigator
              initialRoute={ initialRoute }
              onItemRef={(ref, index, route) => {
                route.sceneRef = ref;
              }}
              onWillFocus={(route) => {
                if (route.sceneRef && route.sceneRef.componentWillFocus) {
                  route.sceneRef.componentWillFocus();
                }
              }}
              onDidFocus={(route) => {
                if (route.sceneRef && route.sceneRef.componentDidFocus) {
                  route.sceneRef.componentDidFocus();
                }
              }}
              onWillBlur={(route) => {
                if (route.sceneRef && route.sceneRef.componentWillBlur) {
                  route.sceneRef.componentWillBlur();
                }
              }}
              onDidBlur={(route) => {
                if (route.sceneRef && route.sceneRef.componentDidBlur) {
                  route.sceneRef.componentDidBlur();
                }
              }}/>
```

**Comment by ericvicenti** [comment]
Maybe you can look at the history of `Navigator.js` over the time period where it broke, and find the offending diff?

In a month or two we will be removing `Navigator` from `react-native`, so you may want to simply copy a working version of Navigator into your project and use it directly.

**Comment by magrinj** [comment]
Ok thanks I will look the file history :)

**Comment by magrinj** [comment]
Apparently `onItemRef` was removed here, and a new function `getRouteID` was created: https://github.com/facebook/react-native/commit/4f904b5d68d1176cabf51b3a476d11b61fb07bd1
I don't really know how to use it

**Comment by hramos** [comment]
Navigator has been deprecated in favor of the [`react-navigation`](https://reactnavigation.org) library.
