### ISSUE TITLE
Watchman was not found

### ISSUE THREAD

**Issue by junaidahmed93** [facebook/react-native#11731]
Hello everyone,
I am new to react-native. I have already installed watchman using npm but still facing this problem.
Also tried some manual installation process for watchman but no luck.

```
[01/05/2017, 12:56:42] <START> Initializing Packager
Watchman:  Watchman was not found in PATH.  See https://facebook.github.io/watchman/docs/install.html for installation instructions
[01/05/2017, 12:56:42]         HMR Server listening on /hot

React packager ready.

jest-haste-map: Watchman crawl failed. Retrying once with node crawler.
  Usually this happens when watchman isn't running. Create an empty `.watchmanconfig` file in your project's root folder or initialize a git or hg repository in your project.
  Error: Watchman was not found in PATH.  See https://facebook.github.io/watchman/docs/install.html for installation instructions
Watchman:  Watchman was not found in PATH.  See https://facebook.github.io/watchman/docs/install.html for installation instructions
 ERROR  Watchman was not found in PATH.  See https://facebook.github.io/watchman/docs/install.html for installation instructions
{"code":"ENOENT","errno":"ENOENT","syscall":"spawn watchman","path":"watchman","spawnargs":["--no-pretty","get-sockname"]}
Error: Watchman was not found in PATH.  See https://facebook.github.io/watchman/docs/install.html for installation instructions
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

See http://facebook.github.io/react-native/docs/troubleshooting.html
```

**Comment by ericvicenti** [comment]
Yes this should be fixable with a proper installation of watchman and putting it in your `PATH` env. Feel free to re-open if this isn't the issue and you have more details

**Comment by junaidahmed93** [comment]
What does it mean by proper installation of watchman
it seem there is nothing to install watchman for windows.
I haven't found a single way to install watchman on windows, already tried with, scoop , chocolatey but there is nothing to install. Only npm providing watchman package but the error is same again after re-installations
.

**Comment by IgorVanian** [comment]
I have the same issue here...

**Comment by davkuzmin** [comment]
Likewise, I ran `npm install -g watchman` but still no dice.

**Comment by aaronksaunders** [comment]
@ericvicenti can you please point all of us to the "proper documentation" for installing watchman on windows?

**Comment by junaidahmed93** [comment]
try `npm uninstall -g watchman` then build (without installing again).

**Comment by davkuzmin** [comment]
That fixed it!

**Comment by aniket-jft** [comment]
try npm uninstall -g watchman then run  npm install -g watchman

**Comment by tirumalavasu** [comment]
On mac, try to uninstall watchman and install with homebrew.
-> npm uninstall -g watchman
-> brew update
-> brew install watchman
