### ISSUE TITLE
TextInput: returnKeyType=done does not work with keyboardType=numeric

### ISSUE THREAD

**Issue by arjunpola** [facebook/react-native#11739]
I have a 'numeric' or 'phone-pad' text field and it does not show the `Done` button when I use the prop `returnKeyType="done"`

```JSX
<MKTextField
  textInputStyle={ {flex:1, color: 'black'} }
  returnKeyType={ "done" }
  keyboardType = { "phone-pad" } />
```

`MKTextField` is a MaterialKitTextField which is nothing but a custom implementation of TextInput. And the result is same when MKTextField is replaced by TextInput.

* React Native version: 0.39.2
* Platform: iOS
* Operating System: MacOS

**iOS Screenshot**
![iOS_screenshot](https://cloud.githubusercontent.com/assets/4324936/21702020/ebb128e4-d35d-11e6-975d-785335444f98.png)

**Android Screenshot**
![android_screenshot](https://cloud.githubusercontent.com/assets/4324936/21702208/20d91634-d35f-11e6-8924-e6f4d6b016df.png)

**Comment by shergin** [comment]
It is iOS limitation. If you need "Done" button for numeric keyboard, you have to place it manually on `inputView` (toolbar bellow the keyboard). I don't think that it should be implemented inside React Native core.

http://stackoverflow.com/questions/584538/how-to-show-done-button-on-iphone-number-pad

**Comment by christopherdro** [comment]
@facebook-github-bot answered
