### ISSUE TITLE
Push getInitialNotification

### ISSUE THREAD

**Issue by AtixD** [facebook/react-native#11737]
Push getInitialNotification() always return null on start app.. What about? thx.

```
PushNotificationIOS.getInitialNotification().then(function (notification) {
  if (notification != null) {
    appOpenedByNotificationTap(notification);
  }
});
```

* React Native version: 0.38
* Platform: ios
* Operating System: 9.3 iPad

**Comment by ericvicenti** [comment]
Hi, you probably need to configure your linking. In xcode, if you want to be able to link to something like `reactnav://mypath`, you need to configure this: 
<img width="1072" alt="screenshot 2017-01-06 11 54 49" src="https://cloud.githubusercontent.com/assets/1483597/21730966/035301a8-d407-11e6-946b-855b7a0323ba.png">

If you still have the issue, please re-open!

**Comment by ericvicenti** [comment]
Have you set up the native module according to the guide? How did you test it?
