### ISSUE TITLE
BUG: fetch request is not finished when interrupted by losing network connectivity

### ISSUE THREAD

**Issue by carlobambo** [facebook/react-native#11743]
### Description

There are times when a fetch request is not finished. After that, there are times where all subsequent request won't reach the server.

### Reproduction
https://github.com/carlobambo/fetch-example-issue

Check the repository above for code sample.

1. Run multiple fetch with a little delay (tap restart on app)
3. Turn off wifi
4. Turn on wifi
5. Execute fetch api (tap add on the app)

Result:
There are requests that were not finished or it takes too long.
And there are times where subsequents request where not reaching the server and does not finished at all. Restarting the app will solve the issue, that is why I am unsure if the cause is network connection or the app itself.

### Additional Information
My laptop is connected on a Wifi repeater with a weak signal and the app is running on emulator. But we also experience it on our production app running on a real device.
* React Native version: 0.38.1
* Platform: Android ( not tested on IOS )
* Operating System: MacOS

**Comment by cbrevik** [comment]
We've also noticed the same issue with React Native 0.39.0

Subsequent fetches will not reach the server. We have to hard-quit the app to be able to re-fetch.

**Comment by carlobambo** [comment]
Will this be fix or any workaround for this issue?

**Comment by cbrevik** [comment]
You could look at [other networking libraries](https://facebook.github.io/react-native/docs/network.html#using-other-networking-libraries) and see if they will work better. 

Personally I went for a quick-fix instead, and reloaded the JS-bundle in order to get out of the bad state. Using [react-native-restart](https://github.com/avishayil/react-native-restart) worked fine for the latter.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/bug-fetch-request-is-not-finished-when-interrupted-by-losing-network-connectivit
