### ISSUE TITLE
Image.prefetch does not help for preloading

### ISSUE THREAD

**Issue by Maxim-Chugaev** [facebook/react-native#11740]
latest MAC OS X
latest IOS
on device and simulator
```javascript
export default class Avatar extends Component {

	static propTypes = {
		host: React.PropTypes.string.isRequired,
		path: React.PropTypes.string.isRequired,
		avatar: React.PropTypes.number.isRequired
	}

	static prefetch (host) {
		let range = [0,1,2,3,4];
		let matrix = [].concat.apply([],range.map(i => range.map( z => [i,z] )));

		let tasks = matrix.reduce((cur, [i,z])=>{
				return cur.concat([
					Image.prefetch(`${host}/male/${i}/${z}.png`),
					Image.prefetch(`${host}/female/${i}/${z}.png`)
				]);
			}, []);

		return Promise.all(tasks);
		
	}

	_generatePaths () {
		let { path, avatar, host } = this.props;
        avatar = ('00000'+avatar.toString(5)).slice(-5);
		return avatar.split('').map((number, i )=> {
			return {uri:`${host}/${path}/${number}/${i}.png`, width: 50, height: 10};
		});
	}

    render () {
        return (
        	<View style={styles.avatar}>
        		{
        			this._generatePaths().map((source, i)=>{
        				return (<Image key={i} source={source} />);
        			})
        		}
            </View>
        );
    }

Avatar.prefetch('myhost').then((res)=>{
	console.log('success', res);
}).catch(()=>{
	console.log('error');
});
};
```

**Comment by nihgwu** [comment]
Why do you think Image.prefetch will speed up you downloads? It's for image cache to speed up render performance

**Comment by Maxim-Chugaev** [comment]
@nihgwu 
I do not exactly put it. Of course you say is true, but I do not see any change from the use of prefetch.

**Comment by nihgwu** [comment]
You are in the wrong way, if you want to navigate to a detail view and have a big header image, you can prefetch if before navigation

**Comment by Maxim-Chugaev** [comment]
@nihgwu i use prefetch images in a few screens, and i not see any difference, absolutely! I use prefetch before navigation and after navigation and everywhere! Where i can read about cache policy? In official documents there is no mention of this.

**Comment by nihgwu** [comment]
search the PRs, there is a PR changed the cache policy completely, makes image cache unavailable in some occasion

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.

**Comment by hpierce93** [comment]
Are there any updates to this? Prefetch does not speed up render performance for me either. On iOS I can use force-cache, but I would like prefetch to work for Android purposes..
