### ISSUE TITLE
HorizontalSwipeJumpFromRight FadeToTheEnd?

### ISSUE THREAD

**Issue by alanshaw** [facebook/react-native#11751]
### Description

Using `HorizontalSwipeJump` the scenes transition as expected, however when using `HorizontalSwipeJumpFromRight` the transition uses a fade, and does not move as it does using HorizontalSwipeJump or HorizontalSwipeJumpFromLeft.

https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/Navigator/NavigatorSceneConfigs.js#L719

...instead of `directionMapping.FadeToTheEnd` should this be `directionMapping.ToTheEnd` as it is for `HorizontalSwipeJumpFromLeft`?

### Additional Information

* React Native version: 0.39
* Platform: both
* Operating System: n/a

**Comment by ericvicenti** [comment]
I'm sorry if the naming is confusing, you can feel free to fork this and rename things in your project.

There is no more work planned on Navigator, and we will be removing it from react-native in a few months. If you're using it in your existing project, you may want to copy it into your codebase or use a fork like ex-navigator. If you're working on a fresh project or are looking to switch, ex-navigation is the best option available at the moment, but we're working on a new option to be released in the coming weeks.
