### ISSUE TITLE
[Android4.1-4.3][v0.39]WebView source={{html}} show all html string without parse html if 'baseUrl' is set

### ISSUE THREAD

**Issue by peichao01** [facebook/react-native#11753]
### Description

use source={{baseUrl: 'xx', html:`<h1>Hi</h1><script>alert(1);</script>`}}
Android4.3 looks like treat webview as <Text>, will output all html string in View,
use html=`xxx` or source={{html:`xxx`}} works

### Reproduction

very simple code will reproduce:

```jsx
export default class RootComponent extends Component {
  render() {
    // return this.render2();
    return this.render1();
  }
  // warn, but works!! except can not alert
  render2 () {
    return (
      <WebView
        // html="<h1>H1</h1><script>alert(1);</script>" // or the following works
        source={{html: "<h1>H1</h1><script>alert(1);</script>"}}
      />
    )
  }
  // will show all html string in View like <Text> label
  render1 () {
    return (
      <WebView
        source={{
          baseUrl: 'http://test.com',
          html="<h1>H1</h1><script>alert(1);</script>"
        }}
      />
    )
  }
}
```

![wechatimg21](https://cloud.githubusercontent.com/assets/844740/21725485/9f6a9c10-d473-11e6-9434-85c23a0cc9ae.jpeg)
![wechatimg22](https://cloud.githubusercontent.com/assets/844740/21725486/9fb5cf32-d473-11e6-8a7c-1b39e66a0245.jpeg)

### Additional Information

* React Native version: [v0.39]
* Platform: [Android4.1-4.3, not test Android4.4]
* Operating System: [MacOS]

**Comment by peichao01** [comment]
And, Android4.3 webview can not use: window.alert('something')

**Comment by Exilz** [comment]
I can confirm this happens on RN 0.39 on my Galaxy S3 with Android 4.3.

**Comment by ivanzotov** [comment]
same issue

**Comment by Exilz** [comment]
Same thing happened in the NativeScript project, looks like the solution is quite simple
https://github.com/NativeScript/NativeScript/issues/1038

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.

**Comment by stereodenis** [comment]
@hramos could you reopen it, cause it is still not fixed?
