### ISSUE TITLE
build release apk failing, missing directory: android/app/src/main/assets/

### ISSUE THREAD

**Issue by goldylucks** [facebook/react-native#11767]
### Description
I've tried to build release apk from terminal, and got an error.

### Reproduction
```bash
$ react init myApp
$ cd myApp && npm install
$ cd android && ./gradlew assembleRelease && cd ..
$ react-native run-android --configuration=release
bundle: Writing bundle output to: android/app/src/main/assets/index.android.bundle

ENOENT: no such file or directory, open 'android/app/src/main/assets/index.android.bundle'

Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

(node:24734) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'message' of undefined
```

### Solution
ATM I'm manually creating the missing directory after I init a project with  
`$ mkdir android/app/src/main/assets`

This folder should b created with react-init

### Additional Information
* React Native version: `0.40.0`
* Platform: android
* Operating System: Linux, Ubuntu 16.04

**Comment by goldylucks** [comment]
I could provide a PR with some guidance :)

**Comment by jagi** [comment]
Thanks! I had the same problem and didn't know that solution is so simple :)

**Comment by MrToph** [comment]
+1 same issue here. Running `react-native upgrade` also didn't create the missing `asset` directory.

**Comment by dsimmons** [comment]
> +1 same issue here. Running `react-native upgrade` also didn't create the missing asset directory.

^ Just ran across this exact issue. Specifically, `0.39` (fresh install) -> `0.40`.

**Comment by goldylucks** [comment]
This is probably a one line addition to fix.

Since it's obviously affects a LOT of RN users, any reason this is not fixed?

I could prepare a PR if I get some pointers (never touched RN cli code)

**Comment by jqn** [comment]
This works for now `react-native run-android --configuration=release`

**Comment by JaysonMandani** [comment]
Add this missing lines `android/app/src/main/assets/index.android.bundle` to your directory then run again the release configuration

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/build-release-apk-failing-missing-directory-androidappsrcmainassets

**Comment by devbriguy** [comment]
Hi, I am able to reproduce this on MS App Center build with a custom `buildType`. I can resolve it locally by running react-native bundle command which will generate the bundle but it's unclear if something is skipped in bundling the custom `buildType`. To clarify, custom `buildType` as in *not* debug or release.

react-native: 0.46.3
