### ISSUE TITLE
How to get Device Token for PushNotificationIOS

### ISSUE THREAD

**Issue by lazywei** [facebook/react-native#1176]
I expected the `PushNotificationIOS.requestPermissions` to return token if permission is granted. However, it didn't. So I'm wondering is there any way I can get the token for push notification?

Thanks

**Comment by iostalk** [comment]
Watch

**Comment by nicklockwood** [comment]
cc @tadeuzagallo

**Comment by lazywei** [comment]
I found there is a relevant issue: https://github.com/facebook/react-native/issues/568#issuecomment-90972246
not sure if @darylrowland's https://github.com/darylrowland/react-native-remote-push works though

**Comment by lazywei** [comment]
ping @tadeuzagallo @nicklockwood . really need this for push notification working.

**Comment by tadeuzagallo** [comment]
@lazywei It's not supported yet, but should be pretty straight forward to implement. A pull request for that would be much appreciated! :)

**Comment by brentvatne** [comment]
Being tracked in the PR mentioned above :smile: nice work
