### ISSUE TITLE
AccessToken is null after app restart

### ISSUE THREAD

**Issue by Amurmurmur** [facebook/react-native#11762]
### Description

fbsdk stopped working after the upgrade from RN 0.39 to RN 0.40. AccessToken returns null after app restart, even tho everything worked right before the upgrade of the RN itself. 

react-native-fbsdk header have been fixed from <RCTThing.h> to <React/RCTThing.h>

Seems like the problem only occurs on the iOS platform. Android works fine.
As said Keychain and AppDelegate has been setup and was untouched, only RN was updated, when the problem started to occur :(
### Reproduction

Upgrade from 0.39 to 0.40

### Solution

No solution :/

### Additional Information

* React Native version: 0.40
* Platform: iOS only
* Operating System: MacOS

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
