### ISSUE TITLE
fetch(`${imageUrl}`) throw RCTDeviceEventEmitter:emit error when fetch image without `Debug JS Remotely`

### ISSUE THREAD

**Issue by peichao01** [facebook/react-native#11764]
### Description

when fetch(imgUrl), throw an error(and can not relation to fetch API after read the Error message),
works fine in `Debug JS Remotely`

### Reproduction

```jsx
componentDidMount() {
  var avatarUrl = 'https://avatars1.githubusercontent.com/u/844740?v=3&s=88';
  fetch(avatarUrl);
}
```

### Additional Information

* React Native version: [0.39, 0.40]
* Platform: [Android6, not test Android7, not test iOS]
* Operating System: [MacOS]

![image](https://cloud.githubusercontent.com/assets/844740/21739455/4be49fce-d4d6-11e6-9403-c7ef9ba0c221.png)

**Comment by yinoneliraz** [comment]
Got the same error with componentWillReceiveProps.

```
  componentWillReceiveProps(nextProps){
    var temp;
    temp=this.state.profileInfo;
    temp.image='http://s3.amazonaws.com/cdn.roosterteeth.com/default/tb/user_profile_female.jpg';
    this.setState({
      profileInfo:temp,
    }, () => {
      console.log(this.props);
      console.log("Updated!!!");

      var api = 'https://graph.facebook.com/' + nextProps.owner_id +
        '/picture?type=normal&access_token=' + nextProps.credentials.token;
      fetch(api)
        .then((response) => {
          var temp;
          temp = this.state.profileInfo;
          temp.image = response.url;
          this.setState({
            profileInfo: temp,
          });
        })
        .done();
    });
  },
```

**Comment by eggytronixx** [comment]
I got the same issue. It only works in Debug JS Remotely

**Comment by arsenslyusarchuk** [comment]
Similar issue happens on Android (IOS works fine). Anybody resolved this?

**Comment by Barylskyigb** [comment]
Same issue while fetching images on react-native v0.44.1

**Comment by cbjs** [comment]
+1
