### ISSUE TITLE
Not possible to use chrome debugger with multiples bundles

### ISSUE THREAD

**Issue by fabriciovergal** [facebook/react-native#11768]
### Description

Steps: 
1. Create empty with react-native init
2. install on Android and iOS  
3. Start chrome debugger in both devices
4. Try to use the app at same time

Currently:
Using the app on one device drop the connection in the other.

Expected:
Able to use both device without the connection being dropped.
Able to open a debugger tab for each bundle or at least log prefix regarding the platform

I'm working in a library to execute a second bundle in a new worker to process massive amount of data, but due to this behavior the app  lost connection right after loading the second bundle.

### Reproduction

Every time

### Solution

Sorry, not sure what could be done.

### Additional Information

* React Native version: [0.39, 0.49]
* Platform: [OS, Android]
* Operating System: [MacOS]

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
