### ISSUE TITLE
Unable to resolve module http from...

### ISSUE THREAD

**Issue by kfir91** [facebook/react-native#11772]
Hello,
Suddenly when i run my app - "react-native start"
i got error: 
https://s23.postimg.org/h85k32aaz/image.png

i tried all the options that he suggested like:
clear cache, delete watchme list, delete temp with react, and delete the app and create new app...
the error come when i use require("somemodule") ...
(i tried to reinstall the axios too).
what can i do?

i work on windows 7 and android

**Comment by tedjames** [comment]
Unfortunately, this problem has yet to be resolved. Refer to this issue for a workaround: [https://github.com/facebook/react-native/issues/11498#issuecomment-267472269](url)

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.

**Comment by lufinkey** [comment]
I am still having this problem. It should be reopened

**Comment by caschomburg123** [comment]
hey Luis! It's your old girlfriend

e <notifications@github.com> wrote:


On Jan 13, 2018, at 9:32 PM, Luis Fink

I am still having this problem. It should be reopened

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/facebook/react-native/issues/11772#issuecomment-357483904>,
or mute the thread

**Comment by lufinkey** [comment]
?

**Comment by robertjuh** [comment]
looks like luis shared something he didnt mean to share

**Comment by lufinkey** [comment]
I have no idea what's going on with that comment

**Comment by ide** [comment]
(Maintainer note: I removed a comment unrelated to this PR or React Native. Please keep the discussions in PRs on topic.)

**Comment by lufinkey** [comment]
Turns out react-native doesn't support the built-in node modules, which is why they weren't getting resolved. However that isn't documented anywhere and I had to find it out from a blog post.
