### ISSUE TITLE
is there anysolution,to open a webview with a post request?

### ISSUE THREAD

**Issue by aqnaruto** [facebook/react-native#11773]
seems webview don't surpport ‘method’,'credentials','body'  , does there have any solution to to open a webview with a post request?

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.

**Comment by baldursson** [comment]
For those of you ending up here looking for answers, this is actually possible now. You can do:
`<WebView source={ { uri: 'http://www.example.com', method: 'POST' } } />`

**Comment by hhunaid** [comment]
@baldursson and how to attach post body?
