### ISSUE TITLE
Unable to run release build

### ISSUE THREAD

**Issue by laclance** [facebook/react-native#11786]
I am trying to deploy my app to android. I follow the steps on this page https://facebook.github.io/react-native/docs/signed-apk-android.html.

When I try to run it, it tells me not such file or directory '.../assets/index.android.bundle'

or i get Task 'installReleaseDebug' not found in root project 'awezaEduApp'

Using Windows 10 and react-native 0.39.2

Any help would be appreciated please.

**Comment by MrToph** [comment]
Hi, see #11767 . A temporary fix is to create the `assets` folder manually.

**Comment by laclance** [comment]
Thank you, but now i get this error

![image](https://cloud.githubusercontent.com/assets/10835285/21779392/2b9b3b66-d6b0-11e6-8707-485381690bca.png)

**Comment by laclance** [comment]
Had to reformat my laptop for other reasons. I redid the signing process and everything is working. I see that --variant=release changed to --configuration=release from v0.39.x. I will update the docs and put in a pull request when i get a chance.

**Comment by jqn** [comment]
`react-native run-android --configuration=release` worked for me with release 0.40
