### ISSUE TITLE
Problem with the Border Bottom 

### ISSUE THREAD

**Issue by farid-neopixe** [facebook/react-native#11789]
Hello guys , 

i have a problem with the Textinput specially the border Bottom , it doesn't show up at all .. 
here's how it looks now :
![screen shot 2017-01-09 at 15 51 34](https://cloud.githubusercontent.com/assets/20015003/21772521/902916a2-d683-11e6-8ba0-8908116566b5.png)

and here's the code  : 

![screen shot 2017-01-09 at 15 52 41](https://cloud.githubusercontent.com/assets/20015003/21772546/b09c4a3a-d683-11e6-8e4d-5f6b203f6aaa.png)

can you please tell me what the problem might be ?

**Comment by wojteg1337** [comment]
i think you need to share more code, styles are not enaugh

**Comment by farid-neopixe** [comment]
@wojteg1337 okay , here's more code 
render() {
    return(
      <View style={styles.container}>
        <View style={styles.welcoming}>
          <Image style={styles.logo} source={require('../images/logo.png')}/>
          <Text style={styles.welcome}>
            Welcome to React
          </Text>
          <Text style={styles.slogan}>
            Team Communication for more the 20 years!
          </Text>
        </View>
        <View style={styles.inputContainer}>
          <TextInput style={styles.inputFiled} onChange={this.handleChange} value={this.state.username} placeholder="Username"/>
          <TextInput secureTextEntry={true} onChange={this.handleChange} value={this.state.username} style={styles.inputFiled}  placeholder="Password"/>
            <View style={styles.button}>
              <TouchableHighlight>
                <Text onPress={() => Actions.home()} style={styles.login}>
                  Login
                </Text>
              </TouchableHighlight>
            </View>
        </View>
        <View style={styles.navigation}>
          <Text  onPress={() => Actions.register()} style={styles.signup}>
            Sign up for an Account
          </Text>
        </View>
      </View>
    )
  }
}

const styles = StyleSheet.create({
  container : {
    flex : 1 ,
    backgroundColor : '#fff',
  },
  welcoming : {
    backgroundColor : '#fff',
    flex : 2,
    justifyContent : 'center',
    alignItems : 'center',
  },
  inputContainer :{
    flex : 2,
    flexDirection : 'column',
  },
  inputFiled : {
    height : 50,
    width : 300,
    alignItems : 'center',
    borderBottomWidth : 1,
    borderBottomColor : 'black',
    color : 'black',
    marginTop : 10,
  },
  button : {
    alignItems : 'center',
    top : 60,
  },
  logo : {
    width  : 70 ,
    height : 70 ,
  },
  welcome : {
    fontSize : 25,
    color : '#A593E0',
    fontWeight : 'bold',
    marginTop : 20,
    marginBottom : 10,
  },
  slogan : {
    color  : '#404040'
  },
  navigation : {
    flex : 0.4 ,
    justifyContent : 'center',
    backgroundColor : '#fff',
    alignItems : 'center',
  } ,
  signup: {
    color : 'gray',
    fontSize : 15,
  },
  login : {
    paddingTop : 10,
    paddingLeft : 40,
    paddingBottom : 10,
    paddingRight : 40,
    backgroundColor : '#A593E0',
    color : '#fff',
  }
})

**Comment by farid-neopixe** [comment]
@wojteg1337 okay , here's more code 
`render() {
    return(
      <View style={styles.container}>
        <View style={styles.welcoming}>
          <Image style={styles.logo} source={require('../images/logo.png')}/>
          <Text style={styles.welcome}>
            Welcome to React
          </Text>
          <Text style={styles.slogan}>
            Team Communication for more the 20 years!
          </Text>
        </View>
        <View style={styles.inputContainer}>
          <TextInput style={styles.inputFiled} onChange={this.handleChange} value={this.state.username} placeholder="Username"/>
          <TextInput secureTextEntry={true} onChange={this.handleChange} value={this.state.username} style={styles.inputFiled}  placeholder="Password"/>
            <View style={styles.button}>
              <TouchableHighlight>
                <Text onPress={() => Actions.home()} style={styles.login}>
                  Login
                </Text>
              </TouchableHighlight>
            </View>
        </View>
        <View style={styles.navigation}>
          <Text  onPress={() => Actions.register()} style={styles.signup}>
            Sign up for an Account
          </Text>
        </View>
      </View>
    )
  }
}

const styles = StyleSheet.create({
  container : {
    flex : 1 ,
    backgroundColor : '#fff',
  },
  welcoming : {
    backgroundColor : '#fff',
    flex : 2,
    justifyContent : 'center',
    alignItems : 'center',
  },
  inputContainer :{
    flex : 2,
    flexDirection : 'column',
  },
  inputFiled : {
    height : 50,
    width : 300,
    alignItems : 'center',
    borderBottomWidth : 1,
    borderBottomColor : 'black',
    color : 'black',
    marginTop : 10,
  },
  button : {
    alignItems : 'center',
    top : 60,
  },
  logo : {
    width  : 70 ,
    height : 70 ,
  },
  welcome : {
    fontSize : 25,
    color : '#A593E0',
    fontWeight : 'bold',
    marginTop : 20,
    marginBottom : 10,
  },
  slogan : {
    color  : '#404040'
  },
  navigation : {
    flex : 0.4 ,
    justifyContent : 'center',
    backgroundColor : '#fff',
    alignItems : 'center',
  } ,
  signup: {
    color : 'gray',
    fontSize : 15,
  },
  login : {
    paddingTop : 10,
    paddingLeft : 40,
    paddingBottom : 10,
    paddingRight : 40,
    backgroundColor : '#A593E0',
    color : '#fff',
  }
})`

**Comment by ikalafat** [comment]
@farid-neopixe check this:

https://github.com/facebook/react-native/issues/7029

**Comment by damusnet** [comment]
@facebook-github-bot duplicate #7029
