### ISSUE TITLE
[ImageLoader] Loading images from the <Application_Home> directory.

### ISSUE THREAD

**Issue by lukasreichart** [facebook/react-native#1178]
In my application I'am using the react-native-camera module to capture images and I write them to a subfolder of the \<Application_Home> directory.
It would be really nice to be able to use the React Image element to load those images from the \<Application_Home> directory. 
My proposal is to add another supported "protocol" to the RCTImageLoader class called "file".
```javascript
<Image source={{uri: "file://tmp/test.jpg"}} style={{ width: 100, height: 100 }}/>
```
Which would in this case try to load the image from \<Application_Home>/tmp/test.jpg .
Anyone else interested in this approach?

**Comment by nicklockwood** [comment]
I agree, we need a standard way to do this. I'm not sure I like using file:// for this though.

Maybe starting the path with "~/..." would make more sense?

**Comment by iostalk** [comment]
I have a good idea

**Comment by lukasreichart** [comment]
@iostalk that would be?

**Comment by iostalk** [comment]
A pull request would be appreciate

**Comment by brentvatne** [comment]
@nicklockwood - I like that idea! @lukasreichart - any interest in submitting a PR?
