### ISSUE TITLE
js api facebook-chat-api doesn't run with react-native

### ISSUE THREAD

**Issue by uragecz** [facebook/react-native#11782]
I am trying to work with this api with react-native, but after import - `var login = require("facebook-chat-api");` i am getting error
![1](https://cloud.githubusercontent.com/assets/15018124/21766586/ae603e66-d66f-11e6-889f-50978019d406.PNG)
![2](https://cloud.githubusercontent.com/assets/15018124/21766591/b2edcc50-d66f-11e6-8ec0-3ec0d48e7337.PNG)
I tried clean installation again, but same error, any experiences with this error message?

**Comment by uragecz** [comment]
So i fixed this error message by setting debug mode on, but now i am getting new error
![3](https://cloud.githubusercontent.com/assets/15018124/21767196/e2f45858-d672-11e6-89ae-291196d6b2b5.PNG)

**Comment by Proberts** [comment]
After adding any node module I think you always have to restart the react native packager (react-native start), otherwise you get that 500 error.

**Comment by uragecz** [comment]
I tried to delete entire project and create new, with restarting android, and computer too :D so it isn't this case :/

**Comment by Ehesp** [comment]
Try doing:

```
import { login } from "facebook-chat-api";
```

They're not exporting a default here: https://github.com/Schmavery/facebook-chat-api/blob/master/index.js#L433

**Comment by uragecz** [comment]
I tried, but same.. and when i am using debug mode, i am getting 
```
13:53:22 Adb connection Error:An existing connection was forcibly closed by the remote host
13:53:23 Connection attempts: 1
```
It has something in common with... ?

**Comment by Ehesp** [comment]
Don't think so. Try restarting your emulator.

**Comment by uragecz** [comment]
I tried too... i restarted entire computer too :D same error all time :/ with new project too.. i just cant import anything from `facebook-chat-api`..

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
