### ISSUE TITLE
Websocket messages not received even with appropriate app background policy set on iOS

### ISSUE THREAD

**Issue by jeremyong** [facebook/react-native#11795]
### Description

Something changed that breaks the behavior of websockets when the app is backgrounded on iOS. Instead of the messages being bubbled to the onmessage callback in JS immediately, they are buffered and all callbacks issued when the app is foregrounded.

In a debugger, the handleMessage on the websocket is in fact invoked but this does not bubble up to the JS layer.

### Reproduction

Make a websocket. Move app to background. Send messages to the client.

### Solution

I believe that something is causing the thread that handles javascript callbacks to get suspended when the app is in the background

### Additional Information

* React Native version: 0.39
* Platform: iOS
* Operating System: MacOS

**Comment by jeremyong** [comment]
Additional information: I'm no iOS expert but I'm curious if a change happened in iOS 10 that causes certain dispatch queues to suspend the message pump while the app is in the background.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/websocket-messages-not-received-even-with-appropriate-app-background-policy-set-
