### ISSUE TITLE
React Native - Image isn't cleared when navigating

### ISSUE THREAD

**Issue by rahmanusta** [facebook/react-native#11800]
I use React Native's Navigator for routing and ListView to show image group, and I use Android. When I trigger navigation, image(s) don't leave page and it blinks as seen below. I opened the issue at stackoverflow but I didn't get good answers. http://stackoverflow.com/questions/41550822/react-native-image-isnt-cleared-when-navigating

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/1158804/21796314/ab3e8368-d710-11e6-85d4-7c119fce7ea7.gif)

**Render functions**

```
_renderRow (rowData){
    return (
       <TouchableWithoutFeedback onPress={()=>this._getCampaigns(rowData)}>
           <Image style={{width: 120, height: 120}}
              source={{uri: rowData.logo, scale: 1}}/>
           </TouchableWithoutFeedback>)
}

render() {
   return (<View style={styles.container}>
      <ListView dataSource={this.state.imageList} 
       contentContainerStyle={styles.list}
       renderRow={(rowData)=> this._renderRow(rowData)}/>
   </View>);
}
```

**Styles**

```
const styles = StyleSheet.create({
        container: {
            flex: 1
        },
        list: {
            flexDirection: 'row',
            flexWrap: 'wrap'
        }
});
```

What could be the reason?

Thanks.

* React Native version:0.40.0
* Platform: Android, never tested with IOS
* Operating System: Windows 10

**Comment by ms88privat** [comment]
It looks like, your pushed View has no backgroundColor - so you will see the view below until the animation completely stopped?

**Comment by rahmanusta** [comment]
Yes this is right, but I wonder is it normal?

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
