### ISSUE TITLE
React Packager start fail after upgrading RN from 0.38.0 to 0.40.0

### ISSUE THREAD

**Issue by monumentyusuf** [facebook/react-native#11811]
Hello,

React packager start fails after i upgrade RN 0.40.0 here is npm-debug logs

> 0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/7.4.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start' ]
2 info using npm@4.0.5
3 info using node@v7.4.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle monumentandroid@0.0.1~prestart: monumentandroid@0.0.1
6 silly lifecycle monumentandroid@0.0.1~prestart: no script for prestart, continuing
7 info lifecycle monumentandroid@0.0.1~start: monumentandroid@0.0.1
8 verbose lifecycle monumentandroid@0.0.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle monumentandroid@0.0.1~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/monument/development/m-android/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/monument/Library/Android/sdk/tools:/Users/monument/Library/Android/sdk/platform-tools
10 verbose lifecycle monumentandroid@0.0.1~start: CWD: /Users/monument/development/m-android
11 silly lifecycle monumentandroid@0.0.1~start: Args: [ '-c',
11 silly lifecycle   'node node_modules/react-native/local-cli/cli.js start' ]
12 silly lifecycle monumentandroid@0.0.1~start: Returned: code: 1  signal: null
13 info lifecycle monumentandroid@0.0.1~start: Failed to exec start script
14 verbose stack Error: monumentandroid@0.0.1 start: `node node_modules/react-native/local-cli/cli.js start`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid monumentandroid@0.0.1
16 verbose cwd /Users/monument/development/m-android
17 error Darwin 16.3.0
18 error argv "/usr/local/Cellar/node/7.4.0/bin/node" "/usr/local/bin/npm" "start"
19 error node v7.4.0
20 error npm  v4.0.5
21 error code ELIFECYCLE
22 error monumentandroid@0.0.1 start: `node node_modules/react-native/local-cli/cli.js start`
22 error Exit status 1
23 error Failed at the monumentandroid@0.0.1 start script 'node node_modules/react-native/local-cli/cli.js start'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the monumentandroid package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node node_modules/react-native/local-cli/cli.js start
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs monumentandroid
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls monumentandroid
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

* React Native version: 0.40.0
* Platform: Android
* Operating System: MacOS Sierra 10.12.2

**Comment by Ehesp** [comment]
Have you nuked node modules? Usually seems to do the trick.

**Comment by monumentyusuf** [comment]
Thanks @Ehesp nuking node modules worked!
