### ISSUE TITLE
Document upoader or picker?

### ISSUE THREAD

**Issue by radvc** [facebook/react-native#11812]
Hi, just want to ask if anyone knows how to build document picker or file picker to upload for IOS. Thanks

**Comment by sriraman** [comment]
You can try [React Native Image Picker](https://github.com/marcshilling/react-native-image-picker), If you just want to pick images. 

If you want to pick any file, Then Try [React Native File picker](https://github.com/Lichwa/react-native-file-picker)

**Comment by radvc** [comment]
@sriraman I tried that one but i've got an error and its not an npm package

**Comment by damusnet** [comment]
@facebook-github-bot stack-overflow
