### ISSUE TITLE
Document required macOS / OS X / XCode version

### ISSUE THREAD

**Issue by xixixao** [facebook/react-native#11818]
I can't find it anywhere in docs or repo, you can infer it from the iOS version but it would be better to document in [Get Started](https://facebook.github.io/react-native/docs/getting-started.html#xcode) or [Troubleshooting](https://facebook.github.io/react-native/docs/troubleshooting.html#troubleshooting). Even if the recommendation is "latest".

**Comment by ide** [comment]
This is a good idea, anyone want to send a PR? We've supported the latest releases of macOS and Xcode (non-beta, non-RC) and drop old versions somewhat quickly and could just write that in the docs.
