### ISSUE TITLE
Same display size, same display density, different Dimensions

### ISSUE THREAD

**Issue by ethanguy** [facebook/react-native#11814]
I have been developing my app on the iPhone 6 Plus **simulator** first, and then i installed it on my Meizu MX5 (actual device).

Both have a 5.5 inches display, with a 1920x1080 resolution, 401 DPI,  and a PixelRatio (scale) of 3. Basically, it's the same display. 

Yet, when i run Dimension.get("window") the iPhone 6 Plus simulator returns {width: 414, height 736}, while the Meizu MX5 returns {width: 360, height: 640}. This also results in everything looking **a lot** "zoomed" on my device. What's happening?

**Comment by ikalafat** [comment]
I'll quote this (source: http://stackoverflow.com/questions/25755443/iphone-6-plus-resolution-confusion-xcode-or-apples-website-for-development): 

```
Real/physical iPhone 6 Plus resolution is 1920x1080 but in Xcode you make your interface for 2208x1242 resolution (736x414 points) and on device it is automatically scaled down to 1920x1080 pixels.
``` 

Your Meizu device doesn't do additional downscaling, and that is where difference comes from.

**Comment by ethan37** [comment]
@ikalafat So basically if I run Dimensions.get("window") on an actual iPhone 6 Plus physical device it will return the same value as my Meizu device?

**Comment by ikalafat** [comment]
No, I think that you will receive same results with Iphone 6 Plus as you get in simulator (that's the point of simulator, to simulate real device, right? :) ). 

As workaround for zoomed images, you can have some base/fixed image dimensions (for example for Iphone 6), and then rescale their width/height according to screen size.

See how we're doing it in UI toolkit: https://github.com/shoutem/ui/blob/develop/theme.js#L244

**Comment by ethan37** [comment]
@ikalafat Thanks for the advice, but what about UI elements and text size?

**Comment by ikalafat** [comment]
I guess that you could use same approach? Fixed size of element for some base resolution and rescale it according to actual dimensions?

**Comment by ethan37** [comment]
I think this approach is going to be a problem if we want images to have the real-life fixed same dimensions on all screen sizes. 
If I understand correctly, the problem here are devices who make use of virtual resolution. Do you know if this is something that only the iPhone 6 Plus does or it's something that Android devices do too? 
Because if only a few known devices do that we could force the right Dimensions though Dimensions.set()

**Comment by ikalafat** [comment]
Sorry, I'm unaware if some Android devices are doing this kind of resolution scaling :/

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
