### ISSUE TITLE
Removing items with LayoutAnimation causes adjacent views/texts to disappear on Android

### ISSUE THREAD

**Issue by vinceyuan** [facebook/react-native#11828]
### Description

When remove items with LayoutAnimation, the adjacent views/texts should not be impacted. But they disappear on Android.

In the following screenshot of the sample app, we can see some texts/buttons disappeared when we press `Remove with opacity animation` button and `Remove with scaleXY animation` button. I found this issue when I worked on #11769.

![Screenshot](https://github.com/vinceyuan/ReactNativeOpacityBugDemo/raw/master/ReactNativeOpacityBug3.gif)

### Reproduction

Reproduced on rnplay.org https://rnplay.org/apps/JbdOpQ
The sample project I created: https://github.com/vinceyuan/ReactNativeOpacityBugDemo

### Solution

N/A

Update on Jan 18, 2017:
I figured out a solution. See below.

### Additional Information

* React Native version: 0.33+
* Platform: Android
* Operating System: MacOS

**Comment by vinceyuan** [comment]
### Cause

When LayoutAnimation is enabled, indices of to-be-removed items are incorrect (to reproduce it, we need to delete at least two items). So the adjacent items are removed. In https://github.com/facebook/react-native/blob/0.41-stable/ReactAndroid/src/main/java/com/facebook/react/uimanager/NativeViewHierarchyManager.java#L364-L373 because `indexToRemove` is wrong, we get wrong `viewToRemove`. `arrayContains(tagsToDelete, viewToRemove.getId())` returns `false`. That view is removed immediately in`viewManager.removeViewAt(viewToManage, indexToRemove);`.

### Essential Cause
The essential cause is in [https://github.com/facebook/react-native/blob/0.41-stable/ReactAndroid/src/main/java/com/facebook/react/uimanager/NativeViewHierarchyOptimizer.java#L278-L285](https://github.com/facebook/react-native/blob/0.41-stable/ReactAndroid/src/main/java/com/facebook/react/uimanager/NativeViewHierarchyOptimizer.java#L278-L285). It gets the index of a `ReactShadowNode` and adds a managing children operation into a queue.

Says we want to delete 2 items `i0` and `i2`  from `[i0, i1, i2, i3]`. It creates two operations `op0` and `op1`. `op0` is created with index `0` for deleting `i0`, and `op1` is created with index `1` for `i2`.  `op1`'s index is `1`, instead of `2`, because `ReactShadowNode` of `i0` has been deleted.

When LayoutAnimation is not enabled, `NativeViewHierarchyManager` gets the view by index and deletes it in the same sequence. There is no problem in deleting `i2` with index `1`.

But when LayoutAnimation is enabled, the problem happens in deleting `i2` with index `1`. Because the animation is running, `i0` still exists. `i2`'s index is `2`, instead of `1`. So wrong item is deleted. [See **Note** below]

### Solution
Skip deleting items by index when LayoutAnimation is enabled. These items will be deleted by correct `tagsToDelete`

It's hard to correct index at [https://github.com/facebook/react-native/blob/0.41-stable/ReactAndroid/src/main/java/com/facebook/react/uimanager/NativeViewHierarchyOptimizer.java#L278-L285](https://github.com/facebook/react-native/blob/0.41-stable/ReactAndroid/src/main/java/com/facebook/react/uimanager/NativeViewHierarchyOptimizer.java#L278-L285), because we don't know if we are using LayoutAnimation.

**Note**
Actually it tries to skip deleting in the existing code. But because the index is wrong, `arrayContains(tagsToDelete, viewToRemove.getId())` is always `false`. `viewManager.removeViewAt(viewToManage, indexToRemove);` is always executed.
```
if (mLayoutAnimationEnabled &&
    mLayoutAnimator.shouldAnimateLayout(viewToRemove) &&
    arrayContains(tagsToDelete, viewToRemove.getId())) {
  // The view will be removed and dropped by the 'delete' layout animation
  // instead, so do nothing
} else {
  viewManager.removeViewAt(viewToManage, indexToRemove);
}
```

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/removing-items-with-layoutanimation-causes-adjacent-viewstexts-to-disappear-on-a
