### ISSUE TITLE
resizeMode `cover` doesn't scale up images

### ISSUE THREAD

**Issue by israelidanny** [facebook/react-native#11820]
### Description

resizeMode `cover` is supposed to make the image width and/or height the same size or bigger than the containing view so that the image fully covers the area of the view. 

Currently that only happens if the image is too big. A small image is not being rescaled properly.

### Reproduction

Testing was done with network images.

Suppose we're trying to display a 200x200 image to cover a 250x250 View. The current logic would only scale the image *down* if necessary, and since in that case it isn't - it would end up causing the image to have white borders.

### Solution

Scale image up if resizeMode is `cover` and image is smaller than the View size we're trying to fill.

### Additional Information

* React Native version: 0.39
* Platform: both ios & android

**Comment by ptmt** [comment]
@israelidanny Is there any particular reason why did you close it?

**Comment by israelidanny** [comment]
@ptmt after further testing, I found out that for some weird reason the images I was working with (straight out of Instagram API) had weird borders in them in certain cases. 

I looked at the code in`react-native` and in fact there is code that scales both up and down (the scaling is done based on ration).

So it seems the problem wasn't in `react-native` but rather in the images I was working with that came out of IG API
