### ISSUE TITLE
App crash when choose reload option

### ISSUE THREAD

**Issue by HarrisLee** [facebook/react-native#11827]
when i use react native in my app.   in fisrt  is ok. but  it crash when reload.    my server is ok.

this is log:
**2017-01-11 14:56:37.278 [info][tid:NSOperationQueue 0x610003e2f4e0 :: NSOperation 0x618001855360 (QOS: DEFAULT)][RCTPerformanceLogger.m:80] Unbalanced calls start/end for tag 0
2017-01-11 14:56:37.279 [warn][tid:NSOperationQueue 0x610003e2f4e0 :: NSOperation 0x618001855360 (QOS: DEFAULT)][RCTBatchedBridge.m:110] Failed to load source: Error Domain=RCTJavaScriptLoaderErrorDomain Code=3 "Could not connect to development server.

Ensure the following:
- Node server is running and available on the same network - run 'npm start' from react-native root
- Node server URL is correctly set in AppDelegate

URL: http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false" UserInfo={NSUnderlyingError=0x6000018490f0 {Error Domain=NSURLErrorDomain Code=-999 "(null)"}, NSLocalizedDescription=Could not connect to development server.

Ensure the following:
- Node server is running and available on the same network - run 'npm start' from react-native root
- Node server URL is correctly set in AppDelegate

URL: http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false, NSLocalizedFailureReason=The operation couldn’t be completed. (NSURLErrorDomain error -999.)}**

* React Native version: 0.40
* Platform: [FILL THIS OUT: iOS, 
* Operating System: MacOS, Xcode 8.2.1

**Comment by keith527** [comment]
I have the same problem , Have you solved it yet?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/app-crash-when-choose-reload-option
