### ISSUE TITLE
Custom Font for Alert head & Description & buttons

### ISSUE THREAD

**Issue by mrxrinc** [facebook/react-native#11833]
I want to set a font family to the TouchableHighlight and expected that to apply in the Alert content inside onPress of that, But Failed ! Guys is that a bug or requires another trick?

[FILL THIS OUT: Explain what you did, what you expected to happen, and what actually happens.]

### Reproduction

[FILL THIS OUT: Try to reproduce your bug on rnplay.org and provide a link. If you can't reproduce the bug on rnplay.org, provide a sample project.]

### Solution

[FILL THIS OUT: What needs to be done to address this issue? Ideally, provide a pull request with a fix.]

### Additional Information

* React Native version: 0.40
* Platform: both
* Operating System: windows

**Comment by antoxi4** [comment]
@mrxrinc For Android if you want use custom font family in Alert Dialog. You Need create another dialog. with AlertDialog.Builder. It is not React Native bug)

**Comment by mehdijjz** [comment]
@antoxi4 Can you show us how ? or point to a document ?
