### ISSUE TITLE
ScrollView in Android not scrolling to top when size is less than parent View

### ISSUE THREAD

**Issue by g3r4n** [facebook/react-native#11837]
### Description

When the height of the scrollView change from more than the parent to less than the parent, the scroll view is not scrolling to top or resizing. The component i have removed from scrollview leave a blank.
When we tap on the scrollview, the scrollview scroll to the top and the scrollview is disable
When we tap on the blank nothing happened. 

### Reproduction

Add components to make the scrollview bigger than the parent view.
Remove tome component to make the scrollview less thant the parent view.
The blank gap is visible, the scrollView do not scroll to top

### Solution

Works on IOS
scrollTo not working
forceUpdate not working

### Additional Information

* React Native version: 0.39.2
* Platform: Android
* Operating System: MacOS

**Comment by xiDaiDai** [comment]
update to the latest version ,https://github.com/facebook/react-native/commit/528a3c776a26c946a6582489c5e1ad234220dc3c

**Comment by g3r4n** [comment]
It's exactly the issue i'm facing.

**Comment by g3r4n** [comment]
@xiDaiDai thanks a lot !
