### ISSUE TITLE
Get invalid layout warning only when remote debugger is off, works fine when debugger is on

### ISSUE THREAD

**Issue by florianbepunkt** [facebook/react-native#11846]
### Description

I have a basic "faky" masonry layout. everything works fine as long as `debug JS remotely` is on. when I deactivate it I get a red error screen with an invalid layout error.

I would exspect consistent behaviour here… the layout itself looks and works as exspected when remote debugging is activated, so I suspect this is a bug.

### Reproduction

clone the full sample repo and start the app. on app start turn remote debugging on and off
https://github.com/florianbepunkt/Bischoff-Portfolio-App

### Solution

no idea.

### Additional Information

* React Native version: 0.39.0
* Platform: iOS  10.1 (iPhone 6 Simulator)
* Operating System: MacOS

**Comment by florianbepunkt** [comment]
same happens on RN 0.40.0

**Comment by amitverma** [comment]
I'm seeing the exact opposite behaviour. I get the invalid layout error only when remote debugging is switched on. RN 0.40.0

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/get-invalid-layout-warning-only-when-remote-debugger-is-off-works-fine-when-debu
