### ISSUE TITLE
[WebView] href calling javascript functions not working

### ISSUE THREAD

**Issue by jsieler** [facebook/react-native#11844]
### Description

We have internal company solution which is running over web. There are some links that call js code,
```<a id="showAuftrag" href='javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions("showAuftrag", "", true, "", "", false, true))' style="left:16px; position:absolute; font-family:Arial; font-size:12px; top:107px;">Auftrag:</a>```
Unfortunately nothing happens if i click such link. But this works in ordinary Google Chrome.

### Reproduction

Don't know how else I could get someone to reproduce it.

### Solution

Currently no solution found.

### Additional Information

* React Native version: 0.40
* Platform: Android 4.4.4 / Android 6.0.1
* Operating System: Windows 7

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
