### ISSUE TITLE
Async Stroage MergeItem callback always returns null

### ISSUE THREAD

**Issue by imbudhiraja** [facebook/react-native#11840]
Here is my code: -

AsyncStorage.setItem('UID123', JSON.stringify(UID123_object), () => {
  AsyncStorage.mergeItem('UID123', JSON.stringify(UID123_delta), () => {
    AsyncStorage.getItem('UID123', (err, result) => {
      console.log(result); // returns null;
    });
  });
});

* React Native version: 0.39 +
* React : 15.4
* Platform: iOS, Android
* Operating System: MacOS

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.

**Comment by hjJunior** [comment]
I'm getting the same problem here...
