### ISSUE TITLE
react-native-git-upgrade crashes

### ISSUE THREAD

**Issue by veddermatic** [facebook/react-native#11843]
### Description

Attempting to upgrade to fix app crashing instantly when running on device, so I installed and ran per these instructions: https://facebook.github.io/react-native/docs/upgrading.html

So I installed the utility: `$ npm install -g react-native-git-upgrade`
Then ran the command (from my project's root directory): `$ react-native-git-upgrade`

After an hour or so, it quit with an error
```
git-upgrade info Check for updates 
git-upgrade info Read package.json files 
git-upgrade info Check declared version 
git-upgrade info Check matching versions 
git-upgrade info Check React peer dependency 
git-upgrade info Check that Git is installed 
git-upgrade info Get information from NPM registry 
git-upgrade info Upgrading to React Native 0.40.0, React ~15.4.0-rc.4 
git-upgrade info Setup temporary working directory 
git-upgrade info Configure Git environment 
git-upgrade info Init Git repository 
git-upgrade info Add all files to commit 
git-upgrade info Commit current project sources 
git-upgrade info Commit current project sources 
git-upgrade ERR! An error occurred during upgrade: 
git-upgrade ERR! Error: Command 'git commit -m "Project snapshot"' exited with code null:
stderr: undefined
stdout: [master (root-commit) 82862fb] Project snapshot
 171276 files changed, 6902241 insertions(+)

[ lots of create mode lines snipped ]

    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/react-native-git-upgrade/cliEntry.js:58:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12) 
```

### Reproduction

Run `react-native-git-upgrade` on my machine. Don't know how else I could get someone to reproduce it. 

### Solution

Have it not explode.

### Additional Information

* React Native version: `react-native-cli: 1.2.0 react-native: 0.38.0`
* Platform: both / neither (not related to a specific app)
* Operating System: macOS Sierra

**Comment by uniquarkD** [comment]
It happened to me bcz of some peer dependencies of a package. After removing the package, it went smoothly. I'm not sure if it is the cause in your case, but it's worth to check your peer deps.

**Comment by grabbou** [comment]
Looks from your comment @uniquarkD that the issue was not directly related to the tooling itself. If I am wrong, please re-open.

**Comment by veddermatic** [comment]
@grabbou : @uniquarkD isn't the guy who reported the issue, I was, and it's still happening, so I'm reoppening.

**Comment by ncuillery** [comment]
> 171276 files changed, 6902241 insertions(+)

@veddermatic 😱  that's huge, try adding a `.gitignore` containing `node_modules` in your project directory.
