### ISSUE TITLE
Import React Native To Android Studio

### ISSUE THREAD

**Issue by putraxor** [facebook/react-native#11845]
I have a problem with importing React-Native project into Android Studio.
Android Studio won't open React-Native project because it isn't gradle project, if I import **./android** folder it is impossible to make changes since the codes is outside "android" folder.
I can make change to react native code with another editor such as Sublime, but it's not ideal as I have to switch from Android Studio to Sublime.

**Comment by srhise** [comment]
That's just the way the cookie crumbles with RN. My only qualm with Android Studio is I am not sure I can produce a release build using *only* Android Studio (like I can with XCode using a release scheme).  

One of the great things about using RN with android studio is you can debug your native Android components there. Highly recommend using AS with RN.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/import-react-native-to-android-studio
