### ISSUE TITLE
Infinite loop in WebView crashes app

### ISSUE THREAD

**Issue by dannycochran** [facebook/react-native#11852]
### Description / Reproduction

If you create a WebView that loads entirely local assets (e.g. HTML, JavaScript), and if it contains an infinite loop, the app will crash once the JavaScript executes. Unmounting the component after some time passes (under the presumption the WebView is caught in an infinite loop) does not work, the app will still crash.

The obvious way to avoid this is not have infinite loops -- but in this use case I am trying to execute arbitrary user code using `eval`, so I can't easily prevent the creation of infinite loops.

### Solution

Maybe the WebView API should expose a "terminate" or "stop" function, and then a user can do something like this:

```javascript
onReceiveWebViewMessage(event) {
  this.clearTimeout(this.timeout);
}

sendMessage() {
  this.timeout = setTimeout(() => {
    this.webview.terminate();
  }, 2000);
  this.webview.postMessage(`{ command: 'executeInfiniteLoop' }`);
}
```

### Additional Information

* React Native version: 0.40.0
* Platform: Android
* Operating System: MacOS

@jacobp100 -- thoughts?

**Comment by jacobp100** [comment]
Could you upload an example or repo that demonstrates this? I'll look into it then!

**Comment by dannycochran** [comment]
@jacobp100 thanks for the reply!

rnplay only supports up to 0.33 so it doesn't have your postMessage change. Here is a repo that reproduces the issue:

https://github.com/dannycochran/webViewCrash

Note that the app won't necessarily crash immediately in this case, but the app becomes unusable after clicking the button once (subsequent clicks to the button will not work). I suspect with larger apps (like mine) it crashes faster.

**Comment by jacobp100** [comment]
Thanks! I’ll look into this ASAP!

Just quickly, did you try this on iOS, and if so, did it fail too?

**Comment by dannycochran** [comment]
Haven't tested on iOS but the example code is in index.ios.js.

**Comment by jacobp100** [comment]
I’m having trouble reproducing this in the emulator. Could I get more information about your setup?

**Comment by dannycochran** [comment]
Hmm that's strange. I'm running a Nexus 5 emulator on API23 for Android.

For the sandbox I provided, I can't get the app to crash, but the UI interactivity slows down to a point where it is unusable. It may be that in my larger app, there are memory issues that cause the app to crash.

**Comment by jacobp100** [comment]
If you or anybody can reproduce it and wants to look into this, PRs are always welcome! I suspect it’s running the JS on the main thread, and causing a crash. The implementation is in [ReactWebViewManager.java](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/webview/ReactWebViewManager.java).

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
