### ISSUE TITLE
React Native Webview not loading on certain devices

### ISSUE THREAD

**Issue by seque1990** [facebook/react-native#11857]
On our app we are using a Webview Component to display some information that is in our website, this is working as intended for most cases, however we have been told by a couple of users that the Webview never loads on their devices. I would like to know the reason for this weird behavior on the React Native Webview.

We have been reported that it doesn't work on

- Huawei Ascend
- Acer Liquid

Thank you very much for any information on this problem.

**Comment by vivekguptaraw** [comment]
I am also having this issue on iphone

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/react-native-webview-not-loading-on-certain-devices
