### ISSUE TITLE
Android xhr.upload.onprogress and addEventListener('progress') not supported?

### ISSUE THREAD

**Issue by dguillamot** [facebook/react-native#11853]
### Description

We are doing XMLHttpRequest PUT request (sending base64 encoded image data, setting content type header, etc).

iOS sends progress updates, Android does not. 

We tried setting progress listener the following ways:

xhr.addEventListener('progress')
xhr.upload.addEventListener('progress')
xhr.upload.onprogress = () => {}
xhr.onprogress = () => {}

None of these handlers end up being called on Android, however on iOS they work fine. 

The request completes successfully with a 200. 

### Additional Information

* React Native version: 0.39.2
* Platform: both Android and iOS tested (issue only on Android)
* Operating System: MacOS

**Comment by dguillamot** [comment]
Ended up moving to a native (Obj-c and Java) solution for now which does provide upload progress events on Android. 

Regarding XmlHttpRequest, not sure if the Android interface is different from iOS or not but no luck with XmlHttpRequest updateProgress on Android.

**Comment by christopherdro** [comment]
@dguillamot Looks like there is some sort of API for progress on android.
https://github.com/facebook/react-native/blob/e87e181998bf4f8efba2c7e04bec0929344600b9/ReactAndroid/src/main/java/com/facebook/react/modules/network/NetworkingModule.java#L190

**Comment by dguillamot** [comment]
@christopherdro Yes, I did see that last week but xhr.upload.addEventListener('progress')  did not result in any updates on Android - only iOS. For now, we have solved it with a Native solution, thanks though.

**Comment by bogobogo** [comment]
Hey @dguillamot, would you mind sharing your solution? I am facing the same problem, and I currently don't have the knowledge to implement it natively (learning java but that will take me some time...).

**Comment by GeoffreyPlitt** [comment]
I'm on RN=0.42 and using XHR with a Content-Length set before uploading begins. I'm seeing the progress events, but no bytesSent or length or anything else that I can use to compute a progress%. Anybody else have luck with this?

**Comment by GeoffreyPlitt** [comment]
I'm on RN=0.42 and using XHR with a Content-Length set before uploading begins. I'm seeing the progress events, but no bytesSent or length or anything else that I can use to compute a progress%. Anybody else have luck with this?

**Comment by ranjitpandit** [comment]
Any ideas how to get send progress events on Android with bytesSent?

**Comment by aguzubiaga** [comment]
@christopherdro Why is this issue closed? This problem persists.

**Comment by 1stman** [comment]
i trying to upload video with youtube v3 api, and have some dilemma. When i use `FormData` , `xhr.upload.onprogress` is working. But then youtube api return processing error, because `FormData` add some data to file object.  So, i use something like `xhr.send({uri: url});` and it works, video is uploading, BUT `xhr.upload.onprogress` stopped working. I still don't know why... 
P.S. sorry for my ugly english
