### ISSUE TITLE
JS Engine crashes on startup

### ISSUE THREAD

**Issue by phou87** [facebook/react-native#11855]
### Description

Just created a new React Native project, built it in Xcode and ran it.  I get a red screen (see the screenshot):

<img width="372" alt="screen shot 2017-01-11 at 9 15 27 pm" src="https://cloud.githubusercontent.com/assets/5732593/21874483/1d3de7dc-d843-11e6-8a48-710bc963c015.png">

I was using a pretty old version of React Native before this (0.33) and never had any issues there.  I just upgraded to 0.40.0 today and haven't been able to get a clean project working.

### Reproduction

Ran react-native init x
Built the project in Xcode.

### Solution

The error is too generic for me to figure out what's going on.

### Additional Information

* React Native version: 0.40.0
* Platform: iOS
* Operating System: MacOS

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
