### ISSUE TITLE
release apk without JS minification 

### ISSUE THREAD

**Issue by aamarcha** [facebook/react-native#11866]
### Description

I'm not able to release my apk with without JS minification.  
### Reproduction
```
react-native bundle --entry-file ./index.android.js --platform android --bundle-output android/app/src/main/assets/index.android.bundle
```

```
cd android
./gradlew  assembleRelease
```

```
cd app/build/outputs/apk

jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore my-release-key.keystore app-release-unsigned.apk alias_name
```

### Additional Information

* React Native version: '0.38.1'
* Platform: Android
* Operating System: MacOS

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.

**Comment by mleduque** [comment]
It's closed so I suppose there is an answer somewhere... @hramos : Could you point me to its please ?
