### ISSUE TITLE
TestIDs swallowed when children of TouchableWithoutFeedback

### ISSUE THREAD

**Issue by kidmillions** [facebook/react-native#11869]
### Description

In automating testing for our mobile app we've come across various issues in using testIDs as props for Text and View components, and in many cases the accessibilityID is not appearing on elements in iOS for use by XCUITest or Appium.

We are seeing this consistently with 1st or 3rd-party React components with TouchableWithoutFeedback included. Child `<View />`s with testID props haven't made their way to ids in the native app, and are therefore not findable by Appium.

I can see that most touchable components set accessibility by `accessible: this.props.accessible !== false` and the same is the case for TouchableWithoutFeedback [as changed in this PR](https://github.com/facebook/react-native/pull/6561)

However I do see that [TouchableWithoutFeedback](https://github.com/facebook/react-native/blob/master/Libraries/Components/Touchable/TouchableWithoutFeedback.js)'s render method quite different that other touchables. I'm wondering if there is anything in this method which would cause testID prop to get wiped out in the child View component.

### Reproduction

nest `<View />` with testID prop in `<TouchableWithoutFeedback /> `

### Additional Information

* React Native version: 0.38.0
* Platform: iOS
* Operating System: MacOS

**Comment by kidmillions** [comment]
Closing for now as the issue for us may be that we do not explicitly set `accessibility={false}` on the TouchableWithoutFeedback component

**Comment by kidmillions** [comment]
Reopening, as I'm not seeing consistent id selection:

```
<TouchableWithoutFeedback accessible={false}>
  <View testId='foo'></View>
</TouchableWithoutFeedback>

```

In this case the accessibilityID 'foo' cannot be found.

**Comment by deecewan** [comment]
@kidmillions why was this closed again? As far as I can tell, this is still not fixed.
