### ISSUE TITLE
How to Hide TabbarIOS on sub pages?

### ISSUE THREAD

**Issue by AmusedMe** [facebook/react-native#11860]
I used TabbarIOS , there is a listview, after tapped the listitem, turned to detail page, but the tabbarios still on the bottom, how to fixed? btw, pass props?

**Comment by rocwangv** [comment]
When you call the `push` method of the navigator , the child page will hide the tabbar .

**Comment by ericvicenti** [comment]
What navigation solution are you using? Have you tried using component state to selectively render the tab bar?

Im closing this because there is nothing to go on without more details and example code
