### ISSUE TITLE
Bug in RCTRootView initialization logic

### ISSUE THREAD

**Issue by LeoNatan** [facebook/react-native#11871]
I have found a bug in RCTRootView initialization logic, which we hit in a use case for [wix/react-native-navigation](https://github.com/wix/react-native-navigation).

When a root view is initialized, it checks if the bridge is still loading; [if not, it calls `bundleFinishedLoading:` directly](https://github.com/facebook/react-native/blob/47f18bdb175af5f76228b86b552e7bbe77db3667/React/Base/RCTRootView.m#L108). However, it also **always** adds itself as an observer for `RCTJavaScriptDidLoadNotification`, [in whose handler method it also calls `bundleFinishedLoading:`](https://github.com/facebook/react-native/blob/47f18bdb175af5f76228b86b552e7bbe77db3667/React/Base/RCTRootView.m#L239). 

However it seems that the `loading` property of the bridge and `RCTJavaScriptDidLoadNotification` are not synchronized, and there is a gap between `loading` being set to `NO` and `RCTJavaScriptDidLoadNotification` firing. Whether this is a bug or not, I leave to you to decide. However, `RCTRootView` behaves incorrectly in the current condition; there exists a code path that can cause a nasty crash with the following error: 

> Expect all root views to have unique tag. Added 1 twice

From [here](https://github.com/facebook/react-native/blob/f839b58c200ce25abfcbc8b2c57b3012f4de14c3/React/Modules/RCTUIManager.m#L388).

If a new `RCTRootView` is created between some time after the bridge has starting loading and `RCTJavaScriptDidLoadNotification` has been dispatched for that bridge, the logic bug in `RCTRootView` causes `-[RCTUIManager registerRootView:withSizeFlexibility:]` to be called twice with the same root view, cause the aforementioned crash.

A simple fix is to remove the root view as observer to `RCTJavaScriptDidLoadNotification` in case `_bridge.loading` returns `NO`. However, it might be worth investigating whether `loading` and `RCTJavaScriptDidLoadNotification` should not be properly synchronized.

**Comment by LeoNatan** [comment]
CC @javache @nicklockwood

**Comment by littlesome** [comment]
same issue, maybe related with [this commit](https://github.com/facebook/react-native/commit/2ae23d9f36ca7140448fc9cafda3fef281cf5b3c)

**Comment by khzliu** [comment]
same issue with v0.42.3

**Comment by LeoNatan** [comment]
CC @majak

**Comment by shergin** [comment]
@javache Do you have any idea?

**Comment by javache** [comment]
I believe I've done some investigation into this before. Since the bridge actually allows you to queue messages as soon as `RCTBridge` exists, we can probably enqueue the render call immediately instead of waiting for the bridge to load.

**Comment by shergin** [comment]
Just for reference: D4849610.

**Comment by javache** [comment]
Please checkout https://github.com/facebook/react-native/commit/59378f71dbc059bb6d8eb75cf86148012a20ba09 and see if that resolves the issue for you. Thanks!

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/bug-in-rctrootview-initialization-logic
