### ISSUE TITLE
[Android] Modal windows have a gap at the bottom when the status bar is not visible

### ISSUE THREAD

**Issue by rgngl** [facebook/react-native#11872]
### Description

If the status bar is hidden, contents of the modal leave a gap at the bottom with the same size as the status bar would be.

Here are some screen shots:
- Main screen before modal is shown:
![image](https://cloud.githubusercontent.com/assets/169434/21910432/a8e79274-d924-11e6-8b51-b9a85d04cc75.png)
- After the modal is shown:
![image](https://cloud.githubusercontent.com/assets/169434/21910450/c1bdcb88-d924-11e6-89b0-da5dedcf7fb8.png)

- Here's a sample dump from the Android Studio layout inspector:
It's visible that the first `ReactViewGroup` inside the modal's `DialogRootViewGroup` is incorrectly sized.
![image](https://cloud.githubusercontent.com/assets/169434/21910503/fa4a5d36-d924-11e6-8fac-3b1fd1f5df14.png)

### Reproduction

Launch a `Modal` in an app in fullscreen mode with no status bar visible.

### Additional Information

* React Native version: 0.40.0
* Platform: Android
* Operating System: MacOS

**Comment by gezichenshan** [comment]
I am experiencing this issue too.

I add android:windowFullscreen = true in the styles.xml.
`<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        
         <item name="android:windowFullscreen">true</item>
        <item name="android:windowBackground">@drawable/launch_screen</item>
    </style>`

Then,when I call a modal showing, there is a gap in the bottom.

**Comment by rgngl** [comment]
I had a PR for this but it wasn't considered a real issue by the maintainer.

**Comment by freedomdouble** [comment]
same issue how to fixed ? please...

**Comment by Traviskn** [comment]
Looks like @rgngl's PR got merged, so this should be fixed in newer versions!

**Comment by mini-eggs** [comment]
This is an issue for me on react-native 0.43.4.

Note: this only happens on when the modals `transparent` value is set to `false` i.e. `<Modal visible={true} transparent={true} >` does not have this issue.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/android-modal-windows-have-a-gap-at-the-bottom-when-the-status-bar-is-not-visibl

**Comment by RobertSheaO** [comment]
This is an even bigger issue on the Samsung Galaxy Note 8, the gap at the bottom is about 100px tall.

Using RN 0.47.1 with React-Navigation 1.0.0-beta.15 and TabBarBottom enabled. The gap is the exact height of the TabBarBottom, leaving it visible. I suspect it could be some odd interaction with the two libraries

**Comment by rgngl** [comment]
I had already made a fix for the gap with the size of the status bar, it got merged at some point and it worked okay, but wasn't the proper solution. Later on, I found a better solution, made a PR but didn't attract much attention. I don't have a Note 8 lying around but maybe you can build react native from source with this changes applied and tell if it works for your case: https://github.com/facebook/react-native/pull/13411

**Comment by RobertSheaO** [comment]
I’ll try that tomorrow and report back on the original pull request

**Comment by JaredSartin** [comment]
Any progress?

**Comment by RobertSheaO** [comment]
I just implemented @rgngl's changes and it works! I'm going to post in #13411 in hopes of having that resurrected so we can get it merged in.

**Comment by ejkkan** [comment]
Also seeing this issue! Please merge the fix!

**Comment by cuilongzhe** [comment]
@rgngl any update on this PR? I want to have this fixed asap
