### ISSUE TITLE
runApplication method in AppRegistry uses a JSON.stringify and prints out a console log in production mode

### ISSUE THREAD

**Issue by varungupta85** [facebook/react-native#11873]
### Description

I am observing a few console logs in the sentry logs for my app. I am using a package called `react-native-navigation` which handles the navigation in a different way. Each screen is an application and each modal is also an application. Currently, the `runApplication` method in `AppRegistry` logs out a message whenever a new application is run and used `JSON.stringify` to serialize the `appParams`. In some cases, the `appParams` can contain a lot of data and it would take some time to serialize the data to print the console log. The log is printed in both development and production mode. I think there should be a way to disable the log complete in production mode or at least not print out the `appParams` in production mode.

This message is also used in a module called `BugReporting` which I guess is used internally within the library.

If it is okay to print out the log in just dev mode or at least not print out the `appParams` in production mode, I can send a PR.

### Solution

Don't log the message in production mode or at least don't log the appParams in production mode

### Additional Information

* React Native version: 0.37
* Platform: [FILL THIS OUT: iOS, Android, or both?] Both
* Operating System: [FILL THIS OUT: MacOS, Linux, or Windows?] MacOS

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
