### ISSUE TITLE
Weird behavior with NavigatorIOS state updates

### ISSUE THREAD

**Issue by opolyo01** [facebook/react-native#1187]
I am trying to load the locations data from AsyncStorage on componentDidMount for the component of NavigatorIOS, but it keeps showing the initial state empty response.  The data appears if I would push another View on the Stack, and then replace it.  Since, I am replacing instead of popping the View, it still keeps the old back button and title.

Here's the link to complete code -- https://github.com/opolyo01/locationTracker

I noticed there are similar issues were not answered on stackoverflow -- http://stackoverflow.com/questions/29622092/react-native-pass-data-between-sibling-views

Key snippets bellow:

```
componentDidMount(){
    AsyncStorage.getItem('listings')
      .then((value) => {
        this.state.listings = JSON.parse(value);
        this.state.passProps = {listings: this.state.listings};
        this.redrawListings(true);
      })
      .done();
  }

redrawListings(startWatch){
    //AlertIOS.alert('listings '+ this.state.listings.length);
    //this.refs.nav.pop();
    this.refs.nav.replace(this.state);
    if(startWatch){
      this.startWatch();
    }
  }

render() {
    return (
      <NavigatorIOS
        style={styles.container}
        ref="nav"
        initialRoute={this.state}/>
    );
  }
```

**Comment by opolyo01** [comment]
Adding componentWillReceiveProps method into Listings view controller made it update the view, and things now more logical.  I guess NavigatorIOS+ListView need a combination of componentWillReceiveProps and replace invocation.
 
```
componentWillReceiveProps(nextProps){
    this.state = {dataSource: this.state.dataSource.cloneWithRows(nextProps.listings)};
  }
```

**Comment by Iliker** [comment]
@opolyo01 but, componentWillReceiveProps looks like it will not cause the second rendering
