### ISSUE TITLE
packager crashed while cd android/ && gradlew assembleDebug

### ISSUE THREAD

**Issue by jianglinchun** [facebook/react-native#11874]
I had found that once I'm keeping packager running. Such as
start "packager" /MIN /D E:\react-native\travel\Tourist react-native start --port 8081

And the packager will crashed immediately when I run:
cd android && gradlew assembleDebug

It seems that the packager are monitoring the dex files. I just don't get the point.  For the Native Module???

 ERROR  EPERM: operation not permitted, lstat 'E:\react-native\travel\Tourist\android\app\build\intermediates\dex\debug\classes.dex'
{"errno":-4048,"code":"EPERM","syscall":"lstat","path":"E:\\react-native\\travel\\Tourist\\android\\app\\build\\intermediates\\dex\\debug\\classes.dex"}
Error: EPERM: operation not permitted, lstat 'E:\react-native\travel\Tourist\android\app\build\intermediates\dex\debug\classes.dex'
    at Error (native)

So it's possible to avoid packager crashes while run gradlew assembleDebug ???

**Comment by christopherdro** [comment]
I am unable to reproduce. Are you running on windows?

**Comment by jianglinchun** [comment]
Yes, windows.

**Comment by jianglinchun** [comment]
……
Executing task ':app:bundleReleaseJsAndAssets' (up-to-date check took 4 mins 45.888 secs) due to:
  Output file E:\react-native\travel\TourGuide\android\app\build\intermediates\res\merged\release has changed.
  Output file E:\react-native\travel\TourGuide\android\app\build\intermediates\assets\release has changed.
……

It seems that bundleReleaseJsAndAssets are monitoring android build outputs. I think this is a bad idea.

**Comment by jrodiger** [comment]
![bug](https://cloud.githubusercontent.com/assets/17132071/25364442/802dfa9c-2930-11e7-8414-f967544f8de5.PNG)
I was unable to reproduce this bug on Windows 10 with React Native 0.43.3

**Comment by jianglinchun** [comment]
The problem had resolved. I had tested under 0.42.3. Thank you so much. 👍
