### ISSUE TITLE
Component is mounted but I can't call this.setState(...) or this.forceUpdate(...);

### ISSUE THREAD

**Issue by AdrianZghibarta** [facebook/react-native#11883]
I am using [scrollable tab view](https://github.com/skv-headless/react-native-scrollable-tab-view) and facebook official flux solution. There are cases when a scene remains inactive (is not current selected tab) and receive an event from the store that need to update the scene, but I have this error :
`Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. `

I've double checked, and `componentWillUnmount()` is not being called .. but I receive this warning and I can't more update the state of component.

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
