### ISSUE TITLE
Unable to resolve module error after importing Axios

### ISSUE THREAD

**Issue by jussisaurio** [facebook/react-native#11887]
I am posting this, because https://github.com/facebook/react-native/issues/11498 was closed, but the bug still persists and the workaround does not permanently fix the problem. Check details from over there, exact same situation. Can't import any new modules.

**Comment by agarcia17** [comment]
+1

**Comment by boyney123** [comment]
+1

**Comment by GantMan** [comment]
https://github.com/facebook/react-native/issues/11498#issuecomment-273972902

**Comment by Thibaut-Fatus** [comment]
This fix might work for this particular packages, but we cannot import any new added module

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/unable-to-resolve-module-error-after-importing-axios
