### ISSUE TITLE
RNG

### ISSUE THREAD

**Issue by mvayngrib** [facebook/react-native#1189]
browserified packages attempt to use window.crypto, which doesn't exist https://github.com/mjohnston/react-native-webpack-server/issues/18#issuecomment-99867249

**Comment by mvayngrib** [comment]
is crypto.getRandomValues even possible given RCTBridge is asynchronous?

**Comment by ide** [comment]
The native side could generate entropy up front and send it to JS in advance but apps that don't use crypto would then always be paying that cost. Async crypto API or synchronous bridge are probably the answer.

**Comment by spicyj** [comment]
I'd be surprised if that would be a significant cost but I am also not a security or performance expert and you shouldn't listen to anything I say.

**Comment by ide** [comment]
For one module it'd be pretty cheap -- I'm more wary of the general pattern of doing potentially unnecessary work up front to work around the async bridge.

**Comment by nicklockwood** [comment]
Our normal solution would be to put the crypto module in a standalone lib so you don't need to include it unless you intend to use it. That way, paying the upfront cost is less of a concern.

**Comment by mvayngrib** [comment]
@nicklockwood sounds good, is there some example of a lib with a synchronous bridge?

**Comment by nicklockwood** [comment]
@mvayngrib it's not possible to create a synchronous bridge, but as @ide suggests, you can create the entropy up front in the native module's constructor and then send the data to JS via the constantsToExport method, so that it's available immediately as a property on the JS module instead of requiring an async callback to retrieve it.

**Comment by mvayngrib** [comment]
@nicklockwood, @ide that sounds like a good temporary compromise to achieve synchronous access to randoms, but I feel like it'll end up a security vulnerability. I'm not a security expert, just being paranoid. I guess async is the way to go in the long run.

**Comment by spicyj** [comment]
It's virtually impossible to write secure code if you can't trust your environment, but if all the JS (and native) code is trusted and you're trying to secure against eavesdroppers, I think it would be fine.

**Comment by brentvatne** [comment]
@mvayngrib - thanks for the interesting discussion! if you ended up creating a native module for this, please do share :smile:
