### ISSUE TITLE
React Native Navigation Experimental Tab Switch Unmount/WillMount

### ISSUE THREAD

**Issue by zachrnolan** [facebook/react-native#11890]
### Description

Our React Native app uses Navigation Experimental NavigationCardStack. On switch tab (NavigationStateUtils.jumpToIndex), the scenes in the tab I switch from, unmount. When I switch back to the original tab, the same scenes mount again causing some slowness in the app.

### Reproduction

We've created an example GitHub repo here: https://github.com/zachrnolan/RN-NavigationExperimental-Redux-Example/tree/tabs

### Solution

Is this behavior part of Navigation Experimental or a side-effect of our navigation implementation? It doesn't seem correct that a tab switch would unmount all of the views in that tab. 

### Additional Information

* React Native version: 0.39.0
* Platform: both
* Operating System: MacOS

**Comment by JLLLinn** [comment]
I am experiencing this too. Can Someone take a look?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/react-native-navigation-experimental-tab-switch-unmountwillmount
