### ISSUE TITLE
React Native Navigator didfocus event listener

### ISSUE THREAD

**Issue by mjabado** [facebook/react-native#11905]
I am having a very weird issue with react native navigator (React Native 0.37.0) and i apologize in advance for the long post, I've been trying so hard for the last 12 hours and no solution yet.
I have a `ScrollableTabView` using `react-native-scrollable-tab-view` that has multiple navigators.
```
<ScrollableTabView>
     <Navigator>
     <Navigator>
     <Navigator>
</ScrollableTabView>
```
On some scenes of a specific navigator (Say the first navigator), i want to hide the bottom navigation.
I tried using the `onFocus `event for navigator to get the current scene details, turned out it was deprecated (Although it works fine on xCode and Android simulators but it doesn't work when i release the app.)

My second attempt was to attach the `didfocus `event listener on the parent stack `componentDidMount `like below:
`this.refs.stackNavigator.navigationContext.addListener('didfocus',(event) => { // Some code here calling an action });`

But also didn't work as i found somewhere someone was saying that attaching the listener should be before rendering the navigator and suggested attaching the listener to the `renderScene `function of the navigator. (Also, all works fine on simulators, but not on released apps.)

My third attempt was to actually do that using the `renderScene `method and also same result as the above two attempts, all works fine on simulators but in release, nothing works. (Also, all works fine on simulators, but not on released apps.)

Any help or if anyone encountered such behavior, i would highly appreciate his feedback as I've been wrapping my head about it for the last 24 hours.

**Comment by hramos** [comment]
Navigator has been deprecated in favor of the [`react-navigation`](https://reactnavigation.org) library.
