### ISSUE TITLE
[TextInput] How to show "Done" button above "number-pad" keyboard?

### ISSUE THREAD

**Issue by ranyefet** [facebook/react-native#1190]
Hello,

I'm trying to implement the following screen:
![2 2_verification_openkeypad_small](https://cloud.githubusercontent.com/assets/1016375/7520819/480eeec4-f4f2-11e4-8513-67b7cc99500e.jpg)

How can I get the bar above the keyboard to show up with "Done" button?
```js
<TextInput
                style={styles.codeInput}
                placeholder="Enter Code"
                value={this.state.pinCode}
                keyboardType="number-pad"
                onChangeText={(code) => this.setState({pinCode: code})}
              />
```

**Comment by ide** [comment]
You want what's called the input accessory but it's not yet built yet.

**Comment by ranyefet** [comment]
@brentvatne @ide Thanks for the comments. 
The reason why I wanted the "Done" button is because in the iOS Simulator I wasn't able to close the keypad by clicking anywhere on the screen. The only way to close the keypad was to hit Return on my mac keyboard.
I haven't tested it yet on a real device, so I'm not sure what will happen there. 

Do you know If this is a bug with the simulator, or do I need to implement this functionality with code?

**Comment by ide** [comment]
You should implement/configure it in code. The keyboard is very manual on iOS. ScrollView has some prop that lets you auto-dismiss the keyboard that you might want to look into.

**Comment by iostalk** [comment]
Watch

**Comment by auser** [comment]
I'm working on adding the `inputAccessoryView` on IOS. I'll update this issue when I have a PR.

**Comment by brentvatne** [comment]
Let's collapse this issue into #371

**Comment by henrikra** [comment]
@auser Are you still working on `inputAccessoryView`?

**Comment by gwendall** [comment]
+1

**Comment by kelset** [comment]
+1

**Comment by stief510** [comment]
+1

**Comment by kelset** [comment]
As a temporary workaround I found this lib which works pretty well, but forces you to have the separated files for the components where using it: https://github.com/DickyT/react-native-textinput-utils

**Comment by MiLeung** [comment]
I just made a keyboard dismissing component for number keyboard on iOS called [DoneBar](https://github.com/MiLeung/done-bar) if anyone wants to give it a try.

**Comment by Burak07** [comment]
+1 still looking forward

**Comment by MobiusHorizons** [comment]
+1

**Comment by filipemonteiroth** [comment]
+1

**Comment by JasonHenson** [comment]
+1

**Comment by volkanaldas** [comment]
+1

**Comment by Amir-Taboul** [comment]
+1

**Comment by rahulbats** [comment]
+1

**Comment by henrikra** [comment]
Here is implementation for this feature https://gist.github.com/chih/3aa8b3bbd490137a31f0b864eff1532e
Now we just need someone to make PR out of it :)

Here is also video on the implementation https://www.youtube.com/watch?v=RuzHai2RVZU

**Comment by lavarajallu** [comment]
in your textInput just u have pass this property
` returnKeyType='done'`

**Comment by henrikra** [comment]
@lavarajallu This does not work when using `keyboardType="number-pad"`

**Comment by jhalborg** [comment]
+1

**Comment by JasonHenson** [comment]
+1 this would be a great addition

**Comment by kitolog** [comment]
+1

**Comment by enstulen** [comment]
+1

**Comment by ptz3233** [comment]
+1

**Comment by bkdev98** [comment]
+1

**Comment by rskull** [comment]
+1

**Comment by dmr07** [comment]
+1

**Comment by luco** [comment]
Not a single PR yet?

**Comment by nntai** [comment]
+1

**Comment by irrigator** [comment]
+1

**Comment by jnrepo** [comment]
+1

**Comment by JohnProg** [comment]
+1

**Comment by beeant** [comment]
+1

**Comment by sakarit** [comment]
+1

**Comment by AnisDerbel** [comment]
+1

**Comment by stief510** [comment]
Check out https://github.com/douglasjunior/react-native-keyboard-manager

**Comment by marcioadr88** [comment]
The "Done" button is always shown in english? My phone lang is in spanish and the button should display as "Hecho". I have this issue only on iOS.

**Comment by NicholasBertazzon** [comment]
@marcioadr88 You need to add support for the localizations. See http://www.ibabbleon.com/iphone_app_localization.html

**Comment by marcioadr88** [comment]
It works, thanks @NicholasBertazzon

**Comment by renso3x** [comment]
Here you can add next also https://gist.github.com/renso3x/2939df594d8571ccfe23aa9bd70e96d7

**Comment by maryammouse** [comment]
+1

**Comment by dauane** [comment]
+1

**Comment by KangYoosam** [comment]
+1

**Comment by savagesnake** [comment]
returnKeyType='done' works with "number-pad" or "numeric" on v0.47.1

**Comment by w-** [comment]
+1

**Comment by w-** [comment]
+1

**Comment by TheMonster1995** [comment]
I have the same problem trying to show "Next" using return key type, and it just doesn't show. Any ideas? This problem only exists on numeric pad, or any other kind of keyboard that shows only the numbers - it works just fine with normal keyboard.

**Comment by PROudoxa** [comment]
Very nice story how to dismiss numpad keyboard!
https://medium.com/@KaushElsewhere/how-to-dismiss-keyboard-in-a-view-controller-of-ios-3b1bfe973ad1

**Comment by egemon** [comment]
Are there any native solutions for custom top bar for any type of keyboard?

**Comment by PROudoxa** [comment]
override func viewDidLoad() {
   super.viewDidLoad()
   //init toolbar
   let toolbar:UIToolbar = UIToolbar(frame: CGRect(x: 0, y: 0,  width: self.view.frame.size.width, height: 30))
   //create left side empty space so that done button set on right side
   let flexSpace = UIBarButtonItem(barButtonSystemItem:    .flexibleSpace, target: nil, action: nil)
   let doneBtn: UIBarButtonItem = UIBarButtonItem(title: “Done”, style: .done, target: self, action: Selector(“doneButtonAction”))
   toolbar.setItems([flexSpace, doneBtn], animated: false)
   toolbar.sizeToFit()
   //setting toolbar as inputAccessoryView
   self.textField1.inputAccessoryView = toolbar // add any textField
   self.textField2.inputAccessoryView = toolbar // add your textField
}
func doneButtonAction() {
   self.view.endEditing(true)
}
