### ISSUE TITLE
Orientation reset on HMR

### ISSUE THREAD

**Issue by eurobob** [facebook/react-native#11903]
### Description

I'm using a device stand to run my app on an iPhone next to my laptop and using HMR for development. Because of this, my USB cable needs to be at the top, so I have my device upside down. I've managed to get the orientation working as per #11864 , but every time HMR patches the app, it reverts to standard portrait mode

### Reproduction

Requires a device

### Solution

I have no idea, that's why i'm posting here

### Additional Information

* React Native version: 0.40.0
* Platform: iOS, maybe Android. Have only tested iOS 10
* Operating System: MacOS

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
