### ISSUE TITLE
ScrollView height includes additional padding 

### ISSUE THREAD

**Issue by xixixao** [facebook/react-native#11917]
### Description

ScrollView's minimal computed height includes a bounce buffer on iOS. Related to #3422.

### Reproduction
If you have the following layout, the ScrollView behaves correctly except for its height being the height of the children plus bounce padding (about 150px).
```jsx
<View style={{flex: 1, alignItems: 'stretch'}}>
  <ScrollView>
      <Text>Item 1</Text>
      <Text>Item 2</Text>
      <Text>Item 3</Text>
  </ScrollView>
  <View style={{flexGrow: 1, backgroundColor: 'red'}}>
    I should stretch unless scrollview is too big
  </View>
</View>
```

### Solution

The height of the ScrollView should be only equal to the height of the children (or the height of the parent if there are more children than can fit).

### Additional Information

* React Native version: 0.39.2
* Platform: iOS
* Operating System: MacOS

**Comment by iou90** [comment]
also happened on React Native 0.43

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/scrollview-height-includes-additional-padding
