### ISSUE TITLE
Transformed TouchableHighlight losing anialiase

### ISSUE THREAD

**Issue by MaxGraey** [facebook/react-native#11911]
### Description

It seems to transformed TouchableHighlight not valid property allowsEdgeAntialiasing

### Reproduction

```jsx
<View style={styles.root}>
   <StatusBar barStyle="light-content"/>
   <TouchableHighlight style={{transform: [{ rotate: "20deg" }]}}>
       <View style={{
           marginLeft: 70, 
           marginTop: 50, 
           width: 180, 
           height: 180, 
           backgroundColor: 'white'
       }}/>
   </TouchableHighlight>
   <View style={{
       marginLeft: 70,
       marginBottom: 100,
       width: 180,
       height: 180,
       backgroundColor: 'white',
       transform: [{ rotate: "20deg" }]
   }}/>
</View>
```

### Result

![TouchNotAntialiased](https://dl.dropboxusercontent.com/u/33221668/TouchNotAntialiased.jpg)
![TouchNotAntialiasedZoomed](https://dl.dropboxusercontent.com/u/33221668/TouchNotAntialiasedZoomed.jpg)

### Solution

Unknown

### Additional Information

* React Native version: 0.40.0
* Platform: iOS
* Operating System: MacOS

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
