### ISSUE TITLE
PushFromBottom for Navigator

### ISSUE THREAD

**Issue by pvinis** [facebook/react-native#11916]
I would like to have that. Should I submit a PR for that?

**Comment by yuya-fujimoto** [comment]
Any problem with `FloatFromBottom`?
Also `Navigator` is going to be deprecated really soon so it's not a good idea to write a PR since it may not be included in any release.

**Comment by pvinis** [comment]
oh ok. then I can wait for that first. yea I don't want the float one because of this 3d effect it has. I want the native push effect.

**Comment by ericvicenti** [comment]
Sorry, Navigator will be deprecated soon. You can fork it and customize it for your app if you'd like, but otherwise you may want to look into React Navigation
