### ISSUE TITLE
After upgrading from 0.39.2 to 0.40.0, I got so many compiling warnings and errors.

### ISSUE THREAD

**Issue by jaggerwang** [facebook/react-native#11921]
### Description

The compiling warnings and errors.
![image](https://cloud.githubusercontent.com/assets/1255011/21971542/7c7b3e0a-dbec-11e6-9fdb-2471b039d89b.png)

I've already did as the follows.
http://stackoverflow.com/questions/41477241/react-native-xcode-upgrade-and-now-rctconvert-h-not-found
![image](https://cloud.githubusercontent.com/assets/1255011/21971565/bc3a80be-dbec-11e6-8fa0-1d82fac624b2.png)

### Additional Information

* React Native version: 0.40.0
* Platform: iOS, Android not test until now.
* Operating System: MacOS

**Comment by christopherdro** [comment]
@jaggerwang This is a breaking change in iOS in 0.40.

See https://github.com/facebook/react-native/wiki/Breaking-Changes#namespace-all-header-imports-to-react-e1577d---javache

You'll have to check all your third-party modules to see if they have released an update with these changes or fork the repos yourself and make the necessary updates.
