### ISSUE TITLE
can not overflow visible navigator

### ISSUE THREAD

**Issue by Maxim-Chugaev** [facebook/react-native#11920]
Example
<img width="374" alt="2017-01-16 02 31 22" src="https://cloud.githubusercontent.com/assets/1440378/21967243/43601cf6-db94-11e6-98e3-a07d32facdcf.png">
i applied overflow visible for sceneStyle of Navigator, and for NavigationBar.
But I did not achieve the desired result

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
