### ISSUE TITLE
RN 0.40.0 Cannot connect to Debug JS Remotely on change of Port

### ISSUE THREAD

**Issue by neel132** [facebook/react-native#11937]
### Description
This is the Exception i getting into Android Emulator:

DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false' failed to load.
    at executeApplicationScript (http://localhost:8080/debuggerWorker.js:40:9)
    at http://localhost:8080/debuggerWorker.js:65:7

Here I have changed the default port to 8080 from 8081, because i have MCAFee installed into my system.

I am running my server on port 8080 successfully but I am not able to debug it remotely. I think it trying to fetch the script from default port 8081 

In Chrome console: 
GET http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false 403 (Forbidden)

Any modification is required in any file manually ? Please help
Thanks in Advance

### Additional Information

* React Native version: [0.40.0]
* Platform: [Android]
* Operating System: [ Windows]

**Comment by hramos** [comment]
Solved in #12095
