### ISSUE TITLE
Get rid of SYSTEM_ALERT_WINDOW permission in production build

### ISSUE THREAD

**Issue by yeknava** [facebook/react-native#11931]
i understand RN needs SYSTEM_ALERT_WINDOW for debug stuff, but even when i want to build my app with 'gradlew assembleRelease' and even when i commented this line
```<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>```
in /src/main/AndroidManifest.xml file, RN still adds this permission to list of permissions during build process.

is there any way to stop it ?

RN 0.39
ubuntu 16.04

**Comment by hey99xx** [comment]
This was extensively discussed in https://github.com/facebook/react-native/issues/5886 

The fix most people have taken is the production-only AndroidManifest.xml change explained in the issue link.

**Comment by yeknava** [comment]
Solution:

1. add tools to manifest:
````<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools>````
2. add this line to manifest:
```` <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" tools:remove="${excludeSystemAlertWindowPermission}"/>````
3. add this lines to android build types in app/build.gradle
````buildTypes {
        debug {
            manifestPlaceholders = [excludeSystemAlertWindowPermission: "false"]
        }
        release {
            manifestPlaceholders = [excludeSystemAlertWindowPermission: "true"]
        }
    }
````
