### ISSUE TITLE
ListView layout breaks when loading more items while zoomed in on iOS

### ISSUE THREAD

**Issue by dgoudy** [facebook/react-native#11934]
### Description

My use case is a horizontally scrolling ListView with images. I would like the user to be able to zoom in on the images, and still be able to scroll smoothly through the list. I attempted to accomplish this on iOS by setting minimumZoomScale to 1.0 and maximumZoomScale to 2.0. At first glance this works as intended, until you scroll and cause more items to load. When more items load while the ListView is zoomed in, the layout breaks in an odd way. The content suddenly scrolls to the right, and the entire ListView shifts upwards, cutting off the tops of the images.

Testing with a vertically scrolling list shows a similar problem, but with the list items shifting to the left instead of upwards.

### Reproduction

Repro with simple views: https://rnplay.org/apps/75Oomw
(Note that this is using React Native 0.33.0, but it is also happening on 0.40.0 when running on device.)

Steps:
* Zoom in so that "0 - Top" remains at the top of the view, and "0 - Middle" is near the bottom of the view.
* Scroll to the right until more items load, near item 7 or so.
* ListView content jumps sideways to item 10 or so, and upwards so that "10 - Middle" is now in the middle of the view, instead of at the bottom.
* Zoom out again. "Middle" will be near the top of the view, and there will be a gap between the bottom of the ListView and the bottom of the screen. You are unable to scroll up to see the tops of the items. You are also unable to scroll all the way back to the beginning of the list.

The rnplay.org version is a bit hard to use for zooming and scrolling, so here's a repo showing the problem with a freshly initialized project using React Native 0.40.0:
https://github.com/dgoudy/react-native-listview-zoom-load-bug

### Solution

Not sure. My guess would be that the ListView is trying to recalculate bounds after adding more items, and the zoom is not being taken into account. Rotating the screen fixes the problem, presumably by recalculating layouts. The layout also seems to fix itself if you zoom out, then scroll further, causing another set of items to load.

### Additional Information

* React Native version: 0.40.0 (on device), 0.33.0 (rnplay.org)
* Platform: iOS 10.2
* Operating System: MacOS 10.12.2, XCode 8.2.1

**Comment by hramos** [comment]
Closing as ListView is deprecated in 0.43. Use FlatList.
