### ISSUE TITLE
[Android] Connection timed out from Gradle when behind a proxy

### ISSUE THREAD

**Issue by emaborsa** [facebook/react-native#11936]
I get Connection timed out when Gradle is building the app. I know the problem is the proxy. In Android Studio it works using **auto-detect proxy settings** specifying the url `http://myHost:8080/array.dll?Get.Routing.Script`.

For react native I tried to add the following to the gradle.properties but it doesn't work:
`systemProp.http.proxyHost=http://myHost:8080/array.dll?Get.Routing.Script`
`systemProp.http.proxyPort=8080`
`systemProp.https.proxyHost=http://myHost:8080/array.dll?Get.Routing.Script`
`systemProp.https.proxyPort=8080`

**Comment by Swordsman-Inaction** [comment]
I do not think Gradle support auto-detect proxy itself. You can open `http://myHost:8080/array.dll?Get.Routing.Script` in the browser, then find out the real `proxyHost` and `proxyPort`, then set them to `systemProp.http.proxyHost` and `systemProp.http.proxyPort`

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/android-connection-timed-out-from-gradle-when-behind-a-proxy
