### ISSUE TITLE
[Android] RefreshControl gesture conflicts with horizontal ScrollView gesture

### ISSUE THREAD

**Issue by fdnhkj** [facebook/react-native#11939]
### Description

I have a use case where I want to list horizontally cards.
I implemented it with a horizontal ScrollView.

Then, for each card I want to implement the pull-to-refresh pattern to let the user manually refresh the data displayed in there.

I nested therefore a ScrollView within the first one but this time with a RefreshControl component as advised by @ericvicenti in https://github.com/facebook/react-native/issues/10910#issuecomment-260471144 .

The issue is that on Android, when I do pull-to-refresh gesture, the refresh component gets in conflict with the horizontal ScrollView (see gif below).

![scrollview-refreshcontrol-android](https://cloud.githubusercontent.com/assets/5569608/22013937/b302bafc-dc9b-11e6-8afe-02c49abce26c.gif)

### Reproduction

https://rnplay.org/apps/dZSmGQ

```
class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {isRefreshing: false};
  }

  _onRefresh() {
    this.setState({isRefreshing: true});
    setTimeout(() => {
      this.setState({isRefreshing: false});
    }, 2000);
  }

  render() {
    return (
      <View style={{flex: 1}}>
        <Text style={{padding: 20}}>
      		Text
        </Text>
        <ScrollView
          contentContainerStyle={styles.container}
          horizontal
          pagingEnabled
          showsHorizontalScrollIndicator={false}
          directionalLockEnabled
        >
          <ScrollView
            refreshControl={
              <RefreshControl
                refreshing={this.state.isRefreshing}
                onRefresh={this._onRefresh.bind(this)}
              />
            }>
              <Text style={styles.card}>First child</Text>
          </ScrollView>
          <ScrollView
            refreshControl={
              <RefreshControl
                refreshing={this.state.isRefreshing}
                onRefresh={this._onRefresh.bind(this)}
              />
            }>
              <Text style={styles.card}>Second child</Text>
          </ScrollView>
        </ScrollView>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  card: {
    width: Dimensions.get('window').width,
    textAlign: 'center'
  },
  container: {
    borderWidth: 1,
    borderColor: 'red'
  },
  refreshControl: {
    backgroundColor: 'red'
  }
});
```

### Solution

* Find out why the pull-to-refresh and horizontal scrollview gestures are conflicting
* Isolate the horizontal gesture for the horizontal scrollview
* Isolate the vertical gesture for the RefreshControl component

### Additional Information

* React Native version: 0.42
* Platform: Android
* Operating System: MacOS

**Comment by teodors** [comment]
I am having the same issue on 0.41-rc.0. I think a possible fix might be to disable horizontal scroll while doing vertical scroll. I think this might be because touch event just gets hijacked by horizontal ScrollView.

**Comment by sohobloo** [comment]
Is there any workaround right now?

**Comment by teodors** [comment]
@sohobloo Not as far as I know. I struggled with this a lot and went back to ViewPagerAndroid. Unfortunately, iOS issues get a bit more love and attention than Android ones.

**Comment by rexjrs** [comment]
Bumping. Any updates on this? Really need a fix.

**Comment by valeriik** [comment]
This is really critical bug because it blocks to use whole the component on Android (with usage of pull-to-refresh pattern). Please fix ASAP. Thanks.

**Comment by valeriik** [comment]
In order to find temporary trick also submitted 2 questions on stackoverflow:
1. http://stackoverflow.com/questions/43800344/how-to-block-horizontal-gesture-in-parent-listview-in-react-native-on-android
2. http://stackoverflow.com/questions/43784388/is-there-a-way-to-catch-start-stop-event-using-pull-to-refresh-gesture-of-listvi

**Comment by zhuyifan2013** [comment]
Any update ???? Developer ???

**Comment by rexjrs** [comment]
January 17 this was posted and still no update? Seriously?

**Comment by teodors** [comment]
@rexjrs  @zhuyifan2013 Being part of RN community for some while, I must say Android usually gets neglected. I created a post on Product Pains for this issue.

https://react-native.canny.io/feature-requests/p/android-refreshcontrol-gesture-conflicts-with-horizontal-scrollview-gesture

**Comment by fdnhkj** [comment]
I just checked if the issue was still there when using newest version of RN.
And.. it looks better in 0.44  🎉

Now, when doing the same gesture (vertical+horizontal), the swipe refresh is invalidated - where before the swipe refresh component remained stuck on the screen.

**Demo** https://github.com/fdnhkj/rn-issue-11939
![scrollview-refreshcontrol-android](https://cloud.githubusercontent.com/assets/5569608/26283069/9a766b28-3e20-11e7-9c40-7deff88b47bc.gif)


I'll read the release notes to see which commit helped.

**Comment by teodors** [comment]
@fdnhkj Haven't developed in RN for a while, but was wondering if slight gesture changes would cancel swipe. What I mean is - would slight (natural) gesture changes cancel out PullToRefresh? Would this be frustrating to end user?

Still, I think this is not ideal. The underlying problem is that gesture is being hijacked. Progress on PTR element should remain, even if you move horizontally, since this is the expected interaction from users.

**Comment by zhuyifan2013** [comment]
TabNavigation + FlatList  in RN 0.44 works well (PullToRefresh and swipe left and right), maybe you could refer to that implementation.

**Comment by em222iv** [comment]
+1, Needs fix asap

**Comment by badaz** [comment]
Yep, I thought it was something I had done, but nope, just a bug, are there any news or workaround other than upgrading RN ?

**Comment by hhanh00** [comment]
This happens on RN 0.48.2 as well

**Comment by Jacse** [comment]
Happens in `0.50.2` too. Could this be reopened, @hramos ?

**Comment by AlgoTrader** [comment]
Same for me. I vote for reopening the issue.

**Comment by jinzunyue** [comment]
Same for me.I'm using the newest version, 0.50.3. It's a bug from 2017 to 2018.

**Comment by masterpetit** [comment]
Just upgraded to ```react-native: 0.52.2``` but the problem still occurs.

**Comment by badaz** [comment]
Strange... it disappeared completely in my app, ios and android. My setup is: listviews with refresh control nested in tabs.

**Comment by badaz** [comment]
Btw my tabs are from react-native-scrollable-tabview, maybe I updated it, can't remember. The rest of my navigation is react-native-navigation. This I changed recently, I was using react-native-router-flix before, but rn-navigation is not handling my tabs

**Comment by Lomaas** [comment]
Same problem on react-native: 0.52.2

**Comment by ahmad2smile** [comment]
The issue was 1 swipe event was being handled by 2 Listeners. Child and Parent. I moved Pull-to-Refresh event setup to Parent and running control of child in parent. As sort of suggested by @badaz

**Comment by diesmori** [comment]
I solved it calling to _onRefresh() on a parent component:

Scrollable component:
`render() {
    return (
      <Container>
        <Content>
          <ScrollView //without refreshControl
.../>
</Content>
</Container>
...etc
`

Parent component:
`<ScrollView
                    refreshControl={
                      <RefreshControl
                        refreshing={this.state.refreshing}
                        onRefresh={this._onRefresh.bind(this)}
                      />
                    }
                  >
                    <Tasks
                      ...
                    />
                  </ScrollView>`

I have Swipe elements into Task controller

**Comment by recepkocur** [comment]
+1

**Comment by ahmad2smile** [comment]
@diesmori I thought this technique would work but it sort of doesn't. If your child has the Vertical List and then you put refresh control on you parent which is Horizontal then you can't Scroll Up the Child List. It just triggers refresh on Horizontal Parent List.

**Comment by Sammekl** [comment]
This definitely needs a fix, nearly impossible to refresh on Android. Any progress on this issue?

**Comment by yeshengwu** [comment]
@diesmori  this technique works fine.  @ahmad2smile you should take cake of you own child listview .

**Comment by yeshengwu** [comment]
@ahmad2smile I mean that you could disable refreshControl of the Horizontal when you scroll your child FlatList by FlatList onScroll callback.

**Comment by ahmad2smile** [comment]
I tried that @yeshengwu . The Refresh Controls don't update dynamically. If its disabled it doesn't update onScroll. 

I ended up keep my setup on iOS as it works smooth on iOS but on Android I had to remove Parent list and ended up with Detecting Left Right Swipe Gestures and rendering new elements in place on Parent List. Its horrible but that was the only option on android.

**Comment by henrikland** [comment]
+1
