### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZSt14__once_functor" referenced by "libfb.so"

### ISSUE THREAD

**Issue by visa8000** [facebook/react-native#11941]
### Description

I have changed   Application.mk file, set   APP_ABI = armeabi,  but the so load failed

01-17 17:03:55.317 19832-19832/? W/System.err: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZSt14__once_functor" referenced by "libfb.so"...
01-17 17:03:55.317 19832-19832/? W/System.err:     at java.lang.Runtime.load(Runtime.java:332)
01-17 17:03:55.317 19832-19832/? W/System.err:     at java.lang.System.load(System.java:981)
01-17 17:03:55.317 19832-19832/? W/System.err:     at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:71)
01-17 17:03:55.317 19832-19832/? W/System.err:     at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:42)
01-17 17:03:55.317 19832-19832/? W/System.err:     at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:299)
01-17 17:03:55.317 19832-19832/? W/System.err:     at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:247)
01-17 17:03:55.318 19832-19832/? W/System.err:     at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:24)
01-17 17:03:55.318 19832-19832/? W/System.err:     at com.facebook.react.bridge.ReactBridge.<clinit>(ReactBridge.java:20)
01-17 17:03:55.318 19832-19832/? W/System.err:     at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:24)
01-17 17:03:55.318 19832-19832/? W/System.err:     at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:22)
01-17 17:03:55.318 19832-19832/? W/System.err:     at com.facebook.react.JSCConfig$1.getConfigMap(JSCConfig.java:14)

* React Native version: [0.40.0]
* Platform: [Android]
* Operating System: [MacOS]

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
