### ISSUE TITLE
Wifi router blocking internal IP

### ISSUE THREAD

**Issue by mkoo21** [facebook/react-native#11949]
We are running into an issue with some public wifi networks (hotels, coffee shops) where the router seems to be preventing access to the JS bundle on device (logging from 192.168.2.19:8081 -> could not connect to devlepment server). This is after installing/testing our app on device from our office wifi, where it works fine. Needless to say accessing/changing router settings isn't an option.

Has anyone else run into this issue/found any solutions?

**Comment by Waterbyte** [comment]
After you moved to public wifi, did u also updated the ip address in development mode? 
You need to verify whether you followed all the steps in Method 2 of this link (connecting with development server):[http://facebook.github.io/react-native/releases/0.40/docs/running-on-device.html#content](url)

**Comment by mkoo21** [comment]
I should probably clarify that the issue wasn't really about developing on public wifi, we had installed the app on device and wanted to run it for demo purposes (so independent of the development machine). 

Anyways we installed a debug build as per usual since it's still in development and ran into this issue, but switching to a released build seems to have resolved the issue. Thanks for your help.
