### ISSUE TITLE
AsyncStorage multiSet behaviour inconsistent between platforms

### ISSUE THREAD

**Issue by ThisIsMissEm** [facebook/react-native#11944]
### Description

Calling the following code yields different results between iOS and Android:

```
AsyncStorage.multiSet([])
```

Yes, I know it seems like you'd never call `multiSet` with an empty `keyValuePairs` array, however, this can happen when you're using it something like: 

```
AsyncStorage.multiSet(_.toPairs(someStateObject))
```

On iOS, the above call works fine.

On Android, the call errors out with an Invalid Key error "null" being the key.

### Reproduction

I tried to create a test case on rnplay.org, however, it failed to start/run, so here's the code: https://gist.github.com/ThisIsMissEm/615d9bbc9813945c9684dfea01f6f176

### Solution

It seems Android's code features an [additional error check](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/modules/storage/AsyncStorageModule.java#L82-L85) that iOS [does not](https://github.com/facebook/react-native/blob/master/React/Modules/RCTAsyncLocalStorage.m#L357)

The solution would be to just make these code paths identical (I'm not sure exactly how to do this, as I'm not fluent enough in objective-c or java)

### Additional Information

* React Native version: master, 0.39.2
* Platform: Both
* Operating System: MacOS

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
