### ISSUE TITLE
[JS] JS API for global handling of unhandled exceptions

### ISSUE THREAD

**Issue by ide** [facebook/react-native#1194]
The API I envision is similar to window.onerror but not necessarily the same. This would allow us to make  `RCTExceptionsManager.reportUnhandledException` a lot smaller (we'd move much of the code into JS to keep the current behavior) and make it easier to do custom error handling.

**Comment by dvine-multimedia** [comment]
@ide Hi. I would very much appreciate such an API. In the mean time is there a way to prevent an production app from crashing on any random JavaScript exception?

**Comment by JoeStanton** [comment]
This would be great for adding something like Bugsnag to report exceptions when apps are in production.

**Comment by richardgill** [comment]
We're looking to log something anytime there is an error, so we can catch bugs early. This would be very useful.

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by despairblue** [comment]
would be definitely useful!:+1:

**Comment by sjmueller** [comment]
@ide, what is the current recommended approach (or hack) for custom handling of global errors?

**Comment by ide** [comment]
You could either hook into the native layer or monkeypatch the JS ExceptionsManager.

**Comment by mkonicek** [comment]
Just saw this - sounds like we should have some global error handler for all JS (and native?) errors. Super useful to log all exceptions instead of crashing etc.

@foghina Do you know if we have anything like that (in the works) on Android, iOS?

**Comment by mkonicek** [comment]
See `ErrorUtils.setGlobalHandler`: https://github.com/facebook/react-native/blob/master/Libraries/JavaScriptAppEngine/Initialization/InitializeJavaScriptAppEngine.js#L87

**Comment by ajwhite** [comment]
Is it a bad idea to set my own global error handler?

My scenario was to
- Report exception to Sentry
- Reload the bridge to avoid crashing

**Comment by qbig** [comment]
Hi @ajwhite. Any luck completing the 2 points you mentioned?

**Comment by qbig** [comment]
Here: https://github.com/facebook/react-native/blob/d33b554f5d4bb7856cf2fc21175bab23d8225fe4/packager/react-packager/src/Resolver/polyfills/error-guard.js
```javascript
var ErrorUtils = {
  _inGuard: 0,
  _globalHandler: null,
  setGlobalHandler: function(fun) {
    ErrorUtils._globalHandler = fun;
  },
//...
```
'setGlobalHandler' would overwrite a lot of the RN behaviour (eg. RedBox in development). Understanding that we could just monkey patch _globalHandler, the "_" seems alarming. So maybe an API like addGlobalHandler, so that we could add custom handler without breaking the default behaviour and and without messing with "internal" variables ?  @ide  @satya164

**Comment by ajwhite** [comment]
In production mode I call `setGlobalHandler` with my own handler, which does the two things listed above -- logging to sentry & reloading the bridge. Seems to work just fine.

**Comment by qbig** [comment]
@ajwhite Cool. How do you reload the bridge? Would really appreciate it if you could share a gist or something.

**Comment by qbig** [comment]
@ajwhite And you have a __DEV__ check I suppose?

**Comment by ajwhite** [comment]
Exactly @qbig

Basically
```js
if (!__DEV__) {
  ErrorUtils.setGlobalHandler(error => {
    sentry.capture(error);
    NativeModules.BridgeReloader.reload()
  });
}
```

Then your `BridgeReloader` would be an objC module that simply calls `[_bridge reload]`

Or in an Android module, you just get the running activity, finish it, and restart it
```java
@ReactMethod
public void reload() {
  Activity activity = getCurrentActivity();
  Intent intent = activity.getIntent();
  activity.finish();
  activity.startActivity(intent);
}
```

**Comment by qbig** [comment]
That's neat:) @ajwhite Thanks so much! 
I guess you are not using the raven-js plugin? which does something like :
```JavaScript
    ErrorUtils.setGlobalHandler(Raven.captureException.bind(Raven));
```
But I don't like the fact that it is overwriting the default exception handler.

So I was considering something like 
```JavaScript
    var defaultHandler = ErrorUtils._globalHandler;
    ErrorUtils._globalHandler = function(...args){
      defaultHandler(...args);
      Raven.captureException(...args);
      // other custom handler
    };

```

**Comment by ajwhite** [comment]
Just took a read through the latest Raven source. The version I had used months back would [report exceptions by loading an image](https://github.com/getsentry/raven-js/blob/f92ff9de538f331a291af4a7d302202e587aaae5/src/raven.js#L755-L781).. That obviously doesn't work well for us here in React Native land. Their latest version looks like it has full support now though!

> But I don't like the fact that it is overwriting the default exception handler.

That would work. I just re-read the source for the native error handler. It looks like it does two things:
- [Shows the redbox](https://github.com/facebook/react-native/blob/88ac40666cf0372fd9bb481c5b8b35c00a929475/React/Modules/RCTExceptionsManager.m#L51) (I assume this does nothing if not in `__DEV__` mode
- [Reloads the bridge](https://github.com/facebook/react-native/blob/88ac40666cf0372fd9bb481c5b8b35c00a929475/React/Modules/RCTExceptionsManager.m#L59-L60) 

I had no idea until now that it reloads the bridge by default. I don't know if this is a new development or not, but that's pretty cool. Unfortunately the application I work on is basically a "kiosk mode" type of thing running 24/7. I notice the handler has a `maxRetries`, which wouldn't work for me, so I'll likely bypass this as I am currently.

So keeping a reference to the original handler and calling it is probably a good thing in your example

**Comment by qbig** [comment]
@ide @satya164 is there any suggested way to add the handler ?

**Comment by ide** [comment]
I think `ErrorUtils.setGlobalHandler` is the recommended way. Maybe the API should be changed to let you get access to the default handler.

**Comment by qbig** [comment]
@ide like a getter for "_globalHandler" ?

**Comment by ide** [comment]
Yes, making it part of the public API.

**Comment by qbig** [comment]
```JavaScript
var ErrorUtils = {
  _inGuard: 0,
  _globalHandler: null,
  getGlobalHandler : function() {
  
  },
  setGlobalHandler: function(fun) {
    ErrorUtils._globalHandler = fun;
  },
  reportError: function(error) {
    ErrorUtils._globalHandler && ErrorUtils._globalHandler(error);
  },
  reportFatalError: function(error) {
    ErrorUtils._globalHandler && ErrorUtils._globalHandler(error, true);
  },
// ...
```

**Comment by satya164** [comment]
@qbig Looks reasonable.

**Comment by jsierles** [comment]
This issue appears to have been solved by #5575. Closing this issue out for now.

**Comment by npomfret** [comment]
Hi, I'm fairly new to both RN and javascript.  I've put the following into my code... It catches errors and warnings in an array before reporting them as normal to the console.  

It sits at the top of my main.js file.  It seems to work, but is this a terrible idea?

```
const orig_console_warn = console.warn;
const orig_console_error = console.error;

let errors = [];
let warnings = [];

console.warn = function() {
  warnings.push(arguments);
  orig_console_warn.apply(console, arguments);
};

console.error = function() {
  errors.push(arguments);
  orig_console_error.apply(console, arguments);
};

```

I then periodically clear the array and send the data to some reporting system.

**Comment by GeoffreyPlitt** [comment]
@jlo1 Did you ever find a solution for non-debug mode?

**Comment by antoinerousseau** [comment]
I'm pretty sure that `global.ErrorUtils.setGlobalHandler` works in production mode too on Android, fyi.

**Comment by GeoffreyPlitt** [comment]
What about iOS? Is there a platform-agnostic way to do this?

**Comment by npomfret** [comment]
I ended up trapping console.log, console.info, console.warn and console.error and writing the data to an in-memory buffer that I can view in my app.  I also send error and warn messages to a server that records the data so I can see error from my clients in one central place.

**Comment by GaoYuJian** [comment]
```
iOS
  RCTSetFatalHandler(^(NSError *error) {
    [Bugly reportError:error];
    
     [rootView.bridge reload];
  });
```
