### ISSUE TITLE
ReferenceError: Can't find variable: module

### ISSUE THREAD

**Issue by ishabo** [facebook/react-native#11943]
I am not sure whether this is a react issue. I've seen this error a few times and now I am stuck with it. The same code branch works fine on my collegues' machine. 
<img width="455" alt="2017-01-17_1107" src="https://cloud.githubusercontent.com/assets/1992039/22018583/64f1354e-dca7-11e6-9f05-14ffdacd1ed9.png">

I tried different emulators and my phone and it's just the same. 

I did a watchman `watch-del-all`, `rm -rf node_modules`, `npm install`, `npm start -- --reset-cache`, `rm -fr $TMPDIR/react-*` all to no avail.

I spent a full day yesterday searching the internet, but never came across anything like that!

I looked at my index.android.bundle, which is very difficult to read, and it seems it points to the usage of module and module.exports (around line 303).

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
