### ISSUE TITLE
[ANDROID] Unfortunately, app has stopped on genymotion!!!

### ISSUE THREAD

**Issue by lelup** [facebook/react-native#11942]
Hi all! I builded successful my project but genymotion alert: Unfortunately! app has stopped. How should I solve this???
Thanks alot!
![nexus 6 - 7 0](https://cloud.githubusercontent.com/assets/19283388/22018543/dbd7d44e-dce1-11e6-94fe-fb1aa2a0708f.png)
![screen shot 2017-01-17 at 11 44 19](https://cloud.githubusercontent.com/assets/19283388/22018547/dfc04dc0-dce1-11e6-8395-fd7c34f38ad2.png)

**Comment by lelup** [comment]
## @grabbou @brentvatne @janicduplessis

**Comment by skv-headless** [comment]
What `adb logcat` says?

**Comment by lelup** [comment]
![screen shot 2017-01-19 at 13 58 18](https://cloud.githubusercontent.com/assets/19283388/22096671/783bdcfe-de4f-11e6-9c73-6b91330bbba2.png)
@skv-headless I tried to set up Android environment for my project two day ago. Today it still won't work.

**Comment by lelup** [comment]
![screen shot 2017-01-19 at 14 09 28](https://cloud.githubusercontent.com/assets/19283388/22096932/ed96b18a-de50-11e6-8230-1d31b579f55e.png)

here is my terminal when I run: adb logcat *:S MyComponent:V

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/android-unfortunately-app-has-stopped-on-genymotion

**Comment by muneebkhan7737** [comment]
please open this issue again

**Comment by alihesari** [comment]
same problem
