### ISSUE TITLE
about react-native-git-upgrade

### ISSUE THREAD

**Issue by windhost** [facebook/react-native#11956]
When I uagrade my app from 0.32 to 0.4, I got an error .
```
error: cannot run /usr/local/bin/bcdiff: No such file or directory
fatal: external diff died, stopping at .babelrc
git-upgrade ERR! An error occurred during upgrade: 
git-upgrade ERR! Error: Command 'git diff HEAD~1 HEAD' exited with code 128:
stderr: undefinederror: cannot run /usr/local/bin/bcdiff: No such file or directory
fatal: external diff died, stopping at .babelrc
```
My environment is maxOS 10.12.2.

**Comment by rmevans9** [comment]
It looks like you have your git setup to use bcdiff to resolve conflicts. When git tries to open bcdiff it fails to find it so it errors out. I would recommend you figure out if you still want to have bcdiff as your compare tool, if so fix the issue of it not finding it. If not, modify your git config to not try and use bcdiff.

**Comment by windhost** [comment]
You are right, I miss config git. Thanks.
