### ISSUE TITLE
[Geolocation] Background low-power / significant location change Geolocation updates

### ISSUE THREAD

**Issue by timfpark** [facebook/react-native#1195]
An application we are building has a need for Foursquare style persistent low power / low accuracy location updates.

In our all native app, we are using CLLocation::startMonitoringSignificantLocationChanges to do this.

I'd like to propose that we add this to Geolocation:

1. Add a "background" option that translates to asking for requestAlwaysAuthorization on iOS.

then either:

1. Redefine the "enableHighAccuracy" option to use startMonitoringSignificantLocationChanges instead of startUpdates when this is false. This seems to be the intent of what the W3C spec was looking for here in terms of providing a bool for this.

-or-

2. Add a "networkBasedUpdates" boolean option that when true uses startMonitoringSignificantLocationChanges on iOS and LocationManager.NETWORK_PROVIDER on Android.

I think I understand the code well enough to provide a PR for this.  Let me know your thoughts.

**Comment by timdoes** [comment]
+1 for this feature

**Comment by rt2zz** [comment]
Redefining `enableHighAccuracy` makes sense, and then potentially exposing seperately an `accuracy` option.

Because we are following the html geolocation api, this seems to be about the best mapping possible. If someone needs a more ios specific solution, I imagine that could live as a seperate module.

I implemented specifically the background(mode) option in https://github.com/facebook/react-native/pull/1506

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/geolocation-background-low-power-significant-location-change-geolocation-updates

**Comment by golorry** [comment]
+1

**Comment by ACCTFORGH** [comment]
Background geolocation update function is crucial to my app too. A feature like this will be awesome. Avoids all the Java native code to run a geolocation update service. Are there any updates on this?

**Comment by NoWay1201** [comment]
+1
I need a background geolocation feature too, but I want avoid writing any Java code. Some progress on that?
