### ISSUE TITLE
Is this supposed to update the package.json? 

### ISSUE THREAD

**Issue by passabilities** [facebook/react-native#11951]
### Description

Everything worked just fine and was upgraded. But I have `react` and `react-native` in my `package.json` yet they didn't change after.

### Additional Information

* React Native version: 0.28.1 upgraded to 0.40.0

**Comment by hramos** [comment]
Can you provide more details? What steps did you take and what were you expecting to happen?

**Comment by guiherzog** [comment]
I think what he meant, is that upgrading the react-native and react version using react-native-git-upgrade didn't change the React and RN version on the project's package.json file.
E.g: My RN version on the package.json is 0.36, I ran the react-native-git-upgrade steps on the website but even though this changed my installed version to 0.40, that didn't change my version on the package.json file.

I have this same doubt, do you know if we should change this version on the package.json manually ?

Thanks!

**Comment by ncuillery** [comment]
The final step of `react-native-git-upgrade` consists in applying a Git patch to updates the source files (including the `package.json` yes).

It could fail for some reasons (see below), if so, the source files are reverted to the initial state but the new version could still lie in node_modules (you have to manually install the old version back).

Known problems when applying the patch:
- if you have changed the default Android app icons #11402 
- if you have referenced Git repositories as NPM dependencies #11578 

So you are in a different situation, feel free to open a new issue **with the `react-native-git-upgrade` output**.

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
