### ISSUE TITLE
WindowedListView lags on scroll up on Android

### ISSUE THREAD

**Issue by sibelius** [facebook/react-native#11950]
### Description

I've implemented a List of Items using WindowedListView

```jsx
<WindowedListView
          data={values}
          renderRow={this.renderCell}
          initialNumToRender={10}
          onEndReached={this.handleOnEndReached}
          maxNumToRender={30}
          numToRenderAhead={20}
          viewablePercentThreshold={50}
          renderWindowBoundaryIndicator={this.renderWindowBoundaryIndicator}
          />
```

it works fine on iOS, but it lags a lot on Android.

this is a video of the bug: https://youtu.be/aFDBJU93b-o

it takes a lot of time to rerender the row when we scroll up, and it waits one row to be rendered after another.

this do not happen on ios

### Additional Information

* React Native version: 0.39.2
* Platform: Android
* Operating System: MacOS

**Comment by sibelius** [comment]
I figure it out that WindowedListView uses `contentInset` prop of `ScrollView` here: https://github.com/facebook/react-native/blob/942b9332b2e9eb779e84d996648e66550965af82/Libraries/Experimental/WindowedListView.js#L531

that only works on iOS

I've tried to replace it to use `contentContainerStyle` as described here https://github.com/facebook/react-native/issues/2914#issuecomment-167153409 by @satya164,

but it did not work

any ideas of how can I fix this for android?

**Comment by satya164** [comment]
@sibelius it works for that use case, but it's not quite the same.

**Comment by bharath-kamath** [comment]
@sibelius Did you manage to fix the scroll issue?

**Comment by sibelius** [comment]
No, I've migrated to FlatList

But it also has the same problem with the list has a bunch of rows

**Comment by bharath-kamath** [comment]
@sibelius Please reopen this issue as its still not fixed.

**Comment by sibelius** [comment]
@bharath-kamath I recommend to move to `FlatList` instead of using `WindowedListView`,

and open another issue if you have the same problem with `FlatList`
