### ISSUE TITLE
Black screen for HTML5 video player in Android WebView

### ISSUE THREAD

**Issue by mehcode** [facebook/react-native#11955]
### Description

1. Created new project

```
react-native init webview_example
```

2. Replaced text nodes with:

```
        <WebView
          javaScriptEnabled={true}
          style={{flex: 1}}
          source={{uri: `https://www.youtube.com/embed/IPV3rQtctkM`}}
        />
```

3. Run.

4. Video does not show (only black screen) but audio does play fine

### Reproduction

Full source code is https://github.com/mehcode/rn-scratchpad/blob/master/index.android.js

### Solution

I have no idea. I've been poking it for awhile. 

### Additional Information

* React Native version: 0.40.0
* Platform: Android v7
* Operating System: Linux

---

Some more information. That example works 100% in Android <= 6. The bug seems to only exist in Android 7+. There must be a difference to WebView usage that we're not handling.

---

Another update. I've reduced this bug down to just raw android and have the same behavior.

https://github.com/mehcode/scratchpad

**Comment by stonecold123** [comment]
@mehcode  I have the exact same problem. The embedded video only has audio. Do you have any solution now?

**Comment by mehcode** [comment]
I just gave up and use react-native-video

**Comment by stonecold123** [comment]
@mehcode 
I'm on the verge of giving up the idea of embedding youtube video. How do you use **react-native-video** with online youtube url? Do you download the youtube clip first then play the mp4/flv with **react-native-video**?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/black-screen-for-html5-video-player-in-android-webview

**Comment by rdp** [comment]
Did the original problem occur in the emulator and on actual device as well?
