### ISSUE TITLE
Memory leak when opening react native view controller in iOS

### ISSUE THREAD

**Issue by byohay** [facebook/react-native#11961]
### Description

In my app there's a part with react native. I upgraded to react native 0.40, and noticed that every time I open the react native VC, the memory usage keeps increasing.

### Reproduction

I was able to reproduce it even with this small example: https://gist.github.com/byohay/c147f80f0f0b44cdb0026b76980342a4

### Additional Information

* React Native version: 0.40.0
* Platform: iOS
* Operating System: MacOS
* Tested in debug and release

**Comment by janicduplessis** [comment]
Is this a regression in RN 0.40? What version did you upgrade from?

**Comment by byohay** [comment]
I upgraded from RN 0.33. I just checked it with RN 0.39 and it doesn't occur.

**Comment by alinz** [comment]
The memory leak in ios v0.40 is pretty bad. also the frame rate on both UI and JS is extremely low. iOS used to be really fast compare to Android. 

 Evey time, the ios gets refreshed, it adds couple of megabytes into memory. This is a default scene. 

![memory_leak](https://cloud.githubusercontent.com/assets/967050/22223542/6ba69ed8-e189-11e6-9456-9cbf7c5d30aa.gif)

**Comment by janicduplessis** [comment]
cc @javache

**Comment by alinz** [comment]
any update on this? @janicduplessis @javache, don't want to put any pressure or anything but releasing v0.41 without fixing this issue does not make any sense! Since we have to wait another month for the next patch!

**Comment by javache** [comment]
I can see a leak related to bundle loading when running a debug instrumentation build in instruments. This shouldn't affect production builds since those use a bundle on disk.

**Comment by alinz** [comment]
@javache what about the poor performance, I always get 25 to 30 frame per second!

**Comment by ide** [comment]
@alinz are you testing on a real device? It's really important that you profile speed/FPS on iPhone/iPad and not the simulator since it's often very different.

**Comment by alinz** [comment]
@ide as you said, the fps on the actual device is 60. I should have tested all cases. 😞

**Comment by byohay** [comment]
Does 0.41 release includes a fix for this? As @alinz said, it's not feasible for me to use it otherwise.

**Comment by julienfouilhe** [comment]
I am having the same issue using the master branch of the repo (commit 3850a4f5b4b885022a91ea319ef0f99ea22dcda1), reusing the same view controller and changing the appProperties fixed my problem, but it would be good if it could be freed :)

**Comment by jasongrishkoff** [comment]
Similar issue from my side.  With Android (testing on device), every time I hot refresh the memory piles up.  Similarly, if I move to a different view on the app, the memory adds up. It never seems to be cleared.

**Comment by julienfouilhe** [comment]
Can someone take a look at this? @alloy, could you maybe ping someone that could know about this? :)

Thank you! :)

**Comment by julienfouilhe** [comment]
Can someone take a look at this? @emilsjolander, could you maybe ping someone that could know about this? :)

Thank you! :)

**Comment by emilsjolander** [comment]
If @javache has already looked I don't know who to ping

**Comment by alloy** [comment]
What isn’t clear to me from the thread is if the memory leak is also witnessed on a static build or if it might be related to the bundle loading, as suggested by @javache [earlier](https://github.com/facebook/react-native/issues/11961#issuecomment-275294583) ?

**Comment by julienfouilhe** [comment]
Oh sorry I didn't see @javache answer. If we are certain this doesn't affect release builds then fine with me.

**Comment by alloy** [comment]
@julienfouilhe Nobody has verified _and_ responded back yet, so probably a good thing to double-check (and let us know once you’ve done so).

**Comment by jasongrishkoff** [comment]
I see this in multiple places in Android.  I'm basing this off of adb shell dumpsys meminfo -a

- When I reload the code, it doesn't clear any old memory or views
- If I do a "pull to refresh" it loads all the same data, but just adds on to the memory
- On infinite scroll, every time my ListView adds a new set of rows, memory increases and doesn't disappear
- If I navigate to new views within my app, the prior views don't get cleared and memory keeps doing up and up and up

**Comment by julienfouilhe** [comment]
@alloy @javache @emilsjolander I just tested by changing the scheme to release and it is still piling up 
<img width="304" alt="screen shot 2017-02-21 at 4 42 54 pm" src="https://cloud.githubusercontent.com/assets/867741/23172070/e201893a-f854-11e6-9c41-a15d7313fab0.png">

**Comment by ide** [comment]
This might be totally unrelated but I have seen leaks in the past (~ a year ago) when using frameworks instead of static libraries. Specifically the JSContext of the old RN bridge was not being totally cleaned up upon reload when using frameworks.

**Comment by haoziy** [comment]
@byoha the same issue;
I check memorny by Instruments @mkonicek 
![image](https://cloud.githubusercontent.com/assets/12541846/25334595/c5292e5a-2921-11e7-98d6-d5c69881a133.png)

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/memory-leak-when-opening-react-native-view-controller-in-ios

**Comment by drpiou** [comment]
I still have a same issue...

**Comment by MikeSilvis** [comment]
@hramos i just updated to the latest, and am still seeing our memory sky rocket. Please take a look at this
