### ISSUE TITLE
Set-class does not work right.

### ISSUE THREAD

**Issue by kapula6** [facebook/react-native#11966]
I tried to use Set-class to check are all values different in an array. Looks like there can be same values in Set-object but it should not be that way. Some of my code looks like this:

```
     var personIndex = []; 

      var length = Object.keys(Company.person).length; 

      var unique = new Set(); 

      for(var i = 0; i < 4; i++){

        personIndex[i] = [Math.floor(Math.random() * length)]

        if(unique.has(personIndex[i])){
          continue;
        }
        else{
        unique.add(personIndex[i]);
        }

      }
      console.log(unique.size)
      console.log(unique.values())
```

When this code is runned, `unique.size` is always 4, not lower when there is added values that already exist. `unique.values()` shows that there is sometimes same values. I think that `.add()` works but `.has()` doesn't. I strongly believe that Set-class is not fully supported in React-Native.

**Comment by janicduplessis** [comment]
We use a Set polyfill here https://github.com/facebook/react-native/blob/master/Libraries/vendor/core/Set.js. Could you test if it is being used in your case (log https://github.com/facebook/react-native/blob/master/Libraries/vendor/core/Set.js#L29)?

**Comment by kapula6** [comment]
How can I use it in my code? `var unique = require('Set');` ?

**Comment by kapula6** [comment]
I did my operation with a different way that didn't use Set-class. No problem anymore.

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
