### ISSUE TITLE
Taking old code reference in release mode

### ISSUE THREAD

**Issue by jitenderchand1** [facebook/react-native#11971]
When build the app in release mode it is not showing the latest code in the app, however it is working fine in debug mode.

**Comment by hramos** [comment]
Can you provide more details?

**Comment by jitenderchand1** [comment]
I am not what details I should posted here for the issue. For now I am attaching the screenshot for your perusal. 
![screen shot 2017-01-19 at 1 47 15 pm](https://cloud.githubusercontent.com/assets/19687185/22098811/5a4e0d12-de4e-11e6-8062-ca6e72a38c4b.png)

**Comment by hramos** [comment]
It's not really clear to me what problem you're describing here.

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
