### ISSUE TITLE
Tutorial - Images dont show up in iOS

### ISSUE THREAD

**Issue by lifeinafolder** [facebook/react-native#11974]
I was following the tutorial and noticed that the images dont load in iOS simulator.

Regular googling led me to http://stackoverflow.com/questions/38114325/cant-show-image-in-react-native which mentions that only https urls would work.

The sample data file `https://raw.githubusercontent.com/facebook/react-native/master/docs/MoviesExample.json` has image urls in http.

**Comment by hramos** [comment]
Good catch. Do you want to open a PR that fixes this?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/tutorial---images-dont-show-up-in-ios
