### ISSUE TITLE
react-native init hangs without any error 

### ISSUE THREAD

**Issue by nairicode** [facebook/react-native#11978]
OS: MAC
node: v7.4.0
npm: 4.1.1

react-native-cli: 2.0.1
react-native: n/a - not inside a React Native project directory

![screen shot 2017-01-19 at 12 07 57 pm](https://cloud.githubusercontent.com/assets/15065065/22098486/f7c3a606-de3f-11e6-9180-e5c568bb06ad.png)

**Comment by Lao-liu** [comment]
+1

**Comment by yorch** [comment]
In my case, it finishes installing packages using `yarn` but then it freezes (I've waited for more than 10 min):

```
(...)
├─ wrappy@1.0.2
├─ write-file-atomic@1.3.1
├─ ws@1.1.1
├─ xcode@0.8.9
├─ xmlbuilder@4.0.0
├─ xmldoc@0.4.0
├─ xmldom@0.1.27
├─ xtend@4.0.1
├─ y18n@3.2.1
├─ yallist@2.0.0
├─ yargs-parser@4.2.1
└─ yargs@6.6.0
✨  Done in 30.90s.
^C
$
```

**Comment by nairicode** [comment]
just update mac your system, or copy react-native project created from other OS and run for android or mac ...
