### ISSUE TITLE
npm link & react-native link 

### ISSUE THREAD

**Issue by 7ynk3r** [facebook/react-native#11975]
### Description

I'm developing a react native package to be consumed by my app. My goal is being able to test my package components directly in my app without having to run `npm install` for each change in my package. For that, I'd like to use `npm link ../my_package` so I can link an external folder with the sources, but this doesn't work with `react-native link` for native components.

This works if we use `npm install ../my_package` instead.

### Reproduction

1. Create a RN project
`react-native init app`
1. Clone any package with native components (i.e. react-native-device-info).
`git clone https://github.com/rebeccahughes/react-native-device-info.git`
1. Link the package to the app
`cd app; npm link ../react-native-device-info;`
1. Link the native components to the app.
`react-native link`

### Solution

Replace `3.` with  `cd app; npm install ../react-native-device-info --save;`

This is a workaround but isn't ideal given that we have to install everytime we make a change to the package.

### Additional Information

* React Native version: 0.40
* Platform: iOS & Android
* Operating System: MacOS

**Comment by 7ynk3r** [comment]
I found the problem with `npm link`.

`react-native link` is using `package.json` in the app directory to look for native libraries.

`npm link` will work if we add a dependency for package in our app `package.json`.

**Comment by pbruna** [comment]
Hi @7ynk3r 
Can you explain what do you mean when you said:

> npm link will work if we add a dependency for package in our app package.json, to help react-native link.

**Comment by 7ynk3r** [comment]
Hi @pbruna,

The problem is that `npm link` won't modify `package.json`. So, even when your package *will be* under `node_module` in your app, `react-native link` won't see it because it needs the package to be declared in `package.json`.

I don't think there's an easy solution to this problem unless `react-native link` looks under `node_module` for rn packages instead of `package.json`, which at first glance looks like a big change for a small reward. Small reward because you can simply declare your package in `package.json` after you've linked it using `npm link`.

**Comment by pawangiri** [comment]
Facing the same issue. Any solution?

**Comment by 7ynk3r** [comment]
Hi @pawangiri,

I'd recommend you to follow a structure similar to https://github.com/FormidableLabs/victory-native.
`npm link` didn't work well for me because of native dependencies. 

I hope it helps.
JM
