### ISSUE TITLE
AsyncStorage sometimes doesn't invoke its callback

### ISSUE THREAD

**Issue by ide** [facebook/react-native#1197]
If I repeatedly access AsyncStorage on a device, sometimes `getItem` never fulfills its promise. Haven't investigated this but noticed that sometimes neither my success nor error handlers on the promise are called.

**Comment by ide** [comment]
This seems to have gone away with one of the two big updates. Possibly was related to the bridge and not AsyncStorage specifically.

**Comment by papmodern** [comment]
Unfortunately, its steel persists! at least for me !!!
