### ISSUE TITLE
-[RCTRootContentView invalidate] is never called

### ISSUE THREAD

**Issue by ide** [facebook/react-native#1198]
It looks like it doesn't get reused so not causing problems. Just thought it'd be good to straighten out this code and either call it or no longer conform to RCTInvalidating.

**Comment by tadeuzagallo** [comment]
Thanks, it was an issue, but has been fixed internally, should be out soon.

**Comment by ide** [comment]
:+1:

**Comment by ide** [comment]
Merged in https://github.com/facebook/react-native/commit/92d7324f15196a8d17d51ab3e16bbec2bb85cf21#diff-9bdd6391cd866b37f84e7e9b5f276ff9R155
