### ISSUE TITLE
IOS: Application crash on release scheme

### ISSUE THREAD

**Issue by Moussawi7** [facebook/react-native#11984]
### Description

I already created a fresh react-native project, and it's working fine on android(debug/release) and ios(debug).

But when i switched to release scheme as described by [Facebook docs](https://facebook.github.io/react-native/docs/running-on-device.html) it crash on startup and throw the following exception:

>Make sure the packager is running or you have embedded a JS bundle in your application bundle.unsanitizedScriptURLString:((null)) 2017-01-17 21:59:18.720641 XXXX[332:53718] *** Terminating app due to uncaught exception 'RCTFatalException: No script URL provided.

Any idea about the cause of this issue?!

### Additional Information

* React Native version: 0.40
* Platform: IOS
* Operating System: MacOS
* Xcode: 8.0

**Comment by Moussawi7** [comment]
My issue has been solved by generating js bundle.
`react-native bundle --dev false --assets-dest ./ios --entry-file index.ios.js --platform ios --bundle-output ios/main.jsbundle`

**Comment by controversialUser** [comment]
https://stackoverflow.com/questions/43854369/no-bundle-url-present-error-with-react-native-ios-release-mode --> helped me a lot

**Comment by tirrorex** [comment]
This should be in the official documentation !!!!
