### ISSUE TITLE
TouchableOpacity can be slow to respond to touch while scrolling

### ISSUE THREAD

**Issue by jameslive** [facebook/react-native#11996]
I do not know why this happens exactly, but am able to force it under certain conditions.

### Description

When scrolling in the Safari mobile browser on IPhone devices (does not happen in the simulator), there seems to be some slowness to the initial touch while scrolling resulting in a choppy experience.  Maybe the best description is that it appears to be unresponsive to my initial touch for about 250-500ms making the scroll itself look detached from my finger with a kind of random scroll distance.

### Reproduction

I have spent time trying to simplify the reproduction of this issue, but the most reliable method of reproducing this is to embed views and TouchableOpacity elements something like the below example repeated 30-40 times..  The real cause I am still not certain because I have seen it happen under other types of conditions but this forces it to happen at least.

            <View>
              <Text>This is my first line of text for this repro</Text>
              <Text>This is my second line to repro this problem </Text>
            </View>
            <TouchableOpacity>
                <View>
                  <Text>This text seems to make the issue slightly worse, but images don't seem as impactful</Text>
                  <img src={logo} className="App-logo" alt="logo" />
                </View>
            </TouchableOpacity>

For comparison, you can replace TouchableOpacity with TouchableWithoutFeedback and see that there is definitely a difference in the scrolling experience.

### Additional Information

* React Native version: react-native@0.38.0
* Platform: IOS device only
* Operating System: IOS

**Comment by Jxcook** [comment]
Moving this to the right place in react-native-web, cannot close

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
