### ISSUE TITLE
Iconfont variable in Text cannot recognize?

### ISSUE THREAD

**Issue by AmusedMe** [facebook/react-native#11990]
I used an iconfont for a text's style, however, it doesn't recognize? Could you give some advices?

Here is the problem:
![image](https://cloud.githubusercontent.com/assets/19369983/22113223/849164b4-dea0-11e6-958f-c8fc2469c289.png)

`
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';

export default class tttt extends Component {
  render() {
    let b = "&#xe637;";
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          {b}
        </Text>
        <Text style={styles.welcome}>
          &#xe637;
        </Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontFamily:"iconfont",
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

AppRegistry.registerComponent('tttt', () => tttt);
`

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
