### ISSUE TITLE
Running on device should be possible

### ISSUE THREAD

**Issue by subtleGradient** [facebook/react-native#12]
Currently throws up a red screen complaining that it can't find localhost

**Comment by roman01la** [comment]
+1 for better way

**Comment by wesleyahall** [comment]
This should at least be documented on the website -- I'm sure it's going to confuse a lot of people initally until updated.  (react native rules!)

**Comment by freshteapot** [comment]
Under option 2).

Where exactly is the 'main.jsbunle' meant to be saved.
Have tried.
- top level.
- inside "AwesomeProject.xcodeproj"

"You'll have to add the downloaded file to the app binary":
Where is this? :)

**Comment by brentvatne** [comment]
@freshteapot - check this issue out: https://github.com/facebook/react-native/issues/240

**Comment by freshteapot** [comment]
To answer my own question:

"You'll have to add the downloaded file to the app binary":
Open Xcode -> Project (I will assume AwesomeProject)
Look in the folder Products, click "once" on 'AwesomeProject.app', look on the rightside and it should display "Full Path".

At this point, jump to the terminal, and navigate to the same directory.
Afterwards.
```
cd FULL_PATH
curl http://localhost:8081/index.ios.bundle -o main.jsbundle
```

Now at this point. You could do
```
curl http://localhost:8081/index.ios.bundle -o FULL_PATH/main.jsbundle
```

**Comment by freshteapot** [comment]
@brentvatne thank you!

**Comment by Rykka** [comment]
@freshteapot Thanks, It works~

**Comment by vjeux** [comment]
Now possible
