### ISSUE TITLE
WebView requestAnimationFrame not running on touch/scroll

### ISSUE THREAD

**Issue by zapkub** [facebook/react-native#12002]
Hi, I use WebView component to display some HTML/Javascript animation with scroll base inside React-native app.

The problem is it seem to stop running animationFrame on touch but everything is fine on iOS Safari.

Is there any workaround about this issue ? 

Thanks

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
