### ISSUE TITLE
TouchableHighlight above WebView: bizarre behaviour

### ISSUE THREAD

**Issue by miketheanimal** [facebook/react-native#12007]
### Description

I have a situation where I am rendering a TouchableHighlight above a WebView (using absolute positioning), like (simplified):

```javascript
  <View>
    <WebView source={{ html: somehtml }}>
    <TouchableHighlight style={ .... } onPress={ this.onPress }>
      <Text>Click Me</Text>
    </TouchableHighlight>
  </View>
```

Running a development build on an iPad, with the JS executing on the iPad: I do something that causes the above to render, and the WebView appears with the expected content. If I then tap the button, the application freezes for maybe 30 seconds, before I see any response. If I replace the WebView with (say)

```javascript
  <Text>Hello</Text>
```

then the response is immediate, so its not a problem with the onPress handler.

If I run exactly the same code in an emulator (specifically iPhone6/iOS9.3) then it behaves perfectly with the WebView. If I run on the iPad but debugging the JS (which I understand runs the JS inside Chrome) then again it works OK.

Now here's the really bizarre bits. The onPress handler results in an View which overlays most of the display, containing a WebView which will render the same content only larger (it's a graph generated using Chart.js). This has an absolutely positioned TouchableHighligh which is used to close the overlay. Taping this works immediately on both the iPad and the emulator. If I then tap the ClickMe a second time, the overlay appears at once. In fact, it will continue to work immediately, until I recreate the original with some different content in the WebView; then it reverts to slow-the-first time, immediate thereafter. Duh?

### Reproduction

I've not tried this is RNPlay or elsewhere because it looks to be environment sensitive?

### Solution

I can move the button elsewhere, perhaps :) Other <TouchableHighlights> that don't overlay the <WebView> are not affected.

### Additional Information

* React Native version: 0.40.0
* Platform: iOS, not tested on Android
* Operating System: OS/X El Capitan, on a Mac Mini

Hope that makes sense?
Regards
Mike

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
