### ISSUE TITLE
Support for Rich Notifications iOS 10

### ISSUE THREAD

**Issue by shercoder** [facebook/react-native#12008]
Are there any plans for adding support for Rich Push to `PushNotificationIOS`?

**Comment by ericvicenti** [comment]
There aren't any plans for this yet. If there was anything planned it would appear in the roadmap: https://github.com/facebook/react-native/wiki/Roadmap

Feel free to post this on Product Pains so the community can vote on it and help the core team prioritize!

https://productpains.com/product/react-native

**Comment by shercoder** [comment]
Here is the Product Pains post if anyone lands here. Please make sure to up vote.
https://productpains.com/post/react-native/support-for-ios-10-rich-push-notifications
