### ISSUE TITLE
Listview overlflow hidden on android

### ISSUE THREAD

**Issue by magrinj** [facebook/react-native#12003]
### Description

When you apply `style` to a `ListView` in android with the property `overflow` set to `hidden`, the ListView can't be scrollable, the problem happen only on Android devices.

### Reproduction

Just create a `ListView` and apply the style `overflow: 'hidden'` to it, then run it on Android.

### Additional Information

* React Native version: `0.36.1`
* Platform: `Android`
* Operating System: `macOS Sierra`

**Comment by radko93** [comment]
Please check if still occurs on latest RN version, older versions are not supported.

**Comment by hramos** [comment]
Closing as ListView is deprecated in 0.43. Use FlatList.
