### ISSUE TITLE
RNGoogleSignin.h "RCTBridgeModule.h" file not found

### ISSUE THREAD

**Issue by zizizi17** [facebook/react-native#12006]
Hello guys
I have the error because of which i cannot run my project - RNGoogleSignin.h "RCTBridgeModule.h" file not found

Help me please
Use version of RN 0.39.2

**Comment by rmevans9** [comment]
Hey @zizizi17! RNGoogleSignin.h is not a part of React-Native but a bit of digging it seems it is a part of https://github.com/devfd/react-native-google-signin

I would recommend opening an issue over on that repo!

**Comment by rmevans9** [comment]
@facebook-github-bot close
