### ISSUE TITLE
TypeError: this._haste.on is not a function

### ISSUE THREAD

**Issue by coolegos** [facebook/react-native#12019]
when ./packager/packager.sh
```
this._haste.on is not a function
TypeError: this._haste.on is not a function
    at /Users/Egos/Desktop/react/react-native-master/packager/react-packager/src/node-haste/index.js:217:19
    at process._tickCallback (node.js:377:9)
```
first my node version is v5.0.0, i update to v7.4.0, it is no use.
can someone encounter this problem?

now:
npm:4.1.1
node:7.4.0

**Comment by coolegos** [comment]
i am sorry. i forgot `npm install`.

**Comment by arifmahfudin** [comment]
How to solve this error. I have same error
`TypeError: this._haste.on is not a function
    at DependencyGraph (C:\Projects\trackvees-mobile\node_modules\metro-bundler\src\node-haste\DependencyGraph.js:279:508)`
