### ISSUE TITLE
TextInput preventDefault

### ISSUE THREAD

**Issue by ranyefet** [facebook/react-native#1202]
Hello,

I'm trying to do some custom validation on TextInput.
I'de to limit the max chars to 4 characters. I've tried the following:
```js
validate(event) {
    if( event.nativeEvent.text.length > 4 ) {
      event.preventDefault();
      return false;
    }
    this.setState({pinCode: event.nativeEvent.text});
    return true;
  }

<TextInput
  style={styles.pinInput}
  placeholder="PIN Code"
  value={this.state.pinCode}
  keyboardType="number-pad"
  onChange={this.validate.bind(this)}
/>
```

Your help is appreciated.

**Comment by stubbornleaf** [comment]
Checkout the controlled prop [here](https://github.com/facebook/react-native/blob/master/Libraries/Components/TextInput/TextInput.js#L269). Setting it to true will make your case work.

**Comment by ranyefet** [comment]
Thanks but the input started acting weird.
Is there a better way to do form validation?

**Comment by vkurchatkin** [comment]
I think the answer is no, since everything is asynchronous and when you receive `onChange` event native view has already accepted new value, so it's too late to prevent it.

**Comment by ide** [comment]
The controlled prop is the semantically correct way to do things but it's not usable from a UX perspective. You can call `setNativeProps` on a ref to the TextInput to directly set its value if desired.
