### ISSUE TITLE
Changes in node_modules/react-native/ files does not appear

### ISSUE THREAD

**Issue by dabit1** [facebook/react-native#12021]
Hi people,

I modified the file `node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/modules/location/LocationModule.java` to fix a problem related to errors response. However when I reload my app always works just like in the past. It seems that react-native ignore the changes.

I tried to reboot my computer, reinstall the app, clear cache from packager, run `react-native run-android` and run `watchman watch-del-all` but the problem still persists.

Can anyone help me please? It is a major problem, 

Many thanks!

**Comment by ericvicenti** [comment]
Have you tried re-building the app with `react-native run-android`?

**Comment by dabit1** [comment]
Hi @ericvicenti !

Yes, I've tried it, but the problem still persists :(

Thanks

**Comment by pcguru** [comment]
Try cleaning the java build folder. Might help?
```
cd android
gradlew clean
```

**Comment by Exilz** [comment]
I think it's much more complicated than that. You need to actually re-build react-native from the source.
See : https://facebook.github.io/react-native/docs/android-building-from-source.html

**Comment by dabit1** [comment]
@Exilz you are right. Many thanks!!!!
