### ISSUE TITLE
setting ProgressBarAndroid color prop on Platform Version < 23 results in full progress bar regardless of progress value

### ISSUE THREAD

**Issue by brcarey** [facebook/react-native#12023]
### Description

Setting color and progress props for ProgressBarAndroid results in the bar being displayed at 100% regardless of progress value

### Reproduction

`<ProgressBarAndroid color='red' progress={0.25} indeterminate={false} styleAttr='Horizontal' />`

### Additional Information

* React Native version: 0.40
* Platform: Android platform < 23
* Operating System: Ubuntu 16.10

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
