### ISSUE TITLE
Orientation Detection in UI Explorer OrientationChangeExample

### ISSUE THREAD

**Issue by Kielan** [facebook/react-native#12026]
### Description

I am trying to figure out how the orientation detection is working in the UI Explorer OrientationChangeExample. I see that when running the app orientation change between layout to portrait is functional. However the values in the OrientationChangeExample do not work/update. I am hoping there is some kind of documentation or to be pointed in the code.

I see that here

https://github.com/facebook/react-native/wiki/Roadmap

there is mention of changing on layout/orientation this month

Please do not close this issue, because this is a bug in the OrientationChangeExample

### Reproduction

to reproduce just run the sample project

### Solution

Simply point where in the UIExplorer orientation is being handled, as well as fix the UIExplorer example.

### Additional Information

* React Native version: current
* Platform:  MacOS simulator and iOS

**Comment by ericvicenti** [comment]
Cc @mmmulani

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
