### ISSUE TITLE
some file not found

### ISSUE THREAD

**Issue by coolegos** [facebook/react-native#12024]
when run Examples 2048.
```
Libraries/Network/RCTNetworkTask.m:10:9: 'React/RCTLog.h' file not found
Libraries/Text/RCTRawTextManager.h:10:9: 'React/RCTViewManager.h' file not found
```
i know it change in [0.40.0](https://github.com/facebook/react-native/releases/tag/v0.40.0). but how to solve it?

**Comment by yimingtang** [comment]
It's clear that you should use `#import <React/RCTLog.h>` instead of `#import "React/RCTLog.h"`.
It's **a breaking change** in version 0.4.0.

**Comment by coolegos** [comment]
@yimingtang  i use #import <React/RCTLog.h>.

**Comment by laclance** [comment]
Same issue here

**Comment by CapitanRedBeard** [comment]
Same

**Comment by nickgeorgiou** [comment]
Same. It's really frustrating that I can't even get the examples from the official developer working

**Comment by laclance** [comment]
I solved by creating a new project and copying ios project accross

**Comment by ericvicenti** [comment]
The samples have been removed from the core RN repo. Feel free to publish standalone example apps, and we can curate a list of them for the website.
