### ISSUE TITLE
React Native ListView render list items incorrectly when list is scrolled fast

### ISSUE THREAD

**Issue by srl3g** [facebook/react-native#12044]
### Description

We need a line chart for displaying up to 80K data points. Data is obtained from the server in real-time and line chart needs to be updated as soon a data point is received from the server. Since we have to display up to 80K data, we used React Native ListView with horizontal scrolling to display data. This helps us in lazy loading data points when the user scrolls through the chart. 

![screenshot_20170123-231911](https://cloud.githubusercontent.com/assets/1297234/22215824/c7842c1e-e1c2-11e6-8ecf-08715a799e07.png)

Everything works fine, but the problem is when we scroll the list fast, ListView might show a blank list or might show some weird patterns on the screen.

![screenshot_20170123-230259](https://cloud.githubusercontent.com/assets/1297234/22215496/9691d42c-e1c1-11e6-87d3-a5e14cee1437.png)

### Reproduction

Install this APK or install using source code below. [app-release.apk.zip](https://github.com/facebook/react-native/files/724497/app-release.apk.zip)

Source: https://github.com/srl3g/React-Native-Lazy-loading-real-time-line-chart-demo

Press Realtime button and try to scroll the list fast after some data is populated. 

### Solution

Unknown. Need help.

### Additional Information

* React Native version: 0.40
* Platform: Android, not tested on iOS
* Operating System: Linux

**Comment by hramos** [comment]
Closing as ListView is deprecated in 0.43. Use FlatList.
