### ISSUE TITLE
<React/RCTLog.h> <React/RCTBridge.h> are not found since I upgrade react-native to 0.40

### ISSUE THREAD

**Issue by clovs** [facebook/react-native#12042]
Hello guys,

<React/RCTLog.h> <React/RCTBridge.h> are not found since I upgrade react-native to 0.40
Sometimes also  <React/RCTEventEmitter.h> is not found.

I tried 
_"react-native-git-upgrade"
_"rm -rf node_modules/"
_"watchman watch-del-all"
_"rm -fr $TMPDIR/react-*"
_"npm i"

But the build still Fail :-(

**Comment by CapitanRedBeard** [comment]
In addition to those above I will sometimes get `React/RCTViewManager.h` not found in RCTRawTextManager.h on line 10 `#import <React/RCTViewManager.h>`.
This is confusing since I changed all of my RCT includes to have the `<React/` prefix, but these errors seem to be occurring in the React library. 

Could this possibly be 3rd party library related? The errors never occur in a dependency library. Or possibly `react-native-git-upgrade` is not fully changing everything. I've tried to get this working with a manual upgrade and still have troubles

Did all the steps above plus `react-native link` still nothing. Also deleted DerivedData cache.
 
react-native: 0.40.0
react: 15.4.2
react-native-cli: 2.0.1
npm: 3.10.7

**Comment by laclance** [comment]
same issue here

**Comment by clovs** [comment]
In addition on RCTLocationObserver.m:10
10:9: fatal error: 'React/RCTEventEmitter.h' file not found
#import <React/RCTEventEmitter.h>
        ^
1 error generated.
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1

Hope you can help us :-)
Regards,

**Comment by badasve** [comment]
same problem here, this issue gives some advice but nothing worked for me https://github.com/facebook/react-native/issues/11721

**Comment by clovs** [comment]
Hello guys,

I solved it by disabling parallelization but I don't know if it's a good thing. 
The packager is slow enough, and I think it's slow down xcode too. 
I really dont think this should be turned off. But you can try by doing this:
(From badasve Source: https://github.com/facebook/react-native/issues/11721)

- In Xcode, go to the project scheme (Product -> Scheme -> Manage Scheme -> double click your project).

- Click on the 'Build' option at the left pane.

- Uncheck 'Parallelize Build' under Build Options.

- Then in Targets section, click '+' button then search for 'React'. Select it and click 'Add'.
'React' should now appear under Targets section. Click and drag it to the top so that it will be the first item in the list (before your project).

- Clean the project and build.

Hope someone can explain us.

**Comment by CapitanRedBeard** [comment]
I've followed the above advice ^ and still not getting anything. I believe that fix aims to disable parallelization so the React package can compile first. However it is not solving the problem for me. @oblador If this is a bug do we have a ticket I can refer to?

**Comment by CapitanRedBeard** [comment]
@badasve  What are your iOS dependencies?

**Comment by LoopIndigo** [comment]
Try the following:

1.  Clean (`cmd+shift+K`)
2. Build core React - select `React` as the scheme in Xcode and build it (`cmd+B`)
3. Build the library that is failing (e.g. `RCTText`).
4. Build your app.

**Comment by badaz** [comment]
I was upgrading from 0.33, so I settled on using to 0.39 for now, I guess I'll wait until this headers change is not so new anymore

**Comment by clovs** [comment]
Thanks LoopIndigo!

Now I can compile on Xcode, but when I compile from the Terminal with 
"react-native run-ios"
The Build still Fail

** BUILD FAILED **

The following build commands failed:
	CompileC PATH/ios/build/Build/Intermediates/RNGL.build/Debug-iphonesimulator/RNGL.build/Objects-normal/x86_64/RCTConvert+CaptureConfig.o RCTConvert+CaptureConfig.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by LoopIndigo** [comment]
@clovs glad to hear it works. I don't use `run-ios` and just stick to Xcode (my reason was more around the capability of `run-ios` to handle projects in sub-directories) so I can't be much help there.

Are you fine with sticking to XCode or is `run-ios` a blocker for you?

**Comment by clovs** [comment]
Yeah I'm fine for now with the Xcode
Thanks again :-)

**Comment by OpakAlex** [comment]
@clovs thanks you man!

**Comment by clovs** [comment]
не за что )))

**Comment by OpakAlex** [comment]
@clovs сколько же ты времени потратил на магический фикс с порядком компиляции?))))

**Comment by clovs** [comment]
With the help of @LoopIndigo @badasve in two days the issue was solved.

**Comment by OpakAlex** [comment]
;)

**Comment by rpylipow** [comment]
@LoopIndigo's solution worked for solving the majority issues - Thanks! 

My `React` scheme builds without any issues, but I'm seeing an error regarding `RCTEventEmitter` within React.

<img width="1272" alt="screen shot 2017-01-25 at 12 01 34 pm" src="https://cloud.githubusercontent.com/assets/1540886/22302862/4df41fa0-e2f6-11e6-908e-c934647880ea.png">

Any ideas?

**Comment by ms88privat** [comment]
Have the same problems with 41-rc. This issue should be open!

https://github.com/facebook/react-native/issues/12077

**Comment by rh389** [comment]
@rpylipow Make sure you don't have any `#import "RCTEventEmitter.h"` directives either in your own project or in any third-party native modules you might be using (inside `React` itself is ok). Change them to `#import <React/RCTEventEmitter.h>`.

That error appears when a header is being imported in both different ways somewhere across the build.

**Comment by Msspl-PrashenjeetRoy** [comment]
@LoopIndigo what do you mean by 3rd no point:
Build the library that is failing (e.g. RCTText). (?)

My was failing in AppDelegate.m file : 
#import "AppDelegate.h"

#import "RCTBundleURLProvider.h" (file not found)
#import "RCTRootView.h" (file not found)

**Comment by clovs** [comment]
For my part, I just recreated a new project with 0.40.
copy and past all src/, reinstall all third party libraries.
After that all errors was out.

I suggested you to do the same, to resolve this issue faster.

**Comment by Msspl-PrashenjeetRoy** [comment]
ok I will follow your suggestion but it really taking time again setting up all libraries again and including fonts etc :( ... but is there any solution with 0.39.0 version. ????? Now I have 0.39 version.

**Comment by freakinruben** [comment]
For me, after days of struggling, several things were required to get 0.40/0.41 working:

1. As described in [this comment](https://github.com/facebook/react-native/issues/11721#issuecomment-272078287), make sure **Dead code stripping** is set to **No** for all build targets

2. Make sure that in your release-schema in the run-job, the **Build Configuration** is set to **Debug** (not release or whatever)

3. Remove these headers from `HEADER_SEARCH_PATHS` in all your build-configurations:
    - `"$(SRCROOT)/../node_modules/react-native/React/**",`
    - `"$(SRCROOT)/../node_modules/react-native/ReactCommon/**",`

**Comment by nim23** [comment]
@freakinruben we have build schemes that are `Debug-*`. Would that be an issue from what you have figured out. Thanks.

**Comment by freakinruben** [comment]
@nim23 No it shouldn't be, I only have one debug schema but multiple release schemes, and that seems to work well

**Comment by Msspl-PrashenjeetRoy** [comment]
Got a solution. My is working please follow these comments https://github.com/evollu/react-native-fcm/issues/201

**Comment by onpaws** [comment]
Upgrading to 0.40+ has been a really frustrating experience.
I tried 0.35>0.41, including ~6 native modules all which claim 0.40+ compatibility.
In the end while I got the Xcode project to compile, when actually running on Simulator/Android the Packager would no longer import static images that had worked previously, e.g.
`<Image source={require('path/to/image.png')}>`
- RedBox'd out. Tried clearing watchman cache, reinstalling node_modules, etc. nothing.

I don't have the time to waste on this - disappointed & sticking with 0.39 for now.

**Comment by rohitgoyal** [comment]
I have tried everything as well and nothing makes these issues go away permanently. :-/
This is the worst update of react-native with much support for upgradation.

**Comment by Msspl-PrashenjeetRoy** [comment]
I got solution.
I solved this issue with this provided solution:

1- opened workspace file before opening close everything.

2- added pod file in manage scheme suggested by :https://stackoverflow.com/questions/40358719/framework-not-found-googletoolboxformac

3- also i followed this suggestions too: http://stackoverflow.com/questions/9458739/ld-warning-directory-not-found-for-option

4-I also updated pod update.

5- Clean and build it's working now.

**Comment by freakinruben** [comment]
@rohitgoyal Did you try [this solution](https://github.com/facebook/react-native/issues/11813#issuecomment-273279257)? It fixed issues for me with archiving a release with a different build-name than 'release'

**Comment by RajanPN** [comment]
I've finally fix the this issue with this solution 👍 
To solve the issue, you have to do the following:

In Xcode, go to the project scheme (Product -> Scheme -> Manage Scheme -> double click your project).
Click on the 'Build' option at the left pane.
Uncheck 'Parallelize Build' under Build Options.
Then in Targets section, click '+' button then search for 'React'. Select it and click 'Add'.
'React' should now appear under Targets section. Click and drag it to the top so that it will be the first item in the list (before your project).
Clean the project and build.

**Comment by geekvijay** [comment]
@RajanPN You saved my day :)

**Comment by onpaws** [comment]
Just wanted to follow up to how I resolved my previous issue.
My project folder had a '+' in the path, and after a lot of frustration on a hunch I tried moving to a path with only 'normal' Roman characters.
Before:
`/Users/me/projects/+client/app/`
After:
`/Users/me/projects/client/app/`

This actually fixed the Packager issues mentioned [above](/facebook/react-native/issues/12042#issuecomment-278560357).
Just sharing in case it helps someone else.

**Comment by ezos86** [comment]
@clovs wtf - not sure why that worked, I literally added a library, and then removed it but still had issue, before I added that library, everything was fine. I had to do this work around you added after adding library.

WTF is wrong with React-Native?

**Comment by arun542** [comment]
I tried all the solutions, but nothings work, i am using RN0.44, apps works fine on simulator as well as on phone with release config. But fails to archive.

**Comment by agrass** [comment]
@arun542 I was with same problem only in archive and I solved adding React as target dependency on build phases settings of your project

**Comment by herarya** [comment]
@RajanPN thanks bro, work now

**Comment by RajanPN** [comment]
@geekvijay @herarya Good to know that it worked!

**Comment by arun542** [comment]
@agrass i tried that also did not work. In the end i had to recreate the project from scratch and i worked automatically. Something was screwed up in that project.

**Comment by andpor** [comment]
Same issue - app builds fine under Simulator but archiving is throwing all kinds of .h not being found from RN package...

**Comment by kyle-ssg** [comment]
I have a feeling a lot of people are getting into this situation by creating a new scheme pointing to production. Instead of selecting new scheme from xcode make sure you duplicate your current scheme.


instead of creating a new scheme for production do the following:

Goto edit scheme > manage schemes > click the cog after selecting your scheme and click duplicate scheme

**Comment by aamalik** [comment]
Tried everything that is mentioned above but still does not work. I am using 0.52. 
Its my second day with react-native and I am just gonna keep on hustling till I fix it. 
Why are there so many problems with react-native?

**Comment by aamalik** [comment]
https://github.com/facebook/react-native/issues/17027

The above issue is actually my issue. Somebody has submitted a pull request

**Comment by russelh15** [comment]
My issue was that I was building on a custom Schema, in my case, "Staging". I had to change the Per-Configuration Build Products Path and the Per-configuration Intermediate Build Files Path to use the "Release" paths instead of the "Staging" path.

If you're project contains Pods, you will need to adjust these values in the Pod project as well as change the PODS_CONFIGURATION_BUILD_DIR config for that custom schema so that it matches the Release schema

**Comment by WundrApp** [comment]
Hello Guys, 

I just updated to RN52 from RN38, solved all of my RCT includes to have the <React/ prefix, and removing all references to react-native in third party modules and now I'm stuck with this issue.

I have a 'RCTBridge+Private.h' file not found when trying to build.

I tried updating to ^2.2.6, unlink and re-link but still not working.

Has anyone been facing he same issue ? 

Thanks

**Comment by n1ru4l** [comment]
@russelh15 Thank you so much! I do not know if this is the ideal solution, however having just spent a half day getting things working I am fine with this.

**Comment by DavitVosk** [comment]
I tried deleting node-modules and installing packages back and it worked. Hope this will help to someone else :)

**Comment by nuravdhiman** [comment]
I did not go through all the comments, but this might help some.
Go to `Product -> Scheme -> Edit Scheme...(at the bottom)`  or Press `⌘ + shift + ,` i.e. `⌘ + <`
Now go to Build section on the left and:

1.  Uncheck **Parallelize Build**
2.  Add **React** in targets.
3. Make sure to drag and drop **React** above your project in targets( so that it builds first ).

Hope this helps.

**Comment by unicornRainbows** [comment]
React-native ...

**Comment by unicornRainbows** [comment]
I do <3 you but sometimes you make me feel crazy...

**Comment by robertobrogi** [comment]
I have the same problem.... :( 'React/RCTBridge.h' file not found with expo kit 26 and react-native-beacons-manager
