### ISSUE TITLE
undefined Linking

### ISSUE THREAD

**Issue by zabojad** [facebook/react-native#12045]
### Description

I 'm getting `undefined is not an object (evaluating '_react.Linking.canOpenURL')` when trying to use `Linking` on iOS. I tried with LinkingIOS but it crashes the same way.

I have checked if LinkingIOS is correctly linked and it is the case. I've even re-linked it, restarted both xcode and the simulator but I'm still getting this error.

### Reproduction

I cannot reproduce it on rnplay.org

### Solution

No solution found.

### Additional Information

* React Native version: "react-native": "0.40.0",
* Platform: iOS simulator
* Operating System: MacOS

**Comment by ericvicenti** [comment]
Does this happen on a fresh project? Without knowing more, I'm afraid there may not be enough info provided to find the problem.

Also, can you run the following command to report the various versions of your software?

```
watchman --version && yarn --version && node --version && sw_vers -productVersion
```

Also, what version of iOS are you testing on?

**Comment by zabojad** [comment]
Hi @ericvicenti and thank you for trying to help. Here is what I get with this command:
```
$ watchman --version && yarn --version && node --version && sw_vers -productVersion
4.7.0
-bash: yarn: command not found
```
Now without yarn:
```
$ watchman --version && node --version && sw_vers -productVersion
4.7.0
v6.9.4
10.11.6
```
I'm testing on iPhone 5 simulator (iOS 9.3).

I've created a new project with nothing else than a call to the `Linking` API and it works. What could be broken in my initial project and how could I fix it.

**Comment by ericvicenti** [comment]
Its hard to know what broke in your project. Maybe you can compare your customized project with a fresh one and see what might cause the breakage?

**Comment by zabojad** [comment]
OK, I've found the problem. I was importing Linking from 'react' instead of 'react-native'. Sorry for the dumb issue post...
