### ISSUE TITLE
[Touchable] Scrolling a native UIScrollView triggers `onPress`

### ISSUE THREAD

**Issue by samwize** [facebook/react-native#12049]
### Description

I embedded a `TouchableOpacity` in an iOS `UIScrollView`.

When I scroll the `UIScrollView` starting with my finger on the `TouchableOpacity`, scroll a distance then lift my finger, `onPress` occurs. It should not have hit `onPress` when scrolling.

Related issue: #3452 @majak

### Reproduction

Embed a `TouchableOpacity` in a native `UIScrollView`.

Scroll with finger on the `TouchableOpacity`, and lift up.

### Solution

Cancel `Touchable` event when scrolling.

### Additional Information

* React Native version: 0.38.1
* Platform: iOS
* Operating System: MacOS

**Comment by shergin** [comment]
Duplicates #3280.
This issue was fixed in c68a708 a week ago. 😃  Right now you can use workaround discussed in #3280 though.

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
