### ISSUE TITLE
Ability to add image to NavigationBar

### ISSUE THREAD

**Issue by soheil** [facebook/react-native#1204]
I want to be able to add an image here:

![screen shot 2015-05-08 at 11 34 05 am](https://cloud.githubusercontent.com/assets/287288/7543026/43c50bd0-f576-11e4-9186-30bd8c5eafef.png)

as such:
![ios simulator screen shot may 6 2015 5 23 48 pm](https://cloud.githubusercontent.com/assets/287288/7543030/45e68e20-f576-11e4-9111-e2e9a0d7657b.png)

**Comment by graemefunk87** [comment]
I'm pretty sure this component can handle what you need... https://github.com/Kureev/react-native-navbar

**Comment by iostalk** [comment]
Maybe

**Comment by brentvatne** [comment]
This seems to be related to #1219 - @soheil you will need to use the `Navigator` component and create your own navbar component (at its most basic, just a view with some height and a background color / image inside, or use something like the react-native-navbar component mentioned above).

**Comment by sau123** [comment]
@brentvatne, unable to open up the above link.

**Comment by anirudh24seven** [comment]
@sau123 I guess the updated links are:

https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/Navigator/NavigationBarSample.js#L79-L85

https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/Navigator/NavigationBarSample.js#L148-L153

**Comment by G2Jose** [comment]
@anirudh24seven the links you mentioned do not work (anymore)

**Comment by smekal** [comment]
@anirudh24seven : links doesn't work :(
