### ISSUE TITLE
[0.41] Commits to cherry pick into stable

### ISSUE THREAD

**Issue by grabbou** [facebook/react-native#12058]
List of fixes to cherry-pick

CC: @oblador

**Comment by oblador** [comment]
https://github.com/facebook/react-native/commit/8d2a034f9c18988a6a63726767bddecd0d02424d Fix sizing of container with child overflowing parent

**Comment by ptomasroos** [comment]
If any podspec user would like to run 0.41 i suggest this is included since it breaks 0.41 https://github.com/facebook/react-native/commit/6e9fe3707a8701c0d2910f96bfb053e8bbe67c4a

**Comment by rh389** [comment]
The iOS release build of a new (`react-native init`) project is broken without https://github.com/facebook/react-native/commit/e0c3d56d3a5dcc68c1a7585275a051d781ade914.

**Comment by oblador** [comment]
Noticed that the RC that went out yesterday didn't have these commits. Do we want to release these directly into the final release?

**Comment by grabbou** [comment]
We released stable. RC you referring to was released by @mkonicek and included fixes he needed for internal works.

**Comment by robinkam** [comment]
@grabbou Please cherry-pick the fixes for this issue: #11809 into 0.41. Thanks a lot.
