### ISSUE TITLE
Error running react-native run-android

### ISSUE THREAD

**Issue by laclance** [facebook/react-native#12055]
My app was working fine. It still works running through android studio. 
If android studio is not used, react-native run-android produces this error:

(node:1808) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'message' of undefined
(node:1808) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**NOTE:** I also had the same error on Linux, I posted to StackOverFlow with no success: http://stackoverflow.com/questions/41698161/unable-to-run-app-on-android-device-linux-ubuntu

* React Native version: 0.40.0 and 0.39.2
* Platform: Android: Nexus 5 (AVD - API 23) and Samsung S4 (Real device - API 21)
* Operating System: macOS Sierra 10.12.2

**Comment by Ananasr** [comment]
Hello,
I have the same problem and I fix it with `chmod +x android/gradlew`
Bye !

**Comment by laclance** [comment]
Yes that fixed it thank you so much
