### ISSUE TITLE
HERE MAP implementation for react native.

### ISSUE THREAD

**Issue by thundenilla** [facebook/react-native#12050]
Is there any way for me to implement here map for react native? I havent found any library or example for implementing this HERE api . Thank you

**Comment by ide** [comment]
Please see https://facebook.github.io/react-native/docs/native-modules-ios.html and https://facebook.github.io/react-native/docs/native-modules-android.html for exposing custom native modules to React Native. If you get stuck this is the type of project hiring a contractor might be good for.
