### ISSUE TITLE
If statement not compiling correctly - being wrapped in parentheses and append with `!`

### ISSUE THREAD

**Issue by dwilt** [facebook/react-native#12052]
### Description
My `if` statement is getting wrapped by parentheses and appended with a  `!`. I first thought to post this as an issue on [Babel](https://github.com/babel/babel/issues) but I'm unable to reproduce it on their [sampler](https://babeljs.io/repl/) and since they don't have a `react-native-preset` as one of the options, I can't completely verify it's them.

My ES6 code:
```javascript
const [{ updated_at: newAuthorUpdatedAt }, { updated_at: newStoryUpdatedAt }] = await Promise.all([
    fetchAuthorLastUpdatedDate(authorId),
    fetchStoryLastUpdatedDate(id)
]);

if ((storyUpdatedAt !== newStoryUpdatedAt) || (authorUpdatedAt !== newAuthorUpdatedAt)) {
    await removeDownloadedStory(story);
    dispatch(removeStory(story.id));

    return download();
}
```
Here's the ES5 code that it compiles to:
```javascript
newAuthorUpdatedAt = _ref2[0].updated_at;
newStoryUpdatedAt = _ref2[1].updated_at;
if (!(storyUpdatedAt !== newStoryUpdatedAt || authorUpdatedAt !== newAuthorUpdatedAt)) {
    _context12.next = 20;
    break;
}
```
It completely changes my logic by wrapping the entire statement in `!(...)`. I can't figure out for the life of me why it's doing that. I tried changing the `||` to a `&&` and the comparisons to `===`:
```javascript
if (!(storyUpdatedAt === newStoryUpdatedAt && authorUpdatedAt === newAuthorUpdatedAt)) {
    _context12.next = 20;
    break;
}
```
and it outputs:
```javascript
if (!(!(storyUpdatedAt === newStoryUpdatedAt && authorUpdatedAt === newAuthorUpdatedAt))) {
    _context12.next = 20;
    break;
}
```
it just rewraps everything again in a `!(...)`. My workaround is the following hack haha:
```
if ((storyUpdatedAt === newStoryUpdatedAt) && (authorUpdatedAt === newAuthorUpdatedAt)) {
    await removeDownloadedStory(story);
    dispatch(removeStory(story.id));

    return download();
}
```
because it wraps it and the logic is correct then.

### Reproduction
I just tried to do a brand new project via `react-native init` using the latest react native and I can't reproduce it there. Not sure what to do about that.

### Solution
The code doesn't wrap an extra parentheses and `!` around the `if` expression

### Additional Information

* React Native version: `0.37.0`
* Platform: `iOS` (didn't test Android but assuming it's there too)
* Operating System: `MacOS`
```
"babel-core": "6.4.5",
"babel-eslint": "7.1.1",
"babel-jest": "9.0.3",
"babel-preset-react-native": "1.5.6",
```

**Comment by dwilt** [comment]
An update.. I tried putting a console log inside of the `if` and and it gets pushed outside of it. Could this have to do with the `await`ed Promise before it maybe?

ES6:
```javascript
if ((storyUpdatedAt === newStoryUpdatedAt) && (authorUpdatedAt === newAuthorUpdatedAt)) {
    console.log('fetching!');
    await removeDownloadedStory(story);
    dispatch(removeStory(story.id));

    return download();
}
```
ES5 Output:
```javascript
if (!(storyUpdatedAt === newStoryUpdatedAt && authorUpdatedAt === newAuthorUpdatedAt)) {
    _context12.next = 21;
    break;
}
console.log('fetching!');
_context12.next = 17;
return regeneratorRuntime.awrap(removeDownloadedStory(story));
```
How messed up is this?

**Comment by ide** [comment]
Is this actually causing problems with your app? Reading through what you've posted, it looks like the program just bails out early when it passes the inverted if-clause.

**Comment by dwilt** [comment]
It seemed to be doing that and it was causing a problem. I moved out a lot of the functions into their own (which they should've been anyway) and I'm not running into the issue anymore.
