### ISSUE TITLE
Duplicate module name error

### ISSUE THREAD

**Issue by jy1989** [facebook/react-native#12051]
### Description
sometimes the cache files make build failed
![image](https://cloud.githubusercontent.com/assets/1291756/22234304/1fa79510-e232-11e6-97de-6b84a24c4e61.png)

and also few files appear at the root after build and I dont konw what's that
![image](https://cloud.githubusercontent.com/assets/1291756/22234343/69adae24-e232-11e6-9788-e84fd16fbcac.png)

### Solution

delete react-native-packager-cache-xxxxxxx folder

### Additional Information

* React Native version: 0.4
* Operating System: MacOS

**Comment by ericvicenti** [comment]
I think this is the same as #12078

Also, the issue may be related to mega issue https://github.com/facebook/react-native/issues/4968
