### ISSUE TITLE
TabBarIOS does not handle rotation correctly

### ISSUE THREAD

**Issue by timfpark** [facebook/react-native#1206]
When I rotate my phone with a TabBarIOS element, the content of the tab is squeezed down into a square size and the Tab Bar does not recover when reoriented back to the original orientation.  Either orientation works at initial launch but breaks on orientation change.

Here is the tab bar JSX 

    <TabBarIOS>
        <TabBarIOS.Item
          icon={{uri:'featured'}}
          selected={this.state.selectedTab === 'map'}
          onPress={() => {
            this.setState({
              selectedTab: 'map',
            });
          }}>
          <Map />
        </TabBarIOS.Item>
        <TabBarIOS.Item
          icon={{uri:'search'}}
          selected={this.state.selectedTab === 'search'}
          onPress={() => {
            this.setState({
              selectedTab: 'search'
            });
          }}>
          <Search />
        </TabBarIOS.Item>
        <TabBarIOS.Item
          icon={{uri:'recents'}}
          selected={this.state.selectedTab === 'timeline'}
          onPress={() => {
            this.setState({
              selectedTab: 'timeline'
            });
          }}>
          <Timeline />
        </TabBarIOS.Item>
        <TabBarIOS.Item
          icon={{uri:'contacts'}}
          selected={this.state.selectedTab === 'me'}
          onPress={() => {
            this.setState({
              selectedTab: 'me'
            });
          }}>
          <Profile />
        </TabBarIOS.Item>
      </TabBarIOS>

This is with release 0.4.1.

**Comment by iostalk** [comment]
Watch

**Comment by brentvatne** [comment]
@nicklockwood - your name seems to be the one most closely associated with this code, any insight?

**Comment by brentvatne** [comment]
Actually let's move this discussion into one issue: #1294
