### ISSUE TITLE
Fetch makes multiple API calls on the server

### ISSUE THREAD

**Issue by gathole** [facebook/react-native#12069]
I am using **fetch** method to make API calls on the server and noted it is making multiple requests at the same time. Below you can see React Native code and server logs

Can someone please help in preventing multiple calls and understanding why is it happening?

### React Native:
```javascript
fetch(url, {
	method: "GET",
	headers: {
		'Accept': "application/json",
		'Content-Type': "application/json"
		}
	}).then((resp) => {
	if (resp.status === 200) {
		resp.text().then(function(data) {
		var resData = JSON.parse(data);
		}
	}
}
```
### Server logs
```
[Wed Jan 25 12:14:08.323939 2017] [:error] [pid 13832] 2017-01-25 12:14:08.323658 URL:  /driver/upcoming-bookings/ User:  {'id': '', 'email': 'Anonymous'} HTTP Method: GET Params:  {u'imei': u'359375062977098'} 
[Wed Jan 25 12:14:08.631057 2017] [:error] [pid 14306] 2017-01-25 12:14:08.630777 URL:  /driver/upcoming-bookings/ User:  {'id': '', 'email': 'Anonymous'} HTTP Method: GET Params:  {u'imei': u'359375062977098'}  
[Wed Jan 25 12:14:09.103341 2017] [:error] [pid 14307] 2017-01-25 12:14:09.102915 URL:  /driver/upcoming-bookings/ User:  {'id': '', 'email': 'Anonymous'} HTTP Method: GET Params:  {u'imei': u'359375062977098'}
```

**Comment by alfonsodev** [comment]
@gathole from where are you calling fetch ?  perhaps you are using fetch from a  react function that you don't expect but it's executed more than once ?

**Comment by gathole** [comment]
@alfonsodev I am calling it in `componentWillMount` and in few screens on swipe of a button

**Comment by alfonsodev** [comment]
Then make sure you are not mounting the component multiple times.  I think this is most likely to be a problem in you application logic, have a look to `https://facebook.github.io/react/docs/react-component.html#componentwillmount` and perhaps add some `console.log` messages, if you get also 3 console.log messages you can discard the issue being a `fetch` issue, and look how you are structuring your components.

**Comment by brunolemos** [comment]
The recommended places to put side effects are on `did` methods, like `componentDidMount`.

**Comment by gathole** [comment]
Thanks @alfonsodev and @brunolemos for your valuable time and got resolved componentWillMount issue.
