### ISSUE TITLE
Error: running react-native run-ios (back-icon.png doesn't exist)

### ISSUE THREAD

**Issue by F1ks3r** [facebook/react-native#12062]
1. Updating latest watchman and node.
2. Installing lastest react-native-cli
3. Initialising react-native project
4. Using react-native run-ios without any changes
5. Error

transformed 349/394 (89%)
(node:25247) UnhandledPromiseRejectionWarning: Unhandled promise rejection
(rejection id: 893): UnableToResolveError:Unable to resolve module ./assets/back-icon.png from weekdays/node_modules/react-native/Libraries/CustomComponents/NavigationExperimental/NavigationHeaderBackButton.js: Directory weekdays/node_modules/react-native/Libraries/CustomComponents/NavigationExperimental/assets/back-icon.png doesn't exist

- Node: v7.2.0
- react-native-cli: v4.1.1
- OSX: ElCapitan: v10.11.5 (15F34)
- Simulator: iPhone 6 - iOS 10.2 (14C89)
- Xcode: v8.2.1 (8C1002)

Opening
/node_modules/react-native/Libraries/CustomComponents/NavigationExperimental/NavigationHeaderBackButton.js
and changing
`43: <Image style={styles.button} source={require('./assets/back-icon.png')} />`
to
`43: <Image style={styles.button} />`
resolves issue, but i'm pretty sure i should not do that

Reinstalling node_modules inside project directiory, and inside /node_modules/react-native with
`npm cache clean`
`rm -rf node_modules`
`npm install`
doesn't do the trick.

also chaning package.json dependencies react-native from "0.40.0" to "0.38.0" fixes the problem

How to fix?

**Comment by ericvicenti** [comment]
Hmm, I haven't seen this issue.

Can you try running `watchman watch-del-all` and running the RN packager server with the `--resetCache` option?

**Comment by F1ks3r** [comment]
Closing, bigger thread here #6691

**Comment by cyclops24** [comment]
Hi guys,
I also want to create simple hello word based on this: https://facebook.github.io/react-native/docs/getting-started.html and I faced on this red error:
```
"node_modules/react-native/Libraries/CustomComponents/NavigationExperimental/assets/back-icon.png doesn't exist"
```

Can you help me to fix this?
I worked with React-Native later without any issue but after install new version this error appear on any app (also a simple hello world)

**Comment by cyclops24** [comment]
This is my complete error:
![photo_2017-03-04_20-51-18](https://cloud.githubusercontent.com/assets/8266479/23580755/d036e788-011c-11e7-9a2a-b2801d31a2b1.jpg)

**Comment by RaThierry** [comment]
Hi guys,
I also want to create simple hello word based on this: https://facebook.github.io/react-native/docs/getting-started.html and I faced on this red error:

`/node_modules/react-native/Libraries/CustomComponents/NavigationExperimental/assets/back-icon.png doesn't exist`

Can you help me to fix this? 
Please, please, please, please!!!!!!

**Comment by Jimmy-YMJ** [comment]
sudo chmod -R 755 your-project

**Comment by cyclops24** [comment]
Hi @RaThierry,
See #6691 and check project folder path. Maybe special character exists in path. For example `+`. For me it's the main issue.

**Comment by gwest7** [comment]
@cyclops24 That was our problem too. We had a space in one of our directory names.

**Comment by joselcvarela** [comment]
@Jimmy-YMJ thank you, that worked for me :D

**Comment by shels107** [comment]
@Jimmy-YMJ thank you, that worked for and me :D
