### ISSUE TITLE
XHR should support priority for HTTP/2

### ISSUE THREAD

**Issue by alexanderkjeldaas** [facebook/react-native#12065]
### Description

The XHR requests should support priorities such as what Chromium, Firefox etc. support for HTTP/2 requests.
See
https://bugs.chromium.org/p/chromium/issues/detail?id=41501
NSURLSession supports it:
http://stackoverflow.com/questions/23602287/nsurlsession-priority
okhttp does not:
https://github.com/square/okhttp/issues/1361

### Reproduction

Manually inspecting the react code base did not bring up any hits that indicated that priority is supported.

### Solution

Implement it?

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
