### ISSUE TITLE
Error: Unknown config option "transformIgnorePatterns" with value "node_modules ...

### ISSUE THREAD

**Issue by itinance** [facebook/react-native#12061]
--- Please use this template, and delete everything above this line before submitting your issue --- 

### Description

When running jest in a newly created react-native-application (0.40 right now), the following startup-error occurs. It still occurs also when all tests are removed, so i guess it has nothing to do with the tests itself but with some babel-presets or something like that.

`$ jest
`

> Error: Unknown config option "transformIgnorePatterns" with value "node_modules/(?!(jest-)?react-native|react-clone-referenced-element)". This is either a typing error or a user mistake and fixing it will remove this message.

![screen shot 2017-01-24 at 19 41 53](https://cloud.githubusercontent.com/assets/1758597/22261716/539acc7a-e26e-11e6-84a2-d04558ae7079.png)

### Reproduction

1. cd /tmp
2. react-native init test
3. cd test
4. jest

### Solution

@cpojer told at https://github.com/facebook/jest/issues/2687#issuecomment-274900981, that jest from version >= 18.x shall fix this issue. However, this is 18.1.0 (see below at "versions") 

### Additional Information

Versions:

```
node:     v6.2.2
npm:      4.0.3
OSX:      El Capitain
yarn:      0.18.1
jest:       18.1.0
babel-jest: 18.0.0
react-native: 0.40.0
react:     15.4.2
babel-preset-react-native": 1.9.1
```

**Comment by cpojer** [comment]
do you have a global version of Jest installed that is lower than the one in your project? I think that may be your issue here.

**Comment by itinance** [comment]
Hell yeah! This is the issue. Jest-cli should have also >= 18.1.0. 
Thank you very much, @cpojer !
