### ISSUE TITLE
Image with wrong format doesn't display

### ISSUE THREAD

**Issue by EJohnF** [facebook/react-native#12074]
### Description

Try to display image using uri-link. Ususally everything works fine, however when in the link there is jpg(or png) images saved as name.gif (=with wrong extension) this image doesn't display.

note: gif support is turn on, so that real gif animation is displaying correctly. 

### Reproduction

https://rnplay.org/apps/1ftZLg

### Solution

I found out that this https://github.com/alwx/react-native-photo-view library can display that type of images. However they cann't show animated gif.

### Additional Information

* React Native version: 
"react": "15.4.1",
"react-native": "0.38.0",
* Platform: both
* Operating System: MacOS

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.

**Comment by EJohnF** [comment]
I didn't check that in the last versions of RN, in our project we used mentioned library
