### ISSUE TITLE
Duplicate module name

### ISSUE THREAD

**Issue by gritzko** [facebook/react-native#12078]
### Description

I build a React Native project.
Sometimes, it finds a package.json file inside the `ios/build/Build/Products/Debug-iphonesimulator` folder.
Why does it look there at all?
Then:
```
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: ReactExample
  Paths: /Users/gritzko/Projects/RealmTasks/RealmTasks React/package.json collides with /Users/gritzko/Projects/RealmTasks/RealmTasks React/ios/build/Build/Products/Debug-iphonesimulator/ReactExample.app/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
  Duplicate module name: ReactExample
  Paths: /Users/gritzko/Projects/RealmTasks/RealmTasks React/package.json collides with /Users/gritzko/Projects/RealmTasks/RealmTasks React/ios/build/Build/Products/Debug-iphonesimulator/ReactExample.app/package.json
```

### Reproduction

You can try building
   https://github.com/realm/RealmTasks/tree/vg-RN/RealmTasks%20React
(a React Native todo list example for the Realm mobile db)
Note the vg-RN branch name.

### Solution

Just don't look everywhere for package.json files. You can find absolutely anything, depending on local conditions.

### Additional Information

* React Native version: 0.40
* Platform: iOS
* Operating System: MacOS

**Comment by ericvicenti** [comment]
cc @cpojer. I'm guessing this can be merged with another task but I'm not sure which

**Comment by gritzko** [comment]
Relate issues: #12051 #7384

**Comment by gritzko** [comment]
FYI. A three-step workaround and some nice regex adventures at SO
http://stackoverflow.com/questions/41813211/how-to-make-react-native-packager-ignore-certain-directories

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
