### ISSUE TITLE
React Native http Fetch POST/PUT not working on android AVD

### ISSUE THREAD

**Issue by TyrealGray** [facebook/react-native#12094]
Working on this one and I have no idea.
iOS is working fine, and GET method is working also fine on android AVD as well.
But POST/PUT/DELETE is not working.
I checked all the methods on Postman also works.

```
fetch(Config.api, {
method: 'POST',//PUT
headers: {
'Content-Type': 'application/json',
'Authorization': 'XXXXXXXXXXX'
},
body: JSON.stringify(data))
```

* React Native version: 0.37.0
* Platform: Android
* Operating System: MacOS 10.11.6

**Comment by athmangude** [comment]
What's your API Level for the AVD?

**Comment by TyrealGray** [comment]
Level 23

**Comment by athmangude** [comment]
I also am also experiencing this issue on devices running android < 5. But emulators run fine

**Comment by TyrealGray** [comment]
@athmangude my issue seems to be like that if the request has a body, it will not work

**Comment by TyrealGray** [comment]
@athmangude I finally found out the problem, #8237. Our server does not prepare api for "utf-8", and android avd sent requests with "charset=utf-8". So it cause 500 status error.
