### ISSUE TITLE
[Chrome Debugger] "Not allowed to load local resource" when debugging in Chrome and loading main.jsbundle

### ISSUE THREAD

**Issue by itsananderson** [facebook/react-native#1209]
When you uncomment this line in a newly generated project to use the main.jsbundle file, debugging in Chrome stops working.

```objective-c
jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
```

When you "Debug in Chrome":

```
Not allowed to load local resource:  
file:///Users/.../Library/Developer/CoreSimulator/Devices/FDEBA9B8-…tion/5EFF3E8A-F067-4DDB-A023-A528FB9D61DE/.../main.jsbundle
```

Of course, this is because the page is trying to load a `file://` script. Totally expected, but it does make it painful to debug scenarios that might only occur when you load from the bundle.

I actually tweaked the packager code to work around this.

In `packager/debugger.html`, I updated the loadScript function to check for the `file://` protocol, and proxy the request through the packager. e.g. `http://localhost:8081/file://...`.

Then in `packager/packager.js` I updated `getDevToolsLauncher` to check for `/file://` in the path, and to serve that file.

Is this workaround something you'd be interested in me sending a PR for, or is the current behavior intentional?

Obviously the main drawback of my workaround is that it exposes a way to fetch arbitrary files from the machine. Considering the packager/debugger already allows any connected websocket clients to cause arbitrary code execution through `executeApplicationScript`, is that a concern?

**Comment by spicyj** [comment]
> Totally expected, but it does make it painful to debug scenarios that might only occur when you load from the bundle.

If it's the dev vs. prod difference, you can change it to use the same http URL with `?dev=false`.

**Comment by itsananderson** [comment]
True for a typical scenario, but I've been experimenting with downloading bundles into the app's writable filesystem, and then loading them from there.

```objective-c
NSString* appName = @"foo";
NSString* home = NSHomeDirectory();
NSString* playerAppPath = [home stringByAppendingPathComponent:@"PlayerApps"];
NSString* appBundleName = [appName stringByAppendingString:@".jsbundle"];
jsCodeLocation = [playerAppPath stringByAppendingPathComponent:appBundleName];
```

In that case, where I'm essentially loading an app from an arbitrary path, I don't think there's currently a way to get the packager to serve that file.

**Comment by MattFoley** [comment]
@itsananderson This is a work around I would be very much interested in. Would you be willing to share?

**Comment by jaygarcia** [comment]
Can i ask a silly question: Why not just point jsCodeLocation to the IP address of your mac so that you can debug code that you can easily edit and refresh w/out having to rebuild & redeploy?

**Comment by MattFoley** [comment]
For what I'm building, that's going to not be the best way to go rather quickly.

**Comment by jaygarcia** [comment]
OK. This sound exciting.  But what about the minification of the source code in the bundle. How are you planning on handling that? :)

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by jacob-israel-turner** [comment]
If anyone gets tripped up with working through @itsananderson's original solution, here is a Gist to walk you through the steps:

https://gist.github.com/jacob-israel-turner/19ee1531443fea2f40f5

**Comment by ohadpartuck** [comment]
@jacob-israel-turner followed the gist and it's not working. 
any other suggestions?

**Comment by jacob-israel-turner** [comment]
Make sure you close and re-open both the debugger ui and the node process running the packager.  That's tripped me up a couple of times.

**Comment by ohadpartuck** [comment]
@facebook-github-bot-8 why is it taking so long long to fix this? it seems to bug a lot of people ...
React-native is important enough to be urgent :-)

**Comment by brentvatne** [comment]
@ohadpartuck - my guess would be that this isn't a use case that is important to the team at Facebook. Additionally, the solution proposed here has a pretty significant security flaw as @itsananderson pointed out..

That said, this does sound like a nice feature to have, but in the short term the solution may have to come from the community. If anyone has proposals or PRs for a solution that would be great. For example, @itsananderson's could be modified to only fetch .jsbundle files from a path that matches some criteria (ideally the simulator id is in there).

**Comment by jacob-israel-turner** [comment]
@brentvatne Is the simulator id exposed somewhere?  I'm willing to make a PR if I can make it secure enough.

**Comment by brentvatne** [comment]
@jacob-israel-turner - not that I'm aware of, @tadeuzagallo @nicklockwood do you know?

**Comment by jacob-israel-turner** [comment]
Sorry, I looked into it over the weekend.  Apple does NOT allow the device ID (simulator id) to be exposed to the app, so I don't think we'd be able to check the exact simulator ID.  However, we could probably check and make sure that *a* valid device ID is in the file path.

**Comment by javache** [comment]
Debugging in Chrome is not supported with bundled files. If you're fixing this by having the chrome debugger load the JS from the packager instead, why not have the app request the JS there in the first place? The JS you load from the bundle might be very different from the bundled one and have different performance characteristics.

A PR that emits a warning when trying to use the Chrome debugger with a bundled file would be very useful though.

**Comment by itsananderson** [comment]
Differences between the bundled files and the packager is exactly what we're wanting to be able to debug. We're not suggesting that requests for local bundled files be redirected to the packager's version. What we want is for the packager to serve the *bundled* file over HTTP (instead of local file path) so that Chrome can load it. Otherwise, when there are issues that only appear with bundled files, they're really hard to debug.

**Comment by javache** [comment]
Thanks for the clarification @itsananderson. I hope we can solve this at a different level, since making the packager a generic file proxy doesn't seem like something we'd want to support. Are there any specific differences you're seeing between the bundled file and the one generated by the packager server? Given the right request flags, they should be identical.

Keep in mind as well that replicating exact runtime conditions will never be possible in Chrome, due to large differences between the websocket and native executor.

**Comment by ide** [comment]
On iOS you can use the JSC debugger against the real bundle.

**Comment by itsananderson** [comment]
The specific use-case for using the Chrome debugger with bundle files is the [CodePush project](https://github.com/Microsoft/react-native-code-push) that we announced today (sorry for the vague pre-release description of the use-case).

I anticipate developers wanting to test their app's upgrade workflow, and potentially debug them if something isn't behaving as expected. Since the CodePush library downloads app updates as 
"jsbundle" files, it's currently impossible to test the update flow in Chrome DevTools. Even if you set the packager url, once the update installs, a new URL is configured, and the app is reloaded, at which point Chrome fails to load it.

Maybe this scenario works with JSC (I'll have to test). Still, it'd be sweet if we could figure out a way to make it work in DevTools, since that seems like the more pleasant experience.
