### ISSUE TITLE
Go back to your native app after launch of react native in existing project

### ISSUE THREAD

**Issue by shukerullah** [facebook/react-native#12109]
I have successfully [integrated react native in existing project](https://facebook.github.io/react-native/docs/integration-with-existing-apps.html). In my native app I have a screen with a button that launch react-native screen.

In Android I can go back to previous screen with help of `BackAndroid.exitApp()`. How can I achieve same functionality in iOS?

**Comment by ericvicenti** [comment]
You can expose a function from the native code by exposing a module with `RCT_EXPORT_MODULE`, and from there, call a native method to close the react screen. You also probably want to pass a rootTag so you know which react screen to go back from.

As an example of one of these bridged method calls, see the hybrid example here: https://github.com/react-community/react-navigation/blob/master/examples/HelloHybrid/ios/HelloHybrid/HybridNavigationManager.m#L30

**Comment by ericvicenti** [comment]
I'm going to close this out for now, please open a new issue if you have troubles with the bridged method

**Comment by shukerullah** [comment]
@ericvicenti Can you please write example for `RCT_EXPORT_METHOD(popLastViewController)`?
