### ISSUE TITLE
CLI freezes during init

### ISSUE THREAD

**Issue by nachoaIvarez** [facebook/react-native#12100]
### Description

`react-native-cli init` freezes after `yarn install`.

### Reproduction
*Note:* click on the image for a video.
[![FREEZE](http://i.imgur.com/0zIL1Rv.png)](http://sendvid.com/xyrjvxev)

### Additional Information

* React Native version: 2.0.1
* Yarn version: 0.19.1
* Operating System: macOS Sierra

**Comment by deptno** [comment]
hang in https://github.com/facebook/react-native/blob/master/react-native-cli/index.js#L303

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
