### ISSUE TITLE
Connection randomly times out

### ISSUE THREAD

**Issue by PavSidhu** [facebook/react-native#12108]
When debugging my React Native app, it all works fine but randomly every 30 minutes or so get this error:

![img_0016](https://cloud.githubusercontent.com/assets/4911505/22399745/f12a747e-e59b-11e6-8ea3-05281518bbad.PNG)

This usually happens when I'm using live reload and save my updated code, though I have not been able to try it without using live reload. This could happen no matter what changes I make to my code as far as I know, it could be anything.

I'm using React-Native version 0.40.0 running on MacOS Sierra along with an iPhone 6S iOS 10.2.

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
