### ISSUE TITLE
Image blinks when source uri changes. Only with resizeMode: 'contain'

### ISSUE THREAD

**Issue by user471** [facebook/react-native#12104]
### Description

I use `this.images = []` so image loading shouldn't affect this problem.

`img1` and `img2` from `android\app\src\main\res\drawable\` directory

```
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  TouchableOpacity,
  Text,
  Image,
  View
} from 'react-native';

export default class test extends Component {
	constructor(props) {
		super(props);
		this.state = {id: 1};
		this.foo = this.foo.bind(this);
		this.images = []
		this.images[0] = <Image style={styles.item} source={{uri: "img1"}} />
		this.images[1] = <Image style={styles.item} source={{uri: "img2"}} />

	}

	foo() {
		this.setState({id: (this.state.id + 1)%2});
	}
	render() {
		return (<View style={styles.container}>
				{this.images[this.state.id]}
				<TouchableOpacity onPress={this.foo}>
				<Text>Button</Text>
				</TouchableOpacity>
				</View>)
	}
}

const styles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: "white"
	},
	item: {
		alignSelf : 'stretch',
		resizeMode: 'contain',
		flex: 1
	}
});

AppRegistry.registerComponent('test', () => test);
```

### Reproduction
Image blinks when "Button" is touched

### Solution

Remove `resizeMode: 'contain'`

### Additional Information

* React Native version: 0.40
* Platform: Android

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.

**Comment by dashracer** [comment]
Hi @hramos ,

I'm having the same issue.

I'm trying to create a slide image but using only single image component by changing source props.

If i follow the solution mentioned in the thread, my image will overlapped with device width because the image do not have fixed size

So what is the solution for this one

Thank you
