### ISSUE TITLE
Unwanted initial scroll on doc pages loaded by clicking `prev` or `next` on small screen device

### ISSUE THREAD

**Issue by jddxf** [facebook/react-native#12116]
When I read the RN documentation using my mobile browser, I find there's a initial scroll if I navigate by clicking `prev` or `next` at the bottom of page which is annoying.Try following link on a small screen device:
http://facebook.github.io/react-native/docs/style.html#content

This doesn't happen when navigating by sidebar as the links there don't have url fragments `#content`.Neither does it on large screen device as `#content` has `display: none` in that situation so that browsers won't scroll.

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
