### ISSUE TITLE
I just want to know where is the changelog?

### ISSUE THREAD

**Issue by soliury** [facebook/react-native#1211]

**Comment by Dashed** [comment]
Here: https://github.com/facebook/react-native/commits/master

**Comment by ide** [comment]
AFAIK there is no changelog separate from the list of commit summaries.

**Comment by brentvatne** [comment]
The compare view works great for this: https://github.com/facebook/react-native/compare/a63b6ff11279e1c39e6147d8576b10c4e57c39d4...41612f37b0c31320b025043df9e954df540db171

**Comment by soliury** [comment]
OK, I see, but look in the commits, it so disorder. I think a clear changelog is good.

**Comment by iostalk** [comment]
I don't need a changlog

**Comment by brentvatne** [comment]
@soliury - It would be useful to see but I'm not sure if the resources are available to compile a changelog. If anyone would like to take on this job I'm sure it would be welcome! This is an OSS project after all :smile:

**Comment by soliury** [comment]
ok, I see.

**Comment by ide** [comment]
The latest RC now has a change log, authored by @vjeux! https://github.com/facebook/react-native/releases/tag/v0.5.0-rc
