### ISSUE TITLE
Unable to change the <Switch /> color in Android

### ISSUE THREAD

**Issue by otoinsa** [facebook/react-native#12121]
There is no way to do this via the React Native javascript API,
so I am trying to do this in native android.

I've managed to change the whole app accent color, however is there a way to change just the switch accent color?

For me this does not work in styles.xml:

<resources>
    
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        
        <item name="android:windowIsTranslucent">true</item>
        <item name="android:switchStyle">@style/myswitch</item>
    </style>

    <style name="myswitch" parent="Theme.AppCompat.Light">
        <item name="colorAccent">#FF0000</item>
        <item name="colorControlActivated">#ff0000</item>
    </style>
</resources>

Only when I change the whole app accent color on theme editor, the switch changes.
Is there really no way to use the native component without dealing with the teal color?
It just sticks out like a sore thumb in my app design...

**Comment by nihgwu** [comment]
#11940
