### ISSUE TITLE
What is the migration strategy for native library publishers in light of the 0.40.0 update?

### ISSUE THREAD

**Issue by rclai** [facebook/react-native#12125]
Is it just me or is there no set strategy for native library publishers regarding how they're supposed to update their libraries to account for the 0.40.0 breaking change that requires iOS devs to change all RN imports to the `<React/<lib name>.h>` format?

Is there at least some kind of `REACT_NATIVE_VERSION` constant available so that library publishers can do conditional imports?

```c
#if REACT_NATIVE_VERSION >= 4000

#import <React/Utils.h>;

#else

#import "Utils.h";

#endif
```
(Untested)

Library publishers are going to have to say in their Read Mes to install 1.0 if their RN version is <=0.3x.x or 2.0 if their RN version is >=0.40.0.

Or they won't, and a bunch of new RN developers are going to be wondering why no third-party libraries work.

Or they'll have to install a pre 0.40.0 version of RN to use the library.

**Comment by janicduplessis** [comment]
I think the strategy right now is to update your libraries to a version that support RN 0.40.0+ if you are using that or pin your libraries to an older version if you not using 0.40 yet. You can lock your libary to a precise version by doing something like "libary": "0.5.0" in your package.json (instead of "^0.5.0").

**Comment by rh389** [comment]
It's a fair question and there's no recommended strategy AFAIK. Most library developers seem to be just making the change as a BC, dropping active development for RN<040, and making a note about compatibility in their `README`s. It's not ideal and I'm sure new users would've been put off in the early days of 0.40, but as time passes most popular packages now seem to be supporting RN 0.40. 

I've seen authors using `__has_include('<React/RCTFoo.h>')... ` to do conditional imports in a non-breaking way - bit hacky but it's effective if you're keen to avoid dropping 0.39 or branching your project. 

I like the idea of a `REACT_NATIVE_VERSION`  define but I don't think we have such a thing yet - the details might be tricky (e.g. versioning `master` usefully, and how/when it gets updated) but in principle it sounds useful as the project matures, particularly for native module devs - @javache?

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
