### ISSUE TITLE
ListView: refreshControl prop does not work if horizontal={true}

### ISSUE THREAD

**Issue by joncursi** [facebook/react-native#12139]
I noticed that on the ListView component, the refreshControl prop is omitted / fails silently if the ListView is set to scroll horizontally with horizontal={true}. Perhaps this is best anyway, as the design would be a bit funky for a horizontal swipe to refresh, but maybe it's worth noting this behavior in the documentation.

**Comment by janicduplessis** [comment]
Yea it's not supported on horizontal scroll views, feel free to send a PR to improve the doc. :)

**Comment by janicduplessis** [comment]
@joncursi Thanks for the PR!
