### ISSUE TITLE
Each child in an array or iterator should have a unique "key" prop

### ISSUE THREAD

**Issue by progrmor** [facebook/react-native#12132]
### Description

I simply copied the example of CameraRoll here at github and it came up with a warning immediately:

> Warning Each child in an array or iterator should have a unique "key" prop

### Reproduction

No need for me to insert any code actually. I copied it all from the example without adjustments. 
From my research I've found very little other than people saying you need to declare a "key" prop somewhere here:

```

_renderRow: function(rowData: Array<Image>, sectionID: string, rowID: string)  {
    var images = rowData.map((image) => {
      if (image !== null) {
          return this.props.renderImage(image);
      }
    });
    return (
      <View style={styles.row}>
        {images}
      </View>
    );
  },

```
(Fair enough, I made one change, it did return null instead of this.props.renderImage(image) before) 

### Additional Information

* React Native version: 0.40.0 / cli: 2.0.1
* Platform: Android (might be both, haven't tried yet)
* Operating System: Windows 7

**Comment by rh389** [comment]
Yes, arrays of components need to have keys so that React can do change detection effectively.

Does this help? https://github.com/facebook/react-native/compare/master...rh389:patch-13 . If so I'll make it a PR.

**Comment by progrmor** [comment]
@rh389 Superb sir! It took care of the warning. Thank you!

**Comment by jasmineelamblakatt** [comment]
**_**_**dfgete**_**_**
