### ISSUE TITLE
Local rn-cli.config.js is not loaded

### ISSUE THREAD

**Issue by rh389** [facebook/react-native#12133]
### Expected behaviour
When a file exists in the project root called `rn-cli.config.js` this should be loaded allowing it to override the defaults in [default.config.js](https://github.com/facebook/react-native/blob/master/local-cli/core/default.config.js), as per a comment in that file.

### Observed behaviour
The file is ignored unless explicitly pointed to with `--config`.

### Additional Information
Since [react-native/rn-cli.config.js](https://github.com/facebook/react-native/blob/master/rn-cli.config.js) was created by @davidaurelio  at https://github.com/facebook/react-native/commit/73f62e588e643a62e7522766bf85772cea4dd8ab , this takes precedence over the user's project's copy of `rn-cli.config.js`, because [local-cli/util/Config.js](https://github.com/facebook/react-native/blob/master/local-cli/util/Config.js) finds the first such file crawling upwards from its own directory.

What is [react-native/rn-cli.config.js](https://github.com/facebook/react-native/blob/master/rn-cli.config.js) for? Could it be called something else (so that it doesn't get in the way of project config) and loaded explicitly wherever it's needed? Could it be merged with default.config.js and removed?

* React Native version: >=0.30
* Platform: All
* Operating System: All

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
