### ISSUE TITLE
Passing React VIews to Native UI component

### ISSUE THREAD

**Issue by rengasahusoft** [facebook/react-native#12151]
Hi,

I am trying to bride the native iOS UITableView. I need to pass the view which i have created in RN as props to Native View

Some thing like
`<Native renderRow={() => <TableCell />} /> `

Then in native i can assign the TableCell which i have passed  as props to UITableCellView

Is there a way to pass the ReactView to Native UI Components as Props ?

**Comment by aaronschubert0** [comment]
@rengasahusoft This should help: https://medium.com/@talkol/recycling-rows-for-high-performance-react-native-list-views-628fd0363861#.7tp88l3ue

**Comment by rengasahusoft** [comment]
@aaronschubert0 That was help ful
