### ISSUE TITLE
can't load image

### ISSUE THREAD

**Issue by nimingzhe** [facebook/react-native#1215]
I write a simple iOS program to show image with React Native.

    'use strict';
    
    var React = require('react-native');
    var {
      Image
    } = React;
    
    var styles = React.StyleSheet.create({
      
      base: {
        height: 400,
        width: 400 
    }
    });
    
    class SimpleApp extends React.Component {
      render() {
        return (
        <Image
        style={styles.base}
        source={require('image!k')}
        //source={{uri: 'http://news.xinhuanet.com/world/2015-05/09/127782089_14311512601821n.jpg'}}
          /> 
        )
      }
    }
    
    React.AppRegistry.registerComponent('SimpleApp', () => SimpleApp);
But I got the message from iPad screen:

    "Failed to print error:","'undefined' is not an object (evaluating 'stackString.split')"

When I change the code to use image url

    //source={require('image!k')}
    source={{uri: 'http://news.xinhuanet.com/world/2015-05/09/127782089_14311512601821n.jpg'}}
I only get a red rect border.

When I use another js file, everything works well."Hello World" can show on iPad screen.

    'use strict';
    
    var React = require('react-native');
    var {
      Text,
    
    } = React;
    
    
    class SimpleApp extends React.Component {
      render() {
        return (
        
            <Text>Hello World</Text>
    
        )
      }
    }
    
    React.AppRegistry.registerComponent('SimpleApp', () => SimpleApp);

**Comment by sharathprabhal** [comment]
Try restarting the iOS Simulator. That helped in my case.

**Comment by brentvatne** [comment]
@nimingzhe - you can't have a comment inline in JSX

```
  source={require('image!k')}
  //source={{uri: 'http://news.xinhuanet.com/world/2015-05/09/127782089_14311512601821n.jpg'}}
```

that is invalid.

Aside from that, are you using a normal project init process, `react-native init`, or are you using Cocoapods?

**Comment by kejinlu** [comment]
@brentvatne  I got the same problem， using Cocoapods

**Comment by kejinlu** [comment]
@nimingzhe Have you  import React/RCTImage pod

**Comment by brentvatne** [comment]
No indication that there is any bug, our solutions suggested above should work. Feel free to ping me if not!
