### ISSUE TITLE
Running Error immediately after build

### ISSUE THREAD

**Issue by ajamiesonfraser** [facebook/react-native#12169]
Followed steps to get the movies example app up and running but after build this screen came up
![screen shot 2017-02-02 at 11 13 15 am](https://cloud.githubusercontent.com/assets/8396654/22555155/255c32fa-e939-11e6-98c2-7407387706fd.png)

**Comment by angelbotto** [comment]
check "responseData" 🙃

**Comment by sashamjolnir** [comment]
It's because rotten tomatoes api doesn't work anymore. See #11028.
You should replace fetch url, like in this sample.
https://facebook.github.io/react-native/releases/0.27/docs/sample-application-movies.html

**Comment by ericvicenti** [comment]
The movies sample has been removed from the core RN repo. Feel free to publish standalone example apps, and we can curate a list of them for the website.
