### ISSUE TITLE
TextInput borderBottomcolor is not working?

### ISSUE THREAD

**Issue by TylerYang** [facebook/react-native#1216]
Hi guys, just created a login page. When I try to change the bottomBorder color of TextInput, it is not working.  
Here is my code:

    <TextInput style={styles.input} placeholder='Your Account' />    

    input:{
        flex: 1,
        height: 50,
        marginLeft: 10,
        marginTop: 5,
        paddingLeft: 10,
        marginRight: 5,
        fontSize: 18,
        borderWidth: 1,
        borderColor: '#CCCCCC',
        borderLeftColor: '#000000',   //nothing happened here.
        color: '#888888'
    }

Any suggestions? Thx...

**Comment by christopherdro** [comment]
The properties you are trying to use don't apply to the TextInput rather the View wrapping it.
It should look something like this...
```
<View style={styles.input}>
  <TextInput placeholder='Your Account' />    
</View>

input:{
    flex: 1,
    height: 50,
    marginLeft: 10,
    marginTop: 5,
    paddingLeft: 10,
    marginRight: 5,
    fontSize: 18,
    borderWidth: 1,
    borderColor: '#CCCCCC',
    borderLeftColor: '#000000',   //nothing happened here.
    color: '#888888'
}
```

**Comment by TylerYang** [comment]
@christopherdro  Get it, thx!

**Comment by christopherdro** [comment]
@TylerYang Np! Make sure to close if it resolved your issue.

**Comment by TylerYang** [comment]
@christopherdro  It's working. Close it now. : )
