### ISSUE TITLE
TextInput with textAlign='right' inside a ScrollView gets focused on scroll (Android only)

### ISSUE THREAD

**Issue by mmazzarolo** [facebook/react-native#12167]
### Description

Hello there,
I've found a small issue on Android.  
When a `TextInput` with has `textAlign: 'right'` inside a `ScrollView` and you press on it for scrolling it will focus instead (only on Android).  
The correct behaviour would be to get focused only if you tap on it (without scrolling).   
It works perfectly on iOS **or** if you remove the `textAlign` style.  

EDIT: I'm having the same issue with `textAlign: 'center'`.  
Works correctly with every other prop (`left`, `justify`, `auto`).

### Reproduction

You can test it easily:
```javascript
<ScrollView>
  <TextInput style={{ textAlign: 'right' }} />
  <View style={{ height: 2000 }} />
</ScrollView>
```

### Additional Information

* React Native version: 0.40
* Platform: Android (tested on an emulated Nexus 5 and on real Moto G3)
* Operating System: MacOS

**Comment by hoangpham95** [comment]
I just tested with react-native 0.40.0 and cannot reproduce the problem. Which Android version are you running in your devices?
![scroll](https://cloud.githubusercontent.com/assets/11971101/22561594/baf366f0-e92d-11e6-84ce-0605554d3360.gif)

**Comment by mmazzarolo** [comment]
That's weird. Are you starting the scroll by tapping the textinput?  
Also, is that a blank project?  
I'm on 5.1.0.  

Oh, and thank you for trying it man!

**Comment by hoangpham95** [comment]
Yes, this is a blank project. I'm starting outside of the TextInput. If you tap the text input then it should be focused, so I think this might not be an issue.

**Comment by mmazzarolo** [comment]
Ah-ha!  
Nope, it should not be focused because:
1. If you remove the `textAlign` it doesn't get focused
2. On iOS it doesn't get focused
3. On many different native apps I tried it doesn't get focused (for example try the form in the new contact screen in Android)

**Comment by hoangpham95** [comment]
You're right, I tried and saw the problem. The `textAlign` caused the text input to be focused on touch.

**Comment by anddo** [comment]
I have the same problem on  react-native 0.45.1

**Comment by igofind** [comment]
+1
No one can solve this problem?

**Comment by pecopeco** [comment]
+1

**Comment by turlac** [comment]
+1
@pecopeco just made my day. thank you for the workaround!
Any idea how we can get around the keyboard limitation of it having to be 'default' and not 'numeric'?

**Comment by igofind** [comment]
@pecopeco
Thanks ! It works!

**Comment by kengjungwa** [comment]
@pecopeco works but NOT on keyboardType={"numeric"}

**Comment by ahmetacikgoz** [comment]
Same issue!

**Comment by programmdesign** [comment]
@pecopeco: thanks for the workaround. We can't use multiline though. Any idea for a workaround w/o multilines?

**Comment by enamin** [comment]
+1
Same Issue

**Comment by yuvalsegev** [comment]
+1

Anyone willing to help?

**Comment by mobitar** [comment]
I solved this issue by installing a [PanResponder](https://facebook.github.io/react-native/docs/panresponder.html):

```
  componentWillMount: function() {
    this._panResponder = PanResponder.create({
      // Ask to be the responder:
      onStartShouldSetPanResponder: (evt, gestureState) => true,
      onStartShouldSetPanResponderCapture: (evt, gestureState) => true,
      onMoveShouldSetPanResponder: (evt, gestureState) => true,
      onMoveShouldSetPanResponderCapture: (evt, gestureState) => true,

      onPanResponderGrant: (evt, gestureState) => {
        // The gesture has started. Show visual feedback so the user knows
        // what is happening!

        // gestureState.d{x,y} will be set to zero now
      },
      onPanResponderMove: (evt, gestureState) => {
        // The most recent move distance is gestureState.move{X,Y}

        // The accumulated gesture distance since becoming responder is
        // gestureState.d{x,y}
      },
      onPanResponderTerminationRequest: (evt, gestureState) => true,
      onPanResponderRelease: (evt, gestureState) => {
        // The user has released all touches while this view is the
        // responder. This typically means a gesture has succeeded
      },
      onPanResponderTerminate: (evt, gestureState) => {
        // Another component has become the responder, so this gesture
        // should be cancelled
      },
      onShouldBlockNativeResponder: (evt, gestureState) => {
        // Returns whether this component should block native components from becoming the JS
        // responder. Returns true by default. Is currently only supported on android.
        return true;
      },
    });
  },
```

Then on your main view:

```
 <View {...this._panResponder.panHandlers} />
```

**Comment by nishiltamboli** [comment]
@pecopeco Thanks mate that worked like a charm. Weird issue really.

**Comment by mobitar** [comment]
For the record, The TextInput component is rendered inside of a `TouchableWithoutFeedback` that focuses on press, so I'm not sure how long any of these workarounds will last:

https://github.com/facebook/react-native/blob/master/Libraries/Components/TextInput/TextInput.js#L799

You might also be able to subclass TextInput, override the render method, and remove the Touchable wrapper.

**Comment by derakhshanfar** [comment]
same issue for me

**Comment by derakhshanfar** [comment]
@mobitar could you write example please?

**Comment by aizigao** [comment]
same problem, has some solution ?

**Comment by derakhshanfar** [comment]
any solution?!

**Comment by yqz0203** [comment]
@derakhshanfar did you have resolved this problem?

**Comment by louislatreille** [comment]
+1
I also have the same issue when manually setting the height of the text input under the default height. This causes it to be vertically scrollable, and eat the ScrollView scroll action. Having the height set like that, removing the textAlign prop or the workaround proposed by @pecopeco aren't even working.

**Comment by derakhshanfar** [comment]
@yqz0203 according to this issue #15274 i think the problem is related to this but i couldn't fix it yet!

> However, sometimes a parent will want to make sure that it becomes responder. This can be handled by using the capture phase. Before the responder system bubbles up from the deepest component, it will do a capture phase, firing on*ShouldSetResponderCapture. So if a parent View wants to prevent the child from becoming responder on a touch start, it should have a onStartShouldSetResponderCapture handler which returns true.

**Comment by yanhaijing** [comment]
I have the same problem on react-native 0.45.1

**Comment by yanhaijing** [comment]
I have the same problem on react-native 0.45.1

**Comment by feong** [comment]
I have the similar issue with RN 0.49.5
When there is a placeholder for a TextInput with AlignText = 'right', touch on it and move the finger away, the placeholder will disappeared.

**Comment by Tankerxyz** [comment]
Just wrap all your content in TouchableOpacity with activeOpacity={1} props.

**Comment by thgala** [comment]
### Number input component:
```js
focus = () => {
  if (this.inputRef) {
    this.inputRef.focus();
  }
}

blur = () => {
  if (this.inputRef) {
    this.inputRef.blur();
  }
}

inputRef: ?TextInput;

assignRef = (inputRef: ?TextInput) => {
  if (inputRef) {
    this.inputRef = inputRef;
  }
}

render() {
  return (
    <TextInput
      keyboardType="numeric"
      ref={inputRef => this.assignRef(inputRef)}
      ...
    />
  );
}
```
### Form component:
```js
handleInputPress = (index: number) => () => {
  if (this.input[index]) {
    this.input[index].focus();
  }
}

input: NumberInput[] = []

assignNumberInputRef = (inputRef: ?NumberInput, index: number) => {
  if (inputRef) {
    this.input[index] = inputRef;
  }
}

render() {
  return (
    <ScrollView>
      <TouchableOpacity activeOpacity={1} onPress={this.handleInputPress(index)}>
        <View pointerEvents="none">
          <NumberInput
            ref={input => this.assignNumberInputRef(input, index)}
            textAlign="right"
            ...
          />
        </View>
      </TouchableOpacity>
    </ScrollView>
  )
}
```

**Comment by SunSargent** [comment]
@thgala  can you show your NumberInput

**Comment by thgala** [comment]
@SunSargent  it is right above the **"Form component"**.

**Comment by SunSargent** [comment]
@thgala Thanks ! it work well.

**Comment by gwuhaolin** [comment]
same problem on react-native 0.54.3

**Comment by yupeifeng** [comment]
@thgala this method cause ：I cannot move cursor

**Comment by itskevinsam** [comment]
ping..

Same issue

**Comment by itskevinsam** [comment]
as per mobitars answer

My implementation is mostly like ..

      this._panResponder = PanResponder.create({

        onStartShouldSetPanResponder: (evt, gestureState) => false,
        onStartShouldSetPanResponderCapture: (evt, gestureState) => false,
        onMoveShouldSetPanResponder: (evt, gestureState) => true,
        onMoveShouldSetPanResponderCapture: (evt, gestureState) => true,

        onPanResponderGrant: (evt, gestureState) => {

        },
        onPanResponderMove: (evt, gestureState) => {
            let startPosition = (evt.nativeEvent.pageY - gestureState.dy);
            let movePosition =  startPosition - gestureState.dy;
            this.props.svr({y: movePosition});
        },
        onPanResponderTerminationRequest: (evt, gestureState) => true,
        onPanResponderRelease: (evt, gestureState) => {
      
        },
        onPanResponderTerminate: (evt, gestureState) => {

        },
        onShouldBlockNativeResponder: (evt, gestureState) => {

        },
      });  

Where this.props.svr function is a property in the scrollview component which effectively calls the scrollTo function.

**Comment by MujtabaFR** [comment]
I believe that the issue is liked to [this line](https://github.com/facebook/react-native/blob/1151c096dab17e5d9a6ac05b61aacecd4305f3db/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java#L131) in `react-native/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java`
But I couldn't fix it :(
Hope someone will do so ..

**Comment by mgolkardev** [comment]
@thgala
Thanks. It works!

**Comment by internet5** [comment]
I have the same problem on react-native 0.57.4

**Comment by Nagibaba** [comment]
For the sake of easy describing, I emphasize again. as @thgala stated, try something like this: 
`
<TouchableOpacity onPress={()=>this.input.focus()} >
  <View pointerEvents="none" >
    <TextInput ref = {(input) => this.input = input} />
  </View>
</TouchableOpacity>
`

**Comment by januslo** [comment]
I have test and worked with:
```javascript

import React, {Component} from 'react';
import {TextInput, View, TouchableOpacity} from 'react-native';

/**
 * 为修复当TextView 在ScrollView下，textAlign="right"时，Scrollview不能滚动的bug
 */
export default class TouchInput extends Component {


    input = null;
    handleInputPress = () => {
        if (this.input
            && (this.props.editable || this.props.editable == undefined)) {
            this.input.focus();
        }
    }
    
    assignNumberInputRef(input) {
        if (input) {
            this.input = input;
        }
    }

    render() {
        return <TouchableOpacity activeOpacity={1} onPress={this.handleInputPress} style={{flex: 1}}>
            <View pointerEvents="none" style={{flex: 1}}>
                <TextInput
                    ref={input => this.assignNumberInputRef(input)}
                    {...this.props}
                />
            </View>
        </TouchableOpacity>
    }
}

````
And use in the scrollview at a real project as:

```javascript
 <ScrollView  keyboardShouldPersistTaps='always'>
                    <View style={[styles.ItemViewContainer,styles.ItemViewContainerMarginBottom]}>
                        <View style={styles.ItemViewContentSpecial}>
                            <TouchableOpacity style={styles.ItemViewUploadImg} onPress={()=>this.openCamera()}>
                                <Image source={{uri: Config.host +  product.ProductPic}} style={styles.uploadImg}/>
                            </TouchableOpacity>
                            <View style={styles.ItemViewUploadRight}>
                                <View style={[styles.ItemViewContent,styles.ItemViewContentBorder]}>
                                    <Text style={styles.ItemViewText}>货品名称</Text>
                                    <TouchInput
                                        style={styles.ItemViewRightText}
                                        underlineColorAndroid='transparent'
                                        placeholder='最多30个字符'
                                        value={product.ProductName}
                                        editable={this.state.isChecked}
                                        onChangeText={(t)=> {
                                            product.ProductName = t;
                                            this.changeStateValue({product: product})
                                        }}/>
                                </View>
                                <View style={styles.ItemView}>
                                    <TouchableOpacity style={styles.ItemRightView} disabled={!this.state.isChecked}
                                                      onPress={()=>this.goToProductType()}>
                                    <View style={styles.ItemViewContent}>
                                        <Text style={styles.ItemViewText}>货品类别</Text>
                                            <Text style={styles.ItemViewRightText}>{this.state.productType}</Text>
                                            <Image source={require('../../../images/arrow-right.png') } style={styles.ItemViewRightImg}/>
                                    </View>
                                    </TouchableOpacity>
                                </View>
                            </View>
                        </View>
       /** any codes continued **/
```

I suffer this at the production testing and make boss pissed off... thx @thgala so much, you save my life!

**Comment by luohaoxin** [comment]
@januslo it works well,thanks

**Comment by cpojer** [comment]
Is there anybody who could work on a pull request to React Native to fix this issue permanently?

**Comment by italomlp** [comment]
This bug still occurs in RN 0.57.4. Had someone found a workaround for this?

**Comment by hussainahmad** [comment]
still it is in `0.59.8` , not fixed yet

**Comment by aliazizi** [comment]
Here is typescript version for @januslo solution

```
import React, { Component } from "react";
import {
  TextInput,
  TextInputProps,
  TouchableOpacity,
  View,
} from "react-native";

export default class TouchInput extends Component<TextInputProps> {
  input: TextInput | null = null;
  handleInputPress = () => {
    if (
      this.input &&
      (this.props.editable || this.props.editable == undefined)
    ) {
      this.input.focus();
    }
  }

  assignNumberInputRef(input: TextInput | null) {
    if (input) {
      this.input = input;
    }
  }

  render() {
    return (
      <TouchableOpacity
        activeOpacity={1}
        onPress={this.handleInputPress}
        style={{ flex: 1 }}
      >
        <View pointerEvents="none" style={{ flex: 1 }}>
          <TextInput
            ref={(input) => this.assignNumberInputRef(input)}
            {...this.props}
          />
        </View>
      </TouchableOpacity>
    );
  }
}
```

**Comment by AdamGold** [comment]
Any solution for this bug yet?

**Comment by ammoradi** [comment]
not fixed yet!
still it is in `0.60.4`

**Comment by elmonshareh** [comment]
I tried all the best way that solved my problem 
multiline={true}
blurOnSubmit={true}
it prevents you to make a new line .
know that is a work around but that is the best way till now

**Comment by leviduan** [comment]
Thank you so much, you help me resolve my question.

**Comment by aliazizi** [comment]
Is there any fix for this issue?

**Comment by aliazizi** [comment]
it's about three years and this issue still exist

**Comment by mydesweb** [comment]
I have the same issue, it's 2020 and there is no working solution.. so sad!

**Comment by akhila-antony** [comment]
> multiline={true}

I had an issue in textinput. textAlign propery was given as center and when I'm clearing my input completely the cursor will be at the right end. 
Added multiline={true} fixed my issue.

**Comment by fabriziobertoglio1987** [comment]
I can not reproduce on react-native master. Can you provide a reproducible example or provide explanation of `expected  behaviour` and maybe the documentation you are referring to? My code is

```javascript
import React, { Component } from "react";
import { ScrollView, TextInput, View, Text, StyleSheet } from "react-native";

export default class App extends Component {
  render() {
    return (
      <ScrollView>
        <TextInput
          onFocus={() => console.warn("onFocus")}
          style={{ 
            textAlign: 'right',
            backgroundColor: 'yellow',
          }} />
        <View style={{ height: 2000 }} />
      </ScrollView>
    );
  }
}

const styles = StyleSheet.create({
});
```

this is the output. You will see **console.warn("onFocus")** when I tap on TextInput. Same behaviour without textAlign. It is what I expect with `TextInput`, otherwise how will the user type in it? Double Tap? 

![align_right](https://user-images.githubusercontent.com/24992535/82926321-58574a00-9f7f-11ea-96fc-82c8dd0d4cd0.gif)

**Comment by aliazizi** [comment]
> 
> 
> I can not reproduce on react-native master. Can you provide a reproducible example or provide explanation of `expected behaviour` and maybe the documentation you are referring to? My code is
> 
> ```js
> import React, { Component } from "react";
> import { ScrollView, TextInput, View, Text, StyleSheet } from "react-native";
> 
> export default class App extends Component {
>   render() {
>     return (
>       <ScrollView>
>         <TextInput
>           onFocus={() => console.warn("onFocus")}
>           style={{ 
>             textAlign: 'right',
>             backgroundColor: 'yellow',
>           }} />
>         <View style={{ height: 2000 }} />
>       </ScrollView>
>     );
>   }
> }
> 
> const styles = StyleSheet.create({
> });
> ```
> 
> this is the output. You will see **console.warn("onFocus")** when I tap on TextInput. Same behaviour without textAlign. It is what I expect with `TextInput`, otherwise how will the user type in it? Double Tap?
> 
> ![align_right](https://user-images.githubusercontent.com/24992535/82926321-58574a00-9f7f-11ea-96fc-82c8dd0d4cd0.gif)

try this
https://snack.expo.io/@cooper47/c2a6bb
android version

try to scroll page while first touch is on textinput.
not tapping, just drag on textinput for scroll and see the textinput will be focused.

excepted behavior is page scroll without focus on textinput

**Comment by aliazizi** [comment]
Issue still exist

**Comment by Solsticel** [comment]
is there any solution

**Comment by lucassouza16** [comment]
Out of 100 bugs that react native has, 99 are just in this TextInput component, this is annoying and it seems that nobody is interested in solving it...

**Comment by lucassouza16** [comment]
> 

This solution solves the problem, but it makes it impossible for the user to move the cursor through the text or select it, it is still more practical to use, I did this improvisation but the experience is still not good:

```
import React, { forwardRef, useState, useEffect, useRef, useImperativeHandle } from "react";
import {
    Text,
    StyleSheet,
    TouchableOpacity,
    TextStyle,
    Keyboard,
    TextInput as TextInputComponent,
    TextInputProps as TextInputComponentProps
} from "react-native";

export type TextInputProps = TextInputComponentProps & {};

export type TextInputRef = TextInputComponent & {};

const TextInput = (
    {
        style,
        multiline,
        placeholder,
        value,
        placeholderTextColor,
        textAlign: textAlignProp,
        ...rest
    }: TextInputProps,
    ref: any
) => {

    const inputRef = useRef<TextInputComponent>(null);
    const [widthPlaceholder, setWidthPlaceholder] = useState(0);

    let {
        textAlign,
        fontFamily,
        fontSize,
        fontStyle,
        fontWeight,
        color,
        ...containerStyle
    } = StyleSheet.flatten(style);

    let textStyle: TextStyle = {
        fontFamily,
        fontSize,
        fontStyle,
        fontWeight,
        color
    };

    textAlign = textAlign || textAlignProp;

    if (!multiline) {
        switch (textAlign) {
            case 'center':
                containerStyle.alignItems = 'center';
                break;
            case 'right':
                containerStyle.alignItems = 'flex-end';
                break;
        }
    } else {
        textStyle.textAlign = textAlign;
    }

    useEffect(() => {
        const emitter = Keyboard.addListener('keyboardDidHide',
            () => inputRef.current?.isFocused() && inputRef.current?.blur()
        );

        return () => emitter.remove();
    },
        [inputRef]
    )

    useImperativeHandle(ref, () => inputRef.current);

    return (
        <TouchableOpacity
            style={
                [
                    styles.container,
                    containerStyle
                ]
            }
            activeOpacity={1}
            onPress={() => inputRef.current?.focus()}
        >
            {
                !value && <Text
                    numberOfLines={1}
                    style={
                        [
                            styles.placeholder,
                            textStyle,
                            { color: placeholderTextColor || color }
                        ]
                    }
                    onLayout={
                        ({ nativeEvent }) =>
                            setWidthPlaceholder(nativeEvent.layout.width)
                    }
                >
                    {placeholder}
                </Text>
            }
            <TextInputComponent
                {...rest}
                ref={inputRef}
                value={value}
                multiline={multiline}
                style={
                    [
                        styles.input,
                        textStyle,
                        { width: value ? undefined : widthPlaceholder }
                    ]
                }
            />
        </TouchableOpacity>
    );
};

const styles = StyleSheet.create({
    input: {
        minWidth: 2,
        maxWidth: '100%'
    },
    placeholder: {
        maxWidth: '100%',
        position: 'absolute'
    },
    container: {
        justifyContent: 'center'
    }
});

export default forwardRef<
    TextInputProps,
    TextInputRef
>(TextInput);
```

**Comment by lucassouza16** [comment]
> Este problema está obsoleto porque está aberto há 180 dias sem atividade. Remova o rótulo ou comentário obsoleto ou isso será fechado em 7 dias.

A

**Comment by JuozasIzi1** [comment]
please reopon this

**Comment by omarabualhija** [comment]
+1 RN 81.4

**Comment by Luong-Dev** [comment]
You can refer to the repair instructions: https://github.com/facebook/react-native/issues/25594#issuecomment-4139966603

**Comment by MuhammadRafeh** [comment]
+1 Issue still exists
