### ISSUE TITLE
Extra Gap In Navigator + ListView

### ISSUE THREAD

**Issue by soheil** [facebook/react-native#1217]
For some reason when I use Navigator instead of NavigatorIOS and I put a ListView inside it, it adds a weird margin top the top of the first row (the same height as the status bar)
Anyone ran into this before?

![screen_shot_2015-05-09_at_11_06_14_am](https://cloud.githubusercontent.com/assets/287288/7551398/88a538ea-f63b-11e4-8981-82b9175bdb09.png)

```
  render() {
    return (
      <Navigator
        style={styles.yoloContainer}
        renderScene={this.renderScene}
        initialRoute={{
          component: MyListViewWithNothingFancy,
          navigationBar: <NavigationBar title="Initial View"/>
        }}
        tintColor='#008888' />
    );
  },
  renderScene(route, navigator) {
    var Component = route.component;
    var navBar = route.navigationBar;

    if (navBar) {
      navBar = React.addons.cloneWithProps(navBar, { navigator, route });
    }

    return (
      <View style={styles.navigator}>
        {navBar}
        <Component navigator={navigator} route={route} />
      </View>
    );
  },

```

**Comment by ide** [comment]
Set `automaticallyAdjustContentInsets={false}`. It's trying to accomodate the status bar. Alternatively you could give your scene 44px of top spacing instead of 64px.

**Comment by rxb** [comment]
`automaticallyAdjustContentInsets` is setting insets based on what they should be with if the ScrollView/ListView is the top-level React component. If you have a NavigatorIOS and/or TabBarIOS, it will also adjust for those. Super useful in those conditions.

If there are any other React components taking up space (not absolutely positioned) above or below your ScrollView/ListView, the math will be off and it's better to just set it to false and deal with the offsets manually.

**Comment by christopherdro** [comment]
@soheil Were you able to figure this one out?

**Comment by soheil** [comment]
yes it was because I had in inside a navigator except that it was one of
two components in the navigator (split screen with map on top and list at
the bottom) so I guess it always assumes there will be a nav bar so it adds
a top padding regardless.

**Comment by brentvatne** [comment]
Thanks for the follow up @soheil!

@christopherdro #fridaytriage

**Comment by soheil** [comment]
Although I hacked my code to work I think this is still an issue that needs
to be fixed though, in case others run into it. Basically a view should not
alway add extra padding on top when it's inside a navigator, it should only
do that when it's the first element (top element.)

**Comment by brentvatne** [comment]
@soheil - happy to reopen if we can get an example on 0.5.0-rc up on rnplay :smile:

**Comment by chengyin** [comment]
I hit this today with 0.26.0.

<img width="487" alt="screen shot 2016-05-22 at 6 05 37 pm" src="https://cloud.githubusercontent.com/assets/128819/15457931/ff1e268a-2047-11e6-97f8-0701f00dba07.png">

The view is super simple:

```javascript
// Container View render

      <NavigatorIOS
        style={styles.container}
        itemWrapperStyle={styles.itemWrapper}
        initialRoute={{
          component: MovieList,
          title: 'Movies',
          passProps: {
            movies: this.state.movies,
          },
        }}
      />

// Styles

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  itemWrapper: {
    flex: 1,
  }
});
```

`MovieList`'s render function returns a `ListView`. 

I would expect `automaticallyAdjustContentInsets` set the `inset` correctly to accommodating the navbar automatically. It seems to me that for some reasons the inset is set to a wrong value here.

**Comment by TasneemBohra** [comment]
@soheil  can you please share your code how you achieved it ?
