### ISSUE TITLE
[0.42] Commits to cherry pick into stable

### ISSUE THREAD

**Issue by grabbou** [facebook/react-native#12172]

**Comment by ide** [comment]
I cherry picked and pushed #11676 (Update React versions to non-RC)

**Comment by nihgwu** [comment]
https://github.com/facebook/react-native/commit/eb54290a3aa82158b6a735ec2fbd27580d1adec0
https://github.com/facebook/react-native/commit/61848ea2f36a2a9ae254a5ea5a6d2136791eb215
what about those two, right now if I use the Nodes as the UIManager implementation, app crashes on Android when launching with RN0.42RC, but it works great with RN0.41RC

**Comment by alloy** [comment]
#12089 - 031cb2045de0ed430d539eb3d5c44baa2fe3bc8b ?

For the release notes, it might be useful to include https://github.com/facebook/react-native/pull/12089#issuecomment-277553904. Let me know if you need a customised version.

**Comment by guysegal** [comment]
I think that you should highly consider cherry picking alloy's PR into 0.42.
This PR solves a lot of issues to swift-pod based projects.
It is not possible to consume react native from master (because of the lack of android binaries) so the only options are either fork react native (and build android from source) or cherry pick it.
I personally don't like to fork for these reasons and I think the PR implementation is pretty simple and safe to merge

**Comment by grabbou** [comment]
I'll cherry-pick all these today and push a new release today.

**Comment by guysegal** [comment]
Thank you very much!

**Comment by guysegal** [comment]
@grabbou did you get to cherry pick it? I can't find it in 0.42 rc2

**Comment by AleF83** [comment]
@grabbou. Does this commit ([#12089](https://github.com/facebook/react-native/pull/12089) - [`031cb20`](https://github.com/facebook/react-native/commit/031cb2045de0ed430d539eb3d5c44baa2fe3bc8b)) supposed to be contained in rc.2/3? It will help me a lot! 10x

**Comment by alloy** [comment]
@guysegal @AleF83 No new RC has been cut yet. @grabbou said he would include all the above commits, so it should all be in the next RC.

**Comment by grabbou** [comment]
@alloy PR was cherry-picked and the build is pending.
@ide PR was closed, changes were not picked.

**Comment by alloy** [comment]
@grabbou This can be closed.
