### ISSUE TITLE
[ScrollView&ListView] When using scrollview, the second page of ListView can not click Back when scrolling

### ISSUE THREAD

**Issue by naivehhr** [facebook/react-native#12186]
#### When using scrollview, the second page of LisvtView can not click Back when scrolling

![1211](https://cloud.githubusercontent.com/assets/5243456/22584870/c135922e-ea2f-11e6-987d-5c9ba6d2f1d6.gif)

* SecondPage Code:
```
render() {
    return (
      <View style={{flex: 1}}>
        <TouchableOpacity onPress={() => {this.props.navigator.pop()}}
          style={{ marginTop: 70}}
          >
          <Text >
            Back
          </Text>
        </TouchableOpacity>
        <ListView
          dataSource={this.state.dataSource}
          renderRow={this.renderRow}
        />
      </View>
    );
  }
```

### Additional Information

* React Native version: 0.40.0
* Platform: iOS
* Operating System: MacOS

**Comment by hramos** [comment]
Closing as ListView is deprecated in 0.43. Use FlatList.

**Comment by naivehhr** [comment]
👌👌 😁
