### ISSUE TITLE
[Timer] EventDispatcher sendDeviceEventWithName only called once.

### ISSUE THREAD

**Issue by mintuz** [facebook/react-native#1218]
Hello, I think the EventDispatcher sendDeviceEventWithName has a bug in which the EventDispatcher sendDeviceEventWithName is only called once initially until you close the app down to the background and then reopen it. Once you open it the Events seem to be triggered as expected.

I have created a native bridge to a library located https://github.com/omergul123/Discovery It's also worth pointing out that the library works fine whilst not in a React Native project.

My bridge looks like this

```
//
//  DiscoveryManager.m
//  DiscoveryExample
//
//  Created by Adam Bulmer on 07/05/2015.
//  Copyright (c) 2015 Adam Bulmer All rights reserved.
//

#import <Foundation/Foundation.h>
#import "DiscoveryManager.h"

@implementation DiscoveryManager

  @synthesize bridge = _bridge;

  RCT_EXPORT_MODULE()

  RCT_EXPORT_METHOD(startAdvertising:(NSString *)uuidString
                    username:(NSString*)username) {
    
    NSMutableArray *usernameArrays = [[NSMutableArray alloc] init];
    NSLog(@"startAdvertising called");
    
    // create our App UUID.
    CBUUID *uuid = [CBUUID UUIDWithString:uuidString];
      
    // start Discovery API
    self.discovery = [[Discovery alloc] initWithAppUUID:uuid username:username usersBlock:^(NSArray *users, BOOL usersChanged) {
        
      NSLog(@"users found in ObjC - %@", users);
      
      // Hacky
      for (BLEUser *user in users) {
        [usernameArrays addObject:user.username];
      }
        
      [self.bridge.eventDispatcher sendDeviceEventWithName:@"FoundUsers" body:@{@"users":usernameArrays}];
    }];
  }

@end
```

The Javascript component looks like this.

```
var React = require('react-native');
var LoginView = require('./App/views/Login.ios.js');
var AuthStore = require('./App/stores/AuthStore.ios.js');
var DiscoveryManager = require('NativeModules').DiscoveryManager;

const APP_UUID = '6969EFE7-C07E-4497-95E7-105C01152421';

var {
  View, 
  DeviceEventEmitter, 
  AlertIOS
} = React;

var App = React.createClass({
  getInitialState: function() {
    
    return {
      loggedIn: false
    };
  },
  onAuthChange: function(authObj) {
    
    this.setState({loggedIn:authObj});
    DiscoveryManager.startAdvertising(APP_UUID, 'mintuz');
  },
  onUsersChange: function(obj) {
    
    console.log(obj);

    AlertIOS.alert(
      'User Found',
      obj.users[0]
    );
  },
  componentWillMount: function() {

    console.log("will mount");

    AuthStore.listen(this.onAuthChange);
    DeviceEventEmitter.addListener('FoundUsers', this.onUsersChange);
  },
  render: function() {
    
    if(!this.state.loggedIn){
      return (<LoginView></LoginView>);
    }

    return (<View style={{flexDirection: 'row', height: 100, padding: 20}}>
      <View style={{backgroundColor: 'blue', flex: 0.3}} />
      <View style={{backgroundColor: 'red', flex: 0.5}} />
    </View>);
  }
});

React.AppRegistry.registerComponent('TestAppSpike', () => App);
```

**Comment by mintuz** [comment]
To add to this I have found out that the block for Discovery library isn't called multiple times until you close the app and reopen it. It does however work if its not called within a React Native environment. Looking at the Discovery library the only things that I think could be breaking with React Native are the timers and queues that are being set. Any help would be appreciated.

**Comment by ide** [comment]
RN pauses timers when the app is backgrounded. Not sure why this is -- it probably shouldn't do this at the infrastructure level.

**Comment by mintuz** [comment]
The timers don't seem to fire until the app is closed and reopened.

**Comment by vjeux** [comment]
cc @nicklockwood and @a2, this is weird that timers are suppressed

**Comment by a2** [comment]
I assume this has to do with the way run loops work?

**Comment by mintuz** [comment]
I know NSTimers work without the use of React Native within a standard native app.

**Comment by ide** [comment]
@a2 that could be part of it since the run loop is driven by the display link. This for sure is part of the problem: https://github.com/facebook/react-native/blob/4eece85b6b96e4d43842b0b59ae1ad1f84e39b0f/React/Modules/RCTTiming.m#L89

**Comment by a2** [comment]
@ide That would definitely do it! :confused:

**Comment by mintuz** [comment]
Any update on this?

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by mintuz** [comment]
Any update on this, sorry for the spam. Just seems to have gone quiet.

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/timer-eventdispatcher-senddeviceeventwithname-only-called-once
