### ISSUE TITLE
Cannot add a child that doesn't have a CSS node to a node without a measure function

### ISSUE THREAD

**Issue by franrios** [facebook/react-native#12195]
I upgraded react version from 0.39 to 0.41 and I got this error: 

![image](https://cloud.githubusercontent.com/assets/7302131/22599341/deffffea-ea36-11e6-980a-4e994d9b5e02.png)

I tried to upgrade when 0.40 was released but I got the same error.

### Description

[FILL THIS OUT: Explain what you did, what you expected to happen, and what actually happens.]

### Additional Information

* React Native version: [0.41]
* Platform: [iOS and Android]
* Operating System: [ MacOS ]

**Comment by demonhunterunderdarkness** [comment]
same problem, anyone else could resolve it ? thx in advance

**Comment by demonhunterunderdarkness** [comment]
some dev info missed.
react-native-svg 4.4.1
I'm using react-native-pathjs-charts for render charts purpose.I had imported related package to MainApplication.java. I just run examples which  under react-native-pathjs-charts, but not works fine

**Comment by janicduplessis** [comment]
This is a bug with react-native-svg and RN 0.40+, if you update to rn-svg to 4.5.0+ it shoud fix this.

**Comment by demonhunterunderdarkness** [comment]
after upgrade react-native-svn, errors gone, thanks for help~@janicduplessis

**Comment by joshuapinter** [comment]
Just to help others, I was getting this because I forgot to wrap my `<Circle/>` in a `<Svg>` tag.
