### ISSUE TITLE
When using ActivityIndicatorIOS then giving error: Element type is invalid: expected a string (for built in components)

### ISSUE THREAD

**Issue by amourya-systango** [facebook/react-native#12191]
I am using ActivityIndicatorIOS in JS component in version RN 0.40 then its giving me error Element type is invalid: expected a string (for built in components)

**Comment by nihgwu** [comment]
Because `ActivityIndicatorIOS` has been depreciated for quite a long time and is removed from the source now, you should use `ActivityIndicator`.

**Comment by amourya-systango** [comment]
Ohk, Thank you it is working
