### ISSUE TITLE
Packager does not detect changes when `index.android.js` is a symlink

### ISSUE THREAD

**Issue by fvgs** [facebook/react-native#12204]
### Description
I replaced the default `index.android.js` with a symlink of the same name pointing to `src/index.js`. I expected this to have no observable impact on the functionality of the packager. I expected changes made to `src/index.js` to be detected by the packager (when prompted to rebuild) and that it would rebuild accordingly. Instead, when changes are made to `src/index.js` and I double-tap `R` in the Android emulator to rebuild, the packager outputs:

```
Bundling `index.android.js`
  No module changed.
```

indicating it did not detect any changes and thus did not rebuild. Thus, the emulator continues to render the app according to the old file state and does not render the changes.

### Reproduction

Replace `index.android.js` with a symlink to another file. Make changes to the file and observe that the packager does not detect the changes when prompted to rebuild.

### Solution

The packager needs to follow symlinks when checking for changes to `index.android.js`.

### Additional Information

* React Native version: 0.41.0
* Platform: Android (but probably iOS too)
* Operating System: macOS

**Comment by brentvatne** [comment]
The packager does not support symlinks because Watchman does not support symlinks :(
