### ISSUE TITLE
Geolocation  - null is not an object (evaluating 'cb.apply')

### ISSUE THREAD

**Issue by bretrouse** [facebook/react-native#1220]
Using the example code available here: http://facebook.github.io/react-native/docs/geolocation.html#content I get the following error:

![ios simulator screen shot may 9 2015 5 53 39 pm](https://cloud.githubusercontent.com/assets/578522/7552181/5b2b1694-f674-11e4-863a-2fe6ba2bae06.png)

**Comment by bretrouse** [comment]
If you dismiss this screen, the location is working as expected

**Comment by auser** [comment]
Bump: I see this error as well

**Comment by henter** [comment]
here is the solution https://github.com/facebook/react-native/pull/1226

**Comment by brentvatne** [comment]
Thanks @henter!

@christopherdro #fridaytriage

**Comment by zxiest** [comment]
@henter's link did it for me; thanks!
