### ISSUE TITLE
Geolocation not working when debugging in Chrome

### ISSUE THREAD

**Issue by bretrouse** [facebook/react-native#1221]
Using the example code here: http://facebook.github.io/react-native/docs/geolocation.html#content

When debugging in Chrome permission is always denied, even when granted via the browser and the app, resulting in the below error when the simulator is not in focus

![ios simulator screen shot may 9 2015 6 08 24 pm](https://cloud.githubusercontent.com/assets/578522/7552214/6d9be702-f676-11e4-816f-7ce2986bc399.png)

**Comment by bretrouse** [comment]
Increasing the timeout gives you more time to get the simulator window into focus.

**Comment by brentvatne** [comment]
Thanks @bretrouse for the followup!
