### ISSUE TITLE
Trouble running react-native-git-upgrade

### ISSUE THREAD

**Issue by cwahlfeldt** [facebook/react-native#12210]
### Description

I am receiving the following errors when attempting to upgrade from 0.40 to 0.41. I would also like to note that this exact same error happened during the 0.39 to 0.40 upgrade as well.

This is the output of running `react-native-git-upgrade` in my projects directory:
```
git-upgrade info Check for updates
git-upgrade info Read package.json files
git-upgrade info Check declared version
git-upgrade info Check matching versions
git-upgrade info Check React peer dependency
git-upgrade info Check that Git is installed
git-upgrade info Get information from NPM registry
git-upgrade info Upgrading to React Native 0.41.1, React ~15.4.0-rc.4
git-upgrade info Setup temporary working directory
git-upgrade info Configure Git environment
git-upgrade info Init Git repository
git-upgrade info Add all files to commit
git-upgrade info Commit current project sources
git-upgrade info Create a tag before updating sources
git-upgrade info Generate old version template
git-upgrade info Add updated files to commit
git-upgrade info Commit old version template
git-upgrade info Install the new version
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
git-upgrade info Generate new version template
git-upgrade info Add updated files to commit
git-upgrade info Commit new version template
git-upgrade info Generate the patch between the 2 versions
git-upgrade info Save the patch in temp directory
git-upgrade info Reset the 2 temporary commits
git-upgrade info Apply the patch
error: patch failed: ios/Queue.xcodeproj/project.pbxproj:22
Falling back to three-way merge...
Applied patch to 'ios/Queue.xcodeproj/project.pbxproj' with conflicts.
U ios/Queue.xcodeproj/project.pbxproj
git-upgrade WARN The upgrade process succeeded but there might be conflicts to be resolved. See above for the list of files that have merge conflicts.
git-upgrade info Upgrade done
```

Then when trying to build my project, it fails with:
```
xcodebuild: error: Unable to read project 'Queue.xcodeproj'.
	Reason: Project /Users/cwahlfeldt/Apps/Queue_Update_Test/ios/Queue.xcodeproj cannot be opened because the project file cannot be parsed.
```

### Reproduction

Run the upgrade command `react-native-git-upgrade` in your projects root directory.

### Solution

Not sure yet 👍 

### Additional Information

* React Native version: rn: 0.40.0 | cli: 2.0.1
* Platform: iOS
* Operating System: mac OS 10.12.2

**Comment by ncuillery** [comment]
The output shows that your project.pbxproj is conflicted. It contains conflicts which need to be resolved. See http://facebook.github.io/react-native/docs/upgrading.html#4-resolve-the-conflicts

Because of the conflict delimiters (`>>>>>>>>` and `<<<<<<<<`) your project is considered as corrupted by Xcode, until you resolve the conflicts.

**Comment by ncuillery** [comment]
@facebook-github-bot close

**Comment by cdesch** [comment]
@ncuillery I understand that as well, although the documentation isn't exactly clear on how we are to approaching the resolution for these conflicts. 

This example, just like the one generated by [my upgrade](https://gist.github.com/cdesch/1f5d4224360ff086034da95a31942320) didn't produce anything that resembled a conflict, unless I'm missing something here. 

     <<<<<<< ours
    CODE_SIGN_IDENTITY = "iPhone Developer";
    FRAMEWORK_SEARCH_PATHS = (
      "$(inherited)",
      "$(PROJECT_DIR)/HockeySDK.embeddedframework",
      "$(PROJECT_DIR)/HockeySDK-iOS/HockeySDK.embeddedframework",
    );
     =======
        CURRENT_PROJECT_VERSION = 1;
     >>>>>>> theirs

**Comment by almadsen** [comment]
Having same problem with upgrade and getting .xcodeproj corrupt.
I also am having trouble find any way of reining what's a real conflict, what to delete and what not to.
Isn't there a simpler way of doing this, or at least a somewhat more logical way?

**Comment by cwahlfeldt** [comment]
I agree @almadsen, it does seem a little confusing. You should be able to delete everything from the `<<<<<<<<<<< ours` to the `==========` and be ok. You may have to make changes to your Xcode project again though which might be a little cumbersome. My problem was that I was confused as to make changes. I thought the cli tool would spit out more info and tell em exactly where to change it. It should have an extra step telling the use that they need to go open this file and check its conflicts or something like that.

**Comment by dasblitz** [comment]
I ran into something similar, ending up with a corrupted .xcodeproj. The error was in the part that looked like this:

````
>>>>>>>>>> ours
LIBRARY_SEARCH_PATHS = (
	"$(inherited)",
	"\"$(SRCROOT)/$(TARGET_NAME)\"",
	"\"$(SRCROOT)/$(TARGET_NAME)\"",
	"\"$(SRCROOT)/$(TARGET_NAME)\"",
	"\"$(SRCROOT)/$(TARGET_NAME)\"",
	"\"$(SRCROOT)/$(TARGET_NAME)\"",
	"\"$(SRCROOT)/$(TARGET_NAME)\"",
==========
OTHER_LDFLAGS = (
	"-ObjC",
	"-lc++",
);
>>>>>>>>>> theirs
````

In my first attempt to fix it I only deleted the lines with
`>>>>>>> ours`
`===========`
`>>>>>>> theirs`

This will result in a corrupt file because the line with `=========` should have been replaced with `);`

In my case there were two code blocks that looked like this, where I needed to put the `);` back in.

It's hard to see what's going on in this file. I left 'ours' as well as 'theirs' and the project builds happily ever after.

**Comment by samparmenter** [comment]
Yeah this is a bit of a mess really. I have a ~1600 line file now where I have to go through and fix all these issues by hand.

**Comment by fungilation** [comment]
What happened to the interactive react-native upgrade, where it actually ASK you whether you want to resolve conflicts or simply overwrite it with the new version from latest RN? Because overwrite is what I want, instead of resolving a thousand conflicts.

I can say that most would want with `project.pbxproj`, to have only "theirs" (RN) and not "ours". We can unlink and re-link native modules after upgrading RN.

**Comment by dcz-switcher** [comment]
It's my first attempt with the "new way" and I am lost ...
how resolve conflicts ?
I suppose it can be made with git mergetool, but my project isn't a git one, so every git command failed

the new way maybe coolest but "how manage conflicts" is not really describe in documentation

**Comment by ncuillery** [comment]
I close this in favor of #12261 since a single place to discuss about react-native-git-upgrade is better than two.

**Comment by ncuillery** [comment]
@facebook-github-bot duplicate #12261

**Comment by ncuillery** [comment]
@mkonicek I'm in the whitelist [here](https://github.com/facebook/react-native/blob/master/bots/IssueCommands.txt#L1) but the bot doesn't obey me.

Is there another configuration to do ?

**Comment by jason-shen** [comment]
just open the file with visual studio code, and find the <<<<<< then highlight the light then it will pop up if you which one you accept, simple hope this help some one out, i got it working in the first shot, everything works
