### ISSUE TITLE
skewX, skewY does not work!

### ISSUE THREAD

**Issue by Pourya8366** [facebook/react-native#12212]
### Description

i styled a `<View />` with `transform: [{skewX: "-20deg"}]` and it does nothing at all!
when i use skewY it do rotate!!!
### Reproduction

https://rnplay.org/apps/FlXziw

### Solution

i think it's a react native bug!

### Additional Information

* React Native version:  0.41.0
* Platform: Android
* Operating System: Windows

**Comment by glcrazier** [comment]
There is no built-in skew animation on Android anyway.

**Comment by Fenwil** [comment]
Having the same problem here. The transform skewY does works, but if you add skewX then skewY stops working. Even using skewX only will not work.

**Comment by roshangm1** [comment]
I am having the same problem as @Fenwil . Any workarounds ?

**Comment by Pourya8366** [comment]
@glcrazier there is a skew function in canvas library of android and it works there!

**Comment by glcrazier** [comment]
@Pourya8366 Cool, thanks for correction! I realized that matrix may do the work as well. Which function are you referring to in canvas library?

**Comment by roshangm1** [comment]
@Pourya8366 hey did you find any workarounds ?

**Comment by Pourya8366** [comment]
@glcrazier i use this function and it works!
https://developer.android.com/reference/android/graphics/Canvas.html#skew(float, float)

**Comment by Pourya8366** [comment]
@roshangm1 No, i found nothing yet! :(

**Comment by glcrazier** [comment]
it works for canvas, but it is not a good option for animation framework in my opinion. I noticed that in latest release this issue was resolved. You can take a shot

**Comment by roshangm1** [comment]
@glcrazier I think, not yet resolved. :/

**Comment by Fenwil** [comment]
@roshangm1 In [v0.42](https://github.com/facebook/react-native/releases/tag/v0.42.0) is fixed:
Fix skew transform on native side ([c681959](https://github.com/facebook/react-native/commit/c68195929b3d7f7cc1370e36f3e22b4cbd2d2707)) - @MaxGraey
I didn't try it yet but I guess it works now

**Comment by roshangm1** [comment]
I tried it. But it doesn't seem to be working for me. Can you confirm if
it's working for you guys?

**Comment by MaxGraey** [comment]
I confirm, for Android skew transform is not working.
Digging deep in ReactAndroid's sources I found the following:

1. Code to transform the view is made very inefficient. In order to apply transformation matrix firstly decompose to scale/rotate/skew/translation and applied separately to view.setTranslationX, view.setTranslationY and etc.

2. Android's view does't has methods for setSkewX and setSkewX at all. "setMatrix" absent as well!

So I see only two ways:

1. Use view's setAnimationMatrix.
2. Subclassing View to obtain direct access to private mRenderNode and his matrix property.

Both way need hard refactoring existing code

**Comment by lirui0407** [comment]
+1, skewX skewY still doesn't work.
Aug 1,2017

**Comment by larspa** [comment]
I would like to know if there is anybody who found a fix for this problem as I am having the same problem.
Why would you close an issue without knowing if it is being fixed?

**Comment by larspa** [comment]
@MaxGraey I encountered the same problem and I wonder what kind of solution there is besides diving into the native code. I find it weird that only the skewX is not working while the skewY is.

**Comment by MaxGraey** [comment]
Theoreticlly you can simulate 2d skew transform via 3d rotation by X and Y axis simultaneously with ortho projection

**Comment by dogofpavlov** [comment]
Hmm, unfortunately a year and 3 months later, this is STILL not fixed. skewX doesn't work on Android, while skewY does. If you add a skewX, the skewY stops working.

I was REALLY sad to discover a lot of work I've done for an isometric game doesn't work whatsoever on Android because of this bug. :(

**Comment by huqiliang** [comment]
react-native": "0.55.4"

 both skewX and skewY doesn't work on Android, is this issue solved ?

**Comment by yeomann** [comment]
same 0.57.0 still no progress i guess?

**Comment by RichardLindhout** [comment]
Not working +1 for this.

**Comment by Fortidude** [comment]
skewY and skewX not working on Android. ANy workaroud?
