### ISSUE TITLE
CameraRoll callbacks are not idiomatic.

### ISSUE THREAD

**Issue by jtremback** [facebook/react-native#1222]
I noticed that the CameraRoll API uses `successCallback, errorCallback` instead of `callback?: ?(error: ?Error) => void`. Seems like it would be a good idea for callback APIs in these modules to be done in the standard way. There are a lot of JS libraries that can deal with this type of callback, and it's a good practice to use existing conventions instead of just inventing new ones.

**Comment by ide** [comment]
https://github.com/facebook/react-native/pull/1232 provides a foundation to address this.

**Comment by brentvatne** [comment]
Closed in favour of @ide's PR, thanks @jtremback!
