### ISSUE TITLE
No devices are booted

### ISSUE THREAD

**Issue by rumanhassan** [facebook/react-native#12226]
### Description

I am trying to run AwesomeProject app on ios, facing `No Device found` issue. Followed below steps :
I ran `sudo react-native run-ios` the build was failing because of port issue, as i don't want to turn off my firewall, so i modified `project.pbxproj` and updated all ports 8081 to 8089, then i ran  `sudo react-native run-ios` this time the build was success but i was getting `No devices are booted` after successful build and in simulator the screen was blank.

Then i followed the suggestion here
http://stackoverflow.com/questions/38293243/react-native-build-succeed-but-no-devices-are-booted
 to run `sudo react-native run-ios` without sudo, but the build was failing without sudo.

Any suggestion or help i appreciated.

**Comment by janzenz** [comment]
What was the error when not running on `sudo`? I think it shouldn't be necessary to run on `sudo`.

**Comment by rumanhassan** [comment]
when i am running without sudo, build is failing with following error

`2017-02-13 02:19:18.691 xcodebuild[1632:644053] Error saving log: Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied" UserInfo={NSFilePath=/Users/ruhassan/react-project/AwesomeProject/ios/build/Logs/Build/26C54236-CFBB-4A0F-AC6F-BB1B93589801.xcactivitylog, NSLocalizedDescription=Permission denied} | User info: {
    NSFilePath = "/Users/ruhassan/react-project/AwesomeProject/ios/build/Logs/Build/26C54236-CFBB-4A0F-AC6F-BB1B93589801.xcactivitylog";
    NSLocalizedDescription = "Permission denied";
}`

i believe permission denied is because i haven't used sudo.

**Comment by janzenz** [comment]
Looks your xcode doesn't have enough rights to save the log files in the mentioned directory around "Error saving log:"
