### ISSUE TITLE
react-native-git-upgrade deletes my non-versioned files and fails

### ISSUE THREAD

**Issue by antoinerousseau** [facebook/react-native#12237]
### Description

I installed react-native-git-upgrade@0.2.5 and ran it on my project.

### Reproduction

	$ react-native-git-upgrade
	git-upgrade info Check for updates
	git-upgrade info Read package.json files
	git-upgrade info Check declared version
	git-upgrade info Check matching versions
	git-upgrade info Check React peer dependency
	git-upgrade info Check that Git is installed
	git-upgrade info Get information from NPM registry
	git-upgrade info Upgrading to React Native 0.41.2, React ~15.4.0
	git-upgrade info Setup temporary working directory
	git-upgrade info Configure Git environment
	git-upgrade info Init Git repository
	git-upgrade info Add all files to commit
	git-upgrade info Commit current project sources
	git-upgrade info Create a tag before updating sources
	git-upgrade info Generate old version template
	git-upgrade info Add updated files to commit
	git-upgrade info Commit old version template
	git-upgrade info Install the new version
	npm WARN deprecated node-uuid@1.4.7: use uuid module instead
	git-upgrade info Generate new version template
	git-upgrade info Add updated files to commit
	git-upgrade info Commit new version template
	git-upgrade info Generate the patch between the 2 versions
	git-upgrade info Save the patch in temp directory
	git-upgrade info Reset the 2 temporary commits
	git-upgrade info Apply the patch
	fatal: unrecognized input
	git-upgrade WARN The upgrade process succeeded but there might be conflicts to be resolved. See above for the list of files that have merge conflicts.
	git-upgrade info Upgrade done
	$

And in the end, no file is modified, and some files are missing, for example `android/app/google-services.json` (present in my `.gitignore`)

### Solution

No idea

### Additional Information

* React Native version: just installed 0.41.2, wanted to upgrade RN templates according to it
* Platform: n/a
* Operating System: macOS

Note: my Android/iOS package name is `net.tribeez` (my `package.json` name is `tribeez`)

**Comment by ncuillery** [comment]
Ok I reproduce the deletion by running the Git commands manually, just like the tool does: https://gist.github.com/ncuillery/4b09e36d772601301cf0d0c94dcde692. I think I got it:

The first step of the process consists in restoring the template of your current RN version, just like it would have been generated by the init command. So your `.gitignore` file is replaced by this one https://github.com/facebook/react-native/blob/master/local-cli/templates/HelloWorld/_gitignore for the rest of the process.

From now on, `android/app/google-services.json` is no longer ignored. So when the files are committed, it is considered as "added". 

At the end, the `git reset --hard` command reverts the commit and logically deletes the file 😱

**Comment by koenpunt** [comment]
`.env` files also disappear, which I'm not happy about...

**Comment by jwarby** [comment]
Also lost some files which were `.gitignore`'d after using the upgrade tool... :disappointed:

**Comment by rdixonbhw** [comment]
I'm assuming the files it obliterates are just as gone as if I'd run `rm` on them? If so that's a pretty significant setback for me.

**Comment by pcxiong** [comment]
react-native-git-upgrade deletes my jks file.
I just *****

**Comment by didil** [comment]
same , some gitignored files get deleted and I have find them in my backups, pretty annoying if you dont expect it ...

**Comment by joncursi** [comment]
Ditto. I use react-native-config to store environment variables for development, staging, and production. Git upgrade wipes out these files since they are not committed to github (contain secrets). Pain in the butt to have to replace them every month when a new RN version comes out.

**Comment by rdixonbhw** [comment]
I've started using rn-diff for upgrades, usually pretty quick and less frustrating to do it manually. https://github.com/ncuillery/rn-diff

**Comment by ujwal-setlur** [comment]
This is driving me nuts too! Every time I upgrade, my .env files and frameworks under ios/Frameworks are deleted (stuff under Frameworks is gitignore'd). First time build always fails before I remember to restore from backup...

Will check out https://github.com/ncuillery/rn-diff

**Comment by Hauuguu** [comment]
Any update on this? Did you all end up switching to rn-diff?

**Comment by antoinerousseau** [comment]
@Hauuguu I did, yes

**Comment by MrToph** [comment]
Same here, just lost all my files that were gitignored ...

**Comment by joeybaker** [comment]
This is very much still happening to everyone who uses `react-native-git-upgrade` and uses a `.gitignore`.

**Comment by ujwal-setlur** [comment]
I stopped using react-native-git-upgrade in favor of rn-diff

**Comment by FredyC** [comment]
I think this tool should be removed from the docs as a recommended way since it's this much unsafe. I lost some files as I did not really expect them to be deleted so I did not have backups :/

Why is there no response from the team on this except @hramos tagging it with a label?

**Comment by antoinerousseau** [comment]
Looks like https://github.com/facebook/react-native/commit/7492860 resolved this.
