### ISSUE TITLE
bug in ListView doc

### ISSUE THREAD

**Issue by umhan35** [facebook/react-native#1223]
On http://facebook.github.io/react-native/docs/listview.html#props, the link **ScrollView props...** should be http://facebook.github.io/react-native/docs/scrollview.html#props rather than http://facebook.github.io/react-native/docs/scrollview.html#proptypes (i.e., change #proptypes to #props)

**Comment by ide** [comment]
Could you please send a PR that fixes it? Look at website/layout/AutodocsLayout.js as a starting point.

**Comment by umhan35** [comment]
😀 I was trying to find that file but couldn't, so I directly created this issue. I'll definitely take a look. It'd be an easy fix after all.
