### ISSUE TITLE
Can't import js file in parent folder

### ISSUE THREAD

**Issue by QuantumInformation** [facebook/react-native#12241]
### Description

Can't import js file in parent folder
### Reproduction
import {ReactNativeCron} from '../ReactNativeCron' gives error:
`Directory /Users/nikos/WebstormProjects/react-native-cron/ReactNativeCron doesn't exist`

If I move the file to ./ReactNativeCron it works

* React Native version:     "react-native": "0.40.0"

* Platform: iOS
* Operating System:MacOS

see https://github.com/QuantumInformation/react-native-cron/commit/ea7fdf2b2d8e280d630baf855da4b4d888772195

**Comment by brentvatne** [comment]
I don't believe that this is a bug, you should not be able to read files from outside of your project's root.

**Comment by gensc004** [comment]
@hnryjms and I ran in to this as well. It is an issue for us because our react-native app is a submodule of our repo that contains a web app and server code. We have a `lib` directory that contains useful JS code for all projects, and would like to be able to use it everywhere. We could make the `lib` directory a local NPM module and install it into both projects, but that makes local development somewhat annoying.

The solution we found was to add the file called [`rn-cli.config.js`](https://github.com/facebook/react-native/blob/master/local-cli/util/Config.js#L20) at the Mobile app's root which is the default file the react-native packager looks at for specifying run configurations. 

```js
const Path = require('path');

module.exports = {
    getProjectRoots: () => [ __dirname, Path.join(__dirname, "..") ]
};
```

**Comment by doque** [comment]
@gensc004 Can you specify? I'm going up two directories, but adding ` __dirname, Path.join(__dirname, "../..")` doesn't work for me:
```
├── components
│   └── Demo.js      # this is the component I want to include from both web and native
├── examples
│   ├── native
│   │   ├── App.js
│   │   ├── App.test.js
│   │   ├── Demo.js
│   │   ├── README.md
│   │   ├── app.json
│   │   ├── package.json
│   │   ├── rn-cli.config.js
│   │   └── yarn.lock
│   └── web
│       └── index.js
└── index.js
```

**Comment by gensc004** [comment]
@doque, Just to make sure, have you rebuilt your project after adding the rn-cli config file?

**Comment by kylebebak** [comment]
@gensc004 
I've been getting the same error as @doque . I'm trying to import a module that's at `../components/Module` relative to the root of my RN project, and I've added the `rn-cli.config.js` you suggested.

The error shows that the path to the component I want to import is corrrect, but it says that directory doesn't exist.

**Comment by doque** [comment]
I've built the project numerous times. I've set up from-scratch using both `create-react-native-app` and `react-native init`, in both cases I'm unable to require modules outside the respective root directories. Adding the rn-cli.config.js did not help, even running `npm link` didn't work.
The only thing that vaguely resembled a solution was manually copying my modules to `node_modules` of the mobile app, which obviously is no solution to this.

**Comment by QuantumInformation** [comment]
Can someone reopen this ticket?

**Comment by gensc004** [comment]
@doque, @kylebebak What versions of react-native are you on? I checked back through my solution to see if I missed any steps and haven't found anything that seems amiss, but I will keep trying to help where I can. Also, I currently only use this solution for IOS and haven't tried it on android so that may be part of the problem.

**Comment by gensc004** [comment]
I just made a new project with react-native init, and tried the solution on IOS (I only have access to an IOS emulator at the moment). After adding the rn-config file, closing my bundler, and re-running the build it worked for me. The only thing I can see being a problem is that the solution doesn't work on Android. If someone could confirm that they are seeing the solution not working on Android that would be awesome, and then we can try to find a solution that works for both!

**Comment by doque** [comment]
I'm running these versions:
```
➜  ~ react-native --version                                                       17:59:11
react-native-cli: 2.0.1
react-native: n/a - not inside a React Native project directory
➜  ~ node --version                                                               17:59:21
v6.9.4
➜  ~ npm --version                                                                17:59:25
3.10.10
```

**Comment by gensc004** [comment]
@doque, doesn't look like it is a version problem, are you testing on android or ios?

**Comment by doque** [comment]
I'm running `react-native run-ios`. BTW this issue occurs as well if using `create-react-native-app` and Expo.

**Comment by ninsy** [comment]
Exact stuff happens with command 'react-native run-android'. What's even worse, I've also moved my source file into project's root and still receiving error 'Unable to resolve module ... Directory doesn't exist".
React-Native ver: 0.45.0, React ver: 16.0.0-alpha.12

**Comment by kylebebak** [comment]
@gensc004 

I'm using Expo 18, which means I'm on RN 0.45.0. We found a work-around and no longer need to import modules from outside the project root, but it would be nice to know if you guys find a solution to this problem.

**Comment by doque** [comment]
@kylebebak what's your workaround?

**Comment by kylebebak** [comment]
@doque 
The workaround is only for our specific use case, which was to share components between different react native apps that live in the same repo.

I'm going to blog about it at some point.

**Comment by colin-han** [comment]
@kylebebak what's your workaround?  :-)

**Comment by untoldone** [comment]
@brentvatne how should we be references shared libraries that might be used in either multiple react-native apps / a react web app where both the libraries and apps are being developed at the same time?

**Comment by arronhunt** [comment]
Has anyone had any luck with this? Neither `npm link` nor `rn-cli.config.js` have worked

**Comment by QuantumInformation** [comment]
Nope, you just have to have everything within the root of the RN project

**Comment by ericketts** [comment]
for anyone still having issues, combining the `rn-cli.config.js` hack with the `package.json` hack worked for me (allowing me to import files contained in directories adjacent to my react-native src dir).

unfortunately this is more than a bug, its a design flaw in `node-haste`...

**Comment by leturtle** [comment]
Finally, we found a solution - [Haul](https://github.com/callstack/haul).

And here is an [example project](https://github.com/pavloko/react-native-library-starter)

**Comment by MPiwowarski** [comment]
@ericketts can you upload please some sample project which shows how to solve the issue?

**Comment by ericketts** [comment]
@MPiwowarski check [here](https://github.com/ericketts/react-native-adjacent-imports) for an example project, hope this helps!

**Comment by MPiwowarski** [comment]
@ericketts thank you very much! It works properly. I've also added some sample react native component to your shared folder and imported it in App.js in rn folder and works fine :) Do you think your solution works also with Expo? Cheers

**Comment by ericketts** [comment]
@MPiwowarski I'm not sure whether expo would work with that configuration, to be honest I gave up on expo after their `exp init` tool created a broken build out of the box due to case sensitive filesystem issues.

**Comment by MPiwowarski** [comment]
@ericketts I've made a fork from your solution, you can check it [here](https://github.com/MPiwowarski/react-native-adjacent-imports) I've added expo project to the src folder and also created Sample react native component in the shared folder. Both projects expo and rn import that component and use it in App.js.

**Comment by AndrewSouthpaw** [comment]
@ericketts and @MPiwowarski, thank you so much for putting together those repos. They were instrumental in helping us set up code sharing between our native and web apps. Many, many thanks, and I hope others will find this. This is probably the most simple solution I've found to sharing code.

**Comment by ericketts** [comment]
worth noting that [this hack my break soon](https://github.com/facebook/metro/issues/139)

**Comment by AndrewSouthpaw** [comment]
Also, were you able to get this to work with eslint? The `package.json` files that simply contain the name mess up how eslint is resolving modules and detecting which dependencies are already added.

**Comment by ericketts** [comment]
I'm not sure I had that issue since I don't have any duplication of deps. We do use eslint and it all seems to work without any special configuration.

**Comment by AndrewSouthpaw** [comment]
Ah. Yeah, so switching over to using `"extends": "react-app"` in the eslint config fixed it for us. For whatever reason, our old approach of using the eslint webpack resolver didn't cut the mustard, while this new config more intelligently handles the dependencies.

**Comment by AndrewSouthpaw** [comment]
Nope, I spoke to soon. It looks like that config simply doesn't check the validity of imported modules. 😞
