### ISSUE TITLE
TextInput padding issue on iOS even though it has been set to 0

### ISSUE THREAD

**Issue by YangShaoyue** [facebook/react-native#12252]
### Description
I've set padding to 0 for TextInput, and it **seems** correct on iOS. But TextInput's placeholder position is physically higher on iOS than its on Android.

In fact, in simulator or real devices using Inspector, TextInput on iOS seems to still have some padding even though it has been set to 0. So in this way it's correct on Android.

I don't have any idea about this issue all the time. Does anyone else also have same problem or have any idea about this?

### Reproduction

It can be reproduced in [rnplay.org](https://rnplay.org/apps/W8jzUw).

For more details, there are two snapshots on iOS (simulator) and Android (real device):
**iOS**
![image](https://cloud.githubusercontent.com/assets/12428824/22682906/6d431a6e-ed50-11e6-8cc5-afcd06d5612c.png)

**Android**
![image](https://cloud.githubusercontent.com/assets/12428824/22683279/379a817a-ed52-11e6-8d4a-aa4b7c8f9672.png)

### Additional Information

* React Native version: 0.38 in my local env, 0.33 in rnplay.org
* Platform: iOS (10.2 in simulator), Android (5.1 in real device)

**Comment by shergin** [comment]
I already have a fix for it. I hope I will land it soon after proper testing.

**Comment by YangShaoyue** [comment]
@shergin look forward to your fix :)

**Comment by shergin** [comment]
It should be fixed in master already. @YangShaoyue Feel free to reopen and contact me if you still have problems with it.
