### ISSUE TITLE
Fetch is Slow 

### ISSUE THREAD

**Issue by flaviotobi** [facebook/react-native#12259]
Hi,
I know there are some issues open about the fetch being slow, but from what i see those issues are about when the app is in debugging mode(connected to the chrome), which is not the case.

The problem is, that when i make a request, it takes a lot of time to complete the request between point A and point B (see code), and this happen both in debug and release mode.
We are talking about 2 mega of information that is coming from the server. in PostMan the same request take 3 second counted with a timer and  1155ms counted by PostMan.

```
//Point A
fetch('http://api.myApi.com/mobile/', {
  method: 'GET',
  headers: {
    'Accept': 'application/json',
    'Content-Type': 'application/json',
    'Authorization': 'myToken'
  },
  body: null
}).then(res => {
  if (!res.ok) {
    throw Error(response.statusText);
  }
  //Point B
  return res.json();
})
```

Values in real devices from Point A to Point B:
iPhone 6s: between 4 and 14 seconds
iPhone6: between 25 and 40 seconds
iPhone 5s: >1m

* React Native version: V0.31.0
* Platform: iOS, (Not 100% sure about Android, i just have one android device to test, so i can't say if it is the device fault)
* Operating System: MacOS
* Network Info: Wi-fi, 200 mega optical fiber

**Comment by yury** [comment]
@flaviotobi why you close this?

Did you found solution for this?

**Comment by flaviotobi** [comment]
I understand that the problem was somewhere where the data is decoded (the response came with data very nested), so in the server side we break the information in peaces for a better decode and networking process.

**Comment by SamiChab** [comment]
I have problems with it. The `fetch()` function is way more faster on iOS than on Android. Does someone have an idea why?

**Comment by yury** [comment]
@SamiChab  do you set gzip header?

**Comment by SamiChab** [comment]
@yury no, what do you mean with it? I suppose the API has to support it?

**Comment by yury** [comment]
@SamiChab try set and see the difference 

```
headers: {'Accept-Encoding':'gzip;q=1.0, compress;q=0.5'}
```

**Comment by SamiChab** [comment]
Nope, it doesn't change a lot. But I guess the error was mine: I wasn't calling exactly the same routes on iOS and Android... Thanks for your help @yury
