### ISSUE TITLE
Activity Indicator doesn't take numeric value

### ISSUE THREAD

**Issue by web-jenezis** [facebook/react-native#12250]
### Description

Activity Indicator doesn't take numeric value. I tried to use ActivityIndicator in my app, and I found in [official documentation](https://facebook.github.io/react-native/docs/activityindicator.html), that I can use custom size for. There is also an example in [official indicator](https://facebook.github.io/react-native/docs/activityindicator.html), so I tried to use it like:

```
<ActivityIndicator
    animating = { true }
    size = { 75 }
    color = "#0c95b2"
/>
```

And as result I getting an error:
```
Invalid UIActivityIndicatorViewStyle '75'. should be one of: (
    0,
    1
)
```

### Additional Information

* React Native version: [0.41.2]
* Platform: [iOS]
* Operating System: [MacOS]

**Comment by lgan1989** [comment]
> Passing a number to the size prop is only supported on Android.

**Comment by hey99xx** [comment]
From the documentation: https://facebook.github.io/react-native/docs/activityindicator.html#size

> Size of the indicator (default is 'small'). Passing a number to the size prop is only supported on Android.

**Comment by janicduplessis** [comment]
Yea this is due to limitations with iOS UIActivityIndicator, if you want to change the size to a custom one you can try using a scale transform, `transform: [{ scale: X }]`.
