### ISSUE TITLE
[iOS][v0.40] Unable to archive - React/RCTDefines.h file not found

### ISSUE THREAD

**Issue by ggordan** [facebook/react-native#12265]
### Description

I am currently having issues **archiving** the application. The issue only occurs when attempting to archive, running in debug mode works just fine. Possibly related to #12042.

When attempting to archive the app the following occurs:

![screenshot 2017-02-07 17 26 00](https://cloud.githubusercontent.com/assets/196237/22703479/3512fa22-ed5c-11e6-92de-36c5769cf55f.png)

Was wondering whether anyone has come across this, and if there are any solutions. I've attempted various things, including solutions mentioned in #12042 however my knowledge of iOS development is minimal.

### Additional Information

* React Native version: 0.40
* Platform: iOS only
* Operating System: MacOS

**Comment by zibs** [comment]
@ggordan Following most of these steps just solved my problem with this error: http://imgur.com/a/KUOQC - in particular step 2.

Thanks to @skellock for posting.

**Comment by ggordan** [comment]
Thanks for the suggestion @zibs . Unfortunately, none of those steps seem to have worked. The `file not found` error changes from time to time. Right now it's something different, though the app builds and runs just fine. 

![screenshot 2017-02-08 10 00 41](https://cloud.githubusercontent.com/assets/196237/22732323/a82614fc-ede5-11e6-9131-4aab7eef0f9e.png)

**Comment by freakinruben** [comment]
Is `DEAD_CODE_STRIPPING` disabled for all your targets?

**Comment by skellock** [comment]
Do you have any 3rd party libs installed that haven't been upgraded?

**Comment by ggordan** [comment]
@freakinruben `DEAD_CODE_STRIPPING` is disabled for `Debug` and `Release`. 

@skellock All third party libraries have been upgraded, and the issue appears to be coming from within react-native libraries. Maybe it could be an issue with 3rd party libraries, but I imagine that in that scenario I wouldn't be able to build and run the app, which isn't the case.

**Comment by freakinruben** [comment]
The fact that it happens not all the time is even more strange.. But debugging this is a pain in the butt, I ended up throwing away the xcode project, workspace and schemes and recreating them, without much luck the first few tries.
Did you try deleting `node_modules` and downloading them again, making sure the `^` of the specified versions doesn't mess with the versions you want from npm?

**Comment by skellock** [comment]
@ggordan I've seen Xcode fail with that error before (blaming wrong lib) when I've had a 3rd party lib not upgraded AND when i've missed the new import statements up at my app level (both in the app & default test).

**Comment by freakinruben** [comment]
@ggordan Just found [this solution](https://github.com/facebook/react-native/issues/11813#issuecomment-273279257) which fixed issues for me with archiving a release with a different build-name than 'release'

**Comment by skellock** [comment]
@freakinruben thx for closing the loop!  Something about Xcode was definitely off.  I remember being able to compile in Xcode, but not the command line at one point.  If I had hair left, I'd tear it out.

**Comment by ggordan** [comment]
@freakinruben Thanks a lot for that. Managed to get it to archive

**Comment by SamSaffron** [comment]
FWIW, I have $300 on the table for anyone that can figure out how to upgrade DiscourseMobile per: 

https://discuss.reactjs.org/t/having-a-hell-of-a-time-upgrading-from-react-native-39-to-40/6331

**Comment by nihgwu** [comment]
@SamSaffron I'd like to help  if no one else do that, I'm always using the bleeding edge version of React Native

**Comment by SamSaffron** [comment]
@nihgwu  sounds like a plan, should I update that topic to say that you are taking this? any timeframe?

**Comment by nihgwu** [comment]
Ok, I'll done in an hour or two, I suppose

**Comment by SamSaffron** [comment]
@nihgwu awesome, will update the topic, if you need to fork any of the dependencies and submit fixes as well feel free to point your PR at the forks.

**Comment by flaviotobi** [comment]
Hi there is it possible to reopen this issue ? I can build in release mode with no problem but when i try to archive i always get this error:
/node_modules/react-native/Libraries/Vibration/RCTVibration.h:10:9: 'React/RCTBridgeModule.h' file not found

![screen shot 2017-03-09 at 10 38 29](https://cloud.githubusercontent.com/assets/13239857/23746659/9dd9e240-04b4-11e7-88b1-a2387816b401.png)

React-Native Version : 0.41.2
react Version: 15.4.2
Xcode Version : 8.2 
Mac OS El Capitan

**Comment by flaviotobi** [comment]
[Update] I resolve this issue  Adding React to Build Target before the app and uncheking parallelize build.

**Comment by arun542** [comment]
I have done all the settings, unchecked parallelize, Added React to build target before the app, still no luck. Fails while archiving with error 'React/RCTBundleURLProvider.h' file not found in appDelegate.m  . Works on simulator, iphone 6 device with release config but archiving fails

**Comment by yewenxiang23** [comment]
@zibs Very useful to me, thank you very much

**Comment by stantoncbradley** [comment]
@FlaviooLima can you explain how to add React to build target? thanks!

**Comment by stephan-nordnes-eriksen** [comment]
I got this error when using cocoapods 1.5 to install dependencies, but it went away when I downgraded to 1.4. 

For reference:
`$ sudo gem uninstall cocoapods`
`$ sudo gem install cocoapods -v 1.4.0`
Then re-run pod install in your `ios` folder.

**Comment by elegantcoder** [comment]
@stephan-nordnes-eriksen Very useful to me. Thank you so much.
