### ISSUE TITLE
Manually hide keyboard with javascript

### ISSUE THREAD

**Issue by TylerYang** [facebook/react-native#1227]
Hi guys,
I am a rookie in ios. 
First I want to find a js module for me to hide keyboard manually.

For example In <code>Navigator</code> when user focus on typing some text into TextInput, with clicking “Back" button, I hope the App can hide the keyboard and switch back to last page. But the fact is, it switch back to last page first, after the transition, it hide the keyboard. 

So I try to find a javascript module to hide the keyboard and failed. Then I try to implement a native module to export a method to javascript. In Stackoverflow, there is an answer: [Hide keyboard with OBJC](http://stackoverflow.com/questions/10389476/hiding-keyboard-ios). Then I try to create my own module, "CustomModule",  inside this module, is there a way to get current View or Something so that I can set view endEditing to true?

If not, is there any way to hide the keyboard manually? Thx...

**Comment by brentvatne** [comment]
Hi Tyler! This is related to #113 - you can call `blur()` on the TextInput ref that you would like to unfocus, and that will hide the keyboard. Notice in #113 that at the moment there is no way to unfocus an entire component hierarchy with a single blur call, but you can iterate over each of your TextInput components on the view when the back button is pressed and call `blur()` on each of them.

**Comment by chirag04** [comment]
@brentvatne:

I want to disable keyboard input altogether but still get change and focus events. `blur` in focus event will give a flicker of keyboard coming and going.

`controlled` will open the keyboard.

`editable` false will not open the keyboard but it will also disable focus and change events.

If there a way around? Happy to PR also if you point me to right direction.

**Comment by ide** [comment]
@chirag04 I don't believe that is possible but if you believe it is can you write a demo with UIKit and we can figure out how to support it in react?

**Comment by chirag04** [comment]
@ide 

I did an extensive search and seems like `textFieldShouldBeginEditing:` in the UITextFieldDelegate is my answer. (See: https://developer.apple.com/library/prerelease/ios/documentation/UIKit/Reference/UITextFieldDelegate_Protocol/index.html#//apple_ref/occ/intfm/UITextFieldDelegate/)


I'm trying to add this to RCTTextField but seems like it is not responding to this event when i put a debugger here. Added the delegate to RCTTextField interface and ``textFieldShouldBeginEditing` in the implementation. I also added `self.delegate = self` which initializing RCTTextField.

PS: I'm totally new to objective-c

**Comment by ide** [comment]
I believe if you return NO from textFieldShouldBeginEditing, the text field won't get focus.

**Comment by chirag04** [comment]
How do i did test this though? I cant get textFieldShouldBeginEditing to be triggered

**Comment by ide** [comment]
@chirag04 are you on IRC? let's take this discussion out of this github issue.

**Comment by chirag04** [comment]
sure

**Comment by chirag04** [comment]
For those who don't want keyboard to pop when you tap on input:
``
<TouchableWithoutFeedback onPress={this.handlePress} style={styles.labelContainer}>
           <View style={styles.labelContainer} pointerEvents={'box-only'}>
             {this.props.children}
           </View>
         </TouchableWithoutFeedback>
``

**Comment by brentvatne** [comment]
Closing because this is related to #113
