### ISSUE TITLE
[Master] - Cannot resolv ReactNativeHost & ReactApplication

### ISSUE THREAD

**Issue by Snorlock** [facebook/react-native#12286]
### Description

I'm waiting for a stable release with a PR that currently went into master: https://github.com/facebook/react-native/pull/12089
So Im currently using master.
But there is an issue with android all of the sudden, it wont resolve these two classes in a completly newly initiated project:
```
import com.facebook.react.ReactApplication;
import com.facebook.react.ReactNativeHost;
```

So Im just trying to figure out what breaking changes is coming. Because when I try to fix up on it, my app won't start with 

```
E/ReactNative: Got JS Exception: ReferenceError: Can't find variable: __fbBatchedBridge
```
So what needs to be changed?

### Reproduction

Initiate a new project, change the version to: git@github.com:facebook/react-native.git
Resync the android project

### Additional Information

* React Native version: Master
* Platform: Android
* Operating System: MacOS

**Comment by quentinfasquel** [comment]
@Snorlock I am having the same issue with these two classes which seem to have disappeared.
I was then trying the "Integrating in an existing app" tutorial for the Android version and it compiles fine but I can't get it to run because I get the same __fbBatchedBridge error.
I have read that it mainly means that your react native packager isn't reachable.

It looks like I could specify the server to use over WiFi but I can't get to debug menu since my activity won't run.

**Comment by Snorlock** [comment]
Thats strange, are you running against master aswell or?

**Comment by quentinfasquel** [comment]
Yup.

**Comment by Snorlock** [comment]
I can supplement with this, and for some reason the reactnative build on android studio is 0.20 and the classes are gone. They should be in root react folder

<img width="978" alt="screen shot 2017-02-09 at 10 04 48" src="https://cloud.githubusercontent.com/assets/1012055/22776273/509c26ac-eeaf-11e6-8552-99634314f372.png">

**Comment by Snorlock** [comment]
Somone mentioned this on another PR/issue: https://github.com/facebook/react-native/pull/12089#issuecomment-278326865

Might there be anything to it?

**Comment by quentinfasquel** [comment]
I agree there is an issue and I don't see how that is related, there are 2 Java classes not found and the react version not pointing to the proper version. There must have been some mix-up between branches or the master branch isn't up-to-date for Android, or there is an obvious mistake we are both doing and can't figure out.

I believe the CocoaPods fix will be part of the next release and Android will be working as well, however for the moment I can't run both Android and iOS with the branch facebook/react-native#master.

**Comment by yimingtang** [comment]
This [answer](https://github.com/facebook/react-native/pull/12089#issuecomment-278897946) may help.

**Comment by Snorlock** [comment]
@quentinfasquel ☝️

**Comment by Snorlock** [comment]
@yimingtang im struggeling a bit, because this is not very up to date: https://github.com/facebook/react-native/blob/master/ReactAndroid/DevExperience.md
The link is not working for example

But Iv done what the readme says on the cli library, but unfortunately im not in init face, i have to change on a app already made. https://github.com/Snorlock/react-native/tree/master/react-native-cli

So i did sinopsis and unpublished and published, and tried to point my react library to 1000.0.0, which the master branch is on. But it still doesnt work.

**Comment by Snorlock** [comment]
I think this might be some update information: https://facebook.github.io/react-native/docs/android-building-from-source.html

**Comment by chirag04** [comment]
`react-native-push-notification` lib is broken currently because of the exact same issue for those building RN from source.

**Comment by Snorlock** [comment]
Yeah, my issue was solved with that guide above, if the lib is broken, then have a look at that guide or take it up with https://github.com/zo0r/react-native-push-notification

**Comment by quentinfasquel** [comment]
@Snorlock were you able to compile ReactAndroid ?

**Comment by Snorlock** [comment]
I just followed what they said, so i believe so. But I have not tried to use the menu yet. Will check it out next week, currently on vacation.

**Comment by ochanje210** [comment]
Thank you. building from source solved the problem!
