### ISSUE TITLE
Date object  has incorrect zone offset when not debugging

### ISSUE THREAD

**Issue by JasonHenson** [facebook/react-native#12288]
### Description
I wish I could provide more information. But, the project is in debug mode for both scenarios below. I am using android emulator and all I am doing is starting and stopping debugging in the dev settings and I get 2 different results -- no code changes.

**NOT debugging console output**
Wed Feb 08 2017 19:15:01 GMT+0000 (GMT)

**DEBUGGING console output**
 Wed Feb 08 2017 14:19:32 GMT-0500 (Eastern Standard Time)
this output is correct

### Reproduction
console.log( "datetime", new Date() )

* React Native version: .41
* Platform: Android (Haven't tested with IOS)
* Operating System: Windows

**Comment by ide** [comment]
The reason you are seeing the discrepancy is because the Date implementation is different on the device (Apple's implementation) and when debugging in Chrome (Google's implementation). There's not much we can do about it without reimplementing Date.

**Comment by JasonHenson** [comment]
so, you are saying I must find another approach to get the user's time zone offset? That seems like a basic functionality for the date object.

**Comment by ide** [comment]
I'm saying use whatever technique you would use in iOS Safari, or write a native module if you prefer that option.

**Comment by JasonHenson** [comment]
I see thank you.
