### ISSUE TITLE
[Android] @ReactMethod-annotated method is not available in JavaScript

### ISSUE THREAD

**Issue by aem** [facebook/react-native#12287]
### Description
I'm attempting use Native Modules to do some processing in JavaScript that we need available in our android application. For some reason, the Native Module is not made available. 

A couple of notes about our codebase:
* We're effectively building a Single Page Application. We're using a combination of Flow and Anvil so we only have one `RootActivity` and all views are inflated into this activity. Because of this, the code around actually starting the React instance is a little different. We inject our `ReactInstanceManager` and then call `RootView::startReactApplication` with that injected instance manager
* We're all in Kotlin :) 

I did read in the resolution to #3515 that the issue might be around the package locations, so I've included the relevant package declarations

My code is as follows:

Module:
```kt
package com.[COMPANY].android.app

class ReactResultHandler(reactContext: ReactApplicationContext?) :
    ReactContextBaseJavaModule(reactContext) {

  override fun getName(): String = "ReactResultHandler"

  @ReactMethod
  fun logResults(results: ReadableMap) {
    println(results.toString())
  }
}
```

ResultProcessorPackage:
```kt
package com.[COMPANY].android.app

class ResultProcessorPackage : ReactPackage {
  override fun createNativeModules(reactContext: ReactApplicationContext?):
        MutableList<NativeModule> = arrayListOf(ReactResultHandler(reactContext))

  override fun createViewManagers(reactContext: ReactApplicationContext?):
        MutableList<ViewManager<View, ReactShadowNode>> = mutableListOf()

  override fun createJSModules(): MutableList<Class<out JavaScriptModule>> =
      mutableListOf()
}
```

Injected instance manager:
```kt
// in package com.[COMPANY].android.sdk
  @Singleton
  @Provides
  fun provideReactInstanceManager(): ReactInstanceManager {
    return ReactInstanceManager.builder()
        .setApplication(HubspotOneApp.get(context))
        .addPackage(MainReactPackage())
        .addPackage(ResultProcessorPackage())
        .setUseDeveloperSupport(BuildConfig.DEBUG)
        .setInitialLifecycleState(BEFORE_RESUME)
        .setJSMainModuleName("index.android")
        .setJSBundleFile("index.android.bundle")
        .build()
  }
```

And then finally, the code in the view where React actually gets initialized:
```kt
  override fun onAttachedToWindow() {
    super.onAttachedToWindow()
    val rootView = ReactRootView(context)
    rootView.startReactApplication(reactInstanceManager, component, props)
    addView(rootView)
    val activity = getActivity() ?: return // means return if null, getActivity() is a
                                           // custom function that just retrieves
                                           // our RootActivity
    reactInstanceManager.onHostResume(activity, activity as RootActivity)
  }
```
### Additional Information

* React Native version: 0.41.2
* Platform: Android
* Operating System: macOS 10.12.1

**Comment by aem** [comment]
I know our use case is a little odd so let me know if you need any more information

**Comment by janicduplessis** [comment]
I think you forgot to add your package to the ReactInstanceManager, you should have `.addPackage(ResultProcessorPackage())`.

**Comment by aem** [comment]
@janicduplessis sorry that was a typo in the comment. this code is sanitized to avoid giving out company information and I accidentally used two different names when i did so, I am adding the correct package to the instance manager though

**Comment by janicduplessis** [comment]
Is it only the method that is not defined in JS or the whole module?

**Comment by aem** [comment]
the whole module is unavailable, `ReactNative.NativeModules.length === 0`

**Comment by janicduplessis** [comment]
NativeModules is actually an object and not an array, It should also contain every native module thats ships with RN so I doubt it will be empty. Your module should be available on `ReactNative.NativeModules.ReactResultHandler` or whatever value you return from the `getName`.

**Comment by aem** [comment]
Makes sense it would be an object, but `console.log(ReactNative.NativeModules)` writes `[]` to the console and trying to access a module throws an exception

**Comment by janicduplessis** [comment]
Hmm, this is very strange, does using `const NativeModules = require('NativeModules');` instead of accessing it from `ReactNative` works?

**Comment by aem** [comment]
Ah sorry. I should've double checked my code. I was executing `console.log(Object.keys(NativeModules));`. Same applies with a direct require of `NativeModules` though, empty array.

**Comment by janicduplessis** [comment]
Ok that explains some of it :)

Maybe the keys in NativeModules are not enumerable, because this object is supposed to contain every native module and RN would not work at all without it. Maybe try debugging it in chrome? Just logging the whole object with console.log might also work.

**Comment by aem** [comment]
Yikes. After all of this, my computer froze so I restarted the whole machine and now everything is working. 🙄  Sorry about the noise haha

**Comment by janicduplessis** [comment]
Haha, glad it worked, maybe it was some build cache issue.
