### ISSUE TITLE
Modal ios supportedOrientations  

### ISSUE THREAD

**Issue by hariharanravi92** [facebook/react-native#12293]
Modal iOS supportedOrientations  Does Not Exit
### Description
Am using react native 0.38 Version. 
am getting error : 
Property 'supportedOrientations' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes

### Additional Information

* React Native version: [0.38]
* Platform: [iOS]
* Operating System: [MacOS]

**Comment by lacker** [comment]
I think this issue is missing sufficient information to let us reproduce. A sample app is ideal. I'm going to close this issue but please feel free to reopen if you do have a sample app here.
