### ISSUE TITLE
Form Data not sent in RN0.40.0

### ISSUE THREAD

**Issue by Suresh-R-S** [facebook/react-native#12295]
### Description

I recently upgraded my project which was in RN0.38.0 to RN 0.40.0 using react-native-git-upgrade.
The project includes ImagePickerIOS to open gallery and select an image, which is sent to the back end.
Iam sending the file as FormData to the backend.
Everything is working good in RN0.38.0, but the server returns file not found when using RN0.40.0
i.e. In the backend file received is undefined.

IMPORTANT : When I log the API call, the multipart form data is being sent.

What did i do wrong here??

### Reproduction

This is the FormData code I use : 
  var body = new FormData();
  var photo = {
  	uri : uri,
  	type: 'image/jpeg',
  	name: 'profilePic'+ new Date().getTime() +'.jpg',
  };
  body.append('file',photo);

### Additional Information

* React Native version: 0.40.0
* Platform: iOS
* Operating System: MacOS

**Comment by lacker** [comment]
Mmm, that code should work. Can you get a form working in a basic app that doesn't have other stuff? I suspect the problem is somewhere else in your stack than the code you pasted.

**Comment by digin-project** [comment]
Any feedback on this ? I think we have the same issue here and we are kind of stuck with our iOS version since we upgraded RN to 0.40.0

**Comment by bluedaniel** [comment]
Could be because of formdata boundary, I had a similar issue and this PR fixes it https://github.com/facebook/react-native/pull/11342

Not yet in release though

**Comment by pariswang** [comment]
same issue on 0.42.3.
any feedback?

**Comment by AdamTyler** [comment]
I've been troubleshooting this all day on 0.44.0 and I'm fairly certain there is an issue with the formData implementation.

**Comment by hramos** [comment]
Closing due to lack of response from the author.
