### ISSUE TITLE
react-native-git-upgrade removes settings from AndroidManifest.xml and strings.xml

### ISSUE THREAD

**Issue by rosiakr** [facebook/react-native#12290]
### Description

I first noticed the problem when upgrading to RN 0.38.
I use react-native-fbsdk in my app. According to their documentation I have to have my Facebook app application id in my AndroidManifest.xml. Not having this causes a crash when starting app on device. So in my strings.xml I have:

    <string name="facebook_app_id">12345678900000</string>

and in my AndroidManifest.xml I have:

    <application...>
        ...
        <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>
        ...
    </application>

Problem is when I run:

    sudo react-native-git-upgrade 0.38.0

it removes those and I have to add them by hand again.

### Reproduction

Add those lines (or something like that) to strings.xml and AndroidManifest.xml and run react-native-git-upgrade and see if those line are still there.

### Additional Information

* React Native version: 0.38
* Platform: Android
* Operating System: MacOS, 10.12.3
* react-native-git-upgrade version: 0.2.4

**Comment by rosiakr** [comment]
Looks like it's fixed in v0.2.5 of react-native-git-upgrade. Closing the issue.

**Comment by JoarLeth** [comment]
@rosiakr I get the same issue when upgrading react-native from 0.38.0 to 0.39.0. I'm using react-native-git-upgrade version 0.2.6.

**Comment by vdlindenmark** [comment]
I get the same issue with react-native-git-upgrade 0.2.7
