### ISSUE TITLE
Android UIExplorer examples are broken

### ISSUE THREAD

**Issue by otoinsa** [facebook/react-native#12300]
The app examples in React Native docs never work for Android platform, usually
it just loads to a blank white view:
![image](https://cloud.githubusercontent.com/assets/7381482/22779608/29962a02-eec4-11e6-9cc9-ef4dad31ae33.png)

For example I'd really like to see this Android ViewPager demo, to understand whether this is a feasible approach for the project:
https://facebook.github.io/react-native/docs/viewpagerandroid.html

**Comment by sibelius** [comment]
u can clone this repo, and run UIExplorer example

**Comment by lacker** [comment]
Hmm, that's annoying. I'm sorry! Can you get this demo working on rnplay.org? That's what I would try.

**Comment by hramos** [comment]
Thanks for reporting this, I will be taking a look at this shortly.

**Comment by hramos** [comment]
These will be removed in https://github.com/facebook/react-native/pull/13644. I'm looking into the possibility of using the new Snack Player to bring these examples back in https://github.com/facebook/react-native/pull/13646.
