### ISSUE TITLE
ScrollView & ViewPager implement next & prev page preview

### ISSUE THREAD

**Issue by grundmanise** [facebook/react-native#12304]
It would be great if we had the ability to use `iOS` `ScrollView + pagingEnabled` with nex & prev page previews, like done [here](https://github.com/kjantzer/peek-page-view-controller). I am not so strong in obj-c.. so I can't correctly implement this feature, or make a plugin from it :(. Also as I understand it is [much easier to implement for Android](http://stackoverflow.com/a/23356010/4541800)'s `ViewPager`

**Comment by lacker** [comment]
I think the best way to do that would be not by hacking on the core ScrollView, but rather by building a separate module that does this sort of scrolling. I think you could implement it just in javascript without dropping down to native code actually. (Maybe? I'm not totally sure.) So I am going to close this issue but I encourage you or other people to build this into third-party modules.

**Comment by outaTiME** [comment]
https://www.npmjs.com/package/react-native-snap-carousel
