### ISSUE TITLE
react-native run-ios

### ISSUE THREAD

**Issue by onuar** [facebook/react-native#12307]
### Description

I was trying to learn react-native from your [get started page](https://facebook.github.io/react-native/docs/getting-started.html).

I have already installed brew and node. Just I upgraded them. And I installed watchman and react-native-cli.

And then, I followed the instructions below:

```
react-native init AwesomeProject
cd AwesomeProject
react-native run-ios
```

Simulator opens. But application doesn't appear in simulator. Even application icon isn't in simulator.

There is no exception or error message on console. Last message:

```
PhaseScriptExecution Start\ Packager /dev/reactsecond/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/Script-006B79A01A781F38006873D1.sh
    cd /dev/reactsecond/node_modules/react-native/React
    /bin/sh -c /dev/reactsecond/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/Script-006B79A01A781F38006873D1.sh

Connection to localhost port 8081 [tcp/sunproxyadmin] succeeded!

```
### Reproduction

I think, this is not a comon issue.

### Additional Information

* React-native-cli: 2.0.1
* React-native: 0.41.2
* Platform: IOS
* Operating System: MacOS 10.11.06
* Npm: 4.1.2
* Node: 7.5.0

**Comment by lacker** [comment]
Well, that's odd. I would do stuff like, try it again, try restarting the packager, restarting the simulator. It's hard for us to help if it's impossible to reproduce but hopefully this small bit of advice helps you. Good luck!

**Comment by onuar** [comment]
It's done! That was really strange. Two days ago, I had no errors, no warnings. But I tried again same instroductions and then it gave an error: 

> ":CFBundleIdentifier", Does Not Exist.

[Here](https://github.com/facebook/react-native/issues/7308) is same problem and seems like default port (8081) already used. I kill process and it works now.

**Comment by WhoJave** [comment]
@onuar I have the same problem , I restart the iOS simulator then react-native run-ios  it's OK.

**Comment by onuar** [comment]
@WhoJave I think, you killed the process when you restart the simulator.

**Comment by hramos** [comment]
Duplicate of #14423
