### ISSUE TITLE
Is RK -> RCT prefix normalization still in use?

### ISSUE THREAD

**Issue by ide** [facebook/react-native#1231]
In the OSS repo I believe all the core libraries have been using the RCT prefix for a good while now. If there aren't any / too many RK prefixes internally then it could make for a good bootcamp task to remove the RK -> RCT remapping code.

**Comment by nicklockwood** [comment]
We still use RK for all our internal modules. It's useful to have a different namespace to differentiate them from the OSS versions (although we could just manually export RKText as RCTText instead of having that be automated by the infra).
