### ISSUE TITLE
Delay in opening modals on devices

### ISSUE THREAD

**Issue by ryanvanbelkum** [facebook/react-native#12310]
### Description

When opening a modal in my app, there is a 2-3 second delay before the modal will show on the screen. The setup I have is pretty straight forward, I'm setting a flag in redux that triggers the modal to be visible. The issue is sometimes apparent in the iOS emulator, but when installing the app on my iPhone 6s the delay happens every time

### Reproduction

Render a component via <Navigator>
Modal is not visible when component loads
Toggle flag to open modal (there is a few second delay before modal opens)
Toggle flag again to close modal (still a couple second delay in closing the modal)

### Solution

Improvement in modal rendering performance, or work around for a best practice. 

### Additional Information

* React Native version: 0.40.0
* Platform: iOS
* Operating System: MacOS

**Comment by lacker** [comment]
I can't reproduce this - I don't get 2-3 second delays when I open a modal. My guess is that your app is running some other computation that's delaying things. I would try profiling to see what is going on in that time. Hope this helps!

**Comment by ryanvanbelkum** [comment]
It appears this only happens when using <Navigator>.  I'll git in a little more.  Thank you.

**Comment by AnisDerbel** [comment]
+1 happens to me also

**Comment by tomycheja** [comment]
Happens to me also, any updates?

**Comment by gregblass** [comment]
If there is a lot of rendering going on, there is bound to be a delay. I'm experiencing this as well. Is there a recommended method to delay rendering of certain things until after the modal is shown?

**Comment by MALHARIHALGEKAR** [comment]
+1 even for me modal is taking 2 3 seconds to open even for close

**Comment by gusilveiramp** [comment]
+1
