### ISSUE TITLE
listview in react-native 0.41.2

### ISSUE THREAD

**Issue by WillSmithInChina** [facebook/react-native#12324]
Problem:
---------------------------------------------------
in react-native 0.40.0, listview can display all rows,
but  when I upgrade react-native to 0.41.2,
listview always can't display last two rows,
is anyone who know wht's going on ?

**Comment by Amurmurmur** [comment]
@WillSmithInChina Make sure you set the following props for the <ListView/> component like so:
```
<ListView 
pageSize={10}
initialListSize={10}
scrollRenderAheadDistance={650}
/>
```

Adjust the page size and scrollRenderAheadDistance based on how many elements you have on a screen at the beginning.

Hope this helps.

**Comment by WillSmithInChina** [comment]
@Amurmurmur  it didn't work for me, but I found the following:

when I type code like this,it works fine :

render(){
        return (
            <View>
                <ListView
                    dataSource={this.state.dataSource}
                    renderRow={this._renderRow.bind(this)}
                />
            </View>
        );
    }

but when I type code like the following, the last two rows can't display:
render(){
        return (
            <View>
                <View style={{height:40}}>
                    <Text>
                        Hello World
                    </Text>
                </View>
                <ListView
                    dataSource={this.state.dataSource}
                    renderRow={this._renderRow.bind(this)}
                />
            </View>
        );
    }

so it means:
can't add any widgets upon listview or is there any solutions to solve this ?

**Comment by Amurmurmur** [comment]
I think you should deffinately check the react-native documentation.
If you just type helloworld its not going to work, you need to have a component inside your return of the render method. 
render(){
render(
<View style={{flex:1}}>
<Text>Hello World</Text>
</View>
}

Should work. 
If you want multiply components in your render method,
you need to wrap them all with the root component:

<View>
<MyAwesomeComponent/>
<MyAnotherAwesomeComponent/>
</View>

**Comment by WillSmithInChina** [comment]
@Amurmurmur  it didn't work for me, but I found the following:

when I type code like this,it works fine :

render(){
	return (
		<View>
			<ListView
				dataSource={this.state.dataSource}
				renderRow={this._renderRow.bind(this)}
			/>
		</View>
	);
}

but when I type code like the following, the last two rows can't display:

render(){
	return (
		<View>
			<View style={{height:40}}>
				<Text>
					Hello World
				</Text>
			</View>
			<ListView
				dataSource={this.state.dataSource}
				renderRow={this._renderRow.bind(this)}
			/>
		</View>
	);
}

so it means:
can't add any widgets upon listview or is there any solutions to solve this ?

**Comment by WillSmithInChina** [comment]
@Amurmurmur  it didn't work for me, but I found the following:

when I type code like this,it works fine :
---------------------------------------------------------------------
render(){
	return (
		<View>
			<ListView
				dataSource={this.state.dataSource}
				renderRow={this._renderRow.bind(this)}
			/>
		</View>
	);
}
------------------------------------------------------------------------
but when I type code like the following, the last two rows can't display:
------------------------------------------------------------------------
render(){
	return (
		<View>
			<View style={{height:40}}>
				<Text>
					Hello World
				</Text>
			</View>
			<ListView
				dataSource={this.state.dataSource}
				renderRow={this._renderRow.bind(this)}
			/>
		</View>
	);
}
--------------------------------------------------------------------------
so it means:
can't add any widgets upon listview or is there any solutions to solve this ?

**Comment by Amurmurmur** [comment]
Ive updated the comment check it above :)

**Comment by WillSmithInChina** [comment]
@Amurmurmur i type ok, but it display wrong in github, actually, here is what i said:
/************************************************************************************
@Amurmurmur  it didn't work for me, but I found the following:

when I type code like this,it works fine :

render(){
	return (
		<View>
			<ListView
				dataSource={this.state.dataSource}
				renderRow={this._renderRow.bind(this)}
			/>
		</View>
	);
}

but when I type code like the following, the last two rows can't display:

render(){
	return (
		<View>
			<View style={{height:40}}>
				<Text>
					Hello World
				</Text>
			</View>
			<ListView
				dataSource={this.state.dataSource}
				renderRow={this._renderRow.bind(this)}
			/>
		</View>
	);
}

so it means:
can't add any widgets upon listview or is there any solutions to solve this ?

******************************************************************************/

**Comment by WillSmithInChina** [comment]
![question](https://cloud.githubusercontent.com/assets/15334969/22852516/afb686f8-f078-11e6-85c6-cf74b9f8bce7.png)

**Comment by WillSmithInChina** [comment]
@Amurmurmur , it displays like above

**Comment by ms88privat** [comment]
try using `renderHeader` of listView

**Comment by WillSmithInChina** [comment]
I'm trying ,but entire screen can scroll , that's not what I want

**Comment by WillSmithInChina** [comment]
@ms88privat  I'm trying ,but entire screen can scroll , that's not what I want

**Comment by WillSmithInChina** [comment]
@facebook-github-bot when i add components above listview that will result in missing of some rows .
so i think it should be post , finally i solve this problem by adding a spicial height footer view to show 
last several rows.

**Comment by Amurmurmur** [comment]
Just use flex: 1 for your listview:
```

<ListView 
style={{flex: 1}}
/>
```

And or set height of your listview as well like so:
```
<ListView 
style={{height: 500}}
/>
```

**Comment by WillSmithInChina** [comment]
@Amurmurmur  this way didn't work for me

**Comment by tomauty** [comment]
We've been having this issue for some time as well. Immediate regression from 0.39 (I believe) and onward.

**Comment by hramos** [comment]
Closing as ListView is deprecated in 0.43. Use FlatList.

**Comment by skovhus** [comment]
Got a similar issue after upgrading from 0.40 to 0.42, adding `style={{flex: 1}}` on the `ListView` solved it for me. Thanks @Amurmurmur
