### ISSUE TITLE
Using Modal - Illegal Argument Exception view=com.android.internal.policy.impl.phonewindow$decorview

### ISSUE THREAD

**Issue by vivekparekh8** [facebook/react-native#12320]
### Description
Modal is open -> on pressing 'ok', I want to restart the app (it gets restarted). After that, in some random cases it throws Exception 

I use [RNN](http://github.com/wix/react-native-navigation) but modal is use is react-native's

![image](https://cloud.githubusercontent.com/assets/9562838/22809543/e73dd814-eef8-11e6-9479-a0b937d187d9.png)
### Solution
Dialog needs to be dismissed after check if its open
ReactModalHostView.java I think

### Additional Information

* React Native version: 0.34
* Platform:  Android 6.0
* Operating System:  MacOS Sierra

**Comment by lacker** [comment]
Can you reproduce this without using react-native-navigation? Maybe it's better to report the error there.

**Comment by vivekparekh8** [comment]
Thank you for the response. The modal is react-native's that was the reason I created it here. 
FYI - I **removed** that modal ( now hiding and unhiding the view as a workaround) and now there's no crash.

**Comment by filiphosko** [comment]
I got the same problem but basically it happened because I forgot to dismiss (close) the modal before I restarted the app. Once I fixed it the error didn't happen again.
