### ISSUE TITLE
How to keep timeout for promise

### ISSUE THREAD

**Issue by swaroopa94** [facebook/react-native#12326]
Hi 
I am using promises for my api calling and some times when net is too slow it is taking more time to fetch the data.
So I want a timeout for my promise so that after some particular interval of time it has to show an alert like request timed out and reject the promise.
Can you tell me how to do this.
Here is my simple api calling 

```
export function Login(string){
	var promise= new Promise(function(resolve,reject){

		fetch(REQUEST_URL,{
          method:'POST',
          headers:{
            'Accept':'application/json',
            'content-Type':'application/graphql'
          },
          body:string
        }).then((response)=>response.json()).then((responseData)=>{
             resolve(responseData);
          }).catch((err)=>{
					reject(err)
					  console.log("timed out ... retrying");
				})
	})

	return promise;
}
```

Please reply as soon as possible as its urgent

**Comment by lacker** [comment]
This problem isn't specific to React Native. There are several ways you can do it, see https://github.com/matthew-andrews/isomorphic-fetch/issues/48 for some examples. Good luck!
