### ISSUE TITLE
react-native-git-upgrade doesn't work with local user config

### ISSUE THREAD

**Issue by jpaas** [facebook/react-native#12334]
I don't have a global git config for user.email because I use different emails for different repos. Instead I set it in each repo. Even though `git config -l` confirms my user.email is set in my local repo, react-native-git-upgrade refuses to run because it believes it isn't set.

In order to run react-native-git-upgrade, I have to set user.email in my global .gitconfig. So I think whatever check it is doing is probably incorrect. It shouldn't care whether its set globally, only locally.

This has been around since react-native-git-upgrade was launched on up to 0.42.rc-2

**Comment by lacker** [comment]
Would you be interested in sending a PR to fix this?

**Comment by jpaas** [comment]
So I dug into this a bit further and react-native-git-upgrade does a simple `git commit -m "snapshot"`. The issues with global vs local config have been reported by many people in regard to many other projects that use git, but in the end I'd say its a problem with git itself.
