### ISSUE TITLE
Images do not show after bundling app

### ISSUE THREAD

**Issue by laclance** [facebook/react-native#12331]
I have tried all the solutions I could find but none have worked for me. 
Images (all of them) show up when running debug app through usb cable or on emulator.

No images or fonts do not show after bundling apk (debug or release) for Android. 
No images or fonts do not show on ios after I unplug the usb cable and reopen the app.

Tried the scripts below which generates a bundle file but how do i install the bundle file to a device?

> "bundle-ios": "react-native bundle --dev false --assets-dest ./ios --entry-file index.ios.js --platform ios --bundle-output ios/main.jsbundle",
>     
> "bundle-android": "react-native bundle --assets-dest ./android/app/src/main/res/ --entry-file ./index.android.js --bundle-output ./android/app/src/main/assets/index.android.bundle --platform android -dev false"

* React Native version: 0.41.2 
* Platform: both
* Operating System: MacOS

**Comment by tsteele2013** [comment]
Are you talking about app icons when you say "Images"?

**Comment by laclance** [comment]
All images.

**Comment by laclance** [comment]
Do i need to remake apk and xproj after creating the bundles?

**Comment by laclance** [comment]
Ok sorry, seems I can just create full productions builds to get the images loaded.

**Comment by mienaikoe** [comment]
@laclance could you go into detail on how you fixed this? I'm currently encountering this issue.

**Comment by laclance** [comment]
In your project directory run these in terminal:

`react-native bundle --assets-dest ./android/app/src/main/res/ --entry-file ./index.android.js --bundle-output ./android/app/src/main/assets/index.android.bundle --platform android --dev=false`

`cd android && ./gradlew assemblerelease`

**Comment by NeosphereMPRH** [comment]
@laclance please provide solution for ios also i have tried

"react-native bundle --dev false --assets-dest ./src/images --entry-file index.ios.js --platform ios --bundle-output ios/main.jsbundle"

but still not getting images for release build

**Comment by NeosphereMPRH** [comment]
@laclance  Please provide solution for ios release build
I have tried 

react-native bundle --dev false --assets-dest ./src.images --entry-file index.ios.js --platform ios --bundle-output ios/main.jsbundle

but still not showing images in release app.

**Comment by NeosphereMPRH** [comment]
@laclance Please provide solution for ios release build
I have tried

react-native bundle --dev false --assets-dest ./src.images --entry-file index.ios.js --platform ios --bundle-output ios/main.jsbundle

but still not showing images in release app.

**Comment by NeosphereMPRH** [comment]
i have tried both but still not working for me

**Comment by laclance** [comment]
try move your images to a directory named assets in your ios folder and link them with xcode
