### ISSUE TITLE
React native base headers for ios not found

### ISSUE THREAD

**Issue by petegerhat** [facebook/react-native#12333]
### Description

During the iOS linking phase, I started seeing errors for my React Native project. 

All worked fine, I edited the Android version, React Native code didn't change, when this kind of linking errors started showing up with headers on `/node_modules/react-native/React/Base/{RCTHeaderName.h}` path not being found:

[![The error][1]][1]

    In file included from /Users/user/ReactNativeProject/node_modules/react-native-vector-icons/RNVectorIconsManager/RNVectorIconsManager.h:9:
    ../react-native/React/Base/RCTBridgeModule.h:12:9: fatal error: 'React/RCTDefines.h' file not found
    #import <React/RCTDefines.h>

### Reproduction

Here are my settings for **Header Search Paths**, matching their actual locations:

[![Header Search Paths][2]][2]

 - The location of the `RCTLog.h` is
   `PROJECTROOT/node_modules/react-native/React/Base/RCTLog.h`, but the
   import is `#import <React/RCTLog.h>` - it looks as if the header can't be imported?

 - In the **Link Binary With Libraries** I include the core React library
   (`libReact.a`).
   
 - Newly adding `React.xcodeproj` into Libraries doesn't help, Xcode's `Product > Clean` doesn't help, neither does restarting Xcode

 - `react-native run-android` works, `react-native run-ios` shows the error

 - File permissions set to the user executing `react-native run-ios`

### Additional Information

* React Native version: `0.41.2`, `0.40`, `0.39`
* Platform: iOS
* Operating System: MacOS
  
 - This could be a problem with automatic linking (`react-native link`) or package versioning (change introduced around React Native `0.40`)

  [1]: https://i.stack.imgur.com/u9mA2.png
  [2]: https://i.stack.imgur.com/nLUhp.png

**Comment by petegerhat** [comment]
The Parallelize build option was checked and React was not listed in my build targets.

**Comment by rohitgoyal** [comment]
How did you solve this?

**Comment by petegerhat** [comment]
The solution with screenshot is here http://stackoverflow.com/a/42190870/5185570

**Comment by devbriguy** [comment]
I tried the solution, no luck. I also tried changing search paths: 
- https://stackoverflow.com/questions/16919580/ios-static-library-as-a-subproject-of-a-project-that-has-custom-build-configurat/
- https://stackoverflow.com/questions/39626055/created-new-xcode-configuration-and-scheme-linker-is-suddenly-failing/

but no luck. Any suggestions?

react-native: 0.46.3
xcode: 9.0

**Comment by coolnalu** [comment]
@petegerhat that solved for me. thanks!
