### ISSUE TITLE
react-native-git-upgrade fails on git diff --binary HEAD~1 HEAD

### ISSUE THREAD

**Issue by macnube** [facebook/react-native#12336]
### Description

Attempting to upgrade react native from 0.38.0 to 0.39.2 using react-native-git-upgrade 0.39.2
### Reproduction

```
react-native-git-upgrade 0.39.2
git-upgrade info Check for updates 
git-upgrade info Read package.json files 
git-upgrade info Check declared version 
git-upgrade info Check matching versions 
git-upgrade info Check React peer dependency 
git-upgrade info Check that Git is installed 
git-upgrade info Get information from NPM registry 
git-upgrade info Upgrading to React Native 0.39.2, React ~15.4.0-rc.4 
git-upgrade info Setup temporary working directory 
git-upgrade info Configure Git environment 
git-upgrade info Init Git repository 
git-upgrade info Add all files to commit 
git-upgrade info Commit current project sources 
git-upgrade info Create a tag before updating sources 
git-upgrade info Generate old version template 
git-upgrade info Add updated files to commit 
git-upgrade info Commit old version template 
git-upgrade info Install the new version 
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
git-upgrade info Generate new version template 
git-upgrade info Add updated files to commit 
git-upgrade info Commit new version template 
git-upgrade info Generate the patch between the 2 versions 
git-upgrade ERR! An error occurred during upgrade: 
git-upgrade ERR! Error: Command 'git diff --binary HEAD~1 HEAD' exited with code null:
stderr: undefined
```

### Solution

No idea!

### Additional Information

* React Native version: 0.38.0
* Platform: N/A
* Operating System: MacOS 10.12.3

**Comment by lacker** [comment]
Does this happen on a fresh 0.38.0 install?

**Comment by ncuillery** [comment]
From https://nodejs.org/api/child_process.html#child_process_event_exit:

>If the process exited, code is the final exit code of the process, otherwise null. If the process terminated due to receipt of a signal, signal is the string name of the signal, otherwise null. One of the two will always be non-null.

It means that the `diff` command's process hasn't exited on its own, it has been terminated by the a signal.

@macnube Do you see a reason to have this process killed by a signal on your machine (Ctrl-C, watchdog or whatever)? Does it happen every time ?

It could be a good idea to improve the debug information in the [exec function](https://github.com/facebook/react-native/blob/master/react-native-git-upgrade/cliEntry.js#L58):
- `exited with code ${code}` if code is not `null`
- `exited by signal ${signal}` if signal is not `null`

**Comment by macnube** [comment]
@lacker You know, I think this may have been an install that I downgraded back to 0.38.0 at some point because I was running into some other issues. I'll see what happens if I start from a fresh install with the project.

@ncuillery Nothing comes to mind and it was happening every time, though admittedly I didn't more than 5 times. With the extra info you've provided, I'll keep an eye out to see if I can find the culprit and will report back soon.

**Comment by macnube** [comment]
I did a clean install and now I'm running on the latest.
