### ISSUE TITLE
Debugger is buggy when chrome has other extension installed

### ISSUE THREAD

**Issue by arypurnomoz** [facebook/react-native#1233]
When having other extension installed on google chrome, some of them will make react-native debugger become very buggy (for example, it keeps saying that "runtime is always not responding"). That's why when some people install chrome canary all the bugs just vanished (because when they install the canary, there is still no extension there)

I think this knowledge of debugging react-native using chrome that has no extension installed is very important and it should be written on the debugger docs, so when there is a problem with the debugger, it's reproducible and not because someone installed a silly extension. I personally have got a lot of problem with the debugger for 2 weeks, until i realize this. 

I use the switch user functionality on chrome to avoid the environment that have other extension installed

**Comment by brentvatne** [comment]
Thanks @arypurnomoz - I added a note in https://github.com/facebook/react-native/commit/39b2342ab9b394bbf7755749677facf97ab8f8a0
