### ISSUE TITLE
ListView: Text rendered in ListView is not selectable even if selectable={true}

### ISSUE THREAD

**Issue by zhangzhhz** [facebook/react-native#12342]
### Description

Text component rendered in ListView is not selectable even if selectable={true} is specified.

### Reproduction

A test code is in http://stackoverflow.com/questions/42009275/react-native-listview-rendered-text-is-not-selectable

### Solution

Need to be able to select Text in ListView.

### Additional Information

* React Native version: 0.41, 0.40, probably all versions
* Platform: Android. Don't know about IOS.
* Operating System: Windows 10 64bit

**Comment by zhangzhhz** [comment]
Just to add, Text with selectable={true} rendered in ScrollView is selectable.

**Comment by gwmccull** [comment]
Experiencing the same issue with rows and the header

Interestingly, if I update the Text component in a way that causes the live/hot reloading to refresh the screen (for example, changing the lineHeight), the text becomes selectable.

# Reproduction
Just to prove to myself that I wasn't crazy, I reproduced it on RN Playground on RN 0.33
https://rnplay.org/apps/R-pm5Q

# Additional Information
- React Native version: 0.36
- Platform: Android
- Operating System: MacOS Sierra

**Comment by cbjs** [comment]
+1

**Comment by cbjs** [comment]
still no solution

**Comment by hramos** [comment]
Closing as ListView is deprecated in 0.43. Use FlatList.

**Comment by cbjs** [comment]
@hramos still not working in FlatList.
