### ISSUE TITLE
[iOS][0.40] Error handling incoming deeplinks - invalid URL: should be a string. Was: [object Object]

### ISSUE THREAD

**Issue by ggordan** [facebook/react-native#12351]
Hello,

I've encountered an issue handling incoming deeplinks on iOS. 

I've added a `url` listener on `componentWillMount` and the handler function has one `event` argument which is an object that contains a `url` property. This works fine, and the event handler is called and starts executing. However, right afterwards an error is thrown with the message `invalid URL: should be a string. Was: [object Object]`. It appears to be coming from within the `Linking` javascript package, in the `_validateURL` function.

My handler function contains only a console.log which is executed..

<img width="563" alt="screenshot 2017-02-12 14 10 17" src="https://cloud.githubusercontent.com/assets/196237/22862787/3aa40c18-f12d-11e6-9306-c570252844d0.png">
 
### Additional Information

* React Native version: 0.40
* Platform: iOS
* Operating System: MacOS

**Comment by ggordan** [comment]
Ok, so I figured out what the issue was. Turns out that there was another event listened somewhere else in the app which was incorrectly calling `canOpenUrl` on the event object. Apologies for the false alarm!

**Comment by omeraplak** [comment]
Hello @ggordan, 
i have a same issue. 
I don't understand how you did fix? Could you more explain?

Thanks
