### ISSUE TITLE
Invalid prop style of type array supplied to Text , expected Number

### ISSUE THREAD

**Issue by jinxac** [facebook/react-native#12356]
### Description

I am trying to create a common component for all buttons in my react-native app. I have created base set of styles and pass styles are props to override default when required.

But while overriding text, it is giving me warning "Invalid prop style of type array supplied to Text , expected Number".

This however works fine in case of view. Ideally this should work right?

### Reproduction

  `<Text style={[styles.caption,this.props.style]}>{caption.toUpperCase()}</Text>`

```
const styles = StyleSheet.create({
  "caption": {
    "fontSize": 18,
    "color": "white"
  }
});

```

### Additional Information

* React Native version: 0.38.1
* Platform: ios
* Operating System: MAc

**Comment by ericvicenti** [comment]
I don't think this is a problem in new versions of RN. Can you check on RN 0.42 and re-open the issue if it is still a problem? Also, can you include the entire code snippet that will cause the error to happen?

**Comment by lihue** [comment]
I've the same problem with RN 0.42. Can you please re-open the issue?

**Comment by jinxac** [comment]
I havent tried it yet as was occupied in other projects. Will open the issue based on your feedback @lihue

**Comment by teknicalissue** [comment]
Had the same issue. Try doing this to avoid the error:

<Text style={{...styles.caption, ...this.props.style}}>{caption.toUpperCase()}</Text>

It's complaining about receiving an array.. so why not pass it a merged object of both styles?
