### ISSUE TITLE
Touches pass through overlay Views in Android, but not iOS

### ISSUE THREAD

**Issue by semekh** [facebook/react-native#12360]
### Description

There is a discrepancy between event propagation in iOS and Android.

On Android: You can have have two "overlay" views that span the whole view, containing some control elements. All control elements are tappable, as long as they don't overlap.

On iOS: The same configuration results in the top view acting like a glass that prevents any interaction with the elements on the bottom view.

In other words, transparent `View`s do propagate touch events to underlying `View`s in Android, but not in iOS.

I personally prefer Android's behavior.

### Reproduction

https://snack.expo.io/SkBZGASx-

On Android: You can tap on both the green and red box.
On iOS: You can only tap on the green box.

### Solution

Add `pointerEvents='box-none'` to overlay Views.
https://snack.expo.io/BkVomRrlb

### Additional Information

* React Native version: 0.44
* Platform: both iOS and Android
* Operating System: N/A

**Comment by SeMeKh** [comment]
Updated the reproduction link.
Also, added my workaround in "Solution" section.

**Comment by brentvatne** [comment]
It sounds like we should try to make these both behave the same, and look to the web for the correct default. PR welcome for this, it will be a breaking change for whichever platform changes.

**Comment by SeMeKh** [comment]
Any updates on this?

**Comment by tianxind** [comment]
I am having exactly the same issue. Please do take a look at the problem. Thank you very much!

**Comment by fxsalazar** [comment]
Any news on this matter?

**Comment by jahskee** [comment]
I still experience the same issue with 0.59, the touch event is still being propagated to lower layer views when in Android.

**Comment by MartinCura** [comment]
Using RN 0.56 and this also happens (only in iOS, which is irksome).

Workaround seems to work but is a pain as i have to use it on every level of nested view.

**Comment by joebernard** [comment]
Still an issue on 0.61.2. @brentvatne Could we please get this one reopened?

**Comment by joebernard** [comment]
I am finding the `pointerEvents` solution isn't working in my case. I'm placing an absolutely positioned overlay on top of a React Navigation modal. Per the [docs](https://facebook.github.io/react-native/docs/view#pointerevents) it seems this is actually the correct behavior, as it says `box-none` only has an impact on _subviews_. No mention that it would or should affect views with a lower z-index (views appearing behind an absolutely positioned overlay).

> 'box-none': The View is never the target of touch events but its subviews can be.

However adding a low `zIndex` won't help since the overlay needs to be on top.

**Comment by VrTech** [comment]
I found this issue as well, any solutions?

**Comment by flloyddsouza** [comment]
Still experencing this issue on iOS, Android works fine.
