### ISSUE TITLE
ios simulator + "debug js remotely" = modals not showing up

### ISSUE THREAD

**Issue by ivpusic** [facebook/react-native#12368]
* React Native version: 0.42.0-rc.2
* Platform: iOS Simulator
* Operating System: MacOS

I installed RN 0.42.0-rc.2 and noticed that when I turn on remote js debugging, modal windows are not opening anymore. If I turn off js remote debugging, then again everything is fine.

**Comment by hramos** [comment]
Closing as the issue is missing some information from the template. We can reopen once your issue is updated.

**Comment by sbaar** [comment]
I am experiencing this issue on devices as well. Any solution?
