### ISSUE TITLE
Code complexity for JSX code

### ISSUE THREAD

**Issue by gourav-singhal** [facebook/react-native#12361]
How can I get the code complexity for JSX code in VS code editor ? Currently I am using Code Metrics but I don't think it calculates the complexity of JSX code properly.

**Comment by rmevans9** [comment]
This question would be better suited asking in a user group type setup - you could try the facebook group for react: https://www.facebook.com/groups/react.native.community/. The issue tracker here on GitHub is used to track bugs within React Native.

**Comment by rmevans9** [comment]
@facebook-github-bot close
