### ISSUE TITLE
React Native Beginner Issue

### ISSUE THREAD

**Issue by mehdyMa** [facebook/react-native#12379]
### Description
Hi developpers,
I am new to React Native, I followed some tutorials on Udemy and now starting working on my end of studies project.
So I am facing some issues, Ididn't get how to use the code proposed on this repository in my project because I am developping it on JSX (with Atom editor), with one file for iOS and android in the same time... 
Hope you understand my issue ! 
Regards. 

### Additional Information

* React Native version: [0.41.2]
* Platform: [iOS, Android]
* Operating System: [MacOS]

**Comment by guiherzog** [comment]
Hi, I'm happy you are learning React Native. However, this isn't the channel to ask these sort of questions. This channel is focused on issues (a.k.a bugs) existent on the RN framework.

1. If you want to learn how to use RN, write in JSX and ES6/7, you should read the documentation and tutorials on the internet:
https://facebook.github.io/react-native/docs/getting-started.html

2. If you have questions or issues related to syntax, APIs, methods, etc. You should ask on StackOverflow.

3. Lastly, only if you sure the bug you're facing is RN's fault, you should create an issue here.

Hope this helps.

**Comment by rmevans9** [comment]
@facebook-github-bot close
