### ISSUE TITLE
Access a ref from inside itself?

### ISSUE THREAD

**Issue by getnashty** [facebook/react-native#12393]
Something I run into quite often, is something like the following:

```
<ScrollView ref={(sv) => this._sv = sv}>
	<View />
	<View />
	<TouchableHighlight onPress={() => this._sv.scrollTo(100)}>
		<View />
	</TouchableHighlight>
</ScrollView>
```

the onPress event never works - this._sv is always undefined... I haven't found any documentation around accessing a ref in such a manner, but I imagine there must be a common solution?

**Comment by hey99xx** [comment]
I don't see any issue with this, it's fairly similar to the examples at https://facebook.github.io/react/docs/refs-and-the-dom.html

You're not using functional component, are you? The doc says that won't work; otherwise I don't know the problem.

**Comment by SuperRainX** [comment]
I encountered a error like this.
