### ISSUE TITLE
StaticContainer file renamed, breaks native-base

### ISSUE THREAD

**Issue by LithodomosVR** [facebook/react-native#12395]
### Description

Latest master has StaticContainer.react.js instead of StaticContainer.js - just want to check whether this is deliberate/correct, so I can submit to either react-native or native-base to fix the problem. When using native-base, it attempts to include StaticContainer so breaks because it can't find it.

### Reproduction
// copied from native-base/src/basic/react-native-scrollable-tab-view/SceneComponent.js 

const StaticContainer = require('react-native/Libraries/Components/StaticContainer');

### Solution

Either rename the file in react-native or I'll submit a PR to native-base.

### Additional Information

* React Native version: current master
* Platform: both
* Operating System: OSX

**Comment by ide** [comment]
StaticContainer is part of the internal API (that is, it's not exported from `react-native`). As with any use of internal APIs, consumers of them (in this case Native Base) should either not use them or react to breaking changes.

So in the short term sending a PR to Native Base is best, longer term they can decide if they want to stop using RN's StaticContainer or continue keeping an eye on how it's named within RN.

**Comment by MagicIndustries** [comment]
Excellent, thank you.
