### ISSUE TITLE
undefined is not an object (evaluating 'RCTDataManager.queryData')

### ISSUE THREAD

**Issue by vishl** [facebook/react-native#1239]
I get `#CLOWNTOWN (error while displaying error): undefined is not an object (evaluating 'RCTDataManager.queryData')` repeatedly in my console if I get any js errors (red screen).  I can work around it by including RCTNetwork in my podfile, but it doesn't seem like this should be required to use the basic functionality.

**Comment by nicklockwood** [comment]
Sorry about that. We're tracking this issue and should have a fix available soon.

**Comment by nicklockwood** [comment]
Fix has landed internally. Should be in the next update.
