### ISSUE TITLE
Why foo() output 2 in react-native, but Chrome console output 3?

### ISSUE THREAD

**Issue by MagicalYan** [facebook/react-native#12392]
foo(x, y = function() { x = 2; }) {
    var x = 3;
    y();
    console.warn(x);
  }
foo();
Who can tell me the reasion?

**Comment by chiptus** [comment]
Seems to me like related to where the default y function is defined and what is its scope. React native compiles your code with babel so it is some issues with babel's scoping instead of react native. 

Try compiling the code with babel and running the compiled code in chrome.

**Comment by scarlac** [comment]
I think this is a question better answered on StackOverflow, @MagicalYan
