### ISSUE TITLE
Tapping <Button> in Jest test

### ISSUE THREAD

**Issue by salutis** [facebook/react-native#12409]
### Description

I decided to try React Native after spending years with Objective-C and Swift. To kick things off, I built a simple counter (increment/decrement) app. All went well and the app works.

Time to check out the testing tools! So, the app has two buttons — _Increment_ and _Decrement_ and here's how one of the buttons looks in Jest snapshot:

```xml
<View
accessibilityComponentType="button"
accessibilityLabel={undefined}
accessibilityTraits={
  Array [
    "button",
  ]
}
accessible={true}
hitSlop={undefined}
isTVSelectable={true}
onLayout={undefined}
onResponderGrant={[Function]}
onResponderMove={[Function]}
onResponderRelease={[Function]}
onResponderTerminate={[Function]}
onResponderTerminationRequest={[Function]}
onStartShouldSetResponder={[Function]}
style={
  Object {
    "opacity": 1,
  }
}
testID={undefined}
tvParallaxProperties={undefined}>
<View
  style={
    Array [
      Object {},
    ]
  }>
  <Text
    accessible={true}
    allowFontScaling={true}
    ellipsizeMode="tail"
    style={
      Array [
        Object {
          "color": "#0C42FD",
          "fontSize": 18,
          "padding": 8,
          "textAlign": "center",
        },
      ]
    }>
    Increment
  </Text>
</View>
</View>
```

I need to tap this button in my test but there's no `onPress` in the snapshot. I tried to mock the `Button` using `jest.mock` but the snapshot didn't change.

Am I missing something?

### Reproduction

* Create a component with a `Button` in it
* Try to "tap" the button in Jest test

### Additional Information

* React Native version: 0.4.1 (Stable)
* Platform: iOS
* Operating System: macOS

**Comment by rmevans9** [comment]
It sounds like you are trying to do some interaction type testing. I would imagine you are looking for something more like using enzyme to test with jest as the test running. This link is for ReactJS but it applies for React Native as well:

https://facebook.github.io/jest/docs/tutorial-react.html#dom-testing

**Comment by rmevans9** [comment]
@facebook-github-bot close

**Comment by salutis** [comment]
@rmevans9 Thanks! Enzyme (with its shallow rendering) is exactly what I need.

**Comment by salutis** [comment]
Actually, I got it working with snapshots!

1. Add `mock` for `Button` to shallow-render

    ```
    jest.mock('Button', () => 'Button');
    ```

2. Add `bind` to component's `constructor`:

    ```js
    constructor(props) {
      super(props);
      this.onIncrementTap = this.onIncrementTap.bind(this);
      this.onDecrementTap = this.onDecrementTap.bind(this);
      this.state = { count: 1 };
    }
    ```
3. Enjoy snapshots:

    ```js
    // Match snapshot
    let tree = component.toJSON();
    expect(tree).toMatchSnapshot();

    // Tap increment and match snapshot
    const incrementButton = tree.children[3]
    incrementButton.props.onPress();
    tree = component.toJSON();
    expect(tree).toMatchSnapshot();
    ```

**Comment by xareelee** [comment]
@salutis 

How do you know the arbitrary index of the `tree.children` for the button?

```js
const incrementButton = tree.children[3]  
```

Is there any other way to get the button via a constant selector?

**Comment by salutis** [comment]
@xareelee 

> How do you know [...]

No idea. I'm back to Swift for now. Waiting for Jest to mature a bit.
