### ISSUE TITLE
Can't run UIExplorer because of "ENOENT: no such file or directory, lstat <...>"

### ISSUE THREAD

**Issue by gaearon** [facebook/react-native#12406]
### Description

In master:

```
yarn
cd Examples/UIExplorer
npm start
```

Expected: RN packager starts.
Actual: RN packager fails with a cryptic error:

```

> react-native@1000.0.0 start /Users/dan/p/react-native
> /usr/bin/env bash -c './packager/packager.sh "$@" || true' --

fs.js:982
  return binding.lstat(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, lstat '/Users/dan/p/041-jsx'
    at Error (native)
    at Object.fs.lstatSync (fs.js:982:18)
    at Object.lstatSync (/Users/dan/p/react-native/node_modules/graceful-fs/polyfills.js:297:22)
    at folders.forEach.folder (/Users/dan/p/react-native/local-cli/util/findSymlinksPaths.js:18:15)
    at Array.forEach (native)
    at findSymlinksPaths (/Users/dan/p/react-native/local-cli/util/findSymlinksPaths.js:14:11)
    at addSymlinkToRoots (/Users/dan/p/react-native/local-cli/core/default.config.js:39:16)
    at Object.getProjectRoots (/Users/dan/p/react-native/local-cli/core/default.config.js:120:12)
    at Object.default (/Users/dan/p/react-native/local-cli/server/server.js:88:33)
    at options.forEach.opt (/Users/dan/p/react-native/local-cli/cliEntry.js:123:43)
```

### Solution

It seems like https://github.com/facebook/react-native/commit/bce6ece5f6927bcc06252dc2368840aa0c6fa30e (cc @harshil07) introduced some kind of symlink crawling in a predefined folder calculated like this:

```js
const NODE_MODULES = path.resolve(__dirname, '..', '..', '..');
```

This probably works inside a real app, but inside RN repo it resolves to the folder right above it. On my computer it resolves to `~/p` which is a folder containing all my projects.

As a result, RN packager starts crawling through all projects on my computer in search of symlinks, and finds some dead symlinks, crashing along the way.

Proposed solution: make `NODE_MODULES` calculation conditional depending on whether we're running inside an RN project or inside an RN repo. Just like we [do it below](https://github.com/facebook/react-native/blob/bce6ece5f6927bcc06252dc2368840aa0c6fa30e/local-cli/core/default.config.js#L110-L119).

### Additional Information

* React Native version: master at https://github.com/facebook/react-native/commit/26304dacf1dc377222c981671d669dd9a31f8569.
* Platform: Both
* Operating System: MacOS

**Comment by gaearon** [comment]
cc @Kureev per #11810

**Comment by Kureev** [comment]
Nice catch! I never tested this case before.

I'll compose a PR and add appropriate specs this weekend.

**Comment by harshil07** [comment]
@gaearon thanks for catching it. Your proposed solution seems reasonable.

**Comment by Kureev** [comment]
@facebook-github-bot close

**Comment by Kureev** [comment]
This issue has been fixed in https://github.com/facebook/react-native/commit/c97c1e551654ff9dd5de50b9eec9d21a791ffe06
