### ISSUE TITLE
React-native v0.29 app can't connect to internet on new iOS - HELP

### ISSUE THREAD

**Issue by allthetime** [facebook/react-native#12407]
I know this isn't really the place but I'm really hoping someone can help quickly because I'm in a lot of trouble right now.

I didn't realize it, but my app is now broken because it cannot connect to the internet at all (it was totally fine before i updated my phone)

 I'm on an older version of react native (v 0.29) and the new ios 10.0 has completely bricked my app. It can no longer connect to the internet and request iamges, or even map tiles from google.

I have
```
    <key>NSAllowsArbitraryLoads</key>
    <true/>
```
Does anyone know what is going on, or if I can patch it quickly before doing the work to completely upgrade everything?

**Comment by prayuditb** [comment]
I think iOS 10 has new privacy permission settings, may be this article can help you
https://blog.xamarin.com/new-ios-10-privacy-permission-settings/

**Comment by allthetime** [comment]
@hramos I'm sure this has been addressed in an update/patch at some point, because I'm assuming people are using react-native in production now without issue, but I've read through the release notes since 0.28 and i haven't found anything. Was hoping someone could point me in the right direction.
