### ISSUE TITLE
NavigatorIOS crashes when "pushing" to a new route

### ISSUE THREAD

**Issue by sharathprabhal** [facebook/react-native#1241]
Error message:

```
Invariant Violation: No navigator item should be pushed without JS knowing about it 1 0"
```

The red screen is displayed as soon as a new route is pushed.

Sample app available at https://github.com/sharathprabhal/TestNavigatorIOS

![screen shot 2015-05-11 at 8 46 58 pm](https://cloud.githubusercontent.com/assets/1396678/7578139/fc601e64-f81e-11e4-95b7-696d9db300e9.png)

**Comment by sharathprabhal** [comment]
(bump)

**Comment by sharathprabhal** [comment]
Found a workaround. Looks like using nested `NavigatorIOS` results in this. Instead, I replaced the top level nav with `Navigator`, since I did not need the iOS style back swipe for the top nav.

See diff at https://github.com/sharathprabhal/TestNavigatorIOS/pull/1/files

What is the purpose of the `Navigator` when developing an iOS app? Will it eventually replace `NavigatorIOS`? Will back swipe gesture be added to `Navigator` Any roadmap type info will be helpful here. Thanks!

**Comment by iktw** [comment]
I encountered the same problem. How do I solve this?

**Comment by sharathprabhal** [comment]
See above comment. I solved it by using `Navigator` for top level navigation

**Comment by brentvatne** [comment]
Closing as it seems to be fixed! @christopherdro #fridaytriage

**Comment by chibicode** [comment]
I'm seeing this error when the structure is like this:

```
<TabBarIOS>
  <TabBarIOS.Item>
    <NavigatorIOS
      initialRoute={{ component: Foo}} />
  </TabBarIOS.Item>
</TabBarIOS>
```

If I try to do `this.props.navigator.push(...)` in `Foo`, this error appears. How are people combining `TabBarIOS` and `NavigatorIOS`?

**Comment by clintconklin** [comment]
Ran into this today. Solution was to pass the root NavigatorIOS component to the nested component as a prop, e.g. `<MyComponent navigator={this.props.navigator} />`, and then just invoke it there via this.props.navigator.

**Comment by ignivanishant** [comment]
i am facing same problem can we solve this without shifting from NavigatorIos to Navigator

**Comment by isikfsc** [comment]
Can one use nested `Navigators` all the way down, instead of using `NavigatorIOS` in any level of that hierarchy?

**Comment by ephemer** [comment]
@brentvatne this still happens over a year later. It'd be great to be able to use a NavigatorIOS inside a NavigatorIOS. Having two different navigation stacks is a common pattern in iOS and is pretty much a must for our use case. The test repo provided by the OP is still relevant (https://github.com/sharathprabhal/TestNavigatorIOS)

I have just played around with this a bit and have a fix. Will post a pull request in a minute.
