### ISSUE TITLE
App crashes in Samsung devices

### ISSUE THREAD

**Issue by keerthanarbt** [facebook/react-native#12414]
Hi, 
Error message:   
react.uimanager.ReactShadowNode.setStyleWidth(float)' on a null object reference

com.facebook.react.uimanager.UIImplementation.updateNodeSize (UIImplementation.java:151)
com.facebook.react.uimanager.UIManagerModule.updateNodeSize (UIManagerModule.java:213)
com.facebook.react.views.modal.ReactModalHostView$DialogRootViewGroup$1.run (ReactModalHostView.java:302)
android.os.Handler.handleCallback (Handler.java:739)
android.os.Handler.dispatchMessage (Handler.java:95)
com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage (MessageQueueThreadHandler.java:31)
android.os.Looper.loop (Looper.java:158)
com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run (MessageQueueThreadImpl.java:196)
java.lang.Thread.run (Thread.java:818)

please help us with the same..with some example codes...

**Comment by keerthanarbt** [comment]
Hi @hramos ,
Please give some explanation.
It seems like some issue related to cpu architecture support.

The same code works fine with other 32 bit devices like, Nexus 5,6, Asus and Moto android devices..
The same code work perfect in Apple device.

Really stuck here please help out.
Otherwise give some reason why you closed this issue. Which will be helpful.

**Comment by hramos** [comment]
This issue was closed because it did not provide sufficient information as outlined in the template. Feel free to open a new issue, and make sure to fill out every field.
