### ISSUE TITLE
Can't change default 'LaunchImage' rn 0.41.2- ios 10.2

### ISSUE THREAD

**Issue by movie4** [facebook/react-native#12417]
* React Native version:  0.41.2
* Platform: iOS 10.2
* Operating System: MacOS

After updating from react-native 40 > 41.2  changing launchimage don't work, app use default screen image
in react-native 40^ i use this solution http://stackoverflow.com/questions/34027270/ios-launch-screen-in-react-native

![react](https://cloud.githubusercontent.com/assets/1005998/23017894/d5624cc8-f45d-11e6-9e71-2210f103a31f.png)

**Comment by Naoto-Ida** [comment]
What do you mean by it doesn't work?
Are you seeing an old one?

**Comment by movie4** [comment]
it use default RN Screen
![screen shot 2017-02-16 at 15 52 13](https://cloud.githubusercontent.com/assets/1005998/23018486/ed325bfc-f45f-11e6-895b-91e2019a5c61.png)

Update issue on iOS 9.3 it work fine

**Comment by movie4** [comment]
Error is not repeated unknown reasons, maybe this simulator and xcode issues
