### ISSUE TITLE
WebView postMessage do not work on iOS

### ISSUE THREAD

**Issue by magicismight** [facebook/react-native#12411]
`postMessage` to WebView can not work on iOS.

First, postMessage on react-native
```
this.refs.webview.postMessage("any thing");
```

Then receive the message on WebView side, the event is always {"isTrusted": false}
```
  document.addEventListener('message', function (e) {
   // e.data !== 'any thing'
   // e == {isTrusted: false}
  })

```

### Additional Information

* React Native version: 0.41.0
* Platform: iOS
* Operating System: MacOS

**Comment by rgoldiez** [comment]
@magicismight - How did you resolve this?  I'm seeing the same thing `{"isTrusted":false}`

**Comment by magicismight** [comment]
@rgoldiez Everything goes fine.
You can not print the `event` object directly.
```
  document.addEventListener('message', function (e) {
    console.log(e); // This will print {isTrusted: false}
    console.log(e.data); // This will work.
  })
```

**Comment by rgoldiez** [comment]
Thank you @magicismight !!
