### ISSUE TITLE
image curved corners get squared

### ISSUE THREAD

**Issue by quanvuong** [facebook/react-native#12413]
I have an image like so:

![fav-icon](https://cloud.githubusercontent.com/assets/6988600/23013970/6d1aa15e-f446-11e6-818a-a67203d297bd.png)

When displaying the image with:

> import favIcon from '../../assets/fav-icon.png';
> ...
> <Image
>        source={favIcon}
>        style={styles.favIcon}
> ></Image>
> ...
> favIcon: { width: 150, height, 150}

The image is rendered like so:

<img width="197" alt="screen shot 2017-02-16 at 12 51 31 pm" src="https://cloud.githubusercontent.com/assets/6988600/23014018/aa4de752-f446-11e6-86ce-891715fec786.png">

**Comment by burdiuz** [comment]
Have you tried to change resizeModes? I think resizeMode="contain" might help

**Comment by quanvuong** [comment]
yes that works. Perfect thank you!
