### ISSUE TITLE
Upgrade breaks pbxproj file

### ISSUE THREAD

**Issue by simonmitchell** [facebook/react-native#12432]
### Description

react-native upgrade breaks pbxproj file if project name has a space in it. I've just run react-native upgrade on a project, taken your changes for the project file and it has broken my pbxproj file.

### Reproduction

Set the project's name to a name with a space in it. Run react-native upgrade from 0.35.0 -> 0.40.0

### Solution

Do not strip parentheses around "path" property in pbxproj items if the project name has a space in it.

### Additional Information

* React Native version: Upgrading 0.35.0 -> 0.40.0
* Platform: iOS
* Operating System: MacOS

**Comment by simonmitchell** [comment]
Same goes for Test file, it created it like so:
```
@interface Pixie MerchantTests : XCTestCase

@end

@implementation Pixie MerchantTests
```

**Comment by ericvicenti** [comment]
Yeah, unfortunately you are responsible for merging this manually. The new tool `react-native-git-upgrade` may help make the upgrade changes more clear.
