### ISSUE TITLE
release edition can't load image when use cocoapods

### ISSUE THREAD

**Issue by HarrisLee** [facebook/react-native#12430]
when i use cocoapods ,  local image can't load.

    NSURL *jsCodeLocation;
    jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];
    rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                           moduleName:@"SmartHomeI"
                                    initialProperties:@{@"appName":@"SmartHomeI App"}
                                        launchOptions:nil];
    rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];
    self.view = rootView;

console log :
2017-02-17 15:11:02.055 [error][tid:main][RCTConvert.m:719] JSON value '{
    "__packager_asset" = 1;
    height = 23;
    scale = 3;
    uri = "/Users/LeexMuller/Library/Developer/CoreSimulator/Devices/FEF766A5-B829-465A-9C98-7CC747670B1B/data/Containers/Bundle/Application/98023DB8-C6CD-4552-A4DD-319A574E5E93/SmartHomeI.app/assets/res/images/icon_23@3x.png";
    width = 23;
}' of type NSMutableDictionary cannot be converted to an image. File not found.
2017-02-17 15:11:02.055 [error][tid:main][RCTConvert.m:748] Image source icon_23@3x.png size {23, 23} does not match loaded image size {0, 0}.

when i not use cocoapods.  it's ok.  why?    
react-native: 0.39.1
xcode: 8.2.1
cocoapods podfile:
platform :ios, '8.0'
target 'SmartHomeI' do
pod 'React', :path => './ReactComponent/node_modules/react-native', :subspecs => [
 'Core',
  'ART',
  'RCTActionSheet',
  'RCTAdSupport',
  'RCTGeolocation',
  'RCTImage',
  'RCTNetwork',
  'RCTPushNotification',
  'RCTSettings',
  'RCTText',
  'RCTVibration',
  'RCTWebSocket',
  'RCTLinkingIOS'
]
end

**Comment by ericvicenti** [comment]
You haven't provided enough info for people to reproduce this issue. cc @alloy  in case you know what is going wrong for @HarrisLee

**Comment by alloy** [comment]
No not based on this info. A reproduction would be good.
