### ISSUE TITLE
Basic View component used for the drawer navigation not working properly with VoiceOver on iOS

### ISSUE THREAD

**Issue by StefanoSarioli** [facebook/react-native#12433]
### Description

The issue is explained on [this](https://stackoverflow.com/questions/42159122/making-the-background-screen-beneath-the-open-drawer-with-react-navigation-und) question on StackOverflow.
The problem is that we need to expose the 'accessibilityViewIsModal' property for the View component so that is possible to fix [this](https://github.com/react-community/react-navigation/issues/311) issue for the accessibility of the Drawer navigation with VoiceOver on iOS.

### Reproduction

You can see the issue even with the [basic example](https://github.com/DanielMSchmidt/DrawerLayoutExample) of DrawerLayout, you need to compile and run the example on a real iOS device otherwise the problem is impossible to reproduce.
react-native-drawer-layout is the component used by the react-native library.

### Solution

Exposing the 'accessibilityViewIsModal' property for the View component, I've tried this solution on local an it works.
Once this property will be exposed I will open an issue and propose a solution to the react-native-drawer-layout component for fixing the original problem.
I've proposed this fix here because this will make the drawer navigation accessible by default and I think that this is the desired behavior for every application written with react native and it's on the spirit of the project.

### Additional Information

* React Native version: 0.41
* Platform: iOS
* Operating System: MacOS, Windows

This is my second issue on an open source project and my first one on a big open source project so if I made something wrong please let me know so that I can fix it.

**Comment by shergin** [comment]
Thank you for pointing this out! I believe, that's really important.
I will implement `accessibilityViewIsModal` property soon at least for iOS (`t16163572`). If you already have a solution for drawer (even if it relays on unavailable yet property) feel free to open PR.

**Comment by StefanoSarioli** [comment]
Thank you, I start working on the PR for the react-native-drawer-layout component.

**Comment by shergin** [comment]
`accessibilityViewIsModal` is here b00c1fa3b66a2c9070a4dfc04aeed205a10d4798!
@StefanoSarioli Could you please check that your solution in the drawer works properly?
Thank you for your effort!

**Comment by StefanoSarioli** [comment]
Hey, sorry for the super late answer but it's a busy period.
Thank you for the hard work, I've tested my solution using this property and it works properly.

Thanks a lot for this.
