### ISSUE TITLE
react-native bundle command fails with a custom project structure

### ISSUE THREAD

**Issue by MartinMoizard** [facebook/react-native#1244]
I built an iOS app using react-native but I created the project myself (not with the react-native init command).

A few things are not working properly because my project structure is not like the one generated by the react-native init command).

My project structure is the following:
- MyProjectRoot
  - MyProject.xcodeproj
  - MyProject.xcworkspace
  - AppDelegate.h
  - [...]
  - ReactComponent

I wanted to bundle the js into my app so I did the following:
```
> cd ReactComponent
> react-native bundle --minify
```

It failed with the following message:
```
Building package...
Build complete
Error saving bundle to disk
/Users/mmoizard-lanvin/Desktop/TestProject/node_modules/react-native/local-cli/bundle.js:32
          throw err;
                ^
Error: ENOENT, open 'iOS/main.jsbundle'
    at Error (native)
```

So without an 'iOS' folder, this command fails. I am not sure this is expected.

**Comment by brentvatne** [comment]
#1428 is a fix for this! Thanks for reporting!
