### ISSUE TITLE
Package Bundle is not compatible between different React-native

### ISSUE THREAD

**Issue by dolphinux** [facebook/react-native#1245]
When I deploying js bundle, I have trouble. For same javascript code, the bundle generated by react 0.3.11 have many differences,  compared with the bundle generated by react 0.4.1. the bundle generated by react 0.3.11 just running on the react 0.3.11. so we need deployment according to the react version.  Is there have way to solve this problem？

**Comment by ide** [comment]
The bundle version should equal the version of React that you are using (don't mix versions).
