### ISSUE TITLE
Navigator problem, can't pass it as prop

### ISSUE THREAD

**Issue by HERRKIN** [facebook/react-native#12456]
### I can't pass navigator as props, it throrws an error
I am trying this:
 ``` render() {
      return (
      <Navigator
          initialRoute={{name: 'Home'}}
          renderScene={(route, navigator) => {
                 if(route.name == 'Home') {
                   return <Home {...route.passProps} navigator={navigator} />
                 }
                 if(route.name == 'List') {
                   return <List title='list'/>
                 }
              }
                }
         />)
  }
```

I get the error `undefined is not a function (evaluating '(0,_color.Color)(this.toolbarDefaultBg)')`
and the first item in the error stack says the error was in statusBarColor light.js:132

### Additional Information
* react-native-cli: 2.0.1
* react-native: 0.40.0
* Platform: Android using AVD on nexus one
* Operating System:  Linux Mint

**Comment by hramos** [comment]
Navigator has been deprecated in favor of the [`react-navigation`](https://reactnavigation.org) library.
