### ISSUE TITLE
ListView wont execute onEndReached when onScroll handler is added to its ScrollView

### ISSUE THREAD

**Issue by ptfly** [facebook/react-native#12461]
Here is the use case (v 0.41.2):

```javascript
<ListView
    style={{flex:1}}
    onEndReached={() => alert('Ok, I\'m @ the bottom')}
    renderScrollComponent={(props) => {
        return <ScrollView 
            style={{flex:1}} 
            scrollEventThrottle={50} 
            onScroll={(e) => console.log('I\'m scrolling')}
            />
    }}
    />
```

I'm not adding all the other props that `ListView` and `ScrollView` have but sure thing they are not causing the issue. As soon as `onScroll` is removed, everything works as expected. This is either a bug, or a missing documentation on how to implement `onScroll` and not capturing the event.

**Update:**
After some digging in the RN source, I understand the problem. As soon as you add your own `onScroll` prop to the scroll view, the RN's one, which owns the logic around `onEndReached` is overwritten and therefore the `ListView`'s callback wont work. It could be fixed very easily by the RN team if they add `onScroll` prop to the `ListView` itself and execute that callback from their `ScrollView`'s `onScroll` implementation.

So, if you want `onEndReached` and access to the `onScroll` event at the same time, you have to implement it yourself.

**It will be very nice if the RN team expose all the callback props related to scrolling in the `ListView` and bubble them from the `ScrollView`'s.**

**Update 2:**
There is a way! Create a reference to your ListView component and then inside your `onScroll` handler just do the following:
```
// IMPORTANT: Using private methods is not usually a good practive but...
this.listView._onScroll(e); // Call RN's default prop handler
```

**Comment by janicduplessis** [comment]
If you put onScroll on the ListView directly instead of the ScrollView it should work.

**Comment by janicduplessis** [comment]
Also is there any particular reason you use renderScrollComponent here? By default ListView uses a ScrollView.

**Comment by ptfly** [comment]
I haven't tried `onScroll` on the `ListView` because it's not documented as a prop. The reason why I'm using `renderScrollComponent` is customization of the scroll view I need. The code above is just an excerpt, there are much more stuff in my actual code.

**Comment by janicduplessis** [comment]
It might not be super clear from the docs, but ListView can take the same props as ScrollView http://facebook.github.io/react-native/docs/listview.html#scrollview

**Comment by ptfly** [comment]
Thanks Janic, you are right. It's working just fine by adding these props directly to the `ListView`.
May be someone could drop one sentence in the docs just above the `ScrollView props...` link :)

**Comment by janicduplessis** [comment]
Feel free to send a PR to make it clearer :), closing this since it has been resolved.
