### ISSUE TITLE
Can not find variable：require（http://localhosy:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:30）

### ISSUE THREAD

**Issue by naWang1227** [facebook/react-native#12467]
### Description

[FILL THIS OUT: Explain what you did, what you expected to happen, and what actually happens.]

![screenshot_1970-07-18-10-33-28](https://cloud.githubusercontent.com/assets/25194203/23114951/f327beb0-f77c-11e6-8b22-3e2f651c8c38.png)

![default](https://cloud.githubusercontent.com/assets/25194203/23114980/0e719b3c-f77d-11e6-9b45-0a6ef73b34a2.png)

* React Native version: 0.41.2
* Platform: [FILL THIS OUT: iOS, Android, or both?] Android
* Operating System: [FILL THIS OUT: MacOS, Linux, or Windows?] Windows

**Comment by naWang1227** [comment]
I tried to modify the port number 8083，but it is still error “Packager can't listen on port 8083”.

**Comment by brentvatne** [comment]
Hi! Please ask on StackOverflow as this is not a bug but some problem with your setup.
