### ISSUE TITLE
RefreshControl set the titleColor causes a crash

### ISSUE THREAD

**Issue by CecilLee** [facebook/react-native#12460]
We use GitHub Issues for bugs.

### Description

set titleColor property,
but I don't set the title, or set the titleColor first, after setting the title
causes a crash

### Reproduction

[FILL THIS OUT: Try to reproduce your bug on rnplay.org and provide a link. If you can't reproduce the bug on rnplay.org, provide a sample project.]

### Solution

[FILL THIS OUT: What needs to be done to address this issue? Ideally, provide a pull request with a fix.]

### Additional Information

* React Native version: 0.39.2
* Platform: ios
* Operating System: IOS

**Comment by janicduplessis** [comment]
This should be fixed on master now https://github.com/facebook/react-native/commit/93a263d874789c23646cb1f77df0198e9e58cf33
