### ISSUE TITLE
I hope React Native can develop Android TV Applications。

### ISSUE THREAD

**Issue by luoshuai5** [facebook/react-native#12464]
I hope React Native can develop Android TV Applications。How does that work?

**Comment by christopherdro** [comment]
@facebook-github-bot stack-overflow

**Comment by luoshuai5** [comment]
The use of react native development can not use the TV remote control .

**Comment by ide** [comment]
Could you write a native module for this?

**Comment by luoshuai5** [comment]
yes,no focus on screen .

**Comment by luoshuai5** [comment]
RN component cannot get focus。

**Comment by luoshuai5** [comment]
How to get the RN component to get the focus and change the style？

**Comment by luoshuai5** [comment]
RN does not intend to support Android TV?

**Comment by brentvatne** [comment]
Hello! React Native does not support Android TV out of the box. @grabbou may be able to help you but this isn't something that is built into core.
