### ISSUE TITLE
How to require modules from string instead of static files?

### ISSUE THREAD

**Issue by matthewga0** [facebook/react-native#1246]
What I want:
```js
var n = require('module.exports = Date.now()');
```
I think the Node way should be working in React Native,
```js
var m = new module.constructor();
m._compile('module.exports = Date.now()', 'now.js');
var n = m.exports;
```
but it's not, could you tell me how?

**Comment by vkurchatkin** [comment]
What you describe is very specific to node and is private API. You can use `eval` or `new Function` instead

**Comment by matthewga0** [comment]
@vkurchatkin Thanks, but it seems that `eval` doesn't support Destructuring.

```js
eval("var React = require('react-native'); var {Text} = React; module.exports = Text;");
```

The code above will throw an error

```
Unexpected token {
```

**Comment by ide** [comment]
That's because the JS interpreter doesn't support that feature of the language yet. Write ES5 or transform your code to ES5 before evaling it.

**Comment by matthewga0** [comment]
@ide Thanks man.
