### ISSUE TITLE
[0.40] RCTRedBox.m:407:58: Conversion from value of type 'NSArray<RCTJSStackFrame *> *' to incompatible type 'NSArray<NSDictionary *> *'

### ISSUE THREAD

**Issue by dannyyaou** [facebook/react-native#12468]
Hi All!
After I update my project to 0.40
I've done dealing with lots of issue and published my app
But today when I wanna keep fixing some bug in my app
I just have to compile in Xcode first, then this compile error happening
How can i fix it? Help!

![image](https://cloud.githubusercontent.com/assets/8759099/23115168/17941626-f77e-11e6-9d22-b1b0d33419f6.png)

React Native version: 0.40
Platform: iOS
Operating System: MacOS

**Comment by brentvatne** [comment]
Hello! Post this to StackOverflow please :)

**Comment by MattyK14** [comment]
Any luck with this?

**Comment by BigPun86** [comment]
+1
