### ISSUE TITLE
Listview inside Listview

### ISSUE THREAD

**Issue by lironhel** [facebook/react-native#12476]
### Description

I have a listView when each cell has a TouchableView & listView
MyElement - When clicking on the touchView - the listView will show\hide

MyElement:
.....
constructor(props) {
        super(props);
        this.state = {
            isExpended: true,
            dataSource: (new ListView.DataSource({rowHasChanged: (r1, r2) => r1 !== r2})).cloneWithRows(this.props.list),

        };
    }

render() {
        var innerListView= this.state.isExpended ?
            <ListView
                style={{flex:1, flexDirection: 'column',}}
                dataSource=
                    {this.state.dataSource} renderRow={this.renderRow.bind(this)}
            /> : null;

        return (
            <TouchableWithoutFeedback
                onPress={() => {
                        this.setState ( {
                            isExpended : !this.state.isExpended,
                        });
                    }}

                style={{
                    flex : 1,
                     flexDirection: 'column'   }}>
                <View>
                    <TitleListItem
                        isExpended={this.state.isExpended}/>

                    {innerListView}
                </View>
            </TouchableWithoutFeedback >
        );
    }

For some reason - after updating to V0.40.0 - the state change will affect the rendering of other list elements,
If I have two listViews and I expand the second (isExp state #1false#2#true) works, 

but when I click on the first element - it will expand and the height calculation of the second element will be correct - without showing the elements in #2

when I click the #2 to set isExp to false - it will affect the #1 too - making both to be null.

I think it worked before (I am not sure about the version it worked) 
I hope I am clear enough, 
Thanks

### Additional Information

* React Native version: 0.40.0
* Platform: Android
* Operating System: Windows

**Comment by hramos** [comment]
Closing as ListView is deprecated in 0.43. Use FlatList.

**Comment by MatthewAwesome** [comment]
@hramos if this is indeed the case, the tutorial should be updated, as it mentions only ListView and nothing about FlatLast. Thanks in advance.
