### ISSUE TITLE
Spring animation with delay

### ISSUE THREAD

**Issue by henrikra** [facebook/react-native#12474]
### Description

When using spring animation with `delay` the delay is not registered at all. Here is how to use delay

```javascript
Animated.spring(
  this.state.rotaneAnimation, 
  {toValue: 360, delay: 500},
).start();
```

But for example with `timing` is works:
```javascript
Animated.timing(
  this.state.rotaneAnimation, 
  {toValue: 360, delay: 500},
).start();
```

### Solution

I think the solution lies here: https://github.com/facebook/react-native/blob/master/Libraries/Animated/src/AnimatedImplementation.js#L447 because it looks like the spring does not take `delay` as parameter

### Additional Information

* React Native version: 0.40.0
* Platform: both
* Operating System: MacOS

**Comment by brentvatne** [comment]
Indeed spring does not support this, you can use `Animated.delay` if you like, it is more composable than an option.
