### ISSUE TITLE
Trying to create apk build fails in ./gradlew assembleRelease.

### ISSUE THREAD

**Issue by santhosh77h** [facebook/react-native#12471]
### ./gradlew assembleRelease

`react-native start` is already running.

I did curl `curl "http://localhost:8081/index.android.bundle?platform=android" -o "android/app/src/main/assets/index.android.bundle"` and then `./gradlew assembleRelease` but my build failed with this exception everytime with this error 
```
 'assets\new_images\slide4.png' could not be found, because 'assets\new_images' is not a subdirectory of any of the roots  ('F:\daddyswallet1\daddyswalletapp')

:app:bundleReleaseJsAndAssets FAILED
```

### Reproduction

I have put all the images in root folder of assets
Project
├── android
├── assets
│   ├── images
│   │   ├── img1
│   ├── new_images
│   │   ├── slide4.png
│   │   ├── img2

### Additional Information

* react-native-cli: 1.0.0
* react-native: 0.33.1
* Platform: Android
* Operating System: Windows

**Comment by brentvatne** [comment]
Hello! Please update your React Native version, it is now nearly 10 releases behind, if this was an issue it is likely resolved now. Otherwise you can try StackOverflow :)
