### ISSUE TITLE
`RCT_EXPORT_METHOD` does not support multiple arities

### ISSUE THREAD

**Issue by pvinis** [facebook/react-native#12498]
`RCT_EXPORT_METHOD` does not support multiple arities. for example 
```
RCT_EXPORT_METHOD(track:(NSString *)event)
{
  [Reporter track:event];
}

RCT_EXPORT_METHOD(track:(NSString *)event 
                    properties:(NSDictionary *)properties)
{
  [Reporter track:event properties:properties];
}
```
now if i call `Reporter.track('bla', { a: 1 })`, thats fine. but `Reporter.track('bla') complains that the method expects 2 args and i gave only 1.

do i need to make an example app for that? its pretty easy to try out.

i guess the second call to `RCT_EXPORT_METHOD` replaces the first one or something?
is this on purpose, or just a bug?

* React Native version: 0.41.0
* Platform: iOS
* Operating System: macOS

**Comment by brentvatne** [comment]
You can wrap the exposed native API in a JavaScript API that accepts multiple arities and provides default values when others aren't provided.

```
RCT_EXPORT_METHOD(track:(NSString *)event 
                    properties:(NSDictionary *)properties)
{
  // if properties is given {
    [Reporter track:event properties:properties];
  } // else if it is not given {
    [Reporter track:event];
  }
}
```

in js:

```
export default function report(event, properties={}) {
  MyModule.report(event, properties);
}
```
