### ISSUE TITLE
Retrieve React Native version programmatically

### ISSUE THREAD

**Issue by peacechen** [facebook/react-native#12503]
### Description

I would like to retrieve the version of React Native through Javascript to include in diagnostic reports.  I haven't found a way to do this aside from a pre-build script that parses the package.json, podspec or gradle.properties. 

### Reproduction

N/A

### Solution

```
import { Version } from 'react-native';

console.log("React Native version " + Version.ReactNative);
```

### Additional Information

* React Native version: 0.34-0.42
* Platform: iOS and Android
* Operating System: OSX

**Comment by ide** [comment]
Could you write require('react-native/package.json').version?

**Comment by peacechen** [comment]
@ide   What a great idea. Thank you. That's so much simpler and doesn't call for any changes in React's code.

**Comment by charpeni** [comment]
@facebook-github-bot answered
