### ISSUE TITLE
Cannot create WebView that allows setting URL programmatically after initial loading

### ISSUE THREAD

**Issue by lyahdav** [facebook/react-native#12507]
### Description

I am unable to create a WebView that allows setting the URL programmatically after the initial load.

### Reproduction

1. Go to the [WebView example in the docs](http://facebook.github.io/react-native/docs/webview.html#examples).
1. Click the Run this example link on the right side and start the simulator.
1. In the demo app, change address bar to `twitter.com` and hit the go button.
1. Notice that Twitter.com never loads and the address bar cycles between `http://twitter.com/` and `https://twitter.com` infinitely. This is because the WebView `source` property is bound to `{uri: this.state.url}` and the go button sets the `url` state to the inputted URL. In `onNavigationStateChange` it sets the `url` state to `navState.url`. On redirects it's getting into an infinite loop.

### Solution

I am trying to use a similar pattern in an app of mine where I added a home button on a screen that should navigate the WebView to a specific URL but I get this same kind of infinite loop in my app.

### Additional Information

* React Native version: Exponent SDK 12.0.0 (not sure how to find React Native version)
* Platform: iOS
* Operating System: MacOS

**Comment by brentvatne** [comment]
Hello! This appears to just be the behaviour of UIWebView, if you google it you'll find that others have similar problems. You can resolve this easily by only changing the URL when loading is done, if you want the TextInput to reflect the url immediately then have displayedURL and loadedURL state vars.

This fixes it:

```
  onNavigationStateChange = navState => {
    let extraOptions = {};
    if (!navState.loading) {
      extraOptions.url = navState.url;
    }

    this.setState({
      backButtonEnabled: navState.canGoBack,
      forwardButtonEnabled: navState.canGoForward,
      status: navState.title,
      loading: navState.loading,
      scalesPageToFit: true,
      ...extraOptions
    });
  };
```
