### ISSUE TITLE
Duplicate JSX attributes cause app to hang

### ISSUE THREAD

**Issue by myuller** [facebook/react-native#1250]
Hi,
If I put this render code into generated react-native index.ios.js, the app will hang after splash screen:

       <View style={styles.container} style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit index.ios.js
        </Text>
        <Text style={styles.instructions}>
          Press Cmd+R to reload,{'\n'}
          Cmd+D or shake for dev menu
        </Text>
      </View>

notice the duplicated `style` attribute on the View. Without it everything works fine.

**Comment by christopherdro** [comment]
In order to pass in multiple attributes you need to send it through as an array.
```<View style={[styles.style1, styles.style2]}>```

**Comment by brentvatne** [comment]
Looks like this gives a red screen with a descriptive error message as it should. @christopherdro's suggestion is totally correct :smile:

**Comment by jaygarcia** [comment]
Duplicate attributes in *ML languages is technically invalid. =)
