### ISSUE TITLE
ListView data shows blank when running in background mode or closed for long time

### ISSUE THREAD

**Issue by krishbhattacharyya** [facebook/react-native#12510]
### Description
I have added a ListView within a View component. It is render properly. But suppose I am out of my app ( not closed staying in stack, running on the background ) or closed the app in login state ( Login state I ahve saved in AsyncStorage ), after long time I reopen my app, the ListView data shows empty. ListView data fetch only in componentDidMount, I didi not use any activity in background. ( In the android it is working fine )

### Additional Information

* React Native version: [0.37.0]
* Platform: [IOS]

**Comment by brentvatne** [comment]
When you scroll after foregrounding the app again do the contents appear? If so, then turning `removeClippedSubviews` off will resolve the problem.

**Comment by krishbhattacharyya** [comment]
@brentvatne  thanks, I will check this. Please do not close the ticket or say me to move this stackoverflow. I think this is react native issue.

One more thing noticeable(missed the last application test)!!!! Which I have not mentioned in my issue? Navigation changes is working fine but no fetch data is loaded ( application seems freeze ) ? Or sometime application is crashed when click any button. 

It is really big problem, I do not know what is going on. But it is okay in android. The condition is only happening  after long time ( like two or three days ) close the application or running in background. Specially when logged in state ( login info stored in AsyncStorage ). 

May be the problem with memory.

**Comment by brentvatne** [comment]
I am closing this issue because it is a dup of #8607
