### ISSUE TITLE
Flex Dimensions example in documentation is broken

### ISSUE THREAD

**Issue by pavankat** [facebook/react-native#12518]
### Description

for this part of the documentation:
https://github.com/facebook/react-native/blob/master/docs/HeightAndWidth.md

The flex dimensions example is broken.

flex : 1 doesn't show anything. 

height : 300 does

### Solution

the documentation needs to get fixed

### Additional Information

* React Native version: 
react-native-cli: 1.0.0
react-native: 0.41.2
* Platform: both
* Operating System: MacOS

**Comment by brentvatne** [comment]
cc @dabbott

**Comment by dabbott** [comment]
@pavankat I can't reproduce this, `flex: 1` shows up for me. Are we doing anything differently?

![screen shot 2017-02-24 at 10 28 27 am](https://cloud.githubusercontent.com/assets/1198882/23315693/28c443c0-fa7c-11e6-8011-a6dccbff3e81.png)

**Comment by brentvatne** [comment]
Thanks for investigating @dabbott!
