### ISSUE TITLE
Can’t access `__dirname`

### ISSUE THREAD

**Issue by kirkstrobeck** [facebook/react-native#12516]
With webpack I can use `__dirname`, but  [Packager](https://github.com/facebook/react-native/tree/master/packager) doesn’t support it.

- Just want it so I can use the parent directory name as a string in the code. 
- It won’t be used in that actual app, it’s just used for the compiling phase.

**Comment by brentvatne** [comment]
you can add a babel plugin to do this if you want! just at the beginning of each file define a var called `__dirname` and set it to the directory
