### ISSUE TITLE
Android Picker onValueChange is Firing on Initialization

### ISSUE THREAD

**Issue by WaffleStudios** [facebook/react-native#12520]
### Description

I have a Picker whose list loads dynamically, based on what has previously been selected (mutually exclusive options). When I select a value from the list, I would like to move it to a different list and remove it from the Picker options. The issue is that, it selects the topmost value and fires the `onValueChange` for that value every time the list is re-rendered due to the `setState`. This causes every value to fire an event and empties the list.

### Reproduction

[RN Play Sample Here](https://rnplay.org/apps/4UMQCw)

### Solution

`onValueChange` should not be fired when the Picker is initialized on Android.  It should only trigger when an option is manually selected by the user.

### Additional Information

* React Native version: 0.41.2
* Platform: Android
* Operating System: Mac OS Sierra 10.12.3

**Comment by wrell** [comment]
:+1:

Does anyone have a workaround for this? Being able to change state on `onValueChange` is pretty crucial.

**Comment by WaffleStudios** [comment]
@wrell Currently my workaround is that I moved the onValueChange code to a button that fires it onPress and save the selected value to state.  This prevents any bunk submissions.  Obviously, this may not be a workable solution for everyone, but it's better than nothing.

**Comment by DamianPereira** [comment]
I have the same issue, the workaround mentioned in #9220 does not work for me. 

Did anyone find any other solution to prevent onValueChange from firing?

**Comment by goblinbr** [comment]
@DamianPereira try this: https://github.com/facebook/react-native/issues/13351#issuecomment-317817198
