### ISSUE TITLE
okhttp version conflict  on  RN

### ISSUE THREAD

**Issue by devinhu** [facebook/react-native#12536]
I  have an project with the okhttp and RN， 
the okhttp 3.6.0   okio 1.11.0 in my project. 
the okhttp 3.4.1    okhttp-urlconnectio 3.4.1   onhttp-ws 3.4.1 in RN.

the version of okhttp 3.6.0 already contain onhttp-ws。 please help me, thanks.

**Comment by hey99xx** [comment]
It's your problem really, this is not an issue with RN, so you would probably get more help on Stackoverflow. I'm sure gradle has option to resolve compatibility, you can likely force RN to use 3.6.0 in your build files.

**Comment by desmond1121** [comment]
You can build your android sdk from source (see [Building React Native from source](http://facebook.github.io/react-native/docs/android-building-from-source.html)), it would be a gradle module of your project then change okhttp version by yourself.
