### ISSUE TITLE
Shrink via scaleXY Animation

### ISSUE THREAD

**Issue by martco** [facebook/react-native#1253]
Currently I am able to animate `<View />` growth using `AnimationExperimental.startAnimation`:

![shrink](https://cloud.githubusercontent.com/assets/420959/7599868/a01a3fd0-f8ba-11e4-93e3-654154c0ec5a.gif)

I would like to shrink instead of grow, however: 

![ccb64735-b914-48bb-bee5-94c91d9415f2](https://cloud.githubusercontent.com/assets/420959/7599879/b4e3d08e-f8ba-11e4-9824-0fb29bc1d826.png)

Here's the object I pass to `startAnimation`: 

<code>
  {
    node: n,
    duration: 7000,
    easing: 'easeInOutCubic',
    property: 'scaleXY',
    toValue: [2,2]
  };
</code>

I've tried positive and negative number for the `toValue`. 

How do I shrink?:

I've dug through the issues and have seen a few [related things](https://github.com/facebook/react-native/issues/46). Does the `<View />` not have layout, and that's why I can't shrink?

Thanks!

**Comment by spicyj** [comment]
Have you tried a number between 0 and 1?

**Comment by martco** [comment]
@spicyj yes but it still grows, not shrinks

**Comment by brentvatne** [comment]
@martco - this is a bug with `AnimationExperimental` that has come up on numerous occasions - the `AnimationExperimental` library is on its way out and I'd recommend using a plain react library such as react-tween-state, see #722
