### ISSUE TITLE
Local images takes time to load, and load separately

### ISSUE THREAD

**Issue by moerabaya** [facebook/react-native#12540]
### Description

Local images takes forever to load, and they loads separately. I believe that caused when loading external image from the web.

### Additional Information

* React Native version: RN 0.40
* Platform: iOS 10.2.1
* Operating System: MacOS

**Comment by ashik94vc** [comment]
You tried it in production or just the debug version. Its because, it will be loaded from your react-native packager. It won't be packaged along with your app. Try to create a bundled build and test image loading in it.

**Comment by moerabaya** [comment]
@ashik94vc yes, exactly that was the issue!! thanks :)

**Comment by frndev** [comment]
@ashik94vc Brilliant! I edited the scheme on iOS project to release instead of debug and it worked perfectly. Thank you
