### ISSUE TITLE
Dev build expires on iPhone?

### ISSUE THREAD

**Issue by ilkarman** [facebook/react-native#12541]
I deployed a 'release' build of my app to my iPhone, which worked for around a week. I don't have an Apple developer account. It seems the app stops working after around a week? I tried this again on another iPhone and the same thing happened. I'm not sure if this is a react-native thing or an XCode thing?

**Comment by brentvatne** [comment]
Please google these types of questions first, it was easy to find an answer:

http://stackoverflow.com/a/38308037/659988
http://stackoverflow.com/questions/4740382/will-an-app-continue-to-work-if-my-provisioning-profile-expires
