### ISSUE TITLE
Creating new project fails

### ISSUE THREAD

**Issue by jeroenbourgois** [facebook/react-native#12542]
### Description

I did a fresh install following the instructions on https://facebook.github.io/react-native/docs/getting-started.html#content, but it fails at the first step:

`react-native init AwesomeProject`

This results in this output (the packages are installed properly with yarn):

```
├─ yargs-parser@4.2.1
└─ yargs@6.6.0
✨  Done in 5.86s.
/private/tmp/test/AwesomeProject/node_modules/babel-core/lib/transformation/file/index.js:600
      throw err;
      ^

SyntaxError: /private/tmp/test/AwesomeProject/node_modules/react-native/packager/react-packager/src/node-haste/index.js: You can only use Class Properties when the 'classProperties' plugin is enabled. (389:2)
  387 |   }
  388 |
> 389 |   static Cache;
      |   ^
  390 |   static Module;
  391 |   static Polyfill;
  392 |   static getAssetDataFromName;
    at Parser.pp$5.raise (/private/tmp/test/AwesomeProject/node_modules/babylon/lib/index.js:4380:13)
    at Parser.pp$1.parseClassProperty (/private/tmp/test/AwesomeProject/node_modules/babylon/lib/index.js:2508:10)
    at Parser.parseClassProperty (/private/tmp/test/AwesomeProject/node_modules/babylon/lib/index.js:5947:20)
    at Parser.pp$1.parseClassBody (/private/tmp/test/AwesomeProject/node_modules/babylon/lib/index.js:2424:34)
    at Parser.pp$1.parseClass (/private/tmp/test/AwesomeProject/node_modules/babylon/lib/index.js:2361:8)
    at Parser.pp$1.parseStatement (/private/tmp/test/AwesomeProject/node_modules/babylon/lib/index.js:1798:19)
    at Parser.parseStatement (/private/tmp/test/AwesomeProject/node_modules/babylon/lib/index.js:5719:22)
    at Parser.pp$1.parseBlockBody (/private/tmp/test/AwesomeProject/node_modules/babylon/lib/index.js:2223:21)
    at Parser.pp$1.parseTopLevel (/private/tmp/test/AwesomeProject/node_modules/babylon/lib/index.js:1733:8)
    at Parser.parse (/private/tmp/test/AwesomeProject/node_modules/babylon/lib/index.js:1628:17)
```

### Additional Information
I first thought it was a node problem so I reverted from 7.6.0 to the 6.10.0 LTS version, same result.

* React Native version: ->
```
react-native-cli: 2.0.1
react-native: n/a - not inside a React Native project directory
```

* Platform: both
* Operating System: MacOS

**Comment by kafkaca** [comment]
+1

**Comment by odemolliens** [comment]
+1

**Comment by kweaver00** [comment]
+1

**Comment by Kraignos** [comment]
+1

**Comment by elizamaria** [comment]
+1

**Comment by jmz331** [comment]
+1 same problem.

**Comment by UtkarshPramodGupta** [comment]
+1

**Comment by kumarpatel** [comment]
+1

**Comment by hacoval-fuke** [comment]
+1

**Comment by aliuspetraska** [comment]
+1

**Comment by BuiTruongXuan** [comment]
+1

**Comment by simonjk** [comment]
+1

**Comment by zphhhhh** [comment]
+1

**Comment by marcosiino** [comment]
Lol, i'm just trying ReactNative now, and saw this strange error...so i've found this. Perfect timing! :) Btw, since i'm a beginner in ReactNative (just trying it now), how can i install the previous version of the cli which is not affect by this bug, using brew on mac, so that in the meanwhile i can try it ? (i've already installed the last cli, so i don't know if i first need to remove it). Someone can help me? Thanks!

**Comment by nikolay-radkov** [comment]
+1

**Comment by idancali** [comment]
+5 (the entire team is frustrated)

**Comment by bluedusk** [comment]
+1

**Comment by agenciafera** [comment]
+1

**Comment by KaanErkol** [comment]
+1

**Comment by aliuspetraska** [comment]
@grabbou please take a look

**Comment by TheBlackHacker** [comment]
+1

**Comment by simonjk** [comment]
This change was don on the file in question 3h ago so it should be the primary suspect:
https://github.com/facebook/react-native/commit/4a4dddbfdcebc71f0828654154b6d4a27b448df0

**Comment by gmh04** [comment]
+1

**Comment by gamer496** [comment]
+1

**Comment by vaxo-m** [comment]
+1

**Comment by idancali** [comment]
Found the bug people. Babylon (6.16.0 published an hour ago) messed something up. If you use 6.15.0 it works.

**Comment by grabbou** [comment]
Thanks, will let the team know we got a problem.

**Comment by kumarpatel** [comment]
```npm uninstall babylon && npm install babylon@6.15.0```

**Comment by craigedmunds** [comment]
+1

**Comment by carlosroberto555** [comment]
+1

**Comment by MoOx** [comment]
Stop +1 noise. Thanks.

**Comment by shmakovdima** [comment]
+1

**Comment by chapati23** [comment]
+1 is the broken window effect of the developer world

**Comment by hzoo** [comment]
Looking into it now.

**Comment by sunruh** [comment]
@hzoo I suspect it to come from PR https://github.com/babel/babylon/pull/300

The changelog states

> Don't parse class properties without initializers when classProperties is disabled and Flow is enabled (#300) (Andrew Levine)
> 
> Ensure that you enable the classProperties plugin in order to enable correct parsing of class properties. Prior to this version it was possible to parse them by enabling the flow plugin but this was not intended the behaviour.
> 
> If you enable the flow plugin you can only define the type of the class properties, but not initialize them.

**Comment by hzoo** [comment]
Awesome, need to figure out what react-native is doing

**Comment by georginio** [comment]
+1

**Comment by voidale** [comment]
@kumarpatel doesn't seems to work to me any other ideas for temp fix?

**Comment by diegorodriguesvieira** [comment]
+1

**Comment by MintyOwl** [comment]
Operating System: Windows 10 64bit

**Comment by chapati23** [comment]
temp fix possibly forking react-native and restraining babylon version to 6.15 in the 2 package.json's?
• https://github.com/facebook/react-native/blob/564126f2bf23f87bc80d9d02c7a9ed227dd1bb4e/package.json#L142
• https://github.com/facebook/react-native/blob/13edf6da2b8090c1b0bfa5fde4354fbfb24e6b4e/packager/package.json#L18

**Comment by simonjk** [comment]
was there any change. it is working now for me including babylon 6.16

**Comment by chapati23** [comment]
interesting, what os / node / react-native-cli versions @simonjk ?

**Comment by hzoo** [comment]
## Yes the workaround should be to pin to babylon@6.15.0

Ok I have to work, so going to revert the 2 PRs and do a patch.

**Comment by dfischer** [comment]
(sorry for OT) Well, if there's one thing to say it's interesting to see how many people are trying to get up and running with a tutorial. I just ran into this too. 👍  thanks for the quick response @hzoo

**Comment by rizwanahmed19** [comment]
+1

**Comment by hzoo** [comment]
Yeah @dfischer, really sorry this is the experience people get when starting out with react-native/javascript/open source. We make mistakes

**Comment by dfischer** [comment]
It's all good, I think it's cool how many people are reporting in. Good work @hzoo you rock!

**Comment by robdonn** [comment]
@hzoo Actually I think this is a really good experience for new people because it shows how quickly a problem can get resolved in a well supported project.

**Comment by hzoo** [comment]
# Releasing v6.16.1 until we actually can get the time to figure this out.

Ok made a new patch release that just reverts the PRs that caused the issues.

If you need to you'll need to `rm -rf node_modules` and `npm install` again. You don't need to add babylon to dependencies if you did before if this fixes it.

**Comment by futurechallenger** [comment]
cool! @hzoo

**Comment by zyhou** [comment]
Good for me, it's work :)

Thanks @hzoo

**Comment by IAmFledge** [comment]
🎉 - Back in business!

```
Using yarn v0.20.3
Installing react-native...
...
...
✨  Done in 9.76s.
To run your app on iOS:
...
```

**Comment by kafkaca** [comment]
Thanks @hzoo

**Comment by sunruh** [comment]
@simonjk @chapati23 If the haste map has been generated once with a babylon version that's working and no change requires regeneration, it keeps workng even if you upgrade babylon again.

**Comment by simonjk** [comment]
@chapati23 MacOS 10.11.6

react-native --version
react-native-cli: 2.0.1
react-native: 0.41.2

node --version
v7.4.0

had the problem first too but after a rm of the folder and a re-init it the problem was suddenly gone

**Comment by jeroenbourgois** [comment]
@hzoo @grabbou and everyone involved: thanks! Amazing how fast this was resolved!
