### ISSUE TITLE
ListView renderSeparator rendering a separator under the last element in list

### ISSUE THREAD

**Issue by RyanMitchellWilson** [facebook/react-native#12555]
Whenever I use the renderSeparator prop on a ListView it keeps rendering a separator under my final element which it should not be doing.

* React Native version: 0.41.0
* Platform: Both

**Comment by ide** [comment]
It might be doing this because that's what iOS does. You could maybe make your renderSeparator function conditionally return null if it's for the last cell.

**Comment by RyanMitchellWilson** [comment]
Ya I could do something like that but I feel as though in pretty much any case that you would want to separate something you would only want it between your items and wouldn't want anything trailing. When you see the word separate you'd assume it is splitting two things up, so having this named 'renderSeparator' is misleading if it just puts something under every single list item. In the case that you would want something under every item you'd just make it part of the component being rendered, instead of splitting it out making it more complicated.

**Comment by ide** [comment]
The reason not to make it part of the component is that when a cell is pressed, you usually want to change the styling of both adjacent separators, not just the one below, hence why the renderSeparator API was introduced.

**Comment by RyanMitchellWilson** [comment]
Yes that is all good, but that doesn't change the fact that you don't want a trailing element. Just for an example if you look at the right side of this page you see a separated list but there is no trailing line under the participants. In almost all cases that someone would want to separate a list they probably want it looking something like that.

**Comment by ide** [comment]
That's true on webpages, looking at mobile though it seems to be the common case ex: the messages app.

**Comment by RyanMitchellWilson** [comment]
That looks more like a bottom border to me, but if your feeling strongly enough the other way, I will concede

**Comment by hramos** [comment]
Closing as ListView is deprecated in 0.43. Use FlatList.
