### ISSUE TITLE
Build fails when using new scheme in Xcode

### ISSUE THREAD

**Issue by retailos** [facebook/react-native#12561]
### Description
When creating a new scheme in xcode, the react-native project fails to build with the error "React/RCTBundleURLProvider.h file not found"

### Reproduction
I created a new react-native project with react-native init. This is installing version 41.2.
I open the project in xcode and under info > configurations created a new build configuration. (duplicating the release config).
I create a new scheme and use the new build configuration for run, test, profile, analyze and archive.

In build settings under "Product Bundle Identifier" I set a new bundle id for the new config.
In the info tab I set the bundle identifier to $(PRODUCT_BUNDLE_IDENTIFIER) so the identifier will change when I switch configs.

Building the app with the new scheme fails. But if I set the new scheme's config back to the "release" config, the app builds successfully, even though the new config was duplicated from release.

### Additional Information

* React Native version: 41.2
* Platform: ios
* Operating System: MacOS

**Comment by brentvatne** [comment]
Hello! Please post this to StackOverflow :)

**Comment by chrxs** [comment]
Hi @retailos did you post this on Stackoverflow? I'm having the exact same issue, and wondering if you got a solution already? Thanks

**Comment by peterept** [comment]
same. I just tried to install react-native-maps, and I get this error too.

**Comment by jordanmkoncz** [comment]
I'm also having the same problem. I'm using react-native 0.41.2.

@retailos @chrxs Did either of you find a solution?
