### ISSUE TITLE
Navigator.NavigationBar as a component

### ISSUE THREAD

**Issue by ButuzGOL** [facebook/react-native#1256]
Can't move NavBar as a component
Two examples

First -> Works
```
<Navigator
  renderScene={this.renderScene.bind(this)}
  navigationBar={
    <Navigator.NavigationBar routeMapper={NavigationBarRouteMapper} />
  }
/>
```

Second -> Not working
```
var NavBar = React.createClass({
  render() {
    return <Navigator.NavigationBar routeMapper={NavigationBarRouteMapper} />
  }
});

<Navigator
  renderScene={this.renderScene.bind(this)}
  navigationBar={
    <NavBar />
  }
/>
```

**Comment by ide** [comment]
You probably need to pass forward all of the props. Try this:
```js
 <Navigator.NavigationBar {...this.props} routeMapper={NavigationBarRouteMapper} />
```

Also if NavigationBar has any instance methods on it that the Navigator calls, you will need to forward those calls.

**Comment by nigelmanson** [comment]
@ide A quick silly question. But is it possible to not use: 

<Navigator.NavigationBar
				routeMapper={NavigationBarRouteMapper}
				style={styles.navBar}
			/>

in the Navigator navigationBar param? The reason is. I want to create a list of tabs and have access to the Navigator Context so I can use navigator.push without using the standard NavigationBarRouteMapper

**Comment by ide** [comment]
You can override the props you don't want. For example if you add "style=[customStyle]" to the list of props it will override the forwarded style from {...this.props}.

**Comment by ButuzGOL** [comment]
@ide Thanks works fine

**Comment by julianocomg** [comment]
I'm passing `{...this.props}`, the component update occurs normally when receiving new props, but the NavigationBar itself doesn't update. The components stay the same of the first route.

I'm using React Native v0.10.0

Working:
```
<Navigator
  renderScene={this.renderScene.bind(this)}
  navigationBar={
    <Navigator.NavigationBar routeMapper={this.getRouteMapper()} />
  }
/>
```

<br>
Not working :(
```
class Navbar extends React.Component {
  render() {
    return <Navigator.NavigationBar {...this.props} />
  }
}

<Navigator
  renderScene={this.renderScene.bind(this)}
  navigationBar={
    <Navbar routeMapper={this.getRouteMapper()} />
  }
/>
```
