### ISSUE TITLE
pushnotificationios remote push notification custom  fields

### ISSUE THREAD

**Issue by adriancuco** [facebook/react-native#12570]
### Description
Hi, 
I am trying to pass a custom parameter to remote push notification as follows:
{
  "aps":
  {
    "alert": "News!",
    "sound": "default"
    "myurl" : "https://raywenderlich.com",
  }
}

Please advise the way to get myurl parameter sent by Remote Push notification.

Thanks a lot

* React Native version: 0.41
* Platform: iOS
* Operating System: MacOS

**Comment by brentvatne** [comment]
Hello! Please post this to StackOverflow.
