### ISSUE TITLE
When is onLayout fired?

### ISSUE THREAD

**Issue by ide** [facebook/react-native#1257]
I noticed it's not called when an absolutely positioned element is moved (changed `top: 0` to `top: 100`), but it is called when the element is resized. This isn't causing problems for me but I'd like to know what the intent is, get bugs fixed if there are cases where it's not firing, and document it.

**Comment by ide** [comment]
cc @sahrens

**Comment by sahrens** [comment]
Hmm, I thought it would fire for that I case - I'll check it out and add to the integration test.  The intention is that it should change any time the values it provides would be different. 

The implementation is pretty simple - any time a frame is updated, we fire onLayout for that view (if a handler exists). Are you sure the handler is on the right component?

**Comment by ide** [comment]
I remember not getting layout events when I adjusted the `top` of a component but then getting them when I adjusted `left` or `right`, but now I'm seeing layout events when modifying `top`, as expected. I may have been doing it wrong or perhaps today's commits might have fixed something.

Will reopen if I see this not fire when I expect it to.
