### ISSUE TITLE
use mutliple events in single scene 

### ISSUE THREAD

**Issue by kazimmusani** [facebook/react-native#12574]
Hi,

i have multiple screens and i want to use both in single scene, is that possible ?

Screen1: Screen2

<Router>
    <Scene rightTitle="Add" key="DataList" component={Screen1, Screen2} hideNavBar />
</Router>

**Comment by ericvicenti** [comment]
Hi, your issue isn't super specific. Please provide lots of details next time, including example code, as well as what version and platform you're using.

I'm not sure what events you're referencing, but generally, yes, you can re-use events between screens.

One way we do that at FB is by using a polyfill of node's event emitter API: https://nodejs.org/api/events.html#events_class_eventemitter
