### ISSUE TITLE
The debugging with stetho documentation is not updated apparently.

### ISSUE THREAD

**Issue by icnovaro** [facebook/react-native#12573]
**Description**

The **onCreate** showed in the react-native debugging with stetho page is different that the showed in github.

```java
//Showed in react page
public void onCreate(Bundle savedInstanceState) {
      super.onCreate(savedInstanceState);
      Stetho.initializeWithDefaults(this);
      OkHttpClient client = new OkHttpClient.Builder()
      .connectTimeout(0, TimeUnit.MILLISECONDS)
      .readTimeout(0, TimeUnit.MILLISECONDS)
      .writeTimeout(0, TimeUnit.MILLISECONDS)
      .cookieJar(new ReactCookieJarContainer())
      .addNetworkInterceptor(new StethoInterceptor())
      .build();
      OkHttpClientProvider.replaceOkHttpClient(client);
}
```

```java
//Showed in github page
public void onCreate() {
     super.onCreate();
     Stetho.initializeWithDefaults(this);
     OkHttpClient client = new OkHttpClient.Builder()
     .connectTimeout(0, TimeUnit.MILLISECONDS)
     .readTimeout(0, TimeUnit.MILLISECONDS)
     .writeTimeout(0, TimeUnit.MILLISECONDS)
     .cookieJar(new ReactCookieJarContainer())
     .addNetworkInterceptor(new StethoInterceptor())
     .build();
     OkHttpClientProvider.replaceOkHttpClient(client);
}
```

**Reproduction**

I'm new in react and I was trying to debug my app with stethos but I was having errors by following the react page instructions, but when I used the github onCreate method my debug works!.

**Additional Information**

React Native version: 0.41.2
Platform: Android
Operating System: Win 10

**Comment by hramos** [comment]
This is due to the way the website is built. You can always see the same docs as those from `master` on GitHub by clicking on the release version at the top of the site and choosing "master". You'll see the version change to `next` in that case.
