### ISSUE TITLE
RN okhttp okhttp-ws  not compatible 

### ISSUE THREAD

**Issue by devinhu** [facebook/react-native#12577]
My project is useful to okhttp, I upgrade the okhttp version to the latest version of 3.6.0. but RN need to use okhttp-ws, the latest version of okhttp-ws 3.4.0 is not compatible with the latest version of okhttp, please help to solve this problem，thanks!

**Comment by ericvicenti** [comment]
This isn't something that is likely to be fixed within RN. Sorry but I think the best thing may be to wait until okhttp-ws is compatible

If you need to use modern versions of RN with an earlier version of okhttp, you could fork RN for your project and revert the commit that upgraded okhttp.
