### ISSUE TITLE
Wrapping a view in TouchableOpacity breaks alignItems:'stretch', but only in flexDirection:'row'

### ISSUE THREAD

**Issue by jamesisaac** [facebook/react-native#12581]
### Description

The docs for `TouchableOpacity` state that it changes wrapped view opacity "without actually changing the view hierarchy", so I'd expect it to not have an effect on flexbox layout.

However, I'm unable to create a row of items that match the parent's height if some of them are wrapped in a `TouchableOpacity` - as soon as they get wrapped, they no longer stretch, and just match the size of their content.

This problem doesn't occur if the axes are inverted (a column of items that match the parent's width).

This isn't an issue with `TouchableNativeFeedback` either, which makes it hard to create this design pattern cross-platform with consistent CSS.

### Reproduction

https://rnplay.org/apps/cIqYXw

Top half of screen works (`flexDirection: 'column'`), bottom half doesn't (`flexDirection: 'row'`).

### Solution

Don't really have any insight into this myself.  Maybe even related to Yoga rather than RN..?

### Additional Information

* React Native version: 0.41
* Platform: iOS and Android

**Comment by jamesisaac** [comment]
Ok, turns out the root of my issue was out of date docs, submitted a PR here: #12583 

However, I can't help but feel the current approach is a bit inconsistent?  Out of the 4 current `Touchable*` components, 1 is wrapped in a `View`, 1 is wrapped in an `Animated.View`, and 2 are cloned elements?  So for them to be at all interchangeable inside layouts, custom wrapping logic is needed.

Also, even though I can now work around this issue, I still don't quite understand the inconsistency between column/row orientation in my example.  Setting `flexDirection: 'row'` on the `TouchableOpacity` doesn't help, and that's the only difference between the two axes that I'm aware of.  Perhaps someone could confirm what's going on there?

**Comment by ericvicenti** [comment]
cc @emilsjolander

**Comment by emilsjolander** [comment]
I don't know anything about how TouchableOpacity works but from the look of the rnplay posted it look as though it wrapps it in an extra flexbox node which has a default direction of column.

**Comment by jamesisaac** [comment]
Yup you're right.  I thought I had tested it with the correct flexDirection applied to the TouchableOpacity nodes, but apparently not.
