### ISSUE TITLE
We just tried to add listener, you won't believe what happens next

### ISSUE THREAD

**Issue by rusfearuth** [facebook/react-native#12580]
### Description

I'd decided to add `PermissionListener` to `ReactActivity#requestPermissions`. Android Studio showed me that `PermissionListener` was missing in `com.facebook.react:react-native:+`. I dived deep and found that `react-native` for Android is **v0.20.1** and it didn't have a lot of interfaces, classes and etc. How could it be possible? Why is ReactNative 0.41.2 in Github and 0.20.1 in maven?

I'd tried to ignore errors from Android Studio and I added `imports` and wrote code with using of `PermissionListener` and It's worked!

Does anybody know what it is?

### Reproduction

Just create native module for Android and use `PermissionListener`.

### Additional Information

* React Native version: 0.41.2
* Platform: Android
* Operating System: MacOS

**Comment by hey99xx** [comment]
Because react-native no longer publishes to maven; but only to npm. Also shame on you for clickbait title

**Comment by rusfearuth** [comment]
@hey99xx 'cos I haven't found any information about it in [docs](https://facebook.github.io/react-native/docs/native-modules-android.html).

**Comment by hey99xx** [comment]
That doesn't make your title any better. Also it is explained in this link http://facebook.github.io/react-native/docs/integration-with-existing-apps.html

> 2. Install react-native in your Android application root directory to create node_modules/ directory.

> 4. Add `com.facebook.react:react-native:+` and a `maven` pointing to the react-native binaries in `node_modules/` to your `build.gradle` file.

You're likely missing these steps. Instead of pointing to public maven, which only has up to 0.20, you need to use your node_modules directory.

**Comment by rusfearuth** [comment]
@hey99xx hmmm.... But why? Using `node_modules` looks like a workaround =/ I won't believe that so strong programmers from Facebook wouldn't build and upload JAR to maven )

Okey, it doesn't matter. Thanks for help )

**Comment by Etheryte** [comment]
See https://github.com/facebook/react-native/issues/6459#issuecomment-196594689
