### ISSUE TITLE
Jest coverage is throwing packager errors

### ISSUE THREAD

**Issue by kirkstrobeck** [facebook/react-native#12582]
#### What I did

I added Jest to my project and started generating code coverage reports, which creates a folder named "coverage" at the project root.

#### What you expect to happen

I expected nothing to happen with the code.

#### What actually happens

Packager is looking at it for some reason, and it is causing an error.

```js
TransformError /PATH/coverage/lcov-report/sort-arrow-sprite.png: Unexpected character '�' (1:0)
```

### Reproduction

Having trouble reproducing.

### Solution

The coverage folder should not be included in the packager logic or I should be able to ignore it. It’s unclear why it is looking in there as I have not linked to any files in the folder.

### Additional Information

* React Native version: 0.39.2
* Platform: iOS
* Operating System: OS X 10.12.3

**Comment by ericvicenti** [comment]
cc @cpojer

**Comment by kirkstrobeck** [comment]
- I have since upgraded to `0.41.2` and am still experiencing the issue, so any additional notes may be applicable to only this newer version
- Tried https://github.com/facebook/react-native/issues/7271#issuecomment-215375355 and it didn’t work
- It throws the error when the coverage report is generated. If I hit reload, I can use my app just fine even though the offending `.png` is still present. It seems to be that the Packager file watcher is having/starting/causing the issue.

**Comment by kirkstrobeck** [comment]
This worked for me http://stackoverflow.com/a/41963217/537998

This still feels like a bug to me, but I’ll close since the issue can be resolved.

**Comment by rogerkerse** [comment]
this is more like a bug. Quite unintuitive to do this with every react native project
