### ISSUE TITLE
ListView disappear after RefreshControl has been triggered

### ISSUE THREAD

**Issue by nicolabortignon** [facebook/react-native#12598]
Here visually what happens : 
![feb-27-2017 11-12-36](https://cloud.githubusercontent.com/assets/883459/23357368/c2d79972-fcdd-11e6-9db0-18a7a6f96a35.gif)

Here the [code](https://github.com/PolyStyle/RNFashion/blob/master/app/components/Stream/StreamListView.js) 

Please note how I moved the rendering of the data for the list view, outside any react lifecycle. This is not the end case, but for the bug report, I just wanted to be sure that there are no other interference.

what happen is: 
- I pull down my list view, the view is visible until the refresh is fully triggered.
- the API is called correctly (although please note I don't attach a callback on the API call because is an action dispatched towards redux)
- the function componentWillUpdate is also called correctly, and the state isRefreshing is set to false.
- unfortunately, the list disappear

**Comment by Amurmurmur** [comment]
Have you treid to set padding to the contentContainerStyle?
```
contentContainerStyle={{paddingTop: 64}}
```

**Comment by nicolabortignon** [comment]
You meant on the ListView, right ? this is what happened

![feb-27-2017 13-21-42](https://cloud.githubusercontent.com/assets/883459/23361199/bacc9e5a-fcef-11e6-863b-a4f2d5f7447f.gif)


Unfortunately from the Inspector on the emulatore I cannot see the ListView anywhere after the pull to refresh ..

**Comment by Amurmurmur** [comment]
try set it to the style prop of the list view, the padding

**Comment by nicolabortignon** [comment]
Unfortunately it looks exactly like the last gif i posted.

Also note that this StreamListView, is a module included in this [class](https://github.com/PolyStyle/RNFashion/blob/master/app/containers/Stream/StreamContainer.js)

And both the ListView, and the View containing the listView has flex:1.  I'm really puzzled :/

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
