### ISSUE TITLE
Module does not exist in the module map for all external npms

### ISSUE THREAD

**Issue by vba** [facebook/react-native#12596]
### Description

When I try to import a class from an external, third party npm package I get the exception `Module does not exist in the module map for all external`.  I've tried 4 or 5 different third party packages, the result is the same.

### Reproduction

Install for example `npm install -S react-native-action-button`

Dependencies:
```json
  "dependencies": {
    "react": "~15.4.0",
    "react-native": "0.41.2",
    "react-native-action-button": "2.6.0"
  }
```

Component:
```js
import React, {Component} from 'react';
import ActionButton from 'react-native-action-button';

import {AppRegistry, StyleSheet, Text, View} from 'react-native';

export default class Readings extends Component {
    render() {
        return (
            <View>
                <Text>
                    Readings!
                </Text>
            </View>
        );
    }
}

AppRegistry.registerComponent('Readings', () => Readings);

```

### Solution

I have no idea how to fix it.

### Additional Information

* React Native version: 0.41.2
* Platform: Android
* Operating System: MacOS (10.12.2)

**Comment by ericvicenti** [comment]
I just tried with `react-native-action-button` on a fresh project, and importing the button worked fine for me on the same version of RN Android.

Maybe this is related to `node --version`? I'm on `v7.4.0`

**Comment by vba** [comment]
Hi Eric, 
Indeed, after updating it works better. Thanks a lot.

**Comment by ericvicenti** [comment]
Great! If you can think of a place to document this fix, that would be awesome
