### ISSUE TITLE
RCTViewManager.h not found

### ISSUE THREAD

**Issue by zabojad** [facebook/react-native#12607]
### Description

I'm trying to create a native iOS UI Component as [described there](https://facebook.github.io/react-native/docs/native-components-ios.html).

When compiling in XCode, I get `RCTViewManager.h not found`.

### Reproduction

Simply follows the example steps of the MapView custom component implementation (described there)[https://facebook.github.io/react-native/docs/native-components-ios.html].

### Solution

Fix the documentation or react native 0.41.2 depending on where the issue comes from.

### Additional Information

* React Native version: 0.41.2
* Platform: iOS
* Operating System: MacOS

**Comment by zabojad** [comment]
OK I've solved my issue with header search pathes settings. This should be indicated in the doc imho...

**Comment by mikach** [comment]
@zabojad how did you solve it?

**Comment by zabojad** [comment]
@mikach  In the build settings, I've added the nodes_modules/React directory in the Header search path.

**Comment by dmueller39** [comment]
@zabojad This is probably not necessary, and has ALWAYS led to problems for me. What you want is for xcode to find the headers in the build folder (It searches there automatically). The way react is guaranteed to be built in the right order is through the schemes. If you create a new project via `react-native init NewProj` you can see how this is set up. Under Manage Schemes->NewProj->Build "Parallelize build" is unselected, and React is listed as a target before NewProj. I would look through all those schemes and make sure that you have schemes that detail the proper build order when necessary.

**Comment by Noitidart** [comment]
@dmueller39 what would be the solution then? I am also getting the problem when I type:

     #import <React/RCTViewManager.h>

**Comment by ovieimara** [comment]
i copied RCTViewManager from ...../node_modules/react-native/React/Views to ..../ios/Pods/Headers/Public/React/  problem solved. Other files were also declared not found and did same thing copying the file from ...../node_modules/react-native/React/Views/ or ...../node_modules/react-native/React/Base/ to ..../ios/Pods/Headers/Public/React/. Problem solved totally.

**Comment by Noitidart** [comment]
@ovieimara check this out - https://medium.com/@Noitidart/bridging-a-swift-component-from-cocoapods-7ffa04388963 - its long but its what i learned.
