### ISSUE TITLE
Gotcha - app.json loaded instead of app/index.js

### ISSUE THREAD

**Issue by rhysburnie** [facebook/react-native#12608]
Hello,

I was having an issue starting a very basic app where I had a file `./app/index.js` containing a component to mount in the registry which would throw an error when imported like so:

`import App from './app'` would throw an error when registering `App`

But it would work fine if imported like: `import App from './app/index'`

The expectation of `import App from './app'` is that it would import the default of the `index.js` file of that directory.

However after further investigation I determined that when using the path `'./app'` the build system is instead preferring the root level `./app.json` file. 

So the import statement works but it's loading the pojo of the json data (an object containing two properties: `name` and `displayName`)

More info on how I arrived at this is in this closed issue: https://github.com/facebook/react-native/issues/12539

Sure, now that I know what is going on I know to simply avoid having an `./app/index.js` file or understand that in that one case you need the full path to index, however I did waste a considerable amount of time reaching that conclusion and I think it's possible that other developers may choose to have an `./app/index.js` file and also wonder whats going on.

**Comment by ide** [comment]
This is the same behavior as Node's require() algorithm, which RN aims to follow where it makes sense (i.e. most places). I don't think the RN repo is the right place to document Node gotchas.

My recommendation in Node and RN is not to use index.js, name your files more explicitly.

**Comment by jakecraige** [comment]
Did y'all consider naming/renaming the `app.json` file something different? Maybe `rn-app.json`, `config-app.json`, `app-config.json` etc?

I just came across this same thing and spent a solid few hours attempting to debug before finding this issue. For the SEOs, I was getting the `__fbBatchedBridge` error.

I've seen many apps that have an `app/index.js` file so while this is expected behavior of Node, this seems likely to affect many people unintentionally by using a generic name that conflicts with that pattern.

**Comment by rhysburnie** [comment]
@jakecraige yeah that was my original point, no one seemed interested tho.
Also when you first create an app the `app.json` doesn't exist, its being generated when you start up for some reason, not sure why, it only contains data you can get dynamically from other sources like the `package.json`.
I of course simply don't use an `app/index.js` now because I know, but I don't get why you wouldn't simply mention in the docs - dont use an `app/index.js`.
meh - whatever
