### ISSUE TITLE
Image never reloads with same uri

### ISSUE THREAD

**Issue by RyanMitchellWilson** [facebook/react-native#12606]
I am using an Image component to display a profile picture but no matter what I do to the image component it will not reload the image. I have to use the same url for the profile pictures so I tried to give the Image a unique key prop to try and get it to reload the image but it still just uses the image from cache. I have changed the image on the server countless times but the Image component only shows the original image it got for the url.

It would be great if there was a prop to pass into Image that forces it to refresh the image every time it is rendered.

In a perfect world it would display the image from cache while fetching the new image, compare the two then decide if the image has changed.

* React Native version: 0.41.0
* Platform: Both

**Comment by ramilushev** [comment]
@RyanMitchellWilson What I do as a workaround is add a meaningless query parameter to the url. Now whenever I want the image to reload, I just change that param and that invalidates the cache.

**Comment by RyanMitchellWilson** [comment]
So it turns out I was actually hitting the wrong dev environment for the picture so it just looked as though it wasn't changing when it actually was.

**Comment by RyanMitchellWilson** [comment]
Well it seems I was actually right the first time so I'm going to reopen this issue. I even gave the image a key of Math.random() and it still keeps loading from cache when the image on the server has changed multiple times

**Comment by RyanMitchellWilson** [comment]
Using @ramilushev suggestion worked but it feels hacky and probably shouldn't be needed

**Comment by LEEY19** [comment]
@RyanMitchellWilson have you found a better solution to this ever since then? I do feel that this is an issue that the developers in FB have to look into. its been re-raised and no good solution has been given till now

**Comment by huangmr** [comment]
Same issue here (only this time with FB account images, LOL). 
On iOS the image seems to refresh okey-ish after the image view is unmounted, and it also has a `cache` props for that.
On android the image is cached for ever unless do something like @ramilushev suggested, although it is only a workaround and not without side effects (e.g. no cache to use after path change, producing too many junk cache copies for the same image).
The issue probably boils down to the Fresco library (the Image component uses internally), which currently doesn't seem to have a good knowledge about when to invalidate its cache, and there is no current way of forcing it to invalidate either (or if there is one please let us know).

**Comment by wuyunqiang** [comment]
ios I can set
<Image key ={this.count++} style={{width:SCALE(200),height:SCALE(70)}} source={{uri:ver,cache: 'reload'}}/> and is ok.
but android stil bad. please let me know if it be solve.

**Comment by RyanMitchellWilson** [comment]
This is still a problem

**Comment by dbyilmaz** [comment]
@RyanMitchellWilson  
Did you solve the problem?

**Comment by RyanMitchellWilson** [comment]
@dbyilmaz Not exactly I'm still using the work around stated above adding a Math.random() to the query string in a way that doesn't affect the url. This causes the url to be different every time so it will actually fetch the image instead of just grabbing it from the cache.

**Comment by dbyilmaz** [comment]
@RyanMitchellWilson  I am using your workaround.  I think it is not good. I guess facebook don't think to solve this problem.

**Comment by dooboolab** [comment]
@RyanMitchellWilson @dbyilmaz 
you can fix this problem by adding new Date() value in key.
like
```
<Image
  key={new Date()}
  style={styles.drawerAccountImg}
  source={uri: this.state.photoURL}
/>
```

However, I've not tested in android yet.

**Comment by malinamircu** [comment]
Hi

This worked for me on Android emulator:

 <Image key={(new Date()).getTime()} source={{ uri: global.SERVER_ROOT + item['LOGO_IMG']+'?time'+(new Date()).getTime(), headers: {Pragma: 'no-cache' } }} style={{ width: width / 5, height: 100 }} />

Hope it hepls
Malina

**Comment by crazyfree** [comment]
add a query string after url, works for both platform
<Image
  style={styles.drawerAccountImg}
  source={uri: this.state.photoURL + '?' + new Date()}
/>

**Comment by dbarros** [comment]
Adding a query param to the source works. But it's all too hacky.

**Comment by Padillahirpan** [comment]
i'm still cant believe its really works

**Comment by indrajeet1629** [comment]
add a 'time=' param along with image URL, works as well.

<Image source={ { uri : this.props.userData.profileImgURL + '?time=' new Date() }} />

**Comment by Dror-Bar** [comment]
Why is this closed? cache: 'reload' doesn't work on Android. That's a bug.

**Comment by I-O-O-I** [comment]
<Image source={{uri: <your_image_uri>, CACHE: 'reload'}} />

CHACHE prop worked for me.

**Comment by Dror-Bar** [comment]
@I-O-O-I 
As mentioned in the thread, this is for IOS only, it does not work for Android.

**Comment by ahpollen** [comment]
+1

**Comment by akashsinghalcoder** [comment]
`        <Image  style={{flex:3,width:'100%'}} source={{uri: image.thumbnailUrl+'?'+new Date().getDate()}}  key={`image${i}`}/>
`

**Comment by harikanammi** [comment]
hi, 
i am using this property for android:-
```
<Image
source={uri: this.state.uri + '?' + new Date()}
/>
```
For iOS:-
<Image source={{uri: this.state.uri, CACHE: 'reload'}} />

But any changes doing in that particular screen then image is disappearing like below mentioned gif file :-
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/31063894/50724748-57b6dd00-1118-11e9-9d44-836539d57fc3.gif)
Please give any suggestion for this issue.

**Comment by agamadev** [comment]
Instead of new Date(), I added Math.random, it worked for me in both iOS and Android:

`<div v-bind:style="{ 'background-image': 'url(' + this.$root.profile.image + '?rnd=' + Math.random() + ')' }" class="..."></div>`

It would be something like this for _Image_ (not tested):

`<Image source={ uri: this.state.uri + '?rnd=' + Math.random() } />`

**Comment by agamadev** [comment]
I **haven't tried** this, but in Vue the same happened to me. It didn't work with Date() but it worked with Math.random(). It would be something like this:

`<Image source= { uri: this.state.uri + '?rnd=' + Math.random() } />`

**Comment by basanthalluri** [comment]
hi @agamadev, thank you for your reply. ` <Image source= { uri: this.state.uri + '?rnd=' + Math.random() } />` it is not working for me. 
image Disappearing issue is not fixed.

**Comment by harikanammi** [comment]
hi @agamadev, thank you for your reply. 
`<Image source= { uri: this.state.uri + '?rnd=' + Math.random() } />` this is not working for me.
Image disappearing issue is not fixed.

**Comment by Salakar** [comment]
Hey all. Thanks for reporting this and posting workarounds. It'd be great if someone could send a PR to support some (if not all) the same options as iOS [currently does](https://facebook.github.io/react-native/docs/images#network-requests-for-images). 

If it helps in creating a PR; the native Image view code can be found in the following places;

 - **ImageView**: https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/image/ReactImageView.java
 - **ImageHelper**: https://github.com/facebook/react-native/tree/master/ReactAndroid/src/main/java/com/facebook/react/views/imagehelper

Internally this uses Fresco's ImagePipeline, which has various caching controls as seen [here in the source](https://github.com/facebook/fresco/blob/master/imagepipeline/src/main/java/com/facebook/imagepipeline/core/ImagePipeline.java).

**Comment by pbitkowski** [comment]
So we want to implement cache property for source on Android with the same implementation as iOS? For reference: https://facebook.github.io/react-native/docs/images#cache-control-ios-only

**Comment by ashishgunjal5896** [comment]
> add a query string after url, works for both platform
> <Image
> style={styles.drawerAccountImg}
> source={uri: this.state.photoURL + '?' + new Date()}
> />

Thanks it Working.. :)

**Comment by ashishgunjal5896** [comment]
Can someone tells React Native 0.59 is stable to upgrade. Currently using 0.57

**Comment by MisterFail** [comment]
Yes, this is still a big issue in RN for Android I think..

**Comment by dann1609** [comment]
Workaround work too with local images like /storage/.../asdasd.jpg

**Comment by cpojer** [comment]
Is there anybody who could send a PR like @Salakar was proposing?

**Comment by Usamaliaquat123** [comment]
what a problem bro 💐

**Comment by bimalgrg519** [comment]
I am planing to ask my backend developer to send date of image created along with image uri.

**Comment by panda0603** [comment]
is this still an ongoing issue? been couple of years now

**Comment by Benjamin-Daniel** [comment]
Yeah I think so

**Comment by jacquesdev** [comment]
Simpy adding `key={new Date()}` seemed to do the trick for me

**Comment by lakhvirk** [comment]
I fixed this issue by adding random string.
This is similar to adding date but it wasn't working for me because i may need to encode url for spacing.

    <Image
        style={styles.image}
        source={uri: `${this.state.photoURL}&random=${Math.random().toString(36).substring(7)}`}
    />

OR
If you don't have existing parameters in that image url.

    <Image
        style={styles.image}
        source={uri: `${this.state.photoURL}?random=${Math.random().toString(36).substring(7)}`}
    />

**Comment by mechazod** [comment]
@malinamircu It works for me when appending date time in photo URL, but it will flicker the image.

**Comment by formaldehydeson** [comment]
would be nice if there was a way to flush the image cache for scenarios like this
@mechazod to fix the flicker thing I'm setting 

``this.state = {now: Date.now()}``

in my constructor and using that as the image URL parameter so that it doesn't re-download the image every time the component re-renders

**Comment by mechazod** [comment]
@formaldehydeson Yes, that will be a great idea to avoid the flicker effect.

**Comment by xstable** [comment]
You easily also can set `new Date().getDay()` instead of `Date.now()`, this way it's only refreshed once a day (e.g. if Image is not such important to refresh [or use hours, minutes....).
This way, the refresh isn't that often (which will result in better App-Performance and lower Network-Traffic)

At least, **all those Solutions are really ugly** and **bad for the App-Performance**.
In my case, it seems to happen only at some Android-Devices (not at IOS at all). I'm not yet figured out, if it's the Android-Version or special Devices (maybe Manufacturer Changes at the OS).

But I would heavily appreciate if  this bug will be analysed and solved soon.

**Comment by EricWiener** [comment]
I'm having this issue with a local image. The image is being changed but kept at the same absolute path. The Image component is not re-rendering. I tried CACHE: 'reload', but it doesn't help.

**Comment by formaldehydeson** [comment]
Since my issue here was with user uploaded profile picture images, I ended up adding a timestamp in their profile with the last time they updated their profile picture and I'm appending that to the image url instead of using a date value set in the component constructor. Still pretty annoying that I need to result to that but it gives the best user experience with the least amount of unnecessary re-loads.

**Comment by duclahoang** [comment]
> add a 'time=' param along with image URL, works as well.
> 
> <Image source={ { uri : this.props.userData.profileImgURL + '?time=' new Date() }} />

Thanks a lot! 👍

**Comment by chetna-webonise** [comment]
Hi , adding some extra params  in the image uri worked for me.
Though it is not a proper solution for this issue.

  ```
const ImageUrl = `${gameBgImg}?time=${new Date()}`;
<Image
        source={{ uri: ImageUrl, cache: 'reload' }}
        key={new Date().getTime()}
     / >
```

**Comment by Tyfoods** [comment]
Experienced same issue. Used randomized parameter to solve it.

Something like:
<Image source={{uri: 'exampleurl.com?'+Math.random()}}/>

Very bad solution, hoping for a fix on this for sure!

**Comment by Yaolegol** [comment]
still is problem

**Comment by PriyaKailash** [comment]
> add a 'time=' param along with image URL, works as well.
> 
> <Image source={ { uri : this.props.userData.profileImgURL + '?time=' new Date() }} />

>Thank you

**Comment by PriyaKailash** [comment]
> add a 'time=' param along with image URL, works as well.
> 
> <Image source={ { uri : this.props.userData.profileImgURL + '?time=' new Date() }} />

Hi, Thanks.
This is working for me on Android, but it's taking time to load the image

**Comment by ahkay** [comment]
This is still problem for me - the dummy params workaround isn't acceptable, as my users have super low spec devices, are very data-limited and need to load hundreds of images each render but on the odd occasion that an image changes, it must update.

Saving a timestamp in the URI is also an unusable hack because the images are managed, updated and accessed by a main rails app using a gem. The gem stores and retrieves filenames with a specific syntax.

Is there no way to access the cache, even if it means diving into some native code? The ability to flush an image of a specific reference from the cache seems like a trivial function.

**Comment by nguyentrannhan** [comment]
+1

**Comment by cyberdude** [comment]
+1. Same issue here

**Comment by WasimIbKhan** [comment]
+1, still an issue, tried all the solutions that are practical for my app.

**Comment by martinivanalfonso** [comment]
Still an issue, my use-case is updating the image 2/·3 times in less than a second without flickering (sort of live streaming). Using time params, intervals and images on top of each other I found a way to partially overcome the issue, however after updating the image 5/6 times in a row it simply stops updating until a unmount and remount, which can only indicate native cache issues as it's a very random behavior.

**Comment by 15110011** [comment]
`            source={{uri: <yourImgUrl> + '?' + new Date()}} `
`              key={<yourImgUrl>}`
  `            onLoadStart={() => setIsShowLoading(true)}`
`              onLoadEnd={() => setIsShowLoading(false)}`
`              resizeMode="contain"`
After tried a lot of solutions above then this config is working for me.

**Comment by ropmansk** [comment]
Adding a timestamp or a random string to an url can result in poor performance because of downloading and rerendering image with each render cycle and flooding the cache.

A better workaround is to increment a counter on a backend every time the image gets updated and then append it to an url when loading image in the client.

**Comment by amoerke** [comment]
> Hi
> 
> This worked for me on Android emulator:
> 
> <Image **_key={(new Date()).getTime()}_** source={{ uri: global.SERVER_ROOT + item['LOGO_IMG']+'?time'+(new Date()).getTime(), headers: {Pragma: 'no-cache' } }} style={{ width: width / 5, height: 100 }} />
> 
> Hope it hepls
> Malina


The magic that worked for me was **_key={(new Date()).getTime()}_**

Thanx Malina!

**Comment by MrGVSV** [comment]
All the above solutions recommending appending a random string assume that the `uri` is a web URL. I don't think this will work for URIs that use the local file system (i.e. `file:///Users/someuser/.../Documents/image.png`). Appending a random query string results in the file not being found.

**Comment by RocketRonz** [comment]
Messing around with the URL is not a great solution. If your image URLs are generated and contain validation information, eg. when using AWS Amplify, you can't just add an extra query parameter as a cachebuster.

I found that setting the "key" property to {new Date().getTime()} on the Image component achieves the same result with the latest version of Expo (SDK44)

**Comment by RocketRonz** [comment]
Messing around with the URL is not a great solution. If your image URLs are generated and contain validation information, eg. when using AWS Amplify, you can't just add an extra query parameter as a cachebuster.

I found that setting the "key" property to {new Date().getTime()} on the Image component achieves the same result.

**Comment by koffhessel** [comment]
The header image updates with either a change to the URI or the key of the element but it starts flickering on navigation to different pages. Anybody know a solution to this?

**Comment by Turtleted21** [comment]
Hi,
How do you add a query parameter on a require?
I try to add one but It change the link to my source

my code:
```
<Viro3DObject // Chimere -------------------------------
      source={ChimereSources.chimereCaracteres[ChimereSourceBuild1].source}
     .....
    />
```
 
    my json:

```
     epuisette_bleu_griffe: {
      source: require('../res/chimeres/epuisette_bleu_griffe/chimere.vrx'),
    },

```

Thanks

**Comment by KrisLau** [comment]
> Messing around with the URL is not a great solution. If your image URLs are generated and contain validation information, eg. when using AWS Amplify, you can't just add an extra query parameter as a cachebuster.
> 
> I found that setting the "key" property to {new Date().getTime()} on the Image component achieves the same result.

This would stop the image from caching though which i still want to happen. That's why I'm only adding the extra parameter when the image is changed

**Comment by MyPalVikram** [comment]
Has anyone come up with another solution? The ones listed in this thread still don't work for me.

```
      <FastImage
        key={new Date().getTime()}
        source={{ uri: `${source}` }}
      />
```

**Comment by MyPalVikram** [comment]
> @MyPalVikram what have you tried? this was mine from further up in the thread: [#12606 (comment)](https://github.com/facebook/react-native/issues/12606#issuecomment-1054393947)

Actually, this works!

Adding ```?=${new Date.getTime()}``` to the end of the URL.

The only thing is I have to handle the loading state because I can't preload what the exact URL is going to be. I could save it in the database with the extension that way I know what the URL will be before I even request it. 🤔

**Comment by indyteo** [comment]
Any solution for local images? The `key` trick does not work for me 😢

I have something like that:
```tsx
<Image source={{ uri: "file://" + path }} {...props} />
```

**Comment by k1mmm** [comment]
> Any solution for local images? The `key` trick does not work for me 😢
> 
> I have something like that:
> 
> ```tsx
> <Image source={{ uri: "file://" + path }} {...props} />
> ```

For local images you can use url parameters


Any solution for local images? The key trick does not work for me 😢

I have something like that:

<Image source={{ uri: "file://" + path + '?v=' + <myCustomIncrementalStateValue> }} {...props} />

**Comment by janusqa** [comment]
If you are using expo
```npx expo i expo-image```

```
import {Image} from "expo-image"
<Image source={{ uri: "blah.jpg" }} cachePolicy={"none"} />
```

**Comment by samih-sghier** [comment]
Bruh this is still an issue

**Comment by VictorDev200** [comment]
Still an issue. Using cache:'reload' doesn't apply any changes. Using '+ new Date()' on the src makes the image reload but takes like 30 seconds to trigger the change even reloading the component.

**Comment by syafiq90** [comment]
// Generate a unique query parameter (timestamp)
  const uniqueQuery = `?timestamp=${new Date().getTime()}`;

  const handleReloadImage = () => {
    // Set a new source with the updated URL
    setImageUrl(imageUrl + uniqueQuery);
  };

**Comment by noctivityinc** [comment]
Slightly cleaner version:

```
export function epoch() {
  return Date.parse(new Date());
}
```

```
  <Image
            source={{ uri: photo_uri + "?" + epoch }}
          />
```

**Comment by cliveportman** [comment]
> If you are using expo `npx expo i expo-image`
> 
> ```
> import {Image} from "expo-image"
> <Image source={{ uri: "blah.jpg" }} cachePolicy={"none"} />
> ```

Something as basic as this shouldn't require installing an additional library.

**Comment by mimo-10** [comment]
But isn't adding new images mean that the cashed data will grow, that could lead to decrease performance over time ?!

**Comment by dentemm** [comment]
The year is 2024, AI has evolved to the point it's able to do things unimaginable back in 2017 (when this bug was first reported). Mankind is even able to let paralyzed people walk again through brain implants. But my React Native app is still loading an old image on Android ...

**Comment by ahpollen** [comment]
I love this community and how we take care of each other

Andrew Pollen
***@***.***  ***@***.***>
+1 215-439-4026 / +34 611 63 19 39

**Comment by mateoguzmana** [comment]
I'm putting some effort into tackling this issue in #47182 (what could go wrong trying to fix an issue that has been opened almost 8 years ago 😄)
