### ISSUE TITLE
Move JavaScript executors to their own subproject + expose executor class

### ISSUE THREAD

**Issue by robertjpayne** [facebook/react-native#1261]
Next week I'm going to attempt to bring SpiderMonkey's JavaScript engine over to react-native. There's a few things that will need to happen with the current codebase to easily support new JavaScript engines:

* RCTBridge currently has a expose instance setter for the JavaScript executor class, but unfortunately you cannot set this before the bridge is initialised and it loads up. This should be a class method that can set the default or an initialisation option.

* React Native is including JavaScriptCore in the RCTContextExecutor and RCTJavaScriptExecutor files. This imports symbol definitions that then break SpiderMonkey due to conflicts. Would be nice to have these dependencies removed and RCTContextExecutor moved to it's own module that can be enabled/disabled easily.

### Why SpiderMonkey?

* Single C/C++ JavaScript API to expose low level native modules such as XMLHttpRequest / websocket / socket.io / WebSQL / IndexedDB etc…

* Allow exposing native objects to the JS environment to better manage things like file handling etc…

* Fine grained control over resource usage. SpiderMonkey allows the implementor to setup resource limits of both heap and stack memory and the GC will aggressively ensure those are met.

* Faster execution of the bridge due to less copying of data ( we don't have to copy JSON data just to deserialise it etc… )

* Single JS engine to run both in production and dev and debugging thanks to FireFox's remote debugger, right now it's unreliable to test certain things via the debugger because Chrome provides a lot of DOM api's that are otherwise unavailable.

Anyways, if this sounds like something everyone is happen with I'll work on a PR.

**Comment by robertjpayne** [comment]
I should note that SpiderMonkey integration itself will be a separate project apart from react-native. I just need a few tweaks to the core to allow an integration to even happen.

**Comment by vkurchatkin** [comment]
I think you can achieve most of these things with JSC, but still it would be nice to have means to customize executor

**Comment by spicyj** [comment]
You can do most of these things with JSC already, but we chose the existing JSON bridge for simplicity and to allow Chrome debugging easily. The remote debugger support sounds interesting though.

cc @jordwalke

**Comment by vkurchatkin** [comment]
> The remote debugger support sounds interesting though.

This works with Safari and JSC out of the box

**Comment by robertjpayne** [comment]
Actually a lot of these things are either poor or not suitable for what I'm after:

* JSC's remote debugging via Safari is poor, and doesn't support source maps well so it's difficult to to debug properly. Also JSC's remote debugging cannot be attached from the beginning of the program like Chrome's debugger can.

* Unless we compile JSC from source we still have to write some things inefficiently ( string copies for example ).

* JSC wont be the default for Android, and though it's probably easy enough to cross compile it it would again be nice to have a single C/C++ API and single debugger to deal with across all platforms/debugging environments.

Really though just looking at how we could decouple the executor from the main project so there isn't symbol conflicts.

**Comment by nicklockwood** [comment]
@robertjpayne I'm intending to do some work to make executor "plugins" possible in the near future. Until then, it should be reasonably simple to hack a solution to get your custom executor working.

**Comment by robertjpayne** [comment]
@nicklockwood cool -- when you do try and keep the built in ones out of the project "unless included" to avoid symbol conflicts if I can ask. 

SpiderMonkey and JSC don't play well, or someone may want to compile their own copy of JSC into it to get access to low level internals.

**Comment by robertjpayne** [comment]
I'm going to close this -- I experimented with SpiderMonkey and while it provides some benefits it's not worth the hassle and it's a huge performance hit compared to JSC.

**Comment by nicklockwood** [comment]
Thanks for looking into it anyway. Any chance you could post your findings somewhere so we can point people to it of we get requests for this in future?

Also, might be worth keeping the code just in case something changes in future to make it worth re-exploring.

**Comment by robertjpayne** [comment]
@nicklockwood it wasn't much:

* SpiderMonkey has symbol conflicts with JavaScriptCore
    * Comment out `RCTContextExecutor.h` and `RCTContextExecutor.m`
    * Remove all `#import <JavaScriptCore/JavaScriptCore.h>` and `#import "RCTContextExecutor.h"
    * Replace all `[RCTContextExecutor class]` with `NSClassFromString(@"RCTContextExecutor")`

In general there are some things internally in react-native that don't play nice with 3rd party executors:

* Built-in executors are hard coded everywhere, would be better to use `NSClassFromString`
* The batched-bridge adds the `_jsDisplayLink` to the current run loop only for the `RCTContextExecutor` and all other executors will be added to the main thread run loop. It would be great to expose this as an API on the `RCTJavaScriptExecutor` protocol so 3rd party executors could specify a run loop.

I have the code around locally, I'm still playing around with getting better debugging for JavaScriptCore. Basically I'm trying to avoid having the JS run in two different engines.
