### ISSUE TITLE
Not documented AdSupportIOS

### ISSUE THREAD

**Issue by kwef** [facebook/react-native#12623]
### Description
I had to add the RCTAdSupport.h and RCTAdSupport.m files to XCode to manually link to react native in order to get AdSupportIOS to stop throwing "undefined is not an object.... ". There ought to be better documentation for this.

* React Native version: [0.41.2]
* Platform: [iOS]
* Operating System: [MacOs]

**Comment by hramos** [comment]
Can you elaborate?

**Comment by kwef** [comment]
Sure. In order to get AdSupportIOS to work, I had to manually add files to Xcode. I feel like this wasn't clear that it was required to somehow manually link files, as the documentation about AdSupportIOS currently says nothing about this: https://facebook.github.io/react-native/docs/adsupportios.html.

**Comment by hramos** [comment]
Would you be willing to open a PR to add the necessary steps missing from that file?

Otherwise, can you comment on this issue with the exact list of steps you had to take in order to use AdSupportIOS.

**Comment by kwef** [comment]
I can open a PR. Where's the best place/file to do that?

**Comment by hramos** [comment]
You would need to add comments to the source file at https://github.com/facebook/react-native/blob/master/Libraries/AdSupport/AdSupportIOS.js. You can take a look at other APIs to see how these comments should be formatted.

**Comment by kwef** [comment]
Is there anything else that I need to do here, or is the PR all set?
