### ISSUE TITLE
Upgrade Android SDK Build-tools to 23.0.3

### ISSUE THREAD

**Issue by tlvenn** [facebook/react-native#12652]
Various parts of RN are referencing 23.0.1 version while the latest (23.0.3) has been released a year ago already. This starts to be an issue as more and more CI will provide only the latest revision for a given major SDK version. This is the case for Bitrise for example. The user can always pull the outdated 23.0.1 manually but that's an extra step he should not have to do.

And beyond CI world, we should depend on the latest revision in any case once it has been deployed for sometimes which is the case.

**Comment by hramos** [comment]
I think it would be useful if you or someone could update all the references to 23.0.3, and open an issue here for anything that appears to block you from using the latest tools. Make sure to run all the unit tests, e2e tests, and so on.

I am going to go ahead and close this issue as it does not describe anything that is specifically broken, but please do go ahead and open any issues if you find incompatibilities with 23.0.3. PRs welcome!

**Comment by tlvenn** [comment]
Hi @hramos , thanks for a feedback, I will open a PR very soon. Have a good WE.
