### ISSUE TITLE
how to confuse,compression,encryption the react native js code?

### ISSUE THREAD

**Issue by cxy200927099** [facebook/react-native#12658]
### Description

React Native JS bundle file how to confuse, compression, encryption, the existing program can not guarantee on the assets directory index.bundle file security?

When i decompose the android apk file, I get the index.android.bundle file from assets directory;
Then i open the bundle file with sublime text, I can easy find my request api  that was defined as const in js code!

React Native Is there a mechanism similar to android code confusion?

The stackoverflow has same question as below:
[http://stackoverflow.com/questions/41542516/how-to-confuse-compression-encryption-the-react-native-js-code](url)

Anyone help me? thanks very much

**Comment by ericvicenti** [comment]
We don't currently offer any code obfuscation features.

If this feature is important to you, please post the feature request on Canny, and the community can vote and help prioritize it for the core team!

https://react-native.canny.io/feature-requests

**Comment by HessiPard** [comment]
any update for this?
Generating APks with React Native needs to have a way for obfuscation bundle file otherwise the source code is visible for everyone with just simple steps ....
