### ISSUE TITLE
[0.43] Commits to cherry pick into stable

### ISSUE THREAD

**Issue by hramos** [facebook/react-native#12664]

**Comment by hramos** [comment]
## `NavigationExperimental` is deprecated in 0.43 (@ericvicenti)

These commits should be cherry-picked into the next 0.43 RC release:

- a0f49fcbd5705d5e387ee1227fe5d6c4b41ea343
- 08dbc43fa64ff1dfc0d364b6cef6262426f76b64

**Comment by hramos** [comment]
## New list components in 0.43: `FlatList`, `SectionList`, `VirtualizedList`

These commits should be cherry-picked into the next 0.43 RC release:

- 2022b1eee6fdf0dfabac6102ec5f304d2aef5516
- d2ed064519cca3512c344374178d149868889506
- 32d753164d1dc33450087fc966fa448e7070a15d

**Comment by ericvicenti** [comment]
cc @grabbou, do we usually do cherry pick issues like this? This is the first one I've seen

**Comment by grabbou** [comment]
Yeah @ericvicenti we have them for every release. 

I am adding one more here https://github.com/facebook/react-native/commit/4471c32b084acb69123463b83080152e53807daa

Will be picking and releasing today

**Comment by grabbou** [comment]
https://github.com/facebook/react-native/commit/32d753164d1dc33450087fc966fa448e7070a15d - not cherry-picking as the change that caused the bug is not present in RC

**Comment by hramos** [comment]
[v0.43.0-rc.1](https://github.com/facebook/react-native/releases/tag/v0.43.0-rc.1) has been released. Thanks @grabbou!

**Comment by grabbou** [comment]
Cherry-picked c8d922b4670127c417d744a0a1412cc6ad961fef

**Comment by grabbou** [comment]
https://github.com/facebook/react-native/commit/5873a228f41bca763c35c470375a9f3cb36f80ab
