### ISSUE TITLE
Semantic Issue when building RN project in XCode or with react-native run-ios

### ISSUE THREAD

**Issue by Parrryy** [facebook/react-native#12661]
I get the following error: 

The terminal `react-native run-ios` error:

	CompileC /Users/cparry/repos/learnium/mobile/ios/build/Build/Intermediates/RCTAnimation.build/Debug-iphonesimulator/RCTAnimation.build/Objects-normal/x86_64/RCTNativeAnimatedModule.o RCTNativeAnimatedModule.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

In xCode:
<img width="1279" alt="screen shot 2017-03-02 at 16 31 54" src="https://cloud.githubusercontent.com/assets/7785538/23517521/882bd77e-ff68-11e6-9571-f2801d2affa1.png">

<img width="273" alt="screen shot 2017-03-02 at 16 51 59" src="https://cloud.githubusercontent.com/assets/7785538/23517539/965a7616-ff68-11e6-91d2-74cc3a582fcb.png">

Only for iOS, runs fine on android. Only started happening since upgrading to v0.42.0

**Comment by Parrryy** [comment]
Just checked with my work mates, this may be an issue with my environment as they aren't having the issue...

**Comment by esamelson** [comment]
I'm getting this error as well. Have you found any solutions or workarounds?

**Comment by eneskaya** [comment]
@Parrryy have you found the problem?

**Comment by Parrryy** [comment]
Well my colleagueson weren't having the issue. So I downgraded and upgraded again and it seemed to run fine. That's the only advice I can give. I tried to reproducexplain it but couldn't.

**Comment by kwnccc** [comment]
I'm facing the exact same issue, with both react-native v0.42.2 and v0.42.3. Anyone found a way to resolve this issue?
