### ISSUE TITLE
Movies Example not working

### ISSUE THREAD

**Issue by toshi0383** [facebook/react-native#12669]
### Description

1. Clone and run Example/Movies/Movies.xcodeproj
2. Movie API responds with no data, the JS context crashes and error screen appears.

Is API token still valid?
I can submit a PR for the JS crash.

### Additional Information

* React Native version: master (fea874584)
* Platform:iOS
* Operating System: macOS Sierra 10.12.3

**Comment by janicduplessis** [comment]
Sure feel free to send a PR to fix it, we don't run that example often so it is likely it is broken :)

**Comment by ericvicenti** [comment]
The movies sample has been removed from the core RN repo. Feel free to publish standalone example apps, and we can curate a list of them for the website.
