### ISSUE TITLE
Overhead of ARTNodes based on UIView?

### ISSUE THREAD

**Issue by joewood** [facebook/react-native#1266]
Looking at the react-native implementation of **react-art**, I notice that each node is based on a `UIView`. Whereas the web version of **react-art** uses a custom reconciler.  I also see that **react-three** does something very similar.

I'm wondering what the overhead of using UIView is here, even though they are marked as invisible - are there any other costs? Is this the recommended practice for virtualizing non-UIView native objects?

**Comment by spicyj** [comment]
The extra UIView instances are temporary and are an artifact of the current view manager implementation. We'd like to remove this restriction in the future.

**Comment by joewood** [comment]
Is the temporary UIView solution being tracked in a ticket? I'm doing some OpenGL work and the overhead is non-trivial. Would be good to know if a custom reconciler is possible.

**Comment by brentvatne** [comment]
@joewood my understanding is that this is an ongoing effort that is happening in parallel with and in part driven by Android development - I'm not sure there is so much value in having an open ticket, but if you like I can reopen this.
