### ISSUE TITLE
keyboard may not show when using OPPO phone sometimes

### ISSUE THREAD

**Issue by 13160102112** [facebook/react-native#12671]
keyboard may not show when using OPPO phone sometimes

**Comment by ericvicenti** [comment]
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Comment by ZHT131** [comment]
I have the same problem, can you tell me how to solve it?
