### ISSUE TITLE
App crashes in 64 bit android devices

### ISSUE THREAD

**Issue by keerthanarbt** [facebook/react-native#12684]
Hi @astreet,
Please give some explanation. 
It seems like some issue related to cpu architecture support.
(We were able to reproduce issues in Samsung S6, S7, Lenova K4 note.. devices)

The same code works fine with other 32 bit devices like, Nexus 5,6, Asus and Moto android devices..
The same code work perfect in Apple device.

Really stuck here please help out.

**Comment by rmevans9** [comment]
@keerthanarbt it would be helpful if you provide any types of error messages or stack traces you are getting on the devices that are not working. You can gather this information by running logcat while the device is attached to your machine.

**Comment by hramos** [comment]
Please fill out the template when opening a new issue. See https://github.com/facebook/react-native/issues/12414#issuecomment-284030023
