### ISSUE TITLE
RN0.42.0 not support ios 9.2 SDK.

### ISSUE THREAD

**Issue by MingYe-dz** [facebook/react-native#12709]
I saw you modified the code in RCTProfile.m, as follows:
![image](https://cloud.githubusercontent.com/assets/19658375/23583544/88d8bad6-0182-11e7-96a5-c9f4d292ed7d.png)

but the api of ios 9.2 SDK is as follows:
![image](https://cloud.githubusercontent.com/assets/19658375/23583574/392febb6-0183-11e7-9d71-0d7f15091808.png)

so the param type is not matched。

**Comment by ide** [comment]
The existing code matches the latest docs here https://developer.apple.com/reference/uikit/uiactivityviewcontrollercompletionwithitemshandler?language=objc

You should upgrade Xcode and use the SDK for iOS 10. You app will still run on iOS 9.
