### ISSUE TITLE
Where can I find source of "Gratuitous Animation App" referred in UIExplorer?

### ISSUE THREAD

**Issue by palaniraja** [facebook/react-native#12704]
--- Please use this template, and delete everything above this line before submitting your issue --- 

### Description

I built UIExplorer from master "7e2d7f0" and I see a reference to "Gratuitous Animation App" under "[Animated](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/AnimatedExample.js#L229)" section, but i could not find it in /examples folder.

I would like to have the source or link to github repo so I can test and learn.

### Reproduction

Build UIExplorer from master and check the "Animated" section.

![screenshot_2017-03-04-20-17-40-428_com facebook react uiapp](https://cloud.githubusercontent.com/assets/124864/23579685/40b9c188-0118-11e7-970b-bf3f6be64a2e.png)

### Solution

Upload or provide link to correct github repo?

### Additional Information

* React Native version: react-native-cli: 1.0.0 & react-native@latest
* Platform: Android
* Operating System: Mac OS

**Comment by ericvicenti** [comment]
https://github.com/facebook/react-native/tree/master/Examples/UIExplorer/js/AnimatedGratuitousApp

**Comment by hey99xx** [comment]
@ericvicenti Why is AnimatedGratuitousApp included in [iOS](https://github.com/facebook/react-native/blob/0.42-stable/Examples/UIExplorer/js/UIExplorerList.ios.js#L222) but not [Android](https://github.com/facebook/react-native/blob/0.42-stable/Examples/UIExplorer/js/UIExplorerList.android.js) UIExplorer bundles?
