### ISSUE TITLE
Reference to `android avd` in Getting Started page is outdated

### ISSUE THREAD

**Issue by dfoverdx** [facebook/react-native#12707]
I hope this constitutes a "bug", and that I'm posting this in the right place.

On [https://facebook.github.io/react-native/docs/getting-started.html](https://facebook.github.io/react-native/docs/getting-started.html):

> Starting the Android Virtual Device
> Android Studio AVD Manager
> 
> You can see the list of available AVDs by opening the "AVD Manager" from within Android Studio. You can also run the following command in a terminal:
> 
> `android avd`
>
> Once in the "AVD Manager", select your AVD and click "Start...".
> 
> Android Studio should have set up an Android Virtual Device for you during installation, but it is very common to run into an issue where Android Studio fails to install the AVD. You may follow the Android Studio User Guide to create a new AVD manually if needed.

According to [https://developer.android.com/studio/tools/help/android.html](https://developer.android.com/studio/tools/help/android.html), `android` is no longer supported.

> This tool is no longer supported. Instead use Android Studio to create AVDs and create projects, or use sdkmanager to view and install SDK packages from the command line.

**Comment by ericvicenti** [comment]
This guide has recently been updated by @hramos so I think its in reasonably good shape. I was able to set up the avd without much trouble by following the guide. If you have a specific recommendation for an alternative way we should recommend, feel free to open up a pull request about it.

**Comment by hramos** [comment]
Thanks for the heads up. `android` did indeed work for me when I refreshed this recently. The new version of the guide may only be visible by [switching to the docs from `master`](https://facebook.github.io/react-native/releases/next/).

If you want to take a stab at updating the instructions to recommend using Android Studio instead of the command line tool, the relevant doc file is at https://github.com/facebook/react-native/blob/master/docs/GettingStarted.md if you want to open a PR.

**Comment by Anima-t3d** [comment]
@dfoverdx is right, the march 2017 update changed a few things. @hramos must have tried it with the previous version. @hramos do a fresh install of android studio and try to replicate your steps?

**Comment by hramos** [comment]
@Anima-t3d this should be fixed now (in master).
