### ISSUE TITLE
Adding defineEnumerableProperties to packager babelHelpers 

### ISSUE THREAD

**Issue by sonaye** [facebook/react-native#12702]
While working on a certain state management use case https://github.com/mobxjs/mobx/issues/839, i had an issue getting it to work specifically with react native. After some digging, i now understand that the react native packager uses some custom babel helpers, which can be found here [facebook/react-native/packager/src/Resolver/polyfills/babelHelpers.js](https://github.com/facebook/react-native/blob/master/packager/src/Resolver/polyfills/babelHelpers.js).

It appears that the helper needed to run my code `defineEnumerableProperties` is currently missing from the list. The helper definition as provided from babel can be found here [babel/babel/packages/babel-helpers/src/helpers.js](https://github.com/babel/babel/blob/master/packages/babel-helpers/src/helpers.js#L275-L285), a small utility.

Adding it locally to the helpers indeed fixed the issue and all is working great now.
```javascript
babelHelpers.defineEnumerableProperties = function(obj, descs) {
  for (var key in descs) {
    var desc = descs[key];
    desc.configurable = (desc.enumerable = true);
    if ('value' in desc) desc.writable = true;
    Object.defineProperty(obj, key, desc);
  }
  return obj;
};
```

I guess the question now, how can i add this custom helper and utilize it within react native, is it possible to achieve this with some sort of babel plugin? or would modifying the list of the helpers be the way to go? i will submit a pull request along with this issue detailing the modification needed.

I am using react native on top of exponent, which means that the support needs to come from here in order for it to actually get there in one of their future sdk releases.

**Comment by sonaye** [comment]
any comments on this @skevy?

**Comment by ericvicenti** [comment]
I'm landing the PR now, which will probably go smoothly
