### ISSUE TITLE
Network inspector unaccessible due to error

### ISSUE THREAD

**Issue by MarkMurphy** [facebook/react-native#12711]
### Description

Network inspector unaccessible due to error. 

### Reproduction

Create a new app with react-native-cli v2.0.1. Run iOS, Press CMD + D to open dev menu then "Show Inspector" then click on "Network". 

### Solution

Unknown

### Additional Information

* React Native version: 0.42.0
* Platform: iOS, Android?
* Operating System: MacOS

![screenshot 2017-03-05 00 36 15](https://cloud.githubusercontent.com/assets/873474/23584647/93773444-013d-11e7-97dc-537c7d2fc038.png)

**Comment by janicduplessis** [comment]
Sorry about that, we broke it in 0.42, it is now fixed.

**Comment by wkwyatt** [comment]
So what do you need to run to get it working?

**Comment by janicduplessis** [comment]
If you update react-native to 0.43.0-rc it will work.
