### ISSUE TITLE
React Native Build Successfully But not running the app

### ISSUE THREAD

**Issue by ahsanazwar** [facebook/react-native#12719]
React Native Build Successfully but not doing anything just stuck on it
![4](https://cloud.githubusercontent.com/assets/20488590/23586465/07555e30-01b7-11e7-95a5-429be0e66763.PNG)

**Comment by AlanFoster** [comment]
Is the app accessible on the android emulator itself?

**Comment by ahsanazwar** [comment]
@AlanFoster yes it is it was running fine before I upgrade the react native

**Comment by ahsanazwar** [comment]
got it solved by reinstalling node.js
