### ISSUE TITLE
[Android] Chrome Debugging - Fetch crashes with invalid cookie characters

### ISSUE THREAD

**Issue by eranbo** [facebook/react-native#12727]
### Description

Explain what you did:
Using fetch to get content of url (for example, here is a link from TechCrunch: https://techcrunch.com/2017/03/02/snap-shares-pop-more-than-40-in-public-trading-debut/)

what you expected to happen
Expected result was a resolved promise with response object that contains the web page html.

what actually happens:
Application crashed with the following exception in adb logcat:
====== start of log cat ==============
03-03 09:01:16.725 18027 18069 E AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
03-03 09:01:16.725 18027 18069 E AndroidRuntime: Process: ****, PID: 18027
03-03 09:01:16.725 18027 18069 E AndroidRuntime: java.lang.IllegalArgumentException: Unexpected char 0xbb at 1759 in Cookie value: _vdl=1; grvinsights=f7c1a76c973a0d6de78c388ffaf70ee8; _cb_ls=1; _mkto_trk=id:270-WRY-762&token:_mch-techcrunch.com-1487152437528-82715; AMCV_6B25357E519160E40A490D44%40AdobeOrg=1256414278%7CMCMID%7C65331407281978611344519258498965440918%7CMCAID%7CNONE%7CMCAAMLH-1489002656%7C6%7CMCAAMB-1489002656%7Chmk_Lq6TPIBMW925SPhw3Q; __pnahc=0; __tbc=%7Bjzx%7DJVNdWatZXHb0W21-_mpQv4BV5FC1cdbK-dHYn8RBz3K52RHVsWJVWJ4n8W6qyD_t92-Llhr2tP-ufNbqdpR8vCbtPS3MPxzmODB6PN-Y5einB_f1x8pUTBZ3QVA6ynDFXDmLreXGZYmS2fNSZKGmZqF0gmJN2e76Rmex82xcXHQRt3IX0t2Cz-dIazkWsVTIz6KSgOoPv4BYgTzwppHjpL5glE3DeuGNLvdEia1sZitiS3z4AxB5N9V5ypDswPbRQCmsZpKmhgFY4MJ82YiPLmKl-Ict69hMqFU49S9JOXDcQ-lMQlF0tW11QHpwmQ92Mua5tIl1-l8fRWeL_HkwZ-Yx2e8b8TRkAPmEKYRVI2OnLkIHNINkiAFKLaE3oZo4xZxTCW6eiOE2AQZ0iqlDV66Xhan2T02gGBYpHjioxGCDd6tTCstqrsKwi8br6fOB7ItMQA_IsPDNKZAQjbGCwI6_4O6pVF5d2my_0Yv47aGm2j7Rb_geQ7ZIxwkFiSQVisiZ9yLUqgVDTWvy_w5X0LZntZ8WM81AwORjPA8hjF8YpqsNDhjy5ptRmx4AO5b1NeNUjStdBmBecLKz_Vo_aMvXaxK3ceyd2yLXTivZBEX8kCzJwDtUpVAXJQjKR3e_SUtGBRq9AqbaKiHZrn4w91B_lhiFG6t2mhvBIvLC_9Kt4KN4kKpQ4G8zw9Q75zBR603Gw6wZx0UKxjk1ytbUEw; __pat=-18000000; xbc=%7Bjzx%7DDwd9hXyC2A67qryooM7JyE1ZewWiIKL2TNfFsnF-ClHzs7yClmGbYi_b6e2VlDvVdLbYPBfVD30PhD97ikwcxIil5ZVlsgPdRQCIymcBk5KRNlew1YM0n0l1KKZvRwfGJYNmyzMghZ1-pRa-NxQzON-VRhtglX4Ngd6sHqo2dORigP8jxqtrBirB3VUT6L9fv3K5j1sJywsTib0bIC0QdpGfgjcU2o9atsKNQm2ElD4; s_pers=%20s_vnum%3D1518688126581%2526vn%253D10%7C1518688126581%3B%20s_invisit%3Dtrue%7C1488399659738%3B%20s_getnr%3D1488397901027-Repeat%7C1551469901027%3B%20s_nrgvo%3DRepeat%7C1551469901044%3B; s_sq=%5B%5BB%5D%5D; s_cc=true; __utma=75736080.1365313809.1487152123.1488366577.1488397856.12; __utmc=75736080; __utmz=75736080.1488397856.12.10.utmcsr=feedburner|utmccn=Feed:%20techcrunch/fundings-exits%20(TechCrunch%20»%20Fundings%20&%20Exits)|utmcmd=feed; __adblocker=false; __tfp=3dde6483b75cc80a18642cd1b0fe9a28; __tpctmp=1488397902795; trc_cookie_storage=aol-techcrunch%253Asession-data%3Dv2_0618c36ba85df3605057e2b2e5fd0ef5_a24e7dc5-2560-4dce-8f0b-c29e2ed07801_1488397857_1488397903_CNawjgYQi8E_GPPIttuoKyACKAQ%7Ctaboola%2520global%253Auser-id%3Da24e7dc5-2560-4dce-8f0b-c29e2ed07801; _cb=BTaZt-BAaGcMB68RMz; _chartbeat2=.1487152126142.1488397904650.100010010011101.Cg8wwrCOr_fTDLdJZ1CLEpXtnFek6; _polar_tu=*_%22mgtn%22_@2Q_u_@_qPB7nKrt-4RIZ-Wchs-nKwx-trNZSfgbVxAP_Q_n_@2Q_s_@9Q_sc_@*_v_@4Q_a_@4+Q_ss_@_%22om5j52_Q_sl_@_%22om5j6c_Q_sd_@*+Q_v_@_4%5B269dfc3_Q_vc_@*_e_@1+Q_vs_@_%22om5j6c_Q_vl_@_%22om5j6c_Q_vd_@*+Q_vu_@_b14baf4c20bd4f985cc33de628ba1a57_Q_vf_@_%22izrdohpx_+; _parsely_visitor={%22id%22:%2272284c76-3a1b-4eb6-9a61-1b99d4a3c16e%22%2C%22session_count%22:12%2C%22last_session_ts%22:1488397860621}
03-03 09:01:16.725 18027 18069 E AndroidRuntime: 	at okhttp3.Headers$Builder.checkNameAndValue(Headers.java:320)
03-03 09:01:16.725 18027 18069 E AndroidRuntime: 	at okhttp3.Headers$Builder.set(Headers.java:300)
03-03 09:01:16.725 18027 18069 E AndroidRuntime: 	at okhttp3.Request$Builder.header(Request.java:163)
03-03 09:01:16.725 18027 18069 E AndroidRuntime: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:86)
03-03 09:01:16.725 18027 18069 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
03-03 09:01:16.725 18027 18069 E AndroidRuntime: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
03-03 09:01:16.725 18027 18069 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
03-03 09:01:16.725 18027 18069 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
03-03 09:01:16.725 18027 18069 E AndroidRuntime: 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
03-03 09:01:16.725 18027 18069 E AndroidRuntime: 	at okhttp3.RealCall.access$100(RealCall.java:33)
03-03 09:01:16.725 18027 18069 E AndroidRuntime: 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:120)
03-03 09:01:16.725 18027 18069 E AndroidRuntime: 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
03-03 09:01:16.725 18027 18069 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
03-03 09:01:16.725 18027 18069 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
03-03 09:01:16.725 18027 18069 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
03-03 09:01:16.727   591   613 W ActivityManager:   Force finishing activity com.*****/.MainActivity
====== end of log cat ==============

it looks like that some web sites/URLs crashes the application due to invalid characters in cookie value when in JS remote debug mode is enabled
### Reproduction

just call fetch('https://techcrunch.com/2017/03/02/snap-shares-pop-more-than-40-in-public-trading-debut/') when JS remote debug is enabled

### Solution

[FILL THIS OUT: What needs to be done to address this issue? Ideally, provide a pull request with a fix.]

### Additional Information

* React Native version: 0.42.0
* Platform: Android
* Operating System: linux Ubuntu 16.04

**Comment by ericvicenti** [comment]
I'm afraid this issue is going to be quite low-priority because it only affects chrome debug mode.

If you can find a simple fix, we can probably get it in.

**Comment by eranbo** [comment]
Hi @ericvicenti, thanks for the reply.

I also tried with Nuclide package in Atom IDE debugger - same thing occur, if it makes any different for prioritizing the issue.

**Comment by eranbo** [comment]
Closing this issue as it's no reproduce on HelloWorld app.
