### ISSUE TITLE
[iOS]Multiline textinput can not pop toolbar on pressing the empty area.

### ISSUE THREAD

**Issue by sohobloo** [facebook/react-native#12725]
### Description

Multiline textinput can not pop 'Paste | Select ...' toolbar when pressing the empty area.

### Reproduction

Simply render this:
```javascript
      <View style={{flex: 1}}>
        <TextInput style={{flex: 1, backgroundColor: 'yellow', marginTop: 30}}
                   multiline={true}
                   value={this.state.text}
                   onTextChange={text => this.setState({text:text})}/>
      </View>
```

If I press the line with text or cursor it works, otherwise not.
![3 -06-2017 03-49-38](https://cloud.githubusercontent.com/assets/13310861/23590738/85ee77ae-0220-11e7-91e2-f9ac350e35e3.gif)

It should pop the toolbar as the same as the iOS original APPs like Note.app do.
Single line textinput does not have this problem.

### Additional Information

* React Native version: 0.41.0
* Platform: iOS (Android not test)
* Operating System: MacOS

**Comment by ericvicenti** [comment]
This is probably not the highest-priority issue.

If you can fix this in the native code and send a PR, we can probably get it landed for you.

**Comment by shergin** [comment]
I already have a fix for it. I hope I will land it soon after proper testing.

**Comment by sohobloo** [comment]
@ericvicenti 
Here was the fix requested over a month ago.   https://github.com/facebook/react-native/issues/12740

**Comment by shergin** [comment]
Should be already fixed now.
@sohobloo Do you still experience this problem on master now?

**Comment by sohobloo** [comment]
@shergin Still in 0.43.3

**Comment by hramos** [comment]
0.43.3 !== master
