### ISSUE TITLE
undefined is not an object (evaluating NativeModules.SegmentedControlManager.ComponentHeight

### ISSUE THREAD

**Issue by jessepollak** [facebook/react-native#1272]
I accidentally ran `npm install react-native` inside of the React app folder. Since then, I've been getting the above error and can't figure out how to solve the issue.

Any ideas?

![screenshot 2015-05-13 21 51 55](https://cloud.githubusercontent.com/assets/1097953/7626240/6764d348-f9ba-11e4-821f-5c1defc80103.png)

**Comment by wim82** [comment]
Somehow i've hit the same issue. But by restarting the packager.. after doing some updates.

**Comment by wim82** [comment]
More info: it happened after setting "latest" as the version for react-native. When i set it to 0.4.1 everything is fine again.

**Comment by esauter5** [comment]
I got this issue as well. It happened after I pulled the latest from master to my fork and then tried using that local version of react-native in a react-native project.

**Comment by jessepollak** [comment]
Downgrading to `0.4.1` fixed it for me as well.

**Comment by vm06007** [comment]
how to exactly downgrade?

**Comment by brentvatne** [comment]
Does this happen for all of you if you clone the repo and run the `UIExplorer` app?

**Comment by brentvatne** [comment]
Tested this on master in UIExplorer and it works fine. Make sure you have all of these files included in your `Libraries/React.xcodeproj` 

```
react-native/React/Views/RCTSegmentedControl.h
react-native/React/Views/RCTSegmentedControl.m 
react-native/React/Views/RCTSegmentedControlManager.h
react-native/React/Views/RCTSegmentedControlManager.m
```

**Comment by jessepollak** [comment]
Tried upgrading to `0.4.4` and the issue persisted. Checked if I had those files and I didn't. Looked at my `Podfile.lock` and it had `React` at `0.4.1`. Changed my `Podfile` from `pod 'React'` to `pod 'React', '~> 0.4.4'` and it worked. I guess it's not surprising that we need to keep the Pod and JS in sync, sorry about the trouble. Hope this helps someone else!
