### ISSUE TITLE
run the example in xcode has error

### ISSUE THREAD

**Issue by naihe138** [facebook/react-native#12720]
when i open Movies.xcodeproj 

<img width="614" alt="123" src="https://cloud.githubusercontent.com/assets/12893716/23586631/f2403b4c-01d3-11e7-9783-b20b72196322.png">

**Comment by AlanFoster** [comment]
Seems to be related to https://github.com/facebook/react-native/issues/12080 and https://github.com/facebook/react-native/issues/7308

What version of xcode are you running currently, is it still present on the latest version? :)

**Comment by naihe138** [comment]
Xcode 7.3.1
Build version 7D1014

**Comment by naihe138** [comment]
@ericvicenti  #12080 and #7308 can`t solve this

**Comment by ericvicenti** [comment]
This "Movies" app is super old and we may want to simply remove it

**Comment by miuel** [comment]
hey I have the same error, did you find the solution ?
same Xcode 7.3.1
Build version 7D1014
@eremzeit what do you mean when you said "Movie" ?
