### ISSUE TITLE
Getting issue in scrollView scrollTo

### ISSUE THREAD

**Issue by krishbhattacharyya** [facebook/react-native#12739]
### Description

I am using scrollView when fetching data & changing scrollView position with "scrollView.scrollTo". I am getting error like bellow (Sometimes): ( In IOS, it is working )

com.facebook.react.common.JavascriptException: undefined is not an object (evaluating 'e.refs.scrollView.scrollTo'), stack:
value@605:5795
<unknown>@605:6752
..............
............

### Reproduction

```
var self = this;
Api.post(url, data_post, function(response) {
      if(response) {
        // my code updating the scrollView
        ............ 
	self.refs.scrollViewEdit.scrollTo({y: 0});
      }
      self.setState({animating: false });
    });
}

<ScrollView ref='scrollViewEdit'></ScrollView>
```

### Additional Information

* React Native version: ["0.40.0"]
* Platform: [Android]
* Operating System: [Linux]

**Comment by janicduplessis** [comment]
This problem is probably that your component gets unmounted before the request finishes. You could add a check to make sure the ref still exists before calling scrollTo on it. Feel free to reopen if I am wrong.

**Comment by krishbhattacharyya** [comment]
@janicduplessis thanks. I will try this. I think this will solve my problem.

**Comment by susan-github** [comment]
Did you resolve this issue? @krishbhattacharyya
