### ISSUE TITLE
Navigator: undefined is not an object (evaluating sceneConfig.animationInterpolators)

### ISSUE THREAD

**Issue by SamakaCD** [facebook/react-native#12742]
During fast pushing screens to a Navigator with sceneConfig "PushFromRight" alternating with "FadeAndroid" I get an error
`undefined is not an object (evaluating sceneConfig.animationInterpolators)`. Screenshot of error stack:
![screen shot 2017-03-06 at 3 02 28 pm](https://cloud.githubusercontent.com/assets/10329766/23611182/b7f28066-027e-11e7-82a7-4102d2ab48d3.png)

**Comment by hramos** [comment]
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Comment by mgrush** [comment]
@SamakaCD So How do you fix it ? I have met the same crash , crazying ~

**Comment by AnisDerbel** [comment]
same +1

**Comment by MathieuMailhos** [comment]
Same here

**Comment by mahshidy** [comment]
Is there an update to this issue? I am seeing the same crash. I popToTop() and that takes me to ComponentX. When in ComponentX I try to push another component, it gives me this error.

**Comment by hramos** [comment]
The issue was closed due to lack of information. Please open a new issue.

**Comment by rocwangv** [comment]
same here!!!
