### ISSUE TITLE
[WebView] Error loading page - Error Code: -1022

### ISSUE THREAD

**Issue by julesmoretti** [facebook/react-native#12757]
### Description

Used a <WebView> component to load a webpage for an iOS app. but upon propagating it I am getting:
<img width="373" alt="screen shot 2017-03-06 at 9 31 53 pm" src="https://cloud.githubusercontent.com/assets/744300/23643093/5b09cb80-02b4-11e7-941f-a13f816746cf.png">

### Reproduction

Here is the code for it:
```
import React, {
  Component,
} from 'react';

import {
  StyleSheet,
  View,
  WebView,
} from 'react-native';

export default class Map extends Component {
  componentDidMount() {
    console.log('Map:: componentDidMount');
  }

  render() {
    return (
      <View
        style={styles.container}
      >
        <WebView
          source={{uri: 'http://google.com'}}
          style={[{
            position: 'absolute',
            top: 0,
            left: 0,
            height: 500,
            width: 100
          }]}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  map: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
});
```

### Solution

Provide explanation on how to resolve this and update the readme to explain how to fix this issue through your doc.

### Additional Information

* React Native version: ^0.41.2
* Platform: iOS
* Operating System: Mac OS - 10.12.3

**Comment by petermikitsh** [comment]
@julesmoretti Have you tried using http**s**://google.com? Plain old http will throw errors, that's normal for iOS.

**Comment by julesmoretti** [comment]
@petermikitsh - https:// for google works. But the sites I am trying to get working does not have any https link to those. They use http:// So how can I make it work for http only addresses?

Do I have to do anything to the Xcode project?

Thank you for your help :)

**Comment by petermikitsh** [comment]
@julesmoretti You can carve out exceptions in your info.plist file (as described [here](http://stackoverflow.com/questions/30731785/how-do-i-load-an-http-url-with-app-transport-security-enabled-in-ios-9)), but it may impact your ability to ship those exception to the app store.

For cases of local development purposes, using http should be no issue once you create those exceptions.

**Comment by julesmoretti** [comment]
@petermikitsh - thank you for this info. That is a useful tip.

I am not able to see partially the content of the site I am trying to serve.

In my case the site I am trying to serve is: http://nhn.newhomesnavigator.com/

I am seeing some of the UI but not the google map. Are you aware if there are any more configurations or restrictions for me to include or be aware of for this implementation?

Or would it because I also need to include google maps url?

For your reference:

```
    <key>NSExceptionDomains</key>
    <dict>
      <key>localhost</key>
      <dict>
        <key>NSExceptionAllowsInsecureHTTPLoads</key>
        <true/>
      </dict>
      <key>newhomesnavigator.com</key>
      <dict>
        <key>NSIncludesSubdomains</key>
        <true/>
        <key>NSExceptionAllowsInsecureHTTPLoads</key>
        <true/>
        <key>NSExceptionRequiresForwardSecrecy</key>
        <true/>
      </dict>
    </dict>
```

**Comment by petermikitsh** [comment]
Instead of editing the Info.plist directly, you might have more success through the XCode interface. Select Info.plist in the left hand pane and then add something like this -- this would allow non-secure traffic on `localhost`.

<img width="480" alt="screen shot 2017-03-07 at 9 58 17 am" src="https://cloud.githubusercontent.com/assets/1571918/23670470/a1e76dba-031c-11e7-9cc0-8d1814b1ff40.png">

**Comment by julesmoretti** [comment]
@petermikitsh thank you :)

All working now

**Comment by LeonHwa** [comment]
@julesmoretti  I have the some error like yours. But it still go wrong After I add domain in info.plist. Can you show me your setting please?

**Comment by julesmoretti** [comment]
@LeonHwa 
```
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
		<key>NSExceptionDomains</key>
		<dict>
			<key>bootstrapcdn.com</key>
			<dict>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
				<key>NSExceptionRequiresForwardSecrecy</key>
				<true/>
				<key>NSIncludesSubdomains</key>
				<true/>
			</dict>
			<key>cloudflare.com</key>
			<dict>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
				<key>NSExceptionRequiresForwardSecrecy</key>
				<true/>
				<key>NSIncludesSubdomains</key>
				<true/>
			</dict>
			<key>facebook.com</key>
			<dict>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
				<key>NSExceptionRequiresForwardSecrecy</key>
				<true/>
				<key>NSIncludesSubdomains</key>
				<true/>
			</dict>
			<key>facebook.net</key>
			<dict>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
				<key>NSExceptionRequiresForwardSecrecy</key>
				<true/>
				<key>NSIncludesSubdomains</key>
				<true/>
			</dict>
			<key>google.com</key>
			<dict>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
				<key>NSExceptionRequiresForwardSecrecy</key>
				<true/>
				<key>NSIncludesSubdomains</key>
				<true/>
			</dict>
			<key>googleapis.com</key>
			<dict>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
				<key>NSExceptionRequiresForwardSecrecy</key>
				<true/>
				<key>NSIncludesSubdomains</key>
				<true/>
			</dict>
			<key>gstatic.net</key>
			<dict>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
				<key>NSExceptionRequiresForwardSecrecy</key>
				<true/>
				<key>NSIncludesSubdomains</key>
				<true/>
			</dict>
			<key>localhost</key>
			<dict>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
			</dict>
			<key>newhomesnavigator.com</key>
			<dict>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
				<key>NSExceptionRequiresForwardSecrecy</key>
				<true/>
				<key>NSIncludesSubdomains</key>
				<true/>
			</dict>
			<key>toptennewhomes.com</key>
			<dict>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
				<key>NSExceptionRequiresForwardSecrecy</key>
				<true/>
				<key>NSIncludesSubdomains</key>
				<true/>
			</dict>
		</dict>
	</dict>
```
