### ISSUE TITLE
[WebView] performance issues when compared to iOS Safari

### ISSUE THREAD

**Issue by petermikitsh** [facebook/react-native#12756]
### Description

It appears that website interactions in the `WebView` component is less performant than opening a website in iOS Safari. FWIW, the website I analyzed this is a React Web app.

### Reproduction

I made a [video recording](https://drive.google.com/open?id=0BwwMv-Qy_KO1NS04SzgxNHhlZWc). The first 15 seconds or so is my website in Safari. In the second half, I navigate my website in a WebView (built in release mode) and running on an iPhone 5s.

I enabled accessibility options so you can see taps in the recording. When comparing the delta between Safari and React Native, notice the amount of time between when a navigation button is clicked and it's icon and text are shown in the active state.

To make the comparison easier, I made some GIF's.

| React Native WebView     | iOS Safari           |
| ------------------------------------------------- |:-------------------------------------------------:|
| ![native](https://cloud.githubusercontent.com/assets/1571918/23642695/64118e00-02b1-11e7-9848-2caa312ff61e.gif)     | ![safari](https://cloud.githubusercontent.com/assets/1571918/23642696/6549d142-02b1-11e7-83f5-561110de5076.gif) |

### Solution

I'm not certain to the origin of this issue, so unfortunately I can't propose PR to amend the problem.

### Additional Information

* React Native version: v0.42.0
* Platform: iOS, possibly Android too but didn't confirm.
* Operating System: iOS 10.2.1

**Comment by petermikitsh** [comment]
I made a [rnplay example app](https://rnplay.org/apps/uE7gZg), but I don't believe it sufficiently demonstrates the issue due to the image compression and probable decreased frame rate. It's a very simple app, though.

**Comment by sunnylqm** [comment]
You can try a WKWebView implemetation for rn.
https://www.quora.com/Why-is-the-quality-of-UIWebView-less-than-Safari

**Comment by petermikitsh** [comment]
@sunnylqm Thanks for pointing me in the right direction. I was reading through #321 and came across this [particular comment](https://github.com/facebook/react-native/issues/321#issuecomment-86902269) that basically says WKWebView is incomplete. I'm curious if those concerns can still be substantiated now since that comment was from 2015. This [PR from October 2016](https://github.com/facebook/react-native/pull/10456) seems to suggest WKWebView isn't still at full feature parity. I'll give it a go anyways, since I'd want the perf boost. Looks like there is already a community solution for using WKWebView in RN: https://github.com/CRAlpha/react-native-wkwebview

Down the line, it would be fantastic to see RN opt for the more performant of the two, but if there are limitations, I could see why WebView uses UIWebView.

**Comment by petermikitsh** [comment]
Alright, I have been able to achieve an acceptable solution using `WKWebView`. Since the performance issues are a known limitation `UIWebView`, closing this.
