### ISSUE TITLE
Exception 'shadowView (for id xx) not found'

### ISSUE THREAD

**Issue by chiraggshah** [facebook/react-native#12768]
I am facing the following error when I try to debug the app on chrome. The app runs fine when I stop remote JS debugging.

RN version: 0.42.0

![image](https://cloud.githubusercontent.com/assets/6805530/23663657/47d094de-0379-11e7-85e1-eef8fd219784.png)

**Comment by hramos** [comment]
Can you troubleshoot a bit more and see if you can identify if there's a specific piece of code that introduced the red box?

Does this reproduce on a minimal React Native app, for example?

**Comment by chiraggshah** [comment]
@hramos : I am also getting the following warning on chrome
`Calling of `[-RCTUIManager setFrame:forView:]` which is deprecated.` Maybe its related?

The app was working fine before. I just introduced redux and some sample action.

**Comment by chiraggshah** [comment]
@hramos : I just reverted all my changes related to redux and I can confirm that this is happening because I just upgraded from 0.28 to 0.42. Any help would be appreciated. Thanks

**Comment by hramos** [comment]
Is there anything specific that triggers it?

**Comment by jacobcyl** [comment]
I got a related issue #12777

**Comment by chiraggshah** [comment]
Debugged a bit more. Downgraded to 0.41.0 and I can confirm that its working correctly. So maybe something has changed in 0.42.0 which is causing this issue.

**Comment by jkolyer** [comment]
I have same problem.  For me it's coming from the RCTAnimation.  

I downgraded to 0.41.0 as suggested, then got this compile error which may be useful information:  "RCTViewPropertyMapper.h file not found" in the RCTPropsAnimatedNode class.  

After clean build the downgrade is confirmed to fix my problem as well.

**Comment by lucasbento** [comment]
I'm having this same issue, it started when I added `<Modal />` to the code.

**Comment by hannigand** [comment]
I can confirm I also received this error when adding `<Modal />` running on React Native `0.42.0` on iOS Simulator. Downgrading to `0.41.0` fixed the error.

Turning off `Debug JS Remotely` also works but isn't a workaround if you intend to debug the contents within the `<Modal />`

**Comment by damathryx** [comment]
Any other solution aside from downgrading?

**Comment by hannigand** [comment]
@damathryx a fix was issued in version `0.42.2`, simply upgrading should now remove the problem.

**Comment by Stefflan00** [comment]
thanks @hannigand you just saved my Weekend :) 
Turning of the remote debug worked fine. I am on 0.42.0.  I am curious why this debug is affecting my Modal. Any hints?

**Comment by hramos** [comment]
Closing as this has been fixed in 0.42.2.

**Comment by lukecwilliams** [comment]
FYI - similar issue and fix in https://github.com/facebook/react-native/issues/9676, related to incorrect comma style in render() method.
