### ISSUE TITLE
A warning from Apple

### ISSUE THREAD

**Issue by XHTeng** [facebook/react-native#12778]
I received a warning from Apple this morning , how to solve it :

Dear Developer,

Your app, extension, and/or linked framework appears to contain code designed explicitly with the capability to change your app’s behavior or functionality after App Review approval, which is not in compliance with section 3.3.2 of the Apple Developer Program License Agreement and App Store Review Guideline 2.5.2. This code, combined with a remote resource, can facilitate significant changes to your app’s behavior compared to when it was initially reviewed for the App Store. While you may not be using this functionality currently, it has the potential to load private frameworks, private methods, and enable future feature changes. 

This includes any code which passes arbitrary parameters to dynamic methods such as dlopen(), dlsym(), respondsToSelector:, performSelector:, method_exchangeImplementations(), and running remote scripts in order to change app behavior or call SPI, based on the contents of the downloaded script. Even if the remote resource is not intentionally malicious, it could easily be hijacked via a Man In The Middle (MiTM) attack, which can pose a serious security vulnerability to users of your app.

Please perform an in-depth review of your app and remove any code, frameworks, or SDKs that fall in line with the functionality described above before submitting the next update for your app for review.

Best regards,

**Comment by csbzhixing** [comment]
Did anyone receive the warning e-mail?

**Comment by KnightJoker** [comment]
+1 
waiting solution

**Comment by bingozhang** [comment]
FK apple

**Comment by watermelon520** [comment]
I'don't care.

**Comment by c9n** [comment]
🚶

**Comment by tdzl2003** [comment]
This includes any code which passes arbitrary parameters to dynamic methods such as dlopen(), dlsym(), respondsToSelector:, performSelector:, method_exchangeImplementations(), and running remote scripts 

Imported any framework for crash collections?

**Comment by fengwanqing** [comment]
https://github.com/bang590/JSPatch/issues/746#issuecomment-284928533

**Comment by dulingkang** [comment]
Swift 大法好，不需要热更新。。。 @apple

**Comment by coofee** [comment]
+1

**Comment by Arthraim** [comment]
Only saw a lot of Chinese apps got this warning so far. Is there any app that's outside of China got this too?

**Comment by wenzhaot** [comment]
bad news

**Comment by fengwanqing** [comment]
Swift是不需要热更新还是不能热更新呢？

**Comment by zliuqing** [comment]
+10086

**Comment by shaojiankui** [comment]
前排

**Comment by myiosemail** [comment]
Do you have an impact？

**Comment by UniverseJun** [comment]
前排

**Comment by CQXfly** [comment]
let's rewrite our apps by swift

**Comment by Sky891028** [comment]
mark~

**Comment by TrustTheBoy** [comment]
Weex, RN ionic, jspatch cocos received mail warning to the QQ group: 416952029 talk about ah
weex，RN ionic ，jspatch cocos收到邮箱警告的来QQ群：416952029说说啊

**Comment by Weibin-Huang** [comment]
mark~

**Comment by shixinzhang** [comment]
刚开始学 RN，请问老司机们，还要继续吗？

**Comment by fighting300** [comment]
Is this triggered from rn？

**Comment by xiangkaiy** [comment]
前排～

**Comment by mrzsun** [comment]
swift 也可以热更新  只要全部fuction都添加dynamic属性 并且不使用原生struct和enum

**Comment by littlewhitetwo** [comment]
前排

**Comment by wenzhaot** [comment]
swift开发者，强势围观 557165621

**Comment by mozhenhau** [comment]
All receive the warning mail  were from China ?

**Comment by wchyan** [comment]
Do you only have RN in your app? or also have JSPatch in your app?

**Comment by Rayzworld** [comment]
感觉苹果搞我

**Comment by monycn** [comment]
前排留名

**Comment by sleepywk** [comment]
man, this is serious!

**Comment by myseven** [comment]
waiting, mark..

**Comment by desmond1121** [comment]
Please feel free to use built-in bundle. If you really care about hot reload, RN may not your first choice.

**Comment by TakWolf** [comment]
mark

**Comment by qxqxqxqx** [comment]
mark

**Comment by JayJJ** [comment]
抢个沙发，留个名号

**Comment by xiongcaichang** [comment]
你们收到警告的是不是同时使用了 JSPatch  或者 BugTags

**Comment by gin7758258** [comment]
Do you only have RN in your app? or also have JSPatch in your app?
@XHTeng

**Comment by talisk** [comment]
There's many reasons cause developers receive the warning. But I'm not sure whether the app written in ReactNative without code-push ability under the influence.

**Comment by myiosemail** [comment]
@XHTeng  Do you have an impact？

**Comment by raopc** [comment]
好方

**Comment by coolicer** [comment]
刚要学react native，不要这样玩。

**Comment by ColorfulCat** [comment]
不是说JSpatch的问题么？

**Comment by ALVIN-YANG** [comment]
I use PHP

**Comment by jiangqqlmj** [comment]
mark   哈哈~  有点小蛋疼啊

**Comment by vitock** [comment]
大家就别为淘宝 微信担心了,人家一来有人脉,能讨价还价,二来人多,换技术方案,不说分分钟,起码来说不费力气
中国是市场主导,不是技术主导,马化腾都说过这话,技术为市场服务,
技术选型的人要背锅,这么多业务依赖于这么一个 冷门小技巧,实在不是正途.

**Comment by githubwing** [comment]
iOS 开发者春天来了

**Comment by huyabin** [comment]
我学了半个月RN估计白学了

**Comment by lzm470445107** [comment]
库克是不是看到了好多做原生的要失业了，才出此妙计啊

**Comment by zichenJack** [comment]
mark

**Comment by 444306979** [comment]
单纯用RN的也收到苹果的邮件了？

**Comment by Lvcary** [comment]
前排

**Comment by aiyidu** [comment]
m

**Comment by xinlidexiaoman** [comment]
到底有没有人确定一下  只用了RN开发的 是不是也收到了警告邮件  
貌似现在说的都说JSPatch引起的

**Comment by lokialone** [comment]
mark

**Comment by chevins** [comment]
In my view, it's none of RN's business, you can still use RN to develop if you don‘t use the hot load.

**Comment by xujinyang** [comment]
这样得把内置的WebView控件也干掉才行，以后H5也不要用了，让我们回到原始社会

**Comment by Lvcary** [comment]
一朝回到解放前的意思？？

**Comment by JoySeeDog** [comment]
RN will over？

**Comment by naivehhr** [comment]
mark...

**Comment by iStarEternal** [comment]
求解怎么破？Chinese come here 🇨🇳

**Comment by tyrad** [comment]
围观

**Comment by fengzhihao123** [comment]
mark

**Comment by tdzl2003** [comment]
Maybe RN should remove usage of these methods: dlopen(), dlsym(), respondsToSelector:, performSelector:, method_exchangeImplementations()

**Comment by anchoriter** [comment]
mark

**Comment by wskeee** [comment]
mark

**Comment by njafei** [comment]
shit,just learned react-native ....

**Comment by FgoPan** [comment]
mark

**Comment by ohsc** [comment]
+1

**Comment by 1124953475** [comment]
心疼自己、正准备看。。

**Comment by sanxxwu** [comment]
what？

**Comment by dimsky** [comment]
振奋人心

**Comment by tonyjiafan** [comment]
来都来了

**Comment by 91hong** [comment]
收到邮件了，一脸懵逼中

**Comment by ibrucekong** [comment]
火 before 留 name

**Comment by wskeee** [comment]
RN官方怎么说啊！

**Comment by tianxiewuhua** [comment]
mark

**Comment by Sumrocks** [comment]
mark

**Comment by fighting300** [comment]
收到邮件的说下自己用了什么库吧  比如 RN +  JSPatch  或者其他等

**Comment by wglloui** [comment]
💊

**Comment by ymmuse** [comment]
I have words that MMP don't know shall we talk ...

**Comment by GeniusBrother** [comment]
RN有没事 去掉热更新 照样有用

**Comment by lixurmy** [comment]
mark

**Comment by tdzl2003** [comment]
I overviewed all code of react native, the only risk which contain "arbitrary parameters to dynamic methods" is:

[RCTUtils.m](https://github.com/facebook/react-native/blob/302d42da7f5a4565a4298bb5e54b6a3386e29339/React/Base/RCTUtils.m) Line 337 & 354

**Comment by chenjinya** [comment]
It' time to create a new mobile system.

**Comment by zzgo** [comment]
it's time to use native

**Comment by Rookie-liu** [comment]
apple nubi

**Comment by spricity** [comment]
mark

**Comment by hardyZhi** [comment]
mark

**Comment by wuyunqiang** [comment]
to learn android is ok

**Comment by geteng** [comment]
mark～

**Comment by flyweights** [comment]
23333

**Comment by det101** [comment]
mark

**Comment by totzcc** [comment]
有什么检测工具吗

**Comment by ide** [comment]
From the data points I've heard: the developers who received this email were using a patching framework called Rollout.io. So please double-check to see whether you app is using a framework like that. Reading the message carefully, it's not describing React Native nor what React Native does.

Second, make sure that you aren't using React Native modules that call methods like `dlopen()` and other method calls like the ones listed in the message.

Last, please use the Subscribe button on GitHub if you wish to follow the conversation but don't have something meaningful to contribute. I'd prefer to leave it open but if the discussion isn't productive we'll have to close this issue and perhaps lock it.

**Comment by strongwray** [comment]
today It's a big day...........

**Comment by magicdawn** [comment]
💊

**Comment by hesshzy** [comment]
23333333333

**Comment by smk524198002** [comment]
啊 席巴~

**Comment by setiproz** [comment]
火钳刘明

**Comment by sevenOnClass** [comment]
刚入rn坑

**Comment by kenvies** [comment]
阿西吧～～～～回家务农的跟我走

**Comment by zhaiyuyong** [comment]
不要玩什么react-native 快加入饿了么大数据team玩spark

**Comment by helengray** [comment]
所以还是android生态好

**Comment by isno** [comment]
纯RN开发，上架会有影响么，开发了三个月的RN 外包项目，周六就要上架收费了， 不会审核被拒吧？

**Comment by aoldcat** [comment]
mark

**Comment by myiosemail** [comment]
gg?

**Comment by iseeicando** [comment]
RN + JSPatch received mail

**Comment by love999262** [comment]
+10086

**Comment by tdzl2003** [comment]
To Chinese friend:
Please do not send spam message on this conversation. I'll translate any response from RN Contributers into chinese.

中国朋友们：
请不要在本贴发表无意义的讨论，我将翻译一些重要的回复入中文。

ide的回复：
到目前为止我听说的事情：许多开发者收到这个邮件，是因为使用了一个叫Rollout.js(译者补充：国内更多的是JSPatch，以及一些直接或间接依赖了JSPatch的第三方库如bugtags、个推等，请关注对应库的更新)的框架，所以请再次检查你的app有没有使用类似的框架。仔细阅读邮件中的描述，里面并不涉及RN或者RN所做的事情。

另外，你也需要检查你没有使用某些第三方的RN模块，如果它们调用了dlopen或者类似的邮件中描述的动态函数也可能会被苹果警告或禁止。

最后，请使用Subscribe按钮来订阅这个会话，如果你没有什么对本会话有意义的事情想要发表。我想让这个会话保持开启但如果讨论过于无意义我可能会关闭甚至锁定这个issue。

**Comment by tdzl2003** [comment]
I searched in all code of react native, the only risk which may contain "arbitrary parameters to dynamic methods" is:

[RCTUtils.m](https://github.com/facebook/react-native/blob/302d42da7f5a4565a4298bb5e54b6a3386e29339/React/Base/RCTUtils.m) Line 337 & 354

@ide any idea for this? Could we remove or change these code?

**Comment by Jiasm** [comment]
waiting for news

**Comment by ericoda** [comment]
mark

**Comment by yxuecheng** [comment]
well done

**Comment by Mrlyjoutlook** [comment]
soft

**Comment by WarnerWang** [comment]
坐等后续事态发展

**Comment by ide** [comment]
@tdzl2003 Thanks for providing the file and line numbers -- those functions (`RCTSwapClassMethods` and `RCTSwapInstanceMethods`) are used only internally within React Native and are not exposed to JavaScript, for example. The way React Native uses them for swizzling is the same as any other "regular" iOS app would. It's very normal, accepted, and not something to be concerned about.

**Comment by UKfire** [comment]
torn inside =.=

**Comment by grabbou** [comment]
3.3.2 of Apple Developer Program License:

> An Application may not download or install executable code. Interpreted
code may only be used in an Application if all scripts, code and interpreters are
packaged in the Application and not downloaded. The only exception to the
foregoing is scripts and code downloaded and run by Apple's built-in WebKit
framework or JavascriptCore, provided that such scripts and code do not change
the primary purpose of the Application by providing features or functionality that are
inconsistent with the intended and advertised purpose of the Application as
submitted to the App Store.

explicitly mentions that:

> An Application may not download or install executable code

React Native does none of these. And so, using React Native doesn't expose you to the aforementioned issue.

However, with React Native, you can do so called OTA updates, by using services like Code Push. This is explicitly allowed later in the same `3.3.2`:
> The only exception to the foregoing is scripts and code downloaded and run by Apple's built-in WebKit framework or JavascriptCore

And so, this has nothing to do with React Native. I believe everyone should follow up on this issue with Apple and sort out what's exactly causing the warning.

**Comment by luncang** [comment]
苹果爸爸要抛弃rn了吗，重回原生时代的节奏？

**Comment by Bofearless** [comment]
RN will over ？

**Comment by tdzl2003** [comment]
@ide I know they are safe, but maybe apple's automatic check system may still consider a application use both script downloading AND arbitrary parameters to dynamic methods as a risk?

**Comment by cuitianze** [comment]
Are u kidding me

**Comment by LiangyongFShen** [comment]
前几天用JSPatch 火速解决一个问题，今天就用不了 mark ~

**Comment by brunolemos** [comment]
React Native apps are finentdon't worry about it.

The apps receiveing this message are using a lib called Rollout.io, which updates NATIVE code (swift/objc). Apple is worried about that.

Libraries like Code Push only updates JavaScript code and were not affected, as least not yet.

![](http://ryanjsalva.com/assets/2016-05-01-agreement.jpg)

**Comment by difoi** [comment]
其实最大的问题,这个技术是苹果不可控的... 所以要干掉了.   好技术,被有些人给用坏了..

**Comment by qhd** [comment]
JSPatch、RN、Weex、收到邮件警告的来QQ群：92362912 说说

**Comment by catcups** [comment]
I have words that MMP don't know shall we talk ...

**Comment by kkmike999** [comment]
国产安卓发来慰问。

**Comment by TrustTheBoy** [comment]
weex，RN ionic ，jspatch cocos收到邮箱警告的来QQ群：416952029说说啊

**Comment by xiyouMc** [comment]
Wow...So far for Chinese Apps

**Comment by ronniechen888** [comment]
Wow,so amazing!

**Comment by tdzl2003** [comment]
grabbou的回复：

苹果开发者协议3.3.2节:

一个应用程序不应该下载或安装任何可执行代码。解释执行的代码可以在应用内使用，如果所有的脚本、代码、和解释器都被打包在应用内而没有被下载。前述内容的唯一的例外在于下载的脚本和代码使用了Apple内置的WebKit框架或JavascriptCore，并且对应的脚本或代码并没有改变这个应用提供功能和特性的主要目的，与提交到AppStore的版本以及相应的宣传描述相符。

其中重要的地方：

一个应用程序不应该下载或安装任何可执行代码
React Native没有做这件事情。所以React Native不会让你受前述条款的影响。

另一方面，使用React Native，你还可能会使用叫做OTA更新的方式（俗称热更新），类似Code Push或中文网提供此热更新服务。这同样是被3.3.2章节的后续内容允许的：

前述内容的唯一的例外在于下载的脚本和代码使用了Apple内置的WebKit框架或JavascriptCore

所以这事情和React Native并无卵关系。我觉得收到邮件的人应该关注和苹果的交流，再次检查是什么导致了这个警告。

**Comment by TrustTheBoy** [comment]
weex，RN ionic ，jspatch cocos收到邮箱警告的来QQ群：416952029说说啊
grabbou的回复：
苹果开发者协议3.3.2节:

一个应用程序不应该下载或安装任何可执行代码。解释执行的代码可以在应用内使用，如果所有的脚本、代码、和解释器都被打包在应用内而没有被下载。前述内容的唯一的例外在于下载的脚本和代码使用了Apple内置的WebKit框架或JavascriptCore，并且对应的脚本或代码并没有改变这个应用提供功能和特性的主要目的，与提交到AppStore的版本以及相应的宣传描述相符。

其中重要的地方：

一个应用程序不应该下载或安装任何可执行代码
React Native没有做这件事情。所以React Native不会让你受前述条款的影响。

另一方面，使用React Native，你还可能会使用叫做OTA更新的方式（俗称热更新），类似Code Push或中文网提供此热更新服务。这同样是被3.3.2章节的后续内容允许的：

前述内容的唯一的例外在于下载的脚本和代码使用了Apple内置的WebKit框架或JavascriptCore

所以这事情和React Native并无卵关系。我觉得收到邮件的人应该关注和苹果的交流，再次检查是什么导致了这个警告。

**Comment by LiangyongFShen** [comment]
framework like thie "WebViewJavascriptBridge" will be warning?

**Comment by ronniechen888** [comment]
苹果站在用户体验角度来做这件事，我觉得无可厚非，因为热更新泛滥后，苹果实在无暇监管！

**Comment by kaelzhang** [comment]
棒棒的

**Comment by fengchuantao** [comment]
hao duo zhong guo developer。 HA HA

**Comment by chevins** [comment]
Good news! My app just passed the review 5 minutes ago. And it contains the 'code-push'. BTW, I don‘t use JSPatch or Bugtags.

**Comment by tdzl2003** [comment]
@LiangyongFShen I think most of them are safe.

**Comment by axemclion** [comment]
Anyone here using CodePush and had issues with Review ? I am the CodePush PM, so would like to know more if you have run into issues.

**Comment by wupengFEX** [comment]
Use pwa!

**Comment by JunyiXie** [comment]
真好 。听说iOS开发没人要了？？？

**Comment by GintokiS** [comment]
我记得在JSPatch出来之前有种热修复的方式是采用lua脚本的，lua这个在封禁JSPatch之后也不能用了？

**Comment by chengaojian** [comment]
这算不上坏消息，最起码苹果没有明确不让使用React Native开发程序

**Comment by chengaojian** [comment]
That's not really bad news, at the very least, apple did not clear not to use the React Native development program

**Comment by zjklyl931081** [comment]
iOS春天来吧，大中国的iOS的已经一片荒凉了，赶紧来点燃这把火

**Comment by sugarye** [comment]
OMG~

**Comment by pinguo-gaoshan** [comment]
@axemclion @tdzl2003 CoduRush is also change the App's behavior out of Apple's review.

**Comment by axemclion** [comment]
@pinguo-gaoshan While CodePush may be misused to change app's behavior, it still cannot load private frameworks or expose private methods other than the ones ReactNative already exposes. Not all the clauses in that rejection apply to CodePush. 
Additionally, I would suggest that individual apps should NOT change their behavior using CodePush.

**Comment by pinguo-gaoshan** [comment]
@axemclion I agree, but Apple can't distinguish the way developers using CodeRush, so it's bad they all disable these functions, and do not allow new version submit to app store.

**Comment by tangkunyin** [comment]
并无暖关系就好，赞RN

**Comment by brunolemos** [comment]
@pinguo-gaoshan it's a possibility that Apple follow this path in the future, but right now apparently code push continues to be accepted.

**Comment by axemclion** [comment]
@pinguo-gaoshan Note that the rejection explicitly calls out methods that they are concerned about. React Native does not dynamically inject into any of those methods.

**Comment by xujihui1985** [comment]
@tdzl2003 I thought most developer from China understand plain English, no need to translate, it's annoying

**Comment by nihgwu** [comment]
@axemclion I published a brand new app written in React Native with Code Push yesterday without any rejection,  and I've made a new version which is still waiting for review, I haven't received any warning email from Apple

**Comment by axemclion** [comment]
@nihgwu Awesome - thanks for that input.

**Comment by NSLogxiaoyu3** [comment]
“translate ... into Chinese” 翻译成“翻译...入中文”
这个是来搞笑的吗

**Comment by fengzhihao123** [comment]
so,What is the conclusion?

**Comment by qq530402037** [comment]
因为微软搞了个visual studio2017，自带基于RN的IOS开发功能，鉴于微软最近的开源力度，可能出现在windows 机上就能搞iOS开发了，所以苹果发飙了。

**Comment by yourscott** [comment]
What about remote html files loaded by Webview? Is that allowed or not?

**Comment by qq530402037** [comment]
最近一段时间小心点，避免使用脚本热更新，避免使用RN，等风头过了再说。
本身在应用/游戏里用lua或JS脚本是没问题的，热更新是不支持的。但是之前做游戏的糕点小版本热更新，苹果睁一眼闭一眼
苹果这次搞这个估计是冲着微软去的。

**Comment by vjeux** [comment]
FYI, given the high visibility and uncertainty around this issue, we are actively using the moderation tools in order for it to remain useful. Please try to only reply if you have concrete information around the subject. Thanks!

**Comment by lechenghhh** [comment]
What happened? React Native can not be used after the development of iOS?

**Comment by akixie** [comment]
m

**Comment by huhuanming** [comment]
It seems that only chinese developers received this warning email.

Do other parts of the world have the same email?

**Comment by SylviaRu** [comment]
mark.

**Comment by pvenkatakrishnan** [comment]
Ok i noticed on the guidelines, they removed the word `javascriptcore` alone in 3.3.2 
Does it mean downloading dynamic react-native bundles is a no no?
https://developer.apple.com/programs/terms/ios/standard/ios_program_standard_agreement_20140909.pdf

**Comment by chandu0101** [comment]
>they removed the word javascriptcore alone in 3.3.2

so its the end of OTA Updates  on iOS ? looks like they got hurt by this https://medium.com/the-react-native-log/comparing-the-performance-between-native-ios-swift-and-react-native-7b5490d363e2#.g2c6ykd8e :D , and they did right before react-conf , its all political! :(

**Comment by Pikaurd** [comment]
@pvenkatakrishnan Your link was published at 2014 
http://adcdownload.apple.com/Documentation/License_Agreements__Apple_Developer_Program/Apple_Developer_Program_License_Agreement_20160921.pdf 
this one has the word `JavascriptCore`

**Comment by ide** [comment]
@huhuanming I believe so, some developers using a library called Rollout received an email. It could be that many Chinese apps use JSPatch

@pvenkatakrishnan As @Pikaurd says, that is a very old agreement. The latest one for 2017 (http://adcdownload.apple.com/Documentation/License_Agreements__Apple_Developer_Program/Apple_Developer_Program_License_Agreement_20170227.pdf) has the same language and mentions JavascriptCore.

**Comment by FurshawFu** [comment]
thank you guys ,very much !

**Comment by pvenkatakrishnan** [comment]
yay thanks @ide and @Pikaurd Phew!! I knew i saw javascriptcore few months ago :)

**Comment by lixiaoning506** [comment]
very good!No problem

**Comment by droidwolf** [comment]
great!maintenance of good order to healthy development!

**Comment by bengirl** [comment]
哈哈，前端的🇨🇳表示无压力，不屌你ios的

**Comment by wsmeichao** [comment]
:cn::cn::cn::cn:还好我是学前端的，吓得我赶紧喝了一口82年的可乐压压惊

**Comment by ramoslin02** [comment]
It seems that the hotpack does not work anymore.

**Comment by pallyoung** [comment]
wait for next step

**Comment by Ilovemycode** [comment]
Discrimination, this is pure discrimination

**Comment by cdll** [comment]
how about app built by cordova?

**Comment by ide** [comment]
From reading the message from Apple and the data points we've observed, **this warning is not about React Native.**

### On the technical concern of dynamically executing Objective-C described in Apple's email:

> Apple's message reads to me that they're concerned about libraries like Rollout and JSPatch, which expose uncontrolled and direct access to native APIs (including private APIs) or enable dynamic loading of native code. Rollout and JSPatch are the only two libraries I've heard to be correlated with the warning.
>
> React Native is different from those libraries because it doesn't expose uncontrolled access to native APIs at runtime. Instead, the developer writes native modules that define some functions the app can call from JavaScript, like setting a timer or playing a sound. This is the same strategy that "hybrid" apps that use a UIWebView/WKWebView have been using for many years. From a technical perspective, React Native is basically a hybrid app except that it calls into more UI APIs.
>
> Technically it is possible for a WebView app or a React Native app also to contain code that exposes uncontrolled access to native APIs. This could happen unintentionally; someone using React Native might also use Rollout. But this isn't something specific to or systemic about React Native nor WebViews anyway

### On the strategy of calling native code from JavaScript:

> Apple has been fine with WebViews in apps since the beginning of the App Store, including WebViews that make calls to native code, like in the Quip app. WKWebView even has APIs for native and web code to communicate. It's OK for a WebView to call out to your native code that saves data to disk, registers for push notifications, plays a sound, and so on.
>
> React Native is very much like a WebView except it calls out to one more native API (UIKit) for views and animations instead of using HTML.
>
> What neither WebViews nor React Native do is expose the ability to dynamically call any native method at runtime. You write regular Objective-C methods that are statically analyzed by Xcode and Apple and it's no easier to call unauthorized, private APIs.

### Data points

The developers who received this email were using **Rollout** or **JSPatch** in their apps. People who are using only React Native or libraries/frameworks like CodePush and Expo are not affected and are continuing to have their apps accepted by the App Store review.

### Recommendations

If you're writing a React Native or WebView app, be sure not to expose dynamic, uncontrolled access to native APIs and you should be OK. There was one third-party RN module that did this and the maintainers have taken it down. And in accordance with the iOS developer terms, make sure your updates don't change the primary purpose of your app and that the changes are consistent with the intended and advertised purpose of your app.

- James

**Comment by treesea2014** [comment]
what's happend?  I 'm new of learnning RN~,  shall  I give it up?

**Comment by havthgem** [comment]
@treesea2014 Do you have a look carefully at what everyone said?
