### ISSUE TITLE
warning: Calling of `[-RCTUIManager setFrame:forView:]` which is deprecated

### ISSUE THREAD

**Issue by jacobcyl** [facebook/react-native#12777]
### Description

After I upgrade RN from 0.38 to 0.42.0 I get this waring: 
```javascript
Calling of `[-RCTUIManager setFrame:forView:]` which is deprecated
```

### Reproduction

Just after I upgrade RN, I got this warning. In remote debug mode. I only test in iOS platform.

### Solution

[empty here]

### Additional Information

* React Native version: 0.42.0
* Platform:  IOS
* Operating System: MacOS - Xcode 8.2.1

**Comment by Kennytian** [comment]
same issus here

**Comment by mrsai** [comment]
yes , same warning here .

**Comment by chiraggshah** [comment]
@jacobcyl : I guess something was changed recently in v0.42.0. Can you confirm that this is not occuring on v0.41.0

**Comment by hramos** [comment]
Which Xcode version are you using?

**Comment by bennygenel** [comment]
@hramos I'm getting the same error with react-native v0.42 and XCode 8.2.1

**Comment by mrsai** [comment]
@hramos as bennygenel

**Comment by froatsnook** [comment]
Phew, I'm glad I'm not the only one -- I thought I broke something!  For me, this started occurring after upgrading to 0.42, and Modals not working only happens when remote debugging is enabled.  I also start to get strange crashes after trying to open Modals.

1. Try to open modal.  Nothing happens.
2. Try to open other modal.  Then:

![screen shot 2017-03-09 at 09 15 09](https://cloud.githubusercontent.com/assets/10405574/23741516/14052756-04a9-11e7-9d35-586015a57b7d.png)

1. Try to open modal.  Nothing happens.
2. Navigate to other tab.  Then:

![screen shot 2017-03-09 at 09 15 32](https://cloud.githubusercontent.com/assets/10405574/23741515/1403773a-04a9-11e7-93b8-931cd508c0a2.png)

**Comment by liqueflies** [comment]
Find same issue, maybe can be a related to remote js debugger, stop remote debugging Modal is working for me.

**Comment by Antonhansel** [comment]
I can confirm that when the debugger is closed, the Modal is working fine

**Comment by codingwaysarg** [comment]
Same issue here, SplashScreen hide stop working when remote js debugger is open.

**Comment by ardalann** [comment]
Same issue. I upgraded from 0.41.2 to 0.42.0 and now the app runs fine when remote debugger is disabled. When it's enabled I get this warning: `Calling of '[-RCTUIManager setFrame:forView:]' which is deprecated.`

**Comment by hlshang** [comment]
Found same Issue

**Comment by hramos** [comment]
GitHub added reactions recently - if you are running into the same issue but have no additional data to provide, you can simply add a reaction to the original post at the top. One advantage of this is that it allows us to filter by issues with a large number of reactions, making it easier to identify issues that people care about the most. Thanks!

**Comment by plusmancn** [comment]
With the same problem when i upgraged rn to 0.42

**Comment by newappco** [comment]
same issue, blank screen after upgrading to 0.42

**Comment by Etheryte** [comment]
Quick git-blame-fu shows the warning was introduced in https://github.com/facebook/react-native/commit/f33f84e75f1957f381e34bc99a902b9c324db6fa by @shergin with the following description:

> #### Deprecating/removing `setFrame`, `setLeftTop`, and co.
> Summary:
> Motivation:
>  * `RCTShadowView`'s `frame` property actually represents computed layout of the view. We must not use it as a setter for yoga node styles;
>  * Using `frame` and `setLeftTop` in existing way actually works only for view with absolute positioning, so it is super rare and special case;
>  * Internally, setting `frame` only make sense to `RootView`, and in that case there we always must not change `origin` we are introducing `setSize` method.
> 
> Changes:
>  * `[-RCTShadowView setFrame:]` was removed, `frame` property is readonly now;
>  * `[-RCTShadowView setLeftTop:]` was removed; no replacement provided;
>  * `[-RCTShadowView size]` read-write property was added;
>  * `[-RCTUIManager setFrame:forView:]` was deprecated, use (just introduced) `setSize:forView:` instead;
>  * `[-RCTUIManager setSize:forView:]` was added.
> 
> If you are still need some of removed methods, you are probably doing something wrong. Consider using `setIntrinsicContentSize`-family methods,
> `setSize`-family methods, or (in the worst case) accessing `yogaNode` directly.

Seems like some internal classes are still dependant on `[-RCTUIManager setFrame:forView:]`?

**Comment by shergin** [comment]
@Etheryte Thank you!

Nope, the internal classes do not depend on `setFrame:forView:`, the proof: https://github.com/facebook/react-native/search?utf8=%E2%9C%93&q=setFrame%3A.

Most likely, one of external native libraries still depends on `[-RCTUIManager setFrame:forView:]`. The fix should be pretty trivial though (see current deprecated implementation).

**Comment by windhost** [comment]
`[-RCTUIManager setFrame:forView:]` which is deprecated."
I changed the code,remind by Xcode to
`[self setSize:frame.size forView:view];`

**Comment by binchik** [comment]
@shergin I've found `[-RCTUIManager setFrame:forView:]` in RCTModalHostView.m

https://github.com/facebook/react-native/blob/v0.42.0/React/Views/RCTModalHostView.m

**Comment by Maftalion** [comment]
For those whose modals aren't working in debugger, check this out: [https://github.com/facebook/react-native/pull/12744](url) 

If you want to make the changes yourself, go to your Libraries/ReactNative/YellowBox.js file in your node_modules and add this line `const elevation = Platform.OS === 'android' ? Number.MAX_SAFE_INTEGER : undefined;`, then change the 3 `elevation: Number.MAX_VALUE` in your styleSheet to `elevation: elevation`.

**Comment by shergin** [comment]
@binchik Oh, my fault. Branch cut splits my changes across versions. 😞  We have to cherry-pick https://github.com/facebook/react-native/commit/233015c93ee6f986cf1267f143fdfadbf9c6831d for 0.42.
Sorry about that. 😿

**Comment by hramos** [comment]
I've cherry picked 233015c93ee6f986cf1267f143fdfadbf9c6831d into `0.42-stable`. We may still need to deploy a new package to npm. cc @ericnakagawa @grabbou

**Comment by grabbou** [comment]
I'll investigate that as soon as I get home after Conf

**Comment by grabbou** [comment]
Version bumped, new package is getting deployed. I am going to close that issue, please update to 0.42.2 when it gets released to npm (next hour).

Apologies for incovnience caused.

**Comment by awitherow** [comment]
@jacobcyl can you please provide a solution to your template?
