### ISSUE TITLE
`export from import` syntax in React Native

### ISSUE THREAD

**Issue by xareelee** [facebook/react-native#12785]
For some reasons, I need to `export` an object (including function, components, etc.) from another `import`.

I find [a syntax to achieve this](https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Statements/export):

```js
// export * from …;
export * from './LoginPage';
```

but this doesn't work in React Native.

How do I do to use this syntax in React Native?

**Comment by janicduplessis** [comment]
This syntax isn't standard (yet), you have to add an extra babel plugin to support it.

You should install the export extensions plugin (`npm install --save-dev babel-plugin-transform-export-extensions`) and create a `.babelrc` file if you have not one already.
```
{
  "presets": ["react-native"],
  "plugins" ["transform-export-extensions"]
}
```
Then restart the react native packager and clear it's cache
```
npm start -- --reset-cache
```

**Comment by janicduplessis** [comment]
You could also try https://github.com/skevy/babel-preset-react-native-stage-0
