### ISSUE TITLE
RN的js端可以监听app进入后台吗?(Android)

### ISSUE THREAD

**Issue by xiaomuxi** [facebook/react-native#12791]
我要监听App进入后台的事件,,等它重新进入前台时做一些处理...希望大神可以帮帮忙!
使用场景是Js写的手势密码在某一个Js界面上需要手势密码保护,当程序从后台重新进入前台时需要输入手势密码.但是现在无法获取程序进入后台的状态...本来想用原生MainActivity的onstop方法中向Js发送一个程序进入后台的消息,但是找不到reactContext上下文...

**Comment by nihgwu** [comment]
https://github.com/facebook/react-native/issues/12790#issuecomment-285008822 

**Issues** is for bug report, not for Q&A

**Comment by YouHan26** [comment]
please use English...

**Comment by zhengxkq** [comment]
666
