### ISSUE TITLE
RN 0.42.0 Fails to compile the Xcode project

### ISSUE THREAD

**Issue by akashdmahali** [facebook/react-native#12795]
### Description
Action Taken  : Upgraded from RN version 0.41.0 to version 0.42.0.
Expected        : RN iOS project should compile and run properly (using Xcode 7.3).
Actual             : The RN iOS project fails to compile the file "react-native/React/Profiler/RCTProfile.m" (#line 386)

Here is the code that fails : 

```
#if !TARGET_OS_TV
      UIActivityViewController *activityViewController = [[UIActivityViewController alloc] initWithActivityItems:@[[NSURL fileURLWithPath:outFile]]
                                                                                           applicationActivities:nil];
      activityViewController.completionWithItemsHandler = ^(__unused UIActivityType activityType,
                                                            __unused BOOL completed,
                                                            __unused NSArray *items,
                                                            __unused NSError *error) {
        RCTProfileControlsWindow.hidden = NO;
      };
      RCTProfileControlsWindow.hidden = YES;
      dispatch_async(dispatch_get_main_queue(), ^{
        [[[[[UIApplication sharedApplication] delegate] window] rootViewController] presentViewController:activityViewController
                                                                                                 animated:YES
                                                                                               completion:nil];
      });

#endif
```

### Reproduction
Steps to reproduce : Upgrade the RN project from version 0.41.0 to 0.42.0

### Solution
After commenting out the code mentioned above, the project compiles and runs successfully, however this by no means should be considered a solution. The developer who did those changes would be in a better position to address this (refer the point 1 in more information below)
### More Information
1. [Github commit which has caused this issue](https://github.com/facebook/react-native/commit/453e70d19c28b56dfcecfe205ccd4ccad2b33009)
2. Xcode version : 7.3
3. [People here are facing this issue too](https://github.com/facebook/react-native/issues/12746)

### Additional Information

* React Native version: [RN 0.42.0 : YES]
* Platform: iOS only
* Operating System : MacOS

**Comment by gbau** [comment]
@akashdmahali thanks for the detailed information. I ran into this recently as well, and while it didn't get to the bottom of the issue, updating Xcode from 7.3.1 to 8.2.1 allowed me to build successfully.

**Comment by hramos** [comment]
You'll need Xcode 8. Our tests are done using Xcode 8, therefore we cannot guarantee older versions are fully supported. You can still target older iOS versions than iOS 10 using Xcode 8.

Thanks for bringing this to our attention, the docs will be updated.
