### ISSUE TITLE
Facebook GitHub Bot not responding

### ISSUE THREAD

**Issue by rmevans9** [facebook/react-native#12796]
Hello!

I have noticed that the GitHub bot has stopped responding to commands. I am not sure who manages the bot so if someone knows can they ping them?

Examples of it not responding:
https://github.com/facebook/react-native/issues/12794
https://github.com/facebook/react-native/issues/12792
https://github.com/facebook/react-native/issues/12790#issuecomment-285012441
https://github.com/facebook/react-native/issues/12680 (I edited the comment but originally tried to run the close command)
https://github.com/facebook/react-native/issues/12464

It was working at least about 20 days ago. Example:
https://github.com/facebook/react-native/issues/12361

**Comment by ncuillery** [comment]
https://github.com/facebook/react-native/issues/12210#issuecomment-282593366

**Comment by charpeni** [comment]
cc @sdwilsh

**Comment by sdwilsh** [comment]
cc @zpao who is oncall :)

**Comment by zpao** [comment]
Adding some logging and perhaps a fix in there as well. New changes will deploy in the morning (PST) so let me know if you see any more failures after then and we can hopefully narrow down what's happening.

**Comment by rmevans9** [comment]
@facebook-github-bot cla

**Comment by rmevans9** [comment]
@zpao looks like it might be working.

**Comment by rmevans9** [comment]
@facebook-github-bot close

**Comment by rmevans9** [comment]
@zpao maybe I jumped the gun. After it working here it failed again today:

https://github.com/facebook/react-native/issues/12922
