### ISSUE TITLE
Problem with Chrome Debugger when using spread operator

### ISSUE THREAD

**Issue by rogergl** [facebook/react-native#1280]
The following code works on the Simulator:

 return Promise.all([fileInfo, ...(m.intoArray(setValuePromises))]);

but gives a Syntax error when I try to debug with Chrome.

**Comment by sahrens** [comment]
cc @amasad - missing transform?

**Comment by sebmck** [comment]
The JavaScript wouldn't be going through any transforms because it's just being executed natively.

**Comment by sahrens** [comment]
The JS is still transformed to generate the bundle which is loaded by chrome.

**Comment by rogergl** [comment]
Still confused. Should it work  ?

**Comment by sebmck** [comment]
It shouldn't work and there's probably no real way to make it work.

On Wednesday, 20 May 2015, Roger Gilliar <notifications@github.com> wrote:

> Still confused. Should it work ?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/react-native/issues/1280#issuecomment-103952695>
> .
>


-- 
Sebastian McKenzie

**Comment by ide** [comment]
@sebmck I believe it should work. RN deploys ES5... in theory with ES3 support RN could run in IE8 if we wanted. Something is going wrong with the transform that's causing Chrome to receive a maltransformed spread operator.

@rogergl can you view the JS that is running in Chrome and see what the code around your Promise.all call looks like?

**Comment by rogergl** [comment]
This is the complete method:

      var setContent = (result) => {
            var fileInfo = result[0];
            var setValuePromises = m.map((data) => {
                return Store.setValue(m.get(data, "fileName"), m.get(data, "content"));
            }, fileInfo);
            return Promise.all([fileInfo, ...(m.intoArray(setValuePromises))]);
        };

**Comment by ide** [comment]
@rogergl, sorry - I meant the code that Chrome's web inspector shows under the Sources tab. Things like the arrow functions should be transformed into normal functions.

**Comment by rogergl** [comment]
Chrome displays the code given in the previous posting.

This is the code from the index.ios.bundle file:
    
       var setContent = function(result)  {
            var fileInfo = result[0];
            var setValuePromises = m.map(function(data)  {
                return Store.setValue(m.get(data, "fileName"), m.get(data, "content"));
            }, fileInfo);
            return Promise.all([fileInfo, ...(m.intoArray(setValuePromises))]);
        };

**Comment by sahrens** [comment]
Hopefully this will be fixed when we switch to babel soon.

**Comment by ide** [comment]
@rogergl: thanks. Looks like a transform bug.

The best workaround now is to write a manual array.concat call until the transform pipeline uses babel as @sahrens mentioned.

**Comment by sebmck** [comment]
@ide Oh right. Sorry for speaking out of turn. I thought he was referring to the dev tools console.

**Comment by amasad** [comment]
Yeah, I hate this descripincy. JavaScript Core has rest param support whereas chrome doesn't. Pushing the switch to Babel shortly, and it should include this transform.

**Comment by rogergl** [comment]
Good to know that babel is coming

**Comment by ide** [comment]
Babel landed in master: https://github.com/tadeuzagallo/react-native/commit/56d6ee3f0fadeb66aeb6cf9156c723759f48f617
