### ISSUE TITLE
The big bully - Apple

### ISSUE THREAD

**Issue by ferologics** [facebook/react-native#12801]
So this happened -> 

> Your app, extension, and/or linked framework appears to contain code designed explicitly with the capability to change your app’s behavior or functionality after App Review approval, which is not in compliance with section 3.3.2 of the Apple Developer Program License Agreement and App Store Review Guideline 2.5.2. This code, combined with a remote resource, can facilitate significant changes to your app’s behavior compared to when it was initially reviewed for the App Store. While you may not be using this functionality currently, it has the potential to load private frameworks, private methods, and enable future feature changes.
This includes any code which passes **arbitrary parameters to dynamic methods** such as dlopen(), dlsym(), respondsToSelector:, performSelector:, method_exchangeImplementations(), and running remote scripts in order to change app behavior or call SPI, based on the contents of the downloaded script. Even if the remote resource is not intentionally malicious, it could easily be hijacked via a Man In The Middle (MiTM) attack, which can pose a serious security vulnerability to users of your app.
Please perform an in-depth review of your app and remove any code, frameworks, or SDKs that fall in line with the functionality described above before submitting the next update for your app for review.

The key being `arbitrary parameters`.

Will this affect React Native apps that don't leverage offline JS bundle?

What happens with [Exponent](https://expo.io) @nikki93 ?

**Comment by huhuanming** [comment]
#12778

**Comment by ide** [comment]
This message from Apple is about JSPatch or Rollout, which exposed arbitrary native APIs. React Native doesn't do that (unless you use a third-party module that does, but that's not specific to RN) and Expo definitely doesn't.
