### ISSUE TITLE
Some files have conflicting license information

### ISSUE THREAD

**Issue by willnorris** [facebook/react-native#12813]
The following files have conflicting license information in their headers.  They claim to be both a BSD-style license as well as one of either:
 - `The examples provided by Facebook are for non-commercial testing and evaluation purposes only.`
 - The [CustomComponents license](https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/LICENSE)

They are all js files, so my guess is that you ran a script to add the BSD header to all js files, and they maybe should not have been applied to these?  In any event, it's unclear what license is really supposed to apply to these files.

- [Examples/Movies/MoviesApp.android.js](https://github.com/facebook/react-native/blob/master/Examples/Movies/MoviesApp.android.js)
- [Examples/Movies/SearchBar.android.js](https://github.com/facebook/react-native/blob/master/Examples/Movies/SearchBar.android.js)
- [Examples/TicTacToe/TicTacToeApp.js](https://github.com/facebook/react-native/blob/master/Examples/TicTacToe/TicTacToeApp.js)
- [Examples/UIExplorer/UIExplorerIntegrationTests/RCTRootViewIntegrationTests.m](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/UIExplorerIntegrationTests/RCTRootViewIntegrationTests.m)
- [Examples/UIExplorer/js/AccessibilityAndroidExample.android.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/AccessibilityAndroidExample.android.js)
- [Examples/UIExplorer/js/AccessibilityIOSExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/AccessibilityIOSExample.js)
- [Examples/UIExplorer/js/ActionSheetIOSExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/ActionSheetIOSExample.js)
- [Examples/UIExplorer/js/ActivityIndicatorExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/ActivityIndicatorExample.js)
- [Examples/UIExplorer/js/AdSupportIOSExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/AdSupportIOSExample.js)
- [Examples/UIExplorer/js/AlertExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/AlertExample.js)
- [Examples/UIExplorer/js/AlertIOSExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/AlertIOSExample.js)
- [Examples/UIExplorer/js/AnimatedExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/AnimatedExample.js)
- [Examples/UIExplorer/js/AnimatedGratuitousApp/AnExApp.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/AnimatedGratuitousApp/AnExApp.js)
- [Examples/UIExplorer/js/AnimatedGratuitousApp/AnExBobble.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/AnimatedGratuitousApp/AnExBobble.js)
- [Examples/UIExplorer/js/AnimatedGratuitousApp/AnExChained.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/AnimatedGratuitousApp/AnExChained.js)
- [Examples/UIExplorer/js/AnimatedGratuitousApp/AnExScroll.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/AnimatedGratuitousApp/AnExScroll.js)
- [Examples/UIExplorer/js/AnimatedGratuitousApp/AnExSet.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/AnimatedGratuitousApp/AnExSet.js)
- [Examples/UIExplorer/js/AnimatedGratuitousApp/AnExTilt.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/AnimatedGratuitousApp/AnExTilt.js)
- [Examples/UIExplorer/js/AppStateExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/AppStateExample.js)
- [Examples/UIExplorer/js/AssetScaledImageExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/AssetScaledImageExample.js)
- [Examples/UIExplorer/js/AsyncStorageExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/AsyncStorageExample.js)
- [Examples/UIExplorer/js/BorderExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/BorderExample.js)
- [Examples/UIExplorer/js/BoxShadowExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/BoxShadowExample.js)
- [Examples/UIExplorer/js/ButtonExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/ButtonExample.js)
- [Examples/UIExplorer/js/CameraRollExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/CameraRollExample.js)
- [Examples/UIExplorer/js/CameraRollView.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/CameraRollView.js)
- [Examples/UIExplorer/js/ClipboardExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/ClipboardExample.js)
- [Examples/UIExplorer/js/DatePickerAndroidExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/DatePickerAndroidExample.js)
- [Examples/UIExplorer/js/DatePickerIOSExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/DatePickerIOSExample.js)
- [Examples/UIExplorer/js/ExampleTypes.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/ExampleTypes.js)
- [Examples/UIExplorer/js/FlatListExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/FlatListExample.js)
- [Examples/UIExplorer/js/GeolocationExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/GeolocationExample.js)
- [Examples/UIExplorer/js/ImageCapInsetsExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/ImageCapInsetsExample.js)
- [Examples/UIExplorer/js/ImageEditingExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/ImageEditingExample.js)
- [Examples/UIExplorer/js/ImageExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/ImageExample.js)
- [Examples/UIExplorer/js/LayoutAnimationExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/LayoutAnimationExample.js)
- [Examples/UIExplorer/js/LayoutEventsExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/LayoutEventsExample.js)
- [Examples/UIExplorer/js/LayoutExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/LayoutExample.js)
- [Examples/UIExplorer/js/LinkingExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/LinkingExample.js)
- [Examples/UIExplorer/js/ListExampleShared.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/ListExampleShared.js)
- [Examples/UIExplorer/js/ListViewExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/ListViewExample.js)
- [Examples/UIExplorer/js/ListViewGridLayoutExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/ListViewGridLayoutExample.js)
- [Examples/UIExplorer/js/ListViewPagingExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/ListViewPagingExample.js)
- [Examples/UIExplorer/js/ModalExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/ModalExample.js)
- [Examples/UIExplorer/js/MultiColumnExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/MultiColumnExample.js)
- [Examples/UIExplorer/js/NativeAnimationsExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/NativeAnimationsExample.js)
- [Examples/UIExplorer/js/Navigator/BreadcrumbNavSample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/Navigator/BreadcrumbNavSample.js)
- [Examples/UIExplorer/js/Navigator/JumpingNavSample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/Navigator/JumpingNavSample.js)
- [Examples/UIExplorer/js/Navigator/NavigationBarSample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/Navigator/NavigationBarSample.js)
- [Examples/UIExplorer/js/Navigator/NavigatorExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/Navigator/NavigatorExample.js)
- [Examples/UIExplorer/js/NavigatorIOSColorsExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/NavigatorIOSColorsExample.js)
- [Examples/UIExplorer/js/NavigatorIOSExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/NavigatorIOSExample.js)
- [Examples/UIExplorer/js/NetInfoExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/NetInfoExample.js)
- [Examples/UIExplorer/js/OrientationChangeExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/OrientationChangeExample.js)
- [Examples/UIExplorer/js/PanResponderExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/PanResponderExample.js)
- [Examples/UIExplorer/js/PermissionsExampleAndroid.android.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/PermissionsExampleAndroid.android.js)
- [Examples/UIExplorer/js/PickerExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/PickerExample.js)
- [Examples/UIExplorer/js/PickerIOSExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/PickerIOSExample.js)
- [Examples/UIExplorer/js/PointerEventsExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/PointerEventsExample.js)
- [Examples/UIExplorer/js/ProgressBarAndroidExample.android.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/ProgressBarAndroidExample.android.js)
- [Examples/UIExplorer/js/ProgressViewIOSExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/ProgressViewIOSExample.js)
- [Examples/UIExplorer/js/PushNotificationIOSExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/PushNotificationIOSExample.js)
- [Examples/UIExplorer/js/RCTRootViewIOSExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/RCTRootViewIOSExample.js)
- [Examples/UIExplorer/js/RTLExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/RTLExample.js)
- [Examples/UIExplorer/js/RefreshControlExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/RefreshControlExample.js)
- [Examples/UIExplorer/js/RootViewSizeFlexibilityExampleApp.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/RootViewSizeFlexibilityExampleApp.js)
- [Examples/UIExplorer/js/ScrollViewExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/ScrollViewExample.js)
- [Examples/UIExplorer/js/ScrollViewSimpleExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/ScrollViewSimpleExample.js)
- [Examples/UIExplorer/js/SectionListExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/SectionListExample.js)
- [Examples/UIExplorer/js/SegmentedControlIOSExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/SegmentedControlIOSExample.js)
- [Examples/UIExplorer/js/SetPropertiesExampleApp.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/SetPropertiesExampleApp.js)
- [Examples/UIExplorer/js/SliderExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/SliderExample.js)
- [Examples/UIExplorer/js/SnapshotExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/SnapshotExample.js)
- [Examples/UIExplorer/js/StatusBarExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/StatusBarExample.js)
- [Examples/UIExplorer/js/SwipeableListViewExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/SwipeableListViewExample.js)
- [Examples/UIExplorer/js/SwitchExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/SwitchExample.js)
- [Examples/UIExplorer/js/TabBarIOSExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/TabBarIOSExample.js)
- [Examples/UIExplorer/js/TextExample.android.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/TextExample.android.js)
- [Examples/UIExplorer/js/TextExample.ios.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/TextExample.ios.js)
- [Examples/UIExplorer/js/TextInputExample.android.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/TextInputExample.android.js)
- [Examples/UIExplorer/js/TextInputExample.ios.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/TextInputExample.ios.js)
- [Examples/UIExplorer/js/TimePickerAndroidExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/TimePickerAndroidExample.js)
- [Examples/UIExplorer/js/TimerExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/TimerExample.js)
- [Examples/UIExplorer/js/ToastAndroidExample.android.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/ToastAndroidExample.android.js)
- [Examples/UIExplorer/js/ToolbarAndroidExample.android.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/ToolbarAndroidExample.android.js)
- [Examples/UIExplorer/js/TouchableExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/TouchableExample.js)
- [Examples/UIExplorer/js/TransformExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/TransformExample.js)
- [Examples/UIExplorer/js/UIExplorerActions.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/UIExplorerActions.js)
- [Examples/UIExplorer/js/UIExplorerApp.android.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/UIExplorerApp.android.js)
- [Examples/UIExplorer/js/UIExplorerApp.ios.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/UIExplorerApp.ios.js)
- [Examples/UIExplorer/js/UIExplorerBlock.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/UIExplorerBlock.js)
- [Examples/UIExplorer/js/UIExplorerButton.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/UIExplorerButton.js)
- [Examples/UIExplorer/js/UIExplorerExampleContainer.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/UIExplorerExampleContainer.js)
- [Examples/UIExplorer/js/UIExplorerExampleList.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/UIExplorerExampleList.js)
- [Examples/UIExplorer/js/UIExplorerList.android.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/UIExplorerList.android.js)
- [Examples/UIExplorer/js/UIExplorerList.ios.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/UIExplorerList.ios.js)
- [Examples/UIExplorer/js/UIExplorerNavigationReducer.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/UIExplorerNavigationReducer.js)
- [Examples/UIExplorer/js/UIExplorerPage.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/UIExplorerPage.js)
- [Examples/UIExplorer/js/UIExplorerStatePersister.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/UIExplorerStatePersister.js)
- [Examples/UIExplorer/js/UIExplorerTitle.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/UIExplorerTitle.js)
- [Examples/UIExplorer/js/URIActionMap.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/URIActionMap.js)
- [Examples/UIExplorer/js/VibrationExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/VibrationExample.js)
- [Examples/UIExplorer/js/VibrationIOSExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/VibrationIOSExample.js)
- [Examples/UIExplorer/js/ViewExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/ViewExample.js)
- [Examples/UIExplorer/js/ViewPagerAndroidExample.android.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/ViewPagerAndroidExample.android.js)
- [Examples/UIExplorer/js/WebSocketExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/WebSocketExample.js)
- [Examples/UIExplorer/js/WebViewExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/WebViewExample.js)
- [Examples/UIExplorer/js/XHRExample.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/XHRExample.js)
- [Examples/UIExplorer/js/XHRExampleBinaryUpload.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/XHRExampleBinaryUpload.js)
- [Examples/UIExplorer/js/XHRExampleCookies.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/XHRExampleCookies.js)
- [Examples/UIExplorer/js/XHRExampleDownload.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/XHRExampleDownload.js)
- [Examples/UIExplorer/js/XHRExampleFetch.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/XHRExampleFetch.js)
- [Examples/UIExplorer/js/XHRExampleFormData.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/XHRExampleFormData.js)
- [Examples/UIExplorer/js/XHRExampleHeaders.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/XHRExampleHeaders.js)
- [Examples/UIExplorer/js/XHRExampleOnTimeOut.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/XHRExampleOnTimeOut.js)
- [Examples/UIExplorer/js/createExamplePage.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/createExamplePage.js)
- [Examples/UIExplorer/js/websocket_test_server.js](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/websocket_test_server.js)
- [IntegrationTests/websocket_integration_test_server.js](https://github.com/facebook/react-native/blob/master/IntegrationTests/websocket_integration_test_server.js)
- [Libraries/Components/AppleTV/TVEventHandler.android.js](https://github.com/facebook/react-native/blob/master/Libraries/Components/AppleTV/TVEventHandler.android.js)
- [Libraries/Components/AppleTV/TVEventHandler.ios.js](https://github.com/facebook/react-native/blob/master/Libraries/Components/AppleTV/TVEventHandler.ios.js)
- [Libraries/CustomComponents/ListView/ListView.js](https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/ListView/ListView.js)
- [Libraries/CustomComponents/Lists/FlatList.js](https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/Lists/FlatList.js)
- [Libraries/CustomComponents/Lists/MetroListView.js](https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/Lists/MetroListView.js)
- [Libraries/CustomComponents/Lists/SectionList.js](https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/Lists/SectionList.js)
- [Libraries/CustomComponents/Lists/VirtualizedList.js](https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/Lists/VirtualizedList.js)
- [Libraries/CustomComponents/Lists/VirtualizedSectionList.js](https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/Lists/VirtualizedSectionList.js)
- [Libraries/CustomComponents/NavigationExperimental/NavigationCard.js](https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/NavigationExperimental/NavigationCard.js)
- [Libraries/CustomComponents/NavigationExperimental/NavigationCardStack.js](https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/NavigationExperimental/NavigationCardStack.js)
- [Libraries/CustomComponents/NavigationExperimental/NavigationCardStackStyleInterpolator.js](https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/NavigationExperimental/NavigationCardStackStyleInterpolator.js)
- [Libraries/CustomComponents/NavigationExperimental/NavigationHeader.js](https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/NavigationExperimental/NavigationHeader.js)
- [Libraries/CustomComponents/NavigationExperimental/NavigationHeaderBackButton.js](https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/NavigationExperimental/NavigationHeaderBackButton.js)
- [Libraries/CustomComponents/NavigationExperimental/NavigationHeaderStyleInterpolator.js](https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/NavigationExperimental/NavigationHeaderStyleInterpolator.js)
- [Libraries/CustomComponents/NavigationExperimental/NavigationHeaderTitle.js](https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/NavigationExperimental/NavigationHeaderTitle.js)
- [Libraries/CustomComponents/NavigationExperimental/NavigationPagerStyleInterpolator.js](https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/NavigationExperimental/NavigationPagerStyleInterpolator.js)
- [Libraries/CustomComponents/NavigationExperimental/NavigationPointerEventsContainer.js](https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/NavigationExperimental/NavigationPointerEventsContainer.js)
- [Libraries/CustomComponents/Navigator/Navigator.js](https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/Navigator/Navigator.js)
- [Libraries/CustomComponents/Navigator/NavigatorBreadcrumbNavigationBar.js](https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/Navigator/NavigatorBreadcrumbNavigationBar.js)
- [Libraries/CustomComponents/Navigator/NavigatorSceneConfigs.js](https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/Navigator/NavigatorSceneConfigs.js)
- [Libraries/Experimental/SwipeableRow/SwipeableListView.js](https://github.com/facebook/react-native/blob/master/Libraries/Experimental/SwipeableRow/SwipeableListView.js)
- [Libraries/Experimental/SwipeableRow/SwipeableListViewDataSource.js](https://github.com/facebook/react-native/blob/master/Libraries/Experimental/SwipeableRow/SwipeableListViewDataSource.js)
- [Libraries/Experimental/SwipeableRow/SwipeableQuickActionButton.js](https://github.com/facebook/react-native/blob/master/Libraries/Experimental/SwipeableRow/SwipeableQuickActionButton.js)
- [Libraries/Experimental/SwipeableRow/SwipeableQuickActions.js](https://github.com/facebook/react-native/blob/master/Libraries/Experimental/SwipeableRow/SwipeableQuickActions.js)
- [Libraries/Experimental/SwipeableRow/SwipeableRow.js](https://github.com/facebook/react-native/blob/master/Libraries/Experimental/SwipeableRow/SwipeableRow.js)
- [Libraries/Experimental/WindowedListView.js](https://github.com/facebook/react-native/blob/master/Libraries/Experimental/WindowedListView.js)

**Comment by lacker** [comment]
Hi, I was just chatting with our tools folks about this from your email. We need some linting type thing that makes sure this is all as it is intended. It is somewhat more tricky than you might imagine because of the two mechanisms by which a pull request can be opened. I will find the right people internally to look into this.

**Comment by lacker** [comment]
@ericvicenti is going to help with the license cleanup and is very excited about getting into the world of licensing-tooling :D

**Comment by gyehuda** [comment]
Can you give us a sense of the timeframe for this to be fixed. We'd love to use React-Native and feel blocked by the uncertainty of your licensing intent. Thanks!

**Comment by ericvicenti** [comment]
I'm hoping to get this done by the end of the month, which will allow `react-native v0.44` to have this problem resolved. This release-candidate will be available ~April 1st, and the stable release is scheduled for ~May 1st.

**Comment by ericvicenti** [comment]
Everything other than `Examples/UIExplorer` should be cleaned up, but unfortunately that is still under the samples license for `v0.44`

`UIExplorer` is somewhat tricky to move because it is integrated with our testing setup. I'll figure it out over the next couple weeks, and we will be completely under a consistent license for `0.v45`

**Comment by gyehuda** [comment]
Eric, 
Are you still on track for the May 1st? 
Is that for v0.44 or v045?

**Comment by ejc3** [comment]
Did this get addressed in the latest release?

**Comment by hramos** [comment]
Yes, 0.45 should have addressed this.
