### ISSUE TITLE
White flash before initial <Image /> load

### ISSUE THREAD

**Issue by martco** [facebook/react-native#1281]
My app begins with a View with an image in it, like this: 

     <View style={styles.page}>
       <Image style={styles.biker} source={require('image!Yosemite')} />
     </View>

When I refresh my simulator I see a white flash before the Image loads:

![whiteflash](https://cloud.githubusercontent.com/assets/420959/7639845/d8639218-fa33-11e4-8c6c-babbe2ca6083.gif)

I see this happen on initial app load, too:

1. The LaunchImage shows
2. The white flash shows
3. Then my image show

I'd like to remove the white flash between those stages. There is other content in my view, could that be slowing things down? 

Thanks in advance for the help!

**Comment by ide** [comment]
Try setting the backgroundColor of your RCTRootView to [UIColor clearColor] (arguably RCTRootView should be transparent by default and the example projects should explicitly give it a white background cc @nicklockwood).

@martco also another thing to note is that the system will hide your launch image as soon as the app has launched. So there will be nothing displayed in the period of time after the app has launched but before React has rendered.

**Comment by martco** [comment]
@ide  thanks!@!!! i was able to change the bgColor, can I change it to my image, instead? Can you point me to how to do that? thanks you're awesome@!

**Comment by ide** [comment]
The easiest solution would be set up your app it looks like:

- View - the root of your app
 - UIImage with your background
 - RCTRootView that is transparent and covers your UIImage once loaded

**Comment by martco** [comment]
`self.window.rootViewController.view.backgroundColor = [UIColor colorWithPatternImage:[UIImage imageNamed:@"Splash.png"]];
`

**Comment by martco** [comment]
I'm so happy right now, thanks @ide!!

**Comment by ide** [comment]
Hah awesome!

**Comment by eyaleizenberg** [comment]
I had the same issue, however my image from the rootViewController is not appearing centered. The LaunchImage is fine, the first image is fine too, but the background between them is not aligned.
