### ISSUE TITLE
Picker with dynamic options broke on Android

### ISSUE THREAD

**Issue by danielfeelfine** [facebook/react-native#12829]
### Description
I'm try to make a dynamic Picker. They are 02 Pickers and the second options appear according to the option selected in the first Picker.

In iOS everything works fine, but in Android I got the error `Cannot read 'props' of null` when I select any Picker at second time.

### Reproduction

The code and reproduction of this bug is in [this repository](https://github.com/danielfeelfine/react-native-picker).

### Additional Information

* React Native version: 0.42.0
* Platform: Android
* Operating System: MacOS
* Dev tools: Android SDK 23.0.1

**Comment by sibelius** [comment]
the error is in this line: https://github.com/facebook/react-native/blob/efcdef711eba82b2905d237ee9a3d094652c37ac/Libraries/Components/Picker/PickerAndroid.android.js#L119

**Comment by danielfeelfine** [comment]
Thanks @sibelius. I found the solution.

### Problem
At same point, the `value` passed to [```onValueChange```](https://github.com/facebook/react-native/blob/efcdef711eba82b2905d237ee9a3d094652c37ac/Libraries/Components/Picker/PickerAndroid.android.js#L120) method is _`undefined`_. The property [`this.props.children[position].props.value`](https://github.com/facebook/react-native/blob/efcdef711eba82b2905d237ee9a3d094652c37ac/Libraries/Components/Picker/PickerAndroid.android.js#L119) doesn't exist because `this.props.children` are an _Array_ of _Arrays_. However, at beginning the same property is only an _Array_, and everything works fine.

### Solution
I try to check if `this.props.children` is an _Array_ of _Arrays_ or only an _Array_. If is the first condition, I get the `value` of the second _Array_. If not, I get the `value` of the single _Array_ and it works as expected.

I will working on this problem and I try to solve it in a better way. If anyone has a better solution, please comment here.

**Comment by Tiago-Marques** [comment]
Any news about that? Same error here !

**Comment by danielfeelfine** [comment]
@Tiago-Marques, for now the solution is:

1. Go to this line: https://github.com/facebook/react-native/blob/efcdef711eba82b2905d237ee9a3d094652c37ac/Libraries/Components/Picker/PickerAndroid.android.js#L119

2. Change to this:

```javascript
var value;
if (this.props.children[0][0]) {
  value = this.props.children[0][position].props.value;
} else {
  value = this.props.children[position].props.value;
}
```

It should be work

**Comment by Tiago-Marques** [comment]
@danielfeelfine thank you !

**Comment by danielfeelfine** [comment]
Closed by: https://github.com/facebook/react-native/pull/8153
