### ISSUE TITLE
[ListView] Render empty list component

### ISSUE THREAD

**Issue by hose314** [facebook/react-native#12825]
I read the docs and did not find something like `renderEmptyListViewComponent` in the current `ListView` API.  Of corse i can check if `ListView` is empty by getting `getRowCount()` and do whatever i want but it will be awesome to have such method to render empty component along with existing `renderHeader` and `renderFooter`. 

I understand that it could be specific case but if not i will implement such method and make PR. 

```js
<ListView
  dataSource={this.state.dataSource}
  renderHeader={() => <Header />}
  renderFooter={() => <Footer />}
  ...
  renderEmptyListComponent={() => <EmptyListMessage />}
/>

**Comment by hose314** [comment]
Issue closed, i will render `ProductEmptyView` to the `renderHeader` component

**Comment by Naoto-Ida** [comment]
@hose314 

I still think this is a valid issue when displaying **section headers**.

For instance, I have a list of pets (cats and dogs).
```
const data = {
  cats: [
    { id: 1, name: 'Bob' }
  ],
  dogs: [
  ],
}

In this case the **section header** will display "Cats" and "Dogs" respectively,
but in many cases you would want to render something for when the "Dogs" section is empty.

**Comment by kytwb** [comment]
@Naoto-Ida Since 0.45, `FlatList` got the [ListEmptyComponent](http://facebook.github.io/react-native/releases/0.45/docs/flatlist.html#listemptycomponent) prop.

**Comment by hose314** [comment]
@kytwb yeap, also notice that, thanks!

**Comment by Naoto-Ida** [comment]
@kytwb Thanks for notifying me! Unfortunately I'm still stuck on 0.40 so can't use them.

**Comment by Rewieer** [comment]
How comes ListEmptyComponent is not referenced anymore ? Is it deprecrated or something ? The link is dead.

**Comment by Naoto-Ida** [comment]
Maybe search the docs?

[here](https://facebook.github.io/react-native/docs/next/flatlist.html#listemptycomponent).

**Comment by Rewieer** [comment]
@Naoto-Ida Don't be so aggressive, I was genuinely asking and aimed to provide help to put it in the docs :) 
I was viewing [this page](https://facebook.github.io/react-native/docs/flatlist.html) in which it is not mentionned.
