### ISSUE TITLE
Unable to pull up Developer Menu after upgrade to 0.42.0

### ISSUE THREAD

**Issue by macnube** [facebook/react-native#12832]
### Description
I upgraded my application to latest react native, react and supporting packages. I did this by creating a brand new react native project and importing the necessary files as `react-native-git-upgrade` was not working for me.

Now when running my application on ios simulator, it doesn't seem to recognize `Command⌘ + D`. However in my old project, using 0.38.0, I have no issues. 

I have tried building and running the application from xCode directly and from terminal using `react-native run-ios`

I have also completely cleaned out the node-modules folder and done a clean `npm install`

I have checked and do not have `Slow Animations` enabled

Are there any logs or run commands that I can add to see why the `Command⌘ + D` isn't being recognized?
### Reproduction

You should be able to clone the following repo and reproduce the issue by following the installation instructions here:

https://github.com/macnube/Atdaa

### Additional Information

* React Native version: 0.42.0
* Platform: ios
* Operating System: MacOS
* Dev tools: XCode

**Comment by hramos** [comment]
Did you check the Hardware Keyboard setting?

**Comment by macnube** [comment]
Yep and it's on. Should have mentioned that earlier as well.

![image](https://cloud.githubusercontent.com/assets/7122725/23794193/b2d3b18a-056d-11e7-93a2-b3204ec5cec3.png)

**Comment by mewwts** [comment]
Have the exact same issue. Wondering if it could be some conflict in pbxproj?

**Comment by macnube** [comment]
So I went through the painful process of recreating the project from scratch and slowly adding in everything little by little. Now the cmd R and debug menu with cmd D does work. 

I did this after I cleaned out the project, cleared the TMPDIR for react-native and reinstalled watchman to no avail.

Not the best solution but I'm glad that it's working now.

**Comment by pfulop** [comment]
Had the same problem. After recreating app it was gone until I installed some other lib via cocoapods, the developer menu stopped working. Upgrade to 0.42.3 solved  this issue so I guess if somebody has same problem, just do upgrade.
