### ISSUE TITLE
[Layout] CSS min-height/max-height

### ISSUE THREAD

**Issue by ecesena** [facebook/react-native#1284]
Are these available, at least for Text?
Any trick to achieve that anyway?

**Comment by ide** [comment]
The React docs say they aren't supported but css-layout says they are: https://github.com/facebook/css-layout#supported-attributes. So I believe React's copy of css-layout needs to be updated and the new properties exposed to Views.

**Comment by ide** [comment]
@vjeux can we get periodic updates of css-layout to keep it up-to-date ex: maybe the on-call does a weekly sync? We also wouldn't want css-layout to get too far ahead of React and accumulate features that need be reverted because they break apps in ways that are hard to fix.

**Comment by vjeux** [comment]
Yes, we have fallen behind. Unfortunately, bringing up the latest version breaks some of our products internally so I have to update them as well.

As for min/max height, unfortunately the current implementation in css-layout is NOT complete enough that it should be added to react native. There are many cases that it doesn't support correctly.

**Comment by ide** [comment]
OK, thanks for the update.

**Comment by ecesena** [comment]
Thanks for the prompt update.

Not sure if it could simplify, but I guess that having min/max height only for Text could already be a big step forward. Also, having just one of two, as most of the time you can work on a dual problem.

My use case, for instance, is a view with an image and a text hidden behind. On click, I want to bring the text in front and the image behind.
When text is behind, I can force height and overflow so that it doesn't overflow the image size.
When text is in front, however, I can either set the height (that would crop a text too long) or leave it auto (that creates a small text box if the text is too short).
As I was mentioning, either min-height or max-height, and just on Text could solve the problem.

**Comment by vjeux** [comment]
Can't you use numberOfLines attribute of the Text for this?

**Comment by ecesena** [comment]
Sorry, I explained in a confusing way.
When text is in front, I'd like to show the full text without truncating it (even when very long), but I'd like to set a minimum height if it's too short, to avoid a text box too small.
(editing also the previous comment to improve readability)

**Comment by sahrens** [comment]
You might be able to use onLayout as a workaround - based on the height of the rendered text you could add some margin as necessary.

**Comment by cgarvis** [comment]
How should min/max height work on images?

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/layout-css-min-heightmax-height

**Comment by narychen** [comment]
I don't think this feature should use product pains to determine whether or not implement.
It is a must have feature of  css flex layout. 
If you don't have this feature, react-native is not complete. And a lot of displays cannot be made as the web way.

**Comment by AbhishekCode** [comment]
minHeight , maxHeight properties works in iOS but not in android. is there any workaround for this?

**Comment by Nadeermalangadan** [comment]
+1

**Comment by mienaikoe** [comment]
I've tried minHeight on Android using React Native v0.39.2, and it seems to be working fine
