### ISSUE TITLE
0.42 version Android packaging error

### ISSUE THREAD

**Issue by kmend** [facebook/react-native#12874]
react-native bundle --platform android --dev false 

ERROR

E/ReactNativeJS: Can't find variable: runInContext
E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules

bundle --platform android --dev ture  is ok

Code can not be compressed, what is the reason?

**Comment by ide** [comment]
There was a bug in uglify-js, clear your node_modules and install again.

**Comment by kmend** [comment]
Well, thank you
