### ISSUE TITLE
Step 2 of Android "Getting Started" instructions is impossible to follow if step 1 was completed

### ISSUE THREAD

**Issue by ExplodingCabbage** [facebook/react-native#12897]
### Description

Step 1 at https://facebook.github.io/react-native/docs/getting-started.html instructs the reader to install Android Studio by following the instructions at https://developer.android.com/studio/install.html. Those instructions (at least on Linux) include a video that shows running Android Studio for the first time and doing a "Standard" installation.

Step 2 then instructs the reader *not* to do a "Standard" installation, but rather to do a "Custom" one. However, if the user has already done Step 1, then by now it is too late and Step 2 is impossible to follow.

### Solution

Either:
- merge steps 1 and 2 together, noting that a "Custom" install is necessary *before* providing the link to the https://developer.android.com/studio/install.html, or
- modify step 2 to describe how to ensure that the necessary components are installed *after* having done a "Standard" installation

### Additional Information

* React Native version: irrelevant
* Platform: Android
* Operating System: Linux
* Dev tools: Android Studio

**Comment by hramos** [comment]
Thanks for the feedback - I fixed this in master last week: http://facebook.github.io/react-native/releases/next/docs/getting-started.html

**Comment by ExplodingCabbage** [comment]
Oops, I probably should've check that before opening an issue. Thanks, @hramos.
