### ISSUE TITLE
FlatList with default selected index?

### ISSUE THREAD

**Issue by coodoo** [facebook/react-native#12891]
Although there is `scrollToIndex()` for FlatList, but seems there's no property to set default selected index on a list, something like this:

```javascript
<FlatList selectedIndex={12} />
```

Am I missing something? or is there a suggested way to make that happen?

cc @sahrens

**Comment by sahrens** [comment]
Not anything right now. If you call `scrollToIndex({..., animated: false})` in `componentDidMount` does that work for you?

**Comment by coodoo** [comment]
Yup that's exactly how I'm doing it now, just hoping there would be even easier way to make that happen :)
