### ISSUE TITLE
React Packager "Unexpected raw mappings" in 0.43.0-rc.2

### ISSUE THREAD

**Issue by pocesar** [facebook/react-native#12895]
### Description

After starting Perf Monitor with Dev settings off, React Packager eventually choked without me doing anything with:

```
 ERROR  Unexpected raw mappings for G:\mobile\cadastro\lib\root.js
{"name":"Invariant Violation","framesToPop":1}
Invariant Violation: Unexpected raw mappings for G:\mobile\cadastro\lib\root.js
    at invariant (G:\mobile\cadastro\node_modules\react-native\node_modules\fbjs\lib\invariant.js:44:15)
    at getModules.forEach.module (G:/mobile/cadastro/node_modules/react-native/packager/src/Bundler/Bundle.js:222:7)
    at Array.forEach (native)
    at Bundle._getCombinedSourceMaps (G:/mobile/cadastro/node_modules/react-native/packager/src/Bundler/Bundle.js:217:23)
    at Bundle.getSourceMap (G:/mobile/cadastro/node_modules/react-native/packager/src/Bundler/Bundle.js:245:14)
    at Bundle.getSourceMapString (G:/mobile/cadastro/node_modules/react-native/packager/src/Bundler/Bundle.js:251:34)
    at building.then.p (G:/mobile/cadastro/node_modules/react-native/packager/src/Server/index.js:777:31)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

### Reproduction

* Enable perf monitor
* Reload a couple of times

### Additional Information

* React Native version: 0.43.0-rc.2
* Platform: Android
* Operating System: Windows 10 x64

**Comment by Jakevin** [comment]
+1
When I do reload at using Remote JS Debug.
```
Unexpected raw mappings for /Volumes/mx200/ReactNativeProject/accupassnative/js/Globals.js
{"name":"Invariant Violation","framesToPop":1}
Invariant Violation: Unexpected raw mappings for /Volumes/mx200/ReactNativeProject/accupassnative/js/Globals.js
    at invariant (/Volumes/mx200/ReactNativeProject/accupassnative/node_modules/fbjs/lib/invariant.js:44:15)
    at /Volumes/mx200/ReactNativeProject/accupassnative/node_modules/react-native/packager/src/Bundler/Bundle.js:222:7
    at Array.forEach (native)
    at Bundle._getCombinedSourceMaps (/Volumes/mx200/ReactNativeProject/accupassnative/node_modules/react-native/packager/src/Bundler/Bundle.js:217:23)
    at Bundle.getSourceMap (/Volumes/mx200/ReactNativeProject/accupassnative/node_modules/react-native/packager/src/Bundler/Bundle.js:245:14)
    at Bundle.getSourceMapString (/Volumes/mx200/ReactNativeProject/accupassnative/node_modules/react-native/packager/src/Bundler/Bundle.js:251:34)
    at /Volumes/mx200/ReactNativeProject/accupassnative/node_modules/react-native/packager/src/Server/index.js:754:31
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by nishiltamboli** [comment]
+1
Same issue. When I enable Remote Debugger and reload - Particularly when there is a reload after some change is made in a file.

**Comment by GeoffreyPlitt** [comment]
Getting this constantly now.

**Comment by zachrnolan** [comment]
+1
Having the same exact issue every reload.

**Comment by groke** [comment]
Me too. Maybe a plugin causing it? Do we have anything in common?
    "react-native-admob": "^1.2.1",
    "react-native-fcm": "^6.1.0",
    "react-native-linear-gradient": "^2.0.0",
    "react-native-menu": "^0.20.2",
    "react-native-splash-screen": "^2.0.0",
    "react-native-swipe-gestures": "^1.0.2",
    "react-native-timer": "^1.3.1",
    "redux-persist": "^4.4.2",

**Comment by GeoffreyPlitt** [comment]
We use react-native-linear-gradient and react-native-swipe-gestures

**Comment by groke** [comment]
I think I found a way around this issue, at least for my setup.
From the development menu on my android I selected _Dev Settings_ and re-enabled _JS Dev Mode_ that resolved this issue for me.

**Comment by ophite** [comment]
+1

**Comment by itbeihe** [comment]
+1.
When I do reload and change JS Dev Mode at using Remote JS Debug.
### Additional Information
react-native-cli: 2.0.1
react-native: 0.43.3
Platform: Android avd
Operating System: debian 8

**Comment by Wu4D** [comment]
+1 Disable dev mode + Start remote js debuging + Reload  it crashes.
Enabling dev mode does solve it

**Comment by JosephDev** [comment]
+1
I have the same issue on iOS. any solution for iOS?

"react-native": "0.43.3",
"react": "16.0.0-alpha.6",

**Comment by mehulmpt** [comment]
+1
I face the same issue randomly when developing on real device. (Using adb reverse tcp 8081)

**Comment by nimishrocks** [comment]
+1 
Same issue. with enabling the remote debugging app crasher on every reload

**Comment by BeckZero** [comment]
+1!! 
"react": "16.0.0-alpha.6",
"react-native": "0.44.2",

**Comment by JosephDev** [comment]
Here is my solution but I don't know why it works.

0. remove native codes. ios and android folders. !! backup first !!
`rm -rf os && rm -rf android`
1. create a new dummy project.
`react-native init AwesomeProject`
2. copy native codes to current project folders
```
cp -R AwesomeProject/ios currentProject/
cp -R AwesomeProject/android currentProject/ 
```
3. build
4. modify native codes as you've done on current project for example:
- icons, version information, and/or push notification etc...

**Comment by annelorraineuy** [comment]
I am getting this as well.
So on **DEV mode ON**, chrome debugging works the first time. Upon reload, the app is just a white screen. So I have to turn off Remote JS Debugging in order to get the app back again. Rinse and repeat cycle. :/

`"react-native": "0.44.0"`
I am using `"react-native-navigation": "^1.1.81"` though. Not sure if this has something to do with it.

**Comment by Zehio** [comment]
+1!!!!  Extremely annoying.

**Comment by ItsNoHax** [comment]
This still happens, has any facebook dev replied to this?

**Comment by fredbt** [comment]
This is also happening to me. Really annoying.

**Comment by wuyunqiang** [comment]
me too.
android simulator is right. and hardware is bug show me.
![reloadimg](https://user-images.githubusercontent.com/13480948/28909780-75098624-785c-11e7-825b-216c0de8a502.png)

**Comment by RomanVanso** [comment]
Same issue by me with
`react-native-cli: 2.0.1
react-native: 0.47.2`

**Comment by alzalabany** [comment]
any workaround yet ?

**Comment by WolfieZero** [comment]
I've been having this issue, but I can pin-point it to a line.

```javascript
findContent(block: Block): string {
    const contentBlock = block.descendants[0];

    if (typeof contentBlock.content === 'string') {
        return contentBlock.content;
    }

    return '';
}
```

So that causes the error to occur. But if I make a simple change to the `if()` block...

```javascript
findContent(block: Block): string {
    const contentBlock = block.descendants[0];

    if (typeof contentBlock.content === 'string') {
        const content = contentBlock.content;
        return content;
    }

    return '';
}
```

That runs fine. So, to me, it has an issue with referencing `content` within an object.

Hope that provides a bit of insight.

JS Dev Mode: off
JS Minify: off
Remote JS Debugging: on
react: 16.0.0-alpha.12
react-native: 0.46.3

**Comment by lasuax** [comment]
Impossible to debug because of this disruptive error.
