### ISSUE TITLE
Android photo upload error: Can someone explain "One of the sources for assign has an enumerable key on the prototype chain"?

### ISSUE THREAD

**Issue by booboothefool** [facebook/react-native#12902]
Am using https://github.com/marcshilling/react-native-image-picker if that makes a difference.

![screen shot 2017-03-13 at 1 55 38 pm](https://cloud.githubusercontent.com/assets/13257645/23868432/bf8d50b8-07f5-11e7-98d6-f10236faf636.png)

On RN 0.37 leads to a file `polyfills.js` similar to https://github.com/facebook/react-native/blob/master/packager/src/Resolver/polyfills/Object.es6.js where:
```
for (var key in nextSource) {
  if (__DEV__) {
    var hasOwnProperty = Object.prototype.hasOwnProperty;

    if (!hasOwnProperty.call(nextSource, key)) {
      console.log(nextSource);
      console.log(key);
      console.log(!hasOwnProperty.call(nextSource, key));
      console.log(target);
      console.log(target[key]);
      console.log(nextSource[key]);
      throw new TypeError(
        'One of the sources for assign has an enumerable key on the ' +
        'prototype chain. This is an edge case that we do not support. ' +
        'This error is a performance optimization and not spec compliant.'
      );
    }
  }

  target[key] = nextSource[key];
```

logs out:
![screen shot 2017-03-13 at 2 00 12 pm](https://cloud.githubusercontent.com/assets/13257645/23868675/afa2f83c-07f6-11e7-85f9-364dd273d285.png)

The same upload code works in iOS, however.

**Comment by nxmohamad** [comment]
hi. did you find a solution for this? currently facing the same error

**Comment by kevin91liu** [comment]
@nxmohamad in case you are still looking for a workaround, this may help you: https://github.com/facebook/react-native/issues/16814#issuecomment-344083873

**Comment by nxmohamad** [comment]
@kevin91liu I am currently not dealing with the same codebase, but I'll definitely come back here should I need it again. Thank you so much for sharing.
