### ISSUE TITLE
ListView sometimes leaves an extra pixel between rows

### ISSUE THREAD

**Issue by RalfNieuwenhuizen** [facebook/react-native#12918]
Once every two or three rows the ListView has an empty pixel row between the actual rows of the list. Any clue where this comes from?

**Comment by Benjamin-Dobell** [comment]
I've seen this same problem in RN 0.42 with other views, not a `ListView` (on iOS, admittedly haven't checked Android). Specifically I've seen it occurring horizontally with a `row` flex layout.

I'm inclined to think that there's a Yoga bug whereby it's attempting pixel-align views. However, it's doing so inconsistently, whereby the "previous" view in the flex layout is not having its primary axis (`flexDirection`) size rounded up, but positions are being rounded up. Or perhaps the reverse.

**Comment by RalfNieuwenhuizen** [comment]
Ah yes, I should have been more specific probably. This happens in iOS only as far as I have seen.
Your explanation may be right in that case.

**Comment by hramos** [comment]
Closing as ListView is deprecated in 0.43. Use FlatList.

**Comment by LeoAref** [comment]
@hramos Is `FlatList` documented somewhere?
The link [here](https://facebook.github.io/react-native/docs/performance.html#listview-initial-rendering-is-too-slow-or-scroll-performance-is-bad-for-large-lists) redirects to the main page!
