### ISSUE TITLE
Double tapping R after making a change in index.android.js doesn't reload the app.

### ISSUE THREAD

**Issue by vijaybritto** [facebook/react-native#12928]
### Description

Installed react native for android as per official docs. Ran the app. It loads in the emulator. But whenever I make a change in index.android.js and press R twice, it doesn't reload the app as mentioned.

### Additional Information

* React Native version: 0.42.0
* Platform: Android
* Operating System: OSX 10.11.6
* Dev tools: Android studio

**Comment by vijaybritto** [comment]
Figured it out.
cmd + M open the developer options. It has the option for hot reloading. Enabling that works.
It has to be mentioned in the docs.

**Comment by hramos** [comment]
You don't need to turn on hot reloading for refresh to work.

**Comment by darthbinamira** [comment]
Still doesn't work for me. Enabled live reload in the developer options (Ctrl+M) and tried changing index.android.js.

Hot reload works though...

**Comment by llaine** [comment]
+1

**Comment by darthbinamira** [comment]
found out that for android you need to enable keyboard in config.ini:

hw.keyboard=yes

**Comment by llaine** [comment]
@darthbinamira which `config.ini` ?

**Comment by darthbinamira** [comment]
in ubuntu it is in ${HOME}/.android/avd/<avd name>/config.ini

**Comment by llaine** [comment]
This didn't solved the problem actually.

**Comment by mqklin** [comment]
@darthbinamira thank you very much, works nicely!

**Comment by darthbinamira** [comment]
@mqklin you're welcome! good to know it worked for you :)

**Comment by fengerzh** [comment]
@darthbinamira in Mac OSX same position. Thank you!

**Comment by darthbinamira** [comment]
@fengerzh you're welcome! glad to be of help! :)

**Comment by 3jFernando** [comment]
Hola, en mi caso uso Ubuntu pero corro la app en un dispositivo real, y no se actualiza agitando el dispositivo que hago?

Gracias

**Comment by Adrek** [comment]
@3jFernando agita tu dispositivo hasta que aparezca el popup del menú y luego presiona "Enable Hot Reloading". Ahora cuando hagas los cambios en tu archivo ya se podrá ver en tu dispositivo.
