### ISSUE TITLE
NetworkOverlay - undefined is not an object (evaluating '_this._renderScrollComponent.bind')

### ISSUE THREAD

**Issue by fdnhkj** [facebook/react-native#12925]
#### What I did
1. Toggle inspector
2. Press Network

#### What I expected to happen
See the network panel

#### What happens
<img width="376" alt="capture d ecran 2017-03-14 a 13 15 34" src="https://cloud.githubusercontent.com/assets/5569608/23902115/3b96d790-08c0-11e7-9d85-08e1ba26d3b8.png">
Stack trace

> undefined is not an object (evaluating '_this._renderScrollComponent.bind')
> NetworkOverlay
>     NetworkOverlay.js:100:62
> <unknown>
>     ReactCompositeComponent.js:405:30
> measureLifeCyclePerf
>     ReactCompositeComponent.js:85:11
> _constructComponentWithoutOwner
>     ReactCompositeComponent.js:405:10
> _constructComponent
>     ReactCompositeComponent.js:376:10
> mountComponent
>     ReactCompositeComponent.js:202:6
> mountComponent
>     ReactReconciler.js:62:6
> updateChildren
>     ReactChildReconciler.js:157:10
> _reconcilerUpdateChildren
>     ReactMultiChild.js:212:10
> _updateChildren
>     ReactMultiChild.js:345:6
> updateChildren
>     ReactMultiChild.js:331:25
> receiveComponent
>     ReactNativeBaseComponent.js:130:24
> receiveComponent
>     ReactReconciler.js:163:38
> _updateRenderedComponent
>     ReactCompositeComponent.js:982:8
> _performComponentUpdate
>     ReactCompositeComponent.js:944:34
> updateComponent
>     ReactCompositeComponent.js:847:8
> receiveComponent
>     ReactCompositeComponent.js:710:6
> receiveComponent
>     ReactReconciler.js:163:38
> _updateRenderedComponent
>     ReactCompositeComponent.js:982:8
> _performComponentUpdate
>     ReactCompositeComponent.js:944:34
> updateComponent
>     ReactCompositeComponent.js:847:8
> receiveComponent
>     ReactCompositeComponent.js:710:6
> receiveComponent
>     ReactReconciler.js:163:38
> updateChildren
>     ReactChildReconciler.js:143:10
> _reconcilerUpdateChildren
>     ReactMultiChild.js:212:10
> _updateChildren
>     ReactMultiChild.js:345:6
> updateChildren
>     ReactMultiChild.js:331:25
> receiveComponent
>     ReactNativeBaseComponent.js:130:24
> receiveComponent
>     ReactReconciler.js:163:38
> _updateRenderedComponent
>     ReactCompositeComponent.js:982:8
> _performComponentUpdate
>     ReactCompositeComponent.js:944:34
> updateComponent
>     ReactCompositeComponent.js:847:8
> receiveComponent
>     ReactCompositeComponent.js:710:6
> receiveComponent
>     ReactReconciler.js:163:38
> updateChildren
>     ReactChildReconciler.js:143:10
> _reconcilerUpdateChildren
>     ReactMultiChild.js:212:10
> _updateChildren
>     ReactMultiChild.js:345:6
> updateChildren
>     ReactMultiChild.js:331:25
> receiveComponent
>     ReactNativeBaseComponent.js:130:24
> receiveComponent
>     ReactReconciler.js:163:38
> _updateRenderedComponent
>     ReactCompositeComponent.js:982:8
> _performComponentUpdate
>     ReactCompositeComponent.js:944:34
> updateComponent
>     ReactCompositeComponent.js:847:8
> receiveComponent
>     ReactCompositeComponent.js:710:6
> receiveComponent
>     ReactReconciler.js:163:38
> _updateRenderedComponent
>     ReactCompositeComponent.js:982:8
> _performComponentUpdate
>     ReactCompositeComponent.js:944:34
> updateComponent
>     ReactCompositeComponent.js:847:8
> performUpdateIfNecessary
>     ReactCompositeComponent.js:735:8
> performUpdateIfNecessary
>     ReactReconciler.js:213:46
> runBatchedUpdates
>     ReactUpdates.js:171:6
> perform
>     Transaction.js:149:24
> perform
>     Transaction.js:149:24
> perform
>     ReactUpdates.js:96:8
> flushBatchedUpdates
>     ReactUpdates.js:199:26
> closeAll
>     Transaction.js:222:29
> perform
>     Transaction.js:163:24
> batchedUpdates
>     ReactDefaultBatchingStrategy.js:65:33
> batchedUpdates
>     ReactUpdates.js:111:41
> _receiveRootNodeIDEvent
>     ReactNativeEventEmitter.js:126:32
> receiveTouches
>     ReactNativeEventEmitter.js:213:8
> __callFunction
>     MessageQueue.js:242:47
> <unknown>
>     MessageQueue.js:108:26
> guard
>     MessageQueue.js:46:4
> callFunctionReturnFlushedQueue
>     MessageQueue.js:107:10
> 

### Solution

It looks related to https://github.com/facebook/react-native/commit/850c71c2f3512b3d7211f89d06fad0ed5cc21794

### Additional Information

* React Native version: 0.42.0
* Platform: both
* Operating System: MacOS

**Comment by fdnhkj** [comment]
cc @janicduplessis

**Comment by janicduplessis** [comment]
Hey, thanks for reporting this, it has been fixed in 0.43 which is currently in RC.

**Comment by fdnhkj** [comment]
Hey @janicduplessis , thanks for the reply!
Could you please help me finding the fix ?
I don't find it in the  [0.43 release changes.](https://github.com/facebook/react-native/compare/v0.43.0-rc.2...master)
