### ISSUE TITLE
Execution failed for task ':app:installDebug'.

### ISSUE THREAD

**Issue by Rebaiahmed** [facebook/react-native#12937]
com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: Failed to install all
![react](https://cloud.githubusercontent.com/assets/13053759/23919742/59117a86-08f8-11e7-9b99-d329a2ce1ed9.png)

**Comment by iremlopsum** [comment]
Is this happening on 0.43.0 version? Because I have the same problem.

**Comment by hramos** [comment]
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Comment by arvenjadeaguilar** [comment]
I am also experiencing this issue. :(

**Comment by crystalcatdika** [comment]
hey,my experiencing this similar issue;
>building 97%> :app:installDebug

**Comment by Tom29** [comment]
Any solution?

**Comment by notmaster** [comment]
@Tom29 try this, find something like "installation sources" in your device setting, then allow the option "Unknown Sources".
( my english sucks , hope you know what i mean : )

**Comment by ChristianFontes** [comment]
adb devices

List of devices attached 
yourDeviceId	device

react-native run-android --deviceId yourDeviceId
