### ISSUE TITLE
[PickerIOS & TabBarIOS] Breaks when rotated.

### ISSUE THREAD

**Issue by admmasters** [facebook/react-native#1294]
PickerIOS does not scale nicely when the device is rotated. Rotate once to the right, then back and it ends up in a weird state. Attaching screenshots to illustrate. Tried various flexbox layouts but the same issue persists. This is using the sample code stripped down to just one picker.
![ios simulator screen shot 15 may 2015 09 26 15](https://cloud.githubusercontent.com/assets/335607/7649442/e98519de-fae4-11e4-95cd-e911e3e5aa84.png)
![ios simulator screen shot 15 may 2015 09 26 12](https://cloud.githubusercontent.com/assets/335607/7649444/ec90ce66-fae4-11e4-8d29-0a20d2dda0d8.png)

**Comment by romanonthego** [comment]
rotation does not works very well with flexbox model here - I believe it's layout (even simpliest one) whats broken, no picker itself since he is pure native.

**Comment by iostalk** [comment]
watch

**Comment by brentvatne** [comment]
Collapsing #1206 into this as well

**Comment by achang28** [comment]
Just in case someone has not yet seen the issue...

![portrait1](https://cloud.githubusercontent.com/assets/3760499/8739120/78d54e46-2bec-11e5-8d53-bd1a05bd7fcc.png) ![portrait2](https://cloud.githubusercontent.com/assets/3760499/8739121/7bc00db2-2bec-11e5-9a69-9d72fa0ec55a.png)

**Comment by brentvatne** [comment]
I believe I remember seeing a commit that fixes this, if it still persists I can reopen
