### ISSUE TITLE
TouchableOpacity onPress event not handled on Andorid when upgrading from 0.33 to 0.34

### ISSUE THREAD

**Issue by jcbiznoff** [facebook/react-native#12941]
### Description

TouchableOpacity's onPress is not a recognized event on Android after an upgrade. iOS is fine.
I expected onPress on the debug console, but nothing shows.

```
class App extends Component<void, Props, void> {
  render() {
    return (
      <TouchableOpacity
        style={{flex:1}}
        onPress={() => console.log('onPress!')}>
        <Text>Pressed</Text>
      </TouchableOpacity>

    );
  }
}
AppRegistry.registerComponent('App', () => App);
```

### Reproduction

upgrade from 0.33 to 0.34

### Solution

[FILL THIS OUT: What needs to be done to address this issue? Ideally, provide a pull request with a fix.]

### Additional Information

* React Native version:0.33 -> 0.34
* Platform: Android
* Operating System: MacOS
* Dev tools: Android Studio

**Comment by hramos** [comment]
I'd be surprised if something this basic broke in 0.34 and we're only hearing about it now.

Does this still happen in 0.42?

**Comment by jcbiznoff** [comment]
@hramos 0.42 still has the same behavior. Btw I ran this on SDK 23 and 25.

**Comment by jcbiznoff** [comment]
I think package versions for react/react-native were getting mixed up under node_modules. Clearing this out and carefully using "npm update" got rid of the issue.
