### ISSUE TITLE
Components without a key in an array break whole app

### ISSUE THREAD

**Issue by wokalski** [facebook/react-native#12949]
### Description

I have a component with the following render function.

```
  render() {
    return (
      <View style={{ flex: 1 }}>
        {this.props.children}
        {this.props.barEmbedded
          ? [
              this.props.renderBar(this.pullUpResponder),
              this.renderExpandedContentIfNeeded()
            ]
          : null}
      </View>
    );
  }
```

If the component returned by `renderBar` doesn't have `key` specified *nothing is rendered (i.e. screen is blank)* and there's no error/warning. The moment I add `key` to the component everything behaves correctly.

### Reproduction

I tried reducing it but couldn't reproduce it in a small example.

### Solution

No idea, sorry.

### Additional Information

* React Native version: 0.43.0-rc.0
* Platform: iOS
* Operating System: macOS
* Dev tools: Xcode 8.2.1, iOS 10.2

**Comment by Ehesp** [comment]
Does this happen on 0.42?

**Comment by wokalski** [comment]
No, I just checked. In 0.42 the element is rendered and there's a warning as expected.

**Comment by wokalski** [comment]
Ooops, it's gone in 0.43.0-rc.2. Very interesting. I also moved from React 16.0.0-alpha.3 to alpha 4.
