### ISSUE TITLE
'React/RCTAnimationType.h' file not found

### ISSUE THREAD

**Issue by bitsal** [facebook/react-native#12952]
### Description
`react-native run-ios` fails with
```
.../react-native/React/Base/RCTConvert.h:13:9: fatal error: 'React/RCTAnimationType.h' file not found
#import <React/RCTAnimationType.h>
```

Prodfile:
```
...
# use_frameworks!

  react_path = '../node_modules/react-native'
  yoga_path = File.join(react_path, 'ReactCommon/yoga')

  # Pods for drfocused
  pod 'React', :path => react_path, :subspecs => [
    'Core',
    'RCTText',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTSettings',
    'RCTVibration',
    'RCTGeolocation',
    'RCTActionSheet',
    'RCTNetwork',
    'RCTWebSocket'
  ]
  pod 'Yoga', :path => yoga_path
...
```

Any ideas how to treat it?

### Additional Information

* React Native version: 0.42.0
* Platform: iOS
* Operating System: MacOS
* CocoaPods: 1.2.0

**Comment by ericvicenti** [comment]
Does this happen on a brand new project, or just on your app? It sounds like your Xcode configuration may not have been upgraded. Did this error always happen for you, or did something change recently that may have caused it?

**Comment by bitsal** [comment]
Existing app. We are migration from `0.39.x` to `0.42.0`.

@ericvicenti The error occurred right after I switched to new RN version.

**Comment by shergin** [comment]
Have you tried rebuilding Pods? Just delete `Podfile.lock`, `Pods`, and run `pod install`.

**Comment by bitsal** [comment]
Usually, I remove the following folders:
 - ios/Pods/*
 - node_modules/react*
 - ios/build/*
 - ~/Libraries/Developer/Xcode/DerivedData/*

Anyway, I've tried to remove `Podfile.lock` and got the same error.

**Comment by bitsal** [comment]
@shergin @ericvicenti any ideas how to fix it?
We want to move to the newest version of react-native and all related libraries but we can't due to this.

Any thoughts how to figure it out myself appreciated.

**Comment by bitsal** [comment]
I've noticed that RCTAnimationType.h is included into React proj file:
`node_modules/react-native/React/React.xcodeproj/project.pbxproj:				3D302FE81DF8290600D6DDAE /* RCTAnimationType.h in Copy Headers */,`

but why is it invisible for my project?!

**Comment by jasongaare** [comment]
Any ideas on this? Having the same issue.

**Comment by bitsal** [comment]
FYI,
If you use Cocoapods some of the libraries are linked incorrectly (at least as expected):
Libraries that you link via Cocoapods still should be under Libraries folder but not in linking section (I mean e.g. libReact.a).

E.g. some of my issues have gone when I:

1. added React.xcodeproj under Libraries
2. added React to the schema -> Build -> targets (BUT not from Pods, only from React.xcodeproj)
3. removed libReact.a from Build Phases -> Link Binary With Libraries section

And I had to link RCTAnimation as described [here](https://github.com/facebook/react-native/issues/11094#issuecomment-263240420)

This particular issue either has gone.

**Comment by bitsal** [comment]
I think this issue can be closed due to it works after I linked RCTAnimuation.
