### ISSUE TITLE
Update Intro Tutorial: Using a List View

### ISSUE THREAD

**Issue by hramos** [facebook/react-native#12960]
Now that FlatList and SectionList are coming up in 0.43, we can recommend their use over ListView in [Using a ListView](https://facebook.github.io/react-native/releases/next/docs/using-a-listview.html).

**Comment by MichelDiz** [comment]
I got problems to test the FlatList - " UnableToResolveError: Unable to resolve module `react/lib/ReactPropTypeLocations` "
I think is about the react module it self.  I'm using ""react": "^16.0.0-alpha.3"" that's recommended by the yarn installer.  And I'm using "react-native": "0.43.0-rc.2".

Just to be sure, I really need to upgrade the React module to use 0.43.0-rc.2? Thanks! Best regards.

**Comment by hramos** [comment]
I'm using FlatList on React Native 0.43.0-rc.2 and React ~16.0.0-alpha.3, but did not run into this issue.

```
	"dependencies": {
		"react": "~16.0.0-alpha.3",
		"react-native": "0.43.0-rc.2"
	},
```

**Comment by MichelDiz** [comment]
Yep, I think few modules need old dependencies :/
Installing as "fresh" react-native init some app it's okay but when I insert old modules to my actual working progress app. It ask for old dependencies from react 15 or 14 not sure the version but it's older.

I think that I have to wait for stable dependencies...

**Comment by thiensubs** [comment]
I think we should close this issue, because now RN 0.43.0 is release.

**Comment by hramos** [comment]
The issue requires the tutorial to be updated, which has not yet happened. We can leave it open.

**Comment by hanumanthan** [comment]
@hramos If you could let me know what needs to be updated in the tutorial, I can take a jab on it

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
