### ISSUE TITLE
Using the backingViewController in native code

### ISSUE THREAD

**Issue by ssssssssssss** [facebook/react-native#1297]
Dear team,

We'd like to hook up our native UINavigationcontroller and view hierarchy to react native view's backingviewcontroller, so the native code can response to UI events and push view controller using the native UINavigationcontroller. the work flow looks like this:
1. Render React native tabbar, 
2. click the tabbar item
3. render a native view for tab content, and the native view will try to manipulate the backingviewcontroller.

Any clue to do it safely in native code?

**Comment by robertjpayne** [comment]
The best way to find the view controller for a react component is walk up the `nextResponder` chain from the UIView you want.

Here's some code I've used:

```objc
- (UIViewController *)sceneBackingViewController {
    RCTRootView *rootView = [self sceneReactRootView];
    if([rootView.nextResponder isKindOfClass:[UIViewController class]]) {
        return (UIViewController *)rootView.nextResponder;
    }
    return nil;
}

- (RCTRootView *)sceneReactRootView {
    UIView *parent = (UIView *)self.reactSuperview;
    while(parent != nil) {
        if([parent isReactRootView] && [parent.nextResponder isKindOfClass:[RCTRootView class]]) {
            return (RCTRootView *)parent.nextResponder;
        }
        parent = (UIView *)self.reactSuperview;
    }
    return nil;
}
```

**Comment by ssssssssssss** [comment]
@robertjpayne Thanks for your reply. How to find the uiview you mentioned in native code? Do I need to wrap react native view component for the native part or just a native API is fine?

**Comment by robertjpayne** [comment]
@ssssssssssss you'll need to create your own custom UI component with Objective-C.

http://facebook.github.io/react-native/docs/nativecomponentsios.html#content

**Comment by ssssssssssss** [comment]
@robertjpayne Thanks, it's crystal clear now.
