### ISSUE TITLE
Nested Navigators

### ISSUE THREAD

**Issue by romanonthego** [facebook/react-native#1298]
how do nested navigators works?
i've encountering some strange behaviour when nesting two Navigators: it appears root navigator not just rendering nested navigator object but instead replaced current route with initial route of child navigator.
This one couses tons of strange things.
With Navigator nesting NavigatorIOs everything is fine

**Comment by jmstout** [comment]
Nesting `Navigator` components is definitely possible. You do have to take special care to make sure you're pushing routes to the intended `Navigator`.

I've found that explicitly passing down the navigator object with properties (`parentNav={navigator}` and `childNav={navigator}`) helps clarify things.

Mind posting some code so we can see exactly where you're having trouble?

**Comment by romanonthego** [comment]
this is exactly what i did.
and while i had `NavigatorIOs` as child and `Navigator` as parent everything was fine.
But `NavigatorIOs ` `NavigationBar` isn't customisable so i've replaced `NavigatorIOs` with `Navigator`.
And strange things start to happen.

first thing related to https://github.com/facebook/react-native/issues/1155 - suddenly `componentDidFocus` was skipped on component of `parentNavigator` but called of component pushed to `childNavigator` (within the `renderScene` of `parentNavigator!`). If I remove `childNavigator` from rendering stack (replace it with any other content) - `componentDidFocus` called correctly again.

next thing is with sudden switch context of `Navigator`: `childNavigator` basically handles `ListView`, pushing to `ItemView` and pop back. After switching tabs (yep, child navigator is inside of `TabNavigation`) sometimes `backButton` works as `pop()` of `childNavigator` and sometimes as `pop()` of `parentNavigator`.

i've still digging into this mess, and will try to recreate this in example app (i could not share this particular app unfortunately).

**Comment by romanonthego** [comment]
ok. so this one most certainly have to do with `request` method ([blob](https://github.com/facebook/react-native/blob/1f8b97aeff01c8ae83a9bdb9cd0aaa18801d1523/Libraries/CustomComponents/Navigator/Navigator.js#L392)).
I'm yet to figure out why sometimes where is parentNavigator and sometimes where isn't but still.
@ide would you please help me with this one?

**Comment by ericvicenti** [comment]
Sorry to see you're having troubles here!

If you post some example code, or modify the `NavigatorExample` to show the bug, I will be able to see exactly what is going wrong and help you find a fix

**Comment by romanonthego** [comment]
actually i no longer have an issue since i've moved from tab layout to slide menu :)
all the symptoms I have here is reported in https://github.com/facebook/react-native/issues/1159:
1) switching context between navigators inside tab view in very, very unclear way - resulting back button calling pop() on parent and child navigator; 
2) skipping focus phase of parent navigator;

the bug with componentDidFocus must be related to context switching.

**Comment by ericvicenti** [comment]
It will be easier to address these issues one at a time. We should have a more specific issue for each.

I'll close this for now, but feel free to open specific issues (with example code!) and tag/assign me. Meanwhile, I am making it easier to use navigators within tabs.

**Comment by stepugnetti** [comment]
I've had a bad day trying to nest Navigator components. I seem to have discovered two interesting facts:

1. The inner Navigator component must be the only child of a View component, or it will render terribly.
2. The route components must be either View or Text (possibly with children).

Am I right? Is this documented somewhere?

Could this help with issue [#1159](https://github.com/facebook/react-native/issues/1159)?
