### ISSUE TITLE
How to handle TabBar + Modal Views?

### ISSUE THREAD

**Issue by rxb** [facebook/react-native#1299]
I'm attempting to put together navigational scheme of 
* Globally persistent Tab Bar, 
* Each Tab Item with its own Navigator 
* Occasional modal that is presented above the Tab Bar and the Navigator

It seems like Facebook Ads Manager does exactly this, but I can't figure out how. 

Thanks so much for any help you can give here!

**Comment by rxb** [comment]
After some experimenting, I think I've figured out at least one way to make this type of thing work. I'll put it here in case other people come along looking for the answer as well.

The basic idea is:
* Start the app with one top-level `Navigator` with no `navigationBar`. 
* Its initial route should be a component which includes the `TabBarIOS`. 
* Each TabBarIOS.Item should contain its own `Navigator` which does have a `navigationBar`
* Pushing routes within each tab should be handled by the `TabBar.Item`'s Navigator. 
* Pushing modal-style routes (or any view that should cover the `TabBarIOS`) should be handled by the top-level `Navigator`, which can be referenced by `this.props.navigator.parentNavigator` but it would probably be safer to pass an explicit reference.

I'll clean up my code a bit more and post it in a Gist,

**Comment by zyadsherif** [comment]
@rxb that's pretty useful am currently doing almost the same thing, if you have the gist already I'd like to take a look

**Comment by rxb** [comment]
This is using a pretty outdated version of react-native, but it should get the idea across: 
https://github.com/rxb/react-native-tabbed

**Comment by zyadsherif** [comment]
Thanks a lot :)

On Tuesday, 14 June 2016, Richard Boenigk <notifications@github.com> wrote:

> This is using a pretty outdated version of react-native, but it should get
> the idea across:
> https://github.com/rxb/react-native-tabbed
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/facebook/react-native/issues/1299#issuecomment-225944354>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABGwyjbtp-9k-aL_H48b5LbJcZZs9k-Qks5qLtxugaJpZM4Eb7FV>
> .
>


-- 

@zyadsherif <http://twitter.com/zyadsherif>
Owner
http://pinkpantherlabs.com
http://zyadsherif.com
