### ISSUE TITLE
Dynamically setting Modals visibility crashing iOS Simulator whilst debugging

### ISSUE THREAD

**Issue by hannigand** [facebook/react-native#12991]
### Description

I have a `Modal` within my React Native app which has it's `visible` prop set via a state property. When using iOS Simulator with `Debug JS Remotely` and trying to toggle the visibility, iOS Simulator crashes. When disabling debugging, the application works as expected.

Here is the error that I am receiving in my console
```
Exception 'shadowView (for ID 22) not found' was thrown while invoking replaceExistingNonRootView on target UIManager with params (
    22,
    36
)
```

Downgrading to React Native `0.41.0` seems to rectify the aforementioned problem. However, when trying clicking `Shake Gesture` on iOS Simulator, it crashes. To reproduce this, simply stop the Package Manager, change `0.42.0` to `0.41.0` in `package.json`, run a `yarn install` and once finished, `react-native run-ios`.

### Reproduction

You can find the error at https://github.com/hannigand/modal (within `index.ios.js`) - Simply clone to repository and do a `yarn install`, subsequently run `react-native run-ios`. Once iOS Simulator has opened, click on `Hardware` in the Toolbar and then `Shake Gesture`. Once the iOS menu opens, click `Debug JS Remotely` and press the `Toggle Modal` button.

### Additional Information

* React Native version: 0.42.0
* Platform: iOS
* Operating System: Mac OSX
* Dev tools: XCode 8.2.1, Chrome 56, Chrome Developer Tools,

**Comment by gemma-ferreras** [comment]
#12768
