### ISSUE TITLE
Custom animations for RKNavigator or View (Slide up/down/right/left)

### ISSUE THREAD

**Issue by jaygarcia** [facebook/react-native#130]
Is it possible to configure custom anims for RKNavigator or any View to allow them to slide in/out? 

I'm currently working on a media player and am considering the UX for it. A slide-in transition would be perfect for a "browse for file" UI a la Spotify (see below).

(Ignore the flicker. That's an artifact of Reflector)
![dfq](https://cloud.githubusercontent.com/assets/180031/6546598/7e5c50c0-c590-11e4-8496-9c8c147796f1.gif)

**Comment by vjeux** [comment]
See Navigator
