### ISSUE TITLE
React-native, Error: Execution failed for task ':app:mergeDebugResources'. > Error: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException:

### ISSUE THREAD

**Issue by prasang7** [facebook/react-native#13015]
### Description

I followed the installation steps at [react-native-getting-started](https://facebook.github.io/react-native/docs/getting-started.html). When I finally execute the last step
`react-native run-android`
I get an error message like this. 

![screenshot 3](https://cloud.githubusercontent.com/assets/13434598/24078349/2f89f0c0-0c91-11e7-8cbc-6c752f35bda5.png)

The error message says: Execution failed for task ':app:mergeDebugResources'.
> Error: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException:

Please help me fix this. Thankyou.

### Additional Information about my development environment

* I'm testing on a physical device, connecting it via USB cable.
* Device: OnePlus 2, Android Version: 6.0.1, OxygenOS: 3.5.6
* React Native version: 0.42.3* 
* React Native CLI version: 2.0.1
* Platform: Android
* Operating System: Windows 10
* Dev tools: Android Studio (v2.3)

**Comment by Nick177** [comment]
@prasang7 Hello. I am new to react-native and have undergone the installation process in the past week. I tried replicating your error, and I have found that it happens when I create a project in the same "C:\Windows\system32" directory as you have done. On the other hand, it does not give me any problems when I create and run under "C:\Users\user_name_here\". I am not sure why it does this. Try it out if this issue is still occurring.

**Comment by mikaalanwar** [comment]
Hey there! I'm new to react-native as well. A similar issue occurred for me too. To resolve it, avoid building the project in "C:\Windows\System32". It's probably due to write permissions in that area.

**Comment by prasang7** [comment]
Thankyou @Nick177 and @mikaalanwar for your suggestions. It solved my issue.

**Comment by joanprimpratrec2** [comment]
Ty . I have same problem. It solved

**Comment by huxaiphaer** [comment]
Hello guys , i have the same issue but quite different , my App was running well , it's not in the  "C:\Windows\System32" path it's in another partition but now it's bringing this error why?
And eventually it arised after adding some images in my App. Need some help.
