### ISSUE TITLE
Changing files inside `node_modules` requires restarting packager

### ISSUE THREAD

**Issue by satya164** [facebook/react-native#13019]
When I change files under node_modules, I need to restart the packager for it to pick up changes. The regression was introduced somewhere around v0.40. It becomes very difficult to debug/develop and debug libraries because of the issue.

**Comment by satya164** [comment]
cc @cpojer

**Comment by Crash--** [comment]
Since 0.39 we have some troubles with node_modules. See #11301

**Comment by lacker** [comment]
@cpojer claims this should work in a version of RN where jest-haste-map is updated to 19.x+

**Comment by satya164** [comment]
Seems it's in latest RC https://github.com/facebook/react-native/commit/570c564e77d00bbbc090acd047f04779914a5d9c#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

Maybe we could cherry-pick to stable? cc @grabbou

**Comment by grabbou** [comment]
I think it's a must as it's rather important feature. Let's discuss it tomorrow as I'll be wrapping up changelog.
