### ISSUE TITLE
Unable to resolve module  `react/lib/ReactDebugCurrentFrame`

### ISSUE THREAD

**Issue by droidwolf** [facebook/react-native#13017]
Unable to resolve module `react/lib/ReactDebugCurrentFrame` from `....\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js`: Module does not exist in the module map or in these directories:
  ...\node_modules\react\lib

**Comment by droidwolf** [comment]
When I update to 0.43.0 - rc. 1 version
`npm WARN react-native@0.43.0-rc.1 requires a peer of react@~16.0.0-alpha.3 but none was installed.`

**Comment by tigerohuang** [comment]
@droidwolf, where can I find the newest version of react and react-native such as  react@~16.0.0-alpha.3 and react-native@0.43.0-rc.1 , I only can find 0.42.3

**Comment by droidwolf** [comment]
https://github.com/facebook/react-native/releases

**Comment by ivanzotov** [comment]
+1

**Comment by wilomgfx** [comment]
I got that error as well on react ^15.4.2 and react-native 0.43, but upgrading to 16.0.0-alpha.6 fixed it. So id say.. stay away from 0.43 or use react 16.0.0-alpha.6

**Comment by itinance** [comment]
Seems that RN 0.43 shouldn't made it out of the door in this stage, particularly when essential Components like ListView got deprecated as 0.43 is not ready for serious usage yet.

**Comment by callmetwan** [comment]
I was also having trouble upgrading. I decided to start a brand new project and migrate things over as a last resort.

I get @droidwolf's error on init of a brand new project, not changing a single thing.

I'm on the latest version of MacOS and Xcode. What else am I missing?

**Comment by digitaldavenyc** [comment]
This is a library issue, clearing your restarting xcode, cleaning your build, clearing npm cache and running `react-native run-ios` fixes the issue. Not sure which one ... I really hate node libraries somtimes.

**Comment by jose2007kj** [comment]
`"react": "16.0.0-alpha.6",` this version got me working
