### ISSUE TITLE
PushNotificationIOS.requestPermissions won't resolve if no event listeners are attached

### ISSUE THREAD

**Issue by frantic** [facebook/react-native#13012]
### Description

`RCTPushNotificationManager` uses `startObserving` to register for `RCTRegisterUserNotificationSettings`. According to [the docs](https://github.com/facebook/react-native/blob/5e20b7bcfbefa9084ab6cdac9c24926ba8a64126/docs/NativeModulesIOS.md#optimizing-for-zero-listeners), the `startObserving` method won't be called until somebody subscribes to `NotificationManagerIOS`.

This means there is a scenario when the developer can call `requestPermissions` without subscribing to notifications first, but since `RCTPushNotificationManager` relies on `NSNotificationCenter` subscribtion, the result will never be returned.

This should be fairly straightforward to solve for somebody new to React Native. Feel free to send a PR!

### Reproduction

Have this in your JS file

```javascript
PushNotificationIOS.requestPermissions().then(console.log);
```

You'll see iOS permissions dialog, however pressing "Allow" won't resolve the promise and nothing will be printed to the console.

### Solution

Change the code to this, then uninstall and run the app again (needed to reset iOS permissions cache):

```javascript
PushNotificationIOS.addEventListener('localNotification', () => {});
PushNotificationIOS.requestPermissions().then(console.log);
```

Now "Allow" button will work as expected, the promise will be resolved and you'll see log entry.

### Additional Information

* React Native version: 0.42.0
* Platform: iOS
* Operating System: macOS

**Comment by binoy14** [comment]
@frantic If you are okay with it. I would like to take a stab at this.

**Comment by frantic** [comment]
@binoy14 sure!

**Comment by binoy14** [comment]
@frantic Can you point me in the right direction? I am not sure which file to edit and what exactly to do.

**Comment by frantic** [comment]
@binoy14 how familiar are you with React Native? I'd recommend starting with building a simple app that uses local notifications. Then you can try reproduce this bug locally on your computer. Once you have the repro case, check out PushNotificationsIOS native module (Objective-C) and see if you can move some event subscriptions out of `startObserving` and into methods that actually depend on them.

**Comment by cpojer** [comment]
This issue has been moved to react-native-community/react-native-push-notification-ios#3.
