### ISSUE TITLE
contentInsets always overwrites scrollIndicatorInsets of ScrollView/ListView

### ISSUE THREAD

**Issue by allenhsu** [facebook/react-native#13025]
### Description

I set `contentInsets` and `scrollIndicatorInsets` of a `ScrollView`, actually  `ListView`, to different values. But seems the value of `contentInsets` always overwrites the `scrollIndicatorInsets` one.

### Reproduction

https://sketch.expo.io/Byi2M7psg

In this demo, `scrollIndicatorInsets.top` is 20, it's expected to be 100. After deleting `contentInset={{top: 20, left: 0, right: 0, bottom: 0}}`, the `scrollIndicatorInsets` is correct.

### Solution

On line 262 of https://github.com/facebook/react-native/blob/master/React/Views/RCTView.m#L262 `scrollIndicatorInsets` is set to `baseInset` which is `contentInset` most of the time. This method is called when `setContentInset` for `RCTScrollView`.

On line 372 of https://github.com/facebook/react-native/blob/v0.42.3/React/Views/RCTComponentData.m#L372 when enumerate props, the order should not be predictable, but actually `contentInset` always comes after `scrollIndicatorInsets` during my debugging. So `contentInset` always overwrites `scrollIndicatorInsets` unless it's Zero (returned on `if (UIEdgeInsetsEqualToEdgeInsets(contentInset, _contentInset)) return`).

### Additional Information

* React Native version: 0.42.3
* Platform: iOS
* Operating System: MacOS
* Dev tools: iOS 10.2.1

**Comment by hramos** [comment]
Thanks for reporting this. Would you consider sending a PR? It seems like you've already done some of the work here.

**Comment by gastonmorixe** [comment]
Any update?

**Comment by flowkraD** [comment]
I would like to give it a shot if this still exists

**Comment by Salakar** [comment]
👋 hey all, thanks for reporting this issue. 

There was a commit some time ago (https://github.com/timotew/react-native/commit/d1b9d329314b18497a310a443ea195d88eb1e06f) that was meant to have fixed this issue, because of this I'm going to go ahead and close this issue for now. 

Should someone be able to provide a reproduction on the latest version of React Native I'd be happy to re-open this, please let me know.

Thank you

**Comment by gabrielbull** [comment]
@Salakar This bug is back, the code from the PR seems to have disappeared. Can you open the issues again?
