### ISSUE TITLE
React-native support being discontinued ?

### ISSUE THREAD

**Issue by ashubham** [facebook/react-native#13024]
Hello team,

I learnt from a friend who works at Facebook, that the project is going to be no longer maintained by facebook. In that case what will be the future of react-native ? Will it find a new home ?

**Comment by ivpusic** [comment]
what? 😄

**Comment by dottorblaster** [comment]
Maybe your friend was joking 😂

**Comment by dpeek** [comment]
Bit early for an April fools...

**Comment by OlivierCo** [comment]
Fake news lol

**Comment by phelgo** [comment]
What do you mean, that Facebook may abandon its community? I find that difficult to parse

**Comment by cesarferreira** [comment]
![img_4533](https://cloud.githubusercontent.com/assets/277426/24097348/548f7eae-0d5d-11e7-985b-3abfcf01af9b.jpg)

**Comment by mkonicek** [comment]
Hey, we're using React Native at Facebook and have an open source team to support the community. Nothing has changed. Can you ping me at mkonicek@fb.com please? I'd like to understand this concern better.

**Comment by y3n3rrr** [comment]
Baby Dont Lie - https://www.youtube.com/watch?v=9uo9oy-Eqo4
