### ISSUE TITLE
ListView does not work properly inside a ScrollView

### ISSUE THREAD

**Issue by RyanMitchellWilson** [facebook/react-native#13038]
I've got a ScrollView as one of my top level components where it needs to render a View at the top of the screen then a ListView beneath it, so that when I scroll it takes the top content with it. But whenever I try to nest my ListView inside of the ScrollView it causes everything in the ListView to be rendered no matter what props I give it. 

This is causing my app to run very slow with large lists because it is rendering every element inside my ListView instead of selectively rendering what it should based on the props I send in.

Gave my ListView a list of 200 elements with a page size of 5 but still renders all 200 elements making it very slow.

React-Native 0.41.0

**Comment by sahrens** [comment]
Nesting vertical scroll views or lists inside each other is not recommended. Ideally you should pass the view you want at the top down as a prop to the list and render it in the header. Does that not work for you for some reason?

**Comment by RyanMitchellWilson** [comment]
Well I've got a specific case but normally I would do that. My page is basically three parts with a profile info section on the top, tabs in the middle that determine the bottom content and the bottom content. I pretty much need that top and middle section to scroll with the content if the bottom content is long enough for it to scroll. And not all the content that shows at the bottom will need a ListView which is why I have the ScrollView wrapping all three components. 

I suppose I could put both sections as the header in one ListView but if I do that I would need a very complex thing making sure all my data was shaped correctly, then I would also need a complex renderRow method, which is something I was trying to avoid.

May just have to rethink how I am building my components.

**Comment by sahrens** [comment]
See my first comment - nesting them isn't really recommended. Try to make your outer ScrollView a ListView (or ideally FlatList or SectionList) with the web view and text input rendered in the header.

**Comment by mdstaff** [comment]
@sahrens Thanks for the quick reply!

**Comment by eysi09** [comment]
@sahrens Rendering all possible content above the list in the header isn't always feasible. In my case the header would need to contain several independent infinite horizontal lists and then the infinite vertical list below. Since we're using Relay this means that we have several `PaginationContainer`s inside a parent `PaginationContainer` which so far I haven't been able to get working. 

On another project the header had to contain tabs that rendered different lists. Again everything had to be stuffed in one `FlatList`/`SectionList`/`ListView` and the data manipulated manually to prevent the header from re-rendering on tab switch.

Both cases would have been easily solved if there were a way to render a list below some content and have the content scroll with the list without having the content literally inside the list component.

**Comment by sahrens** [comment]
@eysi09: perhaps renderScrollComponent would give you the control you need?

**Comment by eysi09** [comment]
@sahrens, thanks for the quick reply! Using `renderScrollComponent` does indeed help. However, that leads to the `FlatList`/`SectionList` not rendering any rows beyond the initial ones. Same as this issue: #8467.

But it seems like to way to go if the issue above gets solved (or if I'm missing something). For those interested, an implementation would look some like this:

```
const MyList = props => (
  <FlatList
    data={props.data}
    keyExtractor={listItem => listItem.id}
    renderItem={props.renderItem}
    renderScrollComponent={() => <CustomScrollComp />}
  />
);

// Using class so that FlatList can use the ref.
class CustomScrollComp extends Component {
  render() {
    return (
      <ScrollView>
        <MyHeader />
        {this.props.children}
      </ScrollView>
    );
  }
}
```

**Comment by sahrens** [comment]
You need to make sure all of the other props are forwarded to the ScrollView instance. See the default renderScrollComponent implementation in VirtualizedList for an example:

https://github.com/facebook/react-native/blob/a48da14800013659e115bf2b58e31aa396e678e5/Libraries/Lists/VirtualizedList.js#L845-L873

**Comment by eysi09** [comment]
I see. Thank you!
