### ISSUE TITLE
RCTAdSupport uses advertisingidentifier which triggers Apple's automated detection upon submit

### ISSUE THREAD

**Issue by jimmystridh** [facebook/react-native#1303]
I just submitted an app to the AppStore earlier today, and I had to remove the implementation of the two methods in RCTAdSupport as to not trigger Apple's automated advertisingidentifier detection (https://github.com/facebook/react-native/blob/master/Libraries/AdSupport/RCTAdSupport.m#L20). They force you to explain why you are using advertisingIdentifier if they detect it (and might reject you if you're not using ads).

Perhaps this should be in the docs, or toggled via an ifdef if you actually use ads?

(Apple about advertisingIdentifier https://developer.apple.com/news/?id=08282014a)

**Comment by jimmystridh** [comment]
Perhaps obfuscating the usage with NSClassFromString could be a workaround as not to trigger the automated detection.

**Comment by ide** [comment]
The best fix is for the sample project to not link in AdSupport. Only apps that track users across different apps made by different companies require it.

**Comment by shayne** [comment]
Apple has made it pretty clear if you're not serving ads don't think about using the advertisingIdentifier. IIRC they'll detect the call at runtime so no matter how you obfuscate the message, if in the end you're calling advertisingIdentifier they'll flag it.

**Comment by robertjpayne** [comment]
I think the idea is that the obfuscation will prevent rejected apps from people that are not using the identifier.

However the app will still then be linked to the AdSupport.framework which may raise some eyebrows.
