### ISSUE TITLE
Failed propType: Invalid props.style key 'color' supplied to [ 'View' | 'RCTView' ] 

### ISSUE THREAD

**Issue by manjula91** [facebook/react-native#13044]
### Warning: Failed propType: Invalid props.style key 'color' supplied to [ 'View' | 'RCTView' ] 

I used color property in react native app and it gives above error.

### Reproduction

You can reproduce the issue 

```
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    color:'white',
    justifyContent: 'center',
  },
});
```

### Additional Information

* React Native version: [0.43]
* Platform: [Android]
* Operating System: [MacOS]
* Dev tools: [ Android SDK version using genymotion for emulator]
![screen shot 2017-03-21 at 10 00 55 am](https://cloud.githubusercontent.com/assets/7845921/24132698/786b112e-0e1d-11e7-9714-717ec6a86023.png)

**Comment by yumengbdw** [comment]
backgroundColor

**Comment by danielbrodin** [comment]
You have to set the `color` style directly on a `Text` component for it to be white. Child components does not inherit style like on the web.

**Comment by hramos** [comment]
What they said - set the color on the Text element. Be aware you're using a white background color on the View container, you'll probably want to use a different color for the text.

**Comment by manjula91** [comment]
Thanks issue is resolved
