### ISSUE TITLE
undefined is not a function (evaluating 'I.hasOwnProperty("process")')

### ISSUE THREAD

**Issue by Mackenzie-Mance** [facebook/react-native#13041]
Couldn't find any leads on the net to this issue. I'm pretty new to this so sorry in advance for any lack of information. I started getting this error when i updated npm. the project works in debug mode but throws this error otherwise.

Thank you.

![screenshot_1490062591](https://cloud.githubusercontent.com/assets/24738013/24129755/10383b3e-0dbb-11e7-8384-60fdcf04e83b.png)

{
  "name": "firstrnproject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node_modules/react-native/packager/packager.sh/"
  },
  "dependencies": {
    "firebase": "^3.6.4",
    "lodash": "^4.17.2",
    "react": "^15.4.2",
    "react-addons-create-fragment": "^15.4.2",
    "react-native": "^0.42.3",
    "react-native-animatable": "^1.1.0",
    "react-native-button": "^1.7.1",
    "react-native-camera": "git+https://github.com/lwansbrough/react-native-camera.git",
    "react-native-collapsible": "^0.8.0",
    "react-native-datepicker": "^1.4.4",
    "react-native-facebook-login": "^1.4.0",
    "react-native-gifted-chat": "^0.1.3",
    "react-native-google-places-autocomplete": "^1.2.8",
    "react-native-image-crop-picker": "^0.10.9",
    "react-native-image-picker": "^0.24.1",
    "react-native-linear-gradient": "^1.5.15",
    "react-native-maps": "^0.12.2",
    "react-native-modalbox": "^1.3.8",
    "react-native-overlay": "^0.5.0",
    "react-native-router-flux": "^3.37.0",
    "react-native-scrollable-tab-view": "^0.7.0",
    "react-native-tab-navigator": "^0.3.3",
    "react-native-tabs": "^1.0.9",
    "react-native-toggle": "^1.0.3",
    "react-native-vector-icons": "^3.0.0",
    "react-redux": "^4.4.6",
    "redux": "^3.6.0",
    "redux-logger": "^2.7.4",
    "redux-storage": "^4.1.2",
    "redux-storage-engine-reactnativeasyncstorage": "^1.0.5",
    "redux-thunk": "^2.1.0",
    "whatwg-fetch": "^2.0.1"
  }
}

**Comment by g6ling** [comment]
I met same error. How did you solve this error?

**Comment by ncuillery** [comment]
Upgrading `firebase` to the latest (3.7.6) has solved the problem for me.

**Comment by g6ling** [comment]
@nucleartux thanks. I solved this problem.

**Comment by nucleartux** [comment]
@ncuillery :)
