### ISSUE TITLE
FlatList not found/exported => Docs not in-sync with current release

### ISSUE THREAD

**Issue by Ragnaroek** [facebook/react-native#13045]
### Description

Tried to use FlatList in a new app.
Documentation https://facebook.github.io/react-native/docs/flatlist.html describes it for the 
current native version 0.43.x.

Neither
const ReactNative = require('react-native')
const {
  FlatList
} = ReactNative;

nor ES6 imports

import {
  ...,
  FlatList
} from 'react-native';

are possible.

### Reproduction
I basically tried to run this example in a new created project:
https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/FlatListExample.js

### Solution
Looking at /Users/mb/pprojects/defmacro_shoppinglist/node_modules/react-native/Libraries/react-native/react-native.js
there is no export of FlatList?
Version is 0.42.3
=> oh well, I now see the problem. FlatList is introduced in 0.43! But this version is not released yet! Could you please update the documentation in-sync with react-native releases. This makes it very confusing (I'm just started to use react-native..).

### Additional Information

* React Native version: 0.42.3
* Platform: iOS (but doesn't matter)
* Operating System: MacOS
* Dev tools: Xcode

**Comment by ide** [comment]
cc @hramos - it looks like the 0.43 are considered stable even though it's still in RC.

**Comment by hramos** [comment]
0.43 was incorrectly tagged as stable yesterday. This should be fixed already but a new website deploy hasn't gone out yet due to Circle being red.

**Comment by hramos** [comment]
Alright, this is now fixed. It required a manual deploy of the website to ensure 0.42 was listed as latest stable.
