### ISSUE TITLE
Possible duplicate imports of RCTBridge

### ISSUE THREAD

**Issue by mauron85** [facebook/react-native#13047]
### Description

Some modules may import both React/RCTBridge.h and React/RCTEventDispatcher.h.
As RCTEventDispatcher is already importing RCTBridge and RCTBridge doesn't contain any `ifndef` guard to not allow importing itself multiple time, build will fail.

### Reproduction

Taken from [react-native-background-geolocation module](https://github.com/mauron85/react-native-background-geolocation/blob/9d83368039aed26f88d812247b43c10af3ea0904/ios/RCTBackgroundGeolocation/RCTBackgroundGeolocation.m
) 
```
#if __has_include("RCTBridge.h")
#import "RCTBridge.h"
#else
#import <React/RCTBridge.h>
#endif
#if __has_include("RCTEventDispatcher.h")
#import "RCTEventDispatcher.h"
#else
#import <React/RCTEventDispatcher.h>
#endif
```

More details in issue: https://github.com/mauron85/react-native-background-geolocation/issues/44

### Solution

Add `#ifndef RCTBridge_h` guard to to RCTBridge.h

### Additional Information

* React Native version: 0.41

**Comment by ide** [comment]
The #import pragma defends against this, this isn't #include. There's something misconfigured with your project.

**Comment by mauron85** [comment]
@ide obviously you're right. Must be problem in my project.
