### ISSUE TITLE
searchPaths.filter is not a function

### ISSUE THREAD

**Issue by pvinis** [facebook/react-native#13051]
https://github.com/rnpm/rnpm-plugin-link/issues/94

**Comment by pvinis** [comment]
why just close it? there is enough info in the link. what is the problem?

**Comment by hramos** [comment]
See the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md) - issues that do not fill this out will be closed without explanation.

**Comment by pvinis** [comment]
ok then tomorrow i will just copy the other issue here i guess. the link has the "template".
