### ISSUE TITLE
UnableToResolveError: Unable to resolve module `BackHandler`

### ISSUE THREAD

**Issue by thiensubs** [facebook/react-native#13054]
### Description
![image](https://cloud.githubusercontent.com/assets/2623569/24158240/4deb9b1e-0e8e-11e7-80d6-9e80e54eab38.png)
This is my issue, how can i fix that?
More details: 

```
at UnableToResolveError (/xxx/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:488:5)
    at /xxx/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:366:19
    at process._tickCallback (node.js:368:9)

```
My enviroment is: Xubuntu 16.04, Lasted NPM, RN: 0.42.3

**Comment by EgaSetya** [comment]
How can you solve this?

**Comment by AkshatSharda** [comment]
This Issue can  be resolved by setting the same version for react-native and react-native-windows.
"react-native": "0.43.0"
"react-native-windows": "0.43.0-rc.0"
By setting the above version, i was able to resolve the issue
