### ISSUE TITLE
React-Native 0.43-rc4 depends on React-0.16-alpha-3

### ISSUE THREAD

**Issue by cgestes** [facebook/react-native#13063]
Hi,

What's going on with the dependency on React for the next RN release?

Right now 0.43-rc4 is pointing to an alpha version of React.

ping @acdlite

**Comment by chandu0101** [comment]
facebook is using `react`-`master` in production! :)

**Comment by jinlong** [comment]
How to upgrade to React-Native 0.43-rc4?

**Comment by cgestes** [comment]
React-native have been released with a dep on React 0.16-alpha.

Let's close.
