### ISSUE TITLE
Please add onEndReachedThreshold to SectionList component

### ISSUE THREAD

**Issue by rqzheng2015** [facebook/react-native#13070]
After reading the SectionList APIs on https://facebook.github.io/react-native/releases/next/docs/sectionlist.html, I still don't know how to make "Scroll loading" without passing param "onEndReachedThreshold" to SectionList which was provided at Listview and FlatList component, can i have any suggestions on making scroll loading in SectionList work? THX!

**Comment by hramos** [comment]
Thanks for opening the issue, however it looks like a feature request. As noted in the [Issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md) we'd like to use the GitHub issues to track bugs only. Consider sending a pull request or a create an entry on [Canny](https://reactnative.canny.io/feature-requests). It has a voting system and if the feature gets upvoted enough it might get implemented by someone from the community. Closing this now, thanks for understanding!

**Comment by rqzheng2015** [comment]
I know how to solve this, you just need to set onEndReachedThreshold as a rate of visibleLength.
So you just need to set it as a number smaller than 1, then it worked!!!!!
