### ISSUE TITLE
'await' is a reserved keyword

### ISSUE THREAD

**Issue by seenickcode** [facebook/react-native#13074]
This example doesn't work.

http://facebook.github.io/react-native/docs/asyncstorage.html#content

"'await' is a reserved keyword" is displayed.

**Comment by davidsharp** [comment]
It's because that snippet should be in an `async` function.

**Comment by seenickcode** [comment]
Strange. It seems it's not.  See this official example.
http://facebook.github.io/react-native/docs/asyncstorage.html#content

**Comment by ericvicenti** [comment]
Can you please send a pull request with the fix?

**Comment by davidsharp** [comment]
@seenickcode, I can see it's not there, but that's how async/await works.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await

It's certainly something that should be clearer in the docs, but it's not a React Native issue specifically.

**Comment by seenickcode** [comment]
Good to know thanks.  It's just that it's in the React Native main
documentation and that example they give clearly doesn't work for newbies
like me.  Not to be negative but it's surprising from the quality of
documentation Facebook produces.  I couldn't find how to report a problem
with documentation.

**Comment by hramos** [comment]
Most of the documentation is hosted in this repo, in the `docs/` directory. The API reference docs are generated from the JavaScript comments in the source files itself.

A good way to report a problem with documentation on React Native is just like this - by opening an issue in the GitHub tracker. A pull request would be ideal, however!

**Comment by seenickcode** [comment]
Ok noted.  Thank you!

**Comment by at-vinhhuynh** [comment]
it should be in an `async` `function`, I resolved this issue :1st_place_medal:

**Comment by veb** [comment]
If one scrolls down to the examples (http://facebook.github.io/react-native/docs/asyncstorage.html#examples) it shows you how to properly format it so that it works properly.

**Comment by Tanumay92** [comment]
I am getting error saying "await is a reserved word". My code pasted below. Please help me if anyone has any solution.

    getDistance=async()=>{
         var value=await AsyncStorage.getItem('id');
        const intervalId=BackgroundTimer.setInterval(()=>{
        var pos_lat;
        var pos_lon;
        navigator.geolocation.getCurrentPosition((position)=>{
            pos_lat=parseFloat(position.coords.latitude);
            pos_lon=parseFloat(position.coords.longitude); 
            var params_1={
            id:value,
            lat:pos_lat,
            lon:pos_lon
        };
        var formData_1=new FormData();
         for (var k in params){
         formData.append(k,params[k]);
        }
        var request_1={
            method:'POST',
            headers:{
                'X-API-KEY':'api0098911sales'
            },
            body:formData_1
        }
        var url_sendloc="http://sugoifit.in/Salesman_Tracking/index.php/api/Add_Location/add_location";
       
        var response_current=await fetch(url_sendloc,request_1);
        var json_response_current=await response_current.json();

        if(json_response_current.status=='true')
           {
            ToastAndroid.showWithGravity('Location sent!',ToastAndroid.CENTER,ToastAndroid.LONG); 
           }
           else{
             ToastAndroid.showWithGravity('Location cannot be added',ToastAndroid.CENTER,ToastAndroid.LONG);
           }  
         },
        (error)=>{
            console.log(error)
        },
        {enableHighAccuracy:false, timeout:2000, maximumAge:10000}
        );
      },10000);

**Comment by Tanumay92** [comment]
This is my code below.I am getting error of await is a reserved word. Please help me on this.

getDistance=async()=>{

      
     var value=await AsyncStorage.getItem('id');
    const intervalId=BackgroundTimer.setInterval(()=>{
    var pos_lat;
    var pos_lon;
    navigator.geolocation.getCurrentPosition((position)=>{
        pos_lat=parseFloat(position.coords.latitude);
        pos_lon=parseFloat(position.coords.longitude); 
        var params_1={
        id:value,
        lat:pos_lat,
        lon:pos_lon
    };
    var formData_1=new FormData();
     for (var k in params){
     formData.append(k,params[k]);
    }
    var request_1={
        method:'POST',
        headers:{
            'X-API-KEY':'xxxxxxxxxx'
        },
        body:formData_1
    }
    var url_sendloc="xxx.cm/xx/xx";
   
    var response_current=await fetch(url_sendloc,request_1);
    var json_response_current=await response_current.json();

    if(json_response_current.status=='true')
       {
        ToastAndroid.showWithGravity('Location sent!',ToastAndroid.CENTER,ToastAndroid.LONG); 
       }
       else{
         ToastAndroid.showWithGravity('Location cannot be added',ToastAndroid.CENTER,ToastAndroid.LONG);
       }  
     },
    (error)=>{
        console.log(error)
    },
    {enableHighAccuracy:false, timeout:2000, maximumAge:10000}
    );
  },10000);

**Comment by MrNicodemuz** [comment]
Documentation is still outdated as of today.
