### ISSUE TITLE
App gets closed when Remote JS Debugging is enabled

### ISSUE THREAD

**Issue by vldgeorgiev** [facebook/react-native#13090]
### Description
When the JS Debugging is started from the Dev menu, the app on the mobile gets closed on its own after a while. It does not happen immediately, but after a minute or two, sometimes after 20-30 seconds.
It only happens if there is a debugger actually attached. If the option is enabled, but the debugger is closed immediately, the app runs as it should. E.g. if the Chrome window localhost:8081/debugger-ui is closed, or whatever other debugger is used.
It doesn't sound like a feature to me, so I suppose it is a bug somewhere. Maybe it is not in react-native itself, I'm not sure. But it definitely makes the logging and debugging much harder.
This happens on an Android 6.0 device connected by USB, not on an emulator.

### Reproduction
1. Create a new project with "react-native init ..."
2. Run it with "react-native run-android"
3. Open the Dev menu on the device and start the remote JS debugging.
4. This will open Chrome to the debugger-ui page (or some other debugger). Don't close the page and wait for a few minutes. The app will close on the mobile on its own.

### Additional Information

* React Native version: 0.42
* Platform: Android
* Development Operating System: Windows 7
* Dev tools: adb is v1.0.36, Android SDK platform-tools 25.0.3

**Comment by rodperottoni** [comment]
There's already an issue for this: #9665

**Comment by vldgeorgiev** [comment]
Thanks. It is exactly the same behaviour. I read the comments, but unfortunately after 7 months the issue is still there and it is a major one.

**Comment by salvagit** [comment]
kill $(lsof -t -i:8081) works for me.
