### ISSUE TITLE
[PermissionsAndroid] request is not prompting and always return true

### ISSUE THREAD

**Issue by Blapi** [facebook/react-native#13097]
### Description

I want to use the camera in my react-native application on Android. For this, I'm using the Camera from https://github.com/lwansbrough/react-native-camera.

So, in order to this, i'm using PermissionsAndroid to make sure that the user has the access to the camera. Here comes my problem.

I'm using the code from the doc (here https://facebook.github.io/react-native/docs/permissionsandroid.html) to do the request permission on camera and I'm having an issue with this as it never asks me to allow the camera and always returns true, even if I disable the camera permission on my device.

Here is the scenario when camera permission access is granted :

![17474142_10213255883420181_780649716_o](https://cloud.githubusercontent.com/assets/3853597/24225340/211ad1e2-0f1d-11e7-904a-83655c7b083f.png)
![17455229_10213255883380180_703171875_o](https://cloud.githubusercontent.com/assets/3853597/24225338/211a44ac-0f1d-11e7-8c86-6fb807ede6fa.png)

Here is the scenario when camera permission access is not granted :

![17475238_10213255884100198_166958326_o](https://cloud.githubusercontent.com/assets/3853597/24225339/211a76b6-0f1d-11e7-870d-edd52e0d7f97.png)
![17475223_10213255884140199_1657109422_o](https://cloud.githubusercontent.com/assets/3853597/24225341/211c3bea-0f1d-11e7-8aee-2087d37d6a44.png)

### Reproduction

What I'm doing is simply this : 

```
export async function requestCameraPermission() {
  try {
    const granted = await PermissionsAndroid.request(
      PermissionsAndroid.PERMISSIONS.CAMERA,
      {
        'title': 'Cool Photo App Camera Permission',
        'message': 'Cool Photo App needs access to your camera ' +
                   'so you can take awesome pictures.'
      }
    )
    if (granted === PermissionsAndroid.RESULTS.GRANTED) {
      console.log("You can use the camera")
    } else {
      console.log("Camera permission denied")
    }
  } catch (err) {
    console.warn(err)
  }
}
```
```
  async componentWillMount() {
    await requestCameraPermission() // which always returns "You can use the camera" even if I disable camera permission access on my device
  }
```

### Additional Information

* React Native version: 0.40
* Platform: Android 7.1.1
* Development Operating System: Linux (Ubuntu 16.04)
* Dev tools: android:minSdkVersion="16" android:targetSdkVersion="23"

I'm also experiencing this issue using https://github.com/yonahforst/react-native-permissions/ : https://github.com/yonahforst/react-native-permissions/issues/86

**Comment by daniel90daniel** [comment]
Hi, I had the same problem.
I solved it by changing the targetSdkVersion ( same to compileSdkVersion, in my case 23) in  android/app/build.gradle.

**Comment by Blapi** [comment]
Much thanks @daniel90daniel  !!!!!!

I did what you did and this is now working perfectly !

If some guys are experimenting the same issue, be careful because as I said in my issue, my dev tools are android:minSdkVersion="16" android:targetSdkVersion="23" BUT those are the infos in my AndroidManifest.xml... in my android/app/build.gradle, the targetSdkVersion was 22 and not 23, and putting it to 23, as @daniel90daniel said, makes it work for me now !

**Comment by TrustTheBoy** [comment]
@Blapi SDK <23 returns true, can not judge

**Comment by Blapi** [comment]
@TrustTheBoy I don't know what you mean, I just had this issue because I was using a targetSdkVersion < 23, just setting it to 23 and everything worked for me. The user can now choose to allow/decline permissions because before that, it was granted automatically, even the dangerous ones.

**Comment by TrustTheBoy** [comment]
@Blapi  if SDK< 23 PermissionsAndroid returns the result is always true, if so, Android 6.0 before the device can not detect whether the user manually closed the permissions

**Comment by TrustTheBoy** [comment]
@Blapi According to your method, `targetSdkVersion` = 23 after, and did not solve, China's Android device there are most users of the system version is 6.0 before

**Comment by aronse** [comment]
@TrustTheBoy ???

**Comment by TrustTheBoy** [comment]
@aronse I just want to say android 6.0 before the device how to detect, and no other meaning

**Comment by aziz-boudi4** [comment]
@TrustTheBoy I guess we cannot trust you

**Comment by aronse** [comment]
Oh ok I see @TrustTheBoy thanks for the explanation it's crystal clear 👍👍

**Comment by TrustTheBoy** [comment]
You do not believe me, hey, what am I doing wrong? Gentlemen, I did not lie to you 😭😭😭😭

**Comment by amitpadmani** [comment]
First time user  permission given, but every time it go into to else  "show  Read Phone State permission denied"

  try {
      const granted = PermissionsAndroid.request(
        PermissionsAndroid.PERMISSIONS.READ_PHONE_STATE,
        {
          'title': 'Read Phone State Permission',
          'message': 'To access you device data we needs access to Phone State '
        }
      )

      console.warn("DFA = ",granted)
      if (granted === PermissionsAndroid.RESULTS.GRANTED) {
        console.log("Device Unique ID", DeviceInfo.getUniqueID());
        
        console.log("Device Manufacturer", DeviceInfo.getManufacturer());
        
        console.log("Device Model", DeviceInfo.getModel());
        
        console.log("Device Name", DeviceInfo.getSystemName());
        
        console.log("Device Version", DeviceInfo.getSystemVersion());
        
        console.log("Bundle Id", DeviceInfo.getBundleId());
        
        console.log("Build Number", DeviceInfo.getBuildNumber());
        
        console.log("App Version", DeviceInfo.getVersion());
        
        console.log("App Version (Readable)", DeviceInfo.getReadableVersion());
      } else {

        console.log("Read Phone State permission denied")
      }
    } catch (err) {

      console.log("errr",err)
      
    }

**Comment by Blapi** [comment]
This is because PermissionsAndroid.request returns a promise, you should put your method as async and await PermissionsAndroid.request as it still clearly stipulated on the doc.

https://facebook.github.io/react-native/docs/permissionsandroid.html

**Comment by amitpadmani** [comment]
Thanks Blapi,

But when i function as async  it will give error , " Unexpected Token" 
please check below Image

![screenshot from 2017-09-13 18-44-46](https://user-images.githubusercontent.com/10232335/30379409-013d5090-98b4-11e7-86b3-3a1a2fafab4e.png)

**Comment by Blapi** [comment]
https://stackoverflow.com/questions/43070702/typescript-unexpected-token-a-constructor-method-accessor-or-property-was-exp

**Comment by nitin0331** [comment]
Hi ,
In my case its always return true and alert 

> "You can use the camera..1."

export default class Tab3 extends Component {
async requestCameraPermission(){
  if(Platform.OS === 'ios'){
 alert("You can use the camera ios");
  }else{
    const chckCamera =PermissionsAndroid.check(PermissionsAndroid.PERMISSIONS.CAMERA);
if(chckCamera === PermissionsAndroid.RESULTS.GRANTED){
  alert("You can use the camera..0.");
  }else{
 try {
    const granted = await PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.CAMERA,
      {
        'title': 'Cool Photo App Camera Permission',
        'message': 'Cool Photo App needs access to your camera ' +
                   'so you can take awesome pictures.'
      }
    )
    if (granted === PermissionsAndroid.RESULTS.GRANTED) {
      alert("You can use the camera..1.");
    } else {
      alert("Camera permission denied");
    }
  } catch (err) {
    alert(err)
  }

  }

  }

}; 



	render() {
		return (

<Container>
    <Content >

<Button block rounded onPress = {() => this.requestCameraPermission()} >
            <Text>Camera</Text>
          </Button>


 </Content >

      </Container>



		);
	}


}

compileSdkVersion 26
buildToolsVersion "26.0.1"
Android Emulator-Android Oreo 8.0.0

Can some check where i have done wrong or missed anything ?

**Comment by fahidmohammad** [comment]
@nitin0331 have you got any solution for the reported case? I'm stuck with it too.

**Comment by nitin0331** [comment]
@fahidmohammad the same code i have mentioned above start working after i have changed in gradle file of the android app.
minimum compilesdk/build too  version should be 23 .
Hope this will help.

**Comment by fahidmohammad** [comment]
@nitin0331 downgrading the version was never a solution for me, but luckly i've got a better [ fix here.](https://medium.com/react-native-development/fixing-problems-in-react-native-caused-by-new-permission-model-on-android-1e547f754b8)

> but the weird thing is that i have integrating camera and its take 2 days and still lots more error in react-camera . So if you can help me on the same. 

I believe the permission if what you are referring to? or could you share more info what exactly you the issue you are facing?
