### ISSUE TITLE
Possibility for Z-Indexing (layers)?

### ISSUE THREAD

**Issue by jaygarcia** [facebook/react-native#131]
Web developers have been accustomed to dealing with plain HTML to represent UI, which gives us the ability to generate layers via Absolute Positioning and z-indexing. 

Do you guys plan on implementing Z-indexing or absolute positioning?

**Comment by Iragne** [comment]
well i agree with you @vjeux  but the fact that we need some time to put a view in the front or in the back what ever the position in the DOM. and position absolute is not the solution for that

**Comment by Iragne** [comment]
Well i know it's closed but it's very useful to have these properties bringSubviewToFront and inverse 

See The PR https://github.com/facebook/react-native/pull/1891
