### ISSUE TITLE
State Error in TextInput Sample

### ISSUE THREAD

**Issue by tk130** [facebook/react-native#13108]
### Description
I'm not working with the emulator. I have my mobile phone connected and run the Application on this. I tried out the following source code: https://facebook.github.io/react-native/docs/handling-text-input.html 
Just by copy and paste and changed all 'PizzaTranslator' to the actual name of my project. I activated hot reload. When I saved the Code I  expected the same view as shown in the link. Unfortunately all I got was a red screen giving follwoing hint: null is not an object (evaluating 'this.state.text'). 

### Reproduction
All the Code thats out of the link with the edited class name:

import React, { Component } from 'react';
import { AppRegistry, Text, TextInput, View } from 'react-native';

class FirstApp extends Component {
  constructor(props) {
    super(props);
    this.state = {text: ''};
  }

  render() {
    return (
      <View style={{padding: 10}}>
        <TextInput
          style={{height: 40}}
          placeholder="Type here to translate!"
          onChangeText={(text) => this.setState({text})}
        />
        <Text style={{padding: 10, fontSize: 42}}>
          {this.state.text.split(' ').map((word) => word && '🍕').join(' ')}
        </Text>
      </View>
    );
  }
}

AppRegistry.registerComponent('FirstApp', () => FirstApp);

### Additional Information

* React Native version: 0.42
* Platform: Android, didn´t try IOS
* Development Operating System: Windows

**Comment by tk130** [comment]
Allright, when I restart everything, that means: I start the command line again with react-natve start and react-native run-android, reconnect the phone, it works. Whats the problem?

**Comment by Kureev** [comment]
@facebook-github-bot icebox
