### ISSUE TITLE
for SegmentedControlIOS component,onChange(event),event.nativeEvent =null

### ISSUE THREAD

**Issue by donghanji** [facebook/react-native#1310]
for SegmentedControlIOS component,when used onChange event,the callback param event,event.nativeEvent is null,no selectedIndex attribute.
<pre>
var EventSegmentedControlExample=React.createClass({
  getInitialState(){
    return {
      values:['One','Two','Three'],
      value:'Not selected',
      selectedIndex:undefined
    };
  },
  render(){
    return(
      &lt;View&gt;
        &lt;Text style={styles.text}&gt;
          Value:{this.state.value}
        &lt;/Text&gt;
        &lt;Text style={styles.text}&gt;
          Index:{this.state.selectedIndex}
        &lt;/Text&gt;
        &lt;SegmentedControlIOS
          values={this.state.values}
          selectedIndex={this.state.selectedIndex}
          onChange={this._onChange}
          onValueChange={this._onValueChange}
        /&gt;
      &lt;/View&gt;
    );
  },
_onChange(event){
    console.log(event);//debug console log here
    this.setState({
      selectedIndex:event.nativeEvent.selectedIndex
    });
  },
  _onValueChange(value){
    this.setState({
      value:value
    });
  }
});

//render EventSegmentedControlExample
//<EventSegmentedControlExample/>
</pre>

this is console log:
<pre>
_dispatchIDs: null,
_dispatchListeners: null,
bubbles: nullcancelable: null,
currentTarget: null,
defaultPrevented: null,
dispatchConfig: null,
dispatchMarker: null,
eventPhase: null,
isDefaultPrevented: function () {},
isPropagationStopped: function () {},
isTrusted: null,
nativeEvent: null,//there is null
target: null,
timeStamp: null,
type: null
</pre>

the SegmentedControlIOS is a new component,is this an bug?

**Comment by yangxf** [comment]
use event.nativeEvent.selectedSegmentIndex

**Comment by christopherdro** [comment]
@donghanji Did this resolve your issue?

**Comment by brentvatne** [comment]
@yangxf's [answer is correct](https://rnplay.org/plays/zibrKw?autoplay=true)

**Comment by donghanji** [comment]
thanks everyone ^_^.sorry to being late.
change the code ,like this:
<pre>
var EventSegmentedControlExample=React.createClass({
  getInitialState(){
    return {
      values:['One','Two','Three'],
      value:'Not selected',
      selectedIndex:undefined
    };
  },
  render(){
    return(
      &lt;View&gt;
        &lt;Text style={styles.text}&gt;
          Value:{this.state.value}
        &lt;/Text&gt;
        &lt;Text style={styles.text}&gt;
          Index:{this.state.selectedIndex}
        &lt;/Text&gt;
        &lt;SegmentedControlIOS
          values={this.state.values}
          <b>selectedSegmentIndex</b>={this.state.selectedIndex}
          onChange={this._onChange}
          onValueChange={this._onValueChange}
        /&gt;
      &lt;/View&gt;
    );
  },
_onChange(event){
    console.log(event);//1:debug console log here
    console.log(event.nativeEvent);//2:debug console log
    this.setState({
      selectedIndex:event.nativeEvent.<b>selectedSegmentIndex</b>
    });
  },
  _onValueChange(value){
    this.setState({
      value:value
    });
  }
});
//
</pre>

after changed ,work well.but there is another question:
when debug console in onChange event,
1:debug console,output null,
2:debug console,output the correct result,an object {}.
why???

Whether those changes  should be updated，<a href="http://facebook.github.io/react-native/docs/segmentedcontrolios.html#content">http://facebook.github.io/react-native/docs/segmentedcontrolios.html#content</a>

thanks everyone again.
