### ISSUE TITLE
Expected ')' in RCTProfile.m

### ISSUE THREAD

**Issue by maggialejandro** [facebook/react-native#13115]
### Description
Expected ')' in [RCTProfile.m](https://github.com/facebook/react-native/blob/ba149d72772111758b12b76db56c60dea5b1ef26/React/Profiler/RCTProfile.m#L399)

![rctprofile](https://cloud.githubusercontent.com/assets/3394748/24252330/ed322020-0fbb-11e7-91af-7e2ea376ce1f.png)

Related issue #13020 

### Reproduction
Product Clean
Product Run

### Additional Information
* React Native version: 0.42.0
* Platform: iOS
* Development Operating System: OSX 10.11.4
* Dev tools: XCode 7.3.1

**Comment by javache** [comment]
Please install Xcode 8.2, UIAcitivityType is part of the iOS10 SDK.
