### ISSUE TITLE
ListView RefreshControl - Unable to pull to refresh if empty

### ISSUE THREAD

**Issue by quangas** [facebook/react-native#13110]
### Description

When a ListView is empty, there is no way to do a pull down to refresh with the RefreshControl. I have no other event triggered option to refresh besides pull down to refresh. How can I get around this?

```
<ListView
            dataSource={this.state.datasource}
            renderRow={this._renderRow}
            refreshControl={
              <RefreshControl
                refreshing={this.state.refreshing}
                onRefresh={this._onRefresh} />
            } />
```

### Additional Information

* React Native version: 0.41
* Platform: Android
* Development Operating System: MacOS
* Dev tools: Android Studio

**Comment by wjm117** [comment]
Now my project has the same problem,Have you Fixed it?

**Comment by quangas** [comment]
No fix but I just created a button to reload if the content if is empty.

So basically 

`if (this.state.datasource.getRowCount() == 0) { 
<View>
 <Text>No content</Text>
 <Button onClick={this. _onRefresh.bind(this)}>Click to refresh</Button>
</View> 
} else 
{ 
 <ListView ....... ></ListView> 
} 
`

**Comment by AndreyMalykhin** [comment]
Version 0.51, applies to FlatList as well. Comment above is more like a workaround, IMO this should be fixed within the core, empty list is still a list.

**Comment by Shu-Ji** [comment]
Hi, guys, you can solve like this:

When the data is empty, **the height of ListView is 0** if you haven't set its style before.

So set the `minHeight` of `ListView` to a value(e.g. the screen height) will solve this:

And set the style of `empty_btn` to make it transparent and float on the top of ListView.

```coffeescript
import { Dimensions } from 'react-native'

class PostList extends React.Component

    render: ->
        empty_btn = null
        if @state.posts.length == 0
            empty_btn = (
                <Text 
                    onPress={@refresh}
                    style={
                        position: 'absolute'
                        top: 0
                        left: 0
                        backgroundColor: 'rgba(0, 0, 0, 0)'
                }>Pull or Click to refresh</Text>
            )

        return (
            <View>
                { empty_btn }
                <ListView
                    ...
                    style={
                        minHeight: Dimensions.get('window').height
                    }
                />
            </View>
        )
```
