### ISSUE TITLE
LayoutAnimation with transform

### ISSUE THREAD

**Issue by smothers** [facebook/react-native#1311]
Can a transform be used in a LayoutAnimation?

I've tried this, but the transform is not tweened. It just snaps to the new position.
```javascript
LayoutAnimation.configureNext(animations.layout.spring);

this.setState({ 
  someViewStyleOverride: { 
    transform: [{translateX: 100}, {translateY: 100}]
  }
});

var animations = {
  layout: {
    spring: {
      duration: 750,
      update: {
        type: LayoutAnimation.Types.spring,
        springDamping: 0.4,
      },
    },
  },
};
```

**Comment by sahrens** [comment]
Transforms aren't part of layout, they are applied on top of it. You'll need to use a different animation mechanism.

We'd like to build a more general transactional animation mechanism that will animate all animatable properties including tranforms, but it's not built yet. Would be happy to see a PR :)

**Comment by smothers** [comment]
Thanks @sahrens. I ended up using [kirkness/react-native-tween-animation](https://github.com/kirkness/react-native-tween-animation). It's not 60fps, but it works as a band-aid.

**Comment by sahrens** [comment]
We'll have some better options for you soon ;)
