### ISSUE TITLE
Unexpected token '>' 

### ISSUE THREAD

**Issue by iremlopsum** [facebook/react-native#13123]
### Description

I get an Unexpected token '>'  error upon which the app crashes and closes. No indication on which line this might be (except index.android.bundle?platform=android&dev=true&hot=true&minify=false:65027:9). I commented everything in the root and  just left a View and it still gives that error. Now, the weird thing is that if I manage to enable Debug JS Remotely fast enough the error disappears and the app works. Any ideas?

### Additional Information

* React Native version: 0.42
* Platform: Android (can't test at the moment if this happens on iOS)
* Development Operating System: Windows
* Dev tools: Android Studio 2.3

**Comment by Oddadmix** [comment]
Did you install a dependency will the app being served ?

**Comment by iremlopsum** [comment]
@Oddadmix Found that this is an issue with a dependency, trying to figure out why though. Should be using general ES6 and nothing fancy. The dependency is written in company.
