### ISSUE TITLE
[iOS] Can't open Dev Menu after upgrading to 0.43.0-rc.4

### ISSUE THREAD

**Issue by zhuyifan2013** [facebook/react-native#13127]
### Description

Can't open Dev Menu after upgrading to 0.43.0-rc.4 , I am sure I am in Debug scheme , and I use cocoapods 1.2 

### Reproduction Steps and Sample Code

I upgrade from 0.41 

### Solution

None

### Additional Information

* React Native version: 0.43.0-rc.4
* Platform: iOS
* Development Operating System: MacOS
* Dev tools: Xcode 8.2.1

**Comment by hnzlk2014** [comment]
add DevSupport module.
E.g：
pod 'React', :path => './React/node_modules/react-native', :subspecs => [ 'Core', 'xxx', 'xxx', 'xxx', 'DevSupport']

**Comment by zhuyifan2013** [comment]
@hnzlk2014  I did this , but still didnot work, I have roll back to 0.42

**Comment by Snorlock** [comment]
Adding DevSupport worked for me, have to remember to "pod install" again

**Comment by nmquebb** [comment]
Also, if you're anything like me you toggle "Connect Hardware Keyboard" and end up forgetting about it when you go to access the dev menu.

**Comment by filipemonteiroth** [comment]
@zhuyifan2013 I had this same issue when tried to upgrade to 0.42 . I realized that when I ran from xcode not "react-native run-ios" it worked. 

The problem was solved when I updated xcode.

**Comment by alloy** [comment]
@hnzlk2014’s comment is correct, this can be closed.

**Comment by abdulhameedalyousef** [comment]
I am facing this issue now with the latest release react-native 0.55.4

```

platform :ios, '9.3'
target 'ArApp' do

  use_frameworks!
  pod 'ViroReact', :path => '../node_modules/react-viro/ios/'
  pod 'ViroKit', :path => '../node_modules/react-viro/ios/dist/ViroRenderer/'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTImage',
    'RCTText',
    'CxxBridge',
    'RCTActionSheet',
    'RCTLinkingIOS',
    'RCTAnimation',
    'RCTNetwork',
    'DevSupport',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
  ]

  pod 'boost-for-react-native'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      # Build React Native with DEBUG enabled
      if target.name == 'React'
        target.build_configurations.each do |config|
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= []
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'DEBUG=1'
        end
      end
    end
  end



end
```

from package.json
```
...
  "dependencies": {
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-viro": "^2.6.1"
  },
  "devDependencies": {
    "babel-jest": "22.4.3",
    "babel-preset-react-native": "4.0.0",
    "jest": "22.4.3",
    "react-devtools": "^3.2.1",
    "react-test-renderer": "16.3.1"
  },
...
```

Please advise

Thanks
