### ISSUE TITLE
Persistent scroll indicator

### ISSUE THREAD

**Issue by SudoPlz** [facebook/react-native#13136]
Hey there,

I was wondering if you plan on adding a way to show the scroll bar (either a vertical, or a horizontal scroll indicator permanently).

Right now it only shows when the user scrolls and then it hides itself.

Any ideas?

Thanks.

**Comment by hramos** [comment]
GitHub issues is not the best place to ask questions - we're trying to stick to issues in the code itself, so we're cutting down on non-bugs issues for now. You can find our roadmap in the wiki, and outstanding feature requests in Canny.
