### ISSUE TITLE
 onPress event is not triggered during scroll ListView animation

### ISSUE THREAD

**Issue by ludovic-coder** [facebook/react-native#13134]
### Description

onPress event is not triggered during scroll animation and after selected tabbar change.

### Reproduction Steps and Sample Code

I got TabBar that embedded an Navigator and a ListView. The cells have an onPress event that trigger an alert. If I scroll down (or up) the list view then change tabbar selected tab during list view animation and go back to list view, onPress is not triggered. 

### Solution

Needs to scroll the list view to get back onPress event.

### Additional Information

* React Native version: react-native-cli: 2.0.1 / react-native: 0.42.3
* Platform: iOS 
* Development Operating System: MacOS
* Dev tools: Xcode, iOS 10.2

**Comment by hramos** [comment]
Can you provide a minimal amount of code to reproduce this using [Sketch](http://sketch.expo.io)? This is necessary for people to be able to see and debug the issue being reported.

Closing this issue as it is not actionable. Please open a new one with a Sketch link (preferred), or link to a GitHub repo with clear instructions how to repro.

**Comment by Choujiji** [comment]
+1, I have the same issue
