### ISSUE TITLE
Android: CameraRoll.getPhotos({assetType: 'Videos'}) doesn't return videos

### ISSUE THREAD

**Issue by JBerendes** [facebook/react-native#13147]
### Description

The goal is to have my own video picker working correctly on both platforms.
On Android: When the picker opens it returns images but the images are not videos, they are simply photos and not photos related to any of my videos.
On iOS: Everything works correctly.

### Reproduction Steps and Sample Code

Record a video on Android with your default camera app. (Do this on both Android and iOS to see the full difference)

On Android you will need to allow Expo to access external storage.
[Link to Sketch](https://sketch.expo.io/r1OmX8E2x)

Notice you should get the first image asset which would be a video.

### Solution

On Android return an image asset for the video and details about the video similar to what iOS returns.

### Additional Information

* React Native version: react-native: 0.41.2 
* Platform: Android (though comparing to iOS should help)
* Development Operating System: MacOS
* Dev tools: Android Studio version 2.3, Android SDK version 23

**Comment by JBerendes** [comment]
Dupe of #11877 but the sketch is helpful for testing.

**Comment by heliocaruccio** [comment]
Equivalent in groupTypes param  (Android)

**Comment by wdoering** [comment]
@JBerendes why is this closed? was this fixed somehow? I'm facing this issue right now too.
