### ISSUE TITLE
[Text] Nested Text component can't have independent opacity

### ISSUE THREAD

**Issue by jmstout** [facebook/react-native#1314]
I came across what I assume is an unintended behavior today.

If you have a child `Text` component within a parent, it doesn't render an independent opacity value when set. It instead renders whatever the opacity of the containing/parent `Text` component is.

Reproducing this issue is easy:
```javascript
<Text>
  <Text style={{opacity:0.25}}>
    This should be 25% opacity, but isn't.
  </Text>
</Text>
```

I'm thinking this is a bug because other style properties (`color, backgroundColor, fontSize, fontWeight`, etc) seem to work properly.

I haven't, yet, had a chance to take a look at what might be the underlying cause.

Anyone have any insight?

**Comment by nicklockwood** [comment]
It's to do with how text components are composed. Inner text nodes are collapsed into a single attributed text string. Text attributes include color but not opacity.

We should probably premultiply the text and background colors by the opacity when collapsing text nodes.

The workaround for now is to set the text color to an rgba() value with a <1 alpha for the inner text, instead of reducing opacity.

**Comment by jmstout** [comment]
Ah, thanks @nicklockwood, that explains it.

Premultiplying the text and background colors seems like it could work - but what about in scenarios where the text with a specific opacity appears on a split color background?

I'm not even sure this would be worth working out though, maybe we just add a note about it in the docs and call it a day?

rgba() seems like a good enough alternative.

Thanks again for your insight!

**Comment by nicklockwood** [comment]
@jmstout I meant premultiplying opacity by background if you want the text background to also be translucent. To get transparent text you should just be able to set the alpha component of the text color - no need to pre-blend it with the background color.

**Comment by jmstout** [comment]
@nicklockwood Ohhh I see, thanks for the clarification. 👍

Seems like it would be doable, then.

I'll leave this issue open for now, maybe we can get around to implementing your solution at some point.

**Comment by Dharmoslap** [comment]
rgba works for me :+1:

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by browniefed** [comment]
@brentvatne @ide recommended rgba works in place of opacity, probably close.

**Comment by brentvatne** [comment]
@browniefed - I'd like to see a solution that allows us to use opacity as we expect here, so I'll keep this open

**Comment by jberdine** [comment]
Using opacity attributes on nested text nodes [now](https://github.com/facebook/react-native/commit/02a8c383618382d669369d3d0701af0892398761) adjusts the alpha channel correspondingly.

**Comment by browniefed** [comment]
@facebook-github-bot answered

**Comment by irohit444** [comment]
I want to use TouchableOpacity  for Radio button with its text. so, can you help me how to do? When we touch the Radio button or its text the data should auto select in selected radio button.
