### ISSUE TITLE
Unable to require image with non-lowercase letters/numbers

### ISSUE THREAD

**Issue by guymorita** [facebook/react-native#13154]
### Description

Unable to require images with certain non-lowercase letters/numbers.

Ex. '_'

![image](https://cloud.githubusercontent.com/assets/2003939/24334014/dabcdf10-128c-11e7-9e8c-674ab29b1fff.png)

```
<Image
              style={{height: 50, width: 50}
              source={require('./101_Ana_0.jpeg')}
            />
```

I'm able to require images with no special characters. Certain ones work '-', however not '_'.

### Additional Information

* React Native version: 0.42
* Platform: Both
* Development Operating System: OSX 10.12
* Dev tools: Latest

**Comment by RakanNimer** [comment]
This usually happens when adding an image to a directory that is being watched.
Try killing the packager server and running it again.

**Comment by guymorita** [comment]
Thanks what if the image is dynamic.

**Comment by rodperottoni** [comment]
If your image is coming from an API, then all you have to do is use **{ uri: imageUri }** instead of **require(imageName)**. The documentation is pretty clear: [React Native Image](https://facebook.github.io/react-native/docs/image.html)

**Comment by guymorita** [comment]
```
    const imageMapping = {
      '101_Ana': require('./101Ana0.png'),
      '102_Jessica': require('./102Jessica0.png'),
      '103_Christina': require('./103Christina0.png'),
      '104_Em': require('./104Em0.png'),
      '105_Katrina': require('./105Katrina0.png')
    }

    const firstImage = (key) => imageMapping[key]

    return (
      <TouchableOpacity onPress={this._onPressCell.bind(this)}>
        <View style={styles.container}>
          <View>
            <Image
              style={styles.thumb}
              source={firstImage(key)}
            />
``` it's the cleanest but it works.
