### ISSUE TITLE
Animation.event 'style property is not supported'

### ISSUE THREAD

**Issue by undershot** [facebook/react-native#13150]
### Description

I have a problem with Animated.event with interpolate on scroll event. When I use Animated.event with 

`useNativeDriver: true`

 I receive next error: 

`Style property 'height' is not supported by native animated module`

If I use `opacity` property - it works fine.

`opacity` - works.

`height` - didn't works.

Without `useNativeDriver: true` - all works fine.

### Reproduction Steps and Sample Code

    render() {
    		this.yOffset = new Animated.Value(0);
    
    		let event = Animated.event([
    			{
    				nativeEvent: {
    					contentOffset: {
    						y: this.yOffset
    					}
    				}
    			}
    		], {useNativeDriver: true});
    
    		let opacity = this.yOffset.interpolate({
    			inputRange: [0, 120],
    			outputRange: [1, 0],
    		});
    
    		let height = this.yOffset.interpolate({
    			inputRange: [0, 180],
    			outputRange: [200, 100],
    		});
    
    		return (
    			<View>
    				<Header
    					style={{
    						opacity,
    						height
    					}}
    				/>
    
    
    				<ScrollView
    					scrollEventThrottle={16}
    					onScroll={event}
    				>
    
    					// some content
    
    				</ScrollView>
    			</View>
    		);
    	}

### Solution

None.

### Additional Information

* React Native version: 0.43.0-rc.4
* Platform: Tested on Android Emulator Accelerated_x86 API 23
* Development Operating System: Windows 10 x64
* Dev tools: Android Studio latest

**Comment by nihgwu** [comment]
It's not a bug, Native Animation only support non layout props, such as transform and opacity, you can try to achieve your intention using `transform translateY` if you want to use Native Animation

**Comment by hramos** [comment]
Working as expected. Animating layout props is not supported by the native driver.

**Comment by DavitVosk** [comment]
I am sure you will find all answers to your questions reading this article: https://facebook.github.io/react-native/blog/2017/02/14/using-native-driver-for-animated.html
