### ISSUE TITLE
UIScrollView : paging horizontally, scrolling vertically ?

### ISSUE THREAD

**Issue by soliury** [facebook/react-native#1315]
I just want to know how to set the [UIScrollView : paging horizontally, scrolling vertically], I mean I have a scrollView, and then  I set the props 'pagingEnabled' to `true`. But it working in horizontally, but I don't want the horizontally to be paging. 

How can I solve it ?

I have tried this:

I set a nest scrollView, the wrapper one set the `pagingEnabled` to `true`, when I scrolling , the inner one don't respond the scrolling , and the wrapper one have respond, How can I let the wrapper one don't handle the scroll event, and let the inner one handle the event?

**Comment by ide** [comment]
Nested scroll views is the correct approach but unfortunately they don't work very well with React right now (#41).

**Comment by soliury** [comment]
I just want to know how to solve it ?

**Comment by ide** [comment]
You could create a native UIPageViewController or native UIScrollView and create a separate RCTRootView (that all share the same RCTBridge) for each screen. I don't think there's a good way to do this with pure React right now. Either you run into issues with nested scroll views or you have to reimplement the scroll physics which was kind of janky in the one example I saw.

**Comment by soliury** [comment]
ok, I see. It is not easy to finish it . I don't know much about object-c.

**Comment by soliury** [comment]
I also want to know how to change the scrollView's props like `pagingEnabled ` when scrolling.

**Comment by soliury** [comment]
I change the `ScrollResponder.js` at line `137`:

```
    scrollResponderHandleScrollShouldSetResponder: function ():boolean {
        //return this.state.isTouching;
        //return true;
        console.log('debug:');
        console.log(arguments);
        if(this.props.onScrollShouldSetResponder){
            console.log(this.props.onScrollShouldSetResponder(arguments));
            return this.props.onScrollShouldSetResponder(arguments)
        }
        return false;
        //this.props.onScrollShouldSetResponder && this.props.onScrollShouldSetResponder(arguments)
    }
```

**Comment by christopherdro** [comment]
I found nesting a horizontal ScrollView within a ListView seems to work fairly well.

Can post an example if you'd like.

**Comment by soliury** [comment]
I have solve it .

**Comment by christopherdro** [comment]
@soliury Great!

Maybe you can share your solution for other people that might come across this!

**Comment by soliury** [comment]
Just don’t set the contentStyle width and height, so it will work.

**Comment by soliury** [comment]
I am writing a app in react-native, and then I will open  the source of app, When the day come, I will put the example to here.

**Comment by soliury** [comment]
The solution is that , don't set the `contentContainerStyle` with height or width equal the window width or height, it will make the the scrollable content size to window width or window height, so you can not scroll. But nest with two scroll will make the app too slow, and take too much memory. 

This is my app writing in react-native, after I finish it, I will open source. 

![](http://lingyong-me.qiniudn.com/IMG_0406.PNG)

![](http://lingyong-me.qiniudn.com/IMG_0407.PNG)

![](http://lingyong-me.qiniudn.com/IMG_0408.PNG)

**Comment by brentvatne** [comment]
@soliury - looks nice! would like to see it when the open source version is available. thanks for the follow up!

**Comment by soliury** [comment]
@brentvatne I have open source. Just see https://github.com/soliury/noder-react-native, But the code is not clear, I will refactor it soon.

@christopherdro

**Comment by brentvatne** [comment]
Nice one @soliury!
