### ISSUE TITLE
searchPaths.filter is not a function, when unlinking

### ISSUE THREAD

**Issue by pvinis** [facebook/react-native#13160]
### Description
i tried unlinking a library and i got an error
```
react-native unlink react-native-video
Scanning 870 folders for symlinks in /Users/pvinis/Source/mycujoo/mycujoo-mobile/node_modules (9ms)
rnpm-install info Unlinking react-native-video ios dependency
rnpm-install ERR! It seems something went wrong while unlinking. Error: searchPaths.filter is not a function

searchPaths.filter is not a function
```
### Reproduction Steps and Sample Code
try to link and then unlink a library i guess.

### Solution
no idea.

### Additional Information

* React Native version: 0.42.3
* Platform: iOS
* Development Operating System: MacOS
* Dev tools: Xcode

**Comment by minhtc** [comment]
up

**Comment by minhtc** [comment]
my quick fixes:
file: /node_modules/react-native/node_modules/xcode/lib/pbxProject.js
line 1146:
change the condition from `if(searchPaths)` to `if (searchPaths && searchPaths !== '"$(inherited)"')`

**Comment by Monte9** [comment]
@minhtc this worked for me. Thank you!

**Comment by mienaikoe** [comment]
@minhtc I didn't find this js file. Instead, I made all of the framework, header, and library search paths in `ios/<projectName>.xcodeproj/project.pbxproj` a list. Some of them were individual strings, but you can list them by surrounding the one string with (parentheses)

**Comment by niftylettuce** [comment]
@minhtc Just to follow up - there are actually two places in that file that need adjusted as such.

**Comment by rocwangv** [comment]
+1

**Comment by qruzz** [comment]
@mienaikoe Could you expand on that?
I am looking at that file, but have no idea what I am looking for?

**Comment by mienaikoe** [comment]
hey @qruzz . It's been a while, but I think I remember what I was talking about:

Somewhere near the bottom of the file, you'll have your build configurations. In here there are several build settings, including `HEADER_SEARCH_PATHS`, `FRAMEWORK_SEARCH_PATHS`, and `LIBRARY_SEARCH_PATHS`. `react-native unlink` seems to be expecting these to be lists in all cases, but many projects just have one value as in 

    HEADER_SEARCH_PATHS = "$(inherited)"

Instead, as a workaround, you should make them into a list:

    HEADER_SEARCH_PATHS = (
    	"$(inherited)",
    );

**Comment by qruzz** [comment]
@mienaikoe Thank you very much for the reply !
Unfortunately, that did not solve the problem for me either ..
All my `HEADER_SERCH_PATHS` were lists already, but had to change all the `LIBRARY_SEARCH_PATHS` .. There were however no `FRAMEWORK_SEARCH_PATHS` in my project, but instead a `LD_RUNPATH_SEARCH_PATHS` instead, that I also changed into lists.

**Comment by kelset** [comment]
Keep happening to me as well (0.46.4), anyone found a proper fix for it?

**Comment by ugiacoman** [comment]
@kelset Were you able to find a solution? Happening to me as well.

**Comment by ugiacoman** [comment]
@minhtc Solutions worked, but the file was at `/node_modules/xcode/lib/pbxProject.js` react-native `0.47.1`

**Comment by kelset** [comment]
@ugiacoman sorry, not being able to fix it :/ Maybe with 0.48? I'll try to upgrade to latest once it comes out, let's see what happens then

**Comment by alexlevy0** [comment]
Same issue with react-native 0.49.1

**Comment by JperF** [comment]
I change the follow bit of code in the `/node_modules/xcode/lib/pbxProject.js` 

```
if (searchPaths) {
            var matches = searchPaths.filter(function(p) {
                return p.indexOf(new_path) > -1;
            });
            matches.forEach(function(m) {
                var idx = searchPaths.indexOf(m);
                searchPaths.splice(idx, 1);
            });
        }
```

to 

```
if (searchPaths) {
            if(typeof searchPaths === 'string'){
                searchPaths = [searchPaths]
            }
            var matches = searchPaths.filter(function(p) {
                return p.indexOf(new_path) > -1;
            });
            matches.forEach(function(m) {
                var idx = searchPaths.indexOf(m);
                searchPaths.splice(idx, 1);
            });
        }
``` 

and it seemed to have fixed the issue as well.

**Comment by Bernhard---H** [comment]
still there in 0.51.0

**Comment by fungilation** [comment]
Confirmed, on running `$ react-native unlink react-native-sentry`:

```
It seems something went wrong while unlinking. Error: searchPaths.filter is not a function
```

**Comment by adamhaney** [comment]
I'm also seeing this in RN 0.51 is the typical process to re-open an issue or create a new one?

**Comment by fungilation** [comment]
@pvinis, re-open please? And this obviously isn't `stale` as it's still happening.

**Comment by wellyshen** [comment]
Please re-open it. I also encounter this issue when I run `$ react-native unlink react-native-sentry`

**Comment by adamhaney** [comment]
After a bit of detective work (threw console.log statements throughout /node_modules/xcode/lib/pbxProject.js to see what part of the project file it was choking on) it seems like the installer was expecting my project to have a 'Plugins' group that I didn't have, I created an empty one in the project. My top level project groups now look like this:

![screen shot 2018-01-26 at 9 32 40 am](https://user-images.githubusercontent.com/1839452/35444928-083fa260-027e-11e8-9ded-73fbca34f673.png)

 I also opened up ios/<ProjectName> and made sure that every variable that ended in *_SEARCH_PATHS was a list, it appears like xcode uses a string for single element lists, so I just wrapped parenthesis around those variables, after that I ran `react-native unlink` and `react-native link` again without issue. 

Perhaps the xcode library needs to be patched and/or there needs to be some exception handling for missing groups / lists that only have a single entry that are being treated as strings?

**Comment by macrozone** [comment]
can confirm this still happens in react-native 0.53! its neither stale nor fixed. Please re-open

**Comment by pietro909** [comment]
Saw now that the `alunny/node-xcode` moved to `apache/cordova-node-xcode`, therefore is unmaintained. There they've already fixed it [see here](https://github.com/apache/cordova-node-xcode/blob/master/lib/pbxProject.js#L1205).

Need to update the dependency.

**Comment by kylevdr** [comment]
0.55.3 and it is still a problem, but as @pietro909 mentioned it appears to be a problem with a dependency, not React Native itself. The same basic fix from @minhtc still works with a few updates:
- As @ugiacoman mentioned, the location of the file you need to change has been moved
- There are multiple places the change needs to be applied
- `"$(inherited)"` is not the only string that can appear

The current solution:
1. Open `/node_modules/xcode/lib/pbxProject.js`
2. Search for `if (searchPaths)`
3. add `&& Array.isArray(searchPaths)` to each match
