### ISSUE TITLE
C++ exception 

### ISSUE THREAD

**Issue by NeoPi** [facebook/react-native#13162]
![722099625](https://cloud.githubusercontent.com/assets/8284829/24359961/7b798c62-12cb-11e7-957a-7574dc56af59.jpg)

How can i fix it

**Comment by jkomyno** [comment]
Which custom native modules are you using? Or are you only using official react-native's modules?

**Comment by NeoPi** [comment]
i just use a custom native module. it has a method :
 `@ReactMethod
    private String byte2Hex(byte b) {
        int value = (b & 0x7F) + (b < 0 ? 0x80 : 0);
        return (value < 0x10 ? "0" : "")
                + Integer.toHexString(value).toLowerCase();
    }`

maybe it caused
