### ISSUE TITLE
[Timer] setTimeout enviroment

### ISSUE THREAD

**Issue by romanonthego** [facebook/react-native#1316]
i've encountering some strange bugs with lodash (3.8.0) and react-native (4.4.0);
it's seams what setTimeout function is not exposed and is undefined for lodash context ([here to be exact](https://github.com/lodash/lodash/blob/master/lodash.js#L7696)).
switching to Chrome Debugging fixing the issue since your runngin code in Chrome, switch back - aaand issue is back.
in react context setTimeout seems fine.
[error screenshot](http://take.ms/ViKya)

**Comment by brentvatne** [comment]
@romanonthego - strange one there, could you post a small project that reproduces this so we can clone and check it out? it helps a lot :smile:

**Comment by browniefed** [comment]
@romanonthego any news one this? Is it still happening?

**Comment by brentvatne** [comment]
This is super old so I'll close, but happy to reopen if still an issue and we have more info
