### ISSUE TITLE
A server with the specified hostname could not be found (code -1003)

### ISSUE THREAD

**Issue by Pau1fitz** [facebook/react-native#13161]
I am trying to set up react native and run on my phone using expo.

I have [created a react native app using][1] `create-react-native-app`.

After running this command everything gets built on my machine. I have also downloaded the expo app on my phone. 

I then ran `npm start` and was given the following in my terminal:

> enter this address in the Expo app's search bar:
> 
>   exp://12.34.567.89:19000

When I try this I get the following error in expo - 

> Error while loading: A server with the specified hostname could not be
> found (code -1003)

Has anyone come across this issue before?

  [1]: https://facebook.github.io/react-native/blog/2017/03/13/introducing-create-react-native-app.html

**Comment by mikaalanwar** [comment]
The same process works fine for me. Try to double check hostname and make sure that the port isn't pre-occupied with something else OR maybe try the QR Code scanning approach, lesser room for errors there.

**Comment by hramos** [comment]
Make sure both devices are on the same network, and that they can reach each other. The easiest way to test if there's reachability is to open the URL on your device directly. Go to the browser and try loading http://12.34.567.89:19000. If that URL is not found, then the device can't reach your server.

This is typical in captive portal wifi networks (e.g. coffee shops and other public wifi networks). You can get around this by tethering, if you can't use a different network.
