### ISSUE TITLE
[cli][upgrade] Failed to run react-native-git-upgrade to 0.43.0-rc.4

### ISSUE THREAD

**Issue by joonhocho** [facebook/react-native#13171]
### Description
run react-native-git-upgrade

It fails due to bunch of false positive UNMET PEER DEPENDENCY statements across many npm packages that I have installed.
All of them are false positive and can be ignored because some npm packages, for example, add peer dependency of react@^15.0.0, but still works great with react@16.0.0. So these peer dependencies can be ignored completely.
However, react-native-git-upgrade stops after these warnings at start.
Is there a way to ignore these warnings and continue?

### Solution

Ignore npm warnings about peer dependencies and continue to run react-native-git-upgrade

### Additional Information

* React Native version: upgrading 0.40.0 -> 0.43.0-rc.4
* Platform: both
* Development Operating System: MacOS
* Dev tools: terminal

**Comment by joonhocho** [comment]
Here's sample output for the upgrade

```
git-upgrade ERR! An error occurred during upgrade:
git-upgrade ERR! Error: Command 'npm install --save --color=always react-native@0.43.0-rc.4 react@~16.0.0-alpha.3' exited with code 1:
stderr: undefined
npm WARN deprecated node-uuid@1.4.7: Use uuid module instead
npm WARN react-redux@4.4.6 requires a peer of react@^0.14.0 || ^15.0.0-0 || ^15.4.0-0 but none was installed.
npm WARN react-addons-shallow-compare@15.3.2 requires a peer of react@^15.3.2 but none was installed.
npm WARN react-native-android-action-sheet@0.0.1 requires a peer of react-native@>=0.10.0 but none was installed.
npm WARN react-native-camera@0.6.0 requires a peer of react@>=15.4.0 but none was installed.
npm WARN react-native-camera@0.6.0 requires a peer of react-native@>=0.40 but none was installed.
npm WARN react-native-drawer-layout-polyfill@1.1.0 requires a peer of react-native@>= 0.25 but none was installed.
npm WARN react-native-drawer-layout-polyfill@1.1.0 requires a peer of react@>= 0.14.5 but none was installed.
npm WARN react-native-image-resizer@0.0.12 requires a peer of react-native@>=v0.14.2 but none was installed.
npm WARN react-relay@0.10.0 requires a peer of react@^15.0.0 || ^0.14.0 but none was installed.
npm WARN react-static-container@1.0.1 requires a peer of react@^0.13.0 || ^0.14.0 || ^15.0.0 but none was installed.
npm WARN react-test-renderer@15.4.2 requires a peer of react@^15.4.2 but none was installed.

stdout: - array-union@1.0.2 node_modules/array-union
- multimatch@2.1.0 node_modules/multimatch
- progress@1.1.8 node_modules/progress

├─┬ UNMET PEER DEPENDENCY react@16.0.0-alpha.6
│ └─┬ fbjs@0.8.11
│   └── core-js@1.2.7
└─┬ UNMET PEER DEPENDENCY react-native@0.43.0-rc.4
  ├─┬ babel-plugin-transform-async-to-generator@6.16.0
  │ └─┬ babel-helper-remap-async-to-generator@6.22.0
  │   ├─┬ babel-helper-function-name@6.23.0
  │   │ └── babel-helper-get-function-arity@6.22.0
  │   ├── babel-runtime@6.23.0
  │   ├── babel-template@6.23.0
  │   ├─┬ babel-traverse@6.23.1
  │   │ ├── babel-code-frame@6.22.0
  │   │ └── babel-messages@6.23.0
  │   └── babel-types@6.23.0
  ├─┬ concat-stream@1.6.0
  │ ├─┬ readable-stream@2.2.6
  │ │ └── isarray@1.0.0
  │ └── typedarray@0.0.6
  ├─┬ fbjs@0.8.11
  │ └── core-js@1.2.7
  ├─┬ jest-haste-map@19.0.0
  │ ├─┬ fb-watchman@2.0.0
  │ │ └── bser@2.0.0
  │ └─┬ sane@1.5.0
  │   ├── anymatch@1.3.0
  │   ├─┬ fb-watchman@1.9.2
  │   │ └── bser@1.0.2
  │   └── minimist@1.2.0
  ├─┬ react-devtools-core@2.0.12
  │ ├─┬ cross-env@3.2.4
  │ │ ├─┬ cross-spawn@5.1.0
  │ │ │ ├── lru-cache@4.0.2
  │ │ │ └─┬ shebang-command@1.2.0
  │ │ │   └── shebang-regex@1.0.0
  │ │ └── is-windows@1.0.0
  │ └─┬ ws@2.2.2
  │   └── ultron@1.1.0
  ├─┬ ws@1.1.4
  │ └── ultron@1.0.2
  └── xpipe@1.0.5
```

**Comment by joonhocho** [comment]
Related https://github.com/facebook/react-native/pull/13194

**Comment by JulianKingman** [comment]
@joonhocho did you manage to fix it somehow?

**Comment by joonhocho** [comment]
@JulianKingman I successfully upgraded to v0.43.0 after release.

**Comment by joonhocho** [comment]
Closing as there is a newer version and it worked for me.

**Comment by MattyK14** [comment]
I got this error when trying to go from 0.40 to 0.42.3 and now from 0.42.3 to 0.43

**Comment by waterPrince** [comment]
how did you solve the problem? after that i got an error

**npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npmgit-upgrade ERR! An error occurred during upgrade:
git-upgrade ERR! Error: Command 'npm install --save --color=always react-native@0.54.2 react@^16.3.0-alpha.1' exited with code 1:
stderr: undefinednpm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm
stdout:
    at ChildProcess.child.on.code (C:/Users/guoya/AppData/Roaming/npm/node_modules/react-native-git-upgrade/cliEntry.js:58:18)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
git-upgrade ERR! Restore initial sources
 WARN jest-react-native@16.0.0 requires a peer of whatwg-fetch@^1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-test-renderer@15.3.2 requires a peer of react@^15.3.2 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-check-constants@7.0.0-beta.38 requires a peer of @babel/core@7.0.0-beta.38 but none is installed. You must install peer dependencies yourself.

npm ERR! path C:\WorkPlace_ReactNative\lifetime-2\lifetime-android\node_modules\react-native\node_modules\.bin\babylon
npm ERR! code EEXIST
npm ERR! Refusing to delete C:\WorkPlace_ReactNative\lifetime-2\lifetime-android\node_modules\react-native\node_modules\.bin\babylon: is outside C:\WorkPlace_ReactNative\lifetime-2\lifetime-android\node_modules\react-native\node_modules\babylon and not a link
npm ERR! File exists: C:\WorkPlace_ReactNative\lifetime-2\lifetime-android\node_modules\react-native\node_modules\.bin\babylon
npm ERR! Move it away, and try again.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\guoya\AppData\Roaming\npm-cache\_logs\2018-03-22T01_56_25_781Z-debug.log
M       ask-doctor
Note: checking out 'project-snapshot'.**

could you give me some help?
