### ISSUE TITLE
react native fbsdk MODULE_NOT_FOUND after link commend

### ISSUE THREAD

**Issue by llioor** [facebook/react-native#13176]
I opened bug on Facebook developer support tool and after investigation I received this answer:
"We investigated this and it looks like an issue with React Native itself. Can you please report the issue using our React Native issue tracker at https://github.com/facebook/react-native/issues?
On this tool we don't currently support React Native itself, but we support its Facebook SDK."

I'm trying to install and link react-native-fbsdk package and I got this error:
`[Error: Cannot find module 'C:\wamp\www\chatapp\node_modules\react-native-fbsdk\package.json'] code: 'MODULE_NOT_FOUND'`

**I went through these steps:**
`react-native init [YourApp]`
Done successfully.

`react-native install react-native-fbsdk`
Output: Scanning 712 folders for symlinks in C:\wamp\www\chatapp\node_modules (26ms) rnpm-install info Module react-native-fbsdk has been successfully installed & linked

`react-native link react-native-fbsdk`
Output: Scanning 712 folders for symlinks in C:\wamp\www\chatapp\node_modules (29ms) { [Error: Cannot find module 'C:\wamp\www\chatapp\node_modules\react-native-fbsdk\package.json'] code: 'MODULE_NOT_FOUND' }

**More Info:**

- React native version: 0.42.3
- npm -version 4.2.0
- I didn't find "react-native-fbsdk" folder under my node_modules folder.
- Windows 8.1
- I'm working with Android Studio
- Android SDK Platform-Tools 25.0.4
- Android SDK Tools 25.2.3

Print screens:
[Console](https://scontent-frt3-1.xx.fbcdn.net/v/t39.2087-6/16685173_282011152233895_4788250101036351488_n.png?oh=809110cc8a41cf96df8437212e3831f6&oe=5962D5B0)
[Packages versions](https://scontent-frt3-1.xx.fbcdn.net/v/t39.2087-6/16685163_352458995152051_8045106265241681920_n.png?oh=34f4c2c1aa508c3a237ad2c589f34fd4&oe=5959452E)

Thank you in advance. 
Leo.

**Comment by stoffern** [comment]
react-native install react-native-fbsdk is not a valid command.

try this inside the app folder
```js
npm i -S react-native-fbsdk
```

**Comment by llioor** [comment]
Thanks @stoffern 
What weird is that in all doc it is written:
react-native install react-native-fbsdk

Weird...

**Comment by stoffern** [comment]
please send a PR to `react-native-fbsdk` about this.
This issue can be closed

**Comment by llioor** [comment]
I have this error now:

https://github.com/facebook/react-native/issues/9136

**Comment by llioor** [comment]
@stoffern Hey Kristoffer, maybe you can advice here:
https://github.com/facebook/react-native/issues/13259#issuecomment-291426909
