### ISSUE TITLE
[RN 0.42 Android] Native UI Components (DatePicker/TimePicker)

### ISSUE THREAD

**Issue by drinkingcode** [facebook/react-native#13177]
It works fine to use native DatePicker and TimePicker on android 6.0 by  [Native UI Components Guide](http://facebook.github.io/react-native/docs/native-components-android.html) , it displays like this:
![4e3efb95-fd4e-4fa9-bca5-9f98196c2bfc](https://cloud.githubusercontent.com/assets/15334969/24396846/3401f7e0-13d7-11e7-8cee-f19632938acd.png)

but when running the same code on android 7.0,  it displays as following:
![a84869eb-6919-4529-929a-8e30298cf0a3](https://cloud.githubusercontent.com/assets/15334969/24396897/56148758-13d7-11e7-806a-8469978ee70b.png)

Here is my code:

**layout_date_time_picker.xml:**
&lt;?xml version="1.0" encoding="utf-8"?&gt;
&lt;RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent" android:layout_height="match_parent"&gt;
    &lt;DatePicker
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_centerHorizontal="true"
        android:id="@+id/date_picker"
        android:datePickerMode="spinner"
        android:calendarViewShown="false"
    /&gt;
    &lt;TimePicker
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_centerHorizontal="true"
        android:id="@+id/time_picker"
        android:timePickerMode="spinner"
        android:layout_below="@+id/date_picker"
    /&gt;
&lt;/RelativeLayout&gt;

**ReactDateTimePicker.java:**
/**
 * 自定义组合控件 (Custom View)
 * 封装了日期和时间的控件
 */
public class ReactDateTimePicker extends RelativeLayout{

    public static final String TAG="ReactDateTimePicker";

    private Calendar mDate;
    private DatePicker mDatePicker;
    private TimePicker mTimePicker;
    private DateTimePickerChangeListener mListener;

    public ReactDateTimePicker(Context context) {
        this(context,null);
    }

    public ReactDateTimePicker(Context context, AttributeSet attrs) {
        this(context, attrs,0);
    }

    public ReactDateTimePicker(Context context, AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);

        View view = LayoutInflater.from(context).inflate(R.layout.layout_date_time_picker,null);
        mDatePicker = (DatePicker) view.findViewById(R.id.date_picker);
        mTimePicker = (TimePicker) view.findViewById(R.id.time_picker);

        mDate = Calendar.getInstance();

        LayoutParams params = new LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT);
        params.addRule(RelativeLayout.CENTER_IN_PARENT);
        addView(view,params);
    }

    /**
     * 初始化日期时间
     */
    public void setDateTimeValue(final int year, final int month, final int dayOfMonth, final int hours, final int minute){
        mDate.set(year,month,dayOfMonth,hours,minute);
        mDatePicker.init(year, month, dayOfMonth, new DatePicker.OnDateChangedListener() {
            @Override
            public void onDateChanged(DatePicker datePicker, int i, int i1, int i2) {
                //同步日期
                mDate.set(datePicker.getYear(),datePicker.getMonth(),datePicker.getDayOfMonth());
                if(mListener != null){
                    mListener.onChange(
                            mDate.get(Calendar.YEAR),
                            mDate.get(Calendar.MONTH),
                            mDate.get(Calendar.DAY_OF_MONTH),
                            mDate.get(Calendar.HOUR_OF_DAY),
                            mDate.get(Calendar.MINUTE));
                }
            }
        });

        mTimePicker.setIs24HourView(true);
        mTimePicker.setCurrentHour(hours);
        mTimePicker.setCurrentMinute(minute);
        mTimePicker.setOnTimeChangedListener(new TimePicker.OnTimeChangedListener() {
            @Override
            public void onTimeChanged(TimePicker timePicker, int i, int i1) {
                //同步时间
                mDate.set(Calendar.HOUR_OF_DAY,timePicker.getCurrentHour());
                mDate.set(Calendar.MINUTE,timePicker.getCurrentMinute());
                if(mListener != null){
                    mListener.onChange(
                            mDate.get(Calendar.YEAR),
                            mDate.get(Calendar.MONTH),
                            mDate.get(Calendar.DAY_OF_MONTH),
                            mDate.get(Calendar.HOUR_OF_DAY),
                            mDate.get(Calendar.MINUTE));
                }
            }
        });

    }

    //日期时间更新的时候进行回调
    public void setDateTimePickerChangeListener(DateTimePickerChangeListener listener){
        mListener = listener;
    }

}

**ReactDateTimeManager.java:**
public class ReactDateTimeManager extends SimpleViewManager<ReactDateTimePicker> {

    private static final String REACT_DATE_TIME_PICKER = "ReactDateTimePicker";

    @Override
    public String getName() {
        return REACT_DATE_TIME_PICKER;
    }

    @Override
    protected ReactDateTimePicker createViewInstance(final ThemedReactContext reactContext) {
        final ReactDateTimePicker dateTimePicker = new ReactDateTimePicker(reactContext);
        dateTimePicker.setDateTimePickerChangeListener(new DateTimePickerChangeListener() {
            @Override
            public void onChange(int year, int month, int dayOfMonth, int hour, int minute) {
                String date = year + "/" + month + "/" + dayOfMonth + "/" + hour + "/" + minute;
                //日期时间发生变化时调用
                WritableMap event = Arguments.createMap();
                event.putString("onDateTimeChange",date);
                reactContext.getJSModule(RCTEventEmitter.class).receiveEvent(dateTimePicker.getId(),"topChange",event);
            }
        });
        return dateTimePicker;
    }

    /**
     * 初始化日期时间
     */
    @ReactProp(name="dateTimeValue")
    public void setDateTimeValue(ReactDateTimePicker view, String date){

        int[] dateTime = new int[5];
        String[] valueArray = date.split("/");

        for(int k=0;k<valueArray.length;k++){
            dateTime[k] = Integer.valueOf(valueArray[k]);
        }
        //it's called, but native ui component doesn't render
        view.setDateTimeValue(dateTime[0],dateTime[1],dateTime[2],dateTime[3],dateTime[4]);
    }

}

**ReactDateTimePickerPackage.java:**
public class ReactDateTimePickerPackage implements ReactPackage {

    @Override
    public List<NativeModule> createNativeModules(ReactApplicationContext reactContext) {
        return Collections.emptyList();
    }

    @Override
    public List<Class<? extends JavaScriptModule>> createJSModules() {
        return Collections.emptyList();
    }

    @Override
    public List<ViewManager> createViewManagers(ReactApplicationContext reactContext) {
        return Arrays.<ViewManager>asList(new ReactDateTimeManager());
    }

}

**MainApplication.java:**
public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          new ReactDateTimePickerPackage()
      );
    }
  };

 @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
  }

}

**DateTimePickerAndroid.js:**
'use strict';
import React from 'react';
import {
    requireNativeComponent,
    View
} from 'react-native';

let iface = {
    name:'ReactDateTimePicker',
    propTypes:{
        dateTimeValue:React.PropTypes.string,
        onDateTimeChange:React.PropTypes.func,
        ...View.prototype
    }
};

var DateTimePicker = requireNativeComponent('ReactDateTimePicker', iface);

export default class DateTimePickerAndroid extends React.Component{

    constructor(props){
        super(props);
        this._onDateTimeChange=this._onDateTimeChange.bind(this);
    }

    render(){
        return(
            <DateTimePicker
                {...this.props}
                onChange={this._onDateTimeChange}
            />
        );
    }

    _onDateTimeChange(event){
        if(!this.props.onDateTimeChange){
            return;
        }
        this.props.onDateTimeChange(event.nativeEvent.onDateTimeChange);
    }
}

**Problem:**
on android 7.0 , DatePicker and TimePicker have already called , but it renders incorrectly, so what's going on here ?
Welcome to discuss this question !

**Comment by hoangpham95** [comment]
Could you edit your question format so the code blocks get easier to read?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
