### ISSUE TITLE
[Flow] react-native FormDataPart type conflicts with built-in FormData types in flow

### ISSUE THREAD

**Issue by michaelgmcd** [facebook/react-native#13187]
### Description

The built-in type for FormData in flow requires that the second argument to the `append` method is a `string`, `Blob`, or `File`. This conflicts with the react-native `FormDataPart` type defined in 
Libraries/Network/FormData.js:

```
type FormDataPart = {
  string: string,
  headers: Headers,
} | {
  uri: string,
  headers: Headers,
  name?: string,
  type?: string,
};
```

Flow built-in types:
- FormData: https://github.com/facebook/flow/blob/2278be3ffbc2f5ebb965e91f83fc8d957fc7d779/lib/bom.js#L292-L312
- Blob: https://github.com/facebook/flow/blob/6fa6d02faac2591e38456872aa23b62f6a999eec/lib/dom.js#L12-L22
- File: https://github.com/facebook/flow/blob/6fa6d02faac2591e38456872aa23b62f6a999eec/lib/dom.js#L43-L46

### Solution

I have made a similar issue in the flow repository (https://github.com/facebook/flow/issues/3597).
I am not sure the approach to take here. I don't think we want to change the flow built-in type so it may require importing FormData directly from react-native or overwriting the type.

### Additional Information

* React Native version: 0.42.3
* Platform: both
* Development Operating System: MacOS
* Dev tools: flow version 0.38.0

**Comment by michaelgmcd** [comment]
Issue was labeled as stale, however as of latest react-native version, this is still an issue.

**Comment by cpojer** [comment]
As of today, the second argument of `append` inside of React Native is typed as `FormDataValue` (not `FormDataPart`) which is typed as `any` so it shouldn't conflict with any typings from Flow.
