### ISSUE TITLE
Android inline image width/height is reversed.

### ISSUE THREAD

**Issue by bennyguitar** [facebook/react-native#13191]
This is on master as of issue creation.

You can see the problem right here:

https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/text/frescosupport/FrescoBasedReactTextInlineImageShadowNode.java#L138

**Comment by ide** [comment]
Anyone want to submit a PR and small test plan?

**Comment by Nick177** [comment]
Hello, I see that the width and height are reversed in the link provided by "bennyguitar". I am new to React-Native, but I was wondering if I can still help out.

**Comment by Yurii-Laguta** [comment]
@ide PR sounds easy, test plan is harder, I would create this textView with some demo image, and then check with Espresso on Android that width and height of view is same as predefined image.
Any suggestions on tests?

**Comment by bennyguitar** [comment]
@Yurii-Laguta looks like it's already in: https://github.com/facebook/react-native/commit/c3110963f2517b3ef8b80f5d510b8dd41a67350d

**Comment by ide** [comment]
A test plan is not quite the same as automated tests. Just providing repro steps and screenshots is helpful.

**Comment by bennyguitar** [comment]
The test plan should be:

* Create a `<Text>` component that wraps an `<Image>` component.
* Make sure the style of the image contains different width and height
* Verify visually that the width/height passed in are respected.

Before this issue, you could pass in `width: 20, height: 100` and see the opposite - an image wider than it is tall. With the change, it would be a taller image.

Basically:

```
<Text>
  <Image source={img} style={{width: 20, height: 100}} />
</Text>
```

**Comment by hoangpham95** [comment]
Should be closed as the PR was being imported into `master`: https://github.com/facebook/react-native/commit/c3110963f2517b3ef8b80f5d510b8dd41a67350d
