### ISSUE TITLE
[Navigator] App crashes when updating main screen after "Toggle in-call status bar"

### ISSUE THREAD

**Issue by PhilippKrone** [facebook/react-native#1319]
Hello,

in my app, I'm reacting on the change of the statusBarHeight to move objects further up or down. Basically, my main screen looks like that:
````javascript
      <View style={[styles.flex1, this.getStatusBarHeight()]}>
        <Navigator
           ...
         />
      </View>
````

The method "getStatusBarHeight()" returns "20 - currentStatusBarHeight", which is again triggered by using @brentvatne s status bar size update snippet (https://github.com/brentvatne/react-native-status-bar-size).

I dont know since which version exactly, but on 0.4.4, I get the following error stack:
2015-05-17 15:50:27.008 [error][tid:com.facebook.React.JavaScript] "Error: null is not an object (evaluating 'prevComponentInstance._currentElement')
 stack: 
  _updateRenderedComponent                 index.ios.bundle:17090
  _performComponentUpdate                  index.ios.bundle:17072
  updateComponent                          index.ios.bundle:16992
  ReactCompositeComponent_updateComponent  index.ios.bundle:5155
  receiveComponent                         index.ios.bundle:16856
  receiveComponent                         index.ios.bundle:5283
  updateChildren                           index.ios.bundle:21467
  _updateChildren                          index.ios.bundle:21232
  updateChildren                           index.ios.bundle:21206
  receiveComponent                         index.ios.bundle:18568
  receiveComponent                         index.ios.bundle:5283
  _updateRenderedComponent                 index.ios.bundle:17093
  _performComponentUpdate                  index.ios.bundle:17072
  updateComponent                          index.ios.bundle:16992
  ReactCompositeComponent_updateComponent  index.ios.bundle:5155
  receiveComponent                         index.ios.bundle:16856
  receiveComponent                         index.ios.bundle:5283
  _updateRenderedComponent                 index.ios.bundle:17093
  _performComponentUpdate                  index.ios.bundle:17072
  updateComponent                          index.ios.bundle:16992
  ReactCompositeComponent_updateComponent  index.ios.bundle:5155
  receiveComponent                         index.ios.bundle:16856
  receiveComponent                         index.ios.bundle:5283
  _updateRenderedComponent                 index.ios.bundle:17093
  _performComponentUpdate                  index.ios.bundle:17072
  updateComponent                          index.ios.bundle:16992
  ReactCompositeComponent_updateComponent  index.ios.bundle:5155
  receiveComponent                         index.ios.bundle:16856
  receiveComponent                         index.ios.bundle:5283
  updateChildren                           index.ios.bundle:21467
  _updateChildren                          index.ios.bundle:21232
  updateChildren                           index.ios.bundle:21206
  receiveComponent                         index.ios.bundle:18568
  receiveComponent                         index.ios.bundle:5283
  _updateRenderedComponent                 index.ios.bundle:17093
  _performComponentUpdate                  index.ios.bundle:17072
  updateComponent                          index.ios.bundle:16992
  ReactCompositeComponent_updateComponent  index.ios.bundle:5155
  receiveComponent                         index.ios.bundle:16856
  receiveComponent                         index.ios.bundle:5283
  _updateRenderedComponent                 index.ios.bundle:17093
  _performComponentUpdate                  index.ios.bundle:17072
  updateComponent                          index.ios.bundle:16992
  ReactCompositeComponent_updateComponent  index.ios.bundle:5155
  receiveComponent                         index.ios.bundle:16856
  receiveComponent                         index.ios.bundle:5283
  updateChildren                           index.ios.bundle:21467
  _updateChildren                          index.ios.bundle:21232
  updateChildren                           index.ios.bundle:21206
  receiveComponent                         index.ios.bundle:18568
  receiveComponent                         index.ios.bundle:5283
  _updateRenderedComponent                 index.ios.bundle:17093
  _performComponentUpdate                  index.ios.bundle:17072
  updateComponent                          index.ios.bundle:16992
  ReactCompositeComponent_updateComponent  index.ios.bundle:5155
  receiveComponent                         index.ios.bundle:16856
  receiveComponent                         index.ios.bundle:5283
  _updateRenderedComponent                 index.ios.bundle:17093
  _performComponentUpdate                  index.ios.bundle:17072
  updateComponent                          index.ios.bundle:16992
  ReactCompositeComponent_updateComponent  index.ios.bundle:5155
  receiveComponent                         index.ios.bundle:16856
  receiveComponent                         index.ios.bundle:5283
  updateChildren                           index.ios.bundle:21467
  _updateChildren                          index.ios.bundle:21232
  updateChildren                           index.ios.bundle:21206
  receiveComponent                         index.ios.bundle:18568
  receiveComponent                         index.ios.bundle:5283
  _updateRenderedComponent                 index.ios.bundle:17093
  _performComponentUpdate                  index.ios.bundle:17072
  updateComponent                          index.ios.bundle:16992
  ReactCompositeComponent_updateComponent  index.ios.bundle:5155
  receiveComponent                         index.ios.bundle:16856
  receiveComponent                         index.ios.bundle:5283
  _updateRenderedComponent                 index.ios.bundle:17093
  _performComponentUpdate                  index.ios.bundle:17072
  updateComponent                          index.ios.bundle:16992
  ReactCompositeComponent_updateComponent  index.ios.bundle:5155
  performUpdateIfNecessary                 index.ios.bundle:16889
  performUpdateIfNecessary                 index.ios.bundle:5301
  runBatchedUpdates                        index.ios.bundle:4860
  perform                                  index.ios.bundle:6287
  perform                                  index.ios.bundle:6287
  perform                                  index.ios.bundle:4804
  flushBatchedUpdates                      index.ios.bundle:4884
  ReactUpdates_flushBatchedUpdates         index.ios.bundle:5155
  closeAll                                 index.ios.bundle:6360
  perform                                  index.ios.bundle:6301
  batchedUpdates                           index.ios.bundle:14131
  batchedUpdates                           index.ios.bundle:4819
  <unknown>                                index.ios.bundle:7772
  applyWithErrorReporter                   index.ios.bundle:7524
  guardReturn                              index.ios.bundle:7546
  processBatch                             index.ios.bundle:7771
 URL: http://localhost:8081/index.ios.bundle
 line: 17090
 message: null is not an object (evaluating 'prevComponentInstance._currentElement')"

In case it is absolutely necessary, I can try to build my app back to a working version to determine since which version this is not working anymore, but since it would take several hours, I'd like to avoid it.

Regards
Philipp

**Comment by PhilippKrone** [comment]
@brentvatne have you ever seen an error stack like this using your snippet?

**Comment by brentvatne** [comment]
@PhilippKrone - does this happen even if you remove the status bar sizing code? Seems like a Navigator issue

**Comment by brentvatne** [comment]
@PhilippKrone - going to close this issue for now, if you're still having this issue it would be *awesome* if you could reopen with a runnable example [as per contributing guidelines](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#reporting-new-issues)

**Comment by PhilippKrone** [comment]
@brentvatne I still have this issue, but am not able to make a runnable example.. Any chance to have a discussion, so I can focus my effort here?

**Comment by brentvatne** [comment]
@philikon - sure - I've never run into this issue, as per the above comment - if you take out the status bar related code, does it still crash?

**Comment by PhilippKrone** [comment]
Yea, its not working without the status bar code as well. It seems like a re-render (either triggered via setState or via forceUpdate()) is resulting in this error stack.

**Comment by brentvatne** [comment]
I would remove all calls to `forceUpdate` and see if that fixes it

**Comment by philikon** [comment]
Hi, I think @brentvatne mentioned me by mistake, but I'm happy to chime in:

We use `Navigator.js` heavily in Facebook's Ads Manager app (in fact, that's mostly what it was written for). You can get it to adapt to the varying window height when on a call / tethering / etc. without the need for `forceUpdate` and changing styles:

    <Navigator
      sceneStyle={styles.scene}
      />

with `styles.scene` being

    {
      marginTop: Navigator.NavigationBar.Styles.General.TotalNavHeight,
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
    }

By not setting an explicit `height`, the view will simply adapt when the window size changes due to the status bar expanding.

**Comment by brentvatne** [comment]
Haha, sorry @philikon I indeed mention you by mistake ;) Best mistake I've made today

**Comment by despairblue** [comment]
@philikon Do you still get the error when you debug the app in chrome? I get a similar stack trace when changing a listview's datasource, but only if I run the app on the device, when I debug the app in chrome everything works :confused:

**Comment by cosmith** [comment]
I'm seeing the same error with Navigator and I'm not using `forceUpdate` and it's only happening on device, not when running in the Chrome debugger... I thought running in the Safari debugger might give more info but it's broken (see #2464). @despairblue did you manage to fix it?

**Comment by cosmith** [comment]
Turns out it was a completely unrelated error in one of my components `render` method that was failing and crashing with this very obscure error when setting the state... Check that all your components are rendering normally if you see this error!

**Comment by BigPun86** [comment]
+1 @cosmith

**Comment by satya164** [comment]
Doesn't `this.getStatusBarHeight()` return a number, and not a style object? In that case you shouldn't be passing it directly to style prop.

**Comment by jsierles** [comment]
@facebook-github-bot answered

**Comment by facebook-github-bot-0** [comment]
Closing this issue as @jsierles says the question asked has been answered. Please help us by asking questions on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.
