### ISSUE TITLE
Widget suggestion : Carousel

### ISSUE THREAD

**Issue by jaygarcia** [facebook/react-native#132]
Our current choice for a Carousel-like widget is the Scroll View oriented in a horizontal mode, but that doesn't give us the milky smooth locking of a carousel.

Hopefully, after i'm done w/ this VGM player app, I'll have the cycles (and skills) to build these types of custom components for submission into this repo.

**Comment by ppong** [comment]
@nick the Carousel sounds awesome. Unfortunately https://github.com/nick/react-native/blob/master/Examples/Weather/js/components/Carousel.js leads to a 404.

**Comment by nick** [comment]
@ppong oops - try now

**Comment by ppong** [comment]
@nick thanks! it works now :+1:

**Comment by nick** [comment]
I've now released this as an npm module at http://github.com/nick/react-native-carousel

**Comment by brentvatne** [comment]
@nick - nice one, thanks! :+1:
