### ISSUE TITLE
Can't select first option from Picker

### ISSUE THREAD

**Issue by Talor-A** [facebook/react-native#13204]
### Description

Using a Picker, onValueChange has no effect when the first item is selected, but works for the rest. 
### Reproduction Steps and Sample Code

[Here's](https://sketch.expo.io/rkMh8jKne) a sketch project demonstrating the bug.

### Additional Information

* React Native version: 0.43.0-rc.1 on my device, don't know the version used on Expo 
* Platform: Both
* Development Operating System: Linux

**Comment by Talor-A** [comment]
Sorry, this was fixed by adding a selectedValue prop.

**Comment by malexsan1** [comment]
This seems to be happening to me too.

[Here's](https://snack.expo.io/SkzTmR16x) a sketch with my code. I've added the *selectedValue* to the Picker component and I still cannot select the first option.

Selecting any other option is working fine and after that everything works fine, including selecting the first item.

Currently experiencing this using ReactNative 0.42.3.

**Comment by renancsoares** [comment]
Same for me... it automatically sets the first option as value so you can't select it, all others options are working properly.

I have this problem usign RN 0.44.2.

**Comment by SirPhemmiey** [comment]
Has anyone found a way through this issue?
