### ISSUE TITLE
Packager takes forever when parsing a large js file

### ISSUE THREAD

**Issue by seantempesta** [facebook/react-native#13208]
Using react-native "0.42" and Clojurescript, the packager takes 10 minutes to parse my `index.[ios|android].js` file.  Please correct me if I'm wrong, but the packager is parsing it just to get a list of `require statements`?  Because the Clojurescript compiler has already done all the necessary javascript transformations and minified the file.  

Is there a way for me to specify a list of the `require`'d packages and just have the react packager include the index file w/o modification?  Barring that, is there a way to increase the amount of threads/processes running?  Right now two processes are launching and I can't figure out how to increase it.

**Comment by hramos** [comment]
GitHub Issues are not meant to be used for questions. 
Questions can be asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

If you feel this is an issue that should be tracked here on GitHub, please make sure to follow the issue [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md). This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!
