### ISSUE TITLE
Running out of memory when using hundreds of same Image

### ISSUE THREAD

**Issue by ericapply** [facebook/react-native#13206]
### Description

I am using react-native-maps to draw about 750 markers on the map.
Each marker is using same Image

### Reproduction Steps and Sample Code

```
const markerImage = <Image source={images.marker} />;
export default class Main extends Component {
  render() {
    return (
      <MapView style={StyleSheet.absoluteFill}>
        { coordinates.map(coordinate => {
              return (
                <Marker
                  key={coordinate.id}
                  coordinate={coordinate}
                  children={markerImage}
                />
              );
            })}
      </MapView>
    )
  }
}
```

### Possible Solution
Re-using UIImage
http://stackoverflow.com/questions/25555778/optimising-custom-marker-image-performance-with-google-maps-sdk-for-ios

However, I do not know how to do this in React Native as React abstracts away the view layer.

### Additional Information

* React Native version: ["0.41.2"]
* react-native-maps: ["^0.13.0"]
* Platform: [both]
* Development Operating System: [MacOS]
* Dev tools: [Xcode: 8.3, iPhone 7(10.3), GalaxyS6(6.0.1)]

![image](https://cloud.githubusercontent.com/assets/26330965/24479019/30f1a13e-1492-11e7-9f11-9dc2c24d9b14.png)

![image](https://cloud.githubusercontent.com/assets/26330965/24479005/26a5b166-1492-11e7-9636-3f3b5023beb0.png)

**Comment by vonovak** [comment]
this is a stackoverflow question

**Comment by ericapply** [comment]
https://stackoverflow.com/questions/43105313/running-out-of-memory-when-using-hundreds-of-same-image
