### ISSUE TITLE
[ListView] How to implement endless scroll from bottom & top?

### ISSUE THREAD

**Issue by ranyefet** [facebook/react-native#1320]
Hello all,

I'm trying to implement something similar to [Sunrise](https://s-media-cache-ak0.pinimg.com/originals/c7/c8/1b/c7c81bf3b855be2b8e932763091d17a5.jpg)

Basically I have a list which I want to:

1. Load new items when scroll reach to end and add them to the end of the list ```onEndReached```
2. Load old items when scroll reach to top and add them to the beginning of the list
3. I need to show section headers ```renderSectionHeader``` and I need to know when the current section was changed.
4. I want to jump into specific section in the list

Is it possible to implement it with ```ListView```? If so, do you have any tips on how to do that?

Your help is appriciated,
Ran.

**Comment by TouchQQ** [comment]
my god, item 1 and 2 is opposite to mine..

**Comment by hongru** [comment]
We just implement a waterfall listview. 
checking whether the scrollview reached the bottom by `RCTViewManager.measureLayout`.
then fetch data for next section list and try to merge data to the `dataSource` of `ScrollView`.
As the `dataSource` changed by `setState` , the scrollView will be rerendered.

But in this case, the scrollview will be complete rerendered everytime when you merge data to `dataSource`. 

I have no better idea to implement this

**Comment by brentvatne** [comment]
These types of how-to questions are best suited for StackOverflow - if you run into a bug in the process then please report that here! :smile:
