### ISSUE TITLE
[Android] Modal backgroundColor: rgba(0, 0, 0, 0.3) is not work in RN 0.41?

### ISSUE THREAD

**Issue by 438198602** [facebook/react-native#13213]
[Android] When I use {backgroundColor : rgba(0, 0, 0, 0.3)} in Modal , It's ok on debug, but in the release apk , show backgroundColor is '#000', the opacity is not work. My react-native version is 0.41,(0.40 is ok). who can help me?

**Comment by 438198602** [comment]
why???

**Comment by hramos** [comment]
Please read the issue template.

**Comment by 438198602** [comment]
@hramos I cannot find the issue with my problem in the issue template. help me, please.

**Comment by hramos** [comment]
There's a template when a new issue is created. Make sure to fill it out in its entirety.
