### ISSUE TITLE
PanResponder with 0 opacity, doesn't detect any gestures

### ISSUE THREAD

**Issue by liubko** [facebook/react-native#1321]
I have a view with 0 opacity, smth like:
```
<View style={{opacity: 0}}
      accessible={true}
      {...this.responder.panHandlers} />
```

so `onPanResponderMove` never gets called, unless I set opacity > 0.01

**Comment by skevy** [comment]
This is iOS expected behavior - views with 0 opacity don't receive touches (react native or not)

**Comment by liubko** [comment]
ok, then. Issue may be closed.

**Comment by liubko** [comment]
```
backgroundColor: 'transparent'
```
 saved me
