### ISSUE TITLE
Hot Reloading not working with Navigator (refreshes entire route stack to initialRoute instead of just the component)

### ISSUE THREAD

**Issue by claykohut** [facebook/react-native#13224]
### Description

I'm having trouble getting hot reloading to work on our app. Changes seem to be submitting / the app shows a banner showing that changes are applied but nothing happens / updates.

If I change the entry point index component to be a stateful component which returns the App component, then changes seem to update but the Navigator component resets to the initial route.

Can anyone please help!?

In the state that causes an entire app refresh, the App file is structured like:
```
render(){
     <Provider>
          <Navigator {props here} />
     </Provider>
}
```

### Additional Information

* React Native version: 0.31.0
* Platform: iOS
* Development Operating System: MacOS
* Dev tools: Xcode

**Comment by hramos** [comment]
`Navigator` is no longer a part of React Native (it was deprecated earlier this year, and will not ship in the next stable release, 0.43). I highly suggest using `react-navigation` in its place. If this is also an issue in `react-navigation`, feel free to open an issue.
