### ISSUE TITLE
Switch onTintColor bug on Android

### ISSUE THREAD

**Issue by henrikra** [facebook/react-native#13221]
### Description
When setting `onTintColor` prop for component `Switch` it works as expected. But when you change the value of the `Switch` it has the default green `onTintColor` for a fraction of a second.

### Reproduction Steps and Sample Code
Here the bug is reproduced: https://sketch.expo.io/B1vEAochg

### Solution
I think something needs to be tweaked in the Java side of the `Switch` component

### Additional Information
* React Native version: 0.42.0
* Platform: Android
* Development Operating System: MacOS

**Comment by hramos** [comment]
Thanks for the repro! Looks like a bug. Here's a GIF of the repro for anyone who might look into this:

![](https://d3uepj124s5rcx.cloudfront.net/items/2T2z0u1p003u053y3J2v/Screen%20Recording%202017-03-30%20at%2011.19%20AM.gif?v=f85dc61d)

**Comment by satya164** [comment]
If you go to android system settings and tap on a switch, you'll see the same behaviour.

**Comment by henrikra** [comment]
@satya164 So basically Android has made bad UI component? :/

**Comment by satya164** [comment]
I guess

**Comment by satya164** [comment]
Probably we could animate the color change to make it feel nicer.

**Comment by henrikra** [comment]
I would not make hacks to this native component. If it is like that then I would close this :)

**Comment by filipemonteiroth** [comment]
@henrikra I'm using this component instead of native one:

[https://github.com/poberwong/react-native-switch-pro](url)

**Comment by hramos** [comment]
Agree with @henrikra.

**Comment by satya164** [comment]
Well, it's not a hack, and can be done is js, but anyway.
