### ISSUE TITLE
[Idea] List of missing properties for existing components

### ISSUE THREAD

**Issue by NathanFlurry** [facebook/react-native#1323]
Hello,

I was chatting with @vjeux on Twitter, in which he suggested that I make an issue listing component properties that are missing, so here is a list of properties that should ideally be added, in my opinion:

### Image
- renderingMode: UIImageRenderingMode
- tintColor: Color *(replaces all pixels matching their alpha, this depends on the renderingMode property)*
- filter: CIFilter
- ~~resizeMode: UIViewContentMode *(options in React Native are not extensive to what is available in iOS)*~~
- source: [{ uri: String}] *(what I mean by this is that animation should be possible, as it is in `UIImageView`; this would be done by giving it a list of URIs)*
- animationDuration: Number
- animationRepeatCount: Number
- animating: Bool

## MapView
- animateRegionChange: Bool *(this is for when the `region` property is changed by the program; the transition should not be forced to be instant or animated)*
- mapType: MKMapType
- showBuildings: Bool
- heading, pitch, and altitude: Number *(these values pertain to the `MKMapCamera`)*

## Navigator
- ~~Merge `NavigatorIOS` into `Navigator`. It seems a bit redundant.~~ (not going to happen)
- *(method)* getNavigationBar() -> NavigationBar
- ~~Remove the `navigationBar` property from `Navigator`, it should be a ~~ (this is a discussion in itself)

## NavigationBar
~~*(I'll let the React engineers design this API themselves, it is largely self explanatory)*~~ (better suited for external lib)

## PickerIOS
- showsSelectionIndicator: Bool

## PickerIOS.Item
- ~~Needs documentation.~~ ([here](https://facebook.github.io/react-native/docs/tabbarios-item.html#content))
- What this displays should be able to be a view.

## SegmentedControllerIOS
- Segments should be able to have images instead of text.

## SliderIOS
- minimumValueImage, maximumValueImage, minimumTrackImage, maximumTrackImage, and currentThumbImage: Image
- ~~thumbTintColor: Color~~ (implemented now)

## TabBarIOS
- ~~tintColor: Color~~ (implemented now)

## View
- tintColor: Color *(see Apple documentation for this behavior, it tints elements and images with the correct rendering mode inside it a certain color)*
- Somehow implement the power of CGLayer.
- maskNode: Node

I hope this helps document some missing functionality to React Native.

That being said, I would also like to remind all React Native engineers that, as @tomocchino said in [this talk](https://www.youtube.com/watch?v=KVZ-P-ZI6W4), UI elements that mimic native UI elements are **not good**. From what I can tell, various APIs in React Native, such as the `navigationBar` property in `Navigator`, custom UI elements are being encouraged.

I had lots of fun hacking around with React Native this weekend -- it seems to have a lot of potential. I'll be sure to check it out again a couple months down the road to see how it matures.

Thanks,
Nathan

**Comment by brentvatne** [comment]
@NathanFlurry - thanks for the list! If anyone wants to pick items off of this and implement them, that would be helpful

**Comment by chirag04** [comment]
@brentvatne closable?
