### ISSUE TITLE
BUG: onNewIntent is not called when app is killed by the system due to low memory

### ISSUE THREAD

**Issue by carlobambo** [facebook/react-native#13233]
### Description

onNewIntent is not getting called when the app is killed by the system due to low memory or by using memory booster app.

### Reproduction Steps and Sample Code

1. Set `android:launchMode="singleTop"` in android manifest
2. Install react-native-push-natifications
2. Open the app.
3. Put app in background.
4. Clear memory by using Solo Cleaner
5. Notify the app using GCM
6. Open the app by tapping on the notification banner.

Result:
onNewIntent in RNPushNotification.java is not called but onNewIntent on MainActivity.java is called.

### Additional Information

* React Native version: 0.42.0
* Platform: Android
* Development Operating System: MacOS

**Comment by hramos** [comment]
What is `RNPushNotification.java` here? Do you think you can add a bit more context or sample code to help reproduce this?

**Comment by hramos** [comment]
Closing this issue as we haven't heard back from the author.
