### ISSUE TITLE
Cannot Add a child that doesn't have a YogaNode to a parent with out a measure function

### ISSUE THREAD

**Issue by joshjconlin** [facebook/react-native#13243]
I've been trying to get React Native up and running for a project I'm working on. It works beautifully for IOS, however on Android every time I try to use a Text component I keep getting the error 
```
Cannot add a child that doesn't have a 
YogaNode to a parent without a measure function! 
Trying to add a ReactVirtualTextShadowNode to a NativeViewWrapper.
```
my entire code is
```
import React, { PureComponent } from 'react';
import { Text } from 'react-native';

class App extends PureComponent  {

render() {
    return (
      <Text>Hello World</Text>
    );
  }
}

export default App;
```

I'm using react native 0.4.3
Any ideas what could be causing this and how I could fix it?

**Comment by janicduplessis** [comment]
Does it work if you wrap the Text inside a view? It's possible it doesn't work because you app is only a Text node and might require at least one View, at least on Android.

**Comment by joshjconlin** [comment]
I just tried that and I still got the same error unfortunately

**Comment by hramos** [comment]
I'm not able to reproduce this on Snack, using the exact same code posted here: https://snack.expo.io/HJw8alx6e

Any chance you can provide a repro?

**Comment by joshjconlin** [comment]
its a private repo, so unfortunately not, I can provide my package.json though to show all the dependencies and versions i'm using.
```

  "name": "app",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "eslint": "^3.18.0",
    "eslint-config-airbnb": "^14.1.0",
    "jest-expo": "^0.3.0",
    "react-test-renderer": "~15.4.1",
    "reactotron-apisauce": "^1.9.1"
  },
  "scripts": {
    "start": "react-native start",
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "test": "node node_modules/jest/bin/jest.js --watch"
  },
  "dependencies": {
    "apisauce": "^0.11.0",
    "babel-preset-react-native-stage-0": "^1.0.1",
    "immutable": "^3.8.1",
    "react": "16.0.0-alpha.3",
    "react-native": "0.43.0-rc4",
    "react-native-svg": "^5.1.6",
    "react-native-vector-icons": "^4.0.0",
    "react-redux": "^5.0.3",
    "reactotron-react-native": "^1.9.1",
    "reactotron-redux": "^1.9.1",
    "reactotron-redux-saga": "^1.9.1",
    "redux-form": "^6.6.0",
    "redux-persist": "^4.5.0",
    "redux-saga": "^0.14.3",
    "reselect": "^3.0.0"
  }
}
```

**Comment by joshjconlin** [comment]
also this is the MainApplication.java
```
package com.readerzone;

import android.app.Application;

import com.facebook.react.ReactApplication;
import com.horcrux.svg.SvgPackage;
import com.oblador.vectoricons.VectorIconsPackage;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new SvgPackage(),
            new VectorIconsPackage()
      );
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
  }
}

```
Let me know if you need anything else

**Comment by joshjconlin** [comment]
I just updated to the newest release of react native and it seems to have resolved this issue;

**Comment by ryands17** [comment]
This issue is still prevailing on Android
React Native version: 0.49.1

**Comment by johngoren** [comment]
I got this error in RN 0.49.1 in some conditional JSX that relied on a value's being truthy to decide whether a View shows up or not. I fixed the error using the classic double exclamation !!, i.e. "{!!value" instead of "{value}."

**Comment by parthgandhi7** [comment]
This is the stack trace i am getting
```
Cannot add a child that doesn't have a YogaNode to a parent without a measure function! (Trying to add a 'ReactVirtualTextShadowNode' to a 'LayoutShadowNode')
addChildAt
    ReactShadowNode.java:181
setChildren
    UIImplementation.java:398
setChildren
    UIManagerModule.java:310
invoke
    Method.java
invoke
    JavaMethodWrapper.java:363
invoke
    JavaModuleWrapper.java:162
run
    NativeRunnable.java
handleCallback
    Handler.java:739
dispatchMessage
    Handler.java:95
dispatchMessage
    MessageQueueThreadHandler.java:31
loop
    Looper.java:148
run
    MessageQueueThreadImpl.java:194
run
    Thread.java:818
```
I am using 
_react-native-cli: 2.0.1
react-native: 0.49.3_

**Comment by parthgandhi7** [comment]
Aah silly error but still the stack trace is too confusing:
I had my button tag like:
 ```
   <Button
      transparent
      style={styles.nextContainer}
      onPress={props.onPress}
    >
      NEXT
    </Button>
```
which was causing the error . This used to work in old react-native. But now, no string values should be without the **<Text>** tag.

So i resolved it by replacing the above code with 
```
    <Button
      transparent
      style={styles.nextContainer}
      onPress={props.onPress}
    >
      <Text>NEXT</Text>
    </Button>
```

**Comment by dcalixto** [comment]
Same issue here on a simple Input Component.
react-native: 0.49.3

**Cannot add a child that doesn't have a YogaNode to a parent without a measure function! (Trying to add a 'ReactVirtualTextShadowNode' to a 'LayoutShadowNode')**


```
import React from 'react';
import { TextInput, View, Text } from 'react-native';

const Input = ({ label, value, onChangeText, placeholder, secureTextEntry }) => {
  const { inputStyle, labelStyle, containerStyle } = styles;

  return (
    <View style={containerStyle}>
      <Text>
      
      <Text style={labelStyle}>{label}</Text>
      <TextInput
        secureTextEntry={secureTextEntry}
        placeholder={placeholder}
        autoCorrect={false}
        style={inputStyle}
        value={value}
        onChangeText={onChangeText}
      />
      </Text>
    </View>
  );
};

const styles = {
  inputStyle: {
    color: '#000',
    paddingRight: 5,
    paddingLeft: 5,
    fontSize: 18,
    lineHeight: 23,
    flex: 2
  },
  labelStyle: {
    fontSize: 18,
    paddingLeft: 20,
    flex: 1
  },
  containerStyle: {
    height: 40,
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center'
  }
};

export { Input };
```

**Comment by Grimmjowjack** [comment]
Thank you @parthgandhi7

**Comment by aloifolia** [comment]
The approach presented by @parthgandhi7 works for me, too. I think the error message should be vastly improved, though.

**Comment by Chozzle** [comment]
I'm getting the same error on RN 0.50.3. Running on Android emulator API 23.

**Comment by xeki** [comment]
Writing each tags on a separate new lines has resolved the same problem for me.

**Comment by LiudmilaE** [comment]
Thank you @parthgandhi7 !!!

**Comment by kgwadhwani** [comment]
Thank you @parthgandhi7

**Comment by SkariDamm** [comment]
Got the same error when trying to render the following JSX:

`
<Card title="All done!">
  <Text style={{ marginBottom: 10 }}>There's no more content here!</Text>
  <Button backgroundColor="#03A9F4" title="Get more!" />>
</Card>
`

If you look very closely you'll see an extra '>' following the Button declaration. That's all I needed to remove for it to successfully render.

**Comment by oguennec** [comment]
I had the same error with a semi column ";" wrongly placed inside the JSX on line 4.
So this error looks like generic for malformed JSX.

>       case 'sun':
>         return (
>           <View style={styles.iconContainer}>
>               <MyIcon name={''} size={18} color={colors.yellow} />;
>           </View>
>         );

**Comment by wuxiaojun123** [comment]
this is still happening on 0.50.4

**Comment by gopaldevra** [comment]
Some times you need to remove the extra spaces between the angle brackets to get rid of it.

**Comment by wuxiaojun123** [comment]
@gopaldevra Thank you very much!!!

**Comment by RoshanSalian** [comment]
**Removing comments inside Component solved it for me.**

I wasted more than a day on this and found no useful solution anywhere. I got this error because I had put a comment inside a component. On removing that comment the app did run for me.

**Comment by jsm** [comment]
Also had this in something slightly different, to do with using `&&` logic for component mounting.

I had something like

```
render {
  <View>
    { val === 'a' && renderA() }
    { val === 'b' && renderB() }
    { val === 'c' && renderC() }
  </View>
}
```

And fixed it by moving those out into it's own function

```
renderAlphabet (
  if (val === 'a') {
    return renderA();
  } else if (val === 'b') {
    return renderB();
  } else if (val === 'c') {
    return renderC();
  } 

  return null;
)

render {
  <View>
    { this.renderAlphabet() }
  </View>
}
```

**Comment by elmawardy** [comment]
I had this when i add a space before comment in JSX

```
<View> {/*Reviews*/}   <-- error
</View>
```

and works fine after removing the space or putting the comment at the second line

```
<View>{/*Reviews*/} <-- works fine
</View>

<View>{/*Reviews*/} <-- works fine
</View>
```

**Comment by terryttsai** [comment]
Thanks @oguennec, solved the issue for me!

**Comment by pjohanb** [comment]
I got this error message when I tried to render some text outside of a JSX text element.

`<View> {someTextConstant} </View>` <- Not working
`<View> <Text> {someTextConstant} </Text> </View>` <- Working

**Comment by bdelville** [comment]
I had this when adding an extra ) in my JSX:
`return (
      <View>
        <Text>{this.props.textEmpty}</Text>)
      </View>
    );`

**Comment by peniqliotuv** [comment]
I had this same silly error when using a `<Modal />` component.
Gotta wrap your stuff in `<Text>`

**Comment by under** [comment]
I also had this with some conditional JSX like
`{ foobar && <View/> }`
Could fix by changing it to
`{ foobar ? <View/> : null }`

**Comment by ThaJay** [comment]
not using `<Text>to wrap text</Text>` gave this stacktrace
```01-25 15:39:25.337 26410 26443 E AndroidRuntime: java.lang.RuntimeException: Cannot add a child that doesn't have a YogaNode to a parent without a measure function! (Trying to add a 'ReactRawTextShadowNode' to a 'LayoutShadowNode')
01-25 15:39:25.337 26410 26443 E AndroidRuntime: 	at com.facebook.react.uimanager.ReactShadowNodeImpl.addChildAt(ReactShadowNodeImpl.java:199)
01-25 15:39:25.337 26410 26443 E AndroidRuntime: 	at com.facebook.react.uimanager.ReactShadowNodeImpl.addChildAt(ReactShadowNodeImpl.java:54)
01-25 15:39:25.337 26410 26443 E AndroidRuntime: 	at com.facebook.react.uimanager.UIImplementation.setChildren(UIImplementation.java:472)
01-25 15:39:25.337 26410 26443 E AndroidRuntime: 	at com.facebook.react.uimanager.UIManagerModule.setChildren(UIManagerModule.java:436)
01-25 15:39:25.337 26410 26443 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-25 15:39:25.337 26410 26443 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
01-25 15:39:25.337 26410 26443 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
01-25 15:39:25.337 26410 26443 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
01-25 15:39:25.337 26410 26443 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:754)
01-25 15:39:25.337 26410 26443 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
01-25 15:39:25.337 26410 26443 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
01-25 15:39:25.337 26410 26443 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:163)
01-25 15:39:25.337 26410 26443 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
01-25 15:39:25.337 26410 26443 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:760)

```

**Comment by alainib** [comment]
Holy sh**t, spend an hour with this bug because i have :  

`<View> <Row>`  <- space between two markup make the android app crash completly (inside a modal)

`<View><Row>`  <- this work

**Comment by Murmand** [comment]
Oh my god. 3 hours!! And the problem was that prittier adds semicolon (`;`) behind curle bracket (`}`) and RN wants to render `;` as a text immediately in a `<View>`.

**Comment by alainib** [comment]
@Murmand, i use microsoft vs code, it is very nice to found syntaxe error even in render method mixing js and view code

**Comment by evanjmg** [comment]
There needs to be better feedback for debugging these issues

**Comment by lzxxxxx** [comment]
I was having problems at this time:
using `ScrollView` not set inside `View`
```
<ScrollView>  //error
  <View></View>
  <View></View>
  ...
</ScrollView>
``` 

```
<ScrollView>  //works well
  <View>
    <View></View>
    <View></View>
      ...
  </View>
</ScrollView>
```

**Comment by LAITONEN** [comment]
In my case the issue was that I had an unnecessary character inside JSX:

`render() {
    return(
        <View>
            <Text>Lalala</Text>;
        </View>
    )
}`

Which is the semicolon at the end of Text line. Removing it fixed the error.

**Comment by xemasiv** [comment]
In my case it's the fucking comment in the copy-pasted example lmao :100:

**Comment by Manish3323** [comment]
i dont have any semicolon or any comments in my render function still it gives the same error .??

**Comment by evanjmg** [comment]
This is always caused by a JSX syntax error, you can forget to close an element or have invalid characters in your JSX - there are endless possibilities. The error messaging for this error needs to improve and point to source of the issue. Right now, it doesn't tell you anything

**Comment by Manish3323** [comment]
i found this link . can anyone  help me  explaining the below code snippet from the following link .
[`https://www.javatips.net/api/ComicBook-master/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/ReactShadowNode.java`](url)

`    // If a CSS node has measure defined, the layout algorithm will not visit its children. Even
    // more, it asserts that you don't add children to nodes with measure functions.
    if (mYogaNode != null && !mYogaNode.isMeasureDefined()) {
      YogaNode childYogaNode = child.mYogaNode;
      if (childYogaNode == null) {
        throw new RuntimeException(
          "Cannot add a child that doesn't have a YogaNode to a parent without a measure " +
            "function! (Trying to add a '" + child.getClass().getSimpleName() + "' to a '" +
            getClass().getSimpleName() + "')");
      }
      mYogaNode.addChildAt(childYogaNode, i);
    }
    markUpdated();`


i am guessing that i have missed on to CSS in my native project.
i will look into that .
correct me if my guess is wrong .

hopefully, the above link could clear some doubts.

**Comment by ritikrishu** [comment]
In my case, `actionText` was `''` changing it to `' '`, resolved the issue.

**Comment by Karim-Bensalah** [comment]
Inside the view you only have to write a text , i've seen many of you using ";" inside the view and that's wrong and causes this problem .

**Comment by Manish3323** [comment]
@Karim-Bensalah i tripled checked my entire directory.

[here is the link to code.](https://github.com/Manish3323/reactNative)

Please check if you find anything help me correct it. I may have missed on some thing really small.

Thanks in Advance.

**Comment by steveccable** [comment]
FWIW, I encountered this same (fairly useless) error stack with the following code:

```
const renderedItem = someOtherRenderFunc(); // My app has a lot of component nesting and reusability, making this a bit open-ended in what it might return.  Assumed to be JSX
return (
  <View style={someStyle}>
    {renderedItem}
  </View>
);
```

And was fixed by just replacing `{renderedItem}` with `{renderedItem || null}`.  By the look of it, something falsey was coming through here (above comments indicate it may be the empty string, though if memory serves I have had RN yell for passing `undefined` in JSX outside of a Text node, which would be more concerning.  Of course strings should be in Text, but undefined?) and the whole thing just crashed with the unhelpful stack trace.

In total agreement here that the trace could stand to be more helpful.  Will see if I can quickly reproduce this on Snack in a bit.

**Comment by corysimmons** [comment]
https://github.com/facebook/react-native/issues/13243#issuecomment-335488473 <-- js is weird

programmer: "does `x` exist?"
javascript: "???"
programmer: "...does `x` not... _not_ exist?"
javascript: "yeah it exists!"

**Comment by ArturGr** [comment]
I got the same error. For me it was a null instead of undefined. 
`this.props.price && <MyText text={'$' + this.props.price} />`

"price" comes from the API and in some cases it was "null" so  `'$' + null` produces this Error. 

Changed to:
`this.props.price !== undefined && this.props.price !== null &&  <MyText text={'$' + this.props.price.toString()} />`

**Comment by qymspace** [comment]
For me I was using immutablejs with forEach() 
`this.props.starred.keySeq().forEach(id=>{
  return null
})`

Changing that to the ussual .map() fixed the issue
`this.props.starred.keySeq().map(id=>{
  return null
})`

I agree the error is very ambiguous  spent an hour on this and just used trial and error

**Comment by RadoAz** [comment]
Guys, I've just solved this problem... The problem was ***ing jsx comment {/* Comment */ }... When I removed it, android began to work! God bless React Native developers)))

**Comment by deadcoder0904** [comment]
This was horrible. I used `<React.Fragment />` & it was giving me error & the version of React is `16.3.0-alpha.1`.

Replaced it with `<View />` & it works.

It was working for IOS & only Android had issue.

Example - 

# Not Working Solution

```js

// About.js
const About = () => <React.Fragment><Text>About</Text></React.Fragment>;

// Home.js
import About from './About'

const Home = () => <About />;

```

# Working Solution

```js

// About.js
const About = () => <View><Text>About</Text></View>;

```

**Comment by Benzer1406** [comment]
I put out all comments out of the `render` function.

**Comment by izikandrw** [comment]
To summarize, this issue is about what RN perceives to be malformatted JSX (usually occurring on Android render) and this thread has done a good job documenting the many forms this malformatted JSX can come in. Still doesn't solve the need for developers to comb through their code line by line looking for a random semicolons or spaces. **If there is a way to have the stack trace be more specific about the specific offending character or error that would probably save devs hours of sad debugging**

**Comment by Brucbbro** [comment]
This seriously needs to be addressed, as the current behaviour is a total mess. Whatever IDE one is using and the stacktrace are completely useless in this situation.
It feels like i'm proofreading an essay written in notepad or nano...

**Comment by compojoom** [comment]
crashlytics just reported the following crash
`Cannot add a child that doesn't have a YogaNode to a parent without a measure function! (Trying to add a 'RCTRawText [text: />]' to a 'RCTView')`

Thanks to the comments here I started looking in our code base for /> and after few minutes found the problem
```
<View>
<MyCustomButton 
/>
/>
</View>
```
Notice the second /> It's sitting there, not crashing on iOS, but causing the issue on Android.

**Comment by mezod** [comment]
Knowing all the potential errors is helpful when the error has just appeared after changing some code but... how to figure it out when the error appears on a device after having developed a full app on another device/simulator? The error gives absolutely no feedback on which line or file the issue occurs.  The stacktrace seems to be limited to java files that are not part of my project. Any ideas on how to debug this?

**Comment by johnckendall** [comment]
I made this comment in #18880 as well but posting it here in case it can help someone not waste hours:
Here is another fun one that happens only in **android** (even in RN 0.55.3):

`{this.props.loadingURL&&
         <View style={{flexDirection:‘row’,alignItems:‘center’,justifyContent:‘center’,marginTop:40,marginBottom:10,}}>
           <Text style={{marginRight:10,fontSize:20}}>{this.props.loadingURL}</Text>
           <ActivityIndicator size=“large” color=“black” />
         </View>
       }`

This blows up Android with the error reported in #18880  if loadingURL is an empty string.  It works fine if it's a non-empty string or a boolean or if I change it to this (basically convert it to a boolean):

`{!_.isEmpty(this.props.loadingURL)&&`

another 2 hours wasted!  👎

**Comment by fengqingyun2008** [comment]
I also encountered the same wonderful problem, rn0.49.5 my code is as follows:

Return (<FocusInstagram
                            Key={index}
                            Shop_name={this.props.shop_name}
                            Title={data.title}
                            Images={data.ext_property.images}
                        />)

And in FocusInstagram.js

 <Text style={{
                Position: "absolute",
                Top: formatPx(115),
                Left: formatPx(158),
                fontSize: formatPx(36),
                Width: formatPx(303),
                Color: "#4a96e2",
            }}
                  numberOfLines={1}
            >{"# " + this.props.title}</Text>

I solved this problem by changing the value of the passed property: 'title'->'title_name'

Return (<FocusInstagram
                            Key={index}
                            Shop_name={this.props.shop_name}
                            Title_name={data.title}
                            Images={data.ext_property.images}
                        />)

And in FocusInstagram.js
 <Text style={{
                Position: "absolute",
                Top: formatPx(115),
                Left: formatPx(158),
                fontSize: formatPx(36),
                Width: formatPx(303),
                Color: "#4a96e2",
            }}
                  numberOfLines={1}
            >{"# " + this.props.title_name}</Text>
However, so far, I still can not understand the real reason for this error.

**Comment by Manish3323** [comment]
@Joan Boixadós
make sure to provide View tag to wrap all stateless components in entire
project.

it solved my issue.

**Comment by mezod** [comment]
Thanks @Manish3323 , unfortunately I do not have stateless components :/

**Comment by Benzer1406** [comment]
I found a "}" that was somewhere random in my JSX but had no corresponding opening "{". It was not marked as syntax error. But after removing it the problem was solved.

**Comment by yaronlevi** [comment]
render with one line works.

two lines break

RN 0.49

VSCODE

**Comment by iivaschenko** [comment]
<img width="919" alt="screen shot 2018-05-04 at 5 30 11 pm" src="https://user-images.githubusercontent.com/35958922/39633791-aa7f4f7c-4fc1-11e8-809f-0e03d12bd82a.png">
My fix.

**Comment by moustafamahamed** [comment]
Cannot add a child that doesn't have a YogaNode to a parent without a measure function! (Trying to add a 'RCTRawText [text: return return]' to a 'RCTView') addChildAt     

      import React , {Component} from 'react';
      import {Text ,View ,StyleSheet, TextInput,Button, AppRegistry} from 'react-native';


      export default class App extends Component {
         

                  state={
                  places:[],
                  placename:""
                  }

              placeholderhandler = val =>{
                 this.setState({
                 placename:val
            });
                  };
              
                  placesubmithandler =()=>{
              
            if(this.state.placename.trim() === ""){ 
            return
                  
              }
         this.setState(prevState =>{
          return{
          places :prevState.places.concat(prevState.placename)
          };
          });
         };
              
                        render()  {   
                             
                            const placeoutput =  this.state.places.map(( place  ,i) =>( 
                                <Text key ={i}>{place}</Text>
                            ));
                            return (
                              <View style={ styles.viewstyle} >
              
                              <View style={styles.inputcontent}>
                                  <TextInput  style={styles.textinputstyle} placeholder="enter text"/>
                                  <Button title="add" style={styles.buttonstyle} onPress={this.placesubmithandler} />
                             </View>
                          return
                          return
                             <View>{placeoutput}</View>
                             </View>
                          )
                        }
                  }
                  
                        const styles = StyleSheet.create({
                        viewstyle: {
              
                        padding:16,
                        backgroundColor:"#fff",
                        alignItems:"center",
                        justifyContent:"flex-start"
                        }
                        ,
                        inputcontent:{
                        width:"100%",
                       flexDirection:"row",
                       justifyContent:"space-between"
                        },
                        textinputstyle:{
                        width:"70%"
                        }
                        ,
                        buttonstyle:{
                        width:"30%"
                        }
              
              
                        }
              
                        );
                  
              
                      // skip these lines if using Create React Native App
                      AppRegistry.registerComponent(
                        'AwesomeProject',
                        () => App);
              

help me please

**Comment by yaronlevi** [comment]
@iivaschenko 
I am developing with RN for over a year, and this is the first time I encountered this.
The amount of dev hours wasted over this is probably huge!

**Comment by marceviana** [comment]
In my case I could solve it replacing an empty string for an empty component:

used:
`const Media = ({ media }) => (media && <Thumbnail source={{ uri: media.src }} /></Left>) || <Text />;`

instead of:
`const Media = ({ media }) => (media && <Thumbnail source={{ uri: media.src }} /></Left>) || '';`

**Comment by JustinasKilas** [comment]
Had the same problem... My part of code that caused this error was something like this in render
```javascript
render(){  
  return({ this.state.loading === false ?(
    <View>
      <Text>Loaded</Text>
    </View> 
  ) : ""   })
}
```
It only crashed on android, ios worked fine. What i had to do was to change `""` to `null`

**Comment by gersonmontenegro** [comment]
this is a really weird case. I wasted two hours to find the problem, and then I found that @alainib got a similar solution: remove an space between tow blocks:
Before solution:
`<Icon name="open" /> <Text>Open details</Text>`
After solution
`<Icon name="open" /><Text>Open details</Text>`

The problem just go away. Only happend in Android.

**Comment by TheSavior** [comment]
Hi all! Sorry for the long wait but I think [the fix for this just landed](https://github.com/facebook/react-native/commit/66601e755fcad10698e61d20878d52194ad0e90c).

We were able to repro and fix this issue with this sample code:

```
function PlaygroundContent(props: {}) {
  return (
    <View>
      <Text>
        <View style={{width: 10, height: 10}}>
          <Image source={ANY_IMAGE_SOURCE} />
        </View>
      </Text>
    </View>
  );
}
```
