### ISSUE TITLE
Cannot get initial React Native App to Run

### ISSUE THREAD

**Issue by flaurida** [facebook/react-native#13249]
### Description

I can't get an initial React Native app to run, following a basic tutorial. The error seems to have to do with `UIUserInterfaceIdiomCarPlay`.

### Reproduction Steps and Sample Code

Following the tutorial [here](https://facebook.github.io/react-native/releases/0.23/docs/tutorial.html#content)

I created a new React Native project `react-native init AwesomeProject`
Then went into the directory, and ran `react-native run-ios`

Note I also tried from Xcode, and the myriad fixes online, but still no dice. This is the error I got:

```
/Users/lauracressman/Desktop/AwesomeProject/node_modules/react-native/React/Base/RCTPlatform.m:26:10: error: use of undeclared identifier 'UIUserInterfaceIdiomCarPlay'; did you mean 'UIUserInterfaceIdiomPad'?
    case UIUserInterfaceIdiomCarPlay:
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
         UIUserInterfaceIdiomPad
In module 'UIKit' imported from /Users/lauracressman/Desktop/AwesomeProject/node_modules/react-native/React/Base/RCTPlatform.m:12:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIDevice.h:33:5: note: 'UIUserInterfaceIdiomPad' declared here
    UIUserInterfaceIdiomPad NS_ENUM_AVAILABLE_IOS(3_2), // iPad style UI
    ^
/Users/lauracressman/Desktop/AwesomeProject/node_modules/react-native/React/Base/RCTPlatform.m:26:10: error: duplicate case value 'UIUserInterfaceIdiomPad'
    case UIUserInterfaceIdiomCarPlay:
         ^
/Users/lauracressman/Desktop/AwesomeProject/node_modules/react-native/React/Base/RCTPlatform.m:22:10: note: previous case defined here
    case UIUserInterfaceIdiomPad:
         ^
2 errors generated.
```

### Additional Information

* React Native version: 0.42.3
* Platform: iOS
* Development Operating System: MacOS

* Dev tools: Xcode, command line

**Comment by lazaridis-com** [comment]
@flaurida , don't know react, but the tutorial you refer too was written for version 0.23, and it looks it was not updated to the latest 0.42 version you're using.

Pick this one as a starting-point:

https://facebook.github.io/react-native/releases/0.42/docs/tutorial.html

-

If you have more problems, you better ask at...

http://stackoverflow.com/questions/tagged/react-native

...because the issue-tracker here is not for general support questions, but just for bugs.

Good luck.

**Comment by flaurida** [comment]
Thank you for the prompt reply! However, I am not even getting the basic app to run for the errors I highlighted. The tutorial you link to has the same setup instructions that I was using:
```
react-native init AwesomeProject
cd AwesomeProject
react-native run-ios
```

I am still getting the same error.

**Comment by lazaridis-com** [comment]
(note that I'm just a guest here, like you)

Ok, this looks pretty basic... so I guess you possibly hit on a bug. You have to await a response from some contributor who is on mac (you may want to post your version numbers, xcode version seems to play a role, e.g. using the latest one)

(as an off-topic sidenote: I'm just going through the basic tutorials of angular2 on win10... it's pure headache, too)

**Comment by flaurida** [comment]
I solved the issue by installing the new Mac OS and updating Xcode, thanks!
