### ISSUE TITLE
onScrollAnimationEnd not firering

### ISSUE THREAD

**Issue by dvine-multimedia** [facebook/react-native#1324]
I'n not sure if I'm missing something here, but I couldn't get onScrollAnimationEnd to fire. Neither with manual scrolling nor with scrollTo()

I'm using react-native 0.4.2 and a simulator with iOS SDK 8.3

Cheers
Georg

**Comment by christopherdro** [comment]
Yea I've been having the same issue working with ScrollView the last couple of days.

Trying using onMomentumScrollEnd for now, this should get it working until the issue is resolved.

**Comment by christopherdro** [comment]
#1410

**Comment by christopherdro** [comment]
#1410

**Comment by brentvatne** [comment]
@dvine-multimedia - silly me, I didn't search before opening my issue - thanks for the report! Given that I have more notes in the other issue, I'll close this instead
