### ISSUE TITLE
"unterminated string constant" when generating production bundle

### ISSUE THREAD

**Issue by udfalkso** [facebook/react-native#13245]
### Description

I've just upgraded from 0.39 to 0.42.3 and things seem to be working well, but I can't do a non-dev build.  

```
$ /usr/local/bin/node ./node_modules/.bin/react-native bundle --entry-file index.ios.js --bundle-output iOS/main.jsbundle --dev false --platform ios --verbose  --reset-cache
Scanning 730 folders for symlinks in /Users/udi/app/node_modules (7ms)
Scanning 730 folders for symlinks in /Users/udi/app/node_modules (7ms)
Loading dependency graph, done.
warning: the transform cache was reset.

Unterminated string constant
```

Changing ```--dev true``` works however.  

```
/usr/local/bin/node ./node_modules/.bin/react-native bundle --entry-file index.ios.js --bundle-output iOS/main.jsbundle --dev true --platform ios --reset-cache
Scanning 730 folders for symlinks in /Users/udi/app/node_modules (6ms)
Scanning 730 folders for symlinks in /Users/udi/app/node_modules (7ms)
Loading dependency graph, done.
warning: the transform cache was reset.
bundle: start
bundle: finish
bundle: Writing bundle output to: iOS/main.jsbundle
bundle: Done writing bundle output
Assets destination folder is not set, skipping...
```

### Reproduction Steps and Sample Code

Unfortunately this error is so vague that I'm not sure where to begin with reproducibility other than to upload my entire codebase, which unfortunately isn't possible.  

Does anyone have suggestions for how I could better debug this issue?  --verbose doesn't seem to do anything.  Thanks!

### Additional Information

* React Native version:     "react": "~15.4.0", "react-native": "^0.42.3",
* Platform: iOS
* Development Operating System: MacOS
* Dev tools: Xcode and command line

**Comment by filipemonteiroth** [comment]
@udfalkso Hey, maybe you had a problem with merges. Maybe you could try to copy your source folder and create a new react native project, then copy your folder inside the new project. Thats how I upgrade react-native versions.

**Comment by gyetvan-andras** [comment]
Do you use babel-plugin-transform-remove-console plugin? If so, it had some problem with RN. I have created an RN compatible one a few months ago at [https://github.com/gyetvan-andras/babel-plugin-transform-remove-console-rncompat](https://github.com/gyetvan-andras/babel-plugin-transform-remove-console-rncompat)

**Comment by udfalkso** [comment]
Thanks @gyetvan-andras but removing that transform doesn't help with the problem.  

@filipemonteiroth Thanks, I may have to resort to that, but it's not very simple as this is a complex application.  I used react-native-git-upgrade to do the merge and resolved all the conflicts.

The curious thing is why it works for dev and not for production...

**Comment by airman00** [comment]
@udfalkso any luck or updates with this?

I'm experiencing the same issue and lost with what to try next

**Comment by udfalkso** [comment]
Sorry @airman00 I had to resort to starting a clean project and moving my code into it and adding dependencies back in piece by piece.

**Comment by veris-amoghbanta** [comment]
any solutions on on this one?
