### ISSUE TITLE
Crash when swiping finger into screen from the edge

### ISSUE THREAD

**Issue by AlexanderFillbrunn** [facebook/react-native#13258]
### Description

When moving the finger from outside of the screen into the screen (left or right) in any of the Android React Native apps I tested, the app crashed on my Huawei P10. This might be the same as issue #13193, but that issue has been closed, probably due to insufficient description of the problem. Other non-react-native apps do not seem to have that problem.

### Reproduction Steps and Sample Code

The problem occurs in the [Material Design Demo App](https://github.com/react-native-material-design/demo-app), the example app of [react-native-drawer](https://github.com/root-two/react-native-drawer) and an app I am currently developing. To reproduce, just build one of the apps, open them on the device and swipe with a finger either from the left or right edge into the screen. The app will be terminated without error message.

Edit: I downloaded [NativeBase Kitchen Sink](https://play.google.com/store/apps/details?id=com.nativebasekitchensink) from the Play Store and this app has the same problem.

### Solution

Currently no idea how to fix this or whether this is a problem specific to the Huawei P10, the issue #13193 suggests that the problem also occurs on the P9.

### Additional Information

* React Native version: react-native-cli: 2.0.1, react-native: 0.37.0
* Platform: Android 7.0, Huawei P10
* Development Operating System: MacOS Sierra
* Dev tools: Android Studio 2.3

**Comment by r4ggj** [comment]
huawei mate9 has the same problem! how to resolve this problem?

**Comment by AndrewJack** [comment]
It has been fixed here https://github.com/facebook/react-native/commit/d2939eafbf56f99ea4da7374b9812ae6f54c1d3d

It will be released with the 0.44.0-rc

**Comment by AndrewJack** [comment]
@facebook-github-bot close

**Comment by tigerohuang** [comment]
"react-native": "0.44.0-rc.0"    has solved it, and I have tested it.

**Comment by r4ggj** [comment]
yeah ,i'v got it .It was resolved.very good!

**Comment by America-first-melon** [comment]
@r4ggj  big brother  教教我怎么升级呗  /抱拳
