### ISSUE TITLE
Image component reduces the quality of images

### ISSUE THREAD

**Issue by ahmedlhanafy** [facebook/react-native#13257]
### Description

I have an image component (in a `<ScrollView/>` to be able to zoom in the image) and there is a noticeable difference in quality between the photos app on IOS and the RN app when the photo is zoomed in.

Changing the `scale` in `source` prop or `resizeMode` prop doesn't change anything.
Here is the image in photos app
![screen shot 2017-04-02 at 7 29 54 pm](https://cloud.githubusercontent.com/assets/7052827/24589479/48f11e44-17db-11e7-8c57-c7701393cf19.png)
And this one is in RN
![screen shot 2017-04-02 at 7 29 48 pm](https://cloud.githubusercontent.com/assets/7052827/24589480/48f32194-17db-11e7-82d3-0f60f199d4c7.png)

### Reproduction Steps and Sample Code

Just an image component wrapped in <Scrollview/> for zooming capability 

### Additional Information

* React Native version: [0.41.2]
* Platform: [IOS]
* Development Operating System: [macOS]

**Comment by peterp** [comment]
How did you extract the image from the camera roll? My concern is that you're not using the exact same image.

**Comment by ahmedlhanafy** [comment]
I'm using [react-native-image-crop](https://github.com/ivpusic/react-native-image-crop-picker), and I print the `uri` I get to the console then I open it on my mac via `Preview.app`. 
That's how I compare both of the images @peterp

**Comment by timonsaval** [comment]
@peterp thanks for helping. Did you experience the same issue? Any other ideas?

**Comment by jamesone** [comment]
@ahmedlhanafy I think this is due to the image cropper resizing 👍 Not related to the Image component itself. 

I have confirmed this by upsizing the image crop size & the blur is gone.
