### ISSUE TITLE
[Dev Perf] CPU usage 95% caused by nano

### ISSUE THREAD

**Issue by mintuz** [facebook/react-native#1325]
Hello, found a bug in which if you close Xcode, turn off the simulator and shut down the packager, the CPU still sits round 95% and is caused by a nano process hanging around.

**Comment by onlymejosh** [comment]
I've been having the same issue. Took me a while to work out what was causing my brand new laptop to run like the old one!

**Comment by ide** [comment]
@mintuz do you mean nano as in the editor? not sure where this is coming from. The only mention of nano is unrelated.

```
ide:react-native·master$ grep -r nano .
./node_modules/module-deps/node_modules/JSONStream/test/fixtures/all_npm.json:{"id":"nano","key":"nano","value":{"rev":"105-50efc49a8f6424706af554872002c014"}},
./node_modules/module-deps/node_modules/JSONStream/test/fixtures/all_npm.json:{"id":"nanostate","key":"nanostate","value":{"rev":"9-1664d985e8cdbf16e150ba6ba4d79ae5"}},
```

**Comment by brentvatne** [comment]
Are you still having this issue @mintuz @onlymejosh? Is your shell $EDITOR or $REACT_EDITOR set to `nano` by any chance?

**Comment by mintuz** [comment]
I do have nano set to my Shell Editor. and it only spikes at 95% CPU when I use React Native on the simulator.

**Comment by browniefed** [comment]
@brentvatne if it only happens on a simulator is this still an issue worth keeping open?

**Comment by ide** [comment]
Will be addressed by https://github.com/facebook/react-native/pull/1957
