### ISSUE TITLE
Watchman error: Watcher took too long to load

### ISSUE THREAD

**Issue by charlesfranciscodev** [facebook/react-native#13265]
### Description

I get `Watchman error: Watcher took too long to load` when running `react-native start`

Error: Watchman error: Watcher took too long to load (WatchmanWatcher)
Try running `watchman version` from your terminal
https://facebook.github.io/watchman/docs/troubleshooting.html. Make sure watchman is running for this project. See https://facebook.github.io/watchman/docs/troubleshooting.html.
    at Promise.all.then.then.error (Project/node_modules/react-native/packager/react-packager/src/node-haste/crawlers/watchman.js:64:15)

### Reproduction Steps and Sample Code

`react-native start`

[Sample Code](https://jsfiddle.net/drh3cjLL/)

### Solution

For now I have to reinstall watchman to fix it.
I don't know how to fix it permanently.

[Installation Steps](https://facebook.github.io/watchman/docs/install.html#installing-from-source)

### Additional Information

* React Native version: 0.35.0
* Platform: Android
* Development Operating System: Ubuntu 16.04.2 LTS
* watchman version 4.7.0
* MAX_WAIT_TIME = 120000

**Comment by ericvicenti** [comment]
I think this can be solved by running `watchman watch-del-all`

**Comment by charlesfranciscodev** [comment]
I tried running `watchman watch-del-all` but I still get the same error `Watchman error: Watcher took too long to load`. Any ideas?
