### ISSUE TITLE
VirtualizedList has hard coded scrollEventThrottle value

### ISSUE THREAD

**Issue by iggyfisk** [facebook/react-native#13267]
### Description
We're doing animations based on `onScroll` in a `<FlatList>`, but the result is choppy in iOS. We tried setting `scrollEventThrottle={16}` on the `<FlatList>` component itself, then inside a `renderScrollComponent` function. No surprise it didn't work, since it gets [overridden in VirtualizedList](https://github.com/facebook/react-native/blob/22a4205bdd63d60c7d7290693aaccfe47e84ebb3/Libraries/Lists/VirtualizedList.js#L451).

Clearly there's some thought behind setting it to 50, and some concern about Android where the property has no effect, but is it critical? Our Flatlists work pretty well on Android as is, after all... and setting a lower throttle doesn't seem to have any catastrophic side effects on iOS.

### Solution

It all depends on what the original reason for hard coding the value to 50 was, but if it was just some happy performance middle ground, then allow it to be overridden by property on the component. @sahrens is a clever guy and will have a great answer I'm sure.

### Additional Information

* React Native version: Current master https://github.com/facebook/react-native/commit/22a4205bdd63d60c7d7290693aaccfe47e84ebb3
* Platform: iOS

**Comment by sahrens** [comment]
Just an oversight, we could easily allow a user override.

But you should really try to use Animated.event with useNativeDriver: true if possible, see the Spindicator component in FlatListExample for a demo.

**Comment by iggyfisk** [comment]
We're using Animated.event with useNativeDriver: true for our onScroll listener, but due to the size of our animation, scrollEventThrottle still makes a big difference. Which is expected, from what I understand https://github.com/facebook/react-native/blob/28ed5eddf2e54146e915ba4427d3960331231bc3/docs/Animations.md

The FlatListExample behaves the same way. Although it's very difficult to tell the difference between 50 and lower values because the Spindicator is so small, once you start going way above 50 it's noticeable. 

Just making sure we're not doing anything terribly wrong, looking forward to the option to override!

**Comment by ptomasroos** [comment]
Thanks a lot for the fix @sahrens https://github.com/facebook/react-native/commit/f186cfb9d657bacafa32588b96de6ddac0786cf8

**Comment by sahrens** [comment]
Oh it hadn't occurred to me that the throttle would affect useNativeDriver but it hooks into the same event dispatching bus so that makes sense. Diff is in master now in any case. Thanks for the report!

**Comment by andreleon** [comment]
I believe this is issue still applies to the `SectionList` component

**Comment by sahrens** [comment]
@andreleon: changing the throttle is not supported, you'll need to manage it in your own code, e.g. with a `Batchinator`

**Comment by andreleon** [comment]
@sahrens Okay, but how can I use the onScroll event for an animation like @iggyfisk? I just used the 500ms throttle as an example to illustrate the problem. Sorry if I wasn't clear. I am trying to bind the onScroll event with `Animated.event` but my animation is jaggy because of the throttle.

**Comment by sahrens** [comment]
Oh sorry, I'm confusing myself.

Not sure why it would be any different for `SectionList`. The fix should be in 0.45-stable for all `VirtualizedList`s.

**Comment by sahrens** [comment]
Note that Android doesn't support throttling at all.
