### ISSUE TITLE
Question: Is there any plan to provide a DatePickerAndroid UI component instead of the API to open a dialogue.

### ISSUE THREAD

**Issue by vincentsong** [facebook/react-native#13262]
### Description

I found there is a DatePickerAndroid API to open a date picker dialogue. Is there any plan to provide a UI component to show the date picker in the view, like the native date picker not the dialogue.

**Comment by filipemonteiroth** [comment]
@vincentsong I think that react-native will not build this component, since it only exposes native components as well. You can build your own, based on the API, it is not so hard to use.

**Comment by mmazzarolo** [comment]
Shameless plug: I created [this component](https://github.com/mmazzarolo/react-native-modal-datetime-picker) exactly for this.
