### ISSUE TITLE
Alternate debug connection than wifi on real device

### ISSUE THREAD

**Issue by pvinis** [facebook/react-native#13289]
### Description

I have specific cases I need to test often, where the network should not be available. Sometimes no wifi, sometimes no cellular, sometimes no Bluetooth. Currently, for the case of no wifi or airplane mode, I just bundle the js part, and try to debug by console.loging. This of course is not great or fast.

### Solution

So I thought we might be able to do the same debugging but using Bluetooth connection to the MacBook. I guess that would not be too challenging, but I would like some input for that idea. I mean that we could actually choose wifi or Bluetooth by commenting some line of code or something. so we can have the default way, and change it on demand. I'm sure Bluetooth would be useful for people sound rn dev on the go, for example.
One other way which I don't know if it's even possible is to debug with chrome but debug the bundled js. provided that we can bundle the js unminified.

What do you think? is there a way o go around that? is there a way to actually fix that? thanks. 

### Additional Information

* React Native version: 0.43.0
* Platform:  iOS
* Development Operating System: MacOS
* Dev tools: Xcode

**Comment by eurobob** [comment]
I would also love this feature. Often in my location I can be without wifi (either it goes down, or I have to hotspot). When i'm using my phone as a hotspot I want to be able to debug my application.

**Comment by eurobob** [comment]
Have come back round to wanting this functionality again and doing a small bit of digging. I think if we change this file:

```Libraries/Core/Devtools/setupDevtools.js```

to somehow use this package: https://www.npmjs.com/package/bluetooth-websocket-api

I think we could achieve this, although I'm not entirely sure what i'm doing :/

**Comment by ThaJay** [comment]
Is there not a was to use usb for debugging?
I would like to have the debugger working while the device has no wireless connection.

**Comment by pvinis** [comment]
so for now whenever I need to debug any network related functionality, I bundle, and compile with the js taken from the bundle. then I don't need the wifi for reloading etc. but then the whole point of react native is a bit lost, because I just drop down to old school printf debugging and waiting for recompilation.
having a way to connect to the packager via bt or usb or wifi would be awesome.

**Comment by ThaJay** [comment]
Should there be a post at [https://react-native.canny.io/feature-requests](https://react-native.canny.io/feature-requests)?

**Comment by jpshelley** [comment]
This would be a great feature, or even over LAN without an Internet connection. Why does the packager require access to the internet if all the node modules are cached locally?
