### ISSUE TITLE
upgrade to RN 0.37 - could not connect to development server (ios simulator)

### ISSUE THREAD

**Issue by jcbiznoff** [facebook/react-native#13283]
### Description

Using an embedded RN here in our apps. Did a clean npm run at the source directory, expect for RN screens to show up nicely but seeing a red screen. Everything worked fine up to v0.36, and after the upgrade screens are just not showing. Android emulator works fine so I'm very confused.

Also i can also see JS transformation happening from the command prompt logs. It's just on the simulator that it doesn't wait until this is completed and fetching JS files and reverts to the red screen and it completes. reload and connecting to debugger doesn't solve the issue as well.

![simulator screen shot apr 3 2017 5 59 58 pm](https://cloud.githubusercontent.com/assets/1912158/24634634/eec8a028-189c-11e7-89d6-7d917a24c31f.png)

I followed advices posting on other issues https://github.com/facebook/react-native/issues/304. 

I have transportsecurty on my plist set correctly, and tried other things. Any ideas?

### Additional Information

* React Native version: v0.37
* Platform: ios only (simulator haven't tried on device)
* Development Operating System: MacOS
* Dev tools: XCode 8.2

**Comment by jcbiznoff** [comment]
This happens on v0.38, 0.39, and 0.40 as well.

**Comment by crisys11** [comment]
Try creating a new app and verify if the same error occurs.

**Comment by jcbiznoff** [comment]
We were using a library that blocked the newly added MultipartDataTask handling in iOS. Removing this resolved.
