### ISSUE TITLE
Unhandled JS Exception: Native animated module is not available

### ISSUE THREAD

**Issue by sphairo** [facebook/react-native#13295]
![simulator screen shot 04 04 2017 10 33 52](https://cloud.githubusercontent.com/assets/4241383/24665223/584aaa02-1922-11e7-972a-57362d6bc1d0.png)

2017-04-04 10:33:14.945 [error][tid:com.facebook.react.JavaScript] Native animated module is not available
2017-04-04 10:33:14.947 [fatal][tid:com.facebook.react.RCTExceptionsManagerQueue] Unhandled JS Exception: Native animated module is not available

**Comment by sphairo** [comment]
@hramos Why is this problem closed? What is the solution ? 

I'm using JEST with react native my package.js contains this:

`{
  "name": "iMusica",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "axios": "^0.15.3",
    "react": "15.3.2",
    "react-localization": "0.0.7",
    "react-native": "0.35.0",
    "react-native-device-info": "^0.9.7",
    "react-native-lazyload": "^1.1.0",
    "react-native-linear-gradient": "^1.5.12",
    "react-native-orientation": "^1.17.0",
    "react-native-progress": "^3.2.0",
    "react-native-scrollable-tab-view": "^0.7.0",
    "react-native-swiper": "^1.5.4",
    "react-native-value-store": "^0.1.0",
    "react-redux": "^5.0.2",
    "redux": "^3.6.0",
    "redux-logger": "^2.7.4",
    "redux-thunk": "^2.1.0"
  },
  "devDependencies": {
    "babel-jest": "^19.0.0",
    "jest": "^19.0.2",
    "regenerator-runtime": "^0.10.3"
  }
}`

after execute `npm install` and before run my react project i have this problem :/

**Comment by hramos** [comment]
Please read the new issue template.
