### ISSUE TITLE
Issues with react-packager running on Windows

### ISSUE THREAD

**Issue by joewood** [facebook/react-native#133]
I'm trying to run the **react-packager** on Windows, to provide the bundle running on an iOS device.   I'm hitting some issues with the output of the packager when running on Windows vs. OSX.  The **Movies** app on the device complains that the dependencies are not resolved and fails to load.

I ran the packager on both platforms and compared the output via **curl** to do a diff.  It's not that easy to compare this, as the packager doesn't seem to respect the same order on each platform. Inspecting the files a bit more closely I can spot a problem with path names and escaping out the path separator.

For example, the require statements are not escaped out:

```javascript
'use strict';

var React = require('react-native\react-native');
```

But the dependency parameter array *does* escape out the path separator, see `react-native\\react-native` below:
```javascript

module.exports = MovieCell;
});
__d('react-native\Examples\Movies\getStyleFromScore',["react-native\\react-native"],function(global, require, requireDynamic, requireLazy, module, exports) {  /**
 * Copyright 2004-present Facebook. All Rights Reserved.
 * @flow
 */
'use strict';
```
 
I'm not sure if this is *the* problem, but it looks like it's tripping up the dependency resolver.

**Comment by brentvatne** [comment]
@joewood - feel free to re-open if this is still a problem, it looks like you've figured it out in #278
