### ISSUE TITLE
关于react-native 0.43.0-rc.4 Bug

### ISSUE THREAD

**Issue by tmxdyf** [facebook/react-native#13308]
当在Android 本地代码中发送Json至JS代码时，发生JSON格式错乱问题。

### Description

``` JAVA
WritableNativeMap map = new WritableNativeMap();
map.putString("json",json);//此处json正常
sendEventToJavaScript(getReactApplicationContext(), SEND_NAME_TO_JS_NEW_GROUP, map);
```
如图：

![31491359677_ pic](https://cloud.githubusercontent.com/assets/6415080/24687425/2a80b5a6-19ec-11e7-84f4-21993aa1354c.jpg)

```JS
  DeviceEventEmitter.addListener('new_group', params => {
            console.log("groups.result:" + params.json);//此处json 格式错误
  });
```
如图：

![Uploading 21491359648_.pic.jpg…]()

**Comment by grabbou** [comment]
I am going to close this issue for now. If you believe this is a bug, please re-open and update the description in English with working screenshots.
