### ISSUE TITLE
Image cache causes high disk usage

### ISSUE THREAD

**Issue by parkerdan** [facebook/react-native#13307]
RN v 42.  The app I have an issue with uses a lot of remote images.

All other production RN apps I have released have no issues, but also use almost no remote images which leads me to believe this is a remote image issue with the Image component.

Download the release build of the app in question via TestFlight and the app size is `26mb` in Settings => General => Storage & iCloud Usage => Manage Storage.

After launching the app and running it for awhile (30 minutes or so), the `Documents & Data` jumps to 100+mb and the total app size is 126mb +.

Why does this jump so high and never go back down?  I am not saving things, just cycling url on Image components.

**Comment by ericvicenti** [comment]
Maybe we should adjust the cache policy on images

**Comment by parkerdan** [comment]
I've tried using just RN's Image Component, I've tried this `https://github.com/wcandillon/react-native-img-cache` as the main Image component, but disk usage still seems excessive.

Is there anyway to wipe the disk usage?

**Comment by ericvicenti** [comment]
The only way I know to wipe disk usage is to remove and re-install the app.

Is the disk usage growing at the same rate as your cached images? IE, if you cache 10 images that are 5MB each, is the disk usage growth ~50MB?

**Comment by parkerdan** [comment]
I'll have to dig a little deeper to check the disk usage per image.

The current native iOS app I am re-creating has a total disk usage of ~95mb after heavy app usage.

The RN re-creation is about ~150mb after heavy use....but I guess that's the way it is.  I might be pulling in higher quality images than the previous, native app, but I am not sure.  I do know we are pulling in more images and bundling less with the app, but not enough more to account for the ~50mb diff.  

It seems the boss' are ok with this because they get an Android version of their app now too.

**Comment by parkerdan** [comment]
@ericvicenti It seems to grow at a reasonable rate.  I will close this.

This app is difficult to use on an iPhone 5.  1GB RAM has a hard time with this app.  The other 2-3GB RAM iPhones have no issues....  I think it might be connected to all the images
