### ISSUE TITLE
Yarn warning with react-addons-shallow-compare on RN 0.43.0 (released)

### ISSUE THREAD

**Issue by fungilation** [facebook/react-native#13310]
This warning shows up on any yarn upgrade or install. This didn't show up before RN 0.43.

```
warning "react-addons-shallow-compare@15.5.0-alpha.0" has incorrect peer dependency "react@^15.5.0".
```

**Comment by nhducit** [comment]
@fungilation https://github.com/facebook/react-native/issues/13309#issuecomment-291757857

**Comment by janicduplessis** [comment]
You can ignore the warning it won't cause any issue. It will be fixed soon.

**Comment by Swizec** [comment]
It or something related to it causes issues.

--> https://github.com/facebook/react-native/issues/13311

**Comment by grabbou** [comment]
0.43.1 is being now released with a fix

**Comment by npomfret** [comment]
Can't get 43.1 to work.  Still getting an error saying unable to resolve module...  react-addons-shallow-compare
