### ISSUE TITLE
RN 0.43 bug

### ISSUE THREAD

**Issue by OlegKovalSmartexe** [facebook/react-native#13313]
Yesterday i update RN in my project to 0.43 (from 0.40)

And today i get report in crashanalistics about crash with message:

"Fatal Exception: com.facebook.react.common.JavascriptException: undefined is not an object (evaluating 'u[n]'), stack:
getListener@95:1029"

No crash before..

Any ideas how to fix it?

**Comment by enieber** [comment]
when this occurred? in the start the app or when you running a specific page?

**Comment by chrisrbs** [comment]
I am also seeing this. I get it occasionally after touching a TouchableWithoutFeedback or TouchableOpacity on android. RN 0.43.2

**Comment by kodemi** [comment]
I'm not shure, but maybe you try to render numeric value like this: `<Text>{n}</Text>` (where `n` is a number variable). 
I had code like this and it works before upgrade to 0.43. I changed code to `<Text>{String(n)}</Text>`.

**Comment by quietUncle** [comment]
@kodemi  thx!

**Comment by windhost** [comment]
maybe the same  problem 
 #13080

**Comment by nik** [comment]
Tape #13, React Native this is for you..

**Comment by wv1124** [comment]
05-24 13:29:30.543 2412-2604/com.qianmi.bolt E/ReactNativeJS: undefined is not an object (evaluating 'u[n]')
05-24 13:29:30.555 2412-2605/com.qianmi.bolt E/CustomCrashHandler: com.facebook.react.common.JavascriptException: undefined is not an object (evaluating 'u[n]'), stack:
                                                                   getListener@117:1034
                                                                   n@125:112
                                                                   i@125:164
                                                                   s@126:587
                                                                   c@125:348
                                                                   i@122:95
                                                                   p@125:808
                                                                   n@137:385
                                                                   extractEvents@137:2967
                                                                   extractEvents@117:1302
                                                                   handleTopLevel@131:159
                                                                   <unknown>@130:576
                                                                   a@133:277
                                                                   c@133:60
                                                                   perform@151:596
                                                                   batchedUpdates@144:464
                                                                   i@145:358
                                                                   i@133:90
                                                                   u@133:150
                                                                   _receiveRootNodeIDEvent@130:548
                                                                   receiveTouches@130:922
                                                                   value@43:2897
                                                                   <unknown>@43:1013
                                                                   <unknown>@43:106
                                                                   value@43:985
                                                                   
                                                                       at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:99)
                                                                       at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:83)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:511)
                                                                       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:345)
                                                                       at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:141)
                                                                       at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                       at android.os.Handler.handleCallback(Handler.java:615)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                       at android.os.Looper.loop(Looper.java:137)
                                                                       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                                       at java.lang.Thread.run(Thread.java:856)
                                                                   
                                                                   
                                                                   [ 05-24 13:29:30.611  2412: 2615 D/         ]
                                                                   HostConnection::get() New Host Connection established 0xb95dcd88, tid 2615
05-24 13:29:30.647 2412-2604/com.qianmi.bolt E/ReactNativeJS: undefined is not an object (evaluating 'u[n]')

**Comment by johndanek** [comment]
I'm getting `undefined is not a function (evaluating '(0,l.combineReducers)({github:r(862).reducer,login:r(863).reducer,search:r(917).reducer})')`

At a complete loss for what to do to get past this.

This only occurs when building a release APK for Android. Running a dev build works fine.

**Comment by dinzo** [comment]
@johndanek have you tried RN 0.44.3?

**Comment by johndanek** [comment]
@dinzo I believe this is an Ignite issue. I started a fresh project just using React Native (no Ignite), re-implemented my code, and don't see the problem anymore.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
