### ISSUE TITLE
React Native 0.43 completely broken

### ISSUE THREAD

**Issue by Swizec** [facebook/react-native#13311]
### Description

I ran `react-native init MyAwesomeApp`. It finishes with npm warnings about peer dependencies and the default app doesn't even run.

![screen shot 2017-04-05 at 00 20 13](https://cloud.githubusercontent.com/assets/56883/24694291/343370bc-1996-11e7-8008-1f4e411d0297.png)
![screen shot 2017-04-05 at 00 21 41](https://cloud.githubusercontent.com/assets/56883/24694292/36272a3a-1996-11e7-9fdf-603e170b9dee.png)

### Reproduction Steps and Sample Code

react-native init MyAwesomeApp
cd MyAwesomeApp
react-native run-ios

Observe that it doesn't work.

### Solution

I assume the issue stems from this:

![screen shot 2017-04-05 at 00 18 48](https://cloud.githubusercontent.com/assets/56883/24694310/42dc332e-1996-11e7-81fd-bf886ea778bf.png)

And potentially other things related to that. I don't understand enough about how react-native works to know what's wrong.

### Additional Information

* React Native version: 0.43.0
* Platform: iOS
* Development Operating System: MacOS Sierra
* Dev tools: CLI

**Comment by janicduplessis** [comment]
Thanks for reporting this, the peer dep isn't actually the issue. Might be related to some yoga commits that were cherry picked recently. cc @grabbou

**Comment by grabbou** [comment]
Have you tried restarting `packager` after upgrading React Native? Before pushing, I've checked `run-ios` on `UIExplorer` (bundled example of React Native) and everything worked.

@janicduplessis I was planning to cherry-pick Yoga commit but eventually didn't, as the commit was to `Yoga` separate repo.

**Comment by Swizec** [comment]
I wasn't updating React Native, I was starting a new project.

*But* it does look like I had a packager from a different project running in a hidden terminal window. After killing that and restarting, everything seems to work.

Thanks for the help ... but why can different projects impact each other like this?

**Comment by grabbou** [comment]
@Swizec packager was serving you a bundle for a different React Native version which resulted in a mismatch when JS -> Native calls happen (as per error message).

**Comment by janicduplessis** [comment]
Yea every RN packager runs on the same port so it didn't start a new packager for your new project and just used the one that was running already.
