### ISSUE TITLE
change 8081 port not use

### ISSUE THREAD

**Issue by hxmpro** [facebook/react-native#13324]
My 8081 port listen by mcafee,so i use "react-native start --port 8082" to change my port.
It can start,but when i "run-ios", it fail.
How to do it right?

**Comment by Lizhooh** [comment]
`Dev Setting -> Debug server host & port for device -> 192.168.1.1:8082`

**Comment by hxmpro** [comment]
@Lizhooh iOS Simulator have no "Dev Settings".

**Comment by hxmpro** [comment]
I find a way to kill McAfee progress.
`cd /Library/LaunchDaemons`
`sudo launchctl unload com.mcafee.agent.macmn.plist`
