### ISSUE TITLE
React native doesn't build Android release. Hangs at bundleReleaseJsAndAssets

### ISSUE THREAD

**Issue by wilomgfx** [facebook/react-native#13329]
### Description

Upgraded to 0.43.1 and tried running ./gradlew assembleRelease
to generate my Android build apk

It just hangs at usually 91..95% for ever.

![image of hang](https://d3uepj124s5rcx.cloudfront.net/items/3l421G1J0w0I0u3X312l/Image%202017-04-05%20at%2015.15.37.png?v=9227fec4)

### Reproduction Steps and Sample Code

Do the required signing for the apk and the various tasks in the gradle files
explained here : https://facebook.github.io/react-native/docs/signed-apk-android.html

Go to Android folder and run ./gradlew assembleRelease

for reference, i added some helper scripts in my package.json

```json
//top of package.json
//...
"droid:assr": "cd android && ./gradlew assembleRelease && cd ..",
"droid:rel": "react-native run-android --variant=release",
//...
//rest of package.json
```

Neither **react-native run-android --variant=release** or  **./gradlew assembleRelease** works.

### Solution

Building from android-studio with gradle works, but it skips bundleReleaseJsAndAssets
so it makes the app crash instantly.

### Additional Information

* React Native version: 0.43.1
* Platform: Android (Haven't tried buiding the release build on iOS yet)
* Development Operating System: MacOS
* Dev tools: Mainly coding in vscode, used android-studio(2.3.1) to try to workout around the problem (no success)

**Comment by HyperSimon** [comment]
I got an exception Instead
![2017-04-06 4 42 57](https://cloud.githubusercontent.com/assets/9377192/24745455/62531da0-1ae8-11e7-8231-3ff6cffb594b.png)

**Comment by wilomgfx** [comment]
I seemed to have fixed the problem by excluding my typescript src folder from the build process inside : `android/app/build.gradle` by adding it to this array:  `project.ext.react`

Kinda strange that it just hangs theres and says nothing... Will further investigate, but it seems to be a solution.

**Comment by Kabangi** [comment]
Experiencing the same error.

**Comment by Hindenes** [comment]
Had the same issue, but I managed to fix it. 

For me, the problem was that I use Realm in my tests, and I didn't remove the generated realm files after a test run. Removing all Realm files fixed it (`rm -rf default.realm* && rm -rf realm-*`).

**Comment by Kabangi** [comment]
@Hindenes Thanks. I suspect the source of the issue could be that because it appeared after setting up jest and running `npm t`. I do have realm and removed all the generated files but the issue still persists.

**Comment by kulor** [comment]
I've just found a workaround to my particular problem; removing the `realm-object-server` directory unblocks the `bundleReleaseJsAndAssets` step

**Comment by tomas-paronai** [comment]
Removed realm generated folders. 
Cleaned project. 
This problem still persists: It hangs `bundleReleaseJsAndAssets`

**Comment by softnodelabs** [comment]
I'm having this problem! Just created a new project with react-native-cli but I cannot build a working Release variant apk. Tried windows and mac. Same issue on both. My client is pressing me to upload the app to Google Play and I don't know what to do!

**Comment by asukiaaa** [comment]
In my case, I could pass `bundleReleaseJsAndAssets` with executing `npm install` instead of `yarn install` to create `node_modules`.
However, I'm not sure the reason why.

My environment
- OS: Ubuntu 17.10
- node: 9.2.0
- npm: 5.5.1
- yarn: 1.3.2
- react-native-cli: 2.0.1
- react-native: 0.48.4

**Comment by rajesh-frontendengineer** [comment]
Please install CMD plugin in android studio. To Resolve:  Hangs at bundleReleaseJsAndAssets

[](https://plugins.jetbrains.com/plugin/5834-cmd-support)
