### ISSUE TITLE
[Navigator] view broken after 0.4.3 (re-opened)

### ISSUE THREAD

**Issue by lwansbrough** [facebook/react-native#1332]
After 0.4.3, my `Navigator` view ceases to function correctly. Pushing new routes to the Navigator animates (very laggy) to a blank white screen (within the Navigator). I am then unable to pop the route.

The cause seems to be the `sceneStyle` prop - when this prop is present, these issues occur. Otherwise it works fine.

CC: @ericvicenti

**Comment by ericvicenti** [comment]
Interesting.. Can you post a simplified gist that demonstrates this bug, or modify the `NavigatorExample` to demo the problem?

**Comment by lwansbrough** [comment]
Well, based on what I've seen in my own app, this should do it: https://gist.github.com/lwansbrough/03a459e59fdc5cf39091

The only thing that's changed is I added `sceneStyle={{}}`.

Just checking myself now..

**Comment by lwansbrough** [comment]
Yes it's reproducible.

**Comment by ericvicenti** [comment]
Ok, thanks. I'll investigate this

**Comment by soliury** [comment]
yes, I also meet this bug.

**Comment by lwansbrough** [comment]
Great thanks @ericvicenti

**Comment by lwansbrough** [comment]
This has regressed @ericvicenti

**Comment by ericvicenti** [comment]
@ide, do you think this is related to #2104 ?

**Comment by lwansbrough** [comment]
You know what guys? I think I may be mistaken. I think I was running `0.4.4` instead of `0.8.0` due to a mistake I made in Git.

**Comment by ide** [comment]
@ericvicenti Navigator has been working well for me for the past few weeks and my diff hasn't been synced to master (FWIW I'm using it w/my patched copy of RN and it's working well too), so at a glance I don't think it's causing this issue.

**Comment by ericvicenti** [comment]
:+1:

**Comment by MuruganDurai** [comment]
Hi @ericvicenti, Could you please advise me how to proceed with this kind of navigation. Working on an android app with 'Navigator' component which contains a home screen with custom header (using <view>) with right buttons for search and in the home content area there is scrollable-tab-view with 4 different tabs. Files look like --> 

app.js, home.js, header.js, search.js, storetab.js, brandtab.js, parkingtab.js, map.js

Now what is working with navigator is : App.js (launcher with Nav)--> Home (initialroute)-->Header ---> Search 
and what is not working is : 
App.js --> Home (initialroute) --> StoreTab --> Map. ----> error  : "got undefined - check render navigator"
I followed this example https://github.com/h87kg/NavigatorDemo. Do I need to use 2 Navigators for this purpose? Please advice.

**Comment by ericvicenti** [comment]
@MuruganDurai, sorry to hear about the troubles! It is difficult to understand what problem you're having without seeing the full error and the code that leads up to it. Could you put an example of the broken behavior on rnplay.org, and explain what happens compared to what you expect?

**Comment by MuruganDurai** [comment]
@ericvicenti I cannot share the code with rnplay as I have used third party modules. Can I gist the code and sketch or video of app behaviour now.
