### ISSUE TITLE
View backgroundColor is removed if the content is to long with borderRadius

### ISSUE THREAD

**Issue by mlabrum** [facebook/react-native#13332]
### Description

It seems if a `View` with `backgroundColor` + `borderRadius` contains a large amount of text, it will stop rendering the `backgroundColor` of the `View`

### Reproduction Steps and Sample Code
https://snack.expo.io/SJ6UPQmal

As you can see the top box renders correctly with a small amount of items, but the bottom box with 400 items doesn't display a background color
![screenshot_20170406-120053](https://cloud.githubusercontent.com/assets/296106/24735322/854e4338-1ac1-11e7-87e9-d57c873f81d5.png)

Removing the border radius then displays the background again
![screenshot_20170406-120151](https://cloud.githubusercontent.com/assets/296106/24735294/65ebeb12-1ac1-11e7-8b79-e49f3af9d733.png)

### Solution
Ideally it would be nice to be able to use `backgroundColor` with `borderRadius` for large content

### Additional Information

* React Native version: 0.42 + 0.43.1 (tried it on the latest)
* Platform: Android 5, 6, 7, we can't replicate this on IOS
* Development Operating System: Windows + Mac OS
* Dev tools: WebStorm

**Comment by idajimenez** [comment]
@mlabrum did you found a solution for this? This also happens in the app that I am working on.

**Comment by mlabrum** [comment]
@idajimenez I worked around this by having another view with border radius above and below the content, hacky but it works....

https://snack.expo.io/rkmLBFO7b

**Comment by ngraef** [comment]
I'm seeing the same issue with very wide views: https://snack.expo.io/S1cuMed8Z. In addition to backgroundColor vanishing, the view's border isn't rendered.

Like @mlabrum, my workaround is to add small views with border radius before and after the main view. Ideally though, I'd like to not render 3x the necessary views.

**Comment by ngraef** [comment]
This is still an issue. Tested in `0.50.0-rc.0`.

**Comment by ngraef** [comment]
Tested in `0.55.3`. Still an issue.
