### ISSUE TITLE
HUAWEI mate9 android7 from the left or right edge of the screen slide app flash back

### ISSUE THREAD

**Issue by fuxianwei** [facebook/react-native#13334]
### Description

HUAWEI mate9 android7 from the left or right edge of the screen slide app flash back

react native 0.43.1
mate9 android 7.0

### Additional Information
--------- beginning of crash
04-04 11:43:09.014 25976 25976 E AndroidRuntime: FATAL EXCEPTION: main
04-04 11:43:09.014 25976 25976 E AndroidRuntime: Process: com.jph.githubpopular, PID: 25976
04-04 11:43:09.014 25976 25976 E AndroidRuntime: java.lang.RuntimeException: Tried to get non-existent cookie
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at com.facebook.react.uimanager.events.TouchEventCoalescingKeyHelper.getCoalescingKey(TouchEventCoalescingKeyHelper.java:75)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at com.facebook.react.uimanager.events.TouchEvent.init(TouchEvent.java:89)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at com.facebook.react.uimanager.events.TouchEvent.obtain(TouchEvent.java:45)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at com.facebook.react.uimanager.JSTouchDispatcher.handleTouchEvent(JSTouchDispatcher.java:114)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at com.facebook.react.ReactRootView.dispatchJSTouchEvent(ReactRootView.java:155)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at com.facebook.react.ReactRootView.onInterceptTouchEvent(ReactRootView.java:127)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2212)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:447)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1871)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at android.app.Activity.dispatchTouchEvent(Activity.java:3213)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:409)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at android.view.View.dispatchPointerEvent(View.java:10231)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4851)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4711)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4244)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4297)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4263)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4390)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4271)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4447)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4244)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4297)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4263)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4271)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4244)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6671)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6645)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6606)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6798)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:181)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6745)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6826)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:923)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:735)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:661)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:909)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:761)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:156)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6524)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
04-04 11:43:09.014 25976 25976 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

**Comment by nihgwu** [comment]
It has been fixed in RN0.44RC0, please search the **Issues** before create one

**Comment by AndrewJack** [comment]
@facebook-github-bot close
