### ISSUE TITLE
unknown error

### ISSUE THREAD

**Issue by privateOmega** [facebook/react-native#13337]
### Description

I tried to run the react-native app using `react-native run-android`.
It displays `Cannot read property '1' of null`
### Reproduction Steps and Sample Code

I am not sure.
https://gist.github.com/privateOmega/7516fbe550b4d651a5be2fe759aa60fb

### Additional Information

* React Native version: 0.42.0
* Platform: Android
* Development Operating System: Ubuntu 16.10 and Ubuntu 16.04

**Comment by hramos** [comment]
This is not the best place to get help debugging a particular app, I'm afraid.
