### ISSUE TITLE
How do I import NativeMethodsMixin?

### ISSUE THREAD

**Issue by evollu** [facebook/react-native#13330]
I did `import {NativeMethodsMixin} from 'react-native'` but it is undefined.
here is exponent example. You will get redbox.
https://snack.expo.io/HJq_dCGTl

**Comment by hramos** [comment]
There's a couple of examples if you grep for `NativeMethodsMixin` in the code base. Both of these should work:
```
import NativeMethodsMixin from 'NativeMethodsMixin';
var NativeMethodsMixin = require('NativeMethodsMixin');
```

**Comment by evollu** [comment]
I think this kind of import only work inside react native project (powered by haste?)
For the application everything should come from react-native module.

**Comment by johnwatsondev** [comment]
@evollu Yes. We cannot use it. :(

**Comment by evollu** [comment]
@hramos is it something react native can expose? Can you reopen this issue?

**Comment by johnwatsondev** [comment]
@evollu I have a tricky approach. We just use several methods of the object of NativeMethodsMixin.

```
const NativeMethodsMixin = {
  measure: function(callback) {
    UIManager.measure(findNumericNodeHandle(this), mountSafeCallback(this, callback));
  },
  measureInWindow: function(callback) {
    UIManager.measureInWindow(findNumericNodeHandle(this), mountSafeCallback(this, callback));
  },
  measureLayout: function(relativeToNativeNode, onSuccess, onFail) {
    UIManager.measureLayout(findNumericNodeHandle(this), relativeToNativeNode, mountSafeCallback(this, onFail), mountSafeCallback(this, onSuccess));
  },
  setNativeProps: function(nativeProps) {
    injectedSetNativeProps(this, nativeProps);
  },
  focus: function() {
    TextInputState.focusTextInput(findNumericNodeHandle(this));
  },
  blur: function() {
    TextInputState.blurTextInput(findNumericNodeHandle(this));
  }
};
```

I copy the dependency of NativeMethodsMixin to a single file.

![nativemethodsmixin](https://user-images.githubusercontent.com/12760754/29757215-ad5bc378-8bdc-11e7-854f-e0bea85a77d1.jpg)

So, I can use it anywhere.
