### ISSUE TITLE
[Android] Attempted to assign to readonly property

### ISSUE THREAD

**Issue by skv-headless** [facebook/react-native#13343]
### Description

fails on start

<img width="300" src="https://cloud.githubusercontent.com/assets/1488195/24759243/eeb7a7e0-1af5-11e7-93a2-8e8f3655d221.png"/>

### Reproduction Steps and Sample Code

in UIExplorer in settings disable JS Dev Mode

### Solution

remove DEV check here https://github.com/facebook/react-native/blob/c7387fefc85fd15dceadfa291857099ed3e848b8/Libraries/react-native/react-native-implementation.js#L145 since it is working in development mode

### Additional Information

* React Native version: [master 5f37483466b32bb9d09945e25c04b1cb8add9679]
* Platform: [Android]
* Development Operating System: [MacOS]

**Comment by skv-headless** [comment]
It fails on `takeSnapshot` method so I think here is the problem https://github.com/facebook/react-native/commit/848593c0f0b75da9ff342596908c5091a2cd1430 @bvaughn

**Comment by bvaughn** [comment]
Hm, I think the problem is because `takeSnapshot` got added to `react-native-implementation` in c7387fe but it's also (still) present on the renderer(s). I'll submit a PR to remove it from the renderers ASAP.

**Comment by ptomasroos** [comment]
Big thanks @bvaughn !

**Comment by bvaughn** [comment]
No problem! Thanks to @skv-headless for calling my attention to this 😁  The actual fix was easy.

**Comment by skv-headless** [comment]
Just checked on master. It works. Thank you 👍
