### ISSUE TITLE
How to get the components that has been required by the current component?

### ISSUE THREAD

**Issue by matthewga0** [facebook/react-native#1335]
I create a component as below, it requires `Text`, is there a way to get the components that has been required by the current component?
```js
var React = require('react-native');
var { Text } = React;

module.exports = React.createClass({
  render: function() {
    return (
       <Text></Text>
    );
  }
);
```

**Comment by ide** [comment]
There's no officially supported way to do this at runtime. Best way is to write your own script with esprima or estree that figures this out. I'm not aware of scripts that do this for destructuring assignment but https://www.npmjs.com/package/find-requires could be a good project to fork.

**Comment by matthewga0** [comment]
Thanks @ide.
