### ISSUE TITLE
ScrollView Inconsistency Between Platform's

### ISSUE THREAD

**Issue by flaviotobi** [facebook/react-native#13350]
Hi, i have a ScrollVIew with a TextInput , and when i click the TextInput the keyboard shows, the TextInput changes position to avoid to be under the keyboard.
It would be ok if the iOS have the same reaction, but it doesn't have.

I don't understand why this happen, especially when we have KeyboardAvoidingView component.

### Reproduction Steps and Sample Code
Just create a ScrollView with a TextInput with enough margin to be under the keyboard.

### Additional Information
* React Native version: 0.41.2
* Platform: Android
* Development Operating System: MacOS

**Comment by ericvicenti** [comment]
Hi, on iOS the app goes behind the keyboard, and usually on Android the app resizes when the keyboard opens. So this isn't a difference with the RN scroll view as much as it is a difference between iOS and Android

**Comment by flaviotobi** [comment]
@ericvicenti thanks for the answer, do you know any way to disable this on android ?

**Comment by christophermark** [comment]
@flaviotobi try changing the value of `android:windowSoftInputMode` in your AndroidManifest.xml file. 

https://developer.android.com/guide/topics/manifest/activity-element.html#wsoft
