### ISSUE TITLE
Crash on TextInput focus - com.facebook.react.views.textinput.ReactEditText.requestFocus(ReactEditText.java:192)

### ISSUE THREAD

**Issue by dylanpinn** [facebook/react-native#13361]
### Description

We have been getting crash reports when users have been selecting a TextInput. It doesn't happen all the time only occasionally.

### Reproduction Steps and Sample Code

I have been unable to reproduce with a small sample app. 

The component where it seems to be happening the most is here. Which is 

```javascript
    <TextInput
      autoCapitalize="none"
      autoCorrect={false}
      onChangeText={(text) => {
        searchFunc(text);
      }}
      placeholder="Search..."
      underlineColorAndroid="transparent"
      style={styles.searchTextInput}
    />
```

Here is a pastebin of one of the crash logs. https://pastebin.com/ZKacW4Gb I can provide more on request.

### Solution

Unsure, my Java skills are rusty. :( 

### Additional Information

* React Native version: 0.42.3
* Platform: Android
* Development Operating System: Linux/MacOS
* Dev tools: Android Studio 2.3.1

**Comment by hramos** [comment]
Hey thanks for reporting this! Unfortunately without a repro it is unlikely we will be able to take a look at this.
