### ISSUE TITLE
[UIExplorer] xcode error

### ISSUE THREAD

**Issue by NecoleYu** [facebook/react-native#1336]
Xcode generates the below error when running example 
```
clang: error: no such file or directory: '/Users/Necole/Library/Developer/Xcode/DerivedData/UIExplorer-gbtvpafqwwvhzvaiuorqbimjgjzx/Build/Products/Debug-iphonesimulator/libReact.a'


clang: error: no such file or directory: '/Users/Necole/Library/Developer/Xcode/DerivedData/UIExplorer-gbtvpafqwwvhzvaiuorqbimjgjzx/Build/Products/Debug-iphonesimulator/libRCTImage.a'


clang: error: no such file or directory: '/Users/Necole/Library/Developer/Xcode/DerivedData/UIExplorer-gbtvpafqwwvhzvaiuorqbimjgjzx/Build/Products/Debug-iphonesimulator/libRCTText.a'


```

**Comment by jaygarcia** [comment]
are those libraries listed in your sub-project dependencies?

**Comment by brentvatne** [comment]
Closing as there has been no response and doesn't seem to happen to others. @NecoleYu if you're still having the issue then ping me with some more details and we can reopen :smile:

**Comment by geraldlrh** [comment]
@NecoleYu @brentvatne I have meet the same issue when I open multiple example project in Xcode. But when I terminal Xcode and reopen only this one project, it works:)
