### ISSUE TITLE
fetch failing with "Network Request Failed" error from insecure HTTPS request

### ISSUE THREAD

**Issue by JCDJulian** [facebook/react-native#13363]
I'm running into a "Network Request Failed" error while trying to hit a RESTful API. I'm running a service on localhost that uses self-signing certs (shows the "Not Secure" message in browser). I can hit the endpoint from postman, browser, console, etc. but it fails in RN.

https://localhost:8993/services

I have been through existing related issues threads including #5222 and #8118. The common fix seems to be allowing arbitrary loads in the info.plist and changing localhost into my local IP. Have tried both with no luck; error is very vague. Almost positive it is because of the self-signing certs but not sure how to enable them.

**Comment by JCDJulian** [comment]
Edit: Fixed this by editing RCTNetwork's RCTHTTPRequestHandler.

[Fix from SO.](http://stackoverflow.com/questions/36289125/react-native-fetch-from-https-server-with-self-signed-certificate)

**Comment by JCDJulian** [comment]
Closing this issue, but also wondering if there's an easier fix. There's not really a clean fix to get this working on Android.

From the answerer on the above SO thread.

> I do have an idea on how to do it, It's just a painstakingly cumbersome process, Basically, you need to build RN from source facebook.github.io/react-native/releases/next/docs/… in that source you need to find if they are using HttpsURLConnection or HttpClient. After that, I could tell you what code to insert to trust all certificates

**Comment by bsilva0x87** [comment]
Try to add this on your `ios/{projectName}/Info.plist`, it works to me!

```
  <key>NSExceptionDomains</key>
  <dict>
    <key>myhttpdomain.com</key>
    <dict>
      <key>NSIncludesSubdomains</key>
      <true/>
      <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
      <true/>
      <key>NSTemporaryExceptionMinimumTLSVersion</key>
      <string>TLSv1.1</string>
    </dict>
  </dict>
  <key>NSAppTransportSecurity</key>
  <dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
  </dict>
```

**Comment by shilihuan** [comment]
@bsilva0x87  this way just effect for ios, not with android

**Comment by shilihuan** [comment]
@bsilva0x87 how to solve the problem in android

**Comment by ntk860** [comment]
how to do it in android ?
