### ISSUE TITLE
Wrapper of DatePicker component on Android, the calendarView was disappeared after changed month

### ISSUE THREAD

**Issue by vincentsong** [facebook/react-native#13367]
### Description

I built a date picker component for react native android [here](https://github.com/vincentsong/react-native-datepicker-component-android) which is not a popup dialogue. When user scroll the calendar view, it disappeared.

### Reproduction Steps and Sample Code
1 create a test app with react-native cli
2 npm install react-native-datepicker-component-android
3 npm link
3 import this component and set `showCalendar` to true
4 run the app by `react-native run-android`
5 scroll the calendar view or tap navigation button to change the month twice.

result: you will see the calendar view disappeared

question: Is it because the view not updated?

**Comment by hramos** [comment]
You probably want to open this issue against the `react-native-datepicker-component`'s issue tracker.

**Comment by vincentsong** [comment]
Hi @hramos , how to move this issue to `react-native-datepicker-component`
