### ISSUE TITLE
PanResponder can't work with Animated.event([], {useNativeDriver: true});

### ISSUE THREAD

**Issue by magicismight** [facebook/react-native#13377]
### Description

PanResponder can't work with `Animated.event([], {useNativeDriver: true});` in iOS.

![image](https://cloud.githubusercontent.com/assets/7693239/24795072/a7fb1bf0-1bba-11e7-8cdb-aa95a0813a3e.png)

### Reproduction Steps and Sample Code

```
PanResponder.create({
      onMoveShouldSetPanResponder: (evt, gestureState) => {
       return true;
      },

      //todo: turn on useNativeDriver after 0.44.0 is landed
      onPanResponderMove: Animated.event([null, {dx: this._translateValue}], {
        listener: (evt, {dx}) => {
          this._nativeAnimationTranslated = dx;
        },
        useNativeDriver: true
      }),

      onPanResponderRelease: this._release,
      onPanResponderTerminate: this._release
    });
```

* React Native version: 0.43.1
* Platform: iOS

**Comment by hramos** [comment]
What is that comment about 0.44 about? Does this reproduce on master?

**Comment by janicduplessis** [comment]
This is a current limitation of native Animated.event. It doesn't work with PanResponder because it is implemented in JavaScript. You can have a look at https://github.com/wix/react-native-interactable which can handle gestures with native animated values.
