### ISSUE TITLE
Spelling errors in documentation

### ISSUE THREAD

**Issue by Trailblazerr1** [facebook/react-native#13380]
Hey, I was browsing through react-native docs.
And I found some spelling errors.
Here are they:
String 'sytem': [Link](http://facebook.github.io/react-native/docs/upgrading.html#1-install-git)
String 'acheived': [Link](http://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configure-permissions-for-development-error-overlay).

**Comment by hramos** [comment]
Please send us a PR with fixes :)
