### ISSUE TITLE
JSON value '<null>' of type NSNull cannot be converted to NSNumber

### ISSUE THREAD

**Issue by robcalcroft** [facebook/react-native#13381]
Having an issue with an array when using ART. Its in `react-native-chart` but the author is AWOL.
```javascript
[[["1491557700",0],["1491558000",0],["1491558300",0],["1491558600",0],["1491558900",0],["1491559200",0],["1491559500",0],["1491559800",0],["1491560100",0],["1491560400",0],["1491560700",0],["",""],["",""]]]
```
This array is causing `JSON value '<null>' of type NSNull cannot be converted to NSNumber` errors at odd times, sometimes it throws the error other times it doesn't and I cant see a pattern. Wondering if anyone can spot why this might be throwing this issue?

**Comment by ashik94vc** [comment]
I think this issue must be with the data or with the react-native-chart. Can you post the complete log to debug it further ?

**Comment by robcalcroft** [comment]
This is what the console generates:
![screen shot 2017-04-10 at 14 50 29](https://cloud.githubusercontent.com/assets/3504764/24864760/2a2f5b4c-1dfd-11e7-8018-1b6eb93cfeb0.png)
And the simulator:
![screen shot 2017-04-10 at 14 51 38](https://cloud.githubusercontent.com/assets/3504764/24864779/380a9c54-1dfd-11e7-91be-f4b0bafc6180.png)

**Comment by ashik94vc** [comment]
This seems to be an issue with the library. File an issue in the respective library. Try with the original library by tomauty.
