### ISSUE TITLE
Error: spawn cmd.exe ENOENT

### ISSUE THREAD

**Issue by ugendrang** [facebook/react-native#13387]
Environment:
react: 16.0.0-alpha.6,
react-native: 0.43.1
OS: Windows 10
node.js: 6.9.2
yarn: 0.22.0

c:\sampleproject>react-native start
.....
 Running packager on port 8088.
.....

c:\sampleproject>react-native run-android
.....
Installing APK 'app-debug.apk' on 'Nexus_5X_API_23_1(AVD) - 6.0' for app:debug
Installed on 1 device.

BUILD SUCCESSFUL

Total time: 14.114 secs
Running C:\Users\User\AppData\Local\Android\sdk/platform-tools/adb -s emulator-5554 reverse tcp:8081 tcp:8081
Starting the app on emulator-5554 (C:\Users\User\AppData\Local\Android\sdk/platform-tools/adb -s emulator-5554 shell am start -n com.sampleproject/.MainActivity)...
Starting: Intent { cmp=com.sampleproject/.MainActivity }
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd.exe ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Kindly assist to solve the issue.

**Comment by hramos** [comment]
GitHub Issues aren't the best place to troubleshoot dev environment issues I'm afraid. Feel free to reopen if you have identified a specific issue that can be addressed with a PR.

**Comment by yash365** [comment]
I am also getting exactly the same error . I tried reinstalling the nodejs but didn't work . My device is running on Android 5.1 Lollipop
