### ISSUE TITLE
Post 0.43 upgrade: PerfMonitor has no setter or ivar for its bridge

### ISSUE THREAD

**Issue by fhad-getmaple** [facebook/react-native#13384]
### Description

After upgrading to React Native version 0.43, getting the red screen with error: "PerfMonitor has no setter or ivar for its bridge, which is not permitted. You must either @synthesize the bridge property, or provide your own setter method".

<img width="371" alt="screen shot 2017-04-07 at 10 04 58 am" src="https://cloud.githubusercontent.com/assets/22453066/24803633/c9b43ae2-1b79-11e7-866d-8f0b180b8cf2.png">

### Reproduction Steps

Upgraded from version 0.42.3 using react-native-git-upgrade. There were no conflicts. Then ran "react-native link". 

### Additional Information

* React Native version: 43
* Platform: iOS
* Development Operating System: MacOS

**Comment by javache** [comment]
It looks like this line is swallowing the original exception: https://github.com/facebook/react-native/blob/master/React/Base/RCTModuleData.mm#L149-L153

Can you comment that try-catch to find the real underlying exception?

**Comment by juanviola** [comment]
Hi guys, I'm having the same issue, have you found a way to fix it?

**Comment by hyb175** [comment]
Resetting the simulator + deleting the `ios/build` folder worked for me.

**Comment by juanviola** [comment]
Awesome, you right. That worked for me!

Thanks

**Comment by alfredctchoi** [comment]
The following steps worked for me.

- clean xcode project
- stop node package manager
- rm -rf node_modules
- yarn
- restart project in simulator

**Comment by inferusvv** [comment]
Running via Xcode helped me.

**Comment by neopit** [comment]
After trying everything (rm node_module etc, clean, change the version of react-native (higher, lower, ....) dozen times. I can say the only thing WORKING for me is DELETING the IOS/BUILD folder.

Hope that help!.

**Comment by MoOx** [comment]
Another solution is via Xcode menu bar : Product > Clean. Worked for me.

**Comment by Mindaugas-Jacionis** [comment]
It is odd, because I get this error with RN 0.44.0 and only when running `react-native run-ios` command from terminal, if I am building using xcode - all is good.

**Comment by hyb175** [comment]
@Mindaugas-Jacionis That's because xcode and `react-native` store the built binaries in different folders. `react-native` stores in `your-project-folder/ios/build/`, but xcode stores in `~/Library/Developer/Xcode/DerivedData`

**Comment by Mindaugas-Jacionis** [comment]
@hyb175 you're awesome! Thanks! :)

**Comment by djalmaaraujo** [comment]
@hyb175 Your suggestion worked for me. Thanks.

**Comment by beausmith** [comment]
FWIW… these were the steps I used to fix this issue for me:

1. stop node package manager
1. open project in Xcode
1. clean Xcode project (command-shift-K)
1. build Xcode project (command-B)  **<-- this was the new step**
1. `rm -rf node_modules`
1. `npm install`
1. restart project in simulator
