### ISSUE TITLE
Application get stuck when displayLink invalidate

### ISSUE THREAD

**Issue by cxfeng1** [facebook/react-native#1340]
In my application, when I push the RCTRootView and pop it at once,  the application will easily get stuck with no touch response.  

I paused program execution and found that the program got stuck at the `invalidate`  method of `CADisplayLink`.

![2015-05-19 6 10 54](https://cloud.githubusercontent.com/assets/1625893/7703695/471a980a-fe6c-11e4-84d1-2d2a8319d559.png)

The react native version is 0.4.1.

Thanks.

**Comment by brentvatne** [comment]
@cxfeng1 - thanks for the report! Can you try this with the latest master branch (npm i facebook/react-native#master --save) and see if that fixes it? Ping me if it is not fixed and I'll reopen the issue!
