### ISSUE TITLE
[0.43] undefined is not an object (evaluating 'subscription.listener.apply') when tapping on TextInput

### ISSUE THREAD

**Issue by ragnorc** [facebook/react-native#13403]
The error `Unhandled JS Exception: undefined is not an object (evaluating 'subscription.listener.apply')` occurs when tapping on TextInput. Does anyone have an idea what the error could be?

**Comment by ide** [comment]
This happens if an undefined event listener is passed in.

**Comment by ragnorc** [comment]
Oh thanks! Had not seen that I had removed the Keyboard listener functions.
