### ISSUE TITLE
[NavigatorIOS] Swipe back not working when navigationBarHidden is true

### ISSUE THREAD

**Issue by Dharmoslap** [facebook/react-native#1341]
Would be great to have swipe back gesture working even when navigationBar is hidden. If it's not possible, it should be mentioned in the doc, that setting navigationBarHidden to 'true' removes the swipe back gesture as well.

**Comment by brentvatne** [comment]
@Dharmoslap - makes sense. Unfortunately nobody on the team is currently working on NavigatorIOS because it is not used internally - if you'd like to submit a PR for this it would be welcome!

**Comment by ide** [comment]
Look at AHKNavigationController for fix. This is an Apple idiosyncrasy and not anything React is doing.

**Comment by brentvatne** [comment]
@ide - good point. It couldn't hurt to augment the docs to reflect this odd behaviour.

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/navigatorios-swipe-back-not-working-when-navigationbarhidden-is-true
