### ISSUE TITLE
UNHANDLED JS EXCEPTION: MINIFIED REACT ERROR #143 

### ISSUE THREAD

**Issue by krishbhattacharyya** [facebook/react-native#13416]
### Description

Used ListView , ScrollView & AsyncStorage in my app. In the AsyncStorage, with the login  I have saved the logged in state with others information & clear the state with the log out.

###  Reproduction Steps and Sample Code

1) Upload my app in mobile center.
2) Login the app.
3) Navigate to a listview page ( There I rendered some big images with content ) .
4) Minimized the app.
5) Keep the app in login state for 4 days.
6) Open the app after 4 days.
7) App was crashed.
8) Got the error - UNHANDLED JS EXCEPTION: MINIFIED REACT ERROR #143 ( crash report )
 

### Additional Information

* React Native version: "0.37.0"
* Platform: IOS
* Development Operating System: MacOS
* Dev tools:  Xcode 8.3

**Comment by rmevans9** [comment]
Hey @krishbhattacharyya - Your reproduction steps don't really help anyone reproduce this issue. Can you get it to happen in a simple app so that others can see the code that you are encountering an issue with?

**Comment by krishbhattacharyya** [comment]
Thanks @rmevans9 . Sorry for late reply. But due to some privacy I could not share my code. 
As before said the app is working fine, no single issue is there. But if I open the app after long time running in background ( Not in android ) , the app shows crashed. 

Got this error in mobile center several times:

![error](https://cloud.githubusercontent.com/assets/10433734/25331939/75e08fa6-2902-11e7-818e-a203065497a4.png)

I could not understand, what is going on ( Is this related to big images or anything else ). Okay I will try  to create same scenario with demo app.

**Comment by krishbhattacharyya** [comment]
@rmevans9 thank you, I am closing this issue. I have declared null in a undefined parameter ( I found after fetching data there were some json return problem ). I don't know how my problem is solved but now it seems working fine.  So further I will reopen this if the problem reproduce again, and need your help that time.
