### ISSUE TITLE
Remove "android.permission.SYSTEM_ALERT_WINDOW" from production

### ISSUE THREAD

**Issue by hamidhadi** [facebook/react-native#13428]
I removed `android.permission.SYSTEM_ALERT_WINDOW` permission from `androidmanifest.xml` but after building the app for production, I still get `display system-level alerts` request permission. 
How can I remove this permission?

**Comment by hey99xx** [comment]
Please do a quick search, there are multiple issues asking the same thing. The most extensive discussion was in https://github.com/facebook/react-native/issues/5886
See especially mikelambert's solution of creating `/src/release/AndroidManifest.xml` file.
