### ISSUE TITLE
null is not an object (evaluating 'this.state.timeElapsed')

### ISSUE THREAD

**Issue by dennisobel** [facebook/react-native#13424]
import React, { Component } from 'react';
import { AppRegistry, Text , StyleSheet, View, TouchableHighlight, TouchableNativeFeedback} from 'react-native';

class AwesomeProject extends Component {
  getInitialState(){
    return{
        timeElapsed: null
    };
  }

  render() {
    return (
    <View style={styles.container}>
        <View style={[styles.header, this.border('yellow')]}>
            <View style={[styles.timerWrapper, this.border('red')]}>
                <Text>
                    {this.state.timeElapsed}
                </Text>
            </View>
            <View style={[styles.buttonWrapper, this.border('green')]}>
                {this.startStopButton()}
                {this.lapButton()}
            </View>
        </View>
        <View style={[styles.footer, this.border('blue')]}>
            <Text>
                List of laps
            </Text>
        </View>
    </View>
    );
  }

  startStopButton(){
    return (
        <TouchableHighlight
        underlayColor="grey"
        onPress={this.handleStartPress}>
            <Text>
               Start
            </Text>
        </TouchableHighlight>
    );
  }

  lapButton(){
    return (
        <View>
            <Text>
                Lap
            </Text>
        </View>
    );
  }

  handleStartPress(){
    var startTime = new Date();

    setInterval(() => {
    this.setState({
        timeElapsed: new Date() - startTime
    });
  }, 30);
  }
  border(color){
    return{
        borderColor: color,
        borderWidth: 4
        }

  }
  }

  var styles = StyleSheet.create({
    container : {
        flex: 1, //Fill the entire screen
        alignItems: 'stretch'
    },

    header:{//yellow
        flex: 1
    },

    footer:{//blue
        flex: 1
    },

    timerWrapper:{
        flex: 5,
        justifyContent: 'center',
        alignItems: 'center'
    },

    buttonWrapper:{
        flex: 3,
        flexDirection: 'row',
        justifyContent: 'space-around',
        alignItems: 'center'
    }
  });

AppRegistry.registerComponent('AwesomeProject', () => AwesomeProject);

**Comment by anttimo** [comment]
@dennisobel when using ES6 classes the initial state is assigned in the class constructor instead of `getInitialState` https://facebook.github.io/react/docs/state-and-lifecycle.html#adding-local-state-to-a-class

**Comment by dennisobel** [comment]
@anttimo 
so i took your advice and moved some code around. Thank God there was no errors, but...the start button isn't performing it's purpose.

here's the revised code.




import React, { Component } from 'react';
import { AppRegistry,
    Text ,
    StyleSheet,
    View,
    TouchableHighlight,
    } from 'react-native';


class AwesomeProject extends Component {

  constructor(props){
	super(props);
	this.state={timeElapsed:null};
	}  

  render() {
    return (
	
    <View style={styles.container}>
        <View style={[styles.header, this.border('yellow')]}>
            <View style={[styles.timerWrapper, this.border('red')]}>
                <Text>
                    {this.setState.timeElapsed}
                </Text>
            </View>
            <View style={[styles.buttonWrapper, this.border('green')]}>
                {this.startStopButton()}
                {this.lapButton()}
            </View>
        </View>
        <View style={[styles.footer, this.border('blue')]}>
            <Text>
                List of laps
            </Text>
        </View>
    </View>
	
    );
  }

  startStopButton(){
    return (
        <TouchableHighlight
        underlayColor="grey"
        onPress={()=>{this.handleStartPress()}}>
            <Text>
               Start
            </Text>
        </TouchableHighlight>
    );
  }

  lapButton(){
    return (
        <View>
            <Text>
                Lap
            </Text>
        </View>
    );
  }

  handleStartPress(){
    var startTime = new Date();

    setInterval(() => {
    this.setState({
        timeElapsed: new Date() - startTime
    });
  }, 30);
  }

  border(color){
    return{
        borderColor: color,
        borderWidth: 4
        }

  }
  }

  var styles = StyleSheet.create({
    container : {
        flex: 1, //Fill the entire screen
        alignItems: 'stretch'
    },

    header:{//yellow
        flex: 1
    },

    footer:{//blue
        flex: 1
    },

    timerWrapper:{
        flex: 5,
        justifyContent: 'center',
        alignItems: 'center'
    },

    buttonWrapper:{
        flex: 3,
        flexDirection: 'row',
        justifyContent: 'space-around',
        alignItems: 'center'
    }
  });

AppRegistry.registerComponent('AwesomeProject', () => AwesomeProject);

**Comment by dennisobel** [comment]
onPress() isn't doing anything

**Comment by roadev** [comment]
Try changing `handleStartPress() {` by `handleStartPress = () => {`
