### ISSUE TITLE
[TextInput] Text longer then visible area is hidden.

### ISSUE THREAD

**Issue by dbarros** [facebook/react-native#13436]
### Description

When creating a TextInput, and I enter more text than can be displayed in a single line component, the text and cursor does not move to be visible as I continue to type.

### Reproduction Steps and Sample Code

Create a TextInput:

```
render() {
    return (<TextInput style={ { borderWidth: 1, height: 20, width: '100%', top: 40 }}></TextInput>)
}
```
When the app is run, and you enter text in the TextInput, as soon as you get to the right edge of the TextInput, the cursor runs off to the right, the text being entered does not shift to be visible.

![Screenshot](http://i.imgur.com/OGVlMQz.png)

### Solution

As per the default behaviour in iOS, I would expect the text to move, so that as I continue to type while at the end of the input field, and see what I am typing.

### Additional Information

* React Native version: 0.43.0
* Platform: iOS 10.3 (Simulator), macOS 10.12.4
* Development Operating System: macOS 10.12.4
* Dev tools: Xcode 8.3.1

**Comment by stephlm2dev** [comment]
I had the same problem until I remove the `width` property style on the `TextInput` and wrap it in a View where you can specify the `width`. Something like this:

```
<View style={{width= 100}}>
  <TextInput style={ { borderWidth: 1, height: 20}}></TextInput>
</View>
```

**Comment by dbarros** [comment]
@stephlm2dev thanks for the tip, but unfortunately, it's not fixing the problem for me. When I enter text it still disappears to the right edge of the TextInput.

**Comment by dbarros** [comment]
OK, I had a height of 20 on the TextInput, when I increased it to 26 (for example), it worked as expected.
