### ISSUE TITLE
Tried to show an alert while not attached to an Activity

### ISSUE THREAD

**Issue by sunxlfred** [facebook/react-native#13439]
* android 7.0
* react-native 0.43
* when i use the 'alert' in an android app which integrated the react-native
the code after:

```

	import React, {Component} from 'react';
	import {
	    AppRegistry,
	    StyleSheet,
	    Text,
	    View,
	    Navigator,
	    Button,
	    Alert,
	} from 'react-native';
	
	
	class HelloWorld extends React.Component {
	    show(){
	        Alert.alert(
	            'Alert Title',
	            'alertMessage',
	        )
	    }
	    render() {
	        return (
	            < View
	                style={styles.container
	                }>
	                <Text
	                    style={styles.hello
	                    }>
	                    Hello, World </ Text >
	                <Button title="a"
	                        onPress={this.show.bind(this)
	                        }/>
	            </ View >
	        )
	    }
	}
	
	var styles = StyleSheet.create({
	    container: {
	        flex: 1,
	        justifyContent: 'center',
	    },
	    hello: {
	        fontSize: 20,
	        textAlign: 'center',
	        margin: 10,
	    },
	});
	
	AppRegistry.registerComponent('a', () => HelloWorld);

```

it give me the warning like this and no dialog show
* ![](https://raw.githubusercontent.com/sunxlfree/RES/master/rn_alert.png)
* ![](https://raw.githubusercontent.com/sunxlfree/RES/master/rn_alert2.png)

**Comment by vonovak** [comment]
try to show the alert after a timeout, eg 100ms

**Comment by sunxlfree** [comment]
no there is nothing wrong with the timeout.
i find it that just because i integrated the react-native with my Android App,
if i run it as a independent react-native project, that's ok
but if i integrate it in my android app, there's this warning and there's no dialog come out

**Comment by esilverberg** [comment]
I also experience the same behavior -- "run it as a independent react-native project, that's ok", "if i integrate it into my android app, there's this warning and there's no dialog come out"

**Comment by ymmn** [comment]
I also ran into this when I followed the [integration with existing apps](https://facebook.github.io/react-native/docs/integration-with-existing-apps.html#add-native-code) tutorial. 

But it's not an issue when you make your application implement `ReactApplication` and your activity inherit from `ReactActivity`

**Comment by sunxlfree** [comment]
@ymmn it seems that there's no `ReactApplication` in RN 0.42.0

**Comment by ymmn** [comment]
@sunxlfree hmm, seems like [ReactApplication](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/ReactApplication.java) hasnt been touched in a year. it should be there

**Comment by saghul** [comment]
I had the same problem, and I solved it by hooking my custom activity's (the one which renders the ReactNativeRootView) lifecycle methods to the ReactNativeInstanceManager as the docs describe: http://facebook.github.io/react-native/releases/0.42/docs/integration-with-existing-apps.html#add-native-code

Specifically I added onPause, onResume, onDestroy and onBackPressed (though you don't need the last one). By reading the code [here](https://github.com/facebook/react-native/blob/0.42-stable/ReactAndroid/src/main/java/com/facebook/react/ReactInstanceManager.java#L521-L590) you'll see that the current activity is saved with those.

I hope that helps. Cheers!

**Comment by froimsonm** [comment]
Facing same issue.
I followed the[ integration with existing apps](https://facebook.github.io/react-native/docs/integration-with-existing-apps.html#add-native-code) tutorial.

RN version 0.48.3

**Comment by MephistoDemon** [comment]
Facing same issue.
I followed the integration with existing apps tutorial.

RN version 0.48.0

**Comment by marcmo** [comment]
why is this closed? it still is very much an issue!
for me I see this a lot, running with 
RN version 0.55.13

**Comment by MarkOSullivan94** [comment]
For anyone who is experiencing this issue while using RN in a fragment, make sure you have defined the current activity for the ReactInstanceManager.

Example:

```
 mReactInstanceManager = ReactInstanceManager.builder()
                .setApplication(getActivity().getApplication())
                .setCurrentActivity(getActivity())
                .setBundleAssetName("index.android.bundle")
                .setJSMainModulePath("index")
                .addPackage(new MainReactPackage())
                .setUseDeveloperSupport(BuildConfig.DEBUG)
                .setInitialLifecycleState(LifecycleState.RESUMED)
                .build();
```
