### ISSUE TITLE
[Idea: LiveReload] Automatic reload fails when there is an error.

### ISSUE THREAD

**Issue by jaygarcia** [facebook/react-native#1343]
Automatic reload should reload the content after a file for a bundle is saved.  This works well when there are no errors, but if I edit a bunch, save, and cause something like a parse error, automatic reload fails to do its job. I have to manually focus the sim and hit CMD+R.

Not a huge bug, but an annoying one :)~.

**Comment by jaygarcia** [comment]
I will say that this issue only seems to be a parsing error condition.  Logic errors seem to work fine =)

**Comment by iostalk** [comment]
It's an awesome job! A pull request would be appreciated!

**Comment by aaronschubert0** [comment]
+1

**Comment by brentvatne** [comment]
This would be a nice feature to have, PR welcome

**Comment by browniefed** [comment]
@brentvatne already solved

**Comment by brentvatne** [comment]
Thanks @browniefed :smile:
