### ISSUE TITLE
Could not remote debugging on real devices

### ISSUE THREAD

**Issue by vjtc0n** [facebook/react-native#13441]
Hello,
I'm facing this issue recently.

Description: it was like my mac released the app to my phone, not debug and I don't know why.
Even I turn off the packager, the app still runs like normal way.
And I see no hot reloading and some other options.

More weird, when I use other iphones, the debug process is correct like I did before, but my phone still happens the above issue.

Does anyone have this proplem ?

![screen shot 2017-04-11 at 4 26 16 pm](https://cloud.githubusercontent.com/assets/13517057/24902486/80b262ca-1ed4-11e7-8830-950b327c7853.png)

* React Native version: 0.43.3
* Platform: iOS
* Development Operating System: MACOSX 10.11.6

**Comment by ansmonjol** [comment]
Did you tried `adb reverse tcp:8081 tcp:8081` before running your app ?

**Comment by vjtc0n** [comment]
@ansmonjol thanks for your advice but it doesn't work.

But I could handle it by restarting my mac and reboot my phone, my internet modem aswell as deleting derived data.
And now it works like a charm...Still I don't know why but maybe it's an issue from xcode.
I think we could close the topic from now.
Thank you.
