### ISSUE TITLE
Objects are not valid as a React child

### ISSUE THREAD

**Issue by agrass** [facebook/react-native#13447]
Hello!  

Some times I'm getting this error:

`com.facebook.react.common.JavascriptException: Minified React error #31; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7BLocation%20Example%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings `

`Objects are not valid as a React child (found: object with keys {Location Example}). `

It's weird, sometimes work well and other it throw this error when rendering an array of Views with some Texts inside with different values. 

### Additional Information

* React Native version: 0.35
* Platform: Android

Thanks!

**Comment by vonovak** [comment]
http://stackoverflow.com/questions/33117449/invariant-violation-objects-are-not-valid-as-a-react-child
