### ISSUE TITLE
Expected array with count 16, but count is 7 in RCTConvert.m

### ISSUE THREAD

**Issue by grahamtallen** [facebook/react-native#13455]
After upgrading to 0.43, I ran into this error after building with the Debug scheme:

"Expected array with count 16, but count is 7"
- see screenshot for entire offending object
- Trace:

_at RCTConvertCGSTructValue + 395
RCTConvert.m:397_

_RCTConvert CATransform3D: + 193_

_RCTViewManger
set_transfrom:forView:withDefaultView..._

![screen shot 2017-04-11 at 1 52 23 pm](https://cloud.githubusercontent.com/assets/14982690/24930372/2236026c-1ebe-11e7-8cb0-e8fb7acdf901.png)

### Additional Information

* React Native version: 0.43.3
* Platform: iOS
* Development Operating System: Mac0S
* Dev tools: Xcode 8.3.1

**Comment by momotofu** [comment]
Ran into this issue as well. Deleting the native build folder and rebuilding does not fix it either.

**Comment by Praveen1404** [comment]
Facing same issue but React-Native version is 0.42.3
![image](https://cloud.githubusercontent.com/assets/22890212/25000079/94007f9e-205d-11e7-8668-4c3a86d375fd.png)

**Comment by felangga** [comment]
Had the same problem :(

**Comment by ajonno** [comment]
Same here. Crazy ! I thought the upgrade process was 'fixed' w/ react-native-git-upgrade? The thought of having to completely 'copy/paste' code from our 0.41 app to latest version is a nightmare.

**Comment by urikphytech** [comment]
+1

**Comment by jsanchezs** [comment]
+1

**Comment by nathmack** [comment]
+1

**Comment by ajamiesonfraser** [comment]
+1
