### ISSUE TITLE
Horizontal ListView Resets Scroll View contentOffset on update

### ISSUE THREAD

**Issue by adi69** [facebook/react-native#13457]
I've a horizontal ListView. When the dataSource is updated, hence the ListView,  it scrolls with contentOffset `{0,0}`, no matter what the current contentOffset is. Here is the snippet of view:
```
 <ListView
          horizontal
          dataSource={this.state.dataSource.cloneWithRowsAndSections({
            section1: this.state.products,
          })}
          renderRow={this.renderRow.bind(this)}
        />
```

I've tried `onScroll={this.handleScroll.bind(this)}` and updating contentOffset in global state, but the changes don't reflect even when ListView is update with `contentOffset={this.state.contentOffset}`.

**Comment by hramos** [comment]
Thanks for reporting this! Can you try out `FlatList` instead? If it is still an issue there, please do submit a new issue against `FlatList`.

**Comment by gezichenshan** [comment]
YES.Same issue with FlatList.
