### ISSUE TITLE
[FlatList] onViewableItemsChanged does not trigger when items change

### ISSUE THREAD

**Issue by iggyfisk** [facebook/react-native#13467]
### Description

We want to keep track of which items in a FlatList are currently being displayed. `onViewableItemsChanged` works great for this on initial render + when scrolling through the list. But when the items change, in our case because of a pull-to-refresh, `onViewableItemsChanged` isn't called until the next scroll event. 

Possibly similar to https://github.com/facebook/react-native/issues/13454 but there's no `getItemLayout` required.

### Reproduction Steps and Sample Code

I made a [demo app](https://github.com/iggyfisk/flatlistviewable) that you can clone, `npm install` and `react-native run-ios`. Or just look at the [relevant code](https://github.com/iggyfisk/flatlistviewable/blob/master/viewableviewer.js) and this [video demonstration](https://drive.google.com/file/d/0B5fs1EXo7qsLamxwSFFFY2d3TTg).

At first you can see scrolling through the list, the status text updates perfectly. But after the first two refreshes, the status text shows the IDs of old items because `onViewableItemsChanged` was never called after the new data arrived. On the third refresh I linger with the drag, which causes more scroll events and therefore the status text updates after the new data has been rendered.

### Solution

I'm assuming the goal is for `onViewableItemsChanged` to let an app like this example work pretty much off the bat. But if there's no plan to support this scenario, maybe you could expose some of the tools inside VirtualizedList and ViewabilityHelper that would help make it work?

We know when the new data arrives and has been rendered, but the problem when attempting a workaround is there's no straightforward way to figure out which items are viewable on demand. There's obviously a ton of work behind ViewabilityHelper, it seems silly to recreate it in application code. Maybe a `getViewableItems` method that spits a similar format to the one sent to the `onViewableItemsChanged` callback? I ask and @sahrens answers.

### Additional Information

* React Native version: 0.43.3
* Platform: iOS tested, probably Android too
* Development Operating System: macOs
* Dev tools: Xcode 8.3.1

**Comment by sahrens** [comment]
Sounds like an oversight, thanks for the report! The fix is probably just to call the viewability helper in compobentDidUpdate. There is a similar bug with onEndReached. Will fix right away.

**Comment by iggyfisk** [comment]
I think this got lost in the heap @sahrens ? 💃 
Or maybe it wasn't as easy as it seemed

**Comment by iggyfisk** [comment]
I'm not exactly sure when this was fixed but it's fixed now, thanks boys!
