### ISSUE TITLE
Android BackButton not work when I pressed the second time.

### ISSUE THREAD

**Issue by WhatAKitty** [facebook/react-native#13468]
### Description

```
if (Platform.OS === 'android') {
    BackAndroid.addEventListener('hardwareBackPress', this.onBackAndroid);
}
```
The code I wrote added in` componetWillMount`, the first time triggered but not worked the second time.

### Additional Information

* React Native version: 0.39.0
* Platform: Android
* Development Operating System: MacOS 10.12.4
* Dev tools: Android SDK 23

**Comment by 424626154** [comment]
I had the same problem。
