### ISSUE TITLE
"react-native link" error

### ISSUE THREAD

**Issue by EgaSetya** [facebook/react-native#13461]
I tried to run react-native link after running npm install, this was working fine before now I got this error 
`ERR! It seems something went wrong while linking. Error: Expected "/* Begin ", "/* End ", "\"" or [A-Za-z0-9_.] but "<" found. 
Please file an issue here: https://github.com/facebook/react-native/issues`

What causes this error?

**Comment by stoffern** [comment]
what libs are you linking? and please provide full error log

**Comment by Fantasim** [comment]
Hi,

I got the same error ! and i cannot open my xcode project now.

**Comment by Kureev** [comment]
> I got the same error ! and i cannot open my xcode project now.

@Fantasim you can always use `git checkout <yourproj>.xcodeproj` to reset this change.

Can you also provide a name of the library that causes this issue? Without it, we can't do anything.

**Comment by naoey** [comment]
Just encountered the same error. It seems to be caused by a corrupt .xcodeproj file because the linking fails on the first iOS module it encounters.

@Fantasim @EgaSetya we were able to fix it by checking out an older version of the .xcodeproj file worked and then ran link again.

**Comment by stoffern** [comment]
As @Kureev said, please provide the name of the library you use and full log.
right now it looks like there is a problem with the library you are linking itself and not react-native.

Until we see what library or error this is we can not do anything.

**Comment by naoey** [comment]
It's not specific to any library. I deleted the libs one by one to confirm this and the problem still occured.

As I said, it seems to be purely because of the corrupt .xcodeproj file. Android modules were still linking fine, it failed on the first iOS module in the alphabetical order of installed libs. Restoring the .xcodeproj to the last non-corrupt version fixed it with the same set of installed libs.

**Comment by EgaSetya** [comment]
@stoffern @Kureev   Where can I find full error log? I only got 2 line of error when running "react-native link" on terminal

@naoey I tried running "git checkout -- myproject.xcodeproj" and got this error `error: pathspec 'Pictalogi.xcodeproj' did not match any file(s) known to git.`

**Comment by naoey** [comment]
You need to give the full path, which will be ios/Pictalogi.xcodeproj

If you've already committed the corrupt file you need to specify a previous commit revision when checking out.

**Comment by EgaSetya** [comment]
@naoey I haven't committed the file yet and I already try as you suggested but it caused the same error.

**Comment by Kureev** [comment]
Can you share the diff of corrupted file so we can check where react-native link corrupts it?

**Comment by dillonykyang** [comment]
I have the issue with this library https://github.com/xinthink/react-native-material-kit

These lines (diff) are causing the error:
```

-				HEADER_SEARCH_PATHS = "$(SRCROOT)/../node_modules/react-native-navigation/ios/**";
+				HEADER_SEARCH_PATHS = "$(SRCROOT)/../node_modules/react-native-navigation/ios/**""$(SRCROOT)/../node_modules/react-native-material-kit/iOS/RCTMaterialKit";

```

**Comment by EgaSetya** [comment]
@Kureev @stoffern I got so many line diff on my project.pbxproj() [link to file](http://pasted.co/45a26907). Do I have to fix this manually?

**Comment by ncuillery** [comment]
@dillonykyang I had a similar issue.

Before using the link command, change all the `HEADER_SEARCH_PATHS` that have a mono-string value
```
HEADER_SEARCH_PATHS = "$(SRCROOT)/../node_modules/react-native-navigation/ios/**";
```

to a multi-string value:
```
HEADER_SEARCH_PATHS = (
  "$(SRCROOT)/../node_modules/react-native-navigation/ios/**",
);
```

The link command should work properly now.

**Comment by ncuillery** [comment]
@EgaSetya Yes, you do. You'll find some useful information in this thread #12261, starting from this post: https://github.com/facebook/react-native/issues/12261#issuecomment-282592590

**Comment by sibelius** [comment]
You should do the same for 

`LIBRARY_SEARCH_PATHS = "$(inherited)";`

**Comment by akyGit** [comment]
multi-string value does not resolve thit issue

```
    "react": "15.4.1",
    "react-native": "0.39.2",
```

**Comment by Clowning** [comment]
I've the same issue!

**Comment by ililysong** [comment]
I got same issue.

**Comment by D-Maher** [comment]
As do I.

**Comment by D-Maher** [comment]
Similar if not same issue here. My error message:
```
ERR! Something went wrong while linking. Error: Cannot read property 'nodeValue' of undefined 
```

**Comment by ililysong** [comment]
I have created the new project with same name, installed the npm module again using the npm install.
resolved the issue.

**Comment by ouss-athome** [comment]
Same probleme here. I tried to inspect the pbxproj whith no success.

**Comment by fgonzalezm** [comment]
I had this same error too when installing 0.6.1. I reverted and installed 0.6.0 as was suggested and that worked. The HEADER_SEARCH_PATHS were already a multi-string value.

**Comment by brianjlandau** [comment]
I too found that using 0.6.0 solved the linking issue.

**Comment by luojinghui** [comment]
@ncuillery thanks ,i resolved the issue.

**Comment by mochadwi** [comment]
Make sure to git diff your *.pbxproj

In our case, there's a lot of "conflicts". So the Xcode can't parse the project.

![screen shot 2017-11-03 at 8 29 49 am](https://user-images.githubusercontent.com/7057959/32357633-3afe41e2-c071-11e7-8548-dc75d5e58527.png)

**Comment by saeedhei** [comment]
I Can't Find `HEADER_SEARCH_PATHS` for android, Where is that?

**Comment by caseyg1204** [comment]
This resolved issue for me: https://stackoverflow.com/questions/34997584/cordova-build-error-nodevalue-undefined/35237655

**Comment by same07** [comment]
@mochadwi thank u man.. u save my day..

**Comment by percivalruiz-bibo** [comment]
Have you tried doing `react-native upgrade` before `react-native link`? That worked for me.

**Comment by pentarex** [comment]
@percivalruiz-bibo this is not the case, it is merge conflicts in project.pbxproj file

**Comment by edumelzer** [comment]
This error seems to be related to <code>Info.plist</code> to me.

Steps to reproduce on my project:

1. <code>react-native link</code>: FINE, but <code>Info.plist</code> was changed.
2. <code>react-native link</code>: ERR! Something went wrong while linking. Error: Cannot read property 'nodeValue' of undefined
3. I revert changes made to <code>Info.plist</code>
4. <code>react-native link</code>: FINE, but <code>Info.plist</code> was changed again.
5. <code>react-native link</code>: ERR! Something went wrong while linking. Error: Cannot read property 'nodeValue' of undefined

**Environment:** I tested this on Windows and Mac:
```
"react": "16.3.1", 
"react-native": "0.55.2",
```

Below are the changes made on my Info.plist when running <code>react-native link</code>:
![changes_infoplist](https://user-images.githubusercontent.com/2285773/38954848-3deb05bc-4329-11e8-824e-2463daeb263b.png)

**Comment by ACCTFORGH** [comment]
@mochadwi The text used now are ours and theirs, instead of HEAD.
