### ISSUE TITLE
BackAndroid.ExitApp() not working properly .

### ISSUE THREAD

**Issue by PARAGJYOTI** [facebook/react-native#13483]
### Description

Trying to Exit App on 'backButtonPressEvent' but not Working as Expected .

### Reproduction Steps and Sample Code

        componentDidMount(){
        
        BackAndroid.addEventListener('hardwareBackPress', function() {
 

        BackAndroid.exitApp()

        return false (tried with return true also)
       })
       }

     render(){
    
    var navigationView = (
    <Menu closeDrawer={this.closeDrawer}   {...this.props}/>
    ) ;

    return (
    <DrawerLayoutAndroid
      ref={(_drawer) => this.drawer = _drawer}
      drawerWidth={270}
      drawerPosition={DrawerLayoutAndroid.positions.Left}
      renderNavigationView={() => navigationView}>
      
      <Nav  {...this.props} openDrawer={this.openDrawer} closeDrawer={this.closeDrawer}/>
    </DrawerLayoutAndroid>
          )
       }
     }

This event Only fire once in the Component . Within this component there's DrawerLayout which have a 
Scrollable-Tab-View component (Nav) . If I dont navigate to any tabs after mount , it works but after that the event doesn't get fired . Am I doing something wrong ? I dont know its the correct way call BackAndroid.exitApp() .

### Additional Information

* React Native version: 0.43.3
* Platform:Android
* Development Operating System: Windows 10

**Comment by basudz365** [comment]
@PARAGJYOTI exitApp() is just a standalone static method that you would call directly when you want to exit the app in ways other than the hardware back button press.  You would not use it inside of the BackAndroid.addEventListener.

The BackAndroid.addEventListener listens for the native hardware back button press and will ignore it if you return true, or execute the native back press (and exit the app) if you return false.  This gives you the ability to navigate back through your navigation stack or tabs without exiting the app.  Also gives you the ability to do any cleanup in your app before exiting the app.

Keep in mind that if you have multiple listeners setup you will have to be aware of the order of their subscriptions as noted by the docs:
"The event subscriptions are called in reverse order (i.e. last registered subscription first), and if one subscription returns true then subscriptions registered earlier will not be called."

**Comment by MrPluto** [comment]
seems `BackAndroid.exitApp()` won't kill the App's process ? 🤔

**Comment by timtawan** [comment]
Yes

componentWillMount() {
		let self = this;
	 	BackAndroid.addEventListener('hardwareBackPress', () => {
	    	if(self.props.nav.index > 0) {
	    		this.props.dispatch({ type:"Navigation/BACK" });
	    		return true;
	    	} else {	
	        	Alert.alert(
				  'Exit App',
				  'Exiting the application?',
				  [
	 			    {text: 'Cancel', onPress: () => console.log('Cancel Pressed'), style: 'cancel'},
				    {text: 'OK', onPress: () => DeviceEventManager.invokeDefaultBackPressHandler() },
				  ],
				  { cancelable: false }
				)
	            return true;
	    	}
	    });
	}

BackAndroid.exitApp() won't kill the App's process

**Comment by PARAGJYOTI** [comment]
Thanks dude . Seems so helpful . I am gonna try this .

**Comment by Obooman** [comment]
Same issue here,
I registered two scenes(`SceneOne` and `SceneTwo`) with `react-navigation`,both of them handle back button as `exit`

1. Use the `SceneOne` component as root scene
2. The navigation stack is `[SceneOne,SceneTwo]`.
3. Press back button exit the app with [exitApp](https://facebook.github.io/react-native/docs/backhandler.html#exitapp) function.
4. Restart the application I see `SceneTwo` instead of `SceneOne`

I have tried replace [exitApp](https://facebook.github.io/react-native/docs/backhandler.html#exitapp)  with `DeviceEventManager.invokeDefaultBackPressHandler()`,It doesn't work for me.

#### Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.45.1
| node             | 8.0.1
| yarn      | 0.15.1
| OS|macOS 10.12.5
| android | 6.0.1

**Comment by hfossli** [comment]
Related to https://github.com/facebook/react-native/issues/10266 and https://github.com/facebook/react-native/issues/8570?

**Comment by Luavis** [comment]
BackHandler.exitApp is not shutdown application but it call device to [press back button](https://github.com/facebook/react-native/blob/0.40-stable/Libraries/Utilities/BackAndroid.android.js#L65). It seems in activity resume state RN resume all previous state.
I don't know why RN doesn't call `finish` method to current react Activity or kill process.

**Comment by devanshsadhotra** [comment]
```componentWillMount() {
let self = this;
BackAndroid.addEventListener('hardwareBackPress', () => {
if(self.props.nav.index > 0) {
this.props.dispatch({ type:"Navigation/BACK" });
return true;
} else {
Alert.alert(
'Exit App',
'Exiting the application?',
[
{text: 'Cancel', onPress: () => console.log('Cancel Pressed'), style: 'cancel'},
{text: 'OK', onPress: () => BackHandler.exitApp() },
],
{ cancelable: false }
)
return true;
}
});
}```

@timtawan i made a little alteration in your code and BackHandler.exitApp() worked as desired .

**Comment by SudoPlz** [comment]
If you're using `wix/react-router-navigation` make sure that you're not passing `overrideBackPress: true` to your scheme, otherwise the back press will be overriden.
