### ISSUE TITLE
Let a WebView be loaded with html, rather than a url

### ISSUE THREAD

**Issue by oveddan** [facebook/react-native#1348]
This would allow us to inject raw html into the WebView.  If this is currently possible, then provide documentation for it.

**Comment by christopherdro** [comment]
http://facebook.github.io/react-native/docs/webview.html#content

WebView already has that option. Just make sure to pass in it in as a string.

**Comment by TouchQQ** [comment]
@christopherdro  it's not work...

**Comment by oveddan** [comment]
I can't see how it would work without HTML being publicly exposed via the interface https://github.com/facebook/react-native/blob/6500ba7bfbdc2bd8e3301813b3cb606aeea35331/React/Views/RCTWebView.h#L14

**Comment by christopherdro** [comment]
You need the html property and it seems you need to add ```webView:{}``` in your styles.

Here's a fiddle showing it to work.
https://rnplay.org/plays/6JolNQ/edit

**Comment by brentvatne** [comment]
@christopherdro - nice demo :smile:
