### ISSUE TITLE
[Idea: Webview] Enable injecting javascript into a WebView

### ISSUE THREAD

**Issue by oveddan** [facebook/react-native#1349]
This way we can take an existing web view and run custom javascript in it, as the WKWebview allows you to do via [WKUserScript](https://developer.apple.com/library/ios/documentation/WebKit/Reference/WKUserScript_Ref/index.html#//apple_ref/occ/cl/WKUserScript)

**Comment by brentvatne** [comment]
Seems reasonable, can you submit a PR @oveddan?

**Comment by oveddan** [comment]
Sure I can work on it.

**Comment by brentvatne** [comment]
Awesome :smile:

**Comment by brentvatne** [comment]
I think we would probably want to execute the JS via a direct function call, eg:

`<WebView ref="myWebView" />`

`this.refs.myWebView.execute('alert("hello world")')`

It would also be neat if there was some way to get data back via a callback function :smile:

**Comment by tadeuzagallo** [comment]
Keep in mind that `WKWebView` in only available on iOS 8.0 and later, and React Native supports iOS 7.

Also `WKWebView`, as far as I know, is not stable enough to replace `UIWebView` yet, so it might be a better idea to make it a npm module that replaces the built-in `RCTWebView`.

**Comment by brentvatne** [comment]
Good points @tadeuzagallo!

If we want to integrate this into our standard `UIWebView` based `WebView` perhaps we can just use [stringByEvaluatingJavaScriptFromString](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIWebView_Class/#//apple_ref/occ/instm/UIWebView/stringByEvaluatingJavaScriptFromString:)?

**Comment by oveddan** [comment]
@tadeuzagallo yeah in an ideal world we would be able to build this around `WKWebView`, but it's only supported in IOS8, and it's not really production ready - for example, loading html from the local file system doesn't work, nor does leveraging the html5 appcache to make a page loaded from a remote server available offline.  Those two things two work with a standard WebView.

I'd want to follow a similar pattern to (WebViewJavascriptBridge)[https://github.com/marcuswestin/WebViewJavascriptBridge], which is built on top of a `WebView`, and as you suggested @brentvatne leverages stringByEvaluatingJavasScriptFromString [here](https://github.com/marcuswestin/WebViewJavascriptBridge/blob/master/WebViewJavascriptBridge/WebViewJavascriptBridge.m#L145)

My main concern is that this would add a lot of bloat to the RCTWebView - maybe this should be done as a separate github repo.  What do you think?

**Comment by brentvatne** [comment]
@oveddan - let's try it as a separate Github repo and see how it turns out, if doesn't end up being too large or if there turns out to be a lot of demand then it might be worth integrating into core

**Comment by brentvatne** [comment]
@oveddan - fyi, I just noticed #1191

**Comment by alinz** [comment]
+1

@brentvatne Any news on when it's going to be merged? #1191 is not merged yet so should I wait?

**Comment by oveddan** [comment]
@brentvatne Thanks for noticing #1191 - I believe this issue will be resolved when that is merged.

**Comment by brentvatne** [comment]
@alinz - not sure when, it's a WIP. @oveddan - great, feel free to drop in there with comments to make sure it's appropriate for the use cases you foresee you will need :smile:

**Comment by alinz** [comment]
@brentvatne, I ended up porting [one of the iOS](https://github.com/marcuswestin/WebViewJavascriptBridge) javascript bridge to react-native. [react-native-webview-bridge](https://github.com/alinz/react-native-webview-bridge). I hope it can be useful for someone else.

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/idea-webview-enable-injecting-javascript-into-a-webview
