### ISSUE TITLE
"Rage shake" gesture interferes with Moto gestures.

### ISSUE THREAD

**Issue by joachimroeleveld** [facebook/react-native#13490]
The "rage shake" gesture that opens the dev menu, interferes with gestures on Motorola phones with Moto gestures enabled.

![gestures-on-moto-g-2015-1-1024x792](https://cloud.githubusercontent.com/assets/5803704/25016942/22699e36-2082-11e7-887a-58d6c0355da3.jpg)

I found it so difficult to get the menu to show that I disabled the Moto gestures in order to be able to continue developing.

An alternative manner to open the menu would be welcome for these users. A solution could be a permanent notification that opens the menu on tap. You could optionally make this a toggle in the settings.

(I'm a beginner to RN, would have been happy to submit a pull request otherwise.)

**Comment by hramos** [comment]
Ah, this is unfortunate. I do think that disabling the gestures is the way to go for now as it does not seem to be affecting too many developers.
