### ISSUE TITLE
[FlatList] `setNativeProps` does not work with `FlatList` component

### ISSUE THREAD

**Issue by liuzhibopp** [facebook/react-native#13501]
`setNativeProps` does not work with `FlatList` component

thanks in advance。

**Comment by huangxiwen** [comment]
i need the setNativeProps support too.

**Comment by henrikra** [comment]
Btw what are the advantages of using `setNativeProps`

**Comment by browniefed** [comment]
It allows you to set the properties on the native component without triggering a set state to happen

**Comment by henrikra** [comment]
What are the benefits of that? Some use case for example?

**Comment by vonovak** [comment]
@henrikra the docs are helpful in clarifying this http://facebook.github.io/react-native/releases/0.43/docs/direct-manipulation.html

**Comment by ide** [comment]
There is a PR for this: https://github.com/facebook/react-native/pull/13529
