### ISSUE TITLE
0.43.3 [TextInput] multiline={true}  in Android can not create newLine when I enter Soft KeyBoard of return.

### ISSUE THREAD

**Issue by xuyuanzhou** [facebook/react-native#13506]
0.43.3 [TextInput] multiline={true}  in Android can not create newLine when I enter Soft KeyBoard of return.

**Comment by xuyuanzhou** [comment]
in 0.43.3

**Comment by hoangpham95** [comment]
Could you put a code snippet?

**Comment by ksegla** [comment]
I have the exact same problem. 
It used to work before. Last version I remember where it used to work is  0.41.

As for a code snippet, something as simple as the following exhibits the bug.

`                <View>
                    <TextInput                        
                        multiline={true}  
                        numberOfLines={3}                      
                    />
                </View>`

**Comment by zhangzhhz** [comment]
There is an issue opened already for this. #12717 . Broke since 0.42. Still not resolved in 0.43.3.

**Comment by ZHT131** [comment]
0.46 have you solved the problem?

**Comment by ZHT131** [comment]
Has anyone solved the problem of not adding new lines?

**Comment by codewithpassion** [comment]
@ZHT131 check out https://gist.github.com/catchin/47afe706256604959c13dc25e7bb9383
That works for me. 048.1 still didn't work for me via Expo.

**Comment by kkusanagi** [comment]
new line work on 0.41. 
starting 0.42 and above until 0.49 still NOT Working.

**Comment by anandsai79** [comment]
I'm also facing the same issue, let me know if anyone found solution for this...

**Comment by kkusanagi** [comment]
install 0.51 React native will fixed all the problem.

also use cradle 2.3.3 and above
