### ISSUE TITLE
[FlatList] Rows rendering. 

### ISSUE THREAD

**Issue by CodeXtinction** [facebook/react-native#13516]
[https://facebook.github.io/react-native/docs/flatlist.html](url)

> In order to constrain memory and enable smooth scrolling, content is rendered asynchronously offscreen. This means it's possible to scroll faster than the fill rate ands momentarily see blank content. This is a tradeoff that can be adjusted to suit the needs of each application, and we are working on improving it behind the scenes.

is this what that means? how to improve? it doesn't look good for ux

how to reproduce?
create a FlatList  and scroll faster as you can.

![](https://media.giphy.com/media/7lj79pST1l0yY/giphy.gif)

react-native 0.43.3 
real device android 6.0

**Comment by hramos** [comment]
This is a known problem, as noted in the announcement.
