### ISSUE TITLE
Release Notes not being updated

### ISSUE THREAD

**Issue by Mayzie** [facebook/react-native#13519]
The Release Notes links for later React Native versions on the [versions](https://facebook.github.io/react-native/versions.html) page link to tagged releases, however those tags do not have any complete releases notes associated with them. For example, versions [0.43.0](https://github.com/facebook/react-native/releases/tag/v0.43.0) and [0.44.0-rc.0](https://github.com/facebook/react-native/releases/tag/v0.44.0-rc.0), despite the fact that those were tagged nearly two weeks ago.

**Comment by ndbroadbent** [comment]
+1 on this. I noticed that `0.43.0` doesn't have any release notes, while there are lots of notes for `0.43.1`: https://github.com/facebook/react-native/releases/tag/v0.43.1

I found this to be pretty confusing.

**Comment by charpeni** [comment]
Thank you for the reporting.

I'll close this issue in favor of #13540, since it's a duplicated one. Sorry I didn't saw this issue before I answered to the other one.

**Comment by charpeni** [comment]
@facebook-github-bot duplicate #13540
