### ISSUE TITLE
[WebView] Can not use hash tag and query string in WebView while loading a file from local file.

### ISSUE THREAD

**Issue by magicismight** [facebook/react-native#13510]
### Description

Can not use hash tag and query string in `WebView` while loading a file from local file.

### Reproduction Steps and Sample Code

Those local `uri`s cannot work in WebView.
They have been encoded and never decoded before convert them into a NSURL.

```
<WebView source={{uri: 'file:///xx/yy/zz.html?query'}} />
```

```
<WebView source={{uri: 'file:///xx/yy/zz.html#hash'}} />
```
### Solution

Decode the uri or url before convert them into a NSURL.

### Additional Information

* React Native version: [0.43.0]
* Platform: [ iOS]

**Comment by afeiship** [comment]
Maybe you can try this way:

### Webview part:
```jsx
<Webview onLoadStart={this._onLoadStart}  source={{uri: 'file:///xx/yy/zz.html?query'}}/>
```

### Your handler:
```js
_onLoadStart = e => {
  const { webview } = this.refs;
  const webviewParams = {
      user_id:1234,
      data:1234,
      otherData:['123','23']
  };
  webview.injectJavaScript(`window.__PARAMS__ =${JSON.stringify(webviewParams)}`);
}
```

### HTML part(js):
```js
var params = window.__PARAMS__;
```
