### ISSUE TITLE
Enviroment configs

### ISSUE THREAD

**Issue by romanonthego** [facebook/react-native#1351]
Whats the best (or at least reliable) way to have multiple enviroments in application?
most node packages solving this problems relaying on `process.env` which is not accesible :(
at very least we need a way to pass variables from console, right?

**Comment by christopherdro** [comment]
You could use AsyncStorage and separate your keys based on your different environments.

**Comment by ide** [comment]
?dev=true/false in the packager's URL sets __DEV__ to true/false in the JS.

**Comment by romanonthego** [comment]
DEV is good to determine development and production environment, but what if you have multiple production environments (stage, test, a/b testing etc)?

For now we stick with exporting environment variables from xcode via native module constants export. (probably will open source it soon).
But I do think react-native will be better with kind of rails config solution (yml/json config files for environments, selection via command-line arguments). Every app will need this as soon as it's gets out of sandbox so this could be considered "core feature".

**Comment by alejomendoza** [comment]
As a suggestion Environment Variable Configuration should be in the docs, didn't know ?dev=true/false in the packager sets __DEV__ to true/false. Thanks!

**Comment by sghiassy** [comment]
+1 for the docs - didn't know that little trick either. Thx

**Comment by kirakik** [comment]
@romanonthego We are currently trying to deal with that issue, did you ever find a more practical way to pass environment variables?
