### ISSUE TITLE
[iOS]pod install error:[!] Unable to find a specification for `Yoga (= 0.43.3.React)` depended upon by `React/Core`

### ISSUE THREAD

**Issue by firetheworld** [facebook/react-native#13526]
Hi,I'm integrate React Native into my application,and I have problem in the step pod install with error Information below:
[!] Unable to find a specification for `Yoga (= 0.43.3.React)` depended upon by `React/Core`

Here is my Podfile
`target 'testRN' do

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTWebSocket',
  ]
  
  use_frameworks!

end
`

I have already npm install , and here is my package.json
`{
	"name": "testRN",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"start": "node node_modules/react-native/local-cli/cli.js start",
		"test": "jest"
	},
	"dependencies": {
		"react": "16.0.0-alpha.6",
		"react-native": "0.43.3"
	},
	"devDependencies": {
		"babel-jest": "19.0.0",
		"babel-preset-react-native": "1.9.1",
		"jest": "19.0.2",
		"react-test-renderer": "16.0.0-alpha.6"
	},
	"jest": {
		"preset": "react-native"
	}
}`

**Comment by Nathan-Smith** [comment]
You need to add Yoga to your Podfile
`pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'`

**Comment by firetheworld** [comment]
Hi, thanks,problem sovled!
I miss a commend in podfile cause I read the version 0.3 document,if you are on the version >=0.42 you have to add a line 'pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec''
