### ISSUE TITLE
environment variables on MacOS from "getting started" didn't work for me

### ISSUE THREAD

**Issue by dotbloup** [facebook/react-native#13534]
in https://facebook.github.io/react-native/docs/getting-started.html when choosing Mobile OS: Android and Development OS: MacOS 

I can read the following in ~/.profile:
export ANDROID_HOME=${HOME}/Library/Android/sdk
export PATH=${PATH}:${ANDROID_HOME}/tools
export PATH=${PATH}:${ANDROID_HOME}/platform-tools

However, on my mac Android SDK is located in the Library under my user folder on Mac OS Sierra.

I had to add the following to make it work:
export ANDROID_HOME=/Users/$(whoami)/Library/Android/sdk
export PATH=${PATH}:${ANDROID_HOME}/tools
export PATH=${PATH}:${ANDROID_HOME}/platform-tools

Did android SDK path moved?

**Comment by hramos** [comment]
Shouldn't `{$HOME}` and `/Users/$(whoami)` resolve to the same path on macOS?
