### ISSUE TITLE
ImageStore support on Android?

### ISSUE THREAD

**Issue by jianglinchun** [facebook/react-native#13537]
ImageStore did not support on Android currently. Any plan?

And I found this extension:

https://github.com/seancunningham/react-native-image-store-ext

http://stackoverflow.com/questions/42070207/react-native-crop-image-on-android

**Comment by hey99xx** [comment]
Is this even a real question? Why should anyone open these links if there's a 3p project you want to use? Why do you not fill the template?

**Comment by jianglinchun** [comment]
@hey99xx The question depends on how you think about this. If you want to add pull request to the official source. A lot of work need to do, Right? I don't have so much time recently. None of the official document had mentioned ImageStore didn't support android. right? Your option is valuable.
