### ISSUE TITLE
TouchableOpacity only supports a single child

### ISSUE THREAD

**Issue by pwmckenna** [facebook/react-native#1354]
the following code triggers fails an invariant check:
```js
            <TouchableOpacity>
                <Text>hi</Text>
                <Text>hi</Text>
            </TouchableOpacity>
```

![screen shot 2015-05-20 at 12 14 50 pm](https://cloud.githubusercontent.com/assets/295678/7734303/df85f92c-fee9-11e4-8820-0564190e2cc7.png)
![screen shot 2015-05-20 at 12 15 00 pm](https://cloud.githubusercontent.com/assets/295678/7734304/df975ad2-fee9-11e4-897f-08f2593e276a.png)

**Comment by pwmckenna** [comment]
this may just be documentation error, so if this is expected I can make a PR for the doc update.

**Comment by MossP** [comment]
Probably is a docs error. In the meantime you can wrap the inner elements in a view. I *believe* that the opacity is applied to that single child rather than cycling though each sub child element.

**Comment by brentvatne** [comment]
@pwmckenna - is there somewhere in the documentation where it's mentioned that you can use multiple children? If so, we should definitely fix that :smile:

**Comment by pwmckenna** [comment]
@brentvatne it doesn't say either way, but its pretty adamant about only using one in practice. I'm not sure how the styling is applied if you wrap everything in a `View` as @MossP suggests.

**Comment by ide** [comment]
+1 to updating the docs

**Comment by brentvatne** [comment]
@pwmckenna - haha good point, do you have time to put together a PR that updates the docs to indicate this?

**Comment by pwmckenna** [comment]
sure, i'll give it a go. I've been meaning to take a peak at that other doc issue as well. I'll see if I can't do both while I'm in there.
