### ISSUE TITLE
Where is the ImageEditor cropped file on Android?

### ISSUE THREAD

**Issue by PARAGJYOTI** [facebook/react-native#13559]
As far as I know , ImageStore is not implemented on android , but when I crop an image by ImageEditor.cropImage()  it saves the Image somewhere like this 
```
file:///data/user/0/com.shopfort/cache/ReactNative_cropped_image_1980504058.jpg
```
 And the uri is valid also as the image is displayed for it . But when I look for the image manually on cache folder on my device , I can't find it there . Where is it actually stored and as react-native documentation says it's important to remove the image from ImageStore , is  it still applies to android ? 

### UPDATE

 However I could find the file by react-native-fs and was able to unlink (delete) the file using RNFS.unlink() .
But will this approach going to clear the memory ?

**Comment by charpeni** [comment]
@facebook-github-bot stack-overflow

**Comment by LEEY19** [comment]
@PARAGJYOTI you manage to get the cropped image path? I am working on it on android but no matter what I do the successURI is just null despite no error being thrown.

**Comment by PARAGJYOTI** [comment]
Hey @LEE19 , yes I managed it . Can you show me your code snippet?

**Comment by LEEY19** [comment]
crop() {
var cropData = {
  offset: {
    x: width * 0.25,
    y: height * 0.45,
  },
  size: {
    width: width * 0.5,
    height: height * 0.1,
  },
}
    ImageEditor.cropImage(
      this.state.path,
      cropData,
      (croppedImageURI) => {
        this.setState({croppedImageURI: croppedImageURI});
        console.log("succes");
      },
      (cropError) => {
        this.setState({cropError: cropError});
        console.log("fail");
      }
    );
}

thank you for your help

**Comment by PARAGJYOTI** [comment]
Seems everything good 
But is that a remote image url? If it is it can be null due to remote url . And as far as I remember , uri is returned as a data object  like {data: 'file:///someurl' } . Try logging the uri or failures .

**Comment by LEEY19** [comment]
@PARAGJYOTI problem is that, even the console.logs are not being fired, it means that neither the success or failure callback functions were being called.

**Comment by LEEY19** [comment]
@PARAGJYOTI must i import ImageStore as well?

**Comment by jbaek7023** [comment]
Did you fix the issue? I'm on the same problem
