### ISSUE TITLE
Android's "singleTask" launch mode as described by the docs does not work.

### ISSUE THREAD

**Issue by LoganBresnahan** [facebook/react-native#13564]
### Description

When attempting to open my app with an Android intent filter from the system browser with a redirect URI, a new instance of the app is opened in the system browser. I have attempted having both:

`android:launchMode="singleTask"` and `android:launchMode="singleInstance"` in my AndroidManifest.xml

![gif](https://media.giphy.com/media/AchFc2ZEQWvMQ/giphy.gif)

In this gif you can see the new instance logged in the console on the right and the instance being rendered in the system browser on this Pixel Simulator (Android 6.0 API 23)

### Reproduction Steps and Sample Code

This example app: https://github.com/LoganBresnahan/Sample-App-React-Native-Android-Intent-Issue

Created this simple app to describe this problem. The flow includes clicking on a button component that uses `Linking.openURL()` to open the link in the system browser. This example specifically uses the Meetup API [https://www.meetup.com/meetup_api/](https://www.meetup.com/meetup_api/) which uses the redirect uri provided in the request to open the sample app.

Linking code:
```javascript
handlePress() {
    Linking.openURL(`https://secure.meetup.com/oauth2/authorize?client_id=${YOUR_API_KEY}&response_type=token&redirect_uri=sampleapp://com.sampleapp`)
 }
```

AndroidManifest:
```xml
  <application
      android:name=".MainApplication"
      android:launchMode="singleTask"
      android:allowBackup="true"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
        <intent-filter>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT"/>
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="sampleapp" />
            <data android:host="com.sampleapp" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
  </application>
```

### Solution

I don't know how to fix the desired functionality but the docs should probably be updated to remove the instructions for using singleTask. [https://facebook.github.io/react-native/docs/linking.html](https://facebook.github.io/react-native/docs/linking.html)

### Additional Information

* React Native version: 0.43.3
* Platform: Android
* Development Operating System: MacOS Sierra 10.12.4
* Dev tools: Android Studio: 2.3, Android SDK: 23

**Comment by carlobambo** [comment]
Try putting `android:launchMode="singleTask"` in activity not on application

**Comment by LoganBresnahan** [comment]
That one is on me. Thanks @carlobambo for pointing that out. The docs clearly show singleTask under MainActivity and not MainApplication. Also, thanks React Native team for this awesome project.
