### ISSUE TITLE
[0.44] Commits to cherry pick into 0.44-stable

### ISSUE THREAD

**Issue by ide** [facebook/react-native#13570]
I cherry picked a couple of commits that guard against errors and one that fixes a CLI bug on Windows. Any other bug fixes or stability improvements that should go in?

**Comment by grabbou** [comment]
Nothing that I have heard of yet. I guess we can release a new release candidate (let me know if you want to do it).

**Comment by ide** [comment]
Think we don't need another RC (but the commits are safe to go out if there's a more important commit for which we want an RC).

**Comment by kesha-antonov** [comment]
Hey guys!

I really need this: https://github.com/facebook/react-native/pull/13715
Support of Videos in Android CameraRoll

**Comment by grabbou** [comment]
It's not yet merged and it's more a feature so I am thinking it will land into 0.45-rc. Going to close this issue now as I am getting into releasing new version.
