### ISSUE TITLE
RCTHTTPRequestHandler sendRequest:withDelegate crash

### ISSUE THREAD

**Issue by IlyaRepo** [facebook/react-native#13587]
### Description

Experienced the following crash:

Crash log snippet
Exception Type: SIGSEGV
Exception Codes: SEGV_MAPERR at 0xebb13beb8
Crashed Thread: 20
Thread 20 Crashed:
0 libobjc.A.dylib 0x00000001818fef70 objc_msgSend + 16
1 CFNetwork 0x0000000183702a60 -[__NSCFURLSessionTask initWithOriginalRequest:updatedRequest:ident:session:] + 276
2 CFNetwork 0x00000001834cd940 -[__NSCFLocalSessionTask initWithOriginalRequest:updatedRequest:ident:session:] + 128
3 CFNetwork 0x00000001834b70c4 -[__NSURLSessionLocal taskForClass:request:uploadFile:bodyData:completion:] + 220
4 MyApp 0x000000010018da24 -[RCTHTTPRequestHandler sendRequest:withDelegate:] (RCTHTTPRequestHandler.m:73)
5 MyApp 0x0000000100187030 -[RCTNetworkTask start] (RCTNetworkTask.m:70)
6 MyApp 0x000000010018bd50 -[RCTNetworking sendRequest:responseType:incrementalUpdates:responseSender:] (RCTNetworking.mm:470)
7 MyApp 0x000000010018d0d0 __44-[RCTNetworking sendRequest:responseSender:]_block_invoke (RCTNetworking.mm:504)
8 libdispatch.dylib 0x0000000181d3e1fc _dispatch_call_block_and_release + 24
9 libdispatch.dylib 0x0000000181d3e1bc _dispatch_client_callout + 16
10 libdispatch.dylib 0x0000000181d4c3dc _dispatch_queue_serial_drain + 928
11 libdispatch.dylib 0x0000000181d419a4 _dispatch_queue_invoke + 652
12 libdispatch.dylib 0x0000000181d4c8d8 _dispatch_queue_override_invoke + 360
13 libdispatch.dylib 0x0000000181d4e34c _dispatch_root_queue_drain + 572
14 libdispatch.dylib 0x0000000181d4e0ac _dispatch_worker_thread3 + 124
15 libsystem_pthread.dylib 0x0000000181f472a0 _pthread_wqthread + 1288
16 libsystem_pthread.dylib 0x0000000181f46d8c start_wqthread + 4

### Reproduction Steps and Sample Code

Unable to reproduce.

### Additional Information

* React Native version: 0.34
* Platform: iOS
* Development Operating System: Mac
* Dev tools: Xcode

**Comment by hramos** [comment]
This is an old RN version and there's not much to follow up on. Closing but feel free to resubmit if you have additional repro details.
