### ISSUE TITLE
Android Kit Kat version 4.4.4 Crashes on App Launch

### ISSUE THREAD

**Issue by larryranches** [facebook/react-native#13589]
### Description

```react-native run-android``` or installing a official release .apk crashes when the app loads. It does work for android version 5.0 and greater

### Errors are below

```Could not run adb reverse: Command failed: /usr/local/opt/android-sdk/platform-tools/adb -s TA431097MJ reverse tcp:8081 tcp:8081```

```
Unable to install /Users/username/stardust-app/android/app/build/outputs/apk/app-release.apk
com.android.ddmlib.InstallException: INSTALL_PARSE_FAILED_INCONSISTENT_CERTIFICATES
```

### Additional Information

* React Native version: 0.42
* Platform: Android 4.4.4 (KitKat)
* Development Operating System: 
* Dev tools: Android sdk 23

**Comment by CodeXtinction** [comment]
maybe you are using touchableNativeFeedback with ripple effect that will crash your app under android 5.0

**Comment by MichaelPintos** [comment]
Adb is not supported by versions of android less than 5. # solution:##  with your app open press on the button menu of your device, dev settings, Debug server host & port for device, enter the ip of your pc and port 8081 ex: 192.168.1.1:8081

**Comment by gengjiawen** [comment]
The error info is very clear, this is not crash. The log indicate in install the apk failed. It's likely that the phone has previously installed the same app, but the signature is different. You can resolve this by simply uninstall the old app.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/android-kit-kat-version-444-crashes-on-app-launch
