### ISSUE TITLE
Illegal callback invocation from native module error

### ISSUE THREAD

**Issue by gavinyeah** [facebook/react-native#13595]
### Description

After upgraded to 0.41, many modules don't work and get this error:

```
java.lang.RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
at com.facebook.react.bridge.CallbackImpl.invoke(CallbackImpl.java:32)
```

I think it's caused by this change in react-native which limits the callback to be invoked for only once:

[Fail-Fast on Redundant Java Callback Invocations ](https://github.com/facebook/react-native/commit/e64618374b2e23ddd0ec91b777c2677c19ac5de3)

```
  @Override
  public void invoke(Object... args) {
+    if (mInvoked) {
+      throw new RuntimeException("Illegal callback invocation from native "+
+        "module. This callback type only permits a single invocation from "+
+        "native code.");
+    }
    mCatalystInstance.invokeCallback(mExecutorToken, mCallbackId, Arguments.fromJavaArgs(args));
+    mInvoked = true;
  }
```

However, many modules would expect their callbacks to be invoked more than once. E.g. react-native-dialogs which shows native dialogs for Android. And on the dialog, we will probably invoke the callback for multiple times, e.g. select an option, press ok will both invoke the callback with different args.

Have we considered that sometimes we do need multiple callback invocations?

**Comment by dobrienlzd** [comment]
This appears to be the same issue as https://github.com/facebook/react-native/issues/12729.  What's the answer guys?

**Comment by dobrienlzd** [comment]
Ok, here is the answer for now:  Whenever you invoke a callback from the javascript side reset the callback:

  setInvokeCallback(){
    MyModule.setTheCallback((suggestions) => {
           this.setState({  suggestions: suggestions });
     });
     MyModule.bar();   // the method within the module that will invoke the callback.
  }

**Comment by dbertella** [comment]
@gavinyeah did you find any solution on this? I have the same problem on a single options dialog. The second time I try to select an option the app crash. Is this work around from @dobrienlzd working with the `react-native-dialogs` lib? If it's so I can't figure out how.

**Comment by tiaanduplessis** [comment]
Facing the same issue

**Comment by agrass** [comment]
I'm with this issue also

**Comment by pwcremin** [comment]
Instead of using callbacks, use events with RCTEventEmitter

Example below using swift.  I left out the .m since it isn't relevant to event emitting with swift

Full project: https://github.com/pwcremin/rn-bluemix-boilerplate

.swift
```swift
@objc(RNSpeechToText)
class RNSpeechToText: RCTEventEmitter {
  
  var speechToText: SpeechToText?
  var audioPlayer = AVAudioPlayer()
  var callback: RCTResponseSenderBlock?
  var hasListeners = false
  
  static let sharedInstance = RNSpeechToText()
  
  private override init() {}
  
  override func supportedEvents() -> [String]! {
    return ["StreamingText"]
  }
  
  @objc func initialize(_ username: String, password: String) -> Void {
    speechToText = SpeechToText(username: username, password: password)
  }
  
  @objc func startStreaming(_ errorCallback: @escaping RCTResponseSenderBlock) {
    
    var settings = RecognitionSettings(contentType: .opus)
    settings.interimResults = true
    
    let failure = { (error: Error) in errorCallback([error]) }
    
    speechToText?.recognizeMicrophone(settings: settings, failure: failure) { results in
      if(self.hasListeners)
      {
        self.sendEvent(withName: "StreamingText", body: results.bestTranscript)
      }
    }
  }
  
  @objc func stopStreaming() {
    speechToText?.stopRecognizeMicrophone()
  }
  
  override func startObserving()
  {
    hasListeners = true
  }
  
  override func stopObserving()
  {
    hasListeners = false
  }
}
```

.js
```javascript
import { NativeEventEmitter, NativeModules } from 'react-native';

let {
    RNTextToSpeech,
    RNSpeechToText
} = NativeModules

module.exports = {
SpeechToText: {
        speechToTextEmitter: new NativeEventEmitter(RNSpeechToText),

        initialize: function ( username, password )
        {
            RNSpeechToText.initialize( username, password );
        },

        startStreaming(callback)
        {
            this.subscription = this.speechToTextEmitter.addListener(
                'StreamingText',
                (text) => callback(null, text)
            );

            RNSpeechToText.startStreaming(callback)
        },

        stopStreaming()
        {
            this.subscription.remove()

            RNSpeechToText.stopStreaming()
        }
    }
}
```

**Comment by digitaldavenyc** [comment]
@pwcremin I tried following this method to fix this issue and having some serious issues getting `NativeEventEmitter` to work

Our events are not being registered and are receiving this error message in xcode: `'TestEvent' is not a supported event type for RCTEventEmitter. Supported events are: '(null)'`

We have reviewed the documentation on how to implement a NativeEventEmitter and I believe we are following it pretty closely. The problem I think is with Objective-C and how we are including our `EventManager` class, the JavaScript side of this is really simple.

`// SpotifyLoginViewController.m`

    #import "SpotifyLoginViewController.h"
    #import "AppDelegate.h"
    #import "SpotifyAuth.h"

    @interface SpotifyLoginViewController () <WKNavigationDelegate>
    @property (strong, nonatomic) WKWebView *webView;
    @property(nonatomic) NSURL *login;

    @end

    @implementation SpotifyLoginViewController

    - (void)viewDidLoad {
        [super viewDidLoad];
        WKWebViewConfiguration *configuration = [[WKWebViewConfiguration alloc] init];
        _webView = [[WKWebView alloc] initWithFrame:self.view.frame
                                    configuration:configuration];
        _webView.navigationDelegate = self;
        _webView.allowsBackForwardNavigationGestures = true;
        [[NSURLCache sharedURLCache] removeAllCachedResponses];
                                                                                             
        [_webView loadRequest:[NSURLRequest requestWithURL:_login]];
        self.view = _webView;
      
    }

    - (void)webView:(WKWebView *)webView decidePolicyForNavigationAction:(WKNavigationAction *)navigationAction decisionHandler:(void (^)(WKNavigationActionPolicy))decisionHandler {
          id<RCTBridgeDelegate> module = [[EventManager alloc] init];
          RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:module launchOptions:nil];
          
          SpotifyAuth *sharedManager = [SpotifyAuth sharedManager];
          NSURL *url = navigationAction.request.URL;
          NSString *myScheme = [[sharedManager myScheme] stringByReplacingOccurrencesOfString:@"://callback" withString:@""];
          if ([url.scheme isEqualToString:myScheme]) {
            
            RCTEventEmitter *event = [[RCTEventEmitter alloc] init];
            event.bridge = bridge;
            [event sendEventWithName:@"TestEvent" body:@{@"name":@"metallica"}];
            
            decisionHandler(WKNavigationActionPolicyCancel);
            return;
          }
          decisionHandler(WKNavigationActionPolicyAllow);
        }

`// EventManager.h`

    #import <React/RCTBridgeModule.h>
    #import <React/RCTEventEmitter.h>


    @interface EventManager : RCTEventEmitter <RCTBridgeModule>

    - (NSURL*)sourceURLForBridge:(RCTBridge*)bridge;

    @end

`//  EventManager.m`

    #import "EventManager.h"
    #import <React/RCTBundleURLProvider.h>

    @implementation EventManager

    RCT_EXPORT_MODULE();

    - (NSArray<NSString *> *)supportedEvents {
      return @[@"TestEvent"];
    }

    - (NSURL*)sourceURLForBridge:(RCTBridge*)bridge {
      NSURL *jsCodeLocation;
      jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];
      return jsCodeLocation;  // [NSURL URLWithString:@"http://localhost:8081/index.ios.bundle?platform=ios"];
    }

    @end

`// player.js`

    import { NativeModules, NativeEventEmitter } from 'react-native';
    const eventManager = new NativeEventEmitter(NativeModules.EventManager);
    
    subscription = eventManager.addListener('TestEvent', (data) => {
      console.log('the event fired!');
      console.log(data);
    });


We are using RN `0.44.0`

**Comment by leoacevedo** [comment]
Hi there, still happening on 0.52.1.

As says in [the docs](http://facebook.github.io/react-native/docs/native-modules-android.html):
> A native module is supposed to invoke its callback only once. It can, however, store the callback and invoke it later.
