### ISSUE TITLE
[FlatList] scrollToIndex will scroll over bottom

### ISSUE THREAD

**Issue by beiming** [facebook/react-native#13594]
I use FlatList to do something like mobile contacts, click alphabet index to jump first item start with alphabet. 

But when I use `scrollToIndex` jump to `Z` it will scroll over bottom, see below picture.

`
this.flatList.scrollToIndex({animated: false, index: itemIndex, viewPosition: 0});
`

![1](https://cloud.githubusercontent.com/assets/1221523/25221556/14c96f5c-25e8-11e7-9bc5-e0093c115cd1.jpeg)

When I focus `FlatList` again, it will scroll to right position. see below picture.

![2](https://cloud.githubusercontent.com/assets/1221523/25221557/14d73380-25e8-11e7-8eb3-751e6101ca0a.jpeg)

It has any option to control `scrollToIndex` not scroll over bottom?  thanks.

# Additional Information
- React Native version: 0.43.3
- Platform: iOS 10.3
- Development Operating System: macOS Sierra 10.12.4

**Comment by rayliao** [comment]
Same problem, Did you find some solutions yet?

**Comment by dotcink** [comment]
Same problem, only for iOS.

**Comment by wj495175289** [comment]
Same problem, only for iOS.

**Comment by lbrdn** [comment]
Anyone found a solution for this ?

**Comment by sauceypan** [comment]
Anyone have a good solution for this?
