### ISSUE TITLE
[FlatList] docs (props) are incomplete

### ISSUE THREAD

**Issue by josvos** [facebook/react-native#13596]
FlatList appears to accept the ListView props pageSize and initialNumToRender, but these props (and maybe others?) are missing in the documentation.

**Comment by irrigator** [comment]
[VirtualizedList](http://facebook.github.io/react-native/releases/0.43/docs/virtualizedlist.html) is the base for both FlatList and SectionList.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/flatlist-docs-props-are-incomplete
