### ISSUE TITLE
[Android] not all images are shown

### ISSUE THREAD

**Issue by sergey-akhalkov** [facebook/react-native#13600]
Hey guys,

### Description

I've created sample app, that should show 100 images.
**Actual**: App randomly shows around 50% of the images. [example1](https://cloud.githubusercontent.com/assets/4928157/25230848/35741e8c-25de-11e7-88ba-abbe2bf2dd00.png), [example2](https://cloud.githubusercontent.com/assets/4928157/25230791/03b8de64-25de-11e7-9e69-3189b756a3b4.png)
**Expected**: All 100 images should be shown.

### Reproduction Steps and Sample Code

***Download the app where the issues reproduces: [rnapp.zip](https://github.com/facebook/react-native/files/943070/rnapp.zip)***

**Repro steps**:
1. Perform `react-native init rnapp` command.
2. Add 100 images in the `./images` folder
3. Change `index.android.js` file like this:
```jsx
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Image,
  View
} from 'react-native';

export default class rnapp extends Component {
  render() {
    return (
      <View style={styles.container}>
        <View style={{ flexDirection: 'row', flexWrap: 'wrap' }}>
          <Image style={styles.image} resizeMode={Image.resizeMode.contain} source={require("./images/laptop_phone_howitworks.1.png")}/>
          ...
          <Image style={styles.image} resizeMode={Image.resizeMode.contain} source={require("./images/laptop_phone_howitworks.100.png")}/>
        </View>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  image: {
    width: 25,
    height: 25,
    margin: 3,
  }
});

AppRegistry.registerComponent('rnapp', () => rnapp);
```

### Additional Information

* React Native version: 0.43.3
* Platform: Android
* Development Operating System: Windows
* Dev tools: Android Studio version 2.3.1, Android SDK version 23

**Comment by nihgwu** [comment]
That's a known bug for quit a long time
#7408 #9581 #10470 I believe they are related
This would be a better choice, https://github.com/facebook/react-native/issues/9581#issuecomment-287945948

**Comment by sergey-akhalkov** [comment]
Hi @nihgwu, thanks for the clarification. Do I get it right that the root cause of this issues is a memory problem? As of now, I've found a workaround that fixes the issue: add android:largeHeap="true" to AndroidManifest.xml

**Comment by jcampalo** [comment]
@sergey-akhalkov Thanks it worked for me

**Comment by surmerming** [comment]
@sergey-akhalkov I tried as your method,  but it does not help

**Comment by pepavesely** [comment]
I see `android:largeHeap="true"` as an accepted solution very often but this is not the right solution. You just enlarge the heap (if the target device has an ability to do so) which means that your application might work longer but might fail eventually anyway.

**Comment by treemore** [comment]
@pepavesely   that is right . before  i set   android:largeHeap="true"  ,the image will not show when i get 50 records. but after i set it , i can only show 200 records.
use ListView and set renderItem  use an Image ,when every Image uri different ,the problem will be come.
if use FlatList  ,Image will be show right .but FlatList has a delay problem..
https://github.com/facebook/react-native/issues/12884

**Comment by treemore** [comment]
every renderItem has a different Image uri .
if all the image has the same uri will work well.

**Comment by pepavesely** [comment]
For me, [https://github.com/facebook/react-native/issues/10569](https://github.com/facebook/react-native/issues/10569) worked very well. I'm using ScrollViews and setting `removeClippedSubviews={true}` solved my issue.

**Comment by treemore** [comment]
@pepavesely . very thank you.

**Comment by appsthatmatter** [comment]
It's also worth mention that with the property `resizeMethod="resize"` I was able to display large images, even though I don't resize the image.

**Comment by subhajitmondalglb** [comment]
Check the solution
https://stackoverflow.com/questions/45736887/react-native-images-are-not-getting-rendered/45751391#45751391

**Comment by adielhercules** [comment]
I am having this issue, images are shown (local & remote) on iOS but not in Android

**Comment by iamtekeste** [comment]
I am facing this issue too, not all images render inside my FlatList. Is this related to memory issue? My images are large in size.

**Comment by itneste** [comment]
that maybe useful:
Image: resizeMethod="resize"
FlatList: removeClippedSubviews={true} scrollEventThrottle={16}

**Comment by adielhercules** [comment]
@itneste totally correct, I am using the `resizeMethod="resize"` over `Image` and it just works, I did not have to add any other props in my case.

Thanks for the suggestion.

I just realized that we can find these props in the react-native documentation. If it helps anyone else [here is the link](https://facebook.github.io/react-native/docs/image.html#resizemethod). And for further information, if you are wondering why these tree options in the `resizeMethod` prop, [here is the documentation of the lib](http://frescolib.org/docs/resizing.html) (fresco) that is used by react-native under the hood.

**Comment by iamtekeste** [comment]
Adding `removeClippedSubviews={true}` to my `FlatList` solved it for me.
Thanks everyone!

**Comment by pacozaa** [comment]
@sergey-akhalkov Problem solved! Thank you ;)

**Comment by pacozaa** [comment]
`android:largeHeap="true"` only works for `android 7.0` but not `android 5.0`

**Comment by MultiformMusic** [comment]
removeClippedSubviews={true}  works for me on android and ios, good !!

**Comment by fatfatson** [comment]
I want to know what's the size of image cache ? can we set it manually ?
I try to load 30 2500x1500 pics at the same time,  the memory cost should be 2500x1500x4x30=450MB,  my tablet device has 4G ram, it's enough for holding them on, but I couldn't display all the pics correctly, some are randomly empty.

**Comment by fatfatson** [comment]
I have found the reason: it's due to RN ImageView's backend `fresco`
it has a cache pool for decoded bitmap, whose default size is calculated by the available runtime memory:
![image](https://user-images.githubusercontent.com/5842874/37030124-b8c2d444-2174-11e8-963b-b9c86060fac5.png)

when the pool is exhausted, it will throw a `PoolSizeViolationException` exception:
![image](https://user-images.githubusercontent.com/5842874/37030334-921b1d5a-2175-11e8-8736-5be0cc4ff777.png)


but RN don't process this well(just ignored):
![image](https://user-images.githubusercontent.com/5842874/37030301-7204f25c-2175-11e8-989c-3005087cb3b3.png)


so we may set a bigger pool size when initializing fresco in `com.facebook.react.modules.fresco.FrescoModule#initialize`

**Comment by shubhi15** [comment]
Changing windowsize property of flatlist (VirtualizedList)  to {5} worked for me.

**Comment by okboy5555** [comment]
我在ios能够显示图片，安卓7.1版本以前能够显示，7.1之后版本大部分图片不能显示

**Comment by asadallahi** [comment]
I found the solution myself.
It was _very easy_. Just **load a child component** instead of rendering in a `rowRenderer`.

```
render() {
    return (
            <View style={{flex: 1}}>
                <RecyclerListView
                    ref="memories_ref"
                    forceNonDeterministicRendering={true}
                    layoutProvider={this._layoutProvider}
                    dataProvider={this.state.dataProvider}
                    rowRenderer={this.renderMemories.bind(this)}
                    renderAheadOffset={50}
                />
            </View>
        );

}
```

and in rowRenderer:
```
renderMemories(type, item) {
    return (<Memory liked={liked} item={item}/>);
}
```

I've also answered this question here: 
https://stackoverflow.com/a/50085668/1670669
