### ISSUE TITLE
RCTRenderingPerf does not expose ReactPerf.printExclusive()

### ISSUE THREAD

**Issue by beeglebug** [facebook/react-native#13608]
### Description

When calling `RCTRenderingPerf.stop`, we automatically get the output from `ReactPerf.printInclusive()` and `ReactPerf.printWasted()`, but have no way of getting `ReactPerf.printExclusive()`, as it is not exposed by the module.

### Reproduction Steps and Sample Code

The following code will trigger the output from `printInclusive` and `printWasted`:

```
import PerfMonitor from 'react-native/Libraries/Performance/RCTRenderingPerf'

PerfMonitor.toggle()
PerfMonitor.start()
setTimeout(() => {
    PerfMonitor.stop()
}, 1000)
```

### Solution

Expose the output functions to be called directly instead of automatically calling some inside stop.

```
import PerfMonitor from 'react-native/Libraries/Performance/RCTRenderingPerf'

PerfMonitor.toggle()
PerfMonitor.start()
setTimeout(() => {
    PerfMonitor.stop()
    PerfMonitor.printExclusive()
    PerfMonitor.printInclusive()
    PerfMonitor.printWasted()
}, 1000)
```

I am happy to do a merge request for this.

### Additional Information

* React Native version: 0.43.3

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/rctrenderingperf-does-not-expose-reactperfprintexclusive
