### ISSUE TITLE
[Android] ImageEditor.cropImage() returns invalid path

### ISSUE THREAD

**Issue by kievu** [facebook/react-native#13612]
### Description

I wanted to crop an image given cropData and a path to an image using https://facebook.github.io/react-native/docs/imageeditor.html

This is done both on iOS and Android. On iOS everything works like it should do. It return a valid path to the cropped image. On Android, the cropImage callback return a weird path every time:

```y + height must be <= bitmap.height()```

This makes me unable to show the image in ```<Image source={path} />```

### Reproduction Steps and Sample Code

```
import React, { Component } from 'react'
import {
  AppRegistry,
  Dimensions,
  Image,
  ImageEditor,
  Text,
  View
} from 'react-native'


const { height, width } = Dimensions.get('window')

const cropData = {
  offset: { x: 0, y: 0 },
  size: { width: width - 100, height: height - 100 }
}

const wholePathToImage = '...'

export default class App extends Component {

  state: {
    path: ?string
  }

  constructor() {
    super()
    this.state = {
      path: null
    }
  }

  componentDidMount() {
    this.crop(wholePathToImage)
  }

  async crop(path: string) {
    ImageEditor.cropImage(
      path, 
      cropData, 
      successURI => this.setState({ path: successURI }), 
      error => console.log(error.message)
    )
  }

  render() {
    if (this.state.path) {
      return (
        <View style={{flex: 1}}>
          <Image source={require(this.state.path)}/>
        </View>
      )
    } else {
      return (
      <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
        <Text>Waiting for image cropping...</Text>
      </View>
      )
    }
  }
}

AppRegistry.registerComponent('app', () => App)
```

### Solution

Return correct path of image for Android

### Additional Information

* React Native version: 0.42.0
* Platform: Android
* Development Operating System: MacOS
* Dev tools: XCode 8.2.1

**Comment by RobertSheaO** [comment]
You've got to use ImageStore.getBase64ForTag(successURI) in your success callback to get what you want.

**Comment by luci1329** [comment]
I'm having the same issue. Did you solve yours?
