### ISSUE TITLE
Contents of a native Android linear layout don't rescale

### ISSUE THREAD

**Issue by jankalfus** [facebook/react-native#13613]
I have created a native linear layout (using `SimpleViewManager`) and inserted it into my RN app. It contains a map and an info panel. The info panel is hidden by default. When a pin in the map is clicked, the panel should display below the map. This works fine in a standard Android app, but not in combination with React Native. The map displays fine, but the info panel is never displayed (even though it's visibility changes from `View.GONE` to `View.VISIBLE` - I've checked this). The component is implemented purely in native code, it is inserted into a RN app using this tutorial: https://facebook.github.io/react-native/docs/native-components-android.html. I'm suspecting the problem is that React Native blocks layout computation/redraw somehow.

Here's a simplified layout of my native component:
```
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
    <FrameLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_weight="1">

        <com.example.MyMapView
            android:id="@+id/map_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />
        <!-- some more stuff -->

    </FrameLayout>

    <LinearLayout
        android:id="@+id/map_details"
        style="@style/bottom_sheet"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical"
        android:visibility="gone">
        
        <!-- contents of the info panel -->
    </LinearLayout>
</LinearLayout>
```

I'm adding a picture to make it easier to understand:
![issue](https://cloud.githubusercontent.com/assets/12714276/25282355/8196876e-26b0-11e7-8a56-c6b06ef84267.png)

Is this a known issue? Are layouts using `layout_weight` not working in combination with RN? Is there a way to somehow unblock the layout recalculation?

* React Native version: 0.41
* Platform: Android
* Development Operating System: Windows
* Dev tools: Android Studio 2.3.1

**Update:**
This solved my problem: http://stackoverflow.com/a/39839405/3979621

**Comment by hramos** [comment]
Should we close this given you've found a solution?

**Comment by jankalfus** [comment]
That's the thing, I don't know. I was already thinking about closing the issue, but this is obviously an issue with React Native. He "solution" is more or less a workaround... I'll leave it up to you.

**Comment by glcrazier** [comment]
In my opinion, React Native takes over the job of layout and measure. So in your case, your native component won't be updated even if you call requestLayout because layout method is nullified in ReactRootView.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/contents-of-a-native-android-linear-layout-dont-rescale
