### ISSUE TITLE
Remove copy tooltip on Text that is not selectable - iOS

### ISSUE THREAD

**Issue by gabrielbull** [facebook/react-native#13618]
### Description

When creating a custom tooltip (could be using [react-native-tooltip](https://github.com/chirag04/react-native-tooltip)), if the custom tooltip is within a Text element, the tooltip will inevitably have the __Copy__ item without any way of removing it.

This is because of the lines [239, 240, 241](https://github.com/facebook/react-native/blame/master/Libraries/Text/RCTText.m#L239) of [react-native/Libraries/Text/RCTText.m](https://github.com/facebook/react-native/blob/master/Libraries/Text/RCTText.m), introduced by @shergin on this commit 5d03ff8035bdb7c582f80d6ce46d7c5f11545e7e .

### Reproduction Steps and Sample Code

Create a custom tooltip inside a `Text` component.

The `Text` component can have the `selectable` property set to `true` or `false`, it does not affect this issue.

```jsx
import * as React from 'react';
import { Text } from 'react-native';
import ToolTip from 'react-native-tooltip';

const MyComponent = () => (
  <Text>
    <Text>This is my text.</Text>
    <ToolTip
      actions={[
        {text: 'My', onPress: (): any => null },
        {text: 'Context', onPress: (): any => null },
        {text: 'Menu', onPress: (): any => null },
      ]}
      underlayColor='transparent'
      longPress={true}
      arrowDirection='down'
    >
      <Text>You can long press me for a tooltip.</Text>
    </ToolTip>
    <Text>This is the rest of my text</Text>
  </Text>
);

export default MyComponent;
```

![capture_d ecran_2017-04-21_a_16_31_27](https://cloud.githubusercontent.com/assets/671923/25295693/9991e69a-26b2-11e7-9761-8de2c3daf587.png)

### Solution

If the `selectable` property on the `Text` component is set to true, the behaviour should remain the same. However, if it set to `false`, the __Copy__ item should not show in the tooltip. 

To fix this, the [following lines](https://github.com/facebook/react-native/blob/master/Libraries/Text/RCTText.m#L239) should be changed to have a condition to only accept the copy item if the text is selectable:

```objc
- (BOOL)canPerformAction:(SEL)action withSender:(id)sender
{
  if (action == @selector(copy:)) {
    return YES;
  }

  return [super canPerformAction:action withSender:sender];
}
```

### Additional Information

* React Native version: 0.43.4
* Platform: iOS
* Development Operating System: MacOS

**Comment by shergin** [comment]
Thank you, Gabriel!
I will fix that.

**Comment by gabrielbull** [comment]
@shergin If you look here, I have submitted a fix: https://github.com/facebook/react-native/pull/13619

**Comment by shergin** [comment]
@gabrielbull Awesome! Please address the comments. :)

**Comment by gabrielbull** [comment]
Fixed with the PR.
