### ISSUE TITLE
[Android] The Style Props: flexGrow, flexShrink and flexBasis prevent Views From Collapsing

### ISSUE THREAD

**Issue by greghe** [facebook/react-native#13622]
### Description

Adding a `flexGrow`, `flexShrink` or `flexBasis` style property to a View on Android prevents it from collapsing.

### Reproduction Steps and Sample Code

Add a flexGrow, flexShrink or flexBasis style property to a View on Android:
```
<View style={{flexGrow: 1}}>
   <View style={{flexGrow: 1}}/>
</View>
```
Notice that nested Views do not collapse.

### Solution

These two flex-related properties are not included in the `LAYOUT_ONLY_PROPS` HashSet defined in `ViewProps.java`. The solution would be to add them. There seems to be no reason they should not be added since `FLEX` is already included in the list.

### Additional Information

* React Native version: 0.43.4
* Platform: Android

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/android-the-style-props-flexgrow-flexshrink-and-flexbasis-prevent-views-from-col
