### ISSUE TITLE
[Android] fetch, xmlhttprequest do not respect caching headers/params

### ISSUE THREAD

**Issue by kappac** [facebook/react-native#13638]
### Description

In our application we need to make a lot of requests to our backend. Requests are different in headers.
On ios everything works fine, all requests are sent to server.
On Android request performs first time fine, but on next try response is with status code 204 without sending request to server. After a few seconds request performs fine again.

### Reproduction Steps and Sample Code

const headers = {
        project_id: project_id,
        language: language,
        authorization: [auth.tokenType, auth.accessToken].join(' '),
        'cache-control': 'no-cache, no-store, must-revalidate',
        // or/and
        pragma: 'no-cache'
    };

axios.request({
            responseType: 'json',
            method: method,
            url: url,
            baseURL: apiConfig.url,
            params: params,
            data: payload,
            headers: headers
        });

The same is true for fetch with the same headers and/or 'cache' parameter set to 'no-cache' or 'no-store'.

### Additional Information

* React Native version: 0.43.3
* Platform: Android
* Development Operating System: MacOS 10.12.4
* Dev tools: Intellij IDEA Ultimate 2017.1, Android SDK - 23.0.1

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/android-fetch-xmlhttprequest-do-not-respect-caching-headersparams
