### ISSUE TITLE
How to implement a mixin animation?

### ISSUE THREAD

**Issue by qingfeng** [facebook/react-native#1363]
AnimationExperimental can only one animation，
```js
    AnimationExperimental.startAnimation({
      node: this.refs.image,
      duration: 400,
      //delay: 10,
      easing: 'easeInOutQuad',
      property: 'position',
      toValue: point,
    },
    () => {
    });
```

For example: I hope that in the process of moving, to change the value of `toValue`

thanks

**Comment by brentvatne** [comment]
@qingfeng - I would strongly advise that you don't use `AnimationExperimental` for now, and instead use something like `react-tween-state` - a better animation api is in the works. See [this project](https://github.com/brentvatne/react-native-modal) for an example of using `react-tween-state` to animate multiple properties.
