### ISSUE TITLE
App process is a steady 130% CPU immediately on launch

### ISSUE THREAD

**Issue by marcshilling** [facebook/react-native#1364]
2012 15" Retina MacBook Pro

Launching my react native app on the iPhone 6 simulator immediately skyrockets the process to 130% CPU. The name of the process matches my app name (I bring this up because the iOS Simulator Process is 0% and XCode is 1%). 

Launching a non-react native app on the same simulator, the process sits at 0.1%.

I'm not experiencing any slowdowns or crashes, it's just annoying that my laptop's fans spin at high speed constantly. Curious what is causing this.

**Comment by brentvatne** [comment]
@marcshilling - is this a brand new project that you created with `react-native init`? If not, we'll probably need to see the code for it to be able to guess at what might be the problem :smile:

**Comment by onlymejosh** [comment]
I'm having the same issues on a brand new Retina MBP. It may be related to #1325

**Comment by jaygarcia** [comment]
When this happens, can you guys fire up instruments and share the data?

I've never run into this, but this is what I'd do if I did. 

JG

@moduscreate

:: sent from my mobile device ::

**Comment by marcshilling** [comment]
@jaygarcia any particular instrument I should be monitoring? Nothing is really standing out other than my app being 130% CPU always like I said

**Comment by jaygarcia** [comment]
Good question @marcshilling :-\

I was hoping maybe there were some signals from the stack display that could help.

I've recorded the following video demonstrating how my mid-2012 MBP displays CPU utilization for the iOS sim.  

http://www.youtube.com/watch?v=91SurUNjkS4

For the record, this app is pushing the limits with React Native's Runloop and I still don't see issues with high CPU utilization like some of you are describing :(.

**Comment by marcshilling** [comment]
I repeated your steps and actually am seeing an even lower React Native Runloop time than you.
![screen shot 2015-05-26 at 3 09 04 pm](https://cloud.githubusercontent.com/assets/5598961/7820908/433a40c6-03b9-11e5-9e21-a1984d8aa781.png)

I do want to clarify - it's not the iOS Simulator process I'm having issues with. That is always around 0% like you show in your video. The process is the actual name of my app.

**Comment by jaygarcia** [comment]
Ah! I See what you mean.  

During idle, i'm < 5% :(

See below.

![cpu](https://cloud.githubusercontent.com/assets/180031/7821475/dceb6724-03bc-11e5-8da1-fb4e09c70f32.gif)



I'll see if i can replicate with a vanilla project. Maybe there's something in there that is acting like a jerk :(

**Comment by brentvatne** [comment]
@marcshilling - any chance you could post a public repo where this issue occurs?

**Comment by brentvatne** [comment]
@marcshilling - I'm going to close this issue for now, if you're still having the issue then ping me with 1) whether this is happening on a plain `react-native init` project 2) if not, somewhere that we can access the source for a project where this occurs
