### ISSUE TITLE
Set Accessibility Label for iOS Unrecognized

### ISSUE THREAD

**Issue by mwalla210** [facebook/react-native#13648]
### Description

React Native application for iOS has accessibility values naturally on text views for application, despite having no settings for this in app. These default to whatever the text view contains.
Android application has no accessibility values for anything (as expected).

Adding a accessible flag and a label in code in pages for an item provides an accessibility label for Android, but makes no changes to presumably "default" labels on iOS. 
Accessibility labels/IDs are verified via both Appium (iOS/Android) and the Accessibility Inspector (iOS).

### Reproduction Steps and Sample Code

Setting the below on a text element 
```
accessible={true} accessibilityLabel={'User\'s Name'}
```
Android's "accessibility ID" from Appium: "User's Name"
iOS's "accessibility ID" from Appium: TASSL TESTER (inner text view content)
iOS's "accessibility value" from Accessibility Inspector: TASSL TESTER
* No label listed

### Additional Information

* React Native version: 0.39.2
* Platform: iOS
* Development Operating System: MacOS
* Dev tools: Xcode 8.0, iOS 10, iPhone 7, Appium 1.0.0, Accessibility Inspector 5.0

**Comment by robcapell** [comment]
@mwalla210 Just a thought - Try putting the accessibility tags on a `<View>`  tag that wraps your text element. The `<Text>` element in iOS may just be funky, and not like the accessibility tags.

**Comment by shergin** [comment]
Does your actual code look like this:
```
<TextInput multiline={true} accessible={true} accessibilityLabel={'User\'s Name'} />
```
?

Could you please provide more full/complete fragment of your code?

**Comment by mwalla210** [comment]
Yes, that is what I've attempted. That's what the code looked like. This has occurred for both `<View>` items and a variety of others.
My current workaround is using `accessible={true} accessibilityLabel={'User\'s Name'} testID={'User\'s Name'}` which does set the "accessibility ID" according to Appium & the "Title" value for the Accessibility Inspector (on Mac).

**Comment by shergin** [comment]
Yeah... My actual question was (should be): Do you experience this problem with many regular `<View>` or only with some specific views, such as multiline `<TextInput>`?

**Comment by mwalla210** [comment]
Many regular views. I don't actually think I've attempted with any multiline <TextInput>s.

**Comment by shergin** [comment]
So, your actual concern is: `accessibility*` just do NOT work on iOS at all? (Or sometimes?)
Could you please provide minimal project or fragment of code which can illustrate the problem?
Could you also please test your code on latest version (or even better on master) of RN?

**Comment by mwalla210** [comment]
Going back to replicate this issue, I am unable to do so and will assume the problem was negligence on my part. Thanks for your assistance.

**Comment by curioustechizen** [comment]
I see a similar issue with `<Text>` on iOS: the actual label of the text always overrides the `testID` and `accessibilityLabel`. So I have no way of retrieving a `<Text>` by accessibilityId.

The repro is very simple: Just edit the default app produced by `react-native init` and edit index.ios.js. Find the "Welcome to React Native" text. Change it to:

```
<Text testID={'welcome'} accessibilityLabel={'welcome'}>Welcome to React Native!</Text>
```

**Expected**: The Accessibility Inspector should say the Label is  `welcome`.
**Actual**: The Accessibility Inspector says the Label is `Welcome to React Native!`.
 
Is this by design? If so, then what is the recommended way of locating a `<Text/>` in end-to-end tests?

_Note:_ - with the same set of properties on Android the `contentDescription` is `welcome` which is what I expect.

**Comment by shergin** [comment]
@curioustechizen No, I believe this is not intentional and wrong. Seems the problem was introduced in e9db0338d27b2d4c11505262d53dc5d26a41fade.
Do you mind create another issue (With something like "accessibilityLabel does not work for <Text>" in title) and assign it to me?
Thank you!

**Comment by curioustechizen** [comment]
@shergin Opened #14123 . I think I don't have the rights to assign it to you though.
