### ISSUE TITLE
New ideas about ListView

### ISSUE THREAD

**Issue by mjt19930301** [facebook/react-native#13647]

**Comment by hramos** [comment]
Can you clarify what your goal is with this issue?

**Comment by mjt19930301** [comment]
@hramos 
I drew a picture, but I'm not sure if I can express my idea clearly through this picture. If you cannot understand it, I will add a video to illustrate further; if you can understand my idea, please try this method and tell me whether it is feasible or not.

![2](https://cloud.githubusercontent.com/assets/22411659/25416571/1001fde4-2a71-11e7-8185-ffbf558de862.png)

**Comment by mjt19930301** [comment]
@hramos 
![qq _20170426034539 mp4_1493149791](https://cloud.githubusercontent.com/assets/22411659/25416806/69ee34e8-2a72-11e7-811e-f5ee6e1b4675.gif)
![qq _20170426030637 mp4_1493149209](https://cloud.githubusercontent.com/assets/22411659/25416840/a08c6178-2a72-11e7-96ce-0b89528bb349.gif)

**Comment by hramos** [comment]
At a glance, this seems like what `VirtualizedList` (and therefore `FlatList`) provides. See https://facebook.github.io/react-native/blog/2017/03/13/better-list-views.html

**Comment by mjt19930301** [comment]
@hramos 

I have tested FlatList, which is not the same as my implementation principle. When the amount of data is very large, even very slow move will lead to JS frame very low-10 or so. However, in my method, no matter how much the data is, the performance is the same-50 or so. Because the number and structure of the total view is unchanged, and the changeable thing is relative to the parent component of the top and inner data, it only need to render a small part each time. If JS only need to use setNativeProps tell Item of its page and the height where it should be, and ios can capture the corresponding data according ton the page, automatically replacing the data into the structure, then both UI and JS should be 60 frames. The following is the code of 5000 data, the performance is unchanged from beginning to the end.



![qq _20170427205033 mp4_1493297774](https://cloud.githubusercontent.com/assets/22411659/25557726/ad736a1a-2d49-11e7-844e-0f0caf381c4a.gif)

`import React, { Component } from 'react';
import {
    AppRegistry,
    StyleSheet,
    Text,
    View,
    ScrollView,
    Dimensions,
    FlatList,
    Image,
    TouchableHighlight
} from 'react-native';
import {observer} from 'mobx-react';
import {observable ,computed } from 'mobx';

const {width,height} = Dimensions.get('window')

class List {
    @observable
    index = 0;
    @observable
    data = [];

    now = 0;
}

const list = new List();

const renderItem = (page) => {
    const data = list.data.slice( page*4, page*4+4 )
    let p = []
    for (let i = 0; i < data.length ; i++){

        p.push(renderRow (i , data[i]))
    }
    return p
}

const renderRow = (i,item) => {
    return<View key={i}  >
        <TouchableHighlight
            style={{height:150}}
            underlayColor = {'#EFEFEF'}
            onPress={this.onPress}
        >
            <View style={{
                marginLeft:10,
                marginRight:10,
                paddingTop:10,
                flexDirection:'row',
                paddingBottom:10,
                borderBottomWidth:1,
                borderBottomColor:'#DFDFDF'
            }}>

                <Image
                    source={{uri:item.goods_img}}
                    style={{height:120,width:80,borderRadius:5}}

                />
                <View style={{flex:1,marginLeft:10 , justifyContent : 'space-between',marginBottom:5
                    ,
                }}>

                    <Text>{item.goods_id}</Text>
                </View>
            </View>
        </TouchableHighlight>
    </View>
}

@observer
class Item0 extends Component {
    h = 600
    num = 0
    page = 0
    data = list.data
    @computed
    get pages () {
        const {now  , index }= list
        if(now === 0){
            const page = index
            this.page = page
            return  this.h  * page
        }
        if(now === 1){
            const page = index - 1
            this.page = page
            return  this.h  * page
        }
        if(now === 2){
            const page = index + 2
            this.page = page
            return  this.h  * page
        }
        if(now === 3){
            const page = index + 1
            this.page = page
            return  this.h  * page
        }
    }
    render() {
        console.log('render :'+this.num)
        return (

            <View

                ref = {a=>this.view = a}
                style={[{
                    position:'absolute',
                    height:this.h,
                    backgroundColor:'white',
                    width:width,
                    top:this.pages


                },this.props.color]}>
                {renderItem(this.page)}
            </View>


        );
    }
}

@observer
class Item1 extends Component {
    h = 600
    num = 1
    page = 1
    data = list.data
    @computed
    get pages () {
        const {now  , index }= list
        if(now === 0){
            const page  = index + 1
            this.page = page
            return  this.h  * page
        }
        if(now === 1){
            const page = index
            this.page = page
            return  this.h  * page
        }
        if(now === 2){
            const page = index - 1
            this.page = page
            return  this.h  * page
        }
        if(now === 3){
            const page = index + 2
            this.page = page
            return  this.h  * page
        }
    }


    render() {
        console.log('render :'+this.num)
        return (

            <View

                ref = {a=>this.view = a}
                style={[{
                    position:'absolute',
                    height:this.h,
                    backgroundColor:'white',
                    width:width,
                    top:this.pages


                },this.props.color]}>
                {renderItem(this.page)}
            </View>


        );
    }
}

@observer
class Item2 extends Component {
    h = 600
    num = 2
    page = 2
    data = list.data
    @computed
    get pages () {
        const {now  , index }= list
        if(now === 0){
            const page = index + 2
            this.page = page
            return  this.h  * page
        }
        if(now === 1){
            const page = index + 1
            this.page = page
            return  this.h  * page
        }
        if(now === 2){
            const page = index
            this.page = page
            return  this.h  * page
        }
        if(now === 3){
            const page = index - 1
            this.page = page
            return  this.h  * page
        }
    }


    render() {
        console.log('render :'+this.num)
        return (

            <View

                ref = {a=>this.view = a}
                style={[{
                    position:'absolute',
                    height:this.h,
                    backgroundColor:'white',
                    width:width,
                    top:this.pages


                },this.props.color]}>
                {renderItem(this.page)}
            </View>


        );
    }
}

@observer
class Item3 extends Component {
    h = 600
    num = 3
    page = 3
    data = list.data
    @computed
    get pages () {
        const {now  , index }= list
        if(now === 0){
            const page = index - 1
            this.page = page
            return  this.h  * page
        }
        if(now === 1){
            const page = index + 2
            this.page = page
            return  this.h  * page
        }
        if(now === 2){
            const page = index + 1
            this.page = page
            return  this.h  * page
        }
        if(now === 3){
            const page = index
            this.page = page
            return  this.h  * page
        }
    }


    render() {
        console.log('render :'+this.num)
        return (

            <View

                ref = {a=>this.view = a}
                style={[{
                    position:'absolute',
                    height:this.h,
                    backgroundColor:'white',
                    width:width,
                    top:this.pages


                },this.props.color]}>
                {renderItem(this.page)}
            </View>


        );
    }
}

@observer
 class ListViewDemo extends Component {




    componentDidMount () {
        this.fetchData()
    }
    offset = 0
    async fetchData () {
        let arr = [];
        for (let i = 0; i < 5001 ; i++){
            arr.push({goods_id:`this is ${i}`})
        }
        list.data = arr

        /*
        try {
            let response = await fetch(`http://192.168.1.101/shop/5`);
            let responseJson = await response.json();
            let a = responseJson;
            console.log(a)
            list.data = a
        } catch(error) {
            console.error(error);
        }
        */
    }

    _onScroll = (e) => {
        const index = Math.floor(e.nativeEvent.contentOffset.y/600)
        list.now = Math.max(0,index%4)
        list.index = Math.max(0,index)

        // console.log([list.index,list.now])
    }
    render() {

        return (
            <View>

                <ScrollView
                    ref = {a=>this.scroll = a}
                    onScroll={this._onScroll}
                    scrollEventThrottle = {1}
                    contentContainerStyle={{
                    }}
                >

                    <View style={{
                        height:200,
                        alignItems:'center',
                        justifyContent:'center',
                        borderBottomWidth:1,
                        borderLeftColor:'red',
                    }}>
                        <Text style={{color:'red',fontSize:30}}>this is header</Text>
                    </View>

                    <View
                        style={{
                            height:150*list.data.length,
                            overflow : 'hidden'
                        }}
                    >
                        <Item0
                            // color = {{backgroundColor:'red'}}
                        />
                        <Item1
                            //  color = {{backgroundColor:'yellow'}}
                        />
                        <Item2
                            // color = {{backgroundColor:'blue'}}
                        />
                        <Item3
                            // color = {{backgroundColor:'green'}}
                        />
                    </View>




                </ScrollView>
            </View>

        );
    }
}

export default ListViewDemo;`


package.json
`{
	"name": "ListViewDemo",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"start": "node node_modules/react-native/local-cli/cli.js start",
		"test": "jest"
	},
	"dependencies": {
		"mobx": "^3.1.9",
		"mobx-react": "^4.1.8",
		"react": "16.0.0-alpha.6",
		"react-native": "0.43.4"
	},
	"devDependencies": {
		"babel-jest": "19.0.0",
		"babel-preset-react-native": "1.9.1",
		"babel-plugin-syntax-decorators": "^6.13.0",
		"babel-plugin-transform-decorators-legacy": "^1.3.4",
		"jest": "19.0.2",
		"react-test-renderer": "16.0.0-alpha.6"
	},
	"jest": {
		"preset": "react-native"
	}
}`


.babelrc
`{
"presets": ["react-native"],
  "plugins": [
    "syntax-decorators",
    "transform-decorators-legacy"
  ]
}`
