### ISSUE TITLE
My app crashed in Android emulator 7.0

### ISSUE THREAD

**Issue by xubuhang** [facebook/react-native#13668]
### Description

1.Explain what you did
My project is a standard React Native project created using react-native init.
, then I used react-native run-android.
2.What you expected to happen
Android emulator should display normal view.

3.What actually happens
However,My app crashed。(but my real phone is ok)

react-native 0.43
react 16.0.0-alpha.6
Android emulator android 7.0
Real phone android 5.1.1
### Reproduction Steps and Sample Code
`04-26 11:27:13.022 7991-7991/? I/art: Not late-enabling -Xcheck:jni (already on)
04-26 11:27:13.023 7991-7991/com.tjhms W/art: Unexpected CPU variant for X86 using defaults: x86
04-26 11:27:13.207 7991-7991/com.tjhms V/fb-UnpackingSoSource: locked dso store /data/user/0/com.tjhms/lib-main
04-26 11:27:13.221 7991-7991/com.tjhms I/fb-UnpackingSoSource: dso store is up-to-date: /data/user/0/com.tjhms/lib-main
04-26 11:27:13.221 7991-7991/com.tjhms V/fb-UnpackingSoSource: releasing dso store lock for /data/user/0/com.tjhms/lib-main
04-26 11:27:13.277 7991-7991/com.tjhms D/NetworkSecurityConfig: No Network Security Config specified, using platform default
04-26 11:27:13.800 7991-8017/com.tjhms I/OpenGLRenderer: Initialized EGL, version 1.4
04-26 11:27:13.800 7991-8017/com.tjhms D/OpenGLRenderer: Swap behavior 1
04-26 11:27:13.801 7991-8017/com.tjhms W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
04-26 11:27:13.801 7991-8017/com.tjhms D/OpenGLRenderer: Swap behavior 0
04-26 11:27:13.838 7991-8017/com.tjhms E/gralloc_ranchu: gralloc_register_buffer(0xe8a5a3c0): invalid buffer
04-26 11:27:13.838 7991-8017/com.tjhms W/GraphicBufferMapper: registerBuffer(0xe8a5a3c0) failed -22 (Invalid argument)
04-26 11:27:13.838 7991-8017/com.tjhms E/GraphicBuffer: unflatten: registerBuffer failed: Invalid argument (-22)
04-26 11:27:13.838 7991-8017/com.tjhms E/Surface: dequeueBuffer: IGraphicBufferProducer::requestBuffer failed: -22
04-26 11:27:13.838 7991-8017/com.tjhms E/EGL_emulation: tid 8017: init(324): error 0x3003 (EGL_BAD_ALLOC)
04-26 11:27:13.839 7991-8017/com.tjhms E/EGL_emulation: tid 8017: eglCreateWindowSurface(847): error 0x3003 (EGL_BAD_ALLOC)
04-26 11:27:13.843 7991-8017/com.tjhms A/OpenGLRenderer: Failed to create EGLSurface for window 0xdb3d8508, eglErr = EGL_BAD_ALLOC
04-26 11:27:13.846 7991-8017/com.tjhms A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 8017 (RenderThread)
                                               
                                               [ 04-26 11:27:13.847  1259: 1259 W/         ]
                                               debuggerd: handling request: pid=7991 uid=10099 gid=10099 tid=8017`

### Solution

What needs to be done to address this issue? Ideally, provide a pull request with a fix.

### Additional Information

* React Native version: [0.43]
* Platform: [ Android ]
* Development Operating System: [ MacOS?]
* Dev tools: [ Android Studio 2.3,  Android SDK 23]

**Comment by kenma9123** [comment]
I had the same problem it crases on Android 7.0. From a production app. I got this error message on google play console

```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
UUID: 572fa66e-d915-4c84-940f-c97bd2e0a8d7
Build fingerprint: 'Sony/F5122/F5122:7.0/34.2.A.2.47/3005313909:user/release-keys'
Revision: '0'
ABI: 'arm'
pid: 8133, tid: 8150, name: RenderThread  >>> com.kenma.iponchallenge <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: 'Leaked 2 GPU objects!'
    r0 00000000  r1 00001fd6  r2 00000006  r3 00000008
    r4 ee4d7978  r5 00000006  r6 ee4d7920  r7 0000010c
    r8 ee4d7780  r9 00000000  sl efa62344  fp efa62340
    ip 0000000b  sp ee4d7300  lr f05175c7  pc f0519e48  cpsr 20000010

backtrace:
    #00 pc 00049e48  /system/lib/libc.so (tgkill+12)
    #01 pc 000475c3  /system/lib/libc.so (pthread_kill+34)
    #02 pc 0001d7d9  /system/lib/libc.so (raise+10)
    #03 pc 000192d1  /system/lib/libc.so (__libc_android_abort+34)
    #04 pc 00017338  /system/lib/libc.so (abort+4)
    #05 pc 0000c331  /system/lib/libcutils.so (__android_log_assert+112)
    #06 pc 0003b13f  /system/lib/libhwui.so
    #07 pc 00025a33  /system/lib/libhwui.so
    #08 pc 00023ef9  /system/lib/libhwui.so
    #09 pc 000269ed  /system/lib/libhwui.so
    #10 pc 00027287  /system/lib/libhwui.so
    #11 pc 000282c5  /system/lib/libhwui.so (_ZN7android10uirenderer12renderthread12RenderThread10threadLoopEv+80)
    #12 pc 0000e349  /system/lib/libutils.so (_ZN7android6Thread11_threadLoopEPv+140)
    #13 pc 000652a5  /system/lib/libandroid_runtime.so (_ZN7android14AndroidRuntime15javaThreadShellEPv+80)
    #14 pc 00047093  /system/lib/libc.so (_ZL15__pthread_startPv+22)
    #15 pc 00019d49  /system/lib/libc.so (__start_thread+6)
```

I had the same version of react-native, this could  be related. I'm not sure. Android 6.0 works fine tho.

**Comment by kelset** [comment]
I have an app in production and can confirm that Android 7.0 seems to have some issue with React Native, ~60% of our crashes are happening there.

Need to investigate more, this issue seems a good thread to work around it.

**Comment by sohobloo** [comment]
+1 on emulator

**Comment by rgabrielsson** [comment]
+1 on emulator

**Comment by karlachavez** [comment]
+1 on emulator

**Comment by imwangze** [comment]
+1 on emulator

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
