### ISSUE TITLE
rootTag changed when back button pressed

### ISSUE THREAD

**Issue by tomasdelima** [facebook/react-native#13679]
When I open my app for the first time, I get the following message on my logs:

```
Running application "AppName" with appParams: {"initialProps":{},"rootTag":1}.
DEV === true, development-level warning are ON, performance optimizations are OFF
```

But whenever I quit my app with the Back button, I get the following message:

```
Running application "AppName" with appParams: {"initialProps":{},"rootTag":11}.
DEV === true, development-level warning are ON, performance optimizations are OFF
```

Every next time I exit the app with the Back button, the parameter rootTag is increased by 10, so becoming 11, 21, 31, 41, ... This prevents me to change scenes with my navigator through `navigator.push({...})`, as I receive the warning message:

```
Warning: Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component. This is a no-op.
Please check the code for the exports component.
```

This happens even when I have my simplest code, like in `index.android.js`:

```
import React, { Component } from 'react'
import { AppRegistry } from 'react-native'

const MyApp = React.createClass({
  render() {
    return null
  }
})

AppRegistry.registerComponent('MyApp', () => MyApp)
```

React Native version: `0.43.4`
Platform: android
OS: Linux
No dev tools

Any help?
Thanks in advance

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/roottag-changed-when-back-button-pressed

**Comment by kesha-antonov** [comment]
@tomasdelima Hello! Did you find a solution?

**Comment by tomasdelima** [comment]
I just upgraded React Native and had no more trouble, but I dont know if it's solved
