### ISSUE TITLE
Possible syntax error in docs for SectionList

### ISSUE THREAD

**Issue by tandcsurf** [facebook/react-native#13678]
--- Delete everything above this line ---

### Description

Explain what you did, what you expected to happen, and what actually happens:

Trying out new SectionList component, seems like there's syntax error in the docs

https://facebook.github.io/react-native/docs/sectionlist.html

```
<SectionList renderItem={({item}) => <ListItem title={item.title}} renderSectionHeader={({section}) => <H1 title={section.key} />} sections={[ // homogenous rendering between sections
{data: [...], key: ...}, {data: [...], key: ...}, {data: [...], key: ...}, ]} />
```

### Solution

`<ListItem title={item.title}}`

add a closure:

`<ListItem title={item.title} />}`

### Additional Information

* React Native version: .43

**Comment by radko93** [comment]
It's already fixed on `master` https://github.com/facebook/react-native/blob/master/Libraries/Lists/SectionList.js#L203
