### ISSUE TITLE
npm test chokes on jsx in node_modules imported component

### ISSUE THREAD

**Issue by QuantumInformation** [facebook/react-native#13677]
### Description

When running npm test [here](https://github.com/QuantumInformation/react-native-cron/tree/master/tests/DemoApp) 
  
I get a JSX error:

![image](https://cloud.githubusercontent.com/assets/216566/25456622/57f299d8-2acb-11e7-8fe2-8b46aa5ba143.png)

### Reproduction Steps and Sample Code

Clone this  [app](https://github.com/QuantumInformation/react-native-cron/tree/master/tests/DemoApp) and run npm test

### Additional Information

* React Native version:0.43.3
* Platform:tests
* Development Operating System: MacOS
* Dev tools: `react-native run-ios`

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/npm-test-chokes-on-jsx-in-nodemodules-imported-component

**Comment by QuantumInformation** [comment]
Ok, thanks.
