### ISSUE TITLE
Autocorrect on iOS TextInput doesn't fire onChangeText in react-native 

### ISSUE THREAD

**Issue by rohitgoyal** [facebook/react-native#13675]
react-native version : 0.43.4
Platform: iOS
Component: TextInput

Steps to reproduce: 
1) Type a misspelled word in TextInput 
2) Press space to make sure it haven't changed to the correct word yet. In case it did just delete and make it the misspelled word again. 
3) Now iOS must be showing the word underlined with dotted red color. Tap on that and iOS will show you 2 types of autocorrect. One would be at the side of the word and second at the top of the keyboard. 
4) Select the autocorrect from the top of the keyboard. 
5) By checking logs etc you will know it hasn't fired any onChangeText event.

Some posts shows it has been resolved in recent react-native versions but I checked it today only with latest react-native version 0.43.4

**NOTE: Read point number 3 carefully to reproduce.**

**Comment by shergin** [comment]
Duplicates #6715 and #2552.
