### ISSUE TITLE
Computed properties fails strict check

### ISSUE THREAD

**Issue by poulsbo** [facebook/react-native#1368]
When I try to use **two** computed properties in an object literal:

```
"use strict";
var foo = {
  [this.props.prop1]: 'whatever',
  [this.props.prop2]: 'something else',
};
```

I get a Red Box stating: `TransformError: Duplicate data property in object literal not allowed in strict mode /path/to/ReactComponent/Component.js:nnn:mm`

Removing `"use strict";` clears the warning, and the code works as expected.

**Comment by ide** [comment]
Babel should end up fixing this for free.

**Comment by amasad** [comment]
Yup. Come Friday this will disappear :)

**Comment by ide** [comment]
Babel landed in master: https://github.com/tadeuzagallo/react-native/commit/56d6ee3f0fadeb66aeb6cf9156c723759f48f617
