### ISSUE TITLE
[android] android project has multiple app,how to Integrate React-native to any app

### ISSUE THREAD

**Issue by zjc** [facebook/react-native#13682]
hi：
   sorry for my pool english. i have a android project, in this project has multiple app.
   
![image](https://cloud.githubusercontent.com/assets/1041554/25470133/28caaa3c-2b53-11e7-90c6-ed92848bb7c4.png)

  i read the 
   https://facebook.github.io/react-native/docs/integration-with-existing-apps.html but it does't help me.  in terminal, operation the react-native run-android 
Scanning 468 folders for symlinks in /Users/mark/git/welltang/node_modules (3ms)
Android project not found. Maybe run react-native android first?

when i create a new android project，it work well for me。
![image](https://cloud.githubusercontent.com/assets/1041554/25474060/60dc7084-2b64-11e7-8927-c5eb143ae270.png)
how to Integrate react-native to my welltang_patient app . 
                                            thanks

**Comment by zjc** [comment]
[operation.txt](https://github.com/facebook/react-native/files/960949/operation.txt)

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/android-android-project-has-multiple-apphow-to-integrate-react-native-to-any-app
