### ISSUE TITLE
Scrollview's styles property 'bounces' not valid

### ISSUE THREAD

**Issue by SeanChenU** [facebook/react-native#13686]
I use `bounces` style props for my scrollView according to official document, but it returns `not valid style property`

![2017-04-27 9 18 28](https://cloud.githubusercontent.com/assets/2536266/25485145/5ee7aee4-2b8f-11e7-9706-c6ba8c2b5e70.png)

![2017-04-27 9 19 07](https://cloud.githubusercontent.com/assets/2536266/25485171/81c1db56-2b8f-11e7-9569-a5880fd0e77f.png)

![2017-04-27 9 18 39](https://cloud.githubusercontent.com/assets/2536266/25485196/9a187fde-2b8f-11e7-8dc0-306b2ed5408e.png)

**Comment by chirag04** [comment]
@SeanChenU it's a prop on scrollview and not a style property. eg: `<Scrollview bounces={false} />`
