### ISSUE TITLE
Loading dependency graph, done - Hangs on Windows 7 in the Company Network

### ISSUE THREAD

**Issue by Manuel83** [facebook/react-native#13684]
### Description

I try to setup a ReactNative Project on Windows 7 with Andorid Emulator in the company network.
I run "react-native start" but it seems to hang. I waited for 10 min without progress. Our company network requires to set a proxy. Is build process connecting to the internet? If yes how can I set a proxy server for this step? Is there any way to debug this step to see what's going on?

![image](https://cloud.githubusercontent.com/assets/5859486/25477738/ddff2988-2b3e-11e7-8c4d-2d1bd30f760c.png)

![image](https://cloud.githubusercontent.com/assets/5859486/25477749/e4c65458-2b3e-11e7-8005-d81b5dbd2cd5.png)

### Additional Information

* React Native version: 0.43.4
* Platform:  Andorid
* Development Operating System: Windows 7
* Dev tools: Android Studio 2.3.1

**Comment by hongxuan229** [comment]
same here

**Comment by nicszerman** [comment]
Same

**Comment by semiautomatix** [comment]
Windows 10

**Comment by pedromazala** [comment]
Some news about this?

**Comment by rvhue** [comment]
1+

**Comment by pedromazala** [comment]
People, I removed all dependencies on Expo, and then I added all again. Afetr run `yarn install` my app get back to life.

**Comment by lihue** [comment]
Same problem on macOS Sierra

**Comment by lihue** [comment]
This helped me:

- delete node_modules folder
- npm install
- npm run ios (or react-native run-ios)

**Comment by enguerranws** [comment]
Here's how I deal with it (dumb way): just stop the packager session in your terminal and `react-native run-ios` again (and again if it still not work).

Some information about what's going on would be appreciated.

**Comment by henrynw** [comment]
For me, I fixed it by making sure I had these settings in Xcode Info.plist:

App Transport Security Settings:
 - Exception Domains
  - localhost (Dictionary)
    - NSTemporaryExceptionAllowsInsecureHTTPLoads (Boolean: YES)

**Comment by yuchaoshiniba** [comment]
Window10

**Comment by skinnyindonesian24** [comment]
same problem on OSX

**Comment by TrLam** [comment]
My fix was adding the FORCE_BUNDLING flag while building. So: `react-native run-ios FORCE_BUNDLING`
It continues building after the "Loading dependency graph, done." message

**Comment by lmiller1990** [comment]
Mid way through development I hit this problem. I had run `nvm use 8` which set my node version to 8.4. I run `nvm use 7` to use 7.2.1, and it worked fine. So if you are on node 8, try <7.

**Comment by ddobby94** [comment]
I am still getting this error. 
Brand new ignite installed, with every needed library on win 10.
Downgraded npm to v6, nothing.
Deleted & reinstalled all node_modules, did not work.

**Comment by jonathanadler** [comment]
After ```rm -rf node_modules && npm install``` didn't help me, I uninstalled the app from the simulator, and ran it again, and the problem was fixed.

**Comment by ddobby94** [comment]
I kind of solved the error.
Delete everything and generate new app with ignite from scratch worked for me.

**Comment by paramadeep** [comment]
I tried all the above suggestions, I'm having the latest version a node, and using latest version on react-native. any help is much appreciated.

**Comment by itsmrTech** [comment]
+1

**Comment by eduardomacetas** [comment]
I have the same problem...

**Comment by BWillis98** [comment]
Same problem on Ubuntu 17.10

**Comment by lymix0** [comment]
Same here Windows 10 any suggestion!

**Comment by Johncy1997** [comment]
same problem on ubuntu 16.04

**Comment by mehulmpt** [comment]
Same problem MacOS 10.13.2

**Comment by ecdundar** [comment]
Same Problem on "Windows 10" +1

**Comment by thedanielvogelsang** [comment]
Same

**Comment by lymix0** [comment]
update: I managed to run this on my MacOS 10.13 although I've been thru some identical problems like Windows but the last thing was to uninstall Java 9 and install Java 8 using `brew cask java 8`.

> Setting up your development environment can be somewhat tedious

**Comment by MJparis** [comment]
Same... (Windows 10)

**Comment by amtBurgos** [comment]
Same issue

**Comment by saravanakumargn** [comment]
Make sure in Android emulator Wifi is Turned on

**Comment by ismuk** [comment]
Same issues windows 10 - my solution, in case it helps anyone: I am using Webstorm as IDE and using the inbuilt terminal to run npm start android. Works fine until after a shutdown and reboot and then hangs as previously described. To get it working again I need to close and then reopen the inbuilt terminal window.
