### ISSUE TITLE
Sourcemaps resolution differ from iOS and Android

### ISSUE THREAD

**Issue by vongohren** [facebook/react-native#13685]
### Description

Im compiling sourcemaps for iOS and Android, I dont have any specialized code for the two of them in react native. But when i do a simple lookup on a generated error, with "source-map" from npm, iOS works, but android misses with 20ish lines.
I cant share sourcecode but sourcemap files are here: https://drive.google.com/drive/folders/0B3pN0HOOlBYQNlM0eEs3UU1JQU0?usp=sharing

### Reproduction Steps and Sample Code

I got the files through http://localhost:8081/index.ios.bundle.map?dev=false&minify=true
Change ios to android for android.
Then i changed to dev false and minify true in android settings and in iphone i loaded the gathered bundle instead of from the server.

And on my produced error, which was `console.log(kino.props.test.test)`, where both test objects are undefined, creating an unexpected javascript error.

### This produces for android:
"Undefined at e.props.test.test 689:1556"
This is line 689 and 1556
### This produces for iOS:
"Undefined at e.props.test.test 691:1048"
This is line 691 and 1048

Then using "source-map" from npm I created a script: https://gist.github.com/vongohren/5619e7ab9a2f6b352f66c996fc908a86

##### For android:
`node index.js 689 1556 index.android.bundle.map`

This produces:
`{ source: '/Users/snorreedwin/Code/entur/entur-clients/native/app/containers/Home.js',
  line: 55,
  column: 20,
  name: 'value' }`

##### For ios: 
`node index.js 691 1048 index.ios.bundle.map`
This produces:
`{ source: '/Users/snorreedwin/Code/entur/entur-clients/native/app/containers/Home.js',
  line: 33,
  column: 40,
  name: 'test' }`

 ### **PS: iOS is right, that is exact where the error is, but android is wrong! Why?**

### Solution

Why does it differ? Are there some config missing or something?

### Additional Information

* React Native version: "0.43.3"
* Platform: both
* Development Operating System: MacOS
* Dev tools: react-native-packager

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/sourcemaps-resolution-differ-from-ios-and-android

**Comment by zaguini** [comment]
+1

**Comment by pcguru** [comment]
Also related to https://github.com/bugsnag/bugsnag-react-native/issues/142

Seems like JavaScriptCore on Android reports the wrong column on errors?
