### ISSUE TITLE
"Unable to resolve module" error, even tho the module exists!

### ISSUE THREAD

**Issue by jenkynolasco11** [facebook/react-native#13692]
I started having this error recently:

```
error: bundling: UnableToResolveError: Unable to resolve module `./WeatherInterface.jsx` from `/Users/jenky/Dev/weatherApp/weather-app-react-native/app/components/WeatherInterface/index.js`: Directory /Users/jenky/Dev/weatherApp/weather-app-react-native/app/components/WeatherInterface/WeatherInterface.jsx doesn't exist
    at UnableToResolveError (/Users/jenky/Dev/weatherApp/weather-app-react-native/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:488:5)
    at Promise.resolve.then (/Users/jenky/Dev/weatherApp/weather-app-react-native/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:445:15)
    at process._tickCallback (internal/process/next_tick.js:109:7)
Bundling `index.ios.js`  94.6% (388/399), failed.
```
![simulator screen shot apr 28 2017 12 45 43 am](https://cloud.githubusercontent.com/assets/8356035/25514644/6a5dff22-2bac-11e7-9677-460beda7bed9.png)

in which I don't understand why.

(Sorry for the size of the image, btw)

I created this simple project a while ago and I had it running for Android in a Windows environment. Now, I moved everything to MacOS, refactored the whole code, and I can't get past this error. 

I tried everything I've found, from clearing the cache and the solutions from another issue opened (already closed, and similar to my case), and still nothing! 

Do you have any idea why is this happening?

If anything, I'll leave my [repository](https://github.com/jenkynolasco11/weather-app-react-native/tree/refactor) for you to check and judge on your own.

**Comment by Lxxyx** [comment]
React Native do not support jsx currently. Please use .js ext.

**Comment by daneharrigan** [comment]
Is the JSX extension not supported because of a technical limitation or just missing a PR?
