### ISSUE TITLE
[XMLHttpRequest] fetch fails with weird unicode whitespace character

### ISSUE THREAD

**Issue by malkomalko** [facebook/react-native#1369]
Making a request with fetch to https://gist.githubusercontent.com/malkomalko/d8f6641618cf490c24a1/raw/05152cfc2b436cce8a2d0d1c7a928ef99d6c68e7/bad_request.json will fail and never return.

Basically the XMLHttpRequest file uses an RCTDataManager.m function.  Most of these files are in https://github.com/facebook/react-native/tree/master/Libraries/Network.

Here is the specific line where it should callback with the json response: https://github.com/facebook/react-native/blob/master/Libraries/Network/RCTDataManager.m#L69.

After doing some digging it appears like the result is coming back fine for the bad request so it appears to be something in the low level internals of the RCT_EXPORT_METHOD and RCTResponseSenderBlock.

I logged the return result of `RCTJSONStringify(responseJSON, NULL);` and put the results for a good and bad request below.

https://gist.github.com/malkomalko/6002587c7ba5967fb5af

**Comment by mnylen** [comment]
Also having this problem. At least U+2028 (line separator) character in http response body seems to cause this.

**Comment by mnylen** [comment]
U+2029 (paragraph separator) also causes this

**Comment by mnylen** [comment]
Weird thing is, it seems to work at least when debugging in chrome.

**Comment by paulgessinger** [comment]
I also have this exact problem. Anyone found a solution or workaround to this?

**Comment by mnylen** [comment]
@paulgessinger if you can control the server side, just strip out those characters. Otherwise I don't know.

**Comment by paulgessinger** [comment]
It's an external site of a client that they don't have immediate technical control over (and thus I don't). I wrote a proxy in node running somewhere else and strip the characters there. It's a hack but it works. 

Would be really nice to have some official insight here.

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by astreet** [comment]
This seems to affect JSC on both android and iOS

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/xmlhttprequest-fetch-fails-with-weird-unicode-whitespace-character

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
