### ISSUE TITLE
Support alignContent StyleSheet property

### ISSUE THREAD

**Issue by MoOx** [facebook/react-native#13698]
### Description

I tried to use `alignContent` style property, which [is available in yoga for a while](https://github.com/facebook/yoga/pull/79) but I got an error saying it's not an available property.

### Reproduction Steps and Sample Code

```js
// @flow

import React from 'react';
import { StyleSheet, View } from 'react-native';

const CenterView = (props: Object) => {
  return (
    <View style={styles.main}>
      {props.children}
    </View>
  );
};

const styles = StyleSheet.create({
  main: {
    flex: 1,
    justifyContent: 'center',
    alignContent: 'center',
  },
});
```

### Solution

I guess there is a mapping that's missing. I saw something in #1171 but it's look out of my league.

### Additional Information

* React Native version: 0.42.
* Platform: iOS 10
* Development Operating System: macOS 10.12
* Dev tools: Xcode 8.2

**Comment by karanjthakkar** [comment]
@MoOx Support for this seems to have been added since `v0.43.0-rc.0`. Check this commit: https://github.com/facebook/react-native/commit/31f848a5fa56e17fbc6dbbba7d319a3b30083ac8 and this release note: https://github.com/facebook/react-native/releases/v0.43.4

**Comment by MoOx** [comment]
Wow yeah. My bad!
