### ISSUE TITLE
When TextInput set OnBlur event, it will prevent trigger other Onpress event

### ISSUE THREAD

**Issue by Aaaaaaaty** [facebook/react-native#13693]
![image](https://cloud.githubusercontent.com/assets/15126694/25519421/53d1ca94-2c2a-11e7-92b8-a151334dfdd6.png)
When i foucs this input, i wanna click on other places to trigger OnPress event. But OnBlur event prevent. I must trigger twice.
```
<View style={ [styles.inputWrapper, {justifyContent: this.state.inputJustifyContent}]}>
              <TextInput  style={[styles.inputInner, { width:this.state.inputWidth}] }
                          placeholder="城市名称或首字母"
                          clearButtonMode="while-editing"
                          keyboardType="default"
                          caretHidden={ this.state.caretHidden }
                          onFocus={ this.inputOnFocus.bind(this) }
                          onBlur={ this.inputOnBlur.bind(this) }/>
</View>
<TouchableOpacity style={{flex: 1}} >
     <Text onPress={ this.inputCancel.bind(this) } style={styles.inputCancel}>取消</Text>
</TouchableOpacity>
```
How to trigger blur and press by one click? or other solution?

**Comment by topchyalexey** [comment]
Face that problem too

**Comment by kylanhurt** [comment]
I am also having issues with this. An onPress to a touchable component underneath the TextInput (think of an textComplete list of search results) instead gets interpreted as only an onBlur event for the TextInput. Would love to see a reasonable solution for this.

**Comment by raduflp** [comment]
any updates on this?
