### ISSUE TITLE
[documentation] Native UI Components example is incorrect

### ISSUE THREAD

**Issue by johndanek** [facebook/react-native#13690]
The documentation at https://facebook.github.io/react-native/docs/native-components-android.html#3-expose-view-property-setters-using-reactprop-or-reactpropgroup-annotation appears to be incorrect for Android.

ReactImageView.setSource does not accept a String as an argument, only a ReadableArray. I cannot find a way to even create a ReadableArray in order to stuff my string into it.

This is preventing me from working through the Native UI Components tutorial.

Other than this one example of using a ReactImageView, I can find absolutely no documentation for creating my own custom native component. I would like to use the Google Cardboard VR/360 video player, but there is a lack of information.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/documentation-native-ui-components-example-is-incorrect

**Comment by seanyu4296** [comment]
Hi, I think this is still an issue I'm trying to create a custom Image component for a grayscale Image feature but I cant seem to get why it uses a ReadableArray

**Comment by seanyu4296** [comment]
@johndanek have you figured this out?
