### ISSUE TITLE
ListView inside Pull to Refresh scrollview is not scrolling for scroll down event

### ISSUE THREAD

**Issue by jittu-tutu** [facebook/react-native#13701]
### Description

Added a list view as child view to the Parent ScrollView which is having RefreshControl to support for pull to refresh.
I expected when user drag down the child ListView, the the listView should scrolldown. 
But Actually Pull to Refresh is happing for drag down event only for Android. On iOS it is working fine. 

### Reproduction Steps and Sample Code
    <View style={styles.containerStyle}>
     <ScrollView contentContainerStyle={styles.contentContainerStyle} refreshControl={
          <RefreshControl
            refreshing={this.state.refreshing}
            onRefresh={this._onRefresh.bind(this)}
          />
        }>
      <View> Some header </View>
      <MyComponent> </MyComponent>
      <ListView
        dataSource={dataSource}
        initialListSize={10}
        renderRow={this.renderRow}
        renderSeparator={this.renderSeparator}/>
     </ScrollView>
    </View>

List all the steps required to reproduce the issue you're reporting. These steps should be clear and concise.

1. Add a ScrollView with RefreshControl  as a parent 
2. Add ListView as a child 
3. ListView should contain enough data so that It can be scrolled in Android. 
4. Now Drag down in List view. 

Expected: List view should scroll for this drag-down event 
Actual :  Pull to Refresh is happening for drag down/Scroll down event (only for Android). drag up/Scroll up is actually scrolling the list in Android. 
### Additional Information

* React Native version: 
react-native-cli: 2.0.1
react-native: 0.40.0

* Platform: Android only. 
* Development Operating System: Mac

**Comment by hramos** [comment]
Does this still reproduce using FlatList? ListView is deprecated.

**Comment by yapiskan** [comment]
@hramos yes it is reproducible for FlatList as well. On Android somehow, scrollview and listview/flatlist cannot decide which one should respond to touches and eventually both responds. or the respond switch from one to another is very easy.

@jittu-tutu it has been long time but, I had the similar issue, try using ViewPagerAndroid instead. That worked for me. However, I had to move RefreshControl to listviews.

**Comment by cheniuiOSloved** [comment]
has anyone fixed this issue?.I have the same problem.Using the scrollView contains the listView ,the listView has a refreshControl,the "onRefresh" not invoke when user drag down.

**Comment by Skarpovich** [comment]
I have the same problem with FlatList inside ScrollView.

react-native-cli: 2.0.1
react-native: 0.49.5
platform: Android only.

**Comment by chetankotkar** [comment]
Any solution on this issue ?

**Comment by Tiago-Marques** [comment]
@Skarpovich, i have the same problem but only iOS platform. 
(using 'create-react-native-app')

"expo": "^23.0.4"
"react": "16.0.0"
"react-native": "0.50.3"
"react-native-cli": "2.0.1"

Also my scenario is similar to #14756,

I'm trying make a HOC with "auto scroll when needed" for all my screen/components, but one of them has a FlatList with RefreshControl not working only iOS platform.

I don't think it is a bad pattern / design like @dmr07 said.

Any sugeestions?

**Comment by reed-jones** [comment]
Adding to what @Komalov said, I fixed my issue, by simply moving the entire refresh control prop
```js
refreshControl={
  <RefreshControl
    refreshing={this.state.refreshing}
    onRefresh={this._onRefresh.bind(this)}
  />
}
``` 
off of my SectionList & FlatList, and onto the ScrollView.
