### ISSUE TITLE
Rerendering with rotate property dynamically set causes app to crash in Android

### ISSUE THREAD

**Issue by thevishnupradeep** [facebook/react-native#13706]
The code below is the problem. This works perfectly in iOS but not in Android.

`<TouchableOpacity
          style={[styles.addBtn, styles.roundBtnShadow, { transform: [{ rotate: this.state.renderForm ? '45deg' : '0deg'}] }]}
          onPress={()=>{ this.setState((state) =>({ newGoal: "", onEdit: false, renderForm: !state.renderForm })); }}>
          <Icon size={25} style={[styles.roundBtnIcon, { marginTop: 2 }]} name="plus" />
        </TouchableOpacity>`

I know the issue is in the code `{ transform: [{ rotate: this.state.renderForm ? '45deg' : '0deg'}` because the app works as expected if I remove this line. Please do note that the error comes only when I update renderForm and rerender.

![screenshot_20170429-010713](https://cloud.githubusercontent.com/assets/5638461/25553951/3d480600-2cd2-11e7-91ef-5d4650633423.png)

Any help would be highly appreciated. Thank you.

**Comment by d0ptnow** [comment]
Did you fix this bug? My app is crashing because of this bug on Android. Version 0.45 @hramos 

Thank you

**Comment by mdaslamansari2008** [comment]
I was able to fix this issue by removing the Transform and Rotate StyleSheet statements:
Here is the stackoverflow [link](https://stackoverflow.com/questions/49533224/errortypeerror-expected-dynamic-type-double-but-had-type-string-in-react-na/49533225#49533225) you can follow up.
