### ISSUE TITLE
AsyncStorage.multiSet callback not getting called

### ISSUE THREAD

**Issue by aferrerallu** [facebook/react-native#13704]
When I execute the code bellow, `AsyncStorage.multiSet` callback is not fired. I only get "this alert is called!" alert message, also, the data is not saved.
I don't have problems with other `AsyncStorage` functions, I tried saving each value with `itemSet` and they are saved with no problems, and the callback is fired.

###  Code

````javascript
var values = [['user', JSON.stringify(response.user)], 
              ['access_token', response.new_access_token]];
alert('this alert is called!');
AsyncStorage.multiSet(values, function(error) {
    alert("finished");
    if(error) { 
         alert("error!");
    } else { 
         alert("saved!");
    }
});
````

### Additional Information

* React Native version: 0.43.2
* Platform: Android at least
* Development Operating System:  Windows 10

**Comment by YOmicha** [comment]
I have the same error :(

**Comment by carlo-fontanos** [comment]
Same here...

**Comment by DMRE** [comment]
Same here =(

**Comment by hzburki** [comment]
same issue, only I have implemented this with promise. .then function is called but nothing is stored.

**Comment by ferdelcorro** [comment]
Same issue here with v0.51

**Comment by abdalafer** [comment]
I have the same issue some times. but with multiGet. I think its an emulator/nodejs issue. If you run
`react-native run-android`
then the app is able to read from the DB just fine.

**Comment by albertpak** [comment]
Any update on this issue? looking for some help about `AsyncStorage.multiSet()` - i have it setup to store a few keys upon user signing in, but when user signs in, screen blacks out and application exits...`AsyncStorage.setItem()` works fine, but I'm looking to set a few keys...any else come across this behavior?

**Comment by mcavaliere** [comment]
Running into this issue on React Native 0.55.4, within Expo 2.8.

**Comment by mcavaliere** [comment]
@albertpak and anyone who needs a workaround: I got it to `AsyncStorage.multiSet()` to save properly by ensuring that no values were null or undefined (and replacing them with an empty string instead).

**Comment by albertpak** [comment]
@mcavaliere thank you for the tip :) will try that out :)

**Comment by jerome-bfan** [comment]
ok but callback work on ios, not on android (for me), do i need to check if my all values are null inside my multiset?
