### ISSUE TITLE
[FlatList] Docs on Flatlist typo

### ISSUE THREAD

**Issue by mayaa6** [facebook/react-native#13716]
### Description

There is a type in Official docs [FlatList page](https://facebook.github.io/react-native/docs/flatlist.html): 

![image](https://cloud.githubusercontent.com/assets/3221154/25564523/ab8ecfac-2de7-11e7-8cd4-b74d1aba24e0.png)

The slash should be placed at the beginning of the closing tag.

**Comment by atlanteh** [comment]
Seems like it has been fixed in commit [f25df50](https://github.com/facebook/react-native/commit/f25df504edf3956244eaa644b60076568414668d)
You can see it in next release docs:
http://facebook.github.io/react-native/releases/next/docs/flatlist.html#flatlist
