### ISSUE TITLE
Semantic Versioning

### ISSUE THREAD

**Issue by jhabdas** [facebook/react-native#13714]
I haven't done any RN dev in about a year so I'm curious if here has been any discussion about lifting a 1.0.0 to the community following SemVer principles, and what might be needed to establish a 1.0.0 other than simply cutting the version given RN is used in production and qualifies for such a version. Having it would set a good example for module developers and help avoid a Grunt scenario longer term. Thoughts?

http://semver.org/

> If your software is being used in production, it should probably already be 1.0.0. If you have a stable API on which users have come to depend, you should be 1.0.0. If you’re worrying a lot about backwards compatibility, you should probably already be 1.0.0.

**Comment by hramos** [comment]
It has been brought up in the past (for example, https://www.facebook.com/groups/reactnativeoss/permalink/1604716516491643/).

There's been some discussion amongst core contributors but nothing to announce at this point. Closing as I'm trying to keep the tracker focused on bugs.
