### ISSUE TITLE
`npm install --save react-native` failed

### ISSUE THREAD

**Issue by carlgik4** [facebook/react-native#1371]
I followed the instruction to install react-native on my macbook
http://facebook.github.io/react-native/docs/getting-started.html

It seems like to use a ssh command to fetch repository, but my ssh key .ssh/id_rsa is not used for github, so I encounter an error:
![screen shot 2015-05-22 at 9 58 51 am](https://cloud.githubusercontent.com/assets/544929/7762570/713aa18a-0069-11e5-83e3-30ae271da83d.png)

git fetch -a origin (git://github.com/frantic/stacktrace-parser.git)
could you turn this fetch method to https://?
thanks a lot.

**Comment by brentvatne** [comment]
@carlgik4 - This wouldn't be related to your ssh config - it seems like your network is blocking the connection. You can try it on another network or create a fork of the project to get it working right away.

cc @frantic

**Comment by frantic** [comment]
I'll take a look, thanks for reporting!

**Comment by threepointone** [comment]
I have a similar problem inside office, and have a workaround (run in terminal) -  `git config --global url."https://".insteadOf git://`

**Comment by ide** [comment]
Changing the package.json deep URL to `frantic/stacktrace-parser#493c5e5638` should do the trick, or at least make this a general problem with npm instead of react.

**Comment by brentvatne** [comment]
Good call @ide, made a PR for that. Until then, @threepointone's workaround should fix this for anyone who has the issue!
