### ISSUE TITLE
Lost all module in Android Studio after upgrade RN to 0.43.4

### ISSUE THREAD

**Issue by Symous** [facebook/react-native#13729]
Help ! I added some third-party lib to my program before, and when I open the android program in Android Studio, it will show me the all the added modules. but they all disappeared after I upgraded the RN  to  verison 0.43.4, and the dependencies in build.gradle also have been set to initial state. Please is there any way to fix this since I have edit some source code of the third-party lib to meet my own statisfication in my program .

**Comment by vonovak** [comment]
I'm sure you have used a version control system such as git? :)

**Comment by Symous** [comment]
All right,I have use react-native link command to re-link these libs and do lots of manually operations to recover this. Wish it will not happen again!!
