### ISSUE TITLE
headlesstask wake-lock consumes battery

### ISSUE THREAD

**Issue by atlanteh** [facebook/react-native#13720]
I have a headless task that wakes up every 30 minutes. does some work for 1-2 seconds and finishes. However I see that the wake-lock is held much much longer than necessary. The battery is draining like crazy. I thought this might be something with my code, so I created an empty project with just my headless task code, but the wake-lock keeps draining the battery. I added logs and I see that the services is destroying after the task is done, so it's releasing the wake-lock acquired in the receiver. So either I'm doing something wrong, or the problem is in react-native.

I uploaded my demo example here:
https://github.com/atlanteh/headlesstask-battery-consumption-example

* React Native version: 0.41.2
* Platform: android
* Development Operating System: windows

**Comment by atlanteh** [comment]
Why did you close this issue? Is it solved?

**Comment by atlanteh** [comment]
@hramos Can you please explain why you closed this issue? It still happens to me..

**Comment by oriharel** [comment]
@atlanteh maybe you need to call onHeadlessJsTaskFinish() instead of stopSelf() directly.

**Comment by atlanteh** [comment]
I don't think so. onHeadlessJsTaskFinish() is meant after a task is finished, not when it was never executed. I left this specific task a long time ago, but now I see that some other modules implement it and you can see [here](https://github.com/vikeri/react-native-background-job/blob/master/android/src/main/java/com/pilloxa/backgroundjob/ReactNativeEventStarter.java), for example, that they don't call stopSelf() or anything, just return null. so maybe this is the problem.
Do you have any insights on this?

**Comment by oriharel** [comment]
I haven't got this far with HeadlessJsTaskService. My issues revolve around ReactContext created not on the main thread. see #15915.

However, I did notice that inside [HeadlessJsTaskService.startTask()](https://github.com/facebook/react-native/blob/1e8f3b11027fe0a7514b4fc97d0798d3c64bc895/ReactAndroid/src/main/java/com/facebook/react/HeadlessJsTaskService.java#L98) there is already a call to acquireWakeLockNow(). So with your call from the received that makes it 2 calls. Maybe you can drop the call from the receiver (I know we are told to do so from the documentation but worth a shot).

**Comment by oriharel** [comment]
Also, maybe try to update React Native to latest and see if it reproduces.

**Comment by atlanteh** [comment]
I must call the acquireWakeLockNow in the broadcast receiver. See the [docs](https://facebook.github.io/react-native/docs/headless-js-android.html):

> If you start your service from a BroadcastReceiver, make sure to call HeadlessJsTaskService.acquireWakeLockNow() before returning from onReceive().

This is to prevent the phone from falling asleep before actually starting the service.
