### ISSUE TITLE
Navigator is deprecated in RN 0.44.0 and not working 

### ISSUE THREAD

**Issue by amirrezamahyari** [facebook/react-native#13723]
As i reported new issue in [react-navigation issue](https://github.com/react-community/react-navigation/issues/1328)

after upgrade react native to 0.44.0 i get this error :

i use react-navigation 1.0.0-beta.9 package and i got BackAndroid deprecated too .

Navigator is deprecated and has been removed from this package. It can now be installed and imported from react-native-deprecated-custom-components instead of react-native. Learn about alternative navigation solutions at http://facebook.github.io/react-native/docs/navigation.html

how can i fix this ?

**Comment by stoffern** [comment]
Are you shure you dont have any kind of the `Navigator` from `react-native` api used?

**Comment by amirrezamahyari** [comment]
@stoffern yes . i find any referenced to Navigator in my android bundle file exactly .

**Comment by grabbou** [comment]
I have answered in React Navigation because it has more context. Closing that one.

**Comment by rh389** [comment]
If anyone else is getting this warning without any mention of `Navigator` in their code, make sure you don't have anything like `import * as Foo from 'react-native'`.

`import * ...` triggers this error because RN thinks you're trying to import a removed module.
