### ISSUE TITLE
WebView not work on Android 7.0 (API24)

### ISSUE THREAD

**Issue by weeravit** [facebook/react-native#13721]
### Reproduction Steps and Sample Code
1. Run Genymotion 2 devices = Samsung S8(api24), Nexus 5(api23)
2. build below sample code
3. Samsung S8(api24) or another device api24 not display web or not responsding

sample code
https://gist.github.com/weeravit/56075d9569d7ff8db22bae19eb200894

### Additional Information

* React Native version: 0.44
* Platform: Android
* Development Operating System: MacOS

**Comment by brunolemos** [comment]
@weeravit Apparently it works fine: https://snack.expo.io/ryDCH4SyW

Try this: 

1. Go to `package.json` and set the `name` property to `app`
2. Change the line `export default class test extends Component {` to `export default class App extends Component {` -- **components must start with uppercase letter**
3. Change the line `AppRegistry.registerComponent('test', () => test);` to `AppRegistry.registerComponent('app', () => App);`
4. Test with another code without `WebView`, just with a simple `Text`

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/webview-not-work-on-android-70-api24
