### ISSUE TITLE
iOS, RN 0.43.2 Multiline text does not show magnifying glass on long press

### ISSUE THREAD

**Issue by thomasttvo** [facebook/react-native#13722]
I haven't tested on Android, but on iOS you can reproduce by following these steps: 

1. Make a multiline Textinput that has more than 1 row. Let's make it 5 rows so we could easily see the issue. 
2. Long press at the center of the Textinput

**Issue**: Notice that no magnifying glass is present.
Alternatively, if you long press at the first line, you'll see the magnifying glass.

**Expected**: This should match the default behavior of textarea: when you long press the textarea anywhere, it shows magnifying glass. Also notice the Reddit native app implements this behavior correctly in the screenshot below

![image](https://cloud.githubusercontent.com/assets/2142140/25578721/db293bd0-2e9b-11e7-809f-0f98d98d7503.png)

**Comment by shergin** [comment]
Can you reproduce this on master?
I am pretty sure I already fixed this month or two ago.

**Comment by thomasttvo** [comment]
Do you remember which file the fix is on? I can quickly check if it's in master or if it's not in 0.43.2 @shergin

**Comment by shergin** [comment]
The commit: 3acafd1f3dd42cc27a592cdee0530e0dbf1c8afd.

**Comment by thomasttvo** [comment]
That explains it. The fix is in 0.44.0 not in 0.43.0.
