### ISSUE TITLE
It's not possible to color emojis

### ISSUE THREAD

**Issue by msafi** [facebook/react-native#13728]
I'm trying to add this truck emoji 🚚 and change its color on React Native. On the web, that's possible by applying [this trick on StackOverflow](http://stackoverflow.com/a/39776303/604296).

With React Native, I tried to use `color`, `textShadowColor` and `textShadowOffset` as suggested by the StackOverflow answer, but it didn't work. 

The text shadow will not show if the text color is `transparent`. Apparently, on the web, that's not the case.

**Comment by hramos** [comment]
Thanks for opening the issue, however it looks like a feature request. As noted in the [Issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md) we'd like to use the GitHub issues to track bugs only. Can you implement the feature as a standalone npm module? If not consider sending a pull request or a create an entry on [Canny](https://reactnative.canny.io/feature-requests). It has a voting system and if the feature gets upvoted enough it might get implemented by someone from the community. Closing this now, thanks for understanding!
