### ISSUE TITLE
How do I pass environments to .babelrc?

### ISSUE THREAD

**Issue by kimjuny** [facebook/react-native#13733]
I'm working on a project using both react-web and react-native(mixed app). I was able to set environment variables using [cross-env](https://github.com/kentcdodds/cross-env) on web, but this seems not working with react-native. 

<b>Meaning</b>: 

1. npm script `cross-env NODE_ENV=development BABEL_ENV=development_web webpack-dev-server --hot --progress --config build/webpack.config.dev.js` works fine.

2. but `cross-env NODE_ENV=development BABEL_ENV=development_rn react-native run-ios` won't work! I tried to print out `process.env.NODE_ENV` and `process.env.BABEL_ENV` they both incorrect.

I got two different BABEL_ENV env settings for `.babelrc`:

    {
      "env": {
        "development_web": {
          "presets": ["react", "es2015", "stage-0"],
          "plugins": [
            [
              "react-transform",
              {
                "transforms": [
                  {
                    "transform": "react-transform-hmr",
                    "imports": ["react"],
                    "locals": ["module"]
                  }, {
                    "transform": "react-transform-catch-errors",
                    "imports": ["react", "redbox-react"]
                  }
                ]
              }
            ],
            ["import", { "style": "css", "libraryName": "antd-mobile" }],
            ["transform-decorators-legacy"]
          ]
        },
        "development_rn": {
          "presets": ["react-native"],
          "plugins": [["import", { "libraryName": "antd-mobile" }]]
        },
      }
    }

So how can I appoint NODE_ENV/BABEL_ENV to `development_rn` for react native?

**Comment by kimjuny** [comment]
Can anyone help? please? This thing's driving me nuts... I think many mixed-app developers should've encountered this same problem as me...

**Comment by mobinni** [comment]
React Native does not run in a node process, so you cannot expect it to behave in such a fashion. Try this: https://github.com/luggit/react-native-config
(source: http://stackoverflow.com/questions/42437995/react-native-process-env-has-only-node-env)

**Comment by agrcrobles** [comment]
I think you should try [haul](https://github.com/callstack-io/haul)

**Comment by okonet** [comment]
It seems to be related to https://github.com/facebook/react-native/issues/8723 and particularily the fact that `BABEL_ENV` is always overwritten: https://github.com/facebook/react-native/pull/6351/files#diff-4676ea0b3c55c65c3929aa993144f07fR104

**Comment by okonet** [comment]
@kimjuny it seems like 0.46 fixes that: https://github.com/okonet/react-native/blob/0.46-stable/babel-preset/configs/main.js

**Comment by alexlevy0** [comment]
+1

**Comment by rpowelll** [comment]
@okonet This continues to be an issue as of React Native v0.48.3. It seems like the packager still overwrites that variable.

**Comment by acvos** [comment]
This seems to still be an issue
