### ISSUE TITLE
PushNotificationIOS docs deprecated

### ISSUE THREAD

**Issue by kyangy** [facebook/react-native#13739]
Unfortunately, the docs on https://facebook.github.io/react-native/docs/pushnotificationios.html#content is throwing warnings saying UIUserNotificationSettings/UILocalNotification is deprecated in ios 10 and to use UNNotificationSettings. What is the correct setup in AppDelegate.m for push notifications to work with ios 10 without any warnings?

**Comment by dmackinn** [comment]
I'd like to see this as well

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/pushnotificationios-docs-deprecated

**Comment by dmackinn** [comment]
The deprecation notice still occurs on React Native 0.48.0-rc.0 with Xcode 8.3.3, iOS 10.x
Documentation is still outdated.

**Comment by hramos** [comment]
@dmackinn it doesn't seem like anyone is actively working on this. Feel free to send a PR!
