### ISSUE TITLE
Live-Reload is not working properly. Add manual live reload via command-line/keyboard shortcut.

### ISSUE THREAD

**Issue by DomiR** [facebook/react-native#13737]
### Description
Live-Reload is currently not picking up every filechanges. It is really annoying having to pick up the device to shake it only to press reload.

Could we add an cli-command like `react-native reload` and `react-native reload --hot`?
Ideally one could add shortcuts to ones favorite IDE to enable something like `cmd-r` to reload the app manually, whenever it is suitable. When changing multiple files at once, e.g. refactoring method parameters, the app will often reload prematurely on filechange and crash with the red screen. It would be nice to be able to issue a reload command from within the IDE, without having to shake the device.

### Additional Information
* React Native version: 0.44.0-rc.0
* Platform: both
* Development Operating System: MacOS

**Comment by neiker** [comment]
+1 to command-line/keyboard shortcut

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/live-reload-is-not-working-properly-add-manual-live-reload-via-command-linekeybo
