### ISSUE TITLE
Documentation on Networking incorrect about Apple's ATS requirements

### ISSUE THREAD

**Issue by jasonhocker** [facebook/react-native#13738]
### Description

When reading the documentation on http://facebook.github.io/react-native/docs/network.html I noticed that the note about  App Transport Security  was incorrect.  Apple has pushed back their deadline from January 2017 that App Store review will require reasonable justification for disabling ATS.

### Reproduction Steps and Sample Code

https://developer.apple.com/news/?id=12212016b 

### Solution

What needs to be done to address this issue? Ideally, provide a pull request with a fix.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/documentation-on-networking-incorrect-about-apples-ats-requirements
