### ISSUE TITLE
[FlatList] [Android] Issue with TextInput element in the bottom of a FlatList

### ISSUE THREAD

**Issue by ibratoev** [facebook/react-native#13745]
### Description

This is closely related to #9822 but using the new FlatList:
TextInputs at the bottom of the screen in a FlatList automatically and immediately dismiss the keyboard on focus, making it impossible to write anything in it.
The issue is reproducible easily on a blank `react-native init` project. I tested it in Nexus 5x simulator and real device. I repro the bug every time on 0.42, 0.43 and 0.44.

### Reproduction Steps and Sample Code

index.android.js:

```
export default class Test extends Component {
  constructor(props) {
    super(props);
    let items = [];
    for (let i = 0; i < 30; i++) {
      items.push({ key: i });
    }
    this.state = { items };
  }

  render() {
    return (
      <View style={{ flex: 1 }}>
        <FlatList
          data={this.state.items}
          style={{ flex: 1 }}
          renderItem={(i) => (
            <View style={{ flexDirection: "row", borderBottomWidth: 1, borderBottomColor: "#333", padding: 24 }}>
              <Text style={{}}>{i.index}</Text>
              <TextInput style={{ flex: 1, backgroundColor: "#bbb" }} />
            </View>
          )}
        />
      </View>
    );
  }
}

AppRegistry.registerComponent('Test', () => tes);
```

### Solution

The only working workaround for the moment I have found is using `android:windowSoftInputMode="adjustPan"` in the AndroidManifest.xml. Unfortunately, it causes other UI glitches when the keyboard is opened.

### Additional Information

* React Native version: 0.44
* Platform: Android
* Development Operating System: OSX

**Comment by ibratoev** [comment]
The issues is reproducible with `VirtualizedList` as well (just replace `FlatList` with `VirtualizedList`) in the example.
Additionally, I tried to put TextInputs directly in a ScrollView. The issues was not reproducible in this case.

**Comment by magrinj** [comment]
Same problem for me, the problem can't be resolved even by moving the TextInput when this one is focused :/

**Comment by desjarlaisdumaishugo** [comment]
Same problem. Using adjustPan for now.

**Comment by rtman** [comment]
I am also seeing this in the same situation. I have a Flatlist with textinputs in it, focusing on any that would be below the keyboard shifts them up above the keyboard but they immediately unfocus causing glitchy behavior. In the emulator the keyboard stays open after but is not able to enter text. On my nexus 5 phone it shifts the text input up and opens/closes the keyboard quickly then loses focus.

Is there anyway to keep focus on these? Can we fix this behaviour?

**Comment by rtman** [comment]
I am also using adjustPan for now, would prefer not to however as it pushes content off the screen.

**Comment by jchirschy** [comment]
I've got the same issue.
Anything new ?

Just testing `adjustPan`. Seems working fine.
What kind of UI issue may happen ?

**Comment by foggy1** [comment]
I seem to be having this exact same issue on iOS with a TextInput as the ListHeaderComponent of a SectionList, meaning adjustPan isn't even an option.

**Comment by freemile2ru** [comment]
I am still experiencing this issue RN 5.2 when TextInput is placed in ListHeaderComponent

**Comment by superhawk610** [comment]
This issue is still present in RN 0.55.

**Comment by scottmas** [comment]
Kind of a show-stopper for text inputs on Android. This should definitely be re-opened.

**Comment by scottmas** [comment]
It only happens when `keyboardDismissMode='on-drag'` is enabled in a `ScrollView` or `FlatList`

**Comment by alexgnatrow** [comment]
I have encountered on this issue. It still prevails? Any better workaround, besides messing with android manifest?

**Comment by witalobenicio** [comment]
@alexgnatrow You are still getting this issue? If not, what version of RN are you using?
