### ISSUE TITLE
React-Native Fetch is failing on Android AVD but works in iOS Simulator

### ISSUE THREAD

**Issue by prathammehta** [facebook/react-native#13741]
### Description

Called a simple GET request on react native. It works perfectly in the iOS simulator but waits a while and then always gives me a 'Network request failed' error on the AVD.

### Reproduction Steps and Sample Code

Here's the code

`let response = await fetch("https://api.icndb.com/jokes/random/",{
      method:'GET',
    });
    alert(response);`

### Additional Information

* React Native version: 0.43.4
* Platform: Android
* Development Operating System: MacOS

**Comment by rodriguesbreno** [comment]
@prathammehta try
adb reverse tcp:8081 tcp:8081

Android have a different way to connect, and the "localhost" at your machine isn't the same at AVD or Android Device

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/react-native-fetch-is-failing-on-android-avd-but-works-in-ios-simulator
