### ISSUE TITLE
FlatList Accessibility

### ISSUE THREAD

**Issue by n8armstrong** [facebook/react-native#13743]
### Description

It is currently not possible to swipe to the next item in a FlatList using VoiceOver if that item is off screen.

[ListView had the same problem](https://github.com/facebook/react-native/issues/10780)

### Reproduction Steps and Sample Code

* Set up a FlatList
* Turn VoiceOver on
* Swipe to scroll through a large list

### Solution

A great solution would be for the FlatList to scroll on its own as VoiceOver moves up and down the list. However, if we had access to the [UIAccessibilityFocusProtocol](https://developer.apple.com/reference/uikit/uiaccessibilityfocus) events we could potentially scroll the FlatList ourselves.

### Additional Information

* React Native version: 0.44.0
* Platform: iOS
* Development Operating System: MacOS

**Comment by sahrens** [comment]
does removeClippedSubviews={false} fix the primary problem?

It would be nice to support the UIAccessibilityFocusProtocol, but that's not on our radar right now - a PR would be appreciated though! Feel free to discuss ideas with people in the community before starting on the implementation, or add/vote for it as a feature request on product pains: https://react-native.canny.io/feature-requests

I'm going to close this for now, feel free to re-open if removeClippedSubviews={false} doesn't fix the primary issue.

**Comment by thedrick** [comment]
For other who find this issue from Google, setting `removeClippedSubviews={false}` does fix VoiceOver navigation. I merged a fix for this into Airbnb's fork of RN which addresses the issue as long as VO is running before the component is mounted. It's definitely not an ideal fix, but does solve it for all RCTView's without needing to set `removeClippedSubviews={false}` manually https://github.com/airbnb/react-native/pull/33
