### ISSUE TITLE
react-nativigation missing methods?

### ISSUE THREAD

**Issue by npomfret** [facebook/react-native#13759]
I'm upgrading to RN0.44 and noticed that the navigation had been removed.  I'm in the process of implementing the replacement react-nativigation but it doesn't seem to have the same features.  For example, I can't `replace` a route in the stack any more.  .. or am I missing something?

**Comment by chirag04** [comment]
react-navigation is a separate project and it's better to post it on react-navaigation's issue tracker.

**Comment by chirag04** [comment]
react-navigation is build on top of the old navigation-exp component so it would be worth adding what you need into react-navigation. ex-navigation(now **deprecated** in favor of react-navigation) is also a good.
