### ISSUE TITLE
Black Radius Images on Android

### ISSUE THREAD

**Issue by emretekince** [facebook/react-native#13752]
Whenever I add borderRadius to an Image style, it becomes full black circle.
<img width="418" alt="screen shot 2017-05-03 at 11 25 25" src="https://cloud.githubusercontent.com/assets/5754074/25652919/3c686e5e-2ff3-11e7-9977-c8a57dd8a17f.png">

* React Native version: 0.43.2
* Platform: Android
* Development Operating System: OSX
* Dev tools: Android Studio

**Comment by gameboyVito** [comment]
Hi, have you solved this issue? I am facing the same one like this. This only happens on android 5.0, and the Image component is nested inside a FlatList.

**Comment by tsaohucn** [comment]
I have this issue as well.

**Comment by ol2dd** [comment]
+1

**Comment by beeant** [comment]
me too...
