### ISSUE TITLE
Style issues when inlining a touchable target within <Text />

### ISSUE THREAD

**Issue by joncursi** [facebook/react-native#13750]
I keep noticing various stylistic issues when I inline a touchable target, say an Icon wrapped with `TouchableOpacity`, within a `Text` component. In this example, there is a story with the author's name being a clickable target inside a larger `Text` component. The default render is blatantly incorrect as the sentence is overflowing off of the paper beneath it, but when you tap on the touchable target,  it snaps into place the way it should have re-rendered initially.

![untitled](https://cloud.githubusercontent.com/assets/4974609/25648281/49910268-2f98-11e7-95d3-adff29c3f37f.gif)

Pseudo code:

```jsx
<Text>

  <SomeTouchableThing
    onPress={() => {}}
    style={{ width: ..., height: ... }}
  />

  {'some other text in here.'}

</Text>

```

It's weird. I'm at a loss for why the default render is incorrect in situations like this. Has anyone else experienced this issue?

**Comment by mobinni** [comment]
I noticed the same issue, so I made a custom touchable opacity that you can style yourself.
https://gist.github.com/mobinni/dd85ba6e3b52a60db2aa0d0a18b45d2b

**Comment by joncursi** [comment]
This only happens for me on iOS. Android renders correctly every time. :/

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/style-issues-when-inlining-a-touchable-target-within-text
