### ISSUE TITLE
react-native-git-upgrade doesn't recognize "latest" in package.json

### ISSUE THREAD

**Issue by austinfathman** [facebook/react-native#13762]
### Description

We use "react-native": "latest" in our package.json, however when running react-native-git-upgrade, it compares the installed version of react-native (0.44.0) to the string in the package.json (latest) and halts operation due to the mismatch, saying that I should run npm install to fix the issue.

### Proposed solution:

Resolve "latest" to point to the latest react-native version number.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/react-native-git-upgrade-doesnt-recognize-latest-in-packagejson
