### ISSUE TITLE
Image onLoad / onLoadStart not firing

### ISSUE THREAD

**Issue by cbjs** [facebook/react-native#13763]
react-native 0.43 & 0.44

**Comment by spencewine** [comment]
Broken for me in 0.42

**Comment by ChongChou** [comment]
same issue for me, react-native 0.44, iOS was broken, but android work fine

**Comment by Fanghornn** [comment]
Hello, i also went through the same issue with react-native in 0.42 but i've been able to fix it.

I had a component that renders a single `<Image />` and it's only purpose was to compute it's height correctly.

So what i was doing, is that i was using the state to set the style of the image like `style={[styles.image, this.state]}` 

And the state looks like this in the constructor: `this.state = { height: 0 };`

Then, after mounting and first render, the state height would've been updated by the onLoad event.

What i figured out, is that if you set `height` to `0` before rendering, IOS won't fire onLoad/onLoadStart, by setting it to `1` these events fires again.

**Comment by mikelambert** [comment]
I am experiencing this for Android 0.45.1. I don't need/care for this feature on iOS, so haven't tested it there. It is not calling `onLoadEnd`, despite `shouldNotifyLoadEvents` being set.

I am using an already-loaded image source (ie, same as another component), though not sure if that 
is relevant here (ie, will it still run through these lifecycle events if the image is pre-loaded?).

**Comment by liucr** [comment]
It's ok on iOS, but partially can't display on android on the same list.

**Comment by davidroman0O** [comment]
I'm on 0.46.1 and i got the same issue !

**Comment by ljunb** [comment]
Same issue for me in 0.48.2, it's works fine on Android but not iOS. And we figured out the same way to fix it as @Fanghornn mentions.

**Comment by hiphapis** [comment]
I got same issue on 0.49.3
```javascript
<Image
  source={{ uri }}
  onLoad={() => console.log('onLoad')}
  onLoadStart={() => console.log('onLoadStart')}
  onLoadEnd={() => console.log('onLoadEnd')}
  resizeMode="cover" />
```
any handlers are not called

**Comment by Oblongmana** [comment]
Ditto on 0.49.3 on iOS

**Comment by jack2684** [comment]
Ditto, RN 0.51.0 on iOS

**Comment by monkingame** [comment]
0.51.0 same issue +1

**Comment by NelGarbuzova** [comment]
Thanks to @Fanghornn . It works!
