### ISSUE TITLE
Unbalanced calls to begin/end appearance transitions.

### ISSUE THREAD

**Issue by myusuf3** [facebook/react-native#1376]
Currently I have an application where the button that is triggered from a react view controller which pushes a modal view for `Healthkit` permissions. 

I get the following "warning" nothing bad happens but might want to have a way to properly tell containing view that something is above to pushed on top of you modally with out getting this: 

```
Unbalanced calls to begin/end appearance transitions for <UIViewController: 0x154d6e7a0>.
```

Thanks.

**Comment by brentvatne** [comment]
@myusuf3 - this seems like an iOS related question, not so much React Native - perhaps give StackOverflow a try :smile:

**Comment by myusuf3** [comment]
@brentvatne I totally disagree. This isn't something I am doing incorrectly. Correct me if i am wrong, but react isn't able to handle modals appearing on top of it unexpectedly granted the push is coming from some native code.

**Comment by brentvatne** [comment]
@myusuf3 - sorry I don't quite understand the issue because there is not a code example. If you can provide one that would help a lot and then I would be happy to reopen :smile:
