### ISSUE TITLE
ReactNativeBenchmarks: undefined is not an object (evaluating 'NativeModules["SQLite"][method]')]

### ISSUE THREAD

**Issue by ugendrang** [facebook/react-native#13768]
On running ReactNativeBenchmarks, got the exception   "undefined is not an object (evaluating 'NativeModules["SQLite"][method]')]"

"dependencies": {
    "react": "15.4.1",
    "react-native": "0.40.0",
    "react-native-sqlite-storage": "^3.3.1",
    "react-native-store": "^0.4.1",
    "realm": "^1.2.0",
  },

Console logs:
Running Realm.insertions
Running RNSqlite.insertions
OPEN database: test.db
'Error running tests:', { [TypeError: undefined is not an object (evaluating 'NativeModules["SQLite"][method]')]
  line: 77736,
  column: 24,

**Comment by igalmizrahi** [comment]
Why aren't you opening this issue in react-native-sqlite-storage's GitHub issues folder? You should go here first https://github.com/andpor/react-native-sqlite-storage/issues to find what you're doing wrong with that package, since SQLite is not part of react-native so the owners will not be here.
