### ISSUE TITLE
borderRadius for specific corner not working on iOS

### ISSUE THREAD

**Issue by FacuAcosta** [facebook/react-native#13760]
Hello guys!

I'm trying to style an Image component applying borderRadius for just two corners. The code I'm using to accomplish that is this:

```
imageStyle: {
		width: 100,
		height: 100,
		borderBottomLeftRadius: 5,
		borderBottomRightRadius: 0,
		borderTopLeftRadius: 5,
		borderTopRightRadius: 0,
		marginRight: 20
}
```

As you can see, I'm applying a borderRadius of 5 to both left corners  and I'm having the next result:

- **On Android:** 
![20170503_143347](https://cloud.githubusercontent.com/assets/19332669/25662942/3a69eb26-300e-11e7-9437-4fc18b2a7ca5.png)

- **On iOS:**
![screen shot 2017-05-03 at 14 28 56](https://cloud.githubusercontent.com/assets/19332669/25662953/452dfba6-300e-11e7-9559-5e169f7ef231.png)

Seems like the iOS version is not applying the values.

### Additional Information

* React Native version: 0.44.0
* Platform: iOS & Android
* Development Operating System: MacOS Sierra 10.12.4

**Comment by FacuAcosta** [comment]
To anyone having this issue, I fixed It by wrapping the Image on a View component and applying the borderRadius to It instead of directly applying It to the Image.
```
{....}
<View style={styles.imageContainerIOS}>
	<Image
	     style={{ width: 100, height: 100 }} 
	    source={dummyImage}
	/>
</View>

{...}

imageContainerIOS: {
		borderBottomLeftRadius: 5,
		borderBottomRightRadius: 0,
		borderTopLeftRadius: 5,
		borderTopRightRadius: 0,
		overflow: 'hidden',
		marginRight: 20,
	},
{...}
```

**Comment by rajapeak07** [comment]
still this issue is coming

**Comment by nmfzone** [comment]
Using `overflow: 'hidden'` on the same element that have `borderRadius` should fix this issue, I guess..

**Comment by Ehsan0007** [comment]
still issue in borderRadius

**Comment by ricardoekm** [comment]
Same issue here.

**Comment by pckz** [comment]
same issue for me

**Comment by Troepster** [comment]
add `position: "absolute"` to the containing `<View>`, that solved it for me on iOS

**Comment by wincod75** [comment]
I was applying border radius to a <Text> tag and it wasn't working until I moved it to it's parent element which is a <View> tag.

**Comment by jr2wolfgang** [comment]
For me, I just put `overflow: "hidden"` on my View container then it solves the issue.

**Comment by WhatAKitty** [comment]
Is there any reason why I put `overflow: "hidden"` fix my issue that the borderTopRightRadius and borderTopLeftRadius not working?

**Comment by yanyixin** [comment]
`overflow: "hidden"` is working

**Comment by ziyafenn** [comment]
Applying _borderTopRightRadius_ / _borderTopLeftRadius_ with or without `overflow: "hidden"` to the `<Image />`doesn't work.
