### ISSUE TITLE
product-name regex fails to match product name in `runIOS.js`

### ISSUE THREAD

**Issue by chris-yoon90** [facebook/react-native#13776]
### Description

The product-name regex in `local-cli/runIOS/runIOS.js` line 160 fails to match the product name. This is probably because there is a `$` to match the end of the string, but there is no guarantee that the product name string (which is in format of `export FULL_PRODUCT_NAME=Test.app`) is at the end of the `buildOutput` string.

Referencing pull-request: #13001, as it seems relevant to this issue.

### Reproduction Steps and Sample Code
Please refer to the below screenshot. Below shows that the regex matches when the product name string is at the end of the line.

<img width="666" alt="screen shot 2017-05-04 at 2 47 26 am" src="https://cloud.githubusercontent.com/assets/2847067/25698545/22cdbbb2-3074-11e7-92fd-e658c48d1953.png">

 The next screenshot does not have any match because the product name string is not at the end of the line.

<img width="667" alt="screen shot 2017-05-04 at 2 46 57 am" src="https://cloud.githubusercontent.com/assets/2847067/25698529/143fffce-3074-11e7-8a7e-016b7ef8abce.png">

### Solution

Fix the regex so that it doesn't assume that the product-name string is at the end of the `buildOutput` string.

### Additional Information

* React Native version: 0.44.0
* Platform: iOS
* Development Operating System: MacOS
* Dev tools: iOS simulator

**Comment by chris-yoon90** [comment]
Regex is missing multi-line flag so that's probably why it's not matching.

**Comment by dkpalmer** [comment]
multi-line is indeed the issue. I put a PR up at https://github.com/facebook/react-native/pull/13826.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/product-name-regex-fails-to-match-product-name-in-runiosjs
