### ISSUE TITLE
Cache downloadBoost file

### ISSUE THREAD

**Issue by stereodenis** [facebook/react-native#13773]
### Description

When I build my project for release — every time it downloads boost

### Reproduction Steps and Sample Code

```
# react-native/ReactAndroid/build.gradle
task downloadBoost(dependsOn: createNativeDepsDirectories, type: Download) {
    // Use ZIP version as it's faster this way to selectively extract some parts of the archive
    src 'http://mirror.nienbo.com/boost/1.57.0/boost_1_57_0.zip'
    // alternative
    // src 'http://mirror.nienbo.com/boost/boost_1_57_0.zip'
    onlyIfNewer true
    overwrite false
    dest new File(downloadsDir, 'boost_1_57_0.zip')
}
```

./gradlew assembleRelease 
:ReactAndroid:downloadBoost 

### Solution

It will be cool to cache downloaded files

### Additional Information

* React Native version: 0.33.0
* Platform: Android
* Development Operating System: Mac
* Dev tools: Terminal

**Comment by stereodenis** [comment]
I'm tired of downloading a file
> Building 82% > :ReactAndroid:downloadBoost > 34,11 MB/105,37 MB downloaded

**Comment by hramos** [comment]
It's not clear to me, from the issue description, what sort of impact this has and why it should be changed. Seems like if downloading this file repeatedly is a problem, a simple PR can be provided to cache the file.

**Comment by rzsombor** [comment]
I think that this issue is resolved now. 

After deleting the downloaded boost file (at the time of writing, on master this is '/react-native/ReactAndroid/build/downloads/boost_1_63_0.tar.gz'), repeated executions of this task will realize that it's already been downloaded.

On clean run:
```
 ./gradlew :ReactAndroid:downloadBoost
Incremental java compilation is an incubating feature.
:ReactAndroid:createNativeDepsDirectories UP-TO-DATE
:ReactAndroid:downloadBoost
Invalid cookie header: "Set-Cookie: logged_in=no; domain=.github.com; path=/; expires=Sun, 04 Oct 2037 11:18:53 -0000; secure; HttpOnly". Invalid 'expires' attribute: Sun, 04 Oct 2037 11:18:53 -0000
Download https://github.com/react-native-community/boost-for-react-native/releases/download/v1.63.0-0/boost_1_63_0.tar.gz

BUILD SUCCESSFUL

Total time: 33.848 secs
```

After first run:
```
./gradlew :ReactAndroid:downloadBoost
Incremental java compilation is an incubating feature.
:ReactAndroid:createNativeDepsDirectories UP-TO-DATE
:ReactAndroid:downloadBoost UP-TO-DATE

BUILD SUCCESSFUL

Total time: 4.943 secs
```

Head at: eae4fe810f43266ee54a3bb89558621324d7a326

**Comment by hramos** [comment]
This was fixed recently.
