### ISSUE TITLE
[TextInput] Changing keyboardType dynamically does not change keyboard layout.

### ISSUE THREAD

**Issue by joonhocho** [facebook/react-native#13782]
### Description

When changing `keyboardType` prop for `TextInput` from `phone-pad` to `default` dynamically does not change keyboard layout on iOS.

### Reproduction Steps and Sample Code

```javascript
<TextInput
  keyboardType={phone ? 'phone-pad' : 'default'}
  ...
/>
```

### Solution

Changing `keyboardType` should dynamically change keyboard layout.
Haven't tested on Android.

### Additional Information

* React Native version: 0.43.4
* Platform: iOS
* Development Operating System: MacOS
* Dev tools: Xcode

**Comment by joonhocho** [comment]
For people experiencing the same problem, the workaround is to use `key` prop to force rerendering of `TextInput`.

```javascript
<TextInput
  key={phone ? 'input-phone' : 'input-default'}
  keyboardType={phone ? 'phone-pad' : 'default'}
/>
```

This works as expected.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/textinput-changing-keyboardtype-dynamically-does-not-change-keyboard-layout
