### ISSUE TITLE
[iOS] ListView renderSectionHeader style defined is not being passed to component

### ISSUE THREAD

**Issue by kmwillia** [facebook/react-native#13788]
### Description

Styles passed to/defined on a component in renderSectionHeader are not actually applied to the component, and instead appear to be applied to some intermediate component.  This occurs regardless of whether the style defined is a plain JS Object, or a StyleSheet reference.  It only appears to occur on iOS.
Calling `StyleSheet.flatten` on `this.props.style` seems to always return `{ flex: 1 }`

### Reproduction Steps and Sample Code

Create a ListView that uses Section Headers and define renderSectionHeader to have an outermost View with `style={{ flexDirection: 'row'}}` and at least two child components.
![Example](https://raw.githubusercontent.com/kmwillia/rn-ios-sectionheader/master/Simulator%20Screen%20Shot%20May%204%2C%202017%2C%206.33.58%20PM.png)

```javascript
export default class App extends Component {
  constructor() {
    super();
    const ds = new ListView.DataSource({
      sectionHeaderHasChanged: (s1, s2) => s1 !== s2,
      rowHasChanged: (r1, r2) => r1 !== r2,
      getSectionHeaderData: (dataBlob, sectionId) => dataBlob[sectionId].meta,
      getRowData: (dataBlob, sectionId, rowId) => dataBlob[sectionId].rows[rowId]
    });
    this.state = {
      dataSource: ds.cloneWithRowsAndSections(data, dataSections, dataRows)
    };
  }

  render() {
    return (
      <ListView
        style={{ paddingTop: 20 }}
        dataSource={this.state.dataSource}
        renderRow={(rowData) => <ListViewRow label={rowData} style={styles.rowContainer} />}
        renderSectionHeader={(sectionData) => <ListViewSection label={sectionData} style={styles.sectionContainer} />}
      />
    );
  }
}
        // renderSectionHeader={(sectionData) => <View style={styles.sectionContainer}><Text>{'A'}</Text><Text>{'B'}</Text></View>}

class ListViewRow extends Component {
  render() {
    return (
      <View style={this.props.style}>
        <Text>{this.props.label}</Text>
      </View>
    );
  }
}

class ListViewSection extends Component {
  render() {
    console.log('style', this.props.style, StyleSheet.flatten(this.props.style));
    return (
      <TouchableHighlight onPress={this._onPress}>
        <View style={this.props.style}>
          <Text>{'Left'}</Text>
          <Text>{this.props.label}</Text>
          <Text>{'Right'}</Text>
        </View>
      </TouchableHighlight>
    );
  }

  _onPress() {
    console.log('press');
  }
}

const styles = StyleSheet.create({
  rowContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    padding: 16,
    backgroundColor: '#fffff8',
    borderBottomColor: '#757575',
    borderBottomWidth: StyleSheet.hairlineWidth
  },
  sectionContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
    borderBottomColor: 'orange',
    borderBottomWidth: 1,
    backgroundColor: '#bdbdbd'
  }
});

const data = {
  section1: {
    meta: 'Fruits',
    rows: ['Apple', 'Banana', 'Cherry']
  },
  section2: {
    meta: 'Animals',
    rows: ['Alligator', 'Bonobo', 'Chinchilla', 'Dingo', 'Emu', 'Feraligatr', 'Giraffe', 'Horse']
  },
  section3: {
    meta: 'Houses',
    rows: ['Doll', 'Toll', 'White']
  }
};

const dataSections = ['section1', 'section2', 'section3'];

const dataRows = [[0, 1, 2], [0, 1, 2, 3, 4, 5, 6, 7], [0, 1, 2]];
```
Code can also be seen [here](https://github.com/kmwillia/rn-ios-sectionheader).

### Solution

Components returned by renderSectionHeader with defined style attributes should on iOS receive those styles the same as Android.

### Additional Information

* React Native version: 0.44.0
* Platform: iOS
* Development Operating System: MacOS Sierra 10.12.4
* Dev tools: Xcode 8.3.2

**Comment by itneste** [comment]
yes,it works fine on android,but flexflexDirection:'row' not work on ios.

**Comment by windhost** [comment]
same problem +1

**Comment by jeanregisser** [comment]
Same here with RN 0.45-rc.2

One workaround is to wrap the section header into another `<View />` so the component which has `flexDirection: row` is not the first one.

@janicduplessis could this be caused by the changes for the new sticky headers implementation?

**Comment by SniperAK** [comment]
same problem too.

but i solved wrapped sectionHeader with View using flex:1. It's works fine for me.

I tried before section header`s root View style has flexDirection:'row' style but it was not working. 
So i used wrapped root View. it will be solve problem but not correct answer.

i think section header inside static renderer made those problem.

**Comment by hramos** [comment]
Does this still reproduce using FlatList? ListView is deprecated.

**Comment by kmwillia** [comment]
Sorry for the late reply,
As far as I can tell this is not an issue with FlatList or SectionList.
Thanks
