### ISSUE TITLE
SectionList renderSectionFooter doesn't render for empty sections

### ISSUE THREAD

**Issue by Ashoat** [facebook/react-native#13784]
### Description

Whereas renderSectionHeader renders for empty sections, renderSectionFooter does not. I'm seeing this on RN master (renderSectionFooter isn't in 0.44.0).

### Reproduction Steps and Sample Code

```js
renderItem = (row) => {
  return (
    <Text>{"item " + row.item.key)}</Text>
  );
}

renderSectionHeader = (row) => {
  invariant(row.section.key, "should be set");
  return (
    <Text>{"header " + row.section.key)}</Text>
  );
}

renderSectionFooter = (row) => {
  invariant(row.section.key, "should be set");
  return (
    <Text>{"footer " + row.section.key)}</Text>
  );
}

render() {
  const sectionListData = [
    { data: [ { key: "item1" }, { key: "item2" } ], key: "section1" },
    { data: [ { key: "item3" } ], key: "section2" },
    { data: [ ], key: "section3" }, // empty section
    { data: [ { key: "item4" }, { key: "item5" } ], key: "section4" },
  ];
  return (
    <SectionList
      sections={sectionListData}
      renderItem={this.renderItem}
      renderSectionHeader={this.renderSectionHeader}
      renderSectionFooter={this.renderSectionFooter}
    />
  );
}
```

### Solution

Either make a clarification in docs about the distinction between `renderSectionHeader`/`renderSectionFooter`, or decide on a shared behavior for the two. If I was deciding, I'd probably make them both appear for empty sections.

### Additional Information

* React Native version: master only
* Platform: iOS definitely, I can't get Android to build on master...
* Development Operating System: macOS Sierra 10.12.4

**Comment by Ashoat** [comment]
cc @sahrens

**Comment by Ashoat** [comment]
Somewhat related - `scrollToLocation` does not take `renderSectionFooter` into account.

**Comment by calebmer** [comment]
@Ashoat what precisely do you mean by “Somewhat related - `scrollToLocation` does not take `renderSectionFooter` into account?” Could you create an image or video describing the behavior you are encountering?

**Comment by Ashoat** [comment]
@calebmer - my apologies, I made that comment before actually testing anything (I was just reading the source of `scrollToLocation`). After reading the source a bit more, I can see that `renderSectionFooter` is handled as part of the last `ItemWithSeperator`'s render, which explains why `scrollToLocation` doesn't bother to consider it when calculating the flattened index.

(In contrast, I definitely *did* test the bug I originally reported :) )

**Comment by calebmer** [comment]
@Ashoat sounds good. The original bug is being worked on 👍
