### ISSUE TITLE
How to promote a pull request?

### ISSUE THREAD

**Issue by guysegal** [facebook/react-native#13781]
Hey,
I've opened a pull request 18 days ago, and I didn't got any response.. exepct from the bot.. :(

https://github.com/facebook/react-native/pull/13356

What is defined as a reasonable time to get some feedback to the PR? I'm not talking about merging it, just getting some input about it (and then hopefully - merge)

Is there something I can do to promote the PR?

Thanks, 
Guy

**Comment by codebymikey** [comment]
+1

**Comment by thotegowda** [comment]
+1

**Comment by vonovak** [comment]
@guysegal there are 1249 issues, many of them questions which aren't really issues and 220 PRs. This means that things simply take time.

**Comment by guysegal** [comment]
I understand that, I just wanted to know if I should expect a response within weeks or months.
This PR solves a problem for me and probably for others, however until it's merged the solution is not optimal.

I'm asking this question because in the future I'd like to understand weather a PR is the right approach for our company

**Comment by vonovak** [comment]
@guysegal sometimes it goes fast (like PRs for the docs) but mostly weeks/months.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/how-to-promote-a-pull-request
