### ISSUE TITLE
error: bundling: UnableToResolveError

### ISSUE THREAD

**Issue by 550609334** [facebook/react-native#13797]
logcat info:
Loading dependency graph, done.
error: bundling: UnableToResolveError: Unable to resolve module `react/lib/ReactDebugCurrentFrame` from `/Users/liuzipeng/Documents/AndroidWorkspace/ReactDemo/node_modules/react-native/Libraries/Renderer/src/renderers/shared/fiber/ReactFiberContext.js`: Module does not exist in the module map or in these directories:
  /Users/liuzipeng/Documents/AndroidWorkspace/ReactDemo/node_modules/react-native/node_modules/react/lib
,   /Users/liuzipeng/Documents/AndroidWorkspace/ReactDemo/node_modules/react/lib

phone screen info:
Unable to download JS bundle

**Comment by chmiguel** [comment]
i have the same issue :( on windows 7, react-native v0.44.0 react-native-router-flux v 3.38.0 react v15 node 6

**Comment by athaseen** [comment]
+1
same issue, have config similar to @chmiguel

**Comment by JulianKingman** [comment]
using `react-native-git-upgrade` worked for me.

**Comment by zhangyao0328** [comment]
same problem，The solution?

**Comment by JulianKingman** [comment]
Npm i -g react-native-git-upgrade && react-native-git-upgrade

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/error-bundling-unabletoresolveerror
