### ISSUE TITLE
Cannot bring up the In-App Developer Menu on iOS simulator or on device after upgrading to 0.43.4

### ISSUE THREAD

**Issue by linamm** [facebook/react-native#13799]
### Description

**Steps**

- upgrade react-native to 0.43.4
- restart the packager
- rebuild debug version of the app for simulator or device

**Observations**

- Shake the device cannot bring up the developer menu
- In simulator, Command + R works for reload, but, Command + D doesn't work, Hardware -> Shake gesture doesn't work.
 
- Revert to version 0.42.3, the Develper Menu works as expected again. 
- Developer Menu in Android app works as expected in version 0.43.4.

**Environment**
* React Native version: 0.43.4
* Platform: iOS
* Development Operating System: MacOS
* Dev tools: Xcode

**Comment by Exilz** [comment]
Are you using cocoapods ? If so you need to add `DevSupport` as a subspec of `React` like so

```
  pod 'React', :path => react_path, :subspecs => [
    'Core',
    'DevSupport', # Devmenu
    'RCTWebSocket', # needed for debugging
   # everything else you need...
  ]
```

**Comment by linamm** [comment]
You are right! Thank you very much. It is working now :)

**Comment by anyueruhui** [comment]
I've found it very hardly, THANKS FOR U!

**Comment by W0LFMAN** [comment]
React native 0.48.1
Platform - IOS
Development Operating System: MacOS
Dev tools: Xcode

 - it doesn't work for me. DevSupport in subspecs in podfile.
