### ISSUE TITLE
Missing Navigator page

### ISSUE THREAD

**Issue by Spookykiller** [facebook/react-native#13804]
[React Native Navigator](https://facebook.github.io/react-native/docs/navigator.html) isn't a page anymore. However at [React Native Navigation](https://facebook.github.io/react-native/docs/navigation.html) under heading **Navigator** still is a link towards the React Native Navigator.

**Comment by vonovak** [comment]
You can fix the problem here https://github.com/facebook/react-native/blob/master/docs/Navigation.md and make a PR :)
