### ISSUE TITLE
People are filing issues instead of getting their questions answered

### ISSUE THREAD

**Issue by dobrienlzd** [facebook/react-native#13802]
I realize some questions might lead to issues but there are lots of open 'issues' here that are really questions about React Native. There needs to be some effort to understand the reason why? Posting questions to stackoverflow.com as recommended is not yielding answers or even comments to legitimate questions.  This is kind of amazing given how popular React and React Native actually are.  I would recommend that a dedicated newsgroup for questions related to RN be setup/shared. Or if stackoverflow is going to continue to be used there needs to be a more active presence from React Native experts.  I posted a question there about Fragment support for example, and there was no response at all. Not even a quick comment.  I could open a third ticket here, but to me it makes more sense to handle this through a more proactive question and answer forum.  The issue here is there really is no adequate forum for getting our questions answered re RN, so people are turning to opening issues. Perhaps there is some facebook group I have not heard of?

**Comment by hey99xx** [comment]
Frankly, I only answer questions here and never at Stackoverflow or elsewhere. The code is right here, I can just press "T" and jump to the file when I'm investigating an error. Also, the conversation on Github is so much nicer compared to toxic Stackoverflow where mods will lock your question as soon as they mistakingly believe it's a duplicate of an unrelated issue. And lastly, all solutions I've found are indeed on Github issues, so I wouldn't go anywhere else as it stands. There are also some Slack groups I think, but I never tried them.

**Comment by dobrienlzd** [comment]
Ok, I'm closing this. If it gets answered here better than not at all!  Mostly I just think SA is totally not working.
