### ISSUE TITLE
Document supported image formats for Image component

### ISSUE THREAD

**Issue by brentvatne** [facebook/react-native#13806]
It isn't very clear from reading the documentation what image formats are supported by the Image component. We should be very explicit about it to avoid issues like https://github.com/react-community/create-react-native-app/issues/194

**Comment by LumisD** [comment]
@brentvatne I upgrated React Native from 0.43 to 0.44 and images disappeared in my projects.
They have paths like this: 
` <Image
        source={require('../../../resources/logo-bookings.png')}
   />`
I checked Image component with http source and it works fine
`source={{uri: 'https://facebook.github.io/react/img/logo_og.png'}}`

What could happen?

**Comment by franciscofsales** [comment]
@brentvatne not sure this was exactly the way to go but I opened #13807.
I was unsure about tiff and psd but used [this](https://github.com/facebook/react-native/blob/66d51bb5d1f7df07694698094b2dbe6a6642a05c/packager/src/Bundler/util.js#L37-L43) as a reference.

Please let me know how I can help further. Thanks

**Comment by brentvatne** [comment]
@franciscofsales - can you test each of those on iOS and Android?

**Comment by franciscofsales** [comment]
@brentvatne sure, will do 👍

**Comment by franciscofsales** [comment]
@brentvatne done and documented on PR. thanks.

**Comment by fogmoon** [comment]
@brentvatne 
ico format not support in android in own app

@franciscofsales 
Could you add test about ico format

**Comment by zhuyifan2013** [comment]
@fogmoon  I face the same problem!

**Comment by franciscofsales** [comment]
@fogmoon and @zhuyifan2013, as seen [here](https://github.com/facebook/react-native/blob/66d51bb5d1f7df07694698094b2dbe6a6642a05c/packager/src/Bundler/util.js#L37-L43), ico is not handled as a picture, therefore should not be supported. Just in case I'm missing something, I gave it a try with a real device Android and iOS simulator and both failed. 

@fogmoon I don't have my iOS device on me for the next week, please submit a PR if you have the chance to do so and think its relevant [here](https://github.com/franciscofsales/react-native-image-format-test), since its already tagged on the documentation PR.

Thanks

**Comment by fogmoon** [comment]
@franciscofsales 
Thanks for your helpful information.

I also just used iOS simulator (iOS 10) which can render ico image correct. By your ref code, this is impossible.  So I am a little confused.

Whatever,  in my opinion, ico should be recognized as image format for the MIME type `image/x-icon`.  And now I had to think other method for my crawler-like app to show friendly `favicon.ico` of the websites.

@brentvatne
@franciscofsales  
Could you please suggest a workaround to show `favicon.ico` ? Or it just can not to make it.

Thanks.

**Comment by franciscofsales** [comment]
@fogmoon were you able to render the ico with react-native Image correctly on the iOS simulator?

I tried this setup and it just failed.
```
React-native version: 0.44.0
fresco version: 1.0.1
```

Also, I found this (issue)[https://github.com/facebook/fresco/issues/868] that is still open regarding fresco supporting `ico`.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/document-supported-image-formats-for-image-component
