### ISSUE TITLE
Emojis are not properly centered in text

### ISSUE THREAD

**Issue by brendan-rius** [facebook/react-native#13805]
### Description

It looks like there is an empty space to the right of a <Text> when it is made of emojis

Here is my code:

```js
const style = {
        marginTop      : 14,
        fontSize       : 43,
        backgroundColor: 'transparent',
        textAlign      : 'center',
        marginBottom   : 35,
 }

<Text>😍</Text>
```

And here how it renders: 

<img width="55" alt="screenshot 2017-05-05 17 14 05" src="https://cloud.githubusercontent.com/assets/5605817/25752196/d40b448c-31b7-11e7-9319-93192f9a8c92.png">

as you can see there is a space on the right which makes it very ugly

### Additional Information

* React Native version: 0.43.1
* Platform: iOS (not tested with Android)
* Development Operating System: MacOS

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/emojis-are-not-properly-centered-in-text

**Comment by brendan-rius** [comment]
This issue is still happening on RN 0.46 unfortunately and I do not know of any PR to solve it
