### ISSUE TITLE
[JS] Implement the warning given when trying to render the global Image when trying to render other commonly used components

### ISSUE THREAD

**Issue by ccheever** [facebook/react-native#1380]
It's very helpful that if you forget to unpack `Image` from `require('react-native')`, you get an error message explaining exactly what the problem is.

If you make the same mistake with any other component provided by react-native, you get a much more cryptic message that doesn't really identify the problem at all. It seems like it would be useful to implement the same thing as `Image` for `ListView`, etc.

I can implement and submit a PR if this is considered something good to add.

**Comment by brentvatne** [comment]
This is an interesting idea. As far as I know, this happens for `Image` and `Text` because those are actually available in the browser environment, whereas others are not.

**Comment by brentvatne** [comment]
@vjeux @spicyj - any thoughts on this?

**Comment by vjeux** [comment]
Can you show what the error is? There's no reason it shouldn't be clear. It should be something along the lines of `variable ListView is not defined` or something

**Comment by brentvatne** [comment]
![](http://url.brentvatne.ca/1fOaE.png)

vs

![](http://url.brentvatne.ca/SCGa.png)

**Comment by vjeux** [comment]
Cannot find the variable ListView seems super explicit to me. This is the same exception you've got when you use a variable you don't have.

Maybe I should update the message on Image and Text to be "Can't find variable Text" so that both look the same?

**Comment by brentvatne** [comment]
I think the line that @ccheever is referring to that seems most useful is "You probably forgot to require x"

**Comment by vjeux** [comment]
Hmm, Can't find variable X is the error message from JavaScriptCore. v8 has the wording: "Uncaught ReferenceError: ListView is not defined"

I'd rather not mess up with those as they are from js itself and you're likely to see them all the time

**Comment by brentvatne** [comment]
:+1:
