### ISSUE TITLE
navigation problems / reintroduce NavigationExperimental?

### ISSUE THREAD

**Issue by vonovak** [facebook/react-native#13810]
React Native does a great job of abstracting away the platform the code is running on. In my experience, however, **RN has one long-term problem, which is navigation**.

I started working with RN over a year ago, soon before NavigationExperimental was introduced in the core. Knowing that the original navigators were going to be deprecated I tried to avoid them and used `react-native-router-flux` and soon switched to `ex-navigation` because it was a better solution and would get a long-time support. Then apparently ex-navigation was going to be replaced by a new library (react-navigation) **in November** (that was the original ETA [as can be seen here](https://github.com/facebook/react-native/wiki/Roadmap/f298819a3e3e8e4ba6a70def30f1773754218c25)). The ETA then moved to December and January (first release of react-navigation was at the end of January).

Now in May, react-navigation is still in beta and seems to be far from stability - although I hoped it would be [stable by now](https://github.com/react-community/react-navigation/issues/723) - with [one commit in the past week](https://github.com/react-community/react-navigation/commits/master).

So we're in a situation when most people probably use old navigators or ex-navigation (or the wix navigator but that is an independent one) and react-navigation is not production-ready. And yet, the latest RN - 0.44 - comes without NavigationExperimental just one month after it was deprecated. IMHO, this behaviour really hurts the developer experience and is kind of frustrating. I'd really appreciate things not getting removed when there is no real replacement available. (maybe you will want to comment on this @ericvicenti ) Sure, I can copy over the old NavigationExperimental but wouldn't it be better not to remove it in the first place..?

What I mainly want to say is that I appreciate the hard work that is being put into RN, and I believe I will speak for a lot of developers (share your opinions in the comments) when I say that navigation is the weakest part of react native and it deservers much, much more attention from people at facebook. That's it.

Thanks!

*edit:* you should be able to find [NavigationExperimental on npm](https://www.npmjs.com/package/navigation-experimental-fork) as `navigation-experimental-fork` and import it like `import NavigationExperimental from 'navigation-experimental-fork'`

**Comment by chris-yoon90** [comment]
I have to say I totally agree with this. I quite don't understand the reasoning behind removing the whole Navigator when the alternative that the documentation suggest is react-navigation, which is far from stable release.

**Comment by gluwa** [comment]
I assume they believe `react-navigation` is stable? `Once stable, NavigationExperimental will be deprecated in favor of React Navigation`, says the React Navigation document. Is this true?

**Comment by Proberts** [comment]
Of the other two suggested replacements, http://airbnb.io/native-navigation/ is nowhere near production ready according to their docs, and while https://github.com/wix/react-native-navigation says it's stable, the docs say "We are currently redesigning and rewriting this project" .

**Comment by mehcode** [comment]
React Router is production ready and as of v4 has strong support for React Native.

https://reacttraining.com/react-router/

**Comment by gluwa** [comment]
@mehcode React Router is great, but it doesn't have built-in transition animation, which is quite critical for mobile application.

**Comment by mehcode** [comment]
Not _yet_, correct. But all the building blocks are there. I'm using it with transition animations. The docs on the website are very helpful in respect to that.

It'd be simple to make an `<Animated.Switch />` component for react-router (native).

**Comment by ryankask** [comment]
I tried to reuse `Transitioner` and some other components from react-navigation but I saw that `navigationState` became `navigation.state` and stuff like `NavigationCardStackPanResponder` was gone so I didn't want figure out what needed to change.

Instead, I created https://github.com/longpond/react-native-navigation-experimental. I'm not sure if I packaged it in the best way and I haven't published it to npm (react-native-navigation-experimental is taken) but I'm using it in a client's app with `yarn add git+ssh://git@github.com/longpond/react-native-navigation-experimental.git` and `import NavigationExperimental from 'react-native-navigation-experimental';`. 

Ideally FB would publish it in their [archive](https://github.com/facebookarchive).

**Comment by ryankask** [comment]
It would be great if FB could publish NavExp to the [archives](https://github.com/facebookarchive) although it would require maintenance for deprecated features (eg `View.propTypes` -> `ViewPropTypes`). Or the community could maintain a fork.

**Comment by vonovak** [comment]
@mehcode I think it is clear that the RN team is promoting react-navigation as the go-to navigation solution for RN, so in this thread I am not looking for any alternatives to it (and not even React Router is not quite there yet as you pointed out).
I'm trying to say that imo navigation is a long-term pain and that react-navigation should be more mature before its predecessor gets removed from the core.
@ryankask a fork is available in the first post.

**Comment by ryankask** [comment]
Thanks. I actually [created my own fork](https://github.com/longpond/react-native-navigation-experimental) before I saw this issue. 😄

@vonovak Just curious -- does the `require('clamp')` in the pan responders work?

**Comment by vonovak** [comment]
I had to do some manual fixes of the imports, but haven't done anything about `clamp`. I need navigation experimental for ex-navigation, might be that ex-navigation doesn't need that and even my fork is broken.

**Comment by ryankask** [comment]
Thanks. Yes, it may be the case that the fork is broken for those that don't use ex-navigation which depends on clamp.

**Comment by nix23** [comment]
Faced same issue. If you are experiencing issues with exnavigation on RN 0.44( because NavExperimental is removed) you can just install exnavigation 3.0.0.(It contains removed NavExp package)

**Comment by hramos** [comment]
Navigation has been at the top of our feature requests on Canny for a long time. I don't think there's necessarily going to be one solution that works for everybody, therefore navigation is something that is best pulled in via an external dependency rather than being part of the core RN library.

If you're looking for the old NE, it's on npm (see edit on the original post). I'm going to close this as we'd like to keep feature requests out of the issue tracker, but feel free to move the conversation over to Canny which is what we use to track the community's pain points.
