### ISSUE TITLE
"borderWidth" does't applied for ListView on Android

### ISSUE THREAD

**Issue by valeriik** [facebook/react-native#13813]
### Description

"borderWidth" style prop does't applied for "ListView" component on Android (but works on iOS).

![2017-05-06 11 25 56](https://cloud.githubusercontent.com/assets/24571089/25771192/33ba2902-3253-11e7-9783-481f0826bc7a.png)
![2](https://cloud.githubusercontent.com/assets/24571089/25771199/7842964a-3253-11e7-8448-6f894a0b8e7d.jpg)

### Reproduction Steps and Sample Code

```
Import ...
class Test extends PureComponent {
...
  render() {
    return (
      <View style={{flex:1}}>
        <ListView 
          style={{borderWidth:10, borderColor:'black',backgroundColor:'red',}}
          ...
        </ListView>
      </View>
    )
  }
}
```

### Solution

Need to be fixed (or explain why border doesn't show on Android).

### Additional Information

* React Native version: [0.42.3]
* Platform: [Android]
* Development Operating System: [MacOS]

**Comment by dobrienlzd** [comment]
Please explain why you think borderWidth is the correct parameter? ReactNative used flexbox etc.  so this might not be how it should be specified. You might also consider importing a ListItem from react native elements module.  Try that and let us know what happens. Thanks!

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/borderwidth-doest-applied-for-listview-on-android
