### ISSUE TITLE
Please add Navigator removal to breaking changes in release notes for 0.44

### ISSUE THREAD

**Issue by Proberts** [facebook/react-native#13815]
Can hopefully benefit other developers trying to schedule RN rollup.

**Comment by richardgirges** [comment]
I second this. I always check the release notes for breaking changes before upgrading. Had to roll back to a previous version after upgrading to 0.44 and discovering that some (or maybe all?) of NavigationExperimental's components were removed.

**Comment by vonovak** [comment]
@richardgirges I put a navigationExperimental fork [on npm](https://www.npmjs.com/package/navigation-experimental-fork)

**Comment by markgoodyear** [comment]
Happened to me also. Rolled back as it was unexpected.

**Comment by hramos** [comment]
Done.
