### ISSUE TITLE
[IOS FlatList] Horizontal arrangement of multiple FlatList, and each width is the width of the screen. out of screen FlatList don't render header and item.   

### ISSUE THREAD

**Issue by bluedreamfly** [facebook/react-native#13812]
![](http://o8695iplk.bkt.clouddn.com/flatlist.png)
[demo source](https://github.com/bluedreamfly/rn_meituan/blob/master/app/modules/nearby/index.js#L77)

**Comment by sahrens** [comment]
Hey, thanks for reporting this issue!

have you tried setting removeClippedSubviews={false}? We're changing it to false by default, but you didn't list what version you're running. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!
