### ISSUE TITLE
How to pass nested objects across bridge? WritableArray?

### ISSUE THREAD

**Issue by dobrienlzd** [facebook/react-native#13821]
I need to pass over bridge a nested Java Object.  

public class MyObject {
        String name;
        Date   date;
       ArrayList<ListItem>  someItems;
}

Do I need to use WritableArray for this?  I would like to pass across the whole object at once in the callback across the bridge. Array will pass elements and I already have this setup, but I need to pass the whole object. How can this be done?  Lastly would it not be better just to serial the whole object to json string and just pass that across? Will that work? or is it not recommended?

**Comment by vonovak** [comment]
You should be able to use WritableMap with a WritableArray inside. Date probably has to be converted to string. Serializing to JSON and then parsing it on the other side will also work. It's mostly a matter of what your preference is. FYI stackOverflow would be a better place for this.

**Comment by dobrienlzd** [comment]
confirmed. A WritableMap can contain a WritableArray.   issue closed.
