### ISSUE TITLE
Missing documentation on View prop 'elevation'

### ISSUE THREAD

**Issue by JReinhold** [facebook/react-native#13823]
### Description

Documentation on what styles can be given to a View have been removed in v0.44, and is now replaced with the simple line ```style?: stylePropType```.  (I don't know if this is on purpose or not, but it's rather confusing, and not very informative)

As a consequence, documentation on style props mut now be found under [Shadow Props](https://facebook.github.io/react-native/docs/shadow-props.html) and 
[Layout Props](https://facebook.github.io/react-native/docs/layout-props.html).
**None of these pages include documentation on the Android-only `elevation` prop, that handles shadows on Android.**

### Reproduction Steps and Sample Code

See [0.43 View style prop](http://facebook.github.io/react-native/releases/0.43/docs/view.html#style) vs [0.44 View style prop](http://facebook.github.io/react-native/releases/0.44/docs/view.html#style)

### Solution

It would be misleading to document the elevation prop on the Shadow Props page, as the props listed there are suppose to go into a StyleSheet, while the elevation is a prop on View. Instead I would recommend documenting the prop on the [View documentation](http://facebook.github.io/react-native//docs/view.html).

### Additional Information

* React Native version: 0.44
* Platform: Docs
* Development Operating System: Not applicable
* Dev tools: Not applicable

**Comment by Sherman-Chen** [comment]
bump

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/missing-documentation-on-view-prop-elevation
