### ISSUE TITLE
Getting started not working

### ISSUE THREAD

**Issue by manugb** [facebook/react-native#13827]
### Description

I follow all the steps in the getting started section, hoping it will render the app as displayed there.
But the end the application throw an error. runApplication. 

Running `react-native run-android` installed the app but after doing that it "shutdowns" letting the terminal taking contorl, instead of keeping the process running. (I dunno actually but maybe a js server is started and the app need that to be up)

### Reproduction Steps and Sample Code

Just follow the getting started section

### Solution

So after running `react-native run-android` and getting the error when the app is running.
I try running `react-native start` and that solved the problem. When the command finished building the index.android.js file, the app render correctly on the phone.

### Additional Information

* React Native version: 2.0.1
* Platform: android
* Development Operating System: linux

**Comment by hramos** [comment]
A fix is in #14040
