### ISSUE TITLE
How to hide the default backButtonIcon in NavigatorIOS?

### ISSUE THREAD

**Issue by faithfe** [facebook/react-native#1383]
My code is:

```
<NavigatorIOS 
        ref='nav'
        style={styles.container}
        tintColor={'#FFFFFF'}
        barTintColor={'#009FDE'}
        titleTextColor={'#FFFFFF'}
        initialRoute={{
          title: 'Title',
          component: List,
          backButtonTitle: ' ',
          backButtonIcon: require('image!back_button'),
          leftButtonIcon: require('image!back_button'),
          rightButtonTitle: 'Right',
          onRightButtonPress: this._onRightButtonPress,
          onLeftButtonPress: this._onLeftButtonPress

        }}/>
```

I want to use my own back icon ('back_button') for backButtonIcon, but there are two back icons in the next page. How to hide the default one? tks

![2015-05-23 10 56 32](https://cloud.githubusercontent.com/assets/5271066/7784627/4150cb34-019f-11e5-9dfb-be263c0d620c.png)

**Comment by brentvatne** [comment]
Hi @faithfe - if you push a new route, you need to specify what the back button icon should be in that as well - not just in the `initialRoute`. Also, your left button looks like it also has the back button image.

If the above doesn't help, can you post a runnable example on https://rnplay.org/ please?

**Comment by faithfe** [comment]
thanks @brentvatne, it works!
Another question, i fail to  use uri to locate the icon, but use 'require' is ok:
backButtonIcon: require('image!back_button'),
leftButtonIcon: {uri: 'http://xx/back_button.png'},

**Comment by ide** [comment]
@faithfe, only local images are supported with NavigatorIOS.

**Comment by faithfe** [comment]
@ide , ok, tks!

**Comment by richarddewit** [comment]
I still have this issue.

Both on my `initialRoute` and the next pushed route, I set the `backButtonIcon` to my desired image.

``` es6
backButtonTitle: " ",
backButtonIcon: require('image!ButtonBack'),
````

But this comes out:
![image](https://cloud.githubusercontent.com/assets/7933750/10754361/51d6ad5c-7c97-11e5-81de-ed6d41834b5b.png)

Although when I omit the Back button, and use a Left button instead, the issue is solved, but I have to make my own "Navigate back" function (`this.refs.nav.pop()`) which IMO shouldn't be the way it's intended.

``` es6
leftButtonTitle: "",
leftButtonIcon: require("image!ButtonBack"),
onLeftButtonPress: this.refs.nav.pop,
```

**Comment by rmdort** [comment]
I am facing the same problem as @richarddewit 

`backButtonIcon, backButtonTitle` is not working as expected. The left arrow is always visible. New routes with custom backButtonIcon or backButtonTitle doesnt show

```
this.props.navigator.push({
	title: 'Next',
	component: Next,
	backButtonIcon: require('./../img/Back.png')	
})
```

**Comment by ide** [comment]
I believe this is how UIKit behaves, though if there's a way to override the back button icon with UINavigationController please send a PR.
