### ISSUE TITLE
How to update an attribute of an object in RN.

### ISSUE THREAD

**Issue by Symous** [facebook/react-native#13833]
```js
var obj = {[id:1,status:false],{id:2,status:false}}
```
Is there any way I can change the 1st status from false to true directly?Thanks. :-)

**Comment by dobrienlzd** [comment]
Sure:

obj[0].status = true;   // obj[0] takes the first element of the array.
if this does not work than try:
obj[0] = {id:1, status: true};  // check if this changes the value.

**Comment by Symous** [comment]
@dobrienlzd Thanks for your reply,I didn't describe what I want.
Actually, I want to change the attribute in setState method;
```
this.setState( //Change attribute value directly here )
```

AFAIK,there are 2 way to do this:
1. Object.assign();
2. React.addons.update();

But I can not figure out how to use this.any idea about that? thank u.

**Comment by dobrienlzd** [comment]
No, I'm sure.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/how-to-update-an-attribute-of-an-object-in-rn
