### ISSUE TITLE
react-native run-android hangs

### ISSUE THREAD

**Issue by tuandt** [facebook/react-native#13838]
Hi you all,

My react-native worked well but suddenly I got error react-native run-android hangs

I run react-native run-android or react-native start, it hangs after display message: 

Scanning 883 folders for symlinks in ...\node_modules (48ms)

It happens to all my projects or new fresh one that created by react-native init

Please give me some advice?

### Additional Information

* React Native version: 0.44
* Platform:  Android
* Development Operating System:  Windows10
* Dev tools: Android Studio version, Android SDK version 6.0

**Comment by tuandt** [comment]
I fixed it by re-install fresh new node and react-native-cli (node version 7.0.0). Could you please close it?

**Comment by stoffern** [comment]
Close it yourself 😉
