### ISSUE TITLE
No Carthage support

### ISSUE THREAD

**Issue by ahmadmuhsink** [facebook/react-native#13835]
### Description

I use carthage as dependency manager. (CocoaPod alternative)
I add facebook/react-native as one of the dependency.

I run carthage update (similar with pod install). Its failed to build react-native because its not compatible.

```
Skipped building react-native due to the error:
Dependency "react-native" has no shared framework schemes for any of the platforms: iOS
```

### Reproduction Steps and Sample Code
use carthage as your dependency manager https://github.com/Carthage/Carthage

add this repo as dependency.
build

### Additional Information

* React Native version: 0.44
* Platform: iOS
* Development Operating System: MacOS
* Dev tools: Xcode

**Comment by jamesone** [comment]
@ahmadmuhsink Hey! Did you end up finding a way to add the fbsdk to your project without using cocoapods? 

I'm in the same boat. We're using carthage and don't want to use cocoapods for various reasons. 

However I've looked around and it looks like Facebook will not be adding Carthage support to the FBSDK. However they are adding the support for there SWIFT fbsdk package (which I don't think we can use with the react-native-fbsdk package).

**Comment by ahmadmuhsink** [comment]
@jamesone 
Hey! I use different approach for this. I need this carthage support because I want to have RN native module as library.

If you really need this carthage support you can add framework scheme by yourself, but that requires fork and will be hard to manage version.

**Comment by jamesone** [comment]
Yeah I figured 😄 How do you setup the fbsdk? Do you use cocoapods? I'm interested to know because we really need to setup the fbsdk but don't want to use cocoapods...so I'm exploring all options at the moment 👍 
@ahmadmuhsink

**Comment by jamesone** [comment]
@ahmadmuhsink Do you use the swift SDK with react-native?

**Comment by ahmadmuhsink** [comment]
@jamesone Nope, I didnt use cocoapods, fbsdk, and swift sdk.

I only use react-native, and I use it as `submodules` for my native modules bridges. https://github.com/blog/2104-working-with-submodules

**Comment by lswith** [comment]
Carthage is gaining some serious space in the dependency management of iOS apps. This should definitely move up to a higher priority.

**Comment by bootstraponline** [comment]
Agreed. Carthage support would be nice.

**Comment by CareSourceMichael** [comment]
We are considering react native but, we use carthage extensively.  When will this be available?

**Comment by CareSourceMichael** [comment]
We are considering react native but, we use carthage extensively.  When will this be available?

**Comment by blackholesoftware** [comment]
We are considering react native but, we use carthage extensively.  When will this be available?

**Comment by henrikra** [comment]
What is better about Carthage compare to CocoaPods with React Native? :D

**Comment by khawkins** [comment]
I don't think it's necessarily an issue of "better", as much as people not wanting to implement Yet Another Dependency Manager in their project if they don't have to.  CocoaPods and Carthage take very different approaches to dependency management.  As such, many teams standardize on one or the other.

If RN supported Carthage, people who have adopted Carthage as their dependency manager would not have to implement another one in the form of CocoaPods, and incur the additional maintenance overhead of another third party tool in their projects.

**Comment by dhei** [comment]
Is there any update on Carthage support?

If not, @ahmadmuhsink can you keep this issue open to track Carthage support of RN? Closed issue gets less attention.

Thanks!

**Comment by bootstraponline** [comment]
I'd also like to see this issue remain open to track Carthage support.

**Comment by ahmadmuhsink** [comment]
alright. reopen the issue.

**Comment by gianpaj** [comment]
Another vote for this (and to keep it open).
I've encountered many issues with install and linking third-party modules with and without cocoapods.
I'm sure Carthage won't fix every issue, but I feel like there has to be a better way to install native modules.

**Comment by michallaskowski** [comment]
+1, keep it open, I also would prefer to use it with Carthage.

**Comment by KarlHarnois** [comment]
Did anyone find a solution for this, we're also planning to try react-native but we are using Carthage.

**Comment by jamesrford7** [comment]
We're currently taking a hybrid Pod/Carthage approach, but are only using Pod for React Native so would be great to get everything over to Carthage

**Comment by dehlen** [comment]
why is this closed again ? Would also love to see this happen.

**Comment by LeeroyDing** [comment]
Is that a subtle way to announce that there will not be Carthage support?

**Comment by andrew-marin** [comment]
Given all the requests for this, coupled with the sheer resources FB has, I find it ridiculous this has not been implemented and is continually closed.

Even worse this has not received any feedback from the dev team one way or the other. In my opinion very unprofessional.
