### ISSUE TITLE
keyboardShouldPersistTaps naming is meaningless.

### ISSUE THREAD

**Issue by asimolmez** [facebook/react-native#13849]
### Description

ScrollView has a property `keyboardShouldPersistTaps`. When I saw this property, I thought its type is boolean.

### Solution

Maybe It can be like`keyboardPersistTapType`

**Comment by nolan-m** [comment]
It used to be a boolean, but those options have been deprecated.

**Comment by DanielMSchmidt** [comment]
@facebook-github-bot answered
