### ISSUE TITLE
upgrade to RN0.44.0 APP Exception

### ISSUE THREAD

**Issue by 759325100** [facebook/react-native#13841]
I use <code>react-native-git-upgrade</code> to RN 0.44.0.  
After the upgrade is complete,run app error  
Error infomation:  
Objects are not valid as a React child(found:object with keys {visible}).If you meant to render a collection of chhildren,use an array instead.  
Check the render method of View   

I use react-navigation.  

I need wait react-navigation upgrade too?

**Comment by 759325100** [comment]
@gabriel

**Comment by idowe** [comment]
我也遇到这个问题了，你是怎么解决的 @759325100

**Comment by hramos** [comment]
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!
