### ISSUE TITLE
borderRadius does not work on Image with "contain" resizeMode

### ISSUE THREAD

**Issue by Quilamir** [facebook/react-native#13847]
### Description

I tried making an Icon Component that simply takes an image and shows it as an icon with a round border, when i use the "contain" resizeMode for the image the broderRadius stops working and a regular (square) border is shown, if i use the "cover" resizeMode the border shows correctly with the radius.

I tried wrapping the Image with a view and put the border on the view but then the image renders on top of the view so the border is actually hidden from view

I tried putting a View inside the Image and then i got a circle on top of the image but in order to see it i need to set borderWidth and all i got was a circle at that width.

I tried putting the style on the TouchableHighlight and nothing changed

I tried using just the Image and same result

### Reproduction Steps and Sample Code
```
import React, { Component } from 'react';
import {
  StyleSheet,
  Text,
  View,
  TouchableHighlight,
  Image
} from 'react-native';

class Icon extends Component {
	constructor(props) {
		super(props)
	}

	render() {
		src = {uri: "https://www.colu.com/layout/img/colu-green.png"}
		return (
			<TouchableHighlight onPress={this.props.onPress ? this.props.onPress : ()=>{}} underlayColor="transparent" activeOpacity={this.props.opacity ? this.props.opacity : 1}>
			     <Image source={src} resizeMode="contain" style={{borderRadius: parseInt(this.props.size / 2), borderColor: this.props.color, width: this.props.size, height: this.props.size}}/>
			</TouchableHighlight>
		)
	}
}

export default Icon
```
### Solution

Please help :)

### Additional Information

* React Native version: 0.42.3
* Platform: android
* Development Operating System: Windows
* Dev tools: Android Studio

**Comment by arsen** [comment]
Duplicate: #8885

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/borderradius-does-not-work-on-image-with-contain-resizemode
