### ISSUE TITLE
React-native: tvOS How to force a Button to be focused?

### ISSUE THREAD

**Issue by BenBenz** [facebook/react-native#13855]
How to force a Button to be focused?
I have been trying to do this since several weeks

For example if I have a ListView and if I want to have a specific cell focused, how I can do that ?

There are posts on Stackoverflow but nobody knows the answer

**Comment by dobrienlzd** [comment]
Have you tried   using:https://facebook.github.io/react-native/docs/touchablehighlight.html

**Comment by BenBenz** [comment]
Yes I have tried:
https://facebook.github.io/react-native/docs/touchablehighlight.html

But nothing to set the focus on an element for Apple Tv

**Comment by dobrienlzd** [comment]
I would forget about Apple TV for a moment and just see if it is possible outside Apple TV.  Perhaps you should also consider using newer list like FlatList for example as well.

**Comment by BenBenz** [comment]
Thanks for you answer 👍 

I'm on tvOS,
I use Touchablehighlight and I know when an item is focus because OnShow is called,
But I have no idea to force a Touchablehighlight to be focused

**Comment by dobrienlzd** [comment]
I think I understand it better now. Ok, you want to almost simulate a user touch of the component. Something like that ...

**Comment by BenBenz** [comment]
Yes ! Not really a user, a user selection, when the user on tvOS move to up it select a cell, and I want to select it programatically

**Comment by BenBenz** [comment]
Do you have an idea to do that ?

**Comment by dobrienlzd** [comment]
https://facebook.github.io/react-native/docs/flatlist.html 
scrollToIndex(pos)  even though it might be on same page it might give it the highlight.
scrollToItem(params: object)

**Comment by BenBenz** [comment]
Thanks, I will try with that and update you as soon as possible

**Comment by dobrienlzd** [comment]
Also take a look at his example above in: class MyList extends React.PureComponent {
  state = {selected: (new Map(): Map<string, boolean>)};

// This deals with some of the issues surrounding FlatList. I would stick with newer list components like FlatList. ListView may be deprecated and won't get improvements.

**Comment by JulienKode** [comment]
Yes it is possible, with tvOS and react native if you want to force a focusable component to be focus you just need to set hasTVPreferredFocus to true

For example: 
		

```
    <TouchableHighlight
        hasTVPreferredFocus={true}
    	onPress={() => {}}
    >
    	<Text>Hello</Text>
    </TouchableHighlight>
```

You can see this post on Stackoverflow: 
https://stackoverflow.com/questions/43862802/react-native-tvos-how-to-force-a-button-to-be-focused/44700590#44700590

**Comment by dlowder-salesforce** [comment]
RN Apple TV author here.... @JulienKode is correct, `hasTVPreferredFocus` is the right way to do this.

**Comment by dlowder-salesforce** [comment]
I've submitted a PR to add `hasTVPreferredFocus` to `TouchableOpacity` (see #15561).

**Comment by JulienKode** [comment]
@dlowder-salesforce  That's a nice a idea 👍
