### ISSUE TITLE
Documentation not clear on support for Fragments - Please clarify support for Fragments

### ISSUE THREAD

**Issue by dobrienlzd** [facebook/react-native#13852]
The existence of a FragmentActivity would suggest support for Fragments. However, it seems that Fragments are not actually supported by React Native.  They do not exist at all in any sample code. (Prove me wrong!).  There is an outstanding issue to integrate a ReactFragment class. There are issues in handling on touch events inside a fragment that is based on react.  Is there someone who can clarify the situation?  What is the best option for those that want to use react native inside a fragment vs. activity?  In particular to have an activity with some fragments that are native and one or more fragments that is react native.  I need clarification if this can be done. This question obviously needs answering for anyone who is planning on a hybrid approach with the UI like integrating into an existing Android app.

**Comment by githubdoramon** [comment]
Having this problem here too... And it is a stopper to use react native as an hybrid solution, since I have a native view pager on my main activity, and am trying to have one os the fragments with react native

**Comment by aditijoshi** [comment]
+1

**Comment by githubdoramon** [comment]
I guess we will never get a reply for this :(

**Comment by dobrienlzd** [comment]
@githubdoramon @aditijoshi It's taking a while.  Looks like there is some movement on https://github.com/facebook/react-native/pull/12199 to release some sample code for at least one approach to doing this.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/documentation-not-clear-on-support-for-fragments---please-clarify-support-for-fr
