### ISSUE TITLE
Cannot read property 'length' of undefined via hot reload autobind

### ISSUE THREAD

**Issue by studiobrain** [facebook/react-native#13869]
App is crashing and erring out on every update when the hot load is triggered.  _see screenshot_ 
```
"react": "16.0.0-alpha.6",
"react-native": "^0.44.0",
"react-navigation": "1.0.0-beta.9",
```
I know there was a post about similar issues, but nothing seems to have been posted about this instance in particular.  

![screen shot 2017-05-09 at 10 01 59 am](https://cloud.githubusercontent.com/assets/4606770/25857762/a263a164-349f-11e7-85b1-847f32f274f6.png)

**Comment by dobrienlzd** [comment]
Looks like you are trying to read variable that's not defined.  This can be due to several reasons.
Maybe you did not import the module/package?  Or what often happens is you did not import correctly.  For example if you are importing Alert object it needs to be pulled in from react not react-native. Let us now if that's it.  Post your imports and also where you are referencing length.

**Comment by dobrienlzd** [comment]
Also sometimes there is more information in the package manager window then just on the emulator window. Let us know more about it so we can help.

**Comment by studiobrain** [comment]
Unfortunately, this isn't an issue with packages missing or a reference to length per se as much as it is to do the hot reloading of the component.  On initial load it renders as expected, yet any subsequent change (or no change and just an IDE save) triggers the red window you see above.  I am debugging to see if there is an area of the code that is causing it 100% of the time, but have been unsuccessful to present.  I will continue to debug and report back.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/cannot-read-property-length-of-undefined-via-hot-reload-autobind
