### ISSUE TITLE
Animated doesn't work when rendering with react-test-renderer

### ISSUE THREAD

**Issue by talarari** [facebook/react-native#13867]
I'm trying to write a test for a react native component using jest and react-test-renderer only.
no enzyme. no jsdom.

everything works great (lifecycle hooks are called etc) ,  expect Animated.

this is the sample component i'm testing :
```
export default class AnimatedShow extends React.Component {
    constructor(props) {
        super(props)

    }
    componentWillMount() {
        this.animatedValue = new Animated.Value(0)
    }

    componentDidMount() {
        Animated.timing(this.animatedValue, {
            toValue: 1,
            duration: 2000,
            easing: Easing.bounce
        }).start()
    }
    render() {
        return (
            <Animated.View testID={'animated-text-1'} style={{ opacity: this.animatedValue }}>
                <Text>animated text</Text>
            </Animated.View>
        )
    }
}
```

then i want to assert the opacity of the animated view (either by time travelling with fake timers or actually waiting, i've tried both)

but the opacity stays 0.

how would you suggest solving this?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/animated-doesnt-work-when-rendering-with-react-test-renderer
