### ISSUE TITLE
Can't Run App In Simulator from Terminal

### ISSUE THREAD

**Issue by yesh0907** [facebook/react-native#13865]
I tried running the react-native run-ios from the terminal, but the build failed. Oddly the build works in XCode but not in the terminal. 

### ERROR:
Scanning 557 folders for symlinks in /Users/yesh0907/Desktop/coding/Javascript/react-native/todo/node_modules (4ms)
Found Xcode project todo.xcodeproj
We couldn't boot your defined simulator due to an already booted simulator. We are limited to one simulator launched at a time.
Launching iPhone 6 (iOS 10.3)...
Building using "xcodebuild -project todo.xcodeproj -configuration Debug -scheme todo -destination id=37AA43EC-63B1-460A-BA5A-26C1B4ECBE4B -derivedDataPath build"
User defaults from command line:

    IDEDerivedDataPathOverride = /Users/yesh0907/Desktop/coding/Javascript/react-native/todo/ios/build

=== BUILD TARGET yoga OF PROJECT React WITH CONFIGURATION Debug ===

Check dependencies

Analyze /Users/yesh0907/Desktop/coding/Javascript/react-native/todo/node_modules/react-native/ReactCommon/yoga/yoga/YGNodeList.c
    cd /Users/yesh0907/Desktop/coding/Javascript/react-native/todo/node_modules/react-native/React
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/yesh0907/.rvm/gems/ruby-2.4.0/bin:/Users/yesh0907/.rvm/gems/ruby-2.4.0@global/bin:/Users/yesh0907/.rvm/rubies/ruby-2.4.0/bin:/Users/yesh0907/opt/cross/bin:/Users/yesh0907/.rbenv/shims:/usr/local/opt/php56/bin:/usr/local/share/npm/bin:/Users/yesh0907/.npm-packages/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/yesh0907/.rvm/bin"
    /usr/local/bin/gcc-4.9 -x c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -fmodules -fmodules-cache-path=/Users/yesh0907/Desktop/coding/Javascript/react-native/todo/ios/build/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/yesh0907/Desktop/coding/Javascript/react-native/todo/ios/build/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wmissing-prototypes -Werror=return-type -Wunreachable-code -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wmissing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wshadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wshorten-64-to-32 -Wpointer-sign -Wnewline-eof -DDEBUG=1 -DRCT_DEBUG=1 -DRCT_DEV=1 -DRCT_NSASSERT=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.3.sdk -fasm-blocks -fstrict-aliasing -Wdeprecated-declarations -mios-simulator-version-min=8.0 -g -Wno-sign-conversion -Winfinite-recursion -D__clang_analyzer__ -Xclang -analyzer-output=plist-multi-file -Xclang -analyzer-config -Xclang path-diagnostics-alternate=true -Xclang -analyzer-config -Xclang report-in-main-source-file=true -Xclang -analyzer-config -Xclang nullability:NoDiagnoseCallsToSystemHeaders=true -Xclang -analyzer-checker -Xclang security.insecureAPI.UncheckedReturn -Xclang -analyzer-checker -Xclang security.insecureAPI.getpw -Xclang -analyzer-checker -Xclang security.insecureAPI.gets -Xclang -analyzer-checker -Xclang security.insecureAPI.mkstemp -Xclang -analyzer-checker -Xclang security.insecureAPI.mktemp -Xclang -analyzer-disable-checker -Xclang security.insecureAPI.rand -Xclang -analyzer-disable-checker -Xclang security.insecureAPI.strcpy -Xclang -analyzer-checker -Xclang security.insecureAPI.vfork -I/Users/yesh0907/Desktop/coding/Javascript/react-native/todo/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/yoga.build/yoga.hmap -I/Users/yesh0907/Desktop/coding/Javascript/react-native/todo/ios/build/Build/Products/Debug-iphonesimulator/include -I/Users/yesh0907/Desktop/coding/Javascript/react-native/todo/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/yoga.build/DerivedSources/x86_64 -I/Users/yesh0907/Desktop/coding/Javascript/react-native/todo/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/yoga.build/DerivedSources -Wextra -Wall -Wno-semicolon-before-method-body -F/Users/yesh0907/Desktop/coding/Javascript/react-native/todo/ios/build/Build/Products/Debug-iphonesimulator -MMD -MT dependencies -MF /Users/yesh0907/Desktop/coding/Javascript/react-native/todo/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/yoga.build/StaticAnalyzer/React/yoga/normal/x86_64/YGNodeList.d --analyze /Users/yesh0907/Desktop/coding/Javascript/react-native/todo/node_modules/react-native/ReactCommon/yoga/yoga/YGNodeList.c -o /Users/yesh0907/Desktop/coding/Javascript/react-native/todo/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/yoga.build/StaticAnalyzer/React/yoga/normal/x86_64/YGNodeList.plist

gcc-4.9: error: path-diagnostics-alternate=true: No such file or directory

gcc-4.9: error: report-in-main-source-file=true: No such file or directory

gcc-4.9: error: nullability:NoDiagnoseCallsToSystemHeaders=true: No such file or directory

gcc-4.9: error: security.insecureAPI.UncheckedReturn: No such file or directory

gcc-4.9: error: security.insecureAPI.getpw: No such file or directory

gcc-4.9: error: security.insecureAPI.gets: No such file or directory

gcc-4.9: error: security.insecureAPI.mkstemp: No such file or directory

gcc-4.9: error: security.insecureAPI.mktemp: No such file or directory

gcc-4.9: error: security.insecureAPI.rand: No such file or directory

gcc-4.9: error: security.insecureAPI.strcpy: No such file or directory

gcc-4.9: error: security.insecureAPI.vfork: No such file or directory

gcc-4.9: error: unrecognized command line option '-fdiagnostics-show-note-include-stack'

gcc-4.9: error: unrecognized command line option '-fmacro-backtrace-limit=0'

gcc-4.9: error: unrecognized command line option '-fmodules'

gcc-4.9: error: unrecognized command line option '-fmodules-cache-path=/Users/yesh0907/Desktop/coding/Javascript/react-native/todo/ios/build/ModuleCache'

gcc-4.9: error: unrecognized command line option '-fmodules-prune-interval=86400'

gcc-4.9: error: unrecognized command line option '-fmodules-prune-after=345600'

gcc-4.9: error: unrecognized command line option '-fbuild-session-file=/Users/yesh0907/Desktop/coding/Javascript/react-native/todo/ios/build/ModuleCache/Session.modulevalidation'

gcc-4.9: error: unrecognized command line option '-fmodules-validate-once-per-build-session'

gcc-4.9: error: unrecognized command line option '-Wnon-modular-include-in-framework-module'

gcc-4.9: error: unrecognized command line option '-fpascal-strings'

gcc-4.9: error: unrecognized command line option '-Wconditional-uninitialized'

gcc-4.9: error: unrecognized command line option '-Wconstant-conversion'

gcc-4.9: error: unrecognized command line option '-Wint-conversion'

gcc-4.9: error: unrecognized command line option '-Wbool-conversion'

gcc-4.9: error: unrecognized command line option '-Wenum-conversion'

gcc-4.9: error: unrecognized command line option '-Wshorten-64-to-32'

gcc-4.9: error: unrecognized command line option '-Wnewline-eof'

gcc-4.9: error: unrecognized command line option '-fasm-blocks'

gcc-4.9: error: unrecognized command line option '-mios-simulator-version-min=8.0'

gcc-4.9: error: unrecognized command line option '-Winfinite-recursion'

gcc-4.9: error: unrecognized command line option '-Xclang'

gcc-4.9: error: unrecognized command line option '-analyzer-output=plist-multi-file'

gcc-4.9: error: unrecognized command line option '-Xclang'

gcc-4.9: error: unrecognized command line option '-analyzer-config'

gcc-4.9: error: unrecognized command line option '-Xclang'

gcc-4.9: error: unrecognized command line option '-Xclang'

gcc-4.9: error: unrecognized command line option '-analyzer-config'

gcc-4.9: error: unrecognized command line option '-Xclang'

gcc-4.9: error: unrecognized command line option '-Xclang'

gcc-4.9: error: unrecognized command line option '-analyzer-config'

gcc-4.9: error: unrecognized command line option '-Xclang'

gcc-4.9: error: unrecognized command line option '-Xclang'

gcc-4.9: error: unrecognized command line option '-analyzer-checker'

gcc-4.9: error: unrecognized command line option '-Xclang'

gcc-4.9: error: unrecognized command line option '-Xclang'

gcc-4.9: error: unrecognized command line option '-analyzer-checker'

gcc-4.9: error: unrecognized command line option '-Xclang'

gcc-4.9: error: unrecognized command line option '-Xclang'

gcc-4.9: error: unrecognized command line option '-analyzer-checker'

gcc-4.9: error: unrecognized command line option '-Xclang'

gcc-4.9: error: unrecognized command line option '-Xclang'

gcc-4.9: error: unrecognized command line option '-analyzer-checker'

gcc-4.9: error: unrecognized command line option '-Xclang'

gcc-4.9: error: unrecognized command line option '-Xclang'
gcc-4.9: error: unrecognized command line option '-analyzer-checker'

gcc-4.9: error: unrecognized command line option '-Xclang'

gcc-4.9: error: unrecognized command line option '-Xclang'
gcc-4.9: error: unrecognized command line option '-analyzer-disable-checker'
gcc-4.9: error: unrecognized command line option '-Xclang'

gcc-4.9: error: unrecognized command line option '-Xclang'
gcc-4.9: error: unrecognized command line option '-analyzer-disable-checker'

gcc-4.9: error: unrecognized command line option '-Xclang'

gcc-4.9: error: unrecognized command line option '-Xclang'

gcc-4.9: error: unrecognized command line option '-analyzer-checker'

gcc-4.9: error: unrecognized command line option '-Xclang'

gcc-4.9: error: unrecognized command line option '--analyze'

Command /usr/local/bin/gcc-4.9 failed with exit code 1

Installing build/Build/Products/Debug-iphonesimulator/todo.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

### Additional Information

* React Native version: 
react-native-cli: 2.0.1
react-native: 0.44.0
* Platform: iOS
* Development Operating System: MacOS
* Dev tools: XCode

**Comment by dobrienlzd** [comment]
You have two simulators running! close one!

**Comment by DanielMSchmidt** [comment]
@facebook-github-bot answered

**Comment by yesh0907** [comment]
@dobrienlzd That wasn't the issue, the problem was that  I was using homebrew's gcc-4.9. I uninstalled it and used the default gcc that comes with a Mac and it worked.

**Comment by hramos** [comment]
Duplicate of #14423
