### ISSUE TITLE
W/OkHttp: A connection to http://localhost:8097/ was leaked. Did you forget to close a response body?

### ISSUE THREAD

**Issue by HanAsteroid** [facebook/react-native#13860]
* React Native version:0.43
* Platform:  Android
* Development Operating System:  MacOS
* Dev tools: Android Studio version,
* OkHttp Version : 3.4.1
when it happens,my android app can not send any http request, i find this answer 
https://github.com/square/okhttp/issues/2311
but i don not konw how can i use in React-Native，

*  I try to use leakcanary ,i get this report:

 In com.ncfgroup.ryj:1.0.0:8.* com.jucaiapp.MainActivity has leaked:* GC ROOT static com.umeng.analytics.b.c.b* references com.jucaiapp.MainApplication.mActivityLifecycleCallbacks* references java.util.ArrayList.array* references array java.lang.Object[].[2]* references com.jucaiapp.modules.AppStateModule.mReactApplicationContext* references com.facebook.react.bridge.ReactApplicationContext.mLifecycleEventListeners* references java.util.concurrent.CopyOnWriteArraySet.al* references java.util.concurrent.CopyOnWriteArrayList.elements* references array java.lang.Object[].[1]* references com.facebook.react.uimanager.UIManagerModule.mUIImplementation* references com.facebook.react.uimanager.UIImplementation.mOperationsQueue* references com.facebook.react.uimanager.UIViewOperationQueue.mNativeViewHierarchyManager* references com.facebook.react.uimanager.NativeViewHierarchyManager.mTagsToViews* references android.util.SparseArray.mValues* references array java.lang.Object[].[0]* references com.facebook.react.ReactRootView.mContext* leaks com.jucaiapp.MainActivity instance* Retaining: 4.7 KB.* Reference Key: 2a593480-9412-4acd-98f5-207000d4495b* Device: HUAWEI HUAWEI HUAWEI GRA-UL00 GRA-UL00* Android Version: 6.0 API: 23 LeakCanary: 1.5 00f37f5* Durations: watch=5039ms, gc=173ms, heap dump=4098ms, analysis=47537ms* Details:* Class com.umeng.analytics.b.c| static $staticOverhead = byte[8]@319425825 (0x130a0d21)| static b = com.jucaiapp.MainApplication@315501920 (0x12ce2d60)* Instance of com.jucaiapp.MainApplication| static $staticOverhead = byte[8]@315336705 (0x12cba801)| static _app = com.jucaiapp.MainApplication@315501920 (0x12ce2d60)| mReactNativeHost = com.jucaiapp.MainApplication$1@315502016 (0x12ce2dc0)| mActivityLifecycleCallbacks = java.util.ArrayList@315501984 (0x12ce2da0)| mAssistCallbacks = null| mComponentCallbacks = java.util.ArrayList@315501952 (0x12ce2d80)| mLoadedApk = android.app.LoadedApk@315170592 (0x12c91f20)| mBase = android.app.ContextImpl@315504000 (0x12ce3580)| shadow$_klass_ = com.jucaiapp.MainApplication| shadow$_monitor_ = -1889873333* Instance of java.util.ArrayList| static $staticOverhead = byte[16]@1879444593 (0x70060c71)| static MIN_CAPACITY_INCREMENT = 12| static serialVersionUID = 8683452581122892189| array = java.lang.Object[12]@315595200 (0x12cf99c0)| size = 5| modCount = 5| shadow$_klass_ = java.util.ArrayList| shadow$_monitor_ = 0* Array of java.lang.Object[]| [0] = com.squareup.leakcanary.ActivityRefWatcher$1@315497248 (0x12ce1b20)| [1] = com.umeng.analytics.d.b$1@315495216 (0x12ce1330)| [2] = com.jucaiapp.modules.AppStateModule@319242496 (0x13074100)| [3] = com.jucaiapp.modules.AppStateModule@319498304 (0x130b2840)| [4] = com.jucaiapp.modules.AppStateModule@318122464 (0x12f629e0)| [5] = null| [6] = null| [7] = null| [8] = null| [9] = null| [10] = null| [11] = null* Instance of com.jucaiapp.modules.AppStateModule| static c = 1| static $staticOverhead = byte[24]@319062017 (0x13048001)| static lastState = java.lang.String@319057408 (0x13046e00)| static __visible = true| mReactApplicationContext = com.facebook.react.bridge.ReactApplicationContext@316240384 (0x12d97200)| mMethods = null| shadow$_klass_ = com.jucaiapp.modules.AppStateModule| shadow$_monitor_ = 0* Instance of com.facebook.react.bridge.ReactApplicationContext| mActivityEventListeners = java.util.concurrent.CopyOnWriteArraySet@315535568 (0x12ceb0d0)| mCatalystInstance = com.facebook.react.cxxbridge.CatalystInstanceImpl@319053744 (0x13045fb0)| mCurrentActivity = java.lang.ref.WeakReference@318622080 (0x12fdc980)| mInflater = null| mJSMessageQueueThread = com.facebook.react.bridge.queue.MessageQueueThreadImpl@319297952 (0x130819a0)| mLifecycleEventListeners = java.util.concurrent.CopyOnWriteArraySet@315535536 (0x12ceb0b0)| mLifecycleState = com.facebook.react.common.LifecycleState@315000128 (0x12c68540)| mNativeModuleCallExceptionHandler = com.facebook.react.devsupport.DevSupportManagerImpl@314965440 (0x12c5fdc0)| mNativeModulesMessageQueueThread = com.facebook.react.bridge.queue.MessageQueueThreadImpl@319298336 (0x13081b20)| mUiMessageQueueThread = com.facebook.react.bridge.queue.MessageQueueThreadImpl@319297312 (0x13081720)| mBase = com.jucaiapp.MainApplication@315501920 (0x12ce2d60)| shadow$_klass_ = com.facebook.react.bridge.ReactApplicationContext| shadow$_monitor_ = -2052544438* Instance of java.util.concurrent.CopyOnWriteArraySet| static $staticOverhead = byte[8]@1879515969 (0x70072341)| static serialVersionUID = 5457747651344034263| al = java.util.concurrent.CopyOnWriteArrayList@315535552 (0x12ceb0c0)| shadow$_klass_ = java.util.concurrent.CopyOnWriteArraySet| shadow$_monitor_ = 0* Instance of java.util.concurrent.CopyOnWriteArrayList| static $staticOverhead = byte[8]@1879515409 (0x70072111)| static serialVersionUID = 8673264195747942595| elements = java.lang.Object[9]@319466464 (0x130aabe0)| shadow$_klass_ = java.util.concurrent.CopyOnWriteArrayList| shadow$_monitor_ = 0* Array of java.lang.Object[]| [0] = com.facebook.react.uimanager.events.EventDispatcher@316318464 (0x12daa300)| [1] = com.facebook.react.uimanager.UIManagerModule@316298480 (0x12da54f0)| [2] = com.facebook.react.modules.accessibilityinfo.AccessibilityInfoModule@319057344 (0x13046dc0)| [3] = com.remobile.toast.Toast@319265024 (0x13079900)| [4] = com.facebook.react.modules.core.Timing@315174032 (0x12c92c90)| [5] = com.facebook.react.modules.appstate.AppStateModule@319057472 (0x13046e40)| [6] = com.facebook.react.animated.NativeAnimatedModule@319185632 (0x130662e0)| [7] = com.facebook.react.modules.netinfo.NetInfoModule@319182720 (0x13065780)| [8] = com.facebook.react.modules.dialog.DialogModule@319180864 (0x13065040)* Instance of com.facebook.react.uimanager.UIManagerModule| static ROOT_VIEW_TAG_INCREMENT = 10| static $staticOverhead = byte[24]@316695553 (0x12e06401)| static NAME = java.lang.String@316298432 (0x12da54c0)| static DEBUG = false| mBatchId = 101| mEventDispatcher = com.facebook.react.uimanager.events.EventDispatcher@316318464 (0x12daa300)| mFontScale = 1.0| mMemoryTrimCallback = com.facebook.react.uimanager.UIManagerModule$MemoryTrimCallback@316154272 (0x12d821a0)| mModuleConstants = java.util.HashMap@316298672 (0x12da55b0)| mNextRootViewTag = 11| mUIImplementation = com.facebook.react.uimanager.UIImplementation@319015808 (0x1303cb80)| mReactApplicationContext = com.facebook.react.bridge.ReactApplicationContext@316240384 (0x12d97200)| mMethods = java.util.HashMap@316427856 (0x12dc4e50)| shadow$_klass_ = com.facebook.react.uimanager.UIManagerModule| shadow$_monitor_ = 0* Instance of com.facebook.react.uimanager.UIImplementation| mEventDispatcher = com.facebook.react.uimanager.events.EventDispatcher@316318464 (0x12daa300)| mLayoutCount = 104.0| mLayoutTimer = 101.696451| mMeasureBuffer = int[4]@319054016 (0x130460c0)| mNativeViewHierarchyOptimizer = com.facebook.react.uimanager.NativeViewHierarchyOptimizer@319054048 (0x130460e0)| mOperationsQueue = com.facebook.react.uimanager.UIViewOperationQueue@319015936 (0x1303cc00)| mReactContext = com.facebook.react.bridge.ReactApplicationContext@316240384 (0x12d97200)| mShadowNodeRegistry = com.facebook.react.uimanager.ShadowNodeRegistry@319053888 (0x13046040)| mViewManagers = com.facebook.react.uimanager.ViewManagerRegistry@318944608 (0x1302b560)| shadow$_klass_ = com.facebook.react.uimanager.UIImplementation| shadow$_monitor_ = 0* Instance of com.facebook.react.uimanager.UIViewOperationQueue| mAnimationRegistry = com.facebook.react.animation.AnimationRegistry@318944992 (0x1302b6e0)| mDispatchRunnablesLock = java.lang.Object@318945008 (0x1302b6f0)| mDispatchUIFrameCallback = com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback@319045600 (0x13043fe0)| mDispatchUIRunnables = java.util.ArrayList@319045504 (0x13043f80)| mIsDispatchUIFrameCallbackEnqueued = false| mIsInIllegalUIState = false| mMeasureBuffer = int[4]@319045472 (0x13043f60)| mNativeViewHierarchyManager = com.facebook.react.uimanager.NativeViewHierarchyManager@319034128 (0x13041310)| mNonBatchedOperations = java.util.ArrayDeque@319045568 (0x13043fc0)| mNonBatchedOperationsLock = java.lang.Object@318945024 (0x1302b700)| mOperations = java.util.ArrayList@317366720 (0x12eaa1c0)| mReactApplicationContext = com.facebook.react.bridge.ReactApplicationContext@316240384 (0x12d97200)| mViewHierarchyUpdateDebugListener = null| shadow$_klass_ = com.facebook.react.uimanager.UIViewOperationQueue| shadow$_monitor_ = 0* Instance of com.facebook.react.uimanager.NativeViewHierarchyManager| static $staticOverhead = byte[8]@318347265 (0x12f99801)| static TAG = java.lang.String@318898096 (0x1301ffb0)| mAnimationRegistry = com.facebook.react.animation.AnimationRegistry@318944992 (0x1302b6e0)| mJSResponderHandler = com.facebook.react.touch.JSResponderHandler@318944896 (0x1302b680)| mLayoutAnimationEnabled = false| mLayoutAnimator = com.facebook.react.uimanager.layoutanimation.LayoutAnimationController@319044448 (0x13043b60)| mRootTags = android.util.SparseBooleanArray@319045408 (0x13043f20)| mRootViewManager = com.facebook.react.uimanager.RootViewManager@318944864 (0x1302b660)| mTagsToViewManagers = android.util.SparseArray@319045376 (0x13043f00)| mTagsToViews = android.util.SparseArray@319045344 (0x13043ee0)| mViewManagers = com.facebook.react.uimanager.ViewManagerRegistry@318944608 (0x1302b560)| shadow$_klass_ = com.facebook.react.uimanager.NativeViewHierarchyManager| shadow$_monitor_ = 0* Instance of android.util.SparseArray| static $staticOverhead = byte[8]@1879957809 (0x700de131)| static DELETED = java.lang.Object@1879124816 (0x70012b50)| mGarbage = true| mKeys = int[125]@319711744 (0x130e6a00)| mSize = 71| mValues = java.lang.Object[125]@319712256 (0x130e6c00)| shadow$_klass_ = android.util.SparseArray| shadow$_monitor_ = 0* Array of java.lang.Object[]| [0] = com.facebook.react.ReactRootView@315076608 (0x12c7b000)| [1] = com.facebook.react.views.view.ReactViewGroup@319121408 (0x13056800)| [2] = com.facebook.react.views.view.ReactViewGroup@319122432 (0x13056c00)| [3] = com.facebook.react.views.view.ReactViewGroup@315073536 (0x12c7a400)| [4] = com.facebook.react.views.view.ReactViewGroup@315134976 (0x12c89400)| [5] = com.facebook.react.views.view.ReactViewGroup@315136000 (0x12c89800)| [6] = com.facebook.react.views.view.ReactViewGroup@316952576 (0x12e45000)| [7] = com.facebook.react.views.view.ReactViewGroup@316953600 (0x12e45400)| [8] = com.facebook.react.views.image.ReactImageView@316954624 (0x12e45800)| [9] = com.facebook.react.views.text.ReactTextView@316955648 (0x12e45c00)| [10] = com.facebook.react.views.view.ReactViewGroup@317252608 (0x12e8e400)| [11] = com.facebook.react.views.image.ReactImageView@317253632 (0x12e8e800)| [12] = com.facebook.react.views.text.ReactTextView@317254656 (0x12e8ec00)| [13] = com.facebook.react.views.view.ReactViewGroup@317255680 (0x12e8f000)| [14] = com.facebook.react.views.image.ReactImageView@317259776 (0x12e90000)| [15] = com.facebook.react.views.text.ReactTextView@317260800 (0x12e90400)| [16] = com.facebook.react.views.view.ReactViewGroup@317261824 (0x12e90800)| [17] = com.facebook.react.views.image.ReactImageView@317262848 (0x12e90c00)| [18] = com.facebook.react.views.text.ReactTextView@317263872 (0x12e91000)| [19] = com.facebook.react.views.view.ReactViewGroup@317745152 (0x12f06800)| [20] = com.facebook.react.views.text.ReactTextView@317748224 (0x12f07400)| [21] = java.lang.Object@1879124816 (0x70012b50)| [22] = com.facebook.react.views.swiperefresh.ReactSwipeRefreshLayout@317743104 (0x12f06000)| [23] = com.facebook.react.views.scroll.ReactScrollView@317761536 (0x12f0a800)| [24] = com.facebook.react.views.view.ReactViewGroup@317763584 (0x12f0b000)| [25] = com.facebook.react.views.view.ReactViewGroup@317765632 (0x12f0b800)| [26] = com.facebook.react.views.view.ReactViewGroup@317766656 (0x12f0bc00)| [27] = com.facebook.react.views.text.ReactTextView@317767680 (0x12f0c000)| [28] = com.facebook.react.views.text.ReactTextView@317768704 (0x12f0c400)| [29] = com.facebook.react.views.text.ReactTextView@317769728 (0x12f0c800)| [30] = com.facebook.react.views.view.ReactViewGroup@317770752 (0x12f0cc00)| [31] = com.facebook.react.views.text.ReactTextView@317773824 (0x12f0d800)| [32] = com.facebook.react.views.text.ReactTextView@317775872 (0x12f0e000)| [33] = com.facebook.react.views.view.ReactViewGroup@317776896 (0x12f0e400)| [34] = com.facebook.react.views.text.ReactTextView@317777920 (0x12f0e800)| [35] = com.facebook.react.views.view.ReactViewGroup@317778944 (0x12f0ec00)| [36] = com.facebook.react.views.view.ReactViewGroup@317779968 (0x12f0f000)| [37] = com.facebook.react.views.view.ReactViewGroup@317780992 (0x12f0f400)| [38] = com.facebook.react.views.text.ReactTextView@317785088 (0x12f10400)| [39] = com.facebook.react.views.text.ReactTextView@317786112 (0x12f10800)| [40] = com.facebook.react.views.text.ReactTextView@317282304 (0x12e95800)| [41] = com.facebook.react.views.view.ReactViewGroup@317283328 (0x12e95c00)| [42] = com.facebook.react.views.text.ReactTextView@317285376 (0x12e96400)| [43] = com.facebook.react.views.text.ReactTextView@317290496 (0x12e97800)| [44] = com.facebook.react.views.view.ReactViewGroup@317291520 (0x12e97c00)| [45] = com.facebook.react.views.text.ReactTextView@317292544 (0x12e98000)| [46] = com.facebook.react.views.view.ReactViewGroup@317305856 (0x12e9b400)| [47] = com.facebook.react.views.view.ReactViewGroup@317306880 (0x12e9b800)| [48] = com.facebook.react.views.view.ReactViewGroup@318288896 (0x12f8b400)| [49] = com.facebook.react.views.text.ReactTextView@318289920 (0x12f8b800)| [50] = com.facebook.react.views.text.ReactTextView@318290944 (0x12f8bc00)| [51] = com.facebook.react.views.text.ReactTextView@318291968 (0x12f8c000)| [52] = com.facebook.react.views.view.ReactViewGroup@318297088 (0x12f8d400)| [53] = com.facebook.react.views.text.ReactTextView@318298112 (0x12f8d800)| [54] = com.facebook.react.views.text.ReactTextView@318300160 (0x12f8e000)| [55] = com.facebook.react.views.view.ReactViewGroup@318301184 (0x12f8e400)| [56] = com.facebook.react.views.text.ReactTextView@318302208 (0x12f8e800)| [57] = com.facebook.react.views.view.ReactViewGroup@318304256 (0x12f8f000)| [58] = com.facebook.react.views.view.ReactViewGroup@318305280 (0x12f8f400)| [59] = com.facebook.react.views.view.ReactViewGroup@318306304 (0x12f8f800)| [60] = com.facebook.react.views.text.ReactTextView@318307328 (0x12f8fc00)| [61] = com.facebook.react.views.text.ReactTextView@318309376 (0x12f90400)| [62] = com.facebook.react.views.text.ReactTextView@318310400 (0x12f90800)| [63] = com.facebook.react.views.view.ReactViewGroup@318311424 (0x12f90c00)| [64] = com.facebook.react.views.text.ReactTextView@318313472 (0x12f91400)| [65] = com.facebook.react.views.text.ReactTextView@318314496 (0x12f91800)| [66] = com.facebook.react.views.view.ReactViewGroup@318315520 (0x12f91c00)| [67] = com.facebook.react.views.text.ReactTextView@318317568 (0x12f92400)| [68] = com.facebook.react.views.view.ReactViewGroup@318318592 (0x12f92800)| [69] = com.facebook.react.views.view.ReactViewGroup@318319616 (0x12f92c00)| [70] = com.facebook.react.views.text.ReactTextView@318321664 (0x12f93400)| [71] = null| [72] = null| [73] = null| [74] = null| [75] = null| [76] = null| [77] = null| [78] = null| [79] = null| [80] = null| [81] = null| [82] = null| [83] = null| [84] = null| [85] = null| [86] = null| [87] = null| [88] = null| [89] = null| [90] = null| [91] = null| [92] = null| [93] = null| [94] = null| [95] = null| [96] = null| [97] = null| [98] = null| [99] = null| [100] = null| [101] = null| [102] = null| [103] = null| [104] = null| [105] = null| [106] = null| [107] = null| [108] = null| [109] = null| [110] = null| [111] = null| [112] = null| [113] = null| [114] = null| [115] = null| [116] = null| [117] = null| [118] = null| [119] = null| [120] = null| [121] = null| [122] = null| [123] = null| [124] = null* Instance of com.facebook.react.ReactRootView| mCustomGlobalLayoutListener = com.facebook.react.ReactRootView$CustomGlobalLayoutListener@319361792 (0x13091300)| mIsAttachedToInstance = false| mJSModuleName = java.lang.String@316314368 (0x12da9300)| mJSTouchDispatcher = com.facebook.react.uimanager.JSTouchDispatcher@314959040 (0x12c5e4c0)| mLaunchOptions = null| mReactInstanceManager = com.facebook.react.ReactInstanceManager@314963904 (0x12c5f7c0)| mRootViewEventListener = null| mRootViewTag = 1| mWasMeasured = true| mOnSizeChangedListener = com.facebook.react.uimanager.UIManagerModule$1@314947968 (0x12c5b980)| mForegroundPaddingBottom = 0| mForegroundPaddingLeft = 0| mForegroundPaddingRight = 0| mForegroundPaddingTop = 0| mMatchParentChildren = java.util.ArrayList@314959008 (0x12c5e4a0)| mMeasureAllChildren = false| mOverlayBounds = android.graphics.Rect@314958976 (0x12c5e480)| mSelfBounds = android.graphics.Rect@314958944 (0x12c5e460)| mAnimationListener = null| mCachePaint = null| mChildAcceptsDrag = false| mChildCountWithTransientState = 0| mChildTransformation = null| mChildren = android.view.View[12]@314736128 (0x12c27e00)| mChildrenCount = 0| mCurrentDrag = null| mCurrentDragView = null| mDisappearingChildren = null| mDragNotifiedChildren = null| mFirstHoverTarget = null| mFirstTouchTarget = null| mFocused = null| mGroupFlags = 2244691| mHoveredSelf = false| mInvalidateRegion = null| mInvalidationTransformation = null| mLastTouchDownIndex = -1| mLastTouchDownTime = 0| mLastTouchDownX = 543.0| mLastTouchDownY = 1732.0| mLayoutAnimationController = null| mLayoutCalledWhileSuppressed = false| mLayoutMode = -1| mLayoutTransitionListener = android.view.ViewGroup$4@314999920 (0x12c68470)| mLocalPoint = null| mNestedScrollAxes = 0| mOnHierarchyChangeListener = null| mPersistentDrawingCache = 2| mPreSortedChildren = java.util.ArrayList@320054368 (0x1313a460)| mSuppressLayout = false| mTempPoint = float[2]@318847136 (0x130138a0)| mTransientIndices = null| mTransientViews = null| mTransition = null| mTransitioningViews = null| mVisibilityChangingChildren = null| mAccessibilityCursorPosition = -1| mAccessibilityDelegate = null| mAccessibilityTraversalAfterId = -1| mAccessibilityTraversalBeforeId = -1| mAccessibilityViewId = -1| mAnimator = null| mAttachInfo = null| mAttributes = null| mBackground = null| mBackgroundRenderNode = null| mBackgroundResource = 0| mBackgroundSizeChanged = true| mBackgroundTint = null| mBottom = 1812| mCachingFailed = false| mCanTouchInOtherThread = false| mClipBounds = null| mContentDescription = null| mContext = com.jucaiapp.MainActivity@314716800 (0x12c23280)| mCurrentAnimation = null| mDrawableState = int[2]@1879160624 (0x7001b730)| mDrawingCache = null| mDrawingCacheBackgroundColor = 0| mFloatingTreeObserver = null| mForceRTL = false| mForegroundInfo = null| mGhostView = null| mHasPerformedLongPress = false| mHwInstrumentation = null| mHwStateListAnimator = null| mID = 1| mIgnoreNextUpEvent = false| mInContextButtonPress = false| mInputEventConsistencyVerifier = null| mKeyedTags = null| mLabelForId = -1| mLastIsOpaque = false| mLayerPaint = null| mLayerType = 0| mLayoutInsets = null| mLayoutParams = android.widget.FrameLayout$LayoutParams@316285760 (0x12da2340)| mLeft = 0| mLeftPaddingDefined = false| mListenerInfo = null| mMatchIdPredicate = null| mMatchLabelForPredicate = null| mMeasureCache = android.util.LongSparseLongArray@317894016 (0x12f2ad80)| mMeasuredHeight = 1812| mMeasuredWidth = 1080| mMinHeight = 0| mMinWidth = 0| mNestedScrollingParent = null| mNextFocusDownId = -1| mNextFocusForwardId = -1| mNextFocusLeftId = -1| mNextFocusRightId = -1| mNextFocusUpId = -1| mOldHeightMeasureSpec = 1073743636| mOldWidthMeasureSpec = 1073742904| mOutlineProvider = android.view.ViewOutlineProvider$1@1879154176 (0x70019e00)| mOverScrollMode = 1| mOverlay = null| mPaddingBottom = 0| mPaddingLeft = 0| mPaddingRight = 0| mPaddingTop = 0| mParent = android.widget.FrameLayout@315132928 (0x12c88c00)| mPendingCheckForLongPress = null| mPendingCheckForTap = null| mPerformClick = null| mPrivateFlags = -2128471920| mPrivateFlags2 = 1610819112| mPrivateFlags3 = 0| mRecreateDisplayList = false| mRenderNode = android.view.RenderNode@314958880 (0x12c5e420)| mResources = android.content.res.HwResources@315502848 (0x12ce3100)| mRight = 1080| mRightPaddingDefined = false| mScrollCache = null| mScrollIndicatorDrawable = null| mScrollX = 0| mScrollY = 0| mSendViewScrolledAccessibilityEvent = null| mSendViewStateChangedAccessibilityEvent = null| mSendingHoverAccessibilityEvents = false| mStartActivityRequestWho = null| mStateListAnimator = null| mSystemUiVisibility = 0| mTag = null| mTempNestedScrollConsumed = null| mTop = 0| mTouchDelegate = null| mTouchSlop = 24| mTransformationInfo = android.view.View$TransformationInfo@319361152 (0x13091080)| mTransientStateCount = 0| mTransitionName = null| mUnscaledDrawingCache = null| mUnsetPressedState = null| mUserPaddingBottom = 0| mUserPaddingEnd = -2147483648| mUserPaddingLeft = 0| mUserPaddingLeftInitial = 0| mUserPaddingRight = 0| mUserPaddingRightInitial = 0| mUserPaddingStart = -2147483648| mVerticalScrollFactor = 0.0| mVerticalScrollbarPosition = 0| mViewFlags = 402653312| mWindowAttachCount = 1| shadow$_klass_ = com.facebook.react.ReactRootView| shadow$_monitor_ = 0* Instance of com.jucaiapp.MainActivity| static $staticOverhead = byte[8]@315365377 (0x12cc1801)| static _self = com.jucaiapp.MainActivity@318956224 (0x1302e2c0)| mDelegate = com.facebook.react.ReactActivityDelegate@316312304 (0x12da8af0)| mActionBar = null| mActionModeTypeStarting = 0| mActivityInfo = android.content.pm.ActivityInfo@315256960 (0x12ca7080)| mActivityTransitionState = android.app.ActivityTransitionState@316308992 (0x12da7e00)| mApplication = com.jucaiapp.MainApplication@315501920 (0x12ce2d60)| mCalled = true| mChangeCanvasToTranslucent = false| mChangingConfigurations = false| mComponent = android.content.ComponentName@314998912 (0x12c68080)| mConfigChangeFlags = 0| mCurrentConfig = android.content.res.Configuration@316294528 (0x12da4580)| mDecor = null| mDefaultKeyMode = 0| mDefaultKeySsb = null| mDestroyed = true| mDoReportFullyDrawn = false| mEmbeddedID = null| mEnableDefaultActionBarUp = false| mEnterTransitionListener = android.app.SharedElementCallback$1@1879125128 (0x70012c88)| mExitTransitionListener = android.app.SharedElementCallback$1@1879125128 (0x70012c88)| mFinished = true| mFragments = android.app.FragmentController@315538112 (0x12cebac0)| mHandler = android.os.Handler@316314240 (0x12da9280)| mHasCurrentPermissionsRequest = false| mIdent = 75807001| mInstanceTracker = android.os.StrictMode$InstanceTracker@315538128 (0x12cebad0)| mInstrumentation = android.app.Instrumentation@315173392 (0x12c92a10)| mIntent = android.content.Intent@315236416 (0x12ca2040)| mIsFullFlag = false| mLastNonConfigurationInstances = null| mMainThread = android.app.ActivityThread@315143872 (0x12c8b6c0)| mManagedCursors = java.util.ArrayList@316314272 (0x12da92a0)| mManagedDialogs = null| mMenuInflater = null| mParent = null| mReferrer = java.lang.String@315241264 (0x12ca3330)| mResultCode = 0| mResultData = null| mResumed = false| mSearchEvent = null| mSearchManager = null| mStartedActivity = false| mStopped = true| mTemporaryPause = false| mTitle = java.lang.String@316314624 (0x12da9400)| mTitleColor = 0| mTitleReady = true| mToken = android.os.BinderProxy@314990816 (0x12c660e0)| mTranslucentCallback = null| mUiThread = java.lang.Thread@1949278000 (0x742f9f30)| mVisibleBehind = false| mVisibleFromClient = true| mVisibleFromServer = true| mVoiceInteractor = null| mWindow = com.android.internal.policy.HwPhoneWindow@315844048 (0x12d365d0)| mWindowAdded = true| mWindowManager = android.view.WindowManagerImpl@316316448 (0x12da9b20)| mInflater = com.android.internal.policy.HwPhoneLayoutInflater@316321904 (0x12dab070)| mOverrideConfiguration = null| mResources = android.content.res.HwResources@315502848 (0x12ce3100)| mTheme = android.content.res.Resources$Theme@316316480 (0x12da9b40)| mThemeResource = 2131296385| mBase = android.app.ContextImpl@315837952 (0x12d34e00)| shadow$_klass_ = com.jucaiapp.MainActivity| shadow$_monitor_ = 1254971044* Excluded Refs:| Field: android.view.inputmethod.InputMethodManager.mNextServedView| Field: android.view.inputmethod.InputMethodManager.mServedView| Field: android.view.inputmethod.InputMethodManager.mServedInputConnection| Field: android.view.inputmethod.InputMethodManager.mCurRootView| Field: android.os.UserManager.mContext| Field: android.net.ConnectivityManager.sInstance| Field: android.view.Choreographer$FrameDisplayEventReceiver.mMessageQueue (always)| Thread:FinalizerWatchdogDaemon (always)| Thread:main (always)| Thread:LeakCanary-Heap-Dump (always)| Class:java.lang.ref.WeakReference (always)| Class:java.lang.ref.SoftReference (always)| Class:java.lang.ref.PhantomReference (always)| Class:java.lang.ref.Finalizer (always)| Class:java.lang.ref.FinalizerReference (always)]

**Comment by stoffern** [comment]
dupe https://github.com/facebook/react-native/issues/9478

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/wokhttp-a-connection-to-httplocalhost8097-was-leaked-did-you-forget-to-close-a-r
