### ISSUE TITLE
gitignore about ios/build/ is not work

### ISSUE THREAD

**Issue by robert1202** [facebook/react-native#13863]
i use https://github.com/facebook/react-native/blob/master/.gitignore in my project,
use "react-native run-ios"  build some files in "ios/build/"
i add ios/build/ into the .gitignore,but is not work,

**Comment by dobrienlzd** [comment]
Be more specific. How so?

**Comment by dobrienlzd** [comment]
Which files is it including that you think it should not be?  You should also tell us your version of git and react-native.    npm list should give you some information.   We need more information about what version of react-native you are on and also what version of git.  How did you create your react native app?  Please tell us specifically what files are not being ignored. What is your file structure etc. Where are these files that are being included but should not be?  Do you have a .git directory and at what level is it?

**Comment by bionetmarco** [comment]
Commit your code, and try this:

```
git rm -r --cached .
git add .
git commit -m ".gitignore is now working"
```

Source: [StackOverflow](http://stackoverflow.com/questions/1139762/ignore-files-that-have-already-been-committed-to-a-git-repository)

**Comment by robert1202** [comment]
this is my fault ,my colleague commit these files
