### ISSUE TITLE
Some UIViews not rendering when storyboard is presented via a Native Module.

### ISSUE THREAD

**Issue by ericcastro92** [facebook/react-native#13878]
### Description

I have created a Native Module that presents a storyboard. In that story board I have a couple of views. When the storyboard is presented a few of the fields (Mainly UILables and hints in UITextFields) take a while (generally > 10+ seconds) before they actually render on screen. If they have not yet rendered, clicking on the field where they should be will render the content (ie. clicking on a text field will then render the missing hint text).

This is where things get interesting, the bug only happens to occur occasionally. It also does not seem to be a problem when the app is deployed to an iPhone 7 Plus. However, the issue appears on simulated iPhone 7 and physical iPhone6/s devices.

### Reproduction Steps and Sample Code

1. Create a Native Module that presents a storyboard
2. Import Native Module into RN app
3. Invoke the Native Module that presents the storyboard

**Native Module (Swift 3.0)**
```
@objc func authorize(_ callback: @escaping RCTResponseSenderBlock) -> Void {
   let touchIDScreen: TouchIDViewController = TouchIDViewController(nibName: "TouchIDScreen", bundle: nil)
   let rootViewController = UIApplication.shared.keyWindow?.rootViewController 
   touchIDScreen.callback = callback
   DispatchQueue.main.async {
      rootViewController?.present(touchIDScreen, animated: true, completion: nil)
   }
}
```

**React Native (Snippet)**
```
import TouchID = NativeModules.TouchID;

componentWillMount() {
    TouchID.authorize();
}
```

### Solution

Not sure what type of fix this bug will require. This issue didn't appear to be present when I was developing with earlier version of react.

Thanks for your help!

### Additional Information

* React Native version:0.42.0
* React Native CLI version : 2.0.1
* Platform: iOS
* Development Operating System: MacOS
* Dev tools: Xcode 8

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/some-uiviews-not-rendering-when-storyboard-is-presented-via-a-native-module
