### ISSUE TITLE
undefined is not an object (evaluating 'ReactInternals.ReactCurrentOwner')

### ISSUE THREAD

**Issue by Benjamin-Dobell** [facebook/react-native#13874]
### Description

The last couple of days I've been attempting to debug the current React Native master (updated the HEAD a few times) on either iOS or Android, however app execution fails immediately after receiving the bundle with the exception:

```
undefined is not an object (evaluating 'ReactInternals.ReactCurrentOwner')
```

I've attempted clean app rebuilds many times:

```
watchman watch-del-all
rm -rf ./node_modules
yarn cache clean
rm -rf $TMPDIR/react-*
yarn install
npm start -- --reset-cache
```

Also, cleaned the Android builds (`./gradlew clean`) and iOS builds ("Clean" and "Clean Build Folder") and rebuilt.

### Reproduction Steps and Sample Code

1. Check out RN master.

2. Build the Android libs using:

```
./gradlew installArchives
```

3. Check in the resultant `android/` directory (force add as it's `.gitignore`'d) and push to a Github branch.

4. In a RN app swap from the NPM published package to the published branch e.g.

```
yarn remove react-native
yarn add github:benjamin-dobell/react-native#builds/dynamic-toolbar
```

5. Rebuild the app `cd android; ./gradlew clean; ./gradlew installDebug`, or for iOS from XCode.

6. Launch the RN packager:

```
yarn start
```

*__Note:__ If you haven't grabbed flowtype from master this will fail here. I just temporarily replaced the spread operator usage in type definitions with copy and paste contents.*

7. Launch the app on an Android or iOS device. Wait for the packager to bundle the package.

Error then occurs.

It's perhaps worth noting that, _I believe_, this is the exact procedure I've followed in the past to build and test (and eventually contribute back) my RN forks.

### Solution

Unsure.

### Additional Information

* React Native version: 73fc439bc03b457d7bcebdb3fd230e470af52e38
* Platform: Android & iOS
* Development Operating System: macOS 10.12.4 (16E195)
* Dev tools:
  - android-ndk-r10e
  - Xcode 8.3.2 (Build version 8E2002)
  - node v7.9.0
  - yarn 0.23.4
  - npm 4.2.0

**Comment by Benjamin-Dobell** [comment]
Perhaps a hint toward the underlying cause. When you run the packager with:

```
yarn start -- --reset-cache
```

instead of simply `yarn start`.

You end up with a few warnings about duplicate modules:

```
React packager ready.

Loading dependency graph...jest-haste-map: @providesModule naming collision:
  Duplicate module name: babylon
  Paths: <PROJECT PATH>/node_modules/react-native/node_modules/babylon/package.json collides with <PROJECT PATH>/node_modules/react-native/node_modules/babel-traverse/node_modules/babylon/package.json

This warning is caused by a @providesModule declaration with the same name across two different files.
jest-haste-map: @providesModule naming collision:
  Duplicate module name: core-js
  Paths: <PROJECT PATH>/node_modules/react-native/node_modules/core-js/package.json collides with <PROJECT PATH>/node_modules/react-native/node_modules/fbjs/node_modules/core-js/package.json

This warning is caused by a @providesModule declaration with the same name across two different files.
Loading dependency graph, done.
```

**Comment by Benjamin-Dobell** [comment]
Full trace (from iOS):

```
undefined is not an object (evaluating 'ReactInternals.ReactCurrentOwner')

<unknown>
   ReactGlobalSharedState.js:18:36
loadModuleImplementation
   require.js:174:12
<unknown>
   ReactDebugTool.js:18:39
loadModuleImplementation
   require.js:174:12
<unknown>
   ReactInstrumentation.js:19:31
loadModuleImplementation
   require.js:174:12
<unknown>
   ReactNativeMount.js:15:35
loadModuleImplementation
   require.js:174:12
<unknown>
   ReactNativeStack.js:16:31
loadModuleImplementation
   require.js:174:12
<unknown>
   ReactNative.js:18:12
loadModuleImplementation
   require.js:174:12
<unknown>
   NativeMethodsMixin.js:14:26
loadModuleImplementation
   require.js:174:12
<unknown>
   View.js:14:35
loadModuleImplementation
   require.js:174:12
<unknown>
   MapMarker.js:25:5
loadModuleImplementation
   require.js:174:12
<unknown>
   MapView.js:12
loadModuleImplementation
   require.js:174:12
<unknown>
   index.js:1
loadModuleImplementation
   require.js:174:12
<unknown>
   BookingDetailView.js:13
loadModuleImplementation
   require.js:174:12
<unknown>
   BookingDetailScreen.js:19
loadModuleImplementation
   require.js:174:12
<unknown>
   routes.js:1
loadModuleImplementation
   require.js:174:12
<unknown>
   Navigator.js:12
loadModuleImplementation
   require.js:174:12
<unknown>
   DrivetrainMobile.js:49
loadModuleImplementation
   require.js:174:12
<unknown>
   setup.js:22
loadModuleImplementation
   require.js:174:12
<unknown>
   index.ios.js:4:22
loadModuleImplementation
   require.js:174:12
guardedLoadModule
   require.js:119:45
global code
   <unknown file>:0
```

**Comment by Benjamin-Dobell** [comment]
I could have sworn I updated my React peer dependency. Apparently, not!

That was the cause. Sorry!

A note to anyone else trying to run RN from master. Double check the react version in RN's `package.json` matches the one in your app's yarn lockfile.

**Comment by winterrain5** [comment]
i have the same problem in the ios,is there anybody solved it?

**Comment by Benjamin-Dobell** [comment]
@winterrain5 As I mentioned, make sure you've installed the correct version of React. If you're using React Native 0.45:

```
yarn add react@16.0.0-alpha.12
```

**Comment by deathnopool** [comment]
i got the same problem after upgrading to 0.45

**Comment by rclai** [comment]
I'm assuming that you also need to update this too?

```
"react-test-renderer": "16.0.0-alpha.12"
```

**Comment by Liqiankun** [comment]
@Benjamin-Dobell Thank you !

**Comment by joimxjtuse** [comment]
i have the same question in my android project. how to fix it ?  i, package.json:
"dependencies": {
    "react": "16.0.0-alpha.12",
    "react-native": "0.45.1"
  }

**Comment by shenxiaolin** [comment]
Hi
Same problem like above 
My package.json


"name": "RNDemo",
  "version": "1.0.0",
  "description": "",
  "main": "index.android.js",
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "react": "^15.6.1",
    "react-native": "^0.46.0"
  }

**Comment by rajsuvariya** [comment]
@Benjamin-Dobell after adding react@16.0.0-alpha.12, I am getting the following error

![image](https://user-images.githubusercontent.com/12663795/28016000-2ea51d26-6590-11e7-8d1d-c963a41a9a13.png)

I am trying to integrate react native in existing Android app. I am following this guide: [link](https://facebook.github.io/react-native/docs/integration-with-existing-apps.html)

MyReactNativeActivity.java
```
package com.abc.def.react;

import android.app.Activity;
import android.os.Bundle;
import android.view.KeyEvent;

import com.abc.def.BuildConfig;

import com.facebook.react.ReactInstanceManager;
import com.facebook.react.ReactRootView;
import com.facebook.react.common.LifecycleState;
import com.facebook.react.modules.core.DefaultHardwareBackBtnHandler;
import com.facebook.react.shell.MainReactPackage;

public class MyReactActivity extends Activity implements DefaultHardwareBackBtnHandler {
    private ReactRootView mReactRootView;
    private ReactInstanceManager mReactInstanceManager;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        mReactRootView = new ReactRootView(this);
        mReactInstanceManager = ReactInstanceManager.builder()
                .setApplication(getApplication())
                .setBundleAssetName("index.android.bundle")
                .setJSMainModuleName("index.android")
                .addPackage(new MainReactPackage())
                .setUseDeveloperSupport(BuildConfig.DEBUG)
                .setInitialLifecycleState(LifecycleState.RESUMED)
                .build();
        mReactRootView.startReactApplication(mReactInstanceManager, "HelloWorld", null);

        setContentView(mReactRootView);
    }

    @Override
    public void invokeDefaultOnBackPressed() {
        super.onBackPressed();
    }

    @Override
    protected void onPause() {
        super.onPause();

        if (mReactInstanceManager != null) {
            mReactInstanceManager.onHostPause(this);
        }
    }

    @Override
    protected void onResume() {
        super.onResume();

        if (mReactInstanceManager != null) {
            mReactInstanceManager.onHostResume(this, this);
        }
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();

        if (mReactInstanceManager != null) {
            mReactInstanceManager.onHostDestroy(this);
        }
    }

    @Override
    public void onBackPressed() {
        if (mReactInstanceManager != null) {
            mReactInstanceManager.onBackPressed();
        } else {
            super.onBackPressed();
        }
    }

    @Override
    public boolean onKeyUp(int keyCode, KeyEvent event) {
        if (keyCode == KeyEvent.KEYCODE_MENU && mReactInstanceManager != null) {
            mReactInstanceManager.showDevOptionsDialog();
            return true;
        }
        return super.onKeyUp(keyCode, event);
    }

}
```
and index.android.js

```
import React from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';

class HelloWorld extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.hello}>Hello, World</Text>
      </View>
    )
  }
}
var styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
  },
  hello: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
});

AppRegistry.registerComponent('AwesomeProject', () => HelloWorld);
```

**Comment by rajsuvariya** [comment]
@Benjamin-Dobell It worked. Thanks.

**Comment by simonbengtsson** [comment]
Hmm. I'm getting the same message with `react-native: 0.46.0` and `react: 16.0.0-alpha.12`. Probably me doing something stupid on my machine though as I get the same issue no matter what react native example I'm running.

**Comment by saayani** [comment]
This is my `package.json`. Is there any workaround?
`{
  "name": "NowPurchase",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "react-native-scripts": "0.0.50",
    "jest-expo": "~18.0.0",
    "react-test-renderer": "16.0.0-alpha.12"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "node node_modules/jest/bin/jest.js --watch"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "expo": "^18.0.3",
    "react": "16.0.0-alpha.12",
    "react-native": "^0.45.1",
    "react-native-collapsing-toolbar": "^1.0.0-beta.4",
    "react-native-drawer-menu": "^0.2.4",
    "react-native-keyboard-aware-scroll-view": "^0.2.9",
    "react-native-material-design": "^0.3.7",
    "react-native-util": "^1.0.2",
    "react-native-vector-icons": "^4.3.0",
    "react-navigation": "^1.0.0-beta.11",
    "util": "*"
  }
}
`

**Comment by tiofabby** [comment]
Hello
I had same issue when migrating from recat native 0.42.1 to 0.47.0
I did the following and it fixed almost all my issues :
- delete/remove yourProject/node-modules folder
- set up package.json with "react": "16.0.0-alpha.12" and "react-native": "0.47.0"
- npm install
- cd android && gradlew clean
- cd.. && npm start -- --reset-cache
(some react native libraries I had had to be updated also to last version supporting 0.47)

**Comment by saayani** [comment]
Thanks! Resolved it!

**Comment by gameboy87** [comment]
followed @tiofabby But,  NOT WORKING.

![image](https://user-images.githubusercontent.com/1721339/29139690-70a04ae2-7d65-11e7-9af6-803e4df73c3f.png)


package.json configuration is as below.

```
{
	"name": "AwesomeProject",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"start": "node node_modules/react-native/local-cli/cli.js start",
		"test": "jest"
	},
	"dependencies": {
		"react": "16.0.0-alpha.12",
		"react-native": "0.47.0"
	},
	"devDependencies": {
		"babel-jest": "20.0.0",
		"babel-preset-react-native": "1.9.1",
		"jest": "20.0.0",
		"react-test-renderer": "16.0.0-alpha.6"
	},
	"jest": {
		"preset": "react-native"
	}
}
```

**Comment by gameboy87** [comment]
OK. I got it resolved by doing the things below.

1) Check in NPM repo all dependencies are latest for the Project Development.
2) Update each dependencies and run react native again.

Problem Solved ! 👍

**Comment by LinkRober** [comment]
@tiofabby it works for me ,i used 
```
"dependencies": {
    "react": "16.0.0-alpha.12",
    "react-native": "^0.47.2"
  }
```

**Comment by iegik** [comment]
@LinkRober https://github.com/facebook/react-native/issues/15621

**Comment by yudiandian** [comment]
解决方法：把react，react-native安装如下版本就好了
"react": "^16.0.0-alpha.12",
"react-native": "^0.46.4",

**Comment by koliatest** [comment]
解决方法：把react，react-native安装如下版本就好了
What...?

**Comment by dienast** [comment]
I removed the '^' in front of  "16.0.0-alpha.12" and it worked.

**Comment by tetogomez** [comment]
Yep I added react@16.0.0-alpha.12 and it worked for me.
 you guys saved my life hahaha thks !!

**Comment by tintorres** [comment]
react@16.0.0-alpha.12  worked for me too. thanks
