### ISSUE TITLE
To run stickySectionHeadersEnabled={true} wrong.

### ISSUE THREAD

**Issue by 452MJ** [facebook/react-native#13889]
### Description

I want to use SectionList to show some data.

### Reproduction Steps and Sample Code

List all the steps required to reproduce the issue you're reporting. These steps should be clear and concise.

The code' repo: https://github.com/452MJ/Mtime-React-Native/blob/master/app/src/screen/CreditListScreen.js

here's the json url: https://api-m.mtime.cn/Movie/MovieCreditsWithTypes.api?movieId=216008

![1](https://cloud.githubusercontent.com/assets/13673008/25890091/dadf86b6-359e-11e7-8385-c10aee0da207.png)
![2](https://cloud.githubusercontent.com/assets/13673008/25890101/e0e0b12a-359e-11e7-88af-3f0ff3903183.png)

### Solution

To run stickySectionHeadersEnabled={true} well~

### Additional Information

* React Native version: 0.44.0
* Platform:Android
* Development Operating System: Windows
* Dev tools: IntelliJ IDEA 2017.1.2

**Comment by kelset** [comment]
Happening to me too on Android. Any idea for a workaround?

**Comment by 452MJ** [comment]
Not yet.

**Comment by janicduplessis** [comment]
I have some fixes for this, you can try to add removeClippedSubviews={false} as a workaround I think in the meantime

**Comment by kyo504** [comment]
@janicduplessis Any update on this? Even if I set `removeClippedSubviews` to `false`, it happens when scrolling.

- React-Native : 0.44.0
- Platform : Android

**Comment by 452MJ** [comment]
@kyo504 it can run well at the RN version 0.46.1, just set stickySectionHeadersEnabled={true} without removeClippedSubviews={true or false}. Try it.

**Comment by kyo504** [comment]
@452MJ Thanks for your comment. I'll check it :)

**Comment by kyo504** [comment]
@452MJ Great! It works fine now :)
