### ISSUE TITLE
Image Flickers when Updated from 0.42.3 to 0.43.4 and changed from listview to flatlist

### ISSUE THREAD

**Issue by bgoyal2222** [facebook/react-native#13886]
Updated RN from 0.42.3 to 0.43.4 and changed newsfeed component from listview to flatlist
So, whenever we scroll the feed the image flickers

<FlatList
            ref={(c)=>this._listViewRef = c}        
            onViewableItemsChanged={(visibleRows, changedRows) => console.log("yes it works")}
            refreshing={this.state._refreshing}                
            data={this.state._dataSource}
            renderItem={({item})=>this._renderRow(item)}
            enableEmptySections={true}
            onEndReached={()=>{  
              if(this.state._stopLazyLoad == false){
                  return this.fetchNewsFeed()
              }
            }}
            extraData={this.state}
            onEndReachedThreshold={height*4}
            ListHeaderComponent={()=><View style={{paddingTop:15}}/>}
            ListFooterComponent={()=>{
              if(this.state._refreshing == true){
                return null;
              }
              return <View style={{flex:1,justifyContent:'center',alignItems:'center'}}><Loading/></View>
            }}           
         />

* React Native version: 0.43.4
* Platform: android
* Development Operating System: Linux
* Dev tools: Android Studio 2.3,Android SDK Tool 25.2.5

**Comment by stoffern** [comment]
Are you using dataSource from `ListView`? if so that is wrong. it should be a array of data not the datasource from `ListView`

**Comment by bgoyal2222** [comment]
No i am using a json array and data is properly visible as before.. just the issue is images keeps on flickering.. I am not getting why it behaving like this @stoffern

**Comment by stoffern** [comment]
@bgoyal2222 sounds like you have issues with the FlatList rerendering on scroll / `onEndReached`

what does this function do? `fetchNewsFeed`
```js
onEndReached={()=>{
if(this.state._stopLazyLoad == false){
return this.fetchNewsFeed()
}
}}
```

**Comment by bgoyal2222** [comment]
@stoffern that is for when the user reach to the of my feed.. to make a call and fetch further data and display

**Comment by dobrienlzd** [comment]
Is that an async call or are you slowing stuff down with it?

**Comment by bgoyal2222** [comment]
ya thats a fetch api call @dobrienlzd

**Comment by dobrienlzd** [comment]
A few ideas:

Where is the render row function?  Seems like that would be interesting to see!
 
1) Put a timer around this request so you know how long in milliseconds it take. Also just return stubbed data and see if you still notice the flickering.
2) Upgrade to 0.44.0 and let us know what happens?
3) Let's try to get the rending time on the item via callbacks.  See if there is a real difference between 0.42 and 0.43 or not.

Just pick whichever is easiest first. But FlatList get's lots of attention. Last commit just four hours ago so give us some stats!

**Comment by bgoyal2222** [comment]
Thanks for the help.. I am not sure but it seems to be solved when i removed image prop resizeMode='contain'
