### ISSUE TITLE
Examples directory doesn't exist in master branch

### ISSUE THREAD

**Issue by stmoreau** [facebook/react-native#13882]
### Description

As I was reading the "the basics" from the react native official [docs](https://facebook.github.io/react-native/docs/more-resources.html) in the "more resources" section I noticed that the link [Examples/ directory](https://github.com/facebook/react-native/tree/master/Examples) returns 404.

### Solution

Removing the Examples reference in the main README.md and in the /docs/MoreResources.md.

### Additional Information

* React Native version: [0.44]
* Platform: [both]
* Development Operating System: [MacOS]

**Comment by DanielMSchmidt** [comment]
@ericvicenti was this renamed to RNTester? Would volunteer to do a docs renaming PR then ;)

**Comment by stmoreau** [comment]
@DanielMSchmidt yes, I was wrong it was renamed to RNTester. Feel free to do the renaming. I would do it but

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/examples-directory-doesnt-exist-in-master-branch-1
