### ISSUE TITLE
Include of non-modular header inside framework module 'React.RCTConvert'

### ISSUE THREAD

**Issue by matthewfang** [facebook/react-native#13888]
build error:
Include of non-modular header inside framework module 'React.RCTConvert': 'xxx/Build/Products/Debug-iphonesimulator/include/yoga/Yoga.h'
I read the "Integration With Existing Apps" doc, but it also cant build success
what should I do?   RN version:0.44

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/include-of-non-modular-header-inside-framework-module-reactrctconvert
