### ISSUE TITLE
Swift Native UI Components

### ISSUE THREAD

**Issue by mtyang** [facebook/react-native#13892]
Hi, where to get Native UI Components for Swift example? I really like Swift, Thanks!

**Comment by jaygarcia** [comment]
There are lots of examples if you google "react native swift components"

**Comment by mtyang** [comment]
Thank you, I have tried the results of this keyword,  but swift viewController hasn't been solved.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/swift-native-ui-components

**Comment by achadha0111** [comment]
@mtyang Just wondering if you managed to implement it? I have been facing a similar issue and found the documentation to be quite sparse.
