### ISSUE TITLE
[Android > TextInput]: Render Multiline Text at start instead of center?

### ISSUE THREAD

**Issue by joncursi** [facebook/react-native#13897]
If you assign a `height` style to TextInput, on iOS the placeholder & actual text will render at the start of the container. However on Android, the placeholder & text will render at the center.

Code:

```jsx
<TextInput
  ...
  style={{ height: 100 }}
  ...
/>
```

Result:

<img width="669" alt="screen_shot_2017-05-10_at_10_08_55_am" src="https://cloud.githubusercontent.com/assets/4974609/25903479/817a93ec-356a-11e7-904b-4709a4ccc7d2.png">

I'd like to get Android to render at the start, but applying flex / alignItems / justifyContent styles don't seem to have any effect.

**Comment by fagerbua** [comment]
On Android, you need to set `textAlignVertical: "top"` in the style prop to TextInput. Not well documented.

**Comment by joncursi** [comment]
Thank you @fagerbua !

**Comment by pandiaraj44** [comment]
Thanks, @fagerbua, 

I have tried with align-items, justify-content and text align but nothing worked.  After adding textAlignVertical: "top", It's worked.  

Really, Awesome.

**Comment by luck2011** [comment]
Thanks! Saved my day @fagerbua

**Comment by yanhaijing** [comment]
thanks

**Comment by iamtekeste** [comment]
Thanks @fagerbua !!! I spent almost half a day trying to figure it out!

**Comment by fagerbua** [comment]
Issue closed, but should the default behavior on Android and iOS differ like this? If not, perhaps this should be re-opened as a bug report?

**Comment by mattyclarkson** [comment]
It's also really annoying that you cannot do the opposite on iOS, i.e put `textAlignVertical: 'center'` and get the Android behaviour. It's [supported](https://developer.apple.com/documentation/uikit/uicontrol/1618249-contentverticalalignment) by the native widget
