### ISSUE TITLE
Question : Is it possible to call ScrollTo_Y on <ListView/> Component?

### ISSUE THREAD

**Issue by MossP** [facebook/react-native#1389]
i.e. is it possible to call a method that scrolls a \<ListView/\> to a given position - the top in my instance.

**Comment by brentvatne** [comment]
@MossP - you can get the underlying `ScrollView` by calling `getScrollResponder` on it, and then you can call `scrollTo` on that :smile:

**Comment by MossP** [comment]
Thanks @brentvatne I'll try that out, thank you :) :+1:

**Comment by jawadrehman** [comment]
can we scroll to using a rowID ?

**Comment by brentvatne** [comment]
@jawadrehman - you could use the UIManager measureLayoutRelativeToParent function to determine the position and then scroll to that

**Comment by jawadrehman** [comment]
@brentvatne so what parameters would i send to the function ? 

Thanks

**Comment by brentvatne** [comment]
The function signature is:

```
RCT_EXPORT_METHOD(measureLayoutRelativeToParent:(NSNumber *)reactTag
                  errorCallback:(RCTResponseSenderBlock)errorCallback
                  callback:(RCTResponseSenderBlock)callback)
```

So you need to pass in a ref to the component, then an error and success callback - the success callback will give you an array of values:

```
  callback(@[@(leftOffset), @(topOffset), @(width), @(height)]);
```

So let's say that your row has some ref like "mySpecialRow"

then..

```
var UIManager = require('NativeModules').UIManager;

// inside of your component...
React.findNodeHandle(this.refs.mySpecialRow),
function(error) { ... },
function(leftOffset, topOffset, width, height) {
  // Do something
}
```

**Comment by jawadrehman** [comment]
@brentvatne thanks for that... 
I have one more problem, how do i use this.refs.mySpecialRow from a listview, i can't seem to access it if its defined in the renderRow function.

**Comment by VonD** [comment]
Same problem here : the refs defined within the `renderRow` function don't seem to be accessible. 

Besides, the row we wish to scroll to might have not been rendered yet depending on current scroll position and `pageSize` / `scrollRenderAheadDistance ` props.

Does that mean we have to use a `ScrollView` instead of a `ListView` if we want to be able to scroll to any row ?

@jawadrehman have you found a solution ?

**Comment by MossP** [comment]
Hi @VonD I hadn't been trying to scroll to a particular item as you guys had. I was just scrolling to a fixed point (0) so the code provided suffices for me.

**Comment by MattFoley** [comment]
@VonD Needed to do the same thing.

1. Added a ref to my listView
2. Passed a function into the class that is my rendered row to fetch the listView. (`this.state.listView()` below)
3. Added a ref to the outmost node of the render function in my rendered row class
4. On `componentDidUpdate`, called my method which did the scrolling.
5. Used UIManager to calculate the y and height of the cell, as well as the height of the listView using 


My scroll method looked something like this:

```js
var cellHandle = React.findNodeHandle(this.cell);
      UIManager.measureLayoutRelativeToParent(cellHandle, () => {}, (x, cellY, width, cellHeight) => {
        var listHandle = React.findNodeHandle(this.state.listView());
        UIManager.measureLayoutRelativeToParent(listHandle, () => {}, (x, y, width, listHeight) => {
          var position = cellY - ((listHeight / 2) - (cellHeight / 2));
          listView.getScrollResponder().scrollWithoutAnimationTo(Math.round(position), 0);
        });
      });
```

Took awhile to figure this out, part of me really misses `scrollToRowAtIndexPath:` right now.

**Comment by coodoo** [comment]
Just found another way to solve this, steps below

1. In `renderRow` function, store the row element in a map by id
```javascript
var row = <View><Text>{movie.title}</Text></View>;
this.$rows[movie.id] = row;
```

2. Later when you need to find out the position of that row on screen, do this
```javascript
var row1 = this.$rows['12345'];  // 12345 is the id of the row
var handle = React.findNodeHandle(row1._owner);  // must add ._owner here 
var m = UIManager.measureLayoutRelativeToParent(
	handle,
	(err)=>console.log( 'err:', arguments ),
	(x, y, w, h)=>{
		console.log( 'success: ', x,y,w,h );
		this.$scrollView.scrollTo(y, x);
	})
```
