### ISSUE TITLE
[Docs] Add setNativeProps documentation (Original title: clear() function on TextInput)

### ISSUE THREAD

**Issue by dvine-multimedia** [facebook/react-native#1390]
The problem: I need to clear a TextInput after some user interaction.

The request: expose some kind of clear() or even setText() functionality.

I understand that this is exactly the mutative approach to UI programming, that React is trying to get rid of. But as the docs state them selfs, a **controlled** approach to the TextInput component using the **value** property doesn't perform.
My current solution is to set the **value** property to null once on the next render after the user interaction. But this feels rather clunky. Since the declarative approach seems to break down with the TextInput implementation I would argue for exposing the mutative API.

**Comment by brentvatne** [comment]
@dvine-multimedia - are you using `setNativeProps` to set the `value` to null?

[setNativeProps example](https://rnplay.org/plays/pOI9bA/edit)
[controlled setState example](https://rnplay.org/plays/EqK4nA)

**Comment by dvine-multimedia** [comment]
@brentvatne I didn't realize that `setNativeProps` actually is the mutation API I was looking for. Thanks a lot. Maybe there could be some more documentation on that? But I don't know if react really want's to encourrage the usage of `setNativeProps`except for a few special cases.

**Comment by brentvatne** [comment]
@dvine-multimedia - good point, documentation for `setNativeProps` would be useful! Related - it might also be useful to add documentation [for the issues faced in this discussion](https://github.com/bsudekum/react-native-mapbox-gl/issues/28) - also pertaining to communicating directly from js->native

**Comment by grabbou** [comment]
Haven't seen any notes about `blur` and other methods available on a given component, is this something we would be interested in describing as well?

**Comment by ide** [comment]
@grabbou yes, would be good to document public methods like `blur()`.

**Comment by grabbou** [comment]
Also, I am pretty sure that's something you've requested with `setNativeProps` forwarding, but I've found it pretty handy to have `blur` and others forwarded as well.. Say I have a custom `form` component that just wraps underlaying `<View><Input /></View>`. Instead of defining a `blur` and calling it explicitly in the form component, the `blur` method could've been forwarded if not present by default.

**Comment by brentvatne** [comment]
@grabbou - any interest in adding some documentation for `blur()` and `focus()`?

**Comment by grabbou** [comment]
Yeah, can add in some descriptions, any hints what's the appropriate place for them speaking docs structure wise?

**Comment by brentvatne** [comment]
@grabbou - TextInput seems like the best spot

**Comment by brentvatne** [comment]
@grabbou - I'm going to close this issue, can you open a PR for that when it's ready? Thanks :smile:

**Comment by brentvatne** [comment]
Docs that cover setNativeProps for TextInput clearing are here: https://facebook.github.io/react-native/docs/direct-manipulation.html#setnativeprops-to-clear-textinput-value

**Comment by grabbou** [comment]
Ah, nice! Will send over later today.
