### ISSUE TITLE
[Alert] Prop to specify Android button colors

### ISSUE THREAD

**Issue by joncursi** [facebook/react-native#13907]
Would be great if the Alert component allowed some sort of styling props for button colors, specifically on Android. Android defaults to Green 500, but that doesn't always match an app's color theme.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/alert-prop-to-specify-android-button-colors
