### ISSUE TITLE
undefined is not an object (evaluating '_module.getCurrentPosition')

### ISSUE THREAD

**Issue by dalufine** [facebook/react-native#13913]
### Description
when i use [baidu map](https://github.com/lovebing/react-native-baidu-map), we have a tabbar in activity, there are four fragments ,two native and two use react, when switch to MatchFragment ,the err come.

**undefined is not an object (evaluating '_module.getCurrentPosition')
<unknown>
    Geolocation.js:88:16**

![](http://ww4.sinaimg.cn/large/006tNbRwgy1ffhkb1dlrsj30ie0y2adu.jpg)

### Reproduction Steps and Sample Code
![](http://ww3.sinaimg.cn/large/006tNbRwgy1ffhkb2cu6zj313m0u4tex.jpg)
![](http://ww3.sinaimg.cn/large/006tNbRwgy1ffhkb02v45j31bi0q6jxv.jpg)
![](http://ww2.sinaimg.cn/large/006tNbRwgy1ffhkjyfyqhj318a0pw43f.jpg)
![](http://ww3.sinaimg.cn/large/006tNbRwgy1ffhkamtqp0j30zg0putd9.jpg)
![](http://ww1.sinaimg.cn/large/006tNbRwgy1ffhkamcpusj318a0s2dm0.jpg)

**Comment by stoffern** [comment]
This is `react-native-baidu-map` issue / StackOverflow - Not a RN issue.

Make shure you have linked the library and import it correct!
