### ISSUE TITLE
multiline TextInput scrolling

### ISSUE THREAD

**Issue by dvine-multimedia** [facebook/react-native#1391]
I'm building a multiline text input component the grows for the first n lines and after that just scrolls as usual.

The growing it self and the scrolling after it's reached it's maximum height are working fine. But when I grow the box after adding a line break the scroll position of the text in the box is completely off.

For this to work I probably would either need to be able to disable scrolling or to have access to a scrollTo() method. Since I'm completely new to iOS and Objective-C, I unfortunately haven't figured out any of the two yet. Suggestions would be greatly appreciated.

**Comment by brentvatne** [comment]
Hi @dvine-multimedia - check out this pull request: https://github.com/facebook/react-native/pull/1229

If that doesn't help, join us in irc (freenode #reactnative), these types of questions are better suited for discussion in that context :smile:

**Comment by marcshilling** [comment]
@dvine-multimedia could you share your growing text input component? I have a similar need

**Comment by dvine-multimedia** [comment]
@marcshilling Sorry, I abandoned my original approach because it was not working properly. I still haven't figured out, how to access the "onLayoutChange" event of the underlying scroll view for a multi-line input. In addition to that I would also need access to some scrolling functionality to keep the text in the correct position after re-sizing the input. I when with a fixed height input for now but surely will re-evaluate the issue in the not so distant future.

**Comment by chrise86** [comment]
@dvine-multimedia did you ever manage to manipulate the underlying scroll view for a multine input? I have a similar situation where I need to scroll the text input to the bottom after bulk text is inserted.

**Comment by duhecx** [comment]
Same here. Access to the textInput's content scroll would be great.
