### ISSUE TITLE
Links from warnings not clickable or selectable to copy url

### ISSUE THREAD

**Issue by Fenwil** [facebook/react-native#13923]
Would be great to be able to click on the link to open up on a browser or at least to be able to copy it.
I'm refering to the issue link in the picture below inside the red box:
[https://github.com/facebook/react-native/issues/12981
](https://github.com/facebook/react-native/issues/12981
)

![rn](https://cloud.githubusercontent.com/assets/2475912/25961202/d9a9c912-364f-11e7-9085-07ea8019e268.png)

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/links-from-warnings-not-clickable-or-selectable-to-copy-url
