### ISSUE TITLE
Ctrl-C on Fedora 24 doesn't clean up processes

### ISSUE THREAD

**Issue by vietnugent** [facebook/react-native#13937]
In Fedora 24 environment  Ctrl-C doesn't really stop `react-native run-android` related processes.  I had to manually kill them in between runs.

Version:  react-native-cli: 2.0.1
Node: v7.10.0
OS env:  Fedora 24

```
15515     1  0 May11 ?        00:00:00 sh node_modules/react-native/packager/launchPackager.command
15520 15515  0 May11 ?        00:00:56 node_modules/react-native/packager/../local-cli/cli.js start
 15551 15520  0 May11 ?        00:00:22 /usr/local/bin/node node_modules/worker-farm/lib/child/index.js

```

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/ctrl-c-on-fedora-24-doesnt-clean-up-processes
