### ISSUE TITLE
ActionSheetIOS on iPad - Crash with Illegal callback invocation from native module. This callback type only permits a single invocation from native code.

### ISSUE THREAD

**Issue by ptfly** [facebook/react-native#13936]
### Description

on iPad - iOS 9.3.5 when fast tap on a button which triggers ActionSheetIOS the app crashes with the following message:

Xcode:
```
[fatal][tid:main] Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
```

RN red screen:
```
Illegal callback invocation from native module. This callback type only permits a single invocation from native code.

RCTFatal
RCTCheckCallbackMutipleInvocations
__41-[RTCModuleMethod processMethodSigniture]_block_invoke_3
__61-[RCTActionsSheetManager showActionSheerWithOptions:callback:]_block_invoke
...
```

### Reproduction Steps and Sample Code

Create a button with onPress action set to `askForOptions()`, quickly tap multiple times on that button, watch the magic happens.

```
askForOptions()
    {
        const BUTTONS = [ 'Option 0', 'Option 1', 'Option 2', 'Delete', 'Cancel', ];
        const DESTRUCTIVE_INDEX = 3;
        const CANCEL_INDEX = 4;

        const options = {
            options: BUTTONS, cancelButtonIndex: CANCEL_INDEX, destructiveButtonIndex: DESTRUCTIVE_INDEX,
        };

        ActionSheetIOS.showActionSheetWithOptions(options, (buttonIndex) => console.log(buttonIndex));
    }
```
### Solution

Not failing, or failing without crashing the app.

### Additional Information

* React Native version: [0.44.0]
* Platform: iOS
* Development Operating System: MacOS
* Dev tools: XCode, WebStorm

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/actionsheetios-on-ipad---crash-with-illegal-callback-invocation-from-native-modu
