### ISSUE TITLE
why delete Navigator?  react-navigation is uncapable、bugly and hard to use!

### ISSUE THREAD

**Issue by aqnaruto** [facebook/react-native#13934]
such as: https://github.com/react-community/react-navigation/issues/1467

in rn 0.44 Navigator is deleted
please do not delete navigator ,it is easy to customize and easy to enhance and this one is bugly

**Comment by tanotify** [comment]
After understanding principles of using the new navigation, I found it much more attractive for my project

**Comment by janicduplessis** [comment]
If you want to keep using Navigator it is available in a separate package now https://github.com/facebookarchive/react-native-custom-components

**Comment by aqnaruto** [comment]
thank you @janicduplessis ,  do you test the new navigator ,i test it in android  35-40fps on genymotion android  @tanotify

**Comment by aqnaruto** [comment]
@tanotify 
if it really work or made some enhancement , i will really been grateful with this 。
but,talking is cheap, by my test  i use the navigator , 28~40 fps to open a webview , in react navigation,enven the same,and it still not support goback-gesture。
i wish you can try it ,and  compare each other,and do really some thing useful
