### ISSUE TITLE
overflow not work

### ISSUE THREAD

**Issue by wollld** [facebook/react-native#13932]
`<View style={{borderRadius:15,borderWidth:1,width:100,height:115,borderColor:"#ffee5b",overflow:"hidden"}}>
                    <View  style={{width: 100,
                        height: 100,
                        backgroundColor:"#f1f"}}>
                    </View>
</View>`

overflow not work；  inner View is over outter view ；

**Comment by stoffern** [comment]
This is a dupe.
@wollld Please check if there are related issues before creating one.
https://github.com/facebook/react-native/issues/3198
