### ISSUE TITLE
99% CPU Usage by React Native Debugger when tab is backgrounded

### ISSUE THREAD

**Issue by dylanpyle** [facebook/react-native#13949]
### Description

When the React Native Debugger tab is in the background in Google Chrome, CPU usage spikes incredibly high. I've only started noticing this in the past couple of days - maybe related to a Chrome update?

### Reproduction Steps

1. Start packager and device simulator
2. Enable remote JS debugging
3. Open Chrome's developer tools in the React Native Debugger tab
4. Change to another tab

![screen shot 2017-05-12 at 12 56 56 pm](https://cloud.githubusercontent.com/assets/806257/26008454/d445d308-3712-11e7-9a76-bc9cd0cbbf52.png)
![screen shot 2017-05-12 at 12 57 07 pm](https://cloud.githubusercontent.com/assets/806257/26008455/d44677d6-3712-11e7-9907-e51afe081a7d.png)

Recording with the "Performance" tool doesn't reveal any unexpected CPU usage — looks like it's actually the Chrome developer tools themselves that are using the CPU?

### Additional Information

* React Native version: 0.42.0
* Platform: iOS
* Development Operating System: macOS 10.12.4
* Chrome: 59.0.3071.47

**Comment by Kureev** [comment]
This is a known issue. The warning message in your console proves it. Do you think it's unclear and / or we can do something better communicating it?

**Comment by dylanpyle** [comment]
@kureev the only warning I see there is about the performance of the simulator app itself being poor - which seems unavoidable if Chrome throttles background tabs, but I'm not clear on why that would cause 99% CPU usage all of a sudden. I've been using React Native heavily for about 6 months and this is a new symptom for me.

**Comment by dylanpyle** [comment]
(if the CPU usage is also a known issue, is there an issue number this should be merged into?)

**Comment by dylanpyle** [comment]
I'm no longer seeing this issue (same Chrome version). I'll close this if nobody sees it again in the next few days. Maybe just hit a weird edge case.

**Comment by dylanpyle** [comment]
disregard previous message, issue is still present

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/99-cpu-usage-by-react-native-debugger-when-tab-is-backgrounded

**Comment by tywoodpav** [comment]
I have this issue after upgrading to XCode 9 and using the iphone 8 simulator. @hramos and his damn iceboxes. react native 44
