### ISSUE TITLE
[React] mountComponent absorbing all errors

### ISSUE THREAD

**Issue by vishl** [facebook/react-native#1394]
When I have an error in my component (e.g. using `styles=` instead of `style=`). The exception handler in mountComponent is catching it and not displaying any error messages.  It would be preferable to at least print the error to the console.  Relevant lines below:

ReactCompositeComponent.js[225:238]
```javascript
    try {
      if (inst.componentWillMount) {
        inst.componentWillMount();
        // When mounting, calls to `setState` by `componentWillMount` will set
        // `this._pendingStateQueue` without triggering a re-render.
        if (this._pendingStateQueue) {
          inst.state = this._processPendingState(inst.props, inst.context);
        }
      }

      renderedElement = this._renderValidatedComponent();
    } finally {
      ReactLifeCycle.currentlyMountingInstance = previouslyMounting;
    }
```

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by javache** [comment]
When using the `try { ... } finally { ... }` construct, the exception won't be caught actually, just the finally block will be executed, to allow for cleanup. If you're not seeing your exception being reported, it must be caught elsewhere.
