### ISSUE TITLE
Clipboard.getString() not retrieving clipboard data.

### ISSUE THREAD

**Issue by shubhnik** [facebook/react-native#13940]
### Description

I was using a bluetooth barcode scanner which pastes the scanned data onto clipboard, the data scanned is pasted to notes(proof that data once scanned is pasted to clipboard).When i tried to get the clipboard data with Clipboard.getString(),it doesn't show any data.Am i doing something wrong?

### Reproduction Steps and Sample Code

```
export default class ReadClipboard extends Component {
    getValue(){
        Clipboard.getString((res) => {
            alert(res)
        })
render() {
        return (
            <View>
                <TouchableOpacity 
  style={{height:70,width:100,backgroundColor:'cyan',alignSelf:'center'}}  
  onPress={this.getValue.bind(this)}
               >
                    <Text>clipboard</Text>
                </TouchableOpacity>
            </View>
 );
    }
}
```

### Additional Information

* React Native version: 0.44.0
* Platform: Both
* Development Operating System: macOS

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/clipboardgetstring-not-retrieving-clipboard-data

**Comment by johnckendall** [comment]
Still isn't working as of 0.50
