### ISSUE TITLE
[0.45] Commits to cherry pick into 0.45-stable

### ISSUE THREAD

**Issue by oblador** [facebook/react-native#13958]
Ship third-party-podspecs in the npm package: https://github.com/facebook/react-native/commit/562f6c55fae4b5aa02cbc3b883a43e81d3429dc6

**Comment by stoffern** [comment]
Fixes symbolication errors on windows: https://github.com/facebook/react-native/commit/074fd33725626530c68d897150413a13715280a1
cc @janicduplessis

**Comment by stoffern** [comment]
`Relay Modern` is not working on React Native, because of core-js.
Update `core-js` to add this commit https://github.com/zloirock/core-js/issues/297
More info here: https://github.com/facebook/relay/issues/1704
cc @davidaurelio

**Comment by davidaurelio** [comment]
are you referring to `Map.js` and `Set.js` in https://github.com/facebook/react-native/tree/master/Libraries/vendor/core?

**Comment by oblador** [comment]
cc @grabbou

**Comment by sjmueller** [comment]
Keep an eye on this sleeper: #14328, it breaks all swift projects by failing to compile.
