### ISSUE TITLE
Type com/facebook/react/modules/core/JavascriptException not present

### ISSUE THREAD

**Issue by mavenave** [facebook/react-native#13962]
### Description

This happens on both debug and release variants using the commands react-native run-android and react-native run-android --variant=release respectively.

However, when I run the same run commands on the Android emulator, everything runs fine, even the release build.

I also asked a [StackOverflow question](http://stackoverflow.com/questions/43961329/type-com-facebook-react-modules-core-javascriptexception-not-present)
![image](https://cloud.githubusercontent.com/assets/5748750/26032005/9b5fc72a-38ba-11e7-8980-168a9088a11f.png)

What I've tried so far:

- `rm -r node_modules`
- `yarn cache clean`
- `react-native unlink, react-native link`
- `./gradlew clean`
- `Allowing permission for app to display popup window`

Notes:

- `USB debugging enabled`
- `Install via USB enabled`
- `Verify apps over USB disabled`

From the stack trace, my guess is that there was some error loading JSC on my phone or something.

### Reproduction Steps and Sample Code

1. Get a MIUI phone.
2. `react-native run-android`.
3. Error occurs.

### Additional Information

* React Native version: 0.43.3
* Platform: Android
* Development Operating System: macOS
* Dev tools: Gradle 2.14.1

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/type-comfacebookreactmodulescorejavascriptexception-not-present
