### ISSUE TITLE
run execCommand insertImage in ios webview cannot show img

### ISSUE THREAD

**Issue by Tomatoo** [facebook/react-native#13968]
### Description

```
var html = '<img src="http://cdn.sketchpan.com/member/g/gytmd589/draw/1232327402671/0.png"alt="test"/>';

document.execCommand('insertHTML', false, html);
```

cannot show image in ios simulator,bug can work on android simulator.

![screenshot](http://i1.piimg.com/591829/41b797fc7bb6faad.png)

### Additional Information

* React Native version: 0.40
* Platform: ios simulator[](url)

**Comment by hramos** [comment]
This may be due to the fact the resource is not served over HTTPS. Closing as this does not seem to be a RN issue.
