### ISSUE TITLE
[Packager] Run `npm start` when launching app, rather than directly calling the packager

### ISSUE THREAD

**Issue by itsananderson** [facebook/react-native#1396]
When you build a React Native app in Xcode, it launches the packager, which is super useful for basic scenarios. Unfortunately, if you need to customize the packager (like having it watch extra folders for changes), or use a completely different packager, there's a bit more manual work that's required to shut down the default packager and launch the custom one.

Rather than directly launching the `packager.sh` script, would it be possible to execute the `npm start` command from Xcode? By default, this command is already configured to run `packager.sh`, but it would enable a simple place to plug in a custom packager.

One scenario where this is useful is if you `npm link` in a package from another folder. By default, the packager won't watch that folder for changes, but the `--root` flag makes it really easy to also watch that folder for changes, so just modifying the `package.json` and adding `--root ~/custom-folder/` would make that scenario work (without having to manually run `npm start`)

**Comment by ide** [comment]
This sounds like a reasonable proposal to me. Just to throw another idea out there, you could also configure Xcode to call your custom packager script directly. It's just a question of whether the level of indirection is at the Xcode script or package.json.

**Comment by JohnyDays** [comment]
I would argue people coming from javascript development are more familiar with the indirection in package.json, and would have to learn how to change Xcode scripts.

**Comment by jtremback** [comment]
:+1:

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by Thegaram** [comment]
Is there any progress on this? I want to do exactly what @itsananderson mentioned (pass `--root ~/custom-folder/` to the packager script). I expected to be able to change the startup script manually in Xcode (e.g. to `npm start`), but I couldn't find where it's defined. Could you help?

**Comment by mroswald** [comment]
Kind of annoying - do I have to change a dependency locally to use a different bundling process? This is not very useful when working in teams? Please make it configurable to use the internal package or not.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/packager-run-npm-start-when-launching-app-rather-than-directly-calling-the-packager

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
