### ISSUE TITLE
ImageEditor is not working on Android, react native v0.43.3

### ISSUE THREAD

**Issue by LEEY19** [facebook/react-native#13965]
ImageEditor is not working on Android, react native v0.43.3

ImageEditor.cropImage(
      this.state.path,
      {offset: {
          x: 0,
          y: 0,
        },
        size: {
          width: width * 0.5,
          height: height * 0.1,
      }},
      (croppedImageURI) => console.log("succes"),
      (cropError) => console.log("fail")
    );
I have checked to ensure that this.state.path is valid, width and height are valid as well. Image is locally stored. I imported ImageEditor above. Issue is that, neither success or fail is logged, so meaning neither of the success or failure callbacks are triggered. No error was thrown as well.

**Comment by martwetzels** [comment]
How did you resolve this issue? on iOS it is working fine but on Android it throws me the error: 'unknown protocol: data' from `data:image/jpeg;base64,${photo.data.userPhoto}`.

**Comment by jbaek7023** [comment]
Other people and I are having same problem. I guess no one cares about ImageEditor. Sad

**Comment by martwetzels** [comment]
@jbaek7023 We are using react-native-image-resizer with react-native-fetch-blob to get the job done. Hopefully that will help you.

**Comment by jbaek7023** [comment]
Thanks for your comment! 

@martwetzels Are you using Expo? I have to detach whole project to use react-native-fetch-blob, so I'm hesitating to do so.

**Comment by martwetzels** [comment]
@jbaek7023 We are not using Expo.
