### ISSUE TITLE
Error for generate final apk

### ISSUE THREAD

**Issue by payamka** [facebook/react-native#13969]
Hi
When I want to generate APK file for below command I get an error:
cd android && ./gradlew assembleRelease

And the error is:
'.' is not recognized as an internal or external command,
operable program or batch file.

First command is working fine and change directory to android but the second one doesn't work.
What is the problem?

**Comment by DailyIncome** [comment]
After you're in android folder  try to use it **gradlew assembleRelease** without **./**, it work for me

**Comment by payamka** [comment]
Thanks, It works for me too!
