### ISSUE TITLE
Using genymotion instead of AVD

### ISSUE THREAD

**Issue by payamka** [facebook/react-native#13963]
Hi
How can I use Genymotion instead of AVD? While Genymotion is runing but AVD not runing I get build error but while AVD is runing all thnigs is OK!
I want to replace Genymotion with AVD completly, Is it possible?
I'm usnig Win 8

**Comment by saubcy** [comment]
in the Genymotion:
Settings->ADB->Use custom Android SDK tools, choose the adb.exe in your Win8 folder
or you could override the adb.exe with the Genymotion's, that may works for you.

**Comment by payamka** [comment]
@saubcy Thanks, It works for me!
