### ISSUE TITLE
NPM Start Failed ELIFECYCLE - Failed at the WelcomeToVR@0.0.1 start script

### ISSUE THREAD

**Issue by arcayne** [facebook/react-native#13975]
### Description

followed instruction on https://facebook.github.io/react-vr/docs/getting-started.html#content

and finally typed npm start 

and got:

`npm  start

> WelcomeToVR@0.0.1 start /Users/joandearcayne/Documents/Dev/reactvr/WelcomeToVR
> node -e "console.log('open browser at http://localhost:8081/vr/\n\n');" && node node_modules/react-native/local-cli/cli.js start

open browser at http://localhost:8081/vr/

 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  Running packager on port 8081.                                            │ 
 │                                                                            │ 
 │  Keep this packager running while developing on any JS projects. Feel      │ 
 │  free to close this tab and run your own packager instance if you          │ 
 │  prefer.                                                                   │ 
 │                                                                            │ 
 │  https://github.com/facebook/react-native                                  │ 
 │                                                                            │ 
 └────────────────────────────────────────────────────────────────────────────┘ 
Looking for JS files in
   /Users/joandearcayne/Documents/Dev/reactvr/WelcomeToVR 

Loading dependency graph...
React packager ready.

2017-05-15 14:21 node[11372] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-05-15 14:21 node[11372] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-05-15 14:21 node[11372] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-05-15 14:21 node[11372] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-05-15 14:21 node[11372] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
 ERROR  watch null EMFILE
{"code":"EMFILE","errno":"EMFILE","syscall":"watch null","filename":null}
Error: watch null EMFILE
    at exports._errnoException (util.js:907:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1217:21)

See http://facebook.github.io/react-native/docs/troubleshooting.html
for common problems and solutions.

npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! WelcomeToVR@0.0.1 start: `node -e "console.log('open browser at http://localhost:8081/vr/\n\n');" && node node_modules/react-native/local-cli/cli.js start`
npm ERR! Exit status 11
npm ERR! 
npm ERR! Failed at the WelcomeToVR@0.0.1 start script 'node -e "console.log('open browser at http://localhost:8081/vr/\n\n');" && node node_modules/react-native/local-cli/cli.js start'.
npm ERR! This is most likely a problem with the WelcomeToVR package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node -e "console.log('open browser at http://localhost:8081/vr/\n\n');" && node node_modules/react-native/local-cli/cli.js start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs WelcomeToVR
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls WelcomeToVR
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/joandearcayne/Documents/Dev/reactvr/WelcomeToVR/npm-debug.log
`

### Additional Information

* React Native version: [React VR Command Line Interface
Version 0.3.1

* Platform: - 
* Development Operating System: MacOS Sierra 10.12.4

**Comment by arcayne** [comment]
Adding logs
[LogNpmStartReactVR.txt](https://github.com/facebook/react-native/files/1001087/LogNpmStartReactVR.txt)

**Comment by hramos** [comment]
Looks like this is a react-vr issue.

**Comment by rpgroot** [comment]
install watchman and start npm , resolve this problem by install watchman
