### ISSUE TITLE
Android crashes when calling AsyncStorage.multiRemove on an empty array

### ISSUE THREAD

**Issue by MajorJ** [facebook/react-native#13982]
### Description

Calling AsyncStorage.multiRemove on an empty array throws an error in Android, but works fine in iOS. The thrown error is an empty object.

### Reproduction Steps and Sample Code

Example: (see https://snack.expo.io/Hkgy9sDx-)

### Additional Information

* React Native version: 0.43
* Platform: Android
* Development Operating System: macOS
* Dev tools: Expo SDK 16.0.0

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/android-crashes-when-calling-asyncstoragemultiremove-on-an-empty-array
