### ISSUE TITLE
Android crash  by pthread_create (1040KB stack) failed: Out of memory

### ISSUE THREAD

**Issue by killnono** [facebook/react-native#13992]
environment：
Android 7.0
Rn 0.44

if i setUseDeveloperSupport（true）,
`java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Out of memory
	at java.lang.Thread.nativeCreate(Thread.java)
	at java.lang.Thread.start(Thread.java:745)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:941)
	at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1009)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1151)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:776)`

use android studio  Start Allocation Tracking 
i find the app alway create thread,like this
![image](https://cloud.githubusercontent.com/assets/1185038/26093174/54aac738-3a47-11e7-902d-d440ab711221.png)

Otherwise，setUseDeveloperSupport（fasle），that's ok .

**Comment by dobrienlzd** [comment]
I think we need to know more about your app!  Maybe your running Unity 3d for all we know!

**Comment by undef1ned** [comment]
Im having the same issue, RN 0.44.0, actually the app is in production, so Im getting bugsnag reports

`java.lang.OutOfMemoryError·pthread_create (1040KB stack) failed: Try again


Thread.java:-2java.lang.Thread.nativeCreate	
Thread.java:1063java.lang.Thread.start	
ThreadPoolExecutor.java:920java.util.concurrent.ThreadPoolExecutor.addWorker	
ThreadPoolExecutor.java:1338java.util.concurrent.ThreadPoolExecutor.execute	
ConnectionPool.java:135okhttp3.ConnectionPool.put	
OkHttpClient.java:149okhttp3.OkHttpClient$1.put	
StreamAllocation.java:188okhttp3.internal.connection.StreamAllocation.findConnection	
StreamAllocation.java:129okhttp3.internal.connection.StreamAllocation.findHealthyConnection	
StreamAllocation.java:98okhttp3.internal.connection.StreamAllocation.newStream	
ConnectInterceptor.java:42okhttp3.internal.connection.ConnectInterceptor.intercept	
RealInterceptorChain.java:92okhttp3.internal.http.RealInterceptorChain.proceed	
RealInterceptorChain.java:67okhttp3.internal.http.RealInterceptorChain.proceed	
CacheInterceptor.java:109okhttp3.internal.cache.CacheInterceptor.intercept	
RealInterceptorChain.java:92okhttp3.internal.http.RealInterceptorChain.proceed	
RealInterceptorChain.java:67okhttp3.internal.http.RealInterceptorChain.proceed	
BridgeInterceptor.java:93okhttp3.internal.http.BridgeInterceptor.intercept	
RealInterceptorChain.java:92okhttp3.internal.http.RealInterceptorChain.proceed	
RetryAndFollowUpInterceptor.java:124okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept	
RealInterceptorChain.java:92okhttp3.internal.http.RealInterceptorChain.proceed	
RealInterceptorChain.java:67okhttp3.internal.http.RealInterceptorChain.proceed	
RealCall.java:170okhttp3.RealCall.getResponseWithInterceptorChain	
RealCall.java:33okhttp3.RealCall.access$100	
RealCall.java:120okhttp3.RealCall$AsyncCall.execute	
NamedRunnable.java:32okhttp3.internal.NamedRunnable.run	
ThreadPoolExecutor.java:1112java.util.concurrent.ThreadPoolExecutor.runWorker	
ThreadPoolExecutor.java:587java.util.concurrent.ThreadPoolExecutor$Worker.run	
Thread.java:818java.lang.Thread.run`

**Comment by dobrienlzd** [comment]
Can either of you say what device this is on? is that top secret or something?

**Comment by undef1ned** [comment]
@dobrienlzd 

pthread_create (1040KB stack) failed: Try again

> model Moto G (5) Plus
> networkAccess wifi
> osBuild NPN25.137-33
> osVersion 7.0

> model HTC One_E8 dual sim
> networkAccess wifi
> osBuild MMB29M release-keys
> osVersion 6.0.1

> model LG-D802
> networkAccess cellular
> osBuild LRX22G
> osVersion 5.0.2

> model HTC One dual sim
> networkAccess wifi
> osBuild LRX22G release-keys
> osVersion 5.0.2

> model SM-T805M
> networkAccess wifi
> osBuild LRX22G.T805MUBU1BPB1
> osVersion 5.0.2

> model MotoG3
> networkAccess wifi
> osBuild MPIS24.65-33.1-2-16
> osVersion 6.0

> model LG-H440n
> networkAccess wifi
> osBuild MRA58K
> osName android
> osVersion 6.0

and lots of other devices

**Comment by dobrienlzd** [comment]
"react-native": "^0.44.0",  does not actually require version 0.44.0 to be installed.  First see if it really is installed with 
     npm list | grep 'react@'
     npm list | grep 'react-native@'

if not remove delete node_modules
then remove the ^ in front of the versions for react and react-native and do
npm install 

Check again that right versions are installed.

**Comment by dobrienlzd** [comment]
also not sure about version on socket.io-client latest is much higher 2.0.1

**Comment by undef1ned** [comment]
@dobrienlzd 

ok, will update the socket.io-client (2.0 released 8 days ago). I dont think it could be a problem at all, since native code fails

> npm list | grep 'react-native@'
> ├─┬ bugsnag-react-native@2.2.3
> ├─┬ react-native@0.44.0
> │ ├─┬ babel-preset-react-native@1.9.1
> npm ERR! peer dep missing: react@>=0.14.5, required by react-native-notifications@1.1.10
> npm ERR! invalid: react-native-fit-image@1.3.2 /Users/undef1ned/ReactNative/app-mobile/node_modules/react-native-fit-image
> npm ERR! invalid: react-native-htmlview@0.1.1 /Users/undef1ned/ReactNative/app-mobile/node_modules/react-native-htmlview
> npm ERR! extraneous: entities@1.1.1 /Users/undef1ned/ReactNative/app-mobile/node_modules/entities
> npm ERR! extraneous: htmlparser2-without-node-native@3.9.0 /Users/undef1ned/ReactNative/app-mobile/node_modules/htmlparser2-without-node-native
> npm ERR! invalid: react-native-scrollable-tab-view@0.7.3 /Users/undef1ned/ReactNative/app-mobile/node_modules/react-native-scrollable-tab-view
> npm ERR! peer dep missing: react@^0.13.0 || ^0.14.0 || ^15.0.0, required by react-static-container@1.0.1
> npm ERR! extraneous: react-static-container@1.0.1 /Users/undef1ned/ReactNative/app-mobile/node_modules/react-static-container

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/android-crash--by-pthreadcreate-1040kb-stack-failed-out-of-memory

**Comment by ominfowave** [comment]
I have a facing same issue with android version 5.0

**Comment by lius0828** [comment]
I have a facing same issue with android version 7.0
