### ISSUE TITLE
NavigatorIOS not rendering initial route component

### ISSUE THREAD

**Issue by timotius02** [facebook/react-native#14004]
### Description
When using NavigatorIOS, I expect it to render the component passed to the initialRoute prop of NavigatorIOS. However, it only renders the navigation bar with the title of the route. 

### Reproduction Steps and Sample Code

1. Initialized react-native app.
2. Modify code in index.ios.js
3. Run react-native run-android

Code Example: https://snack.expo.io/r1gqllteZ
The example is a modified version of code in the first example in the [doc](https://facebook.github.io/react-native/docs/navigatorios.html).

### Additional Information

* React Native version: 0.44.0
* Platform: iOS
* Development Operating System: macOS
* Dev tools: Xcode version 8.0, iOS version 10.0

**Comment by hramos** [comment]
This is working fine, as you can tell by the navigation header displaying "Initial Route" at the top. You're just missing some styles that would make your text visible. Example: https://snack.expo.io/SJgA-ZFl-

**Comment by timotius02** [comment]
*Face Palm*

Thanks for the quick response @hramos 😄

**Comment by nicewahson** [comment]
what can i do if it doesn't work?i copy the code on the official websiteo(╯□╰)o

**Comment by nicewahson** [comment]
this can not work on my xcode simulator. Ant other way?

**Comment by harshita-dhingra** [comment]
You are a saviour! !hramos
