### ISSUE TITLE
[Navigator] Components of inactive Navigator scenes intercepting touch events

### ISSUE THREAD

**Issue by ide** [facebook/react-native#1401]
With master (0.5.0-rc) I occasionally encountered touch events being received by components in a scene that's not visible but is in my initial route stack. The initial route stack has two scenes, the bottom scene and top scene. The initial route is the bottom scene's.

Some touches in the bottom scene are sent to the components in the top scene, even though the top scene isn't active. That is, the bottom scene is still visible and has focus. The top scene has never been pushed/jumped to.

Looking at the UIView hierarchy, the root of the top scene is 0px wide and 667px tall and its children are not clipped. If it makes sense for the Navigator to mount scenes that aren't active, it might make sense to implement `visibility: hidden` (#1322) so that only the shadow views are created. In the meantime, `opacity: 0` seems to stop intercepting the touch events.

**Comment by PhilippKrone** [comment]
@ide Do you have any update here? I have the same at the moment

**Comment by ide** [comment]
> I dont really know what you mean with "opacity:0" here - should I set it dynamically on all inactive scenes?

Yes but this works only on iOS.

**Comment by PhilippKrone** [comment]
But thats not really a good solution, is it? Gives a lot of non-functional code for something which sounds like a bug for me. Can you give me a hint how to tackle this issue by creating a PR?

**Comment by ide** [comment]
It's not a great solution which is why I only use it in my own copy of react native. The problem is that navigator hides scenes using overflow:hidden on a zero-width element but the overflowing elements still receive touches. There's also that prop to clip overflowed subviews that might work as well though I haven't tried it. If you discover a good approach you could submit a PR.

**Comment by ide** [comment]
Another approach is to use initialRoute instead of initialRouteStack.

**Comment by PhilippKrone** [comment]
Adding

````javascript
            removeClippedSubviews={true}
````

worked. I'll create a PR for that, or do you see any disadvantage here?

**Comment by ide** [comment]
I would send the PR and then the engineers at FB working on navigator could take a look at it. It seems like a good approach to me though.
