### ISSUE TITLE
Documentation for doing a sharable debug build on Android?

### ISSUE THREAD

**Issue by dobrienlzd** [facebook/react-native#14017]
I don't see any documentation on how to create a debug.apk that can be shared and run on Android devices without switching ports etc.   What steps need to be done a debug build. I want a apk that does not produce bridge errors etc when it is released. Is this possible?

Just to clarify I am not talking about how to debug on a device. My question is how can I create an debug APK that I could give to QA and let them run the app and look at the logs and test the UI without having to do a full release build?

This is what people are doing now: http://stackoverflow.com/questions/35283959/build-and-install-unsigned-apk-on-device-without-the-development-server/36961021#36961021

What's the latest and best way to do this with RN 0.44 ?

React Native 0.44
Android  19+

**Comment by hramos** [comment]
Closing as this is not specifically an issue.
