### ISSUE TITLE
Failed prop type: prop type is invalid (Text.propTypes.style.isRequired)

### ISSUE THREAD

**Issue by xareelee** [facebook/react-native#14026]
### Description, Reproduction Steps and Sample Code

I wrote a React Native component:

```js
export const OneLineText = ({ textStyle, title }) => (
  <Text style={textStyle} numberOfLines={1}>
    {title}
  </Text>
);

OneLineText.propTypes = {
  textStyle: Text.propTypes.style.isRequired,
  title: PropTypes.string.isRequired,
};
```

Run `jest --watch`, and it shows warning:

```
Warning: Failed prop type: OneLineText: prop type `textStyle` is invalid; it must be a function, usually from React.PropTypes.
    in OneLineText (created by LeftTextContainer)
    in ...
    ...
```

After deleting the `isRequired` in the line `textStyle: Text.propTypes.style.isRequired`, the warning is gone, but I need this `prop` to be `required`.

### Additional Information

* React Native version: 0.44
* Dev tools: while jest testing

**Comment by jkomyno** [comment]
Same here. The solution would be to manually mock PropTypes, but I'm sure there should be something way cleaner at disposal to fix this. @xareelee, you might want to submit your issue [here](https://github.com/facebook/prop-types/issues), as PropTypes has been detached from the main React package, and PropTypes aren't strictly bound to React Native.

**Comment by xareelee** [comment]
@jkomyno Thanks for your reply and info.

I currently switch to use Flowtype system instead of PropTypes.

Close this issue anyway.
