### ISSUE TITLE
AsyncStorage#removeItem returns null rather than a Promise

### ISSUE THREAD

**Issue by thebigredgeek** [facebook/react-native#14024]
### Description

```js
import { AsyncStorage } from 'react-native';

const keyGen = key => `@BoostMobile:${key}`;

const r = AsyncStorage.removeItem(keyGen('helloWorld'));

console.log('removeItem return', r);
```

yields
 
```
removeItem return null
```
* React Native version: 0.43.2
* Platform: ios
* Development Operating System: osx
* Dev tools: expo, atom, unix cli

**Comment by jordanpapaleo** [comment]
This is from 0.43.2

Here is the code for removeItem and yes it does return a promise.

```javascript
removeItem: function(
  key: string,
  callback?: ?(error: ?Error) => void
): Promise {
  return new Promise((resolve, reject) => {
    RCTAsyncStorage.multiRemove([key], function(errors) {
      var errs = convertErrors(errors);
      callback && callback(errs && errs[0]);
      if (errs) {
        reject(errs[0]);
      } else {
        resolve(null);
      }
    });
  });
}
```

Using your code in my app:

```javascript
import {AsyncStorage} from 'react-native'
const keyGen = key => `@BoostMobile:${key}`;
const r = AsyncStorage.removeItem(keyGen('helloWorld'));
console.log('removeItem return', r); // Shows a Promise

AsyncStorage.removeItem(keyGen('helloWorld')).then(
  () => {
    console.log('resolved')
  },
  () => {
    console.log('rejected')
  }
)
```

Also resolved is logged for me.

**Comment by thebigredgeek** [comment]
Interesting.  I am definitely NOT seeing that behavior.  I literally ran the above code I pasted in my Expo app and out comes `null` rather than a Promise.  I actually discovered this because I was attempting to interact with the result as a Promise... which was causing a reference error.  Took me 30 minutes to figure out just how bizarre the problem was

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/asyncstorageremoveitem-returns-null-rather-than-a-promise
