### ISSUE TITLE
Getting startet should be edited for new Android Studio because it doesn't work

### ISSUE THREAD

**Issue by sefel** [facebook/react-native#14035]
New version of Android Studio is not compatibile with Getting startet description of react-native. It need update.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/getting-startet-should-be-edited-for-new-android-studio-because-it-doesnt-work
