### ISSUE TITLE
undefined is not an object(evaluating 'ViewPropTypes.style')

### ISSUE THREAD

**Issue by dalufine** [facebook/react-native#14032]
### Description

When i clone a project from git, after **'npm install'** **react-native run-ios**,the error coming.But others in team can run success.

### Reproduction Steps and Sample Code

![](http://ww4.sinaimg.cn/large/006tKfTcgy1ffpiaxezb3j30ku12ate8.jpg)

### Additional Information

```
react-native-cli: 2.0.1
react-native: 0.42.3
```

**Comment by chetankothari** [comment]
Facing the same issue, how did you end up solving it. Stuck with it for quite some time now.

**Comment by chetankothari** [comment]
Sorry, this is not related to `React Native`. The problem was with a version of `@expo/ex-navigation`. [Link](https://github.com/expo/ex-navigation/issues/473) to the issue.

**Comment by kevineaton** [comment]
I have this issue and I do not use expo nor do I see any expo dependencies. I am using Native Base and a few other libraries. Everything was running fine and then I tried to update a library and now I get this error. I reverted and even did a full git checkout of the repo before the attempted upgrade and now I get this anytime I try to run the application.

**Comment by 77ukhtar** [comment]
@kevineaton same problem with me did u found any solution?

**Comment by virgil9306** [comment]
@77ukhtar Check out https://github.com/react-community/react-navigation/issues/1352 , seems to have a solution from @chenyi5266 

I personally have not seen this on Windows w/building for Android (latest Android Studio & updates) but I have seen this on Mac for iOS (latest updates)

**Comment by 77ukhtar** [comment]
@virgil9306 thanks, i will just not use nativebase on this project till it fixed

**Comment by shadman264** [comment]
having the same problem with android on both Windows & ubuntu 14.04. Is there any working solution?

**Comment by 77ukhtar** [comment]
@kevineaton I solved the error by updating native-base from 2.1.2 to 2.1.4 and react-native from 0.43.4 to 0.44.0

**Comment by JulioOrellana** [comment]
@77ukhtar you are the true hero here! works for me!

**Comment by 1hndrxx** [comment]
Hi @kevineaton @77ukhtar I updated native-base from 2.1.2 to 2.1.4 and react-native from 0.43.4 to 0.44.0. But then I'm getting an error: DeviceInfo native module is not installed correctly...Help please? Thanks

**Comment by shadman264** [comment]
Update React-Native to 0.44.0 in package.json
Then run the following commands:
1) sudo rm -rf node_modules && npm install
2) sudo rm -fr $TMPDIR/react-*

**Comment by 1hndrxx** [comment]
Okay @shadman264. Let me try this real quick. Thanks

**Comment by 1hndrxx** [comment]
Yes! @shadman264 your solution **works**! Thanks!!!

**Comment by suark** [comment]
I'm getting this problem but on react-native 0.42.3. I don't have the option of upgrading react-native because then a bunch of other libraries break due to the react peer dependency upgrade. Hoping for other ideas

**Comment by mtx62** [comment]
Greetings
I follow this upgrading page
https://facebook.github.io/react-native/docs/upgrading.html

and it's working fine

**Comment by anthonied** [comment]
Same as suark, I'm using react-native-maps.  Can't upgrade.

**Comment by m-lg** [comment]
@shadman264 Thanks for the tip, you're a life saver 👍 
worked for me after I specified the version in the package.json for the dependencies I didn't wan't to update (and created this mess in the first place when they got updated :'( )

**Comment by huozhenwei** [comment]
I have had the same problem
If you use a third-party component, change ViewPropTypes.style to View.propTypes.style

**Comment by SorooshPardazCompany** [comment]
best [mobile programming](https://sorooshpardaz.com/mobile-app-android-ios-programming) source around the world
sorooshpardaz.com

**Comment by haifaGh** [comment]
guys i'm having the same problem and i can't upgrade since i have other dependencies .. so what should i do ? thanks 
<img width="399" alt="screen shot 2017-07-02 at 21 12 32" src="https://user-images.githubusercontent.com/15948361/27773150-3740250a-5f6b-11e7-9a7d-a6b9bf2d0048.png">

**Comment by huyunbo** [comment]
我只是拉一个分支，开发新项目，分支是没问题，要怎么解决

**Comment by martianmartian** [comment]
So i had the same problem. it's quite newbie problem in fact.
react-native link doesn't work. 
for ios you have to manually link the xcodeproj thing to your project.(not sure about the android version yet)
here's a good tutorial for getting over this problem.
https://blog.nativebase.io/adding-third-party-native-modules-using-react-native-cbcb9e3786ba

**Comment by cinder92** [comment]
for those that have same issue after install this package try this.

in file `node_modules/react-native-maps/lib/components/MapView.js`

in line 63

replace : `style: ViewPropTypes.style`
for : `style: PropTypes.style`

it fix my issue :)

**Comment by Jason8Zhang** [comment]
I am a newer for RN. This problem has complexed me a few days.

**Comment by harish-aka-shivi** [comment]
I was having the same issue. So I updated the RN and change from
    `import React, { Component, PropTypes } from 'react' `
to 
`import React, { Component } from 'react' `
`import PropTypes from 'prop-types';`

**Comment by samthui** [comment]
I only had to update RN from 0.43.4 to 0.44.0.
Many thanks to @77ukhtar, @shadman264.

**Comment by shubhanshusingh** [comment]
How I solved this:

1. grep -R "View.propTypes" node_modules
above command fetches me list of all packages to update in my case  ex. rn-viewpager,react-native-material-ui etc.

2. Installed and cloned these scripts. https://github.com/reactjs/react-codemod#reactnative-view-proptypes
3. ran command for each module found in step 1  https://github.com/reactjs/react-codemod#reactnative-view-proptypes

**Comment by shubhanshusingh** [comment]
How I solved this:

1. grep -R "View.propTypes" node_modules
above command fetches me list of all packages to update in my case  ex. rn-viewpager,react-native-material-ui etc.

2. Installed and cloned these scripts. https://github.com/reactjs/react-codemod#reactnative-view-proptypes
3. ran command for each module found in step 1  https://github.com/reactjs/react-codemod#reactnative-view-proptypes

**Comment by gitarre94** [comment]
i have the same issue somebody knows how to solve?

**Comment by zibs** [comment]
@gitarre94 depends on your RN version. 

~ >0.45 you must use ViewPropStyles.style - even in third party packages. You'll have to go through and upgrade or fork to remove all references to `View.propTypes.style`
~ <0.45 you can use `View.propTypes.style` but you might not have access to ViewPropStyles.style
