### ISSUE TITLE
App doesn't update on iOS Simulator 

### ISSUE THREAD

**Issue by isaacalves** [facebook/react-native#14039]
From the [Getting Started documentation](https://facebook.github.io/react-native/docs/getting-started.html):

> Now that you have successfully run the app, let's modify it.
> 
> Open index.ios.js in your text editor of choice and edit some lines.
> Hit Command⌘ + R in your iOS Simulator to reload the app and see your change!

I modified some text `index.ios.js` but I can't see any change on the Simulator when I reload. I can see it reloading though, so it's not the "Connect Hardware Keyboard" issue. And even if I close the simulator and run `react-native run-ios` again, I still see the old text.

Am I missing something obvious?

xcode: Version 8.3.2 (8E2002)
simulator: Version 10.0 (SimulatorApp-745.10 CoreSimulator-375.21)
watchman: version 4.7.0
node: v6.10.2

**Comment by isaacalves** [comment]
Solved by running `react-native start` in parallel... maybe that's missing in the Getting Started documentation?

**Comment by ibedek** [comment]
Packager didn't start automatically. Could be related to #14029

**Comment by hramos** [comment]
The packager should be started by `react-native run-ios` automatically, but if you don't see the packager running then you can start it with `react-native start`.
