### ISSUE TITLE
keyboardavoidview padding before time with list view and fixed textinput

### ISSUE THREAD

**Issue by oklivePOP** [facebook/react-native#14044]
### Description
problem with ios **keyboardavoidview**
i have screen that build from 3 component
header - fixed
listView 
TextInput -fixed

the problem is when i use  keyboardavoidview  the padding come before the key board and it look bad (broken)

![ezgif com-crop](https://cloud.githubusercontent.com/assets/28393667/26203306/626fe572-3be3-11e7-8c1c-4e8de1b8e675.gif)

in this gif it happen above the listview (because i'm using invert listVIew)
and in the code sample is happen bottom of the list view

### Reproduction Steps and Sample Code
my demo
https://snack.expo.io/B1z1tGie-

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/keyboardavoidview-padding-before-time-with-list-view-and-fixed-textinput
