### ISSUE TITLE
Config for react-native link

### ISSUE THREAD

**Issue by ericwooley** [facebook/react-native#14046]
I have come across a few native module packages that break my build for android, but work fine on IOS, so far the main culprit has been needing to target different API levels. 

https://github.com/oblador/react-native-keychain for example, requires 23+ but I need to target api 19. So i need to implement two solutions, one for android and one for ios. 

The ios version of react-native-keychain works fine, so I would like to just use that for my .ios.js files, however, linking it breaks my android build. 

It would be great if react-native-cli would read package.json for a linkConfig property, where I could add something like thins

package.json
```JSON
{
//...
    "RNLink": {
        "react-native-keychain": {"ios": true, "android": false}
    }
}
```

and have the react native link command skip the android link for react-native-keychain.

`Apologies if this has been brought up before, or is somehow already implemented. Searches have been done with no solution found.`

**Comment by hramos** [comment]
Thanks for opening the issue, however it looks like a feature request. As noted in the [Issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md) we'd like to use the GitHub issues to track bugs only. Can you implement the feature as a standalone npm module? If not consider sending a pull request or a create an entry on [Canny](https://reactnative.canny.io/feature-requests). It has a voting system and if the feature gets upvoted enough it might get implemented by someone from the community. Closing this now, thanks for understanding!
