### ISSUE TITLE
Inconsistent documentation about Breaking Changes

### ISSUE THREAD

**Issue by Hitabis** [facebook/react-native#14059]
### Description

The [wiki section about breaking changes](https://github.com/facebook/react-native/wiki/Breaking-Changes) is inconsistent with the [release comments](https://github.com/facebook/react-native/releases).

### Example
For version **0.42** there are no documented breaking changes in the [wiki](https://github.com/facebook/react-native/wiki/Breaking-Changes#043) whereas there are some in the [release comments](https://github.com/facebook/react-native/releases/tag/v0.42.3).

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/inconsistent-documentation-about-breaking-changes

**Comment by hramos** [comment]
Always refer to the release notes for breaking changes. Facebook employees update the wiki when they land a breaking change, while the release notes are written based on the wiki plus the contents of commit messages themselves.
