### ISSUE TITLE
EXC_BAD_ACCESS shadowText layout manager crash

### ISSUE THREAD

**Issue by admmasters** [facebook/react-native#1405]
Sometimes a React Native app crashes at line 32 of RCTShadowText. At the line: [shadowText.layoutManager ensureLayoutForTextContainer:shadowText.textContainer]; This is on the queue: com.facebook.React.ShadowQueue - this happened to me while refreshing the app using cmd+R. Not really any specific steps to reproduce. iPhone 6 Simulator - latest Xcode 6.3.2. 6D2105. I believe this has happened a couple of times.

**Comment by ide** [comment]
Yeah this is a real issue. Crash in a different but similar part of the code in #1207.

**Comment by ide** [comment]
Closing this out since https://github.com/facebook/react-native/commit/0689c0790edcc9cb8494e3f15300e2743556f442 hopefully fixes the source of the text crashes. Please open another task if you continue to see crashes when running the latest master branch of React.
