### ISSUE TITLE
ListView scroll event stops Drag/Drop

### ISSUE THREAD

**Issue by alixeb** [facebook/react-native#14057]
### Description

I am using `ListView` with `horizontal={true}`
The listview renders x numbers of `Card` component.
Each card can be dragged up to some drop zones
When the listview has a scroll, I can no longer drag a card up. The card does not move. It seems to freeze.

Drag and drop is done via https://github.com/deanmcpherson/react-native-drag-drop/tree/master/lib which provides some high order components

### Pseudo code

```
<DragContainer
	onDragStart={this.onDragStart}
	onDragEnd={this.onDragEnd}
>
	<View>
		<DropZone
			onDrop={(dragObject) => {
				onDrop(dragObject)
			}}
		>
			<DropItem
				title="Drop Zone 1"
			/>
		</DropZone>
		<DropZone
			onDrop={(dragObject) => {
				onDrop(dragObject)
			}}
		>
			<DropItem
				title="Drop Zone 2"
			/>
		</DropZone>
	</View>
	<ListView
		horizontal={true}
		dataSource={dataSource}
		renderRow={this.renderCard}
	/>
</DragContainer>
```

Then `renderCard` renders `<Draggable>` components like so

```
renderCard(data) {
	return (
		<Draggable data={data}>
			<Card
				firstName={data.firstName}
				lastName={data.lastName}
			/>
		</Draggable>
	)
}
```
### Solution

Help needed.
I tried to set `scrollEnabled={false}` on `ListView` when dragStart is fired and no luck

### Additional Information

* React Native version: 0.42
* Platform: Windows 10. react-native-windows 0.42 , but this also happens on Android
* Development Operating System: started on MacOS but now using Windows 10
* Dev tools: Visual Studio / Atom

**Comment by kevinleeTCA** [comment]
similar issue is reported here with some possible solutions 
https://github.com/facebook/react-native/issues/1046

**Comment by hramos** [comment]
Does this still reproduce using FlatList? ListView is deprecated.

**Comment by alixeb** [comment]
Hello,

Not tested with `FlatList` as not sure if Windows 10 supports it yet.
Also I moved on for the project, so although there is a bug somewhere, it is no longer a priority for me.

If you would like to close the issue feel free.

Cheers
