### ISSUE TITLE
Textinput wrapped in another View causes maximum call stack

### ISSUE THREAD

**Issue by zhuyifan2013** [facebook/react-native#14051]
### Description

TextInput usage  is wired.

### Reproduction Steps and Sample Code

My View hierarchy: 

    A extends Component {
       render(this.props.innerView())
    }

    B extends Component {
       render(
          <A innnerView={this._renderInnerView}/>
       )
    }

And my innerView contains a TextInput . 

In Android , My TextInput is below :

    <TextInput
                    style={{flex: 1}}
                    autoCapitalize='none'
                    placeholder={strings.addLinkTitleHint}
                    keyboardType='default'
                    enablesReturnKeyAutomatically={true}
                    autoCorrect={false}
                    onChangeText={(text) => {
                        console.log("text : ", text);
                        if (this.state.modifyingTitle === text) {
                            return;
                        }
                        this.setState({
                            modifyingTitle: text
                        })
                    }}
                    underlineColorAndroid='rgba(0,0,0,0)'
                    value={this.state.modifyingTitle}
                />

I just could get one time log info, and after seconds, I get "Maximum call stack size exceeded" error. 

I found the render method in A is called many times, but i do not know how to solve it.

### Additional Information

* React Native version: [0.44]
* Platform: [iOS, Android]

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/textinput-wrapped-in-another-view-causes-maximum-call-stack

**Comment by royalcheeseburger** [comment]
@zhuyifan2013 do you still face the issue? If not, how did you solve it?
