### ISSUE TITLE
createJsModules not possible because BatchedBridge is not exposed.

### ISSUE THREAD

**Issue by lingz** [facebook/react-native#14062]
I was trying to create my own JsModule in my own application using createJsModules, and was following all the steps documented in this StackOverflow post: http://stackoverflow.com/questions/38661060/are-there-any-guides-for-implementing-javascriptmodule-in-react-native

I was almost able to create the Js module but I was not able to call `registerCallableModule` on `BatchedBridge` because it's not exposed in react-native. Two solutions seem to be either:

1. Remove the createJsModule API, which is less desirable
2. Expose BatchedBridge or an equivalent API.

Should also add documentation on this.

**Comment by hramos** [comment]
Thanks for opening the issue, however it looks like a feature request. As noted in the [Issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md) we'd like to use the GitHub issues to track bugs only. Can you implement the feature as a standalone npm module? If not consider sending a pull request or a create an entry on [Canny](https://reactnative.canny.io/feature-requests). It has a voting system and if the feature gets upvoted enough it might get implemented by someone from the community. Closing this now, thanks for understanding!
