### ISSUE TITLE
No Android documentation for NativeEventEmitter

### ISSUE THREAD

**Issue by lingz** [facebook/react-native#14061]
There used to be a section of Android docs that mentions using `RCTDeviceEventEmitter` to pass events between Native and JS. However, since `RCTDeviceEventEmitter` was deprecated in favor of subclassing `NativeEventEmitter`, this section of docs, instead of being updated with how to use `NativeEventEmitter`, just got completely deleted in this commit https://github.com/hramos/react-native/commit/b11f8f4936459c104b4fccb3da5eef1d53aa76f7.

Now the docs are strange, there's this mention that events will be described below, but they never are. We need some Android example docs for NativeEventEmitter.

I'd be happy to write this if needed.

**Comment by lingz** [comment]
I tried subclassing NativeEventEmitter but it requires registering a JS Module which also seems not possible right now. I documented this related but distinct issue in https://github.com/facebook/react-native/issues/14062.

However, using NativeAppEventEmitter seems to be the only way to emit events right now. Even though there is a comment that it is deprecated, I think the developer in https://github.com/facebook/react-native/commit/516bf7bd94d14600920a3d78fdcf51ea7fe48495 @nicklockwood meant to deprecate it only internally, and not externally?

In either case, some Android documentation on how to emit events, as callbacks definitely do not satisfy Native-JS communication enough!

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/no-android-documentation-for-nativeeventemitter
