### ISSUE TITLE
[Xcode][0.45.0-rc.0] React Packager starts in a wrong directory

### ISSUE THREAD

**Issue by bosung90** [facebook/react-native#14070]
### Description

1. Close any existing React Packager.
2. Run iOS app using Xcode.
3. Watch React Packager running automatically, then failing with the following
![image](https://cloud.githubusercontent.com/assets/1477531/26264722/b1b7625e-3c92-11e7-8658-a1c8b6003998.png)
![image](https://cloud.githubusercontent.com/assets/1477531/26264730/b94c3076-3c92-11e7-8c57-b720298a53bc.png)

### Workaround

Start React Packager manually using `react-native start` inside your root project directory

### Additional Information

* React Native version: "react-native": "^0.45.0-rc.0"
* React version: "^16.0.0-alpha.12",
* Platform: iOS, Xcode
* Development Operating System: macOS
* Dev tools: Xcode

**Comment by rodriguesbreno** [comment]
Same here when upgraded to RN45-rc.

**Comment by sjmueller** [comment]
Same

**Comment by christianbach** [comment]
Same here :(

**Comment by oallouch** [comment]
Same one android/windows

**Comment by christianbach** [comment]
Any "official" comment on this?

**Comment by nihgwu** [comment]
`npm start -- --reset-cache`

**Comment by oallouch** [comment]
ok... no expert here, but I guess I found it

. 1 window with the packager:
              npm start -- --reset-cache
. and in another window  :
              react-native run-android
The packager opens a server on the port 8081 and is used by the other window.

**Comment by nkov** [comment]
Works if you start the packager manually with `npm start` but doesn't work when launched alongside `react-native run-android` or `react-native run-ios`, it looks for the entry file in this location:

> Looking for JS files in
>        ${PROJECT_DIR}/node_modules/react-native/packager

when it should just be `${PROJECT_DIR}`

**Comment by skevy** [comment]
Hi there!

The packager no longer lives in this repo. It now lives in https://github.com/facebook/metro-bundler. The reasoning for the split is explained here: https://github.com/facebook/react-native/issues/13976.

If you're still interested in pursuing this issue, please open an issue on that repo! :)

Thanks!
-Adam
