### ISSUE TITLE
Network Request Failed

### ISSUE THREAD

**Issue by mocanSergiu666** [facebook/react-native#14078]
I try to fetch some json data from a service through http in react native 0.44.
It throws an error: "network request failed".
It happens when I work with a real Android phone, Windows 10, Visual Studio Code.
On emulator i didn't have such problem.

Here is the code for fetching data:

static async getSports() {
	let result = null;

	await fetch(
		"http://www.picknation.com/scores/scoresService/ActiveLeagues",
		{
			method: "get",
			headers: {
				"Accept": "application/json",
				"Referer": "picknation.com"
			}
		}
	)
		.then(response => {
			if (response.ok) {
				return response.json();
			}
			return null;
		})
		.then(responseValue => {
			result = responseValue;
		})
		.catch(error => console.error(error));
	return result;
}

**Comment by EgaSetya** [comment]
How did you solve this issue?

**Comment by mocanSergiu666** [comment]
Actually I've forgotten, sorry. But I guess the problem was that the phone had not direct net access to the computer when I was working in debug mode through usb. You need to do so that phone and computer can have net access to each other. With phone you connect to wifi and in dev settings you specify the ip address and port of the machine. Port usually is 8081. I hope that one was the solution.
