### ISSUE TITLE
Failed to load the icon from imageset file when integrated to existing App.

### ISSUE THREAD

**Issue by faithfe** [facebook/react-native#1407]
My React native app named (named A) is ok in simulator, but when A is intergrated to existing App (named B), my icon (use require('image!icon') to load) failed to display. I have added the icon to the Images.xcassets of B. In main.jsbundle, the path of [__d("image!icon")] is my own desktop's dictory.  Maybe the icon's path is wrong, but I don't know how to set it.

help, pls!

**Comment by brentvatne** [comment]
Hi @faithfe! Your image should be inside: `Images.xcassets/icon.imageset/icon.png`. Try deleting the imageset on app B and re-adding it like this: https://facebook.github.io/react-native/docs/image.html#adding-static-resources-to-your-app-using-images-xcassets

**Comment by faithfe** [comment]
@brentvatne    I  just use url (http:xxxx/xx/main.jsbundle) to locate  main.jsbundle file in app B, and not anything else.  So  should i cope the whole Images.xcassets directory from app A to app B?

**Comment by brentvatne** [comment]
@faithfe - yeah you will need to add all of those image assets to app B as well
