### ISSUE TITLE
Possibility React Native Mac Remote Assistant App?

### ISSUE THREAD

**Issue by cia48621793** [facebook/react-native#14096]
Just like how Xamarin did it, we could actually relay all the work to a Mac Pro or MacBook, while I'm still handling and using the IDE of my choice on my Windows workstation.

In Xamarin Mac Assistant, all files and commands are remotely executed on the target Mac machine, most of the compilations was done on the Mac side, neat and simple, the only thing annoys me is that the simulator is running in the remote PC, which is a MacBook Pro I have.

So I guess RN can provide a similar functionality like that as well? When I type `react-native run-ios` it just tells me xcrun is not fond.

**Comment by hramos** [comment]
It's an interesting idea. It's not on the [roadmap](https://github.com/facebook/react-native/wiki/Roadmap), but if someone wants to take a stab at it they can send a PR.
