### ISSUE TITLE
HOT Reloading shows the previous change

### ISSUE THREAD

**Issue by tibbus** [facebook/react-native#14099]
### Description

I have this issue where HOT reloading works perfectly, but in the Simulator it shows the previous change instead of the current one.

### Reproduction Steps and Sample Code
Lets say I have a `<Text>12</Text>`
If I change it to `<Text>123</Text>` the Simulator shows on screen : **12**
If I change it to `<Text>1234</Text>` the Simulator shows on screen : **123**
If I change it to `<Text>12345</Text>` the Simulator shows on screen : **1234**
....
.... and so on
Works fine but just with 1 step behind.

### Additional Information

* React Native version: 0.44.0
* Platform: iOS
* Development Operating System: macOS
* Dev tools: Visual Code

**Comment by hramos** [comment]
Any chance you can get the exact list of steps that got your project into this state?

**Comment by hramos** [comment]
Closing this issue as we haven't heard back from the author.
