### ISSUE TITLE
Seeking help with setFrame:

### ISSUE THREAD

**Issue by jonslenkooyala** [facebook/react-native#1411]
hi, I am trying to hook up some native iOS Objective-C UI widgets. Normally I would be using initWithFrame: and then the native widget's drawing code would know about a non-zero area to paint in. How do I do this in React-Native? I tried constantsToExport in my *Manager, but the frame was still zero. Does the JSX have to explicitly pass values (I'm just hoping to use the flow layout)?

In other words, I would dearly like to read a tutorial (with complete sample source code hopefully) that explicitly addresses how frames are managed in the React-Native world. :-)

**Comment by ide** [comment]
Frames are set from JS. Once you bridge your component over, give it `style={{width: 100, height: 100}}` and it should show up.

**Comment by jonslenkooyala** [comment]
Thanks, will do.
