### ISSUE TITLE
client is busy with a request

### ISSUE THREAD

**Issue by RiyasMeeran** [facebook/react-native#14120]
Set data to view using `DeviceEventEmitter.addListener` by binding native mic volume level. 

```
<Text style={styles.instructions}>
          Mic Level {this.state.micLevel}
        </Text>
```

    
```
DeviceEventEmitter.addListener('onMicLevelChange', (data) => {
            this.setState({micLevel:data});
        });
```

but I get error as follows,

![screenshot_20170522-190619](https://cloud.githubusercontent.com/assets/16999176/26338753/3f32e0ee-3fa0-11e7-86ea-0e9ea2cd74a8.jpg)

How to solve this?

**Comment by hey99xx** [comment]
Not sure if this is react-native issue or a third-party library.

It also seems disrespectful to reopen your closed issue https://github.com/facebook/react-native/issues/14098 line by line, even though @hramos had closed it with a reasonable comment.

> It looks like your description is missing some necessary information. Can you please add all the details specified in the template? This is necessary for people to be able to understand and reproduce the issue being reported.

**Comment by ide** [comment]
Looks like this error message comes from code that lives outside React Native: https://github.com/aws/aws-sdk-android/blob/master/aws-android-sdk-lex/src/main/java/com/amazonaws/mobileconnectors/lex/interactionkit/InteractionClient.java#L818

Closing this issue for that reason, if you find that this is a bug with React Native itself then please open another issue.
