### ISSUE TITLE
Can not render item of FlatList when state changed.

### ISSUE THREAD

**Issue by Symous** [facebook/react-native#14125]
Hi, I have a checkbox which is hidden in the right part of the item of FlatList, and when I do a longPress at the Item, the checkbox is supposed to show as it's state has set to true.

```js
<FlatList data={...} renderItem{({item})=>{
      <EveryItem onLongPress={()=>{this.setState({isEditing :true})}}>
           {this.state.isEditing ? <Checbox /> : null}
      </EveryItem>
}}
>
```

but the result is the checkbox never show. Any idea about that ? Thanks.

**Comment by Symous** [comment]
In brief , we can not change the Item style of the FlatList once we render it.such as press it to give it a different background color.

**Comment by Symous** [comment]
OK.I just found out that if we want the FlatList to know the data change outside of the data prop,we need set it to extraData, so I do it like this now:
```
<FlatList data={...} extraData={this.state} .../>
```

refer to : https://facebook.github.io/react-native/docs/flatlist.html - extraData .

**Comment by francisngo** [comment]
I am running into a similar issue with having checkboxes inside FlatList. I am using react-native-elements and added the extraData={this.state} snippet to my FlatList. But now, when I select one checkbox, all of the checkboxes are selected. Did you run into this similar issue? Did you resolve it? If so, how?

**Comment by TamojitPalGit** [comment]
extraData={this.state} fixing my issue. But its reloading entire table, want to reload, perticular cell.

**Comment by Progoogler** [comment]
@TamojitPalGit shouldComponentUpdate() is working as it should for me.

**Comment by Mr3JZ** [comment]
Try setting data:[] in your onRefresh function, when you set isRefreshing: true. That worked for me.

**Comment by ThakurBallary** [comment]
@Symous thanks for mentioning https://facebook.github.io/react-native/docs/flatlist.html#extradata this worked for me.

**Comment by fabiopaiva** [comment]
```
extraData={{ onlyWhatIneedToCheckOutsideData }}
```
worked for me
