### ISSUE TITLE
`Picker` color style prop throws error

### ISSUE THREAD

**Issue by thebigredgeek** [facebook/react-native#14137]
According to the docs:

https://facebook.github.io/react-native/docs/picker.html

Picker accepts a `color` style key.  However, when using `color` in practice, React Native throws an error about `color` not being a valid style prop.  Ironically, on the Appetize demo on the Picker page, this same error is thrown for the example code :(

**Comment by hramos** [comment]
The Appetize sample code is outdated, and has already been removed in master.
