### ISSUE TITLE
error running 2 animations together that do work separately 

### ISSUE THREAD

**Issue by zoharlevin** [facebook/react-native#14130]
### Description

when using Animated with useNativeDriver I succeed in running a **transform animation** on a Text component and I can succeed in running a **color animation** on the same component, as long as the interpolated value is not related to the native driver.
however the **2 animations cannot run together** and I get the error:
`Style property 'color' is not supported by native animated module`

I expected that if the animations work separately then they should run ok together as well.  and the error is unrelated to the issue since i'm using an interpolated value for the color that is not using native driver.

### Reproduction Steps and Sample Code

a snippet from the code that demonstrates this:

```
var testVal = new Animated.Value(0);      
      Animated.timing(testVal, {
        toValue: 1,
        duration: 5000
      }).start();

      const animateColor = testVal.interpolate({
                                    inputRange: [0, 1],
                                    outputRange: ['rgba(255,0,0,1)', 'rgba(0,255,0,1)']                                    
                                });

      const animateTransform = {
        transform: [
            {
                translateY: animationRange.interpolate({
                    inputRange: [0, 1],
                    outputRange: [0, 100],
                }),
            },
            {
                translateX: animationRange.interpolate({
                    inputRange: [0, 1],
                    outputRange: [0, 100],
                }),
            },
            {
                scale: animationRange.interpolate({
                    inputRange: [0, 1],
                    outputRange: [1, 3],
                }),
            },
        ],
    };
                    
// remove "color: animateColor" OR "animateTransform" and the code will work but together there's an error
      return (<View>      
        <Animated.Text style={[{ position:'absolute',                                          
                                  color: animateColor
                              }, animateTransform]} >blah blah blah</Animated.Text>
```

if you run only the `color: animateColor` then it works and if you run only `animateTransform` then it works but together they give that error.

i wrote a small demo app in [this github repo](https://github.com/zoharlevin/DemoAnimatedBug/blob/master/index.android.js) to demonstrate the issue 

### Additional Information

* React Native version: 0.44.0
* Platform: Android (didn't try it on iOS)
* Development Operating System: Win10
* Dev tools: Android Studio

**Comment by brentvatne** [comment]
Thanks for sharing! It's best to post examples on snack.expo.io so that we can easily try them w/o having to clone and build a project. Also it's best for examples to be minimal -- if you can remove any use of recompose that would help.

**Comment by zoharlevin** [comment]
@brentvatne 
thanks, first time opening an issue here..  so i've tried to make it clearer now.

i made 3 expo's - 
1. this one has the `animateColor` working (the transform is commented out): https://snack.expo.io/Hy_GP-OZ-
2. this one has the `animateTransform` working (the color is commented out): https://snack.expo.io/H1Z7DbdW-
3. this one has both `animateColor` and `animateTransform` together and you can see it throws an exception: https://snack.expo.io/HkVNvWuZW

**Comment by brentvatne** [comment]
thanks @zoharlevin!

@janicduplessis - it does indeed look like something strange is going on here both on iOS and Android, different issues though

**Comment by malashkevich** [comment]
Hi! @zoharlevin, did you able to get it work? 
Or may be there are some updates on this issue from developers?

**Comment by zoharlevin** [comment]
Hi @malashkevich , I haven't tried anything further myself :(
I'd love to hear from someone who is more familiar with the internals of Animated about this issue.  I might be mistaken, but to me it feels like this is one example of a wider bug.

**Comment by malashkevich** [comment]
@zoharlevin Yeah, I agree. As for now I just split my view into 2 separate and animate on one color and on other - transformations.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by zachgibson** [comment]
@zoharlevin It’s because you’re applying a natively driven and non-natively driven animation on the same component. From this [React Native Blog Post](https://facebook.github.io/react-native/blog/2017/02/14/using-native-driver-for-animated.html):

> Since Animated produces a graph of animated nodes, it can be serialized and sent to native only once when the animation starts, eliminating the need to callback into the JS thread; the native code can take care of updating the views directly on the UI thread on every frame.

**Comment by zachgibson** [comment]
Also see @janicduplessis comment #14075
