### ISSUE TITLE
Could not install the app on the device, read the error above for details.

### ISSUE THREAD

**Issue by Abdul-majid-ashrafi** [facebook/react-native#14144]
Greetings guys,
I am using a react-native project.
I am facing issue when I run cmd react-native run-android
### Error
Build failed
read the error above for details
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

adb devices
List of devices attached
T062808LX3 device

### Additional Information
* I am using windows 8.1
* I am not new in react-native I have build some project in react-native

**Comment by kholiavko-roman** [comment]
I have the same issue, adb devices show me my device, but when I run project I have error
```
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html
```

**Comment by kholiavko-roman** [comment]
@Abdul-majid-ashrafi are you slove this problem ?

**Comment by Abdul-majid-ashrafi** [comment]
Yeah Thanks @kholiavko-roman 👍

**Comment by kholiavko-roman** [comment]
@Abdul-majid-ashrafi can you help me slove this issue please ? What are you do fo fix that ?

**Comment by Abdul-majid-ashrafi** [comment]
When we install dependency then this crash just remove dependency what you install last time or create new project

**Comment by kholiavko-roman** [comment]
thanks!

**Comment by Abdul-majid-ashrafi** [comment]
**@kholiavko-roman** are you slove this problem ?

**Comment by kholiavko-roman** [comment]
Yes. I reinstall global react-native cli and node_modules in my folder project.

**Comment by Farzad7** [comment]
Same problem, my problem was the fact that I needed internet connection in order to be able to download the packages for my React Native mobile app to be built properly hence it was failing

Hope this saves a bit of your time if you come across similar problem :)

**Comment by andresteves** [comment]
Similar to
https://github.com/facebook/react-native/issues/8868#issuecomment-233458065

**Comment by adityapatnaik25x** [comment]
In the project root directory....
`cd _<Project Name>_` 
`chmod 755 android/gradlew`
Hope this helps....
