### ISSUE TITLE
Add resizeMode repeat on Android.

### ISSUE THREAD

**Issue by SudoPlz** [facebook/react-native#14158]
Hey there..

Do you plan to add resizeMode repeat on Android?
It's been a long time that we've only had this for iOS.

Is this on the roadmap?

Thanks.

**Comment by hramos** [comment]
It's not: https://github.com/facebook/react-native/wiki/Roadmap

Best would be to send a PR. Closing as this is not an issue.

**Comment by dev4xy** [comment]
+1. it necessary!!
