### ISSUE TITLE
Please include at least the right 'import' commands in documentation

### ISSUE THREAD

**Issue by Fonze** [facebook/react-native#14151]
I'm trying to create a Callback in a native Android module but as Android has tons of import-commands for a Callback and I have no idea which one should I pick. So please include the import-commandlines to the documentation of Native Modules.

The Native Modules documentation also could use more React-side code especially in the lifecycle events as the docs give me no reference as how to access data in React that a listener type module can send back at any moment multiple times. The examples above that just seem to ask a question once and the native module just returns an answer once, but in listener case the React-code should be able to listen to any answers at any time. As to how that would be implemented is not documented.

Idiots and newbies like me don't get enough from this documentation ^^'

**Comment by Fonze** [comment]
Got the listener thing working with info from OPEN issue #2819. Please document proper usage of DeviceEventEmitter too.

**Comment by hramos** [comment]
DeviceEventEmitter is documented in the [Native Modules guide in master](http://facebook.github.io/react-native/releases/next/docs/native-modules-android.html#sending-events-to-javascript).

As for native modules docs, the best approach would be to send a PR with the added imports once you get this working.
