### ISSUE TITLE
Touchable elements within FlatList / SectionList not registering

### ISSUE THREAD

**Issue by Mayzie** [facebook/react-native#14155]
### Description

For some reason, Touchable* elements within a FlatList or SectionList view, do not register touches. Rather, it seems that upon rendering a FlatList, a touch event immediately occurs.

### Reproduction Steps and Sample Code

The following, upon render, will produce an alert, "Touched". This should not happen, only on element touch. Furthermore, you cannot touch the TouchableHighlight element and have an alert popup (no highlight colours, nothing).

```
import {
	Alert,
	FlatList,
	TouchableHighlight,
} from 'react-native';

...

<FlatList
	data={[{'name': 'Frodo Baggins', 'address': 'Bag End, Bagshot Row, Hobbiton'}]}
	renderItem={({person}) =>
		<TouchableHighlight
			onPress={() => Alert.alert('Touched') }
			underlayColor='black'
		>
			<View>
				<Text style={{ fontSize: 24 }}>{ person.name }</Text>
				<Text>{ person.address }</Text>
			</View>
		</TouchableHighlight>
	}
	style={{ flex: 1, flexDirection: 'column', padding: 10 }}
/>
```

### Solution

Make elements touchable within FlatList (and SectionList, which exhibits the same behaviour).

### Additional Information

* React Native version: react-native: 0.44.0
* Platform: both
* Development Operating System: Linux & Mac OSX Sierra
* Dev tools: Xcode 8, `react-native run-android`

**Comment by Guacaswole** [comment]
I too am having trouble getting touchable elements to work with FlatList.  In particular, TextInput

**Comment by bbeckk** [comment]
same problem here too. Have you found the soln?

**Comment by bbeckk** [comment]
same problem here too. Have you found the soln?

**Comment by hailie-rei** [comment]
This solution helped me: https://github.com/facebook/react-native/issues/13649
I created a separated pure component for my FlatList item, and now Touchable event works immediately.

**Comment by mahgolfa** [comment]
I recommend u to use ListItem:
1- install react-native components : 
yarn add react-native-elements
# or with npm
npm install --save react-native-elements
2- import it to ur project : 
import { ListItem } from 'react-native-elements'
3- use : 
  <FlatList
      data= {this.state.data}
    renderItem={({item}) =>  <ListItem
       title = {item}  onPress={() => Alert.alert('pressed') }
     />  }
      keyExtractor={(item, index) => index.toString()}
    />

for more information : https://react-native-training.github.io/react-native-elements/docs/listitem.html

**Comment by gurol** [comment]
@pull-bot:  Certainly, the issue has not been fixed in a recent release and perhaps it is affecting a lot of people. 😀
