### ISSUE TITLE
assembleRelease success, but can't find the app-release.apk file on Windows 10

### ISSUE THREAD

**Issue by byn9826** [facebook/react-native#14159]
### Description

I'm trying to generating the signed APK. I got "build Success" by command "gradlew assembleRelease" and the app successfully installed on my android phone by command "react-native run-android --variant=release". However I can't find the APK file at "android/app/build/outputs/apk/app-release.apk". Actually, the "build" folder doesn't even exist in the "android/app" folder. Then I created the "android/app/build/outputs/apk/" folder by hand, and assembleRelease again, still can't find any APK.

I tried to search "app-release.apk" through the project folder, but nothing found.

### Reproduction Steps and Sample Code

```
buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
	   signingConfig signingConfigs.release
    }
}
```

![1](https://cloud.githubusercontent.com/assets/1484618/26414375/05e91348-407d-11e7-8846-c653cd313dfe.JPG)
![2](https://cloud.githubusercontent.com/assets/1484618/26414379/081adffc-407d-11e7-8136-e58c698639a4.JPG)

### Additional Information

* React Native version: 0.44
* Platform: Android
* Development Operating System: windows 10

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.

**Comment by jtl3d** [comment]
@byn9826 did you figure this out? I'm having the same problem.

**Comment by jtl3d** [comment]
@byn9826 Nevermind - one of my developers added the following which trolled me for a good while until I spotted it:

`buildDir = "C:/tmp/${rootProject.name}/${project.name}"`

**Comment by leanhforevo** [comment]
i think you can check in android/app/build.gradle may be lost row -apply from: "../../node_modules/react-native/react.gradle"(default in line 75)

**Comment by sujalBandhara** [comment]
Facing same issue from last 2 days. It would be great if somebody help!!

**Comment by johnlaine1** [comment]
Thanks @byn9826! I forgot that I had put this line in myself due to a "file name exceeds max length" error on my windows machine.

**Comment by mahdit83** [comment]
It's go on this path: ``\app\build\outputs\apk\release
