### ISSUE TITLE
How to change a Item value of a state.

### ISSUE THREAD

**Issue by Symous** [facebook/react-native#14156]
for example, I have a list state like this:
```js
this.state = {
    list:[1,2,3,4,5]
}
```

How can I change the value of the first item of list from 1 to 0? 

I usually use like this but I don't believe that is the best way.
```js
var temp = this.state.list;
temp[0] = 0;
this.setState({ list : temp});
```

Please who can tell me is there any better way to do this ?

**Comment by HofmannZ** [comment]
You could use the [immutability-helper](https://github.com/kolodny/immutability-helper), that would look something like this:

You have the following state, and want to change the first item in the list array.
```js
this.state = {
  list: [1, 2, 3, 4, 5],
};
```

Using the update function, you can do the following:
```js
import update from 'immutability-helper';

this.setState({
  list: update(this.state.list, {
    indexYouEdit: {
      $splice: [[indexYouEdit, amountOfRemoval, newValue, ...optionalNewValues]]
    },
  }),
});
```

Hope that helps you out!

**Comment by Symous** [comment]
@HofmannZ ,Thanks for your help.But when I import update from 'immutability-helper' to my page, there is a error said that - 

Unable to resolve module 'immutability-helper' rom [MY_DIRECTORY];Modules does not exist in the module map or in theres directories ....

do you have any idea about this ? 
PS: React Native 0.43 + Android ;

**Comment by Symous** [comment]
@HofmannZ ,I simply consider that was intergered into react-native already. :-) . And can you tell me is there any other way without importing a third-party lib to achieve this ? Will be grateful  to solve my confusion.Thanks again!
