### ISSUE TITLE
[Android][0.45.0-rc.0] Android keyboard pushes entire view up

### ISSUE THREAD

**Issue by ericapply** [facebook/react-native#14167]
### Description
After upgrading RN from 0.41 to 0.45.0-rc.0, Android soft keyboard will push the entire view up from the bottom. Even after adding `android:windowSoftInputMode="adjustPan"` inside AndroidManifest.xml this behaviour is still there. 
I am not using `KeyboardAvoidingView`

### Additional Information

* "react": "^16.0.0-alpha.12",
    "react-native": "^0.45.0-rc.0",
* Platform: Android
* Development Operating System: [macOS]

**Comment by Maxim-Chuhno** [comment]
it's breaking change in 0.42 https://github.com/facebook/react-native/commit/e3d4ace3ae46e3e4046e1ec5a201b92033deb24a, you sure that in your manifest all fine?
https://developer.android.com/guide/topics/manifest/activity-element.html#wsoft

**Comment by ericapply** [comment]
@Maxim-Chuhno Yes, my bad. I did mean to say the entire view is resized rather than pushed up. I realized that I was putting windowSoftInputMode="adjustPan" inside <application> rather than <activity>. Thank you!
