### ISSUE TITLE
Error when using rotation transform and "useNativeDriver: true" in Android

### ISSUE THREAD

**Issue by raulgg** [facebook/react-native#14161]
### Description

Animation do not work on Android when `useNativeDriver` is `true` and using a rotation transform setting the its angle as a `String` value. But it works as expected when setting it in radians using a `double` value. I usually set the rotation using a String as it is specified in the documentation, but in this case it crashes as it is expecting a double value.

The error I am getting is the following:

![error screenshot](https://cloud.githubusercontent.com/assets/7021021/26415370/1c88d8a6-4067-11e7-949d-000b870e5856.png)

### Reproduction Steps and Sample Code

The following code sample would work either changing `useNativeDriver` to `false` or setting the rotation in radians.

```
  animateOpacity() {
    console.log('animation')
    Animated.timing(
      this.state.opacity_anim,
      {toValue: 1, duration: 600, useNativeDriver: true}
    ).start()
  }
  
  render() {
    return (
      <View style={styles.container}>
        {/* If the rotate transform is set in radians it works, but it doesn't when setting it in degrees with a string value. */}
        <Animated.View style={[
            styles.block,
            {
              transform: [{rotate: '90deg'}],
              opacity: this.state.opacity_anim
            }
        ]}>
          <Text style={styles.message}>Some text</Text>
        </Animated.View>
      </View>
    );
  }
```
I wrote an example in Expo as well:  https://snack.expo.io/SJGbutsl-

### Additional Information

* React Native version: v0.44.0, v0.43.0
* Platform: Android
* Development Operating System: macOS 10.12.5
* Dev tools: Android SDK 25.2.5, Android 7.0

**Comment by brentvatne** [comment]
cc @janicduplessis

**Comment by hrubilov** [comment]
I have the same issue. RN version: v0.45.1

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by syardumi** [comment]
I can confirm this is still a bug in RN 0.48 and narrowed down to the line `...transform: [{rotate: '90deg'}],...` . Using Android 8.0. Please re-open.

**Comment by WemagineGuillaume** [comment]
gfdg

**Comment by WemagineGuillaume** [comment]
Hi,

On iOS, rotate value in string format work properly but on Android, you have to use a double value like that `transform: [{rotate: 4.5}]`.

**Comment by mkpietrzyk** [comment]
Hello, I have the same issue, RN 0.49.2, 

When trying @WemagineGuillaume soulution, it throws an error, that Transform can only accept String with 'deg' or 'rad' values. When using double value with Platform.select for android (f.ex. 4.71), the same error as from OP throws up.

**Comment by henrikra** [comment]
I noticed this bug too and none of the "fixes" in this thread are not working. Using RN 0.48.4

**Comment by rdy** [comment]
animating without {useNativeDriver: true} is the only fix I've noted. It will animate correctly but it doesn't work natively. Non-native animations don't throw this same string double error. I tried using doubles (assuming radians) but react-native complains that it wants the rotation as a string. This is under RN 0.49.5.

**Comment by wli** [comment]
This is still a problem on RN 0.51

**Comment by lvmtam** [comment]
I have the same issue with RN 0.49 :(
It will be nice if have someone PR for it

**Comment by Noitidart** [comment]
Stick it into a `interpolation` but keep it constant. It works fine for me:


```
        const styleFace = {
            opacity: anim.interpolate({ inputRange:[0,.5,.5,1], outputRange:[1,1,0,0] }),
            transform: [
                { rotateY:anim.interpolate({ inputRange:[0,1], outputRange:['0deg', '180deg'] }) }
            ]
        };
```

Here I go from 0deg to 180deg. But you can keep it constant.

**Comment by scisci** [comment]
@janicduplessis I opened a PR for this here: https://github.com/facebook/react-native/pull/18872

**Comment by scisci** [comment]
@janicduplessis @hramos what is the process for getting this merged? Currently forces people to setNativeDriver to false.

**Comment by keeleycarrigan** [comment]
Yea I'm getting this too only when using `useNativeDriver` with `Animated.timing`. Except for me it animating opacity.

**Comment by VitorLuizC** [comment]
@scisci our error seems related to https://github.com/facebook/react-native/issues/19931.

I've replace `TouchableOpacity` to `TouchableHighlight` on my component and fixed it.

**Comment by AhmetGurbuzz** [comment]
I have this problem on RN 0.55.4 on <Animated.View>.

**Comment by AhmetGurbuzz** [comment]
Ouw, I could use it. It's code block like that
state={
  ViewRotation: new Animated.Value(0),
}
componentDidMount() {
    Animated.timing(this.state.ViewRotation, {
        toValue: 1,
        duration: 5000,
        useNativeDriver: true,
        easing: Easing.linear
    }).start();
}
<Animated.View
    style={{
        ...this.props.style,
        transform: [
            {
                rotateY: this.state.ViewRotation.interpolate({
                    inputRange: [0, 1],
                    outputRange: ['0deg', '180deg']
                })
            },
        ]
    }}
>
...
</Animated.View>
