### ISSUE TITLE
[Image & ListView] Image in ListView is not updated when re-rendering

### ISSUE THREAD

**Issue by lazywei** [facebook/react-native#1417]
Say I have such row in ListView

```
return (
        <View style={styles.chatRow}>
          <Image source={{ uri: otherUser.avatarUrl }} style={styles.chatAvatar} />
          <View style={styles.chatRowInfo}>
            <Text style={styles.chatRowName}> {otherUser.name} </Text>
            <Text style={styles.chatRowText}> {Tool.trimToLength(chatContent, 40)} </Text>
            <Text style={styles.chatRowText}> {otherUser.avatarUrl} </Text>
          </View>
        </View>
    );
```

When the state changes, the `Text`'s are re-rendered but the `Image` isn't. The last `Text` shows that the `avatarUrl` is updated correctly. However, the `Image` still shows the old picture.
I'm wondering if this is due to `Image` doesn't compare `{uri: xxx}` deeply?

Thanks

**Comment by JohnyDays** [comment]
It's not a comparison problem, because even the shallow comparison would return false, given you are creating different object instances on every render. So I'm afraid that's not the issue. I think in #1397 @ide mentioned there might be some bug in the Image class that causes Images not to change, might want to check that.

**Comment by adrian-social-prod** [comment]
Have same issue, dataSource updated, row change is triggered and text updated but image does not rerender with new url

**Comment by adrian-social-prod** [comment]
To answer my own problem - Image rerender works by adding a 'key' param with same value as the uri <Image key={url} source={{uri:url}} />

https://github.com/facebook/react-native/issues/1397#issuecomment-105367632

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by qingfeng** [comment]
@adrian-social-prod 'key' param method seems to have been ineffective?

**Comment by JohnyDays** [comment]
@adrian-social-prod It does work, but it recreates the entire image view. This might not be problematic for 1 image, but for a few dozen it starts to become costly.

**Comment by adrian-social-prod** [comment]
is still a problem in 0.8.0. list view image does not change when a new item is added to list unless the 'key' param is used to force the image to rerender. list is inside a TabBar item.  

Seems like a major problem to me.

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/image-listview-image-in-listview-is-not-updated-when-re-rendering

**Comment by KishPatel1996** [comment]
Any chance I can reopen this?

**Comment by npomfret** [comment]
Please re-open - I still have the issue with RN 0.28.  It only seems to be a problem under certain circumstances.  For me it happens when:

An image is added to the end of the list, AND it is adjacent in the list to another image.  Adding `key={uri}` didn't help.

**Comment by merielleimpreso** [comment]
@npomfret: Were you able to fix the issue? I actually run into the same problem as yours. I'm using RN 0.30.

**Comment by ippy04** [comment]
might try `key={source.uri}` instead of `key={uri}`

**Comment by carera** [comment]
Any updates on this? So far only hacking the `key` property seems to be solving the problem. In my case, i render multiple images in a for loop, and under certain condition, i render different images, so it has to look something like this:

```
const PATH_TO_IMG_1 = '/path/to/img/1.png'
const PATH_TO_IMG_2 = '/path/to/img/1.png'

render() {
  let arr = []
  for (let i=1; i < 100; i++) {
    if (cond) {
      arr.push(<Image source={require(PATH_TO_IMG_1)} key={PATH_TO_IMG_1+i}/>)
    } else {
      arr.push(<Image source={require(PATH_TO_IMG_2)} key={PATH_TO_IMG_2+i}/>)      
    }
  }
  return <View>{arr}</View>
}
```

Not sure if requiring image within a loop is efficient though.

**Comment by JohnyDays** [comment]
You can just require the images at the top @carera 
`const IMG_1 = require('/path/to/img/1.png')` but i don't think that's causing your problem ( it may be though )

**Comment by WaterEye0o** [comment]
+1

**Comment by npomfret** [comment]
@merielleimpreso i don't have a 'proper' fix, but hacking the key={uri} worked around it

**Comment by sscaff1** [comment]
I'm having the same issue, but hacking the key={uri} also worked for me.

**Comment by npomfret** [comment]
I don't think this should be closed.  Images in ListViews don't re-render when you change the uri props.  Feels like a proper bug.

**Comment by kelset** [comment]
I had a similar issue: every time I added a new element to the list, it did not populate the new "graphical row" with the correct data (even if in the state are correct) but with a copy of the first row.

Adding the `key={id}` worked for me.

**Comment by joeferraro** [comment]
This is happening to me as well on 0.38. After updating the `ListView`, the new `Image` will load only after scrolling it off then on screen.

**Comment by tianxind** [comment]
Yes seeing the same problem as well. This ticket shouldn't be closed.

**Comment by iamcco** [comment]
same issue

**Comment by hugomosh** [comment]
So it is open?
Does **[FlatList](https://facebook.github.io/react-native/docs/flatlist.html)** take care of this issue?

**Comment by mchandleraz** [comment]
I just ran into this.

I'm rendering an image using a remote URL, provided by my components initial state. Some UI actions can cause the URL that's store in component state to update. If I render the URL using a `Text` component, I see state updating. It does not update the `Image` component. I tried adding a key property of `Math.random()` and that causes the image to disappear entirely when state is updated.

**Comment by jose920405** [comment]
I join the question of @hugomosh

**Comment by eurobob** [comment]
@hugomosh @jose920405 I've also been experiencing this issue with FlatList :/

**Comment by Thetoto** [comment]
I've this issue with FlatList too...

**Comment by brzonsea** [comment]
I'm also experiencing this issue with Flatlist

**Comment by MERTKIRKALI** [comment]
+1

**Comment by EsdrasEtrenne** [comment]
Same, when using the FlatList and adding a `key = {uri}` prop the image will update but then it just show up blank. 

If I change the amount of rows in the FlatList or make a few further changes to the data in the FlatList then the new data will appear. I think this has something to do with the row in the FlatList not completely being redrawn maybe? Maybe iterators are caching image resources until the row is completely redrawn.

**Comment by robisaks** [comment]
Someone on StackOverflow report that if you don't set the size on the image, it will re-render correctly. This fix didn't work for me but I'm posting it here for others just in case.

https://stackoverflow.com/questions/37529211/react-native-image-wont-rerender-when-state-changes

**Comment by alexandretournier** [comment]
Using [react-native-image-cache](https://github.com/kfiroo/react-native-cached-image) instead of Image component solved this issue for me. Maybe related to https://github.com/kfiroo/react-native-cached-image/issues/26

**Comment by asadallahi** [comment]
@alexandretournier  may not be used.
I found the solution.
check [this one](https://github.com/facebook/react-native/issues/13600#issuecomment-385242078)

**Comment by alexandretournier** [comment]
thanks @asadallahi
