### ISSUE TITLE
Android gradle build crashes on launch: Didn't find class "com.facebook.jni.HybridData$Destructor"

### ISSUE THREAD

**Issue by rigdern** [facebook/react-native#14170]
@javache

When building React Native Android using gradle, I get the following runtime exception during launch:

```
05-22 11:07:20.273 28749 28749 E libfb   : error java.lang.ClassNotFoundException: Didn't find
class "com.facebook.jni.HybridData$Destructor" on path: DexPathList[[zip file
"/data/app/com.rnplayground-2/base.apk"],nativeLibraryDirectories=[
/data/app/com.rnplayground-2/lib/arm, /data/app/com.rnplayground-2/base.apk!/lib/armeabi-v7a,
/vendor/lib, /system/lib]]
```

I think the exception is related to [these lines in `Hybrid.cpp`](https://github.com/facebook/react-native/blob/74a70fea97ddddb430346bd4b9b7e83a29616abc/ReactAndroid/src/main/jni/first-party/fb/jni/Hybrid.cpp#L31-L33):

```
  registerNatives("com/facebook/jni/HybridData$Destructor", {
      makeNativeMethod("deleteNative", deleteNative),
  });
```

They were changed on May 19 in commit https://github.com/facebook/react-native/commit/99f8c5df370f5b28347a09fe5e3624a53fdf34ed.

That commit [introduced a BUCK file for fb/jni](https://github.com/facebook/react-native/blob/99f8c5df370f5b28347a09fe5e3624a53fdf34ed/ReactAndroid/src/main/jni/first-party/fb/jni/java/BUCK). Maybe we have to add a corresponding Android.mk file for fb/jni to fix the gradle build?

**Comment by kesha-antonov** [comment]
@javache Same here!
App crashes immediately after open

**Comment by javache** [comment]
Should be fixed by https://github.com/facebook/react-native/commit/f0e4a6cd2c2f74d85d8141054c8c1b5bea78cd46. Can you verify and close this issue?

**Comment by janicduplessis** [comment]
I tested and it works now, thanks @javache
