### ISSUE TITLE
UI Freezes on Redux/Redux-Thunk Fetch?

### ISSUE THREAD

**Issue by stokesbga** [facebook/react-native#14175]
### Description

#9452 This bad boy got closed, but I am still having this issue, and it is absolutely terrible.

I have a paginated listview that fetches results as I scroll. When i press on an item, i want a modal to pop up. However, this only occurs when the fetch is NOT occurring. If I try to press on an item during a fetch, nothing happens. In fact, I cant press any other buttons on the screen until the fetch completes. Scrolling still works, oddly enough.

I am using redux, and redux thunk, and I am doing fetch in my action.

### Reproduction Steps and Sample Code

1. Scroll with paginated list view
2. Press any button. 

Should result in no action. Touchable highlights/opacity dont fire or act disabled.

``` export function fetchNextProductSet(immediateSearchTerm) {
  return async (dispatch, getState) => {
    let {global: {api}, searchFilter, searchResultPage} = getState();

    dispatch({
      type: types.SET_IS_FETCHING,
      isFetching: true
    });

    let searchObj = {favoriteFood: 'pizza'}

    let res = await api.foods(searchObj);
    dispatchArr = [], { foods } = res;
    if(foods && foods.length) {
      dispatchArr.push({
        type: types.ADD_FOODS_TO_LIST,
        items: foods
      });
      dispatchArr.push({
        type: types.SET_HAS_MORE_DATA,
        hasMoreData: foods.length > 0
      });
    } else {
      dispatchArr.push({
        type: types.SET_HAS_MORE_DATA,
        hasMoreData: false
      });
    }

    dispatchArr.push({
      type: types.SET_IS_FETCHING,
      isFetching: false
    });

    dispatch(dispatchArr);
```

* React Native version: 0.42.3
* Platform: iOS
* Development Operating System: macOS
* Dev tools: XCode

**Comment by AlanFoster** [comment]
@stokesbga Do you have a minimum reproducible test case? Is it possible to reproduce without redux?

**Comment by stokesbga** [comment]
@AlanFoster Afraid not. Id imagine the minimum requirements would be to have a paginated listview component fire the fetch action as described. There isn't too much going on in my case, but it seems that everywhere I have fetches, UI locks.

**Comment by AlanFoster** [comment]
@stokesbga Would you mind pasting more of your react component please

**Comment by brentvatne** [comment]
Hello! As you can appreciate there are many issues on this repository and it'll be tough for us to track down the problem without a reproducible example. Additionally, if you can remove any third party dependencies like redux and redux-thunk and help narrow down to specifically what code is causing this, without the abstractions, that would help. If you have time to do this please re-create an issue with the example :)
