### ISSUE TITLE
@providesModule naming collision error

### ISSUE THREAD

**Issue by mykelaballe** [facebook/react-native#14181]
Node: 4.8.3
NPM: 4.5.0
RN CLI:  1.0.0
RN: 0.34.0
Ignite: 1.13.0

the ios react-native project im working on is actually from another machine Mac machine. i transferred it over my windows machine and run it in a virtual machine with El Capitan OS. But now i cant even build it. I dont understand what the errors below are. And im not really familiar with XCode and OSX. The error is saying something about naming collisions. I already tried deleting the collisioned files but another file happens to occur. Then delete that file again and then same thing happens. It goes on and on. Already tried deleting the node_modules folder then running npm install again. tried running npm dedupe and also tried creating a new project using ignite new MyApp but it seems to happen. What did i miss here? We already have an android version of this but now we need to release an iOS version of this but the developer thats supposed to do this has left. Need help ASAP. I can give you the whole running project if it helps. If you need anything let me know. I'll gladly send it to you guys. Thaks in advance

![2](https://cloud.githubusercontent.com/assets/22584900/26436735/341685d8-414b-11e7-9a4b-480dc60aa6b4.JPG)
![3](https://cloud.githubusercontent.com/assets/22584900/26436736/342c0476-414b-11e7-9f7b-d49a873763cf.JPG)

**Comment by brentvatne** [comment]
Hello! Please post this issue to the Ignite repository unless you're able to reproduce it on a project with no external dependencies :)
