### ISSUE TITLE
[Misc] How to set  id<RCTExceptionsManagerDelegate> delegate?

### ISSUE THREAD

**Issue by lzyy** [facebook/react-native#1418]
in `RCTExceptionsManager.h`, there is 

```objc
- (instancetype)initWithDelegate:(id<RCTExceptionsManagerDelegate>)delegate NS_DESIGNATED_INITIALIZER;
```

but `delegate` is not public, so the only way to pass in delegate is use the designated initializer.

but when used like

```javascript
var RCTExceptionsManager = require('NativeModules').ExceptionsManager;
```

it's impossible to set delegate, so when and how to set this delegate so that i can handle exception myself?

### Update, found a way to handle this

1) set an object implement `RCTExceptionsManagerDelegate`

2) find `RCTExceptionsManager` instance via `bridge.modules`

3) set  `exceptionsManager._delegate` via KVC.

### Update Again

maybe there is a more elegant way to do this?

**Comment by brentvatne** [comment]
@lzyy - Thanks for the follow up here! I don't know a lot about this area and I'm very curious to what your objective is in replacing the delegate :smile: could you explain?

@nicklockwood @sahrens - you two seem to appear most in the git history for this, did you have any ideas for how this might be extendable?

**Comment by tadeuzagallo** [comment]
The current approach to use the delegate is to pass it in through `RCTBridgeModuleProviderBlock`, e.g.:

```objc
RCTBridge *bridge = [[RCTBridge alloc] initWithBundleURL:_scriptURL
                                          moduleProvider:^{
                                            return @[[[ExceptionManagerDelegate alloc] init]];
                                          }
                                           launchOptions:nil];
```

Where `ExceptionManagerDelegate` implements the `RCTExceptionsManagerDelegate ` protocol.

**Comment by brentvatne** [comment]
@tadeuzagallo - that seems like a very reasonable approach, @lzyy does that work for you? If not, let me know why and we can discuss options.

**Comment by lzyy** [comment]
@tadeuzagallo @brentvatne Thanks, didn't notice the Provider, problem solved.

**Comment by paramaggarwal** [comment]
Just for info, if you are looking to implement the steps in this issue to see errors in Crashlytics, no need to do anything special.

All JS exceptions will show up in Crashlytics for `Release` builds - search for `RCTExceptionsManager` in Crashlytics. The exception manager throws an exception as expected: [RCTExceptionsManager.m#L86](https://github.com/facebook/react-native/blob/2f6e7336cb96bf14d47554ae0db1836075ea809e/React/Modules/RCTExceptionsManager.m#L86) and Crashlytics catches it and sends to server as a non-fatal.

A JS error will never cause a crash in your app, only a red box error. Any native modules causing an exception will show up in Crashlytics as always.
