### ISSUE TITLE
ScrollView cannot scroll .

### ISSUE THREAD

**Issue by camellieeee** [facebook/react-native#14188]
4 examples code will look like this:
1.  only `<ScrollView> `{some `<View/>`} `</ScrollView>`, It will not scroll.
![1](https://cloud.githubusercontent.com/assets/18331008/26447823/f70435b4-417c-11e7-9dcc-e7a86a0f32c6.jpeg)

![scrollview1](https://cloud.githubusercontent.com/assets/18331008/26447852/1209f092-417d-11e7-8fc7-5f35bae162b5.gif)

2. I wrap it in another View, It will not scroll too.
![2](https://cloud.githubusercontent.com/assets/18331008/26447863/1aa23728-417d-11e7-9126-63ecdb600e82.jpeg)

![scrollview2](https://cloud.githubusercontent.com/assets/18331008/26447874/2b5a0640-417d-11e7-88e8-f0005cd85a40.gif)

3.I wrap it in another View, and setting a height , It will scroll.
   I know why it can scroll by comparing example 4, but I cannot understand 1 and 2.
![3](https://cloud.githubusercontent.com/assets/18331008/26447885/3478e8a4-417d-11e7-9b1a-a684eab442f0.jpeg)

![scrollview3](https://cloud.githubusercontent.com/assets/18331008/26447888/3c6fe2ec-417d-11e7-9133-543850919428.gif)

4.I wrap it in another View, and setting a height , It will not scroll.
![4](https://cloud.githubusercontent.com/assets/18331008/26447894/42b0c324-417d-11e7-8017-a46ee5ac6920.jpeg)

![scrollview4](https://cloud.githubusercontent.com/assets/18331008/26447898/475a712c-417d-11e7-8564-294fc0119bdd.gif)

### Additional Information

* React Native version: 0.43.0
* Platform: ALL
* Development Operating System: macOS

**Comment by AlanFoster** [comment]
@camellieeee Could you paste your example code please :+1:

**Comment by hramos** [comment]
Can you clarify? All of these GIFs show scrolling. Please make sure to fill out the new issue template.

**Comment by brentvatne** [comment]
Also helps to just post an example to https://snack.expo.io/

**Comment by camellieeee** [comment]
@hramos gif1, gif2 and gif4, the ScrollView would bounce back to the top of the screen and fail to scroll to the bottom.

**Comment by brentvatne** [comment]
@camellieeee - please post the examples to https://snack.expo.io/ and I can reopen!

**Comment by hqro** [comment]
same issue
