### ISSUE TITLE
Connection to http://localhost:8081/debugger-proxy timed out. Are you running node proxy? If you are running on the device, check if you have the right IP address in RCTWebSocketExecutor.m.

### ISSUE THREAD

**Issue by RamboLouis** [facebook/react-native#14186]
In the use of iOS devices, real machine remote debugging when there will be this error,but using the emulator does not cause this problem:
"Connection to http://localhost:8081/debugger-proxy timed out. Are you running node proxy? If you are running on the device, check if you have the right IP address in RCTWebSocketExecutor.m."
![wechatimg32](https://cloud.githubusercontent.com/assets/16864923/26444271/5345eb74-416e-11e7-8d19-a396e3bf32bf.jpeg)
This problem still occurs when localhost is replaced with local IP.

**Comment by AlanFoster** [comment]
@RamboLouis Are you running the javascript asset server with `npm run start`
If there's difficulties starting up the server, see if there's something already running on the port - i.e. nginx or such.

**Comment by RamboLouis** [comment]
@AlanFoster The JavaScript resource server is already running , use iOS simulator and Android devices can be remotely debugged, only iOS devices can't be remotely debugged

**Comment by RamboLouis** [comment]
@AlanFoster The javascript asset server is already running , use iOS simulator and Android devices can be remotely debugged, only iOS devices can't be remotely debugged

**Comment by brentvatne** [comment]
Please follow the issue template

**Comment by nazarTrynko** [comment]
@RamboLouis hi, have you been able to resolve this issue for debugging iOS device?

**Comment by RamboLouis** [comment]
Yes, I presume the iOS device and the computer in the same wifi network caused, and then switch to the another wifi signal.

**Comment by RamboLouis** [comment]
@nazarTrynko Yes, I presume the iOS device and the computer in the same wifi network caused, and then switch to the another wifi signal.

**Comment by novellizator** [comment]
same problem, not solved in my case. How should I proceed, please? what are the frequent causes?

**Comment by dgurns** [comment]
I have the same problem here -- it used to work. The only thing that's changed is I updated a parent folder name. Do I have to also update something in the Xcode project?

**Comment by manosim** [comment]
I've got the same issue as well. Exactly the same code, **same iPhone and MacBook** do work fine **at work** but I am getting the above issue when I am **at home**. Note that everything was working fine last night at home.

So I guess there's probably something wrong with my router? Also last night I updated the Command Line Tools (just in case it helps).

![image](https://user-images.githubusercontent.com/6333409/30757676-6c3ea244-9fc7-11e7-8fc5-c962ff3eaad3.png)

**Comment by bohdanbirdie** [comment]
Switching to different wifi network worked for me

**Comment by EsdrasEtrenne** [comment]
if you are getting this error you may not be connected to the internet on your device/simulator

**Comment by alexmbarton** [comment]
If using a device (rather than the emulator) make sure that both the computer and device are on the same network.

**Comment by anwarhamr** [comment]
For me this is always happening when I am working from a wifi that I've not connected to in the past.  Make sure your device is connected to the same wifi as your laptop...  I get myself with this nearly every time I work remote not at home!
