### ISSUE TITLE
Doesn't work with Android Instant Apps on O

### ISSUE THREAD

**Issue by anirudhd** [facebook/react-native#14197]
### Description

1. Build react hello sample as an Android Instant App
2. Ran on Android O

### Reproduction Steps and Sample Code

Run react hello work as an Instant App. App fails because Android Instant Apps can't have SYSTEM_ALERT_WINDOW permissions to draw over other apps.

  ***An example of your code is REQUIRED***

### Solution

What needs to be done to address this issue? Ideally, provide a pull request with a fix.
Remove dependency on  SYSTEM_ALERT_WINDOW (draw over other apps) for development.

### Additional Information

* React Native version: [FILL THIS OUT: Be specific, filling out "latest" here is not enough.]
react-native-cli: 2.0.1
react-native: 0.44.0

* Platform: [FILL THIS OUT: iOS, Android, or both?]
Android 

* Development Operating System: [FILL THIS OUT: Are you developing on macOS, Linux, or Windows?]
Mac

* Dev tools: [FILL THIS OUT: Xcode or Android Studio version, iOS or Android SDK version, if applicable]
 Android Studio 3.0 preview

**Comment by brentvatne** [comment]
Can't you just do a release build to use it an instant app rather than debug build?
