### ISSUE TITLE
[JS] Expose global as `self` too

### ISSUE THREAD

**Issue by johanneslumpe** [facebook/react-native#1419]
In JavascriptCore `self` is not defined. Libraries like `bluebird` for example rely on `self` being the global object instead of `window`, as it works in web workers too.

This fails in `react-native` due to `self` not being defined. A simple `global.self = global` at the beginning of the script solves this issue. Could we get this into the default packaged code so that we don't have to put the statement in there by ourselves?

Edit: As discussed in https://github.com/petkaantonov/bluebird/issues/630

**Comment by jtremback** [comment]
Sounds pretty drastic to be defining new top-level variables to support some library!

**Comment by johanneslumpe** [comment]
Except for the fact that it's available in every browser and web workers - it's more of a generic fix for the runtime which is missing a prop on the window object than just "supporting some library". Read about it here: https://developer.mozilla.org/en-US/docs/Web/API/Window/self

**Comment by brentvatne** [comment]
@johanneslumpe - good point, what do you think @vjeux?

**Comment by vjeux** [comment]
Finding the global object is annoying as there is no standard way of doing it. Here are 4 ways and how they behave:

```
>> node
> self
ReferenceError: self is not defined
> window
ReferenceError: window is not defined
> this
{...}
> global
{...}
```

```
// browser
> self
{...}
> window
{...}
> this
{...}
> global
Uncaught ReferenceError: global is not defined
```

`this` has the best coverage.

As to introduce `self` in react-native, I'm unsure. I'd really like to avoid adding 10 different ways to do the same thing. I'd love to find a way to get one solution that works everywhere and implement this one

**Comment by ide** [comment]
Seems like this is the kind of thing that could be neatly maintained by a standalone project for the most part. Ex: `npm install react-native-browser-polyfill` + `import 'react-native-browser-polyfill` and have docs that explain this. Then if it turns out that basically everyone ends up doing this, it'd be pretty easy to include it with the default react environment.

**Comment by brentvatne** [comment]
@johanneslumpe - want to make that module? :smile:

**Comment by johanneslumpe** [comment]
@brentvatne @ide @vjeux Yeah I think I can cook up that module. Will probably use the name @ide suggested. And it will only contain a single polyfill for now, but maybe we can add more in the future.

**Comment by ide** [comment]
Sounds like a plan.

**Comment by johanneslumpe** [comment]
Published as `react-native-browser-polyfill`!

**Comment by ide** [comment]
yay https://github.com/johanneslumpe/react-native-browser-polyfill
