### ISSUE TITLE
Include CoreTelephony

### ISSUE THREAD

**Issue by pbaran** [facebook/react-native#1420]
I would like to know whether you are planning some API to view call log. For now I can see some plugins/modules which allow to read files so that I can read a proper file but as far as it seems to be so large it is a performance hit.

**Comment by jtremback** [comment]
Getting into React Native right now, you should be expecting to write some native code, unfortunately. Write an adapter and share it with us!

**Comment by brentvatne** [comment]
@jtremback is right, this will need to come in the form of an external library. .If you're up for writing one, check out [the Native Module docs](https://facebook.github.io/react-native/docs/nativemodulesios.html#content) and let me know if you need a hand - you can ping me in irc @notbrent or here!
