### ISSUE TITLE
Cannot read property 'style' of undefined (NativeBase) react native

### ISSUE THREAD

**Issue by juanverlop** [facebook/react-native#14214]
I have this problem, since I run "npm update" in my project.
"Can not read property 'style' of undefined"
"Module AppRegistry is not a registered callable module (calling runApplication)"

Apparently occurs because "_reactNative.ViewPropTypes.style" is coming undefined

This is my dependency on the package.json

"dependencies": {
    "native-base": "^2.0.13",
    "react": "15.4.2",
    "react-native": "0.42.2",
    "react-native-drawer": "^2.3.0",
    "react-native-image-picker": "^0.26.3",
    "react-native-maps": "^0.13.1",
    "react-native-modalbox": "^1.3.9",
    "react-native-onesignal": "^3.0.3",
    "react-native-redux-router": "^1.0.7",
    "react-native-swipeable": "^0.4.0",
    "react-native-tab-navigator": "^0.3.3",
    "react-native-vector-icons": "^4.0.0",
    "react-redux": "^5.0.3",
    "redux": "^3.6.0",
    "redux-thunk": "^2.2.0"
  }

**Comment by brentvatne** [comment]
Hello! Issues with third party libraries belong on those repositories. In this case it sounds like the issue was with "NativeBase" - please re-create the issue on that repository.
