### ISSUE TITLE
[Animated] Re-render problem with `useNativeDriver`

### ISSUE THREAD

**Issue by mosesoak** [facebook/react-native#14219]
I ran into a react lifecycle glitch with `useNativeDriver` where a component that's set up with Animated styles will get reset to its initial position on parent re-render.

Repro: https://snack.expo.io/r1sRoKLW-

It repros for iOS but not for Android, which is strange since I tracked it down to purely React Native mechanics.

This took a really long time to debug. After digging into the native iOS side and verifying that the UIView was not being set incorrectly, I carefully inspected the props of the component in `ReactNativeAttributePayload`'s diffing methods and `ReactNativeCompositeComponent`'s mount and update methods. 

Finally figured it out! The problem is that the component doesn't know it's going to `useNativeDriver` until the tween starts, so it mounts with its animated props in place. The `useNativeDriver` animations work fine prior as long as the parent component doesn't re-render, which is expected. But on re-render, the style props [get removed from component props by Animated](https://github.com/facebook/react-native/blob/master/Libraries/Animated/src/AnimatedImplementation.js#L1519).

This causes the view to be redrawn due to the diffing engine correctly noticing the missing styles.

<img width="240" alt="screen shot 2017-05-26 at 10 54 02 pm" src="https://cloud.githubusercontent.com/assets/24345/26518484/47766ad2-4266-11e7-825e-a82838b8bec6.png"> <img width="239" alt="screen shot 2017-05-26 at 10 53 42 pm" src="https://cloud.githubusercontent.com/assets/24345/26518483/441aa09c-4266-11e7-85f1-3ec15d7227cd.png">

ping: @janicduplessis @kmagiera

**Comment by mosesoak** [comment]
One solution might be to make it possible to set up an Animated.Value as native on instantiate. This could potentially also remove the requirement to set `useNativeDriver` in every tween as well.

Perhaps a config object is most appropriate since eventually `useNativeDriver` will be deprecated once it's finished, and other config options might come up later.

e.g.:

```javascript
boxAnimVal = new Animated.Value(0, { useNativeDriver: true });

// This will automatically use the native driver based on the value being animated
Animated.timing(this.boxAnimVal, {
  toValue: 1,
  duration: 500,
  easing: Easing.out(Easing.exp),
}).start();
```

I'd be happy to take a stab at writing that next week if you guys like the direction.

**Comment by nihgwu** [comment]
ping @janicduplessis 
I don't think move `useNativeDriver` to Animated.Value is a good idea, as I can also apply it to a prop that can't be driven by native

**Comment by mosesoak** [comment]
@nihgwu fair point - although from my experience if any non-native props are associated with a value that's been set to native they'll throw a runtime error, so presetting a value to native would simply limit its scope.

Can you think of another way to indicate native to the render tree in advance of tweens?

**Comment by janicduplessis** [comment]
@mosesoak Thanks for investigating this, I remember @ryangomba had a similar issue some time ago and wanted to implement the same solution. I think I understand the issue and the fix makes sense.

I don't think moving useNativeDriver to Animated.Value will cause issues since mixing native and non-native animations with the same Animated.Value will cause runtime crashes anyway since they are not compatible.

Here's an old PR that did pretty much what you want to do I think https://github.com/facebook/react-native/pull/10657. If we go for this we should also add deprecation warnings for useNativeDriver on animation functions and events.

**Comment by smallpath** [comment]
facing the same issue on Android but very randomly that I can't even reproduce it🤔
