### ISSUE TITLE
Crash within dispatchBlock:(dispatch_block_t)block forModule:(NSNumber *)moduleID in  RCTBridge.m

### ISSUE THREAD

**Issue by admmasters** [facebook/react-native#1421]
Crashing while generating a payload on line 1330. Interestingly all the variables are pointing to 0x0 or nil.
![screen shot 2015-05-27 at 13 00 48](https://cloud.githubusercontent.com/assets/335607/7835413/ad1a420e-0470-11e5-9bb9-8cf7c6ca8ea2.png)

**Comment by ide** [comment]
Looks like another text layout crash (look at the stack in be bottom right corner).

**Comment by ide** [comment]
Closing this out since https://github.com/facebook/react-native/commit/0689c0790edcc9cb8494e3f15300e2743556f442 hopefully fixes the source of the text crashes.
