### ISSUE TITLE
[Integration w/ Existing App] How to pass the native navigation controller into a react-native root view component?

### ISSUE THREAD

**Issue by iostalk** [facebook/react-native#1422]
I have a navigation controller already, I want to pass the navigation controller into the react-native root view, how to implement this?

**Comment by iostalk** [comment]
help! help!

**Comment by brentvatne** [comment]
Hi @iostalk! Can you explain the use case and provide some sample code for how you would like to use this from the React Native side?

**Comment by iostalk** [comment]
In MainController.m, I set a ReactRootView instance as a root view, and I have a navigation Controller already in objective-c side:

In MainController.m(extended from a navigation controller):
```objective-c
RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                    moduleName: @"SimpleApp"
                                                 launchOptions:nil];
self.view = rootView;
```

In jsx:
```jsx

render: function() {
  return (
    <NavigatorIOS
      initialRoute={{
        component: MyView,
        title: 'My View Title',
        passProps: { myProp: 'foo' },
      }}
    />
  );
},
...
this.props.navigator.push(nextRoute); 
```
My question is, can I get the navigator in the js side?

**Comment by brentvatne** [comment]
@iostalk - I haven't tried that myself, this is probably a better question for StackOverflow now that I see it, could you repost it there? If you don't get an answer, ping me here and I can reopen and see if someone on the team can help you. :smile:

**Comment by axelg12** [comment]
@iostalk Did you find out how to get the navigator in the js side ?

**Comment by edo1493** [comment]
I am wondering the same?

**Comment by jabez128** [comment]
I meet the similar problem and my solution is in this issue: https://github.com/facebook/react-native/issues/3324

wish could help you :)
