### ISSUE TITLE
No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.

### ISSUE THREAD

**Issue by imarem** [facebook/react-native#14227]
Since yesterday when I try to build the application, get the error below. I'm using compileSdkVersion 23, and buildToolsVersion "23.0.1", but the react-native-fbsdk library is compiled on 25.3.1.
Any idea how to fix the error? Or how to force compile with sdk version 23?

**Build details:**
:react-native-fbsdk:prepareComAndroidSupportAnimatedVectorDrawable2531Library
:react-native-fbsdk:prepareComAndroidSupportA**ppcompatV72531Library**
:react-native-fbsdk:prepareComAndroidSupportCardviewV72531Library
:react-native-fbsdk:prepareComAndroidSupportCustomtabs2531Library
:react-native-fbsdk:prepareComAndroidSupportRecyclerviewV72301Library
:react-native-fbsdk:prepareComAndroidSupportSupportCompat2531Library
:react-native-fbsdk:prepareComAndroidSupportSupportCoreUi2531Library
:react-native-fbsdk:prepareComAndroidSupportSupportCoreUtils2531Library
:react-native-fbsdk:prepareComAndroidSupportSupportFragment2531Library
:react-native-fbsdk:prepareComAndroidSupportSupportMediaCompat2531Library
:react-native-fbsdk:prepareComAndroidSupportSupportV42531Library
:react-native-fbsdk:prepareComAndroidSupportSupportVectorDrawable2531Library
:react-native-fbsdk:prepareComFacebookAndroidFacebookAndroidSdk4230Library
:react-native-fbsdk:prepareComFacebookFrescoDrawee0110Library
:react-native-fbsdk:prepareComFacebookFrescoFbcore0110Library
:react-native-fbsdk:prepareComFacebookFrescoFresco0110Library
:react-native-fbsdk:prepareComFacebookFrescoImagepipeline0110Library
:react-native-fbsdk:prepareComFacebookFrescoImagepipelineBase0110Library
:react-native-fbsdk:prepareComFacebookFrescoImagepipelineOkhttp30110Library
:react-native-fbsdk:prepareComFacebookReactReactNative0390Library
:react-native-fbsdk:prepareComFacebookSoloaderSoloader010Library
:react-native-fbsdk:prepareOrgWebkitAndroidJscR174650Library
:react-native-fbsdk:prepareReleaseDependencies
:react-native-fbsdk:compileReleaseAidl
:react-native-fbsdk:compileReleaseRenderscript
:react-native-fbsdk:generateReleaseBuildConfig
:react-native-fbsdk:generateReleaseAssets UP-TO-DATE
:react-native-fbsdk:mergeReleaseAssets
:react-native-fbsdk:generateReleaseResValues UP-TO-DATE
:react-native-fbsdk:generateReleaseResources
:react-native-fbsdk:mergeReleaseResources
:react-native-fbsdk:processReleaseManifest
:react-native-fbsdk:processReleaseResources
C:\git\iChallenge\node_modules\react-native-fbsdk\android\build\intermediates\exploded-aar\com.android.support\appcompat-v7\25.3.1\res\values-v24\values-v24.xml:2 : Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
C:\git\iChallenge\node_modules\react-native-fbsdk\android\build\intermediates\exploded-aar\com.android.support\appcompat-v7\25.3.1\res\values-v24\values-v24.xml:2 : Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.

:react-native-fbsdk:processReleaseResources FAILED

FAILURE: Build failed with an exception.

**build.gradle**

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    defaultConfig {
        applicationId "com.bcnapps.ichallenge"
        minSdkVersion 19
        targetSdkVersion 22
        versionCode 5
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
        renderscriptTargetApi 23
        renderscriptSupportModeEnabled true
    }
...

* React Native version: 0.39.0
* Platform: Android
* Development Operating System: Windows

**Comment by brentvatne** [comment]
hello! please create this issue on the [react-native-fbsdk](https://github.com/facebook/react-native-fbsdk) repo :)

**Comment by Rewieer** [comment]
@brentvatne it seems not to be possible to create an issue on the fbsdk repo

**Comment by imarem** [comment]
Hi @Rewieer,

Never mind, I found a workaround in this thread:
[https://stackoverflow.com/questions/44190829/facebook-sdk-android-error-building](url)

You can set the version of the compilation by modifying, the build.gradle file in 
...\node_modules\react-native-fbsdk\android\build.gradle or setting a global configuration project in your build.gradle.

I hope this helps you.

**Comment by Rewieer** [comment]
@imarem thanks, I just found it out and it's a very great hack. However it seems a PR is waiting and is going to be shipped soon to solve this problem :)

**Comment by brentvatne** [comment]
it looks like that repo has their own process for reporting issues: https://github.com/facebook/react-native-fbsdk#give-feedback

**Comment by khunghang16** [comment]
hello. @imarem  . how about fix it? me too .

**Comment by imarem** [comment]
Hi @khunghang16 ,

follow the steps from [http://stackoverflow.com/questions/44190829/facebook-sdk-android-error-building](url)

;)

**Comment by conorstrejcek** [comment]
@imarem The page you linked to no longer exists -- do you still remember the steps you had to take to resolve this issue?

**Comment by imarem** [comment]
@conorstrejcek the link is restored now ;)

I hope this helps you.

**Comment by conorstrejcek** [comment]
@imarem Thanks! I didn't even look to see that it was a stackoverflow link, I could have just copy/pasted it...
