### ISSUE TITLE
react-native-ugrade error

### ISSUE THREAD

**Issue by mykelaballe** [facebook/react-native#14228]
Node: 4.8.3
NPM: 4.5.0
RN CLI: 1.0.0
RN: 0.34.0
Ignite: 1.13.0
Platform: Virtualbox running OSX 10.11 El Capitan

Moved react-native project to a new machine, deleted the ios folder, run react-native upgrade command. Produced this error: 

![image](https://cloud.githubusercontent.com/assets/22584900/26521608/183a4428-431f-11e7-9586-81b7018fd7ae.png)

This project successfully builds in android
Any idea?

**Comment by mykelaballe** [comment]
any idea how to fix this?

![image](https://cloud.githubusercontent.com/assets/22584900/26522821/b820bfbe-433b-11e7-986b-62e01dbe0963.png)

**Comment by johnryan** [comment]
@mykelaballe looks like you need to change your security settings in System Preferences

**Comment by mykelaballe** [comment]
thanks got it
