### ISSUE TITLE
A new react-native release on jcenter with version 0.42.3-atlassian-1 is seems to be breaking RN builds with version less than 0.42.3

### ISSUE THREAD

**Issue by gShrey** [facebook/react-native#14225]
Creating new issue from #14223 for better visibility. 

For android projects, react native is added as dependency in gradle by using "com.facebook.react:react-native:+" and are linked to android source in react-native package. 
But few hours ago, a new release with version 0.42.3-atlassian-1 was added on bintray was added. This is seems to be breaking on React native android build before version 0.44 . 
I have checked on 0.41, 0.39.1 and 0.42.1. All projects are failing with same error:

**Could not find com.atlassian.mobile.video:okhttp-ws-compat:3.7.0-atlassian1.**

Any resolution with jcenter on this will be helpful.

**Comment by kishanj918** [comment]
I can confirm it happening also on 0.40.0.

**Comment by hjumeau** [comment]
I'm using the 0.38 version of react-native and I have the same issue.

**Comment by bestotem** [comment]
I have the same issue today, my version is 0.42

**Comment by Knorcedger** [comment]
Same issue here

**Comment by david50407** [comment]
Try the temporary fix here https://github.com/facebook/react-native/issues/14223#issuecomment-304447493

**Comment by kishanj918** [comment]
@david50407 thanks david that worked.

**Comment by timscott** [comment]
Same issue on 0.41.0.

**Comment by muneebsajjad** [comment]
same issue on 0.41.2

**Comment by GuoMeng6** [comment]
In your build.gradle (not android/app/build.gradle) add this lines to force all dependency to react-native to specific version:
```
allprojects {
  configurations.all {
    resolutionStrategy {
        eachDependency { DependencyResolveDetails details ->
            if (details.requested.group == 'com.facebook.react' && details.requested.name == 'react-native') {
                details.useVersion "0.42.0" // Your real React Native version here
            }
        }
    }
  }
}
```

 I hope this help.

**Comment by freckletonj** [comment]
same issue despite @david50407 's fix, tried on a smattering of RN versions 0.22 -> 0.44

**Comment by rszalski** [comment]
Upgrading to react-native from `0.42.0` to `0.42.3` fixed this error for me.

**Comment by xwartz** [comment]
Any update on this? @brentvatne

**Comment by weiliank** [comment]
same issue on RN 0.39.2

**Comment by EslamNasser** [comment]
Same issue on RN 0.40.0

**Comment by metelski** [comment]
Agree with @rszalski - try upgrading `react-native` from `0.42.0` to `0.42.3`. This worked for me as well.

**Comment by SathishSundharam** [comment]
Hi all.
   please find the solution here.  
 [https://github.com/facebook/react-native/issues/14223]

**Comment by pentateu** [comment]
Hi @SathishSundharam,
This is a workaround, not a definitive solution. 

The solution is for them to fix the repository.

**Comment by arunkumarrmrj** [comment]
"com.atlassian.mobile.video" is not avaible on maven right now. To run your project you need to update it 

Update your react and react-native version to in your package.json file 

    "react": "16.0.0-alpha.3",
    "react-native": "0.43.1",

Then remove `node_modules` and do a `npm install` again

Let me know if it works for you

**Comment by TheMarsGuy** [comment]
Not everybody is in a situation to upgrade their projects. So, upgrading cannot be the solution.

**Comment by inakianduaga** [comment]
> "com.atlassian.mobile.video" is not avaible on maven right now. To run your project you need to update it
> Update your react and react-native version to in your package.json file
> "react": "16.0.0-alpha.3",
> "react-native": "0.43.1",
> Then remove node_modules and do a npm install again

I actually have 

>     "react": "16.0.0-alpha.6",
>    "react-native": "0.43.3",

and I'm still getting the same error (wiped `npm_modules` as well). Is the fix specific to `0.43.1`?

**Comment by LisitaEugen** [comment]
Same issue here with  ```"react": "15.3.2","react-native": "^0.36.0"``` Any idea to workaround this?

**Comment by muneebsajjad** [comment]
I upgraded to version "react-native": "^0.44.0"  which solve this problem
but I will not recommend this as it will break your navigator and app will
crash. There is workaround for that too that come at cost of extra code
work.

**Comment by rezaarifian** [comment]
I cannot release or build project react native. 
Same issue here with "react-native": "0.32.0" "react-native-cli: 2.0.1" "react": "15.3.1",

**Comment by jamescoq** [comment]
The workaround mentioned in https://github.com/facebook/react-native/issues/14223#issuecomment-304447493 seems to work only for app created via react-native scripts. When integrating react-native app into existing android app there is a subsequent error:
`A problem occurred configuring project ':mobile'.
> Could not resolve all dependencies for configuration ':mobile:_dev1DebugApk'.
   > A problem occurred configuring project ':react-native-vector-icons'.
      > Could not resolve all dependencies for configuration ':react-native-vector-icons:_debugPublishCopy'.
         > Could not find com.facebook.react:react-native:0.38.0.
           Required by:
               project :react-native-vector-icons
`

**Comment by ChrisPikul510** [comment]
Desperately need a fix for this. Upgrading RN isn't an option (time constraints) so as of RN: 0.35 I can't get it to work. The build.gradle fix suggested did nothing for me. I'm speciffically getting it from `react-native-image-picker` package. But the atlasion package is the same as being reported here.

Missing Dependency:
`com.atlassian.mobile.video:okhttp-ws-compat:3.7.0-atlassian1`

Referenced Package:
`react-native-image-picker`

RN: 0.35.0

**Comment by bilalsyed001** [comment]
@ChrisPikul510 dirty fix: goto node_modules/react-native-image-picker and change this line to compile "com.facebook.react:react-native:0.20.1" -> https://github.com/react-community/react-native-image-picker/blob/develop/android/build.gradle#L48

**Comment by ChrisPikul510** [comment]
@bilalsyed001 Wow, that worked. But it is dirty. It just brought me to another dependency. This time `react-native-photo-view` not sure how far I want to chase the rabbit down this hole. I'm gonna see how painful the jump from RN 0.35 to 0.42 is... Will report back.

**Comment by rezaarifian** [comment]
it's work for me.
> // Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }

        configurations.all {
            resolutionStrategy {
                eachDependency { DependencyResolveDetails details ->
                    if (details.requested.group == 'com.facebook.react' && details.requested.name == 'react-native') {
                        details.useVersion "0.42.0" // Your real React Native version here
                    }
                }
            }
        }
    }
}

**Comment by kibot914** [comment]
Very Desperate, I think I have to work overnight, come on

**Comment by rezaarifian** [comment]
it's work for me with "react-native": "0.32.0" "react-native-cli: 2.0.1" "react": "15.3.1",
edit on android/build.gradle

allprojects {

    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }

        configurations.all {
            resolutionStrategy {
                eachDependency { DependencyResolveDetails details ->
                    if (details.requested.group == 'com.facebook.react' && details.requested.name == 'react-native') {
                        details.useVersion "0.32.0" // Your real React Native version here
                    }
                }
            }
        }
    }
}

**Comment by khannasaransh** [comment]
I am having same issue as mentioned by @jamescoq 

Error:Failed to resolve: com.facebook.react:react-native:0.42.3

**Comment by tiofabby** [comment]
Same here, setting up version to my local one: details.useVersion "0.41.2" fixed the issue.

**Comment by monumentyusuf** [comment]
same with @khannasaransh ;
Error:Failed to resolve: com.facebook.react:react-native:0.42.3

**Comment by kibot914** [comment]
https://bintray.com/bintray/jcenter/com.facebook.react%3Areact-native#

**Comment by tszajna0** [comment]
I managed to fix the issue with build.gradle:

    allprojects {
        repositories {
            mavenLocal()
            mavenCentral()
            jcenter()
            maven {
                // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
                url "$projectDir/../../node_modules/react-native/android"
            }
            maven {
              // Because some dependencies are differently nested
              url "$projectDir/../../../node_modules/react-native/android"
            }
            maven {
              // Because some other dependencies are nested in yet another way
              url "$projectDir/../../../../node_modules/react-native/android"
            }
        }
    }

Nasty, but worked for me; you may need to try with more or less `../`

**Comment by kibot914** [comment]
Remember : **$rootDir**/../node_modules/react-native/android

$rootDir instead of $projectDir

**Comment by tszajna0** [comment]
@kibot914 right; that's an explanation why the solution above didn't work for me. Thanks a lot!

**Comment by maoueh** [comment]
One of the problem with `configurations.all` workaround mentioned above is that it does not apply to subprojects. It's a problem for react-native dependencies which are pulled as project dependency as and as such, have a distinct `configurations` from the main `app` project. To solve it, put in `android/build.gradle` file (**Note** that it's the main build file, putting in **android/app/build.gradle** won't work!) at the very bottom:

```
subprojects {
  project.apply {
    configurations.all {
      resolutionStrategy.force 'com.facebook.react:react-native:0.42.0' // <-- Put your own version
    }
  }
}
```

This ensures that all projects in the build are forced to use version `0.42.0` (change by your own here) and not the one defined in the dependency project itself (like `react-native-vector-icons` for example) which is usually specified as `compile "com.facebook.react:react-native:+"` which always picks the latest.

**Comment by devmaster72** [comment]
If you are on RN 0.41.2 then applying the temporary fix that @david50407  suggests above solves the issue right away. No other change required.

**Comment by simaoneves** [comment]
Using RN 0.36.1 and @david50407 temporary fix above solves the issue.

**Comment by shrutic** [comment]
The temporary fix by @david50407  does not work for me as I am using a custom fork of 0.43.3 react-native. I get "Failed to resolve: com.facebook.react:react-native:0.43.3"

**Comment by nowtech** [comment]
Upgrading from react-native 0.42.0 to 0.42.3 worked for me

**Comment by gShrey** [comment]
After contacting bintray and asking them to remove invalid release. They have deleted 0.42.3-atlassian-1 release from jcenter repo.  App should build without any need of workaround now.

**Comment by godspeedelbow** [comment]
Great! Would there be anything *we* could do to prevent this from happening
in the future?

**Comment by piyush565** [comment]
i cant start development server even after build successful in windows. i updated react-native version to 0.42.3, message comes 'loading dependency graph, done' in packager. #help

**Comment by matthiasprieth** [comment]
I also had no possibility to change to RN >= 0.44.0 i got it working by switching to version in `package.json`
```
    "react": "~15.4.1",
    "react-native": "0.42.0",
```
and putting this in my `build.gradle`
```
    configurations.all {
        resolutionStrategy {
            eachDependency { DependencyResolveDetails details ->
                if (details.requested.group == 'com.facebook.react' && details.requested.name == 'react-native') {
                    def file = new File("$rootDir/../node_modules/react-native/package.json")
                    def version = new groovy.json.JsonSlurper().parseText(file.text).version
                    details.useVersion version
                }
            }
        }
    }
```

**Comment by piyush565** [comment]
Error still exists even after adding configurations.all in app/build.gradle, the THING is it just cant able to start or connect to the development server

**Comment by AdrianZghibarta** [comment]
Guys, did you tried one more time? cause now all my projects are running fine, it seems that the maven node was restored.

**Comment by monotv** [comment]
All good in the hood now for me.

**Comment by ignivaankushrishi** [comment]
I have observed that the temporary fix is somewhere working for react-native versions greater than 0.35.

When I tried on 29.2 it did not work in any case after lot of effort.

Now, I am not in a situation to update to latest version as it will create a lot of problems and crashes. It may not work because not all the packages or libraries are updated with latest version of react native and will not work.

**Comment by piyush565** [comment]
app running cool with version react- 15.3.2, react-native- 0.35.0, but it asks for reactnativepropsregistry.js file missing or changed. So, i put "import { ReactNativePropRegistry } from 'react-native';" in node modules/react native easy grid/utils/ compute props.js... Happy coding after struggling for 5 days straight to figure out the issue solution.

**Comment by abhrp-hs** [comment]
Hi, this issue is happening again, cannot download react-native:0.45.5 from maven, the repos do not exist on both [maven](https://mvnrepository.com/artifact/com.facebook.react/react-native) and [bintray](https://bintray.com/bintray/jcenter/com.facebook.react%3Areact-native#). Using react-native:+ downloads v0.20.1 which is a very old version and is breaking all my react native projects.

**Comment by ABKZR** [comment]
Same Problem
HELP me to solve this 


* What went wrong:          
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-vector-icons'.
      > Could not resolve all dependencies for configuration ':react-native-vector-icons:classpath'.
         > Could not resolve com.android.tools.build:gradle:2.3.+.
           Required by:
               Login_Page:react-native-vector-icons:unspecified
            > Could not resolve com.android.tools.build:gradle:2.3.+.
               > Failed to list versions for com.android.tools.build:gradle.
                  > Unable to load Maven meta-data from https://jcenter.bintray.com/com/android/tools/build/gradle/maven-metadata.xml.
                     > Could not GET 'https://jcenter.bintray.com/com/android/tools/build/gradle/maven-metadata.xml'.
                        > Permission denied: connect
