### ISSUE TITLE
zIndex not working.

### ISSUE THREAD

**Issue by Symous** [facebook/react-native#14221]
Hi, I want to create a view(said ViewA) that is draw over another view(ViewB). from the react-native document I read this:

> zIndex controls which components display on top of others. Normally, you don't use zIndex. Components render according to their order in the document tree, so later components draw over earlier ones. zIndex may be useful if you have animations or custom modal interfaces where you don't want this behavior.

But the result is : 
I put ViewA behind ViewB - not as excepted.
Give ViewA zIndex:999 ViewB zIndex:1 - not as excepted.

Is a bug of react-native ? 
ps:
React Native Version :0.43.4
Platfrom : Android

**Comment by brentvatne** [comment]
Hello! Please re-create this issue with an example on snack.expo.io as suggested in the issue template :)

**Comment by jacklovepdf** [comment]
the same as this issue:https://github.com/facebook/react-native/issues/8968
