### ISSUE TITLE
[SampleApp] Launching default app template on iPad with iOS7.0 renders incorrectly

### ISSUE THREAD

**Issue by thomasvm** [facebook/react-native#1423]
I adjusted the app generated by `react-native init <myproject>` to be Universal instead of iPhone; and the resulting app renders strangely on an iOS7.0 iPad Mini. 

![img_0140](https://cloud.githubusercontent.com/assets/140572/7836678/50875ae2-0482-11e5-8820-f93a90014a2a.PNG)

Some initial observations:
* the welcome text is not shown at all; if I put the `fontSize` property in comment, the `Text` becomes visible, but layout still isn't correct
* the text is centered correctly horizontally, but the `justifyContent` seems to have no effect at all

Details:
* iPad Retina Mini
* iOS: 7.0.4
* react-native: 0.5.0-rc and 0.4.4

**Comment by browniefed** [comment]
@thomasvm can you confirm this is still happening on the latest react-native?
Tested in simulator for iPad and iPad Retina and it all seemed to render correctly, but I don't know about retina mini on a real device.
![http://i.imgur.com/c8JMxF9.png](http://i.imgur.com/c8JMxF9.png)
@brentvatne

**Comment by brentvatne** [comment]
This issue is way old, closing for now, if it turns out to be an issue just ping me and I will reopen!
