### ISSUE TITLE
Crash on large images.

### ISSUE THREAD

**Issue by damathryx** [facebook/react-native#14237]
### Description

I display images from the server and currently its not being resized so whatever the  size it was uploaded i am getting the same when I fetch it. 

### Reproduction Steps and Sample Code

Basically I have scene that is wrapped on ScrollView, some text and views then Images under it viewed as thumbnail. After all the images are loaded, you can see that the large image is just black. When you scroll on it, scroll up then scroll down until it lags then crashes on Android.

on the Simulator it wont crash just lags terrible bad everytime the large image is on the screen but in android phone it crashes.

here is a sample code:

https://gist.github.com/damathryx/70283fd2e790130fa0ae679300462b8f

### Additional Information

* React Native version: 0.43.3
* Platform: Android
* Development Operating System: macOS

**Comment by hramos** [comment]
Here's a Snack with the same sample code as above: https://snack.expo.io/rJ7_INj-Z

This just seems like a memory issue. You'll want to download smaller thumbnails here instead.
