### ISSUE TITLE
Duplicate interface definition for class 'RCTEventEmitter' when linking PushNotificationsIOS

### ISSUE THREAD

**Issue by ahmedlhanafy** [facebook/react-native#14235]
### Description

Whenever I try to link PushNotificationsIOS following the guide in RN docs, I get this error 
```
..../node_modules/react-native/React/Modules/RCTEventEmitter.h:16:1: Duplicate interface definition for class 'RCTEventEmitter'
```
![](https://cloud.githubusercontent.com/assets/7052827/26530262/eccc947c-43d1-11e7-8ef5-63e310b14ad1.png)

### Solution
Removed `#import "CodePush.h"` from `AppDelegate.m` and the app compiled!

### Additional Information

* React Native version: 0.44
* Platform: IOS
* Development Operating System: macOS

**Comment by brycepavey** [comment]
For future reference to anyone else coming across this the issue, in my project the issue was codepush was on version incompatible with the react-native version I had installed (from upgrading react-native from 0.39 to 0.40), and was solved by installing the correct react-native-code-push version
