### ISSUE TITLE
[Bridge] Array Buffers / Typed Arrays for WebSockets, Ajax

### ISSUE THREAD

**Issue by phoboslab** [facebook/react-native#1424]
It's currently not possible to send/received ArrayBuffers with React Native.

Am I right to assume that this is largely due to the missing TypedArray implementation in JSC? I.e. we're not able to transfer raw memory in a sane and performant way between JavaScript and native.

I've opened an issue over at webkit.org (https://bugs.webkit.org/show_bug.cgi?id=120112), asking for a TypedArray API a few years ago and have written a working implementation for this API (https://github.com/phoboslab/JavaScriptCore-iOS/blob/master/JavaScriptCore/JSTypedArray.h) in my fork of JSC. Forking JSC has worked okay-ish for my own library, but now I'm stumbling over this issue again with React Native.

It would be really useful to be able to load and handle binary data for a number of use cases. So I'm wondering if you guys would be interested to weigh in on a TypedArray API or if you have any ideas how this would be workaroundable without the huge performance penalty that we currently face.

**Comment by ide** [comment]
There are two roadblocks here. One is the API limitation you described and onet solution would be to work with the WebKit team to patch the API for the next-next release of JSC.

The second issue is that the RN bridge uses JSON to communicate between JS and native. There are no shared references so you currently can't access a TypedArray from Obj-C that JS can also access. This could change at the cost of losing the Chrome debugger but if shared memory enables another class of apps that do photo processing etc that might be the right trade off.

**Comment by vkurchatkin** [comment]
We can have a separate `ArrayBuffer`  implementation that is just a handle for raw memory. They can be produced and consumed by some APIs and behave just as usual array buffers, except no direct access to bytes via typed arrays (maybe `DataView` is also possible).

**Comment by sebmarkbage** [comment]
Even without shared memory, the RN bridge could benefit from binary serialization and transferring ownership of memory. However, given the direction of the language, it might as well just be a shared reference.

**Comment by rclai** [comment]
This is also an issue for any kind of Bluetooth related functionality. Perhaps we should document current work-arounds for this?

**Comment by phoboslab** [comment]
FYI: I recently put a lot of time into a workaround for reading/writing Typed Arrays in native code and it seems to perform reasonably well. About 7ms/MB for reading, 20ms/MB for writing. The overhead of the read/write function call itself (regardless of array size) is ~0.2ms. The whole journey is documented here:
http://phoboslab.org/log/2015/11/the-absolute-worst-way-to-read-typed-array-data-with-javascriptcore

Final implementation: [EJConvertTypedArray.h](https://github.com/phoboslab/Ejecta/blob/typed-array-clusterfuck/Source/Ejecta/EJConvertTypedArray.h), [EJConvertTypedArray.m](https://github.com/phoboslab/Ejecta/blob/typed-array-clusterfuck/Source/Ejecta/EJConvertTypedArray.m)

**Comment by vkurchatkin** [comment]
it looks like this API is finally being added to JSC

**Comment by rclai** [comment]
Wow really? You have link for this?

**Comment by vkurchatkin** [comment]
@rclai https://bugs.webkit.org/show_bug.cgi?id=120112

**Comment by fungilation** [comment]
Looks like this is resolved and merged? https://github.com/facebook/react-native/pull/4483

**Comment by rclai** [comment]
Not quite, it is just a fix for WebSocket. There's more being requested in this ticket.

**Comment by springuper** [comment]
I'm writing a react-native-thrift lib, but find out that binary protocol can't be sent over xhr, Typed Arrays will make it work as [MDN](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Sending_and_Receiving_Binary_Data) says, can you continue to work for this feature?

**Comment by springuper** [comment]
#6327

**Comment by rikuayanokozy** [comment]
@springuper I tried to modify RCTNetworking and XMLHttpRequest.js to add basic binary support, it might help. See https://github.com/rikuayanokozy/react-native/commit/a40a0a1739fa99551d6248bc27c2672742fa3d09.

**Comment by cvermilion** [comment]
Looks like Typed Array support will indeed be in iOS 10: https://developer.apple.com/library/prerelease/content/releasenotes/General/iOS10APIDiffs/Objective-C/JavaScriptCore.html

**Comment by saulshanabrook** [comment]
@cvermilion Will this let it work on Android as well?

**Comment by cvermilion** [comment]
@saulshanabrook I'm not sure, but I think the Android version uses JavaScriptCore directly, so I would think so. But looking at the ReactAndroid build files it looks like it's using a pretty old commit of JSC (r174650, from 2014), so having TypedArray access might require upgrading JSC on that side?

**Comment by saulshanabrook** [comment]
I think it does, I was checking it out. Will verify that.

**Comment by sulliwane** [comment]
fetching **.gz** file in **react-native android 0.30** fails with **response.arrayBuffer()**:
```javascript
fetch('http://127.0.0.1:8125/test.txt.gz', {
  mode: 'no-cors'
})
.then(function(response) {
  return response.arrayBuffer();
})
.then(function(buffer) {
  console.log(buffer);
})
```
Here is the result from react-native running on my android device (chrome debugger):

<img width="281" alt="2016-08-07 12_43_05-react native debugger" src="https://cloud.githubusercontent.com/assets/1733686/17460514/a98ce1a2-5c9c-11e6-9222-f19032e6add5.png">

You can see **_blobBlob** and **_blobInit** in the response, as well as arrayBuffer size of **54**. It should be **42** as you can see from the correct result from firefox, running on the same android device:

<img width="608" alt="2016-08-07 12_39_12-firefox webide_ 127 0 0 1_ the html5 herald" src="https://cloud.githubusercontent.com/assets/1733686/17460518/d4c4c984-5c9c-11e6-8c3d-c14c948bc445.png">

**firefox android** and **react-native android** run the same javascript code. Why Firefox can properly use arrayBuffer on a fetch() response object, but not react-native?

note: I'm trying to download a .gz file as an arrayBuffer to then decompress it using [pako](https://www.npmjs.com/package/pako).

**Comment by robclouth** [comment]
So TypedArray support is now in iOS 10. For earlier versions we could either use the code @phoboslab wrote, or show an unsupported error. On Android we'd need to rebuild android-jsc with a newer version of WebKit, and add it to maven. That would be TypedArray support on the JSC side done.
How would we start adapting the bridge?

**Comment by lacker** [comment]
We are trying to keep issues focused on bugs and this is more of a feature request, albeit a very cool and valuable feature request. I am going to close this issue but if people are interested in working to improve this then that would be pretty great!

**Comment by rclai** [comment]
Is there at least a Product Pain for this?

**Comment by lacker** [comment]
I don't see one, you could create a new one! Maybe we should flush out Product Pains every once in a while to keep it fresh....

**Comment by leoselig** [comment]
@rclai @lacker 
Product pain was added a while ago: https://react-native.canny.io/feature-requests/p/packager-support-resolvealias-ala-webpack
Kind of sad that the discussion on this died down
A wrap up of outstanding issues on this would be nice - maybe someone (*cough*) could give it a go

**Comment by idibidiart** [comment]
@sebmarkbage how would a shared reference get implemented? seems too low level for JS. 

@all can we take care of the bridge--is-the-bottleneck issue? seems that the JS<->Native interop is the "weakest link" in the RN performance story.

**Comment by gre** [comment]
We are discussing and looking for a way to implement a `UInt8Array pixels => Promise<encoded image uri>` at https://github.com/react-community/react-native-webgl/issues/2#issuecomment-328343029 and unfortunately hitting on this missing support. However, in Expo EXGLView (and react-native-webgl fork) there are support for typedarray, via using C++ and accessing JSC environment with a fallback when not supported (iOS < 10, android). (see https://github.com/expo/expo/blob/master/cpp/UEXGL.cpp#L339-L403 & https://github.com/expo/expo/blob/master/cpp/EXJSConvertTypedArray.c )

I wonder if it could be generalized in RN? and if so, what would it mean when in ObjC iOS/Java Android (and not just in C++ support) – would it also mean RN to provide an abstract new type on top of this?
