### ISSUE TITLE
[Question] Should not LayoutAnimation utilize the UI thread instead of the JS thread?

### ISSUE THREAD

**Issue by grundmanise** [facebook/react-native#14248]
When `LayoutAnimation` runs I can see in the `perf monitor` that the `UI` thread's FPS stays the same whereas`JS` FPS drops. Does not `LayoutAnimation` run on the `UI` thread or it is calculating each frame on the `JS` thread?

**Comment by hramos** [comment]
Issues are not the best place to ask these sorts of questions, sorry. We'd like to focus on reproducible bugs.

**Comment by grundmanise** [comment]
Sorry, definitely a question for SO.
