### ISSUE TITLE
[Navigator] React Hot Loader and StaticContainer Usage in Navigator

### ISSUE THREAD

**Issue by skevy** [facebook/react-native#1425]
I'm opening this issue for discussion at the moment, because I'm not quite sure what the proper fix is yet.

React Native's Navigator uses a pattern that will return, if the component has already been rendered before, a `StaticContainer` element that has no children with the `shouldUpdate` prop set to false. This never breaks "in real life", because the whole point of not updating that component is to keep the previous reconciliation. The problem is, when using something like React Hot Loader, it force updates all components in the tree...so it will fail with an onlyChild invariant violation in StaticContainer when this pattern is used.

Can we think of any elegant way to keep Navigator working with React Hot Loader? Theoretically, in the check in NavigatorNavigationBar and NavigatorBreadcrumbNavigationBar that is determining whether to recalculate the children or not, if we could know whether or not the component is being forceUpdated, we could allow for the recalculation of the children. I'm just honestly not sure how to check for that, or if that's some kind of anti-pattern.

/cc @ericvicenti

**Comment by ide** [comment]
@ericvicenti mentioned in another discussion that StaticX components can often be replaced by holding a reference to the JSX element, and returning the same element instance from render() each time it is called. That should be robust against forceUpdates too.

**Comment by skevy** [comment]
@ide do you have a link to that discussion?

**Comment by ide** [comment]
https://github.com/facebook/react-native/pull/262#issuecomment-101371638

**Comment by skevy** [comment]
Cool, so based on that, we should work on updating Navigator to use that new pattern, rather than the StaticContainer pattern

**Comment by skevy** [comment]
@ericvicenti I saw somewhere you were working on a refactor of Navigator...does it include this change?

**Comment by ericvicenti** [comment]
Yep, we should totally migrate to the "freezing" technique of putting the rendered descriptor directly into the state and using it directly in later renders instead of StaticComponent

The change that will be coming in a few days is actually removing the contextual navigation capabilities from Navigator, because it is causing too much complication. A better and more isolated solution for contextual navigation will come later

**Comment by skevy** [comment]
This doesn't apply anymore, as Navigator no longer uses StaticContainer. Closing.
