### ISSUE TITLE
Unable to resolve module `react/lib/ReactDebugCurrentFrame`

### ISSUE THREAD

**Issue by ShanthiSenguttuvan** [facebook/react-native#14269]
I am developing android app. I have updated my react-native version to 0.44.2. my react version is 15.5.4.  i got the following error while bundling,
error: bundling: UnableToResolveError: Unable to resolve module `react/lib/ReactDebugCurrentFrame` from '.../node_modules/react-native/Libraries/Renderer/src/renderers/shared/fiber/ReactFiberContext.js`: Module does not exist in the module map or in these directories:
  .../node_modules/react-native/node_modules/react/lib

my react package does not have ReactFiberContext.js.

What the supported react version?

**Comment by raffij** [comment]
The version of react-native you are using has a devDependency of:

https://github.com/facebook/react-native/blob/4a32ec5b4f805a57a11423497043ee646fee20e8/package.json#L227

**Comment by ShanthiSenguttuvan** [comment]
Thanks for your reply.
Issue has been solved my installing react@16.0.0-alpha.6
