### ISSUE TITLE
Crash within RCTShadowText - Line 29.

### ISSUE THREAD

**Issue by admmasters** [facebook/react-native#1426]
EXC_BAD_ACCESS @ [textStorage addLayoutManager:shadowText.layoutManager].

Within: static css_dim_t RCTMeasure(void *context, float width) function.

**Comment by ide** [comment]
Closing this out since https://github.com/facebook/react-native/commit/0689c0790edcc9cb8494e3f15300e2743556f442 hopefully fixes the source of the text crashes.
