### ISSUE TITLE
After react native upgrade to 0.44.2 InteractionManager runAfterInteractions not fired.

### ISSUE THREAD

**Issue by AkilLis** [facebook/react-native#14271]
After upgrade react native version 0.42.0 to 0.44.2 InteractionManager runAfterInteractions method doesn't work not even called. 

Trying to call after componentDidMount.

componentDidMount() {
  InteractionManager.runAfterInteractions(() => {
     this.setState({
          interactionsComplete: true});
     })
}

React Native version: 0.44.2
Platform: Android
Development Operating System: Linux
Dev tools: Android Studio version,Android SDK version

**Comment by rocwangv** [comment]
+1

**Comment by dioxide** [comment]
+1

**Comment by lyxia** [comment]
+1

**Comment by mjylfz** [comment]
how to solve the problem？
