### ISSUE TITLE
index.ios.bundle not updating

### ISSUE THREAD

**Issue by mxstbr** [facebook/react-native#1427]
OSX 10.10.3, npm 2.10.1, watchman 3.1.1

If I change something in the `index.ios.js` file in my code editor (Sublime Text), the changes are not reflected in the simulator until I run the `npm start` command again. 
Occasionally I get the `watchman took to long` error (cannot reproduce it), but have already taken and tried all the steps outlined on both troubleshooting pages, of react-native and of watchman.
I've also already tried everything outlined [here](https://github.com/facebook/react-native/issues/910), [here](https://github.com/facebook/react-native/issues/490#issuecomment-89235460) and repaired the permissions using the Disk Utility, as per recommendation from [here](http://feedback.livereload.com/knowledgebase/articles/86239-os-x-fsevents-bug-may-prevent-monitoring-of-certai).

Now, the thing is, I thought it might be a fsevents–bug, and I do get results when I use Andreys [find-fsevents-bugs](https://github.com/andreyvit/find-fsevents-bugs) tool. The problem is, none of the things recommended doing with those results [here](http://feedback.livereload.com/knowledgebase/articles/86239-os-x-fsevents-bug-may-prevent-monitoring-of-certai) fixes it. (And a full reboot doesn't either)

I've talked to @brentvatne on `IRC`, sadly he couldn't help me either but told me to submit this problem as an issue here and ping @amasad. 

Hope somebody has an idea on how to fix this issue, thanks for any help I can get.

**Comment by mxstbr** [comment]
After further investigation, this issue has nothing to with react native/watchman. No build tool is working, and it is the FSEvents Bug, as explained in great detail here: https://github.com/bdkjones/fseventsbug/wiki/realpath()-And-FSEvents (and, for 5 years of discussions about this bug, look here: https://github.com/thibaudgg/rb-fsevent/issues/10)

There is currently no real fix for it, but I expect Apple will fix it with one of the major OSX updates in the future. Closing this issue, but pinging @brentvatne and @amasad. Read through the post above, this issue might come up again. Cheers!

**Comment by brentvatne** [comment]
Thanks @mxstbr for the follow up!

**Comment by amasad** [comment]
Thanks. fseevents is terrible
