### ISSUE TITLE
get user inactivity in react native

### ISSUE THREAD

**Issue by tonystaa** [facebook/react-native#14287]
This is not a bug or a feature request(as I don't not know if the solution exist already).
I have posted a question on stackoverflow 6 days ago ( [https://stackoverflow.com/questions/44196459/get-user-inactivity-in-react-native](url) ), but it got no answers.
My question is very simple-
What I want, is to display an Image if user does not interact with the app for 1 minute. I have tried implementing it by setting timers on all the user events like onPress, onSwipe etc on all the UI elements. 
I want to display different images on different user screen(if user does not interact with app for 1 minute) and that's why I cannot set timers on all the event on all the screens because handling those will be very cumbersome. Then I tried out using InteractionManager but that also didn't work out. What I want to know is there any way I can get to know if any user event has occurred?

**Comment by hramos** [comment]
This is not the best place for this sort of question, I'm afraid. We'd like to focus on actionable issues with the framework itself.

**Comment by brentvatne** [comment]
I agree with @hramos, and I certainly don't want to encourage posting these kinds of questions on the issues, however I did want to chime in on this for posterity.

This would be very easy to implement *if it were not for some quirks with the current react-native gesture system* -- specifically, you can't have a view both 1) respond to a touch and 2) let the touch pass through to other views. There's a library that gets around this by [implementing a custom touch handler to both respond to and pass-through touches](https://github.com/xinthink/react-native-material-kit/blob/master/iOS/RCTMaterialKit/MKTouchableManager.m), and @kmagiera is [working on an improved + backwards compatible gesture handling library](https://github.com/kmagiera/react-native-gesture-handler) that would also solve this. For a short-term solution it's probably easiest to use something like what react-native-material-kit provides and do something like this: https://snack.expo.io/ryKsT6TWb

It's possible that there is some other solution but I can't think of one off of the top of my head.

**Comment by brentvatne** [comment]
I stand corrected, by myself, here is a working solution: https://snack.expo.io/H1gk4AaZb

Rather than using an overlay like in the previous example I shared, just attach the the pan handlers to the root of the app.

**Comment by jkomyno** [comment]
@tonystaa I've created a small library around the link @brentvatne posted, but it seems that onPress events aren't captured by the PanResponder used. I don't want to encourage posting of these kinds of questions here on issues either, but would have suggestion?
https://github.com/jkomyno/react-native-user-inactivity

**Comment by cvarley100** [comment]
@jkomyno Did you come up with a solution to onPress detection in the end?
