### ISSUE TITLE
 UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1966): SyntaxError: SyntaxError /home/app/file.js: Unexpected token (71:8)

### ISSUE THREAD

**Issue by soniyachandran** [facebook/react-native#14285]
### Description

I used the Fetch API to fetch some data from the network and display it in a ListItem . But i got error as " UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1966): SyntaxError". Help me from this iissue i want to display the response in Listitem

import React, {Component} from 'react'
import {Text, View, StyleSheet, TextInput, ScrollView,Image} from 'react-native'
import {Item, Input, ListItem,  Body,Button,Container} from 'native-base'

export default class OpenMic extends Component {
     static navigationOptions = {
        header: {
            visible : false
        }
    }
    constructor(){
       super()
       this.state ={
                    data:{openmic:[]}
       }
   }
   getData = () => {
     fetch('http://35.186.157.230:9000/dummy/getallopenmic', {
        method: 'GET'
     })
     .then((response) => response.json())
     .then((responseJson) => {
        console.log("json::"+responseJson);
         this.setState({
           data: responseJson
        })
         })
     .catch((error) => {
        console.error(error);
     });
   }
    componentDidMount(){
      this.getData();
    }
  
    makeList= (item) => (
         <Text
            key={item.title}
            >
            {item.title}
      );

    render(){
        return (
          <Container  style={{flex:1}}>
            <ScrollView style={styles.container}>
            <View style={{ flex:1,flexDirection:'row',backgroundColor:"transparent",marginTop:5}}>
              <View style={styles.formContent}>
               <View style={styles.inputFieldWrapper}>
                <ListItem>
                   <Body>
               <Text style={styles.listheader}></Text>
                { this.state.data.openmic.map(this.makeList)}
               </Body>
             </ListItem>
             </View>
           </View>
        </ScrollView>
      </Container>
    );
    }
}

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
