### ISSUE TITLE
panResponder doesn't work with Modal

### ISSUE THREAD

**Issue by tibbus** [facebook/react-native#14295]
### Description

`onMoveShouldSetPanResponder ` is not triggered inside the `Modal` component, when used outside is triggered just fine.

### Reproduction Steps and Sample Code

https://snack.expo.io/HkttB70ZZ

1. Click on the `Touch me !!` green box and the alert from the event should be triggered.
2. Click on `Click Open Modal` to open the Modal.
3. Click on the `Touch me !!` green box, observe that event is not triggered anymore.

### Additional Information

* React Native version:  0.44.2
* Platform:  iOS
* Development Operating System: macOS

**Comment by tibbus** [comment]
I tested in the last version `v0.45.1` still doesn't work.

**Comment by srameshr** [comment]
Same here!

**Comment by tiendn** [comment]
Same here!
**Additional Information**

 * React Native version: 0.47.1
 * Platform: iOS
 * Development Operating System: macOS

**Comment by hkung77** [comment]
Metoo..

I'm on react native : 0.41.2
Platform iOS & android.

**Comment by alzalabany** [comment]
same here, not working on .49

**Comment by marioskonstantinou** [comment]
Any updates on this? It's still not working.

**Comment by onlybenyang** [comment]
I try to wrap a <TouchableOpacity> outside of the view, it works

**Comment by MeisterTea** [comment]
I just had this issue,
I fixed it by following these instructions
https://github.com/facebook/react-native/issues/9786#issuecomment-262932857
Enjoy !

**Comment by jakallergis** [comment]
I tried @onlybenyang 's workaround and the modal now successfully releases its responder.
So Im using this for now:

```javascript
render() {
    /**
     * Im using the TouchableWithoutFeedback with its View as a workaround
     * so that this component is swipable even when it is inside a modal,
     * because modals do not release their responder properly.
     */
    return (
      <Animated.View style={ { marginTop: this.position } } { ...this.panResponder.panHandlers }>
        <TouchableWithoutFeedback>
          <View>
            
            // The component's content goes here

          </View>
        </TouchableWithoutFeedback>
      </Animated.View>
    );
  }
```

**Comment by b1acKr0se** [comment]
@onlybenyang @jakallergis What if I have more Touchables inside the wrapper TouchableWithoutFeedback? the inner Touchable does not respond to click event at all.

**Comment by orangecoloured** [comment]
Why is this issue is closed?
`panResponder` does not work properly with the `Modal` component.

**Comment by dbarner1** [comment]
Check out react navigation's modal.  Replaced a modal with its version of a modal, and registered touches perfectly: https://reactnavigation.org/docs/en/modal.html

**Comment by athammer** [comment]
For me what fixed the issue was making sure I included all of panresponder's [methods](https://facebook.github.io/react-native/docs/panresponder).  Personally all I was missing was...
`onStartShouldSetPanResponder: (evt, gestureState) => true,`
and once I added that it was fixed. If you can't get it to work try adding all of panresponder's methods just to check that you are not missing anything.

good luck!

**Comment by gdelazeri** [comment]
@jrob-io your solution works for me, thanks!

**Comment by nathggns** [comment]
This issue should not be closed. I just ran into it myself too. Should we just recreate it?

**Comment by alainib** [comment]
i get this bug too

**Comment by yamankatby** [comment]
For me I fixed this issue by following this steps
- Firstly All your PanResponder functions must return `true` as following
```js
this.panResponder = PanResponder.create({
    onMoveShouldSetPanResponder: () => true,
    onPanResponderMove: (evt, gestureState) => {
        console.warn('Start Moving');
        return true;
    },
});
```
- Then you have to wrap your content with TouchableWithoutFeedback don't forgot to pass it any function as `onPress` prop because `Touchables` without `onPress` throwing exception on release  
```js
<View {...this.panResponder.panHandlers}>
    <TouchableWithoutFeedback onPress={() => {}}>
        {this.props.children}
    </TouchableWithoutFeedback>
</View>
```
