### ISSUE TITLE
Has 'vertical-align' feature been added?

### ISSUE THREAD

**Issue by ckim16** [facebook/react-native#14309]
I saw several issues with vertical-align and I was wondering that feature is now being supported yet.

I want to position my text on the bottom of the image but I can't find a way to get around this.

If anyone can give me any update or advice, I would appreciate it.

Thank you,

**Comment by hramos** [comment]
I'm not sure which issues you're referring to - I'd check the releases notes to see if anything specific to vertical-align is covered. I'm going to close this as we're only using issues to track specific bugs in the core library.
