### ISSUE TITLE
[Packager] Please add a second target to React project that does not launch the packager.

### ISSUE THREAD

**Issue by bparadie** [facebook/react-native#1430]
`React.xcodeproj` currently only supports one target that always launches the `packager` through this run script:

```
if nc -w 5 -z localhost 8081 ; then
  if ! curl -s "http://localhost:8081/status" | grep -q "packager-status:running" ; then
    echo "Port 8081 already in use, packager is either not running or not running correctly"
    exit 2
  fi
else
  open $SRCROOT/../packager/launchPackager.command || echo "Can't start packager automatically"
fi
```

Because not everybody on our team is involved in developing UI we decided to use two separate targets in our project. One of those targets is for 'core development' only while the other one defines `UI_DEV` for 'UI development'. In our `AppDelegate.m` we use `localhost` for UI dev and `main.jsbundle` for core dev:

```
#ifdef UI_DEV
  jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/build/js/app.jsx.bundle?dev=true"];
#else
  // OPTION 2
  // Load from pre-bundled file on disk. To re-generate the static bundle, run
  //
  // $ curl 'http://localhost:8081/build/js/app.jsx.bundle?dev=false&minify=true' -o iOS/main.jsbundle
  //
  // and uncomment the next following line
  jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
```

While this all works great for us, core dev still launches the `packager` even though it's not needed, because we pull the resources from `main.jsbundle`. 

Having a second target `React.xcodeproj` that does not automatically launch `packager` would help us greatly. That would also allow us to work around issues like https://github.com/facebook/react-native/issues/1429.

**Comment by bparadie** [comment]
My proposal would work for us, see https://github.com/bparadie/react-native/tree/v0.5.0-rc-nopackager

![screen shot 2015-05-27 at 2 14 05 pm](https://cloud.githubusercontent.com/assets/1578115/7847728/636db85c-047a-11e5-872c-ddfaaee3e2eb.png)

I duplicated the `React` target and changed the name to `React-NoPackager`. I had to patch the project file afterwards and change all `React copy.a` strings to `React-NoPackager.a`, because of `XCode` quirks.

In our main project file I then selected `libReact-NoPackager.a` for the core dev target:

![screen shot 2015-05-27 at 2 17 20 pm](https://cloud.githubusercontent.com/assets/1578115/7847792/d5258970-047a-11e5-9587-6994212d9803.png)

Ignore the red color of `libReact-NoPackager.a`. That's just one of many other `XCode` quirks.

**Comment by ide** [comment]
This may or may not work for you but if you use the podspecs via CocoaPods you'll skip using the FB-provided React.xcodeproj and therefore drop the magic packager launcher.

**Comment by bparadie** [comment]
@ide Thanks for the tip. I am not super familiar with podspecs. We have to use `npm`. Right now I pull in the React projects from `node_modules`. That's also what I see in every example.

**Comment by ide** [comment]
You can use npm along with the podspecs. It's not documented but it's a standard cocoapods setup.  Probably best to find an iOS/app developer on your team who can help set it up.

**Comment by bparadie** [comment]
@ide I'll try that. I am curious: Do you agree, that it would be a good idea to have a second target that does not automatically launch the `packager`? Or do you suggest using podspecs for use cases like mine?

**Comment by ide** [comment]
My thinking is that instead of putting the launch script in React.xcodeproj, it'd be better for the top-level projects like UIExplorer.xcodeproj and SampleApp.xcodeproj to have the script. You could make the argument that React.xcodeproj implies that you need the packager but users who are manually linking React are also the kind of users who want to set up their own packager scripts and aren't expecting everything to work out of the box.

**Comment by bparadie** [comment]
I agree that having a launch script baked into `React.xcodeproj` is not such a great idea. On the other hand the `packager` is pretty important to get react-native working properly. Perhaps a good compromise  would be moving that run script into its own separate project, i.e. `Packager.xcodeproj`. 
There are probably many ways to skin this cat. Bottom line:  I would love to see that launch script removed from  `React.xcodeproj`!

**Comment by jtremback** [comment]
:+1: :+1: 

Personally, I have been getting a bunch of weird errors from many packager instances building up over time after multiple recompiles. 

https://github.com/facebook/react-native/issues/1437

**Comment by ide** [comment]
@frantic, @amasad, what do you think about moving the packager startup script out of React.xcodeproj and into the individual top-level project files like UIExplorer and SampleApp?

**Comment by amasad** [comment]
I'm not familiar with the tradeoffs here. I'll leave it to @frantic

**Comment by frantic** [comment]
> @frantic, @amasad, what do you think about moving the packager startup script out of React.xcodeproj and into the individual top-level project files like UIExplorer and SampleApp?

Yes, this seems to be the right thing to do.

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/packager-please-add-a-second-target-to-react-project-that-does-not-launch-the-packager
