### ISSUE TITLE
[Packager] Requiring a script without newline at the end of file fails

### ISSUE THREAD

**Issue by uber5001** [facebook/react-native#1431]
I can't seem to reproduce this issue for a single file. For libraries and packages installed from npm, however, this issue appears, in the form of

    Uncaught SyntaxError: Unexpected end of input                    RunMainModule.js:1

If I add newlines to every file in the library or package, the error goes away.

**Comment by ide** [comment]
cc @amasad

**Comment by josebalius** [comment]
I am having the same problem....and can't figure out what's causing it....it started to happen out of nowhere.

**Comment by amasad** [comment]
huh, can you add test case? A specific npm module?

**Comment by josebalius** [comment]
@amasad I will try to get a test case for you.

**Comment by uber5001** [comment]
In my case, I init the project:

    react-native init AwesomeProject
    cd AwesomeProject
    npm install reflect-metadata

and add this line below the first require in index.ios.js:

    require('reflect-metadata');

Which causes the error described above when run in XCode.

This error can be fixed by adding newlines:

    find node_modules/reflect-metadata -name "*.js" -type f -exec sed -i '' -e '$a\' {} \;

**Comment by amasad** [comment]
I can't replicate this with the latest react-native. Which version are you using?

Latest uses Babel transformer and we don't print the comments, which I think is the problem in this case. If there is a comment at the last line then it would cause a problem. I'll fix this by adding a newline, but I'm just curious about if you're using babel or are you at an older version?

**Comment by amasad** [comment]
Landed a fix for this internally. Meanwhile until the next sync you can update to start using babel which shouldn't be an issue with it.

**Comment by uber5001** [comment]
I'm using 

    react-native-cli@0.1.3
    react-native@0.4.4

Which are the most recent versions on npm.

**Comment by amasad** [comment]
There should be a v0.5.0-rc release.

**Comment by uber5001** [comment]
I'm now at:

    "dependencies": {
        "react-native": "^0.5.0-rc1",
        "reflect-metadata": "^0.1.0"
    }

Nothing seems to have changed. Still getting the error when `reflect-metadata` hasn't been modified with new newlines at the ends of its .js files.

**Comment by jaulz** [comment]
Unfortunately I face the same issue. Upgraded to the latest version from git today and since then I have no idea how to fix it. @amasad: this version should already have babel or am I wrong?
