### ISSUE TITLE
React Native Execution failed for task ':app:mergeDebugResources'.

### ISSUE THREAD

**Issue by FrenchMajesty** [facebook/react-native#14315]
Hey, I am trying to get react-native to work with Android but when I run react-native run-android I get this:

> :app:mergeDebugResources
> AAPT: libpng error: Read Error
> AAPT err(Facade for 273543934) : No Delegate set : lost message:libpng error: Read Error
> AAPT: libpng error: Read Error
> AAPT: libpng error: Read Error
> Error: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: 
> :app:mergeDebugResources FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:mergeDebugResources'.
> > Error: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: 
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> BUILD FAILED
> 
> Total time: 17.832 secs
> Could not install the app on the device, read the error above for details.
> Make sure you have an Android emulator running or a device connected and have
> set up your Android development environment:
> https://facebook.github.io/react-native/docs/android-setup.html

My emulator works fine, I can open my virtual device through Android Studio.
By default Android Studio came with the latest version, Android 7.1.1. I tried to install Android 6.0 but it did not fix the issue.
I also tried making a new project, cleaning the project and starting again but without success.
Most of the "solutions" that can be found online involve the use of the `android` command line but unfortunately it has been deprecated. I don't think downgrading would be a good idea.

### My system

* React Native version: 0.44.2
* Platform: Android
* Development Operating System: mac OSX El Capitan
* Dev tools:
Android Studio 2.3.2
Build #AI-162.3934792, built on April 21, 2017
JRE: 1.8.0_112-release-b06 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by FrenchMajesty** [comment]
Forgot to add:
My emulator works fine when I open my virtual device through Android Studio.

**Comment by hramos** [comment]
Can you try going through the getting started instructions? You'll need to switch to the latest version of the doc by clicking on the version number at the top.

**Comment by FrenchMajesty** [comment]
![screen shot 2017-06-03 at 8 28 43 pm](https://cloud.githubusercontent.com/assets/24761660/26758153/889d2592-489b-11e7-9ffa-27596c2a2167.png)
![screen shot 2017-06-03 at 8 29 00 pm](https://cloud.githubusercontent.com/assets/24761660/26758151/8899d716-489b-11e7-89ef-64566e6570e8.png)
![screen shot 2017-06-03 at 8 29 58 pm](https://cloud.githubusercontent.com/assets/24761660/26758152/8899e01c-489b-11e7-9dca-19ab3a70c020.png)
I have re-done the getting started instructions. Every works just like it did before but the `run-android` still fails

**Comment by FrenchMajesty** [comment]
I have kind of lost hope of figuring this out... but on the doc it says 

> react-native run-android is just one way to run your app - you can also run it directly from within Android Studio or Nuclide.

But I can't find informations on how to run it directly from Android Studio

**Comment by hramos** [comment]
You can launch it like any regular app built using Android Studio exclusively. You can find more in the Android Studio docs: https://developer.android.com/training/basics/firstapp/running-app.html

**Comment by hramos** [comment]
Closing this issue as we haven't heard back from the author.

**Comment by ozgesevin** [comment]
do not run the node.js command prompt as a administrator.Just click on the node.js command prompt and cd projectname
react-native run-android
