### ISSUE TITLE
Modal not showing

### ISSUE THREAD

**Issue by mykelaballe** [facebook/react-native#14311]
RN: 0.34.0
Platform: iOS

With or without remote debugging, the modal is does not show on iOS simulators. Works fine on Android.

**Comment by hramos** [comment]
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!
