### ISSUE TITLE
navigation template is not working anymore

### ISSUE THREAD

**Issue by dunhuang** [facebook/react-native#14313]
App generated by cli 'react-native init --template navigation' is not working anymore. The template should be upgraded.

**Comment by hramos** [comment]
This hasn't fully launched just yet. When you use a template name, it will look for a npm package named `react-native-template-XXXX` where XXXX is the template name. I don't see a `react-native-template-navigation` template in the npm registry.

**Comment by hramos** [comment]
Turns out this particular template is not loaded from npm, but rather is bundled in the `react-native` package itself. The template can be found at https://github.com/facebook/react-native/tree/master/local-cli/templates

What specifically is not working for you?
