### ISSUE TITLE
[FlatList] FlatList onEndReached no work android

### ISSUE THREAD

**Issue by KeyX-y** [facebook/react-native#14312]
<FlatList
        data={dataSource}
        keyExtractor={(_, i) => i}
        ItemSeparatorComponent={this._renderSeparator}
        renderItem={({ item }) => this._renderListItem(item)}
        onRefresh={() => this.handleRefresh()}
        refreshing={refreshing}
        onEndReached={() => this.handleLoadMore()}
        onEndReachedThreshold={0.3}
      />

this is no work  in android,
can work in ios

**Comment by shergin** [comment]
Can you provide a minimal amount of code to reproduce this using [Sketch](http://sketch.expo.io)? This is necessary for people to be able to see and debug the issue being reported.

**Comment by PauloDurrerMelo** [comment]
+1

onEndReached is called one or two times before the first load ends and data array is filled. 
It should only get called when the data is loaded and the onEndReachedThreshold is true. Since no data is yet displayed, the onEndReached should not be called.

This does not happen on iOS.

**Comment by TheCodeNinja** [comment]
I'm having this issue as well; onEndReached simply never fires. Here's a link to a sketch that reproduces the issue on android: https://snack.expo.io/SkNo3vn7-

Very frustrating; haven't even been able to find a functional workaround.

**Comment by iainheng** [comment]
I had the same problem with onEndReached is not called on Android when FlatList is scrolled to the bottom when I have prop `onEndReachedThreshold={0}`. Change the `{0}` to any number greater than `0` will make it working again. 

This issue only happen on Android but not iOS.

**Comment by yash2code** [comment]
same issue

**Comment by zakster12** [comment]
same here

**Comment by vvavepacket** [comment]
+1, happening on android on react native 0.45 any solution?

**Comment by vishnuc** [comment]
+1 same for me

**Comment by phumaster** [comment]
+1

**Comment by phumaster** [comment]
I think this is not a bug. My FlatList trigger onEndReached once time. This is problem. When onEndReached trigger, we must get new data and append to the old data => FlatList change and onEndReached can be fire. 
My emulator: Pixel_API_25(AVD) - 7.1.1.
React native: 0.46.1.
Worked!

**Comment by yash2code** [comment]
@phumaster can you explain with sharing some code. Ty!

**Comment by phumaster** [comment]
My FlatList
```javascript
<FlatList
                    data={this.props.data.data}
                    renderItem={this.renderItem}
                    keyExtractor={this.keyExtractor}
                    initialNumToRender={10}
                    onEndReached={this.handleOnEndReached}
                    onEndReachedThreshold={0.5}
                    refreshing={fetching}
                    onRefresh={this.handleOnRefresh}
                />
```

I get data. => FlatList have 10 Items

when onEndReached fire i get data from api. Then I change data in reducer (I use Redux)
```javascript
let {data} = action.payload;
            let hasData = data && data.results && data.results.length > 0;
            state = {
                ...state,
                fetched: true,
                fetching: false,
                data: hasData ? {data: [...state.data.data, ...data.results], nextPage: data.next_page} : {
                    data: [],
                    nextPage: -1
                }
            };
```

=> FlatList has 20 Items. And onEndReached work!

`state.data.data` is old data.

**Comment by zhanghuiyun** [comment]
I have a same problem.

**Comment by dan-klasson** [comment]
Still not fixed. Same problem here on Android.

**Comment by Sadanandteggi** [comment]
I found answer here , I initially tried all solutions given in github comments nothing worked, but finally check this answer which worked for me. Hope it will work for other too.

https://stackoverflow.com/questions/48740770/react-native-flatlist-pagination-not-working-onendreached-doesnt-fired/48747461#48747461

**Comment by lucasleelz** [comment]
+1

**Comment by tranduykhanh** [comment]
In my case onEndReached was not called because the list is not long enough.
So i hacked by adding marginTop to the container of FlatList. After the first fetch i remove that marginTop and anything work as expected
