### ISSUE TITLE
`LikeView` has no propTypes defined

### ISSUE THREAD

**Issue by joncursi** [facebook/react-native#14338]
I'm using the [`react-native-fbsdk`](https://github.com/facebook/react-native-fbsdk) package in React Native (I would post this to that repo, but they don't accept GitHub issues, so this is the next best place). When I booted up RN this morning, I started getting the following redbox error:

```
`LikeView` has no propTypes defined
```

![screen shot 2017-06-06 at 6 47 56 am](https://cloud.githubusercontent.com/assets/4974609/26825708/18519882-4a84-11e7-9f1a-e1b1a681ac68.png)

I noticed this error on RN `0.44.2` this morning so I decided to upgrade to the latest `0.44.3` to see if that would resolve it, but getting the same issue.

Thoughts?

**Comment by joncursi** [comment]
I wonder if this could be from a new babel plugin I installed yesterday:

```
babel-plugin-transform-react-remove-prop-types
```

However, I have tried removing this plugin and node_modules and re-installing node modules, but no luck.

**Comment by hramos** [comment]
According to the fbsdk repo, any bugs or issues should be reported to https://developers.facebook.com/bugs/. That's likely why it does not accept GitHub issues.
