### ISSUE TITLE
[Text] Having an emoji changes line height

### ISSUE THREAD

**Issue by bernatfortet** [facebook/react-native#14331]
To reproduce copy this to any view
```
<Text style={{backgroundColor:'red', marginBottom:12}}>This text has no emojis</Text>
<Text style={{backgroundColor:'red'}}>This text has 😑 emojis</Text>
```

![image](https://cloud.githubusercontent.com/assets/390010/26812540/220e680c-4a2d-11e7-9085-126aa9c1ae76.png)
notice the difference in height

Expected both lines have the same height.
As you can expect in any text emojis should not affect the line height for example in github 👇

Related to https://github.com/facebook/react-native/issues/4457

**Comment by hramos** [comment]
I saw you re-opened #4457. Can you make sure to fill out the issue template in its entirety?

**Comment by hramos** [comment]
Closing this issue as we haven't heard back from the author.
