### ISSUE TITLE
[Packager] Only a single simulator gets LiveReload/HMR connections in Xcode 9

### ISSUE THREAD

**Issue by orta** [facebook/react-native#14334]
### Description

Installed the Xcode9-beta simulator, opened up my app in two different devices and hit save.

![screen shot 2017-06-06 at 09 15 10](https://cloud.githubusercontent.com/assets/49038/26819971/1a95f920-4a99-11e7-96d7-063e15077e18.png)

You can see it happening in this tweet: https://twitter.com/orta/status/872002403930968064

### Reproduction Steps and Sample Code

List all the steps required to reproduce the issue you're reporting. These steps should be clear and concise.

- The beta can be downloaded from https://developer.apple.com/xcode
- If you run your app from the Xcode project, you can run it twice by changing the device type in this device switcher

![screen shot 2017-06-06 at 09 20 24](https://cloud.githubusercontent.com/assets/49038/26820064/6b721f0e-4a99-11e7-8c0b-06f041a8e685.png)

Once you have two simulators running, whichever simulator you hit `cmd +r` on last is the one that receives notifications about the module changes.

### Solution

Ideally React Native Packager would support multiple connections.

### Additional Information

* React Native version: 0.45
* Platform: iOS 
* Development Operating System: macOS
* Dev tools: Xcode 9

**Comment by linnett** [comment]
+1 

This problem occurs also when there are multiple physical devices running hot reload. The only one that updated is the last one you enable

**Comment by ajostergaard** [comment]
https://react-native.canny.io/feature-requests/p/hot-reload-multiple-clients-simultaneously

**Comment by ajostergaard** [comment]
I have what appears to be the same problem when running Android and iOS simulators simultaneously - the last one reloaded gets the hot reload. Does that work for others?
