### ISSUE TITLE
Incorrect react-native-custom-components package linked on latest release notes

### ISSUE THREAD

**Issue by markgoodyear** [facebook/react-native#14337]
I notice the `react-native-custom-components` link goes through to https://yarnpkg.com/en/package/react-native-custom-components instead of https://yarnpkg.com/en/package/react-native-deprecated-custom-components on the latest release notes (http://d.pr/i/v4ObOa/27V3MyOK).

Just thought I'd point it out incase it causes any confusion.

**Comment by hramos** [comment]
Fixed, thanks.
