### ISSUE TITLE
ES6 support bug

### ISSUE THREAD

**Issue by magicismight** [facebook/react-native#1433]
As this [DOCUMENT](http://facebook.github.io/react-native/docs/javascript-environment.html#content) said,
react native\`s JavaScript environment should support `Computed Properties`.
But those code will throw an exception `Uncaught SyntaxError: Unexpected token [` in `v0.4.4`

```javascript
var key = 'abc'; var obj = {[key]: 10};
```

**Comment by ide** [comment]
This will be fixed once babel lands.

**Comment by ide** [comment]
Babel landed in master: https://github.com/tadeuzagallo/react-native/commit/56d6ee3f0fadeb66aeb6cf9156c723759f48f617

**Comment by jaygarcia** [comment]
@ide , this is great. Question: will 5.0.0 be used? I'd sure like to use decorators =)

http://babeljs.io/blog/2015/03/31/5.0.0/

**Comment by ide** [comment]
I imagine so. Peek at package.json.
