### ISSUE TITLE
Confused on version

### ISSUE THREAD

**Issue by jbcullis** [facebook/react-native#14341]
I cannot reproduce this error at will, it seems when an update is interrupted the app has believes it's running the latest version and a sync will return as up to date, however it's still running the previous version of the code.

Is there an option to force update to the most recent package?

**Comment by hramos** [comment]
Can you provide more details? Ideally, fill out the template when opening a new issue.

**Comment by jbcullis** [comment]
This error has presented itself on several occasions with my users and I've only been able to reproduce it once.
When the update process is interrupted and fails to update the package, it seems that code push has already decided it's got the most current version of the package and therefore subsequent sync calls will fail.

When this happens there are only two ways to fix the issue, you need to reinstall the app entirely or I need to push a new version before it will update.

**Comment by hramos** [comment]
Alright, we really need more detailed reproduction steps in order to keep this open. Can you fill out the template?

**Comment by jbcullis** [comment]
Like I said, I cannot reproduce this on demand. What I'd be interested in is some sort of 'Force Update' option so we have a fallback when this happens.

We have a bit over 3k active users and as far as I'm aware it has only happened a dozen times or so.

**Comment by hramos** [comment]
It's still unclear what specific issue you're reporting. If this is about Code Push, perhaps https://github.com/Microsoft/code-push is a better place to report the issue.

If you're confident this is an issue in React Native core, please open a new issue and make sure to fill out the template in its entirety. Thanks.
