### ISSUE TITLE
Exposing System Date & Time format

### ISSUE THREAD

**Issue by nicinabox** [facebook/react-native#1434]
I'd love to be able to respect the system's time format rather than forcing a localized style. Are there any plans for exposing settings like this to JavaScript?

**Comment by brentvatne** [comment]
Hey there @nicinabox! Probably an issue more with my lack of experience with this than your explanation, but I don't quite follow - could you elaborate with an example?

**Comment by nicinabox** [comment]
Sure, sorry for the lack of detail. 

iOS has settings for 24 hour time. I'd like to be able to reflect that in my UI rather than specifically formatting times 12 hour or 24 hour time.

![img_7330](https://cloud.githubusercontent.com/assets/246280/7869175/abe2c542-0546-11e5-99b9-77220d4f5925.jpg)

(and yes, I'm a 24-hour user)

**Comment by brentvatne** [comment]
Makes sense! ![](http://url.brentvatne.ca/1dzu9.png) - I am too :smile:

Looks like this would do it: [How can I determine if iPhone is set for 12 hour or 24 hour time display? - StackOverflow](http://stackoverflow.com/a/1972487/659988) - it uses the fact that `NSLocale` formats the date according to system preferences to indirectly determine the setting for you. Would you like to try your hand at writing a native module that exposes this?

**Comment by nicinabox** [comment]
Nice. I'd love to be able to do this, but my native-fu is weak.

**Comment by brentvatne** [comment]
@nicinabox - here you go: https://github.com/brentvatne/react-native-device-clock-format

**Comment by nicinabox** [comment]
I was trying it anyway. Turns out I wasn't TOO far off. Thanks @brentvatne, this is really helpful!

**Comment by brentvatne** [comment]
My pleasure :smile:

**Comment by mfkp** [comment]
Hey @brentvatne - thanks for your initial work on this. I think it's a bit of a bigger problem than just exposing 12/24 hour format though.

The date format is the trickier one to get correct, as there are so many different formats in different countries.

I'm wondering if it would be wise to make a native module that could communicate with the NSDateFormatter class, something like this: http://stackoverflow.com/a/5938858/798533

(Using the `[dateFormatter setLocale:[NSLocale currentLocale]];` line will set the date format to the format of the user's device. Thoughts?
