### ISSUE TITLE
v0.45.0+ - VirtualizedList slow performance and rendering

### ISSUE THREAD

**Issue by niftylettuce** [facebook/react-native#14348]
The rendering of VirtualizedList (namely `<SectionList>`) has extremely poor performance.  I will be submitting a PR that seems fixes the issue introduced by this line <https://github.com/facebook/react-native/blame/v0.45.0-rc.3/Libraries/Lists/VirtualizedList.js#L537> per this commit <https://github.com/facebook/react-native/commit/52e50af56d601e63a0c83118c194149d3aed38ea#diff-25477c6bad509193f026645fd928dec6R515>.  There are a few more instances of the change from `this._updateCellsToRenderBatcher.schedule();` to `this._scheduleCellsToRenderUpdate();`.  Therefore I believe that there is more work to be done in order to fully fix this issue.

To reproduce, simply use RN v0.45.x+ and create a `<SectionList>` with a lot of records.  The performance is horrible compared to v0.44.x.  However I need v0.45.x since it brings the scrollTo* methods on `<SectionList>` component.

cc @sahrens

**Comment by niftylettuce** [comment]
So the issue is actually this function:

```js
  _scheduleCellsToRenderUpdate() {
    this._updateCellsToRenderBatcher.schedule();
    return;
    const {first, last} = this.state;
    const {offset, visibleLength, velocity} = this._scrollMetrics;
    const itemCount = this.props.getItemCount(this.props.data);
    let hiPri = false;
    if (first > 0 || last < itemCount - 1) {
      const distTop = offset - this._getFrameMetricsApprox(first).offset;
      const distBottom = this._getFrameMetricsApprox(last).offset - (offset + visibleLength);
      const scrollingThreshold = this.props.onEndReachedThreshold * visibleLength / 2;
      hiPri = (
        Math.min(distTop, distBottom) < 0 ||
        (velocity < -2 && distTop < scrollingThreshold) ||
        (velocity > 2 && distBottom < scrollingThreshold)
      );
    }
    if (hiPri) {
      // Don't worry about interactions when scrolling quickly; focus on filling content as fast
      // as possible.
      this._updateCellsToRenderBatcher.dispose({abort: true});
      this._updateCellsToRender();
      return;
    } else {
      this._updateCellsToRenderBatcher.schedule();
    }
  }
```

**Comment by niftylettuce** [comment]
Specifically on first load, this function has `hiPri` true, which delays the rendering until it finishes iterating over all records.  If we have 1000+ records, it's incredibly slow.

```
    if (hiPri) {
      // Don't worry about interactions when scrolling quickly; focus on filling content as fast
      // as possible.
      this._updateCellsToRenderBatcher.dispose({abort: true});
      this._updateCellsToRender();
      return;
    } else {
      this._updateCellsToRenderBatcher.schedule();
    }
```

**Comment by niftylettuce** [comment]
See <https://github.com/facebook/react-native/pull/14349#issuecomment-307258520>.  I've fixed this and the scrolling is much more performant now.

**Comment by niftylettuce** [comment]
I also switched to use a FlatList.

**Comment by mikelambert** [comment]
Question from the peanut gallery...I'm confused. I thought virtualized list
controlled whether there is an update based on the contents of the
`sections` or `data` field, and whether they had changed. How would the
existence/use of a non pure component cause anything to be re-rendered?
Were you changing your data model for the list during scroll?

2017年6月9日(金) 8:56 niftylettuce <notifications@github.com>:

**Comment by sahrens** [comment]
Yeah, one of the changes from ListView is that we no longer do any special diffing - we rely on the components to do their own diffing with PureComponent or shouldComponentUpdate. It turns out it's just about as fast to render all the cells that are in the finite render window as it is to do all the data diffing manually - the important bit is that the cells not re-render recursively. By making diffing the responsibility of the user-land components, it simplifies the list API by leveraging standard React performance techniques/best practices instead of introducing new concepts.

**Comment by mikelambert** [comment]
Ahh interesting. I was going off this documentation:

> This is a `PureComponent` which means that it will not re-render if props remain shallow- equal. Make sure that everything your renderItem function depends on is passed as a prop (e.g. `extraData`) that is not === after updates, otherwise your UI may not update on changes. This includes the data prop and parent component state.

So I guess resolving these two statements (yours, and docs):
- If your props changes are shallow-equal, the contents of your list won't be updated.
- However, `VirtualizedList` can still do any re-rendering it wants, and often re-renders rows repeatedly out of simplicity. However, it will not pull in the latest props...rather, the render will be based on the last updated props as defined by shallow-equality.
- And so using `PureComponent`s inside the List item renders becomes a very important (perhaps vital?) performance optimization to avoid wasteless renders.

I totally missed that I should be using `PureComponent`s in my List. This is mentioned in passing in `FlatList` docs in their complex example, but is totally omitted in `SectionList` and `VirtualizedList` docs (which is what I had read and was using).

**Comment by sahrens** [comment]
Yes, the list has to re-render itself even ignoring props don't change in order to adjust the window while scrolling. That comment is more about people changing things inside the data array without changing the array object itself, which would remain shallow-equal and not trigger a render of the new data.

Feel free to clarify the docs with a PR :)

**Comment by RodrigoCS** [comment]
This is happening to me, but I do have my renderItem function returning a stateless pureComponent, still the rendering freezes on the first load, some items render (initialNumToRender), then the js freezes and about 3-4 seconds later the whole list renders, If I do as @niftylettuce said [here](https://github.com/facebook/react-native/issues/14348#issuecomment-306636679), the list works as expected, rendering as I scroll.
Is this actually meant to happen?

**Comment by xilonxiao** [comment]
Hello guys! I've just upgraded my react-native from 0.44.2 to 0.45.1 and noticed a huge performance drop on my both flatlists components, specially the one with 2 columns. My list items have fixed height, use the same components but they are dynamic, that is, they are non-stateless components. From what @sahrens commented, it seems that flatlist now relies on developer's implementation of diffing, am I right? Considering that I can not use PureComponent, the most likely solution would be to implement my own shouldComponentUpdate? Thanks!

**Comment by niftylettuce** [comment]
@xilonxiao I'd tried to find a way to use pure component - why can't you?

**Comment by xilonxiao** [comment]
@niftylettuce I actually don't know how to do that. My list item is quite complex, a component composed of other components that have changeable states. As far as I know, PureComponents are stateless, right? I haven't found any example that could help me understand how to correctly implement PureComponents.

**Comment by xilonxiao** [comment]
@niftylettuce I actually tried the first obvious thing, to change my ListItem from Component to PureComponent an got absolutely no improvement on performance. Now I'm trying to figure it out how PureComponent works to make the necessary changes. If you have any example or tutorial, I'd appreciate. Thanks!

**Comment by tjmadsen** [comment]
@xilonxiao Have you managed to figure it out?  I'm having the same issue...

**Comment by xilonxiao** [comment]
@tjmadsen I haven't found a silver bullet solution, but i've made some changes on my FlatList configurations that improved a lot, not 100%, but enough to keep using the new version.
It was a lot of minor changes but there was 2 that I noticed had the most impact:
- To reduce the FlatList prop "windowSize" from 21 to just 5. It brings some disadvantages, but on my case it was worth it. Check the flatlist/virtualized list documentation to see if it applies on your case;
- To set the "maxToRenderPerBatch" to just 2. Almost the same as the change cited above, as each of my items occupies roughly 70% of the screen, loading 2 gives me some space.

The major drawback with these was not being able to do smooth fast scrolling, but in may case the performance boost paid off.

**Comment by tjmadsen** [comment]
@xilonxiao Also, not sure which version of RN you're using, but with 0.47, this fix [https://github.com/facebook/react-native/commit/ebcf5fd24173c2628a5dcc65871fa7a8b219f96e]  made it WAY faster for me (though still not perfect)

**Comment by xilonxiao** [comment]
@tjmadsen I'm using 0.46.4 but it's good to know that 47 has a fix that may solve this problem....I'll check it out. One thing that kept me from updating to 47 is that I read somewhere that it has a breaking bug, but I'm not sure about it.

**Comment by TGPSKI** [comment]
I was running into two problems - extremely slow framerate (sometimes not even loading) when navigating to a large FlatList component, and the same navigating away from the FlatList page.

In addition to the normal steps (use PureComponent, use initialNumToRender), I got improvements by making the following changes to VirtualizedList.js:

componentWillUnmount - add this.setState && this._updateCellsToRenderBatcher.schedule();
```
  componentWillUnmount() {
    this.setState({
      first: this.props.initialScrollIndex || 0,
      last: Math.min(
        this.props.getItemCount(this.props.data),
        (this.props.initialScrollIndex || 0) + this.props.initialNumToRender,
      ) - 1});
    this._updateCellsToRenderBatcher.schedule();
    this._updateViewableItems(null);
    this._updateCellsToRenderBatcher.dispose();
    this._viewabilityHelper.dispose();
    this._fillRateHelper.deactivateAndFlush();
    clearTimeout(this._initialScrollIndexTimeout);
  }
```
componentDidUpdate - use this._updateCellsToRenderBatcher.schedule();
```
componentDidUpdate() {
    this._updateCellsToRenderBatcher.schedule();
  }
```

in _scheduleCellsToRenderUpdate(), replace this._updateCellsToRender() with this._updateCellsToRenderBatcher.schedule(); in the if (hiPri) statement
```
if (hiPri) {
      // Don't worry about interactions when scrolling quickly; focus on filling content as fast
      // as possible.
      this._updateCellsToRenderBatcher.dispose({abort: true});
      this._updateCellsToRenderBatcher.schedule();
```
