### ISSUE TITLE
How to change TabbarIOS icon's  size?

### ISSUE THREAD

**Issue by Anu-Ujin** [facebook/react-native#14340]
```
 <TabBarIOS.Item
          selected={this.state.selectedTab == 'profile'}
          style={styles.icon}
          icon={require("./images/profile.png")}
          renderAsOriginal
          selectedIcon={require("./images/profile1.png")}
          iconImageStyle={{width: 23, height: 23, resizeMode:'contain'}}
          iconSize={20}
          title=''
          onPress={() => {
              this.setState({
                selectedTab: 'profile'
              });
          }}>
           <View style={{flex:1}}>
              <Navigator
                initialRoute={{
                  id: 'Profile',
                }}
                renderScene={
                  this.navigatorRenderScene
                }  
              />
            </View>
          </TabBarIOS.Item>
```

Here is my code and i can't change size of the require image

**Comment by hramos** [comment]
Hey @Anu-Ujin, thanks for reporting this. Unfortunately we need more details to help. For example, what did you expect and what did you get as a result? If you think this is a bug in the project itself, can you make sure to fill out the new issue template that we provide when you create a new issue?

**Comment by hramos** [comment]
In this case, the component being displayed is an actual native UITabBar. Therefore we're limited in terms of how much it can be customized, especially when it comes to the presentation of icons. If you need to present a tabbar that is sufficiently different from the native iOS tab bar, you may want to write a JavaScript component that matches your look instead.

**Comment by jjhesk** [comment]
how to change the icon size?

**Comment by Anu-Ujin** [comment]
@jjhesk i used this

icon={{uri: ProfileIcon, scale: 2}}
and 

var ProfileIcon's image must converted by https://www.base64-image.de/

**Comment by arronhunt** [comment]
I'm having the same issue. The problem I'm encountering is that I'm saving my icons @3x for retina displays, but they get rendered 3x larger than they should on the screen. You can't use `iconSize` when using `require()` to import the PNG. Any workarounds for this?
