### ISSUE TITLE
Xcode 9 Beta Simulator failure

### ISSUE THREAD

**Issue by ugiacoman** [facebook/react-native#14342]
### Description

React-Native doesn't want to launch beta Simulators that come with Xcode 9 Beta

If I run directly from Xcode and not from CLI, I receive the following error: 
`Error returned in reply: Connection invalid`

### Reproduction Steps and Sample Code

1. Install Xcode 9 Beta
2. Run `react-native run-ios`

Error:

> 2017-06-06 10:46:57.395 instruments[38401:2733259] CoreSimulator detected Xcode.app relocation or CoreSimulatorService version change.  Framework path (/Applications/Xcode.app/Contents/Developer/Library/PrivateFrameworks/CoreSimulator.framework) and version (375.21) does not match existing job path (/Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/XPCServices/com.apple.CoreSimulator.CoreSimulatorService.xpc) and version (459.9).  Attempting to remove the stale service in order to add the expected version.
> 2017-06-06 10:46:57.654 instruments[38401:2733389] CoreSimulatorService connection interrupted.  Resubscribing to notifications.
> 2017-06-06 10:46:57.662 instruments[38401:2733463] CoreSimulatorService connection became invalid.  Simulator services will no longer be available.
> 2017-06-06 10:46:57.662 instruments[38401:2733259] Note: simulator support disabled: Failed to initialize simulator device set.
> 2017-06-06 10:46:57.674 instruments[38401:2733306] CoreSimulatorService connection became invalid.  Simulator services will no longer be available.
> 2017-06-06 10:46:57.921 simctl[38427:2733815] CoreSimulatorService connection interrupted.  Resubscribing to notifications.
> Unable to locate device set: Error Domain=NSPOSIXErrorDomain Code=53 "Software caused connection abort" UserInfo={NSLocalizedFailureReason=Failed to subscribe to notifications from CoreSimulatorService., NSLocalizedDescription=Failed to initialize simulator device set., NSUnderlyingError=0x7fac03507120 {Error Domain=NSPOSIXErrorDomain Code=53 "Software caused connection abort" UserInfo={NSLocalizedDescription=Error returned in reply to notification request: Connection interrupted}}}

### Additional Information

* React Native version: 0.44.0 
* React Native CLI version: 2.0.1
* Platform: iOS
* Development Operating System: macOS
* Dev tools: Xcode 9 Beta

**Comment by cprovatas** [comment]
+1

**Comment by cprovatas** [comment]
Opening the simulator manually, then running the project fixed the issue for me.  I think it's a bug w/ Xcode 9 finding the PID and attaching to the simulator

**Comment by cyprusglobe** [comment]
I ended up trying this

```sudo xcode-select -s /Applications/Xcode-beta.app/Contents/Developer ```

which worked

not sure if its the best approach though.

**Comment by mac-cain13** [comment]
When using Xcode command line tools you need to switch to the correct version of the tools with `xcode-select` if you have multiple Xcode versions installed. Since `react-native` calls out to some of the Xcode CLI tools you need to first use `xcode-select` as @cyprusglobe suggests.

If then still you get an error you could have found a bug in the Xcode beta or in React Native, but using another Xcode then is selected on the CLI will not work as expected anyway. This is also a normal step in the native iOS development workflow btw.

**Comment by ikanth** [comment]
Hi,
I am also having same problem.
I am using only one XCode at a time.
My system configuraton:
# XCode 9 beta,
# MacOS 10.12.6.

Any solution for this?
Thank you In advance

**Comment by jnrepo** [comment]
anyone have an issue where they can't access their developer menu?

**Comment by sibelius** [comment]
this is not an issue with react-native itself

it is an issue with xcode

**Comment by ugiacoman** [comment]
Closing issue, it seems that if you are running a beta version of Xcode, react-native get's confused the first time you launch it. Should be fixed now that golden master has come out

**Comment by elnygren** [comment]
Incase you've just updated to XCode9.0 and you get this error: try starting Xcode.app normally. It'll ask you to install some additional stuff and after that everything works.

**Comment by yduman** [comment]
@elnygren thank you! this fixed the issue for me.

**Comment by abstructs** [comment]
Also had this error with X-code 9 beta. I removed the beta version and got X-code 9.

First attempt at running "react-native run-ios" it said to run the same line as @elnygren posted (omitting the "beta").

Fixed my error.

**Comment by abstructs** [comment]
@cyprusglobe and @mac-cain13's answers helped fix the issue for me.
