### ISSUE TITLE
Please support share api on Facebook app (Android)

### ISSUE THREAD

**Issue by weeravit** [facebook/react-native#14353]
My below code didn't work with android because facebook app display empty text

`Share.share({
message: 'Test test test',
url: 'https://facebook.com/',
title: 'React Native'
})`

**Comment by hramos** [comment]
Thanks for opening the issue, however it looks like a feature request. As noted in the [Issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md) we'd like to use the GitHub issues to track bugs only. Can you implement the feature as a standalone npm module? If not consider sending a pull request or a create an entry on [Canny](https://reactnative.canny.io/feature-requests). It has a voting system and if the feature gets upvoted enough it might get implemented by someone from the community. Closing this now, thanks for understanding!

**Comment by gvillenave** [comment]
https://react-native.canny.io/feature-requests/p/share-api-doesnt-populate-the-message-for-facebook
