### ISSUE TITLE
Commas inserted before interpolated text

### ISSUE THREAD

**Issue by esauter5** [facebook/react-native#1435]
When I try something like this:

```js
<Text>Hello, {name}</Text>
```

The output is `Hello, ,Eric`

If I add text after `{name}` like:

```js
<Text>Hello, {name}.</Text>
```
The output is `Hello, ,Eric.,`

Is this unintended and a bug or is it something I should not be trying to do? I double checked some of the docs and that's definitely done in some examples. The alternative is:

```js
<Text>{"Hello, " + {name} + "."}</Text>
```

 That works, but the other way is a little cleaner so it's preferable. I don't remember seeing this introduced until I upgraded to 0.4.4.

**Comment by brentvatne** [comment]
@esauter5 -  [it looks like your first example works as expected](https://rnplay.org/plays/j4DwGw?autoplay=true) - can you reproduce your issue on [rnplay.org](https://rnplay.org) please?

**Comment by esauter5** [comment]
OK, this is my bad. I'm using a thin wrapper around the generic `Text` component and its actually a bug in that wrapper.

I just verified the problem isn't there with the actual React `Text` component. Closing
