### ISSUE TITLE
Link from website tutorial to example apps is broken

### ISSUE THREAD

**Issue by kotAPI** [facebook/react-native#14369]
--- Delete everything above this line ---

### Description

I was reading the [tutorial ](https://facebook.github.io/react-native/docs/more-resources.html#content)and tried to look into some example projects and hit a 404 when I clicked on it.

Currently points to [this](https://github.com/facebook/react-native/tree/master/Examples)

### Solution

The link needs to fixed to the correct repository link of the apps. 

### Additional Information

I'm not sure if this is fixed yet, but the example link seems to be broken.

**Comment by hramos** [comment]
Thanks for the report. This is [already fixed](https://facebook.github.io/react-native/releases/next/docs/more-resources.html#content) in the latest version of the docs, which you can access by clicking on 0.45 at the top. I'll work on getting these fixes backported to 0.45 soon.
