### ISSUE TITLE
[Packager] Presence of problematic module (without even requiring it) causes error (Original: ReferenceError: process is not defined in keyMirror)

### ISSUE THREAD

**Issue by jtremback** [facebook/react-native#1437]
Attempting to run: https://github.com/jtremback/rnTest2

I get this cryptic string of errors:

https://gist.github.com/jtremback/d152ce43f643fb735994

**Comment by jtremback** [comment]
Getting these same errors even with a completely fresh `react-native init`. Is the `react-native-cli` still the recommended way to set up a project? 

The npm module appears to be somewhat old and doesn't link to a repository: https://www.npmjs.com/package/react-native-cli

**Comment by jtremback** [comment]
This was fixed by running `killall node`. I think that there are some deeper issues around the packager misbehaving. Is there a relevant issue for the packager script?

**Comment by jtremback** [comment]
Actually, this still persists in some of my projects. Sorry if this issue is not very helpful, I'm as puzzled as anyone.

**Comment by brentvatne** [comment]
@jtremback - I cloned your project and had the same issue, then I removed Babel and your other dependencies from the project, `rm -rf node_modules && npm i`, and it worked. If you'd like to use Babel, try installing from master.

**Comment by jtremback** [comment]
Turns out, it was actually nuclear-js that was causing the problems.

It appears to me as if adding nuclear-js to a react-native project's node_module breaks react-native.

This is **without** even requiring nuclear-js anywhere. Its very presence in the node_modules folder causes the problem. I've never seen this from another npm-compatible piece of software, and I'm guessing that it will break on other stuff besides nuclear-js.

**Comment by brentvatne** [comment]
@jtremback - weird! cc @amasad

**Comment by brentvatne** [comment]
@jtremback - any chance you want to dig through nuclear-js and find the offending code?

**Comment by jtremback** [comment]
@brentvatne working on it now.

**Comment by jtremback** [comment]
Ok, so the version of `nuclear-js` that is on NPM has an `examples` folder. I wish I could link you to it on here, but its only on NPM.

One of the examples has checked-in `node_modules`. In these `node_modules` is a copy of `React`. Part of the `React` code is `keyMirror`, which has some code (`process.env`) that only will run in node, or webpack etc.

Removing the `node_modules` folder results in an error like "Can't find React". Removing the offending example entirely solves the issue.

`nuclear-js` could definitely clean up what they have on NPM, but at the same time, why is the packager hoovering up stuff that's not even `require`'d?

**Comment by brentvatne** [comment]
Thanks for checking that out @jtremback, @amasad is much more capable of answering that question than I am so I'll leave it to him :smile:

**Comment by jtremback** [comment]
Curious what the requirements are for packaging and serving your own JS? Just a bundle on 8081? I'm sure this issue will be resolved easily, but I'd like to look into bundling the JS myself, at least in a basic way.

**Comment by ide** [comment]
I believe the packager is searching all files (including under node_modules) for `@providesModule` directives. `nuclear-js` is shipping the raw React source with the facebook directives still, so this is tricking the packager.

Two things I recommend: nuclear-js should put examples under .npmignore. This is a super quick fix since you can just fork and then reference your fork from your own package.json.

The other thing I think should be done is for the packager to support a whitelist of directories to scan for `@providesModule` directives. Scanning files under `node_modules` doesn't make sense except in a very few select scenarios since the directives are proprietary to facebook and other npm packages shouldn't be using them. cc @amasad 

@jtremback You can bundle your JS however you want as long as it produces a single file that when executed runs `AppRegistry.registerComponent`. The tricky part will be creating that bundle and you're better off using the packager for that.

**Comment by jtremback** [comment]
What is @providesModule?

**Comment by amasad** [comment]
I have a diff that will land by next diff. It's what we discussed before, @ide. The packager will only scan react-tools and react-native for providesModule, other modules will use node module resolution. As a bonus, node module resolution will be lazy, and should speed up server start up (internally that went from 20s to 15s).

Working on more speed ups and trying to contain Facebook JS infra funkiness to creep out into the open source community.

**Comment by jtremback** [comment]
:+1: Nice!

**Comment by amasad** [comment]
Couldn't get this in by the sync. Shooting for the next one.

**Comment by leoasis** [comment]
@amasad any updates on this one? Could it be possible to be the same problem that's going on in https://github.com/mjohnston/react-native-webpack-server/issues/40?

**Comment by grabbou** [comment]
> I believe the packager is searching all files

@ide, shouldn't it just use what you have in package.json? We know the reality, not everybody cleans up `node_modules` after removing module from package.json...

**Comment by ide** [comment]
@grabbou - you could make an argument for either behavior.  Either way this issue is still a problem in master if any of your npm deps requires `invariant`.

**Comment by amasad** [comment]
This should be fixed. node_modules will not be scaned for "providesModule". If it still happens, please give me repro steps.
