### ISSUE TITLE
[SectionList] Sticky headers do not stick

### ISSUE THREAD

**Issue by JonnyBurger** [facebook/react-native#14375]
### Description

The `SectionList` component does have a prop called `stickySectionHeadersEnabled`. However when I set it to true, the section headers do not seem to stick to the top as the documentation suggests.

### Reproduction Steps and Sample Code

Snack: https://snack.expo.io/rkt7_TrzZ

### Additional Information

* React Native version: 0.45.0
* Platform: both
* Things I've tried: Adding a `stickyHeaderIndices` prop, using `ScrollView` / `View` as a container.

**Comment by nihgwu** [comment]
can you test with RN0.46? several related bug-fix commits have been shipped in this release

**Comment by JonnyBurger** [comment]
Upgrading to `react-native@0.46` alone did not make it work, but in the `RNTester` it seems to work. From that I might be able to pinpoint the exact issue. Will look into this a bit closer as I would like to use the SectionList in my app.

I also tried `AnimatedSectionList` – no dice.

**Comment by kramer9x** [comment]
@JonnyBurger 
Try to use 
<ScrollView contentContainerStyle={styles.container}>
instead of 
<ScrollView style={styles.container}>

**Comment by mikelambert** [comment]
@JonnyBurger I suspect it might be fixed by https://github.com/facebook/react-native/commit/0518a0ba12e7cafc8228be0455403cc23b055a79 , which is part of the 0.46 RCs. Not sure if it's part of `react-native@0.46` as that may be a different thing? (Not sure)

**Comment by danielfeelfine** [comment]
@mikelambert I try with `RN 0.46.2` and it doesn't work.

**Comment by mvanroon** [comment]
I ran into the same issue today and it turned out that my SectionList was inside a ScrollView.
Make sure your SectionList is not a (grand)child of a ScrollView component

**Comment by danielfeelfine** [comment]
Now, it's works for me. @mvanroon @mikelambert

**Comment by mvanroon** [comment]
@danielfeelfine what was the problem?

**Comment by danielfeelfine** [comment]
It seems that my implementation was wrong @mvanroon. If you can post your code I can help you.

**Comment by mvanroon** [comment]
@danielfeelfine I already got it working mate, cheers

**Comment by chenghaohao** [comment]
i have the same issue here when i use 
`<SectionList>
<SectionList />
</SectionList>`
the first section sticky header works, but inside one is not working.
i need a big sticky header and several small group sticky header, so i use sectionList in this way.
any solutions? 3ks.

**Comment by pohy** [comment]
I have the same issue as @chenghaohao, when nesting `<SectionList>`s.

**Comment by danielfeelfine** [comment]
@calirec can you post the code of you are using?

**Comment by MathieuVedana** [comment]
Hello, 
I have an issue with stickyHeader and **nested SectionList** as @calirec.
The nested header section is not sticky.
I have made a sample here : https://snack.expo.io/By2my0VV7
Can you please check if it is a bug or not?
Thank you for your help.

May be nested SectionList and stickyHeader would require a new issue creation...?
