### ISSUE TITLE
"Hello World"app is not working on Android 7.0

### ISSUE THREAD

**Issue by ramosalx1504** [facebook/react-native#14372]
I've initialized a new react-native project and it does not work on Android 7.0, but in all other versions (4xx,5xx,6xx, 7.1.1) works normally on avd's.

adb logcat : 

![captura de pantalla 2017-06-07 a las 12 03 30 p m](https://user-images.githubusercontent.com/12147160/26893721-5ed1f13a-4b79-11e7-8c53-19d86014e968.png)

Note: I have an app in the Google Play store, and it has reported locks on Android 7.0 for a few days, only on Samsung Sxx devices.

![captura de pantalla 2017-06-07 a las 11 55 34 a m](https://user-images.githubusercontent.com/12147160/26893444-9a4562ac-4b78-11e7-9f28-f67b7977f5ec.png)

![captura de pantalla 2017-06-07 a las 11 59 10 a m](https://user-images.githubusercontent.com/12147160/26893651-2971f936-4b79-11e7-8b01-895dc690e3c3.png)

I tried to initialize the project with : 

- "react": "16.0.0-alpha.12"
- "react-native": "0.45.0",
- updated sdk android and avd

**Comment by hramos** [comment]
Can you open a new issue and make sure to fill out the template with plain text?
