### ISSUE TITLE
[Text] Text doesn't wrap 

### ISSUE THREAD

**Issue by bogdantmm92** [facebook/react-native#1438]
http://puu.sh/i407j/805ec722a0.png 
Text doesn't wrap when it's wrapped inside : 
```
msgReceivedAlignContainer: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'flex-w',
  },
```

**Comment by brentvatne** [comment]
@bogdantmm92 - can you post a complete minimal example on [rnplay.org](http://rnplay.org/) please?

**Comment by bogdantmm92** [comment]
Demo: https://rnplay.org/plays/21GRFQ

**Comment by brentvatne** [comment]
@bogdantmm92 - the problem is that it won't wrap because the flexDirection is row. I fixed this for you [here](https://rnplay.org/plays/6h_SzA?autoplay=true)

**Comment by bogdantmm92** [comment]
Thanks for testing & fixing this so fast! Really appreciate it!

**Comment by uc-hus** [comment]
How to break  text of flexDirection: row view
![image](https://cloud.githubusercontent.com/assets/12196308/17253991/9d5597bc-55d0-11e6-996c-8003e54edc36.png)

**Comment by peter4k** [comment]
Try add `flexWrap: "wrap"` to the style of the Text component

**Comment by mvnnn** [comment]
@peter4k That's not works in my case.
```
              <View style={{flexDirection:'row',flexWrap: 'wrap'}}>
              <Text> You miss fdddddd dddddddd You miss fdddddd dddddddd</Text>
              </View>
```

**Comment by peter4k** [comment]
@mvnnn You have to add it to your <Text> component, like:
```
<View style={{flexDirection:'row'}}>
       <Text style={{flexWrap: 'wrap'}}> You miss fdddddd dddddddd You miss fdddddd dddddddd</Text>
</View>
111

**Comment by mvnnn** [comment]
@peter4k thanks, I also try this but that's not working inside ```card``` so i use "minWidth" and "maxWidth" and that's working great.

**Comment by a11y1337** [comment]
Hey there, I was able to get this to work by adding a 'flex: 1' property to the text element.

`<View style={{flexDirection:'row'}}>
       <Text style={{flex: 1, flexWrap: 'wrap'}}> You miss fdddddd dddddddd You miss fdddddd dddddddd</Text>
</View>`

**Comment by janaka120** [comment]
I think this also work

`<View style={{flexDirection:'row', flex: 1, flexWrap: 'wrap'}}> <Text> You miss fdddddd dddddddd You miss fdddddd dddddddd</Text> </View>`

**Comment by dwilt** [comment]
I tried @a11y1337 's method and it didn't work for me. I have a situation where I have text sitting in a `View` along side of another `View` and the text is running through the parent's `padding` and out of the parent's container:

![image](https://cloud.githubusercontent.com/assets/1065539/22799280/1a0feb72-eeba-11e6-8ec6-5749325acaf4.png)

Markup:
```jsx
<View style={styles.container}>
    <AlbumCover
        image={album_cover}
        width={smallAlbumCover}
        height={smallAlbumCover}
        borderRadius={6}
    />
    <View style={styles.info}>
        <Text style={styles.title} allowFontScaling={false}>{title}</Text>
        <Text style={styles.author} allowFontScaling={false}>{author}</Text>
    </View>
</View>
````
Styles:
```javascript
export default StyleSheet.create({
    container: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    info: {
        flexGrow: 1,
        marginLeft: gutter,
    },
    title: {
        fontSize: 16,
        fontFamily: sansSerifLight,
        color: nearlyBlack,
    },
    author: {
        fontSize: 12,
        fontFamily: sansSerif,
        color: greyishBrown,
    }
});
```
As I said, I tried all of the the suggestions here and nothing seemed to work. *WHAT DID WORK* was adding a `width: 0` to the `info` style:

```js
info: {
    width: 0,
    flexGrow: 1,
    marginLeft: gutter,
},
```
and voilà:

![image](https://cloud.githubusercontent.com/assets/1065539/22799269/11ae3808-eeba-11e6-91ff-19a139b559da.png)

**Comment by georgemickael-b** [comment]
@dwilt That helped!

**Comment by highbass** [comment]
@a11y1337 ... that saved me ton of headache! thank you.

**Comment by TWGN** [comment]
thanks a lot, it is great help for me!

**Comment by IrvanWijaya** [comment]
@dwilt thanks for the solution. By the way what does the flexGrow do? I check it https://facebook.github.io/react-native/docs/layout-props.html there and it give me nothing.

thanks

**Comment by dwilt** [comment]
@IrvanWijaya read this [guide](https://css-tricks.com/snippets/css/a-guide-to-flexbox/#article-header-id-10) which is probably implemented the same way on React Native. It

**Comment by vardanmobiloitte** [comment]
Hello All,
  I am using react native 0.28.0. and I am not able to wrap text in chat I am using react-native-gifted-chat . also I get error if I use maxWidth. Do anyone know workaround of maxWidth

**Comment by pavloko** [comment]
Hi all,

[Text supports ](https://facebook.github.io/react-native/docs/text.html#numberoflines)`NumberOfLines` property, not sure about the case described above, but maybe it can be an option.

```
<Text numberOfLines={2}/>
```

**Comment by gusgard** [comment]
@dabit1  thanks!

Example that works:

**Code**
```
<View style={styles.container}>
  <Text style={styles.text}>{text}</Text>
</View>
```

**Styles**
```
export default StyleSheet.create({
  container: {
      flexDirection: 'row',
      alignItems: 'center',
  },
  text: {
    width: 0,
    flexGrow: 1,
    flex: 1,
  }
});
```

**Comment by pie6k** [comment]
For me - none of solutions did work.

After a bit of hard time I've found out that adding `flexShrink: 1` to text container helped.

**Comment by MehdiAlouafi** [comment]
So far @gusgard answer always worked for me but I just faced this issue and despite all of the documented solution no one actually worked except for that one : 

I found this gem https://stackoverflow.com/questions/38233789/react-native-view-auto-width-by-text-inside.  the accepted answer tells us that 👍 

>  "alignSelf" does the same as 'display: inline-block' would in common HTML/CSS and it works very well for me.

I don't know you but I really didn't know. Just tested it and it worked like a charm.

**Comment by yordis** [comment]
@pie6k solution is the best subjectively approach but put it on the `Text` that you want to wrap.

**Comment by benevbright** [comment]
@pie6k You saved my day. Many thanks for your sharing!

**Comment by charleylla** [comment]
this worked for me:
```
<View style={{flexGrow:1,width:0,flexDirection:"column",justifyContent:"center"}}>
    <Text >{handle_description}</Text>
</View>
```

**Comment by nanosoft-vivek** [comment]
![screenshot_1516863404](https://user-images.githubusercontent.com/31314177/35376779-9748a120-01d2-11e8-9781-d067e32eb09c.png)

**Comment by dmeehan1968** [comment]
All of the above solutions didn't work for me, I had a fairly complicated view hierarchy, simpler versions always worked as expected.

Also, I was using ```react-native-web```, so coding to ```react-native``` standards, using ```View``` and ```Text``` components as the basis for all rendering.  The above did allow me to resolve the issue on Native, but it didn't resolve it on Web.

The correct solution (for me) was to ensure that I had ```flex: 1``` on ALL ancestors of the ```Text``` node that was not wrapping as expected.

So - check your view hierarchy, you can do this in the browser using the Element Inspector (Computed Styles), just walk up from the non-wrapping node and check for ```display: flex``` - anything missing ```flex``` is missing the corresponding ```flex: 1```.

NB: ```Text``` nodes in ```react-native-web``` do not pass the ```flex``` property to the underlying ```div```/```span```.

**Comment by MehdiAlouafi** [comment]
@dmeehan1968 your solution solved this problem on one occasion thank you !

There are a lot of solutions to this problem

**Comment by Fi2zz** [comment]
`
 <View style={style.textWrap}>
     <Text numberOfLines={your value} >
         Your very very very very very long text content
     </Text>
</View>

style ={
 textWrap:{ 
     width: your_certain_width
  }
}

`
