### ISSUE TITLE
[0.45.0] checkPropTypes warning on LayoutAnimation.easeInEaseOut()

### ISSUE THREAD

**Issue by allmaxgit** [facebook/react-native#14381]
On call `LayoutAnimation.easeInEaseOut()` in React native 0.45.0 occurs next warning:
```
Warning: checkPropTypes has been moved to a separate package. Accessing React.checkPropTypes is no longer supported and will be removed completely in React 16. Use the prop-types package on npm instead. (https://fb.me/migrating-from-react-proptypes)
```

**Comment by peterp** [comment]
It looks like this [was fixed](https://github.com/facebook/react-native/commit/962e664c33e514729de8a8bd3a7289c8ddb2d5d9). I'm not sure why it's not in this release.

**Comment by hramos** [comment]
If the commit landed 27 days ago, then it should be in the current release candidate (0.46) that was cut this week.

**Comment by chenyi5266** [comment]
if you use LayoutAnimation：
node_modules/react-native/Libraries/LayoutAnimation/LayoutAnimation.js，line 18
	var {PropTypes} = require('prop-types')
	var {checkPropTypes} = PropTypes;
