### ISSUE TITLE
[Packager] Change to any file in node_modules requires restart

### ISSUE THREAD

**Issue by brentvatne** [facebook/react-native#1439]
On `master` after today's sync, any changes to JS inside of node_modules requires a packager restart in order to take effect, and they will not be picked up for auto-reload. In contrast, on `v0.5.0-rc`, auto-reload works and a packager restart is not required.

It is useful sometimes to modify JS inside of node_modules directly for debugging purposes.

**Comment by JohnyDays** [comment]
This used to already be the case for symlinked folders, usually created by npm link facebook/watchman#105

**Comment by tadeuzagallo** [comment]
I added a rule to the packager to ignore node_modules in order to unbreak the test builds on Travis, but I understand that's not ideal, sorry about that.

**Comment by JohnyDays** [comment]
@tadeuzagallo can I get a hint on where this rule is and how I can disable it? I'm currently using master and even changing this manually would speed up my development. Thanks!

**Comment by tadeuzagallo** [comment]
It's set in: https://github.com/facebook/react-native/blob/master/packager/react-packager/src/FileWatcher/index.js#L70, sorry about that, I already know how to fix it, just didn't have the time to do so yet.

**Comment by brentvatne** [comment]
Thanks @tadeuzagallo :smile:

**Comment by JohnyDays** [comment]
Had found with with grep, sorry I didn't update this issue. Glad to know I found the right one though :+1:

**Comment by tadeuzagallo** [comment]
Oops, this has already been fixed.
