### ISSUE TITLE
mixedContentMode has no effect

### ISSUE THREAD

**Issue by Jahans3** [facebook/react-native#14398]
### Description

I added the prop `mixedContentMode='always'` to a WebView but it had no effect. I am using a WebView to host the checkout page for my app, however the styles on that page are not loading and they come from an insecure domain and the checkout is obviously secure.

### Reproduction Steps and Sample Code

1. Create a WebView
2. Add `mixedContentMode='always'` as a pro
3. Load a secure page which uses mixed content
4. Non-secure content is not loaded

Is this a problem with me, or a bug in RN?

### Additional Information

* React Native version: 0.44.2
* Platform: Android
* Development Operating System: macOS Sierra
* Dev tools: 2.3.1

**Comment by hramos** [comment]
Can you provide a reproduction on Snack?

**Comment by keithmichelson** [comment]
I seem to be having that problem as well. Unless I'm implementing it wrong.

`<WebView
          source={{uri: 'http://testsite.com'}}
          style={{marginTop: 20, width: 300}}
          mixedContentMode = 'always'
        />`

**Comment by Mercury-Dai** [comment]
I have same problem,RN version is 0.42.0

**Comment by hramos** [comment]
Closing as author did not respond.

**Comment by sun2rise** [comment]
any solution for this? i have the same problem with RN 0.48.4 on Android
