### ISSUE TITLE
[SectionList] Cannot scroll to top of a SectionList with Header

### ISSUE THREAD

**Issue by mikelambert** [facebook/react-native#14392]
`SectionList.scrollToLocation` internally calls `VirtualizedList.scrollToIndex`. Calling it with `{itemIndex: 0, sectionIndex: 0}` will scroll to the first element, but in the case of a header, will leave the header offscreen.

In writing this up, I discovered an ugly hack workaround that takes advantage of the calculation code: `{itemIndex: 0, sectionIndex: 0, viewPosition: 100}` will scroll to the top of the page (or some sufficiently high number to guarantee the code clamps to 0).

**Comment by jstheoriginal** [comment]
I believe `viewOffset` param is what you should use, with it equal to the height of the header.

**Comment by kelset** [comment]
`viewOffset` worked fine for me.
