### ISSUE TITLE
when run  react-native run-ios,please tell me what should i do?

### ISSUE THREAD

**Issue by Easyzhan** [facebook/react-native#14399]
** BUILD FAILED **

The following commands produced analyzer issues:

	Analyze /Users/vizard/WebstormProjects/AwesomeProject/node_modules/react-native/ReactCommon/yoga/yoga/YGNodeList.c
	Analyze /Users/vizard/WebstormProjects/AwesomeProject/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.c
(2 commands with analyzer issues)

The following build commands failed:
	PhaseScriptExecution Install\ Third\ Party /Users/vizard/WebstormProjects/AwesomeProject/ios/Build/Intermediates/React.build/Debug-iphonesimulator/double-conversion.build/Script-190EE32F1E6A43DE00A8543A.sh
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/AwesomeProject.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/AwesomeProject.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by dgurns** [comment]
How did you solve this? I'm running into the same problem.

**Comment by Easyzhan** [comment]
not yet

**Comment by Nivedita-g** [comment]
Same problem here

**Comment by kumarryogeshh** [comment]
Facing same issue.

The following build commands failed:
	PhaseScriptExecution Install\ Third\ Party ... /ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/double-conversion.build/Script-190EE32F1E6A43DE00A8543A.sh
(1 failure)

**Comment by l3wi** [comment]
Me too. 
Same script as above: double-conversion.build/Script-190EE32F1E6A43DE00A8543A.sh

**Comment by kumarryogeshh** [comment]
Fixed using earlier versions. Try this

react-native init --version="0.42.0" AwesomeProject

**Comment by kingbin** [comment]
The following has fixed the double-conversion errors for me by removing ~/.rncache, cleaning the ios project(Product->Clean), cleaning the build folder(option + Product -> Clean Build Folder...) and kicking off the packager with npm start -- --reset-cache. I believe the problem is in cached files in ~/.rncache.

**Comment by davinderkumar** [comment]
Same issue. 
react-native-cli: 2.0.1
react-native: 0.46.4

Cannot use version lower than 0.45 as getting issue 
[Update RN version to 0.45](https://github.com/Vizzuality/forest-watcher/pull/167)

Tried clearing NPM cache, iOS project clean, but nothing works.

**Comment by Sophia-Gao** [comment]
you should download boost_1_63_0 manually from web and put in react-native/third-party

**Comment by hramos** [comment]
Duplicate of #14423
