### ISSUE TITLE
RTL in picker not supported

### ISSUE THREAD

**Issue by reehamRaed** [facebook/react-native#14396]
Hi , 
can any one help me in making picker and picker item  RTL 
even i use I18nManager every thing was good except picker

**Comment by hramos** [comment]
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Comment by gendeld** [comment]
Please re-open this.

**Comment by alihesari** [comment]
+1
