### ISSUE TITLE
Android StatusBar translucent does not get applied when push notification clicked

### ISSUE THREAD

**Issue by iremlopsum** [facebook/react-native#14407]
### Description

I use OneSignal for push notifications. When app is in the background or focused and I tap on the notification the translucent state does not get applied and content is rendered beneath the StatusBar.

Initially I though that this happens only when application is on the background and app is resumed because of tapping on the application, but it happens as well if the app is already in focus.

I define StatusBar in the root of my project. I tried defining it else where as well (screens that would get rendered upon resuming the app from notification), but the result is the same as before.

Any ideas how I could get translucent to be applied or what is the root of this issue?

### Additional Information

* React Native version: 0.45.0
* Platform: Android
* Development Operating System: Windows

**Comment by vincejah** [comment]
I have exact same issue when an intent belonging to the application is called on an already running application instance (android:launchMode="singleTask")

Additional Information

React Native version: 0.44.3
Platform: Android
Development Operating System: Mac OSX

**Comment by vincejah** [comment]
@iremlopsum in case you are intereseted, I found a workaround. Just before your StatusBar gets rendered, you can call the static method:
```
StatusBar.setTranslucent(true)
StatusBar.setBackgroundColor(Colors.blackTransparent)
```

In my case it solves the problem.

**Comment by iremlopsum** [comment]
@vincejah this fixed it, thanks!
