### ISSUE TITLE
 'boost/iterator/iterator_adaptor.hpp' file not found

### ISSUE THREAD

**Issue by maquanhong** [facebook/react-native#14404]
fatal error: 'boost/iterator/iterator_adaptor.hpp' file not found
#include <boost/iterator/iterator_adaptor.hpp>
         ^
1 error generated.

** BUILD FAILED **

The following build commands failed:
	CompileC /Users/maquanhong/项目/RN/AwesomeProject/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/third-party.build/Objects-normal/x86_64/Bits.o /Users/maquanhong/项目/RN/AwesomeProject/node_modules/react-native/third-party/folly-2016.09.26.00/folly/Bits.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/AwesomeProject.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/AwesomeProject.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

How can I fix the error?

**Comment by adjustit** [comment]
I got around this by manually downloading the Boost 1.63 package (https://sourceforge.net/projects/boost/files/boost/1.63.0/) and installing it into the `third_party/` folder manually. It's not a great fix, but nonetheless, it at least works.

**Comment by srijak** [comment]
I just ran into this after a fresh install of react-native. 

Doesn't seem like it should be closed because the solution is very much a workaround.

**Comment by hramos** [comment]
I closed the issue because there was no effort to fill out the issue template. Please open a new issue and make sure to fill it out.

**Comment by srijak** [comment]
@hramos #14423 :)

**Comment by HaseebYousaf** [comment]
downloaded and replaced boost_1_63_0.tar.gz in the .rncache folder. It seem to fix the problem for me.

**Comment by zssr** [comment]
In my case the `boost_1_63_0.tar.gz` and `double-conversion-1.1.5.tar.gz` in the `~/.rncache` directory went wrong for some reason, not in full solid size( which is `12.3M` & `7M`).  After I copied them from my colleague, things go smooth.

**Comment by hramos** [comment]
Duplicate of #14423
