### ISSUE TITLE
iOS app crashes on launch in xcode

### ISSUE THREAD

**Issue by oliveriobw** [facebook/react-native#14419]
### Description
Crash when app is loading in Xcode. 
Reproducible maybe 50% of the time

### Reproduction Steps and Sample Code

Steps
- Create iOS project
- Define a controller, loaded at launch, with no buttons
- Launch the app 

Result

Crash at this point:

![image](https://user-images.githubusercontent.com/18595960/26978110-217bba64-4d22-11e7-98de-7f04665a6c55.png)

### Solution

```
-(void)setButtons:(NSArray*)buttons viewController:(UIViewController*)viewController side:(NSString*)side animated:(BOOL)animated
{
  NSMutableArray *barButtonItems = [NSMutableArray new];
  
  if([buttons isKindOfClass:[NSNull class]])
    return;  //added
```
### Additional Information

Sorry cannot give more detail.

**Comment by hramos** [comment]
We really need more information here. "Create iOS project" is too vague.

**Comment by hramos** [comment]
Closing this issue as we haven't heard back from the author.
