### ISSUE TITLE
What happened to the old MapView component?

### ISSUE THREAD

**Issue by hsavit1** [facebook/react-native#14426]
I've recently upgraded a project to RN 0.45, and I've had to swap out the deprecated MapView component for the AirBnB MapView component, which is unreliable. The deprecated MapView doesn't exist in the react-native-deprecated-custom-components library. Is it stashed somewhere else?

**Comment by hramos** [comment]
The `react-native-deprecated-custom-components` package is for JavaScript components only. The `MapViewIOS` component requires native code. It was deprecated some time ago, and was finally [removed entirely in 0.44](https://github.com/facebook/react-native/releases/tag/v0.44.3).

The recommendation is to use the Airbnb MapView library, and file any issues you may find directly in their repo.

**Comment by hsavit1** [comment]
@hramos the AirBnB MapView component does not work at all. They take what seems like MONTHS to reply to issues. There's even an issue titled ["Is airbnb still on this project?"](https://github.com/airbnb/react-native-maps/issues/1280)

For that reason i see this solution as pretty unacceptable.  I have no options now.
