### ISSUE TITLE
Require more information in ISSUE_TEMPLATE

### ISSUE THREAD

**Issue by tabrindle** [facebook/react-native#14420]
### Description

Many issues here on GitHub are very difficult to recreate, due to the low amount of context information given - the template as it stands only asks for RN version, Platform, OS + toolchain. Given the number of global dependencies this project has, I believe it may be prudent to ask for more information, especially **node + npm version**, given the major releases recently. 

### Solution

Update the ./github/ISSUE_TEMPLATE.md to include more basic information, and if possible, create a CLI tool similar to `ionic info` where one can type a single command to get all the relevant information. I would be willing to create a PR for both. 

EDIT: [PR](https://github.com/facebook/react-native/pull/14422) added for adding Node/npm - open to adding more while I'm at it.

**Comment by hramos** [comment]
Thanks for sending the PR!

**Comment by tabrindle** [comment]
Looks like we can close this now that it's merged and actively used!
