### ISSUE TITLE
React native packager not running for android

### ISSUE THREAD

**Issue by guru0510** [facebook/react-native#14421]
When I run this command
  react-native run-android
React Native packager seems to be started, but stuck and not working

 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  Running packager on port 8081.                                            │ 
 │                                                                            │ 
 │  Keep this packager running while developing on any JS projects. Feel      │ 
 │  free to close this tab and run your own packager instance if you          │ 
 │  prefer.                                                                   │ 
 │                                                                            │ 
 │  https://github.com/facebook/react-native                                  │ 
 │                                                                            │ 
 └────────────────────────────────────────────────────────────────────────────┘ 
Looking for JS files in
   /Volumes/Dev/react-native/uxa_dev 

[06/09/2017, 21:55:39] <START> Initializing Packager
[06/09/2017, 21:55:40]         HMR Server listening on /hot

React packager ready.

jest-haste-map: Watchman crawl failed. Retrying once with node crawler.
  Usually this happens when watchman isn't running. Create an empty `.watchmanconfig` file in your project's root folder or initialize a git or hg repository in your project.
  Error: Watchman error: fileData.mtime_ms.toNumber is not a function. Make sure watchman is running for this project. See https://facebook.github.io/watchman/docs/troubleshooting.html.
[06/09/2017, 21:56:02] <START> Building Haste Map
[06/09/2017, 21:56:03] <END>   Building Haste Map (1210ms)
[06/09/2017, 21:56:03] <END>   Initializing Packager (23853ms)

How can I get my packager running?

**Comment by hramos** [comment]
Can you please fill out the template?

**Comment by bernharduw** [comment]
I had the same error, it was a file descriptor issue on OS X. I solved it by following these instructions: https://facebook.github.io/watchman/docs/install.html#mac-os-file-descriptor-limits
