### ISSUE TITLE
Is there a way to import jsx file in react native?

### ISSUE THREAD

**Issue by denghejun** [facebook/react-native#14438]
Like this:

`import TestComponent from 'Test.jsx'`

**Comment by renehauck** [comment]
How you export "TestComponent"?

You can do this (based on your component-export):

`import TestComponent from 'Test'` 
or
`import * as TestComponent from 'Test'`
or
`import {TestComponent} from 'Test'`

**Comment by denghejun** [comment]
@renehauck
NO, I mean import a jsx file is not support in react native.

**Comment by renehauck** [comment]
Ah... sorry....maybe [this](https://github.com/airbnb/javascript/issues/982) help

**Comment by RichardLindhout** [comment]
I ended up renaming all files to js with a command and ignore eslint warnings when having jsx in js files.

**Comment by brentvatne** [comment]
no
