### ISSUE TITLE
[Swift] Difference in how NSString and String handle null param when exporting Swift module?

### ISSUE THREAD

**Issue by kevindeleon** [facebook/react-native#1443]
First let me just say I have very little experience with Objective C and Swift.

I've been working on re-creating @jaygarcia's [tutorial](http://moduscreate.com/react_native_custom_components_ios/) using Swift based on the documentation provided on the React Native site and I've run into a bit of an error, but wasn't sure if this was just a problem with Jay's coding, my coding, React Native or a problem with the Objective C bridge between Swift's String type and Objective C's NSString.

based on the React Native documentation I have this in my 'm' file:
```objc
RCT_EXTERN_METHOD(readFile:(NSString *)fileName errorCallback:(RCTResponseSenderBlock *)failureCallback callback:(RCTResponseSenderBlock *)successCallback)
```

And the following method in my swift file:
```objc
  @objc func readFile(fileName: String, errorCallback failureCallback: RCTResponseSenderBlock, callback successCallback: RCTResponseSenderBlock) -> Void {
    
    // String doesn't have a length method in Swift, so we use count here instead.
    if (count(fileName) < 1) {
      // Craft a failure message
      let resultDict = [
        "success": false,
        "errMsg": "No file name"
      ]
      
      // Execute the JavaScript failure callback handler
      failureCallback([resultDict])
      
      return; // Halt execution of this function
    }
    
    // A bunch of other stuff that happens if we have a fileName
  }
```
As you can see, the param fileName has a type of String in the Swift declaration and a type of NSString in the bridge file, and I'm using `count` instead of `length`, as in Jay's tutorial, since String doesn't bridge `length` over from Objective C for some reason.

In Jay's tutorial, `textInputValue` (in index.ios.js) is set to `null` initially and is eventually set to whatever string is entered into the input field. If you click the `Load` button, which calls the `readFile` method from our Swift module, BEFORE entering anything into the field (even just clicking the field fixes the error because it then sets fileName to the state of the textInput, which would be an empty string at that point and not null), the app bombs on Line 524 of the RCTBridge.m file `[invocation invokeWithTarget:_isClassMethod ? [module class] : module];` with the code `Thread 5: EXC_BAD_ACCESS(code = 1, address=0x0)`

The above scenario doesn't happen in Jay's Objective C version, so I changed the type to NSString in my Swift declaration (and changed count to length of course), and the problem no longer exists in mine either.  The other way to fix the bug, if I want to use the Swift String type, is to initially set `textInputValue` to an empty string in `index.ios.js` instead of `null` (which seems to be what it likely should be anyway since that is what the function expects).

So my question is, is this all happening due to a difference between how NSString and Swift's String handle JavaScript `null` values that are being passed across the RCTBridge, or is everything happening as it should, and we shouldn't be passing `null` from JS when Swift/ObjC is expecting a String anyway?

My revised version that has the bug 'fixed' is here:
https://github.com/kevindeleon/react-custom-swift-component

You can recreate the bug by: 
1. Changing `textInputValue` to `null` intially on line 26 of `index.ios.js`
2. Building in Xcode
3. press load or save buttons BEFORE doing anything else.

**Comment by ide** [comment]
Can you try `String?` instead of `String`?

**Comment by kevindeleon** [comment]
@ide Yes, I did try that, but it then bombs on the `count()` call because `fileName` is `nil` -- due to it being passed as `null` initially from `index.ios.js`.

I suppose I could write a more complex `if` statement checking for `nil` before checking for `count()`, but in reality...the Swift function expects a String, and it should get a String (because that param is really not optional...it has to have a fileName to work)...but there are a lot of people who are accustomed to initiating a JS var as `null` and then going onto making it a string (for better or worse) as Jay did in his example. Obviously we should pass what the method expects (which is how I fixed it).

What's confusing is why @jaygarcia's [example](https://github.com/ModusCreateOrg/custom-react-native-components-part1/tree/master/Phase2) using Objective C seems not to balk at all. Maybe it's how the RCTBridge passes the value, or perhaps it's just how Objective C handles the nil value? Again, I'm def not a Swift/Object C ninja.

**Comment by ide** [comment]
You should add the nil check since the Swift function can receive nil. That is, `String?` is the correct type unless you assert in JS that `typeof value === 'string'` before passing it down to Obj-C.

Jay's example works because `NSString *` in Obj-C means the function can take a string or a nil value. To express that it takes only a string you can write `(nonnull NSString *)` but I don't think that will compile in RN right now.

**Comment by kevindeleon** [comment]
Thanks @ide 

Is that the more appropriate way of doing it, rather than setting the state of `textInputValue` to an empty string initially? I guess using `String?` and checking for nil makes things a bit more bulletproof on the back-end?

**Comment by ide** [comment]
Either could work equally well. I think it's really up to your preference because your RN module (the JS and native code together) is a black box since people will use your module through its JS interface. It doesn't affect them whether your JS passes null values to native code that does a `nil` check, or if your JS coerces null to an empty string and ensures that the native code never receives `nil`.

Between the two I'd personally lean slightly towards explicitly checking for `nil` in native because, as you've seen, the default error message is confusing if somehow JS were to pass null to native. Also `NSString *`, which is what RN sees, really means "a string or nil" so `String?` is a more robust choice until RN supports `nonnull NSString *`.

**Comment by kevindeleon** [comment]
Sounds good @ide, and thanks for the explanation.  Going to close this as it seems to be a syntax/convention issue and not so much a problem in React or Swift.
