### ISSUE TITLE
running on device takes ~1 min  to load after it states running on device using xcode and won't even load through CLI

### ISSUE THREAD

**Issue by jasan-s** [facebook/react-native#14439]
`react-native run-ios --device "iPhone" ` does not do anything on device. 
However build and run through Xcode runs the app but after being stuck on launch screen for approx. ~1 min. Additionally in simulator the app launches within 10sec
`react-native run-ios --device "iPhone"  --configuration Release` works as it should. 

I expect it to launch through CLi using the pre-bundle js.  and In Xcode it should NOT take 1 min to load after the build and after its states its running on device. the app which is just empty project created using **react-native init** 

* React Native version: [0.45.1]
* Platform: [ iOS]
* Development Operating System: [macOS]
* Dev tools: [Xcode 8.3.3]

**Comment by hramos** [comment]
It sounds like you're reporting multiple issues. Can you edit your original post and ensure it follows the new issue template? That will help clarify what exactly is being reported. Thanks!

**Comment by hramos** [comment]
Closing this issue as we haven't heard back from the author.
