### ISSUE TITLE
Add PlatformConstants.ServerHost for iOS to support react-devtools on device

### ISSUE THREAD

**Issue by brentvatne** [facebook/react-native#14431]
### Description

As described in [this issue](https://github.com/react-community/create-react-native-app/issues/124#issuecomment-307475949), react-devtools works great for iOS and Android in simulator/emulator, but only works on device on Android. I believe this is because `PlatformConstants.ServerHost` is not implemented on iOS, so it always falls back to attempting to connect to localhost, and therefore from your device the react-devtools are unreachable.

### Reproduction Steps and Sample Code

Try to run react-devtools and connect with an iOS device

### Solution

Add `PlatformConstants.ServerHost` to [RCTPlatform](https://github.com/facebook/react-native/blob/f6754348be617e9e6d79865e24894af0bd027ee0/React/Base/RCTPlatform.m), it should be a string constant that returns the `ip:port` string that points to the packager. With this change in place, react-devtools should work out of the box on device on iOS. 

### Additional Information

* React Native version: 0.45
* Platform: iOS
* Development Operating System: macOS

**Comment by gaearon** [comment]
We’re going to look at this with @javache.

**Comment by javache** [comment]
In some places we use [getDevserverUrl](https://github.com/facebook/react-native/blob/292cc82d0ebc437a6f1cdd2e972b3917b7ee05a4/Libraries/Core/Devtools/getDevServer.js). It sounds like we should merge that with ServerHost, which is only exposed on Android right now.

**Comment by nahuelhds** [comment]
Any news on this? Would be very nice.

**Comment by macrozone** [comment]
See also https://github.com/facebook/react-native/pull/15547 for a different approach.

**Comment by Eyesonly88** [comment]
Is anyone working on this? if not I can pick it up and do it.

**Comment by brentvatne** [comment]
@Eyesonly88 - I don't think so! would love to see a PR for it

**Comment by jhen0409** [comment]
@Eyesonly88 are you already doing this? If NO, I can change #15547 to support `PlatformConstants.ServerHost` for iOS.

I missed this issue. 😢

**Comment by fiznool** [comment]
This or #15547 would be greatly appreciated! I'm teaching a course on React Native and telling students to manually patch the `setupDevtools` function is proving to be difficult.

**Comment by Eyesonly88** [comment]
@jhen0409 sorry, I didn't get around to fixing this issue and stopped working on it.

**Comment by fiznool** [comment]
This should definitely remain open! Without the proposed fixes in this thread, we can't use the remote inspector on an iOS device, which IMHO should absolutely work.

**Comment by geirman** [comment]
@jhen0409 Looks like you have a fix for this figured out. Would you be able to submit a PR to fix this? https://github.com/facebook/react-native/pull/15547/files

**Comment by ploureiro** [comment]
Should remain open. Still not possible to use react native devtools on iOS devices.

**Comment by fiznool** [comment]
This can be closed, it works fine now.
