### ISSUE TITLE
SceneView has a method called shouldComponentUpdate() with React-native-router-flux

### ISSUE THREAD

**Issue by cronos88** [facebook/react-native#14430]
Description:
---------------
In the emulador appear this warning:

Warning: SceneView has a method called shouldComponentUpdate(). shouldComponentUpdate should not be used when extending React.PureComponent. Please extended React.Component if shouldComponentUpdate is used.

Reproducing Bug:
------------------------
1. Create a new project: react-native-cli init test
2. Install react-native-router-flux
3. Implement react-native-router-flux in App.js
4. In a terminal run: npm start
5. In another terminal run: npm run-android

Aditional Information
-----------------------------
React Native Version: 0.45.0
Platform: Android
Development Operating System: Linux
Dev tools: Android Studio, SDK 24

**Comment by hramos** [comment]
Can you provide more details? I think step 3 is a bit vague.

**Comment by cronos88** [comment]
I don't know what additional info do you need. If you say me what info do you need then I put them here.

**Comment by hramos** [comment]
The contents of your App.js would be a good start.

**Comment by neetocode** [comment]
I'm have a same error warning
Using:
```
"react-native": "0.45.1"
"react-native-router-flux": "3.39.2"
```

**Comment by stoffern** [comment]
This problem appears with RN 0.45.0+ and when you use: `shouldComponentUpdate` in a `PureComponent` as described in the  to a

**Comment by 95deepan** [comment]
Solved... After upgrading to the latest version ` (v3.40.1).`

**Comment by stoffern** [comment]
Yet a problem as i have described!

**Comment by EliCDavis** [comment]
Upgrading using `npm install react-native-router-flux@latest --save` worked for me as well

**Comment by stoffern** [comment]
yet again what i wrote..
