### ISSUE TITLE
[MapView] Add callback for MapView annotation tap

### ISSUE THREAD

**Issue by chandu0101** [facebook/react-native#1445]
In my app i want to display bunch of locations on mapview and on each annotation click i want to display alert box with actual address and a button to getdirections.

**Comment by brentvatne** [comment]
Hi @chandu0101 - this type of question is best suited for StackOverflow - if this turns out to be a bug, feel free to create an issue here. Thanks!

**Comment by chandu0101** [comment]
its not a bug , i believe its an enhancement because i don't see any prop that handles this http://facebook.github.io/react-native/docs/mapview.html#content

**Comment by brentvatne** [comment]
@chandu0101 - reopened! any interest in submitting a PR for this?

**Comment by chandu0101** [comment]
thank you for reopen , sorry i have limited skills in javascript and objective-c, i am from scala.js land . Hope some one from community will take care of this ...

**Comment by brentvatne** [comment]
@chandu0101 - it looks like there is an existing PR for this! #1247
