### ISSUE TITLE
Undefined symbols for architecture arm64: linker command failed with exit code 1

### ISSUE THREAD

**Issue by ferologics** [facebook/react-native#14465]
### Description

After updating React Native and related Cocoapods, the project broke.
```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_RCTDevMenuItem", referenced from:
      objc-class-ref in libReact.common.a(RCTJSCExecutor.o)
      objc-class-ref in libReact.common.a(RCTPerfMonitor.o)
  "_OBJC_CLASS_$_RCTPackagerConnection", referenced from:
      objc-class-ref in libReact.common.a(RCTDevSettings.o)
  "_OBJC_CLASS_$_RCTDevLoadingView", referenced from:
      objc-class-ref in libReact.common.a(RCTBatchedBridge.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Reproduction Steps
Have a project with ton of Obj-C, Swift and React Native code, upgrade your React Native with `react-native-git-upgrade`.

### Solution
Tried to clean module cache and derived data unsuccessfully.
Updated to the latest Cocoapods version. Deintegrated -> Installed -> Updated all pods multiple times to make sure I have all in order.

### Additional Information

* React Native version: `0.45.1`
* React version: `16.0.0-alpha.12`
* Platform: `iOS`
* Development Operating System: `macOS`
* Dev tools: `Xcode`

**Comment by ferologics** [comment]
I must have changed the scheme build configuration on auto-generating from `release` to `debug`. The scheme's Pod subspecs didn't include `"DevSupport"`, hence the error. Issue solved and moving on, cheers :))

**Comment by mohammed1955** [comment]
@ferologics
can do put screenshot from your solution ??

**Comment by ferologics** [comment]
change your xcode scheme build configuration to release or make sure that your React "DevSupport" pod subspec is included like so:

```podfile
target :SomeScheme do
    # Your 'node_modules' directory is probably in the root of your project,
    # but if not, adjust the `:path` accordingly
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
        'DevSupport', # to show developer menu, etc.
    ]
end
```
