### ISSUE TITLE
Have any idea to get this special effecte? (Include ScrollView, StickyHeader and ScrollTab)

### ISSUE THREAD

**Issue by camellieeee** [facebook/react-native#14466]
![scrollview10](https://user-images.githubusercontent.com/18331008/27031366-99c86ba2-4fa2-11e7-8d77-5a0fc5dfdd58.gif)

**Comment by tushar-singh** [comment]
You can implement this by listening to [`onScroll`](https://facebook.github.io/react-native/docs/scrollview.html#onscroll) on [`ScrollView`](https://facebook.github.io/react-native/docs/scrollview.html) and use `NativeModules.ScrollViewManager.getContentOffset` to get pixels from top. With that you should be able to calculate when to change header content/style

If you're not interested in implementing that yourself – https://github.com/jaysoo/react-native-parallax-scroll-view
