### ISSUE TITLE
Init app project crash only on android 7.0 when try to launch.

### ISSUE THREAD

**Issue by ramosalx1504** [facebook/react-native#14471]
new react-native **init** project crash **only** on android 7.0 emulator when try to launch.

I'm using

- "react": "16.0.0-alpha.12",
- "react-native": "0.45.1"

## Additional info:

- In the other versions of android it works normally.

- I have applications made with react-native in the Google App Store and are currently blocking only on devices with android 7.0

avd logcat :

ActivityManager: Start proc 4555:com.testandroid7/u0a83 for activity com.testandroid7/.MainActivity
AudioFlinger: mixer(0xf2583f80) throttle end: throttle time(10)
art     : Not late-enabling -Xcheck:jni (already on)
art     : Unexpected CPU variant for X86 using defaults: x86
fb-UnpackingSoSource: locked dso store /data/user/0/com.testandroid7/lib-main
fb-UnpackingSoSource: dso store is up-to-date: /data/user/0/com.testandroid7/lib-main
fb-UnpackingSoSource: releasing dso store lock for /data/user/0/com.testandroid7/lib-main
NetworkSecurityConfig: No Network Security Config specified, using platform default
unknown:React: Packager connection already open, nooping.
SurfaceFlinger: ro.sf.lcd_density must be defined as a build property
        : HostConnection::get() New Host Connection established 0xdbffe040, tid 4576
        : Process pipe failed
OpenGLRenderer: Initialized EGL, version 1.4
OpenGLRenderer: Swap behavior 1
gralloc_ranchu: gralloc_register_buffer(0xddc8bc20): invalid buffer
GraphicBufferMapper: registerBuffer(0xddc8bc20) failed -22 (Invalid argument)
GraphicBuffer: unflatten: registerBuffer failed: Invalid argument (-22)
Surface : dequeueBuffer: IGraphicBufferProducer::requestBuffer failed: -22
EGL_emulation: tid 4576: init(324): error 0x3003 (EGL_BAD_ALLOC)
EGL_emulation: tid 4576: eglCreateWindowSurface(847): error 0x3003 (EGL_BAD_ALLOC)
OpenGLRenderer: Failed to create EGLSurface for window 0xddd58508, eglErr = EGL_BAD_ALLOC
libc    : Fatal signal 6 (SIGABRT), code -6 in tid 4576 (RenderThread)
        : debuggerd: handling request: pid=4555 uid=10083 gid=10083 tid=4576
DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
DEBUG   : Build fingerprint: 'Android/sdk_google_phone_x86_64/generic_x86_64:7.0/NYC/3761695:userdebug/dev-keys'
DEBUG   : Revision: '0'
DEBUG   : ABI: 'x86'
DEBUG   : pid: 4555, tid: 4576, name: RenderThread  >>> com.testandroid7 <<<
DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
DEBUG   : Abort message: 'Failed to create EGLSurface for window 0xddd58508, eglErr = EGL_BAD_ALLOC'
DEBUG   :     eax 00000000  ebx 000011cb  ecx 000011e0  edx 00000006
DEBUG   :     esi cedd8978  edi 00000002
DEBUG   :     xcs 00000023  xds 0000002b  xes 0000002b  xfs 0000006b  xss 0000002b
DEBUG   :     eip ffffe430  ebp 000011e0  esp cedd812c  flags 00000296
DEBUG   : 
DEBUG   : backtrace:
DEBUG   :     #00 pc ffffe430  [vdso:ffffe000] (__kernel_vsyscall+16)
DEBUG   :     #01 pc 0008c4fc  /system/lib/libc.so (tgkill+28)
DEBUG   :     #02 pc 00087a46  /system/lib/libc.so (pthread_kill+70)
DEBUG   :     #03 pc 0002a4c0  /system/lib/libc.so (raise+36)
DEBUG   :     #04 pc 00021a4a  /system/lib/libc.so (abort+92)
DEBUG   :     #05 pc 0000fcb0  /system/lib/libcutils.so (__android_log_assert+208)
DEBUG   :     #06 pc 0002e341  /system/lib/libhwui.so
DEBUG   :     #07 pc 000296ac  /system/lib/libhwui.so
DEBUG   :     #08 pc 00029a27  /system/lib/libhwui.so
DEBUG   :     #09 pc 0002f7d9  /system/lib/libhwui.so
DEBUG   :     #10 pc 00031ce2  /system/lib/libhwui.so
DEBUG   :     #11 pc 0003361d  /system/lib/libhwui.so (_ZN7android10uirenderer12renderthread12RenderThread10threadLoopEv+189)
DEBUG   :     #12 pc 00012085  /system/lib/libutils.so (_ZN7android6Thread11_threadLoopEPv+309)
DEBUG   :     #13 pc 0006ec9b  /system/lib/libandroid_runtime.so (_ZN7android14AndroidRuntime15javaThreadShellEPv+111)
DEBUG   :     #14 pc 00011873  /system/lib/libutils.so (_ZN13thread_data_t10trampolineEPKS_+259)
DEBUG   :     #15 pc 00086cb2  /system/lib/libc.so (_ZL15__pthread_startPv+190)
DEBUG   :     #16 pc 00022ed0  /system/lib/libc.so (__start_thread+25)
DEBUG   :     #17 pc 00020736  /system/lib/libc.so (__bionic_clone+70)
ActivityManager:   Force finishing activity com.testandroid7/.MainActivity
JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 112)
ActivityManager: Exception thrown during pause
ActivityManager: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
ActivityManager: 	at android.os.BinderProxy.transactNative(Native Method)
ActivityManager: 	at android.os.BinderProxy.transact(Binder.java:615)
ActivityManager: 	at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:784)
ActivityManager: 	at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:1128)
ActivityManager: 	at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:3483)
ActivityManager: 	at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:3319)
ActivityManager: 	at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:1842)
ActivityManager: 	at com.android.server.am.AppErrors.handleAppCrashLocked(AppErrors.java:619)
ActivityManager: 	at com.android.server.am.AppErrors.makeAppCrashingLocked(AppErrors.java:481)
ActivityManager: 	at com.android.server.am.AppErrors.crashApplicationInner(AppErrors.java:357)
ActivityManager: 	at com.android.server.am.AppErrors.crashApplication(AppErrors.java:309)
ActivityManager: 	at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:13261)
ActivityManager: 	at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
BootReceiver: Copying /data/tombstones/tombstone_08 to DropBox (SYSTEM_TOMBSTONE)
lowmemorykiller: Error writing /proc/4555/oom_score_adj; errno=22
WindowManager: Failed to capture screenshot of Token{a357d17 ActivityRecord{5051d96 u0 com.testandroid7/.MainActivity t6 f}} appWin=Window{7dc609c u0 Starting com.testandroid7} drawState=4
        : debuggerd: resuming target 4555
JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 56)
GraphicsStats: Buffer count: 3
EGL_emulation: tid 2156: eglSurfaceAttrib(1178): error 0x3009 (EGL_BAD_MATCH)
OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0x706741518e40, error=EGL_BAD_MATCH
InputDispatcher: channel '35a2734 com.testandroid7/com.testandroid7.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
InputDispatcher: channel '35a2734 com.testandroid7/com.testandroid7.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
Zygote  : Process 4555 exited due to signal (6)

**Comment by JobsSteve** [comment]
👍  I have crash problem in Android too. Hope your question will be noted, mine [](https://github.com/facebook/react-native/issues/14467) has been closed.

**Comment by JobsSteve** [comment]
👍 I have crash problem in Android too. Hope your question will be noted, mine has been closed.
https://github.com/facebook/react-native/issues/14467

**Comment by rodriguesbreno** [comment]
@JobsSteve have you tried 46.0-rc.2?

**Comment by ramosalx1504** [comment]
It seems that somebody already fixed it, I updated the android emulators, I made a new compilation and now it works.
