### ISSUE TITLE
Why Webview only work when it's the root element? is this expected behavior?

### ISSUE THREAD

**Issue by 1c7** [facebook/react-native#14472]
package.json
```
{
	"name": "haha",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"start": "node node_modules/react-native/local-cli/cli.js start",
		"test": "jest"
	},
	"dependencies": {
		"react": "16.0.0-alpha.6",
		"react-native": "0.44.3"
	},
	"devDependencies": {
		"babel-jest": "20.0.3",
		"babel-preset-react-native": "1.9.2",
		"jest": "20.0.4",
		"react-test-renderer": "16.0.0-alpha.6"
	},
	"jest": {
		"preset": "react-native"
	}
}
```
## it's root: working

![image](https://user-images.githubusercontent.com/1804755/27042723-6a3509c2-4fca-11e7-8663-f4b5b6f0cb95.png)

## it's nested: not working
![image](https://user-images.githubusercontent.com/1804755/27042783-959c5f16-4fca-11e7-99fd-7cb137be7013.png)

# Env
![image](https://user-images.githubusercontent.com/1804755/27042864-d0d38fa0-4fca-11e7-92ca-13239d010c82.png)
System: macOS

Why?

**Comment by Dani93380** [comment]
Remove inside styles container 
justifitContent &  alignItems

**Comment by 1c7** [comment]
@Dani93380 Thank you for reply!

**Comment by Adamnator92** [comment]
@1c7  i believe u can find your answer in #4773

**Comment by 1c7** [comment]
@Adamnator92  
Thank you very much!
I would close this issue now.
I only did a quick scan to the issue link you provide.
Thanks Again!

**Comment by Kwon11** [comment]
For anyone else who searches

https://github.com/facebook/react-native/issues/4773

CTRL+F "JayGarcia", he gives a great explanation of how WebView works and why it seems it only works as a "root" component.

TL:DR, WebView with {flex:1} will scale to its container, but that container needs a height if you are in scrollView. In other cases it should work as expected.
