### ISSUE TITLE
Object.assign enumerable key 0.45.0

### ISSUE THREAD

**Issue by RWOverdijk** [facebook/react-native#14480]
### Description

> One of the sources for assign has an enumerable key on the prototype chain. Are you trying to assign a prototype property? We don't allow it, as this is an edge case that we do not support. This error is a performance optimization and not spec compliant.

```
Object.assign
    Object.es6.js:57:16
<unknown>
    ReactNativeReconcileTransaction.js:124:2
```

I updated to 0.45.0 and tried 0.45.1, too, using the `react-native-git-upgrade` command, upon running I encounter the above in the app. I tracked it down to it trying to assign this function:

```js
function ReactNativeReconcileTransaction() {
  this.reinitializeTransaction();
  this.reactMountReady = CallbackQueue.getPooled(null);
}
```

to key `$asyncbind`

I don't know what any of this means to be honest.

### Reproduction Steps and Sample Code

It seems to be coming from within react native itself. I can't find any code related to the issue.

### Solution

Not sure. I wasn't able to find the actual problem, just the location of the error.

### Additional Information

* React Native version: 0.45.1
* Platform: iOS
* Development Operating System: MacOS
* Dev tools: xcode

### Note

You'll probably close this because I didn't add an example, but I wanted this documented more thoroughly in case someone else finds the problem. Then, if someone ever finds the cause it can be attached here.

**Comment by mwarger** [comment]
I'm getting the same thing, same place, on Android on Windows 10 with react@16.0.0-alpha.12

**Comment by skellock** [comment]
If you're using [apisauce](https://github.com/skellock/apisauce), then try updating to `0.14`.  I was using [fast-async](https://github.com/MatAtBread/fast-async) to compile `async/await` code.  I've since switched to TypeScript which works well without the 1337 hax.  [Boring Details](https://github.com/skellock/apisauce/issues/108).  

Hopefully that was your issue and you can close this one.

**Comment by RWOverdijk** [comment]
@skellock This does indeed solve it. Funny thing, is that it was only when combining RN 0.45.1 with apisauce. 0.14.0 works.

**Comment by manjeets12** [comment]
@skellock  you are a saviour this time.
