### ISSUE TITLE
Oppo mobile keyboard blocked cannot display！！

### ISSUE THREAD

**Issue by ZHT131** [facebook/react-native#14489]
Keyboard congestion problem on OPPO mobile phone!
Such as:
There are now two containing Textinput page on the first page, click the Textinput pop-up keyboard after retracting the keyboard, and then click Textinput to jump second page pop-up keyboard, when I press the standby button open again after clicking the Textinput and bring up the keyboard, so the keyboard was blocked, have encountered similar problems?

react-native:0.44
react-navigation:1.0.0-beta.9

**Comment by hramos** [comment]
0.45.1 is the latest stable version. Can you try using that instead?
