### ISSUE TITLE
LayoutAnimation using PropTypes from React

### ISSUE THREAD

**Issue by CJStroud** [facebook/react-native#14482]
### Description

Using `KeyboardAvoidingView` in an new project causes a warning to be thrown:

`Warning: checkPropTypes has been moved to a separate package. Accessing React.checkPropTypes is no longer supported and will be removed completely in React 16.`

### Solution

Use the `prop-types` package for PropTypes inside `LayoutAnimation`.

This seems to have been fixed on Master a month ago, but isn't in the latest release?

**Comment by hramos** [comment]
You can check whether a commit is in a given release by looking at the tags. If it isn't in 0.45, it may be in the next release, 0.46.0-rc.

**Comment by emiliano-carrillo** [comment]
Is there a solution yet?

**Comment by crisppY** [comment]
+1

**Comment by hramos** [comment]
@emiliano-carrillo @crisppY this is already fixed in master

**Comment by CJStroud** [comment]
@emiliano-carrillo @hramos It looks like it will be in the 0.46.0 release

**Comment by manaka02** [comment]
I have same problem XD !!

**Comment by nonameolsson** [comment]
I get the same warning message!

**Comment by sreenivasanac** [comment]
I get the same message! What should I do

**Comment by hramos** [comment]
This is already fixed in 0.46.
