### ISSUE TITLE
issue when execute 'react-native run-ios'

### ISSUE THREAD

**Issue by liulongdev** [facebook/react-native#14485]
Environment : 

node v8.1.0
react-native-cli: 2.0.1
react-native: 0.44.3
xcode 8.3.3
OSX 10.12.5

react-native init AwesomeProject
cd AwesomeProject
react-native run-ios

terminal display：
.
.
.
curl: Saved to filename 'double-conversion-1.1.5.tar.gz'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                 Dload  Upload   Total   Spent    Left  Speed

100   609    0   609    0     0    602      0 --:--:--  0:00:01 --:--:--   602

curl: (7) Failed to connect to github-production-release-asset-2e65be.s3.amazonaws.com port 443: Connection refused

** BUILD FAILED **

The following build commands failed:

	PhaseScriptExecution Install\ Third\ Party /Users/fanghongliang/Documents/AwesomeProject/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/double-conversion.build/Script-190EE32F1E6A43DE00A8543A.sh
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/AwesomeProject.app
No devices are booted.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/AwesomeProject.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by hramos** [comment]
0.45.1 is the latest stable version. Can you try using that instead?

**Comment by wxb2939** [comment]
i have same question!

**Comment by GitterYang** [comment]
I used 0.45.1 and Xcode 8.3.3, it also show this issue, How can I resolve this problem?

**Comment by hramos** [comment]
Duplicate of #14423
