### ISSUE TITLE
Building for android "Could not resolve all dependencies for configuration ':app:_debugApk'"

### ISSUE THREAD

**Issue by owenauch** [facebook/react-native#14498]
### Description
I recently started working on an existing React Native app implemented only in ios, and started the task of trying to build and develop it on Android as well. I followed all the instructions on the React Native docs, but keep getting this error and can't figure out why:

    A problem occurred configuring project ':app'.
    > Could not resolve all dependencies for configuration ':app:_debugApk'.
       > Configuration with name 'default' not found.

Based on research, I'm assuming that it has to be something with my settings.gradle file, but I can't figure out what. This is what that file looks like:

    include ':react-native-firebase-analytics'
    project(':react-native-firebase-analytics').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-firebase-analytics/android')
    include ':tipsi-stripe'
    project(':tipsi-stripe').projectDir = new File(rootProject.projectDir, '../node_modules/tipsi-stripe/android')
    include ':react-native-sentry'
    project(':react-native-sentry').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-sentry/android')
    include ':react-native-webview-bridge'
    project(':react-native-webview-bridge').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-webview-bridge/android')
    include ':react-native-vector-icons'
    project(':react-native-vector-icons').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-vector-icons/android')
    include ':react-native-device-info'
    project(':react-native-device-info').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-device-info/android')
    include ':react-native-config'
    project(':react-native-config').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-config/android')
    
    include ':ReactAndroid'
    
    project(':ReactAndroid').projectDir = new File(
        rootProject.projectDir, '../node_modules/react-native/ReactAndroid')
    
    include ':app'

Does anyone know why this is happening and how to solve it? Thanks!

### Reproduction Steps and Sample Code

`react-native run-android`

### Solution

Why won't this build?

### Additional Information

* React Native version: 0.42.0
* Platform: both
* Development Operating System: MacOS

**Comment by LaPoPvLe** [comment]
try `cd android && ./gradlew assembleDebug --info` will show the build progress detail.
hope it help u.
refer:  [React-native debug apk](https://stackoverflow.com/questions/37454913/react-native-debug-apk)

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.

**Comment by doraeminemon** [comment]
I tried `yarn install` again and it works !

**Comment by Awekbing** [comment]
@doraeminemon   thanks  for it works!!!

**Comment by rajsatish4ar** [comment]
"react-native upgrade" solved my problem.

**Comment by HashiramaTwT** [comment]
@LaPoPvLe Thank you so much

**Comment by ReactDeveloperTwoQsoft** [comment]
check your package.json file how many packages is adding into "dependencies" : {}, seem lost new dependencies you're just add. Because of some reason like syntax install or settings 👍

**Comment by NguyenPhatBG** [comment]
check your package.json file how many packages is adding into "dependencies" : {}, seem lost new dependencies you're just add. Because of some reason like syntax install or settings 👍
