### ISSUE TITLE
Webview cannot load a file from remote URI

### ISSUE THREAD

**Issue by opolyo01** [facebook/react-native#14499]
### Description

I have a service that returns a binary file (xls/pdf/html) back to user.  I tested in the browser by hitting service URL directly, and it works fine.  It also works fine on iOS if I have startInLoadingState set to false.   It never works on Android with or without flag.

### Reproduction Steps and Sample Code
Load a webview that points to remote uri that needs Authentication.

Expected result -- view loaded with a file content

Actual result -- blank screen

  ***An example of your code or a repro using Snack is REQUIRED***

```
<WebView
          source={{
            uri,
            headers: {"Authorization": `Bearer ${token}`},
            token: `${token}`,
          }}
          startInLoadingState={true}
          scalesPageToFit={false}
        />
```

### Additional Information

* React Native version: 0.44
* Platform: ios/Android
* Development Operating System: Mac
* Dev tools: Genymotion/Xcode

**Comment by hramos** [comment]
Can you reproduce this using Snack?

**Comment by Ilyaololo** [comment]
I have some problem on React Native version 0.42.0 on Android platform. But If use:
`
<WebView url="http://url" />
`, it work and page is loading.

**Comment by hramos** [comment]
Closing this issue as we haven't heard back from the author.

**Comment by esutton** [comment]
@opolyo01  @Ilyaololo did you solve this?

I have same problem.  Android only.  Using: **RN 0.53.3**

Copying the URL opens fine on a desktop or on native Android browser.

In a **WebView** it results in blank screen?

````
https://acme.com.io/user?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZC
TmpkRlFqRTBPRFl5TkVJeVEwUkJPRUZFT1VFNE4wWXpNZyJ9.eyRwczovL2F1dGguc3Vic2l
....
HV9Pcyya_g8xq_VmLKvFx4JF7EqeKXXOQbGx5iDJohQkQJ0O85C0HF3LtvBvf9xBHSpMhtZ
gWQVsXhMfqNX1gmg23dwzbGroPz4k_EQ057GKTajVwwnWDXpgz6JAVTuFQ6S9Dg1ZQEtw
````

````
  render() {
    return (
      <WebView
        source={{ uri: this.props.uri }}
        style={{ marginTop: 0 }}
        scalesPageToFit
        onError={() => {
          this.trackLoadTime(-1);
          }}
        onLoadEnd={() => this.onLoadEnd(0)}
      />
    );
  }
````
Using:
````
		"react": "^16.2.0",
		"react-native": "^0.53.3",
````

**Comment by hramos** [comment]
Please open a new issue.
