### ISSUE TITLE
Support for reparenting

### ISSUE THREAD

**Issue by rikuayanokozy** [facebook/react-native#14508]
React native can move nodes without re-creating it when there placed in the same tree, like `<View>{node1}{node2}</View>`.
But if we have to re-parenting nodes, that will cause re-creating. For example, we want to move node1 into the Modal, node1 will be re-creating.
```
<View>
  {node1}
  {node2}
  <Modal></Modal>
</View>
```
The states of node1 will be purge as the old node1. In most cases it's not a big problem, we can maintain states in the root view, and pass it as props to subnodes, but we offload some expensive view or task into native ui component, it's a problem. For example:
```
<View>
  {fullscreen ? <Modal>{player}</Modal> : (
    <View>
      {player}
      <Text>{video.title}</Text>
    </View>
  )}
</View>
```

**Comment by rikuayanokozy** [comment]
We solved the problem by create a wrapper for the native component.
```
let uid = 0;
class VideoPage extends React.Component {
  _uid = uid++;
  render() {
    const player = <Player {...this.playerProps} reuseToken={this._uid};
    return (
      <View>
       {fullscreen ? <Modal>{player}</Modal> : player}
      </View>
    )
  }
}
```
ViewManager.m:
```
- (UIView)view {
  return [Wrapper new];
}
RCT_EXPORT_METHOD(destroy:(nonnull NSNumber*)reactTag) {
  [self.bridge.uiManager addUIBlock:^(RCTUIManager* manager, NSDictionary* registry) {
    WrappedPlayer* view = registry[reactTag];
    if ([view isKindOfClass:[WrappedPlayer class]]) {
      [view destory];
    }
  }];
}
RCT_EXPORT_PROPERTY(reuseToken, NSNumber *);
```
PlayerWrapper.m:
```
static NSDictionary<WrappedPlayer *> * players;
- (void) setReuseToken:(nonnull NSNumber *) token {
  _reuseToken = token;
  _player = players[token];
  if (player == nil) {
    _player = [WrappedPlayer new];
    players[reuseToken] = _player;
    [self initPlayer];
  }
}
- (void)destory {
  if (_player) {
    [players deleteObject:_reuseToken];
    [_player destory];
  }
}
```
But it would be better to have some help from react native core.

**Comment by hramos** [comment]
Thanks for opening the issue, however it looks like a feature request. As noted in the [Issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md) we'd like to use the GitHub issues to track bugs only. Can you implement the feature as a standalone npm module? If not consider sending a pull request or a create an entry on [Canny](https://reactnative.canny.io/feature-requests). It has a voting system and if the feature gets upvoted enough it might get implemented by someone from the community. Closing this now, thanks for understanding!
