### ISSUE TITLE
Android - SyntaxError: \u can only be followed by a Unicode character sequence

### ISSUE THREAD

**Issue by sattaman** [facebook/react-native#14510]
* React Native version: 0.45.1
* Platform: Android
* Development Operating System: macOS / Windows
* Dev tools: Android Studio 2.3.3

My app is running on iOS fine , but on android I am getting 

SyntaxError: \u can only be followed by a Unicode character sequence

![](https://i.stack.imgur.com/MeFAI.png)

My full logs: https://pastebin.com/by6uCmPW

I've also created a SO question here: https://stackoverflow.com/questions/44542041/react-native-app-not-building-for-android-syntaxerror-u-can-only-be-followed

Update : The error is being thrown by the code here

![](https://d2ppvlu71ri8gs.cloudfront.net/items/1a3Q271r2A0B1P243U3r/%5B91250d671ac26b52ee2a36b50dde270a%5D_Screen%2520Shot%25202017-06-14%2520at%252013.37.21.png?v=f805e5f0)

Which is the following code from the React Native repo (for YellowBox)

https://github.com/facebook/react-native/blob/a974c140db605ecbdf8d3faa7a079b7e2dcebb09/Libraries/ReactNative/YellowBox.js#L263

**Comment by hramos** [comment]
Closing as it's already posted to SO. If you believe this is an issue in React Native, feel free to open a new issue, making sure to fill out the entire issue template.
