### ISSUE TITLE
ScrollView fires "onLayout" and "onContentSizeChange" all the time

### ISSUE THREAD

**Issue by MSSPL-PiyaleeMaiti** [facebook/react-native#14513]
### Description

I add onLayout and onContentSizeChange two prop in ScrollView to get content size and viewHeight so that I can scroll to bottom properly in my section.

I want to stop calling onLayout and onContentSizeChange fires continuously, and also want to stop rerendering if any values haven't changed.

The scroll is working fine, but onLayout and onContentSizeChange fires continuously, even if the values haven't changed. 

### Reproduction Steps and Sample Code
I add below screen shot code: 
![screenshot from 2017-06-14 18 04 51](https://user-images.githubusercontent.com/20696057/27132426-84430bda-512c-11e7-8adc-663e3ea941ec.png)
![screenshot from 2017-06-14 18 05 02](https://user-images.githubusercontent.com/20696057/27132462-9f65ca9c-512c-11e7-889e-27a6ab764443.png)

Now the console log in which shows onLayout funbction call continuously.
![screenshot from 2017-06-14 18 06 53](https://user-images.githubusercontent.com/20696057/27132506-c423e0ee-512c-11e7-9512-7c8484b8819d.png)

### Solution
  I need to stop calling all time onLayout function in scrollview if any values not changed.
 
### Additional Information

* React Native version: [0.40]
* Platform: [both]
* Development Operating System: [ macOS, Linux]

**Comment by radko93** [comment]
Please check on latest react native version, this one is very old.

**Comment by hramos** [comment]
0.45.1 is the latest stable. If this is reproducible in 0.45.1, please open a new issue and make sure to follow the template.

**Comment by MSSPL-PiyaleeMaiti** [comment]
I can't use new react native version for now because of many library support. We will do it later task may be after few months. Please tell us for now that can we fix this issue in this current version or not.

**Comment by radko93** [comment]
@MSSPL-PiyaleeMaiti create a new empty project a try if you can reproduce this issue on new RN version, you don't your whole app to do this.

**Comment by MSSPL-PiyaleeMaiti** [comment]
@radko93   It may fix bug it's a live version and we need a quick fix. We know as it may surely fix the issue after using the new version. So can you provide some quick solution for now. 
As we are focusing to new version upgradation later.

**Comment by prasanthyejje** [comment]
@MSSPL-PiyaleeMaiti  i want to find the scroll down action and hit the services to get some data to display,(like in whats app, while scrolling down i have to display the previous messages ) and my code is 

render() {
        return (
 <ScrollView  ref='scrollView'         
        onContentSizeChange={(w, h) => this.contentHeight = h}
        onLayout={ev => this.scrollViewHeight = ev.nativeEvent.layout.height} >                        
                {this.renderList()}
                    </ScrollView>
   )}

 scrollToBottom(animated = true) // i am calling this method from  componentDidUpdate()
    {
      const scrollHeight = this.contentHeight - this.scrollViewHeight;
      if (scrollHeight > 0) {
        const scrollResponder = this.refs.scrollView.getScrollResponder();
        scrollResponder.scrollResponderScrollTo({x: 0, scrollHeight, animated});
      }
    }

My Issues is : I am not able to listen the ScrollDown action  
Please help me to solve this..
