### ISSUE TITLE
[FlatList] Flatlist BUG

### ISSUE THREAD

**Issue by fangkyi02** [facebook/react-native#14517]
RN：0.44
**data structure** :

![image](https://user-images.githubusercontent.com/3389652/27141235-4fc3e6f8-515a-11e7-9a0a-66bfaa8269d3.png)

**control interface** :

![image](https://user-images.githubusercontent.com/3389652/27142329-4767951a-515d-11e7-86f6-cb97d2f518b7.png)

**Interface effect** :

![image](https://user-images.githubusercontent.com/3389652/27142670-4ef713a4-515e-11e7-9464-82a1d1ef1935.png)

**Implementation code** :

![image](https://user-images.githubusercontent.com/3389652/27142699-681f8cda-515e-11e7-9326-f5b29178a4bb.png)

![image](https://user-images.githubusercontent.com/3389652/27142834-e913907a-515e-11e7-87ea-7f8f8b970003.png)

This is the case now
I render the items I want to delete in the interface, and then click the delete button to delete them
The implemented code is on top
Now is I using key to delete object data for this and will be copied to the flatlist bound data there but after doing so that flatlist directly display the white screen of the original data without but did not trigger a new renderItem even if the forceUpdate is not any effect

**Comment by hramos** [comment]
Hey, thanks for providing samples of your code. May I ask that you post them in plain text? Even better, if you can reproduce this using [Snack](https://snack.expo.io) that would be very helpful.

**Comment by hramos** [comment]
Also, can you edit the title to describe the actual bug you're encountering?

**Comment by hramos** [comment]
Closing this issue as we haven't heard back from the author.
