### ISSUE TITLE
[Packager] How to configure Babel?

### ISSUE THREAD

**Issue by jtremback** [facebook/react-native#1451]
My code is using async/await. How can I configure the Babel instance in the packager?

**Comment by jtremback** [comment]
I could work on a PR for this. Does a react-native config section in package.json sound good to people?

**Comment by jtremback** [comment]
How about having the packager look for a `.babelrc`, or in `package.json` like the standalone Babel does? It could fall back to the existing settings if one is not found.

**Comment by brentvatne** [comment]
I believe I see that being mentioned elsewhere but can't seem to find it cc @ide

**Comment by jtremback** [comment]
Is there any `react-native` specific reason not to use any of the experimental transforms?

**Comment by ide** [comment]
@brentvatne were you thinking about this? https://twitter.com/amasad/status/604057791859445760

**Comment by brentvatne** [comment]
@ide that's the one :) thanks

**Comment by jtremback** [comment]
Modifying the config object in `packager/transformer.js` doesn't seem to change the settings. Maybe this is an error on my part.

**Comment by johanneslumpe** [comment]
So how should we read the `.babelrc` file? `babel-core` already provides a tool to read and parse the file, but unfortunately it's not exposed. And since react-native requires `babel` but not `babel-core` directly, it might be very ugly to do a nested require into `babel/node_modules/babel-core`.

But copying the file does not seem like the right solution. Would be nice to figure out a way to get a hold of that function so we could just require it. Thoughts?

**Comment by jtremback** [comment]
We could skip parsing the `.babelrc` for now and just get our stuff from `package.json`.

**Comment by ide** [comment]
@johanneslumpe would things be easier if RN depended on babel-core directly?

**Comment by jtremback** [comment]
https://github.com/facebook/react-native/pull/1469

**Comment by johanneslumpe** [comment]
@ide i believe so, but now we have @jtremback's PR.

**Comment by sebmck** [comment]
I can expose that method if you want.

**Comment by sebmck** [comment]
Actually, as long as [this](https://github.com/facebook/react-native/blob/41859e594d0dbd0be43cf7cc1561051ac4b1b853/packager/transformer.js#L20) variable is an absolute path then the `.babelrc` files will be resolved and merged into the input options.

**Comment by jtremback** [comment]
So, `filename` is used for error messages, and to find `.babelrc`?

**Comment by sebmck** [comment]
Yep.

**Comment by jtremback** [comment]
Here are my findings:

The packager will load `.babelrc`, IF `resetCache` is true: https://github.com/jtremback/rnTest3/blob/master/node_modules/react-native/packager/packager.js#L206

I found this out by putting a syntax error in `.babelrc`. However, it will apparently not merge the `whitelist`. Adding and removing transforms has no effect

I'm going to try spoon-feeding the packager a package concatenated by browserify.

IMO, react-native should eliminate the packager entirely and just split out those parts of it concerned with debugging and serving the bundle.

**Comment by amasad** [comment]
Yeah, you need to reset the cache when changing anything about the compiler. Any ideas of how we can incorporate .babelrc in the cache hash?
https://github.com/facebook/react-native/blob/master/packager/react-packager/src/JSTransformer/Cache.js#L160-L170

**Comment by amasad** [comment]
Also should we mention `.babelrc` in the docs?

**Comment by amasad** [comment]
@sebmck do you have any ideas on how to override the whitelist via babelrc?

**Comment by sebmck** [comment]
@amasad Babel actually has it's own cache [here](https://github.com/babel/babel/blob/master/src/babel/tools/resolve-rc.js#L6-7) for performance. So changes to `.babelrc` wont be reflect without a complete restart. There's currently no way to override specific options. The current `.babelrc` behaviour is pretty weird, it merges all parent configs which is kinda nasty. Hoping to make it more inline with other config files in the future with an `extends` property instead of doing the word directory inheritance stuff.

**Comment by dozoisch** [comment]
:+1:  That would be awesome

**Comment by schickling** [comment]
+1

**Comment by cgarvis** [comment]
:+1:

**Comment by amasad** [comment]
cc @martinbigio (maybe we can find a way to make this easier as we're redesigning the transformer API)

**Comment by es6Test** [comment]
Just trying my 1st RN app and when I run npm start I get the error:

```/Users/foo/PhpstormProjects/react-native/packager/transformer.js:13
const babel = require('babel-core');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
```

**Comment by es6Test** [comment]
Ignore, nvm forgot to use 4.1.2

**Comment by tenorok** [comment]
Hello, guys!
Sorry, but I not understood how can I extend Babel config?
For example, I need [class properties transform](http://babeljs.io/docs/plugins/transform-class-properties/).
Can you explain please?

**Comment by skoch-fixeads** [comment]
@tenorok You need create your .babelrc and add this babel-presenter: babel-preset-react-native
 https://github.com/facebook/react-native/tree/master/babel-preset
