### ISSUE TITLE
[SectionList] SectionList's sticky header dose not work well with 'inverted' option

### ISSUE THREAD

**Issue by freeljt** [facebook/react-native#14520]
### Description

When rendering SectionList with 'inverted' option and renderSectionHeader, the sticky header is upside down and sticky to the bottom. (in our App, we want them sticky at top even) 

### Reproduction Steps

Render SectionList with inverted option and section header. 

#### Sample Code

            <SectionList style={styles.messageList}
                         **inverted**
                         sections={this.getSectionData()}
                         renderSectionHeader={renderSectionHeader}
                         onEndReached={this.props.loadEarlierMsgs}
                         keyExtractor={rowKey}
                         renderItem={this.renderRow} />

#### Solution

Maybe apply the transform scale -1 to header component and make the section header sticky to the top as well?

### Additional Information

* React Native version: downloaded from master branch on June 14th, 2017
* Platform: iOS
* Development Operating System: maxOS
* Build tools: Xcode

**Comment by kholiavko-roman** [comment]
@freeljt, I trying to use `SectionList` with `'inverted={true}'`, but SectionLIst rendered as default.
Here is my code:
```
 <SectionList
          renderItem={this.renderItem}
          inverted={true}
          stickySectionHeadersEnabled={true}
          keyExtractor={(item, index) => `message_${index}`}
/>
```
It is right, in you case inverted Section list scrolled in different direction ?

**Comment by compojoom** [comment]
@kholiavko-roman - are you on RN 0.47? It seems that inverted on sectionlist was added there. I was on 0.46 and was wondering what the inverted property is supposed to do as I wasn't seeing any difference.

@freeljt - have you found a solution already? I think that nobody tested this with sectionlist as it's implemented in the VirtualizedList. It doesn't make much sense having the Seactionheader at the bottom, but this is a consequence of the transform that is applied on the whole view

**Comment by dralletje** [comment]
I am having the same problem. Sticky headers are not implemented in VirtualizedList either, they are implemented in ScrollView, but even there they work pretty much alone:

https://github.com/facebook/react-native/blob/master/Libraries/Components/ScrollView/ScrollViewStickyHeader.js

I guess the best way to support everything we need, it making allowing for "sticky footers". Then `inverted` on VirtualizedList could "just" swap `stickyHeaderIndices` and `stickyFooterIndices`.
I also could imagine some people actually needing stickyFooters sometimes.

I wondered "But do we want stickyXXX for everything?!" but figured that there are really only two sides tangent to the scroll direction 🤷‍♀️

I'll try to make `stickyFooterIndices` based on how `stickyHeaderIndices` is implemented sometime soon!

**Comment by terrysahaidak** [comment]
Anybody has any solution for that?

**Comment by terrysahaidak** [comment]
Hi there. I think this issue definitely should be open because there is no way in SectionList to use some different scroll view component like ListView does. Since ListView is deprecated and SectionList still has some laggy features, each of them should be fixed. Or ListView support should be continued.

**Comment by diegolmello** [comment]
I'm having the same problem as you can see on Unread header below.

![screen shot 2017-12-21 at 13 47 05](https://user-images.githubusercontent.com/804994/34263294-15729cf6-e656-11e7-9d59-cb3071272c9a.png)

**Comment by vascogaspar** [comment]
any progress on this?

**Comment by Bessonov** [comment]
I think `inverted` is a workaround for a really common requirement: to build chat-like apps. You don't believe me? Look at any virtualized-list-component for react, react-native and angularjs. This requirement exists for every component. Unfortunately, I can't find any suitable solution, except workarounds with flaws.

The idea to reverse the list is quite cool, but well, that's not really fix the issue with adding elements to top without junks, because it leads to add-to-bottom issue.

I understand, that "virtual-both-directions-scrollable-list-with-dynamic-rows-height-and-you-can-go-to-desired-item" requirement is quite complex. But I can't believe that this is impossible.

For our angularjs-based app we've implemented own solution which works, but it's to specific to our internals.

It would be a killer feature for react/react-native or angular, if one of them supports chat-like virtualized lists.

**Comment by stijnvanderlaan** [comment]
Would love this feature.

**Comment by Bessonov** [comment]
Hey, stale bot, leave it open :)

**Comment by terrysahaidak** [comment]
Stale bot, leave it open as it still exists.

**Comment by mo22** [comment]
`
<FlatList inverted={true} invertStickyHeaders={true} ... />
`

**Comment by terrysahaidak** [comment]
@mo22 Well, you're right, it forces them to stick at the top, but still, they don't work well:
![kapture 2019-02-20 at 11 28 05](https://user-images.githubusercontent.com/7809008/53081025-a8389d00-3502-11e9-8b21-db17b111f9de.gif)

**Comment by terrysahaidak** [comment]
This hasn't been fixed yet.

**Comment by Bessonov** [comment]
Activity!

**Comment by ydv0121** [comment]
+1

**Comment by iamolegga** [comment]
Yes, it does still require the community's attention

**Comment by terrysahaidak** [comment]
Seems like it's almost fixed in 0.62.

The only minor problem is it seems like there is unnecessary section separator next to the `ListFooterComponent`.

![image](https://user-images.githubusercontent.com/7809008/79487367-cfb0ca00-8020-11ea-87e9-ecbf3a4ef62f.png)

**Comment by irfaan** [comment]
> Seems like it's almost fixed in 0.62.
> 
> The only minor problem is it seems like there is unnecessary section separator next to the `ListFooterComponent`.
> 
> ![image](https://user-images.githubusercontent.com/7809008/79487367-cfb0ca00-8020-11ea-87e9-ecbf3a4ef62f.png)

Nice. How does this look with a short (less than height of viewport) list?

**Comment by Bessonov** [comment]
further activity occurs

**Comment by gustperz** [comment]
`inverted` and` invertStickyHeaders` work correctly when scrolling, but the first items are not rendered as expected when they are low on items

<img src="https://user-images.githubusercontent.com/9136712/99157729-a0873780-2699-11eb-9fbf-cc7f1d228526.png" width="300" />

for this, the header is still represented below the items

this is how it looks when scrolling
<img src="https://user-images.githubusercontent.com/9136712/99157828-8437ca80-269a-11eb-8110-6d73aeac6976.png" width="300" />

**Comment by dmarselus** [comment]
use renderSectionFooter instead
thank me later bois

**Comment by adidoes** [comment]
can footers be made sticky instead of the headers?

**Comment by iamolegga** [comment]
Reopen please

**Comment by deniska69** [comment]
2024.07.30 - the problem is still relevant.
`<FlatList
inverted={true}
stickyHeaderIndices={[0]}
ListHeaderComponent={<StickyHeader />} />`
scrol! not sticky!
