### ISSUE TITLE
Provide --android --ios flags to react-native link

### ISSUE THREAD

**Issue by jjzazuet** [facebook/react-native#14529]
Hi. I've battling a lot when upgrading native library dependencies between iOS and Android on each major RN release. The most hassle free way I've found to manage these is:

- For iOS: Use Cocoapods, since `react-native link` produces non-compiling projects most of the time.
- For Android: `react-native link` works flawlessly most of the time.

So, any flag options to direct `react-native link` towards one platform or the other (i.e. not both at the same time) would be highly desirable. 

Thanks for your time and help!

**Comment by hramos** [comment]
Thanks for opening the issue, however it looks like a feature request. As noted in the [Issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md) we'd like to use the GitHub issues to track bugs only. Can you implement the feature as a standalone npm module? If not consider sending a pull request or a create an entry on [Canny](https://reactnative.canny.io/feature-requests). It has a voting system and if the feature gets upvoted enough it might get implemented by someone from the community. Closing this now, thanks for understanding!

**Comment by jjzazuet** [comment]
Ok, will do. Thanks.
