### ISSUE TITLE
[Android] AppState 'inactive' not triggered on Android

### ISSUE THREAD

**Issue by duhseekoh** [facebook/react-native#14537]
### Description

 When listening to an AppState change, `inactive` is never triggered on Android, only `background`.

### Reproduction Steps

1. Setup a `change` listener on AppState.
2. Output the current app state in the listener function.
3. Send the app to the background (go to home screen) and notice `background` is logged, but never `inactive`

#### Sample Code

```
componentDidMount() {
  AppState.addEventListener('change', this._handleAppStateChange);
}

_handleAppStateChange(currentAppState) {
  console.log(currentAppState); // never outputs 'inactive' on android
}
```

### Additional Information

* React Native version: 0.43.3
* Platform: Android
* Development Operating System: macOS
* Testing on: Android Simulator with a Nexus 5 with Nougat

**Comment by Geor23** [comment]
+1 RN0.44.0

**Comment by Memerto** [comment]
+1

**Comment by gsavchenko** [comment]
+1

**Comment by ragamufin** [comment]
+1

**Comment by sijangurung** [comment]
+1 RN 0.42.0

**Comment by JLWalsh** [comment]
+1. The inactive state is not sent when receiving a phone call aswell.

**Comment by martin-rueegg** [comment]
@JLWalsh, according to https://stackoverflow.com/a/41009169/3102305, there seems to be an `inactive` (`onPause`) event/state.

Hope that helps.

Our issue is, that we want to re-render the main component for privacy reasons as the screenshot of the app that is used in the task list should only show a "covered" version, not the apps last screen.

**Comment by martin-rueegg** [comment]
just for reference: [[AppState] App state never becomes "inactive"](https://github.com/facebook/react-native/issues/524)

**Comment by martin-rueegg** [comment]
I'm not aware that the issue is solved. It would be required to take action when the app goes into background, e.g. covering the app's screen for privacy reasons, so that the system's screenshot in the app-switch does not show the content of the app, but it's lock screen.

**Comment by felixus95** [comment]
Did you find a solution for the described case? @martin-rueegg ?

We need it for the same scenario. Rendering a view before the Snapshot for Task Switcher is made (Android). On iOS it works just fine.

**Comment by YKSing** [comment]
I also discover that when detecting NFC, it will also trigger `background` and then `active`.

**Comment by alexlevy0** [comment]
This issue should NOT be close, RN 0.56 still have the bug, inactive is not triggered on app close on Android

**Comment by alexlevy0** [comment]
+1
