### ISSUE TITLE
Touchable* cannot touchable inside a absolute View

### ISSUE THREAD

**Issue by jp928** [facebook/react-native#14536]
### Description
TouchableOpacity/TouchableNativeFeedback not working if its parent view has position absolute.
If I do following in 0.45.1, the _onPress function would not be called.

#### Sample Code

```javascript
<View style={{position: 'absolute'}}>
  <TouchableOpacity onPress={this._onPress.bind(this)}>
     <Text>Press Me</Text>
  </TouchableOpacity>
</View>
```

### Additional Information

* React Native version: 0.45.1
* Platform: Android
* Development Operating System: Mac OSX with Android 6.0 device

**Comment by afilp** [comment]
@jp928 I have the same problem. Any ideas if this is fixed?

**Comment by tavonkelly** [comment]
Experiencing the same issue

**Comment by raimens** [comment]
more the same
