### ISSUE TITLE
FlatList not scrollable in absolute View.

### ISSUE THREAD

**Issue by Symous** [facebook/react-native#14549]
When we put a FlatList inside a view which position is absolute,the FlatList can not scroll.
```js
<View style={{position:'absolute'}}>
   <FlatList .... />
</View>
```

**Comment by dann1609** [comment]
Why this was closed?

**Comment by dann1609** [comment]
You need to change the render item from <View> to <TouchableOpacity> or any other touchable. I think is a focus problem.

**Comment by cltsang** [comment]
Is there any solution to this?
