### ISSUE TITLE
Unable to resolve module error

### ISSUE THREAD

**Issue by courtneybeames** [facebook/react-native#14541]
Everytime I try to run my app on the simulator, I get this error:

Unable to resolve module "..." from "/Users/../../node_modules/react-native/Libraries/react-native/react-native-implementation.js': Module does not exist in the module map or in these directories: /Users/.../Desktop/../node_modules/react-native/node_modules, /Users/../Desktop/../node_modules

When I clear watchman, delete the node modules folder, npm install, and reset packager cache, the app works for approximately 5 minutes and then I run into another error with resolving a module. Each time, the module changes. I cannot figure out what would be causing this, especially because the module changes everytime. It also seems to work on my coworkers computer.

Thanks

My package.json is:
{
  "name": "Veemo",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "native-base": "^2.1.5",
    "react": "16.0.0-alpha.12",
    "react-native": "0.45.1",
    "react-native-check-box": "^1.0.4",
    "react-native-datepicker": "^1.6.0",
    "react-native-deprecated-custom-components": "^0.1.0",
    "react-native-geocoding": "^0.2.0",
    "react-native-maps": "^0.15.2",
    "react-native-modal": "^2.4.0",
    "react-native-modalbox": "^1.3.9",
    "react-native-phone-call": "^1.0.2",
    "react-native-root-toast": "^1.1.2",
    "react-native-scrollable-tab-view": "^0.6.6"
  },
  "devDependencies": {
    "babel-jest": "20.0.3",
    "babel-preset-react-native": "1.9.2",
    "jest": "20.0.4",
    "react-test-renderer": "16.0.0-alpha.12"
  },
  "jest": {
    "preset": "react-native"
  }
}

### Additional Information

* React Native version: 0.45.1
* Platform: iOS
* Development Operating System: macOS
* Build tools: Xcode version 8.3.3

**Comment by bcitdaltond** [comment]
**Questions:**

1. Have you recently deleted a package/library/dependency?
2. Is the missing module "..." a added package/library/dependency or something to React-Native or iOS itself?
3. Have you tested this on a actual device? Does it result in the same error?
4. Do you have "Remote Debug Mode" on?

**What I can think of off the bat:**

- Issue: https://github.com/facebook/react-native/issues/7686
- Look through your coworkers XCode settings.   
Some places to check:
- - General > Linked Frameworks and Libraries
- - Build Settings
- - Build Phases

**Note:** If you just started working with react-native, this happens a lot ;)
