### ISSUE TITLE
React Native project init error (windows)

### ISSUE THREAD

**Issue by xkrumeng** [facebook/react-native#14546]
when i run the command: **react-native init AwesomeProject** , then show me those info below:

npm WARN react-native@0.45.1 requires a peer of react@16.0.0-alpha.12 but none was installed.
{ Error: Command failed: npm install --save --save-exact react-native
    at checkExecSyncError (child_process.js:481:13)
    at execSync (child_process.js:521:13)
    at run (C:\Users\Administrator\AppData\Roaming\npm\node_modules\react-native-cli\index.js:294:5)
    at createProject (C:\Users\Administrator\AppData\Roaming\npm\node_modules\react-native-cli\index.js:249:3)
    at init (C:\Users\Administrator\AppData\Roaming\npm\node_modules\react-native-cli\index.js:200:5)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\react-native-cli\index.js:153:7)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
  error: null,
  cmd: 'npm install --save --save-exact react-native',
  file: 'C:\\Windows\\system32\\cmd.exe',
  args:
   [ 'C:\\Windows\\system32\\cmd.exe',
     '/s',
     '/c',
     '"npm install --save --save-exact react-native"' ],
  options:
   { stdio: [ [Object], [Object], [Object] ],
     shell: true,
     windowsVerbatimArguments: true,
     file: 'C:\\Windows\\system32\\cmd.exe',
     args:
      [ 'C:\\Windows\\system32\\cmd.exe',
        '/s',
        '/c',
        '"npm install --save --save-exact react-native"' ],
     envPairs:
      [ 'aliases=E:\\cmder\\config\\user-aliases.cmd',
        'ALLUSERSPROFILE=C:\\ProgramData',
        'ANDROID_HOME=F:\\Android\\sdk',
        'ANSICON=157x1000 (157x47)',
        'ANSICON_DEF=7',
        'APPDATA=C:\\Users\\Administrator\\AppData\\Roaming',
        'architecture=64',
        'ChocolateyInstall=C:\\ProgramData\\chocolatey',
        'ChocolateyLastPathUpdate=Thu May 11 14:51:08 2017',
        'ChocolateyToolsLocation=C:\\tools',
        'CLASSPATH=D:\\Java\\jdk1.8.0_131\\lib\\dt.jar;D:\\Java\\jdk1.8.0_131\\lib\\tools.jar',
        'CMDER_ROOT=E:\\cmder',
        'CommonProgramFiles=C:\\Program Files\\Common Files',
        'CommonProgramFiles(x86)=C:\\Program Files (x86)\\Common Files',
        'CommonProgramW6432=C:\\Program Files\\Common Files',
        'COMPUTERNAME=WIN-20140317SFJ',
        'ComSpec=C:\\Windows\\system32\\cmd.exe',
        'ConEmuANSI=ON',
        'ConEmuAnsiLog=',
        'ConEmuArgs=/Icon "E:\\cmder\\icons\\cmder.ico" /Title Cmder',
        'ConEmuArgs2=',
        'ConEmuBackHWND=0x01BC04FC',
        'ConEmuBaseDir=E:\\cmder\\vendor\\conemu-maximus5\\ConEmu',
        'ConEmuBuild=161022',
        'ConEmuConfig=',
        'ConEmuDir=E:\\cmder\\vendor\\conemu-maximus5',
        'ConEmuDrawHWND=0x000603C2',
        'ConEmuDrive=E:',
        'ConEmuHooks=Enabled',
        'ConEmuHWND=0x000903B4',
        'ConEmuIsAdmin=ADMIN',
        'ConEmuPalette=Monokai',
        'ConEmuPID=26128',
        'ConEmuServerPID=24392',
        'ConEmuTask={cmd::Cmder}',
        'ConEmuWorkDir=C:\\Users\\Administrator',
        'ConEmuWorkDrive=C:',
        'DEVMGR_SHOW_DETAILS=1',
        'FLUTTER_ROOT=H:\\flutter',
        'FP_NO_HOST_CHECK=NO',
        'GIT_INSTALL_ROOT=C:\\Program Files\\Git',
        'GOPATH=I:\\workspace\\react-demos\\sound-redux',
        'HOME=C:\\Users\\Administrator',
        'HOMEDRIVE=C:',
        'HOMEPATH=\\Users\\Administrator',
        'JAVA_HOME=D:\\Java\\jdk1.8.0_131',
        'LOCALAPPDATA=C:\\Users\\Administrator\\AppData\\Local',
        'LOGONSERVER=\\\\WIN-20140317SFJ',
        'MOZ_PLUGIN_PATH=C:\\Program Files (x86)\\Foxit Software\\Foxit Reader Plus\\plugins\\',
        'NUMBER_OF_PROCESSORS=4',
        'OS=Windows_NT',
        'Path=E:\\cmder\\bin;E:\\cmder\\vendor\\conemu-maximus5\\ConEmu\\Scripts;E:\\cmder\\vendor\\conemu-maximus5;E:\\cmder\\vendor\\conemu-maximus5\\ConEmu;C:\\Ruby23-x64\\bin;C:\\Program Files (x86)\\Common Files\\NetSarang;C:\\Python27\\Lib\\site-packages;C:\\Python27;C:\\Python27\\Scripts;C:\\Windows\\system32;C:\\Windows;C:\\Program Files\\TortoiseSVN\\bin;C:\\Program Files\\TortoiseGit\\bin;C:\\ProgramData\\chocolatey\\bin;F:\\Android\\sdk\\tools;F:\\Android\\sdk\\platform-tools;C:\\Program Files\\Git\\cmd;C:\\Program Files\\MongoDB\\Server\\3.4\\bin;D:\\Java\\jdk1.8.0_131\\bin;D:\\Java\\jdk1.8.0_131\\jre\\bin;D:\\nodejs\\;C:\\Users\\Administrator\\AppData\\Local\\atom\\bin;C:\\Python27;C:\\Python27\\Scripts;D:\\tools\\dart-sdk\\bin;C:\\Users\\Administrator\\AppData\\Roaming\\npm;C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\Git\\usr\\share\\vim\\vim74;E:\\cmder\\',
        'PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JSE;.WSF;.WSH;.MSC;.RB;.RBW',
        'PLINK_PROTOCOL=ssh',
        'PROCESSOR_ARCHITECTURE=AMD64',
        'PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 58 Stepping 9, GenuineIntel',
        'PROCESSOR_LEVEL=6',
        'PROCESSOR_REVISION=3a09',
        'ProgramData=C:\\ProgramData',
        'ProgramFiles=C:\\Program Files',
        'ProgramFiles(x86)=C:\\Program Files (x86)',
        'ProgramW6432=C:\\Program Files',
        'PROMPT=C\bL\bI\bN\bK\b \b$P$G',
        'PSModulePath=C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules\\',
        'PUBLIC=C:\\Users\\Public',
        'SCALA_HOME=D:\\Program Files (x86)\\scala',
        'SESSIONNAME=Console',
        'SVN_SSH=C:\\\\Program Files\\\\Git\\\\bin\\\\ssh.exe',
        'SystemDrive=C:',
        'SystemRoot=C:\\Windows',
        'TEMP=C:\\Users\\ADMINI~1\\AppData\\Local\\Temp',
        'TERM=cygwin',
        'TMP=C:\\Users\\ADMINI~1\\AppData\\Local\\Temp',
        'user-aliases=E:\\cmder\\config\\user-aliases.cmd',
        'USERDOMAIN=WIN-20140317SFJ',
        'USERNAME=Administrator',
        'USERPROFILE=C:\\Users\\Administrator',
        'verbose-output=0 ',
        'VS140COMNTOOLS=D:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\Tools\\',
        'windir=C:\\Windows',
        'windows_tracing_flags=3',
        'windows_tracing_logfile=C:\\BVTBin\\Tests\\installpackage\\csilogfile.log' ] },
  envPairs:
   [ 'aliases=E:\\cmder\\config\\user-aliases.cmd',
     'ALLUSERSPROFILE=C:\\ProgramData',
     'ANDROID_HOME=F:\\Android\\sdk',
     'ANSICON=157x1000 (157x47)',
     'ANSICON_DEF=7',
     'APPDATA=C:\\Users\\Administrator\\AppData\\Roaming',
     'architecture=64',
     'ChocolateyInstall=C:\\ProgramData\\chocolatey',
     'ChocolateyLastPathUpdate=Thu May 11 14:51:08 2017',
     'ChocolateyToolsLocation=C:\\tools',
     'CLASSPATH=D:\\Java\\jdk1.8.0_131\\lib\\dt.jar;D:\\Java\\jdk1.8.0_131\\lib\\tools.jar',
     'CMDER_ROOT=E:\\cmder',
     'CommonProgramFiles=C:\\Program Files\\Common Files',
     'CommonProgramFiles(x86)=C:\\Program Files (x86)\\Common Files',
     'CommonProgramW6432=C:\\Program Files\\Common Files',
     'COMPUTERNAME=WIN-20140317SFJ',
     'ComSpec=C:\\Windows\\system32\\cmd.exe',
     'ConEmuANSI=ON',
     'ConEmuAnsiLog=',
     'ConEmuArgs=/Icon "E:\\cmder\\icons\\cmder.ico" /Title Cmder',
     'ConEmuArgs2=',
     'ConEmuBackHWND=0x01BC04FC',
     'ConEmuBaseDir=E:\\cmder\\vendor\\conemu-maximus5\\ConEmu',
     'ConEmuBuild=161022',
     'ConEmuConfig=',
     'ConEmuDir=E:\\cmder\\vendor\\conemu-maximus5',
     'ConEmuDrawHWND=0x000603C2',
     'ConEmuDrive=E:',
     'ConEmuHooks=Enabled',
     'ConEmuHWND=0x000903B4',
     'ConEmuIsAdmin=ADMIN',
     'ConEmuPalette=Monokai',
     'ConEmuPID=26128',
     'ConEmuServerPID=24392',
     'ConEmuTask={cmd::Cmder}',
     'ConEmuWorkDir=C:\\Users\\Administrator',
     'ConEmuWorkDrive=C:',
     'DEVMGR_SHOW_DETAILS=1',
     'FLUTTER_ROOT=H:\\flutter',
     'FP_NO_HOST_CHECK=NO',
     'GIT_INSTALL_ROOT=C:\\Program Files\\Git',
     'GOPATH=I:\\workspace\\react-demos\\sound-redux',
     'HOME=C:\\Users\\Administrator',
     'HOMEDRIVE=C:',
     'HOMEPATH=\\Users\\Administrator',
     'JAVA_HOME=D:\\Java\\jdk1.8.0_131',
     'LOCALAPPDATA=C:\\Users\\Administrator\\AppData\\Local',
     'LOGONSERVER=\\\\WIN-20140317SFJ',
     'MOZ_PLUGIN_PATH=C:\\Program Files (x86)\\Foxit Software\\Foxit Reader Plus\\plugins\\',
     'NUMBER_OF_PROCESSORS=4',
     'OS=Windows_NT',
     'Path=E:\\cmder\\bin;E:\\cmder\\vendor\\conemu-maximus5\\ConEmu\\Scripts;E:\\cmder\\vendor\\conemu-maximus5;E:\\cmder\\vendor\\conemu-maximus5\\ConEmu;C:\\Ruby23-x64\\bin;C:\\Program Files (x86)\\Common Files\\NetSarang;C:\\Python27\\Lib\\site-packages;C:\\Python27;C:\\Python27\\Scripts;C:\\Windows\\system32;C:\\Windows;C:\\Program Files\\TortoiseSVN\\bin;C:\\Program Files\\TortoiseGit\\bin;C:\\ProgramData\\chocolatey\\bin;F:\\Android\\sdk\\tools;F:\\Android\\sdk\\platform-tools;C:\\Program Files\\Git\\cmd;C:\\Program Files\\MongoDB\\Server\\3.4\\bin;D:\\Java\\jdk1.8.0_131\\bin;D:\\Java\\jdk1.8.0_131\\jre\\bin;D:\\nodejs\\;C:\\Users\\Administrator\\AppData\\Local\\atom\\bin;C:\\Python27;C:\\Python27\\Scripts;D:\\tools\\dart-sdk\\bin;C:\\Users\\Administrator\\AppData\\Roaming\\npm;C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\Git\\usr\\share\\vim\\vim74;E:\\cmder\\',
     'PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JSE;.WSF;.WSH;.MSC;.RB;.RBW',
     'PLINK_PROTOCOL=ssh',
     'PROCESSOR_ARCHITECTURE=AMD64',
     'PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 58 Stepping 9, GenuineIntel',
     'PROCESSOR_LEVEL=6',
     'PROCESSOR_REVISION=3a09',
     'ProgramData=C:\\ProgramData',
     'ProgramFiles=C:\\Program Files',
     'ProgramFiles(x86)=C:\\Program Files (x86)',
     'ProgramW6432=C:\\Program Files',
     'PROMPT=C\bL\bI\bN\bK\b \b$P$G',
     'PSModulePath=C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules\\',
     'PUBLIC=C:\\Users\\Public',
     'SCALA_HOME=D:\\Program Files (x86)\\scala',
     'SESSIONNAME=Console',
     'SVN_SSH=C:\\\\Program Files\\\\Git\\\\bin\\\\ssh.exe',
     'SystemDrive=C:',
     'SystemRoot=C:\\Windows',
     'TEMP=C:\\Users\\ADMINI~1\\AppData\\Local\\Temp',
     'TERM=cygwin',
     'TMP=C:\\Users\\ADMINI~1\\AppData\\Local\\Temp',
     'user-aliases=E:\\cmder\\config\\user-aliases.cmd',
     'USERDOMAIN=WIN-20140317SFJ',
     'USERNAME=Administrator',
     'USERPROFILE=C:\\Users\\Administrator',
     'verbose-output=0 ',
     'VS140COMNTOOLS=D:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\Tools\\',
     'windir=C:\\Windows',
     'windows_tracing_flags=3',
     'windows_tracing_logfile=C:\\BVTBin\\Tests\\installpackage\\csilogfile.log' ],
  stderr: null,
  stdout: null,
  pid: 25972,
  output: [ null, null, null ],
  signal: null,
  status: 1 }
Command `npm install --save --save-exact react-native` failed.

**Comment by Mr-Antivirus** [comment]
Why was this closed? I'm also having the same issue and I can't find a resolution. I personally think there is a bug where the cli version is referencing the wrong version of react. If I don't get a beta version of the cli, then I shouldn't be getting a beta version of react. It should be referencing the most stable version of react.

react-native-cli version: 2.0.1

**Comment by hramos** [comment]
Feel free to open a new issue, making sure to fill out the template and it won't be closed.
