### ISSUE TITLE
fetch is not work in IOS with React Native 0.45.1

### ISSUE THREAD

**Issue by bingfj2008** [facebook/react-native#14547]
Hi !
fetch is not work in IOS with React Native 0.45.1

/************  source like this *************************/
export async function callApi(paramObj, successCallback, errorCallback) {

  // オプション
  let option = {
    method: 'POST',
    headers: {
      'Accept': 'application/json',
      'Content-Type': 'application/json',
    },
    body: paramObj,
  };
    try {
      let response = await fetch("http://............", option);          // ※stop in here
      successCallback ? successCallback(await response.json()) : null;
    } catch (error) {
      errorCallback ? errorCallback(error) : null;
    }
    return;
}

This same source in Android ,fetch is work!

Please help!!!

* React Native version: 0.45.1
* Platform: IOS
* Development Operating System: mac os 10.12
* Build tools: Xcode 8.3.3

**Comment by EdwardHuCS** [comment]
There are already issues about this (#14391). Basically, response.json() is not resolving for some reason when RN is upgraded to 0.45.1. There is a quick work around.
```
fetch(url).then(response => {
  setTimeout(() => null, 0);  // workaround for issue-6679
  return response.json();
})
```
