### ISSUE TITLE
fail to start the program!

### ISSUE THREAD

**Issue by junliang0819** [facebook/react-native#14544]
### Description

** BUILD FAILED **

The following commands produced analyzer issues:

	Analyze /Users/jlchen/Desktop/AwesomeProject/node_modules/react-native/ReactCommon/yoga/yoga/YGNodeList.c
	Analyze /Users/jlchen/Desktop/AwesomeProject/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.c
(2 commands with analyzer issues)

The following build commands failed:
	PhaseScriptExecution Install\ Third\ Party /Users/jlchen/Desktop/AwesomeProject/ios/Build/Intermediates/React.build/Debug-iphonesimulator/double-conversion.build/Script-190EE32F1E6A43DE00A8543A.sh
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/AwesomeProject.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

### Reproduction Steps
now I'm on the desk folder,cli:
  react-native init AwesomeProject
  cd AwesomeProject
  react-native run-ios

### Additional Information

* React Native version: [0.45.1]
* react-native-cli version: [: 2.0.1]
* Platform: [iOS]
* Development Operating System: [macOS 10.12.3]
* Build tools: [Xcode 8.3.3 ]

**Comment by pannz** [comment]
same issue！

**Comment by hramos** [comment]
There's already an open issue about this.

**Comment by JessicaBarclay** [comment]
@hramos do you have a link to the issue?

**Comment by hramos** [comment]
These are all the issues that mention CFBundleIdentifier that are currently open: https://github.com/facebook/react-native/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20CFBundleIdentifier

**Comment by grigored** [comment]
did you fix this?

**Comment by hramos** [comment]
Duplicate of #14423
