### ISSUE TITLE
have react-native link error with project integrating from existing app 

### ISSUE THREAD

**Issue by Katakeyni** [facebook/react-native#14558]
Hi,

I have integrated RN with an existing android app following this link [here](https://facebook.github.io/react-native/docs/integration-with-existing-apps.html).
I wanted to add **react-native-vector-icons**  but when I run **react-native link ** I have the following error : 
_**ENOENT: no such file or directory, open 'android/src/main/java/com/szxb/s8api/MainApplication.java'**_
![error](https://user-images.githubusercontent.com/6898114/27231704-0251ac9e-52a3-11e7-8669-1bab1873d9d4.png)

**Comment by ben-snaize** [comment]
This would be best asked [here](https://github.com/oblador/react-native-vector-icons)

**Comment by Katakeyni** [comment]
Thank you I finally find the solution.
Thank

**Comment by sun2rise** [comment]
@Katakeyni what was that? i am experiencing the same issue with another package..
