### ISSUE TITLE
World's worst high-five not rendering in second code sample

### ISSUE THREAD

**Issue by dirkstoop** [facebook/react-native#14566]
### Description

Visited https://facebook.github.io/react-native/, tried second example (under header "A React Native app is a real mobile app") in a react-native project. Image does not render

### Reproduction Steps

1. Add the below JSX to any component that won't apply a styleSheet to it:
        <Image source={{uri: 'https://i.chzbgr.com/full/7345954048/h7E2C65F9/'}} />
2. npm start ios
3. notice how the image does not render

#### Sample Code

App.js:

import React from 'react';
import { Image } from 'react-native';

export default class HighFives extends React.Component {
  render() {
    return (
      <Image source={{uri: 'https://i.chzbgr.com/full/7345954048/h7E2C65F9/'}}/>
    );
  }
}

### Solution

Adding style={{width:320 height:240}} fixes it, but not sure if that's the right fix. New to this.

### Additional Information

* React Native version:     "react-native": "^0.44.0"
* Platform: iOS
* Development Operating System: macOS el capitan
* Build tools: N/A, running Expo app

**Comment by dirkstoop** [comment]
Isolating issue: replacing the uri with "https://media0.giphy.com/media/xUA7baC8zM9BAVFYLC/giphy.gif" does not address issue, showing that problem is not related to original gif no longer being world's worst high-five ever.

**Comment by hramos** [comment]
Interesting - I thought I had fixed this, but it looks like I didn't get around to pushing a fix. Yes, the fix is to add `style={{width:320 height:240}}` as React Native needs to know the dimensions for a remote image ahead of time. Do you want to send a PR? Should be a quick fix.

**Comment by dirkstoop** [comment]
Sure thing, I'll put one up in a minute. Cheers!

**Comment by peterp** [comment]
@hramos I've seen this issue hit a few web-dev-people, do you think there's value in adding a runtime warning to images loaded over the network that don't specify dimensions? Something along the lines of "Remote images must specify dimensions, `style={{ height: 100, width: 100 }}`, ahead of time."

**Comment by ItsNoHax** [comment]
I don't know if it is related to this but if an Image has a borderRadius style, it won't load the image in RN 0.46.1, 0.46.2, 0.46.3 (the ones I've tested so far)

**Comment by peterp** [comment]
@ItsNoHax Can you reproduce in an expo demo?

**Comment by ItsNoHax** [comment]
https://github.com/facebook/react-native/issues/15053
