### ISSUE TITLE
Documentation for useNativeDriver needs to be updated

### ISSUE THREAD

**Issue by a-koka** [facebook/react-native#14564]
### Description

The [docs](
https://facebook.github.io/react-native/docs/animations.html#using-the-native-driver) state that `backgroundColor` works when using native driver under the Caveats section but I verified that this indeed doesn't work. We need to update the docs.

![screenshot](https://user-images.githubusercontent.com/16167317/27238187-c95babf0-5280-11e7-97d5-359f986fd5b5.png)

#### Sample Code

```
Animated.timing(this.state.background, {toValue: 300, useNativeDriver: true}).start();

render() {
    var color = this.state.background.interpolate({
        inputRange: [0, 300],
        outputRange: ['rgba(255, 0, 0, 1)', 'rgba(0, 255, 0, 1)']
    });

    return (
        <View style={{backgroundColor:color}}></View>
    );
}
```

### Solution

Docs need to be updated

### Additional Information

* React Native version: 0.44.2
* Platform: Both
* Development Operating System: macOS

**Comment by hramos** [comment]
cc @janicduplessis should backgroundColor be supported?

**Comment by janicduplessis** [comment]
It could be, just not implemented yet :)

**Comment by janicduplessis** [comment]
@a-koka Would you like to submit a PR to update the docs to avoid confusion until we support backgroundColor?

**Comment by a-koka** [comment]
Looks like @emilong beat me to the punch [here](https://github.com/facebook/react-native/commit/280ed810b0ee645df0c82c58ce5d0076f5b4dc5a). His PR has a failed check though. Should I still submit a PR?

**Comment by janicduplessis** [comment]
Oh nice, seems like it's fixed then. It will appear in the next version of the docs.
