### ISSUE TITLE
react-native link does not work with Android native modules written in kotlin

### ISSUE THREAD

**Issue by rauliyohmc** [facebook/react-native#14561]
### Description

Since Google announced Kotlin support for developing applications with Android, I've been building a library that implies bridging Native code to JavaScript and decided to go with Kotlin. However, the linking step does not work automatically since `local-cli` only supports modules written in Java

### Reproduction Steps

- Write a simple Native Module in Android using Kotlin
- Consume it in a RN example project
- Type `react-native link <your-library-written-in-kotlin>` from your example project
- Nothing happens

### Solution

- I could compose a PR to add support for kotlin into the `local-cli` (rnpm part). It would be my first PR, but I would be very happy to take it over.

### Additional Information

* React Native version: react-native>=0.43
* Platform: Android
* Development Operating System: macOS

**Comment by grabbou** [comment]
Do it! Since we work together, you know where to look for help! 💯
