### ISSUE TITLE
picker text cropped

### ISSUE THREAD

**Issue by ReactFan23** [facebook/react-native#14575]
hello i have big data (9000 Item) and  using react native picker for select , when i open picker my inner text was cropped (android)
can anyone help me ?

[see this pic](http://prntscr.com/fkxqs0)

how i can break text at new line  if text doesn't fit? 

this is picker code

`<View style={styles.input}> 

                        <Picker iosHeader="Select one"
                                mode="dropdown"
                                selectedValue={this.state.query[input.model]}
                                onValueChange={ e => this.query(input.model, e) }>
                            {array.map((val, index) => (
                                <Text key={index}
                                      label={ (val.name) ? val.name : val}
                                      value={(val.id) ? val.id : val}/>
                            ))}
                        </Picker>
                    </View>`

**Comment by alexgnatrow** [comment]
Why this was closed? Is there any solution to this issue?
