### ISSUE TITLE
FlatList cannot scroll when wrapped in a absolute position View.

### ISSUE THREAD

**Issue by Symous** [facebook/react-native#14573]
Code: 
```js
<View style={{position:'absolute'}}>
   <FlatList .../>
</View>
```
Platform: Android

React-Native Version: 0.43.4

**Comment by Symous** [comment]
@hramos Hi,Please can you tell me why you close it without any feedback ?

**Comment by hramos** [comment]
Before you submit an issue, please [review the guidelines](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#bugs) for this repository. This particular issue did not follow the issue template that is provided when a new issue is created.
