### ISSUE TITLE
Facebook login in a webview

### ISSUE THREAD

**Issue by tywoodpav** [facebook/react-native#14576]
I am developing a simple web browser (WebView) using `react-native`.

Everything works well except logging into Facebook.

The website has a Facebook login and when I tap it, it takes me to the in-app mobile Facebook login page. Entering the correct user/pass redirects me to `/dialog/oauth?redirect_uri=https://staticxx.facebook.com/connect.......` and I get stuck there.

Without using `react-native-fbsdk` how do I solve this? 

Using the same site on desktop and mobile safari works well. (Although it opens a new tab).

**Comment by tywoodpav** [comment]
Why was this closed? Still have the issue.

**Comment by hramos** [comment]
Before you submit an issue, please [review the guidelines](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#bugs) for this repository. This particular issue did not follow the issue template that is provided when a new issue is created.

**Comment by leonardogutierrezh** [comment]
I think this issue should be reopen, Its a big issue regarding if is following the right issue template or not...
