### ISSUE TITLE
Geolocation - Calling watchPosition without specifing options results in error

### ISSUE THREAD

**Issue by esteban-filardi** [facebook/react-native#14580]
### Description

Calling `watchPosition` passing just the first argument results in error

>  Attempt to invoke interface method '...ReadableMap.hashKey' on null object reference.

.Sending "{}" as the third parameters makes it work. I think it should work without sending the "options" parameter, as per the documentation.

### Reproduction Steps

Call `navigator.geolocation.getCurrentPosition((position) => {});`

(No optional parameters specified)

#### Sample Code

https://snack.expo.io/HJ4JpPXQZ

### Solution

I think handle the case in which the third parameter (options parameter) is null.

### Additional Information

* React Native version: 0.44.3
* Platform: Android
* Development Operating System: Windows 10
* Build tools: 17

**Comment by caal-15** [comment]
I can confirm this Issue, adding an empty options object solved the problem.

**Comment by WillBeebe** [comment]
Confirming it's still an issue with a fresh project.
