### ISSUE TITLE
scrollTo of ScrollView doesn't work sometimes

### ISSUE THREAD

**Issue by wjwzwy** [facebook/react-native#14582]
We are working on app, which loads content into a ScrollView dynamically. So, the content of ScrollView changes. During the content change of ScrollView, we are calling scrollTo. Sometimes, we call it like scrollTo({x: 0, y: 0, animated: true});, but in onScroll event, the offsetY is NOT 0, but is 300, 120, or else. That is so weird.

Did anyone run into a similar issue?

**Comment by peterp** [comment]
I've noticed this as well, with `{ /*..*/, animated: false, }` it appears works correctly?

**Comment by adarshTS** [comment]
can someone help here : [https://stackoverflow.com/questions/45568086/how-to-select-the-center-item-in-a-scroll-view-from-a-list-of-items](https://stackoverflow.com/questions/45568086/how-to-select-the-center-item-in-a-scroll-view-from-a-list-of-items)
