### ISSUE TITLE
undefined is not an object evaluating ReactPropTypes.string

### ISSUE THREAD

**Issue by damiaozi** [facebook/react-native#14590]
react-native run-android，then
error
undefined is not an object evaluating ReactPropTypes.string

**Comment by AriaEdo** [comment]
Maybe you can check this https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

**Comment by bartolkaruza** [comment]
@damiaozi maybe you are having the same issue as https://github.com/facebook/react-native/issues/14588 ? What version of RN are you?

**Comment by DavitVosk** [comment]
the same problem here. Anybody has fixed the problem?

**Comment by cromasystem** [comment]
After version 15.5 you have to import PropTypes from prop-types like below:

import React from 'react';
import PropTypes from 'prop-types';

class Component extends React.Component {
  render() {
    return <div>{this.props.text}</div>;
  }
}

Component.propTypes = {
  text: PropTypes.string.isRequired,
};

**Comment by sachinwak** [comment]
@cromasystem   yes it works thanks.  i have replaced React.PropTypes with PropTypes

**Comment by elvismercado** [comment]
@cromasystem do i have to do this for every component?

**Comment by MonsieurPetion** [comment]
good quest @elvismercado

**Comment by KothariShridutt** [comment]
import PropTypes from 'prop-types'; 

worked for me !! Thanks

**Comment by theebi** [comment]
import PropTypes from 'prop-types';
This works for me too.

**Comment by vishakha7395** [comment]
import React from 'react';
import PropTypes from 'prop-types';

**Comment by wanghuajian620** [comment]
![screen shot 2018-01-22 at 4 23 15 pm](https://user-images.githubusercontent.com/31924547/35211537-dbd4fd68-ff91-11e7-8b42-13946bc45755.png)

**Comment by Shazam14** [comment]
what specific module or file did you change?? going nuts.. doing this...

**Comment by tannerhallman** [comment]
@Shazam14 you will have to make the change in both your modules and those modules of the libraries you have declared in your package.json. There's a lot of pull requests waiting to merge these fixes into various libraries that I've run into, but until those are merged and packaged for deployment, you will have to make the temporary fix yourself.
