### ISSUE TITLE
[Text] Text is nondeterministically rendered on one line

### ISSUE THREAD

**Issue by ide** [facebook/react-native#1459]
After the Friday sync (though the Thursday sync could be to blame too), this text rendering bug appeared where text that should wrap was rendered on a single line. Notably the layout of the screen is correct, it's just the text drawing that's wrong. Refreshing the bridge and root view made the issue go away.

Screenshot (drop shadow was applied after screenshotting):
![text](https://cloud.githubusercontent.com/assets/379606/7896331/6d0b2498-066a-11e5-9f58-909b9dd19088.png)

cc @nicklockwood

**Comment by ide** [comment]
These are `<Text>` components that don't set a max number of lines. I'm not sure what caused this bug but one hypothesis is that when the NSTextStorage for the RCTText view is created in `uiBlockToAmendWithShadowView:`, the frame of the shadow view is somehow incorrectly very wide. The NSLayoutManager would think there is enough room to draw the text on one line.

**Comment by nicklockwood** [comment]
This was a consequence of the text multithreading crash fix. I landed a fix for this yesterday, but it must have just missed the branch cut.

**Comment by ide** [comment]
That's great to hear. I'll close this out.

**Comment by ide** [comment]
I'm seeing this with master still (up to and including the June 10 sync). Once I tap the screen the text reflows properly but occasionally it is rendered all on one line.

**Comment by nicklockwood** [comment]
Is this only happening for you when the screen is rotated / RCTRootView is resized?

If so, I have a fix.

If not, can you provide steps to reproduce?

**Comment by ide** [comment]
No screen rotation. The root view is smaller than the screen, but it isn't resized after its initial layout is computed... maybe there's a race condition where the content is rendered and then the root view is laid out.

**Comment by nicklockwood** [comment]
Possibly. I landed a fix for the rotation issue anyway. Once it hits Github, let me know if it's fixed.

If not, a sample app to repro the issue would be super-helpful.

**Comment by ide** [comment]
I haven't seen this in the past couple of weeks. Closing it out.
