### ISSUE TITLE
Building react-native as a CommonJS module?

### ISSUE THREAD

**Issue by joewood** [facebook/react-native#146]
Is it possible to use **jsx** CLI to build the react-native JS files into a set of CommonJS files? I've tried following the same steps that **react** is built with, but **jsx** is having problems finding the modules through `@providesModule`. There also seems to be a few duplicate modules (like tabBarIOS) that trip up a build without a root module.  Any hints would help.

**Comment by brentvatne** [comment]
@joewood - is this still something you're wanting to do? Did the discussion in the issue mentioned above solve you problem? ping me if not, otherwise we'll just keep this closed
