### ISSUE TITLE
Text component doesnt works properly on some android devices. 

### ISSUE THREAD

**Issue by thayanithik** [facebook/react-native#14603]
I am using <Text> component in my sample project. When am using <Text> tag to display some user information like "<Text>Disclaimer</Text>", only part of "Disclaimer" is visible. It shows perfectly on few devices only. It shows partially on some android devices...

I dont know why this is happening, please refer the following details and code.

Kindly help me to solve the issue...

working fine on :  Redmi 4 
resolution: 1080 x 1920 pixels (~441 ppi pixel density)
size: 5.0 inches (~70.1% screen-to-body ratio)
** Working Screenshot:**
![screenshot_2017-06-19-20-25-38-526](https://user-images.githubusercontent.com/29544750/27291714-b1747610-552e-11e7-80d3-a0919b4588c3.jpeg)

Not working on : oppo f3 plus
resolution: 1080 x 1920 pixels (~367 ppi pixel density)
size: 6.0 inches (~75.1% screen-to-body ratio)
**Non-working Screenshot:**
![screenshot_2017-06-19-19-17-46-16 1](https://user-images.githubusercontent.com/29544750/27289347-3c1a45c2-5527-11e7-9b6b-305444a727e1.png)

/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */
index.android.js

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  TouchableHighlight,
  Alert
} from 'react-native';

export default class MyFirstProject extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit index.android.js
        </Text>
        <Text style={styles.instructions}>
          Double tap R on your keyboard to reload,{'\n'}
          Shake or press menu button for dev menu
        </Text>
        <TouchableHighlight
                    underlayColor = {'#F07E0C'}
                    onPress = {() => Alert.alert('Button pressed')}
                    style={styles.buttonContainer}
                    >
              <Text style = {styles.buttonText}>
                 Disclaimer
              </Text>
        </TouchableHighlight>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
  buttonContainer: {
    height: 55,
    backgroundColor: '#F07E0C',
    borderColor: '#F07E0C',
    borderWidth: 1,
    borderRadius: 5,
    marginBottom: 10,
    paddingLeft:10,
    paddingRight:10,
    justifyContent: 'center'
  },
  buttonText: {
    fontSize: 20,
    fontWeight:'bold',
    color: 'white',
    alignSelf: 'center'
  }
});

AppRegistry.registerComponent('MyFirstProject', () => MyFirstProject);

**Comment by ssssssssssss** [comment]
Any workaround? Or is it fixed in latest release?

**Comment by mdomygit** [comment]
Any solution?

**Comment by Rajat421** [comment]
Any solution for this

**Comment by matthieucan** [comment]
Looks like the same bug as in #15114, you'll find solutions there.
