### ISSUE TITLE
How to test React Native component with Jest ?

### ISSUE THREAD

**Issue by checkraiser** [facebook/react-native#1460]
Do you know how to use Jest to test React Native component instead of integration test using XCTest ?

**Comment by brentvatne** [comment]
Dup: https://github.com/facebook/react-native/issues/700

**Comment by checkraiser** [comment]
Jest uses `contextify`, i install jest with `npm install -g jest-cli` . How to run the test with `react-native` ?

**Comment by brentvatne** [comment]
@checkraiser - can you ask that question in the issue I mentioned above? Ideally we would keep all related conversations in one place
