### ISSUE TITLE
View styles were removed in docs

### ISSUE THREAD

**Issue by RyanMitchellWilson** [facebook/react-native#14605]
I'm trying to find all the styles that can be applied to a view but when I get to the View page in the docs, the style section is completely empty. It would be great if we could get these back.

https://facebook.github.io/react-native/docs/view.html#style

<img width="937" alt="screen shot 2017-06-19 at 9 37 24 am" src="https://user-images.githubusercontent.com/11371200/27293201-ef76519c-54d2-11e7-861b-7cb09ff9677b.png">

**Comment by hramos** [comment]
Hey, thanks for reporting this. We're tracking this in #14147.
