### ISSUE TITLE
[iOS][v0.44] Unable to archive - 'React/RCTBundleURLProvider.h' file not found in appDelegate.m

### ISSUE THREAD

**Issue by arun542** [facebook/react-native#14601]
'React/RCTBundleURLProvider.h' file not found in appDelegate.m while trying to archive. Works like a charm in simulator as well as ios device in both debug and release mode. Already tried all the changes needed for RN >0.4.0.
1) Tried solutions suggested on https://github.com/facebook/react-native/issues/11813#issuecomment-273279257 
2) Removed parallelize build, added react to build targets before the app
3) Changed optimization level to none.

But nothing works 

* React Native version: 0.44.0
* Platform: IOS
* Development Operating System: macOS
* Build tools: Xcode 8.3.2

**Comment by pallyoung** [comment]
i got the error too, can't fixed it . i can build at debug mode,but when i tried to build it at release mode, i got the error. is any one else has the same question with me.

**Comment by Albinzr** [comment]
same issue for me also

**Comment by Jinran** [comment]
when you npm install some plugins, make sure your plugins`s Build Settings header search paths is 
 right , I`m sorry this question puzzled me several days . Wish helpful.

e.g. 

react-native-device-info
![image](https://user-images.githubusercontent.com/16407903/31852987-cf81b1da-b646-11e7-8bf8-0cf3356301e6.png)
remove  (/node_modules/...)

**Comment by magichim** [comment]
@arun542 try to build and run in xcode and then you will get wanting :)
