### ISSUE TITLE
Print: Entry, “:CFBundleIdentifier”, Does Not Exist

### ISSUE THREAD

**Issue by udave216** [facebook/react-native#14604]
![sc](https://user-images.githubusercontent.com/29546531/27291367-43fb7542-5525-11e7-8787-3378234fd4f3.jpg)

HELPPPPPPP.... :(

MAC-OS 10.12
XCODE 8.2.1

react-native run-ios not workgin.... !!!

**Comment by hramos** [comment]
Hey, thanks for reporting this. There's actually a handful of issues already open about this. If you believe this is a separate issue, please fill out the issue template when opening a new issue.

**Comment by hramos** [comment]
Duplicate of #14423

**Comment by flawnn** [comment]
HELP

**Comment by flawnn** [comment]
I Have the same Issue! Please HELP

**Comment by udave216** [comment]
1. Duplicate of [#14423](https://github.com/facebook/react-native/issues/14423)
OR
2. Update to last version

**Comment by liss1990** [comment]
You can try the following method:
$ react-native init ReactCalculator --version 0.44.3
$ cd ReactCalculator
$ react-native run-ios

**Comment by iHirenDev** [comment]
I had version 0.52 of React Native and tried almost all the trick I found on the internet but have not got succeeded. Then I tried @liss1990 's solution and it worked for me, but I have to downgrade the version.
