### ISSUE TITLE
Android React Text Component includeFontPadding:false incorrect height

### ISSUE THREAD

**Issue by mishagreenberg** [facebook/react-native#14606]
On Android, when includeFontPadding is set to false, the React Text component does not adjust its height. This makes it difficult to lay out other components at a precise spacing relative to a Text component.

For the native TextView component, the height is different depending on the value of includeFontPadding-

When includeFontPadding is set to true, the height of the TextView is based on abs(FontMetrics.top) + abs(FontMetrics.bottom). 

When includeFontPadding to set to false, the height of the TextView is based on abs(FontMetrics.ascent) + abs(FontMetrics.descent).

This is happening because in ReactTextShadowNode.java, includeFontPadding is hardcoded to true when passing parameters to StaticLayout and BoringLayout. This seems like an easy fix.

An example from the measure function in ReactTextShadowNode.java -

private final YogaMeasureFunction mTextMeasureFunction = new YogaMeasureFunction() {
```
BoringLayout.make(
                text,
                textPaint,
                boring.width,
                Layout.Alignment.ALIGN_NORMAL,
                1.f,
                0.f,
                boring,
                true); // this parameter is includeFontPadding and should be based on the includeFontPadding value style of the component
...
};
```

**Comment by dmueller39** [comment]
@hramos Can you provide a reason for closing the issue? Does it need more information?

**Comment by lelandrichardson** [comment]
I'd like to reopen this issue as I believe font rendering remains to be one of the biggest reasons for cross-platform differences across iOS and Android and this is an important thing to explore.

**Comment by msand** [comment]
We're tracking similar issues in react-native-svg here: https://github.com/react-native-community/react-native-svg/issues/362 and here https://github.com/react-native-community/react-native-svg/issues/377

I've fixed most of the issues, but it depends on magic constants in two places. And kerning is still off (if the letter-spacing is not set to a length value). Font rendering and kerning has a surprisingly big effect on the user / reading experience, especially if there are large amounts of text or larger font-sizes on headers and labels etc.

**Comment by mishagreenberg** [comment]
#14609 is a PR to fix this issue

**Comment by mishagreenberg** [comment]
#14609 was merged
