### ISSUE TITLE
Can't run tvOS target for newly generated RN project

### ISSUE THREAD

**Issue by vrudikov** [facebook/react-native#14613]
### Description

**Basic iOS target runs successfully**
I've created basic RN project with the help of react-native-cli and tried to run tvOS target, but got the following issue:
```
AppleTvSample/node_modules/react-native/ReactCommon/jschelpers/Value.cpp:3:10: 'folly/json.h' file not found
```

**!!!RNTester application fails for the tvOS target too with the error above**

### Reproduction Steps

```
> react-native init sample_program
> cd sample_program
> open ios/sample_program.xcodeproj
> change Run Target to tvOS. Run it
```

#### Sample Code

[AppleTvSample](https://github.com/vrudikov/AppleTvSample)

### Solution

Can't say for sure, because i'm not so familiar with XCode and Objective-C

### Additional Information

* React Native version: 0.45.1
* react-native-cli: 2.0.1
* Platform: tvOS
* Development Operating System: macOS 10.11.6
* Build tools: Xcode 8.2.1

**Comment by speedandfunction-anri** [comment]
+1

**Comment by speedandfunction-helen** [comment]
+1

**Comment by knot123** [comment]
+1

**Comment by altayaydemir** [comment]
+1 😢

**Comment by altayaydemir** [comment]
@vrudikov, @speedandfunction-anri, @speedandfunction-helen, @know123 hi guys. 

it's confusing as hell but creating and ejecting an app with [create-react-native-app](https://github.com/react-community/create-react-native-app) resolved this one for me.

* npm i create-react-native-app -g
* create-react-native-app MyAwesomeProject
* cd MyAwesomeProject
* npm run eject

lulz 😅

**Comment by vrudikov** [comment]
@altayaydemir Cool! Thanks for sharing!

**Comment by knot123** [comment]
@altayaydemir I tried but same error appears 'folly/json.h' file not found

**Comment by ndcollins** [comment]
@knot123 @altayaydemir I also get the same error that 'folly/json.h' file not found.

**Comment by vrudikov** [comment]
@Hi, all. It works for me. Guys, please post your environment specs as I
did above

On Jun 24, 2017 6:11 AM, "Nick Collins" <notifications@github.com> wrote:

@knot123 <https://github.com/knot123> @altayaydemir
<https://github.com/altayaydemir> I also get the same error that
'folly/json.h' file not found.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/facebook/react-native/issues/14613#issuecomment-310809930>,
or mute the thread

**Comment by vrudikov** [comment]
@ndcollins @knot123 Hi, all. It works for me. Guys, please post your environment specs as I did above

**Comment by ndcollins** [comment]
Identical environment  from what I can tell

react-native-cli: 2.0.1
react-native: 0.45.1
Platform: tvOS
Development Operating System: macOS 10.12.5
Build tools: Xcode 8.3.3 (8E3004b)
Yarn: 0.24.6
Node: 6.10.1
NPM: 4.6.1

**Comment by altayaydemir** [comment]
well, hello again. https://github.com/facebook/react-native/issues/14613#issuecomment-310756091 is worked for me once. but doesn't work now 🤔 

I guess that is a
### double lulz 😅 
situation

**Comment by vrudikov** [comment]
Strange, but yes. Stopped working for me too. What i see is that there some difference between jschelpers and jschelpers-tvOS targets. But can't understand what is that difference. Both projects share the same Target Dependency: third-party(React)

**Comment by vrudikov** [comment]
Strange, but yes. Stopped working for me too. What i see is that there some difference between jschelpers and jschelpers-tvOS targets. But can't understand what is that difference. Both projects share the same Target Dependency: third-party(React)

**Comment by vrudikov** [comment]
So here is the difference between working project(right) and failing(left)

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/493714/27557114-09c4a4c4-5ac1-11e7-8ab0-11495d9b8875.png">

**Comment by joduss** [comment]
Any news? I'm having the same issue?

react-native-cli: 2.0.1
react-native: 0.45.1
Build tools: Xcode 8.3.3
NPM: 4.6.1
Yarn: 0.27.5
Development Operating System: 10.12.5

**Comment by joduss** [comment]
I created the projet by mistake in /usr/local/Cellar/node/8.1.3/bin/ and it is working. Certainly something to do with permissions.

**Comment by Failcookie** [comment]
@joduss could you provide more information on what you did? I am having the same issue, but my folder is within my user library, so I feel like i shouldn't have any permission issues.

**Comment by joduss** [comment]
I tried to remove node, yarn etc nothing changed.  Until I did the react-native init in the folder I mentioned above.
So it could weird permissions or something not supported in the path. I didn't try in other locations.

**Comment by Maxwell2022** [comment]
in my case, it 'folly/dynamic.h' that is missing, brand new project:
I've also ejected to project, `yarn eject`

`create-react-native-app version: 0.0.6`
`react-native: ^0.45.1`

**Comment by ndcollins** [comment]
This issue appears to now be resolved. Now if you run react-native init the project is generated using react-native 0.46.4 in which this issue appears to be fully resolved.

**Comment by Failcookie** [comment]
Can confirm - updated to the lasest version of react-native and I am good to go.

**Comment by Maxwell2022** [comment]
humm, I just realised that the documented way to start a project (ie. `create-react-native-app`) is using expo, and expo is not using the latest version of RN by default.

Really annoying...

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
