### ISSUE TITLE
View.js, line 84: const View = React.createClass,  LayoutPropTypes.js -> React.PropTypes

### ISSUE THREAD

**Issue by switheyw** [facebook/react-native#14610]
### Description

Explain what you did, what you expected to happen, and what actually happens.

### Reproduction Steps

List all the steps required to reproduce the issue you're reporting. These steps should be clear and concise. Always include a sample of your code.

#### Sample Code
 
// $FlowFixMe(>=0.41.0)
84: const View = React.createClass({

 
An example of your code or a reproduction of the problem using Snack is **REQUIRED**.
Using Snack?   What is Snack.
The 1st few stack entries
printWarning    warning.js
warning            warning.js
get                   react_development.js
(anonymous)   View.js

### Solution

What needs to be done to address this issue? Ideally, provide a pull request with a fix.
All of the calls to  React.createClass and calls to react-props have to be removed and replaced
with supported replacements.

### Additional Information

* React Native version: [FILL THIS OUT: Be specific, filling out "latest" here is not enough.]
albums(15:34)react-native --version
react-native-cli: 2.0.1
react-native: 0.45.1

* Platform: [FILL THIS OUT: iOS, Android, or both?]
iOS

* Development Operating System: [FILL THIS OUT: Are you developing on macOS, Linux, or 
Windows?]
Mac
* Build tools: [FILL THIS OUT: Xcode or Android Studio version, iOS or Android SDK version, if applicable]
Xcode 8.3.3

**Comment by switheyw** [comment]
Should user community generate a list of files with depreciated calls?

**Comment by hellomaya** [comment]
Probably same issues: 

https://github.com/facebook/react-native/issues/14621

https://github.com/facebook/react-native/issues/14620

**Comment by switheyw** [comment]
I agree.

I'm wondering how all of the changes are going to get done?   The provided source code translate package - jscodeshift <https://github.com/facebook/jscodeshift> - doesn’t work for me (or at least not ones I tried to update  i.e., React-PropTypes-to-prop-types <https://github.com/reactjs/react-codemod#react-proptypes-to-prop-types> and create-element-to-jsx <https://github.com/reactjs/react-codemod#create-element-to-jsx>).

Just a suggestion
Perhaps we could advertise for users to send in the names of files that they need fixed first. Then we wouldn’t be have to start at the beginning and go through to the end.  Instead we'd get the most critical files fixed first.

Stephen

**Comment by hramos** [comment]
> What is Snack?

https://snack.expo.io/

See the [contribution guidelines](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md) linked at the top. Snack provides a web player where you can share the JavaScript portion of your React Native app and allow others to run the app within an iOS or Android device.

**Comment by hramos** [comment]
This is being tracked in #14712
