### ISSUE TITLE
Validate custom fonts for compatibilty on iOS + Android

### ISSUE THREAD

**Issue by dmueller39** [facebook/react-native#14611]
Android + iOS interpret fonts slightly differently in 2 cases at the moment:

The style property for fontFamily on iOS refers to the internal post script name of the font. This is what the iOS UIFont object reports as fontName. The style property for fontFamily on Android refers to the filename of the font.

Additionally, iOS + Android pay attention to different metadata when defining the line height of a font. There is a metadata property called lineGap which is often used to specify how to layout a font. This is ignored on android but used on iOS. For a font to have the same layout on both platforms, the linegap should be 0. There are other variations on the metadata that can lead to layout differences between the plaforms, but linegap is a property that leads to significant discrepencies.
https://stackoverflow.com/questions/5414730/custom-installed-font-not-displayed-correctly-in-uilabel

There is some difference in character widths or letter spacing that needs some investigation.

### Reproduction Steps

This affects some custom fonts, added using the nominal flow of `react-native link`

#### Sample Code

https://github.com/dmueller39/react-native-font-discrepency-demo

Here is a side by side:

![screen shot 2017-06-19 at 3 53 16 pm](https://user-images.githubusercontent.com/9422359/27303062-75ec5486-5507-11e7-9bf5-3d5da9bcaea7.png)

Note the missing fonts for the first two examples and and the exacerbated line spacing in the third. The spacing between the letters is still different in the last example, but the two issues presented are things that led to big discrepancies for us.

### Solution

It would be great if there was some validation that ran on custom fonts somewhere between linking them + building the project. I would be excited to contribute to this (we already have a portion of this solved) but I would need some guidance on best practices of where to add this. 

### Additional Information

* React Native version: 0.45.0
* Platform: Android + iOS
* Development Operating System: macOS 10.12.5
* Build tools: Xcode 8.3.2 + AndroidStudio 2.3

**Comment by dmueller39** [comment]
Also note that the text examples wrap at different locations. If anyone has thoughts that would be great, but if not, well look into it.

**Comment by lelandrichardson** [comment]
@dmueller39 i think the wrapping in different places is just due to different viewport sizes, no? I don't think i would call that a bug. Agree some extra validations would be great, or making the font loading process more similar for the two platforms.

**Comment by dmueller39** [comment]
@lelandrichardson

Whats the best way to surface a warning? At the time of `react-native link` (this might be really complicated actually) or at runtime?

- runtime would be really annoying if you want to use a custom font without modifying it, or if you are only developing for one platform. It's almost like we would need to add something that could silence that error. Also at the moment I think only iOS can do this without adding any dependencies. Android would need to add some additional font parsing capabilities.
- `react-native link` would require some npm dependencies for font parsing (which might be a no-go tbh).

Any thoughts on the best direction?

**Comment by peterp** [comment]
Perhaps we could write a shell script that's capable of adjusting the fonts to behave the same, and additionally writing some documentation on how to add custom fonts to each platform (there isn't any documentation on this process yet.)

**Comment by shivawu** [comment]
+1 for this!

I think the most ideal way to solve this is for `react-native link` to create some kind of metadata stored in project's files for both iOS and Android with some custom API to locate the font by a single source of truth (file name seems easier)

Just an idea with require and the bundler would figure this out for both platform.

```
textStyle: {
  fontFamily: require('../../assets/fonts/Awesome.otf'),
}
```

At least, the fact that iOS uses PostScriptName and Android uses file name should be properly documented somewhere in the official docs, given how much time people have spent on this issue, accoss multiple teams
