### ISSUE TITLE
Does the Webview's postMessage have character limitation when post message from React APP to JavaScript ????

### ISSUE THREAD

**Issue by rogerluo410** [facebook/react-native#14619]
-- Please use this template, and delete everything above this line before submitting your issue ---

**Description**

Does the Webview's postMessage have character limitation when post message from React APP to JavaScript ????  

I post a short string which is ok, but, when I post a long string (more than 10 characters perhaps) that I can't receive the message in JavaScript.   

```javascript    

      React Naive end: 
       const message = '123'   //it's ok, what if --->
       const message = '123456374343843848348323232'   //it's not     
        this.webView.postMessage(message)

      JaveScript: 
        document.addEventListener("message", function(event) {
           alert(123);   // Not popup, if string is long enough
         }
       }, false);
```

**Solution**

I want to confirm whether the post message has character limitation??   any solutions ??

To be honest, using React-Native which is a tired working, I would go to give up.

**Additional Information**

React Native version: 0.44.2
Platform:  iOS / Android
Operating System: MacOS

**Comment by rogerluo410** [comment]
Not a problem/... closed

**Comment by PrimeLens** [comment]
I'm interested what the character limit is if anyone knows it
