### ISSUE TITLE
BorderRadius has some mistake in ReactImageView 

### ISSUE THREAD

**Issue by jetzhliu** [facebook/react-native#14627]
- border[Top|Bottom][Left|Right]Radius have no effect in __iOS__, but borderRadius are correct
- Both borderRadius and border[Top|Bottom][Left|Right]Radius are incorrect in __Android__

The second case is as follows:

I use an Android phone with 1080*1920, and set an Image with the following style:

```js
  myImamge: {
    width: 60,
    height: 60,
    resizeMode: 'contain',
    borderColor: '#ffffff',
    borderRadius: 30,
  },
```

The Image doesn't like a circle, but when set the borderRadius to `90`, it does!! I think it has something wrong with scaling.

I'd tried it using v0.44 and v0.45.

**Comment by hramos** [comment]
@tindn back then, we'd instantly close issues that did not follow the new issue template. Please open a new issue with more information if you're running into this in 0.53 or newer.
