### ISSUE TITLE
Warning: React.createClass is no longer supported.

### ISSUE THREAD

**Issue by hellomaya** [facebook/react-native#14620]
When try ```react-native run-ios```, by using ```Debug JS Remotely```,  it showed those warning in Google Chrome developer tools.

```
ExceptionsManager.js:71 Warning: React.createClass is no longer supported.
 Use a plain JavaScript class instead. 
If you're not yet ready to migrate, 
create-react-class is available on npm as a drop-in replacement. (https://fb.me/migrating-from-react-create-class)
```

> https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.createclass

By searching ```React.createClass``` in ```react-native``` folder, there are many parts used it.

For example, in ```Image.android.js```, line 79:

```
var Image = React.createClass({
  propTypes: {
    ...ViewPropTypes,
    style: StyleSheetPropType(ImageStylePropTypes),
```

* React Native version: 0.45.1
* Platform: iOS
* Development Operating System: macOS 10.12.5
* Build tools: Xcode 8.3.2

**Comment by hellozhangran** [comment]
I have the very same question with you

But ~~~~  when i remove React.createClass , and this warming still here !

**Comment by Gumija** [comment]
I think this is caused by this
```
// $FlowFixMe(>=0.41.0)
const View = React.createClass({
```
Source: node_modules/react-native/Libraries/Components/View/View.js
