### ISSUE TITLE
Button.onPress parameter not documented

### ISSUE THREAD

**Issue by dpkirchner** [facebook/react-native#14634]
### Description

The `onPress` documentation for `Button` does not explain what argument(s) may be passed.

I visited https://facebook.github.io/react-native/docs/button.html .
I expected to find documentation describing the argument passed to `onPress`.
The documentation seems to suggest that no arguments are passed `() => any`.

### Reproduction Steps

Do the stuff in the description.

#### Sample Code

N/A

### Solution

The documentation would be updated to show the parameter that is passed to the `onPress` callback. Ideally, it'd link to the documentation of that parameter.

### Additional Information

* React Native version: v0.46.0-rc.2 (current master)
* Platform: N/A
* Development Operating System: N/A
* Build tools: N/A

**Comment by hramos** [comment]
It's just a function that is called when the button is pressed. The component does not place any requirements on what sort of function you use or what parameters you pass to it.

**Comment by dpkirchner** [comment]
I may not have been clear. A parameter is already being passed, when you specify something like `onPress={this.method}`, but its type and structure are not documented anywhere (that I have found, certainly not on that `Button.html` page or in its source).

To be more clear, I'm not talking about adding my own parameters.

**Comment by hramos** [comment]
The docs are generated from the source code. This is effectively calling http://facebook.github.io/react-native/docs/touchablewithoutfeedback.html#onpress, and from what I can see the only parameter passed is an Event https://github.com/facebook/react-native/blob/master/Libraries/Components/Touchable/TouchableWithoutFeedback.js#L119

**Comment by McPo** [comment]
So should the Event not then be documented. I believe that is what @dpkirchner is getting at. As It did not appear to me that onPress was called with any parameters, where as it is apparently being called by and Event object. The next question is what is within the Event object.

Im interested in this, to see if theres a way for me to get an attribute from the button element that was pressed.

Or am I missing something?

**Comment by kvrmd** [comment]
@McPo 
What about this?
```jsx
import { Button as RNButton } from 'react-native'
export class Button extends React.PureComponent {
  static defaultProps = {
    onPress: () => {}
  }
  static propTypes = {
    data: PropTypes.any,
    onPress: PropTypes.func
  }
  onPress = () => {
    this.props.onPress(this.props.data)
  }
  render () {
    const { data, onPress, ...otherProps } = this.props
    return <RNButton {...otherProps} onPress={this.onPress} />
  }
}
```
