### ISSUE TITLE
Cannot read property 'string' of undefined | React.PropTypes | LayoutPropTypes.js

### ISSUE THREAD

**Issue by gyetvan-andras** [facebook/react-native#14644]
We can play this game this way. @hramos you should try to read and understand our problem, instead of giving advice how to look answer on SO, and filling stupid forms. The case is clear, there is a problem, which was described well enough to understand. But you come with meaningless advices and asking for proper format of report, while every detail is given.

After deleting and reinstalling my node_modules folder, I'm facing an issue that I don't understand in LayoutPropTypes.js file.

In node_modules/react-native/Libraries/StyleSheet/LayoutPropTypes.js
The following variable is undefined : var ReactPropTypes = require('React').PropTypes;

react-native: 0.45.1
react: 16.0.0-alpha.12

Hey @hramos , don't close this issue giving an advice to search for solution on StackOverflow. It is a critical issue. My whole development is down because of this. And of course, first I tried to look an answer on StackOverflow, the only answer is to use prop-types package, but HOW in RN source?!

**Comment by hramos** [comment]
Alright then.
