### ISSUE TITLE
TextInput horizontal padding does not update on iOS

### ISSUE THREAD

**Issue by davidlongest** [facebook/react-native#14645]
#### What happens
When changing horizontal padding (`paddingRight`, `paddingLeft`, `paddingHorizontal`) on a TextInput during focus change, the text in the TextInput view should reflect the padding change.
What makes this especially odd is that changing any vertical padding by more than the height of the view (for height 20 can have left and right of 10 or horizontal of 20) makes the text respect the horizontal padding changes.

#### What I expected
When changing the horizontal padding, the text should change position to respect the padding.

### Reproduction Steps

Using the sample code below...
1. Note the two TextInput fields have space between the text and border
2. Click or tap the first field to give it focus
3. Note that text changes to red, but there is still padding between the text and border
4. Open the inspector and click the focused field
5. Note that the content area (blue) fills the entire text view (showing 0 padding)
6. Click the unfocused field
7. Note the padding area (green) fills up the empty area next to the text

#### Sample Code

Run the code below on iOS and switch focus between the two text inputs. Opening the inspector shows that the padding is updated, but the text itself doesn't actually update its position.

https://snack.expo.io/S1B3TZv7Z

### Solution

The ideal fix is to make sure horizontal padding updates are respected, even if it is on one axis. The issue doesn't seem to lie within what React thinks the view should look like, but instead with the actual iOS view code.

### Additional Information

* React Native version: 0.45.0
* Platform: iOS 10.2
* Development Operating System: macOS Sierra 10.12.5
* Build tools: XCode 8.2.1

**Comment by davidlongest** [comment]
Verified still happens in 0.46.0

**Comment by atlanteh** [comment]
Yep, happens to me too

**Comment by inevermore** [comment]
happens to me too in 0.47
