### ISSUE TITLE
Cannot read property 'string' of undefined | React.PropTypes | LayoutPropTypes.js

### ISSUE THREAD

**Issue by gyetvan-andras** [facebook/react-native#14643]
After deleting and reinstalling my node_modules folder, I'm facing an issue that I don't understand in LayoutPropTypes.js file.

In node_modules/react-native/Libraries/StyleSheet/LayoutPropTypes.js
The following variable is undefined : var ReactPropTypes = require('React').PropTypes;

react-native: 0.45.1
react: 16.0.0-alpha.12

Hey @hramos , don't close this issue giving an advice to search for solution on StackOverflow. It is a critical issue. My whole development is down because of this. And of course, first I tried to look an answer on StackOverflow, the only answer is to use ```prop-types``` package, but HOW in RN source?!

**Comment by hramos** [comment]
Did you try Reactiflux? If you really think this belongs in the issue tracker, at least make an effort to fill out the template. Thanks!
