### ISSUE TITLE
Problem when i use padding style it's difference on Android - iOS

### ISSUE THREAD

**Issue by boyinfotronics** [facebook/react-native#14655]
Problem when i use padding style it's difference on Android - iOS

`<Content  style={{padding: '7%'}}>`

how can i take it in same style

[](https://i.imgur.com/IDmQX5p.jpg)

![differenc](https://user-images.githubusercontent.com/25657869/27378553-78c667c2-56a2-11e7-9c82-2bf5f73e1526.png)

**Comment by omar-dev** [comment]
Hi please follow the issue templete to help the maintainers solve your problem. You can find it on this link [issue templete](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
