### ISSUE TITLE
Thousands of Views being rendered after upgrading RN

### ISSUE THREAD

**Issue by aurnik** [facebook/react-native#14668]
### Description

In the Perf Monitor my View count went from ~350 to 7000+ after upgrading React Native.

### Reproduction Steps

My only steps were upgrading from RN 0.43.3 to 0.45.

#### Sample Code

My code didn't actually change, I can try to provide code as needed but I really don't know where the problem is coming from.

### Solution

I'm looking to see if anyone else has had this issue, it's a little unusual because the upgrade has caused my entire app to significantly fall back in performance. Even dismissing warnings has a 3+ second lag sometimes.

### Additional Information

* React Native version: 0.45
* Platform: iOS
* Development Operating System: macOS
* Build tools: WebStorm / iOS 10.2

**Comment by aurnik** [comment]
I just downgraded to 0.44.3 and the number of views has once again gone down to <500

**Comment by xilonxiao** [comment]
@aurnik I'm having a similar problem after upgrading from 0.44.3 to 0.45.1. My app overall performance dropped drastically. Are you using flatlist? In my case flatlist seem to be the problem, but I'm not sure. I even rolled back and got my performance back. But I don't think it is ideal to stay on a outdated version of RN.

**Comment by aurnik** [comment]
@xilonxiao I agree that it isn't ideal, but unfortunately it seems that none of the recent updates for RN are fully suitable for complex apps. I was never able to solve this.
