### ISSUE TITLE
FlatList ItemSeparatorComponent not work correctly.

### ISSUE THREAD

**Issue by dooubsam** [facebook/react-native#14661]
### Description

for some reason, when I try horizontal true for ItemSeparatorComponent in FlatList, I get vertical results. Can anyone help?

#### Sample Code

```js
import React from 'react';
import { FlatList, StyleSheet, Text, View } from 'react-native';

class App extends React.Component {
    constructor() {
        super();

        const arr = [];
        for(let i=0; i<100; i++)
            arr.push({key: i, value: i});
        this.state = {data: arr};
    }

    render() {
        return (
            <View style={ styles.container }>
                <FlatList
                    horizontal
                    ItemSeparatorComponent={ () => <View style={ { width: 10, height: 10, backgroundColor: 'red' } } /> }
                    data={ this.state.data }
                    renderItem={ (rowData) => <Text>{ rowData.item.value }</Text> }
                />
            </View>
        );
    }
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
    },
});
```

![screen](https://user-images.githubusercontent.com/24642237/27385567-1dea2f4c-56ce-11e7-83b2-49c47e3a3cbc.png)

### Additional Information

* React Native version: 0.45.1
* React: 16.0.0-alpha.12
* Platform: ios. not checked android.
* Development Operating System: macOS
* Build tools: WebStorm

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.

**Comment by dooubsam** [comment]
No. This is a BUG. It works perfect in RN 0.44

**Comment by dooubsam** [comment]
@hramos This is a BUG. It works perfect in RN 0.44

**Comment by basketofsoftkittens** [comment]
+1

**Comment by hramos** [comment]
If this is a bug, feel free to open a new issue, making sure to follow the template.

**Comment by ZainaliSyed** [comment]
![screenshot_1501590643](https://user-images.githubusercontent.com/24393023/28825567-30c6c7b0-76e0-11e7-9327-0be583b69e5a.png)
![screenshot_1501590649](https://user-images.githubusercontent.com/24393023/28825565-30c33906-76e0-11e7-856d-192a82f205d0.png)
![screenshot_1501590665](https://user-images.githubusercontent.com/24393023/28825566-30c4046c-76e0-11e7-8eb5-5d776c30615c.png)
Code Working for me

**Comment by lsps9150414** [comment]
@ZainaliSyed Could you share your code?
