### ISSUE TITLE
It will be impossible to create a class with extend?

### ISSUE THREAD

**Issue by AdrianZghibarta** [facebook/react-native#14662]
Hi guys,

As I saw from the updates that will be implemented in react version 0.16 [link](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.createclass) ... we will need to use `create-react-class` in order to create a new component for our project.
My question is.. how I can use the ES6 syntax with `class MyComponents extends React.component ...` in that case, I dont want to use `createReactClass`.

**Comment by hramos** [comment]
You can already use the ES6 syntax. That announcement only applies to code that uses the old createClass API.

**Comment by AdrianZghibarta** [comment]
That's great. Thanks :)
