### ISSUE TITLE
console.err:"You cannot render into anything but a top root"

### ISSUE THREAD

**Issue by jerboy** [facebook/react-native#14674]
<details>
   When I add ReactRootView to my ViewGroup then ReloadJS, and I got this.

**Comment by budiga** [comment]
I got this too.Any idea?

**Comment by kmiloarguello** [comment]
This can be help you. [Issue 14717](https://github.com/facebook/react-native/issues/14717)

**Comment by Katakeyni** [comment]
I have the same error. It  happens when it's reloading after a change and I click in button. I am sure but It may be the root is not fully rendered.
