### ISSUE TITLE
[Bridge] How to remove a UIView via a bridge method?

### ISSUE THREAD

**Issue by the4dpatrick** [facebook/react-native#1467]
I have a view controller with two views (Banner Ad and React View). I would like to be able to remove the banner ad view from within the react native code calling a bridged method of some sort. 

Could someone steer me in the right direction on how to do this?

**Comment by brentvatne** [comment]
Hi @the4dpatrick - this is the type of question better suited for StackOverflow or IRC - if you don't have any luck there, feel free to open an issue.
