### ISSUE TITLE
init a new project and build failed

### ISSUE THREAD

**Issue by zhenliliu** [facebook/react-native#14677]
init ad new  project and have a problem with 
/*Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist*/

this is package.json 

"dependencies": {
    "react": "16.0.0-alpha.12",
    "react-native": "^0.45.1"
  },
  "devDependencies": {
    "babel-jest": "20.0.3",
    "babel-preset-react-native": "2.0.0",
    "jest": "20.0.4",
    "react-test-renderer": "16.0.0-alpha.12"
  },
  "jest": {
    "preset": "react-native"
  }

**Comment by housecricket** [comment]
same problems. pls help.

**Comment by maestunfox** [comment]
Seems to be related to a boost lib config error error:
my_project/node_modules/react-native/third-party/boost_1_63_0/boost/config.hpp:30:12: 'boost/config/user.hpp' file not found

The my_project.app cannot be created, thus the Info.plist file cannot be found.

**Comment by 452MJ** [comment]
@maestunfox same problem to me. How to fix it?(〒︿〒)

**Comment by hramos** [comment]
Duplicate of #14423
