### ISSUE TITLE
Unable to resolve module

### ISSUE THREAD

**Issue by Vinu-MysteriousTechVision** [facebook/react-native#14687]
### Description

Install the node module **npm install open-graph-scraper**. and import the 

> var ogs = require('open-graph-scraper'); 

getting Error

_**Error:**_ 
```
Loading dependency graph, done.
error: bundling: UnableToResolveError: Unable to resolve module url from ../SampleOGP/node_modules/open-graph-scraper/app.js:
Module does not exist in the module map or in these directories:
../SampleOGP/node_modules/open-graph-scraper/node_modules
, ../SampleOGP/node_modules
```
### Additional Information

* React Native version: 0.45.1
* Platform: iOS
* Development Operating System: macOS
* Build tools: x-code

> **Following steps are done but not use**
> 
> - Clear watchman watches: watchman watch-del-all.
> - Delete the node_modules folder: rm -rf node_modules && npm install.
> - Reset packager cache: rm -fr $TMPDIR/react-* or npm start -- --reset-cache.

**Comment by kaykie** [comment]
然并卵。
建议把版本切换到0.42，这个问题我研究了3天也看不明白

**Comment by hramos** [comment]
I'm not sure this is an issue related to React Native. If it's a packager issue, you can try the `facebook/metro-bundler` repo.
