### ISSUE TITLE
Crash when loading two react bundles

### ISSUE THREAD

**Issue by supriyasaha** [facebook/react-native#14685]
I am trying to load two different react native bundles in two fragments in a view pager.
So, I use two instances of ReactInstanceManager to load the individual bundles.
When one instance of ReactInstanceManager is running the bundle works fine, but when two bundles are loaded parallelly with two react instance manager running parallelly the react code crashes. Below is the stacktrace of the crash:

The react code is as follow: 
```
export default class test extends Component {
  render() {
        var views = [];
        for (var i = 0; i < 1000; i++) {
            views.push(<Text key={i}>Testing </Text>)
        }

        return (
            <ScrollView>
                <View >
                    {views}
                </View>
            </ScrollView>
        );
  }
}
```

The same code when loaded twice parallelly with two reactinstancemanager it crashes.

> com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'onLayout' in shadow node of type: RCTView  at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:109) at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(ViewManagerPropertyUpdater.java:150)  at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:52)at com.facebook.react.uimanager.ReactShadowNode.updateProperties(ReactShadowNode.java:176)
> at com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:152)
>                                                      at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:200)
>                                                      at java.lang.reflect.Method.invoke(Native Method)
>                                                      at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319)
>                                                      at com.facebook.react.bridge.NativeModuleRegistry$ModuleDefinition.call(NativeModuleRegistry.java:187)
>                                                      at com.facebook.react.bridge.NativeModuleRegistry.call(NativeModuleRegistry.java:62)
>                                                      at com.facebook.react.bridge.CatalystInstanceImpl$NativeModulesReactCallback.call(CatalystInstanceImpl.java:432)
>                                                      at com.facebook.react.bridge.queue.NativeRunnableDeprecated.run(Native Method)
>                                                      at android.os.Handler.handleCallback(Handler.java:751)
>                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
>                                                      at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
>                                                      at android.os.Looper.loop(Looper.java:154)
>                                                      at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:193)
>                                                      at java.lang.Thread.run(Thread.java:761)
>                                                   Caused by: java.lang.IllegalArgumentException: method com.facebook.react.uimanager.LayoutShadowNode.setShouldNotifyOnLayout argument 1 has type boolean, got java.lang.Float
>                                                      at java.lang.reflect.Method.invoke(Native Method)
>                                                      at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:99)
>                                                      at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(ViewManagerPropertyUpdater.java:150) 
>                                                      at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:52) 
>                                                      at com.facebook.react.uimanager.ReactShadowNode.updateProperties(ReactShadowNode.java:176) 
>                                                      at com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:152) 
>                                                      at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:200) 
>                                                      at java.lang.reflect.Method.invoke(Native Method) 
>                                                      at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319) 
>                                                      at com.facebook.react.bridge.NativeModuleRegistry$ModuleDefinition.call(NativeModuleRegistry.java:187) 
>                                                      at com.facebook.react.bridge.NativeModuleRegistry.call(NativeModuleRegistry.java:62) 
>                                                      at com.facebook.react.bridge.CatalystInstanceImpl$NativeModulesReactCallback.call(CatalystInstanceImpl.java:432) 
>                                                      at com.facebook.react.bridge.queue.NativeRunnableDeprecated.run(Native Method) 
>                                                      at android.os.Handler.handleCallback(Handler.java:751) 
>                                                      at android.os.Handler.dispatchMessage(Handler.java:95) 
>                                                      at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) 
>                                                      at android.os.Looper.loop(Looper.java:154) 
>                                                      at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:193) 
>                                                      at java.lang.Thread.run(Thread.java:761) 

The link to the source code of the android project: [Click here](https://github.com/supriyasaha/reactnative)
The link to the source code of the react  project I am trying to load: [Click here](https://github.com/supriyasaha/react)

**Additional Information**

React Native version: [0.45.1]
Platform: [Android]
Development Operating System: [macOS]
Build tools: [Android Studio 2.3, Android SDK 25

Attached  apk: [Click here](https://www.dropbox.com/s/wm0lnaikx7afpru/app-debug.apk?dl=0)

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by lizouzt** [comment]
@supriyasaha  is this problem solved? I have meet this problem too.

**Comment by hramos** [comment]
I recommend filing a new issue and filling out the template if you're still seeing this.

**Comment by xiyouMc** [comment]
I add postDelayed(), fixed it

**Comment by oximer** [comment]
@xiyouMc where you add 'postDelayed'?
