### ISSUE TITLE
fetch has weird behavior for 0.45.1 when debugger is attached

### ISSUE THREAD

**Issue by cbrevik** [facebook/react-native#14681]
### Description

I've upgraded one of our apps to `0.45.1` (from `0.42.3`) and `fetch` has some weird behaviour when attaching the Chrome debugger. The `Promise` with the Response returns as normally. What is weird is if I try to return any of the `Promise`s from the Response, e.g. `response.text()`, then I must touch/click the UI in order for it to continue.

For example, this works fine:
```javascript
fetch('https://github.com/facebook/react-native')
  .then((res) => console.log(res));
```

It will log the Response-object when the GET completes. But if I add another `then` to return for example the text of the response:
```javascript
fetch('https://github.com/facebook/react-native')
  .then((res) => res.text())
  .then((text) => {
    console.log(text)
  });
```

Then I must touch/click the UI in order for it to run the last `then`. 

If I set a break point into the function which handles the console.log, I even see from the call-stack that it is `callFunctionReturnFlushedQueue` with the touch-event as scope variables which triggers the `Promise` resolution:
![image](https://user-images.githubusercontent.com/4932625/27431493-0aa89c46-574d-11e7-9c7d-05b07f0eda02.png)

### Reproduction Steps

1. Download the below sample project. Important file is `Core.js`.
2. Run the app. Note that the UI quickly goes from "Not done" -> "Done :D"
3. Attach debugger, reload app. Note that it stays on "Not done".
4. Click the UI, it should go to "Done :D".

#### Sample Code

[Sample project here](https://github.com/cbrevik/jsFetch).

### Additional Information

* React Native version: 0.45.1
* Platform: Both
* Development Operating System: macOS
* Build tools: Both iOS/Android.

**Comment by neiker** [comment]
Same here on RN 0.45.1

I changed res.text to res.json just to check it and the behavior is the same

**Comment by neiker** [comment]
This seems to be duplicated:
https://github.com/facebook/react-native/issues/14391
https://github.com/facebook/react-native/issues/6679

**Comment by cbrevik** [comment]
I think that this is a more general problem with the event loop and attaching the Chrome debugger. 

For example a standalone `setTimeout(() => console.log("Hello"), 3000);` will not log after three seconds with the debugger attached. If you lower the timeout to 1 second though, then it still logs with the debugger attached.

Weird thing is though, that if I have two concurrent timeouts, for example:
```javascript
setTimeout(() => console.log("Hello"), 1000);
setTimeout(() => console.log("Hello again"), 3000);
```

Then it will log both. Seems like the event loop is falling asleep as @mikelambert says in https://github.com/facebook/react-native/issues/14391#issuecomment-308932709, and the first timeout keeps the second timeout "awake".

**Comment by cbrevik** [comment]
So, I have a bit stronger suspicion that it is "sleep" related. 

If you debug the app in Xcode, and set a break point in [createTimer](https://github.com/facebook/react-native/blob/d795fa1b2c2eed7b46a759acd1295fce59d47946/React/Modules/RCTTiming.m#L282) (used by `setTimeout`, `setInterval`, etc), it will only break into it a couple of times, using RN `0.45.1` and the Chrome debugger attached. 

While if you do not have the debugger attached, then it will break into that method and create a new timer every two seconds.

Testing the same code with RN `0.44.3`, it always break into the method every two seconds, regardless if the debugger is attached or not.

Turns out `createTimer` is in this case called from [`setTimeout`](https://github.com/facebook/react-native/blob/c848c3820b21205f66f5756e29ba38b17ec994d0/Libraries/Core/Timers/JSTimers.js#L208-L228), which has the following stack trace:

![image](https://user-images.githubusercontent.com/4932625/27864583-73519314-618f-11e7-9a4b-263d841618d5.png)

Drilling into the arguments of the bottom of the stack I find:
![image](https://user-images.githubusercontent.com/4932625/27864644-ad1a84a2-618f-11e7-90a2-b94cf6b2958b.png)

`websocketFailed` in turn seems to be related to `RCTWebSocket` connection failing. Which is called [here](https://github.com/facebook/react-native/blob/047961fbf77cb012b53978184102e8ca3d00c7ec/Libraries/WebSocket/RCTWebSocketModule.m#L134). If you set a break point into that method you see the same behaviour, it will not break into it every two seconds in RN `0.45.1` with Chrome debugger attached.

Wondering if it might be related to #10027, and any fixes done there? Not a lot of info to go on in that issue.

Or, I might be completely wrong here. But that's as far as I've gotten thus far.

**Comment by cbrevik** [comment]
@javache Just wondering if any commits related to #10027 landed in `0.45.0`?

Been having difficulty tracking it down, but seems like something happened related to timers, and the debugger being attached. Possibly also related to `RCTWebSocket` (see above comment). 

I might be barking up the wrong tree here, but would be nice to cross it off the list. :)

**Comment by mikelambert** [comment]
I assume you read https://github.com/facebook/react-native/issues/9436#issuecomment-302868758 ? That's the most promising avenue I've seen yet, though it's personally not high enough on my radar for me to dig in...

**Comment by javache** [comment]
I believe I fixed this in https://github.com/facebook/react-native/commit/64825389dfb4e01d5b30cd63b0b41937a9bb431d which is in v0.47.

**Comment by cbrevik** [comment]
@mikelambert I read that comment but it seemed (at first glance) like the fix was Android-specific?

@javache Thanks! Did a simple test with `0.47.0-rc.1`, seems like that commit fixed it. Closing this issue.
