### ISSUE TITLE
When I build from master there's no android directory being created.

### ISSUE THREAD

**Issue by SudoPlz** [facebook/react-native#14689]
Hey there.

I'm installing react native by using 
`npm i react-native@facebook/react-native#7d1981ef8245cd6267823a970054cbebb2d2fd14`

but after that there's no `node_modules/react-native/android/` directory at all, therefore there's no maven local repo to build from.

Why is that? Is the `android` directory automatically created? Is some script failing to run?

Thanks.

**Comment by SudoPlz** [comment]
Nevermind, I had to read [this](https://facebook.github.io/react-native/releases/next/docs/android-building-from-source.html) more carefully.

**Comment by SudoPlz** [comment]
I still have a problem
```java
Gradle sync failed: No such property: sdkHandler for class: com.android.build.gradle.LibraryPlugin
```

specifically in the file https://github.com/facebook/react-native/blob/master/ReactAndroid/build.gradle#L171

but it seems to be related with https://github.com/facebook/react-native/pull/14136

**Comment by hramos** [comment]
Issues is probably not the best place to troubleshoot this. Maybe try Reactiflux for real time feedback?

**Comment by SudoPlz** [comment]
Got it.
