### ISSUE TITLE
[FlatList] ItemSeparatorComponent bug.

### ISSUE THREAD

**Issue by dooubsam** [facebook/react-native#14680]
### Description

When I set horizontal true for FlatList, ItemSeparatorComponent is added vertically.

#### Sample Code

```js
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  FlatList
} from 'react-native';

export default class flatlist_bug extends Component {
  constructor() {
      super();

      const arr = [];
      for(let i=0; i<100; i++)
          arr.push({key: i, value: i});
      this.state = {data: arr};
  }

  render() {
      return (
          <View style={ styles.container }>
              <FlatList style={{marginTop: 100, paddingHorizontal:30, backgroundColor:'yellow', height:20}}
                  horizontal
                  ItemSeparatorComponent={ () => <View style={ { width: 10, height: 10, backgroundColor: 'red' } } /> }
                  data={ this.state.data }
                  renderItem={ (rowData) => <Text style={{backgroundColor:'blue'}} >{ rowData.item.value }</Text> }
              />
          </View>
      );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
```

![2017-06-22 6 48 32](https://user-images.githubusercontent.com/24642237/27427978-a777804a-577b-11e7-94fa-fbd72627616e.png)

### Additional Information

* React Native version: 0.45.1
* React: 16.0.0-alpha.12
* Platform: ios. not checked android.
* Development Operating System: macOS

**Comment by hramos** [comment]
Thanks for reporting these - can you file separate issues for each bug?

**Comment by I-ad** [comment]
![image](https://user-images.githubusercontent.com/16728559/27477329-a7705f14-57c0-11e7-81d9-106359d637a1.png)



same here, its happen after update RN to 45.0.1

**Comment by hramos** [comment]
Closing this issue as we haven't heard back from the author.

**Comment by lsps9150414** [comment]
Having the exact same issue. @hramos Could you reopen this?

**Comment by lsps9150414** [comment]
@hramos Having the exact same issue. Could you reopen this?

**Comment by hramos** [comment]
I'd rather see a new issue being opened with up to date details. Easier to manage.

**Comment by yozel** [comment]
@hramos I have opened a new issue: #15777

**Comment by HernanAA** [comment]
That also happen to me:
Android Emulator
Windows
"react": "16.0.0-alpha.12",
"react-native": "0.48.3",
![image](https://user-images.githubusercontent.com/7015591/31787648-ca1b5d32-b4e2-11e7-8261-d35005924977.png)
