### ISSUE TITLE
KeyboardAvoidingView Warnings

### ISSUE THREAD

**Issue by Ethan0007** [facebook/react-native#14692]
Hi,

I'm using 0.43 react-native it shows warnings when I used KeyboardAvoidingView  in my login form.

![image](https://user-images.githubusercontent.com/12542052/27467709-49721310-5817-11e7-9f3c-02c468533575.png)

Please be advised.

#Thanks

**Comment by DealPete** [comment]
Why was this closed? I'm getting the warnings too. From looking at the source, it appears that KeyboardAvoidingView uses deprecated react-native features.

**Comment by Ethan0007** [comment]
@DealPete sir, i have a temporary fix on this by adding the this line of code:
 console.disableYellowBox = true

**Comment by carlesnunez** [comment]
Same problem here.

Disabling yellow box is not the clean way OFC, we need some feedback here please.

**Comment by yidc** [comment]
I'm using react-native v0.45.1 and I got another yellow warning saying "checkPropTypes has been moved to a separate package". Could somebody please reopen this issue?

**Comment by hramos** [comment]
It looks like the description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

Feel free to open a new issue with the additional information provided. Thanks!

**Comment by yidc** [comment]
Another similar thread has mentioned that this will be fixed on 0.46, so I will just ignore this from now...

**Comment by Ethan0007** [comment]
Hi,

I think this is related to this issue.
https://github.com/facebook/react-native/issues/14381
