### ISSUE TITLE
RCTPushNotificationManager does not set alertTitle in UILocalNotification

### ISSUE THREAD

**Issue by stage88** [facebook/react-native#14699]
### Description

Setting the alertTitle property on PushNotificationIOS.scheduleLocalNotification does not display the title in the notification.

With alertTitle set:
![image](https://user-images.githubusercontent.com/9906800/27482779-1ca92900-5866-11e7-8578-1afed9a5843d.png)

Without:
![image](https://user-images.githubusercontent.com/9906800/27482878-8083cc28-5866-11e7-8d69-6f4455fc4351.png)

### Reproduction Steps

Use the below code to reproduce.

#### Sample Code

`
PushNotificationIOS.scheduleLocalNotification({
      fireDate: new Date(Date.now() + (30 * 1000)).toISOString(),
      alertTitle: 'Incoming Message',
			alertBody: 'This is my message, please read it for good fortune.',
			soundName: 'default',
			applicationIconBadgeNumber: 1,
			userInfo: {
        id: 11
      }
    })
`

### Solution

Adding the following line in RCTPushNotificationManager.m (54) fixes the issue:

`notification.alertTitle = [RCTConvert NSString:details[@"alertTitle"]];`

### Additional Information

* React Native version: 0.45
* Platform: iOS
* Development Operating System: macOS Sierra 10.12.15
* Build tools: XCode 8.3.3

**Comment by hramos** [comment]
Can you send a PR?

**Comment by hramos** [comment]
Tagging as a Good First Task. A solution is provided in the original post above. People can get familiar with the contribution process by applying the fix in a PR.

**Comment by tinajohnson** [comment]
@hramos I'm ready to create a PR as I'm new to the contribution process and is essential for me to get to know the process.

**Comment by stage88** [comment]
Great work on this guys, thanks!

**Comment by cpojer** [comment]
This issue has been moved to react-native-community/react-native-push-notification-ios#2.
