### ISSUE TITLE
Setting an array as a component state property cause an error

### ISSUE THREAD

**Issue by ramsestom** [facebook/react-native#14705]
When trying to set a non empty array as a component state property, like for example:

`
this.state = {
      results: ['apple','orange']
 }
`

this error is returned: 

`In this environment the sources for assign MUST be an object.This error is a performance optimization and not spec compliant`

If the array is empty though, that works (but as soon as you try to reasign a non empty array, it would bug)

So this works:

`
this.state = {
      results: []
 }
`
until you do 

`
this.setState({results: ['apple','orange'] }),
`

at which point the previous error would be returned...

This is with the latest react-native version (0.45.1). Tested on android

**Comment by hramos** [comment]
It's not clear that this is a React Native issue. What you're describing concerns React. If you think this should remain open, please file a new issue and make sure it follows the template guidelines.

**Comment by fungilation** [comment]
I'm not sure this is entirely React's fault, when I'm seeing it now just testing on Android:
```javascript
				<View
					style={[
						styles.stickyHeader,
						{
							width: viewWidth,
							...(stickyHeaderHeight ? { height: stickyHeaderHeight } : null),
						},
					]}
				>
...
```
<img width="471" alt="screenshot 2018-05-03 22 46 43" src="https://user-images.githubusercontent.com/3803466/39614811-81364a8e-4f27-11e8-9721-a5d37b7ea2c8.png">

By process of elimination, I tried taking out components that included the offending line that triggered the same `In this environment the sources for assign MUST be an object...` error. I take one component out, another component gives the same error. (above snippet is one sample of where error triggers)

Why I say this is a React Native issue is that I've never seen this on iOS. Only on Android. If it's a React issue, how can this happen in multiple components only on Android?
