### ISSUE TITLE
Support iOS accessibilityValue and accessibilityHint

### ISSUE THREAD

**Issue by randyzhao** [facebook/react-native#14706]
Currently we only support `accessibilityLabel`. It would be great if we could also support [`accessibilityValue` ](https://developer.apple.com/documentation/objectivec/nsobject/1615117-accessibilityvalue?language=objc) and [`accessibilityHint`](https://developer.apple.com/documentation/objectivec/nsobject/1615093-accessibilityhint) for iOS.

Platform: iOS

**Comment by hramos** [comment]
Thanks for opening the issue, however it looks like a feature request. As noted in the [Issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md) we'd like to use the GitHub issues to track bugs only. Can you implement the feature as a standalone npm module? If not consider sending a pull request or a create an entry on [Canny](https://reactnative.canny.io/feature-requests). It has a voting system and if the feature gets upvoted enough it might get implemented by someone from the community. Closing this now, thanks for understanding!

**Comment by cannona** [comment]
I do not believe that this is a feature, unless accessibility in general is considered a feature. This is a basic part of the accessibility API of IOS, and is necessary for making some types of interactions accessible.
