### ISSUE TITLE
Cannot read property 'string' of undefined | React.PropTypes | LayoutPropTypes.js

### ISSUE THREAD

**Issue by Jonovono** [facebook/react-native#14709]
Seems to be crashing with:

```
    "react": "^16.0.0-alpha.12",
    "react-native": "^0.45.1",
```

I think it's because they are still using `var ReactPropTypes = require('React').PropTypes;` instead of the prop types file?

**Comment by hramos** [comment]
Known issue. We're tracking a fix in #14712, #14713.
