### ISSUE TITLE
You cannot render into anything but a top root

### ISSUE THREAD

**Issue by Symous** [facebook/react-native#14717]
### Description

I have met this error irregularly after I update RN to 0.45.1
### Reproduction Steps

Modify any code of the program and "Reload".

### Solution

Just reload again and the error will disappear.

### Additional Information

* React Native version:0.45.1
* Platform: Android 
* Development Operating System: Windows 10 64 bit

**Comment by kmiloarguello** [comment]
Thank you!

**Comment by HelloEdit** [comment]
Hello,

I'm on 0.46.0-rc.2, using Ignite-CLI and boiterplate.
This error doesn't disappear when I reload my app...

**Comment by Symous** [comment]
@kmiloarguello Please I do not know the reason why this error occured.Is it a bug of RN and Is there any way to solve this for good?

**Comment by jetzhliu** [comment]
I have met this error in RN 0.46-rc2 on Android emulator and real machine.
But when I downgrade RN to 0.45.1, this error disappears.

**Comment by HelloEdit** [comment]
Thank, I will try later

**Comment by kmiloarguello** [comment]
@Symous I thought it would be an Android emulator error maybe when React Native builds the package but really I don't know... Actually I get this error sometimes but I just reloading again solve the problem.

**Comment by HelloEdit** [comment]
I get this error on physical device (O+ 3T 7.1.1)

**Comment by fredbt** [comment]
I get this error when react-native packager dies (see https://github.com/facebook/react-native/issues/12895).

**Comment by yash2code** [comment]
same issue

**Comment by ecasona** [comment]
I have got this error  for more times in RN 0.45.1 when I reload my project,but try again ,it solved.

**Comment by ricbermo** [comment]
I'm using Expo SDK 18, which is based on NR 0.45 and for me the only way to workaround this issue is to open remote debugger

**Comment by Farzad7** [comment]
Same issue here, after React Native 0.46 was released yesterday I downloaded and configured everything to what React Native suggests, Node v6.11 and downgraded npm from 5 to 4
Download Expo and opened emulator, started the app and in the Expo clicked on Device

Everything works but this error intermittently occurs and it's very annoying!
Hope they fix this annoyable bug ASAP

**Comment by Farzad7** [comment]
As of today 7th July, the best way round this problem is to enable "Remote JS Debugger" from your emulator "Ctrl + M"
Hope it helps

**Comment by nimamyscreen** [comment]
I get this error (real device) when I try to dismiss a modal and I have to say I'm using react-native-navigation lightbox
```
  <TouchableOpacity style={{alignSelf: 'flex-end',}} activeOpacity={0.6} onPress={this.props.navigator.dismissLightBox.bind(this)}>
                    <Text style={{ padding: 16, color: 'orange'}}>CANCEL</Text>
</TouchableOpacity>
 
```

**Comment by lipingruan** [comment]
@nimamyscreen 

https://github.com/wix/react-native-navigation/issues/1502

**Comment by hemedani** [comment]
this hackThis hacky by @rawrmaan fixed for me 
change the `destry` method on `node_modules/react-native-navigation/android/app/src/main/java/com/reactnativenavigation/views/LightBox.java`
```java
    public void destroy() {
        // content.unmountReactView();
        dismiss();
    }
```
tank you man

**Comment by christoshrousis** [comment]
Above fix doesn't resolve for me on 
```
"react-native": "0.46.4",
"react-native-navigation": "^1.1.230",
```

**Comment by hemedani** [comment]
@christoshrousis you should reinstall app on devices
