### ISSUE TITLE
[0.46] Commits to cherry-pick

### ISSUE THREAD

**Issue by hramos** [facebook/react-native#14713]
##  Fix: use prop-types with React 16

> `react@16` (a `peerDependency`) did away with the `PropTypes` export in favor of the `prop-types` module.

The issue has been fixed in master. I don't think the fix made the 0.46-RC cut, so we'll also need to cherry-pick them into v0.46.0-rc.3.

## Fix dev reloading on Android

* c639a1f - fix dev reloading - related to #14533

**Comment by mojodna** [comment]
Commits to cherry-pick:

* 50b11aa09b479e5ce8b06de98e02ba1dd6a8cca3
* 8e9322c65e751dc8e7512874e03e7c4349a28b93

**Comment by AndrewJack** [comment]
https://github.com/facebook/react-native/commit/c639a1f802d8da58405ac5132ed75b8a0e9ac032 - fix dev reloading - related to https://github.com/facebook/react-native/issues/14533

**Comment by hramos** [comment]
@AndrewJack Is c639a1f related to the prop-types issue?

**Comment by AndrewJack** [comment]
@hramos No it fixes Android DEV reloading and an issue with code push. It was fixed just after 0.46 cut.

**Comment by hramos** [comment]
Gotcha, it doesn't look like this is in the 0.46 RC as you mentioned, cherry picking it into 0.46 should help us prevent more issues getting opened about it. I updated this issue to cover all commits that we want to be cherry picked into 0.46

cc @grabbou to be aware, I am planning on cherry picking these once I get https://github.com/facebook/react-native/pull/14729 merged.

**Comment by grabbou** [comment]
https://github.com/facebook/react-native/commit/4fd427e249d39c1ed6d136019c362a6edcba2d3f to be cherry-picked from another issue

**Comment by grabbou** [comment]
All commits were cherry-picked. Going to close this issue and we will land #14729 separately.

**Comment by hramos** [comment]
It's failed all the open source tests that we currently run internally. I haven't been able to look at this between the long holiday weekend and moving to a new place.

**Comment by grabbou** [comment]
I understand. Do you think there's anybody from FB that has some time
upcoming days to assist me with landing it? Sounds reasonable to get this
fixed before promoting RC to stable.

**Comment by gre** [comment]
I wish https://github.com/facebook/react-native/commit/ee42cd092894a3084d20979f85fef9c4ef247d22 was picked in 0.46, sounds safe to add, is it still time for a patch?
thanks

**Comment by hramos** [comment]
Re-opening for 0.46.3 release.

* 5c53f89dd86160301feee024bce4ce0c89e8c187 nominated by @janicduplessis to address compiling issues when running on device
* ee42cd092894a3084d20979f85fef9c4ef247d22 nominated by @gre, fixes https://github.com/facebook/relay/issues/1866

**Comment by hramos** [comment]
v0.46.3 has been cut and will be released once https://circleci.com/gh/facebook/react-native/19569 finishes.

**Comment by ujwal-setlur** [comment]
Critical iOS fix is needed: 

https://github.com/facebook/react-native/commit/5c53f89dd86160301feee024bce4ce0c89e8c187

**Comment by ujwal-setlur** [comment]
Looks like it got included. Thanks!

**Comment by ujwal-setlur** [comment]
If we have a 0.46.4, please include https://github.com/facebook/react-native/commit/7d1981ef8245cd6267823a970054cbebb2d2fd14

**Comment by grabbou** [comment]
Releasing and closing this issue, thanks!
