### ISSUE TITLE
Can WebView provide a method to execute scripts and callback the result?

### ISSUE THREAD

**Issue by RonnieRen** [facebook/react-native#14726]
I am using WebView to show a html5 page, a requirement for me is to execute a script and callback me the result when page is loaded.
so far WebView only provide a property(injectJavaScript) to execute a script, but does not provide a way to get the result .
could you please enhance this with a callback so that I can get the result ?

**Comment by hramos** [comment]
Thanks for opening the issue, however it looks like a feature request. As noted in the [Issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md) we'd like to use the GitHub issues to track bugs only. Can you implement the feature as a standalone npm module? If not consider sending a pull request or a create an entry on [Canny](https://reactnative.canny.io/feature-requests). It has a voting system and if the feature gets upvoted enough it might get implemented by someone from the community. Closing this now, thanks for understanding!

**Comment by kdastan** [comment]
@hramos any news, did react-native team add callback feature ?
