### ISSUE TITLE
Image with cookie?

### ISSUE THREAD

**Issue by cbjs** [facebook/react-native#14727]
### Description

some images need to be logged in to view. 
Image http request seems ignore the cookies. 

I try to use headers of Image source property to fix this problem.
It seems not work.

#### Sample Code

```js
let uri = 'http://url/of/image.jpg'
let headers = { Cookie: 'COOKIE STRING' }

<Image source={{ uri, headers}} />
```
### Solution

no.

### Additional Information

* React Native version: 0.45.1
* Platform: Android
* Development Operating System: MacOS

**Comment by hramos** [comment]
Is this supposed to work? Do you have a link to the docs?

**Comment by lodicolo** [comment]
https://facebook.github.io/react-native/docs/images.html#network-requests-for-images

This would allude to this being possible. I remember seeing this mentioned somewhere else in the docs as well, but found this specific mention first. (I personally haven't tried to see if this works or doesn't work.)

**Comment by hramos** [comment]
Got it, thanks for clarifying!
