### ISSUE TITLE
IOS Production Build

### ISSUE THREAD

**Issue by Ethan0007** [facebook/react-native#14739]
Hi,

We have a problem in our IOS Production build, our app can't connect in WIFI Connection or any request that we made, also we change the Scheme -> Run -> Build Configuration to Release, but in our Debug/Simulator mode our app is running correctly.

RN: 0.43

Please be advised.

#Thanks

**Comment by Ethan0007** [comment]
Issue Resolved -> Product -> Edit Scheme -> Archive -> Release to Debug

:)

**Comment by hellogerard** [comment]
We've encountered this problem too. Changing the Archive mode from Release to Debug works, but isn't really an option. This means that the app would run unminified, with warnings, and users would be able to shake the device to get the dev menu.
