### ISSUE TITLE
Picker on iOS needs explicit width set, documentation doesn't explain it

### ISSUE THREAD

**Issue by brentvatne** [facebook/react-native#14734]
### Description

Picker reference doesn't indicate that it requires width to be set explicitly. See: https://snack.expo.io/r1orbz1NZ for working example. Remove the width and notice it doesn't work.

### Solution

Explain that width is required for Picker on iOS.

### Additional Information

* React Native version: All with Picker
* Platform: iOS
* Development Operating System: macOS
* Build tools: Snack

**Comment by joshyhargreaves** [comment]
Forgive me for asking a potentially stupid question, but is worth asking the question, from a technical perspective, should it need an explicit width to be set?

**Comment by akshaynaik404** [comment]
Hey, guys! I am new to Open Source and want to dive into this issue. I also do not have any react-native experience, How should I go about solving this one?

**Comment by joshyhargreaves** [comment]
@brentvatne: this seems to fix it: https://github.com/facebook/react-native/compare/master...joshyhargreaves:fix_need_for_explicit_size_picker_ios?expand=1

**Comment by joshyhargreaves** [comment]
@akshaynaik404, wonderful it's great that you're getting involved 💯 . 😊

Your best place to start is to start building the react-native project from source and running the , [RNTester](https://github.com/facebook/react-native/tree/master/RNTester) example project. For an issue like this you can start playing around with the relevant native source files!

RCTPicker is where you'd start looking at here. Perhaps you'd put a breakpoint in the init method and verify you had the right class from loading the [PickerExample](https://github.com/facebook/react-native/blob/master/RNTester/js/PickerExample.js) in the RNTester project. 

Let me know how that goes for you and if you have any issues :).

**Comment by joshyhargreaves** [comment]
@brentvatne : I don't really have any idea though, [RCTDatePicker](https://github.com/facebook/react-native/blob/master/React/Views/RCTDatePicker.m) also seems to be initialised in the same way (with a default frame of 0,0,0,0).

**Comment by joshyhargreaves** [comment]
May actually have been a red herring, RNTester example seems to work without an explicit width set.

**Comment by GantMan** [comment]
@joshyhargreaves and @brentvatne - What's the plan?  I just verified this is an issue in React Native 0.46.2

I'll be happy to update the docs, or work with objective C to implement Josh's code etc.  Looks like this has had 2 weeks to sizzle, so feel free to ask me to implement if needed!

Cheers! 🍻

**Comment by joshyhargreaves** [comment]
Aha @gantman so my fix was in fact complete bogus, didn’t fix anything. Unless we have a fix, then probably no harm in documenting the defect for the time being. 

I’m still curious as why setting the width is actually necessary from a technical perspective...

**Comment by GantMan** [comment]
I might throw some energy into it, and fall back to just documenting.  Will report back.

**Comment by joshyhargreaves** [comment]
More than happy to work with you on this! I was starting by asking the question, why is it necessary for RCTPicker vs other ‘Native’ components

**Comment by GantMan** [comment]
@joshyhargreaves - how about a bandaid to make a default width until we have time to uncover?  I don't feel documenting this is a better path than a default width.  Thoughts?

**Comment by brentvatne** [comment]
@GantMan - the problem with a default width, if it is just something arbitrary, is that if we set that and then decide to change it, then it's a breaking change and people will potentially need to update their apps. I'd like to have a better solution than guessing an arbitrary width before actually making a code change

**Comment by hramos** [comment]
Closing now that the docs have been moved. Feel free to re-open at https://github.com/facebook/react-native-website
