### ISSUE TITLE
Can't release APK with RN 0.46.0-rc.2 (BASH subsystem and windows CMD)

### ISSUE THREAD

**Issue by HelloEdit** [facebook/react-native#14733]
I have tried to release APK with RN 0.46.0-rc.2 on windows,

Windows (CMD)
```
[...]
:app:mergeReleaseResources UP-TO-DATE
:app:bundleReleaseJsAndAssets FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Failed to capture snapshot of input files for task 'bundleReleaseJsAndAssets' property '$1' during up-to-date check.
> Failed to create MD5 hash for file 'C:\Users\coren\Documents\Lab\test\node_modules\.bin\format-json'.
```
So I try on bash subsytem

Windows (BASH sub):
```
[...]
:react-native-vector-icons:prepareReleaseDependencies
:react-native-vector-icons:compileReleaseAidl FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-vector-icons:compileReleaseAidl'.
> java.lang.IllegalStateException: aidl is missing

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Comment by HelloEdit** [comment]
This is my solution for this problem:

# Upgrade gradle
One essential thing is gradle, let's update it with the latest version.
> android/gradle/wrapper/gradle-wrapper

By default, it would look like this:
```
[...]
distributionUrl=https\://services.gradle.org/distributions/gradle-x.x-all.zip
```
let's change the url by the latest ([here for check version of gradle](https://services.gradle.org/distributions/))
At the time I write these lines, it looks like this
```
[...]
distributionUrl=https\://services.gradle.org/distributions/gradle-4.0-all.zip
```
Then, let's update the build.gradle file for update gradle **plugin**.
> android/build.gradle
```
[...]
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'
        // Check latest version here: https://developer.android.com/studio/releases/gradle-plugin.html#revisions


        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
```
# Update build tools
Then, to be compatible with the latest version of gradle, It will be necessary to update build tools.
For forcing extension to use the same build tools, we need to add additional code, which is very well explained [here](https://blog.bam.tech/developper-news/boost-compilation-time-react-native-android-app-latest-android-build-tools).
>android/build.gradle
```
[...]
ext {
    compileSdkVersion = 26 // Or what version you want (latest is recommended)
    buildToolsVersion = '26.0.0' // same thing
}

subprojects { subproject ->
    afterEvaluate{
        if((subproject.plugins.hasPlugin('android') || subproject.plugins.hasPlugin('android-library'))) {
            android {
                compileSdkVersion rootProject.ext.compileSdkVersion
                buildToolsVersion rootProject.ext.buildToolsVersion
            }
        }
    }
}
[...]
```
> android/app/build.gradle
```
[...]
android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion
[...]
```

I hope this will help you !
(It's really weird, I managed to build the app when I updated gradle, now it gives me AIDL is missing ...)

**Comment by damathryx** [comment]
i did all the steps. didnt work for me. still the same error on react-native-code-push

**Comment by giacomocerquone** [comment]
@HelloEdit why is this still unfixed? Who do we need to tag in order to bring attention to this long standing problem?
