### ISSUE TITLE
Need a way to enable packager to create JS bundle even when targeting iOS simulator in Debug mode

### ISSUE THREAD

**Issue by hiddentao** [facebook/react-native#14748]
### Description

In order to get testing with Appium, etc working, I need the ability to build the Debug configuration in XCode but with the RN bundle enabled.

Appium cannot find the UI elements to click on when the app is built in Release mode, so I have to build in Debug mode. But in Debug mode, the XCode packager script [skips building the bundle](https://github.com/facebook/react-native/blob/master/scripts/react-native-xcode.sh) if/when the target is an iOS simulator.

For now I've created a custom version of the packager - see [react-native-xcode-packager]() that effectively ensure the bundle always gets built. But it would be nice to add a command-line flag / environment variable which enables this in the default packager script.

If people like this idea I can have a go at doing a PR.

### Additional Information

* React Native version: 0.40.0
* Platform: iOS
* Development Operating System: macOS
* Build tools: XCode 8.3.2

**Comment by ajostergaard** [comment]
https://github.com/facebook/react-native/pull/14731
