### ISSUE TITLE
0.46 rc.2 - display:none crashes app

### ISSUE THREAD

**Issue by compojoom** [facebook/react-native#14742]
According to the docs https://facebook.github.io/react-native/docs/layout-props.html

display can be either flex or none. Unfortunatly with 0.46 rc.2 display none just crashes the app. On 0.43 - it also had issued. The app was hanging -> CPU went to 100% and memory was filling up. But on 46 the app just crashes

```
libsystem_kernel.dylib`__pthread_kill:
    0x109e8cd38 <+0>:  movl   $0x2000148, %eax          ; imm = 0x2000148 
    0x109e8cd3d <+5>:  movq   %rcx, %r10
    0x109e8cd40 <+8>:  syscall 
->  0x109e8cd42 <+10>: jae    0x109e8cd4c               ; <+20>
    0x109e8cd44 <+12>: movq   %rax, %rdi
    0x109e8cd47 <+15>: jmp    0x109e85caf               ; cerror_nocancel
    0x109e8cd4c <+20>: retq   
    0x109e8cd4d <+21>: nop    
    0x109e8cd4e <+22>: nop    
    0x109e8cd4f <+23>: nop    

```

Here is a repository where I've reproduced the issue:
https://github.com/compojoom/rn46crash
Just run `yarn` and afterwards launch the app in ios. 

### Additional Information

* React Native version: 0.46 rc2
* Platform: tested with iOS
* Development Operating System: macOS
* Build tools:XCode

**Comment by japesh** [comment]
hey @compojoom , i am facing the same issue, did you find any solution for this.

**Comment by compojoom** [comment]
@japesh - a workaround would be to not use display none, but overflow: hidden and width: 0, height: 0.

But yea - display: none shouldn't lead to a crash of the App in the first place.

**Comment by patw0929** [comment]
I'm encountering the same issue in 0.45.1 at iOS, but it looks good at Android.

```javascript
export default class test123 extends Component {
  render() {
    return (
      <View style={{ display: 'none' }}>
        <Text>
          Why crash?
        </Text>
      </View>
    );
  }
}
```

**Comment by patw0929** [comment]
Seems like it's been fixed in this commit:
https://github.com/facebook/react-native/commit/ac3f345b071fbf762e7224fc6357ab2f7080575c

**Comment by compojoom** [comment]
ok, tested with ac3f345 - it seems to be fixed now.

**Comment by japesh** [comment]
thanks for the answer @compojoom  & @patw0929

**Comment by gonglong** [comment]
The cpu jumps to 100% and  the app hang there if i apply [ac3f345](https://github.com/facebook/react-native/commit/ac3f345b071fbf762e7224fc6357ab2f7080575c) to rn@0.46

**Comment by afridash** [comment]
On rn@0.48.4, app crashes on **ios** when a view with **display:none** holds another component with styling. @compojoom provided a cool work around, but in my case I ended up using state to decide if to render or not.

**Comment by sherxia92** [comment]
On rn@0.48.4, app crashes @afridash 
then i upgrade  "react": "16.0.0",    "react-native": "0.50.3", now it works well!

**Comment by trickeyd** [comment]
I am getting this error too, release build only ios and android. Happens when I click any button.

Was getting it on:
"react": "16.0.0-alpha.12"
"react-native": "^0.47.0"

and just upgraded to:
"react": "^16.3.1"
"react-native": "^0.54.4"

but the problem persists! 

I haven't used 'display:none' anywhere in my project. Anything else I can look for!? It's making me sad. :-(
