### ISSUE TITLE
[Android] Text in FlatList not selectable

### ISSUE THREAD

**Issue by dgruseck** [facebook/react-native#14746]
### Description

Text component rendered in FlatList is not selectable even if selectable={true} is specified.
Another Issue for ListView #12342

### Reproduction

```
this.props.data should be an array like [{ key: 1, text: 'Some text' }]

renderListItem = ({ item }) => {
    return (
      <View>
        <Text selectable>{item.text}</Text>
      </View>
    );
  }

  render() {
    return (
      <FlatList
        data={this.props.data}
        renderItem={this.renderListItem}
        keyExtractor={item => item.key}
      />
    );
  }
```

### Solution

Need to be able to select Text in FlatList.

### Additional Information

React Native version: 0.44
Platform: Android, (iOS is working)

**Comment by jhonnold** [comment]
On 0.45.1 I could not recreate this issue (Android).

I used the exact code you pasted above.

**Comment by dgruseck** [comment]
Just upgraded to 45.1 and it works, perfect.
But I have a problem with ios (#14326), so I have to wait to upgrade to the new version.

Thank you

**Comment by asafda** [comment]
reproduced on 0.51

**Comment by JoseIgnacio92** [comment]
In my case I solved the problem by passing a prop key

`<Text selectable={true} key={Math.random()} style={{color:'#FFF'}}>{this.props.message.Message}</Text>`


to force to reload the field. It is not the most appropriate, but I get out of a problem
