### ISSUE TITLE
Running project with release config fails 

### ISSUE THREAD

**Issue by veris-amoghbanta** [facebook/react-native#14751]
### Description
Running react-native project with release config via Xcode fails and gets stuck to the screen below. There is no error or stack trace to find the reason behind it. Everything works smoothly in debug mode. 
<img width="1304" alt="screen shot 2017-06-27 at 8 03 04 pm" src="https://user-images.githubusercontent.com/16878180/27593394-b486ee0e-5b74-11e7-9b93-b895c0996f3f.png">

### Reproduction Steps

- change the run config to release via product/scheme in Xcode
- run on any iOS simulator 

* React Native version: 0.44.2, react: 16.0.0-alpha.6
* Platform: iOS, Android
* Development Operating System: macOS Sierrra 10.12.5
* Build tools:Xcode 8.3.3

**Comment by veris-amoghbanta** [comment]
I feel this is an issue with bundle not getting attached to production build.
I get the following error on running ``react-native build``:
```
error: option '--entry-file' missing
```

**Comment by veris-amoghbanta** [comment]
This is an issue with bundling.
``react-native bundle --platform ios --dev false --entry-file index.ios.js --bundle-output iOS/main.jsbundle`` gives the following error:
``` 
SyntaxError: Unterminated string constant
```
Bundling with --dev true works as expected.

**Comment by lolobosse** [comment]
@veris-amoghbanta Did you solve it? Running into the same issue...

**Comment by veris-amoghbanta** [comment]
Wasn't able to pin point the exact cause, but it was some native dependency that caused the bundler to fail silently. So I switched to a new project and installed and linked the exact compatible dependency versions by hand and it seemed to have worked.
Most probably, it was either react-native-elements or react-native-router-flux that was causing the issue in my case.
