### ISSUE TITLE
[Android] FloatingInput Bug

### ISSUE THREAD

**Issue by ParkHeeTae1** [facebook/react-native#14759]
### Is this a bug report?

No.

### Have you read the Bugs section of the Contributing to React Native Guide?

Yes.

### Environment

1. `react-native -v`: 2.0.1
2. `node -v`: v6.10.3
3. `npm -v`: 3.10.10
4. `yarn --version` (if you use Yarn): 0.24.6

Then, specify:

1. Target Platform (e.g. iOS, Android): Android
2. Development Operating System (e.g. macOS Sierra, Windows 10): macOS Sierra
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant): Android SDK 26.0.2

### Actual Behavior

My problem is disappear Label, when touch input. 

I think that there seems to be a problem native-base/item.js .

why paddingBottom : 12 in Android??

![1](https://user-images.githubusercontent.com/29560569/27621947-36b5778e-5c0f-11e7-9fce-986add9090fc.jpg)

in item.js

<Animated.View
          key="float"
          style={{
            position: "absolute",
            left: this.props.last ? 22 : 22,
            right: 0,
            top: this.state.topAnim,
            opacity: this.state.opacAnim,
            paddingTop: Platform.OS === "ios" ? undefined : undefined,
            paddingBottom: Platform.OS === "ios" ? undefined : 12
          }}
        >

### Reproducible Demo

<FloatingInput
                itemStyle={{ alignItems: 'flex-end' }}
                label="아이디(이메일)"
                autoFocus={true}
                keyboardType="email-address"
                onChangeText={text => this.setState({ email: text })}
                returnKeyType="next"
              />

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by hramos** [comment]
We're only tracking bug reports in this repo.
