### ISSUE TITLE
Can't deploy project on device

### ISSUE THREAD

**Issue by limoncello** [facebook/react-native#14755]
**Is this a bug report?**
Yes.

**Have you read the Bugs section of the Contributing to React Native Guide?**
Yes.

**Environment**
react-native -v: react-native-cli: 2.0.1, react-native: 0.45.1
node -v: v7.7.2
npm -v: 4.1.2
yarn --version: 0.18.1

Target Platform: iOS
Development Operating System: macOS Sierra 10.12.5 (16F73)
Build tools: Xcode 8.3.3

**Actual Behavior**
I tried to deploy the project on an iOS device (10.3.2) using Xcode. The build gets interrupted by an error:

<details>

```
Showing Recent Issues
CpResource ios /Users/limoncello/Library/Developer/Xcode/DerivedData/projectX-gqasesfugdbcefeizfdgumtmcteh/Build/Products/Release-iphoneos/projectX.app/ios
    cd /Users/limoncello/github/projectX/projectX/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -strip-debug-symbols -strip-tool /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip -resolve-src-symlinks /Users/limoncello/github/projectX/projectX/ios/ios /Users/limoncello/Library/Developer/Xcode/DerivedData/projectX-gqasesfugdbcefeizfdgumtmcteh/Build/Products/Release-iphoneos/projectX.app

error: /Users/limoncello/github/projectX/projectX/ios/ios: No such file or directory
```

</details>

**Comment by rozenshtein** [comment]
Delete /ios and /android folders which are likely damaged.
Run react-native upgrade to generate /ios and /android folders again.
Run react-native link for any native dependency.
Finally run react-native run-ios or just open your project in XCode.

**Comment by limoncello** [comment]
It didn't help.
I deleted the npm_modules folder, then `react-native-git-upgrade`. Cleaned the cache..and voilà!

**Comment by charpeni** [comment]
I'll close this as it seems resolved, if it's not feel free to ping me.

**Comment by charpeni** [comment]
@facebook-github-bot close
