### ISSUE TITLE
Cannot connect to remote debugger when using android real device with charlse proxy enabled.

### ISSUE THREAD

**Issue by Obooman** [facebook/react-native#14758]
### Is this a bug report?
Yes,I think it's a bug with react-native itself.

### Have you read the Bugs section of the Contributing to React Native Guide?
Yes,the bug can only be reproduced with real devices.

### Environment

1. `react-native -v`:0.45.1
2. `node -v`:v7.8.0
3. `npm -v`:5.0.3
4. `yarn --version`:0.15.1

Then, specify:

1. Target Platform (e.g. iOS, Android):Android
2. Development Operating System:macOS Sierra 10.12.5 (16F73)
3. Build tools : Android Studio 2.2.2 , SDK 21

### Steps to Reproduce

1.With a local node data server running,hijacked `http://demo.com:6003` to local server with hosts.
2.open `Charlse` as device proxy set my android phone proxy to `Charlse` address
3.Shake the phone and press debug `Debug JS Remotely`,react native package process log `Launching Dev Tools...` and `http://localhost:8081/debugger-ui` shown,but android device keeps showing `connecting to remote debugger` green bar and after short time it shows `Timeout while connecting to remove debugger`

### Expected Behavior
I can connect to remote debugger successfully,log my http response from server .

### Actual Behavior
packager server acts but real device cannot aware of conneted info.
PS:the packager works well and if I do not open `Debus js remotely` everything works well,the aoo compile and reload well.

### Reproducible Demo
Real Device bug,there's no demo can be offered.
have changed ip address to `IP` or `localhost`,no difference.

**Comment by th317erd** [comment]
Same issue for me

**Comment by Obooman** [comment]
As there's no one reply the issue I'll close it.But I have to say the problem still exits.
😞
By moving website to a public repo and `chrome devTool network panel`,I can continue my development

**Comment by pangpond** [comment]
I resolve this by disable production config in main App

```
// console.disableYellowBox = true
// console.error = error => error.apply
// NativeModules.ExceptionsManager = null
```

**Comment by rutsatz** [comment]
For me, it solved to uninstall the app in the real android device and install it again by running react-native run-android in the terminal. After that, shake the device and enable debugger. Everything works.

**Comment by hjJunior** [comment]
I got the same problem using react native 0.53

**Comment by iastanley** [comment]
I also have the same issue using react native 0.53 on macOS with android virtual device emulator. In addition when I try to enable debugging and it fails I am always taken to this url: http://10.0.2.2:8081/debugger-ui. When it works I am redirected to this url: http://localhost:8081/debugger-ui/

I have only gotten the debugger to work once out of over a dozen times restarting terminal instance, browser, emulator etc. trying to get it to work.

**Comment by nhuthuynh** [comment]
same here, I am using react-native 0.5.3 running on mac os. Trying to reverse port in terminal but it does not help.

**Comment by nhuthuynh** [comment]
Follow this link [link](https://stackoverflow.com/questions/40898934/unable-to-connect-with-remote-debugger), the second answer works for me!
