### ISSUE TITLE
[AnimationExperimental] iPhone 5 Animation Bug?

### ISSUE THREAD

**Issue by TimonSotiropoulos** [facebook/react-native#1476]
Just been working on doing a few animations with AnimationExperimental to slide a View up and down using a TouchableHighlight. All seems to be working fine in the iOS Simulator on iPhone 6, 6 Plus and 5S but am getting some weird results on the iPhone 5. Instead of animating from it's current position to it's new position, on the iPhone 5 is it animating from outside of the screen entirely to the position. Here is the component that I am working on that is doing the animation.

    var CategoryDetail = React.createClass({
        getInitialState: function() {
            return {
                descViewHeight: 427,
                expViewActive: false
            };
        },
        _toggleExpScrollMenu: function() {
            var self = this;
            this.state.expViewActive ? this._hideExpView(self) : this._showExpView(self); 
        },
        _showExpView: function(self) {
            self._animateView(self, -150);
        },
        _hideExpView: function(self) {
            self._animateView(self, 150);
        },
        _animateView: function(self, viewAnimateHeight) {

            var descViewCurrentHeight = self.state.descViewHeight;
            var expViewActive = self.state.expViewActive;
            var animateToValue = expViewActive ? 577 : 427;
            var animateDuration = 350;
            var callbackDelay = expViewActive ? 0 : animateDuration - 75;

            AnimationExperimental.startAnimation({
                node: self.refs.playView,
                duration: animateDuration,
                easing: 'linear',
                property: 'positionY',
                toValue: animateToValue,  
            }, 
                function (finished) {
                    setTimeout(() =>
                    self.setState({
                        descViewHeight: descViewCurrentHeight + viewAnimateHeight,
                        expViewActive: !expViewActive
                    }), callbackDelay);    
                }
            );
        },
        render: function() {
            var expViewTop = this.state.expViewTop;
            var descViewHeight = this.state.descViewHeight;

            return (
                <View>
                    <View ref="descView" style={[styles.descView,{height: descViewHeight} ]}>
                        <ScrollView>
                            <View style={[Layout.rowCenter, Layout.contentCenter, Layout.containerTopTailPadded]}>
                                <Image  style={Layout.logo}
                                        source={{uri: this.props.category.image}}
                                />
                                <Text style={TextStyle.heading}>{this.props.category.title}</Text>
                            </View>
                            <Text style={[Layout.containerSidesPadded, TextStyle.paragraph]}>{this.props.category.paragraph}</Text>
                        </ScrollView>
                    </View>
                    <View ref="playView" style={[styles.playView]}>
                        <ScrollView style={[styles.menuScrollView]} contentInset={{top: -64}}>
                            <TouchableHighlight onPress={this._toggleExpScrollMenu}>
                                <View style={styles.expScrollMenu}>
                                    <Image source={require('image!toggle')} ></Image>
                                </View>
                            </TouchableHighlight>
                            <ExperienceList rightButtonTitle={this.props.rightButtonTitle} onRightButtonPress={this.props.onRightButtonPress} navigator={this.props.navigator} category={this.props.category} />
                        </ScrollView>
                    </View>
                </View>
            );
        }
    });

**Comment by ivanbabanov** [comment]
I saw the same behavior on iPhone4 and iPad2. I think it's caused by hardware performance. I saw that animation is implemented as KeyFrame animation and I saw very slow frame rate on device when Animation was started.

**Comment by brentvatne** [comment]
AnimationExperimental is deprecated and will be replaced soon, for the moment you are better off using [react-tween-state](https://github.com/chenglou/react-tween-state) or [rebound](https://github.com/facebook/rebound-js) (used in various places by react-native, so it's already in your project ready to require).r
