### ISSUE TITLE
FlatList refresh bug

### ISSUE THREAD

**Issue by zzetao** [facebook/react-native#14761]
### Is this a bug report?

Yes.

### Have you read the Bugs section of the Contributing to React Native Guide?

Yes.

### Environment

`react-native -v`: 0.43.4
`node -v`: 7.7.4
`npm -v`: 4.1.2
`yarn --version`: 0.22.0

Then, specify:

Target Platform (e.g. iOS, Android): iOS
Development Operating System: macOS Sierra
Build tools : Xcode

### Description

The first click is invalid after refreshing, See the demo for details.

### Reproducible Demo

https://snack.expo.io/Hyd4CAlEb

**Comment by hramos** [comment]
Can you elaborate a bit more? Please explain the list of steps to reproduce, what was expected, and what happened instead.

**Comment by andrewda** [comment]
@hramos I believe the issue is that after refreshing the FlatList, the TouchableHighlight does not respond to the first press. The user has to press the TouchableHighlight twice in order to get the Alert to appear.

**Comment by michaelspeed** [comment]
i can confirm this on iOS but android is working as expected

**Comment by eladgel** [comment]
```
react-native -v: 0.46.4
node -v: 6.9.2
npm -v: 3.10.9
yarn --version: 0.27.5
```

Then, specify:

Target Platform (e.g. iOS, Android): iOS
Development Operating System: macOS Sierra
Build tools : Xcode

Happens also with ScrollView and ListView
notice that the touchable element becomes untappable when you scroll and reach the end of the scrolling component(ListView/ScrollView/FlatList)

https://github.com/facebook/react-native/commit/23c2a6cf1ae297182a62d1a8143b55b186f5e1b7
is supposed to fix this, waiting for RN 0.47 then :(

**Comment by narodejesus** [comment]
what @andrewda said is what is exactly happening to my app when using the RefreshControl component

**Comment by Furqankhanzada** [comment]
@zzetao any solution ? i am also facing this issue.

**Comment by eladgel** [comment]
react-native -v: 0.49.3

same thing :(

**Comment by eladgel** [comment]
react-native -v: 0.49.5
FIXED!!!!!!!!!!!! ! ! !! ! ! 1 
! !
 !
! 
!
 !

**Comment by eladgel** [comment]
I can't repro on iphoneX, every other iphone, still happening

**Comment by narodejesus** [comment]
i encountered this few months ago .. but now i am using 0.47.2 @eladgel it doesn't seem a problem anymore .. perhaps it was fixed

**Comment by fallenner** [comment]
it's still happening   I am using 0.52 android

**Comment by AnotherEye** [comment]
it's still happening using reactnative -v 0.54.2 iOS

**Comment by jemoav** [comment]
In #20011 there is an useful solution
