### ISSUE TITLE
'setTimeout' And 'setInterval' Breaks With Remote Debugging In Chrome (iOS)

### ISSUE THREAD

**Issue by WilliamIPark** [facebook/react-native#14776]
### Is this a bug report?
Yes

### Have you read the Bugs section of the Contributing to React Native Guide?
Yes

### Environment

1. `react-native -v`: 0.45.1
2. `node -v`:  6.11.0
3. `npm -v`: 5.0.4

1. `Target Platform`: iOS
2. `Development Operating System`: macOS Sierra
3. `Build tools`: Xcode 8.3.2

### Steps to Reproduce

1. Start a new react-native project.
2. Use a `setTimeout` or `setInterval` in a component's `componentWillMount` to log to console.
3. Set the delay to 3000 on the `setTimeout` or `setInterval`.
4. Run project, open remote debugging on Chrome.

### Expected Behavior

I expected a log to appear in the console after 3 seconds.

### Actual Behavior

- No console log appears. The `setTimeout`/`setInterval` does not fire.
- The timeout/interval will run fine if the delay is low enough. (1000ms seems generally safe)
- Closing the remote debugging will fix the issue.
- There are several ways to force the log to appear. One of them is to pull down the iOS notification drawer. When the drawer closes the log will appear instantly.
- This problem still occurs if the interval or timeout is triggered elsewhere, eg not in `componentWillMount`, but on a button's press.
- Harder to reproduce, but I have had instances where if the delay was in a certain time range (1200ms for me) where the timeout would fire the first time, but never again, until the delay value was slightly changed, even by 1ms.

### Reproducible Demo

See this repo: https://github.com/PiggyPot/timeout-bug/tree/master
Follow the instructions in the readme to reproduce.

We have been able to reproduce this issue in 4 different projects, on 4 different machines (with the same set up).

I think issue #9436 is related, however it only mentions issues pertaining to Android.

**Comment by WilliamIPark** [comment]
Fixed in the latest version of react-native

**Comment by arnsa** [comment]
@WilliamIPark still not working for me on 0.46.4.

**Comment by WilliamIPark** [comment]
@arnsa You'll need `0.47.0-rc.1`
