### ISSUE TITLE
undefined is not an object (evaluating 'this._onEmoticonPress.bind') react native "0.45.1" 

### ISSUE THREAD

**Issue by sachinsinghh** [facebook/react-native#14770]
import Emoticons from 'react-native-emoticons';

export default class Decker extends Component {
_emojiSelected(emoji) {
    console.log(emoji)
  }

        <Emoticons
 	 onEmoticonPress={this._onEmoticonPress.bind(this)}
 	 onBackspacePress={this._onBackspacePress.bind(this)}
 	 show={this.state.showEmoticons}
 	 concise={true}
 	 showHistoryBar={true}
 	 showPlusBar={true}
  />

**Comment by sachinsinghh** [comment]
@hramos You didn't mention solution.

**Comment by hramos** [comment]
I'm sorry, the issue you opened is missing information. Please make sure to fill out the template when opening a new issue, thanks!
