### ISSUE TITLE
Generate apk doesn't work on windows

### ISSUE THREAD

**Issue by LukasNavickas** [facebook/react-native#14771]
### Is this a bug report?
Yes

### Have you read the Bugs section of the Contributing to React Native Guide?
Yes

### Environment
Windows 
`react-native -v`: (I have tried different versions)
SDK Build Tools 25

Then, specify:

1. Target Platform (e.g. iOS, Android):
2. Development Operating System (e.g. macOS Sierra, Windows 10):
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant):

### Steps to Reproduce
I followed the tutorial on https://facebook.github.io/react-native/docs/signed-apk-android.html First problem: there is no gradle.properties file at C/Users/User/.gradle/
Inside the .gradle folder, I can only find 4 other folders: 'caches', 'native', 'daemon', 'wrapper' 
Second Problem: I have generated the .apk, but it says 'release-unsigned'. It doesn't install on my Android phone. 

### Expected Behavior
I could find "gradle.properties" and generate a signed .apk

**Comment by hramos** [comment]
Can you post the latest RN version that you tried? 
Did you try using the 23 SDK Build Tools?

**Comment by LukasNavickas** [comment]
I could successfully build it after updating my Android Studio and my gradle to 3.3
