### ISSUE TITLE
GIF looped only once on React Native Android

### ISSUE THREAD

**Issue by GaoStudio** [facebook/react-native#14783]
My GIF is only looped once in Android version, while in iOS it looped infinitely. Could you tell me what i'm missing?
RN: 0.44.2 Fresco: 1.0.1

**Comment by charpeni** [comment]
I was not able to reproduce it on `react-native@0.45.1`.

Have you added `compile 'com.facebook.fresco:animated-gif:1.0.1'` as mentioned here : https://facebook.github.io/react-native/docs/image.html#gif-and-webp-support-on-android

Can you reproduce it on a fresh new project ?

**Comment by GaoStudio** [comment]
Yes，My gif is only show once on IE,I need refresh,it can show again，Does it have anything to do with GIF?

**Comment by charpeni** [comment]
On IE? Sorry, I don't understand, do you have any code sample?

**Comment by hezheop** [comment]
me too, 0.44.2   only once

**Comment by Deallinker** [comment]
Me too on Android 0.46.2

**Comment by GaoStudio** [comment]
you  should  set  your  gif by ps to loop

**Comment by Juliocbr** [comment]
me too, only once on Android
RN 0.50.3
Fresco 1.5.0

**Comment by qamoonsite** [comment]
hi ,my gif is set to loop once- 
yet , on android everything is great and it loops once , but on IOS it keeps on looping . 
any suggestions ?

**Comment by jsfu** [comment]
if you want to the gif  keeps on looping, you must set gif to loop Infinitely when you make it
