### ISSUE TITLE
 Module does not exist in the module map or in these directories: please help!!

### ISSUE THREAD

**Issue by JanaTrajkovska** [facebook/react-native#14785]
Please help! I have tried everything:
Deleting node modules, updating react native, clear cache...

{
	"name": "tech",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"start": "node node_modules/react-native/local-cli/cli.js start",
		"test": "jest"
	},
	"dependencies": {
		"react": "16.0.0-alpha.12",
		"react-native": "0.45.1"
	},
	"devDependencies": {
		"babel-jest": "20.0.3",
		"babel-preset-react-native": "2.0.0",
		"jest": "20.0.4",
		"react-test-renderer": "16.0.0-alpha.12"
	},
	"jest": {
		"preset": "react-native"
	}
}

**Comment by charpeni** [comment]
Can you provide more information?

**Comment by JakeDoe** [comment]
@JanaTrajkovska which module? Please enable chrome debugging and post error from chrome console here. Thx!

**Comment by JanaTrajkovska** [comment]
Loading dependency graph, done.
Bundling `index.android.js`
  Analysing...(node:5812) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): UnableToResolveError: Unable to resolve module `.src/app` from `C:\Users\Jana\Desktop\ReactNative\tech\index.android.js`: Module does not exist in the module map or in these directories:
  C:\Users\Jana\Desktop\ReactNative\tech\node_modules\.src

**Comment by JakeDoe** [comment]
try to change ```.src``` to ```./src```

**Comment by JanaTrajkovska** [comment]
@JakeDoe now when I change that, this error showed up:

Bundling `index.android.js`
  Transforming modules  ▓▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░░  11.1% (1/3)...(node:5772) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 34): UnableToResolveError: Unable to resolve module `react/lib/LinkedStateMixin` from `C:\Users\Jana\Desktop\ReactNative\tech\node_modules\react-native\Libraries\react-native\react-native.js`: Module does not exist in the module map or in these directories:
  C:\Users\Jana\Desktop\ReactNative\tech\node_modules\react-native\node_modules\react\lib
,   C:\Users\Jana\Desktop\ReactNative\tech\node_modules\react\lib

**Comment by JanaTrajkovska** [comment]
I have created new project and change .src to ./src and it worked! 
Thank you very much @JakeDoe :)

**Comment by charpeni** [comment]
I'll close this as it has been resolved.

**Comment by charpeni** [comment]
@facebook-github-bot resolved

**Comment by charpeni** [comment]
@facebook-github-bot answered

**Comment by shashikantChetu** [comment]
facebook-github-bot which one file change .src to ./src

**Comment by Kana00** [comment]
I solved this problem by deleting an `import MyModule from '../MyModule'` attempt, while the package was not declared in the package.json (useless package...)
