### ISSUE TITLE
Flatlist Footer animation[possible BUG]

### ISSUE THREAD

**Issue by michaelspeed** [facebook/react-native#14788]
Possible BUG
I was creating a Flatlist component like following - 

`<FlatList data={data} renderItem={this._renderItem} keyExtractor={this._keyExtractor} refreshing={this.state.refresh} onRefresh={this.onRefresh}
                ListHeaderComponent={this._renderHeader} ListFooterComponent={this._footerComponent}/>`

now the footer component looks like this - 

`_footerComponent = () => {
      return(
        <ButtonComponent buttonState={this.state.buttonState}
          states={{
            load:{
              onPress: () => {
                this._endReached();
              },
              text:'Load More'
            },
            loading:{
              onPress: () => {},
              spinner: true,
              text:'Loading More .....'
            }
          }}></ButtonComponent>
      )`

with library [react-native-button-component](https://github.com/jacklam718/react-native-button-component)

now the problem is that the button does not seem to animate! 
in fact anything i put in the footer component it does not seem to animate or even change with a change of state

i even tried with this library - [ant](https://mobile.ant.design/)

in this manner -

`<View style={{alignItems:'center', justifyContent:'center', height: 40, flex:1, flexDirection:'row'}}>
                            <ActivityIndicator animating={this.state.loadingMore} text="Loading more ..."/>
                            <Text>{this.state.ButtonText}</Text>
                        </View>`

but it does not animate, except that everything works fine

### Have you read the Bugs section of the Contributing to React Native Guide?
YES

### Environment

1. `react-native -v`: {react-native-cli: 2.0.1
react-native: 0.45.1}
2. `node -v`:  v7.4.0
3. `npm -v`: 4.0.5
4. `yarn --version` (if you use Yarn): 0.24.5

Then, specify:

1. Target Platform (e.g. iOS, Android): Android/iOS(Tested on: Android 7.1.1/ iOS: 10.3.2/11 beta)
2. Development Operating System (e.g. macOS Sierra, Windows 10): macOS 10.12.5
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant): not relevant

### Steps to Reproduce

1. copy the above code, 
2. configure state change accordingly to show animations
3. use any of the above library

### Expected Behavior

it should animate or show a state change

### Actual Behavior

not showing state change or animation/ but the onPress function runs fine

if i skip this step its fine no apparent change! but i do not think that it should behave like this!

**Comment by jalalat** [comment]
Hi @michaelspeed did you find any solution for this issue. I am facing the same issue with FlatList.
