### ISSUE TITLE
[Packager] require('react-native') must be assigned to React

### ISSUE THREAD

**Issue by alinz** [facebook/react-native#1479]
By accident I have assigned require('react-native') to a variable other than `React` and It failed to execute. hmmm...

This code works fine

```js
var React = require('react-native');

var {
  Component,
  View
} = React;

class MyApp extends Component {
  render() {
    return (
      <View></View>
    );
  }
}

module.exports = MyApp;
```

By this one doesn't

```js
var Test = require('react-native');

var {
  Component,
  View
} = Test;

class MyApp extends Component {
  render() {
    return (
      <View></View>
    );
  }
}

module.exports = MyApp;
```

Here's what I got as an error:
![screen shot 2015-06-01 at 1 47 47 pm](https://cloud.githubusercontent.com/assets/967050/7919244/fc3f157e-0864-11e5-9f95-e588bfc2abf8.png)

**Comment by jtremback** [comment]
:+1:

**Comment by alinz** [comment]
After some digging I found that JSX transformer is the root cause.

Here's an example:

```js
var Test = require('react-native');
...

render() {
    return (
        <View></View>
    );
}
```

is compiles into

```js
return (
    React.createElement(View, null)
);
```

even though I required `react-native` to `Test`, JSX compiler doesn't really care and uses `React` object to create the `View` element.

**Comment by brentvatne** [comment]
What use case do you have for using a name other than React? While this isn't ideal I don't think it is really a big issue either :smile: cc. @frantic.

@alinz - If you want to look into it and submit a PR that would be great.

**Comment by alinz** [comment]
@brentvatne I don't have any! I wish I had one! ;) 
I don't know whether this PR would be beneficial for anyone, but challenge accepted! :+1:

**Comment by spicyj** [comment]
We don't intend to support this in the JSX transformer, sorry. We require that you have `React` in scope.
