### ISSUE TITLE
Android multi-dimensional product flavors not supported

### ISSUE THREAD

**Issue by wsxyeah** [facebook/react-native#14791]
### Is this a bug report?

Yes

### Have you read the Bugs section of the Contributing to React Native Guide?

Yes

### Environment

1. Target Platform: Android
2. Build tools: Android Studio 2.3.3(gradle 2.14.1)

### Steps to Reproduce

1. Configure your `android/app/build.gradle` with 2 or more product flavor dimensions, such as below:
```gradle
flavorDimensions 'stage', 'product'
productFlavors {
    dev {
        dimension 'stage'
    }
    beta {
        dimension 'stage'
    }

    chair {
        dimension 'product'
    }
    table {
        dimension 'product'
    }
}
```
2. Then build the project. Run `./gradlew assembleDevChairRelease`

### Expected Behavior

According to `react.gradle`,
```gradle
runBefore("process${targetName}Resources", currentBundleTask)
```

There **should** be a task called `bundleDevChairReleaseJsAndAssets ` to build the js bundle into assets, which runs before `processDevChairReleaseResources`.

### Actual Behavior

As written in `react.gradle`
```gradle
productFlavors.each { productFlavorName ->
    buildTypes.each { buildTypeName ->
            def flavorNameCapitalized = "${productFlavorName.capitalize()}"
            def buildNameCapitalized = "${buildTypeName.capitalize()}"
            def targetName = "${flavorNameCapitalized}${buildNameCapitalized}"
            ...
            runBefore("process${targetName}Resources", currentBundleTask)
    }
}
```
the loop will be executed within `[dev, beta, chair, table]`,
instead of the expected combination `[devChair, devTable, betaChair, betaTable]`.

Apparently,  the `targetName` is not matched to the real task name to be hooked,
so `currentBundleTask` never get executed.

**Comment by aniljaiswal** [comment]
Have you found a work around for this? We are facing the same issue with flavors.

**Comment by wsxyeah** [comment]
@aniljaiswal 
Yes, see my pull request #14792. But it's not merged until now.

It works for me.
- If you are using command line `gradlew` to build your apk, no more configuration is required.
- If you want to use Android Studio, you should disable `Configuration on demand` option in `Settings > Build, Execution, Deployment > Compiler`.

**Comment by liamjones** [comment]
Any chance on resurrecting this issue and PR #14792? We've just hit this issue at our company too.
