### ISSUE TITLE
Command `bundle` unrecognized for yarn

### ISSUE THREAD

**Issue by xareelee** [facebook/react-native#14795]
I need to pack **main.jsbundle** for local usage. I only found ReactNative 0.19 docs (http://facebook.github.io/react-native/releases/0.19/docs/running-on-device-ios.html) to demonstrate this step. So I tried this command but failed:

``` 
$ react-native bundle --platform ios --dev false --entry-file index.ios.js --bundle-output iOS/main.jsbundle

Command `bundle` unrecognized. Make sure that you have run `npm install` and that you are inside a react-native project.
```

Then I tried use `npm install` first (I used `yarn`): 

```
$ npm install && react-native bundle ...
// now it works
```

I have a few question:

1. Does not `react-native bundle` command support `yarn` node module manager?
2. Docs about `react-native bundle` is missing in official website (https://facebook.github.io/react-native/docs/getting-started.html). Could you add this info in the docs?
3. What is `main.jsbundle.meta` and  how could I use it? 
4. How can I use uglify for my js bundle? Could you document this?

### Environment

1. `react-native -v`: 0.45.1
2. `node -v`: v7.8.0
3. `npm -v`: 4.2.0
4. `yarn --version` (if you use Yarn): 0.22.0

Then, specify:

1. Target Platform (e.g. iOS, Android): iOS/Android
2. Development Operating System (e.g. macOS Sierra, Windows 10): macOS

**Comment by duzliang** [comment]
+1
