### ISSUE TITLE
Cannot read property 'string' of undefined

### ISSUE THREAD

**Issue by WayneUong** [facebook/react-native#14805]
`LayoutPropTypes.js:35:26`
Only with react `16.0.0-alpha.13`

**Comment by gibson** [comment]
And you think this is bag report? With react alpha version? You are crazy.

**Comment by WayneUong** [comment]
We all know why the error happens. Just pushing for the prop-type package.

**Comment by RaphArbuz** [comment]
Same thing with react 16.0.0-alpha.12. If you know why the error happens could you please let us know?
