### ISSUE TITLE
set borderRadius topLeft and bottomLeft affects the view displaying

### ISSUE THREAD

**Issue by Creemli** [facebook/react-native#14817]
```javascript
<View style={{marginTop: 100,width: Width, height: 35, borderTopLeftRadius: 18, borderBottomLeftRadius: 18, backgroundColor: 'red'}}/>
```
This situation is not correct， and it displays mess on 6sPlus:
![image](https://user-images.githubusercontent.com/5566981/27818334-ca7ef794-60c7-11e7-85ac-4b309d1f94c1.png)
and  it is like this when resize to 100%:
![image](https://user-images.githubusercontent.com/5566981/27818476-56304b26-60c8-11e7-846f-f2382aa9f049.png)

But if I set the height to even number Or add the radius to the other corner, it displays correct.
![image](https://user-images.githubusercontent.com/5566981/27818439-2b871558-60c8-11e7-99a2-b843a4f6917c.png)

RN: 0.33 
ios simulator 6p, 10.3

**Comment by brentvatne** [comment]
Hello! Please follow the issue template when you file an issue. Additionally, no support is provided for very old versions of React Native -- 0.33 is just about 12 versions behind, which is nearly a year.
