### ISSUE TITLE
[Bridge] Is there a way to guarantee in what order set#propName will be called in a view

### ISSUE THREAD

**Issue by JohnyDays** [facebook/react-native#1481]
Currently implementing the solution for #1442 proposed by @brentvatne. Tried asking in IRC several times, but got no response. 
While I'm at it, here's the current planned (and almost complete, barred by the interaction between changing from local urls to remote urls and etc.) api

````javascript

// Will load the contents of index.html, with relative paths being resolved from /folder
<WebView baseUrl = {"/folder"} url = {"index.html"} /> 

// If the contents of index.html were '<script src="index.js"></script>' this would be equivalent.
// It will load folder/index.js
<WebView baseUrl = {"/folder"} html = {"<script src='index.js'></script>"} />

// Also equivalent to the above
<WebView url = {"file://folder/index.html"} />

````

For this I need baseUrl to be resolved before both url and html, and I have found no way to do this explicitly, either by ordering the exported macros or passing the props in the correct order(which is not ideal anyway)

**Comment by JohnyDays** [comment]
Don't really see a way to implement this without explicit ordering of the props. Pausing development on this until someone can tell whether this is possible.

**Comment by JohnyDays** [comment]
Was told there was no way to do this, there might be another solution though.

**Comment by brentvatne** [comment]
An example of how you might do this @JohnyDays:

```objc
- (void)setHtml:(NSString *)html
{
  _html = html;
  [self applyHtmlAndBaseUrl];
}
 
- (void)setBaseUrl:(NSString *)baseUrl
{
  _baseUrl = baseUrl;
  [self applyHtmlAndBaseUrl];
}
 
- (void)applyHtmlAndBaseUrl
{
  if (_baseUrl != nil && _html != nil) {
    // set them on the webview
  }
}
```

**Comment by JohnyDays** [comment]
I need to deal with the transition between ````html/baseUrl```` to ````File/baseUrl```` to ````html/no baseUrl```` to ````file/noBaseUrl(in this case I am infering the base url from the file path)```` to ````remoteUrl````

And having an html(inline) property defined makes url navigation broken, since I can't point the url to a file or remote uri

**Comment by brentvatne** [comment]
@JohnyDays - maybe it's easiest for us to collapse all of these options into a `source` prop?

**Comment by JohnyDays** [comment]
@brentvatne That would be ideal, although it would change the current api. I'm not sure how much impact that would have

**Comment by brentvatne** [comment]
@JohnyDays - let's do that, leave the existing API in place and submit a PR then get some feedback on it - maybe we can leave those props in for a while and deprecate them after a few versions if we decide to go in that direction

**Comment by JohnyDays** [comment]
My IRC isn't working properly, after a few minutes of being logged in I stop both being able to write and read messages, gonna try to fix it soon. 
Anyway, I'm implementing it with a source object right now.

**Comment by JohnyDays** [comment]
Thanks @brentvatne, your suggestions really guided me towards making this work properly. I was clearly overthinking it. However there's still a few edges to be roughed out, should I submit a working, but unpolished pull request to gather feedback?

**Comment by brentvatne** [comment]
@JohnyDays - sounds like a great idea :smile:
