### ISSUE TITLE
run app on a device is throwing an error index.android.js not found

### ISSUE THREAD

**Issue by Mirodil** [facebook/react-native#14828]
### Is this a bug report?

yes

### Have you read the Bugs section of the Contributing to React Native Guide?

yes

### Environment
MacOS

1. `react-native -v`: react-native-cli: 2.0.1 react-native: 0.45.1
2. `node -v`: v7.10.0
3. `npm -v`: 4.2.0
4. `yarn --version` (if you use Yarn): 0.27.5

Then, specify:

1. Target Platform (e.g. iOS, Android): Android
2. Development Operating System (e.g. macOS Sierra, Windows 10): MacOS
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant):

### Steps to Reproduce

(Write your steps here:)

1. run `create-react-native-app AwesomeProject`
2. run `react-native run-android`
3. then you can see this error

### Expected Behavior

I hope it will work

### Actual Behavior

error cannot found index.android.js or index.ios.js
![photo_2017-07-04_16-55-21](https://user-images.githubusercontent.com/1898801/27842880-eee3bc3c-60db-11e7-915b-59a47352d46b.png)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

I have tried solution from: #3442, #5174, #14246  did not work

**Comment by btav** [comment]
@Mirodil can you see any issues in the Packager? 

I noticed that you created the project using the `create-react-native-app` CLI and are trying to start it with the `react-native run-android` command. For the `create-react-native-app` CLI I believe the way to run an app on the Android simulator is by running the `npm run android` command. For more information check out the following repo [https://github.com/react-community/create-react-native-app](https://github.com/react-community/create-react-native-app). 

If that doesnt work, I would try the `react-native-cli` instead. [https://facebook.github.io/react-native/docs/getting-started.html#the-react-native-cli](https://facebook.github.io/react-native/docs/getting-started.html#the-react-native-cli 
)
I hope that helps!

**Comment by brentvatne** [comment]
@btav is right, you will need to use `npm run android` instead of `react-native run-android`.

I created an issue on Create React Native App to track this, we should make react-native-cli delegate to react-native-scripts in a CRNA project. See: https://github.com/react-community/create-react-native-app/issues/294

**Comment by Mirodil** [comment]
Thank you for the answer
I have faced to the same issue with `react-native-cli`, just created a new project with `react-native init AwesomeProject` command and run app with `react-native run-android` command. The screen with the same issue "Cannot file entry file index.andoird.js in any of the roots"
