### ISSUE TITLE
TextInput displays placeholder on multiple lines when set dynamically on Android

### ISSUE THREAD

**Issue by davidlongest** [facebook/react-native#14839]
### Is this a bug report?

Yes

### Have you read the Bugs section of the Contributing to React Native Guide?

Yes

### Environment

1. `react-native -v`:
```
react-native-cli: 2.0.1
react-native: 0.45.1
```
2. `node -v`: `v7.7.2`
3. `npm -v`: `4.1.2`
4. `yarn --version` (if you use Yarn): `N/A`

Then, specify:

1. Target Platform (e.g. iOS, Android): Android
2. Development Operating System (e.g. macOS Sierra, Windows 10): macOS Sierra 10.12.5
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant): Android Studio 2.3.2. Compile SDK 23. Build tools 23.0.1

### Steps to Reproduce

1. Add a TextInput with no props set
2. Set a placeholder that render longer than the TextInput is wide after the first render
3. Do the same while setting the TextInput `multiline` prop to false.

### Expected Behavior

On a TextInput with multiline undefined or `false`, the placeholder should only display a single line of text.

### Actual Behavior

After the TextInput renders, it will display a second line of placeholder text halfway rendered and push the first line to the top of the view.

<img width="427" alt="screen shot 2017-07-05 at 3 49 50 pm" src="https://user-images.githubusercontent.com/5114282/27882189-aca3fbb6-6199-11e7-92cd-df0a8fedd1ee.png">

### Reproducible Demo

To see the issue. Launch the example project below and preview it. Once the application launches, wait a half second and note the placeholder text showing below the android underline.
https://snack.expo.io/SyE1ChqEb

**Comment by davidlongest** [comment]
Also occurs on 0.46.0

**Comment by zhantx** [comment]
+1 on 0.46.4, I think this is related to android version as well, not all my android devices have this issue, the only one has this is Android 5.1

**Comment by psteele2** [comment]
👍

**Comment by HemrajLodha** [comment]
numberOfLines prop not working in ios TextInput.
