### ISSUE TITLE
TypeError:expected dynamic type 'string', but had type 'object'

### ISSUE THREAD

**Issue by Alleeeen** [facebook/react-native#14833]
1. react-native :  0.45.1
2. node :  6.3.1
3. npm :   3.10.3

1. Android
2. Development Operating System : macOS X EI Capitan
3. Build tools ： Android 25.0.0

After I upgrade the react version from 0.29.0 to 0.45.1, I got the following error: 

TypeError:expected dynamic type 'string', but had type 'object'

![device-2017-07-05-201151](https://user-images.githubusercontent.com/18445727/27863754-31a30216-61be-11e7-8c32-5077b6010c88.png)

It's been bother me for a few days, anyone who know how to solve this would be appricated.

**Comment by rawrmaan** [comment]
Sounds like you might be calling the `Alert` native module with old/incorrect params? Just a guess.

**Comment by Alleeeen** [comment]
Yes, I saw the code of Alert.js and figured out that this error is due to I call the Alert with a param of 'error' which is a object not a string anymore. The strange thing is this happened after I upgraded the react native version from 0.29.0 to 0.45.1.
