### ISSUE TITLE
UI not responsive during expensive native call

### ISSUE THREAD

**Issue by joIivier** [facebook/react-native#14841]
### Is this a bug report?

Yes

### Have you read the Bugs section of the Contributing to React Native Guide?

Yes

### Environment

1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.45.1

2. `node -v`:
v7.7.3
3. `npm -v`:
4.4.4
4. `yarn --version` (if you use Yarn):

Then, specify:

1. Target Platform (e.g. iOS, Android):
Android
2. Development Operating System (e.g. macOS Sierra, Windows 10):
Linux (ArchLinux) and macOS Sierra
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant):
Android Studio 2.3.3

### Steps to Reproduce
1.Start a new application with `react-native init B`
2.Change index.android.js to just render a button performing a native call:
```
render() {
    return (
      <View style={styles.container}>
       <TouchableHighlight underlayColor="yellow" style={styles.button} onPress={() => {
          this.setState({a: 2});
          NativeModules.T.run(() => {
            this.setState({a: 3});
          });
         }}>
         <Text>Press me</Text>
       </TouchableHighlight>
       <Text>{this.state.a}</Text>
      </View>
    );
  }
```
(Initial state is `{a: 1}`)
3.Add native module T to perform some expensive calculation in the method run:
```

  @ReactMethod
  public void run(Callback c) {
    long t = System.currentTimeMillis();
    ByteArrayOutputStream bos = new ByteArrayOutputStream();
    for (;;) {
      try {
        bos.write((int) Math.floor(Math.random() * 256));
      } catch (Throwable e) {
        Log.w("A", "Expensive calculation stopped");
      }
      long now = System.currentTimeMillis();
      if (now > t + 5000) {
        break;
      }
    }
    c.invoke();
  }
```
This methods mimics an expensive operation that lasts for 5 seconds. In the real world I resize bitmaps and send them over the network but this snippets here is simpler and reproduces always the problem.

4. Launch the application on a phone (OnePlus 3T on Android 7.1.1 here, but issue appears also on Samsung and Sony phones with stock Android or not), these phones all have 4 or 2 threads.

5. Click the button 

### Expected Behavior

I would expect:
- the button highlights in yellow as soon as I press or end pressing the button (because of the underlayColor)
- the view rerenders a few frames later with a 2 below the button (because of the setState)
- 5 seconds later the view rerenders with a 3 below (because of the setState in the callback)
### Actual Behavior
- nothing is rendered when the user presses the button: there is no highlight feedback, no state change. Basically at this point the users of my app press again the button because they have no feedback it has been pressed.
- 5 seconds later the view rerenders directly with a 3 below. We never see the rendering corresponding to the state a: 2, nor the highlight of the button.
- During these 5 seconds the UI is completely not responsive, rotating the phone during these 5 seconds will leave black pixelxs at the top as if the portrait rendering had been rotated in a landscape rendering with an image rotation...

### Reproducible Demo
I published the project reproducing the issue at: https://github.com/joIivier/react-native-nonresponsive-reproduction
git clone then npm install then running this project on an android phone should reproduce this issue

### Solution attempts
I read the performance guide especially the part about non responsive buttons  but considered that this situation was not covered since my render method is very simple.
- I still tried to wrap the call to the native method in `setTimeout(,0)` and at this point:
I could see the highlight of the button, but not the rendering with the state a:2
- I then tried to move the setState({a:2}) outside the setTimeout and then saw nicely my state change AND my button press.
But all the other changes in the UI that happen during the next 5 seconds are not happening so this is really an issue since any user of my application consider it as non responsive. I've added setTimeouts around all my TouchableHighlights in the meantime so that they see at least the press feedback but the next renders that are supposed to happen while my application performs its background task are not happening.

**Comment by hey99xx** [comment]
If you read the docs, you'll see that it's your native module implementation that is frowned upon:
http://facebook.github.io/react-native/docs/native-modules-android.html

> Native modules should not have any assumptions about what thread they are being called on, as the current assignment is subject to change in the future. If a blocking call is required, the heavy work should be dispatched to an internally managed worker thread, and any callbacks distributed from there.

The problem is that you're waiting for the 5 second timeout (or heavy image processing, whatever) in the native module thread. This thread is also the point of interaction of JavaScript into the native views where all calls are enqueued to be processed on the main UI thread. So by doing a heavy operation there, you've blocked the entire communication bridge.

If you look at how networking is implemented for example, nothing is actually blocking the thread.
https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/modules/network/NetworkingModule.java

Not really a bug report, but a question about implementing native modules, which in my opinion is already covered sufficiently.

**Comment by joIivier** [comment]
Ohh right I never saw this chapter in the docs and was assuming everything was supposed to be non-blocking. It makes a lot more sense now. I'll change my native Android module to be non blocking then.
Thanks a lot!

Olivier

**Comment by wu464995183** [comment]
@hey99xx  i look  the file :  https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/modules/network/NetworkingModule.java

@ReactMethod
  public void sendRequest(){}

It also seems to be blocking the thread... because it not open subThread in the method. okhttp also can be blocking this thread.

**Comment by MultiformMusic** [comment]
Hello Olivier,

Do you solve your problem ? 
I have the same for android module (but not for ios swift module), i've tried some solutions but my android module always block the react native ui.

**Comment by joIivier** [comment]
Yes, I just wrapped all my expensive calculations in [AsyncTasks](https://developer.android.com/reference/android/os/AsyncTask.html)

**Comment by MultiformMusic** [comment]
Thanks for your answer, i will try AsyncTasks

**Comment by MultiformMusic** [comment]
Yes, it works fine for me !!
