### ISSUE TITLE
[React] Unique "key" pop message. Is there a way to console.log out the offending view?

### ISSUE THREAD

**Issue by jaygarcia** [facebook/react-native#1484]
I had some code where i got the following message (i've since manually reviewed my code & resolved):

```
Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of exports. See http://fb.me/react-warning-keys for more information.
```

For newer developers, is there something that can be done to alert them as to the origin of the issue? (class name, method name, etc?)

**Comment by alinz** [comment]
Usually these warnings are very accurate. However if you export your component directly without setting it to a variable and also not set [displayName](https://facebook.github.io/react/docs/component-specs.html#displayname) of the component, debug information won't have enough information to point you to right component. Take a look at the warning code [here](https://github.com/facebook/react/blob/e47fa115bb37efe627ff8eed712aaf1b97394f56/src/isomorphic/classic/element/ReactElementValidator.js#L101-L103). This code requires element object which contains `displayName`.

Here are some examples:

```js
//this is bad
module.exports = React.createClass({ ... });

//this is good
module.exports = React.createClass({
    displayName: 'MyAwesomeItem',
    render() {
    }
});

//This is good as well. As long as you are using JSX, since JSX automatically set displayName for you.
var MyAwesomeItem = React.createClass({ ... });

module.exports = MyAwesomeItem
```

So I guess, it comes down to the best practices when you writing React and React-Native applications.

**Comment by jaygarcia** [comment]
@alinz, makes a lot of sense. I guess the key here is to ensure that you're helping the tool help you ;).

Reminds me of this skit: https://www.youtube.com/watch?v=OHXyVbxijko
