### ISSUE TITLE
[0.46.0] react-native link is broken

### ISSUE THREAD

**Issue by ttdat89** [facebook/react-native#14857]
### Is this a bug report?

Yes

### Environment

1. `react-native -v`: 0.46

Then, specify:

1. Target Platform (e.g. iOS, Android): Android
2. Development Operating System (e.g. macOS Sierra, Windows 10): MacOS Sierra
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant): SDK 25

### Steps to Reproduce
1. react-native init
2. yarn add react-native-svg (or any package that need to be linked to native projects)
3. react-native link

### Expected Behavior

react-native-svg is linked to Android project

### Actual Behavior

Nothing happen

**Comment by hopeMing** [comment]
+1

**Comment by kuniiskywalker** [comment]
+1

**Comment by grabbou** [comment]
It's fixed in master, I am cherry-picking and releasing a fix later today. Thanks for the report.

**Comment by tak3mat3k** [comment]
@grabbou did you release the fix?

**Comment by grabbou** [comment]
Not yet, waiting for major packager fix to release one version at a time.

**Comment by w8choi** [comment]
shouldn't it be open until the fix is actually released?

**Comment by grabbou** [comment]
It's being released now, please try 0.46.1 in like an hour.

**Comment by w8choi** [comment]
still doesn't link properly on Android (doesn't add compile project on app/build.gradle and if I run react-native link again, it makes duplicate on settings.gradle and MainApplication.java)

**Comment by danieljvdm** [comment]
I'm getting this behavior on 47

**Comment by jdelafon** [comment]
Still happening in 0.51.

**Comment by alex1a** [comment]
Still happening to me.

react-native-cli: 2.0.1
react-native: 0.51.0
