### ISSUE TITLE
Websocket .ping and .onpong missing

### ISSUE THREAD

**Issue by msageryd** [facebook/react-native#14855]
Websocket in RN seems to to respond correctly with a pong when ping is received (as per the Websockets spec.). 

It would be great if there also where a function to send a `ping` and an event for knowing when `pong` is received.

Like this:

    var ws = new WebSocket('ws://host.com/path');

    ws.ping();

    ws.onpong = () => {
      // pong received  
      // this socket is alive
    };

**Comment by msageryd** [comment]
Update.
I found that ping() is already implemented, but not documented. Couldn't find any `pong`event though.

**Comment by tapz** [comment]
Android native code uses OkHttp for WebSocket and that does not seem to handle pong. However, RN codebase includes an iOS version of OkHttp and it supports pong. RCTSRWebSocket handles pong and calls the delegate, but RCTWebSocketModule does not implement didReceivePong method. Just a few lines of code copy-pasted from onopen to relay the event to JavaScript...

RCTWebSocketModule.m:

```
- (NSArray *)supportedEvents
{
  return @[@"websocketMessage",
           @"websocketOpen",
           @"websocketFailed",
           @"websocketClosed", 
           @"websocketPong"];
}

- (void)webSocket:(RCTSRWebSocket *)webSocket didReceivePong
{
  [self sendEventWithName:@"websocketPong" body:@{
    @"id": webSocket.reactTag
  }];
}
```

WebSocket.js:

```
this._eventEmitter.addListener('websocketPong', ev => {
  if (ev.id !== this._socketId) {
    return;
  }
  this.dispatchEvent(new WebSocketEvent('pong'));
}),
```

RCTReconnectingWebSocket.m
...
RCTWebSocketExecutor.m 
...

**Comment by msageryd** [comment]
That's great news! Thank you.
Maybe a PR on this?

**Comment by tapz** [comment]
I'm thinking about that :-) Probably need to do it to Android OkHttp too.
