### ISSUE TITLE
Scroll Text in tvOS

### ISSUE THREAD

**Issue by skyAnja** [facebook/react-native#14852]
### Is this a bug report?

Yes

### Have you read the Bugs section of the Contributing to React Native Guide?

Yes

### Environment

react-native-cli: 2.0.1
react-native: 0.43.2
node: v6.10.3
npm: 3.10.10
yarn: 0.23.4

1. Target Platform: tvOS
2. Development Operating System: macOS Sierra 10.12.5
3. Build tools: XCode Version 8.3.3 (8E3004b)

### Steps to Reproduce

Text that is vertically too large to fit on a screen. No possibility to scroll this text

### Expected Behavior

If the `Text` or `TouchableHighlight` or `ScrollView` gets focus, the remote keys for 'up' and 'down' should scroll the View and make text below readable

### Actual Behavior

Nothing happens. If there is an element below, this gets focus. Also doesn't work if there is no element above or below

### Tested Possibilities

* Every Combination of nesting `Text` or `TouchableHighlight` or `ScrollView` or `FlatList`
* Give every element a fixed height

### Working native solution 

`descriptionTextView.UserInteractionEnabled = true;
descriptionTextView.ScrollEnabled = true;
descriptionTextView.PanGestureRecognizer.AllowedTouchTypes = new NSNumber[]{(int)UITouchType.Indirect};
descriptionTextView.ShowsVerticalScrollIndicator = true;`

**Comment by JulienKode** [comment]
I have the same problem, so I've created a custom bridged component

I think we need to improve a lot of things to have a better experience on react-native tvOS

**Comment by dlowder-salesforce** [comment]
Thanks for the bug report -- I'll take a look at this issue.

**Comment by dlowder-salesforce** [comment]
@JulienKode @skyAnja please see https://github.com/dlowder-salesforce/react-native/tree/tvos-scrollview-focus for a possible fix.  Includes additions to the RNTester ScrollView example.

**Comment by JulienKode** [comment]
@dlowder-salesforce perfect solution 👍

**Comment by gtebbutt** [comment]
@dlowder-salesforce that does indeed look like a perfect solution! Is there any plan to get this merged in?
