### ISSUE TITLE
[0.45+] Changing zIndex dynamically not working on Android

### ISSUE THREAD

**Issue by ethan605** [facebook/react-native#14854]
### Is this a bug report?

Yes

### Have you read the Bugs section of the Contributing to React Native Guide?

Yes

### Environment

1. `react-native -v`:
```
react-native-cli: 2.0.1
react-native: 0.46.0
```
2. `node -v`: `v8.1.3`
3. `npm -v`: `5.0.3`
4. `yarn --version`: `0.27.5`

5. Target Platform: both
6. Development Operating System: macOS Sierra
7. Build tools: both

### Steps to Reproduce

In RN 0.44, I can dynamically change `zIndex` layout prop for Views on both Android & iOS. But after upgrading to 0.46, only iOS can work as expected, can't make it work on Android.

### Expected Behavior

`zIndex` could be changed dynamically on Android.

### Actual Behavior

Here are screenshot on Android. By tapping on "Change top box" button, it's expected that red box will overlap green & blue boxes, another tap should make green box overlap the others, and so on. This works on iOS, but not on Android.

![zIndex bug on Android](http://i.imgur.com/14Tr4Xu.png)

### Reproducible Demo

Please see this [gist](https://gist.github.com/ethan605/36422ef692c1d81d699fa6202b40dee7).

**Comment by Noitidart** [comment]
I have the same issue here - with screencasts - and git clone'able super simple app - https://github.com/facebook/react-native/issues/8968#issuecomment-298992588

That comment links to stackoverflow - https://stackoverflow.com/questions/45021849/zindex-not-working-on-android-0-46-but-does-on-ios-and-even-uwp-windows

zIndex works perfectly as expected on iOS and even windows (UWP) but not on Android :(

I am using 0.46.1

**Comment by ruwusu** [comment]
hack
{left:0,zIndex:10} or {top:0,zIndex:10}

**Comment by ruwusu** [comment]
hack style:
{left:0,zIndex:10} or {top:0,zIndex:10}

**Comment by Noitidart** [comment]
Thanks @ruwusu very much for sharing a work around. I tried it but it didn't work. May you please help me understand the hack. I even tried `zIndex` of `999` but it still wouldn't work.

**Comment by ethan605** [comment]
Thanks to @ruwusu, it seems that the `elevation` trick could work for now. There's only a problem with shadow effects with elevation, but that's better than not working.

**Comment by pqthang97** [comment]
![image](https://user-images.githubusercontent.com/14305217/28490332-b47f0392-6f01-11e7-8d9e-85356b175974.png)
I have this problem on 0.45.1 and 0.46.4.
I set zIndex of 100, position absolute. It work fine in iOS but not android.

**Comment by linnett** [comment]
`elevation` is certainly a decent work-around, thanks for that. It does not solve the problem with `zIndex` in Android. Defo a bug I can reproduce

**Comment by phips28** [comment]
we have the same issue on android (works on iOS). any news how to fix this on android?

<img width="767" alt="screenshot 2017-08-29 13 50 06" src="https://user-images.githubusercontent.com/3694800/29819423-011ca70e-8cc1-11e7-855d-e8e5abaae597.png">

**Comment by hyochan35** [comment]
I am waiting for this one too ..

**Comment by rtman** [comment]
Same here

_Sent from my Google Nexus 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by syardumi** [comment]
+1

**Comment by arcollector** [comment]
use elevation property, set it to 1 for example and you must put the container at the same level, elevation works at sibling level

**Comment by rtman** [comment]
@ethan605 
Is there a fix for this? Why is this closed?

**Comment by mtnst** [comment]
still not working, please can someone take care of this issue.

**Comment by Noitidart** [comment]
I think it was closed because I think the similar/same issue is addressed here - https://github.com/facebook/react-native/issues/8968

**Comment by XBT1** [comment]
same here

**Comment by ethan605** [comment]
@rtman 
Firstly, it seems that the issue is no more active with RN team
Secondly, the workaround solution (using `zIndex`) is acceptable

**Comment by Noitidart** [comment]
@ethan605 this is an active issue, it's just a duplicate. The `zIndex` solution is also not a workaround, it is the actual bug here. The behavior differs greatly, especially when it comes to handling presses in the `zIndex`ed views.

**Comment by rtman** [comment]
@Noitidart  right that's what I thought was happening. I just noticed in react-natiave 0.49 release there is a bugfix to zIndex, hopefully that fixes the issue. Will have a look soon.

**Comment by Noitidart** [comment]
I'm praying it's fixed in 0.49 too :) Long standing bug and never had a feasible workaround. :(

**Comment by ethan605** [comment]
@Noitidart @rtman thanks for your feedbacks. I've closed this due to a long time of inactivity. Now reopen to raise it again. Hope that a proper fix will be provided soon.

**Comment by Noitidart** [comment]
Thank you sir. I think you were right to close this though as it's a duplicate of that issue. I don't know if that patch fixes this though, we'll know in a bit, as soon as that patch releases.

**Comment by Noitidart** [comment]
Hey all I just tried using 0.49.3 and a fix landed! Yahoo. Try it again it might work, let us know.

**Comment by rtman** [comment]
Agreed 0.49.3 fixes my issue

_Sent from my Google Nexus 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by AugustoAleGon** [comment]
Same mistake!
