### ISSUE TITLE
[RCTConvert] +[RCTConvert UIColor:] is not thread safe

### ISSUE THREAD

**Issue by jwyld** [facebook/react-native#1485]
If there are multiple contexts each using their own thread, it's possible to get multiple entering into +[RCTConvert UIColor:] at close to the same time.  colorCache is an unprotected, static cache.  As a result, all threads may attempt to adjust it at RCTConvert.m:586.  NSMutableDictionary is not prepared for such.

**Comment by javache** [comment]
Color conversion now happens on the native side.
