### ISSUE TITLE
Running Xcode's "analyze" on Yoga code surfaces issues

### ISSUE THREAD

**Issue by Mensa-func** [facebook/react-native#14859]
The following commands produced analyzer issues:
	Analyze /Volumes/Untitled\ 2/work/React-native/testapp/node_modules/react-native/ReactCommon/yoga/yoga/YGNodeList.c
	Analyze /Volumes/Untitled\ 2/work/React-native/testapp/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.c
(2 commands with analyzer issues)

The following build commands failed:
	PhaseScriptExecution Install\ Third\ Party /Volumes/Untitled\ 2/work/React-native/testapp/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/double-conversion.build/Script-190EE32F1E6A43DE00A8543A.sh
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/testapp.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/testapp.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by weberli** [comment]
I have the same problem...

**Comment by hramos** [comment]
Duplicate of #14423

**Comment by sandeepsparity** [comment]
Remove Build folder from IOS
 Now run - >  react-native run-ios
