### ISSUE TITLE
Unable to create new "react-native init myAwesomeProject"

### ISSUE THREAD

**Issue by aung-win** [facebook/react-native#14861]
This is the first time I setup react-native. I'm trying to create new react-native project. Nodejs, Python, JDK, Android SDK and react-native cli all are correctly installed on my Windows Server 2012 64-bit.  

node -v : v6.11.0
npm -v : 5.1.0
yarn --version : 0.27.5
react-native -v : 2.0.1

When I create my first react-native project from Command Prompt run as Administrator.
**react-native init albums**
About a miniute late the following error occur.

______
Arguments:
C:\Program Files (x86)\nodejs\node.exe C:\Users\Administrator\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js add react-native --exact

PATH: 
  C:\Python27\;C:\Python27\Scripts;C:\Program Files\PHP\v5.3;
C:\ProgramData\Oracle\Java\javapath;
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;
C:\Windows\system32;
C:\Windows;
C:\Windows\System32\Wbem;
C:\Windows\System32\WindowsPowerShell\v1.0\;
C:\Program Files\Microsoft SQL Server\110\DTS\Binn\;
C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;
C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;
C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\PrivateAssemblies\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;
C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;
C:\Windows\system32\config\systemprofile\.dnx\bin;
C:\Program Files\Microsoft DNX\Dnvm\;
C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;
C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;
C:\Program Files\Microsoft\Web Platform Installer\;
C:\android_sdk\platform-tools;
C:\android_sd;C:\ProgramData\chocolatey\bin;
C:\Program Files (x86)\nodejs\;
C:\Users\Administrator\AppData\Local\atom\bin;
C:\android_sdk\platform-tools;
C:\android_sdk\tools;
C:\Python27;
C:\Python27\Scripts;
C:\Users\Administrator\AppData\Roaming\npm

Yarn version: 
  0.27.5

Node version: 
  6.11.0

Platform: 
  win32 ia32

npm manifest: 
  {"name":"albums","version":"0.0.1","private":true,"scripts":{"start":"node node_modules/react-native/local-cli/cli.js start"}}

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

Trace: 
  Error: 0:error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac:openssl\ssl\s3_pkt.c:535:
  
      at Error (native)

_________________

P.S : I aready tried with node.js 64-bit and 32-bit. Both are same error.

**Comment by reense** [comment]
Same. Re-installed everything (Including node), but still this error.

**Comment by hramos** [comment]
What react native version are you using? Seems like #14866 (which is newer, admittedly) may already cover the issue where new projects in 0.46 fail to run.

**Comment by aung-win** [comment]
react-native -v : 2.0.1

I'm not reach that stage that you mention. #14866
My error occur after execute the following command
react-native init albums

**Comment by aung-win** [comment]
Thanks. @hramos 
My current npm version is 5.1.0.
Problem solved by changing npm version to 4.0
`npm install -g npm@latest-4`
