### ISSUE TITLE
New project fails on react-native@0.46

### ISSUE THREAD

**Issue by iRoachie** [facebook/react-native#14866]
### Is this a bug report?

Yes

### Have you read the Bugs section of the Contributing to React Native Guide?

Yes

### Environment

1. `react-native -v`: 0.46.0
2. `node -v`: 8.1.3
3. `npm -v`: 5.0.3
4. `yarn --version` (if you use Yarn): 0.27.5

Then, specify:

1. Target Platform (e.g. iOS, Android): iOS
2. Development Operating System (e.g. macOS Sierra, Windows 10): macOS Sierra (10.12.5 (16F73)
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant): Xcode 8.3.3

### Steps to Reproduce

(Write your steps here:)

1. react-native init Test
2. cd Test
3. react-native run-ios

### Expected Behavior

App would go through build process and start app in iOS Simulator, and packager in a terminal window.

### Actual Behavior

Error in simulator
![simulator screen shot jul 6 2017 9 34 25 am](https://user-images.githubusercontent.com/5962998/27913491-4eeda644-622e-11e7-97ef-b3329f761296.png)

Error in packager
[Terminal Saved Output.pdf](https://github.com/facebook/react-native/files/1127997/Terminal.Saved.Output.pdf)

### Reproducible Demo

It's a fresh project built with react-native-cli.

**Comment by ryan-burmeister** [comment]
I've had a lot of issues with React Native version 0.45 and up. One thing that I found is that React Native doesn't play well with npm 5. Switch to npm 4. Do this with `npm install -g npm@latest-4`. If that doesn't help, simply switch to React Native 0.44.0. That's what I'm using, and you're not missing out on much by going back. When starting a new project, run `react-native init projectname --version 0.44.0`. Hope that helps!

**Comment by iRoachie** [comment]
@ryan-burmeister I had no problems on react-native@0.45 with npm 5. This is a new problem in 0.46

**Comment by estherleah** [comment]
I also had this problem on Windows/Android. I used `react-native init name --version react-native@0.45.1` and it solved the problem for me. It seems to be a problem with the latest version.

**Comment by iRoachie** [comment]
@estherleah I'm aware. I have a few projects that I upgraded that are showing the same problem. I wanted to see if it was a problem with additional libraries, but making a fresh project confirms it's a problem with the new version

**Comment by iRoachie** [comment]
Removing .babelrc seems to temporarily fix the issue

**Comment by ds300** [comment]
Same reproduction steps here. I'm getting the same red screen of death, but also the packager that is started by the `run-ios` command dies with the following:

```
Last login: Thu Jul  6 18:59:58 on ttys000
/Users/dshe/code/react-native-shit/TestTransformer046/node_modules/react-native/scripts/launchPackager.command ; exit;
➜  ~ /Users/dshe/code/react-native-shit/TestTransformer046/node_modules/react-native/scripts/launchPackager.command ; exit;



















/Users/dshe/code/react-native-shit/TestTransformer046/node_modules/babel-core/lib/transformation/file/options/option-manager.js:328
        throw e;
        ^

ReferenceError: Unknown plugin "transform-runtime" specified in "/Users/dshe/code/react-native-shit/TestTransformer046/node_modules/regenerator-transform/package.json" at 0, attempted to resolve relative to "/Users/dshe/code/react-native-shit/TestTransformer046/node_modules/regenerator-transform" (While processing preset: "/Users/dshe/code/react-native-shit/TestTransformer046/node_modules/babel-preset-react-native/index.js")
    at /Users/dshe/code/react-native-shit/TestTransformer046/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/dshe/code/react-native-shit/TestTransformer046/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/dshe/code/react-native-shit/TestTransformer046/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/dshe/code/react-native-shit/TestTransformer046/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at compile (/Users/dshe/code/react-native-shit/TestTransformer046/node_modules/babel-register/lib/node.js:103:45)
    at loader (/Users/dshe/code/react-native-shit/TestTransformer046/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/dshe/code/react-native-shit/TestTransformer046/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
```

**Comment by iRoachie** [comment]
@ds300 It looks like the same error i had (uploaded the pdf file above).

**Comment by holasebas** [comment]
+1

**Comment by millerbennett** [comment]
+1

**Comment by coolguy001tv** [comment]
I solved it by edit `node_modules/react-native/scripts/packager.sh`
I find it ok if i run `npm start`. 
So modify packager.sh like this:
```
THIS_DIR=$(dirname "$0")
cd "$THIS_DIR/../../../"
# node "./local-cli/cli.js" start "$@"
node "node_modules/react-native/local-cli/cli.js" start "$@"
```

**Comment by Richard-Cao** [comment]
Same problem

**Comment by xiaozhouwu** [comment]
me too, same problem. when will this be solved?

**Comment by iRoachie** [comment]
@xiaozhouwu It's already being worked on.

**Comment by hramos** [comment]
0.46.1 is now out, please give it another go. As always, make sure to clear out your node_modules directory and run `npm install` again.

**Comment by iRoachie** [comment]
Confirming fix in 0.46.1. Great works guys! @hramos @grabbou

**Comment by oeddyo** [comment]
still seeing this: 

➜  albums react-native -v
react-native-cli: 2.0.1
react-native: 0.46.1

**Comment by 452MJ** [comment]
+1 @oeddyo

**Comment by nonotest** [comment]
have this in 46.2

**Comment by mkraft** [comment]
+1

**Comment by rochapablo** [comment]
```
npm run android

> app@0.0.0 android /app
> react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res && react-native run-android

Scanning folders for symlinks in /app/node_modules (20ms)
Scanning folders for symlinks in /app/node_modules (18ms)

Cannot find module 'react-native/packager/transformer'

npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

```
"react": "16.0.0-alpha.12",
"react-native": "^0.49.3",
```

**Comment by Alinux61** [comment]
@rochapablo this code work, thanks :)
react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res

**Comment by varandrew** [comment]
The same problem.I tried to switch to npm 4 and the react packager was working.But it didn't work.Now should i downgrade  react-native to v0.44 ? Cool.

Environment
1. react-native -v: 0.49.5
2. node -v: 8.0.0
3. npm -v: 4.6.0
4. yarn --version (if you use Yarn):  nope

**Comment by arapocket** [comment]
Why is this closed? And why is this still a problem after all these months?

**Comment by Zuckjet** [comment]
+1
