### ISSUE TITLE
react-native run-android caching mobile device

### ISSUE THREAD

**Issue by aditya1027** [facebook/react-native#14878]
Hello,

When i am using `react-native run-android` command in my android 4.x version, content is not changing. I am getting the old content every time. I have googled this issue but didn't get any solution.

Please help me with this issue. I want to make an app for android 4.x version mobile devices.

**Comment by vigzmv** [comment]
Is the packager running? Need more information.

**Comment by aditya1027** [comment]
@vigzmv I am new in RN. Please let me know how to check whether it's running or not.

**Comment by vigzmv** [comment]
Follow this. https://facebook.github.io/react-native/docs/getting-started.html
Start `react-native start` in one terminal and do `react-native run-android` in another.

Are you able to see your app, is there any errors in terminal or in app screen ?

**Comment by DeliDoktoru** [comment]
hi did u make bundle ? if ur problem like this https://github.com/facebook/react-native/issues/14837 lets talk

**Comment by hramos** [comment]
The bug report is missing some necessary details. Please read the contributing guide and open a new issue, thanks!
