### ISSUE TITLE
App Super Slow When Using Debugger

### ISSUE THREAD

**Issue by keeleycarrigan** [facebook/react-native#14874]
When using the Chrome debugger the application is so slow it gets stuck. When I disable the JS debugger the app runs as normal.

Using RN 0.46

**Comment by charpeni** [comment]
Unfortunately, that's the downside of Chrome debugger as it executes JavaScript into V8 engine instead of JavaScriptCore. 

Unless it's much slower than the previous version?

**Comment by keeleycarrigan** [comment]
Yea when I updated to RN 0.46 my app will rarely load past the launch screen if the debugger is running. If I turn the debugger off I works normally, and this really only started after I used the React Native Git upgrade.
