### ISSUE TITLE
FlatList complex example does not explain 'selected' state & prop

### ISSUE THREAD

**Issue by jkdf2** [facebook/react-native#14872]
The complex example in [the FlatList documentation](https://facebook.github.io/react-native/docs/flatlist.html) goes through pains to set `this.state.selected` with the correct `MyListItem` but provides no motivation for why we care about the `selected` prop in `MyListItem`.

Is the idea that `MyListItem` will use `selected` to style itself depending on whether or not it's a selected element?

If you are already using a `TouchableHighlight` or other `Touchable` that includes feedback and an `onPress` that responds appropriately, is there necessarily a reason to bother with identifying which one is selected?

**Comment by hramos** [comment]
I'm not sure this belongs here in the issue tracker.

**Comment by jkdf2** [comment]
@hramos The intention here is that the documentation be clarified. Either someone (most likely @sahrens) can clarify on this issue and I will update the documentation with a pull request, or they will create a pull request that updates the documentation directly and closes this issue.

Therefore I believe the issue should be re-opened and closed via a pull request that clarifies the documentation.

**Comment by sahrens** [comment]
The example is just showing how to properly manage state across multiple items, for example in a todo list where you can select multiple items then take an action on all of them (like delete them). Feel free to clarify that in a PR if you think it's important and list me as a reviewer.
