### ISSUE TITLE
[TabBarIOS] The tintColor attribute of TabBarIOS is not working

### ISSUE THREAD

**Issue by maplebaby** [facebook/react-native#1488]
[Bug]The tintColor attribute of TabBarIOS isn't effective！Should it be white？

![2015-06-01 10 11 45](https://cloud.githubusercontent.com/assets/2143705/7931585/57b62200-0944-11e5-8a47-1c6093c7c16a.png)
![ios simulator screen shot 2015 6 1 10 11 15](https://cloud.githubusercontent.com/assets/2143705/7931672/2d47a0ba-0945-11e5-8c11-73bf6e6b5548.png)

**Comment by cmcewen** [comment]
I just cloned fresh from master and it works fine for me - are you using the latest version?
![screen shot 2015-06-02 at 2 53 00 pm](https://cloud.githubusercontent.com/assets/1307633/7944183/30cdc39e-0937-11e5-917a-932cb8889454.png)

**Comment by maplebaby** [comment]
Yes it is when clone the master。

**Comment by ide** [comment]
Thanks for chiming in @cmcewen
