### ISSUE TITLE
WebView didn't get canGoBack correctly

### ISSUE THREAD

**Issue by silver6wings** [facebook/react-native#14889]
### Have you read the Bugs section of the Contributing to React Native Guide?

(Write your answer here.)

### Environment

1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.45.1
2. `node -v`:
v8.1.2
3. `npm -v`:
5.0.3
4. `yarn --version` (if you use Yarn):
0.24.6

Then, specify:

1. Target Platform (e.g. iOS, Android):
iOS
2. Development Operating System (e.g. macOS Sierra, Windows 10):
macOS Sierra
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant):
iOS >8.0 Xcode 8.3.3

### Steps to Reproduce

1.add an webView and a button call webView's goBack
2.view some page and go back
3.check whether the canGoBack is right

### Expected Behavior

the canGoBack is false when back to the first page
the canGoBack is true when viewing deeper page

### Actual Behavior

the canGoBack sometime is false at the page which is not the first loaded page.

**Comment by hramos** [comment]
The bug report is missing some necessary details. Please read the contributing guide and open a new issue, thanks!

**Comment by 0x5e** [comment]
same problem.
`canGoBack` sometimes correct but sometimes wrong

**Comment by 0x5e** [comment]
When the second page is loading, I get `onNavigationStateChange` callback contains wrong `canGoBack` as `false`, after loading finished, I get correct `canGoBack`. Tested on iOS 10.0.3 & Android 7.1.1, RN 0.49.3.

**Comment by mmiani** [comment]
same issue in RN 0.50.3

**Comment by ngankt2** [comment]
+1

**Comment by RLesser** [comment]
Still happening, this especially hurts because there's no other way (that I know of) to correctly tell if the current webview can go back.

**Comment by ashconnell** [comment]
Just confirming this is a bug.

**To Reproduce:**

1. Instantiate a WebView like so
```
    <WebView
        source={{ uri: 'https://www.google.com' }}
        onNavigationStateChange={ ({ canGoback }) => console.log(canGoBack) }
    />
```
2. Click anything (eg the banner image) to navigate to a new page

**What Happens:**
The console logs `false` as the next page begins to load, and then `true` after the page is loaded

**What should happen:**
The console logs `true` as the next page begins and `true` after the page is loaded

**Comment by mmorcc** [comment]
in android the console logs true as the next page begins to load and true after the page has loaded
in ios is wrong

**Comment by sapjax** [comment]
@hramos  Please open this bug again  🤔

**Comment by hramos** [comment]
Please open a new issue.

**Comment by iamdurui** [comment]
When the second page is loading, I don't get  onNavigationStateChange callback , Tested on iOS 10.3.3 , RN 0.46.2, but the Android don't have this bug

**Comment by peanutli** [comment]
Not fist page,iOS 11.0 no have this problem,canGoback == true,but iOS 11.4 have this problem, canGoback == false.
