### ISSUE TITLE
utf8 is not a function

### ISSUE THREAD

**Issue by zgc2537** [facebook/react-native#14882]
Hello,
I've updated react native to 0.46 from 0.44 for my company project. But problem occurred , when i compiled release version.

** I initiated a new 0.46 react native project, the problem also exists.**

![image](https://user-images.githubusercontent.com/8650623/27947178-5c7ec88e-6327-11e7-80ce-cd3994d88613.png)

![image](https://user-images.githubusercontent.com/8650623/27947153-43896b04-6327-11e7-91c7-d713498a4b43.png)
The package file content is : 
{
  "name": "smartpark",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "babel-core": "^6.25.0",
    "react": "16.0.0-alpha.12",
    "react-native": "0.46.0",
    "react-native-image-crop-picker": "^0.14.1",
    "react-native-progress": "^3.3.0",
    "react-native-splash-screen": "^2.1.0",
    "react-native-tab-navigator": "^0.3.3",
    "react-navigation": "^1.0.0-beta.11",
    "react-redux": "^5.0.5",
    "redux": "^3.7.1",
    "redux-persist": "^4.8.2",
    "redux-thunk": "^2.2.0",
    "start": "^5.1.0"
  },
  "devDependencies": {
    "babel-jest": "20.0.3",
    "babel-preset-react-native": "2.1.0",
    "jest": "20.0.4",
    "react-test-renderer": "16.0.0-alpha.12",
    "redux-devtools": "^3.4.0"
  },
  "jest": {
    "preset": "react-native"
  },
  "main": "index.android.js",
  "repository": {
    "type": "git",
    "url": "ssh://git-gogs@git.hanyunsh.com:10022/zgc2537/SmartPark.git"
  },
  "author": "",
  "license": "ISC",
  "description": ""
}

thx

**Comment by zgc2537** [comment]
"react-native run-android" is ok

**Comment by hramos** [comment]
The bug report is missing some necessary details. Please read the contributing guide and open a new issue, thanks!

**Comment by zgc2537** [comment]
@dgoudy Thx, it works for me.

**Comment by roofiah** [comment]
@dgoudy i have same problem. can you explain step detail for it?. thanks

**Comment by zgc2537** [comment]
@roofiah just update version of nodejs of system to the 6.11.1, and it will be ok.

**Comment by markusguenther** [comment]
I had the same issue and after upgrading node everything was fine again.

Kudos to @zgc2537

**Comment by thinkma** [comment]
thk ,update node is working

**Comment by cdlewis** [comment]
This sounds like it might still be an issue. Package.json says RN supports Node 4+

https://github.com/facebook/react-native/blob/master/package.json#L11

**Comment by lai32290** [comment]
@dgoudy Thanks! I was using node 5.7 because the project that I'm working before. I change to 8.* than it's working.
