### ISSUE TITLE
Using state to get the value of place holder is making it blank, react-native TextInput 

### ISSUE THREAD

**Issue by abhisheklalnediya** [facebook/react-native#14890]
Using state to get the value of place holder is making it blank, react-native TextInput 

### Environment
react-native-cli: 2.0.1
react-native: 0.45.1
node: v6.9.5
npm: 3.10.10

1. Target Platform (e.g. iOS, Android): Android
2. Development Operating System (e.g. macOS Sierra, Windows 10): Mac

### Code
![image](https://user-images.githubusercontent.com/3649024/27958534-44f3a85a-6341-11e7-80d4-0bb3485f1798.png)

## Before State Change, Screen shot
![image](https://user-images.githubusercontent.com/3649024/27958568-6d2b5d86-6341-11e7-909a-27b2de868163.png)

## After State Change screen shot
![image](https://user-images.githubusercontent.com/3649024/27958590-854693b8-6341-11e7-99af-32cc23d58ed2.png)

### To reproduce, 
1. In a TextInput, placeholder attribute, set value using state.
2. Set state with new value

### Expected Result
1. Place holder should change to new value.

### Actual Result
1. Place holder goes blank

**Comment by hramos** [comment]
The bug report is missing some necessary details. Please read the contributing guide and open a new issue, thanks!
