### ISSUE TITLE
react native modal

### ISSUE THREAD

**Issue by baraa95** [facebook/react-native#14893]
### Is this a bug report?

yes

### Have you read the Bugs section of the Contributing to React Native Guide?
no

### Environment

1. `react-native -v`:
2. `node -v`:
3. `npm -v`:
4. `yarn --version` (if you use Yarn):

Then, specify:

1. Target Platform (e.g. iOS, Android):
2. Development Operating System (e.g. macOS Sierra, Windows 10):
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant):

### Steps to Reproduce

(Write your steps here:)

1.use the react native modal module
2. change your phone language to any rtl support
3. return to the app... the modal will not be working and you have to close all the app and reopen it again from zero

### Expected Behavior

i expect to see the modal when i press to show it 

### Actual Behavior

nothing is shown... i have to close all the app and then reopen it agian to show it

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by hramos** [comment]
The bug report is missing some necessary details. Please read the contributing guide and open a new issue, thanks!

**Comment by Nitroman605** [comment]
I am facing the same issue . After changing language the modal does not show up (It shows in console but not in screen ) . 

Did you manged to fix it ?
