### ISSUE TITLE
ImageBackground don't accept resizemode style (Image does)

### ISSUE THREAD

**Issue by Norfeldt** [facebook/react-native#14915]
I upgraded to version 0.46 and implemented `ImageBackground` instead of `Image` but now I can't use `resizemode` anymore in the styling. 

I can't find any docs on the [website](https://facebook.github.io/react-native/) regarding the `ImageBackground`

Is it a bug or name change of the property?

**Comment by hramos** [comment]
Check out the release notes: https://github.com/facebook/react-native/releases/tag/v0.46.1

**Comment by matthewstyers** [comment]
Like @Norfeldt, I ran into this issue but was unable to find any reference to actual usage in the aforementioned release notes or docs. Having discovered a solution, I'm adding the following to expand directions for future travelers beyond 'RTFD':

Per https://github.com/facebook/react-native/blob/dc97e3fb4e1a297d18b9361710290468060626fc/Libraries/Image/ImageBackground.js, `ImageBackground` accepts two style props – `style ` and `imageStyle` – which are (obviously) applied to the internal `View` and `Image` respectively. It's also worth noting that `height` and `weight` values from the container style are applied to the image style automatically.

**Comment by hramos** [comment]
Feel free to send a PR to the docs - they're hosted on this repo.
