### ISSUE TITLE
[0.46.1]No bundle URL present not fixed in 0.46.1

### ISSUE THREAD

**Issue by oeddyo** [facebook/react-native#14913]
**SOLUTION** (LIKELY RELATED TO):

When I turned shadowsocks off, it seems to compile. Maybe that's the problem. Hope it helps 

Is this a bug report?

Yes

Have you read the Bugs section of the Contributing to React Native Guide?

Yes

Environment

react-native: 0.46.1
node: v6.11.0
npm -v: 5.0.1
yarn --version (if you use Yarn): v0.24.6
Then, specify:

Target Platform (e.g. iOS, Android): iOS
Development Operating System (e.g. macOS Sierra, Windows 10): macOS Sierra (10.12.2 
Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant): Xcode 8.3.3

Steps to Reproduce

(Write your steps here:)

react-native init Test
cd Test
react-native run-ios
Expected Behavior

App would go through build process and start app in iOS Simulator, and packager in a terminal window.

Actual Behavior

Error in simulator

![image](https://user-images.githubusercontent.com/1943146/27989988-e11d5ea8-647a-11e7-9d22-00e8698890bc.png)

It's mentioned here: 
https://github.com/facebook/react-native/issues/14866

and seems it's resolved for some users. But for my setting, the problem persists.

**Comment by oeddyo** [comment]
tried everything mentioned in #14866 
including:
downgrade npm to 4.xx
downgrade react-native to 0.45, 0.44 etc

none worked

**Comment by oeddyo** [comment]
btw I'd like to mention that for 

react-native run-android

works for me

**Comment by hramos** [comment]
Is the packager running, and if so, does it display any error? Do you see any logs once the client connects to it?

**Comment by oeddyo** [comment]
Thanks for the response @hramos 

The packager is running. It doesn't mention any errors, but two warnings. Complete output: 

> ~/workspace/album/node_modules/react-native/packager ~
Scanning 565 folders for symlinks in /Users/exie/workspace/album/node_modules (7ms)
 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  Running packager on port 8081.                                            │ 
 │                                                                            │ 
 │  Keep this packager running while developing on any JS projects. Feel      │ 
 │  free to close this tab and run your own packager instance if you          │ 
 │  prefer.                                                                   │ 
 │                                                                            │ 
 │  https://github.com/facebook/react-native                                  │ 
 │                                                                            │ 
 └────────────────────────────────────────────────────────────────────────────┘ 
Looking for JS files in
   /Users/exie/workspace/album 


React packager ready.

Loading dependency graph...jest-haste-map: @providesModule naming collision:
  Duplicate module name: bser
  Paths: /Users/exie/workspace/album/node_modules/react-native/node_modules/jest-haste-map/node_modules/bser/package.json collides with /Users/exie/workspace/album/node_modules/react-native/node_modules/fb-watchman/node_modules/bser/package.json

This warning is caused by a @providesModule declaration with the same name across two different files.
jest-haste-map: @providesModule naming collision:
  Duplicate module name: bser
  Paths: /Users/exie/workspace/album/node_modules/react-native/node_modules/bser/package.json collides with /Users/exie/workspace/album/node_modules/react-native/node_modules/jest-haste-map/node_modules/bser/package.json

This warning is caused by a @providesModule declaration with the same name across two different files.
jest-haste-map: @providesModule naming collision:
  Duplicate module name: fb-watchman
  Paths: /Users/exie/workspace/album/node_modules/react-native/node_modules/fb-watchman/package.json collides with /Users/exie/workspace/album/node_modules/react-native/node_modules/jest-haste-map/node_modules/sane/node_modules/fb-watchman/package.json

This warning is caused by a @providesModule declaration with the same name across two different files.
Loading dependency graph, done.

**Comment by oeddyo** [comment]
it didn't give any errors neither. As soon as I type react-native run-ios, it launched and showed the messages above, the messages remained the same.

**Comment by oeddyo** [comment]
Any idea is this my env only? Do you have a minute to look into this? 

@hramos

**Comment by ctxdl** [comment]
I have the same problem with this as well on the device it may be because the images with @ are not loading anymore

**Comment by oeddyo** [comment]
hi @ctxdl can you elaborate a bit more? 

Did you fix it? If so, how?

Thanks!

**Comment by 452MJ** [comment]
@oeddyo try this then I build successfully. https://hacpai.com/article/1497235254333

![image](https://user-images.githubusercontent.com/13673008/28316268-b8c91aec-6bf4-11e7-8087-d79f8f78a0c9.png)

**Comment by oeddyo** [comment]
Thanks a lot for the suggestion @452MJ 
Unfortunately I tried your suggested setting but it's still giving me the same error :|

**Comment by TrustTheBoy** [comment]
@oeddyo This may be related to the web tools you are using, turn them off, run it again

**Comment by oeddyo** [comment]
@TrustTheBoy 

Actually i figured it most likely related to Shadowsocks that I was using while trying to connect to packager. Thanks for the help.
