### ISSUE TITLE
props.style keys with (final) value "undefined" should be treated as not present

### ISSUE THREAD

**Issue by josvos** [facebook/react-native#14910]
Version: 0.44.2
Platform: Android

Example 1:
`<View style={[{backgroundColor: 'red'}, {backgroundColor: undefined}]} ...>`

In this case, the `backgroundColor` property is treated as not present and the background will get the color of the parent.  This is good, as it allows you to "remove" style properties when cascading styles.

Example 2:
`<View style={[{fontSize: 20}, {fontSize: undefined}]} ...>`

In this case, you get a warning about an invalid props.style key `fontSize` supplied to `View`, even when its final value is `undefined`.  IMHO it would be better to ignore the key if the value is `undefined`.  This allows you to pass stylesheets with (e.g.) both `View` and `Text` properties and override parts that are not valid for a certain component.

**Comment by hramos** [comment]
Thanks for opening the issue, however it looks like a feature request. As noted in the [Issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md) we'd like to use the GitHub issues to track bugs only. Can you implement the feature as a standalone npm module? If not consider sending a pull request or a create an entry on [Canny](https://reactnative.canny.io/feature-requests). It has a voting system and if the feature gets upvoted enough it might get implemented by someone from the community. Closing this now, thanks for understanding!
