### ISSUE TITLE
[Beginner]How to open the ［Location Services］ screen of IOS by react-native？？

### ISSUE THREAD

**Issue by bingfj2008** [facebook/react-native#14923]
How to open the ［Location Services］ screen of IOS by react-native？？

By the way. I tried the way to open location services screen like this.

`if (&UIApplicationOpenSettingsURLString != NULL) {`
`   NSURL *url = [NSURL URLWithString:UIApplicationOpenSettingsURLString];`
`    [[UIApplication sharedApplication] openURL:url];`
`}`
`else {`
`  // Present some dialog telling the user to open the settings app.`
`}`

but it not work!!!

PS. I am also a Beginner Of the Objective-c.

**Comment by vongohren** [comment]
Think if its better to ask this question on: https://stackoverflow.com/questions/tagged/react-native

**Comment by charpeni** [comment]
@facebook-github-bot stack-overflow
