### ISSUE TITLE
[Text] Emoji not supported on Android 4.4.2?

### ISSUE THREAD

**Issue by sirilicious** [facebook/react-native#14929]
### Is this a bug report?

Yes

### Have you read the Bugs section of the Contributing to React Native Guide?

Yes

### Environment

react-native-cli: 2.0.1
react-native: 0.45.1
node: v7.10.0
npm: 4.6.1
yarn: n/a

1. Target Platform: Android
2. Development Operating System: macOS Sierra
3. Build tools: Android Studio 2.3.3, Android 4.4.2

### Steps to Reproduce

1. open [https://snack.expo.io/SyMmc1-rW](https://snack.expo.io/SyMmc1-rW) with your Android device
2. the Emoji "🇺🇸" is not correctly displayed (only on Android, on iOS it is working)
3. wonder why? ;)

### Expected Behavior

Does the react-native Text element provide support for Emojis for Android? It should.

### Actual Behavior

The Emoji is not displayed correctly.

![screenshot_2017-07-10-13-53-48](https://user-images.githubusercontent.com/29576073/28016999-4c60f16e-6577-11e7-8652-d4019bced759.png)

### Reproducible Demo

Check out this [snack](https://snack.expo.io/SyMmc1-rW).

**Comment by hramos** [comment]
It works fine on the emulator used by Snack. Perhaps that emoji is not supported on Android 4?
