### ISSUE TITLE
Yellow box - application not responding after "Dismiss All"

### ISSUE THREAD

**Issue by madox2** [facebook/react-native#14921]
When I press "Dismiss All" button for warnings in yellow box, aplication is not responding to user touches anymore. However "Dismiss" and "Minimize" buttons works fine.

Running on real android device connected via cable on Ubuntu.

```bash
$ react-native -v
react-native-cli: 2.0.1
react-native: 0.42.3
```

I have also found workaround: when app is in this not responsible state, toggle inspector on and off.

**Comment by JakeDoe** [comment]
Please answer this questions:
1. Do buttons work fine before you have press YellowBox buttons? 
2. Have you tried to remove problem code from your application for debug?

**Comment by madox2** [comment]
@JakeDoe yes, application works fine before pressing YellowBox buttons.

**Comment by JakeDoe** [comment]
@madox2 please attach error message text here or take a screenshot. You can turn on debug in chrome (press CMD+D in Simulator for iOS or shake device)

Also, you can delete a part of code while an error disappears and debug problem part.

**Comment by madox2** [comment]
@JakeDoe it is probably not an error in application logic. Application works fine until I press "Dismiss All" button.

However it is not reproducible in fresh new RN project therefore I am closing this issue.
