### ISSUE TITLE
[Remote Debugging] Chrome Debugger affects code behavior. (defines navigator.userAgent)

### ISSUE THREAD

**Issue by mikelehen** [facebook/react-native#1493]
I ran into a situation where a 3rd-party library was working fine when I had the chrome debugger open, but failed when I ran it normally.

It looks like opening the chrome debugger ends up adding/modifying global state.  In particular, navigator.userAgent is undefined when you run normally but if you have the chrome debugger open, it becomes Chrome's user agent.

I don't know how the chrome debugger integration works, but ideally it would not affect the runtime behavior of your app!  Else you end up with these heisenbugs. :-/

**Comment by JohnyDays** [comment]
It actually affects the runtime behavior a lot more than this, since running it on chrome uses google's V8 engine, while the app runtime uses JavascriptCore. I don't know how this would be fixed though, since I don't think the chrome remote debugging protocol supports using a different engine :cry:

**Comment by stan229** [comment]
I'm seeing a similar issue. I wonder if it has something to do with ES6 class usage?


![jun 02 2015 14 25](https://cloud.githubusercontent.com/assets/454130/7943582/5a4a4930-0933-11e5-8385-9ad013ce2c6b.gif)

**Comment by JohnyDays** [comment]
ES6 classes are supported by the packager AFAIK, but some other ES6 features aren't
The full list of supported features is here https://facebook.github.io/react-native/docs/javascript-environment.html#content
All of them are supported in master, because it's using babel.

**Comment by jaygarcia** [comment]
I am using es6 classes with .4.4 and don't see that problem 

JG

:: @moduscreate

:: sent from my mobile device ::

**Comment by stan229** [comment]
Is there anywhere I can set breakpoints to see if JavascriptCore is failing on some bit of code? Not seeing anything in the console output of Xcode.

**Comment by stan229** [comment]
I'm not sure if I'm hunting in the right place but I tried to set some breakpoints on javaScriptDidLoad and bundleFinishedLoading in RCTRootView. They only fire after I enable Chrome debugging. 

I thought it was could have been my simulator settings forcing debugging so I reset the sim, but still seeing the same results.

**Comment by stan229** [comment]
Turns out it was a const keyword! 

If you look at this page you'll see that const in strict mode is not supported by iOS 8 (JavascriptCore).  It does work if you're not using strict mode. In my case, I was in strict mode.
https://kangax.github.io/compat-table/es6/#ios8

@mikelehen see if you're using that anywhere.

**Comment by JohnyDays** [comment]
Cool! This will be supported once babel lands though. (Already in master if you wanna live on the edge)

**Comment by jaygarcia** [comment]
Living on the edge with This project can cause bleeding sometimes. :)

John, any idea when the next version of RN will be cut?


@stan229, please feel free to close this issue.

**Comment by JohnyDays** [comment]
I'm bleeding a bit from living on the edge, but nothing that's unsalvageable with responsible use of shrinkwrap and testing :+1: 
@jaygarcia No idea, I'm not on the core team, but I'm sure 0.5.0 is soon to be released (you can already use the rc)

**Comment by stan229** [comment]
@jaygarcia can't close as I kind of highjacked @mikelehen original post. Hopefully this thread helps him out.

**Comment by ide** [comment]
Closing since 0.5.0 is out
