### ISSUE TITLE
React Native 0.46.1 does not support import/export generator functions

### ISSUE THREAD

**Issue by UlfR** [facebook/react-native#14933]
### Is this a bug report?

yes

### Have you read the Bugs section of the Contributing to React Native Guide?

yes

### Environment

1. `react-native -v`: 0.46.1
2. `node -v`: v7.10.0
3. `npm -v`: 4.2.0
4. `yarn --version` (if you use Yarn): 0.27.5

Then, specify:

1. Target Platform (e.g. iOS, Android): Android
2. Development Operating System (e.g. macOS Sierra, Windows 10): Ubuntu Linux 17.04
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant):

### Steps to Reproduce

(Write your steps here:)

1. Create empty react-native project

2. Add test.js in project root with generator function export:
export function* doSomething() {console.log('test');}
export default {test: doSomething};

3. Change index.android.js to: 
import React from 'react';
import {AppRegistry, Text} from 'react-native';
import {doSomething} from "./test"; //neither this
// import doSomething from "./test"; //nor this doen't work

class GFTest extends React.Component { render(){return <Text>hi!</Text>} }
AppRegistry.registerComponent('gf_test', () => GFTest);

### Expected Behavior

Expected to see screen with 'hi!' string on it

### Actual Behavior

See error screen:
E/ReactNativeJS(13905): undefined is not an object (evaluating 'regeneratorRuntime.mark')
ExceptionsManager.js:63 Cannot read property 'mark' of undefined
handleException	@	ExceptionsManager.js:63
handleError	@	InitializeCore.js:125
reportFatalError	@	error-guard.js:44
guardedLoadModule	@	require.js:121
_require	@	require.js:110
(anonymous)	@	index.android.bundle…&minify=false:52122
executeApplicationScript	@	debuggerWorker.js:40
(anonymous)	@	debuggerWorker.js:65

E/ReactNativeJS(13905): undefined is not a function (evaluating 'this._lazyCallableModules[name]()')
ExceptionsManager.js:63 this._lazyCallableModules[name] is not a function
handleException @ ExceptionsManager.js:63
handleError @ InitializeCore.js:125
reportFatalError @ error-guard.js:44
__guard @ MessageQueue.js:230
callFunctionReturnFlushedQueue @ MessageQueue.js:100
(anonymous) @ debuggerWorker.js:71

### Reproducible Demo

https://github.com/UlfR/gf_test

**Comment by Lepozepo** [comment]
I think changing `babel-preset-react-native` from 2.1.0 to 2.0.0 fixes the issue, it looks like whatever changes have been made to the regeneratorRuntime hit the preset

**Comment by UlfR** [comment]
@Lepozepo no, downgrading babel-preset-react-native does not help.

**Comment by Lepozepo** [comment]
Mmm, yeah, I ended up going back to 0.45.1, ran into the same issue in that version but then modified the preset to 2.0.0 and it started working again (after doing the whole `watchman watch-del-all` stuff).

**Comment by UlfR** [comment]
@Lepozepo sorry, you are right, downgrading babel-preset-react-native + clearing cache fix the problem

**Comment by Lepozepo** [comment]
Awesome!

**Comment by markusguenther** [comment]
I had the same issue and solved this by using variables.

```
export default function* root() {
  let sagaIndex = [
    // some sagas only receive an action
    takeLatest(StartupTypes.STARTUP, startup)
  ];

  yield sagaIndex;
};
```

becomes:

```
const rootSaga = function* root() {
  let sagaIndex = [
    // some sagas only receive an action
    takeLatest(StartupTypes.STARTUP, startup)
  ];

  yield sagaIndex;
};

export default rootSaga;
```

**Comment by asCii88** [comment]
@UlfR why did you close this issue? shouldn't this be supported in the latest version? isn't downgrading just a temporary fix?

**Comment by Manuelandro** [comment]
same here without using `babel-preset-react-native`

**Comment by JulianKingman** [comment]
Search your `node_modules` folder for the `lazyCallableModules` function, for me it's in `react-native-sentry`, opening an issue there: https://github.com/getsentry/react-native-sentry/issues/227

**Comment by vjk2005** [comment]
I had the same issue, began after upgrading expo to `20`. Problem went away just by upgrading to` react 0.48.0`, didn’t touch anything else. Hope this helps someone.

**Comment by iMagdy** [comment]
Just go back to a state where the app was working, check package-lock.json file, and make sure that package.json file match the same versions.

**Comment by omatrot** [comment]
same problem here. What's frustrating is the lack of complete stack trace to see your application code.

**Comment by adamski** [comment]
Been hunting this issue for the last couple of hours. Any updates from people that solved it?
