### ISSUE TITLE
error while using reactnative fbsdk in android 

### ISSUE THREAD

**Issue by mansoorahamedf** [facebook/react-native#14939]
possibly unhandled promise rejection (id 1) type error:undefined is not an object(evaluating result.grantedPermission.toString) in react-native while running it on android device kindly any one help me to debug this error 
this is my code whats wrong with this code i dont know 
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  TouchableOpacity,
  TouchableHighlight
} from 'react-native';
//import {FBLogin, FBLoginManager} from 'react-native-facebook-login';

import FBSDK, { LoginManager,LoginButton } from 'react-native-fbsdk'

export default class fbappss extends Component {

   _fbAuth(){

        LoginManager.logInWithReadPermissions(['public_profile']).then(function(result){

          if (result.isCancelled) {

              alert('Login was cancelled'); 
          } else {

              alert('Login was a success' + result.grantedPermission.toString());
          }
        }, function(error) {

            alert('an error occured:' +error);
        }

        );

        }

  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <View style={{borderWidth: 2, marginBottom: 20}}>
        <TouchableHighlight
          onPress={this._fbAuth}>
          <Text>Login with fbLoginManager</Text>
        </TouchableHighlight>
        </View>
        <LoginButton
          readPermissions={["public_profile","email"]}
          onLoginFinished={
            (error, result) => {
              if (error) {
                alert("Login failed with error: " + result.error);
              } else if (result.isCancelled) {
                alert("Login was cancelled");
              } else {
                alert("Login was successful with permissions: " + result.grantedPermissions)
              }
            }
          }
          onLogoutFinished={() => alert("User logged out")}/>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

AppRegistry.registerComponent('fbappss', () => fbappss);

my react-native version 
react-native-cli: 2.0.1
react-native: 0.46.0
 thanks and help will be appriciated

**Comment by laurent22** [comment]
Please use Stack Exchange as the issue tracker is not for support but for bug reports only.
