### ISSUE TITLE
fetch Api: Read response header 

### ISSUE THREAD

**Issue by anikets43** [facebook/react-native#14942]
Trying out to read the Authorization token sent with response header, but gets only body segment. Is there any way response headers can be read.
`checkLogin(email) {

    var payLoad = {
      method: "POST",
      credentials: 'same-origin',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ email: email })
    }
    fetch(url, payLoad)
      .then((response) => response.json())
      .then((responseData, err) => {
        console.log(responseData);
        AlertIOS.alert(
          "POST Response",
          "Response Body -> " + JSON.stringify(responseData.body)
        )
      })
      .done();`

**Comment by Oddadmix** [comment]
You use `const headers = response.headers.entries();`
