### ISSUE TITLE
[JS Polyfills] Can't find variable: document (potential need for document polyfill)

### ISSUE THREAD

**Issue by hharnisc** [facebook/react-native#1495]
It's understood that React Native doesn't have a document because it eliminates the need for it with native components. However, there are some cases where the `document` is needed by 3rd party node modules and Javascript components that rely on the `document` for initialization purposes. An example of this would be bundled up `Meteor` frontend code that provides communication with the backend (not directly manipulating UI).

Here's an example project to highlight this use case

https://github.com/hharnisc/react-native-official-meteor-client

I've used `meteor bundle` to wrap up on DDP (websocket based communication) and Minimongo (client side in Memory DB) that have a dependency on a few `document` attributes in their setup phase (this list may not be 100% complete)

- document.readyState
- document.addEventListener
 - "DOMContentLoaded"
- document.attachEvent
 - "onreadystatechange"
- window.attachEvent <- might need some of the window functionality as well
 - "load"
- window.addEventListener
 - "load"

I did try to polyfill some of the document and window functionality with [jsdom-jscore](https://github.com/brentvatne/jsdom-jscore) and this got me a little further, but still eventually ended up with the red screen of doom.

So for cases of using document to initialize it might be useful to have **document** and **window** polyfill.

**Comment by vjeux** [comment]
Looks like the only reason meteor relies on document is to figure out when the dom is loaded. In React Native there is no such concept, you can just start running your code right away.

I don't think it's a good idea to add this in react native. I would much rather have meteor update their code and if they don't find addEventListener and readyState then just execute the code right away

**Comment by ide** [comment]
My thinking is that events like 'readystate' and the notion of a document are auxiliary concepts to RN and would better be provided by an npm package if polyfilling `document` is the best direction.

**Comment by hharnisc** [comment]
Agree with you @ide - especially since the JS runtime is ready immediately (good to know @vjeux!). Pulling the polyfill via NPM package would be great. I think the firebase community was dealing with this as well, and seems like one potential first point of friction for new framework communities exploring React Native.

**Comment by AdamBrodzinski** [comment]
+1 I think having an NPM based polyfill that other 3rd party modules (like Firebase, Meteor, etc..) can all use sounds like a fairly good solution!

**Comment by ide** [comment]
@hharnisc, @AdamBrodzinski - is this something you guys want to explore? Since you have a real use case for it I imagine you'll be able to make more progress on it than people who don't.

**Comment by AdamBrodzinski** [comment]
@ide We've talked about it! Hopefully i'll have enough time in a few weeks to contribute :beers:

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/js-polyfills-cant-find-variable-document-potential-need-for-document-polyfill

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
