### ISSUE TITLE
[0.46.1] TextInput wrapt in touchable, will led touchable stop working

### ISSUE THREAD

**Issue by opp100** [facebook/react-native#14958]
### Is this a bug report?

Yes

### Have you read the Bugs section of the Contributing to React Native Guide?

Yes

### Environment

1. `react-native -v`: react-native: 0.46.1
2. `node -v`: v8.1.1
3. `npm -v`: 5.1.0

Then, specify:

1. Target Platform (e.g. iOS, Android): iOS
2. Development Operating System (e.g. macOS Sierra, Windows 10): macOS
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant): Xcode

### Expected Behavior

```
          <TouchableWithoutFeedback onPress={()=>{ //function was working here in 0.45 }>
              <View style={styles.inputContainer}>
                <TextInput
                  editable={false}
                  ref={component => this._input = component}
                  placeholder='Text Input'/>
                <TouchableOpacity
                  onPress={() => {
                    //function only working here now in 0.46
                }}>
                  <View>
                    <Text>Button</Text>
                  </View>
                </TouchableOpacity>
              </View>
          </TouchableWithoutFeedback>
```

### Actual Behavior

The source code above was working perfectly in 0.45, but after I upgrade to 0.46 is not working. However wrapt Image or Text is working fine.

**Comment by opp100** [comment]
Downgrade to 0.45.1 can fix this issue.

**Comment by hramos** [comment]
Can you tell us more about the issue you're reporting? What did you expect and what happened instead?

**Comment by opp100** [comment]
Hey @hramos, 

I have do a sample project on this issue, we can see the TextInput wrapt in touchable is working on 0.45.1. But not working on 0.46.1.

0.46:
![046](https://user-images.githubusercontent.com/19526135/28144649-208f91fe-67b0-11e7-9890-754c57251458.gif)

0.45:
![045](https://user-images.githubusercontent.com/19526135/28144758-c6d3b086-67b0-11e7-8ee3-f2d1fddc1e78.gif)


source code of this demo project:
```
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, {Component} from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  TouchableOpacity,
  TextInput
} from 'react-native';

export default class testProject extends Component {
  state = {
    output: 0
  }

  onPress() {
    this.setState({
      output: ++this.state.output
    })
  }

  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          React Native 0.45.1
        </Text>
        <Text style={styles.instructions}>
          To get started, edit index.ios.js
        </Text>
        <Text style={styles.instructions}>
          {`Press ${this.state.output} times`}
        </Text>
        <TouchableOpacity onPress={() => {
          this.onPress()
        }}>
          <View style={styles.inputContainer}>
            <TextInput
              editable={false}
              style={styles.textInput}
              ref={component => this._input = component}
              placeholder='Text Input'/>
            <View>
              <Text>Text</Text>
            </View>
            <TouchableOpacity
              onPress={() => {
              this.onPress()
            }}
              style={styles.button}>
              <View >
                <Text>Button</Text>
              </View>
            </TouchableOpacity>
          </View>
        </TouchableOpacity>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF'
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5
  },
  inputContainer: {
    flexDirection: 'row',
    borderColor: '#555',
    borderRadius: 3,
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff'
  },
  textInput: {
    width: 200,
    backgroundColor: '#f99',
    height: 40,
    marginRight: 10
  },
  button: {
    marginLeft: 10,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#9f9',
    height: 40
  }
});

AppRegistry.registerComponent('testProject', () => testProject);
```
By the way, anyone knows how to make code in github colourful?

**Comment by hramos** [comment]
Why is everything wrapped in a TouchableOpacity?

**Comment by opp100** [comment]
Generally is unnecessarily warp all in one touchable, but users tap on textInput will be much easier than tap the small icon on side.    For example, if there are one drop down picker nested in this touchable, tap on textInput directly shows the picker, and when users select some option called other, 
Users can instantly input text in that textInput.

From my iPhone

**Comment by JLLLinn** [comment]
This is a regression. Confirm that downgrading works. This is needed for user's input that is not from keyboard (e.g. date picker) and consistency on style.

**Comment by c3098051** [comment]
I just upgraded from RN42 to RN46, and having the same error. Touchable with TextInput now doesn't trigger onPress.

**Comment by eladgel** [comment]
confirm 0.46.4

**Comment by mrtomhoward** [comment]
A temporary fix that works for me is to wrap the TextInput in a View with pointerEvents set to 'none'

That is:
```
<TouchableOpacity onPress={()=>{console.log('press')}}>
   <View pointerEvents='none'>
      <TextInput editable={false} />
   </View>
</TouchableOpacity>
```

This is working for me right now on RN 0.47.1.

**Comment by ilonashub** [comment]
Thanks for the fix! this doesn't work with `TouchableWithoutFeedback` tough

**Comment by bermann** [comment]
@ilonashub I'm having the same issue, did you find a way to solve it?

**Comment by ofilipowicz** [comment]
Still not fixed :(

**Comment by ofilipowicz** [comment]
@bermann @ilonashub setting pointerEvents to `box-only` makes it work with `TouchableWithoutFeedback `

**Comment by PoliakovMaksym** [comment]
`"react-native": "0.51.0"`

`TouchableWithoutFeedback` onPress event still not working with `TextInput` inside.

But wrapping `TextInput` with `View` that has pointerEvent="box-only" still works. Thanks @mrtomhoward and @ofilipowicz

**Comment by hoscarcito** [comment]
@JLLLinn Hey Jiaxin you are saying that is it possible to open a Picker from a touchable??

**Comment by JLLLinn** [comment]
@hoscarcito Yes, you can use the touchable to trigger open a time picker

**Comment by JeremyRicky** [comment]
still happening in RN 0.54.4

**Comment by izikandrw** [comment]
still happening in 0.54.4

**Comment by izikandrw** [comment]
still happening on 0.54.4. @mrtomhoward workaround above still works (thanks!)

**Comment by Arshiamidos** [comment]
oh @mrtomhoward  god bless you 👏👏

**Comment by nihp** [comment]
Same issue for me also. TextInput not seen inside the text box.

Selected test is shown as outside the text box.

**Comment by eliasrodeloso** [comment]
Still happening on RN0.55.4. @mrtomhoward workaround works just fine.

**Comment by jpamarohorta** [comment]
Still happening on RN 0.56

**Comment by venkatmithunk** [comment]
onPress not working with TouchableNativeFeedback ( RN 0.56 )
Workaround doesn't work.
Also I need ripples which are only working with pointerEvents='box-only' 
`<FlatList
            renderItem={({item}) => {
              return(
                      <TouchableNativeFeedback onPress={()=> {this.props.navigation.navigate('Channels');console.log("dsds")}} background={TouchableNativeFeedback.Ripple('#d3d3d3')}>
<Text>Help plz</Text>
</TouchableNativeFeedback>
              )
            }}
            keyExtractor={(item, index) => index.toString()}
          />
`

**Comment by numen31337** [comment]
The @mrtomhoward's solution works. Unfortunately, on the Android side, it prevents text fields from being editable (i.e. user can't place the cursor in the middle of a word).

**Comment by AlainGauthier** [comment]
when would that be solved?
