### ISSUE TITLE
who can help me ? bundling 'index.android.js' 0.0% (0/1) , failed.

### ISSUE THREAD

**Issue by hahai23456789** [facebook/react-native#14961]
![image](https://user-images.githubusercontent.com/23414297/28096595-b246bc96-66dc-11e7-93a4-858db831167b.png)
![image](https://user-images.githubusercontent.com/23414297/28096623-cfafecee-66dc-11e7-9844-9bc7ff4076a0.png)

**Comment by opp100** [comment]
have you cd into your project folder?

**Comment by hahai23456789** [comment]
@opp100 yes i have

**Comment by opp100** [comment]
Can you do a screen shot of your project folder?

From my iPhone

**Comment by hahai23456789** [comment]
I probably ate shit, installed watchman, went to fuck watchman and bothered me for 2 days

**Comment by hahai23456789** [comment]
@opp100  
Thank you for your help, I found the reason, because my computer installed watchman before, I can work properly after uninstalling

**Comment by hahai23456789** [comment]
where are you from ,i am from China;

**Comment by opp100** [comment]
卧槽，我也是

From my iPhone

**Comment by hahai23456789** [comment]
你在哪上班 啊

**Comment by opp100** [comment]
我在澳洲上班呢，小公司，不出名的

From my iPhone

**Comment by duanj3** [comment]
大哥，我也遇到这个问题了，你怎么解决的啊？你就卸载了一个watchman就解决了吗？ps.我没有下这个叫watchman的软件
