### ISSUE TITLE
CFBundleIdentifier", Does Not Exist

### ISSUE THREAD

**Issue by wei63w** [facebook/react-native#14969]
this is my init new project  but it has error ...

```


** BUILD FAILED **



The following build commands failed:
	PhaseScriptExecution Install\ Third\ Party /Users/genilex3/Desktop/reactNative/reactthree/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/double-conversion.build/Script-190EE32F1E6A43DE00A8543A.sh
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/reactthree.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/reactthree.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

```

**Comment by Baptiste-Garcin** [comment]
I bet you are using react-native 0.46 on mac...

**Comment by fanyuexiang** [comment]
#14604 this is it

**Comment by Baptiste-Garcin** [comment]
You should try to remove react-native and reinstall the 0.44 version, it worked for me.

**Comment by gopaldevra** [comment]
Hey Baptiste, how to remove the react-native and install the 0.44 version? please leme know.

**Comment by yozef** [comment]
everybody has this issue, and so far it's being ignored.

**Comment by Baptiste-Garcin** [comment]
I've done exactly what @yozef said and it somehow worked.

@gopaldevra You might have some issues if you have already an app and try to downgrade it. If it is the case, they are mostly related to the folder structure.
Let me know if it works

**Comment by hramos** [comment]
https://github.com/facebook/react-native/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20CFBundleIdentifier

**Comment by wei63w** [comment]
@Baptiste-Garcin     ,  no no no ,  I tried many version because of this error, a few days ago my project version is 45  , i do nothing in project  and when i  using run command it's wrong. then i tred version of 0.44.0 ,0.45.1, 0.45.0 , 0.46.1  but it also was wrong.

**Comment by wei63w** [comment]
@fanyuexiang  啥意思 , 你说的那个已经关闭了啊, 也没有成功的解决方案啊 ? 我猜你看得懂中文

**Comment by fanyuexiang** [comment]
@wei63w 把"package.json"里面"react"换成这个版本, "16.0.0-alpha.6","react-native": "0.44.3",然后删除node_modules文件夹,重新npm install, 再react-native run-ios,如果还报错,你打开ios项目里面,target-buildphases-bundle react native code and images, 里面有个路径是写错了的,好像是script,正确的是"packager",你按照那个路径打开,把正确的路径写上去再运行试试

**Comment by gopaldevra** [comment]
Thanks, @yozef, @Baptiste-Garcin, Now I am running the app through the Xcode and it's working.
So I am not using the command to run on the iOS.

**Comment by wei63w** [comment]
@fanyuexiang    thanks for you , 额 谢谢啦, 跟你说的一样 那个shell会报错 写错东西了 script需要改成packager ,

**Comment by hramos** [comment]
Duplicate of #14423

**Comment by mradkov** [comment]
I had the same problem, and I solved it with the `react-native upgrade` command. It asks you to reset several settings of the project like the Launch screen and etc. 

I think this issue is caused by changing the name of the app name from within XCode instead from react-native project. Or at least that was what caused the issue in my case.

**Comment by dathu7728** [comment]
In react native main.jsbundle file missing in xcode ios

**Comment by vish-udp** [comment]
Looks like this is an issue with _Xcode Build Location_. Try switching it to **Unique** under Xcode -> Preferences -> Locations -> Advanced.

**Comment by sunnypurewal** [comment]
The solution by @vish-udp fixed the issue for me. I always set my build location relative to my current project but react-native doesn't seem to like that.

**Comment by DomLeMarin** [comment]
The solution for me was in the Xcode Build Location, under Xcode -> Preferences -> Locations, I changed the "Command Line Tools" from an old version to the latest version of Xcode 9.4 and it worked.

**Comment by wawhal** [comment]
This happens for me whenever the React Native cache gets corrupted. Clearing cache and retrying works for me:

```
$ rm -rf ~/.rncache
$ rm -rf node_modules
$ npm install
$ react-native run-ios
```

**Comment by IshanFx** [comment]
I downgraded react-native to 0.52.0 and build work fine

**Comment by oluomoniyi** [comment]
I tried all the other suggestions multiple times infact, the only thing that worked for me was the downgrade to version 0.52.0!

My Xcode version is 8.3

`yarn add react-native@0.52.0`
or 
`npm i react-native@0.52.0`

**Comment by SamiChab** [comment]
Try to run your project by building it from XCode. It worked for me
