### ISSUE TITLE
Unable to resolve module react-native/Libraries/Renderer/shims/ReactNativePropRegistry

### ISSUE THREAD

**Issue by ckim16** [facebook/react-native#14977]
Hi all,

I'm currently using 
`"native-base": "^2.2.1"` and 
` "react-native": "^0.44.3"` and I get an error saying 

`Unable to resolve module react-native/Libraries/Renderer/shims/ReactNativePropRegistry from path/to/node_modules/native-base/dist/src/Utils/computeProps.js`.

I believe this is a version issue and but not sure  this is a native-base's issue or react-native's issue.

Has anyone had same problem before?

**Comment by kisubs** [comment]
I am getting the same error.

**Comment by bbuscarino** [comment]
Got the same error with `"native-base": "2.2.1"` and `"react-native": "0.44.3"`, went back to `"native-base": "2.2.0"` and the error was resolved. Looks like this is an issue with native-base.

**Comment by charpeni** [comment]
`react-native/Libraries/Renderer/shims/` is a new directory since `react-native@0.46.1`, you should downgrade your dependencies or upgrade react-native.

I'll close this since it's related to Native Base and not React Native.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by kisubs** [comment]
i found a work around by changing the import statement in node_modules/native-base/dist/src/Utils/computeProps.js
`var _ReactNativePropRegistry=require("react-native/Libraries/Renderer/native/ReactNativePropRegistry"); `
to
`var _ReactNativePropRegistry=require("react-native/Libraries/Renderer/src/renderers/native/ReactNativePropRegistry");`

You should check where your ReactNativePropRegistry.js is and replace the import statement.

**Comment by kayrules** [comment]
Downgrade to native-base@2.2.0 will solve this issue.
https://github.com/GeekyAnts/NativeBase/issues/1049

**Comment by alexmngn** [comment]
I have the same issue using `react-native-svg` library

**Comment by apurvaaggarwal** [comment]
I solved this issue...by updating
"dependencies": {
   
    "native-base": "^2.2.1",
    "react": "^16.0.0-alpha.12",
    "react-native": "^0.46.1"
}
cd android
./gradlew clean
< create bundle>
