### ISSUE TITLE
"react": "16.0.0-alpha.12"

### ISSUE THREAD

**Issue by sm2017** [facebook/react-native#14974]
Today I run `react-native init` , Why it install 16.0.0-alpha.12 version? is it safe for me?

I run `yarn add react-dom` and it fetch version 15.6.1 , so I think it is not match 16.0.0-alpha.12
Is there any version matches ?

**Comment by chirag04** [comment]
because RN is using react v16 alpha. It is as safe as an alpha version can get. Although, i think facebook is using that in production. 

yarn add react react-dom will install the latest stable which is 15.6. If you need alpha you need to explicitly mention the version when installing.

**Comment by sm2017** [comment]
But I cannot found react-dom@6.0.0-alpha.12
