### ISSUE TITLE
SectionList calls getItemLayout with out of bounds index

### ISSUE THREAD

**Issue by wvteijlingen** [facebook/react-native#14972]
### Is this a bug report?
Yes

### Have you read the Bugs section of the Contributing to React Native Guide?
Yes

### Environment

1. `react-native -v`: react-native-cli: 2.0.1 / react-native: 0.46.1
2. `node -v`: v8.1.0
3. `npm -v`: 5.0.3
4. `yarn --version`: 0.24.6 

Then, specify:

1. Target Platform (e.g. iOS, Android): iOS 10.3
2. Development Operating System (e.g. macOS Sierra, Windows 10): macOS Sierra
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant): Xcode

### Steps to Reproduce

1. Create a SectionList with 2 sections, each containing each row. Each section must have a section header, but no section footer.
2. Set up the `getItemLayout` so that it logs the index argument.
3. See that index ranges from 0 to 5.

### Expected Behavior

I expected the index to range from 0 to 3. AFAIK SectionList flattens everything into one list, which in this case would be a total of 4 items (header, row, header, row).

### Actual Behavior

The `getItemLayout` function gets called with indexes ranging from 0 to 5. I've looked through the code in VirtualizedSectionList and it seems that the itemCount calculation adds 2 to each section length:

```javascript
    const itemCount = props.sections.reduce(
      (v, section) => {
        stickyHeaderIndices.push(v + offset);
        return v + section.data.length + 2; // Add two for the section header and footer.
      },
      0
    );
```

I don't have a lot of knowledge about the inner workings of this class, but it seems weird that it always adds 2, even if there is no section footer.

**Comment by wvteijlingen** [comment]
The following code shows this issue.

```javascript
import React, { Component } from 'react';
import { AppRegistry, StyleSheet, Text, SectionList, PixelRatio } from 'react-native';

export default class GetItemLayoutDemo extends Component {

  render() {
    const sections = [
      {
        key: 'section1',
        data: ['Row']
      },{
        key: 'section2',
        data: ['Row']
      }
    ]

    return (
      <SectionList
        sections={sections}
        keyExtractor={(item, index) => index}
        ItemSeparatorComponent={() => {
          return <View style={{height: 1, backgroundColor: 'red'}} />
        }}
        renderSectionHeader={() => {
          return <Text style={{height: 40, backgroundColor: 'green'}}>Section header</Text>
        }}
        renderItem={() => {
          return <Text style={{height: 40, backgroundColor: 'yellow'}}>Row</Text>
        }}
        getItemLayout={(data, index) => {
          console.log(`getItemLayout called with index: ${index}`);
          return { length: 44, offset: 44 * index, index: index };
        }}
        / >
    );
  }
}

AppRegistry.registerComponent('GetItemLayoutDemo', () => GetItemLayoutDemo);
```

Console output:

```
getItemLayout called with index: 1
getItemLayout called with index: 2
getItemLayout called with index: 4
getItemLayout called with index: 5
```

**Comment by tiaaaa123** [comment]
It seems that the sectionList in `react-native v0.47.0` consider the section AND his content as a single element in the list.
So: 
section: (index 0)
   row 1 (index 1)
total = section + row + (row and section) = 3 elements

**Comment by dotansimha** [comment]
I found this extremely helpful: https://medium.com/@jsoendermann/sectionlist-and-getitemlayout-2293b0b916fb
