### ISSUE TITLE
[0.47.0-rc.2] Podspec: subspec "DevSupport" requires InspectorInterfaces

### ISSUE THREAD

**Issue by HeEAaD** [facebook/react-native#14975]
### Is this a bug report?

Yes

### Have you read the Bugs section of the Contributing to React Native Guide?

Yes

### Environment

1. `react-native -v`: react-native: 0.47.0-rc.2
2. `node -v`: v8.1.3
3. `npm -v`: 5.0.3
4. `yarn --version` (if you use Yarn): 0.27.5

Then, specify:

1. Target Platform (e.g. iOS, Android): iOS
2. Development Operating System (e.g. macOS Sierra, Windows 10): macOS Sierra
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant):
Xcode: 8.3.3
Cocoapods: 1.2.1

### Steps to Reproduce

iOS project which tries to integrate React Native 0.47.0-rc2 with DevSupport via Cocoapods.
1. have a package.json with React Native `0.47.0-rc.2` dependency
2. run `yarn install`
3. add the following lines to the Podfile:
```
pod 'React', :path => 'node_modules/react-native', :subspecs => ['BatchedBridge', 'DevSupport']
pod 'Yoga', :path => 'node_modules/react-native/ReactCommon/yoga'
```
4. run `pod install`
5. open the generate workspace
6. try to build the project

### Expected Behavior

Build will succeed without an error.

### Actual Behavior

Build fails with the following error:
```
Undefined symbols for architecture x86_64:
  "facebook::react::IRemoteConnection::~IRemoteConnection()", referenced from:
      RemoteConnection::~RemoteConnection() in libReact.a(RCTInspector.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Reproducible Demo

https://github.com/HeEAaD/Demo-ReactNative-0.47.0-rc2-Podspec-issue
To reproduce the bug execute the folling:
1. `yarn install`
2. `pod install`
3. open "ReactNative Podspec Dependency Bug.xcworkspace" with Xcode
4. try to build it

## Possible Solution
Add InspectorInterfaces to the DevSupport section of the React.podspec
```
  s.subspec "DevSupport" do |ss|
    ss.dependency             "React/Core"
    ss.dependency             "React/RCTWebSocket"
    ss.source_files         = "React/DevSupport/*",
                              "React/Inspector/*",
                              "ReactCommon/jschelpers/InspectorInterfaces.{cpp,h}"
  end
```

**Comment by javache** [comment]
I think the correct solution is to add these files to the `jschelpers_legacy` podspec. Can you send a PR for this?

**Comment by HeEAaD** [comment]
Sure, I'll create a PR.
