### ISSUE TITLE
<Text> w/ adjustsFontSizeToFit does not use the correct font family when first character is an emoji

### ISSUE THREAD

**Issue by chourobin** [facebook/react-native#14981]
### Is this a bug report?

Yes

### Have you read the Bugs section of the Contributing to React Native Guide?

Yes

### Environment

1. `react-native -v`: 0.45.1
2. `node -v`: v8.1.4
3. `npm -v`: 5.0.3
4. `yarn --version` (if you use Yarn): 0.27.5

Then, specify:

1. Target Platform (e.g. iOS, Android): both
2. Development Operating System (e.g. macOS Sierra, Windows 10): macOS Sierra
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant): Xcode 8.3.3

### Steps to Reproduce

(Write your steps here:)

1. Create a `<Text>` component and enable `adjustsFontSizeToFit` and set the `minimumFontScale`. Set a non-default font family like "Helvetica".
2. Use an emoji as the first character of the string (ie. 👋🏻 hello world)

```
render() {
    return(
      <View style={styles.container}>
        <Text style={styles.paragraph} adjustsFontSizeToFit={true} minimumFontScale={0.8}>
          👋🏻 Hello World
        </Text>
      </View>
    )
}

const styles = StyleSheet.create({
    paragraph: {
        fontFamily: "Helvetica",
    }
}
```

### Expected Behavior

The text would render normally with the Helvetica font family applied to the entire text string.

### Actual Behavior

The text string renders in the Courier font family.
![screenshot 2017-07-12 15 24 19](https://user-images.githubusercontent.com/438742/28135995-36958c6e-6716-11e7-834b-868cb69a82c8.png)

### Reproducible Demo

https://snack.expo.io/H15ZslNrb

### Additional Info

Seems like line 553 of `RCTShadowText.m` replaces the font based on the first character of the string. If the character is an emoji, it will try to apply "Apple Color Emoji" fontFamily on the entire string.

https://github.com/facebook/react-native/blob/bd004568d3e006b61391417fc405e9483996dc81/Libraries/Text/RCTShadowText.m#L553

**Comment by southerneer** [comment]
This is still an issue as of 0.47.2
