### ISSUE TITLE
Debugging with dev server on Android is broken

### ISSUE THREAD

**Issue by mganandraj** [facebook/react-native#14995]
### Is this a bug report?

Yes

### Have you read the Bugs section of the Contributing to React Native Guide?

Yes

### Environment

PS C:\Users\anandrag.FAREAST> react-native -v
react-native-cli: 2.0.1
react-native: n/a - not inside a React Native project directory
PS C:\Users\anandrag.FAREAST> node -v
v8.1.2
PS C:\Users\anandrag.FAREAST> npm -v
5.0.4Then, specify:

- Target Platform: Android

- Development Operating System: Windows

- Build tools: gradle

### Steps to Reproduce

1. Clone facebook/react-native repo, and checkout the latest commit.
2. Run npm install, and start the dev server using "node cli.js start"
3. ./gradlew :RNTester:android:app:installDebug to install RNTester app.
4. App is frozen after loading bundle from the dev server.

### Expected Behavior

Launch RNTester app 

### Actual Behavior

App is frozen with a white screen, and the entire device is misbehaving/not responding. Killed the app through adb shell to recover the device. At time the redbox with the following error shown multiple times is shown,

SyntaxError: Strict mode does not allow function declarations in a lexically nested statement. 

I did some investigation and figured out that this is introduced in the following commit. In this change, the code in ReactNativeStack(Fiber)-dev.js is moved to inside a conditional block. This results in few function definitions inside a block, which is not supported by the version of JSC packaged for Android.

https://github.com/facebook/react-native/commit/30352ecbf234a69249a29c9908e76e46ca900ff2

**Comment by foghina** [comment]
CC @gaearon / @bvaughn - looks like this is hitting OSS now.

@mganandraj if you need to be unblocked a workaround is to go into `ReactNativeFiber-dev.js` and `ReactNativeStack-dev.js` (in `Libraries/Renderer`) and remove `if (__DEV__) {` and the corresponding closing bracket at the end of the file.

**Comment by bvaughn** [comment]
I'll look into this.

**Comment by bvaughn** [comment]
FYI a fix for this has been landed internally and will sync upstream to GitHub whenever the next batch-sync happens. (Soon?)

**Comment by bvaughn** [comment]
This change has landed in React Native ([221286b](https://github.com/facebook/react-native/commit/221286be136c092df4c2a736d66c2f5aacf3bab4)) and I've reached out to @grabbou about getting it cherry picked/released.

**Comment by grabbou** [comment]
Going to close this one then and will cherry-pick into respective branches.

**Comment by grabbou** [comment]
Going to cherry-pick it into 0.47-stable branch. If anyone is interested in having it in a different release, please let me know.

**Comment by bvaughn** [comment]
Thanks Mike!

**Comment by mganandraj** [comment]
Thanks guys for quick turnaround. Sorry for not tracking this issue more closely.
