### ISSUE TITLE
Bug: Unable to override Image style prop

### ISSUE THREAD

**Issue by xahon** [facebook/react-native#15001]
### Is this a bug report?
Yes

### Have you read the Bugs section of the Contributing to React Native Guide?
Yes

### Environment
Ubuntu 14.04

1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.45.1

2. `node -v`:
7.10.0

3. `npm -v`:
4.2.0

4. `yarn --version` (if you use Yarn):
0.27.5

Then, specify:

- Target Platform: Android 6.0.1 Miui 8.1.2.0

- Development Operating System: Ubuntu

- Build tools: Expo

### Steps to Reproduce
1. Create class that contains `Image` and style prop on it with `height` and `width`
```JSX
render () {
  return (
    <Image source={ require('../img.png') }
        style={[ {width: 10, height: 10}, ...this.props.style ]}
    />
  )
}
```
2. Override style passing `style` prop
```JSX
   render () {
        return (
            <ComponentAbove style={{ width: 20, height: 20 }} />
        )
   }
```
3. Image have `width` 10 and `height` 10 instead of 20 each   

### Expected Behavior

Both dimension are 20

### Actual Behavior

Both dimensions are 10

Another components excluding `Image` works well

**Comment by seanyusa** [comment]
@xahon You should not be using the spread operator within the array. The style prop accepts either a style object or an array of style objects.

**Comment by xahon** [comment]
Thanx, closing
