### ISSUE TITLE
404 on packager defaults file

### ISSUE THREAD

**Issue by shadowwzw** [facebook/react-native#15011]
https://github.com/facebook/react-native/blob/master/packager/defaults.js
404
in doc:
https://facebook.github.io/react-native/docs/images.html#static-non-image-resources

**Comment by hramos** [comment]
Already fixed in master: https://github.com/facebook/react-native/commit/94116dbad59dba489014d46f152b2233b00c8c43#diff-a9a8718d9b53e6140509339957c1e155
