### ISSUE TITLE
Version problem

### ISSUE THREAD

**Issue by sm2017** [facebook/react-native#15027]
`react-native init` install react@16.0.0-alpha.12 I need react-dom too so I install last version react-dom@15.6.1 , these version are incompatible so I downgrade react to react@15.6.1 

When I run application , I see this error 

![image](https://user-images.githubusercontent.com/19644997/28237566-a080c42a-6957-11e7-87fd-691fb64e1e39.png)

**Comment by peterp** [comment]
You could install `react-dom@16.0.0-alpha.12`

**Comment by sm2017** [comment]
@peterp I tried `react-dom@16.0.0-alpha.12` But I have same issue
see https://github.com/necolas/react-native-web/issues/570
