### ISSUE TITLE
jschelpers/JavaScriptCore.h file not found

### ISSUE THREAD

**Issue by codergelly** [facebook/react-native#15024]
cocopods version 1.2.1  

The project is written in swift

More anxious, online and so on

thanks

![image](https://user-images.githubusercontent.com/15134985/28234499-ce419052-68c5-11e7-9bde-f9972b14d205.png)

![image](https://user-images.githubusercontent.com/15134985/28234478-a3832eb6-68c5-11e7-8fb8-3c95125eeeef.png)

**Comment by charpeni** [comment]
@facebook-github-bot duplicate #13010
