### ISSUE TITLE
Expo Something Went Wrong Error

### ISSUE THREAD

**Issue by carloabelli** [facebook/react-native#15025]
### Is this a bug report?

Yes

### Have you read the Bugs section of the Contributing to React Native Guide?

Yes

### Environment

1. `react-native -v`: 0.45.1
2. `node -v`: v8.1.4
3. `npm -v`: 5.3.0
4. `yarn --version` (if you use Yarn): 0.27.5

Then, specify:

- Target Platform: iOS, Android

- Development Operating System: Linux (Arch Linux), 4.12.1

- Build tools:

### Steps to Reproduce

(Write your steps here:)

1. Create new app using `create-react-native-app`
2. Run `yarn start`

### Expected Behavior

Be able to view the app on my phone by scanning the QR code in Expo.

### Actual Behavior

Outputs warning:
```
Warning: You are using npm version 5.3.0. There may be bugs in this version, use it at your own risk. We recommend version 4.6.1.
```
but seems to work fine otherwise. When opening the link in Expo I just get the error that something went wrong. In the log it states:
```
Uncaught Error: Packager is not running at http://XXX.XXX.X.X:19001
```

### Reproducible Demo

Create an app using `create-react-native-app`.

**Comment by zibs** [comment]
Have you tried downgrading your npm to the recommended version of 4.6.1? I think that warning message may be there for a reason.

If it's not related to npm, this might be more of an expo issue, you could try joining their community slack channel or their forums: https://forums.expo.io/ for help there.

**Comment by dedmass** [comment]
Downgraded to 4.6.1 and the warning disappeared but the other behavior did not change. I will try asking on the expo channels.

**Comment by mixelpixel** [comment]
Hello, have you resolved this issue? I just tried downgrading to 4.6.1 using the command: `npm install npm@4.6.1` from within the RN project directory (then `npm i` after confirming the package.json file specified npm 4.6.1). I still get the same warning from Expo IDE and when I query `npm -version` from within the RN project directory, I get 5.3.0.

What am I doing wrong? Please advise - thank you 😄

**Comment by Mythrim** [comment]
I am facing the same issue even after downgrading the npm version to 4.6.1. Can You please help me with that.

**Comment by nikki93** [comment]
Can you remove `node_modules/` directory and reinstall with npm? There may be some stale packages.

**Comment by Dsantacruz** [comment]
the solution for me was: set REACT_NATIVE_PACKAGER_HOSTNAME=my-custom-ip-address , then disable others connection differences wifi, good luch
