### ISSUE TITLE
React Native fetch() Network Request Failed(This error message is useless please configure to give some detailed error)

### ISSUE THREAD

**Issue by udhayaraj01** [facebook/react-native#15028]
### Is this a bug report?

(write your answer here)

### Have you read the Bugs section of the Contributing to React Native Guide?

(Write your answer here.)

### Environment

1. `react-native -v`:
2. `node -v`:
3. `npm -v`:
4. `yarn --version` (if you use Yarn):

Then, specify:

- Target Platform: 

- Development Operating System: 

- Build tools:

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by Shubham-Sinha** [comment]
Were you able to debug this ?

**Comment by AlanFoster** [comment]
@facebook-github-bot needs-repro

@udhayaraj01 As a guess; Are you using the axios library? As `'Network Error'` is the Error given by Axios. 

As a work around it may be possible to reach into `error.request._response` and see your full error.

**Comment by AlanFoster** [comment]
@facebook-github-bot needs-repro

**Comment by udhayaraj01** [comment]
Thanks for your reply.I fixed this issue long back ago, This is how i fixed this issue I'm trying to call webservices of my machine Ip address say for 192.XX.XX.XX but my andriod emulator running on the Ip is 10.0.0.2. So when i changed the Ip it works fine.
