### ISSUE TITLE
compileDebugJavaWithJavac - is not incremental

### ISSUE THREAD

**Issue by chandanGr** [facebook/react-native#15026]
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
:app:prepareComAndroidSupportMediarouterV72300Library UP-TO-DATE
:app:prepareComAndroidSupportSupportCompat2520Library UP-TO-DATE
:app:prepareComAndroidSupportSupportCoreUi2520Library UP-TO-DATE
:app:prepareComAndroidSupportSupportCoreUtils2520Library UP-TO-DATE
:app:prepareComAndroidSupportSupportFragment2520Library UP-TO-DATE
:app:prepareComAndroidSupportSupportMediaCompat2520Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42520Library UP-TO-DATE
:app:prepareComFacebookFbuiTextlayoutbuilderTextlayoutbuilder100Library UP-TO-DATE
:app:prepareComFacebookFrescoDrawee101Library UP-TO-DATE
:app:prepareComFacebookFrescoFbcore101Library UP-TO-DATE
:app:prepareComFacebookFrescoFresco101Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipeline101Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipelineBase101Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipelineOkhttp3101Library UP-TO-DATE
:app:prepareComFacebookReactReactNative0463Library UP-TO-DATE
:app:prepareComFacebookSoloaderSoloader010Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServices920Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesAds920Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesAdsLite920Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesAnalytics920Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesAnalyticsImpl920Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesAppindexing920Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesAppinvite920Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesAuth920Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesAuthBase920Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesBase1026Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesBasement1026Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesCast920Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesCastFramework920Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesClearcut920Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesContextmanager920Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesDrive920Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesFitness920Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesGames920Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesGass920Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesGcm920Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesIdentity920Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesIid920Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesLocation920Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesMaps920Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesNearby920Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesPanorama920Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesPlaces920Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesPlus920Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesSafetynet920Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesTagmanager920Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesTagmanagerApi920Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesTasks1026Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesVision920Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesWallet920Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesWearable920Library UP-TO-DATE
:app:prepareComGoogleFirebaseFirebaseAnalytics1026Library UP-TO-DATE
:app:prepareComGoogleFirebaseFirebaseAnalyticsImpl1026Library UP-TO-DATE
:app:prepareComGoogleFirebaseFirebaseAuth1026Library UP-TO-DATE
:app:prepareComGoogleFirebaseFirebaseAuthCommon920Library UP-TO-DATE
:app:prepareComGoogleFirebaseFirebaseAuthModule920Library UP-TO-DATE
:app:prepareComGoogleFirebaseFirebaseCommon1026Library UP-TO-DATE
:app:prepareComGoogleFirebaseFirebaseConfig920Library UP-TO-DATE
:app:prepareComGoogleFirebaseFirebaseCore1026Library UP-TO-DATE
:app:prepareComGoogleFirebaseFirebaseCrash920Library UP-TO-DATE
:app:prepareComGoogleFirebaseFirebaseDatabase920Library UP-TO-DATE
:app:prepareComGoogleFirebaseFirebaseDatabaseConnection920Library UP-TO-DATE
:app:prepareComGoogleFirebaseFirebaseIid1026Library UP-TO-DATE
:app:prepareComGoogleFirebaseFirebaseMessaging1026Library UP-TO-DATE
:app:prepareComGoogleFirebaseFirebaseStorage920Library UP-TO-DATE
:app:prepareComGoogleFirebaseFirebaseStorageCommon920Library UP-TO-DATE
:app:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:mergeDebugShaders UP-TO-DATE
:app:compileDebugShaders UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:processDebugGoogleServices
Parsing json file: C:\Users\suhas\Documents\NotificationTest1\android\app\google-services.json
:app:generateDebugResources
:app:mergeDebugResources UP-TO-DATE
:app:bundleDebugJsAndAssets SKIPPED
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
:app:compileDebugJavaWithJavac
:app:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
C:\Users\suhas\Documents\NotificationTest1\android\app\src\main\java\com\notificationtest1\MainActivity.java:24: error: cannot find symbol
    protected List<ReactPackage> getPackages() {
              ^
  symbol:   class List
  location: class MainActivity
C:\Users\suhas\Documents\NotificationTest1\android\app\src\main\java\com\notificationtest1\MainActivity.java:24: error: cannot find symbol
    protected List<ReactPackage> getPackages() {
                   ^
  symbol:   class ReactPackage
  location: class MainActivity
C:\Users\suhas\Documents\NotificationTest1\android\app\src\main\java\com\notificationtest1\MainActivity.java:23: error: method does not override or implement a method from a supertype
    @Override
    ^
C:\Users\suhas\Documents\NotificationTest1\android\app\src\main\java\com\notificationtest1\MainActivity.java:26: error: cannot find symbol
        new MainReactPackage(),
            ^
  symbol:   class MainReactPackage
  location: class MainActivity
C:\Users\suhas\Documents\NotificationTest1\android\app\src\main\java\com\notificationtest1\MainActivity.java:27: error: cannot find symbol
        new VectorIconsPackage(),
            ^
  symbol:   class VectorIconsPackage
  location: class MainActivity
C:\Users\suhas\Documents\NotificationTest1\android\app\src\main\java\com\notificationtest1\MainActivity.java:28: error: cannot find symbol
        new FIRMessagingPackage(getIntent()));
            ^
  symbol:   class FIRMessagingPackage
  location: class MainActivity
C:\Users\suhas\Documents\NotificationTest1\android\app\src\main\java\com\notificationtest1\MainActivity.java:25: error: cannot find symbol
      return Arrays.<ReactPackage>asList(
                     ^
  symbol:   class ReactPackage
  location: class MainActivity
C:\Users\suhas\Documents\NotificationTest1\android\app\src\main\java\com\notificationtest1\MainActivity.java:25: error: cannot find symbol
      return Arrays.<ReactPackage>asList(
             ^
  symbol:   variable Arrays
  location: class MainActivity
8 errors
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

## This is my MainActivity.java file  -> 

package com.notificationtest1;

import com.facebook.react.ReactActivity;
import android.content.Intent; 

public class MainActivity extends ReactActivity {

    @Override
    protected String getMainComponentName() {
        return "NotificationTest1";
    }

    @Override                                                                 
    public void onNewIntent(Intent intent){                               
        setIntent(intent);                                             
    } 

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
        new MainReactPackage(),
        new VectorIconsPackage(),
        new FIRMessagingPackage(getIntent()));
    }
}

**Comment by chandanGr** [comment]
I am new to react native and I was trying to setup FCM on my react native project and I got this error, can anyone please solve this error .

**Comment by veb** [comment]
If anyone else lands on a similar problem, the answer is inside the `List`

This was mine:
```
    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
            new MainReactPackage(),
            new RNDeviceInfo(),
            new ImagePickerPackage(),
            new ReactNativeOneSignalPackage(),
            new RNCameraPackage(),
      );
    }
```

Notice I had forgotten to remove the end comma after `RNCameraPackage` - that was what was causing the issue. Same with @chandanGr but he had the semicolon. 

Hope this helps anyone else.

**Comment by chenweigh** [comment]
after upgrade react-native project, 
The same issue for me .
----
react-native ^0.50.1
react 16.0.0
----
<img width="1038" alt="2018-04-03 11 28 29" src="https://user-images.githubusercontent.com/15101298/38227829-b2a935e8-3732-11e8-8f14-710b946d480c.png">

how to fix it ?
please help me .
thank you !

**Comment by tonz341** [comment]
C:\Users\tonz\projects\androidtest\android\app\src\main\java\com\myapplication\MainApplication.java:28: error: illegal start of expression
      );
      ^
1 error
:app:compileDebugJavaWithJavac FAILED



"react-native": "0.55.2",
    "react-native-contacts": "^2.1.3",


me also huhuhu please help
