### ISSUE TITLE
Flatlist - onEndReached firing at init and not end

### ISSUE THREAD

**Issue by warka0** [facebook/react-native#15039]
### Is this a bug report?

Probably, or i don't know how to make it works. So yes ?

### Have you read the Bugs section of the Contributing to React Native Guide?
Yes

### Environment

1. `react-native -v`: From the package expo 18.0.1, probably 16.0.0
2. `node -v`: v6.11.0
3. `npm -v`: 3.10.10
4. `yarn --version` (if you use Yarn): 0.27.5

Then, specify:

- Target Platform: Actually, iOS

- Development Operating System: maxOS

- Build tools: Expo

### Steps to Reproduce

1. FlatList with this code
```
<FlatList
	style={{flex:1}}
	removeClippedSubviews={true}
	initialNumToRender={5}
	data={ this.state.store }
	renderItem={this.renderRowView}
	keyExtractor={item => item.reference}
	onRefresh={this.handleRefresh}
	refreshing={this.state.refreshing}
	onEndReached={this.handleLoadMore}
	onMomentumScrollBegin={() => { this.setState({ onEndReachedCalledDuringMomentum: false }); }}
      	onEndReachedThreshold={0.5}
/>
```
2. onEndReached is firing on init and nerver on end

### Expected Behavior

Should act normally, i would to have the firing event on the end of the list or just before!

### Actual Behavior

onEndReached is fired on init

### What i'm searching for

I would like to make it works, if someone has a demo that work normally. 
Someone else have the same problem? It's really drive my crazy... 

Inside of the flastlit, row are view with an height of 350. 

Thx!

**Comment by warka0** [comment]
Soooo

I was really upset when programming this shit :)

If someone want a demo that works, here the link : 
https://github.com/spencercarli/react-native-flatlist-demo/blob/master/FlatListDemo.js

**Comment by YouHan26** [comment]
hey, how it resolve ?
