### ISSUE TITLE
it did not contain a package, nor an index file

### ISSUE THREAD

**Issue by chenghaohao** [facebook/react-native#15030]
### Is this a bug report?

(write your answer here)

### Have you read the Bugs section of the Contributing to React Native Guide?

(Write your answer here.)

### Environment

1. `react-native -v`: 0.46.1
2. `node -v`:v6.10.3
3. `npm -v`:3.10.10
4. `yarn --version` (if you use Yarn):v0.24.5

Then, specify:

- Target Platform: Android

- Development Operating System: Windows10

- Build tools:

### Steps to Reproduce

(Write your steps here:)

1.react-native start
2.err shows up:   bundling failed: "Unable to resolve module `./img/tabbar/pfb_tabbar_homepage@2x.png` from `F:\\code\\react-native\\meituanCopy\\src\\RootScene.js`: could not resolve `F:\\code\\react-native\\meituanCopy\\src\\img\\tabbar\\pfb_tabbar_homepage@2x.png' as a folder: it did not contain a package, nor an index file"
3.just using  <Image
                source={require('../img/tabbar/pfb_tabbar_homepage@2x.png')} /> and the png is existed

### Actual Behavior

in v0.44.0 react-native , the code runs well..but when i copy the code to a new demo. the err shows...

**Comment by ctxdl** [comment]
I have the same problem the code was working correctly in 0.45.1 now i updated version and the images cannot load Icon-83.5@2x.png' as a folder: it did not contain a package, nor an index file

**Comment by nemophrost** [comment]
@hramos any resolution for this, or another issue that addresses it? Thanks!

**Comment by nemophrost** [comment]
I was able to fix this by changing my file names to ones without any `@`

**Comment by chenghaohao** [comment]
no solution?... so closed..😂😂

**Comment by hramos** [comment]
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Comment by henrypip** [comment]
@nemophrost I think this fixes it for me too but then it would break React Native's static image functionality? https://facebook.github.io/react-native/docs/images.html#static-image-resources

**Comment by henrypip** [comment]
Is this a bug report?

(write your answer here)

Have you read the Bugs section of the How to Contribute guide?

(Write your answer here.)

Environment

react-native -v: 0.46.1
node -v: v7.7.2
npm -v: 4.1.2
yarn --version: 0.24.6
expo: v19.0.0

Then, specify:

Target Platform: iOS
Development Operating System: MacOS 10.12.5
Build tools: Expo
Steps to Reproduce
```
{
  "presets": ["babel-preset-expo"],
  "env": {
    "development": {
      "plugins": ["transform-react-jsx-source"]
    }
  },
  "sourceMaps": true // https://marketplace.visualstudio.com/items?itemName=vsmobile.vscode-react-native
}
```

Errors on @2x and @3x, but when I take out the @ it works fine
```
require("./assets/images/placeholders/icon-image.png"),
      require('./assets/images/placeholders/icon-image@2x.png'),
      require("./assets/images/placeholders/icon-image@3x.png"),
```

```
require("./assets/images/placeholders/icon-image.png"),
      require('./assets/images/placeholders/icon-image2x.png'),
      require("./assets/images/placeholders/icon-image3x.png"),
```


Expected Behavior

Should run fine, will double check it does when I roll back to v18

Actual Behavior

![simulator screen shot 23 jul 2017 19 48 11](https://user-images.githubusercontent.com/28408923/28501961-e07e7246-6fdf-11e7-87c5-5b83eb9128c8.png)

**Comment by nemophrost** [comment]
@henrypip Yeah it could break static image stuff. In my case I was only using `@2x` without the others and using its path explicitly. Perhaps the bug would also be fixed if I wasn't explicitly referring to @2x and referred to a file without the density suffix, but I haven't tried it.

**Comment by craftdong** [comment]
any facebook offical solution for this issue? @hramos

**Comment by hramos** [comment]
I have not looked into this since the issue was closed. I recommend opening a new issue (and following the template).

**Comment by sytolk** [comment]
@hramos have you see this? https://github.com/facebook/react-native/issues/15030#issuecomment-317273562 (I think that the template is following)
Why not simple reopen this issue instead of opening new one ??

**Comment by mo-solnet** [comment]
I've created a ticket for this issue against the metro-bundler project 👉 https://github.com/facebook/metro-bundler/issues/43

**Comment by milon87** [comment]
I have got the same error.
The solution in my case: 
import path was wrong, after fixing import from exact path problem resolved.

**Comment by alihaydarkoc** [comment]
dont support png u should transform jpg

**Comment by hramos** [comment]
@sytolk there's hundreds of comments across issues and PRs on this repo every day, it's easy for things to slip by. Still, I highly recommend opening a new issue that meets the guidelines - the author still hasn't updated their original post, and the comment with the additional details was not from the OP. A new issue would make things easier for everyone.
