### ISSUE TITLE
Inconsistent dynamic array-length rendering behavior between iOS and Android.

### ISSUE THREAD

**Issue by dsimmons** [facebook/react-native#15031]
### Is this a bug report?

Yes.

### Have you read the Bugs section of the Contributing to React Native Guide?

Yes. If there is any open issue(s) related to this behavior, I must have missed it.

### Environment

1. `react-native -v`:

```
react-native-cli: 2.0.1
react-native: 0.45.0
```

2. `node -v`: `v7.10.0`
3. `npm -v`: `4.2.0`
4. `yarn --version` (if you use Yarn): `0.24.5`

- Target Platform: iOS, Android

- Development Operating System: macOS 10.12.5

- Build tools: Standard.

(**NOTE:** Although the above is reflective of my actual environment, I also just reproduced on a fresh `react-native init` using RN `v0.46.3`).

### Steps to Reproduce

1. `react-native init MyNewApp`

2. Embed the minimal code snippet:

```Javascript
  <View>
    <StatusBar hidden />
    {Array.from(Array(5).keys()).map(idx => (
      <Text key={idx}>{idx}</Text>
    ))}
  </View>

```

3. Run on iOS and Android separately, observe the below behavior (screenshots):

<img width="628" alt="screen shot 2017-07-15 at 5 17 34 pm" src="https://user-images.githubusercontent.com/694034/28242769-d6ca80fe-6982-11e7-85aa-46c28341ab9f.png">

### Expected Behavior

I'd expect the rendered output to be **identical** on **both** iOS and Android. Either:

  - ... it works on **both** iOS and Android.

  - ... it works on works on **neither** iOS **nor** Android.

Currently, it works as expected on iOS. On Android, **nothing is rendered**.

Although I do realize this is a relatively new language feature that may require transpilation, as I mentioned above, if it weren't to work, I'd expect it to not work on **either** platform rather than the inconsistent results I'm seeing presently.

### Actual Behavior

See above screenshot.

### Reproducible Demo

See above code snippet.

  - Specifically, the pertinent line: `Array.from(Array(5).keys())`.

  - I'd also originally tried: `[...Array(5).keys()]`

### Additional Context

Although I used a **static** (literal) numeric value in the minimal reproducible snippet above, in my actual app code, the ***actual*** value (quantity) is **dynamic** (depending on props).

For example, imagine the "pegs" of a paging indicator for a swipeable view, where the number of elements shown is dynamic based on some resultant API call to populate the view with data.

This ended up throwing me for a quick loop because I'd been iterating on the core business logic, visual appearance, and user interaction using the iOS simulator. Once I fired up an Android emulator (and additionally sanity-checked with an actual device), some of my dynamically-rendered screen elements (based on quantity) using the above technique weren't showing up on Android as they were on iOS.

Just to reiterate, the reason I'm filing this bug is because the resultant behavior **isn't consistent** between both platforms. If it wouldn't have worked for **either**, I would've spent less time tracing down the issue.

**Comment by zibs** [comment]
https://snack.expo.io/rkbkRmtHb Here is a quick snack of this issue.

**Comment by hey99xx** [comment]
Is it any different in iOS 8? Maybe JSC version has something to do with this.

**Comment by hey99xx** [comment]
According to [ES6 support table](https://kangax.github.io/compat-table/es6/), after checking "Show obsolete platforms" (so iOS 8 column shows up) and looking at "Array static methods" > "Array.from, array-like objects", the support for `Array.from` method starts at iOS 9. 

So this makes me think your test would also fail at iOS 8 simulator and kind of explain the issue.

**Comment by dsimmons** [comment]
> Is it any different in iOS 8? Maybe JSC version has something to do with this.

Based on my understanding from [this page of the docs](https://facebook.github.io/react-native/docs/javascript-environment.html):

> "On iOS simulators and devices, Android emulators and devices React Native uses JavaScriptCore which is the JavaScript engine that powers Safari. On iOS JSC doesn't use JIT due to the absence of writable executable memory in iOS apps."

... it sounds like iOS and Android both use JSC. I was aware of the fact that iOS did, but I hadn't yet done any diligence in terms of Android implementation details.

If that's indeed the case, the only situation in which we'd see the behavior described by this issue is if/when iOS and Android are using different versions of JSC, right? Because AFAIK, all else should be equal as far as Javascript goes (eg. transpilation, polyfills) between platforms.

**Comment by hey99xx** [comment]
Yes, all else is equal but here's the thing. On different iOS versions (iOS 8, 9, 10) JSC version is tied to the operating system. On Android, JSC is not part of the device, its binary is shipped with your app.

In the JavaScript environment that does not have `Array.from`, [react-native polyfills it](https://github.com/facebook/react-native/blob/0.48-stable/Libraries/polyfills/Array.es6.js#L21-L22). 

Since Android's JSC version is closer to iOS 8's (this is not documented anywhere except mentioned in few GitHub issues in this repo), I expect your bug report to behave the same on both Android and iOS 8, since these would be the platforms to use the `Array.from` polyfill. Does that make sense?

**Comment by hey99xx** [comment]
And it's still a valid bug report btw, I am just trying to help isolating the issue.

**Comment by dsimmons** [comment]
> On Android, JSC is not part of the device, its binary is shipped with your app.
> ...
> Since Android's JSC version is closer to iOS 8's (this is not documented anywhere except mentioned in few GitHub issues in this repo)...

Ah! This was the part that I was missing 😄 

> ... I expect your bug report to behave the same on both Android and iOS 8, since these would be the platforms to use the `Array.from` polyfill. Does that make sense?

Totally! 👍 

As a somewhat related aside, if iOS is the lowest common denominator (in that the JSC version is pegged), wouldn't it make sense to keep Android's shipped JSC version in lock-step (or at least very close) in order to avoid inconsistencies?

Of course, I realize there's probably a very good explanation as to why this isn't the case (especially considering I'm unaware of the degree of effort involved in shipping updated JSC versions) 😄 

Independently, like you said, the pertinent/appropriate polyfills should largely make the above a moot point.

**Comment by hey99xx** [comment]
See https://github.com/facebook/react-native/issues/15382#issuecomment-320754495 if you want updated JSC on Android , but I don't think this library is tested by Facebook , so use it at your own risk.
