### ISSUE TITLE
[Text] Transparency requires backgroundColor: 'transparent'

### ISSUE THREAD

**Issue by brentvatne** [facebook/react-native#1504]
Edit: this was originally posted for Image, which turned out to not be a bug, but @jsierles pointed out an issue with Text that is related and being followed up on here.

## [0.4.4](https://rnplay.org/plays/28pp0A?autoplay=true)

![screen shot 2015-06-03 at 10 07 16 am](https://cloud.githubusercontent.com/assets/90494/7966351/5d3796b6-09d8-11e5-9d40-5328f6df3738.png)

## [master as of b63a0a](https://rnplay.org/plays/btoovQ?autoplay=true)

![screen shot 2015-06-03 at 10 07 24 am](https://cloud.githubusercontent.com/assets/90494/7966373/8a4e3484-09d8-11e5-9251-c68248e2341b.png)

**Comment by maplebaby** [comment]
Good jobs！

**Comment by jsierles** [comment]
For a text element, even with 'transparent' set, the background on master is white.

Working on 0.4.4: https://rnplay.org/apps/pIEhKg
master: https://rnplay.org/plays/PCqivA

**Comment by sahrens** [comment]
I'm confused - what's broken exactly?

**Comment by ide** [comment]
@sahrens the image is a transparent PNG and React Native is rendering it with a white background instead of a transparent one (presumably inherited from the background color of an ancestor view).

**Comment by sahrens** [comment]
@nicklockwood - your stuff?

**Comment by nicklockwood** [comment]
@ide yes, this is expected behavior - it's an optimisation to resuce blending. Try setting the background color of the `<Image>` explictly to transparent and it shouldn't do this (if it still does then it's a bug).

**Comment by ide** [comment]
@nicklockwood OK, makes sense and is consistent with Text nodes if I'm not mistaken.

I believe @jsierles has found a different bug here, where the Text node in `<Image><Text style={{background: 'transparent'}}>Words</Text></Image>` is rendered with an opaque background.

**Comment by sahrens** [comment]
Text is weird - it has backgroundColor, which refers to the actual area where there is text, and backgroundContainerColor, which is the background color of the UIView that hosts the text...I'm thinking that might have been a poor naming choice and perhaps we should flip those names and change to "textBackgroundColor"?

**Comment by ide** [comment]
To me it's more intuitive if backgroundColor sets the background behind the glyph runs and not the containing box, so the current naming makes sense in that light.

I think we want to disable the blending optimization on the container if the text has a translucent background color, so as to maintain the illusion that the container is transparent. So in the example above, the text's container would have a transparent background because (a) the text's backgroundColor is "transparent" and (b) containerBackgroundColor is null/undefined.

**Comment by sahrens** [comment]
Perhaps, but we want to be careful about adding too many magic special
rules that are hard to reason about.  That might be an ok one though, what
do you think @nicklockwood?

**Comment by ide** [comment]
My reasoning is that CSS applies the background color to the glyph runs and not the bounding box. RN should produce that effect if it's the behavior we want (maintaining CSS compatibility is the strongest argument I can think of), and text with a translucent background color is a scenario that isn't eligible for the blending optimization. When I think of it that way, it's less a magic rule that users need to learn and more like code specialization that is applicable under certain conditions.

**Comment by sahrens** [comment]
That's a great point.

**Comment by nicklockwood** [comment]
OK, so I have a solution for this. I'm thinking that for top-level <Text> nodes, the background color should apply to the whole view, and for nested <Text> nodes it should apply only to the span. This avoids the need for the extra containerBackgroundColor style, and makes the color propagation consistent with other views.

So this would yield a completely red view:

    <Text style={{backgroundColor: 'red'}}>foo</Text>

And if you only wanted the span to be red, not the whole <Text> node, you could do this:

    <Text>
      <Text style={{backgroundColor: 'red'}}>foo</Text>
    </Text>

Thoughts? @vjeux, @sahrens?

**Comment by vjeux** [comment]
@nicklockwood: that sounds like a good trade-off to me. It's not the exact same behavior as web but that's more in line with what people expect tbh

**Comment by nicklockwood** [comment]
An alternative solution (which is possibly the same or similar to what @ide is suggesting) would be to disable the ability to explicitly set the `containerBackgroundColor`, and have `backgroundColor` only affect the span.

In that scenario, we'd still inherit the container background from the parent, but if you set the span background to something translucent, it would disable inheritance.

The only problem I have with that is that if you wanted to have an opaque span background, but a transparent container background, you'd have to embed your `<Text>` inside a `<View>` with an explicit transparent background, and I think that having that requirement only apply for opaque span backgrounds and not translucent ones is more confusing than the solution I suggested, where the behavior would aways be consistent.

**Comment by chirag04** [comment]
@brentvatne  @jsierles This seems to be pretty old. Is this still a problem?

**Comment by nicklockwood** [comment]
I believe I fixed this a while ago by implementing te behavior discussed above.

**Comment by chirag04** [comment]
:+1:
