### ISSUE TITLE
Modal inside camera freezes the app when its closed

### ISSUE THREAD

**Issue by srameshr** [facebook/react-native#15057]
### Is this a bug report?

Yes

### Have you read the Bugs section of the Contributing to React Native Guide?

(Write your answer here.)
No

### Environment

1. `react-native -v`: 0.46.2
2. `node -v`: 6.4.0
3. `npm -v`: 3.10.3
4. `yarn --version` (if you use Yarn):

Then, specify:

- Target Platform: 
IOS 10.2

- Development Operating System: 
Mac

- Build tools:
```react-native-camera:``` 0.9.4

### Steps to Reproduce

(Write your steps here:)

1. Inside ```react-native-camera``` add a modal and set its initial visibility to false
2. Now set the modal to be visible through ```visible``` prop state update. It works fine.
3. Now close the modal and come back to camera. The whole camera view and app freezes.

### Expected Behavior

 The app should not freeze.
(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo
```
import { Modal } from 'react-native'
import Camera from 'react-native-camera'

class A extends Component {
  constructor(props) {
    super(props);
    this.set.vis = false;
  }
  render() {
    return (
     <Camera
          ref={(cam) => {
            this.camera = cam;
          }}
          aspect={Camera.constants.Aspect.fill}
        >
        <Modal visible={this.state.vis}> modal content </Modal>
     </Camera>
  )
  }
}

```

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by hramos** [comment]
This issue tracker is for issues in the core React Native library.
