### ISSUE TITLE
It seems something went wrong while linking. Error: Expected "/*" or ";" but "\"" found 

### ISSUE THREAD

**Issue by karthi789** [facebook/react-native#15069]
### Is this a bug report?

(write your answer here)

### Have you read the Bugs section of the Contributing to React Native Guide?

(Write your answer here.)

### Environment

1. `react-native -v`:
2. `node -v`:
3. `npm -v`:
4. `yarn --version` (if you use Yarn):

Then, specify:

- Target Platform: 

- Development Operating System: 

- Build tools:

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by jeff-da** [comment]
What module are you trying to link to React Native?

**Comment by rupalpatel0008** [comment]
I am having this same issue when trying to link facebook sdk: "react-native-fbsdk": "^0.6.1"

**Comment by ziadalame** [comment]
Linking  "react-native-fbsdk" v 0.6.1 causes problems. I downgraded to v 0.6.0 and things worked out. Try doing that.

**Comment by blairvanderhoof** [comment]
I also get this for everything i try to link, e.g. codepush and sentry.

`Expected "/*" or ";" but "\"" found.`

**Comment by developdeez** [comment]
Same issue

**Comment by developdeez** [comment]
rolling back to 0.6.0 fixed the linking but of course a new error after.
Something about method in FBSDK not overriding.

**Comment by sybil052** [comment]
I am having this same issue when trying to link react-native-fs: "react-native-fs": "^2.5.1"

**Comment by blairvanderhoof** [comment]
Here is the fix btw, https://github.com/facebook/react-native/issues/13461#issuecomment-295124309
