### ISSUE TITLE
Canonical way to be 'invisible' to touches / forward / delegate responder?

### ISSUE THREAD

**Issue by jonslenkooyala** [facebook/react-native#1507]
hi. I have a top layer view that is getting the touch, and I would like it to /not/ be involved at all in the touch handling -- have the events go to the views underneath. What is the "standard" way this should be coded when using react-native? Thank you.

**Comment by ide** [comment]
You should use pointerEvents: https://facebook.github.io/react-native/docs/view.html#pointerevents
