### ISSUE TITLE
react-native/third-party/glog-0.3.4/src/raw_logging.cc

### ISSUE THREAD

**Issue by flyjennyetn** [facebook/react-native#15075]
react-native 0.46.4

ios :
clang: error: no such file or directory: '/Users/zhengxiaolet/Documents/codepushDemo/node_modules/react-native/third-party/glog-0.3.4/src/raw_logging.cc'
clang: error: no input files

**Comment by hramos** [comment]
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Comment by YourMelody** [comment]
I've got the same issue :(
clang: error: no such file or directory: '/node_modules/react-native/third-party/glog-0.3.4/src/raw_logging.cc'
clang: error: no input files
