### ISSUE TITLE
unable to load scripts from assets 'index.android.bundle' on real device

### ISSUE THREAD

**Issue by ketankulkarni** [facebook/react-native#15070]
### Is this a bug report?
NO

### Environment
    "native-base": "^2.2.1",
    "react": "16.0.0-alpha.12",
    "react-native": "0.46.3",
    "react-native-meteor": "^1.1.0"
    nodejs - 6.10.3
   npm - 3.10.10

- Target Platform:  Android

operating system - ubuntu 16.04LTS

Expected result - output should be displayed on real device

Actal output -
unable to load script from assets index.android.bundle make sure your bundle is packaged correctly or your running a package server

steps taken to resolve the error -
adb reverse tcp:8081 tcp:8081

observations - 
running react-native start or restarting machine gives output sometimes

**Comment by johndanek** [comment]
I started experiencing this too. Works fine on ios simulator. Android simulator and physical device instantly crashes, regardless of `adb reverse`

**Comment by ketankulkarni** [comment]
then what should be done

**Comment by jkomyno** [comment]
+1

**Comment by adlondon** [comment]
+1

**Comment by littlehome-eugene** [comment]
+1

**Comment by njustice4all** [comment]
+1

**Comment by transifex3** [comment]
It's driving me crazy now. any updates here?

**Comment by anwarhamr** [comment]
+1

**Comment by Obooman** [comment]
Have tried make bundle by hand with `react-native bundle --entry-file index.android.js --bundle-output index.android.bundle` and it still doesn't work.

**Comment by anwarhamr** [comment]
It started working for me by running the project from android studio; adb reverse tcp:8081 tcp:8081, and react-native start each separately.

**Comment by rod-stuchi** [comment]
I try this [https://stackoverflow.com/a/44476757/6785523](this) and now is working.

**Comment by snstrauss** [comment]
This link seems to be dead..
maybe you can post it again?

**Comment by rod-stuchi** [comment]
@snstrauss try copy / paste.

**Comment by BhavanPatel** [comment]
This  helped me resolve the problem in following steps.
- If not than (in project directory) mkdir android/app/src/main/assets
- `react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res`

- `react-native run-android`

**Comment by arfaWong** [comment]
@BhavanPatel After reload, get the error again.

**Comment by transifex3** [comment]
Damn it worked!! Thanks @rod-stuchi
It should be fixed officially by developers thou.

**Comment by aadiroid** [comment]
@rod-stuchi, It loads the JS from Offline bundle so if we change anything in code we have to rerun ("react-native bundle") command. And this also disable debug mode. Don't you think its an overhead for a developer.

**Comment by ihewro** [comment]
will offical tend to slove this problem in next version ?

**Comment by firofame** [comment]
this never happened to me in windows.

**Comment by cyphire** [comment]
I think I know what is going on here....  I mistakenly thought I had to constantly do a "react-native init _appname_" each time i moved my source, used a different machine then put my source files into it.  Finally realized to use the .gitignore and store my source from the root of the app, not just my source code.  Now I pull down the whole thing.

At some point i lost my index.android.js and index.ios.js files and only had the starting file index.js (which I think is part of doing the create-react-native-app rather than doing a react-native init _appname_ .

Anyway, I did the above still didn't work.  Instead i renamed my index.js to index.android.js, then copied that file to index.android.js, THEN did the above:

```
 mkdir android/app/src/main/assets

react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res

```
Now when I ran the above it actually created the assets in the right place.

Go see if you only have a index.js file... That is the non-native modules expo way of doing things...

**Comment by Noitidart** [comment]
Something is wrong, this is not normal. I am on Windows 10. This does not happen when testing on device, only when simulator for me.

I am having to run the above:

> react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
> react-native run-android

Every time after making a change. Defeating hot reload. This only happens to me when using emulator. It builds to device fine.

**Comment by REBOOTERS** [comment]
Find another solution .open MainApplication.java in the android directory ,delete the following code if exist

```
import com.facebook.react.BuildConfig;
```

BuildConfig.DEBUG should be true in debug mode ,while in com.facebook.react.BuildConfig it is always false.

**Comment by srishanbhattarai** [comment]
@REBOOTERS That did it for me too after intense `git bisect`. I believe an issue ought to be created for this since Android Studio complains that the import is not present, and importing it implicitly causes nothing to work.

**Comment by raktec** [comment]
latest React-Native Code fallow below Code in mac terminal
step1:  If not than (in project directory) mkdir android/app/src/main/assets 
step2: react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res 
step3: react-native run-android

**Comment by HGWells07** [comment]
@raktec thanks! this worked just fine for me!

**Comment by akamittal** [comment]
In my case, adb path was not defined in environment variables and that's why it was not able to make the assets folder. I set the path and its working fine.

**Comment by lzmhhh123** [comment]
@akamittal Could you tell me how to define adb path in environment variables?

**Comment by akamittal** [comment]
@lzmhhh123 If you have windows machine then follow these steps -
1. Open Control Panel -> System -> Advanced System Settings -> Environment Variables
2. Double Click on "Path"
3. Click on New
4. Add the platform tools path there. For me it was - C:\Users\akash\AppData\Local\Android\sdk\platform-tools
Change "akash" with your Computer's user name.

Make sure you have adb installed before going through these steps.

**Comment by vvavepacket** [comment]
@raktec 

Do we need to execute this 3 lines of code every time we create an android release?

**Comment by Kaveriph** [comment]
Its riddiculous !! I unistalled the app and reinstalled it worked all fine.
Previously also the same happened.. but no idea what is causing the issue sometimes.

**Comment by leonismx** [comment]
Same issue with akamittal, setting the adb environment variable solves it. 
AppData is hidden by default, enable view hidden files to locate.

**Comment by santoshgistto** [comment]
`  
java.lang.RuntimeException: Unable to load script from assets 'index.android.bundle'. Make sure your bundle is packaged correctly or you're running a packager server.
                                                                            at com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromAssets(Native Method)
                                                                            at com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromAssets(CatalystInstanceImpl.java:216)
                                                                            at com.facebook.react.bridge.JSBundleLoader$1.loadScript(JSBundleLoader.java:34)
                                                                            at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:233)
                                                                            at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1126)
                                                                            at com.facebook.react.ReactInstanceManager.access$800(ReactInstanceManager.java:112)
                                                                            at com.facebook.react.ReactInstanceManager$4.run(ReactInstanceManager.java:922)
                                                                            at java.lang.Thread.run(Thread.java:818)
`

App is crashing i am not able load the js bundle.
project structure is like this : android/clients/libs/ui

**Comment by santoshgistto** [comment]
@REBOOTERS  thanks it worked for me .

**Comment by agersoncgps** [comment]
So this fix does solve it, but I would like to understand why it is happening and do I need to run react-native bundle every time I build a new apk?

**Comment by sajidcosmo** [comment]
I get a red screen in my app with the following content:

Can't find variable: DOMParser

_connect_cb_wrapper
index.android.bundle?
platform=android&dev=true&minify=false:
61420:104

.
.
.

Anyone has any idea on it?

**Comment by sudhanvadp** [comment]
Install yarn from internet or choco.
Then normal 'react-native init name'.

(Install yarn before creation of project)
That's it.

If again it fails reply

**Comment by SantoshSah** [comment]
Hi @sudhanvadp,

Same error even after installing yarn before creating project.

**Comment by sudhanvadp** [comment]
In the recent version of react-native they have fixed it. If you want complete freedom from this just uninstall node (For complete uninstallation [Completely remove node][1] refer this link) and reinstall node, react-native-cli then create your new project.


  [1]: https://stackoverflow.com/questions/20711240/how-to-completely-remove-node-js-from-windows/20711410

**Comment by dan-santana** [comment]
The latest react-native version worked fine for me when connecting to an Android device via USB, but the error still happens when connecting ADB to device via TCP/IP.

**Comment by assem-ch** [comment]
Have it in 0.53.3

**Comment by yeahe83** [comment]
same error in 0.53.3, test in physical device and virtual device both

**Comment by olejjon** [comment]
well, what's work for me is just run a command in project root folder `npm install` .

**Comment by alex-gokkun** [comment]
If you're launching gradle via Android Studio try to disable _Offline Work_ (Preferences -> Build, Execution, Deployment -> Gradle). At least it fixed the issue for me.

**Comment by ishigamii** [comment]
updated from 0.53.0 to 0.54.3 and got this error

**Comment by djaonourside** [comment]
react-native v.0.54.3 
I got the same error on android emulator. Solved with 
1. Make directory android/app/src/main/assets
2. Execute command: `react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res`

**Comment by newbby123** [comment]
I tried to run 'adb reverse tcp:8081 tcp:8081' and my machine run. Because my service runs on port 8081

**Comment by andrewgrewell** [comment]
Sorry if I missed this already being mentioned but this can also be caused by setting `org.gradle.configureondemand=true` in your gradle.properties
