### ISSUE TITLE
Navigation Demo Error：this.props.navigator undefined

### ISSUE THREAD

**Issue by wangweiwei** [facebook/react-native#15078]
import React from 'react';
import PropTypes from 'prop-types';
import { AppRegistry, Button, NavigatorIOS, Text, View } from 'react-native';

export default class NavigatorIOSApp extends React.Component {
  render() {
    return (
      <NavigatorIOS
        initialRoute={{
          component: MyScene,
          title: 'My Initial Scene',
        }}
        style={{flex: 1}}
      />
    )
  }
}

class MyScene extends React.Component {
  static propTypes = {
    title: PropTypes.string.isRequired,
    navigator: PropTypes.object.isRequired,
  }

  constructor(props, context) {
    super(props, context);
    this._onForward = this._onForward.bind(this);
  }

  _onForward() {
    this.props.navigator.push({
      title: 'Scene ' + nextIndex,
    });
  }

  render() {
    return (
      <View>
        <Text>Current Scene: { this.props.title }</Text>
        <Button
          onPress={this._onForward.bind(this)}
          title="Tap me to load the next scene"
        />
      </View>
    )
  }
}
AppRegistry.registerComponent('Demo', () => MyScene);
[
react-native-cli: 2.0.1
react-native: 0.46.4
]

**Comment by chenxiaochun** [comment]
所以，为什么报错，还是木有解决吗？
