### ISSUE TITLE
[Proposal] Add crop type option to resizeMode cover

### ISSUE THREAD

**Issue by MrLoh** [facebook/react-native#15080]
Hi, I'm a little confused as to where proposed changes should be reported. The template here and the [guidelines](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md) seem contradictory. 

First of all, I love the great work you are doing, thank you so much. I ran into an issue I couldn't solve though. I want to crop an image to a specific height. Since the image has rounded corners, I can only do so by setting the width and height on the image, using `resizeMode: cover` but this doesn't give me any control about how the image is cropped, it always crops from both top and bottom. I'd like to control the cropping of the resize mode to only crop from the top. Am I overlooking a way, how to do this, or is it simply not possible at the moment? If not, would you consider adding an option. I'd be happy to contribute, but am not very experienced in native development.

**Comment by hramos** [comment]
I wrote up both the template and the guidelines. Let me know what seems contradictory as I'd like to make sure it's clear. Feature requests and proposals should be filed as entries in Canny. We're solely using the GitHub repository for bug reports. We may open up to other types of issues later on once the number of outstanding issues is brought under control.

**Comment by hramos** [comment]
Hmm yeah, it's a bit ambiguous in the contribution guidelines what counts as a feature request vs a proposing a change. I believe the intention here is that, if you're considering sending a PR, filing an issue first to get some feedback is a good idea. It seems like you're open to going down that route, so I'll re-open. Apologies for the confusion.

**Comment by MrLoh** [comment]
@hramos thanks a lot for the clarification. Maybe canny should be mentioned in the [guideline here](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#proposing-a-change) as well. But now I see the reference to canny in the Readme. 

Anyways. I'd love some feedback on how this feature should look from someone more experienced with the Image component prop design.
