### ISSUE TITLE
[Text] String displayed in Text view only updates when number of characters changes.

### ISSUE THREAD

**Issue by jtremback** [facebook/react-native#1508]
In https://github.com/jtremback/CodePathRN, I am incrementing a value and displaying it in a Text element. It exhibits this weird behavior:

![image](http://i.imgur.com/N6GspuQ.gif)

Here's the `render` method:

```js
  render: function() {
    var num = this.state.stepperValue
    console.log(num)
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          {num}
        </Text>
        <Stepper style={styles.stepper}
          onChange={this.onStepperChange}
        />
        <Text style={styles.instructions}>
          To get started, edit index.ios.js
        </Text>
        <Text style={styles.instructions}>
          Press Cmd+R to reload,{'\n'}
          Cmd+D or shake for dev menu
        </Text>
      </View>
    )
  }
```

**Comment by jtremback** [comment]
Update: Adding some random characters, I see that this has to do with the size of the text contained. When the number of characters changes, the view updates.

**Comment by ide** [comment]
cc @a2 @nicklockwood

**Comment by nicklockwood** [comment]
The fix for this was included in Tuesday's update, so if you upgrade to the latest release it should now be working correctly.

https://github.com/ericvicenti/react-native/commit/49e87af934b8060858a8b0e3e1b03b690470b1e8

**Comment by browniefed** [comment]
@brentvatne this is fixed.
