### ISSUE TITLE
Requiring Static Images: Unknown Named Module

### ISSUE THREAD

**Issue by jackmead515** [facebook/react-native#15083]
### Is this a bug report?

Yes

### Have you read the Bugs section of the Contributing to React Native Guide?

Yes

### Environment

1. `react-native -v`: 0.46.1
2. `node -v`: 6.10.1
3. `npm -v`: 3.10.10
4. `yarn --version` (if you use Yarn): n/a

Then, specify:

- Target Platform: Android

- Development Operating System: Windows 10

- Build tools: Android Studio

### Steps to Reproduce

(Write your steps here:)

Attempt to require static png image with require from <Image /> component using a variable.

Ex: 
```
let uri = './../img/image.png';
<Image style={styles.image} source={require(uri)} />
// Does not work! ^

<Image style={styles.image} source={require('./../img/image.png')} />
// Works! ^
```

### Expected Behavior

(Write what you thought would happen.)
```

let str = 'string';
'string' === str //true
```

### Actual Behavior

(Write what happened. Add screenshots!)

![image](https://user-images.githubusercontent.com/24357063/28323903-b569471e-6b9f-11e7-9be0-bfca27a11389.png)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

https://github.com/jackmead515/simpleweather

**Comment by ide** [comment]
The docs talk about this, this is just a requirement of the packager.
> In order for this to work, the image name in require has to be known statically.

https://facebook.github.io/react-native/docs/images.html

**Comment by jackmead515** [comment]
Well. I feel like an idiot after looking through the docs for several hours before posting this. Time to get another bag of coffee.
