### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by sm2017** [facebook/react-native#15098]
At first see https://github.com/facebook/react-native/pull/15046#issuecomment-316272171

Here we have a `base64 encoding` in native environment and `base64 decoding` in js environment( and vise versa for sending binary)

This redundant encode/decode take a lot of CPU resources and can be omitted 

In https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/bridge/WritableMap.java#L21 we only have `putString` so we cannot transfer binary from native to js or vise versa , I request `void putByte(String key, Byte value);` method for android and similar method for iOS and JS side

**Comment by charpeni** [comment]
@facebook-github-bot feature
