### ISSUE TITLE
Embed React Native to existing app failed

### ISSUE THREAD

**Issue by cincas** [facebook/react-native#1510]
Hi everyone,

We're trying to use ReactNative as part of our app and I was going through the documentation recently.

Tried example project EmbeddedReactNative, works fine, but it is using 0.2.*

Tried to do same thing in latest version (0.4.4), keep getting error msg as following:
```
[error][tid:com.facebook.React.JavaScript] "Error: 
 stack: ModuleError@http://localhost:8081/index.ios.bundle:107:23
require@http://localhost:8081/index.ios.bundle:204:28
applyWithGuard@http://localhost:8081/index.ios.bundle:885:25
require@http://localhost:8081/index.ios.bundle:196:39
 line: 204
 message: Requiring unknown module "BatchedBridge". If you are sure the module is there, try restarting the packager.", {"name":"ModuleError","message":"Requiring unknown module \"BatchedBridge\". If you are sure the module is there, try restarting the packager.","stack":"ModuleError@http://localhost:8081/index.ios.bundle:107:23\nrequire@http://localhost:8081/index.ios.bundle:204:28\napplyWithGuard@http://localhost:8081/index.ios.bundle:885:25\nrequire@http://localhost:8081/index.ios.bundle:196:39","framesToPop":2,"line":204,"column":33,"sourceURL":"http://localhost:8081/index.ios.bundle"}
```

Is there any step I miss?
Maybe it is worth to update the example project or documentation at here: http://facebook.github.io/react-native/docs/embedded-app.html#content

Thanks!

**Comment by cincas** [comment]
turns out I made a very stupid mistake. pls ignore this.
Sorry gusy

**Comment by irfaan** [comment]
For anyone else hitting this error, I had an old instance of the React Packager running.

**Comment by drager** [comment]
I'm getting this error on OSX trying to run my application in iOS using an simulator.

**Comment by irfaan** [comment]
Try quitting the packager and running your project again in xcode. It should start a new packager instance. IIRC, that was exactly what I had to do.

**Comment by drager** [comment]
Problem was that the TypeScript transpiling went wrong and added an empty index.ios.js file which did brake packing and gave me that error. My bad...
