### ISSUE TITLE
RCTSRWebSocket.m crashes with SIGSEGV, SIGABRT

### ISSUE THREAD

**Issue by ajinasokan** [facebook/react-native#15101]
### Environment

1. `react-native -v`: react-native-cli: 2.0.1 react-native: 0.44.2
2. `node -v`: v7.10.0
3. `npm -v`: 4.2.0
4. `yarn --version` (if you use Yarn): 0.24.5

- Target Platform: iOS (Happens in different iPhone devices and different iOS versions. Our min version is 9.3)

- Development Operating System: macOS Sierra

- Build tools: Xcode, Visual Studio Code

### Steps to Reproduce

We are not sure when this happens. We can see many crash reports and we have received complaints from clients.

### Expected Behavior

WebSocket thread is supposed to give the stream data

### Actual Behavior

As per crash reports from Mobile Center by Microsoft, native WebSocket module is crashing with SIGSEGV and sometimes SIGABRT signal. This stops WebSocket to stream data.

### Reproducible Demo

We are using the WebSocket implementation in React Native docs. Our app has ~12k users, around 8k sessions per day and it happens for ~20 times a day. Which means this doesn't happen all the time and it is extremely difficult to reproduce. But the data transferred through WebSocket is crucial and we cannot afford to happen this even to a single user.

We have an Android app (Not React Native) and Web app which uses the same WebSocket connection and they don't have any issues at all.

I have attached the crash report dump from Mobile Center.

In Mobile Center it shows such crashes happen in line numbers 1384, 1385, 1405, 1457, 1627 in RCTSRWebSocket.m. 

### Crash Report

Incident Identifier: 2f6e2875-3cdd-4ed0-93f4-ad6b744065b9
CrashReporter Key:   e59e68b7-f972-4c77-832e-31e82d3f9cfd
Hardware Model:      iPhone6,2
Process:         AppName [3089]
Path:            /var/containers/Bundle/Application/99EDAC8E-E0A4-4820-9493-C6FB58D8BBD1/AppName.app/AppName
Identifier:      com.example.appname
Version:         2.0.0 (9)
Code Type:       arm64
Parent Process:  ??? [1]

Date/Time:       2017-07-18T15:32:00.058Z
Launch Time:     2017-07-18T13:01:38.174Z
OS Version:      iPhone OS 10.3.2 (14F89)
Report Version:  104

Exception Type:  SIGSEGV
Exception Codes: SEGV_ACCERR at 0x10
Crashed Thread:  6

Application Specific Information:
stream:handleEvent:

React Exception Stack:
stream:handleEvent:

Thread 6 Crashed:
0   libobjc.A.dylib                      0x0000000186fb0150 objc_msgSend + 16
1   CoreFoundation                       0x000000018848601c _signalEventSync + 208
2   CoreFoundation                       0x0000000188485f28 _cfstream_shared_signalEventSync + 436
3   CoreFoundation                       0x00000001884e942c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 20
4   CoreFoundation                       0x00000001884e8d04 __CFRunLoopDoSources0 + 384
5   CoreFoundation                       0x00000001884e69a8 __CFRunLoopRun + 740
6   CoreFoundation                       0x0000000188416da4 CFRunLoopRunSpecific + 420
7   Foundation                           0x0000000188f30d74 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 300
8   AppName                                 0x000000010020d6c4 -[_RCTSRRunLoopThread main] (RCTSRWebSocket.m:1627)
9   Foundation                           0x000000018902e2d8 __NSThread__start__ + 992
10  libsystem_pthread.dylib              0x00000001875fd68c _pthread_body + 236
11  libsystem_pthread.dylib              0x00000001875fd59c _pthread_start + 280
12  libsystem_pthread.dylib              0x00000001875facb4 thread_start + 0

Thread 0:
0   libsystem_kernel.dylib               0x0000000187517224 mach_msg_trap + 8
1   CoreFoundation                       0x00000001884e8e90 __CFRunLoopServiceMachPort + 188
2   CoreFoundation                       0x00000001884e6ae4 __CFRunLoopRun + 1056
3   CoreFoundation                       0x0000000188416da4 CFRunLoopRunSpecific + 420
4   GraphicsServices                     0x0000000189e80074 GSEventRunModal + 96
5   UIKit                                0x000000018e6d1058 UIApplicationMain + 204
6   AppName                                 0x00000001000ee3cc main (main.m:16)
7   libdyld.dylib                        0x000000018742559c start + 0

Thread 1:
0   libsystem_kernel.dylib               0x0000000187517224 mach_msg_trap + 8
1   CoreFoundation                       0x00000001884e8e90 __CFRunLoopServiceMachPort + 188
2   CoreFoundation                       0x00000001884e6ae4 __CFRunLoopRun + 1056
3   CoreFoundation                       0x0000000188416da4 CFRunLoopRunSpecific + 420
4   Foundation                           0x0000000188f30d74 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 300
5   Foundation                           0x0000000188f51b44 -[NSRunLoop(NSRunLoop) runUntilDate:] + 92
6   UIKit                                0x000000018f05b6a8 -[UIEventFetcher threadMain] + 132
7   Foundation                           0x000000018902e2d8 __NSThread__start__ + 992
8   libsystem_pthread.dylib              0x00000001875fd68c _pthread_body + 236
9   libsystem_pthread.dylib              0x00000001875fd59c _pthread_start + 280
10  libsystem_pthread.dylib              0x00000001875facb4 thread_start + 0

Thread 2:
0   JavaScriptCore                       0x000000018c445180 llint_slow_path_jfalse + 276
1   JavaScriptCore                       0x000000018cbdc114 llint_entry + 23408
2   JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
3   JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
4   JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
5   JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
6   JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
7   JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
8   JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
9   JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
10  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
11  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
12  JavaScriptCore                       0x000000018cbdccc8 llint_entry + 26404
13  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
14  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
15  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
16  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
17  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
18  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
19  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
20  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
21  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
22  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
23  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
24  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
25  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
26  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
27  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
28  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
29  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
30  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
31  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
32  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
33  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
34  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
35  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
36  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
37  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
38  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
39  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
40  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
41  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
42  JavaScriptCore                       0x000000018cbdccc8 llint_entry + 26404
43  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
44  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
45  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
46  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
47  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
48  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
49  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
50  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
51  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
52  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
53  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
54  JavaScriptCore                       0x000000018cbdccc8 llint_entry + 26404
55  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
56  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
57  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
58  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
59  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
60  JavaScriptCore                       0x000000018cbdccc8 llint_entry + 26404
61  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
62  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
63  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
64  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
65  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
66  JavaScriptCore                       0x000000018cbdccc8 llint_entry + 26404
67  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
68  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
69  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
70  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
71  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
72  JavaScriptCore                       0x000000018cbdccc8 llint_entry + 26404
73  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
74  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
75  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
76  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
77  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
78  JavaScriptCore                       0x000000018cbdccc8 llint_entry + 26404
79  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
80  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
81  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
82  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
83  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
84  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
85  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
86  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
87  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
88  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
89  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
90  JavaScriptCore                       0x000000018cbdccc8 llint_entry + 26404
91  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
92  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
93  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
94  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
95  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
96  JavaScriptCore                       0x000000018cbdccc8 llint_entry + 26404
97  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
98  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
99  JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
100 JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
101 JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
102 JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
103 JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
104 JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
105 JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
106 JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
107 JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
108 JavaScriptCore                       0x000000018cbdccc8 llint_entry + 26404
109 JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
110 JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
111 JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
112 JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
113 JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
114 JavaScriptCore                       0x000000018cbdccc8 llint_entry + 26404
115 JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
116 JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
117 JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
118 JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
119 JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
120 JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
121 JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
122 JavaScriptCore                       0x000000018cbdccc8 llint_entry + 26404
123 JavaScriptCore                       0x000000018cbdccc8 llint_entry + 26404
124 JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
125 JavaScriptCore                       0x000000018cbd63d8 vmEntryToJavaScript + 260
126 JavaScriptCore                       0x000000018cac06f8 JSC::JITCode::execute(JSC::VM*, JSC::ProtoCallFrame*) + 160
127 JavaScriptCore                       0x000000018c44d528 JSC::Interpreter::executeCall(JSC::ExecState*, JSC::JSObject*, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) + 412
128 JavaScriptCore                       0x000000018caf4954 JSC::boundThisNoArgsFunctionCall(JSC::ExecState*) + 472
129 JavaScriptCore                       0x000000018cbdd694 llint_entry + 28912
130 JavaScriptCore                       0x000000018cbdccc8 llint_entry + 26404
131 JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
132 JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
133 JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
134 JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
135 JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
136 JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
137 JavaScriptCore                       0x000000018cbd63d8 vmEntryToJavaScript + 260
138 JavaScriptCore                       0x000000018cac06f8 JSC::JITCode::execute(JSC::VM*, JSC::ProtoCallFrame*) + 160
139 JavaScriptCore                       0x000000018c44d528 JSC::Interpreter::executeCall(JSC::ExecState*, JSC::JSObject*, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) + 412
140 JavaScriptCore                       0x000000018caf4954 JSC::boundThisNoArgsFunctionCall(JSC::ExecState*) + 472
141 JavaScriptCore                       0x000000018cbdd694 llint_entry + 28912
142 JavaScriptCore                       0x000000018cbdccc8 llint_entry + 26404
143 JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
144 JavaScriptCore                       0x000000018cbdccc8 llint_entry + 26404
145 JavaScriptCore                       0x000000018cbdccc8 llint_entry + 26404
146 JavaScriptCore                       0x000000018cbdccc8 llint_entry + 26404
147 JavaScriptCore                       0x000000018cbdd108 llint_entry + 27492
148 JavaScriptCore                       0x000000018cbdd108 llint_entry + 27492
149 JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
150 JavaScriptCore                       0x000000018cbdccc8 llint_entry + 26404
151 JavaScriptCore                       0x000000018cbdcc64 llint_entry + 26304
152 JavaScriptCore                       0x000000018cbd63d8 vmEntryToJavaScript + 260
153 JavaScriptCore                       0x000000018cac06f8 JSC::JITCode::execute(JSC::VM*, JSC::ProtoCallFrame*) + 160
154 JavaScriptCore                       0x000000018c44d528 JSC::Interpreter::executeCall(JSC::ExecState*, JSC::JSObject*, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) + 412
155 JavaScriptCore                       0x000000018caf4954 JSC::boundThisNoArgsFunctionCall(JSC::ExecState*) + 472
156 JavaScriptCore                       0x000000018cbd6520 vmEntryToNative + 268
157 JavaScriptCore                       0x000000018c44d56c JSC::Interpreter::executeCall(JSC::ExecState*, JSC::JSObject*, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) + 480
158 JavaScriptCore                       0x000000018c759b74 JSC::profiledCall(JSC::ExecState*, JSC::ProfilingReason, JSC::JSValue, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) + 160
159 JavaScriptCore                       0x000000018c44d29c JSObjectCallAsFunction + 632
160 AppName                                 0x0000000100198234 __65-[RCTJSCExecutor _executeJSCall:arguments:unwrapResult:callback:]_block_invoke (RCTJSCExecutor.mm:634)
161 AppName                                 0x0000000100198a54 -[RCTJSCExecutor executeBlockOnJavaScriptQueue:] (RCTJSCExecutor.mm:798)
162 AppName                                 0x0000000100197df0 -[RCTJSCExecutor _executeJSCall:arguments:unwrapResult:callback:] (RCTJSCExecutor.mm:599)
163 AppName                                 0x00000001001979b8 -[RCTJSCExecutor _callFunctionOnModule:method:arguments:returnValue:unwrapResult:callback:] (RCTJSCExecutor.mm:571)
164 AppName                                 0x0000000100197ad4 -[RCTJSCExecutor callFunctionOnModule:method:arguments:callback:] (RCTJSCExecutor.mm:576)
165 AppName                                 0x000000010019e55c -[RCTBatchedBridge _actuallyInvokeAndProcessModule:method:arguments:] (RCTBatchedBridge.m:881)
166 AppName                                 0x000000010019d918 __57-[RCTBatchedBridge enqueueJSCall:method:args:completion:]_block_invoke (RCTBatchedBridge.m:765)
167 AppName                                 0x0000000100198a54 -[RCTJSCExecutor executeBlockOnJavaScriptQueue:] (RCTJSCExecutor.mm:798)
168 Foundation                           0x000000018902e4cc __NSThreadPerformPerform + 336
169 CoreFoundation                       0x00000001884e942c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 20
170 CoreFoundation                       0x00000001884e8d9c __CFRunLoopDoSources0 + 536
171 CoreFoundation                       0x00000001884e69a8 __CFRunLoopRun + 740
172 CoreFoundation                       0x0000000188416da4 CFRunLoopRunSpecific + 420
173 AppName                                 0x0000000100195a58 +[RCTJSCExecutor runRunLoopThread] (RCTJSCExecutor.mm:211)
174 Foundation                           0x000000018902e2d8 __NSThread__start__ + 992
175 libsystem_pthread.dylib              0x00000001875fd68c _pthread_body + 236
176 libsystem_pthread.dylib              0x00000001875fd59c _pthread_start + 280
177 libsystem_pthread.dylib              0x00000001875facb4 thread_start + 0

Thread 3:
0   libsystem_kernel.dylib               0x0000000187535314 __semwait_signal + 8
1   libc++.1.dylib                       0x0000000186f653c4 std::__1::this_thread::sleep_for(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > const&) + 76
2   JavaScriptCore                       0x000000018cdc8d08 bmalloc::Heap::scavenge(std::__1::unique_lock<bmalloc::StaticMutex>&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l> >) + 268
3   JavaScriptCore                       0x000000018cdc8adc bmalloc::Heap::concurrentScavenge() + 116
4   JavaScriptCore                       0x000000018cdc9ebc bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>::threadRunLoop() + 88
5   JavaScriptCore                       0x000000018cdc9de8 bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>::threadEntryPoint(bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>*) + 32
6   JavaScriptCore                       0x000000018cdca098 void* std::__1::__thread_proxy<std::__1::tuple<void (*)(bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>*), bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>*> >(void*) + 88
7   libsystem_pthread.dylib              0x00000001875fd68c _pthread_body + 236
8   libsystem_pthread.dylib              0x00000001875fd59c _pthread_start + 280
9   libsystem_pthread.dylib              0x00000001875facb4 thread_start + 0

Thread 4:
0   libsystem_kernel.dylib               0x0000000187517224 mach_msg_trap + 8
1   CoreFoundation                       0x00000001884e8e90 __CFRunLoopServiceMachPort + 188
2   CoreFoundation                       0x00000001884e6ae4 __CFRunLoopRun + 1056
3   CoreFoundation                       0x0000000188416da4 CFRunLoopRunSpecific + 420
4   CFNetwork                            0x0000000188c22df4 +[NSURLConnection(Loader) _resourceLoadLoop:] + 400
5   Foundation                           0x000000018902e2d8 __NSThread__start__ + 992
6   libsystem_pthread.dylib              0x00000001875fd68c _pthread_body + 236
7   libsystem_pthread.dylib              0x00000001875fd59c _pthread_start + 280
8   libsystem_pthread.dylib              0x00000001875facb4 thread_start + 0

Thread 5:
0   libsystem_kernel.dylib               0x0000000187517224 mach_msg_trap + 8
1   CoreFoundation                       0x00000001884e8e90 __CFRunLoopServiceMachPort + 188
2   CoreFoundation                       0x00000001884e6ae4 __CFRunLoopRun + 1056
3   CoreFoundation                       0x0000000188416da4 CFRunLoopRunSpecific + 420
4   WebCore                              0x000000018d0e8608 RunWebThread(void*) + 452
5   libsystem_pthread.dylib              0x00000001875fd68c _pthread_body + 236
6   libsystem_pthread.dylib              0x00000001875fd59c _pthread_start + 280
7   libsystem_pthread.dylib              0x00000001875facb4 thread_start + 0

Thread 7:
0   libsystem_kernel.dylib               0x000000018753523c __select + 8
1   libsystem_pthread.dylib              0x00000001875fd68c _pthread_body + 236
2   libsystem_pthread.dylib              0x00000001875fd59c _pthread_start + 280
3   libsystem_pthread.dylib              0x00000001875facb4 thread_start + 0

Thread 8:
0   libsystem_kernel.dylib               0x0000000187534e1c __psynch_cvwait + 8
1   JavaScriptCore                       0x000000018c41d8b4 WTF::ThreadCondition::timedWait(WTF::Mutex&, double) + 76
2   JavaScriptCore                       0x000000018cdb0b18 WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&) + 2252
3   JavaScriptCore                       0x000000018ca28b7c JSC::Heap::stopTheMutator() + 268
4   JavaScriptCore                       0x000000018ca265c4 JSC::Heap::stopTheWorld() + 156
5   JavaScriptCore                       0x000000018ca27e54 JSC::Heap::collectInThread() + 188
6   JavaScriptCore                       0x000000018ca2a974 JSC::Heap::Thread::work() + 12
7   JavaScriptCore                       0x000000018cda08a4 std::__1::__function::__func<WTF::AutomaticThread::start(WTF::Locker<WTF::LockBase> const&)::$_0, std::__1::allocator<WTF::AutomaticThread::start(WTF::Locker<WTF::LockBase> const&)::$_0>, void ()>::operator()() + 348
8   JavaScriptCore                       0x000000018c419e88 WTF::threadEntryPoint(void*) + 208
9   JavaScriptCore                       0x000000018c419d98 WTF::wtfThreadEntryPoint(void*) + 20
10  libsystem_pthread.dylib              0x00000001875fd68c _pthread_body + 236
11  libsystem_pthread.dylib              0x00000001875fd59c _pthread_start + 280
12  libsystem_pthread.dylib              0x00000001875facb4 thread_start + 0

Thread 9:
0   libsystem_kernel.dylib               0x0000000187535a88 __workq_kernreturn + 8
1   libsystem_pthread.dylib              0x00000001875facac start_wqthread + 0

Thread 10:
0   libsystem_pthread.dylib              0x00000001875faca8 start_wqthread + 0

Thread 11:
0   libsystem_kernel.dylib               0x0000000187535a88 __workq_kernreturn + 8
1   libsystem_pthread.dylib              0x00000001875facac start_wqthread + 0

Thread 12:
0   libsystem_kernel.dylib               0x0000000187535a88 __workq_kernreturn + 8
1   libsystem_pthread.dylib              0x00000001875facac start_wqthread + 0

Thread 13:
0   libsystem_kernel.dylib               0x0000000187535a88 __workq_kernreturn + 8
1   libsystem_pthread.dylib              0x00000001875facac start_wqthread + 0

Thread 14:
0   libsystem_kernel.dylib               0x0000000187535a88 __workq_kernreturn + 8
1   libsystem_pthread.dylib              0x00000001875facac start_wqthread + 0

Thread 15:
0   libsystem_kernel.dylib               0x0000000187535a88 __workq_kernreturn + 8
1   libsystem_pthread.dylib              0x00000001875facac start_wqthread + 0

Thread 6 crashed with arm64 Thread State:
   x21: 0x000000011024f780     x2: 0x000000017411f260    x16: 0x0000000000000000     x3: 0x0000000000000008
   x22: 0x0000000000000008     x4: 0x0000000000000001    x17: 0x000000010020c16c   cpsr: 0x0000000020000000
    x5: 0x0000000000000001    x23: 0x00000001884dad28     x6: 0x000000017417ed80    x18: 0x0000000000000000
   x10: 0x000000010121a600     lr: 0x000000018848601c     x7: 0x0000000108e34010    x24: 0x0000000000000008
   x11: 0x000000330000007f     x8: 0x0000000000000001    x19: 0x000000017411f260    x25: 0x0000000000000000
    x9: 0x00000001891881ff    x12: 0x000000010121adf0     fp: 0x000000016e6f5d50    x26: 0x0000000000000008
   x13: 0x8000000000000000     pc: 0x0000000186fb0150    x27: 0x00000001ad28dffc    x14: 0x0000850000008500
   x20: 0x000000017411f298     x0: 0x000000011024f780     sp: 0x000000016e6f5d10    x28: 0x0000000000000000
   x15: 0x0000000000000000     x1: 0x00000001891881ff

Binary Images:
0x00000001000e8000 -        0x0000000100277fff +AppName arm64  <21dff666-9cae-3263-95a3-c4ab58ede6fb> /var/containers/Bundle/Application/99EDAC8E-E0A4-4820-9493-C6FB58D8BBD1/AppName.app/AppName
0x0000000186f1e000 -        0x0000000186f73fff  libc++.1.dylib arm64  <da0f6a86-db85-3140-b2d7-9e3b36f28795> /usr/lib/libc++.1.dylib
0x0000000186f94000 -        0x0000000187371fff  libobjc.A.dylib arm64  <85f3b59b-9624-3690-b138-ce96e663bf4b> /usr/lib/libobjc.A.dylib
0x0000000187421000 -        0x0000000187425fff  libdyld.dylib arm64  <6c6a61f7-20cf-30da-a4a3-57cbefbf4cd6> /usr/lib/system/libdyld.dylib
0x0000000187516000 -        0x000000018753afff  libsystem_kernel.dylib arm64  <27562406-1b1a-3ab3-91ba-f08b4ba58a97> /usr/lib/system/libsystem_kernel.dylib
0x00000001875fa000 -        0x0000000187603fff  libsystem_pthread.dylib arm64  <8f14c41e-6536-348a-9b6f-fd2a82be7d57> /usr/lib/system/libsystem_pthread.dylib
0x000000018840e000 -        0x000000018878ffff  CoreFoundation arm64  <719044f9-5fe2-3ee0-ab14-504def42b100> /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
0x0000000188b41000 -        0x0000000188eb5fff  CFNetwork arm64  <05331a42-dd8b-31ce-a6ef-547eadc487cd> /System/Library/Frameworks/CFNetwork.framework/CFNetwork
0x0000000188f24000 -        0x00000001891f3fff  Foundation arm64  <08e6a29f-dbac-38dd-817c-66cedf0e0052> /System/Library/Frameworks/Foundation.framework/Foundation
0x0000000189e74000 -        0x0000000189e88fff  GraphicsServices arm64  <b5749f3f-a6f1-3ce6-8968-3db33f23256c> /System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices
0x000000018c410000 -        0x000000018ce52fff  JavaScriptCore arm64  <f4afe098-cd9b-33c2-b336-9773851e26b9> /System/Library/Frameworks/JavaScriptCore.framework/JavaScriptCore
0x000000018d0a5000 -        0x000000018e29afff  WebCore arm64  <d0a2b6b3-b794-34a0-8272-968e20cd00a7> /System/Library/PrivateFrameworks/WebCore.framework/WebCore
0x000000018e65c000 -        0x000000018f403fff  UIKit arm64  <4ad90348-edcc-3d21-983f-83490705f2aa> /System/Library/Frameworks/UIKit.framework/UIKit

**Comment by hramos** [comment]
Thanks for opening the issue! It does not appear like a community member will be able to reliably reproduce this issue. This may be for several reasons; perhaps it affects a particular app but a minimal repro has not been provided, or the issue may be sporadic. As it happens, we need a concrete set of steps that can demonstrably reproduce the issue as this will allow your fellow community members to validate a fix. We'll close the issue for now, but feel free to submit a new issue once you're able to reliably reproduce the issue locally. Thanks for your understanding!

**Comment by jose920405** [comment]
It happens in my project constantly seeing crashes in AppSee
