### ISSUE TITLE
[WebView] Expose scalesPageToFit

### ISSUE THREAD

**Issue by cleercode** [facebook/react-native#1511]
iOS `UIWebView` has a `scalesPageToFit` property that scales the non-mobile web content down to fit in the web view.

**Comment by alvaromb** [comment]
I've sent a PR with this feature a couple of days ago :smile: 

https://github.com/facebook/react-native/pull/1631

You can already use it in the v0.7.0-rc.2 release.

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/webview-expose-scalespagetofit

**Comment by alvaromb** [comment]
I think my PR got merged a few versions ago @brentvatne. Thanks!

**Comment by brentvatne** [comment]
Oh awesome, thanks for the follow up @alvaromb!
