### ISSUE TITLE
Error: Cnnot find module 'fb-watchman' 

### ISSUE THREAD

**Issue by Symous** [facebook/react-native#15117]
when I run react-native start or react-native run-android(ios),
it gives me an error that : Cnnot find module 'fb-watchman' ;

I have try to delete node_modules and run npm install and the error still exist;

OS: Windows 10 64 bit
Platfrom : Android 7.0
React-Native : 0.45.1
Node: 8.1.3

**Comment by Symous** [comment]
Just found that the fb-watchman and some other lib folder disappeared from node_modules , they didn't add to node_modules again even I have run npm install . so wired. I copy the lost libs from another project and now it works. Is that a bug of RN ?

**Comment by brentvatne** [comment]
sounds like a bug with npm, I imagine with node 8.1.3 you're using npm5 which is pretty buggy, I'd recommend npm 4.6.1 or yarn
