### ISSUE TITLE
[package.json] npm (2.10.1) chokes on package.json when installing the examples

### ISSUE THREAD

**Issue by chumster** [facebook/react-native#1512]
this fixed it:

"sane": "git://github.com/tadeuzagallo/sane#a029f8b04a",
"stacktrace-parser": "git://github.com/frantic/stacktrace-parser#493c5e5638",

**Comment by brentvatne** [comment]
Interesting, in a recent commit I changed this to specifically not include the git schema

@chumster - does `npm i tadeuzagallo/sane#a029f8b04a` work for you?

**Comment by brentvatne** [comment]
With latest npm `2.7.5` as well as `1.x`

**Comment by brentvatne** [comment]
Closing because I didn't hear back from you
