### ISSUE TITLE
Samsung doesn't display slider bar

### ISSUE THREAD

**Issue by DylanKeystoke** [facebook/react-native#15127]
### Is this a bug report?

Yes

### Have you read the Bugs section of the How to Contribute guide?

Yes

### Environment

1. `react-native -v`:0.45.1
2. `node -v`: 6.11.0
3. `npm -v`: 3.10.10
4. `yarn --version`:

Then, specify:

- Target Platform: Android

- Development Operating System: macOS Sierra 10.12.5

- Build tools: N/A

### Steps to Reproduce

1. Import Slider from React Native
2. Render Slider in a View with minimumTintColor and maximumTintColor declared
3. Build on Device
4. Navigate to Slider Component

### Expected Behavior

I expected a track bar to appear across all devices. 

### Actual Behavior

Track bar appears on all devices except for Samsung devices. The first example is the result on a Samsung device and the second is on a Pixel. As you can see there is no tracking bar on the Samsung device. 

![screenshot_20170717-143640](https://user-images.githubusercontent.com/7320279/28440113-9377f3b8-6d6a-11e7-8c81-95108077522c.png)
![screenshot_20170717-150125](https://user-images.githubusercontent.com/7320279/28440117-955007c0-6d6a-11e7-93e6-75ac5563a0ab.png)

### Reproducible Demo

Open on Samsung Device

https://snack.expo.io/S16WUoCSZ

Any assistance would be greatly appreciated. 

Thanks for all you do!

**Comment by zibs** [comment]
Thanks for the Snack demo - I'm noticing that the slider actually does appear if you remove the `transform: [{ rotateZ: '-90deg' }]` style.  Is this also the case with the Samsung device? Does the slider show up leave it in its horizontal position?

**Comment by DylanKeystoke** [comment]
The ```renderToHardwareTextureAndroid``` prop worked, thank you!
