### ISSUE TITLE
EXC_BAD_ACCESS when accessing _moduleDataByName in RCTBatchedBridge.mm

### ISSUE THREAD

**Issue by nbyh100** [facebook/react-native#15129]
I guess it will crash when reloading RCTBridge randomly. The variable _moduleDataByName is not thread safe. 

The implementation of reload method, first stop and release modules, then re-init them.
<pre>
- (void)reload
{
  dispatch_async(dispatch_get_main_queue(), ^{
    [self invalidate];
    [self setUp];
  });
}
</pre>

A part of invalidate method, call on JavaScript queue. Set _moduleDataByName to nil.
<pre>
dispatch_group_notify(group, dispatch_get_main_queue(), ^{
    [self->_javaScriptExecutor executeBlockOnJavaScriptQueue:^{
      [self->_displayLink invalidate];
      self->_displayLink = nil;

      [self->_javaScriptExecutor invalidate];
      self->_javaScriptExecutor = nil;

      if (RCTProfileIsProfiling()) {
        RCTProfileUnhookModules(self);
      }

      self->_moduleDataByName = nil; 
      self->_moduleDataByID = nil;
      self->_moduleClassesByID = nil;
      self->_pendingCalls = nil;

      if (self->_flowIDMap != NULL) {
        CFRelease(self->_flowIDMap);
      }
    }];
  });
</pre>

Then call the initModulesWithDispatchGroup on the main queue, init the value of _moduleDataByName.

For the invalid method has some async logic, setting and releasing _moduleDataByName may execute concurrently. It causes the memory problem.

**Comment by shergin** [comment]
It is unclear is this true or not, actually. Let's keep in open for visibility.
(T19226372)
