### ISSUE TITLE
Unhandled error Network error: Network request failed Error:

### ISSUE THREAD

**Issue by haris-ramzan** [facebook/react-native#15121]
I  got this error in my application ( react-native ) when internet connection is lost. 
### Version
   "apollo-client" "1.0.4", 
   "react-apollo": "1.1.1",
    "react-native": "0.44.0",
 ### Found this error on console
 ```"ExceptionsManager.js:71 Unhandled error Network error: Network request failed Error: Network error: Network request failed at new ApolloError"```

How can i fix this issue: Here is my Screen-Shot,
![screenshot_1499843569](https://user-images.githubusercontent.com/25927759/28413431-e97ff0bc-6d60-11e7-9bb1-9d42b471ca0b.png)
```import ApolloClient, { createNetworkInterface } from 'apollo-client';
import { AsyncStorage } from 'react-native';
import {SubscriptionClient, addGraphQLSubscriptions} from 'subscriptions-transport-ws';

const wsClient = new SubscriptionClient('wss://172.20.32.6:5000', {
  reconnect: true,
  connectionParams: {
    accessToken: 'jka sdhkjashd jkashdjk ashdas'
  }
});

const networkInterface = createNetworkInterface({

  uri: 'http://172.20.32.6:8000/graphql',
  opts: {
    credentials: 'same-origin'
  }
});
const networkInterfaceWithSubscriptions = addGraphQLSubscriptions(
  networkInterface,
  wsClient
);
const client = new ApolloClient({
  dataIdFromObject: o => o.id,
  networkInterface: networkInterfaceWithSubscriptions

});
networkInterface.use([{
  applyMiddleware(req, next) {
    if (!req.options.headers) {
      req.options.headers = {};  // Create the header object if needed.
    }
    // get the authentication token from local storage if it exists
    AsyncStorage.getItem('sessionToken').then((token) => {
      req.options.headers.Authorization = token ? `${token}` : null;
      next();
    }
    );
  }
}]);
export default client;

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.

**Comment by reactionic127** [comment]
@haris-ramzan 
did you fixed this error at all?
