### ISSUE TITLE
Statusbar disappear after rotating back to Portrait when watching Video (webview iOS) in landscape (fullscreen)

### ISSUE THREAD

**Issue by samw2k00** [facebook/react-native#15134]
When opening up WebView to play video either from Youtube or Vimeo, iOS open up it native player. After rotating the phone to landscape to view the video in fullscreen mode (status bar still there), when i rotate the phone back to portrait, the status bar disappeared.

### Environment
1. `react-native -v`: 0.44.1  - "0.46.4"
2. `node -v`:  6.10.3
3. `npm -v`: 3.10.10
4. `yarn --version`: 0.23.4

- Target Platform: iOS (10.3.x) only. Tested in iOS 8.x and iOS 9.1 (no problem)
- Development Operating System: macOS

### Steps to Reproduce

1. Open Youtube or Vimeo URL using WebView (At this point the status bar is there)
2. play the video (native iOS player), then rotate the screen to landscape 
3. rotate back the screen to portrait, 
4. pressed done, you will see the status bar disappeared

iOS simulator 10.3
react-native init <project_name>

modify index.ios.js with

```/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  WebView
} from 'react-native';

export default class VideoTest extends Component {
  render() {
    return (
      <WebView
        source={{ uri: 'https://vimeo.com/195741434' }}
        style={{ flex: 1 }}
      />
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

AppRegistry.registerComponent('VideoTest', () => VideoTest);
```
Videos Proof!!

**iOS9 seem perfectly fine**

![ios9](https://user-images.githubusercontent.com/496038/28666695-dae86902-730b-11e7-8410-25c180ab8bd5.gif)

**iOS10, the status bar disappeared after full screen (rotation)**

![ios10](https://user-images.githubusercontent.com/496038/28666727-f5a53a36-730b-11e7-913a-e7199ced19f1.gif)

**Comment by samw2k00** [comment]
Need help pls!!!

**Comment by QB3L** [comment]
+1 I have the same problem

**Comment by wikieswan** [comment]
+ 1

**Comment by wikieswan** [comment]
i use `StatusBar.setHidden(false);`
