### ISSUE TITLE
Consider re-licensing to AL v2.0, as RocksDB has just done

### ISSUE THREAD

**Issue by huhuanming** [facebook/react-native#15133]
Hi there,

`Facebook BSD+Patents License`  did great damage to the community, and I am afraid that community will be split in the future.

Something like this might happen and no one will like it:

```
React = Oracle JDK
Preact = OpenJDK
```

But we cannot blame facebook, because there is no doubt about the legal right.

so it is just a request for `React Native`.

**Comment by codepunkt** [comment]
Consider
https://github.com/facebook/react/issues/10191
for related discussion.

**Comment by gaearon** [comment]
I'll close this. Please follow https://github.com/facebook/react/issues/10191 for updates.

**Comment by gaearon** [comment]
React Native has been relicensed as MIT.

https://github.com/facebook/react-native/commit/26684cf3adf4094eb6c405d345a75bf8c7c0bf88
