### ISSUE TITLE
Rendering issues with border radius on iOS devices

### ISSUE THREAD

**Issue by nazywamsiepawel** [facebook/react-native#15137]
Dear all,

As soon as I apply border radius on a view I'm getting a strange rendering issue- gradient like lines appear in the corners. I believe it's an issue of a similar nature to #2089 which I believe has been already resolved with https://github.com/facebook/react-native/commit/b115277d00f54fa7af5d61062c9e3cf362b7c5da last year. It seems to happen again but only on certain iOS devices. 

So far, from what I have tested:

Occurs on : iPhone 5s (iOS 9.2.1), iPhone 6 (iOS 10.3.2), iPhone 5 (iOS 9.0, 9.3).
Doesn't occur on iPhone 6s (iOS 10.2.1)

The style I am applying on the view : 
```
  highlightBackground: {
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
    backgroundColor: '#4DADF7',
  },
```

The issue look like this: 

![screen shot 2017-07-21 at 13 54 14](https://user-images.githubusercontent.com/334875/28464777-68748b0e-6e1e-11e7-877f-a44ab32e36ec.png)

I'm currently using RN version 0.42.0

**Comment by vaxxis** [comment]
Any updates on this? Has anyone found a solution or a workaround? I stil have this problem in iPod touch iOS 11.3 (rn v0.54).

**Comment by Whyseverythingtaken** [comment]
Getting very similar issues on rn 0.57.0 on ipad mini 2 (ios 12) but not on iphone 7 plus. Getting rid of border radius fixes the problem
