### ISSUE TITLE
[iOS] Non-editable, Multiline TextInput chops text on Re-Render

### ISSUE THREAD

**Issue by trblandford4** [facebook/react-native#15142]
### Is this a bug report?

Yes.

### Environment

1. `react-native -v`: `react-native-cli: 2.0.1` `react-native: 0.46.4`
2. `node -v`: `v7.7.2`
3. `npm -v`: `4.1.2`

Then, specify:
- Target Platform: **iOS**

- Development Operating System: **macOS Sierra v10.12.5**

### Steps to Reproduce

(Write your steps here:)

1. Create TextInput with long, multiline text value, set editable to false
2. Create Text with same value as above
3. Toggle between the two components using state change

### Expected Behavior

Long text appears as scrollable and fully created inside disabled TextInput, as it would in an editable TextInput or plain Text.

### Actual Behavior

Text is cut short, like this : 

<img width="241" alt="screen shot 2017-07-21 at 11 58 28 am" src="https://user-images.githubusercontent.com/10342337/28471730-1b160be2-6e0c-11e7-856f-6aebf8352cd7.png">

### Reproducible Demo

https://snack.expo.io/BkX2enyUZ

**Comment by zibs** [comment]
I think the issue here might be more with your styling (padding/height etc.) than a bug to do with TextInput/Editable.

I've remove the styling from your snack and just left it with a `flex: 1` and it seems to render fine:
https://snack.expo.io/By8gpCk8b
