### ISSUE TITLE
Can not run "react-native run-android"

### ISSUE THREAD

**Issue by ngocdb** [facebook/react-native#15140]
1. I join a react native project & I checkout all the project to local.
2. I setuped everything is OK.
3. I run the normal command for a react native project in android (with a opened emulator already)
4. But immediately after I run the command, I get the below error.
react-native run-android
Scanning 675 folders for symlinks in /media/datas/websites/groot/node_modules (18ms)
JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug)...
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

===>
There is no clue for me to check, it seems the command stop right after running without any scan on module. I can sure I have an opening emulator.
Please help, how can I debug the error ?

**Comment by dipernaa** [comment]
https://github.com/facebook/react-native/issues/8868

**Comment by ngocdb** [comment]
OK, thank you @dipernaa , it works!

**Comment by NarendraSingh88** [comment]
@dipernaa  `chmod 755 android/gradlew` is not working for me. :(

**Comment by RajaSaravanan** [comment]
@dipernaa Thank you it works for me!

**Comment by oehc123** [comment]
@NarendraSingh88 

@dipernaa chmod 755 android/gradlew is not working for me. :(

does not work for me either
