### ISSUE TITLE
Feature request to shut down the app & BackHandler not working in Snack

### ISSUE THREAD

**Issue by croraf** [facebook/react-native#15149]
https://snack.expo.io/SJdErhlLZ

BackHander does not prevent the back button default behavior to close the app in this Snack (on preview and device). But it does prevent in my project.

The other issue is that on the real device back button does not shut down the app it just puts it in background. It would be good to have an option to shut down the app on back button pressed. Check also #15106.
(Android 7.0, expo 18.0.3, react-native 0.45.1 )

#13483

**Comment by brentvatne** [comment]
hello! please follow the issue template in the future :) I don't really understand what you are describing here

**Comment by croraf** [comment]
OK :). In case someone wanders, the answer is probably this: 
The back button should not shut down the app but put it in background. The developer should assure that all things that should stop when app is in background actually do stop.
