### ISSUE TITLE
react-native-git-upgrade to specific commit 

### ISSUE THREAD

**Issue by sm2017** [facebook/react-native#15153]
I want to upgrade react-native@0.46.1 to commit https://github.com/facebook/react-native/commit/7e29b1fc7711a285765f021be3e83a981b066435
According to https://github.com/facebook/react-native/issues/15105 I do the following

#package.json
```
"dependencies": {
		...,
		"react-native": "facebook/react-native#7e29b1fc7711a285765f021be3e83a981b066435",
		,,,
	},
```
#commands 
```
yarn install
react-native-git-upgrade
```

> git-upgrade info Check for updates
> git-upgrade info Using yarn 0.27.5
> git-upgrade info Read package.json files
> git-upgrade info Check declared version
> git-upgrade info Check matching versions
> git-upgrade ERR! An error occurred during upgrade:
> git-upgrade ERR! Error: react-native version in "package.json" (facebook/react-native#7e29b1fc7711a285765f021be3e83a981b066435) doesn't match the installed version in "node_modules" (1000.0.0).
> Try running "yarn" to fix this.

**Comment by brentvatne** [comment]
react-native-git-upgrade doesn't support arbitrary commits. you should run it on the latest release before that commit, then update the version in package.json again to the commit you want. a PR to support this is welcome, if you don't want to work on that then please create a feature request on http://react-native.canny.io/
