### ISSUE TITLE
[Image] iPhone 4s Simulator unable to render <Image> with .jpeg extension

### ISSUE THREAD

**Issue by marcshilling** [facebook/react-native#1515]
```javascript
<Image source={{uri: 'http://www.rick.com/wp-content/uploads/2013/02/third-eye-blind.jpeg'}} />
```

Image is loaded fine on every simulator except iPhone 4s.

**Comment by JonasJonny** [comment]
Try to add specific width and height in style.

**Comment by marcshilling** [comment]
The image has a width and height. Like I said, the image loads on non-iPhone 4s devices. Also, using a non-.jpeg image source on the 4s displays an image - leading me to believe it is specific to the 4S and JPEG images.

**Comment by JonasJonny** [comment]
I can't see style on your example.
Anyway I tried display your link inside my 4S simulator with specific width and height and it worked.

**Comment by JonasJonny** [comment]
```
<View>
    <Image style={{width: 100, height: 100}} source={{uri: 'http://www.rick.com/wp-content/uploads/2013/02/third-eye-blind.jpeg'}} />
</View>

**Comment by marcshilling** [comment]
This is annoying. Yes, you're right - in a fresh `react-native init` project that works. However I am having all sorts of issues with `<Image>` with my particular project setup, which unfortunately I can't easily share. See #1516

**Comment by browniefed** [comment]
@brentvatne this was fixed with 10 fixing defaultSource..
