### ISSUE TITLE
Cannot build TestFlight version after upgrading to 0.46.4

### ISSUE THREAD

**Issue by zakster12** [facebook/react-native#15168]
### Is this a bug report?

Yes

### Environment
macOs Sierra

I deleted the node_modules folder and ran npm install. After that I change the package.json to:
```
"dependencies": {
        "react": "16.0.0-alpha.12",
        "react-native": "^0.46.4",
    },
    "devDependencies": {
        "babel-jest": "20.0.3",
        "babel-preset-react-native": "1.9.2",
        "eslint-config-rallycoding": "^3.2.0",
        "jest": "20.0.4",
        "react-test-renderer": "16.0.0-alpha.13"
    },
```

1. `react-native -v`: 
react-native-cli: 2.0.1
react-native: 0.46.4
2. `node -v`: v6.11.1
3. `npm -v`: 5.3.0

After I upgraded to React Native 0.46.4 I cannot build TestFlight version. I can build version for the simulator and for the device (Debug) but when I tried to make an Archive for TestFlight (Release) I have the following error:

```
/Users/user/Workspace/BobeZ/node_modules/metro-bundler/build/lib/TerminalClass.js:141
    this._nextStatusStr = util.format(format, ...args);

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Module._extensions..js (module.js:417:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/user/Workspace/BobeZ/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/user/Workspace/BobeZ/node_modules/react-native/local-cli/server/runServer.js:18:18)
    at Module._compile (module.js:410:26)
+ [[ false != true ]]
+ [[ ! -f /Users/user/Library/Developer/Xcode/DerivedData/BobeZ-gftwimogvotpwtbuhunewxpyezll/Build/Intermediates/ArchiveIntermediates/Tuts/BuildProductsPath/Release-iphoneos/BobeZ.app/main.jsbundle ]]
+ echo 'error: File /Users/user/Library/Developer/Xcode/DerivedData/BobeZ-gftwimogvotpwtbuhunewxpyezll/Build/Intermediates/ArchiveIntermediates/BobeZ/BuildProductsPath/Release-iphoneos/BobeZ.app/main.jsbundle does not exist. This must be a bug with'
error: File /Users/user/Library/Developer/Xcode/DerivedData/BobeZ-gftwimogvotpwtbuhunewxpyezll/Build/Intermediates/ArchiveIntermediates/BobeZ/BuildProductsPath/Release-iphoneos/BobeZ.app/main.jsbundle does not exist. This must be a bug with
+ echo 'React Native, please report it here: https://github.com/facebook/react-native/issues'
React Native, please report it here: https://github.com/facebook/react-native/issues
+ exit 2
```
I edited the scheme to be for Release and also have the right signing setup.

**Comment by kelset** [comment]
Looks like your issue is related to the [packager](https://github.com/facebook/metro-bundler) - and in particular, the jsbundle isn't being created.

Have you tried running `react-native run-ios`? Does it work in that case?

**Comment by zakster12** [comment]
@kelset Yes, it's working with `react-native run-ios`.

**Comment by BenBenz** [comment]
I have the same problem

**Comment by kelset** [comment]
Ok, just tested with my config: I think there have been some issues during your update to `0.46.4` - maybe try following [this guide](https://medium.com/react-native-training/updating-your-react-native-app-a724c996a76d) which is quite comprehensive.

One other possible issue is `node 6`. I have `8.2.1`.

**Comment by zakster12** [comment]
@kelset updating to node 8 fixed the problem. Thank you!

**Comment by renatobenks** [comment]
@zakster12 I'm currently on 8.1.2 version node and it's not working. This is only it's solved with 8 version node? Don't make sense!
