### ISSUE TITLE
[Image] "defaultSource" prop not working

### ISSUE THREAD

**Issue by marcshilling** [facebook/react-native#1516]
Duplicate of #980, but my post there wasn't getting any love.

Here's my code:
```javascript
<Image style={styles.avatar}
       source={{uri: 'http://cdn.macrumors.com/article-new/2015/06/Apple-Watch-Midnight-Blue-250x299-250x273.jpg?retina'}}
       defaultSource={require('image!placeholder')} 
/>
```

I use the network link conditioner tool to slow down my internet connection so that I can test this, and the image view remains blank until the URL is loaded, at which point it is displayed. I can confirm my "placeholder" image is working correctly because it is displayed fine when I do:

```javascript
<Image style={styles.avatar}
       source={require('image!placeholder')} 
/>
```

Did this break again since `0.4.0`?

Side note: This functionality appears to work fine on the iPhone 4S simulator...none of the others

**Comment by christopherdro** [comment]
@marcshilling Could you provide a example of your project.

I can confirm that I have this working with 0.4.4.

**Comment by marcshilling** [comment]
So in a new react-native init project, the exact same code from my other project works. I guess I'll go set some breakpoints in Image.ios.js...

**Comment by ssssssssssss** [comment]
I'm facing exactly the same issue with 0.4.2. The defaultSource prop doesn't work.

**Comment by ide** [comment]
Shoud be fixed with 0.10.0-rc.

**Comment by adrianha** [comment]
I still got the exact problem @ide,
here's my code:
<Image
style={styles.songThumbnail}
defaultSource={require('image!logo')}
source={{uri: rowData.cover}}
resizeMode='stretch'
/>
Image didnt change with network image..
I used ^0.12.0 react-native version..
Any solutions?

Thank you

**Comment by gudmundurmar** [comment]
@ide Having the same problem as @adrianha when I updated to 0.13.0. 
The default image will not go away when the other is loaded
