### ISSUE TITLE
How to access fonts from res/font folder?

### ISSUE THREAD

**Issue by rajsuvariya** [facebook/react-native#15170]
As to provide custom fonts in react native I need to keep my fonts at assets/fonts. But as per the new version of support library of android I have to keep fonts in res/font in order to apply it directly in xml. So I cannot keep my fonts at assets/fonts. Please update this in React native so that the res/font are directly accessible

**Comment by charpeni** [comment]
@facebook-github-bot stack-overflow

**Comment by hey99xx** [comment]
You can certainly load the font yourself and inject into [ReactFontManager](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/text/ReactFontManager.java).

Also I don't think having res/font font files and loading from xml is an absolute requirement. Most react-native apps simply don't deal with xml created views, so loading from assets is fine for most. I'd imagine this will not be a highly-requested feature, but it'd a nice addition nonetheless.

This method [`Resources#getFont(int)`](https://developer.android.com/reference/android/content/res/Resources.html#getFont(int)) is only introduced in SDK level 26 though, but RN currently is compiled against SDK level 23. So there would be some significant work before introducing an API for this. It'd be probably easier to have a custom native module in your own app to load the font file.

**Comment by hey99xx** [comment]
If someone wants to add label to the question (I can't) -- choose "Android" and "Feature Request".

**Comment by hramos** [comment]
Thanks for opening the issue! As it happens, we're using GitHub to track bugs in React Native. If you'd like to submit this as a feature request, please go ahead and create an entry on [Canny](https://reactnative.canny.io/feature-requests). It has a voting system and if the feature gets a good amount of votes, it will have a greater chance of being implemented by the community. Closing this now, thanks for understanding!

**Comment by rajsuvariya** [comment]
@hey99xx Yes, for applying fonts directly in xml using support library 26 we need to keep it inside res folder. Anyway I added feature request on Canny as asked by @hramos

**Comment by akoufatzis** [comment]
Hello. I am reopening this issue/ feature request again as the link for Canny does not seem to work. I tried to put my fonts in the Android res folder but that does not seem to work with React Native 0.51 . Unfortunately I must put my custom fonts both in the res folder and in the assets/fonts folder so I can use them in React Native and Android ( native) respectively. Is there any solution for this I might have overseen?

**Comment by hey99xx** [comment]
Correct link to Canny https://react-native.canny.io/feature-requests

What's the point of putting your custom fonts in res folder, just keep them in assets. Android's support for assets folder did not disappear just because now they made res folder the suggested location. If you want, create the Typeface from res yourself, and inject into RN via https://github.com/facebook/react-native/blob/0.50-stable/ReactAndroid/src/main/java/com/facebook/react/views/text/ReactFontManager.java#L83

**Comment by akoufatzis** [comment]
There would be no point and you would be right if I did not have to use the same fonts in the Android Java/XML code too. Now I am obligated to add the fonts two times, one in the assets/fonts folder and one in the res/font folder. Or I have to use your suggestion and add them programmatically.
