### ISSUE TITLE
undefined is not an object (evaluating 'component._instance')

### ISSUE THREAD

**Issue by levani** [facebook/react-native#15171]
### Is this a bug report?

Yes

### Have you read the Bugs section of the How to Contribute guide?

Yes

### Environment

1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.46.4
2. `node -v`: 6.11.1
3. `npm -v`: 5.3.0
4. `yarn --version`: 0.27.5
5. `react-devtools`: 2.5.0

Then, specify:

- Target Platform: Android

- Development Operating System: Windows 10

- Build tools: Android Studio

### Steps to Reproduce

(Write your steps here:)

1. create new empty app using `react-native init AwesomeProject`
2. install genymotion and launch this app.
3. install react-devtools and open it.
4. in emulator window click Menu button and select "Toggle Inspector"
5. Click on any text node from the sample app.

### Expected Behavior

Select the corresponding component in react devtools.

(Write what you thought would happen.)

### Actual Behavior

Getting the red screen with the following error:

> undefined is not an object (evaluating 'component._instance')
> getHostProps
>     D:\RN\AwesomeProject\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:2314:29
> getInspectorDataForViewTag
>     D:\RN\AwesomeProject\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:2334:259
> onTouchViewTag
>     D:\RN\AwesomeProject\node_modules\react-native\Libraries\Inspector\Inspector.js:175:44
> proxiedMethod
>     D:\RN\AwesomeProject\node_modules\react-proxy\modules\createPrototypeProxy.js:44:35
> <unknown>
>     D:\RN\AwesomeProject\node_modules\react-native\Libraries\Inspector\InspectorOverlay.js:51:34
> __invokeCallback
>     D:\RN\AwesomeProject\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:301:19
> <unknown>
>     D:\RN\AwesomeProject\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:118:28
> __guard
>     D:\RN\AwesomeProject\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:228:6
> invokeCallbackAndReturnFlushedQueue
>     D:\RN\AwesomeProject\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:117:17

This seem to happen only when I click the Text component. Clicking on View component for example works fine.

I tested this on android 6.0 and android 7.1 on nexus 5 device.

### Reproducible Demo

I'm experiencing this on a new project generated using `react-native init AwesomeProject`. No custom code added!

I made a small screen recording:

https://drive.google.com/file/d/0B7Ls870jI1CLeFRyaTRjWVV4YVU/view

**Comment by brentvatne** [comment]
sounds like a bug with react-devtools? can you repro it without react-devtools? if not, please create the issue on that repo instead

**Comment by phantom1299** [comment]
I have the exact same problem, this happend to me with and without react-devtools. Whenever I inspect  a Text, I get this error.

**Comment by letalumil** [comment]
Same issue here.

**Comment by klinkov** [comment]
same issue

**Comment by jslz** [comment]
I also am running into this, also on Android (never iOS yet).
react-native-cli: 2.0.1
react-native: 0.46.4
mac os x 10.12.6

(I haven't noticed a way to get the inspector overlay to let me click on things underneath it? Afaict I have to click on something else visible such that the inspector overlay then moves to the top of the screen, to be able to click on something that was underneath it? I am stuck because the other things are text fields.)

**Comment by Kuluum** [comment]
Same

**Comment by levani** [comment]
I have reported the same issue on `react-devtools` repository as well. No 'official' response so far.

https://github.com/facebook/react-devtools/issues/859
