### ISSUE TITLE
[Inspector] Render inspector UI over status bar

### ISSUE THREAD

**Issue by brentvatne** [facebook/react-native#1518]
![](http://url.brentvatne.ca/128yc.png)

I don't think there is a lot of value in keeping the status bar around when the inspector is open, what do you think about saving the status bar state before opening and hiding it when the user closes the inspector?

**Comment by ide** [comment]
We should render the inspector UI on top of the status bar (window level + 1).

**Comment by brentvatne** [comment]
@ide - even better

**Comment by browniefed** [comment]
@brentvatne this might seem like a good first task?

**Comment by brentvatne** [comment]
Looks like this is done already :smile:

![](http://url.brentvatne.ca/1gHrI.png)
