### ISSUE TITLE
ScrollView Example Not Working

### ISSUE THREAD

**Issue by dbnex14** [facebook/react-native#15187]
### Is this a bug report?

YES

### Have you read the Bugs section of the How to Contribute guide?

(Write your answer here.)

### Environment

1. `react-native -v`: 0.45.1
2. `node -v`:6.11.1
3. `npm -v`:3.10.10
4. `yarn --version`:

Then, specify:

- Target Platform:I dont know, I just started learning about react-native yesterday, created CRNA according to your Get Started steps and tried ScrollView by connecting my Android phone via USB cable to my laptop and enabling Development options.  So, I guess this means I am targeting Android

- Development Operating System:MacOS

- Build tools:Atom editor and npm

### Steps to Reproduce

(Write your steps here:)
1. Create CRNA by issuing in Terminal
   npm install -g create-react-native-app
   
 
2. Open generated AwesomeProject in Atom editor
  
3. Copy ScrollView code from link   into the generated App.js by replacing entirely the original content in this file
import React, { Component } from 'react';
import { AppRegistry, ScrollView, Image, Text } from 'react-native';

export default class IScrolledDownAndWhatHappenedNextShockedMe extends Component {
  render() {
      return (
        <ScrollView>
          <Text style={{fontSize:96}}>Scroll me plz</Text>
          <Image source={require('./img/favicon.png')} />
          <Image source={require('./img/favicon.png')} />
          <Image source={require('./img/favicon.png')} />
          <Image source={require('./img/favicon.png')} />
          <Image source={require('./img/favicon.png')} />
          <Text style={{fontSize:96}}>If you like</Text>
          <Image source={require('./img/favicon.png')} />
          <Image source={require('./img/favicon.png')} />
          <Image source={require('./img/favicon.png')} />
          <Image source={require('./img/favicon.png')} />
          <Image source={require('./img/favicon.png')} />
          <Text style={{fontSize:96}}>Scrolling down</Text>
          <Image source={require('./img/favicon.png')} />
          <Image source={require('./img/favicon.png')} />
          <Image source={require('./img/favicon.png')} />
          <Image source={require('./img/favicon.png')} />
          <Image source={require('./img/favicon.png')} />
          <Text style={{fontSize:96}}>What's the best</Text>
          <Image source={require('./img/favicon.png')} />
          <Image source={require('./img/favicon.png')} />
          <Image source={require('./img/favicon.png')} />
          <Image source={require('./img/favicon.png')} />
          <Image source={require('./img/favicon.png')} />
          <Text style={{fontSize:96}}>Framework around?</Text>
          <Image source={require('./img/favicon.png')} />
          <Image source={require('./img/favicon.png')} />
          <Image source={require('./img/favicon.png')} />
          <Image source={require('./img/favicon.png')} />
          <Image source={require('./img/favicon.png')} />
          <Text style={{fontSize:80}}>React Native</Text>
        </ScrollView>
    );
  }
}

// skip these lines if using Create React Native App
AppRegistry.registerComponent(
  'AwesomeProject',
  () => IScrolledDownAndWhatHappenedNextShockedMe);
  
4. Save

5. In terminal, enter npm start

6. This starts packager and generates QR code

7. on Android device, open Expo and scan generated QR code

8. The AwesomeProject starts and shows "The development server returned response error code: 500..."
The screenshot is provided

9. The terminal shows "10:13:14 PM: Failed building JavaScript bundle"

10. Snack shows
<div data-snack-id="H1ZDDL4L-" data-snack-platform="android" data-snack-preview="true" data-snack-theme="light" style="overflow:hidden;background:#fafafa;border:1px solid rgba(0,0,0,.16);border-radius:4px;height:505px;width:100%"></div>
<script async src="https://snack.expo.io/embed.js"></script>

### Expected Behavior

As per http://facebook.github.io/react-native/docs/using-a-scrollview.html, it should show scrollbar with images and text

### Actual Behavior

(Write what happened. Add screenshots!)
Seriously?  Steps to reproduce are above.  Screenshot is attached.
Snack shows following errors
Device: (128:72) Trying to import unknown module './img/favicon.png'

ESLint: (10:26) 'require' is not defined. (no-undef)

ESLint: (11:26) 'require' is not defined. (no-undef)

ESLint: (12:26) 'require' is not defined. (no-undef)

ESLint: (13:26) 'require' is not defined. (no-undef)

ESLint: (14:26) 'require' is not defined. (no-undef)

ESLint: (16:26) 'require' is not defined. (no-undef)

ESLint: (17:26) 'require' is not defined. (no-undef)

ESLint: (18:26) 'require' is not defined. (no-undef)

ESLint: (19:26) 'require' is not defined. (no-undef)

ESLint: (20:26) 'require' is not defined. (no-undef)

ESLint: (22:26) 'require' is not defined. (no-undef)

ESLint: (23:26) 'require' is not defined. (no-undef)

ESLint: (24:26) 'require' is not defined. (no-undef)

ESLint: (25:26) 'require' is not defined. (no-undef)

ESLint: (26:26) 'require' is not defined. (no-undef)

ESLint: (28:26) 'require' is not defined. (no-undef)

ESLint: (29:26) 'require' is not defined. (no-undef)

ESLint: (30:26) 'require' is not defined. (no-undef)

ESLint: (31:26) 'require' is not defined. (no-undef)

ESLint: (32:26) 'require' is not defined. (no-undef)

ESLint: (34:26) 'require' is not defined. (no-undef)

ESLint: (35:26) 'require' is not defined. (no-undef)

ESLint: (36:26) 'require' is not defined. (no-undef)

ESLint: (37:26) 'require' is not defined. (no-undef)

ESLint: (38:26) 'require' is not defined. (no-undef)

Dark theme
Components
Preview
Platform
SDK
<img width="345" alt="image" src="https://user-images.githubusercontent.com/8755679/28557478-8dcf96e6-70c1-11e7-9a6a-0b1df4d7435c.png">

<img width="578" alt="image" src="https://user-images.githubusercontent.com/8755679/28557541-e4f7aa12-70c1-11e7-8e46-016e54837013.png">

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)
<div data-snack-id="H1ZDDL4L-" data-snack-platform="ios" data-snack-preview="true" data-snack-theme="light" style="overflow:hidden;background:#fafafa;border:1px solid rgba(0,0,0,.16);border-radius:4px;height:505px;width:100%"></div>
<script async src="https://snack.expo.io/embed.js"></script>

THIS IS VERY EASY TO REPRODUCE.  JUST FOLLOW THE STEPS ABOVE.

**Comment by hramos** [comment]
You need to remove the last line in your copy-pasted code, per the comment:

```
// skip these lines if using Create React Native App
AppRegistry.registerComponent(
'AwesomeProject',
() => IScrolledDownAndWhatHappenedNextShockedMe);
```

I'm going to close this as it does not appear to be an issue with React Native itself. If you believe there's a bug that needs attention, please add more information and let us know. I would also like to kindly point you to https://code.facebook.com/codeofconduct if you haven't read it yet. We want this to be a welcoming and considerate community.

**Comment by dbnex14** [comment]
@hramos Removing that line is working; however, it behaves inconsistently with other examples that are before the ScrollView example such as TextInput example which works with or without the AppRegister line

**Comment by hramos** [comment]
Yes, you do need to copy the image over into a `img/` folder. I'll see how we can make that clearer in the example. Thanks.

**Comment by dbnex14** [comment]
Please note that img folder does not exist in CRNA.  Both, img folder and
image in it must be added to AwesomeProject created by CRNA.
much appreciated

**Comment by hramos** [comment]
That's very much intentional. The example shows how you might display a hypothetical image in a img directory within your project.
