### ISSUE TITLE
[FlatList] scrollToOffset always scrolls to top

### ISSUE THREAD

**Issue by NSLS** [facebook/react-native#15197]
### Is this a bug report?

Yes

### Have you read the Bugs section of the How to Contribute guide?

Yes

### Environment

1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.46.4
2. `node -v`:
v8.1.3
3. `npm -v`:
5.3.0

Then, specify:

- Target Platform: iOS

- Development Operating System: OS X Sierra

- Build tools: Xcode

### Steps to Reproduce

1. Create a normal FlatList with data and header
2. Add a ref to `<FlatList />`, in order to have access to scrollToOffset function
3. Add an onScrollEndDrag callback, which listens to scroll end, then gets the final scroll y offset, evaluates it and calls scrollToOffset() function with y > 0

### Expected Behavior

Content of the FlatList should be scrolled to provided y position

### Actual Behavior

Content of the FlatList is always scrolled to y = 0

### Reproducible Demo

Try to scroll to the header and then let go. this.onScrollEnd should scroll back to y = 100, but instead the content is scrolled to y = 0

https://snack.expo.io/Sy9NcgrLb

**Comment by DriesVS** [comment]
It's not a bug - you need to use the offset key, not y.
FlatList infers it to either x or y based on the horizontal prop.

Fix based on your example:
```
this.flatList.scrollToOffset({
   offset: headerHeight,
   animated: true
})
```
