### ISSUE TITLE
__DEV__ is false, cant set it to true anymore

### ISSUE THREAD

**Issue by basvdheijden** [facebook/react-native#15191]
### Is this a bug report?

Yes, I think so. All over the sudden my __DEV__ variable has been set to false. If I run ``react-native run android`` it boots up with `` __DEV__ === false``. and I can't figure out how to set it to __DEV__ = true again. Any clues?

### Environment

1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.45.1

2. `node -v`:
v7.10.0

3. `npm -v`:
4.2.0

4. `yarn --version`:

0.19.1
Then, specify:

- Target Platform: Android

- Development Operating System: MacOS
- Build tools: Android studio.

**Comment by padil** [comment]
Go in terminal

1- type it "adb shell input keyevent 82"
2- in device -> Dev Settings 
3- Js Dev Mode -> set true in checkbox

**Comment by basvdheijden** [comment]
Thanks a ton.
