### ISSUE TITLE
RN 0.46 Packager fails to resolve Module XMLHttpRequest

### ISSUE THREAD

**Issue by Phrosh** [facebook/react-native#15195]
I just upgraded from 0.44 to 0.46 (via the Git-Upgrade tool) and whenever I start the packager, it runs but fails with output:

```
Loading dependency graph, done.
Bundling `index.android.js`  69.5% (1416/1698), failed.
error: bundling failed: "Unable to resolve module `XMLHttpRequest` from `C:\\Git\\[project name]\\node_modules\\react-native\\Libraries\\Core\\InitializeCore.js`: Module does not exist in the module map or in these directories:\n  C:\\Git\\[project name]\\node_modules\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`."
```

I tried everything inside this message, but no luck. This also happens with 0.47. Of course I also tried `npm install xmlhttprequest`

### Environment

1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.46.4
2. `node -v`:
v7.10.0
3. `npm -v`:
5.3.0
4. `yarn --version`:

- Target Platform: android

- Development Operating System: Windows 10 x64

- Build tools:

### Steps to Reproduce

maybe just do what the above says...

### Expected Behavior

A working package

### Actual Behavior

No working package and the above error message

**Comment by thatjuan** [comment]
Try deleting your `node_modules` folder altogether, then running `npm install`. 

After that, start your packager with `npm start --reset-cache`

**Comment by Phrosh** [comment]
Thx,
did that already, with no luck :(
(I used `npm start -- --reset-cache`, I don't think there is any difference, right?)

**Comment by sibelius** [comment]
this is happening on RN48 as well

**Comment by KalebPortillo** [comment]
+1

**Comment by raspasov** [comment]
This is happening to me as well, on production build only. 
I can't build for production at all at the moment.

**Comment by sibelius** [comment]
Solved on 48

**Comment by raspasov** [comment]
@sibelius how did you solve it? I'm on RN48 and I get the same error when building for production:
Unable to resolve module `xmlhttprequest`

**Comment by sibelius** [comment]
Try to use

yarn why xmlhttprequest 

For me the error was because of d3

**Comment by Eddie104** [comment]
@sibelius how did you solve it?

**Comment by sibelius** [comment]
@Eddie104 check this https://github.com/facebook/react-native/issues/15195#issuecomment-330006886

**Comment by Eddie104** [comment]
@sibelius thanks! after I removed d3 with "yarn remove d3" then added d3 with "yarn add d3", it works!!!That's amazing!

**Comment by stephenlaughton** [comment]
@Eddie104 I am running into this issue as well and `yarn remove d3` followed by `yarn add d3` is not solving my issue. Did you do anything else before or after these steps?

**Comment by Eddie104** [comment]
@stephenlaughton I modified the version number of d3 from "^4.10.0" to "4.10.0"
