### ISSUE TITLE
react native app restarted when changing permission through settings

### ISSUE THREAD

**Issue by pandiaraj44** [facebook/react-native#15207]
### Is this a bug report?

Yes

### Have you read the Bugs section of the How to Contribute guide?

Yes

### Environment

1. `react-native -v`: react-native-cli: 1.0.0, react-native: 0.35.0
2. `node -v`: v6.6.0
3. `npm -v`: 3.10.3
4. `yarn --version`: --NA--

Then, specify:

- Target Platform: Android(>=M) and Ios

- Development Operating System: Ubuntu 14.04LTS, OS X 10.10: Yosemite

- Build tools: Default

### Steps to Reproduce

1. Take a new/existing react native project. Please make sure it have some two pages[Page 1(initial), Page 2].
2.  Add any permissions(like Camera, Storage,.....) to AndroidManifest.xml(For Android) & info.plist(For Ios) file. 
3. Run the app on emulator/simulator/a real device. 
4. At initial, Page 1 will be presented to the user.
5. Navigate to Page 2.
6. Minimize the app and go to settings and change the app permissions(Camera, Stroage....).
7. Resume the app. It will open the Page1.

### Expected Behavior

App needs to be in Page2.

### Actual Behavior

App gets restarted and initial page will be displayed.

### Reproducible Demo

https://github.com/pandiaraj44/ReactNativePermissionChangeBug

Video Ref: https://drive.google.com/file/d/0B9gIc_qkvdRIbm4xR3U2R292OHc

### Actual Description
I have a react native app. Which is working fine in both ios & android but if change any permissions(Camera, Storage) through settings option then app get restarted.

For Example, If I am on the home-screen and I had changed the permission then the app will get restarted and takes me to the login screen.

Are there any options to maintain current app state(both ios and android)?

**Comment by hramos** [comment]
Any chance you can provide an up to date repro? The link you provided is for an older version of RN, o.35.

**Comment by pandiaraj44** [comment]
@hramos 

I will create the new project and will share the link. 

FYI...
I think for these kind of bug we can take react native default awesome project itself.

**Comment by pandiaraj44** [comment]
@hramos 

Reproducible Demo Link updated.
https://github.com/pandiaraj44/ReactNativePermissionChangeBug

**Comment by pandiaraj44** [comment]
Hi, @hramos 

If possible, Please add tags/assignees to this issue, May be it will be visible to other contributors and they might help.

**Comment by pandiaraj44** [comment]
Hi @hramos, Is there any updates?

**Comment by hramos** [comment]
Sorry, I don't have anything to add here. Let me know if you open a PR with a fix for this.

**Comment by victorbadila** [comment]
Hi, I am experiencing this issue as well, same scenario though it also appears in iOS apps. It was there in iOS 10 and it is still in iOS 11 with RN upgraded to the latest version. @hramos should we also attach the `iOS` label to the issue?

**Comment by victorbadila** [comment]
Someone please reopen this, it is still an issue and it is blocking for many of us. Also would be nice to add the iOS label as well, not sure how to do that though.
