### ISSUE TITLE
'$FlowFixMe' Appearances throughout Docs

### ISSUE THREAD

**Issue by jeff-da** [facebook/react-native#15218]
### Is this a bug report?

Yes

### Have you read the Bugs section of the How to Contribute guide?

Yes

### Environment

- Target Platform: Web (tested on Chrome, Safari)

- Development Operating System: MacOS

### Steps to Reproduce

Visit the following sites on the React Native docs.
https://facebook.github.io/react-native/docs/tabbarios.html
https://facebook.github.io/react-native/docs/picker.html
https://facebook.github.io/react-native/docs/statusbar.html

### Expected Behavior

It's important to keep the state of the docs updated, as the docs are the main way that most users look to when figuring how to get their application working. A parameter was expected (such as a boolean or color field).

### Actual Behavior

The various appearances of $FlowFixMe happen because of the way the docs are generated. While the generation works most of the time, these errors prevent any information from being passed and make the components much harder to use, as an assumption must be made by looking at the codebase itself to figure out what components to pass.

**Comment by hramos** [comment]
Yes, this is something that needs to be fixed. The `$FlowFixMe` tag is used to suppress errors when Flow type checks the code. Ideally, someone will come back to the code and do the work to use the correct type here, but it doesn't always come to happen that way.

I'll tag this as a `Good First Task`, as anyone interested in learning about Flow may benefit from completing this task.

**Comment by prasanthp96** [comment]
hello @hramos, @jeff-da 
I am interested to fix this ! can you guide me to fix this ?

**Comment by meggamind** [comment]
Is this still an issue ? Can I pick this up ?

**Comment by hramos** [comment]
I don't think it's an issue any more, now that the docs have been flattened out into markdown.
