### ISSUE TITLE
Failed building JavaScript bundle

### ISSUE THREAD

**Issue by athahabee** [facebook/react-native#15219]
### Is this a bug report?

Yes

### Have you read the Bugs section of the How to Contribute guide?

Yes

### Environment

1. `react-native -v`: react-native-cli: 2.0.1, react-native: 0.46.4
2. `node -v`: V6.11.1
3. `npm -v`: 3.10.10
4. `yarn --version`:

Then, specify:

- Target Platform: Android

- Development Operating System: Microsoft Windows [Version 10.0.15063]

- Build tools:

### Steps to Reproduce

The issue is straight forward for me. I've tried many times to re-install everything, and still getting the same error. I'm following the official getting started guide step by step. Here is what I did:
Install Node.js for windows "node-v6.11.1-x64"
(I've tried to put WatchMan with suitable PATH variable)
Open cmd with admin
> npm install -g create-react-native-app
> e:
> cd ReactNative
> create-react-native-app ReactDemo
> cd ReactDemo
> np start

### Expected Behavior

Application should start without any error from inside expo for Android

### Actual Behavior

Then when try to run the app in expo I get this error:

```
The development server returned response error code: 404

URL: http://192.168.170.1:19001/node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=android&dev=true&strict=false&minify=false&hot=false&assetPlugin=expo/tools/hashAssetFiles

Body:
{"message":"Cannot find entry file node_modules/react-native-scripts/build/bin/crna-entry.js in any of the roots: [\"E:\\\\ReactNative\\\\ReactDemo\"]","name":"NotFoundError","type":"NotFoundError","status":404,"errors":[{}]}
processBundleResult
    BundleDownloader.java:172
access$100
    BundleDownloader.java:38
execute
    BundleDownloader.java:108
emitChunk
    MultipartStreamReader.java:69
readAllParts
    MultipartStreamReader.java:116
onResponse
    BundleDownloader.java:96
execute
    RealCall.java:126
run
    NamedRunnable.java:32
runWorker
    ThreadPoolExecutor.java:1113
run
    ThreadPoolExecutor.java:588
run
    Thread.java:818

```

And in the console, I get "Failed building JavaScript bundle" error message
Snaps: 
https://pasteboard.co/GCN6m2B.png
https://pasteboard.co/GCNi6ZF.png

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by vzhen** [comment]
Getting same error, after android client expo update i no longer can yarn start.

**Comment by athahabee** [comment]
Finally solved. I forgot that I had WatchMan in my System32 folder, so after 
1- removing watchman
2- Running the console as current user rather than admin
I've made fresh install, and was able finally to get my app running.
