### ISSUE TITLE
[RN 0.46.4]Error while updating property 'transform' in shadow node of type: ARTShape

### ISSUE THREAD

**Issue by younatics** [facebook/react-native#15223]
### Is this a bug report?

Yes I get this error. while render react native again and again, it throws this error.

### Have you read the Bugs section of the How to Contribute guide?

YES

### Environment

1. `react-native -v`: 0.46.4
2. `node -v`:
3. `npm -v`: 
4. `yarn --version`: 0.24.6

Then, specify:

Android get this error.

- Target Platform:

- Development Operating System:

- Build tools:

### Steps to Reproduce
click rn view and back. and reenter

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by hramos** [comment]
Thanks for opening the issue! It does not appear like a community member will be able to reliably reproduce this issue. As it happens, we need a concrete set of steps that can demonstrably reproduce the issue as this will allow your fellow community members to validate a fix. We'll close the issue for now, but feel free to submit a new issue once you're able to reliably reproduce the issue locally. Thanks for your understanding!
