### ISSUE TITLE
[0.46.4] Can not install the Realm.

### ISSUE THREAD

**Issue by guoliang1206** [facebook/react-native#15222]
### Is this a bug report?

I guess yes.

### Environment

1. `react-native -v`:0.46.4
2. `node -v`:7.9.0
3. `npm -v`:5.3.0
4. `yarn --version`:0.22.0
5.  Mac OS

Operation steps:
1.upgrade react-native from 0.44.0 to 0.46.4
2.Create a new project with `react-native init`
3.install the realm with `npm install --save realm` , execute in the dir of node_modules and dir of project root both , same error.
4.stuck in  node-pre-gyp install --fallback-to-build

### Expected Behavior
Realm should  be install automatically , at least in RN 0.44.0
### Actual Behavior
Can not install the Realm, and the terminal will stuck.
![realm-issue](https://user-images.githubusercontent.com/12846676/28768018-adcc5c1c-7608-11e7-9c9b-7937b59034b0.png)
at the redline, the process  will be suspended and can't finish unless I have Ctrl + C

**Comment by hramos** [comment]
Hmm, it seems like this report is missing some crucial details. Can you edit your post and make sure it fills the template in its entirety?

**Comment by guoliang1206** [comment]
@hramos  I am not sure which informations that you need. The screenshots is what problems I faced. The process `npm install --save realm` will stuck in terminal.

**Comment by hramos** [comment]
The screenshot doesn't match your repro steps, or it has additional, probably unrelated steps. It's not clear what someone should follow in order to reproduce the issue.

**Comment by hey99xx** [comment]
Besides screenshot being hard to understand, I think Realm related issue should be reported to Realm's Github repository, and not here.

**Comment by guoliang1206** [comment]
@hey99xx  but this is the all informations I faced and saw. I have upgrade the RN, and want to install the realm by npm. and the issue happened.
