### ISSUE TITLE
Changes in index.android.js are not being built automatically after I saved then neither when I restart the App. BUG

### ISSUE THREAD

**Issue by MichaelSzer** [facebook/react-native#15226]
### Is this a bug report?

Yes

### Have you read the Bugs section of the How to Contribute guide?

Yes

### Environment

1. `react-native -v`: react-native-cli: 2.0.1, react-native: 0.46.4
2. `node -v`: v7.10.1
3. `npm -v`: 4.2.0
4. `yarn --version`:

Then, specify:

- Target Platform: Android

- Development Operating System: Windows 10

- Build tools: Android Studio, I only modified the native code to use the react-native-firebase library and the 'buildToolsVersion' to "21.1.2" and delete and reinstalled 'watchman'. Project was created using 'react-native init [name]'.

### Steps to Reproduce

(Write your steps here:)

1. Open the terminal.
2. Go to App directory and run: 'react-native run-android'
3.

### Expected Behavior

When you run the app you should see only text.

### Actual Behavior

(Write what happened. Add screenshots!)

When you run the app you should see a custom component (a login layout). Changes in index.android.js are not being built automatically after I saved then neither when I restart the App. (I am not sure what kind of screenshots I could show on this issue, please let me know if you are looking a for a specific screenshot) 

### Reproducible Demo

https://www.dropbox.com/s/b0isif6yoq8u816/altoque.zip?dl=0

**Comment by rajsuvariya** [comment]
Instead of uploading entire project just add the important files on dropbox

**Comment by MichaelSzer** [comment]
I don't know what is the bug, I deleted the only thing I was sure wasn't part of it, the components.

**Comment by GaidamakUA** [comment]
I have same issue. I always get "bundling failed: "Cannot find entry file index.android.js in any of the roots:"projectname"". And I really don't have index.android.js in my project directory. I don't know what the issue is. And it's really frustrating. I have the same version as OP.

**Comment by hramos** [comment]
After looking at this, I don't think there's a minimal enough repro for this issue. Due to lack of activity here, it does not seem like it is something affecting other users.
