### ISSUE TITLE
error in installing react.js

### ISSUE THREAD

**Issue by dimplegarg** [facebook/react-native#15244]
npm ERR! sha1-z09Ze4ZNZcikkrLqvp1wbIecOIs= integrity checksum failed when using sha1: wanted sha1-z09Ze4ZNZcikkrLqvp1wbIecOIs= but got sha1-EMJxnw9sA1o2MpZQXY
lxb94W+wo=. (149690 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ADMIN\AppData\Roaming\npm-cache\_logs\2017-07-28T04_18_38_757Z-debug.log

**Comment by rajsuvariya** [comment]
Can you provide the log from C:\Users\ADMIN\AppData\Roaming\npm-cache_logs\2017-07-28T04_18_38_757Z-debug.log ??

**Comment by dimplegarg** [comment]
Thanks Raj Suvariya,
for contributing but i resolved the problem ... now i have installed the react..

**Comment by rajsuvariya** [comment]
@dimplegarg Please close the issue

**Comment by rajsuvariya** [comment]
@facebook-github-bot close this issue

**Comment by rajsuvariya** [comment]
@facebook-github-bot close
