### ISSUE TITLE
[Question] How to add Android Back Handler for a perticular screen?

### ISSUE THREAD

**Issue by rajsuvariya** [facebook/react-native#15248]
I have three screens MyVault, Add Doc and Add Repo. From Myvault there is one button add new doc by clicking on that Add Doc will open. Now in Add doc if user presses Bank button then I want a confirmation pop up. I have one button inside add doc screen which opens Add repo screen where user can select one repo and when they click add that screen will be poped and add doc screen will be refreshed with the repo data. If I add a listener in ComponentDidMount and then remove it in ComponentWillUnmount then the issue is that even when I press back on Add repo then also the popup comes. I don't want popup on any other screens, I just want it on Add doc.

**Comment by Dani93380** [comment]
How do you handle your navigation betwen scene? Are you using react-navigation or router-flux ?

**Comment by rajsuvariya** [comment]
@Dani93380 I am using react-native-router-flux v4

**Comment by Dani93380** [comment]
You should have 3 class for your 3 components . If you add the listener inside the AddDoc class only and remove it on componentWillUnmount it should work.

**Comment by rajsuvariya** [comment]
Actually, I have done the same but what happens is this event listener if not removed will be there on all the screens.
I have added this listener on Add doc and works fine when I press back. But now when I click on add repo button it will open  Select Repo screen where a user can select repo and come back to add doc. So when I open the Select Repo componentWillUnmount won't be called, so the listener will be there and will open popup when user press back on Select Repo screen

**Comment by Dani93380** [comment]
If you are using redux or something similar , store your current scene in the store and only call your back function if currentScene=="AddDoc"

**Comment by rajsuvariya** [comment]
No I am not using redux. But I think react native should provide such options

**Comment by Dani93380** [comment]
https://facebook.github.io/react-native/docs/more-resources.html#popular-libraries ^^

**Comment by rajsuvariya** [comment]
Never mind figured out that react-native-router-flux has onEnter and onExit callbacks for every scene. So I added the event listener in onEnter and removed it in onExit and that fixed my issue.

**Comment by rajsuvariya** [comment]
BTW @Dani93380 I know about Redux but don't want to use in my app :D
