### ISSUE TITLE
 UnableToResolveError: Unable to resolve module ActivityIndicator

### ISSUE THREAD

**Issue by ferminmoli** [facebook/react-native#15256]
error: bundling: UnableToResolveError: Unable to resolve module `ActivityIndicator` from `C:\Projects\node_modules\react-native\Libraries\react-native\react-native-implementation.js`: Module does not exist in the module map or in these directories:
  C:\Projects\node_modules\react-native\node_modules
,   C:\Projects\node_modules

1. `react-native -v`: 0.44.3
2. `node -v`: 6.10
3. `npm -v`: 3.10.10

- Target Platform: Android
- Development Operating System: Windows 10
- Build tools: Android SDK 23

Step to reproduce:
1 - react-native run-android

NOTE: The following steps did not work for me

  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.
  4. Clone repository from the scratch and install modules again

**Comment by ferminmoli** [comment]
Installing yarn fixed my issue! The I ran yarn upgrade

**Comment by saaksshi** [comment]
I've same kind of problem.

error: bundling failed: Error: Unable to resolve module `SegmentedControlIOS` from `****/node_modules/react-native/Libraries/react-native/react-native-implementation.js`: Module `SegmentedControlIOS` does not exist in the Haste module map

node - v10.1.0
npm -v6.1.0
react- 16.4.0
react-native - 0.55.4

This happened when I upgraded react-native from .45 to .55.

**Comment by cgonzalezp91** [comment]
@saaksshi did you find a solution?
I did the same thinks as you and all of other solutions in every bug tipic that RN have about this problem and anything worked :(

**Comment by saaksshi** [comment]
@cgonzalezp91 unfortunately I didn't find any solution and instead of upgrading I preferred creating new project as I literally wasted 1 week over this. but feel free to post solution if you find anything.
