### ISSUE TITLE
Module AppRegistry is not a registered callable module (calling runApplication)

### ISSUE THREAD

**Issue by xiaoyongchen** [facebook/react-native#15250]
### Is this a bug report?

(write your answer here)

### Have you read the Bugs section of the How to Contribute guide?

(Write your answer here.)

### Environment

1. `react-native -v`:
2. `node -v`:
3. `npm -v`:
4. `yarn --version`:

Then, specify:

- Target Platform:

- Development Operating System:

- Build tools:

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by xiaoyongchen** [comment]
React-native Upgrade lead  Module AppRegistry is not a registered callable module (calling runApplication)

**Comment by BenBenz** [comment]
I have the same problem

**Comment by BenBenz** [comment]
Any update ?

**Comment by hallij145** [comment]
same issue here, crashes android at startup

**Comment by hramos** [comment]
I recommend opening a new issue that follows the template.

**Comment by xiaoyongchen** [comment]
@hramos hi，How did you solve the problem?

**Comment by GutteApps** [comment]
same issue here
![screenshot_1510532396](https://user-images.githubusercontent.com/4751301/32705137-36fc953a-c819-11e7-8cec-6e13e8c18172.png)

**Comment by santamaria7** [comment]
Same problem here. I wonder why this issue has been closed without any solution. We still have this problem, whether this issue follows the template or not. By the way I am sure there are many other people with the same problem.

**Comment by Ambujesh** [comment]
I am also getting the same problem. Module AppRegistry is not a registered callable module (calling unmountApplicationComponentAtRootTag) . My debug android apk runs well but when i try to run release build then only i get this error??

**Comment by sinhpn92** [comment]
Did you resolve it? @Ambujesh
