### ISSUE TITLE
How to render nested firebase data with listview in react-native

### ISSUE THREAD

**Issue by MuhammetYavuzCayli** [facebook/react-native#15259]
### How to render nested firebase data with listview in react-native

Hi everyone!  I am developing a beginner project using Firebase and React-Native. I have a problem and
### I want you to give me some advice or code tricks on this problem 👍 
This is my [PageCode ](https://github.com/MuhammetYavuzCayli/firebaseexample/blob/master/discover.js) 
 this is my [firebase data](https://github.com/MuhammetYavuzCayli/firebaseexample/blob/master/firstapp-a479a-export%20(2).json)
this is my   [renderRow(rowData)](https://github.com/MuhammetYavuzCayli/firebaseexample/blob/master/discover.js#L87)
this is Fill [ListViewDatasource](https://github.com/MuhammetYavuzCayli/firebaseexample/blob/master/discover.js#L48)

### So i cannot reach `RandomFirebaseKey`{...`Post`{`PostText` or `postUri`},...} in `renderRow(rowData)` and my `PostTexts` and `images` not showing :/ screenshot like that: 
![screenshot_20170728-141836](https://user-images.githubusercontent.com/29316755/28718853-64bd5f08-73b0-11e7-89bc-4abe07afdfd0.png)

### İ already try `rowData.Post.PostText` or `rowData.Post.postUri` and throw an error like that:
![screenshot_20170728-143546](https://user-images.githubusercontent.com/29316755/28718999-fee4ad0c-73b0-11e7-9b86-3496b92b08a7.png)

### Help :D

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.

**Comment by MuhammetYavuzCayli** [comment]
@hramos yeah i asked [StackOverflow](https://stackoverflow.com/questions/45362654/how-to-render-nested-firebase-data-in-listview-with-react-native) and i can not the solution :/

**Comment by hramos** [comment]
It looks like you've had several people try to help over there, which is good. We don't want to duplicate effort, plus we're limiting issues to actual bugs in RN. Thanks for understanding.

**Comment by MuhammetYavuzCayli** [comment]
Thank you for your answer :) if you know the answers i can close that StackOverflow question :D Of course 
I understand what you want to tell  :)
