### ISSUE TITLE
React Native breaks .NET Core command line tools

### ISSUE THREAD

**Issue by Kikimora** [facebook/react-native#15255]
I don't really use React Native too much and does not have time to do proper investigation, sorry about sketchy bug report. Hope it sill be useful.

I suddenly noticed that my .NET Core build tools start producing React.dll instead of proper assemblies. Quick investigation showed that React Native has put tons of environment variables like 

FULL_PRODUCT_NAME=libReact.a
PROJECT_NAME=React
PRODUCT_MODULE_NAME=React

They seems to interfere with .NET Core CLI and make them produce React.dll instead of specified output.

**Comment by hramos** [comment]
Thanks for opening the issue! It does not appear like a community member will be able to reliably reproduce this issue. This may be for several reasons; perhaps it affects a particular app but a minimal repro has not been provided, or the issue may be sporadic. As it happens, we need a concrete set of steps that can demonstrably reproduce the issue as this will allow your fellow community members to validate a fix. We'll close the issue for now, but feel free to submit a new issue once you're able to reliably reproduce the issue locally. Thanks for your understanding!
