### ISSUE TITLE
[Question] How to call postMessage() and injectedJavaScript() in the native side?

### ISSUE THREAD

**Issue by gygl09** [facebook/react-native#15267]
### Is this a bug report?
No
### Environment
1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.46.4
2. `node -v`: v6.11.1
3. `npm -v`: 3.10.10

- Target Platform: Android 18,19,23
- Development Operating System: Ubuntu 14.04
- Build tools: Android Studio

Can I know how to call postMessage() or injectedJavaScript() in the native side? In the following code, handleMessage can be called. But postMessage() is never hit, since this.webview was always null. 
So how to initialize this.webview?

```
export default class MyWeb extends Component {
        handleMessage(e) {
                console.log("[native] receive a msg" + e.nativeEvent.data);
                if (this.webview) {
                        this.webview.postMessage("[native] received the message");
                }

        }

        render() {
                return (
                        <WebView
                           javaScriptEnabled
                           ref={webview => { this.webview = webview; }}
                           source={{uri: 'xxx'}}
                           onMessage={this.handleMessage}
                           style={{marginTop: 40}}
                         />
                 );
        }
}
```

**Comment by liquidprogrammer** [comment]
Hi @gygl09, when your **handleMessage** function is called from WebView, context **this** is not a WebView instance, you need to bind **handleMessage** function to **this**:

```javascript
export default class MyWeb extends Component {

    constructor(props) {
        super(props)
        this.handleMessage = this.handleMessage.bind(this) // <----- add this line       
    }

    handleMessage(e) {
        ...
    }
}
```

**Comment by gygl09** [comment]
Hi @liquidprogrammer, thanks a lot! It works.
