### ISSUE TITLE
[Question]node_modules/react-native/packager/react-native-xcode.sh:No such file or directory

### ISSUE THREAD

**Issue by mrainezty** [facebook/react-native#15268]
### Is this a bug report?

no

### Have you read the Bugs section of the How to Contribute guide?

yes

### Environment

1. `react-native -v`:react-native: 0.46.4
2. `node -v`:v8.1.0
3. `npm -v`:none
4. `yarn --version`:0.24.6

- Target Platform:iOS

- Development Operating System:MacOs

- Build tools:Xcode

### Steps to Reproduce

1.open the xcode
2.click the run button

then the xcode report that:
Users/zty/Library/Developer/Xcode/DerivedData/iMetric-efzaxfdglbsyddhglsclbqijircq/Build/Intermediates/iMetric.build/Release-iphonesimulator/iMetric.build/Script-00DD1BFF1BD5951E006B06BC.sh: line 3: ../node_modules/react-native/packager/react-native-xcode.sh: No such file or directory

**Comment by hose314** [comment]
https://github.com/facebook/react-native/releases/tag/v0.46.4

**Comment by charpeni** [comment]
I'll close this as it was correctly answered by @hose314.

**Comment by charpeni** [comment]
@facebook-github-bot close
