### ISSUE TITLE
App Crashes on Launch Screen

### ISSUE THREAD

**Issue by luco** [facebook/react-native#15260]
Whenever I try to run my app by react-native run-ios it crashes on the launch screen. I already tried to:

- Remove `node_modules`
- Remove `ios` folder and create again
- Clear `npm` cache
- Link with `react-native link`

But, If I open my `xcodeproj` and try to run by Xcode, it works perfectly.
Any tips?

Thanks in advance.

**Comment by IvRRimum** [comment]
Having the same issue, but only in release build. debug build works normally from any launch method.

**Comment by luco** [comment]
@IvRRimum I think you have a differente issue than me. My app even launch a white screen. It crashes on launch screen.

**Comment by luco** [comment]
Nevermind, fixed my issue with this reply:
https://stackoverflow.com/a/42484203/486509
