### ISSUE TITLE
React native error can not find entry modules error 404

### ISSUE THREAD

**Issue by MBehtemam** [facebook/react-native#15262]
hi today i install `React native` and create an app with `create-react-native-app` with following instruction of [this page](https://facebook.github.io/react-native/docs/getting-started.html) and then run `npm start` but i get this error : 

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/xLWHQ.png

before it i develop android app and i think the problem is not from sdk but i cant face why this error happen , also i doesn't change source of app only create app and then run it.

**Comment by hramos** [comment]
For CRNA issues, can you open the issue at [react-community/create-react-native-app](https://github.com/react-community/create-react-native-app) instead?
