### ISSUE TITLE
custom font is not working 

### ISSUE THREAD

**Issue by adarshTS** [facebook/react-native#15266]
### Is this a bug report?

NO

### Have you read the Bugs section of the How to Contribute guide?

Yes

### Environment

1. `react-native -v`: 0.46.4
2. `node -v`: 6.11.0
3. `npm -v`: 3.10.10
4. `yarn --version`: 0.27.5

Then, specify:

- Target Platform: Android

- Development Operating System: Windows

- Build tools:

### Steps to Reproduce
1. I need to make a custom font 
2. Then assign it some attributes 
3.

### Expected Behavior

After saving the fonts in my assets folder of my project  I linked it by the command `react-native link` 
the links were installed and I cross checked the installation in my android>src>main>assets>fonts and everything was fine there too and I expected to  get the custom font using the styling `fontFamily: 'Coda-Heavy'` but I didn't get the required custom font in run 

### Actual Behavior

[
![onrun](https://user-images.githubusercontent.com/22904766/28742604-0a395562-7452-11e7-9b31-d14fa9fefc70.jpg)
](url)

**Comment by rajsuvariya** [comment]
For resources, Android doesn't accept Capital letters or hyphen (-). Try to rename the fonts and use the convention followed in the following code snippet. This snippet works for me.

```
...Platform.select({
      ios: {
        fontFamily: "PFEncoreSansPro-Medium",
      },
      android: {
        fontFamily: "pfencoresanspro_medium",
      },
    }),
```

**Comment by adarshTS** [comment]
thanks, @rajsuvariya but it's not working my fonts were in lowercase

**Comment by liquidprogrammer** [comment]
@adarshTS What fonts do you use? I mean, what extension? I work with **ttf** fonts, and everything is fine with them (i used this guide, was very helpful for me https://medium.com/@gattermeier/custom-fonts-in-react-native-for-android-b8a331a7d2a7). 

Also, my fonts path is a little bit different: android/**app**/src/main/assets/fonts, but may be i just have an old project structure :)

**Comment by adarshTS** [comment]
@liquidprogrammer  I also use ttf font, I don't know why is it not working I had already  referred  that article  when I was doing this

**Comment by peterp** [comment]
The issue here is that on Android you have to match the filename exactly.

**Comment by adarshTS** [comment]
I have followed the same but still its not working

**Comment by rajsuvariya** [comment]
@adarshTS Looks like this guide is outdated. I followed this https://medium.com/react-native-training/react-native-custom-fonts-ccc9aacf9e5e and I am able to load custom fonts in my app

**Comment by adarshTS** [comment]
I have done all the same process but the problem is  encountered only  when I use some  particular fonts like  
`SwitzerlandCondBlack Italic`   and `SwitzerlandCondBlackPSMT`

**Comment by rajsuvariya** [comment]
@adarshTS Can you push your code on git and post a link here?

**Comment by adarshTS** [comment]
@rajsuvariya  I have created a demoApp  and have used this  custom font  just check it out its still not working
[https://github.com/adarshTS/demoApp](https://github.com/adarshTS/demoAppurl)

**Comment by rajsuvariya** [comment]
@adarshTS Have you figured out the issue? if yes, please post the solution here it may help others facing the same issue

**Comment by adarshTS** [comment]
Well I don't know how it worked when I was moving to some other fonts I gave it a final try and it worked. Couldn't figure out if its the problem with the emulator or something else because I double checked everything before making a demoApp for others to check the problem. Happy that its working fine now

**Comment by joshjconlin** [comment]
I had this issue, and it ended up being because i was using font-weight. see https://hiddentao.com/archives/2017/03/10/get-custom-fonts-working-in-react-native/ for a work around

**Comment by adarshTS** [comment]
when we are using custom fonts we can't assign `fontWeight` or `fontStyle`  because  it makes the custom font disabled

**Comment by sunweiyang** [comment]
I'm seeing this problem, but I don't believe I have `fontWeight` or `fontStyle` set (I filed #17641 which was marked as a duplicate). Anyone else experiencing this too?

**Comment by cjadhav** [comment]
Hi @sunweiyang,

You can follow these methods as show in this link.
https://hiddentao.com/archives/2017/03/10/get-custom-fonts-working-in-react-native/

It's really nice to use all fonts.
This solves my problem, I hope it might help you too..

**Comment by Macromeda** [comment]
i'm facing the same issue, RN version 0.55.1, using real device android 4.4.2.

this issue should re-opened.

**Comment by mrezzaaa** [comment]
Yeah,me too . using latest RN and gradle-4.4-all but still not works

**Comment by Shanie1331** [comment]
I am also having the same issue. Please help.

**Comment by divyanshverma** [comment]
+1

**Comment by ayehia** [comment]
+1 the same issue

**Comment by mwmwmw** [comment]
This may help some of you.

Make sure you add 
```
  "rnpm": {
    "assets": [
	    "./assets/fonts/"
    ]
  }
```
to your package.json before you `react-native link`

**Comment by aleppos** [comment]
@mwmwmw I already doing this but `react-native link` not finding anything

**Comment by Cicko** [comment]
Using fontWeight was my problem. Thank you to you all!!
