### ISSUE TITLE
[Dependencies] Broken depends when building from scratch

### ISSUE THREAD

**Issue by lorenzostdubois** [facebook/react-native#1527]
uname -a
Darwin MacBookPro.local 14.4.0 Darwin Kernel Version 14.4.0: Tue May  5 14:17:52 PDT 2015; root:xnu-2782.30.4~3/RELEASE_X86_64 x86_64

> contextify@0.1.14 install /usr/local/lib/node_modules/contextify
> node-gyp rebuild

2015-06-05 10:31:32.214 xcodebuild[31128:3358611] [MT] PluginLoading: Required plug-in compatibility UUID 8DC44374-2B35-4C57-A6FE-2AD66A36AAD9 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/GCC 4.9.xcplugin' not present in DVTPlugInCompatibilityUUIDs
  CXX(target) Release/obj.target/contextify/src/contextify.o
  SOLINK_MODULE(target) Release/contextify.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/contextify.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/contextify
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "contextify"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.5
npm ERR! code ELIFECYCLE

npm ERR! contextify@0.1.14 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the contextify@0.1.14 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/lorenzo/Develop/facebook/react-native/npm-debug.log

**Comment by brentvatne** [comment]
Discussion about this on the [contextify repo](https://github.com/brianmcd/contextify/issues/151) - maybe that will help @lorenzostdubois

**Comment by lorenzostdubois** [comment]
It seems to be related to this issue building contextify:

gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/contextify/src/contextify.o
  SOLINK_MODULE(target) Release/contextify.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/contextify.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/lorenzo/Develop/facebook/contextify
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok

**Comment by brentvatne** [comment]
@lorenzostdubois - indeed, can you chime in on that issue I linked you to above? I think that they can help you better there.

What node version are you using? Or are you using iojs?

**Comment by ide** [comment]
@lorenzostdubois the `lgcc._s.10.5` error is kind of a mystery. I encountered it too (Node 0.10, 0.12, 1.8.1, and 2.1.0) and couldn't get it to go away (tried updating brew packages, tried pruning them, used a clean installation of io.js) and the issue went away only after I restarted my computer (OS X Yosemite). Sorry I can't provide more informative guidance than that :/

**Comment by lorenzostdubois** [comment]
Hey thanks guys for taking the time to reply. 

node -v
v0.12.2

@ide I'll restart after installing the latest update. It looks like a dangling symlink that points no where and a few people have reported it without finding a real solution.

**Comment by lorenzostdubois** [comment]
Restarting MacBook did the trick! :+1:

**Comment by ide** [comment]
#magic

**Comment by MattFoley** [comment]
Rebooting worked for me as well

**Comment by jonespen** [comment]
Rebooting didn't work for me, but this did: http://stackoverflow.com/a/32654062
