### ISSUE TITLE
Checking Android Push Notifications Permissions

### ISSUE THREAD

**Issue by hose314** [facebook/react-native#15270]
### Is this a bug report?

No

### Have you read the Bugs section of the How to Contribute guide?

Yes

Hi there! Thanks for making awesome product!

Recently i've needed to check if notifications enabled on android smartphone. I've read the docs and could not found that functionality in `PermissionsAndroid` component. So then i've decided to implement it by native touch through `NotificationManagerCompat`. I think it's useful feature and i would like to add it to the build in `react-native` API. 

>If you intend to change the public API, or make any non-trivial changes to the implementation, we recommend filing an issue.

What you think?

- Target Platform: Android

- Development Operating System: macos

**Comment by hey99xx** [comment]
I am not a FB dev or a contributor, but I'd assume this PR would be very welcome. I also had to implement a native module for this. 

That said, if you're using [`NotificationManagerCompat.areNotificationsEnabled`](https://developer.android.com/reference/android/support/v4/app/NotificationManagerCompat.html#areNotificationsEnabled()) it requires support lib 24+, but [RN currently uses 23](https://github.com/facebook/react-native/blob/0.47-stable/ReactAndroid/build.gradle#L282). Hopefully that doesn't become a blocker.

**Comment by rajsuvariya** [comment]
I would look into this and submit a PR shortly

**Comment by hose314** [comment]
@hey99xx yeap. Forgot about that RN minimal version support is 23 :(
@rajsuvariya oh awesome!
