### ISSUE TITLE
[Question] Responsive font size for Android platform.

### ISSUE THREAD

**Issue by rajsuvariya** [facebook/react-native#15285]
### Is this a bug report?

No

### Have you read the Bugs section of the How to Contribute guide?

Yes

### Question
I am developing a hybrid application using react native + native Android. I have a very basic doubt how to scale the fonts according to different Android devices. I know a library for native Android https://github.com/intuit/sdp. Is there any such library for React Native?

I have searched a lot and I got different solutions, they suggest using Native Module, Pixel Ratio, or some custom functions. But I am not sure which one to use as I am using sdp for Native android and the font size for entire application should be consistent. Please suggest the best way so that I can have the consistent font size in the entire application.

I also posted the same on stackoverflow but they put it on hold saying that it is an off-topic post. Here is the link https://stackoverflow.com/questions/45409871/discussion-responsive-font-size-for-different-devices-react-native

**Comment by charpeni** [comment]
@facebook-github-bot stack-overflow

**Comment by rajsuvariya** [comment]
@charpeni  please read the last line of the description
