### ISSUE TITLE
Does PureComponent also apply to React Native?

### ISSUE THREAD

**Issue by benweizhu** [facebook/react-native#15286]
Hi React-Native team,

I am wondering whether PureComponent for React Native is still valid for writing stateless component?

I know PureComponent will shallow compare and pure function's shouldComponentUpdate will always return true.

This means I should use pureComponent or override shouldComponentUpdate to prevent meaningless render.

My question is : Does this still valid for React-Native?

**Comment by benweizhu** [comment]
Maybe I should take @charpeni comments from https://github.com/facebook/react-native/pull/14728 as reference and get a yes answer, right?

**Comment by gwmccull** [comment]
Yes, PureComponent works and is valid for React Native

**Comment by chirag04** [comment]
@facebook-github-bot stack-overflow

**Comment by charpeni** [comment]
I can confirm @benweizhu.
