### ISSUE TITLE
UnableToResolveError: Unable to resolve module ActivityIndicator #15256

### ISSUE THREAD

**Issue by ferminmoli** [facebook/react-native#15289]
error: bundling: UnableToResolveError: Unable to resolve module ActivityIndicator from C:\Projects\node_modules\react-native\Libraries\react-native\react-native-implementation.js: Module does not exist in the module map or in these directories:
C:\Projects\node_modules\react-native\node_modules
, C:\Projects\node_modules

react-native -v: 0.44.3
node -v: 6.10
npm -v: 3.10.10
Target Platform: Android
Development Operating System: Windows 10
Build tools: Android SDK 23
Step to reproduce:
1 - react-native run-android

NOTE: The following steps did not work for me

Clear watchman watches: watchman watch-del-all.
Delete the node_modules folder: rm -rf node_modules && npm install.
Reset packager cache: rm -fr $TMPDIR/react-* or npm start -- --reset-cache.
Clone repository from the scratch and install modules again

**Comment by hramos** [comment]
The latest version is 0.46.4, have you tried that? This error sounds like something we fixed already.

**Comment by ferminmoli** [comment]
Yes, I tried it, but it did not work.

**Comment by hramos** [comment]
Did you recently upgrade react-native? This can happen if there's a disconnect between the versions used in the native app and JavaScript.

**Comment by BrunoBernardino** [comment]
Seems like a duplicate of #14209.

I also just recently started having this issue (upgrading from 0.46.4) and going back isn't helping.

**Comment by jnrepo** [comment]
updated from 0.42.3 to 0.47.1 and I'm getting this error...

**Comment by iMokhles** [comment]
#15671 i was facing this issue also and fixed it with other issues and posted my fix here
