### ISSUE TITLE
React native fbsdk link failed 

### ISSUE THREAD

**Issue by shyam528** [facebook/react-native#15288]
rnpm-install info Linking react-native-fbsdk ios dependency 
rnpm-install ERR! Something went wrong while linking. Error: Expected "/*", "//", or "{" but "<" found. 
Please file an issue here: https://github.com/facebook/react-native/issues 

Expected "/*", "//", or "{" but "<" found.

linking failed by running command for ios "react-native link react-native-fbsdk"

**Comment by grigored** [comment]
duplicate of [https://github.com/facebook/react-native/issues/10032](https://github.com/facebook/react-native/issues/10032) , see answer there
