### ISSUE TITLE
How to override NetworkingModule?

### ISSUE THREAD

**Issue by huanghaiyang** [facebook/react-native#15283]
### Is this a bug report?

No

### Environment

react-native-cli: 2.0.1
react-native: 0.46.4
node: v7.10.0
npm: 5.0.1

- Target Platform:
Android

- Development Operating System:
win10

- Build tools:
Androind SDK 23

### Steps to Reproduce

1. create a new LazyPackage
2. override getNativeModules
3. override getReactModuleInfoProvider

my code below:
`
public class UEMPackage extends LazyReactPackage {

    @Override
    public List<ModuleSpec> getNativeModules(final ReactApplicationContext reactContext) {
        final List list = Arrays.asList(new NetworkInterceptorCreator() {
            @Override
            public Interceptor create() {
                return new UEMNetworkInterceptor();
            }
        });
        return Arrays.asList(
            new ModuleSpec(UEMModule.class, new Provider<NativeModule>(){
                @Override
                public NativeModule get() {
                    return new UEMModule(reactContext);
                }
            }), new ModuleSpec(NetworkingModule.class, new Provider<NativeModule>() {
                @Override
                public NativeModule get() {
                    return new NetworkingModule(reactContext, list);
                }
            })
        );
    }

    @Override
    public ReactModuleInfoProvider getReactModuleInfoProvider() {
        return new ReactModuleInfoProvider() {
            @Override
            public Map<Class, ReactModuleInfo> getReactModuleInfos() {
                Map<Class, ReactModuleInfo> map = new HashMap<Class, ReactModuleInfo>();
                map.put(UEMModule.class, new ReactModuleInfo(UEMModule.MODULE_NAME, true, false, false));
                map.put(NetworkingModule.class, new ReactModuleInfo("Networking", true, false, false));
                return map;
            }
        };
    }

    @Override
    public List<Class<? extends JavaScriptModule>> createJSModules() {
        return Collections.emptyList();
    }

    @Override
    public List<ViewManager> createViewManagers(
            ReactApplicationContext reactContext) {
        return Collections.emptyList();
    }
}
`

### Expected Behavior

I want use XMLHttpRequest or fetch to requeset a resourse by custom NetworkingModule, but it happend a waring or error

### Actual Behavior

![image](https://user-images.githubusercontent.com/5448818/28767051-cfa3b294-7604-11e7-9900-749ba28f37cd.png)

**Comment by lostaloneesk** [comment]
add 
`    @Override
    public boolean canOverrideExistingModule() {
        return true;
    }` in NetworkingModule

**Comment by huanghaiyang** [comment]
@lostaloneesk I want to extends the `NetworkModule` , but it is a final class  

`public final class NetworkingModule extends ReactContextBaseJavaModule {}`

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
