### ISSUE TITLE
[Website] Versions page should link to release notes for most recent patch

### ISSUE THREAD

**Issue by RyanMitchellWilson** [facebook/react-native#15296]
I'm trying to look at what is new in each version of react-native to see which I should upgrade to and every one of them seem to have the release notes erased so I'm not sure what is new and what I would need to do to upgrade.

<img width="920" alt="screen shot 2017-07-31 at 2 42 04 pm" src="https://user-images.githubusercontent.com/11371200/28797486-ba0403ae-75fe-11e7-862b-2812f158a1eb.png">
<img width="898" alt="screen shot 2017-07-31 at 2 42 17 pm" src="https://user-images.githubusercontent.com/11371200/28797485-ba00d31e-75fe-11e7-9903-832b139eea16.png">
<img width="900" alt="screen shot 2017-07-31 at 2 42 25 pm" src="https://user-images.githubusercontent.com/11371200/28797487-ba0458d6-75fe-11e7-8f9e-e2094c134e5a.png">

**Comment by gwmccull** [comment]
I know Github was having some issues this morning so that could be the problem, but the release notes are there:
https://github.com/facebook/react-native/releases

All of the release notes for a version get bundled together under the latest patch version of a release.  So for example, instead of looking at the release notes for v0.46.0-3, you would find all of the release notes under v0.46.4
![screen shot 2017-07-31 at 2 23 30 pm](https://user-images.githubusercontent.com/580060/28799126-23a8f592-75fc-11e7-94d8-155616ca179b.png)

**Comment by chirag04** [comment]
yeah, github was having some issues but i can see all the release notes that were created.

**Comment by RyanMitchellWilson** [comment]
I still cannot see any of the Release Notes. Click any `Release Notes` link on this page: https://facebook.github.io/react-native/versions.html and you will see nothing, when not to long ago there were notes for every single version. This should be reopened until this is actually fixed because everywhere on the react-native site points at the versions page and tells you to read the release notes to find the one you need.

**Comment by chirag04** [comment]
i see. seems like release notes are attached to the latest version but in docs we are not linking to latest version. cc @hramos

**Comment by hramos** [comment]
This is because the versions page links to the .0 release notes, but we move them over to the latest patch. I think this makes for a good first task for anyone interested in getting familiar with the website generation code.

**Comment by wisn** [comment]
@hramos Where I can find the source code? Is the `gh-pages` branch generated from elsewhere?

**Comment by hramos** [comment]
The docs have now moved to https://github.com/facebook/react-native-website

We'd still like to fix this, feel free to re-open there.
