### ISSUE TITLE
TouchableHighlight underlayColor should be a style?

### ISSUE THREAD

**Issue by ColinEberhardt** [facebook/react-native#153]
It feels a little odd / inconsistent that all of the visual properties of TouchableHighlight can be set via a style, apart from underlayColor (and potentially activeOpacity as well).

**Comment by brentvatne** [comment]
@ColinEberhardt - I believe the purpose for this is to keep the StyleSheet properties as similar as possible to CSS, this allows for styles to potentially be portable between platforms and keeps it as a subset of CSS. cc @vjeux
