### ISSUE TITLE
Can not use Chrome to debug React Native App?

### ISSUE THREAD

**Issue by FourEyebrowXiake** [facebook/react-native#15307]
Error was occurred while I was trying to open the Debug JS Remotely option in my **iOS** emulator.
The follow information was shown in react-native debug app:

![image](https://user-images.githubusercontent.com/18180417/28822165-cd6d8810-76ea-11e7-989a-e0f38d93e4bf.png)

I found these error information in my terminal running React packager：

![image](https://user-images.githubusercontent.com/18180417/28822204-efb9e9a4-76ea-11e7-9b5d-657cc6c634b2.png)

But if i stop Remote JS Debugging, React Native App can run successfully.

I changed "localhost" in RCTWebSocketExecutor.m to the IP address of my computer (and restarting everything),but none of the solutions seem to work:
![image](https://user-images.githubusercontent.com/18180417/28827474-41b8b4dc-7700-11e7-8da6-cd9e229e4a70.png)

**Comment by charpeni** [comment]
@facebook-github-bot no-template
