### ISSUE TITLE
StatusBar background not being set & translucent=false not working

### ISSUE THREAD

**Issue by markentingh** [facebook/react-native#15301]
I tried posting a comment to closed bug #12618, but there is more to the bug than just background color. The translucency is not being set as well.

Running React Native 0.46.4 on Windows 10 in an Android emulator, emulating a Google Pixel phone with Android version 7. Also tested on Moto E 2nd Gen phone running Android 5.1

In the first screenshot, you can clearly see a translucent StatusBar with no background color, even though I set the translucent property to false & backgroundColor to "blue".

In the second screenshot, I set hidden to true, and the StatusBar did infact hide, so the component is working (somewhat).

![2017-07-29-day-2-statusbarcolorbug2](https://user-images.githubusercontent.com/2896371/28755240-401bef96-7524-11e7-85b8-a68751705ab1.jpg)

![2017-07-29-day-2-statusbarcolorbug3](https://user-images.githubusercontent.com/2896371/28755243-4425411e-7524-11e7-8421-ddf70ae5ddd9.jpg)

**Comment by Noitidart** [comment]
On Android of course, testing `StatusBar.translucent` on device is also giving `undefined`:

```
import { StatusBar } from 'react-native'

console.log('StatusBar.translucent:', StatusBar.translucent); // should be false - is undefined
StatusBar.setTranslucent(true);
console.log('StatusBar.translucent:', StatusBar.translucent); // should be true - is undefined
```

**Comment by cchampou** [comment]
Same issue on 0.47, running on Android 7.0 device.

**Comment by iamdurui** [comment]
My android's device is this case .it is MI5 7.0(xiaomi)

**Comment by ArvoGuo** [comment]
same problem!

Device: MIX 2
System Version: MIUI 8.5

only prop `hidden` work well

prop `backgroundColor` and `barStyle` doesn't work 

code: 

```jsx
    <View>
       <StatusBar
            backgroundColor="green"
            barStyle="dark-content" 
       />
    </View> 
```

nothing happend!!!

**Comment by Noitidart** [comment]
Re-filed this following the template here - https://github.com/facebook/react-native/issues/16432

**Comment by dann1609** [comment]
@Noitidart I tried as you said but it return undefended all times!

**Comment by daney357** [comment]
I have the same problem :(
