### ISSUE TITLE
0.6.0-rc StatusBarIOS.Style.lightContent undefined is not an object

### ISSUE THREAD

**Issue by ldesplat** [facebook/react-native#1530]
What happened to StatusBarIOS? This used to work on 0.4.x and then I upgraded to 0.5 and it continued working. I then upgraded to 0.6.0-rc and I get `undefined is not an object (evaulating 'StatusBarIOS.Style.lightContent')`.

Inspecting StatusBarIOS I see there is still setStyle and setHidden but that's it.

Alright, going through the docs I see that the API has changed (which is a breaking change). Now we have to put an actual string in so:
`StatusBarIOS.setStyle(StatusBarIOS.Style.lightContent, false);`
to
`StatusBarIOS.setStyle('light-content', false);`

**Comment by ide** [comment]
I believe this was an intentional change in https://github.com/facebook/react-native/commit/45d8fb0ef64a8a41929d61fe822a64c2febe5455. @nicklockwood could you confirm that the enum was dropped in favor of "default" and "light-content"?

cc @vjeux for the breaking change for the release notes.

**Comment by nicklockwood** [comment]
Yes, sorry, I updated the example but forgot to include it in the release notes.

**Comment by ide** [comment]
Thanks for confirming.

@ldesplat looks like this is working as intended and thanks for testing the RC!

**Comment by vjeux** [comment]
@ide, i'm not at a computer, mind editing the changelog with this and react-native-mixin require (even though I thought that diff was reverted)
