### ISSUE TITLE
How to import permissions module on react native project?

### ISSUE THREAD

**Issue by boga01** [facebook/react-native#15308]
I'm new at react native and typescript.I wanna create permissions module for my react native project and I seperated two links at below [Yonah's project][1] and [Facebook's permissions project][2]

  [1]: https://github.com/yonahforst/react-native-permissions
  [2]: https://github.com/facebook/react-native/blob/master/Libraries/PermissionsAndroid/PermissionsAndroid.js

Additionaly 

> npm install ,npm start , yarn run build --watch and react-native run-android

  command running smoothly but permission module dont use it ,I dont present this module add my project.  
And my trying link at below ;

    const permission = require('react-native-permissions')
    import React from 'react'
    import {
    StyleSheet,
    TouchableHighlight,
    Text,
    View,
    Alert,
    AppState,
    Platform,
    PermissionsAndroid,
    } from 'react-native'

    interface Props {
    names: string[]
    }

    interface PermissionsState {
    status: PermissionStatus
    }

    type PermissionStatus = 'granted' | 'denied' | 'never_ask_again' | ''

    export class permissions extends React.Component<Props, PermissionsState>
    {
    constructor(props: Props, context: any)
    // tslint:disable-next-line:brace-style
    {
        super(props, context)

        this.state = {
            status: '',
        }
    }

    public render()
    // tslint:disable-next-line:brace-style
    {
        return (<View> a </View>)
    }
     }

     async function requestCameraPermission() {
    try {
        const granted = await PermissionsAndroid.request(
            PermissionsAndroid.PERMISSIONS.CAMERA,

        )
        if (granted === PermissionsAndroid.RESULTS.GRANTED) {
            // console.log("kamerayı kullanabilirsiniz")
        } else {
            // console.log('kamerayı kullanamazsınız')
        }
      } catch (err) {
        // console.warn(err)
      }
      }

      export default permission

**Comment by charpeni** [comment]
@facebook-github-bot stack-overflow

**Comment by boga01** [comment]
**@facebook-github-bot @mkonicek  thanks for comment I know I asked this question on stackoverflow myself,but dont answer suitable,I just try this platform for chance.**

**Comment by boga01** [comment]
@mkonicek Is it any idea this situation :1st_place_medal:

**Comment by charpeni** [comment]
@facebook-github-bot stack-overflow
