### ISSUE TITLE
TextInput's secureTextEnry={true} not working with keyboardType="email-address" on Android

### ISSUE THREAD

**Issue by poongnewga** [facebook/react-native#15319]
### Is this a bug report?

Yes

### Have you read the Bugs section of the How to Contribute guide?

Yes

### Environment

1. `react-native -v`: 0.45.1
2. `node -v`: v8.2.1
3. `npm -v`: 4.6.1
4. `yarn --version`:

Then, specify:

- Target Platform: Android, iOS

- Development Operating System: macOS Sierra

- Build tools:

### Steps to Reproduce

(Write your steps here:)

1. Use secureTextEntry={true} with  keyboardType="email-address" 
2. secureText will not work on Android. (work well on iOS)
3. without keyboardType="email-address", secureText works well on Android.
    (I used my Samsung Galaxy S6 device.)

### Expected Behavior

Just add secureText={true} with keyboardType="email-address"  on TextInput.
I expected everything just go well.

### Actual Behavior

I wanted to use email-address keyboard for password and make TextInput safe with secureText={true}.

I wrote secureTextEntry={true} with  keyboardType="email-address",
and something went awkward.

Only on iOS, it worked well not on Android.

[iOS]
<img width="380" alt="ios" src="https://user-images.githubusercontent.com/15710904/28841929-c5e0ccf0-7736-11e7-924a-4adc5f3e3091.png">
[Android]
<img width="380" alt="android" src="https://user-images.githubusercontent.com/15710904/28842003-f4c5fa04-7736-11e7-8f8e-16ecbfe3dc00.jpeg">
=> nothing happen. There are no circle characters.
### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by henrikra** [comment]
Why email should be secured?

**Comment by poongnewga** [comment]
@henrikra First I'm sorry for my nonfluent English. I thought the layout of email address keyboard would be appropriate for my password input, because I validate this password with alpha-numeric characters. There would be no problem when using 'Default' type keyboard, but I thought there are some possibilities some services would force users to use some layouts like email, numeric and etc.

**Comment by BrandonWilliamsCS** [comment]
If I'm understanding properly, this isn't even possible on native Android.
One would need to set text type flags of both `TYPE_TEXT_VARIATION_PASSWORD` (0x00000080)  and `TYPE_TEXT_VARIATION_EMAIL_ADDRESS` (0x00000020), which Android would just interpret as `TYPE_TEXT_VARIATION_WEB_EDIT_TEXT` (0x000000a0).

**Comment by andela-cofor** [comment]
I think poongnewga is saying the password field is not hiding the password on Android
