### ISSUE TITLE
ComponentWillUnmout not called for Modal in AppleTV

### ISSUE THREAD

**Issue by rada** [facebook/react-native#15313]
### Is this a bug report?

Yes

### Have you read the Bugs section of the How to Contribute guide?

Yes

### Environment

1. `react-native -v`: 0.46.4
2. `node -v`: 6.5.0
3. `npm -v`: 3.10.3

Then, specify:

- Target Platform: AppleTV

- Development Operating System: macOS Sierra (10.12.5)

- Build tools: Xcode (8.3.3)

### Steps to Reproduce

Open Modal in Tab 1 by clicking on 'Open Modal' touchable.

(Write your steps here:)

1. Focus touchable 'Open Modal' (in simulator press key Down)
2. Press touchable 'Open Modal'
3. Press 'Menu' button on Apple TV Remote (in simulator, press CMD + SHIFT + R to display TV Remote)

### Expected Behavior

After the 'Menu' button is pressed on Apple TV Remote, Modal is closed and the method componentWillUnmout is called for component used in Modal.

### Actual Behavior

Modal is closed but the componentWillUnmout method is not called if the modal is closed by pressing the 'Menu' button in the Apple TV Remote. If the modal is closed by pressing the touchable 'Close Modal', the componentWillUnmout method is called as expected.

### Reproducible Demo

https://gitlab.com/radamich/tvTabBar/tree/tvosModal

index
```javascript
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  AppRegistry,
  Text,
  View,
  TabBarIOS,
  ListView,
  Modal,
  TouchableHighlight,
} from 'react-native';

import List from './List';

export default class tvTabBar extends Component {

	_tabItems: Array<{ key: string }> = [
		{ key: 'TAB 1' },
		{ key: 'TAB 2' },
		{ key: 'TAB 3' },
		{ key: 'TAB 4' },
	];

	constructor(props) {
		super(props);
		this.state = {
			activeTab: 'TAB 1',
			showModal: false,
		};
	}

	_getTabItem = (key: string) => {
		switch (key) {
			case 'TAB 1':
				return (
					<View style={{ flex: 1, top: 140, borderColor: 'red', borderWidth: 10, padding: 200 }}>
						<Modal 
							visible={this.state.showModal}
							transparent={true}
						>
							<List closeModal={this.closeModal} />

						</Modal>
						<TouchableHighlight onPress={() => {
								console.log('MODAL SHOW', this.state.showModal);
								this.setState({ showModal: true });
							}}
							underlayColor={'orange'}
						>
							<Text style={{ fontSize: 30 }}>Open Modal</Text>
						</TouchableHighlight>
					</View>
				);
			case 'TAB 2':
				return (
					<View style={{ flex: 1, top: 140, borderColor: 'green', borderWidth: 20 }}>
						<Text style={{ fontSize: 30 }}>TAB 2</Text>
					</View>
				);
			case 'TAB 3':
				return (
					<View style={{ flex: 1, top: 140, borderColor: 'darkblue', borderWidth: 30 }}>
						<Text style={{ fontSize: 30 }}>TAB 3</Text>
					</View>
				);
			case 'TAB 4':
				return (
					<View style={{ flex: 1, top: 140, borderColor: 'deeppink', borderWidth: 40 }}>
						<Text style={{ fontSize: 30 }}>TAB 4</Text>
					</View>
				);
			default:
				return null;
		}
	}

	closeModal = () => {
		this.setState({ showModal: false });
	}

	_setTab(key) {
		return () => {
			console.log('Selecting tab: ', key);
			if (this.state.activeTab !== key) {
				this.setState({ activeTab: key });
			}
		};
	}

	render() {
		return (
			<TabBarIOS>
				{
					this._tabItems.map((tabItem) => {
						return (
							<TabBarIOS.Item
								key={tabItem.key}
								onPress={this._setTab(tabItem.key)}
								title={tabItem.key}
								selected={tabItem.key === this.state.activeTab}
							>
								{ this._getTabItem(tabItem.key) }
							</TabBarIOS.Item>
						);
					})
				}
			</TabBarIOS>
		);
	}
}

AppRegistry.registerComponent('tvTabBar', () => { return tvTabBar; });
```

List.js
```javascript
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  Text,
  View,
  ListView,
  FlatList,
  TouchableHighlight,
} from 'react-native';

export default class List extends Component {

	
	constructor(props) {
		super(props);

		this.ds = new ListView.DataSource({ rowHasChanged: (r1: Object, r2: Object) => { return r1 !== r2; } });

		this.state = {
			dataSource: this.ds.cloneWithRows([{ value: 1 }]),
			data: [{ value: 1 }, { value: 2 }],
		}
	};

	_renderRow(rowData) {
		console.log('RenderRow: ', rowData.value);
		return (
			<View>
				<Text>{rowData.value}</Text>
			</View>
		)
	}
	
	_renderFlatListItem = ({ item }) => {
		return this._renderRow(item);
	}
	
	componentDidMount() {
		setTimeout(() => {
			const data = Array.from({ length: 2000 }).map((_, index) => {
				return { value: index };
			})
			this.setState({
				dataSource: this.ds.cloneWithRows(data),
				// data: data,
			})
		}, 3000)
	}

	componentWillUnmount() {
		console.log('List.js: componentWillUnmount');
	}
	
	render() {
		console.log('Render List');
		return (
			<View style={{ backgroundColor: 'blue', padding: 500 }}>
				<FlatList
					data={this.state.data}
					renderItem={this._renderFlatListItem}
					keyExtractor={(item) => { return item.value }}
				/>
				<TouchableHighlight onPress={() => {
						this.props.closeModal();
					}}
					underlayColor={'orange'}
				>
					<Text style={{ fontSize: 30 }}>Close Modal</Text>
				</TouchableHighlight>
			</View>
		);
	}
}
```

**Comment by rada** [comment]
@dlowder-salesforce

**Comment by dlowder-salesforce** [comment]
Thanks for the bug report @rada , I'll have a look

**Comment by dlowder-salesforce** [comment]
Hmmm this does not look like something that will be easy to fix.  The Modal component isn't really a modal in the usual iOS sense -- it just renders null if visible is set to false, and renders normally otherwise.  The problem is that the tvOS menu button bypasses the JS and just dismisses the view, getting the app into a bad state where JS thinks the Modal component is still there, but there is no native view for it any more.  I think this component needs some work maybe....

**Comment by dlowder-salesforce** [comment]
Found a solution -- will be submitting a pull request shortly.

**Comment by dlowder-salesforce** [comment]
@rada you can test out my fix by using https://github.com/dlowder-salesforce/react-native/tree/tvos-combined-fixes (includes previous fixes to TabBarIOS).

You will need to add one line of code to your test case:  in `index.ios.js`, the Modal component should look as shown below:

```javascript
						<Modal 
							visible={this.state.showModal}
                                                        onMenuPress={this.closeModal}    // <------
							transparent={true}
						>
							<List closeModal={this.closeModal} />

						</Modal>

```

**Comment by rada** [comment]
Thanks @dlowder-salesforce, it's working now with your fix. Thanks.

**Comment by dlowder-salesforce** [comment]
@rada in further work on this issue, I find that I need to change the `onMenuPress` property to `onRequestClose` instead, for consistency with Android (where the back button does the same thing).  My repo has been updated with this change.

**Comment by dlowder-salesforce** [comment]
The fix for this is now merged, so we can close this issue.

**Comment by psegalen** [comment]
Hi all, sorry for bringing bad news but it seems that onRequestClose gets called on tvOS only for "Debug" scheme, in "Release" it just doesn't fire!

Repo to reproduce: https://github.com/psegalen/rn-tvos-modal-bug
Steps:
- Get the code, run it in Apple TV simulator with XCode (btw, to get an app running in Release scheme for tvOS you have to modify a `react-native init` config twice, one to add `libReact.a` to the test project, another to add missing "Other Linker Flag" `-lc++`)
- If you press the touchable, the modal shows, if you press the remote's menu button, it hides, it's ok but onRequestClose isn't called (you can see that because the state hasn't changed, isModalOpen remains true)
- If you do the same test after switching the "Run" scheme to "Debug", you'll see that the behaviour is correct since the state is correctly changed (isModalOpen become false after closing the modal)

Can someone check why this is happening please?
