### ISSUE TITLE
react-native link doesn't start on version 0.47.0

### ISSUE THREAD

**Issue by AlpZero** [facebook/react-native#15324]
### Environment

1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.47.0
2. `node -v`:
v8.2.1
3. `npm -v`:
5.3.0
4. `yarn --version`:
0.27.5

- Target Platform:
Android,  iOS

- Development Operating System:
macOS Sierra

### Steps to Reproduce

1. `react-native init myapp`
2. `cd myapp `
_Add a component that need to be linked_
3. `yarn add react-native-awesome-master-blaster-component`
_Link the installed component_
4. `react-native link react-native-awesome-master-blaster-component`
5. wait.

### Expected Behavior

The `react-native-awesome-master-blaster-component` linked to the project

### Actual Behavior

Nothing happens:
![test](https://user-images.githubusercontent.com/17249907/28855952-7d1c3e5c-7716-11e7-8c9f-1065636c23c6.png)

ps: On the same environment, with react-native version <= 0.46.4, react-native link works as expected.

**Comment by hongphi** [comment]
Same issue

**Comment by oatcrunch** [comment]
Same here (running on Windows 7, RN version 0.47):

C:\0\testmap>react-native link react-native-maps
Scanning 559 folders for symlinks in C:\0\testmap\node_modules (13ms)

C:\0\testmap>

**Comment by strawferry** [comment]
+1

**Comment by AlpZero** [comment]
Issue solved on 0.47.1.
