### ISSUE TITLE
How to write camera permissions for RN project?

### ISSUE THREAD

**Issue by boga01** [facebook/react-native#15327]
I'm very new on React-Native and typescript I want to write a permission module for camera.My idea is like this begin ;

     async componentWillMount() { // 
		// tslint:disable-next-line:prefer-const
		let options:Camera []*/
but don't forward anymore I referenced [facebook rN permissions][1],[yonah permissions][2] 
Sum how I will continue this module ?

                                                                    

  [1]: https://facebook.github.io/react-native/docs/permissionsandroid.html
  [2]: https://github.com/yonahforst/react-native-permissions

**Comment by charpeni** [comment]
You could refer to https://github.com/lwansbrough/react-native-camera.

**Comment by charpeni** [comment]
@facebook-github-bot stack-overflow
