### ISSUE TITLE
[packager] Hangs on: `index.ios.js`  [development, non-minified, hmr disabled] 0%

### ISSUE THREAD

**Issue by dluksza** [facebook/react-native#15332]
### Is this a bug report?

Yes

### Have you read the Bugs section of the How to Contribute guide?

Yes

### Environment

1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.47.0
2. `node -v`:
v8.2.1
3. `npm -v`:
5.3.0
4. `yarn --version`:
0.27.5

Then, specify:

- Target Platform: iOS, Android

- Development Operating System: macOS

- Build tools: xcode, android studio.

### Steps to Reproduce

(Write your steps here:)

1. Start new project with `react-native init BuildHangs`
2. Run `react-native run-ios` within `BuildHangs` directory
3. Wait for ever for `packager` to build `index.ios.js` file.

### Expected Behavior

Initial react-native application should start on iphone emulator.

(Write what you thought would happen.)

### Actual Behavior

Nothing happen, it seams like `index.ios.js` file is not compiled, compilation process hangs (or exit). Packager hangs with output:

```
Loading dependency graph...
Bundling `index.ios.js`  [development, non-minified, hmr disabled]  ░░░░░░░░░░░░░░░░  0.0% (0/1)
```

(Write what happened. Add screenshots!)

Everything was working fine until today afternoon when it immediately stopped working. Probably `brew update && brew upgrade` has updated /something/ and react-native got broken.

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by joshuakelly** [comment]
+1

`2017-08-02 22:22:12.250 [warn][tid:main][RCTBridge.m:114] Class RCTCxxModule was not exported. Did you forget to use RCT_EXPORT_MODULE()?`

**Comment by prakashsejwani** [comment]
+1

**Comment by joshuakelly** [comment]
Can confirm @prakashsejwani. Uninstalling watchman `brew uninstall watchman` got this working again for me as well.

**Comment by dluksza** [comment]
Uninstalling `watchman` fixed this issue for react demo app, but in my main project I'm facing issue described in #910

**Comment by fungilation** [comment]
Not sure if related, but regarding `watchman` my Packager console has this output:
```
React packager ready.

Loading dependency graph.../Users/<user>/Library/LaunchAgents/com.github.facebook.watchman.plist: Could not find specified service

Loading dependency graph, done.
Bundling `index.ios.js`  [development, non-minified, hmr disabled]  ░░░░░░░░░░░░░░░░  0.0% (0/1)Launching Dev Tools...
Bundling `index.ios.js`  [development, non-minified, hmr disabled]  100.0% (599/599), done.
```

**Comment by dluksza** [comment]
Running `launchctl unload -F $HOME/Library/LaunchAgents/com.github.facebook.watchman.plist` fix both issues for me. Now I'm able to run `react-native` with `watchman` again :)

Thanks to @danielfarrell for figuring this out on https://github.com/facebook/watchman/issues/511#issuecomment-319764222

**Comment by youmyyou** [comment]
@dluksza how to open hmr?

**Comment by dluksza** [comment]
@youmyyou I don't know how to open hmr, never did that and never was interested in opening it

**Comment by youmyyou** [comment]
@dluksza How do you open the dev menu?

**Comment by prank7** [comment]
@youmyyou could you figure out how to open hmr?

**Comment by olviejs** [comment]
@joshuakelly work for me, tks.

**Comment by faizmokhtar** [comment]
I'm currently experiencing the same issue too right now. Uninstalling watchman only worked the first time. Running `launchctl unload -F $HOME/Library/LaunchAgents/com.github.facebook.watchman.plist` also doesn't work.

**Comment by iMokhles** [comment]
#15671 i fixed this issue and posted my fix hope It helps you
