### ISSUE TITLE
iOS FlatList Rotation Bug

### ISSUE THREAD

**Issue by jeremy4772** [facebook/react-native#15337]
### Is this a bug report?

Yes

### Have you read the Bugs section of the How to Contribute guide?

Yes

### Environment

1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.47.1
2. `node -v`:
v6.11.0
3. `npm -v`:
5.3.0

Then, specify:

- Target Platform: iOS

- Development Operating System: macOS 10.12.5

- Build tools: No native code, built using react-native run-ios

### Steps to Reproduce

(Write your steps here:)

1. Create new react native project with react-native init RotationBug
2. Replace the index.ios.js code with the code from https://snack.expo.io/B1P9GYJwb
3. react-native run-ios
4. Rotate phone emulator to landscape mode.
5. Scroll to bottom of list view.
6. Rotate back to portrait mode.

### Expected Behavior

<img width="376" alt="screen shot 2017-08-02 at 12 56 21 pm" src="https://user-images.githubusercontent.com/6550393/28885006-29ed91ec-7782-11e7-9367-1088dbb79997.png">

Would rotate such that the bottom list element would be on the bottom of the screen, just as if they had scrolled to the bottom entirely in portrait mode.

### Actual Behavior

<img width="375" alt="screen shot 2017-08-02 at 12 56 09 pm" src="https://user-images.githubusercontent.com/6550393/28884988-18c5e84c-7782-11e7-854e-206dc1e3ef99.png">

The bottom message ends up in the middle of the screen, with the remainder below it just being empty space. React native will re-render the list correctly if it is dragged, but not tapped.

This is iOS exclusive, on Android it exhibits expected behavior.

### Reproducible Demo

https://snack.expo.io/B1P9GYJwb

The snack UI does not allow for rotation as far as I know, so to see the bug create a new Project with 'react-native init RotationBug', copy paste that code into index.ios.js, and run with react-native run-ios.

**Comment by shergin** [comment]
Duplicates #13566

**Comment by shergin** [comment]
Fixed in https://github.com/facebook/react-native/commit/1d22f8fb27e9432e357401ce6f6cede4d710472c .
