### ISSUE TITLE
[Bridge] UIColor cache fills up when animating colors

### ISSUE THREAD

**Issue by ide** [facebook/react-native#1533]
See #1513. The issue is that animating a color quickly fills up the color cache. We probably want to:

- Cap the size of the cache and implement a policy like Least Frequently Used or segmented LRU
- Change the caching policy when the color is animated (e.g. MRU, or don't cache at all. But if the animation repeats it could be helpful to have cached the values.)

cc @sahrens @nicklockwood @vjeux for thoughts

**Comment by sahrens** [comment]
Oh yeah, forgot about the color cache. Another approach is to maintain a frequency map of usage that is periodically periodically reset (never more than 10 entries or something). Then you only cache elements if they have multiple counts in the map.

**Comment by ide** [comment]
Color cache now limits to 128 entries.
