### ISSUE TITLE
TextInput keyboardType='numeric' doesnt work on android if editable={false}

### ISSUE THREAD

**Issue by TakaGoto** [facebook/react-native#15346]
### Is this a bug report?

yes

### Have you read the Bugs section of the How to Contribute guide?

Yes

### Environment

1. `react-native -v`: 0.42.3
2. `node -v`: 8.1.3
3. `npm -v`: 4.6.1
4. `yarn --version`: 0.27.5

- Target Platform: Android

- Development Operating System: MacOS Sierra 10.12.5

### Steps to Reproduce

I was able to reproduce this by:

1. starting a new AwesomeProject reading through the guide here: https://facebook.github.io/react-native/docs/getting-started.html
2. then created a TextInput Component in app.js with the following props: autoFocus={true} keyboardType='numeric' editable={false}.

### Expected Behavior

the keyboard should be numeric version, where numbers 0-9 should be the majority of the keyboard displayed, along with a few symbols. OR it should just not show the keyboard because it's not supposed to be editable. I say 'or' because I was able to show a numeric keypad on the iOS side with the same props.

### Actual Behavior

it shows the default full keyboard with letters.

### Reproducible Demo

https://snack.expo.io/BkkyY61v-

Other Information:
You might notice the RN version i'm using it a bit old, but I was also able to reproduce this with the latest RN version, which is React 16.0.0-alpha.12 and RN 0.46.1 currently.

if I remove `editable={false}`, it starts to work.

**Comment by shergin** [comment]
But... What the point to see a keyboard if you cannot type?

**Comment by TakaGoto** [comment]
@shergin the intention was to not let the user tap on the text input, but only use the numeric keyboard to enter text in it, constraining the user to only numbers. 

i do want to point out that the functionality is different with the same props across ios and android, so even if my use case isnt a big deal, i think there should be some consistency across platforms.

**Comment by shergin** [comment]
@TakaGoto I am sorry, I don't understand. If the TextInput is disabled, it means that user cannot enter anything into the field. So, how can he if he cannot?

**Comment by aMarCruz** [comment]
@shergin , same issue here in Android w/editing=true (implicit):

```js
    <Input
        ref="codeInput"
        autoFocus
        maxLength={PHONE_CODE_LEN}
        onChangeText={this.setCode}
        returnKeyType="next"
        onSubmitEditing={this.goProfile}
        style={styles.input}
        keyboardType="numeric"
        value={code}
    />
```
The default keyboard is opened.

RN 0.53.3
Tested on devices with Android 6.0 and 7.1
Meybe an issue with autoFocus?
