### ISSUE TITLE
The facebook.github.io/react-native website doesn't work completely on Google Chrome

### ISSUE THREAD

**Issue by shyamalschandra** [facebook/react-native#15343]
Does anyone know why?

https://facebook.github.io/react-native/docs/props.html

It shows up like the following:

![screen shot 2017-08-02 at 3 18 22 pm](https://user-images.githubusercontent.com/9545735/28893112-debded70-7795-11e7-8a7e-62ad46e742ca.png)

Why are the examples showing up?

**Comment by chirag04** [comment]
works fine for me on chrome. Which OS, browser are you using?
