### ISSUE TITLE
[android]stickyheader of ScrollView show shake when scrolling  in android 

### ISSUE THREAD

**Issue by linjson** [facebook/react-native#15355]
### Is this a bug report?

stickyheader in android show shake when scrolling

### Have you read the Bugs section of the How to Contribute guide?

(Write your answer here.)

### Environment

1. `react-native -v`:0.47.0
2. `node -v`:
3. `npm -v`:
4. `yarn --version`:

Then, specify:

- Target Platform:Android

- Development Operating System: macOS

- Build tools:Android SDK-25.0.3

### Steps to Reproduce

(Write your steps here:)

1.run RNTesterApp.android.js
2.choose "SectionList" Example,then scroll the list quickly
3.you wil see "section header" shaking

### Expected Behavior

"section header" don't shake 

### Actual Behavior

"section header" shake

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by linjson** [comment]
```
@Override
  protected void onScrollChanged(int x, int y, int oldX, int oldY) {
    super.onScrollChanged(x, y, oldX, oldY);
    if (mOnScrollDispatchHelper.onScrollChanged(x, y)) {
      if (mRemoveClippedSubviews) {
        updateClippingRect();
      }

      if (mFlinging) {
        mDoneFlinging = false;
      }

      ReactScrollViewHelper.emitScrollEvent(
        this,
        mOnScrollDispatchHelper.getXFlingVelocity(),
        mOnScrollDispatchHelper.getYFlingVelocity());
    }
  }
```

why `mOnScrollDispatchHelper.onScrollChanged` need

**Comment by hramos** [comment]
It looks like your original issue is missing some information. Can you add repro steps?

**Comment by hellomaya** [comment]
I have met the same issue, this time, I used section list, it looks like this:

```jsx
      <SectionList
        initialNumToRender={50}
        renderSectionHeader={this.renderSummary}
        style={Styles.listView}
        sections={this.props.dataSource()}
        renderItem={this.renderRow}
        keyExtractor={this.keyExtractor}
        extraData={OrderIndexStore.listIsUpdate + this.updateIt}
        windowSize={11}
        onRefresh={this.onRefresh}
        refreshing={this.refreshing}
        stickySectionHeadersEnabled
      />
```

You can see ``` stickySectionHeadersEnabled```, when it scrolling up slowly, it looks good, or if it scrolling up really fast. 

But if it scrolling up a bit fast, when the next section header is replacing the previous one, the next section header will bouncing a bit more high, then back, so it start to trembling a short time. Its really obvious to see, just like a tight spring bouncing up and down.

Here is a link to the video I records.

https://github.com/tsfosnz/RN-SectionList-Trembling-Header/blob/master/RN-SectionList-Trembling.mov

It happened in Android, Device Nexus 5, Version 5.1.1. Same RN version as above.

**Comment by kyo504** [comment]
I think this issue is pretty similar to #15445.

**Comment by sahrens** [comment]
Yeah this is the same as #15445; closing.
