### ISSUE TITLE
ReactNative v0.47.1 FlatList onEndReached problem.

### ISSUE THREAD

**Issue by strawferry** [facebook/react-native#15356]
when i update my project form 0.44.1 to 0.47.1, i found that onEndReached  Function has been called repeatedly! and never stop call onEndReached.

| version | V 0.44.1  | V 0.47.1|
|:-----------: | :-----------: | :-----------:|
 |       |      ![](https://ws1.sinaimg.cn/large/8bbf0afbly1fi6kqmyq9og208i0eox4n.gif)    |    ![](https://ws1.sinaimg.cn/large/8bbf0afbly1fi6kqmwsj6g208i0eoql7.gif)|  

### Environment

1. `react-native -v`: 0.47.1
2. `node -v`: v6.11.0
3. `npm -v`: 3.10.10
4. `yarn --version`: v0.27.5

Android  and iOS all have this problem.

```
<FlatList
                    ref={(flat) => { this._flat = flat; }}
                    ItemSeparatorComponent={()=>{return <View style={{height: 4}}/>}}
                    data={this.props.data}
                    initialNumToRender={4}
                    keyExtractor={(item, index)=>{ return index}}
                    onEndReached={this._handleMore}
                    onEndReachedThreshold={0.5}
                    onRefresh={this._handleNew}
                    refreshing={false}
                    renderItem={this._renderItem}
                    style={{backgroundColor: '#EFEFF6'}}
                />
```

**Comment by guilhermemello** [comment]
same here

**Comment by yohei01** [comment]
same here

**Comment by SurpassRabbit** [comment]
same here

**Comment by saleehk** [comment]
Any Solution yet?

**Comment by youngcao2015** [comment]
I fixed this problem by re-rendering component after componentDidMount. Here is my code: 
componentDidMount() {
        this.setState({});
        this._makeRemoteRequest();  // network request
 }

Anyone have a better solution？

**Comment by gelove** [comment]
same here

**Comment by eiosca** [comment]
In my case the loop appear beacause the bottom of my list was under the screen.
you can add the props
```
debug=1 or debug
```
to get the scroll debug. On this screen i add a margin bottom to see the bottom of the scrollbar. After that, the function associated to onEndReached was call one time.
<img src="https://user-images.githubusercontent.com/6291996/31428565-6e63e91e-ae6b-11e7-8f1b-948c333d09b1.jpg" width="200">

**Comment by Daley** [comment]
"react-native": "0.48.2"
when wrapped a FlatList with ScrollView，and onEndReached  add some data with delay.
onEndReached not stop

**Comment by HyperSimon** [comment]
@Daley Same here

**Comment by cole-yeah** [comment]
same here

**Comment by timwangdev** [comment]
If this bug was introduced from 0.45. Most likely https://github.com/facebook/react-native/commit/3e7aa5f14e0064c5e142b810829019027c52d6eb this commit broke it.

#16876 this issue gives me the information.

Ping @sahrens, who is the reviewer of that commit.

**Comment by timwangdev** [comment]
#16067 may also related

**Comment by bolan9999** [comment]
Try this,please. may be it is a surprise for you

https://github.com/bolan9999/react-native-largelist
