### ISSUE TITLE
React native ActionSheetIOS doesn’t seems to be centred when user changes device orientation.

### ISSUE THREAD

**Issue by PankajNeve** [facebook/react-native#15359]
### Is this a bug report?

Yes

### Environment

1. `react-native -v`: 2.0.1
2. `node -v`: v7.10.0
3. `npm -v`: 4.2.0
4. `yarn --version`: 

Then, specify:

- Target Platform: iOS

- Development Operating System: macOS v10.12.4

- Build tools: Xcode

### Steps to Reproduce

React native ActionSheetIOS doesn’t seems to be centred when user changes device orientation.
Steps are as below:

1. Launch the app
2. Make sure the device/simulator is in portrait mode
3. Tap on the button “Tap here... to Show Actionsheet”
4. It will show an Action sheet. in this case it's with - Title, message, Option 0, Option 1, Option 2 and Delete. 
5. Now rotate device/simulator to Landscape
6. The entire screen will adjust itself to orientation change.

### Expected Behavior

Device/simulator is in portrait position. The action sheet is shown on screen and user rotates the device from portrait to landscape, the action sheet should remain centred.

### Actual Behavior

Device/simulator is in portrait position. The action sheet is shown on screen and user rotates the device from portrait to landscape, the action sheet doesn’t remain centred. However, it is positioned towards left and bottom.

### Reproducible Demo

https://github.com/PankajNeve/RNTest.git

**Comment by PankajNeve** [comment]
<img width="431" alt="actionsheetios-portrait-noissue-centred" src="https://user-images.githubusercontent.com/25241124/28919649-096bf1e2-7814-11e7-9071-a93fdcb24a4a.png">

Action sheet in portrait screen when shown, it's a result from step#4 mentioned above.

**Comment by PankajNeve** [comment]
<img width="567" alt="actionsheetios-landscape-issue-notcentred" src="https://user-images.githubusercontent.com/25241124/28919667-22265a4c-7814-11e7-911e-84255cc4cad5.png">
Action sheet in landscape screen when rotate, it's a result from step#5 mentioned above.
Action Sheet is not centred, which is an issue.

**Comment by bishalshr** [comment]
@PankajNeve Did you find the solution to this? I am having the same problem with actionsheet not being centered when changing the orientation.

**Comment by megantracy93** [comment]
This is still an issue with v53

**Comment by pokurivijay** [comment]
Unfortunately, this issue is present in Native iOS(v11) also...
