### ISSUE TITLE
react-native@0.46.4 requires a peer of react@16.0.0-alpha.12 but none was installed

### ISSUE THREAD

**Issue by sura2k** [facebook/react-native#15366]
### Is this a bug report?
Yes

### Have you read the Bugs section of the How to Contribute guide?
Yes

### Environment
1. `react-native -v`: 
react-native-cli: 2.0.1
react-native: 0.46.4
2. `node -v`: 
v6.11.0
3. `npm -v`: 
3.10.10

- Target Platform: Android
- Development Operating System: Windows 10 64Bit
- Build tools: react-native-cli

### Steps to Reproduce
1. git clone git@github.com:GeekyAnts/NativeBase-KitchenSink.git
2. cd NativeBase-KitchenSink/
3. npm install

### Expected Behavior
No warnings specially related to 'react' and 'react-native' inter-dependency 

### Actual Behavior
In Console:
`WARN react-native@0.46.4 requires a peer of react@16.0.0-alpha.12 but none was installed`

package.json after `npm install`:
```
{
	"name": "NativebaseKitchenSink",
	"version": "2.3.1",
	"private": true,
	"devDependencies": {
		"jest": "20.0.4",
		"react-test-renderer": "16.0.0-alpha.13"
	},
	"scripts": {
		"start": "react-native start",
		"android": "react-native run-android",
		"ios": "react-native run-ios",
		"test": "node node_modules/jest/bin/jest.js --watch"
	},
	"jest": {
		"preset": "react-native",
		"transformIgnorePatterns": ["node_modules/(?!react-native|native-base-shoutem-theme)"]
	},
	"dependencies": {
		"color": "~1.0.3",
		"lodash": "^4.13.1",
		"native-base": "2.3.1",
		"react": "16.0.0-alpha.13",
		"react-native": "0.46.4",
		"react-navigation": "1.0.0-beta.11"
	}
}
```

### Reproducible Demo
https://github.com/GeekyAnts/NativeBase-KitchenSink

### What happens if you go forward ?
Runs as expected

**Comment by arsenalol69** [comment]
Hi @sura2k ! I think that you have to update NPM with : `npm install npm@latest -g`
I had the same problem but the problem disappear when I've updated npm. Hope it helps ! :)

**Comment by sura2k** [comment]
Np. Closing

**Comment by abhishek0058** [comment]
Please solve this. I am having the same problem. I have tried npm i npm@latest -g
