### ISSUE TITLE
JSExport'd objects (or alternative) aren't supported

### ISSUE THREAD

**Issue by mhuusko5** [facebook/react-native#15367]
Currently the native bridge is 1) very simple (lump modules) 2) boilerplate heavy (macros/wrappers for desired exports, objects/data needing JSONification) 3) limited to Obj-C (or Swift wrapped/de-typed in Obj-C)

#1 and #2 could be solved by supporting the native JavaScriptCore JSExport protocol functionality, so that arbitrary Obj-C objects are passable to/interactable from JS land. If this is possible as a short term measure, it would be very valuable.

But I imagine a fine grained, full, automatic bridge unique to RN could be (and would need to be, to provide the same functionality for Android) developed in the longer term, given the skill/knowledge base that participates in this project.
I'm imagining, for example, a native bridge between JS<->Obj-C, TS<->Swift that's code-gen'd for full support of each's interfaces/lang features. Has something like this ever been played with?

**Comment by ide** [comment]
If you are looking to invoke native code synchronously from JS, the CxxBridge modules support this.

JSExport wouldn't work on Android and it doesn't go through the JS bridge so it's a bit of a non-starter but for your own projects you can get the JSCExecutor from the CxxBridge (need a private category) and the JSContext from that. If you call RN functions from code invoked by JSContext, they might get scheduled outside the RN event loop and cause bugs, so be very careful.

It doesn't make sense for RN to support this nor encourage it, the pitfalls are non-obvious.
