### ISSUE TITLE
Command /bin/sh failed with exit code 35

### ISSUE THREAD

**Issue by lipan** [facebook/react-native#15378]
curl: (35) Server aborted the SSL handshake 
Command /bin/sh failed with exit code 35

![1501904675485-image](https://user-images.githubusercontent.com/1832738/28992815-4b3cb676-79d9-11e7-9a34-b8717adf4faa.png)
![1501904792052-image](https://user-images.githubusercontent.com/1832738/28992816-4b3d7f7a-79d9-11e7-92c5-de12daf81ea5.png)

**Comment by askiiRobotics** [comment]
+1
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to codeload.github.com:443 
Command /bin/sh failed with exit code 35

Weird...
