### ISSUE TITLE
Nested FlatList does not scroll

### ISSUE THREAD

**Issue by juanamd** [facebook/react-native#15375]
### Is this a bug report?

Yes

### Have you read the Bugs section of the How to Contribute guide?

Yes

### Environment

1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.47.1
2. `node -v`:
v7.10.0
3. `npm -v`:
v7.10.0
4. `yarn --version`:
0.27.5

Then, specify:

- Target Platform: Android

- Development Operating System: Windows 10 Pro

- Build tools: Not using Xcode nor Android Studio to build native code. Have only tried this on Android.

- Comments: This worked fine with RN 0.44 until yesterday when I updated to RN 0.47 and I noticed that the sublists on my app stopped working.

### Steps to Reproduce

(Write your steps here:)

1. Add a FlatList (vertical scroll) component with some data.
2. Have the renderItem prop be a function which returns another FlatList component (also with vertical scroll)
3. Let the nested FlatList have a constrained height

### Expected Behavior

Both lists (parent and children) would be able to scroll (as it did with RN v0.44)

### Actual Behavior

Only the parent FlatList scrolls.

### Reproducible Demo

https://snack.expo.io/HJSueSfPZ

**Comment by MingLoan** [comment]
same here, any updates???

**Comment by jasongonzales23** [comment]
+1

**Comment by Rpeanut** [comment]
+1

**Comment by denisftw** [comment]
I have the same issue, but I didn't know that it worked on 0.44. Hopefully, someone will come up with a workaround. This definitely works when the nested `FlatList` is inside the `ListView`, I wonder why `FlatList` is different.

**Comment by arminsal1** [comment]
Anyone find any solutions or hack-arounds? I'm facing the same issue

**Comment by hellereye** [comment]
I have the same issue

**Comment by dotansimha** [comment]
For me it works after adding `contentContainerStyle={{ flexGrow: 1}}` to the list, and `style={{ flex: 1}}` to the container. using rn>0.49.3

**Comment by tomdixon** [comment]
Same issue for me. I've noticed that the complete content of the inner FlatList appears to render outside of the bounds of the FlatList itself, and therefore no scrolling occurs as it has all been rendered. I noticed this by hiding some of the elements after the inner FlatList element.

**Comment by congsuboya** [comment]
+1

**Comment by alex1815** [comment]
From documentation: "Also inherets ScrollView Props, unless it is nested in another FlatList of same orientation", https://facebook.github.io/react-native/docs/0.48/flatlist.html

**Comment by monkingame** [comment]
+1 same issue.
I have to use 'Click More' button if there isn't any solution yet.

**Comment by tuncaulubilge** [comment]
https://github.com/facebook/react-native/pull/18299 aims to fix this issue on Android 21 and above.

**Comment by SSTPIERRE2** [comment]
@alex1815 Hey I read that too, but I don't quite understand the implications, do you? So a nested FlatList doesn't inherit ScrollView props, does that mean it's not possible for the FlatList to scroll independent from the outer ScrollView?

**Comment by boris-burgos** [comment]
+1

**Comment by ionush** [comment]
+1

**Comment by Albert0405** [comment]
Any fix for this?

**Comment by dracudakid** [comment]
+1

**Comment by Balasnest** [comment]
I am still facing this issue. Any solution for this problem?

**Comment by vitorolivg** [comment]
+1

**Comment by Danishkhan007** [comment]
I had the same issue, I resolved this by giving my Parent View,  style: {{flex: 1}}, give the same style of flex 1 for all the views that on the top of your flatlist. 
This works.

**Comment by MarcBrout** [comment]
Could you guys @Danishkhan007 or @vitorolivg post some working code please ? I'm currently pulling my hair off with this workaround...

**Comment by tuncaulubilge** [comment]
@MarcBrout did you try "nestedScrollEnabled" prop in ScrollView (available in react-native 0.56.0+) 
https://facebook.github.io/react-native/docs/scrollview#nestedscrollenabled

**Comment by MarcBrout** [comment]
@tuncaulubilge I can't upgrade my project to 0.56.0 right now, but I implemented this workaround https://github.com/facebook/react-native/issues/1966#issuecomment-285130701 and it works out !

**Comment by est7** [comment]
@MarcBrout outer component is scrollview ,if i replaced with flatlist , nested flatlist cant work

**Comment by alexpchin** [comment]
Any update on this?

**Comment by pavermakov** [comment]
+1

**Comment by sorinns** [comment]
+1
