### ISSUE TITLE
[Packager] EM watch error

### ISSUE THREAD

**Issue by elgubenis** [facebook/react-native#1537]
```sh
elgubenis:AwesomeProject lgubenis$ npm start

> AwesomeProject@0.0.1 start /Users/lgubenis/projects/AwesomeProject
> node_modules/react-native/packager/packager.sh

node_modules/react-native/packager/packager.sh: line 16: ulimit: open files: cannot modify limit: Operation not permitted

 ===============================================================
 |  Running packager on port 8081.       
 |  Keep this packager running while developing on any JS         
 |  projects. Feel free to close this tab and run your own      
 |  packager instance if you prefer.                              
 |                                                              
 |     https://github.com/facebook/react-native                 
 |                                                              
 ===============================================================

Looking for JS files in
   /Users/lgubenis/projects/AwesomeProject 


React packager ready.

 ERROR  watch EMFILE
{"code":"EMFILE","errno":"EMFILE","syscall":"watch"}
Error: watch EMFILE
    at exports._errnoException (util.js:746:11)
    at FSWatcher.start (evalmachine.<anonymous>:1172:11)
    at Object.fs.watch (evalmachine.<anonymous>:1198:11)
    at NodeWatcher.watchdir (/Users/lgubenis/projects/AwesomeProject/node_modules/react-native/node_modules/sane/src/node_watcher.js:144:20)
    at Walker.<anonymous> (/Users/lgubenis/projects/AwesomeProject/node_modules/react-native/node_modules/sane/src/node_watcher.js:351:12)
    at Walker.emit (events.js:110:17)
    at /Users/lgubenis/projects/AwesomeProject/node_modules/react-native/node_modules/sane/node_modules/walker/lib/walker.js:69:16
    at ReaddirReq.Req.done (/Users/lgubenis/projects/AwesomeProject/node_modules/react-native/node_modules/graceful-fs/graceful-fs.js:141:5)
    at ReaddirReq.done (/Users/lgubenis/projects/AwesomeProject/node_modules/react-native/node_modules/graceful-fs/graceful-fs.js:88:22)
    at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)

See http://facebook.github.io/react-native/docs/troubleshooting.html
for common problems and solutions.

npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/Users/lgubenis/.npm-packages/bin/npm" "start"
npm ERR! node v0.12.4
npm ERR! npm  v2.11.1
npm ERR! code ELIFECYCLE
npm ERR! AwesomeProject@0.0.1 start: `node_modules/react-native/packager/packager.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the AwesomeProject@0.0.1 start script 'node_modules/react-native/packager/packager.sh'.
npm ERR! This is most likely a problem with the AwesomeProject package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node_modules/react-native/packager/packager.sh
npm ERR! You can get their info via:
npm ERR!     npm owner ls AwesomeProject
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/lgubenis/projects/AwesomeProject/npm-debug.log
```

**Comment by browniefed** [comment]
This is a fairly common error I think. Workaround is to up the ulimit with `ulimit -n 2560`
Similar issue here https://github.com/substack/node-browserify/issues/431

**Comment by brentvatne** [comment]
Thanks @browniefed! @elgubenis - did this solve your problem?

**Comment by elgubenis** [comment]
hi, i used sudo and it worked

**Comment by syzer** [comment]
:+1:

**Comment by ADOMAKOR412** [comment]
elgubenis: How did you use "sudo"

**Comment by elgubenis** [comment]
i did sudo npm start and it worked that way, the error did not came up again

**Comment by abbothzhang** [comment]
i use sudo npm start and it still won`t work

**Comment by abbothzhang** [comment]
Forgot to install watchman. Sorry.

**Comment by 1181631922** [comment]
Failed at the reactnativeactivity@0.0.1 start script 'node_modules/react-native/packager/packager.sh'.
How to solve this problem？
`F:\reactnative\Demo1>npm start

> reactnativeactivity@0.0.1 start F:\reactnative\Demo1
> node_modules/react-native/packager/packager.sh

'node_modules' 不是内部或外部命令，也不是可运行的程序                                                                                                                                                    
或批处理文件。                                                                                                                                                                                           

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "E:\\Program Files\\Node\\node.exe" "E:\\Program Files\\Node\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v5.5.0
npm ERR! npm  v3.8.1
npm ERR! code ELIFECYCLE
npm ERR! reactnativeactivity@0.0.1 start: `node_modules/react-native/packager/packager.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the reactnativeactivity@0.0.1 start script 'node_modules/react-native/packager/packager.sh'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the reactnativeactivity package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node_modules/react-native/packager/packager.sh
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs reactnativeactivity
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls reactnativeactivity
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\reactnative\Demo1\npm-debug.log
`
