### ISSUE TITLE
Expo not responding with console.log statement in ref

### ISSUE THREAD

**Issue by James2516** [facebook/react-native#15383]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

1. `react-native -v`:  
react-native-cli: 2.0.1
react-native: 0.45.1
2. `node -v`: v6.11.0
3. `npm -v`: 3.10.10
4. `yarn --version`:

Then, specify:

- Target Platform: Android

- Development Operating System: Windows

- Build tools: 

### Steps to Reproduce

(Write your steps here:)

1. Clone https://github.com/James2516/drawer-app
2. npm install && npm start
3. remove `console.log(this.drawer);` from https://github.com/James2516/drawer-app/blob/master/src/components/Main.js#L15
4. App now loads in Expo.
5. put  `console.log(this.drawer);` back to the same place.
6. Expo will never load (not responding)

### Expected Behavior

Expo should load even with console.log statement

### Actual Behavior

Expo not responding

### Reproducible Demo

see above

**Comment by skevy** [comment]
For Expo-related issues, please open an issue in https://github.com/expo/expo/issues. Thanks!

**Comment by JulianKingman** [comment]
https://github.com/expo/expo/issues/466
