### ISSUE TITLE
Can't use Intl.NumberFormat without Debug JS Remotely turned on

### ISSUE THREAD

**Issue by vendramini** [facebook/react-native#15382]
### Is this a bug report?

I think so.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes.

### Environment

1. `react-native -v`: 0.46.4, cli: 2.0.1
2. `node -v`: 8.2.1
3. `npm -v`: 5.3.0

Then, specify:

- Target Platform: Both, but I just tested on Android for now.

- Development Operating System: Linux Mint 17

- Build tools: I use JetBrains PHPStorm to code. Build with default react-native run-*

### Steps to Reproduce

(Write your steps here:)

1. Try to use a simple code: 
```javascript
export const formatReal = (value) => {
    const formatter = new Intl.NumberFormat('pt-BR', {
        style: 'currency',
        currency: 'BRL',
        minimumFractionDigits: 2,
    });

    return formatter.format(value);
}
```
2. Works if the debugger is conected.
3. Turn off debugger from device.
4. Explodes an error: `"Can't find variable: Intl"`.

**Comment by hey99xx** [comment]
It's very possible that Chrome has `Intl` defined, but Android JSC engine which is closer to iOS 8's JSC engine doesn't. This is not a bug with react-native; you'll always see newer JS variables / functions while working with a debugger that what ships with your app. For example `localeCompare` would also behave differently according to https://github.com/facebook/react-native/issues/12597

You'll need to polyfill `Intl` on Android with a package such as https://github.com/andyearnshaw/Intl.js/

**Comment by newyankeecodeshop** [comment]
You can also use SoftwareMansion's work which brings an updated JavaScriptCore to Android:
https://github.com/SoftwareMansion/jsc-android-buildscripts

The version roughly matches the JavaScriptCore bundled with iOS 10.3, so it has many of the modern JavaScript APIs, including `Intl`. Note that there is a special build that includes the full locale stack. I've started using this in a React Native project, and it works very well.

**Comment by vendramini** [comment]
@newyankeecodeshop very interesting, I will use this on future apps.

I solved using @hey99xx solution. I'm just importing intl and specifics locales.

Thank you, guys!
