### ISSUE TITLE
On iPhone 6 Plus/6s Plus/7 Plus the Zoom options affects font of text, and allowFontScaling doesn't work

### ISSUE THREAD

**Issue by vmacavero** [facebook/react-native#15386]
### Is this a bug report?

Yes, sort of, anyway something we should clarify

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

1. `react-native -v`:
react-native-cli: 1.2.0
react-native: 0.46.4

2. `node -v`:
v6.9.1

3. `npm -v`:
4.0.5

Then, specify:

- Target Platform:
iOS

- Development Operating System:
macOS Sierra 10.12.6

- Build tools:
Xcode

### Steps to Reproduce

(Write your steps here:)

1. Create a simple app with fixed font, something like 

https://snack.expo.io/ry7LNPVv-

### Expected Behavior

the font should be fixed

### Actual Behavior

the font is bigger than expected

http://imgur.com/a/BxwWW

[http://imgur.com/a/BxwWW](url)

**I know the problem is caused by setting Zoom in iphone Plus family by setting Display Zoom settings to "Zoomed" instead of "Standard"**

### Reproducible Demo

https://snack.expo.io/ry7LNPVv-

But i used react-native init on a fresh new project

Thanks.

Victor

**Comment by skevy** [comment]
The `allowFontScaling` is not affected by display zoom -- only by "dynamic text" (General -> Accessibility -> Larger Text). If the user has display zoom enabled, I'm not aware of a way (even in native iOS) to keep things the same size.

**Comment by vmacavero** [comment]
@skevy is there a react-corresponding of : [https://stackoverflow.com/questions/40864262/swift-3-check-if-iphone-6-7-and-6-7plus-display-is-in-standard-or-zoomed-mode#](url)  ?

Thanks.
