### ISSUE TITLE
  Expo is not making live changes.

### ISSUE THREAD

**Issue by Albinzr** [facebook/react-native#15385]
### Is this a bug report?

No

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

1. `react-native -v`:0.46.4
2. `node -v`:v8.1.2
3. `npm -v`:5.3.0
4. `yarn --version`:

Then, specify:

- Target Platform: iOS & Android 

- Development Operating System: macOS

- Build tools: No

### Steps to Reproduce

1.Run code with npm start
2.When you make change in code some time live update stop working
3.Once it stop live update it wont work again until you restart it

### Expected Behavior

For live update to work fine, also if not working show proper notification or error

### Actual Behavior

Stuck in previous error state and wont update after

**Comment by skevy** [comment]
Hi @Albinzr, I'd recommend that you make an issue on https://github.com/expo/expo/issues -- this repo doesn't deal with Expo-related issues.
