### ISSUE TITLE
console.log("some text") does not get printed to Chrome console

### ISSUE THREAD

**Issue by andidev** [facebook/react-native#15398]
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.47.1
2. `node -v`:
v7.10.0
3. `npm -v`:
4.2.0
4. `yarn --version`:
0.27.5

Then, specify:

- Target Platform: iOS and Android

- Development Operating System:
macOS 10.12.6

- Build tools:
Chrome 60.0.3112.90

### Steps to Reproduce

(Write your steps here:)

1. Create a new react native project with `react-native init NewProject`
2. Add a console print to index.ios.js and index.android.js in the render method, e.g. 
```javascript
...
export default class NewProject extends Component {

  render() {
    console.log("This should be printed in console!");
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit index.ios.js
        </Text>
        <Text style={styles.instructions}>
          Press Cmd+R to reload,{'\n'}
          Cmd+D or shake for dev menu
        </Text>
      </View>
    );
  }
}
...
```
3. Run `react-native run-ios` from project root
4. Enable Remote Debugging
5. Open the console in Chrome
6. Refresh app and nothing gets printed

### Expected Behavior

In step 6 the text `This should be printed in console!` should have been printed to Chrome console

### Actual Behavior

Nothing gets printed to console.
I think the issue may be related to the Chrome release since it was after an upgrade it stopped working.

### Reproducible Demo

https://github.com/andidev/react-native-console-log-bug-example-project

**Comment by andidev** [comment]
No issue here, for some reason a console filter where applied. I how no idea how though. Closing this.

**Comment by AlanFoster** [comment]
-sigh-

I ran into the exact same problem:

![image](https://user-images.githubusercontent.com/1271782/29233969-fa4c0358-7eeb-11e7-9f7d-87086a8433d0.png)

**Comment by tlloydukdev** [comment]
Me too all of a sudden

**Comment by stanshivam** [comment]
Same Issue

**Comment by Clarkbaum** [comment]
yeah strange same thing happened to me. thankfully i found this thread so I bothered checking the filters

**Comment by dmatora** [comment]
having same problem, no filtering enabled

**Comment by dmatora** [comment]
solution was to run debug mode (production clears console.log while minifying the code)
