### ISSUE TITLE
[Perf] Baseline CPU Usage

### ISSUE THREAD

**Issue by vishnevskiy** [facebook/react-native#1539]
It seems that any react-native app uses 4% CPU even when idle even when in Release.

https://www.dropbox.com/s/plsvxh7r15bpha9/Screenshot%202015-06-06%2020.00.45.png?dl=0

I profiled in Instruments (both my own app and UIExplorer) and it seems that jsThreadUpdate is the one responsible. Seems to be constantly looking up module names and dispatching to RCTEventDispatcher and RCTTimer (even when they have no work).

https://www.dropbox.com/s/u5mtztcltk1c884/Screenshot%202015-06-06%2020.02.27.png?dl=0

This may very well be intended? This was done on an iPhone 6 so I assume it can only be worse on lower end devices.

**Comment by ide** [comment]
4% CPU usage when the app isn't doing anything is high. The run loop shouldn't do real work if there are no tasks for it.

**Comment by tadeuzagallo** [comment]
ListView has a `setInterval` of 20ms used to check items that are on screen. I'm not sure it's still necessary, I'll look into it.

**Comment by tadeuzagallo** [comment]
Sorry, my mistake, it has already been removed recently, but we still have to go through the modules that implement `RCTFrameUpdateObserver`, that includes `RCTTimer` and `RCTEventDispatcher`, I'll see if we can avoid it.

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/perf-baseline-cpu-usage

**Comment by strefethen** [comment]
Was trying to make some headway with UI automation of a hybrid RN app but it looks like this idle CPU usage prevents Apple's automation support from detecting the app is actually idle leading to: "App failed to quiesce within 30.0s". I've been looking for a means of tweaking what the automation framework needs to detect idle in terms of CPU.

**Comment by jrz** [comment]
For me an idle app (just some views, no logic) takes 8%
