### ISSUE TITLE
[NavigatorIOS] How can I hide NavigatorIOS in child page when NavigatorIOS push?

### ISSUE THREAD

**Issue by maplebaby** [facebook/react-native#1540]
In 0.6.0-rc NavigatorIOS background can't be transparent, so I want to hidden it in the children page, but I have no idea! How can I make page like the follow picture?
![img_3599](https://cloud.githubusercontent.com/assets/2143705/8022688/f4bd4194-0d15-11e5-9e6e-27eb13cea49e.jpg)

**Comment by JonasJonny** [comment]
You should use custom Navigator.
For an example https://github.com/Kureev/react-native-navbar and push without navigationBar.

**Comment by brentvatne** [comment]
Also, this is a dup of #846

**Comment by Iragne** [comment]
or patch navigatorios in my next PR
