### ISSUE TITLE
ios menu debug crash!

### ISSUE THREAD

**Issue by wuyunqiang** [facebook/react-native#15404]
### Is this a bug report?
 no

### Environment

1. `react-native -v`:0.46.4
2. `node -v`:v8.0.0
3. `npm -v`:5.0.1
4. `yarn --version`:0.24.5

- Target Platform: iOS
- Development Operating System: macOS
- Build tools: Xcode

### Steps to Reproduce
1.react-naitve init xxx
2.copy xxx to somewhere path
3.cd somewhere and run ios

### Expected Behavior
![reload](https://user-images.githubusercontent.com/13480948/29061745-ae044c2c-7c51-11e7-893b-84b2e1f907cc.png)

### Actual Behavior
onclick debug JS Remotely
not open chrome and show me bug.
![hahahadebug](https://user-images.githubusercontent.com/13480948/29061760-bafaa610-7c51-11e7-928f-7d09d16bc9e5.png)

![debugbughaha](https://user-images.githubusercontent.com/13480948/29061765-c1e31f8e-7c51-11e7-8f67-d3a0bbe58917.png)

android is right.

**Comment by hramos** [comment]
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

**Comment by wuyunqiang** [comment]
I have description details it.
it is all of my steps.
