### ISSUE TITLE
Build iOS Release error

### ISSUE THREAD

**Issue by pohodnya** [facebook/react-native#15410]
### Environment
1. react-native-cli: 2.0.1
react-native: 0.47.1
2. node: v8.2.1
3. npm: v5.3.0
4. yarn: 0.20.3

- Target Platform: iOS
- Development Operating System: MacOS

### Steps to Reproduce

1. react-native init rn0471_build_ios_release_error_reproduce
2. open .xcodeproj file
3. edit scheme -> select "release" build configuration
4. build & run in simulator

### Actual Behavior
Build failed error in XCode:

```
+ DEST=/Users/alekseypokhodnya/Library/Developer/Xcode/DerivedData/rn0471reproduce-fdeyxrhuiruhnzgprfosmoijckya/Build/Products/Release-iphonesimulator/rn0471reproduce.app
+ [[ Release = \D\e\b\u\g ]]
+ BUNDLE_FILE=/Users/alekseypokhodnya/Library/Developer/Xcode/DerivedData/rn0471reproduce-fdeyxrhuiruhnzgprfosmoijckya/Build/Products/Release-iphonesimulator/rn0471reproduce.app/main.jsbundle
+ node /Users/alekseypokhodnya/RubymineProjects/rn047-fail-test/rn0471reproduce/node_modules/react-native/local-cli/cli.js bundle --entry-file index.ios.js --platform ios --dev false --reset-cache --bundle-output /Users/alekseypokhodnya/Library/Developer/Xcode/DerivedData/rn0471reproduce-fdeyxrhuiruhnzgprfosmoijckya/Build/Products/Release-iphonesimulator/rn0471reproduce.app/main.jsbundle --assets-dest /Users/alekseypokhodnya/Library/Developer/Xcode/DerivedData/rn0471reproduce-fdeyxrhuiruhnzgprfosmoijckya/Build/Products/Release-iphonesimulator/rn0471reproduce.app
/Users/alekseypokhodnya/RubymineProjects/rn047-fail-test/rn0471reproduce/node_modules/metro-bundler/src/lib/Terminal.js:141
    this._nextStatusStr = util.format(format, ...args);
                                              ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/alekseypokhodnya/RubymineProjects/rn047-fail-test/rn0471reproduce/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/alekseypokhodnya/RubymineProjects/rn047-fail-test/rn0471reproduce/node_modules/react-native/local-cli/server/runServer.js:18:18)
    at Module._compile (module.js:409:26)
+ [[ false != true ]]
+ [[ ! -f /Users/alekseypokhodnya/Library/Developer/Xcode/DerivedData/rn0471reproduce-fdeyxrhuiruhnzgprfosmoijckya/Build/Products/Release-iphonesimulator/rn0471reproduce.app/main.jsbundle ]]
+ echo 'error: File /Users/alekseypokhodnya/Library/Developer/Xcode/DerivedData/rn0471reproduce-fdeyxrhuiruhnzgprfosmoijckya/Build/Products/Release-iphonesimulator/rn0471reproduce.app/main.jsbundle does not exist. This must be a bug with'
error: File /Users/alekseypokhodnya/Library/Developer/Xcode/DerivedData/rn0471reproduce-fdeyxrhuiruhnzgprfosmoijckya/Build/Products/Release-iphonesimulator/rn0471reproduce.app/main.jsbundle does not exist. This must be a bug with
+ echo 'React Native, please report it here: https://github.com/facebook/react-native/issues'
React Native, please report it here: https://github.com/facebook/react-native/issues
+ exit 2
```

### Reproducible Demo
https://github.com/pohodnya/rn0471_build_ios_release_error_reproduce

**Comment by chirag04** [comment]
what does your babelrc file look like?

**Comment by pohodnya** [comment]
@chirag04, Full project you can see [here](https://github.com/pohodnya/rn0471_build_ios_release_error_reproduce), .babelrc [here](https://github.com/pohodnya/rn0471_build_ios_release_error_reproduce/blob/master/.babelrc)

**Comment by sanyam-coursera** [comment]
Seeing this as well after upgrading from 0.42 -> 0.46.x .

**Comment by pohodnya** [comment]
This is a critical problem for me. When can you solve it?

**Comment by timvansteenis** [comment]
I had the exact same problem. But I didn't upgrade my project or anything, it just stopped working.

After I removed my NVM it worked again.

**Comment by asifmahmud** [comment]
I'm experiencing the same problem, except mine happens when I run `react-native init <project-name>`
@timvansteenis, What do you mean by removing the NVM? the node version manager?

**Comment by voidstarfire** [comment]
Same problem with Android, stopped our automated pipeline for QA. Critical.

**Comment by gino8080** [comment]
@timvansteenis  what you mean removed my NVM?

could you please explain?

thx

**Comment by timvansteenis** [comment]
@gino8080 I removed my Node Version Manager. I guess the script was somehow using another version of Node.

The script that resulted in the error (when run from XCode) worked fine when i ran it from the terminal. That gave me a clue that it probably wasn't a bug in RN.

**Comment by tabrindle** [comment]
This appears to not be a bug in React Native, but a problem with how your environment is setup. 

This is the script that xcode uses to determine which binary to use: 
https://github.com/facebook/react-native/blob/6e99e314b232c315628c31f97a865c17c071ad23/scripts/react-native-xcode.sh

Notice you can explicitly specify a NODE_BINARY to use via env var. To debug, you can also compare which binary the script is pointing to by using `which node` inside of this script, and inside your terminal. 

Mine for instance works fine like this:

`/Users/tabrindle/.nvm/versions/node/v7.10.0/bin/node`

**Comment by pohodnya** [comment]
@tabrindle yes, you are right. I find in my nvm list node@4.5.0 with default alias.
Yes you are right.
As a result, the following steps helped for me
1. completely remove the node from the mac os system with comand:
`sudo rm -rf /usr/local/{lib/node{,/.npm,_modules},bin,share/man}/{npm*,node*,man1/node*}`
2. delete all node versions from nvm
3. `nvm install v6.10.0`
4. `nvm alias default 6.10.0`

**Comment by tabrindle** [comment]
Glad I could help! Thanks for documenting what you did.

**Comment by LivioGama** [comment]
I had to change `.babelrc` file to :
`{
  "presets": ["react-native"],
  "plugins": ["transform-decorators-legacy"],
  "sourceMaps": true
}
`
