### ISSUE TITLE
InteractionManager.runAfterInteraction(callback)  callback sometimes doesnot work????

### ISSUE THREAD

**Issue by mjylfz** [facebook/react-native#15418]
when I use **InteractionManager.runAfterInteraction(callback)** callback sometimes does not implemented.
It was usually happened the first time I open the app.When I kill the Process and Restart it，it works.
Sorry about my poor english.Please help me.

**Comment by zhuyifan2013** [comment]
yes, you have better do not use this method .
Please refer to https://github.com/facebook/react-native/issues/8624 
@mjylfz

**Comment by mjylfz** [comment]
@zhuyifan2013 我们公司用开发rn，大量使用了这个InteractionManager.runAfterInteraction。如果不使用如何避免动画掉帧？

**Comment by nihgwu** [comment]
@mjylfz try to use native animation where possible

**Comment by zhuyifan2013** [comment]
@mjylfz  避免在 JS 线程上处理耗时的操作，使用 Native 的多线程处理而不是用 JS 处理。

**Comment by DevArenaCN** [comment]
https://github.com/facebook/react-native/issues/8624 See the 2nd comment on this issue. This is what works for me in my case.
