### ISSUE TITLE
multiline TextInput doesn't grow properly in React Native 0.47.1

### ISSUE THREAD

**Issue by dannyharding10** [facebook/react-native#15415]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

1. `react-native -v`: 0.47.1
2. `node -v`: v7.10.0
3. `npm -v`: 4.2.0
4. `yarn --version`: N/A

- Target Platform: both Android and iOS

- Development Operating System: macOS Sierra 10.12.6

- Build tools: I'm only using `react-native run-ios` and `react-native run-android` to run my project. I use Android Studio to open the Android emulator.

### Steps to Reproduce

1. Create a project with react-native 0.47.1 (`react-native init BadTextInput`)
2. Insert a TextInput component. 
3. Add `multiline={true}` as a prop
3. Run the app
4. Enter enough text in the TextInput for the text to wrap

### Expected Behavior

The text should wrap and the TextInput component should grow once the text reaches the end of the TextInput. This behavior works as expected in React Native 0.46.4.

### Actual Behavior

The text wraps at the proper place, but the height of the TextInput begins to grow before the text wraps.  This creates a lot of whitespace inside the text input below the text. The TextInput has similar behavior in both iOS and Android

![simulator screen shot aug 8 2017 11 10 16 am](https://user-images.githubusercontent.com/11875246/29084795-7341681c-7c2a-11e7-847f-deaf5b1a9b4b.png)

![simulator screen shot aug 8 2017 11 12 46 am](https://user-images.githubusercontent.com/11875246/29084818-844615ae-7c2a-11e7-899b-88d6fd4e58e8.png)

![simulator screen shot aug 8 2017 11 16 46 am](https://user-images.githubusercontent.com/11875246/29085017-13655d44-7c2b-11e7-91ce-66b5e7398721.png)

### Reproducible Demo

https://snack.expo.io/H1SjowDwW

This Snack has the minimum amount of code I used to reproduce the issue. However, the error doesn't occur using this Snack because it's using React Native 0.46. The error is very easily reproducible if you just copy this code into a new React Native project that uses 0.47.1.

#### Code
This is the code to put into `index.ios.js` or `index.android.js` to reproduce the issue:

```
import React, { Component } from 'react';
import { TextInput, StyleSheet, AppRegistry } from 'react-native';

export default class BadTextInput extends Component {
  render() {
    return (
      <TextInput
        style={styles.textInput}
        multiline={true}
        placeholder={'This text input will act weird on RN 0.47.1'}
      />
    );
  }
}

const styles = StyleSheet.create({
  textInput: {
    borderWidth: 1,
    borderColor: 'black',
    margin: 4,
    marginTop: 24,
    fontSize: 12,
  },
});

AppRegistry.registerComponent('BadTextInput', () => BadTextInput);
```

**Comment by Jeepeng** [comment]
I have the same issue.

**Comment by magicismight** [comment]
Same issue.
Press submit can not insert a new line in TextInput

**Comment by ujenjt** [comment]
Yes, I have the same issue too 🤔

**Comment by shergin** [comment]
It was fixed recently. https://github.com/facebook/react-native/commit/603cc48ceba001827d10231d51b4031c7768eef8

**Comment by shergin** [comment]
@magicismight What do you mean?

**Comment by magicismight** [comment]
@shergin 
In 0.47.0 Android I can't insert a line beak in TextInput even if I have set `multiline={true}`

**Comment by shergin** [comment]
Which device/keyboard do you use?

**Comment by shergin** [comment]
@magicismight #12717 ?

**Comment by magicismight** [comment]
@shergin yep
