### ISSUE TITLE
Can't use TouchableBounce

### ISSUE THREAD

**Issue by olivierlesnicki** [facebook/react-native#1542]
I'm using react-native 5.0.0

**Comment by christopherdro** [comment]
Could you please provide a bit more information. Maybe a possible example?

I think your referring to version 0.5.0. Was this working with a pervious version?

**Comment by brentvatne** [comment]
@olivierlesnicki - you can require it using `var TouchableBounce = require('TouchableBounce')` - it isn't currently included in the react-native export.

See [https://rnplay.org/apps/q8c-hg](https://rnplay.org/apps/q8c-hg?autoplay=true) for an example

**Comment by olivierlesnicki** [comment]
I get the following issue when trading a TouchableHighlight with a TouchableBounce
```
undefined is not an object (evaluating RCTAnimationManager.startAnimation)

startAnimation
AnimationExperimental.js:59
```

**Comment by brentvatne** [comment]
@olivierlesnicki - you will need to link `Libraries/Animation/RCTAnimationExperimental.xcodeproj` with your project
