### ISSUE TITLE
RCTEventEmitter bridge is not set

### ISSUE THREAD

**Issue by Symous** [facebook/react-native#15421]
### Is this a bug report?
Not confirm.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes, I have follow all sept of this document of how to use RCTEventEmitter to send event from Native to JS.but still meet this error. 

### Environment

1. `react-native -v`: 0.45.1
2. `node -v`: 8.1.2
3. `npm -v`: 5.30

Then, specify:

- Target Platform: iOS

- Development Operating System:macOS

- Build tools:iOS 10

### Steps to Reproduce

1. Create a helper class that can emit event from iOS native to JS according to the document.
2. invoke sendEventWithName method any where in the code we need to emit event.

### Expected Behavior

JS will receive the event and catch the data.

### Actual Behavior

```oc
[tid:com.facebook.react.ShadowQueue] Exception 'bridge is not set. 
This is probably because you've explicitly synthesized the bridge in RCTCameraEvent, 
even though it's inherited from RCTEventEmitter.'
was thrown while invoking capture on target CameraManager with params (
        {
        audio = 0;
        barCodeTypes =         (
        );
        description = "";
        mirrorImage = 0;
        mode = 1;
        playSoundOnCapture = 1;
        preferredTimeScale = 30;
        quality = 0;
        target = 1;
        title = "";
        totalSeconds = 10;
        type = 1;
    },
    3892,
    3893
)
```
### Reproducible Demo

EventHelper.h
```oc
#import <React/RCTBridgeModule.h>
#import <React/RCTEventEmitter.h>

@interface RCTCameraEvent : RCTEventEmitter<RCTBridgeModule>

@end
```

EventHelper.m
```oc
#import "RCTCameraEvent.h"

@implementation RCTCameraEvent

RCT_EXPORT_MODULE();

- (NSArray<NSString *> *)supportedEvents
{
    return @[@"CustomEvent"];
}

- (void)sendEvent2JS
{
    [self sendEventWithName:@"CustomEvent" body:@{@"name": @"111"}];
}

@end
```

invoke send event method in code 

```oc
RCTCameraEvent * cameraEvent = [[RCTCameraEvent alloc]init];
[cameraEvent sendEvent2JS];
```

All I want to do is create a helper class so that I can invoke the send event method anywhere I need.

I have look into many issues (#8714) and search related answer on Google and stackoverflow but still can not found a perfect solution using RCTEventEmitter. there are lots of developers like me meet this problem and react native haven't provide us a standard code demo or completely document.

**Comment by hfossli** [comment]
You shouldn't init `RCTCameraEvent` yourself. It will be initialized by react native. You must try to communicate with that instance in some way. For example your `AppDelegate` may send a notification which `RCTCameraEvent` subscribes to on init. You may then forward that information to js using the `[self sendEventWithName:@"CustomEvent" body:@{@"name": @"111"}];`

**Comment by hfossli** [comment]
I agree this is a bit tricky and some help from the framework and documentation would be nice

**Comment by hfossli** [comment]
This is also a very nice way. https://gist.github.com/brennanMKE/1ebba84a0fd7c2e8b481e4f8a5349b99 I think this is exactly what you are looking for?

**Comment by Liqiankun** [comment]
Finally, I got the solution.
```
#import "RNNotification.h"
@implementation RNNotification

RCT_EXPORT_MODULE();

+ (id)allocWithZone:(NSZone *)zone {
    static RNNotification *sharedInstance = nil;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        sharedInstance = [super allocWithZone:zone];
    });
    return sharedInstance;
}

- (NSArray<NSString *> *)supportedEvents
{
    return @[@"EventReminder"];
}

- (void)sendNotificationToReactNative
{
    [self sendEventWithName:@"EventReminder" body:@{@"name": @"name"}];
}
```
When you use it!
```
RNNotification *notification = [RNNotification allocWithZone: nil];
[notification sendNotificationToReactNative]
```

**Comment by hfossli** [comment]
Yep, singleton pattern is one option.

**Comment by huyhai** [comment]
you save my day @Liqiankun 
thank you!

**Comment by JefferyHus** [comment]
@Liqiankun I did the same thing as you, still getting a damn error in my AppDelegate `No visible @interface for 'RTNEventManager' declares the selector 'socketOpenConnection:userNumber:'`

These are my files:

`RTNEventManager.h`
```objectivec
#import <React/RCTBridgeModule.h>
#import <React/RCTEventEmitter.h>

@interface RTNEventManager : RCTEventEmitter <RCTBridgeModule>

@end
```

`RTNEventManager.m`
```objectivec
#import "RTNEventManager.h"

@implementation RTNEventManager

RCT_EXPORT_MODULE();

+ (id)allocWithZone:(NSZone *)zone {
    static RTNEventManager *sharedInstance = nil;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        sharedInstance = [super allocWithZone:zone];
    });
    return sharedInstance;
}

- (NSArray<NSString *> *)supportedEvents
{
  return @[@"onOpened"];
}

- (void)socketOpenConnection
{
  [self sendEventWithName:@"onOpened" body:@{@"callername": @"205-966-1916", @"username": @"9542493959"}];
}

@end
```

and then inside my AppDelegate.m I do this

```objectivec
#import "RTNEventManager.h"
...
RTNEventManager *manager = [RTNEventManager allocWithZone: nil];
[manager socketOpenConnection];
```
And when building it pops up the same error again and again.

**Comment by ogil7190** [comment]
expose an interface like this

- (void) socketOpenConnection 

in your ".h" file
