### ISSUE TITLE
[Android] CameraRoll groupTypes not supported on Android 

### ISSUE THREAD

**Issue by filippofilip95** [facebook/react-native#15423]
### Is this a bug report?

NO

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

YES

### Environment

1. `react-native: 0.45.1`:
2. `node: 8.0.0`:
3. `yarn: 0.27.5`:

- Target Platform:
Android

- Development Operating System:
macOS

- Build tools:
Android Studio

### Steps to Reproduce

1. Import CameraRoll API.
2. I used it like this
```
    try {
      const photos = await CameraRoll.getPhotos({
        first: 10,
        groupTypes: 'Album'
      });
    } catch (err) {
      console.log(err);
    }
```

### Expected Behavior

Returning photos in groups by album.

### Actual Behavior

Throws error  `groupTypes not supported on Android`

![20727789_1733841826920219_314253407_o](https://user-images.githubusercontent.com/10739349/29108914-3a9cb95a-7ce1-11e7-8242-cc3896f6d893.jpg)

### Reproducible Demo

Don't forget to switch to Android.

https://snack.expo.io/HkrqfEODZ

### My question
Is implementation of groupTypes for Android planned in the near future ? 
Or it's there another workaround ?
Thank for answer.

**Comment by hramos** [comment]
Thanks for opening the issue! As it happens, we're using GitHub to track bugs in React Native. If you'd like to submit this as a feature request, please go ahead and create an entry on [Canny](https://reactnative.canny.io/feature-requests). It has a voting system and if the feature gets a good amount of votes, it will have a greater chance of being implemented by the community. Closing this now, thanks for understanding!
