### ISSUE TITLE
PermissionsAndroid permission not granted on APIs 22 and below

### ISSUE THREAD

**Issue by aritradgupta** [facebook/react-native#15420]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes.

### Environment

1. `react-native -v`: 0.46.4
2. `node -v`: 8.0.0
3. `npm -v`: 5.0.2
4. `yarn --version`: 0.24.6

Then, specify:

- Target Platform: Android

- Development Operating System: MacOS

 Android SDK
- Build tools: Gradle

### Steps to Reproduce

(Write your steps here:)

1. Create an async function to request permission. PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE
2. Call this function inside onPress prop of TouchableOpacity
3. The function returns a prompt asking for the user to agree or deny the permission like an android app does based on the new permission model. But while testing on a device which has Android 5.1.1 installed the request function does not return the string "granted". Therefore the if statement which checks for the condition based on this returned string value returns false.

### Expected Behavior

In Android 5.1.1 or APIs before that PermissionsAndroid returns true for check and request calls. This means if I write my actual functionality inside an if statement with the condition PERMISSIONS.RESULT.GRANTED === permission, it should pass as true. 

### Actual Behavior

Whenever the async function is called, the IF statement which checks if the request function returned the string value "granted" returns False. This happens in devices with Android Lollipop installed or previous versions.

**Comment by gourav-singhal** [comment]
Did you get any solution for this?
