### ISSUE TITLE
How to make a Minimize Button (Home Button Click)

### ISSUE THREAD

**Issue by ashafizullah** [facebook/react-native#15425]
**Is this a bug report?**
No.

**Have you read the Contributing Guidelines?**
Yes.

**Problem**
Hi. I want to try make a **minimize button** on the header with Icon. So, the question is, when minimize icon clicked, how to make the event handle to minimize app like we pressed hardware home button on our Android smartphone?

Thank you before. 👍

**Comment by thotegowda** [comment]
Write your own native module and fire home intent.

**Comment by aaronschubert0** [comment]
@facebook-github-bot stack-overflow

**Comment by ashafizullah** [comment]
Sorry, please explain to me how to fire home button with code. Thank you.

**Comment by charpeni** [comment]
@facebook-github-bot stack-overflow
