### ISSUE TITLE
Unable to symbolicate stack trace bundle was not loaded from the packager (Android)

### ISSUE THREAD

**Issue by lugrugzo** [facebook/react-native#15431]
### Is this a bug report?

Yes.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes.

### Environment

1. `react-native -v`: 0.46.4
2. `node -v`: v.7.7.2
3. `npm -v`: 4.1.2

Then, specify:

- Target Platform: Android
- Development Operating System: Mac OS
- Build tools: We only able to test in android using Android SDK (this problem occurs in a pyhsical device).

### Steps to Reproduce

(Write your steps here:)

1. react-native start
2. react-native run-android
3. No error in physical device, only warning and weird screen (screenshot: https://i.hizliresim.com/BAQg6p.jpg)
When 'Reload' it gives this error: https://i.hizliresim.com/293412.jpg

### Expected Behavior
In IOS and Android emulator it's working

**Comment by ahmeturganci** [comment]
I'm having same problem

**Comment by ramintagizade** [comment]
same problem

**Comment by ozergul** [comment]
Interestingly same problem. Is react-native broken?

**Comment by thotegowda** [comment]
+1

**Comment by Zcgong** [comment]
+1 the same on iOS

**Comment by hellozhangran** [comment]
+1 the same on iOS

**Comment by cronos88** [comment]
Same problem on Android: 
Unable to symbolicate stack trace. The stack is null.

"react": "16.0.0-alpha.12",
"react-native": "0.48.4"
Node version: 8.6.0
NPM version: 5.4.2

OS: Linux Elementary OS

**Comment by anshchauhan** [comment]
+1 checked on android

**Comment by nageshwar-uideveloper** [comment]
i am also facing this issue, any ideas/fixes?

**Comment by T-Minus14** [comment]
+1 on android physical device

**Comment by psikosen** [comment]
Same for me on an android device.

**Comment by DevBkIL** [comment]
+1 checked on android

**Comment by spencewine** [comment]
+1, same issue on iOS

**Comment by medidt** [comment]
Same issue on Android

```
react-native -v:
    react-native-cli: 2.0.1
    react-native: 0.41.0
node -v: v8.7.0
npm -v: 5.5.1
```

**Comment by TomKarachristos** [comment]
+1 checked on android

**Comment by finetimi** [comment]
@medidt  
`rm -rf ~/.rncache`
`npm start -- reset-cache`
`react-native run-[ios/android]`

**Comment by jayeshjain24** [comment]
+1 checked on android

**Comment by abhishek0058** [comment]
+1

**Comment by dben89x** [comment]
+1

**Comment by opensol2018** [comment]
+1

**Comment by ghariharan** [comment]
+1

**Comment by Benzer1406** [comment]
Same problem on both iOS and Android!

**Comment by wprater** [comment]
We are seeing this on debug builds which we also FORCE_BUNDLING on `0.53.0`

**Comment by tramorphius** [comment]
Yes. it is. This problem still exists.

**Comment by kosmicbird** [comment]
...problem still exists.

I only get the warning when using Hot Reload after I've made a typing error. Everything else works fine and no warning when not in HR mode. Guess this is more irritating than app-breaking.

**Comment by sandeep0607** [comment]
+1 problem still exists in version 0.55

**Comment by seewah48** [comment]
+1 same issue 0.55.3

**Comment by gbsimon87** [comment]
+1 0.55.4

**Comment by minisahex** [comment]
+1 only when Hot Reloading

**Comment by thu-sama** [comment]
+1 iOS Hot Reload

**Comment by nerjok** [comment]
was this gone with rn 0.56?

**Comment by lustigdev** [comment]
Hacky way to ignore:

Place `console.disableYellowBox = ["Unable to symbolicate"];` anywhere in your code.

I put it at the top of App.js for now and will put it in a better place later.

**Comment by Drisicus** [comment]
@lustigdev thanks, until is fixed we don't have that annoying message around 👍

**Comment by gbsimon87** [comment]
As you can see, your app needs more security.
More to come tomorrow.

**Comment by lustigdev** [comment]
@gbsimon87 Sorry, what do you mean?

**Comment by mehmetyilmaz001** [comment]
same problem here. very annoying thing

**Comment by leticiamrosa** [comment]
i've the same problem here yet

**Comment by JackKenney** [comment]
+1 -- rn version 0.57.8

**Comment by craigcosmo** [comment]
got this problem on ios

React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (12) x64 Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz
      Memory: 305.79 MB / 24.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.6.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 28
        Build Tools: 28.0.3
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by purr-kyungmin** [comment]
Is this issue has been solved or is there anyone who solved it?
