### ISSUE TITLE
Text Font Scaling should allow thresholds

### ISSUE THREAD

**Issue by Jpoliachik** [facebook/react-native#15433]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

1. `react-native -v`: 0.42.3
2. `node -v`: 8.2.1
3. `npm -v`: 5.3.0
4. `yarn --version` 0.19.1

- Target Platform: iOS

- Development Operating System: macOS

- Build tools: Xcode

### Steps to Reproduce

On iOS, set the Accessibility Text as large as possible. 
(iOS Settings -> General -> Accessibility -> Larger Text -> Larger Accessibility Sizes -> Drag to Far Right)

(Android accessibility scaling works as expected, this is an iOS-only issue)

React Native scaled text becomes WAY larger than expected, to the point where the view is broken. 

### Expected Behavior

With the largest accessibility text setting possible, apps are expected to scale the text, but still be useable. 
React Native views are effectively useless at this massive level of font scaling. 

Font Scaling on `<Text>` is a boolean, but there should be a way to set thresholds or customize the level of scaling based on the accessibility setting.

### Actual Behavior

See the current Instagram app's Push Notification Settings view (which uses React Native). 
For a reproducible demo, navigate to the current *Live* Instagram app with the largest accessibility setting and you'll see this: 

This view is essentially broken. 
![image](https://user-images.githubusercontent.com/5148640/29126613-d9c15dbe-7cec-11e7-9ae4-6edaa3e892e4.png)

**Comment by Jpoliachik** [comment]
`RCTAccessiblityManager.m` sets the font scaling multipliers. These values need to be customizable: 

```- (NSDictionary<NSString *, NSNumber *> *)multipliers
{
  if (_multipliers == nil) {
    _multipliers = @{UIContentSizeCategoryExtraSmall: @0.823,
                     UIContentSizeCategorySmall: @0.882,
                     UIContentSizeCategoryMedium: @0.941,
                     UIContentSizeCategoryLarge: @1.0,
                     UIContentSizeCategoryExtraLarge: @1.118,
                     UIContentSizeCategoryExtraExtraLarge: @1.235,
                     UIContentSizeCategoryExtraExtraExtraLarge: @1.353,
                     UIContentSizeCategoryAccessibilityMedium: @1.786,
                     UIContentSizeCategoryAccessibilityLarge: @2.143,
                     UIContentSizeCategoryAccessibilityExtraLarge: @2.643,
                     UIContentSizeCategoryAccessibilityExtraExtraLarge: @3.143,
                     UIContentSizeCategoryAccessibilityExtraExtraExtraLarge: @3.571};
  }
  return _multipliers;
}
```

That way, we can set the ExtraLarge* values to stop at 2x, rather than scale to 3.57x - which is WAY too large for most applications. 


What mechanism should we use to allow customizability here?

**Comment by Jpoliachik** [comment]
I created a temporary workaround for myself by swizzling the `multipliers` getter. If anyone is interested, here's the code: https://gist.github.com/Jpoliachik/ed5cb38b480bc544427ce0db529786bf

**Comment by sahrens** [comment]
Note you should also be able to tune these in JS with `AccessibilityManager.setAccessibilityContentSizeMultipliers`
