### ISSUE TITLE
[npm] Stupid question: Why is `npm update react-native` not updating?

### ISSUE THREAD

**Issue by jaygarcia** [facebook/react-native#1543]
Wasn't 0.6.0 released a few days ago?  My project just won't update.

Someone please help me understand what i'm  doing wrong here.

```
jgarcia-15in:KGMP jgarcia$ npm update react-native
npm WARN engine stacktrace-parser@0.1.1: wanted: {"node":"~0.10"} (current: {"node":"0.12.0","npm":"2.5.1"})
 
> ws@0.4.31 install /www/ios/KeyGenMusicPlayer/KGMP/node_modules/react-native/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
react-native@0.4.4 node_modules/react-native
├── absolute-path@0.0.0
├── stacktrace-parser@0.1.1
├── graceful-fs@3.0.8
├── react-timer-mixin@0.13.1
├── underscore@1.7.0
├── image-size@0.3.5
├── debug@2.1.3 (ms@0.7.0)
├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.0.1, supports-color@1.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)
├── yargs@1.3.2
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── worker-farm@1.3.1 (xtend@4.0.0, errno@0.1.2)
├── source-map@0.1.31 (amdefine@0.1.0)
├── promise@7.0.1 (asap@2.0.3)
├── bluebird@2.9.27
├── sane@1.1.2 (watch@0.10.0, minimist@1.1.1, exec-sh@0.2.0, minimatch@0.2.14, fb-watchman@0.0.0, walker@1.0.7)
├── rebound@0.0.12
├── ws@0.4.31 (tinycolor@0.0.1, options@0.0.6, commander@0.6.1, nan@0.3.2)
├── connect@2.8.3 (methods@0.0.1, uid2@0.0.2, fresh@0.1.0, pause@0.0.1, cookie-signature@1.0.1, qs@0.6.5, bytes@0.2.0, buffer-crc32@0.2.1, cookie@0.1.0, send@0.1.2, formidable@1.0.14)
├── uglify-js@2.4.23 (uglify-to-browserify@1.0.2, async@0.2.10, yargs@3.5.4, source-map@0.1.34)
├── jstransform@11.0.1 (object-assign@2.1.1, base62@1.1.0, source-map@0.4.2, esprima-fb@15001.1.0-dev-harmony-fb, commoner@0.10.1)
├── module-deps@3.5.6 (inherits@2.0.1, shallow-copy@0.0.1, minimist@0.2.0, parents@1.0.1, subarg@0.0.1, stream-combiner2@1.0.2, readable-stream@1.0.33, through2@0.4.2, duplexer2@0.0.2, resolve@0.7.4, concat-stream@1.4.8, JSONStream@0.7.4, browser-resolve@1.9.0, detective@3.1.0)
├── react-tools@0.13.2 (jstransform@10.1.0, commoner@0.10.1)
└── joi@5.1.0 (topo@1.0.2, isemail@1.1.1, hoek@2.14.0, moment@2.10.3)
```
Then checking:
```
jgarcia-15in:KGMP jgarcia$ npm list | grep -i react
├─┬ react-native@0.4.4
│ ├── react-timer-mixin@0.13.1
│ ├─┬ react-tools@0.13.2
```

**Comment by christopherdro** [comment]
The latest stable release is 0.5.0.

Did you make sure to update the version inside of package.json?

Afterwards, you can just run `npm update` in the your project directory.

**Comment by brentvatne** [comment]
@jaygarcia - I'd recommend updating the version in `package.json` then just running `npm i` again

**Comment by jaygarcia** [comment]
@christopherdro  @brentvatne that worked. It feels pretty stupid to have to manually update package.json, but it works. =)

Thanks.

**Comment by ivesy85** [comment]
I cant for the life of me get this to work. I navigate to my project folder and change version number in package.json from 0.4.4 to 0.6.0 and then do npm update but it just changes it back to 0.4.4

**Comment by jawadrehman** [comment]
this might help https://github.com/facebook/react-native/issues/1606

**Comment by joshuapinter** [comment]
@jaygarcia I agree. This requires you to know that there _is_ a more recent version, which version number that is, update the `package.json` and then _finally_ go `npm update`.

**Comment by joshuapinter** [comment]
Don't forget to run `react-native upgrade` after `npm update` so your template files are updated, if necessary.

**Comment by joshuapinter** [comment]
FYI, my buddy [EKryski](https://github.com/ekryski) and I were hanging out and he mentioned that NPM has a weird behaviour when the major version is 0.

Basically, when the major version of a package is 0, like React Native is (currently `0.21.0`), then the caret won't do what it typically does when a package's major version is >= 1. It simply ignores the caret and only cares about the specific version you have entered.

So, for packages with a major release of 0 you have a few options, including using `>=` like:

`"react-native": ">=0.21.0"`

And that will update to the latest version using `npm update`.

Or you can manually specify the exact version you want.

Also, a great little npm command is `npm outdated` which shows new versions of your packages:
![screenshot 2016-03-11 11 16 59](https://cloud.githubusercontent.com/assets/180819/13711244/cf4f6e2e-e77a-11e5-95a8-be694e99ccec.png)

The more you know!
![image](https://cloud.githubusercontent.com/assets/180819/13711186/74500790-e77a-11e5-9d51-ddf7041fa614.png)
