### ISSUE TITLE
Tool to detect memory leaks and reference to the source code 

### ISSUE THREAD

**Issue by crazy9code** [facebook/react-native#15430]
### Is this a bug report?

No

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

yes

### Environment

1. `react-native -v`: 0.46.3
2. `node -v`: 7.9.0
3. `npm -v`: 4.6.1
4. `yarn --version`:

Then, specify:

- Target Platform:

- Development Operating System:
macOS

- Build tools:
Xcode
### Steps to Reproduce

(Write your steps here:)

1. I need to detect the memory leaks in js files.
2. links memory leaks to their source code in js files.
3. I'm able to see the memory leaks in memory -> Profiles in Chrome debugging tool, but not able to reference into my react native JavaScript source code.

 I have attached chrome debugger result.

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

![screen shot 2017-08-09 at 4 09 51 pm](https://user-images.githubusercontent.com/16454771/29117808-3da76d7a-7d1d-11e7-993d-7196a998e371.png)

**Comment by hramos** [comment]
Thanks for opening the issue! As it happens, we're using GitHub to track bugs in React Native. If you'd like to submit this as a feature request, please go ahead and create an entry on [Canny](https://reactnative.canny.io/feature-requests). It has a voting system and if the feature gets a good amount of votes, it will have a greater chance of being implemented by the community. Closing this now, thanks for understanding!
