### ISSUE TITLE
VirtualizedList keeps re-rendering forever

### ISSUE THREAD

**Issue by gastonmorixe** [facebook/react-native#15441]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes 

### Environment

1. `react-native -v`: 0.47.1
2. `node -v`: 8.2.1
3. `npm -v`: 5.3
4. `yarn --version`: 0.27.5

Then, specify:

- Target Platform: iOS

- Development Operating System: macOS 10.12.6

- Build tools: Xcode, only tested on iOS 

### Steps to Reproduce

1. Make a `VirtualizedList`

Next demo does not use `data` array but custom data class and assessor. 

https://gist.github.com/gastonmorixe/fb45ded04ff60a420ee09802e569fe0a

### Expected Behavior

VirtualizedList should not re-render if state or props stay the same.

### Actual Behavior

VirtualizedList keeps re-rendering forever without any user interaction, state or props change.

![VirtualizedList Gif demo](http://g.recordit.co/Gd4Q960tXk.gif)

### Reproducible Demo

https://gist.github.com/gastonmorixe/fb45ded04ff60a420ee09802e569fe0a

### Culprit (stack trace)

`VirtualizedList.js`

1. 
```js
    this._updateCellsToRenderBatcher = new Batchinator(
      this._updateCellsToRender,
      this.props.updateCellsBatchingPeriod,
    );
```
2. 
```js
  _updateCellsToRender = () => {
   ....
    this.setState(state => {
```
3.
```js
  componentDidUpdate() {
    this._scheduleCellsToRenderUpdate();
  }
```
4.
```js
  _scheduleCellsToRenderUpdate() {
   ...
    if (hiPri && this._averageCellLength) {
      ....
    } else {
      this._updateCellsToRenderBatcher.schedule(); <<<<<< HERE starts looping again
    }
```

**Comment by tlcheah2** [comment]
@gastonmorixe ,

When you're using React.PureComponent, please do not pass in deeply nested object types as it will only perform shallow equal check. Shallow equal check will always return true for Object and Array types. I did some changes on your gist on the link below. Please tried it out and let me know whether it resolve your concern.

https://gist.github.com/tlcheah2/f043c272003ee988f9fc1979f5000ad2/revisions

Here is reference for React.PureComponent:
https://60devs.com/pure-component-in-react.html

**Comment by cbjs** [comment]
same

**Comment by gastonmorixe** [comment]
@tlcheah2  I don't think it is related to that.
