### ISSUE TITLE
Error when linking react-native-fbsdk

### ISSUE THREAD

**Issue by CSMarco** [facebook/react-native#15449]
### Environment

1. `react-native -v`: react-native-cli: 2.0.1
react-native: 0.44.3
2. `node -v`: v6.11.0
3. `npm -v`: 3.10.10

Then, specify:

- Target Platform: iOS

- Development Operating System: macOS

- Build tools: Xcode

### Steps to Reproduce

(Write your steps here:)

1. rnpm link react-native-fbsdk

### Expected Behavior

Normally it should output something like 'iOS module react-native-fbsdk successfully linked'

### Actual Behavior

<img width="1046" alt="output" src="https://user-images.githubusercontent.com/27492648/29170033-27591428-7dd7-11e7-95a1-98aeb59ab419.png">

If I am trying to use the Facebook Login Button in the App I am just getting a red square instead of the button

### What did I try to fix the issue?

I have gone through a few issue reports on here and on some Stackoverflow questions where other people have experienced similar problems, but none of the things listed below worked for me: 
- Clean Xcode project
- Delete node_modules and run npm install again

**Comment by aphillipo** [comment]
Yes I also have this issue...

**Comment by ngprnk** [comment]
having same issue
