### ISSUE TITLE
I want to hide the status bar with a modal overlay.

### ISSUE THREAD

**Issue by chucky6413** [facebook/react-native#15443]
### Is this a bug report?
no

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?
yes

### Environment

1. `react-native -v`: 0.46.4
2. `node -v`: 8.1.4
3. `npm -v`:5.0.3
4. `yarn --version`: 0.27.5

Then, specify:

- Target Platform:Android

- Development Operating System: macOS

- Build tools: jdk, android sdk

### Steps to Reproduce

(Write your steps here:)

1.

````
<View style={{flex:1}}>
  <View style={{flex:1}}>
    <StatusBar
      backgroundColor={backgroundColor}
      barStyle={barColor === 'light' ? 'light-content' : 'dark-content' }
     />
  </View>
  <Modal
        visible={ this.state.modalVisible }
        transparent={true}
        onRequestClose={() => { this.setModalVisible(false) }}
        >
       <View style={{flex:1}}>
       </View>     
  </Modal>
</View>
````
2. I want to hide the status bar with a modal overlay.
 But as shown in the screenshot below, Modal's overlay does not hide the StatusBar. I want to do it without using the navigator. Why is it not covered? Please help me.

(Write what happened. Add screenshots!)
![image](https://user-images.githubusercontent.com/13410316/29155537-c2bc2856-7dd7-11e7-952c-eaa161855d69.png)

**Comment by ajonno** [comment]
there is a similar ticket here too: #7474

**Comment by chirag04** [comment]
@facebook-github-bot duplicate #7474

**Comment by kallayyash** [comment]
instead this true transparent={true} make it as transparent={false}
