### ISSUE TITLE
The problem with 'SectionList' 'SectionSeparatorComponent' on version 0.47.0

### ISSUE THREAD

**Issue by RoarRain** [facebook/react-native#15442]
On version 0.44.3  between sectionHeader and item no sectionSeparator，but on version 0.46.0、0.47.0 it is have sectionSeparator，now, i don't want it to show between sectionHeader and item ,what do I do？
0.44.3
Image 
![image](http://upload-images.jianshu.io/upload_images/1414069-e59edd2600056511.gif)

0.47.0

![image](http://upload-images.jianshu.io/upload_images/1414069-6c209fcdb727d47c.png)

thank you!

**Comment by AndsteLyc** [comment]
haha, The problem looks very serious.

**Comment by ddzyndra** [comment]
Try to play with leading/trailing properties in SectionSeparatorComponent

`_renderSectionSeparator = (data) => {
    return (
      <View style={{height: !!data.leadingItem && !!data.trailingSection ? 2 : 0, backgroundColor: '#05A5D1'}}/>
    )
  }`
