### ISSUE TITLE
ListView Blank Top

### ISSUE THREAD

**Issue by kietcroco** [facebook/react-native#15446]
**Is this a bug report?**

Yes

**Have you read the Contributing Guidelines?**

Yes

**Steps to Reproduce**

1. Launch the app.
2. Scroll down
3. Set data ListView

tôi có 1 data khoảng 8 dòng trên listview. khi tôi kéo thanh scroll xuống cuối và gán lại data thành 1 dòng (lọc dữ liệu), sau đó gán lại như cũ thì thanh scroll bị 1 khoản trống, nhưng khi chạm và kéo nhẹ thanh scroll thì nó bình thường trở lại.

> By Google translate
> I have 1 data about 8 lines on the listview. When I drag the scroll bar to the end and reassign the data to a line (filtered data), then reassign the same scroll bar is empty, but when touching and scrolling light scroll bar it is normal again.

Please see at: http://recordit.co/NLWbIAOvrl

### Environment
react-native-cli: 1.0.0
react-native: 0.47.1 and 0.48.0-rc.0
node: v7.4.0
npm: 4.1.1

- Target Platform: android
- Development Operating System: window 7
- Build tools: 25.0.1

  Thanks for helping!

**Comment by hramos** [comment]
Thanks for opening the issue! It does not appear like a community member will be able to reliably reproduce this issue. This may be for several reasons; perhaps it affects a particular app but a minimal repro has not been provided, or the issue may be sporadic. As it happens, we need a concrete set of steps that can demonstrably reproduce the issue as this will allow your fellow community members to validate a fix. We'll close the issue for now, but feel free to submit a new issue once you're able to reliably reproduce the issue locally. Thanks for your understanding!
