### ISSUE TITLE
RN 0.47 seems to be working fine with gradle 4.0 and compileSdkVersion / buildToolsVersion 26

### ISSUE THREAD

**Issue by pocesar** [facebook/react-native#15448]
The build went from 6 minutes (for a 35 file project) down to 24s, on a second wind after the gradle daemon has already started with at least 1500MB memory... 

Maybe encourage new projects to use those optimized settings, since I'm also using a lot of third party android Java modules, with no incompatibilities issues. 

my `build.gradle` looks like this:

```gradle
// Top-level build file where you can add configuration options common to all sub-projects/modules.
ext {
    compileSdkVersion = 26 // Or what version you want (latest is recommended)
    buildToolsVersion = '26.0.1' // same thing
}

subprojects { subproject ->
    afterEvaluate{
        if((subproject.plugins.hasPlugin('android') || subproject.plugins.hasPlugin('android-library'))) {
            android {
                compileSdkVersion rootProject.ext.compileSdkVersion
                buildToolsVersion rootProject.ext.buildToolsVersion
            }
        }
    }
}

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.+'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
```

`gradle-wrapper.properties`:

```properties
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-4.0-all.zip
```

in `build.gradle` inside `app` folder

```gradle
android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion
    // ...
```

also, I was this settings since 0.46, and `react-native-git-upgrade` without any issues as well

**Comment by kelset** [comment]
Are you using these settings for an app out in production?

**Comment by pocesar** [comment]
yes, I am, and also using with `code-push`

**Comment by kelset** [comment]
Interesting, how long have you been using these settings? Is it performing well in Android 7?

Since I've upped to 25 (both compile and buildtools) some users have crashes I don't know how to debug (#15429) on Nougat.

And, follow-up, if you submit to the Google Play Store a build targetting 26, can you reverse to 25? 'cause I know you can't when upping from 23 to 25 it's a "no turning back" point.

**Comment by pocesar** [comment]
well, I'm not using Google Play, so I'm not sure. I'm testing on Samsung J7 with Android 6.0.1 and Android 7 as well, both seems to be working fine with a lot of intricate third party modules (like react-native-maps, react-native-camera, etc)

That error doesn't seem to be a problem with the buildTools per se, but it might be related to the SDK version, and guess it might be some bugs since it's the 'edge' of the Android SDKs

**Comment by iegik** [comment]
Still have issues:
https://github.com/facebook/react-native/issues/14980

**Comment by kelset** [comment]
Ok, I've tried to update my app too to 26 settings provided above, everything seems to be running fine for now.

I think tbh this issue could be closed, anyway, because it's not really "an issue".

**Comment by agrass** [comment]
it is not recommended to use compileSdkVersion 26 on production??  What do you guys think?

**Comment by iegik** [comment]
https://github.com/facebook/react-native/pull/15601

**Comment by pocesar** [comment]
@agrass I think you mean `targetSdkVersion` you can set that regardless of the `compileSdkVersion` (usually 23)

**Comment by agrass** [comment]
@pocesar I have ``targetSdkVersion`` 22, and I changed the ``buildToolsVersion`` and ``compileSdkVersion`` from 23 to 26 in order to use a library with some dependencies.  Now I'm a bit scared about this, because I'm not sure about the compatibility in some phones building RN with v26. Probably I'm going to roll back to v23

**Comment by agrass** [comment]
thanks @iegik for the references. what about v25, it is the same??

**Comment by iegik** [comment]
25 - more stable

**Comment by iegik** [comment]
I would not to promote stable release since of https://github.com/facebook/react-native/releases/tag/v0.40.0 because:
- in iOS not everywhere `<React/` prefix are added and don't forget that importing with prefix and without cause **Duplicate declaration** error in outdated dependent components
- Android builds are crashes with ProGuard enabled

**Comment by kelset** [comment]
> thanks, but suitable for production?? Anyone already using it?

I've been using 25 in prod and it's mostly stable, aside from an [Android 7 issue](https://github.com/facebook/react-native/issues/15429).

**Comment by pocesar** [comment]
not many tests were done in recente android sdk versions. Google itself ask to always use the latest SDK versions, and RN is still stuck in 23 by default. Maybe create a matrix testing for the CI?

**Comment by kelset** [comment]
I think this should remain open, currently I'm trying to use version 26 on our prod app and I'm facing some weird issues only when I test the app on Android 8.

**Comment by pocesar** [comment]
#17287 shows urgency on the issue

**Comment by nerdmed** [comment]
Any news on this. Updating Gradle makes our Android builds 50x faster. That is really significant and would benefit the developer experience!

**Comment by slorber** [comment]
Hey, just wanted to point out that when ejecting from Expo, you already use SDK26. Many of us have SDK26 Expo ejected apps in production (I have one, Expo SDK22, Android SDK26), so I guess it should be safe to target SDK26.

**Comment by dulmandakh** [comment]
Closing this issue, because RN 0.57 will have SDK 27, Support library 27.x, gradle 4.x and android gradle plugin 3.x
