### ISSUE TITLE
maxLength deprecated?

### ISSUE THREAD

**Issue by Joey-Hicklin** [facebook/react-native#15453]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

1. react-native: 0.46.4
2. node: 7.10.0
3. npm: 4.2.0
4. yarn: N/A

- Target Platform:  Android

- Development Operating System:  Windows 10 Home, 10.0.14393 Build 14393

- Build tools: I'm using the recommended Expo, Genymotion setup with Redux. With Genymotion I'm emulating a Google Nexus 4 - 5.0.0 - API 21 - 768x1280

### Steps to Reproduce

Create any textInput component and attempt to style it with the property maxLength. Specifically, I'm styling the textInput inside a scrollView, which is replicated here:
https://snack.expo.io/HkuZKB9PZ 

The snack.io example doesn't show warnings, but the emulated Genymotion device does. The associated warning is:

![image](https://user-images.githubusercontent.com/16186665/29192650-ffde70d2-7dd6-11e7-9a02-50a0665e18cd.png)

1. Create a textInput component
2.  Style it with the property maxLength

### Expected Behavior

I would expect the input to disallow further typing once the character count set by maxLength has been reached.

### Actual Behavior

Typed text is allowed infinitely and a warning is displayed when serving the app in development mode into an emulator.

(screenshot of warning posted above)

### Reproducible Demo

https://snack.expo.io/B1dVJUqDW 

Try to type more than 5 characters in the textInput

Thanks for the Help!
-- Joey Hicklin

**Comment by chirag04** [comment]
maxLenght is not a style property. it's a prop on the TextInput component. refer the example here: https://github.com/facebook/react-native/blob/603cc48ceba001827d10231d51b4031c7768eef8/RNTester/js/TextInputExample.ios.js
