### ISSUE TITLE
Retyping after TextInput.clear() brings back characters before the clear.

### ISSUE THREAD

**Issue by toytonic** [facebook/react-native#15450]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

- Target Platform: Android
- Development Operating System: macOSX
- Build tools: vscode, react-native-cli, android-studio, sdk: 23.0.1
- Issue is specific to some android versions/devices: We could reproduce it with 'SM-G903F - 6.0.1' 

### Steps to Reproduce

1. Implement a textinput with a clear function that calls 'textinputRef.clear()' on an input ref
2. type something in the text field
3. trigger that clear
4. start typing in the exact same textinput

### Expected Behavior
1. ...
2. Textinput shows characters I typed
3. Texinput shows no characters
4. Textinput shows only the caracters typed after the clear

### Actual Behavior

1. ...
2. Textinput shows characters I typed
3. TexInput shows no characters
4. Textinput shows characters before the clear AND the characters typed after the clear

### Reproducible Demo

https://snack.expo.io/HkCfLCYP-

The issue happens both with controlled and uncontrolled inputs.

**Comment by amirrezamahyari** [comment]
same problem , anybody have some idea ?
