### ISSUE TITLE
custom internet(okhttp) native module

### ISSUE THREAD

**Issue by wu464995183** [facebook/react-native#15459]
Hi, i try custom  internet(okhttp) native module.

   @ReactMethod
    public void get(String url, Callback callback) {

        try {
            Thread.sleep(10000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        String json = HttpClientC.get(url);
        callback.invoke(json);
    }

I purposely delayed it by 10 seconds. 

It will blocking the page when i call it in componentDidMount method.

is it run subThread?   but it blocking the page. why?

**Comment by hey99xx** [comment]
It is run in native module thread, which is still used to enqueue calls to the main UI thread. See my previous answer https://github.com/facebook/react-native/issues/14841#issuecomment-313595180 explaining why you shouldn't do blocking calls in @ReactMethod methods.

**Comment by hey99xx** [comment]
From http://facebook.github.io/react-native/docs/native-modules-android.html

> Native modules should not have any assumptions about what thread they are being called on, as the current assignment is subject to change in the future. If a blocking call is required, the heavy work should be dispatched to an internally managed worker thread, and any callbacks distributed from there.

**Comment by wu464995183** [comment]
I see. Thank you for your patience.
