### ISSUE TITLE
i can use props

### ISSUE THREAD

**Issue by Brhernann** [facebook/react-native#15458]
Hello,

I need to pass a function on the props, I have this component:

    `import React, {Component} from 'react';
     import { View } from 'react-native';
     import {FBLogin, FBLoginManager} from 'react-native-facebook-login';
      
     const Loginfb = (props) => (
            <FBLogin
            style={{marginBottom: 10}}
            ref={props.ref}
            permissions={["email", "user_friends"]}
            loginBehavior={FBLoginManager.LoginBehaviors.SystemAccount}
            onLogin={props.login}
);

    export default Loginfb;`

when props.ref and props.login are functions whit data. In my container component i have this:

    `import React, {Component} from 'react';
     import {View} from 'react-native';
     import {FBLogin, FBLoginManager} from 'react-native-facebook-login';
     import Loginfb from '../components/fblogin';

    class Inicio extends Component {

    constructor(props) {
    super(props);
    this.state = {
      user: null,
    };
}

    Ref = (fbLogin) => {
    this.fbLogin = fbLogin
}

    login = (data) => {
    console.log("Logged in!");
    console.log(data);
    this.setState({user: data.credentials});
}

    render() {
         return (
            <View
                 <Loginfb
                  ref={this.ref} 
                  onLogin={this.login}/>
            </View>
                  );
           }
    }
    export default Inicio;`

i cant understand my error : "this.props[event] is not a function"

Please Help

**Comment by jozan** [comment]
Unfortunately this issue is not React Native specific. I'd suggest you to create new a question on [StackOverflow](https://stackoverflow.com/) with proper tags and check the [issues on react-native-facebook-login repo](https://github.com/magus/react-native-facebook-login) if there's something similar.
