### ISSUE TITLE
Unable to resolve module implementation.js

### ISSUE THREAD

**Issue by msabaeian** [facebook/react-native#15468]
hi all
from two days ago i cant run my react native apps because of this error and i check lots of issues and search in google and ....
i remove all data and create new project with RNCA and init but it doesnt work too!

![Error Screenshot](https://image.ibb.co/jip6Pv/Capture.png)

- React Native version: 0.47.1
- Platform: Android
- Operating System: Windows 10

package.json
> {
  "name": "ReactNative",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "rnpm": {
    "assets": [
      "./src/fonts/"
    ]
  },
  "dependencies": {
    "mobx": "^3.2.2",
    "mobx-react": "^4.2.2",
    "moment": "^2.18.1",
    "native-base": "^2.3.1",
    "react": "16.0.0-alpha.12",
    "react-native": "0.47.1",
    "react-native-parsed-text": "0.0.18",
    "react-native-timeago": "^0.3.0"
  },
  "devDependencies": {
    "babel-jest": "20.0.3",
    "babel-preset-react-native": "2.1.0",
    "jest": "20.0.4",
    "react-test-renderer": "16.0.0-alpha.12"
  },
  "jest": {
    "preset": "react-native"
  }
}

I'd really appreciate if someone could help me out with this.

Thanks :)

**Comment by phixtalk** [comment]
Hey i am currently having exactly the same issue too.. But what caused mine i think was after i installed react-native-image-picker and was forced to remove the method located at:
node_modules\react-native-image-picker\android\src\main\java\com\imagepicker\ImagePickerPackage.java:34 for a successful build

Please any help will be duely appreciated. thanks
