### ISSUE TITLE
RCTBridge never dealloc

### ISSUE THREAD

**Issue by punan** [facebook/react-native#15462]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

1. `react-native -v`: 0.47.0
2. `node -v`: v8.1.2
3. `npm -v`: 5.3.0
4. `yarn --version`: not use

Then, specify:

- Target Platform: iOS

- Development Operating System: macOS

- Build tools: Xcode

### Steps to Reproduce

(Write your steps here:)

1.create new project
`react-native init demo`
2. create a new ViewController, and delete all the code in AppDelegate
3.add the RCTRootView to ViewController
```
@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    NSURL *jsCodeLocation;
  
    jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];
  
    RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                        moduleName:@"demo"
                                                 initialProperties:nil
                                                     launchOptions:nil];
  rootView.frame = self.view.frame;
  [self.view addSubview:rootView];
}

@end
```
4、run the project

### Expected Behavior

When the ViewController has been popped from UINavigationController, the RCTRootView and RCTBridge has to call dealloc methos

### Actual Behavior

ViewController and RCTRootView has called dealloc method, but RCTBridge hasn't call dealloc, become leak.
![screen shot 2017-08-11 at 3 50 35 pm](https://user-images.githubusercontent.com/5136784/29205028-f78fa374-7e3f-11e7-8804-b0da06d9b86e.png)
I use debug memory graph, it shows ViewControll and RCTRootView has been released, but when open ViewController again and again, the number of RCTBrigde will increase, the memory also increase
### Reproducible Demo

 [Demo Link](https://github.com/punan/rndemo)
I try to fix the issue, add [_bridge invalidate] to RCTRootView dealloc method. It works, RCTBridge calls dealloc methods when RCTRootView dealloc. 

> RCTRootView

```
- (void)dealloc
{
  [[NSNotificationCenter defaultCenter] removeObserver:self];
  [_contentView invalidate];
  [_bridge invalidate];
}
```

**Comment by shergin** [comment]
Probably fixed in https://github.com/facebook/react-native/commit/1f9fc0ee3a2964b067f0848e35603475e510067c .

**Comment by sdyxch** [comment]
same issue,  The ViewController and RCTRootView has been released, but RCTBridge never.

**Comment by 312362115** [comment]
still on 0.53.0

**Comment by edison0951** [comment]
still on 0.51.0

**Comment by edison0951** [comment]
We must set [_bridge invalidate] so that the relative resource can be release

**Comment by seuzxh** [comment]
Same issue with version 0.54.2,  RCTBridge cannot be dealloced

**Comment by vvlee** [comment]
still on 0.55.4

**Comment by arslan2012** [comment]
still on 0.56.0 lol wtf
