### ISSUE TITLE
React-native App fails to launch in Android with multiple warning messages on debug builds

### ISSUE THREAD

**Issue by ReactUserQuest** [facebook/react-native#15465]
### Environment
react-native-cli: 2.0.1
node : v8.2.1
npm: 5.3.0

- Target Platform:
Android 5.0 x86-64 image

- Development Operating System:
Windows 7 professional edition, x86_64

package.json
===============
"dependencies": {
    "axios": "^0.16.2",
    "buffer": "^5.0.6",
    "lodash": "^4.17.4",
    "mobx": "^3.2.1",
    "mobx-react": "^4.2.2",
    "react": "16.0.0-alpha.12",
    "react-native": "0.45.1",
    "react-native-background-timer": "^1.1.0",
    "react-native-fetch-blob": "latest",
    "react-native-timer": "^1.3.1"
  },
  "devDependencies": {
    "babel-jest": "20.0.3",
    "babel-preset-react-native": "2.0.0",
    "jest": "20.0.4",
    "react-test-renderer": "16.0.0-alpha.12",
    "tslint": "^5.4.3",
    "typescript": "^2.4.1",
    "typings": "^2.1.1"
  },

### Steps to Reproduce
1. npm install
2. npm run build
3. react-native run-android 

### Expected Behavior
This is supposed to launch the application successfully on Physical device connected via USB or on the emulator running.

### Actual Behavior

App fails to launch with these bunch of warning messages:
Warning: Failed prop type: Invalid prop 'alignItems' of value 'function checkType() {... [native code]
Warning: Failed prop type: Invalid prop 'bacckgroundColor' supplied to 'SrollView': function colorPropType() { [native code] }
Warning: Failed prop type: Invalid prop 'bacckgroundColor' supplied to 'View': function colorPropType() { [native code] }
Warning: Failed prop type: Invalid prop 'display' of type 'function' supplied to  'RCTView', expected 'string'. Bad object:{} in RCTView (at View.js:128)
....
###
1)      Build and deployment works fine with release builds which means running the following command it works fine:
**_react-native run-android --variant=release_**
2)      The same code base doesn’t work with apk debug builds 
**_react-native run-android --variant=debug_**
3)      The weird thing is that this behavior is not consistent. Intermittently sometimes it works fine. For example, I have tried using different combination of react/react-native versions in the package.json. Its observed that it worked once with react v0.47.1 and react-native v16.0.0-bet5. The same configuration on same set up failed later. 
4)      For once it also worked with a combination of both react/react-native upgraded to latest versions (v0.48_rc0 and v16.0.0-bet5 respectively). But that too is not consistently working.

**Comment by ReactUserQuest** [comment]
Could someone help me with this error?

Here is the stacktrace:
========================================================
[vscode-react-native] Finished executing: adb -s emulator-5554 shell am broadcast -a "com.reactnativets.RELOAD_APP_ACTION" --ez jsproxy true
[vscode-react-native] Starting debugger app worker.
[vscode-react-native] Established a connection with the Proxy (Packager) to the React Native application
[vscode-react-native] Debugger worker loaded runtime on port 36781
Warning: PropTypes has been moved to a separate package. Accessing React.PropTypes is no longer supported and will be removed completely in React 16. Use the prop-types package on npm instead. (https://fb.me/migrating-from-react-proptypes)
Warning: React.createClass is no longer supported. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement. (https://fb.me/migrating-from-react-create-class)
Running application "ReactNativeTS" with appParams: {"rootTag":1}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
Warning: Failed prop type: Invalid prop `alignItems` of value `function () { [native code] }` supplied to `View`, expected one of ["flex-start","flex-end","center","stretch","baseline"].
Bad object: {}
    in View (at ActivityIndicator.js:94)
    in ActivityIndicator (created by AutoLogin)
    in RCTView (at View.js:128)
    in View (created by AutoLogin)
    in AutoLogin (created by App)
    in RCTView (at View.js:128)
    in View (created by App)
    in App (at renderApplication.js:35)
    in RCTView (at View.js:128)
    in View (at AppContainer.js:93)
    in RCTView (at View.js:128)
    in View (at AppContainer.js:92)
    in AppContainer (at renderApplication.js:34)
Warning: Failed prop type: Invalid prop `alignItems` of value `function () { [native code] }` supplied to `RCTView`, expected one of ["flex-start","flex-end","center","stretch","baseline"].
Bad object: {}
    in RCTView (at View.js:128)
    in View (at ActivityIndicator.js:94)
    in ActivityIndicator (created by AutoLogin)
    in RCTView (at View.js:128)
    in View (created by AutoLogin)
    in AutoLogin (created by App)
    in RCTView (at View.js:128)
    in View (created by App)
    in App (at renderApplication.js:35)
    in RCTView (at View.js:128)
    in View (at AppContainer.js:93)
    in RCTView (at View.js:128)
    in View (at AppContainer.js:92)
    in AppContainer (at renderApplication.js:34)
Warning: Failed prop type: Invalid prop `backgroundColor` supplied to `ScrollView`: function () { [native code] }
Valid color formats are
  - '#f0f' (#rgb)
  - '#f0fc' (#rgba)
  - '#ff00ff' (#rrggbb)
  - '#ff00ff00' (#rrggbbaa)
  - 'rgb(255, 255, 255)'
  - 'rgba(255, 255, 255, 1.0)'
  - 'hsl(360, 100%, 100%)'
  - 'hsla(360, 100%, 100%, 1.0)'
  - 'transparent'
  - 'red'
  - 0xff00ff00 (0xrrggbbaa)

Bad object: {}
    in ScrollView (at YellowBox.js:411)
    in YellowBox (at AppContainer.js:88)
    in RCTView (at View.js:128)
    in View (at AppContainer.js:92)
    in AppContainer (at renderApplication.js:34)
Warning: Failed prop type: Invalid prop `backgroundColor` supplied to `View`: function () { [native code] }
Valid color formats are
  - '#f0f' (#rgb)
  - '#f0fc' (#rgba)
  - '#ff00ff' (#rrggbb)
  - '#ff00ff00' (#rrggbbaa)
  - 'rgb(255, 255, 255)'
  - 'rgba(255, 255, 255, 1.0)'
  - 'hsl(360, 100%, 100%)'
  - 'hsla(360, 100%, 100%, 1.0)'
  - 'transparent'
  - 'red'
  - 0xff00ff00 (0xrrggbbaa)

Bad object: {}
    in View (at YellowBox.js:410)
    in YellowBox (at AppContainer.js:88)
    in RCTView (at View.js:128)
    in View (at AppContainer.js:92)
    in AppContainer (at renderApplication.js:34)
Warning: Failed prop type: Invalid prop `backgroundColor` supplied to `RCTView`: function () { [native code] }
Valid color formats are
  - '#f0f' (#rgb)
  - '#f0fc' (#rgba)
  - '#ff00ff' (#rrggbb)
  - '#ff00ff00' (#rrggbbaa)
  - 'rgb(255, 255, 255)'
  - 'rgba(255, 255, 255, 1.0)'
  - 'hsl(360, 100%, 100%)'
  - 'hsla(360, 100%, 100%, 1.0)'
  - 'transparent'
  - 'red'
  - 0xff00ff00 (0xrrggbbaa)

Bad object: {}
    in RCTView (at View.js:128)
    in View (at YellowBox.js:410)
    in YellowBox (at AppContainer.js:88)
    in RCTView (at View.js:128)
    in View (at AppContainer.js:92)
    in AppContainer (at renderApplication.js:34)
Warning: Failed prop type: Invalid prop `display` of type `function` supplied to `View`, expected `string`.
Bad object: {}
    in View (at ScrollView.js:649)
    in ScrollView (at YellowBox.js:411)
    in RCTView (at View.js:128)
    in View (at YellowBox.js:410)
    in YellowBox (at AppContainer.js:88)
    in RCTView (at View.js:128)
    in View (at AppContainer.js:92)
    in AppContainer (at renderApplication.js:34)
Warning: Failed prop type: Invalid prop `flexGrow` of type `function` supplied to `RCTScrollView`, expected `number`.
Bad object: {}
    in RCTScrollView (at ScrollView.js:732)
    in ScrollView (at YellowBox.js:411)
    in RCTView (at View.js:128)
    in View (at YellowBox.js:410)
    in YellowBox (at AppContainer.js:88)
    in RCTView (at View.js:128)
    in View (at AppContainer.js:92)
    in AppContainer (at renderApplication.js:34)
Warning: Failed prop type: Invalid prop `display` of type `function` supplied to `RCTView`, expected `string`.
Bad object: {}
    in RCTView (at View.js:128)
    in View (at ScrollView.js:649)
    in RCTScrollView (at ScrollView.js:732)
    in ScrollView (at YellowBox.js:411)
    in RCTView (at View.js:128)
    in View (at YellowBox.js:410)
    in YellowBox (at AppContainer.js:88)
    in RCTView (at View.js:128)
    in View (at AppContainer.js:92)
    in AppContainer (at renderApplication.js:34)
=================================================

Note: There is no reference to React.propType or React.createClass in the code. But it still gives the warning. Any help is appreciated. Thanks.

**Comment by Amwam** [comment]
@ReactUserQuest I think this question would be better suited to stackoverflow.

The warnings aren't about the use of PropTypes or CreateClass, but the types of the props you are supplying to your component.

`flexGrow`, `display`, `alignItems`, `backgroundColor` all seem to be functions, rather than their expected types. If you look through the error messages they clearly describe the expected types.

**Comment by ReactUserQuest** [comment]
@Amwam Thanks for your quick response. Please correct me if I am wrong.

The warnings are a bit misleading here because these flexGrow, display, alignItems, backgroundColor are CSS properties which adheres to their designated values, for example:
    infoBox: {
        **flexGrow: 1,**
        paddingLeft: 10,
    }
   rowBoxDirection: {
        width: '100%',
        flexWrap: 'wrap',
        flexDirection: 'row',
        **alignItems: 'flex-start',**
        margin: 5,
    },
Lets take a look at this specific warning message:
_Warning: Failed prop type: Invalid prop alignItems of value function () { [native code] } supplied to RCTView, expected one of ["flex-start","flex-end","center","stretch","baseline"]._

The value assigned to 'alignItems' is indeed one of the permissible value, which is 'flex-start'. But still it complains. 
Besides, as mentioned in the beginning of this issue, it works fine with release build and fails only on debug build, that too intermittently. This is the most confusing behavior observed here. 

I will also try my luck with stackoverflow.

**Comment by ReactUserQuest** [comment]
This is found to be working fine with  "react": "16.0.0-alpha.12" and  "react-native": "0.47.0". Hence closing the issue.
