### ISSUE TITLE
[ListView] broken without setInterval

### ISSUE THREAD

**Issue by vishnevskiy** [facebook/react-native#1547]
This commit removed setInterval

https://github.com/facebook/react-native/commit/34cef28a10b7d44be453c072578b5b6c07a0dcd8

But it seems there might be a bug with ListView without it. No matter what I set initial size to eventually the ListView refuses to render the right amount of items until forced.

For example I set it to 10. If I keep changing the data source between 5 and 15 elements eventually it will render 3. Just scrolling it will reveal the rest though.

I have been unable to figure out what is causing this, will keep digging.

**Comment by vishnevskiy** [comment]
So looks like to reproduce this is.

- Make 2 data sets. One that fits on the screen without scrolling and one that does not.
- Load up the small one first. 
- Then switch it to the long data set and scroll all the way down.
- Then switch back to small one and then instantly back again to big one.
- It will now not render properly until you scroll.

Using a unique key for the ListView per dataset will fix it. So remounting works.

**Comment by sahrens** [comment]
Probably just need to add an extra call to manually trigger updates when data changes to catch that corner case. I'll put out a fix soon.

**Comment by sahrens** [comment]
Thanks for fixing this @ide!
