### ISSUE TITLE
How to add a number value no the ListItem ?

### ISSUE THREAD

**Issue by jpca999** [facebook/react-native#15470]
the number 199 should be coming from backend, dynamically. 

![image](https://user-images.githubusercontent.com/1026325/29236093-1b614c96-7ed4-11e7-8723-067f529b4573.png)

  <List>

            <ListItem
                onPress={() => navigate('allProperties')}
                title="All Properties                         199"
                leftIcon={{name: 'flight-takeoff'}}
                color="rgba(0,122,255,1)"
            />

### Is this a bug report?

(write your answer here)

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.)

### Environment

1. `react-native -v`:
2. `node -v`:
3. `npm -v`:
4. `yarn --version`:

Then, specify:

- Target Platform:

- Development Operating System:

- Build tools:

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by charpeni** [comment]
@facebook-github-bot stack-overflow
