### ISSUE TITLE
RN 0.47.1 with cocoapods failed when use_frameworks

### ISSUE THREAD

**Issue by taojoe** [facebook/react-native#15471]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

1. `react-native -v`:  0.47.1
2. `node -v`: v8.2.1
3. `npm -v`: 5.3.0
4. `yarn --version`: v0.27.5

Then, specify:

- Target Platform: iOS

- Development Operating System: macOS, 10.12.6

- Build tools: Xcode 8.3.3, cocoapods 1.3.1

### Steps to Reproduce

(Write your steps here:)

1. following the ["Integration With Existing Apps"](http://facebook.github.io/react-native/releases/0.47/docs/integration-with-existing-apps.html) guide make the demo project exactly. 
2. change the Podfile, make sure use "use_frameworks!"

### Expected Behavior

work as not "use_frameworks!"

### Actual Behavior

cannot start, #import <React/RCTRootView.h> file not found.

### Reproducible Demo

1.  git clone https://github.com/taojoe/RNIntegrationWithExistingApp.git
2. cd RNIntegrationWithExistingApp 
3. npm install
4. cd ios 
5. pod install, then run xcode get the error
6. change Podfile, comment "use_frameworks!",  then do pod install again, all works.

**Comment by ide** [comment]
Have you tried `@import` instead of `#import`?

**Comment by taojoe** [comment]
@import React;  module not found.
