### ISSUE TITLE
React-native uses outdated version of connect, which in turn requires package with vulnerability 

### ISSUE THREAD

**Issue by katnem** [facebook/react-native#15486]
At the moment react-native dependency on connect is declared like this: "^2.8.3", which won't allow  for the newer versions of connect like 3.6.3 (connect 3.6.3 doesn't depend on compression module, so this eliminates the problem I have).
My dependency tree looks like this: 
```
└─┬ react-native@0.46.4
  │ A framework for building native apps using React
  │ git+ssh://git@github.com/facebook/react-native.git
  │ https://github.com/facebook/react-native#readme
  └─┬ connect@2.30.2
    │ High performance middleware framework
    │ git+https://github.com/senchalabs/connect.git
    │ https://github.com/senchalabs/connect#readme
    ├─┬ compression@1.5.2
    │ │ Node.js compression middleware
    │ │ git+https://github.com/expressjs/compression.git
    │ │ https://github.com/expressjs/compression#readme
    │ └─┬ accepts@1.2.13
    │   │ Higher-level content negotiation
    │   │ git+https://github.com/jshttp/accepts.git
    │   │ https://github.com/jshttp/accepts#readme
    │   └── negotiator@0.5.3
    │       HTTP content negotiation
    │       git+https://github.com/jshttp/negotiator.git
    │       https://github.com/jshttp/negotiator#readme
```
The package with vulnerability - negotiator (issue described here https://nodesecurity.io/advisories/106).

p.s. not sure whether this is the right place to enquire regarding the support for the latest version of connect, but all the other resources seemed equally unfit for my issue.

**Comment by Strayer** [comment]
This has already been mentioned in #11637, but that issue has been closed due to inactivity. Since its just a packager issue I have this .nsprc in our project:

```javascript
{
  "exceptions": [
    "https://nodesecurity.io/advisories/106" // https://github.com/facebook/react-native/issues/11637
  ]
}
```

**Comment by katnem** [comment]
Thanks for the quick reply @Strayer. 
I understand that the vulnerability might not apply in my case. 
Still, I'm interested whether there are plans to update the dependency.

**Comment by ide** [comment]
There are no plans to update it. If you would like to go through all the call sites and update the dependency, a PR would be appreciated.
