### ISSUE TITLE
'RCTViewManager.h' file not found

### ISSUE THREAD

**Issue by zhangkaiyulw** [facebook/react-native#15482]
There is an annoying error which always happen when create a new iOS native view.

Steps to reproduce:

1. Create a new file in Xcode 8.3.3
2. Select Cocoa Touch Class
3. Type a class name which is a subclass of RCTViewManager, language is selected to Objective-C
4. Click Next and Save this file
5. Compile, there is an error
6. Open the header of the newly created file
``` objc
#import "RCTViewManager.h"
```
This line has an error,
changing to this line fixed the error
``` objc
#import <React/RCTViewManager.h>
```

I'm using
react-native-cli: 2.0.1
react-native: 0.47.1

Is this template file error?

**Comment by shergin** [comment]
Xcode provides this template, so we cannot fix this.
