### ISSUE TITLE
1 second delay in setState , when flatlist is used

### ISSUE THREAD

**Issue by vishnuc** [facebook/react-native#15480]
So I have component like below

```
 return (
      <View>
        <View
          style={!this.state.showSearchBar && styles.hidden}
        >
          <Header>
            <View>
              <Item >
                <Icon name="ios-search" />
                <Input placeholder="Search" />
              </Item>
              <Button
                onPress={this.searchBarButton}
              >
                <Text>Search</Text>
              </Button>
            </View>
          </Header>
        </View>

        <View
          style={this.state.showSearchBar && styles.hidden}
        >
          <Header ref={"button"}>
            <Button onPress={() => this.searchBarButton()} transparent>
              <Icon name="search" style={styles.bigblue} />
            </Button>
          </Header>
        </View>

<FlatList style={{zIndex: 0,minHeight:'100%'}}
				ref={ref => {
					this.listRef = ref;
				}}
				extraData={this.state}
				data={this.state.data}
				onRefresh={this.onRefresh}
				refreshing={this.state.refreshing}
				renderItem={this._renderItem}
				onEndReached={this.onEnd}
				onEndReachedThreshold={0.5}
				ListHeaderComponent={this.headerMessage}
				ListFooterComponent={this.footerMessage}
				ListEmptyComponent={this.empty}
			/>


      </View>
    );
  }
```
When I click on button I basically set state so I am hiding and showing search bar with search icon

```
 searchBarButton() {
    this.setState({ showSearchBar: !this.state.showSearchBar });
  }
```
and style

```
   hidden: {
    height: 0,
    width: 0,
    opacity: 0
  }
```

So basically this works very smooth and fast when my scene is just with header , But when I add flatlist , there is 1 second delay between toggle.But if I remove flat list its again fast.

**Comment by iamawebgeek** [comment]
Are you using the `state` inside flat list? If no, try to remove it from `extraData`

**Comment by vishnuc** [comment]
Yes I use state inside ListHeaderComponent.

**Comment by iamawebgeek** [comment]
Is your `renderItem` component pure? Also in `__DEV__` mode there may be some slow performance, try to uncheck it in development settings and reload the bundle

**Comment by vishnuc** [comment]
Yes renderItem is pure , I also removed all the state in
ListHeaderComponent .Now
Flatlist is pure but contains around 100 items.But problem is my flatlist
is being called and rendered again when state is changed,same problem when
extraData is removed. I guess I should use shouldcomponentupdate and stop
reRendering.

I am using Expo , there is no development mode in that I guess..

**Comment by oakis** [comment]
I had this problem in __DEV__ but not in production. Thanks @iamawebgeek
