### ISSUE TITLE
RCTJSEnvironment.h file not found after upgrade to react-native 0.47.0

### ISSUE THREAD

**Issue by tjmadsen** [facebook/react-native#15483]
Everything is working in 0.46.0, but after upgrading to 0.47.0 (both by manually upgrading the package and by using react-native-git-upgrade), getting this error.

### Environment

1. `react-native -v`: 0.47.0
2. `node -v`: 8.2.1
3. `npm -v`: 5.3.0
4. `yarn --version`: 0.21.3
![image](https://user-images.githubusercontent.com/1667894/29258370-df58db6a-806d-11e7-831d-7cce389aa75b.png)

Then, specify:

- Target Platform: iOS

- Development Operating System: macOS

- Build tools: Xcode (iOS)

### Steps to Reproduce

Upgrade to react-native 0.47.0 and run `react-native run-ios`

### Expected Behavior

App should build and run successfully

### Actual Behavior

![image](https://user-images.githubusercontent.com/1667894/29258282-4c881a44-806d-11e7-898d-29e120c7f82d.png)

**Comment by AlanFoster** [comment]
@tjmadsen Sanity test question; Did you run a yarn / do a clean / clear caches etc?

**Comment by tjmadsen** [comment]
Yes, did a cache clean, did a fresh yarn/npm install

In addition, I tried troubleshooting with a number of versions, and other dependencies.  I wasn't able to make much progress other than to further isolate the issue down to the single switch between 0.46.0 and 0.47.0

I'm still in active dev with the app, so I'll continue to test upgrading and add any more information I can.

**Comment by zaiz91** [comment]
I got the same error, after upgrading to 0.47. @tjmadsen Any progress on this issue?

**Comment by fbacker** [comment]
Same issue after an upgrade. Any success for anyone?

    "react-native": "0.47.1"

When browsing the RCTDevSettings.mm I can hyperclick to the file 
    
    /React/Base/RCTJSEnvironment.mm but still getting the error.

I've also tried to clean house without success with: 

    npm cache clean --force 
    watchman watch-del-all 
    rm -fr $TMPDIR/react-* && rm -rf node_modules

**Comment by zaiz91** [comment]
The following workend for me:

- Clean Xcode Project
- Delete Pod Files & pod.lock
- Delete node_modules & yarn.lock
- fix possible bugs in js code 
- yarn install 
- pod installl

Good luck.
