### ISSUE TITLE
fetch does not work properly on Android with react native 0.47.1

### ISSUE THREAD

**Issue by pongponglau** [facebook/react-native#15491]
I find a strange problem with fetch on android. 

fetch(url).then(res => res.json())
      .then(res => {
        console.log('pongpong ttttttttt '+JSON.stringify(res))
      })

No then() is called in the above statement.

The following is printed when i print out the content of the promise returned by fetch(url)

tx1 {"_40":0,"_65":0,"_55":null,"_72":null}

However, fetch works perfectly in iOS.

Do you have any idea?

Thanks a lot

**Comment by zhaiyjgithub** [comment]
same error.

**Comment by gao520sun** [comment]
+1
