### ISSUE TITLE
android：No dimension set for key window, stack: value

### ISSUE THREAD

**Issue by mingkang1993** [facebook/react-native#15495]
### android：No dimension set for key window, stack: value

node 7.7.1
npm 4.1.2
react-native-cli  2.0.1
react-native 0.44.0

not is debug  ， is release.
this is Tencent - bugly platform provide log

this is bug image.
![8fbf9bce-18fa-4069-9e07-62e3f647e0d3](https://user-images.githubusercontent.com/9126292/29301319-da5d8a02-81ad-11e7-9947-fd10c5dc0ab7.png)

**Comment by mingkang1993** [comment]
help

**Comment by dabit3** [comment]
When does this get thrown? Is it on application start?

**Comment by sospedra** [comment]
I'm experiencing the issue also.

Just on release build for Android :/
