### ISSUE TITLE
how can i get these numbers on the ListItem ?

### ISSUE THREAD

**Issue by jpca999** [facebook/react-native#15498]
number should be coming here from backend. 

  <List>
              <ListItem
                  onPress={() => navigate('todoItems')}
                  title="ToDo Task"
                  leftIcon={{name: 'flight-takeoff'}}
                  color="rgba(0,122,255,1)"
              />

![image](https://user-images.githubusercontent.com/1026325/29314642-dc558920-818c-11e7-9704-de375cf54864.png)

### Is this a bug report?

(write your answer here)

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.)

### Environment

1. `react-native -v`:
2. `node -v`:
3. `npm -v`:
4. `yarn --version`:

Then, specify:

- Target Platform:

- Development Operating System:

- Build tools:

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by charpeni** [comment]
@facebook-github-bot stack-overflow
