### ISSUE TITLE
[TouchableBounce] Split up into separate module

### ISSUE THREAD

**Issue by brentvatne** [facebook/react-native#1550]
As per #1545, this library should be pulled out into a separate project that is installable via npm.

**Comment by grabbou** [comment]
Doesn't matter who's the owner of the repo?

**Comment by brentvatne** [comment]
@grabbou - if you create one and @vjeux would prefer it to be on the Facebook account we can look at transferring it :smile:

**Comment by grabbou** [comment]
One step closer to join Facebook organisation :8ball: Ok, will dig into that.

**Comment by brentvatne** [comment]
Haha awesome thanks :100:

**Comment by browniefed** [comment]
@grabbou any progress on splitting this into a separate module?

**Comment by grabbou** [comment]
Yeah, I've started last Saturday as I finally had enough time to understand how these sub-project all work, so will publish it probably tomorrow along with few other modules I was working on. Thank you for this reminder ;)

**Comment by brentvatne** [comment]
:+1: awesome thanks @grabbou!

**Comment by grabbou** [comment]
@brentvatne what should I do with the copyright headers in files? Shall I keep them + include your licence?

**Comment by brentvatne** [comment]
@grabbou - I'd make it as similar as you can to what FB has in React Native :)

**Comment by grabbou** [comment]
Ok, will keep all the things and send you a link to private repo so we can work out the legal issues before it goes live :)

**Comment by grabbou** [comment]
In progress. To be published by 5 pm I guess.

**Comment by joshuagutierrez** [comment]
Status of issue?

**Comment by grabbou** [comment]
Yes, I've finished that last week - I am on holidays now but will try to find time either tomorrow or on Friday to push it to npm! Sorry for such huge delay

**Comment by grabbou** [comment]
That's now done -> https://github.com/grabbou/react-native-touchable-bounce

Going to publish it to npm later today & update react-native repo to reference it.

Anything we can do about:
https://github.com/grabbou/react-native-touchable-bounce/blob/master/src/index.js#L19

**Comment by grabbou** [comment]
@brentvatne @mkonicek right now it uses internal not-exported modules (https://github.com/grabbou/react-native-touchable-bounce/blob/master/src/index.js#L14-L21) which unfortunately does not work (as far as I remember, relying on that has undefined behaviour - in examples it works, but when consumed from npm it does not).

Any chances these get included? (Touchable seems to be included in master now).

**Comment by grabbou** [comment]
This has been fixed and you can now consume TouchableBounce from npm: https://github.com/grabbou/react-native-touchable-bounce

There's open PR for doing the same in main react-native repo, however it's loosely coupled with this issue itself.
