### ISSUE TITLE
Loading all modules in a folder

### ISSUE THREAD

**Issue by jarecsni** [facebook/react-native#15508]
This is not a bug per se, more like a feature request, but it seems it's not really on the radar for RN.

There's a genuine reason for wanting to load modules in bulk (not referencing each and every module directly). This is possible with Webpack require.context, and is very important to implement certain designs (plugin architecture, inversion of control, etc.)

As a bare minimum we should have some API to load all modules from a folder, similar to require.context.

For further insight into this issue, please see my article here: 
https://medium.com/@janos.jarecsni/auto-loading-modules-c8c47472d59b

In case you do think you will have to close this issue as it's not a bugreport, please kindly let me know where such feature requests should be filed.

Thanks!

**Comment by jarecsni** [comment]
Maybe the way to go is to use Webpack for packaging RN apps?

**Comment by hramos** [comment]
Thanks for opening the issue! We do have a place for feature requests on [Canny](https://reactnative.canny.io/feature-requests). You can also refer to the rest of the Contributor's Guide (linked from the issue template) for more information on getting in touch.

**Comment by jarecsni** [comment]
Thanks, apologies for opening this here, will check out the Contributor's Guide. I will now open a feature request on Canny (URL correctly is: https://react-native.canny.io/feature-requests)

Thanks!

**Comment by jarecsni** [comment]
https://react-native.canny.io/feature-requests/p/load-all-modules-from-a-folder

**Comment by Obooman** [comment]
[babel-plugin-import-glob](https://github.com/novemberborn/babel-plugin-import-glob) solved my problem,alternative to webpack  

```javascript
const batch = require.context("../foo/", false,  /\.js$/)
``` 
we can do this
```javascript
import * as batch from "../foo/*.js"
```
