### ISSUE TITLE
[android / ios] bundling failed: "TransformError

### ISSUE THREAD

**Issue by esganzerla** [facebook/react-native#15513]
### Is this a bug report?
Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?
Yes

### Environment
1. `react-native -v`:
react-native-cli: 2.0.0
react-native: n/a - not inside a React Native project directory
(I was inside the folder, version is: 0.47.1)
2. `node -v`: v7.10.0
3. `npm -v`: 4.2.0
4. `yarn --version`: 0.17.10

Then, specify:
- Target Platform: Android, iOS
- Development Operating System: macOS Sierra 10.12.6
- Build tools: Using Xcode 8.3.3 and Android Studio 2.3

### Steps to Reproduce
1. `react-native init rn_reproduce_transform_error`
2. `cd rn_reproduce_transform_error`
3. `react-native run-ios` or `react-native run-android`

### Expected Behavior
Should show the default "Welcome to React Native!" screen.

### Actual Behavior
![bundling failed: "TransformError: /Users/eduardo/Desktop/rn_reproduce_transform_error/index.ios.js: Unexpected token ) (While processing preset: \"/Users/eduardo/Desktop/rn_reproduce_transform_error/node_modules/babel-preset-react-native/index.js\")"](https://github.com/esganzerla/rn_reproduce_transform_error/blob/master/screenshots/app-error.png)

Same error occurs when I tried to update RN version to 0.48.0-rc.1
![SyntaxError: Unexpected token )](https://github.com/esganzerla/rn_reproduce_transform_error/blob/master/screenshots/upgrade-error.png)

### Reproducible Demo
https://github.com/esganzerla/rn_reproduce_transform_error

### Notes
- This happens both on android and iOS.
- I saw some people having the same problem on issue #15496.

**Comment by tmartres** [comment]
Had the same issue and after restarting my computer the issue went away for me. You might have to just close and restart your terminal and simulator too.

**Comment by PhillipWinder** [comment]
+1 

experiencing the same issue on `run-android` aswell as `run-ios`

**Comment by amerej** [comment]
@tmartres Restarting don't work for me

**Comment by esganzerla** [comment]
Restarting didn't help here too.

**Comment by esganzerla** [comment]
I've just found a workaround:

`yarn remove babel-preset-react-native`
`yarn add babel-preset-react-native@2.1.0`

The hole is probably deeper, but that is works for me.

**Comment by jarecsni** [comment]
I've tried to create a new RN app by RNCA (Expo) and then eject it. Works perfectly fine, although it runs on React Native 0.46.1, so I'm guessing this is an issue with 0.47.

**Comment by charpeni** [comment]
Thanks for reporting and the workaround @esganzerla.

It seems an issue with `babel-preset-react-native@3.0.0` that was released earlier.

@jeanlauliac How should we fix this issue? Add a specific major version in `react-native-cli`? 
https://github.com/facebook/react-native/blob/a54d449e947afc609a404a699494902823fbbf5e/local-cli/init/init.js#L91

cc @ericnakagawa who's on call.

**Comment by charpeni** [comment]
@facebook-github-bot label Tooling

**Comment by sachinwak** [comment]
uninstalling and installing babel-preset-react-native works for me thanks  a lot @esganzerla

**Comment by ivanzotov** [comment]
Spent a lot of time trying to fix this issue, PR #15516 but I still don't understand why these changes fixes it.

**Comment by ivanzotov** [comment]
I just moved plugins from `plugins.push(...` to `const plugins = [...]`

**Comment by ivanzotov** [comment]
@jeanlauliac any ideas?

**Comment by charpeni** [comment]
Trailing commas in function parameter lists is not supported.

https://github.com/ivanzotov/react-native/blob/master/babel-preset/configs/main.js#L40

**Comment by ivanzotov** [comment]
@charpeni exactly

**Comment by cpojer** [comment]
Needs node 8. Feel free to remove that and the @format annotation, I guess.

**Comment by Ibrokola** [comment]
It is a bug an the work around that worked for me was to edit dependency of babel in package.json to "babel-preset-react-native": "2.1.0". After which I deleted node_modules and re-installed the npm (npm install). Then it worked like a charm.

**Comment by ShubhamBabhulkar** [comment]
npm add babel-preset-react-native@2.1.0
Command not Work, please give me any Solution

**Comment by Ibrokola** [comment]
Did you delete node_modules if not delete node_modules and run npm install.
I am certain it will work.

**Comment by iktw** [comment]
This fixed it for me:
`yarn add react@16.0.0-alpha.12 react-test-rendere@16.0.0-alpha.12`

**Comment by gedeagas** [comment]
Thx a lot dude @esganzerla , your workaround fixed my problem

**Comment by coryarmbrecht** [comment]
Since I'm not using yarn, @Ibrokola 's solution fixed it for me (Thanks!), but I'm curious about what that version jump (3 -> 2) could do.

**Comment by guoliang1206** [comment]
for my case , it need execute `npm install babel-preset-react-native@2.1.0 --save-dev` , it works for me .

**Comment by ShubhamBabhulkar** [comment]
Nice @Ibrokola, But we need to do same thing every time?

**Comment by ShubhamBabhulkar** [comment]
For npm Following Command are work for me
$ npm uninstall babel-preset-react-native
$ npm install babel-preset-react-native@2.1.0

**Comment by ShubhamBabhulkar** [comment]
If you Still Getting Problem in babel-preset-react-native then try Following Process

package.json

"dependencies": {
		"react": "16.0.0-alpha.12",
		"react-native": "0.47.1",
		"babel-preset-react-native": "2.1.0" --------->Here
	},


Delete 'Node_modules' folder from react native project manually
and run followinf Commands in react native project
$ npm install
$ npm start -- --reset-cache
$ react-native run-android

**Comment by Ibrokola** [comment]
@ShubhamBabhulkar, I think there's a bug 🐜 in 3.0 that needs to be fixed...

**Comment by cheng-kang** [comment]
Check `index.ios.js`, see if there is a trailling comma. If so, delete it. It works for me.

```JavaScript
const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
  // ↑ here, delete it
});
```

**Comment by cyorobert** [comment]
@Ibrokola's solution fixed this issue for me. Thanks!

**Comment by zhiyingzzhou** [comment]
@ShubhamBabhulkar it works for me,thank you!

**Comment by golestanirad** [comment]
@Ibrokola thanks worked for me. 
1) delete node_modules folder
2) go to package.json and change babel-preset-react-native: 3.0.0" to babel-preset-react-native: 2.1.0"
3) run "npm install"

**Comment by zuhrisaifudin** [comment]
this works ..thanks guys

**Comment by SambitPrakash** [comment]
@esganzerla thank you a lot. I uninstall yarn and reinstall it. It worked for me.

**Comment by GuiMend** [comment]
thanks a lot @esganzerla, i installed yarn and then added that babel-preset... and it worked for me!

**Comment by jmgallo55** [comment]
Hey Guys-
Nothing new, just writing what worked for me:
1. npm install --save-dev babel-preset-react-native@2.1.0
2. npm install
3. react-native run-android

**Comment by varunagg45** [comment]
@cheng-kang your answer worked. I did all the steps necessary, yarn delete yarn add, npm install, uninstall, babel preset version upgrades but nothing worked but your solution.

**Comment by nikkwong** [comment]
I'm running into this in ```^5.0.0```. Anyone else having this problem? I've tried several different versions of ```babel-preset-react-native``` and haven't had any luck. Been debugging it for 7-8 hours now. Clearing xcode caches, npm caches, restarting process on :8081, where else could this be coming from? 

```
error: bundling failed: SyntaxError: /Users/nikkwong/iq-client/index.js: Unexpected token < (19:12)
  17 |     render() {
  18 |         return (
> 19 |             <View>Hi</View>
     |             ^
  20 |         )
  21 |     }
  22 | }
```

**Comment by sujitpk-perennial** [comment]
@nikkwong are you able to solve this issue?
