### ISSUE TITLE
[TextInput] Password Prop Regression in 0.6.0rc

### ISSUE THREAD

**Issue by bryanhelmig** [facebook/react-native#1551]
In my case it is a component like:

```jsx
          <TextInput
            placeholder={'Password'}
            style={[styles.bordered, styles.loginPaneTextInput]}
            value={this.state.password}
            password={true}
            onChangeText={(text) => this.setState({password: text})}
          />
```

In 0.5.0 it renders the proper "bullets" - in 0.6.0rc it renders a normal text field with no "bullets".

> Note: obviously comitting a faux pas passing the `value={this.state.password}` - it's just a hack so I don't have to type my localhost API password a bajillion times when testing... :-P I realize the element isn't "controlled" per se.

**Comment by marcshilling** [comment]
Yep - just discovered this myself.

**Comment by alinz** [comment]
@bryanhelmig, I had the similar issue, so I started look into what has been changed for RCTTextField, nothing! weird!!! 

AND, I found that instead of using `password` property, you can use `secureTextEntry`.

I think we should use different magic spell. :P

**Comment by jawadrehman** [comment]
Comparing with 0.5 , I did this and it worked.. 

secureTextEntry={this.props.password || this.props.secureTextEntry} on line 435 of Components/TextInput/TextInput.js

**Comment by marcshilling** [comment]
The `password` prop is working for me now on 0.6.0.

**Comment by brentvatne** [comment]
FYI, tangential to this issue is #584 - it's awkward that we have both `password` and `secureTextEntry`, so it would be nice to pick something that is as closely aligned as possible to web naming conventions and deprecate those. Contributions welcome!

**Comment by grabbou** [comment]
Password not working for me, but secureTextEntry works out of the box. Please @brentvatne remember about putting a note on that in the changelog when we have the final solution which one to use.

**Comment by leoasis** [comment]
Confirmed that it only works when setting `secureTextEntry` and not with just `password` in `0.6.0`. 

One extra thing I noticed since I'm using react-hot-loader is that if you remove the `secureTextEntry` prop, after having it set to some value (true or false), you get the message `Error setting property 'secureTextEntry' of RCTTextField with tag #275: RCTTextField does not have setter for `secureTextEntry` property`

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/textinput-password-prop-regression-in-060rc
