### ISSUE TITLE
can't initial Animated in componentDidMount in Android

### ISSUE THREAD

**Issue by jiarWang** [facebook/react-native#15512]
(Android RN0.47)I code this
```js
'use strict';
let _animateHandler;
class MAnimated extends Component{

    constructor(props){
        super(props);

        this.state={
            opacityAnmValue: new Animated.Value(0),
        }
    }

    componentDidMount(){
        _animateHandler = Animated.timing(
            this.state.opacityAnmValue,
            {
                toValue: 1,
                duration: 3000,
                easing: Easing.bezier(0.15, 0.73, 0.37, 1.2)
            }
        );
    }

    _onPress(){
        _animateHandler.start && _animateHandler.start();
    }

    render(){
        return (
            <View style={styles.container}>
            <Animated.View style={[styles.content, {opacity: this.state.opacityAnmValue}]}>
                <Text>hi</Text>
            </Animated.View>
            <TouchableOpacity onPress={() => this._onPress()} style={styles.btnContent}>
            <View><Text>Start Animated</Text></View>
            </TouchableOpacity>
            </View>
        );
    }
}
```
 When i press this `TouchableOpacity` , it throw error(undefined is not an object(evaluating '_animatedHandler.start'))with a red screen , ,however, it's works when i code like below:
```js
constructor(props){
        super(props);

        this.state={
            opacityAnmValue: new Animated.Value(0),
        }
    }

    componentDidMount(){
    }

    _onPress(){
        _animateHandler = Animated.timing(
            this.state.opacityAnmValue,
            {
                toValue: 1,
                duration: 3000,
                easing: Easing.bezier(0.15, 0.73, 0.37, 1.2)
            }
        ).start();
       // _animateHandler.start && _animateHandler.start();
    }
render(){
/**no change with render**/
}
```
Why the frist code way can't work ? thank you for your answer

**Comment by dabit3** [comment]
You need to call `.start() `if you want the animation to start. Is there any reason why you do not want to call `.start`?

**Comment by jiarWang** [comment]
As you can see, I initial the animation in `componentDidMount()`  instead of  in `_onPress()`(I guess if I code in this way, it would improve my user experience by reduce _onPress-runnig time, but I not really sure ),and I call it on`_onPress()`, what I want is that the animation will not `.start` until users press my button.

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
