### ISSUE TITLE
Incorrect bundle when serving TicTacToe

### ISSUE THREAD

**Issue by john-difool** [facebook/react-native#1552]
npm start && npm install from github project root. 

http://localhost:8081/Examples/TicTacToe/TicTacToeApp.includeRequire.runModule.bundle

is loading then I get the parsing error (... module.exports = ;}else ... ) line 35K ish.

module.exports = POPAnimationMixin;}});
__d('POPAnimation',["NativeModules","ReactPropTypes","createStrictShapeTypeChecker","getObjectValues","invariant","merge"],function(global, require, requireDynamic, requireLazy, module, exports) {  'use strict';

var RCTPOPAnimationManager=require('NativeModules').POPAnimationManager;
if(!RCTPOPAnimationManager){

module.exports = ;}else 
{

var ReactPropTypes=require('ReactPropTypes');
var createStrictShapeTypeChecker=require('createStrictShapeTypeChecker');
var getObjectValues=require('getObjectValues');
var invariant=require('invariant');
var merge=require('merge');

var RCTTypes=RCTPOPAnimationManager.Types;
var RCTProperties=RCTPOPAnimationManager.Properties;

**Comment by john-difool** [comment]
This line in POPAnimation.js is creating this issue:

if (!POPAnimationOrNull) {
  // POP animation isn't available in the OSS fork - this is a temporary
  // workaround to enable its availability to be determined at runtime.
  module.exports = (null : ?{});
} else {

**Comment by brentvatne** [comment]
This is an issue with Packager that has since been fixed: #1526 - thanks for reporting! :smile:
