### ISSUE TITLE
[Getting Started] react-native run-ios got error: TransformError - Unexpected token

### ISSUE THREAD

**Issue by phuongwd** [facebook/react-native#15524]
### Is this a bug report?

Bundling `index.ios.js`  [development, non-minified, hmr disabled]  0.0% (0/1), failed.
error: bundling failed: "TransformError: /Users/imac/Documents/react-native/AwesomeProject/index.ios.js: Unexpected token ) (While processing preset: \"/Users/imac/Documents/react-native/AwesomeProject/node_modules/babel-preset-react-native/index.js\")"

### Environment

1. `react-native -v`: 0.47.1
2. `node -v`: 6.10.2
3. `npm -v`: 5.3.0

Then, specify:

- Target Platform: iOS

- Development Operating System:  macOS Sierra

- Build tools: Terminal

### Steps to Reproduce

Follow step by step as guide **Building Projects with Native Code** http://facebook.github.io/react-native/docs/getting-started.html#getting-started

### Actual Behavior
Got error message as screenshot:
![simulator screen shot aug 17 2017 10 45 59 am](https://user-images.githubusercontent.com/2460806/29395414-dd3a0406-833a-11e7-9c75-595b09f2d988.png)

![screen shot 2017-08-17 at 10 56 06 am](https://user-images.githubusercontent.com/2460806/29395421-e3e2c022-833a-11e7-83b8-8203812e9a2a.png)

**Comment by hramos** [comment]
Sounds like you have an error in your index.ios.js file, can you include the actual contents of the file?

**Comment by phuongwd** [comment]
@hramos 
yes, I can. Its Sample React Native App

```
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';

export default class AwesomeProject extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit index.ios.js
        </Text>
        <Text style={styles.instructions}>
          Press Cmd+R to reload,{'\n'}
          Cmd+D or shake for dev menu
        </Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

AppRegistry.registerComponent('AwesomeProject', () => AwesomeProject);

```

**Comment by arufian** [comment]
Got this today, but not yesterday.

**Comment by arufian** [comment]
probably related with this #15513

**Comment by tmkst2607** [comment]
@arufian Thank you so much!

**Comment by phuongwd** [comment]
@arufian  thank you.

**Comment by ShubhamBabhulkar** [comment]
@arufian 
npm remove babel-preset-react-native   
is  ok but
npm add babel-preset-react-native@2.1.0  its not work

**Comment by charpeni** [comment]
Duplicate of #15513

**Comment by rajankonar** [comment]
@arufian Thanks

**Comment by DevelopHack** [comment]
This is bug in the new version of babel-preset-react-native 3.0.0 then.. 
**step1**: npm remove babel-preset-react-native 
**step 2**: go to package.json and change of version on this line "babel-preset-react-native": "3.0.0" by  "babel-preset-react-native": "2.1.0" 
**step 3**: delete of node_modules and run this command npm install

**Comment by machinefixer** [comment]
@sharathprabhal , try to close the terminal that opened by the packager, it runs package at port 8081, close the it will terminate the package, then you re-run `react-native run-ios`, it should work.

**Comment by tobefine** [comment]
thanks

**Comment by sBush265** [comment]
@arufian Thank you so much that helped me out.

**Comment by leandrodavimg** [comment]
@machinefixer answer solved my problem.
Thanks

**Comment by sospedra** [comment]
Still broken. Repro:

https://github.com/sospedra/RNAnimated

**Comment by hramos** [comment]
Duplicate of #15513

**Comment by zubko** [comment]
I had this issues while importing [react-native-collapsible](https://github.com/oblador/react-native-collapsible).
Upgrading `babel-preset-react-native` to `3.0.2` solved it for me.

**Comment by nikkwong** [comment]
I'm running into this in ```^5.0.0```. Anyone else having this problem? I've tried several different versions of ````babel-preset-react-native``` and haven't had any luck.
