### ISSUE TITLE
Unable to load images with the below component

### ISSUE THREAD

**Issue by srameshr** [facebook/react-native#15528]
### Is this a bug report?

YES

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.) YES

### Environment

1. `react-native -v`: 0.47.1
2. `node -v`: 8.3.0
3. `npm -v`: 5.3.0
4. `yarn --version`:

Then, specify:

- Target Platform: iOS

- Development Operating System: MACOS

- Build tools: iOS

### Steps to Reproduce
```
RCTJSONStringify() encountered the following error: Invalid number value (infinite) in JSON write
RCTJSONStringify() encountered the following error: Invalid number value (NaN) in JSON write

```
I get this error, when loading images.

Here are the console outputs:
```
Reloading image https://apple.wallpapersfine.com/wallpapers/original/750x1334/w-13330.jpg as size {inf, inf}
Reloading image https://dummyimage.com/750x1334/ffffff/000000.png&text=Test as size {inf, inf}
 RCTJSONStringify() encountered the following error: Invalid number value (infinite) in JSON write
Invalid layout for (200)<RCTView: 0x7fdf461a3c60; reactTag: 200; frame = (0 0; 7.60333e+37 667); layer = <CALayer: 0x7fdf461bc760>>. position: {nan, 333.5}. bounds: {{0, 0}, {nan, 667}}
```
### Reproducible Demo

```
<View style={{ flex: 1 }}>
  <FitImage
    resizeMode="contain"
     source={{ uri: 'https://apple.wallpapersfine.com/wallpapers/original/750x1334/w-13330.jpg'  }}
  />
</View>
```

**Comment by dabit3** [comment]
Have you filed an issue at the [react-native-fit-image](https://github.com/huiseoul/react-native-fit-image) repo? This looks like it could have something to do with that library.

**Comment by srameshr** [comment]
@dabit3 Well, It happens even with ```<Image />``` tag. It used to work fine until I upgraded my whole project yesterday. 
I am also using native navigation. Let me post it there.
