### ISSUE TITLE
Share does not work for sharing to facebook

### ISSUE THREAD

**Issue by pigflymoon** [facebook/react-native#15523]
### Is this a bug report?

(write your answer here)
Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.)
Yes
### Environment

1. `react-native -v`:0.44.0
2. `node -v`:6.8.1
3. `npm -v`:4.1.2
4. `yarn --version`:

Then, specify:

- Target Platform:
iphone 6s
ios 10.2

- Development Operating System:
Target Platform: iOS
Development Operating System: macOS Sierra 10.12.3
 

- Build tools: Using Xcode 8.3.2

### Steps to Reproduce

(Write your steps here:)

1.When build the app to run in my iphone device, share text to facebook app, it works for other apps(twitter, pinteres etc.) the app share dialogue didn't come out. 

2. code according to https://facebook.github.io/react-native/docs/share.html

### Expected Behavior

When click share button, share to facebook share dialogue should come out as expected.
### Actual Behavior

facebook share dialogue didn't come out.

### Reproducible Demo

https://snack.expo.io/r1kV4Yzu-
when click share links, share to facebook doesn't work, other social app works.

Thanks in advance!

**Comment by hramos** [comment]
Does this reproduce on 0.47.1?

**Comment by pigflymoon** [comment]
I tried     "react": "16.0.0-alpha.12",
    "react-native": "0.47.1",

this morning, still couldn't work when share to facebook app. @hramos

**Comment by askarhu** [comment]
I could reproduce the same on react-native: 0.48.0 In my case, the dialog came up on the device but the content I passed-in was empty. Sharing on rest of the networks worked just fine.

**Comment by malithjkmt** [comment]
same as @askarhu  is happening to me also, any leads?

**Comment by NoRoboto** [comment]
I have the same issue, facebook lite works well.

**Comment by askarhu** [comment]
Can someone please answer here? It's been a big hold up for us so far. Couldn't ship it with the Facebook share dialog showing up empty regardless of what we set for title, message etc. Would greatly help if someone can chime in and take care of fixing this issue, or at least can point us in the right direction. There's no error getting reported.

**Comment by aidan2129** [comment]
Got the same issue on 0.48.3

**Comment by Badacadabra** [comment]
Same problem on 0.47.2 after updating the Facebook app (Android).

**Comment by easilver** [comment]
This is happening in my project as well, running react native 0.44.3

**Comment by Badacadabra** [comment]
Well... Apparently, this is not even a bug. It is part of the new Facebook policies. Check this out: https://react-native.canny.io/feature-requests/p/share-api-doesnt-populate-the-message-for-facebook

Honestly, it is great to have strict policies, but forbidding pre-filling is a terrible idea. Lots of apps will have a bad UX because of that.
