### ISSUE TITLE
react-native response error code 500

### ISSUE THREAD

**Issue by reza7rm** [facebook/react-native#15534]
Hello 
I'm encountering a strange issue ,  when I  use react-native run-android command on the template project which I've created using react-native init I get the following the red error page on the device:
![re-error](https://user-images.githubusercontent.com/13413278/29408379-366b57c4-835d-11e7-990e-0eb5f4a66a60.jpg)

and then it disappears leaving me with a totally blank page!
the packager terminal shows the following error:
![capture](https://user-images.githubusercontent.com/13413278/29408526-d3c42b72-835d-11e7-9a53-ac3eb80211c5.JPG)

Development OS: Win 7
react-native-cli: 2.0.1
react-native: 0.47.1
node-v: 6.11.2
npm -v: 3.10.10
yarn --version: 0.27.5
device android version:6.0.1

**Comment by adon94** [comment]
I was getting the same error today. For me, I fixed by downgrading babel-preset-react-native from 3.0.0 to 1.9.2 in my package.json.

`"devDependencies": {
		"babel-jest": "20.0.3",
		"babel-preset-react-native": "1.9.2",
		"jest": "20.0.4",
		"react-test-renderer": "16.0.0-alpha.12"
	}`

Then just run 'yarn' in your terminal

**Comment by reza7rm** [comment]
Thank you very much @adon94 , you saved a day !

**Comment by charpeni** [comment]
Should be fixed in the next release of `babel-preset-react-native`.

**Comment by charpeni** [comment]
@facebook-github-bot duplicate #15513

**Comment by haru1313** [comment]
Hello,
I'm getting this error "The development server returned response code:500" 
I decremented the version of the dependencies but still the error is not going.

Please help.

**Comment by blackwine93v** [comment]
Did you try to connect on same wifi network (phone & computer)?
