### ISSUE TITLE
OnLayout not returning position with respect to screen

### ISSUE THREAD

**Issue by James2516** [facebook/react-native#15535]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

1. `react-native -v`:  
react-native-cli: 2.0.1
react-native: 0.45.1
2. `node -v`: v6.11.0
3. `npm -v`: 3.10.10

Then, specify:

- Target Platform: Android

- Development Operating System: Windows

- Build tools: 

### Steps to Reproduce

(Write your steps here:)

I need to detect if component A's position is within component B when pan gesture (drag) on A is released. However, the position from `onPanResponderRelease`'s `gesture.moveY` is measured with respect to the entire screen, whereas the position returned from A's `onLayout`is measured with respect to the parent view. So i'd need to know the parent view's current height to reconcile the differences.

### Expected Behavior

There should be a function to return the position with respect to the entire screen.

### Actual Behavior

see above

### Reproducible Demo

see above

**Comment by hramos** [comment]
Thanks for opening the issue! As it happens, we're using GitHub to track bugs in React Native. If you'd like to submit this as a feature request, please go ahead and create an entry on [Canny](https://reactnative.canny.io/feature-requests). It has a voting system and if the feature gets a good amount of votes, it will have a greater chance of being implemented by the community. Closing this now, thanks for understanding!
