### ISSUE TITLE
Inspector is broken in RTL

### ISSUE THREAD

**Issue by iddan** [facebook/react-native#15530]
### Is this a bug report?

Yes.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes.

### Environment

1. `react-native -v`: 0.47.1
2. `node -v`: 8.2.1
3. `npm -v`: 5.3.0
4. `yarn --version`: 0.27.5

Then, specify:

- Target Platform: IOS and Android

- Development Operating System: macOS

- Build tools: Xcode
- Is the issue specific to a particular iOS or Android SDK? no.

### Steps to Reproduce

(Write your steps here:)

1. Use RTL language or enforce RTL layout
2. open inspector
3. try to inspect an element aligned to the left or to the right

### Expected Behavior

The element bounding box should be coloured

### Actual Behavior

The bounding box is aligned to the opposite side.
<img width="378" alt="screen shot 2017-08-17 at 11 38 21" src="https://user-images.githubusercontent.com/12671072/29403302-9ddcaa92-8340-11e7-807b-2decff6db07c.png">

**Comment by iddan** [comment]
This issue should definitely remain open

**Comment by mhemrg** [comment]
It's a bug, definitely.
