### ISSUE TITLE
Render Images with borderRadius in FlatList/ScrollView only on android 5.0 will render black circle.

### ISSUE THREAD

**Issue by tsaohucn** [facebook/react-native#15537]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

1. `react-native -v`: 0.47.1
2. `node -v`: v6.9.4
3. `npm -v`: 5.3.0
4. `yarn --version`: v0.27.5

Then, specify:

- Target Platform:  android : 5.0/ 6.0 /7.0

- Development Operating System:  macOS

- Build tools: buildToolsVersion : 25.0.2

### Steps to Reproduce

1. create ListView/ScrollView 
2. render each Image item with borderRadius(props or style)
3. build in android 5.0/6.0/7.0 , and android 6.0/7.0 render correct, only android 5.0 render incorrect

### Expected Behavior

* android 6.0/7.0 render correct as below

<img width="373" alt="2017-08-17 10 54 14" src="https://user-images.githubusercontent.com/6713879/29418504-10d5a5fe-839f-11e7-9690-4ade73c158cc.png">

### Actual Behavior

android 5.0 render incorrect as below

<img width="378" alt="2017-08-16 11 43 28" src="https://user-images.githubusercontent.com/6713879/29418512-192fefd4-839f-11e7-81d5-6c9f74bfda02.png">

* If I cancel borderRadius in android 5.0 then it render correct as below

<img width="370" alt="2017-08-17 11 00 49" src="https://user-images.githubusercontent.com/6713879/29418808-fa748acc-839f-11e7-8659-31e3db190d03.png">

So it seem like the picture will render incorrect(black circle) when use borderRadius with image in FlatList/ScrollView on android 5.0

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by ol2dd** [comment]
+1

**Comment by ranjithnori** [comment]
Still experiencing this issue on 0.48.4. Please reopen this.

**Comment by svbutko** [comment]
There's a workaround (_not a solution!_) which can solve this issue, **BUT!** it can have significant performance implications:

Place this line into application tag of AndroidManifest.xml:
`android:layerType="software"`

Or you can try an make your own component (which is slightly better) where you can put this line:
`myView.setLayerType(View.LAYER_TYPE_SOFTWARE, null);`

**Comment by HsanBenJobrane** [comment]
+1

**Comment by sianlasaga** [comment]
Same problem. I browsed some issues related to this but none of them were solved.

**Comment by svbutko** [comment]
@sianlasaga, If you don't want to use software layer type, you can always place your image inside of the view which will be having border radius, it's going to work but edges of your image will be slightly sharp and idk how it can be solved atm.

**Comment by sianlasaga** [comment]
@svbutko, thanks man it works but it should have overflow: 'hidden' in view. And yeah you're right the edges of the image is sharp. Well at least it's a partial solution atm.

**Comment by svbutko** [comment]
@sianlasaga, overflow: "hidden" doesn't work correctly on Android atm and it's better to avoid using it extensively, I prefer to change the background's component instead of using this property.

**Comment by tandat2209** [comment]
+1

**Comment by davidmarciano** [comment]
+1
