### ISSUE TITLE
unable to create project , error as below！  please help 。

### ISSUE THREAD

**Issue by hpze2000** [facebook/react-native#1553]
$ react-native init AwesomeProject
This will walk you through creating a new React Native project in /Users/johnson/AwesomeProject
npm WARN engine stacktrace-parser@0.1.1: wanted: {"node":"~0.10"} (current: {"node":"0.12.4","npm":"2.10.1"})

ws@0.4.31 install /Users/johnson/AwesomeProject/node_modules/react-native/node_modules/ws
(node-gyp rebuild 2> builderror.log) || (exit 0)

**Comment by checkraiser** [comment]
Please upgrade Nodejs and npm to use the latest React Native.

**Comment by hpze2000** [comment]
@checkraiser TKS! bug error below again:

:~ johnson$ react-native init AwesomeProject
This will walk you through creating a new React Native project in /Users/johnson/AwesomeProject
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "--save" "react-native"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1

npm ERR! shasum check failed for /var/folders/fj/4nbp1d9x5b341std7mz5wpt80000gn/T/npm-3042-a56948e4/registry.npmjs.org/react-native/-/react-native-0.5.0.tgz
npm ERR! Expected: 287a1036d0c4de8861217e989cb46e8ea872fb11
npm ERR! Actual:   c89c9d8255c8ec34a25732e2665bd70e894b292a
npm ERR! From:     https://registry.npmjs.org/react-native/-/react-native-0.5.0.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/johnson/AwesomeProject/npm-debug.log
`npm install --save react-native` failed

**Comment by paramaggarwal** [comment]
It's probably just a download error, hence failure of checksum. Try deleting that cached file and try again.

**Comment by brentvatne** [comment]
There hasn't been any followup in a few days, @hpze2000 ping us if you're still having the issue, thanks! :smile:
