### ISSUE TITLE
[FlatList] when data is changed FlatList keeps scrolling

### ISSUE THREAD

**Issue by JohnKanev** [facebook/react-native#15533]
### Environment
react-native: 0.46.4 with expo
node 8.4.0
npm 5.3.0
yarn 0.27.5

- Target Platform: Android and IOS

- Development Operating System: Windows, Linux, masOS

### Steps to Reproduce

So i have a horizontal FlatList i start scrolling then quickly change the data prop 
the FlatList keeps scrolling until velocity is 0.

1.You scroll the FlatList 
2.Quickly change the data
then it keeps scrolling

### Expected Behavior
FlatList stops scroll after you change the data.

### Actual Behavior
FlatList keeps scrolling  after you change the data.

**Comment by hramos** [comment]
Can you reproduce the issue using [Snack](http://snack.expo.io)? This step is necessary for people to be able to see and debug the issue being reported.

**Comment by JohnKanev** [comment]
@hramos never mind my snapToCenter function was causing that kind of behaivor.
