### ISSUE TITLE
error: bundling failed: "TransformError [...] (While processing preset: node_modules [... \\babel-preset-react-native\\index.js")"

### ISSUE THREAD

**Issue by tudor2it** [facebook/react-native#15545]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

No

### Environment

1. `react-native -v`: react-native-cli: 2.0.1
2. `node -v`: v6.11.2
3. `npm -v`: 3.10.10
4. `yarn --version`: not using

Then, specify:

- Target Platform: Android

- Development Operating System: Windows 7 Professional SP1 x86_64

- Build tools: Android Studio 2.3.3, JRE 1.8.0_122, Android SDK Tools 26.0.2

### Steps to Reproduce

(Write your steps here:)

1. D:\path\path>react-native init project
2. cd project
3. react-native run-android

### Expected Behavior

The welcome React-Native screen should appear on the emulator screen.

### Actual Behavior

It throws the below error:

```
React packager ready.

Loading dependency graph, done.
Bundling `index.android.js`  [development, non-minified, hmr disabled]  ░░░░░░░░░░░░░
Bundling `index.android.js`  [development, non-minified, hmr disabled]  0.0% (0/1), f
ailed.
Bundling `index.android.js`  [development, non-minified, hmr disabled]  ░░░░░░░░░░░░░
error: bundling failed: "TransformError: D:\\path\\path\\project\\index.android.js: Unex
pected token ) (While processing preset: \"D:\\\\path\\\\path\\\\project\\\\node_modules
\\\\babel-preset-react-native\\\\index.js\")"
```

![image](https://user-images.githubusercontent.com/13054854/29449439-11ae52e4-83fb-11e7-97cd-f2b3c0160b36.png)

### Reproducible Demo

It is an empty standard project as it is described in https://facebook.github.io/react-native/docs/getting-started.html > Building Projects with Native Code.

**Comment by Kennytian** [comment]
some here +1

**Comment by emilioicai** [comment]
+1

**Comment by tudor2it** [comment]
@Kennytian Thank you for the solution. I have known about the workaround. The issue has appeared a few days ago and I've expected to disappear. But it is still there and it's frustrating that the react-native team didn't fix it. I'm desperate to finish a project and I'm only struggling with all kind of errors because versions of packages and compilers don't match.

**Comment by bissmp** [comment]
+1 
workaround didnt fix it in my app:

npm: 5.0.1
react-native-cli: 2.0.1
react-native: 0.47.1
node: v7.9.0

**Comment by charpeni** [comment]
@facebook-github-bot duplicate #15513

**Comment by ShubhamBabhulkar** [comment]
for yarn used following Commands

yarn remove babel-preset-react-native 
 yarn add babel-preset-react-native@2.1.0

for npm used following Commands

npm uninstall babel-preset-react-native
npm install babel-preset-react-native@2.1.0

**Comment by oliverraf** [comment]
This work like a charm

@tudor2it work around:  npm install --save-dev babel-preset-react-native@2.1.0

**Comment by kwesihackman** [comment]
workaround fixed it for me

**Comment by gjvpaet** [comment]
@Kennytian workaround fixed it thanks!

**Comment by uurtsaikhb** [comment]
@Kennytian  workaround fixed it, thank you

**Comment by jmacias54** [comment]
@Kennytian  fixed it, thank you so much

**Comment by vegano1** [comment]
@ShubhamBabhulkar This fixed my issue as well. Thank you.

**Comment by Ghayyas** [comment]
@Kennytian Great Thanks it works.. :+1:

**Comment by sospedra** [comment]
Still broken. Repro:

https://github.com/sospedra/RNAnimated

**Comment by ChenYCL** [comment]
step1   
npm install --save-dev babel-preset-react-native@2.1.0
step2
npm update

**Comment by duckdonghwan** [comment]
@Kennytian fixed it! Great Thanks it works.. :+1:

**Comment by lavarajallu** [comment]
Gettting this Error In Ios

`TransformError: /Users/stellent/Desktop/terapanth/index.ios.js: Couldn't find preset "babel-preset-react-native-stage-0/decorator-support" relative to directory "/Users/stellent/Desktop/terapanth"`

**Comment by Shaunakdas** [comment]
Getting similar error in android
```
Couldn't find preset "babel-preset-react-native-stage-0/decorator-support" relative to directory 
```

**Comment by tekslave** [comment]
1. Open '.barbelrc' file in your project root and change the preset

```
{
  "presets": [
    "babel-preset-react-native-stage-0/decorator-support"
  ],
  "env": {
    "development": {
      "plugins": [
        "transform-react-jsx-source"
      ]
    }
  }
}
```
**change to**
```
{
  "presets": [
    "react-native"
  ],
  "env": {
    "development": {
      "plugins": [
        "transform-react-jsx-source"
      ]
    }
  }
}
```

**Comment by anderson9149** [comment]
npm reinstalls did not work for me.  Only Yarn method

yarn remove babel-preset-react-native
yarn add babel-preset-react-native@2.1.0

**Comment by Poukai** [comment]
I am getting ``` error: bundling failed: TypeError: Cannot read property 'bindings' of null ```

**Comment by wesleyguirra** [comment]
getting the same error here

**Comment by YouCii** [comment]
I love you ma~
@Kennytian

**Comment by empitechathu** [comment]
give this man (@Kennytian) a medal

**Comment by zhangmingnjun** [comment]
一直挣扎在版本，编译不匹配的坑里，rn team要加油！
