### ISSUE TITLE
Image doesn't support  local  animated webp

### ISSUE THREAD

**Issue by hanxk** [facebook/react-native#15543]
### Environment

1. `react-native -v`:  0.47.1
2. `node -v`: v8.3.0
3. `npm -v`: 5.3.0

 Build tools: Android Studio 

### React Code:
 **it not works:**    
```
<Image source={require('../../imgs/ezgif-1-cbfa2c9256.webp')}  style={{width: 120, height:120 }}/>
```

**it works :**  
`<Image source={{uri:'https://im.ezgif.com/tmp/ezgif-1-cbfa2c9256.webp'}}  style={{width: 120, height:120 }}/>`

### Android:
    compile 'com.facebook.fresco:animated-base-support:1.0.1'
    compile 'com.facebook.fresco:animated-gif:1.0.1'
    compile 'com.facebook.fresco:animated-webp:1.0.1'
    compile 'com.facebook.fresco:webpsupport:1.0.1'
    compile 'com.facebook.fresco:webpsupport:1.0.1'

### Error Log:

TypeError: unsupported file type
    at lookup (/code/workspace/dudu/node_modules/image-size/lib/index.js:35:9)
    at /code/workspace/dudu/node_modules/image-size/lib/index.js:93:22
    at /code/workspace/dudu/node_modules/image-size/lib/index.js:50:9
    at /code/workspace/dudu/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)

![image](https://user-images.githubusercontent.com/5105604/29443306-c46d5192-8409-11e7-88b5-b8c81cf8fe4f.png)

**Comment by ide** [comment]
Looks like this library https://github.com/image-size/image-size might not support animated webp. That library needs to be updated first.

**Comment by MindFreeze** [comment]
If someone could at least update the docs, because the seem to be a lie now http://facebook.github.io/react-native/releases/0.47/docs/image.html#gif-and-webp-support-on-android

**Comment by StevenGBrown** [comment]
This looks the same as #13102 which was closed due to inactivity. I can reproduce the error with React Native 0.47, but it works with v0.48.0-rc.1 which has a newer version of image-size.

**Comment by StevenGBrown** [comment]
Issue has been fixed. See my last comment.
