### ISSUE TITLE
[android] react-native unlink doesn't remove strings added in strings.xml

### ISSUE THREAD

**Issue by dhei** [facebook/react-native#15555]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

1. `react-native -v`: 0.47.1
2. `node -v`: 6.11.2
3. `npm -v`: 4.6.1
4. `yarn --version`: 0.27.5

Then, specify:

- Target Platform: Android

- Development Operating System: macOS 10.12.6

- Build tools: Android Studio

### Steps to Reproduce

(Write your steps here:)

1. react-native init reproProject
2. cd reproProject
2. npm install mobile-center-crashes mobile-center-analytics --save
3. react-native link
4. react-native unlink mobile-center-crashes

### Expected Behavior

With `react-native link` linking two npm package "mobile-center-crashes" and "mobile-center-analytics", two strings are added to /android/app/src/main/res/values/strings.xml as a result. 

```xml
<string moduleConfig="true" name="mobileCenterCrashes_whenToSendCrashes">ALWAYS_SEND</string>
<string moduleConfig="true" name="mobileCenterAnalytics_whenToEnableAnalytics">ALWAYS_SEND</string>

```

I expect `react-native unlink mobile-center-crashes` to remove `<string moduleConfig="true" name="mobileCenterCrashes_whenToSendCrashes">ALWAYS_SEND</string>` in the /android/app/src/main/res/values/strings.xml.

### Actual Behavior

However, in android project, `react-native unlink mobile-center-crashes` remove everything except `<string moduleConfig="true" name="mobileCenterCrashes_whenToSendCrashes">ALWAYS_SEND</string>` in the /android/app/src/main/res/values/strings.xml. It makes everything right except the strings.xml.

### Reproducible Demo

I have created a repro project following all the 5 steps in "Steps to Reproduce" [here](https://github.com/dhei/react-native-android-unlink-issue-repro). You can see after unlink, string is not removed from [/android/app/src/main/res/values/strings.xml](https://github.com/dhei/react-native-android-unlink-issue-repro/blob/master/android/app/src/main/res/values/strings.xml).

**I believe I was able to identify the root cause of this issue.** It is caused by a bug in the regular expression at [Ln21-Ln23](https://github.com/facebook/react-native/blob/0.48-stable/local-cli/link/android/unregisterNativeModule.js#L21-L23) in the react-native/local-cli/link/android/unregisterNativeModule.js. 

```javascript
  strings.replace(
    /moduleConfig="true" name="(\w+)">(.*)</g,
    (_, param, value) => {
      params[param.slice(toCamelCase(name).length + 1)] = value;
    }
  );
```
`param.slice(toCamelCase(name).length + 1)` is making an assumption that all the matching strings _must_ comes from npm package with the same length of the name. In my case, I have two npm packages "mobile-center-crashes" and "mobile-center-analytics" with different length of package name. Regular expression matching `mobileCenterCrashes_whenToSendCrashes` and `mobileCenterAnalytics_whenToEnableAnalytics`, so it doesn't work because they have different length.

Looks like I am running into an edge case that this regular expression doesn't work well. Let me know if I you need more information for reproducing this bug.

**Comment by wuyunqiang** [comment]
maybe you can try 
yarn add xxx
react-native-link
react-native-unlink 
yarn remove xxx.

**Comment by dhei** [comment]
@wuyunqiang Thanks. It won't help because the problem is actually with `react-native unlink <package>`. It has nothing to do with installing or removing the package, so `yarn remove <package>` won't help.

**Comment by dhei** [comment]
This bug still exists in react-native@0.49. My workaround is quite straight forward--manually remove extra strings in strings.xml. I guess not many people are bumping into this issue, but it creates some trouble for automating linking and unlinking process.
