### ISSUE TITLE
[Navigator] initialRoute vs initialRouteStack after update to 0.5.0

### ISSUE THREAD

**Issue by JonasJonny** [facebook/react-native#1555]
Hello,
I had working Navigation but after update to 0.5.0 version I have just blank screen.

I found out if I remove "initialRouteStack={ROUTE_STACK}" from Navigator then my first INIT_ROUTE_INDEX route/component in ROUTE_STACK {name: 'HomeNavigator', component: HomeNavigator, index: 0} is loaded fine. 

(Of course then I have missing "Invariant Violation: Cannot jump to route that is not in the route stack" if any other tab is selected.)

Thank you for any help.
cc @ericvicenti, @vjeux, @ide, @brentvatne 

```
var NavigationBar = require('react-native-navbar');

var ROUTE_STACK = [
    {name: 'HomeNavigator', component: HomeNavigator, index: 0},
    {name: 'SearchNavigator', component: SearchNavigator, index: 1},
    {name: 'ActivityNavigator', component: ActivityNavigator, index: 2},
    {name: 'ProfileNavigator', component: ProfileNavigator, index: 3},
];
var INIT_ROUTE_INDEX = 0;
```
```
class MainScreen extends Component {

    constructor(props) {
        super(props);
        this.state = {
            isAnimating: 0,
        };
    }

    render() {

        return (
            <Navigator
                ref={(navigator) => {
                  this._navigator = navigator;
                }}
                renderScene={this.renderScene.bind(this)}
                initialRoute={ROUTE_STACK[INIT_ROUTE_INDEX]}
                initialRouteStack={ROUTE_STACK}
                configureScene={(route) => {
                      if (route.sceneConfig) {
                        return route.sceneConfig;
                      }
                      return Navigator.SceneConfigs.FloatFromRight;
                    }}
                navigationBar={
                        <Tabs
                            ref={(navBar) => { this.navBar = navBar; }}
                            navigator={this._navigator}
                            route={this.route}
                            onTabIndex={(index) => {
                                this._navigator.jumpTo(ROUTE_STACK[index]);
                            }}
                        />
                    }
                />
        );
    }

renderScene(route, navigator) {

        console.log('1-route', route);
        console.log('1-navigator', navigator);
        console.log('1-this.state.tabIndex', this.state.tabIndex);
     
        var Component = route.component;

        return (
            <View style={styles.container}>
                <Component {...route.passProps} navigator={navigator} route={route}/>
            </View>
        );
    }
}

- - -
// style
container: {
   flex: 1,
   backgroundColor: '#ebebeb',
},

**Comment by JonasJonny** [comment]
First console part is with initialRouteStack removed.
Second is shown when I add initialRouteStack={ROUTE_STACK}.

![consoletabs](https://cloud.githubusercontent.com/assets/1771823/8035928/5d5013ce-0df4-11e5-9e59-52dbba0945ae.png)

**Comment by brentvatne** [comment]
Is this happening for you on `master` as well? Is the render function being called on your `HomeNavigatorComponent`? I notice a couple of warnings there, you could try fixing those and see if that helps too

**Comment by JonasJonny** [comment]
Hah, the problem is not in routestack.
A few minutes ago I removed flexWrap: 'wrap', from style for RefreshableListView by accident and the right screen occurred. The same with ListView.

Can ListView have its own style?
Here is a demo https://rnplay.org/apps/4OGi4w.
Try to edit flexWrap: 'nowrap' <-> 'wrap'.

**Comment by browniefed** [comment]
@JonasJonny any movement on this? From you last comment it doesn't appear to be a navigation issue but a ListView issue now?

**Comment by JonasJonny** [comment]
It's not a navigation issue. The problem is flexWrap: 'wrap' on ListView.

**Comment by browniefed** [comment]
Ah I see now. `flexWrap` on a `ListView` is causing it to not render correctly.
Flipping it to `flexDireciton: 'column'` and wrapping it in a View solved the problem.

Check it out here https://rnplay.org/apps/tKH7ng

**Comment by browniefed** [comment]
Is that an acceptable solution @JonasJonny ?

**Comment by JonasJonny** [comment]
Looks good @browniefed, thanks for following.

(But still it is a little weird behaviour for 'wrap' and 'row'.)

**Comment by browniefed** [comment]
I don't know what to say haha, that's flexbox for you.

@brentvatne looks solved we can close this

**Comment by brentvatne** [comment]
@JonasJonny @browniefed - as long as that's the same behaviour as in the browser it looks like this issue is resolved. If either of you would like to validate that and post a link to a fiddle with the same situation that would be cool for reference! :smile: :tada:

**Comment by JonasJonny** [comment]
@browniefed, @brentvatne  IMO still weird.
This is how 
``
flexDirection: 'row',
        flexWrap: 'wrap',
        flex: 1,
``
should work
http://the-echoplex.net/flexyboxes/?fixed-height=on&display=flex&flex-direction=row&flex-wrap=wrap&justify-content=flex-start&align-items=flex-start&align-content=flex-start&order%5B%5D=0&flex-grow%5B%5D=0&flex-shrink%5B%5D=1&flex-basis%5B%5D=auto&align-self%5B%5D=auto&order%5B%5D=0&flex-grow%5B%5D=0&flex-shrink%5B%5D=1&flex-basis%5B%5D=auto&align-self%5B%5D=auto&order%5B%5D=0&flex-grow%5B%5D=0&flex-shrink%5B%5D=1&flex-basis%5B%5D=auto&align-self%5B%5D=auto&order%5B%5D=0&flex-grow%5B%5D=0&flex-shrink%5B%5D=1&flex-basis%5B%5D=auto&align-self%5B%5D=auto&order%5B%5D=0&flex-grow%5B%5D=0&flex-shrink%5B%5D=1&flex-basis%5B%5D=auto&align-self%5B%5D=auto&order%5B%5D=0&flex-grow%5B%5D=0&flex-shrink%5B%5D=1&flex-basis%5B%5D=auto&align-self%5B%5D=auto&order%5B%5D=0&flex-grow%5B%5D=0&flex-shrink%5B%5D=1&flex-basis%5B%5D=auto&align-self%5B%5D=auto&order%5B%5D=0&flex-grow%5B%5D=0&flex-shrink%5B%5D=1&flex-basis%5B%5D=auto&align-self%5B%5D=auto&order%5B%5D=0&flex-grow%5B%5D=0&flex-shrink%5B%5D=1&flex-basis%5B%5D=auto&align-self%5B%5D=auto

but in react-native I have whole screen white (my background everywhere is lightgray) and here https://rnplay.org/apps/4OGi4w "rows" are not next to each other or rendered to next row when width is exceeded.

Or am I missing something?
