### ISSUE TITLE
Animated.timing: TypeError: expected dynamic type `double', but had type `null' 

### ISSUE THREAD

**Issue by raitucarp** [facebook/react-native#15568]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

1. `react-native -v`: 0.46.1
2. `node -v`: v8.2.1
3. `npm -v`: 5.3.0
4. `yarn --version`:

Then, specify:

- Target Platform: Android

- Development Operating System: Linux

- Build tools: Android SDK, expo

### Steps to Reproduce

1. Use native driver alongside with big duration number in Animated timing:
```
Animated.timing(this.state.rotation, {
    toValue: 1,
    duration: 15200000,
    easing: Easing.linear,
    useNativeDriver: true,
})
```

### Expected Behavior

Create animation with big duration number such as 15200000 alongside with useNativeDriver should running smoothly as expected.

### Actual Behavior

got an error 
```
TypeError: expected dynamic type `double', but had type `null'
getDouble
    ReadableNativeArray.java
<init>
    FrameBasedAnimationDriver.java:37
startAnimatingNode
    NativeAnimatedNodesManager.java:197
execute
    NativeAnimatedModule.java:288
doFrameGuarded
    NativeAnimatedModule.java:112
doFrame
    GuardedFrameCallback.java:31
doFrame
    ReactChoreographer.java:136
doFrame
    ChoreographerCompat.java:107
run
    Choreographer.java:872
doCallbacks
    Choreographer.java:686
doFrame
    Choreographer.java:618
run
    Choreographer.java:860
handleCallback
    Handler.java:751
dispatchMessage
    Handler.java:95
loop
    Looper.java:154
main
    ActivityThread.java:6119
invoke
    Method.java
run
    ZygoteInit.java:886
main
    ZygoteInit.java:776
```
![image](https://user-images.githubusercontent.com/163585/29491974-1b4a4a7c-8597-11e7-83c3-02c7f6907b36.png)

**Comment by raitucarp** [comment]
@facebook-github-bot

**Comment by raitucarp** [comment]
Where is the team?

**Comment by wcandillon** [comment]
@raitucarp Where you able to solve your issue? I'm experiencing the same problem.

**Comment by raitucarp** [comment]
This issue is not resolved yet. I frustrating with this issue and switch to native dev approach.

**Comment by petsinho** [comment]
hey @raitucarp , I ran into a similar issue because I was using a module that was using React Native animations, but it seems since then. In my case, the `Animated.Spring` most likely changed and the module (https://github.com/GeekyAnts/react-native-hamburger) was not updated.
If you are using something with animations, I would check the code that runs under the hood.
Also have a look on https://facebook.github.io/react-native/docs/animated.html#value.
I tried disabling animations in the module as an experiment, and I no longer get the error

**Comment by JakeRawr** [comment]
Can you try not to use `useNativeDriver: true,` for android devices?
That might fix the error.

**Comment by yaronlevi** [comment]
When using useNativeDriver: false, same error

**Comment by pfeiffer** [comment]
Seeing this as well

**Comment by lavarajallu** [comment]
@JakeRawr  where i keep this line of code

**Comment by raitucarp** [comment]
Hi, please don't close this issue. I am investigating further about this issue.

**Comment by jaycee425** [comment]
similar issue on 0.53 using the LayoutAnimation on android 
I set as per instruction 
`if (Platform.OS === 'android') {
  UIManager.setLayoutAnimationEnabledExperimental && UIManager.setLayoutAnimationEnabledExperimental(true);
    }`
but I get the same error
