### ISSUE TITLE
index.android.js file not updates update not shown when run the app in windows 10 is any one help me to resolve this problem

### ISSUE THREAD

**Issue by Neha-Rajput** [facebook/react-native#15564]
### Is this a bug report?

(write your answer here)

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.)

### Environment

1. `react-native -v`:
2. `node -v`:
3. `npm -v`:
4. `yarn --version`:

Then, specify:

- Target Platform:

- Development Operating System:

- Build tools:

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by aspiringguru** [comment]
Please edit with the info requested in the contributing guidelines. Impossible to answer as written.
