### ISSUE TITLE
Bundling  'index.android.js' [development, non-minified, hmr disabled] 0.0%(0/1), failed

### ISSUE THREAD

**Issue by duanj3** [facebook/react-native#15575]
Is this a bug report?
Yes
Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?
No
Environment
1.react-native -v:
react-native-cli: 2.0.1
react-native: n/a - not inside a React Native project directory
2.node -v: v6.11.2
3.npm -v: v3.10.10
4.yarn --version: v0.27.5

Then, specify:
Platform: Android
Operating system: Windows 10 *64
Buidling tool: Android studio 2.3

Steps to Reproduce
1. react-native init myapp
2. cd myapp
3. react-native run-android

I have tried to do the _'yarn remove babel-preset-react-native'_ and 'yarn add babel-preset-react-native@2.1.0', still didn't work for me. 

Expected Behavior
Welcome to React Native Page

Actual Behavior
![image](https://user-images.githubusercontent.com/23101432/29496687-8c2fb916-860a-11e7-9fdc-a2ac00a4e5d4.png)

The development server returned response error code: 500

URL: http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false

Body:
{"message":"TransformError: C:\\Users\\Administrator\\jiekeapp\\index.android.js: Unexpected token ) (While processing preset: \"C:\\\\Users\\\\Administrator\\\\jiekeapp\\\\node_modules\\\\babel-preset-react-native\\\\index.js\")","type":"TransformError","lineNumber":0,"description":"","errors":[{"description":"","lineNumber":0}]}
processBundleResult
    BundleDownloader.java:170
access$100
    BundleDownloader.java:39
onResponse
    BundleDownloader.java:139
execute
    RealCall.java:135
run
    NamedRunnable.java:32
runWorker
    ThreadPoolExecutor.java:1113
run
    ThreadPoolExecutor.java:588
run
    Thread.java:818

This problem has got me stuck for 3 days, still can't solve it after I did a lot of searching. #15513 #15496 #15524 #14961 
Thanks for helping me ahead of time!

**Comment by gsabatie** [comment]
i have the same issue on windows

**Comment by guochao285575** [comment]
+1

**Comment by guochao285575** [comment]
Bundling `index.ios.js`  [development, non-minified, hmr disabled]  0.0% (0/1), failed.
error: bundling failed: "TransformError: /Users/guochao/Desktop/rndemo/AwesomeProject/index.ios.js: Unexpected token ) (While processing preset: \"/Users/guochao/Desktop/rndemo/AwesomeProject/node_modules/babel-preset-react-native/index.js\")"

**Comment by lndgalante** [comment]
Same problem here with macOS 10.12.6 and React Native 0.47.1

**Comment by kitsoftwaregroup** [comment]
Any fix with this issue ?

**Comment by huzcNo1** [comment]
Maybe because of  "babel-preset-react-native": "3.0.0"   ，  I have solved this problem by  back to 2.1.0

**Comment by FaridSafi** [comment]
+1

**Comment by FaridSafi** [comment]
uninstalling watchman fixed my issue

**Comment by duanj3** [comment]
@FaridSafi dude, I don't think I have installed watchman, couldn't find it at all

**Comment by afeifly** [comment]
"babel-preset-react-native": "3.0.0" change to 2.1.0 . still same problem.

**Comment by duanj3** [comment]
@huzcNo1 I think I have downgraded the version of react-native, the current version of react-native-cli is 2.0.1, but still doesn't work, and how do you back it to 2.1.0?

**Comment by huzcNo1** [comment]
@duanj3  
yarn remove babel-preset-react-native  
yarn add babel-preset-react-native@2.1.0

**Comment by duanj3** [comment]
@huzcNo1 yeah, that's exactly what I did before, and react-native-cli just automatically turned to 2.0.1, I mentioned in the issue as well, thanks anyway, have you got Wechat (QQ) or something if it doesn't bother you, cause I want to check that I didn't make it wrong

**Comment by huzcNo1** [comment]
Can  I  have a look  the file of package.json in your  project @duanj3

**Comment by duanj3** [comment]
@huzcNo1 
![image](https://user-images.githubusercontent.com/23101432/29525552-abd2135c-86c5-11e7-9e7e-9e1f2e503915.png)
oh, it shows "babel-preset-react-native": "3.0.0", what can I do?

**Comment by huzcNo1** [comment]
do this  in the root dir  of  you project
yarn remove babel-preset-react-native
yarn add babel-preset-react-native@2.1.0

**Comment by guochao285575** [comment]
run android fail -- Bundling `index.android.js`  [development, non-minified, hmr disabled]  0.0% (0/1), failed.
error: bundling failed: "TransformError: /Users/chaos/Desktop/demo/MyApp/index.android.js: Unexpected token ) (While processing preset: \"/Users/chaos/Desktop/demo/MyApp/node_modules/babel-preset-react-native/index.js\")"


run ios success...
Why?

**Comment by afeifly** [comment]
@huzcNo1 Thank you .  in Mac, using npm remove and install 2.1.0,  that work!

**Comment by duanj3** [comment]
omg, it is solved, thanks a lot, but new issue comes out...nearly broke down
![image](https://user-images.githubusercontent.com/23101432/29526444-57fa79ba-86c8-11e7-8a3d-50d2d5d9a989.png)

**Comment by duanj3** [comment]
@huzcNo1 nothing to worry, I have fixed it, thank you so much, it has annoyed me for so long thanks

**Comment by guochao285575** [comment]
@huzcNo1 I do this,then run ios success  but run android failed...

**Comment by huzcNo1** [comment]
my pleasure @duanj3  @afeifly

**Comment by huzcNo1** [comment]
@guochao285575  I am  sorrry , maybe I don't known how to fix the problem that you come across

**Comment by guochao285575** [comment]
@huzcNo1 thank you anyway

**Comment by lndgalante** [comment]
Guys this solution fixed the problem for me: https://github.com/facebook/react-native/issues/15332#issuecomment-319770048
