### ISSUE TITLE
Question about Native Modules

### ISSUE THREAD

**Issue by sm2017** [facebook/react-native#15586]
According to https://facebook.github.io/react-native/docs/native-modules-android.html native android modules `extends ReactContextBaseJavaModule` , Is the module singleton?

If I have the following method
```java
@ReactMethod 
public void testMethod(String message, Promise promise) { 
    this.promise = promise;
}
```

and 

```js
MyModule.testMethod('A').then(function(result){
    console.log(result);
});

MyModule.testMethod('B').then(function(result){
    console.log(result);
});

MyModule.testMethod('C').then(function(result){
    console.log(result);
});
```

What happens exactly? is `MyModule.testMethod('C')` overwrite `this.promise` (the module is singleton ) OR each time the new instance of module is created and `promise` is a property and isolated?

**Comment by chirag04** [comment]
@facebook-github-bot stack-overflow
