### ISSUE TITLE
fontWeight='bold' cause Unexpected token

### ISSUE THREAD

**Issue by jiarWang** [facebook/react-native#15585]
I code like this:
```jsx
 <Text  style={{height: 25, textAlign: 'center', fontWeight='bold'}}>Starts:</Text>
```
My foolish cellphone give me a red screen, and tell me ***Unexpected token***, until i delete `fontWeight='bold'`.

Then I use the `fontWeight`  in `StyleSheet` ,  no red screen show.

**Comment by Amwam** [comment]
@jiarWang 
This is because you used `=` instead of `:` 

The following should work:
```js
<Text  style={{height: 25, textAlign: 'center', fontWeight: 'bold'}}>Starts:</Text>
```

Note: `fontWeight='bold'` vs `fontWeight: 'bold'`

**Comment by jiarWang** [comment]
wow, when i am blind.?  ..thank you very much
