### ISSUE TITLE
scrollView set style unuseful

### ISSUE THREAD

**Issue by wuyunqiang** [facebook/react-native#15581]
### Is this a bug report?

(YES/No)

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(YES)

### Environment

1. `react-native -v`:0.46.4
2. `node -v`:v8.3.0
3. `npm -v`:5.3.0
4. `yarn --version`:0.27.5

Then, specify:

- Target Platform: android && ios

- Development Operating System: mac10.12.5

- Build tools:webstorm

### Steps to Reproduce

code like that:
```
   renderTab = ()=> {
        return (
            <View style={{width:WIDTH,height:SCALE(100),backgroundColor:'blue',flexDirection:'row', justifyContent:'space-around', alignItems:'center'}}>
            <View><Text>我发起的</Text></View>
            {(this.state.data&&this.state.data.myIsLeader===1)?<View><Text>带我审批</Text></View>:null}
            {(this.state.data&&this.state.data.myIsLeader===1)?<View><Text>我已审批</Text></View>:null}
        </View>)
    };

    render(){
        return (
            <View style={{width:WIDTH,height:HEIGHT}}>
                <ScrollView
                    style={{backgroundColor:'red',width:WIDTH,height:HEIGHT-SCALE(200)}}>

            </ScrollView>
                {this.renderTab()}
        </View>
        );
    }
```
if I delet style={{width:WIDTH,height:HEIGHT}} or I set style={{flex:1}} will be ok.
Why?
### Expected Behavior

like that:
![expected](https://user-images.githubusercontent.com/13480948/29507687-cb45484a-8683-11e7-8ce7-4dde762fe165.png)

### Actual Behavior

![actual](https://user-images.githubusercontent.com/13480948/29507760-16197350-8684-11e7-8fdf-c892885b6fc7.png)

**Comment by Ehesp** [comment]
```
   renderTab = ()=> {
        return (
            <View style={{ flex: 1, height: 50, backgroundColor: 'blue', etc... }}>

        </View>)
    };

    render(){
        return (
            <View style={{ flex: 1 }}>
                <ScrollView
                    style={{ flex: 1 }}>

                </ScrollView> 
                {this.renderTab()}
        </View>
        );
    }
```

**Comment by chirag04** [comment]
use contentContainerStyle prop of scrollview.

**Comment by chirag04** [comment]
@facebook-github-bot stack-overflow
