### ISSUE TITLE
[rebound] how does rebound work in react-native?

### ISSUE THREAD

**Issue by threepointone** [facebook/react-native#1559]
- I was trying to get rebound.js to work in react native, and had to add `rebound.util.onFrame = global.requestAnimationFrame;` to make it work. However, I notice a number of RN components use rebound, but can't find a polyfill. How?

- I have a 'fix' for the rebound issue [here](https://github.com/facebook/rebound-js/pull/16/files), but it would be nice if we could special case it for RN. what 'test' works to detect react-native?

please and thank you.

**Comment by brentvatne** [comment]
@threepointone - can you post the code where you have a problem? I just tried this on my own project with `0.5.0` and this worked fine for me

**Comment by brentvatne** [comment]
@threepointone - full code example [on rnplay.org](https://rnplay.org/apps/qHU_5w)

**Comment by brentvatne** [comment]
@threepointone - [this is why it works without making that change](https://github.com/facebook/rebound-js/blob/master/rebound.js#L1124-L1126)

**Comment by brentvatne** [comment]
@threepointone - I believe [this is why it works](https://github.com/facebook/rebound-js/blob/master/rebound.js#L1120-L1122)

**Comment by threepointone** [comment]
really odd. I'm not able to reproduce this anymore (moved from 0.4.4 > 0.6.0-rc in the last couple of days), so maybe that's why. I was clearly seeing that `window` was not defined, and the node condition would fail, so `onFrame` would be undefined. 

Followup question - surely we can do faster than 60fps on react-native? 

I'll mark this bug as closed, sorry for the trouble.

**Comment by threepointone** [comment]
I tried this 
```js
rebound.util.onFrame = function(callback) {
  window.setTimeout(callback, 1000 / 120);
};
```
and it works well :) I haven't tried it with anything heavy yet, will report back after a day or so. 

/cc @willbailey

**Comment by brentvatne** [comment]
glad it was resolved @threepointone :smile:

**Comment by threepointone** [comment]
one last followup - looks like on RN, rebound taps into RN's requestAnimationFrame, and as such, is super performant.
