### ISSUE TITLE
TextInput breaks system spell check on Samsung devices (S8)

### ISSUE THREAD

**Issue by george-cz** [facebook/react-native#15590]
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

yes

### Environment

1. `react-native -v`: 0.46.4
2. `node -v`: v6.9.5
3. `npm -v`: 3.10.10
4. `yarn --version`: 0.21.3

Then, specify:

- Target Platform: Android (Samsung)

- Development Operating System: MacOS

- Build tools: using create-react-native-app and Expo

### Steps to Reproduce

(Write your steps here:)

1. Use Samsung S8 with latest firmware (should be reproducible S6 and above)
2. Enable Spell Checker in the phone menu
3. Create controlled `<TextInput value={this.state.val} onChangeText={this.onChange} editable={true} spellCheck={true} />`
4. Run the app and input some obviously wrong spelled text, (e.g. aiefsjaliesfj or adsjfaleifjlaisef :))

### Expected Behavior

I would expect the text input to underline the invalid text with red line, allowing me to click it and select from close correctly spelled candidates.

### Actual Behavior

The red line just flashes and then disappears, breaking the system spell check feature.

### Reproducible Demo

https://snack.expo.io/B1-6Lw_uW

Fire this up and insert some text.

**Comment by chirag04** [comment]
> The red line just flashes and then disappears, breaking the system spell check feature.

spell check is ios only.

**Comment by george-cz** [comment]
Well even though the prop might not be supported, TextInput still breaks the native functionality.
