### ISSUE TITLE
Something went wrong while linking. Error: Expected "/*", "//", or "{" but "<" found.

### ISSUE THREAD

**Issue by krishnads** [facebook/react-native#15598]
Hello there,

i have problem in installing the fbsdk . I am getting following error in my terminal and not able to proceed further .

> # Something went wrong while linking. Error: Expected "/*", "//", or "{" but "<" found.

I am also attaching a screenshot of what i am doing in terminal..

![screen shot 2017-08-22 at 1 21 20 pm](https://user-images.githubusercontent.com/16478904/29554468-dfbb927a-873c-11e7-8072-50353fd20040.png)

**Comment by grabbou** [comment]
Duplicate of #10032
