### ISSUE TITLE
Tap missed / taps ignored

### ISSUE THREAD

**Issue by jslz** [facebook/react-native#15606]
### Is this a bug report?

Yes, this is a bug report.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes, I have read it.

### Environment

1. `react-native -v`: react-native-cli: 2.0.1 react-native: 0.46.4
2. `node -v`: v6.11.1
3. `npm -v`: 5.3.0
4. `yarn --version`: 0.27.5

Then, specify:

- Target Platform:

iOS and Android

- Development Operating System:

Mac OS X 10.12.6

- Build tools:

For iOS release we are building via Xcode / Archive / upload to TestFlight. See down below for package.json.

### Steps to Reproduce

With our app's iOS release builds (unclear/untested if it also happens with Android) we are seeing taps on the screen get utterly ignored some times. The 2 main scenarios we reproduce are 

1) there's a harder to repro case where the user scrolls the list some, and then stops the scrolling, and then taps on another component on-screen, and the first tap is ignored/lost/missed/not seen. 

2) more 100% reproducible, while our ListView is scrolling, other things on the screen do not respond to taps. (We have tried using FlatList and for various reasons it is not an acceptable component for us to use, so we're using ListView.)

### Expected Behavior

taps should always work and never be missed/lost/ignored.

### Actual Behavior

It appears that RN is missing input events. Note that we are not talking about a delay. We are talking about events never being "seen" by the RN system.

```
  "dependencies": {
    "color": "^1.0.3",
    "moment": "^2.18.1",
    "query-string": "^4.3.4",
    "react": "16.0.0-alpha.12",
    "react-native": "0.46.4",
    "react-native-branch": "^2.0.0-beta.7",
    "react-native-code-push": "^2.1.0-beta",
    "react-native-contacts": "^0.8.1",
    "react-native-device-info": "^0.10.2",
    "react-native-dismiss-keyboard": "^1.0.0",
    "react-native-fabric": "^0.4.1",
    "react-native-fbsdk": "^0.6.0",
    "react-native-fcm": "tjlian616/react-native-fcm#503dd7a",
    "react-native-fetch-blob": "^0.10.8",
    "react-native-fs": "^2.5.1",
    "react-native-image-picker": "^0.26.3",
    "react-native-mail": "^3.0.4",
    "react-native-material-design-styles": "^0.2.6",
    "react-native-orientation": "^2.0.0",
    "react-native-progress": "^3.2.1",
    "react-native-sentry": "^0.14.0",
    "react-native-simple-toast": "0.0.6",
    "react-native-ux-cam": "^3.4.0",
    "react-native-view-shot": "^1.10.1",
    "react-native-youtube": "1.0.0-beta.2",
    "react-navigation": "^1.0.0-beta.9",
    "react-redux": "^5.0.5",
    "redux": "^3.6.0",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.2.0",
    "seamless-immutable": "^7.1.2"
  },
  "devDependencies": {
    "@google-cloud/storage": "^1.2.1",
    "babel-eslint": "^7.2.3",
    "babel-jest": "20.0.3",
    "babel-preset-react-native": "^1.9.2",
    "code-push-cli": "^2.0.0-beta",
    "eslint": "^3.19.0",
    "eslint-config-rallycoding": "^3.2.0",
    "eslint-plugin-react": "^7.1.0",
    "eslint-plugin-react-native": "^2.3.2",
    "flow-bin": "^0.47.0",
    "jest": "20.0.3",
    "mailgun-js": "^0.13.1",
    "react-test-renderer": "16.0.0-alpha.6",
    "redux-mock-store": "^1.2.3"
  },
```

**Comment by jslz** [comment]
If anybody knows where in the RN system I could put debug logging to see if the underlying native layer is getting the events, that would be potentially helpful to know, so we can try to do some/any debugging about it.

**Comment by jslz** [comment]
Update: So far, it appears that the ListView is eating up CPU time (or something) for a while even after scrolling has visibly stopped. We've experimented with various combinations of having and not-having ListViews and trying to repro, and it doesn't repro when the ListView is not in use. Whereas if we do have the ListView and scroll-and-stop and then tap, the fist tap or so is lost.

The window of time that the first tap will be missed after scrolling appears to depend on the phone e.g. our iPhone6 seems to be faster / less likely to repro the issue / reduces the window of time after scrolling in which the bug manifests.

**Comment by jslz** [comment]
Question: why/how/are the iOS native level events not/going into a native level Q that the JS UI thread then reads from when it gets a chance? That would convert our problem of completely missing some events over into the other classic UX problem of a system that responds to events with lag. That probably would be better overall, though not ideal of course.

**Comment by jslz** [comment]
Update/Tweak/Nuance/Wrinkle: We've actually repro'd on some iOS devices that it isn't a matter of timing, that no matter how long one waits after scrolling the ListView, the first tap is missed in JS.

**Comment by ssssssssssss** [comment]
Do you have any progress here ?

**Comment by Cool04ek** [comment]
Facing same issue as well

**Comment by Cool04ek** [comment]
The root of the issue can possibly can be rad here - https://github.com/negativetwelve/react-native-ux-cam/issues/36

**Comment by ognen** [comment]
@Cool04ek I can also confirm that by changing the [delegate method](https://github.com/facebook/react-native/blob/1e8f3b11027fe0a7514b4fc97d0798d3c64bc895/React/Base/RCTTouchHandler.m#L349) in `RCTTouchHandler.m` to always return `NO`, the problem disappears:

```
- (BOOL)gestureRecognizer:(__unused UIGestureRecognizer *)gestureRecognizer shouldRequireFailureOfGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer
{
	return NO;
}
```

By examining the git history of this class, I can see that this method was added by @shergin with commit c68a70862168cd3df751c5110a0062493397dc9d. Prior to this, the class always returned NO (though w/o a delegate impl). @shergin could you look into this and propose a proper way to fix this issue? 

I can provide a test project which demonstrates this behavior.
