### ISSUE TITLE
Android WebView doesn't expose AllowFileAccess permissions

### ISSUE THREAD

**Issue by airandfingers** [facebook/react-native#15604]
I want to disable file access within an Android WebView I'm creating using react-native's built-in WebView component.

The [Android WebView docs](https://developer.android.com/reference/android/webkit/WebSettings.html#setAllowFileAccess(boolean)) say "File access is enabled by default.", and this is a security concern for my organization.

The [react-native 0.31 docs](https://facebook.github.io/react-native/releases/0.31/docs/webview.html) mention a `getWebViewHandle` method that can be used to access the underlying WebView node; if this worked, then I could (presumably) write:

    import { WebView, Platform } from 'react-native';
    //...
    var reactWebview = <Webview [props here] />
    if (Platform.OS === 'android') {
        var webview = reactWebview.getWebViewHandle();
        console.log(webview.getAllowFileAccess()); // check AllowFileAccess setting
        webview.setAllowFileAccess(false); // disable file access
    }

However, later versions of the [react-native docs](https://facebook.github.io/react-native/docs/webview.html) don't mention `getWebViewHandle`, and when I run code like this in react-native 0.44 on an Android device, I get this error:

    webview.getWebViewHandle is not a function.

My questions are:

1. How can we check if file access is enabled by default for the Android WebViews created by react-native's WebView component?

2. How can we disable this file access? Would we need to extend the WebView class, or fork and modify react-native?

Thanks for your time!

**Comment by hramos** [comment]
WebView is close to getting deprecated and split out of React Native core. I recommend extending the WebView class as needed, and packaging it as a separate npm package.

**Comment by airandfingers** [comment]
Thanks for the info and suggestion, @hramos!

I'm now trying to extend the WebView class for my own use, but running into some issues. `getWebViewHandle` returns a reactTag integer value rather than a native component, but based on its code, I think the actual WebView component should be accessible via `this.refs[RCT_WEBVIEW_REF]`.

This appears to be a component:

    Constructor {_currentElement: {…}, _topLevelWrapper: null, _hostParent: Constructor, _hostContainerInfo: {…}, _rootNodeID: 5, …}
        _currentElement:
            $$typeof: Symbol(react.element)
            key: "webViewKey"
            props: {style: Array(2), source: {…}, scalesPageToFit: true, injectedJavaScript: undefined, userAgent: undefined, …}
            ref: "webview"
            type: ƒ Constructor(element)
            _owner: ReactCompositeComponentWrapper {_currentElement: {…}, _rootNodeID: 0, _compositeType: 0, _instance: WebViewWithHandle, _hostParent: Constructor, …}
            _store: {validated: true}
            _self: null
            _source: null
            __proto__: Object
        _debugID: 14
        _hostContainerInfo: {_tag: 1}
        _hostParent: Constructor {_currentElement: {…}, _topLevelWrapper: null, _hostParent: Constructor, _hostContainerInfo: {…}, _rootNodeID: 4, …}
        _mountImage: null
        _mountIndex: 0
        _renderedChildren: null
        _rootNodeID: 5
        _topLevelWrapper: null
        __proto__: ReactNativeBaseComponent

However, I can't access any of the public methods that Android WebViews are supposed to expose, per https://developer.android.com/reference/android/webkit/WebView.html (`getSettings` is the one I want to call).

How can I access a native component given a reference like the one above?

**Comment by Quelu** [comment]
@hramos Do you have more information about the future deprecation of the WebView in React Native ? Like when or some links ?
