### ISSUE TITLE
ScrollView scroll to make some part of the content disappeared on iOS

### ISSUE THREAD

**Issue by Symous** [facebook/react-native#15620]
### Is this a bug report?

YES!

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

YES!

### Environment

1. `react-native -v`: 0.45.1 
2. `node -v`: 8.1.2
3. `npm -v`: 5.3.0

- Target Platform: iOS

- Development Operating System:macOS 10.12.5

### Steps to Reproduce

(Write your steps here:)

1. a ta200 height container view (viewA)  wrap a scrollView ;
2. make the height of the viewA to 100 ;
3. use scrollTo method to scroll the content of the scrollView to y: 100 position;
4. make the height of the viewA back to 200;
5. the part of 0-100 of the scrollview content disappeared ;

### Expected Behavior

when the height of the viewA back to 200, the content recover its status;

### Actual Behavior
0-100 part of the content disappeared ;

PS: that's only happen on iOS, Android is working well as expect.

similar issue : #13749

**Comment by hramos** [comment]
Can you reproduce the issue using [Snack](http://snack.expo.io)? This step is necessary for people to be able to see and debug the issue being reported.
