### ISSUE TITLE
[Cosmetic] Rename `tick` to avoid iTunes Store warnings

### ISSUE THREAD

**Issue by gpbl** [facebook/react-native#1562]
I'm using v0.5. Before submitting the app, when I validate an archive, I get this warning:

```
iTunes Store operation succeeded with a warning
The app references non public-selectors in Payload/<AppName>.app/<Appname>: tick:
```

Do you also get this message? Is it something I should worry about?

**Comment by vjeux** [comment]
cc @nicklockwood

**Comment by nicklockwood** [comment]
I don't think this should be a problem, as "tick:" is a pretty common name for timer handlers.

Thanks for letting us know though, I think we may want to change it just to avoid the noise.

(And of course, if your app does actually rejected for this, please do let us know).

**Comment by gpbl** [comment]
Alright thanks! Such messages are a bit frightening because it's difficult to find out their actual meaning, especially using third-party libraries. Feel free to close the issue, if you don't need it as reminder.

**Comment by brentvatne** [comment]
I'm going to close this because otherwise it will just sit here, but a PR is very welcome to fix this :smile:

**Comment by ide** [comment]
How do people feel about s/tick/runTick/? Would make for an easy task.

**Comment by brentvatne** [comment]
@ide - maybe onTick?

**Comment by admmasters** [comment]
Created a PR for this - changed tick to onTick.
