### ISSUE TITLE
react native first Project can't run on my iOS simulator : MAC Terminal 

### ISSUE THREAD

**Issue by burkaslarry** [facebook/react-native#15622]
I have read the guidelines for running native apps  under the guidance below 

https://facebook.github.io/react-native/docs/getting-started.html
https://facebook.github.io/react-native/docs/troubleshooting.html

### Environment

node v8.4.0
react-native-cli: 2.0.1
react-native: 0.47.2

- Development Operating System: macOS

- Build tools:

Following commands I type
1.  cd AwesomeProject
2. react0native run-ios

I expect the app will run as 

https://facebook.github.io/react-native/img/iOSSuccess.png

 Actual Behavior

it runs as : 
<img width="997" alt="screenshot 2017-08-23 22 09 50" src="https://user-images.githubusercontent.com/5709615/29620193-d8448786-884f-11e7-94ff-9afaf47929b1.png">

 
What should I do next ?

**Comment by lugrugzo** [comment]
From the screenshot, it looks like react-packager is not finished bundling?

**Comment by hramos** [comment]
As @lugrugzo said. Closing as this doesn't highlight a particular code level issue.
