### ISSUE TITLE
iPhone 5/5c/5s weird blank space Top/Bottom of the screen BUG

### ISSUE THREAD

**Issue by Amurmurmur** [facebook/react-native#15625]
### Is this a bug report?
Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?
Yes
### Environment

1. `react-native -v`: 0.47.2
2. `node -v`: 8.4.0
3. `npm -v`: 5.3.0
4. `yarn --version`: 0.27.5

Then, specify:

- Target Platform:
iOS

- Development Operating System:
macOS Sierra 10.12.6

- Build tools:
iOS
### Steps to Reproduce

(Write your steps here:)

1. react-native init AwesomeProject
2. react-native run-ios --simulator=iPhone 5

### Expected Behavior

App should run in full screen
(Write what you thought would happen.)

### Actual Behavior
App gets cut from the top and bottom of the screen on iPhone 5/5s/5c iOS 8.0-10.3.3

(Write what happened. Add screenshots!)
![simulator screen shot 24 aug 2017 01 02 07](https://user-images.githubusercontent.com/8608333/29640517-ed15e30e-8867-11e7-8d80-334f797c26ba.png)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by hramos** [comment]
Can you reproduce the issue using [Snack](http://snack.expo.io)? This step is necessary for people to be able to see and debug the issue being reported. Your example is showing a Facebook web page, which tells me you're not simply using the default code provided by the `react-native init` command.

**Comment by Amurmurmur** [comment]
@hramos Fixed an issue, brought back LaunchScreen.xib and it fixed the issue, used to use Splash screen images and was just fine.
