### ISSUE TITLE
Crash on Android if index.android.bundle is a multiple of 4096 bytes

### ISSUE THREAD

**Issue by GeorgeDewar** [facebook/react-native#15623]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

1. `react-native -v`: react-native-cli: 2.0.1
   react-native: 0.47.2 (can also reproduce on 0.48.0-rc.1)
2. `node -v`: v7.9.0
3. `npm -v`: 4.2.0
4. `yarn --version`: 0.27.5

Then, specify:

- Target Platform: Android

- Development Operating System: Android 6.0.1 (Marshmallow) on a Samsung Galaxy Tab A 8.0 inch (SM-T350) [error is also reproducible on a Samsung Galaxy S6 running Android 7.0]

- Build tools: `react-native run-android`

### Steps to Reproduce

(Write your steps here:)

1. Create a new React Native application (`react-native init CrashTest`)
2. Add padding to some text in *index.android.js* so that the file size of *index.android.bundle* is a multiple of 4096 bytes (in my case, 2070768 bytes). Verify with `curl "http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false" | wc`
3. Attempt to run the application with `react-native run-android`. It will crash.

### Expected Behavior

I expect the application not to crash if I add or remove a byte from a piece of text.

### Actual Behavior

If I follow the reproduction steps above, or make a one-character change that takes the file size to a multiple of 4096 bytes, the app immediately crashes with the following backtrace:

```
08-24 02:13:53.998   369   369 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
08-24 02:13:53.998   369   369 F DEBUG   : Build fingerprint: 'samsung/gt58wifixx/gt58wifi:6.0.1/MMB29M/T350XXU1BQA1:user/release-keys'
08-24 02:13:53.998   369   369 F DEBUG   : Revision: '4'
08-24 02:13:53.998   369   369 F DEBUG   : ABI: 'arm'
08-24 02:13:53.998   369   369 F DEBUG   : pid: 3699, tid: 4011, name: mqt_js  >>> com.crashtest <<<
08-24 02:13:53.998   369   369 F DEBUG   : signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x9aaf2000
08-24 02:13:54.018   369   369 F DEBUG   :     r0 9a8f3000  r1 9aaf2000  r2 663d7966  r3 65736c61
08-24 02:13:54.018   369   369 F DEBUG   :     r4 9cd3d3f8  r5 9cd3d3e4  r6 9cd3cb84  r7 9a8f3000
08-24 02:13:54.018   369   369 F DEBUG   :     r8 9cd3d3e8  r9 9cd3d3f0  sl 6ffde5f0  fp 00000000
08-24 02:13:54.018   369   369 F DEBUG   :     ip 00000000  sp 9cd3cb78  lr 9f55cb35  pc b6cd0068  cpsr 600f0030
08-24 02:13:54.028   369   369 F DEBUG   : 
08-24 02:13:54.028   369   369 F DEBUG   : backtrace:
08-24 02:13:54.028   369   369 F DEBUG   :     #00 pc 00018068  /system/lib/libc.so (strlen+71)
08-24 02:13:54.028   369   369 F DEBUG   :     #01 pc 00042b31  /data/app/com.crashtest-1/lib/arm/libjsc.so (JSStringCreateWithUTF8CString+22)
08-24 02:13:54.028   369   369 F DEBUG   :     #02 pc 0002f5e7  /data/app/com.crashtest-1/lib/arm/libreactnativejni.so (_ZN8facebook5react11JSCExecutor11adoptStringESt10unique_ptrIKNS0_11JSBigStringESt14default_deleteIS4_EE+42)
08-24 02:13:54.028   369   369 F DEBUG   :     #03 pc 0003042d  /data/app/com.crashtest-1/lib/arm/libreactnativejni.so (_ZN8facebook5react11JSCExecutor21loadApplicationScriptESt10unique_ptrIKNS0_11JSBigStringESt14default_deleteIS4_EESs+124)
08-24 02:13:54.028   369   369 F DEBUG   :     #04 pc 00033033  /data/app/com.crashtest-1/lib/arm/libreactnativejni.so
08-24 02:13:54.028   369   369 F DEBUG   :     #05 pc 00032b21  /data/app/com.crashtest-1/lib/arm/libreactnativejni.so
08-24 02:13:54.028   369   369 F DEBUG   :     #06 pc 00015459  /data/app/com.crashtest-1/lib/arm/libreactnativejni.so (_ZNKSt8functionIFvvEEclEv+12)
08-24 02:13:54.028   369   369 F DEBUG   :     #07 pc 0001d27d  /data/app/com.crashtest-1/lib/arm/libreactnativejni.so
08-24 02:13:54.028   369   369 F DEBUG   :     #08 pc 00015459  /data/app/com.crashtest-1/lib/arm/libreactnativejni.so (_ZNKSt8functionIFvvEEclEv+12)
08-24 02:13:54.028   369   369 F DEBUG   :     #09 pc 00017201  /data/app/com.crashtest-1/lib/arm/libreactnativejni.so
08-24 02:13:54.028   369   369 F DEBUG   :     #10 pc 0001723f  /data/app/com.crashtest-1/lib/arm/libreactnativejni.so
08-24 02:13:54.028   369   369 F DEBUG   :     #11 pc 007d40ef  /data/app/com.crashtest-1/oat/arm/base.odex (offset 0x5dc000) (void com.facebook.react.bridge.queue.NativeRunnable.run()+74)
08-24 02:13:54.028   369   369 F DEBUG   :     #12 pc 037b71ff  /system/framework/arm/boot.oat (offset 0x2f97000)
```

### Reproducible Demo

The following reproduction was created by following the "steps to reproduce" above:

https://github.com/Datacom/ReactNativeCrashTest

**Comment by GeorgeDewar** [comment]
I do not think this issue should be closed just because it has not received any attention yet. I will try to reproduce the issue again on the latest version and will close it if I cannot.

**Comment by GeorgeDewar** [comment]
I cannot reproduce this on v0.49.3. I had a look and I suspect it was fixed via https://github.com/facebook/react-native/commit/8497ec297cf0f96b450952a64dc4fb4b10efba93. Thanks bot!

**Comment by iloveplus** [comment]
I have the same problem.

**Comment by GeorgeDewar** [comment]
@iloveplus have you tried v0.49.3 or newer?

**Comment by Rpeanut** [comment]
@GeorgeDewar We are using the 0.50.0 version, We haven't quite solved it yet，Now check the size when we're packing
