### ISSUE TITLE
[Android] FlatList scrollTo(Index|Item|End) without animation doesn't render items

### ISSUE THREAD

**Issue by chrusart** [facebook/react-native#15634]
### Is this a bug report?

Yes

### Environment

1. `react-native -v`: 0.47.2 and master
2. `node -v`: 7.3.0
3. `npm -v`: 5.3.0

- Target Platform: Android

- Development Operating System: macOS 10.12.6

- Build tools: Android Studio 2.3.3

### Steps to Reproduce

1. Use FlatList with number of items that would be rendered outside initial render windowSize
2. Invoke scrollToIndex/Item/End function to index greater than windowSize without animation

Snack app:

1. Run
2. Use 'SCROLL TO END WITHOUT ANIMATION' button
3. FlatList scrolls, items not rendered

When scrolling with animation everything works.
When scrolled to end, back and again to end, items will be rendered, so it doesn't work for first scroll only.

### Expected Behavior

Items should be rendered at this index.

### Actual Behavior

They are not rendered.

### Reproducible Demo

https://snack.expo.io/rJ_7g83_Z

* use Android platform.

**Comment by jacintoface** [comment]
i have the same problem

**Comment by simonas88** [comment]
This should be reopened, I am experiencing the same bug.

**Comment by MrEdinLaw** [comment]
Same here

**Comment by tsaohucn** [comment]
+ 1
