### ISSUE TITLE
ScrollView doesn't support 'horizontal' on android

### ISSUE THREAD

**Issue by cinan** [facebook/react-native#15637]
### Is this a bug report?

Yes.

### Environment

1. `react-native -v`: 0.47.1
2. `node -v`: v8.1.3
3. `npm -v`: 5.3.0
4. `yarn --version`: 0.27.5

- Target Platform: Android

- Development Operating System: macOS

- Build tools:

### Steps to Reproduce

1. import ScrollView from react-native
2. use it with `<ScrollView horizontal>...</ScrollView>`

Snack: https://snack.expo.io/SkAoeOpOZ

### Expected Behavior

ScrollView should scroll horizontally.

### Actual Behavior

ScrollView doesn't scroll horizontally. On iOS it is working. Documentation says it should be supported on both platforms.

**Comment by hramos** [comment]
Can you reproduce the issue using [Snack](http://snack.expo.io)? This step is necessary for people to be able to see and debug the issue being reported.

**Comment by cinan** [comment]
Here it is: https://snack.expo.io/SkAoeOpOZ

**Comment by uygaruysal** [comment]
I'm experimenting the same issue. Any updates?

**Comment by hramos** [comment]
Reopening, I'll edit the original post to include the necessary information.
