### ISSUE TITLE
React Native 0.47.1 this._lazyCallableModules Error

### ISSUE THREAD

**Issue by lvntayn** [facebook/react-native#15638]
Environment

node v6.9.4
react-native-cli: 2.0.1
react-native: 0.47.1

Development Operating System: macOS

Following commands I type

cd AwesomeProject
react-native run-andorid

I expect the app will run as

https://facebook.github.io/react-native/img/iOSSuccess.png

Actual Behavior

it runs as :
`08-24 18:51:17.809 27315-27430/xxx E/ReactNativeJS: undefined is not a function (evaluating 'this._lazyCallableModules[e]()')`
![alt text](https://i.hizliresim.com/Q7qpy3.jpg)

**Comment by hramos** [comment]
Can you provide additional repro information? What does your code look like? Please be as specific as you can. A minimal repro will help us help you.

**Comment by JulianKingman** [comment]
@lvntayn did you find a solution? What caused this problem? Related: https://github.com/facebook/react-native/issues/14933

**Comment by tobob** [comment]
make sure that you update packages (`yarn`) and if you running release version - make sure that bundle is on place `react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res`
