### ISSUE TITLE
TouchableNativeFeedback not working with FlatUIImplementationProvider (Nodes)  

### ISSUE THREAD

**Issue by guilharj** [facebook/react-native#15639]
### Is this a bug report?

YES

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

YES

### Environment

1. `react-native -v`: 0.47
2. `node -v`: v6.9.2
3. `npm -v`: 3.10.8
4. Android :  7.0

Then, specify:

- Target Platform: Android

- Development Operating System: macOS

- Build tools: react-native run-android

### Steps to Reproduce

1. Change the ReactNativeHost.getUIImplementationProvider Method to use FlatUIImplementationProvider ( as the use of Nodes renderer indicates )
2. Create a simple TouchableNativeFeedback component
3. When pressed, the component is not rendering the Ripple Effect 

### Expected Behavior

The ripple effect should appear while pressing the touchable area

### Actual Behavior

The ripple effect does not appear but the touchable , after released, respond the onPress method as expected. 

### Reproducible Demo
![image](https://user-images.githubusercontent.com/13605710/29682846-dc0e2a3c-88e2-11e7-80f2-4ef51fbe0a8c.png)

index.android.js
```

export default class reproduce extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <TouchableNativeFeedback onPress={()=>console.log(asdas)} style={{backgroundColor: 'gray'}}>
          <Text style={styles.instructions}>
           CLICK
          </Text>
        </TouchableNativeFeedback>
        <Text style={styles.instructions}>
          Double tap R on your keyboard to reload,{'\n'}
          Shake or press menu button for dev menu
        </Text>
      </View>
    );
  }
}
```

**Comment by hramos** [comment]
Can you tell me a bit more about your use case, why you're changing the UIImplementationProvider here, and where the expected behavior is documented?

**Comment by ssssssssssss** [comment]
Dear @hramos @AaaChiuuu , the roadmap indicates the Nodes (FlatUIImplimentation) will be turned on by default in June. I think many person are using this experimental feature to keep the Android port on par with iOS.
Do you have any progress or plans to update? Thanks.

**Comment by hramos** [comment]
I'll let @AaaChiuuu comment on that.

**Comment by guilharj** [comment]
Hi @hramos sorry about the late response, my notifications was turned off . 

So I'm was facing a problem that Nodes promise to solve ( overflow:visible) . So I changed the implementation to test if my layout would behave as I expected.  

I notice some small  layouting problems that I assumed that some flexbox tweaks would solve. But, the ripple effect was not working so I gave up bc to google play featured apps this is a HUGE deal. 

And also I was giving a try in a module that I understood that we will using by default some time soon. 

About where is documented: If the TouchableNativeFeedback react-native doc says that will show the ripple and the FlatUIImpl..  not mention that will not work ( as mentioned about the LayoutAnimation), I assume that the expected behavior would be : The Ripple will work!

I hope I've awnsered your questions , any help you need I here also to help. Thanks a lot for your reply!

**Comment by guilharj** [comment]
Any news?  Does nodes will be released as the main renderer soon?

**Comment by AaaChiuuu** [comment]
No. We're actually in the early stages of working on a new renderer.

**Comment by guilharj** [comment]
Thankyou @AaaChiuuu.  If nodes will not be in production, I assume that this issue can be closed.  But if you have any written information about this new renderer, I would like to now and see if I can collaborate anyhow.

**Comment by JCMais** [comment]
@AaaChiuuu may we get more information about the new renderer?

**Comment by JCMais** [comment]
Info if this is being worked on, or what are the plans for the new renderer, are really appreciated
