### ISSUE TITLE
react-native link never works

### ISSUE THREAD

**Issue by gokulkulkarni1987** [facebook/react-native#15646]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

YES

### Environment

1. `react-native -v`: react-native-cli: 2.0.1, react-native: 0.47.0
2. `node -v`: v8.4.0
3. `npm -v`: 5.3.0
4. `yarn --version`: 0.27.5

Then, specify:

- Target Platform:
iOS and Android

- Development Operating System:
macOS and Linux

- Build tools:
Not specific to any platform
### Steps to Reproduce

(Write your steps here:)

1. I do installation of any library by using `npm install <lib_name> --save`
2. The installation goes successful and I run `react-native link <lib_name>`

### Expected Behavior

The linking of the library must happen.

### Actual Behavior

The library linking never happens and I will have to manually do all the steps to add the library in both iOS and Android.

### Reproducible Demo

I think this step is not applicable as it is related to linking.

**Comment by patw0929** [comment]
link issue were solved in 0.47.1.

**Comment by laurent22** [comment]
I had this issue after renaming a project. The old name was still used in one place and because of this linking was silently failing.

**Comment by agrison** [comment]
I'm also having the exact same issue with react-native `0.47.2` and react-native-cli `2.0.1`.

**Comment by agrison** [comment]
Complete step to reproduce:

```bash
$ react-native -v
react-native-cli: 2.0.1
react-native: 0.47.2
$ create-react-native-app foo
$ cd foo
foo$ yarn add react-native-device-info
foo$ react-native link react-native-device-info
foo$ cat <<EOF > App.js
> import React from 'react';
> import { StyleSheet, Text, View } from 'react-native';
> import { DeviceInfo } from 'react-native-device-info';
> 
> export default (props) => {
>  return (
>    <View
>      style={{
>        flex: 1,
>        backgroundColor: '#fff',
>        alignItems: 'center',
>        justifyContent: 'center'
>      }}
>    >
>      <Text>Locale: {DeviceInfo.getDeviceLocale()}</Text>
>    </View>
>  );
>};
>EOF
```

![http://i.imgur.com/wTKuCmw.png](http://i.imgur.com/wTKuCmw.png)

Now if I eject and link manually in XCode, it works.

    foo$ yarn eject
    foo$ do some stuff in XCode
    foo$ hit Cmd+R 

![http://i.imgur.com/FAqjd4x.png](http://i.imgur.com/FAqjd4x.png)

**Comment by agrison** [comment]
Same problem with any other library, for instance `react-native-i18n` which I need to use, but I'd rather not have to eject just to handle internationalization 😃

**Comment by reneweb** [comment]
The problem is that create-react-native-app does not support native code (https://github.com/react-community/create-react-native-app#what-are-the-limitations-of-create-react-native-app) thus the linking doesn't work. It's unfortunate though that it doesn't present any error message, but just silently ignores the linking. I will look into adding some error message for that. 
To use native code you need to either eject or use `react-native init` to setup the project.

**Comment by reneweb** [comment]
There is already an error message by now in master: https://github.com/facebook/react-native/blob/master/local-cli/link/link.js#L160

**Comment by agrison** [comment]
Thanks, that's what I did, everything works correctly :)
