### ISSUE TITLE
Exception with RCTBridge: No bridge implementation is available, giving up.

### ISSUE THREAD

**Issue by zhunt11** [facebook/react-native#15655]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

1. `react-native -v`:
**react-native-cli: 2.0.1**
**react-native: 0.47.2**
2. `node -v`:
**v8.4.0**
3. `npm -v`:
**5.3.0**
4. `yarn --version`:
**0.27.5**

Then, specify:

- Target Platform: **iOS**

- Development Operating System: **macOS**

- Build tools: **Xcode, iOS Specific**

### Steps to Reproduce

1. Create a new native iOS project
2. Integrate React Native into the project following instructions from [here](https://facebook.github.io/react-native/docs/integration-with-existing-apps.html)
3. Declare and instantiate a bridge manager in your `AppDelegate.m`. See code below:

```
@property (nonatomic, strong, readonly) RCTBridge *bridge;

self.bridgeManager = [[ReactBridgeManager alloc] initWithBundleURL:jsCodeLocation launchOptions:launchOptions];
```

My ReactBridgeManager.m looks like this:

```
@interface ReactBridgeManager () <RCTBridgeDelegate>

@property (nonatomic, strong) NSURL *bundleURL;

@end

@implementation ReactBridgeManager

- (instancetype)initWithBundleURL:(NSURL *)bundleURL launchOptions:(NSDictionary *)launchOptions
{
	if (self = [super init])
	{
		self.bundleURL = bundleURL;
		_bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
	}
	
	return self;
}

#pragma mark - RCTBridgeDelegate

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
	return self.bundleURL;
}

@end
```

4. Run the app

### Expected Behavior

Before upgrading to this version of React I was on version 0.43.3 and I was able to run the app and create a bridge manager just fine. I expect my bridge manager to work how it did before the upgrade, or have documentation that shows how to adjust my bridge manager to make it work with the new version.

### Actual Behavior

**Result:** Exception is thrown in `RCTBridge.m` in function `bridgeClass` (line 293):
`RCTAssert(implClass != nil, @"No bridge implementation is available, giving up.");`

![image](https://user-images.githubusercontent.com/1995050/29718454-1c2a1026-8970-11e7-9a03-6f4c87ab712d.png)

### Reproducible Demo

https://github.com/zhunt11/React-Issues/tree/master/Hybrid

**Comment by zhunt11** [comment]
**UPDATE:**

In `RCTBridge.m` in function `bridgeClass` (line 276-277):

```
Class batchedBridgeClass = objc_lookUpClass("RCTBatchedBridge");
Class cxxBridgeClass = objc_lookUpClass("RCTCxxBridge");
```

The `batchedBridgeClass` and the `cxxBridgeClass` are `0x0` after `objc_lookUpClass()` is called. It seems `implClass` will always be `nil` because `batchedBridgeClass` and `cxxBridgeClass` are always `nil`.

**Comment by zhunt11** [comment]
Even if I call  `initWithBundleURL:moduleName:initialProperties:launchOptions:` on `RCTRootView` instead of `initWithBridge:moduleName:initialProperties:`, I still get the same error.

A bridge is still created with `initWithBundleURL`, it's just created internally. I'm guessing `objc_lookUpClass()` is keeping the bridge from being created successfully under any circumstances.

**Comment by zhunt11** [comment]
Is anyone going to take a look at this?

**Comment by zhunt11** [comment]
Anyone out there?

**Comment by nim23** [comment]
Ran into somewhat similar situation, downgraded node to 6.9.1 and removed node_modules folder, reinstalled everything, re ran the packager seemed to fix it :rofl:

**Comment by zhunt11** [comment]
Oh wow, thats crazy. I didn't think about downgrading node. I will take a look if we decide to go that far.

**Comment by zhunt11** [comment]
And who's fault is it for being stale? No one from the React Native team could answer my question. haha

**Comment by brandonpage** [comment]
@zhunt11 Did this ever get resolved?  I'm seeing it in v0.50.3.

**Comment by dustturtle** [comment]
why is this issue closed?

**Comment by rikur** [comment]
haha, just sweep it under the rug. I have the same issue.. probably can't get help here.

**Comment by gavrix** [comment]
If anyone still seeing this issue — check of you have "-ObjC" in Other Linker flags (OTHER_LD_FLAGS) for your main project. That was the reason of reported behaviour for me.
