### ISSUE TITLE
After I update to 0.5.0, it take too much cpu

### ISSUE THREAD

**Issue by soliury** [facebook/react-native#1565]
I just do nothing , and the the app will take about 30% cpu of my iphone6. In v0.4.4, it take a little.

I just want to know why.

**Comment by soliury** [comment]
I have found the reason, in listView there is a `setInterval` in line 249. If I remove it, it working good. I think it is not nessasery to use `setInterval` to check the item is touch the end.

**Comment by ide** [comment]
I believe the set interval call has been removed in 0.6.0-RC

**Comment by ide** [comment]
Thanks for investigating. The RC is published to npm so you could edit your package.json to upgrade to it and see if it fixes the CPU usage.

**Comment by soliury** [comment]
I see, yes it works well in 0.6.0.
