### ISSUE TITLE
TextInput - Change padding dynamically failed

### ISSUE THREAD

**Issue by inevermore** [facebook/react-native#15650]
## Description
I have a `TextInput` component in my project. I want to change its padding when it focused, but I failed. I inspect it, the padding changed, but its style didn't.

## Reproducible Demo

I create a simple demo in Github.
https://github.com/inevermore/react-native-textInput-padding-test

## Environment
1. react-native -v: 0.47.2
2. node -v: 8.1.2
3. react-native-cli -v: 2.0.1
4. device: IOS simulator / IOS phone

**Comment by ligaz** [comment]
Looks similar to #14645.
