### ISSUE TITLE
react-packager has encountered an internal error, please check your terminal error output for more details

### ISSUE THREAD

**Issue by FengHuangDong** [facebook/react-native#15656]
{"type":"InternalError","message":"react-packager has encountered an internal error, please check your terminal error output for more details"}  RCTFatal -[RCTBatchedBridge stopLoadingWithError:] __25-[RCTBatchedBridge start]_block_invoke_2 _dispatch_call_block_and_release _dispatch_client_callout _dispatch_main_queue_callback_4CF __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ __CFRunLoopRun CFRunLoopRunSpecific GSEventRunModal UIApplicationMain main start 0x0

**Comment by iMokhles** [comment]
#15671 here's how I fixed this issue

**Comment by jagelooyadav** [comment]
running below commonds in root folder in terminal worked for me
npm start -- --reset-cache
