### ISSUE TITLE
RN breaks rendering Text with more than 490 lines on iOS

### ISSUE THREAD

**Issue by gunn** [facebook/react-native#15663]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

1. `react-native -v`: 0.47.1

Then, specify:

- Target Platform: iOS

### Steps to Reproduce

1. Have a Text component with more than 490 lines
2. Or add lines to a Text component so it has more than 490

e.g.:
```javascript
const lines = (new Array(491)).fill().map((e, i)=>i+1).join("\n")
return <Text>{lines}</Text>
```

### Expected Behavior

The text to display as it does with e.g. 400 lines.

### Actual Behavior

The app refuses to start, or crashes, or renders the text area with visual glitches.

### Reproducible Demo

https://snack.expo.io/Sk_KyTRuW
Try editing the number of lines. With 491 it freezes on startup, with 490 runs fine.

In the iOS simulator on my desktop, the failure occurs with more than 434 lines. The count doesn't seem to be affected by the absolute number of characters shown.

The same works fine on android with huge line counts.

**Comment by gunn** [comment]
An example of visual glitches:
![text_component_bug](https://user-images.githubusercontent.com/42500/29758567-b4a64ca8-8c08-11e7-88f2-73d1b1dcd227.png)

The corrupted area under "source:" is where the Text component with a  large number of lines is rendering.

I've also found the exact number of lines that cause trouble changes with font size, so perhaps it's a function of absolute component height?

**Comment by samratshekhar** [comment]
+1

### Environment
1. `react-native -v`: 0.44.3
2. `node -v`: 7.7.1
3. `npm -v`: 4.1.2
4. `platform`: iOS only

In my case, the app runs perfectly, but no text is rendered, even though the container takes up required space inside a `ScrollView` as shown below:
![screen shot 2017-09-11 at 6 50 44 pm](https://user-images.githubusercontent.com/25629471/30276442-79c90a2e-9722-11e7-956d-ddab92c7ca9e.png)

**Comment by kmagiera** [comment]
Looks like it doesn't necessarily have to do with the number of lines but with the height of the Text component. So even if I only put a single like of text, but explicitly set height of the component to be large enough I get the same effect as @samratshekhar described.

Interestingly the largest `height` that seems to work for me while testing this on iPhone 6S simulator is 8192 (interestingly, because 8192 = 2^13). When I set `height: 8193` or more I see no text and some visual glitches when scrolling.

**Comment by kmagiera** [comment]
This could be related: https://stackoverflow.com/questions/14125563/uilabel-view-disappear-when-the-height-greater-than-8192

Seems like the issue is not exclusive to RN
