### ISSUE TITLE
Modal not working as expected inside ScrollView

### ISSUE THREAD

**Issue by jalalat** [facebook/react-native#15665]
### Is this a bug report?
Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?
Yes

### Environment
1. `react-native -v`: 0.45.1
2. `node -v`: v7.10.0
3. `npm -v`: 4.6.1
4. `yarn --version`: 0.24.4

Then, specify:
- Target Platform: Android, iOS
- Development Operating System: Windows 10
- Build tools: Expo
- Issue tested on: Android

### Steps to Reproduce
1. Use Modal in the code (as specified in the example: https://facebook.github.io/react-native/docs/modal.html) within ScrollView (not there in the example).
2. Add two views in the modal as specified in the example
3. In the Internal View add a text box (TextInput) and Button.
4. Add some text in the TextInput and click on the Button to send response back to the parent component.
5. The first click on the button hides the keyboard. onPress event does not get triggered.
6. Click again on the same button and this time Modal is hidden and Parent component gets the text data.
7. This issue occurs only when Modal is used inside ScrollView. If you replace ScrollView with View then you will get the expected behavior. 

### Expected Behavior
1. When user clicks on the Button for the first time then then onPress event should get triggered. Text data from TextInput should be logged to console.

### Actual Behavior
1. When button is clicked the keyboard hides -> that's good. However onPress event does not get triggered.
2. When button is clicked again -> only then the onPress event get triggered.
3. The same behavior occurs if i click on the back button (on the bottom right hand side; next to home screen on Android phone).

### Reproducible Demo
https://snack.expo.io/S1WS11JKZ

**Comment by Letty-Liang** [comment]
Facing the same issue

**Additional:** 
Modal + InputText
After the keyboard is opened => hidden => exit from a react-native page to a native page => enter react-native page again => crash
