### ISSUE TITLE
** operator breaks packager (white screen with no feedback) - adb logs show Unexpected token '*'

### ISSUE THREAD

**Issue by dhirnyj** [facebook/react-native#15668]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

1. `react-native -v`: react-native-cli: 2.0.1, react-native: 0.47.1
2. `node -v`: v8.4.0
3. `npm -v`:5.3.0
4. `yarn --version`: 0.27.5
Then, specify:

- Target Platform: Android

- Development Operating System: Ubuntu 16.04

- Build tools: No

### Steps to Reproduce

1. Include ** operator somewhere in project
2. Try to run project and it will display blank screen with no error logs (except in adb logcat)

### Expected Behavior

I expected the ** operator to work since it is recommended by eslint-config-airbnb, but at the very least feedback from react-native regarding the error.

### Actual Behavior

If I include the ** operator which is suggested to be used over Math.pow() by eslint-config-airbnb, the index.android.bundle file gets corrupted without any notice in the terminal running "react-native start" or on the android screen, which is blank. Adb logs include an error saying: 
08-26 10:37:10.309  4682  4715 E unknown:ReactNative: Caused by: com.facebook.jni.CppException: Unexpected token '*' (http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:67929)

Upon running:
react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/ - I could got feedback to the file/line of code where the error occurred - but in general could not get consistent behavior with this command either. It was also successful without any errors, even when the error was present.

### Reproducible Demo

export default class TestProject extends Component {
  render() \{
    return \(
      \<View\>
        \<Text\>
          {2**3}
        \</Text\>
      \</View\>
    \);
  \}
}

AppRegistry.registerComponent('TestProject', () => TestProject);

** Note: creating a snack did not reproduce this issue **

**Comment by chirag04** [comment]
You need to add support exponential operator in your babelrc. Check babel-preset-react-native-stage-0

**Comment by chirag04** [comment]
let me know if this needs to re-opened.

**Comment by MiLeung** [comment]
Damn, just spent 2 days on this trying to figure out what this was
