### ISSUE TITLE
[Animation] what's status of `AnimationExperimental`?

### ISSUE THREAD

**Issue by flashlizi** [facebook/react-native#1566]
Is `AnimationExperimental` can be used on production now?

I have tried to use it, it works fine on 64bit devices, such as iPhone6 etc, but doesn't work on 32bit devices, such as iPhone4s, iPhone5C etc.

**Comment by browniefed** [comment]
I believe we can assume this is solved with the latest release of .8 and Animated.
Check out the docs here http://facebook.github.io/react-native/docs/animations.html#content for all animation recommendations.
@brentvatne already solved

**Comment by brentvatne** [comment]
:tada: :rocket: :guitar:
