### ISSUE TITLE
https://facebook.github.io/react-native/releases/0.23/docs/tutorial.html

### ISSUE THREAD

**Issue by ExtAnimal** [facebook/react-native#15664]
### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### OSX

1. `react-native -v`: `react-native-cli: 2.0.1`
    `react-native: 0.47.2`
2. `node -v`: `v7.10.1`
3. `npm -v`:`4.2.0`

- Target Platform:

- Development Operating System:

- Build tools:

### Steps to Reproduce

1.  Go to https://facebook.github.io/react-native/releases/0.23/docs/tutorial.html
2. `npm install -g react-native-cli`
3. `react-native init AwesomeProject`

### Expected Behavior

Not sure. It's a tutorial. It should do SOMETHING.

### Actual Behavior

Installs a megaton of... stuff and then throws an error.

![screen shot 2017-08-26 at 13 09 58](https://user-images.githubusercontent.com/200516/29740814-ef737680-8a5f-11e7-8ac5-453fafa1a604.png)

### Reproducible Demo

https://facebook.github.io/react-native/releases/0.23/docs/tutorial.html

Follow the first two instructions to the letter.

After installing megatons of... stuff, you get this

```
** BUILD FAILED **

The following commands produced analyzer issues:

	Analyze /Users/nige/react-native/AwesomeProject/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.c
	Analyze /Users/nige/react-native/AwesomeProject/node_modules/react-native/ReactCommon/yoga/yoga/YGNodeList.c
(2 commands with analyzer issues)

The following build commands failed:
	CompileC /Users/nige/react-native/AwesomeProject/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64/RCTTabBarItem.o Views/RCTTabBarItem.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/AwesomeProject.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/AwesomeProject.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
```

It's not good. The first tutorial page, from the framework's authors. Overcomplicated. And throws an error. Why would anybody bother?

**Comment by guhungry** [comment]
Current react native version is 0.47 the tutorial is from version 0.23.

**Comment by radko93** [comment]
@facebook-github-bot answered
