### ISSUE TITLE
ios build fails with npm 5.4.0

### ISSUE THREAD

**Issue by rpadovani** [facebook/react-native#15677]
### Is this a bug report?

Yes

The bug is not in react-native itself, but in npm: https://github.com/npm/npm/issues/18324
But since I have spent some time to understand it, I think it is worth sharing, and maybe put an advice somewhere in the project to do not use npm 5.4.0

Possible workarounds:
- Use npm 5.3.0
- Use chmod +x to restore right permissions

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

1. `react-native -v`: n/a
2. `node -v`: v6.11.2
3. `npm -v`: 5.4.0

Then, specify:

- Target Platform: iOS

- Development Operating System: macOS

- Build tools: Xcode / fastlane

### Steps to Reproduce

(Write your steps here:)

1. npm i npm@5.4.0
2. npm i react-native
3.  ls -l node_modules/react-native/scripts

### Expected Behavior

The output should be:

```
-rwxrwxr-x 1 rpadovani rpadovani  933 Aug 22 11:00 ios-configure-glog.sh
-rwxrwxr-x 1 rpadovani rpadovani 1230 Aug 22 11:00 ios-install-third-party.sh
-rw-rw-r-- 1 rpadovani rpadovani  382 Aug 22 11:00 launchPackager.bat
-rwxrwxr-x 1 rpadovani rpadovani  498 Aug 22 11:00 launchPackager.command
-rwxrwxr-x 1 rpadovani rpadovani  397 Aug 22 11:00 packager.sh
-rwxrwxr-x 1 rpadovani rpadovani 3517 Aug 22 11:00 react-native-xcode.sh
```

### Actual Behavior

The output is:

```
-rw-rw-r-- 1 rpadovani rpadovani  933 Aug 22 11:00 ios-configure-glog.sh
-rw-rw-r-- 1 rpadovani rpadovani 1230 Aug 22 11:00 ios-install-third-party.sh
-rw-rw-r-- 1 rpadovani rpadovani  382 Aug 22 11:00 launchPackager.bat
-rw-rw-r-- 1 rpadovani rpadovani  498 Aug 22 11:00 launchPackager.command
-rw-rw-r-- 1 rpadovani rpadovani  397 Aug 22 11:00 packager.sh
-rw-rw-r-- 1 rpadovani rpadovani 3517 Aug 22 11:00 react-native-xcode.sh
```
Please notice `x` is missing from permissions

**Comment by hramos** [comment]
Thanks for raising this. We probably need to do some work to support the newly released 5.4.0 version. While we could add a callout warning people about this, I think it's best to just figure out why it broke and fix it.
