### ISSUE TITLE
Wiki: How i fixed my issue ( react-packager has encountered, Error: ENOENT: no such file & other issue similar )

### ISSUE THREAD

**Issue by iMokhles** [facebook/react-native#15671]
i wanna share the simple way I found to fix those issue 
( react-packager has encountered, Error: ENOENT: no such file & other issue similar/familiar )
because I saw there are a lot of people facing the same,

i installed yarn https://yarnpkg.com/lang/en/docs/install/
then
I installed this package https://github.com/pmadruga/react-native-clean-project
```
yarn add -D react-native-clean-project
```

and after that everything goes well my react-native project worked again without initialize another new project and setup everything from scratch.

hope this helps others

**Comment by iMokhles** [comment]
update: i was able to fix the same issues without
``` 
 react-native-clean-project
```
just I run yarn inside my project folder and close packager and the app from ( AppSwitcher in Simulators ) then run
``` 
 react-native run-ios
or
 react-native run-android
```

everything went correctly once again

**Comment by Taewa** [comment]
@iMokhles 
It does not resolve the `react-packager has encountered` error for me by using  `react-native-clean-project`.

I changed `"react-native": "0.46.4"` in `package.json` from `0.47.x` but no luck.

What was your react-native version when you ran `react-native init`?

**Comment by iMokhles** [comment]
@Taewa 
my version is 0.47.x 
so if `react-native-clean-project ` you have to install `yarn` and just call `yarn` command from terminal inside your project that's the second solution which worked for me too

**Comment by Taewa** [comment]
@iMokhles 
Thanks for the solution. I have tried installing package by using `yarn` but didn't work.
My solution was re-installing `"babel-preset-react-native": "2.1.0"`. I had 2.1.0 version already though...

**Comment by iMokhles** [comment]
@Taewa nice hope it helps others, I will keep updating this conversation and hope others do also with other ways to solve such issues if I got new solution

**Comment by jaschaio** [comment]
I followed the [getting started guide in the docs](https://facebook.github.io/react-native/docs/getting-started.html) and encountered the same problem. 

Running `yarn add -D react-native-clean-project` solved the problem for me.

**Comment by wincod75** [comment]
FWIW I was recently experiencing this issue, did a force clean via NPM, deleted NM folder, did a fresh NPM install and the error magically went away and the build succeed...
