### ISSUE TITLE
TransformError babel-preset-react-native after clean install

### ISSUE THREAD

**Issue by sospedra** [facebook/react-native#15675]
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

yes

### Environment

1. `react-native -v`:  0.47.2
2. `node -v`: 8.0.0
3. `npm -v`: 5.0.0
4. `yarn --version`: 0.27.5

Then, specify:

- Target Platform: ios

### Steps to Reproduce

(Write your steps here:)

1. `react-native init MyAwesomeProject`
2. `cd MyAwesomeProject`
3. `react-native run-ios`

### Expected Behavior

Should open the simulator without any trouble.

### Actual Behavior

It triggers the following error:  `TransformError: /{paths}/MyAwesomeProject/index.ios.js: Unexpected token ) (While processing preset: "/{paths}/node_modules/babel-preset-react-native/index.js")`

<details>
  <summary>Screenshot</summary>

  ![image](https://user-images.githubusercontent.com/3116899/29764069-0ce0e2f8-8bd6-11e7-8428-313fa8a5f88b.png)

</details>

### Reproducible Demo

https://github.com/sospedra/RNAnimated

### Extra research

I tried the workaround from here: https://github.com/facebook/react-native/issues/15545 and doesn't work

**Comment by mohamed-alashry** [comment]
it happen with react-native -v: 0.47.2

**Comment by rashnk** [comment]
Help please
```
react-native --v
react-native-cli: 2.0.1
react-native: 0.47.2
```


![58d41756-20da-4883-ae2d-59faac5c5919](https://user-images.githubusercontent.com/12730428/29785737-5259816c-8c46-11e7-81ee-8c7c61bf595a.jpg)

**Comment by mohamed-alashry** [comment]
it didn't work yesterday, but it works today for some mysterious reason...

**Comment by ronal2do** [comment]
+ 1 
react-native --v
react-native-cli: 2.0.1
react-native: 0.47.2

.babelrc
```
{
  "presets": [
    "react-native"
  ],
  "plugins": [
    "relay"
  ]
}
```

<img width="375" alt="captura de tela 2017-08-31 as 00 42 55" src="https://user-images.githubusercontent.com/4389565/29905502-8ba4b19e-8de5-11e7-8fa8-5749875c007f.png">
