### ISSUE TITLE
Upgrading from 0.44 to 0.46.4 gives core-js conflict within the react-native package

### ISSUE THREAD

**Issue by tss101** [facebook/react-native#15678]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

1. `react-native -v`:react-native: 0.46.4
2. `node -v`:v7.5.0
3. `npm -v`:5.3.0

- Target Platform: iOS + Android

- Development Operating System: macOS

- Build tools: Xcode + Vim

### Steps to Reproduce

1. Run react-native-upgrade 0.46.4 to upgrade from 0.44 to 0.46.4
2. ./gradlew clean in android folder
3. cmd+shift+K in Xcode to clean xcode project
4. rm -rf $TMPDIR/react-* && watchman watch-del-all && rm -rf ios/build/ModuleCache/* && rm -rf node_modules/ && npm cache clean —force && npm i
5. npm start -- --reset-cache

### Expected Behavior

A clean upgrade to RN 0.46.4

### Actual Behavior

npm start -- --reset-cache gives the warning:

Loading dependency graph...jest-haste-map: @providesModule naming collision:
  Duplicate module name: core-js
  Paths: /{path_to_app}/node_modules/react-native/node_modules/core-js/package.json collides with /{path_to_app}/node_modules/reac
t-native/node_modules/fbjs/node_modules/core-js/package.json

This warning is caused by a @providesModule declaration with the same name across two different files.

I saw similar errors in a few other issues on here, and tried the fixes in the steps above. And I found this on StackOverflow, 

https://stackoverflow.com/questions/45790702/jest-haste-map-providesmodule-naming-collision

and deleting the the node_modules folder under /{path_to_app}/node_modules/react-native/node_modules/fbjs did get rid of the warning for me. 

However, I'm just wondering why 2 modules included within the react-native package would collide with each other?

**Comment by jinxac** [comment]
I have similar issue while migrate from 0.40 to 0.47.2

**Comment by tss101** [comment]
The debug library also gave me a similar warning, but it only appeared once (I'm assuming it's something to do with the initial build being cached). 

It doesn't seem to be causing any problems with the app build process apart from the warning, so I'm wondering if we don't need to worry about.

**Comment by jinxac** [comment]
yes @tss101 you are right. It does not cause any problems with the build

**Comment by Lxxyx** [comment]
same issue
