### ISSUE TITLE
WebView stopLoading no longer working in onNavigationStateChange on Android

### ISSUE THREAD

**Issue by tss101** [facebook/react-native#15679]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
OS: macOS Sierra 10.12.6
Node: 6.11.2
Yarn: 0.15.1
npm: 3.10.10
Watchman: 4.9.0
Xcode: Xcode 8.2 Build version 8C38
Android Studio: 2.2 AI-145.3537739

Packages: (wanted => installed)
react: 16.2.0 => 16.2.0
react-native: 0.53.3 => 0.53.3 (reproduced in react-native: 0.54.2, 0.55.4)

### Steps to Reproduce

1. Create a Webview in 0.54.0, point it to a url with an embedded youtube video (iframe) or link
2. Call stopLoading in onNavigationStateChange

### Expected Behavior

Newly clicked url stops loading

### Actual Behavior

Url keeps loading

### Reproducible Demo

```
export var TestWebContentView = createReactClass( {displayName: 'TestWebContentView',
    handleNavigationChange: function(navState) {
         console.log(navState)
         this.webview.stopLoading();
        }
    },
    render: function() {
        return (
            <View style={rootViewStyle} >
                <WebView
                ref={(ref) => { this.webview = ref; }}
                scrollEnabled={false}
                source={{uri: 'http://www.simplehtmlguide.com/livedemo.php?e=youtube2' }}
                startInLoadingState={false}
                mixedContentMode={'always'}
                scalesPageToFit={false}
                onNavigationStateChange={this.handleNavigationChange}
                allowsInlineMediaPlayback={true}
                automaticallyAdjustContentInsets={false}
                />
            </View>
        )
    }
})
```

I'm quite stumped by this, since it was working a week or so ago on the same Android device, on react-native 0.44. However, I reverted the react-native version back to 0.44 and it's still not working. Might a Chrome update be responsible? iOS version appears to work.

**Comment by aizigao** [comment]
same problem，how to fix it

**Comment by pmusaraj** [comment]
I had this issue on iOS, when trying to get an external link to stop loading in the webview and launch SafariView (via `react-native-safari-view`). I solved it (again, in iOS) by moving the relevant code to `onShouldStartLoadWithRequest` instead of `onNavigationStateChange`. My understanding is that `onNavigationStateChange` takes place too late in the lifecycle, so calling `stopLoading` does nothing.

**Comment by boxOfAces** [comment]
How to fix it for both iOS & Android?

**Comment by reyalpsirc** [comment]
Since `onShouldStartLoadWithRequest` does not exist on Android and `stopLoading` does not work now inside `onNavigationStateChange`, there's no way at the moment to catch a link of page and process something else inside the App without opening that link... :(

**Comment by dancherb** [comment]
Still an issue in v0.53.0!

**Comment by riteshmahajan47** [comment]
Still same issue in Android in v0.53.3

**Comment by hramos** [comment]
Reopening as have seen various reports of this happening in 0.54

**Comment by hramos** [comment]
I've updated the original post with additional information from #18047

**Comment by bostrot** [comment]
A workaround could be to just `goBack` to the url.

**Comment by gtjamesa** [comment]
Can confirm that this is still not working in 0.55.4

**Comment by nelsonchen5** [comment]
still not working

**Comment by rickyliu93** [comment]
still not work in 0.56 for some URL

**Comment by jamonholmgren** [comment]
Migrated to https://github.com/react-native-community/react-native-webview/issues/8 and this issue can be closed.

**Comment by ShashankMalviya1994** [comment]
can confirm that still not working in "react-native": "^0.57.4"
