### ISSUE TITLE
[NavigatorIOS] Titlebar has margin in iOS 11 (not in iOS 9.3)

### ISSUE THREAD

**Issue by Zyphrax** [facebook/react-native#15681]
### Is this a bug report?
Yes

### Have you read the Contributing Guidelines?
Yes

### Environment
1. `react-native -v`: react-native-cli: 2.0.1, react-native: 0.47.2
2. `node -v`: v8.4.0
3. `npm -v`: 5.3.0
4. `yarn --version`: 0.27.5

- Target Platform: iOS
- Development Operating System: macOS
- Build tools: Xcode

### Steps to Reproduce
The NavigatorIOS navigation bar doesn't seem to render properly under iOS 11.

### Expected Behavior
The NavigatorIOS navigation bar should render in iOS 11 like it does in iOS 9.

![bug-ios9](https://user-images.githubusercontent.com/966500/29796144-9645e380-8c1d-11e7-874c-042157c9ff68.png)

### Actual Behavior
There is a margin under the titlebar that shouldn't be there.

![bug-ios11](https://user-images.githubusercontent.com/966500/29796156-a44d0454-8c1d-11e7-83d1-47ab9398c242.png)

### Reproducible Demo

This snack contains a simplified version of the structure in my app.
Unfortunately I can't seem to select an iOS version in Snack, so you don't see the margin issue.

https://snack.expo.io/H1TNLMMFW

**Comment by WATER1350** [comment]
This issue is caused by safeArea concept introduced by iOS 11 and set the property **contentInsetAdjustmentBehavior** of UITableView will fix it. Just like:
`tableView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever.`

**Comment by Zyphrax** [comment]
Awesome, so this should be a relative simple fix in the source?

**Comment by Zyphrax** [comment]
I've decided to stop using NavigatorIOS. It often contains bugs and of course isn't a solution that we can use for Android. I'm now using [React Navigation](https://reactnavigation.org), that works great!
