### ISSUE TITLE
<ImageBackground> Touchable child must either be native or forward...

### ISSUE THREAD

**Issue by ChristianTucker** [facebook/react-native#15684]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

1. `react-native -v`: 0.47.2
2. `node -v`: v6.2.2
3. `npm -v`: 3.10.7
4. `yarn --version`: N/A

Then, specify:

- Target Platform: Android, iOS

- Development Operating System: macOS (10.11.6), Windows 10 Professional.

- Build tools: Nonspecific.

### Steps to Reproduce

Create a component that uses a `<ImageBackground>` component as the child of a `Touchable*` component. The `<Image>` component did not have this problem. Example below:

```javascript
class Foo extends React.Component {
    render() {
        return (
            <TouchableOpacity onPress={() => console.warn("Example")}>
                <ImageBackground source={{ uri: "http://placehold.it/256" }} style={...}>
                    ...
                </ImageBackground>
            </TouchableOpacity>
        );
    }
}
```

Here's a workaround for the issue, however it does make the code more messy in my opinion:

```javascript
class Foo extends React.Component {
    render() {
        return (
            <TouchableOpacity onPress={() => console.warn("Example")}>
                <View>
                    <ImageBackground source={{ uri: "http://placehold.it/256" }} style={...}>
                        ...
                    </ImageBackground>
                </View>
            </TouchableOpacity>
        );
    }
}
```

Previously this could be done without an issue by just using an `<Image>` in place of `<ImageBackground>`  Perhaps we could forward `setNativeProps` by default in the `<ImageBackground>` component?

**Comment by IljaDaderko** [comment]
Confirmed, still an issue in react-native 0.49, after changing `<Image />` to `<ImageBackground />` Some elements became completely un-clickable, some are, but you have to target edges for touch to happen.

**Comment by atitpatel** [comment]
+1
