### ISSUE TITLE
[iOS] RefreshControl spinner freezes

### ISSUE THREAD

**Issue by kramer9x** [facebook/react-native#15694]
### Is this a bug report?
Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

1. `react-native -v`:
> react-native-cli: 2.0.1
> react-native: 0.46.4
2. `node -v`: 
> v7.5.0
3. `npm -v`: 
> 4.5.0
4. `yarn --version`: 
> 0.27.5

- Target Platform:
iOS

- Development Operating System:
macOS

- Build tools:
Issue is specific to iOS

### Steps to Reproduce
[iOS] Spinner component of RefreshControl freezes if app was put to the background and returned to the foreground.

Steps to reproduce:
1. Run snack on iPhone
2. Perform pull2refresh action on SectionList
3. While spinner component is active put app to background by pressing Home button
4. Tab on App icon or activate it using OS task manager

### Expected Behavior
After app is returned to foreground and async process is not finished - spinner icon should be active (rotating)

### Actual Behavior
Spinner icon is stuck in one position

### Reproducible Demo
Snack - https://snack.expo.io/rkDK8bXKZ

**Comment by fokoz** [comment]
https://github.com/facebook/react-native/issues/13977
Long time ago.

**Comment by Marina-Miranovich** [comment]
I'm still able to reproduce the issue...
