### ISSUE TITLE
Unhelpful docs for Native UI Components for Android

### ISSUE THREAD

**Issue by Leva7** [facebook/react-native#15697]
### Is this a bug report?

No

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### The issue
The [docs](https://facebook.github.io/react-native/docs/native-components-android.html) for implementing native UI components are not very helpful.  

Reasons:  
1) The example shows only a few lines of code without any context or filename/location, leaving it to the user to figure out.
2) There's no full version of the example for the user to examine and modify
3) The second step includes this bit: `Fresco.newDraweeControllerBuilder(), mCallerContext`. But nowhere is it stated, what it is, what's it for and does the person need it when adapting the example to their situation. Also the `ReactImageView` class definition is nowhere to be seen.
4) There's no final usage. What I mean by that is a code snippet that imports the newly created component and puts it into an application. It would have been much more helpful if the user could construct a working example out of those snippets.

Therefore, I'd like to request a revision for that section of the docs for clarity, as this is a very unintuitive process that needs thorough guidance

**Comment by Leva7** [comment]
This issue should remain open as it is a painful process for beginners, especially the ones with little to no Java experience, to make up their own native components or adapt the existing Java code for React Native

**Comment by hramos** [comment]
We've moved the docs! Feel free to reopen at https://github.com/facebook/react-native-website if you're still interested in seeing this.
