### ISSUE TITLE
[Android] LayoutAnimation crashes on certain devices

### ISSUE THREAD

**Issue by matihabbas** [facebook/react-native#15698]
### Is this a bug report?

Yes.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes.

### Environment

1. `react-native -v`: 0.47.0
2. `node -v`: 8.4.0
3. `npm -v`: 5.3.0

Then, specify:

- Target Platform: Android
- Development Operating System: macOS 10.12.6
- Build tools: 23.0.1

### Steps to Reproduce

Description:

App crashes on while setting `setLayoutAnimationEnabledExperimental(true)` on certain Android devices. The crash is only seen on devices with the Adreno 330 GPU on Android 5.0+. Examples of devices on which it is crashing are:

1. Samsung Galaxy S5
2. One Plus One
3. Nexus 5
4. HTC One M8
5. LG G2/G3
6. Sony Xperia Z2/Z3

Note: the app will only crash on a real device with the mentioned GPU. Has not been reported otherwise.

Steps:

1. `setLayoutAnimationEnabledExperimental(true)`
2. `LayoutAnimation.easeInEaseOut()`
3. Render view

### Expected Behavior

Should perform Layout Animations.

### Actual Behavior

Crashes with stacktrace:

`Fatal Exception: java.lang.IllegalStateException: Unable to create layer for d
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:143)
       at android.os.Looper.loop(Looper.java:122)
       at android.app.ActivityThread.main(ActivityThread.java:5569)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:931)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:726)`

Note: Not using `setLayoutAnimationEnabledExperimental` fixes the crash.

**Comment by ChristianGR11093** [comment]
Wat moet ik doen

**Comment by dluksza** [comment]
I've got this exception on RN 0.50.4

![screen shot 2017-12-02 at 18 48 03](https://user-images.githubusercontent.com/127442/33518199-67e83f00-d791-11e7-97db-196984fd76d3.png)

**Comment by dluksza** [comment]
Today  got the same issue on RN 0.51.0 it seams that only Android 6.0 is affected.

**Comment by DanGDroid** [comment]
FATAL
still active bug.

RN 0.51
Samsung SM-G900F
Android 6.0.1

i use it in constructor as:
```javascript
 UIManager.setLayoutAnimationEnabledExperimental && UIManager.setLayoutAnimationEnabledExperimental(true);
```
and the crash is when dispatch:
```javascript
LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut)
```

**Comment by yaronlevi** [comment]
Same here +1

**Comment by Winglonelion** [comment]
same here +1
