### ISSUE TITLE
Image component prevents ListView to render

### ISSUE THREAD

**Issue by alvaromb** [facebook/react-native#1570]
When using an `Image` component inside a `ListView` to render a series of items, I pass an image URL to the source `uri` prop:

```jsx
<Image source={{uri: rowData.media}} resizeMode='cover' style={styles.image} />
```

`rowData.media` being `https://www.meneame.net/backend/media?type=link&id=2426367`. However, if I use our [Thumbor](http://thumbor.org) server to generate thumbnails based on the previous image URL, the `ListView` doesn't even render. The Thumborized URL is: `http://thumbor.eduherraiz.com/unsafe/750x310/www.meneame.net/backend/media?type=link&id=2426126`.

Does anyone know how can this happen?

**Comment by lazywei** [comment]
Do you mean it is working when using `https://www.meneame.net/backend/media?type=link&id=2426367`, but it is not working when using `http://thumbor.eduherraiz.com/unsafe/750x310/www.meneame.net/backend/media?type=link&id=2426126`?

I found I can't reproduce this. I tried the latter URI in my listview component, it works correctly.

Did you set the `style` props to your Image?

**Comment by alvaromb** [comment]
Yes @lazywei , that's what I meant. The style props were correctly set but the issue was when composing the image URL. The API was returning an entry without image and the URL generation was breaking but I couldn't see any errors in the console. Enabling `Pause On Caught Exceptions` in Google Chrome helped me to find the bug.

Thanks for helping me!
