### ISSUE TITLE
Is react-native complete joke on windows?

### ISSUE THREAD

**Issue by MikeMnD** [facebook/react-native#15700]
Just to summarise the facts.
Yesterday I received the source code of react-native app "build" on linux for the last 2 months.
ENV: ubuntu 16.06, Node 6.10.3, npm 3.10.10
So I have just to build it on my windows machine to change some hard coded texts.

For the past 30 hours I tried:

- Installing different versions of Node, npm (learned about nvm-windows and used it to try different combination for Node - Npm (Node 6.1.3, Node 6.11.2, npm 3.10.10., npm 4.6, npm 5... but npm5 doesn't work with react-native at all)
- Install and uninstalled JDK 7, JDK 8, Android SDK, watchman, expo, yarn, chocolatey, python
- Reinstalled JAVA, added whatever is needed to system PATH as environment variables JAVA_HOME, JAVA_SDK_HOME, ADP
- Different combinations of versions for react, react-native (0.46, 0.47, 0.44), native-base
- Changed buildToolsVersion for some packages from 23.1.0. to  '25.0.0'
- I've tried `npm start`, `npm --clear-cache`, `react-native start`, `npm install && npm start -- --reset-cach`
- I've completely uninstalled watchman - since that was frequently met problem to others. It needed multiple times of running `watchman watch-del-all`
- I've used `rm -rf ./node_modules` and also deleted by hand number of times the node_modules... to have a clean start of the dependency hell...
- I've read more than 50+ issues and developers posts and tried their "fixes" and "combinations" but 50% of them were for linux or mac
- I've tried the examples from the documentation of react-native with top notch version 0.4.7 - nothing builds
- I've tried pure native-react app (without native code installed with `create-react-native-app AwesomeProject`)   - nothing but build errors for duplicate modules, 
- I tried react-native start, react-native run-android
- I've tried building it from the console directly with graddle
- I've tired building it with different environment , platform SDK version trough Android Studio
- I'have 5 pure example projects: AwesomeProject, AwesomeProject2 (made with native-starter-kit which is  "A Starter Kit for React Native + NativeBase + React Navigation + Redux + CodePush Apps (iOS & Android)" - but after all ... I've gave it a try.) expo-app - made with this `exp init your-project-name`

Most of the time the errors were:
#14209 - which dont have solution from 4 months
other often errors were:
![reacthistory4](https://user-images.githubusercontent.com/186191/29858995-c39129de-8d68-11e7-96ce-db7bb4efea4e.jpg)
![reacthistory5](https://user-images.githubusercontent.com/186191/29858997-c395ce08-8d68-11e7-8fc3-f358ca99ba60.jpg)

offtopic:
And in the mean time I received another native Android project who needed a little fix... I've setup the project, made the fix and build it in 20 minutes... and I LITERALLY forget that I've did this job still fighting with setting up and trying to build anything with react-native... even samples and hello-words

Something is terribly wrong with react-native under windows. 

Also I'm willing to give a real money price at the moment if someone give me a working react-native project and documented step by step with instructions and environment setup.

Peace out!

p.s
To be completely honest I've managed to build 2 times an empty hello world app made of: 
{
	"name": "rn_test_app",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"start": "node node_modules/react-native/local-cli/cli.js start",
		"test": "jest"
	},
	"dependencies": {
		"react": "16.0.0-alpha.12",
		"react-native": "0.47.2"
	},
	"devDependencies": {
		"babel-jest": "20.0.3",
		"babel-preset-react-native": "3.0.1",
		"jest": "20.0.4",
		"react-test-renderer": "16.0.0-alpha.12"
	},
	"jest": {
		"preset": "react-native"
	}
}
and build with: `react-native start` in one console, and `react-native run-android` in other console...
yes if you just go with `react-native run-android` results in new "cmd" opening and the results differs to some errors

p.s.2
Today i found this: https://arielelkin.github.io/articles/why-im-not-a-react-native-developer 
It can't be more true.

**Comment by MikeMnD** [comment]
Just a quick reference about the build results from the two consoles: the one with "start" and the one with "run-android"

![screenshot_1504095683](https://user-images.githubusercontent.com/186191/29872793-b4991244-8d99-11e7-98e2-ade37371d675.png)
![screenshot_1504095686](https://user-images.githubusercontent.com/186191/29872794-b499cbbc-8d99-11e7-9cbd-c2fd4e6fb3a0.png)

[console2.txt](https://github.com/facebook/react-native/files/1263594/console2.txt)
[console.txt](https://github.com/facebook/react-native/files/1263593/console.txt)

**Comment by chirag04** [comment]
@facebook-github-bot no-template

**Comment by Droppers** [comment]
@MikeMnD I am just happy to hear I am not the only one.

**Comment by sjmueller** [comment]
If it makes you feel any better @MikeMnD, the OSX community has also been dealing with the horrendous `AccessibilityInfo` bug for months -- and we feel completely ignored by the core team.

Our startup has literally pinned RN to a single random commit somewhere between `0.47` and `0.48`, we are so afraid to touch anything because of various exceptions and broken stuff that started cropping up ever since `0.44`. I'm quite disappointed to see how far react native has come, only to slide into a multi-month trough of instability with little feedback from maintainers.

**Comment by MikeMnD** [comment]
Others people pain can't make me feel better. 
I just hope react-native team to take some serious measures. And if needed to focus and to support only one platform at first, cause their claims for "support" and "working" are duck-taped on prayers, voodoo shamanism and witchery.
