### ISSUE TITLE
Orientation Native Module is not available

### ISSUE THREAD

**Issue by ferminmoli** [facebook/react-native#15711]
1. `react-native -v`: 0.45.1
2. `node -v`: 6.10.0
3. `npm -v`: 5.3.0

- Target Platform: Android/Ios
- Development Operating System: Windows 10
- Build tools: 23

https://user-images.githubusercontent.com/10004370/29878252-61b59af0-8d78-11e7-92ba-da584d8e8000.png

You can see there that Orientation is not present. This breaks: [https://github.com/yamill/react-native-orientation/issues/218](url)

**Comment by chirag04** [comment]
Doesn't look like an RN bug. please continue to use issue tracker on rn-orientation. Let me know if this needs to be reopened.
