### ISSUE TITLE
TouchableOpacity not working on ONCLICKING but working on ONPRESSING

### ISSUE THREAD

**Issue by hash9** [facebook/react-native#15712]
I am facing this issue of TouchableOpacity not working when clicking but working on pressing(or on touch) in ios simulator. 
Below is my code.
`<TouchableOpacity
                style={{ height: 40 }}
                hitSlop={{ top: 10 }}
                onPress={this.onPressSettings}
            >
              <View style={styles.thirdChildView}>
                <Image
                    source={require('../../../../images/icon_settings.png')}
                />
                <Text style={[styles.itemText, { paddingLeft: 18 }]}>
                  Settings
                </Text>
              </View>
            </TouchableOpacity>`

**Comment by chirag04** [comment]
@facebook-github-bot no-template
