### ISSUE TITLE
Geolocation timed out, code 3

### ISSUE THREAD

**Issue by iamdurui** [facebook/react-native#15718]
my code is 
navigator.geolocation.getCurrentPosition(
      position => {
        console.log(position)
      },
      error => {
        console.log(error)
      },
      {
        enableHighAccuracy: Platform.OS !== 'android',
        timeout: 20000
      }
    )
Before when I open the device's position 
the result is   code:1  message: "No location provider available."
After when I open the device's position 
the result is   code:3   message: "Location request timed out"

my device is Nexus 5 android version 4.4.4

1. `react-native -v`: 0.46.2
2. `node -v`:v8.2.0
3. `npm -v`:5.3.0

- Build tools:25.0.0  minSdkVersion 16  targetSdkVersion 22

**Comment by iamdurui** [comment]
@hramos why?

**Comment by kelset** [comment]
@iamdurui duplicate issue (see #7495) and you haven't respected the template for issues.

**Comment by AmeerAqnawe** [comment]
Have you solved it ?!
