### ISSUE TITLE
[Android] NetInfo is not working properly under power saving mode

### ISSUE THREAD

**Issue by xingsuo** [facebook/react-native#15729]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

1. `react-native -v`: 0.47.2
2. `node -v`: v6.10.3
3. `npm -v`: 3.10.10

Then, specify:

- Target Platform: Android

- Development Operating System: macOS

- Build tools: react-native & Android studio

### Steps to Reproduce

This bug happened when I try to use NetInfo library to listen if there is network connection. 
The example I use is from the official site: https://facebook.github.io/react-native/releases/0.24/docs/netinfo.html
1. Run this code on android
2. Disattach the cable to make sure the phone is not under charging
3. Open the app find the app is online 
4. Turn on the power saving mode
5. Press Android back button to exit the app (It's only happen when press the back key to exit not the home button)
6. Open app again find the app is now offline (You can try multiple times and will find out that sometimes it's offline sometimes it's online again. The result may be not constant. )

### Expected Behavior

The app is still online when it's open no matter the power saving mode turn on or not.

### Actual Behavior

Most of the time, the app is offline when turn on the power saving mode and use the android back key to exit the app and open again.

### Reproducible Demo
https://snack.expo.io/ByLt21UtZ

**Comment by vishnuc** [comment]
Same problem for me

**Comment by jkimbo** [comment]
I can reproduce this issue as well on a Samsung SM-G930F. In my case it happens after opening the camera app using `react-native-image-picker` and it seems quite intermittent. Also I didn't need to unplug the device to reproduce it.

I suspect the issue is due to power saving preventing apps from using data when in the background.

**Comment by AndrewIngram** [comment]
Is commit https://github.com/facebook/react-native/commit/e6f542d62037e9830c0ae5749a32874c44cf2334 related to this issue?

**Comment by gabsima** [comment]
This is happening to me on react native 0.49.5

**Comment by gabsima** [comment]
As a workaround i made a retry connexion button that fetches google. If it throws, i know i am really offline, if everything goes well, i know i am connected to the internet.
