### ISSUE TITLE
'React/RCTShadowView+Layout.h' file not found

### ISSUE THREAD

**Issue by iegik** [facebook/react-native#15722]
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

yes

### Environment

1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.47.0-rc.3
2. `node -v`:
v8.4.0
3. `npm -v`:
5.3.0
4. `yarn --version`:

Then, specify:

- Target Platform: iOS

- Development Operating System: macOS 10.12.6

- Build tools: 
Xcode 8.3.1

### Steps to Reproduce

(Write your steps here:)

1. npm i react-native@0.47.0-rc.3
2. Run project in Xcode
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

Error thrown: 'React/RCTShadowView+Layout.h' file not found
node_modules/react-native/Libraries/Text/RCTTextManager.m:16

```
#import <React/RCTShadowView+Layout.h>
```

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by radko93** [comment]
Why are you using rc version and not the final version?

**Comment by iegik** [comment]
Recently, I clean project, unlink all libraries and manually remove all reffirences from iOS project.

```
npm i react@16.0.0-alpha.12
npm i react-native@0.45.1 
react-native upgrade
```

(replaced all files to defaults)

Try to build project and got same error, on 0.45.0

**Comment by hramos** [comment]
Please verify against either 0.47.2 (the latest stable version), or v0.48.0-rc.1, the most recent release candidate. We want to make sure we address bugs that are present in either of these versions, so checking against older releases does not help much. An exception where checking against an older release is verifying if a confirmed issue is a regression.

**Comment by iegik** [comment]
I cant: https://github.com/facebook/react-native/issues/15621
