### ISSUE TITLE
NetInfo.isConnected.fetch() not working in background Android

### ISSUE THREAD

**Issue by ShaileshPrajapati-BTC** [facebook/react-native#15735]
### Is this a bug report?
Yes

NetInfo.isConnected.fetch() is not working in background android.when app is open works fine but when we minimize app and stop internet it will not change the state also tried with addEventListener too. 

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

1. `react-native -v`: 0.44.0
2. `node -v`: v7.10.1
3. `npm -v`: 4.2.0
4. `yarn --version`: no

Then, specify:

- Target Platform: Android

- Development Operating System: linux

- Build tools: Android Studio

### Steps to Reproduce

1.Connect your device with internet(turn on wifi or mobile data) and start app will give you a internet status  `true`
2.Press home button app will go in background and then disconnect internet(turn off mobile data or wifi) from mobile `NetInfo` will not change the state it will show true even if the internet is off but when we open app again `NetInfo` change the internet status `false` 
3.Try with `addEventListener` and without same result

### Expected Behavior

it should give internet state even if app is in background.

### Actual Behavior

When app is open give the internet state but when press home button app not changing internet state show previous state of internet.

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by kelset** [comment]
It looks you are 3 versions (4 soon) behind, have you checked the release notes for newer versions? It may have been fixed already.

**Comment by JonasWho** [comment]
I also have this issue. I looked through the release docs and I didn't find anything about NetInfo in newer version updates. I am on RN 0.43.4 myself.

**Comment by tichondrius** [comment]
I have same problem when get network on background! IOS not happen

**Comment by vishnuc** [comment]
same for me , happens in both ios and android

**Comment by colinclarkbcgdv** [comment]
`NetInfo.addEventListener` does not work even when the AppState is `active`
