### ISSUE TITLE
[Bridge] requireNativeComponent should not require native props

### ISSUE THREAD

**Issue by jwyld** [facebook/react-native#1574]
It would be possible to provide a native UI element which has no exposed properties.  I don't know how often this occurs in practice, but it certainly happened while I was first creating and exposing my native view.  requireNativeComponent.js:45 verifies there are native props being exported.  If there are none, it slips the UnimplementedView into place.

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/bridge-requirenativecomponent-should-not-require-native-props
