### ISSUE TITLE
[ListView] Tap status bar to scroll to the top not working

### ISSUE THREAD

**Issue by marcshilling** [facebook/react-native#1575]
I have a TabBarIOS at the root. One of the tabs contains a NavigatorIOS, whose root is a simple ListView with content that extends past the bounds of the screen. I would expect to be able to tap on the status bar when scrolled all the way to the bottom to return to the top. This isn't working, even when I explicitly set `scrollsToTop={true}` on the ListView (although it is supposed to be true by default)

**Comment by ide** [comment]
This is how UIKit behaves -- go through the ScrollViews in your app and make sure that all of them have `scrollsToTop={false}` except for the one you want to scroll to the top. See https://stackoverflow.com/questions/8527801/how-to-find-out-which-other-uiscrollview-interferes-with-scrollstotop for tips.

**Comment by marcshilling** [comment]
@ide but, there are no other scroll views...the ListView is at the top level.

**Comment by ide** [comment]
How barebones is your code? Try paring it down to only the TabBarIOS, NavigatorIOS, and ListView with empty View cells if you haven't already.

**Comment by marcshilling** [comment]
Aha! I found it - it was my slide out side menu that had a ScrollView in it. Setting `scrollsToTop={false}` on that did the trick. I also did not know this was default UIKit behavior! Thanks @ide

**Comment by jiyinyiyong** [comment]
We have to leave **only a single ScrollViews** with `scrollsToTop={true}`, at last I figured out that **a ListView is also a ScrollView**. Took me long time to find out the problem.

**Comment by Cordazar** [comment]
@ide But this should be `false` by default. That way you just set it to true when you actually needs that behaviour. Currently it's a pain to go around disabling the feature everywhere to work around the native behaviour.

**Comment by ide** [comment]
@Cordazar make CordazarScrollView that changes the default value and use it in your app / publish it to npm and if a lot of people really like it we can change the default in RN.
