### ISSUE TITLE
I'm unable to grab the item upon click... 

### ISSUE THREAD

**Issue by jpca999** [facebook/react-native#15757]
Here's the full question. 
https://stackoverflow.com/q/45993677/2403823

### Is this a bug report?

(write your answer here)

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.)

### Environment

1. `react-native -v`:
2. `node -v`:
3. `npm -v`:
4. `yarn --version`:

Then, specify:

- Target Platform:

- Development Operating System:

- Build tools:

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by chirag04** [comment]
@facebook-github-bot no-template

**Comment by chirag04** [comment]
@jpca999 i would suggest continuing to use stack-overflow for questions like these.
