### ISSUE TITLE
ld: library not found for -lRCTBlob

### ISSUE THREAD

**Issue by crajesh238** [facebook/react-native#15767]
created a new project with react-native init
{
	"name": "Test1",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"start": "node node_modules/react-native/local-cli/cli.js start",
		"test": "jest"
	},
	"dependencies": {
		"react": "16.0.0-alpha.12",
		"react-native": "0.47.1"
	},
	"devDependencies": {
		"babel-jest": "20.0.3",
		"babel-preset-react-native": "2.1.0",
		"jest": "20.0.4",
		"react-test-renderer": "16.0.0-alpha.12"
	},
	"jest": {
		"preset": "react-native"
	}
}

ld: library not found for -lRCTBlob
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

The following commands produced analyzer issues:

	Analyze /Users/rajeshchilukuri/Documents/Projects/reactNative/Test1/node_modules/react-native/ReactCommon/yoga/yoga/YGNodeList.c
	Analyze /Users/rajeshchilukuri/Documents/Projects/reactNative/Test1/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.c
(2 commands with analyzer issues)

The following build commands failed:
	Ld build/Build/Products/Debug-iphonesimulator/Test1.app/Test1 normal x86_64
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/Test1.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/Test1.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

react-native -version
react-native-cli: 2.0.1
react-native: 0.47.1

**Comment by Doko-Demo-Doa** [comment]
Are you sure you created project with RN 0.47.1 ?

0.48.0 has just been released.

**Comment by crajesh238** [comment]
Before 0.47 worked and have an app too working. I updated to 0.48 for a new app and it crashed. So reverted to 0.47.1 but still not working.. really strange

**Comment by crajesh238** [comment]
Now the app just crashes thats it without any error display

**Comment by drakmail** [comment]
Have same problem with 0.48 in fresh app

**Comment by Doko-Demo-Doa** [comment]
Seems like the new version has some breaking changes.

**Comment by grabbou** [comment]
> Now the app just crashes thats it without any error display

That has been fixed already.

**Comment by stereodenis** [comment]
present in  0.48.4

**Comment by RyanRong** [comment]
me too,
I init Project with current version 0.50,
but I modify dependencies 

{
	"name": "PickerTest",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"start": "node node_modules/react-native/local-cli/cli.js start",
		"test": "jest"
	},
	"dependencies": {
		"react": "16.0.0-alpha.6",
		"react-native": "0.44.3"
	},
	"devDependencies": {
		"babel-jest": "21.2.0",
		"babel-preset-react-native": "4.0.0",
		"jest": "21.2.1",
		"react-test-renderer": "16.0.0-alpha.6"
	},
	"jest": {
		"preset": "react-native"
	}
}

**Comment by tirrorex** [comment]
doesn't seem to be fixed

**Comment by dcordz** [comment]
I had the same error, what solved it was:
1. Go to Link the `Build Phases` tab in Xcode
2. Select `libRCTBlob.a` under `Link Binary with Libraries` and then click the `-` sign below.
3. Close and re-open Xcode
4. Click the `+` sign and re-add `libRCTBlob.a`
