### ISSUE TITLE
Horizontal ScrollView Sensitivity?

### ISSUE THREAD

**Issue by joecaraccio** [facebook/react-native#15766]
### Is this a bug report?
No

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

One of the things I am having a hard time finding documentation for is the ScrollView.. particularly in a horizontal mode. I am trying to implement a Instagram like navigation.. where the app is smart enough to know if you are say... scrolling up and down or horizontally scrolling the view

The issue I have found, is the ScrollView will move on diagnal drags... whereas some of that could just be from user error as they intended to pull downwards but the DX was not 0, triggering the horizontal scroll view

Does anyone have a solution to this? Or a way to override the scrollview's sensitivity to only respond when the other direction, (dy or dx) isn't a large value? Did this make sense? Has anyone implimented something like this or know how to do this? I have had a hard time figuring out in the documentation how to pull something like this off

I also think this would be a good prop... some sort of way to edit the sensitivity if there is movement in the opposite direction

**Comment by rajsuvariya** [comment]
hjk

**Comment by qmegas** [comment]
I also faced that problem, does anyone have solution for this?

**Comment by evanjmg** [comment]
+1
