### ISSUE TITLE
cant scroll when TextInput has TextAlign - Android

### ISSUE THREAD

**Issue by amirrezamahyari** [facebook/react-native#15764]
when i trying to set TextAlign style to a TextInput , i cant scroll when start touching from that TextInput , in ios everything is fine , thats maybe a bug ?
is anyone has any idea how to solve it ?

**Comment by piyush2468** [comment]
I think it's a Bug because if it's working in IOS and not working anywhere else.
I am sure it's a bug.

**Comment by sinapcs** [comment]
Hi I have this problem too.
I solved this by a trick but it has it's own problems.
You can use this component instead of TextInput
https://github.com/sinapcs/react-native-scrollable-text-input/blob/master/ScrollableTextInput.js
