### ISSUE TITLE
create a new react App with react-native init tool makes impossible to run App in iOS Simulator

### ISSUE THREAD

**Issue by rafaga** [facebook/react-native#15768]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.48.0
2. `node -v`:
v8.4.0
3. `npm -v`:
5.3.0
4. `yarn --version`:
0.27.5
Then, specify:

- Target Platform: iOS

- Development Operating System: macOS 10.12.6 (16G29)

- Build tools: No i'm using the default tool to build but i have XCode installed

### Steps to Reproduce

(Write your steps here:)

1. run react-native init coms
2. cd coms
3. react-native run-ios
4. react-native log-ios

### Expected Behavior
runs react native Application in iOS simulator. with the default code generated by react-native-cli

(Write what you thought would happen.)

### Actual Behavior
it build fine, and installs the App into the iOS simulator but when tries to run the app the app exists without any visible message or error and refuses to run.

in stderr screen running react-native log-ios this appears:

```
coms[7364] <Error>: assertion failed: 16G29 14E8301: libxpc.dylib + 64131 [624BAF4F-2E03-34F8-ACBA-970B04637786]: 0x7d
Unknown[7364] <Error>: 
coms[7364] <Notice>: Initializing <RCTCxxBridge: 0x6000001a2d80> (parent: <RCTBridge: 0x6000000a1ce0>, executor: (null))
coms[7364] <Warning>: Class RCTCxxModule was not exported. Did you forget to use RCT_EXPORT_MODULE()?
coms[7364] <Notice>: Running application coms ({
        initialProps =     {
        };
        rootTag = 1;
    })
coms[7364] <Error>: -[NSTaggedPointerString unsignedIntValue]: unrecognized selector sent to instance 0xa313537323930327
coms[7364] <Error>: *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSTaggedPointerString unsignedIntValue]: unrecognized selector sent to instance 0xa313537323930327'
    *** First throw call stack:
    (
        0   CoreFoundation                      0x000000010d419b0b __exceptionPreprocess + 171
        1   libobjc.A.dylib                     0x000000010c2cf141 objc_exception_throw + 48
        2   CoreFoundation                      0x000000010d489134 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
        3   CoreFoundation                      0x000000010d3a0840 ___forwarding___ + 1024
        4   CoreFoundation                      0x000000010d3a03b8 _CF_forwarding_prep_0 + 120
        5   coms                                0x000000010b6a70d4 -[RCTMultipartStreamReader emitProgress:contentLength:final:callback:] + 244
        6   coms                                0x000000010b6a78ca -[RCTMultipartStreamReader readAllPartsWithCompletionCallback:progressCallback:] + 1610
        7   coms                                0x000000010b6f71fc -[RCTMultipartDataTask URLSession:streamTask:didBecomeInputStream:outputStream:] + 444
        8   CFNetwork                           0x000000010ce79c51 __88-[NSURLSession delegate_streamTask:didBecomeInputStream:outputStream:completionHandler:]_block_invoke + 51
        9   Foundation                          0x000000010bdd93b7 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
        10  Foundation                          0x000000010bdd90bb -[NSBlockOperation main] + 101
        11  Foundation                          0x000000010bdd7877 -[__NSOperationInternal _start:] + 627
        12  Foundation                          0x000000010bdd35fc __NSOQSchedule_f + 198
        13  libdispatch.dylib                   0x00000001110f4792 _dispatch_client_callout + 8
        14  libdispatch.dylib                   0x00000001110da237 _dispatch_queue_serial_drain + 1022
        15  libdispatch.dylib                   0x00000001110da98f _dispatch_queue_invoke + 1053
        16  libdispatch.dylib                   0x00000001110dc899 _dispatch_root_queue_drain + 813
        17  libdispatch.dylib                   0x00000001110dc50d _dispatch_worker_thread3 + 113
        18  libsystem_pthread.dylib             0x00000001114885a2 _pthread_wqthread + 1299
        19  libsystem_pthread.dylib             0x000000011148807d start_wqthread + 13
    )
SpringBoard[3413] <Error>: [KeyboardArbiter] HW kbd: Failed to set (null) as keyboard focus
com.apple.CoreSimulator.SimDevice.E2457C7B-7E39-4B0A-B1C4-0FF23CDB1193.launchd_sim[3395] (UIKitApplication:org.reactjs.native.example.coms[0xeff5][3418][7364]) <Notice>: Service exited due to Abort trap: 6
backboardd[3414] <Error>: [Common] Unable to get short BSD proc info for 7364: No such process
backboardd[3414] <Error>: [Common] Unable to get proc info for 7364: Undefined error: 0
assertiond[3418] <Warning>: Deleted job with label: UIKitApplication:org.reactjs.native.example.coms[0xeff5][3418]
```

### Reproducible Demo

Theres is not a reproducible demo, due to the that the problem is into iOS Simulator

### Detected work around ###

creating an app with create-react-native-app tool and executing yarn eject or npm eject, creates a app structure that has no problems into the iOS emulator

**Comment by usakc** [comment]
Hi,
here is quick fix for this error:
`"postinstall":  "sed -i '' 's/\\[headers\\[@\"Content-Length\"\\] unsignedIntValue\\]/\\[headers\\[@\"Content-Length\"\\] intValue\\]/' ./node_modules/react-native/React/Base/RCTMultipartStreamReader.m"`
Add it to "scripts" in package.json in your project.

Also fixed in this PR GH-15755.

**Comment by matt-schrader** [comment]
I just ran into this also.  Usakc's response fixed it.  Thanks for the quick response!

**Comment by leandrodavimg** [comment]
I have the same problem, and I still do not know the solution.
The difference of what works in my projects is "react-native": "0.47.2"

**Comment by krittiyaclark** [comment]
That works if this is a first project for my case is prod/albums but when I created a second project it keeps trow an error when I run react-native run-ios.
This is what I do: - Go to a _prod_ folder run `react-native init auth --version 0.47.2`.
                             - It built a project and I go to _prod/auth_ then run `npm install`
                             - It built again then run `react-native run-ios` and here an error message.
![screen shot 2017-09-03 at 10 55 57 am](https://user-images.githubusercontent.com/3038228/30004074-85aa1f5a-9096-11e7-8c5c-692da03bb930.png)

**Comment by fanwise** [comment]
`[headers[@"Content-Length"] unsignedIntValue]`in `./node_modules/react-native/React/Base/RCTMultipartStreamReader.m` cause the problem.
`headers[@"Content-Length"]` is a NSString, but the unsignedIntValue is a selector for NSNumber.
replace the code with `(NSUInteger)[headers[@"Content-Length"] integerValue]` can fix it. Because integerValue works both on NSString and NSNumber

**Comment by LiLiKazine** [comment]
what usakc said won't do for me, yet i went to RCTMultipartStreamReader.m and replace unsignedIntValue with intValue then it worked! Don't know why changes in package.json didn't work, though.

**Comment by Phieo** [comment]
@usakc It works for me, thanks.

**Comment by dabit3** [comment]
This issue has been fixed in version [0.48.1](https://github.com/facebook/react-native/releases/tag/v0.48.1)

**Comment by suckoja** [comment]
Can confirm to @dabit3, upgrade to 0.48.1 is fixing this issue now.

**Comment by uokesita** [comment]
I had this problem since yesterday, upgrading to 0.48.1 fixed for me

**Comment by fachilles** [comment]
#15779

**Comment by iegik** [comment]
![2017-09-04 17 54 15](https://user-images.githubusercontent.com/175293/30031442-22ff436c-919a-11e7-8efa-fff2acca44f5.png)

Same problem on:
react-native-cli: 2.0.1
react-native: 0.48.1

**Comment by fachilles** [comment]
It's a real bug. Try the new version 0.48.1. 
Duplicated  #15779

**Comment by iegik** [comment]
already tried, no luck

**Comment by rafaga** [comment]
i have tested with 0.48.1, seems fixed now

**Comment by dabit3** [comment]
@rafaga I've also tested with 0.48.1 and seems to work whereas 0.48.0 did not. @iegik , what errors are you getting? Thanks.

**Comment by iegik** [comment]
@dabit3 maybe it fixed in some of master commits or 0.49.0-rc.*...
@grabbou grabbou tagged this 2 days ago · 272 commits to master since this tag
but I did not see "Content-Length" line in https://github.com/facebook/react-native/blob/v0.48.1/React/Base/RCTMultipartStreamReader.m

**Comment by iegik** [comment]
I still cannot launch my app since 0.45.1 on android https://github.com/facebook/react-native/issues/15621

**Comment by jcxc** [comment]
@fanwise  it works for me, thank U

**Comment by HananeAlSamrout** [comment]
downgrading to 0.48.1 worked for me

**Comment by jasonzhangdong** [comment]
```
Feb 28 11:05:18 iPhone-chenyu wepilotrelase(CoreFoundation)[17432] <Notice>: -[__NSCFString unsignedIntValue]: unrecognized selector sent to instance 0x1c442f720
Feb 28 11:05:18 iPhone-chenyu wepilotrelase[17432] <Notice>: Exception '-[__NSCFString unsignedIntValue]: unrecognized selector sent to instance 0x1c442f720' was thrown while invoking pay on target WeChat with params (
        {
        nonceStr = 322a45a25fb119b2fac403e6a2cc011c;
        package = "Sign=WXPay";
        partnerId = 1578411422;
        prepayId = wx20180228110517c3b3a2fc600991055163;
        sign = C113CB1A20EC33513C3810BF8B17745C;
        timeStamp = 1519787117;
    },
    6643
)
callstack: (
	0   CoreFoundation                      0x0000000182e0237c <redacted> + 148
	1   libobjc.A.dylib                     0x0000000182048528 objc_exception_throw + 56
	2   CoreFoundation                      0x0000000182e0f828 <redacted> + 0
	3   CoreFoundation                      0x0000000182e07d10 <redacted> + 1380
	4   CoreFoundation                      0x0000000182cececc _CF_forwarding_prep_0 + 92
	5   wepilotrelase                       0x00000001011c1c98 _ZNSt3__112__hash_tableINS_17__hash_value_typeINS_12basic_stringIcNS_11char_traitsIcEENS_9allocato<\M-b\M^@\M-&>
```
