### ISSUE TITLE
SectionList yellowbox misleading

### ISSUE THREAD

**Issue by GantMan** [facebook/react-native#15772]
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

yes

### Environment

1. `react-native -v`:  react-native-cli: 2.0.1 & react-native: 0.47.2
2. `node -v`: v8.4.0
3. `npm -v`: 5.3.0
4. `yarn --version`: 0.27.5

Then, specify:

- Target Platform: iOS

- Development Operating System: Mac OS X

- Build tools: `react-native run-ios`

### Steps to Reproduce

1. Create a `SectionList`
2. Add `flexWrap: 'wrap'` style to the `contentContainerStyle`
3. See misleading yellowbox

### Expected Behavior

SectionList doesn't support numColumns.  So there should be no yellowbox telling me to add it.

(Write what you thought would happen.)

### Actual Behavior

FlatList warning comes in with advice that is useless on SectionList.   It also says it won't work, when it works just fine.  
![image](https://user-images.githubusercontent.com/997157/30005291-b7d45640-90a4-11e7-8df3-437e0cca5f4a.png)

### What should happen?

If we are going to add numColumns to SectionList, then the message should be different.  If we are not, then the yellowbox shouldn't show.

https://github.com/facebook/react-native/blob/57c7324ab7679df9a26d0b41e9fffba9dd50bd98/Libraries/Lists/VirtualizedList.js#L545-L548

I'm happy to fix this depending on what the proper path for SectionList is.  Also, I need to know why we're showing a warning saying it doesn't work, when it does.  Let me know how to proceed in fixing!

**Comment by robbawebba** [comment]
@GantMan I'm glad you brought this up! I'm happy that the `flexWrap` css property still works even though we're warned not to use it, but I'm reluctant to use it in my app because of the warning. The react native team must've included this warning for a reason, right? I'm starting to see some wacky rendering behavior with the `flexWrap` property.

Does anyone know the reason for this warning?
