### ISSUE TITLE
Was the release really tested?

### ISSUE THREAD

**Issue by Doko-Demo-Doa** [facebook/react-native#15779]
### Is this a bug report?

Yes.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes.

### Environment

1. `react-native 0.48.0`
2. `node 8.4.0`
3. `npm 5.4.0`
4. `yarn 0.27.5

Then, specify:

- Target Platform:

- Development Operating System: Mac OS Sierra 10.12.6

- Build tools: iOS

### Steps to Reproduce

(Write your steps here:)

1. `react-native init TestProject`
2. `cd TestProject`
3. `react-native run-ios`

### Expected Behavior

It should run as the example in the docs.

I would like to ask that did you really test the release (with simple init command) before releasing? Yes I know RN is currently in heavy development but since 0.46 there are many breaking changes and `init` command is a fundamental feature, it shouldn't be ignored.

### Actual Behavior

Same with #15762 

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by gre** [comment]
I also wondered about this. I remember that react-native test app is pretty decent (including the snapshot thing to check regression) but maybe it's no longer hooked to a continuous integration?

**Comment by grabbou** [comment]
Yeah, we have quite a lot of tests to run - I am running them every time I am releasing new version (including 0.49.0-rc.0).

It's my fault that I've released 0.48.0 by promoting latest RC to stable - I assumed it was already tested after someone cherry-picked commits. I am going to add appropriate mention to the "Releasing.md" file.
