### ISSUE TITLE
Re-open #3198

### ISSUE THREAD

**Issue by Elijen** [facebook/react-native#15774]
Can we re-open #3198? It was closed for inactivity, but was not fixed (AFAIK) and is a popular demand (see https://react-native.canny.io/feature-requests/p/add-overflow-support-to-android)

**Comment by hramos** [comment]
The bot left some next steps as a comment on #3198 that can help get it re-opened.

**Comment by guoliang1206** [comment]
@all does RN fixed the overflow prop on android?
