### ISSUE TITLE
Ambiguous resolution of react-native

### ISSUE THREAD

**Issue by ManvendraSK** [facebook/react-native#15789]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

1. `react-native -v`: 2.0.1
2. `node -v`: v8.4.0
3. `npm -v`: 5.3.0
4. `yarn --version`:

Then, specify:

- Target Platform: Android

- Development Operating System: Windows 10 Home

- Build tools: Android Studio

### Steps to Reproduce

(Write your steps here:)

1. Rename `node_modules` directory to `node_modules_`. 
2. Delete `android` directory.
3. Execute `npm i`
4. Execute `react-native upgrade`
5. Execute `react-native run-android`

After not working I even deleted the `node_modules_` directory. But the problem still persists. 

### Expected Behavior

It should just work as expected, run the app in the Android emulator. 

### Actual Behavior

It's not working. React packager is complaining.

### Reproducible Demo

https://github.com/ManvendraSK/ChatNowReactNativeSampleApp

![packager](https://user-images.githubusercontent.com/3501410/30033421-d3f97bec-91b8-11e7-944a-71ecc9a07571.PNG)
![command](https://user-images.githubusercontent.com/3501410/30033424-d50c230e-91b8-11e7-99db-70cbd407d0e0.PNG)
![emulator](https://user-images.githubusercontent.com/3501410/30033422-d415c1da-91b8-11e7-8df9-d9e445b46f17.PNG)

**Comment by ManvendraSK** [comment]
I have recreated the emulator after deleting it. I tried a new app and existing apps, they all are working fine.

**Comment by radko93** [comment]
What's the point of having two `node_modules` folders?

**Comment by ManvendraSK** [comment]
Obviously nothing. See I renamed it to `node_modules_` (with extra **underscore**). But later I deleted it after the problem arose. But still, it is complaining to resolve from this **underscore**d directory too! How can it be?

Moreover, we can't have two folders with the same name on Windows.

**Comment by radko93** [comment]
Have you tried cleaning cache? Still, I can't see any point in doing this.

**Comment by jonathanoron** [comment]
I'm having the same problem.
It's pointing to package.json files in directories that no longer exists.
Have tried `npm cache clean` `yarn cache clean` etc...
Keeps trying to resolve the react_native module to the non-existent dirs.

**Comment by ManvendraSK** [comment]
Yes, I had tried deleting `android`, `ios`, `build` and `node_modules` directories. Then `npm i` followed by `react-native upgrade` that generates `ios` and `android` directories. Then `react-native run-android` and this problem occurs again. 

I know no point in doing this, but all I wanted to reinstall `node_modules` but I didn't want the time consumed in deleting existing `node_modules` folder, so I just renamed it to `node_modules_` folder. 

Now could you please help?

**Comment by radko93** [comment]
Maybe clean watchman cache then? If not, unfortunately, I have no clue about this.

**Comment by ManvendraSK** [comment]
Ohk, I'll try cleaning watchman cache. How to do it? Command? Directory? I'll keep you posted here. Thanks.

**Comment by jonathanoron** [comment]
@ManvendraSK try `watchman watch-del-all`
Unfortunately, it did not help me 😞

**Comment by ManvendraSK** [comment]
@jonathanoron I'll try when back at home, right now in office ;-). 

Let's see what is next, I'll keep you posted here. May be somebody would help like Batman! :-P

**Comment by jonathanoron** [comment]
@ManvendraSK `npm start -- --reset-cache ` saved the day for me:
https://github.com/facebook/react-native/issues/1924#issuecomment-249861004

**Comment by ManvendraSK** [comment]
Thanks @jonathanoron. I'll try it when at home. :+1:

**Comment by ManvendraSK** [comment]
Hey @jonathanoron and @radko93, it's working fine! 

`npm start -- --reset-cache` does work! But, after it has executed we need to kill this command and start with the usual one `react-native run-android`. `watchman` didn't work though!

Thanks, guys. You both are Batman for me!

**Comment by radko93** [comment]
@facebook-github-bot answered

**Comment by ggsrivas** [comment]
I am facing the same issue and unfortunately npm start -- --reset-cache is also not working for me. I asked this same question here,
https://stackoverflow.com/questions/46065313/react-native-packager-fails-to-create-jsbundle

**Comment by DanielRamosAcosta** [comment]
In my case, It seems that I had conflicts between `.yarn` directory and `node_modules`, despite I did a clean `yarn install`.

Deleting `.yarn` and starting the app with `npm start` solved this problem for me, but it doesn't feel like the correct solution.

**Comment by pkshefi** [comment]
i tried to install,
npm install --save react-native-router-flux@3.38.0
npm install -g react-native-git-upgrade
react-native-git-upgrade

fixed thanks folks

**Comment by yummyelin** [comment]
Reboot mac works

**Comment by DanielRamosAcosta** [comment]
Also, delete `system32`

**Comment by noumantahir** [comment]
having this same issue, I am mac, restarting doesn't work, neither refreshing node_modules and clearing cache..

Is there anything else I can try

![simulator screen shot - iphone 6 - 2018-01-09 at 03 34 47](https://user-images.githubusercontent.com/6298342/34695812-1019fc80-f4ee-11e7-86fe-5f74f5152831.png)

**Comment by jooleeanh** [comment]
**For those of you trying to create a library/bridge:**

I just got this error, and it was because I had put an `example` app inside my library:
```
.
├── README.md
├── android
│   ├── build.gradle
│   ├── libs
│   └── src
├── example
│   ├── App.js
│   ├── __tests__
│   ├── android
│   ├── app.json
│   ├── index.js
│   ├── ios
│   ├── node_modules
│   ├── package.json
│   ├── screens
│   ├── utils
│   └── yarn.lock
├── index.js
├── ios
│   └── app.xcodeproj
├── node_modules
├── package.json
└── yarn.lock
```

Which means that when I ran `react-native run-android`, my index.js would find `react-native` in `./example/node_modules`, but also in `./example/node_modules/MyApp/example/node_modules/...`.

The fix was to add a `.npmignore` file with:
`example/*`
which prevents this recursion from happening.

**Comment by Knowledge91** [comment]
For me the error appeared in calling my Project **ReactNative**! 
As soon as I changed the name to something different than **./ReactNative** the error disappeared!

**Comment by JazzJupiter** [comment]
Any idea when this will be solved? For now I cannot install any pods that install React as well.

**Comment by leaphawk** [comment]
If nothing helps remove duplicate dependencies from Pods & react native links. Then clear Pods cache & reinstall them using this : [gist](https://gist.github.com/leaphawk/b03a96073525a65a43e1ee422ffbdd08) 
then do above stuff. Spent half day on this

**Comment by evanjmg** [comment]
Generally this issue arises when there are two folders of react-native. More often, if you use Pods, you have dependency that relies on the 'React' pod and thus you should reference the pod in your node_modules/ not create install from cocopods. To do so, you can add the following to your Podfile
```
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', :path => '../node_modules/react-native', :subspecs => ['DevSupport']
```

**Comment by cameck** [comment]
Full reset that worked for me:

```bash
#!/bin/bash
echo "Completely resetting life"
echo "STARTING: Deleting Node modules"
rm -rf ./node_modules
echo "FINISHED: Deleting Node modules"
echo "STARTING: Removing yarn.lock file"
rm yarn.lock
echo "FINISHED: Removing yarn.lock file"
echo "STARTING: Deleting Watchman and yarn cache"
watchman watch-del-all
yarn cache clean
echo "STARTING: Re-installing node modules"
yarn install
echo "FINISHED: Re-installing node modules"
echo "STARTING: restarting app"
yarn start --reset-cache
```

**Comment by meehanman** [comment]
My problem was the same (renaming node_modules to node_modules_) and I found out there was another terminal window open on the desktop (I was ssh'd into the Mac) and it has Metro Bundler open. Closing this window and rerunning `npm start -- --reset-cache` solved this issue as well as deleting node_modules_.

**Comment by imapolaris** [comment]
npm start -- --reset-cache solved the problem for me. thx!!!
