### ISSUE TITLE
[Bug?] After I update to 0.6.0rc, it can't support the es6 class?

### ISSUE THREAD

**Issue by soliury** [facebook/react-native#1578]
I use `.createClass` it works well, but use `class xxx extends Component`, it failed.
It shows that :RCTDataManager.queryData was called with 4 arguments, but expects 3

**Comment by jaygarcia** [comment]
I am extending React.Component via ES6 style classes and am using 0.6.0 and do not have those exceptions :(

**Comment by athaeryn** [comment]
@soliury Are you getting those issues in the Simulator or on real hardware?

**Comment by brentvatne** [comment]
This has worked for a while, the error seems unrelated to the class problem. If all you do is toggle between the `createClass` and `extends` does that break it still?

**Comment by soliury** [comment]
I meet this problem in both simulator and hardware.

**Comment by brentvatne** [comment]
@soliury - but with both `createClass` and `extends`? or just `extends`? can you reproduce on rnplay.org?

**Comment by soliury** [comment]
Now, I close reboot and then, it works well. I don't know why.

And I have a project which using 0.4.4, and then I update it to 0.6.0-rc, it can't work. I use 0.5.0, it can works well.

It shows that : 

```
RCTDataManager.queryData was called with 4 arguments, but expects 3
```

**Comment by jaulz** [comment]
Same issue here after upgrading to 0.6.0-rc. I still try to find out whether the project files must be changed as well but haven't figured anything specific out yet.

**Comment by soliury** [comment]
I try to create a new project in 0.5.0, and then, update to 0.6.0-rc , and then , it can work. 

Then, I try to copy the new project file to my older project in 0.4.4, but it also failed. I don't know why.

**Comment by VonD** [comment]
Same problem here after upgrading to 0.6.0:

`RCTDataManager.queryData was called with 4 arguments, but expects 3`

**Comment by soliury** [comment]
it is good now when I update to 0.6.0.

**Comment by jevakallio** [comment]
I am experiencing the same issue when upgrading from 0.5.0 to 0.6.0 stable:
```
RCTDataManager.queryData was called with 4 arguments, but expects 3
```

**Comment by soliury** [comment]
Now I have no issue in 0.6.0. It runs well

**Comment by TYRONEMICHAEL** [comment]
I had the same issue. Upgraded to 0.6.0 and everything worked well. I then installed a package which required a lower version of RN. Once I removed the package, cleaned and rebuilt, everything started working again.

**Comment by soliury** [comment]
yes. This is the require bug of react-native.

**Comment by browniefed** [comment]
@soliury are you still having issues, this seems to be resolved. It appears there are multiple solutions here and on #1754 as well.

@brentvatne already solved.

**Comment by browniefed** [comment]
Although #1606 does say "Packager should fail loudly" however, the workaround is basically clearing everything out.

**Comment by soliury** [comment]
Yes, it solved. Thanks all.
