### ISSUE TITLE
Can’t find variable: Symbol

### ISSUE THREAD

**Issue by sm2017** [facebook/react-native#15786]
"Debug JS Remotely" is very buggy system , I have many issue with it

I use `Symbol` in a js file from 6 months ago , Today react-native told me 

> Can’t find variable: Symbol

Cannot find what?! Why you could find it yesterday?!

After hours of hard working and searching, I found that my codes works on iOS , but don't works in my and other machine (So there is no cache issue) that `run-android` 

Suddenly I see https://medium.com/@jordan_mohi/cant-find-variable-symbol-in-react-native-782489d86bd7

OH!!! MY GOD!!!!! `Debug JS Remotely` !!! 😡

See also https://github.com/facebook/react-native/issues/15497 (I don't know why no body care it)

I open dev menu and press `Debug JS Remotly` , my code works 

> React Can find Symbol 😮 😲 😵 😳

**Comment by radko93** [comment]
@facebook-github-bot no-template

**Comment by sm2017** [comment]
💩💩💩💩💩💩💩

https://github.com/facebook/react-native/issues/15497 has template

**Comment by sm2017** [comment]
I open https://github.com/facebook/react-native/issues/15805

**Comment by rottenoats** [comment]
Was getting the same error when using mobx for android.

Solution:
https://github.com/react-community/jsc-android-buildscripts#how-to-use-it-with-my-react-native-app

**Comment by Tai13492** [comment]
You should try 
npm install --save es6-symbol
Then,
import 'es6-symbol/implement'; 
At the starting point of your project (App.js/index.js).
This will solve your problem but it may lead you to another problem if you are using mobx in your project. 
The way to solve it is to downgrade your mobx version to 4.x.x (mobx version >= 5 will crash)
Hope this helps.

**Comment by badarshahzad** [comment]
Does their exist any other solution?

**Comment by newyankeecodeshop** [comment]
Using the upgraded `jsc-android` is your bet because it has the same runtime support as iOS 10+. You'll get a more consistent runtime experience.

**Comment by badarshahzad** [comment]
Where this could be find?

**Comment by newyankeecodeshop** [comment]
@badarshahzad Instructions are here: https://github.com/react-community/jsc-android-buildscripts#how-to-use-it-with-my-react-native-app
If you don't want to bump the `minSdkVersion` to 21 for that version of JSC (it includes 64-bit support), then you can use `jsc-android@216113.0.3`. We've been using that version in two production apps targeting Android 17+ and it has been flawless.

**Comment by badarshahzad** [comment]
Thank you to suggest this one but I face this error when I used MobX instead of Redux. I am junior so kindly enlighten me what to do now.
