### ISSUE TITLE
Flatlist flow error 

### ISSUE THREAD

**Issue by zhuyifan2013** [facebook/react-native#15799]
React-Native version : 0.47
Flow version : 0.53.1

The Flow shows an error about Flatlist : 

And I look into the FlatList source code , this error also exists below VirtualList 

> file: 'file:///Users/rockvr/Documents/VRPlayer/react-native/js/recommend/RecommendMoreVideo.js'
severity: 'Error'
message: 'exact type: object type (This type is incompatible with union: undefined | null | boolean | number | string | type application of type `React$Element` | type application of identifier `Iterable` See also: React element `FlatList` Member 1: Error: inconsistent use of library definitions object type This type is incompatible with Member 2: Error: inconsistent use of library definitions object type This type is incompatible with Member 3: boolean Error: inconsistent use of library definitions object type This type is incompatible with boolean Member 4: number Error: inconsistent use of library definitions object type This type is incompatible with number Member 5: string Error: inconsistent use of library definitions object type This type is incompatible with string Member 6: type application of type `React$Element` Error: type application of property `PureComponent` Too many type arguments. Expected at most 2 See type parameters of definition here Member 7: type application of identifier `Iterable` Error: inconsistent use of library definitions property `@@iterator` of $Iterable Property not found in object type)'
at: '49,9'
source: 'flow'

**Comment by radko93** [comment]
Please use the same flow version that your react native installation uses for best effects.

**Comment by radko93** [comment]
@facebook-github-bot no-template
