### ISSUE TITLE
Can't run app

### ISSUE THREAD

**Issue by leoaccorsi** [facebook/react-native#15797]
`react-native: 0.46.4`

I'm getting this error's only on android:

`FATAL EXCEPTION: mqt_native_modules
                  Process: br.com.MYPACKAGE, PID: 2964
                  com.facebook.react.common.JavascriptException: No dimension set for key window`

I've searched that it happens using Router Flux, but i don't use it.

Any help?

**Comment by iegik** [comment]
Duplicate of https://github.com/facebook/react-native/issues/13758

**Comment by chirag04** [comment]
@facebook-github-bot duplicate #13758
