### ISSUE TITLE
[CameraRoll] Please switch from Assets Library Framework to Photos framework

### ISSUE THREAD

**Issue by bparadie** [facebook/react-native#1579]
#### PROBLEM
The current implementation of CameraRoll support uses Assets Library Framework, i.e.  [ALAssetRepresentation](https://developer.apple.com/library/prerelease/ios/documentation/AssetsLibrary/Reference/ALAssetRepresentation_Class/index.html).

The Apple documentation notes that Assets Library Framework will be deprecated in iOS 9 and recommends using the Photos framework instead, see [ALAssetRepresentation](https://developer.apple.com/library/prerelease/ios/documentation/AssetsLibrary/Reference/ALAssetRepresentation_Class/index.html) documentation:

> IMPORTANT
> 
> The Assets Library framework is deprecated as of iOS 9.0. Instead, use the Photos framework instead, which in iOS 8.0 and later provides more features and better performance for working with a user’s photo library. For more information, see Photos Framework Reference.
> 

#### RELATED ISSUES

- Slow rendering of CameraRoll images since 0.4.0, https://github.com/facebook/react-native/issues/930
- Make ALAsset representation and orientation configurable, https://github.com/facebook/react-native/issues/1567

**Comment by browniefed** [comment]
@brentvatne I believe this has been fixed with the Orientation bug fixes in .11

**Comment by gran33** [comment]
Hi, 
Anything new with this?

`RCTCameraRollManager` and `RCTAssetsLibraryRequestHandler` are still implemented in the deprecated `AssetLibrary` framework.

Does is `community responsibility` as well?

10x in advance.

**Comment by olofd** [comment]
I'm working on a library called [react-native-photos-framework](https://github.com/olofd/react-native-photos-framework) that can access assets from local camera-roll and iCloud using Apples Photos-framework. Its starting to take form and will be able to do most things you can do with Apples native API's. This includes: Loading images from iCloud (Custom RN-Image-Loader), Loading albums and collections from iCloud, Creating Albums, Deleting and saving assets in albums etc. 

I'm also implementing more low-lever features such as change-detection in asset-collections. And caching for large number of assets. Check it out if your interested.

**Comment by DVassilev** [comment]
@browniefed as @gran33 mentioned, it seems to still use `AssetLibrary`. Any plans for this to be changed?
