### ISSUE TITLE
[Android] Wrong gradle-wrapper.jar 

### ISSUE THREAD

**Issue by iegik** [facebook/react-native#15790]
### Is this a bug report?

maybe

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

yes
### Environment

react-native-cli: 2.0.1
react-native: 0.48.1
node -v v8.4.0
npm -v 5.3.0

Android 7+ Nexus 5x 5.2" on Emulator
distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-bin.zip

Then, specify:

- Target Platform:

- Development Operating System:

- Build tools:

### Steps to Reproduce

1. react-native-git-upgrade 0.48.1
2. cd android && ./gradlew clean && cd ..
3.

### Expected Behavior

No gradle wrapper changes

### Actual Behavior

android/gradle/wrapper/gradle-wrapper.jar file was changed and build filed with:
```
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
```

### Reproducible Demo

https://stackoverflow.com/questions/29805622/could-not-find-or-load-main-class-org-gradle-wrapper-gradlewrappermain

**Comment by 3DEsprit** [comment]
Found this issue when upgrading to 0.46.1 from 0.46.0 with the git-upgrade. During this process the gradle-wrapper jar file was replaced. Is this version specific, or something quark in git-upgrade?
