### ISSUE TITLE
Content-Type does not respect optional charset encoding for iOS RCTJavascriptLoader

### ISSUE THREAD

**Issue by justinr1234** [facebook/react-native#15791]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

1. `react-native -v`: 0.42.0
2. `node -v`: v6.11.2
3. `npm -v`: 4.6.1
4. `yarn --version`: 0.27.5

- Target Platform: iOS
- Development Operating System: macOS
- Build tools: XCode

### Steps to Reproduce

1. Try to run a react native app and download a bundle from a server which returns a `Content-Type` header that includes both the MIME Type and an optional character encoding as specified here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type
2. The React Native code for iOS will fail on this line of code as it strictly checks the `Content-Type` header as if the optional character encoding doesn't exist: https://github.com/facebook/react-native/blame/master/React/Base/RCTJavaScriptLoader.mm#L277

### Expected Behavior

The code should follow the specification of `Content-Type` and respect only MIMEType checking instead of strictly checking the `Content-Type` header for an exact match on MIMEType.

Per Apple documentation, `NSURLResponse` contains the `MIMEType` field that should be checked for `application/javascript` instead of checking the raw `Content-Type` header: https://developer.apple.com/documentation/foundation/nsurlresponse

### Actual Behavior

Though this was encountered while using Expo, the error is nonetheless coming from the `RCTJavaScriptLoader`

<img width="384" alt="screen shot 2017-09-04 at 7 52 51 am" src="https://user-images.githubusercontent.com/7017500/30034896-19385ff6-916a-11e7-9a80-d171adf17717.png">

Expected JavaScript, but got content type 'application/javascript; chartset=UTF-8'. Check that your internet connection is working.

### Reproducible Demo

https://github.com/sysgears/apollo-universal-starter-kit

Follow starter instructions and checkout this commit: https://github.com/sysgears/apollo-universal-starter-kit/commit/bbcd52a934e24b4ce873e802d085af2b8fe04ec2

The problem is worked around after this commit in the project.

**Comment by joearasin** [comment]
I just tripped over this when attempting to get Haul to make a build for react-native 0.48.2: https://github.com/callstack-io/haul/issues/228

**Comment by dikaiosune** [comment]
cc'ing @janicduplessis as he was cc'd on an Expo bug report.

**Comment by grabbou** [comment]
Up @janicduplessis, there are some commits in the history of this issue. Is any of them ready for merging? If yes, I can go ahead and cherry-pick into respective branches.

**Comment by janicduplessis** [comment]
The PR has not been merged yet https://github.com/facebook/react-native/pull/15792, let's cherry pick it once it is.

**Comment by justinr1234** [comment]
@janicduplessis did this end up getting merged somewhere?
