### ISSUE TITLE
Vertical margin in percentage is calculated with screen width instead of height

### ISSUE THREAD

**Issue by IanMcmillan** [facebook/react-native#15798]
A simplified use case - trying to draw a square with its top placed at the very bottom of the screen (`y = [screen height]`):

    render() {
      return (
        <View style={{flex: 1}}>
          <View style={{
              backgroundColor: "red",
              width: 20,
              height: 20,
              top: 0,
              marginTop: "100%",
           }} />
        </View>
      );
    }

The square is instead placed at `y = [screen width]`

![tmplayout_bug](https://user-images.githubusercontent.com/11072689/30038639-9c779c64-91cf-11e7-98d9-929a4068ce96.png)

(I need this ability for trickier use cases, e.g. placing a shape with height=[30% screen height], with its middle at [20% screen height], etc.)

The problem occurs in both iOS and Android
react-native: 0.46.4
node: v7.10.0
yarn: v0.24.5
Using OS X El Capitan 10.11.6

**Comment by ylarom** [comment]
+1

**Comment by harunurhan** [comment]
This is how it works on the major browsers too. You can read it https://www.w3.org/TR/CSS21/box.html#margin-properties

**Comment by ylarom** [comment]
Looks like you're absolutely right.
Thanks!
(Though I still think this is still f*ed up...)
