### ISSUE TITLE
Expo crashes when using adjustsFontSizeToFit on Text

### ISSUE THREAD

**Issue by Li357** [facebook/react-native#15803]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

1. `react-native -v`: 0.47.2, CLI: 2.0.1
2. `node -v`: 8.2.1
3. `npm -v`: 4.6.1
4. `yarn --version`: 0.27.5

Then, specify:

- Target Platform: iOS

- Development Operating System: macOS El Capitan, 10.11.6

- Build tools: Using CRNA, related to iOS

### Steps to Reproduce

(Write your steps here:)

1. Apply `adjustsFontSizeToFit` to a `Text` component
2. Apply a `fontFamily` rule to the `Text` component

### Expected Behavior

I expected the prop to automatically scale my text down into one line. So instead of this:

![screen shot 2017-09-04 at 9 52 26 pm](https://user-images.githubusercontent.com/12980971/30043091-2afb080a-91bb-11e7-9508-957b07e9811c.png)

I would expect to get this:

![screen shot 2017-09-04 at 9 53 51 pm](https://user-images.githubusercontent.com/12980971/30043132-5079dd72-91bb-11e7-9e6b-fada79fe113b.png)

As the text is automatically scaled down to fit the width.

### Actual Behavior

The app failed to load, and Expo crashed with seemingly zero reasons. There are no errors in the console. This seems to only happen with custom loaded fonts, with `Expo.Font`.

### Reproducible Demo

Since I can't upload custom fonts to a Snack, here's a minimal example:

    <View>
      {
        fontsLoaded &&
          <Text
            adjustsFontSizeToFit
            style={{ fontFamily: 'RobotoThin' }}
          >
            Hello!
          </Text>
      }
    </View>

Here, `fontsLoaded` is just a variable in state that indicates if all fonts are loaded:

    async componentDidMount() {
      await Font.loadAsync({
        RobotoThin
      });
      this.setState({
        fontsLoaded: true
      });
    }

All the fonts are loading correctly, and I removed styling until I isolated the cause, which was the `fontFamily` rule. Whenever a non-builtin font family is applied to a `Text` component that has `adjustsFontSizeToFit`, Expo crashes.

**Comment by cyprusglobe** [comment]
@Li357 i think this issues would be better suited for either https://github.com/expo/expo or https://github.com/expo/expo-sdk

**Comment by nikki93** [comment]
Tracking this at https://github.com/facebook/react-native/issues/15803.

**Comment by cohendl** [comment]
I see this was closed, but has it been resolved? I am still getting this crash.

**Comment by wli** [comment]
@nikki93 i think you just linked back to this issue. is there a place where we can track progress on this? Just ran into this today on SDK22.

**Comment by terribleben** [comment]
Hi, I added an expo/expo issue to track this. Thanks for mentioning again.

**Comment by brentvatne** [comment]
fixed in sdk23, releasing soon
