### ISSUE TITLE
undefined is not an object (evaluating 'CameraManager.Aspect') - From NativeModules

### ISSUE THREAD

**Issue by javaherian** [facebook/react-native#15809]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

1. `react-native -v`: react-native: 0.48.1
2. `node -v`: v7.10.0
3. `npm -v`: 3.10.10
4. `yarn --version`:

Then, specify:

- Target Platform: Android

- Development Operating System: Ubuntu 17.04

- Build tools: Android Studio

### Steps to Reproduce

1. Try to run the following minimal code:
```
import { NativeModules } from 'react-native';

const CameraManager = NativeModules.CameraManager || NativeModules.CameraModule;

CameraManager.Aspect;
```

### Expected Behavior

You would expect NativeModules to export a `CameraManager` object

### Actual Behavior

It returns `undefined`

### Reproducible Demo

https://snack.expo.io/BJJlfZhYZ

Run the above and scan the code from any Android device to see it fail.

Some related information here - https://github.com/lwansbrough/react-native-camera/issues/748#issuecomment-312493527

**Comment by ferminmoli** [comment]
Same Issue here.

**Comment by ferminmoli** [comment]
I've just verified my project with last version of RN. Camera module is still not loading all the functionality. In the following image you can see that CameraModule does not have Aspect for instance. So, once I load the application the line CameraModule.Aspect.Fill breaks.

![image](https://user-images.githubusercontent.com/10004370/30077268-ae13b610-9251-11e7-8d37-465cf5eec392.png)

**Comment by javaherian** [comment]
We have figured out this issue. From what I can see, it's related to using `create-react-native-app`. 

Steps to solve:
1) Start a new react native project with `react init` NOT with `create-react-native-app`
2) Copy over your source files and refactor to make them build
3) It should be working now

Note that simply ejecting your app did not work for us. Hope this helps someone.

**Comment by javaherian** [comment]
Closing this since it seems to be a `create-react-native-app` issue.

**Comment by ferminmoli** [comment]
It's not working for me. I've started the App using react-native init so this solution does not solve the issue for me. Is there anothere alternative? I've been stuck since last week and my app is not working properly.

**Comment by Anatoliy24** [comment]
Hi! Did you resolve this problems?

**Comment by pavanmehta91** [comment]
I've still getting the same error CameraManager seems to initialise first but later when extracting defaultProps it says undefined.
Any leads on that?

**Comment by natefoundry** [comment]
I have a similar issue with `NativeModules` being `undefined` but with the `MapView` component.

The map view loads the map, but when I attempt to call `takeSnapshot()` then I get a similar error. It seems that `NativeModules` isn't defined? 

I created my app using `create-react-native-app` and copied one of the MapView example apps for taking snapshots of the map. 

Works OK on iOS, just not android. 

I am using the native emulator (Nexus 5 API level 25) for testing the expo app.

**Comment by jaydenmaddison** [comment]
After linking the libraries, run 'pod install' in the ios directory. This solved it for me.

**Comment by Jakerevans** [comment]
Any Android solution?

**Comment by NirmalsinhRathod** [comment]
Its working fine in iPhone. Android is having same issue. Please share solution if anyone have it.

**Comment by export-mike** [comment]
@NirmalsinhRathod any luck same issue here.
