### ISSUE TITLE
Tests failing on a newly created app

### ISSUE THREAD

**Issue by cschroeter** [facebook/react-native#15810]
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

yes

### Environment

react-native-cli: 2.0.1
react-native: 0.48.1
node: v8.4.0
yarn: 0.27.5

- Target Platform: 
iOs, Android

- Development Operating System:
macOs Sierra 10.12.6

### Steps to Reproduce

1. react-native init testapp
2. cd testapp
3. yarn test

### Expected Behavior

Initially created tests should pass.

### Actual Behavior

```
yarn test
yarn test v0.27.5
$ jest
 FAIL  __tests__/index.android.js
  ● Test suite failed to run

    TypeError: Cannot read property 'BLOB_URI_SCHEME' of undefined

      at Object.<anonymous> (node_modules/react-native/Libraries/Blob/URL.js:21:21)
      at node_modules/react-native/Libraries/Core/InitializeCore.js:174:40
      at getValue (node_modules/react-native/Libraries/Utilities/defineLazyObjectProperty.js:44:10)
      at ContextifyScript.Script.runInContext (vm.js:53:29)

 FAIL  __tests__/index.ios.js
  ● Test suite failed to run

    TypeError: Cannot read property 'BLOB_URI_SCHEME' of undefined

      at Object.<anonymous> (node_modules/react-native/Libraries/Blob/URL.js:21:21)
      at node_modules/react-native/Libraries/Core/InitializeCore.js:174:40
      at getValue (node_modules/react-native/Libraries/Utilities/defineLazyObjectProperty.js:44:10)
      at ContextifyScript.Script.runInContext (vm.js:53:29)

Test Suites: 2 failed, 2 total
Tests:       0 total
Snapshots:   0 total
Time:        0.95s
Ran all test suites.
error Command failed with exit code 1.
```

**Comment by shaundon** [comment]
I dropped back to version `0.47.x` and this no longer happens - have you tried that?

**Comment by cschroeter** [comment]
@shaundon I've just have migrated to the latest version. Tests passed on ```0.47.1```

**Comment by edraitsev** [comment]
Also this issue reproducible on node `8.4.0`, but all works fine with node `7.4.0`. You can use it how temporary workaround

**Comment by sir-gon** [comment]
I have the same tool versions in my stack and can confirm the issue :/

**Comment by timwangdev** [comment]
I created PR in #15843 to fix this issue.

**Comment by richardgirges** [comment]
Here are some temp workarounds that don't involve downgrading Node, until a release is cut with @timwangdev's fix.

**WORKAROUND 1 (thanks to @timwangdev's PR):**
Overwrite `./node_modules/react-native/jest/setup.js` with this: https://raw.githubusercontent.com/facebook/react-native/master/jest/setup.js

**WORKAROUND 2:**
WARNING: Risky! I didn't actually test this.

Install RN #master git branch:
```
"react-native": "git://github.com/facebook/react-native#master"
```

**Comment by timwangdev** [comment]
Another workaround does not involve change current RN files (I'm using) is:

Add https://github.com/facebook/react-native/blob/master/jest/setup.js#L112-L307 to your own project's jest-setup.js. This one will actually rewrite the mock for whole `NativeModules`.

You could remove those lines after the fix releases.

**Comment by Ashoat** [comment]
For anybody still experiencing this issue, note that it is fixed in 0.48.4. It can be closed now.

**Comment by timwangdev** [comment]
@facebook-github-bot close

**Comment by rsp8055** [comment]
> MyDemo@0.0.1 test /home/MyDemo
> jest

 FAIL  __tests__/App.js
  ● Test suite failed to run

    TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string

      at assertPath (path.js:28:11)
      at Object.relative (path.js:1249:5)

 FAIL  __tests__/App-test.js
  ● Test suite failed to run

    TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string

      at assertPath (path.js:28:11)
      at Object.relative (path.js:1249:5)

Test Suites: 2 failed, 2 total
Tests:       0 total
Snapshots:   0 total
Time:        0.47s
Ran all test suites.
npm ERR! Test failed.  See above for more details



tried by various ways but could not found exact solution, even dont know the exact problem.
