### ISSUE TITLE
Method Websocket.send(string) is inconsistent in case of Null-terminated string (0x00)

### ISSUE THREAD

**Issue by Max-Pudov** [facebook/react-native#15815]
Let's say I send a message from client: 
`let websocket = new WebSocket("ws://echo.websocket.org/");`
`websocket.onopen = evt => { websocket.send("test\u0000test"); }`
`websocket.onmessage = evt => { console.log('RESPONSE: ' + evt.data); };`

Console:
ios: `test\u0000test`
android: `test`

**Comment by radko93** [comment]
@facebook-github-bot no-template
