### ISSUE TITLE
[NavigatorIOS] Why NavigatorIOS overlaps upper part of inner component?

### ISSUE THREAD

**Issue by aksonov** [facebook/react-native#1581]
I've just generated empty React-Native project (using react-native init) and added sample NavigatorIOS code. 
```javascript
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 */
'use strict';

var React = require('react-native');
var {
  AppRegistry,
  StyleSheet,
  Text,
  NavigatorIOS,
  View,
} = React;

var TestProject = React.createClass({
  render: function() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit index.ios.js
        </Text>
        <Text style={styles.instructions}>
          Press Cmd+R to reload,{'\n'}
          Cmd+D or shake for dev menu
        </Text>
      </View>
    );
  }
});

var Test = React.createClass( {
  render() {
    return (
      <NavigatorIOS
        style={{flex:1}}
        initialRoute={{
          title: 'Preference',
          component: TestProject
        }}
        />
    );
  }
});

var styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

AppRegistry.registerComponent('TestProject', () => Test);

```
![ios simulator screen shot 10 2015 15 33 19](https://cloud.githubusercontent.com/assets/1321329/8083626/4a02eff6-0f86-11e5-9264-245919e42754.png)

**Comment by marcshilling** [comment]
This is default iOS behavior since iOS 7 when they made the Navigation Bar translucent. Content is supposed to be able to visually scroll beneath the nav bar. 

Anyway, if you don't need that functionality, just set `paddingTop: 64` on your container style which will start everything beneath the nav bar.

**Comment by aksonov** [comment]
Thanks! Looks like translucent property is not in 0.5.0 yet and it is NOT on by default, so it looks a little bit confusing .

**Comment by marcshilling** [comment]
It should be on by default. Make a ScrollView with some colored views in it and scroll it up - you should see the colors bleed through a little bit.

**Comment by aksonov** [comment]
Strange, in my example I don't see symbols ("Welcome to React Native!...") from underlying view under "Preference" nav bar or it just should show background color, not text?

**Comment by browniefed** [comment]
@aksonov is this still an issue? NavigatorIOS is a community supported component so you may be better off with Navigator. 
That being said the `translucent` is now a property on NavigatorIOS so does that solve your issue mentioned in the comment above?

@brentvatne ?

**Comment by brentvatne** [comment]
Looks like this is working as expected, @aksonov if you can post an example of this in action I can look at it for you! Otherwise, closing

**Comment by aksonov** [comment]
Thanks, I've switched to Navigator component.

**Comment by DanielApt** [comment]
Just adding to this thread, for anyone googling this issue.

Add `itemWrapperStyle={styles.navItem}` as an attribute to `NavigatorIOS`

and then add a stylesheet:

```js
const styles = Stylesheet.create({
    navItem: {
        paddingTop: 64
    }
});
```

**Comment by ericcastro92** [comment]
FYI: For those coming across this issue, a more stable solution than setting paddingTop: 64 is turning off the translucent property.

```
<NavigatorIOS
   translucent={false}
   initialRoute={{
      ...
   }}/>
```

**Comment by dphans** [comment]
@marcshilling I think set style `paddingTop: 64` is not solve the problem. Because if screen change orientation to landscape, the scene will display not good, because in new state, UINavigationBar height is smaller than 64.
