### ISSUE TITLE
Sidebar in docs not showing on Firefox 55 for < 1440px screens

### ISSUE THREAD

**Issue by kanyuga** [facebook/react-native#15816]
### Is this a bug report?

Yes. In docs.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

yes

### Environment

1. `react-native -v`: all
2. `node -v`: n/a
3. `npm -v`: n/a
4. `yarn --version`: n/a

Then, specify:

- Target Platform: n/a

- Development Operating System: macOS

- Build tools: n/a

### Steps to Reproduce

(Write your steps here:)

1. Load the react-native docs on Firefox 55 on Mac.

### Expected Behavior

Sidebar should show: 
<img width="1440" alt="screen shot 2017-09-04 at 17 27 48" src="https://user-images.githubusercontent.com/1700080/30074074-beb0f77c-9278-11e7-9e29-b3d9a07c7488.png">

### Actual Behavior

Sidebar doesn't show:

<img width="1440" alt="screen shot 2017-09-04 at 17 27 42" src="https://user-images.githubusercontent.com/1700080/30074234-714bcd62-9279-11e7-95d4-74b9ffe7aaf3.png">

### Reproducible Demo

N/A

**Comment by chirag04** [comment]
cc @hramos

**Comment by hramos** [comment]
We're switching to a new website generator, so it's probably not worth fixing this in master right now. I'll keep this in mind and make sure the issue does not reproduce in the new site.
