### ISSUE TITLE
What is the tabNavigator click event? I need to pass a parameter in the item component when I click a picture under tabNavigator. How do I do that?

### ISSUE THREAD

**Issue by wangweifeng66** [facebook/react-native#15811]
### Is this a bug report?

(write your answer here)

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.)

### Environment

1. `react-native -v`:
2. `node -v`:
3. `npm -v`:
4. `yarn --version`:

Then, specify:

- Target Platform:

- Development Operating System:

- Build tools:

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by wangweifeng66** [comment]
I've used react-navigation's TabNavigator, tab pages, A, B, and C, all using StatusBar,
When the A tab is changed, StatusBar does not work because it is covered by the last C tab StatusBar,
How can you separate StatusBar on each tab page?

**Comment by radko93** [comment]
@facebook-github-bot stack-overflow
