### ISSUE TITLE
CameraModule is not loading correctly

### ISSUE THREAD

**Issue by ferminmoli** [facebook/react-native#15814]
react-native -v: 0.45.1
node -v: 6.10.0
npm -v: 5.3.0
Target Platform: Android/Ios
Development Operating System: Windows 10
Build tools: 23

Put the following line on your react-native code, and debug js remotly.

const CameraManager = NativeModules.CameraManager || NativeModules.CameraModule;

- CameraManager is always undefined
- Sometimes CameraModule is undefined
- When CameraModule is not undefined it does not have all the needed functionality, for example, aspect()

**Comment by radko93** [comment]
Can you please verify this on the latest version? We don't support old versions.

**Comment by radko93** [comment]
@facebook-github-bot duplicate #15809

**Comment by ferminmoli** [comment]
I've just verified my project with last version of RN. Camera module is still not loading all the functionality. In the following image you can see that CameraModule does not have Aspect for instance. So, once I load the application the line _CameraModule.Aspect.Fill_ breaks.

![image](https://user-images.githubusercontent.com/10004370/30077162-594aaada-9251-11e7-8eb3-bc3b7b89f75f.png)
