### ISSUE TITLE
Position absolute view is not covering `<Button>`

### ISSUE THREAD

**Issue by Noitidart** [facebook/react-native#15823]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

1. `react-native -v`: 0.47.1 and 0.48.1
2. `node -v`: v.7.5.0
3. `npm -v`: 5.3.0
4. `yarn --version`: N/A

Then, specify:

- Target Platform: Android

- Development Operating System: Windows 10

- Build tools: N/A

### Steps to Reproduce

(Write your steps here:)

1. Code:
```
import React, { Component } from 'react';
import { AppRegistry, View, StyleSheet, Text, ActivityIndicator, Button } from 'react-native';

export default class App extends Component {
  render() {
    return (
        <View style={styles.wrap}>
                <Button title='Enabled' onPress={this.handleSubmit} />
                <Text>{'\n'}</Text>
                <Text>{'\n'}</Text>
                <Text>{'\n'}</Text>
                <Text>{'\n'}</Text>
                <Button title='Disabled' onPress={this.handleSubmit} disabled />
                <View style={styles.loadingWrap}>
                    <ActivityIndicator color="deepskyblue" size={50} />
                </View>
        </View>
    )
  }

  handleSubmit = () => alert('hi')
}

const styles = StyleSheet.create({
    wrap: {
        flex: 1,
        width: '100%',
        justifyContent: 'center'
    },
    loadingWrap: {
        position: 'absolute',
        height: '100%',
        width: '100%',
        backgroundColor: 'rgba(0, 0, 0, 0.8)',
        justifyContent: 'center'
    }
})

AppRegistry.registerComponent('interactable', () => App)
```

### Expected Behavior

I thought the `<View>` would cover the `<Button>` becuase it comes after the button in the hierarchy.

### Actual Behavior

View is not covering Button.

### Reproducible Demo

Demo - https://snack.expo.io/BJHX7-15-

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by Noitidart** [comment]
If you set attribute of `disabled` on the `<Button>` then it does get covered. Funky.

**Comment by hramos** [comment]
0.48 is the newest version, can you try with the latest release and update your issue accordingly if it repros?

**Comment by Noitidart** [comment]
@hramos - thanks very much for the follow up. I tested with 0.48.1 and same thing.


I updated with a snack demo in original post that shows the bug, but I think expo doesnt use 0.48.1

**Comment by Noitidart** [comment]
It can be sort of "worked around" with setting `elevation: 20` on view style `loadingWrap` but this creates an undesired shadow. Trying `zIndex: 20` does not work.

**Comment by Noitidart** [comment]
If it's not affecting a lot of people should we close it out? Or file it for later?

**Comment by JLLLinn** [comment]
Mine is a Text with absolute position and the onPress does not work. I'm running the latest 0.51 react

**Comment by Noitidart** [comment]
It seems you can't cover `elevation`. I can't figure out how exactly. But sometimes if you add an element positioned absolutely in the target.parent.parent then it will cover it (it has to be outside of the component that renders the thing you have to cover, it can't be inside). It is way weird.

**Comment by Saraceni** [comment]
I have a view with absolute position which is drawn behind another view in the bottom of my screen only in Android. But in iOS it works fine.

**Comment by Noitidart** [comment]
@Saraceni move it to the parent component until it it covers. It's most likely the elevation issue I encountered.

**Comment by Lucastrike** [comment]
@Noitidart  I'm working in a similar mockup that needs to have an absolute View over two different View containers.

**The problem:** An absolute component does not mean that is over the other ones.
**The solution:** Just give a `zIndex: 1` to the same element you made absolute, now the button or even touchable elements will working.

Hope it helps anyone having this problem!

**Comment by Noitidart** [comment]
Thanks at @Lucastrike ! I also found `<ScrollView>` will overlap it too. Its interesting.

**Comment by KumariShalini** [comment]
i am also facing the problem with overlapping of one view on other view, onpress is not working in android in react native... can anyone give some solution please? thank you.
