### ISSUE TITLE
React native Unit testing

### ISSUE THREAD

**Issue by NawazKhanMd** [facebook/react-native#15829]
HI all 
This is not a issue but information sharing kindof thing 

I have a basic class which extends react native component

 _export default class testProject extends Component {
_sum(a, b) {
    return a + b;
  }
  render() {
    return (<View>
<Text>Business Finance</Text>
      </View>
    );
  }
}_

How can I write unit tests for both UI and Business logic :)

**Comment by dbyilmaz** [comment]
You can read this articles then you can write test :) 

https://facebook.github.io/jest/docs/en/getting-started.html

https://blog.callstack.io/unit-testing-react-native-with-the-new-jest-i-snapshots-come-into-play-68ba19b1b9fe

https://blog.callstack.io/unit-testing-react-native-with-the-new-jest-ii-redux-snapshots-for-your-actions-and-reducers-8559f6f8050b

https://medium.com/@romarioraff/testing-react-apps-with-jest-and-chai-enzyme-for-beginners-baa5f57cec0b

https://medium.com/@dschmidt1992/jest-snapshot-testing-3ef9fa1222bb

**Comment by chirag04** [comment]
@facebook-github-bot answered

**Comment by NawazKhanMd** [comment]
after a day of reading documents a stright answer for the question

For UI -> Enzyme and Jest example :->

    import Index from '../index.android.js';
    const expectedText = 'Business Finance';
    let wrapper=shallow(<Index />);
    expect(wrapper.find('Text').children().text()).toEqual(expectedText);
For Businesslogic testing ->Enzyme

expect(wrapper.instance()._sum(2,3)).toBe(5);
