### ISSUE TITLE
undefined is not an object (evaluating '_reactNativeCodePush2.default.sync')

### ISSUE THREAD

**Issue by aditya-simplecrm** [facebook/react-native#15828]
After Installing this library, I am getting this error 

`arning: PropTypes has been moved to a separate package. Accessing React.PropTypes is no longer supported and will be removed completely in React 16. Use the prop-types package on npm instead. (https://fb.me/migrating-from-react-proptypes)
09-06 15:24:48.223 11231 12471 W ReactNativeJS: Warning: React.createClass is no longer supported. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement. (https://fb.me/migrating-from-react-create-class)
09-06 15:24:48.653 11231 12471 I ReactNativeJS: [CodePush] The CodePush module doesn't appear to be properly installed. Please double-check that everything is setup correctly.
09-06 15:24:48.823 11231 12471 I ReactNativeJS: Running application "NagpurIsAwesome" with appParams: {"rootTag":1}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
09-06 15:24:49.273 11231 12471 E ReactNativeJS: undefined is not an object (evaluating '_reactNativeCodePush2.default.sync')`

react-native: 0.45.1

MainApplication.java
`package com.nagpurisawesome;

import android.app.Application;

import com.facebook.react.ReactApplication;
import com.facebook.reactnative.androidsdk.FBSDKPackage;
import com.microsoft.codepush.react.CodePush;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;

import com.facebook.CallbackManager;
import com.facebook.FacebookSdk;
import com.facebook.reactnative.androidsdk.FBSDKPackage;
import com.facebook.appevents.AppEventsLogger;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private static CallbackManager mCallbackManager = CallbackManager.Factory.create();

  protected static CallbackManager getCallbackManager() {
    return mCallbackManager;
  }
  
  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {

    @Override
    protected String getJSBundleFile() {
      return CodePush.getJSBundleFile();
    }

      @Override
      public boolean getUseDeveloperSupport() {
        return BuildConfig.DEBUG;
      }

      @Override
      protected List<ReactPackage> getPackages() {
        return Arrays.<ReactPackage>asList(
            new MainReactPackage(),
            new FBSDKPackage(mCallbackManager)
        );
      }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    FacebookSdk.sdkInitialize(getApplicationContext());
    // If you want to use AppEventsLogger to log events.
    AppEventsLogger.activateApp(this);
  }

}
`

**Comment by chirag04** [comment]
@aditya-simplecrm please reopen this issue on code-push github issue tracker.
