### ISSUE TITLE
Error running new AppleTV project

### ISSUE THREAD

**Issue by dabit3** [facebook/react-native#15834]
### Is this a bug report?

(yes)

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(yes)

### Environment

1. `react-native -v`: 0.48.1 (edit by @hramos)
2. `node -v`: v6.9.1
3. `npm -v`: 3.10.8
4. `yarn --version`: 0.24.6

Then, specify:

- Target Platform:

AppleTV

- Development Operating System:

MacOS Sierra 10.12.6

- Build tools:

Xcode 9.0 beta6

### Steps to Reproduce

(Write your steps here:)

1. create new react native project using react-native init
2. run tvOS as target

### Expected Behavior

(Simulator opens)

### Actual Behavior

Error: `ld: library not found for -lReact-tvOS
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

<img width="862" alt="screen shot 2017-09-06 at 2 38 40 pm" src="https://user-images.githubusercontent.com/1857282/30112296-20bbf7c6-9311-11e7-9312-46ed90660431.png">

### Reproducible Demo

https://www.dropbox.com/s/cyg71ggmvunficw/zip.zip?dl=0

To reproduce:

1. run in Xcode

**Comment by dabit3** [comment]
Update: By creating a project using an older version of React Native the error seems to go away. eg: `react-native init --version="0.47.2"`

**Comment by hramos** [comment]
Which version does this repro in? 2.0.1 above is the CLI version.

**Comment by dabit3** [comment]
It looks like I'm running version 2.0.1.

**Comment by hramos** [comment]
That is the CLI version. The RN version should be something like 0.48 or 0.47.1.

**Comment by dabit3** [comment]
Ah, this repros in version `0.48.1`

**Comment by ntodd** [comment]
I see the exact same behavior in RN 0.49.3.  Creating project with 0.47.2 worked.

**Comment by abdelilah** [comment]
Same error here, created a brand new project using RN 0.49.3. iOS works fine though.

**Comment by dlowder-salesforce** [comment]
I'll take a look and see what's going on.

**Comment by dlowder-salesforce** [comment]
@dabit3 this is now fixed as of PR #16076 .  Please verify and close.

**Comment by cantyjeffrey** [comment]
@dlowder-salesforce Having the same issue with brand new RN project scaffolded using `0.50.4` — Running `react-native init --version="0.47.2"` works fine. Any ideas on which newer versions are capable of running on tvOS?

**Comment by tsaiDavid** [comment]
@dlowder-salesforce 

Same issue as @cantyjeffrey - specifying an older version of RN allowed the tvOS app to build properly

**Comment by cantyjeffrey** [comment]
Damn, I was hoping I was missing something obvious, @tsaiDavid — well anyway, let me know if there’s any useful info or debugging output I could provide you with to help squash this, @dlowder-salesforce 👍

**Comment by dabit3** [comment]
@dlowder-salesforce @tsaiDavid @cantyjeffrey Yes I also tested it out a few days ago and could not get it to build, but was debugging to make sure I did not do anything wrong, but as of 0.50.4 I was unable to have any luck.

**Comment by dlowder-salesforce** [comment]
@dabit3 @tsaiDavid @cantyjeffrey I just did

`react-native init TestApp --version facebook/react-native#master`

and the tvOS target compiles and runs.  So I'm guessing that the fix in #16076 just hasn't made it into any releases yet.  @grabbou @hramos do you know when that fix will show up in the release train?

**Comment by grabbou** [comment]
Generally a month from hitting master :) 

This particular commit (https://github.com/facebook/react-native/commit/45185947ee5f1672fb00765a8b32a7100fd0c1bd) is part of 0.52.0-rc.0.

**Comment by cantyjeffrey** [comment]
@dlowder-salesforce scaffolding RN from master worked for me, thanks!

**Comment by dlowder-salesforce** [comment]
@hramos we can close this issue
