### ISSUE TITLE
JSON Error

### ISSUE THREAD

**Issue by piyush2468** [facebook/react-native#15833]
![cmderr](https://user-images.githubusercontent.com/18625797/30111869-f6e6bb72-932c-11e7-9d9b-c07bf68d2bd2.png)

### Is this a bug report? 

(No)

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Yes)

### Environment

1. `react-native -v`: 0.47.2
2. `node -v`:
3. `npm -v`:
4. `yarn --version`:

Then, specify:

- Target Platform: Android

- Development Operating System: Windows

- Build tools:
Android Studio
### Steps to Reproduce

(Write your steps here:)

1.Trying to gradlew assemblerelease
2.Going to bundlereleasejsandassets
3.Stuck at it

### Expected Behavior

(It should build up the apk.)

### Actual Behavior

(It's not building the APK and don't say upgrading the version of RN as it's causing more errors. Please provide me solutions.)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by hramos** [comment]
0.48 is the newest version, can you try with the latest release and update your issue accordingly if it repros? Also, make sure to completely fill out the issue template. Thanks!
