### ISSUE TITLE
prevent jumping on refresh

### ISSUE THREAD

**Issue by majd-kho** [facebook/react-native#15835]
This issue has been reported before and closed  but the issue is still persistent on IOS 10.3.3

https://github.com/facebook/react-native/pull/8896

The issue still exists and I am currently experiencing it using ListView and Refresh

- Target Platform: building for both android and ios, but the jumpiness is experienced in ios only.

- Development Operating System: macOS 10.12

- Build tools: Using Expo Client/ Xcode / simulator, the jumpiness exists.

### Steps to Reproduce

1. To test with RN 0.48 and higher, use react-native init  to create a project.
2. Enter  the following code in the index.ios.js file 
```
import React from 'react';
import {AppRegistry,View,Text,ListView,RefreshControl} from 'react-native';

export default class Test extends React.Component {

  constructor() {
     super();
     const ds = new ListView.DataSource({rowHasChanged: (r1, r2) => r1 !== r2});
     this.state = {
       dataSource: ds.cloneWithRows(['row 1', 'row 2', 'row 2', 'row 2', 'row 2', 'row 2']),
       refreshing:false
     };
   }

   refreshListView(){
     this.setState({refreshing: true})
     setTimeout(function(){
        //do something
     },1000)
     this.setState({refreshing: false})
   }

  render() {
    return (
       <View>
          <ListView
          dataSource={this.state.dataSource}
          renderRow={(rowData) => <Text>{rowData}</Text>}
          refreshControl={
            <RefreshControl
              refreshing={this.state.refreshing}
              onRefresh={this.refreshListView.bind(this)}
            />
          }
          />
      </View>
    )
  }
}

AppRegistry.registerComponent("fileName", () => Test);
```

3. launch the app in a simulator or a device and pull slowly to notice the jumpiness

dependencies.
1. `react-native -v`: 0.48.2
2. `node -v`: 0.6.11
3. `npm -v`: 3.10.10
4. `yarn --version` N/A

- Target Platform: IOS 10.3.3

- Development Operating System: Mac OS Sierra

### Expected Behavior
when pulling the list down from the top, the activity indicator should have a smooth cycle to complete and remain at the position where the user drags it to until the user lifts of their finger from the screen.

### Actual Behavior
as the cycle completes, the refresh icon jumps to the top.

 project that reproduces the issue.
  https://snack.expo.io/SJ5QhUE9-

reproduce gif 
![](https://image.ibb.co/ddnYta/drag.gif)

**Comment by hramos** [comment]
Thanks for reporting this issue! Please make sure to fill out the issue template in its entirety, including a full repro. 0.48 is the newest version, can you try with the latest release and update your issue accordingly if it repros?

**Comment by majd-kho** [comment]
@hramos I updated to react 0.48 but we the IOS app is not launching, im getting "scrollView has no prop type for native prop... Updating both should make this error go away" on the expo app and 
"Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in." in the terminal.
once i fix that ill update the issue, thanks!

**Comment by majd-kho** [comment]
@hramos Expo Client app is incompatible with RN 0.48, so is the simulator. Any suggestions on how to test it  for the mean while ? or should I wait for the new update by Expo ?

**Comment by hramos** [comment]
You can try to reproduce it on a new project that uses 0.48, created using `react-native init`.

**Comment by majd-kho** [comment]
@hramos  running it in the simulator and the jumpiness still exists.
using "react-native": "0.48.2"

**Comment by wholcman** [comment]
Any fix ?

**Comment by majd-kho** [comment]
@wholcman , unfortunately I haven't had time to check ever since I
completely filed this issue. Please update if you test it with a newer RN
version.

**Comment by chrismllr** [comment]
I can confirm, I am also seeing this. Versions:
```
"react": "16.0.0-alpha.12",
"react-native": "0.47.2"
```

I recently updated to XCode 9 and have been running on iOS 11 devices.I believe it may be correlated to iOS 11.

**Comment by kumarpatel** [comment]
same. Seeing this on 
```
    "react": "16.0.0-alpha.12",
    "react-native": "0.45.1",
```

**Comment by majd-kho** [comment]
Can someone confirm whether its still persistent in the latest RN version? I will try to test it asap

**Comment by chrismllr** [comment]
Still occurring for me:
```
"react": "16.0.0",
"react-native": "0.50.4",
```

**Comment by wholcman** [comment]
- Add `onScrollBeginDrag, onScrollEndDrag` props to your list
- Delete `this.setState({refreshing: true})` from `onRefresh` fn
- Make your fetch in your `onRefresh` fn
- And do it: 
```
onScrollBeginDrag(e) {
  const { nativeEvent } = e;
  this.timeout && clearTimeout(this.timeout);
  this.props.onScrollBeginDrag && this.props.onScrollBeginDrag(nativeEvent);
}
onScrollEndDrag(e) {
  const { nativeEvent } = e;
  this.timeout && clearTimeout(this.timeout);
  this.timeout = setTimeout(() => {
    this.setState({ refreshing: false });
  }, 600);
  this.props.onScrollEndDrag && this.props.onScrollEndDrag(nativeEvent);
}
```
