### ISSUE TITLE
setState doesn't re-render the source of Image component

### ISSUE THREAD

**Issue by ahmedashraff** [facebook/react-native#15837]
## Issue Description
While I am using RN with `setState` method to change the Image source of map marker based on a user clicking on buttons, The Image doesn't re-render with the new source.

I required the images assets and i assigning the assets to the state while constructing the component. and when the user click one of the buttons in the screen. I change the ` state key ` with the new source expecting re-render the image. But what actually happen is the state change " I making sure that the state change by logging the new state key in the render "
But the image still doesn't change.

## work around
I had to fix that problem anyway, So i decided to use a shitty code to work arround the issue by add a checking method - before the Image component - that's has a Text with a another state value that i change it while i am changing the source. Like that..
Inside the `render` method:
`<View style={{width: 0, height: 0}} > {(this.state.buttonType == 'TypeA') ? <Text>A</Text> : <Text>B</Text> </View>}
<Image source={this.state.ImageSource} />` 

I searched for any thing about Image caching in react native - Android Specifically - But i didn't find anything useful.

So Any information about this issue ?

**Comment by chirag04** [comment]
@facebook-github-bot no-template
