### ISSUE TITLE
Audio in Remote Debuggger

### ISSUE THREAD

**Issue by neuberoliveira** [facebook/react-native#15839]
Not exactly an issue, but makes me wondering why.

Recently i realized that there are a `<audio>` tag in remote debugger, so i was wondering, whats the purpose of it?

![captura de tela 2017-09-06 as 15 45 28](https://user-images.githubusercontent.com/3378304/30129227-aa5c84fa-931b-11e7-97e4-3f69932b9a43.png)

**Comment by chirag04** [comment]
it's intentionally added as a hack to avoid chrome de-prioritizing the tab when the tab is not focused. When de-prioritized you will notice visible delays in execution. Don't worry about the audio, it's not in the human audible range. Going to close this issue. let me know if you need more info.
