### ISSUE TITLE
Shadow offset of elevation increases if used multiple times

### ISSUE THREAD

**Issue by franticBIT** [facebook/react-native#15832]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Partly

### Environment

1. `react-native -v`: react-native-cli: 2.0.1
react-native: 0.47.1
2. `node -v`: v8.4.0
3. `npm -v`: 5.4.0
4. `yarn --version`:

Then, specify:

- Target Platform: Android

- Development Operating System: macOS

- Build tools:

### Steps to Reproduce

(Write your steps here:)

Use same `elevation` in style property of multiple elements.

### Expected Behavior

Every element should have the same shadow.

### Actual Behavior

The shadow offset increases with same `elevation`.
![screenshot_1504700088](https://user-images.githubusercontent.com/7360440/30111789-59144198-930f-11e7-898a-14bd215e3942.png)

### Reproducible Demo

https://snack.expo.io/r1htOvaK-

**Comment by slorber** [comment]
also have this issue... any idea or workaround available?

**Comment by raymondchooi** [comment]
I also have the same issue when elevation is used on items in a list

**Comment by slorber** [comment]
Reopened a new issue as this one got closed while the bug is still there.
https://github.com/facebook/react-native/issues/19033

@franticBIT did you find a workaround that you could share?

**Comment by franticBIT** [comment]
@slorber Unfortunately not, since it wasn't the most urging issue of the project. But I hope this will get resolved, if more people are having the same issue.

**Comment by Bonobomagno** [comment]
yep, issue still here.
The main problem is the absence to shadow border control in android. If you can add elevation but also  disabling the shadow, (or just add the shadow without elevation, using zIndex in both android and ios) this problem issue be easy closed
