### ISSUE TITLE
[Touches] Disable multi-touch, specifically during navigation transitions

### ISSUE THREAD

**Issue by mixophrygian** [facebook/react-native#1584]
I'd like to disable multi-touch throughout the entire app, particularly to avoid corrupting my navigation when the user accidentally double taps and the same view gets pushed twice.  What's the best way to achieve this?

**Comment by ide** [comment]
@ericvicenti does the navigator currently do anything special to ignore touches on views that will lose focus?

@mixophrygian the `pointerEvents` prop lets you disable touches for any view and optionally its subviews. You could set `pointerEvents="none"` on your root component for the duration of the transition. https://facebook.github.io/react-native/docs/view.html#pointerevents

**Comment by ericvicenti** [comment]
Yep, the navigator currently blocks all touches on scenes during transitions

**Comment by mixophrygian** [comment]
Ya, the accidental double tap / double view push occurs before the transition.

**Comment by ericvicenti** [comment]
Is this a tap in the navbar or the scene itself? The navbar might have this issue, but tapping inside of a scene will be blocked once the transition begins, so a double tap should not be a problem.

This is a recent fix, so I would suggest cloning the repo and seeing if the master branch still suffers from this issue.

**Comment by ide** [comment]
Also so we're all on the same page - @mixophrygian are you using Navigator or NavigatorIOS?

**Comment by mixophrygian** [comment]
It's a custom navigator made with TouchableOpacity.

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/touches-disable-multi-touch-specifically-during-navigation-transitions
