### ISSUE TITLE
Execution failed for task ':app:mergeDebugAssets' when running android on Windows

### ISSUE THREAD

**Issue by WillyRamirez** [facebook/react-native#15849]
### Environment

1. `react-native -v`: react-native-cli: 2.0.1
react-native: 0.46.3
2. `node -v`: v7.6.0
3. `npm -v`: npm 4.1.2

Then, specify:

- Target Platform: Android

- Development Operating System: WINDOWS, (works fine on apple)

- Build tools: gradle -> react-native run-android

### Steps to Reproduce

(Write your steps here:)

1. open CMD in project root
2. type: react-native run-android
3. 

### Expected Behavior

The code is bundles correctly 100% of the times, and the app is launched on the emulator. When in debug JS remotely mode, I am able to reload the app without it crashing on me.

### Actual Behavior

50% of the times i try to run-android, i get the following error in CMD. When I run it again, it works. 
However, when it runs, and then I enter _debug js remotley_ mode i cannot reload the app or the emulator crashes. Every reload i do causes the app to freeze when in debug mode. No error is given.

This happened since i upgraded from 0.44.3 to 0.46.3

 react-native run-android:
```
* What went wrong:
Execution failed for task ':app:mergeDebugAssets'.
> Error: java.nio.file.AccessDeniedException: C:\projects\PROJECTNAME\android\
app\build\intermediates\assets\debug\fonts


```

**Comment by WillyRamirez** [comment]
Upgrading npm and node to latest solved the issue.

**Comment by cyphire** [comment]
I'm having the same problem... It just started, and I don't know why.  I did remove some old modules i no longer use and now having this problem.

**Comment by WillyRamirez** [comment]
I ended up buying a Mac.... :/

**Comment by Manish12197** [comment]
I have the same problem
