### ISSUE TITLE
Fetch does not pass parameter in POST

### ISSUE THREAD

**Issue by Miteshivgroup** [facebook/react-native#15845]
### Is this a bug report?
Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?
Yes
### Environment

1. `react-native -v`: 0.48.1
2. `node -v`: 8.4.0
3. `npm -v`: 5.3.0
4. `yarn --version`:

Then, specify:

- Target Platform: Android

- Development Operating System: Windows 7

### Steps to Reproduce

(Write your steps here:)

### 1.First 
 ```
 fetch('http://127.0.0.1:3000/check?', {
       method: 'POST',
       headers: {
         'Accept': 'application/json',
         'Content-Type': 'application/json',
       },
       body: JSON.stringify({
         firstParam: 'yourValue',
         secondParam: 'yourOtherValue',
       })
     })
```

### Expected Behavior
```
{
         firstParam: 'yourValue',
         secondParam: 'yourOtherValue',
       }
```
should be received as parameter to the check API

(Write what you thought would happen.)

### Actual Behavior
on GET method we receive the object as parameter in API but did not get in POST method

(Write what happened. Add screenshots!)
![image](https://user-images.githubusercontent.com/22392408/30157346-b3486fe2-93df-11e7-8ce7-e37cf96cbb66.png)
![image](https://user-images.githubusercontent.com/22392408/30157409-d8f8cc82-93df-11e7-8d09-4f24f13a5b08.png)
Parameter is not received in post method

### Reproducible Demo
 fetch('http://127.0.0.1:3000/check?', {
       method: 'POST',
       headers: {
         'Accept': 'application/json',
         'Content-Type': 'application/json',
       },
       body: JSON.stringify({
         firstParam: 'yourValue',
         secondParam: 'yourOtherValue',
       })
     })

**Comment by Shubham-Sinha** [comment]
You can access parameters passed in body as ``req.body.firstParams`` and ``req.body.secondParam`` . It's related to Express Js , and not with React Native or Fetch

**Comment by Miteshivgroup** [comment]
@Shubham-Sinha Thank you for your inputs.

**Comment by Miteshivgroup** [comment]
@Shubham-Sinha Thank you for your inputs.
