### ISSUE TITLE
HelveticaNeue-Light in v48 is too thin

### ISSUE THREAD

**Issue by blairvanderhoof** [facebook/react-native#15840]
iOS Bug
version 0.48.0

Upgraded from 0.47.1 to 0.48.0 and setting the font family on a Text component to HelveticaNeue-Light results in a very thin font, thinner than FontBook shows for that font on OSX.  I downgraded to 0.47.1 and the font now renders appropriately.

**Comment by chirag04** [comment]
@blairvanderhoof please follow the issue template. I think it could be a real bug so 
1) it would be help to have a reproducible demo
2) can you screenshot the screen using RN 0.47 and RN 0.48

**Comment by shergin** [comment]
Possible related to https://github.com/facebook/react-native/pull/15825

**Comment by chirag04** [comment]
@blairvanderhoof i am going to close this. let me know if #15825 does not fix the problem here. feel free to nominate the fix to be cherry-picked into 0.48.0 if not already done.
