### ISSUE TITLE
alignItems: 'baseline' doesn't work

### ISSUE THREAD

**Issue by autoric** [facebook/react-native#15858]
### Is this a bug report?

Yes.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes.

### Environment

1. `react-native -v`: 0.48.1
2. `node -v`: v7.9.0
3. `npm -v`: 5.4.1
4. `yarn --version`: N/A

Then, specify:

- Target Platform: iOS, Android

- Development Operating System: macOS Sierra 10.12.5

- Build tools:
`react-native run-ios`
`react-native run-android`

### Steps to Reproduce

1. Create a wrapper view with the styles: `{flexDirection: 'row', alignItems:'baseline'}`
2. Within the wrapper view, create multiple text nodes with different `fontSize`s

### Expected Behavior

The text nodes would be aligned along the baseline.

### Actual Behavior

The text nodes are not aligned along the baseline. The alignment is indistinguishable from `alignItems: 'flex-end'`
<img width="79" alt="screen shot 2017-09-07 at 2 26 37 pm" src="https://user-images.githubusercontent.com/918178/30183717-b43543b4-93d8-11e7-9981-d324966045d2.png">

### Reproducible Demo

https://snack.expo.io/HkoJ_QkcZ

(T16975579)

**Comment by joechrysler** [comment]
There is a pretty easy workaround to this. If you wrap your `<Text>`s in another `<Text>` with `alignItems: baseline`, everything lines up nicely.

https://snack.expo.io/ry2knIZ3-

**Comment by shergin** [comment]
I recently fixed this on iOS.

**Comment by gelitenight** [comment]
this bug still exists...
     "react": "16.3.1",
    "react-native": "0.55.2"

**Comment by mangei** [comment]
I confirm, this bug is still alive.

Screenshot:
![image](https://user-images.githubusercontent.com/1218033/44117092-94ca8f56-a012-11e8-9e34-c1ccf7089c6b.png)

**Comment by shergin** [comment]
https://github.com/facebook/react-native/blob/03663491c6e68409f73d5c9bbc1a2e3c02ee0966/RNTester/js/TextExample.ios.js#L226-L276

<img width="522" alt="screen shot 2018-08-14 at 4 28 46 pm" src="https://user-images.githubusercontent.com/22032/44119606-59a333d4-9fdf-11e8-8ab1-fb43b7e3999d.png">

**Comment by MrSeaWave** [comment]
@shergin on Android this bug still exists...

```
react-native init AwesomeProject
cd AwesomeProject
react-native run-android
```

## Environment
```
node v8.12.0
npm 6.4.1
react-native-cli: 2.0.1
react-native: 0.57.3
```
my package.json is
```
{
  "name": "TemReactNative",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.6.0-alpha.8af6728",
    "react-native": "0.57.3"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.48.1",
    "react-test-renderer": "16.6.0-alpha.8af6728"
  },
  "jest": {
    "preset": "react-native"
  }
}
```
the Code is

```jsx
import React, { PureComponent } from 'react';
import { Text, View, StyleSheet } from 'react-native';

export default class TestTextBaseline extends PureComponent {
  render() {
    return (
      <View style={styles.container}>
        <View style={styles.textContainer}>
          <Text style={{ fontSize: 65, backgroundColor: '#ff9c6e' }}>1</Text>
          <Text style={{ fontSize: 55, backgroundColor: '#ff9c6e' }}>1</Text>
          <Text style={{ fontSize: 45, backgroundColor: '#ff9c6e' }}>1</Text>
          <Text style={{ fontSize: 35, backgroundColor: '#ff9c6e' }}>1</Text>
          <Text style={{ fontSize: 25, backgroundColor: '#ff9c6e' }}>1</Text>
        </View>
      </View>
    );
  }
}

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center'
  },
  textContainer: {
    justifyContent: 'center',
    flexDirection: 'row',
    alignItems: 'baseline'
  }
});

```

ios is correct

![image](https://user-images.githubusercontent.com/21967852/47329231-82ab9c00-d6a6-11e8-8500-05fa8b6d5125.png)



But android is wrong
![image](https://user-images.githubusercontent.com/21967852/47329191-5bed6580-d6a6-11e8-96cb-cdb6caa40bdc.png)

**Comment by SaeedZhiany** [comment]
I'm on RN 0.59.10 and it's not working on android yet. I get the same result that @MrSeaWave getting.

**Comment by blueberry6401** [comment]
In many cases we cannot apple the workaround by wrapping all Texts inside Text, for example in making a table.
