### ISSUE TITLE
DatePickerAndroid style

### ISSUE THREAD

**Issue by MrVisitor** [facebook/react-native#15850]
Please add in to document https://facebook.github.io/react-native/docs/datepickerandroid.html description about style CalendarDatePickerDialog.

It is very important info, if your want change default style for DatePickerDialog on android.

I managed to change the style this way:
In styles.xml from res folder:
```
<resources>
    ...
    <style name="CalendarDatePickerDialog">
        <item name="colorAccent">#487FFE</item>
        <item name="android:colorAccent">#487FFE</item>
        <item name="android:textColorPrimary">#487FFE</item>
    </style>
<resources>
```

**Comment by hramos** [comment]
Feel free to send a PR!

**Comment by MrVisitor** [comment]
@hramos I will be glad to do this  #15864

**Comment by nateReiners** [comment]
@MrVisitor Thanks for the code snippet, it is the first thing online that has enabled me to change the date picker in any way. However, with those styles the datepicker shows up like this now https://imgur.com/a/nNNVsn7 . Any ideas what's wrong?
