### ISSUE TITLE
CircleCI todos

### ISSUE THREAD

**Issue by ide** [facebook/react-native#15855]
Just making a note of a few things to look at after we get fully running on CircleCI 2.

- Cache Android SDKs
- Tune worker parameters, see if/how parallelism helps us
- Look into `resource_class` for Android builds: https://circleci.com/docs/2.0/configuration-reference/#resource_class
- Adjust NDK cache key since uploading the cache archive is slower than installing the NDK (share across branches? don't cache?)

**Comment by hramos** [comment]
Currently I'm leaning towards not caching the NDK, as you said it's slower than downloading and extracting the archives.

To add to your list:

- [ ] Look into using a custom image with various dependencies set up ahead of time

The custom image could be set up ahead of time with the Android SDKs and NDK, but as you pointed out in the PR keeping the image up to date may be more trouble than it's worth. Some work has already gone into setting up such an image, see the `ContainerShip/` folder in this repo.

**Comment by hramos** [comment]
Once the test APK is built and native libraries are compiled, we may be able to fan out into three separate jobs that run unit tests, integration tests, and end to end tests in parallel, if that speeds up things. For these three, we may be able to use the basic android docker images, installing node on the last two as needed.

**Comment by sibelius** [comment]
`resource_class: large`

it is working fine on our projects

**Comment by hramos** [comment]
Re-opening as this is a discussion task.

**Comment by hramos** [comment]
@grabbou just opened a PR to move over iOS/tvOS tests from Travis to Circle: https://github.com/facebook/react-native/pull/16354

**Comment by dlowder-salesforce** [comment]
@hramos is Circle CI robust enough that we can actually run the unit and integration tests on tvOS?  At the moment I believe we're just testing that tvOS compiles....

**Comment by grabbou** [comment]
@dlowder-salesforce I think yeah, there's full OS X machine with different simulators, so no reason why it wouldn't be possible.

I think it's even advised as we are hitting few tvOS bugs from time to time :)

**Comment by grabbou** [comment]
@hramos what's the status of this issue? Anything left to get this closed?
