### ISSUE TITLE
0.44 PushNotifcationIOS.scheduleLocalNotification handles JavaScript Date objects in simulator, not on devices

### ISSUE THREAD

**Issue by atom-r** [facebook/react-native#15857]
1. `react-native -v`: 0.44.3
2. `node -v`: 6.3.0
3. `npm -v`: 3.10.3

- Target Platform: iOS

- Development Operating System: macOS Sierra 10.12.4

- Build tools: XCode

### Steps to Reproduce

This behavior results in a very confusing bug where scheduled notifications work as expected on the simulator, but fail in a very mysterious way on a device.

1. Schedule a local notification for one minute in the future: `PushNotificationIOS.scheduleLocalNotification({ 
fireDate: new Date(Date.now() + 60 * 1000),  alertBody: 'message'})`
2. Run this build in the simulator (by default this is a Debug build unless you mess with settings, I believe)
3. Observe that your notification gets scheduled as expected.
3. Run this build as a Debug build on your device through XCode (Edit your scheme so that Run uses Debug instead of Release)
5. Observe a crash when you attempt to schedule your notification
6. Run this as a Release build on your device.
7. Observe that the notification fires immediately (note that this is the behavior in iOS if a scheduled notification is assigned a null date or a date that has already passed.

Note that in order to observe the immediately-fired notification, you must have a listener set up to handle it and provide feedback. It seems that a local notification will not be displayed on iOS if its associated app is in the foreground (AppState: 'active').

It's possible that future versions of react native account for this and make the necessary conversion prior to sending the schedule date over the RCT bridge. I'm merely writing this up to document a pain point I hit, as I was unable to find any other similar issues elsewhere.

Please close this if you see fit.

**Comment by atom-r** [comment]
Ah, forgot our solution:

```
let desiredNotificationDate = new Date(Date.now + 60 * 1000); //one minute in the future
let fireDate = desiredNotificationDate.getTime()
```

Unix times are handled just fine in all environments.

**Comment by hramos** [comment]
Can you make sure this repros on 0.48? 0.44 is quite old.
