### ISSUE TITLE
[WebView] scrollEnabled={false} doesn't work for .pdf in a WebView 

### ISSUE THREAD

**Issue by lpetkovic** [facebook/react-native#15851]
I'm trying to disable scrolling inside a WebView that is showing a .pdf file. However, `scrollEnabled ` set to `false` does not disable it.
I've created a simple Snack example to demonstrate this: https://snack.expo.io/r1drA0Rt-

Versions I'm using
1. react-native: v0.47.0 (_edit by @hramos: updated this to 0.47, as your Snack repro is using Expo 20.0 which is itself based on RN 0.47_)
2. node v7.9.0
3. npm v4.2.0

Platform: iOS
OS: macOS Sierra 10.12.6

**Comment by hramos** [comment]
I was able to confirm that the repro occurs when a PDF is loaded, but not when a webpage is loaded (I used the RN website as an example).

I assume this is a case where iOS is taking over the display of the PDF, and the underlying UIWebView is unable to lock scrolling.

`WebView` is not currently owned by anyone, so a PR to fix this would be appreciated.
