### ISSUE TITLE
[RN 0.48.2 TextInput] onSubmitEditing not called if blurOnSubmit set to false

### ISSUE THREAD

**Issue by xxsnakerxx** [facebook/react-native#15863]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

1. `react-native -v`: 0.48.2
2. `node -v`: 8.4.0
3. `npm -v`: 4.6.1
4. `yarn --version`:

- Target Platform: iOS, Android

- Development Operating System: macOS Sierra 10.12.6

- Build tools:
`react-native run-ios`
`react-native run-android`

### Steps to Reproduce

1. 
```js
<TextInput 
  blurOnSubmit={false} 
  onSubmitEditing={() => alert('!!!')} 
  returnKeyType={'done'}
/>
```
2. If I press the __done__ button __onSubmitEditing__ callback not called

### Expected Behavior

`onSubmitEditing` should be called for  `blurOnSubmit={false}` text inputs

### Reproducible Demo

https://snack.expo.io/S1tMt619b
but I don't know how to turn on the last RN version there

**Comment by raphaelhovsepyan** [comment]
+1

**Comment by raphaelhovsepyan** [comment]
This is works on 0.47

**Comment by xxsnakerxx** [comment]
related with [this](https://github.com/facebook/react-native/commit/8f93ce680d79fac4b58e518fde5f019fb9eb7e89#diff-1fc9493f9f850337aca70b21009a5ee2R89) commit

I found a workaround

Change in `node_modules/react-native/Libraries/Text/RCTTextInput.m`
```obj-c
- (BOOL)textInputShouldReturn
{
  return _blurOnSubmit;
}
```
to
```obj-c
- (BOOL)textInputShouldReturn
{
  // We send `submit` event here, in `textInputShouldReturn`
  // (not in `textInputDidReturn)`, because of semantic of the event:
  // `onSubmitEditing` is called when "Submit" button
  // (the blue key on onscreen keyboard) did pressed
  // (no connection to any specific "submitting" process).
  [_eventDispatcher sendTextEventWithType:RCTTextEventTypeSubmit
                                 reactTag:self.reactTag
                                     text:self.backedTextInputView.text
                                      key:nil
                               eventCount:_nativeEventCount];
  
  return _blurOnSubmit;
}
```

**Comment by shergin** [comment]
It is fixed in master.

**Comment by raphaelhovsepyan** [comment]
So it will come with 0.49 I guess

**Comment by hramos** [comment]
#Fixed

**Comment by hblumberg** [comment]
Hello! Has this also been fixed on Android? I see it's been fixed for iOS [here](https://github.com/facebook/react-native/commit/b06672e6cf7eee1f94e535aef2c49d8f6d7e8e16). I'm experiencing this problem on 0.48 on Android (and it seems like the original issue also mentioned Android).

**Comment by shergin** [comment]
@hblumberg Exactly same code from the expo snack in the initial description does not work for you? (I just tried it in the expo emulator and it is working on Android.)
Could you please provide more details? Or even better Snack with your test case.

**Comment by hblumberg** [comment]
Thanks for your quick response, @shergin! The same code from the initial description is not working on my own emulator (with RN v0.48). It is working in Snack, but it seems to be working for iOS there too. I think the original post mentioned not being able to specify the RN version in Snack (so I assumed it wasn't running v0.48).

**Comment by shergin** [comment]
@hblumberg Yes, Expo SDK 20 is based on RN 47. I will try to repro this on master.

**Comment by FatalTouch** [comment]
Yup doesn't work with RN 0.48.3 on android.

**Comment by Adam0000** [comment]
@FatalTouch I'm finding the same. Though the iOS workaround by @xxsnakerxx works, so [this commit](https://github.com/facebook/react-native/commit/8f93ce680d79fac4b58e518fde5f019fb9eb7e89#diff-1fc9493f9f850337aca70b21009a5ee2R89) seems to fix iOS.

Android still has this bug.

**Comment by isnifer** [comment]
@hramos please, reopen

**Comment by Adam0000** [comment]
I found the [source of the issue](https://github.com/facebook/react-native/blob/3ae45d5cb8b9aaca568227ca00cc304e053bf073/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactTextInputManager.java#L735-L757) for Android. The comment there accurately describes what the code below it does:
```
// Motivation:
// * blurOnSubmit && isMultiline => Generate `submit` event; clear focus; prevent default behaviour (return true);
// * blurOnSubmit && !isMultiline => Generate `submit` event; clear focus; prevent default behaviour (return true);
// * !blurOnSubmit && isMultiline => Perform default behaviour (return false);
// * !blurOnSubmit && !isMultiline => Prevent default behaviour (return true).
```
However, the case for `!blurOnSubmit && !isMultiline` is not as desired. That case prevents the default behavior for the submit button but does not dispatch onSubmitEditing. That leaves no way for the submit button to have any behavior at all.

Replacing the linked lines with this block should fix the problem, though I haven't been able to test it:
```
boolean blurOnSubmit = editText.getBlurOnSubmit();
boolean isMultiline = ((editText.getInputType() &
  InputType.TYPE_TEXT_FLAG_MULTI_LINE) != 0);

// Motivation:
// * blurOnSubmit && isMultiline => Generate `submit` event; clear focus; prevent default behaviour (return true);
// * blurOnSubmit && !isMultiline => Generate `submit` event; clear focus; prevent default behaviour (return true);
// * !blurOnSubmit && isMultiline => Perform default behaviour (return false);
// * !blurOnSubmit && !isMultiline => Generate `submit` event; prevent default behaviour (return true).

boolean dispatchSubmitEvent = blurOnSubmit || !isMultiline;

if (dispatchSubmitEvent) {
  EventDispatcher eventDispatcher =
      reactContext.getNativeModule(UIManagerModule.class).getEventDispatcher();

  eventDispatcher.dispatchEvent(
      new ReactTextInputSubmitEditingEvent(
          editText.getId(),
          editText.getText().toString()));
}

if (blurOnSubmit) {
  editText.clearFocus();
}

// Prevent default behavior when dispatching `submit` event.
return dispatchSubmitEvent;
```

Also important to note is that the iOS behavior is not actually correct even after the commit @xxsnakerxx mentioned. While the `!blurOnSubmit && !isMultiline` case that this issue concerns is treated correctly by that commit, the `!blurOnSubmit && isMultiline` case still dispatches submit events along with adding a newline to the text. According to [the documentation](https://facebook.github.io/react-native/docs/textinput.html#onsubmitediting), that should not happen.

**Comment by isnifer** [comment]
@Adam0000 will you suggest a PR?

**Comment by joncursi** [comment]
I'm able to report the same issues on my end on `0.48.3`, both iOS and Android.

**Comment by Adam0000** [comment]
@isnifer Working on one.

**Comment by Adam0000** [comment]
Could someone weigh in on the desired behavior when tapping the submit button?

Currently (before the changes I'm making) we have on Android:
 * blurOnSubmit && isMultiline => Generate `submit` event, blur, do not insert newline
 * blurOnSubmit && !isMultiline => Generate `submit` event, blur
 * !blurOnSubmit && isMultiline => Insert newline
 * !blurOnSubmit && !isMultiline => Do nothing

And on iOS we have (on _master_, not 0.48.2):
 * blurOnSubmit && isMultiline => Generate `submit` event, blur, do not insert newline
 * blurOnSubmit && !isMultiline => Generate `submit` event, blur
 * !blurOnSubmit && isMultiline => Generate `submit` event, insert newline
 * !blurOnSubmit && !isMultiline => Generate `submit` event

I modified the Android behavior so that it generates a submit event for the last case. And I reconciled the iOS behavior with that:
 * blurOnSubmit && isMultiline => Generate `submit` event, blur, do not insert newline
 * blurOnSubmit && !isMultiline => Generate `submit` event, blur
 * !blurOnSubmit && isMultiline => Insert newline
 * !blurOnSubmit && !isMultiline => Generate `submit` event

The current documentation for [`onBlurSubmit`](https://facebook.github.io/react-native/docs/textinput.html#bluronsubmit) supports the behavior of the first case. But the documentation for [`onSubmitEditing`](https://facebook.github.io/react-native/docs/textinput.html#onsubmitediting) says the submit event is "invalid" if multiline is set (a contradiction in the first case).

Does this new behavior seem correct? Is there any reason to still dispatch the submit event in the third case, when a newline is also inserted?

**Comment by shergin** [comment]
I personally believe that we have to implement last one (do not generate submit event on third case).

**Comment by shergin** [comment]
@Adam0000 Thank you for investigating this! I would love to review and land your PRs.

**Comment by Adam0000** [comment]
@shergin Here's the PR: https://github.com/facebook/react-native/pull/16040
