### ISSUE TITLE
Android: CPU busy when application idling

### ISSUE THREAD

**Issue by davidmontemayor** [facebook/react-native#15868]
### Is this a bug report?
Yep.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?
Yep.

### Environment

1. `react-native -v`: 0.47.1
2. `node -v`: v7.7.1
3. `npm -v`: 4.1.2

Then, specify:

- Target Platform: Android
- Development Operating System: Mac OS
- Build tools: Android Studio, VS Code

### Steps to Reproduce
1. Start any react-native Android application
2. Execute systrace (e.g. `<android sdk>/platform-tools/systrace/systrace.py --time=4 -o trace.html sched gfx view -a com.appname`
3. Open the file. You should see something like this:
<img width="1166" alt="screenshot 2017-09-07 15 58 05" src="https://user-images.githubusercontent.com/340216/30213961-c5309aa6-9478-11e7-8f0d-d81702429d5d.png">
4. If you zoom in, you see that it seems like there's an animation callback that keeps firing
<img width="1401" alt="screenshot 2017-09-07 15 58 47" src="https://user-images.githubusercontent.com/340216/30213998-e0dab764-9478-11e7-9b3d-4ce95ac76221.png">
5. In the Android Profiler, you can see the CPU constantly doing work as well:
<img width="1166" alt="screenshot 2017-09-07 15 58 05" src="https://user-images.githubusercontent.com/340216/30214309-eb968452-9479-11e7-8e91-f3bcdb01e48b.png">
5. Open any other android app
6. Execute systrace (e.g. `<android sdk>/platform-tools/systrace/systrace.py --time=4 -o trace.html sched gfx view -a com.theotherappname`
7. (Note that in this case I scrolled in a list view, because otherwise this view would be mostly blank)
<img width="1217" alt="screenshot 2017-09-07 16 01 54" src="https://user-images.githubusercontent.com/340216/30214054-06176edc-9479-11e7-9ce0-5b38ec47a11d.png">

### Expected Behavior
Little to no CPU usage when application is idling.

### Actual Behavior
Quite a bit of CPU while application is idling.

### Reproducible Demo
Any app should be able to reproduce this.

Sounds similar to [this guy](https://github.com/facebook/react-native/issues/1539). I can attach the trace HTMLs if that seems useful.

**Comment by hramos** [comment]
Can you make sure this repros on 0.48?

**Comment by davidmontemayor** [comment]
I just tested this by doing:
1. `react-native init RnTest` (which configured RN 0.48.3)
2. `react-native run-android`
3. `systrace.py --time=4 -o trace_rntest_483.html sched gfx view -a com.rntest`

Here's a screenshot of the HTML:
<img width="1174" alt="screenshot 2017-09-14 10 48 39" src="https://user-images.githubusercontent.com/340216/30436662-b1171e70-993a-11e7-83e3-9fb6e99b711f.png">

**Comment by davidmontemayor** [comment]
@hramos - Any update on this?

**Comment by hramos** [comment]
I don't have any updates - generally my goal here is to make sure issues provide sufficient information so that a community member may proceed to provide a fix.

**Comment by davidmontemayor** [comment]
Gotcha, thanks!
