### ISSUE TITLE
ScrollView has no propType for RCTScrollView.onScrollAnimationEnd Error

### ISSUE THREAD

**Issue by younanjo** [facebook/react-native#15875]
### Is this a bug report?

Yes

### Have you read the Contributing Guidelines?

Yes.

### Environment

1. `react-native -v`: 0.48.2
2. `node -v`: v7.10.0
3. `yarn --version`: 1.0.1
4. `exp:` 44.0.0

- Target Platform: iOS 
- Development Operating System: macOS 10.12.6

### Steps to Reproduce

my dependencies

```
  "dependencies": {
    "axios": "^0.16.2",
    "expo": "^20.1.2",
    "faker": "^4.1.0",
    "history": "^4.7.2",
    "jwt-decode": "^2.2.0",
    "moment": "^2.18.1",
    "prop-types": "^15.5.10",
    "rambda": "^0.9.0",
    "react": "16.0.0-alpha.12",
    "react-native": "0.48.2",
    "react-native-animatable": "^1.2.3",
    "react-native-config": "^0.6.0",
    "react-native-device-info": "^0.11.0",
    "react-native-drawer": "^2.5.0",
    "react-native-vector-icons": "^4.3.0",
    "react-redux": "^5.0.6",
    "react-router": "^4.2.0",
    "react-router-native": "^4.2.0",
    "react-router-navigation": "^1.0.0-rc.3",
    "react-router-redux": "5.0.0-alpha.6",
    "reactotron-redux-saga": "^1.12.2",
    "redux": "^3.7.2",
    "redux-logger": "^3.0.6",
    "redux-persist": "^4.9.1",
    "redux-saga": "^0.15.6",
    "seamless-immutable": "^7.0.1",
    "styled-components": "^2.1.2"
  }

```

1)  Remove all your installed node_modules and existing ios/android

```
watchman watch-del-all
rm -rf ./node_modules
rm -rf ./ios
rm -rf ./android
rm -rf $TMPDIR/react-*
yarn cache clean
yarn
```
2) rebuild ios/android and link
```
react-native-git-upgrade
react-native upgrade
react-native link
``` 

Note: `yarn outdated` should have no outdated packages related to react-native.

### Expected Behavior

App should launch successfully

### Actual Behavior

<img width="374" alt="screen shot 2017-09-09 at 12 31 11 pm" src="https://user-images.githubusercontent.com/957874/30236458-017e67a6-955d-11e7-9cf7-ee04ca0e9dc1.png">

**Comment by wellyshen** [comment]
I have the same issue

**Comment by augustoody** [comment]
Me too

**Comment by augustoody** [comment]
By the way, a downgrade the react-native to 0.47.2 and the error stopped now

**Comment by wellyshen** [comment]
Yea, I also downgrade to the 0.47.2 and waiting for bug fixing.

**Comment by Dallas62** [comment]
I have the same issue using the `Button` Component:
```js
import { Button } from 'react-native';
```

**Comment by majd-kho** [comment]
It seems that the expo app is incompatible with RN 0.48.

**Comment by javascala** [comment]
I met the same issue

**Comment by DanielRamosAcosta** [comment]
I'm having the same issue:

* react-native -v: 0.48.3
* node -v: v8.4.0
* yarn --version: 1.0.1

* react: 16.0.0-rc.2

**Comment by majd-kho** [comment]
Try running your code base using react-native init [project]

**Comment by majd-kho** [comment]
Try running your code base using react-native init [project]

**Comment by wellyshen** [comment]
@majd-kho Is this command for creating a new RN project right? Why you think the command can fix this issue?

**Comment by majd-kho** [comment]
Im not exactly sure, but rn0.48 is incompatible with the expo client  app,
but for some reason my code ran on a simulator (after creating a rn project
using react-native init)  but not the expo client after upgrading to rn
0.48.
So in short  create-react-native-app  didn't run my codebase  with rn 0.48
on a physical device. But react-native init ran it.

**Comment by johndanek** [comment]
This is still an issue for me in version 0.48.3. I can't find a way around this issue. I've wiped out node_modules and run `react-native-git-upgrade`. Still get this error every time.

**Comment by wellyshen** [comment]
I solved this problem by `react-native init <Your App Name>` and migration all my stuff to the new project. So stupid but it works. HAHA

**Comment by DanielRamosAcosta** [comment]
@wellyshen can you post your package.json please? And if possible the .lock too

**Comment by limitsapp** [comment]
@wellyshen i tryed this and got the same error in the new project? what could be causing this

**Comment by seantimm** [comment]
We're experiencing the same problem.

**Comment by rochapablo** [comment]
+1

**Comment by johndanek** [comment]
Note: It looks like this is only happening in iOS for me. Android is working fine.

**Comment by abdennour** [comment]
We are experiencing the same problem . It happens after clicking on "Reset Content and Settings" for simulator : 

<img width="304" alt="screen shot 2017-09-26 at 03 48 17" src="https://user-images.githubusercontent.com/1788384/30837439-b38d8a86-a26d-11e7-9cb0-92025d6ed047.png">

**Comment by rubencodes** [comment]
I was getting this on 0.48.0 and after downgrading, I'm getting this slight variation on 0.47.2... Tried deleting node_modules several times and still getting the same thing.

<img width="412" alt="screen shot 2017-09-26 at 3 07 49 pm" src="https://user-images.githubusercontent.com/1036549/30886715-f54dbf04-a2cc-11e7-993f-63ac4ee87035.png">

**Comment by tyeon95** [comment]
#https://github.com/expo/expo/issues/679#issuecomment-332243743
