### ISSUE TITLE
[PickerIOS] Wrapping `PickerIOS` with a container and `flexDirection: "row"` view breaks scrolling and selection

### ISSUE THREAD

**Issue by tonyhb** [facebook/react-native#1587]
Wrapping a PickerIOS with a parent who has the styles `flex: 1, flexDirection: "row"` breaks PickerIOS views completely.  It doesn't break date picker views, though.

Example code (the bottom picker will be unselectable):

```js
/**
 * The examples provided by Facebook are for non-commercial testing and
 * evaluation purposes only.
 *
 * Facebook reserves all rights not expressly granted.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL
 * FACEBOOK BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
 * AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 * @flow
 */
'use strict';

var React = require('react-native');

var {
  PickerIOS,
  Text,
  View,
} = React;

var PickerItemIOS = PickerIOS.Item;

var CAR_MAKES_AND_MODELS = {
  amc: {
    name: 'AMC',
    models: ['AMX', 'Concord', 'Eagle', 'Gremlin', 'Matador', 'Pacer'],
  },
  alfa: {
    name: 'Alfa-Romeo',
    models: ['159', '4C', 'Alfasud', 'Brera', 'GTV6', 'Giulia', 'MiTo', 'Spider'],
  },
  aston: {
    name: 'Aston Martin',
    models: ['DB5', 'DB9', 'DBS', 'Rapide', 'Vanquish', 'Vantage'],
  },
  audi: {
    name: 'Audi',
    models: ['90', '4000', '5000', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'Q5', 'Q7'],
  },
  austin: {
    name: 'Austin',
    models: ['America', 'Maestro', 'Maxi', 'Mini', 'Montego', 'Princess'],
  },
  borgward: {
    name: 'Borgward',
    models: ['Hansa', 'Isabella', 'P100'],
  },
  buick: {
    name: 'Buick',
    models: ['Electra', 'LaCrosse', 'LeSabre', 'Park Avenue', 'Regal',
             'Roadmaster', 'Skylark'],
  },
  cadillac: {
    name: 'Cadillac',
    models: ['Catera', 'Cimarron', 'Eldorado', 'Fleetwood', 'Sedan de Ville'],
  },
  chevrolet: {
    name: 'Chevrolet',
    models: ['Astro', 'Aveo', 'Bel Air', 'Captiva', 'Cavalier', 'Chevelle',
             'Corvair', 'Corvette', 'Cruze', 'Nova', 'SS', 'Vega', 'Volt'],
  },
};

var PickerExample = React.createClass({
  getInitialState: function() {
    return {
      carMake: 'cadillac',
      modelIndex: 3,
    };
  },

  render: function() {
    var make = CAR_MAKES_AND_MODELS[this.state.carMake];
    var selectionString = make.name + ' ' + make.models[this.state.modelIndex];
    debugger;
    return (
      <View>
        <Text>Please choose a make for your car:</Text>
        <PickerIOS
          selectedValue={this.state.carMake}
          onValueChange={(carMake) => this.setState({carMake, modelIndex: 0})}>
          {Object.keys(CAR_MAKES_AND_MODELS).map((carMake) => (
            <PickerItemIOS
              key={carMake}
              value={carMake}
              label={CAR_MAKES_AND_MODELS[carMake].name}
              />
            )
          )}
        </PickerIOS>

        <Text>Please choose a model of {make.name}:</Text>
        <View style={{flex: 1, flexDirection: 'row'}}>
	        <PickerIOS
	          selectedValue={this.state.modelIndex}
	          key={this.state.carMake}
	          onValueChange={(modelIndex) => this.setState({modelIndex})}>
	          {CAR_MAKES_AND_MODELS[this.state.carMake].models.map(
	            (modelName, modelIndex) => (
	              <PickerItemIOS
	                key={this.state.carmake + '_' + modelIndex}
	                value={modelIndex}
	                label={modelName}
	              />
	            ))
	          }
	        </PickerIOS>
        </View>
        <Text>You selected: {selectionString}</Text>
      </View>
    );
  },
});
module.exports = PickerExample;
```

**Comment by tonyhb** [comment]
So one of the easy solutions is, in `PickerIOS.js`, wrapping RCTPicker in a view like so:

```js
  render: function() {
    return (
      <View style={this.props.style}>
        <View style={{flex: 1, flexDirection: 'column'}}>
          <RCTPickerIOS
            ref={PICKER}
            style={styles.pickerIOS}
            items={this.state.items}
            selectedIndex={this.state.selectedIndex}
            onChange={this._onChange}
          />
        </View>
      </View>
    );
  },
```

It's an unexpected wrapper and band-aid though.  Just haven't been able to pinpoint the relationship between flexbox and the RCTPicker view to figure out the issue.

**Comment by nicklockwood** [comment]
@vjeux, I noticed that we're using different default styles for PickerIOS and DatePickerIOS width/height, but I'm not really sure what these should be. In both cases, the height is fixed and can't be changed, and the width has a default value, but should ideally be flexible.

Any thoughts?

**Comment by jhsu** [comment]
running into this issue too, tried @tonyhb 's solution of wrapping the `RCTPicker` but it still is messed up:

![](http://cl.ly/image/0f1D2D3m2l0q/Screen%20Shot%202015-08-27%20at%205.42.23%20PM.png)

**Comment by ide** [comment]
Rather than trying to pick a default could we rely on flex box / user-specified widths as we do for Images (would be a breaking change)?

**Comment by chetstone** [comment]
+1. Yes, picker should definitely be styleable.

**Comment by elisei-timofte** [comment]
I am trying to get two PickerIOS on the same row, but I can not set the width properly. It just cut from the content. I'd like to be able to set styles to the picker so I can decide the left and right padding. Thanks
<img width="392" alt="screen shot 2015-10-30 at 6 13 55 pm" src="https://cloud.githubusercontent.com/assets/6162068/10851115/070debda-7f32-11e5-827e-fe45844e94a4.png">

**Comment by cosmith** [comment]
I'm having a related issue with `DatePickerIOS` too. The width and height are hardcoded here: https://github.com/facebook/react-native/blob/dd09c88571f5397346903e0e8c73224cbf40c862/Libraries/Components/DatePicker/DatePickerIOS.ios.js#L142-L147

Removing them and leaving flexbox set the width seems to work perfectly for me so I'm not sure why they're set in the first place (well maybe having a default height is good otherwise the component doesn't show up).

I'm not sure how to fix this elegantly without a breaking change though.

**Comment by nicklockwood** [comment]
I feel like we need to have a way to specify default size without hard-coding the width and height. Setting default size would be like setting width/height, except that it would be overridden automatically by flex properties, instead of you having to undefine the width/height explicitly.

**Comment by cosmith** [comment]
@nicklockwood agreed. In the meantime what I'm doing is this:

```js
    componentDidUpdate: function () {
        if (this.refs.datepickeropen && this.refs.datepickerclose) {
            this.refs.datepickeropen.refs.datepicker.setNativeProps({width: Window.width - 100});
            this.refs.datepickerclose.refs.datepicker.setNativeProps({width: Window.width - 100});
        }
    },
```

which is not ideal...

**Comment by dorthwein** [comment]
this go anywhere?

**Comment by geirman** [comment]
@facebook-github-bot label "For Discussion"

**Comment by geirman** [comment]
@facebook-github-bot label Help Wanted

**Comment by geirman** [comment]
@facebook-github-bot label Size/s

**Comment by geirman** [comment]
@facebook-github-bot label For Discussion

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/pickerios-wrapping-pickerios-with-a-container-and-flexdirection-row-view-breaks-scrolling-and-selection

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
