### ISSUE TITLE
[Bug / Docs] Usage of nvm is undocumented

### ISSUE THREAD

**Issue by calvinf** [facebook/react-native#15883]
### Is this a bug report?

Yes.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes.

### Environment

1. `react-native -v`: react-native-cli: 2.0.1, react-native: 0.48.2
2. `node -v`: v8.4.0
3. `npm -v`: 5.3.0
4. `yarn --version`: 1.0.1

Then, specify:

- Target Platform: iOS

- Development Operating System: macOS Sierra - 10.12.6 (16G29)

- Build tools: XCode

### Steps to Reproduce

(Write your steps here:)

1. I forgot I had an old version of `nvm` installed that I'd never removed from my system and it was using Node v4.  
2. When `react-native-xcode.sh` ran, it used the version of node.js provided by `nvm` which is different from the default version of node.js on my system that I use for the rest of my development.

### Expected Behavior

I expected to be told on the command line or in documentation that:

1. A certain version of `node` or newer is required to support React Native.
2. That `nvm` is used by  the system if it is available.  (Either directly installed or via `brew`.)

See [react-native-xcode.sh](https://github.com/facebook/react-native/blob/743dc20aac54ed1d5e9a259fcf6b41a05aab2473/scripts/react-native-xcode.sh#L48-L62).

### Actual Behavior

My bundle failed due to using an old version of node via nvm without me knowing.  None of the debugging instructions say anything about nvm being used.

I fixed the problem by uninstalling nvm on my system since I haven't been using it in development anymore.

### Reproducible Demo

This should be reproducible by [installing `nvm`](https://github.com/creationix/nvm#installation) and Node 4.x.

I'm not sure of a good way to share a reproducible demo since this is more of an environment configuration issue.  I'd expect to occur with the React Native demo app, too.

### Next steps

I'm interested in working on a "fix" for this issue by adding some documentation, but I could use some guidance on the best approach.  Where in the docs does it make sense to add info about `nvm`?

The `react-native-xcode.sh` file doesn't log out anything about the node version being used -- is that something that would make sense to add?

**Comment by hramos** [comment]
Node 4 is supported, but there's a known issue with how the eslint deps are pulled in that results in an error when npm2 is used (which is the version of npm Node 4 comes with). If we fix that, then the issue you're reporting should go away.

See #15821 for discussion.
