### ISSUE TITLE
`allowFontScaling={false}` doesn't work with TextInput's placeholder in Android. 

### ISSUE THREAD

**Issue by BBBOND** [facebook/react-native#15886]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

1. `react-native -v`: 0.43.4
2. `node -v`: v6.11.2
3. `npm -v`: 3.10.10
4. `yarn --version`: 0.24.5

Then, specify:

- Target Platform: Android

- Development Operating System: macOS

- Build tools: Android Studio, buildToolsVersion "23.0.1"

### Steps to Reproduce

(Write your steps here:)

1. Use `TextInput` in the project
2. set `allowFontScaling={false}` the component

### Expected Behavior

Text and placeholder size shouldn't be scaled when user set font size.

### Actual Behavior

1. Text size don't be scaled.(It's right.)
![image](https://user-images.githubusercontent.com/9862759/30267243-89d519d4-9714-11e7-9f4e-4828a103ce31.png)
2. Placeholder size still be scaled.(**I think that it's unreasonable.**)
![image](https://user-images.githubusercontent.com/9862759/30267227-7c2127ba-9714-11e7-9f98-c984cf55d5ca.png)

**Comment by sejas** [comment]
It does not work on *iOS* either

**Comment by sabbyt54** [comment]
+1

**Comment by PasinduDineth** [comment]
any solution for this. I am having the same problem.

**Comment by inodw1** [comment]
i have the same problem. since my galaxy s5  only have font size MEDIUM, i have to scroll inside textinput to see the placeholder. How to fix this. 
 Thanks..

**Comment by VasudevAkhil** [comment]
I have the same problem in android

**Comment by levynir** [comment]
This really is a problem in both ios and android.

**Comment by BeckyWu220** [comment]
I found the placeholder of text input component in Android not ignoring the device system font size. Even in the latest react-native 0.54 version, the issue still exist. I finally solved it by making a faked placeholder on top of the text input instead of using the placeholder props of text input.

**Comment by yoonzm** [comment]
I solved:

import React from 'react'
import {
  Text,
  TextInput,
  PixelRatio,
  Platform,
} from 'react-native'

const ReactNativePropRegistry = require('ReactNativePropRegistry');

const fontSizeScale = PixelRatio.getFontScale()

const originTextRender = Text.prototype.render
const originTextInputRender = TextInput.prototype.render

function defaultFontSize() {
  return Platform.OS === 'ios' ? 15 : 14
}

function fixedFontSize(target) {
  return function () {
    const originComponent = target.apply(this, arguments);
    return React.cloneElement(originComponent, {
      allowFontScaling: false
    })
  }
}

Text.prototype.render = fixedFontSize(originTextRender)
TextInput.prototype.render = function () {
  const originComponent = originTextInputRender.apply(this, arguments);
  try {
    const originText = originComponent.props.children
    let originStyle = originText.props.style
    let newStyle = {
      fontSize: defaultFontSize()
    }
    const textStyle = originStyle[0]

    if (Number.isInteger(textStyle)) {
      textStyle = ReactNativePropRegistry.getByID(textStyle)
    }

    if (Array.isArray(textStyle)) {
      newStyle = textStyle.reduce((pre, styleItem) => ({...pre, ...(styleItem || {})}), newStyle)
    } else {
      newStyle = {...newStyle, ...(textStyle || {})}
    }
    newStyle.fontSize = newStyle.fontSize / fontSizeScale

    return React.cloneElement(originComponent, {
      children: {
        ...originText,
        props: {
          ...originText.props,
          style: newStyle
        }
      }
    })
  } catch (e) {
    return originComponent
  }
}

It's work.

**Comment by yoonzm** [comment]
I solved:


import React from 'react'
import {
  Text,
  TextInput,
  PixelRatio,
  Platform,
} from 'react-native'

const ReactNativePropRegistry = require('ReactNativePropRegistry');

const fontSizeScale = PixelRatio.getFontScale()

const originTextRender = Text.prototype.render
const originTextInputRender = TextInput.prototype.render

function defaultFontSize() {
  return Platform.OS === 'ios' ? 15 : 14
}

function fixedFontSize(target) {
  return function () {
    const originComponent = target.apply(this, arguments);
    return React.cloneElement(originComponent, {
      allowFontScaling: false
    })
  }
}

Text.prototype.render = fixedFontSize(originTextRender)
TextInput.prototype.render = function () {
  const originComponent = originTextInputRender.apply(this, arguments);
  try {
    const originText = originComponent.props.children
    let originStyle = originText.props.style
    let newStyle = {
      fontSize: defaultFontSize()
    }
    const textStyle = originStyle[0]

    if (Number.isInteger(textStyle)) {
      textStyle = ReactNativePropRegistry.getByID(textStyle)
    }

    if (Array.isArray(textStyle)) {
      newStyle = textStyle.reduce((pre, styleItem) => ({...pre, ...(styleItem || {})}), newStyle)
    } else {
      newStyle = {...newStyle, ...(textStyle || {})}
    }
    newStyle.fontSize = newStyle.fontSize / fontSizeScale

    return React.cloneElement(originComponent, {
      children: {
        ...originText,
        props: {
          ...originText.props,
          style: newStyle
        }
      }
    })
  } catch (e) {
    return originComponent
  }
}


It's work.

**Comment by NelGarbuzova** [comment]
Still have this issue

**Comment by NelGarbuzova** [comment]
Guys, I faced with the same problem. I created this lib for resolving this issue in my project. Maybe it will help you: https://github.com/NelGarbuzova/react-native-stylized-placeholder  .

**Comment by anirudha-ani** [comment]
For placeholder fontSize change issue @NelGarbuzova  's solution works. To fix font changing while inputting text the workaround is to - 

1. import PixelRatio from react-native 
2. In TextInput style set your fontSize to {intendedFontSize / PixelRatio.getFontScale()}

It will fix your fontSize and won't change because of system settings for both android and iOS. For this workaround don't set allowFontScaling to false.

**Comment by latera1n** [comment]
> For placeholder fontSize change issue @NelGarbuzova 's solution works. To fix font changing while inputting text the workaround is to -
> 
> 1. import PixelRatio from react-native
> 2. In TextInput style set your fontSize to {intendedFontSize / PixelRatio.getFontScale()}
> 
> It will fix your fontSize and won't change because of system settings for both android and iOS. For this workaround don't set allowFontScaling to false.

This works for me on Android 99%, but still there is a noticeable flash of font size change (intended size -> smaller size -> intended size) when starting to input contents into empty `TextInput`s.
