### ISSUE TITLE
ActivityIndicator cannot be a number on iOS

### ISSUE THREAD

**Issue by Noitidart** [facebook/react-native#15884]
On Android I was using a number of `60` for `ActivityIndicator`. However on iOS it complains, it only wants `"small"` or `"large"`, is this a bug? Is it intended that iOS can also take a number?

**Comment by vonovak** [comment]
please take a good look at the docs https://facebook.github.io/react-native/docs/activityindicator.html#size

**Comment by Noitidart** [comment]
Oh dang thanks. Any ideas if they plan to support size for iOS? That would be awesome.
