### ISSUE TITLE
Content-Encoding headers are used for things other then 'gzip'

### ISSUE THREAD

**Issue by BarnabyShearer** [facebook/react-native#15895]
https://github.com/facebook/react-native/blob/1e8f3b11027fe0a7514b4fc97d0798d3c64bc895/ReactAndroid/src/main/java/com/facebook/react/modules/network/NetworkingModule.java#L576

This line is over zealous, removing all 'Content-Encoding' headers rather then filtering out 'gzip' as intended. My use-case is https://www.rfc-editor.org/rfc/rfc8188.txt

I am not even sure if it is safe to remove 'gzip' given the requestData may already by compressed.

**Comment by JonasWho** [comment]
+1
