### ISSUE TITLE
When the screen is clicked quickly, FlatList scrollToIndex() is slower, but after opening the Debug JS Remotely, FlatList scrollToIndex() becomes very fast, which is why？

### ISSUE THREAD

**Issue by SemperChen** [facebook/react-native#15903]
import React, {Component} from 'react';
import {AppRegistry, Dimensions, FlatList, StatusBar, Text, View} from 'react-native';

export default class readertest1 extends Component {
    constructor() {
        super();
        this.width = Dimensions.get('window').width;
        this.height = Dimensions.get('window').height;
        StatusBar.setHidden(true);
        this.currentCount = 0;
        this.state = {
            array: [123, 456, 789, 1000]
        }
    }

    render() {
        return (
            <View
                style={{height: this.height, width: this.width, flex: 1}}
                onStartShouldSetResponder={() => {
                    return true
                }}
                onMoveShouldSetResponder={() => {
                    return true
                }}
                onResponderRelease={(e) => {
                    let pageY = e.nativeEvent.pageY;
                    if (pageY < this.height / 5 * 2) {

                        if (this.currentCount < this.state.array.length && this.currentCount > 0) {
                            this.currentCount--;
                            this._flatRef.scrollToIndex({
                                animated: false,
                                index: this.currentCount
                            });

                        } else {
                        }
                    } else if (pageY > this.height / 5 * 3) {

                        if (this.currentCount < this.state.array.length - 1) {
                            this.currentCount++;
                            this._flatRef.scrollToIndex({
                                animated: false,
                                index: this.currentCount
                            });
                        } else {
                        }
                    } else {

                    }
                    // console.log('onResponderRelease:',e.nativeEvent)
                }}>
                <FlatList
                    ref={(ref) => {
                        this._flatRef = ref
                    }}

                    data={this.state.array}
                    extraData={[]}
                    getItemLayout={(data, index) => (
                        {length: this.height, offset: this.height * index, index}
                    )}
                    onEndReachedThreshold={100}
                    onEndReached={() => {
                        this.array = this.state.array;
                        this.array = this.array.concat(this.array);
                        this.setState({
                            array: this.array
                        })
                    }}
                    keyExtractor={(item, index) => {
                        return index
                    }}
                    renderItem={({item}) => {
                        return <View
                            style={{
                                height: this.height,
                                width: this.width,
                                alignItems: 'center',
                                justifyContent: 'center'
                            }}>
                            <Text
                                style={{fontSize: 32}}>{item}</Text>
                        </View>
                    }}/>
            </View>
        );
    }
}
AppRegistry.registerComponent('readertest1', () => readertest1);

**Comment by Andrfas** [comment]
Facing the same issue with scrollToIndex (very-very slow performance). Why is this closed?
