### ISSUE TITLE
run-android stuck in:app:mergeDebugResources

### ISSUE THREAD

**Issue by saeedvaziry** [facebook/react-native#15909]
When i run react-native run-android android building stuck in :app:mergeDebugResources and does not report any error.

Here is my package.json file :

	{
		"name": "listeo",
		"version": "0.0.1",
		"private": true,
		"scripts": {
			"start": "node node_modules/react-native/local-cli/cli.js start",
			"test": "jest"
		},
		"dependencies": {
			"react": "16.0.0-alpha.12",
			"react-native": "0.48.2"
		},
		"devDependencies": {
			"babel-jest": "21.0.2",
			"babel-preset-react-native": "3.0.2",
			"jest": "21.0.2",
			"react-test-renderer": "16.0.0-alpha.12"
		},
		"jest": {
			"preset": "react-native"
		}
	}

build.gradle file in app folder :

    apply plugin: "com.android.application"

    import com.android.build.OutputFile

    /**
     * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
     * and bundleReleaseJsAndAssets).
     * These basically call `react-native bundle` with the correct arguments during the Android build
     * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
     * bundle directly from the development server. Below you can see all the possible configurations
     * and their defaults. If you decide to add a configuration block, make sure to add it before the
     * `apply from: "../../node_modules/react-native/react.gradle"` line.
     *
     * project.ext.react = [
     *   // the name of the generated asset file containing your JS bundle
     *   bundleAssetName: "index.android.bundle",
     *
     *   // the entry file for bundle generation
     *   entryFile: "index.android.js",
     *
     *   // whether to bundle JS and assets in debug mode
     *   bundleInDebug: false,
     *
     *   // whether to bundle JS and assets in release mode
     *   bundleInRelease: true,
     *
     *   // whether to bundle JS and assets in another build variant (if configured).
     *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
     *   // The configuration property can be in the following formats
     *   //         'bundleIn${productFlavor}${buildType}'
     *   //         'bundleIn${buildType}'
     *   // bundleInFreeDebug: true,
     *   // bundleInPaidRelease: true,
     *   // bundleInBeta: true,
     *
     *   // whether to disable dev mode in custom build variants (by default only disabled in release)
     *   // for example: to disable dev mode in the staging build type (if configured)
     *   devDisabledInStaging: true,
     *   // The configuration property can be in the following formats
     *   //         'devDisabledIn${productFlavor}${buildType}'
     *   //         'devDisabledIn${buildType}'
     *
     *   // the root of your project, i.e. where "package.json" lives
     *   root: "../../",
     *
     *   // where to put the JS bundle asset in debug mode
     *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
     *
     *   // where to put the JS bundle asset in release mode
     *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
     *
     *   // where to put drawable resources / React Native assets, e.g. the ones you use via
     *   // require('./image.png')), in debug mode
     *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
     *
     *   // where to put drawable resources / React Native assets, e.g. the ones you use via
     *   // require('./image.png')), in release mode
     *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
     *
     *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
     *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
     *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
     *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
     *   // for example, you might want to remove it from here.
     *   inputExcludes: ["android/**", "ios/**"],
     *
     *   // override which node gets called and with what additional arguments
     *   nodeExecutableAndArgs: ["node"],
     *
     *   // supply additional arguments to the packager
     *   extraPackagerArgs: []
     * ]
     */

    apply from: "../../node_modules/react-native/react.gradle"

    /**
     * Set this to true to create two separate APKs instead of one:
     *   - An APK that only works on ARM devices
     *   - An APK that only works on x86 devices
     * The advantage is the size of the APK is reduced by about 4MB.
     * Upload all the APKs to the Play Store and people will download
     * the correct one based on the CPU architecture of their device.
     */
    def enableSeparateBuildPerCPUArchitecture = false

    /**
     * Run Proguard to shrink the Java bytecode in release builds.
     */
    def enableProguardInReleaseBuilds = false

    android {
        compileSdkVersion 23
        buildToolsVersion "23.0.1"

        defaultConfig {
            applicationId "com.listeo"
            minSdkVersion 16
            targetSdkVersion 22
            versionCode 1
            versionName "1.0"
            ndk {
                abiFilters "armeabi-v7a", "x86"
            }
        }
        splits {
            abi {
                reset()
                enable enableSeparateBuildPerCPUArchitecture
                universalApk false  // If true, also generate a universal APK
                include "armeabi-v7a", "x86"
            }
        }
        buildTypes {
            release {
                minifyEnabled enableProguardInReleaseBuilds
                proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            }
        }
        // applicationVariants are e.g. debug, release
        applicationVariants.all { variant ->
            variant.outputs.each { output ->
                // For each separate APK per architecture, set a unique version code as described here:
                // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
                def versionCodes = ["armeabi-v7a":1, "x86":2]
                def abi = output.getFilter(OutputFile.ABI)
                if (abi != null) {  // null for the universal-debug, universal-release variants
                    output.versionCodeOverride =
                            versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
                }
            }
        }
    }

    dependencies {
        compile fileTree(dir: "libs", include: ["*.jar"])
        compile "com.android.support:appcompat-v7:23.0.1"
        compile "com.facebook.react:react-native:+"  // From node_modules
    }

    // Run this once to be able to run the application with BUCK
    // puts all compile dependencies into folder libs for BUCK to use
    task copyDownloadableDepsToLibs(type: Copy) {
        from configurations.compile
        into 'libs'
    }

When i run `react-native run-android` i get :

	$ react-native run-android
	Scanning 574 folders for symlinks in C:\Users\Saeed\Projects\Apps\listeo\node_modules (54ms)
	JS server already running.
	Building and installing the app on the device (cd android && gradlew.bat installDebug)...
	Incremental java compilation is an incubating feature.
	:app:preBuild UP-TO-DATE
	:app:preDebugBuild UP-TO-DATE
	:app:checkDebugManifest
	:app:preReleaseBuild UP-TO-DATE
	:app:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
	:app:prepareComAndroidSupportSupportV42301Library UP-TO-DATE
	:app:prepareComFacebookFbuiTextlayoutbuilderTextlayoutbuilder100Library UP-TO-DATE
	:app:prepareComFacebookFrescoDrawee130Library UP-TO-DATE
	:app:prepareComFacebookFrescoFbcore130Library UP-TO-DATE
	:app:prepareComFacebookFrescoFresco130Library UP-TO-DATE
	:app:prepareComFacebookFrescoImagepipeline130Library UP-TO-DATE
	:app:prepareComFacebookFrescoImagepipelineBase130Library UP-TO-DATE
	:app:prepareComFacebookFrescoImagepipelineOkhttp3130Library UP-TO-DATE
	:app:prepareComFacebookReactReactNative0482Library UP-TO-DATE
	:app:prepareComFacebookSoloaderSoloader010Library UP-TO-DATE
	:app:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
	:app:prepareDebugDependencies
	:app:compileDebugAidl UP-TO-DATE
	:app:compileDebugRenderscript UP-TO-DATE
	:app:generateDebugBuildConfig UP-TO-DATE
	:app:mergeDebugShaders UP-TO-DATE
	:app:compileDebugShaders UP-TO-DATE
	:app:generateDebugAssets UP-TO-DATE
	:app:mergeDebugAssets UP-TO-DATE
	:app:generateDebugResValues UP-TO-DATE
	:app:generateDebugResources UP-TO-DATE
	> Building 59% > :app:mergeDebugResources

and it stock in here...

how can i fix this?

**Comment by AinyFeng** [comment]
请问楼上的你的问题解决了吗？我和你遇到相同的问题，求帮助！！！！

**Comment by saeedvaziry** [comment]
@AinyFeng Could you say in English?

**Comment by AinyFeng** [comment]
I can speak a little English。

**Comment by AinyFeng** [comment]
The above problem was solved

**Comment by saeedvaziry** [comment]
@AinyFeng How can i fix this problem?

**Comment by AinyFeng** [comment]
enter the following command:
sudo apt-get install lib32z1
sudo apt-get install zlib1g:i386
sudo apt-get update
sudo apt-get install --yes lib32z1 lib32stdc ++ 6

**Comment by joaovitorsilvestre** [comment]
@AinyFeng It worked for me, thanks

**Comment by saeedvaziry** [comment]
@AinyFeng I am using windows...
Any solution for windows?

**Comment by SeuZeRicardo** [comment]
I'm having the same problem

I've seen some people running the following code:

`cd android && ./gradlew clean`
`cd .. && response-native run-android`

for some people it worked, for me no ... did you try these commands?

**Comment by saeedvaziry** [comment]
I solved this problem by clearing gradle cache

**Comment by FLabbaf97** [comment]
@saeedvaziry 
how do you clear gradle cache?

**Comment by viveksharmaui** [comment]
@FLabbaf97 
_

> gradlew cleanBuildCache

_
it is the command to clear Cache

**Comment by codyi96** [comment]
@AinyFeng thanks.

**Comment by quanpower** [comment]
@AinyFeng you saved me,thks!
