### ISSUE TITLE
RCTShadowText extreme memory consumption/leak

### ISSUE THREAD

**Issue by eneskaya** [facebook/react-native#15906]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

1. `react-native -v`: 0.46.3
2. `node -v`: v6.10.2
3. `npm -v`: 5.4.1
4. `yarn --version`: v0.27.5

Then, specify:

- Target Platform: iOS

- Development Operating System: 10.3.3

- Build tools: Xcode / Instruments

### Steps to Reproduce

For me this happens when reloading in the Simulator in development mode. Unfortunately I haven't found out how to exactly reproduce it yet.

### Expected Behavior

No memory leak

### Actual Behavior

I recognized, that sometimes, when reloading in the Simulator my MacBook is getting extremely loud. Then I had a look in Xcode and there it said that memory consumption is at 1,92 GB! Where usually is a number of around 200-300 MB, depending on what screen I have opened. Now, what I did is to transfer the debug session to Instruments and this is what I ended up with:

<img width="822" alt="bildschirmfoto 2017-09-12 um 13 08 02" src="https://user-images.githubusercontent.com/964419/30323270-d5e7cb20-97bc-11e7-8ec8-68db59a5a4a3.png">

It seems as RN keeps mallocing for something. But, idk what is going on here, as I'm no iOS developer.

<img width="1440" alt="bildschirmfoto 2017-09-12 um 13 21 49" src="https://user-images.githubusercontent.com/964419/30323457-93770fac-97bd-11e7-8398-c412f1458514.png">

I have the Instruments.trace saved, if anyone needs more details on that. 

**UPDATE:**

I have now a release version on my phone, and just experienced a freeze of the app with the phone getting _really warm_ (iPhone 6s). I believe, as no one seems to have experienced it here, that it may be caused by a defect plugin. Are there any recommended ways to find out what the culprit is? A further symptom is, whenever this happens in the release build, the images won't load.
See also #4730

**Comment by D1no** [comment]
To really investigate this, please create a quick reproduction (as a link to a repo) with the latest RN version and the min required code to test this behaviour. It is extremely difficult to isolate memory leaks.

For example, as you mentioned, a third party plugin could not properly unmount components or the interface is used in an incorrect way. That is impossible to figure out correctly from production code.

**Comment by eneskaya** [comment]
@dino yes we just had the same conversation. I will try and bring up a repro case, but it's hard for us to isolate this issue.
