### ISSUE TITLE
Unable to resolve module 'prop-types' while importing a module

### ISSUE THREAD

**Issue by eykjs** [facebook/react-native#15913]
### Environment

1. `react-native`: 0.44.3
2. `node`: 6.11.0
3. `npm`: 5.4.1
4. `yarn`: 1.0.0
5.  `react`: 16.0.0-alpha.6

- Target Platform: iOS

- Development Operating System: macOS 10.12.2

- Build tools: VS code , iOS Simulator by xcode

### Steps to Reproduce

1. Setting up a project with `react-native init <Projectname>`
2. Installing a 3rd party library like react-native-maps (by AirBnB) with `npm install --save react-native-maps`
3. Linking the library to react-native with `react-native link`
4. Importing a feature with `import MapView from 'react-native-maps';`
5. Starting the simulator with `react-native run-ios` and the server (if needed) with `npm start`

### Expected Behavior

No errors and the Map API ready for usage.

### Actual Behavior

I get an error which is saying that the app was "unable to resolve module 'prop-types' ... " and if i look into the console log, it's telling me that the module doesn't exist in the directory. But that's not true. The module definitely exists. 

This error appears with any module i try to install, not just with react-native-maps.

[Screenshots of the log and the error](https://imgur.com/a/0Df7f)

### Reproducible Demo

Not reproducible, because it's just an error on a few machines. (Because actually it should work perfectly and really don't know why it's not) ; I'm sorry

### UPDATE: 
After hours of testing i got it to work with React-Native version 0.42.0, ReactJS Version 15.4.2 and react-native-maps version 0.13.0. 
But it's not the perfect solution for me, so the question is still: Why isn't it working on newer versions?

**Comment by radko93** [comment]
Your problem is that `prop-types` is now a separate module (it was moved out of react package). Also, we don't support older RN versions, please test with the latest one and open another issue if this occurs.

**Comment by radko93** [comment]
@facebook-github-bot close
