### ISSUE TITLE
ACCESS_FINE_LOCATION Permission Denied via PermissionsAndroid on API 19

### ISSUE THREAD

**Issue by sircEUNHO** [facebook/react-native#15912]
1. `react-native -v`: 0.47.0
2. `node -v`: 7.0.0
3. `npm -v`: 3.10.6
4. `yarn --version`:

- Target Platform: Android

- Development Operating System: Windows 10 Pro 64 bit (Build 15063)

- Build tools:  Android Studios
- BUILD SDK : 25.0.1

Im trying to get the user location on my application but it always request's time out so i suspected that maybe its from permissions. But I tried PermissionsAndroid, It should prompt an alert asking for permission. It doesnt prompt any alert to allow permission thus it logs that the location permission is denied. 

```
try {
            const granted = await PermissionsAndroid.request(
            PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION,
                {
                    'title': 'Location Permission',
                    'message': 'Activeev needs to access your location.'
                }
            )
            console.log('here': granted);
            if (granted === PermissionsAndroid.RESULTS.GRANTED) {
                console.log("Location Permitted")
            } else {
                console.log("Location permission denied")
            }
        } catch (err) {
            console.warn(err)
        }

```
I am testing it on real device API 19, Huawei Honor 4C Model Number CHM-U01.

**Comment by amitsystech** [comment]
I am also facing the same issue on RN 0.49
Malformed calls from JS: field sizes are different.

**Comment by anonrig** [comment]
I'm having the same issue.

**Comment by rizwanahmed19** [comment]
+1

**Comment by dancomanlive** [comment]
I get Location permission denied as well.
