### ISSUE TITLE
PermissionsAndroid.RESULTS is undefined

### ISSUE THREAD

**Issue by AdrianZghibarta** [facebook/react-native#15910]
### Is this a bug report?

YES

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

NO

### Environment

1. `react-native -v`: 2.0.1 for react-native-cli and 0.38.0 for react-native
2. `node -v`: 7.7.3
3. `npm -v`: 4.1.2

Then, specify:

- Target Platform: Android
- Development Operating System: macOS Sierra 10.12.6 (16G29)
- Build tools: 24.0.3

### Steps to Reproduce
1. import PermissionsAndroid from 'react-native' library
2. try to get PermissionsAndroid.RESULTS.GRANTED
3. you will get that RESULTS is undefined, in PermissionsAndroid you will have only PERMISSIONS

### Expected Behavior

PermissionsAndroid will have PERMISSIONS + RESULTS fields

### Actual Behavior

PermissionsAndroid will have PERMISSIONS field without RESULTS field

### Reproducible Demo
None :)

**Comment by cmdshepard** [comment]
@AdrianZghibarta I think you're looking at the latest documentation - for 0.38.0, the API works a bit differently. Please [see the PermissionsAndroid documentation for 0.38](http://facebook.github.io/react-native/releases/0.38/docs/permissionsandroid.html). Thanks!

**Comment by AdrianZghibarta** [comment]
@cmdshepard yes man, my bad. Thanks a lot!
