### ISSUE TITLE
HeadlessJsTaskService is expected to run on UI thread

### ISSUE THREAD

**Issue by oriharel** [facebook/react-native#15915]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

1. `react-native -v`: react-native-cli: 2.0.1 react-native: 0.48.1
2. `node -v`: v7.5.0
3. `npm -v`: 5.3.0

- Target Platform: Android

- Development Operating System: macOS

- Build tools:

### Steps to Reproduce

1. Received a push notification
2. Starting a Service that extends HeadlessJsTaskService.java
3. App throws exception `com.facebook.react.bridge.AssertionException: Expected to run on UI thread!`

### Expected Behavior

I expect no UI thread requirement for a background service (same as Android native SDK)

### Actual Behavior

App throws an exception

**Comment by oriharel** [comment]
@chirag04 thanks for the note. However, as I understand, one of the common uses of this is performing tasks triggered by a push notification (or a job schedule). These are clearly not required to run in a UI thread as these are background activities.

**Comment by cmdshepard** [comment]
@oriharel according to the documentation, HeadlessJS is meant for tasks that are needed to be ran when your app in the *background*. In which case there are no operations on the main thread.

**Comment by oriharel** [comment]
Exactly. This is why I don't understand the "startTask must be triggered from the UI thread" requirement. Unless there is some limitation forcing the React context to be spawned from the UI thread.

**Comment by D1no** [comment]
That means you can not trigger a headless task from another headless task (threads of threads).

**Comment by oriharel** [comment]
In the documentation, it is clearly stated - 

> Now, whenever you start your service, e.g. as a periodic task or in response to some system event / broadcast, JS will spin up, run your task, then spin down.

Which means, even if a BroadcastReceiver is triggered, say from a push notification, the Headless task should be able to perform. 

But this is not the case, because there is an underline requirement that the onReactContextInitialized event handler will be called from the main thread (AKA UI thread). A requirement that most of the time not fulfilled (for example, when a user swiped out the app from the recent apps menu). 

So in fact - I DO consider this a bug and updated the form.

**Comment by haimyyy** [comment]
+1

**Comment by ycarmel** [comment]
+1

**Comment by blankg** [comment]
+1

**Comment by foghina** [comment]
I think there's a bit of confusion here. The "UI" thread is simply the "main" thread of an Android application. It's the thread that `Service`s naturally run on. For various reasons, the React context is always initialized on this thread, from where it spins off two others: JS and modules (IIRC). This is why `startTask` needs to be run on the UI/main thread, because it might need to initialize the context.

**Comment by oriharel** [comment]
You're right, everything I said about the UI thread actually reffers to the main thread. The Service "onStartCommand" does indeed happen on that thread. However, inside startTask there is an asynchronic call to create the React context. The callback that is triggered asynchronically is no longer on that thread. And that is already a private area so we can't override this in our inheriting class.

**Comment by oriharel** [comment]
An updated pull request [here](https://github.com/facebook/react-native/pull/15940).

**Comment by narodejesus** [comment]
+1

**Comment by oriharel** [comment]
Issue is now fixed and merged to React Native.

**Comment by sparsh** [comment]
I have used latest version i.e 0.48.4 of react-native, still, I don't see your changes in File HeadlessJsTaskService.java.

**Comment by oriharel** [comment]
I don't think it's released yet

**Comment by artemukolov** [comment]
Hi. I tried to fix this file manually, but i got another error.
![screen shot 2017-10-26 at 15 39 49](https://user-images.githubusercontent.com/11043617/32053439-0a9ec552-ba64-11e7-8b07-f72e2bfc6f16.png)

My code 

    BackgroundJob.register({
            jobKey: exactJobKey,
            job: () => process()
        });

        BackgroundJob.schedule({
            jobKey: exactJobKey,
            period: 900000,
            override: true,
            allowExecutionInForeground: true,
            persist: true
        });

**Comment by oriharel** [comment]
Check your AppRegistry in js code. You need to register a js file before you call it from Java

**Comment by oriharel** [comment]
Also check your HeadlessJsTaskService implementation in Java.  Make sure you return new HeadlessJsTaskConfig with a name  "exactJobKey".

**Comment by artemukolov** [comment]
Thanks. Looks like this issue is fixed in 0.49.5.
