### ISSUE TITLE
Integration With Existing Apps and Native module cannot be null 

### ISSUE THREAD

**Issue by minajm** [facebook/react-native#15925]
we want to integrate with swift app and when bundle it with react native app from server we get this error Native module cannot be null  on iPhone device.

version of react native is 0.44.2

how can we solve it?
tnx

**Comment by radko93** [comment]
We don't support older react-native versions. Please update and create a new issue.

**Comment by radko93** [comment]
@facebook-github-bot no-template

**Comment by minajm** [comment]
we install last version of react native and add react-navigation  library 
but we get  error Native module cannot be null on iPhone device again .

its important to our that use react-navigation  library .

can we solve it?
