### ISSUE TITLE
Requesting permission results into java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by msidlo** [facebook/react-native#15928]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

1. `react-native -v`: 0.45.1
2. `node -v`: 7.9.0
3. `npm -v`: 4.2.0
4. `yarn --version`: 0.23.2

Then, specify:

- Target Platform: Android

- Development Operating System: macOC Sierra

- Build tools: Android Studio

### Steps to Reproduce

1. ask for [permission](https://snack.expo.io/H1fzb9UqZ) just like in [documentation](https://facebook.github.io/react-native/docs/permissionsandroid.html)
2. press home button
3. open the App again and it crashes on this  [line](https://github.com/facebook/react-native/blob/51efaab1209a41254c90dcba596d49e3cbc2d925/ReactAndroid/src/main/java/com/facebook/react/modules/permissions/PermissionsModule.java#L119)
`if (results[0] == PackageManager.PERMISSION_GRANTED) {`

### Expected Behavior

Check results array before accessing it.
instead of 
`if (results[0] == PackageManager.PERMISSION_GRANTED) {`
something like
`if (results.length > 0 && results[0] == PackageManager.PERMISSION_GRANTED) {`

### Actual Behavior

On some devices app crashes after Requesting a permission on Android. App crashed on Xiaomi Redmi 4 Prime(Android 6.0.1), Lenovo C2 (Android 6.0), Sony Xperia Z3Compact (Android 6.0.1), Samsung Galaxy A3 (Android 7.0.). App is not crashing on Huawei P10 lite(Android 7) or Sony Xperia L1(Android 7). After crash, the app is restarted.

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by RafaelMagalhaesN** [comment]
PR #16507 @msidlo tnks for the solution ;)
