### ISSUE TITLE
react-native-git-upgrade always downgrade react dependency to 16.0.0-alpha.12

### ISSUE THREAD

**Issue by pocesar** [facebook/react-native#15926]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

1. `react-native -v`: 0.48.2
2. `node -v`: 8.4.0
3. `npm -v`: 4.6.1

Then, specify:

- Target Platform: Android

- Development Operating System: Windows 10 x64

### Steps to Reproduce

1. react-native-git-upgrade on a project with react@16.0.0-beta.5 or greater

### Expected Behavior

Keep current version that matches fresh react-native init, that is 16.0.0-beta.5

### Actual Behavior

It will try to install 16.0.0-alpha.12, whatever the version of react already installed. this leads to inconsistencies and problems like #14209 since different tools might have different versions installed (like react-test-renderer)

**Comment by dantman** [comment]
> It will try to install 16.0.0-alpha.12, whatever the version of react already installed. this leads to inconsistencies and problems like #14209 since different tools might have different versions installed (like react-test-renderer)

`react-test-renderer` should be pinned to the same version of react that react-native uses, the version of that package is directly linked to the version of `react` you use.

**Comment by pocesar** [comment]
I want to use `react-test-renderer@16.0.0-rc.3` and I won't be able to because of `react-native-git-upgrade` keep downgrading react?

**Comment by dantman** [comment]
@pocesar Using the latest version of `react-test-renderer` will not get you extra features, there is no purpose in trying to use a newer version of it than you need. The version of `react-test-renderer` you use should be the same as the version of `react` that is in use.

So you should be using `react-test-renderer@16.0.0-alpha.12` with `react@16.0.0-alpha.12`. You shouldn't be trying to upgrade `react` to a different version than the version of `react` that `react-native` is built to be used with. The two libraries are intertwined and using the wrong version isn't guaranteed to work at all.

**Comment by pocesar** [comment]
I've been using react 16.0.0-rc.* with RN since 0.47 without problems, not sure what your point is
