### ISSUE TITLE
TouchableOpacity can't call onPress props.

### ISSUE THREAD

**Issue by Kaelzzs** [facebook/react-native#15927]
### Is this a bug report?

TouchableOpacity can't call onPress method in iPhone 6sP.
When TouchableOpacity cantains a View ,
The View contains two View(top and bottom)
top can call onPress but bottom can't,in iPhone 6sP

(write your answer here)

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.)

### Environment

1. `react-native -0.48.1`:
2. `node -v8.1.4`:
3. `npm -5.4.1`:
4. `yarn --v0.23.4`:

Then, specify:

- Target Platform:

- Development Operating System:

- Build tools:

### Steps to Reproduce

(Write your steps here:)

1.A `View` ,inside ,top is `Text`,bottom is `View`
2. `TouchableOpacity` contains the `View`,not defined `TouchableOpacity`'s `style` 
3.iPhone 6p:touch bottom `View` is normal,
but,iPhone 6s P:touch bottom `View` is can't call onPress

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by radko93** [comment]
@facebook-github-bot needs-repro

**Comment by Norfeldt** [comment]
I tumbling a bit around. As oppose to the parent component you are not allowed to use `this`. So it should look like this:

```
const RNPureComponent = ({ onPress }) => (
  <TouchableOpacity onPress={onPress}>
    <.../>
  </TouchableOpacity>
)

export default RNPureComponent
```
