### ISSUE TITLE
`react-native bundle` can't resolve symlink in `node_modules` and doesn't provide `--root` options 

### ISSUE THREAD

**Issue by xareelee** [facebook/react-native#15921]
### Is this a bug report?

I think this is a bug.

I use [lerna](https://lernajs.io/) for monorepo. The following is my project structure

```
monorepo/
  |-- lerna.json
  |-- package.json
  |-- ...
  |-- packages/
  |      |-- foo-module/
  |            |-- package.json
  |            |-- ...
  |-- apps/
         |-- my-react-native-app/
               |-- package.json
               |-- node_modules/
               |      |-- foo-module/  # this is a symlink to ../../../packages/foo-modules
               |-- ...
```

I have a react-native project under `apps/my-react-native-app`, and it use a local module `foo-module` by lerna with yarn symlink.

For development, I need to add `--root` to `react-native start` resolve the symlink module correctly:

```
$ react-native start --root ../../packages
```

Now I have to pack the js bundle, but adding `--root` to `react-native bundle` doesn't work:

```
$ react-native bundle --platform android ...{other flags}...  --root ../../packages

Scanning 966 folders for symlinks in {path_to}/monorepo/apps/my-react-native-app/node_modules (10ms)

  error: unknown option `--root'
```

I can't bundle my rn app directly without `--root` (the `foo-module` can't be found):

```
$ react-native bundle --platform android ...{other flags}...

Scanning 965 folders for symlinks in /Users/Xaree/Development/ofo/ofo-monorepo/apps/ofoBikeIntl/node_modules (9ms)
Scanning 965 folders for symlinks in /Users/Xaree/Development/ofo/ofo-monorepo/apps/ofoBikeIntl/node_modules (9ms)
Loading dependency graph, done.

Unable to resolve module `foo-module` from `{path_to_file}`: Module does not exist in the module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.

```

The `react-native bundle` lacks the `--root` option.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

YES

### Environment

1. `react-native -v`: 0.46.4 (cli: 2.0.1)
2. `node -v`: v8.3.0
3. `npm -v`: 5.4.1
4. `yarn --version`: 0.28.4

Then, specify:

- Target Platform: Android

- Development Operating System: macOS 10.12.6

- Build tools: react-native-cli

### Steps to Reproduce

(please see above)

### Expected Behavior

(please see above)

### Actual Behavior

(please see above)

**Comment by deepsweet** [comment]
Almost the same here, monorepo where one of the packages is React Native project and it should require another "neighbor" package.

As far as I understand internal React Native Packager can't handle any files from "outside" of its root. Symlinks and [babel-plugin-module-resolver](https://github.com/tleunen/babel-plugin-module-resolver) doesn't work.

Any soultion?

**Comment by deepsweet** [comment]
https://github.com/facebook/metro-bundler/issues/1

**Comment by mustafaskir** [comment]
i have the same issue
because of i change entry point to index.android.js
so the solution is to change your entry point
or simply change name of index.js in project root Directory to index.android.js
