### ISSUE TITLE
[Android] App crash on android search assistant opening

### ISSUE THREAD

**Issue by sooth-sayer** [facebook/react-native#15932]
### Is this a bug report?
Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?
Yes

### Environment

1. `react-native -v`: 0.48.3
2. `node -v`: 7.7.3
3. `yarn --version`: 0.23.2

Then, specify:

- Target Platform:
Android

- Development Operating System:
Mac OS X

- Build tools:
Android build tools v23.0.1
### Steps to Reproduce

1. Open android search assistant when modal is visible

### Actual Behavior

App crashes

### Reproducible Demo
[Simple app that can help to reproduce](https://github.com/sooth-sayer/RNModalCrash)

[Related issue](https://github.com/facebook/react-native/issues/13201)

**Comment by radko93** [comment]
Hey, please reproduce it on latest RN version.

**Comment by sooth-sayer** [comment]
@radko93 I updated the demo app. Now RN 0.48.3 is used

**Comment by LironErman** [comment]
Still happening, RN 0.49.5

**Comment by Shinichi52** [comment]
Happening for me using 0.47.1

**Comment by DanNi0130** [comment]
Happening for me using 0.48.4

**Comment by yaronlevi** [comment]
Still happen in 0.51

**Comment by maxkomarychev** [comment]
True in 0.50.4 as well

**Comment by knicefire** [comment]
same thing on 0.52

**Comment by pzawadzki82** [comment]
Is there any workaround ?

**Comment by ramirobg94** [comment]
same error :/

**Comment by TheBlackHacker** [comment]
Did anyone fixed it?

**Comment by zaiz91** [comment]
This Bug still exist in the newest version of RN!

**Comment by sandeep0607** [comment]
still in react-native 0.55.4

**Comment by padampadam** [comment]
still happening in RN 0.56.0
