### ISSUE TITLE
Service started on different address than Wifi is

### ISSUE THREAD

**Issue by jurosh** [facebook/react-native#15933]
### Is this a bug report?

Yes.

### Environment

react-native-cli: 2.0.1
react-native: 0.47.2
NodeJs v7.6.0
yarn 1.0.1

on Windows10

### Steps to Reproduce

1. `yarn start` in project directory
2. Try to scan QR code
3. It's not working because script used incorrect IP address (of virtualbox adapter)

### Expected Behavior

Script should know which IP is Wifi connection or ask which adapter to use.

At least would be good to have documented option how to configure which adapter should be used manually.

### Actual Behavior

It takes incorrect IP address.

From adapters:
- VirtualBox Host-Only Network
- Wi-Fi (active Wifi connection which should be used)

**Comment by radko93** [comment]
I don't really get what's the real problem. Why is scanning a QR code related to react-native? Is it really a bug in react native. Seems it's only related to your installation.

**Comment by radko93** [comment]
@facebook-github-bot needs-repro

**Comment by jurosh** [comment]
@radko93 it's not just me, also saw that few others having the same issue. It's not about QR code - I didn't mentioned that. Whole service (npm start) started on incorrect adapter (= on incorrect IP address), so it's not possible to connect - even when I use correct IP address (of Wifi adapter).

That this might happen to anyone who is using multiple network adapters.

I've hotfixed this by manually setting Network interface metrics in Network adapters settings - but it's possible that other's might deal with same issue.

**Comment by jurosh** [comment]
This looks to be related https://github.com/react-community/create-react-native-app/issues/60 - not sure why it was closed, but seems like that just happened to me yesterday.

If there will be no resolution, probably we might include hotfix from last comment in documentation ? (that hotfix helped me)

**Comment by radko93** [comment]
If you think this will help anyone, please send a PR.
