### ISSUE TITLE
change 'value' props by state can't trigger  'onChange' of TextInput

### ISSUE THREAD

**Issue by huanghaodong** [facebook/react-native#15935]
render(){
   return <TextInput
                 value={this.state.data}
                 onChange={()=>{alert('trigger!')}}
             >
             </TextIput>
}

componentDidMount(){
   setTimeOut(()=>{
      this.setState({
         data:'change'
      })
   },3000)
}

**Comment by ubatin** [comment]
@facebook-github-bot stack-overflow
