### ISSUE TITLE
'RCTDevMenu.h' file not found,in RCTTVRemoteHandler.m

### ISSUE THREAD

**Issue by Kaelzzs** [facebook/react-native#15936]
### Is this a bug report?

react-native/node_modules/react-native/React/Base/RCTTVRemoteHandler.m:25:9: fatal error: 'RCTDevMenu.h' file not found
#import "RCTDevMenu.h"
        ^~~~~~~~~~~~~~
1 error generated.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.)

### Environment

1. `react-native -v`:0.48.3
2. `node -v`:v8.2.1
3. `npm -v`:5.4.1
4. `yarn --version`:0.23.4

Then, specify:

- Target Platform:iOS

- Development Operating System:Mac os 10.12.6

- Build tools:Xcode

### Steps to Reproduce

(Write your steps here:)
1. pod install
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

inhibit_all_warnings!

target "RNOC" do

pod 'Yoga',  :path => '../react-native/node_modules/react-native/ReactCommon/yoga'
pod 'React', :path => '../react-native/node_modules/react-native', :subspecs => [
  'RCTImage',
  'RCTNetwork',
  'RCTText',
  'RCTWebSocket',
  # 添加其他你想在工程中使用的依赖。
]

end

2. run~

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by Kaelzzs** [comment]
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

inhibit_all_warnings!

target "RNOC" do

pod 'Yoga',  :path => './react-native/node_modules/react-native/ReactCommon/yoga'
pod 'React', :path => './react-native/node_modules/react-native', :subspecs => 
[
  'Core', 
  'RCTText',
  'RCTNetwork',
  'RCTWebSocket', 
]

end
```

**Comment by Kaelzzs** [comment]
miss the `RCTDevMenu.h`

**Comment by Kaelzzs** [comment]
node_modules/react-native/React/Modules

old react-native version had the `RCTDevMenu.h `,
but now, react-native 0.48.3 not cantains .

**Comment by dkstar88** [comment]
check if you have 'DevSupport' added, see
#15775 
https://github.com/facebook/react-native/issues/15775#issuecomment-327971300

**Comment by samuela** [comment]
Just came across this exact issue. Adding `DevSupport`to the subspecs list did the trick.

**Comment by Kaelzzs** [comment]
`DevSupport` is halpful

**Comment by Kaelzzs** [comment]
`pod 'React', :path => './react-native/node_modules/react-native', :subspecs => 
[
  'Core', 
  'DevSupport',
  'RCTText',
  'RCTNetwork',
  'RCTWebSocket', 
]`

**Comment by MaheshNandam** [comment]
Thanks @Kaelzzs , 

pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'Core', 'DevSupport', 'RCTText', 'RCTNetwork', 'RCTWebSocket'
  ]

This works for me.
