### ISSUE TITLE
[Android] React native views not arranged properly inside custom ViewGroup

### ISSUE THREAD

**Issue by rsreejithkrishnan** [facebook/react-native#15939]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

1. `react-native -v`: 0.48.3
2. `node -v`: v8.4.0
3. `npm -v`: 5.4.1
4. `yarn --version`: 0.21.3

Then, specify:

- Target Platform: Android

- Development Operating System: macOS

- Build tools: Android studio

### Steps to Reproduce

Example: Create a LinearLayout native UI component.

``` Java
public class RNLinearLayoutManager extends ViewGroupManager<LinearLayout> {

    @Override
    public String getName() {
        return "RNLinearLayout";
    }

    @Override
    protected LinearLayout createViewInstance(ThemedReactContext reactContext) {
        LinearLayout layout = new LinearLayout(reactContext);
        layout.setOrientation(LinearLayout.VERTICAL);
        return layout;
    }

}
```

``` Javascript
const LinearLayout = requireNativeComponent('RNLinearLayout', {
  name: 'LinearLayout',
  propTypes: {
    ...View.propTypes
  }
}, {
  nativeOnly: {
    nativeBackgroundAndroid: true,
    nativeForegroundAndroid: true
  }
})

export default class RNTest extends Component {
  render() {
    return (
      <LinearLayout style={{flex: 1}}>
        <Text>Linear Layout demo</Text>
        <Text>The below view should be arranged in a row</Text>
        <View style={{flexDirection: 'row', flex: 1}}>
          <Text>Column 1</Text>
          <Text>Column 2</Text>
        </View>
        <Text>But it is arranged in two different rows</Text>
      </LinearLayout>
    );
  }
}
```

### Expected Behavior

![image](https://user-images.githubusercontent.com/31202232/30413189-4654a04e-993a-11e7-8ccb-5879efc04aae.png)

Text Column 1 and Column 2 should be arranged in same line as shown above

### Actual Behavior

![image](https://user-images.githubusercontent.com/31202232/30413165-2429fa5a-993a-11e7-8623-69acb82a8e74.png)

Text Column 1 and Column 2 were arranged in 2 lines

### Reproducible Demo

https://github.com/rsreejithkrishnan/RNLinearLayoutTest

**Comment by radko93** [comment]
@facebook-github-bot label Android
