### ISSUE TITLE
no native API  instruction

### ISSUE THREAD

**Issue by yyTopfounder** [facebook/react-native#15931]
I can't get a detailed description of native API(for example：ReactRootView and ReactInstanceManager) from react-native's official website.Don't they belong to react-native?Where can I see a detailed description of them?

**Comment by radko93** [comment]
I guess they are not exposed in the documentation. You can look it at the code https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/ReactRootView.java

**Comment by radko93** [comment]
@facebook-github-bot label Documentation

**Comment by radko93** [comment]
@facebook-github-bot close
