### ISSUE TITLE
Potential leak on FlatList + images

### ISSUE THREAD

**Issue by mfrachet** [facebook/react-native#15930]
### Is this a bug report?

Yes, it seems so

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

1. `react-native -v`: 
- react-native-cli: 2.0.1
- react-native: 0.47.2
2. `node -v`: v8.4.0
3. `npm -v`: v5.3.0
4. `yarn --version`: v1.0.0

- Target Platform: Android

- Development Operating System: macOS Sierra v10.12.6 

### Steps to Reproduce

(Write your steps here:)

1. use a low memory device (128mb for example)
2. create a FlatList with "infinite" images
3. See the app crash and android monitor 

### Expected Behavior

Image are well garbaged while scrolling FlatList (recycle view + fresco disk caching ?)

### Actual Behavior

It 'actually throws OOM errors :

<img width="849" alt="capture d ecran 2017-09-13 a 14 31 06" src="https://user-images.githubusercontent.com/3874873/30377508-3c1d4810-9890-11e7-99a5-3a246623cfb8.png">

Here's the Android monitoring shot while I m playing with the app. We can see that the memory is always jumping but rarely dropping, and so forth, OOM at some moment

![rn](https://user-images.githubusercontent.com/3874873/30377527-4dc79f98-9890-11e7-99ee-1abb9256e01e.gif)

And here's what I can see from the Eclipse Memory Analyzer stuff :

![image quand tu nous tiens](https://user-images.githubusercontent.com/3874873/30377538-5c81176c-9890-11e7-86f3-7d32c783266c.gif)

### Reproducible Demo

-	Clone the following repo : https://github.com/mfrachet/potentialLeak
-	Cd && npm i
-	React-native run-android (on real device for myself)

**Comment by RobbyWH** [comment]
I encountered the same problem, any solution for this problem ?

**Comment by mfrachet** [comment]
Just a little up to not forget :/

**Comment by irwing-reza** [comment]
Any updates?

**Comment by kesha-antonov** [comment]
+

**Comment by ngoducduy** [comment]
Any solution for this ?

**Comment by suetming** [comment]
Any solution for this ?

**Comment by nico1510** [comment]
I'm seeing this too 🙁

**Comment by cglacet** [comment]
Its been two months, did you had any feedback on this?

**Comment by cglacet** [comment]
Isn't it related to [this](https://github.com/jhen0409/react-native-debugger/issues/147). I haven't ran your code, but mine had similar issue and stoping remote debugging worked.

**Comment by mfrachet** [comment]
We have this bug in production, it's simply a reproduction in dev mode, but it exists for us in production

**Comment by RafaelMagalhaesN** [comment]
Last month I had the same problem with the app in production.

I found a momentary solution (workaround?) when I added the property 'removeClippedSubviews' in FlatList.

`<FlatList
        data={this.state.dataSet}
        keyExtractor={this._keyExtractor}
        renderItem={this._renderItem}
        removeClippedSubviews />`

**Comment by lhfiii** [comment]
@RafaelMagalhaesN tried, but no help

**Comment by pavanmehta91** [comment]
Any solutions for this yet? Can anybody explain why it's happening despite using flatlist? Does flatlist not automatically garbage collect or free the memory of the images not in the view?

**Comment by pavanmehta91** [comment]
according to the docs removeClippedSubviews is by default true for FlatList

**Comment by tracinah** [comment]
Nope

**Comment by pavanmehta91** [comment]
Okay

**Comment by pavanmehta91** [comment]
I keep seeing 
`02-12 15:48:48.612 32155-32155/com.starbuds I/Choreographer: Skipped 49 frames!  The application may be doing too much work on its main thread.`
in LogCat when FlatList with images is being viewed.
Here's the code for my Flatlist
`              <FlatList
                data={this.state.posts}
                numColumns={2}
                keyExtractor={this._keyExtractor}
                ListFooterComponent={this.renderFooter}
                onEndReachedThreshold={1}
                renderItem={this.renderGridItem}
                initialNumToRender={6}
              />`
and renderGridItem method
`  renderGridItem = ({ item }) => {
    return <GridItem item={item} />;
`
and GridItem component

`
class GridItem extends React.PureComponent {
  render(){
    const {item} = this.props;
      return (
        <TouchableOpacity
          onPress={() => {
            this.openPostDetails(item);
          }}
          activeOpacity={0.9}
        >
          <View style={ProfileStyle.imageInGrid} key={item._id}>
            <View
              style={{
                zIndex: 10,
                flex: 1,
                top: ProfileStyle.imageInGrid.height - 22,
                alignSelf: "flex-end"
              }}
            >
              <Image source={Images.videoIcon} style={ProfileStyle.videoIcon} />
            </View>
            <CachedImage
              style={ProfileStyle.imageInGrid}
              source={{ uri: item.medias[0].thumbnail }}
              defaultSource={Images.placeHolder}
              fallbackSource={Images.placeHolder}
              activityIndicatorProps={{ display: "none", opacity: 0 }}
            />
          </View>
        </TouchableOpacity>
      );
  }
}
`

**Comment by brentvatne** [comment]
use `removeClippedSubviews`, it does not defualt to `true` for FlatList or SectionList, only for ListView

**Comment by kelset** [comment]
(FYI, refer to #13413 for followup on this)

**Comment by alzalabany** [comment]
this is still active on .54, adding an Image to Flatlist cause huge memory leak on android.
