### ISSUE TITLE
How you support orientation changes on FlatList without changing columns on the fly?

### ISSUE THREAD

**Issue by ferrannp** [facebook/react-native#15944]
I remember using `FlatList` when it didn't have this check:

```js
invariant(
   nextProps.numColumns === this.props.numColumns,
   'Changing numColumns on the fly is not supported. Change the key prop on FlatList when ' +
   'changing the number of columns to force a fresh render of the component.',
 );
```

So basically I wrapped the `FlatList` in a `View` with `onLayout` prop, and when the width of screen changes (from portrait <-> layout) I would change the number of columns (and some other calculations). This is not allowed now, so what it forces me to do is changing the `key` prop of the `FlatList`... This renders a completely new list, **losing the scroll position** and with a big delay even in production.

Any workarounds, thoughts ?

**Comment by nvme978** [comment]
Did you figure out how to do it?

**Comment by Guihgo** [comment]
import React, { Component } from 'react';
import {
  Dimensions,
  Alert,
  FlatList,
  StyleSheet,
  Text,
  View
} from 'react-native';

import GridView from 'react-native-super-grid';

import LinearGradientBg from './../../mComponentes/linearGradientBg';
import NumeroCirculado from './../../mComponentes/botaoNumeroCirculado';

export default class Jogar extends Component<{}> {

  prepData = () => {
    let data = []
    for (let i = 1; i <= 30; i++) {
      data.push({
        key: i,
        checked: false,
        n: i
      })
    }
    return data
  }

  renderItem = ({ item }) => {
     return (
       <View style={styles.botaoNumeroCirculado}><NumeroCirculado>{item.n}</NumeroCirculado></View>
     )
   }

  onLayout(e) {
    const {width, height} = Dimensions.get('window');

    this.setState({
        numColumnsBotoesNumeroCirculado: parseInt(width/this.espacoUmBotao)
    });
  }

  constructor(props) {
    super(props);

    const {width, height} = Dimensions.get('window');
    let botaoNumeroCirculadoWidth = 45;
    let botaoNumeroCirculadoMargin = 10;
    this.espacoUmBotao = (2*botaoNumeroCirculadoMargin)+botaoNumeroCirculadoWidth;

    let mNumerosData = [];
    for(let i=1; i<=30; i++) {
      let numero = {
        checked: false,
        n: i
      };
      mNumerosData.push(numero);
    }

    this.state = {
      numerosData: mNumerosData,
      numColumnsBotoesNumeroCirculado: 1
    }
  }

  render() {
    const { params } = this.props.navigation.state;
    //params.data.titulo

    return (
      <LinearGradientBg>
        <View style={styles.container} onLayout={this.onLayout.bind(this)}>
          <Text style={styles.tvEscolhaOsNumeros}>Escolha seus números</Text>
        </View>
        <FlatList
          data={this.prepData()}
          renderItem={this.renderItem}
          numColumns={this.state.numColumnsBotoesNumeroCirculado}
          initialNumToRender={5}
        />
      </LinearGradientBg>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    padding: 15
  },
  tvEscolhaOsNumeros: {
    color: '#FFF',
    fontSize: 25,
    fontFamily: 'Roboto-Thin'
  },
  botaoNumeroCirculado: {
    margin: 10
  }
});

**Comment by cyphire** [comment]
Having same issue.  Don't understand why, I am re-rendering the child with the FlatList with a new number of columns.  Is there some magic to work around this?

**Comment by xstable** [comment]
Sombody suggest do use `extraData` property of Flatlist to let Flatlist notice, that something changed. 

But this didn't work for me, here is what work for me: 
Use `key={this.state.orientation}` while orientation e.g is "portrait" or "landscape"... it can be everything you want, but it had to change, if orientation changed.
