### ISSUE TITLE
babel-preset-react-native has two versions on npm that are not in this repo

### ISSUE THREAD

**Issue by hawkrives** [facebook/react-native#15949]
### Is this a bug report?

Kinda?

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes. 

### What is happening?

The npm package for [babel-preset-react-native](https://www.npmjs.com/package/babel-preset-react-native) recently published v3.0.2, and just published v4.0.0 a few minutes ago. However, the [package in this repository](https://github.com/facebook/react-native/tree/master/babel-preset) is still at v3.0.1, and hasn't been updated for around three weeks. 

Has the package source moved? I'm highly curious about what changed to mandate a major version bump. 

Thanks, and have a great week!

**Comment by radko93** [comment]
@facebook-github-bot label Tooling

**Comment by hawkrives** [comment]
This issue has been resolved, as the source code for v4.0.0 has been uploaded.
