### ISSUE TITLE
'FlatList' - React.createElement: type is invalid -- expected a string (for built-in components) or a class/function

### ISSUE THREAD

**Issue by anvesh523** [facebook/react-native#15948]
## Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in

While I'm using **FlatList** in my code, I'm getting this error. If I remove the **FlatList** code, the app is working fine. I imported **FlastList** in my code too and I'm export the container.

import { ListView, Text, FlatList } from 'react-native';

render() {
    return (

      <FlatList
        data={[{ key: 'a' }, { key: 'b' }]}
        renderItem={({ item }) => <Text>{item.key}</Text>}
      />

    );
  }

export default connect(mapStateToProps, mapDispatchToProps)(HistoryViewport);

Please give some solution, where I'm doing mistake! What I forgot to export the component from the file?

![2017-09-14_17-31-12](https://user-images.githubusercontent.com/10726276/30428878-e1835532-9972-11e7-94de-05c01703226a.png)

**Comment by radko93** [comment]
@facebook-github-bot stack-overflow

**Comment by NawazKhanMd** [comment]
@anvesh523  Hai dude facing the issue, have you found any work around

**Comment by marcodefreitas** [comment]
@anvesh523 @NawazKhanMd What is your RN version?

I had that error when trying to use the FlatList with RN 0.42

**Comment by courage-liberty** [comment]
@anvesh523 
Was this settled?
I suffer from the same problem, too.

**Comment by anvesh523** [comment]
@marcodefreitas  I'm using latest version.

@NawazKhanMd  @courage-liberty  I didn't find any solution for now.

**Comment by courage-liberty** [comment]
@anvesh523 
In the case of me, the problem is like the expo client.

**Comment by anvesh523** [comment]
@courage-liberty  I was testing on emulator and mobile. On both devices it's not working.

**Comment by courage-liberty** [comment]
@anvesh523 
So.
Though because there was information to be good with the emulator, my problem may be different.

**Comment by NawazKhanMd** [comment]
Guys i think theres a issue with react-native 0.42 and FlatList, I was in a development mode so choose the List component of native-base which was already added to the project 

now am using List of native-base instead of FlatList of React-native on same mentioned version of react-native

**Comment by courage-liberty** [comment]
@anvesh523 
I was able to work in the simulator.（Windows/Android）

There is information to be settled by version up.
https://github.com/facebook/react-native/issues/16090#issuecomment-332139111

For your information.

**Comment by NawazKhanMd** [comment]
or if u are using 0.42 of react-native use ListView  . ListView of 0.42 is changed to FlatList of 0.48

**Comment by courage-liberty** [comment]
Person of expo saying "repairs it early" in Slack.
I wait for a while.

**Comment by TarasDumych** [comment]
Try this:
`import FlatList from 'FlatList';`

It works for me.
