### ISSUE TITLE
[iOS]: Time out waiting for modules to be invalidated!

### ISSUE THREAD

**Issue by ohflying** [facebook/react-native#15941]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

1. `react-native -v`: 0.48.3
2. `node -v`: v6.8.1
3. `npm -v`: 3.10.8
4. `yarn --version`:

Then, specify:

- Target Platform: iOS

- Development Operating System: macOS 10.12.4

- Build tools: Xcode

### Steps to Reproduce

(Write your steps here:)

1. create a component, like this
``` javascript
class Root extends React.Component {
    render() {
        return (
            <View style={{display: 'none'}}>
                <Text>这是一个测试!</Text>
            </View>
        );
    }
}
```
If the '\<Text\>' contains any Chinese characters, an exception is thrown.
### Actual Behavior

(Write what happened. Add screenshots!)
![image](https://user-images.githubusercontent.com/21188038/30419553-568ac3d8-9969-11e7-9858-e439d028ce3a.png)

**Comment by sumedhaverma** [comment]
I am also facing the same issue. Are you able to solve it?
Please let me know here.

**Comment by 447491480** [comment]
{display: 'none'} cause this bug

**Comment by gibson** [comment]
I dont use display: 'none' and has this problem

**Comment by mobitar** [comment]
In my case the issue was using `react-native-vector-icons`, then display a component that has an icon and then removing the component from display really quickly.

i.e

```
<Icon name={"icon"} size={25} color={color} />
```

Seems like it might be a memory access issue where where the component is loaded, the icon begins loading, the component is removed, the icon finishes loading, and that error occurs. That's just my theory.

**Comment by silentmaker** [comment]
I am having the same problem. It just happened, still don't know what caused it or how to solve it.
Restart everything can only make things right once, after one reload all components disappear.

Really hope that someone can tell me what cause this and how to solve it.

**Comment by illl48** [comment]
I am also facing the same issue. It happens when the TextInput is blurred and the orientation is in landscape mode.

**Comment by messense** [comment]
Same issue here, I am also using `react-native-vector-icons`. Maybe @oblador can help us here?

**Comment by messense** [comment]
Added some NSLog and found that it's `UIManager' invalidate timed out.

**Comment by laurent22** [comment]
@javache, it seems this bug (or at least the error message) was introduced in this commit: https://github.com/facebook/react-native/commit/7b770556ac6eb60094bdf59bfd14876b6e2a1307

**Comment by Mubashirkhan** [comment]
was anyone able to fix this issue i'm facing the same issue on iOS everything works fine on android

**Comment by kamelj** [comment]
Remove **letterSpacing** if you use it on styles for non English it's will solved the issue, 
It's work for me =)
