### ISSUE TITLE
Rendering an absolutely positioned item with a sibling in a flex container breaks the layout on iOS

### ISSUE THREAD

**Issue by iremlopsum** [facebook/react-native#15942]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

1. `react-native -v`: 0.48.1
2. `node -v`: 6.9.5
3. `npm -v`: 4.6.1

- Target Platform: iOS and Android
- Development Operating System: Linux (elementaryOS Loki)

The issue is specific to iOS

### Steps to Reproduce

```
<View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
  <View style={{width: widthOfTheContainer, height: heightOfTheContainer, position: 'absolute', left: 0, top: 0}} />
  <Icon />
</View>
```

### Expected Behavior

This is how it works on Android. Which makes sense. I have an absolute element (yellow), and it's positioned `left: 0, top: 0`.

![androidtab](https://user-images.githubusercontent.com/8178748/30419611-aa8f6738-993f-11e7-87d3-c01210d0fd55.png)

### Actual Behavior

This is how it works on iOS. I do not understand why it doesn't actually start from `left: 0`, but instead starts from where the sibling starts. It works fine if I remove ` alignItems: 'center', justifyContent: 'center'` from the parent

![iostab](https://user-images.githubusercontent.com/8178748/30419644-c8101e38-993f-11e7-9a1b-7cc3fcaf5008.png)

Any ideas what is causing it? Or do I just have to have a weird workaround for iOS?

**Comment by shergin** [comment]
@iremlopsum Could you please create a Snack illustrating your problem?

**Comment by vaibhavkuliza** [comment]
Any idea if this was fixed ? Still getting the same issue in iOS for 0.53
