### ISSUE TITLE
[ActionSheetIOS] support image in showShareActionSheetWithOptions

### ISSUE THREAD

**Issue by chirag04** [facebook/react-native#1594]
As per the official documentation it seems image can be passed to activity view. 

There is a third party implementation of this component already here: https://github.com/naoufal/react-native-activity-view. Here you can pass imageUrl or image.

If there is a standard way to passing react image component to objective-c modules, we can use that instead two options like image and imageUrl.

Happy to PR if someone point me to right direction with passing image component to objective-c.

cc @tadeuzagallo . Going by the history seems like you are associated with this component.

**Comment by sahrens** [comment]
It should be pretty straight-forward to just pass a URL to the native component via a new property.  If you specify the type of the property as `UIImage`, then RCTConvert will automatically parse the string and convert it into a UIImage, whether it's a network url or a local static image file path:

https://github.com/facebook/react-native/blob/master/React/Base/RCTConvert.m#L613

Then in the native code you can plug in the resulting UIImage object wherever you want.

**Comment by sahrens** [comment]
I'm going to close this out assuming you'll put up a PR - if you have any more questions, feel free to ask here or reach out directly in the community group or IRC channel.

**Comment by chirag04** [comment]
@sahrens I was able to get the static image working by adding image option. 
``[RCTConvert UIImage: image]``

However when i pass image as url string, RCTConvert is not able to convert it to an UIImage. eg: 
``image: 'https://www.facebook.com/images/fb_icon_325x325.png'``

Seems like it expects a data: prefix to fetch network image. Not sure if this is a bug.
https://github.com/facebook/react-native/blob/master/React/Base/RCTConvert.m#L633

**Comment by tadeuzagallo** [comment]
The `data:` prefix is for base64 encoded images. For network images you need to use `RCTImageDownloader`.

**Comment by chirag04** [comment]
So, we should support two options like ``image`` and ``imageUrl``?

This is what we do exactly here: https://github.com/naoufal/react-native-activity-view

**Comment by tadeuzagallo** [comment]
```objc
- (void)setImage:(NSString *)image
{
  _image = [RCTConvert UIImage:image];
  if (!_image) {
    // Download the image
  }
}
```

**Comment by chirag04** [comment]
@tadeuzagallo That makes sense. I was reading through the code of RCTImageDownloader which seems to be using blocks(async). I'm new to ios and this seems to get little complicated here.

Mind reopening this issue?

**Comment by chirag04** [comment]
@javache Would this be something of interest at fb?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/actionsheetios-support-image-in-showshareactionsheetwithoptions

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
