### ISSUE TITLE
The scrollview breaks on  iOS 10 when using RN-0.48

### ISSUE THREAD

**Issue by gameboyVito** [facebook/react-native#15957]
### Error:

> ***Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[RCTCustomScrollView setContentInsetAdjustmentBehavior:]: unrecognized selector sent to instance 0x7ffab9891a00'***

### Reproduce:
Build your app by XCode9-GM, then run it on your iOS10 device or below version.

### Env:
- `Device - iOS 10.3.1`
- `XCode 9.0 (9A235)`
- `react-native - 0.48.3`

**Comment by janicduplessis** [comment]
@skevy Any idea what could cause this? All calls seem to be wrapped with `[_scrollView respondsToSelector:@selector(setContentInsetAdjustmentBehavior:)]`

**Comment by gameboyVito** [comment]
I think this commit #6e28b39 breaks the code. Any update?

**Comment by suetming** [comment]
I met the same problem. Any update?

**Comment by spronin** [comment]
The issue is in [https://github.com/wix/react-native-navigation](react-native-navigation)

You can fix it yourself. Just find `RCCViewController.m` and change [this line](https://github.com/wix/react-native-navigation/blob/master/ios/RCCViewController.m#L295) to the following:  
```swift
if ([view isKindOfClass:UIScrollView.class] && [view respondsToSelector:@selector(setContentInsetAdjustmentBehavior:)]) {
```

**Comment by baijunjie** [comment]
At present 1.1.228 version still has this problem, **spronin** method is very effective, hope the official can be repaired again.

**Comment by mehdijjz** [comment]
any updates on this ?! this is a critical issue I believe

**Comment by ide** [comment]
Can you please point out which call is failing? Reading this thread, janic's pointed out that all of the RN call sites should be guarded and spronin mentioned this isn't even an issue with RN at all.

**Comment by gameboyVito** [comment]
I think the latest react-native-navigation@1.1.229 has merged my PR and addressed this issue.
