### ISSUE TITLE
(Android) Images loading causes that app crashes

### ISSUE THREAD

**Issue by Borisboky** [facebook/react-native#15956]
I'm using:

**react-native: 0.39.0
npm: 4.0.2
node: 6.9.1**

The problem is when I try to take a few pictures in a row, after fifth taken image the app crashes. I'm not getting any errors of warnings.

It crashes also if the camera is opened and if I wait for about 15-20 seconds with camera opened, without taking photo.

On newer, better phone (s8 galaxy) and newer android versions (7) it works as expected, but on this one it isn't working. Thus, I suppose that it has something to do with memory issues. But I'm not sure.

I've added **largeMemoryHeap** to the manifest file.

In android studio I get log file as follows:
![screen shot 2017-09-14 at 11 11 58](https://user-images.githubusercontent.com/13819165/30471015-6408fca8-99f7-11e7-9b31-d0c3e8ac27b9.png)

Thus, no errors, nothing. But the app doesn't work.

The stuck of code where those photos are rendered is as follows:

```
<ScrollView removeClippedSubviews={true}>
      <StatusBar backgroundColor="blue" barStyle="light-content"/>
      <Zoom visible={this.state.zoomVisible} close={() => this.setState({zoomVisible: false})} image={this.state.zoomImage} imageIndex={this.state.zoomIndex} pictures={this.state.zoomPictures} remove={this.onRemoveImage.bind(this)} />
      <View style={{width: width, height: 1, backgroundColor: '#ddd'}} />
           <View style={styles.container}>
               {cards}
           </View>
 </ScrollView>
```
And one **card** is as follows, and I have a stuck of 10:

```
<TouchableHighlight onPress={this.props.onPress} style={styles.card} underlayColor={s.color}>
       <View style={styles.innerCard}>
             <View style={styles.innerImageContainer}>
                  <Image contain='contain' style={styles.innerImage} source={this.props.image}/>
              </View>
              <View style={[styles.innerTitle, {borderBottomWidth: 4, borderBottomColor: this.props.mandatory ? this.props.noImage ? s.paletteMandatory : s.success : '#fff'}]}>
                   <Text style={styles.textTitle} allowFontScaling={false} numberOfLines={1} ellipsizeMode={'tail'}>{this.props.title}</Text>
              </View>
        </View>
</TouchableHighlight>
```
I found [here](https://github.com/facebook/react-native/issues/8677) that I need to add `removeClippedSubviews={true}` to `ScrollView`, but it does not help.

On IOS it works just fine.

It looks something like:

![simulator screen shot 15 sep 2017 09 27 34](https://user-images.githubusercontent.com/13819165/30471241-49ad2072-99f8-11e7-9701-5f9a38feb1a5.png)

When they click on one of the cards the camera is opened and after they take the photo, the get something like:
![simulator screen shot 15 sep 2017 09 27 52](https://user-images.githubusercontent.com/13819165/30471278-6dad9d12-99f8-11e7-8342-b4e7755a729b.png)

Thus, on IOS and on Android phones with more memory (Samsung S8) it works as expected.

**Comment by flynnch** [comment]
1. resizeMethod={'resize'}       http://facebook.github.io/react-native/docs/image.html
2.use Flatlist

**Comment by Borisboky** [comment]
resizeMerhod doesn't help, the same problem.
FlatList aren't available on 0.39 RN versio.

**Comment by radko93** [comment]
We don't support older versions of RN (at least not 8 versions old). Please reproduce with a new version and open a new issue (using a template).

**Comment by radko93** [comment]
@facebook-github-bot close

**Comment by deehuey** [comment]
@flynnch You are a god amongst men. Thank you, we were displaying shop logos in a ScrollView and getting crashes the further you scrolled down. Now I can quintuple the list length  without a single performance hit, all with adding `resizeMethod="resize"`.

Dumb, but glad to have found the issue :)
