### ISSUE TITLE
How to add  click event on the ART Surface

### ISSUE THREAD

**Issue by RoarRain** [facebook/react-native#15951]
I use the ART draw Bezier curve
`<Surface width={1500} height={height}>
                            <Group>
                                <Shape
                                    d={this.state.currentPath} strokeWidth={0.1} fill={linearGradientWhite}
                                    strokeCap="butt" strokeJoin="bevel"/>
                                <Shape
                                    d={this.state.averagePath} strokeWidth={0.1} fill={linearGradientWhite}/>
                            </Group>
                        </Surface>
`
How to add  click event on this top？

**Comment by radko93** [comment]
@facebook-github-bot stack-overflow
