### ISSUE TITLE
[RFC: ListView] Default rowHasChanged for DataSource, initial rows value via constructor

### ISSUE THREAD

**Issue by brentvatne** [facebook/react-native#1595]
Similar to how we provided a default prop differ with `requireNativeComponent` it would clean up code a bit and reduce the cognitive overhead of people just getting into React Native to provide a default `rowHasChanged` function that defaults to a reference equality check.

The current minimal example from the docs:

```javascript
getInitialState: function() {
  var ds = new ListView.DataSource({rowHasChanged: (r1, r2) => r1 !== r2});
  return {
    dataSource: ds.cloneWithRows(['row 1', 'row 2']),
  };
},

render: function() {
  return (
    <ListView
      dataSource={this.state.dataSource}
      renderRow={(rowData) => <Text>{rowData}</Text>}
    />
  );
},
```

This would become

```javascript
getInitialState: function() {
  var ds = new ListView.DataSource();
  return {
    dataSource: ds.cloneWithRows(['row 1', 'row 2']),
  };
},

render: function() {
  return (
    <ListView
      dataSource={this.state.dataSource}
      renderRow={(rowData) => <Text>{rowData}</Text>}
    />
  );
},
```

Additionally, we could clean up the constructor so that we can pass in some initial data rather than having to instantiate the DataSource and then call cloneWithRows on it:

```javascript
getInitialState: function() {
  return {
    dataSource: new ListView.DataSource({rows: ['row 1', 'row 2']});
  };
},

render: function() {
  return (
    <ListView
      dataSource={this.state.dataSource}
      renderRow={(rowData) => <Text>{rowData}</Text>}
    />
  );
},
```

If this looks reasonable, I can go ahead and make either or both of these changes and update docs accordingly.

**Comment by sahrens** [comment]
I'm definitely a fan of your second suggestion for initial data - for the comparison function, the thinking was that we wanted people to make sure they thought about the perf instead of just doing things blindly, but I don't think that's really working out since people just copy-pasta anyway, and it's usually not even that big a perf opportunity to customize that function anyway, so I saw go for both.  Closing this assuming you'll put up a PR :)

**Comment by ide** [comment]
I like the initial data constructor too. For the differ, I bet `(r1, r2) => true` will work better for most people as a default. It matches React's default for `shouldComponentUpdate` and is what you want when working with mutable data objects.

**Comment by brentvatne** [comment]
:guitar: :rocket: thanks for the feedback! @ide - excellent point, will try that as the default
