### ISSUE TITLE
not able to build from imagepipeline dependencies at bintray

### ISSUE THREAD

**Issue by RajuSE** [facebook/react-native#15967]
> Could not download imagepipeline.aar (com.facebook.fresco:imagepipeline:1.3.0)
> Could not get resource 'https://jcenter.bintray.com/com/facebook/fresco/ima gepipeline/1.3.0/imagepipeline-1.3.0.aar'. Could not GET 'https://jcenter.bintray.com/com/facebook/fresco/imagepipe line/1.3.0/imagepipeline-1.3.0.aar'. akamai.bintray.com

Posted on [StackOverflow](https://stackoverflow.com/questions/46251198/react-native-not-able-to-connect-to-bintray)

**Comment by ubatin** [comment]
@facebook-github-bot no-template

**Comment by radko93** [comment]
@facebook-github-bot no-template

**Comment by RajuSE** [comment]
My bad if you could not get more info.. But Could you check[ stackoveflow question ](https://stackoverflow.com/questions/46251198/react-native-not-able-to-connect-to-bintray)I posted for more details on.
I am just trying to run `react-native init AwesomeProject` command which gives this error:

> Could not download imagepipeline.aar (com.facebook.fresco:imagepipeline:1.3.0)
> Could not get resource 'https://jcenter.bintray.com/com/facebook/fresco/ima gepipeline/1.3.0/imagepipeline-1.3.0.aar'. Could not GET 'https://jcenter.bintray.com/com/facebook/fresco/imagepipe line/1.3.0/imagepipeline-1.3.0.aar'. akamai.bintray.com
>

**Comment by radko93** [comment]
I have no idea what is going on there. You haven't provided any description.

**Comment by RajuSE** [comment]
I'm following steps at [docs](https://facebook.github.io/react-native/releases/0.23/docs/getting-started.html#content)
trying to run  AwesomeProject sample project with command `react-native init AwesomeProject`
