### ISSUE TITLE
[ANDROID] Linking.getInitialURL() returns null after exiting the app with back button and using deep linking again (only in production!)

### ISSUE THREAD

**Issue by ferrannp** [facebook/react-native#15961]
### Is this a bug report?

Yes.

### Environment

1. `react-native -v`: 0.46.4
2. `node -v`: 8.4.0
3. `npm -v`: 5.3.0
4. `yarn --version`: 0.27.5

- Target Platform: Android
- Development Operating System: macOS

### Steps to Reproduce

Configure your app to receive deep linking links as explained here: https://facebook.github.io/react-native/docs/linking.html.

My native code looks like:

```xml
<intent-filter>
    <action android:name="android.intent.action.VIEW" />
    <category android:name="android.intent.category.DEFAULT" />
    <category android:name="android.intent.category.BROWSABLE" />
    <data android:scheme="https"
          android:host="some-url.com"
          android:pathPrefix="/some-prefix" />
</intent-filter>
```
I also set the Android Activity to `singleTask`.

On the JS code:

```js
componentDidMount() {
  Linking.getInitialURL().then((url: string) => {
    if (url) {
      this._handleLinking(url);
    }
  });
}
```

### Expected Behavior

1. URL is not null when handling deep linking. I am using the command:

```
$ adb shell am start
        -W -a android.intent.action.VIEW
        -d "example://gizmos" com.example.android
```

#### Development

- I kill the app (manually removing it from apps), I ran the adb command, url is not null and deep linking is ok
- I open the app, I kill the activity with the back button, I ran the adb command, url is not null and deep linking is ok

#### Production

- I kill the app (manually removing it from apps), I ran the adb command, url is not null and deep linking is ok
- I open the app, I kill the activity with the back button, I ran the adb command, **url is null so I cannot handle the deep linking**

From Logcat:

```
09-15 18:18:52.262 675-686/system_process I/ActivityManager: START u0 {act=android.intent.action.VIEW dat=https://some-url.com/... flg=0x10000000 pkg=com.myapp cmp=com.myapp/.MainActivity} from uid 0 on display 0
09-15 18:18:52.386 8191-10955/com.myapp I/ReactNativeJS: Running application "MyApp" with appParams: {"rootTag":11}. __DEV__ === false, development-level warning are OFF, performance optimizations are ON
09-15 18:18:52.393 8191-10955/com.myapp I/ReactNativeJS: getInitialURL null
```

As you can see Intent has data but the `console.log` inside `getInitialURL` shows `null` as url.

It looks like an issue which the fact that even that I kill the activity with back button, JS bundle is not destroyed till it passes some time. However, I don't understand why the behavior is different in development than in production. The correct behavior is the development one though.

### Some debugging

- It looks like https://github.com/facebook/react-native/blob/1e8f3b11027fe0a7514b4fc97d0798d3c64bc895/ReactAndroid/src/main/java/com/facebook/react/modules/intent/IntentModule.java#L50 `currentActivity` is null
- Wrapping `getInitialURL` with a 10ms `setTimeout` actually makes it work

Race condition somewhere? Is it possible than in this case `componentDidMount` it's called before the actual activity gets created?

### Reproducible Demo

Can't do it in Expo. I'll try to write something I can share.

**Comment by radko93** [comment]
@facebook-github-bot label Android
