### ISSUE TITLE
Lifecycle events and HeadlessJS on Android

### ISSUE THREAD

**Issue by vjeranc** [facebook/react-native#15960]
I'm interested in how exactly lifecycle events work with HeadlessJS and how they should be used by react-native modules.

Example: If I were to make a background task where I'm fetching messages only over WiFi, I'd need [NetInfo](https://facebook.github.io/react-native/docs/netinfo.html) to tell me the network type. I'd register a listener and stop fetching if network provider changed.

The problem is that `onHostResume`, `onHostDestroy` and `onHostPause` listeners are triggered when something happens with the main activity.

In the above case, NetInfo [unregisters](https://github.com/facebook/react-native/blob/1e8f3b11027fe0a7514b4fc97d0798d3c64bc895/ReactAndroid/src/main/java/com/facebook/react/modules/netinfo/NetInfoModule.java#L85-L88) receiver and the background task that can still be running (despite activity being destroyed or on pause) will no longer receive events on network provider. There might be other ways to solve the task above but there can be plenty of similar tasks that are crippled by things done in native when actions on activity trigger lifecycle changes.

There seem to be other non-`react-native` modules doing similar things and completely crippling the background task.

Is this expected behavior?

**Comment by vjeranc** [comment]
What exactly happened here?

**Comment by vjeranc** [comment]
This is not a bug report and this is not a question or a problem I have with the library?

Should I frame the NetInfo implementation as a bug?

**Comment by hramos** [comment]
Hey @vjeranc, we have a bot that periodically closes issues that don't use the template provided. We're only using GitHub issues for bug reports at this time. If you can frame this within the requirements set forth by the template, go ahead and open a new issue. Otherwise it might be best to find another avenue to direct this sort of question.
