### ISSUE TITLE
TextInput Prevent Scroll

### ISSUE THREAD

**Issue by limeytrader007** [facebook/react-native#15962]
Are there any props (I don't see any in docs) to prevent a multiline TextInput from scrolling at all?
Thanks

**Comment by ubatin** [comment]
@facebook-github-bot stack-overflow

**Comment by radko93** [comment]
@facebook-github-bot stack-overflow

**Comment by gastonmorixe** [comment]
+1 how? thanks

**Comment by markdaws** [comment]
+1

**Comment by sledderGIT** [comment]
+ 1

**Comment by gastonmorixe** [comment]
Patch RCTTextView.m
```
    _backedTextInput.scrollEnabled = YES;
```

to `NO`

**Comment by aizigao** [comment]
@gastonmorixe  has same example?
