### ISSUE TITLE
Print: Entry, ":CFBundleIdentifier", Does Not Exist

### ISSUE THREAD

**Issue by rahulnakate** [facebook/react-native#15964]
### Environment

1. `react-native -v`:  0.48.3
2. `node -v`: v6.11.3
3. `npm -v`: 3.10.10

Then, specify:

- Target Platform: iOS

- Development Operating System: macOS

- Build tools: iOS

### Steps to Reproduce

(Write your steps here:)

1. react-native init TestApp
2. cd TestApp
3. react-native start 
4. react-native run-ios

### Expected Behavior

2017-09-16 00:46:58.823 xcodebuild[7968:247699]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-13181.4/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/BuildSystem/DependencyGraph/XCDependencyGraph.mm:688
Details:  unable to write dependency graph: You don’t have permission to save the file “RCTNetwork.build” in the folder “Debug-iphonesimulator”.
Object:   <XCDependencyGraph>
Method:   +loadOrCreateInBuildDirectory:withTargetBuildContext:withBasePath:
Thread:   <NSThread: 0x7fe8127a7310>{number = 9, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.

Installing build/Build/Products/Debug-iphonesimulator/TestApp.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/TestApp.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

In Xcode its showing error
<img width="856" alt="screen shot 2017-09-16 at 12 57 04 am" src="https://user-images.githubusercontent.com/7077797/30499932-03f11e26-9a7a-11e7-810a-d448fdf9f24f.png">

**Comment by ubatin** [comment]
@facebook-github-bot label iOS

**Comment by radko93** [comment]
```Details: unable to write dependency graph: You don’t have permission to save the file “RCTNetwork.build” in the folder “Debug-iphonesimulator”.
Object: ```
Don't you think it's a problem on your side?

**Comment by bangonkali** [comment]
I have the same issue

```
> react-native --version
react-native-cli: 2.0.1
react-native: 0.48.3
```

```
Xcode 9.0
Build version 9A235
```

Error
```
...
** BUILD FAILED **

The following build commands failed:
	CompileC app/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/third-party.build/Objects-normal/x86_64/Bits.o app/node_modules/react-native/third-party/folly-2016.09.26.00/folly/Bits.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/app.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/app.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
```

**Comment by jweboy** [comment]
@bangonkali 
>注意：init命令默认会创建最新的版本，而目前最新的0.45及以上版本需要下载boost库编译。此库体积 庞大，在国内即便翻墙也很难下载成功，导致很多人无法正常运行iOS项目，中文网在论坛中提供了这>
些库的国内下载链接。如果你嫌麻烦，又没有对新版本的需求，那么可以暂时创建0.44.3的版本。

> 提示：你可以使用--version参数（注意是两个杠）创建指定版本的项目。例如react-native init MyApp  --version 0.44.3。注意版本号必须精确到两个小数点。

这段话的原文地址 http://reactnative.cn/docs/0.48/getting-started.html

**react-native init MyApp  --version 0.44.3**
I installed version 0.44.3 to fix this problem

**Comment by dustturtle** [comment]
fucking the bots ! idiot
