### ISSUE TITLE
null is not an object (evaluating 'this._listRef.scrollToIndex')

### ISSUE THREAD

**Issue by dnish** [facebook/react-native#15968]
Since switching from ListView to FlatList we're getting some errors like this:

```
null is not an object (evaluating 'this._listRef.scrollToIndex')
```

They happen rarely, but I could confirm that this also happened on one of my devices (OnePlus 3 with Android 7). The app shutted down after I've tried to open a view with a FlatList in it. Sadly I wasn't able to reproduce it. 

This is the full output:

```
TypeError null is not an object (evaluating 'this._listRef.scrollToIndex') 
    index.android.bundle:207:2069 value
    index.android.bundle:817:11813 value
    index.android.bundle:817:3218 
    index.android.bundle:39:562 
    index.android.bundle:32:664 callTimer
    index.android.bundle:32:1084 callTimers
    index.android.bundle:30:3208 value
    index.android.bundle:30:959 
    index.android.bundle:30:2640 value
    index.android.bundle:30:931 value
```

Due to our logs it only happens on Android devices. We are on React Native 0.46 and [react-navigation](https://github.com/react-community/react-navigation) for our routes. Maybe the view is destroyed while RN tries to access <code>this._listRef</code>?

**Comment by charpeni** [comment]
@facebook-github-bot needs-repro

**Comment by dnish** [comment]
@charpeni Does this really need a repo when it appears in the error logs of Bugsnag? I'm just wondering, when I take a look into https://github.com/facebook/react-native/blob/d1372faeb5f9ebc87a8dc9b8c9f31590bda414ea/Libraries/Lists/FlatList.js#L395, there are a checks for <code>this._listRef</code>. But this check is missing in https://github.com/facebook/react-native/blob/d1372faeb5f9ebc87a8dc9b8c9f31590bda414ea/Libraries/Lists/FlatList.js#L342

I guess there is a reason why we need to check for <code>this._listRef</code> in the other functions?

**Comment by jasongrishkoff** [comment]
Also seeing this error pop up in my Android crash logs.

**Comment by DeividVeloso** [comment]
TypeError: null is not an object (evaluating 'this._listRef.scrollToOffset')
  at scrollToOffset(app:///index.android.bundle:40893:20)
  at ? (app:///index.android.bundle:79013:48)
  at ? (app:///index.android.bundle:4153:24)
  at _callTimer(app:///index.android.bundle:4074:15)
  at callTimers(app:///index.android.bundle:4268:17)
  at __callFunction(app:///index.android.bundle:3637:47)
  at ? (app:///index.android.bundle:3453:29)
  at __guard(app:///index.android.bundle:3608:11)
  at callFunctionReturnFlushedQueue(app:///index.android.bundle:3452:20)

I have same issue

**Comment by est7** [comment]
@DeividVeloso did u solved it?

**Comment by DeividVeloso** [comment]
Not yet, some times ocorre.

Thanks
