### ISSUE TITLE
Packager does not gracefully handle project switches

### ISSUE THREAD

**Issue by samuela** [facebook/react-native#15963]
### Is this a bug report?

Yes.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes.

### Environment

1. `react-native -v`: 
react-native-cli: 2.0.1
react-native: 0.48.3
2. `node -v`: v8.5.0
3. `npm -v`: 5.3.0
4. `yarn --version`: 0.17.2

Then, specify:

- Target Platform: iOS

- Development Operating System: macOS 10.12.6

- Build tools: Xcode

### Steps to Reproduce

The react native packager fails to detect a project switch and respond to it in a friendly way to the user.

Round 1:

1. Create a react native project A which includes some JavaScript error that will be triggered on launch. Anything that produces the red screen of death should work.
2. Run project A in the simulator with eg `react-native run-ios`.
3. Keep in the local react native packager open.
4. Create a react native project B. Just using `react-native init` with no modifications is sufficient.
5. Run project B in the simulator with eg `react-native run-ios`.
6. At this point you should be prompted with the *same* red screen of death citing the JavaScript error in project A even though you ran project B.

Round 2:

7. Now, go back to project A and fix the JavaScript code such that it runs fine.
8. Return to project B and run it in the simulator. You should now be presented with the `Application ... has not been registered." error screen (attached). This is not a bad error, since it provides a hint that immediately identifies the issue.
![screen shot 2017-09-15 at 1 46 41 pm](https://user-images.githubusercontent.com/226872/30497289-50dd3d14-9a20-11e7-848d-81dd80d7efb0.png)
9. Now, reintroduce the error in project A and we're back to the same situation.

### Expected Behavior

I would expect to either see project B run successfully or an error indicating that the packager was in a bad state.

### Actual Behavior

The local packager ends up in a corrupted state and produces unexpected behavior in the simulator.

### Reproducible Demo

Hopefully the steps above are sufficient to repro the issue. If you have any issues, don't hesitate to reach out in the comments.

**Comment by ubatin** [comment]
@facebook-github-bot stack-overflow

**Comment by radko93** [comment]
Why do you need one packager to be used in two different apps? Just try opening two packagers.

**Comment by samuela** [comment]
@radko93 Well I think there are two issues here. One being that the react-native CLI will reuse the same packager if it finds one already running and then not tell you that things have gone wrong. So, if you have a long-lost packager window buried in one of your desktops and then you run `react-native run-ios` in a new project, it automatically tries to reuse the wrong packager and things go wrong.

The second issue is that the error screen you are presented with reflects the error in project A while it should be showing you an error in project B. All in all, this issue would likely be fixed or avoided by addressing the whole packager reuse issue.

**Comment by samuela** [comment]
Any updates here before this gets auto-closed?

**Comment by samuela** [comment]
bump

**Comment by Rojuinex** [comment]
There are so many issues with React packer, this being just one. @radko93 you cant just open up two packagers because they default to port 8081 and there's no graceful way to fix that ATM.  Also React packager explodes if you try to use it from a build server (I've tried Xcode Server, GoCD, etc).  More to the point even if you could get a RN project to build on a build server you couldn't ever build more than one project on your build server because of this statically set port 8081 issue.

**Comment by radko93** [comment]
Maybe try using an alternative then (like https://github.com/callstack/haul). Unfortunately, I'm not really a person that could influence any decision on changing this.

**Comment by samuela** [comment]
bump

**Comment by kelset** [comment]
I don't think this issue needs to live on the main repo, since it seems to me this is strictly related to Metro.

Open a dedicated issue there.

Closing.
