### ISSUE TITLE
ios click to send text will wrap instead of triggering  blurOnSubmit

### ISSUE THREAD

**Issue by huanghaodong** [facebook/react-native#15978]
Ask the bigwigs, TextInput component, multiline is true, and blurOnSubmit is false, ios click Send (enter)  the text will be wrapped without firing onSubmitEditing, there is no way to make it not to line but trigger onSubmitEditing (android is like this Effect). I do is a similar WeChat chat, click to send is sent, do not wrap.

**Comment by radko93** [comment]
@facebook-github-bot no-template
