### ISSUE TITLE
debugger-ui not shown console.log

### ISSUE THREAD

**Issue by khanghyxda** [facebook/react-native#15972]
In tab console shown this error and debugger-ui can't see console to debug

>debugger-ui:92 Uncaught TypeError: Cannot set property 'volume' of null
    at Object.render (debugger-ui:92)
    at Object.setState (debugger-ui:46)
    at WebSocket.ws.onopen (debugger-ui:150)
render @ debugger-ui:92
setState @ debugger-ui:46
ws.onopen @ debugger-ui:150
debugger-ui:92 Uncaught TypeError: Cannot set property 'volume' of null
    at Object.render (debugger-ui:92)
    at Object.setState (debugger-ui:46)
    at WebSocket.ws.onclose (debugger-ui:187)`

**Comment by pirosoft** [comment]
i have the same problem! did you solve it?

**Comment by treytrahin** [comment]
Refreshing the simulator `⌘R` seems to work, at least some of the time. It would be nice if the error was more specific, though.

**Comment by tested01** [comment]
+1

**Comment by khanghyxda** [comment]
Hi
I solved it. 
After this error, I tried to install canary chrome to debug, but I still have this error, I tried using Visual Code and installed Extension React Native Tool to debug. After debugging on Visual Code, I installed React Developer Tools and then suddenly the chrome canary did not get this error again. You try this way.
1. Install chrome canary 
2. Install React Developer Tools 
> npm install -g react-devtools
react-devtools
3. Reset computer
Good luck.

**Comment by sinner** [comment]
I'm having the same problem. Moreover, this error is making me not able to print information to debug through the console.log method. Here more details about the error:

Uncaught TypeError: Cannot set property 'volume' of null
    at Object.render (debugger-ui:92) 92: silence.volume = 0.1;
    at Object.setState (debugger-ui:46)
    at WebSocket.ws.onopen (debugger-ui:150)
debugger-ui:1


Error in event handler for (unknown): TypeError: Cannot read property 'userId' of undefined
    at chrome-extension://lifbcibllhkdhoafpjfnlhfpfgnpldfl/contentscript.js:1:841

**Comment by pedrommuller** [comment]
@sinner I have the same exact issue, and my app doesn't load on the emulator, any ideas?

**Comment by RossKinsella** [comment]
Getting this issue also

**Comment by cadz** [comment]
I just starting to learn react-native and i thought there is problem with my redux-logger implementation. Almost pulling my hair out of this. any solution yet?

**Comment by cadz** [comment]
ok, i think i finally able to get this to work.
on the react-native app, press ctrl+M to open developer menu. and choose "Debug JS Remotely" .
only after this the logging on debugger-ui will work.

you might want to close all opened debugger-ui windows/tabs. choosing debug js remotely will open a new tab.

**Comment by magneticz** [comment]
I had same issue for two days, which severely hurt my work progress. At the end, i tried to disable all my extensions on chrome and it worked. After that, I started enabling them one by one, but it kept working fine, so i couldn't single out one extension that was causing it. I suspect it was either adblocker or react/redux-dev-tools.

**Comment by RajeshwariGandmal** [comment]
Same issue...has anyone found a way out?

**Comment by mymai91** [comment]
@RajeshwariGandmal press Command and M and then reload http://localhost:8081/debugger-ui/

**Comment by Graham42** [comment]
I've opened an issue for this that follows the template so bots wont close it. If you are still experiencing this please go :+1:  it 
https://github.com/facebook/react-native/issues/17941

**Comment by afilp** [comment]
@sinner Did you find any solution to this? I tried everything, upgraded all packages and still cannot work on the project (I am on Windows 10, if this is a problem).

**Comment by kyriakos** [comment]
I also get the volume of null problem, but weirdly doesn't happen every time.

**Comment by adipascu** [comment]
I fixed this by disabling the "Adblock Plus" Chrome extension.

**Comment by barbush** [comment]
Solution above @cadz worked for me. Windows 10 / Android emulator. 

> on the react-native app, press ctrl+M (or Command + M on mac to open developer menu. and choose "Debug JS Remotely" .
only after this the logging on debugger-ui will work.

**Comment by mustafaskir** [comment]
same issue :- 
i remove all extensions , not working with chrome or React Native Debugger
gives me 
unfortunately App has stopped
any help please ,
thanks in advance

**Comment by mikeyamato** [comment]
The solution is a combination of what @cadz and @lironzluf posted. 

For Mac OS...
With the iPhone simulator open type `⌘` + `D` to bring up the [in-app developer menu](http://facebook.github.io/react-native/docs/debugging#accessing-the-in-app-developer-menu). Next click `Debug JS Remotely`.

Note: if you're running Android Studio on a Mac type `⌘` + `M` instead.

For Windows OS I'm guessing the solution to be similar. With your Android simulator open type `Control` + `M` then click `Debug JS Remotely`.
