### ISSUE TITLE
 ios TextInput press 'enter' 换行 而是不触发 onSubmitEditing

### ISSUE THREAD

**Issue by huanghaodong** [facebook/react-native#15977]
请问一下大佬们，TextInput组件，multiline为true，并且blurOnSubmit为false时，ios点击确定（enter）输入文字会换行而不触发onSubmitEditing，有什么办法能让它不换行而是触发onSubmitEditing（android就是这样的效果）。我做的是一个类似微信聊天，点击发送就是发送，不换行。

**Comment by jasonchou3** [comment]
http://reactnative.cn/docs/0.48/textinput.html#bluronsubmit能不能好好看文档？？

**Comment by huanghaodong** [comment]
是的，blurOnSubmit为true时,按下回车键时文本不会换行同时触发onSubmitEditing事件。问题是，设计要求提交后不能失焦，也就是blurOnSubmit必须为false。参照微信，发送消息

**Comment by radko93** [comment]
@facebook-github-bot close

**Comment by radko93** [comment]
Please use English next time.
