### ISSUE TITLE
RCTImageStoreManager.m: Error "This block declaration is not a prototype"

### ISSUE THREAD

**Issue by agersoncgps** [facebook/react-native#15971]
"react-native": "0.47.2"
This started after updating to XCode 9 Gold Master

<img width="873" alt="screenshot 2017-09-16 15 43 05" src="https://user-images.githubusercontent.com/336441/30515440-be0710a6-9af5-11e7-9372-1708daef272f.png">

I was able to add:
`#pragma clang diagnostic ignored "-Wstrict-prototypes"`
to work around it

**Comment by ide** [comment]
Have you tried 0.48.x? The latest release should compile with Xcode 9.

**Comment by agersoncgps** [comment]
Confirmed fixed in "react-native": "0.48.3",

**Comment by ragamufin** [comment]
See: https://github.com/facebook/react-native/issues/16070#issuecomment-331662289

**Comment by michaelmerrill** [comment]
I'm using RN 0.48.4 and still seeing this issue.

**Comment by tolgaduzenli** [comment]
any solution for RN 0.43.3 ?

**Comment by masm** [comment]
This is still an issue in version 0.49.2

**Comment by EduardJS** [comment]
I can see it today ... in a new project I just created. Version 0.49.5

Fun fact, works just fine on an "older" project with version 0.48.4

**Comment by arorajatin** [comment]
I'm facing this issue as well. Would need to add custom code to the file to get rid of the warning. Any ETA on the fix?

**Comment by EduardJS** [comment]
Solution is to add void as parameter as the compiler is a bit stricter now, and expects void for methods with no parameters.

Just add `void` in both places, ignore the new errors which appear and hit build again. It will work just fine

**Comment by jdnichollsc** [comment]
Thanks @EduardJS, you save my day!
