### ISSUE TITLE
jsSchedulingOverhead warnings

### ISSUE THREAD

**Issue by jaygarcia** [facebook/react-native#1598]
I'm quite embarrassed to say that I'm finally getting around to debugging my JSX code on the phone.

I'm getting these jsSchedulingOverhead warnings:

![jsschedulingoverhead](https://cloud.githubusercontent.com/assets/180031/8118527/7d3c489a-105d-11e5-9ac0-b8f406f2c2e9.jpg)

Should I be worried? Could it be caused by the fact that I'm debugging w/ chrome?

**Comment by tadeuzagallo** [comment]
What it means is that the start date passed on the timer creation (`Date.now()` on JavaScript) is 800ms ahead of the current time on iOS (`[NSDate now]`), when you're running the app on the device and the executor on your computer it's very unlikely that the times will be the same at the millisecond level. So no, don't worry about it.

**Comment by siwymilek** [comment]
How can I not worry about though warrnings obscure a half of screen and I can't disable them...

**Comment by tadeuzagallo** [comment]
I don't know if you realise, but this issue is from 6 months ago, and at the time there were no YellowBox, but yes, you can disable them, try:

```js
console.ignoreYellowBox = ['jsSchedulingOverhead'];
```

---

@nicklockwood maybe we should remove this warning?

**Comment by nicklockwood** [comment]
@tadeuzagallo I've no context on what this warning means, but it seems very spammy. Maybe YellowBox should have an upper limit on warnings displayed at once?

**Comment by mvayngrib** [comment]
@tadeuzagallo looks like it's console.ignoredYellowBox not console.ignoreYellowBox

**Comment by lfsanchezg** [comment]
pasted `console.ignoredYellowBox = ['jsSchedulingOverhead']; ` on my code and it worked on the phone, but Xcode still shows the warning. 

![captura de pantalla 2016-01-07 a las 6 20 25 p m](https://cloud.githubusercontent.com/assets/4084015/12183084/6576315e-b56b-11e5-81d2-c8a68da10686.png)

Do you have any workaround for this? for now I put my computer some seconds behind.

**Comment by eysi09** [comment]
This warning is clogging up my Chrome console, repeating indefinitely and obscuring all relevant console logs. Is there any way around this except changing the computer's cloclk? `console.ignoredYellowBox = ['jsSchedulingOverhead'];` only removes the warning from the phone, not the Chrome or Xcode consoles.

**Comment by lrettig** [comment]
+1

This is happening to me too, and making debugging while running on a device impossible. Why is this request closed?

It's clearly affecting a bunch of other people, cf: https://github.com/root-two/react-native-drawer/issues/44, https://github.com/facebook/react-native/issues/2046, https://github.com/lwansbrough/react-native-camera/issues/32, https://github.com/facebook/react-native/issues/5136 etc.

Thanks

**Comment by lrettig** [comment]
Temporary workaround: comment out [line 179 of React/Modules/RCTTiming.m](https://github.com/facebook/react-native/blob/master/React/Modules/RCTTiming.m#L179)

![image](https://cloud.githubusercontent.com/assets/3316532/12423267/a30f6b3a-be98-11e5-8579-a8694ad5d2db.png)

**Comment by marcboehret** [comment]
+1

**Comment by corbt** [comment]
Re-opening because this is a common problem when developing on a device.

**Comment by aakashsigdel** [comment]
+1

**Comment by ryaneof** [comment]
+1. Seems commenting out that line is the only effective way remove . by @lrettig https://github.com/facebook/react-native/issues/1598#issuecomment-172890857

**Comment by prabakarviji** [comment]
+1

**Comment by sjmueller** [comment]
+1

**Comment by corbt** [comment]
I agree with everyone that this is an annoying issue developing on a device. I've pushed a possible fix in https://github.com/facebook/react-native/pull/5731, will try to poke some people at Facebook to review the change.

**Comment by leijing7** [comment]
@lrettig your commenting out method works well

**Comment by kennym** [comment]
+1

**Comment by elaygl** [comment]
+1

**Comment by bcalik** [comment]
Wow this is a year old simple issue and still has no progress!

**Comment by corbt** [comment]
Warning removed in https://github.com/facebook/react-native/commit/2d27cf0ceb6441e0044e9dada3482fd6fe2672df. Sorry that took so long!
