### ISSUE TITLE
Automatically takes a space after 4 letters in text input field

### ISSUE THREAD

**Issue by harikanammi** [facebook/react-native#15985]
If i entered text in text-input field then automatically it takes a space after 4 digits.

Here is my code for text-input field:
handleCardNumber = (text) => {
this.setState({ cardNumber: text })
}
<TextInput
ref="first"
underlineColorAndroid="transparent"
autoCapitalize="none"
style={styles.cardNumberTextInput}
placeholder="1234 1234 1234 1234"
placeholderTextColor="grey"
returnKeyType='next'
keyboardType = {'numeric'}
onChangeText={this.handleCardNumber}
onSubmitEditing={(event)=>{
this.refs.second.focus();
}}
/>

Here is my screenshot:
![screen shot 2017-09-18 at 12 44 18 pm](https://user-images.githubusercontent.com/31063894/30536840-229493d2-9c85-11e7-964c-d2fb0ed25851.png)

**Comment by radko93** [comment]
@facebook-github-bot no-template
