### ISSUE TITLE
Automatically takes a space after 4 letters in text input field

### ISSUE THREAD

**Issue by harikanammi** [facebook/react-native#15982]
If i entered text in text-input field then automatically it takes a space after 4 digits.
Here is my screenshot:
![screen shot 2017-09-18 at 12 44 18 pm](https://user-images.githubusercontent.com/31063894/30531965-3c05f42a-9c6f-11e7-9886-08ff77f2a7f1.png)

Here is my code for text-input field:
handleCardNumber = (text) => {
     this.setState({ cardNumber: text })
  }
 <TextInput
       ref="first"
       underlineColorAndroid="transparent"
       autoCapitalize="none"
       style={styles.cardNumberTextInput}
       placeholder="1234 1234 1234 1234"
       placeholderTextColor="grey"
       returnKeyType='next'
       keyboardType = {'numeric'}
       onChangeText={this.handleCardNumber}
       onSubmitEditing={(event)=>{
       this.refs.second.focus();
       }}
      />

**Comment by radko93** [comment]
@facebook-github-bot duplicate #15985
