### ISSUE TITLE
code doesn't run when stop Remote Debugger!

### ISSUE THREAD

**Issue by zhaoheqi** [facebook/react-native#15983]
![image](https://user-images.githubusercontent.com/6813909/30532674-28474a42-9c88-11e7-9f9b-55c0097914ca.png)
![image](https://user-images.githubusercontent.com/6813909/30532680-2ea5aa00-9c88-11e7-8ba3-68c94effea63.png)

it will get image Code when page initialize.if i was in debugger it's ok but if i stop remote debugger then it goes error!why?

**Comment by radko93** [comment]
@facebook-github-bot no-template
