### ISSUE TITLE
Enable dev mode after disabled (Android)

### ISSUE THREAD

**Issue by furedal** [facebook/react-native#15986]
I want to re-enable dev-mode after i disabling it using:
`react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/`

I tried removing the generated files, in the assets folder `index.android.bundle` and `index.android.bundle.meta` and then execute `react-native run-android` but after that the application will only crash.

**Comment by radko93** [comment]
@facebook-github-bot no-template
