### ISSUE TITLE
Test react native app V0.45.1 (or above) with JEST

### ISSUE THREAD

**Issue by assafb81** [facebook/react-native#15981]
I am trying to test my react native application with JEST.
I am using:
```
dependencies:
  "react": "16.0.0-alpha.12",
  "react-native": "0.45.1",

devDependencies:
  "enzyme": "^2.9.1",
  "react-dom": "^15.6.1",
  "jest": "20.0.4",
  "react-test-renderer": "16.0.0-alpha.12",
  "save": ^2.3.1"
```
I wanted to add tests to my react native application without downgrade my react native version.
Actually, I am thinking about upgrading it before moving to production.

I keep getting the error:
` react-dom is an implicit dependency in order to support react@0.13-14. Please add the appropriate version to your devDependencies. See https://github.com/airbnb/enzyme#installation`

and most of the way to solve the problem was to downgrade my RN version, is there any other way?

I am using yarn (v1.0.2) 
The application is aimed to Android and iOS phones.
I develop on Window and Mac.

**Comment by sattaman** [comment]
`react-dom` version should match `react`

**Comment by radko93** [comment]
And react version should match the one that comes with a RN version.

**Comment by assafb81** [comment]
@sattaman: `react-dom` latest version is 15.6.1 according to [react-dom](https://www.npmjs.com/package/react-dom) but I need version 16.X.X.
I don't want to downgrade my RN version.

@radko93: my react version is the one that comes with RN v0.45.1.

**Comment by sattaman** [comment]
@assafb81 It probably does exist its just prerelease. You could try yarn add react-dom@next and you'll see a beta version
