### ISSUE TITLE
Linking.getInitialURL() url value is null

### ISSUE THREAD

**Issue by ArkadyB** [facebook/react-native#15992]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

1. `react-native -v`: 2.0.1
2. `node -v`: 8.4.0
3. `npm -v`: 4.6.1

Then, specify:

- Target Platform: Android

- Development Operating System: MacOs Sierra

- Build tools: Application created using create-react-native-app and then detached with support of Expo SDK

### Steps to Reproduce

(Write your steps here:)

1. Create application using create-react-native-app 
2. Detach application with: npm run eject (keep support of Expo SDK)
3. Update AndroidManifest.xml with respective deep links filters inside MainActivity
```
<intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="https"
              android:host="www.mydomain.com"
              android:pathPrefix="/" />
        <data android:scheme="https"
              android:host="www.mydomain.com" />
</intent-filter>
```
4.  Update activity declaration with `android:launchMode="singleTask"`
5.  Update application component to load url on componentDidMount:
```
componentDidMount() {
    Linking.getInitialURL().then((url) => {
      console.log('Inside of the function is: ' + url);
      this._handleOpenURL(url);
    }).catch(err => console.error('An error occurred', err));
}
```
6. Find url is always null

### Expected Behavior

url variable populated with respective Url application was loaded with

### Actual Behavior

Url is null

**Comment by harrycheung** [comment]
Experiencing this too with expo. Linking.getInitialURL works for apps created with `react-native init` though.

**Comment by Minishlink** [comment]
Duplicate of #15961 ?

**Comment by ArkadyB** [comment]
@Minishlink , not really (similar yes, but not a duplicate). My issue has nothing similar to closing application with back button. For me it just never works at all. Regardless of the way app was killed or never started since installation...

**Comment by gvillenave** [comment]
I'm experiencing the same thing since updating from RN 0.46.4 to 0.48.4, it used to work fine before that.

Note: I'm using [wix/react-native-navigation](https://github.com/wix/react-native-navigation)

**Comment by AuraIV** [comment]
Same issue

**Comment by henebb** [comment]
Any updates on this?

**Comment by henebb** [comment]
Solved it! I'll explain what the problem for us was, if anyone is facing the same issue as we did.

We had a custom activity called "SplashActivity" where we had added the
```
<intent-filter>
    <action android:name="android.intent.action.VIEW" />
    ...
```
In our `SplashActivity.java` we started the MainActivity like this:
```
@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    Intent intent = new Intent(this, MainActivity.class);
    startActivity(intent);
    finish();
}
```

For RN to pick up the url from `getInitialURL()`, we need to pass the data and action to our MainActivity. So basically we just passed the required information to our MainActivity (in `SplashActivity.java`):
```
@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    Uri data = null;
    String action = null;
    Intent currentIntent = getIntent();
    if (currentIntent != null) {
        Uri intentData = currentIntent.getData();
        if (intentData != null) {
            data = intentData;
        }

        // Get action as well.
        action = currentIntent.getAction();
    }

    Intent intent = new Intent(this, MainActivity.class);
    // Pass data and action (if available).
    if (data != null) {
        intent.setData(data);
    }
    if (action != null) {
        intent.setAction(action);
    }
    startActivity(intent);
    finish();
}
```

(don't forget to `import android.content.Intent;` and `import android.net.Uri;`)

This solved it for us.

**Comment by sercand** [comment]
I am getting null value too but on iOS.
