### ISSUE TITLE
undefined is not an object (evaluating'(0,_reactNative.connect)(function(state){return{nav:state.nav};})')

### ISSUE THREAD

**Issue by jctadios** [facebook/react-native#15997]
### Is this a bug report?

No

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

1. `react-native -v`:
               react-native-cli: 2.0.1
               react-native:0.47.2
2. `node -v`: v8.2.1
3. `npm -v`: 4.6.1
4. `yarn --version`:

Then, specify:

- Target Platform: Andriod

- Development Operating System: windows 7 ultimate version 6.1

- Build tools: Expo

Code:

`import React, {Component} from 'react'`
`import {Provider, connect} from 'react-native'`
`import {StackNavigator, addNavigationHelpers} from 'react-navigation'`

`import Routes from './config/routes'`
`import getStore from './store'`

`const Navigator = StackNavigator(Routes, {`
   `headerMode: 'none'`
`})`

`const navReducer = (state, action) => {`
    `const newState = Navigator.router.getStateForAction(action, state)`
    `return newState || state`
`}`

`class App extends Component {`
    `render(){`
        `return(`
            `<Navigator `
                `navigation={addNavigationHelpers({`
                    `dispatch: this.props.dispatch,`
                    `state: this.props.nav`
                `})}`
            `/>`
        `)`
    `}`
`}`

`const store = getStore(navReducer)`
`const AppIndex = connect( state => ({ nav: state.nav }) )(App)`

`export default Index = () => {`
    `return (`
        `<Provider store={store}>`
            `<AppIndex />`
        `</Provider>`
    `)`
`}`

**Comment by chirag04** [comment]
@facebook-github-bot stack-overflow
