### ISSUE TITLE
From 0.44 to 0.48: Cannot read property "ReactCurrentOwner" of undefined

### ISSUE THREAD

**Issue by enguerranws** [facebook/react-native#15991]
Hi,

I recently updated my project from RN 0.44 to RN 0.48. My project now crashes on launch (iOs, didn't tested it yet on Android) throwing this error:

`Cannot read property 'ReactCurrentOwner' of undefined`

The thing is that this error doesn't refers explicitely to a module so it's kinda hard to debug.

Did I miss something during the upgrade? What could cause this?

Here's my dependencies:

```
...
"dependencies": {
    "atob": "^2.0.3",
    "buffer": "^5.0.6",
    "file-api": "^0.10.4",
    "link": "^0.1.5",
    "moment": "^2.18.1",
    "react": "16.0.0-alpha.6",
      "react-dom": "^16.0.0-alpha.6",
    "react-native": "^0.48.3",
    "react-native-blur": "^3.1.3",
    "react-native-button": "^1.8.2",
    "react-native-display": "^1.0.8",
    "react-native-fbsdk": "^0.6.0",
    "react-native-fetch-blob": "^0.10.8",
    "react-native-google-places-autocomplete": "^1.3.5",
    "react-native-gravatar": "^1.0.2",
    "react-native-htmlview": "^0.12.0",
    "react-native-i18n": "^2.0.2",
    "react-native-image-picker": "^0.26.3",
    "react-native-img-cache": "^1.4.0",
    "react-native-inviewport": "^1.1.0",
    "react-native-keyboard-aware-scrollview": "^1.1.7",
    "react-native-linear-gradient": "^2.2.0",
    "react-native-path": "0.0.3",
    "react-native-render-html": "^2.1.0",
    "react-native-router-flux": "^4.0.0-beta.1",
    "react-native-share": "^1.0.21",
    "react-native-snap-carousel": "^2.4.0",
    "react-native-svg": "5.1.3",
    "react-native-uploader": "0.0.10",
    "react-navigation": "^1.0.0-beta.7",
    "react-redux": "^5.0.4",
    "redux": "^3.6.0",
    "redux-form": "^7.0.4",
    "redux-logger": "^3.0.1",
    "redux-persist": "^4.6.0",
    "redux-thunk": "^2.2.0",
    "tcomb-form-native": "^0.6.9",
    "url": "^0.11.0",
    "util": "^0.10.3",
    "wpapi": "^1.0.3"
  },
...
```

**Comment by radko93** [comment]
Your react-navigation version is too old I guess. Might be the same for other dependencies like rn svg.

**Comment by radko93** [comment]
@facebook-github-bot stack-overflow

**Comment by radko93** [comment]
Something failed @hramos, I'm not sure if @mkonicek is active recently.

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
