### ISSUE TITLE
TextInput,How can i use 'onSubmitEditing'  when 'multiline={true}' and 'blurOnSubmit={false}'

### ISSUE THREAD

**Issue by huanghaodong** [facebook/react-native#15995]
‘Note that for multiline fields, setting blurOnSubmit to true means that pressing return will blur the field and trigger the onSubmitEditing event instead of inserting a newline into the field.’
   But according to the project needs, 'blurOnSubmit’ must be false and 'multiline' must be 'true'.What should i do?

**Comment by chirag04** [comment]
@facebook-github-bot stack-overflow

**Comment by chirag04** [comment]
@huanghaodong please follow the issue template going forward.
