### ISSUE TITLE
Some bugs when I see the documents,I hope you will fix this

### ISSUE THREAD

**Issue by yangqingxian** [facebook/react-native#15996]
# The page is always on the button

When i read the whole page,I'm in the bottom of the web page,but when i choose a new link,the new page comes out ,i still in the bottom.I hope when the new page came out, i can go back to the top,or there is link,i can go to the top quickly.

# The page is locked

Sometimes when you read the web page,and it's just suddenly locked,you can choose to open a new page.The web browser will show to downloading,but still not working.I don't know why.

# The Example is too long

I just start to learn react-native.I want to know some UI components's functions.But the example is too long, it's hard for me to understand it.

**Comment by chirag04** [comment]
@yangguang2009 i'm not sure what we can do to improve things here but feel free to send a PR. in light of keeping the issue tracker focused, i'm going to close this.
