### ISSUE TITLE
Wrong initial state using useNativeDriver: true and production bundle

### ISSUE THREAD

**Issue by ferrannp** [facebook/react-native#16003]
### Is this a bug report?

Yes.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes.

### Environment

1. `react-native -v`: 0.48.3
2. `node -v`: 8.4.0
3. `npm -v`: 5.4.2
4. `yarn --version`: 1.0.2

Then, specify:

- Target Platform: Android O

- Development Operating System: macOS

### Steps to Reproduce

1. Use `onScroll` event on `FlatList`
```js
onScroll={Animated.event(
  [{ nativeEvent: { contentOffset: { y: scrollY } } }],
  { useNativeDriver: true }
)}
```

2. Use the value for some interpolations:

```js
const imageTranslate = scrollY.interpolate({
  inputRange: [0, bannerHeight],
  outputRange: [0, -bannerHeight],
  extrapolate: 'clamp',
});

const opacityInterpolator = scrollY.interpolate({
  inputRange: [bannerHeight-56-24-24, bannerHeight-56-24],
  outputRange: [0, 1],
  extrapolate: 'clamp',
});

const fontScale = scrollY.interpolate({
  inputRange: [0.0, bannerHeight-56-24],
  outputRange: [1.5, 1.0],
  extrapolate: 'clamp',
});

const fontTranslateX = scrollY.interpolate({
  inputRange: [0, bannerHeight-56-24],
  outputRange: [0, -24],
  extrapolate: 'clamp',
});

const fontTranslateY = scrollY.interpolate({
  inputRange: [0, bannerHeight - 56 - 24],
  outputRange: [0, -bannerHeight + 56 + 24],
  extrapolate: 'clamp',
});
```

3. Apply them to `Animated.View` and `Animated.Text`. With state `scrollY: new Animated.Value(0)`, the View should have 0 opacity and the text should be big (initial state).

### Expected Behavior

See gif:

![expected](https://user-images.githubusercontent.com/774577/30587971-5321e774-9d35-11e7-84a2-94e0b726fa19.gif)

### Actual Behavior

![actual](https://user-images.githubusercontent.com/774577/30587990-5c2097bc-9d35-11e7-992c-cb647df257fe.gif)

The issue happens **only in production** and in my real device (Nexus 5X) which is now using Android O. I cannot reproduce it in Genymotion. Initial state is wrong and it goes ok just when touching and scrolling a bit.

### Temporal solution

```js
this.state = {
  scrollY: new Animated.Value(0),
  useNativeDriver: true,
};

componentDidMount() {
  setTimeout(() => this.setState({ useNativeDriver: true }), 10);
}
```

**Comment by satya164** [comment]
cc @janicduplessis

**Comment by ferrannp** [comment]
Temporal solution does not really work always. At some point, if I click something in the list, the bug reappears.

**Comment by janicduplessis** [comment]
I'm not sure if it is the issue but could you try with this PR https://github.com/facebook/react-native/pull/15919?

**Comment by ferrannp** [comment]
Ok, gonna try that and let you know.

**Comment by janicduplessis** [comment]
@ferrannp Hmm I'm not sure what could cause the issue in prod only. I'm around on the Expo slack if you want to give me more info I can try to help.
