### ISSUE TITLE
[ListView] ListView momentum scroll bug

### ISSUE THREAD

**Issue by magicismight** [facebook/react-native#1600]
As the gif shows ,I dragged the ListView quickly to make a momentum scroll. and stop hold for few seconds and then release the drag. The ListView scrolls anyway.
BTW: my react-native version is 0.5.0, and the ScrollViews are in a navigator.
![scroll-bug](https://cloud.githubusercontent.com/assets/7693239/8122383/b51f29c4-10eb-11e5-9f06-e2496a2756d3.gif)

**Comment by magicismight** [comment]
It happens in ScrollView too.It should be a ScrollView bug.

**Comment by jaygarcia** [comment]
Is it a bug or does your list view not buffer ahead of time enough?

**Comment by magicismight** [comment]
@jaygarcia 
I think it is a bug,it happens in ScrollView too,not just in ListView.
Drag quickly to make a momentum scroll and then stop drag but do not release the cursor. After a few seconds release the cursor.It will continue the momentum scroll.

**Comment by sahrens** [comment]
I think this is an ios issue in the simulator.  Do you ever see this particular bug on device?

**Comment by josebalius** [comment]
@sahrens I think this is happening on a device as well, at least on a iPhone 5s that I am testing with. I'll do more debugging but it looks like a real issue.

**Comment by jaygarcia** [comment]
@josebalius , this is is a normal behavior of the ListView component.  I see the same problem in my apps.

One way to mitigate is to tweak:

```
                    initialListSize={30} 
                    pageSize={30} 
                    scrollRenderAheadDistance={300} 
```

![pulldown](https://cloud.githubusercontent.com/assets/180031/9098651/261585d8-3b99-11e5-8687-daf80ab5649b.gif)

**Comment by magicismight** [comment]
This is a issue in the simulator.Not on the device.
So just ignore it.

**Comment by jaygarcia** [comment]
Makes no sense how that could be, but awesome :)
