### ISSUE TITLE
Released react-native app on playstore but it's not supporting as expected

### ISSUE THREAD

**Issue by MahbbRah** [facebook/react-native#16001]
I created a `react-native` app but unfortunately, it's not supporting many devices including 4.1 version. it's not supporting 4.1, 4.2 and so on even I checked with 5.1.1 device also but it's always saying apps not compatible with the device when I'm trying to install from play store.
I created this app with `minSDKVersion 16`   but it's not working on 16,17,18,19 and all that..
here is the URL for my APP: https://play.google.com/store/apps/details?id=com.letschatanonymously
Before uploading on play store I checked my app it is working on the same device. But after uploading it to play store it say's not compatible with the device. I don't know why, Please help.

My gradle config:
`android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    defaultConfig {
        applicationId "com.letschatanonymously"
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 2
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    signingConfigs {
        release {
            if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
                storeFile file(MYAPP_RELEASE_STORE_FILE)
                storePassword MYAPP_RELEASE_STORE_PASSWORD
                keyAlias MYAPP_RELEASE_KEY_ALIAS
                keyPassword MYAPP_RELEASE_KEY_PASSWORD
            }
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk true  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}`

**Comment by chirag04** [comment]
@facebook-github-bot stack-overflow

**Comment by MahbbRah** [comment]
Actually, I currently blocked to post on there. so Please if there is any consideration to keep it here. and figure out a solution.

**Comment by chirag04** [comment]
@MahbbRah https://facebook.github.io/react-native/support.html
