### ISSUE TITLE
Switch of android will cause a NullPointerException

### ISSUE THREAD

**Issue by 4ndroidev** [facebook/react-native#16000]
### Is this a bug report?

(Yes)

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(No)

### Environment

1. `react-native -v`: 2.0.1
2. `node -v`: 6.11.1
3. `npm -v`: 5.3.0
4. `yarn --version`: 0.27.5

Then, specify:

- Target Platform: Android

- Development Operating System: macOS

- Build tools: Android Studio

### Steps to Reproduce

(Write your steps here:)

1. using library `com.android.support:appcompat-v7:24.2.1`
2. using component `<Switch />`

### Expected Behavior

display a `Switch` component

### Actual Behavior

![switch-crash](https://user-images.githubusercontent.com/27715835/30579177-24641a5a-9d4a-11e7-99df-4b41492a4724.jpg)

### Reason
<img width="996" alt="switch-reason" src="https://user-images.githubusercontent.com/27715835/30579378-0331bf4e-9d4b-11e7-81e9-eff8c6f3349e.png">

from this picture, `line 59` and `line 102` create instance of ReactSwitch; 

the difference: 
1. the first one hasn't called `setShowText(false)`, it will get the error of the red box, while calling `measure`.
2. the second one has called `setShowText(false)`, that's right.

how to fix:

follow `line 59`, insert a new line `reactSwitch.setShowText(false);`

if using `com.android.support:appcompat-v7:23.0.1`, it will not get this error; but i think this error can be avoided without downgrading `appcompat-v7` library. Sorry for my poor english, thank you!

**Comment by janicduplessis** [comment]
Thanks for reporting this, would you like to send a PR with your fix?

**Comment by Fortidude** [comment]
react-native-cli: 2.0.1
react-native: 0.50.3

"com.android.support:appcompat-v7:25.3.1"

Still buggy, Can someone fix it? :) 

<img width="342" alt="zrzut ekranu 2017-12-03 o 13 16 22" src="https://user-images.githubusercontent.com/8781462/33525253-366c75ae-d82c-11e7-9d9c-54e4cbfaa175.png">

**Comment by Fouppy** [comment]
@Fortidude you should ping there https://github.com/facebook/react-native/pull/16064

**Comment by Fortidude** [comment]
@Fouppy oke, thx
