### ISSUE TITLE
Error loading local image

### ISSUE THREAD

**Issue by mahdiG** [facebook/react-native#16007]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

1. `react-native -v`: command not found
2. `node -v`: v7.9.0
3. `npm -v`: 4.2.0
4. `yarn --version`: 1.0.2

Then, specify:

- Target Platform: Android and iOS

- Development Operating System: Debian 9.1

- Build tools: Running app in Expo

### Steps to Reproduce

(Write your steps here:)

1. Create project with CRNA
2. Run app in Expo
3. Create a method with a path argument
4. load image using source(path) in that method
5. Declare that method and give it a local path to an image

### Expected Behavior

Image should load

### Actual Behavior

Image doesn't load and expo gives warning:
```
Possible Unhandled promise rejection (id:0):
Error: Unknown named module: 'image.jpg'
_require@http://192.168.1.113:19001/./node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=android&dev=true&hot=false&minify=false:46:22
makeCard@http://192.168.1.113:19001/./node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=android&dev=true&hot=false&minify=false:113251:36
render@http://192.168.1.113:19001/./node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=android&dev=true&hot=false&minify=false:113288:30
http://192.168.1.113:19001/./node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=android&dev=true&hot=false&minify=false:26349:31
```

(Write what happened. Add screenshots!)

### Reproducible Demo

This code works:
```
import React, {Component} from 'react'
import {Image, ScrollView, StyleSheet, Text} from 'react-native'


export default class Catagory extends Component {
    makeCard(text) {

        return (

            <Image source={require("./image.jpg")}>
                <Text>{text}</Text>
            </Image>

        )
    }

    render() {

        return (
            <ScrollView contentContainerStyle={styles.container}>
                {this.makeCard("Animation")}
            </ScrollView>
        )
    }
}
```
![screenshot_20170919-154154](https://user-images.githubusercontent.com/4989445/30589815-33d65b40-9d51-11e7-9907-dde4ed3ac2ca.png)

But this one gives error:
```
import React, {Component} from 'react'
import {Image, ScrollView, StyleSheet, Text} from 'react-native'


export default class Catagory extends Component {
    makeCard(text , path) {

        return (

            <Image source={require(path)}>
                <Text>{text}</Text>
            </Image>

        )
    }

    render() {

        return (
            <ScrollView contentContainerStyle={styles.container}>
                {this.makeCard("Animation" , "./image.jpg")}
            </ScrollView>
        )
    }
}
```
![screenshot_20170919-153355](https://user-images.githubusercontent.com/4989445/30589848-551963c4-9d51-11e7-968c-dd3d0cbbe3ac.png)
![screenshot_20170919-153358](https://user-images.githubusercontent.com/4989445/30589855-5a334bc2-9d51-11e7-9860-5a10b8fa649e.png)
I simplified the code by removing the styling...

**Comment by chirag04** [comment]
static images should be required statically for the packager to correctly bundle them(your first case). RN does not support dynamic require of assets or modules like that since there is not way for the package to know which files to include in the bundle unless we support a way to explicitly pass a list of such assets to the packager . this a client environment which is not the same as nodejs environment. 

Refer this document for some good vs bad patterns: https://github.com/facebook/react-native/blob/1e8f3b11027fe0a7514b4fc97d0798d3c64bc895/docs/Images.md
