### ISSUE TITLE
A TextInput with nested child components and an onChangeText handler to prevent a newline still adds a newline

### ISSUE THREAD

**Issue by davidkpham** [facebook/react-native#16012]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

1. `react-native -v`: 0.48.3
2. `node -v`: 8.4.0
3. `npm -v`: 5.3.0
4. `yarn --version`: 0.27.5

Then, specify:

- Target Platform: iOS

- Development Operating System: macOS

- Build tools: XCode

### Steps to Reproduce

In summary, I am building a rich text editor with each paragraph being represented by a TextInput. In order to add rich functionality (e.g. add a mention that is styled differently and should be treated as a whole) within each paragraph and thus each TextInput, I am using TextInput's ability to nest and display children components instead of using its value prop which would only support plain text.

The wrinkle is that I am also using onChangeText on each TextInput to catch newlines and instead go to the next TextInput which highlights a discrepancy between displaying the TextInput's value using the value prop vs. nesting children components.

When I use the value prop on each TextInput to display the state of its content (albeit in plain text), everything works as expected: the TextInput displays the state of its content and when I press enter, instead of adding a newline, it goes to the next TextInput.

When I instead use the TextInput's ability to nest and display children components, it correctly displays the state of its content but when I press enter, it adds a newline and then goes to the next TextInput. Interestingly, the newline is not reflected in the state of its content.

I've tried a couple workarounds like setting blurOnSubmit to true and adding an onSubmitEditing handler, but it causes the keyboard to dismiss/re-appear funkily. It does prevent the newline though.

### Expected Behavior

When I use TextInput with an onChangeText handler that prevents newlines (by not updating the state of that TextInput's content) and nest children components inside to display its content, pressing enter should not add a new line.

### Actual Behavior

When I use TextInput with an onChangeText handler that prevents newlines (by not updating the state of that TextInput's content) and nest children components inside to display its content, pressing enter adds a newline.

### Reproducible Demo

https://gist.github.com/davidkpham/09be8954ed995285c200d3dfd6b73ffd

**Comment by bsbechtel** [comment]
@davidkpham did you ever have any luck finding a way around this? I'm facing a similar issue.

**Comment by davidkpham** [comment]
Hey @bsbechtel, unfortunately I did not - since this functionality is critical to our app, I ended up just going native.

**Comment by lxcid** [comment]
In case anyone need a clever hack to work around this before 0.54.0, You can force a re-render but setting style.color.

My workaround is to use `hsla()` for my color, and use alternate between to logically same color.

e.g.

`hsla(0, 0%, 20%, 1.0)` and `hsla(0, 0%, 20%, 1.00)` are logically similar but will trigger a re-render and kinda fix this issue.
