### ISSUE TITLE
Should I continue using react and react-native?

### ISSUE THREAD

**Issue by bochen111** [facebook/react-native#16018]
### Is this a bug report?

(write your answer here)

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.)

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by sisyphsu** [comment]
NO

**Comment by Jonovono** [comment]
Listen to your heart

**Comment by sibelius** [comment]
stop using react-native and stop opening issues like this one

**Comment by fakhrawy** [comment]
why react team not giving us the ability to close like this discussions

**Comment by hramos** [comment]
@fakhrawy you can! We are in sore need of contributors to help out with issues. Read the docs to learn how to use the GitHub bot to manage issues: http://facebook.github.io/react-native/docs/contributing.html#triaging-issues-and-pull-requests
