### ISSUE TITLE
Android Font and Screen Scaling issue for Worklight Hybrid App

### ISSUE THREAD

**Issue by Dipal1512** [facebook/react-native#16016]
My app is hybrid app with worklight(7.1.0) and cordova. From Aug 28 the fonts and screen is enlarged and the UI looks too ugly. Is there a way to do the font scale for hybrid app. Also the Mobile accessibility plugin of cordova is not working neither the changes to the viewports?

**Comment by Diwei-Chen** [comment]
Hi @Dipal1512 , I met the issue as well after I started to build my app on Android. Have you solved it yet?
