### ISSUE TITLE
App.js issue 

### ISSUE THREAD

**Issue by vindicoryank** [facebook/react-native#16010]
I'm new to this coding stuff but can anyone help me out? 
It's only recently just started happening,

![screenshot_1](https://user-images.githubusercontent.com/29656587/30599859-b6f1c63c-9d55-11e7-900a-b04d458c9b28.png)

**Comment by chirag04** [comment]
@vindicoryank sorry, unfortunately this is not the right forum for this issue. That said,  looking at the error, it looks like you have a typo in the package.json. check for trailing `,`
