### ISSUE TITLE
RN 0.48.4 was tagged but not released

### ISSUE THREAD

**Issue by vovkasm** [facebook/react-native#16022]
### Is this a bug report?
Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?
Yes

### Environment
Environment:
  OS:  macOS Sierra 10.12.6
  Node:  8.5.0
  Yarn:  Not Found
  npm:  5.4.2
  Watchman:  4.9.0
  Xcode:  Xcode 8.3.3 Build version 8E3004b
  Android Studio:  2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: 0.48.3 => 0.48.3

### Steps to Reproduce

1. Project tests fails because of #15810, and this was fixed in 0.48-stable branch in 355eaf72b6c8775abf4edc8b8bd29e60db62af08, release tag was created in b61fe7fe80681ee23f6f6b35839d73e745cb0ec7
2. `npm outdated` in project dir to see that update available
3. `npm info react-native | grep 0.48.4` to confirm that version 0.48.4 available

### Expected Behavior

`npm outdated` should show something like:
```
Package                              Current           Wanted  Latest  Location
babel-preset-react-native              2.1.0            2.1.0   4.0.0  MyProject
react                        16.0.0-alpha.12  16.0.0-alpha.12  15.6.1  MyProject
react-native                          0.48.3           0.48.3  0.48.4  MyProject
react-test-renderer          16.0.0-alpha.12  16.0.0-alpha.12  15.6.1  MyProject
```

`npm info react-native | grep 0.48.4` should return something like (time can be differrent):
```
'0.48.4': '2017-09-18T22:40:23.133Z'
```

### Actual Behavior

`npm outdated` don't show react-native 0.48.4:
```
Package                              Current           Wanted  Latest  Location
babel-preset-react-native              2.1.0            2.1.0   4.0.0  MyProject
react                        16.0.0-alpha.12  16.0.0-alpha.12  15.6.1  MyProject
react-test-renderer          16.0.0-alpha.12  16.0.0-alpha.12  15.6.1  MyProject
```

`npm info react-native | grep 0.48.4` don't return anything

**Comment by grabbou** [comment]
I am going to close this issue. I've removed the tag and scheduled yet another build. Looks like it failed because of website step which means there could've been race condition between few builds.

**Comment by vovkasm** [comment]
Ok. Will wait. Just for notice. Recently I published to npm and was requested to confirm profile email. Publish to profiles with unconfirmed emails is locked...

**Comment by vovkasm** [comment]
@grabbou People opens new bugs because you close and not reopen this one. You close this issue too early without test first, not a good practice :-/

Duplicate: #16074
