### ISSUE TITLE
onPress custom CallBack Funtion

### ISSUE THREAD

**Issue by hai2014bk** [facebook/react-native#16020]
Hi there, i want to custom TouchOpacity by creat new Component, but i'm facing this, that i can't custom onPress Callback Function, i mean, onPress not fire when i touch

This is my custom Component 
`onPressFuntion(){
		this.props.onPress
	}
render = () => {
    const { style, children } = this.props;
    return (
      <TouchableOpacity disabled={this.state.disabled} onPress={() => this.onPressFuntion.bind(this)} style={style}>
       			{children}
      </TouchableOpacity>
    );
  }
}`

and this is how i use is 
`<TouchAble
					  rounded
					  style={styles.loginBtn}
					  onPress={() => this.loginClick()}
					>
					  <Text
						style={
						  { fontSize: 20, color: "white" }
						}
					  >
						Đăng Nhập
					  </Text>
					</TouchAble>`

So any Help??

**Comment by finian** [comment]
```
<TouchableOpacity 
  disabled={this.state.disabled} 
  onPress={() => this.onPressFunction()}
  // or
  onPress={this.onPressFunction.bind(this)}
  // or
  // define onPressFunction as `onPressFuntion = () => {}`
  onPress={this.onPressFunction}
  style={style}
>
```

**Comment by hai2014bk** [comment]
@finian i tried but when i used it like this 
`<TouchAble rounded style={styles.loginBtn} onPress={() => this.loginClick()} > <Text style={ { fontSize: 20, color: "white" } } > Đăng Nhập </Text> </TouchAble>`

my loginClick() didn't called

**Comment by finian** [comment]
@hai2014bk 

Make sure you call this.props.onPress in your `onPressFuntion`

```
onPressFuntion() { this.props.onPress() } // <-- ()
```

**Comment by janicduplessis** [comment]
@facebook-github-bot stack-overflow
