### ISSUE TITLE
[Android] Image not show ,if the image src not have Image Format

### ISSUE THREAD

**Issue by YuZhongMa** [facebook/react-native#16029]
if the img src is 'http://images/branding/googlelogo/2x/googlelogo_color_272x92dp' not
'http://images/branding/googlelogo/2x/googlelogo_color_272x92dp.png'

**Comment by mealleader** [comment]
i also got this issue after upgrading to 0.49.0, why is this issue closed? is there any solution? @hramos

**Comment by hramos** [comment]
Hi @mealleader, we have some guidelines in place to make sure issues are actionable. For example, we provide a template with all the information that needs to be filled out. Not following the template may result in an issue getting closed without explanation.
