### ISSUE TITLE
startReactApplication bundle contains a HashMap,red screen 'Could not convert java.util.HashMap'

### ISSUE THREAD

**Issue by jf4444** [facebook/react-native#16026]
### Is this a bug report?

(Yes)

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(YES)

### Environment

Environment:
  OS:  macOS Sierra 10.12.6
  Node:  8.2.0
  Yarn:  0.27.5
  npm:  5.4.2
  Watchman:  4.7.0
  Xcode:  Xcode 8.3.3 Build version 8E3004b
  Android Studio:  2.3 AI-162.3934792

Packages: (wanted => installed)
  react: ^16.0.0-alpha.12 => 16.0.0-rc.3
  react-native: 0.48.1 => 0.48.1

### Steps to Reproduce

(Write your steps here:)

1.In my pure native app,I creat a activity add a mReactRootView
2.when I use mReactRootView's method 'startReactApplication' to pass a bundel which contains a HashMap
3.I got a red screen,the message is 'could not convert class java.util.HashMap'

4:in react native 0.44,It's ok

### Expected Behavior

run ok in android device 

(Write what you thought would happen.)

### Actual Behavior

(I got a red screen,the message is 'could not convert class java.util.HashMap')

![8730aac18260de2d12dfec8d66695630](https://user-images.githubusercontent.com/2690128/30634472-cf5b9a28-9e21-11e7-97f6-fc7c0d93daf6.png)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by jf4444** [comment]
I hava resolve this problem,In new version of react native, startReactApplication  to pass a bundel which contains a HashMap is wrong, must translate the HashMap to a bundle

**Comment by jose920405** [comment]
Thanks @jf4444 Using `Bundle` is the fix
