### ISSUE TITLE
[RN 0.48.3 TextInput] onSubmitEditing not called if blurOnSubmit set to false

### ISSUE THREAD

**Issue by snksergio** [facebook/react-native#16038]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

react-native -v: 0.48.3
node -v: 8.4.0
npm -v: 4.6.1
yarn --version:
Target Platform: Android
Development Operating System: Windows 10
Build tools:
react-native run-android

### Steps to Reproduce

1.
`<TextInput
          placeholder="one"
          blurOnSubmit={ false }
          onSubmitEditing={() => {
            this.focusNextField('two');
          }}
          returnKeyType={ "next" }
          style={styles.textInput}
          ref={ input => {
            this.inputs['one'] = input;
          }}
        />
        <TextInput
          placeholder="two"
          blurOnSubmit={ false }
          onSubmitEditing={() => {
            this.focusNextField('three');
          }}
          returnKeyType={ "next" }
          style={styles.textInput}
          ref={ input => {
            this.inputs['two'] = input;
          }}
        />`

2. If I press the **next** button onSubmitEditing callback not called

### Expected Behavior

onSubmitEditing should be called for blurOnSubmit={false} text inputs
In other versions it works normally, in 48.3 I need to remove the blurOnSubmit = {false} so that the focus goes to the next input

### Reproducible Demo
[](https://medium.com/reactnative/tabbing-through-input-fields-ef283f923ab1)
https://medium.com/reactnative/tabbing-through-input-fields-ef283f923ab1

**Comment by nhuthan** [comment]
+1

**Comment by re-deku** [comment]
+1

**Comment by ericlewis** [comment]
+1

**Comment by douglasjunior** [comment]
Same problem here.

**Comment by masterpetit** [comment]
I encountered the same problem. The onSubmitEditing callback in not called if the prop blurOnSubmit={false}.

**Comment by kot-ezhva** [comment]
+1

**Comment by brunocascio** [comment]
It does not work in `ˆ0.46.0` as well...

**Comment by jankarres** [comment]
+1

**Comment by sergeyzhukov** [comment]
+1

**Comment by MLStoltzenburg** [comment]
+1

**Comment by re-deku** [comment]
+1

**Comment by ido-kang** [comment]
+1

**Comment by joncursi** [comment]
Works on iOS in 0.49.1 but not Android. See linked issue above

**Comment by shergin** [comment]
Can anyone confirms that is still broken on master (I think @rsnara fixed something like that ~ week ago).

If this is sill an issue, @snksergio, could you please create a Snack?

**Comment by 8of** [comment]
@shergin Yes, the problem persist in latest react-native *0.49.1* on Android.

**Comment by 8of** [comment]
Snack to illustrate an issue: https://snack.expo.io/BJap1QE3b

**Comment by shergin** [comment]
@8of, master is not the same as 0.49.1.

**Comment by joncursi** [comment]
The 0.49.1 release notes stated that this fix was included. Either the bug is still present after the “fix” or the fix wasn’t cherry picked into 0.49.1 and the release notes are wrong

**Comment by 8of** [comment]
@shergin Good to know.
I tried master branch and the is no problem with `onSubmitEditing` on **master**. 👍 
How we can help to push this change to next React Native release?

**Comment by shergin** [comment]
@8of It will be in the next major release. You also can advocate to include this change in the future minor update; somewhere here should be the issue where you can propose the cherry pick.

**Comment by 8of** [comment]
@shergin how can I propose commit for cherry picking if I don't know which commit fixed the issue?

**Comment by nhuthan** [comment]
still not work in RN 0.49.3 (android 7.1.2)

**Comment by kesepara** [comment]
+1

**Comment by rtman** [comment]
can confirm that this issue persists in 0.49.3

**Comment by ccdwyer** [comment]
Working as expected now in 0.50.3.

**Comment by thambt** [comment]
hi. i have same problem in react native 0.49.3. Please help me how to fix, thanks!

**Comment by masterpetit** [comment]
@thambt the bug is fixed in ```"react-native": "0.50.x"```
