### ISSUE TITLE
Disk usage grows indefinitely with app's use

### ISSUE THREAD

**Issue by daesan** [facebook/react-native#16035]
### Is this a bug report?

Yes.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes.

### Environment

Environment:
  OS:  macOS Sierra 10.12.6
  Node:  6.11.0
  Yarn:  Not Found
  npm:  3.10.10
  Watchman:  Not Found
  Xcode:  Xcode 8.3.3 Build version 8E3004b
  Android Studio:  2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: ^0.48.3 => 0.48.3

### Steps to Reproduce

My app is iOS only and is implemented entirely with RN.

My app has the timeline of user posts, each post containing 1 to 4 photos. The timeline is implemented using FlatList. Heavy users spend several hours on the app everyday scrolling the timeline and reading/writing posts.

The problem is that the app's disk usage grows steadily and indefinitely. Using the app several hours a day for like a month, the disk usage grows up to 3-4 GB. (I am checking this from "Document & Data" section in Settings.)

I am not explicitly saving anything to the disk, except for a few bytes of configuration data using AsyncStorage.

### Expected Behavior

I am not quite sure what's happening. Could this be a image caching issue? Maybe, but I would image that the cache size is fixed at certain number.

At any rate, the disk usage should be constant or at least should come back down when I quit the app.

### Actual Behavior

However, the disk usage grows and grows and grows. It grows indefinitely. One user reported that his app's data size has grown up to 10 GB.

Looking at the "Debug navigator" in xCode, Disk Writing stats doesn't seem to catch this disk usage growth. I deleted and reinstalled the app, after scrolling the timeline for several minutes, iOS is telling me that my app is using 12.3 MB of disk storage. Debug navigator's Disk Writing stats says it has written only 0.3 MB of data.

My app is in production now and this issue has become quite a troublesome issue for my users. If anyone can image where the issue may be stemming from, please share your views. Any help will be very much appreciated.

**Comment by daesan** [comment]
For some reason, this issue seems to disappear with iOS 11 upgrade. It is present with iOS 10, however.

**Comment by slickdev** [comment]
I'm experiencing this issue as well. Running MacOS Sierra 10.12.6 developing an iOS app. The app I'm creating plays videos and edits them, then saves to camera roll. I've deleted all of the processed videos from camera roll on my development device, so this must be something else. I just discovered the issue and it's currently at 17.5GB in size.

**Comment by janicduplessis** [comment]
I think we are using NSCache internally, could be a bug in iOS 10. Not sure what the best solution would be here.

**Comment by slickdev** [comment]
In my case, I implemented the filesystem package and manually deleted the /tmp/ folder on the last page of my app, it seemed to have solved the issue for me.

**Comment by joshbax** [comment]
Seeing this issue on iOS 11.0.3. Disk usage grows at a healthy 80kb/s when foregrounded.
