### ISSUE TITLE
[NavigatorIOS] Navigator overlay NavigatorIOS bar

### ISSUE THREAD

**Issue by alvaromb** [facebook/react-native#1603]
Is it possible for a ``Navigator`` component to overlay ``NavigatorIOS`` navigation bar? I can't make the modal transition of the JS navigator to overlay the native navigation bar.

**Comment by alvaromb** [comment]
This is an example of the issue. Looks confusing to open a modal an still have a navigation with a back button that does not close the modal.

![modal](https://cloud.githubusercontent.com/assets/289640/8125964/c24a061a-10ea-11e5-968b-5409bf451121.gif)

**Comment by ide** [comment]
I would try putting the NavigatorIOS component inside of the Navigator (it might not work because it takes extra work to set up UIViewControllers inside of arbitrary views but worth a shot).

**Comment by sahrens** [comment]
yeah, you probably just don't want to mix these...but passing to Eric in case he's thought about this more.

**Comment by ericvicenti** [comment]
Yeah, combining navigator with the native navigator is not very well supported. But I suspect it will work if you put the Navigator outside of NavigatorIOS

**Comment by paramaggarwal** [comment]
@alvaromb `NavigatorIOS` has a `navigationBar` and a `view`. When you nest `Navigator` inside it, it is being drawn into the `view`. Then `NavigatorIOS` draws the `navigationBar` on top of the `view`. Hence the `view` has no way to come on top of the `navigationBar`.

Please try the suggestion by @ericvicenti and share here!

**Comment by alvaromb** [comment]
Thank you for your replies. I'll try that as soon as I can @paramaggarwal, but I'm facing a tremendous amount of work right now and this has been removed from my top priority list. I expect I'll be able to try this on Friday.

**Comment by alvaromb** [comment]
I've switched from ``NavigatorIOS`` with a ``Navigator`` to display the modal to a full ``Navigator`` navigation.

However, if I set a ``navigationBar`` in the parent ``Navigator``, it stays on top of the modal-``Navigator``.

This is the render code for the main ``Navigator``:

```javascript
return (
<Navigator
    navigationBar={
        <Navigator.NavigationBar
            style={styles.navBar}
            routeMapper={MnmNavigationBarRouteMapper}
        />
    }
    initialRoute={{
        title: this.state.selectedTab,
        component: MnmPublished,
        passProps: {section: this.state.selectedTab}
    }}
    renderScene={(route, nav) => {
        var props = route.passProps;
        props.navigator = nav;
        return React.createElement.bind(this)(
            route.component, props
        );
    }}
    configureScene={(route) => {
        if (route.sceneConfig) {
            return route.sceneConfig;
        }
        return Navigator.SceneConfigs.FloatFromRight;
    }}
/>
);
```

This is how I open another ``Navigator`` (the "modal" component):

```javascript
this.props.navigator.push({
    index: 1,
    component: MnmCommentsContainer,
    sceneConfig: Navigator.SceneConfigs.FloatFromBottom,
    passProps: {entryId: entrada.id}
});
```

And this is the code for the "modal" component:

```javascript
render() {
    return (
        <Navigator
            renderScene={(route, navigator) => (
                <MnmComments entryId={this.props.entryId}/>
            )}
            initialRoute={{
                title: 'Comentarios'
            }}
            navigationBar={
                <Navigator.NavigationBar
                    routeMapper={MnmNavigationBarRouteMapper}
                    style={styles.navBar}
                />
            }
        />
    );
}
```

This last ``navigationBar`` is the one that has the red background. What I would like to achieve is  a *stacked* (right-to-left) navigation similar to the iOS native one and open a modal-like transition from one of the previously navigated views (something which I think is quite common in iOS app navigation). That modal should overlay the content that's behind. I would also like to prevent the right-to-left transition in the root ``navigationBar`` if possible.

![modal](https://cloud.githubusercontent.com/assets/289640/8235621/309c23ee-15e3-11e5-9b58-834d2d1a1533.gif)

**Comment by alvaromb** [comment]
Another thing that bugs me is that setting the content to ``flex: 1`` with the custom ``navigationBar`` displays the content a couple of points behind the navigation bar, preventing the first element to be correctly displayed.

**Comment by ide** [comment]
This is intentional. You should use content insets or top padding if you don't want that effect.

**Comment by alvaromb** [comment]
Thanks @ide! I've realised about that a while ago so I decided to close the issue :smile:

**Comment by ButuzGOL** [comment]
From this conversation I can't find solution
May be somebody will help
Here what I have
![overlay](https://cloud.githubusercontent.com/assets/196564/10186962/3b680b9e-6755-11e5-860b-961eed2409fa.gif)
But I need Red one should overlay Green one NavBar

**Comment by alvaromb** [comment]
@ButuzGOL you can wrap your views in two ``<Navigator />`` components. Take my pseudocode as an example:

```js
<Navigator ref='topNavigator'
  render={() => {
    <Navigator ref='innerNavigator' render={ ... } />
  }}
/>
```

Then you use ``innerNavigator`` to make push-like transitions from right to left with a navigation bar. When you want to open your red modal and overlay the other views, use a ``Navigator.SceneConfigs.FloatFromBottom`` transition and make the ``push`` from ``topNavigator`` instead of ``innerNavigator``. 

Let me know if you have any trouble setting up this :smile:

**Comment by ButuzGOL** [comment]
@alvaromb thanks for comment
but I made it using http://facebook.github.io/react-native/docs/modal.html#content
So you can add there Navigator and it works like I expected

**Comment by alvaromb** [comment]
Cool @ButuzGOL! Modal it's a very nice component but keep in mind that if you render some kind of picker component there, chances are that you're not going to get it rendered because of this https://github.com/facebook/react-native/issues/2628 bug.

**Comment by IlyasM** [comment]
@alvaromb what if you set navigationBarHidden to true when you push your Navigator or modal schene for NavigatorIOS? would that work?

**Comment by alvaromb** [comment]
Haven't tried that @IlyasM, but honestly the nested ``<Navigator />`` is the way to go.
