### ISSUE TITLE
Support for Data Blobs?

### ISSUE THREAD

**Issue by austinksmith** [facebook/react-native#16034]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

All

### Steps to Reproduce

Create a React Native application and attempt to create a data blob, error is created saying a "Blob can only be created from another Blob".

### Expected Behavior

A data blob is created the same as it works for all other JavaScript execution environments

### Actual Behavior

Support for data blobs appears broken with an error message of "Data blob can only be created from another blob"

### Reproducible Demo

You may make use of my library Hamsters.js to see this in action, simply follow the instructions to import the library into a React Native application. A user of my library has reported this bug to me and I would really like to see support for my library brought back as it relies on data blob creation for efficient operation, the alternatives are bad for performance. 

https://github.com/austinksmith/Hamsters.js/issues/40

**Comment by austinksmith** [comment]
Any response on this? Curious on how to create *new* data blobs in RN

**Comment by shoebmogal** [comment]
I am experiencing the same issue. Curious to know the work around.

**Comment by EduardJS** [comment]
Same thing here. Was just trying to upload some files with Firebase Storage in a react native app, used RNFS to get the actual file, all works fine, but when I actually try and upload it, this errors pops up, and I guess Firebase uses this type of blob ( out of base64 strings ) as well ..

**Comment by jsappme** [comment]
same thing in here, it used to work with the previous react native version.

**Comment by serhiipalash** [comment]
@EduardJS I have the same error. Did you find a solution?

**Comment by EduardJS** [comment]
Hello gents, and Yes. I have worked around the lack of support for Blob in RN by using **RNFetchBlob** ( react-native-fetch-blob ). Getting `assets-library` data via `react-native-camera-roll-picker`

```javascript
const imageRef = storage
	.ref( user.objectId )
	.child( `messages/${conversation.roomId}/${Date.now()}.jpg` )

Blob.build( RNFetchBlob.wrap( URI_FROM_PHOTO_PICKER ), { type: 'application/octet-stream' })
	.then( blob => {

		imageRef
			.put( blob, { contentType: 'application/octet-stream' })
			.then( () => {
				blob.close()
				return imageRef.getDownloadURL()
			})

	})
```

Hope it helps :)

**Comment by serhiipalash** [comment]
@EduardJS thanks for your help! Unfortunately, this does not work in my situation, because we use Expo, and we can not add `response-native-fetch-blob` to the project.

I guess the only thing we can do is use some cloud function that will get base64 string, convert it into byteArray and store in Firebase.

**Comment by EduardJS** [comment]
@serhiipalash Hello. Sorry to hear that. Firebase also supports `putString` ( base64 ) but it can't create a blob inside RN enviroment since it's actually developed for web browsers.

**Comment by jsappme** [comment]
also using expo and still no solution

this issue is blocking us to release our app to production

**Comment by serhiipalash** [comment]
@EduardJS Hi! I tried `putString` last week and it does not work.

**Comment by serhiipalash** [comment]
> this issue is blocking us to release our app to production

+1

**Comment by serhiipalash** [comment]
> also using expo and still no solution

I will write here solution with cloud function if it will work.

**Comment by EduardJS** [comment]
Yea, because firebase uses **Blob** support from the browser … hence the need for a polyfill ( which RNFetchBlob provides ). Only solution for you is to find a polyfill that works, for Blob support, in Expo ( can’t help with that though ).

As for waiting for an improvement, don’t get your hopes up :)

**Comment by serhiipalash** [comment]
> As for waiting for an improvement, don’t get your hopes up

:rofl: 

The speed of adding new features is very slow compared to the normal React world. It was a big surprise for me when I started working with RN.

**Comment by dbadeveloping** [comment]
Getting same issue on a 64-Bit Android emulator. Using 32-Bit now an everything works as expected.

**Comment by dantman** [comment]
> @EduardJS thanks for your help! Unfortunately, this does not work in my situation. We use Expo and I can not add response-native-fetch-blob to the project.

RNFB is also not really an option for many projects even when they're not using Expo.

That library has some critical issues regarding how it handles things from document providers on Android:
https://github.com/wkh237/react-native-fetch-blob/issues/525

**Comment by EduardJS** [comment]
Hei Daniel! I can only hope for official support then. I only deal with an
iOS app, so I’m covered

**Comment by kelset** [comment]
As far as I know there's an open PR to add this functionality: https://github.com/facebook/react-native/pull/11573

**Comment by wcandillon** [comment]
@serhiipalash did you end writing that cloud function?

**Comment by karimraoudy** [comment]
@serhiipalash  did you end writing that cloud function? i'm realy stuck .Thank You

**Comment by wcandillon** [comment]
@serhiipalash @karimraoudy I wrote a cloud function for this: https://medium.com/@wcandillon/uploading-images-to-firebase-with-expo-a913c9f8e98d

**Comment by karimraoudy** [comment]
@wcandillon I did saw your post but didn't understand how to implant in my code. thank you for your reply

**Comment by TizioFittizio** [comment]
I'm experiencing this too, tried base64, base64url and blob with no luck

**Comment by pablo-albaladejo** [comment]
@wcandillon Thank you very much for sharing your solutions. Worked like a charm for me!
