### ISSUE TITLE
TouchableOpacity doesn't work on IPad

### ISSUE THREAD

**Issue by flaviotobi** [facebook/react-native#16036]
Hi, for some reason TouchableOpacity doesn't work on IPad, but it works on iphone.
The version of iOS doesn't change the result.
Tested with a few version but the result is always the same, with iPhone works, with iPad doesn't.

### Is this a bug report?
Yes

### Environment
  Environment:
    OS:  macOS Sierra 10.12.6
    Xcode:  Xcode 9.0
  Packages: 
    react-native: 0.44.1 
  Target Platform: iOS (10.3, 9.3)

### Steps to Reproduce
1. Create View with TouchableOpacity
2. Open the app in Ipad Simulator
3.Verify if you can click the button and if yes if it calls onPress function

### Expected Behavior
When the TouchableOpacity is clicked, that it could call the onPress function.

### Actual Behavior
TouchableOpacity onPress function or pressed effect doesn't happen.

**Comment by hramos** [comment]
0.44.1 is an old version. Any chance you can provide a repro on the latest version?
