### ISSUE TITLE
[Docs] Suggested development environment for react-native

### ISSUE THREAD

**Issue by alvaromb** [facebook/react-native#1604]
I'm struggling to find a good development environment for React Native. Obviously [Nuclide](http://nuclide.io) is the way to go, but in the meantime, is it possible to have an small guide of the recommended tools for React Native development?

My list of needed items is:

* JSHint/JSLint with support for ES6 syntax
* Flow checker
* JSX support

Currently I'm using [Atom](http://atom.io) with a couple of plugins (``atom-ide-flow``, ``jshint``) but there are a lot of inconsistencies between those tools or they lack documentation in order to set-up a good React Native development environment. For instance, I can have Flow support but JSHint is always displaying them as errors.

![screen shot 2015-06-12 at 12 36 54](https://cloud.githubusercontent.com/assets/289640/8128478/bfd8e5bc-10ff-11e5-90ee-fac07d49158d.png)

Maybe this is a too broad question, but I think that having a small guide of this can help a lot.

**Comment by jaygarcia** [comment]
Maybe i'm too old school, but Generic sublime text, Xcode, Google Debugger seem to work. just fine.

**Comment by ide** [comment]
@alvaromb I recommend using eslint + babel-eslint + eslint-plugin-react. It handles flow syntax and matches the same linting and transformer used by the react-native packager.

**Comment by sahrens** [comment]
@ide: want to stick something in the docs?

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/docs-suggested-development-environment-for-react-native
