### ISSUE TITLE
Installation issue in: 'react-native-tab-view'

### ISSUE THREAD

**Issue by prasang7** [facebook/react-native#16058]
Main Error during installation of [react-native-tab-view](https://github.com/react-native-community/react-native-tab-view): **Couldn't find any versions for "react-native-background-geolocation-android" that matches "2.7.1"**

### Is this a bug report?

yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

yes

### Environment

OS:  macOS Sierra 10.12.5
Node:  6.11.0
Yarn:  1.0.2
npm:  5.3.0
Watchman:  4.9.0
Xcode:  Version 8.3.3 (8E3004b)

### Steps to Reproduce

I was trying to add the react-native-tab-view library in one of my existing project. So I did:

> yarn add react-native-tab-view

inside my project directory. 

### Expected Behavior

The library should get installed/Add in my project.

### Actual Behavior

It threw an unexpected error:

> yarn add react-native-tab-view
> yarn add v1.0.2
> info No lockfile found.
> [1/4] 🔍  Resolving packages...
> warning polyline@0.2.0: This module is now under the @mapbox namespace: install @mapbox/polyline instead
> warning connect@2.30.2: connect 2.x series is deprecated
> warning node-uuid@1.4.7: Use uuid module instead
> Couldn't find any versions for "react-native-background-geolocation-android" that matches "2.7.1"
> ? Please choose a version of "react-native-background-geolocation-android" from 
> this list: (Use arrow keys)
> ❯ 0.0.1-security

<img width="593" alt="screen shot 2017-09-21 at 10 03 52 pm" src="https://user-images.githubusercontent.com/13434598/30708716-77965a4c-9f1d-11e7-8a99-bf295ba5ac3c.png">

###Furthur,
If I proceed by selecting the '0.0.1-security', I get an error in the installation.

<img width="773" alt="screen shot 2017-09-21 at 10 20 02 pm" src="https://user-images.githubusercontent.com/13434598/30708784-a99041fc-9f1d-11e7-8c8f-e7a3c7a3c732.png">

To get full error log: [click here](https://github.com/react-native-community/react-native-tab-view/issues/350)

**Comment by satya164** [comment]
This is an issue in your project setup.
