### ISSUE TITLE
Can't find variable: ReactNative

### ISSUE THREAD

**Issue by GuillaumeMunsch** [facebook/react-native#16057]
### Is this a bug report?

Yes

### Environment

Environment:
  OS:  macOS Sierra 10.12.6
  Node:  8.5.0
  Yarn:  Not Found
  npm:  5.3.0
  Watchman:  4.7.0
  Xcode:  Xcode 8.3.3 Build version 8E3004b
  Android Studio:  2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: 0.48.3 => 0.48.3

  Target Platform: iOS (10.3)

### Steps to Reproduce

First of all, here is my `package.json`:

```{
  "name": "SquareboardMobile",
  "version": "1.1.0",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "lint": "./node_modules/eslint/bin/eslint.js -c .eslintrc ./src/** ; exit 0"
  },
  "dependencies": {
    "@expo/react-native-action-sheet": "^1.0.0",
    "@zapsa/react-native-draftjs-render": "^1.0.2",
    "babel-cli": "^6.26.0",
    "babel-preset-react-native-stage-0": "^1.0.1",
    "crossroads": "^0.12.2",
    "mobx": "^3.2.2",
    "mobx-react": "^4.2.2",
    "moment": "2.18.1",
    "moment-timezone": "^0.5.13",
    "react": "16.0.0-alpha.12",
    "react-native": "0.48.3",
    "react-native-calendar-events": "^1.4.1",
    "react-native-datepicker": "^1.6.0",
    "react-native-device-info": "^0.11.0",
    "react-native-exception-handler": "^2.3.0",
    "react-native-fetch-blob": "^0.10.6",
    "react-native-google-static-map": "^0.1.8",
    "react-native-image-gallery": "^2.0.0",
    "react-native-image-picker": "^0.26.3",
    "react-native-image-progress": "^1.0.1",
    "react-native-img-cache": "^1.4.0",
    "react-native-keyboard-spacer": "^0.3.1",
    "react-native-localization": "^0.1.30",
    "react-native-maps": "^0.16.4",
    "react-native-photo-view": "^1.3.0",
    "react-native-progress": "^3.2.1",
    "react-native-prompt-android": "0.3.1",
    "react-native-restart": "0.0.3",
    "react-native-router-flux": "^4.0.0-beta.21",
    "react-native-scrollable-tab-view": "^0.6.7",
    "react-native-swiper": "^1.5.4",
    "react-native-tabs": "^1.0.9",
    "react-navigation": "^1.0.0-beta.11",
    "react-redux": "^5.0.5",
    "react-swipeable-views-native": "^0.12.8",
    "redux": "^3.7.1",
    "redux-devtools-extension": "^2.13.2",
    "redux-persist": "^4.9.1",
    "redux-thunk": "^2.2.0",
    "remote-redux-devtools": "^0.5.12"
  },
  "devDependencies": {
    "babel": "^6.23.0",
    "babel-eslint": "^7.2.3",
    "babel-plugin-module-resolver": "^2.5.0",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-preset-env": "^1.6.0",
    "babel-preset-react-native": "^2.0.0",
    "eslint": "^3.19.0",
    "eslint-config-airbnb": "^15.0.1",
    "eslint-config-airbnb-base": "^11.2.0",
    "eslint-import-resolver-babel-module": "^3.0.0",
    "eslint-plugin-import": "^2.6.1",
    "eslint-plugin-jsx-a11y": "^6.0.2",
    "eslint-plugin-react": "^7.1.0"
  }
}
```

And here is my `.babelrc`: 

```{
  "presets": ["env", "react-native"],
  "plugins": [
    [
      "module-resolver", {
        "alias": {
          "actions": "./src/actions",
          "components": "./src/components",
          "config": "./src/config",
          "locales": "./src/locales",
          "modules": "./src/modules",
          "sqbStyleSheet": "./src/sqbStyleSheet",
          "utils": "./src/utils",
          "theme": "./src/theme",
        },
      },
      "transform-class-properties"
    ]
  ],
}
```

1. Install the npm packages:`npm install`
2. Simply launch the app (`react-native run-ios` or through `XCode`)

### Expected Behavior

My app to start. My previous `react-native` version was the `0.44.2`. I just upgraded to `0.48.3`. Also I re-installed my whole `node` environnement (I do actually expect the error to come from this but I'm not quite sure though). 

### Actual Behavior

The packager is starting perfectly (as shown in the first screenshot) but afterwards I do get the error `Can't find variable: ReactNative` in the red error screen (second screenshot).

<img width="715" alt="capture d ecran 2017-09-21 a 17 42 13" src="https://user-images.githubusercontent.com/8775145/30704942-6d64b68c-9ef4-11e7-899c-0156ed030d9e.png">

<img width="376" alt="capture d ecran 2017-09-21 a 17 43 59" src="https://user-images.githubusercontent.com/8775145/30704977-8306ce80-9ef4-11e7-9513-6d01236321b7.png">

### Reproducible Demo

I can't really upload something here because it isn't really related with the code itself. I re-tried with the version `0.44.2` of `react-native` and the issue still remains... I'm actually quite impressed I didn't find any issue like this one.

**Comment by janicduplessis** [comment]
Have you tried clearing the caches? `watchman watch-del-all` and start the packager with the `--clear-cache` flag. If the problem persist could you try debugging in chrome see if you can find more info about where this error is coming from?

**Comment by M-Izadmehr** [comment]
In order to answer we need more details, Please try the following and tell us the result:
 * Inside your project directory, write `react-native -version' and see if both versions of `react-native-cli` and `react-native` are specified.
 If it says not inside a react native directory, run `npm install` again.
 * Does the issue remain, when you create a new react native project?
 If yes, can you please upload the files of your new project.
 * what happens when you rebuild your apk by 'react-native run-ios':

**Comment by GuillaumeMunsch** [comment]
First of all, thanks for your answers :)

I didn't mentionned it in my previous message but I'm used to clearing `watchman` and clearing the `npm cache` and I tried it but it didn't worked out. I thought I'll let the week-end pass and try again today. Turns out an update for the iOS simulators came out and guess what. It fixes it ...

Once again thanks for your time ! 👍
