### ISSUE TITLE
[StyleSheet] Sort valid style props alphabetically 

### ISSUE THREAD

**Issue by grabbou** [facebook/react-native#1605]
Was there any specific decision behind displaying them in the current way?

<img src="https://cloud.githubusercontent.com/assets/2464966/8128724/1d1d0c6a-1102-11e5-86c2-1eebd30a17eb.png" width="200" />

Personally having all the properties sorted alphabetically would've helped a lot to find the one wanted in case of a typo.

**Comment by janmonschke** [comment]
This has been fixed in https://github.com/facebook/react-native/commit/e2fc7d23628ab8162ae02e35a434dabb13b18968, issue can be closed.
