### ISSUE TITLE
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR) on Android 8.0 (production env)

### ISSUE THREAD

**Issue by bm-software** [facebook/react-native#16050]
### Is this a bug report?

YES

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

YES

### Environment
  Environment:
    OS:  not important
    Node:  7.8.0
    Yarn:  1.0.2
    npm:  4.6.1
    Watchman: none
    Xcode: not important
    Android Studio:  not important

  Packages: (wanted => installed)
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "date-fns": "^1.28.5",
    "fetchival": "^0.3.2",
    "firebase": "^4.3.1",
    "moment": "^2.18.1",
    "native-base": "^2.3.2",
    "node-fetch": "^1.7.1",
    "prop-types": "^15.5.10",
    "react": "16.0.0-alpha.12",
    "react-moment": "^0.6.0",
    "react-native": "0.48.3",
    "react-native-loading-spinner-overlay": "^0.5.1",
    "react-native-modalbox": "^1.4.1",
    "react-native-vector-icons": "^4.3.0",
    "react-native-version-number": "^0.1.3",
    "react-navigation": "^1.0.0-beta.11",
    "react-redux": "^5.0.5",
    "redux": "^3.7.2",
    "redux-logger": "^3.0.6",
    "redux-persist": "^4.8.2",
    "redux-persist-transform-filter": "^0.0.15",
    "redux-thunk": "^2.2.0",
    "reselect": "^3.0.1",
    "rxjs": "^5.4.2"

  Target Platform: Android 8.0

### Actual Behavior

On production environment the app sometimes crash with the following error:

    backtrace:
      native: pc 0000000000182d9c  /data/app/it.bmsoftware.caliup-99che_1wi04RSxu0MEvpcw==/lib/arm/libjsc.so (WTFCrash+19)
      native: pc 000000000005370f  /data/app/it.bmsoftware.caliup-99che_1wi04RSxu0MEvpcw==/lib/arm/libjsc.so
      native: pc 0000000000053891  /data/app/it.bmsoftware.caliup-99che_1wi04RSxu0MEvpcw==/lib/arm/libjsc.so
      native: pc 00000000000a5b4f  /data/app/it.bmsoftware.caliup-99che_1wi04RSxu0MEvpcw==/lib/arm/libjsc.so
      native: pc 000000000009cdb1  /data/app/it.bmsoftware.caliup-99che_1wi04RSxu0MEvpcw==/lib/arm/libjsc.so
      native: pc 000000000000363b  <anonymous:c9800000>

**Comment by hramos** [comment]
Thanks for opening the issue! It does not appear like a community member will be able to reliably reproduce this issue. This may be for several reasons; perhaps it affects a particular app but a minimal repro has not been provided, or the issue may be sporadic. As it happens, we need a concrete set of steps that can demonstrably reproduce the issue as this will allow your fellow community members to validate a fix. We'll close the issue for now, but feel free to submit a new issue once you're able to reliably reproduce the issue locally. Thanks for your understanding!
