### ISSUE TITLE
[Crash] Can't start my app after upgrading to v0.6.0-rc

### ISSUE THREAD

**Issue by grin** [facebook/react-native#1606]
Tested in iOS simulator, here is the console output:

```
2015-06-12 13:59:56.066 [error][tid:com.facebook.React.JavaScript] "Error: undefined is not an object (evaluating 'RCTScrollViewConsts.KeyboardDismissMode.None')
 stack: 
  <unknown>       index.ios.bundle:24120
  require         index.ios.bundle:244
  <unknown>       index.ios.bundle:23173
  require         index.ios.bundle:244
  <unknown>       index.ios.bundle:1144
  require         index.ios.bundle:244
  <unknown>       index.ios.bundle:1112
  require         index.ios.bundle:244
  applyWithGuard  index.ios.bundle:880
  require         index.ios.bundle:195
  <unknown>       index.ios.bundle:47474
 URL: http://localhost:8081/index.ios.bundle
 line: 24120
 message: undefined is not an object (evaluating 'RCTScrollViewConsts.KeyboardDismissMode.None')"
2015-06-12 13:59:56.087 [error][tid:com.facebook.React.BridgeMethodQueue][RCTBridge.m:432]
 RCTDataManager.queryData was called with 4 arguments, but expects 3
```

**Comment by chirag04** [comment]
I'm getting the exact same error after update. @brentvatne: seems to be related to #1578

**Comment by sahrens** [comment]
FYI: It's helpful if you include the stack trace with sourcemaps (a screenshot of the redbox should be sufficient).

But I think this is just from a breaking API change - replace usage of `RCTScrollViewConsts.KeyboardDismissMode.None` in your code with just the string 'none'

**Comment by sahrens** [comment]
please re-open if there is something else going on.

**Comment by chirag04** [comment]
@sahrens  I'm not using keyboardDismissMode in my app at all. I'm using using ``<ScrollView>....</ScrollView>``

After some debugging, this error seems to be coming from react-native code itself. Here:
https://github.com/facebook/react-native/blob/master/Libraries/Components/ScrollView/ScrollView.js#L323

It expects ``RCTScrollView.Constants`` to export ``KeyboardDismissMode``. However only ``DecelerationRate`` is exported. Hence the error.

**Comment by sahrens** [comment]
That code is only in the "if (Platform.OS === 'android')" branch which
isn't used in OSS yet...

**Comment by chirag04** [comment]
Ok. I took the latest master. I have attached the screenshots.

Error seems to come from line 24289 in the bundle. I have attached the screenshot of those lines in the bundle. Not where how are these constants coming here.

Let me know if you need more info.

![ios simulator screen shot jun 13 2015 2 52 30 pm](https://cloud.githubusercontent.com/assets/954063/8145604/f9d4a3dc-11db-11e5-98ce-c9b50f0655c4.png)
![screen shot 2015-06-13 at 2 52 48 pm](https://cloud.githubusercontent.com/assets/954063/8145605/fc6bb996-11db-11e5-9d2f-eb301c0476f2.png)

**Comment by sahrens** [comment]
Hmm, do the source maps ever work for you? Looks like they didn't load
here. cc @frantic, @amasad

I'll dig into the actual failure...not sure how it could be so broken...

**Comment by chirag04** [comment]
As a matter of fact, the project was generated before react-native 0.4 i guess. Not sure if that has got anything to do here.

**Comment by amasad** [comment]
Do you have sourcemaps turned off in chrome?

**Comment by chirag04** [comment]
yes. I have it turned off in chrome.

**Comment by sahrens** [comment]
I just tried react-native init, then upgraded to 0.6.0-rc and npm installed again, recompiled, and everything still works with scrollview and I don't see any references to `KeyboardDismissMode` outside of that android-gated code.

You should turn them back on in chrome so we can see what your stack trace is.  Also, not sure why they aren't working in the RedBox - separate issue, but your setup definitely has some breakage.

Did you make sure to do a clean and recompile in Xcode (cmd+shift+K, cmd+R) after upgrading?  Also maybe try restarting the packager server with --reset-cache?

**Comment by Sing-Li** [comment]
Here are some observations:

1. if you use any recent versions of react-native init to scaffold, you will not have this problem
2. if you just go into the Examples/SampleApp and start hacking the code there to create your app -- you eventually will have this problem
3. you will ONLY have this problem if you used git clone'd the repo and are working off source

Clues:

1.  if you used recent versions of react-native init to scaffold - you WILL HAVE package.json in the app directory, and 'npm install' will place all the node_modules dependencies under the app directory; if you use npm start to run the packager -- the packager will only search from your app directory downwards ... it will never see the root react-native git-cloned source directory

2.  if you just hacked the Examples/SampleApp - even in today's master - there is no package.json, and no node_modules in the app directory ... instead, the XCode project is somehow rigged to ask the packager for a search from the root git-cloned react-native source directory for all .js files

Last clue:  when this happens, the packager took A LONG LONG TIME to find the source(s) and seems to have created a HUGE bundle

My 2 cents.  I'm quite sure this is happening a lot everywhere - but it is so hard to find this CLOSED thread.

**Comment by chirag04** [comment]
I think  --reset-cache did it.

**Comment by sahrens** [comment]
@amasad: Sounds like we're not properly clearing cache/restarting the server on upgrade - something you can fix?

**Comment by Sing-Li** [comment]
Is the ` --reset-cache` option undocumented on packager?  

With `--help` it shows:
````
> react-native@0.6.0 start /Users/sam/dev/react-native
> ./packager/packager.sh --help

Options:
  --port                                                                           [default: 8081]
  --root           add another root(s) to be used by the packager in this project
  --assetRoots     specify the root directories of app assets                    
  --platform       Specify the platform-specific blacklist (ios, android, web).    [default: "ios"]
  --skipflow       Disable flow checks                                           
  --nonPersistent  Disable file watcher
````
With source map enabled on chrome debugger  - exception was first caught here:

![reactnbug](https://cloud.githubusercontent.com/assets/122633/8198492/3566ae9a-1475-11e5-98e4-fa66fe064de3.png)

zooming to stack trace:

![reactnbug2](https://cloud.githubusercontent.com/assets/122633/8198514/812d93ac-1475-11e5-8b78-108a5603ba4b.png)

Then later leading to the 'red box exception:

![reactnbug3](https://cloud.githubusercontent.com/assets/122633/8198522/aa5022ea-1475-11e5-8c77-92bd127ad771.png)

**Comment by grin** [comment]
In my case this issue was caused by the `react-native-viewport` dependency in my app which itself depended  on an older version of react-native and it was all fixed after I bumped it to v0.6.0-rc (https://github.com/pjjanak/react-native-viewport/pull/5) and re-linked it to my project.

**Comment by Sing-Li** [comment]
@grin   THANKS!!    That's the vital clue.

Issue isolated!   

The packager seems to just recursively spider from the root git-cloned `react-native` directory down to scan for dependencies (avoiding only explicitly blacklisted dirs) and will load any old version of node-modules/react-native lying around.

So if you go to your root git-cloned `react-native` directory and then do a:

`find . -name 'react-native' -print`

... you will see any old react-native npm-installs lying around that the packager might decide to load, and cause the problem.

From my previous post on the 'observations' , you will see a mix of:

*   pre- '0.4.x' generated scaffolds that does not use package.json
*   post - '0.4.x' generated scaffolds that use package.json

The problem is that for post-'0.4.x' generated projects, UNDER THE react-native/Examples directory (which the Facebook testers will almost never have with fresh git-clones, but most devs tinkering with react-native are likely to hastily create), there might be node-modules/react-native lying around that are not 0.6.0-rc!   The packager gladly load these into the ios.js.bundle - causing the problem.

The bypass for now is to find any old node-modules/react-native lying around manually.  Or blacklist the Examples directory.

**Comment by jawadrehman** [comment]
after successfully updating my packages, i was able to start the app... but I get this warning in 
XCode


>instance method 'eventDispatcher' in category from >/Users/jawad/Library/Developer/Xcode/DerivedData/VoxIosApp->azaijsjijhyvgacmwwmnuorswkql/Build/Products/Debug->iphonesimulator/libReact.a(RCTEventDispatcher.o) overrides method from class in >/Users/jawad/Library/Developer/Xcode/DerivedData/VoxIosApp->azaijsjijhyvgacmwwmnuorswkql/Build/Products/Debug-iphonesimulator/libReact.a(RCTBridge.o)

**Comment by brentvatne** [comment]
@jawadrehman - that shouldn't cause any problems, related to #1562 - PR welcome :smile:

**Comment by jawadrehman** [comment]
@brentvatne even the first message on xCode isn't going to cause problems ?

**Comment by brentvatne** [comment]
@jawadrehman - actually I'm not familiar with the first one cc @tadeuzagallo

**Comment by tadeuzagallo** [comment]
The warning is safe, but it has already been fixed.

**Comment by owais** [comment]
If one of your dependencies specifies `react-native` as a dependency itself, then react-native is also installed inside the node_modules directory of that dependency. This leaves older versions of react-native inside your source tree. For me the solution was to manually edit the culprits package.json file and remove react-native from dependencies list and also remove react-native from their node_modules.

**Comment by wootwoot1234** [comment]
@owais I figured that out as well just now.  Worked great.  Here is what I did (same thing as @owais just in different words incase someone is confused.):

It had to do with a component I was using, in my case ```react-native-device```.  What I had to do to fix it was delete the ```/node_modules``` folder located in the component. ```AppName/node_modules/React-Native-Component/node_modules```.

I also updated the dependencies in the ```package.json``` file also located in the component folder ```AppName/node_modules/React-Native-Component/package.json``` and change the react-native dependency to (or something similar):

      "peerDependencies": {
        "react-native": ">= 0.4.0 < 1"
      },

Why do components need to specify react native as dependency.  Seems like it's implied, right?  Can I just remove the dependency?

**Comment by owais** [comment]
Yes, components should not specify react-native as a dependency. It causes many problems. Not to mention that it significantly increases installation time and each module that does this ends up imprting its own version of react-native instead of the one the developer is working on.

**Comment by Sing-Li** [comment]
A third party component may have dependencies on older react-native APIs that are either changed or no longer supported in later versions.  But it may still work and be useful when creating apps using the latest version of react-native. 

The thing that is broken here is the packager.  

And the problem with multiple/old-version loading is NOT isolated to react-native alone (see all the other related issues).

**Comment by chauthai** [comment]
I've just ran into the same problem upgrading from 0.5 to 0.6.
Moving react-native dependencies to peerDependencies in third party components 
AND resetting the cache of the packager resolved the starting errors of my app:

```./node_modules/react-native/packager/packager.sh --reset-cache``` 

Third-party components in use:
- react-native-facebook-login
- tcomb-form-native
- react-native-geocoder
- react-native-router

**Comment by fatuhoku** [comment]
:+1:  I ran into this issue after having creating a new project with  `react-native init`. Not encouraging!  What's the current workaround?

**Comment by amasad** [comment]
It sounds like the packager should fail loudly when it sees multiple versions of react-native installed. And we should establish a community standard around only using `peerDependencies` when depending on react-native. Thoughts?

**Comment by chauthai** [comment]
@amasad I think a short guide how to write 3rd party components would be nice. Included should be a guideline how to setup a node project etc...

**Comment by owais** [comment]
@amasad Sounds like a plan.

**Comment by ilansas** [comment]
@chauthai I agree this would be nice

**Comment by Sing-Li** [comment]
a) packager loudly fails (but please do not exit console)  :+1:    because it will stop devs  from looking everywhere else for the cause of this  *red screen of death*

b) `peerDependencies` as a fix rather than a temporary bypass :-1:   I, too, would really like to move on and forget this ever happened but the divergence from npm behavior might prevent a healthy growth of the React Native components ecosystem for the longer term (broken unmaintained components all over github, for example)  - jmho

**Comment by ilansas** [comment]
Well I tried to clear react-native folders in node_modules, change the dependencies by peerDependencies and clear the cache but it's throwing me an error : 

    Recrawled this watch 2 times, most recently because:
    /Users/isasportas/Projects/canalplus/iOS/RemoteX1: kFSEventStreamEventFlagUserDropped
    To resolve, please review the information on
    https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
    Recrawled this watch 2 times, most recently because:
    /Users/isasportas/Projects/canalplus/iOS/RemoteX1: kFSEventStreamEventFlagUserDropped
    To resolve, please review the information on
    https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
    [16:24:44] <START> fs crawl
    TypeError: Cannot read property 'root' of null
        at /Users/isasportas/Projects/canalplus/iOS/RemoteX1/node_modules/react-native/packager/react-packager/src/DependencyResolver/crawlers/index.js:16:84
        at tryCallOne (/Users/isasportas/Projects/canalplus/iOS/RemoteX1/node_modules/react-native/node_modules/promise/lib/core.js:37:12)
        at /Users/isasportas/Projects/canalplus/iOS/RemoteX1/node_modules/react-native/node_modules/promise/lib/core.js:103:15
        at flush (/Users/isasportas/Projects/canalplus/iOS/RemoteX1/node_modules/react-native/node_modules/promise/node_modules/asap/raw.js:50:29)
        at process._tickCallback (node.js:355:11)
    TypeError: Cannot read property 'root' of null
        at /Users/isasportas/Projects/canalplus/iOS/RemoteX1/node_modules/react-native/packager/react-packager/src/DependencyResolver/crawlers/index.js:16:84
        at tryCallOne (/Users/isasportas/Projects/canalplus/iOS/RemoteX1/node_modules/react-native/node_modules/promise/lib/core.js:37:12)
        at /Users/isasportas/Projects/canalplus/iOS/RemoteX1/node_modules/react-native/node_modules/promise/lib/core.js:103:15
        at flush (/Users/isasportas/Projects/canalplus/iOS/RemoteX1/node_modules/react-native/node_modules/promise/node_modules/asap/raw.js:50:29)
        at process._tickCallback (node.js:355:11)

**Comment by ilansas** [comment]
After doing the three steps advised above, I'm getting this error. Is it related  to this problem or something totally different ? Checking https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl did not really help me to understand...

    Recrawled this watch 2 times, most recently because:
    /Users/isasportas/Projects/canalplus/iOS/RemoteX1: kFSEventStreamEventFlagUserDropped
    To resolve, please review the information on
    https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
    Recrawled this watch 2 times, most recently because:
    /Users/isasportas/Projects/canalplus/iOS/RemoteX1: kFSEventStreamEventFlagUserDropped
    To resolve, please review the information on
    https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
    [16:24:44] <START> fs crawl
    TypeError: Cannot read property 'root' of null
        at /Users/isasportas/Projects/canalplus/iOS/RemoteX1/node_modules/react-native/packager/react-packager/src/DependencyResolver/crawlers/index.js:16:84
        at tryCallOne (/Users/isasportas/Projects/canalplus/iOS/RemoteX1/node_modules/react-native/node_modules/promise/lib/core.js:37:12)
        at /Users/isasportas/Projects/canalplus/iOS/RemoteX1/node_modules/react-native/node_modules/promise/lib/core.js:103:15
        at flush (/Users/isasportas/Projects/canalplus/iOS/RemoteX1/node_modules/react-native/node_modules/promise/node_modules/asap/raw.js:50:29)
        at process._tickCallback (node.js:355:11)
    TypeError: Cannot read property 'root' of null
        at /Users/isasportas/Projects/canalplus/iOS/RemoteX1/node_modules/react-native/packager/react-packager/src/DependencyResolver/crawlers/index.js:16:84
        at tryCallOne (/Users/isasportas/Projects/canalplus/iOS/RemoteX1/node_modules/react-native/node_modules/promise/lib/core.js:37:12)
        at /Users/isasportas/Projects/canalplus/iOS/RemoteX1/node_modules/react-native/node_modules/promise/lib/core.js:103:15
        at flush (/Users/isasportas/Projects/canalplus/iOS/RemoteX1/node_modules/react-native/node_modules/promise/node_modules/asap/raw.js:50:29)
        at process._tickCallback (node.js:355:11)

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/crash-cant-start-my-app-after-upgrading-to-v060-rc
