### ISSUE TITLE
Double Dev Menu and Un-deallocated React Objects

### ISSUE THREAD

**Issue by achuvm** [facebook/react-native#16068]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS:  macOS Sierra 10.12.6
  Node:  7.9.0
  Yarn:  Not Found
  npm:  5.4.2
  Watchman:  4.7.0
  Xcode:  Xcode 9.0 Build version 9A235
  Android Studio:  2.3 AI-162.3871768

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: 0.49.0-rc.5 => 0.49.0-rc.5

### Steps to Reproduce

1. create a new react project (I tested with the latest RC, but it happens with the 48.3 too)
2. modify the `App.js` file to have a red screen error (ie. rename `View` to `Viewa`
3. build the app from the xcode project
4. launch the app and get red screen
5. shake phone & hit reload without fixing error and get red screen
6. repeat step 5 and notice that multiple dev menus appear

### Expected Behavior

There should only be 1 dev menu that appears

### Actual Behavior

Multiple dev menu appears, also if you inspect the memory, you'll notice that more than 1 copy of the React objects are also being kept around.

<img width="1402" alt="screen shot 2017-09-22 at 12 14 02 pm" src="https://user-images.githubusercontent.com/21074927/30761501-51ae91de-9f93-11e7-971b-3f0370f20964.png">

### Reproducible Demo

Read reproduction steps, it's just a new project with an erroneous view.

**Comment by ryankask** [comment]
Did you ever identify what's causing the double dev menu? I'm seeing this as well.

**Comment by achuvm** [comment]
Hi @ryankask,

From what I can determine it's something in React Native where, when an error screen appears, there's a memory leak that keeps the old managers around when the app is reloaded. I don't think there's anything us developers on top of React Native can do though. The good thing is that it only happens in debug (when you can reload and have red screens).

**Comment by ryankask** [comment]
Thanks for the update. There's [a line here](https://github.com/facebook/react-native/blob/7f6a7aec46773fff351de1aea85cdb16d469a829/React/DevSupport/RCTPackagerConnection.m#L100) that discusses multiple dev menus so maybe I'll have a look at that when I get a spare moment.

Here's what is looks like for me: 

![double-dev](https://user-images.githubusercontent.com/81891/31460253-a957c4c6-aebd-11e7-8129-9cdca2ba817c.gif)

**Comment by mkozhukharenko** [comment]
same issue

**Comment by ryankask** [comment]
I've also noticed when this happens that the Chrome dev console because unresponsive and the console output lags.

**Comment by spencewine** [comment]
I'm having this exact same issue that is being demonstrated by @ryankask. I had this issue in react-native@0.48.4, then upgraded to react-native@0.49.5 and it is still there.

**Comment by sdyxch** [comment]
same issue

**Comment by achuvm** [comment]
This is still an issue, thanks!

**Comment by kylevdr** [comment]
Still an issue. Occurs when testing on physical device (0.54.0).

**Comment by kfoxb** [comment]
Still an issue on 0.54.0.

**Comment by gre** [comment]
experimenting it as well

**Comment by JeremyBradshaw7** [comment]
I've got this issue too, when deploying to attached device from vscode.

**Comment by praveenkumarc86** [comment]
Still an issue in 0.54.4
