### ISSUE TITLE
Question about React Native license

### ISSUE THREAD

**Issue by richardgirges** [facebook/react-native#16069]
This is a simple question, just looking for clarification.

I know about facebook/react#10191 - but comments are locked for non-collaborators on that issue. I heard the good news today about React being relicensed under MIT. 

Does React Native fall under that umbrella? Or will React Native stay on the same BSD + Patent license? Not looking for a debate, just an answer. :)

Thanks and keep up the great work RN team!

**Comment by ide** [comment]
I don't speak for Facebook so someone who works there should close this but one of the engineering directors clarified that for now RN will keep its current license: https://twitter.com/dmwlff/status/911348886882607104.

**Comment by lsycxyj** [comment]
I hope RN could be relicensed.

**Comment by richardgirges** [comment]
Thanks @ide

**Comment by SleetShang** [comment]
RN is so great! I also hope RN could be relicensed.

**Comment by wz2cool** [comment]
Hope RN could be relicensed.

**Comment by yahue** [comment]
no zuo no die why you try

**Comment by abeemukthees** [comment]
I'm waiting for the license to change...

**Comment by yahue** [comment]
@shengxinjing This is the act of the software license agreement, is the shame of things. I have abandoned react-native, too insecure！

**Comment by janicduplessis** [comment]
Locking this since license discussions get too heated :)

**Comment by gaearon** [comment]
React Native (including Metro, Fresco, and Yoga) has just been relicensed as MIT.

https://github.com/facebook/react-native/commit/26684cf3adf4094eb6c405d345a75bf8c7c0bf88
