### ISSUE TITLE
tried to scrollTo: on non-RCTScrollableProtocol view (null) with tag #658

### ISSUE THREAD

**Issue by mrkentlng** [facebook/react-native#16073]
I got issue like picture below here
<img width="373" alt="screen shot 2017-09-23 at 6 17 13 pm" src="https://user-images.githubusercontent.com/12961488/30772830-f66f3ca0-a08d-11e7-84a1-32c28253146c.png">

  Environment:
    OS:  macOS Sierra 10.12.6
    Simulator: iOS 11
    Node:  8.4.0
    Yarn:  0.27.5
    npm:  5.4.0
    Watchman:  4.7.0
    Xcode:  Xcode 9 (9A235)

    "react": "16.0.0-alpha.12",
    "react-native": "0.46.4",

**Comment by eballeste** [comment]
http://facebook.github.io/react-native/docs/contributing.html#reporting-new-issues
