### ISSUE TITLE
Network Request Failed

### ISSUE THREAD

**Issue by AAGSICON** [facebook/react-native#16081]
![screenshot_2017-09-22-13-18-50-54](https://user-images.githubusercontent.com/31310379/30794091-c479bf44-a1b5-11e7-853c-2c42a093c366.png)

var SERVER_SIGNUP_URL = 'https://192.168.0.80/Registration/Registration.php';
fetch(SERVER_SIGNUP_URL + '?username=' + this.state.username + '&password=' + this.state.password)
                  .then((response) => response.json())
                  .then((responseData) => {
                    var id = responseData.id;
                    if (id === -1) {
                      this.hideProgressBar();
                      showMessage("Something is bad", "This username is already taken");
                    }
                    else {
                      this.props.navigator.push({
                        name: 'contacts',
                        password: this.state.password,
                        id: id,
                        username: this.state.username
                      });
                    }
                  })
            .done();

**Comment by 1048034876** [comment]
I have this problem too on android

**Comment by jakelacey2012** [comment]
Have you guys looked at this? https://stackoverflow.com/questions/38418998/react-native-fetch-network-request-failed

**Comment by udtrokia** [comment]
if someone try to use emulator to  fetch "http://localhost/" or http://"127.0.0.1"/, you can change them to '10.0.2.2'

**Comment by fsunset** [comment]
@AAGSICON @1048034876 - hey guys, have you reach a fix for it please? I'm stuck. Thanks a lot!

**Comment by ducanhmai205** [comment]
im stuck this too.

**Comment by 1048034876** [comment]
you can try your ip instead of localhost

**Comment by JosePaulo95** [comment]
Dont get your ip from a website like findmyip.com go to the cmd and ipconfig

**Comment by branb** [comment]
I had the same error using http://localhost:8000 as my development server.

I think on react native 0.52.x it worked fine, but after upgrading to 0.54.x it caused the network request failed error.

As mentioned by @udtrokia and @1048034876, replacing localhost with my actual IP (not 127.0.0.1) didn't cause the error anymore.

**Comment by egeniegithub** [comment]
how to change the default IP address as development server?

**Comment by webeasystep** [comment]
this  fix the problem
https://www.youtube.com/watch?v=shstJgkLW-I
