### ISSUE TITLE
Is react-native will under mit license this week

### ISSUE THREAD

**Issue by qifenshu** [facebook/react-native#16080]
I heard that react is relicensing under mit.
But the reason we choose react is react-native.
So, Is react-native will under mit license this week.

**Comment by richardgirges** [comment]
I had the same question. See #16069. While there is no official answer (to my knowledge), it doesn't seem that React Native will be part of the React/Jest/Flow relicensing.

**Comment by qifenshu** [comment]
@richardgirges  thanks for ur share.

**Comment by janicduplessis** [comment]
See https://github.com/facebook/react-native/issues/16069#issuecomment-331602504

**Comment by gaearon** [comment]
React Native (including Metro, Fresco, and Yoga) has just been relicensed as MIT.

https://github.com/facebook/react-native/commit/26684cf3adf4094eb6c405d345a75bf8c7c0bf88
