### ISSUE TITLE
Image not working for uri: 'https://robohash.org/awesome'

### ISSUE THREAD

**Issue by hars-shhh** [facebook/react-native#16083]
Image is not working with this kind of URI: 'https://robohash.org/awesome' and it works with URI that ends with extension(.png) URI: 'https://facebook.github.io/react/img/logo_og.png'

**Comment by ubatin** [comment]
It worked for me. You should try again.
```javascript
...

<Image
   style={{ width: 50, height: 50 }}
   source={{ uri: 'https://robohash.org/awesome' }}
/>

...
```

**Comment by ubatin** [comment]
@facebook-github-bot  close
