### ISSUE TITLE
JSON Parse error: Unexpected EOF

### ISSUE THREAD

**Issue by AAGSICON** [facebook/react-native#16082]
![screenshot_2017-09-25-11-30-44-21](https://user-images.githubusercontent.com/31310379/30794384-4c4c4454-a1b7-11e7-80bd-e6cd0042f4dc.png)

var SERVER_SIGNUP_URL = 'http://192.168.0.80/Registration/Registration.php';

                  fetch(SERVER_SIGNUP_URL + '?username=' + this.state.username + '&password=' + this.state.password)
                  .then((response) => response.json())
                  .then((responseData) => {
                    var id = responseData.id;
                    if (id === -1) {
                      this.hideProgressBar();
                      showMessage("Something is bad", "This username is already taken");
                    }
                    else {
                      this.props.navigator.push({
                        name: 'contacts',
                        password: this.state.password,
                        id: id,
                        username: this.state.username
                      });
                    }
                  })
            .done();

**Comment by vonovak** [comment]
there si very likely a bug in your code

**Comment by Martian2Lee** [comment]
Try change `http://` to `https://`
