### ISSUE TITLE
adjustsFontSizeToFit not working

### ISSUE THREAD

**Issue by jsaguiar** [facebook/react-native#16087]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment
  Environment:
    OS:  macOS Sierra 10.12.6
    Node:  7.10.1
    Yarn:  0.27.5
    npm:  4.2.0',
    Watchman:  4.7.0
    Xcode:   9.0 (9A235)

  Packages: (wanted => installed)
    react-native: 0.46.3
    react: 16.0.0-alpha.12

### Steps to Reproduce

```
import React, { Component } from 'react';
import { AppRegistry, Text } from 'react-native';

export default class BoldAndBeautiful extends Component {
  render() {
    return (
      <Text 
        style={{width:200}}
        numberOfLines={1}
        adjustsFontSizeToFit={true}
        minimumFontScale={0.1}
>
        I want this text to be smaller
      </Text>
    );
  }
}
AppRegistry.registerComponent('AwesomeProject', () => BoldAndBeautiful);
```

### Expected Behavior

Text should be getting smaller.

### Actual Behavior

Text is not getting smaller

### Reproducible Demo

Use code above

**Comment by zachasme** [comment]
You need to apply to the Text element a fontSize, for example, this will fit each text to its width:
```
export default class App extends Component {
  render() {
    return (
      <View style={{flex: 1}}>
        <Text 
          style={{flex:1,width:200,fontSize:200}}
          adjustsFontSizeToFit={true}
          numberOfLines={1}
          minimumFontScale={0.01}
  >
          I want this text to be smaller
        </Text>
        <Text 
          style={{flex:1,width:400,fontSize:200}}
          adjustsFontSizeToFit={true}
          numberOfLines={1}
          minimumFontScale={0.01}
  >
          I want this text to be smaller
        </Text>
      </View>
    );
  }
}
```
