### ISSUE TITLE
overflow is not working with borderRadius in android.

### ISSUE THREAD

**Issue by neilzhengzx** [facebook/react-native#16093]
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

yes

### Environment

Environment:
OS: macOS Sierra 10.12.6
Node: 7.10.1
Yarn: 0.27.5
npm: 4.2.0',
Watchman: 4.7.0
Xcode: 9.0 (9A235)

Packages: (wanted => installed)
react-native: 0.47.1
react: 16.0.0-alpha.12

### Steps to Reproduce

```javascript
import React, { Component } from 'react';
import { AppRegistry, View } from 'react-native';

export default class BoldAndBeautiful extends Component {
  render() {
    return (
      <View
           style={{width:200, height:200, selfAlign:'center', borderRadius:100, overflow:'hidden'}}
      >
          <View
               style={{width:200, height:200, backgroundColor:'red'}}
          />
      </View>
    );
  }
}
AppRegistry.registerComponent('AwesomeProject', () => BoldAndBeautiful);
```

### Expected Behavior

the red View should be circular  in android.

### Actual Behavior

the red View be square in android. overflow is not working.

### Reproducible Demo

Use code above

**Comment by VasudevAkhil** [comment]
Hi @neilzhengzx 

I am also facing same issue

**Comment by janicduplessis** [comment]
This is a known issue, android doesn't support overflow and won't for the time being. As a workaround you have to apply the border radius to the subview also.
