### ISSUE TITLE
Error : 'ScrollView' has no propType for native prop 'RCTScrollView.onScrollAnimationEnd' of native type ' BOOL'

### ISSUE THREAD

**Issue by jpca999** [facebook/react-native#16090]
I'm stuck on this error. 

![image](https://user-images.githubusercontent.com/1026325/30834598-d7021e24-a221-11e7-954a-8ec0bdfc7c7c.png)

{
  "name": "app-20",
  "version": "0.0.0",
  "description": "Hello Expo!",
  "author": null,
  "private": true,
  "main": "node_modules/expo/AppEntry.js",
  "dependencies": {
    "axios": "^0.16.2",
    "expo": "^20.0.0",
    "latlng-to-zip": "^0.0.1",
    "lodash": "^4.17.4",
    "react": "16.0.0-alpha.12",
    "react-addons-update": "^15.6.0",
    "react-native": "^0.47.2",
    "react-native-calendar": "^0.12.3",
    "react-native-calendars": "^1.5.8",
    "react-native-communications": "^2.2.1",
    "react-native-easy-toast": "^1.0.6",
    "react-native-elements": "^0.16.0",
    "react-native-flexbox-grid": "^0.3.1",
    "react-native-google-place-autocomplete": "^0.3.0",
    "react-native-indicator": "^0.6.7",
    "react-native-loading-spinner-overlay": "^0.5.2",
    "react-native-maps": "^0.16.2",
    "react-native-modal": "^3.1.0",
    "react-native-modal-datetime-picker": "^4.11.0",
    "react-native-multiple-select-list": "^1.0.4",
    "react-native-progressive-input": "^1.0.3",
    "react-native-segmented-control-tab": "^3.2.1",
    "react-native-signature-pad": "^0.0.8",
    "react-navigation": "^1.0.0-beta.11",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-form": "^5.0.1",
    "redux-persist": "^4.9.1",
    "redux-thunk": "^2.2.0"
  }
}

{
    "expo": {
    "name": "thapp",
    "description": "thapp",
    "slug": "thapp",
    "privacy": "unlisted",
    "sdkVersion": "20.0.0",
    "version": "1.0.5",
    "orientation": "portrait",
    "primaryColor": "#cccccc",
    "icon": "./assets/icons/app.png",
    "loading": {
      "icon": "./assets/icons/loading.png",
      "hideExponentText": false
    },
    "packagerOpts": {
      "assetExts": ["ttf", "mp4"]
    },
    "ios": {
          "bundleIdentifier": "com.thapp.exp",
          "supportsTablet": true
    },
    "android": {
       "package": "org.thapp.exp",
     }
  }
}

I also tried replacing react-native package with   "react-native": "^0.47.2",  But didnt work.

### Is this a bug report?

(write your answer here)

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.)

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by courage-liberty** [comment]
and so do I.
FlatList becomes the error.

`Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.`

```
import React from 'react'
import { FlatList, StyleSheet, Text, View } from 'react-native'

export default class App extends React.Component {
  render () {
    return (
      <View style={styles.container}>
        <FlatList
          data={[{key: 'a'}, {key: 'b'}]}
          renderItem={({item}) => <Text>{item.key}</Text>}
        />
      </View>
    )
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center'
  }
})
```

**Comment by philipjc-apacio** [comment]
Feels like this has just decided to break on me this morning, right before a deadline. Any help, please??

**Comment by chrise86** [comment]
This occurs for me when using the CLI to build and run the app, however it does not happen when running via Xcode.

**Comment by philipjc-apacio** [comment]
This is happening while using Expo and create-react-native-app

**Comment by courage-liberty** [comment]
My issue is like the EXPO client, too.

**Comment by nokwin** [comment]
Found the possible solution!

1. Bump `expo` version in `package.json` to `21.0.2`
1. Remove `node_modules`
1. Change sdk version in `app.json` to `21.0.0`
...
ScrollView is working AGAIN! :)

**Comment by giulianok** [comment]
Same here. I created a new fresh app using `create-react-native-app`. The following dependencies have been installed

```
"dependencies": {
  "expo": "^20.0.0",
  "react": "16.0.0-alpha.12",
  "react-native": "^0.47.0"
}
```

I started getting that error, infinitely, causing the browser consume a lot of memory.

I've tried updating to `0.48.4` with this command `react-native-git-upgrade 0.48.4`, it installs the react native v0.48 but it doesn't update `package.json`.

Finally, I end up with the same solution as @nokwin:

```
"dependencies": {
  "expo": "21.0.2",
  "react": "16.0.0-alpha.12",
  "react-native": "0.48.4"
}
```

And make sure you have the following sdkVersion in `app.json`

```
"expo": {
  "sdkVersion": "21.0.0"
}
```

**Comment by PabloTeari** [comment]
I had the same problem, solved! Thank You @nokwin @giulianok.

**Comment by andrespch** [comment]
thaaanks @nokwin

**Comment by marcfielding1** [comment]
Hmm thats not solving it for me, anybody else stuck?

**Comment by andrespch** [comment]
did you update to xcode 9? I think I needed to `yarn cache clean` after changing (and installing) the dependencies  to get it to work

**Comment by marcfielding1** [comment]
Hmm I'm using NPM actually, let me try cleaning that cache out.

**Comment by andrespch** [comment]
hm I actually asked you because I only got this issue after updating to xcode 9, so if you had not updated yet, that might be a sign that your issue is a different one, and that's why this solution is not working.

**Comment by marcfielding1** [comment]
Ok so for me, it's actually an issue with the [Google Places Autocomplete package](https://github.com/FaridSafi/react-native-google-places-autocomplete). If I remove that now it's, tis still very odd it just suddenly started of out nowhere.

**Comment by courage-liberty** [comment]
I tried it, but project opening of expo client has become the time-out.
Because I have not yet updated iOS, it may be caused by it.

**Comment by rubencodes** [comment]
OH MY GOD this worked! Thanks y'all, this issue popped out of nowhere for me as well and right on a demo day 😵 Better late than never!

**Comment by igorbrandao** [comment]
I confirm that @nokwin / @giulianok solution works
Thank you so much for figuring this out! Started to flip when I updated expo and got this error earlier today...

**Comment by courage-liberty** [comment]
Person of expo saying "repairs it early" in Slack.
I wait for a while.

**Comment by thelostspore** [comment]
Does anyone know why this happened and can anyone agree on a remedy? I've tried all solutions proposed up to this point and still see the error.

**Comment by andrespch** [comment]
what's exactly the error you are getting?

**Comment by thelostspore** [comment]
@andrespch A very similar error to the one posted (native code & js code out of sync). I've seen similar [issues](https://github.com/facebook/react-native/issues/6006) and [SO](https://stackoverflow.com/questions/38520003/react-native-no-proptype-for-native-prop-rctview-maxheight)'s and I'm mostly curious about the root cause...seems like this has occurred for other major upgrades of react-native. I've managed to get my app running but I couldn't pinpoint the exact remedy.

Does anyone know if react-native `0.48.4` now only works with expo sdk `21.0.2`? If so the CRNA [Versions](https://github.com/react-community/create-react-native-app/blob/master/VERSIONS.md) readme could probably use a note.

![image](https://user-images.githubusercontent.com/3950085/30974163-cf75dfb6-a423-11e7-820c-04c4bb44e644.png)

**Comment by Martian2Lee** [comment]
@nokwin Thanks bro!

**Comment by rom1k** [comment]
I have this same error and I don't use expo. Anyone found a solution?

**Comment by sujitpk-perennial** [comment]
Most of faced issue with expo. I am not using expo. It was working for me. Suddenly it starts showing this danger red screen. I am using

Xcode: 8.0
iOS: 10
npm: 5.5.1
