### ISSUE TITLE
When i give npm-check command, it tells that package.json is missing in react-native node module.

### ISSUE THREAD

**Issue by bimix** [facebook/react-native#16098]
### Is this a bug report? No

(write your answer here)

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by jakelacey2012** [comment]
Could you provide steps to reproduce please.

Does this error happen every time to create a new react-native application and run `npm-check`?
