### ISSUE TITLE
custom shell build error: ..node_modules/react-native/packager/react-native-xcode.sh: Permission denied

### ISSUE THREAD

**Issue by cuiyueshuai** [facebook/react-native#16095]
Environment
react-native -v:react-native: 0.36.0
node -v:v8.3.0
npm -v:5.3.0
Target Platform:iOS
Development Operating System:MacOs
Build tools: jenkins and shell

I write shell script for my project in the jenkins, and run the shell script. when it execute command "xcodebuild -configuration ..." to compile the project, I get error:

<img width="654" alt="wx20170926-151723 2x" src="https://user-images.githubusercontent.com/13741688/30847354-d5bb381e-a2cd-11e7-931e-200652291d52.png">

I watch the upgrade of react-native v0.46 [https://github.com/facebook/react-native/releases/tag/v0.46.4](https://github.com/facebook/react-native/releases/tag/v0.46.4),

But I don't think my problem is that, so I can how to resolve it;

thank you, my English so poor, please forget it, you can understand my mean?

**Comment by janicduplessis** [comment]
This file was moved to node_modules/react-native/scripts/react-native-xcode.sh, you can change this manually in xcode in your project settings, build phase and there should be a script phase there that runs this command.
