### ISSUE TITLE
Modal component sets the StatusBar to White

### ISSUE THREAD

**Issue by EnriqueDev** [facebook/react-native#16103]
### Is this a bug report?
Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?
yes

### Environment

  Environment:
    OS:  macOS Sierra 10.12.6
    Node:  6.11.3
    npm:  3.10.10
    Watchman:  4.7.0
    Using expo

  Packages: (wanted => installed)
    react-native: 0.48.1 => 0.48.1
    react: 16.0.0-alpha.12 => 16.0.0-alpha.12

  Target Platform: iOS (10.3)

### Steps to Reproduce
Open a modal in Android.

### Expected Behavior

Should just activate a modal an present the view.

### Actual Behavior

Statusbar turned white.

![i3 pimgpsh_fullsize_distr](https://user-images.githubusercontent.com/25365731/30864343-361c9822-a2cb-11e7-801f-27457f874171.jpg)

**This happens in the following phones:**

- Samsung Galaxy A5 2017 - 6.0.1
- Huawey Ascent P8 - Android 6.0
- Sony Xperia Z1 - Android 5.1.1

**But when trying on:**

- BQ Aquaris 5H - Android 4.4.2
- Google Nexus 5X- Android 7.1.2

it works properly.

Seems like is SO version related.

### Reproducible Demo
https://snack.expo.io/HkIaCRviZ

**Comment by mikedream89** [comment]
this bug had be fixed??? @EnriqueDev

**Comment by sound2gd** [comment]
this bug had be fixed??? @EnriqueDev 
have the same issue here
