### ISSUE TITLE
[Text] fontStyle cancels fontWeight

### ISSUE THREAD

**Issue by jose920405** [facebook/react-native#16116]
**This way the Bold works**

`fontWeight: 'bold',`

**This way the Bold does not work but the italic works** 
```
fontStyle: 'italic',
fontWeight: 'bold',
```

**Comment by vonovak** [comment]
make sure the font supports both bold and italic

**Comment by jose920405** [comment]
I'm not adding a fontFamily, I'm leaving the default one.

**Comment by badarshahzad** [comment]
I also noticed this bug I have applied the Century Gothic text style but when I applied fontWeight='bold' the test style changed and text become bold.
