### ISSUE TITLE
Webview contentInset property doesn't work in Android. But, work well in iOS 

### ISSUE THREAD

**Issue by rogerluo410** [facebook/react-native#16111]
### Is this a bug report?

(write your answer here)  yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.) Yes

### Environment

    OS:  macOS Sierra 10.12.6
    Node:  8.4.0
    Yarn:  0.27.5
    npm:  5.4.0
    Watchman:  4.7.0
    Xcode:  Xcode 8.3.3 Build version 8E3004b
    Android Studio:  2.3 AI-162.4069837

    react-native: 0.44.2
    react: 16.0.0-alpha.12 

### Steps to Reproduce

(Write your steps here:)

`contentInset={{top: -8, left: -8}}`  contentInset property doesn't work in Android, but, this is not marked as an iOS property in Docs. 

### Expected Behavior

(Write what you thought would happen.)

How to fix it ?  move or remove the content offset?  No space between webview and content.

which RN version could solve the problem and use the `contentInset`  property?? 

Thank you.

### Actual Behavior

(Write what happened. Add screenshots!)

![image](https://user-images.githubusercontent.com/5260711/30905189-a48be6ba-a3a6-11e7-8c14-6e0c8bdc5876.png)

I am hoping in Android: 

![image](https://user-images.githubusercontent.com/5260711/30905347-199c4742-a3a7-11e7-9a68-1651bcfdbfff.png)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by janicduplessis** [comment]
Android doesn't have the concept of insets so I think this is more of a documentation issue, the prop should be marked as iOS only. Is it possible to achieve the effect you are looking for on Android using padding instead?
