### ISSUE TITLE
How to render <Image> within <Text> in react-native (Android app)

### ISSUE THREAD

**Issue by Wars13** [facebook/react-native#16113]
### Is this a bug report?

(write your answer here)

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.)

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by orta** [comment]
@facebook-github-bot no-template
