### ISSUE TITLE
null is not an object (evaluating '_this.props.cards[currentIndex[_this.guid]]') 

### ISSUE THREAD

**Issue by bimix** [facebook/react-native#16118]
### Is this a bug report?

No

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

It should run and be able to swipe the content (text boxes). 

### Actual Behavior

-![image](https://user-images.githubusercontent.com/15432652/30933585-425c77f0-a3cb-11e7-9dbc-ae66f216378e.png)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by 8of** [comment]
What's `this.props.cards` structure?
What's structure for `currentIndex` object?
What's `guid`'s type?
