### ISSUE TITLE
[ScrollView] scroll to Top leaves unnecessary white space

### ISSUE THREAD

**Issue by ahishek** [facebook/react-native#16114]
I'm trying to scroll to the top of my scrollView on the click of an item at it's bottom. But what's happening is that, on doing this, it leaves random white space at the top of my scrollview. Basically, pushes my other content down. 

`<ScrollView
          ref={(c) => {
            this.content = c;
          }}
          alwaysBounceVertical={false}
          bounces={false}
          automaticallyAdjustContentInsets={false}
          onScroll={this.handleScroll}
        >
   {....content}
  </ScrollView>

 // On bottom component click,
    this.content.scrollTo({ y: 0, x: 0, animated: true });
`

Here are the screen shots - 
## Expected Behaviour
<img width="359" alt="screen shot 2017-09-27 at 3 55 09 pm" src="https://user-images.githubusercontent.com/2196040/30910190-61830d12-a3a1-11e7-96f2-e73726dae504.png">

## Actual Behaviour
<img width="375" alt="screen shot 2017-09-27 at 3 54 28 pm" src="https://user-images.githubusercontent.com/2196040/30910298-cf82c1e0-a3a1-11e7-9095-0cb2bc3d273d.png">

<img width="369" alt="screen shot 2017-09-27 at 3 54 54 pm" src="https://user-images.githubusercontent.com/2196040/30910189-61814040-a3a1-11e7-8cbe-624b1c217dd7.png">

### Environment
  Environment:
    OS:  macOS Sierra 10.12.6
    Xcode:  9.0 (9A235)

  Packages: (installed)
    react-native: 0.45.1
    react: 16.0.0-alpha.12

  Target Platform: iOS (11)

**Comment by JeremDsgn** [comment]
This issue have been fixed on latest version of react-native, see here: https://github.com/facebook/react-native/commit/19544385335647e82a83b8103e48d3f08d8f670f#diff-973dcd0e3fbfcc5e35485bb6404a2fd2

You can either upgrade, or patch the code library component if you can't upgrade.
