### ISSUE TITLE
Inconsistent scaling with adjustsFontSizeToFit and numberOfLines=1

### ISSUE THREAD

**Issue by zachasme** [facebook/react-native#16124]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS:  Linux 4.12
  Node:  8.5.0
  Yarn:  1.0.1
  npm:  5.3.0
  Watchman:  4.7.0
  Xcode:  N/A
  Android Studio:  Not Found

Packages: (wanted => installed)
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: 0.48.4 => 0.48.4

  Target Platform: iOS (9.3.5)

### Steps to Reproduce

1. Create a Text element with `adjustsFontSizeToFit` and `numberOfLines={1}`
2. Put it in a View and set `style={{flex: 1}}` on both elements.

### Expected Behavior

The paragraph inside the text element is adjusted to fit on a single line, with every word visible.

### Actual Behavior

The paragraph is scaled to fit, but inconsistently. Sometimes the last word is cut off. Adding/removing a word sometimes fixes this. See [screenshot](https://imgur.com/RfsnwMN).

### Reproducible Demo

https://snack.expo.io/BkXvD4qjb

**Comment by zachasme** [comment]
For anyone else encountering this, as temporary workaround we're adding a regular space followed by a non-breaking space: `<Text {...props}>Long Paragraph {"\u00a0"}</Text>`.

**Comment by CharlieOrlando** [comment]
Finally found someone else with this issue! I have been searching like crazy to find an answer. Has anyone else found a solution besides the hacky workaround??

**Comment by iPrytz** [comment]
I'm also looking for a better solution for this, i've made a calculator where the text scales if the input is a big number. When it starts to scale, the last char is sometimes cut of :(

**Comment by chriscohoat** [comment]
I've been struggling for days on this and I believe the trick is to use a mono-spaced font family as well, like `Helvetica Neue`. Used in combination with @zachasme's fix everything seems to render properly.
