### ISSUE TITLE
peer dep missing: react@> 15.0.0 using create-react-native-app

### ISSUE THREAD

**Issue by julesmoretti** [facebook/react-native#16120]
### Is this a bug report?

Yes its a bug report

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

yes

### Environment

Environment:
  OS:  macOS Sierra 10.12.6
  Node:  7.0.0
  Yarn:  Not Found
  npm:  3.10.8
  Watchman:  4.7.0
  Xcode:  Xcode 9.0 Build version 9A235
  Android Studio:  2.3 AI-162.3934792

Packages: (wanted => installed)
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: ^0.48.4 => 0.48.4

### Steps to Reproduce

(Write your steps here:)

1. create-react-native-app TestProject
2. cd TestProject
3. npm list --depth=0 

### Expected Behavior

To return no npm ERR

### Actual Behavior

it returns 2 npm errors:

```
OperaSetup@0.1.0 /Users/jmoretti/Git/logitech/ux-smarthome/OperaSetup
├── expo@21.0.2
├── jest-expo@21.0.2
├── react@16.0.0-alpha.12
├── react-native@0.48.4
├── react-native-scripts@1.5.0
└── react-test-renderer@16.0.0-alpha.12

npm ERR! peer dep missing: react@>=15.4.0, required by react-native-branch@2.0.0-beta.3
npm ERR! peer dep missing: react@> 15.0.0, required by react-native-gesture-handler@1.0.0-alpha.22
```

### Reproducible Demo

[TestProject.zip](https://github.com/facebook/react-native/files/1338850/TestProject.zip)

**Comment by ide** [comment]
This is an issue with create-react-native-app, can you re-open this issue over there?

**Comment by julesmoretti** [comment]
@ide - this should not be closed and is an issue that should be within this repo rather than `create-react-native-app` ones. Because your quick start deployment guideline from https://facebook.github.io/react-native/docs/getting-started.html is exclusively contingent on this tool and therefore it becomes in my opinion your responsibility to make sure it is maintained and not your users.

**Comment by ide** [comment]
create-react-native-app is maintained by several of the same people and the root issue is there. The actionable thing that a maintainer of the react-native repo can do is to point you at a more precise repo to open the issue.

**Comment by julesmoretti** [comment]
@ide that is one method (getting your users to do the work). The other is for your team to point to this issue on their repo instead, which reduces the frustration for your users.

Anyways I have added it here: https://github.com/react-community/create-react-native-app/issues/420

Thanks

**Comment by julesmoretti** [comment]
@ide - No one resolved this issue yet...

**Comment by sm1th** [comment]
Having the same problem as well... Desperately waiting for a fix!

**Comment by julesmoretti** [comment]
@sm1th - expo is the one that is throwing this off check this out:
https://github.com/expo/expo/issues/726

**Comment by sm1th** [comment]
Thanks @julesmoretti, turns out it is fine to ignore these errors. I thought this was somehow causing `npm start` not to work, but if I had read the error that `npm start` was giving more carefully I could have just installed watchman and continued on with my day 👍
