### ISSUE TITLE
Inconsistent scaling with adjustsFontSizeToFit and without numberOfLines set

### ISSUE THREAD

**Issue by zachasme** [facebook/react-native#16125]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
OS: Linux 4.12
Node: 8.5.0
Yarn: 1.0.1
npm: 5.3.0
Watchman: 4.7.0
Xcode: N/A
Android Studio: Not Found

Packages: (wanted => installed)
react: 16.0.0-alpha.12 => 16.0.0-alpha.12
react-native: 0.48.4 => 0.48.4

Target Platform: iOS (9.3.5)

### Steps to Reproduce

1. Create a Text element with `adjustsFontSizeToFit` and some fixed dimensions.
2. Try different heights

### Expected Behavior

The paragraph is always visible with no text cut off.

### Actual Behavior

At some heights the scaling results in the top of the first line and the bottom of the last line being cut off. See [screenshot](https://imgur.com/a/DT91O)

### Reproducible Demo

Try the following snack, changing the height up/down a few pecentage points until the issue occurs (as in screenshot above).

https://snack.expo.io/BkMMmrqo-

**Comment by CharlieOrlando** [comment]
Have you found a solution for this issue??

**Comment by zachasme** [comment]
For anyone else encountering this, as temporary workaround we're wrapping text in a pair of line-breaks and non-breaking spaces: `<Text {...props}>{"\u00a0\n"}Long Paragraph{"\n\u00a0"}</Text>`.

**Comment by CharlieOrlando** [comment]
Yeah. I saw that solution in your other post (quite clever, i might add). Was wondering if there's been any official word on a fix to the react native prop itself. I'd also be curious to know what causes the issue in the first place. It's quite perplexing. Anyway, appreciate the reply and the workaround. It seriously took me days before I found it.

**Comment by zachasme** [comment]
Do note that this is a slightly different workaround. We had to apply both for multiline autoscaled text, while we only needed the other for singleline. I don't know what the underlying issue is, and haven't had the time to investigate further.

**Comment by CharlieOrlando** [comment]
Only needed it for the single line at first, but just realized I now need it for a multiline so this added solution is much appreciated!
