### ISSUE TITLE
React-Native Picker.Item color property set also on selected item

### ISSUE THREAD

**Issue by dragos-panaitescu** [facebook/react-native#16129]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?
Yes

### Environment

  Environment:
OS: Ubuntu 16.04
Node: 7.6.0
Yarn: 0.24.6
npm: 4.1.2
Watchman: 4.7.0
Xcode:-
Android Studio: 2.3 AI-162.4069837

  Packages: (wanted => installed)
    react-native: 0.45.1 => 0.45.1
    react: 16.0.0-alpha.12 => 16.0.0-alpha.12

  Target Platform: Android

### Steps to Reproduce

Using the Picker component in Android, if you set color property on one of the Picker.Item components this color will be used also for the selected item.

### Expected Behavior

The color would be applied only to the Picker.Item with that color property.

### Actual Behavior

In my case I used set a color for the first Picker.Item and it worked. The problem is that when you select another item it gets that color also.

### Reproducible Demo

https://snack.expo.io/rkFcoqcjb

**Comment by vonovak** [comment]
indeed looks like a bug. interestingly, if you explicitly specify the color also for the second item, it works..
