### ISSUE TITLE
Update README.md License Section

### ISSUE THREAD

**Issue by phc5** [facebook/react-native#16142]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Steps to Reproduce

1. Open README 
2. Go to License Section

### Expected Behavior

React is now [MIT licensed](https://github.com/facebook/react/blob/master/LICENSE).

### Actual Behavior

README says BSD licensed.

**Comment by ide** [comment]
The README should have said React Native (still BSD) instead of React. Anyone want to send a PR to make that change at the bottom?

**Comment by TheSavior** [comment]
PR Landed. Thanks!
