### ISSUE TITLE
react-native run-android fails

### ISSUE THREAD

**Issue by Pravandan** [facebook/react-native#16143]
Android Support Repository has already been installed.

A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not find com.android.support:appcompat-v7:23.0.1.
     Searched in the following locations:
         file:/C:/Android/sdk/extras/android/m2repository/com/android/support/appcom
pat-v7/23.0.1/appcompat-v7-23.0.1.pom
         file:/C:/Android/sdk/extras/android/m2repository/com/android/support/appcom
pat-v7/23.0.1/appcompat-v7-23.0.1.jar
         file:/C:/Users/Pravandan Chand/Documents/shagun_react_app/shagun_app/androi
d/sdk-manager/com/android/support/appcompat-v7/23.0.1/appcompat-v7-23.0.1.jar
     Required by:
         shagun_app:app:unspecified
         shagun_app:app:unspecified > com.facebook.react:react-native:0.48.4

**Comment by 8of** [comment]
Have you tried to add 
`compile 'com.android.tools:sdklib:23.0.1'`
to file
**android/app/build.gradle**?

what about installing **Android Support LIbrary**, not **Android Support Repository**?
