### ISSUE TITLE
multipart != application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by yooouuri** [facebook/react-native#16149]
On iOS i don't have any problems.

Running the app for the first time on Android.

![whatsapp image 2017-09-30 at 18 57 32](https://user-images.githubusercontent.com/12934957/31048058-dc46cc02-a615-11e7-8d3b-361f8b9d9708.jpeg)

Two times I do a fetch:
```
    const data = new FormData();
    ......

    fetch('........', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded'
      },
      body: data
    })
```

Can't find anything about this error...

**Comment by lra-tapptic** [comment]
I had the same problem when the formData was empty. Sending body: null resolved the error in that case.

**Comment by yooouuri** [comment]
But my formData is not empty...

**Comment by 1uokun** [comment]
My Solution

> react-native 0.54.4
> react 16.3.1
---------------
```
let xhr = new XMLHttpRequest();
xhr.open('POST', api.url);
let formData = new FormData();
formData.append("name",name);
......
xhr.send(formData);
.
.
.
```
> only for android,ios does not need
> fetch不行就肝原生ajax啊

**Comment by zeddz92** [comment]
Hi, as @jasonmerino  said, you have to set 'Content-Type': 'multipart/form-data' and specify the type of your file like this:
` const data = new FormData();
  data.append('image', {
                uri: source,
                name: 'image',
                type: 'image/png'
});`
