### ISSUE TITLE
Error linking 0.6.1

### ISSUE THREAD

**Issue by yooouuri** [facebook/react-native#16147]
Updated to 0.6.1

```
npm update
+ react-native-fbsdk@0.6.1
```

When i try to link with `react-native link react-native-fbsdk`, i get the following error:

```
Scanning 561 folders for symlinks in /Users/youri/atlacarte-mobile/node_modules (5ms)
rnpm-install info Android module react-native-fbsdk is already linked 
rnpm-install info Linking react-native-fbsdk ios dependency 
rnpm-install ERR! Something went wrong while linking. Error: Expected "/*", "//", or "{" but "<" found. 
Please file an issue here: https://github.com/facebook/react-native/issues 

Expected "/*", "//", or "{" but "<" found.
```

0.6.0 does not fail.

**Comment by richardgirges** [comment]
This has been a long standing issue with `react-native-fbsdk`. The current working solution is to simply stay on 0.6.0 - although I believe there are various issues with building android while on 0.6.0 in with RN 0.47+. 

A PR that was opened back in July resolves this but hasn't been merged yet:
https://github.com/facebook/react-native-fbsdk/pull/349

Duplicate/related issues:
#10032
#14594 
#15069
#14594
