### ISSUE TITLE
ScrollView overScrollMode prop not working

### ISSUE THREAD

**Issue by Symous** [facebook/react-native#16144]
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

sure

### Environment

OS:  macOS Sierra 10.12.6
    Node:  8.4.0
    Yarn:  0.27.5
    npm:  5.4.0
    react-native:0.45.1
   Target Platform: Android (6.0)

### Steps to Reproduce

(Write your steps here:)
```js
<ScrollView ref='scrollView'  overScrollMode={'always'} contentContainerStyle={{alignItems:'center'}}>

          <View style={{...}}>
        </ScrollView>
```
### Expected Behavior

It supposed to be scrolled whatever the height of the content is;

### Actual Behavior
Can not be scrolled.

**Comment by wv1124** [comment]
try to remove contentContainerStyle

**Comment by wangkai63** [comment]
this bug not fix ?

**Comment by borisyankov** [comment]
I am encountering the same issue.

**Comment by tranhoangduong1994** [comment]
Same problem here. Does anyone have a fix or workaround?
