### ISSUE TITLE
peekEnabled not woking in ViewPagerAndroid . 

### ISSUE THREAD

**Issue by PARAGJYOTI** [facebook/react-native#16158]
### Is this a bug report?

Yes

### Issue

  The most awaited property 'peekEnabled' in ViewPagerAndroid is not working . I believe , this is an exciting feature for which most of  developers been waiting for . Though its documented , it doesn't work . Even it's not showing in the 'autocomplete' feature in 'Visual studio code' (Normally it shows up as autoSuggestion when I start to type the prop) . I checked the props in js code , but the prop is there . But setting the property to true in main ViewPagerAndroid.android.js component also doesn't help . It's probably isn't implemented correctly in Native  code . Are you guys having the issue ? Please let me know , I upgraded from 0.43 to 0.48 just to get this feature . Now its not here .
  

### Environment

  Platform - Android
  Development Platform- Windows 10

  Packages: (wanted => installed)
    react-native: 0.48.4 => 0.48.4
    react: 16.0.0-alpha.12 => 16.0.0-alpha.12

**Comment by Noitidart** [comment]
May you please share the code that worked for you with/without `peekEnabled`. I actually can't even get a copy paste from docs of the `ViewPagerAndroid` to work - https://stackoverflow.com/questions/47584773/viewpagerandroid-doesnt-show-children

**Comment by koox00** [comment]
Seems that `peekEnabled` to work as expected needs `ViewPagerAndroid` to have `padding`.

Looking at the source code, child views style is set to `position: absolute` and `right,left,top,bottom: 0` so the parent's container padding has no effect.

**Comment by Noitidart** [comment]
Interesting at @koox00 - may you please share some examples.
