### ISSUE TITLE
How can i increase the fontsize of the items inside the FlatList ?

### ISSUE THREAD

**Issue by jpca999** [facebook/react-native#16157]
return (
            <FlatList
              data={this.props.properties}
              renderItem={({ item }) => (
                <ListItem onPress={()=>navigate('editProperty',{item})}
                  roundAvatar
                  title={`${item.agent_name} `}
                  subtitle={`${item.address}, ${item.city}`}
                  style={styles.row_alternate}
                  containerStyle={{ borderBottomWidth: 0 }}
                />
              )}
              keyExtractor={item => item._id}
              ItemSeparatorComponent={this.renderSeparator}
              ListHeaderComponent={this.renderHeader}
              ListFooterComponent={this.renderFooter}
              onRefresh={this.handleRefresh}
              refreshing={this.state.refreshing}
              onEndReached={this.handleLoadMore}
              onEndReachedThreshold={50}
            />
    );
  }

const styles = StyleSheet.create({
    row_alternate: {
        padding: 20,
        backgroundColor: 'white',
        fontSize: 90,
    },
});

I tried,

  <FlatList
              data={this.props.properties}
              renderItem={({ item }) => (
                <ListItem style={{backgroundColor: 'blue', flex: 0.3}} onPress={()=>navigate('editProperty',{item})}
                  roundAvatar
                  title={`${item.agent_name} `}
                  subtitle={`${item.address}, ${item.city}`}
                  style={styles.row_alternate}
                  containerStyle={{ borderBottomWidth: 0, backgroundColor: 'blue' }}
                />

**Comment by chirag04** [comment]
@facebook-github-bot stack-overflow
