### ISSUE TITLE
Unable to resolve module 'VibrationIOS'

### ISSUE THREAD

**Issue by louuysison** [facebook/react-native#16165]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS:  macOS Sierra 10.12.6
  Node:  8.2.0
  Yarn:  0.27.5
  npm:  5.4.2
  Watchman:  4.7.0
  Xcode:  Xcode 9.0 Build version 9A235
  Android Studio:  2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: 0.48.2 => 0.48.2

### Steps to Reproduce

1. react-native-git-upgrade 0.48.2
2. Xcode -> Run

### Expected Behavior

Expected to run the project on the simulator

### Actual Behavior

```
bundling failed: "Unable to resolve module `VibrationIOS` from `/Users/louallen/bliimo/bliimo-mobile/node_modules/react-native/Libraries/react-native/react-native-implementation.js`: Module does not exist in the module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`."
```

**Comment by 8of** [comment]
According to docs **VibrationIOS** is being deprecated:
https://facebook.github.io/react-native/docs/vibrationios.html

Please, use [Vibration](https://facebook.github.io/react-native/docs/vibration.html) instead.
