### ISSUE TITLE
[Image] padding not work

### ISSUE THREAD

**Issue by walfud** [facebook/react-native#16164]
Environment:
  OS:  macOS Sierra 10.12.6
  Node:  8.6.0
  Yarn:  1.1.0
  npm:  5.3.0
  Watchman:  Not Found
  Xcode:  Not Found
  Android Studio:  2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: 0.48.3 => 0.48.3

====================

I just write the simple code below. The problem is **Why the padding in <Image> style not work?**
```js
            <View style={{
                flex: 1,

            }}
            >
                <Image style={{
                    flex: 1,
                    padding: 10,
                }}
                       source={{uri: 'd7'}}
                       resizeMode='stretch' />
            </View>
```
This is the result. You can see there is no padding around image.
![image](https://user-images.githubusercontent.com/9317897/31061715-a4d86838-a756-11e7-8f8b-c8df99e216a8.png)

**Comment by ubatin** [comment]
Add `padding` on parent component of image component like below 
```javascript
...

<View
  style={{ flex: 1, padding: 10 }}>
    <Image 
      style={{ flex: 1 }}
      source={{ uri: 'd7' }}
      resizeMode='stretch' />
</View>

...
```

**Comment by walfud** [comment]
@ubatin Yes I know this can do. But I want to know why the padding does not work on <Image>?

**Comment by ubatin** [comment]
Hi @walfud ,
The `Image` component is only to show image. So, Why do you need to padding on `Image` component? Actually you should learn to know about `Image` component on [here](https://github.com/facebook/react-native/tree/master/Libraries/Image).

Should read before [reporting new issues](http://facebook.github.io/react-native/docs/contributing.html#reporting-new-issues).
