### ISSUE TITLE
React-Native: TextInput cannot display the word when i'm typing

### ISSUE THREAD

**Issue by monkeylau12** [facebook/react-native#16169]
### Is this a bug report?

No

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment
    OS:  macOS Sierra 10.12.6
    Node:  6.11.3
    Yarn:  1.1.0
    npm:  5.3.0
    Watchman:  4.9.0
    Xcode:  Xcode 8.3.3 Build version 8E3004b
    Android Studio:  2.3 AI-162.4069837

  Packages: (wanted => installed)
    react-native: 0.48.1 => 0.48.1
    react: 16.0.0-alpha.12 => 16.0.0-alpha.12

  Target Platform: iOS (10.3)

### Steps to Reproduce

I go the search tab to input the keywords

### Expected Behavior

I can see what im typing.

### Actual Behavior

I cannot see what i had typed, but the search function is perfectly work!

(Write what happened. Add screenshots!)

### Reproducible Demo
`render() {
        var spinner = this.state.isLoading ?
              ( <ActivityIndicator
                  hidden='true'
                  size='large'/> ) :
              ( <View/>);
          return (
              <View style={styles.container}>
                  <Text style={styles.instructions}>Search by book title and/or author</Text>
                  <View>
                      <Text style={styles.fieldLabel}>Book Title:</Text>
                      <TextInput style={styles.searchInput} onChangeText={this.bookTitleInput.bind(this)}/>
                  </View>
                  <View>
                      <Text style={styles.fieldLabel}>Author:</Text>
                      <TextInput style={styles.searchInput} onChangeText={this.bookAuthorInput.bind(this)}/>
                  </View>
                  <TouchableHighlight style={styles.button}
                                      underlayColor='#f1c40f'
                                      onPress={this.searchBooks.bind(this)}>
                      <Text style={styles.buttonText}>Search</Text>
                  </TouchableHighlight>
                  {spinner}
                  <Text style={styles.errorMessage}>{this.state.errorMessage}</Text>
              </View>
          );
      }
      bookTitleInput(text) {
          this.setState({ bookTitle: text });
      }
      bookAuthorInput(text) {
          this.setState({ bookAuthor: text });
      }`

Style:
`const styles = StyleSheet.create({
  container: {
    flexDirection: 'column',
    justifyContent: 'center',
    marginTop: 65,
    padding: 10,
    flex:1
  },
  searchInput: {
    textAlign: 'left',
    color: 'black',
    margin: 5,
    height: 50,
    borderColor: '#60b7e2',
    borderWidth: 2,
    flex: 2,
    padding: 20`

Screenshot:
![simulator screen shot 2017 10 2 7 43 14](https://user-images.githubusercontent.com/32454044/31075889-56b5e8ca-a7aa-11e7-9a22-766426752745.png)

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by HilSny** [comment]
Hi!

You need to provide a value to the TextInput and that value will update with state. See the example at the top of this page: https://facebook.github.io/react-native/docs/textinput.html

**Comment by sanketthanvi** [comment]
Hi @HilSny 
I don't think thats the case here.
On https://facebook.github.io/react-native/docs/textinput.html, copy following code in first example.
It works fine. Attaching screenshot as well.

`
import React, { Component } from 'react';
import { AppRegistry,View, TextInput,Text } from 'react-native';

export default class UselessTextInput extends Component {
  constructor(props) {
    super(props);
    this.state = { text: 'Initial Placeholder' , textTwo:'Initial Two'};
  }

  render() {
    return (
      <View>
      <Text>
        text: {this.state.text}
        </Text> 
              <Text>
        textTwo: {this.state.textTwo}
        </Text>
      <TextInput
        style={{height: 40, borderColor: 'gray', borderWidth: 1}}
        onChangeText={this.onChangeText.bind(this)}
      />
      <TextInput
        style={{height: 40, borderColor: 'gray', borderWidth: 1}}
        onChangeText={this.onChangeTextTwo.bind(this)}
      />
      </View>
    );
  }
  
  onChangeText(text){
    this.setState({text})
  }
  
  onChangeTextTwo(text){
    this.setState({textTwo:text})
  }
}

// skip this line if using Create React Native App
AppRegistry.registerComponent('AwesomeProject', () => UselessTextInput);

`

![screen shot 2017-11-23 at 7 21 34 pm](https://user-images.githubusercontent.com/30018108/33176029-a25cf488-d083-11e7-989a-ac39e8cee5d2.png)
