### ISSUE TITLE
peer dep missing: react@> 15.0.0 on fresh install

### ISSUE THREAD

**Issue by julesmoretti** [facebook/react-native#16174]
### Is this a bug report?
yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?
yes

### Environment
Environment:
  OS:  macOS Sierra 10.12.6
  Node:  7.0.0
  Yarn:  Not Found
  npm:  3.10.8
  Watchman:  4.7.0
  Xcode:  Xcode 9.0 Build version 9A235
  Android Studio:  2.3 AI-162.3934792

Packages: (wanted => installed)
  react: ^16.0.0 => 16.0.0
  react-native: ^0.48.4 => 0.48.4

### Steps to Reproduce
Since `create-react-native-app` is also not working currently, I attempted to recreate from scratch a react-native repo. In order to do this I installed `react`, `react-native`, and `expo`. Doing these for steps give `npm ERR`.

1. mkdir test
2. cd test
3. npm init
4. npm i --save react react-native expo
5. npm list --depth=0

```
├── expo@21.0.2
├── UNMET PEER DEPENDENCY react@16.0.0
└── react-native@0.48.4

npm ERR! peer dep missing: react@16.0.0-alpha.12, required by react-native@0.48.4
npm ERR! peer dep missing: react@16.0.0-alpha.12, required by react-native-svg@5.3.0
```

### Expected Behavior
Upon install I expected to get no `npm ERR` and just a clean.

```
├── expo@21.0.2
├── react@16.0.0
└── react-native@0.48.4
``` 

### Actual Behavior
Since `create-react-native-app` is also not working currently, I attempted to recreate from scratch a react-native repo. In order to do this I installed `react`, `react-native`, and `expo`. Doing these for steps give `npm ERR`.

```
├── expo@21.0.2
├── UNMET PEER DEPENDENCY react@16.0.0
└── react-native@0.48.4

npm ERR! peer dep missing: react@16.0.0-alpha.12, required by react-native@0.48.4
npm ERR! peer dep missing: react@16.0.0-alpha.12, required by react-native-svg@5.3.0
```

### Reproducible Demo
`npm i`
[test.zip](https://github.com/facebook/react-native/files/1349929/test.zip)

**Comment by julesmoretti** [comment]
So just to follow up on this. Its Expo that is throwing everything off..

```
@logitech/pavarottisetup@1.0.0 /Users/jmoretti/Git/logitech/ux-smarthome/PavarottiSetup
├── expo@21.0.2
├── react@16.0.0-beta.5
└── react-native@0.49.1

npm ERR! peer dep missing: react@>=15.4.0, required by react-native-branch@2.0.0-beta.3
npm ERR! peer dep missing: react@> 15.0.0, required by react-native-gesture-handler@1.0.0-alpha.22
npm ERR! peer dep missing: react@16.0.0-alpha.12, required by react-native-svg@5.3.0
```

If you just do `npm i --save react-native` then `npm list --depth=0` this will show you which react version to install. And then if you install that version and do another `npm list ...` then you dont get any errors until you do..... `npm i --save expo`!!!! WTF>>> 😱

**Comment by entraigas** [comment]
Hi, today I face the same issue... after spending a lot of time, I think might I found a workaround.
You can use the below library versions to get rid of the missing dependencies:

├── expo@16.0.0
├── react@15.4.1
└── react-native@0.42.3

Hope it helps, cheers!
