### ISSUE TITLE
[FlatList] Re-render issue after item delete from flatlist array

### ISSUE THREAD

**Issue by MSSPL-PiyaleeMaiti** [facebook/react-native#16183]
### Is this a bug report?

Yes, this is a bug of FlatList. After remove a index value from flatlist array, then rendering item some view is missing. Re-render is breaking in many portion.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
    OS:  iOS, Android
  Packages: 
   "react-native": "^0.44.0",
   "react": "16.0.0-alpha.6",

### Steps to Reproduce

1. We list item of array in FlatList View. 
2. Remove one item index from array which provide in FlatList view.
3. After remove render view break or hide for some item not for all item.
4. After refresh the view render issue will be same.

### Expected Behavior

Rener view will be same as before and after remove index from flalist array item. No view will be changes if we delete index or add a new index in middile or in end or in start.

### Actual Behavior

1. First time array item in FlatList is showing properly.
2. When we delete one index value from array FlatList item some view will hide.
3. After close app again open the app then its again works fine. 
4. Why auto render will not working and also not working when doing pull to refresh.
5. But it's working fine for loadmore item render.

Please provide any solution for this FlatList view, maybe flatlist store old data and we should delete old data store. But don't know how to remove the old data store history form flatlist.

**Comment by fatwhale** [comment]
I just encountered with this yesterday. My solution is to set a height in your items inside the FlatList. So, basically, there is some wrong about height calculation when your view gets rerendered. Maybe FlatList can have some better internal height calculation schemes?

**Comment by MSSPL-PiyaleeMaiti** [comment]
@fatwhale we solve our problem. Their is some view star and ending problem. And also some styling problem. For this kind of issue of view and style some view will missing after delete array from flatlist and some view will be extra exist.
