### ISSUE TITLE
borderHorizontalWidth and borderVerticalWidth missing

### ISSUE THREAD

**Issue by jacobp100** [facebook/react-native#16187]
We have these for `margin` and `padding`. Should the same extend to borders? It seems like it is already supported in yoga.

**Comment by ethanyuwang** [comment]
any update on this?

**Comment by yungsters** [comment]
Yes, we are missing `borderHorizontalWidth` and `borderVerticalWidth`.

**Comment by cpojer** [comment]
@jacobp100 would you be open to sending a Pull Request that adds this functionality?

**Comment by cpojer** [comment]
This isn't currently on anyone's roadmap and it seems like there isn't a significant need so I'm gonna close this issue. I still think we should have this feature so if you wanna send a PR, that would be awesome!
