### ISSUE TITLE
Transform rotatez working on ios, but not on android

### ISSUE THREAD

**Issue by chakrihacker** [facebook/react-native#16189]
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

yes

### Environment

  Environment:
    OS:  Ubuntu 16.04
    Node:  8.5.0
    Yarn:  1.1.0
    npm:  5.4.2
    Android Studio:  2.3 AI-162.4069837

  Packages: (wanted => installed)
    react-native: 0.47.2 => 0.47.2
    react: 16.0.0-alpha.12 => 16.0.0-alpha.12

  Target Platform: Android

### Steps to Reproduce

please check [Expo](https://snack.expo.io/SJfzTlzh-)

in ios transform rotateZ is working, but in android it's not working 
I am using like this
```
myStyle: {
    transform: [{ rotateZ: '180deg'}]
}
```

### Expected Behavior

It has to display graph

### Actual Behavior

It displays nothing

**Comment by aidan2129** [comment]
Just using `[{ rotate: '180deg'}]` works for me, Seems to do the same as rotateZ.

**Comment by chakrihacker** [comment]
Still not working in android

**Comment by aidan2129** [comment]
Strange is working for me on react native 0.48.3

**Comment by chakrihacker** [comment]
Will update react-native from 0.47 to 0.48 and check
          
            
            On Oct 6 2017, at 1:46 pm, Aidan <notifications@github.com> wrote:
            
            
              Strange is working for me on react native 0.48.3

**Comment by chakrihacker** [comment]
It's not working

**Comment by aidan2129** [comment]
Can you post a more detailed code example including the view you have the style attached to. Cant really think of anything else without seeing that.

**Comment by shyam528** [comment]
It's not working in my case also

**Comment by badaz** [comment]
I don't know if it's the same problem, but my transform rotate is working except for borders, everything in the view rotates but not the colored solid border, this only happens on android 7 and 8 though. I do not have the problem in genymotion running Android 5 and 6, and yet I have the problem on my Huawei Mate 8 running android 7, and in genymotion running android 7 and 8.
