### ISSUE TITLE
[Text] padding problem

### ISSUE THREAD

**Issue by sherlock221** [facebook/react-native#1619]
The text element set padding under view causes no background to display.  

on react-naitve 0.6.0-rc and 0.4.4 

but rnplay is fine 
https://rnplay.org/apps/E6HXug

**Comment by sherlock221** [comment]
Just tested 0.5.0 is ok 
![image](https://cloud.githubusercontent.com/assets/5842676/8147086/ad3ea27e-1290-11e5-872e-908a80fc21e7.png)

**Comment by chirag04** [comment]
This thing is not vertically centered, which i think it should be. I was hit by this bug too. Not sure whats the problem is here.

**Comment by brentvatne** [comment]
This is what I see on 0.6.0rc:

![screen shot 2015-06-14 at 9 56 39 pm](https://cloud.githubusercontent.com/assets/90494/8153283/451ee212-12e0-11e5-961d-f8247f0f425a.png)
(https://rnplay.org/apps/BrylDg)

There is some discussion going on about this in #1504 as well.

**Comment by jellea** [comment]
What's the status on this? (@nicklockwood)

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/text-padding-problem
