### ISSUE TITLE
Getting "Application has not been registered" in mature project

### ISSUE THREAD

**Issue by wbattel4607** [facebook/react-native#16195]
### Is this a bug report?

Maybe... but my guess is that it's not a widespread bug but rather an uncommon environment issue that needs more documentation.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes.

### Environment

Environment:
    OS:  macOS Sierra 10.12.6
    Node:  6.10.3
    npm:  5.4.0
    Watchman:  4.9.0
    Xcode:  9.0 (9A235)

  React/React-Native
    react-native: 0.45.1 (can't upgrade yet because of dependencies, but we've been using this version without issues for a while)
    react: 16.0.0-alpha.12

  Target Platform:
    Xcode Target: 10.0
    Device (Physical iPhone 6 Plus) iOS: 10.3.3

### Steps to Reproduce

(Write your steps here:)

1. Open Xcode app workspace (generated by cocoa pods)
2. Press Run using physical or simulator device
... this is a niche issue so I don't expect anyone to be able to easily reproduce it. See below for the explanation.

### Expected & Actual Behavior

Until today, the project built and ran with no issues. I have never been able to run from terminal (react-native run-ios) because of [this](https://github.com/facebook/react-native/issues/12754) issue, but running from Xcode has never been an issue.

This project has been building fine for the past 6+ months but today I am getting [this](https://pastebin.com/r9Qdxv9Z) error. `undefined is not an object (evaluating 'n.default.PropTypes.any')`

Research into the error suggests that it is typically caused by one of three things:
1. Updating react-native without properly migrating the project, which I haven't done
2. Running the packager in the wrong location / leaving it running from a different project, which is not the case for me (I've even tried restarting my computer)
3. Improperly registering app component, which hasn't been touched in my project in the past 6 months so I'd be shocked if it were this.

My index.ios.js looks like this, using the same `appname` I used when the project was initialized.
```
import { AppRegistry } from 'react-native';
import App from './src/App';

AppRegistry.registerComponent('appname', () => App);
```
The src/App file has not been modified since the last working build.

I've restarted Xcode, restarted Terminal, even restarted my computer but none of that helped.

**Does anyone have any ideas of what might have caused this? Again, this project has been working for quite a long time and nothing regarding AppRegistry has been modified, and my packager is running from the right location with the latest node modules.**

The project is confidential and even stripped down I'm not really able to share it- and it's a really niche environment problem so the same exact project would probably work on a different computer, i'm guessing.

**Comment by kelset** [comment]
Have you tried doing a more "deep" clean up of the project? Something along the lines of:

`watchman watch-del-all && rm -rf node_modules && rm -rf $TMPDIR/react-* && rm -rf $TMPDIR/npm-* && rm -rf android/build && rm -rf ios/build && yarn cache clean`

And then reinstalling the modules?

Can it be that maybe it's related to you updating to XCode 9?

**Comment by wbattel4607** [comment]
@kelset I've tried the deep cleaning to no avail. My co-developer on Xcode 8 is able to build the same code without this problem. I've been building on Xcode 9 without issues for about a week and it was lasted updated on my machine earlier than that, so I'd be surprised if that was related. It's quite strange- it really came out of the blue without a trace.

**Comment by kelset** [comment]
Not too much - let's just say that my best guess at the moment is that some peer/hidden dependency got updated and it breaks something related to PropTypes.

Tbh I really suggest you spend some time to upgrade to 46, 47, or 48 even. Or at least give it a try on a dedicated branch to see if it changes something.

**Comment by wbattel4607** [comment]
@kelset I can *try* it, but I have multiple important dependencies that are still upgrading from 0.45 and aren't yet functional on any more recent version, so I'm not sure how far the build will go before running into problems.

**Comment by wbattel4607** [comment]
Like you suggested, it looks like multiple peer dependencies were updated without my knowledge. That's the only difference I can find in Git, and the version before those dependency updates does build successfully for me.

Copying the npm files from the last commit and skipping `npm install` and just doing `npm link` instead has fixed the issue.

Since this issue *technically* isn't caused by React Native, I'm going to close this issue- but I am still in need of a long term solution (though my guess is that whichever dependency caused this will fix itself in time).

**Comment by kelset** [comment]
I see - thanks for the update. TBH I'm afraid your only long term plan is update to newer rn versions and fix the libs on your own (like, fork them and have npm point there)
