### ISSUE TITLE
[0.49.1] Broken bundling on run-ios in simulator

### ISSUE THREAD

**Issue by fungilation** [facebook/react-native#16208]
### Is this a bug report?
Yes.

Upgraded RN to 0.49.1.

Terminal output after `react-native run-ios`:
```
React packager ready.

Loading dependency graph, done.
Launching Dev Tools...
Bundling `index.js`  [development, non-minified]  0.0% (0/1), failed.
error: bundling failed: Error
    at DependencyGraph._getAbsolutePath ([PROJECT]/node_modules/metro-bundler/src/node-haste/DependencyGraph.js:305:11)
    at DependencyGraph.getDependencies ([PROJECT]/node_modules/metro-bundler/src/node-haste/DependencyGraph.js:283:4236)
    at Resolver.getDependencies ([PROJECT]/node_modules/metro-bundler/src/Resolver/index.js:129:5)
    at [PROJECT]/node_modules/metro-bundler/src/Bundler/index.js:642:39
    at Generator.next (<anonymous>)
    at step ([PROJECT]/node_modules/metro-bundler/src/Bundler/index.js:13:1336)
    at [PROJECT]/node_modules/metro-bundler/src/Bundler/index.js:13:1496
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

And a corresponding redbox on simulator, for "Cannot find entry file index.js in any of the roots". Reloading simulator would just repeat the above.

### Environment

Environment:
  OS:  macOS Sierra 10.12.6
  Node:  8.6.0
  Yarn:  1.1.0
  npm:  5.3.0
  Watchman:  4.9.0
  Xcode:  Xcode 9.0 Build version 9A235
  Android Studio:  Not Found

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: 0.49.1 => 0.49.1

Target Platform: iOS (11.0)

### Steps to Reproduce

1. `react-native-git-upgrade`
2. `react-native run-ios`
3. Bundling failure, as shown above

### Expected Behavior

App bundles and run.

### Actual Behavior

<img width="487" alt="screenshot 2017-10-04 17 08 46" src="https://user-images.githubusercontent.com/3803466/31205513-b7cd73f8-a926-11e7-8c63-f038428271a0.png">

Also in case it's 3rd package issues (unlikely since it's not building at all), here's my `package.json`:
```js
{
  "name": "[NAME]",
  "version": "0.0.1",
  "private": true,
  "eslintConfig": {
    "parserOptions": {
      "ecmaVersion": 6,
      "sourceType": "module",
      "ecmaFeatures": {
        "jsx": true,
        "experimentalObjectRestSpread": true
      }
    },
    "env": {
      "browser": true,
      "node": true
    },
    "plugins": [
      "react",
      "react-native"
    ],
    "rules": {
      "comma-dangle": [
        2,
        "always-multiline"
      ],
      "semi": [
        2,
        "never"
      ],
      "react-native/no-unused-styles": 2,
      "react-native/split-platform-components": 2
    }
  },
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "babel-plugin-idx": "^2",
    "he": "^1.1.0",
    "jssha": "^2.3.1",
    "lodash": "^4.17.2",
    "moment-timezone": "^0.5.10",
    "node-summary": "file:../node-summary",
    "react": "16.0.0-beta.5",
    "react-native": "0.49.1",
    "react-native-blur": "^3.1",
    "react-native-code-push": "5.1.3-beta",
    "react-native-firebase": "^3.0",
    "react-native-fit-image": "^1.4.8",
    "react-native-highlight-words": "^1.0.0",
    "react-native-keep-awake": "^2.0.4",
    "react-native-linear-gradient": "^2.0.0",
    "react-native-modalbox": "^1.3.8",
    "react-native-notification": "^2.0.0",
    "react-native-orientation": "^3.0.0",
    "react-native-parallax-scroll-view": "file:../react-native-parallax-scroll-view",
    "react-native-safari-view": "^2.0.0",
    "react-native-sentry": "^0.26",
    "react-native-status-bar-size": "^0.3.2",
    "react-native-swiper": "^1.5.10",
    "react-native-tooltip": "^5.0.0",
    "react-native-tts": "^1.3.0",
    "react-native-vector-icons": "^4.1.1",
    "react-native-webview-bridge": "lefnire/react-native-webview-bridge",
    "react-redux": "^5.0.1",
    "redux": "^3.6.0",
    "redux-thunk": "^2.1.0"
  },
  "devDependencies": {
    "redux-logger": "^3.0.6"
  }
}
```

### Reproducible Demo

Umm, am I the only one hitting this after all the RC's? I see some errors reported [like this](https://github.com/react-community/react-navigation/issues/901) that's caused by 3rd party packages, but my terminal output says nothing about errring on a certain package, it just ends on line `at process._tickCallback (internal/process/next_tick.js:188:7)`.

I would give more reproducing details if I even know where to look.

**Comment by iainkirkpatrick** [comment]
I'm seeing this too, with a similar upgrading RN to 0.49 situation. Fix for me was to duplicate my `index.ios.js` file and rename as `index.js` - the only indication of this I can see in the docs after a quick look is [here](https://github.com/facebook/react-native/commit/6e99e314b232c315628c31f97a865c17c071ad23#diff-c427a522f4ea08a4c045a518ac721ce9R586).

Does this mean we are required to have a single `index.js` entry point from 0.49?

**Comment by fungilation** [comment]
Interesting, will have to test that. 

How is this not a breaking change unlisted in changelog if intentional? I don't think it is as we still need iOS and android code separation.

**Comment by kytwb** [comment]
Experiencing as well.

**Comment by sasosaso** [comment]
Same here

**Comment by Andreyco** [comment]
> Interesting, will have to test that.
> 
> How is this not a breaking change unlisted in changelog if intentional? I don't think it is intentional as we still want iOS and android code separation.

While it's breaking change (should be listed), there is nothing preventing you from separating platform specific code.
I find it convenient to have single application entry point.

**Comment by grabbou** [comment]
It's not a breaking change since it should affect just new apps. See here: https://github.com/facebook/react-native/commit/6e99e314b232c315628c31f97a865c17c071ad23 - the commit modifies the HelloWorld app which is used as a template when using `init`.

I believe `git-upgrade` has a bug as it takes that change and applies it into your project whereas it doesn't touch filesystem: https://github.com/facebook/react-native/blob/master/local-cli/upgrade/upgrade.js#L139-L147

Either:
1) Remove `index.android.js` and rename `index.ios.js` to `index.js` if two files are identical
2) Revert that change and stick to two separate entry points

Please pay attention to `git diff` after upgrading. All changes should be at a glance. It's fine to revert them in `AppDelegate.m` and `MainApplication`.

**Comment by fungilation** [comment]
> 2. Revert that change and stick to two separate entry points

You mean revert to to RN 0.48? Ya that's what I did. The larger question is what's new convention going forward. I'm for just moving to `index.js` so I for one would just do that. But for RN, this needs:

1. Documented as a breaking change, or
2. Fix `upgrade.js` so it doesn't affect existing installation and allow separate ios and android indexes

Which should it be?

**Comment by Andreyco** [comment]
In my opinion, it definitely is breaking change. All existing apps does not work after upgrade. New ones are flawless, working as expected.

Thumbd up for single entry point! 👍🏻

**Comment by grabbou** [comment]
Can you share with me your `AppDelegate.m` after upgrade?

**Comment by fungilation** [comment]
0.48.4:
```objectivec
#ifdef DEBUG
    jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];
#else
    jsCodeLocation = [CodePush bundleURL];
#endif
```

0.49.1:
```objectivec
#ifdef DEBUG
    jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
    jsCodeLocation = [CodePush bundleURL];
#endif
```

Yes I manually merged since I have a conflicting change with CodePush that failed 3 way merge during `react-native-git-upgrade`. I also already tried `index.ios` on 0.49.1, same bundling failure.

**Comment by grabbou** [comment]
Hm, interesting that it failed even with `index.ios` - that shouldn't be
the case. Have you tried restarting packager w/o cache? Anyway, for
everyone - first step to try is to revert to `0.48.4` snippet that has been
pasted above. Simply said: make sure you have `index.ios` instead of
`index`.

**Comment by fungilation** [comment]
Upgrading to 0.49.1 again. Note these changes merged by `react-native-git-upgrade`

Applied patch to 'android/app/build.gradle' cleanly.

Added:
```
project.ext.react = [
    entryFile: "index.js"
]
```

Applied patch to 'android/app/src/main/java/com/wonderswipe/MainApplication.java' cleanly.

Added:
```
    @Override
    protected String getJSMainModuleName() {
      return "index";
    }
```
inside `private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {}`

**Comment by Andreyco** [comment]
Patch for my upgrade, excluded some files to keep it cleaner.

As expected, upgrade process did change code to pick `index.js` as entry point.
I am not sure it would be possible to merge `index.ios.js` and `index.android.js` automatically, but probably.

I think it is sufficient to inform users about this change ;)

```patch
diff --git a/android/app/build.gradle b/android/app/build.gradle
index 8fab59d..77b7192 100644
--- a/android/app/build.gradle
+++ b/android/app/build.gradle
@@ -80,6 +80,10 @@ project.ext.envConfigFiles = [
 
 apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"
 
+project.ext.react = [
+    entryFile: "index.js"
+]
+
 apply from: "../../node_modules/react-native/react.gradle"
 
 /**
diff --git a/android/app/src/main/java/com/app/MainApplication.java b/android/app/src/main/java/com/app/MainApplication.java
index 01d7c8c..ab01a1d 100644
--- a/android/app/src/main/java/com/app/MainApplication.java
+++ b/android/app/src/main/java/com/app/MainApplication.java
@@ -33,6 +33,11 @@ public class MainApplication extends Application implements ReactApplication {
         new ImagePickerPackage()
       );
     }
+
+    @Override
+    protected String getJSMainModuleName() {
+      return "index";
+    }
   };
 
   @Override
diff --git a/ios/app/AppDelegate.m b/ios/app/AppDelegate.m
index 4e1baef..a79f344 100644
--- a/ios/app/AppDelegate.m
+++ b/ios/app/AppDelegate.m
@@ -18,7 +18,7 @@
 {
   NSURL *jsCodeLocation;
 
-  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];
+  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
 
   RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                       moduleName:@"app"
```

**Comment by fungilation** [comment]
I confirm that bundler works on keeping `index.ios` in `AppDelegate.m`.

However my app is still broken hitting [this error](https://github.com/facebook/react-native/issues/16216). I do have `moment-timezone` dependency.

Commenting out code that uses moment and its import, and I'm hitting another error (redbox) in https://github.com/alinz/react-native-webview-bridge, about PropTypes.func and PropTypes being null. I know many old libraries are still stuck on not having migrated away from React.PropTypes, like https://github.com/clauderic/react-native-highlight-words/issues/2. But did RN 0.49 went and made  React.PropTypes use a silent error now, instead of the warning `Warning: PropTypes has been moved to a separate package...` on previous RN versions? Or this is due to React being upgraded?

Yes I'm frustrated how many things break on a single version upgrade. Tip on whether `React.PropTypes` should remain a warning in RN 0.49 would be appreciated.

**Comment by grabbou** [comment]
I have added note about this issue to the release notes as well as tweeted about it. Should prevent it from further escalation. 

 > Or this is due to React being upgraded? Doesn't look like any such move in React from googling.

This has been a change in React itself and so, is most likely a result of React being upgraded. Maybe we should be more explicit about its version bumps, especially when we change majors.

**Comment by cvraghav** [comment]
react-native-git-upgrade updated with index.js. I changed AppDelegate.m to
jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil]; which worked fine. [Look for @index.ios], earlier it was just @index

**Comment by Reiji87** [comment]
<img width="278" alt="screen shot 2017-10-11 at 3 52 16 pm" src="https://user-images.githubusercontent.com/8175305/31428119-42caab5e-ae9c-11e7-8eed-c08b253a87a8.png">
I keep getting the following error, is there a way to fix this?

**Comment by grabbou** [comment]
Have you restarted your packager and built iOS app once again? (either from
xcode or by running `react-native run-ios`)

**Comment by grabbou** [comment]
I am going to close this issue as the breaking change has been outlined in the release notes. Anyone else suffering from this issue, please comment here and I'll try to help to get your environment up and running.
