### ISSUE TITLE
react-native license clarification

### ISSUE THREAD

**Issue by sirme3** [facebook/react-native#16201]
Hello team,
I came across this recent blog post about React license changing to MIT (from BSD + Patents).
https://code.facebook.com/posts/300798627056246/relicensing-react-jest-flow-and-immutable-js/

I want to confirm if this change applies to react-native also, as it's built on React. 
I read thru this closed issue dating back to 2016 [7293](https://github.com/facebook/react/issues/7293). It is posted for React but react native was referenced in the discussion. So just wondering.

I am considering using react native for an app at my company. One of our legal reps pointed this blog post out, so just wanted to clarify with the community.

Appreciate any comments
thanks

**Comment by kelset** [comment]
Duplicate #16180.

**Comment by gaearon** [comment]
React Native (including Metro, Fresco, and Yoga) has also been relicensed as MIT.

https://github.com/facebook/react-native/commit/26684cf3adf4094eb6c405d345a75bf8c7c0bf88
