### ISSUE TITLE
scrolling form TextInput in Scroll View doesn't work when textAlign in set to right or center(android only)

### ISSUE THREAD

**Issue by ghost** [facebook/react-native#16206]
### Is this a bug report?

YES

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

NO
### Environment
  Environment:
      OS:  Linux 4.8
      Node:  8.6.0
      Yarn:  1.1.0
      npm:  5.3.0
      Watchman:  Not Installed
      Android Studio:  2.3 AI-162.4069837

  Packages: (wanted => installed)
      react-native: 0.48.4 => 0.48.4
      react: 16.0.0-alpha.12 => 16.0.0-alpha.12

  Target Platform: Android (6.0.1)
### Steps to Reproduce
1. Created a scroll view with some text Input component inside of it
2. set textAlign : 'right' or 'center' in text Input styles
3. try to scroll down or up from inside of text input, but text Input is focused and doesn't scroll up or down in scroll view
the issue is present in android only

### Expected Behavior
it must be possible to scroll in the scroll view when you tap a text Input, and then scroll, it works on textAlign : 'left',
### Actual Behavior
the scrolling doesn't work if you start scrolling on a text input

### Reproducible Demo
cause my country restriction, I don't have access to expo, so I just shared a small code that reproduce the problem 
`export default class ScrollViewWithTextInput extends React.Component {
render() {
    return (
    <ScrollView>
        <TextInput
            style={styles.input}
            placeholder={'توضیحات'}
            underlineColorAndroid='transparent'
        />
        <TextInput
            style={styles.input}
            placeholder={'توضیحات'}
            underlineColorAndroid='transparent'
        /><TextInput
            style={styles.input}
            placeholder={'توضیحات'}
            underlineColorAndroid='transparent'
        /><TextInput
            style={styles.input}
            placeholder={'توضیحات'}
            underlineColorAndroid='transparent'
        />
        <TextInput
            style={styles.input}
            placeholder={'توضیحات'}
            underlineColorAndroid='transparent'
        />
        <TextInput
            style={styles.input}
            placeholder={'توضیحات'}
            underlineColorAndroid='transparent'
        /><TextInput
            style={styles.input}
            placeholder={'توضیحات'}
            underlineColorAndroid='transparent'
        /><TextInput
            style={styles.input}
            placeholder={'توضیحات'}
            underlineColorAndroid='transparent'
        />
    </ScrollView>
)
}}
const styles = StyleSheet.create({
Container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
},
input: {
    width: 350,
    height: 100,
    margin: 5,
    borderColor: 'black',
    borderWidth: 2,
    textAlign: 'right'
}})`

**Comment by Luckygirlllll** [comment]
Have you found any solutions for that issue? I have a similar problem!

**Comment by erfanyousefifar** [comment]
@Luckygirlllll add  multiline={true} , keyboardType={'default'}, maxLength={10} to textInput props. it should work, i think that maxLength isn't necessary, but I didn't check

**Comment by Mostafasaffari** [comment]
@erfanyousefifar 
Thank you this is work for me. but when you choose keyboard to numeric it doesn't work

**Comment by erfanyousefifar** [comment]
@Mostafasaffari 
your welcome, and yeah it doesn't work on numeric, I hope they fix it.

**Comment by aizigao** [comment]
same problem, has some solution?

**Comment by erfanyousefifar** [comment]
@aizigao please read above answers.

**Comment by mafiusu** [comment]
@erfanyousefifar With `multiline={true}` and `keyboardType={'default}` it works but this is not the correct solution for the problem. I don't want to have a multiline input

**Comment by erfanyousefifar** [comment]
@mafiusu you can set number of lines to 1, I know that it's not a correct solution, but I don't have native knowledge to fix it unfortunately

**Comment by chamileb** [comment]
I have been experiencing this issue since yesterday, issue is still alive. i'm using react native 0.53.
This is only in android not in ios.
The workaround is to add multiline={true} but my problem is it doesn't help with my scenario 
i cannot have multiline enabled.

**Comment by robertohurtado** [comment]
I ran into a similar issue. I solved it by increasing the height of the textinput style.

**Comment by DannyvanderJagt** [comment]
@robertohurtado Thanks, somehow adding 10px to the height fixed it too for me on Android.
