### ISSUE TITLE
[Packager] Fails when package doesn't contain pure javascript

### ISSUE THREAD

**Issue by mosch** [facebook/react-native#1621]
The packager fails when the required package does not contain an javascript entry point with an exported *module.exports*. It looks like the feature is missing / other packagers support it. 

**Example:** [dfcreative/color-name](https://github.com/dfcreative/color-name) is a module that only provides a json file.

**Error:** "cannot find package main file for package"

**Comment by ide** [comment]
What version of React Native are you using?

**Comment by mosch** [comment]
0.5

**Comment by amasad** [comment]
This is fixed in master as we implement the full node resolution algorithm.
