### ISSUE TITLE
Upgrade from 0.47.2 to 0.48+

### ISSUE THREAD

**Issue by wholcman** [facebook/react-native#16212]
Current state:

```
node: v8.6.0
react-native-cli: 2.0.1
react-native: 0.47.2
npm: 4.6.1
```

Command: 

`react-native-git-upgrade 0.48.0`
`react-native run-ios`

An error appears during the bundling.
`JSON.parse` error from this file `jest-haste-map/build/worker.js`  `line 65`

Any feedback ?

![capture d ecran 2017-10-05 a 11 34 00](https://user-images.githubusercontent.com/1247755/31220579-23e88a06-a9c1-11e7-9c69-b458acce0692.png)

**Comment by cmdshepard** [comment]
Can you try deleting your `node_modules` folder and running `npm install` or `yarn install` again?
You can also try resetting the packager cache. From the root directory of your project, run `npm start -- --reset-cache`

**Comment by nhducit** [comment]
This error often happen when we upgrade to new react native version.  

- Solution:
Run this command and rebuild project
```
yarn nuclear ## clear cache, delete node_modules folder and reinstall node package

rm -rf ~/.rncache
rm -rf node_module
yarn nuclear
yarn start
yarn ios/yarn android

```

```
    "nuclear":
      "rm -rf $TMPDIR/react-* && watchman watch-del-all && rm -rf ios/build && rm -rf node_modules/ && yarn install",
```
