### ISSUE TITLE
FlatList Documentation Missing Props

### ISSUE THREAD

**Issue by moward** [facebook/react-native#16219]
### Is this a bug report?
Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?
Yes

### Environment
React Native 0.49 Documentation

### Steps to Reproduce
Go to [http://facebook.github.io/react-native/docs/flatlist.html](http://facebook.github.io/react-native/docs/flatlist.html).

### Expected Behavior
List all of FlatList's properties. See [http://facebook.github.io/react-native/releases/0.48/docs/flatlist.html](http://facebook.github.io/react-native/releases/0.48/docs/flatlist.html#flatlist)

### Actual Behavior
Under properties, only "numColumns" is shown.

**Comment by nhuthan** [comment]
+1
please update full document

**Comment by ravirajn22** [comment]
Nearly two months to update docs which were already present that too critical component?
