### ISSUE TITLE
Flatlist inverted props not working in huawei p9

### ISSUE THREAD

**Issue by rhenmark** [facebook/react-native#16213]
Flatlist render items cannot be seen when using inverted props only in huawei p9 phones. Any suggestions/help is very much appreciated.

**Comment by enahum** [comment]
I had to extend the FlatList and change the style to this
```
vertical: Platform.select({
        android: {
            scaleY: -1
        },
        ios: {
            transform: [{scaleY: -1}]
        }
    }),
```

is the only way is working on Huawei devices, the whole thing seems to be that Huawei devices do not support the `transform: [{scaleY: -1}]` style for some reason.

**Comment by itchingpixels** [comment]
This is actually a useful issue with a great suggestion!

We're having the same issue with a Huawei tablet, but 
```
android: {
            scaleY: -1
        },
```

Is actually also inverting the FlatList's row's content, nut just FlatList itself.

Also we're getting a deprecation warning.

Does anyone have any info regarding why this could be happening with some Huawei devices?

**Comment by lekenny** [comment]
same problem

**Comment by mindaugas-zaluba** [comment]
Same on Honor 8 (Huawei sub-brand)

**Comment by rhenmark** [comment]
When setting transform style in the View the Text inside it makes blurry.

**Comment by yury** [comment]
`{perspective: 1}` fixes transformation on Huawei

```js
const FLIP_Y_TRANSFORM = [{scaleY: -1}];
const FLIP_X_TRANSFORM = [{scaleX: -1}];

if (Platform.OS === 'android') {
  FLIP_Y_TRANSFORM.push({perspective: 1});
  FLIP_X_TRANSFORM.push({perspective: 1});
}
```

**Comment by enahum** [comment]
@yury can you confirm that fix actually works?

**Comment by yury** [comment]
Yep, we shipped that fix in production. RN v0.43.4

**Comment by henninghall** [comment]
@yury Looks good, where did you put that code?

**Comment by yury** [comment]
@henninghall 

it is in our `components/theme.js`

```js
const theme = {
   /* ... */
  flipX: { transform: FLIP_Y_TRANSFORM },
  flipY: { transform: FLIP_Y_TRANSFORM }
  /* ... */
}

export default theme;

```

Basic usage 

```js

import theme from '../theme';

class XComponent extends Component {
  render() {
     return <View style={ styles.wrapper }>/*...*/</View>
  }
}

const styles = StyleSheet.create({
  wrapper: {
    marginTop: 12,
    ...theme.flipY,
  },
});

```

**Comment by henninghall** [comment]
@yury's solution also inverts the FlatList's row's content, not just FlatList itself (discussed earlier)

**Comment by yury** [comment]
@henninghall yep, if you want just flip listview, you should apply this transform on list and on row. That’s the trick.

**Comment by sondremare** [comment]
@facebook-github-bot reopen
