### ISSUE TITLE
Receiving "undefined" for values when adding "useNativeDriver" alongside "createAnimatedComponent"

### ISSUE THREAD

**Issue by IljaDaderko** [facebook/react-native#16218]
### Is this a bug report?
Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS:  macOS Sierra 10.12.6
  Node:  8.6.0
  Yarn:  1.1.0
  npm:  5.5.0
  Watchman:  4.9.0
  Xcode:  Xcode 9.0 Build version 9A235
  Android Studio:  Not Found

Packages: (wanted => installed)
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: https://github.com/expo/react-native/archive/sdk-21.0.2.tar.gz => 0.48.4

Target Platform: iOS 11

### Steps to Reproduce

1) Create component that takes in children and passes its props onto children, while also making itself an Animatable component.

_Animate.js_
```
import React, { Component } from "react";
import PropTypes from "prop-types";
import { Animated } from "react-native";

class AnimateWrapper extends Component {
  // -- prop validation ----------------------------------------------------- //
  static propTypes = {
    children: PropTypes.node.isRequired
  };

  // -- render -------------------------------------------------------------- //
  render() {
    const { children, ...props } = this.props;
    return React.cloneElement(children, { ...props });
  }
}

const Animate = Animated.createAnimatedComponent(AnimateWrapper);

export default Animate;
```

2) Use this component in a scene and pass it animated values i.e.

_Scene.js_
```
import React, { Component } from "react";
import { Animated, Easing } from "react-native";
import Logo from "../components/Logo";

class Scene extends Component {
  // -- state --------------------------------------------------------------- //
  state = {
    logoAnim: new Animated.Value(1)
  };

  // -- methods ------------------------------------------------------------- //
  componentDidMount() {
    Animated.timing(this.state.logoAnim, {
      duration: 2000,
      toValue: 0,
      delay: 1000,
      easing: Easing.easeOut
    }).start();
  }

  // -- render -------------------------------------------------------------- //
  render() {
    return (
      <Animate
        animatedOpacity={this.state.logoAnim.interpolate({
          inputRange: [0, 1],
          outputRange: [0, 1]
        })}
      >
        <Logo />
      </Animate>
    );
  }
}

export default Scene;
```

Now your `<Logo />` or any other component receives `animatedOpacity` prop that you can use in its styles as value for opacity. This works perfectly fine at this point.

3) Add `useNativeDriver: true` to your animated function, so

```
Animated.timing(this.state.logoAnim, {
      duration: 2000,
      toValue: 0,
      delay: 1000,
      easing: Easing.easeOut,
      useNativeDriver: true
    }).start();
```

This now makes `animatedOpacity` undefined when used inside `<Logo />`

### Expected Behavior

`animatedOpacity` should still be defined as it was before adding `useNativeDriver: true`

### Actual Behavior

`animatedOpacity` is now undefined and can't be used.

### Reproducible Demo

Demo available here: https://snack.expo.io/BJ-y9nX3W
It shows working case initially, i.e. you will see text fade away. After this uncomment `useNativeDriver: true` animation becomes broken, text doesn't go away.

**Comment by saraht129** [comment]
I'm seeing the same issue here.

    `Animated.timing(this.state.fill,{ toValue: windowWidth * newProps.progress, duration: 1000, useNativeDriver: true,},).start();`

    <AnimatedBar width={C.windowWidth} height={5} fill={this.state.fill} color={this.props.color} mutedColor={this.props.mutedColor} />

const AnimatedBar: () => Component<IProgressBarProps, State> = Animated.createAnimatedComponent(ProgressBar);

`this.props.fill` of the `ProgressBar` will become `undefined`.
