### ISSUE TITLE
"react-native run-ios --configuration Release" - does not run in Release mode, but Debug instead 

### ISSUE THREAD

**Issue by GeoffreyPlitt** [facebook/react-native#16227]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes.

### Environment

```
$ react-native info
Scanning 819 folders for symlinks in /Users/giro/stardust-app/node_modules (11ms)

Environment:
  OS:  macOS Sierra 10.12.6
  Node:  6.5.0
  Yarn:  0.24.6
  npm:  3.10.3
  Watchman:  4.7.0
  Xcode:  Xcode 9.0 Build version 9A235
  Android Studio:  Not Found

Packages: (wanted => installed)
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: 0.48.0 => 0.48.0
```

### Steps to Reproduce

Run the command in the title of this issue.

### Expected Behavior

App runs in Release mode.

### Actual Behavior

App runs in Debug mode-- shake menu, etc.

### Reproducible Demo

Any skeleton RN app.

**Comment by ItsNoHax** [comment]
react-native run-ios --variant=release

**Comment by GeoffreyPlitt** [comment]
Thanks!
