### ISSUE TITLE
[0.49.1] TextInput > onSubmitEditing prop broken on Android when blurOnSubmit={false}

### ISSUE THREAD

**Issue by joncursi** [facebook/react-native#16224]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS:  macOS Sierra 10.12.6
  Node:  8.6.0
  Yarn:  1.1.0
  npm:  5.4.2
  Watchman:  4.9.0
  Xcode:  Xcode 9.0 Build version 9A235
  Android Studio:  2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: 0.49.1 => 0.49.1

  Target Platform: Android

### Steps to Reproduce

```js
import { TextInput } from 'react-native';

<TextInput
  ...
  blurOnSubmit={false}
  onSubmitEditing={() => {alert('I never get called')}}
  ..
/>
```

The alert never gets called when the user presses "Done" / "Next" / "Return" on the keyboard.

**Comment by 8of** [comment]
Probably the same as #16038

**Comment by joncursi** [comment]
Ah, I guess so. This was advertised as fixed in the 0.49.1 release notes and it's not yet fixed for Android.

https://github.com/facebook/react-native/commit/b06672e6cf7eee1f94e535aef2c49d8f6d7e8e16

I can confirm that iOS works though.

**Comment by 8of** [comment]
@joncursi So apparently fix present in master.
I'd like to advocate for including the fix to one of the closest minor updates.
I need to find specific commit in master that fixed the issue. I tried, but failed.
Any ideas how to find one?

**Comment by joncursi** [comment]
@8of I couldn't find it myself, either. But I'm with you - I would personally push to have this updated before the next major release. This, among the other android TextInput issues, are the difference between me shipping now and shipping in November

**Comment by eeynard** [comment]
Hi guys ! Here is the fix [4d54b48](https://github.com/facebook/react-native/commit/4d54b48167c99d0f3a8917e7637ffe3304c6bed6#diff-a1e6ca3a6b1647be95d97e7890bcc11c) I would love to see it in a minor release too. Otherwise, I will have to use v0.50.0-rc.0 because this bug is critical for my app.

**Comment by nitish24p** [comment]
@eeynard I am on RN 0.49.3, and am facing the same issue, did you find a solution to the problem

**Comment by eeynard** [comment]
Hey, not really, I had to upgrade RN. Sorry ! I think you should be fine with RN 0.50+
