### ISSUE TITLE
How to get data out of webview in react naitve ?

### ISSUE THREAD

**Issue by dotienthang** [facebook/react-native#16220]
### Is this a bug report?

(write your answer here)

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.)

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by chirag04** [comment]
@facebook-github-bot stack-overflow
