### ISSUE TITLE
.flowconfig in 0.49.1 has a bug which prevents using flow

### ISSUE THREAD

**Issue by alinz** [facebook/react-native#16225]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS:  macOS Sierra 10.12.6
  Node:  8.0.0
  Yarn:  1.1.0
  npm:  5.0.3
  Watchman:  4.9.0
  Xcode:  Xcode 9.0 Build version 9A235
  Android Studio:  2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: 0.49.1 => 0.49.1

### Steps to Reproduce

checking the newly created project using flow 0.53.0 throws an error

1. yarn add flow-bin@0.53.0
2. run `./node_modules/.bin/flow`

### Expected Behavior

Showing no errors

I think one of `suppress_comment` in `.flowconfig` has a bug and unfortunately there is no simple way to debug it since it is regex and on top of that you need to escape it and it becomes full of nonsense. Is there any tools that we can use to do the conversion back and forth?

### Actual Behavior

```bash
Error: node_modules/react-native/Libraries/Lists/ListView/ListViewDataSource.js:21
       v----------------------------------------------------------------------------
 21:   /* $FlowFixMe(>=0.53.0 site=react_native_fb) This comment suppresses an error
 22:    * found when Flow v0.53 was deployed. To see the error delete this comment
 23:    * and run Flow. */
        -----------------^ Error suppressing comment. Unused suppression

Error: node_modules/react-native/Libraries/Lists/ListView/ListViewDataSource.js:25
       v----------------------------------------------------------------------------
 25:   /* $FlowFixMe(>=0.53.0 site=react_native_fb) This comment suppresses an error
 26:    * found when Flow v0.53 was deployed. To see the error delete this comment
 27:    * and run Flow. */
        -----------------^ Error suppressing comment. Unused suppression
```

**Comment by GertjanReynaert** [comment]
[This](https://github.com/facebook/react-native/commit/11963d824d42cf94caed7212e55e0452e5a537ea) is the required fix, but it's on master instead of on the 0.49 release

**Comment by tychota** [comment]
I also reported this in #16235. I will close my issue as this one is older.

# How to fix

- Cherry-pick 11963d8 to 0.49 branch
- Release 0.49.2

**Comment by tychota** [comment]
cc @ide

**Comment by alinz** [comment]
Do we have to remove the comment? I don't think that's the right approach. I thought there is a bug in regex which need to be fixed.

**Comment by ide** [comment]
Thanks for the heads up, will cherry pick and release 0.49.2 later tonight.

**Comment by ide** [comment]
Cherry-picked that commit into 0.49-stable and pushed 0.49.2 to CircleCI. If CI succeeds, it will publish 0.49.2 to npm. CircleCI build is here: https://circleci.com/gh/facebook/react-native/22180.

**Comment by tychota** [comment]
Thank you James.

**Comment by nihgwu** [comment]
@ide when will you release 0.50.0-rc.0?

**Comment by ide** [comment]
Not sure, @grabbou is doing that release and there might be CI issues. (also please try to keep the conversation on topic)
