### ISSUE TITLE
Unknown Flag Options: CLI recommends --stacktrace, --info, or --debug flags but non work

### ISSUE THREAD

**Issue by geirman** [facebook/react-native#16234]
### Is this a bug report?

BUG: running `react-native run-android` failed and the CLI recommeds...

```bash
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```
but either I'm passing the options incorrectly or they're no longer valid. 

If I'm passing them incorrectly, then the cli output should probably be updated to clarify how to use and/or link to the docs.

If these flags are no longer valid, the cli output should be updated to something more helpful. 

### Environment

  Environment:
  OS:  macOS Sierra 10.12.6
  Node:  8.2.1
  Yarn:  0.27.5
  npm:  5.3.0
  Watchman:  4.7.0
  Xcode:  Xcode 9.0 Build version 9A235
  Android Studio:  Not Found

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: 0.49.1 => 0.49.1

### Steps to Reproduce

1. in the cli, run `react-native run-android --stacktrace`

### Expected Behavior
expected more info to troubleshoot the concern

### Actual Behavior

error: unknown option `--stacktrace'

![image](https://user-images.githubusercontent.com/1640318/31274266-83521ba2-aa92-11e7-888e-bb36a82e7eef.png)

**Comment by 8of** [comment]
`--stacktrace` should be added as gradle parameters.
Easy way to add them is via Android Studio settings.
Here is where to find gradle params in macOS:
Android Studio > Preferences > Build, Execution, Deployment > Compiler

Search for Command-line Options item and put `--stacktrace` there, then save & rebuild.

**Comment by geirman** [comment]
Thx, I'd have had no idea. I'd be happy to submit a pr to make these clarifications, but need more guidance. 

Where (in the code) do I make this change? 

What would be better verbiage, including info and debug flags as well?

**Comment by geirman** [comment]
Btw, I don't think I have Android studio installed

**Comment by 8of** [comment]
One of the reasons for command `react-native run-android` to fail.

**Comment by geirman** [comment]
I still think we need to submit clarification around this. Again, I'd be happy to do the work if someone would offer some guidance as to what to change where.

**Comment by geirman** [comment]
Bummer stalebot!
