### ISSUE TITLE
[0.49.1] Warning:Native component for "AndroidCheckBox" does not exist

### ISSUE THREAD

**Issue by kidmysoul** [facebook/react-native#16230]
### Is this a bug report?

(write your answer here)

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

yes

### Environment

Environment:
  OS:  macOS Sierra 10.12.6
  Node:  7.4.0
  Yarn:  Not Found
  npm:  4.3.0
  Watchman:  4.7.0
  Xcode:  Xcode 9.0 Build version 9A235
  Android Studio:  2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: 0.49.1 => 0.49.1

### Steps to Reproduce

(Write your steps here:)

1.import {  CheckBox } from 'react-native';
2.`<CheckBox value={this.state.isChecked} onValueChange={this.toggle.bind(this)}/>`
3.run-ios(this problem only happend in ios )

<img width="450" alt="2017-10-06 11 43 12" src="https://user-images.githubusercontent.com/15664045/31261919-5a9fa30a-aa92-11e7-9a0d-dc018be6186f.png">

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by sunilshenoy** [comment]
The release notes for 0.49 mention Checkbox under section Android. Checkbox looks like an android only component as of now.

https://github.com/facebook/react-native/releases/tag/v0.49.0

**Comment by kidmysoul** [comment]
@sunilshenoy 

Thank you.I didn't notice it. I think they should name it as "CheckboxAndroid".

**Comment by janicduplessis** [comment]
It should now render an UnimplementedView on Android so it will crash with a clear error message.

**Comment by James2516** [comment]
> It should now render an UnimplementedView on Android so it will crash with a clear error message.
Unimplemented on Android? Thought it's only implemented on Android?
