### ISSUE TITLE
Cannot establish secure connection

### ISSUE THREAD

**Issue by stokesbga** [facebook/react-native#16239]
On simulator running any version, I am getting error "Safari cannot open page because it could not establish a secure connection to the server." 

Virtually any https website yields this message. There are no errors/stack trace I can paste here.
I have tried: 

- resetting the device
- xcrun simctl erase all
- rebooting mac
- info.plist > allow arbitrary loads

Anyone running into this issue?

**Comment by 8of** [comment]
Check your date and time.

**Comment by stokesbga** [comment]
I agree it is not a RN issue, but I have asked on apple dev boards and no one has posted solution there either. Are you referring to date and time for the simulator or mac? Both appear correct.

**Comment by 8of** [comment]
What about timezone?

**Comment by stokesbga** [comment]
No dice, timezone is also correct.

**Comment by stokesbga** [comment]
...this is why vk will always be better than facebook

**Comment by andresfcamacho** [comment]
I'm getting this too, for localhost. Like @stokesbga  I've added:
```
    <key>NSAppTransportSecurity</key>
    <dict>
        <key>NSAllowsArbitraryLoads</key>
        <true/>
    </dict>
  </dict>
```
in my plist just to see if that would address it, but I get the same error.

**Comment by madisonscott** [comment]
Did anyone ever figure out this issue?

**Comment by ryan4888** [comment]
+1 also having this issue

**Comment by stokesbga** [comment]
I am so sorry for not updating this. I found Avast's "web shield" was causing the issue. To disable it, open Avast, then preferences > web shield > disable. You can just enable it again when you're not using the simulator. I have no idea how it just randomly got turned on, because this issue just started happening out of no where.

**Comment by teppix** [comment]
@stokesbga thanks! It was the same here, but with AVG web shield.

**Comment by singhraman4282** [comment]
going to avast>preferences>websheild>disable solved it for me
