### ISSUE TITLE
[Xcode] 7 beta - keyboard shortcuts no longer working

### ISSUE THREAD

**Issue by sjmueller** [facebook/react-native#1624]
On Xcode 7 beta, none of the Keyboard shortcuts (⌘+R, ⌘+D etc) are responding anymore.  I stepped through [RCTKeyCommands](https://github.com/facebook/react-native/blob/a5212c8180de124bc5fefab90005e3ee1d01d97a/React/Base/RCTKeyCommands.m), and [RCT_handleKeyCommand](https://github.com/facebook/react-native/blob/a5212c8180de124bc5fefab90005e3ee1d01d97a/React/Base/RCTKeyCommands.m#L73) does not get invoked.  The same behavior is observed even if targeting iOS 8.3 instead of 9.0.  It's somewhat difficult to isolate the problem, because Xcode 7 beta simulator support is [quite limited](http://adcdownload.apple.com/WWDC_2015/Xcode_7_beta/Xcode_7_beta_Release_Notes.pdf):

> Xcode 7.0 beta does not support iOS 8.4 and earlier simulator runtimes. (20699475)

A temporary workaround is to invoke the debugger menu with ctrl+⌘+Z, which is the built-in shortcut for shake.  It does require an extra mouse click for reload, which definitely slows down dev workflow.

It's worth mentioning that iOS9 has added `UIViewController.addKeyCommand(_: UIKeyCommand)` according to the [UIKit diff](https://developer.apple.com/library/prerelease/ios/releasenotes/General/iOS90APIDiffs/modules/UIKit.html).  Perhaps we can use this to get away from the current (albeit necessary) hacks?

**Comment by nrako** [comment]
I'm seeing the same issues, however when I have a red screen (i.e chrome not running for remote debugging) ESC and ⌘+R are handled correctly.

**Comment by nicklockwood** [comment]
`[UIViewController addKeyCommand:]` doesn't seem to help us, unfortunately, but I've devised a new, even more diabolical hack. Should be ready to ship soon.

**Comment by mnylen** [comment]
@nicklockwood, anything on this?

**Comment by nicklockwood** [comment]
It should be fixed. Is it not working for you?

**Comment by nicklockwood** [comment]
Closing, as the fix for this has already landed AFAIK. Feel free to re-open if it's still an issue.

**Comment by mnylen** [comment]
@nicklockwood It's working in 0.7.0-rc2. Thanks. Just wondered because this issue was still open. :)
