### ISSUE TITLE
How to prevent re-rendering of FlatList

### ISSUE THREAD

**Issue by pgwzzz** [facebook/react-native#16240]
Hello.

I'm implementing chatting with FlatList.

Every time there is a new chat message detected, I do the following.

`let newItem = {...};   // read a new chat message from server`
`let nextFlatListData = this.state.flatListData.slice(0);    // clone the chat list`
`nextFlatListData.push(newItem);    // add the new chat to the list`
`this.setState({flatListData: nextFlatListData});    // update FlatList`

It seems that it re-renders every row.

I just need the row for newItem is rendered and the others are NOT re-rendered.

Thank you very much.

**Comment by PatNeedham** [comment]
@pgwzzz can you share the `renderItem` prop you're using for your Flatlist? Including a `key` property as part of all the objects in the array you use for the FlatList (or a `keyExtractor` prop) is necessary to prevent re-renders.

**Comment by DragonRaider5** [comment]
Also you could try using a `PureComponent` or implement an own shouldComponentUpdate for your items. Your old components will be passed the same props again (if your old messages don't change), so they won't rerender if you use a `PureComponent`.
