### ISSUE TITLE
 On the real iPhone 7 Plus is not Full Screen

### ISSUE THREAD

**Issue by gHashTag** [facebook/react-native#16252]
Why in the simulator application Full Screen in iPhone 7 Plus and on the real iPhone 7 Plus is not Full Screen Where is the error?

```
react: 16.0.0-beta.5,
react-native: 0.49.1
```

Real Device

![img_6029](https://user-images.githubusercontent.com/6774813/31318946-46f33eac-ac63-11e7-9dc2-f6968eddf446.PNG)

Simulator

![simulator screen shot 8 2017 19 47 59](https://user-images.githubusercontent.com/6774813/31318948-55db7cc2-ac63-11e7-9d95-4e07750ff06b.png)

**Comment by nhducit** [comment]
Can you provide reproduce git hub repository?

**Comment by gHashTag** [comment]
Create project in 0.47.0 and working.
Maybe there was a bug in the version 0.49.1
