### ISSUE TITLE
Sharing on iOS 11 leads to duplicated content on "Copy & Paste"

### ISSUE THREAD

**Issue by jnbt** [facebook/react-native#16258]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

    Environment:
      OS:  macOS Sierra 10.12.6
      Node:  7.7.1
      Yarn:  0.27.5
      npm:  4.1.2
      Watchman:  4.7.0
      Xcode:  Xcode 9.0 Build version 9A235
      Android Studio:  2.3 AI-162.4069837

    Packages: (wanted => installed)
      react: 16.0.0-alpha.12 => 16.0.0-alpha.12
      react-native: ^0.48.4 => 0.48.4

### Steps to Reproduce

1. Install iOS 11 
2. Create a vanilla React Native app
    1. Install Create React Native App: `npm install -g create-react-native-app`
    2. Create a new app: `create-react-native-app AwesomeProject`
    3. Launch packager: `cd AwesomeProject && npm start`
3. Add some UI and trigger a share action:

    ```
    Share.share({message: "The message", title: "The title", url: "http://facebook.github.io"}) 
    ```

3. Choose "Copy" from the UIActivityViewController
4. Open the "Notes" app and paste the clipboard

### Expected Behavior

The URL should not be duplicated

### Actual Behavior

The URL is duplicated when the clipboard is pasted

Screenshot:

![img_2462](https://user-images.githubusercontent.com/678542/31346056-2067761c-ad18-11e7-88da-b3744bfffc7a.PNG)

Video capture: https://www.youtube.com/watch?v=i7BuwwNHYqg

### Reproducible Demo

Snack: https://snack.expo.io/r1KP-GYhW

### Insights

From my findings this is a bug of `UIActivityViewController` in iOS 11:

* https://stackoverflow.com/questions/46424313/uiactivityviewcontroller-duplicate-url-in-ios-11
* https://stackoverflow.com/questions/46526609/uiactivityviewcontroller-copy-copies-item-twice-on-ios-11
* https://www.reddit.com/r/getnarwhal/comments/6ufqr8/url_duplicated_when_sharing_it_via_copy_on_iphone/

Changing the implementation in `RCTActionSheetManager.m` slightly seems to solve this issue:

Replace [`[items addObject:URL];`](https://github.com/facebook/react-native/blob/0c5b3901781f145d77dc627fddb54bc88fd8afab/Libraries/ActionSheetIOS/RCTActionSheetManager.m#L149) with `[items addObject:URL.absoluteString];`

solves the issue. For me sharing to other apps (e.g. Facebook) still works. Another option would be to add iOS version checks here or to wait for Apple to fix this problem (might only take some years).

I'm more than happy to provide this little change as a PR.

**Comment by ethanneff** [comment]
Go to the App Store and share an app via copy. You will see it's a iOS bug.

**Comment by jnbt** [comment]
@ethanneff I totally agree. 

Sadly users won't get this and blame the app itself. Therefor I was asking if this project is willing to accept a workaround für iOS 11?

**Comment by jayasme** [comment]
It seems only happened in Apple's apps such as SMS and Note

**Comment by janicduplessis** [comment]
If the workaround works and doesn't break any other use cases I think this is fine. Just make sure iOS still detects the URL and it is clickable.

Feel free to open a PR and document the fix since it is a bit of a workaround.

**Comment by dlowder-salesforce** [comment]
Sorry the commit mentioned above is for #16528 ....
