### ISSUE TITLE
[DatePickerIOS and PickerIOS] are unusably slow in simulator.

### ISSUE THREAD

**Issue by hansonkd** [facebook/react-native#1625]
Using the code from:

https://facebook.github.io/react-native/docs/datepickerios.html#content

or 

https://facebook.github.io/react-native/docs/pickerios.html#content

or anything creates selectors that are unusably slow. It hangs when selecting an element in the most basic of examples. Its not just slow, but freezes the application until the pick is done. Is there additional configuration that is needed? 

I took a short video here:
http://i.imgur.com/EY10U0X.gifv

This happens on all my apps with react-native 0.5.0, even if I start a fresh project. However, deploying it to device or using React Native Playground, like so: https://rnplay.org/apps/7bfF6g, doesn't exhibit this behavior. I have checked and slow animations are turned off.

This was in the console:

```
2015-06-14 19:45:30.611 [warn][tid:com.facebook.React.JavaScript] "InteractionManager: interaction handle not cleared within 2000 ms.
createInteractionHandle@http://localhost:8081/index.ios.bundle:14755:28
onChange@http://localhost:8081/index.ios.bundle:14650:69
extractEvents@http://localhost:8081/index.ios.bundle:18024:61
extractEvents@http://localhost:8081/index.ios.bundle:12489:59
handleTopLevel@http://localhost:8081/index.ios.bundle:20222:46
_receiveRootNodeIDEvent@http://localhost:8081/index.ios.bundle:20091:43
receiveTouches@http://localhost:8081/index.ios.bundle:20175:54
jsCall@http://localhost:8081/index.ios.bundle:7496:34
_callFunction@http://localhost:8081/index.ios.bundle:7759:21
http://localhost:8081/index.ios.bundle:7786:37
forEach@[native code]
http://localhost:8081/index.ios.bundle:7780:22
perform@http://localhost:8081/index.ios.bundle:6295:24
batchedUpdates@http://localhost:8081/index.ios.bundle:14140:26
batchedUpdates@http://localhost:8081/index.ios.bundle:4827:34
http://localhost:8081/index.ios.bundle:7779:34
applyWithErrorReporter@http://localhost:8081/index.ios.bundle:7531:21
guardReturn@http://localhost:8081/index.ios.bundle:7553:27
processBatch@http://localhost:8081/index.ios.bundle:7778:23
[native code]
global code"
```

**Comment by brentvatne** [comment]
@hansonkd - I'm not seeing this in the simulator on my laptop, what kind of machine are you using? I don't see how this would be React Native specific, it seems more like either a simulator issue or slow hardware. Try this out with just a plain UIDatePicker, without React Native and let me know if you still have the issue. If you're not familiar enough with iOS to do this, check out [this tutorial](http://www.makemegeek.com/uidatepicker-example-ios/) - you can download the source and run it.

**Comment by hansonkd** [comment]
@brentvatne Hmm. Yes it appears to be happening on native object-c. I am on a maxed out new 17" macbook pro, so my only guess is that it is El Capitan that is the problem.  I will close this issue.

**Comment by brentvatne** [comment]
hansonkd - ah, makes sense, hard to say what could be going on with the early developer release of El Capitan :smile:
