### ISSUE TITLE
react-native starting the application

### ISSUE THREAD

**Issue by hayait599** [facebook/react-native#16254]
I installed all the requirements :
1.android studio
2.java jdl 8 and 9 
3.paython 2
4.node.js 6
5.npm 3
6.set the android home and java home variables
but I keep seeing this error 

-> failed to notify project evaluation listener
->java/xml/bind/JAXBException

**Comment by 8of** [comment]
Assuming you want to run app on android.

What about:
- react-native-cli ?

Also you need to install specific SDKs inside android Studio:
- Android SDK
- Android SDK Platform
- Performance (Intel ® HAXM)
- Android Virtual Device

Please confirm you installed all of the above and restarted computer (just in case)?
