### ISSUE TITLE
[DOCS] Links not working (tiny.cc)

### ISSUE THREAD

**Issue by gusgard** [facebook/react-native#16255]
### Is this a bug report?

Yes, in docs.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Steps to Reproduce

https://github.com/facebook/react-native/blob/master/Libraries/Animated/src/Easing.js#L168

### Reproducible Demo

http://tiny.cc/elastic_b_1 (bounciness = 1, default)
http://tiny.cc/elastic_b_3 (bounciness = 3)

Since the example (http://easings.net/#easeInElastic) is clear, I think we should delete the links.

**Comment by hramos** [comment]
Sounds good. I'd approve a PR.

**Comment by gusgard** [comment]
Done 👍
