### ISSUE TITLE
Long image filenames result in assembleRelease crash

### ISSUE THREAD

**Issue by joachimroeleveld** [facebook/react-native#16263]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

1. `react-native -v`: 0.45.1
2. `node -v`: v8.2.1
3. `npm -v`: 5.3.0

- Target Platform: Android
- Development Operating System: macOS

- Build tools: 
compileSdkVersion 23
buildToolsVersion '25.0.0'

### Steps to Reproduce

1. Create a file in a deep folder (e.g. `/shared/components/Component/components/AnotherComponent/components/AnotherComponent/components/AnotherComponent/img/image.png`)
2. Require that file
3. Run `assembleRelease`

### Expected Behavior

Successful assembly

### Actual Behavior

Assembly fails when processing the file:

```
.../app/android/app/build/intermediates/res/merged/release/drawable-mdpi/shared_components_component_components_anothercomponent_components_anothercomponent_components_anothercomponent_img_image.png: error: Invalid filename.  Unable to add.

:app:processReleaseResources FAILED

FAILURE: Build failed with an exception.
```

It's probably the long filename that cannot be handled by Java. When I undeepen the structure, the problem disappears. If a hash of the path would be used as a filename, this problem would not exist.

### Reproducible Demo

https://github.com/joachimroeleveld/rn-issue-15509

Steps to reproduce: 
1) clone repo
2) `npm install`
3) run `./android/assembleRelease`

**Comment by rpavlovs** [comment]
Same issue:
```
.../mobile_node_modules_reactnative_libraries_customcomponents_navigationexperimental_assets_backicon.png
Invalid filename. Unable to add.
```

**Comment by vovanmozg** [comment]
The names of assets files converting at the getAndroidResourceIdentifier() method.
https://github.com/facebook/react-native/blob/164591218f5fab7d386e057e0d51b9c1fe30b0a9/local-cli/bundle/assetPathUtils.js#L58

I suggest to modify getAndroidResourceIdentifier() method by drastically change filenames with using md5

```
function getAndroidResourceIdentifier(asset: PackagerAsset) {
  var folderPath = getBasePath(asset);
  return 'a' + md5(folderPath + '/' + asset.name).toLowerCase();
}

```

**Comment by joachimroeleveld** [comment]
This should really not be closed as this is still a problem and it will affect more people in the future.

**Comment by dante8300** [comment]
Hi this is the future and i confirm this is still an issue...

**Comment by mlazari** [comment]
Related Android bug: https://issuetracker.google.com/issues/36953084 It looks like the resulting drawable file name should be no longer than 100 characters.

**Comment by Salakar** [comment]
👋 hey all, thanks for the report and additional Android issue tracker details.

I'm going to close this issue as it's out of our control, but let's track this over on the [Known Issues](https://github.com/facebook/react-native-website/issues/564) list instead.

Feel free to continue the conversation though if needed and update on the status of the Android issue tracker should anything change.

Thank you
