### ISSUE TITLE
Layout issues in Android ?

### ISSUE THREAD

**Issue by deadcoder0904** [facebook/react-native#16265]
Checkout the issues in Android. `zIndex` doesn't work properly. One layout renders over the other in Android. IOS looks fine.

# Android

<img src="https://user-images.githubusercontent.com/16436270/31361350-9cf190b6-ad70-11e7-9dd7-da0767240f29.png" alt="android" width="350" height="568" />

# IOS

<img src="https://user-images.githubusercontent.com/16436270/31361411-d9def27a-ad70-11e7-8064-6a9bcee27bf7.png" alt="ios" width="350" height="568" />

IOS layout is proper. The android layout is cut. Also, applying `zIndex` didn't work. The source code is provided [here](https://github.com/deadcoder0904/react-native-redux-calculator)

**Comment by DragonRaider5** [comment]
Try out the elevation prop for android. It provides shadow and also adds a logical 'height' to your components, see the material design guidelines. Additional information: https://facebook.github.io/react-native/docs/viewstyleproptypes.html#elevation

PS.: Providing extra info about the platform would have helped (-> contribution guidelines), to know wether or not elevation effects you (-> Android 5.0+)

**Comment by deadcoder0904** [comment]
> PS.: Providing extra info about the platform would have helped (-> contribution guidelines), to know wether or not elevation effects you (-> Android 5.0+)

Naah, I read the guidelines but none of that is related to the problem.

I'll try elevation

**Comment by deadcoder0904** [comment]
Elevation didn't work

The problem is the result appears above everything. Checkout the `yellow` background below

<img src="https://user-images.githubusercontent.com/16436270/31382418-3be04258-add5-11e7-95ee-09ffb541f332.png" alt="android" width="350" height="568" />

In IOS it looks alright. Now IDK if its bcz of the screen size or its actually below.

I want 1 element to appear over other. Like we do using `zIndex` but `zIndex` didn't work

**Comment by DragonRaider5** [comment]
Oh actually it's pretty easy. The problem is, that android doesn't support `overflow: visible`. I guess your buttons are children of the dark background - in iOS, they get fully shown, because it defaults to `overflow: visible` whereas under Android they don't, as it's `overflow: hidden` due to the native view rendering on Android. See http://facebook.github.io/react-native/releases/0.49/docs/layout-props.html#overflow

**Comment by iremlopsum** [comment]
It might be because you have a border on the wrapper element. You can't overflow and element that has a border on Android.

**Comment by deadcoder0904** [comment]
@DragonRaider5 so what is the solution ?

@iremlopsum I have no border on wrapper element

& if u have any solution, plz tell me. Source Code is [here](https://github.com/deadcoder0904/react-native-redux-calculator)

**Comment by deadcoder0904** [comment]
& ur right @DragonRaider5 buttons are children of dark background. Idk how u guyz get it without looking at the code 🤔 but its cool eh

**Comment by DragonRaider5** [comment]
Because I encountered similar problems when I first used RN ;) btw. you have to check in your android and ios folders too, otherwise I cant build ^^

**Comment by deadcoder0904** [comment]
Nah it uses Expo.

U just install & run `yarn start` or `npm start`

**Comment by DragonRaider5** [comment]
You could try positioning your first line of control elements absolute (all views are per default `position: relative` in RN), or something similar.

**Comment by DragonRaider5** [comment]
Oh my bad, I tried `react-native run android` haha

**Comment by deadcoder0904** [comment]
> all views are per default position: relative in RN

True, but `position: absolute` doesn't work. I've been doing that long time.

**Comment by DragonRaider5** [comment]
It does, but it always position relative to it's first parent container, as he'll always be `position: relative` - that's the point :/

**Comment by deadcoder0904** [comment]
Now I totally lost it. Can u explain it clearly or just tell me the code ?

**Comment by DragonRaider5** [comment]
I'd probably get the position of your Controls component in its wrapping view [onLayout](http://facebook.github.io/react-native/releases/0.49/docs/view.html#onlayout), make your first line (of the controls) an additional component, put it into your root component with `position: absolute` and set the `top` style based on the y position of your Controls component (you could make your Root component stateful and let it save the data you get in the onLayout callback into its state).

It's not the cleanest solution, but it'll work.

**Comment by DragonRaider5** [comment]
Something like that
```
class Root extends React.Component {
  state = {
    top: 0
  }

  onLayout = ({ nativeEvent: { layout: { y } } }) => this.setState({ top: y })

  render() {
    return (
      <View>
        <Controls onLayout={this.onLayout} />
        <ControlsFirstLineOverlay style={{
          position: 'absolute',
          top: this.state.top
        }} />
      </View>
    )
  }
}
```

In your Controls component, you'll also have to pass on the onLayout to your wrapping View. Also you'll have to give it a paddingTop in order to not make the ControlsFirstLineOverly overlap your other buttons.

**Comment by deadcoder0904** [comment]
Nah I just added [1 more commit] (https://github.com/deadcoder0904/react-native-redux-calculator/commit/6cf07efbd97f982ff953c09f026897a230e36742) regarding ur workaround.

Plz check it out. I hope I did it right. But it doesn't work.

**Comment by DragonRaider5** [comment]
Yeah, that's because you left your first line in your Controls component - that causes it to
a.) still get limited by the `overflow: hidden` as it can't extend over the edge of your wrapping View
b.) as your wrapping View is `position: relative` by default your first line will position relative to it (`position: absolute` always positions absolute to the next parent object with a set position, which is the case for all Views in RN) - so `top: 0` would align it to the top of your container. But because you pass the absolute (in a real absolute sense) y position of your Controls container in, it will be exactly at double the distance of your upper screen edge as your Controls container.

**Comment by deadcoder0904** [comment]
@DragonRaider5 I'm a beginner & I'm absolutely not getting it. Although I read it 10 times now 😂 
Can u send a PR please❓ I think that might take little time for u.

**Comment by DragonRaider5** [comment]
I see that somebody already submitted a PR - everything okay now?

**Comment by deadcoder0904** [comment]
Yep, thanks to u as well, issue solved 😄 
U & him both did the same thing using `onLayout`
I guess I'll close this one now
Thank u again 👍

**Comment by deadcoder0904** [comment]
Hey @DragonRaider5 there is just 1 issue now

Black background shows up for half a second, & then it goes & then it looks like the Original App

Now can it be removed ❓ 

I tried displaying Dummy View like http://cmichel.io/how-to-get-the-size-of-a-react-native-view-dynamically/ but it doesn't work
