### ISSUE TITLE
Make master to pass tests on CI

### ISSUE THREAD

**Issue by grabbou** [facebook/react-native#16273]
Currently CI is broken due to flow failing. After investigating that matter for a bit, it turns out issues are coming from `metro-bundler` package.

It doesn't happen on `0.49-stable` and has been a result of either `flow` or `metro-bundler` being updated.

I am opening this issue to keep a better track of the status of this issue. Further more, I would also suggest to change the order of tests being run on the CI. I believe `flow` and `eslint` should run last, after `unit` tests. They often break or error temporarily and I've seen many PRs landing to the repo that break those two test suites. That, unfortunately, makes `unit` tests to never run and I am afraid some might ignore them for time being.

For reference: This issue is currently blocking release of 0.50-stable branch. 

CC: @cpojer @hramos

**Comment by fernandopasik** [comment]
`metro-bundler` is using an [old ](https://github.com/facebook/metro-bundler/blob/master/package.json#L25)version of flow.

**Comment by fernandopasik** [comment]
Ok, it was [updated](https://github.com/facebook/metro-bundler/commit/87cfc05ea67e19c367e24e644915b49024ce3f2a) but after the last release.

They still haven't updated the package.json though

**Comment by grabbou** [comment]
Good catch! I thought it got included in the last release. I have asked for updated release already and waiting for the update.

**Comment by grabbou** [comment]
Okay, I've figured out where the issue was. I left details on the problem on `metro-bundler` repo [here](https://github.com/facebook/metro-bundler/commit/87cfc05ea67e19c367e24e644915b49024ce3f2a#commitcomment-24884835). 

I am fixing the 0.50-stable branch as answered in that comment and should hit `npm` in a second.

There are two things that one has to do in order to fix master:
- update metro to `v0.20.0` (released today, there's already open issue about keeping these two in sync)
- perform steps as advised in the diff linked above

**Comment by grabbou** [comment]
Unfortunately, mockFS is broken on Node lower than 8 which breaks our tests. Unfortunately, I left the office. Will keep working on that issue tomorrow.

**Comment by grabbou** [comment]
Pull requests #16301 and #16302 fix all failures and make master green again. As a proof, 0.50-stable is green and about to hit `npm` soon.

**Comment by grabbou** [comment]
Tests are green now, except failing Travis, but that wasn't in scope for this issue. I am going to work on migrating Travis to make CI green.
