### ISSUE TITLE
Change made for react native breaks all webpack Moment.js users

### ISSUE THREAD

**Issue by maggiepint** [facebook/react-native#16274]
Hi,

I'm Maggie from the moment core team. We merged + released a change that react native users requested to rename all dynamic requires because they apparently do not work with this library: https://github.com/moment/moment/pull/4207

The net result is that all webpack2 users are now broken: https://github.com/moment/moment/issues/4216

We're working on getting a small sample app that replicates pushed to a branch. In the interim, can you give me any insights on whether there is a different acceptable solution than the one here? I'm happy to ship any kind of bug fix release that makes sense.

Thanks,
Maggie

**Comment by maggiepint** [comment]
Example: https://github.com/mj1856/moment-webpack-test

**Comment by hramos** [comment]
Hey @maggiepint, I believe this is being discussed already in https://github.com/facebook/metro-bundler/issues/65.
