### ISSUE TITLE
[Android] onSubmitEditing not happening when blurOnSubmit is false

### ISSUE THREAD

**Issue by davidhellsing** [facebook/react-native#16289]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

    OS:  macOS Sierra 10.12.3
    Node:  8.6.0
    Yarn:  0.27.5
    npm:  5.3.0
    Watchman:  4.7.0
    Xcode:  Xcode 8.3.2 Build version 8E2002
    Android Studio:  2.3 AI-162.4069837

### Packages: (wanted => installed)

    react: 16.0.0-alpha.12 => 16.0.0-alpha.12
    react-native: 0.48.4 => 0.48.4

### Target Platform
   
    Android

    compileSdkVersion 23
    buildToolsVersion "25.0.0"
    minSdkVersion 16
    targetSdkVersion 23

### Steps to Reproduce

(Write your steps here:)

1. Make the TextInput maintain focus when pressing the submit button on Android
2. Add `onSubmitEditing={this.submit}` and `blurOnSubmit={false}`
3. The `this.submit` method never gets called

### Expected Behavior

The submit method should be called

### Actual Behavior

The submit method does not call. If I remove the `blurOnSubmit={false}` or set it to true, the method calls as expected.

### Code example

```
class Input extends Component {
  submit() {
    console.log('Submitting');
  }
  render() {
    return (
      <TextInput
        editable={true}
        keyboardType='phone-pad'
        onSubmitEditing={this.submit}
        blurOnSubmit={false}
        returnKeyType="next"
      />
    )
  }
}
```

**Comment by kelset** [comment]
How have you defined the submit method? It simply looks like you haven't "linked" it properly.
Try to change `onSubmitEditing={this.submit}` to `onSubmitEditing={() => {console.log("I'm getting called")}}` and you should see it working regularly.

That said, I also suggest you change the title to something more meaningful

**Comment by davidhellsing** [comment]
@kelset Sorry, I was too quick! Yes, the method does call when removing the `blurOnSubmit` property (or setting it to false) so the linking is not the problem.

I noticed this after upgrading React & React Native, and also some target SDKs.

**Comment by mmazzarolo** [comment]
I'm experiencing the same issue on Android, both `onEndEditing` and `onSubmitEditing` do not get called when `blurOnSubmit` is set to `false`.  

I'm on `"react-native": "0.48.1"`.

**Comment by Kosai106** [comment]
Can confirm this is also the case on `0.49.3`

**Comment by eeynard** [comment]
Hey ! Looks like it duplicates #16224
