### ISSUE TITLE
[Packager] Requiring momentjs locale fails

### ISSUE THREAD

**Issue by alvaromb** [facebook/react-native#1629]
I'm trying to use a different locale for Moment.js, and I keep receiving the same error. This is the code:

```javascript
var moment = moment();
moment.locale('es');
```

And I'm receiving this error in the Chrome Dev Tools console:

```
Error: Requiring unknown module "./locale/es". If you are sure the module is there, try restarting the packager.
 stack: 
  Object.ErrorUtils.applyWithGuard  index.ios.bundle:880
  require                           index.ios.bundle:195
  loadLocale                        index.ios.bundle:42796
  chooseLocale                      index.ios.bundle:42774
  locale_locales__getLocale         index.ios.bundle:42867
  Moment.locale                     index.ios.bundle:44506
  eval                              eval at evaluate …:1
 URL: undefined
 line: undefined
```

It doesn't seems a Moment.js error though.

**Comment by cyprusglobe** [comment]
just do ```npm install moment```
then
```var moment = require('moment');```

**Comment by alvaromb** [comment]
That’s what I did. I can use moment and I’ve been using it with react-native, but I cannot change the moment ``locale``.

**Comment by brentvatne** [comment]
@alvaromb - just a quick thought from browsing the moment docs, what about:

```
var moment = require('moment');
var esLocale = require('moment/locale/es');
moment.locale('es', esLocale);
```

**Comment by brentvatne** [comment]
Also, see this: https://github.com/moment/moment/issues/2007#issuecomment-99811475

If it doesn't fix the problem, let me know and I'll reopen

**Comment by alvaromb** [comment]
Super @brentvatne!! I haven't found that option in the docs. Many thanks.

**Comment by ranyefet** [comment]
@brentvatne loading the locale directly i.e ```require('moment/locale/es');``` works.
I'm trying to set the locale dynamically, AKA, I get the locale from user device and then load the specific locale.

```
const deviceLocale = React.NativeModules.RNI18n.locale;
// fails
require('moment/locale/' + deviceLocale); 
```

Is there other way to solve it besides:
```
switch deviceLocale:
case 'es':
  require('moment/locale/es');
case 'he':
  require('moment/locale/he');
```

**Comment by anderson916** [comment]
It works. Thanks.

**Comment by JBerendes** [comment]
This is a bit old now but I'd like to show you my how I've done it. I'm using react-native-i18n.

- Create your language string files. (example ru.js)
- Do the a locale check at the top of each language string file. 
`import I18n from 'react-native-i18n';
if(I18n.locale === 'ru') {
  require('moment/locale/ru');
}

export default {
  HelloReact: "Здравствуйте, React
}`

**Comment by bourgois** [comment]
Same question here: I would like to load dynamically depending on user/device but I dan't want to write a long serie of 'case'. @ranyefet solution still seem to be the only valid one... @JBerendes seems equivalent but even more work...
Anyone with a better solution? @brentvatne ?

**Comment by jdmunro** [comment]
I also have this issue: for some reason it doesn't seem to be possible to do a dynamic include based on the locale.
