### ISSUE TITLE
Padding is not overriding paddingTop, paddingLeft, paddingHorizontal, etc...

### ISSUE THREAD

**Issue by facuescobar** [facebook/react-native#16309]
### Is this a bug report?
Yes, **padding** attribute is not overriding individual padding attributes like **paddingTop**, **paddingLeft**, **paddingVertical**, etc...

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes 
### Environment

  Environment:
  OS:  macOS Sierra 10.12.6
  Node:  7.9.0
  Yarn:  0.23.2
  npm:  4.5.0
  Watchman:  4.7.0
  Xcode:  Xcode 8.2.1 Build version 8C1002
  Android Studio:  2.3 AI-162.3871768

  Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: 0.49.3 => 0.49.3

### Steps to Reproduce

1. Create default styles for a wrapper component and assign padding values
```
const ScreenStyles = {
  paddingTop: 0,
  paddingLeft: 10,
  paddingRight: 10,
  paddingBottom: 10,
};
```
You also can try with *paddingHorizontal* and *paddingVertical*

2. Declare new styles for custom screen, extending from *ScreenStyles*:
```
const CustomScreenStyles = StyleSheet.create({
  screen: {
    ...ScreenStyles,
    padding: 50,
  }
});
```

### Expected Behavior
Extended **padding** attribute must override individual values like *paddingTop*, *paddingLeft*, *paddingVertical*, etc...

### Actual Behavior
**padding** attribute is not overriding individual padding attributes like **paddingTop**, **paddingLeft**, **paddingVertical**, etc...

### Reproducible Demo

https://snack.expo.io/rkPlT3s3-

**Comment by facuescobar** [comment]
This issue has not been fixed, here's a new demo

https://snack.expo.io/SkUA0PWff

**Comment by vdpdev** [comment]
This issue is still reproducible
"version": "0.54.0"

**Comment by a6051529** [comment]
I also face the same problem， 
`listItem: {
    padding: 15,
    paddingLeft: 0
}
`
`paddingLeft ` is not working.

**Comment by devth** [comment]
This is still an issue. Makes it hard to control layout when multiple styles are being merged (incorrectly).
