### ISSUE TITLE
Circle 2.0 setup requires further work

### ISSUE THREAD

**Issue by grabbou** [facebook/react-native#16306]
### Is this a bug report?

Bug

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Not related, issue is about CI.

### Steps to Reproduce

Checkout stable branch of master and try releasing.

### Expected Behavior

CircleCI builds `android`, `js` and `website` in parallel. After all tasks have finished, `deploy_website` and `deploy_npm` jobs are run.

### Actual Behavior

CircleCI builds `android`, `js` and `website` not as jobs, but as separate workflows. That results in those 3 being unaware of each other. That makes it hard to run something as a result of successful test. A good example is missing `npm publish`. I tried adding it and couldn't find the right place. There's no hook to wait for all workflows to finish with success. You can't run it on `deploy_website` job because android tests can fail in the meantime (that did happen to me during my tests).

Also, as in this example (https://circleci.com/gh/facebook/react-native/22571) website is not deployed despite all conditions being met.

### How can this be fixed

We can add `deploy_npm` job after `deploy_website` and mark it as the one that requires manual approval. That means person releasing new version (me in particular) would have to double check that all tests are green and hit the deploy.

Alternatively, `npm publish` permissions has to be given to someone who will be running this command locally.

**Comment by hramos** [comment]
A website deploy should only happen on stable and master branches. If the step is being skipped on those branches, it's because the `test-website` step is failing. The deploy should happen regardless of failures on other unrelated steps (such as test-node-*, test-android).

Is the deploy-website step being skipped when test-website is successful? Or is there something we need to fix in test-website?

**Comment by grabbou** [comment]
CC: @ide and @hramos who were involved in Circle 2.0 migration. Right now, I have reverted this change and built on 1.0

**Comment by grabbou** [comment]
> The deploy should happen regardless of failures on other unrelated steps (such as test-node-*, test-android).

Yes, @hramos, you are right! That's indeed same behaviour that we had in 1.x and so, I am not reporting an issue in regards to it.

My issue is related to fact that `./scripts/publish-npm.js` has been removed and there's no way for me to release a successful build now.

**Comment by grabbou** [comment]
There's no immediate need to work on it as I've restored to 1.0 on 0.50-stable. This will be used only for purposes of releasing new version.

I will use this branch to roll out a fix and create a pipeline that satisfies our open source requirements. We will investigate further workflow / jobs setup to see what can be done in order to improve it.

**Comment by ramubhai** [comment]
NPM still has not received 0.5 released as of now. 
Need to publish it manually till the fix is worked out?

**Comment by grabbou** [comment]
I can see it's on npm. What's the way you are checking?

**Comment by ramubhai** [comment]
Rechecked. I see following on NPM site in relevant section.

react-native-bot react-native-bot published 3 days ago
0.49.3 is the latest of 216 releases
github.com/facebook/react-native
BSD-3-Clause

**Comment by grabbou** [comment]
That only shows the "latest" version. Please use semver.npmjs.com to check
:)

**Comment by hramos** [comment]
The npm deploy step is missing from the Circle CI 2.0 config as Mike said earlier. Will open a PR to add it back.

**Comment by hramos** [comment]
Opened #16340, but Circle is not yet running a build for it.

**Comment by hramos** [comment]
#16350 landed. We now wait for approval when running builds on master and stable releases. This should allow you to selectively deploy to npm when a new release is cut.

**Comment by grabbou** [comment]
I believe this can be closed now.
