### ISSUE TITLE
Babel Plugin `transform-runtime` causes app to crash

### ISSUE THREAD

**Issue by faerbena** [facebook/react-native#16335]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS:  macOS Sierra 10.12.6
  Node:  8.0.0
  Yarn:  Not Found
  npm:  5.4.2
  Watchman:  4.9.0
  Xcode:  Xcode 9.0 Build version 9A235
  Android Studio:  2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: 0.49.3 => 0.49.3

### Steps to Reproduce

1. Create a new project: `react-native init AwesomeProject`
2. `cd AwesomeProject`
3. `npm install --save-dev babel-preset-env babel-plugin-transform-runtime`
4. Change content of `.babelrc` to
```
{
  "presets": ["react-native", "env"],
  "plugins": ["transform-runtime"]
}
```
5. Try to run the app on a device.

### Expected Behavior

The app starts up normally without errors.

### Actual Behavior

![bildschirmfoto 2017-10-12 um 16 29 35](https://user-images.githubusercontent.com/15094703/31501473-a7bdd166-af6a-11e7-82bd-7a16a89ba7f5.png)

The actual error message may depend on the actual content of the app. I googled some of them and it seems to me like these are babel related errors. The problem is resolved as soon as I remove `"plugins": ["transform-runtime"]` from the `.babelrc`file.

### Reproducible Demo

Just follow the steps described above.

I am new to React Native and looking forward to find answers to this problem!

**Comment by willhlaw** [comment]
I just discovered the same thing. Still investigating a fix.
