### ISSUE TITLE
React native screens rendering problem?

### ISSUE THREAD

**Issue by RagamAnekaGlobal** [facebook/react-native#16334]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes
### Environment

Environment:
  OS:  macOS Sierra 10.12.6
  Node:  6.11.3
  Yarn:  1.1.0
  npm:  5.3.0
  Watchman:  4.9.0
  Xcode:  Xcode 9.0 Build version 9A235
  Android Studio:  2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: 0.49.1 => 0.49.1

### Steps to Reproduce

(Write your steps here:)

1.Access the application
2. Going to splash screen
3. Go to other menu via react-navigation (Using TabNavigator and StackNavigator).

### Expected Behavior

The menu and content of the apps accessed normally in IOS devices.

(Write what you thought would happen.)

### Actual Behavior

The screens become blur like the content is not loaded properly.

(Write what happened. Add screenshots!)
<img width="366" alt="screen shot 2017-10-12 at 8 10 54 pm" src="https://user-images.githubusercontent.com/32739276/31498142-697ff264-af8b-11e7-9c01-ec63b9a0da7a.png">
Hi, i am new in react native. This only happens in ios application (never happen in android). All screens and contents of apps become strange, but is is intermittent some times is become normally again after access the other screen and sometimes become crash again. Please Help. It is the problem with my codes or there is something wrong? Thank you.

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by hramos** [comment]
Thanks for opening the issue! It does not appear like a community member will be able to reliably reproduce this issue. This may be for several reasons; perhaps it affects a particular app but a minimal repro has not been provided, or the issue may be sporadic. As it happens, we need a concrete set of steps that can demonstrably reproduce the issue as this will allow your fellow community members to validate a fix. We'll close the issue for now, but feel free to submit a new issue once you're able to reliably reproduce the issue locally. Thanks for your understanding!
