### ISSUE TITLE
TextInput Alignment does not work on iOS 11

### ISSUE THREAD

**Issue by n-kumari** [facebook/react-native#16341]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes
### Environment

  Environment:
    OS:  macOS Sierra 10.12.6
    Node:  7.7.2
    Yarn:  Not Found
    npm:  5.4.2
    Watchman:  4.7.0
    Xcode:  Xcode 9.0 Build version 9A235
    Android Studio:  Not Found

  Packages: (wanted => installed)
    react-native: 0.49.3 => 0.49.3
    react: 16.0.0-alpha.12 => 16.0.0-alpha.12

### Steps to Reproduce

1. Create  a `TextInput` and few buttons. Set the alignment dynamically as you press buttons using `textAlign`.

``` 
<View style ={{marginTop: 42}}>
            <Button
            onPress={ this.setStateLeft }
            title="Left"
            color="#841584"
            />
            <Button
            onPress={ this.setStateCenter }
            title="Center"
            color="#841584"
            />
            <Button
            onPress={ this.setStateRight }
            title="Right"
            color="#841584"
            />
            <TextInput
                style={{height: 40, borderColor: 'gray', borderWidth: 1, marginTop: 112, textAlign: this.state.alignText}}
                onChangeText={(text) => this.setState({text})}
                value={this.state.text}
            />
</View>
```

2. Press the buttons

### Expected Behavior

The alignment should work on iOS devices, irrespective of versions.

### Actual Behavior

The alignment works as expected on iOS 10, but not on iOS 11 as seen below. The simulator on the left is iOS 11 and on right is iOS 10.

![align_demo](https://user-images.githubusercontent.com/30132665/31510623-098c3e5e-af53-11e7-84a1-854d7811561b.gif)

### Reproducible Demo

https://snack.expo.io/rkX3DXphb

**Comment by gusgard** [comment]
Could you try `this.state = { text: 'Alignment', alignText: 'right'};`  in the constructor ?

**Comment by n-kumari** [comment]
In the constructor we are just setting the initial state. All that `this.state = { text: 'Alignment', alignText: 'right'};` does is setting the initial state to the right. It makes no difference to the issue.

**Comment by gusgard** [comment]
The `TextInput` is re-rendered when the value changes, not when the style. In your example if you focus on the TextInput or change to this `value={this.state.alignText}`, it works.

**Comment by n-kumari** [comment]
@gusgard Thank you for your input. I understand that the `TextInput` is re-rendered when the value changes, not when the style.

The issue I am talking about here is that re-rendering is not required on iOS 10. In the gif above, as shown, with the same code, it works as expected on iOS 10 (right simulator) but not on iOS 11 (left simulator).

**Comment by fmanns** [comment]
This appears to be an IOS 11 bug. I was able to reproduce it in a simple standalone app.

<img width="500" src="https://user-images.githubusercontent.com/1413388/31799413-f20e6d00-b507-11e7-8064-d61d9fabcb09.gif">

```swift
class ViewController: UIViewController {

    @IBOutlet weak var alignmentSelector: UISegmentedControl!
    @IBOutlet weak var alignedTextField: UITextField!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        alignmentSelector.addTarget(self, action: #selector(alignmentSelected), for: .valueChanged)
    }
    
    @objc func alignmentSelected() {
        switch alignmentSelector.selectedSegmentIndex {
        case 0:
            alignedTextField.textAlignment = .left
        case 1:
            alignedTextField.textAlignment = .center
        default:
            alignedTextField.textAlignment = .right
        }
    }
    
}
```
