### ISSUE TITLE
AsyncStorage multiSet doesn't resolve if called on Android with more/less than 2 elements in key-value array

### ISSUE THREAD

**Issue by lovenm** [facebook/react-native#16355]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

I ran into this on react-native 0.47.1, but based on the source code, the bug seems to be in the latest version as well. Also reproduced it with Snack SDK v21.0.0, which has react-native 0.48.4.

### Steps to Reproduce

AsyncStorage's multiSet method takes in an array of arrays that should contain 2 elements. If one of the inner arrays does not contain exactly 2 elements, the callback won't be called and the promise won't get resolved or rejected on Android.

So calling it like this will break it:
```
AsyncStorage.multiSet([['key', 'value', 'something']], callback);
```
I believe this is caused by this line:
https://github.com/facebook/react-native/blob/1e8f3b11027fe0a7514b4fc97d0798d3c64bc895/ReactAndroid/src/main/java/com/facebook/react/modules/storage/AsyncStorageModule.java#L177

Which makes the method return without ever calling the callback.

The same bug can also happen if the key or value in the array is null, due to these two lines:
https://github.com/facebook/react-native/blob/1e8f3b11027fe0a7514b4fc97d0798d3c64bc895/ReactAndroid/src/main/java/com/facebook/react/modules/storage/AsyncStorageModule.java#L181
https://github.com/facebook/react-native/blob/1e8f3b11027fe0a7514b4fc97d0798d3c64bc895/ReactAndroid/src/main/java/com/facebook/react/modules/storage/AsyncStorageModule.java#L185

### Expected Behavior

Callback is called with error and Promise rejected with error.

### Actual Behavior

Callback is not called and Promise is left hanging.

### Reproducible Demo

https://snack.expo.io/HJYsdV0nW
The callback in the example gets called on iOS, but not on Android.

**Comment by rochapablo** [comment]
@lovenm, how are you getting the data from AsyncStorage? Can you give an example?

[I'm struggling to get the data on Android (native code)](https://stackoverflow.com/questions/48151030/how-to-read-asyncstorage-on-android-correctly)

**Comment by lovenm** [comment]
@rochapablo Uh, first of all I've no idea how what you're asking is related to this bug report, so this is probably not the best place to find the answer to your question. 

I'm also not quite sure what you're asking, but the documentation of AsyncStorage has plenty of examples on how to retrieve data:
https://facebook.github.io/react-native/docs/asyncstorage.html

If that doesn't answer your questions, please check these channels for help:
https://facebook.github.io/react-native/docs/more-resources.html#where-react-native-people-hang-out
