### ISSUE TITLE
[Android]Release crash l.View.propTypes.style

### ISSUE THREAD

**Issue by cbjs** [facebook/react-native#16352]
debug is fine, crash while release.

logcat dump.
`
10-13 10:28:08.810  9145  9194 E AndroidRuntime: com.facebook.react.common.JavascriptException: undefined is not an object (evaluating 'l.View.propTypes.style'), stack:
10-13 10:28:08.810  9145  9194 E AndroidRuntime: <unknown>@1184:5578
10-13 10:28:08.810  9145  9194 E AndroidRuntime: i@2:565
10-13 10:28:08.810  9145  9194 E AndroidRuntime: n@2:348
10-13 10:28:08.810  9145  9194 E AndroidRuntime: t@2:210
10-13 10:28:08.810  9145  9194 E AndroidRuntime: <unknown>@1183:197
10-13 10:28:08.810  9145  9194 E AndroidRuntime: i@2:565
10-13 10:28:08.810  9145  9194 E AndroidRuntime: n@2:348
10-13 10:28:08.810  9145  9194 E AndroidRuntime: t@2:210
10-13 10:28:08.810  9145  9194 E AndroidRuntime: <unknown>@1182:113
10-13 10:28:08.810  9145  9194 E AndroidRuntime: i@2:565
10-13 10:28:08.810  9145  9194 E AndroidRuntime: n@2:348
10-13 10:28:08.810  9145  9194 E AndroidRuntime: t@2:210
10-13 10:28:08.810  9145  9194 E AndroidRuntime: <unknown>@1180:311
10-13 10:28:08.810  9145  9194 E AndroidRuntime: i@2:565
10-13 10:28:08.810  9145  9194 E AndroidRuntime: n@2:348
10-13 10:28:08.810  9145  9194 E AndroidRuntime: t@2:210
10-13 10:28:08.810  9145  9194 E AndroidRuntime: <unknown>@698:1008
10-13 10:28:08.810  9145  9194 E AndroidRuntime: i@2:565
10-13 10:28:08.810  9145  9194 E AndroidRuntime: n@2:348
10-13 10:28:08.810  9145  9194 E AndroidRuntime: t@2:210
10-13 10:28:08.810  9145  9194 E AndroidRuntime: <unknown>@309:403
10-13 10:28:08.810  9145  9194 E AndroidRuntime: i@2:565
10-13 10:28:08.810  9145  9194 E AndroidRuntime: n@2:348
10-13 10:28:08.810  9145  9194 E AndroidRuntime: t@2:210
10-13 10:28:08.810  9145  9194 E AndroidRuntime: <unknown>@12:44
10-13 10:28:08.810  9145  9194 E AndroidRuntime: i@2:565
10-13 10:28:08.810  9145  9194 E AndroidRuntime: n@2:278
10-13 10:28:08.810  9145  9194 E AndroidRuntime: t@2:210
10-13 10:28:08.810  9145  9194 E AndroidRuntime: global code@1260:9
10-13 10:28:08.810  9145  9194 E AndroidRuntime: 
10-13 10:28:08.810  9145  9194 E AndroidRuntime: 	at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:56)
10-13 10:28:08.810  9145  9194 E AndroidRuntime: 	at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:40)
10-13 10:28:08.810  9145  9194 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-13 10:28:08.810  9145  9194 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:363)
10-13 10:28:08.810  9145  9194 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
10-13 10:28:08.810  9145  9194 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
10-13 10:28:08.810  9145  9194 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:754)
10-13 10:28:08.810  9145  9194 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
10-13 10:28:08.810  9145  9194 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
10-13 10:28:08.810  9145  9194 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:160)
10-13 10:28:08.810  9145  9194 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
10-13 10:28:08.810  9145  9194 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)

`

**Comment by timxyz** [comment]
We've been banging our heads against this issue for a few days. Seems like the cause was View.propTypes only being accessible from dev mode, meaning it is undefined in release. The fix is to switch it with ViewPropTypes.

Quote from View.js:

```
// `propTypes` should not be accessed directly on View since this wrapper only
  // exists for DEV mode. However it's important for them to be declared.
  // If the object passed to `createClass` specifies `propTypes`, Flow will
  // create a static type from it.
  propTypes: ViewPropTypes,
```

**Comment by pongponglau** [comment]
I have the same problem in iOS 10 when running the app in release mode.

2017-10-21 22:52:35.287874+0800 hkustudport[286:15231] Unhandled JS Exception: undefined is not an object (evaluating 'l.View.propTypes.style')

May i ask if there is any solution?

Thanks

**Comment by rcorrie** [comment]
In order to solve this, make sure that your app nor any of your dependencies is using `View.propTypes`.

**Comment by michaelstokes** [comment]
Hello, is there any update for this? I'm having the same issue currently, I've resolved on the debug side by running `jscodeshift -t react-codemod/transforms/React-PropTypes-to-prop-types.js <path>`

https://github.com/mapbox/react-native-mapbox-gl/issues/832

But the app crashes in release mode

**Comment by indrawanadjie** [comment]
@timxyz Thank you.. Works for me 🙏
