### ISSUE TITLE
Push iOS not working anymore

### ISSUE THREAD

**Issue by Crash--** [facebook/react-native#16361]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?
Yes
### Environment
Environment:
  OS:  macOS Sierra 10.12.6
  Node:  7.6.0
  Yarn:  1.1.0
  npm:  4.1.2
  Watchman:  4.7.0
  Xcode:  Xcode 9.0 Build version 9A235
  Android Studio:  2.2 AI-145.3537739

Packages: (wanted => installed)
  react: ^16.0.0 => 16.0.0
  react-native: ~0.49.2 => 0.49.2

### Steps to Reproduce

(Write your steps here:)

1. Create a component with 
```jsx
 componentWillMount() {
    PushNotificationIOS.addEventListener('register', this._onRegistered);
    PushNotificationIOS.addEventListener('registrationError', this._onRegistrationError);
    PushNotificationIOS.addEventListener('notification', this._onRemoteNotification);
    PushNotificationIOS.addEventListener('localNotification', this._onLocalNotification);

    PushNotificationIOS.requestPermissions();
  }

  componentWillUnmount() {
    PushNotificationIOS.removeEventListener('register', this._onRegistered);
    PushNotificationIOS.removeEventListener('registrationError', this._onRegistrationError);
    PushNotificationIOS.removeEventListener('notification', this._onRemoteNotification);
    PushNotificationIOS.removeEventListener('localNotification', this._onLocalNotification);
  }
 _onRegistered(deviceToken) {
console.log('deviceToken', deviceToken);
}
_onRemoteNotification(notification){
console.log('notification', notification); 
}
```
2. Send a push notification to the token when the application is not launched (not even in background). The notification appears in the control center. GOOD
3. Launch the app, send a new notification. Nothing is display. `notification` listener is not called.

### Expected Behavior

3. Expect to have a console.log with the notification

###

I tried to put some breakpoint in native code. I can have a break on `didRegisterUserNotificationSettings`, `getDeliveredNotifications` and so on. But nothing on `didReceiveRemoteNotification`... 

I simulated a push notification with : 
```jsx
require('RCTDeviceEventEmitter').emit('localNotificationReceived', {
      aps: {
        alert: 'Sample local notification',
        badge: '+1',
        sound: 'default',
        category: 'REACT_NATIVE'
      },
    });
````

With that, the `notification` listener is well executed.

**Comment by gtchance** [comment]
@Crash-- Did you figure this out? I'm having problems with local notifications on iOS 11. They fire, but listeners are never notified.

**Comment by lucianomlima** [comment]
I can't get information from listeners too in iOS 11.

**Comment by juergengunz** [comment]
same for me
@lucianomlima @Crash-- did you find a solution?
