### ISSUE TITLE
[WebView] postMessage hangs iOS 10.3(14E8301) simulator

### ISSUE THREAD

**Issue by evasyuk** [facebook/react-native#16360]
### Is this a bug report?

postMessage to WebView hangs simulator

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

yes

### Environment

 Environment:
OS: macOS Sierra 10.12.1
Node: 7.2.1
Yarn: Not Found
npm: 5.4.2
Watchman: 4.8.0
Xcode: Xcode 8.3.3 Build version 8E3004b
Android Studio: Not Found

  Packages: (wanted => installed)
react: 16.0.0-alpha.12 => 16.0.0-alpha.12
react-native: 0.48.4 => 0.48.4

  Target Platform: iOS (10.3)

### Steps to Reproduce

# Steps to reproduce:
1. Create html with script

```
<script> 
 document.addEventListener("message", function(data) {
	var temp = data.data.split("::");

	if (temp[0] === "token") {
	    token = temp[1];
	    alert("token " + temp[1]);
	else {
	    alert("unexpected data: " + data.data);
	}
});
</script>
```

2. Create component as
```
import React, { Component } from 'react';
import {
    View, TouchableHighlight, Text, WebView
} from 'react-native'
import TimerMixin from 'react-timer-mixin'

var htmlFile = require('../../assets/temp.html');

const SEPARATOR = "::";

export default class MapScreen extends Component<{}> {
    constructor(props) {
        super(props);

        this.state = {
            id: this.props.id || "null",
            token: this.props.token || "TOKEN",
        };
    }

    render() {
        return (
            <View style={{height: '100%', width: '100%'}}>
                <WebView
                    ref={ webview => { this.webview = webview; }}
                    source={htmlFile}
                    style={{backgroundColor: '#000000'}}
                    // onLoadEnd={()=>this._helloWebView()}
                />
            </View>
        )
    }

    componentDidMount() {
        this._helloWebView();
    }

    componentWillUnmount() {
        TimerMixin.clearTimeout(this.timer);
    }

    _helloWebView() {
        console.log("_helloWebView called");
        this.sendData("token::" + (this.state.token || "null"), 5000);
    }

    sendData(data, timeout) {
        console.warn("sendData called [" + data + "][" + (timeout || 0) + "]");

        TimerMixin.setTimeout(() => {
            console.log("postMessage executed [" + data + "][" + timeout + "]");
            this.webview.postMessage(data);
        }, timeout || 0);
    }

}
```

### Expected Behavior

Alert is shown with provided token with no hang

(Write what you thought would happen.)

### Actual Behavior

Simulator does not responding and the process needs to be killed via ActivityMonitor 

![webview_ios_hang](https://user-images.githubusercontent.com/4641605/31551527-84f84174-b03d-11e7-9d3a-e02ef529169f.gif)

### Reproducible Demo

https://snack.expo.io/H1P4m802b

**Comment by evasyuk** [comment]
yes-template

**Comment by hramos** [comment]
Thanks for editing your post to make sure it uses the template as required by the contribution guidelines. Your issue is now open again.
