### ISSUE TITLE
[RCTBridge] Attempt to insert `nil` object into _scheduledCalls causes crash

### ISSUE THREAD

**Issue by paramaggarwal** [facebook/react-native#1636]
I saw the following crash yesterday. I can't think of how to reproduce it, but the fact that `_scheduledCalls[1]` is `nil` here is a red flag that some check is missing somewhere.

![screen shot 2015-06-15 at 11 16 50 pm](https://cloud.githubusercontent.com/assets/543981/8180618/c8638fc6-143c-11e5-8e75-664068c4c924.png)

I understand this is hard to reproduce, but a `nil` check before inserting into `_scheduledCalls` can help prevent a crash. I was using React 0.4.1.

**Comment by tadeuzagallo** [comment]
This has already been fixed, upgrading should solve it. Feel free to ping me if you see any similar issue :)
