### ISSUE TITLE
[CameraRoll] checkPermissions?

### ISSUE THREAD

**Issue by JonasJonny** [facebook/react-native#1638]
Hello.
Is there a way how to get permission status to access CameraRoll?
I tried https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/CameraRollView.ios.js but I don't know how to check if user allowed the permission or not.

It make sense to take a action if user don't approve the permission. Redirect him somewhere, etc...

Thank you for any help how to catch and handle the error bellow if the permission is not given or to add checkPermissions() to master.

![camerapermission](https://cloud.githubusercontent.com/assets/1771823/8182003/33289cfa-142b-11e5-83ef-00b1483e2a2e.png)

**Comment by nicklockwood** [comment]
There isn't currently an API to check this, but I agree it would make sense. I'll file a task to add one.

**Comment by JonasJonny** [comment]
Thank you @nicklockwood. It will be very useful.

**Comment by JonasJonny** [comment]
Is there any progress on this issue?

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/cameraroll-checkpermissions

**Comment by victorbadila** [comment]
+1 this needs to be reopened
