### ISSUE TITLE
[Packager] Requiring validate.js fails

### ISSUE THREAD

**Issue by mosch** [facebook/react-native#1640]
When requiring [validate.js](https://github.com/ansman/validate.js/), the packaging fails.

``
var validatejs = require('validate.js');
``

However, there is a workaround:

``
var validatejs = require('validate.js/validate');
``

**Comment by nicklockwood** [comment]
@amasad, any thoughts?

**Comment by ide** [comment]
@mosch I think this might have been fixed in master. What version of react are you using?

**Comment by mosch** [comment]
@ide tested at 0.5 and 0.6-rc1

**Comment by ide** [comment]
Hmm https://github.com/facebook/react-native/commit/856469a24b6f0b0998061c1244533b510aee3ddd is in 0.6-stable so this could be a bug.

**Comment by amasad** [comment]
Rewrote the resolver to implement the exact node resolution algorithm. This will work now.

And sorry for the delay, my attempt at email filtering by mentions failed me but I just discovered about the 'participating' tab in github notifications.

**Comment by mosch** [comment]
@amasad awesome, thank you!
