### ISSUE TITLE
TextInput padding not working on Android

### ISSUE THREAD

**Issue by gitlovenotwar** [facebook/react-native#16405]
### Is this a bug report?
Yes. On android, TextInput padding not working when its parent has display: none/flex to show/hide the TextInput. It works fine when the TextInput will be mounted/unmounted.

### Environment
 Environment:
   OS:  macOS Sierra 10.12.5
   Node:  6.11.1
   Yarn:  0.27.5
   npm:  5.3.0
  Watchman:  4.7.0
  Xcode:  Xcode 8.3.2 Build version 8E2002
  Android Studio:  2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: 0.49.3 => 0.49.3

### Steps to Reproduce
1. Parent Component of TextInput has display: 'none' when component mounted
2. Click to some button to show the parent component having display from 'none' to 'flex'

### Expected Behavior
Padding should work just the same on iOS, TextInput padding on iOS works always even parent is displayed or not(NOTE: not mounted/unmounted but using style display: 'none'/'flex')

### Actual Behavior
On Android, padding not working on TextInput

**Comment by provedotit** [comment]
This is still an issue on 0.53. The workaround is to use absolute positioning and a negative zIndex when you want to hide the input instead of display: none.

**Comment by zarincheg** [comment]
This is still a problem in 0.50. But if render TextInput by visibility condition it works fine.
```js
const field = !invisible ? <TextInput placeholder="Write here" /> : null;
return (<View style={invisible ? { display: 'none' } : { display: 'flex' }}>{field}</View>);
```
