### ISSUE TITLE
[ScollView/ListView] contentOffsets, contentInsets strange behavior

### ISSUE THREAD

**Issue by marcshilling** [facebook/react-native#1641]
I am trying to make a simple ListView which has a search bar header that is hidden behind the nav bar by default, but upon scrolling you can reveal it (a pretty standard iOS interaction). Has anyone had success with this? I am seeing some pretty strange behavior.

Here is my ListView setup. The list view is behind both a nav bar and a tab bar (hence the content insets):
```javascript
<ListView
   ref='listView'
   style={styles.listView}
   dataSource={this.state.dataSource}
   renderHeader={::this.renderHeader}
   renderRow={::this.renderRow}
   contentOffset={{x: 0, y: -20}}
   contentInset={{top: 64, bottom: 49}}
   automaticallyAdjustContentInsets={false}
/>
```

The "strange behavior" I mention is that the "contentOffset" prop (which I believe is how this should be accomplished) seems to have no effect upon this view first appearing. I can set that Y value to anything and the view looks the same when it is presented (the search bar is displayed at the top). However, if I change that Y value and save, the simulator live reloads and seems to adjust the offset properly.

**UPDATE:**
I've found a really dumb, hacky way of getting around this:

If in `componentDidMount` I do this:
```javascript
 setTimeout(() => {
   this.setState({      
      contentOffsetY: -20
   });
 }, 16);
```

And render ListView's `contentOffset` like so: 

```javascript
contentOffset={{x: 0, y: this.state.contentOffsetY}}
```
Then, the search bar is correctly hidden upon the view appearing.

Because of that ^, I'm lead to believe there HAS to be a bug here.

**Comment by jtremback** [comment]
Would it be possible to replicate this on https://rnplay.org?

**Comment by marcshilling** [comment]
@jtremback *SUPER* frustratingly, this seems to work just the way I'd expect (https://rnplay.org/apps/nWGxtw)

However, in my project, of course it does not work that way.

I've found a really dumb, hacky way of getting around this:

If in `componentDidMount` I do this:
```javascript
 setTimeout(() => {
   this.setState({      
      contentOffsetY: -20
   });
 }, 16);
```

And render ListView's `contentOffset` like so: 

```javascript
contentOffset={{x: 0, y: this.state.contentOffsetY}}
```
Then, the search bar is correctly hidden upon the view appearing.

There has to be a bug here.

**Comment by jtremback** [comment]
@marcshilling What version of react-native are you running?
@brentvatne What version of react-native is the simulator running?

**Comment by marcshilling** [comment]
@jtremback I'm on the master branch...0.6.0

**Comment by brentvatne** [comment]
@jtremback - that simulator is on 0.5.0 (see the header bar)

**Comment by PhilippKrone** [comment]
Is this related to my issue? https://github.com/facebook/react-native/issues/1779

**Comment by jaygarcia** [comment]
Seems like #2151 might be related.

**Comment by dubert** [comment]
:+1:

**Comment by aleclarson** [comment]
:+1:

**Comment by christopherdro** [comment]
Related #1779 or #2151.

@ide @brentvatne Can be closed. Solution provided in related issues.

**Comment by nguyenquangtrung** [comment]
a
