### ISSUE TITLE
Naming issues with special characters produces 'Unable to resolve module 'filepath'.

### ISSUE THREAD

**Issue by srseven** [facebook/react-native#16413]
Yes, this is a bug report.
We use Github Issues to report bugs.
I have read the contributing guidelines.

## Description

Naming an asset file (fonts, icons, etc) with special characters generates this error. To solve this I renamed those icons without special characters. Take a look into this as it is likely somebody else runs into this and is left to scratch his/her head into what's going wrong.

## Environment

1. OS: Windows 10
2. Node: 8.4.0
3. Yarn: 1.1.0
4. npm: 5.5.1
5. react-native: 0.48.1
6. react: 16.0.0-alpha.1

### Steps to Reproduce

1. Add a path to an asset (font, icon, etc) or any kind of a file with a special character in it to a react-native project (For example inside image tag with the path of the icon passed as a parameter of require() in source attribute.)

### Expected Behavior

The image, the font should load into the app.

### Actual Behavior

This [error](https://github.com/facebook/react-native/issues/11257) occurs.

**Comment by hramos** [comment]
Can you expand your repro steps? A basic example with a special character that causes the error to show up would be good.

**Comment by srseven** [comment]
## Steps To Reproduce

1. Name an asset file (font, icon) with a special character.
2. Put that path as the argument of a require() inside say Image component. For example:
   `<Image style={[styles.thumbnailStyle]} source={require('../../assets/icons/employer_home_green@1x.png')}/>`
