### ISSUE TITLE
VirtualizedList renders rows unnecessarily when scrolling past the render window's end limit

### ISSUE THREAD

**Issue by bdrobinson** [facebook/react-native#16415]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment
Environment:
  OS:  macOS Sierra 10.12.6
  Node:  8.5.0
  Yarn:  1.2.0
  npm:  5.4.2
  Watchman:  4.9.0
  Xcode:  Xcode 9.0 Build version 9A235
  Android Studio:  2.3 AI-162.4069837

Packages: (wanted => installed)
  react: ^16.0.0 => 16.0.0
  react-native: ^0.48.4 => 0.48.4

### Steps to Reproduce

1. Create a `VirtualizedList` (I've observed the behaviour on both `SectionList` and `FlatList`). Give it a large number (~1000) of rows that take a while to render, and a small window size to make the issue more noticeable (I used 5).
2. Implement `getItemLayout`. This will allow the user to scroll past the end of the render window.
3. Add a `console.log` to each row so you can see when it gets rendered.
4. Scroll down very quickly, so that you are scrolling faster than the cells can render.
5. The screen will be blank, and then eventually the required rows will appear.

### Expected Behavior
Suppose the initial render (before any scrolling took place) resulted in the first 30 rows being rendered. Then the user scrolls down very quickly to, say, row index 700.

Once the user has scrolled a significant distance past the end of the render window, the render method of each row in between the end of the current render window (row 31) and the user's current scroll position (row 700) should NOT be called (as the cells are not visible, even though they were briefly on-screen).

### Actual Behavior
If a user scrolls very quickly (let's say it's essentially instant) to row 700, every single row up to 700 gets rendered, even though the vast majority of those rows were never on screen for more than a split second. This means the user has to wait far longer than necessary for the rows they actually want to look at to appear. This is a big problem if each row is quite slow to render anyway.

Of course I don't mind if the rows in between 31-700 get rendered eventually, but surely priority should be given to rows at the current scroll position?

I've been having a look at the code for `VirtualizedList` and from what I can tell it looks as though it does try to cancel previously-scheduled row renders from the queue in favour of higher priority rows (see [here](https://github.com/facebook/react-native/blob/master/Libraries/Lists/VirtualizedList.js#L1114)), but it doesn't seem to work for this case.

### Reproducible Demo

https://snack.expo.io/H1KaiUzpW

This demo has a FlatList with 1000 rows. Each row has an artificial function to slow down the render of each row, to simulate conditions in our actual app where each row takes a while to render on old devices (and just to be clear – in our actual app we're not doing heavy CPU-bound calculations in the render function).

If you scroll down to the bottom of the list very quickly, you will see it takes a *long* time for the rows to appear. You might need to play around with the `blockThread` function to make each row render at a delay long enough to demonstrate the problem but not so long as to make each row take minutes to render.

Let me know if anything isn't clear. Thanks very much!

**Comment by sitompul** [comment]
have you tried to implement onEndReached method? Loading huge pile of data directly to flatlist will cause your apps to crash

**Comment by bdrobinson** [comment]
You mean I should gradually append data to my list as I scroll down, rather than all at once at the beginning? That's not the way `FlatList` is intended to be used is it? I thought the whole point of `FlatList` was that I could give it a huge lump of data and not have to worry about performance etc?

**Comment by sitompul** [comment]
Even if you already implemented  `onEndReached` method, the performance still a bit laggy. If you only develop on **IOS** and want to **load all the data at once** check this one, [react-native-tableview-simple](https://github.com/Purii/react-native-tableview-simple). I hope it helps.

But still, even the newest 0.49 FlatList still have some performance issue.

**Comment by bdrobinson** [comment]
Ah really? Thanks, that's helpful to know! I'm developing for both iOS and Android sadly, but yes I might have to look into more native list solutions like that for this component.

Out of interest, are the limitations of FlatList well documented?

**Comment by sitompul** [comment]
@bdrobinson No it's not. Your best bet is to try to search on the issues tab while entering 'FlatList' or 'FlatList Performance' as your query.

**Comment by bolan9999** [comment]
FlatList and SectionList is bad performance. Try this,please. may be it is a surprise for you

https://github.com/bolan9999/react-native-largelist

**Comment by damrem** [comment]
A simple comment to reopen the issue, that I encounter as well with `@0.52.0`.
