### ISSUE TITLE
Android: HTTP request not sent in release build

### ISSUE THREAD

**Issue by Palisand** [facebook/react-native#16420]
### Is this a bug report?

Yes... well maybe. This might be intended behavior.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes.

### Environment

Environment:
  OS:  macOS Sierra 10.12.6
  Node:  8.4.0
  Yarn:  1.0.1
  npm:  4.6.1
  Watchman:  4.9.0
  Xcode:  Xcode 9.0 Build version 9A235
  Android Studio:  2.3 AI-162.4069837

Packages: (wanted => installed)
  react: ^16.0.0-beta.5 => 16.0.0-beta.5
  react-native: 0.49.3 => 0.49.3

### Steps to Reproduce

1. Create an app that includes an http request to a local server.
2. Build for release.
3. Run app and observe that the request never makes it to the server.

### Expected Behavior

I didn't really know what to expect and now I suppose Android will prevent insecure requests from being sent. Is there a way to allow insecure requests in a release build?

### Actual Behavior

Failed http request.

### Reproducible Demo

NA

**Comment by khurramwaqar** [comment]
I had the same problem with RN 0.49, when i run this command gradlew assembleRelease then i had this error:

:app:bundleReleaseJsAndAssets
Scanning folders for symlinks in C:\Users\Khurram\HelloWorld\node_modules (47ms)
Sc
anning folders for symlinks in C:\Users\Khurram\HelloWorld\node_modules (53ms)
Loading dependency graph, done.
warning: the transform cache was reset.
bundle: start
bundle: finish
bundle: Writing bundle output to: C:\Users\Khurram\HelloWorld\android\app\build\int
ermediates\assets\release\index.android.bundle
bundle: Done writing bundle output
bundle: Copying 7 asset files
bundle: Done copying assets

FAILURE: Build failed with an exception.

What went wrong:
Unable to process incoming event 'ProgressComplete ' (ProgressCompleteEvent)

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

**Comment by cdlewis** [comment]
Are you making the request against localhost or 10.0.2.2?

**Comment by Palisand** [comment]
@khurramwaqar I am not experiencing a build failure.
@cdlewis I am making requests against my local ip, 192....
