### ISSUE TITLE
Trying to make signed apk but getting error of duplicacy

### ISSUE THREAD

**Issue by sunnynegi** [facebook/react-native#16428]

**Comment by sunnynegi** [comment]
Info added

**Comment by choo737** [comment]
I'm having the same issue.
```
:app:processReleaseResources
/Users/macbookpro/eciroad/android/app/build/intermediates/res/merged/release/drawable-mdpi-v4/images_banner.jpeg: error: Duplicate file.
/Users/macbookpro/eciroad/android/app/build/intermediates/res/merged/release/drawable-mdpi/images_banner.jpeg: Original is here. The version qualifier may be implied.
```

Steps I performed to package the released version

1. $ react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
2. $ cd android
3. $ ./gradlew assembleRelease

Tried
1. npm clean cache --force
2. ./gradlw clean

**Comment by choo737** [comment]
I deleted those original duplicate file manually from the drawable mdpi file and run ./gradlew assembleRelease again, the workaround worked.

**Comment by nikhilemmanuel** [comment]
i have this issue now, is there a proper fix for this? apart from the workaround. Would be of great help... 
 thanks.

**Comment by sujayjaju** [comment]
The issue is that the new version of react-native bundles the assets under /app/build/intermediates/res/merged/release instead of app/src/main/res

To resolve it, this is what I did
```
rm -rf android/app/src/main/res/drawable-*
```

Now bundle assets using this command:
```
react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/build/intermediates/res/merged/release/
```
Note the updated ```--assets-dest``` in the above command. Assembling the APK worked ok after that!
```
react-native run-android --variant=release
```

**Comment by locliem08** [comment]
it's work for me! thanks @sujayjaju

**Comment by hesokaslave** [comment]
I Confirm, it's working !
