### ISSUE TITLE
Application crashed after using ART library in Android Emulator

### ISSUE THREAD

**Issue by sintylapse** [facebook/react-native#16425]
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

yes

### Environment

```
Environment:
  OS:  windows 10
  Node:  6.11.3
  npm:  3.10.10
  Android Studio: 2.3.3

Packages: (wanted => installed)
  react-native: 0.49.3 => 0.49.3
  react: 16.0.0-beta.5 => 16.0.0-beta.5

Target Platform: Android Emulator - Nexus_5x_API_26_x86

```

### Steps to Reproduce

1) Create new project

```
react-native init NotAwesomeUselessProject
cd NotAwesomeUselessProject
```

2) Paste this code in App.js

```
import React from 'react'
import { ART, View } from 'react-native'

const { Surface, Group, Shape } = ART

export default class App extends React.Component {
    render(){
        return (
            <View>
                <Surface width={200} height={100}>
                    <Group x={0} y={0}>
                        <Shape
                            d={"M-68.9646319937036,-29.476762610114324A75,75,0,0,1,-49.345310456503256,-56.48044206582762L-20.635195356782273,-21.775874553905552A30,30,0,0,0,-27.086713440010442,-12.896121704557451Z"}
                            stroke={"#2ca02c"}
                            strokeWidth={3}
                        />
                    </Group>
                </Surface>
            </View>
        )
    }
}
```

3) Run project

```
react-native run-android
```

### Expected Behavior
I expect some graph to appear

### Actual Behavior

Application is crashed without throwing any error

![1](https://user-images.githubusercontent.com/12295016/31576576-420a7674-b106-11e7-8e0c-490c4a27178d.png)

### Reproducible Demo
https://snack.expo.io/r1u6yoJpW

**Comment by sintylapse** [comment]
Don't use Android Emulator

**Comment by chris-divvito** [comment]
... I am having this same issue, I was just curious as to whether there is a supported option for testing React Native for Android other than Android Emulator - I have the same issue but I see this has been closed with the solution to not use android emulator. Is something like tnuxeo a supported alternative?

**Comment by chris-divvito** [comment]
A note that I found I was able to resolve this issue by using software graphics emulation in the AVD properties

**Comment by sintylapse** [comment]
@chris-divvito yea, you right, it solves the issue. But it works very slow now. Did you have this problem too?

**Comment by chris-divvito** [comment]
It's hard to tell, my machine's pretty RAM poor so it was already kind of chuggy, but I'm not surprised that running the graphics in software would definitely be a big performance hit.
