### ISSUE TITLE
Webview.scalesPageToFit not working on Android

### ISSUE THREAD

**Issue by thomasobrien99** [facebook/react-native#16421]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS:  macOS Sierra 10.12.6
  Node:  6.11.0
  Yarn:  1.0.1
  npm:  4.6.1
  Watchman:  4.7.0
  Xcode:  Xcode 9.0 Build version 9A235
  Android Studio:  2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: 0.48.3 => 0.48.3

### Steps to Reproduce

1. Create a <WebView /> component ON ANDROID, with scalesPageToFit set to true, and a source of some website:
  ```
  <WebView scalesPageToFit source={{ https://github.com/facebook/react-native/issues/new" }} />
```
### Expected Behavior

The screen loads with the website filling the viewport.

### Actual Behavior

The screen load with the image extending beyond the viewport

![image](https://user-images.githubusercontent.com/13715890/31641278-6b212fce-b298-11e7-9684-cd44b8294eba.png)

**Comment by aditya-simplecrm** [comment]
solution?

**Comment by tianweicc** [comment]
Have you solved it

**Comment by PaitoAnderson** [comment]
While `scalesPageToFit` does work for me with GitHub.com on Android, other sites don't scale nicely at all. (Just like above)

I have submitted #17190 which fixes this problem for me.

**Comment by iDay** [comment]
https://github.com/yptech/react-native-yunpeng-webview
use this can fix it right now

**Comment by sabbyt54** [comment]
+1

**Comment by nixoz** [comment]
The bug is still here. Any updates?

**Comment by samdoj** [comment]
Yes, this is a serious issue.  The same site I'm trying to load in my WebView scales just fine in iOS.  Worse, I can't even horizontally scroll.  Please reopen.

**Comment by smitthakkar1** [comment]
@iDay  can you give an example using this library?

https://github.com/yptech/react-native-yunpeng-webview

**Comment by iDay** [comment]
@smitthakkar1
use it just like react-native's

**Comment by FRizzonelli** [comment]
@iDay Thanks man, works great! Maybe can you submit another PR with the fix to RN? Because #17195 was closed without merging :(

**Comment by lubomyr** [comment]
up,
a lot of version passed, but this patch https://github.com/tranvinhtruong/react-native/commit/01f02a596a2575b84dac1901703b6216c5e630c5 still not applied :(

**Comment by amit2908** [comment]
is this fixed yet?
