### ISSUE TITLE
undefined: measure for 'sub' react classes

### ISSUE THREAD

**Issue by jonslenkooyala** [facebook/react-native#1643]
When I abstract out a set of views into another React class, and then try to measure them, it fails. What syntax / design should I follow to let me measure such separate code?

http://pastebin.com/LWUj1EzX

If you set the "var crash = true" then it should show you that the 'custom' class "daviews" fails to have the 'measure' function on it for some reason. Whereas the 'inline' "myrootview" does have it.

**Comment by jonslenkooyala** [comment]
I guess it is because the 'custom' thing is not the markup returned from a render() call, but is an instance. So something I tried that works is to use a callback.

http://pastebin.com/11wYCE8A

It all seems sort of gross.

**Comment by ide** [comment]
Native view components have a prop called onLayout. For now the best way to measure composite components is to explicitly pass the prop down.

```js
class X extends Component {
  render() { return <View onLayout={this.props.onLayout} />; }
}
```

**Comment by jonslenkooyala** [comment]
Thanks for your note. I started with onLayout :-) but the onLayout callback doesn't get all the details, the x & y are often/always zero it seems to me vs. the ox,oy and px,py of measuring. 

If there's a way to get the actual screen pixel position of the Component, that's all I'm really trying to get, sorry I didn't explain my use case in the first place.

**Comment by ide** [comment]
onLayout returns the component's position relative to its parent. I don't think there's a way right now to get its global position without getting the layout of the entire component ancestry.

**Comment by jonslenkooyala** [comment]
With the grossness I mentioned above, I think maybe if I am lucky I am getting the values I want in the px,py arguments to the callback?

**Comment by sahrens** [comment]
Yeah, you have to call measure manually to get the global or "page"
position. This is because we don't currently have an efficient/reliable way
to provide events for this you can listen to (e.g. it would have to be
called on every scroll event iff nested in a scroll view, and what if that
ScrollView was nested in a scrollview? We'd have to re-measure every view
subscribing to measure events in every frame to decide to send an event or
not.).
