### ISSUE TITLE
[Android WebView] Youtube embed video flicker bug

### ISSUE THREAD

**Issue by onrige** [facebook/react-native#16445]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS:  macOS Sierra 10.12.6
  Node:  6.9.5
  Yarn:  1.1.0
  npm:  5.5.1
  Watchman:  4.9.0
  Xcode:  Xcode 9.0 Build version 9A235
  Android Studio:  Not Found

Packages: (wanted => installed)
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: https://github.com/expo/react-native/archive/sdk-21.0.2.tar.gz => 0.48.4

  Target Platform: Android (7.0)

### Steps to Reproduce

1. Use WebView component from react-native package
2. Insert any you want youtube embed video url to `source={{ uri: here... }}`

### Expected Behavior

Video should play as usual

### Actual Behavior

But there is such flicker bug:
![bug](https://user-images.githubusercontent.com/14055801/31714897-5bf92e7a-b40a-11e7-8ee4-2662963b1469.gif)

### Reproducible Demo

```javascript
<WebView
  style={styles.video}
  javaScriptEnabled
  source={{ uri: `https://www.youtube.com/embed/${video.youtube}?rel=0&autoplay=0&showinfo=0&fs=1` }}
/>
```

**Comment by ksegla** [comment]
+1
On my side, I think the problem appeared when I made the jump from 0.43.2 to 0.48.2.
I don't seem to have any issues on Android versions 4.4 (Galaxy S3) or  5.1 (Galaxy S6). But on Android 7 (Galaxy S8), Webview crashes a lot. And oftem flickers for youtube and even simple gifs.

**Comment by Jayasagar** [comment]
Still happening on RN 0.52.2.

**Comment by sridhard** [comment]
still the issue happens.
