### ISSUE TITLE
start with error "undefined is not an object( evaluating '_react2.PropTypes.string')"

### ISSUE THREAD

**Issue by liukefu2050** [facebook/react-native#16442]
### Is this a bug report?

YES

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

YES

### Environment
    OS:  macOS Sierra 10.12.6
    Node:  8.4.0
    Yarn:  0.27.5
    npm:  5.4.0
    Watchman:  4.7.0
    Xcode:  Xcode 8.3.3 Build version 8E3004b
    Android Studio:  2.3 AI-162.4069837

  Packages: (wanted => installed)
    react-native: 0.49.3 => 0.49.3
    react: 16.0.0-beta.5 => 16.0.0-beta.5

  Target Platform: iOS (10.3)

### Steps to Reproduce

1.Create a ReactNative project, which uses React Native 49
### some code
    import React, {
        Component,
        PropTypes
    } from 'react';
    import {
        Platform,
        StyleSheet,
        Text,
        View
    } from 'react-native';
    
    const instructions = Platform.select({
        ios: 'Press Cmd+R to reload,\n' +
        'Cmd+D or shake for dev menu',
        android: 'Double tap R on your keyboard to reload,\n' +
        'Shake or press menu button for dev menu',
    });
    
    export default class App extends Component<{}> {
        static propTypes = {
            showText: PropTypes.string,  
            tag: PropTypes.string, 
            tagId: PropTypes.string, 
            onClick: PropTypes.func,  
            width: PropTypes.number
        }
    
        render() {
            return (
                <View style={styles.container}>
                    <Text style={styles.welcome}>
                        Welcome to React Native!
                    </Text>
                    <Text style={styles.instructions}>
                        To get started, edit App.js
                    </Text>
                    <Text style={styles.instructions}>
                        {instructions}
                    </Text>
                </View>
            );
        }
    }
    
    const styles = StyleSheet.create({
        container: {
            flex: 1,
            justifyContent: 'center',
            alignItems: 'center',
            backgroundColor: '#F5FCFF',
        },
        welcome: {
            fontSize: 20,
            textAlign: 'center',
            margin: 10,
        },
        instructions: {
            textAlign: 'center',
            color: '#333333',
            marginBottom: 5,
        },
    });

2.Run the project

### Expected Behavior
red screen

### Actual Behavior
An exception is thrown: undefined is not an object( evaluating '_react2.PropTypes.string')

### Reproducible Demo

Thanks !

https://github.com/facebook/prop-types/issues/128

**Comment by liukefu2050** [comment]
#https://github.com/facebook/prop-types/issues/128

**Comment by ljharb** [comment]
This is intentional; React 16 does not have a `PropTypes` property.

**Comment by DalalAbadi** [comment]
Install this to do the migration automatically :
https://github.com/reactjs/react-codemod

then run this command :
jscodeshift -t react-codemod/transforms/React-PropTypes-to-prop-types.js <your/project/path>
