### ISSUE TITLE
[Style] flexWrap: 'wrap' in a Navigator will cause crash

### ISSUE THREAD

**Issue by magicismight** [facebook/react-native#1644]
View in a Navigator with the style below will cause app crashed when the Navigator route changes
```css
{
    flexDirection: 'row',
    flexWrap: 'wrap'
}
```

**Comment by magicismight** [comment]
If the outside container of this `flexWrap: 'wrap'` element doesn`t have a width.
It will crash.But if give the outside container a width style,It works fine.

**Comment by jsierles** [comment]
Duplicate of #1378 

Hopefully this will be fixed soon with a new import of the css-layout package.

**Comment by brentvatne** [comment]
@vjeux - I think we need to update css-layout

**Comment by everfire130** [comment]
I met the same problem.

**Comment by mattds** [comment]
I've also encountered this, it worked for me after I set the outer container to have the style: flex: 1

**Comment by joel100** [comment]
+1 for fixing this. I just ran into this in both 0.7 and 0.8

**Comment by browniefed** [comment]
@brentvatne this is fixed.

**Comment by ide** [comment]
Fixed in 0.10.
