### ISSUE TITLE
[Android WebView] No Fullscreen API Support

### ISSUE THREAD

**Issue by onrige** [facebook/react-native#16444]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS:  macOS Sierra 10.12.6
  Node:  6.9.5
  Yarn:  1.1.0
  npm:  5.5.1
  Watchman:  4.9.0
  Xcode:  Xcode 9.0 Build version 9A235
  Android Studio:  Not Found

Packages: (wanted => installed)
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: https://github.com/expo/react-native/archive/sdk-21.0.2.tar.gz => 0.48.4

  Target Platform: Android (7.0)

### Steps to Reproduce

1. Use WebView component from react-native package
2. Insert any you want youtube embed video url to `source={{ uri: here... }}`

### Expected Behavior

There is should be a button to change fullscreen mode for the video

### Actual Behavior

But this button is missing
<img width="333" alt="screen shot 2017-10-18 at 13 27 03" src="https://user-images.githubusercontent.com/14055801/31713970-bd302ace-b408-11e7-9f26-500d000a9c82.png">
Also there are an issue #5230, ignored PR #10327 and [feature request](https://react-native.canny.io/feature-requests/p/webview-android-video-fullscreen).

### Reproducible Demo

```javascript
<WebView
  style={styles.video}
  javaScriptEnabled
  source={{ uri: `https://www.youtube.com/embed/${video.youtube}?rel=0&autoplay=0&showinfo=0&fs=1` }}
/>
```

**Comment by Hauuguu** [comment]
@hramos Can we please get this looked at? You had suggested I open a new issue in #5230 but @onrige did us all a favor and took the initiative to open this. Cheers.

**Comment by raphaeleidus** [comment]
Please reopen this

**Comment by nebmesemaou** [comment]
still have problem reopen pls

**Comment by ozanmanav** [comment]
+1

**Comment by jdeanwaite** [comment]
What needs to be done in order to push something along here?

**Comment by gancheng** [comment]
+1

**Comment by rafaelsorto** [comment]
+1

**Comment by roysG** [comment]
Amazing Solution , Enjoy!
https://github.com/teamairship/react-native-android-fullscreen-webview-video
