### ISSUE TITLE
Invalid character in findSymlinkModules.js line 37 when running react-native run-android

### ISSUE THREAD

**Issue by yenda** [facebook/react-native#16458]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

No

### Environment

```Environment:
  OS:  Linux 4.8
  Node:  8.5.0
  Yarn:  Not Found
  npm:  5.3.0
  Watchman:  4.9.0
```

### Issue

When I run `react-native run-android` I get 

```
/home/yenda/status-react/node_modules/react-native/local-cli/util/findSymlinkedModules.js:37
ignoredRoots? = [])
            ^

SyntaxError: Unexpected token ?
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:588:28)
    at loader (/home/yenda/status-react/node_modules/metro-bundler/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/yenda/status-react/node_modules/metro-bundler/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
```
Removing the `?` fixes it.
https://github.com/facebook/react-native/blob/master/local-cli/util/findSymlinkedModules.js#L37

**Comment by Kureev** [comment]
Hi @yenda!

Strange, looks like for some reason it doesn't stripe out flow types 🤔 Do you have a custom setup or something? How can I reproduce this issue?

**Comment by yenda** [comment]
Hi @Kureev ,

I am not really familiar with javascript ecosystem so I am not sure what you mean by striping flow types.
Is it related to flowconfig ? Here is our project flowconfig file https://github.com/status-im/status-react/blob/develop/.flowconfig

What part of my setup would be relevant to you besides the project itself ?

**Comment by yenda** [comment]
I just deleted my repo and re-cloned it and the error disappeared

**Comment by vitamin-deaner** [comment]
I had the exact same issue. Yenda's turn it off and back on again approach miraculously worked for me too. thanks

**Comment by robrichard** [comment]
I have the same issue in an iOS project. Re-cloning did not help.

**Comment by zaidqureshi2** [comment]
cleaning my node_module folder helped, almost same as recloning

**Comment by robrichard** [comment]
I had babel-plugin-transform-flow-strip-types@6.14.0 in my yarn.lock. Recreating the yarn.lock installed v6.22.0 and fixed this issue.

**Comment by sibelius** [comment]
I have the same issue, any other fix?

**Comment by HananeAlSamrout** [comment]
i just removed "?" from the file and it worked
