### ISSUE TITLE
Unable to resolve module SegmentedControlIOS

### ISSUE THREAD

**Issue by amitava82** [facebook/react-native#16452]
### Is this a bug report?
I've upgraded to 0.49.3 following `react-native-git-upgrade`. My project builds fine but I'm getting following error

![screen shot 2017-10-18 at 9 52 21 am](https://user-images.githubusercontent.com/1279530/31724866-d8d9b442-b3f0-11e7-8c0e-af4add6efc05.png)

I've followed all the steps to clean cache, remove node_modules but no luck.

### Environment
Environment:
  OS:  macOS High Sierra 10.13
  Node:  7.5.0
  Yarn:  1.2.1
  npm:  4.1.2
  Watchman:  4.7.0
  Xcode:  Xcode 9.0 Build version 9A235
  Android Studio:  2.2 AI-145.3537739

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: 0.49.3 => 0.49.3

  Target Platform: iOS (11)

**Comment by matthew-reilly** [comment]
@amitava82 Any resolution to this? Seeing this as well.

**Comment by XMalatji** [comment]
Im also getting this error but ok.

**Comment by nicoara** [comment]
solution: rm -rf /tmp/metro-bundler-cache-*
