### ISSUE TITLE
[Cocoapods] no package.json found.

### ISSUE THREAD

**Issue by zace-yuan** [facebook/react-native#1645]
I use Cocoapods import React Native, and I run script './Pods/React/packager/packager.sh --projectRoots=/Users/Zac/Documents/Test/ReactNative/ReactComponent,/Users/Zac/Documents/Test/ReactNative/Pods/React/'. Every is fine,but when I use 'var DetailView = require('./DetailView')' in List.ios.js file , display redbox and terminal show log is "Error: Expected relative module lookup from /Users/Zac/Documents/Test/ReactNative/ReactComponent/list.ios.js to ./DetailView to be within a package but no package.json found."

I want to know why and how what i do fixed it?

**Comment by sghiassy** [comment]
Check out issue https://github.com/facebook/react-native/issues/925

**Comment by brentvatne** [comment]
Closing because @sghiassy nailed it
