### ISSUE TITLE
[Packager] Multiple versions of a library, choosing the wrong one

### ISSUE THREAD

**Issue by almost** [facebook/react-native#1646]
I'm using [Underscore.js](http://underscorejs.org/) in my code, I've got the latest version in `node_modules` but the packager finds a (very old) version installed as a dependency of the `jest-cli` package and uses that instead.

I would expect the packager to favour the version installed in the higher up `node_modules` directory.

I found that adding `'node_modules/jest-cli'` to the `sharedBlacklist` in [blacklist.js](https://github.com/facebook/react-native/blob/0.6-stable/packager/blacklist.js#L13) fixes it for that one module, but obviously that's not a general solution (it would still be nice to be able to specify extra blacklist directories as a configuration option for the pacakager though).

**Comment by almost** [comment]
Demonstration of the issue is here: https://github.com/almost/react-packager-issue-demo

When run the app displays "Underscore version: 1.2.4", the expected output should be "Underscore version 1.8.3"

**Comment by almost** [comment]
I've tested with 0.6.0-rc and with master as of just now

**Comment by ide** [comment]
Thanks for the repro and noting the versions... @amasad is this something that your node_modules algorithm diffs could fix?

**Comment by nicinabox** [comment]
I have this issue with 0.5.0 when including `lodash`. One of my dependencies uses an older version (2.4.1) and I have 3.9.3 in `node_modules/lodash`. Using `require('lodash')` the older version gets included. The intended version was unrecognized unless I specified `require('lodash/index')` or a specific module from it.

**Comment by almost** [comment]
I can confirm this is now fixed in master, I'll close the issue
