### ISSUE TITLE
Reload / Dev Menu are repeatedly invoked while holding Cmd key

### ISSUE THREAD

**Issue by jd20** [facebook/react-native#16469]
### Is this a bug report?

Yes. 

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes.

### Environment

Environment:
  OS:  macOS High Sierra 10.13
  Node:  8.4.0
  Yarn:  0.21.3
  npm:  5.3.0
  Watchman:  4.7.0
  Xcode:  Xcode 9.0.1 Build version 9A1004
  Android Studio:  2.3 AI-162.3871768

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: 0.49.3 => 0.49.3

### Steps to Reproduce

1. `react-native init testproject`
2. `cd testproject && react-native run-ios`
3. In the simulator, press Cmd+R or Cmd+D, but do not release the Cmd key. While the Cmd key is being held, the action will repeatedly be invoked. For example, screen will keep reloading rapidly, or developer menu will keep popping up and disappearing, as if it had a mind of it's own.

Note: If you use any other method to invoke reload or dev menu (like choosing Shake gesture from the Simulator menu, this behavior does not happen).

### Expected Behavior

The action (to either reload or show/hide the developer menu), should only happen once, not continuously as the Cmd key is held.

### Actual Behavior

Action keeps getting invoked repeatedly.

### Reproducible Demo

I'm able to reproduce this with any react-native project. The behavior is probably more specific to either RN/macOS/XCode version. Was also happening on macOS 10.12 (not sure at what point the bug was introduced, or if it had always been there).

**Comment by jondubman** [comment]
I'm able to repro this reliably with latest macOS, XCode, RN and a newly created project. The issue has remained for several months even with the following upgrades:

  Environment:
    OS:  macOS Sierra 10.13.3
    Node:  8.9.4
    Yarn:  1.3.2
    npm:  5.6.0
    Watchman:  4.9.0
    Xcode:  Xcode 9.2 Build version 9C40b

  Packages: (wanted => installed)
    react-native: 0.53.0 => 0.53.0
    react: 16.2.0 => 116.2.0

  Target Platform: iOS (10.3)
