### ISSUE TITLE
[Discussion] Custom Event Names

### ISSUE THREAD

**Issue by paramaggarwal** [facebook/react-native#1647]
Currently, there is no way for a custom native module to make custom event names like `onVideoPlayerDidLoad`. There is only one global list of event names defined in  [RCTUIManager.m](https://github.com/facebook/react-native/blob/master/React/Modules/RCTUIManager.m#L1232-L1235).

There is also a comment there regarding this, but I cannot find a corresponding issue, hence creating one and sharing my thoughts.

```
// TODO: these event types should be distributed among the modules
// that declare them. Also, events should be registrable by any class
// that can call event handlers, not just UIViewManagers. This code
// also seems highly redundant - every event has the same properties.
```

Instead of making the native module specify names for each and every event, what if the event name is generated automatically? So on calling `[self.bridge.eventDispatcher sendInputEventWithName:@"onVideoPlayerDidLoad" body:event];` it will internally call `onVideoPlayerDidLoad` on the JS and for capture phase: `onVideoPlayerDidLoadCapture`. 

Is there some reason we need to specify the [mappings](https://github.com/facebook/react-native/blob/master/React/Modules/RCTUIManager.m#L1236-L1245) beforehand?

**Comment by ide** [comment]
FYI your custom modules can define their own events. I forget the specifics but somewhere in RCTUIManager it asks each module for its events.

**Comment by paramaggarwal** [comment]
Checking... In that case we should document the same, and also remove the above comment in the code (I think).

**Comment by ide** [comment]
Oh.. the comment is right -- only custom modules that are view managers can fire events. I imagine for 95%+ of cases you'd want to fire a UI event from only a view manager. In non-view managers you'd just use the event dispatcher to fire an event through DeviceEventEmitter.

**Comment by paramaggarwal** [comment]
Ah, [I see it here](https://github.com/facebook/react-native/blob/master/React/Modules/RCTUIManager.m#L1333-L1334). In that case we should document the same. (Once I learn how it works, maybe I can do this myself.)

So the comment has multiple parts:

> These event types should be distributed among the modules that declare them.

Is this too complicated to do? Maybe I can take a shot at attempting this.

> Events should be registrable by any class that can call event handlers, not just UIViewManagers.

This the comment I misunderstood and which you clarify above. So the point here is that any Native Module should be able to define events, not just the ones that inherit from `RCTViewManager`?

> This code also seems highly redundant - every event has the same properties.

This is the bit where I was suggesting why even specify event names. Why not just call the event and map it to corresponding event name in JS automatically. What are the challenges in doing so?

**Comment by paramaggarwal** [comment]
Also, what is the difference between `customBubblingEventTypes` and `customDirectEventTypes`?

**Comment by ide** [comment]
>> These event types should be distributed among the modules that declare them.

>Is this too complicated to do? Maybe I can take a shot at attempting this.

Probably would be appreciated. Some of the events might be shared by multiple modules though, so centralizing them in the UIManager might make sense. Also Facebook may have internal modules that also use the same events so you'd need to get someone to test the FB apps too.

> So the point here is that any Native Module should be able to define events, not just the ones that inherit from RCTViewManager?

I guess so but it doesn't seem that useful because all modules can already emit events via the NativeAppEventEmitter and DeviceEventEmitter. The limitation now is just that non-view managers cannot fire UI events... which seems mostly fine. If someone has a compelling use case then we could look into it.

> This is the bit where I was suggesting why even specify event names. Why not just call the event and map it to corresponding event name in JS automatically. What are the challenges in doing so?

I'm not sure - you could read the code to learn that.

> Also, what is the difference between customBubblingEventTypes and customDirectEventTypes?

Bubbling events are like DOM events so that a parent component can capture an event fired by its child. Generally these are UI-related, like "the user touched this box". Direct events are not bubbled and are intended for more abstract events like "this image failed to load".

**Comment by cosmith** [comment]
+1 for the docs, spent a long time before realizing that I had to implement `- (NSArray*)customBubblingEventTypes` in my manager to declare my event names. I might submit a PR later.
