### ISSUE TITLE
console.warn will break production builds

### ISSUE THREAD

**Issue by joarwilk** [facebook/react-native#16474]
### Is this a bug report?
Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS:  macOS Sierra 10.12.6
  Node:  8.3.0
  Yarn:  1.2.0
  npm:  5.5.1
  Watchman:  4.7.0
  Xcode:  Xcode 9.0 Build version 9A235
  Android Studio:  2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: 0.48.1 => 0.48.1

### Steps to Reproduce

Use `console.warn` in production and pass in something that does not have `indexOf` as a property as the first argument.

### Expected Behavior

`console.warn` should behave like it does in development, printing the warning to the console. Or do nothing. But it should not crash the application.

### Actual Behavior

Application crashes. 

### Reproducible Demo

`console.warn({})` in production.

Here is the offending logic:
```
console.warn = function() {
  if (!(
    arguments[0] &&
    arguments[0].indexOf("Requiring module 'NativeModules' by name") > -1
  ))
    return o.apply(console, arguments);
};
```

It runs `.indexOf` on any thing passed into console.warn, which will break for most types.

Do note I don't really approve of using console.warn in production, but it should be silent if anything.

**Comment by yinghang** [comment]
`RedBoxes and YellowBoxes are automatically disabled in release (production) builds.`

https://facebook.github.io/react-native/docs/debugging.html#in-app-errors-and-warnings

If I'm not wrong, they are disabled in production builds.

**Comment by joarwilk** [comment]
>If I'm not wrong, they are disabled in production builds.

Redboxes and yellowboxes yes, but the overwritten console.warn is still there.
