### ISSUE TITLE
Error while updating property 'borderRadius' of a view managed by :  RCTView 

### ISSUE THREAD

**Issue by jpca999** [facebook/react-native#16485]
Does anybody know how to fix this ?

![image](https://user-images.githubusercontent.com/1026325/31855563-a5d13b6e-b67b-11e7-9e74-8a65c1c71263.png)

### Is this a bug report?

(write your answer here)

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.)

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by kristfal** [comment]
Error says it there: you’re calling a border radius style object with string instead of number. This issue might also happen if your border radius is undefined / null.

**Comment by jpca999** [comment]
It has something to do with android. Error doesn’t happen on iOS simulator.

**Comment by libetl** [comment]
I can confirm that it works with react+electron, whereas it fails with react-native.
I react web, a percentage-valued borderRadius works, and if fails abruptly with react-native
