### ISSUE TITLE
[Geolocation] navigator.geolocation doesn't accept options any longer

### ISSUE THREAD

**Issue by PatrickHeneise** [facebook/react-native#1648]
The following code worked on 0.4.x:

    componentDidMount: function() {
      var that = this;
      navigator.geolocation.getCurrentPosition(
        function (initialPosition) {
          that.setState({initialPosition});
          that.fetchData(initialPosition);
        },
        function (error) {
          that.fetchData({});
        },
        {enableHighAccuracy: true, timeout: 500, maximumAge: 1000}
      );
    }

0.5.0 crashes with the options attached ({enableHighAccuracy: true, timeout: 500, maximumAge: 1000}) and throws an error:

```
2015-06-17 13:23:41.775 [warn][tid:com.facebook.React.JavaScript] "Warning: Cannot find callback with CBID 5. Native module may have invoked both the success callback and the error callback."
2015-06-17 13:23:41.776 [error][tid:com.facebook.React.JavaScript] "Error: null is not an object (evaluating 'cb.apply')
 stack: 
  _invokeCallback         index.ios.bundle:7634
  <unknown>               index.ios.bundle:7697
  <unknown>               index.ios.bundle:7689
  perform                 index.ios.bundle:6203
  batchedUpdates          index.ios.bundle:14047
  batchedUpdates          index.ios.bundle:4735
  <unknown>               index.ios.bundle:7688
  applyWithErrorReporter  index.ios.bundle:7440
  guardReturn             index.ios.bundle:7462
  processBatch            index.ios.bundle:7687
 URL: http://localhost:8081/index.ios.bundle
 line: 7634
 message: null is not an object (evaluating 'cb.apply')"
```

**Comment by svenanders** [comment]
Seeing this too. Setting options to 'null' bypasses the problem, but of course it would be nice to use options.

**Comment by svenanders** [comment]
Also, it doesn't seem to respect custom locations, giving Apple's Cupertino address in the simulator no matter which Location you choose from the Debug menu.

**Comment by sghiassy** [comment]
I'm seeing this problem as well. Good to know it works on a real device

**Comment by brentvatne** [comment]
Anyone want to dig into this and submit a PR if it's a bug? Would be much appreciated! @sghiassy? @svenanders? :)

**Comment by svenanders** [comment]
Sure :)

**Comment by svenanders** [comment]
So.. I did some tests, and options works (almost) as expected in react 0.6.0. The accuracy setting was overridden however, so I sent a PR for that (https://github.com/facebook/react-native/pull/1906). Also, if you want to change locations, you're kind of out of luck because there wasn't a way to set the app to observe location changes (which means even when you've moved to a new location, you get the first location data that was available). I added that too in the PR with a hook to the _enableHighAccuracy_ option. It works great for me, so I hope it's an acceptable change.

**Comment by PatrickHeneise** [comment]
:+1:

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/geolocation-navigatorgeolocation-doesnt-accept-options-any-longer
