### ISSUE TITLE
how to figure where is the warning error coming from ?

### ISSUE THREAD

**Issue by jpca999** [facebook/react-native#16492]
![image](https://user-images.githubusercontent.com/1026325/31863482-f31336d4-b71b-11e7-874e-3c23df99264c.png)

Warning: Failed prop type: Invalid props.style key `fontSize` supplied to `ScrollView`.
Bad object: {
  "backgroundColor": "white",
  "margin": 10,
  "fontSize": 12
}
Valid keys: [
  "display",
  "width",
  "height",
  "top",
  "left",
  "right",
  "bottom",
  "minWidth",
  "maxWidth",
  "minHeight",
  "maxHeight",
  "margin",
  "marginVertical",
  "marginHorizontal",
  "marginTop",
  "marginBottom",
  "marginLeft",
  "marginRight",
  "padding",
  "paddingVertical",
  "paddingHorizontal",
  "paddingTop",
  "paddingBottom",
  "paddingLeft",
  "paddingRight",
  "borderWidth",
  "borderTopWidth",
  "borderRightWidth",
  "borderBottomWidth",
  "borderLeftWidth",
  "position",
  "flexDirection",
  "flexWrap",
  "justifyContent",
  "alignItems",
  "alignSelf",
  "alignContent",
  "overflow",
  "flex",
  "flexGrow",
  "flexShrink",
  "flexBasis",
  "aspectRatio",
  "zIndex",
  "direction",
  "shadowColor",
  "shadowOffset",
  "shadowOpacity",
  "shadowRadius",
  "transform",
  "transformMatrix",
  "decomposedMatrix",
  "scaleX",
  "scaleY",
  "rotation",
  "translateX",
  "translateY",
  "backfaceVisibility",
  "backgroundColor",
  "borderColor",
  "borderTopColor",
  "borderRightColor",
  "borderBottomColor",
  "borderLeftColor",
  "borderRadius",
  "borderTopLeftRadius",
  "borderTopRightRadius",
  "borderBottomLeftRadius",
  "borderBottomRightRadius",
  "borderStyle",
  "opacity",
  "elevation"
]
    in ScrollView (at ListView.js:332)
    in ListView (at MapScreen.js:137)
    in RCTView (at View.js:113)
    in View (at MapScreen.js:136)
    in RCTView (at View.js:113)
    in View (at MapScreen.js:114)
    in MapScreen (created by Connect(MapScreen))
    in Connect(MapScreen) (at SceneView.js:35)
    in SceneView (at CardStack.js:408)
    in RCTView (at View.js:113)
    in View (at AnimatedImplementation.js:1865)
    in AnimatedComponent (at Card.js:28)
    in Card (at PointerEventsContainer.js:55)
    in Container (at CardStack.js:438)
    in RCTView (at View.js:113)
    in View (at CardStack.js:368)
    in RCTView (at View.js:113)
    in View (at CardStack.js:367)
    in CardStack (at CardStackTransitioner.js:110)
    in RCTView (at View.js:113)
    in View (at Transitioner.js:192)
    in Transitioner (at CardStackTransitioner.js:60)
    in CardStackTransitioner (at StackNavigator.js:48)
    in Unknown (at createNavigator.js:36)
    in Navigator (at createNavigationContainer.js:200)
    in NavigationContainer (at SceneView.js:35)
    in SceneView (at TabView.js:70)
    in RCTView (at View.js:113)
    in View (at TabView.js:69)
    in RCTView (at View.js:113)
    in View (at TabViewPagerPan.js:285)
    in RCTView (at View.js:113)
    in View (at AnimatedImplementation.js:1865)
    in AnimatedComponent (at TabViewPagerPan.js:275)
    in TabViewPagerPan (at TabView.js:133)
    in RCTView (at View.js:113)
    in View (at TabViewAnimated.js:260)
    in TabViewAnimated (at TabView.js:185)
    in TabView (at withCachedChildNavigation.js:60)
    in withCachedChildNavigation(TabView) (at TabNavigator.js:51)
    in Unknown (at createNavigator.js:36)
    in Navigator (at createNavigationContainer.js:200)
    in NavigationContainer (at SceneView.js:35)
    in SceneView (at TabView.js:70)
    in RCTView (at View.js:113)
    in View (at TabView.js:69)
    in RCTView (at View.js:113)
    in View (at TabViewPagerPan.js:285)
    in RCTView (at View.js:113)
    in View (at AnimatedImplementation.js:1865)
    in AnimatedComponent (at TabViewPagerPan.js:275)
    in TabViewPagerPan (at TabView.js:133)
    in RCTView (at View.js:113)
    in View (at TabViewAnimated.js:260)
    in TabViewAnimated (at TabView.js:185)
    in TabView (at withCachedChildNavigation.js:60)
    in withCachedChildNavigation(TabView) (at TabNavigator.js:51)
    in Unknown (at createNavigator.js:36)
    in Navigator (at createNavigationContainer.js:200)
    in NavigationContainer (at App.js:235)
    in RCTView (at View.js:113)
    in View (at App.js:234)
    in Provider (at App.js:233)
    in App (at registerRootComponent.js:36)
    in RootErrorBoundary (at registerRootComponent.js:35)
    in ExpoRootComponent (at renderApplication.js:35)
    in RCTView (at View.js:113)
    in View (at AppContainer.js:100)
    in RCTView (at View.js:113)
    in View (at AppContainer.js:121)
    in AppContainer (at renderApplication.js:34)
11:26:13 AM
▶Warning: Failed prop type: Invalid props.style key `fontSize` supplied to `ListView`.
Bad object: {
  "backgroundColor": "white",
  "margin": 10,
  "fontSize": 12
}
Valid keys: [
  "display",
  "width",
  "height",
  "top",
  "left",
  "right",
  "bottom",
  "minWidth",
  "maxWidth",
  "minHeight",
  "maxHeight",
  "margin",
  "marginVertical",
  "marginHorizontal",
  "marginTop",
  "marginBottom",
  "marginLeft",
  "marginRight",
  "padding",
  "paddingVertical",
  "paddingHorizontal",
  "paddingTop",
  "paddingBottom",
  "paddingLeft",
  "paddingRight",
  "borderWidth",
  "borderTopWidth",
  "borderRightWidth",
  "borderBottomWidth",
  "borderLeftWidth",
  "position",
  "flexDirection",
  "flexWrap",
  "justifyContent",
  "alignItems",
  "alignSelf",
  "alignContent",
  "overflow",
  "flex",
  "flexGrow",
  "flexShrink",
  "flexBasis",
  "aspectRatio",
  "zIndex",
  "direction",
  "shadowColor",
  "shadowOffset",
  "shadowOpacity",
  "shadowRadius",
  "transform",
  "transformMatrix",
  "decomposedMatrix",
  "scaleX",
  "scaleY",
  "rotation",
  "translateX",
  "translateY",
  "backfaceVisibility",
  "backgroundColor",
  "borderColor",
  "borderTopColor",
  "borderRightColor",
  "borderBottomColor",
  "borderLeftColor",
  "borderRadius",
  "borderTopLeftRadius",
  "borderTopRightRadius",
  "borderBottomLeftRadius",
  "borderBottomRightRadius",
  "borderStyle",
  "opacity",
  "elevation"
]
    in ListView (at MapScreen.js:137)
    in MapScreen (created by Connect(MapScreen))
    in Connect(MapScreen) (at SceneView.js:35)
    in SceneView (at CardStack.js:408)
    in RCTView (at View.js:113)
    in View (at AnimatedImplementation.js:1865)
    in AnimatedComponent (at Card.js:28)
    in Card (at PointerEventsContainer.js:55)
    in Container (at CardStack.js:438)
    in RCTView (at View.js:113)
    in View (at CardStack.js:368)
    in RCTView (at View.js:113)
    in View (at CardStack.js:367)
    in CardStack (at CardStackTransitioner.js:110)
    in RCTView (at View.js:113)
    in View (at Transitioner.js:192)
    in Transitioner (at CardStackTransitioner.js:60)
    in CardStackTransitioner (at StackNavigator.js:48)
    in Unknown (at createNavigator.js:36)
    in Navigator (at createNavigationContainer.js:200)
    in NavigationContainer (at SceneView.js:35)
    in SceneView (at TabView.js:70)
    in RCTView (at View.js:113)
    in View (at TabView.js:69)
    in RCTView (at View.js:113)
    in View (at TabViewPagerPan.js:285)
    in RCTView (at View.js:113)
    in View (at AnimatedImplementation.js:1865)
    in AnimatedComponent (at TabViewPagerPan.js:275)
    in TabViewPagerPan (at TabView.js:133)
    in RCTView (at View.js:113)
    in View (at TabViewAnimated.js:260)
    in TabViewAnimated (at TabView.js:185)
    in TabView (at withCachedChildNavigation.js:60)
    in withCachedChildNavigation(TabView) (at TabNavigator.js:51)
    in Unknown (at createNavigator.js:36)
    in Navigator (at createNavigationContainer.js:200)
    in NavigationContainer (at SceneView.js:35)
    in SceneView (at TabView.js:70)
    in RCTView (at View.js:113)
    in View (at TabView.js:69)
    in RCTView (at View.js:113)
    in View (at TabViewPagerPan.js:285)
    in RCTView (at View.js:113)
    in View (at AnimatedImplementation.js:1865)
    in AnimatedComponent (at TabViewPagerPan.js:275)
    in TabViewPagerPan (at TabView.js:133)
    in RCTView (at View.js:113)
    in View (at TabViewAnimated.js:260)
    in TabViewAnimated (at TabView.js:185)
    in TabView (at withCachedChildNavigation.js:60)
    in withCachedChildNavigation(TabView) (at TabNavigator.js:51)
    in Unknown (at createNavigator.js:36)
    in Navigator (at createNavigationContainer.js:200)
    in NavigationContainer (at App.js:235)
    in RCTView (at View.js:113)
    in View (at App.js:234)
    in Provider (at App.js:233)
    in App (at registerRootComponent.js:36)
    in RootErrorBoundary (at registerRootComponent.js:35)
    in ExpoRootComponent (at renderApplication.js:35)
    in RCTView (at View.js:113)
    in View (at AppContainer.js:100)
    in RCTView (at View.js:113)
    in View (at AppContainer.js:121)
    in AppContainer (at renderApplication.js:34)
11:26:15 AM
▶Warning: Failed prop type: Invalid props.style key `fontFamily` supplied to `TouchableHighlight`.
Bad object: {
  "padding": 20,
  "paddingTop": 20,
  "paddingBottom": 20,
  "backgroundColor": "white",
  "fontFamily": "morbi-rounded"
}
Valid keys: [
  "display",
  "width",
  "height",
  "top",
  "left",
  "right",
  "bottom",
  "minWidth",
  "maxWidth",
  "minHeight",
  "maxHeight",
  "margin",
  "marginVertical",
  "marginHorizontal",
  "marginTop",
  "marginBottom",
  "marginLeft",
  "marginRight",
  "padding",
  "paddingVertical",
  "paddingHorizontal",
  "paddingTop",
  "paddingBottom",
  "paddingLeft",
  "paddingRight",
  "borderWidth",
  "borderTopWidth",
  "borderRightWidth",
  "borderBottomWidth",
  "borderLeftWidth",
  "position",
  "flexDirection",
  "flexWrap",
  "justifyContent",
  "alignItems",
  "alignSelf",
  "alignContent",
  "overflow",
  "flex",
  "flexGrow",
  "flexShrink",
  "flexBasis",
  "aspectRatio",
  "zIndex",
  "direction",
  "shadowColor",
  "shadowOffset",
  "shadowOpacity",
  "shadowRadius",
  "transform",
  "transformMatrix",
  "decomposedMatrix",
  "scaleX",
  "scaleY",
  "rotation",
  "translateX",
  "translateY",
  "backfaceVisibility",
  "backgroundColor",
  "borderColor",
  "borderTopColor",
  "borderRightColor",
  "borderBottomColor",
  "borderLeftColor",
  "borderRadius",
  "borderTopLeftRadius",
  "borderTopRightRadius",
  "borderBottomLeftRadius",
  "borderBottomRightRadius",
  "borderStyle",
  "opacity",
  "elevation"
]
    in TouchableHighlight (at ListItem.js:98)
    in ListItem (at AllPropertiesScreen.js:129)
    in RCTView (at View.js:113)
    in View (at VirtualizedList.js:1238)
    in CellRenderer (at VirtualizedList.js:463)
    in RCTScrollContentView (at ScrollView.js:707)
    in RCTScrollView (at ScrollView.js:778)
    in ScrollView (at VirtualizedList.js:749)
    in VirtualizedList (at FlatList.js:557)
    in FlatList (at AllPropertiesScreen.js:126)
    in AllPropertiesScreen (created by Connect(AllPropertiesScreen))
    in Connect(AllPropertiesScreen) (at SceneView.js:35)
    in SceneView (at CardStack.js:408)
    in RCTView (at View.js:113)
    in View (at AnimatedImplementation.js:1865)
    in AnimatedComponent (at Card.js:28)
    in Card (at PointerEventsContainer.js:55)
    in Container (at CardStack.js:438)
    in RCTView (at View.js:113)
    in View (at CardStack.js:368)
    in RCTView (at View.js:113)
    in View (at CardStack.js:367)
    in CardStack (at CardStackTransitioner.js:110)
    in RCTView (at View.js:113)
    in View (at Transitioner.js:192)
    in Transitioner (at CardStackTransitioner.js:60)
    in CardStackTransitioner (at StackNavigator.js:48)
    in Unknown (at createNavigator.js:36)
    in Navigator (at createNavigationContainer.js:200)
    in NavigationContainer (at SceneView.js:35)
    in SceneView (at TabView.js:70)
    in RCTView (at View.js:113)
    in View (at TabView.js:69)
    in RCTView (at View.js:113)
    in View (at TabViewPagerPan.js:285)
    in RCTView (at View.js:113)
    in View (at AnimatedImplementation.js:1865)
    in AnimatedComponent (at TabViewPagerPan.js:275)
    in TabViewPagerPan (at TabView.js:133)
    in RCTView (at View.js:113)
    in View (at TabViewAnimated.js:260)
    in TabViewAnimated (at TabView.js:185)
    in TabView (at withCachedChildNavigation.js:60)
    in withCachedChildNavigation(TabView) (at TabNavigator.js:51)
    in Unknown (at createNavigator.js:36)
    in Navigator (at createNavigationContainer.js:200)
    in NavigationContainer (at SceneView.js:35)
    in SceneView (at TabView.js:70)
    in RCTView (at View.js:113)
    in View (at TabView.js:69)
    in RCTView (at View.js:113)
    in View (at TabViewPagerPan.js:285)
    in RCTView (at View.js:113)
    in View (at AnimatedImplementation.js:1865)
    in AnimatedComponent (at TabViewPagerPan.js:275)
    in TabViewPagerPan (at TabView.js:133)
    in RCTView (at View.js:113)
    in View (at TabViewAnimated.js:260)
    in TabViewAnimated (at TabView.js:185)
    in TabView (at withCachedChildNavigation.js:60)
    in withCachedChildNavigation(TabView) (at TabNavigator.js:51)
    in Unknown (at createNavigator.js:36)
    in Navigator (at createNavigationContainer.js:200)
    in NavigationContainer (at App.js:235)
    in RCTView (at View.js:113)
    in View (at App.js:234)
    in Provider (at App.js:233)
    in App (at registerRootComponent.js:36)
    in RootErrorBoundary (at registerRootComponent.js:35)
    in ExpoRootComponent (at renderApplication.js:35)
    in RCTView (at View.js:113)
    in View (at AppContainer.js:100)
    in RCTView (at View.js:113)
    in View (at AppContainer.js:121)
    in AppContainer (at renderApplication.js:34)
11:26:17 AM
▶Warning: Failed prop type: Invalid props.style key `fontSize` supplied to `RCTScrollView`.
Bad object: {
  "flexGrow": 1,
  "flexShrink": 1,
  "flexDirection": "column",
  "overflow": "scroll",
  "backgroundColor": "white",
  "margin": 10,
  "fontSize": 12
}
Valid keys: [
  "display",
  "width",
  "height",
  "top",
  "left",
  "right",
  "bottom",
  "minWidth",
  "maxWidth",
  "minHeight",
  "maxHeight",
  "margin",
  "marginVertical",
  "marginHorizontal",
  "marginTop",
  "marginBottom",
  "marginLeft",
  "marginRight",
  "padding",
  "paddingVertical",
  "paddingHorizontal",
  "paddingTop",
  "paddingBottom",
  "paddingLeft",
  "paddingRight",
  "borderWidth",
  "borderTopWidth",
  "borderRightWidth",
  "borderBottomWidth",
  "borderLeftWidth",
  "position",
  "flexDirection",
  "flexWrap",
  "justifyContent",
  "alignItems",
  "alignSelf",
  "alignContent",
  "overflow",
  "flex",
  "flexGrow",
  "flexShrink",
  "flexBasis",
  "aspectRatio",
  "zIndex",
  "direction",
  "shadowColor",
  "shadowOffset",
  "shadowOpacity",
  "shadowRadius",
  "transform",
  "transformMatrix",
  "decomposedMatrix",
  "scaleX",
  "scaleY",
  "rotation",
  "translateX",
  "translateY",
  "backfaceVisibility",
  "backgroundColor",
  "borderColor",
  "borderTopColor",
  "borderRightColor",
  "borderBottomColor",
  "borderLeftColor",
  "borderRadius",
  "borderTopLeftRadius",
  "borderTopRightRadius",
  "borderBottomLeftRadius",
  "borderBottomRightRadius",
  "borderStyle",
  "opacity",
  "elevation"
]
    in RCTScrollView (at ScrollView.js:800)
    in ScrollView (at ListView.js:332)
    in ListView (at MapScreen.js:137)
    in RCTView (at View.js:113)
    in View (at MapScreen.js:136)
    in RCTView (at View.js:113)
    in View (at MapScreen.js:114)
    in MapScreen (created by Connect(MapScreen))
    in Connect(MapScreen) (at SceneView.js:35)
    in SceneView (at CardStack.js:408)
    in RCTView (at View.js:113)
    in View (at AnimatedImplementation.js:1865)
    in AnimatedComponent (at Card.js:28)
    in Card (at PointerEventsContainer.js:55)
    in Container (at CardStack.js:438)
    in RCTView (at View.js:113)
    in View (at CardStack.js:368)
    in RCTView (at View.js:113)
    in View (at CardStack.js:367)
    in CardStack (at CardStackTransitioner.js:110)
    in RCTView (at View.js:113)
    in View (at Transitioner.js:192)
    in Transitioner (at CardStackTransitioner.js:60)
    in CardStackTransitioner (at StackNavigator.js:48)
    in Unknown (at createNavigator.js:36)
    in Navigator (at createNavigationContainer.js:200)
    in NavigationContainer (at SceneView.js:35)
    in SceneView (at TabView.js:70)
    in RCTView (at View.js:113)
    in View (at TabView.js:69)
    in RCTView (at View.js:113)
    in View (at TabViewPagerPan.js:285)
    in RCTView (at View.js:113)
    in View (at AnimatedImplementation.js:1865)
    in AnimatedComponent (at TabViewPagerPan.js:275)
    in TabViewPagerPan (at TabView.js:133)
    in RCTView (at View.js:113)
    in View (at TabViewAnimated.js:260)
    in TabViewAnimated (at TabView.js:185)
    in TabView (at withCachedChildNavigation.js:60)
    in withCachedChildNavigation(TabView) (at TabNavigator.js:51)
    in Unknown (at createNavigator.js:36)
    in Navigator (at createNavigationContainer.js:200)
    in NavigationContainer (at SceneView.js:35)
    in SceneView (at TabView.js:70)
    in RCTView (at View.js:113)
    in View (at TabView.js:69)
    in RCTView (at View.js:113)
    in View (at TabViewPagerPan.js:285)
    in RCTView (at View.js:113)
    in View (at AnimatedImplementation.js:1865)
    in AnimatedComponent (at TabViewPagerPan.js:275)
    in TabViewPagerPan (at TabView.js:133)
    in RCTView (at View.js:113)
    in View (at TabViewAnimated.js:260)
    in TabViewAnimated (at TabView.js:185)
    in TabView (at withCachedChildNavigation.js:60)
    in withCachedChildNavigation(TabView) (at TabNavigator.js:51)
    in Unknown (at createNavigator.js:36)
    in Navigator (at createNavigationContainer.js:200)
    in NavigationContainer (at App.js:235)
    in RCTView (at View.js:113)
    in View (at App.js:234)
    in Provider (at App.js:233)
    in App (at registerRootComponent.js:36)
    in RootErrorBoundary (at registerRootComponent.js:35)
    in ExpoRootComponent (at renderApplication.js:35)
    in RCTView (at View.js:113)
    in View (at AppContainer.js:100)
    in RCTView (at View.js:113)
    in View (at AppContainer.js:121)
    in AppContainer (at renderApplication.js:34)
11:26:19 AM
▶Warning: Failed prop type: Invalid props.style key `fontFamily` supplied to `RCTView`.
Bad object: {
  "backgroundColor": "white",
  "padding": 20,
  "paddingTop": 20,
  "paddingBottom": 20,
  "fontFamily": "morbi-rounded"
}
Valid keys: [
  "display",
  "width",
  "height",
  "top",
  "left",
  "right",
  "bottom",
  "minWidth",
  "maxWidth",
  "minHeight",
  "maxHeight",
  "margin",
  "marginVertical",
  "marginHorizontal",
  "marginTop",
  "marginBottom",
  "marginLeft",
  "marginRight",
  "padding",
  "paddingVertical",
  "paddingHorizontal",
  "paddingTop",
  "paddingBottom",
  "paddingLeft",
  "paddingRight",
  "borderWidth",
  "borderTopWidth",
  "borderRightWidth",
  "borderBottomWidth",
  "borderLeftWidth",
  "position",
  "flexDirection",
  "flexWrap",
  "justifyContent",
  "alignItems",
  "alignSelf",
  "alignContent",
  "overflow",
  "flex",
  "flexGrow",
  "flexShrink",
  "flexBasis",
  "aspectRatio",
  "zIndex",
  "direction",
  "shadowColor",
  "shadowOffset",
  "shadowOpacity",
  "shadowRadius",
  "transform",
  "transformMatrix",
  "decomposedMatrix",
  "scaleX",
  "scaleY",
  "rotation",
  "translateX",
  "translateY",
  "backfaceVisibility",
  "backgroundColor",
  "borderColor",
  "borderTopColor",
  "borderRightColor",
  "borderBottomColor",
  "borderLeftColor",
  "borderRadius",
  "borderTopLeftRadius",
  "borderTopRightRadius",
  "borderBottomLeftRadius",
  "borderBottomRightRadius",
  "borderStyle",
  "opacity",
  "elevation"
]
    in RCTView (at View.js:113)
    in View (at TouchableHighlight.js:257)
    in TouchableHighlight (at ListItem.js:98)
    in ListItem (at AllPropertiesScreen.js:129)
    in RCTView (at View.js:113)
    in View (at VirtualizedList.js:1238)
    in CellRenderer (at VirtualizedList.js:463)
    in RCTScrollContentView (at ScrollView.js:707)
    in RCTScrollView (at ScrollView.js:778)
    in ScrollView (at VirtualizedList.js:749)
    in VirtualizedList (at FlatList.js:557)
    in FlatList (at AllPropertiesScreen.js:126)
    in AllPropertiesScreen (created by Connect(AllPropertiesScreen))
    in Connect(AllPropertiesScreen) (at SceneView.js:35)
    in SceneView (at CardStack.js:408)
    in RCTView (at View.js:113)
    in View (at AnimatedImplementation.js:1865)
    in AnimatedComponent (at Card.js:28)
    in Card (at PointerEventsContainer.js:55)
    in Container (at CardStack.js:438)
    in RCTView (at View.js:113)
    in View (at CardStack.js:368)
    in RCTView (at View.js:113)
    in View (at CardStack.js:367)
    in CardStack (at CardStackTransitioner.js:110)
    in RCTView (at View.js:113)
    in View (at Transitioner.js:192)
    in Transitioner (at CardStackTransitioner.js:60)
    in CardStackTransitioner (at StackNavigator.js:48)
    in Unknown (at createNavigator.js:36)
    in Navigator (at createNavigationContainer.js:200)
    in NavigationContainer (at SceneView.js:35)
    in SceneView (at TabView.js:70)
    in RCTView (at View.js:113)
    in View (at TabView.js:69)
    in RCTView (at View.js:113)
    in View (at TabViewPagerPan.js:285)
    in RCTView (at View.js:113)
    in View (at AnimatedImplementation.js:1865)
    in AnimatedComponent (at TabViewPagerPan.js:275)
    in TabViewPagerPan (at TabView.js:133)
    in RCTView (at View.js:113)
    in View (at TabViewAnimated.js:260)
    in TabViewAnimated (at TabView.js:185)
    in TabView (at withCachedChildNavigation.js:60)
    in withCachedChildNavigation(TabView) (at TabNavigator.js:51)
    in Unknown (at createNavigator.js:36)
    in Navigator (at createNavigationContainer.js:200)
    in NavigationContainer (at SceneView.js:35)
    in SceneView (at TabView.js:70)
    in RCTView (at View.js:113)
    in View (at TabView.js:69)
    in RCTView (at View.js:113)
    in View (at TabViewPagerPan.js:285)
    in RCTView (at View.js:113)
    in View (at AnimatedImplementation.js:1865)
    in AnimatedComponent (at TabViewPagerPan.js:275)
    in TabViewPagerPan (at TabView.js:133)
    in RCTView (at View.js:113)
    in View (at TabViewAnimated.js:260)
    in TabViewAnimated (at TabView.js:185)
    in TabView (at withCachedChildNavigation.js:60)
    in withCachedChildNavigation(TabView) (at TabNavigator.js:51)
    in Unknown (at createNavigator.js:36)
    in Navigator (at createNavigationContainer.js:200)
    in NavigationContainer (at App.js:235)
    in RCTView (at View.js:113)
    in View (at App.js:234)
    in Provider (at App.js:233)
    in App (at registerRootComponent.js:36)
    in RootErrorBoundary (at registerRootComponent.js:35)
    in ExpoRootComponent (at renderApplication.js:35)
    in RCTView (at View.js:113)
    in View (at AppContainer.js:100)
    in RCTView (at View.js:113)
    in View (at AppContainer.js:121)
    in AppContainer (at renderApplication.js:34)
11:26:21 AM
▶Warning: Failed prop type: Invalid props.style key `fontFamily` supplied to `View`.
Bad object: {
  "backgroundColor": "white",
  "padding": 20,
  "paddingTop": 20,
  "paddingBottom": 20,
  "fontFamily": "morbi-rounded"
}
Valid keys: [
  "display",
  "width",
  "height",
  "top",
  "left",
  "right",
  "bottom",
  "minWidth",
  "maxWidth",
  "minHeight",
  "maxHeight",
  "margin",
  "marginVertical",
  "marginHorizontal",
  "marginTop",
  "marginBottom",
  "marginLeft",
  "marginRight",
  "padding",
  "paddingVertical",
  "paddingHorizontal",
  "paddingTop",
  "paddingBottom",
  "paddingLeft",
  "paddingRight",
  "borderWidth",
  "borderTopWidth",
  "borderRightWidth",
  "borderBottomWidth",
  "borderLeftWidth",
  "position",
  "flexDirection",
  "flexWrap",
  "justifyContent",
  "alignItems",
  "alignSelf",
  "alignContent",
  "overflow",
  "flex",
  "flexGrow",
  "flexShrink",
  "flexBasis",
  "aspectRatio",
  "zIndex",
  "direction",
  "shadowColor",
  "shadowOffset",
  "shadowOpacity",
  "shadowRadius",
  "transform",
  "transformMatrix",
  "decomposedMatrix",
  "scaleX",
  "scaleY",
  "rotation",
  "translateX",
  "translateY",
  "backfaceVisibility",
  "backgroundColor",
  "borderColor",
  "borderTopColor",
  "borderRightColor",
  "borderBottomColor",
  "borderLeftColor",
  "borderRadius",
  "borderTopLeftRadius",
  "borderTopRightRadius",
  "borderBottomLeftRadius",
  "borderBottomRightRadius",
  "borderStyle",
  "opacity",
  "elevation"
]
    in View (at TouchableHighlight.js:257)
    in TouchableHighlight (at ListItem.js:98)
    in ListItem (at AllPropertiesScreen.js:129)
    in RCTView (at View.js:113)
    in View (at VirtualizedList.js:1238)
    in CellRenderer (at VirtualizedList.js:463)
    in RCTScrollContentView (at ScrollView.js:707)
    in RCTScrollView (at ScrollView.js:778)
    in ScrollView (at VirtualizedList.js:749)
    in VirtualizedList (at FlatList.js:557)
    in FlatList (at AllPropertiesScreen.js:126)
    in AllPropertiesScreen (created by Connect(AllPropertiesScreen))
    in Connect(AllPropertiesScreen) (at SceneView.js:35)
    in SceneView (at CardStack.js:408)
    in RCTView (at View.js:113)
    in View (at AnimatedImplementation.js:1865)
    in AnimatedComponent (at Card.js:28)
    in Card (at PointerEventsContainer.js:55)
    in Container (at CardStack.js:438)
    in RCTView (at View.js:113)
    in View (at CardStack.js:368)
    in RCTView (at View.js:113)
    in View (at CardStack.js:367)
    in CardStack (at CardStackTransitioner.js:110)
    in RCTView (at View.js:113)
    in View (at Transitioner.js:192)
    in Transitioner (at CardStackTransitioner.js:60)
    in CardStackTransitioner (at StackNavigator.js:48)
    in Unknown (at createNavigator.js:36)
    in Navigator (at createNavigationContainer.js:200)
    in NavigationContainer (at SceneView.js:35)
    in SceneView (at TabView.js:70)
    in RCTView (at View.js:113)
    in View (at TabView.js:69)
    in RCTView (at View.js:113)
    in View (at TabViewPagerPan.js:285)
    in RCTView (at View.js:113)
    in View (at AnimatedImplementation.js:1865)
    in AnimatedComponent (at TabViewPagerPan.js:275)
    in TabViewPagerPan (at TabView.js:133)
    in RCTView (at View.js:113)
    in View (at TabViewAnimated.js:260)
    in TabViewAnimated (at TabView.js:185)
    in TabView (at withCachedChildNavigation.js:60)
    in withCachedChildNavigation(TabView) (at TabNavigator.js:51)
    in Unknown (at createNavigator.js:36)
    in Navigator (at createNavigationContainer.js:200)
    in NavigationContainer (at SceneView.js:35)
    in SceneView (at TabView.js:70)
    in RCTView (at View.js:113)
    in View (at TabView.js:69)
    in RCTView (at View.js:113)
    in View (at TabViewPagerPan.js:285)
    in RCTView (at View.js:113)
    in View (at AnimatedImplementation.js:1865)
    in AnimatedComponent (at TabViewPagerPan.js:275)
    in TabViewPagerPan (at TabView.js:133)
    in RCTView (at View.js:113)
    in View (at TabViewAnimated.js:260)
    in TabViewAnimated (at TabView.js:185)
    in TabView (at withCachedChildNavigation.js:60)
    in withCachedChildNavigation(TabView) (at TabNavigator.js:51)
    in Unknown (at createNavigator.js:36)
    in Navigator (at createNavigationContainer.js:200)
    in NavigationContainer (at App.js:235)
    in RCTView (at View.js:113)
    in View (at App.js:234)
    in Provider (at App.js:233)
    in App (at registerRootComponent.js:36)
    in RootErrorBoundary (at registerRootComponent.js:35)
    in ExpoRootComponent (at renderApplication.js:35)
    in RCTView (at View.js:113)
    in View (at AppContainer.js:100)
    in RCTView (at View.js:113)
    in View (at AppContainer.js:121)
    in AppContainer (at renderApplication.js:34)

### Is this a bug report?

(write your answer here)

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.)

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by bartolkaruza** [comment]
You can only set `fontSize` and `fontFamily` styles to a `<Text />` component. There is no way to set the 'global' font. If you want to re-use font styling in multiple places, try wrapping the `<Text/>` component in your custom text component, with those styles applied and then using your custom text instead of the React Native text wherever you want the font applied.

This error indicates that you are trying to add a font related styling to non `Text` components, check your implementation.

**Comment by jpca999** [comment]
I appreciate your response ,, thanks @bartolkaruza   I'll look into it.

**Comment by mintbridge** [comment]
It took me a long time to work this out, but you also get this error when you set a `fontSize` on a `<Text>` component that has a sibling of a `<View>`. For example,

Shows error:
```
 <View>
  <Text style={{fontSize: 16}}>Some Other Text</Text>
  <View>
    ...
  </View>
</View>
```

No error:
```
<View>
  <View>
    <Text style={{fontSize: 16}}>Some Other Text</Text>
  </View>
  <View>
    ...
  </View>
</View>
```

Not sure if this by design or not?

**Comment by jpca999** [comment]
Thanks, nice observation.  this should help...
