### ISSUE TITLE
[Query] Implementing iAd

### ISSUE THREAD

**Issue by steve-ng** [facebook/react-native#1649]
Hi,

I followed the guide on creating a native UI component and tried to create an iAd.

I manage to see iAd and click it. However when I place it inside a scrollview, it is unclickable. any idea why?

**Comment by steve-ng** [comment]
Here's my code

<ScrollView stickyHeaderIndices={[0]} >
  <AdView />
  <View>
    //other view content 
  </View>
</ScrollView>

it work if I just did

<View>
  <AdView />
</View>

**Comment by brentvatne** [comment]
@steve-ng - can you share the code behind the AdView?

**Comment by steve-ng** [comment]
Here's my RCTAdManager.m


    #import <Foundation/Foundation.h>

    #import <iAd/iAd.h>
    #import "RCTViewManager.h"

    @interface RCTAdManager : RCTViewManager <ADBannerViewDelegate>
    @end

    @implementation RCTAdManager

    RCT_EXPORT_MODULE()

    - (UIView *)view
    {
      //ADBannerView *adView = [[ADBannerView alloc] initWithFrame:CGRectZero];
      ADBannerView *adView = [[ADBannerView alloc] initWithFrame:CGRectMake(0, 518, 320, 50)];
      adView.delegate = self;
     return adView;
    }

    #pragma mark AdViewDelegate


    - (void)bannerView:(ADBannerView *)banner didFailToReceiveAdWithError:(NSError *)error{
      NSLog(@"bannerview did not receive any banner due to %@", error);
    }

    - (void)bannerViewActionDidFinish:(ADBannerView *)banner{
      NSLog(@"bannerview was selected");
    }

    - (BOOL)bannerViewActionShouldBegin:(ADBannerView *)banner willLeaveApplication:   (BOOL)willLeave{
      NSLog(@"banner view action should begin");
      return true;
    }

    - (void)bannerViewDidLoadAd:(ADBannerView *)banner {
      NSLog(@"banner was loaded");
    }

    @end

**Comment by steve-ng** [comment]
And here's my AdView.js 


    var React = require('react-native');
    var { requireNativeComponent } = require('react-native');

    class AdView extends React.Component {
      render() {
        return <RCTAd />;
       }
    }

    AdView.propTypes = {};

    var RCTAd = requireNativeComponent('RCTAd', AdView);

    module.exports = AdView;

**Comment by steve-ng** [comment]
i realised that it's because I didn't allocate height for adView.

**Comment by brentvatne** [comment]
Oh, excellent :smile: thanks for the follow up!
