### ISSUE TITLE
Setting `margin: '20'` doesn't log the crash on Android but does on iOS

### ISSUE THREAD

**Issue by joaosardinha** [facebook/react-native#16491]
### Is this a bug report? 

Yes

### Environment

  Environment:
      OS:  Linux 4.10
      Node:  7.10.1
      Yarn:  1.2.1
      npm:  4.2.0
      Watchman:  Not Found
 
### Steps to Reproduce

1. CRNA
2. In any component's style set an attribute with an absolute pixel value in quotes, i.e. "marginLeft: '24'"
3. Run on an Android device from the Expo app
4. Watch it crashing

### Expected Behavior

A crash log indicating why it crashed like a usual error would do.

(Write what you thought would happen.)

Android (25): System's "App has stopped working" dialog, with no log.
iOS: A crash log indicating why it crashed like a usual error would do.
![erorrror](https://user-images.githubusercontent.com/15181917/31863100-9d55f996-b740-11e7-8124-c75757ae7de6.PNG)

**Comment by zibs** [comment]
It looks like you're passing in a string, when it should be a number. `marginRight: 20`, should be sufficient. No need for quotes.
