### ISSUE TITLE
Missing props documentation for some components in react native docs

### ISSUE THREAD

**Issue by AudyOdi** [facebook/react-native#16501]
### Is this a bug report?
Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Steps to Reproduce
in [react native docs](http://facebook.github.io/react-native/), go to 0.48 version and click FlatList, SectionList or VirtualizedList docs and compare it to 0.49 or newer version docs.
 
### Expected Behavior
The props documentation should be the same as it's defined in flow type in src.

### Actual Behavior
You will notice that in 0.49 or newer version, all the props documentation for FlatList and SectionList are missing, except for `numColumns` (in FlatList) and `stickySectionHeadersEnabled` in SectionList. 
![image](https://user-images.githubusercontent.com/11345526/31889308-99a6b1de-b829-11e7-8e50-e48eadb68351.png)
source: https://facebook.github.io/react-native/docs/flatlist.html

![image](https://user-images.githubusercontent.com/11345526/31889322-a5827150-b829-11e7-82f3-6124e41c8aae.png)
source: http://facebook.github.io/react-native/releases/0.48/docs/flatlist.html

My guess is because react-docgen is still expecting 3 params for a React class (`<DefaultProps, Props, State>`). But in the actual react native source, it's using the new style, 2 params (`<Props, State>`). I have confirmed that defining a React component with 3 params will fix the docs issue, but gives me a Flow error.
![image](https://user-images.githubusercontent.com/11345526/31890326-ec9fa348-b82c-11e7-993c-441d14f001e4.png)

source: https://github.com/reactjs/react-docgen

If anyone know what approach should I do to fix this, please let me know. I would love to contribute.
Thank you.

**Comment by hramos** [comment]
Hey! We've made some changes to the docs recently. We are no longer using react-docgen, so you can go ahead and add the missing props directly to the markdown source for each of these components. The docs are now at https://github.com/facebook/react-native-website. Looking forward to seeing you there!

**Comment by AudyOdi** [comment]
@hramos Hi! Thank you for the update. Will look at that and make the PR soon!
