### ISSUE TITLE
[Bridge] RCTBatchedBridge should create the loader early

### ISSUE THREAD

**Issue by jwyld** [facebook/react-native#1651]
Not until -[RCTBatchedBridge initJS] does the loader get created.  There is a fair amount of code which runs between the creation of the bridge and when the loader is actually told to load.  It would be possible for the loader to asynchronously get loading at the same time as the bridge is getting set up.

On an iPhone 5, I'm seeing a waste of 10-15ms while the bridge is stalled waiting for the loader to read the JS off disk.

**Comment by tadeuzagallo** [comment]
Thanks, had just looked into it, should be able to work on it pretty soon :)

**Comment by ide** [comment]
The bridge now loads JS in parallel with module creation -- has this issue been addressed?

**Comment by javache** [comment]
Yes, this should all run in parallel now.
