### ISSUE TITLE
Cannot See Image on Device but showing on Emulator react-native 0.45.1

### ISSUE THREAD

**Issue by AdminDev826** [facebook/react-native#16514]
I have uploaded the image to the web server successfully.
After that I am loading the image datas to the listView.
But the Image is not showing on Device(just white screen) but it shows on Emulator...
If the image is very small, then it shows well on device also.

I am not sure, how can I fix this issue?
Thank you in advance!

**Comment by AdminDev826** [comment]
![image](https://user-images.githubusercontent.com/18238802/31923165-c7eb3d44-b8ab-11e7-88ea-eb2524569a34.png)
![image](https://user-images.githubusercontent.com/18238802/31923201-f2050d8a-b8ab-11e7-9a0b-16cc7ae612eb.png)

**Comment by ntomallen** [comment]
I am getting the same issue for all static images in my app. Everything shows up fine on iOS and an the android emulator, but not on the physical android device. I also have a fastlane beta build that creates a release build for beta, and the images don't show up through that either. I'm on RN 0.51.0, but I also updated to 0.53.3 on a different branch and that didn't solve it either. I've tried multiple cleans, re-installs, etc, but nothing has worked thus far. I've come across several different issues, but can't seem to find a definitive solution.

**Comment by ranadeep47** [comment]
+1 i have the same issue, my image is the renderItem of a FlatList if that matters.

**Comment by SeamusY** [comment]
any updates?

**Comment by sebgam** [comment]
alguien lo soluciono?

**Comment by noahtallen** [comment]
I haven't had the issue recently, but we have cut down on the number of pictures we have. I did also bundle my images through Android Studio / Xcode and reference via `uri` rather than via js import
