### ISSUE TITLE
Stay off my d@mn lawn?

### ISSUE THREAD

**Issue by th317erd** [facebook/react-native#16510]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Controlling polyfills forcing ideologies and telling me how to live my life

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**
It is simple to reproduce, put something in the object prototype chain that is enumerable (which does and can happen all the time... including injection from 3rd party libraries, and creating context objects via Object.create)

**What is the expected behavior?**
Stay off my lawn, stop telling me how to code, and stop doing things the slow way just to tell other people how to do things

**Please provide your exact metro-bundler configuration and mention your metro-bundler, node, yarn/npm version and operating system.**
Simple hello world example + `var a = { test: 'derp' }, b = Object.create(a), c = Object.assign({}, b);`

Your Polyfill for Object.assign (Object.es6.js) is completely backwards, slow, and forcing an ideology. You are DELIBERATELY walking and copying the entire prototype chain, which is slow, and often not desired. The SUPER INSANE part? You are telling me how to live my life, and throwing an exception if there IS an enumerable property in the prototype chain. Forcing people to do things YOUR way is the wrong way. Please update the polyfill to 1) NOT walk the entire chain, 2) NOT tell me how to code.

By the way, I ran into this simply inheriting from EventEmitter, which is SUPER COMMON by the way.

```javascript
// We don't currently support accessors nor proxies. Therefore this
    // copy cannot throw. If we ever supported this then we must handle
    // exceptions and side-effects.
    
    // No SANE person would ever copy an object with `key in obj`
    // please use `Object.keys(obj)` instead, which is much faster, and doesn't involve forced ideologies
    for (var key in nextSource) {
      if (false) { // <--- Add false here... because you don't need to tell me the proper way to code
        var hasOwnProperty = Object.prototype.hasOwnProperty;
        if (!hasOwnProperty.call(nextSource, key)) {
          throw new TypeError(
            'One of the sources for assign has an enumerable key on the ' +
            'prototype chain. Are you trying to assign a prototype property? ' +
            'We don\'t allow it, as this is an edge case that we do not support. ' +
            'This error is a performance optimization and not spec compliant.'
          );
        }
      }
      target[key] = nextSource[key];
    }
```

**Comment by ColeTownsend** [comment]
![image](https://user-images.githubusercontent.com/987654/38378419-a25214f4-38cb-11e8-845c-126625d05d2b.png)
