### ISSUE TITLE
Unable to modify existing RN project to use single index.js entry point (both iOS and Android)

### ISSUE THREAD

**Issue by sunweiyang** [facebook/react-native#16517]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS:  macOS High Sierra 10.13
  Node:  8.6.0
  Yarn:  1.2.0
  npm:  5.5.1
  Watchman:  4.9.0
  Xcode:  Xcode 9.0.1 Build version 9A1004
  Android Studio:  2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: 0.49.3 => 0.49.3

### Steps to Reproduce

(Write your steps here:)

1. Have an existing React Native 0.48 project
2. Upgrade to React Native 0.49.3
3. Rename index.android.js to index.js, and delete index.ios.js
4. Use `jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.bundle?platform=ios&dev=true"];` in AppDelegate.m

### Expected Behavior

My expectation was that RN 0.49.* would know to use index.js as the entry point, but the packager and output suggested that it was still trying to use the old entry points (i.e. index.android.js).

### Actual Behavior

The packager showed this output, suggesting that it was using old entry points:

```
Bundling `index.android.js`  [development, non-minified]  0.0% (0/1), failed.
error: bundling failed: Error
    at DependencyGraph._getAbsolutePath (/Users/sunw/Skale/Repos/skale-react-native/Skale/node_modules/metro-bundler/src/node-haste/DependencyGraph.js:305:11)
    at DependencyGraph.getDependencies (/Users/sunw/Skale/Repos/skale-react-native/Skale/node_modules/metro-bundler/src/node-haste/DependencyGraph.js:283:4236)
    at Resolver.getDependencies (/Users/sunw/Skale/Repos/skale-react-native/Skale/node_modules/metro-bundler/src/Resolver/index.js:129:5)
    at /Users/sunw/Skale/Repos/skale-react-native/Skale/node_modules/metro-bundler/src/Bundler/index.js:642:39
    at Generator.next (<anonymous>)
    at step (/Users/sunw/Skale/Repos/skale-react-native/Skale/node_modules/metro-bundler/src/Bundler/index.js:13:1336)
    at /Users/sunw/Skale/Repos/skale-react-native/Skale/node_modules/metro-bundler/src/Bundler/index.js:13:1496
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Screenshots (Android and iOS, respectively):

![screenshot_1508818289](https://user-images.githubusercontent.com/12490625/31924644-d0f66fd6-b837-11e7-98e2-6efad290fb69.png)

![img_0358](https://user-images.githubusercontent.com/12490625/31924659-e8bcf3ec-b837-11e7-9241-4f95424d79b9.png)

**Comment by 393197906** [comment]
I have the same problem

**Comment by duailibe** [comment]
I had the same problem, which was fixed by deleting the `ios/build/` and `android/app/build/` folders

**Comment by sunweiyang** [comment]
Unfortunately @duailibe, the issue persists even after deleting `ios/build/` and `android/app/build/`.

**Comment by achuvm** [comment]
I'm pretty sure this could've been done prior to the defaulting to only 1 `index.js` file

**For Android**, go to your `Module: app`'s `build.gradle` and add the following above the `apply from: "../../node_modules/react-native/react.gradle"`

```
project.ext.react = [
    entryFile: "index.js"
]
```

**For iOS**, go to your `AppDelegate.m` and change `"index.ios"` to `"index"` in this line:

```
  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];

```

Hope that helps!

**Comment by AishwaryaSurana** [comment]
@achuvm this is not helping as well.

**Comment by achuvm** [comment]
Hi @AishwaryaSurana, 

That's interesting, maybe take a look at my updated answer for iOS, there's possibly another thing you have to change to run from Xcode. Although I was under the impression `react-native run-ios` would essentially build the Xcode project.

**Comment by sunweiyang** [comment]
Thanks @achuvm, your edited comment worked great for me!
