### ISSUE TITLE
TouchableHighlight `onPress` not working when wrapping a `TextInput`

### ISSUE THREAD

**Issue by SandroMachado** [facebook/react-native#16524]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS:  macOS Sierra 10.12.6
  Node:  8.7.0
  Yarn:  0.21.3
  npm:  5.4.2
  Watchman:  4.6.0
  Xcode:  Xcode 8.3.2 Build version 8E2002
  Android Studio:  2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: 0.49.3 => 0.49.3

### Steps to Reproduce

Wrap a `TextInput` in a `TouchableHighlight`

```js
        <TouchableHighlight
          onPress={() => this.props.action()}
          underlayColor="transparent"
        >
          <View style={this.state.styles.inputView}>
              <TextInput
                style={this.state.styles.field}
                underlineColorAndroid="transparent"
               />
          </View>
        </TouchableHighlight>
```

`this.props.action()` is not called on pressing the `TouchableHighlight`.

Replacing the `TextInput` with a `Text`, the `this.props.action()` is called as expected.

```js
        <TouchableHighlight
          onPress={() => this.props.action()}
          underlayColor="transparent"
        >
          <View style={this.state.styles.inputView}>
              <Text>Click here</Text> 
          </View>
        </TouchableHighlight>
```
In this scenario, `this.props.action()` is called on pressing the `TouchableHighlight`.

### Expected Behavior

Pressing the `TouchableHighlight` should call `this.props.action()`.

### Actual Behavior

Pressing the `TouchableHighlight` is not calling `this.props.action()`.

### Reproducible Demo

Just create a screen with this:

```js
        <TouchableHighlight
          onPress={() => console.log("called")}
          underlayColor="transparent"
        >
          <View style={this.state.styles.inputView}>
              <TextInput
                style={this.state.styles.field}
                underlineColorAndroid="transparent"
               />
          </View>
        </TouchableHighlight>
```

**Comment by quyentranvan** [comment]
@SandroMachado Take a look at comment of mrtomhoward 
https://github.com/facebook/react-native/issues/14958

**Comment by SandroMachado** [comment]
@quyentranvan thanks! It worked!

Closed since it is duplicated of https://github.com/facebook/react-native/issues/14958
