### ISSUE TITLE
[Bridge] -[RCTJavaScriptLoader loadBundleAtURL:onComplete:] doesn't need the URL

### ISSUE THREAD

**Issue by jwyld** [facebook/react-native#1652]
The loader is initialized with the bridge.  The URL passed to the load is the bridge's URL.  Unless there is going to be support for loading various bundles using a single loader instance, this could be removed.

**Comment by tadeuzagallo** [comment]
Closing since the implementation has changed and `RCTJavaScriptLoader` doesn't know about the bridge anymore.
