### ISSUE TITLE
'React/RCTTVNavigationEventEmitter.h' file not found

### ISSUE THREAD

**Issue by skyAnja** [facebook/react-native#16528]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS:  macOS Sierra 10.12.6
  Node:  6.10.3
  Yarn:  0.23.4
  npm:  4.6.1
  Watchman:  4.7.0
  Xcode:  Xcode 9.0.1 Build version 9A1004
  Android Studio:  2.3 AI-162.3764568

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.49.3 => 0.49.3

### Steps to Reproduce

MyProject-Bridging-Header.h: 
#import <React/RCTTVNavigationEventEmitter.h>

OR 

MyOwnSuperClass.m
#import <React/RCTTVNavigationEventEmitter.h>

### Expected Behavior

File is found, and RCTTVNavigationEventNotification can be used

### Actual Behavior

`'React/RCTTVNavigationEventEmitter.h' file not found`

`#import <React/RCTBridge.h>` is found

### Additional Information
Target is tvOS

**Comment by dlowder-salesforce** [comment]
This should be fixed in #16076.

**Comment by dlowder-salesforce** [comment]
This is now fixed in #16076 .

**Comment by dlowder-salesforce** [comment]
@skyAnja this should be fixed in #16076, could you please verify and close this?
