### ISSUE TITLE
Uint8Array forEach is undefined when debugger isnt active

### ISSUE THREAD

**Issue by wind0r** [facebook/react-native#16538]
### Is this a bug report?
Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?
Yes

### Environment
Environment:
  OS:  macOS High Sierra 10.13
  Node:  8.7.0
  Yarn:  Not Found
  npm:  5.5.1
  Watchman:  4.9.0
  Xcode:  Xcode 9.0.1 Build version 9A1004
  Android Studio:  2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: 0.49.3 => 0.49.3

and

Environment:
  OS:  Linux 4.9
  Node:  8.6.0
  Yarn:  Not Found
  npm:  5.5.1
  Watchman:  4.9.0
  Xcode:  N/A
  Android Studio:  Not Found

Packages: (wanted => installed)
  react: ^16.0.0-beta.5 => 16.0.0-beta.5
  react-native: ^0.49.3 => 0.49.3

Platform: Android

### Steps to Reproduce
Uint8Array forEach is undefined when remote debugger isnt active
1. git clone https://github.com/wind0r/react-native-uint8array-bug/
2. npm install
3. react-native run-android
4. react-native log-android

Repo uses the init react-native project with just this change: https://github.com/wind0r/react-native-uint8array-bug/blob/master/App.js#L24-L26

### Expected Behavior
adb logcat should return 10 5 8 2 0 0 9

### Actual Behavior
it just reports undefined is not a function.
"funny" part is that is working if remote debugger is active.

### Reproducible Demo
https://github.com/wind0r/react-native-uint8array-bug/

**Comment by ide** [comment]
The remote debugger runs your JS in Chrome, which is a completely different environment than on the phone. The JS VM on the phone doesn't have UInt8Array to begin with, so it's expected that all operations related to it will fail. If you use iOS 10 or 11 it should work though.

**Comment by wind0r** [comment]
Thanks for the explanation :)
I was "confused" that it was working with debugger enabled. 
I simply installed the forEach polyfil and now it is working fine :)
