### ISSUE TITLE
[WebView] Outdated Browser

### ISSUE THREAD

**Issue by clovs** [facebook/react-native#16534]
Hello Every One,

I'm trying to encapsulate a part of a React WebSite.
It's working! but it's display me a warning headband:
"You are using an outdated browser. Please upgrade your browser to improve your experience."

There is a way to improve my WebView by upgrading it?

Thanks by advance 

  Packages:
    "react": "16.0.0-alpha.12",
    "react-native": "0.47.1",

  Target Platform: iOS (8.1 -> 11.0)

**Comment by jorbs** [comment]
Did you found a solution for this issue?

**Comment by clovs** [comment]
The issue wasn't an issue with react-native. 
but was about the user agent check on the website.

you can test user agent check with this plugin for chrome:
https://chrome.google.com/webstore/detail/user-agent-switcher-for-c/djflhoibgkdhkhhcedjiklpkjnoahfmg

Hope it helps
bye

**Comment by jorbs** [comment]
Thanks!
