### ISSUE TITLE
CheckBox renders a box with red borders

### ISSUE THREAD

**Issue by luco** [facebook/react-native#16537]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS:  macOS Sierra 10.12.6
  Node:  6.9.2
  Yarn:  0.23.4
  npm:  3.10.9
  Watchman:  4.7.0
  Xcode:  Xcode 9.0 Build version 9A235
  Android Studio:  2.2 AI-145.3537739

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: 0.49.3 => 0.49.3

### Steps to Reproduce

```
import {
  CheckBox
} from 'react-native';

```
(Write your steps here:)

1. Install 0.49.3
2. Create a project.
3. Import Checkbox

### Expected Behavior

A styled checkbox such as Switch does.

### Actual Behavior

A box with red borders with no actions.

![image](https://user-images.githubusercontent.com/246373/32017585-ef7c99c0-b9a5-11e7-9a07-870922f64b1c.png)

**Comment by timwangdev** [comment]
CheckBox doesn't support iOS. Document was updated in master branch. Please use Switch for iOS.

**Comment by timwangdev** [comment]
@facebook-github-bot answered
