### ISSUE TITLE
Gradle distribution needs to be updated in order to work with JDK v9

### ISSUE THREAD

**Issue by IljaDaderko** [facebook/react-native#16536]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS:  macOS Sierra 10.12.6
  Node:  8.7.0
  Yarn:  1.2.1
  npm:  5.5.1
  Watchman:  4.9.0
  Xcode:  Xcode 9.0.1 Build version 9A1004
  Android Studio:  2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: 0.49.3 => 0.49.3

### Steps to Reproduce

1. Update to JDK version 9+
2. run `react-native run-android`

### Expected Behavior

Should build android files correctly

### Actual Behavior

Errors with following details
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '9.0.1'.
```

Solution seems to be described here: https://discuss.gradle.org/t/could-not-determine-java-version-from-9-0-1/24457 I tried it and got past the error, but had issues when opening project in my android studio, so am not sure if further steps are required.

**Comment by gregogalante** [comment]
Get the same problem

**Comment by gregogalante** [comment]
This work for me:

Edit the file **/android/gradle/wrapper/gradle-wrapper.properties** and update the last line with:

```text
distributionUrl=https\://services.gradle.org/distributions/gradle-4.3-rc-2-all.zip
```

So i update the gradle version used for project dependencies.

**Comment by IljaDaderko** [comment]
Opening project in android studio fixes this by prompting to update gradle version.

**Comment by lndgalante** [comment]
What it works for me was to rollback to Java8

```
brew cask uninstall java
brew tap caskroom/versions
brew cask install java8
```

**Comment by alexanderkjeldaas** [comment]
I don't think any of these workarounds are good.

- Not using java9 is not a solution to not being able to use java9.
- Using gradle 4.3 requires the android gradle plugin 3.0.0+ which requires flavors and other incompatible changes.

**Comment by ilezhnin** [comment]
Same with version '10'. "Could not determine java version from '10'.
"

**Comment by ditsayakul** [comment]
get the same problem
---------------------------------------------------------------
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '10.0.1'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
----------------------------------------------------------------------------
that work for me
`brew cask uninstall java
brew tap caskroom/versions
brew cask install java8`

**Comment by jorwan** [comment]
Same here...

![captura de pantalla 2018-05-18 a la s 2 01 33 p m](https://user-images.githubusercontent.com/875379/40250576-b3846998-5aa4-11e8-9a0b-c2f22196d513.png)

**Comment by wt1098078873** [comment]
For me, I change my java version to java 8. It's work.
This is [Link](https://www.jianshu.com/p/91bbb537fd52) @jorwan @ditsayakul

**Comment by Beamanator** [comment]
I had the error `Could not determine java version from '10.0.2'.`

I followed @alexanderkjeldaas 's advice and upgraded Gradle. This also made me update the minimum sdk version, but now `react-native run-android` smoothly opens the app on the emulator.

I still see the warning `WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html`, but at least the app runs for now

**Comment by ajharry69** [comment]
@Beamanator which gradle version are you using or how did you update your gradle? Am having the exact same error as yours.

**Comment by Beamanator** [comment]
@ajharry69 I'm using the following versions:
Android Studio: 3.1.3 (you didn't ask, but I'm just letting you know)
Emulator: Nexus 5, API level 26
Gradle distributionUrl: https\://services.gradle.org/distributions/gradle-4.4-all.zip
-> Gradle Version: 4.4

**Comment by DixitaSO** [comment]
Gradle refresh failed
Error:Could not resolve all dependencies for configuration ':app:debugAndroidTestRuntimeClasspath'.
Could not determine artifacts for com.android.support.test:runner:1.0.1
Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/support/test/runner/1.0.1/runner-1.0.1.aar'.
Could not HEAD 'https://dl.google.com/dl/android/maven2/com/android/support/test/runner/1.0.1/runner-1.0.1.aar'.
dl.google.com

**Comment by dulmandakh** [comment]
Closing this issue, because RN 0.56 uses gradle 4.x.

**Comment by danielsellergren** [comment]
Same thing but for Java version 11.

    $ react-native run-android
    Scanning folders for symlinks in /Users/[redacted]/Code/[redacted]/node_modules (18ms)
    JS server already running.
    Building and installing the app on the device (cd android && ./gradlew installDebug)...

     FAILURE: Build failed with an exception.

     * What went wrong:
     Could not determine java version from '11'.

Problem solved by changing the line in `gradle-wrapper.properties` to `distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip` which is the latest version as of right now. Still other problems but this solves this one.

**Comment by tmle** [comment]
I follow danielsellergren latest comment installing:
distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip

Got new error when running 'npm run android'

* What went wrong:
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > javax/xml/bind/annotation/XmlSchema
