### ISSUE TITLE
[UIExplorer] App is broken: Attempted to assign readonly property. (ActivityIndicatorIOS.ios.js)

### ISSUE THREAD

**Issue by bparadie** [facebook/react-native#1654]
I synced to commit https://github.com/facebook/react-native/commit/522fd33d6f3c8fb339b0dde35b05df34c1233306, cleaned `UIExplorer` and tried to run it on the simulator using iPhone 5 (8.3). Here is what I got:

![ios simulator screen shot jun 17 2015 10 21 29 am](https://cloud.githubusercontent.com/assets/1578115/8213957/a7746166-14da-11e5-9a84-ba80d25f9872.png)

**Comment by bparadie** [comment]
@vjeux I am still seeing this problem after syncing to the latest commit (https://github.com/facebook/react-native/commit/e47cfb6e3365b381253934a30c543276430ca350).

**Comment by bparadie** [comment]
@vjeux In the debugger I am seeing that `createReactNativeComponentClass` for `RCTView` returns undefined:

```javascript
var RCTView = createReactNativeComponentClass({
  validAttributes: ReactNativeViewAttributes.RCTView,
  uiViewClassName: 'RCTView',
});
```

On the stack I see `var View = require('View');` (line 18) in `ActivityIndicatorIOS.ios.js`.

Then drilling further into `createReactNativeComponentClass`... This line seems to be the trouble maker:

```
  return ((Constructor: any): ReactClass);
```

That doesn't look like JS to me, not even ES6. Is this `flow` syntax? Shouldn't that be transformed?
If I execute that line in the debugger I'll get:

![screen shot 2015-06-21 at 10 16 07 am](https://cloud.githubusercontent.com/assets/1578115/8272603/d0838a1a-17fe-11e5-83ff-c2fc97eb8a6d.png)

I am taking a wild guess here: Is it possible that you guys at FB use a more advanced [flow](http://flowtype.org/) version then the rest of the world? I believe expressions like `(Constructor: any)` should get transformed by your flow tool to proper JS - assuming you have the right flow version. Again, this is just a wild guess. 

Just for clarity, my environment is: OSX 10.10.2, running XCode 6.3.1 and the simulator for iPhone 6 (ios 8.1).

`flow` version is:
```
/usr/local/bin/flow --version
Flow, a static type checker for JavaScript, version 0.12.0
```

Latest flow version is [0.12.0](https://github.com/facebook/flow/releases/tag/v0.12.0).

**Comment by bparadie** [comment]
@vjeux Ah, here is the puppy that messed everything up...
It's a recent commit for `[Flow] Fix or suppress react-native github errors for Flow v0.12.0`, 
https://github.com/facebook/react-native/commit/1acca01aa44d5d2533dd3037428a9c1fdc5a7c91.

![screen shot 2015-06-21 at 10 37 48 am](https://cloud.githubusercontent.com/assets/1578115/8272686/b9e1d084-1801-11e5-87fa-5ec38c22a4c2.png)

@gabelevi @sahrens Do I need a special `flow` version in order to use your 'fix'? I am using 0.12.0.

**Comment by bparadie** [comment]
@vjeux @gabelevi @sahrens @brentvatne Everything works great again after reverting back to `return Constructor`. I don't even see any flow errors with my 0.12.0 version.

Now, this journey brings up a few interesting points:
- react-native has a dependency to `flow`, which is supposed to be installed as a global tool.
- there is no version dependency check in place that would enforce `flow` updates (i.e. this react-native version requires that flow version)
- all react-native windows need to be closed after upgrading `flow`. But it's easy to forget that and then you run into errors that don't look like `flow` problems at all.
- does `flow` allow global `.flowconfig` files? If so you have to anticipate that global `.flowconfig` settings might interfere with local `.flowconfig` settings.


This side note is probably more interesting to @avikchaudhuri, which I had the honor to work with when he was still at Adobe: I find `flow`'s value proposition quite thin in light of having the option of just using Typescript. I've been using Typescript for over a year now and I don't really see a need for `flow`. I gave it a try in one of my projects and it was just too slow and didn't find anything that Typescript wouldn't have flagged. I finally had enough and disabled `flow` altogether by adding these lines to `.flowconfig`:

```
# bparadie flow takes up two minutes.
.*/*.js
```

I am sure `flow` is faster and better now, and I could probably narrow the search scope to a few folders I care about. But why going through the trouble of re-enabling flow? To make a fair offer, I could be persuaded to try `flow` again if I were presented, say, 3 examples where `flow` would find something suspicious, or questionable, that Typescript would not detect. So far it has been rather the other way around for me (Typescript found more than flow). I am not interested in flow enhancements that are essentially syntactic sugar improvements, along the lines of "you don't have to specify the type here, we'll figure that out". I don't mind spelling out the types. Besides: Typescript is pretty good at inferring the types, too.

**Comment by satya164** [comment]
Closing this as this is an old issue and seems to be fixed. Let's reopen if you still have the issue.
