### ISSUE TITLE
The use of postMessage will lead to WebView onLoadStart run Twice,

### ISSUE THREAD

**Issue by TrustTheBoy** [facebook/react-native#16547]
### Is this a bug report?  
> Yes
### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?
> Yes
### Environment
 > OS:  macOS Sierra 10.12.6
Node:  v7.10.0
Yarn:  0.27.5
npm:  4.2.0
Watchman:  4.7.0
Xcode:  Xcode Version 9.1 beta (9B37) 
Android Studio:  2.3 
react-native: 0.48.4
react: 16.0.0-alpha.12
Target Platform: iOS (8-11.1) android(4.4.4-8.0)  

### Steps to Reproduce
 1.
```javascript
messtest = e => {
  const message = e.nativeEvent.data
  alert(message)
}
```
2.
```jsx
<WebView
  ref={w => this.webview = w}
  source={{uri:jumpUrl}}
  onMessage={this.messtest}
  domStorageEnabled={true}
  javaScriptEnabled={true}
  startInLoadingState={true}
  dataDetectorTypes="none"
  onLoadEnd={()=>{
    console.log('load end... onLoadEnd function');
  }}
  onLoadStart={()=>{
    console.log('load start..');
  }}
  renderLoading={this._renderLoading}
  //onNavigationStateChange={this.onNavigationStateChange}
/>
```
![image](https://user-images.githubusercontent.com/20201085/32039573-f34cd0f8-b9f3-11e7-8e61-1ba1b39f8db5.png)

### Expected Behavior
LoadStart should be executed before loadEnd,As you can see from the diagram, `load end... ` re executes `load start `, and then does not execute `load end`, which causes the state to be updated. It has always been `load start`

**Comment by jojol** [comment]
same issue, received duplicate message...

**Comment by jayshah123** [comment]
Yes, post message seems to change location/url of the window and hence resulting in multiple calls to onLoad, is there any way to avoid this?

**Comment by reedspool** [comment]
I do not have an answer, but I have found offending code which proves the assumptions https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/webview/ReactWebViewManager.java#L578

**Comment by TrustTheBoy** [comment]
Unresolved, the problem still exists

**Comment by tedscape** [comment]
The problem still exists.

**Comment by jamonholmgren** [comment]
This issue has been migrated to https://github.com/react-native-community/react-native-webview/issues/9 and can be closed.

**Comment by Titozzz** [comment]
Closing in favor of new repo. Please keep discussing there :rocket:
