### ISSUE TITLE
ReactNativeJS: Requiring unknown module "./locale/en-US" on release build

### ISSUE THREAD

**Issue by mlescaudron** [facebook/react-native#16540]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS:  Linux 4.10
  Node:  6.10.3
  Yarn:  0.24.4
  npm:  3.10.10
  Watchman:  Not Found
  Xcode:  Not Found
  Android Studio:  Not Found (I'm using docker)

Packages: (wanted => installed)
  react-native: 0.48.4 => 0.48.4

### My error

I am using I18n to translate the app, but I have the following error only when I build the assets : 
(I don't know if the error is due to I18n)
```
0-26 09:56:58.545 19105 19161 E ReactNativeJS: Requiring unknown module "./locale/en-US".
10-26 09:56:58.552 19105 19161 E ReactNativeJS: Requiring unknown module "./locale/en-us".
10-26 09:56:58.561 19105 19162 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
10-26 09:56:58.561 19105 19162 E AndroidRuntime: Process: com.nelio, PID: 19105
10-26 09:56:58.561 19105 19162 E AndroidRuntime: com.facebook.react.common.JavascriptException: Requiring unknown module "./locale/en-US"., stack:
10-26 09:56:58.561 19105 19162 E AndroidRuntime: o@2:783
10-26 09:56:58.561 19105 19162 E AndroidRuntime: n@2:426
...
```

My steps : 
```
m -rf node_modules
yarn install
react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
react-native run-android --variant=release
```

And the app crash when I launched it. Not in debug mode.
Do you have any idea how to add this module ? Manually or automatically ?

**Comment by showcheap** [comment]
Any update?

**Comment by kyo504** [comment]
I had the same problem after updating moment-related packages.

moment : 2.19.1 => 2.19.2
moment-timezone : 0.5.13 => 0.5.14
I don't know what the problem is exactly but after downgrading versions it works fine. Hope this helps you.

**Comment by JanithaR** [comment]
I don't understand what am I suppose to do to fix this. Should I be adding `import 'moment/locale/en-us';` ? I only see 

> en-au, en-ca, en-gb, en-ie, en-nz

 in the locale folder.
