### ISSUE TITLE
[Navigator] SceneConfigs: PushFromRight and FloatFromRight seem to do the same type of animation

### ISSUE THREAD

**Issue by jaygarcia** [facebook/react-native#1655]
Is one deprecated?
Demo:

![woot](https://cloud.githubusercontent.com/assets/180031/8217105/23f026b6-1509-11e5-9d11-1e2d23739700.gif)

**Comment by chirag04** [comment]
was transitionType ever supported? Shouldn't it be sceneConfig below component?

**Comment by ericvicenti** [comment]
Sorry for the confusion. Right now they both have the `FloatFromRight` behavior.

We were intending to make the `PushFromRight` animation visually match the animation in `NavigatorIOS`. Unfortunately we never got around to it. For now, use `FloatFromRight`, and it won't change in the future.

We would accept a PR if anybody wants to re-configure `PushFromRight` to match the native navigation controller.

**Comment by neciu** [comment]
Here you can find my pull request addressing this issue: https://github.com/facebook/react-native/pull/5061

**Comment by neciu** [comment]
I made another pull request hoping this time it will pass the tests: https://github.com/facebook/react-native/pull/5723

Unfortunately I got error:
> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
> 
> The build has been terminated

Can someone help me with this? @hoodsy @ericvicenti

**Comment by mikeygee** [comment]
@neciu's solution looks good to me. The animation matches up better with NavigatorIOS. Any chance we could get some help with merging his PR?

**Comment by neciu** [comment]
@mikeygee thanks. 
Here you can find the patch I'm using in my project: https://gist.github.com/neciu/391127f1f70b3eb69adf

**Comment by mikeygee** [comment]
Just saw this: https://github.com/ericvicenti/navigation-rfc/blob/master/Docs/NavigationOverview.md. I guess the navigator is getting replaced with a new one, so no point in updating this one.

**Comment by grabbou** [comment]
https://github.com/facebook/react-native/commit/9a82c03e1f3415e255c5936aa2c35f0fd006a785

Looks like merged few days ago and issue wasn't closed automatically.
