### ISSUE TITLE
3D Touch not working?

### ISSUE THREAD

**Issue by getnashty** [facebook/react-native#16556]
### Is this a bug report?
Yes

### Environment

  Environment:
    OS:  macOS Sierra 10.12.6
    Node:  7.6.0
    Yarn:  0.27.5
    npm:  4.1.2
    Watchman:  4.7.0
    Xcode:  Xcode 8.3.2

  Packages: (wanted => installed)
    react-native: 0.43.4
    react: 16.0.0-alpha.6

  Target Platform: iOS (10.3)

### Steps to Reproduce

1. build a new component, add `force: 0` to the component's state
2. Make a view, give it these attributes:
``` 
onStartShouldSetResponder={() => true}
onResponderMove={(event) => {
     this.setState({force: event.nativeEvent.force})
 }}
onResponderRelease={(event) => this.setState({force: 0})}
```
3. Style the view to be visible, and large enough to tap
4. Place a <Text> element in the view, with `{this.state.force.toFixed(3)}`
5. Build on an iOS device (6 or greater)
6. Try to force touch the View

### Expected Behavior

I followed the documentation in this commit. I haven't been able to find anything else with my google-fu about 3d touch or force touch with ReactNative: https://github.com/facebook/react-native/commit/f685878938b59f858dc65b8e5e873045a25ccf79

### Actual Behavior

Force stays at 0.000

**Comment by hramos** [comment]
Can you check this is still the case on a more recent RN version?

**Comment by getnashty** [comment]
Dang, you're right @hramos — it _does_ work with the latest version of RN
