### ISSUE TITLE
Fetch with request body

### ISSUE THREAD

**Issue by sm2017** [facebook/react-native#16575]
### Is this a bug report
May be 

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

    OS:  Windows 10
    Node: v8.1.3
    Yarn:  1.2.0
    npm:  5.0.3
    Watchman: Not Found
    Xcode:  Not Found
    Android Studio:  2.3.3

    Packages: (wanted => installed)
        react-native: 0.49.3 => 0.49.3
        react: 16.0.0-alpha.12 => 16.0.0-alpha.12

    Target Platform: Android 7

### Steps to Reproduce

I don't know it's a bug or my mistake . How can I send a http request with binary body?

As both `XMLHttpRequest` and `fetch` is using `NetworkingModule::sendRequest` , so the following codes

```js
fetch('https://mywebsite.com/endpoint/', {
  method: 'POST',
  body: new Uint8Array([1,2,3,4,5,6,7,8,9])
})
```

```js
var request = new XMLHttpRequest();
request.onreadystatechange = (e) => {
  if (request.readyState !== 4) {
    return;
  }

  if (request.status === 200) {
    console.log('success', request.responseText);
  } else {
    console.warn('error');
  }
};

request.open('GET', 'https://mywebsite.com/endpoint/');
request.send(new Uint8Array([1,2,3,4,5,6,7,8,9]));
```

is correct according to

https://github.com/facebook/react-native/blob/master/Libraries/Network/XMLHttpRequest.js#L508

Type of `data` is `RequestBody` and can be
```js
type RequestBody =
    string
  | FormData
  | {uri: string}
  | ArrayBuffer
  | $ArrayBufferView
;
```
But not work's. Fetch don't send request

Here https://docs.postman-echo.com we have an  echo test server

### Expected Behavior

Send http request with binary body

### Actual Behavior

No http request is send

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by Kureev** [comment]
Unfortunately, there is no out-of-box way to send binary data in React Native. You may track PR progress here: https://github.com/facebook/react-native/pull/11573

**Comment by Kureev** [comment]
@facebook-github-bot answered

**Comment by sm2017** [comment]
@Kureev So why RequestBody accept ArrayBufferView?

**Comment by sm2017** [comment]
@Kureev I don't want send Blob just I want put an array buffer in http request body

**Comment by sm2017** [comment]
I believe that here is android implementation
https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/modules/network/NetworkingModule.java#L274
