### ISSUE TITLE
react native bundle no any response

### ISSUE THREAD

**Issue by jiazil** [facebook/react-native#16578]
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

yes

### Environment
Environment:
  OS:  macOS High Sierra 10.13
  Node:  8.7.0
  Yarn:  1.2.1
  npm:  5.4.2
  Watchman:  4.9.0
  Xcode:  Xcode 9.0.1 Build version 9A1004
  Android Studio:  2.3 AI-162.4069837

Packages: (wanted => installed)
   "react": "~15.4.1",
    "react-native": "0.42.0",

### Steps to Reproduce

(Write your steps here:)

1.react-native bundle --entry-file index.ios.js --platform ios --dev false --bundle-output release_ios/main.jsbundle --assets-dest release_ios/
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo
react-native bundle --entry-file index.ios.js --platform ios --dev false --bundle-output release_ios/main.jsbundle --assets-dest release_ios/

no any response

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by timwangdev** [comment]
The procedure looks normal and we need more information for the problem. I'm going to close this issue. Feel free to open a new one and follow the issue template.

**Comment by timwangdev** [comment]
@facebook-github-bot no-template
