### ISSUE TITLE
Android statusbar not translucent after deep link

### ISSUE THREAD

**Issue by umaulana** [facebook/react-native#16582]
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

no

### Steps to Reproduce

1. Create new react native app
2. Make statusbar translucent
```
      <View style={styles.container}>
        <StatusBar
          translucent
          backgroundColor='transparent'
        />
```
3. Add deep link to androidManifest.xml
```
        <intent-filter>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="testapp" android:host="testapp" />
        </intent-filter>
```
4. Make on press handler to handle deep linking
```
        <Text onPress={() => Linking.openURL('testapp://testapp')} style={styles.welcome}>
          Welcome to React Native!
        </Text>
```
5. Press that text

### Expected Behavior

Android statusbar will stay translucent

### Actual Behavior

Android statusbar not translucent anymore

statusbar translucent
![screenshot_2017-10-28-23-00-05-029_com testapp](https://user-images.githubusercontent.com/9917335/32136279-3483a0ee-bbfa-11e7-9f49-eaed50538a67.png)

statubar not translucent
![screenshot_2017-10-28-23-00-11-595_com testapp](https://user-images.githubusercontent.com/9917335/32136280-3d0376ae-bbfa-11e7-8420-225848a24079.png)

**Comment by adrianomelo** [comment]
Hi, @umaulana!

Thank you for reporting the problem. I tried to reproduce the issue but deep linking doesn't seem to affect status bar. Please, double check if the logic of your app is correct. I recommend you to create a self-contained project to reproduce this issue. If you can reproduce it using this self-contained project, please, share it with us :)

Here are the files of my test case: https://gist.github.com/adrianomelo/f45c47d7cfeab604cfa2936fb8784f3c

Environment:
 - Nexus 6p
 - Android O
 - React Native 0.49

**Comment by umaulana** [comment]
@adrianomelo this is what I got from your code

![ezgif-1-316dcf4f98](https://user-images.githubusercontent.com/9917335/32164701-34a2fcbe-bd58-11e7-85b6-91258456d671.gif)

it looks like this code is never called
```
   _handleOpenURL(event) {
     console.log(event)
     this.setState(() => ({url: event.url}))
   }
```
I tried to add console log but nothing shows up

that gif is when I pressed url1 then I pressed url2, then I press back button and press back button again. Is it correct behavior?

my environtment:

- xiomi redmi 4x

- Android 6.0.1 (Marshmallow)

- React Naive (0.49)

**Comment by adrianomelo** [comment]
It looks like it is creating a new activity. The AndroidManifest.xml from this example had `android:launchMode="singleTask"` to prevent it.

I have noticed that the first screen has the correct status bar color, but when you open one of the links, the color of the status bar changes.

**Comment by umaulana** [comment]
@adrianomelo yeah I forgot about `android:launchMode="singleTask"`, sorry my bad.
 So if it is not single task, is it right behavior?, I mean translucent is always be there, even if it opens new activity, shouldn't it stays translucent?

**Comment by adrianomelo** [comment]
No worries, I hope that using `android:launchMode="singleTask"` solves the problem of your application.

I agree with you. The status bar should stay translucent. I will investigate this problem, but it might take some time. I have just started to contribute to this project on my spare time.

If you have the time to debug it, [this code](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/modules/statusbar/StatusBarModule.java) is a good place to start.

And it doesn't look like a critical bug, given that most of the people are probably using `android:launchMode="singleTask"` with deep linking.

**Comment by umaulana** [comment]
@adrianomelo sure I will check that code and thanks for your reponses 👍
