### ISSUE TITLE
RCTShadow Text is broken; there is no layoutDirectionProperty.

### ISSUE THREAD

**Issue by misbell** [facebook/react-native#16589]
Now, then.

RCTShadowText.m is broken. Some code thinks there is a self.layoutDirection property on RCTShadowText class, and yet it doesn't exist. Result is, any Xcode app using 5.0 and referencing the Text project crashes.

**Comment by heikkimantere** [comment]
I'm encountering the same problem when trying to build for release. 

```
Compile RCTShadowText.m
Property 'layoutDirection' not found on object of type 'RCTShadowText *
```

In RCTShadowText.m there's three times a line like this:
`_cachedLayoutDirection == self.layoutDirection`

**Comment by readthecodes** [comment]
I have the same problem! after upgrade react-native v0.48.4 to v0.51

**Comment by sajsanghvi** [comment]
any solutions?

**Comment by vvkaghera** [comment]
Same issue. Any solution?

**Comment by woshicezai** [comment]
any solutions?
