### ISSUE TITLE
URL class is undefined only with remote debugger off

### ISSUE THREAD

**Issue by neuberoliveira** [facebook/react-native#16599]
### Is this a bug report?
maybe

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?
no

### Environment
 Environment:
    OS:  macOS Sierra 10.12.6
    Node:  v6.11.1
    Yarn:  0.27.5
    npm:  5.4.2
    Watchman:  4.7.0
    Xcode:  Xcode 9.1
    Android Studio:  2.3

  Packages: (wanted => installed)
    "react-native": "0.45.1",
    "react": "16.0.0-alpha.12",

  Target Platform: iOS (11.0.1) Android (5.1)

### Steps to Reproduce
The curious is that this error only occur while remote debugger is off, if its on everthing works fine.

1. Turn off remote debugger
2. `var url = new URL('https://facebook.github.io/react-native');`

Same code work if remote debuger is turned on
![simulator screen shot - iphone 5s 11 0 1 - 2017-10-30 at 11 58 02](https://user-images.githubusercontent.com/3378304/32175762-06c4484c-bd6d-11e7-9af3-eec1f4ec3fa6.png)

### Expected Behavior
A new instance of `URL()` class like [documented in mozila](https://developer.mozilla.org/en-US/docs/Web/API/URL) and the [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) from the `searchParams` property

### Actual Behavior
`URL is undefined` so everything messup

Why this happens? I think all js apis are supposed to work, and most weird it only work when debugger is on.

**Comment by timwangdev** [comment]
`URL()` is Web API and not available in pure js Environment (JavaScriptCore in your device). When you're using remote debugger, the host environment is your Chrome browser which have those APIs and you should not rely on that.
You may want to have add a `URL` polyfill [example](https://github.com/github/url-polyfill) to your project.

**Comment by timwangdev** [comment]
@facebook-github-bot expected
