### ISSUE TITLE
[Android] Very high memory usage. App becomes very laggy!

### ISSUE THREAD

**Issue by kesha-antonov** [facebook/react-native#16590]
Hello! I have an app with not very complex UI. But with lots of code. And it takes a lot of memory in android. And becomes very laggy after few screens loaded. In iOS code works without any lag in dev/prod modes.

### Is this a bug report?

Yes. In iOS same code works great whether is in dev mode or production mode.

**Here's memory usage without remote debugger turned on:**
<img width="704" alt="dumpsys_without_remote_debugger copy" src="https://user-images.githubusercontent.com/11584712/32142699-a40528f8-bcad-11e7-9dab-35e92f18a42e.png">

**Here's memory usage with remote debugger turned on (see memory usage reduced):**
<img width="703" alt="dumpsys_with_remote_debugger copy" src="https://user-images.githubusercontent.com/11584712/32142700-b2b1341e-bcad-11e7-8d33-750fa5106a94.png">

**Even if I reduce views - memory usage is still high:**
<img width="696" alt="dumpsys_with_remote_debugger_reduced_views" src="https://user-images.githubusercontent.com/11584712/32143167-9003dcba-bcb6-11e7-8ff5-7318e3851cd2.png">

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes.

### Environment

Environment:
  OS:  macOS High Sierra 10.13
  Node:  6.11.3
  Yarn:  Not Found
  npm:  5.4.2
  Watchman:  4.9.0
  Xcode:  Xcode 9.0 Build version 9A235
  Android Studio:  2.3 AI-162.3871768

Packages: (wanted => installed)
  react: ^16.0.0 => 16.0.0
  react-native: github:facebook/react-native#60c898d8643daf80ef8175af7dc8411709eff379 => 1000.0.0

RN -  0.50-rc

### Steps to Reproduce

1. ```git clone https://github.com/kesha-antonov/rn_memory_usage_test_high_usage```
2. ```cd rn_memory_usage_test_high_usage```
3. ```npm i```
4. ```nano node_modules/react-native-sentry/android/build.gradle```
5. Change sdk tools to 
```
    compileSdkVersion 25
    buildToolsVersion '25.0.3'
```
6. Set your android ndk, sdk paths in ```androids/local.properties```
7. ```react-native run-android```
8. ```adb shell dumpsys meminfo com.rn_memory_usage_test_high_usage```
9. See a lot of memory used (115 MB and above with just 21 (!!!) views, 125.5 MB with 126 useless views)

<img width="847" alt="screen shot 2017-10-29 at 22 11 06" src="https://user-images.githubusercontent.com/11584712/32147300-19973c08-bcf6-11e7-81d0-821df1322ed0.png">

<img width="841" alt="screen shot 2017-10-29 at 23 49 48" src="https://user-images.githubusercontent.com/11584712/32148189-04196afa-bd04-11e7-84ed-850f08613dd2.png">

### Expected Behavior

25-75 MB of memory usage will be fine I guess.
With no lags, no frame drops

### Actual Behavior

A lot of memory used: 165-261 MB
Users experience good look of first screen and when they go through the app it becomes laggy

### Reproducible Demo

https://github.com/kesha-antonov/rn_memory_usage_test_high_usage

**Comment by kesha-antonov** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/11584712/32323193-3c8bd734-bfd8-11e7-8e5c-04eca5fa6780.gif)

**Comment by kesha-antonov** [comment]
Anybody?

@javache @ide @hramos

**Comment by kesha-antonov** [comment]
I even see growing memory in sample app https://github.com/facebook/react-native/issues/16600

**Comment by kesha-antonov** [comment]
Maybe related https://github.com/facebook/react-native/issues/16732

**Comment by lhfiii** [comment]
Resolved? How? @kesha-antonov

**Comment by kesha-antonov** [comment]
Unfortunately now. Still very high memory usage @lhfiii

**Comment by lhfiii** [comment]
@kesha-antonov It may be related with memory leak. Try to display a number of image with FlatList. Even close the activity does not help. Especially on android 4

**Comment by lhfiii** [comment]
I have replace fresco with glide and the leak still exists. It seems that the leak comes from other native module. I have found a lot of YogaNode in the FinalizeReference chain.

**Comment by droidwolf** [comment]
YogaNodePool.get().clear(); release reference.

**Comment by kesha-antonov** [comment]
Hello @droidwolf !
Where to put it?

**Comment by droidwolf** [comment]
activity onDestory

**Comment by pavanmehta91** [comment]
Could you guide where to put it? and where's Activity onDestory()?

**Comment by 1c7** [comment]
still unsolved? my RN 0.52 app also take huge chunk memory then just crash 
( on certain model of qihoo 360 phone, not all of them)

my app use `react-native-image-crop-picker` to choose multiple image and display them with `<Image>` in a `<FlatList>`

**Comment by tehong** [comment]
@kesha-antonov @droidwolf @1c7 @pavanmehta91 
Has anyone resolved this problem.  I also used ```react-native-image-crop-picker``` but I'm not sure that's related.   My memory usage grows to 478MB from 250MB initially.

**Comment by 1c7** [comment]
@tehong 
nope, 
I give up on this problem and decide not to waste more time on it.

I open an issue about this: https://github.com/facebook/react-native/issues/17801
and wrote demo app: https://github.com/1c7/react-native-image-memory-problem-demo-app
and a video using that demo app: https://youtu.be/Vgq-P826aqw

I am not an RN expert/mobile dev expert, so I can't solve this myself.
good luck with your project :D @tehong

**Comment by kesha-antonov** [comment]
Same as @1c7

**Comment by kelset** [comment]
Hi folks, going to close this in favour of #13413, so that we avoid redundancy - the core team is aware of this Android+Flat/SectionList+Images issue (going to write a follow up there).

**Comment by rahulnpadalkar** [comment]
@kesha-antonov which profiling tool is it. Looks really cool. Sorry new to react native.

**Comment by kesha-antonov** [comment]
@rahulnpadalkar It's Android Studio
