### ISSUE TITLE
Android status bar style forcibly changes to light content when a transparent modal is open 

### ISSUE THREAD

**Issue by mRokita** [facebook/react-native#16597]
### Is this a bug report?
Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Steps to Reproduce

1. Create a blank app.
2. Add some transparent modal and a StatusBar with barStyle="dark-content"
```
<StatusBar
    backgroundColor="#EEEEEE"
    barStyle="dark-content" />
```
3. Add some modal  with transparent=true
```
<Modal visible={this.state.modal_visible}  animationType={'slide'} transparent={true} onShow={() => {console.log('show');}} onRequestClose={() => {alert("Modal has been closed.")}}></Modal>
```
4. Add some button to open the modal or simply set visible to true.

### Expected Behavior

The barStyle should be still "dark-content", like this:
![image](https://user-images.githubusercontent.com/10209201/32169301-41440874-bd70-11e7-81e3-bbdf7306214b.png)

### Actual Behavior
It becomes "light-content" 
![image](https://user-images.githubusercontent.com/10209201/32169325-57407536-bd70-11e7-8717-a718678ad67e.png)

### Reproducible Demo

Reproduction should be pretty easy, I couldn't get the barStyle prop working at snack.expo.io though.
I will try to provide a demo later.
I believe that the example provided above is clear enough though.

**Comment by mRokita** [comment]
Also, everything works as expected when I use light-content all the time.

**Comment by llamaluvr** [comment]
This is still an issue as of React 51 (what I could demonstrate on Expo Snack).

Here is a snack that reproduces the issue: https://snack.expo.io/BJQKFvRVG. You'll notice that when you open the modal, the status bar goes white. What color is actually changes to seems to depend on the background color of the original view, but it does seem to always change color. If you take the transparent flag off of the Modal, it's no longer an issue (of course, it's also no longer transparent).

![screenshot_20180118-133909](https://user-images.githubusercontent.com/8053974/35115238-8b7df12e-fc55-11e7-871a-4a40b47b3e94.png)

This issue affects a lot of downstream libraries, and basically any attempt to overlay content from a child (think dropdown menus, dialogs, picker controls) doesn't look right in Android as a result.

**Comment by llamaluvr** [comment]
Some additional information - some of reported that this does not happen on their devices. As best I can tell, it's related to the Android version. A stock Android 6.0 emulator experiences the issue while a stock Android 7.0 emulator does not.

**Comment by Soontao** [comment]
Happened on my android 7.0 real device

**Comment by mRokita** [comment]
I'm running Android 7.0 on my Xperia Z5 Compact and it still happens
