### ISSUE TITLE
index.android.js and index.ios.js should be unified also in build.gradle and iOS build file

### ISSUE THREAD

**Issue by giacomocerquone** [facebook/react-native#16594]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS:  Windows 10
  Node:  8.5.0
  Yarn:  1.2.1
  npm:  5.5.1
  Watchman:  Not Found
  Xcode:  N/A
  Android Studio:  Version  2.3.0.0 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: 0.49.5 => 0.49.5

### Steps to Reproduce

(Write your steps here:)

1. react-native init
2. cd android && ./gradlew assembleRelease

### Expected Behavior

Assemble release should go fine but...

### Actual Behavior

I receive: `Cannot find entry file index.android.js in any of the roots:`

And this is because (in case of android) after the **upgrade with react-native-git-upgrade**, the build gradle file didn't change and the entry file is specified as below:

```
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",

**Comment by giacomocerquone** [comment]
Actually modifying the file android/app/build.gradle doesn't even work... What this could be?

**Comment by dannycochran** [comment]
Experiencing the same issue after upgrading from 0.48.3 -> 0.49.5.

I removed index.ios.js and index.android.js in favor of just "index.js", and changed this my react entry file point:

```
project.ext.react = [
    entryFile: "index.js"
]
```

Some other fixes I've seen have suggested running react-native start with "reset-cache", but that did not work for me either.

**Comment by giacomocerquone** [comment]
I tried reset-cache too but it didn't work

**Comment by Jp3rd** [comment]
add this code inside the method "mReactNativeHost" of the MainApplication.java file.

```java
@Override
 protected String getJSMainModuleName() {
        return "index";
 }

**Comment by udarts** [comment]
I have the same issue, on android I get the same error message: "Cannot find entry file index.android.js in any of the roots:".
Tried adding that line of code, but didn't work. I think I have tried everything mentioned on this topic but still no luck.

**Comment by giacomocerquone** [comment]
@Jp3rd That didn't help, that method was even already there and it still has problems building my apk for release.
Any clue?

**Comment by Kay-Zee** [comment]
Same issue here. Have both 

```
project.ext.react = [
    entryFile: "index.js"
]
```
and

```java
@Override
 protected String getJSMainModuleName() {
        return "index";
 }
```

and running with `start --reset-cache` but still not working, anyone have any ideas?

**Comment by fiznool** [comment]
I've found that you need both the changes to the `build.gradle` file and your `MainApplication.java` file for this to work, and it's also important **where** you put these in the two files.

**build.gradle**

Put the following in your `android/app/build.gradle` file, **above** the line that contains `apply from: "../../node_modules/react-native/react.gradle`

```
project.ext.react = [
    entryFile: "index.js"
]
```

Make sure you use the correct `build.gradle` file - you want the one **inside** the `app` folder.

**MainApplication.java**

Put the following in your `MainApplication.java` file, which will be located inside a subdirectory tree in the `android/app/src` folder:

``` java
@Override
protected String getJSMainModuleName() {
  return "index";
}
```

This needs to live **inside** the call to `new ReactNativeHost(this)`.

**Comment by giacomocerquone** [comment]
Still no fix for this? Updated rn to 0.51.0 and it still gives me troubles

**Comment by sapjax** [comment]
@fiznool  not work for me ☹️

**Comment by ziyafenn** [comment]
@fiznool i'm always getting `Execution failed for task ':app:compileDebugJavaWithJavac'.`

Don't know what to do anymore...
