### ISSUE TITLE
Android gif bug

### ISSUE THREAD

**Issue by wuyunqiang** [facebook/react-native#16604]
### Is this a bug report?
YES.
### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?
YES

### Environment

    OS:  macOS Sierra 10.12.6
    Node:  8.3.0
    Yarn:  0.27.5
    npm:  5.5.1
    Xcode:  Xcode9.01 Build version 9a1004
    Android Studio:  2.3.3 
    react-native: 0.49.3
    react: 16.0.0-beta.5

### Steps to Reproduce
1:gradle:
```
dependencies {
    compile project(':react-native-svg')
    compile project(':react-native-fetch-blob')
    compile project(':react-native-device-info')
    compile project(':react-native-vector-icons')
    compile project(':react-native-code-push')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile 'com.facebook.fresco:animated-gif:0.14.1'
    compile "com.android.support:appcompat-v7:25.2.0"
    compile "com.facebook.react:react-native:+"  // From node_modules
}
```
2:react-native run-android and crash.

### Expected Behavior
like ios.

### Actual Behavior
<img width="1072" alt="gifandorid" src="https://user-images.githubusercontent.com/13480948/32204430-1a82dd8c-be24-11e7-9899-21215e12b29e.png">

**Comment by wuyunqiang** [comment]
must be set 
 compile 'com.facebook.fresco:fresco:1.5.0'
 compile 'com.facebook.fresco:animated-gif:1.5.0'
for rn0.49.3

**Comment by ethan6077** [comment]
@wuyunqiang Thanks, it works on me.
