### ISSUE TITLE
[Android][Bug] Memory grows over time in sample app

### ISSUE THREAD

**Issue by kesha-antonov** [facebook/react-native#16600]
Hello!

I've noticed that memory grows over time with no reason. In my app I see significant growth. In sample app is lower. But still.
It grows over limit. And then starts again and never stops to grow.

What's the reason?

Here's video:

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/11584712/32195278-e7cf3ab2-bdcd-11e7-870d-5a724d3f35d7.gif)

### Is this a bug report?

Yes.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS:  macOS High Sierra 10.13
  Node:  6.11.3
  Yarn:  Not Found
  npm:  5.4.2
  Watchman:  4.9.0
  Xcode:  Xcode 9.0 Build version 9A235
  Android Studio:  2.3 AI-162.3871768

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: 0.49.5 => 0.49.5

### Steps to Reproduce

1. Create sample RN app
2. Open Android studio - Android monitor
3. See memory usage grows over time

### Expected Behavior

Not growing memory

### Actual Behavior

Memory grows over time.

### Reproducible Demo

No need. Just use sample app

**Comment by kesha-antonov** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/11584712/32323227-59e5b570-bfd8-11e7-8bba-bc6194a7b6cc.gif)

**Comment by yinghang** [comment]
@kesha-antonov Can you try running `0.50.0-rc.2` and see if it still happens? I've been running the sample app (with constant but simple network calls)  on `0.50.0-rc.2` for > 12 hours and my memory graph still looks pretty flat. 

<img width="1344" alt="screen shot 2017-11-03 at 9 35 55 am" src="https://user-images.githubusercontent.com/4490352/32376181-6c972df0-c07a-11e7-8a1c-dd2e8eb2e889.png">

**Comment by yinghang** [comment]
Also, wondering if you're running the profiler with the debug build? If you are, chances are that the memory usage will keep growing.

**Comment by kesha-antonov** [comment]
@yinghang Ok thanks! I will try latest master

**Comment by kesha-antonov** [comment]
> Also, wondering if you're running the profiler with the debug build? If you are, chances are that the memory usage will keep growing.

I've tried both. Memory grows. In sample app slowly. In my production app faster

**Comment by kesha-antonov** [comment]
@yinghang BTW your graph looks like a saw. It means memory constantly grows and garbage collected. You think it's okay? I don't have much experience with java so not sure.

**Comment by yinghang** [comment]
I think so, I think it's due to the API call that I'm making every 5 seconds.

**Comment by kesha-antonov** [comment]
Maybe related https://github.com/facebook/react-native/issues/16732

**Comment by yinghang** [comment]
Are you using WebSockets in your app? If not I'm afraid that they're probably unrelated. Also, did you get to build your app with the release variant? App memory will grow continuously in debug mode.

**Comment by kesha-antonov** [comment]
It's active

**Comment by nachofregeiro** [comment]
Any update on this?

**Comment by kesha-antonov** [comment]
It's active
