### ISSUE TITLE
[Bridge] Support background restoration

### ISSUE THREAD

**Issue by jacobrosenthal** [facebook/react-native#1660]
Right now when an app is launched, the launchoptions are given to a native module via the setBridge function. This is handy for push notifications as you can know what notification launched you, etc. 

That paradigm doesnt work for Corelocation and Corebluetooth restoration though. These trigger a didFinishLaunchingWithOptions in order to tell the app that a location or device it was told to track has resurfaced. The rest of the app is never launched though, so setbridge never happens. Its common to do a push notification right there or restart your bluetooth stack to do some action. So I think we need a way to register functions to be called upon those launchoptions keys.

**Comment by brentvatne** [comment]
cc @nicklockwood @tadeuzagallo

**Comment by machard** [comment]
any news on this ?

**Comment by brentvatne** [comment]
@machard - I don't think anybody is working on it, cc @christopherdro

**Comment by christopherdro** [comment]
@jacobrosenthal I see we share common interests. :)

I think what you may be referring to might be a bit different than the referenced issue.
Are you maybe referring to ranging for beacons in the background?

I'm currently working on a library that will support both iBeacon and Eddystone beacons for react native that might help.

Ping me on slack if you want. username: `cdro`

**Comment by ehd** [comment]
I'm interested in this for another reason, but not sure this is the right issue for this: Running JavaScript in response to remote background push notifications. I have some code implementing `didReceiveRemoteNotification` in `AppDelegate.m` that passes the notification on to `RCTPushNotificationManager`. However, the actual JavaScript event handler is only going to run as long as the app hasn't been suspended by iOS. I'm wondering whether there is a way to wake up the app shortly & handle the event, or to run a specific JavaScript module designed for handling the message, maybe storing data via `AsyncStorage` and presenting a local notification.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/bridge-support-background-restoration

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is heavily focused working on performance.

**Comment by npomfret** [comment]
@ehd I think what you need is actually supported (I have it working).  If your server sends a _voip_ push notification (rather than a regular push notification with `content-available=1`) then iOS will launch your app.
