### ISSUE TITLE
TouchableNativeFeedback and Remote debug mode

### ISSUE THREAD

**Issue by sm2017** [facebook/react-native#16615]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

    OS:  Windows 10
    Node: v8.1.3
    Yarn:  1.2.0
    npm:  5.0.3
    Watchman: Not Found
    Xcode:  Not Found
    Android Studio:  2.3.3

    Packages: (wanted => installed)
        react-native: 0.49.5 => 0.49.5
        react: 16.0.0-alpha.12 => 16.0.0-alpha.12

    Target Platform: Android(7)

### Steps to Reproduce
In remote debug mode always `onLongPress` is called
```js
class Playground extends Component {
  render() {
	  return (
		<TouchableNativeFeedback delayPressIn={50} 
			onPress={()=>{console.log("onPress")}} 
			onLongPress={()=>{console.log("onLongPress")}}>
			
			<Text style={{fontSize: 15}}>Press me</Text>
			
		</TouchableNativeFeedback>
		);
  }
}
```

### Expected Behavior

When I press `onPress` and when I long press `onLongPress` must be called

### Actual Behavior

In remote debug mode always `onLongPress` is called even you press shortly

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by sm2017** [comment]
I think . we must have a time synchronization system for debug mode

I know that js timers (like setTimeout) it not working well on remote debug mode

But with my experience when device time and remote machine time is about same we have less issue with remote debug mode ( it is not possible to manually sync time)

When time is about synced we have app is fast and when out of sync is slow

In simulator as the machine and simulator time is same we have good experience

I'm sure  time synchronization is needed for remote debug mode

**Comment by jankarres** [comment]
+1

**Comment by sm2017** [comment]
Any idea?
