### ISSUE TITLE
Hot Reloading `Maximum call stack size exceeded` error with circular reference

### ISSUE THREAD

**Issue by codebymikey** [facebook/react-native#16613]
Carrying on from #7288 which has been opened for over a year.

Say, there are two files `a.js` and `b.js`.

`a.js`:
```javascript
require('./b');
```

`b.js`:
```javascript
require('./a')
```

After making a change to one of these files, with Hot Reloading enabled, it will run into an infinite situation and finally throw a `Maximum call stack size exceeded` error.

Even if I use a dynamic require in a function, such as what in `b.js`:
```javascript
function f(){
  require('./a')
}
```

-----

This is a pretty serious issue.

**Comment by anonrig** [comment]
ffs, this is getting frustrating.

**Comment by realart** [comment]
This is a show-stopper for the entire framework and reason why I haven't done anything in React for past 5 months.

**Comment by hramos** [comment]
This is now fixed in master.
