### ISSUE TITLE
PermissionsAndroid request crashes 

### ISSUE THREAD

**Issue by srinuch1981** [facebook/react-native#16626]
### Is this a bug report?
Yes . 
When we used PermissionsAndroid for Bluetooth permission in android we are getting crash as th

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Steps to Reproduce

Android Permission in API Level (>=23) for BT using PermissionsAndroid.request API with rationale option.

1. Accessing permission "android.permission.ACCESS_COARSE_LOCATION"
2. Invoked from componentDidMount lifecycle method
3. Observed crash as ArrayIndexOutOfBounds index =0

### Expected Behavior

Must show Alert Dialog if not granted earlier and return grant status

### Actual Behavior

Not shown Alert Dialog and Throws Exception 

(Write what happened. Add screenshots!)

### Reproducible Demo

N/A

componentDidMount() {
        this.requestBTPermission();
}
async requestBTPermission() {
        try {
            const granted = await PermissionsAndroid.request("android.permission.ACCESS_COARSE_LOCATION", {
                'title': 'Turn On Bluetooth',
                'message': 'App needs access to your bluetooth ' + 'to connected to CEC.'
            });

            if (granted === PermissionsAndroid.RESULTS.GRANTED) {
                console.log("You can use the BT now")
            } else {
                console.log("BT permission denied")
            }
        } catch (err) {
            console.warn(err)
        }
    }

Logs:
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
07-16 10:43:40.786 10457 10457 E AndroidRuntime:        at com.facebook.react.modules.permissions.PermissionsModule$1.invoke(PermissionsModule.java:119)
07-16 10:43:40.786 10457 10457 E AndroidRuntime:        at com.facebook.react.modules.permissions.PermissionsModule.onRequestPermissionsResult(PermissionsModule.java:207)
07-16 10:43:40.786 10457 10457 E AndroidRuntime:        at com.facebook.react.ReactActivityDelegate$1.invoke(ReactActivityDelegate.java:211)
07-16 10:43:40.786 10457 10457 E AndroidRuntime:        at com.facebook.react.ReactActivityDelegate.onResume(ReactActivityDelegate.java:131)
07-16 10:43:40.786 10457 10457 E AndroidRuntime:        at com.facebook.react.ReactActivity.onResume(ReactActivity.java:66)
07-16 10:43:40.786 10457 10457 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1270)
07-16 10:43:40.786 10457 10457 E AndroidRuntime:        at android.app.Activity.performResume(Activity.java:6824)
07-16 10:43:40.786 10457 10457 E AndroidRuntime:        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3470)
07-16 10:43:40.786 10457 10457 E AndroidRuntime:        ... 8 more

**Comment by Unforgiven-wanda** [comment]
+1 I am having the exact same issue

**Comment by SamMatthewsIsACommonName** [comment]
this is fixed with this commit:
https://github.com/facebook/react-native/commit/ce967c6fbe9ff7337cc95bdd93a0c08a0688769a
however it doesn't seem to be in the production release yet

**Comment by derakhshanfar** [comment]
@SamMatthewsIsACommonName thanks so much but how can i upgrade react-native that refer to specific commit or tag when it is not release on NPM?

**Comment by SamMatthewsIsACommonName** [comment]
@derakhshanfar  I've been using 0.51.0-rc.2,
I believe it's fixed in this one

**Comment by LannyCodes** [comment]
@SamMatthewsIsACommonName Hi,I am having the exact same issue in 0.55.4 when I  used PermissionsAndroid for Camera permission ,how do you fix this problem,please help me, Thanks!
