### ISSUE TITLE
How can we set a group of fonts using fontFamily props?

### ISSUE THREAD

**Issue by aiynmm** [facebook/react-native#16620]
### Is this a bug report?

No

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
OS: window 10
Node: 8.1.3
Yarn: 0.27.5
npm: 5.0.3
Watchman: NO
Xcode: NO
Android Studio: NO

Packages: (wanted => installed)
react-native: 0.49.3 => 0.49.3
react: 16.0.0-beat.5 => 16.0.0--beat.5

Target Platform: Android

### Steps to Reproduce

(Write your steps here:)

1.As in css , we can set like this : `font-family:"Times New Roman",Georgia,Serif;`
2.But in RN , we just set one font ,` fontFamily: 'MidPlane00v3.1',`
3.How can we use it like css?

### Expected Behavior

we can set a group of font using fontFamily props!
I need to show multiple bytes Chinese words using  font rollback mechanism!So I need to set a group of fonts!

### Actual Behavior

we can just set one font!

### Reproducible Demo

```
fontFamily: 'MidPlane00v3.1','MidPlane02v3.1','MidPlane03v4.0',
```
It will report an error if I write like this,because fontFamily props just accept a String parameter！

**Comment by luqiuyuan** [comment]
+1 Also looking for this information. I am using a TextInput with placeholder containing a custom icon and some text
