### ISSUE TITLE
0.50.0-rc.2 not working with axios in release build

### ISSUE THREAD

**Issue by stackia** [facebook/react-native#16629]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS:  macOS High Sierra 10.13
  Node:  8.8.1
  Yarn:  1.2.1
  npm:  5.4.2
  Watchman:  4.9.0
  Xcode:  Xcode 9.0.1 Build version 9A1004
  Android Studio:  2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.50.0-rc.2 => 0.50.0-rc.2

### Steps to Reproduce

After upgrading my project to RN 0.50.0-rc.2, all [axios](https://github.com/axios/axios) call stopped working in release build (they work well in development build and RN 0.49.5).

```javascript
    try {
      const res = await axios.get('/news', {
        params: { limit: 20, offset: 0 }
      })
      console.log(res)
    } catch (error) {
      window.alert(error)
    }
```

I got this exception:
![image](https://user-images.githubusercontent.com/5107241/32280297-5ac4f126-bee9-11e7-9e7e-3f649464cc44.png)

This only happens on RN 0.50.0-rc.2 & production build.

After I changed [this line](https://github.com/axios/axios/blob/v0.17.0/lib/defaults.js#L18) in axios to `if (true) {` then it works again in production build. I don't know why the assertion failed in production build. When I use `window.alert(typeof XMLHttpRequest)` in my own code it outputs 'function', but it outputs 'undefined' in axios code.

**Comment by stackia** [comment]
Here is a workaround if you face the same problem.

```javascript
axios.defaults.adapter = require('axios/lib/adapters/xhr') // Force set to xhr adapter
```

I don't know if this is a bug of axios or React Native, but everything was working properly in previous version of React Native.

**Comment by alimek** [comment]
+1 same problem here

**Comment by Manweill** [comment]
I has same issue. fetch or axios, if use by async/await ,it doesn't work .but  use promise mode，it work。
like this
### can't work
```js
try {
   const res = await fetch('/api')
   const text = await res.text()
   Alert.alert("success")
} catch (error) {
  Alert.alert(error.message)
}
```

### working
```js
fetch('/api')
.then(res=>res.text())
.then(res=>{
    Alert.alert("success")
})
.catch(err=>{
   Alert.alert("error")
})
```

**Comment by vtrrsl** [comment]
Setting the metro-bundler version to 0.20.1 like seems to fix this issue for me

```  
"resolutions": {
    "react-native/metro-bundler": "0.20.1"
}
```

**Comment by Manweill** [comment]
@vtrrsl where is setting

**Comment by alimek** [comment]
@Manweill in `package.json`. Anyway you can try update RN to version `0.50.3`, they are saying that its fixed, but haven't tried it yet.

**Comment by Manweill** [comment]
@alimek Yes, it's ok in rn 0.50.3。
