### ISSUE TITLE
Deadlink in tutorial

### ISSUE THREAD

**Issue by sohum2002** [facebook/react-native#16621]
### Is this a bug report?

No.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes.

### Environment

None required.

### Steps to Reproduce

The documentation of react-native (https://facebook.github.io/react-native/releases/0.23/docs/tutorial.html) refers to Movies Example where the said URL lies at https://github.com/facebook/react-native/tree/master/Examples/Movies. However, this link directs to  404.

### Expected Behavior

Link refers to an active github page.

### Actual Behavior

Link refers to a 404 github page.

### Reproducible Demo

None required.

**Comment by phillip055** [comment]
That's the old version of docs, not sure if we want to remove it?!
But here is the latest docs http://facebook.github.io/react-native/docs/getting-started.html

**Comment by sohum2002** [comment]
Woops, didn't notice that I was looking at an old version. Thanks!

**Comment by sohum2002** [comment]
Khaek
