### ISSUE TITLE
[Bridge] RCTBatchedBridge should make use of other queues

### ISSUE THREAD

**Issue by jwyld** [facebook/react-native#1662]
If the loader could make use of another queue, the bridge's completion block could be called on that queue.  Anything (error handler) needing to fire on the main thread, can enqueue that work there, otherwise the enqueueing of the application script could go ahead and fire straight from its callback location.

This means it doesn't have to semaphore wait at the injection but prior to the enqueueing of the application script.

Additionally, it means the success case no longer waits on the main run loop to get cycles to simply trampoline the loaded script over to the JS queue.  The main run loop is likely very busy doing other application work and may not return quickly.

**Comment by tadeuzagallo** [comment]
This has been changed and everything is initialised in parallel.
