### ISSUE TITLE
undefined is not a function (evaluating 'arr[typeOf Symbol === 'function'? Symbol.iterator:'@@iterator']()')

### ISSUE THREAD

**Issue by andres221293** [facebook/react-native#16633]
### Is this a bug report?

(yes)

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(no)

### Environment
Environment:
    OS:  macOS Sierra 10.12.6
    Node:  6.11.2
    Yarn:  0.27.5
    npm:  5.5.1
    Watchman:  4.7.0
    Xcode:  Xcode 8.3.3 Build version 8E3004b
    Android Studio:  3 AI-171.4408382

  Packages: (wanted => installed)
    react-native: 0.44.2 => 0.44.2
    react: 16.0.0-alpha.6 => 16.0.0-alpha.6

  Target Platform: iOS (11)

### Steps to Reproduce

1.create a project react native with version 0.44.2 and install the ReactNavigation
2.then configure the StackNavigator as described by the official ReactNavigation website and that's when I got this error.
3.The funny thing that when I activate the debug the application works correctly

### Expected Behavior

(I expected it to work the same as the Debug that did not leave said error)

### Actual Behavior

![screenshot_20171101-141804](https://user-images.githubusercontent.com/22030681/32297853-8a880198-bf1e-11e7-9cc1-4dbbdb80d809.png)

**Comment by rcastill** [comment]
Same here! it happened after I cleaned my project's cache. Really bad timing D:

Any help is appreciated.

![photo_2017-11-01_20-37-14](https://user-images.githubusercontent.com/8534987/32302994-93e5c6a0-bf44-11e7-8c38-88d3ed5baf32.jpg)

**Comment by stlemon** [comment]
same here! but in Android.how to solve it?

**Comment by rcastill** [comment]
Here is a temp solution:

[https://github.com/react-community/react-navigation/issues/2853](https://github.com/react-community/react-navigation/issues/2853)

_tl;dr_ change `package.json` dependency:
```
"react-navigation": "git+https://github.com/react-community/react-navigation.git#ed2fc9a09e2f562ae9d3fc7f5df17c593989db0a"
```

**Comment by andres221293** [comment]
@rcastill replaced "react-navigation": "^1.0.0-beta.16" for "react-navigation": "git+https://github.com/react-community/react-navigation.git#ed2fc9a09e2f562ae9d3fc7f5df17c593989db0a"?

after npm remove react-navigation && npm install?

**Comment by militho** [comment]
I had the same problem, just do it next:

1.- npm remove react-navigation
2.- npm install

Start project:
3.- react-native start -- --reset-cache

When trying to open app it will show an error with react-navigation dependence, so then will reinstall the dependence and will resolved:

4.- npm install --save react-navigation

**Comment by TeslaMotors91** [comment]
undefined is not a function (evaluating ‘arr[typeofSymbol === “function” ? Symboliterator : “@@iterator”]())

Error turned out to be a package problem with "react-navigation": "^1.0.0-beta.16”, and used 
"react-navigation": "^1.0.0-beta.15 instead. 

This solved the problem stated above. Thank you all!! :D
