### ISSUE TITLE
Semantic Issue on iOS Build RN0.49.5

### ISSUE THREAD

**Issue by mbenjamin618** [facebook/react-native#16647]
### Is this a bug report?

Yes!

![screen shot 2017-11-02 at 10 18 38 am](https://user-images.githubusercontent.com/9419421/32330730-5ee1a898-bfb7-11e7-8587-ae51cb661c3b.png)

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.)

### Environment

Environment:
  OS:  macOS Sierra 10.12.6
  Node:  6.5.0
  Yarn:  0.27.5
  npm:  4.6.1
  Watchman:  4.8.0
  Xcode:  Xcode 9.0 Build version 9A235
  Android Studio:  2.3 AI-162.3934792

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: 0.49.5 => 0.49.5

### Steps to Reproduce

1. Install ReactNativeAudioToolkit
2. Empty derived data folder (Preferences->Locations) and Clean Project
3. Run

### Expected Behavior

Builds an iOS project on iPhone 8 Simulator

### Actual Behavior

Build fails with errors seen in image above. 
`Redefinition of 'RCTMethodInfo`
`Typedef redefinition with different types`

**Comment by chen236310** [comment]
I have the same problem，by Joining   react-native-customer-keyboard  the third party library leads to.

**Comment by mbenjamin618** [comment]
I think the fix to this is about relinking the project.
