### ISSUE TITLE
Eject with ExpoKit option fails in linux

### ISSUE THREAD

**Issue by rishii95** [facebook/react-native#16656]
### Is this a bug report?
After running npm run eject:-

Validating project manifest...
It appears you are trying to detach outside of macOS. You will require Xcode to build the resulting artefact.
Downloading iOS code...
Moving iOS project files...
Naming iOS project...
Configuring iOS project...
Error running eject: Error: Cannot configure an iOS app with no bundle identifier.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.)

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by jozan** [comment]
This is not a problem with React Native but Expo. You may want to reach out to Expo team or their [forums](https://forums.expo.io/).

**Comment by rastogitech** [comment]
+1

**Comment by rastogitech** [comment]
@rishii95 Have you solved this issue?
