### ISSUE TITLE
Vector Drawable support

### ISSUE THREAD

**Issue by andrewfluck** [facebook/react-native#16651]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: macOS High Sierra 10.13
  Node: 8.9.0
  Yarn: 1.2.1
  npm: 5.5.1
  Watchman: Not Found
  Xcode: Not Found
  Android Studio: 3.0 AI-171.4408382

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: 0.49.5 => 0.49.5

### Steps to Reproduce

1. Put your vector drawable into the Android drawable folder.
2. Inside the image primitive, call the resource using the `uri` method
3. There is no vector drawable inside the view.

### Expected Behavior

I expected the vector file to load fine and populate inside the Image

### Actual Behavior

The vector drawable was not visible at all. I do not think it even loaded into there.

### Reproducible Demo

1. Initialize a React Native project
2. Put a vector drawable in the drawable directory
3. Create an Image, I did this for example: `<Image source={{ uri: 'ic_arrow' }} style={{height: 24, width: 24}}/>`
4. Run the app, the vector doesn't load

**Comment by cdlewis** [comment]
Image doesn't support vector drawables so I think this is a feature request rather than a bug.

**Comment by andrewfluck** [comment]
Oh? It doesn't even support it? I would assume it did. :confused:

**Comment by andrewfluck** [comment]
That's the thing, I don't want something that could break easily, I trust primitives more than 3rd party implementations.

**Comment by andrewfluck** [comment]
Another thing is with vector drawables, they work just like normal bitmap drawables that you can require in. If the image component is based on ImageView, then it should be able to have native vector drawable support too. I could be wrong though.
