### ISSUE TITLE
Android `injectJavascript` must return `undefined` or it replaces the contents of the WebView

### ISSUE THREAD

**Issue by dahjelle** [facebook/react-native#16650]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS:  macOS Sierra 10.12.6
  Node:  7.10.0
  Yarn:  Not Found
  npm:  4.5.0
  Watchman:  4.7.0
  Xcode:  Xcode 9.1 Build version 9B55
  Android Studio:  2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: 0.49.3 => 0.49.3

  Target Platform: Android (broken) and iOS (works)

### Steps to Reproduce

1. Create an app with a WebView. Add a `ref` for the WebView.
2. Use `ref.injectJavaScript('x = "test";') to inject some JavaScript into the WebView.

### Expected Behavior

The JavaScript is executed on the page, without replacing the page.

### Actual Behavior

The result of the JavaScript expression replaces the contents of the page.

### Reproducible Demo

https://snack.expo.io/Hke6dJFAW (EDIT: fixed URL)

### Problem Code

I'm reasonably sure [this line](https://github.com/facebook/react-native/blob/59d9f8ca5eb96b4b455b60ed170dfb05bc9c7251/ReactAndroid/src/main/java/com/facebook/react/views/webview/ReactWebViewManager.java#L596) is the issue.

[Elsewhere in that file](https://github.com/facebook/react-native/blob/59d9f8ca5eb96b4b455b60ed170dfb05bc9c7251/ReactAndroid/src/main/java/com/facebook/react/views/webview/ReactWebViewManager.java#L596), the injected JavaScript is wrapped in an IIFE so that the `javascript:` URL always evaluates to `undefined`.

Is the IIFE the complete solution? If so, I can submit a PR. Or are there other considerations (such as the changing scope) that need to be considered?

**Comment by Jancat** [comment]
Meet the same problem. Thanks for temporary solution with `return undefined`

**Comment by treyp** [comment]
`return;` stopped the page from being replaced with the last return value, but I still couldn't get input values to be set. Once I wrapped the code in an IIFE, it worked. Thanks!

**Comment by GianniGM** [comment]
Same problemi, it's very annoying :(

**Comment by ryan-granlund** [comment]
@treyp I am struggling to get a work around in place. Are you able to add a code snippet to get input values to work?

**Comment by treyp** [comment]
@ryan-granlund: sure, here's an example of code i have working in both platforms:
```js
this.webview.injectJavaScript(`
    (function () {
        document.getElementById('exampleTextInput').value = '${inputValue}';
    })();
`);
```

where `this.webview` is a ref to a webview (`<WebView ref={(el) => {this.webview = el;}} source={{uri: webviewUrl}} />`)

**Comment by Jancat** [comment]
not fixed in RN 0.54.2

**Comment by AleksandrChernyavenko** [comment]
Workaround:

For not everything inside of`injectedJavaScript` and `injectJavaScript` should be in one line (without newlines)

```js
 const injectScript = `
    setInterval(function () {
      window.postMessage('example text');
      alert('sent');
    }, 1000)
    `
const inlineScript = injectScript.replace(/[\r\n]+/g, '')
 <WebView
        injectedJavaScript={inlineScript}
        onMessage={this.onMessage}
        source={{uri: url}}
        style={styles.webView}
        startInLoadingState
      />
```

**Comment by BlackSword101** [comment]
how can we get data from injectJavaScript ?  `injectedJavaScript={`return document.cookie;`}`

**Comment by SiavasFiroozbakht** [comment]
@BlackSword101 For returning data the `window.postMessage()` function can be used. Check [this gist](https://gist.github.com/xxxxlr/475bd734fe49d776370633461164c361#file-react-native-webview-cookies-js-L1) for instructions, especially related to cookies.
