### ISSUE TITLE
why the latest version can not run the example ? shit.

### ISSUE THREAD

**Issue by philonpang** [facebook/react-native#1666]
since the react native publish, the upgrade versions always have  some bug when using,  i know facebook is a well and open company , i only please the react-native team to make sure the publish version is avaliale, thanks ..

**Comment by ide** [comment]
Are you having trouble upgrading your React Native version, or are you not able to run a new project with the latest version? I'm not sure what you're asking and need more details like a stack trace or screenshots to tell you what's happening. Provide more info if you expect to receive help.

As for upgrading, React Native's versions are currently 0.x releases which generally means that [features may change between releases](http://semver.org/). However, the changes are usually documented in the [release notes](https://github.com/facebook/react-native/releases/tag/v0.6.0-rc) and no one is intentionally trying to make life hard for users. Maybe this isn't yet right for your use case if you require a very stable API that changes much more slowly or need to ship a production app and can't afford the technical risk. The native part of React Native is young compared to other frameworks and under heavy development in many areas, so there have been many changes and you should expect the framework to evolve.

**Comment by brentvatne** [comment]
@ide nailed it, not much else to be said here. I'm sorry that the experience wasn't seamless for you @philonpang. Closing this issue, feel free to re-open one with a detailed description of your problem, we'd be happy to help if we knew what was wrong! :smile:
