### ISSUE TITLE
Slider's minimumTrackTintColor & maximumTrackTintColor props are reversed on Android

### ISSUE THREAD

**Issue by dekelev** [facebook/react-native#16672]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

```
Environment:
    OS: Windows 10
    Node: 6.11.4
    Yarn: 1.1.0
    npm: 4.6.1
    Android Studio: Android Studio 2.3.2, Build #AI-162.3934792

  Packages: (wanted => installed)
    react-native: 0.47.2 => 0.47.2
    react: 16.0.0-alpha.12 => 16.0.0-alpha.12
```

### Steps to Reproduce

1. Set minimumTrackTintColor & maximumTrackTintColor props on the Slider component
2. Run on Android

### Expected Behavior

minimumTrackTintColor should set the progress color while the maximumTrackTintColor should set the background color.

### Actual Behavior

On Android, minimumTrackTintColor sets the background color while the maximumTrackTintColor sets the progress color.

From [ReactSliderManager.java](https://github.com/nicktate/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/slider/ReactSliderManager.java)
```
@ReactProp(name = "minimumTrackTintColor", customType = "Color")
  public void setMinimumTrackTintColor(ReactSlider view, Integer color) {
    LayerDrawable drawable = (LayerDrawable) view.getProgressDrawable().getCurrent();
    Drawable background = drawable.findDrawableByLayerId(android.R.id.background);
    if (color == null) {
      background.clearColorFilter();
    } else {
      background.setColorFilter(color, PorterDuff.Mode.SRC_IN);
    }
  }

  @ReactProp(name = "maximumTrackTintColor", customType = "Color")
  public void setMaximumTrackTintColor(ReactSlider view, Integer color) {
    LayerDrawable drawable = (LayerDrawable) view.getProgressDrawable().getCurrent();
    Drawable progress = drawable.findDrawableByLayerId(android.R.id.progress);
    if (color == null) {
      progress.clearColorFilter();
    } else {
      progress.setColorFilter(color, PorterDuff.Mode.SRC_IN);
    }
  }
```

### Reproducible Demo

```
import { Slider } from 'react-native';
...
<Slider
        minimumTrackTintColor="white"
        maximumTrackTintColor="gray"
      />
```

**Comment by maggialejandro** [comment]
Same problem here
RN 0.48.4

iOS: 
![captura de pantalla 2017-12-12 a la s 12 48 58](https://user-images.githubusercontent.com/3394748/33893785-19093d10-df3b-11e7-9387-59b6d742468c.png)

Android: 
![captura de pantalla 2017-12-12 a la s 12 48 49](https://user-images.githubusercontent.com/3394748/33893797-1ed8e7fe-df3b-11e7-8aa4-47964263a1ee.png)

Code:
```javascript
<Slider
  style={{ marginBottom: 10 }}
  value={durations[i] ? durations[i] : s.max}
  step={step}
  minimumValue={s.min}
  maximumValue={s.max}
  onSlidingComplete={this.handleDuracionComplete}
  onValueChange={value => this.handleValueChange(value, i)}
  minimumtracktintcolor="green"
  maximumTrackTintColor="red"
  thumbTintColor="#3f78c3"
/>
```

**Comment by maggialejandro** [comment]
Same problem here
RN 0.48.4

iOS: 
![captura de pantalla 2017-12-12 a la s 12 48 58](https://user-images.githubusercontent.com/3394748/33893785-19093d10-df3b-11e7-9387-59b6d742468c.png)

Android: 
![captura de pantalla 2017-12-12 a la s 12 48 49](https://user-images.githubusercontent.com/3394748/33893797-1ed8e7fe-df3b-11e7-8aa4-47964263a1ee.png)

Code:
```javascript
<Slider
  style={{ marginBottom: 10 }}
  minimumtracktintcolor="green"
  maximumTrackTintColor="red"
  thumbTintColor="#3f78c3"
/>
```

**Comment by maggialejandro** [comment]
related PR https://github.com/facebook/react-native/pull/16053
