### ISSUE TITLE
Error at launch screen when running app for Release.

### ISSUE THREAD

**Issue by jonching** [facebook/react-native#16681]
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

yes

### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 6.9.1
  Yarn: Not Found
  npm: 3.10.8
  Watchman: 4.7.0
  Xcode: Xcode 9.1 Build version 9B55
  Android Studio: Not Found

Packages: (wanted => installed)
  react: ^16.0.0 => 16.0.0
  react-native: ^0.50.0 => 0.50.0

### Steps to Reproduce

1. Open xcode
2. Product -> Edit scheme -> Build configuration "Release"
3. Build and run for device or simulator

### Expected Behavior

App successfully runs.

### Actual Behavior

Stalls at launch screen and produces the following Xcode error:

E1104 15:25:43.994065 1870475264 JSCHelpers.cpp:137] Got JS Exception: Can't find variable: self (/var/containers/Bundle/Application/30C12CDD-E4C1-46CB-8972-FB0FF5650DDF/hydrangea.app/main.jsbundle:389)
E1104 15:25:43.994191 1870475264 JSCHelpers.cpp:143] Got JS Stack: /var/containers/Bundle/Application/30C12CDD-E4C1-46CB-8972-FB0FF5650DDF/hydrangea.app/main.jsbundle:389:12193

Reverting my react native version back to 0.49.3 makes it work again. I tried removing ios/build directory, doing xcode cleans, npm installing and always end up with this same error when running the app for release.

**Comment by 0x0E** [comment]
hi @jonching ,I got same issue, how do you fix it?
