### ISSUE TITLE
It seems something went wrong while linking. Error: Cannot read property 'nodeValue' of undefined

### ISSUE THREAD

**Issue by JairOrozco1986** [facebook/react-native#16683]
I have an issue while linking react-native project

react-native link

then throws error like this:

rnpm-install info Android module react-native-maps is already linked
rnpm-install info iOS module react-native-maps is already linked
rnpm-install info iOS module react-native-uploader is already linked
rnpm-install info Linking assets to ios project
rnpm-install ERR! It seems something went wrong while linking. Error: Cannot read property 'nodeValue' of undefined

I don't know why...
I have tried delete node_module folder and delete cache and delete lock files, and also tried yarn, npm

But not working at all.

**Comment by whitebunny890202** [comment]
I have met the same problem.
