### ISSUE TITLE
[Docs] Install React Native Using CocoaPods Into An Existing Swift Project

### ISSUE THREAD

**Issue by yelled3** [facebook/react-native#1669]
Is it possible to install React Native from CocoaPods into an existing Swift project?
if so, what should I `#import` in the bridging header? (e.i `MyRNSwiftApp-Bridging-Header.h`)

more over, I was reading the docs:
http://facebook.github.io/react-native/docs/embedded-app.html#install-react-native-using-cocoapods

and looking at some related issues (some of which are a few months old) and couldn't find a clear answer for this issue.

**Comment by brentvatne** [comment]
Haven't done this myself but it seems like we should update the embedded app docs to explain how this would be different for Swift

**Comment by yelled3** [comment]
@brentvatne 
> we should update the embedded app docs to explain how this would be different for Swift

![](http://replygif.net/i/945.gif)

**Comment by nsimmons** [comment]
Figuring out what to import into the bridging header is the main difference between obj-c and swift. I have an idea of how this could be automated and built into the cli as a command. I'll see if I can come up with a solution and update the docs.

**Comment by christopherdro** [comment]
Please reference the documentation found [here](http://facebook.github.io/react-native/docs/embedded-app-ios.html#install-react-native-using-cocoapods).

**Comment by yelled3** [comment]
@christopherdro thanks!
