### ISSUE TITLE
[Docs] Document FormData local resource hack

### ISSUE THREAD

**Issue by alexrussell** [facebook/react-native#16700]
### Is this a bug report?

Yes, of a sort - request for documentation.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes - not overly relevant to reporting documentation issues.

### Environment

Not relevant

### Steps to Reproduce

Not relevant.

### Expected Behavior

Not relevant.

### Actual Behavior

Not relevant.

### Reproducible Demo

Not relevant.

---

It'd be really useful to document the FormData `{ uri: [string] }` hack that RN adds so that we can upload local files with Fetch/XHR. This is kinda documented [in the tests](https://github.com/facebook/react-native/blob/master/Libraries/Network/__tests__/FormData-test.js#L40) and also features in [some testing app](https://github.com/facebook/react-native/blob/master/RNTester/js/XHRExampleFormData.js#L107) but it's not explicitly mentioned in the networking documentation, which is the perfect place for it.

**Comment by madhums** [comment]
Agree, there's not much documentation about FormData and the tests fail when using libraries that use FormData. Would be really helpful to document this.
