### ISSUE TITLE
React Native 0.50 flicker when used with Wix React Native Navigation

### ISSUE THREAD

**Issue by salisuabubakar** [facebook/react-native#16707]
I just upgrade from React Native 0.49.1 to 0.50.1 ... the upgrade was successfull but screen is flickering. Am using it with Wix React Native Navigaton 1.1.260. Please help. Thanks

**Comment by emin93** [comment]
I can confirm that i have the same issue. Adding `{ navBarHidden: true }` to the navigatorStyle did fix the issue for me. But i couldn't find out yet what exactly causes the issue.

**Comment by SudoPlz** [comment]
I also have the same issue

**Comment by SudoPlz** [comment]
Ok that looks like a react-native-navigation issue
https://github.com/wix/react-native-navigation/issues/2138
