### ISSUE TITLE
0.50.1 react-native bundle android the process is undefined

### ISSUE THREAD

**Issue by xiaoDC** [facebook/react-native#16713]
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

yes

### Environment

Environment:
   OS: macOS Sierra 10.12.6
   Node: 8.9.0
   Yarn: 1.3.2
   npm: 5.5.1
   Watchman: 4.9.0
   Xcode: Xcode 9.0 Build version 9A235
   Android Studio: 3.0 AI-171.4408382

Packages: (wanted => installed)
    react: 16.0.0 => 16.0.0
    react-native: 0.50.1 => 0.50.1

### Steps to Reproduce

(Write your steps here:)

1. I run the command `react-native run-android` , the app did work;
2. But when i want build bundle file with the command `react-native bundle --verbose --dev true --entry-file index.js --bundle-output output.bundle`, the app did work, and i find the Android Studio log the error `process is undefined`;
3.  I find the develop bundle file, there is 
```
;require(50);
;require(0);
```
, however the `output.bundle`, there is only

```
;require(0);
```

the `50` package is the file `react-native/Libraries/Core/InitializeCore.js`,
and the code
```
// Set up process
global.process = global.process || {};
global.process.env = global.process.env || {};
``` 
in it.

### Expected Behavior

the app using 0.50.1 can work with bundle file.

### Actual Behavior

the app can not work.

**Comment by Fefbug** [comment]
Probably link to this issue : 
https://github.com/facebook/react-native/issues/16689

and the workaround  :
https://github.com/facebook/react-native/issues/16689#issuecomment-342474127

**Comment by xiaoDC** [comment]
@Fefbug thanks
