### ISSUE TITLE
[Bug][FlatList] assigning object to viewabilityConfig prop in render method triggers error

### ISSUE THREAD

**Issue by eballeste** [facebook/react-native#16710]
### Is this a bug report?

Yup.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yup.

### Environment

  OS:  OS X El Capitan 10.11.6
  Node:  7.10.0
  Yarn:  0.24.6
  npm:  4.2.0
  Watchman:  4.9.0
  Xcode:  Xcode 8.2.1 Build version 8C1002
  Android Studio:  Not Found

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.50.1 => 0.50.1

### Steps to Reproduce

Use a flatlist with a `viewabilityConfig.viewAreaCoveragePercentThreshold` prop set to any value.
e.g: `viewabilityConfig={{ viewAreaCoveragePercentThreshold: 50 }}`. 

    <View>
        <FlatList
          data={[{a: foo}, {b: bar}, {c: foobar}]}
          viewabilityConfig={{ viewAreaCoveragePercentThreshold: 50 }}
        />
    </View>

### Expected Behavior

Normal use of a `viewabilityConfig` prop on a FlatList.

### Actual Behavior

Use of `viewabilityConfig` throws errors caused by checks introduced in the following commit: [ad733ad](https://github.com/facebook/react-native/commit/ad733ad430a4b1d69b89041be8b227e2dfdb5501#diff-85e8f96a713d23be94fbd08687332bff)

Get Invariant violations, testing for equality, console.log spits out equal values, throws error regardless.

_FlatList.js_ (425-428):

    invariant(
          nextProps.viewabilityConfig === this.props.viewabilityConfig,
          'Changing viewabilityConfig on the fly is not supported',
    );

![screen shot 2017-11-06 at 7 25 35 pm](https://user-images.githubusercontent.com/6924108/32471035-549fddc6-c329-11e7-83aa-3f2afebc3560.png)

### Reproducible Demo

Can't reproduce error on snack.

**Comment by eballeste** [comment]
@Vince0613 @sahrens

**Comment by eballeste** [comment]
I'm guessing the objects in prop are not considered equal because they are recreated on each re-render?? Is this what's happening?

**Comment by eballeste** [comment]
Fixed this by setting the properties as a constant, outside of the render method, but still not sure if these checks should be so strict, unless it's perf related...

**Comment by eballeste** [comment]
Fixed this by setting the properties as a constant outside of the render method, but still not sure if these invariant checks should be doing equality checks by reference...

**Comment by smithaitufe** [comment]
I still have this issue despite setting the viewabilityConfig as a constant outside of my class. It happens when the app is refreshing or reloading. Please fix this asap.

**Comment by rikur** [comment]
Please re-open, this is still an issue. I second that it shouldn't be checked by reference.
