### ISSUE TITLE
  :ReactAndroid:downloadBoost FAILED  ....WTF! Chinese GFW ! 

### ISSUE THREAD

**Issue by jackbabyyyy** [facebook/react-native#16716]
### Is this a bug report?

(write your answer here)

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.)

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by hey99xx** [comment]
You should be awarded for the most interesting bug report title. Are you trying to say downloadBoost task fails because it gets blocked because of firewall in China?

**Comment by jackbabyyyy** [comment]
@hey99xx  yes,downloadBoost task fails .

**Comment by blinkcat** [comment]
Failed to successfully download 'boost_1_63_0.tar.gz'.   Me too

**Comment by fuxianwei** [comment]
me too
