### ISSUE TITLE
FlatList not working with array with non-numeric key

### ISSUE THREAD

**Issue by kelvinaliyanto** [facebook/react-native#16720]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS:  OS X El Capitan 10.11.6
  Node:  6.11.0
  Yarn:  Not Found
  npm:  3.10.10
  Watchman:  4.9.0
  Xcode:  Xcode 8.0 Build version 8A218a
  Android Studio:  3.0 AI-171.4408382

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: 0.49.3 => 0.49.3

### Steps to Reproduce

1. FlatList is not working when it is provided array with non-numeric keys, for example: ["A"=>"B", "C"=>"D"]. 
2. But it works fine when using [0 => "B", 1 => "D"]. 
3. Is using numeric keys strictly required for FlatList? Because my array's index will keep changing, so it is better to use its hash value as key, so it will be easier when doing updating, rather than need to always loop to search the element. I am migrating from ListView to FlatList, because ListView will be deprecated in future. But it still works using ListView if using non-numeric key.

### Expected Behavior

It should show the 2 items eventhough we are using A and C as key index. It will only show when using 0 and 1 as key index.

### Actual Behavior

It does not show any items. It also does not throw any error.

### Reproducible Demo

It happens in any project.

**Comment by eballeste** [comment]
I use non numeric keys by supplying an array of objects:
`data={[{a: foo}, {b:foo}, {c: foobar}]}`

**Comment by kelvinaliyanto** [comment]
@eballeste but the key of the array will be 0, 1, 2. Can we actually use "A" or "B" as the key of the array?
