### ISSUE TITLE
Upgrade to 0.50.1 - Bundling `index.js` error: bundling failed: Error of metro-bundler

### ISSUE THREAD

**Issue by oriharel** [facebook/react-native#16738]
Because of issue #16737 I had to do a workaround (which I'm still not sure works) of saving a backup copy of the pre-upgrade xcodeproj file and pasting it again after upgrading. Now the project loads on XCode, but I can't run the app. I get this error in the packager:

```
Loading dependency graph, done.
Bundling `index.js`  [development, non-minified]  0.0% (0/1), failed.
error: bundling failed: Error
    at DependencyGraph.getAbsolutePath (/Users/oriharel/oriApp/anoo/anooClient/node_modules/metro-bundler/src/node-haste/DependencyGraph.js:322:11)
    at DependencyGraph.getDependencies (/Users/oriharel/oriApp/anoo/anooClient/node_modules/metro-bundler/src/node-haste/DependencyGraph.js:300:4465)
    at /Users/oriharel/oriApp/anoo/anooClient/node_modules/metro-bundler/src/Resolver/index.js:135:29
    at Generator.next (<anonymous>)
    at step (/Users/oriharel/oriApp/anoo/anooClient/node_modules/metro-bundler/src/Resolver/index.js:13:830)
    at /Users/oriharel/oriApp/anoo/anooClient/node_modules/metro-bundler/src/Resolver/index.js:13:1060
    at Promise (<anonymous>)
    at /Users/oriharel/oriApp/anoo/anooClient/node_modules/metro-bundler/src/Resolver/index.js:13:741
    at Resolver.getDependencies (/Users/oriharel/oriApp/anoo/anooClient/node_modules/metro-bundler/src/Resolver/index.js:151:46)
    at /Users/oriharel/oriApp/anoo/anooClient/node_modules/metro-bundler/src/Bundler/index.js:660:39
```

Any help?

Thanks

**Comment by chocky335** [comment]
@oriharel You should compile your index.android.js & index.ios.js to index.js

**Comment by rpavlovs** [comment]
Same issue. I only have `index.js`.

**Comment by hmenzagh** [comment]
Same here, I'm sure there is a good reason but I don't get it

**Comment by fpyang** [comment]
I fix the issue by following @chocky335's comment

**Comment by arapocket** [comment]
Same issue after changing index.ios.js to index.js

**Comment by jrumbut** [comment]
My project had an edited AppDelegate.m file and I needed to change the line that looked like (though in my case not exactly like)

    jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];

to reflect the change to index.js instead of index.ios.js. Hope that helps someone!
