### ISSUE TITLE
React Native CLI loading indicator on iPhone X simulator

### ISSUE THREAD

**Issue by deadcoder0904** [facebook/react-native#16730]
Its a little bug that on iPhone X simulator the loading screen goes off. 

It hides behind the top part of iPhone, so the percentage of App Loaded can't be seen. 

I think on iPhone X bringing it to the bottom would do the job. Or can be done with `SafeAreaView`  API

**Comment by deadcoder0904** [comment]
Well, sometimes automation sucks 😂

**Comment by salimbutex** [comment]
HI guys, react native cmd+D open debug menu for any simulator. But not working in iphone x. any idea?

**Comment by deadcoder0904** [comment]
It does work for me `CMD+D`
