### ISSUE TITLE
Upgrading from 0.48.4 to 0.50.1 - Unable to find project.pbxproj file

### ISSUE THREAD

**Issue by oriharel** [facebook/react-native#16737]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS:  macOS Sierra 10.12.6
  Node:  8.6.0
  Yarn:  1.1.0
  npm:  5.3.0
  Watchman:  4.1.0
  Xcode:  Xcode 9.0.1 Build version 9A1004
  Android Studio:  1.4 AI-141.2288178

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.50.1 => 0.50.1

### Steps to Reproduce

(Write your steps here:)

1. react-native-git-upgrade
2. rm -rf node_modules/
3. yarn

### Expected Behavior

XCode to successfully load the project

### Actual Behavior

XCode fails to load the project. Says the the project.pbxproj is missing (which is true)

**Comment by eballeste** [comment]
You need to consolidate your `index.ios.js` and `index.android.js` files into a single index.js file. 

I also did a jump from 0.48 to 0.50 and apparently this was a breaking change on 0.49.
