### ISSUE TITLE
FlatList "topScrollBeginDrag"

### ISSUE THREAD

**Issue by yasirdev** [facebook/react-native#16731]
While using flatlist Horizontal={true} I'm having this issue
Issue:
**Unsupported top level event type "topScrollBeginDrag" dispatched**

Is there anyone who is facing this issue in Android?

**Comment by donnes** [comment]
On Android when FlatList is defined as true this error is occurring.

![screenshot_1510354651](https://user-images.githubusercontent.com/9506146/32682075-c98e53b4-c659-11e7-9593-5ebfe884a5a1.png)

Please re-open the issue.

**Comment by vitorsilvalima** [comment]
Just run the following code in order to test this issue. I have tested on versions: 0.50.0, 0.50.2 and 0.50.3
``` js
export class MovieList extends Component {

    constructor(props){
        super(props)
    }
    onPress = (item) => {
        console.log(item)
    }

    render(){
        return <FlatList 
            data={[{key: 'a'}, {key: 'b'}, {key: 'c'}]}
            horizontal
            ItemSeparatorComponent={() => <View style={ { width: 5, height: 10 }}/>}
            renderItem = {({item}) => <View style={ { width: 100, height: 100, backgroundColor: 'white' }}/>}
        />
    }
}
```
