### ISSUE TITLE
[Android] stream was reset: PROTOCOL_ERROR

### ISSUE THREAD

**Issue by onrige** [facebook/react-native#16733]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.7.0
  Yarn: 1.1.0
  npm: 5.4.2
  Watchman: 4.9.0
  Xcode: Xcode 9.0 Build version 9A235
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: https://github.com/expo/react-native/archive/sdk-22.0.1.tar.gz => 0.49.3

### Steps to Reproduce

Sorry but I can't reproduce this bug for now. I hope you can help me to find the problem. It happens while loading on some devices in production.

### Expected Behavior

There should be no exceptions.

### Actual Behavior

<img width="844" alt="screen shot 2017-11-07 at 16 17 52" src="https://user-images.githubusercontent.com/14055801/32495661-2d315e9e-c3cf-11e7-8607-3bf384c8c852.png">

I am also found these issues that based on okhttp error [#1844](https://github.com/square/okhttp/issues/1844), [1897](https://github.com/square/okhttp/issues/1897).

**Comment by hrkeni** [comment]
I am having this issue as well. Any solutions?

**Comment by patrickCode** [comment]
Facing the same issue? Any updates?

**Comment by hrkeni** [comment]
We fixed it by moving the `content-type` of the POST request from `application/json` to `multipart/form-data`
This was probably better because the data was an image we were trying to upload.
