### ISSUE TITLE
"resource-id" or "content-desc" for react native apps on Android not populating

### ISSUE THREAD

**Issue by sasasa42** [facebook/react-native#16748]
### Expected Behavior

I must be able to be able to view the resource-id and content-desc attributes for Android when inspecting

### Actual Behavior

No resource-id and content-desc attributes are populated
I already referred the other issues related to this, but finally nothing works for me. Please suggest a solution, as I am not able to proceed with the testing.

### Reproducible Demo

I have a react native app to **inspect the elements** using Appium/UIAutomatorViewer.
For iOS, I could find that by having the elements with "accessibilityLabel" or "testID" solves the problem. But for **Android**, it seems that there is no solution at all. I tried with various combination of the **"accessibilityLabel" or "testID"**. Nothing finally worked out.

**Comment by jnrepo** [comment]
I believe this is needed for functional testing...

**Comment by bhgames** [comment]
Yeah this turned out for me to be because CodePush was pulling my un-labeled elements and old code from the Staging deployment, not running my newer code on my own local machine which had these tags(and which debug used just fine since it's programmed to not use CodePush).
