### ISSUE TITLE
The development server returned response error code:500

### ISSUE THREAD

**Issue by xiaoyongchen** [facebook/react-native#16749]
### Is this a bug report?
bundling failed: "Unable to resolve module `react-native/Libraries/vendor/emitter/EventEmitter` from `/Users/chenxiaoyong/workspace/zm-course-android-mobile/node_modules/react-native-root-siblings/lib/AppRegistryInjection.js`: Module does not exist in the module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`."
(write your answer here)

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.)

### Steps to Reproduce

(Write your steps here:)

1."dependencies": {
    "react": "16.0.0-alpha.12",
    "react-native": "0.47.1",
    "react-native-code-push": "^5.0.0-beta",
    "react-native-orientation": "^3.0.0",
    "react-native-qrcode": "^0.2.6",
    "react-native-view-shot": "^2.1.0",
    "react-navigation": "^1.0.0-beta.11",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.2.0"
  },
  "devDependencies": {
    "babel-jest": "20.0.3",
    "babel-preset-react-native": "2.1.0",
    "jest": "20.0.4",
    "react-test-renderer": "16.0.0-alpha.12"
  },
  "jest": {
    "preset": "react-native"
  }
}

2.npm start
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by 393197906** [comment]
你好，我和你的问题一样 ，你现在解决了吗？（
Hello, I have the same problem with you, have you solved it now?
）

**Comment by xiaoyongchen** [comment]
@393197906 这是安卓的问题，这两个库版本于RN版本要一致
configurations.all { resolutionStrategy.force 'com.squareup.okhttp3:okhttp:3.6.0' }
 // socket.io库-->https://github.com/socketio/socket.io-client-java
    compile('io.socket:socket.io-client:0.8.3') {
