### ISSUE TITLE
undefined is not an object (evaluating NativeModules.ProgressViewManager.ComponentHeight) when I make a new project in react native

### ISSUE THREAD

**Issue by arunshan** [facebook/react-native#1675]
I am having issues with creating a project in react native. It was working fine until last night and today I get this error. 
![image 2015-06-18 at 11 06 47 am](https://cloud.githubusercontent.com/assets/1124102/8238414/5c41611e-15aa-11e5-94ce-9587436c908d.png)

Anyone having similar issues? My react-native version is 0.4.4.

**Comment by brentvatne** [comment]
ProgressView does not exist in 0.4.4, it was introduced in 0.6.0-rc: https://github.com/facebook/react-native/commit/e68f89bfadba2381e7ea6c958a5aa187bc862713
