### ISSUE TITLE
'react-native log-ios' doesn't work with xcode 9.1

### ISSUE THREAD

**Issue by wootwoot1234** [facebook/react-native#16754]
`react-native log-ios` doesn't work with xcode 9.1

I get this error:

> NOTE:  Most system logs have moved to a new logging system.  See log(1) for more information.

Has anyone been able to find a workaround for this?

Environment:
  OS:  macOS High Sierra 10.13.1
  Node:  7.9.0
  Yarn:  0.27.5
  npm:  4.2.0
  Watchman:  4.7.0
  Xcode:  Xcode 9.1 Build version 9B55
  Android Studio:  Not Found

Packages: (wanted => installed)
  react: ^16.0.0 => 16.0.0
  react-native: ^0.50.0-rc.1 => 0.50.0-rc.1

**Comment by kytwb** [comment]
@wootwoot1234 I'm having the same issue. Any findings on your side since 8 days ago?
