### ISSUE TITLE
Switch component handle on iOS loses drop shadow when `thumbTintColor` is set

### ISSUE THREAD

**Issue by shaundon** [facebook/react-native#16764]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

    Environment:
      OS:  macOS Sierra 10.12.6
      Node:  8.9.0
      Yarn:  Not Found
      npm:  5.5.1
      Watchman:  4.7.0
      Xcode:  Xcode 9.1 Build version 9B55
      Android Studio:  2.3 AI-162.4069837

    Packages: (wanted => installed)
      react: 16.0.0-beta.5 => 16.0.0-beta.5
      react-native: ^0.49.3 => 0.49.3

  Target Platform: iOS (11.1)

### Steps to Reproduce

The `Switch` component has a `thumbTintColor` prop that allows the handle colour to be set. I've noticed that if this is set, the handle loses its drop shadow.

Here's some sample code:

```
// The handle has a drop shadow.
<Switch value />

// The handle does not have a drop shadow.
<Switch thumbTintColor="#fff" value />
```

### Expected Behavior

I assumed that the handle's drop shadow would be maintained no matter the colour of the handle.

### Actual Behavior

The handle loses its drop shadow when `thumbTintColor` is set, even when it's set to white.

![img_f525a6d535b5-1](https://user-images.githubusercontent.com/73652/32602364-c8fbac48-c53d-11e7-91c9-29fbc642b3ab.jpeg)

### Reproducible Demo

https://snack.expo.io/B1PwL3-Jz

**Comment by shaundon** [comment]
I've investigated this more and it appears to be part of the underlying iOS implementation. 

I tested this by creating a project in Xcode and adding a switch using storyboards, no JavaScript / React Native involved. I set [thumbTintColor](https://developer.apple.com/documentation/uikit/uiswitch/1623684-thumbtintcolor) on the switch to white, and it loses its drop shadow. 

The [UISwitch documentation](https://developer.apple.com/documentation/uikit/uiswitch) doesn't list any properties available to control the shadow, so I don't think there's anything that can be done in React Native about this, except for possibly updating the RN documentation to make people aware of this behaviour.

**Comment by joshuawright11** [comment]
This is pretty late but I came across this while googling around. It looks like the shadow doesn't actually disappear, it just changes to whatever the thumbTintColor is. So in your second image above you can see the faint white shadow. If you change thumbTintColor to red and give it a dark tintColor, the shadow is more noticeable:
<img width="134" alt="screen shot 2017-12-13 at 10 47 02 am" src="https://user-images.githubusercontent.com/6025554/33956323-0c1d778e-dff3-11e7-8688-76e20047bfac.png">
.

**Comment by shaundon** [comment]
@joshuawright11 that's really interesting, good find! It's a bit strange that it works like that, given that (as far as I can think of) coloured shadows aren't really a thing in the real world!

I think the behaviour is still on the iOS side so there's little that can be done from RN, but we could update the note I added in https://github.com/facebook/react-native-website/pull/24 to mention your new findings.
