### ISSUE TITLE
Android devDisabledInStaging in build.gradle has no effect

### ISSUE THREAD

**Issue by pcguru** [facebook/react-native#16767]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Can not upgrade to React Native 0.48.0 at this time. I'm at:

$ react-native -v
react-native-cli: 2.0.1
react-native: 0.47.2

None of this is relevant for this problem, it's present in master as well as all previous versions.

### Steps to Reproduce

1. Create a Staging build type for Android. (Copy "release" and name it "staging").

2. Open build.gradle and follow the instructions to override settings for Staging.

Add these lines at top of file:
```
project.ext.react = [
    bundleInStaging: true,
    devDisabledInStaging: true
]
```

3. Build and install app.

### Expected Behavior

The app should have dev mode disabled and be as fast as the release build type.

### Actual Behavior

The "shake-to-show debug modal" feature is disabled, but the app is still as slow as the debug build. It is definitely not in release mode.

### Reproducible Demo

The issue has been written about here:
https://dzone.com/articles/react-native-multiple-release-variants

The react.gradle file inside of React Native requires the build target to contain the string "release". So "staging" does not work. I confirm that renaming "staging" to "releaseStaging" works.

See latest version of react.gradle here:
https://github.com/facebook/react-native/blob/master/RNTester/android/app/react.gradle

`!targetName.toLowerCase().contains("release")`

**Comment by vonovak** [comment]
This is weird, the react.gradle that should be used is this: https://github.com/facebook/react-native/blob/master/react.gradle#L82

**Comment by zaguini** [comment]
+1
