### ISSUE TITLE
[Layout] Layout.c is out of date

### ISSUE THREAD

**Issue by dmueller39** [facebook/react-native#1676]
There have been bug fixes to https://github.com/facebook/react-native/blob/master/React/Layout/Layout.c since it was last updated. 
For instance https://github.com/facebook/css-layout/commit/fca176109d84a7b583bc091f91109d8c359ac1fc which addresses custom measurement for  container views. The instructions for updating indicate ./import.sh which does not exist in the react-native.

**Comment by a2** [comment]
@vjeux Do we want to update `css-layout`?

**Comment by vjeux** [comment]
We absolutely do. There were a couple of things that broke when we updated last so need to be careful and fix them

**Comment by ide** [comment]
The css-layout repo is over three months ahead of the version here and contains mostly bugfixes and new features i.e. good stuff that's ~mostly backwards-compatible.

@vjeux can a bootcamper or new team member help update css-layout and start to shape a process around keeping it up-to-date?

**Comment by ide** [comment]
pingcat. can this go on the roadmap for 0.12 or 0.13?

**Comment by ide** [comment]
I saw that the latest Android sync includes a new version of css-layout. Is Android using the latest css-layout, or does it match iOS's implementation? The layout engines can't diverge too much across platforms and we need a plan for keeping them in sync and up-to-date.

cc @vjeux @mkonicek

**Comment by vjeux** [comment]
The ios diff is also in the queue. Had issue landing it because of internal unrelated breakages but it's coming

**Comment by ide** [comment]
Fantastic, that's great to hear.

**Comment by ide** [comment]
Closing this since css-layout was synced awhile back.
