### ISSUE TITLE
[Bug] java.lang.SecurityException: Requires VIBRATE permission

### ISSUE THREAD

**Issue by chocky335** [facebook/react-native#16768]
Environment:
  OS:  macOS Sierra 10.12.6
  Node:  8.4.0
  Yarn:  1.3.2
  npm:  5.5.1
  Watchman:  4.9.0
  Xcode:  Xcode 9.1 Build version 9B55
  Android Studio:  2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: ^0.48.4 => 0.48.4

  Target Platform:  android 5.1.1 (XIAOMI Redmi 3) | Android versions less than 6.0

### Steps to Reproduce

1. Add permission to AndroidManifest.xml:
    ```<uses-permission android:name="android.permission.VIBRATE"/>```
2. Add to project file
   ```import { Vibration } from "react-native```
3. Run a vibration
   ```Vibration.vibrate()```

### Tried to use:
    ```<uses-permission android:name="android.permission.VIBRATE" />```
    ```<uses-permission android:name="android.permission.VIBRATE" android:maxSdkVersion="18" />```
     ```<uses-permission-sdk-23 android:name="android.permission.VIBRATE"/>```

### This one works for android 6+:
    ```<uses-permission-sdk-23 android:name="android.permission.VIBRATE"/>```

**Comment by arcollector** [comment]
I have the same issue, only  using ```<uses-permission-sdk-23 android:name="android.permission.VIBRATE"/>```
