### ISSUE TITLE
refs do not work in renderRow functions

### ISSUE THREAD

**Issue by jamiefaye** [facebook/react-native#1677]
ref='name' attributes generated inside of functions called via the renderRow property of ListViews do not work. Using this.refs.name returns undefined. This makes coding renderRow functions more difficult. Is this supposed to be this way?

https://github.com/facebook/react-native/issues/897 addresses this problem, however I have not been able to get any of the suggestions to work. In particular, attempts to use the ref={(row, sec, i) => ...
approach fail with complaints about writing to read-only properties.

How should I refer to one object from another inside a renderRow function?

I do have an example of this not working I can share if need be.

**Comment by ide** [comment]
Can you paste a gist with your code? The callback-style ref should work. String-style refs won't work because they're assigned to the owner component that renders them which probably ends up being ListView and not your own component.

**Comment by jamiefaye** [comment]
I encountered the issue with the callback-style ref back on 0.4.4 and was able to get the callback working in 0,6.0-rc. It may well have been programmer error back then.

If the issue comes back, we can reopen this.
