### ISSUE TITLE
react-native keep calling ws://localhost:8097 and getting 500

### ISSUE THREAD

**Issue by dktan** [facebook/react-native#16779]
![image](https://user-images.githubusercontent.com/12505414/32634967-20023528-c563-11e7-8943-3cce2389098a.png)
dosen't seems to cause any problem right now, but annoying

RN: 0.44.0
OS: 10.13.1

**Comment by JunielKatarn** [comment]
Hi @dktan. Did you ever found out the reason of this issue?
