### ISSUE TITLE
"Something went wrong while linking. Error: Cannot read property 'match' of undefined"

### ISSUE THREAD

**Issue by fungilation** [facebook/react-native#16774]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

`$ react-native info`:
```
Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.9.1
  Yarn: 1.3.2
  npm: 5.5.1
  Watchman: 4.9.0
  Xcode: Xcode 9.1 Build version 9B55
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.50.3 => 0.50.3
```

  Target Platform: iOS 11.1

### Steps to Reproduce

1. `yarn add react-native-blur@3.2.2`
2. `react-native link react-native-blur`

### Expected Behavior

Package linked without error

### Actual Behavior

```
$ react-native link react-native-blur

rnpm-install info Linking react-native-blur android dependency 
rnpm-install info Android module react-native-blur has been successfully linked 
rnpm-install info Linking react-native-blur ios dependency 
rnpm-install ERR! Something went wrong while linking. Error: Cannot read property 'match' of undefined 
Please file an issue here: https://github.com/facebook/react-native/issues 

Cannot read property 'match' of undefined

```

Note that I haven't seen a similar error, before RN 0.50 or react-native-blur <= 3.2.0

Issue also reported at https://github.com/react-native-community/react-native-blur/issues/246

**Comment by ngankt2** [comment]
same bug with "react-native": "^0.50.3" and react-native link ANYTHING => same bug
I did the following and it worked:

step1: remove node_modules
step2: close xcode
step3: cd ios and run pod install (i have use firebase) 
step4: react-native link ANYTHING => and OK
 
I hope it will help you

**Comment by henrydeclety** [comment]
I get the same error with react-native-keychain when trying to link
`rnpm-install info Linking react-native-keychain android dependency 
rnpm-install info Android module react-native-keychain has been successfully linked 
rnpm-install info Linking react-native-keychain ios dependency 
rnpm-install ERR! Something went wrong while linking. Error: Cannot read property 'match' of undefined 
Please file an issue here: https://github.com/facebook/react-native/issues 

Cannot read property 'match' of undefined`

And if I uninstall react-native-keychain, the same happens with react-native-vector-icons:
`rnpm-install info Android module react-native-vector-icons is already linked 
rnpm-install info Linking react-native-vector-icons ios dependency 
rnpm-install ERR! Something went wrong while linking. Error: Cannot read property 'match' of undefined 
Please file an issue here: https://github.com/facebook/react-native/issues 

Cannot read property 'match' of undefined`

**Comment by povloid** [comment]
Some problem on React-native 0.50.3

**Comment by erlendfh** [comment]
At least in our case, this was related to a "problem" with Podfile. If you're using cocoapods, `react-native link` now (#15460) looks for the line `target '<project-name>' do`, in the Podfile, to figure out where to add cocoapods dependencies, but we had added additional targets to this list, so it no longer matched.

**Comment by fungilation** [comment]
Note that I'm hitting this issue in 2 packages since upgrading RN to 0.50.3: `react-native-code-push` and `react-native-blur`. Without unlink/link however, the packages works fine after upgrades. I haven't looked yet at whether the packages break when installed new and linked, not having been previously installed.

**Comment by LiuShuoyu** [comment]
If your iOS project is using CocoaPods (contains Podfile) and linked library has podspec file, then react-native link will link library using Podfile. To support non-trivial Podfiles add # Add new pods below this line comment to places where you expect pods to be added.

**Comment by code-by** [comment]
@LiuShuoyu in my project there is Pod file with following content:
```target 'MyApp'
pod 'Fabric'
pod 'Crashlytics'
```

and after these lines I need add `# Add new pods below this line`?

**Comment by isnifer** [comment]
@LiuShuoyu You're fucking brilliant!

**Comment by luongs3** [comment]
@LiuShuoyu oh my god, I gave you a thousand likes

**Comment by ykbryan** [comment]
Running `react-native upgrade` works for me.

**Comment by gtaylor44** [comment]
In response to @LiuShuoyu comment

I thought comments were meant to make source code more readable and are ignored by the interpreter. There should be another "comment" to warn people that the comment `# Add new pods below this line` actually means something. Unbelievable.

**Comment by wzup** [comment]
@LiuShuoyu Doesn't work one bit

**Comment by mehulmpt** [comment]
In my case, I had changed name of 'app' through XCode but in Podfile it was still `target 'app' do`. Changing it to `target 'codedamn' do` worked for me (codedamn is the name I set through XCode)

**Comment by narutojone1218** [comment]
I updated the react-native version to 0.56.0 and got `Cannot read property 'match' of undefined` for all node_modules.

**Comment by joevo2** [comment]
On React Native 0.57 adding this in the podfile worked for me... omg... why is a comment important.. 
`# Add new pods below this line`
