### ISSUE TITLE
TextInput Method isFocused owner.getName Error

### ISSUE THREAD

**Issue by emmajam** [facebook/react-native#16787]
### Is this a bug report?

Yes!

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes 👍 

### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 6.10.3
  Yarn: 0.24.4
  npm: 3.10.10
  Watchman: 4.7.0
  Xcode: Xcode 9.0 Build version 9M214v
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: 0.49.5 => 0.49.5

  Target Platform: iOS (11.0) iPhone 6

### Steps to Reproduce

(Write your steps here:)

1. Create component with a `<TextInput />` component
2. Add a ref to this `<TextInput />` component like so: 
```
        <TextInput
          ref={(ref) => { this.textInput = ref }}
          placeholder={placeholder}
          onFocus={(val) => this.onFocus(val)}
          onSubmitEditing={(text) => handleSubmitEditing(text.nativeEvent.text)}
        />
```
3. Call a method from the TextInput Ref as below - to check if it is focused:
```
console.log('isFocused?', this.textInput.isFocused())
```

### Expected Behavior

See in the Debugging Console...

`console.log('isFocused?', true)` OR `console.log('isFocused?', false)`

### Actual Behavior

When this method is called the following error occurs:
<img width="376" alt="screen shot 2017-11-10 at 11 12 34" src="https://user-images.githubusercontent.com/21029500/32656027-13bd86dc-c608-11e7-8911-ef85a391ee1a.png">

### More Info:

I also tried to run this line of code:
`console.log('findNodeHandle - ', this.input ? findNodeHandle(this.textInput) : null)`

When it runs the `findNodeHandle(this.textInput)` it also throws the same error.

**Comment by vineet-287** [comment]
This is has reappear to me also for a particular instance. Here below my snipped 

```
<TextInput
                                        value={this.state.newMessage}
                                        style={{width : '80%', fontSize : 16, paddingLeft : 20}}
                                        placeholder="Message..."
                                        multiline = {true}
                                        numberOfLines = {5}
                                        underlineColorAndroid ={'transparent'}
                                        onChangeText={(newMessage) => {this.setState({newMessage})}} />
```

I am using Expo and when I run in development mode, I got this error. But surprisingly for this text input I am facing error may be `multiline` is throwing an error because in my complete app I am not using `multiline` for any input. Digging more into it for the solution.
