### ISSUE TITLE
Error processing request body: Error Domain=NSCocoaErrorDomain Code=257

### ISSUE THREAD

**Issue by AshokICreate** [facebook/react-native#16783]
### Is this a bug report?
YES

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?
YES

### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.5.0
  Yarn: Not Found
  npm: 5.3.0
  Watchman: 4.9.0
  Xcode: Xcode 9.0 Build version 9A235
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: 0.48.4 => 0.48.4

### Steps to Reproduce

1. Take Images using ImagePicker Component 
2. Tried to upload the image i am getting this error
3. it's not often but it will happen once out of 5 times.

### Expected Behavior

1. Able to capture image and system should be able to get the image from the specified url/path

### Actual Behavior

`Error processing request body: Error Domain=NSCocoaErrorDomain Code=257 "The file “InspireME” couldn’t be opened because you don’t have permission to view it." UserInfo={NSFilePath=/var/containers/Bundle/Application/E7F57FD7-965B-4C2D-9765-E445356CA8C7/InspireME.app, NSUnderlyingError=0x1c085dc70 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}}`

### Reproducible Demo

1. Take Images using ImagePicker Component 
2. Tried to upload the image i am getting this error
3. it's not often but it will happen once out of 5 times.

![img_82754333519b-1](https://user-images.githubusercontent.com/7522708/32645047-42fb980a-c60b-11e7-9c63-f0df89ccece1.jpeg)

**Comment by jomaint** [comment]
I am facing this issue too

**Comment by hoanganhbk94** [comment]
I am uploading multi images to server, but if i don't chose enough image, this error will happen. Now, i am checking image in client, anyone have other solution?
![screen shot 2017-11-20 at 10 52 54 am](https://user-images.githubusercontent.com/14512150/33001643-ae4463a2-cde1-11e7-99d7-7832351c38ce.png)

**Comment by HananeAlSamrout** [comment]
i was trying to upload an empty image, when stopping that the error disappeared

**Comment by harshsrivastavaglobussoft** [comment]
+1

**Comment by harshsrivastavaglobussoft** [comment]
@AshokICreate  did you find any solution for this issue

**Comment by ssomnoremac** [comment]
Check the local photo uri has the `file:///` prefix. It shouldn't.

**Comment by LuisRizo** [comment]
Use `image.path` instead of `image.sourceUri`

**Comment by harshsrivastavaglobussoft** [comment]
the problem was with my image.uri and form data 


  `let formData = new FormData();
      formData.append("videoFile", {
        name: name.mp4,
        uri: video.uri,
        type: 'video/mp4'
    });
    formData.append("id", "1234567");
    try {
        let response = await fetch(url, {
            method: 'post',
            headers: {
                'Content-Type': 'multipart/form-data',
            },
            body: formData
        });
        return await response.json();
    }
    catch (error) {
        console.log('error : ' + error);
        return error;`

this code worked for me for iOS and android for uploading video

**Comment by bnauta** [comment]
@LuisRizo `image.sourceURL`. For others running into this issue, confirm your source path/uri/url, it's likely pointed somewhere other than it should be.

**Comment by MacKentoch** [comment]
@LuisRizo  `image.sourceURL` works on iOS but not on android.
@bnauta what do you mean by `it's likely pointed somewhere other than it should be` on both iOS and Android.

> Both thank you for helping this already far better than not knowing what to try.

There an issue, maybe we have to deal with it another way.

It would be nice having some enlightenments from someone who knows what's behind.

**Comment by bnauta** [comment]
@MacKentoch inspect your source path; confirm it resolves to the file/url you intend it to. Put it this way: If the source pointer is correct, you likely won't be running into a permissions issue.

@ssomnoremac, @LuisRizo, @harshsrivastavaglobussoft and I are all effectively saying the same thing

**Comment by LuisRizo** [comment]
@MacKentoch `image.sourceURL` worked perfectly on iOS on simulator, but when ran on real device, it was complaining about permission errors regarding accessing a file using: `file://...` when I tried sending that image through HTTP requests.
Using `image.path` solved the issue.

**Comment by mehulnahar** [comment]
Use image.path instead of image.sourceUri
This worked for me :)

**Comment by ricardomalagon** [comment]
Hi i have the same inssue with videos but if i put video.path the error disappear but have a horrible quality and when i put video.sourceURL have a good quality but show me the error, any solution for this? i need it with good quality
