### ISSUE TITLE
Strange padding shows up on IOS+ screens

### ISSUE THREAD

**Issue by sonaye** [facebook/react-native#16796]
I noticed a strange effect showing on IOS larger screen devices, the plus models show an extra padding it seems.

With the exact same code:

iPhone 8
<img width="426" alt="screen shot 2017-11-12 at 6 31 49 pm" src="https://user-images.githubusercontent.com/23000873/32700569-038076ae-c7d8-11e7-912e-1444bd6c06ae.png">

iPhone 8 Plus
<img width="433" alt="screen shot 2017-11-12 at 6 29 56 pm 1" src="https://user-images.githubusercontent.com/23000873/32700572-0c1d0dcc-c7d8-11e7-96b2-0619f115f852.png">

Is there an explanations for this? and how can we avoid it?

**Comment by lukemiles** [comment]
You're probably using `0.5`/half points for your border-width, which has weird side effects on 3x screens

**Comment by sonaye** [comment]
You are probably right about this, I believe I am using `StyleSheet.hairlineWidth`, I'll check and confirm here.

**Comment by sonaye** [comment]
Turned out to be 0.5 indeed, https://github.com/sonaye/react-native-actually-usable-prompt/blob/master/src/styles.js#L37

**Comment by sonaye** [comment]
`StyleSheet.hairlineWidth` fixes the issue, thanks.
