### ISSUE TITLE
Continue with debugging after publish release version  (Android)

### ISSUE THREAD

**Issue by mriza1815** [facebook/react-native#16793]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

No

### Environment
  Environment:
    OS:  macOS
    Ide : Android Studio
    Emulator : Adb, genymotion

  Packages: (wanted => installed)
    react-native: 0.45.1 => 0.45.1
    react: 16.0.0-alpha.12 => 16.0.0-alpha.12
    native-base : 2.1.4 => 2.1.4

  Target Platform: Android (23)

### Steps to Reproduce
1.  Make offline bundle with " react-native bundle"
2.  Generated signin apk
3.  Published on google play
4.  Running "react-native run-android" for continue with development, want to see dev menu

### Expected Behavior

Want to running apk from react packager (development server) and continue debugging with development mode

### Actual Behavior
1. App open on emulator and immediately crash
2. Got this error on android monitor logcat : "Unable to load script from assets 'index.android.bundle'.Make sure your bundle is packaged correctly or you are running a package server.""

### More Info
If a created index.android.bundle file with react-native bundle, debug-apk work. But can't reach development menu. I don't want to offline mode on debug, i want to running from local server so i continue my development. In ios, everything working correctly
I also tried this commands : 
1. react-native start > /dev/null 2>&1 &
2. adb reverse tcp:8081 tcp:8081
3.  Change package name
4. Trying different os (ubuntu)
5. Delete all node, all tmp and install again
6. start packager with delete cache

**Comment by yinghang** [comment]
Did you build the app in release mode?

**Comment by mriza1815** [comment]
@yinghang Yes. But i found my own solution. 
Somehow i added this import  "import com.facebook.react.BuildConfig;" on MainApplication.java. I deleted this line and problem solved
Thanks for the reply

**Comment by StanislavSergeev** [comment]
Hi, @mriza1815 
I have same issue.
However I don't have 
import com.facebook.react.BuildConfig;

I need some help.
Thanks.
