### ISSUE TITLE
NSNull Length exception thrown while invoking multiSet on target AsyncLocalStorage - unhandled exception crashes app on iOS

### ISSUE THREAD

**Issue by ZachCurtis** [facebook/react-native#16808]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

  Environment:
    OS:  Win 10 1703 OS Build: 15063.674
    Node:  4.6.1
    Yarn:  --
    npm:  5.5.1
    Watchman:  --
    Xcode:  --
    Android Studio:  --

    "expo": "^22.0.2",
    "react": "16.0.0-beta.5",
    "react-native": "^0.49.5",
    "react-native-auth0": "^1.2.1",
    "react-native-canvas": "^0.1.20",
    "react-native-maps": "^0.17.1",
    "react-navigation": "^1.0.0-beta.19"

  Target Platform: iOS (11)

### Steps to Reproduce

NSNull unhandled exception leading to total application crash when attempting to call AsyncStorage.setItem('justAString').

Cannot try/catch/finally to prevent crash, suggest adding exception handler.

### Expected Behavior

An error message should have been thrown with the promise associated with setItem. 

### Actual Behavior

Expo displays this exception and stack trace for less than a second before crashing the Expo instance.
![image](https://user-images.githubusercontent.com/31259055/32723078-23fc4f90-c83a-11e7-9d13-ea367ea1383b.png)

### Reproducible Demo

```javascript
import React, { Component } from 'react';
import { AsyncStorage } from 'react-native';

replaceLocal('StringParam')

export async function replaceLocal(key,newObj){
    try {
        let stringObject = JSON.stringify(newObj)
        AsyncStorage.setItem(key,stringObject)
    } catch (error) {
        console.log(error)
    }
}
```

**Comment by adricos** [comment]
Is it possible to reopen this bug? We are facing a similar issue. (react-native 0.51)

**Comment by andyh2** [comment]
We eliminated this issue in our RN codebase at comma.ai by ensuring we never setItem(key, null). 

Not sure if this qualifies as a bug given the AsyncStorage.setItem is documented to expect a non-null string value parameter.

**Comment by fuxximus** [comment]
still a problem on setItem on existing key

**Comment by cbartondock** [comment]
I am having this exact same issue. I already check that the value being stored isn't null

**Comment by hellgirl** [comment]
Same here. It works fine when loading build in expo but fails in TestFlight. 
Values are empty strings.

**Comment by niraj002** [comment]
I am having this same issue while storing a json file in the async and then using it later. Is there any way to get past this

**Comment by yuoppp** [comment]
The issue is still present.

**Comment by sewign** [comment]
Issue still present

**Comment by LipeEng** [comment]
Issue still present.

**Comment by lubnaski** [comment]
Facing the same issue. Anyone can help?

**Comment by tmswartz12** [comment]
I am experiencing the same issue!

**Comment by Shamar22** [comment]
For anyone still experiencing the same problem, check all parameters.  An example of where the problem could occur would be calling a reducer from another reducer.  A mistake would be to access a payload's prop inside the first reducer and then attempt to access a non-existent prop within the reducer being called.  

@ZachCurtis  You are calling the replaceLocal function with one parameter when it requires two.  If you console.log(newObj), you will see that it is undefined.

**Comment by Zopitirik** [comment]
hi,

use JSON.stringify(value) solved my problem.

AsyncStorage.setItem("myKey", JSON.stringify("myValue"));
