### ISSUE TITLE
RCTImageFromLocalAssetURL is loading image from web

### ISSUE THREAD

**Issue by douglasjunior** [facebook/react-native#16800]
### Is this a bug report?

I dont know if this is a Bug.

The [docs](https://github.com/facebook/react-native/blob/1e8f3b11027fe0a7514b4fc97d0798d3c64bc895/React/Base/RCTUtils.h#L123) says that `RCTImageFromLocalAssetURL` loads only local images.

> // Returns an UIImage for a local image asset. Returns nil if the URL
> // does not correspond to a local asset.

But in recent version of RN, it is also loading [image from web](https://github.com/facebook/react-native/blob/e846a9f82fb7a7dcfe6f55d40c3e4cd3c9b17e77/React/Base/RCTUtils.m#L685) (https). I think that this is related to https://github.com/facebook/react-native/commit/998197f444aca06cde0d5258469b3d314f8ea8b9.

My question is, this is intentional? Because this breaks the docs and my previous logic.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes.

### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 6.11.3
  Yarn: 1.3.2
  npm: 5.5.1
  Watchman: 4.9.0
  Xcode: Xcode 9.1 Build version 9B55
  Android Studio: EAP AI-171.4429293 AI-171.4429293

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.50.3 => 0.50.3

### Steps to Reproduce

Call `RCTImageFromLocalAssetURL` with a web image URI.

### Expected Behavior

Return `nil` if a non local image is provided.

### Actual Behavior

It is loading image from the web.

**Comment by janicduplessis** [comment]
cc @sahrens Since you reviewed this

**Comment by douglasjunior** [comment]
The problem still exists.

**Comment by douglasjunior** [comment]
The problem still exists.

**Comment by rodrigobdz** [comment]
@hramos could you reopen this issue? I can confirm that the issue is still happening in the latest React Native version `v0.56.0`.

> But in recent version of RN, it is also loading [image from web](https://github.com/facebook/react-native/blob/e846a9f82fb7a7dcfe6f55d40c3e4cd3c9b17e77/React/Base/RCTUtils.m#L685) (https). I think that this is related to 998197f.

The link to the snippet loading an image from the web is [still present](https://github.com/facebook/react-native/blob/e9e20e6c8335f27af8469cd23cb7ba079b0422f9/React/Base/RCTUtils.m#L713) in `RCTUtils.m`.

**Comment by hramos** [comment]
Reopening, it would be great to see a code snippet that reproduces this. I am aware there's already repro steps, but ideally an issue would contain a code snippet that can be easily dropped into a new project.

**Comment by rodrigobdz** [comment]
Thanks. @douglasjunior Do you have a [MCVE](https://stackoverflow.com/help/mcve) for this issue?

**Comment by douglasjunior** [comment]
Hello everyone, sorry for the delay. I found this problem while working in an image viewing library.

Here is the PR where I explain the problem: https://github.com/alwx/react-native-photo-view/pull/122

**Comment by cpojer** [comment]
This was an intentional change the documentation should be updated to reflect it.
