### ISSUE TITLE
Switching between TextInputs with values does something funny to the keyboard

### ISSUE THREAD

**Issue by KirMcC** [facebook/react-native#16819]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes 👍 

### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.1.0
  Yarn: 0.19.1
  npm: 5.5.1
  Watchman: 4.6.0
  Xcode: Xcode 9.0 Build version 9A235
  Android Studio: Not Found

Packages: (wanted => installed)
  react: ^16.0.0-beta.5 => 16.0.0-beta.5
  react-native: ^0.49.5 => 0.49.5

### Steps to Reproduce

(Write your steps here:)

1. Add two simple `<TextInput />` ( can even use react natives [example](https://facebook.github.io/react-native/docs/textinput.html) )
2. Make sure both `<TextInput />` have values in them and autoCapitalize is set to `default`
3. Then switch between the two inputs ( better tested on a phone ).
### Expected Behaviour

Simply when focusing on a new `<TextInput />` with a value, the keyboard should not shift from Uppercase to Lowercase

### Actual Behaviour

When navigating between the two `TextInput` components the keyboard for some reason starts with uppercase keyboard, then quickly changes to lowercase.

Example below is a bare bone of react native using Expo.

 
![gif](https://user-images.githubusercontent.com/9655830/32782410-39c750ca-c940-11e7-8dfb-78044e0c812e.gif)

### Reproducible Demo

[Link to simple demo](https://snack.expo.io/r1B7TDOyM)
Continually tap between the two `<TextInputs/>` and you should notice the keyboard flickers between uppercase and lowercase.

**Comment by omar-dev** [comment]
Hi @KirMcC, I think you missed that you are changing the first input in the setState on both text inputs.
```javascript
_handleTextChange = inputValue => {
    this.setState({ inputValue });
};
```
see your modified [demo](https://snack.expo.io/H1nPUcO1f).

**Comment by KirMcC** [comment]
Ah my bad on that part @omar-dev . But doesn't fix the issue :(. Still set's the keyboard to uppercase first then switches to lowercase. Only if you have values in the `TextInputs` components and `autoCapitalize` is set to `default`. Setting the inputs to autoCapitalize ='none' doesn't bug out the keyboard, but I can't have all inputs set like this.

I'm still able to input/update values okay, but seeing the keyboard flicker when focusing on the next input looks terrible.

**Comment by omar-dev** [comment]
@KirMcC yes I missed that one, hope it got fixed soon. 
Thanks.
