### ISSUE TITLE
[FlatList] When you scroll to fast the motion never stop.

### ISSUE THREAD

**Issue by AugustoAleGon** [facebook/react-native#16812]
### Is this a bug report?

Yes, it is a bug report.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.)

### Steps to Reproduce

(Write your steps here:)

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by lazzy930529** [comment]
I have the same problem..

**Comment by AugustoAleGon** [comment]
I recently discover how to solve it. Check your warnings. You will see a message that says: `Wrapped shouldn't be used in Pure Components`. So basically just remove the `flex-wrap: wrap` and make the changes to have the same result.
