### ISSUE TITLE
[RN 0.25.1] _reactNative.DeviceEventEmitter.removeListener is not a function 

### ISSUE THREAD

**Issue by 12343954** [facebook/react-native#16811]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

  Environment:
    OS:  macOS Sierra 10.12.6
    Node:  v8.2.1
    Yarn:  NO
    npm:  5.5.1
    Watchman:  4.9.0
    Xcode:  Version 8.3.3 (8E3004b)
    Android Studio:  NO

  Packages: (wanted => installed)
    react-native: 0.25.1
    react: ^0.14.9

  Target Platform: iOS (10.3)

### Steps to Reproduce

(Write your steps here:)

1.
`componentDidMount() {
		//Alert.alert('xx',this.state.user.FName+' ')
		this.watchID = navigator.geolocation.watchPosition((position) => {
			var lastPosition = JSON.stringify(position);
			this.setState({ lastPosition });
		});
		console.log('this.watchID')
		console.log(this.watchID)
	}`

`**componentWillUnmount() {  // here is the bug**
			navigator.geolocation.clearWatch(this.watchID);
	}`

2. when unmount , appear this error
`_reactNative.DeviceEventEmitter.removeListener is not a function `

3.

### I don't want upgrade RN to other version，because it will occur lots of error，that's too bad！

(Write what you thought would happen.)

### I do catch error，but can't catch the error
```
componentWillUnmount() {
		try {
			navigator.geolocation.clearWatch(this.watchID);
			debugger;
		} catch (error) {
			console.log(error)
		}
		// debugger;
	}
```

(Write what happened. Add screenshots!)
![image](https://user-images.githubusercontent.com/1804003/32727266-ec91e70e-c8b6-11e7-9872-0cf9668aa5c6.png)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by hramos** [comment]
Hey! 0.25.1 is quite old at this point. Please try a newer version and submit a new issue if needed.
