### ISSUE TITLE
UI Freeze on Remote Debugger Enabled

### ISSUE THREAD

**Issue by racerxdl** [facebook/react-native#16813]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

```
┌─[lucas@nblucas] - [~/Works/Quanto/quanto-backend/pushtest] - [Seg Nov 13, 14:48]
└─[$] <git:(LucasT*)> react-native info 
Scanning 586 folders for symlinks in /home/lucas/Works/Quanto/quanto-backend/pushtest/node_modules (4ms)

Environment:
  OS:  Linux 4.6
  Node:  6.11.4
  Yarn:  0.27.5
  npm:  3.10.10
  Watchman:  4.1.0
Error: unable to print environment info
{ Error: not found: xcodebuild
    at getNotFoundError (/home/lucas/Works/Quanto/quanto-backend/pushtest/node_modules/which/which.js:13:12)
    at Function.whichSync [as sync] (/home/lucas/Works/Quanto/quanto-backend/pushtest/node_modules/which/which.js:134:9)
    at getXcodeVersion (/home/lucas/Works/Quanto/quanto-backend/pushtest/node_modules/envinfo/envinfo.js:17:25)
    at Object.module.exports.print (/home/lucas/Works/Quanto/quanto-backend/pushtest/node_modules/envinfo/envinfo.js:136:28)
    at Object.info (/home/lucas/Works/Quanto/quanto-backend/pushtest/node_modules/react-native/local-cli/info/info.js:17:13)
    at Promise.resolve.then (/home/lucas/Works/Quanto/quanto-backend/pushtest/node_modules/react-native/local-cli/cliEntry.js:109:26)
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9) code: 'ENOENT' }
```

### Steps to Reproduce

1. Create a react native app
2. Add https://github.com/orhan/react-native-openpgp / https://github.com/akyGit/react-native-openpgp module to the project
3. Just `import * as openpgp from 'react-native-openpgp';` anywhere.
4. Attach the debugger.

### Expected Behavior

App open normally and works.

### Actual Behavior

UI Freezes. Nothing shows up. The "shake" menu still works.

![image](https://user-images.githubusercontent.com/578310/32737827-4540830e-c882-11e7-9b54-5a0dec86a583.png)

(Write what happened. Add screenshots!)

### Reproducible Demo

That's simple to reproduce, just create a new react-native project with create-react-native-app and add the `react-native-openpgp` as normal. If you just import the module (anywhere, doesn't matter where, I imported in App.js) and attach the debugger to the project, it will freeze the UI. If the debugger isn't attached, everything works fine.

I'm running on Android Emulator x86 - 6.0.0, but also tested on a Galaxy S5 (5.0) and a Galaxy S8 (7.0) and all shows the same problems. One of my co-workers also tested on a iPhone 5S and it exibited the same issue (so it is probably on the Javascript side, not native side).

### Side comments

That library (both orhan and akyGit) works fine if the debugger is not attached, but when I attach, the UI Freezes and gives a white screen. The thing is that I dont need to call anything, just importing. I tried to debug to find where is the issue but I couldn't. There seens to be nothing wrong with both base codes, so it might be a bug on react-native, still I can't find what's causing it (since if I go step by step in the debugger, it even calls `render()`).

First I though it might be the WebWorker that it spaws, but checking the code for the akyGit version, it looks like the webworker never get spawned.

**Comment by racerxdl** [comment]
Sadly, it hasn't been fixed :/

**Comment by nezaidu** [comment]
Any update on this? still experiencing this on android for RN 54

**Comment by racerxdl** [comment]
Sadly, it hasn't been fixed :/ [2]

**Comment by racerxdl** [comment]
Not fixed. sadly.
