### ISSUE TITLE
Something went wrong while linking. Error: Cannot read property 'nodeValue' of undefined

### ISSUE THREAD

**Issue by whitebunny890202** [facebook/react-native#16817]
I was going to add custom font into React Native project.

First, I added follow code into package.json 
"rnpm": {
    "assets": [
      "assets/fonts"
    ]
  }

Next, I copied ttf file into /assets/fonts

Then , I run  "react-native link"

At that time, I see the error message like the issue title.
How can I solve this problem? Looking forward expert response.
Thanks.

**Comment by bhaskartalluri999** [comment]
Open info.plist in xcode and remove
empty key value  like 
<key></key>
<string></string>

**Comment by bhaskartalluri999** [comment]
<key></key>
<string></string>

**Comment by bhaskartalluri999** [comment]
open info.plist in xcode and remove empty key value like,
<key></key>
<string></string>
