### ISSUE TITLE
`fontWeight: bold` does not work with other styling properties for TextInput on iOS

### ISSUE THREAD

**Issue by ethanyuwang** [facebook/react-native#16829]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.)

### Environment

Environment:
  OS: macOS High Sierra 10.13.1
  Node: 6.11.3
  Yarn: Not Found
  npm: 4.6.1
  Watchman: 4.9.0
  Xcode: Xcode 9.1 Build version 9B55
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: ^0.49.5 => 0.49.5

### Steps to Reproduce

(Write your steps here:)

```
            <TextInput
              style={{fontSize: TITLE_SECONDARY,
                color: COLOR_DARK_PRIMARY,
                fontWeight: 'bold',}}
              editable={this.state.expand}
              value={"well"}
              placeholder="Company Name"
            />
```
I have a TextInput with style of `fontWeight: 'bold'`. It  would not render the text as bold, even though Element Inspector says it has the property of `fontWeight: 'bold'`

If I remove other styling properties and only keep `fontWeight: 'bold'`, the Text appears to be bold.

This only happens on iOS

### Expected Behavior

Text should be rendered as bold

### Actual Behavior

Text is not rendered as bold when there are other styling properties:

![simulator screen shot - iphone 8 - 2017-11-14 at 18 23 51](https://user-images.githubusercontent.com/17556945/32815477-235901b6-c969-11e7-9881-5af156c1ef0f.png)

Text is rendered as bold when there is only `fontWeight: 'bold'` in style:

![simulator screen shot - iphone 8 - 2017-11-14 at 18 24 08](https://user-images.githubusercontent.com/17556945/32815659-f64b310c-c969-11e7-82f7-9a9d86c36cbd.png)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by lwinkyawmyat** [comment]
It worked for me 💯 %. You can check on [snack](https://snack.expo.io/H1q71TPWG). So, we should close this issue.

**Comment by lwinkyawmyat** [comment]
@facebook-github-bot close
