### ISSUE TITLE
section list header search bar looses focus when the search results in an empty list

### ISSUE THREAD

**Issue by tharungeorgebabu** [facebook/react-native#16824]
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.) yes

### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 7.9.0
  Yarn: 1.0.2
  npm: 5.4.2
  Watchman: 4.7.0
  Xcode: Xcode 9.0 Build version 9A235
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.50.0 => 0.50.0
  Target Platform: iOS (10.3)
### Steps to Reproduce

(Write your steps here:)

1.use section list
2.add a header callback with a search bar
3.the search when resulting in an empty list results in the search bar on header to loose focus

### Expected Behavior

(Write what you thought would happen.)

the focus should stay on the input field even if the list was empty
### Actual Behavior
 the focus went away from the input field

(Write what happened. Add screenshots!)
the focus went away from the input field when no results where returned by the search
### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by tharungeorgebabu** [comment]
The issue happens when using ListHeaderComponent of section list &
when the search results in zero results

**Comment by tharungeorgebabu** [comment]
can someone pls look into this issue ?

**Comment by piloulac** [comment]
I have the same problem here! 
I'm then not able to find Header Search Path with a new react native project (that I just created: 11/23/2017)
Below  two screenshots: 
-normal
<img width="762" alt="screen shot 2017-11-23 at 12 30 56" src="https://user-images.githubusercontent.com/22507697/33158114-8a3bb1fc-d04a-11e7-9f49-b6882e309f98.png">
-problem
![Uploading Screen Shot 2017-11-23 at 12.32.27.png…]()

**Comment by piloulac** [comment]
Hey, 
I found a really dirty workaround. 

You can for example just: 
`npm i react-native-vector-icons --save && react-native link react-native-vector-icons`

It will make appear the header search paths. Then you can play with it.
And after your can unlink and uninstall react-native-vector-icons!

**Comment by tharungeorgebabu** [comment]
never saw this fixed

**Comment by arielpollack** [comment]
Yes, its still happens.

When a text field is rendered as (or part of) the `SectionList` header component, it renders everytime the list is re-rendered.
The most common use case, which is filtering the SectionList through the text field, cause a re-render and then also re-render the text field itself which lose its focus.

The expectation would be to not re-render the section's header component on data change.

**Comment by Niryo** [comment]
same issue here. react-native: 0.51.6

**Comment by damikdk** [comment]
Any ideas how to fix this? Reproduced on all 0.5x RN

**Comment by jgautheron** [comment]
Same issue here, `0.57.1`.
