### ISSUE TITLE
The StatusBar barStyle in android5.1 is invalid

### ISSUE THREAD

**Issue by Yiiu** [facebook/react-native#16827]
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

yes

### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.4.0
  Yarn: 1.0.0
  npm: 5.3.0
  Watchman: 4.9.0
  Xcode: Xcode 9.0.1 Build version 9A1004
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.50.3 => 0.50.3

### Steps to Reproduce

demo1:

```jsx
<StatusBar barStyle="dark-content" />
```

demo2:

```jsx
<StatusBar barStyle="light-content" />
```

### Expected Behavior

I want demo1 status bar text color to white, demo2 status bar text color is black, but it is invalid in android5.1, the status bar text color is always white.android6.0 is ok. I do not know what to do.

### Actual Behavior

is android5.1.

I change barStyle and the color of the status bar is always white.

demo:

![demo1](https://i.loli.net/2017/11/15/5a0b9d8caa10c.png)
![demo2](https://i.loli.net/2017/11/15/5a0b9f8fd6890.png)

### Reproducible Demo

Need android5.1, no demo

**Comment by Mrshutao** [comment]
I have the same problem,have you resolved it ?

**Comment by Yiiu** [comment]
@Mrshutao I have not resolved,Had to change the statusbar translucent

**Comment by laszhiai** [comment]
https://dev.mi.com/console/doc/detail?pId=1159

**Comment by laszhiai** [comment]
![sb](https://user-images.githubusercontent.com/19182850/35134477-8e66e794-fd11-11e7-9715-b20190e2fece.png)

**Comment by wedneyyuri** [comment]
Maybe it's related to https://github.com/facebook/react-native/issues/16432 because it's not working:

```jsx
<StatusBar translucent={false} />
```
