### ISSUE TITLE
clarification request for removing android_react_native_perf.use_separate_ui_bg_thread experiment

### ISSUE THREAD

**Issue by hey99xx** [facebook/react-native#16825]
### Is this a bug report?

No, but it's a clarification request from FB devs on a recent commit.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Android RN 0.51 above

### Steps to Reproduce

Last night this commit https://github.com/facebook/react-native/commit/4f886a29a1234c967deae2354bbc5092e0e6595e seems to remove UI-Background thread in React Native source code.

This looked like a very beneficial change in the first look, and I was experimenting with it. I understand some changes fail to reach the high-quality bar, or they're difficult to maintain, or there's some other reason that leads to their removal. In this case, I do not know what happened with it. All the commit message says is:

> Remove android_react_native_perf.use_separate_ui_bg_thread experiment.

I have an app with infinite scroll views with lots of cards (similar to FB news feed on mobile) and multiple connections opened to fetch more data from the backend. Each card contains quite heavy views such as image carousels. We right now have lots of congestion in the native module thread, so I though this would be a solution to that.

Can I please ask for a clarification for why you did do this change in the first place, and what led you to remove it? If it still aligns with the needs of my app, and if it's not horribly buggy I may revert this commit in my company's RN version (we have capacity to maintain an internal fork, if this will lead to actual performance improvements).

### Expected Behavior

I would have liked to this experiment.

### Actual Behavior

It seems I won't be able to.

**Comment by MacKentoch** [comment]
Sad but interesting.

Apart from synchronization issues I don't understand this removal.

**Comment by chirag04** [comment]
cc @AaaChiuuu @hramos

**Comment by hey99xx** [comment]
Just commenting so the mods don't close this with the Ice-Box label. It'd be nice to have an answer even it's simply, "it was buggy so now it's gone"

**Comment by hey99xx** [comment]
Commenting one more time to make this non-stale. If it gets stale again, I'm just going to let it be closed.
