### ISSUE TITLE
RTCBridge is always nil.

### ISSUE THREAD

**Issue by JakielaAdam** [facebook/react-native#16828]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Cannot run react-native info because of earlier version.

react-native-cli: 2.0.1
react-native: 0.36.1

Environment:
    OS:  macOS Sierra 10.12.6
    Node:  8.1.4
    Yarn:  not installed
    npm:  5.0.3
    Watchman:  4.7.0
    Xcode:  Version 9.1 (9B55)
    Android Studio:  2.3.3

Target Platform: iOS (11.1)

### Steps to Reproduce

I have been using React Native in our software without problem for over a year now. After a recent update to XCode and upgrading a lib from one of our business partners, I can no longer reference the `RTCBridge` from one of our native components since it is always `nil`. 

I have a native Swift component which I integrate into the app via a bridgin header. The origanization looks like this:

**BLEScanner.swift (This is the native component)
BluetoothModuleBridge.m 
Module-Practive-Bridging-Header.h (The bridging header)**

Relevant code snippets from each file:

**BLEScanner.swift**

```
import Foundation

@objc(BLEScanner)
class BLEScanner: NSObject {
  
  //....

  var bridge: RCTBridge!  // THIS IS ALWAYS NIL

  //....

  @objc func requestBluetoothState() -> Void {
    print("REQUEST BLE STATE")
    let ret = [
      "enabled" : true
    ]

    //THIS LINE WILL FAIL BECAUSE bridge IS NIL
    self.bridge.eventDispatcher().sendDeviceEvent(withName: "BluetoothStateEvent", body: ret)
  }

}

```
**BluetoothModuleBridge.m** 

```
#import "RCTBridgeModule.h"

@interface RCT_EXTERN_MODULE(BLEScanner, NSObject)

RCT_EXTERN_METHOD(requestBluetoothState)

@end

```
**Module-Practive-Bridging-Header.h** 

```
// BluetoothModule-Bridging-Header.h
#import "RCTBridge.h"
#import "RCTBridgeModule.h"
#import "RCTEventDispatcher.h"
#import "RCTRootView.h"
#import "RCTUtils.h"
#import "RCTConvert.h"

#import "AppDelegate.h"
#import "BugsnagReactNative/BugsnagReactNative.h"

```

### Expected Behavior

`bridge` in BLEScanner.swift file should not be `nil`.

### Actual Behavior

bridge is BLEScanner.swift is nil.

### Reproducible Demo

Skipping because this is specific to my project.

### Other Comments

My apologies if I am not giving much information to solve this issue. Admittedly, I am very puzzled myself on why this could happen so I have trouble giving relevant info on the issue. At a minimum, if someone could provide steps to make sure I have my project set up properly, this would be very helpful.

**Comment by benhurott** [comment]
+1

**Comment by benhurott** [comment]
I found a possible solution (works for me =P).

You create your swift class and (like me) use it in other places than `BluetoothModuleBridge.m`.

The problem is: then your javascript use native module, it uses the default singleton module provided by `BluetoothModuleBridge.m`. In this case, the `bridge` IS injected. 
When you call a method from your swift code inside another native code directly, the bridge is nil because RN can't inject this property.

What i do:

I create my swift file normaly:
```swift
import Foundation


@objc(SzSalesForceSdk)
class SzSalesForceSdk: RCTEventEmitter {
  private var appId: String = ""
  private var accessToken: String = ""
  
  private var waitingNotification: SzSalesForcePushData? = nil
  private var isConfigured: Bool = false
  
  @objc(start:accessToken:resolver:rejecter:)
  func start(appId: String,
                   accessToken: String,
                   resolver resolve: RCTPromiseResolveBlock,
                   rejecter reject: RCTPromiseRejectBlock) -> Void {
    self.appId = appId
    self.accessToken = accessToken
    
    self.configureForLauching()
    resolve(true)
  }

//...
```

And create my obj-c file normaly too:
```objective-c
#import <Foundation/Foundation.h>

#import "RCTBridgeModule.h"
#import "RCTEventEmitter.h"

@interface RCT_EXTERN_MODULE(SzSalesForceSdk, RCTEventEmitter)

RCT_EXTERN_METHOD(start:(NSString *)appId accessToken:(NSString *)accessToken resolver:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)

RCT_EXTERN_METHOD(getWaitingNotification:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)

RCT_EXTERN_METHOD(testFakePush)
RCT_EXTERN_METHOD(supportedEvents)

@end
```

NOW LOOK THIS TRICK:

In my `AppDelegate.h`, I added the following property: `@property (nonatomic, strong) RCTBridge *bridge;`

```objective-c
#import <UIKit/UIKit.h>
#import "RCTRootView.h"

@interface AppDelegate : UIResponder <UIApplicationDelegate>

@property (nonatomic, strong) UIWindow *window;

@property (nonatomic, strong) RCTBridge *bridge;

@end
```

In my `AppDelegate.m`, I replace the default RootView creation:
```objective-c

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  NSURL *jsCodeLocation;

  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];

  _bridge = [[RCTBridge alloc] initWithBundleURL:jsCodeLocation moduleProvider:nil launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:_bridge moduleName:@"myapp" initialProperties:nil];

//...
```

To use my custom module, we create in `AppDelegate.m` the following method:
```objective-c
- (SzSalesForceSdk *)getSzSalesForceSdkModule
{
  return [_bridge moduleForName:@"SzSalesForceSdk"];
}

@end
```

And now i can use it:
```objective-c
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler
{
  [[self getSzSalesForceSdkModule] didReceiveRemoteNotification:userInfo];
  completionHandler(UIBackgroundFetchResultNoData);
}
```

This is a intergalactic workaround, I'll sleep well tonight =P.
