### ISSUE TITLE
Hot Reloading - Packager does not rebuild code

### ISSUE THREAD

**Issue by MajPay** [facebook/react-native#16835]
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

No

### Environment

Environment:
  OS:  Linux 4.10
  Node:  7.10.0
  Yarn:  1.3.2
  npm:  4.2.0
  Watchman:  4.9.0
  Xcode:  N/A
  Android Studio:  Not Found

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: 0.49.3 => 0.49.3

Target Platform: Android (7.0)

### Steps to Reproduce

This is very hard to tell, it suddenly broke... init a new react-native project and work a while, maybe it breaks too?

### Expected Behavior

Like it was, i expect that the packager will rebuild the app once i change something.

### Actual Behavior

"Hot reloading" does not work anymore. Everything used to work really well until some days ago. I dont know what changed but the functionality broke and that is very inconvenient. Once i apply changes to my code i can see the toast message "Hot Loading..." on my phone, so the "watching" seems to work. But i cant see the "bundling `index.js`..." line in my terminal (where i am running the packager via npm start or react-native start). Using the android emulator does not change anything.

If i shake the phone, which brings up the dev menu and select "Reload" i can actually see the bundling in the packager process (in my terminal) and the app reloads correctly.

In [this issue](https://github.com/facebook/react-native/issues/10889) i read, that a .lock file may prevent watchman from detecting the change, so i moved my yarn.lock to _yarnlock to test that. But that did not work (i also restarted the packager with [ctrl]+C and re-running npm start).

Reinstalling watchman (from source again) did not change the behavior either.

### Reproducible Demo

nope

**Comment by OmarMahili** [comment]
https://github.com/facebook/react-native/issues/16505

**Comment by anchetaWern** [comment]
had to enable hot reloading and then live reload, then I reload JS before I got it to work.
