### ISSUE TITLE
stuck at Loading Dependency Graph then Bundling `index.js`  [development, non-minified]  ░░░░░░░░░░░░░░░░  0.0% (0/1)

### ISSUE THREAD

**Issue by avalond** [facebook/react-native#16838]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

  Environment:
    OS:  macOS High Sierra 10.13.1
    Node:  8.9.1
    npm:  5.5.1
    Watchman:  4.9.0
    Yarn:not install
    Flow: 0.58.0
    Xcode:  Xcode Version 9.1 (9B55)
    Android Studio:  Version 9.1 (9B55)

  Packages: ( installed)
    react-native: 0.50.3
    react: 16.0.0
   
 android :5.0.2,linegeos14.1, aosp8.0
 ios:11.1.1,9.3.3

### Steps to Reproduce

1.create new react native project use this 'react-native init AwesomeProject'
2.cd AwesomeProject
3. npm start 
4. react-native run-android

### Expected Behavior

loading view show hello react native 

### Actual Behavior

is not working stuck at Loading Dependency Graph [....]

![screenshot_2017-11-15-20-18-33-287_com awesomeproject](https://user-images.githubusercontent.com/5616958/32836236-2336e17c-ca44-11e7-8671-5669570c4f3e.png)
<img width="605" alt="qq20171115-203416 2x" src="https://user-images.githubusercontent.com/5616958/32836339-6d646fe4-ca44-11e7-8144-cda69767cd70.png">

### Reproducible Demo

this is my project [](https://github.com/avalond/awesomeproject_react-native)
https://github.com/avalond/awesomeproject_react-native

**Comment by avalond** [comment]
i reproducible project i push all code, please help me, thank you

**Comment by ragamufin** [comment]
Having the same issue but only on iOS. The only way I get around it when it happens is to open XCode, clean build folder and build the project again. This seems to take a God-awful long time but once it's done, I am able to launch the project again from the terminal and the loading dependency graph gets to done

**Comment by avalond** [comment]
@ragamufin but in my local i clean build folder and build the project agion,both android and ios is not worked, strange

**Comment by tc0087** [comment]
Same. Android build gets stuck at Loading dependency graph, done and says "could not connect to development server".  Adb reverse does not work.  iOs build does not bundle. I run react-native run-ios a second time and the project then builds.  Does anyone know why this started happening about a week ago and how it can be resolved?

**Comment by uKL** [comment]
I'm experiencing the same issue with a clean sample "AwesomeProject". It's stuck bundling. I'm using Mac OS X High Sierra.

**Comment by ungacy** [comment]
+1

**Comment by latpaw** [comment]
same problem

**Comment by AllenWen** [comment]
I got the same problem!!

**Comment by ungacy** [comment]
@latpaw Thx, problem solved!

**Comment by AbrahamMan** [comment]
brew uninstall watchman
then 
brew install watchman
fix the problem

**Comment by guguji5** [comment]
thanks for saving my time

**Comment by guguji5** [comment]
I find the watchman is a bug, I remove it as all, refresh my app manually

**Comment by Deepjyoti120** [comment]
sir, how to fix them i faces same problem how to delete wtchman please reply sir
