### ISSUE TITLE
[Android] Image not creating video thumbnail

### ISSUE THREAD

**Issue by FacuAcosta** [facebook/react-native#16839]
### Is this a bug report?
Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?
Yes

### Environment

Environment:
  OS:  macOS High Sierra 10.13.1
  Node:  6.10.0
  Yarn:  0.21.3
  npm:  5.5.1
  Watchman:  4.7.0
  Xcode:  Xcode 9.1 Build version 9B55
  Android Studio:  2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: 0.49.5 => 0.49.5

  Target Platform: Android (7.0)

### Steps to Reproduce

1. Create an Image component
2. Pass a video local uri to the source prop

### Expected Behavior
The expected behavior as seen in iOS is to see an image thumbnail for the video, corresponding to the first frame of the video.

### Actual Behavior
No image present on the Android environment.

iOS
![simulator screen shot - iphone 6 - 2017-11-15 at 12 35 11](https://user-images.githubusercontent.com/19332669/32836708-a9f32d8e-ca02-11e7-9de2-045e44b0f850.png)

Android
![screenshot_20171115-123548](https://user-images.githubusercontent.com/19332669/32836715-ae3f2410-ca02-11e7-84bc-a2b80d7cb4ac.png)

**Comment by bulats** [comment]
Experiencing the same issue.

**Comment by zanfirovidius** [comment]
I have the same problem on Android.... does any body have an workaround?
Thank you.
