### ISSUE TITLE
Website: Wrong React-Native version displaying on https://facebook.github.io/react-native/

### ISSUE THREAD

**Issue by suark** [facebook/react-native#16831]
**Steps to reproduce:** 

1. Go to https://facebook.github.io/react-native/
2. Look at the top right corner of the page.

![pageplusurl](https://user-images.githubusercontent.com/6233440/32821963-69906e4c-c993-11e7-85d3-b80265e62489.PNG)

It displays the current version number of 0.49 which is incorrect because the current version is now 0.50.

**More:**

1. If I click on the version number I see the link to the current version of the docs

![pagecurrentversionl](https://user-images.githubusercontent.com/6233440/32822080-048ba93e-c994-11e7-8f8f-5c45fea60643.PNG)
2. This just links to the same page https://facebook.github.io/react-native/ that displays 0.49

**More:**

1. If I manually type in this link http://facebook.github.io/react-native/releases/0.50/ then I end up on a page that looks better and displays the 0.50 in the version position.

![page050version](https://user-images.githubusercontent.com/6233440/32822195-96c6444e-c994-11e7-8ae1-178ef7d0352d.PNG)

**Questions:**

I want to contribute to fixing this, but I have a few questions that are currently blocking me.

1. When I manually go to http://facebook.github.io/react-native/releases/0.50/docs/getting-started.html I don't see any documentation for `SafeAreaView` which I know is a new feature, does that indicate that I'm not really seeing the docs for 0.50, or does it mean that the docs are just not there for `SafeAreaView` yet?

2. When I run the website locally, I don't see these links at all. Are the links and versions added in later?

![pagelocalversion](https://user-images.githubusercontent.com/6233440/32822744-3712090e-c997-11e7-9c60-68fb63c4f56d.PNG)

I'll keep digging into these things myself but comments are appreciated.

**Comment by jasperkuperus** [comment]
For people who might be looking for `SafeAreaView` documentation before this is fixed, you can also go here: https://github.com/react-community/react-native-safe-area-view
