### ISSUE TITLE
Use http://semver.org/

### ISSUE THREAD

**Issue by wlwl2** [facebook/react-native#16846]
I noticed in my apps and in the release notes that breaking changes are introduced with the versioning you are using. Would be nice if you followed this: http://semver.org/

**Comment by ide** [comment]
RN follows semver with npm’s added semantics. You can think of RN 0.50.2 as 50.2.x — shift everything over to the left by one number — this is how npm treats 0.x.y. Maybe we’ll just do that one day (ex: 51.0.0, 52.0.0, etc). Regardless, the first non-zero version is bumped with each major release (monthly) and minor releases (ex: 0.50.0 -> 0.50.1) tend not to have breaking changes and try to follow semver.

**Comment by wlwl2** [comment]
I'm reading https://docs.npmjs.com/getting-started/semantic-versioning, is there something I'm missing?

"Changes which break backwards compatibility: Major release, increment the first number, e.g. 2.0.0."
