### ISSUE TITLE
[Geolocation] does not return anything

### ISSUE THREAD

**Issue by jaulz** [facebook/react-native#1684]
Unfortunately the getCurrentPosition function does not call any of the given callbacks. Any idea what could be wrong in the following code? I also tried to set `NSLocationWhenInUseUsageDescription` to a custom value.

```javascript
class LocationAPI {
  getLocation() {
    return new Promise((resolve, reject) => {
      navigator.geolocation.getCurrentPosition(
        (position) => {
          debugger;
        },
        (error) => {
          debugger;
        },
        {
          enableHighAccuracy: true,
          timeout: 20000,
          maximumAge: 1000
        }
      )
    });
  }
}

module.exports = LocationAPI
```

**Comment by brentvatne** [comment]
Do you see any logs in the Xcode console? Is this in the simulator?

**Comment by jaulz** [comment]
Unfortunately no hint at all not in Chrome Debugger nor in XCode. Tried with a lower timeout and with HighAccuracy false as well. 

And yes it is in the simulator and location is enabled.

**Comment by jaulz** [comment]
Sorry but I found the issue. I was in debug mode and didn't see (neither expected) that Chrome asked me for the corresponding authorization to access my location. After accepting this my callbacks were fired. Though shouldn't the error callback be triggered anyway after the timeout was reached?

**Comment by pbasel** [comment]
> Though shouldn't the error callback be triggered anyway after the timeout was reached?

Don't know what difference would that make.

**Comment by browniefed** [comment]
@ide @brentvatne not sure if this should be closed or if error CB should be called on timeout?
