### ISSUE TITLE
Memory Leaks with iOS 11

### ISSUE THREAD

**Issue by ajwhite** [facebook/react-native#16843]
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

yes

### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 6.10.2
  Yarn: 0.24.5
  npm: 3.10.10
  Watchman: 4.7.0
  Xcode: Xcode 9.1 Build version 9B55
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 15.1.0 => 15.1.0
  react-native: 0.27.3 => 0.27.3

### Steps to Reproduce

This is not one that is easy to reproduce. We have a kiosk-mode application that begins to see memory issues after a long period of time on **iOS 11**.

### Expected Behavior

The application should remain stable over prolong periods of time.

### Actual Behavior

The application hits memory issues after devices have updated to iOS 11.

A few crashes have surfaced past out-of-memory sessions, all within the JavaScriptCore:
- `JSC::Heap::runNotRunningPhase(JSC::GCConductor)`
http://crashes.to/s/b9212ed75c4
- `JSC::Heap::finishChangingPhase(JSC::GCConductor)`
http://crashes.to/s/3abc177f424

Majority of the crashes are not reported as traceable crashes, as iOS will release the application without a specific crash ([more on that](https://code.facebook.com/posts/1146930688654547/reducing-fooms-in-the-facebook-ios-app/)).

It's important to note that this only began happening on **iOS 11**. We are on an early version of React Native, but we've seen similar crashes in `0.43`. We are upgrading to `0.50`, but are concerned this may still be a present issue.

**Comment by ajwhite** [comment]
Additional JSC crashes on React Native `0.43` with a session time of 2 minutes:

- `JSC::SlotVisitor::drain(WTF::MonotonicTime)::$_3::operator()(JSC::MarkStackArray&)`
http://crashes.to/s/a6c20098a4b
- `JSC::Heap::runCurrentPhase(JSC::GCConductor, JSC::CurrentThreadState*)` 
http://crashes.to/s/38139a3ec1a

**Comment by thatjuan** [comment]
I’m running into something similar when using FlatList and some third party libs. 

Could you post your packages list?

**Comment by AggarwalAnkit** [comment]
Getting the same crash on iPhone 8, OS version 11.0.1. Has anyone found out any solution yet?

**Comment by bsneha90** [comment]
I am getting the same issue. @ajwhite did the migration to 0.50 react-native fix the issue for you?
