### ISSUE TITLE
Unsupported top level event type "topLoadingStart" dispatched in Custom WebView

### ISSUE THREAD

**Issue by juangl** [facebook/react-native#16848]
### Is this a bug report?
I believe so.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes.

### Environment

 Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.7.0
  Yarn: 1.2.1
  npm: 5.4.2
  Watchman: 4.7.0
  Xcode: Xcode 9.1 Build version 9B55
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.50.3 => 0.50.3

  Target Platform: iOS (11.1)

### Steps to Reproduce

We implemented a Custom WebView. It used to work in RN 0.49 (we were using the components/WebView.ios.js from master). I'm not an Objective-C developer and probably I'm doing something wrong. Our implementation looks like this:

```objetive-c
// RCTCustomWebViewManager.h
#import <React/RCTWebViewManager.h>
#import <React/RCTWebView.h>

@interface RCTCustomWebViewManager : RCTWebViewManager

@end


// RCTCustomWebViewManager.m
#import "RCTCustomWebViewManager.h"

@interface RCTCustomWebViewManager () <RCTWebViewDelegate>

@end

@implementation RCTCustomWebViewManager { }
RCT_EXPORT_MODULE()
RCT_REMAP_VIEW_PROPERTY(keyboardDisplayRequiresUserAction, _webView.keyboardDisplayRequiresUserAction, BOOL)

- (UIView *)view
{
  RCTWebView *webView = [RCTWebView new];
  webView.delegate = self;
  return webView;
}

@end

```
### Expected Behavior

I expect it works.

### Actual Behavior

![simulator screen shot - iphone 6 - 2017-11-15 at 17 19 15](https://user-images.githubusercontent.com/1887029/32865522-1e669428-ca29-11e7-809b-2c6f2a951022.png)

### Reproducible Demo

https://github.com/juangl/with-custom-webview

**Comment by rpowelll** [comment]
Seeing the same issue here.

**Comment by evilDave** [comment]
Same here. Working on a new customised WebView, works on Android, has this problem on iOS.

**Comment by evilDave** [comment]
#16522 Kind of looks similar... On Android we need to do getExportedCustomDirectEventTypeConstants to register custom top level events (and add your own). Is there something like that that is required for iOS too?

**Comment by evilDave** [comment]
@cbrevik @jacobp100 @spicyj

(Apologies if this is not the right way to get someone to look at an issue)

#10946 and #15016 introduce a really nice way to handle extending native components, but it seems like something has gone awry with the default events.

There is a note in one of those pull requests that "You'll have to duplicate RCTWebViewManager.m, since the exported macro-defined methods/properties (with RCT_REMAP_VIEW_PROPERTY, RCT_EXPORT_METHOD, etc) are only picked up from the subclass, and not from the parent.". However I don't think any such advice made it into the documentation. Not sure what the issue is, if there is a problem to be fixed, or just some extra steps to customise the webview that need to be taken.

Thanks

**Comment by cbrevik** [comment]
Quickly tested it out, and was able to reproduce the same error. 

Regarding:
>You'll have to duplicate RCTWebViewManager.m, since the exported macro-defined methods/properties (with RCT_REMAP_VIEW_PROPERTY, RCT_EXPORT_METHOD, etc) are only picked up from the subclass, and not from the parent.

This should not be the case any more. With #14775 inheritance works on iOS as well.

I am not sure where the `topLoadingStart` event is coming from though. Searching through the code base I only find references in Android-code. Might be something changed with events on iOS from RN `0.49` -> `0.50`.

Maybe @javache knows?

**Comment by cbrevik** [comment]
Seems like this is related to changes in how events are resolved for inherited ViewManagers.

Spent half an hour investigating this, nailed it to changes necessary in 👍

**Comment by cbrevik** [comment]
Seems related to how events are resolved in [`requireNativeComponent.js`](https://github.com/facebook/react-native/blob/master/Libraries/ReactNative/requireNativeComponent.js)

Spent a bit of time investigating this, and was about to submit a PR, but seems like @shergin already fixed this in master: https://github.com/facebook/react-native/commit/2afe7d4765ffc0d0c71d233211edd1d21972040e

So it will probably be working again in a future version of RN :+1:
