### ISSUE TITLE
Input type="file" doesn't work in WebView Android

### ISSUE THREAD

**Issue by FelipeBohnertPaetzold** [facebook/react-native#16869]
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

yes

### Steps to Reproduce

1. Add a component with WebView pointing to a page that contains a file type input.

2. Access the component of an Android device.

### Expected Behavior

The photo gallery of Android is expected to open to select the desired file.

### Actual Behavior

Nothing happens, as if it had clicked out of the input.

### Reproducible Demo

https://snack.expo.io/@felipepaetzold/webview-input-file-error-on-android

**Comment by juangl** [comment]
Consider implementing it in a custom WebView. See:

- http://facebook.github.io/react-native/releases/0.50/docs/custom-webview-android.html
- https://infeeds.com/u/mgks/20475/upload-image-file-gallery-or-camera-webv

**Comment by FelipeBohnertPaetzold** [comment]
I am not able to inject native code, I am using Expo: '(

**Comment by dahjelle** [comment]
There's an [existing merge request](https://github.com/facebook/react-native/pull/12807#issuecomment-345388468) for this, but it's been closed in preference for an external module. That said, [making your own module](https://github.com/dahjelle/react-native-android-webview-file-image-upload) still requires native code but isn't as difficult as I'd feared.

**Comment by FelipeBohnertPaetzold** [comment]
Unfortunately the Expo does not allow me to build native modules. But for now I will give another solution.

**Comment by waldandrade** [comment]
@FelipeBohnertPaetzold How you fix that with expo?

**Comment by FelipeBohnertPaetzold** [comment]
@waldandrade I did not get it. I just created a screen for this in my App

**Comment by andreipfeiffer** [comment]
You have to `eject` from expo if you want to build native modules:
https://facebook.github.io/react-native/docs/getting-started.html#caveats

**Comment by sanshao** [comment]
the same problem  
anybody have an solution?

**Comment by andreipfeiffer** [comment]
@sanshao you can checkout [my custom WebView component](https://github.com/andreipfeiffer/react-native-webview-android-file-upload) or [dahjelle's](https://github.com/facebook/react-native/issues/16869#issuecomment-345388941). If you are using Expo, you have to `eject`.

**Comment by jamonholmgren** [comment]
This issue has been migrated to https://github.com/react-native-community/react-native-webview/issues/11 and can be closed.

**Comment by Titozzz** [comment]
This is currently being fixed on the community repo. Closing here
