### ISSUE TITLE
react native TextInput onBlur get unedfined in android

### ISSUE THREAD

**Issue by hawx1993** [facebook/react-native#16863]
my `react-native` version is `0.38.0`, 

```javascript
<TextInput underlineColorAndroid="transparent" . onBlur={ (event) => this.handleBlurCheck(event.nativeEvent.text,params) } />
```
in function `handleBlurCheck`,  I get the value at ios,  but I get `undefined` at android. 

how to get value when TextInput is blur on android platform.

**Comment by hawx1993** [comment]
@react-native-bot 

I think I describe it clearly, no need for more information.  I just can't get `event.nativeEvent.value` on android.

**Comment by budiga** [comment]
face the same problem

**Comment by GhizlaneA** [comment]
Hi, I am facing the same issue, anyone could find a workaround ?

**Comment by dmoss18** [comment]
Workaround is to use `onEndEditing` instead of `onBlur`

https://stackoverflow.com/a/47379303/683235
