### ISSUE TITLE
toLocaleString wrong format on Android

### ISSUE THREAD

**Issue by kern3lpan1c** [facebook/react-native#16867]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS:  macOS Sierra 10.12.6
  Node:  8.9.1
  Yarn:  1.3.2
  npm:  5.5.1
  Watchman:  4.7.0
  Xcode:  Xcode 9.0 Build version 9A235
  Android Studio:  2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: 0.48.4 => 0.48.4

Target Platform: Android (8.0)

### Steps to Reproduce

1. Open a fresh React Native project
2. Make sure you're not debugging JS remotely
3. Try to use toLocaleString on a Date() object 
```javascript
  let formatted = new Date('2017-11-17T10:59:30.527Z').toLocaleString('de-DE', {
    timeZone: 'Europe/Zurich',
    year: 'numeric',
    month: 'numeric',
    day: 'numeric',
    hour: 'numeric',
    minute: 'numeric',
  })
```
4. Either write up a simple component to display text or do an alert/console.log with the aforementioned variable. 

### Expected Behavior

The expected string should be as follows:
```text
Imput: 2017-11-17T10:59:30.527Z -> Output: 17.11.2017, 11:59
```
### Actual Behavior

The resulting string is as follows:
```text
Imput: 2017-11-17T10:59:30.527Z -> Output: Fri Nov 17 11:59:30 2017
```
My contention is that this is an issue with the underlying JS engine that Android uses, and handles it differently as opposed to the integrated JS engine on iOS, hence the variance in the date format. For this reason if you open a remote debugged, say on Chrome, you will actually get the correct format, due to the different JS engine handling it, but if you switch off the debugger and resume using the application whilst not debugging remotely, the incorrect format will be shown.

### Reproducible Demo

Here's an example Expo project that shows the behaviour, toggle between iOS and Android to see the difference in the output.

https://snack.expo.io/Bk3unwhyM

**Comment by hey99xx** [comment]
Pretty much same as https://github.com/facebook/react-native/issues/12597 So yes, it's JSC version on Android being old and not supporting localization methods to the full extent. If you're ambitious about it maybe you can try https://github.com/SoftwareMansion/jsc-android-buildscripts#international-variant-1

**Comment by oriharel** [comment]
This issue must exist.

**Comment by aayushis12** [comment]
The same issue is with me 
I am making a react-native project in which I have a function which is like this
`console.log("Formatter",(2500).toLocaleString('en-US', {
    style: "currency",
    currency: "USD",
    minimumFractionDigits: 0,
  }))
`
The expected output should be "$2,500"
But what I get on my console is "**Formatter 2500**"

**Comment by rgabriel18** [comment]
Using react-native 0.50.4
This problem is here alright, cannot format a number to currency.

Could get arround the issue by using  [Currency Formatter](https://github.com/smirzaei/currency-formatter)

Still, would be nice to have this working

**Comment by kholiavko-roman** [comment]
Issue still present.

**Comment by erlike** [comment]
Issue still present

**Comment by anchetaWern** [comment]
I also encountered this issue. Too bad I was only testing on iOS so I got puzzled when things are breaking for Android. Turns out `toLocaleString()` isn't working for Android.

Had to use the following function as an alternative for formatting the date:

```
getLocalDateTime(new Date());

function getLocalDateTime(date) {

  let hours = date.getHours();
  if (hours < 10) hours = hours;

  let minutes = date.getMinutes();
  if (hours < 10) hours = hours;

  let timeOfDay = hours < 12 ? 'AM' : 'PM';

  return date.getMonth() + '/' + date.getDate() + '/' +
         date.getFullYear() + ', ' + hours + ':' + minutes + " " + timeOfDay;
}
```

**Comment by AlirezaAkbarix** [comment]
Guys nothing to do?

**Comment by AlirezaAkbarix** [comment]
It's a real shame, to those who are using `toLocaleString()` method for **Currency** you can use this code for now:

`
  _getPriceValue() {

    if (Platform.OS === 'ios')

      return (+this.props.number).toLocaleString(fa ? 'fa-IR' : 'en-US', {maximumFractionDigits: 0});

    else

      return (+this.props.number).toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");

  }
`

**Comment by luco** [comment]
Still having this issue.

**Comment by mohsinriaz17** [comment]
Still having the same issue

**Comment by eshinkawa** [comment]
Same issue here as well. This should be prioritised considering the fact that this is a basic platform feature.

**Comment by lukewlms** [comment]
@kern3lpan1c It's been requested by the FB bot to open a new issue with same content, are you up for doing that and just pasting in the same content?

**Comment by kern3lpan1c** [comment]
@lukewlms , I've opened a new ticket [here](https://github.com/facebook/react-native/issues/22652). Hopefully a bot won't decide the ticket's fate this time and actually catch the attention of human maintainers.

**Comment by KotiJocki** [comment]
I believe this is a problem with the JavaScriptCore that comes with Android and not a React Native bug. It should be resolved by shipping an alternative core: 
https://github.com/react-community/jsc-android-buildscripts#how-to-use-it-with-my-react-native-app
with the international variant:
https://github.com/react-community/jsc-android-buildscripts#international-variant
