### ISSUE TITLE
Center multiline <Text> Component

### ISSUE THREAD

**Issue by AishwaryaSurana** [facebook/react-native#16865]
If the `<Text>` is multilined than it is not center aligned
```

<View style = {{
    justifyContent: 'center',
    alignItems: 'center'}}>
          <Text style={{alignSelf:'center',fontSize:20,justifyContent:'center',alignItems:'center'}}>
             A very big multiline text that can not be accumulated in a single line is shown here with all the attributes trying to center it</Text>
        </View>
        
```

**Comment by Suraj-Tiwari** [comment]
@AishwaryaSurana go with this and you are good to go!!

`<View style={{justifyContent: 'center', flex: 1}}>
<Text style={{textAlign: 'center'}}>A very big multiline text that can not be accumulated in a single line is shown here with all the attributes trying to center it</Text>
</View>`
