### ISSUE TITLE
[ASan] RCTImport data segment loader crashes w/Address Sanitizer

### ISSUE THREAD

**Issue by ide** [facebook/react-native#1687]
Compiling and running with ASan crashes inside of RCTJSMethods. cc @tadeuzagallo I think I read that you were going to change the RCTImport initialization so it doesn't use the data segment anymore and can work with dynamic modules. That work should fix this issue too.

**Comment by tadeuzagallo** [comment]
It's been removed in: d3065fc2e78bc80af8231c977845f4bb23c987be

**Comment by ide** [comment]
Sweet! The crash is gone. The app gets stuck loading with ASan enabled but that looks like a separate issue. Closing this out.
