### ISSUE TITLE
[Animated] Animated.View component loses shadow on animation

### ISSUE THREAD

**Issue by llanginger** [facebook/react-native#16870]
### Is this a bug report?

Yes (I think!)

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

  Environment:
    OS:  macOS High Sierra 10.13.1
    Node:  8.9.0
    Yarn:  1.2.1
    npm:  5.5.1
    Watchman:  Not Found
    Xcode:  Xcode 9.1 Build version 9B55
    Android Studio:  Not Found

  Packages: (wanted => installed)
    react: 16.0.0-beta.5 => 16.0.0-beta.5
    react-native: 0.49.1 => 0.49.1

  Target Platform: iOS (8)

### Steps to Reproduce

1. Initialize new react-native project, import Animated and TouchableWithoutOpacity

2. Create simple Animated function - in my case: 

```
bounce() {
    this.springValue.setValue(0)
    Animated.spring(
        this.springValue,
        {
            toValue: 1,
            friction: 5,
            velocity: 20
        }
    ).start()
}
```

along with interpolation such as:

```
const bounceScale = this.springValue.interpolate({
    inputRange: [0, 0.5, 1],
    outputRange: [1, 0.99, 1]
})
```

2. Create an Animated.View component with style props that include an animated `{transform: { scale: bounceScale}}` as well as shadow (offset and opacity) style props.

3. Place the above Animated.View component inside a TouchableWithoutOpacity component and set `onPress={this.bounce}`

### Expected Behavior

Animated.View component would, onPress, animate according to the bounce function leaving all other style props intact

### Actual Behavior

Bounce function completes and removes shadow props:

![Issue gif](https://media.giphy.com/media/l2QEbLV0cM94zO52g/giphy.gif)

### Reproducible Demo

Snack demo: https://snack.expo.io/BkmcUs3yf

**Comment by mujavidb** [comment]
I had a similar problem with the `elevation` property. I fixed it by resetting the property to a new `Animated.Value` on completion, as such:

```
Animated.spring(
    this.springValue,
    {
        toValue: 1,
        friction: 5,
        velocity: 20
    }
).start(() => {
    this.springValue = new Animated.Value(1) // <--here
})
```

**Comment by llanginger** [comment]
I was hopeful but alas, this seems not to solve my problem :(

**Comment by mujavidb** [comment]
Ahh, that's unfortunate. Instead of `this.springValue = new Animated.Value(1)` I have also used `this.springValue.setValue(1)`

**Comment by llanginger** [comment]
Same deal, unfortunately - setValue certainly does its thing but the shadow disappears until the next time the component fully re-renders

**Comment by mujavidb** [comment]
So if you stored the animation in the component state a change to its value, would trigger a re-render. 

A temporary solution, but I guess having `this.setState({springValue: new Animated.Value(1)})` in the animation callback could be a fix.
