### ISSUE TITLE
[Help Wanted] ListView OnEndReached

### ISSUE THREAD

**Issue by HyperSimon** [facebook/react-native#16876]
### Is this a bug report?
I am not sure

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Steps to Reproduce

1.Load the first page
2.Simulate a weak network status (such as shutting down the network)
3.Sliding to the ListView triggers loading more locations
4.Swipe to the top of listview
5.Connect to the network
6.Swipe to load more positions

### Expected Behavior

Load the second page of data

### Actual Behavior

Load more interfaces without callbacks

### Reproducible Demo

I actually looked at the Flatlist source code and found this method below, 
and I want to know why the current list height should be judged when loading more. 
How do I load more data after the network back to normal?

```javascript
  _maybeCallOnEndReached: function(event?: Object) {
    if (
      this.props.onEndReached &&
      this.scrollProperties.contentLength !== this._sentEndForContentLength &&
      this._getDistanceFromEnd(this.scrollProperties) <
        this.props.onEndReachedThreshold &&
      this.state.curRenderedRowsCount ===
        (this.props.enableEmptySections
          ? this.props.dataSource.getRowAndSectionCount()
          : this.props.dataSource.getRowCount())
    ) {
      this._sentEndForContentLength = this.scrollProperties.contentLength;
      this.props.onEndReached(event);
      return true;
    }
    return false;
  },

```

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by timwangdev** [comment]
I'm facing the same problem and there is one issue already. Let's keep the discussion in this issue in #15356.

**Comment by timwangdev** [comment]
@facebook-github-bot duplicate #15356
