### ISSUE TITLE
Shell script innovation error

### ISSUE THREAD

**Issue by ravisankit** [facebook/react-native#16887]
### Is this a bug report?

I am facing this while archiving my IOS app.

File /Users/home/Library/Developer/Xcode/DerivedData/My-baglsgtzrkvgtcdsdixmbhryokrf/Build/Intermediates.noindex/ArchiveIntermediates/MyApp/BuildProductsPath/Release-iphoneos/My.app/main.js bundle does not exist

### Environment
    OS:  macOS Sierra 10.12.6
    Node:  6.10.2
    npm:  4.5.0
    Watchman:  4.9.0
    Xcode:  Xcode 9.0.1  Build version  (9A1004)

  Packages: (wanted => installed)
    react-native: 0.48.1 => 0.47.2

  Target Platform: iOS (10.3)

### Steps to Reproduce

1. Open Xcode
2. Build IOS project

### Expected Behavior

It would have been built up.

### Actual Behavior

Getting error.

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by xuyan618** [comment]
i have the same problem

**Comment by xuyan618** [comment]
升级node的版本号至最新。问题解决
