### ISSUE TITLE
[Docs] A guide for Animation

### ISSUE THREAD

**Issue by brentvatne** [facebook/react-native#1688]
So many questions come up about animation and `AnimationExperimental`, which inevitably lead to mentions of the new animation api and suggestions to avoid `AnimationExperimental` in favour of `react-tween-state` or `rebound`. This should be summarized in the docs to bring more clarity to the current state of animations for newcomers.

**Comment by chirag04** [comment]
:100:

**Comment by dubert** [comment]
:+1:

**Comment by chirag04** [comment]
@brentvatne  This should be close though. We have an animation guide up now.

**Comment by browniefed** [comment]
Solved with documentation http://facebook.github.io/react-native/docs/animations.html#content unless you believe the current animation documentation isn't enough
@brentvatne already solved

**Comment by brentvatne** [comment]
Excellent :)
