### ISSUE TITLE
undefined is not a function (evaluating 'ReactComponentTreeHook.purgeUnmountedComponents()')

### ISSUE THREAD

**Issue by mbbarry91** [facebook/react-native#16898]
### Is this a bug report?

(I don't know but it seems to be)

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Yes)

### Steps to Reproduce

()

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(I deleted the node_module then i installed used the npm install after i run the app using react-native run-android then i got the error
![screenshot_1511190209](https://user-images.githubusercontent.com/25786816/33042154-d0708538-ce7b-11e7-9cd3-6aac20be578b.png)
)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by kckunal2612** [comment]
Even I had this issue. Fixed it by updating my 'react-native' version to '0.50'.

**Comment by mbbarry91** [comment]
ok, I will try that.

**Comment by mbbarry91** [comment]
@kckunal2612 how can I update my react-native? a command please

**Comment by kckunal2612** [comment]
In your project's root directory, there would be a "package.json" file. In there, there would be a dependencies block like this -

"dependencies": {
...
react-native": "^0.50.3",
...
}

In case you don't have version 0.50 here, you can change the version value for 'react-native' and then run the command 'npm-update' from the terminal. This will update the node-modules directory as well (update contents for this module).

**Comment by mbbarry91** [comment]
ok 
I have also tried this " npm install -git react-native-git-upgrade"
but i am having this warning 
"git-upgrade WARN The upgrade process succeeded but there might be conflicts to be resolved. See above for the list of files that have merge conflicts.
git-upgrade info Upgrade done"
 and had some errors
error: patch failed: android/app/build.gradle:72
Falling back to three-way merge...
Applied patch to 'android/app/build.gradle' cleanly.
error: patch failed: android/app/src/main/java/com/taximoto/MainApplication.java:25
Falling back to three-way merge...
Applied patch to 'android/app/src/main/java/com/taximoto/MainApplication.java' cleanly.
error: patch failed: ios/TaxiMoto.xcodeproj/project.pbxproj:36
Falling back to three-way merge...
Applied patch to 'ios/TaxiMoto.xcodeproj/project.pbxproj' with conflicts.
U ios/TaxiMoto.xcodeproj/project.pbxproj
any help with this

**Comment by SerafimC** [comment]
Got the same error here.
Already tried to update React, react native, all packages and npm but 
it dont work:
undefined is not a function (evaluating 'ReactComponentTreeHook.purgeUnmountedComponents()')

I'll keep up and any news I bring here

**Comment by vcheban** [comment]
Hello guys.
I've found this solution

https://reformatcode.com/code/ios/react-native---reactcomponenttreehookpurgeunmountedcomponents-is-not-a-function

> In the end, I figured that the versions of react and react-native packages that I were installed didn't "match". I saw the message npm WARN react-native@0.48.4 requires a peer of react@16.0.0-alpha.12 but none was installed. (I had a previous version installed because of another warning that I got).

As soon as I installed react@16.0.0-alpha.12 instead, the problem was solved. Apparently facebook has removed the function ReactComponentTreeHook.purgeUnmountedComponents from the code, it is not to be used 


It helped me too.

**Comment by naxir** [comment]
I was facing the same issue after going to  **react-native' '0.50'.**
now the issue Solved Thanks  @kckunal2612 c

**Comment by naxir** [comment]
I was facing the same issue after going to react-native version 0.50 issue resolved 
Thanks @kckunal2612
