### ISSUE TITLE
Unsupported top level event type "topScrollBeginDrag" dispatched

### ISSUE THREAD

**Issue by qinfensky** [facebook/react-native#16900]
software-version:
"react-native": "0.50.3",
"react-navigation": "^1.0.0-beta.11",
I slip on the tabbar, and there's an error. This is just the case on Android.

![s71121-093153](https://user-images.githubusercontent.com/7803520/33050785-aa51f302-cea1-11e7-893f-a9fe76cfc8e9.jpg)

**Comment by evilDave** [comment]
Wouldn't it be better if the bot asked the poster to fix it rather than closing the issue?

**Comment by qinfensky** [comment]
@evilDave I don't know what these robots think, either

**Comment by HossamSamir** [comment]
I have the same issue wtf robot 😒

**Comment by Jacse** [comment]
Duplicate #16522
