### ISSUE TITLE
Geolocation getCurrentLocation request times out when GPS is turned off then on again

### ISSUE THREAD

**Issue by vydingding** [facebook/react-native#16903]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

<!--
  In your terminal run `react-native info` and paste its contents here. Next, specify your target platform, like this:

Environment:
  OS:  Windows 7
  Node:  6.11.4
  Yarn:  Not Found
  npm:  3.10.10
  Watchman:  Not Found
  Xcode:  N/A
  Android Studio:  3.0

Packages: (wanted => installed)
  react: ^16.1.1 => 16.0.0
  react-native: ^0.49.5 => 0.49.3

  Target Platform: Android (6.0)

### Steps to Reproduce

(Write your steps here:)

1. Location initially turned on, then turn it off through settings
2. Navigate to the component with geolocation.
3. A message will pop and ask you to turn on your location.
4. Get navigated to settings, turn on your location.

### Expected Behavior

Location would be received, app proceeds.

P.S. Initially, when my app is first built, ACCESS_FINE_LOCATION permission is enabled, so location permissions are allowed. Thus, initially, location returns a value for latitude and longitude.

### Actual Behavior

Error message, saying location request timed out.

**Comment by hemedani** [comment]
i have the same issue ...
i use this package for turning on location on android `react-native-android-location-services-dialog-box` when when i turned on location and get back to app getCurrentLocation request gets timed out.

**Comment by damsorian** [comment]
Same issue with the **getCurrentPosition**:
`{message: "Location request timed out", code: 3}`

**Comment by guopeng1994** [comment]
me too! 

RN: 0.51.0 
React:16.0.0-alpha.12 
Platform:Android 6.0

**Comment by zaplo00** [comment]
Happens always, at least in RN 0.49 and 0.53

**Comment by hemedani** [comment]
it's not solved please don't close it

**Comment by damsorian** [comment]
I solved the **getCurrentPosition** issue with this workaround:

```javascript
const getCurrentPosition = (onSuccess, onError, error3) => {
  navigator.geolocation.getCurrentPosition(
    (position) => onSuccess(position),
    (err) => {
      if (err.code === 3 && !error3) {
        getCurrentPosition(onSuccess, onError, true);
      } else {
        onError(err);
      }
    },
    { enableHighAccuracy: !error3, timeout: 5000 },
  );
};

getCurrentPosition(
  (position) => console.log('position', position),
  (error) => console.log('position error', error),
)
```
