### ISSUE TITLE
[WebView] How to force reloading webview resources every time opening the webview?

### ISSUE THREAD

**Issue by Jancat** [facebook/react-native#16907]
### Is this a bug report?

No

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

How to force reloading webview resources every time opening the webview?

I find it instantly opening the webview page from cache after the first load. And it can't see the updated content on the webview page.

**Comment by charpeni** [comment]
@facebook-github-bot stack-overflow
