### ISSUE TITLE
Flow errors on 0.50.3

### ISSUE THREAD

**Issue by joemckie** [facebook/react-native#16914]
### Is this a bug report?

Yes. Although this may not be RN specific -- it's more of a problem with flow in RN.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: macOS High Sierra 10.13.1
  Node: 9.2.0
  Yarn: 1.2.1
  npm: 5.5.1
  Watchman: 4.9.0
  Xcode: Xcode 9.1 Build version 9B55
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.50.3 => 0.50.3
  flow-bin: 0.56.0 => 0.56.0

Target Platform: iOS (10.3)

### Steps to Reproduce

Run flow in a RN project

### Expected Behavior

Should pass flow checks.

### Actual Behavior

Flow errors are being reported from both the `metro-bundler` package and `react-native`.

Full list of errors can be found [here](https://gist.github.com/joemckie/35d42c0e8040d55a82c3897f112d8738).

They seem to all be Promise related, but I can't quite work out why. This has only been an issue since upgrading RN@0.50.3.

### Reproducible Demo

n/a, not a visual bug.

**Comment by voidstarfire** [comment]
How can they push a release candidate and not even flow check it.

**Comment by otusweb** [comment]
./node_modules/.bin/flow version
Flow, a static type checker for JavaScript, version 0.64.0
./node_modules/.bin/react-native --version
Scanning folders for symlinks in /Users/otusweb/Projects/reactnative/node_modules (13ms)
0.52.1

Flow returned 24 errors.

**Comment by ericketts** [comment]
like @otusweb also getting 24 errors on fresh install with crna, as follows:

* node_modules/react-native/Libraries/Inspector/Inspector.js:104
* node_modules/react-native/Libraries/Interaction/InteractionManager.js:171
* node_modules/react-native/Libraries/Lists/FlatList.js:465
* node_modules/react-native/Libraries/Lists/FlatList.js:558
* node_modules/react-native/Libraries/Lists/ViewabilityHelper.js:91
* node_modules/react-native/Libraries/Lists/ViewabilityHelper.js:200
* node_modules/react-native/Libraries/Lists/ViewabilityHelper.js:207
* node_modules/react-native/Libraries/Lists/VirtualizedList.js:484
* node_modules/react-native/Libraries/Lists/VirtualizedList.js:484
* node_modules/react-native/Libraries/Lists/VirtualizedList.js:500
* node_modules/react-native/Libraries/Lists/VirtualizedList.js:1016
* node_modules/react-native/Libraries/Lists/VirtualizedList.js:1016
* node_modules/react-native/Libraries/Lists/VirtualizedList.js:1094
* node_modules/react-native/Libraries/Lists/VirtualizedList.js:1094
* node_modules/react-native/Libraries/Lists/VirtualizedList.js:1170
* node_modules/react-native/Libraries/Lists/VirtualizedList.js:1170
* node_modules/react-native/Libraries/Lists/VirtualizedList.js:1247
* node_modules/react-native/Libraries/Lists/VirtualizedSectionList.js:236
* node_modules/react-native/Libraries/StyleSheet/flattenStyle.js:36
* node_modules/react-native/Libraries/vendor/emitter/EmitterSubscription.js:0
* node_modules/react-native/Libraries/vendor/emitter/EventSubscription.js:0
* node_modules/react-native/Libraries/vendor/emitter/EventSubscriptionVendor.js:0
* node_modules/reqwest/tests/fixtures/fixtures_with_prefix.json:1
* node_modules/reqwest/tests/fixtures/invalidJSON.json:1

i can include the full messages for each, but i figure it would be easier for you guys to just run flow on it yourself. 

kinda funny, at my last shop we used typescript with react-native, did not have such issues.
