### ISSUE TITLE
When I open modal  lots of times (5-6) then app is crashing. (BUG)

### ISSUE THREAD

**Issue by dbyilmaz** [facebook/react-native#16929]
### Is this a bug report?

Yes, it is serious bug.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?
yes

### Environment

  Environment:
    OS: Ubuntu 16.04
    Node:  v6.11.2
    npm:  5.5.1
    Watchman:  4.7.0

  Packages: (wanted => installed)
    react-native: 0.50.3
    react: 16.0.0-beta.5

  Target Platform: Android

### Expected Behavior
I open modal lots of times (5-6) . This situation must not  cause the app is crash.

(Write what you thought would happen.)

### Actual Behavior
When I open modal  lots of times (5-6) then app is crashing. (BUG)

(Write what happened. Add screenshots!)

**Comment by Crash--** [comment]
Hi, 

Can you share a small project to reproduce this error? Also, can you post some console logs? ( https://facebook.github.io/react-native/docs/debugging.html#accessing-console-logs )

**Comment by dbyilmaz** [comment]
Hi, I will write details a soon as. @Crash--

**Comment by AlgoTrader** [comment]
I have quite the same problems but app hangs. Just stop to respond touches. Modal can be open/closed during navigation transtitions
