### ISSUE TITLE
webview not support viewport width 640px

### ISSUE THREAD

**Issue by banli17** [facebook/react-native#16923]
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

yes

### Environment

- react -native 0.44.0
- iphone 6s and other iphones

### Steps to Reproduce

(Write your steps here:)

1. my html page 

```
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
	<meta name="viewport" content="width=640px,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no">
</head>
<body>
	<div style="height:200px;background: red;width:640px;"></div>
</body>
</html>
```

2. in react-native 

```
<WebView
	ref={(e)=> {
		this.webView = e
	}}
		onLoadEnd={this.onLoadEnd.bind(this)}
	source={{uri: url}}
	javaScriptEnabled={true}
	scalesPageToFit={false}
	startInLoadingState={true}
	renderLoading={this.renderLoading.bind(this)}
	onNavigationStateChange={this.onNavigationStateChange.bind(this)}
/>
```

3.  but in app the page's html, page has scrollbar, and div'width =  2* device-width， it should just 1*device-width not 2。 i think this is bug。

it's ok on android and it's bug on iphone。

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by Crash--** [comment]
Can you try with removing minimum & maximum-scale from your viewport?

**Comment by banli17** [comment]
@Crash--  yes，i have tried，but it's same。i even try 

```
width=640px  user-scalable=no
width=640px  initial-scale=1.0
```

**Comment by jackklpan** [comment]
I have the same problem.
And I solved by setting the "scalesPageToFit" prop to true.

**Comment by banli17** [comment]
@jackklpan  but as yours user can  scale ?

**Comment by jackklpan** [comment]
@banli17 No. Our viewport set as <meta name="viewport" content="width=640, user-scalable=no">.
