### ISSUE TITLE
FlatList footer render bug??

### ISSUE THREAD

**Issue by xilibro** [facebook/react-native#16921]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

 Environment:
  OS:  macOS Sierra 10.12.6
  Node:  8.2.1
  Yarn:  0.27.5
  npm:  5.3.0
  Watchman:  4.7.0
  Xcode:  Xcode 9.1 Build version 9B55
  Android Studio:  2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: 0.49.3 => 0.49.3

  Target Platform: iOS (10.3)

### Steps to Reproduce

(Write your steps here:)

1. create a custom compoennt, and render a FlatList
2. add renderItem，ListFooterComponent，refreshing，onRefresh，onEndReached，onEndReachedThreshold，keyExtractor，ItemSeparatorComponent props
3. write functions for these props except refreshing set a boolean value, onEndReachedThreshold set 1, 

### Expected Behavior

when i bind 'this' for _handleRefresh()、_renderFooter()、_renderSeparator()、_onEndReached() all 4 functions in my component constructor，FlatList can not render its footer as normal, nothing render actually, but if i bind this as above, the FlatList‘s footer rendered as expected.
What make me strange is , it is worked if i bind 'this' as above for one of them, the other three functions do bind in constructor, it's also worked.

### Actual Behavior

when i bind 'this' for _handleRefresh()、_renderFooter()、_renderSeparator()、_onEndReached() all 4 functions in my component constructor，FlatList can not render its footer as normal, nothing render actually, 

### Reproducible Demo

https://github.com/xilibro/ReactNativeFlatListDemo

**Comment by jslok** [comment]
You do not need to do bind the functions in the constructor. Remove this:
```
        this._renderFooter=this._renderFooter.bind(this)
        this._onEndReached=this._onEndReached.bind(this)
        this._separator = this._separator.bind(this)
```

Instead, write your functions with the arrow function like this:

```
_renderFooter = () => {
    ....
}
```

**Comment by alainib** [comment]
@jslok  from what i understand arrow function instead of bind create a new function on each render. 
I'm trying to optimise my flatlist who is slow and use arrow function everywhere. 
any advice ?
