### ISSUE TITLE
[iOS] Geolocation API not work on RN 0.50.3

### ISSUE THREAD

**Issue by jacobchen** [facebook/react-native#16928]
### Is this a bug report?

Yes

### Environment

    OS:  macOS Sierra 10.13.1
    Node:  8.9.1
    Yarn:  0.21.3
    npm:  5.5.1
    Xcode:  Xcode 9.1 Build version 9B55
  
    react-native: 0.50.3
    react: 16.0.0
    Test device: Simulator iPhone6s / iOS11

### Steps to Reproduce

1. create a pure app with command: react-init geoTest

2. Setup the app as following: include NSLocationAlwaysUsageDescription and NSLocationWhenInUseUsageDescription in the info.plist, add location as a background mode in the 'Capabilities' tab in Xcode

3. Add code as below:

```javascript
componentDidMount() {
     navigator.geolocation.getCurrentPosition(
          (position) => {
            console.log("position.coords: ", position.coords);
          },
          (error) => this.setState({ error: error.message }),
          { enableHighAccuracy: true, useSignificantChanges: true, distanceFilter:10, timeout: 20000, maximumAge: 1000 },
        );
}
```

Below error message show up:

`TypeError: Cannot read property 'geolocation' of undefined`

**Comment by ProteanDev** [comment]
Yeah I'm having this issue too. I haven't found a way around it yet. I am using react-native-maps though, not sure yet if that has something to do with that.

**Comment by hawkup** [comment]
Have you tried remove /node_modules and install again yet?
