### ISSUE TITLE
Multiline break style

### ISSUE THREAD

**Issue by rahmanmarija** [facebook/react-native#16925]
### Is this a bug report?

No

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Steps to Reproduce

(Write your steps here:)

1. Have an iPhone 6s+
2. Import TextInput
3. Add multiline to TextInput

### Expected Behavior

I expect when I add multiline property to TextInput styles not to break.

![android_working](https://user-images.githubusercontent.com/29597350/33118174-5229eb06-cf6b-11e7-87aa-caa5e8497a51.png)

### Actual Behavior

What actually happens is that some weird stylings appear. It happens only on iPhone 6s+, tested only on 5, 5s, 7.

![multine_bug](https://user-images.githubusercontent.com/29597350/33117976-a70c17b2-cf6a-11e7-80f3-21db7e7cec67.jpg)

**Comment by lwinkyawmyat** [comment]
@facebook-github-bot stack-overflow
