### ISSUE TITLE
React Native 0.49.5 crash in release mode.

### ISSUE THREAD

**Issue by hushicai** [facebook/react-native#16920]
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

yes

### Environment

OS:  macOS Sierra 10.12.6
Node: 8.9.0
Yarn:  not installed
npm: 5.5.1
Watchman: 4.7.0
Xcode: Version 9.0 (9A235)
react-native: 0.49.5
react:  16.0.0-beta.5
Target Platform: IOS 10.3.3（14G60）

### Steps to Reproduce

1. xcode run in release mode into real device.
2. crash
3. view devices logs

![image](https://user-images.githubusercontent.com/1249423/33107920-8156e7e0-cf74-11e7-857e-25fb055bef1d.png)

### Expected Behavior

App opened normally.

### Actual Behavior

Can not open App at all, crash!

### Reproducible Demo

no

I have use `react-codemod` to fix `View.propTypes`, but codemod does not modify `Animated.View.propTypes`, is that cause the same problem?

**Comment by wangghon** [comment]
It seems your code or  one of your dependency still using View.propTypes, should be changed to ViewPropTypes

**Comment by hushicai** [comment]
Yes, It is.

**Comment by amirmatin** [comment]
I also had the same issue, mine was fixed my by removing node_module files and installing them back.. it is not the best fix but does the job ..!

**Comment by SanyasiraoM** [comment]
@hushicai How did you see those logs in release mode? Thanks!

**Comment by hushicai** [comment]
@SanyasiraoM https://stackoverflow.com/questions/39089772/release-mode-diagnostics-in-react-native
You can use mac `console.app` to see logs.

**Comment by SanyasiraoM** [comment]
Thank you @hushicai
