### ISSUE TITLE
TypeError undefined is not an object (evaluating 'nativeVersion.major')

### ISSUE THREAD

**Issue by SephoraCode** [facebook/react-native#16938]
### Is this a bug report?
YES
![image](https://user-images.githubusercontent.com/25217992/33157483-551b782a-d03d-11e7-9589-9cf40749d8d3.png)

i want rn 0.49, but error with this, why?
![image](https://user-images.githubusercontent.com/25217992/33157574-0b61bb08-d03e-11e7-9d14-afea354df65d.png)

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?
YES

### Environment
Environment:
  OS: macOS Sierra 10.12.6
  Node: 6.10.3
  Yarn: 0.21.3
  npm: 5.5.1
  Watchman: 4.7.0
  Xcode: Xcode 9.1 Build version 9B55
  Android Studio: 2.3 AI-162.3934792

Packages: (wanted => installed)
  react: ^16.1.1 => 16.1.1
  react-native: 0.49.0 => 0.49.0

**Comment by ide** [comment]
You’d get this error if you’re not running the same version of JS as the native code. I’d recommend deleting node modules, clearing derived data, resetting simulator, basically clear all the caches, make sure you have the same version of TN everywhere, then rebuild since this isn’t a bug with RN.

**Comment by SephoraCode** [comment]
thank you, clean and run, is ok,

**Comment by morenoh149** [comment]
I had to run `watchman watch-del-all && react-native start --reset-cache`

**Comment by jiteshwadia** [comment]
Having the same problem here.

"react": "16.0.0",
"react-native": "0.50.1",

Tried killing and restarting the packager,` npm install`.
Also run `watchman watch-del-all && react-native start --reset-cache`
 But the error is still there

**Comment by IgorGanapolsky** [comment]
Is there a solution?  I am getting the error:
> TypeError undefined is not an object evaluating _reactNative.nativeModules.UIManager.RCTVideo.Constants)

**Comment by wanghuajian620** [comment]
I am getting the error:
![screen shot 2018-01-22 at 4 23 15 pm](https://user-images.githubusercontent.com/31924547/35211258-b03c36e0-ff90-11e7-99e2-7229290b29dc.png)

**Comment by rajatbeck** [comment]
Facing similar issue when upgrading my version

**Comment by luqmanrom** [comment]
@wanghuajian620 They just moved out the PropTypes from React core. You have require separate package to use it, https://www.npmjs.com/package/prop-types

**Comment by Bagus98** [comment]
i am getting error
![185795](https://user-images.githubusercontent.com/32588695/40583526-2cd109a8-61c3-11e8-9b65-60d00a0739b7.jpg)

**Comment by nikhilponnuru** [comment]
do try building, react-native run-android /ios and check for any errors and then restart package manager. It solved the error for me. I got errors when I have run react-native run-android
