### ISSUE TITLE
path.indexOf is not a function unsing link

### ISSUE THREAD

**Issue by jose920405** [facebook/react-native#16932]
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

YES

### Environment
```
react-native-cli: 2.0.1
react-native: 0.39.0
```
👇 
 Unrecognized command 'info'
 Run react-native --help to see list of all available commands

### Steps to Reproduce

1) yarn add `react-native-anyModule`.
2) `react-native link react-native-anyModule` 👈  Here error.

### Expected Behavior

not show the console error

### Actual Behavior

```
rnpm-install ERR! It seems something went wrong while linking. Error: path.indexOf is not a function 
Please file an issue here: https://github.com/facebook/react-native/issues 

path.indexOf is not a function
```

![captura de pantalla 2017-11-22 a la s 11 38 28 a m](https://user-images.githubusercontent.com/12536184/33138947-d0bfadd0-cf79-11e7-973c-347b7e488299.png)

**happens with all modules**
_____

**Comment by Crash--** [comment]
RN 0.39 ?! Can you try to upgrade ?

**Comment by jose920405** [comment]
Yes, that's the plan .. I just can not do it now, the change seems to be very careful, since there are notable changes in modules that I'm using, depreciated things, etc. My project is a bit big and it may take me some time. For now, the idea is to go to prod with this version and for the next update to do this.
