### ISSUE TITLE
FlatList with getItemLayout(): Invariant Violation: Should not have to estimate frames when a measurement metrics function is provided

### ISSUE THREAD

**Issue by Phrosh** [facebook/react-native#16950]
### Is this a bug report?

yes

### Environment

  Environment:
    OS:  Windows 10 x64
    Node:  10.0
    npm:  5.5.1
    Watchman:  4.9.0

  Packages:
    react-native: 0.50.0
    react: 16.0.0

  Target Platform: Android

### Steps to Reproduce

Use a FlatList and pass in a getItemLayout prop

### Expected Behavior

Everything works normal and I get a beautiful FlatList

### Actual Behavior

The items are rendered but I get a red error screen of death stating the following:

> Invariant Violation: TaskQueue: Error with task: Should not have to estimate frames when a measurement metrics function is provided

![screenshot_1511455651](https://user-images.githubusercontent.com/7522383/33183237-5370cec8-d077-11e7-83f0-3d68a665b955.png)
.

### Reproducible Demo
Just return a 
`<FlatList
      getItemLayout={() => { return {length: 33, index: 3, offset: 334} }}
      data={['asdf', 'sdfsdf']}
      renderItem={({item}) => <Text>{item}</Text>}
    />`
from the render method of a component and let the magic happen

**Comment by ChrisLahaye** [comment]
getItemLayout is called for each item, your method needs to depend on index.

Try something like this
```
 <FlatList getItemLayout={(data, index) => { return {length: 33, index, offset: 33 * index} }} data={['asdf', 'sdfsdf']} renderItem={({item}) => <Text>{item}</Text>} />
```

**Comment by Phrosh** [comment]
Nope, this still does not work

**Comment by ChrisLahaye** [comment]
@Phrosh Well if you expect someone to seriously help you, then you should come with a more detailed problem description. Your `getItemLayout` method needs to dependent on index.

**Comment by Rewieer** [comment]
You pass a function to getItemLayout that get called for every entry in your array.
In this case `index` is just the index of the current element in the array.

**Comment by bolan9999** [comment]
FlatList and SectionList is bad performance. Try this,please. may be it is a surprise for you

https://github.com/bolan9999/react-native-largelist

**Comment by cyphire** [comment]
I have had a similarproblem for a long time... gave up...

The new error changes it to explain about the 'key' property, but there IS NO KEY PROPERTY in the documentation. I changed:

to the following: (Added: key = {this.state.slideNum}).. Now it works!
`
<FlatList
....
key = {this.state.slideNum}
numColumns={this.state.slideNum}

`

**Comment by ChrisLahaye** [comment]
@cyphire that is most like unrelated to this issue. It is due to the fact that you are rendering an array of components instead of a single component. When rendering an array of components each component requires a key property for optimization.

And don't use react-native-largelist its full of bugs and null pointer exceptions, if only that library was as good as @bolan9999 is in marketing

**Comment by cyphire** [comment]
Yeah you are right, this is unrelated... I do have the key component updating in each element of the array.  The problem I was having is that I was trying to change the numColumns, not dynamically but as a new value passed into the props.  Nothing I did worked, i kept getting the invariantViolation, but about "cannot dynamically change column size, look at the key property of the list".  Nothing has ever worked this way, no way to fix it.  I just discovered that by putting the key property in the actual <FlatList> list of properties, it finally worked!  I just don't think that this is documented.

Also I agree with the -largelist it even messed up my gradles and such!

**Comment by ChrisLahaye** [comment]
@alpamys-qanybet Offset dictates the space above the corresponding item (so the start position of an item). The offset is based on the assumption that each of the prior items are ITEM_HEIGHT in height. No matter how many horizontal columns you have, or maybe you even have two vertically placed rows in an item, ITEM_HEIGHT should match the total height of the most outer container for the most accurate rendering.

If your items are dynamic in size you should not use getItemLayout or add a static height which matches ITEM_HEIGHT.

**Comment by alpamys-qanybet** [comment]
@ChrisLahaye, I use ```getItemLayout``` and ```viewabilityConfig``` properties to get better performance, and yes, it does matter but after scrolling deep I see jumping effects, don't know why.

**Comment by ChrisLahaye** [comment]
@alpamys-qanybet You see jumping if your offset calculation (which is used to dictate the initial position of an item) doesn't match the actual offset caused by the prior items, so one or more items don't have ITEM_HEIGHT in height.

**Comment by nikolakanacki** [comment]
Probably not related but does anyone has experience with using `getItemLayout` with variable (but prior known) row heights? For an example - if you have two types of items (major / minor), you loop through the data and add heights. Also, how does ItemSeparator fit's into this calculation?

This is what I'm doing:
```js
...
getItemLayout=((data, index) => {
  let offset = 0;
  for (let i = 0; i < index; i++) {
    offset += getRowHeight(data[index]);
    offset += GUTTER;
  }
  return {
    length: getRowHeight(data[index]),
    offset,
    index,
  };
});
...
```

Function `getRowHeight` is just a helper returning the height of a particular row, `GUTTER` is the height of the `ItemSeparator`.

As soon as the items are being removed from the list (VirtualizedList way of optimizing large lists) I see jumping all around.
