### ISSUE TITLE
getCurrentPosition hanging forever on Android when Location services are turned off

### ISSUE THREAD

**Issue by jamesone** [facebook/react-native#16954]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

I cannot update to RN > 0.48 due to multiple issues (stuff todo with the packager - e.g moment throws errors when upgrading). I am stuck on 0.44

Node: 8.6
Watchman: 4.1.0
RN: 0.44

### Steps to Reproduce

(Write your steps here:)

1. Disable location services for your device
2. Run:

```
global.navigator.geolocation.getCurrentPosition(
      ({ coords }) => {
        // IT NEVER REACHES HERE
      },
      () => {
       // IT NEVER REACHES HERE
      },
      { enableHighAccuracy: true }
    );
```

### Expected Behavior

It is supposed to at least run the error callback, but it doesn't. Instead it just hangs forever. This is an issue because we're relying on the fallback (if the location services are disabled).

### Actual Behavior

It hang forever and never runs any of the fallback methods.

I opened this SO question a couple weeks ago: https://stackoverflow.com/questions/47195962/react-native-getcurrentposition-method-hanging-forever-on-android

**Comment by Casy** [comment]
@jamesone did you find a solution?
