### ISSUE TITLE
Option for <CheckBox> to look like "Radio"?

### ISSUE THREAD

**Issue by Noitidart** [facebook/react-native#16952]
The new [`<CheckBox>`](https://facebook.github.io/react-native/docs/checkbox.html) component is awesome! I was trying to make it look like a radio button though. Is there an option for this? I can't find it in the code nor in the [repo](https://github.com/facebook/react-native/search?utf8=%E2%9C%93&q=CheckBox&type=). Is there another issue talking about possibility of attribute to make it look like "radio"? Is there another issue tracking this?

**Comment by Noitidart** [comment]
I added the information.

**Comment by sijad** [comment]
any news on this one?
