### ISSUE TITLE
xcodeproj layout

### ISSUE THREAD

**Issue by mattapperson** [facebook/react-native#1696]
As someone coming from the Titanium Mobile world, there are some potential pitfalls I would like to make suggestions so as to help avoid.

The fact that an app has a single xcodeproj can cause issues as you start to look at tolling (official or community made) that helps to manage common tasks. It can also cause issues when you look at things like modules/dependencies. The reason is you start crisscrossing a lot between what a developer can "safely" touch and what tooling needs to change. The best solution I think can be found in how cocoapods does things with an xcodeworkspace file containing both an "app" xcodeproj that tooling NEVER TOUCHES, and a "project" xcodeproj that tooling manipulates and even dynamically generates so as to keep things lean and streamlined.

Just wanted to open up discussions here for this to be fleshed out :)

**Comment by brentvatne** [comment]
Interesting ideas! Can you try reviving the discussion on #235?
