### ISSUE TITLE
`removeImageForTag() not implemented` warning(or error) on Android

### ISSUE THREAD

**Issue by jbaek7023** [facebook/react-native#16969]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment
```

Environment:
  OS:  Linux 4.4
  Node:  4.6.1
  Yarn:  0.27.5
  npm:  4.6.1
  Watchman:  4.7.0
Error: unable to print environment info
{ [Error: not found: xcodebuild] code: 'ENOENT' }

```
### Steps to Reproduce

1. ImageStore can't call removeImageForTag()

### Expected Behavior
ImageStore calls and remove the image file from ImageStore.

### Actual Behavior
I'm getting this warning: `removeImageForTag() not implemented` 

### Code Snippet

```
    ImageEditor.cropImage(
      this.state.image,
      imageData,
      (successURI) => {
        ImageStore.getBase64ForTag(successURI,
          (base64Data) => {
            console.log(base64Data);
          },
          (failure) => {console.log('failed to load')});
        console.log(successURI);
        ImageStore.removeImageForTag(successURI)
      },
      (error) => { console.log('ERROR: ', error)}
    )
```

**Comment by jbaek7023** [comment]
I guess I'm using outdated react-native. 
```
    "react-native": "https://github.com/expo/react-native/archive/sdk-21.0.2.tar.gz", 
```
Should I upgrade React-Native to use the removeImageForTag()?
Is it breaking anything when I upgrade my RN pkg. I'm little hesitating to do so.

**Comment by Fsarmento** [comment]
I am having the same problem.

**Comment by alprtv** [comment]
in doc `https://facebook.github.io/react-native/docs/imagestore.html`
write `static removeImageForTag(uri) - @platform ios`
