### ISSUE TITLE
Default of `contentInsetAdjustmentBehavior` is incorrect

### ISSUE THREAD

**Issue by Jpunt** [facebook/react-native#16971]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

ReactNative 0.50 (which is the only relevant part in this case)

### Steps to Reproduce

1. Go to the ReactNative-docs of `ScrollView`, in particular the section about [`contentInsetAdjustmentBehavior`](https://facebook.github.io/react-native/docs/scrollview.html#contentinsetadjustmentbehavior)
2. Go to the UIKit-docs of [`contentInsetAdjustmenBehaviour`](https://developer.apple.com/documentation/uikit/uiscrollview/2902261-contentinsetadjustmentbehavior)
3. Compare the default value of `never` for ReactNative and `automatic` for UIKit. 

### Expected Behavior

Since this is an iOS specific option of `ScrollView`, I'd expect that we would follow the default setting that UIKit has.

### Actual Behavior

- The default value of `contentInsetAdjustmentBehavior` is `never` for ReactNative
- The default value of `contentInsetAdjustmentBehavior` is `automatic` for UIKit

### Reproducible Demo

Not relevant in this case.

**Comment by hawkrives** [comment]
FWIW, the thread where [`contentInsetAdjustmentBehavior` support was added](https://github.com/facebook/react-native/pull/15023) has some reasoning behind picking `never` as the default.

**Comment by hawkrives** [comment]
@react-native-bot This issue does not need `react-native info`.

**Comment by MikeSilvis** [comment]
Can someone please take a look at this?

**Comment by hramos** [comment]
If this is something people want to change, the thread that @hawkrives has insight into why the default was chosen. If a PR is sent to change this, please copy the people involved in that thread.

**Comment by kelset** [comment]
Hello there 👋 this issue seems to have been inactive for the past few months. Because of this, it's likely that the issue is not a high priority anymore or it has been solved by OP; for these reasons, we'll close it.

But please, if it's actually still an issue with 0.59 please comment below and we can reopen it or please send us a Pull Request with a fix 😊
