### ISSUE TITLE
Remote debugger bug, react-native v 0.50 android

### ISSUE THREAD

**Issue by universalmind303** [facebook/react-native#16977]
### Is this a bug report?
yes

### Environment

Environment:
  OS: Linux 4.10
  Node: 8.5.0
  Yarn: 1.0.1
  npm: 5.3.0
  Watchman: Not Found
  Xcode: N/A

  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.50.4 => 0.50.4

Browser: Chrome Version 59.0.3071.115 (Official Build) (64-bit)
 Target: (Android 8.0)

### Steps to Reproduce

`react-native init AwesomeProject`
`cd AwesomeProject`
`react-native run-android`
enable remote debugger on device

open browser to http://localhost:8081/debugger-ui/

### Expected Behavior

device should connect to remote debugger with no errors

### Actual Behavior

device will not connect to remote debugger. 

console will display - 

 'Uncaught SyntaxError: Unexpected token ...'  localhost/:183

localhost/:183 -         
worker.postMessage({
          ...object,
          url: await getBlobUrl(object.url),
      });

I reverted back to 0.49 and it got rid of the error, and am able to connect properly, so I am sure it is with 0.50

it looks like the error is coming from object spread operator in /react-native/blob/master/local-cli/server/util/debugger-ui/index.html

Object spread is not supported pre version 60 on google chrome. 

### Reproducible Demo

react-native init ${app name}

**Comment by chmiguel** [comment]
i have the same issue on ubuntu 14.04, react native v0.50, on windows the project debugger works fine

**Comment by mataoct** [comment]
i got the same issue on mac

**Comment by universalmind303** [comment]
I have a bugfix in my repo, I submitted a PR as well. 

You can pull down my version instead of the facebook one 

https://github.com/universalmind303/react-native

Another fix ( if you are using chrome ) , upgrade to the latest version of chrome

**Comment by MatheusR42** [comment]
Same error here. I update the chrome and now it works. 

Thanks @universalmind303

**Comment by pedrobertao** [comment]
I've got the error and updating my chrome to the latest version (63) fixed this error. 
Thanks @universalmind303

**Comment by nsantacruz** [comment]
Started experiencing this error when I upgraded from RN 51 to 52. Just upgraded Chrome from 63 to 64 and still seeing the error 😔

**Comment by hjJunior** [comment]
I got the same problem, and I'm using chrome version `64.0.3282.167`
Runing `react-native: 0.53.3`

**Comment by nsantacruz** [comment]
@react-native-bot, still experiencing this issue on v0.53.0

**Comment by anas10** [comment]
Same here with v0.54.0

**Comment by iamtekeste** [comment]
Still seeing this issue with Chrome version `66.0.3359` and React Native version `0.55.4`
