### ISSUE TITLE
[Docs] Example of <Navigation> NavigationBar node syntax?

### ISSUE THREAD

**Issue by evanmrose** [facebook/react-native#1698]
I'm looking through the docs and trying to find the proper syntax for a navigationBar node within a Navigation component. I see the following in the source:

    propTypes: {
    navigator: React.PropTypes.object,
    routeMapper: React.PropTypes.shape({
      Title: React.PropTypes.func.isRequired,
      LeftButton: React.PropTypes.func.isRequired,
      RightButton: React.PropTypes.func.isRequired,
    }),
    navState: React.PropTypes.shape({
      routeStack: React.PropTypes.arrayOf(React.PropTypes.object),
      idStack: React.PropTypes.arrayOf(React.PropTypes.number),
      presentedIndex: React.PropTypes.number,
    }),
    style: View.propTypes.style,
    }

Does anyone have/can anyone point me to an example of a properly formatted navigationBar node?

**Comment by brentvatne** [comment]
Check this out: https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/Navigator/NavigationBarSample.js

**Comment by evanmrose** [comment]
Thanks Brent!

**Comment by brentvatne** [comment]
No problem! :smile:
