### ISSUE TITLE
App crahses on launch upon updating the react native version on release 

### ISSUE THREAD

**Issue by santhosh77h** [facebook/react-native#16985]
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.)

### Environment
Environment:
  OS: Linux 3.10
  Node: 6.11.0
  Yarn: 1.2.0
  npm: 3.10.10
  Watchman: 4.7.0
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: ^16.0.0 => 16.0.0
  react-native: ^0.50.4 => 0.50.4

### Steps to Reproduce
On debug version app works fine but in release version app crashes on launch

### Error stack

Fatal Exception: com.facebook.react.common.JavascriptException: undefined is not an object (evaluating 'd.propTypes.style'), stack:
<unknown>@1169:521
t@2:633
<unknown>@2:224
e@2:231
<unknown>@1167:502
t@2:633
<unknown>@2:224
e@2:231
<unknown>@782:191
t@2:633
<unknown>@2:224
e@2:231
<unknown>@298:215
t@2:633
<unknown>@2:224
e@2:231
<unknown>@12:86
t@2:633
<unknown>@2:154
e@2:231
global code@1552:9

       at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:56)
       at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:40)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:154)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
       at java.lang.Thread.run(Thread.java:761)

**Comment by szholdiyarov** [comment]
@santhosh77h have you tried to clear npm cache and node_modules folder?

**Comment by santhosh77h** [comment]
@szholdiyarov  yes i have done this many times and whenever i try to create release version using this command ` cd android && sudo ./gradlew assembleRelease` i get this error  
> Failed to capture snapshot of input files for task 'bundleReleaseJsAndAssets' property $1 during up-to-date check.
> Failed to create MD5 hash for file '/project/path/metro-bundler-symbolicate1171027-20618-uzzm93.n1'.` 

so before creating release version i delete `metro-bundler-symbolicate1171027-20618-uzzm93.n1`

**Comment by szholdiyarov** [comment]
@santhosh77h try to add --verbose to get the more information and paste it here please

**Comment by santhosh77h** [comment]
11-28 11:35:44.444  8007  8058 E ReactNativeJS: undefined is not an object (evaluating 'd.propTypes.style')
11-28 11:35:44.445  8007  8058 E ReactNativeJS: Module AppRegistry is not a registered callable module (calling runApplication)
11-28 11:35:45.099  8007  8059 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
11-28 11:35:45.099  8007  8059 E AndroidRuntime: Process: com.daddyapp, PID: 8007
11-28 11:35:45.099  8007  8059 E AndroidRuntime: com.facebook.react.common.JavascriptException: undefined is not an object (evaluating 'd.propTypes.style'), stack:
11-28 11:35:45.099  8007  8059 E AndroidRuntime: <unknown>@1413:521
11-28 11:35:45.099  8007  8059 E AndroidRuntime: t@2:633
11-28 11:35:45.099  8007  8059 E AndroidRuntime: <unknown>@2:224
11-28 11:35:45.099  8007  8059 E AndroidRuntime: e@2:231
11-28 11:35:45.099  8007  8059 E AndroidRuntime: <unknown>@1408:562
11-28 11:35:45.099  8007  8059 E AndroidRuntime: t@2:633
11-28 11:35:45.099  8007  8059 E AndroidRuntime: <unknown>@2:224
11-28 11:35:45.099  8007  8059 E AndroidRuntime: e@2:231
11-28 11:35:45.099  8007  8059 E AndroidRuntime: <unknown>@1407:502
11-28 11:35:45.099  8007  8059 E AndroidRuntime: t@2:633
11-28 11:35:45.099  8007  8059 E AndroidRuntime: <unknown>@2:224
11-28 11:35:45.099  8007  8059 E AndroidRuntime: e@2:231
11-28 11:35:45.099  8007  8059 E AndroidRuntime: <unknown>@782:1814
11-28 11:35:45.099  8007  8059 E AndroidRuntime: t@2:633
11-28 11:35:45.099  8007  8059 E AndroidRuntime: <unknown>@2:224
11-28 11:35:45.099  8007  8059 E AndroidRuntime: e@2:231
11-28 11:35:45.099  8007  8059 E AndroidRuntime: <unknown>@298:215
11-28 11:35:45.099  8007  8059 E AndroidRuntime: t@2:633
11-28 11:35:45.099  8007  8059 E AndroidRuntime: <unknown>@2:224
11-28 11:35:45.099  8007  8059 E AndroidRuntime: e@2:231
11-28 11:35:45.099  8007  8059 E AndroidRuntime: <unknown>@12:86
11-28 11:35:45.099  8007  8059 E AndroidRuntime: t@2:633
11-28 11:35:45.099  8007  8059 E AndroidRuntime: <unknown>@2:154
11-28 11:35:45.099  8007  8059 E AndroidRuntime: e@2:231
11-28 11:35:45.099  8007  8059 E AndroidRuntime: global code@1537:9
11-28 11:35:45.099  8007  8059 E AndroidRuntime: 
11-28 11:35:45.099  8007  8059 E AndroidRuntime: 	at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:56)
11-28 11:35:45.099  8007  8059 E AndroidRuntime: 	at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:40)
11-28 11:35:45.099  8007  8059 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-28 11:35:45.099  8007  8059 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
11-28 11:35:45.099  8007  8059 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
11-28 11:35:45.099  8007  8059 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
11-28 11:35:45.099  8007  8059 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
11-28 11:35:45.099  8007  8059 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
11-28 11:35:45.099  8007  8059 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
11-28 11:35:45.099  8007  8059 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
11-28 11:35:45.099  8007  8059 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
11-28 11:35:45.099  8007  8059 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
11-28 11:35:45.100  1625  1636 W ActivityManager:   Force finishing activity com.daddyapp/.MainActivity
11-28 11:35:45.102  8007  8024 V FA      : Recording user engagement, ms: 1459
11-28 11:35:45.103  8007  8024 V FA      : Activity paused, time: 4752227
11-28 11:35:45.105  8007  8024 D FA      : Logging event (FE): user_engagement(_e), Bundle[{firebase_event_origin(_o)=auto, engagement_time_msec(_et)=1459, firebase_screen_class(_sc)=MainActivity, firebase_screen_id(_si)=8793034049915983839}]
11-28 11:35:45.119  2382  7891 V FA-SVC  : Logging event: origin=auto,name=user_engagement(_e),params=Bundle[{firebase_event_origin(_o)=auto, engagement_time_msec(_et)=1459, firebase_screen_class(_sc)=MainActivity, firebase_screen_id(_si)=8793034049915983839}]
11-28 11:35:45.121  2382  7891 V FA-SVC  : Saving event, name, data size: user_engagement(_e), 67
11-28 11:35:45.122  2382  7891 V FA-SVC  : Event recorded: Event{appId='com.daddyapp', name='user_engagement(_e)', params=Bundle[{firebase_event_origin(_o)=auto, engagement_time_msec(_et)=1459, firebase_screen_class(_sc)=MainActivity, firebase_screen_id(_si)=8793034049915983839}]}
11-28 11:35:45.123  2382  7891 V FA-SVC  : Upload scheduled in approximately ms: 9041
11-28 11:35:45.123  1340  1978 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 2691072
11-28 11:35:45.131  1340  1340 E EGL_emulation: tid 1340: eglCreateSyncKHR(1901): error 0x3004 (EGL_BAD_ATTRIBUTE)
11-28 11:35:45.150  2382  7891 V FA-SVC  : Cancelling job. JobID: 812057698
11-28 11:35:45.152  2382  7891 V FA-SVC  : Scheduling upload with DelayedRunnable
11-28 11:35:45.152  2382  7891 V FA-SVC  : Scheduling upload with GcmTaskService
11-28 11:35:45.152  2382  7891 V FA-SVC  : Scheduling task with Gcm. Time9041
11-28 11:35:45.154  2382  7891 V FA-SVC  : Background event processing time, ms: 36
11-28 11:35:45.178  1625  5360 I OpenGLRenderer: Initialized EGL, version 1.4
11-28 11:35:45.178  1625  5360 D OpenGLRenderer: Swap behavior 1
11-28 11:35:45.178  1625  5360 W OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
11-28 11:35:45.178  1625  5360 D OpenGLRenderer: Swap behavior 0
11-28 11:35:45.190  1625  5360 D EGL_emulation: eglCreateContext: 0x9eef5ec0: maj 2 min 0 rcv 2
11-28 11:35:45.206  1625  5360 D EGL_emulation: eglMakeCurrent: 0x9eef5ec0: ver 2 0 (tinfo 0x8f6ff8f0)
11-28 11:35:45.236  1625  5360 D EGL_emulation: eglMakeCurrent: 0x9eef5ec0: ver 2 0 (tinfo 0x8f6ff8f0)
11-28 11:35:45.240  2053  2249 D EGL_emulation: eglMakeCurrent: 0xa18852a0: ver 2 0 (tinfo 0xa1883760)
11-28 11:35:45.342  8007  8047 D EGL_emulation: eglMakeCurrent: 0x9d203780: ver 2 0 (tinfo 0x9d228910)
11-28 11:35:45.614  8007  8007 D ReactNative: ReactInstanceManager.detachViewFromInstance()
11-28 11:35:45.615  8007  8058 E ReactNativeJS: Module AppRegistry is not a registered callable module (calling unmountApplicationComponentAtRootTag)
11-28 11:35:45.635  8007  8007 E WindowManager: 
11-28 11:35:45.635  8007  8007 E WindowManager: android.view.WindowLeaked: Activity com.daddyapp.MainActivity has leaked window DecorView@12b1f8[] that was originally added here
11-28 11:35:45.635  8007  8007 E WindowManager: 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:417)
11-28 11:35:45.635  8007  8007 E WindowManager: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:331)
11-28 11:35:45.635  8007  8007 E WindowManager: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
11-28 11:35:45.635  8007  8007 E WindowManager: 	at android.app.Dialog.show(Dialog.java:316)
11-28 11:35:45.635  8007  8007 E WindowManager: 	at com.mehcode.reactnative.splashscreen.SplashScreen$1.run(SplashScreen.java:30)
11-28 11:35:45.635  8007  8007 E WindowManager: 	at android.app.Activity.runOnUiThread(Activity.java:5849)
11-28 11:35:45.635  8007  8007 E WindowManager: 	at com.mehcode.reactnative.splashscreen.SplashScreen.show(SplashScreen.java:22)
11-28 11:35:45.635  8007  8007 E WindowManager: 	at com.daddyapp.MainActivity.onCreate(MainActivity.java:30)
11-28 11:35:45.635  8007  8007 E WindowManager: 	at android.app.Activity.performCreate(Activity.java:6662)
11-28 11:35:45.635  8007  8007 E WindowManager: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
11-28 11:35:45.635  8007  8007 E WindowManager: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
11-28 11:35:45.635  8007  8007 E WindowManager: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
11-28 11:35:45.635  8007  8007 E WindowManager: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
11-28 11:35:45.635  8007  8007 E WindowManager: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
11-28 11:35:45.635  8007  8007 E WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-28 11:35:45.635  8007  8007 E WindowManager: 	at android.os.Looper.loop(Looper.java:154)
11-28 11:35:45.635  8007  8007 E WindowManager: 	at android.app.ActivityThread.main(ActivityThread.java:6077)
11-28 11:35:45.635  8007  8007 E WindowManager: 	at java.lang.reflect.Method.invoke(Native Method)
11-28 11:35:45.635  8007  8007 E WindowManager: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
11-28 11:35:45.635  8007  8007 E WindowManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)

**Comment by santhosh77h** [comment]
@szholdiyarov this error i'm getting it from from adb logcat and its in release apk build apk works fine

**Comment by szholdiyarov** [comment]
@santhosh77h try to clean the gradle folder inside Android directory

**Comment by santhosh77h** [comment]
i have downgraded react and react native checked on these versions as well it still crashes on release 
Environment:
  OS: Linux 3.10
  Node: 6.11.0
  Yarn: 1.2.0
  npm: 3.10.10
  Watchman: 4.7.0
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: ^0.49.0 => 0.49.5

**Comment by santhosh77h** [comment]
i have downgraded react and react native checked on these version as well it still crashes on release 
Environment:
  OS: Linux 3.10
  Node: 6.11.0
  Yarn: 1.2.0
  npm: 3.10.10
  Watchman: 4.7.0
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: ^0.49.0 => 0.49.5

**Comment by santhosh77h** [comment]
@janicduplessis  i saw the issue you have solved in here [https://github.com/facebook/react-native/issues/5655](old) but i was not able to solve the same can you please help me out.

**Comment by FreddieOD** [comment]
I have noticed that react 0.49.x still has exact same break. We moved to 0.48.x and no more error. I have found one guys fix for it but I can't seem to find the issue.

Basically what you have to make sure of is that you not longer get PropTypes from the react-native library but from prop-types. If you have done this, then make sure your dependencies are correctly upgraded to do the same. If they are not then 1) upgrade the dependencies if their maintainers have added this fix, or 2) fork it yourself and make the change. I had to do both.

Hope this helps

**Comment by santhosh77h** [comment]
I tried solving those two steps mentioned by @FreddieOD  still  facing the same issue it seems only option is downgrading to 0.48.x

**Comment by santhosh77h** [comment]
@FreddieOD yes the issue is solved by downgrading i don't think that is better approach
I really started thinking that how many of them are using 0.49.x and 0.50.x because i checked in both they faile creating release apk. @vjeux
