### ISSUE TITLE
An error occurred while using TouchableHighlight，can you help me?

### ISSUE THREAD

**Issue by Vagrant-gb** [facebook/react-native#16996]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Steps to Reproduce

Attempted to transition from state RESPONDER_INACTIVE_PRESS_IN to RESPONDER_ACTIVE_LONG_PRESS_IN, which is not supported. This is most likely due to Touchable.longPressDelayTimeout not being cancelled.

  | reactConsoleErrorHandler | @ | A:\CricketClient\nod…ptionsManager.js:71
  | console.error | @ | A:\CricketClient\nod…ive\YellowBox.js:62
  | _handleLongDelay | @ | A:\CricketClient\nod…le\Touchable.js:628
  | proxiedMethod | @ | A:\CricketClient\nod…rototypeProxy.js:44
  | (anonymous) | @ | A:\CricketClient\nod…mers\JSTimers.js:92
  | callTimer | @ | A:\CricketClient\nod…mersExecution.js:95
  | callTimers | @ | A:\CricketClient\nod…ersExecution.js:136
  | __callFunction | @ | A:\CricketClient\nod…MessageQueue.js:250
  | (anonymous) | @ | A:\CricketClient\nod…MessageQueue.js:101
  | __guard | @ | A:\CricketClient\nod…MessageQueue.js:218
  | callFunctionReturnFlushedQueue | @ | A:\CricketClient\nod…MessageQueue.js:100
  | (anonymous) | @ | debuggerWorker.js:71

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by Ehesp** [comment]
Maybe show some actual code usage?

**Comment by christianchown** [comment]
I get this a fair bit, running on Android on a real device.... but it only occurs after I have Hot Reloaded at least once.

If that's the case for you, @Vagrant-gb, it's safe to ignore. Just dismiss the warning dialog and continue working. I found a thread describing the reason why it occurs. I can't remember exactly what it was, but it's a non-issue.

**Comment by Vagrant-gb** [comment]
@christianchown Glad to get your reply, I am annoying at every debugging will pop up this warning, which is very detrimental to my job, so I hope we can solve this problem.

**Comment by Vagrant-gb** [comment]
@Ehesp This is an error every time TouchableHighligh is used, so the code is not clear

**Comment by christianchown** [comment]
Hello

After googling the issue, I can see it's related to a mismatch between your
PC clock and your Android device clock. Try accurately syncing the times
and you should see the issue less

**Comment by Vagrant-gb** [comment]
@christianchown I am sorry for your suggestion, I have already debugged, it seems that this issue is useless

**Comment by Vagrant-gb** [comment]
I tried a lot of methods, still can not solve this problem
