### ISSUE TITLE
Facebook's news feed navigation bar

### ISSUE THREAD

**Issue by 7ynk3r** [facebook/react-native#1700]
I'd like to implement expandable/collapsable navigation + action bars like facebook's feed news does. 
Any advice on how to proceed? 

Currently I'm using GTScrollNavigationBar. I can add it natively but it doesn't update immediately and fails because of 
`RCTAssert(self.subviews.count == 1, @"we should only have exactly one subview");` in `RCTScrollView`.  
Removing the assertion makes it work but after rotating everything looks funny, it doesn't play well with react.

Thanks!

**Comment by brentvatne** [comment]
Hey there, these types of questions are probably better suited for StackOverflow or IRC, and it'd probably help to post some code with it too. If you don't have any luck on either of those sources, ping me with what you tried / some code and I'll re-open this issue!

**Comment by 7ynk3r** [comment]
NP, to keep track

**Comment by 7ynk3r** [comment]
NP

http://stackoverflow.com/questions/31015915/facebooks-news-feed-navigation-bar-for-react-native
