### ISSUE TITLE
Javascript Exception: invalid host

### ISSUE THREAD

**Issue by afilp** [facebook/react-native#17007]
### Is this a bug report?
Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

  OS: Windows 10
  Node: 8.9.1
  Yarn: 1.3.2
  npm: 4.6.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.0.0.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.1.1 => 16.1.1
  react-native: ^0.50.4 => 0.50.4

### Expected Behavior

The installed app should launch without crashing

### Actual Behavior

When releasing the app for Android, we get this error upon launching it (the app does not even appear and crashes):

![screenshot_2017-11-28-18-09-15-846_com miui bugreport](https://user-images.githubusercontent.com/7850073/33331593-adf79b82-d46a-11e7-9e75-192de90b426d.png)

Why is this happening? We cannot release unfortunately due to this.

IMOPRTANT NOTES:
- The app works perfectly OK in DEBUG mode (`react-native run-android`)
- We are using the latest `code-push` which seems to be the only package that plays a different role in PRODUCTION mode

### Reproducible Demo

Unfortunately this happens when launching our installed app. We cannot share the entire code base of our app.

**Comment by anfieldleung** [comment]
I have exactly the same issue on ios release, @afilp are you able to fix it now? Thanks

**Comment by dbader87** [comment]
For me, the issue was that I was using Reactotron. Remove any bindings to Reactotron for your release build.

```javascript
let scriptHostname;
if (__DEV__) {
    const scriptURL = NativeModules.SourceCode.scriptURL;
    scriptHostname = scriptURL.split('://')[1].split(':')[0];
}

Reactotron
    .configure({
        name: 'Soundog',
        host: scriptHostname
    })
    .use(trackGlobalErrors())
    .use(openInEditor())
    .use(overlay())
    .use(asyncStorage())
    .use(networking())
    .use(reactotronRedux())
    .connect()
```
The `host` key in the configure method was empty. Giving the 'invalid host' exception.

If that doesn't work for you I reccomend you try to find the exception and work your way back from there.

```
find node_modules/ -type f -exec grep -H 'invalid host' {} \;
```

Hope this helps.

**Comment by ducpt2** [comment]
@dbader87 save my day. Thank you so much.
