### ISSUE TITLE
Pinch-to-Zoom doesn't work without setting scalesPageToFit={true} explicitly on WebView component.

### ISSUE THREAD

**Issue by ewhitebloom** [facebook/react-native#17005]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.)

### Steps to Reproduce

(Write your steps here:)

1. Make a WebView Component
2. Set the source attribute to have a uri value of a PDF.
3. You'll notice that you can't pinch-to-zoom without explicitly setting scalesPageToFit={true}. Even though the docs say that it is set to true by default, it appears it is not.

### Expected Behavior

The pinch-to-zoom behavior should be there without setting scalesPageToFit equal to true, explicitly. 

### Actual Behavior

Pinch-to-zoom doesn't work without setting the scalesPageToFit explicitly. 

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by baurine** [comment]
@ewhitebloom , same issue with you but in react-native 0.37.0 (an old project), and fixed it by your method, explicitly add `scalesPageToFix={true}`, thx!

**Comment by RafaelRViana** [comment]
I'm still facing same problem here.

**Comment by 452MJ** [comment]
+1

**Comment by jamonholmgren** [comment]
This issue has been migrated to https://github.com/react-native-community/react-native-webview/issues/12 and can be closed.

**Comment by Titozzz** [comment]
Closing but feel free to keep discussing on the new repo
