### ISSUE TITLE
[Docs] Documentation for using DocumentSelectionState

### ISSUE THREAD

**Issue by hansonkd** [facebook/react-native#1702]
In the TextInput docs, it has a prop for selectionState. I tried creating an instance of `DocumentSelectionState`, and adding a listener, but no events come through. Whats more, is that there is another undocumented prop (`onSelectionChange`) for TextInput that should do the same thing, however the function never seems to be called. 

https://rnplay.org/apps/eZnvIA

Is there an example of using DocumentSelectionState somewhere?

**Comment by brentvatne** [comment]
I'm not familiar with this myself, any idea @vjeux?

**Comment by vjeux** [comment]
cc @sahrens

**Comment by sahrens** [comment]
I think onSelectionChange is only supported in our internal TextView comonent that we haven't released (it's tangled with some other internal FB infra), so unfortunately this isn't going to work without a bit of effort....

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/docs-documentation-for-using-documentselectionstate
