### ISSUE TITLE
Gradle sync error in Android Studio 3.0 with scoped module

### ISSUE THREAD

**Issue by 0x5e** [facebook/react-native#17029]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: macOS High Sierra 10.13.1
  Node: 8.7.0
  Yarn: 1.2.1
  npm: 5.4.2
  Watchman: 4.9.0
  Xcode: Xcode 9.1 Build version 9B55
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.50.4 => 0.50.4

### Steps to Reproduce

1. `react-native init example && cd example`
2. `yarn add @0x5e/react-native-alipay`
3. `react-native link`
4. Open Android Studio 3.0, import `android` folder
5. Press `Sync Project with Gradle Files` button

### Expected Behavior

Gradle Sync Success

### Actual Behavior

Gradle Sync Failure

```
Missing Dependencies
Error:Unable to find module with Gradle path ':@0x5e/react-native-alipay' (needed by module 'app'.)
```

### Reproducible Demo

`react-native init example` can reproduces this issue.

### PS

1. Android Studio 2.x don't have this problem.
2. If I rename the project `:@0x5e/react-native-alipay` to `:react-native-alipay` in `android/settings.gradle` and `android/app/build.gradle`, gradle sync will success.
3. Shall we change the module name from `:@username/project-name` to `:@username:project-name` during `react-native link`? See this: https://docs.gradle.org/4.2/release-notes.html#path-separator-characters-in-names-are-deprecated

**Comment by clovs** [comment]
I confirm any sub library that contain @user... got this issue with android Studio 3 (Mac Version)

#Android Studio 2.x don't have this problem.
If I rename the project :@0x5e/react-native-alipay to :react-native-alipay in android/settings.gradle and android/app/build.gradle, gradle sync will success.
Shall we change the module name from :@username/project-name to :@username:project-name during react-native link? See this: https://docs.gradle.org/4.2/release-notes.html#path-separator-characters-in-names-are-deprecated

**Comment by lufinkey** [comment]
I am also affected by this. It would be nice if there was some way to specify the android project name in the actual native library, so that when `react-native link` is called, it uses the specified project name rather than the package name
