### ISSUE TITLE
TouchableOpacity with parent PanResponder Android problem 

### ISSUE THREAD

**Issue by MaxToyberman** [facebook/react-native#17028]
Description
I have a parent PanResponder with a child TouchableOpacity. What happens is that the TouchableOpacity doesn't respond to clicks because the PanResponder takes the click.

Additional Information

React Native version: 0.50.3
Platform: android 
Development Operating System: macOS

Code:

```
this._panResponder = PanResponder.create({
            onStartShouldSetPanResponder: (evt, gestureState) => true,
            onStartShouldSetPanResponderCapture: (evt, gestureState) => false,
            onMoveShouldSetResponderCapture: () => true,
            onMoveShouldSetPanResponder: (evt, gestureState) => true,
            onMoveShouldSetPanResponderCapture: (evt, gestureState) => {
                return gestureState.dx != 0 && gestureState.dy != 0;
            },
            onPanResponderGrant: (evt, gestureState) => {
                let isFirst = gestureState.y0 > 164 ? false : true;
                this.setState({animObj: isFirst, isUsingCurtain: true});
            },
            onPanResponderMove: (evt, gestureState) => {

                //let Y = this.state.animObj ? gestureState.moveY - this.state.currentHeaderHeight  : gestureState.moveY - this.state.currentHeaderHeight ;// - this.state.currentHeaderHeight;
                let Y = gestureState.moveY - this.state.currentHeaderHeight + 20
                if (Y < 0) {
                    return false
                }
                this.state.animCurtain.setValue(Y);
                gestureState.moveY > height / 2 ? this.setState({curtainOnMiddle: true}) : this.setState({curtainOnMiddle: false})
            },
            onPanResponderTerminationRequest: (evt, gestureState) => true,
            onPanResponderRelease: (evt, gestureState) => {
                if (((height / 2) > gestureState.moveY)) {//slide back up1
                    this._CurtainAnimation(0, false);
                } else {//slide to bottom
                    let val = height - calcSize(180);
                    this._CurtainAnimation(val, true);
                }
            },
            onPanResponderTerminate: (evt, gestureState) => {
            },
            onPanResponderStart: (e, gestureState) => {
            },
        });
```

and this is my View

```
<Animated.View
            style={[styles.bottomHPHeader, TopArroOpacity ? {opacity: TopArroOpacity} : ""]} {...this._panResponder.panHandlers}>
            <TouchableOpacity onPress={() => this._animateAutoCurtain()}>
                {this.state.curtainOnMiddle ?
                    <AIIcon image={require('../../../../assets/images/homepage/close_drawer_arrow.png')}
                            boxSize={30}/>
                    : <AIIcon image={require('../../../../assets/images/homepage/open_drawer_arrow.png')}
                              boxSize={30}/>}
            </TouchableOpacity></Animated.View>
```

**Comment by zc-Mukden** [comment]
this._panResponder = PanResponder.create({

            onStartShouldSetResponder: (evt, gestureState) => true,
            onStartShouldSetResponderCapture: () => true,
            onMoveShouldSetPanResponder: () => true,
            onMoveShouldSetPanResponderCapture: () => true,

            onPanResponderGrant: (evt, gestureState) => {
                for (let x in this._touches) {
                    if (evt.nativeEvent.touches[x]) {
                        this._touches[x].x = evt.nativeEvent.touches[x].pageX;
                        this._touches[x].y = evt.nativeEvent.touches[x].pageY;
                        this._touches[x].identifier = evt.nativeEvent.touches[x].identifier
                    }
                }
            },

            //移动回调
            onPanResponderMove: (evt, gestureState) => {
                if (evt.nativeEvent.touches.length === 1) {
                    if (this._touches[0].identifier === undefined) {

                        for (let x in this._touches) {
                            if (evt.nativeEvent.touches[x]) {
                                this._touches[x].x = evt.nativeEvent.touches[x].pageX;
                                this._touches[x].y = evt.nativeEvent.touches[x].pageY;
                                this._touches[x].identifier = evt.nativeEvent.touches[x].identifier
                            }
                        }
                        return false
                    } else {

                        let moveX = evt.nativeEvent.touches[0].pageX - this._touches[0].x;
                        let moveY = evt.nativeEvent.touches[0].pageY - this._touches[0].y;

                        this.state.left += moveX;
                        this.state.top += moveY;
                        this.setState({
                            left: this.state.left,
                            top: this.state.top
                        });

                        for (let x in this._touches) {
                            if (evt.nativeEvent.touches[x]) {
                                this._touches[x].x = evt.nativeEvent.touches[x].pageX;
                                this._touches[x].y = evt.nativeEvent.touches[x].pageY;
                                this._touches[x].identifier = evt.nativeEvent.touches[x].identifier
                            }
                        }
                    }
                } else {

                    if (this._zoom === undefined) {

                        this._zoom = {
                            x: (evt.nativeEvent.touches[0].pageX + evt.nativeEvent.touches[1].pageX) / 2,
                            y: (evt.nativeEvent.touches[0].pageY + evt.nativeEvent.touches[1].pageY) / 2,
                            distance: Math.sqrt(
                                Math.pow(evt.nativeEvent.touches[0].pageX - evt.nativeEvent.touches[1].pageX, 2)
                                + Math.pow(evt.nativeEvent.touches[0].pageY - evt.nativeEvent.touches[1].pageY, 2)
                            )
                        };
                        return false
                    } else {

                        let distanceTemp = Math.sqrt(
                            Math.pow(evt.nativeEvent.touches[0].pageX - evt.nativeEvent.touches[1].pageX, 2)
                            + Math.pow(evt.nativeEvent.touches[0].pageY - evt.nativeEvent.touches[1].pageY, 2)
                        );
                        let distanceAdd = distanceTemp - this._zoom.distance;
                        let distanceScale = distanceAdd / this._zoom.distance;

                        let scaleAdd = 0;
                        if (distanceScale === 0) {

                        } else {
                            scaleAdd = this.state.scale * distanceScale
                        }
                        let setScale = this.state.scale + scaleAdd;


                        this.state.left = (setScale / this.state.scale) *
                            (0.5 * this.state.width + this.state.left - this._zoom.x) -
                            0.5 * this.state.width + this._zoom.x;
                        this.state.top = (setScale / this.state.scale) *
                            (0.5 * this.state.height + this.state.top - this._zoom.y) -
                            0.5 * this.state.height + this._zoom.y;

                        this.state.scale = setScale;

                        this._zoom.distance = distanceTemp;
                        this.setState({
                            scale: this.state.scale,
                            left: this.state.left,
                            top: this.state.top
                        })
                    }
                }
            },

            //松开回调
            onPanResponderRelease: (evt, gestureState) => {
                this._touches = [
                    {},
                    {}
                ];
                this._zoom = undefined;
            }
        })

**Comment by zc-Mukden** [comment]
return (
            <View
                style={[styles.container, {top: this.state.top, left: this.state.left}]}
                {...this._panResponder.panHandlers}
            >
                <VideoPlayer
                    url={this.props.videoUrl}
                    onPressDrift={(url) => this.props.onPressDrift(url)}
                    imgDrift={Images.iconDriftLeft}
                />
            </View>
        );

**Comment by zc-Mukden** [comment]
我要做一个拖动的浮动视频播放器，但是，在Android真机上，VideoPlayer里的TouchableOpacity事件不响应。模拟器又完全正常。

**Comment by zc-Mukden** [comment]
简单的来说就是父组件如果带有PanResponder属性，子组件的Touchable事件在安卓真机上很难响应，几乎不响应！

**Comment by zc-Mukden** [comment]
今天测试发现，TouchableOpacity的事件除了onPress ，其他的都响应，如：onPressIn , onPressOut 都响应！
