### ISSUE TITLE
Part of the text disappears on screen with ratio 18:9

### ISSUE THREAD

**Issue by stasgalin** [facebook/react-native#17026]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Expected Behavior

The text should not be cut.

### Actual Behavior

The user can't see half of the text.

### Reproducible Demo

![image](https://user-images.githubusercontent.com/17909600/33432545-0a7745e8-d5e1-11e7-84fb-89746666bcb4.png)

**Comment by ElieMyIdea** [comment]
+1 same here

**Comment by RiusmaX** [comment]
+1 for this problem

**Comment by rahuljaguste** [comment]
facing this issue after migrating to Android 8.0. Any Solutions?

**Comment by khemmapon** [comment]
+1 found same problem here

**Comment by rahuljaguste** [comment]
I found a fix here. https://github.com/facebook/react-native/issues/15114

**Comment by Jacse** [comment]
Happens on OnePlus 5 when the user has the system font set as "Slate" instead of "Roboto".

**Comment by 814k31** [comment]
Same Here!

**OnePlus 5**

Steps to reproduce:

```jsx
<View style={styles.container}>
    {/* Prev is displayed on the button with no problems */}
    <Button title='Prev' onPress={() =>{}} />

    {/* 'Nex' is displayed */} 
    <Button title='Next' onPress={() =>{}} />

    {/*Log out button*/}
    <View style={styles.buttonContainer}>
        <Button
            onPress={() => this.logout()}
            title="Logout"
        />
    </View>
</View>

/* Later in the file */
const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#F5FCFF',
    },
    buttonContainer: {
        marginTop: 10,
        height: 40,
        alignSelf: 'stretch',
        paddingLeft: 10,
        paddingRight: 10
    },
});
```
![screenshot_20180412-143700](https://user-images.githubusercontent.com/9160551/38661017-f29ce056-3e61-11e8-8d92-6369f9c52012.jpg)

## Environment
```
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.8.0
  Yarn: Not Found
  npm: 5.7.1
  Watchman: Not Found
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.1 AI-173.4697961

Packages: (wanted => installed)
  react: ^16.3.1 => 16.3.1
  react-native: ^0.55.2 => 0.55.2
```

**Comment by RiusmaX** [comment]
Hi ! We fixed it by forcing Roboto font in styles at app start.

**Comment by jariwalabhavesh** [comment]
We are also facing same issue. 
@RiusmaX but we are not using Roboto font family we are using other font family

**Comment by RiusmaX** [comment]
@jariwalabhavesh Did you try to force it with react-native-global-font ?
