### ISSUE TITLE
Snapshot testing fails on DrawerLayoutAndroid when defaultPlatform is set to android

### ISSUE THREAD

**Issue by peterlandry** [facebook/react-native#17031]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

  Environment:
    OS: macOS High Sierra 10.13.1
    Node: 8.7.0
    Yarn: 1.2.1
    npm: 5.4.2
    Watchman: 4.9.0
    Xcode: Xcode 9.1 Build version 9B55
    Android Studio: Not Found
  
  Packages: (wanted => installed)
    react: 16.0.0 => 16.0.0
    react-native: 0.50.4 => 0.50.4

  Target Platform: Android

### Steps to Reproduce

(Write your steps here:)

1. Use the DrawerLayoutAndroid [example](https://facebook.github.io/react-native/docs/drawerlayoutandroid.html) in App.js of a newly created app
2. Set `jest.haste.defaultPlatform: "android"` package.json
3. `yarn run test`

### Expected Behavior

Snapshot test would render basic example app

### Actual Behavior

```
➜  bugreport yarn run test
yarn run v1.2.1
$ jest
 FAIL  __tests__/App.js
  ✕ renders correctly (292ms)

  ● renders correctly

    TypeError: Cannot read property 'Constants' of undefined

      at Object.<anonymous> (node_modules/react-native/Libraries/Components/DrawerAndroid/DrawerLayoutAndroid.android.js:25:48)
      at Object.get DrawerLayoutAndroid [as DrawerLayoutAndroid] (node_modules/react-native/Libraries/react-native/react-native-implementation.js:25:34)
      at App.render (App.js:33:44)
      at finishClassComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:4205:31)
      at updateClassComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:4182:12)
      at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:4561:16)
      at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6529:16)
```
Here's the line causing the issue: https://github.com/facebook/react-native/blob/1e8f3b11027fe0a7514b4fc97d0798d3c64bc895/Libraries/Components/DrawerAndroid/DrawerLayoutAndroid.android.js#L25

I believe it's because the native modules never load the constants expected, since, well, there are no native modules :) The default jest/haste setup doesn't trigger the error because `DrawerLayoutAndroid` just renders [UnimplementedView](https://github.com/facebook/react-native/blob/1e8f3b11027fe0a7514b4fc97d0798d3c64bc895/Libraries/Components/DrawerAndroid/DrawerLayoutAndroid.ios.js#L13) on ios.

As for setting android as the platform, I need to for snapshot testing on our app, as we only support web and android in our app.

### Reproducible Demo

Here's a snack with the example code running on android: https://snack.expo.io/Bym7626eG

If you use that App.js and the default test with a new react-native project, you can reproduce this with the following jest settings in package.json:

```json
    "jest": {
      "haste": {
        "defaultPlatform": "android",
        "platforms": ["android", "ios", "native"],
        "providesModuleNodeModules": [
          "react-native"
        ]
      },
      "moduleNameMapper": {
        "^React$": "<rootDir>/node_modules/react"
      },
      "modulePathIgnorePatterns": [
        "<rootDir>/node_modules/react-native/Libraries/react-native/"
      ],
      "transform": {
        "^.+\\.js$": "babel-jest",
        "^[./a-zA-Z0-9$_-]+\\.(bmp|gif|jpg|jpeg|mp4|png|psd|svg|webp)$": "<rootDir>/node_modules/react-native/jest/assetFileTransformer.js"
      },
      "transformIgnorePatterns": [
        "node_modules/(?!(jest-)?react-native|react-clone-referenced-element)"
      ],
      "setupFiles": [
        "<rootDir>/node_modules/react-native/jest/setup.js"
      ],
      "testEnvironment": "node"
    }
```

**Comment by peterlandry** [comment]
The following jest mock can avoid this issue:

```
jest.mock('react-native', function() {
  const reactNative = require.requireActual('react-native')
  reactNative.UIManager.AndroidDrawerLayout = {
    Constants: {
      DrawerPosition: {
        Left: 3,
        Right: 5
      }
    }
  }
  
  return reactNative
})
```

**Comment by martnst** [comment]
Thanks for the mocking hint. The code example did not work for me though. Hence I came up with this, which I am happy to share in case somebody needs it. 


```
jest.mock('DrawerLayoutAndroid', () => {
  const RealComponent = require.requireActual('DrawerLayoutAndroid')
  const React = require('React')
  class DrawerLayoutAndroid extends React.Component {
    render () {
      return React.createElement('DrawerLayoutAndroid', this.props, this.props.children)
    }
  }
  DrawerLayoutAndroid.propTypes = RealComponent.propTypes
  DrawerLayoutAndroid.positions = { Left: 3, Right: 5 }
  return DrawerLayoutAndroid
})
```

*I just put it at the top of my `App.test.js` for now.*
