### ISSUE TITLE
zIndex not working in Android

### ISSUE THREAD

**Issue by cruisecoders** [facebook/react-native#17039]
### Is this a bug report?
Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

 Environment:
    OS:  Windows 10 64 bit
    Node:  8.4.0
    Yarn:  0.27.5
    npm:  4.6.1

  Packages: (wanted => installed)
    react-native: 0.49.3 => 0.49.3
    react: 16.0.0-alpha.12 => 16.0.0-alpha.12

  Target Platform: Android
### Expected Behavior

![login screen](https://user-images.githubusercontent.com/27813353/33469518-5fb00c72-d689-11e7-8dbc-e12ba4e6f7d5.png)

I wanted something like this if zIndex is working properly in this.

### Actual Behavior

![skype_picture 1](https://user-images.githubusercontent.com/27813353/33469572-af5439f6-d689-11e7-9d5b-c0a63ebe8434.jpeg)

In this, the user Icon image is not coming on top of the view as zIndex is not working properly in android.

**Comment by jeveloper** [comment]
You should review 50.x branch , i believe there were specific issues resolved for zindex , yoga changes

**Comment by mudasirkhan** [comment]
This is not an issue with zIndex, your image is simply getting cropped

**Comment by lwinkyawmyat** [comment]
@facebook-github-bot label Needs more information

**Comment by lwinkyawmyat** [comment]
@facebook-github-bot no-reply
