### ISSUE TITLE
RCT_EXPORT_METHOD that takes no parameters and returns a promise throws error

### ISSUE THREAD

**Issue by JPTeasdale** [facebook/react-native#17037]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

yes

### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.9.0
  Yarn: 1.3.2
  npm: 5.5.1
  Watchman: 4.9.0
  Xcode: Xcode 9.1 Build version 9B55
  Android Studio: 3.0 AI-171.4408382

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: 0.49.3 => 0.49.3

  Target Platform: iOS (10.3)

### Steps to Reproduce

(Write your steps here:)

1. Create a native module that returns a promise

TestNativeModule.h
```
#import <Foundation/Foundation.h>
#import <React/RCTBridgeModule.h>

@interface TestNativeModule : NSObject <RCTBridgeModule>
@end
```
TestNativeModule.m
```
@implementation TestNativeModule
RCT_EXPORT_MODULE();

RCT_EXPORT_METHOD(get: findEventsWithResolver:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject) {
  resolve("test");
}
@end
```
2. Call it from JS:
```
const promise = NativeModules.CallToAdventureNative.get();
```
3. See the error:
```
CallToAdventureNative.get was called with 0 arguments but expects 1 arguments. If you haven't changed this method yourself, this usually means that your versions of the native code and JavaScript code are out of sync. Updating both should make this error go away.
```

**Note: It works if you pass *Anything* to the .get function.**

### Expected Behavior

It would call the function. 

### Actual Behavior

The error posted above. 

### Reproducible Demo

It's a native module, can't repro the web

**Comment by caschomburg123** [comment]
What are you talking about

**Comment by floriancargoet** [comment]
Try:
```
RCT_EXPORT_METHOD(get:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject) {
  resolve("test");
}
```

**Comment by anderskev** [comment]
FWIW this is still broken as of 0.53, although I believe you can get around it via the hacky solution stated above:
```
RCT_EXPORT_METHOD(someMethodName: (NSString *)blank
        resolve(RCTProniseResolveBlock)resolve
        reject(RCTPromiseRejectBlock)reject) {
    // Do something
    resolve(nil);
}
```

Then in JS
```
SomeModule.someMethodName("");
```

Like I said, **super** hacky.

**Comment by floriancargoet** [comment]
@anderskev Have you tried:
```
RCT_EXPORT_METHOD(someMethodName:(RCTPromiseResolveBlock)resolve
                  reject:(RCTPromiseRejectBlock)reject) {
  // Do something
  resolve(nil);
}
```
?
This is the expected Objective-C signature for a method receiving only resolve & reject arguments.

**Comment by PerspectivesLab** [comment]
the function 
```
RCT_EXPORT_METHOD(get: findEventsWithResolver:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject) {
  resolve("test");
}
```

should be:
```
RCT_EXPORT_METHOD(get: (RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject) {
  resolve("test");
}
```

**Comment by cmwall** [comment]
I'm just checking in on this. I'm also running into this error. Is there a better solution than that empty string hack?

**Comment by floriancargoet** [comment]
@cmwall The issue here was a incorrect syntax, there's no need for an empty string. What's your native method signature?
