### ISSUE TITLE
[ListView] View with panResponder inside ListView

### ISSUE THREAD

**Issue by PhilippKrone** [facebook/react-native#1705]
Hello,

I'm trying to build a listview with rows in it, where each row has its own panResponder (kind of analogous to react-native-swipeable-element). However, I have the problem that the panResponder of the rows get terminated (onPanResponderTerminate) once the listview is moved. Currently, I'm trying to fix the issue by setting "scrollEnabled" to false once the individual panResponder move, but this results in some kind of (noticable) lag due to the update of the listview. 

Is this the expected behaviour? I can gladly build a small snippet which demonstrates the issue - just drop me a line. However, the lag will only be noticable with a reasonable large listview..

Regards
Philipp

**Comment by PhilippKrone** [comment]
@sahrens I just tested that the lag does occur in the following version of ListView.js:

https://github.com/facebook/react-native/commit/34cef28a10b7d44be453c072578b5b6c07a0dcd8#diff-b4c8e4c7b175f06ffa084d8dca28e86a

but not in the one before. Do you have any idea why your change here might result in a lag when updating a ListView by changing the value of scrollEnabled?

**Comment by sahrens** [comment]
How does the lag manifest exactly?  While dragging the pan responder or trying to render something or?

**Comment by sahrens** [comment]
There are a couple other fixes pending that might fix your issue once they get sync'd out.

**Comment by PhilippKrone** [comment]
@sahrens to give you some background:

I have a ListView with scrollEnabled={this.state.scrollEnabled}. Each row of this ListView has a panResponder and in the respective onPanResponderMove, I set the ListView to not being scrollEnabled via this.setState({scrollEnabled: false});

````javascript
        <ListView
          ref="listview"
          ...
          scrollEnabled={this.state.scrollEnabled}
          renderRow={this.renderActivity}
          ...
  
        />

...

  renderActivity: function(item, sectionID, rowID) {
        ...
      return   <SwipeableElement
                  responderMove={(gestureState) => {
                    if (Math.abs(gestureState.dx) > 10) {
                      this.setState({scrollEnabled: false});
                    }
                  }}
   }
````

And inside the SwipeableElement, I have:

````javascript
    this._panResponder = PanResponder.create({
       ...
      onPanResponderMove: this._handlePanResponderMove,
       ...
    });

  _handlePanResponderMove: function(e, gestureState) {
    this.props.responderMove(gestureState);
  }
````


The issue now is that the line this.setState({scrollEnabled: false}); seems to induce the lag (its really slow in e.g. IPhone 4s), where as this was not the case before the mentioned commit.

**Comment by sahrens** [comment]
Hmm, it's hard to say without more code. A quick optimization would be to only setState if scrollEnabled is actually changing rather than calling it on every single touch event once your gesture is active. Something like

```
responderMove={(gestureState) => {
  if (Math.abs(gestureState.dx) > 10) {
    if (this.state.scrollEnabled) {
      this.setState({scrollEnabled: false});
    }
    ... // other gesture handling
  }
```

If that doesn't fix it, you might need to add some componentShouldUpdate or similar optimization to your code to prevent the re-rendering, or perhaps use a better rowDidChange function. Another option is to use setNativeProps to update scrollEnabled to avoid the setState/render completely.

**Comment by PhilippKrone** [comment]
Hi @sahrens 
thanks for your help. I was already trying 

````javascript
                  responderMove={(gestureState) => {
                    if (Math.abs(gestureState.dx) > 10 && this.state.scrollEnabled) {
                      this.setState({scrollEnabled: false});
                    }
                  }}
````

and this kind of helped, but there is a small lag the moment the one update occurs. I was just wondering as this has worked before without any lag and the one (small) change from your commit made it laggy, although I dont understand that at all, as your code is actually increasing the performance and not inducing lags. 

I was as well trying to use componentShouldUpdate, but its the same: one time (the moments its actually doing the re-rendering), there is a small lag. If i return false in componentShouldUpdate during the swiping of the rows completely, the ListView is not changing its "scrollEnabled" behaviour to false, resulting in a bad user experience due to a terminate of the swipe of the row once the ListView is moved.

Can you tell me one sentence more about the setNativeProps way to update scrollEnabled? I currently use setNativeProps to set top/left/right etc., but not to set native features like scrollEnabled.

Thanks!
Philipp

**Comment by PhilippKrone** [comment]
Update: just figured setNativeProps out. For reference:

````javascript
                  responderMove={(gestureState) => {
                    if (Math.abs(gestureState.dx) > 10 && this.state.scrollEnabled) {
                    //  this.setState({scrollEnabled: false});
                      this._listview.setNativeProps({scrollEnabled: false});
                    }
                  }}
                  responderEnd={() => {
                    this._listview.setNativeProps({scrollEnabled: true});
                  }}

...

        <ListView
          ref={component => this._listview = component}
````

**Comment by brentvatne** [comment]
Perfect! @PhilippKrone - I also added docs about setNativeProps recently: https://facebook.github.io/react-native/docs/direct-manipulation.html#content

If you've figured this out can you close this issue?

**Comment by PhilippKrone** [comment]
Hi @brentvatne I can happily close this topic, although I would still love to know the reason for the lag coming from the one commit. In case there is any explanation, feel free to reopen the topic and paste it in here for reference :)
