### ISSUE TITLE
Scrollview w/ pagingEnabled instantly changing page on Android when scrolling fast

### ISSUE THREAD

**Issue by mtnptrsn** [facebook/react-native#17056]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: macOS High Sierra 10.13.1
  Node: 7.9.0
  Yarn: 0.22.0
  npm: 4.2.0
  Watchman: 4.9.0
  Xcode: Xcode 9.1 Build version 9B55
  Android Studio: 2.3 AI-162.3934792

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: https://github.com/expo/react-native/archive/sdk-23.0.0.tar.gz => 0.50.3

  Target Platform: iOS (11.2) & Android (8.0)

### Steps to Reproduce

1. Create a scrollview with pagingEnabled, horizontal and 100% width & height
2. Populate the scrollview with more than 3 `<View />` elements with device width and flex: 1 (so it takes up the whole height)
3. Scroll really quickly between those elements on Android
4. You'll now see an instant hop from one element to the other, without an animation
5. Do the same thing on iOS and it will be a smooth scroll animation

### Expected Behavior

I expected it to be the same on Android as it is on iOS, a smooth scroll animation instead of instantly changing page.

### Actual Behavior

Instantly switching page on Android (without any animation)

[Video demonstration](https://drive.google.com/a/lindmarkpartner.se/file/d/1PPpKA5eqFmP8RsJi2y-CSDxKGII0K8jA/view?usp=sharing)

### Reproducible Demo

[Expo snack](https://expo.io/@mtnptrsn/scrollview-demonstration)

**Comment by Fsarmento** [comment]
I had the same problem using scrollview with pagingEnabled. Ended up using ViewPagerAndroid for android to have a smoother scrolling effect. However, it gives much more work since the scroll event props for ViewPagerAndroid.onPageScroll are "offset" and "position", not the same as in ScrollView.

**Comment by scottmas** [comment]
Experiencing this in RN 55.4
