### ISSUE TITLE
PROPOSAL: Bridge of <canvas /> web API to native layer (OpenGL ES / Bitmap etc.)

### ISSUE THREAD

**Issue by D1no** [facebook/react-native#17051]
**Getting RN ready for Augmented Reality**

The `<canvas />` element of HTML5 has been the entry point for sophisticated 3D & 2D applications written in JS. At the moment, those JS based frameworks are only able to render to react-native by either using a webview or by using third party packages which bridge parts of the `<canvas />` web api back to the corresponding native api. I.e. map webGL calls to the native OpenGL ES interface.

### Benefit
If the `<canvas />` web api would be bridged in full to the mobile platform, a century of rendering frameworks could be used flawlessly to create stunning visual effects. Instrument 3D rendering and Augmented Reality implementations within the react-native toolset by using common, well documented tools. I.e.

- [Three.js](https://threejs.org/)
- [Babylon.js](http://www.babylonjs.com/)

in cooperation with 

- [ARKit](https://developer.apple.com/arkit/)
- [ARCOre](https://developers.google.com/ar/)

avoiding the messaging bottleneck between a webview and the JS thread.

### Implementation for End-Users
Augmented Reality: https://blog.expo.io/introducing-expo-ar-mobile-augmented-reality-with-javascript-powered-by-arkit-b0d5a02ff23

### Feasibility
That this is possible is shown by third party packages that partially implement the web `<canvas />` api achieve common goals. Including facebooks reactART package for 2D rendering.

- Bridging of webGL to the native OpenGL ES API: 
  - https://github.com/gre/gl-react/tree/master/packages/gl-react-native
  - https://github.com/react-community/react-native-webgl
  - https://github.com/expo/expo/blob/cdbcfa9a323fe71afb12cd8ccdf900103925c8a1/cpp/UEXGL.cpp
- 2D Implementation (reactART / facebook): https://github.com/facebook/react-native/tree/d20a6e9d2d92bfc6bc81cc828c4008af1c7a7760/Libraries/ART
- By Google (three.ar.js for ARCore & ARKit) https://github.com/google-ar/three.ar.js

### Why should it be a part of react-native core
A lot of time has been spend on the paradigm "_learn once, use everywhere_". At the moment this approach has been held up by tying together the very heterogeneous apis of the mobile platforms. And that is great. The next logical step is to **make the underlying graphics power of modern devices accessible**. The web `<canvas />` has done that elegantly on the web — using that api to unleash the native power of mobile graphics would enable incredible user experiences; all with an existing ecosystem of libraries that are already building on top of WebGL.

Compared to the DOM and Device APIs, the Graphics Layer has **no volatile API development**. We have years of experience in dealing with the web canvas and great frameworks that instrument them well. Satellite implementations by third party packages of the `<canvas />` seem like an unnecessary uncertainty for using frameworks and libraries that rely on proper `<canvas />` implemention. If the api is done once and well, it will little change in shape in the future. As volatility is often a reason to prefer to have contributions be maintained outside of the core, this seems to not be the issue.

It's a **straight implementation**. That it is very well possible to bridge the full `<canvas />` api to a **foreign** platform (or back to its OpenGL origin) is very well shown by the maintainers of babylon.js (microsoft), who have created a webgl 2D bridge to be independent of the DOM for node.js chakra:

https://www.eternalcoding.com/?p=1922

I hope we can achieve the same for react-native.

### Related Issues / Tickets
https://github.com/facebook/react-native/issues/12119
https://github.com/facebook/react-native/issues/246

### Is this a bug report?

 - [x] No (but it concurrences a full implementation related to ART; therefore here, not on canny)

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

 - [x] Yes

### Context
The Problem and this Issue was featured in my talk at the [reactday.berlin](https://reactday.berlin/) Conference on Dec. 2, 2017:

[![Augmented Reality with React Native](https://user-images.githubusercontent.com/2397125/33524769-0f33cc5c-d823-11e7-97cc-f9c4dbdab09c.png "Augmented Reality with React Native")][ss1]

[ss1]: https://twitter.com/DinoScheidt/status/937274264817987584

**Comment by satya164** [comment]
Don't think it should be part of the core, especially because it's likely that Facebook some be supporting it and it'll increase the API surface and maintenance overhead if RN, which is already huge. Furthermore, the releases will be tied to React Native releases instead of being independent.

If course if it's officially supported by Facebook, it'll be awesome. But even then I'd really like to see it in a separate repo, like Metro Bundler. If also like to see more UI components moved out of the core, but that's a separate topic.

**Comment by axemclion** [comment]
In the spirit of reducing the surface area for React Native, I agree with @satya164 that this should not be a part of the core. 

Is there a reason that this a this cannot be added as a plugin to ReactNative ?
