### ISSUE TITLE
TextInput green drop 

### ISSUE THREAD

**Issue by mudasirkhan** [facebook/react-native#17057]
Am facing an issue with textInput in JMAX tabs.
i get a green drop whenever i select some text and that green drop doesnt dissappear till the app is running.
It seems like it happens for every react app that we install on the tab.

**Comment by joseluizmonteirojr** [comment]
Same here!! 
I'm able to reproduce this on 57 as well..
Related: #17060 and #17188.
Device: Samsung Galaxy J2 - Android 5.1.1

I've tested on Motorola Moto E, and didn't happen. 
It probably only happens on Samsung devices.
