### ISSUE TITLE
[Android] React ART can't draw large width Surface on android 6 device

### ISSUE THREAD

**Issue by lisbakke** [facebook/react-native#17052]
### Is this a bug report?

Yes.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.1.3
  Yarn: 1.1.0
  npm: 5.0.3
  Watchman: 3.9.0
  Xcode: Xcode 9.1 Build version 9B55
  Android Studio: 3.0 AI-171.4408382

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.50.4 => 0.50.4

### Steps to Reproduce

A Surface with width >= 2049 will not render on devices running Android 6 (android 7 not tested). If the width is < 2049 then the surface renders.

(Write your steps here:)

1. Create a surface with width 2049
2. Add a Group with a Shape
3. Run the code **on a device**. FYI the simulator works fine.

### Expected Behavior

I expected the shape to render with >= 2049 pixel surface width.

### Actual Behavior

The shape does not render. It is blank.

### Reproducible Demo

https://github.com/lisbakke/art-surface-repro

1. Clone the repo, yarn / npm

2. Plug in a physical device

3. Run on device.

4. There are two graphs with identical code, except one has a width of 2048 and one has a width of 2049. The graph with width 2049 **does not render.**

I've attached a screenshot of the app on my device.
![screenshot_20171202-120423](https://user-images.githubusercontent.com/982613/33518941-982183ca-d75a-11e7-87e5-9edf9706e285.png)

**Comment by alwaysonlinetxm** [comment]
I have met the same issue.

**Comment by iloveplus** [comment]
@lisbakke did you solve it?

**Comment by iloveplus** [comment]
@react-native-bot I updated to React Native 0.53.3 and still have this issue.
