### ISSUE TITLE
FEATURE - Support for Fragments in react native instead of view

### ISSUE THREAD

**Issue by chakrihacker** [facebook/react-native#17053]
### Is this a bug report?

No

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

yes

It would be nice if we can have something like fragments in react native just like react which recently landed. Please provide your opinions

**Comment by lwinkyawmyat** [comment]
If you want to features request, you can request [here](https://react-native.canny.io/feature-requests). So, we should close this issues.

@facebook-github-bot close
