### ISSUE TITLE
Please suggest a tutorial to integrate react-native app with existing app

### ISSUE THREAD

**Issue by ranvirgorai** [facebook/react-native#17058]
### Is this a bug report?
On android build **ReactApplication** not found
(write your answer here)

react-native-cli: 2.0.1
react-native: 0.50.3

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.)

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by lwinkyawmyat** [comment]
@facebook-github-bot close
