### ISSUE TITLE
Proper doc about packaging the apps and deployment

### ISSUE THREAD

**Issue by sumanta-ghosh** [facebook/react-native#17063]
### Is this a bug report?
This is not an issue. 
There is a ton of example how to use the react native components but there is no doc how to package the code and deploy it. Mainly there is no doc about
**`react-native bundle`**

So please add doc for it or if anybody knows good resource for it then please share it

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes I read it

**Comment by hramos** [comment]
Hey! Thanks for the feedback. Our docs are now over at https://github.com/facebook/react-native-website, would you mind moving the suggestion over there?
