### ISSUE TITLE
Image reload when app from background to active

### ISSUE THREAD

**Issue by SephoraCode** [facebook/react-native#17069]
### Is this a bug report?

No sure

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

YES

### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 6.10.3
  Yarn: 0.21.3
  npm: 5.5.1
  Watchman: 4.7.0
  Xcode: Xcode 9.1 Build version 9B55
  Android Studio: Not Found

Packages: (wanted => installed)
  react: ^16.0.0-alpha.12 => 16.0.0
  react-native: 0.48.0 => 0.48.0

### Steps to Reproduce

(Write your steps here:)

1. run app ( home is rn, other page is native page),
2.click myAccount jump to native page,
3. com+h  app is background state,
4. click app open this, and click home 
5. Image reload????   why ?

![121121](https://user-images.githubusercontent.com/25217992/33598947-7d9bfcc4-d9df-11e7-9ec1-24a5538f05bc.gif)

 I dont known this is bug ?  can you help me .  ths

**Comment by lwinkyawmyat** [comment]
@facebook-github-bot stack-overflow

**Comment by fokoz** [comment]
Why did this issue should ask in `stackoverflow` ? it should be the direct issue of `react-native`.
I'm facing this issue for local images, I have a lot of local images and it causes a slow load instead of white reload image.
