### ISSUE TITLE
[Android] Overflow does not work and is inconsistent with iOS

### ISSUE THREAD

**Issue by slorber** [facebook/react-native#17074]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

  Environment:
    Expo SDK 23 (RN 50)

### Steps to Reproduce

Use this minimal [Expo Snack](https://snack.expo.io/HyPoVZVWG)

### Expected Behavior

The children elements of the Snack should overflow their parent container (I think), or at least both platforms should handle that Snack consistently which is not the case.

### Actual Behavior

The platforms are inconsistent with each others when using the exact same code.

![image](https://user-images.githubusercontent.com/749374/33605455-2c36d0b8-d9ba-11e7-9ea1-b0293537e383.png)

![image](https://user-images.githubusercontent.com/749374/33605534-841b4534-d9ba-11e7-9758-8dd55d42ce59.png)

### Reproducible Demo

Use this minimal [Expo Snack](https://snack.expo.io/HyPoVZVWG)

### Additional notes

There has been [changes regarding `overflow: hidden`](https://github.com/facebook/react-native/issues/3198) on Android  that probably shipped with RN50, so it may be a regression. As far as I know it has been noticed as a regression in my app when updating from Expo22 to Expo23 (which use RN50).

I tried using zIndex, position absolute, transforms, overflow visible, collapsable=false... nothing made the inner views overflow correctly on Android.

**Comment by slorber** [comment]
cc @AaaChiuuu maybe you have an idea on what is happening here? By the way I'm interested by any workaround.

**Comment by slorber** [comment]
hmm ok sorry there is a popular Canny for that: https://react-native.canny.io/feature-requests/p/add-overflow-support-to-android

**Comment by Noitidart** [comment]
@slorber - Expo is not up to date with RN updates usually. Is Expo using RN 50? Did the overflow hidden fix land in 50? Or is it going to land in 51?

**Comment by slorber** [comment]
Expo is currently using RN50 and I think this fix landed in RN50:

![image](https://user-images.githubusercontent.com/749374/33660424-fa2ca866-da83-11e7-852f-c9af19ebf693.png)

so for me it still does not work

I'm not even sure to understand what is happening here, was there recently an attempt to support overflow visible that broke overflow hidden?

**Comment by Noitidart** [comment]
Thanks @slorber - so that screenshot, does that mean all those tags is where this code is found? And v0.50.0-rc.0 is where it was first found?

**Comment by slorber** [comment]
I guess :)

**Comment by faurehu** [comment]
+1 and I've got Expo 24.0.0 and using Expo's fork with React-native 51.0.0.

**Comment by vvavepacket** [comment]
+1 I am using RN 0.51.0 still same issue

**Comment by lsps9150414** [comment]
+ 1

**Comment by Ekhui** [comment]
+1 I am using RN 0.52.0 still same issue .
how did you solved it? ?

**Comment by goforwork** [comment]
same issue，waiting solution

**Comment by nikasvan** [comment]
Any updates on this?

**Comment by lugrugzo** [comment]
Would like to know as well. 

```
Environment:
  OS: macOS Sierra 10.12.6
  Node: 9.3.0
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.0 => 0.53.0
```

**Comment by garan82** [comment]
This is still an issue.

**Comment by jilb1992** [comment]
Still an issue.. almost with expo i didn't try with a react native clean proyect

**Comment by slorber** [comment]
Expo 25 is based on RN 0.52, so it won't work until SDK 26 is published. If you want to claim it's still an issue, make sure you are using RN 0.53 @garan82 @jilb1992 

I haven't tested myself, can't tell

**Comment by zeh** [comment]
Just to make it clear, it is still an issue on RN 0.53.

This has been a problem for a long time. Some people say it's going to be fixed when `FlatUIImplementation` is implemented by default instead - I've seen "June" [mentioned in this thread](https://react-native.canny.io/feature-requests/p/add-overflow-support-to-android) - but I haven't seen any official signal on that, not have I tried manually turning `FlatUIImplementation` on.

**Comment by floriancargoet** [comment]
I tried the provided example on a fresh RN 0.53.3 project, it is still an issue indeed.

**Comment by erikxavier** [comment]
Still an issue, RN 0.53.3.

Any luck with FlatUIImplementation ? How to test this ?

**Comment by DrRefactor** [comment]
RN 0.53 - no luck of finding workaround for this yet, have you guys figured one out?

**Comment by NrqhEIcsRi004** [comment]
Still an issue, RN 0.55.3.

**Comment by RomanISWG** [comment]
same issue on RN 0.55.4
