### ISSUE TITLE
Problem with RN Android App with 64k+ methods

### ISSUE THREAD

**Issue by danZheng1993** [facebook/react-native#17077]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: macOS High Sierra 10.13
  Node: 8.7.0
  Yarn: 1.2.1
  npm: 5.4.2
  Watchman: 4.9.0
  Xcode: Xcode 9.0 Build version 9A235
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: ^0.50.0 => 0.50.0

### Steps to Reproduce

1. Install Various React Native Libraries with lots of methods (React-Native-FBSDK, React-Native-Firebase...)
2. Run react-native run-android

### Expected Behavior

Build and Run without any issues

### Actual Behavior

throws exception:
```
Execution failed for task ':react-native-firebase:transformClassesWithDexForDebugAndroidTest'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
```
![screen shot 2017-12-05 at 7 23 01 am](https://user-images.githubusercontent.com/33262634/33614799-2ac00e7a-d98d-11e7-8d24-26ade497de34.png)

**Comment by charpeni** [comment]
Hey @danZheng1993,

The 64k methods limitation cames from Android and it's not directly related to react native.

You need to configure your application for Multidex support, here's the documentation: https://developer.android.com/studio/build/multidex.html

**Comment by charpeni** [comment]
@facebook-github-bot close
