### ISSUE TITLE
Issue template broken link?

### ISSUE THREAD

**Issue by anohren** [facebook/react-native#17078]
### Is this a bug report?

Yes and no.

>   If you answered "No":
> 
>     We use GitHub Issues exclusively for tracking bugs in React Native. If you're looking for help,
>     the Community page at http://facebook.github.io/react-native/support.html list various resources 
>     that should help you get started.

That address is a 404.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

No.

### Environment

Firefox 57.0.1

### Steps to Reproduce

1. Visit http://facebook.github.io/react-native/support.html 

### Expected Behavior

I expected a page that lists various resources.

### Actual Behavior

A 404 page appears.

[Screenshot](https://screenshots.firefox.com/c4pux2WU8NvDARgc/facebook.github.io)

**Comment by charpeni** [comment]
Thank you for the reporting @anohren.

I'll fix this.

**Comment by charpeni** [comment]
@facebook-github-bot label Documentation
