### ISSUE TITLE
com.facebook.react.common.JavascriptException: All native instances should have a tag.

### ISSUE THREAD

**Issue by dongawli** [facebook/react-native#17070]
# Is this a bug report?
No sure, as application is working on all latest mobiles. Issue found on only Samsung J7 Max mobile. 

# Environment:
npm: 5.5.1
Android Studio: 3.0 AI-171.4443003
targetSdkVersion 18

# Packages: ( installed)
react: 16.0.0-alpha.12
react-native: 0.47.2
# Third Party Packages used
"react-native-calendars": "^1.9.3",
"react-native-hr": "^1.1.3",
"react-native-indicators": "^0.10.0",
"react-native-material-dropdown": "^0.4.2",
"react-native-modal-dropdown": "^0.5.0",
"react-native-models": "^0.7.9",
"react-native-orientation": "^3.1.0",
"react-native-overlay": "^0.5.0",
"react-native-popup-dialog": "^0.10.43",
"react-native-pull-to-refresh": "^2.1.2",
"react-native-push-notification": "^3.0.1",
"react-native-radio-buttons": "^1.0.0",
"react-native-section-list-get-item-layout": "^2.1.0",
"react-native-segmented-control-tab": "^3.2.1",
"react-native-simple-popover": "^2.0.1",
"react-native-sliding-calendar-view": "^0.1.3",
"react-native-table-component": "^1.0.6",
"react-native-vector-icons": "^4.4.2",

# Steps to Reproduce

Open Android Native App => Open React-native page => Open another activity => Application Crash with following error - 
FATAL EXCEPTION: mqt_native_modules
Process: com.ms.engage, PID: 3258
com.facebook.react.common.JavascriptException: All native instances should have a tag., stack:
l@114:389
Br@115:18673
Rt@114:20659
_updateChildren@115:27301
updateChildren@115:26806
receiveComponent@115:28378
receiveComponent@115:2339
updateChildren@115:25392
_reconcilerUpdateChildren@115:26047
_updateChildren@115:26918
updateChildren@115:26806
receiveComponent@115:28378
receiveComponent@115:2339
updateChildren@115:25392
_reconcilerUpdateChildren@115:26047
_updateChildren@115:26918
updateChildren@115:26806
receiveComponent@115:28378
receiveComponent@115:2339
_updateRenderedComponentWithNextElement@115:14747
_updateRenderedComponent@115:14597
_performComponentUpdate@115:13989
updateComponent@115:13054
performUpdateIfNecessary@115:11962
performUpdateIfNecessary@115:2705
be@114:10867
perform@115:3484
perform@115:3484
perform@115:4728
$o@115:4889
closeAll@115:4141
perform@115:3571
batchedUpdates@115:18574
Te@114:11043
Re@114:11081
enqueueSetState@115:6436
setState@100:3104
unregisterPopover@306:1200
value@300:1357
value@300:966
unmountComponent@115:10481
unmountComponent@115:2176
unmountChildren@115:25762
unmountChildren@115:27414
unmountComponent@115:27955
unmountComponent@115:2176
unmountChildren@115:25762
unmountChildren@115:27414
unmountComponent@115:27955
unmountComponent@115:2176

# Expected Behavior
Should work on all devices.

# Actual Behavior
Not working on Samsung J7 Max. 
Currently application is working almost all latest phone . 
After exiting/closing the react-native page and launching new activity, application crashes with above exception.

**Comment by lwinkyawmyat** [comment]
@facebook-github-bot stack-overflow

**Comment by dongawli** [comment]
Hi @lwinkyawmyat : just able to solve the issue. It's my code fault. 
In Activity's onDestroy() method, I am calling unmountReactApplication() first and then destroying the ReactInstanceManager object. On high configuration mobiles, its processing fast and not found any difference. But on low configuration mobiles, it throws error in method unmountReactApplication() and ReactInstanceManager never calls destroy method which causing application crash. 

So this is just update for new beginners, that first call mReactInstanceManager.destroy() and then unmount the react-native root view by calling  mReactRootView.unmountReactApplication()

if (mReactInstanceManager != null) {
	mReactInstanceManager.destroy();
}
new Handler().postDelayed(new Runnable() {
	@Override
	public void run() {
	    mReactRootView.unmountReactApplication();
	    mReactRootView = null;
	}
},200);
