### ISSUE TITLE
Problem with React Native Android App with 64k+ methods

### ISSUE THREAD

**Issue by danZheng1993** [facebook/react-native#17076]
I have problem with running RN Android app using ```react-native run-android```

It throws exception at the build stage and can't figure out the issue.

```
Execution failed for task ':react-native-firebase:transformClassesWithDexForDebugAndroidTest'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
```

I've tried various solutions on the web and it was all in vein.
Tried solutions were enabling multiDex and increase the javaMaxHeapSize in dexOptions.

Anyone faced similar problems?

This error can be seen as a library or component dependent, but it happens for any kind of apps which exceeds 64k limits.

One more thing:
It compiles without any problem in Android Studio

**Comment by chirag04** [comment]
i would suggest investigating which module is adding so many methods first. multiDex or jumboMode should work if you really need more than 64k.

**Comment by danZheng1993** [comment]
I have tried those methods, but wasn't help for me.
I have added jumboMode true to the android{ dexOptions { } }, but still go
same issue.

**Comment by skrywus** [comment]
@danZheng1993 I have the same issue right now. Have you fixed it somehow?
