### ISSUE TITLE
404 movies.json using URL from tutorial (https://facebook.github.io/react-native/movies.json)

### ISSUE THREAD

**Issue by happyspace** [facebook/react-native#17082]
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: Windows 10
  Node: 8.6.0
  Yarn: 1.3.2
  npm: 5.4.2
  Watchman: 4.9.0
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: ^0.50.3 => 0.50.4

### Steps to Reproduce

(Write your steps here:)

1. Open URL https://facebook.github.io/react-native/movies.json
2. Note that the URL returns a 404

### Expected Behavior

The URL returns a simple JSON document containing a few movies.

See tutorial...
https://facebook.github.io/react-native/docs/network.html

This was working a few weeks ago. Add a redirect so github returns the correct document or update the URL in the docs. 

### Actual Behavior
404

![image](https://user-images.githubusercontent.com/571100/33633252-fea61356-d9c4-11e7-9769-5802b14c2053.png)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by hramos** [comment]
Thanks for the feedback! The repository for the website is now located at https://facebook.github.io/react-native-website. A PR to fix this has already been opened over there.
