### ISSUE TITLE
Require('image!'+'name') doesn't work for big images

### ISSUE THREAD

**Issue by ecesena** [facebook/react-native#1708]
I reduced my issue to this minimal repro (react-native 0.5.0). I have a png of about 1MB, with smaller images I have no issues.
```
var image = require('image!name');
```
works properly, while
```
var image = require('image!'+'name');
```
returns "Requiring unknown module...".

My use case would be to have jpg images, and of course 'name' will be a variable different for each image. Will jpg be supported anytime soon? Thanks! E.

**Comment by browniefed** [comment]
A static analysis done to determine what images to include or not, so doing dynamic images is not supported. At least that is what I assume is going on here.

**Comment by ide** [comment]
@browniefed is right. @ecesena please try `var image = require('image!name');` with your big image. If you want to dynamically display an image based on its name, write this:

```js
function getImageSourceByName(name) {
switch (name) {
case 'pic1':
  return require('image!pic1');
case 'pic2':
  return require('image!pic2');
case 'pic3':
  return require('image!pic3');
}
}
```

Then you can write `<Image source={getImageSourceByName(name)} />`.
