### ISSUE TITLE
Feature: Autofill options for Android Oreo

### ISSUE THREAD

**Issue by jeremistadler** [facebook/react-native#17097]
Android Oreo (API level 26) introduces autofill for login and credit card info.
It already works right now for react native but we have no way of configuring options for the autofill.

### Features: 

- [ ] Autofill hints to 
- [ ] Autofill important / not important (captcha)
- [ ] Force an autofill request
- [ ] Check if autofill is enabled

### Suggestion of solution
```jsx
<TextInput autofillHint="username" />
<TextInput autofillMode="important" />
<View autofillMode="not-important"><Stuff /></View>
 
this.ref.input.requestAutofill()
```

More info can be found here: https://developer.android.com/guide/topics/text/autofill.html

**Comment by jeremistadler** [comment]
I don't know what I am missing. I give up to try getting this as open.
Is it possible to create a PR for a closed issue?

**Comment by gaodeng** [comment]
+1

**Comment by cassiozen** [comment]
Please upvote the feature request here: https://react-native.canny.io/feature-requests/p/support-for-android-autofill-framework
