### ISSUE TITLE
[Packager] can't reconnect to chrome after being closed.

### ISSUE THREAD

**Issue by uber5001** [facebook/react-native#1709]
If the packager is closed and re-opened, and a debugging tab in chrome still exists, the packager has issues connecting to the tab.

When "Launching Dev Tools..." in the packager, Chrome switches to the correct tab, but the page does not refresh. This give the error (in the simulator):

    Runtime is not ready. Make sure Chrome is running and not paused on a breakpoint or exception and try reloading again.

Additionally, the chrome tab shows:

    Status: Disconnected from proxy. Is node server running?

Currently, my solution is to remember to close the debugging tab and then refresh iOS. This needs to be done every time the packager needs to be re-opened.

**Comment by jtremback** [comment]
I've found that reloading the web page works.

**Comment by brentvatne** [comment]
@uber5001 - does @jtremback's solution work for you?

**Comment by uber5001** [comment]
Yup. Both refreshing and closing it work.

**Comment by brentvatne** [comment]
@amasad - is this something that can be easily fixed?

**Comment by frantic** [comment]
Should be fairly easy to fix, see [debugger.html](https://github.com/facebook/react-native/blob/master/packager/debugger.html#L88), just need to add some code that tries to reconnect. Anyone fancy a PR?

**Comment by longdivision** [comment]
> Should be fairly easy to fix, see debugger.html, just need to add some code that tries to reconnect. Anyone fancy a PR?

Added reconnection in #1992. This was a fun one because the platform impl for `WebSocket` (e.g. `WebSocket.ios.js`) and `setTimeout` would override the browser impl and would stop working when the packager went down. I had to alias them on startup so I could reference them later to reconnect.

**Comment by browniefed** [comment]
@brentvatne seems like this was fixed and imported.
