### ISSUE TITLE
Android doesn't respect autoCapitalize when secureTextEntry is set

### ISSUE THREAD

**Issue by joshhornby** [facebook/react-native#17099]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

```
Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.4.0
  Yarn: 1.2.1
  npm: 5.3.0
  Watchman: 4.9.0
  Xcode: Xcode 9.1 Build version 9B55
  Android Studio: 3.0 AI-171.4408382

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.50.1 => 0.50.1
```

### Steps to Reproduce

```
<View style={styles.container}>
        <TextInput
          placeholder="Text"
          secureTextEntry={true}
          autoCapitalize="none"
          underlineColorAndroid="rgba(0, 0, 0, 0)"
        />
      </View>
```

### Expected Behavior

Keyboard shouldn't be auto capitalized. It seems when `autoCapitalize` and `secureTextEntry` are both set `autoCapitalize` is ignored. If I remove `secureTextEntry` then `autoCapitalize` works as expected. **This only happens on Android**.

### Actual Behavior

Keyboard is auto capitalized when `secureTextEntry` is set

### Reproducible Demo

https://snack.expo.io/ByoIR0rbG

**Comment by Sommerfeld** [comment]
I just made a project with `react-native init foo` and pasted your code. My actual behaviour is **not** a auto capitalized keyboard. (Android Emulator - Nexus 5X API25)
Additionally (just to clarify) the first character is lower cased if I start typing **without** pressing shift before.

Also downgraded to your react-native version. Same result.

---

Even so I can not reproduce this behaviour: As far as I see react-native does not unset any input type flags set by `autoCapitalize` when setting `secureTextEntry` (or other way around). So I don't think we could call it a react-native bug. This might be a problem with some versions of android?

https://github.com/facebook/react-native/blob/1e18d907bfb8cc5f4f2e1a1ede0dd98aec40ab11/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactTextInputManager.java#L509-L526

**Comment by joshhornby** [comment]
Thanks for the response @Sommerfeld.

I updated to the latest React Native and seemed to work on my Android device. So putting it down to something strange in Android, thanks.

**Comment by sunweiyang** [comment]
@joshhornby @Sommerfeld, I believe this issue should be re-opened. (Or please let me know if a new issue should be opened -- the issue would be identical to this one.)

I'm seeing this exact issue also on devices running Android API 26-27 (Oreo 8.0 and 8.1), with react-native@0.52.0. However, autoCapitalize +secureTextEntry for my same app seems to be fine on certain other Android versions (such as API 24 / Nougat 7.0).
