### ISSUE TITLE
KeyboardAvoidingView doesn't re-calculate padding on subsequent layout changes.

### ISSUE THREAD

**Issue by avendiart** [facebook/react-native#17098]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

```
Environment:
  OS:  macOS High Sierra 10.13.1
  Node:  8.9.0
  Yarn:  1.2.1
  npm:  5.5.1
  Watchman:  4.9.0
  Xcode:  Xcode 9.1 Build version 9B55
  Android Studio:  3.0 AI-171.4408382

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.49.3 => 0.49.3
```

### Steps to Reproduce

1. Wrap your view into a `KeyboardAvoidingView`.
2. Change the layout, so that `onLayout` would trigger.

### Expected Behavior

The bottom padding should change accordingly.

### Actual Behavior

While `onLayout` is being triggered and picked up by `KeyboardAvoidingView` it doesn't lead to the `bottom` value being re-calculated, as the `onLayout` event listener doesn't trigger a change in the state.

### Reproducible Demo

https://snack.expo.io/BkrVxWm-z

Our solution so far has been to create our own version of `KeyboardAvoidingView` which re-calculates the changes. It works for us, but may not be the best way to solve this problem: http://www.mergely.com/6xBeZfAq/

**Comment by jr2wolfgang** [comment]
Apologies, but how can I use your merged code? This issue of KeyboardAvoidingView is driving me nuts for days.

**Comment by avendiart** [comment]
@jr2wolfgang Just use the right side of the diff here: http://www.mergely.com/6xBeZfAq/

**Comment by hegelstad** [comment]
Needs to be reopened.
