### ISSUE TITLE
how can use RN on secondary display？

### ISSUE THREAD

**Issue by winnerliu** [facebook/react-native#17090]
### Is this a bug report?

No

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

yes

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

how can use RN on secondary display like https://developer.android.com/reference/android/app/Presentation.html

support it ？

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by lwinkyawmyat** [comment]
@facebook-github-bot stack-overflow
