### ISSUE TITLE
can't find variable:Component

### ISSUE THREAD

**Issue by yoyo0427** [facebook/react-native#17104]
### Is this a bug report?
Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Steps to Reproduce

(Write your steps here:)

1.Build a new project use react-native: 0.51.0
2.import React, { Component} from 'react'

### Expected Behavior

No mistake

### Actual Behavior

can't find variable:Component
![1](https://user-images.githubusercontent.com/12933263/33705552-b4ae3c12-db6b-11e7-93bb-c4c97198d8df.png)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by lwinkyawmyat** [comment]
@facebook-github-bot stack-overflow

**Comment by Naveen7892** [comment]
Check if all classes extending Component, have Component imported.

In my case, I missed to import Component for Sidebar class. Hope it helps.

Import methods:
Method 1: 
import React from 'react';
... class ... extends React.Component { ... }

Method 2:
import React, { Component } from 'react';
... class ... extends Component { ... }

**Comment by prasad456** [comment]
@Naveen7892 
I used method 2, but i'm facing the issue after I added AppTabNavigator Component in return menthod
