### ISSUE TITLE
[TabBarIOS] tintColor and barTintColor do not work

### ISSUE THREAD

**Issue by hyusetiawan** [facebook/react-native#1711]
Taking from the [example](http://facebook.github.io/react-native/docs/tabbarios.html#examples) and changing the tint colors, the icon and tint color are still the default blue:

https://www.rnplay.org/apps/67MHTQ

**Comment by charlie-gbox** [comment]
having the same problem here. they don't have any effect

**Comment by everfire130** [comment]
The same

**Comment by owais** [comment]
Facing the same issue with 0.5.0

**Comment by jeanregisser** [comment]
The fix for this is available from 0.6.0-rc

**Comment by brentvatne** [comment]
Yup, this is fixed in 0.6.0-rc and on master: https://www.rnplay.org/apps/ShFX9g
