### ISSUE TITLE
[ios][issue] tintColor on image component does not work 

### ISSUE THREAD

**Issue by aidan2129** [facebook/react-native#17111]
### Is this a bug report?

(write your answer here)
Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.)

### Steps to Reproduce

(Write your steps here:)

1. Add a png to <Image/> with a tint color
2. view the image and the tint color remains unchanged
3.

### Expected Behavior
the non transparent pixels on the image should change to the set color as mentioned in the docs under image component

(Write what you thought would happen.)

### Actual Behavior
Color does not change.

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by lwinkyawmyat** [comment]
@facebook-github-bot cannot-repro

**Comment by aidan2129** [comment]
@lwinkyawmyat so if you add something like` <Image source={require("IMAGEURLHERE")} tintColor={"red"}/> ` it displays as red on ios for you?

**Comment by lwinkyawmyat** [comment]
@aidan2129 , It not worked for me check on [snack](https://snack.expo.io/r1o2j0wZM). We should need to re-open this issue.

**Comment by aidan2129** [comment]
@lwinkyawmyat Nope not working for me on snack either

**Comment by aidan2129** [comment]
created new issue https://github.com/facebook/react-native/issues/17124
