### ISSUE TITLE
App crash with error "index=4 count=3" using LayoutAnimation.easeInEaseOut() on Android

### ISSUE THREAD

**Issue by jay1337** [facebook/react-native#17118]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

This bug has been there for several months and is still there with react-native@0.51.0.

Environment:
  OS: Windows 10
  Node: 8.9.1
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.0.0.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.2.0 => 16.2.0
  react-native: 0.51.0 => 0.51.0

### Steps to Reproduce

On Android, updating a specific (but very simple) component tree after calling LayoutAnimation.easeInEaseOut() leads to an error.
Here is a repro : https://snack.expo.io/H1H0AbDZM
Just click 2 times on the top text component to see the app crash.

### Expected Behavior

No app crash.

### Actual Behavior

Component are not correctly rendered after first click (some are missing).
App crash after second click.:

```
index=4 count=3
addInArray
    ViewGroup.java:3971
addViewInner
    ViewGroup.java:3902
addView
    ViewGroup.java:3733
addView
    ViewGroup.java:3678
addView
    ViewGroupManager.java:47
manageChildren
    NativeViewHierarchyManager.java:401
execute
    UIViewOperationQueue.java:180
run
    UIViewOperationQueue.java:819
flushPendingBatches
    UIViewOperationQueue.java:926
access$2100
    UIViewOperationQueue.java:47
doFrameGuarded
    UIViewOperationQueue.java:986
doFrame
    GuardedFrameCallback.java:31
doFrame
    ReactChoreographer.java:136
doFrame
    ChoreographerCompat.java:107
run
    Choreographer.java:765
doCallbacks
    Choreographer.java:580
doFrame
    Choreographer.java:549
run
    Choreographer.java:753
handleCallback
    Handler.java:739
dispatchMessage
    Handler.java:95
loop
    Looper.java:135
main
    ActivityThread.java:5221
invoke
    Method.java
invoke
    Method.java:372
run
    ZygoteInit.java:899
main
    ZygoteInit.java:694
```

### Reproducible Demo

Cf Steps to Reproduce

**Comment by jay1337** [comment]
Hey !

**Comment by DanGDroid** [comment]
#15698

**Comment by Larrysea** [comment]
@react-native-bot hello I am still face this exception com.facebook.react.uimanager.IllegalViewOperationException: ViewManager for tag 10 could not be found  did this also solved in v0.53.0

**Comment by AndrePech** [comment]
I am having the same issue.

**Comment by psg2** [comment]
I am having the same issue.

**Comment by AsensioM** [comment]
I have the same issue as well w/ v0.53.0

**Comment by tiaaaa123** [comment]
Same. with RN 0.55.2

**Comment by mstiggle** [comment]
Same issue here. Real bummer that I have to disable most uses of LayoutAnimation for android

**Comment by evanjmg** [comment]
Android crashes on Flatlist with LayoutAnimation. Please note this in the docs as warning until this index handling is fixed
