### ISSUE TITLE
Error "index=4 count=3" with LayoutAnimation.easeInEaseOut() on Android

### ISSUE THREAD

**Issue by jay1337** [facebook/react-native#17113]
On Android, updating a specific (but very simple) component tree after calling `LayoutAnimation.easeInEaseOut()` leads to an error :

```
index=4 count=3
addInArray
    ViewGroup.java:3971
addViewInner
    ViewGroup.java:3902
addView
    ViewGroup.java:3733
addView
    ViewGroup.java:3678
addView
    ViewGroupManager.java:47
manageChildren
    NativeViewHierarchyManager.java:401
execute
    UIViewOperationQueue.java:180
run
    UIViewOperationQueue.java:819
flushPendingBatches
    UIViewOperationQueue.java:926
access$2100
    UIViewOperationQueue.java:47
doFrameGuarded
    UIViewOperationQueue.java:986
doFrame
    GuardedFrameCallback.java:31
doFrame
    ReactChoreographer.java:136
doFrame
    ChoreographerCompat.java:107
run
    Choreographer.java:765
doCallbacks
    Choreographer.java:580
doFrame
    Choreographer.java:549
run
    Choreographer.java:753
handleCallback
    Handler.java:739
dispatchMessage
    Handler.java:95
loop
    Looper.java:135
main
    ActivityThread.java:5221
invoke
    Method.java
invoke
    Method.java:372
run
    ZygoteInit.java:899
main
    ZygoteInit.java:694
```

Here is a repro : https://snack.expo.io/H1H0AbDZM
Just click 2 times on the top text component to see the app crash.

This bug has been there for several months and is still there with `react-native@0.51.0`.

Thanks in advance for your help.

**Comment by TechyTimo** [comment]
Same issue here. Test the template below. Trying to toggle some views using a button.

`import React, { Component } from 'react';

import { 
  View, 
  Text, 
  LayoutAnimation, 
  Button } from 'react-native';


export default class Testing extends Component {
  state = {
    showOthers: false
  }
  componentWillUpdate(){
    LayoutAnimation.easeInEaseOut()
  }
  showOthers = () => {
    this.setState({ showOthers: !this.state.showOthers })
  }
  render() {

    const { showOthers } = this.state

    return (
        <View>

          {showOthers && 
            <View>
              <Text>One</Text>
              <Text>Two</Text>
            </View>
          }
          
          <Text>Three</Text>
          <Text>Four</Text>

          {showOthers && 
            <Text>Five</Text>
          }

          <Button onPress={this.showOthers} title={showOthers ? 'Hide Others' : 'Show Others' } />

      </View>
    );
  }
}
`

Using:
 
 "react": "16.2.0",
 "react-native": "0.53.0",

**Comment by psg2** [comment]
I'm facing the same problem.
