### ISSUE TITLE
Execution failed for task ':app:processDebugResources'. > com.android.ide.common.process.ProcessException: Failed to execute aapt

### ISSUE THREAD

**Issue by prasanthyejje** [facebook/react-native#17117]
i am new to react native i had to start a project in React-native which involves FCM notification, i did follow this article
https://github.com/evollu/react-native-fcm

After adding services.json file in my android/app , i updated the all android files as mentioned in above article , but i am getting the error "Failed to execute aapt"

i am using 

Os: windows 7 64 bit 
Ram:8Gb
react-native-cli: 2.0.1
react-native: 0.50.3

and also i am little bit confusing over this topic in react-native please help me 

thanks in advance

**Comment by yvkschaefer** [comment]
https://github.com/facebook/react-native/issues/16906

**Comment by Arshiamidos** [comment]
app/build.gradle
android {
    compileSdkVersion 25
    buildToolsVersion "25.0.0"

    defaultConfig {

**Comment by fetot** [comment]
Try installing android p sdk and change compileSdkVersion value to 28

**Comment by paba002** [comment]
@fetot Thanks! this worked for me

**Comment by emmadal** [comment]
thanks it work for me. great job
