### ISSUE TITLE
imports[0] for react-transform-hmr does not look like React

### ISSUE THREAD

**Issue by delayhsiao** [facebook/react-native#17112]
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.)

yes

### Steps to Reproduce

(Write your steps here:)

1. i install react-native-cli with npm in global
2. then, run 'react-native init test' to create project
3. i run 'react-native run-ios' when the project create complete
4. the simulator run success, and "react-native" normal install & run

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

it show me the normal page and then show me the error after short time.
<img width="374" alt="wx20171208-001453 2x" src="https://user-images.githubusercontent.com/9155059/33725803-32eee9c2-dbae-11e7-9cae-c85c1771e10b.png">

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by lwinkyawmyat** [comment]
@facebook-github-bot needs-repro

**Comment by delayhsiao** [comment]
i recreate the project with 0.44.3
it works.
i will retry to create project with 0.51.0 later
thx for reply.

**Comment by lwinkyawmyat** [comment]
@facebook-github-bot close

**Comment by vhmolinar** [comment]
Could you solve this? I'm facing this problem at the newer version.
