### ISSUE TITLE
react-native link fails for all modules

### ISSUE THREAD

**Issue by allthetime** [facebook/react-native#17129]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 7.10.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 8.0 Build version 8A218a
  Android Studio: 1.5 AI-141.2456560

Packages: (wanted => installed)
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: 0.48.0 => 0.48.0

### Steps to Reproduce

`react-native link react-native-fbsdk` 
or simply
`react-native link`

### Expected Behavior

I thought it would link react-native-fbsdk

### Actual Behavior

```
rnpm-install ERR! ERRPACKAGEJSON No package found. Are you sure this is a React Native project?

Cannot read property '_text' of undefined
```

### Reproducible Demo

This is a tooling issue, can only reproduce at command line, doesn't matter what the app is.

**Comment by allthetime** [comment]
starting clean by pulling my git repo to another folder and doing npm install fixed the problem.

**Comment by drewandre** [comment]
I had commented out code in my android manifest which was throwing this error. The code was below the closing `</manifest>` tag -- any commented out code within these tags was fine.
