### ISSUE TITLE
App crash when build for production

### ISSUE THREAD

**Issue by atton16** [facebook/react-native#17120]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: macOS High Sierra 10.13.1
  Node: 8.9.0
  Yarn: 1.3.2
  npm: 5.5.1
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.50.3 => 0.50.3

Target Platform: iOS 11.2, Android 7.1.1

### Steps to Reproduce

1. Build for release (i.e. react-native run-ios --configuration release)
2. Run the app

### Expected Behavior

The app runs fine without a crash.

See this [demo](https://snack.expo.io/SykiZlu-M)

### Actual Behavior

App crash with JS errors:

v

TypeError: function is undefined. (<-- This is not the actual sentence).

### Reproducible Demo

See this [demo](https://snack.expo.io/SykiZlu-M)

Or download the [source code](https://www.dropbox.com/sh/4hy1c1fwohtkm3e/AAD7dChxATWQpU6DJIKPkjKsa?dl=0)

If you run this demo on Snack or on React Native **development** **environment** or on **Expo Snack** it will **work** just **fine**.

But if you run it on **react-native with release environment**, it will **crash** the app.

I have tracked it down to the cause and suspect that somehow **babel** compiler **optimize** the code **differently** with **release** **environment**.

I **tried** to **bundle** JS **manually** **without minify** it, same result.

So **there must be more to it under the hood**.

This only affect the part of the code that use 'serviceprovider' package.

Specifically, problem only rises once a service is depend on another.

My workaround for React native so far

1. constructed services without 'serviceprovider' and

2. export them as a singleton

3. and use node's 'import' as the mean for resolving the dependency

there will be no problem at all.

**Comment by ranggarifqi** [comment]
i have the same issue too...

i've upgraded my RN from 0.46 to 0.51

on development server, there isn't any issue and work perfectly
But after i build the release version, it crashed exactly after i open the app..

Do you have any solution ?
i don't quite understand about your workaround... how to do that ?

thanks :)

**Comment by atton16** [comment]
@ranggarifqi The workaround is specifically designed to fix my demo source code. It really depends on the root of the problem. I am not sure if you are using the same library that has problem with RN.

**Comment by sandropoluan** [comment]
Same problem with RN 0.51

**Comment by dhanushuUzumaki** [comment]
Any updates on this? Facing the same issue.

**Comment by temitope** [comment]
Also ran into this issue. Any updates?

**Comment by dhanushuUzumaki** [comment]
@temitope  Downgrading to RN 0.45.1 and React 16.0.0-alpha.8 solved the issue for me.
Related issue: https://github.com/facebook/react-native/issues/16567

**Comment by temitope** [comment]
@dhanushuUzumaki thanks for the update
