### ISSUE TITLE
[ios][issue] tintColor on image component does not work on ios

### ISSUE THREAD

**Issue by aidan2129** [facebook/react-native#17124]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes
### Environment
  OS: macOS Sierra 10.12.6
  Node: 7.4.0
  Yarn: Not Found
  npm: 5.5.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: ^16.0.0 => 16.0.0
  react-native: ^0.51.0 => 0.51.0

### Steps to Reproduce

1.Create a page with an image component in it.
2.Add a tintColor prop to the image component with any color valid color value in it
3.View the image on your screen 

### Expected Behavior

I though the rendered image would change to the tintColor set on the image component.

### Actual Behavior

The image renders but the color has not been changed. On android the color is changed as expected just not on ios.

![tint-color-bug](https://user-images.githubusercontent.com/4376874/33772763-abb5c5fe-dc2d-11e7-9aa4-897787fa43c3.png)

### Reproducible Demo

https://snack.expo.io/r1o2j0wZM

**Comment by Sommerfeld** [comment]
In the docs tintColor is listed under `style`. This works on both platforms. Actually you might should call it a bug that your code is working on android.

Just change your code to

```js
<Image
  style={{width: 50, height: 50, tintColor: 'red'}}
  source={{uri: 'https://facebook.github.io/react-native/docs/assets/favicon.png'}}
/>
```

**Comment by akamahesh** [comment]
I am having the same issue with this ie. passing tint as a prop to the image 

```
<Image
  tintColor='#2d3436'
  style={{width: 20, height: 15,margin:10}}
  source={{uri: 'backsignup'}}/>
```  
This works fine for android but not in android

If you want it to work on ios as well go with this ie. passing tint color with style instead of passing it as a props 

```
<Image
  style={{ width: 20,height: 23,margin: 10,tintColor: "#2d3436"}}
  source={{ uri: "pdficon" }}
/>
```

**Comment by rikur** [comment]
Still an issue.

**Comment by kientux** [comment]
Anyone got a fix for this? Still tinting not working on iOS.

**Comment by JeffGuKang** [comment]
It is not working on 0.57.3

**Comment by janaka120** [comment]
In Android, If you pass **tintColor** with style instead. It's not working.
```
<Image
  style={{ width: 20,height: 23,margin: 10, tintColor: "#2d3436"}}
  source={{ uri: "pdficon" }}
/>
```

But it works when you pass it as **prop** to **Image**.
```
<Image
  tintColor='#2d3436'
  style={{width: 20, height: 15,margin:10}}
  source={{uri: 'backsignup'}}/>
```

**Comment by uguraktas** [comment]
is this work in windows ?

> In Android, If you pass **tintColor** with style instead. It's not working.
> 
> ```
> <Image
>   style={{ width: 20,height: 23,margin: 10, tintColor: "#2d3436"}}
>   source={{ uri: "pdficon" }}
> />
> ```
> But it works when you pass it as **prop** to **Image**.
> 
> ```
> <Image
>   tintColor='#2d3436'
>   style={{width: 20, height: 15,margin:10}}
>   source={{uri: 'backsignup'}}/>
> ```



> In Android, If you pass **tintColor** with style instead. It's not working.
> 
> ```
> <Image
>   style={{ width: 20,height: 23,margin: 10, tintColor: "#2d3436"}}
>   source={{ uri: "pdficon" }}
> />
> ```
> But it works when you pass it as **prop** to **Image**.
> 
> ```
> <Image
>   tintColor='#2d3436'
>   style={{width: 20, height: 15,margin:10}}
>   source={{uri: 'backsignup'}}/>
> ```
is this work in windows ?
