### ISSUE TITLE
A lot of symlinks - dropbox don't like it

### ISSUE THREAD

**Issue by Norfeldt** [facebook/react-native#17121]
### Is this a bug report?

Perhaps..

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Skimmed.. hope it's okay for this type of issue - otherwise just delete my issue.

### Environment

  Environment:
    OS:  macOS Sierra 10.12.6
    Node:  8.4.0
    Yarn:  0.27.5
    npm:  5.4.0
    Watchman:  4.7.0
    Xcode:  Xcode 8.3.3 Build version 8E3004b
    Android Studio:  2.3 AI-162.4069837

  Packages: (wanted => installed)
    react-native: 0.49
    react: 16.0.0-alpha.12 => 16.0.0-alpha.12

### Steps to Reproduce

I have been in contact with dropbox because I had some performance issues - iPhone simulator doesn't work well when dropbox is running. Dropbox is also way behind with my node_modules.

Initiazing new react-native projects and adding npm packages seems to create a lot of symlinks.

They told me that it was due to all the symlinks...

2 Questions:

1. Can I just delete the symlinks, without breaking it all?

2. Is there a way to work with react native and npm so it doesn't create all these symlinks?

(Yes, I don't understand what symlinks are or do)

**Comment by lwinkyawmyat** [comment]
@facebook-github-bot stack-overflow
