### ISSUE TITLE
React Native Image Prefetch Is Not Caching GIFs, And Falsely Says it Does (only tested on iOS)

### ISSUE THREAD

**Issue by ztratar** [facebook/react-native#17137]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 7.2.1
  Yarn: 0.17.10
  npm: 3.10.9
  Watchman: Not Found
  Xcode: Xcode 8.3.3 Build version 8E3004b
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: https://github.com/expo/react-native/archive/sdk-23.0.0.tar.gz => 0.50.3

### Steps to Reproduce

- Using Image.prefetch, prefetch a GIF that is online such as the one here: https://78.media.tumblr.com/30cc9a2d916a3b93b0505686f3e16369/tumblr_nj6azbWpcP1twakhqo1_540.gif
- Enter a view that shows the image
- Although the image should be loaded from the cache, it is always loaded on the spot.

### Expected Behavior

I expect prefetching to work with Animated GIFS.

### Actual Behavior

- I am building a card stack interface, and the cards have image backgrounds. Some of them are GIFs.
- I am using the Image library from react-native to prefetch all images from the cards. The goal of this is to create a fast UX. -> Image.prefetch(url)
- The JPGs and static images are preloaded fine -- they show up immediately as intended.
- GIFs, however, are not. They are loading after the fact, live, once the view is rendered.
- The output from the Image.prefetch(url) is a promise, and when identified it appears all caching is running. Even the GIF prefetch requests are returning true.
- When the view showing the actual Image has the source.cache property set to only load the image if it's in the cache, the JPGs and such still show up (cache validated), and the GIFs do not.
- I have only tested this on iOS, and have tested GIFs from multiple source URLs.

### Reproducible Demo

This demo will show you exactly what I'm talking about. =)

https://snack.expo.io/BkMaU5iWG

**Comment by shiqkuangsan** [comment]
I was shocked when I found that the gifs only displayed once on Android , But when I use a web-gif by uri reference, it worked well. And however the iOS does not meet the problem.

**Comment by ztratar** [comment]
Hey Shiqkuangsan! I'm not sure what you mean -- does that have to do with prefetching/caching GIFs?

**Comment by shiqkuangsan** [comment]
When I used xxx.gif in the 'asset' path of my project  by require-reference, the gif only displayed once, and stopped, behaved like a png, But when I changed the method to use uri: 'http:xxx/.../xxx.gif', the same gif workded well.  I don't know why.

**Comment by ztratar** [comment]
Sounds weird, but unrelated to the bug I posted above.

**Comment by shiqkuangsan** [comment]
So I came here and found your issue, thought you maybe also met this problem~But thank you all the same.

**Comment by shiqkuangsan** [comment]
And as for your issue, I tested on Android. I enter a activity contained a web-gif prefetched from site, and than I exit my app, and turn off wifi, open app and enter the same activity, the gif works well. Does it means the prefetch method cached the gif ?

**Comment by shiqkuangsan** [comment]
And I upload that problem-gif to a web, and than use uri:'xxx'  to display it, it does not worked, so I can say there is something with my gif, and I change to another gif, my problem solved.
