### ISSUE TITLE
[Android 7.0] Text color is not working

### ISSUE THREAD

**Issue by fokoz** [facebook/react-native#17139]
### Is this a bug report?
Yes

### Environment

Environment:
  OS:  macOS High Sierra 10.13
  Node:  9.1.0
  Yarn:  Not Found
  npm:  5.5.1
  Watchman:  4.4.0
  Xcode:  Xcode 9.0.1 Build version 9A1004
  Android Studio:  2.3 AI-162.3764568

Packages: (wanted => installed)
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: ^0.48.2 => 0.48.2

 Target Platform: Android 7.0 (Samsung)

### Steps to Reproduce

1. Setting text color style `<Text style={{color: 'red'}}>Test</Text>`
2. Nothing has changed 

### Expected Behavior

Text color shows as styling

### Actual Behavior

Text color doesn't change (black color)

**Comment by Dorentin1997** [comment]
Try reloading the app "RR" twice when you make changes.

**Comment by fokoz** [comment]
@Dorentin1997 It is not working both production and debug mode. I tested only on Samsung(Android 7.0). Android 6,5,4 is working fine.

**Comment by shanematte** [comment]
And sony phone. Android 7. Text color only black and white.
