### ISSUE TITLE
Text component have borders in iphone 6p

### ISSUE THREAD

**Issue by cuiken** [facebook/react-native#17143]
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.)

### Environment

   react-native:  0.51.0
  Target Platform: iOS (11.2)

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior
The Text component in the simulator is normal, but in the iPhone 6p real machine have some borders.
<img width="370" alt="screen shot 2017-12-11 at 17 16 44" src="https://user-images.githubusercontent.com/1669444/33823763-339a6234-de97-11e7-8af6-654b7250d892.png">

(Write what you thought would happen.)

### Actual Behavior
![2b01f577-0296-45d0-a492-962fd46d0d99-1682-000000ea966a882e_tmp](https://user-images.githubusercontent.com/1669444/33823242-632f635c-de95-11e7-9ea9-c8094d0202f3.jpg)

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by yechunxi** [comment]
I face the same problem

react-native： 0.46.4
iOS (10.3.1)

**Comment by yechunxi** [comment]
I solve the problem by the way:
 check this file "ios/RN/Images-2.xcassets/Brand Assets.launchimage/Contents.json"
the config has  this  property :"unassigned" : true" , and remove it

**Comment by cuiken** [comment]
Hi @yechunxi  ,thanks for your attention.
But,there is no "unassigned" property in my project.
The "Contents.json" is just config for image file ，why it causes this.

**Comment by Andrei-Vakulski** [comment]
Same issue for me on iphone 8 ios 11.2.
