### ISSUE TITLE
react-native-fbsdk makes my build fail

### ISSUE THREAD

**Issue by sun2rise** [facebook/react-native#17147]
### Is this a bug report?

YES

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

YES

### Environment
    OS:  macOS Sierra 10.12.6
    Node:  8.9.3
    Yarn:  1.3.2
    npm:  5.6.0
    Watchman:  4.9.0
    Xcode: 9.1 (9B55)
    Android Studio:  3.0 AI-171.4443003

  Packages: (wanted => installed)
    "react": "^16.0.0-beta.5"
    "react-native": "^0.49.5"

### Steps to Reproduce

1. `create-react-native-app my-test-app`
2. `cd my-test-app`
3. `npm run eject`
  3.1. option1: React Native: I'd like a regular React Native project
  3.2 option2: give a name
  3.3 option3: confirm
4. `yarn add react-native-fbsdk`
5. react-native link react-native-fbsdk
6. configure native project as described [here](https://github.com/facebook/react-native-fbsdk#3-configure-native-projects)
6. react-native run-android

### Expected Behavior

The app is built and runs on android without any problem

### Actual Behavior

I have this error during the build of the project:
```
➜  my-test-app react-native run-android
Scanning folders for symlinks in /Users/sunrising/Documents/work/sitrap/my-test-app/node_modules (7ms)
JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug)...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-fbsdk'.
      > Could not resolve all dependencies for configuration ':react-native-fbsdk:_debugPublishCopy'.
         > Could not find com.android.support:appcompat-v7:27.0.1.
           Searched in the following locations:
               file:/Users/sunrising/Library/Android/sdk/extras/android/m2repository/com/android/support/appcompat-v7/27.0.1/appcompat-v7-27.0.1.pom
               file:/Users/sunrising/Library/Android/sdk/extras/android/m2repository/com/android/support/appcompat-v7/27.0.1/appcompat-v7-27.0.1.jar
               file:/Users/sunrising/Documents/work/sitrap/my-test-app/android/sdk-manager/com/android/support/appcompat-v7/27.0.1/appcompat-v7-27.0.1.jar
           Required by:
               mytestapp:react-native-fbsdk:unspecified
         > Could not find com.android.support:appcompat-v7:27.0.1.
           Searched in the following locations:
               file:/Users/sunrising/Library/Android/sdk/extras/android/m2repository/com/android/support/appcompat-v7/27.0.1/appcompat-v7-27.0.1.pom
               file:/Users/sunrising/Library/Android/sdk/extras/android/m2repository/com/android/support/appcompat-v7/27.0.1/appcompat-v7-27.0.1.jar
               file:/Users/sunrising/Documents/work/sitrap/my-test-app/android/sdk-manager/com/android/support/appcompat-v7/27.0.1/appcompat-v7-27.0.1.jar
           Required by:
               mytestapp:react-native-fbsdk:unspecified > com.facebook.react:react-native:0.50.3
         > Could not find com.android.support:support-annotations:27.0.1.
           Searched in the following locations:
               file:/Users/sunrising/Library/Android/sdk/extras/android/m2repository/com/android/support/support-annotations/27.0.1/support-annotations-27.0.1.pom
               file:/Users/sunrising/Library/Android/sdk/extras/android/m2repository/com/android/support/support-annotations/27.0.1/support-annotations-27.0.1.jar
               file:/Users/sunrising/Documents/work/sitrap/my-test-app/android/sdk-manager/com/android/support/support-annotations/27.0.1/support-annotations-27.0.1.jar
           Required by:
               mytestapp:react-native-fbsdk:unspecified > com.facebook.android:facebook-android-sdk:4.29.0 > com.facebook.android:facebook-core:4.29.0
         > Could not find com.android.support:support-core-utils:27.0.1.
           Searched in the following locations:
               file:/Users/sunrising/Library/Android/sdk/extras/android/m2repository/com/android/support/support-core-utils/27.0.1/support-core-utils-27.0.1.pom
               file:/Users/sunrising/Library/Android/sdk/extras/android/m2repository/com/android/support/support-core-utils/27.0.1/support-core-utils-27.0.1.jar
               file:/Users/sunrising/Documents/work/sitrap/my-test-app/android/sdk-manager/com/android/support/support-core-utils/27.0.1/support-core-utils-27.0.1.jar
           Required by:
               mytestapp:react-native-fbsdk:unspecified > com.facebook.android:facebook-android-sdk:4.29.0 > com.facebook.android:facebook-core:4.29.0
         > Could not find com.android.support:appcompat-v7:27.0.1.
           Searched in the following locations:
               file:/Users/sunrising/Library/Android/sdk/extras/android/m2repository/com/android/support/appcompat-v7/27.0.1/appcompat-v7-27.0.1.pom
               file:/Users/sunrising/Library/Android/sdk/extras/android/m2repository/com/android/support/appcompat-v7/27.0.1/appcompat-v7-27.0.1.jar
               file:/Users/sunrising/Documents/work/sitrap/my-test-app/android/sdk-manager/com/android/support/appcompat-v7/27.0.1/appcompat-v7-27.0.1.jar
           Required by:
               mytestapp:react-native-fbsdk:unspecified > com.facebook.android:facebook-android-sdk:4.29.0 > com.facebook.android:facebook-common:4.29.0
         > Could not find com.android.support:cardview-v7:27.0.1.
           Searched in the following locations:
               file:/Users/sunrising/Library/Android/sdk/extras/android/m2repository/com/android/support/cardview-v7/27.0.1/cardview-v7-27.0.1.pom
               file:/Users/sunrising/Library/Android/sdk/extras/android/m2repository/com/android/support/cardview-v7/27.0.1/cardview-v7-27.0.1.jar
               file:/Users/sunrising/Documents/work/sitrap/my-test-app/android/sdk-manager/com/android/support/cardview-v7/27.0.1/cardview-v7-27.0.1.jar
           Required by:
               mytestapp:react-native-fbsdk:unspecified > com.facebook.android:facebook-android-sdk:4.29.0 > com.facebook.android:facebook-common:4.29.0
         > Could not find com.android.support:customtabs:27.0.1.
           Searched in the following locations:
               file:/Users/sunrising/Library/Android/sdk/extras/android/m2repository/com/android/support/customtabs/27.0.1/customtabs-27.0.1.pom
               file:/Users/sunrising/Library/Android/sdk/extras/android/m2repository/com/android/support/customtabs/27.0.1/customtabs-27.0.1.jar
               file:/Users/sunrising/Documents/work/sitrap/my-test-app/android/sdk-manager/com/android/support/customtabs/27.0.1/customtabs-27.0.1.jar
           Required by:
               mytestapp:react-native-fbsdk:unspecified > com.facebook.android:facebook-android-sdk:4.29.0 > com.facebook.android:facebook-common:4.29.0
         > Could not find com.android.support:support-v4:27.0.1.
           Searched in the following locations:
               file:/Users/sunrising/Library/Android/sdk/extras/android/m2repository/com/android/support/support-v4/27.0.1/support-v4-27.0.1.pom
               file:/Users/sunrising/Library/Android/sdk/extras/android/m2repository/com/android/support/support-v4/27.0.1/support-v4-27.0.1.jar
               file:/Users/sunrising/Documents/work/sitrap/my-test-app/android/sdk-manager/com/android/support/support-v4/27.0.1/support-v4-27.0.1.jar
           Required by:
               mytestapp:react-native-fbsdk:unspecified > com.facebook.android:facebook-android-sdk:4.29.0 > com.facebook.android:facebook-common:4.29.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 11.653 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html
```

### Reproducible Demo

Take a look at *Steps to Reproduce*

**Comment by massoprod** [comment]
I have the same issue. 

![snimka obrazovky 2017-12-11 o 16 47 45](https://user-images.githubusercontent.com/8200096/33839624-0d0d6c78-de93-11e7-80f5-b04be91e8e75.png)

**Comment by massoprod** [comment]
I have the same issue.

**Comment by sun2rise** [comment]
now i have 
`compileSdkVersion 26` and `buildToolsVersion "26.0.1"`

and
```
dependencies {
... 
   compile "com.android.support:appcompat-v7:26+"
    compile "com.android.support:design:26+"
    compile "com.android.support:recyclerview-v7:26+"
    compile "com.android.support:cardview-v7:26+"
...
}
```
but i always get 
```
<mypath> .../node_modules/react-native-fbsdk/android/build/intermediates/res/merged/release/values-v26/values-v26.xml:15:21-54: AAPT: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.

<mypath> .../node_modules/react-native-fbsdk/android/build/intermediates/res/merged/release/values-v26/values-v26.xml:15: error: Error: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.


:react-native-fbsdk:processReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-fbsdk:processReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt
```

**Comment by chirag04** [comment]
This might be a problem in react-native-fbsdk or your app setup. I suggest asking this on the react-native-fbsdk or stackoverflow.

**Comment by chirag04** [comment]
@facebook-github-bot stack-overflow

**Comment by sun2rise** [comment]
@chirag04 it seems that react-native-fbsdk has the issue section disabled, I will try in stackoverflow anyway... have you ever seen something like this?

**Comment by sy92th** [comment]
# 1 ) Goto android/build.gradle add maven { url 'https://maven.google.com/' name 'Google' }
```
allprojects {
    repositories {
        ...
        // Add 
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }
}

```

#  2) Goto android/app/build.gradle 
```
android {
    // change to
    compileSdkVersion 26
    buildToolsVersion "26.0.2"
    defaultConfig {
        ...
        // change to
        targetSdkVersion 26
    }
}
dependencies {
    ...
    // change all com.android.support to version 26.1.0
    com.android.support:appcompat-v7:26.1.0
}
```
# 3 ) When you has error AAPT: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.
Example:

`/node_modules/react-native-fbsdk/android/build/intermediates/res/merged/release/values-v26/values-v26.xml:15: error: Error: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.`

You can go to react-native-fbsdk/android/app/build.gradle and edit same  2 )

**Comment by yannickschuchmann** [comment]
For me [this](https://stackoverflow.com/a/47786292/1410503) was the simplest solution.
Way better than fiddling with node_modules. But be aware of updating the SDK dependency manually from time to time.. :)

**Comment by crysfel** [comment]
I had to define the facebook sdk version on `android/build.gradle`:

```
allprojects {
    repositories {
        ...
        configurations.all {
            resolutionStrategy {
                force 'com.facebook.android:facebook-android-sdk:4.28.0'
            }
        }
    }
}
```

**Comment by rafaesc** [comment]
It works @yannickschuchmann @crysfel 

Thanks!

**Comment by ujwal-setlur** [comment]
@rafaesc You might be using a lower compileSdkVersion and buildToolsVersion under android/app/build.gradle. I had used 23 and 23.0.1 respectively, and had the same problem as you. When I used 26 and 26.0.1, I could use the solution by @yannickschuchmann  

```
    compileSdkVersion 26
    buildToolsVersion "26.0.1"
```

**Comment by nenti** [comment]
Error reappeared in `react-native-fbsdk@0.7.0` and the resolutionStrategy with fiex facebook-sdk version doesn't help in `0.7.0`. Anyone has a solution for the new version?

**Comment by rafaesc** [comment]
@nenti, yes, I had to change to 0.6.3 version, I need a new solution for 0.7.0

**Comment by ujwal-setlur** [comment]
0.70.0 works for as long as I stick to older sdk libraries. When I use latest sdk library, app crashes on launching.

**Comment by MinhNQ90** [comment]
I try all the solution which have been provide but it didn't work.
My issue is in fbsdk build.gradles, it use com.android.support:appcompat-v7:27.0.2
but the newest version i can see in my folder C:\Users\ComputerName\AppData\Local\Android\sdk\extras\android\m2repository\com\android\support\appcompat-v7 is 26.0.0-alpha1
I try to update in Android Studio but still the same.

**Comment by warrenronsiek** [comment]
Adding a [maven repository url to google](https://stackoverflow.com/a/47727794/3112506) solved this for me:

```
allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            url "https://maven.google.com"
            }
        configurations.all {
            resolutionStrategy {
                force 'com.facebook.android:facebook-android-sdk:4.28.0'
                }
            }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
                url "$rootDir/../node_modules/react-native/android"
            }

        }
    }  
```

**Comment by chuckcwh** [comment]
@heralight 
As you mentioned the error in facebook docs
use
compile 'com.facebook.android:facebook-android-sdk:[4,5)'

<-- this is the same as facebook doc?

So far I tried 0.7.0 and got no luck :(

**Comment by donghungx** [comment]
what a idiot SDK, cant get success build

**Comment by ujwal-setlur** [comment]
Yeah, given that this is a Facebook module meant to work with their own react-native framework, I must say this should have been much more robust

**Comment by heralight** [comment]
@chuckcwh there is an error in https://developers.facebook.com/docs/android/getting-started/
they write "implementation" in step 5 instead of "compile"...

Have you any log on crash, rn or android ?

**Comment by chuckcwh** [comment]
@heralight 
Thanks for reply.
I was following [this:](https://developers.facebook.com/quickstarts/?platform=android) so I used "compile".

**Finally I got it to work**

** What I did**
Versions - blank app with only
react-native 0.54.2 (I tried from 0.52, 54.0, 54.1, 54.2)
react-native-fbsdk 0.7.0

after following the tutorial the errors were
> Could not find com.android.support:appcompat-v7:27.0.2.
...

then I added this to **build.gradle**
allprojects {
    repositories {
        ...
        configurations.all {
            resolutionStrategy {
                force 'com.facebook.android:facebook-android-sdk:4.28.0'
            }
        }
        maven {
            url "https://maven.google.com"
            }
        configurations.all {
            resolutionStrategy {
                force 'com.facebook.android:facebook-android-sdk:4.28.0'
                }
            }
    }
}

then the error became this:
/Users/chuck/Code/fblogin/android/app/build/intermediates/res/merged/debug/values-v24/values-v24.xml:3: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.

/Users/chuck/Code/fblogin/android/app/build/intermediates/res/merged/debug/values-v24/values-v24.xml:4: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.

/Users/chuck/Code/fblogin/android/app/build/intermediates/res/merged/debug/values-v26/values-v26.xml:15:21-54: AAPT: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.

/Users/chuck/Code/fblogin/android/app/build/intermediates/res/merged/debug/values-v24/values-v24.xml:3: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.

/Users/chuck/Code/fblogin/android/app/build/intermediates/res/merged/debug/values-v24/values-v24.xml:4: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.

/Users/chuck/Code/fblogin/android/app/build/intermediates/res/merged/debug/values-v26/values-v26.xml:15: error: Error: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.


then in **app/build.gradle** I changed to
compileSdkVersion 26
buildToolsVersion "26.0.1"

defaultConfig {
    ...
    targetSdkVersion 26
}

And then It works on android now :)

**Comment by heralight** [comment]
@chuckcwh if you upgrade compileSdkVersion and buildToolsVersion, you don't need to 
force 'com.facebook.android:facebook-android-sdk:4.28.0' ...

**Comment by grocco** [comment]
Just changing compileSdkVersion, buildToolsVersion and targetSdkVersion to 26, "26.0.1" and 26 respectively in app/build.gradle solved it for me. Thanks @heralight and @chuckcwh !

**Comment by sfratini** [comment]
Just a comment. Using API 26 is breaking the Dev Menu in Android 8, because of a change in permissions with the overlay. Just blindily putting a greater compileVersion is not that good idea.

**Comment by SalviShahzad** [comment]
I followed all the steps by @chuckcwh but still my app is crashing in debug

**Comment by peferb** [comment]
So to get FB-login working in react-native you have to up target and compile sdk to 26? Which isnt supported by react native?

So not to risk breaking anything i have to use a old version of fbsdk targeting sdk 23?
