### ISSUE TITLE
iOS build of the `react-native init` generated template fails

### ISSUE THREAD

**Issue by maephisto** [facebook/react-native#17148]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 6.10.3
  Yarn: 0.24.5
  npm: 3.10.10
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.51.0 => 0.51.0

### Steps to Reproduce
The default getting started steps over at [React Native Getting Started](https://facebook.github.io/react-native/docs/getting-started.html)

1. npm install -g react-native-cli
2. react-native init AwesomeProject
3. cd AwesomeProject
4. react-native run-ios

### Expected Behavior

According to the [docs](https://facebook.github.io/react-native/docs/getting-started.html) the project should build and the load in the iOS simulator.

### Actual Behavior

The build process fails with the following message

```
[...]
▸ Building library libfishhook.a
▸ Building RCTWebSocket/RCTWebSocket [Debug]
▸ Check Dependencies

❌  /Users/xxx/Personal/test/AwesomeProject/node_modules/react-native/Libraries/WebSocket/RCTWebSocketModule.h:10:9: 'React/RCTEventEmitter.h' file not found

#import <React/RCTEventEmitter.h>
  ^       ~



❌  /Users/xxx/Personal/test/AwesomeProject/node_modules/react-native/Libraries/WebSocket/RCTReconnectingWebSocket.h:10:9: 'React/RCTDefines.h' file not found

#import <React/RCTDefines.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~



❌  /Users/xxx/Personal/test/AwesomeProject/node_modules/react-native/Libraries/WebSocket/RCTWebSocketExecutor.h:10:9: 'React/RCTDefines.h' file not found

#import <React/RCTDefines.h>
        ^~~~~~~~~~~~~~~~~~~~


** BUILD FAILED **



The following commands produced analyzer issues:
	Analyze /Users/xxx/Personal/test/AwesomeProject/node_modules/react-native/ReactCommon/yoga/yoga/YGNodeList.c
	Analyze /Users/xxx/Personal/test/AwesomeProject/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.c
	Analyze Base/RCTModuleMethod.mm
(3 commands with analyzer issues)

The following build commands failed:
	CompileC build/RCTWebSocket.build/Debug-iphonesimulator/RCTWebSocket.build/Objects-normal/x86_64/RCTWebSocketExecutor.o RCTWebSocketExecutor.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/AwesomeProject.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/AwesomeProject.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
```

### Reproducible Demo

Since this a setup & build issue, a demo cannot be attached. But the issue is reproducible in the environment config presented above.

**Comment by jasdeepsingh** [comment]
i can attest i'm having this same issue.
