### ISSUE TITLE
[FlatList] Android rendered with white patch,Ios nothing.

### ISSUE THREAD

**Issue by RyanRong** [facebook/react-native#17153]
### Is this a bug report?

(write your answer here)
NO

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.)
YES
### Environment
  Environment:
  OS: macOS High Sierra 10.13.2
  Node: 7.0.0
  Yarn: Not Found
  npm: 5.5.1
  Watchman: 4.7.0
  Xcode: Xcode 9.0.1 Build version 9A1004
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0-alpha.6=> 16.0.0-alpha.6
  react-native:0.44.3 =>0.44.3

  Target Platform: Android (5.0.0)

### Steps to Reproduce

(Write your steps here:)
I have a flatlist inside the ScrollView, I set up numberOfRow = {3}, and then I when rendering to a problem, the Android rendering some Item after a white patch, but did not appear this problem in the ios.

```
 <ScrollView
                    refreshControl={
                                <RefreshControl
                                    refreshing={this.state.isRefreshing}
                                    onRefresh={this._onRefresh.bind(this)}
                                     tintColor="#192c4d"
                                     title="玩命加载中......."
                                     titleColor={'red'}
                                 />}
                    onScroll={this._onScroll.bind(this)}
                    style={{ flex: 1, backgroundColor:'white',marginTop:-20}}>
                    {this.renderHeader()}
                    <View style={{ flex: 1}}>
                        <JiuProList
                            key={(this.state.horizontal ? 'h' : 'v')}
                            ref={this.listRef.bind(this)}
                            renderItem={this.renderItem.bind(this)}
                            itemHeight={PIC_ITEM_HEIGHT}
                            renderHeader={this.state.awardHeader&&this.state.awardHeader.isReceive==0?this.renderListHeader.bind(this):undefined}
                            numberOfRow={(this.state.horizontal ? 3 : 1)}
                            onRefresh={this.onRefresh.bind(this)}
                            onEndReached={this.onInfinite.bind(this)}
                            initialNumToRender={18}
                            removeClippedSubviews={false}
                        >
                        </JiuProList>


                    </View>
               
                </ScrollView>
```

### Expected Behavior

(Write what you thought would happen.)
no white patch.
### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by RyanRong** [comment]
![wechatimg3285](https://user-images.githubusercontent.com/11749548/33866378-57eb1ba2-df31-11e7-8121-793718e78e65.jpeg)

**Comment by RyanRong** [comment]
![default](https://user-images.githubusercontent.com/11749548/33866836-e6ea9cd6-df33-11e7-87c1-b02c230a3264.gif)

**Comment by jmahatpure01** [comment]
By white patch are you referring to the unloaded image??

**Comment by RyanRong** [comment]
@jmahatpure01 yes,I think item unloaded image

**Comment by jmahatpure01** [comment]
Then, I don't think there is a problem, its just taking more time to load.

**Comment by RyanRong** [comment]
@jmahatpure01 I don't think so, I've been waiting for a long time is still not load up pictures.

**Comment by arcollector** [comment]
try in a real devices, i have encounter the same problem when i use genymotion, in real devices loading images wroks fine

**Comment by RyanRong** [comment]
@arcollector i have tried,but still is the same problem.

**Comment by lishoulong** [comment]
I also encounter this problem, @RyanRong , do you solve this problem?

**Comment by RyanRong** [comment]
@lishoulong 这个问题,我也没解决,也没查出来是什么原因.
如果你解决了,请你告诉我一声.

**Comment by lishoulong** [comment]
@RyanRong ,我的出现空白是因为getItemLayout导致的，后来把getItemLayout就没有这个问题了。

**Comment by mujavidb** [comment]
Can confirm I have this issue on `0.54.2`.
