### ISSUE TITLE
displayName is missing on React components

### ISSUE THREAD

**Issue by frantic** [facebook/react-native#1715]
Seems like `displayName` is not attached to React components created with `React.createClass`. Looking... 

Meanwhile maybe @sebmck knows what's going on?

![image](https://cloud.githubusercontent.com/assets/192222/8294922/b7ddf4a4-18f4-11e5-8152-e40c23feb2fc.png)

**Comment by sebmck** [comment]
It'd be due to babel/babel#1761 which split up the `react` transformer into `react` and `react.displayName` to fix precedence issues with the `displayName` insertion. Adding `react.displayName` to the `whitelist` should fix this.

**Comment by frantic** [comment]
Awesome, thanks!

**Comment by frantic** [comment]
Chatted with @amasad - adding `react.displayName` is trivial in open-source repo, however we'll need to update internal version first.

**Comment by wzup** [comment]
@kittens , what _whitelist_ do you mean? How can we do it?
> _Adding `react.displayName` to the whitelist should fix this._
