### ISSUE TITLE
Unexpected keyword 'const'.

### ISSUE THREAD

**Issue by hoanglinh2k7** [facebook/react-native#17156]
### Is this a bug report? 
Yes, this is a bug report. When i reinstall node_module, then i re-run app by `react-native run-android`. I found this issue. I re-run with debug mode, app will work. When I run app without debug mode, app won't work.

![screenshot_20171212-131238](https://user-images.githubusercontent.com/33474102/33871062-5f1b114a-df43-11e7-8971-7d838afc1284.png)

### Environment

  Environment:
  OS: macOS High Sierra 10.13.2
  Node: 9.2.1
  Yarn: 1.3.2
  npm: 5.5.1
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: 0.48.4 => 0.48.4

**Comment by charpeni** [comment]
@facebook-github-bot needs-repro

**Comment by hoanglinh2k7** [comment]
Oh, I found the reason. I use the lib victory-native so it cause this issue

**Comment by darkrift** [comment]
@imcodervn How did you solve this ?

**Comment by dairdr** [comment]
I have this issue too

**Comment by dairdr** [comment]
I ran a new fresh project using "react-native": "0.52.0"
