### ISSUE TITLE
CSS Grid Layout Supporting?

### ISSUE THREAD

**Issue by amorenew** [facebook/react-native#17150]
### Is this a bug report?
No, Information request

I heard about CSS Grid Layout "Display: grid" So I wonder if React Native will support it?

Thanks

**Comment by lwinkyawmyat** [comment]
@facebook-github-bot no-template

**Comment by amorenew** [comment]
I found that it is a feature request so I added to requests here
https://react-native.canny.io/feature-requests/p/css-grid-layout-supporting
