### ISSUE TITLE
Initial create-react-native-app and run fails with `Failed building JavaScript bundle`

### ISSUE THREAD

**Issue by hahahatrick** [facebook/react-native#17159]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?
Yes

### Environment
    OS:  0SX 10.9.5
    Node:  8.9.3
    Yarn:  1.3.2
    npm:  5.6.0
    Watchman:  4.9.0
    Android Studio:  2.3

### Steps to Reproduce

1. ```create-react-native-app CRNA```
2. ```yarn run android```

### Expected Behavior
Should have got a working app on expo.

### Actual Behavior

Only error line ```Failed building JavaScript bundle```
### Reproducible Demo
I'm a beginner with React native, I never did any modifications to the app files.

**Comment by brentvatne** [comment]
Please post to https://github.com/react-community/create-react-native-app/issues
