### ISSUE TITLE
React Native - ScrollView - Disallow a component to go above screen during scrolling.

### ISSUE THREAD

**Issue by prasang7** [facebook/react-native#17168]
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

yes

### Environment

Environment:
OS: macOS Sierra 10.12.6
Node: 6.11.0
Yarn: 1.0.2
npm: 5.3.0
Watchman: 4.9.0
Xcode: Xcode 9.0 Build version 9A235
Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
react: 16.0.0-alpha.12 => 16.0.0-alpha.12
react-native: 0.48.2 => 0.48.2

### Steps to Reproduce

Code Structure: 

```
<ScrollView>
    <MyComponent />
</ ScrollView>
```
### Expected Behavior

I have a parent scrollview. And few components inside it. I want one specific component 'MyComponent' to not exit the phone's screen window when scrolling up.

### Actual Behavior

I want one of my component nested inside ScrollView to never cross the physical screen.
eg:
This is the normal screen:
<img width="285" alt="123" src="https://user-images.githubusercontent.com/13434598/33921954-598435cc-dfed-11e7-924e-c9bc6b19b0f3.png">

It should stop scrolling up when the MyComponent hits top of the screen. Like this:
<img width="285" alt="123 copy" src="https://user-images.githubusercontent.com/13434598/33921958-6509709c-dfed-11e7-8df9-a1c10d7d4eba.png">

### Reproducible Demo

There is no reproducible demo.

**Comment by moooji** [comment]
This is not a bug IMHO. If I understand you correctly, you would like to be able to switch of the elasticity of the scroll viewer? On iOS you can try if the `bounce` property does what you are looking for. https://facebook.github.io/react-native/docs/scrollview.html#bounces

**Comment by moooji** [comment]
Or maybe you mean something like this? http://rawgit.com/captivationsoftware/react-sticky/master/examples/basic/index.html

**Comment by bolan9999** [comment]
use stickyHeaderIndices, but it needs the top monotonous increasing. And you can not move it. 
if stickyHeaderIndices can not suit your requirements.
This is maybe an example for you. It implements with ScrollView

https://github.com/bolan9999/react-native-largelist
