### ISSUE TITLE
Cannot clear data with AsyncStorage

### ISSUE THREAD

**Issue by tirrorex** [facebook/react-native#17160]
The implementation is straightforward, calling clear with await.
But the data is not deleted even is the app is unistalled ???

>   async clearStorage() {
    try {
      await AsyncStorage.clear();
    } catch (error) {
    }
  }

Any workaround for this?

**Comment by tirrorex** [comment]
Are you kidding me ?

**Comment by tirrorex** [comment]
@harshrajk probably but no idea how, sorry mate

**Comment by ryanlntn** [comment]
I'm seeing this after updating to 0.57. I'm just working around it by manually resetting all my data but it's odd that it fails without giving back any error.

**Comment by alubeck** [comment]
Same here. I'm used to clear my storage with console in the react native debugger via ```require('AsyncStorage').clear()``` ... now the console tells me that require is not defined ?! what?
