### ISSUE TITLE
Fail to build app Release

### ISSUE THREAD

**Issue by raphcadiz** [facebook/react-native#17164]
Hi, I've jumping through different threads on solutions to solve the issue I have but I got no luck and so I wonder maybe somebody can help on this. I updated my app and my Android Studio as then suddenly it just stop building app for release. I wonder what's wrong. This the content of my build.grade

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}
```

When I run `./gradlew assembleRelease` I get this error 

FAILURE: Build failed with an exception.

```
* What went wrong:
Execution failed for task ':app:processReleaseResources'.
> Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 56s
66 actionable tasks: 57 executed, 9 up-to-date
```

Thanks for the help!

**Comment by andylidong** [comment]
Have you solved it？I have the same problem.
Maybe you can change " classpath 'com.android.tools.build:gradle:3.0.1'"
to classpath 'com.android.tools.build:gradle:2.2.3',

**Comment by yvkschaefer** [comment]
@andylidong I'm not  sure if you're still having the problem but https://github.com/facebook/react-native/issues/16906 seems to reference this and there is a PR open .... hoping there will be a fix soon!
