### ISSUE TITLE
Unsupported top level event type "topScroll" dispatched. only on android . react-native 0.50.0

### ISSUE THREAD

**Issue by anhdbknws** [facebook/react-native#17175]
### Is this a bug report?

(write your answer here)

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.)

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by lwinkyawmyat** [comment]
@facebook-github-bot needs-repro

**Comment by anhdbknws** [comment]
when i try to use “react-native-pages”.

ios worked normally.
android occur this issue

**Comment by anhdbknws** [comment]
and this bug occur in react-native version 0.50

**Comment by manidlou** [comment]
Same here! Issue occurs only on Android!

**Comment by anhdbknws** [comment]
this bug was fixed on React version 0.52

**Comment by lwinkyawmyat** [comment]
@facebook-github-bot label Needs more information
