### ISSUE TITLE
Facebook login doesn't work as expected, keeps loading

### ISSUE THREAD

**Issue by wyvasi** [facebook/react-native#17174]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.)
Yes
### Environment

Environment:
  OS: Windows 10
  Node: 7.10.0
  Yarn: Not Found
  npm: 4.6.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.0.0.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.50.3 => 0.50.3

  Target Platform: Android (7.0) HUAWEI P9 lite

### Steps to Reproduce

1. create-react-native-app test 
2. cd test
3. npm run android
4. changed App.js with https://gist.github.com/wyvasi/b0193c4658c81a30df05ad0faab263e9 (YES I USED MY APP ID, 2 of them)

### Expected Behavior

Each time should login or at least throw an error in case something is wrong.

(Write what you thought would happen.)

### Actual Behavior

When  I create new app the first login works. After that I keep getting this https://imgur.com/1fouDEB
https://user-images.githubusercontent.com/4634020/33923038-6d248d5e-dfd7-11e7-876c-a780ef654ee2.png
(Write what happened. Add screenshots!)

### Reproducible Demo

https://snack.expo.io/Sk-ykvCbG

**Comment by wyvasi** [comment]
tried same app on another device  Android 6.0.1 and is woking as I expected to work. Not sure what I should do with my device...

**Comment by wyvasi** [comment]
up

**Comment by ArsenyYankovsky** [comment]
This affects both iOS and Android for me.

**Comment by wyvasi** [comment]
This was a problem with facebook app.

**Comment by Ejyption** [comment]
Works if you don't have facebook app installed. uninstalled facebook app and it works

**Comment by Tahriff** [comment]
Any work around on how to make it work even if the Facebook app is installed ?

**Comment by rafaelsales** [comment]
I'm getting this issue on android emulator without facebook installed.
