### ISSUE TITLE
React-Native website search bar does not work as expected

### ISSUE THREAD

**Issue by ravirajn22** [facebook/react-native#17176]
### Is this a bug report?

Yes 

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

yes

### Environment

 Environment:
    OS:  macOS Sierra 10.12.6
    Node:  6.11.0
    Yarn:  1.3.2
    npm:  5.4.2
    Watchman:  4.7.0
    Xcode:  Xcode 8.3.3 Build version 8E3004b
    Android Studio:  2.3 AI-162.4069837
    Chrome - 63.0.3239.84
    Firefox - 57.0

 Packages: (wanted => installed)
    react-native: 0.48.1 => 0.48.1
    react: 16.0.0-alpha.12 => 16.0.0-alpha.12

 Target Platform: iOS (10.3)

### Steps to Reproduce

(Write your steps here:)

1. Open Website https://facebook.github.io/react-native/
2. Search for Switch component using the search bar
3. Modal drop down appears with appropriate search results
4. Select Switch component
5. Inside Switch component docs, search for Button component. 
6. Nothing happens.

But,
7. Go back again to home page i.e https://facebook.github.io/react-native/
8. Search for Button, it shows all search results again.

### Expected Behavior

When you search for Button component inside Switch Component docs, a Modal dropdown must appear with all the search results

(Write what you thought would happen.)

### Actual Behavior

Nothing happens! the search bar does nothing.

(Write what happened. Add screenshots!)

![bug](https://user-images.githubusercontent.com/10977864/33930837-3a8e613e-e014-11e7-8a90-136e29783c0b.gif)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by lwinkyawmyat** [comment]
Hi, Can you re-create this issue at [here](https://github.com/facebook/react-native-website/issues/new)?

**Comment by lwinkyawmyat** [comment]
@facebook-github-bot close
