### ISSUE TITLE
[Error] imports[0] for react-transform-hmr does not look like React

### ISSUE THREAD

**Issue by connectkushal** [facebook/react-native#17192]
### Is this a bug report?

Yes

It is the same as #17112 but on an android device and since that was closed without a proper solution, creating another issue. On following the basic installation process and running `native-react run-android` I got this error on 3 different devices, 
```
imports[0] for react-transform-hmr does not look like React
```
Tried it on two devices with latest android connected via usb and on an emulated android 6

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: Linux 4.4
  Node: 7.4.0
  Yarn: 0.27.5
  npm: 5.5.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.51.0 => 0.51.0

  Target Platform: Android (marshmallow)

### Steps to Reproduce

(Write your steps here:)

1. Install react-native and android sdk as per official documents
2. create new project with `react-native init TestProject`
3. start android 6 on emulator or connect to device (ive tried both and got the same result)
4. run `react-native run-android` from the project directory

### Expected Behavior

To see the bare project landing page

### Actual Behavior

![image](https://user-images.githubusercontent.com/19621775/33970519-8a84bb9a-e099-11e7-8c39-3b0111e8c450.png)

### Reproducible Demo

Just follow the steps to reproduce without changing anything

**Comment by c-fitzmaurice** [comment]
Seeing the same thing for iOS on Mac, in the last hour.

**Comment by Elindorath** [comment]
Same here on iOS Simulator.

**Comment by SY102134** [comment]
Same here on android.
react: 16.2.0
react-native: 0.53.0

**Comment by yinchuanjiang** [comment]
How do you solve this problem? I'm using 0.55.3 and this is wrong.

**Comment by connectkushal** [comment]
@yinchuanjiang i have switched to using flutter which has far better docs and a more responsive community.
