### ISSUE TITLE
Not able to build a basic file

### ISSUE THREAD

**Issue by shardy315** [facebook/react-native#17208]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Steps to Reproduce

(Write your steps here:)

1. Created a basic react-native project 
2. Changed the App.js as per below
3. Got an error

### Expected Behavior

The text to be displayed on the screen
### Actual Behavior

Got an error as per below

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

> Invariant Violation: Element type is invalid: expected a string (for built-in components) but got : object. You likely forgot to export your component from the file it's defined in.
> 
> The error is located at :
> in RCTView (at View.js:112)
> in View (at AppContainer.js:102)
> in RCTView (at View.js:112)
> in View (at AppContainer.js:122)
> in AppContainer (at renderApplication.js: 34)

Here is a screenshot : 

https://image.ibb.co/b8EK4m/Screen_Shot_2017_12_14_at_16_27_33.png

My App.js is like this. Not sure what I am doing wrong here. Would be grateful for any pointers. Thank you :)

```
import React from 'react';
import { AppRegistry, View, Text } from 'react-native';

class App extends React.Component {
  render(){
    return (
      <View>
        <Text> Sierra </Text>
        <Text> Tanner </Text>
      </View>
    )
  }
}

AppRegistry.registerComponent('SampleApp', () => App);

```

**Comment by moooji** [comment]
Does it work with the original (unchanged) App.js?

**Comment by shardy315** [comment]
Hi @moooji ,

Yes it does. I deleted all of the contents of the original and wrote the above to see what is happening.

**Comment by moooji** [comment]
OK, how about the `index.js`? When you create a new project with `react-native init` you will get an `index.js` which looks like this:

```
import { AppRegistry } from "react-native";
import App from "./App";

AppRegistry.registerComponent("SampleApp", () => App);
```

So the `index.js` is the entry point and imports `App.js`. It looks like you have somehow merged them together?

**Comment by shardy315** [comment]
I didn't change that file and it looks exactly the same as above : 

```
import { AppRegistry } from 'react-native';
import App from './App';

AppRegistry.registerComponent('SampleApp', () => App);

```

**Comment by moooji** [comment]
OK, in that case your App.js should for example not include `AppRegistry.registerComponent('SampleApp', () => App);`. That is only needed in `index.js`.

A very simple `App.js` could look like this:
```
import React, { Component } from "react";

import {
  Platform,
  Text,
  View,
} from "react-native";

class App extends Component {
  render() {
    return (
      <View>
        <Text>Sample App</Text>
      </View>
    );
  }
}

export default App;
```

**Comment by shardy315** [comment]
Thank you @moooji  and the above now seems to work :) .

Just so I can understand, how did you know that `AppRegistry.registerComponent('SampleApp', () => App);` is only needed in` index.js` ? 

https://facebook.github.io/react-native/docs/tutorial.html has it in `App.js` and so does Lynda.com where I am following the tutorial from.

Where would you say is a good place to learn RN step by step from ?

Thank you.
