### ISSUE TITLE
[Keyboard] Idiomatic way of handling keyboard obscuring the screen.

### ISSUE THREAD

**Issue by admmasters** [facebook/react-native#1720]
I think it would be wise if we had some kind of idiomatic way of handling situations where the keyboard covers the screen when entering text in a textinput. At present we have no way to handle this outside of  hacks which work to varying degrees but add a lot of boilerplate and aren't nice to implement and jar from a UX perspective. Apologies if something like this already exists - but this is a fairly common scenario on apps that have form components etc.

**Comment by brentvatne** [comment]
@adamjernst - have you tried https://github.com/johanneslumpe/react-native-keyboardevents ?

I think it would be useful to have a "Recipes" type site that deals with these sorts of common topics, any interest in starting one? ;)

**Comment by jawadrehman** [comment]
@brentvatne The experience is a bit janky ?  Is there a way to sync the animation of the keyboard and the movement of the form.

**Comment by ide** [comment]
There's no built-in way. You could replicate the same bezier curve that Apple uses, or write a bit of native code to animate the view.

**Comment by jtremback** [comment]
I see a lot of native apps that do fine with this- does anyone know what they are doing?

**Comment by admmasters** [comment]
@brentvatne - the experience is indeed not very nice and seems a little bit hacky - having worked with native keyboard handling I've seen the multitude of issues that people come up against when trying to write this kind of code. I've even seen production apps where the attempts to move the screen to cope with the keyboard appearing have resulted in fails. For pure native iOS there are libraries like this one:  https://github.com/hackiftekhar/IQKeyboardManager - without really delving deeply into the issue it would be nice to be able to have this sort of functionality built into React Native as we are going to end up having to write lots of boilerplate specific to iOS as Android has much better methods out of the box of handling this sort of scenario: http://stackoverflow.com/questions/3295672/android-soft-keyboard-covers-edittext-field

**Comment by admmasters** [comment]
I'd imagine we could base something off: https://github.com/johanneslumpe/react-native-keyboardevents - but absolutely animation would be necessary, to achieve the native experience that I'm sure drew the majority of the developers using it to React-Native. Would be absolutely essential to recreate that Apple Bezier curve animation and it would be nice - not to have to jump into native code. Just having the discussion I guess at this stage.

**Comment by grabbou** [comment]
I am doing this kind of stuff in my app currently. The way we've approached this is we use react-native-keyboardevents in a custom mixin `TrackKeyboard` that basically updates `state` of the component with the current height of the keyboard (which is either 0 when keyboard is off or != 0 when keyboard is on). Then I have a paddingTop value that I change by subtracting keyboardHeight from initial value. I also set LayoutAnimation before that change happens so the whole e.g. modal animates to the top when the keyboard is being opened.

**Comment by admmasters** [comment]
Thanks - had a play around with it, looks good - the issues with some of the approaches like this are that the best implementations on iOS only move the keyboard up when necessary as oppose to all the time, for instance opening a textfield at the top of the page should not move the frame up etc. Interestingly - IQKeyboardManager seems to work well with React Native now, might be worth a look for an out of the box solution for iOS. Would prefer if we had a purely native solution though, frankly. :-)

**Comment by fov42550564** [comment]
use https://github.com/remobile/react-native-smart-keyboard
