### ISSUE TITLE
Yarn install throws an error

### ISSUE THREAD

**Issue by prasadsampath** [facebook/react-native#17215]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Steps to Reproduce

(Write your steps here:)

1. react-native init <project>
2. cd <project>
3. yarn install

### Expected Behavior

Packages to get installed correctly.

### Actual Behavior

Throws below error:

\node_modules\core-js\modules\_enum-bug-keys.js:3
  'constructor,hasOwnProperty,isPrototypeOf,propertyIsEnumerable,toLocaleString
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Invalid or unexpected token
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by rsnara** [comment]
What version of yarn and node are you using?

Also, this seems like a parsing error. Could it be that the string `'constructor,hasOwnProperty,isPrototypeOf,propertyIsEnumerable,toLocaleString` doesn't have an ending quotation mark?

**Comment by prasadsampath** [comment]
Yarn : 0.27.5
Node: 6.11.0

I'm not sure what's the problem, but this only happens when i started a fresh project. I replaced coreJS from my older project and it works okay.
