### ISSUE TITLE
ReOpening android app is cached

### ISSUE THREAD

**Issue by nschurmann** [facebook/react-native#17211]
### Is this a bug report?

Yes

### Environment

Environment:
  OS: macOS High Sierra 10.13.1
  Node: 8.5.0
  Yarn: 1.3.2
  npm: 5.3.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0-alpha.12 => 16.0.0
  react-native: ^0.47.1 => 0.51.0

  Target Platform: Android (8)

### Steps to Reproduce

(Write your steps here:)

1. Install the app
2. Open the app
3. Navigate somewhere like 'products'
4. Close the app
5. Open the app
6. The app will be in 'products' instead af the main scene

### Expected Behavior

1. Install the app
2. Open the app
3. Navigate somewhere like 'products'
4. Close the app
5. Open the app
6. The app will be in 'index'

Super easy and replicable steps 😄

**Comment by Jerameel** [comment]
This is not possible unless you are saving the state.

**Comment by nschurmann** [comment]
@Jerameel this is the default behaviour in android prior to 7...

**Comment by Jerameel** [comment]
If you close the app without actually removing it in the "recent apps" it would probably resume its last state as long as android has enough memory to sustain it. This is the default behavior for all android versions.

**Comment by nschurmann** [comment]
@Jerameel that's the case i'm referring, close the app and remove it from "recent apps", or android multitasking.
