### ISSUE TITLE
License update

### ISSUE THREAD

**Issue by l1x** [facebook/react-native#17228]
Hi,

I was wondering when/if the license will follow React's (removing PATENTS) and moving over to MIT. 

Sorry for using the issue system for this.

Thanks,
Istvan

**Comment by gaearon** [comment]
React Native (including Metro, Fresco, and Yoga) has also been relicensed as MIT.

https://github.com/facebook/react-native/commit/26684cf3adf4094eb6c405d345a75bf8c7c0bf88
