### ISSUE TITLE
Optional function in getDefaultProps doesn't get into props 

### ISSUE THREAD

**Issue by mosch** [facebook/react-native#1723]
A component with an optional function passed in as a prop and a fallback for that function defined in getDefaultProps.

However, the function defined in getDefaultProps doesn't make it to the props if you don't pass one in.

__Example:__ https://rnplay.org/apps/8tCMcA/

*I played around with this for a long time, maybe I just don't get what i'm doing wrong.*

**Comment by brentvatne** [comment]
@mosch - check this out: https://facebook.github.io/react/docs/reusable-components.html#default-prop-values

> The result of getDefaultProps() will be cached and used to ensure that this.props.value will have a value if it was not specified by the parent component. This allows you to safely just use your props without having to write repetitive and fragile code to handle that yourself.

Add this to `getDefaultProps` and behold: `React.AlertIOS.alert(Object.keys(this).toString());`

`this` is the 'class' not an instance, so you need to add that function to statics:
```
  statics: {
    getDefaultText() { return "Default" }
  },
```

That will fix your issue!

See here: https://rnplay.org/apps/J7su3w
