### ISSUE TITLE
Changing TextInput keyboardType from visible-password does not unset the underlying flags (Android)

### ISSUE THREAD

**Issue by BrandonWilliamsCS** [facebook/react-native#17248]
### Is this a bug report?

Yes.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes.

### Environment

Environment:
  OS: macOS High Sierra 10.13.2
  Node: 9.2.0
  Yarn: 1.3.2
  npm: 5.5.1
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: facebook/react-native#master => 1000.0.0
(react-native built from master branch on 2017-12-17)

Target Platform: Android 8.x
Tested specifically on Nexus 5x, api level 27

### Steps to Reproduce

1. Create a TextInput with `secureTextEntry` set and a `keyboardType` of `null`, `undefined`, or `'default'`
2. Change the `keyboardType` to `'visible-password'`
3. Change the `keyboardType` back to `'default'`

### Expected Behavior

The field would initially be an obscured password field, then become unobscured, then become obscured again when no longer of type `'visible-password'`.
Additionally, the soft keyboard variant stays in "password" mode (e.g., no suggestions) in each case due to `secureTextEntry`.

### Actual Behavior

After set to `'visible-password'`, the field remains unobscured even after switching to a different type.
However, when not obscured, the soft keyboard falls returns to a plain text keyboard with suggestions instead of numbers on the top row (may vary by device).

### Reproducible Demo

I believe this branch should exhibit the bug out-of-the-box (after installing packages and building):
https://github.com/BrandonWilliamsCS/react-native-test-harness/tree/fix/android-textfield-keyboardtype-flags

Once running on an Android device or emulator, tap the field so that the soft keyboard appears and enter text into the field. This will trigger a state change that toggles between `'visible-password'` and `'default'`.

**Comment by hanspoo** [comment]
Same problem here with: 

    "react": "16.3.0-alpha.1",
    "react-native": "0.54.0"

The use of a keyboardType email-address disables secureTextEntry.
