### ISSUE TITLE
Back Handler: repeating one screens functionality in other screen

### ISSUE THREAD

**Issue by vigneshwarrao** [facebook/react-native#17241]
### Is this a bug report?

I hope it is bug, if my functionality is fine.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Steps to Reproduce

(Write your steps here:)

1. We have implemented back handler in our app.
2. Suppose two screens from all screens, Products list and Selected Product Description.
3. In product list we placed sign out confirmation on clicking of back handler, where as in Product description we just kept back handler disabled.
4. So, we are getting sign out confirmation even on the Product description screen, where it should only restrict going back.
The code we used is:

componentDidMount() {
        const nav = this.props.navigation;
        BackHandler.addEventListener('hardwareBackPress', function () {
            this.setState({logoutModalBool:true});
            return true;
        });
    }
    componentWillUnmount(){
        BackHandler.removeEventListener('hardwareBackPress', function(){
            self.setState({logoutModalBool:false});
            return true;
        });
    }

### Expected Behavior
It should be not show popup confirmation in Product description because it is already removed in componentWillUnmount.

**Comment by jmahatpure01** [comment]
Did you defined a BackHandler in your Product description screen also?

**Comment by jmahatpure01** [comment]
I faced similar issue. I found out that in StackNavigation the previous screen component is not unmounted, they are just buried under the new screen. So, BackHandler is not removed and you have to add BackHandler in your new screen for overwriting your previous screen BackHandler.

**Comment by sfm2222** [comment]
Can we use DrawerNavigator, StackNavigator and NavigatoriOS in the same project>

I'm developing a standard application in react native with a drawer and back button option for both android and iOS. Can I use the following combination, if no kindly suggest alternative:
DrawerNavigator - to show the side bar menu items in drawer.

Stack Navigator - to switch between screens for eg clicking on car will move to car detail page.

NavigatorIOS - to implement native iOS back button.Drawer Navigator

Also this.props.navigation.goback() takes back to the first screen that is home not to the last visited screen, how we can resolve that?

**Comment by vigneshwarrao** [comment]
jmahatpure01: Hi, sorry for late reply. Yes we defined in product description also., but it is not overwriting the previous one.

**Comment by vigneshwarrao** [comment]
sfm2222: Hi, we haven't tried Navigator IOS but you can use DrawerNavigator inside Stack Navigator.
coming to this.props.navigation.goBack() : back "B" should be uppercase. Just try again let me know.
