### ISSUE TITLE
Red screen error on emulator and real devices

### ISSUE THREAD

**Issue by suhailjain** [facebook/react-native#17245]
### Is this a bug report?

YES

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

YES

### Environment

Environment:
  OS: Windows 10
  Node: 8.9.1
  Yarn: Not Found
  npm: 5.5.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.0.0.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.51.0 => 0.51.0

target device : android api 24

### Steps to Reproduce

1. ran app with 'react-native run-android'
2. both emulator and the real device fail to load the app displaying a red screen even though there is no error in the node package manager and also in the code as per Atom IDE which is use having linter and eslint packages installed.

### Expected Behavior

app should work fine without any red screen errors

### Actual Behavior
![error](https://user-images.githubusercontent.com/16290101/34077543-92389b78-e32c-11e7-948c-5e53b8e7a808.jpg)

### Reproducible Demo

attached are screenshots of all my JS files.

![albumdetailsjs](https://user-images.githubusercontent.com/16290101/34077559-fc3ea92c-e32c-11e7-8e94-32b25554def9.jpg)
![albumlistjs](https://user-images.githubusercontent.com/16290101/34077560-fc9f01aa-e32c-11e7-9328-01e711042c07.jpg)
![cardjs](https://user-images.githubusercontent.com/16290101/34077561-fcd3d5ec-e32c-11e7-937f-1c2966d9cfa2.jpg)
![headerjs](https://user-images.githubusercontent.com/16290101/34077562-fd0819c4-e32c-11e7-8862-5ff437ff9bbc.jpg)
![indexjs](https://user-images.githubusercontent.com/16290101/34077563-fd3f219e-e32c-11e7-81fc-a0e97de17191.jpg)

**Comment by jmahatpure01** [comment]
These issues look similar: https://github.com/facebook/react-native/issues/13653
https://github.com/leecade/react-native-swiper/issues/618
