### ISSUE TITLE
[android] multiline TextInput in ScrollView

### ISSUE THREAD

**Issue by socar-dorma** [facebook/react-native#17256]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

  Environment:
    OS:  macOS Sierra 10.12.6
    Node:  8.1.2
    npm:  5.6.0
    Watchman:  4.7.0
    Xcode:  Xcode 9.2 Build version 9C40b
    Android Studio:  2.3 AI-162.4069837

  Packages: (wanted => installed)
    react-native: 0.51.0 => 0.51.0
    react: 16.2.0 => 16.2.0

  Target Platform: android

### Steps to Reproduce

(Write your steps here:)

* **This problem only occurs with android.**
1. Inside ScrollView component put TextInput components(`multiline=true` & fixed height)
2. ScrollView is a scrollable
3. Tap on one TextInput, keyboard will appear, type text with multiple newline.
4. When, overflow TextInput's height. The ScrollView scrolls down.

### Expected Behavior

The scroll of the ScrollView does not move.
Only TextInput should be scrolled.

### Actual Behavior
Each time you press Enter, the scroll of the ScrollView moves.
![multiline-textinput](https://user-images.githubusercontent.com/28700428/34100382-9574af76-e425-11e7-8c25-be21241d6918.gif)

### Reproducible Demo
https://snack.expo.io/BJLrxGrzf

**Comment by derakhshanfar** [comment]
do you try wrap your textinput on other scrollview with fixed height?

**Comment by socar-dorma** [comment]
@derakhshanfar don't work...
https://snack.expo.io/ry50lXSfM

**Comment by derakhshanfar** [comment]
@socar-dorma  when i see your expo on IOS, the textinput has scroll and its work like your expect!  what is wrong in your example?!

**Comment by socar-dorma** [comment]
@derakhshanfar see issues's title... `[android] multiline TextInput in ScrollView`
This problem only occurs with android.

**Comment by socar-dorma** [comment]
sorry. I found same issue.. #12799
