### ISSUE TITLE
ScrollView not scrolling to bottom 

### ISSUE THREAD

**Issue by nikolal** [facebook/react-native#17257]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: OS X El Capitan 10.11.6
  Node: 8.4.0
  Yarn: 1.3.2
  npm: 4.6.1
  Watchman: 4.7.0
  Xcode: Xcode 8.2.1 Build version 8C1002
  Android Studio: 2.2 AI-145.3537739

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: https://github.com/expo/react-native/archive/sdk-24.0.0.tar.gz => 0.51.0

### Steps to Reproduce

  1) Create a View with flex: 1 ( not sure if this step is necessary )
  2) Nest ScrollView inside
  3) Nest elements inside ScrollView to fill in screen height.
  4)  Set height: 30% ( or any other % value ) to one of those elements

### Expected Behavior

ScrollView should expand and allow scrolling to the bottom of the last element.

### Actual Behavior

ScrollView cuts the last elements depending of the height percentage of the child element.

### Reproducible Demo

https://snack.expo.io/B1Z7HMHfG

### Note

We are building dynamic app and we can't know in advanced what kind of styles will user set for components, or even what components will be created as a  ScrollView children or parent.

**Comment by Navidhp** [comment]
Hi i think you should use Dimensions for height , like this exmple
import {Dimensions } from 'react-native';
const height = Dimensions.get('window').height;
This feature allows you to have the height of the device ,If you want to get View height use onlayout on View tag

exmple : 
heightView(layout){
const {x, y, width, height} = layout;
let itemHeightPercent20 = height % 20
let itemHeightPercent30 = height % 30
}

render() {
<View style={{flex:1}} onLayout={(event)=>this.heightView(event.nativeEvent.layout)}>
   <ScrollView>
    <item style={{height : itemHeightPercent20 }} />
    <item style={{height : itemHeightPercent20 }} />
   </ScrollView>
</View>
}

**Comment by nikolal** [comment]
I solved this by wrapping ScrollView inside View, converting width and height percentage to number (logical pixels) and passing it to child components:

```
  handleLayout = e =>
    this.setState({
      scrollViewWidth: e.nativeEvent.layout.width,
      scrollViewHeight: e.nativeEvent.layout.height
    });
```

```
<View onLayout={this.handleLayout}>
    <ScrollView>
        <ChildComponent
            scrollViewWidth={this.state.scrollViewWidth}
            scrollViewHeight={this.state.scrollViewHeight}
       </ChildComponent>
    </ScrollView>
</View>
```

Then inside child components I am setting width and height:

```
  height: scrollViewHeight ? parseFloat(styles.height) / 100 * scrollViewHeight : styles.height,
  width: scrollViewWidth ? parseFloat(styles.width) / 100 * scrollViewHeight : styles.width,
```

**Comment by lixingdecai** [comment]
can not scroll to the bottom on the scrollview, is also happened to me .  i dont think set handleLayout is a good way. @nikolal are there any other solutions?

**Comment by aseelasi** [comment]
Im also facing the same problem i used style={{flex:1}} for parent, wrapped in a view etc but doesn't work properly actually i can't scroll to bottom,can only view the components in screen height only .when i scroll up it bounce back
