### ISSUE TITLE
Keyboard cannot be dismissed, if user taps on second TextInput component

### ISSUE THREAD

**Issue by magneticz** [facebook/react-native#17252]
### Is this a bug report?

Yes.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes.

### Environment
Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.7.0
  Yarn: 1.2.1
  npm: 5.4.2
  Watchman: 4.9.0
  Xcode: Xcode 9.0 Build version 9A235
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.51.0 => 0.51.0

### Steps to Reproduce

1. Inside ScrollView component put several TextInput components
2. Tap on one TextInput, keyboard will appear, tap on blank space, keyboard will disappear.
3. Tap on one TextInput, then tap on second TextInput, and then tap on blank space.

### Expected Behavior

Keyboard should be dismissed when pressed on blank space

### Actual Behavior

Keyboard persists if user has several TextInput components inside ScrollView and he taps on first and then second TextInput component. Keyboard persists, and it is correct behavior. 

However, now, when user presses on blank space, keyboard is not dismissed. It stays there until user presses any other TextInput, and then presses blank space.
![bug](https://user-images.githubusercontent.com/968005/34096287-fd869894-e3fe-11e7-958d-1545745a280d.gif)
### Reproducible Demo
Newly generated react-native app with ScrollView and several TextInput components
https://github.com/magneticz/AwesomeBug

**Comment by watanabeyu** [comment]
I solved this below.

```
<ScrollView keyboardShouldPersistTaps="never" style={{ flex: 1 }}>
  <TextInput
    ref={ref => this.input1 = ref}
    onFocus={() => this.input1.focus()}
    style={{ borderWidth: 1, borderColor: 'red', height: 50, margin: 10 }}
  />
  <TextInput
    ref={ref => this.input2 = ref}
    onFocus={() => this.input2.focus()}
    clearButtonMode="while-editing"
    style={{ borderWidth: 1, borderColor: 'red', height: 50, margin: 10 }}
  />
  <TextInput
    ref={ref => this.input3 = ref}
    onFocus={() => this.input3.focus()}
    clearButtonMode="while-editing"
    style={{ borderWidth: 1, borderColor: 'red', height: 50, margin: 10 }}
  />
</ScrollView>
```
Add `ref` and `onFocus`, and you have to explicitly call focus() on each onFocus.

https://snack.expo.io/B1Vcm-Lff

**Comment by magneticz** [comment]
it turns out, if `keyboardShouldPersistTaps="handled"` on `ScrollView` is used, it works just fine, no need for `ref` and `onFocus()`.
However, it is a strange behavior, not to dismiss keyboard only when second TextInput is pressed

**Comment by ltankey** [comment]
> it turns out, if keyboardShouldPersistTaps="handled" on ScrollView is used, it works just fine, no need for ref and onFocus().

If `keyboardShouldPersistTaps="never"`, surely attempting to select the second `TextInput` while focused on the first should result in the keyboard being dismissed?
