### ISSUE TITLE
Text Input the height does not automatically decrease.

### ISSUE THREAD

**Issue by gtauniverse** [facebook/react-native#17260]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

  Packages: (wanted => installed)
    react-native: 0.51.0 => 0.51.0
    react: 16.0.0 => 16.0.0

  Target Platform: android

### Steps to Reproduce

This problem only occurs with android.

```
<TextInput
 value={this.state.text}
 onChangeText={(text) => this.setState({text})}
 style={{flex: 1, height: 40}}

 multiline={true}
 autoGrow={true}
 maxHeight={80}
/>
```

### Expected Behavior 
The height of the component 'TextInput' automatically decreased when the number of rows decreased in it.

### Actual Behavior
<img src="http://i.yapx.ru/nUC4.gif" border="0">

**Comment by tss101** [comment]
Having the same issue

**Comment by arma7x** [comment]
Same for me

**Comment by albert-carreras** [comment]
any updates? this is still broken!

**Comment by arma7x** [comment]
[dabb78b](https://github.com/facebook/react-native/commit/dabb78b)
