### ISSUE TITLE
Is ART broken?

### ISSUE THREAD

**Issue by msageryd** [facebook/react-native#17272]
Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.6.0
  Yarn: 1.2.1
  npm: 5.3.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.50.3 => 0.50.3

I also tried RN 0.52 and React 16.2. Same error.

### Steps to Reproduce

Put this in your App.js in a new RN app.

    import React from 'react';
    import { View, ART } from 'react-native';
    const { Surface } = ART;

    export default class ArtTest extends React.Component {
      render() {
        return <Surface width={100} height={100} />;
      }
    }

`npm run ios`

### Expected Behavior

I expected no error. The example doesn't do much as it's stripped down to bare bones.

### Actual Behavior

![image](https://user-images.githubusercontent.com/4483085/34150467-b8c41db2-e4a8-11e7-8970-4e0987999d5c.png)

**Comment by msageryd** [comment]
I just realised that ART needs to be manually linked. Problem solved.

Sorry for bothering.

**Comment by Kielan** [comment]
Just want to mention in case anybody runs into this that ART and possibly all other core libraries that require native linking the project will need to be a workspace.
