### ISSUE TITLE
[Navigator] _popN does not update routeStack state

### ISSUE THREAD

**Issue by kyle-ssg** [facebook/react-native#1727]
The navigator keeps the routestack in state, this seems to be used by getCurrentRoutes. I noticed this gets updated on push but not pop/popN.

I'd expect a state update similar to the following: 
 this.setState({
      idStack: nextIDStack,
      routeStack: nextStack,
      sceneConfigStack: nextAnimationConfigStack,
      updatingRangeStart: nextStack.length - 1,
      updatingRangeLength: 1,
    });

**Comment by chirag04** [comment]
@ericvicenti

**Comment by chirag04** [comment]
I just did a small test can't get to replicate this though. Mind sharing a fiddle on rnplay?

**Comment by ericvicenti** [comment]
Agreed- a simplified example on RNPlay would be great to see

Currently, (and I agree that it's not ideal,) the Navigator will only remove the popped routes once the pop animation completes.

**Comment by brentvatne** [comment]
New Navigator is in progress, you can comment on it here: https://github.com/ericvicenti/navigation-rfc
