### ISSUE TITLE
Text shadow doesn't render when blur is set but offset is (0,0)

### ISSUE THREAD

**Issue by Firehed** [facebook/react-native#17277]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment
Environment:
  OS:  macOS High Sierra 10.13.1
  Node:  8.9.0
  Yarn:  1.3.2
  npm:  5.5.1
  Watchman:  4.9.0
  Xcode:  Xcode 9.0.1 Build version 9A1004
  Android Studio:  Not Found

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: ^0.49.3 => 0.49.5

### Steps to Reproduce

```jsx
<Text style={{
    textShadowOffset: { height: 0, width: 0 },
    textShadowColor: 'red',
    textShadowRadius: 3,
}}>This text should have a shadow</Text>
```

### Expected Behavior

Text should have a blurred shadow with no offset, similar to having `text-shadow: 0 0 3px red` in CSS.

### Actual Behavior

No shadow exists at all

### Reproducible Demo

https://snack.expo.io/B1X1Lzvff

### Other

At least on iOS, I think the issue is an overly-grabby conditional in [`Libraries/Text/RCTShadowText.m`](https://github.com/facebook/react-native/blob/6ad1f0957a020cb57b177ab015c17aa883e1f0ad/Libraries/Text/RCTShadowText.m#L467), something like `if (!CGSizeEqualToSize(_textShadowOffset, CGSizeZero) || _textShadowRadius != 0.0) {`. Not too sure about the build process so I can't easily test that fix locally. Plus it seems to occur on Android as well.

**Comment by mcmar** [comment]
@shergin @mdvacca @davidaurelio Can on of you please re-open this or otherwise respond? I can confirm the issue and it does not appear to be intended behavior. Compare to text-shadow prop on web browsers, where the following is perfectly valid and displays the intended behavior:
`text-shadow: 0 0 2px #FF0000;`
