### ISSUE TITLE
main.jsbundle does not exist. TransformError: Couldn't find preset "es2015"

### ISSUE THREAD

**Issue by clovs** [facebook/react-native#17288]
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

yes

### Environment
  OS: macOS High Sierra 10.13.2
  Node: 9.3.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.2.0 => 16.2.0
  react-native: ^0.50.3 => 0.50.4

### Steps to Reproduce

1. open .xcodeproj file
2. edit scheme -> select "release" build configuration
3. build & run in simulator

### Expected Behavior

The project should be successfully build and run in the simulator

### Actual Behavior

The project build failed

`node /Users/User/Documents/Code/Test/Test-app/node_modules/react-native/local-cli/cli.js bundle --entry-file index.js --platform ios --dev false --reset-cache --bundle-output '/Users/User/Library/Developer/Xcode/DerivedData/test-gqrafewypmcfwienuoudxkbrihal/Build/Intermediates.noindex/ArchiveIntermediates/test/BuildProductsPath/Release-iphoneos/test.app/main.jsbundle' --assets-dest '/Users/User/Library/Developer/Xcode/DerivedData/test-gqrafewypmcfwienuoudxkbrihal/Build/Intermediates.noindex/ArchiveIntermediates/test/BuildProductsPath/Release-iphoneos/test.app'
Scanning folders for symlinks in /Users/User/Documents/Code/Test/Test-app/node_modules (14ms)
Scanning folders for symlinks in /Users/User/Documents/Code/Test/Test-app/node_modules (21ms)
Loading dependency graph, done.
warning: the transform cache was reset.

TransformError: /Users/User/Documents/Code/Test/Test-app/node_modules/js-base64/base64.js: Couldn't find preset "es2015" relative to directory "/Users/User/Documents/Code/Test/Test-app/node_modules/js-base64"

+ [[ false != true ]]
+ [[ ! -f /Users/User/Library/Developer/Xcode/DerivedData/test-gqrafewypmcfwienuoudxkbrihal/Build/Intermediates.noindex/ArchiveIntermediates/test/BuildProductsPath/Release-iphoneos/test.app/main.jsbundle ]]
+ echo 'error: File /Users/User/Library/Developer/Xcode/DerivedData/test-gqrafewypmcfwienuoudxkbrihal/Build/Intermediates.noindex/ArchiveIntermediates/test/BuildProductsPath/Release-iphoneos/test.app/main.jsbundle does not exist. This must be a bug with'
error: File /Users/User/Library/Developer/Xcode/DerivedData/test-gqrafewypmcfwienuoudxkbrihal/Build/Intermediates.noindex/ArchiveIntermediates/test/BuildProductsPath/Release-iphoneos/test.app/main.jsbundle does not exist. This must be a bug with
+ echo 'React Native, please report it here: https://github.com/facebook/react-native/issues'
React Native, please report it here: https://github.com/facebook/react-native/issues`

### Reproducible Demo
I'm working on

**Comment by karlmosenbacher** [comment]
+1

**Comment by roura356a** [comment]
Still having this issue with 0.54.0

**Comment by clovs** [comment]
Try to reboot your PC.
Then try to reinstall all node_modules

 npm install --save-dev babel-preset-es2015
worked for me
