### ISSUE TITLE
Border color behaviour breaks in Android in 0.51

### ISSUE THREAD

**Issue by AndrewIngram** [facebook/react-native#17286]
I've been using the old trick from CSS days to draw triangles with React Native, eg:

```jsx
<View style={{
  width: 64,
  height: 64,
  borderWidth: 32,
  borderColor: 'red',
  borderTopColor: 'transparent',
  borderLeftColor: 'transparent',
 }} />
```

Expo Snack reproduction here: https://snack.expo.io/Skyt2nPzG (Switch between SDK 24 and 23 to toggle between React Native 0.51 and 0.50)

In React Native 0.50 and earlier, this correctly renders like this:
![rn050](https://user-images.githubusercontent.com/35227/34202727-8e142b5c-e570-11e7-8a0f-5d139c21447d.png)

In React Native 0.51 it renders like this:
![rn051](https://user-images.githubusercontent.com/35227/34202730-8f871b84-e570-11e7-846a-d756e6f5c0b2.png)

Explicitly defining border colors for all sides seems to be a workaround:

```jsx
<View style={{
  width: 64,
  height: 64,
  borderWidth: 32,
  borderRightColor: 'red',
  borderBottomColor: 'red',
  borderTopColor: 'transparent',
  borderLeftColor: 'transparent',
 }} />
```

iOS behaves as expected in all versions.

**Comment by shergin** [comment]
cc @rsnara
