### ISSUE TITLE
navigationBarColor on Android does not work

### ISSUE THREAD

**Issue by rogerkerse** [facebook/react-native#17308]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: macOS High Sierra 10.13.2
  Node: 8.9.1
  Yarn: 1.3.2
  npm: 5.5.1
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.51.0 => 0.51.0

Target Platform: Android (8.1)

### Steps to Reproduce

(Write your steps here:)

1. I created empty react native project and empty android project.
2. I add this to styles AppTheme
`<item name="android:navigationBarColor">#2dab37</item>`
3. Run project

### Expected Behavior

Regular android project changes color from black to green behind on screen soft navigation buttons, but react native project does not.

### Actual Behavior

React native projects on screen soft navigation buttons background stays black no matter what.

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by Dorentin1997** [comment]
Can you show a screen shot of your code so i can get more information about what you are doing.

**Comment by damoguyan8844** [comment]
I have same problem , with android 8.0.

**Comment by rogerkerse** [comment]
This is the code then
<img width="577" alt="screen shot 2017-12-23 at 09 06 14" src="https://user-images.githubusercontent.com/571171/34317845-94752d96-e7c0-11e7-9264-d822c82500ae.png">

But I figured it out, once I change `targetSdkVersion` to 27 in app/build.gradle, then it works. It would be nice if react-native would set itself to use newer version of things
