### ISSUE TITLE
[WebSocket] RCTWebSocket crashes when receiving messages in binary format

### ISSUE THREAD

**Issue by orktes** [facebook/react-native#1730]
WebSocket client doesn't currently contain any handling for binary messages and just passes the message directly to bridge. This crashes the application.

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Invalid type in JSON write (_NSInlineData)'
```

Problematic code:
https://github.com/facebook/react-native/blob/0c9c6e89e36c3bd8c7926ad58d58c750975ae61a/Libraries/WebSocket/RCTWebSocketManager.m#L83-L89

Few ways to fix this.

1. Wait for https://github.com/facebook/react-native/issues/1424
2. Pass error describing the issue instead of crashing
3. Convert NSData to string
4. Base64 encode NSData and convert to arraybuffer & blob in JS

Personally I'd prefer 4. as it brings the polyfill api more closer to actual WebSocket behaviour. I can take a stab at the problem once we've settled with the correct approach.

Thanks!

**Comment by orktes** [comment]
It seems that FileReader and atob (and probably Blob)  are not implemented in JSCore by default. Should be go with 3.?

**Comment by phoboslab** [comment]
We could also just push Apple to provide a native API for Typed Arrays in JSCore:
https://bugs.webkit.org/show_bug.cgi?id=120112

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/websocket-rctwebsocket-crashes-when-receiving-messages-in-binary-format
