### ISSUE TITLE
SKIP_BUNDLING does not take dev-machine IP into account

### ISSUE THREAD

**Issue by Knight704** [facebook/react-native#17301]
### Is this a bug report?
yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?
yes

### Environment
OS: macOS Sierra 10.12.6
Node: 9.0.0
Yarn: 0.24.6
npm: 5.5.1
Watchman: 4.9.0
Xcode: Xcode 9.1 Build version 9B55
Android Studio: 2.3 AI-162.3934792

Packages: (wanted => installed)
react: 16.0.0-alpha.12 => 16.0.0-alpha.12
react-native: 0.48.4 => 0.48.4

### Steps to Reproduce
1. Run SKIP_BUNDLING=true react-native run-ios --device
2. Wait app build and install on device
3. Open app

### Expected Behavior
App loads bundle from local packager

### Actual Behavior
App uses bundled file, doesn't download from packager

**Comment by rmevans9** [comment]
https://github.com/facebook/react-native/pull/16533 seems like it will fix this.
