### ISSUE TITLE
ES6 and ES7 features without babel transpiling?

### ISSUE THREAD

**Issue by mercmobily** [facebook/react-native#17314]
I just have a quick question, and I couldn't find it addressed anywhere.
I would love to use Javascript ES6 and ES7 syntax (especially async/await, my new best friends) without transpiling. Is that even an option? And _should_ it be an option?

It all edpends on the sub-question: what Javascript engine does react-active effectively use, on Android and MacOs? Is it taken from the device itself? (in which case transpiling IS the only option...) Or is it provided by React Native?

Thanks for listening...!

**Comment by ide** [comment]
It's not an option right now. You could write a custom babelrc to override all the transforms (at your own risk!).

**Comment by mercmobily** [comment]
OK but then the sub-question stands even taller: 

"what Javascript engine does react-active effectively use, on Android and MacOs? Is it taken from the device itself? (in which case transpiling IS the only option...) Or is it provided by React Native?"

...?

**Comment by ide** [comment]
See the code for the specifics, but the short answer is it uses JSC -- the built-in version on iOS (differs across versions) and a copy from about ~2015 on Android.

**Comment by mercmobily** [comment]
Is there any way to place an updated copy from Android? (I mean, easily enough) Or, do you know if it's planned?

**Comment by ide** [comment]
It's not trivial and my company has supported some work to do it but have encountered some issues. There's a deadline of August 2019 because Google Play will require 64-bit on Android by then.

**Comment by mercmobily** [comment]
OK. Ah, that's 1.5 years away... thanks for answering ide!
