### ISSUE TITLE
[Help] Custom Android text input component, cannot focus

### ISSUE THREAD

**Issue by Doko-Demo-Doa** [facebook/react-native#17317]
### Is this a bug report?

No. But help needed.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Steps to Reproduce

(Write your steps here:)

I'm trying to port this library into my RN app: `https://github.com/ChaosLeong/PinView`

It's a subclass of EditText. And I can't get it to focus on the EditText field with keyboard opened.

### Expected Behavior

The keyboard should be opened and should be editable. I cannot find any solution anywhere.

### Actual Behavior

Can't focus on the EditText.

**Comment by lwinkyawmyat** [comment]
@facebook-github-bot stack-overflow
