### ISSUE TITLE
Jagged rendering of round borders on Android

### ISSUE THREAD

**Issue by firefueled** [facebook/react-native#17311]
### Is this a bug report?
Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?
Yes

### Environment
Environment:
  OS: Linux 4.4
  Node: 6.10.0
  Yarn: 0.24.5
  npm: 3.10.10
  Watchman: 4.7.0
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: ~16 => 16.2.0
  react-native: ~0.51.0 => 0.51.0

Android (any)

### Steps to Reproduce
Simply create a round bordered View.

### Expected Behavior
The bordered View should be smooth, or as smooth as a border-less rounded View

### Actual Behavior
The View with a round border (left) is jagged and ugly while a rounded border-less, but background-colored, View (right) is fine.
![round views](http://pablo.universomw8.com.br/Screenshot_1513881456.png)

### Reproducible Demo
https://github.com/firefueled/rn-bad-borders
The problem is not visible on Snack or a current phone, tested on Samsung S5, but it is so on devices and emulators with lower screen DPI.
This latest release where this starts happening in 0.51.0. It doesn't on 0.50.4
[This commit](https://github.com/facebook/react-native/commit/4994d6a389b4e41ba25e802edab5d3fdc9e8a4f1) seems to have changed something related to border drawing on Android but I haven't looked to deep into it.

**Comment by firefueled** [comment]
The exact same issue has been reported here #17267 
A work-around is "faking" a border by having a smaller view on top of a larger one like:

```jsx
<View style={styles.border}>
  <View style={styles.content}>
  </View>
</View>
...
const styles = StyleSheet.create({
  border: {
    backgroundColor: 'blue',
    borderRadius: 50,
    height: 50,
    width: 50,
    justifyContent: 'center',
    padding: 5,
  },
  content: {
    borderRadius: 40,
    height: '100%',
    width: '100%',
    backgroundColor: 'white',
  },
});
```

**Comment by mezod** [comment]
+1

**Comment by alpamys-qanybet** [comment]
Hey guys, I just copied the ```ReactViewBackgroundDrawable.java, ReactViewBackgroundManager.java, ReactViewGroup.java``` from ```RN0.50.1``` and IT WORKS.

**Comment by Albert0405** [comment]
@alpamys-qanybet  where exactly can i find that files?

**Comment by alpamys-qanybet** [comment]
@Albert0405, here in GitHub.
