### ISSUE TITLE
Error: Activity class MainActivity does not exist.

### ISSUE THREAD

**Issue by wukakuki** [facebook/react-native#17318]
I'm integration React Native with an existing android project. When I run the project(react-native-cli run-android --no-packager), there is an error: Activity class MainActivity does not exist. However, my android project should start with an activity named HomeActivity instead of MainActivity. Sorry for my bad English. The error for a rookie is very difficult. Thank you!

**Comment by rpavlovs** [comment]
I'm having the same issue

**Comment by lindoelio** [comment]
For solve this problem, open your settings.gradle (`.../android/settings.gradle`) and make sure that it contains `include ':app'` (exactly) on there, same like my example below.

```
rootProject.name = 'VoosOnline'

include ':react-native-gesture-handler'
project(':react-native-gesture-handler').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-gesture-handler/android')
include ':react-native-vector-icons'
project(':react-native-vector-icons').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-vector-icons/android')

include ':app'
```

After check it out, do:

- `cd android && ./gradlew clean` && cd ..
- `react-native link`
- `react-native run-android`

I hope it helps.
