### ISSUE TITLE
[0.52] Commits to cherry-pick into stable release

### ISSUE THREAD

**Issue by ide** [facebook/react-native#17315]
The thread containing issues that are blocking the 0.52 release and need to be addressed. 

**Please keep this list to critical bug fixes that are new in 0.52 and ideally have been merged into master** -- post commit hashes rather than issue/PR numbers unless the issue/PR in question targets a problem specific to 0.52. The intent of these cherry-pick threads is not to solicit features but to fix things that make 0.52 substantially more launch-blocked than 0.51.

---

https://github.com/facebook/react-native/commit/7ff6657985a09bd2572615d16403fba3af709859 (fixes a layout bug for older Android introduced in https://github.com/facebook/react-native/pull/16596)

**Comment by grabbou** [comment]
Thanks, @ide - I completely forgot to create this issue after spending few days on getting the branch up and running.

Do you have any requirements as to when next version should be released? There's Christmas coming up, so I can release that one in a couple of days.
