### ISSUE TITLE
Font embedded line height issue

### ISSUE THREAD

**Issue by Druux** [facebook/react-native#17322]
### Is this a bug report?

probably

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

yes

### Environment

Environment:
  OS: macOS High Sierra 10.13.1
  Node: 8.7.0
  Yarn: Not Found
  npm: 5.6.0
  Watchman: Not Found
  Xcode: Xcode 9.0.1 Build version 9A1004
  Android Studio: 1.5 AI-141.2456560

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.51 => 0.51.0

### Steps to Reproduce

I have installed some custom fonts within `assets/fonts` and linked them via `react-native link`.
Everything is working fine but it seems like I have to face the default font embedded line height issue.
The text doesn't get vertically centered within the view due to some default padding within the font (I suppose). Do you guys could suggest me any non-hacky workaround to fix this issue?

### Expected Behavior

<img width="166" alt="bildschirmfoto 2017-12-22 um 15 07 49" src="https://user-images.githubusercontent.com/9655723/34300790-0e6034ee-e72a-11e7-96b9-cb99289bc633.png">

### Actual Behavior
I didn't make use of any special styles - I have just added `alignSelf: 'center'` and `fontFamily: 'GothamRounded-Bold'` to the component style.

<img width="163" alt="bildschirmfoto 2017-12-22 um 15 07 00" src="https://user-images.githubusercontent.com/9655723/34300782-fe0d8f56-e729-11e7-9c1b-6313316d5d38.png">

<img width="146" alt="bildschirmfoto 2017-12-22 um 15 07 30" src="https://user-images.githubusercontent.com/9655723/34300786-08bd5d78-e72a-11e7-9319-9e96e10d9101.png">

**Comment by andfk** [comment]
@Druux had you found a fix?

**Comment by Druux** [comment]
@andfk Yes I did after a lot of time spending on reasearch :D but thats the cleanest way to go imo: https://medium.com/@martin_adamko/consistent-font-line-height-rendering-42068cc2957d

**Comment by Druux** [comment]
@andfk Yes I did after a lot of time spending on research :D but thats the cleanest way to go imo:
(I will sum it up for you) 

1. [Download Font Tools for Xcode](https://developer.apple.com/download/more/?=Font%20Tools%20for%20Xcode)
2. In Terminal navigate to `<insert your custom font's path here>`
3. Run `$ ftxdumperfuser -t hhea -A d <insert your font name here>`
4. Edit dumped GothamRounded-Bold.hhea.xml and set lineGap="0"
5. If `lineGap` was `200` and `ascender="800"`, set `ascender` to the sum of these two => `1000`
6. In Terminal run `$ ftxdumperfuser -t hhea -A f <insert your font name here>`
7. Change directory to the project's root folder and run `react-native link`

Done. Your new values are fused back the font file.

**Repeat steps 5 and 6 until the rendering is OK.** Do not change other values. Those should be OK.

Keep in mind that this approach only works on macOS - but I am sure that there is a way to accomplish this on another OS.

Hope I could help some of you out.

**Comment by andfk** [comment]
Woop! Awesome explanation. Many thanks @Druux im pretty sure this issue is very common :)
