### ISSUE TITLE
i can run the example

### ISSUE THREAD

**Issue by Drakezair** [facebook/react-native#17336]
### Is this a bug report?

(write your answer here)

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.)

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by waquidvp** [comment]
@facebook-github-bot close

**Comment by waquidvp** [comment]
Do you have an actual issue with react-native or your example? This issue seems to be some sort of spam? Could you give some detail if you are having any issue, or I want to close this issue.

**Comment by waquidvp** [comment]
@facebook-github-bot label Needs more information
