### ISSUE TITLE
How to detect Multi Window mode in Galaxy S8 on my app?

### ISSUE THREAD

**Issue by northern-fox** [facebook/react-native#17330]
I use Modal component, and for the samsung galaxy s8 I have bug which you can see on my screenshot 
![screenshot_20171223-164037](https://user-images.githubusercontent.com/8543255/34319683-b851ccc4-e801-11e7-9d47-85914d384e44.png)

**Comment by northern-fox** [comment]
@facebook-github-bot 
How to open navigation bar in Samsung Galaxy S8 in case when modal is open?

**Comment by JasonZhongjunyan** [comment]
我也遇到了这个问题，就是modal层在三星S8手机和vivo手机上显示不全（modal没有整个遮挡屏幕，底下会有一节空白，遮挡不住modal层下一层的内容），而且是时不时的，作者解决了么？
