### ISSUE TITLE
Android: screen not resizing when shifting focus to next empty TextInput

### ISSUE THREAD

**Issue by Agontuk** [facebook/react-native#17338]
### Is this a bug report?
YES

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?
YES

### Environment
Environment:
  OS: macOS High Sierra 10.13.2
  Node: 8.9.1
  Yarn: 1.3.2
  npm: 5.5.1
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.51.0 => 0.51.0

Target Platform: Android

### Steps to Reproduce

1. Create a blank react-native app and add a scrollview with 7-8 TextInput inside it. (just making sure some of the input will be under keyboard when it shows up)
2. For the bottom inputs, add `blurOnSubmit={false}` and `onSubmitEditing` to focus to the next input when submitting. Example: (Notice the last input value is empty.)
```js
<TextInput
  ref={(r) => { this.pqr = r; }}
  blurOnSubmit={false}
  onSubmitEditing={() => { this.stu.focus(); }}
  value='pqr'
  onChangeText={() => null}
  returnKeyType='next'
/>
<TextInput
  ref={(r) => { this.stu = r; }}
  blurOnSubmit={false}
  onSubmitEditing={() => { this.vwx.focus(); }}
  value='stu'
  onChangeText={() => null}
  returnKeyType='next'
/>
<TextInput
  ref={(r) => { this.vwx = r; }}
  value=''
  onChangeText={() => null}
  returnKeyType='go'
/>
```
3. Now focus the input which has a value `pqr` and press 'Next' from keyboard. Screen will push up the next input which has a value set to `stu`. Now press 'Next' again, in this case screen doesn't push up the next input because it's value is empty.

### Expected Behavior
Next input should be pushed up by screen

### Actual Behavior
Next input (ref `vwx`) is not getting pushed up above the keyboard cause it's initial value is empty.

### Demo
![input_bug](https://user-images.githubusercontent.com/5656440/34325222-0c9885de-e8b6-11e7-9ebb-cca967f1425f.gif)

**Comment by danilobuerger** [comment]
Reproducible on react 16.3 / react-native 0.53.3

**Comment by Agontuk** [comment]
This is still happening on RN 0.55.4, I didn't have a chance to look for a fix. Hopefully someone else will find a solution and post it here, so that everyone can benefit from it.

**Comment by fghiggi** [comment]
Still happening on RN 0.57.1. ScrollView don't focus on empty input, more examples:

![focus](https://user-images.githubusercontent.com/9020705/46312253-ead0fb80-c59a-11e8-869c-e77613714b87.gif)

[Expo example](https://snack.expo.io/@theghiggi/why_u_no_focus)

**Comment by RodrigoAWeber** [comment]
@hramos any updates?

**Comment by ozberkctn** [comment]
Still happening. any solution ?

**Comment by hramos** [comment]
No update on my part. If there is a pull request that fixes this issue, let me know so we can take a look.

**Comment by ozberkctn** [comment]
i found the solution can you take a look @hramos [Pull request](https://github.com/facebook/react-native/pull/23143)

**Comment by jkdf2** [comment]
@hramos can you remove the PR Submitted tag? The submitted PR was rejected.
