### ISSUE TITLE
borderStyle cannot working (v0.47.2 on Android)

### ISSUE THREAD

**Issue by kerwin1** [facebook/react-native#17344]
### Is this a bug report?
I wanna the top of border be dashed,but It's not working.
`borderTopWidth:1,
  borderTopColor:'#ddd',
  borderStyle:'dashed',`
Then I try to make all of the borders be dashed.It's working after I add 'borderRadius : 1'.
`borderWidth:1,
  borderStyle:'dashed',
  borderRadius:1,
  borderColor:'#ddd',`
I don't know why.Can anyone resolve it?Thx in advance.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

  Environment:
    OS:  macOS Sierra 10.12.6
    Node:  8.9.1
    Yarn:  1.3.2
    npm:  5.5.1
    Watchman:  4.7.0
    Xcode:  Xcode 8.3.3 Build version 8E3004b
    Android Studio:  2.3 AI-162.4069837

  Packages: (wanted => installed)
    react-native: 0.47.2
    react: 16.0.0-alpha.12

**Comment by waquidvp** [comment]
This seems to be an unsolved bug, this bug hasn't been fixed for years. Refer to this issue https://github.com/facebook/react-native/issues/3159.
