### ISSUE TITLE
Keyboard can not dismiss after use Alert

### ISSUE THREAD

**Issue by chiquyet199** [facebook/react-native#17356]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

  Environment:
    OS:  macOS Sierra 10.12.6
    Node:  8.9.0
    Yarn:  not found
    npm:  5.5.1
    Watchman:  4.9.0
    Xcode:  Xcode 9.1 Build version 9B55
    Android Studio:  3.0 AI-171.4408382

  Packages: (wanted => installed)
    react-native: 0.49.3 => 0.49.3
    react: 16.0.0-beta.5 => 16.0.0-beta.5

  Target Platform: iOS (10.3)

### Steps to Reproduce
I have a screen with one Input, two buttons (one for dismiss keyboard and another for alert some dummy)
1. Focus on Input
2. Click button alert then dismiss alert dialog
3. Click button dismiss keyboar

### Expected Behavior

The keyboard should dismiss

### Actual Behavior

The keyboard did not dismiss

### Reproducible Demo

Code: 
```

import React, { Component } from 'react'
import { TextInput, TouchableHighlight, Text, Alert } from 'react-native'

import DismissKeyboard from 'dismissKeyboard'
import Container from 'components/Container'

class Home extends Component {
  state = { text: '' }

  alert = () => {
    Alert.alert('Alert Title', 'Invalid input', [{ text: 'Ok' }])
  }

  render() {
    return (
      <Container center>
        <TextInput
          style={{ height: 40, width: 120, borderColor: 'gray', borderWidth: 1 }}
          onChangeText={text => this.setState({ text })}
          value={this.state.text}
        />

        <TouchableHighlight
          onPress={DismissKeyboard}
          style={{ borderWidth: 1, borderColor: '#fff', width: 100, height: 50 }}
        >
          <Text>hide keyboard</Text>
        </TouchableHighlight>

        <TouchableHighlight
          onPress={this.alert}
          style={{ borderWidth: 1, borderColor: '#fff', width: 100, height: 50 }}
        >
          <Text>alert</Text>
        </TouchableHighlight>
      </Container>
    )
  }
}

export default Home
```

**Comment by spape** [comment]
+1

**Comment by spape** [comment]
@chiquyet199 
The following solved the problem for me (work around):
```js
setTimeout(function(){
   //... open your alert here
}, 50)
```

**Comment by ericdcobb** [comment]
@spape's fix works for me (note that I have to explicitly call `Keyboard.dismiss()` before  using the setTimeout. Obviously feels a *little* hacky  but it works ;-).

A note, my scroll view which I am using to dismiss the keyboard on press is set to:

```
keyboardShouldPersistTaps="handled"
```
So buttons still work while the keyboard is out. Maybe that's relevant?

**Comment by dalinarkholin** [comment]
This issue still exists or has cropped back up in React Native v0.54.3.

setTimeout workaround is definitely hacky...but it will work for now.

**Comment by teod** [comment]
Also have this issue with React Native 0.55.4

**Comment by RafaelKr** [comment]
RN 0.56.0 also has this issue.

**Comment by Mth-bs-park** [comment]
RN 0.57.1 also has this issue.

**Comment by KryDos** [comment]
The issue is still here in 0.57.1. 
In my case I cannot use `setTimeout` because Alert that is popping up is called by password "suggester" ("Passwords" button - on top of the keyboard). When username and password are automatically filled in, the `Keyboard.dismiss()` isn't working.

**Comment by swaroopa94** [comment]
@KryDos did you solve the issue?

**Comment by KryDos** [comment]
@swaroopa94 I've changed `returnKeyType` attribute of my `TextInput` to `done`. In this case it works.
