### ISSUE TITLE
The placeholder of the TextInput is not displayed when the layout changes, and the content of the TextInput input is assigned to another TextInput

### ISSUE THREAD

**Issue by baguosiji** [facebook/react-native#17364]
### Is this a bug report?

The placeholder of the TextInput is not displayed when the layout changes, and the content of the TextInput input is assigned to another TextInput

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

yes

### Environment
android  6.0 and 7.0

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)
import React, {Component} from "react";
import {Text, View, TextInput, Button,TouchableOpacity} from "react-native";
import {STYLES} from "./styles";

export class Setting extends Component {
    constructor(props) {
        super(props);
        this.state = {
            selectGoodTag: ""
        }
    }

    data1;
    data2;
    data3;
    data4;
    data5;

    render() {
        return (
            <View>
                <TouchableOpacity onPress={() => this.setState({selectGoodTag: "体系服务"})}>
                    <View style={{alignItems:"center",justifyContent:"center",marginTop:20,padding:20}}>
                        <Text>体系服务</Text>
                    </View>
                </TouchableOpacity>
                <TouchableOpacity title="VIP专区" onPress={() => this.setState({selectGoodTag: "VIP专区"})}>
                    <View style={{alignItems:"center",justifyContent:"center",marginTop:20,padding:20}}>
                        <Text>体系服务</Text>
                    </View>
                </TouchableOpacity>
                {this.state.selectGoodTag === "体系服务" ?
                    <View>
                        <View style={[{height: 45, flexDirection: 'row'}, STYLES.borderBottom]}>
                            <View style={{flex: 1, justifyContent: 'center'}}>
                                <Text>市场零售价</Text>
                            </View>
                            <View style={{flex: 1, justifyContent: 'center'}}>
                                <TextInput style={{textAlign: 'right', color: "#333", paddingRight: 10}}
                                           placeholder="请输入市场零售价"
                                           placeholderTextColor="#ddd"
                                           onChangeText={(text) => {
                                               this.data1 = text
                                           }}
                                           underlineColorAndroid="transparent"/>
                            </View>
                        </View>
                        <View style={[{height: 45, flexDirection: 'row'}, STYLES.borderBottom]}>
                            <View style={{flex: 1, justifyContent: 'center'}}>
                                <Text style={{fontSize: 14}}>批发价 <Text
                                    style={{fontSize: 12, color: "red"}}>(购买现金)</Text></Text>
                            </View>
                            <View style={{flex: 1, justifyContent: 'center'}}>
                                <TextInput style={{textAlign: 'right', color: "#333", paddingRight: 10}}
                                           placeholder="请输入批发价"
                                           placeholderTextColor="#ddd"
                                           onChangeText={(text) => {
                                               this.data2.amount = text
                                           }}
                                           underlineColorAndroid="transparent"/>
                            </View>
                        </View>
                        <View style={[{height: 45, flexDirection: 'row'}, STYLES.borderBottom]}>
                            <View style={{flex: 1, justifyContent: 'center'}}>
                                <Text>赠送积分</Text>
                            </View>
                            <View style={{flex: 1, justifyContent: 'center'}}>
                                <TextInput style={{textAlign: 'right', color: "#333", paddingRight: 10}}
                                           placeholder="请输入赠送积分"
                                           placeholderTextColor="#ddd"
                                           onChangeText={(text) => {
                                               this.data3 = text
                                           }}
                                           underlineColorAndroid="transparent"/>
                            </View>
                        </View>
                    </View> :
                    <View>
                        <View style={[{height: 45, flexDirection: 'row'}, STYLES.borderBottom]}>
                            <View style={{flex: 1, justifyContent: 'center'}}>
                                <Text>厂商指导价</Text>
                            </View>
                            <View style={{flex: 1, justifyContent: 'center'}}>
                                <TextInput style={{textAlign: 'right', color: "#333", paddingRight: 10}}
                                           placeholder="请输入厂商指导价"
                                           placeholderTextColor="#ddd"
                                           onChangeText={(text) => {
                                               this.data4 = text
                                           }}
                                           underlineColorAndroid="transparent"/>
                            </View>
                        </View>
                        <View style={[{height: 45, flexDirection: 'row'}, STYLES.borderBottom]}>
                            <View style={{flex: 1, justifyContent: 'center'}}>
                                <Text>市场零售价</Text>
                            </View>
                            <View style={{flex: 1, justifyContent: 'center'}}>
                                <TextInput style={{textAlign: 'right', color: "#333", paddingRight: 10}}
                                           placeholder="请输入市场零售价"
                                           placeholderTextColor="#ddd"
                                           onChangeText={(text) => {
                                               this.data5 = text
                                           }}
                                           underlineColorAndroid="transparent"/>
                            </View>
                        </View>
                        <View style={[{height: 45, flexDirection: 'row'}, STYLES.borderBottom]}>
                            <View style={{flex: 1, justifyContent: 'center'}}>
                                <Text>进货价</Text>
                            </View>
                            <View style={{flex: 1, justifyContent: 'center'}}>
                                <TextInput style={{textAlign: 'right', color: "#333", paddingRight: 10}}
                                           placeholder="请输入进货价"
                                           placeholderTextColor="#ddd"
                                           onChangeText={(text) => {
                                               this.data6 = text
                                           }}
                                           underlineColorAndroid="transparent"/>
                            </View>
                        </View>
                    </View>}
            </View>
        )
    }
}

**Comment by harshsrivastavaglobussoft** [comment]
please report issues in proper format
