### ISSUE TITLE
upgrading RN: runtime crash on ios (in release mode)

### ISSUE THREAD

**Issue by gaultierq** [facebook/react-native#17367]
### Is this a bug report?
yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

yes

### Environment

  Environment:
    OS:  macOS Sierra 10.12.6
    Node:  8.4.0
    Yarn:  0.27.5
    npm:  5.4.0
    Watchman:  4.7.0
    Xcode:  Xcode 8.3.3 Build version 8E3004b
    Android Studio:  2.3 AI-162.4069837

  Packages: (wanted => installed)
    react-native: 0.48.1 => 0.48.1
    react: 16.0.0-alpha.12 => 16.0.0-alpha.12

  Target Platform: iOS (10.3)

### Steps to Reproduce

(Write your steps here:)

1. run `react-native-git-upgrade`
2. run `react-native run-ios --configuration Release`

### Expected Behavior

App launching normally

### Actual Behavior

App crashing at startup with error :

<Error>: objc[49957]: Class VCWeakObjectHolder is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AVConference.framework/Frameworks/ViceroyTrace.framework/ViceroyTrace (0x122e7f4d0) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AVConference.framework/AVConference (0x122cfef48). One of the two will be used. Which one is undefined

**Comment by Romchik22** [comment]
Have the same issue on IOS 11.2. All included modules return the same logs.
https://imgur.com/a/UvTx6
