### ISSUE TITLE
ScrollView crashing the app in release variant.

### ISSUE THREAD

**Issue by Aleksandar-FFWD** [facebook/react-native#17363]
### Is this a bug report?
Yes!

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?
Yes.

### Environment
  OS: Windows 10
  Node: 9.3.0
  Yarn: 0.24.5
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.0.0.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.50.4 => 0.50.4

 Target Platform:
-  Android (7.1.1)
-  Android (6.0)

### Steps to Reproduce
- Start a fresh react native project. Run `react-native init Test --version 0.50.4`
- Edit the `App.js` file with following changes

```
...

<View style={styles.container}>
   <ScrollView contentContainerStyle={{ flexGrow: 1 }}>
      <Text style={styles.welcome}>
         Welcome to React Native!
      </Text>
      <Text style={styles.instructions}>
         To get started, edit App.js
      </Text>
      <Text style={styles.instructions}>
            {instructions}
       </Text>

       ...

   </ScrollView>
</View>

...
```
- Extend the content a bit so it becomes scrollable. 
- Follow the guide for generating signed .apk file. https://facebook.github.io/react-native/docs/signed-apk-android.html

- Run `react-native run-android --variant=release`

### Expected Behavior

Expected the app to work normal in release version like in dev. 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/24916092/34376901-a71180b8-eaee-11e7-8e6f-42d632c009f7.gif)

### Actual Behavior

- App crashes on startup.
- Confirmed the issue on 2 different computers.
- Same issue persist on **react-native version 51.0**
- App works as expected on **react-native version 49.5**

![ezgif com-video-to-gif 2](https://user-images.githubusercontent.com/24916092/34376905-b1f90e74-eaee-11e7-8361-15ecd011c270.gif)

### Reproducible Demo
Download the project. 
Run `npm install`
Run `react-native run-android --variant=release`

https://github.com/Aleksandar-FFWD/react-native-test

**Comment by aspidvip** [comment]
and I have the same situation

**Comment by aspidvip** [comment]
2017-12-29 10:51:30.233 [error][tid:com.facebook.react.JavaScript] TypeError: undefined is not an object (evaluating 'this._subscribableSubscriptions.forEach')

This error is located at:
    in ScrollView
    in t
    in t
    in RCTView
    in a
    in Connect(a)
    in n
    in i
    in RCTView
    in RCTView
    in t

**Comment by Aleksandar-FFWD** [comment]
@aspidvip Its connected to #17348 as I can see. 

There is an issue with `..\node_modules\react-native\Libraries\Components\Subscribable.js` on `componentWillUnmount` function.

The workaround I did was to change this:

```
componentWillUnmount: function() {
    this._subscribableSubscriptions.forEach(
      (subscription) => subscription.remove()
    );
    this._subscribableSubscriptions = null;
},
```

To this: 

```
componentWillUnmount: function() {
    this._subscribableSubscriptions && this._subscribableSubscriptions.forEach(
      (subscription) => subscription.remove()
    );
    this._subscribableSubscriptions = null;
},
```

**Comment by Silvercast** [comment]
related to https://github.com/facebook/react-native/issues/17348

**Comment by bridgewaterlabs** [comment]
I have huge issue with ScrollView not running properly in release mode ... WTF in debug all works fine
