### ISSUE TITLE
Android does not properly support bidirectinal text for mixed content due to missing support for writingDirection

### ISSUE THREAD

**Issue by galkahana** [facebook/react-native#17361]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: macOS High Sierra 10.13.2
  Node: 8.9.2
  Yarn: 0.27.5
  npm: 5.5.1
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.0.0 => 16.0.0
  react-native: ^0.51.0 => 0.51.0

  Target Platform: iOS (tested on 11.2) and Android (tested on 6.0.1)

### Steps to Reproduce

(Write your steps here:)

1. Create a text element
2. as its content provide the following text: "גל, how are you"?
3. provide "ltr" as writingDireciton for this element style, to convey that the text writing direction intent is left to right. (namely - this is a sentence in english).

### Expected Behavior

Text should appear like it does here in github - hebrew name on the left of the rest of the sentence on its right, as this is a sentence in english.

### Actual Behavior

On IOS the text appears as expected (thanks to support of intent through writingDirection). On android the text would appear flipped - hebrew name on the right, while rest of the text on the left, as this property is ignored.

Below is a screen shot of the demo below to show the problem. android on the left, iphone on the right. the problematic texts are the 3rd and 4th lines in each section, which on Android always follow Auto algorithm to determine writing direction intent, and in IOS the intent is correctly provided by the user:
![screen shot 2017-12-26 at 13 17 11](https://user-images.githubusercontent.com/271847/34373257-c30967a6-eae2-11e7-9456-c096287b2ee6.png)

### Reproducible Demo

https://snack.expo.io/HJbqW6emz
(this is a snack app, you will need Expo on your device, and then just scan the code to run the program).

This demo shows all possible cases of writing direction. when played on IOS the texts appear as expected. When on android they are flipped.

ltr 4th line is the example i explained here in reproducing steps. Though the more common one, is the the RTL 4th line, which shows a case of using an english written name (say, a brand name) in a hebrew sentence.

This issue, while potentially seeming minor, is at the essence of properly supporting RTL functionality. mixed text is quite common in RTL languages scenarios (consider numbers or brand names (which are normally internally LTR)), and the method supported in Android which tries to guess the writing direction based on the text (namely - Auto bidi) does not work and cannot work. hence any including of such mixing of text will cause the text order to appear wrong. 
Due to potential line braking, it is quite difficult to determine how to order the text to workaround this problem, hence it is humbly requested to add support for this flag in Android, or let me know if there's a known workaround. 
Thank you,
Gal.

**Comment by ilonashub** [comment]
I have the same issue in version 0.55.4...
@galkahana did you find a fix to it?

**Comment by ilonashub** [comment]
meanwhile I ended up prefixing all the text I wanted to be RTL with `\u200F`

**Comment by galkahana** [comment]
@ilonashub this is the way to go

**Comment by yaronlevi** [comment]
> meanwhile I ended up prefixing all the text I wanted to be RTL with `\u200F`

This is pure magic! (-:
