### ISSUE TITLE
Is DRM (Digital Rights Management) Available in react-native

### ISSUE THREAD

**Issue by Sagaryal** [facebook/react-native#17377]
### Is this a bug report?

No but necessary

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes, Briefly.
http://facebook.github.io/react-native/help.html did not help me. My queries were not answered by either of the solutions mentioned in that link. Thankyou.
### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by brentvatne** [comment]
hi! issues are reserved for bugs, not for questions like this.
