### ISSUE TITLE
Webview of React-native In the adaptation of Samsung S8 curved screen phone issues.

### ISSUE THREAD

**Issue by jsl328** [facebook/react-native#17372]
### Is this a bug report?

WebView of react-native adapter Samsung S8 Android mobile phone screen surface, the horizontal scroll bar, and laterally beyond the screen outside. And html+css is normal in a mobile browser.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.)

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by wyxt81** [comment]
i also met this situation
