### ISSUE TITLE
Wrong border thickness when drawing TouchableOpacity with borderRadius

### ISSUE THREAD

**Issue by huynhtansi** [facebook/react-native#17384]
### Is this a bug report?

Yes. It only occurs 0.51.0 version

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

 Environment:
  OS: macOS High Sierra 10.13.2
  Node: 8.9.1
  Yarn: Not Found
  npm: 5.5.1
  Watchman: Not Found
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.51.0 => 0.51.0

  Target Platform: Android 4.1.2 (API 16)

### Steps to Reproduce

`
<TouchableOpacity
      style={{
            				borderColor: 'blue',
            				borderWidth: 1,
            				borderRadius: 4,
            				alignItems: 'center',
            				justifyContent: 'center',
            				flexDirection: 'row',
            				height: 44,
                            width: 200,
			        }}>
        				{
        					<Text style={{
        						fontSize: 16,
        						color : 'blue',
        						textAlign: 'center',
        						backgroundColor: 'transparent',
        					}}>
        						This is a flat button
        					</Text>
        				}
			    </TouchableOpacity>
`

### Expected Behavior

![expect_behavior](https://user-images.githubusercontent.com/16728346/34432626-85cb27b0-ecab-11e7-980d-825e5f611dea.png)

### Actual Behavior

![actual_behavior](https://user-images.githubusercontent.com/16728346/34432639-a5c73478-ecab-11e7-87ab-ddc42bb90c99.png)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by huynhtansi** [comment]
@adrianomelo why is your commit referenced this issue?

**Comment by adrianomelo** [comment]
Hi @huynhtansi, thank you for pointing it out. It is a typo, I am going to delete the commit.

**Comment by derakhshanfar** [comment]
same issue for me, any solution?

**Comment by ThaJay** [comment]
Same issue here on Android
    "react-native": "^0.51.0",
    "react": "^16.0.0-alpha.12",

**Comment by PerThomasHaga** [comment]
+1
