### ISSUE TITLE
[ListView] renderSectionHeader onPress event not working on overlay?

### ISSUE THREAD

**Issue by yamill** [facebook/react-native#1739]
Hey guys, I'm having a little weird issue here not sure if anyone else has noticed this but when adding an event inside a renderSectionHeader it works when its docked to the top, when overlayed over the section it doesn't work.

Here's a screenshot scenario.

I am able to click through the touchableHighlight surrounding the image (when docked):
![ios simulator screen shot jun 24 2015 5 32 17 pm](https://cloud.githubusercontent.com/assets/755943/8342028/49f61a12-1a97-11e5-9e85-9c05b22344cf.png)

I am not able to click through the touchableHighlight surrounding the image when overlayed over the section:
![ios simulator screen shot jun 24 2015 5 35 41 pm](https://cloud.githubusercontent.com/assets/755943/8342058/7ba3bdda-1a97-11e5-8345-1dd92fe0444f.png)

**Comment by ide** [comment]
@yamill Can you test this with 0.10.0-rc if you still have the code available? An issue with touch events in sticky headers has been fixed.
