### ISSUE TITLE
SocketRocket has build warnings

### ISSUE THREAD

**Issue by ide** [facebook/react-native#174]
The newest version of SocketRocket fixes these but React Native is using an old version. Grabbing the latest code should be fine but probably better if you guys do it internally.

On a related note I believe the current setup won't build apps that already use SocketRocket. When there are React modules that use more popular libraries like CocoaLumberjack or AFNetworking, the app and the React modules need to share the same copy of the 3rd party Obj-C dependency (unlike with npm, two copies of the same framework or static library will conflict). This is also an issue if two React modules use the same library.

**Comment by ccheever** [comment]
This no longer happens. Closing the issue.
