### ISSUE TITLE
Does React Native support SPDY?

### ISSUE THREAD

**Issue by matthewga0** [facebook/react-native#1741]
Does `XMLHttpRequest` or `Fetch` support SPDY in React Native?

**Comment by ide** [comment]
No it does not. In iOS 9 all NSURLSessions automatically support HTTP2.

**Comment by ide** [comment]
Actually I misspoke - there is some SPDY support in iOS 8. But React Native doesn't do anything special regarding SPDY.

**Comment by matthewga0** [comment]
I saw [CocoaSPDY](https://github.com/twitter/CocoaSPDY) is injecting `NSURLConnection` and `NSURLSession`, is it possible to make SPDY working with React Native?

**Comment by kemcake** [comment]
@matth3wga0 Did you find a way to make it work ?

**Comment by ide** [comment]
RN uses NSURLSession so on iOS 8 it will use SPDY, and on iOS 9 and 10 it will use HTTP/2. Servers like NGINX are retiring SPDY so it probably makes sense to use HTTP/2.

RN supports HTTP/2 on iOS 9 and 10 (using NSURLSession) and Android (using OkHttp 3.4.1).
