### ISSUE TITLE
Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system

### ISSUE THREAD

**Issue by iammelvin** [facebook/react-native#17410]
### Is this a bug report?

Yes

I cloned a react-native project from github then ran npm run eject after then when i tried to run the app using react-native run-android i am getting the below error

Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system.Please install a supported C++11 compiler and reinstall the module 'uws'.

Because of this the packager server exits and i couldn't connect to dev server from my physical device also one more issue i face is when i try to run adb reverse tcp:8081 tcp:8081 i am getting address already in use but i tried to kill adb using adb kill-server but still i get the same error.Need some help to get passed this as a new dev to react native.Thanks in advance !

**Comment by iammelvin** [comment]
UWS Build log 
=========

`
M:\cryptoR\node_modules\uws>if not defined npm_config_node_gyp (node "C:\Users\iamme\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild ) 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [M:\cryptoR\node_modules\uws\build\binding.sln]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\iamme\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\iamme\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd M:\cryptoR\node_modules\uws
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok 
`

**Comment by dnfield** [comment]
Do you have a C++11 compiler installed on your OS?  Have you tried to reinstall the uws module?

**Comment by iammelvin** [comment]
@dnfield  Hey yes i did install c++ built tools 2015 and set env variable after a long time banging my head i found and fixed the issue just now.There was a binding.gyp file missing in node-gyp which i created manually and then it is now working will set this issue to closed.Thanks for responding.

**Comment by lfernando-silva** [comment]
I reinstalled C++ built tools 2015 and it worked on windows 10.

**Comment by brunolemos** [comment]
I was able to fix this on a mac by doing:

```shell
cd node_modules/uws
npm install
```

**Comment by minhduchua** [comment]
@iammelvin

**Comment by maciossek** [comment]
Dunno if this helps, but I had the same error using Node 10, switched to Node v9 and it works like a charm

**Comment by minhduchua** [comment]
@maciossek
Thx, this helps indeed.
This is because uws v8.14.0, required by the packager, is not compatible with node 10.
In order to use node 10, you can require uws v10.148.0 in devDependencies.
Sorry, I should have come back and posted it earlier, I went so many places to solve this that I forgot half of them posting feedback...
