### ISSUE TITLE
Error: Activity class MainActivity does not exist

### ISSUE THREAD

**Issue by wukakuki** [facebook/react-native#17423]
I'm integration React Native with an existing android project. When I run the project(react-native-cli run-android --no-packager), there is an error: Activity class MainActivity does not exist. However, my android project should start with an activity named HomeActivity instead of MainActivity. Sorry for my bad English. The error for a rookie is very difficult. Thank you!
  

### Is this a bug report?

(write your answer here)
Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.)
Yes

### Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 9.3.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.51.0 => 0.51.0

### Steps to Reproduce

(Write your steps here:)

1.init a react native project with react-native init yourprojectname
2.run npm install
3.go to folder /yourprojectname/android/app/src/main/java/com/yourprojectname/
4.rename MainActivity.java to HomeActivity.java
5.open HomeActivity.java, change class name from MainActivity to HomeActivity
6.go to folder /yourprojectname/android/app/src/main
7.open AndroidManifest.xml, change activity from MainActivity to HomeActivity
8.run react-native run-android

### Expected Behavior

(Write what you thought would happen.)
app install to android device

### Actual Behavior

(Write what happened. Add screenshots!)
an error will jump out
error: Activity class MainActivity does not exist.
<img width="1366" alt="screen shot 2018-01-03 at 10 06 51 am" src="https://user-images.githubusercontent.com/7627497/34507088-dee91526-f06d-11e7-92c7-c6519cb97758.png">

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)
https://drive.google.com/file/d/1L1mMgb-IV185v52HznFNqLINwvlGIPsf/view?usp=sharing
it's a zip file, please extract it.

**Comment by dogbutcat** [comment]
From your zip file, I don't know why your applicationId is com.test, but your package name is com.testwithoutmainactivity, if you did this. Also you changed the default activity entry for react-native-cli to search, so if you want to start the app, you can't use the default command line, you need run this ```react-native run-android --appId com.test --main-activity HomeActivity```. You'd better use same setting cuz there is no difference between customize and default, or you need to have some android native knowledge.

**Comment by wukakuki** [comment]
Thank you very much!! That solve my problem.@dogbutcat

**Comment by HHuiHao** [comment]
ApplicationId is consistent with the package name, or delete it.

```
android/app/build.gradle
defaultConfig {
      applicationId "xxx" 
}
```

**Comment by dccmmtop** [comment]
I also meet the question,but my applicationId is right.
Solve a problem by changing a mobile phone。
this is why ? who can tell me .

**Comment by sgon00** [comment]
@dccmmtop I met the exact same error in `flutter` (NOT react native). Some devices have this error and some don't. I found this issue by google. I think it's something to do with `gradle`. That's why different frameworks have the same error. The reason why? no idea yet.

**Comment by VRuzhentsov** [comment]
@wukakuki  if you use emulator, try `Cold boot`

**Comment by dccmmtop** [comment]
I am back , I resolve  the problem ,hahaha.

adb uninstall "package name"
