### ISSUE TITLE
[StyleSheet] Extending A StyleSheet

### ISSUE THREAD

**Issue by yelled3** [facebook/react-native#1742]
I want to be able to define a component library and be able to share and extend `StyleSheet` definition between components. 

After messing around with `StyleSheet` I came up with the following, somehat hacky solotion:

```js
var StyleSheetRegistry = require('StyleSheetRegistry');

var BigLabelStyleRef = StyleSheet.create({
  label: {
    fontSize: 18,
    padding: 5
  }
});

var RedLabelStyleRef = StyleSheet.create({
  label: {
    color: 'red'
  }
});

var BigLabelStyle = StyleSheetRegistry.getStyleByID(BigLabelStyleRef.label);
var RedLabelStyle = StyleSheetRegistry.getStyleByID(RedLabelStyleRef.label);


var BigRedLabelStyleRef = StyleSheet.create({
  label: {
    ...BigLabelStyle,
    ...RedLabelStyle,
    fontSize: 24
  }
});

var BigRedLabelStyle = StyleSheetRegistry.getStyleByID(BigRedLabelStyleRef.label);
```

```js
BigRedLabelStyle
 Object {fontSize: 24, padding: 5, color: "red"}
```

this is a lot of boilerplate for something fairly simple.
ideally I would like to be able to do:

```js
var BigLabelStyle = StyleSheet.create({
  label: {
    fontSize: 18,
    padding: 5
  }
});

var RedLabelStyle = StyleSheet.create({
  label: {
    color: 'red'
  }
});


var BigRedLabelStyle = StyleSheet.create({
  ...BigLabelStyle,
  ...RedLabelStyle, 
  label: {
    fontSize: 24
  }
});

/**
 * BigRedLabelStyle
 Object {fontSize: 24, padding: 5, color: "red"}
 */
```

I don't think I should even be aware of the `StyleSheetRegistry` when working with `StyleSheet` - it's just an implementation detail...

one simple solution is to add a getting to `StyleSheet` that fetches the style hash (same as I did)
so you can do:
```js
var BigLabelStyleRef = StyleSheet.create({
  label: {
    fontSize: 18,
    padding: 5
  }
});

var styleDict = BigLabelStyleRef.get('label')
// OR
var styleDict = BigLabelStyleRef.label.getRaw()
```

Thoughts?

**Comment by ide** [comment]
Great to see exploration in this area... I think we can make writing stylesheets better in a bunch of ways.
 
For this specific use case, you could omit the `StyleSheet.create` calls from the styles you want to share so that they remain plain JS objects. RN will happily accept them without the `StyleSheet.create` wrapper, at some cost to performance because you then would be sending JSON-encoded objects instead of a single stylesheet ID from JS to native.

Another approach would be to let `StyleSheet.create` accept multiple arguments so you could write:
```js
StyleSheet.create(
  BigLabelStyle,
  RedLabelStyle,
  {
    label: {
      fontSize: 18,
      padding: 5
    }
  },
);
```

The nice thing is that you could implement this entirely in user space without modifying RN. In fact I encourage you to do that (ex: set up a project called MultiStyleSheet) to explore and learn how useful new techniques like this are.

**Comment by JohnyDays** [comment]
It's an implementation detail yes, but the reason it's used is to avoid serializing the entire style object through the bridge every time you render any component with a style. It might be annoying or even look unnecessary, but your users will thank you for the performance. I do think it would be cool to support the following (and maybe feasible)

````javascript
var BigLabelStyle = StyleSheet.create({
  label: {
    fontSize: 18,
    padding: 5
  }
});

var RedLabelStyle = StyleSheet.create({
  label: {
    color: 'red'
  }
});


var BigRedLabelStyle = StyleSheet.create({
  label: [
    BigLabelStyle.label, 
    RedLabelStyle.label,
    {
      fontSize: 24
    }
});

````

Does this make sense?

**Comment by JohnyDays** [comment]
And in the same vein as @ide's proposal, maybe this would be easier (and more consistent with the current style prop api)
````javascript
var BigRedLabelStyle = Stylesheet.create([
  BigLabelStyle,
  RedLabelStyle,
  {
    fontSize: 24
  }
])
````

**Comment by yelled3** [comment]
@ide 
> I think we can make writing stylesheets better in a bunch of ways.

what other issues have you encountered?

> In fact I encourage you to do that (ex: set up a project called MultiStyleSheet) to explore and learn how useful new techniques like this are.

will do :-)

**Comment by yelled3** [comment]
@JohnyDays 
The issue with you're last suggestion is that it assumes that `BigLabelStyle` and `RedLabelStyle` both have a **single** key (e.i `label`)

if we change the create interface to specify a single key, the maybe it would work:
```js

var BigLabelStyle = StyleSheet.create('big_label', {
    fontSize: 18,
    padding: 5
});

var RedLabelStyle = StyleSheet.create('red_label', {
    color: 'red'
});

var BigRedLabelStyle = Stylesheet.create('big_red_label', [
  BigLabelStyle,
  RedLabelStyle,
  {
    fontSize: 24
  }
])
```
then you can just pass it directly to the view
```js
<Text style={BigRedLabelStyle}>...</Text>
```

**Comment by JohnyDays** [comment]
I actually forgot the label:{fontSize} in my last comment, it would actually be
````javascript
var BigRedLabelStyle = Stylesheet.create([
  BigLabelStyle,
  RedLabelStyle,
  {
    label:{
      fontSize: 24
    }  
  }
])
````

**Comment by brentvatne** [comment]
Closing because inactivity
