### ISSUE TITLE
Image flickering and loading times on re-render / inside animated component.

### ISSUE THREAD

**Issue by danmatthews** [facebook/react-native#17446]
### Is this a bug report?

Yes, i believe so. Related to either asset loading or performance.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

```
Environment:
  OS: macOS High Sierra 10.13.1
  Node: 8.9.1
  Yarn: 1.3.2
  npm: 5.5.1
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: https://github.com/expo/react-native/archive/sdk-23.0.0.tar.gz => 0.50.3
```

### Steps to Reproduce

Create an `<Image />` housed inside an animated `TouchableOpacity`, then have the Image rendered be dependent on a state property - in this case to toggle between male and female icons on a custom toggle control.

I have @1x (no prefix) @2x and @3x versions of the icons, sized *exactly* right for the control - no resizing is taking place using `style` or otherwise.

### Expected Behavior

After an initial loading flash (expected), toggling between the two icons (i.e. a re-render) should not cause a delay before showing the other icon.

You can see it works pretty quickly to switch in the Snack demo.

### Actual Behavior

As you can see, any re-render triggers a flash where the image is empty, these are tiny images that have been loaded before, so i thought they'd perhaps remain in memory without having to re-request them from the filesystem (i'm assuming that's what the delay is caused by here).

First flicker is caused by tapping the user error banner (which causes a re-render). Second and onwards you see is caused by toggling the switch, which fires `setState` when tapped.

This doesn't happen even on Ionic applications - the first time the image is loaded, it is cached by the browser, and doesn't need to be refreshed again.

![screenflow](https://user-images.githubusercontent.com/149426/34568730-a19ec138-f15e-11e7-9e42-88e1daaec9aa.gif)

### Reproducible Demo

Strangely enough, this snack demo works exactly how it should using the same code as mine - is it simply that the asset loading on my local version (expokit, ejected), takes longer to load the assets?

If you set the state change to happen after the animation (in the callback), it can take up to a full second to load the icon.

https://snack.expo.io/SyEgZnsXM

**Comment by danmatthews** [comment]
Marking this as closed as it appears to be an issue with Expo and development mode - once the app is published and assets are cached, it's no longer an issue.

**Comment by JoseIgnacio92** [comment]
The problem is the library ("fresco") that uses react-native to render images in android. You must use cover in resizeMode
