### ISSUE TITLE
<ImageBackground /> onLoad and onLoadEnd not firing

### ISSUE THREAD

**Issue by ikots** [facebook/react-native#17440]
### Is this a bug report?

yes

### Environment

Environment:
  OS: macOS High Sierra 10.13.1
  Node: 6.11.1
  Yarn: Not Found
  npm: 4.6.1
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.51.0 => 0.51.0

### Steps to Reproduce

1. Create component <ImageBackground source={...} onLoad={() => console.log('loaded!')} />
2. This callback should fire, as according to the docs, ImageBackground accepts the same props as Image, but it's not firing.

### Expected Behavior

See 'loaded!' in the console

### Actual Behavior

Console is clear. This makes it impossible to check when image is ready, so to fire layout animation right after the image is being loaded.

**Comment by Ajith-Pandian** [comment]
@ikots I've checked with following versions.
```js
 "react": "16.0.0",
 "react-native": "0.51.0"
`````
I'm not able to find any problem. "loaded!" is printing. Please check your code again.

The snippet that I used,
````  
<View
      style={{
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#F5FCFF"
      }}
    >
      <ImageBackground
        style={{
          width: 500,
          height: 300,
          position: "absolute",
          top: 0,
          bottom: 0,
        }}
        source={{
          uri:
            "http://paulryan.com.au/wp-content/uploads/2015/01/high-resolution-wallpapers-25.jpg"
        }}
        onLoad={() => console.log("loaded!")}
      />
    </View>
````

**Comment by ikots** [comment]
After rebuilding the project the issue disappeared. Strange, but in any case closing the issue.
