### ISSUE TITLE
[Flexbox] How to properly wrap text elements when mixed with image elements

### ISSUE THREAD

**Issue by janmonschke** [facebook/react-native#1744]
Hey,

I was looking for a trick to make a group of Text elements that are mixed with Image elements (for icons in text) wrap as if they were normal Text elements.

![screen shot 2015-06-25 at 16 08 00](https://cloud.githubusercontent.com/assets/68591/8356226/6353dbda-1b54-11e5-9e3c-5885d570b9b3.png)
For the example app see: <https://rnplay.org/apps/PRQO0Q>

The text does not wrap.

If I set the container's `flexWrap` to `wrap` it cuts off the line, rather then wrapping the elements:

![screen shot 2015-06-25 at 16 09 34](https://cloud.githubusercontent.com/assets/68591/8356272/9a6ec7d8-1b54-11e5-8f20-4dd732b68f3a.png)

What would you recommend in this case? Use an icon-font?

**Comment by udfalkso** [comment]
@janmonschke Did you ever find a solution to this issue?  I'm running into something similar when trying to turn web urls inside a paragraph of text into tappable links.  Thanks!

**Comment by yuriyvl** [comment]
@janmonschke Same here - please respond if you found a way around...  Thank you in advance!

**Comment by sospartan** [comment]
@janmonschke @udfalkso @yuriyvl
Is these icons included in some iconic font ? If so ,you should just use these iconic font . Check this out  https://github.com/sospartan/react-native-iconic-font

**Comment by ide** [comment]
On iOS I believe Images within Text are now supported.

From a practical standpoint I am going to use a custom icon font for Android. It's simple and should work well.

**Comment by yuriyvl** [comment]
@sospartan - thanks for pointing out the iconic font!  But unfortunately it does not fit my use case.  In fact I was hoping I could place any image of my choice along side the text.

@ide -  We do have a working solution with a custom native implementation (we could bridge that class over).  But I was wondering if there is a "React Native way" for this, so we don't have to resort to custom modules.

**Comment by bestander** [comment]
@facebook-github-bot stack-overflow
