### ISSUE TITLE
[MapView] lacks support for custom annotation views

### ISSUE THREAD

**Issue by jwyld** [facebook/react-native#1745]
I've looked at various ways of doing this.  Using simple overlays of views for the annotations doesn't perform well.  It's easy to see the views are overlays during the map panning.  It would be nice if MapView had a property similar to ListView's renderRow.

**Comment by christocracy** [comment]
+1

**Comment by cyprusglobe** [comment]
+1

**Comment by machard** [comment]
+1

**Comment by brentvatne** [comment]
Not a lot of resources to work on this right now but a PR is certainly welcome!

**Comment by mejackreed** [comment]
+1

**Comment by sahrens** [comment]
Yeah, this would be a nice feature, but unfortunately we don't have any bandwidth to support this right now :(

PR's definitely welcome :)

**Comment by frontvu** [comment]
+1

**Comment by nsainaney** [comment]
+1

**Comment by brentvatne** [comment]
Closing this as we now use [ProductPains](https://productpains.com/product/react-native/) for feature prioritization. Thanks!
