### ISSUE TITLE
Bug report with border and padding

### ISSUE THREAD

**Issue by NikolaBorislavovHristov** [facebook/react-native#17459]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: macOS High Sierra 10.13.2
  Node: 6.11.5
  Yarn: 1.2.1
  npm: 5.5.1
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.51.0 => 0.51.0

Target Platform: Android 5.0.2 and Android 7.1.1

### Steps to Reproduce

1. Copy-paste the template below and try it on android phones with different densities

### Expected Behavior

Render 4 borders with equeal size.

### Actual Behavior

Render 4 borders with different size or no borders.

Screenshots:
[Samsung A3](https://my.pcloud.com/publink/show?code=XZFubp7ZjB95RdAwxRf5T5zNczMj8V2M9rJk)
[OnePlus5](https://my.pcloud.com/publink/show?code=XZ1ubp7Zonhl1klvV78MiFk6jPX4vfnUhxtV)

### Reproducible Demo

```jsx
<ScrollView style={{flex: 1,backgroundColor: 'white'}}>
  <View style={{flexDirection: 'row'}}>
    <View style={{margin: 2, width: 110, height: 109, backgroundColor: 'red', padding: 1}}>
      <View style={{flex: 1, backgroundColor: 'yellow'}}/>
     </View>
     <View style={{margin: 2, width: 110, height: 110, backgroundColor: 'red', padding: 1}}>
       <View style={{flex: 1, backgroundColor: 'yellow'}}/>
     </View>
     <View style={{margin: 2, width: 110, height: 111, backgroundColor: 'red', padding: 1}}>
        <View style={{flex: 1, backgroundColor: 'yellow'}}/>
     </View>
   </View>
   <FlatList 
     data={[1, 2, 3]}
     renderItem={() => 
       <FlatList horizontal={true} data={[1, 2, 3, 4, 5, 6, 7]}
         renderItem={() => <View style={{margin: 2, width: 110, height: 169, backgroundColor: 'yellow', borderWidth: 0.5, borderColor: 'red'}}><View style={{flex: 1, backgroundColor: 'yellow'}} /></View>}
         />
        }
      />
</ScrollView>
```

**Comment by maxim-c** [comment]
workaround that i find for now: padding: PixelRatio.roundToNearestPixel(1),

**Comment by NikolaBorislavovHristov** [comment]
Thank you. This workaround solves my problem.

**Comment by wcandillon** [comment]
Is this really an issue? The documentation at https://facebook.github.io/react-native/docs/pixelratio.html seems to state that this would be the expected behaviour.

I would be curious to understand is why `roundToNearestPixel()` is not used by default everywhere? It feels like we use it for every dp values in our app when we set a float value as dimension or the pixel density of the device is a float.
