### ISSUE TITLE
react-native link react-native-fbsdk not working in Windows with Android Studio

### ISSUE THREAD

**Issue by nicoara** [facebook/react-native#17451]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: Windows 8.1
  Node: 8.1.3
  Yarn: 1.3.2
  npm: 4.6.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  2.3.0.0 AI-162.3871768

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.51.0 => 0.51.0

Target Platform: Windows, Android Studio 2.3.1

### Steps to Reproduce

1. >react-native init demoapp1
2. >cd demoapp1
3. >react-native install react-native-fbsdk
Scanning folders for symlinks in C:\Users\nicoara\Desktop\demoapp1\node_modules
(42ms)
rnpm-install info Module react-native-fbsdk has been successfully installed & li
nked
4. >react-native link react-native-fbsdk
Scanning folders for symlinks in C:\Users\nicoara\Desktop\demoapp1\node_modules
(38ms)
{ Error: Cannot find module 'C:\Users\nicoara\Desktop\demoapp1\node_modules\reac
t-native-fbsdk\package.json'
at Function.Module._resolveFilename (module.js:485:15)
at Function.Module._load (module.js:437:25)
at Module.require (module.js:513:17)
at require (internal/module.js:11:18)
at getRNPMConfig (C:/Users/nicoara/Desktop/demoapp1/node_modules/react-nativ
e/local-cli/core/index.js:52:3)
at Object.getDependencyConfig (C:/Users/nicoara/Desktop/demoapp1/node_module
s/react-native/local-cli/core/index.js:90:18)
at deps.reduce (C:/Users/nicoara/Desktop/demoapp1/node_modules/react-native/
local-cli/link/getDependencyConfig.js:9:24)
at Array.reduce (native)
at getDependencyConfig (C:/Users/nicoara/Desktop/demoapp1/node_modules/react
-native/local-cli/link/getDependencyConfig.js:6:15)
at Object.link (C:/Users/nicoara/Desktop/demoapp1/node_modules/react-native/
local-cli/link/link.js:180:24) code: 'MODULE_NOT_FOUND' }
5.  When adding the following line in Android Studio in MainApplication.java: 'import com.facebook.FacebookSdk', Android Studio does not recognize FacebookSdk

### Expected Behavior

Those are the exact steps from the official documentation at https://developers.facebook.com/docs/react-native/getting-started.
I expected to install the Facebook SDK. I want to do a login in a React Native project.

(Write what you thought would happen.)

### Actual Behavior

The errors are above in steps 4 and 5 

### Reproducible Demo

https://www.dropbox.com/s/iy9ppsydw15h028/demoapp1.zip?dl=0

**Comment by nmerchant** [comment]
+1

Running into this when following the documentation exactly.  

Windows 10
npm v3.8.6
node v6.0.0
react v16.2.0
react-native v0.52.0

**Comment by Duverney** [comment]
+1

Windows 10
npm v5.6.0
node v9.4.0
react v16.2.0
react-native v0.52.0

**Comment by nmerchant** [comment]
I was able to get around this by doing `npm install react-native-fbsdk` instead of `react-native install react-native-fbsdk`.  It appears that `react-native install` doesn't actually do anything, despite the output indicating it was installed successfully...nothing is installed to the node_modules folder.

**Comment by xemasiv** [comment]
Can confirm what @nmerchant said.

* No entries in my package json.
* Nothing too in my node_modules

Fixed with:

```
npm install react-native-fbsdk --save
react-native link
```

**Comment by wmendes** [comment]
I am having this problem. Any development on this?

**Comment by NULL-SWEAT** [comment]
I'm on v0.55.3 and I can confirm that using `react-native install react-native-fbsdk` does NOT work.

**Comment by Surender-Suhag** [comment]
+1 (v0.55.4)

**Comment by AfamO** [comment]
I am encountered the same error on 
windows 10
node 8.11.1
npm 6.2.0
react 16.3.1
react-native-0.55.4.


However mine was fixed when I used ` npm install react-native-fbsdk`  instead of `react-native install react-native-fbsdk`
