### ISSUE TITLE
Swift module with 0.6.0-rc

### ISSUE THREAD

**Issue by nicinabox** [facebook/react-native#1746]
I'm getting the following error with the snippet below. As far as I can tell this is how the docs say wire a Swift module. What am I missing?

> Unknown argument type 'NSObject' in method -[SocketIO emit:items:]. Extend RCTConvert to support this type.

```ObjC
# SocketBridge.m
#import "RCTBridgeModule.h"

@interface RCT_EXTERN_MODULE(SocketIO, NSObject)

RCT_EXTERN_METHOD(emit:(NSString*)event items:(NSObject*)items)

@end
``

**Comment by nicklockwood** [comment]
Sorry about that - I forgot to add NSObject as a supported RCTConvert type.

It's generally better to be specific about the type, so use NSArray, NSDictionary, or whatever the actual type is. But if you aren't sure, or it's a mixed type (i.e. could be several different types) then use id, like this:

    RCT_EXTERN_METHOD(emit:(NSString*)event items:(id)items)

**Comment by nicinabox** [comment]
:boom: `items:(id)items` does the trick. Thanks for the tip @nicklockwood!
