### ISSUE TITLE
FlatList Android issue with horizontal scrolling  and pagingEnabled

### ISSUE THREAD

**Issue by waubau** [facebook/react-native#17466]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

    "expo": "^24.0.2",
    "react": "16.0.0",
    "react-native": "0.51.0",

Android and IOS of the latest versions. 
Development environment is not relevant to this bug.

### Steps to Reproduce

Issue is with **FlatList** with **pagingEnabled** and **horizontal** scrolling. Please see the **video** below.

### Expected Behavior

When horizontally  scrolling the FlatList with pagingEnabled in Android if the last page is less than the page width, that page bounces back. Expectation is that the last page is shown.

IOS works as expected showing the last page.

### Actual Behavior
There are two ways you can scroll the flatList
1. scrolling by finger sliding gesture
2. scrolling by pressing the button and calling e.g.`scrollToIndex` function.

Both scrolling methods works differently in IOS and Android
method 1. IOS adjusts the page to the last content and Androing bounces back (See the video)
method 2. IOS shows full page letting empty space. Android adjusts the page tho the last content. This potentially is OK but would be nice if both platforms worked similar. 

### Reproducible Demo

**IOS** behavior video https://youtu.be/K_pSy6AMi1Y
**Android** behavior video https://youtu.be/o0f-vSi9abw

Watch for the last last card dated 15 jan 2018

Github repo is here https://github.com/waubau/weather 

The FlatList code is below for your convinience
```
const width = Dimensions.get('window').width;
const moveValue = 3;

class ForecastCardList extends Component {
  scrollToRight = () => {
    const { increaseIndex, weather: { currentIndex } } = this.props;
    increaseIndex(moveValue);
    this.flatListRef.scrollToIndex({ animated: true, index: currentIndex + moveValue });
  };

  scrollToLeft = () => {
    const { decreaseIndex, weather: { currentIndex } } = this.props;
    decreaseIndex(moveValue);
    const scrollIndex = (currentIndex - moveValue > 0) ? currentIndex - moveValue : 0;
    this.flatListRef.scrollToIndex({ animated: true, index: scrollIndex });
  };

  handleScroll = (event) => {
    const { setIndex } = this.props;
    const scrollIndex = Math.ceil(event.nativeEvent.contentOffset.x / width * moveValue);
    setIndex(scrollIndex);
  };

  render() {
    const { weather: { weatherForecast, currentIndex, forecastLength, isFahrenheit } } = this.props;
    const weatherCard = weatherForecast.map(item => (
      <ForecastCardSingle key={item.date} item={item} isFahrenheit={isFahrenheit} />
    ));

    const arrowLeft = (currentIndex > 0)
      ? (<TouchableOpacity style={styles.touchableArea} onPress={this.scrollToLeft}>
        <Image style={styles.arrow} source={require('../../assets/arrow_left_white.png')} />
      </TouchableOpacity>)
      : <Text />;

    const arrowRight = (currentIndex < forecastLength - moveValue)
      ? (<TouchableOpacity style={styles.touchableArea} onPress={this.scrollToRight}>
        <Image style={styles.arrow} source={require('../../assets/arrow_right_white.png')} />
      </TouchableOpacity>) : <Text />;

    return (
      <View style={styles.container}>
        <View style={styles.buttonContainer}>
          {arrowLeft}
          {arrowRight}
        </View>
        <FlatList
          ref={(ref) => {
            this.flatListRef = ref;
          }}
          data={weatherCard}
          renderItem={({ item }) => item}
          onMomentumScrollEnd={this.handleScroll}
          horizontal
          pagingEnabled
        />
      </View>
    );
  }
}
```

**Comment by ouabing** [comment]
same here
