### ISSUE TITLE
[Docs] The <title> on every published documentation page is identical

### ISSUE THREAD

**Issue by cdzombak** [facebook/react-native#1747]
The `<title>` for every page of [the published React Native documentation](http://facebook.github.io/react-native/docs/getting-started.html) is identical:

`<title>React Native | A framework for building native apps using React</title>…<meta property="og:title" content="React Native | A framework for building native apps using React">`

For obvious reasons, this is not helpful or accessible.

![screen shot 2015-06-25 at 14 38 10](https://cloud.githubusercontent.com/assets/102904/8362700/6fb17312-1b48-11e5-836a-48f60586dc36.png)

**Comment by brentvatne** [comment]
Good point! Can you submit a PR to fix this? Would be much appreciated

**Comment by christopherdro** [comment]
This is still limited since the docs for components and api's are handled differently. 
Works with existing .md files inside of the /docs folder.

**Comment by brentvatne** [comment]
@christopherdro - nice! can you submit a PR with that?

**Comment by browniefed** [comment]
@brentvatne @ide this looks like it is fixed.
