### ISSUE TITLE
Android Permissions are not working for Android

### ISSUE THREAD

**Issue by AugustoAleGon** [facebook/react-native#17470]
### Is this a bug report?

(write your answer here)
Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.)
Yes. I have read it.
### Steps to Reproduce

(Write your steps here:)

1. First Step is when your application is running you want to use the Android Permissions provide by React Native. So you basically you have to put this code (example code):

import { PermissionsAndroid } from 'react-native';

```
async function requestCameraPermission() {
  try {
    const granted = await PermissionsAndroid.request(
      PermissionsAndroid.PERMISSIONS.CAMERA,
      {
        'title': 'Cool Photo App Camera Permission',
        'message': 'Cool Photo App needs access to your camera ' +
                   'so you can take awesome pictures.'
      }
    )
    if (granted === PermissionsAndroid.RESULTS.GRANTED) {
      console.log("You can use the camera")
    } else {
      console.log("Camera permission denied")
    }
  } catch (err) {
    console.warn(err)
  }
}
```
2.
3.

### Expected Behavior
Application just take permissions.

(Write what you thought would happen.)

### Actual Behavior
 Android Application crash.

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by hawkup** [comment]
I reproduce follow permissionAndroid example, It works correctly no crash on Android.
This is my reproduce repo [link](https://github.com/hawkup/react-native-permission-android-example).

**Environment**
OS: macOS Sierra 10.12.6
Node 9.2.0
Yarn 1.3.2
Watchman: 4.9.0
Android Studio: 2.3.3

**Comment by Rewieer** [comment]
Still happening under RN 0.54.0.

**Comment by SeamusY** [comment]
@AugustoAleGon 
async function requestCameraPermission() {
  try {
    const granted = await PermissionsAndroid.request(
      PermissionsAndroid.PERMISSIONS.CAMERA,
      {
        'title': 'Cool Photo App Camera Permission',
        'message': 'Cool Photo App needs access to your camera ' +
                   'so you can take awesome pictures.'
      }
    ) <--- This shouldn't be here...
    if (granted === PermissionsAndroid.RESULTS.GRANTED) {
      console.log("You can use the camera")
    } else {
      console.log("Camera permission denied")
    }
  } catch (err) {
    console.warn(err)
  }
}

**Comment by mepritam** [comment]
Faced the same problem .

My Code : 
` import { PermissionsAndroid } from 'react-native';`
`export async function requestCameraPermission() `
`{`
 ` try {`
    `const granted = await PermissionsAndroid.request(`
      `PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION,`
      `{`
       ` 'title': 'Example App',`
       ` 'message': 'Example App access to your location '`
     ` }`
   `)`
    `if (granted === PermissionsAndroid.RESULTS.GRANTED) {`
     ` console.log("You can use the location")`
     ` alert("You can use the location");`
    `} else {`
     ` console.log("location permission denied")`
      `alert("Location permission denied");`
   ` }`
 ` } catch (err) {`
    `console.warn(err)
 ` }`
`}`

` async componentWillMount() {`
    `await requestCameraPermission()`
   ` }`

**SOLUTION:**
Allow your app on **Draw over other app** (Inside Settings-> Apps)
http://i.imgur.com/rdUzj0w.gif
