### ISSUE TITLE
[SectionList] scrollToLocation scrolls past content on iOS

### ISSUE THREAD

**Issue by Jpunt** [facebook/react-native#17479]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: macOS High Sierra 10.13.2
  Node: 8.2.1
  Yarn: 0.27.5
  npm: 5.3.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.2.0 => 16.2.0
  react-native: ^0.51.0 => 0.51.0

### Steps to Reproduce

Implement a `SectionList` and use `scrollToLocation` to scroll to the last section.

### Expected Behavior

It scrolls to the last section, while making sure it doesn't scroll past the content. On Android this works as expected: 

![screen shot 2018-01-08 at 11 54 05](https://user-images.githubusercontent.com/190501/34667961-909e16ee-f46b-11e7-8a5d-0e7cfdd0b6c1.png)

### Actual Behavior

On iOS `scrollToLocation` scrolls to far:

![img_362ddaf36c23-1](https://user-images.githubusercontent.com/190501/34668105-2be376d0-f46c-11e7-889a-d7f49aaaf28a.jpeg)

This also introduces some weird issues when the user starts scrolling from there on.

### Reproducible Demo

[https://snack.expo.io/HJgTyClEG](https://snack.expo.io/HJgTyClEG)

**Comment by sahanay** [comment]
This would be very helpfull!

**Comment by Jpunt** [comment]
No, this is not fixed in 0.53. New issue: https://github.com/facebook/react-native/issues/18098
