### ISSUE TITLE
Fetch never times out.

### ISSUE THREAD

**Issue by mannol** [facebook/react-native#17483]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: Linux 4.10
  Node: 6.12.3
  Yarn: Not Found
  npm: 3.10.10
  Watchman: Not Found
  Xcode: N/A
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.0.0-alpha.12 => 16.0.0
  react-native: ^0.48.3 => 0.51.0

### Steps to Reproduce

The necessary steps involve a remote-end server or a configurable router.

1. Use `fetch()` call to issue a http request to a remote server; The request is successful.
2. Shutdown a remote server or turn off your router (or walk out of range of the router).
3. Use `fetch()` call again to issue a http request to a remote server; The fetch then reuses the existing connection causing it to resolve only after a very long time (like 30 minutes or so).

### Expected Behavior

`fetch()` should reject the promise after a short amount of time.

### Actual Behavior

`fetch()` is configured to reuse existing connections from the connection pool, causing it to resolve only after a very long time (like 30 minutes or so) in the case when the connection has timed-out.
The issue is usually experienced on a long-running app (on android) when user has the app **hidden** or **screen locked** soon after issuing a successful `fetch()` call(s). If the user returns to the app in a shorter period of time (usually less than 15 minutes) and their connection is poor, they will experience a said behaviour on a next `fetch()` call. 

The issue can also be observed with loading Images. If there happens to be an `Image` that has a remote source on the same host and it hasn't been loaded before the app being paused(usually observed with FlatList), the image will never load after user returns to the app.

### Proposed solution

Add `timeout` property for `fetch()` and a default, small, timeout for Image network component.

### What we did for our project

We used [react-native-fetch-blob](https://github.com/wkh237/react-native-fetch-blob) as a replacement for built-in `fetch()` API. We then set the timeout property for each `fetch()` call which solves the first issue.

As for images; we used [react-native-cached-image](https://github.com/kfiroo/react-native-cached-image) and modified [config](https://github.com/kfiroo/react-native-cached-image/blob/master/utils/fsUtils.js#L97) to have a short 10s timeout and added a quick retry [here](https://github.com/kfiroo/react-native-cached-image/blob/master/utils/fsUtils.js#L123) in case of a timeout.

### Reproducible Demo

I'm sorry, the issue requires remote non-react-native resources or some physical work to reproduce so the reproducible demo including those resources is very hard to make.

**Comment by alien3d** [comment]
I do testing yesterday new update..  IOS seem quick to respond network failure while android a bit around 3 minute..
