### ISSUE TITLE
[TextInput] Defocussing via JS

### ISSUE THREAD

**Issue by PhilippKrone** [facebook/react-native#1748]
Hi,

is there any possibility to de-focus a textinput component? I see the function blurTextInput() in TextInputState, but I'm not sure whether that should be used. Basically I'm trying to build a SearchBar and can't use react-native-search-bar for some reasons.

Regards
Philipp

**Comment by brentvatne** [comment]
`this.refs.textInputRefHere.blur()`

**Comment by PhilippKrone** [comment]
doh! :)

**Comment by brentvatne** [comment]
:smile:
