### ISSUE TITLE
Linking.openURL behavior is not consistent with documentation

### ISSUE THREAD

**Issue by jaycanty** [facebook/react-native#17484]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Steps to Reproduce

(Write your steps here:)

1. Click button that calls `Linking.openURL`
2. Wait for `Confirm/Cancel` popup
3. Press `Cancel`

### Expected Behavior

Expect: `Linking.openURL` should reject

### Actual Behavior

Actual: `Linking.openURL` resolves

### Reproducible Demo

Steps to recreate:

- `react-native init LinkTest`
- In App.js render add;
```
        <TouchableOpacity onPress={this.onPress}>
          <Text>
            Link
          </Text>
        </TouchableOpacity>
```
and in App class;
```
  onPress = () => {
      const link = 'tel:2125551212'
      Linking.openURL(link)
          .then(() =>  {
              console.log('CONFIRM')
          })
          .catch(() => {
              console.log('CANCEL')
          })
  }
```

No repo included due to this needing to be run on a device to test

**Comment by treemore** [comment]
i was test in react-native 0.55.3 and 0.55.4 .  and i am sure Linking.openURL behavior is not consistent with documentation  .
whenever your choice confirm or cancel . the promise resolve will be done .

**Comment by TNicholson11** [comment]
Anyone have a fix or workaround for this? I'm also in need of the callback from the Confirm/Cancel system dialog.

**Comment by guojindai** [comment]
this issuer still exists in 0.57.5

**Comment by Zvukamar** [comment]
+1
