### ISSUE TITLE
[New Component Test Request] Better performance than FlatList/SectionList

### ISSUE THREAD

**Issue by bolan9999** [facebook/react-native#17490]
Hello, everyone. Share my large data source list component, Its performance is much better than FlatList/SectionList, I invite anyone to help me to test it and improve it.

## react-native-largelist

https://github.com/bolan9999/react-native-largelist

## Features

* Much better performance than FlatList and SectionList. Item reused, lower CPU/Memory usage.
* Large data source supported, infinite data supported, super fast sliding support.
* Full cross-platform. Improved from ScrollView, good version compatibility with react-native
* Sticky Section support.
* Callback when Cell/Item enter/leave the safeArea support.
* List header/footer/empty component support.
* Better swipe out to edit Cell.
* Pull to Refresh and Scroll loading more.
* Scroll loading more custom view support, all data source load completed custom view support.
* Dynamic variable support, for example: size, contentOffset, currentSection, contentSize, height of Header/Footer, visibleIndexPaths and so on.
* Scroll to offset or index path.
* Reload data.
* Custom optimize parameters.
* More callbacks or dynamic variable can be added through a new issue.

Star me please if it is useful for you. I'll contribute it to react-native if it is useful for most developers. 

Forgive me for my poor English,thank you!

**Comment by gao520sun** [comment]
heightForCell 为什么是固定的呢
