### ISSUE TITLE
[UIManager] "Attempted to measure layout but offset or dimensions were NaN" in UIExplorer

### ISSUE THREAD

**Issue by ide** [facebook/react-native#1749]
Running the June 24 master (e81e29f9282bf8) in Xcode 6.3 with iPhone 6 sim. I have a clean checkout (git clean -dfx) and upon launching the UIManager get a redbox with "Attempted to measure layout but offset or dimensions were NaN" because the width and height are NaN.

@brentvatne is able to repro too. Cleaning the project didn't help either on the off chance that it might have.

**Comment by ide** [comment]
@sahrens I bisected this to 5b476d0e41914372e1c53

**Comment by ide** [comment]
@brentvatne pointed out that the tests shouldn't have passed. Should `RCTLogError` calls mean automatic test failure (except in tests that expect intentional errors)?

**Comment by brentvatne** [comment]
Travis link for convenience: https://travis-ci.org/facebook/react-native/builds/68349816

**Comment by frantic** [comment]
`RCTLogError` calls RedBox which should fail the test, I'm not sure why it didn't happen this time...

**Comment by sahrens** [comment]
Hooking up RCTLogError to fail tests sounds like a good idea.

**Comment by grabbou** [comment]
Getting that in MapView atm.
