### ISSUE TITLE
How to map json data with array in react native 

### ISSUE THREAD

**Issue by FarihulR** [facebook/react-native#17508]
I have array like this in react native 

` {
        "id": 17421,
        "title": "LEGO Power Functions 88002 Train Motor",
     
        "items": [
            {
                "id": 17421,
                "product_id": "17421",
                "item_title": "",
                "item_description": "",
                "sku": "88002",
              
                "taxonomies": [
                    {
                        "id": 1186,
                        "cat_id": null,
                        "name": "Black",
                        "excerpt": null,
                        "pivot": {
                            "item_id": "17421",
                            "taxonomy_id": "1186"
                        }
                    },
                    {
                        "id": 2,
                        "cat_id": null,
                        "name": "Brand New",
                      
                        "data": "",
                        "store_data": "",
                        "excerpt": null,
                        "pivot": {
                            "item_id": "17421",
                            "taxonomy_id": "2"
                        }
                    }
                ],
                "medias": []
            },
            {
                "id": 69882,
                "product_id": "17421",
                "item_title": "",
             
                "trigger_inventory": "",
                "taxonomies": [],
                "medias": []
            },
            {
                "id": 69883,
                "product_id": "17421",
                "item_title": "",
                "item_description": "",

                "medias": []
            }
        ],
        "medias": []
    },`

Here Source code 
`import React, { Component } from 'react';
import { Text } from 'react-native';
import { Content, Card, CardItem, Body } from 'native-base';
import AppBodyData from './AppBodyData';

export default class AppBody extends Component{
	constructor(){
		this.state = {
			data: []
		}
	}

	ambilData(){
		console.log('req list product');
		fetch("http")
		.then((response) => response.json())
		.then((responseJson) => {
			console.log(responseJson);
			this.setState( { data: responseJson });

		})
		.catch((error) => {
			console.error(error);
		});
	}

	componentDidMount() {
		this.ambilData();
	}

	render(){
		return (
			<AppBodyData data={this.state.data} />
		);
	}

}`

`export default class AppBodyData extends Component {

    constructor(props){
        super(props);
        this.toProductDetail = this.toProductDetail.bind(this);
        // console.log('app body data constructor');
    }

    toProductDetail(dataku){
        // console.log('product clicked');
        console.log(dataku);
        Actions.DetailProduct({product: dataku});
    }

    render() {
        var ini = this;
        let isi = this.props.data.map(function (DataPopitoi, index) {
            return (
                <Card key={index}>
                    <CardItem cardBody button={true} onPress={() => {ini.toProductDetail(DataPopitoi)}} >
                        <Image source={{ uri: 'http://lab.hellomorra.com/popitoi-warehouse/images/main.jpg' }} style={{ height: 200, width: null, flex: 1 }} />
                    </CardItem>

                    <CardItem>
                        <Text>
                            Item name
                       </Text>
                        <Body>
                            <Text>
                                SKU : {DataPopitoi.items[0].sku}
                            </Text>
                        </Body>
                    </CardItem>

                    <CardItem>

                        <Left>
                            <CheckBox checked={true} />
                            <Body>
                                <Text>Brand New</Text>
                            </Body>

                        </Left>
                        <Right>
                            <Text>{DataPopitoi.items[0].stock_available}</Text>
                        </Right>
                    </CardItem>

                    <CardItem>
                        <Left>
                            <CheckBox checked={false} />
                            <Body>
                                <Text>Demaged</Text>
                            </Body>

                        </Left>
                    </CardItem>

                </Card>
            )
        });

        return (
            <Content>
                {isi}
            </Content>
        );

    }
}
`

How to read items.sku on array josn ?
-- | --

### Is this a bug report?

(write your answer here)

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.)

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by Lxxyx** [comment]
I think this is not an issue or bugs about react native, you should ask it in stackoverflow.

**Comment by Taym95** [comment]
Stackoverflow bro ;)

**Comment by lwinkyawmyat** [comment]
@facebook-github-bot stack-overflow

**Comment by johnreytanquinco** [comment]
`items[0].sku`
