### ISSUE TITLE
[RN 0.52] RCTImageLoader requires main queue setup since it overrides `init` but doesn't implement `requiresMainQueueSetup`

### ISSUE THREAD

**Issue by fungilation** [facebook/react-native#17504]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

```
Environment:
  OS: macOS Sierra 10.12.6
  Node: 9.3.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.0 => 0.52.0
```

### Steps to Reproduce

`$ react-native run-ios`

### Expected Behavior

iOS simulator run without errors.

### Actual Behavior

<img width="487" alt="screenshot 2018-01-09 14 53 14" src="https://user-images.githubusercontent.com/3803466/34747390-edde8370-f54c-11e7-954c-3d7615387bab.png">
<img width="1180" alt="screenshot 2018-01-09 15 02 18" src="https://user-images.githubusercontent.com/3803466/34747677-2fa5ef68-f54e-11e7-886d-b2a592756345.png">

^
```
Module RCTImageLoader requires main queue setup since it overrides `init` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.
```

### Reproducible Demo

Any app using the Image component, although in my app I wrap that in a higher level component I use: `react-native-fit-image`.

I've never seen `RCTImageLoader` complain about `requiresMainQueueSetup` before. Only started now after I upgraded RN from 0.51 to 0.52.

**Comment by rashtay** [comment]
For me, it doesn't show any warning in the simulator but appears as a warning in the browser console.

**Comment by hramos** [comment]
PR #17679 is an attempt to fix this.

**Comment by animaonline** [comment]
Started getting this in 0.54.0, is there a way to actually disable the warning?

This doesn't seem to work:

YellowBox.ignoreWarnings([
  'Warning: Module RCTImageLoader requires',
]);

**Comment by fungilation** [comment]
because the warning has no "warning: " prefix. Take that out in your ignore

**Comment by alzalabany** [comment]
can we merge this soon ?

**Comment by hramos** [comment]
Merged

**Comment by fungilation** [comment]
It'll be included in RN 0.56 I take it?

**Comment by vikrantnegi** [comment]
Still showing up in 0.55.2

**Comment by aqkhan** [comment]
Still showing

**Comment by iRoachie** [comment]
It should be in the next minor (0.56.0), the patch updates(x.x.patch) only fix errors found in the latest minor afaik.

**Comment by watadarkstar** [comment]
Did this actually get fixed?

**Comment by iRoachie** [comment]
It’s merged into master but it’s not released in a version as yet

**Comment by watadarkstar** [comment]
Thanks for the quick reply @iRoachie !

**Comment by courptwayne** [comment]
RCTLog.js:46 Module RCTImageLoader requires main queue setup since it overrides `init` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.

Facing this error!
=> Any solution ?

**Comment by woowalker** [comment]
still showing up in 0.55.4
![image](https://user-images.githubusercontent.com/7894779/40231829-1fc2c8c8-5acf-11e8-935e-c5e5f2547a39.png)

**Comment by bgold0** [comment]
How do we make this go away

**Comment by hramos** [comment]
Fix is in master. You may build React Native from source to take advantage of the fix.
