### ISSUE TITLE
Cannot run this command react-native run-android

### ISSUE THREAD

**Issue by praveenkumar66** [facebook/react-native#17519]
FAILURE: Build failed with an exception.

* Where:
Build file 'D:\SVN Working Repo\Astrology\Astro\android\app\build.gradle' line:1

 What went wrong:
A problem occurred evaluating project ':app'.
> java.lang.UnsupportedClassVersionError: com/android/build/gradle/AppPlugin : U
nsupported major.minor version 52.0

**Comment by androidwt** [comment]
I encountered the same problem right now,a new project just initialized， and i'm sure that my enviorment is correct. the tips just like this:

Total time: 1.916 secs
FAILURE: Build failed with an exception.

* Where:
Build file 'D:\react_native_space\HelloRN\android\app\build.gradle' line: 1

* What went wrong:
A problem occurred evaluating project ':app'.
> com/google/protobuf/MessageOrBuilder

**Comment by androidwt** [comment]
@facebook-github-bot   a new project

**Comment by androidwt** [comment]
@praveenkumar66  did you have any resolution for this problem
