### ISSUE TITLE
Platform.OS returns 'android' when running in iOS device

### ISSUE THREAD

**Issue by rash6795** [facebook/react-native#17518]
### Is this a bug report?
Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?
Yes

### Environment
Environment:
  OS: macOS High Sierra 10.13.2
  Node: 8.9.2
  Yarn: Not Found
  npm: 5.5.1
  Watchman: Not Found
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4408382

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: 0.50.3 => 0.50.3

Target Platform: iOS (8.0)

### Steps to Reproduce

1. Paste below code in your `index.js`
```
componentDidMount() {
        if(Platform.OS === 'ios') {
	       console.log(" ios") 
        } else {
              console.log("android") 
       } 
}
```

2. Enable Remote JS Debugging and check the Console for log

### Expected Behavior

Console Log Output: ios

### Actual Behavior

Console Log Output:

![screen shot 2018-01-10 at 6 14 10 pm](https://user-images.githubusercontent.com/34880490/34773713-b3e51b16-f632-11e7-8558-c3d29161ca8c.png)

Simulator Output:
![screen shot 2018-01-10 at 6 15 34 pm](https://user-images.githubusercontent.com/34880490/34773715-b5c77e2e-f632-11e7-81b4-082c1461f547.png)

checkInitialPermissions is the function to be executed only on android. But its executed on iOS.

### Reproducible Demo
Follow steps to reproduce

**Comment by compojoom** [comment]
Can't reproduce this. Have you run android version of the app before testing in android? Did you close the packager/debugger - this shouldn't matter though.

**Comment by froatsnook** [comment]
Are you sure it's returning `"android"`?  Trying changing it to: `console.log(Platform.OS)`.  Maybe you've imported `Platform` incorrectly?

**Comment by rash6795** [comment]
@froatsnook  yes tried that too it still prints `android `. And the import statement is `import {Platform} from 'react-native'; `

**Comment by rash6795** [comment]
@compojoom  yes android works fine as expected. the same code when i try to run for ios is giving the android output instead of ios output 

I tried `removing the node modules and installing it again` . `Teminated react packager and started all over `.  `Clean & Build` also restarting `xcode ` also didn't help.

**Comment by rash6795** [comment]
Sorry it was my mistake in render method i had given `Platform.OS = 'android'` instead of `Platform.OS == 'android'` so after the render method when the componentDidMount is called the `Platform.OS was assigned as android `
