### ISSUE TITLE
Android release build shows dev menu on shake.

### ISSUE THREAD

**Issue by azeemhassni** [facebook/react-native#17522]
### Is this a bug report?
Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS:  OS X El Capitan 10.11.6
  Node:  9.3.0
  Yarn:  1.3.2
  npm:  5.6.0
  Watchman:  4.9.0
  Xcode:  Xcode 8.2.1 Build version 8C1002
  Android Studio:  Not Found

Packages: (wanted => installed)
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: 0.48.3 => 0.48.3

Target Platform: Android 6 Marshmallow 

### Steps to Reproduce

(Write your steps here:)

1. run `react-native run-android --variant=release`

### Expected Behavior

App should run in your device in release mode.

(Write what you thought would happen.)

### Actual Behavior

The app runs in device but in dev mode. I can still shake the device to open the dev menu.
and JS loads from packager instead of being bundled in the APK.

### Reproducible Demo
None

**Comment by Rizwanilahi** [comment]
+1

**Comment by azeemhassni** [comment]
Closing this because it wasn't a bug in react-native.

The cause for this behaviour was the following method in my `MainApplication.java`.

```java
@Override
public boolean getUseDeveloperSupport() {
     return true;
}
```

I just changed it to

```java
@Override
public boolean getUseDeveloperSupport() {
     return BuildConfig.DEBUG;
}
```

I'm not sure why It was like that but anyways it's fixed now and working as expected.

**Comment by smitthakkar1** [comment]
@azeemhassni thanks for your answer but My `getUseDeveloperSupport` returning the correct part but still it is showing the developer menu when shaking

**Comment by ishiestar** [comment]
@smitthakkar1  check if `debuggable true` is there in the `buildTypes.release` block in your build script (module level build.gradle).
