### ISSUE TITLE
zIndex is not working on android

### ISSUE THREAD

**Issue by kalyanijamunkar10** [facebook/react-native#17536]
### Is this a bug report?

Yes

zIndex is not working on android as it is working on iOs.
### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

yes

### Environment
  Environment:
    OS:  macOS Sierra 10.12.6
    Node: 7.7.3
    Yarn:  0.22.0
    npm:  4.1.2

  Packages: (wanted => installed)
    react-native: 0.49.2
    react: 16.0.0-alpha.12 => 16.0.0-alpha.12

  Target Platform: iOS (10.2)

  ***Make sure you are on v0.48.0 or greater of react-native otherwise, you may get this error:
This is iPhone image :
![screen shot 2018-01-10 at 6 46 45 pm](https://user-images.githubusercontent.com/27677593/34819152-01f34368-f6e3-11e7-8bcc-8fae5b87d9ee.png)
and this is image taken from android:

![screen shot 2018-01-11 at 3 20 09 pm](https://user-images.githubusercontent.com/27677593/34819213-26f50354-f6e3-11e7-93da-096f81dd8b84.png)

This is the my Code: 

      ` var tabs = ['Activity', 'Files', 'People'];
           this.state = {
             tabs
            };
           return (
           <Container style={{backgroundColor: '#F5F5F5'}}>
               <View style={styles.topStrip}>
                  {
                   this.state.tabs.map((tab, index) => (
                      <View key={index} >
                         <TouchableOpacity>
                           <Text style={styles.streamName}>{tab}</Text>
                        </TouchableOpacity>
                      </View>
                   ))
               }
             <View style={{position: 'absolute', backgroundColor: 'transparent', alignItems: 'center', 
                  justifyContent: 'center', zIndex: 5, elevation: 24, marginTop: 15, marginLeft: 300}}>
                 <EIcon size={40} color='#2196f3' name={'circle-with-plus'} />
             </View>
          </View>
          <View style={{zIndex: -1}}></View>
       </Container>
       );
      }
    }
        const styles = StyleSheet.create({
      topStrip: {
       alignItems: 'center',
      },
     streamName: {
        marginTop: 7,
        marginBottom: 6,
        flexDirection: 'row',
        alignSelf: 'center'
      }
    }
    });`

**Comment by cpyle0819** [comment]
I'm still seeing this in v0.53.0.
![screen shot 2018-03-01 at 1 56 57 pm](https://user-images.githubusercontent.com/2723491/36863690-701e83c0-1d58-11e8-8b19-c3e4e76b53d6.png)

**Comment by franj0** [comment]
Environment:
  OS: macOS High Sierra 10.13.5
  Node: 10.1.0
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

Still on andorid not working
left: android, right: iOS

![image](https://user-images.githubusercontent.com/11553585/42128948-f387685e-7cb6-11e8-900e-36d1003dc9a8.png)

**Comment by radjivF** [comment]
same here with version "react-native": "0.55.4", Any help??? elevation is not working either

**Comment by kalyanijamunkar10** [comment]
elevation: 3,
    shadowColor: '#545454',
    shadowOffset: {
      width: 0,
      height: 0
    },
    shadowRadius: 1,
    shadowOpacity: 0.5

Try this
