### ISSUE TITLE
Camera Roll iCloud images/videos

### ISSUE THREAD

**Issue by pentarex** [facebook/react-native#17532]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: macOS High Sierra 10.13.2
  Node: 9.3.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.1
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.50.3 => 0.50.3

### Steps to Reproduce

1. Have some images/videos on iCloud
2. Implement CameraRoll

### Expected Behavior

Expecting the images/videos which are on iCloud to be visible when using CameraRoll

### Actual Behavior

iCloud images/videos not visible

**Comment by pentarex** [comment]
It is supported, just you have to specify groupTypes: 'All' instead of 'SavedPhotos'.
There is another issue though #13671

**Comment by JoshuaGRubin** [comment]
@pentarex - this is helpful.  I wish it was in in the documentation, particularly since it's not the default.  
That being said, while `groupTypes: 'All'` returns more than the 'SavedPhotos', I'm only getting 193 photos of the more than 2000 on my iPhone.   Am I missing something?

`  CameraRoll.getPhotos({
       first: 200,
       assetType: 'All',
       groupTypes: 'All'
     })
     .then(r => {
       console.log(r)
     })`

**Comment by pentarex** [comment]
@JoshuaGRubin  yes you are missing. For some reason facebook is using ALAsset which is deprecated from iOS 8 and its taking the photos from iTunes rather iCloud, and its not returning them even in some order (it shows me the oldest ones first). Currently I am developing a module which is using PHAsset (the alternative from iOS 8 and upwards). Those days I will do a commit (currently working for iOS only, not Android but in the next weeks I will develop it also for Android).

**Comment by pentarex** [comment]
I will write you when its available (expect it during the weekend)

**Comment by JoshuaGRubin** [comment]
Thanks for the quick reply @pentarex- and looking forward to hearing about about your progress!  Interestingly RCTPhotoLibraryImageLoader is implemented with  the new Photos API, so one could, in principle, download images from iCloud URIs, but everything else is written with the deprecated AssetsLibrary API - so it seems that only (or mostly?) local images are provided when CameraRoll.getPhots is called.

**Comment by pentarex** [comment]
@JoshuaGRubin https://github.com/pentarex/react-native-gallery-manager

**Comment by FacuAcosta** [comment]
Will we have an official commit of this at some point? Sounds stupid only having half of the images that you have on your phone.

**Comment by pentarex** [comment]
@FacuAcosta I don't think. They are using old Framework. Find another solution to check the link that I gave above your post

**Comment by pvsong** [comment]
+1 :v
