### ISSUE TITLE
Errors after upgrading to 0.6.0

### ISSUE THREAD

**Issue by VonD** [facebook/react-native#1754]
After upgrading to 0.6.0 I cannot get the react app to boot. Here are the various warnings from the console : 

`Error: undefined is not an object (evaluating 'RCTScrollViewConsts.KeyboardDismissMode.None')`
the line in question is : https://github.com/facebook/react-native/blob/bb0c21cb2ebb81ae5141908ab7681a87301ee4d6/Libraries/Components/ScrollView/ScrollView.js#L313

`Error: Invariant Violation: Application MyApp has not been registered`

`RCTDataManager.queryData was called with 4 arguments, but expects 3`
Also reported here: #1578 

Any hints on how to solve these issues ?

**Comment by janmonschke** [comment]
@VonD Did you try to clean project? `XCode > Product > Clean`. If that doesn't help, I also try to clean the build folder `hold alt > Product > Clean`.

**Comment by jevakallio** [comment]
The issue seems to be that transitive npm dependencies include their own, older copies or `react-native`, and the packager loads them, causing incompatibilities:

Issue documented here:
https://github.com/facebook/react-native/issues/1606#issuecomment-113113816

@VonD If you want to figure out which dependency is causing this issue, load your app in the debugger, `Cmd+O` to find `ScrollView.js`, right click on the file and choose `Reveal in navigator`. That's your culprit.

**Comment by alinz** [comment]
Could it be if one of the modules is using `peerDependencies`? Since in npm 2.x if you are using `peerDependencies` with range version, npm will show you this warning:

```bash
peerDependencies in npm 3+. Your application will need to depend on it explicitly.
```

**Comment by VonD** [comment]
Many thanks everyone, the problem was some packages depending on older versions of react-native. @jevakallio the `Reveal in navigator`tip was particularly useful.

**Comment by achang28** [comment]
@VonD, wondering how you resolve the issue specifically?  Not sure where the "Reveal in Navigator" link can be found.  I couldn't find the ```Reveal in Finder``` link when finding the ScrollView.js file.

**Comment by VonD** [comment]
@achang28 i resolved the issue by upgrading the packages that had dependencies on older versions of react native. once you load the app in the debugger (`Cmd+D`) you can type `Cmd+O` in the console, type in the name of the RN file causing your issue, and select it in the autocomplete menu. Then you can right click on the file and you should have the `Reveal in Navigator` link. This will show you what package the file comes from, and so which one you should upgrade/patch. Hope it helps.

**Comment by olivierlesnicki** [comment]
@VonD this helped me, thanks!

**Comment by chai2** [comment]
@janmonschke Thanks man. Product clean fixed my issue.
