### ISSUE TITLE
unable to resolve module

### ISSUE THREAD

**Issue by pieczyk** [facebook/react-native#17552]
### Is this a bug report?
yes
(write your answer here)

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.)

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior
I get a red screen with this
![bug](https://user-images.githubusercontent.com/35214791/34849274-323b47fc-f722-11e7-85dc-ab2d401f8f2e.png)

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by jinxac** [comment]
@pieczyk looks like your file does not exist in the your App directory.  Can you share your folder structure once?
