### ISSUE TITLE
[ListView] Unnecessary re-render of header in _updateVisibleRows

### ISSUE THREAD

**Issue by paramaggarwal** [facebook/react-native#1756]
Just noticed that on each call to [_updateVisibleRows](https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/ListView/ListView.js#L465) in ListView, the header is rendered again and again. This method is run as frequently as the onScroll event - so this is very intensive!

```
var header = this.props.renderHeader && this.props.renderHeader();
var totalIndex = header ? 1 : 0;
```
while the actual information needed is just that:
```
var totalIndex = this.props.renderHeader ? 1 : 0;
```

Please let me know if I'm missing something - otherwise I can go ahead and raise a minor PR for this.

(I am currently debugging an issue where `onChangeVisibleRows` stops updating after quickly scrolling down a few cells.)

**Comment by MossP** [comment]
Seems like a reasonable PR. Do you still see this issue?

**Comment by ide** [comment]
The original code might have been written that way in case renderHeader returns null. If you change this behavior and ideally post some speed/energy numbers that justify it, can you add a warning if renderHeader() returns null?
