### ISSUE TITLE
[Packager] Unable to use vector assets feature of xcode 6

### ISSUE THREAD

**Issue by owais** [facebook/react-native#1757]
Xcode 6 introduced the vector assets feature detailed here http://martiancraft.com/blog/2014/09/vector-images-xcode6/

I'm unable to `require(image!myVectorImage)` in react-native 0.6. It raises the following error,

```
 message: Requiring unknown module "image!myVectorImage". If you are sure the module is there, try restarting the packager."
```

Normal PNG images work just fine.

**Comment by frantic** [comment]
That's because packager doesn't know about it. Try adding your file extension to this list https://github.com/facebook/react-native/blob/master/packager/packager.js#L218

**Comment by YoungElPaso** [comment]
Why was this closed? Did adding the extension (presumably pdf) work? I've been trying to add density independent vector drawables the same way for Android, under react 0.14 and they also don't work (even if I add xml to ln 60 in packager/react-packager/src/Server/index.js).

On the other hand, if I remove 'png' from that same list, pngs are now unsupported, so it seems that array is where the difference lays, but maybe I'm wrong about that?
