### ISSUE TITLE
App run multiple times in fresh install first run.

### ISSUE THREAD

**Issue by vzhen** [facebook/react-native#17576]
### Is this a bug report?

Yes, app run multiple instance in fresh install first run. Both physical and virtual device.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment
  OS:  Windows 10
  Node:  6.11.3
  Yarn:  1.1.0
  npm:  5.4.2
  Watchman:  Not Found
  Visual Studio Code: 1.19.2

  Packages: (installed)
    react-native: 0.49.3
    react: 16.0.0-beta.5

### Steps to Reproduce

1.  react-native run-android.
2.  Click home button to minimize app.
3.  Re-open app via home screen app icon.
4.  Double R to reload 
5.  Check browser console.
6.  App run multiple instance, every minimize stack 1.
7.  Only happen in first run, kill app > re-open issue gone.

### Expected Behavior

Component should run ONCE when double R reload.

### Actual Behavior
Component run multiple times when double R reload.
Example: componentDidMount componentUnmount multiple times
![capture](https://user-images.githubusercontent.com/1941395/34894732-709e250e-f81d-11e7-9c7f-4b0e15c748d3.JPG)

### Reproducible Demo

https://github.com/vzhen/MultipleInstanceIssue
1. npm install
2. react-native run-android
3. DO NOT kill app, this happen only in first run
4. Click home button to minimize
5. Re-open app via home screen
6. Check browser console to see multiple instance.
7. Repeat 4 & 5 steps multiple time
8. Double R to reload app and check browser console.
9. Kill app
10. Open app repeat 4 & 5 steps
11. Double R reload
12. Check log, No more multiple instance.

**Comment by kalek** [comment]
I have the same issue on - "react-native": "0.55.4",

**Comment by microcipcip** [comment]
@kalek try this fix: https://stackoverflow.com/a/45001797/974107
