### ISSUE TITLE
Provide option to ignore SSL errors instead of hardcoded rejection for fetch/XMLHTTPRequest

### ISSUE THREAD

**Issue by TimNZ** [facebook/react-native#17588]
Target device: Android, 5.0.2 and below

This is a feature request.

This is also a duplicate of #6058, but since that was closed over a year ago and nothing has been done, time to ask community to review it again.

I spent 3 hrs tracing down why a 'fetch' request was erroring resulting in a 'Network Request Failed' error.
This was triggered by a 'java.security.cert.CertPathValidatorException: Trust anchor for certification path not found' that I accidentally saw in a response property from the underlying XMLHTTPRequest when painfully debugging.

Android 5.0.2 and below (maybe below 6.0) do not support the intermediary cert for a SSL cert on a domain (https://api.binance.com in this case).

There is no way to specify an option to fetch/XMLHTTPRequest to ignore SSL issues.

Since a lot of Android apps still support Android 4.1, and RN min Android version is 4.1, it seems reasonable that we get a workaround for a fundamental networking issue that we can't control e.g. new cert authorities.

Previous issue discussions have shown an unwillingness to support non-standard options on fetch/XMLHTTPRequest, but giving us nothing to get around this issue isn't cool either.

I don't do native dev so me doing a PR would be a challenge.

**Comment by manit77** [comment]
is this what our future looks like with AI bots? Closed before even reviewed.

**Comment by TimNZ** [comment]
Yeah, sad.

**Comment by TimNZ** [comment]
The new issue template refers to bug issues go here, or help via Stackoverflow.
So apparently, not interested in feature requests.

**Comment by kevindaniels** [comment]
hey @TimNZ, I'm actually facing the exact same issue for the same API. Did you happen to find a solution? The only thing I found was making an OkHttpClient that trusts all certificates, but that's not exactly ideal.
