### ISSUE TITLE
How to show a “Spinner” mode “DatePickerAndroid” without any dialog/modal/popup screen?

### ISSUE THREAD

**Issue by TechSatya** [facebook/react-native#17581]
### Is this a bug report?

No

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

No

### Environment
Environment:
  OS: Windows 10
  Node: 6.11.5
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.0.0.0 AI-171.4408382

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.50.4 => 0.50.4

### Steps to Reproduce

1. How to get the DatePickerAndroid view without any dialog/popup/modal?
2. How to show the DatePickerAndroid on a screen with other views without any dialog/popup/modal view?

### Expected Behavior

I wanted to show a simple spinner mode DatePickerAndroid statically (not in a dialogue/modal screen) on a profile screen with some other views but didn't found any helpful suggestions throughout the web.

### Actual Behavior
I didn't find such helpful suggestion/answer to show the DatePickerAndroid statically on a screen.

A screenshot here (which I need actually like this);
[Screenshot](https://i.stack.imgur.com/gIPx7.png)

### Reproducible Demo
Nothing to show in a demo as I will start this from scratch after getting a valuable help.

**Comment by ravirajn22** [comment]
The DatePickerAndroid, Opens the standard Android date picker Dialog. Hence it is not currently possible to use it without opening a Dialog i.e Modal or Popup. If you want u can create your own picker using Javascript or try searching for projects in GitHub.

**Comment by TechSatya** [comment]
Do you know any libraries which can give the same look and feel??
I have found some but they look like a wheel roller.

**Comment by ravirajn22** [comment]
I don't know and also Please close this issue.
