### ISSUE TITLE
Feature Request - Web Audio API Implementation

### ISSUE THREAD

**Issue by jamesharvey2** [facebook/react-native#17593]
### Is this a bug report?

This is a crucial feature request.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

  Environment:
OS: Win 10
Node: 8.4.0
Yarn: 0.27.5
npm: 5.4.0
Watchman: 4.7.0

Packages: (wanted => installed)
react-native: 0.48.1 => 0.48.1
react: 16.0.0-alpha.12 => 16.0.0-alpha.12

Target Platform: iOS (10.3)

### Steps to Reproduce

Simply try to use Web audio API on react native.. nothing will work.

1.Try Web audio API on your react native app
2.and it will not make sound
3.and will make you want to request web audio API feature to facebook development team

### Expected Behavior

React Native would fully respond to codes from web audio api

### Actual Behavior

Surprisingly, React Native doesn't make any sound when using Web Audio API...
I can't believe this still hasn't been implemented yet.

### Reproducible Demo

All React Native apps are demos for this problem.
Please implement web audio API to react native so we can use amazing js library like tone.js!

**Comment by lwinkyawmyat** [comment]
@facebook-github-bot feature
