### ISSUE TITLE
borderWidth of decimals (.5, .75, etc.) alters background unexpectedly while using StyleSheet

### ISSUE THREAD

**Issue by prodigynelson** [facebook/react-native#17594]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.9.1
  Yarn: 1.3.2
  npm: 5.5.1
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: Not Found

Packages: (wanted => installed)
  react: Not Found
  react-native: ^0.52.0 => 0.52.0

### Steps to Reproduce

(Write your steps here:)

1. run iphone X simulator 
2. in a view (or any other component that allows borders), set style={styles.whatever}(where styles is a React-Native StyleSheet object) to borderWidth: .5 (or any decimal value) 
3. witness the chaos

### Expected Behavior

[This screenshot](http://prntscr.com/i0ghsp) demonstrates the same borderWidth property behaving differently on iPhone 7 than iPhone X.

### Actual Behavior

On iPhone X (tested on real device too), a borderWidth of .5 will create a weird fade off of color from the background to the border [(screenshot)](http://prntscr.com/i0gjkl) and what's weird is it's only on the bottom...

### Reproducible Demo
    const styles = StyleSheet.create({
        shitsBroke: {
            flexBasis: 'auto',
            backgroundColor: '#fff',
            borderWidth: .5,
            borderColor: '#DCDCDC',
           },
          tabContainer: {
           flexBasis: 'auto',
           flexDirection: 'row',
           justifyContent: 'flex-end',
           backgroundColor: '#fff',
           borderWidth: .5,
           borderColor: '#DCDCDC',
    },
    })

    class BrokenWidth extends Component { 
        render () {
            return (
                <View>
                <NavButton/>
                <View style={styles.shitsBroke}>
                    <Text style={{paddingTop: 5, fontSize: 16}}> 
                        I wish everything would just work on every device ever but no instead of writing valuable code I gotta spend time debugging an issue I think isn't my fault but probably ended up causing somehow 
                    </Text>
                </View>
                </View>
                )
            }
    }

    const NavButton = () => {
        return (
            <SafeAreaView forceInset={{ top: 'always' }} style={styles.tabContainer}> 
                <TouchableOpacity>
                    <Text >PlaceHolder</Text>
                </TouchableOpacity>
 
        </SafeAreaView>
    )}

**Comment by cyperus** [comment]
You can find solution in this similar issue. https://github.com/facebook/react-native/issues/12401#issuecomment-317644016
