### ISSUE TITLE
How to reduce Android apk size? (build by React Native) What's the minimum Android APK size?

### ISSUE THREAD

**Issue by 1c7** [facebook/react-native#17607]
### Is this a bug report?
NO

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

No

### Environment
Environment:
  OS: macOS High Sierra 10.13.2
  Node: 8.9.4
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.51.0 => 0.51.0

-----

## Background info
I build a simple App that focus on Android for now, the generate APK size is about 8~9 mb
(6 screen, 4 image that add up doesn't exceed 500kb, just logo and splash screen)

### What's the minimum size a React Native Android APK can get?
there not much info on Google,
here is few of them:

https://github.com/facebook/react-native/issues/5037
https://hashnode.com/post/how-to-reduce-the-app-size-in-react-native-cj6ohocv002rqt9wuy24etkee
https://facebook.github.io/react-native/docs/signed-apk-android.html
https://stackoverflow.com/questions/38184734/react-native-for-small-size-apk-with-low-internet-bandwidth

seem like 
```
def enableProguardInReleaseBuilds = true
def enableSeparateBuildPerCPUArchitecture = true
```
is the most I can do,

it's 2018 and newest React Native version is 0.52,
### is there anything more I can do to reduce Android APK size?
the ideal size should be around 1~3mb

Thank you very much :)

**Comment by thevolcanomanishere** [comment]
Use the apk analyser in Android studio and see what is taking up the space then post the screenshot back here

**Comment by 1c7** [comment]
@thevolcanomanishere  no problem~ Thanks! would come back soon

**Comment by 1c7** [comment]
# Here is result
@thevolcanomanishere 
![1 1](https://user-images.githubusercontent.com/1804755/34987169-23dc1ffc-faf5-11e7-9fda-f99e214a9059.png)
![2 1](https://user-images.githubusercontent.com/1804755/34987167-2370dc42-faf5-11e7-9ec4-c06f644d0224.png)
![3 1](https://user-images.githubusercontent.com/1804755/34987168-23a3839a-faf5-11e7-8efe-aeb0925d00b2.png)

**Comment by 1c7** [comment]
# Here is source code screenshot
![image](https://user-images.githubusercontent.com/1804755/34987203-4eb1530a-faf5-11e7-949b-47f0cae55275.png)

## 15 file under `/src`
![image](https://user-images.githubusercontent.com/1804755/34987210-553a5974-faf5-11e7-8573-0504d8bf2b0c.png)

**Comment by 1c7** [comment]
## I used:
* React Native 0.51
* [react-native-image-picker](https://github.com/react-community/react-native-image-picker)
* [NativeBase](https://github.com/GeekyAnts/NativeBase)
* `react-native-i18n` 
* MobX for state management
* `react-native-splash-screen` 

here is full list:
![image](https://user-images.githubusercontent.com/1804755/34987303-a21ac652-faf5-11e7-96eb-4866f7e61cc3.png)

**Comment by 1c7** [comment]
appreciate @thevolcanomanishere

**Comment by thevolcanomanishere** [comment]
You could reduce the size of your launcher images by a good but. Look up how to compress your images efficiently. You are also creating an api with both x86 and arm versions. x86 alone is 3.1mb. Without that and more efficient images you could reduce your apk by 4-5megs

**Comment by thevolcanomanishere** [comment]
Your react-native-splash-screen package is unnecessary. You could create a much more lightweight splash screen by making it yourself

**Comment by 1c7** [comment]
@thevolcanomanishere
Thanks! 
will do!

**Comment by lwinkyawmyat** [comment]
@facebook-github-bot stack-overflow
