### ISSUE TITLE
Can't change StatusBar backgroundColor

### ISSUE THREAD

**Issue by sushantsaho** [facebook/react-native#17602]
### Is this a bug report?

YES

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.)

### Steps to Reproduce

(Write your steps here:)
1. run iphone X simulator
2. Applying the backgroundColor prop to StatusBar component doesn't get applied. I need to set the background colour of SafeAreaView to get the effect i want, which is not desired because on iPhone X it will have that same colour at the bottom of the screen where the "notch" is

### Expected Behavior
I want to apply color only to top Status bar area.
<img width="282" alt="screen shot 2018-01-15 at 4 07 36 pm" src="https://user-images.githubusercontent.com/35450162/34938424-4de32eae-fa0e-11e7-90f0-bfad8241b3a4.png">

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by RidaRidss** [comment]
import {StatusBar} from "react-native";

  componentDidMount() {
// use white status bar 
    StatusBar.setBarStyle("light-content");
// use black status bar 
    StatusBar.setBarStyle("dark-content");
}
