### ISSUE TITLE
Feature Request - Canvas API Implementation

### ISSUE THREAD

**Issue by jamesharvey2** [facebook/react-native#17614]
### Is this a bug report?

This is a crucial feature request...

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

  Environment:
    OS:  macOS Sierra 10.12.6
    Node:  8.4.0
    Yarn:  0.27.5
    npm:  5.4.0
    Watchman:  4.7.0
    Xcode:  Xcode 8.3.3 Build version 8E3004b
    Android Studio:  2.3 AI-162.4069837

  Packages: (wanted => installed)
    react-native: 0.48.1 => 0.48.1
    react: 16.0.0-alpha.12 => 16.0.0-alpha.12

  Target Platform: iOS (10.3)

### Steps to Reproduce

HTML Canvas API can do amazing things for UI but it's not available in React Native....

1. Try Canvas API on React Native
2. Nothing will happen...

### Expected Behavior

React Native would fully support Canvas API
https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API

### Actual Behavior

React Native doesn't respond to Canvas API... that is a huge miss for talented UI designers.
See what you can do with Canvas API here:
https://codepen.io/search/pens?q=canvas+api&limit=all&type=type-pens

and please imagine what if you could use them on React Native.

### Reproducible Demo

All React Native apps are demos for this problem. 
We need Canvas API fully supported in React Native ASAP.....

**Comment by hey99xx** [comment]
I don't want to belittle your app's needs, but you sound needlessly demanding with 

> This is a crucial feature request.
> ...
> We need Canvas API fully supported in React Native ASAP.

Anyway, this kind of stuff does not really belong to the core React Native. They're probably going to remove WebView component out of the core API soon too. You'd have better luck using something like https://www.npmjs.com/package/react-native-canvas or alternatives to canvas such as:

- https://github.com/react-native-china/react-native-ART-doc/blob/master/doc.md
- https://github.com/react-native-community/react-native-svg

I don't know where the exception that **HTML**  `<canvas>` API would be supported out of the box comes from. You are not developing a web app with RN.

**Comment by jamesharvey2** [comment]
I'm beginner at React Native... I've been working on Cordova for a while. 
Yes, you're right. There's already a plugin for this! 
Thanks a lot.

**Comment by hey99xx** [comment]
> Canvas API leverages JavaScript for drawing UI. and React Native is javascript-based.

Not totally correct. Canvas is an HTML5 API. Similarly Node.JS servers can have access to the file system, creating HTTP servers, and creating child processes. These things are not standard JavaScript libraries, they're part of Node.JS offerings. Similarly with RN you have 3rd JavaScript environment, where there's no `window` or `document` objects, no LocalStorage (but AsyncStorage)... 

It's true that RN does polyfill stuff like `fetch` or `navigator.geolocation` to be compatible with browsers, but it does not promise to bring entire browser API into its JavaScript runtime.

Anyways I'll let a dev from FB team comment, but they're probably going to repeat my comment.

**Comment by hramos** [comment]
I have nothing to add to @hey99xx's comments. Closing as we don't typically track feature requests here, only bug reports.

**Comment by jamesharvey2** [comment]
Hello Facebook Dev team,

Would you please make Web Audio API work on React Native? 

https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API
