### ISSUE TITLE
Accessibility Issue[Android] :  TextInput not editable when talkback on.

### ISSUE THREAD

**Issue by rimzici** [facebook/react-native#17624]
### Is this a bug report?

YES

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

YES

### Environment
Environment:
  OS: Linux 4.4
  Node: 8.9.1
  Yarn: 1.3.2
  npm: 5.5.1
  Watchman: 4.9.0
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.50.4 => 0.50.4

Have tried in Emulator as well as Device.
Google Pixel 2
API Level: 26 
### Steps to Reproduce

1. run the sample below.
2. turn talkback on.
3. try editing TextInput (as suggested by double tapping)
the key board never shows up.

### Expected Behavior

on double tap, as expected the keyboard has to open and field should be editable.

### Actual Behavior

TextInput not editable because keyboard never shown.
when autofocus is set 'true' on TextInput, that time alone it is editable , but not while trying manually.

### Reproducible Demo

https://github.com/rimzici/NavigationEx

**Comment by RamyaSenk** [comment]
@react-native-bot @rimzici is this working for you on the latest react native version? For me it is not working. The focus does,nt get set on text input when Talkback is on.

**Comment by rimzici** [comment]
Issue still persist in RN v0.54, text input is not editable when talk back in ON, unless autoFocus is set true on it.

**Comment by tzhong92** [comment]
Still noticing this bug on RN v0.55.2. TextInput is not editable when talk back is ON. Even though autoFocus is true, when user select another component and select back on TextInput, it's still not editable.

**Comment by StatikVerse** [comment]
Hi. Still noticing the bug as well in React Native 0.55.4, using Expo 28.0.0. What I have noticed is that the text input field becomes editable when I tap on it with two fingers, instead of double tapping with one finger after selecting. I'm not sure if this could be a talkback update thing or if this behaviour is specific with my phone (Huawei P10 VTR-L29, build number 8.0.0.368(C185), but I haven't found any documentation on it.

**Comment by dbrezack** [comment]
Still an issue .56.

**Comment by MaxToyberman** [comment]
@dbrezack  did you find any info about this problem ?

**Comment by ilydnic** [comment]
Seeing this on 0.55.4. Am able to swipe to and select a TextInput with double tap if it has already been selected once with TalkBack off or with autofocus on.

**Comment by czdosi** [comment]
Still doesn't work in latest RN. Seems to be related to Android 8.0 changes (see: https://developer.android.com/about/versions/oreo/android-8.0-changes#a11y), because it works for me with Android 6.0.

**Comment by shalbert94** [comment]
I"m an Android Native developer, not a React Native developer. However, this issue persists to Android Native, so it's definitely not a React Native issue.
