### ISSUE TITLE
Immediate child views of a TouchableHighlight cannot be assigned a "ref" (reference).

### ISSUE THREAD

**Issue by ozburo** [facebook/react-native#17637]
### Is this a bug report?

Yes.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes, (but you know that's a lie).

### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.4.0
  Yarn: 0.24.5
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4408382

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.50.3 => 0.50.3

Target Platform: iOS (10.3)

### Steps to Reproduce

A View with a `ref` as an immediate child of a <TouchableHighlight> doesn't get it's ref assigned.

```
  render() {
    return (
      <View style={styles.container}>

        <TouchableHighlight>

          <View ref="parentView">
            <View ref="childView">
              <Text>Some text</Text>
            </View>
          </View>

        </TouchableHighlight>

        <TouchableOpacity>

          <View ref="parentView2">
            <View ref="childView2">
              <Text>Some text</Text>
            </View>
          </View>

        </TouchableOpacity>

        <TouchableWithoutFeedback>

          <View ref="parentView3">
            <View ref="childView3">
              <Text>Some text</Text>
            </View>
          </View>

        </TouchableWithoutFeedback>

      </View>
    );
  }

```

When you inspect `this.refs`:

```
console.log(this.refs)
// {childView: {…}, childView2: {…}, parentView2: {…}, childView3: {…}, parentView3: {…}}
// no parentView when using TouchableHighlight

```

### Expected Behavior

We should be able to use refs on child views of TouchableHighlights like any other parent view type.

### Actual Behavior

No ref!

### Reproducible Demo

Please refer to this complete TestScreen.js

```
'use strict';

import React from 'react';
import {
  TouchableWithoutFeedback,
  TouchableHighlight,
  TouchableOpacity,
  StyleSheet,
  Text,
  View,
} from 'react-native';

class TestScreen extends React.Component {
  constructor(props) {
    super(props);
  }

  componentDidMount() {
    console.log(this.refs)
    // {childView: {…}, childView2: {…}, parentView2: {…}, childView3: {…}, parentView3: {…}}
    // no parentView when using TouchableHighlight
  }

  componentWillUnmount() {
  }

  render() {
    return (
      <View style={styles.container}>

        <TouchableHighlight>

          <View ref="parentView">
            <View ref="childView">
              <Text>Some text</Text>
            </View>
          </View>

        </TouchableHighlight>

        <TouchableOpacity>

          <View ref="parentView2">
            <View ref="childView2">
              <Text>Some text</Text>
            </View>
          </View>

        </TouchableOpacity>

        <TouchableWithoutFeedback>

          <View ref="parentView3">
            <View ref="childView3">
              <Text>Some text</Text>
            </View>
          </View>

        </TouchableWithoutFeedback>

      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
});

export default TestScreen;



```

**Comment by adrianfalleiro** [comment]
@ozburo I pasted the contents of `TestScreen.js` into a fresh 0.52 project and I seem to be able to see `parentView` (and the others) logged in the console.

<img width="1246" alt="screen shot 2018-01-18 at 1 24 08 am" src="https://user-images.githubusercontent.com/8309411/35047575-7a4c1f96-fbee-11e7-922b-13bba596ee09.png">

I don't know if it will fix your issue - but perhaps it might be worth updating to RN 0.52 and seeing if the problem still exists.

**Comment by ozburo** [comment]
@adrianfalleiro Well hot dang! I guess I needed to upgrade before I created this ticket  👍 

Yes, it works now w/ RN@0.52, so I'm happy to close this.

Thanks!
