### ISSUE TITLE
0.52.0 'RCTTVRemoteHandler.h' file not found

### ISSUE THREAD

**Issue by Clcll** [facebook/react-native#17639]
Hi!

I am trying to run my app on React Native 0.52.0
I get this error
![2018-01-17_19-30-10](https://user-images.githubusercontent.com/22677040/35054428-96038e12-fbbd-11e7-9ef9-da9eb953b320.png)

My podfile is 
`# You Podfile should look similar to this file. React Native currently does not support use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

# Change 'AirMapsExplorer' to match the target in your Xcode project.
target 'clcorp' do

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/yoga.podspec'
  pod 'React', path: '../node_modules/react-native', :subspecs => [
      'Core',
      'RCTActionSheet',
      'RCTAnimation',
      'RCTGeolocation',
      'RCTImage',
      'RCTLinkingIOS',
      'RCTNetwork',
      'RCTSettings',
      'RCTText',
      'RCTVibration',
      'RCTWebSocket',
      'DevSupport'
  ]

  pod 'GoogleMaps'  # <~~ remove this line if you do not want to support GoogleMaps on iOS
  pod 'react-native-maps', path: '../'
  pod 'react-native-google-maps', path: '../'  # <~~ if you need GoogleMaps support on iOS

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    if target.name == 'yoga'
       target.build_configurations.each do |config|
         config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
         config.build_settings['GCC_WARN_64_TO_32_BIT_CONVERSION'] = 'NO'
       end
    end
  end
end`

Any ideas ?
Thx

**Comment by Riant** [comment]
#17027

Try to add `'tvOS'` to your react native subspecs, like below:
```
pod 'React', :path => '../tangguo/node_modules/react-native', :subspecs => [
    'Core',
    'tvOS', // here
    ...
]
```

It works well for me.

**Comment by CityLifeCorp** [comment]
@Riant  thx, works for me

**Comment by miighty** [comment]
Not too happy about adding TvOS but it did work for me  also.

**Comment by woshi82** [comment]
+1 Not too happy about adding TvOS
