### ISSUE TITLE
TextInput onSubmitEditing is called when multiline is true

### ISSUE THREAD

**Issue by hushicai** [facebook/react-native#17634]
### Is this a bug report?

I think so.

According to the docs:

> Callback that is called when the text input's submit button is pressed. Invalid if multiline={true} is specified.

When multiple is true, onSubmitEditing should not be called.

### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.9.0
  Yarn: 1.3.2
  npm: 5.5.1
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.2.0 => 16.2.0
  react-native: ^0.52.0 => 0.52.0

Target Platform: iOS (11.2)

### Steps to Reproduce

(Write your steps here:)

1.set TextInput multiline={true}
2.onSubmitEditing={() => {console.log('called');}}
3.typing words in TexInput and return

### Expected Behavior

onSubmitEditing should not be called!

### Actual Behavior

onSubmitEditing is called when return.

**Comment by Sommerfeld** [comment]
`"multiple" === "multiline" // false`

**Comment by hushicai** [comment]
Sorry for spelling mistake.
Actually, it is multiline.
![image](https://user-images.githubusercontent.com/1249423/35077962-bb74d78c-fc3a-11e7-818f-ac45e8178e60.png)

**Comment by RidaRidss** [comment]
<TextField   
  autoCapitalize={true}
      autoCorrect={false}
           multiline={true}
      value={value} 
      label={label} 
       maxLength={30}
      numberOfLines={3}
/>

**Comment by nikasvan** [comment]
This is very weird. On Android it is called but on iOs it's not.
