### ISSUE TITLE
RCTImageCache working incorrectly.

### ISSUE THREAD

**Issue by nhiicts** [facebook/react-native#17647]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.9.3
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: ^16.0.0 => 16.0.0
  react-native: ^0.51.0 => 0.51.0
### Steps to Reproduce

(Write your steps here:)
![untitled](https://user-images.githubusercontent.com/26533691/35092673-b6cd4a9c-fc72-11e7-87a3-29acdda5a01d.gif)
Precondition: images was saved in local before.
1. Name images as 1,2,3,4 for easily tracking
2. Display images in FlatList as Gif above (Image component must have same width and height)
3. Change the name of image 4.jpg to 5.jpg and 3.jpg to 4.jpg

### Expected Behavior

Image 3.jpg after rename to 4.jpg display correct image

### Actual Behavior

I think RCTImageCache was fetched wrong image because of `NSString *cacheKey = RCTCacheKeyForImage(url, size, scale, resizeMode, responseDate);` line. In the example above. suppose data1 is 4.jpg and data2 is 3.jpg. so when we change 4.jpg to 5.jpg, we have cached data1 with file:///xxx/documents/downloads/4.jpg and file:///xxx/documents/downloads/4.jpg keys.(file:///xxx/documents/downloads/xxx.jpg is absolute path to image). Then when change 3.jpg to 4.jpg it will fetched data1 with file:///xxx/documents/downloads/4.jpg key (which was saved by another image before). So wrong image was fetched

I think the bug can be fixed if Image component support keyExtractor like FLatList for cache-key

### Reproducible Demo

The instructions I have give in the give above.
(I'm sorry for my bad english)

**Comment by nhiicts** [comment]
Anyone help?

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (186/150 (124%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o3.sgmail.github.com ([192.254.112.98]:31546)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-a7b0-hello=salmanwaheed.info@sgmail.github.com>)
	id 1epQW8-003Jj6-1A
	for hello@salmanwaheed.info; Fri, 23 Feb 2018 20:28:57 -0700
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=J10vyvUT2CbvOymwJQojY6W9I7g=; b=qDbRf2QOwaBge3Uf
	fnGXnCFACKIiz+0BPsrRKWv5WhjAGoQVl/EOJvWxX90Jmffd7FS/OhWKTGOb6968
	1RX5HsUyPY8dsv1ipOGJAMDlecTCkR8bkBbb2IlpCCx6qy20HEqHTaGXFQSnBVsa
	5ddxSvdAjq1B9fIclYmpWsLlhJc=
Received: by filter0452p1iad2.sendgrid.net with SMTP id filter0452p1iad2-4025-5A90DBEC-4
        2018-02-24 03:28:44.447986204 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0021p1iad2.sendgrid.net (SG) with ESMTP id GOI77_AxRpONwaRb2PBtYQ
	for <hello@salmanwaheed.info>; Sat, 24 Feb 2018 03:28:44.421 +0000 (UTC)
Date: Sat, 24 Feb 2018 03:28:44 +0000 (UTC)
