### ISSUE TITLE
Custom fontFamily for Text not working in either iOS or Android

### ISSUE THREAD

**Issue by sunweiyang** [facebook/react-native#17641]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: macOS High Sierra 10.13.2
  Node: 9.4.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.0 => 0.52.0

### Steps to Reproduce

1. Place contents of Nunito font fro Google (*ttf files) into project root's `assets/fonts/` directory [(here are the contents of that directory)](https://github.com/facebook/react-native/files/1640191/assets.zip)
2. Add the following to my `package.json`:
```
"rnpm": {
    "assets": [
	"./assets/fonts/"
    ]
},
```
3. Run `react-native link`
4. Verify that both Xcode/Info.plist and Android Studio reflects the new Nunito font:
![screen shot 2018-01-17 at 10 41 59 am](https://user-images.githubusercontent.com/12490625/35060421-420b8e9e-fb73-11e7-8f6d-dd90ecb49d98.png)
![screen shot 2018-01-17 at 10 44 44 am](https://user-images.githubusercontent.com/12490625/35060493-79e95bc0-fb73-11e7-9a03-bfd7c57be4e1.png)
5. Run `./gradlew clean` from `android` directory, fresh install of `node_modules` from scratch, fresh install of pods from `android` directory, restart both Xcode and Android Studio, reset npm cache, uninstall and reinstall app on variety of emulators and devices
5. Try setting `Text.defaultProps.style = {fontFamily: 'Nunito'};` in root component (`App.js`)
6. Try setting `{fontFamily: 'Nunito'}` style for a single `Text` component

### Expected Behavior

I expected globally setting `Text.defaultProps.style = {fontFamily: 'Nunito'};` to result in the font being applied everywhere in my app, or at the very least setting `{fontFamily: 'Nunito'}` style for a single `Text` component to work.

### Actual Behavior

In all cases, I still only observe my app using the default RN font family.

**Comment by lwinkyawmyat** [comment]
Can you try to match `font filename` and `fontFamily` name.
```javascript
{ 
  fontFamily: 'Nunito-Reqular' // if filename is Nunito-Reqular.ttf
}
```
```javascript
{ 
  fontFamily: 'Nunito-Bold' // if filename is Nunito-Bold.ttf
}
```

**Comment by lwinkyawmyat** [comment]
@facebook-github-bot duplicate #15266

**Comment by sunweiyang** [comment]
@lwinkyawmyat I'm unsure if it's a duplicate, since I don't have `fontWeight` or `fontStyle` set.

**Comment by vivek-walecha-657** [comment]
i am facing the same issue, tried everything but dint get any solution.

**Comment by hamadasamir85** [comment]
I found out that font names on ios are different from the file name.
the files name might be 'GE_SS_TWO_MEDIUM.ttf' but if you check the font info with fontbook app you will find the name is 'GE SS TWO'.
using the file name as fontfamily works on android but does not work on ios ,and vise versa
so my solution was to use Platform check on style

`fontFamily: Platform.OS === 'ios' ? 'GE SS TWO':'GE_SS_TWO_MEDIUM' `

worked for me so far
