### ISSUE TITLE
Undefined symbols for architecture arm64:   "_OBJC_CLASS_$_RCTLinkingManager"

### ISSUE THREAD

**Issue by mounlion** [facebook/react-native#17652]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: macOS High Sierra 10.13.2
  Node: 8.9.3
  Yarn: Not Found
  npm: 4.6.1
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.51.0 => 0.51.0

### Actual Behavior

Can not  make archive for release app

<img width="1193" alt="2018-01-18 16 07 33" src="https://user-images.githubusercontent.com/17071211/35099620-baeef8ae-fc69-11e7-8c0d-c14e6f2a5537.png">

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_RCTLinkingManager", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by adrianfalleiro** [comment]
@mounlion Can you provide a sample project?

**Comment by mounlion** [comment]
👎
