### ISSUE TITLE
1 #1104 com.facebook.react.uimanager.IllegalViewOperationException

### ISSUE THREAD

**Issue by wangyongpenga** [facebook/react-native#17669]
### Is this a bug report?

(write your answer here)

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.)

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by hey99xx** [comment]
Can you actually complete the template? There's absolutely no information to work with here except your title.

**Comment by chirag04** [comment]
@facebook-github-bot no-template
