### ISSUE TITLE
Text input value error

### ISSUE THREAD

**Issue by koswarabilly** [facebook/react-native#17664]
### Is this a bug report?

maybe

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

no

### Environment

(Write your steps here:)

1. I wanted to have two buttons that are able to add and remove new textinput (not the value) onclick 
2. i want to assign the value of each textinput to an array using onChangeText props
3. I add 2 field , then i input in the first field 
4. I try to delete it which mean  i have to delete the data in the array too right? i did and the array change too but the data from the first field move to the second field which is weird
5. the other time i try, i add a textinput and input some data to it then add new textinput when i remove it , it works perfectly fine which make me confuse

### Expected Behavior

The textinput value should not follow the previous array that have been deleted

### Actual Behavior

Just watch the gif
The array assigned are edited correctly which make me more confuse
![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/29243760/35132468-17ccb87e-fcfe-11e7-8ea0-b2913580fff0.gif)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by ravirajn22** [comment]
What method are you using to remove strings from the array? show your complete code. I have a feeling this could be a problem with your logic.

**Comment by koswarabilly** [comment]
@ravirajn22 
okay let me explain the app flow too.
when method `addfield` called, i have this code

```
addfield() {
        var temp;
        temp = this.state.fielddata;
        temp.splice(temp.length, 0, { name: 'Field ' + (temp[temp.length - 1].id + 1), id: temp[temp.length - 1].id + 1 })
        this.setState({ fielddata: temp })
        this.fetchfield()
    }
```

fetchfield is a method to rerender the list of input if added or changed
noted that in each input of the textinput i set `onChangeText={(text)=>this.field[id] = text}`

in the `deletefield` method i use for loop to find the specific id 

```
var temp;
        for (var i = 0; i < this.state.fielddata.length; i++) {
            if (this.state.fielddata[i].id == id) {
                temp2 = this.field
                temp2.splice(id, 1, null)
                this.field = temp
                temp = this.state.fielddata
                temp.splice(i, 1)
                this.setState({ fielddata: temp })
                this.fetchfield()
                break;
            }
        }
```
