### ISSUE TITLE
Android WebView net::ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by alekshs** [facebook/react-native#17670]
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

yes

### Environment

Environment:
  OS: macOS High Sierra 10.13.2
  Node: 8.7.0
  Yarn: 1.3.2
  npm: 5.2.0
  Watchman: 4.9.0
  Xcode: Xcode 9.1 Build version 9B55
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.51.0 => 0.51.0

  Target Platform: Android

### Steps to Reproduce

1. Create a clean project with `react-native init myProject`
2. add a webview
```
<WebView
  source={{ uri: 'https://m.facebook.com' }} // or any other url
/>
```
3. Run on Android

### Expected Behavior

Should render the website.

### Actual Behavior

Shows blank screen and showing `"Encountered an error loading page "` in debug console. 

The onNavigationStateChange method returns:
```
{
  canGoBack: false
  canGoForward: false
  code: -2
  description: "net::ERR_NAME_NOT_RESOLVED"
  loading: false
  target: 489
  title: ""
  url: "https://m.facebook.com/"
}
```

Tested on the emulator and on a real device.
(works fine on iOS)

**Comment by adderly** [comment]
Same here.

**Comment by jeremy4772** [comment]
Any news on this? Am also seeing this problem and need a fix ASAP

**Comment by alekshs** [comment]
I built my project in another computer and it works just fine. I still have this issue in my computer. It was working fine and one day ti started throwing this error. My android setup must be corrupted or something.

**Comment by balavishnu-vj** [comment]
Faced this issue when my laptop was connected to wifi and was using Emulator. Check whether emulator can assess DNS server ( use chrome and open google.com, if it works then emulator has assess to DNS server). 
Else check [this](https://stackoverflow.com/questions/2039964/how-to-connect-android-emulator-to-the-internet)
