### ISSUE TITLE
weird requiring issue

### ISSUE THREAD

**Issue by hyusetiawan** [facebook/react-native#1767]
for some reason, requiring this way works:
```
var Klass = require('./module')
```
however, this doesn't
```
var Klass = require('./' + 'module')
```
it throws, the red screen, require unknown module.
Am I missing something basic? What I am trying to do is to dynamically require several modules from an array eg: ['module1', 'module2', 'module3']

**Comment by ide** [comment]
The packager only works with statically analyzable requires. Treat require like a keyword (as you would with ES6 import).
