### ISSUE TITLE
(Android-0.53) Nuclide debugging should be available to external build 

### ISSUE THREAD

**Issue by hey99xx** [facebook/react-native#17678]
### Is this a bug report?

Yes

### Environment

Android
RN 0.53

### Expected Behavior

 My company builds each React Native release from source with Gradle. Currently https://github.com/facebook/react-native/blob/dd016f334cef26f393b1a3c1e052e89a69502a56/ReactAndroid/src/main/java/com/facebook/react/common/BUCK#L35 sets internal build = true for BUCK and https://github.com/facebook/react-native/blob/1e8f3b11027fe0a7514b4fc97d0798d3c64bc895/ReactAndroid/build.gradle#L247 for Gradle.

Nuclide debugging will not be available outside internal build according to this line https://github.com/facebook/react-native/blob/7c7108a1e8e9354d8aeb2f0ff712561d8aa19408/ReactAndroid/src/main/java/com/facebook/react/devsupport/DevInternalSettings.java#L130

### Actual Behavior

Nuclide debugging is guarded behind flag. What's the reason, is RN's Gradle build somehow incompatible with Nuclide ? It seems like an unnecessary condition just to discourage people compiling RN from source.

**Comment by lwinkyawmyat** [comment]
@facebook-github-bot label Android

**Comment by hramos** [comment]
I'm not sure Nuclide debugging is ready just yet for use in the open source builds. For now, this is something that's only supported internally at Facebook.

**Comment by hey99xx** [comment]
If you're not sure why close the issue? Maybe it was a mistake to put that check in the first place and it actually works, then there's value keep this issue open.
