### ISSUE TITLE
Image resizeModes `contain` & `center` render incorrectly on Android

### ISSUE THREAD

**Issue by motiz88** [facebook/react-native#17684]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

I don't have the CLI set up, or rather, I don't know how to invoke it from a local Git copy of `react-native`. For the sake of complying with the issue template, my environment is:

  Environment:
    OS: macOS High Sierra 10.13.2
    Node: 8.9.3
    Yarn: 1.3.2
    npm: 5.5.1
    Watchman: 4.7.0
    Xcode: Xcode 9.0.1 Build version 9A1004
    Android Studio: 3.0.1 AI-171.4443003

Packages:
   `react-native` at latest `master` (431670f)
   `react`:  16.2.0 => 16.2.0

Target Platform: Android (I am running 7.0 on Genymotion)

### Steps to Reproduce

1. Run RNTester on both iOS and Android.
2. Go to the `<Image>` page on both and scroll down to the "Resize Mode" section.
3. Observe the difference between the rendering of the `contain` images on both, for the case where the image is larger than its view.
4. Observe the similarly broken rendering of `center` (which is an Android-only value of `resizeMode`)

##### `resizeMode="contain"`

The image should be scaled down to fit the view in a "letterboxed" manner, leaving empty space at the top and bottom in this case. See [documentation](https://facebook.github.io/react-native/docs/image.html#resizemode):

> `contain`: Scale the image uniformly (maintain the image's aspect ratio) so that both dimensions (width and height) of the image will be equal to or less than the corresponding dimension of the view (minus padding).

And see correct behaviour on iOS:

<img src=https://user-images.githubusercontent.com/2246565/34461897-4e12008e-ee2f-11e7-8581-1dc0cc8f2779.png width=300>

##### `resizeMode="center"`

(See also: #17759)

No corresponding iOS screenshot, and the documentation currently [omits this value](https://facebook.github.io/react-native/docs/image.html#resizemode). However, it's clear from the actual behaviour (see below) that there is a bug, similar to the `contain` case.

### Actual Behavior

On Android, for both `resizeMode="contain"` and `resizeMode="center"`, the shrunk image (bottom set of examples, blue background) seems to be drawn on top of an incorrectly scaled or unscaled copy of itself: 

<img src=https://user-images.githubusercontent.com/2246565/34462337-db5f5518-ee39-11e7-8f92-321578585240.png width=300>

### Reproducible Demo

Reproducible in RNTester as-is. I can also put together a Snack if that helps.

**Comment by RidaRidss** [comment]
import ImageResizer from "react-native-image-resizer";    



// first upload image with resizing using below block of code 

  if (image_uri) {
        ImageResizer.createResizedImage(image_uri, 800, 600, "JPEG", 100)
          .then(resizedImage => {
            this.setState({
              image: resizedImage.uri
            });
          })
          .catch(err => {
            console.log(err);
          });
      }

// show image after resize 

  <Image
              style={{
                // marginTop: 20,
                width: Metrics.image.tiny,
                height: Metrics.image.tiny
              }}
              source={Images.next}
              resizeMode="contain"
            />

**Comment by motiz88** [comment]
@RidaRidss that looks like a reasonable workaround for these `resizeMode` issues; there's also [`ImageManipulator`](https://docs.expo.io/versions/latest/sdk/imagemanipulator.html) for Expo users.

**Comment by motiz88** [comment]
After a bit of digging, this is likely due to https://github.com/facebook/fresco/issues/153.

**Comment by kimthangatm** [comment]
I get sample error, because I forgot style Image with `width and height`

```js
{image && (
  <Image
    source={image}
    style={{
      width: 188,
      height: 188,
      position: 'absolute',
      resizeMode: 'contain',
    }}
  />
)}
```
