### ISSUE TITLE
Change Font in React Native ART Library

### ISSUE THREAD

**Issue by ShaikhKabeer** [facebook/react-native#17691]
Hello Guys,

I have used React Native ART library in my code. 

` <Text font=`{`40px "Helvetica Neue", "Helvetica", Arial`} `
    fill="#000000" alignment="center" >`
  `  {midValue}`
 `</Text>`

Here "Helvetica Neue" font is already used. But I want to change font. How can I do this ? Need help

**Comment by ShaikhKabeer** [comment]
I just want to change the font. How can I do this ?

**Comment by ShaikhKabeer** [comment]
`import React, { Component } from 'react'
`import {
 ` Surface,
  `Shape,
  `Path,
  `Text,
  `RadialGradient
} from 'ReactNativeART'

export default class WordPath extends Component {
  render() {
    const circle = new Path()
      .move(25, 50)
      .arc(25, 25, 1)
      .arc(-25, -25, 1)

    const textPath = new Path()
      .lineTo(100, 225)

    const gradient = RadialGradient(['red 20%', 'green 40%', 'yellow 80%'], 20, 20, 80, 80, 140, 120)

    return (
      <Surface width={250} height={150}>
        <Shape d={circle} fill="teal" />
        <Text
          x={100}
          y={50}
          font="24px helvetica"
          fill="orange"
          path={textPath}
        >
          Text!
        </Text>
      </Surface>
    )`
  }`
}`

**Comment by yiday** [comment]
you can do this 
`
class Blink extends Component {
  constructor(props) {
    super(props);
    this.state = {
      showText:true,
      style:{
        fontSize:20,
        fontFamily:'Cochin'
      }
    }

    setInterval(()=>{
      this.setState(previousState=>{
        return {showText:!previousState.showText};
      });
    }, 1000);
  }

  render() {
    let mystyle = this.state.showText ? this.state.style: {
      fontSize:40,
      fontFamily:'arial'
    };
    return (
      <View>
      <Text style={mystyle}>Hello,React-Native</Text>
      </View>
    )
  }

}


export default class App extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Blink text="this is my code" />
      </View>
    )
  }
}

const styles = StyleSheet.create({
  container: {
    flex:1,
    justifyContent:'center',
    alignItems:'center'
  },

  item: {
    fontSize:20,
    fontFamily:'Cochin'
  }
})`
