### ISSUE TITLE
All the animations in my project are running really slow after upgrading to v0.6

### ISSUE THREAD

**Issue by wootwoot1234** [facebook/react-native#1770]
I'm using NavigationIOS and the page transitions are super slow (about 2 seconds to finish animation).  Also when I type cmd+d the menu from the bottom also takes about 2 seconds to slide up.   I haven't made any changed to my code since I upgraded to v0.6.

Anyone else having this issue? Any ideas?

**Comment by brentvatne** [comment]
@wootwoot1234 - device or simulator?

**Comment by wootwoot1234** [comment]
simulator

**Comment by jeanregisser** [comment]
Wild guess, did you turn on slow animations on your simulator?

**Comment by wootwoot1234** [comment]
@jeanregisser Yup. :/  I'm not sure how but it was on.  Thanks!
