### ISSUE TITLE
Error: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by 1966767119** [facebook/react-native#17700]
Error: getaddrinfo ENOTFOUND dpq5q02fu5f55.cloudfront.net dpq5q02fu5f55.cloudfront.net:443
step:
create-react-native-app AwesomeProject

cd AwesomeProject
npm start
and press i
下午11:18:30: Starting iOS...
Error: getaddrinfo ENOTFOUND dpq5q02fu5f55.cloudfront.net dpq5q02fu5f55.cloudfront.net:443

 › Press a to open Android device or emulator, or i to open iOS emulator.
 › Press q to display QR code.
 › Press r to restart packager, or R to restart packager and clear cache.
 › Press d to toggle development mode. (current mode: development)

please help me

**Comment by 1966767119** [comment]
ok,I will open a new issue.

**Comment by stonyme** [comment]
Do not use the create-react-native-app to create RN project,use the"react-native init appName",and cd to appName ,"npm install",when install completed, "npm start",then "react-native run-ios".it's work.
