### ISSUE TITLE
Items past the initialNumToRender are not rendering after onRefresh in a VirtualizedList

### ISSUE THREAD

**Issue by flavio-dev** [facebook/react-native#17707]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

 Environment:
  OS: macOS High Sierra 10.13.2
  Node: 9.3.0
  Yarn: 1.3.2
  npm: 5.5.1
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.0 => 0.52.0

  Target Platform: iOS (11.2) (also on Android)

### Steps to Reproduce

(Write your steps here:)

1. Create a VirtualizedList with a long list of items (I have 200)
2. The renderItem returns an Image of 160px high and 160px wide
3. Edit the Stylesheet for that VirtualizedList to be
```
flexDirection: 'row',
justifyContent: 'space-around',
flexWrap: 'wrap'
```
4. It should render the list of images with 2 items per row
5. scroll down for a bit so the VL render a lot of items
6. Back at the top of the screen and pull/refresh so onRefresh gets called
7. The new data is completely different (200 new items) and so the images start to update. It renders the first N images as expected
8. Start scrolling and realise that past the initial rendered new images, there is a void underneath until bottom of screen as prior to refresh the view was scrolled a lot deeper.

### Expected Behavior

(Write what you thought would happen.)

Would have expected that once reaching the last of the initial images re rendered, the next batch would be loaded. That or the view height would be set back to the height of the initial set of images, so reaching the last one would trigger the rendering of the next batch.

### Actual Behavior

(Write what happened. Add screenshots!)

Once arriving at the last image there is a void of the size of the first deep scrolling in step 5.

<img width="336" alt="screen shot 2018-01-22 at 18 34 37" src="https://user-images.githubusercontent.com/5730835/35234907-f3bf337e-ffa2-11e7-9beb-af3fd99a1a8d.png">

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

Here is code of my VL:

```
<VirtualizedList
  data={this.props.userList}
  keyExtractor={(item, index) => {
    return item.get('email')
  }}
  getItem={(data, index) => data.get(index)}
  getItemCount={(data) => data.size}
  contentContainerStyle={gridStyle}
  backgroundColor={backgroundColorVl}
  renderItem={({item}) => {
      return (
        <View backgroundColor={colorWhite} style={styles.gridElm}>
          <Image
            resizeMode={'cover'}
            source={{uri: item.get('picture').get('large')}}
            style={{
              height: this.state.dimensionItem,
              width: this.state.dimensionItem
            }}
            defaultSource={{uri: profileImageUri}}
          />
          <Text>{`${item.get('name').get('first')} ${item.get('name').get('last')}`}</Text>
        </View>
      )
  }
  refreshing={this.state.refreshing}
  onRefresh={this.onRefresh}
/>
```

The reason I am using this VL for a grid view is because libraries for GridView such as [react-native-super-grid](https://github.com/saleel/react-native-super-grid) use ListView which is deprecated, and I am using Immutable (supported only by VirtualizedList to my knowledge).

The problem does not happen on when I am not using the StyleSheet `flex-wrap`. As expected, with 1 item per row it seems to work fine. I am wondering if that is linked.

Cheers

**Comment by flavio-dev** [comment]
I would extend this by wondering why the numColumns attribute that is available for FlatList isn't made available for VirtualizedList? That would pretty much solve the problem/

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (164/150 (109%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o10.sgmail.github.com ([167.89.101.201]:5007)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-a7b0-hello=salmanwaheed.info@sgmail.github.com>)
	id 1epQUy-003J1V-5w
	for hello@salmanwaheed.info; Fri, 23 Feb 2018 20:27:44 -0700
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=0PatcxIRNdYjQFY5owrmFGesIHI=; b=hewK8ai9ltdtgE6b
	F/IxAcAy4/BuJgwS+ZHFi+VOcDmyjz5yEp1fN6dG82y49F/YlS/iHebdCC9zLLMD
	7lhlkETx0FPLJyV9UrIKVqf4xJw38lLaMBQyJ4qyZdqyAzhvEqYG+50gRIVXw/ci
	55VxYuTGdrTZUXRsZ7LAmQLemcE=
Received: by filter0456p1iad2.sendgrid.net with SMTP id filter0456p1iad2-21651-5A90DBA5-3
        2018-02-24 03:27:33.177626343 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0007p1iad1.sendgrid.net (SG) with ESMTP id -HKRHs6TTM-nOqjBOXrvvw
	for <hello@salmanwaheed.info>; Sat, 24 Feb 2018 03:27:33.105 +0000 (UTC)
Date: Sat, 24 Feb 2018 03:27:33 +0000 (UTC)
