### ISSUE TITLE
[NavigatorIOS] why I can not do "this.props.navigator.push" in componentDidMount Function?

### ISSUE THREAD

**Issue by vczero** [facebook/react-native#1771]
why  I can not do "this.props.navigator.push" in componentDidMount Function?
if I set a timeout, it works!

```javascript
var _that = this;
setTimeout(function(){
          _that.props.navigator.push({
              title: "首页",
             component: Index,
             leftButtonTitle:" "
          });
 }, 1000);
```

**Comment by carlyeah** [comment]
I have the same question. Faced this some days ago.

**Comment by vczero** [comment]
I have solved this problem.you can  use "nav.state.makingNavigatorRequest":
for example:
(1) in NavigatorIOS
var APP = React.createClass({
  componentDidMount: function(){
    Global.nav = this.refs.nav;
  },

  render: function(){
    return (
      <NavigatorIOS
        style={styles.container}
        ref="nav"
        initialRoute={{
          component: Login,
          title: 'login'
        }}
      />
    );
  }
});


(2)in other module:
var handle = setInterval(function(){
              if(Global.nav.state.makingNavigatorRequest){
                clearInterval(handle);
                _that._goMainPage();
              }
            }, 10);

**Comment by browniefed** [comment]
@brentvatne solved by user.

**Comment by brentvatne** [comment]
NavigatorIOS isn't a high priority, so I'm going to close this. If you stumble upon this and want to contribute a better solution to the above, by all means submit a pull request! :smile:

**Comment by aakashsigdel** [comment]
@brentvatne I am facing the same issue with `Navigator`. If I do `navigator.push` in `componentDidMount`, the current route is replaced by the next route instead of being pushed into the stack.

**Comment by Kentverger** [comment]
@aakashsigdel Hello, I have the same problem, did you solve the problem and how?

**Comment by vkwitshana** [comment]
I also have the same problem :(
