### ISSUE TITLE
View : aspectRatio + marginBottom = marginRight

### ISSUE THREAD

**Issue by yairopro** [facebook/react-native#17718]
### Is this a bug report?

Yes.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?
Partially

### Environment
https://snack.expo.io/r1W-XxSSG

Environment:
  OS: Windows 10
  Node: 8.9.0
  Yarn: 1.2.1
  npm: 5.5.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: ^0.51.0 => 0.51.0

  Target Platform: Android

### Steps to Reproduce
1. Create a square view : `aspectRatio = 1`
2. Give it a background color, in order to see it : `backgroundColor = "#aaa"`
3. Add a margin at the bottom (let's say 10) : `marginBottom : 10`
4. Now our view should look like this : `<View style={{aspectRatio : 1, backgroundColor : "#aaa", marginBottom : 10}}/>`

### Expected Behavior

I expect from this view to fill the width of its parent (if `flexDirection` is column as it's default value), and have some margin at its bottom.
[See here](https://image.ibb.co/cBwheG/Screenshot_20180123_194823.png)
### Actual Behavior

Adding some margin bottom with the aspect ratio added a margin to the right of the view.
[See here](https://dl2.pushbulletusercontent.com/ezROAnuhdDsggSMrkcnhJpauaaRBYeVM/Screenshot_20180123-194823.png)

### Reproducible Demo

[Here the live demo](https://snack.expo.io/r1W-XxSSG).

**Comment by yairopro** [comment]
The problem is still occuring in the live demo, and I suppose that it uses the latest react-native version. Then the issue is still a problem.

**Comment by allenhsu** [comment]
Why is this issue closed? Is it fixed? We're using v0.52 encountering same problem, although there're workarounds like adding the margin to outer container. But just wondering if it's fixed in latest version?

**Comment by Amberon** [comment]
The issue is actual in 0.58
