### ISSUE TITLE
Invalid YGJustify 'space-evenly'

### ISSUE THREAD

**Issue by aputinski** [facebook/react-native#17728]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

  Environment:
    OS:  macOS High Sierra 10.13.2
    Node:  8.7.0
    Yarn:  1.3.2
    npm:  5.5.1
    Watchman:  4.9.0
    Xcode: 9.2 (9C40b)
  Packages: (wanted => installed)
    react-native: 0.52.1
    react: 16.2.0
  Target Platform: iOS (11.2)

### Steps to Reproduce

1. `react-native init MyProject`
2. Add `<View style={{ justifyContent: 'space-evenly' }} />` to `App.js`
3. `react-native run-ios`

### Expected Behavior

According to https://github.com/facebook/react-native/releases/tag/v0.52.0 `justifyContent: space-evenly` was introduced and should NOT crash the app.

### Actual Behavior

Red error screen with error: `Invalid YGJustify 'space-evenly'`

![screen shot 2018-01-24 at 11 21 55](https://user-images.githubusercontent.com/603528/35343568-f7e327ba-00f8-11e8-979b-1e7dd4607df6.png)

**Comment by danieljvdm** [comment]
I get a similar error on 0.52.1

![simulator screen shot - iphone 7 - 2018-01-26 at 08 58 27](https://user-images.githubusercontent.com/3450486/35428336-1a460f14-0277-11e8-9bd0-4db4f65d6cb9.png)

**Comment by gedeagas** [comment]
i am working on a PR for this.

**Comment by gedeagas** [comment]
#17805

**Comment by gedeagas** [comment]
Submitted a pr
#17805

**Comment by mizinin** [comment]
Thanks @gedeagas.
Does this PR have any chance to get cherry-picked into 0.53 branch?

**Comment by woowalker** [comment]
@gedeagas , still face the problem like @danieljvdm,
* "react": "16.2.0",
* "react-native": "0.53.0"
both create-react-native-app and react-native init projectName, can not run justifyContent: 'space-evenly'

**Comment by mtt87** [comment]
Facing the same issue I've upgraded with `react-native-git-upgrade` to `rn@0.53.3` but I can't use `justifyContent: 'space-evenly'` (currently testing on iOS)

**Comment by davidpaulsson** [comment]
Yup, it's the same here. Not working on Android nor iOS.
```"react": "16.0.0", "react-native": "0.53.0"```

**Comment by defrian** [comment]
the same here. Not working on iOS.
"react": "16.2.0", "react-native": "0.53.3",

**Comment by gedeagas** [comment]
Hi guys, sadly for now this feature can only be used from react-native version 0.54 above.
sorry for the inconvenience. 
@woowalker @mtt87 @davidpaulsson @defrian

**Comment by mtt87** [comment]
Good to know :) thanks for the update

**Comment by turnrye** [comment]
Owning up to this -- I mistook this entry. Will update the 0.52 changelog to reflect that this was foundational work rather than ready for use.
