### ISSUE TITLE
getDefaultProps doesn't work with ES6 syntax; warning is not helpful

### ISSUE THREAD

**Issue by fatuhoku** [facebook/react-native#1772]
I'm trying to build a component that defines a default value for a required prop, but it doesn't seem to work.

```js
class ReviewsList extends Component {
  propTypes: {
    reviews : React.PropTypes.array.isRequired,
  }
  getDefaultProps() {
    return {
      reviews: [],
    };
  }
  render() {
    var reviewItems = this.props.reviews.map(function (review) {  // ERROR
      return (
        <RecipeReviewItem key={review.objectId} reviewText={review.reviewText}></RecipeReviewItem>
      )
    });

    return (
      <View>{reviewItems}</View>
    );
  }
}
```

When I run this, I get:

`ERROR: undefined is not an object (evaluating 'this.props.reviews.map')`

Why?

**Comment by fatuhoku** [comment]
Upon inspecting the console log I got this message:

"Warning: getDefaultProps was defined on Blah, a plain JavaScript class. This is only supported for classes created using React.createClass. Use a static property to define defaultProps instead."

What does that even mean? What's a static property? How do you 'define defaultProps'? An example is worth its weight in gold herre.

**Comment by fatuhoku** [comment]
I've tried

```js
  static defaultProps: {
      reviews: []
  }
```

```js
  static defaultProps: {
      reviews: []
  }
```

```js
  static defaultProps() {
    return {
      reviews: []
    };
  }
```

But none of these work.

**Comment by andreypopp** [comment]
```
 static defaultProps = {
      reviews: []
  }
```
should work

**Comment by cyprusglobe** [comment]
try this

## Original
```
class ReviewsList extends Component {
  propTypes: {
    reviews : React.PropTypes.array.isRequired,
  }
  getDefaultProps() {
    return {
      reviews: [],
    };
  }
  render() {
    var reviewItems = this.props.reviews.map(function (review) {  // ERROR
      return (
        <RecipeReviewItem key={review.objectId} reviewText={review.reviewText}></RecipeReviewItem>
      )
    });

    return (
      <View>{reviewItems}</View>
    );
  }
}
```

## New
```
class ReviewsList extends Component {
  render() {
    var reviewItems = this.props.reviews.map(function (review) {  // ERROR
      return (
        <RecipeReviewItem key={review.objectId} reviewText={review.reviewText}></RecipeReviewItem>
      )
    });

    return (
      <View>{reviewItems}</View>
    );
  }
}

  ReviewsList.propTypes: {
    reviews : React.PropTypes.array.isRequired,
  }
  ReviewsList.getDefaultProps() {
    return {
      reviews: [],
    };
  }
```

**Comment by fatuhoku** [comment]
Thanks @cyprusglobe. Fantastic answer, and a really informative link. It's working very well now, thanks. When RN moves towards ES6 in earnest the documentation examples must be updated to show this.

**Comment by vhmth** [comment]
+1 @cyprusglobe

**Comment by seanfuture** [comment]
For future visitors, ES6 syntax for latest version should be ( none of the above ):

## Revised
```
ReviewsList.propTypes = {
   reviews : React.PropTypes.array.isRequired,
}

ReviewsList.defaultProps = {
      reviews: [],
}
```

**Comment by jcsmesquita** [comment]
isRequired doesn't throw an error when the prop isn't provided... I've had this issue with RN ES6 for a long time. Am I missing something?

**Comment by AlexChaseJones** [comment]
for future users here is es2015 syntax for defaultprops...
```
static get defaultProps() {
      return {
             //Add your stuff here
     }
}
```

**Comment by ide** [comment]
`defaultProps` just needs to be a static property on the component class. How you want to do this is up to you.

**Static property:**
```js
class C1 extends React.Component {
  static defaultProps = {
    prop: 'hello',
  };
}
```

**Static getter:**
```js
class C2 extends React.Component {
  static get defaultProps() {
    return {
      prop: 'hello',
    };
  }
}
```

**Assign a property:**
```js
class C3 extends React.Component {
}
C3.defaultProps = {
  prop: 'hello',
};
```

**Comment by angelo24983** [comment]
Last suggestion is the good one.
Please update documentation as said by @liperuf

**Comment by danoz73** [comment]
https://github.com/facebook/react-native/commit/9864c3a0dfe0aeb0cd9633e9adb381a3388de9bf#diff-a827bf1fa682284e142f4dd5bdb741d2

**Comment by zargold** [comment]
what are the conditions by which defaultProps will be followed?

I have a component which accepts a 

```javascript
slot: PropTypes.shape({
    fields: PropTypes.shape({
      stories: PropTypes.object
    }),
    permitted: PropTypes.array
  }).isRequired,
```
The thing is that permitted is seeded into the database but fields are blank when the db query is made (if there's nothing already stored for these fields).

So as a result it seems like: 
```javascript
let stories = Array.from({length: 17}, (v, k) => {
  return {
    link: '',
    bannerImage: 'http://fakeimg.pl/525x295/?text=Story%20Image',
    title: 'Story Title',
    shortDescription: 'Short Description of this article',
    articleDescription: 'Analyst\'s Picks:'
  }
})
console.log(stories) //=> this works just fine in building an array
FeaturedStories.defaultProps = {
    slot: {
      fields: { stories },
    },
}
```
But unfortunately in the render function:
```javascript
console.log(this.props) // {slot: {fields = Empty{}(just as in the db }, permitted: ['from the database', 'from db']
return (
<div>
  { slot.fields && typeof slot.fields == 'object' && slot.fields.stories &&
  <div>
   Never Renders :(
  </div>
  }
</div>
)
//also 
return (
  <div>
    { JSON.stringify(slot.fields.stories)} {<!--blank -->}
  </div>
)
```

**Comment by yanbober** [comment]
@ide very good! nice.

**Comment by ConAntonakos** [comment]
At what proposal stage is the static getter syntax? Is that stable enough to confidently implement?

**Comment by ide** [comment]
It's at Stage 2 and the champion is currently at Facebook. I think the syntax might change (or might not) but you could write a codemod or similar source transformer to transpile from old syntax to new if that happened.

**Comment by noahehall** [comment]
@ide  you saved the day

**Comment by libin1991** [comment]
static get defaultProps() {
  return {
       yourkey: yourvalue
  }
}

**Comment by golestanirad** [comment]
I tried to find some more info about `contextTypes`, `propTypes  ` and `defaultProps  `at _React Native_  doc but I failed, could you tell me where we can find a doc for them?

**Comment by naiduprakash** [comment]
works like charm with **es6**
```
class ReviewsList extends Component {
  static propTypes = {
     reviews : PropTypes.array.isRequired,
  };
  static defaultProps = {
     reviews: [],
  };
  render() {
    var reviewItems = this.props.reviews.map(function (review) {  // ERROR
      return (
        <RecipeReviewItem key={review.objectId} reviewText={review.reviewText}></RecipeReviewItem>
      )
    });

    return (
      <View>{reviewItems}</View>
    );
  }
}
```
