### ISSUE TITLE
TouchableOpacity does not respond immediately to changes in opacity property

### ISSUE THREAD

**Issue by 1335382915** [facebook/react-native#17723]
### Is this a bug report?
Yes  
### Have you read the Contributing Guidelines?
Yes
### Environment:
OS:  windows 7
Node:  6.11.0
npm:  3.10.10

### Packages: 
react-native: 0.51.0
react: 16.0.0
### Steps to Reproduce
Just modify the opacity of the TouchableOpacity style property:
```
//constructor
this.state = {disabled: false}
//render
const opacity = this.state.disabled ? 0.6 : 1;
//return
<View>
    <TouchableOpacity style = {{width: 100, height: 50, backgroundColor: 'red', opacity}} />
    <Button title = {'disable'} onPress = {() => this.setState({disabled: true})} />
</View>
```
Click the button, and there is no change in vision, but the opacity really turns into 0.6 `console.log(opacity); //0.6`. After I clicked the TouchableOpacity, it worked fine.

If I replace TouchableOpacity with TouchableHighlight, everything works well.

**Comment by 1335382915** [comment]
change the code

**Comment by RidaRidss** [comment]
// For immediate response 

 constructor(props) {
    super(props);
    this.state = {disabled: false}
  }

  render() {
    const opacity = this.state.disabled ? 0.6 : 1;    
    return (
      <View>

      <TouchableOpacity onPress={()=>{
        if(this.state.disabled) {
          this.setState({disabled:false})
        }else {
          this.setState({disabled:true})
          
        }
      }} style = {{width: 100, height: 50, backgroundColor: 'red', 
     opacity: opacity 
   }} />
      </View>
    );
  }

**Comment by mmazzarolo** [comment]
I don't understand @RidaRidss solution. 

I'm having the same issue on `react-native@0.53.0`.
