### ISSUE TITLE
[LayoutAnimation] success err functions only called on first call

### ISSUE THREAD

**Issue by mschipperheyn** [facebook/react-native#1773]
I have a toast that I want to autoremove after a short delay. The problem I have is that the success function is only called on the first time the function is called. After that only the animation is executed, but the success (or error) call is ignored. Not sure why

	componentWillUpdate(nextProps, nextState){

		if(nextState.visible === this.state.visible)
		  return;

		var instance = this;

		//On the chance that there is a timeout waiting to be executed,
		//we want to stop that because if a toast gets called twice in a row, only the last one should count
		if(timeout)
		  clearTimeout(timeout);

		//if the state changes we want to animate the toast either from the bottom or from the top
		LayoutAnimation.configureNext(this.state.visible? animations.hide : animations.show,function(){

		  //the animation has ended. If we want to autoHide, we should hide it after a delay
		  if(instance.props.autoHide && instance.state.visible){
			timeout = setTimeout(function(){

			  instance.setState({
				visible:false
			  });

			},1200);

		  }else if(!nextState.visible){
			//we'r done animating so time to remove if we're hidden
			instance.setState({
			  visible:false
			});
		  }

		},function(err){
		  console.log(err);
		});

	  },

**Comment by sahrens** [comment]
What kind of animation is this doing?  Do you have more code and a video/gif?  Might be a better fit for Animated rather than LayoutAnimation.

I'll also look into the broken callback.

**Comment by mschipperheyn** [comment]
It's basically a toast that moves into the screen from the bottom and is supposed to move out after a small timeout.

**Comment by sahrens** [comment]
I'd definitely recommend Animated then :)

**Comment by mschipperheyn** [comment]
Thanks. I'll have a go with that then. Still Newbie. But it's great to work w this stuff. React-Motion also looks great BTW

**Comment by mschipperheyn** [comment]
Still trying to wrap my head around Animated.

I get singleValue.stopTracking is not a function on the following. Any suggestions?
Also, is there a simple "delay" feature so that a sequence can wait in between two animation cycles?

  componentWillUpdate(nextProps, nextState){

    if(nextState.visible === this.state.visible)
      return;

    var showSequence = Animated.decay(
      this.state.position,{
          toValue:0
      });

    var hideSequence = Animated.decay(
      this.state.position,{
          toValue:-150
      });

    if(nextState.visible){

        Animated.sequence([showSequence,hideSequence]).start(function(){
          //animation has completed
          this.setState({
            visible:false
          });
        });

    }else{

      hideSequence.start(function(){
        //animation has completed
        this.setState({
          visible:false
        });
      });

  	}
  }

**Comment by ide** [comment]
@mschipperheyn a couple of your functions should be arrow functions. That might fix a couple bugs.

> Also, is there a simple "delay" feature so that a sequence can wait in between two animation cycles

Animated.timing takes a delay so you could animate with the same to & from values to simulate a delay.

**Comment by browniefed** [comment]
@mschipperheyn is this still an issue?

**Comment by brentvatne** [comment]
@mschipperheyn - if you're still stuck on this, I'd recommend trying your luck with StackOverflow -- it's much better suited for support questions, whereas this is better for bug reports / feature requests! :smile: good luck :+1: :rocket: :guitar:

**Comment by sahrens** [comment]
Didn't we implement Animated.delay?  I think you can stick that between
animations in your sequence array.

**Comment by mschipperheyn** [comment]
Yeah, this issue is obsolete
