### ISSUE TITLE
Failed to notify project evaluation listener.

### ISSUE THREAD

**Issue by pankaja92** [facebook/react-native#17730]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

 Environment:
  OS: Linux 4.13
  Node: 9.4.0
  Yarn: Not Found
  npm: 4.6.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.0 => 0.52.0

  Target Platform: Ubuntu 17.10

### Steps to Reproduce

1. Followed official docs and started react project using `react-native init`
2. And tried to run the project on an Android device by `react-native run-android`
3. Got an [error](https://github.com/facebook/react-native/issues/17688) and fixed it by uninstalling Java 9 and installing JDK 8.
4. Then again tried to run the project by `react-native run-android`

### Expected Behavior

Start the project and run the app on the connected device which is an adb recognized and configured device.

### Actual Behavior
```

Scanning folders for symlinks in /home/pankaja/Documents/Projects/react-native/AwesomeProject/node_modules (10ms)
JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug)...

> Configure project :app 
The CompileOptions.bootClasspath property has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the CompileOptions.bootstrapClasspath property instead.


FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > com.android.build.gradle.tasks.factory.AndroidJavaCompile.setDependencyCacheDir(Ljava/io/File;)V

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html
```

### Reproducible Demo

1. Followed official docs and started react project using `react-native init`
2. And tried to run the project on an Android device by `react-native run-android`
3. Got the error

followed this [official react-native docs](https://facebook.github.io/react-native/docs/getting-started.html)

**Comment by ThHareau** [comment]
Have you seen this? https://github.com/react-community/create-react-native-app/issues/478

**Comment by pankaja92** [comment]
@ThHareau  Yes. I followed that and installed JDK8 and set it as the default JDK. But I got the same error. Then I searched Stackoverflow and followed [this](https://stackoverflow.com/questions/43415673/occurred-configuring-project-app-failed-to-notify-project-evaluation-liste) as it says the error is because of 2 JDKs installed in the machine, I removed JDK9. But still I'm getting the error.

**Comment by ThHareau** [comment]
It worked for me, I can really help you more :S

**Comment by pankaja92** [comment]
Thanks @ThHareau then I think it's with JDK 9. I just removed JDK 9 using `sudo rm -rf jdk-9` which was in my `/usr/lib/jvm` folder and I've already set jdk 8 as the default jdk by following previously mentioned issue. Still I'm getting the error.

**Comment by pankaja92** [comment]
Fixed by completely removing both JDKs and reinstalling JDK 8
