### ISSUE TITLE
"message : Incomplete login details" while logging in to an remote server. 

### ISSUE THREAD

**Issue by manisha-sinha01** [facebook/react-native#17735]
### Is this a bug report?

(write your answer here)No.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.)
Yes
### Steps to Reproduce

(Write your steps here:)

1.I am trying to login to a remote server using fetch by passing the username nad passowrd.

2.but the login is unsuccessful. The error log is showing "message: Incomplete login details"
3.i am passing the username and password which is required for the login.

### Expected Behavior

It should get logged in and show "login successful".

### Actual Behavior

it is showing "Incomplete login details"
**the error log:-**
[SyntaxError: JSON Parse error: Unrecognized token '<']
  line: 14957,
  column: 16,
  sourceURL: 'http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false' }
adb logcat
11:53:08 AM
{ message: 'Incomplete login details',
  exc: '["Traceback (most recent call last):\\n  File \\"/home/ubuntu/frappe-bench/apps/frappe/frappe/app.py\\", line 59, in application\\n    init_request(request)\\n  File \\"/home/ubuntu/frappe-bench/apps/frappe/frappe/app.py\\", line 121, in init_request\\n    frappe.local.http_request = frappe.auth.HTTPRequest()\\n  File \\"/home/ubuntu/frappe-bench/apps/frappe/frappe/auth.py\\", line 53, in __init__\\n    frappe.local.login_manager = LoginManager()\\n  File \\"/home/ubuntu/frappe-bench/apps/frappe/frappe/auth.py\\", line 107, in __init__\\n    if self.login()==False: return\\n  File \\"/home/ubuntu/frappe-bench/apps/frappe/frappe/auth.py\\", line 126, in login\\n    self.authenticate(user=user, pwd=pwd)\\n  File \\"/home/ubuntu/frappe-bench/apps/frappe/frappe/auth.py\\", line 197, in authenticate\\n    self.fail(_(\'Incomplete login details\'), user=user)\\n  File \\"/home/ubuntu/frappe-bench/apps/frappe/frappe/auth.py\\", line 226, in fail\\n    add_authentication_log(message, user, status=\\"Failed\\")\\n  File \\"/home/ubuntu/frappe-bench/apps/frappe/frappe/core/doctype/activity_log/activity_log.py\\", line 44, in add_authentication_log\\n    }).insert(ignore_permissions=True)\\n  File \\"/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py\\", line 217, in insert\\n    self._validate_links()\\n  File \\"/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py\\", line 724, in _validate_links\\n    frappe.LinkValidationError)\\n  File \\"/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py\\", line 323, in throw\\n    msgprint(msg, raise_exception=exc, title=title, indicator=\'red\')\\n  File \\"/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py\\", line 309, in msgprint\\n    _raise_exception()\\n  File \\"/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py\\", line 282, in _raise_exception\\n    raise raise_exception(encode(msg))\\nLinkValidationError: Could not find User: Unknown User\\n"]',
  _server_messages: '["{\\"message\\": \\"Could not find User: Unknown User\\", \\"indicator\\": \\"red\\"}"]' }
adb logcat
11:53:09 AM
New Messages

00myapp/src/Components/Component1/Component2.js73:1(71, 1415)
LFUTF-8JavaScript0 files

the code is given below:- 

`import React, { Component } from 'react';
import {
  AppRegistry,
  ActivityIndicator,
  ListView,
  Text,
  View,
  StyleSheet,
  ScrollView,
  Button
} from 'react-native';

export default class Component2 extends Component {

  static navigationOptions = {
    'title' : 'GO',
  };

  constructor(props){
    super(props);
    this.state = {
        value:'',
    }
  }

componentWillMount() {

    fetch('https://runga.rungamatteegroup.com/api/method/login',
      {
       method: 'POST',
       headers: {
         Accept: 'application/json',
         'Content-type':'application/json'
       },
       body: JSON.stringify({
         username:'Administrator',
         password:'***********'
       }),
     })
     .then((response) => response.json())
     .then((responseJson) => {console.log(responseJson);})
     .catch((error) => {
       console.log(error);
     });

     fetch('https://runga.rungamatteegroup.com/api/method/frappe.auth.get_logged_user')
     .then((response) => response.json())
     .then((responseJson) => {this.setState(value:responseJson);})
     .catch((error) => {
       console.log(error);
     });
}

  componentDidMount() {
    //console.log("inside did");
  }

  render(){
    console.log("ya render");

    return(

      <View>
           <Text>{this.state.value}</Text>
      </View>
    );
  }
}
AppRegistry.registerComponent('Component2' , () => Component2);
`
### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by xpertogo** [comment]
im having the same issue.
if my android is on the same LAN network it logsin fine but if my android is on another network, then it does not connect

login = () => {
  	fetch('http://xpertogo.ddns.net:3000/users', {
  		method: 'Post',
  		headers: {
  			'Accept': 'application/json',
  			'Content-Type': 'application/json',
  		},
  		body: JSON.stringify({
  			username: this.state.username,
  			password: this.state.password,
  		})
  	})
  	.then((response) => response.json())
  	.then ((res) => {

  //      alert(res.message);

  		if (res.success === true) {
  			AsyncStorage.setItem('users', res.users);
  			this.props.navigation.navigate('Profile');
  		}
  		else{
  			alert(res.message);
  		}
  	})
  	.done();
  }

**Comment by manisha-sinha01** [comment]
Try passing the username and password as a query string after the URL..arent you accessing the URL through its API?? If you get the api then pass it after the query string of the api. I think it will work instead of passing it in the body part of fetch.

**Comment by xpertogo** [comment]
I don't get you, sorry im a newbie, can you tell me step by step
can you edit the code so i can understand.

is it possible to get your skype

Thanks

**Comment by manisha-sinha01** [comment]
`let password= 'password';
    let username= 'username';
   let url= 'http://xyz.com/api/method/login?usr='+ username +'&pwd='+password;
  console.log(url);
  fetch(url,
 {
  method: 'POST',
  headers: {
    Accept: 'application/json',
    'Content-Type': 'application/json',
  },

 })
  .then( (response) => response.json() )
  .then( (responseJson) => {console.log(responseJson); })
  .catch( (error) => {
    console.error(error);
  });`

This worked for me! I passed it as querystring after my API for the URL i am trying to access.

**Comment by manisha-sinha01** [comment]
Let me know if it worked!

**Comment by manisha-sinha01** [comment]
For accessing an url in the net. You need their APIs. API S

**Comment by manisha-sinha01** [comment]
For accessing any URL on the net. You need their APIs. APIs are gateways for accessing the content present in the url. These APIs connect two applications. The applications you are building and the URL you are accessing is the other application which will be connected with the API of the URL.

So the steps are:-
1. study the documentation of the URL. 
2. Get appropriate APIs for different actions like login,displaying url data,etc.
3.Put the api's URL ,the way i have used in my code.
4.Pass the username and password in the same way.

I hope this helps you!

**Comment by xpertogo** [comment]
Thanks for your help, i will try out in the morning and give the results
