### ISSUE TITLE
Deep linking in Android not working if the app is in the background

### ISSUE THREAD

**Issue by zaguini** [facebook/react-native#17749]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: macOS High Sierra 10.13.2
  Node: 9.0.0
  Yarn: 1.3.2
  npm: 5.5.1
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.1 => 0.52.1

Target Platform: Android 4.0.0 or higher. iOS works fine.

### Steps to Reproduce

1. Add `Linking.addEventListener` to `componentDidMount`, with `alert` callback, just to check if it works;
2. Put the app in background;
3. Open a deep link.

### Expected Behavior

Fire the callback handler specified in the `addEventListener` function.

### Actual Behavior

The callback function simply doesn't get fired. The `getInitialURL()` works as expected (alerts the correct URL in this case, when the app is launched from the deep link click). This issue happens only on iOS, Android works fine.

It looks like that the callback event listener function is not getting fired.

### Reproducible Demo

AndroidManifest.xml
```xml
<activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:launchMode="singleTask"
>
```

index.js
```js
import React, { PureComponent, AppRegistry, View, Linking } from 'react-native'

class Root extends PureComponent {
  componentDidMount() {
    Linking.getInitialURL().then(alert)
    Linking.addEventListener('url', alert)
  }

  render() {
    return (
      <View />
    )
  }
}

AppRegistry.registerComponent('linkingtestapp', () => Root)
```

**Comment by zaguini** [comment]
It looks like there is a bug in the `alert` component in Android... It works if you change to `console.log`, for example. Meh.

**Comment by GopiKrishna10** [comment]
@zaguini Have solved the issue for IOS.

**Comment by alihesari** [comment]
I have same issue in Android.

**Comment by tajammul1996** [comment]
Did anyone found the solution for this?

**Comment by Udbhav12** [comment]
I have the same issue in iOS
@GopiKrishna10 - How did you solve this for iOS ?
