### ISSUE TITLE
[Master Branch] Text Refactor broke TextInput Functionality

### ISSUE THREAD

**Issue by kpink224** [facebook/react-native#17746]
### Is this a bug report?
Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

  Environment:
    OS:  macOS Sierra 10.12.6
    Node:  9.3.0
    Yarn:  1.3.2
    npm:  5.6.0
    Watchman:  4.7.0
    Xcode:  Xcode 9.0 Build version 9A235
    Android Studio:  2.3 AI-162.3764568

  Packages: (wanted => installed)
    react: 16.2.0 => 16.2.0
    react-native: github:facebook/react-native#master => 1000.0.0

### Background
We are exploring the idea of supporting data detection for Text in addition to text input. In our situation, we have rich text that is supposed to detect data patterns in addition to different styling changes. This means we need data detection to work with nested Text components and for all of it to be inline.

### Problem
First off, love the work @shergin did on [this commit](https://github.com/facebook/react-native/commit/2716f53220f947c690d5f627286aad51313256a0). Our text components are rendering ~30% faster!

Unfortunately, TextInput seems to have lost some functionality.
* Clear button doesn't do anything while editing.
* Data Detection does not work anymore.
* When you delete all existing values via keyboard backspace, the text styling defaults to italics.

### Expected Behavior

All mentioned issues above should be working as expected from previous versions of react native.

### Reproducible Demo

This is broken for any project based on master.

**Comment by shergin** [comment]
Oh my, thank you for reporting this!
I will try to repro and fix it asap. I know it annoying but... if you can provide a simple Snack which illustrates the problem, it will speed up the fixing drastically.

**Comment by shergin** [comment]
Well, I could not repro all of this. So, @kpink224, could you please provide exact repro cases?

**Comment by kpink224** [comment]
Hey @Shergin. So update on this issue:

1) The clear button not working was on our end in consequence to the file name changes. This is nothing you need to worry about.

2) When I said that styling defaults to italics, that was our style change. Unfortunately at the time, the style wasn't getting updated when the value was changing.

3) I made a project to reproduce everything today and didn't see the remaining issues anymore -- I could get data detection working again and the styling was changing as expected.

I suppose at this point, this issue is good to close! Thanks for you help and awesome improvement of Text

**Comment by chirag04** [comment]
closing as per above comment. Let us know if this comes up again. 👍
