### ISSUE TITLE
Access to a API rest with https autosigned certificated

### ISSUE THREAD

**Issue by diegoceldranmorell** [facebook/react-native#17740]
Hi, i have a problem, i need to make fetch request to an api rest located in a server with a invalid https certificate, we use https, but with a autosigned certificate, when i try to make the request i have a TypeError: Network request failed, i can make it via curl from my pc, but i CAN'T make anything with fetch in Android, i've not tested it in iOS, but i need it works in both platforms, please, it's really important, i CAN'T change the ssl server certificate, i only can modify mi mobile app made in react-native. Please, help me, i can't find any valid solution...
![image](https://user-images.githubusercontent.com/11218421/35388981-391d90ac-01d6-11e8-9ab2-058b5fd75610.png)

**Comment by perrosnk** [comment]
@diegoceldranmorell Have you found a solution?

**Comment by shilihuan** [comment]
@diegoceldranmorell do you solve the problem, i meet the same problem, i can't find someway to sovle

**Comment by lefrankleal** [comment]
same here! help please

**Comment by zedtux** [comment]
Looking also for a solution to this problem.
