### ISSUE TITLE
Getting Started guide causes a "React Native version mismatch." error.

### ISSUE THREAD

**Issue by joshuapinter** [facebook/react-native#17756]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

```
Environment:
  OS: macOS High Sierra 10.13.2
  Node: 6.9.1
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.50.3 => 0.50.3
```

### Steps to Reproduce

1. `create-react-native-app AwesomeProject`

1. `cd AwesomeProject`

1. `npm run ios`

### Expected Behavior

It runs happily.

### Actual Behavior

It loads the package but then produces a "React Native version mismatch." error with: 

```
JavaScript version: 0.50.3
Native version: 0.52.0
```

<img width="206" alt="screenshot 2018-01-26 12 37 39 non-retina" src="https://user-images.githubusercontent.com/180819/35457382-f340d736-0295-11e8-94af-24d9c6a6da77.png">

### Reproducible Demo

Not necessary as you can follow the steps above to reproduce it. However, here is the Expo QR code:

![screenshot 2018-01-26 12 39 55](https://user-images.githubusercontent.com/180819/35457395-0713d89e-0296-11e8-83ff-edde61bebd98.png)

**Comment by YanNerio** [comment]
Some minutes ago I was facing the same problem

> JavaScript version: 0.50.3
> Native version: 0.52.0

I tried this:
react-native eject
react-native link
react-native run-android
react-native run-ios

And it worked!

**Comment by YanNerio** [comment]
I was facing the same problem minutes ago  (I'm using linux mint 18.3 and Expo Client but maybe it helps), if you've followed this steps 

1. change the version of react-native in package.json  from  "react-native": "0.50.3" to "react-native":"0.52.0", and 
"devDependencies": {
    "react-native-scripts": "1.11.1",
    "jest-expo": "25.0.0",
    "react-test-renderer": "16.2.0"
  },
"dependencies": {
    "expo": "^25.0.0", 
    "react": "16.2.0",
    "react-native": "0.52.0"
  }
2. Deleted **node_modules** folder and 
3. run npm install 

And it didn't worked then try  the following commands to rebuild:

react-native eject
react-native link
react-native run-ios

![27535901_10213296061810310_1417014409_o](https://user-images.githubusercontent.com/7425700/35464620-7edbc88e-02bc-11e8-981a-0e7142c35982.png)

![27393888_10213296061250296_648379256_o](https://user-images.githubusercontent.com/7425700/35464625-8acc64fa-02bc-11e8-8c5d-0e7dd0730e1f.png)

**Comment by YanNerio** [comment]
I was facing the same problem minutes ago (I'm using linux mint 18.3 and Expo Client but maybe it helps), if you've followed this steps

change the version of react-native in package.json from "react-native": "0.50.3" to "react-native":"0.52.0", and
"devDependencies": {
"react-native-scripts": "1.11.1",
"jest-expo": "25.0.0",
"react-test-renderer": "16.2.0"
},
"dependencies": {
"expo": "^25.0.0",
"react": "16.2.0",
"react-native": "0.52.0"
}
Deleted node_modules folder and
run npm install
And it didn't worked then try the following commands to rebuild:

react-native eject
react-native link
react-native run-ios

<img src="https://user-images.githubusercontent.com/7425700/35464620-7edbc88e-02bc-11e8-981a-0e7142c35982.png" width="250" />

<img src="https://user-images.githubusercontent.com/7425700/35464625-8acc64fa-02bc-11e8-8c5d-0e7dd0730e1f.png" width="250" />

**Comment by ide** [comment]
@fson: it looks like CRNA is installing an older copy of RN (0.50.x) but is using the latest SDK version.

**Comment by fson** [comment]
`react-native-scripts` v1.11.0 went out with SDK 23 version numbers by mistake. This has been fixed in the latest `react-native-scripts` release. If you run `create-react-native-app AwesomeProject` again, it will use the latest version. Sorry about the hassle!

**Comment by ide** [comment]
Closing this since it sounds like the issue has been fixed with CRNA / react-native-scripts. If this issue comes up in the future, please feel free to open a new issue.

**Comment by joshuapinter** [comment]
👍  Thanks for the quick fix, guys!
