### ISSUE TITLE
Guidance on how to break up index.ios.js into other Javascript files

### ISSUE THREAD

**Issue by fatuhoku** [facebook/react-native#1775]
My JSX code (including `index.ios.js`) lives in a directory called `jsx/`, so in my `AppDelegate.m`:

```objc
  //...
  jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/jsx/index.ios.bundle"];
```

`index.ios.js` was just getting really big, and I wanted to pull out some class, function and object declarations into `jsx/foobar.js`.

However, when I try to `var Foobar = require('jsx/foobar')` or anything similar, I just get:

![ios simulator screen shot 28 jun 2015 21 58 13](https://cloud.githubusercontent.com/assets/430233/8398304/cec8d684-1de0-11e5-8f8e-67676635adcd.png)

What am I doing wrong?

**Comment by ide** [comment]
Use `require('./foobar')` -- https://nodejs.org/api/modules.html#modules_file_modules

**Comment by fatuhoku** [comment]
Ah. Took me a few packager restarts and trying different syntaxes out but I think I'm much more familiar with the way node handles requires now. Thanks @ide.
