### ISSUE TITLE
[Native UI Components]  Better way needed to use third-part native UI widgets

### ISSUE THREAD

**Issue by vincenting** [facebook/react-native#1777]
Recently I'm tring hard to use [JVFloatLabeledTextField](https://github.com/jverdi/JVFloatLabeledTextField/) in my react-native app, referring to the doc [Native UI Components (iOS)](http://facebook.github.io/react-native/docs/nativecomponentsios.html#content). `JVFloatLabeledTextField` is also a inheritance of `UITextField` just like `RCTTextField`, because the lack of supporting of multiple inheritance in objective-c, i have to copy lots of code in `RCTTextField` and `RCTTextFieldManager` to finish my job. Then when it comes to nodejs, I also have to copy lots of javascript code from `Libraries/Components/TextInput`, to support lots of propTypes and end-to-end tests.

There are some other great third-part ui components in ios such as [FlatUIKit](https://github.com/Grouper/FlatUIKit). I do not think re-implement them with react(javascript) or copy lots of code in both objective-c and nodejs is a good idea.

---

1. In Objective-c, macros should be a better solution. `RCTTextFieldMacro.m` defines all methods and properties as macros those will be used in `RCTTextField` and `RCTTextFieldManager`. So we could use all these macros in our own ui components which has the same superclass, rather than copy those codes.
2. In NodeJS, we can consider add some **inherit** method in `React.Component` rather than only mixins. So, extends `TextInput` and override or add some methods and props will be a better choice.

**Comment by mantouxu** [comment]
who a u

**Comment by brentvatne** [comment]
@vincenting - have you thought about trying to re-implement it in React Native in pure JS as a wrapper around TextInput? As for the FlatUIKit controls, it looks like you could do remake those in the same way. This would make it easier to do have cross-platform components.

**Comment by vincenting** [comment]
Thanks for your reply.@brentvatne.

I have thought about this, but the re-implementing always means that we cannot take advantage of current open source projects, and will build a grand new community.

I would like to treat the react-native as a bridge between the native code (both java and objective-c) and the javascript, so that the development experience of native code should not be ignored. Besides, "Learn once write anywhere" does not mean cross-platform should always be considered in first place 😀.

**Comment by geminiyellow** [comment]
+1 
we need more common way to use existing resources, if everything must be re-implemented once, why not use obj-c or java.

**Comment by jtremback** [comment]
:+1: I recognize the inherent advantages of reimplementing in React-Native, but it would be good to put some thought into this.... there may be components that are better off completely native for performance reasons.

@vincenting:

1. Maybe you can do a very small example of what you mean so that others can take on building out the concept to all the other components if it seems like a good idea.

2. It sounds to me like you should try the new ES6 classes which support inheritance. Would these solve your problem?

**Comment by vincenting** [comment]
@jtremback THX for your support. I will attach the url as soon as i complete the demo.

**Comment by jtremback** [comment]
Another very good argument for awesome compatibility with existing native libraries is that it will alienate existing native developers less. React Native will seem less like a special little land with its own ecosystem and more like a common sense tool for people who may have already been developing native apps for a long time.

**Comment by brentvatne** [comment]
@jtremback - I believe that there would not be any appreciable performance difference between implementing a floating label text input in JavaScript vs wrapping a library like `JVFloatLabeledTextField`. The same applies to `FlatUIKit`. If simple components like these could not be implemented effectively with JavaScript only in React Native we would have a problem :smile:

That's just my take on it though, and I'm willing to be convinced! I don't know what the official stance is with the team and overall just curious to hear what others think.

**Comment by yangjunsss** [comment]
So what's the best solution for this case now? I'm also in this kind of situation,We have iOS and Android Apps and both of them are using the FloatLabeledTextField Native UI component and others like TextView,etc. But now we're trying to use RN to refactor some UI components for platform-cross requirement. Any help?

**Comment by yangjunsss** [comment]
Finally, I found this https://github.com/eyaleizenberg/react-native-floating-label-text-input. One guy implement the floating labeled in RN.Thanks
