### ISSUE TITLE
Cannot load static image/png files in hybrid app (Android)

### ISSUE THREAD

**Issue by ishaanbahal** [facebook/react-native#17781]
I recently started to integrate react native in an already existing android app. I have tried multiple image loading styles as mentioned on the page https://facebook.github.io/react-native/docs/images.html

**Method 1(Hybrid Apps):** For android use `<Image source={{uri: 'asset:/app_icon.png'}} style={{width: 40, height: 40}} />`
This method doesn't load anything on the app, just a 40X40 empty area is loaded.

**Method 2:** `<Image source={require('./my-icon.png')} />`
I used the absolute path to the image `app/res/drawable-hdpi/image.png` but it didn't work either.

Got the error 
```Unable to resolve module `../app/res/drawable-hdpi/image.png` from `/Users/MyName/StudioProjects/reatProject/android/react-native/index.js`: could not resolve `/Users/MyName/StudioProjects/reatProject/android/app/res/drawable-hdpi/image.png' as a file nor as a folder```

I always provide height and width attributes in style map.

My project structure is
```
android/
  app/
    res/
    src/
    tests/
  react-native/
    index.js
    package.json
    package.lock.json
  tests/
  build.gradle
```
The project `build.gradle` file has the maven repository included as `maven { url "$rootDir/react-native/node_modules/react-native/android" }`

I am fairly new to react-native, so I may be doing something wrong here, but I have searched around on the internet to look for a solution, couldn't find one.

**package.json**

```
{
  "name": "MyReactNativeApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "react": "^16.0.0",
    "react-native": "^0.52.0"
  }
}
```

**Comment by Ashutosh21Nigam** [comment]
[info.txt](https://github.com/facebook/react-native/files/1779390/info.txt)
Sir local images is not dispay in my project.so this info.txt contains information about the project.
