### ISSUE TITLE
[ListView] In 0.7.0-rc.2, an empty header is rendered 

### ISSUE THREAD

**Issue by PhilippKrone** [facebook/react-native#1779]
Hi,

with RN 0.7.0-rc.2, a header is rendered for each ListView taking approx. 40-50pixels, even when not specified. This has not been that way in 0.6.0:

![screen shot 2015-06-29 at 08 47 04](https://cloud.githubusercontent.com/assets/11861008/8402361/7377f818-1e3b-11e5-9717-109f033af12f.png)

The corresponding code is:

````javascript
        <ListView
          dataSource={this.state.dataSourceImages}
          renderRow={this._renderRowImages}
          alwaysBounceVertical={false}
        />
````

**Comment by PhilippKrone** [comment]
When using sticky headers, it looks like this:

![screen shot 2015-06-29 at 09 42 11](https://cloud.githubusercontent.com/assets/11861008/8403268/28e5f608-1e43-11e5-887c-bb178435840a.png)

**Comment by ide** [comment]
I noticed that something to do with the top content inset changed, possibly due to one of the Navigator diffs. Can you try adding these props to your ListView?

```js
contentInset={{top: 44}}  // may need to play with this value
automaticallyAdjustContentInset={false}
```

**Comment by PhilippKrone** [comment]
Hi @ide: no change, I'm afraid.

**Comment by PhilippKrone** [comment]
@ide: Update - the following works: 

````javascript
          contentInset={{top: -24}}
````

**Comment by marcshilling** [comment]
Something definitely changed with `contentInset` and `automaticallyAdjustContentInsets` in `0.7.0`. After upgrading, I had to change all my ListViews with
```javascript
contentInset={{top:64}}
automaticallyAdjustContentInsets={false}
```
to
```javascript
contentInset={{top:0}}
automaticallyAdjustContentInsets={false}
```

This is broken because I can achieve the same effect with `automaticallyAdjustContentInsets={true}`

**Comment by PhilippKrone** [comment]
@marcshilling I'm not using NavigatorIOS but Navigator and I don't see the property ````translucent```` there.

**Comment by PhilippKrone** [comment]
Update: 

Using ````contentInset={{top: -20}}```` works as well for ListViews with sticky header if you modify line 276 of RCTScrollView.m (https://github.com/facebook/react-native/blame/522fd33d6f3c8fb339b0dde35b05df34c1233306/React/Views/RCTScrollView.m#L276) to ````if (idx > subviewCount) {```` instead of ````if (idx >= subviewCount) {````.
@nicklockwood What do you say about that? In my case, both idx and subviewCount seem to be 0 in the call of the function.

**Comment by PhilippKrone** [comment]
@nicklockwood After upgrading to 0.7.X, I had to change this again manually. Do you have any idea here or do I have a conceptional issue here?

**Comment by stan229** [comment]
@PhilippKrone I'm seeing the same issue going from 0.6.0 to 0.8.0-rc (skipped a couple of versions)
![image](https://cloud.githubusercontent.com/assets/454130/8715844/46468576-2b56-11e5-9a0f-12fb2afc3890.png)

When scrolling:
![image](https://cloud.githubusercontent.com/assets/454130/8715845/55c10940-2b56-11e5-8b2a-f7245e7493b6.png)

**Comment by stan229** [comment]
@marcshilling your solution of 
```
contentInset={{top:0}}
automaticallyAdjustContentInsets={false}
```

Worked for me, not using NavigatorIOS here.

**Comment by grabbou** [comment]
Same here. Above fixes the problem. Would be awesome to have a nice explanation of the above as currently it looks more like a glitch than feature.

**Comment by brentvatne** [comment]
@nicklockwood - this issue seems pretty stubborn, happening on master, none of the above fixes are working for me

**Comment by brentvatne** [comment]
I had to do this to avoid the blank space at the top of my ScrollView :(

```javascript
var React = require('react-native');
var { ScrollView, } = React;

var MyScrollView = React.createClass({
  render() {
    return (
      <ScrollView {...this.props} style={[{marginTop: -15}, this.props.style]}>
        {this.props.children}
      </ScrollView>
    )
  }
})

module.exports = MyScrollVIew;
```

**Comment by ide** [comment]
automaticallyAdjustContentInsets={false} should fix a lot of issues... @brentvatne can you try again?

**Comment by brentvatne** [comment]
@ide - yeah, it didn't help for me, I tried all of the suggestions above

**Comment by ide** [comment]
Hm ok. Thanks for checking.

**Comment by grabbou** [comment]
Maybe that's the case, for ListView it worked perfectly (I am having another issue with ListView not scrolling to top on navbar tap, but there was an issue about some weird race conditions causing that when multiple ScrollViews are embedded, need to head over there)

**Comment by brentvatne** [comment]
OK this looks like it is solved for ListView then, I'm going to close this issue so we can focus on ScrollView referenced above.

**Comment by yelled3** [comment]
@ide @brentvatne FYI, the `automaticallyAdjustContentInsets` flag appears in the ScrollView docs but is undocumented:

http://facebook.github.io/react-native/docs/scrollview.html#automaticallyadjustcontentinsets

**Comment by ide** [comment]
We should add a link to https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIViewController_Class/#//apple_ref/occ/instp/UIViewController/automaticallyAdjustsScrollViewInsets

**Comment by jaygarcia** [comment]
Does this help anyone in the short term? 

https://github.com/facebook/react-native/issues/2151#issuecomment-128159054
