### ISSUE TITLE
'RCTPackagerClient.h' file not found

### ISSUE THREAD

**Issue by zaiz91** [facebook/react-native#17799]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?
Yes

### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.6.0
  Yarn: 0.27.5
  npm: 5.3.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.2 => 0.52.2

### Steps to Reproduce

(Write your steps here:)

1. Upgrade react from 16.0.0-alpha.12 to 16.2.0
2. Upgrade react-native from 0.47.2 to 0.52.2
3. Reinstall all node_modules and Pods

### Expected Behavior

Xcode Build with no Errors

### Actual Behavior

Got following error:

../node_modules/react-native/React/Modules/RCTDevSettings.mm:23:9: 
'RCTPackagerClient.h' file not found

![image](https://user-images.githubusercontent.com/9715008/35616278-16c47040-0675-11e8-8ae5-b647e2f0adb6.png)

I did not find any Issues with the same bug. But I also have no clue why I get this bug. Maybe someone can help me?

**Comment by zaiz91** [comment]
Adding 'DevSupport' to podfile fixed the issue.

pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'DevSupport',

**Comment by mattop1709** [comment]
@zaiz91 i have inserted 'DevSupport', but it still won't work..

**Comment by Sadanandteggi** [comment]
I am still getting this error despite having     'DevSupport', in pod file. Can I expect any help here ?
Thanks

**Comment by Baskerville42** [comment]
+1
the same problem!
