### ISSUE TITLE
[Android] Splash screen image is shown when keyboard opens (Video included)

### ISSUE THREAD

**Issue by lugrugzo** [facebook/react-native#17800]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

  Environment:
    OS:  macOS Sierra 10.12.6
    Node:  9.3
    npm:  5.6.0
    Watchman:  4.7.0
    Xcode:  Xcode 9.2
    Android Studio:  2

  Packages: (wanted => installed)
    react-native:0.52.0
    react: 16.2.0

  Target Platform: Android

### Steps to Reproduce

(Write your steps here:)

1. Click on a text input
2. Open keyboard

### Expected Behavior

Splash screen must not seen when keyboard opens. I set it up for android using drawables:

    <style name="CustomTheme" parent="AppTheme">
        <item name="android:windowBackground">@drawable/splash_screen</item>
    </style>

### Actual Behavior

Splash screen image is disturbingly shown when keyboard opens

**Video**: https://photos.app.goo.gl/DDAncZ2KaknSz00I2

**Comment by SMJ93** [comment]
@liubko The link to your video is empty, but I think we are experiencing the same issue. When pressing a text input the splash screen flashes before the keyboard shows.

**Comment by liubko** [comment]
@SMJ93 I think you mentioned be by mistake

**Comment by SMJ93** [comment]
Ahh sorry @liubko i meant @lugrugzo.

**Comment by lugrugzo** [comment]
It turns out I had to give background color to root component according to this post: 

https://android.jlelse.eu/change-splash-screen-in-react-native-android-app-d3f99ac1ebd1

I did not test it yet.

**Comment by SMJ93** [comment]
We are already doing that 🙁  I think we need to reset the theme background to white once the app has loaded.

**Comment by SMJ93** [comment]
@lugrugzo We managed to get this working by changing the background colour to white after the splash screen loads inside the `MainActivity`. It's a bit hacky but works:

```
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        // Set the Android background to white after 8 seconds 
        // to fix the splashscreen flash when the keyboard is shown
        new CountDownTimer(8000, 1000) {

            public void onTick(long millisUntilFinished) {}

            public void onFinish() {
                getWindow().getDecorView().setBackgroundColor(Color.WHITE);
            }

        }.start();
    }
```

**Comment by tannera** [comment]
Why is this issue closed? It's still not fixed without using a hack unless someone has a clean solution?

**Comment by OliwerSmedjevik** [comment]
In our project we have a `SplashActivity.java` which initialises `MainActivity.java` after the splash screen is done. Because of this we can put the following code in our `MainActivity.java` `onCreate` function: `getWindow().getDecorView().setBackgroundColor(Color.parseColor("hex"));`

Our `SplashActivity.java`
``` java
public class SplashActivity extends AppCompatActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        Intent intent = new Intent(this, MainActivity.class); // This is the line that makes this work.
        startActivity(intent);
        finish();
    }
}
```

Our `MainActivity.java` `onCreate` function
``` java
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    getWindow().getDecorView().setBackgroundColor(Color.parseColor("#212121"));
  }
```

This resolves the issue where the splash screen is visible to the user for a second when opening the keyboard.
