### ISSUE TITLE
View borderRadius antiAliasing android

### ISSUE THREAD

**Issue by numez** [facebook/react-native#17804]
### Is this a bug report?

Yes

### Environment

```
Environment:
  OS: Windows 10
  Node: 8.1.2
  Yarn: 0.27.5
  npm: 5.3.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.0.0.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.51.0 => 0.51.0

  Target Platform: Android (7.1.1)
```

### Steps to Reproduce
`<View style={{
      width: 32,
      height: 32,
      borderRadius: 16,
      borderWidth: 2,
      borderColor: '#2196f3',
    }}/>`

### Behavior
expected like ART.Shape at left, but actual View behabior at right

![antialias](https://user-images.githubusercontent.com/6752432/35630569-0e6b9b9e-06a2-11e8-8cd9-b71b3bb27a92.png)

**Comment by gedeagas** [comment]
Hello @numez, can you elaborate more on this problem? 
What device are you using?

**Comment by numez** [comment]
I've tested on 
- Nexus 5 (Android 6.0.1)
- Samsung Glaxy S6 edge + (Android 7.0)
- AVD emulator (Android 7.1.1)

background edge is smooth with backgroundColor (AntiAliasing enabled).
But with borderWidth property border edge became jagged.

![bg_border](https://user-images.githubusercontent.com/6752432/35647448-dd0b5b12-06d2-11e8-80b7-e0fe71a06c75.png)

**Comment by sigvef** [comment]
Can reproduce on Samsung S8+, Android 7.0, RN 0.52.1

**Comment by gedeagas** [comment]
I think this issue is related to 
https://github.com/facebook/react-native/issues/17267 by @dannycochran
