### ISSUE TITLE
<Image> take up a lot memory on Android

### ISSUE THREAD

**Issue by 1c7** [facebook/react-native#17801]
### Is this a bug report?
Yes
(write your answer here)

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

No

### Environment
```
Environment:
  OS: macOS High Sierra 10.13.2
  Node: 8.9.4
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.51.0 => 0.51.0
```
![image](https://user-images.githubusercontent.com/1804755/35620591-8c7d77f4-06bc-11e8-9789-12b1b1a643a1.png)

### Steps to Reproduce
1. build a button that allow user to chose multiple image
(I am using `react-native-image-crop-picker` for Android
2. display these image in a `<FlatList>`
3. select >20 image can cause App take 400~600MB memory.
4. app could crash, depending on if the phone is high-spec or low-spec, cheap phone are more likely to crash since it has less memory

### Expected Behavior
it doesn't take **that much** memory and cause app crash.

### Actual Behavior
take about 400mb to 600mb memory. then my app crash

### Reproducible Demo
* Video demo(2 minute 38 second): https://youtu.be/zL1heevcWpk
![123](https://user-images.githubusercontent.com/1804755/35622392-ae9afc34-06c2-11e8-8e75-e24f9a3f6fec.png)

* I am writing a demo using RN 0.52, would post it here once it done
* Here is Image( I also post them in https://github.com/facebook/react-native/issues/17142)

![image](https://user-images.githubusercontent.com/1804755/35620414-1d20938c-06bc-11e8-978f-92412d9384a5.png)
369MB memory and keep growing to 400+mb
![image](https://user-images.githubusercontent.com/1804755/35620521-53b2c71c-06bc-11e8-9b02-2f7aa71a2840.png)

![image](https://user-images.githubusercontent.com/1804755/35620553-671bc808-06bc-11e8-8603-cf0da14f9cff.png)

Thanks for reading :smile:

**Comment by 1c7** [comment]
I am writing a demo for this, would post link here soon.
and also make a video with that demo.

**Comment by 1c7** [comment]
https://github.com/1c7/react-native-image-memory-problem-demo-app

**Comment by gedeagas** [comment]
This is an interesting bug, will try to reproduce the issue.

**Comment by 1c7** [comment]
@gedeagas Thanks!

**Comment by 1c7** [comment]
## demo app video is done:
https://youtu.be/Vgq-P826aqw

**Comment by aknad** [comment]
to reduce the memory usage you can try to add removeClippedSubviews={true} to your FlatList
then you should find a workaround for this old issue: #1831 / #368
we add a +1 scroll on componentWillReceiveProps

**Comment by 1c7** [comment]
@aknad Thanks! would try.

**Comment by 1c7** [comment]
I hope someone can take a look into this issue fast, 
display image in a list is quite a common scenario.

**Comment by 1c7** [comment]
btw, 
I have a old app(React Native 0.46) using ListView and loading image from Network.
it display a lot image, that list have like 300 item, but it work just fine. everything is smooth.

not sure this high memory problem is with FlatList? 
or just display local image/network image are different, 
somehow display local image is more difficult? need more work on downsampling or something?

if want try the old app I mention above, you can download here: https://www.coolapk.com/apk/com.crashcourse.china.c17

it's not on Google Play Store. 
and also this is not an advertisement for my app, 
I am just trying to provide more info to help diagnose this problem.

**Comment by 1c7** [comment]
I don't have time to retest this in 0.53.

**Comment by mattmcdonald-uk** [comment]
I can confirm this is an issue in 0.5.3

**Comment by 1c7** [comment]
@mattmcdonald-uk  so iOS doesn't have this problem, but Android still does?

**Comment by mattmcdonald-uk** [comment]
@1c7 Exactly

**Comment by mattmcdonald-uk** [comment]
@facebook-github-bot reopen

**Comment by mattmcdonald-uk** [comment]
@react-native-bot reopen

**Comment by kelset** [comment]
@mattmcdonald-uk please refer to #13413, so that we avoid redundancy - the core team is aware of this Android+Flat/SectionList+Images issue (going to write a follow up there).
