### ISSUE TITLE
The version number's location

### ISSUE THREAD

**Issue by OnlyFlyer** [facebook/react-native#17803]
### Is this a bug report?

No

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

  Environment:
    OS:  macOS Sierra 10.12.6
    Node:  8.9.0
    npm:  5.5.1
    Xcode:  Xcode 8.3.3 Build version 8E3004b
    Android Studio:  3

  Packages: (wanted => installed)
    react-native: 0.48.1 => 0.48.1
    react: 16.0.0-alpha.12 => 16.0.0-alpha.12

  Target Platform: iOS (10.3)

### Steps to Reproduce

1. don't find The version number
2. and no `package.json`
3. and no `react-native-implementation.js`

### Expected Behavior

The version number should be write to in package.json or other, must be marked

### Actual Behavior

no marked, don't find The version number

### Reproducible Demo

[this](https://github.com/facebook/react-native/blob/master/package.json)

**Comment by hramos** [comment]
Can you elaborate?

**Comment by gedeagas** [comment]
Hey @OnlyFlyer 

from your pull request here 
https://github.com/facebook/react-native/issues/17802

I concluded that you want to "research" on special version only right?
you can do that easily by switching branch on this repo.

so for example, if you want the react-native code base from version 0.30 you can just switch the branch to 0.30-stable.

**Comment by OnlyFlyer** [comment]
I find that, thank you, and my English isn't great, Sorry for the inconvenience

**Comment by gedeagas** [comment]
Don't worry you English will improve by practice, English is also not my first language.

Since my answer solve your problem, can you kindly close this issue @OnlyFlyer?
