### ISSUE TITLE
[RCTNetworking] Received data was invalid.

### ISSUE THREAD

**Issue by PhilippKrone** [facebook/react-native#1780]
Hi,

since v0.7.0-rc.2, I get the following error:

````javascript 
  [error][tid:com.facebook.React.RCTNetworkingQueue][RCTNetworking.m:384] Received data was invalid.
`````

When trying to fetch() something as follows:
````javascript
    fetch('https://ssl.google-analytics.com/collect', {
      method: 'post',
      body: hit.toQueryString()
    });
`````

This code was working in prior versions of RN. The return from google seems to be an empty gif (1x1px).

P.S. this is from react-native-google-analytics.

**Comment by PhilippKrone** [comment]
@brentvatne Do you have any idea here? I was now debugging for some hours but had no luck until now.

**Comment by PhilippKrone** [comment]
@nicklockwood I just figured it was your commit in RCTNetworking.m that introduced this check (https://github.com/facebook/react-native/commit/f88bc3eb73107d0df25c660f159eac8197474d7e) - do you have any idea as to why this might happen?

**Comment by nicklockwood** [comment]
We currently only support XHR requests that return text responses. Support for images is planned, but not currently implemented. It probably worked before because we didn't report the error and just returned null as the response.

**Comment by PhilippKrone** [comment]
@nicklockwood Thanks for the answer. Would it make sense to add it to the breaking changes section then? Moreover, wouldnt it be better to log the error but not create a redbox? Sometimes, you might just want to open an URL without parsing the result (as it is the case for google analytics sometimes).
@Iwansbrough This might be of interest for you in terms of react-native-google-analytics

**Comment by nicklockwood** [comment]
Yes, on both counts.

**Comment by PhilippKrone** [comment]
@brentvatne I've seen that you have been active concerning "breaking changes" recently IIRC. Are you able to add stuff there? Concerning the other point of changing:
````javascript
 if (!responseText && data.length) {
    RCTLogError(@"Received data was invalid.");
    return;
   }
````
in RCTNetworking.m to something that does not result in a Redbox: could you gimme some guidance as to how this should be done in RN? I would like to add a PR then (have never done that before, so a little more guidance is highly appreciated :))

**Comment by nicklockwood** [comment]
Hi Philipp, I'm just investigating what would be involved. If it was a normal method call you'd just return an error callback, but in this case it's slightly more complicated as you'd need to cancel the request to prevent multiple errors being sent.

**Comment by PhilippKrone** [comment]
@nicklockwood OK, I've just created a pull request to work with, feel free to give feedback in there if thats better. 
https://github.com/facebook/react-native/pull/1860

**Comment by brentvatne** [comment]
Thanks for the heads up @PhilippKrone, I updated the breaking changes section of the release notes: https://github.com/facebook/react-native/releases/tag/v0.7.0-rc

**Comment by lwansbrough** [comment]
Thanks for looking into this guys, as @PhilippKrone said, this is affecting my GA module.

**Comment by lwansbrough** [comment]
Can we not just check the `Content-Type` of the response for any of `text`, `json`, `xml`, `html`? If one of those is contained in it, assume it's text, if it isn't then return the response as binary?

**Comment by negativetwelve** [comment]
I just updated to 0.7.0-rc.2 and started getting some response errors on the app that I'm creating. I submitted a pull request at #1917 that fixes a bug in the way response headers are looked up (values were supposed to be lowercased but ended up not being lowercased which caused looking up things like `Content-Type` to return null).

I'm not sure if this is going to fix your problem but since you said it was working prior to 0.7.0-rc.2 and my change fixes a bug introduced in this commit (https://github.com/facebook/react-native/commit/e00b9ac8f38fb1b7968c4bc5253a47656362fc5b) that was introduced in 0.7.0-rc.2, I figured you could try it out!

**Comment by nicklockwood** [comment]
FYI, I'ver merged the RCTWarn solution internally for now. It's not thr right fix, but it will do as a workaround for the time being.

@negativetwelve the lowercase content-type bug is a separate issue, which has also now been fixed. Should be in the next update.

**Comment by burgalon** [comment]
I'm also experiencing "Received data was invalid." on a response with Content-Type "text/html" and response.text() yields empty string ""
Any ideas?

**Comment by nicklockwood** [comment]
Might be malformed utf8 - can you paste in the url you're trying to download?

**Comment by burgalon** [comment]
http://www.yad2.co.il/Nadlan/ViewImage.php?CatID=2&SubCatID=1&RecordID=57624352f8c449d90827b9dd4b576ac9ee3

**Comment by gauravmc** [comment]
I've been seeing this same issue with `text/html` content type. I'm querying amazon.com to download some books data and while it works for most cases, I consistently get `Received data was invalid.` for certain books. It works perfectly if I try those requests in the browser. It's not clear why it would error out for some requests when all the requests are almost identical.

**Comment by gauravmc** [comment]
@nicklockwood I dug more into this, and, the reason in my case is that `data` coming in [here](https://github.com/facebook/react-native/blob/ac9471f2cd8b97c546d5b4aca8da2c8e10b45379/Libraries/Network/RCTNetworking.m#L274) was actually ASCII instead of UTF-8. It's not uncommon to have wrong content-type, so relying on that alone isn't the best for fetch api IMO. Should let client handle whatever response data comes in.

**Comment by nicklockwood** [comment]
Ascii is a subset of UTF8, so that shouldn't be a problem. I suspect the issue here is that the text includes some characters that mean is doesn't conform to any valid encoding, and Apple's string parsing is super-strict about bad encoding.

I'll see if I can find a way to make it more robust/tolerant.

**Comment by nicklockwood** [comment]
@guaravmc can you include some examples of pages that it won't download properly so I can test?

**Comment by gauravmc** [comment]
@nicklockwood Since the pages I was requesting are behind my login session, here's a super tiny server you can test this against: https://github.com/gauravmc/encoding_test_server

**Comment by nicklockwood** [comment]
I've added a fix, but it relies on an iOS 8-only API I'm afraid: https://github.com/facebook/react-native/commit/0044b3c2c34127de65208f2f366b1f41ef043f3a

Feel free to keep this issue open if iOS 7 support is critical for you.

**Comment by gauravmc** [comment]
@nicklockwood awesome, thanks! I'd imagine iOS 7 support being important for people; what do you think?

**Comment by nicklockwood** [comment]
It's not that it isn't important, but it's going to be very complex to fix if Apple don't provide an API for it, and we'll probably be dropping iOS 7 support within a year or so now that iOS 9 is out (assuming it's adopted quickly).

**Comment by chirag04** [comment]
Closing this since it's already fixed for ios 8+. Feel free to submit a PR with ios 7 support.

**Comment by lwansbrough** [comment]
@chirag04 can you reopen this? It appears people are still having an issue with this. https://github.com/lwansbrough/react-native-google-analytics/issues/19#issuecomment-162602098

**Comment by danleveille** [comment]
Still having this issue on iOS 9.1 from a Google Analytics request as @lwansbrough mentioned above.

**Comment by anderson916** [comment]
+1

**Comment by PaulMest** [comment]
My team is having an issue with running PouchDB in React Native and retrieving images from CouchDB.

Error message:
`Received data was not a string, or was not a recognised encoding`

react-native 0.26
pouchdb 5.3.2
iOS 9.3.2

**Comment by nicklockwood** [comment]
@PaulMest if you want to retrieve images via a network request, you'll have to do this via the `Image.prefetch()` API, or do it with native code. Retrieving image data on the JS side is not supported in RN (it would be a bad idea since you'd have to base64-encode the data to send it to the native side for display, so it's better just to keep the image on the native side to begin with).

**Comment by lwansbrough** [comment]
@nicklockwood The reason why this is affecting me is actually out of my control. I'm sending Google Analytics data to Google's collect URL, and they send back a 1x1 image. Is there anyway we can "dangerously allow" binary content?

**Comment by PaulMest** [comment]
@nicklockwood This is helpful guidance. I'll chat with my team about it. Thanks.

For more context: we're building an offline-first app that can do bi-directional syncing when the device comes online. We're trying to leverage PouchDB/CouchDB for this. The performance is acceptable now with hundreds of images and we have resorted to base64 encoding images and syncing the strings. Not a very elegant solution by any means, but it's functional. If we had more time, we could probably figure out a way to build our own offline-to-online bi-directional sync provider for images while keeping them native. But I agree with @lwansbrough that there should be a way to "dangerously allow" binary content.

**Comment by nicklockwood** [comment]
@lwansbrough I'll look into it.

**Comment by lwansbrough** [comment]
@nicklockwood I suppose I could use the aforementioned image pre fetching API? All my data is being passed as query parameters anyway.

**Comment by nicklockwood** [comment]
@lwansbrough note that unless you actually need to prefetch the image, you can simply store the URL and pass it directly to `<Image source={{uri: ...}}/>`, then RN will download and cache the image on demand.

**Comment by lwansbrough** [comment]
@nicklockwood Unfortunately the current API doesn't make use of the rendering context (nor do I think it should, particularly). In fact it doesn't require anything from React Native. I still think optionally delegating control of the response binary to the user might be the best solution in my case.

**Comment by lwansbrough** [comment]
@nicklockwood How long do images stay in the prefetch cache for? Would it be a bad choice to use that for downloading 1px images from GA?

**Comment by nicklockwood** [comment]
@nicklockwood on iOS it's an LRU cache with a fixed size limit (200MB on disk, 5MB in memory). Images will stay in the cache indefinitely until they're pushed out by a new image.

**Comment by lwansbrough** [comment]
Thanks for the info!

**Comment by peacechen** [comment]
2018 and the yellow box warning continues to pop up when using Google Analytics.  It's "just" a warning, but when multiple warnings consistently stack up, developers start to ignore all warnings and it lessens the value of warnings in general.

Image.prefetch isn't an option for us because our app can't waste cache space on these empty pixels.  Would like to see an option in the config object (second param to `fetch`) such as `allowBinaryResponse`.  For example:

```
fetch('https://mywebsite.com/endpoint?v=1&t=abcd', {
  method: 'GET',
  allowBinaryResponse: true,
});
```
