### ISSUE TITLE
onSubmitEditing not working on TextInput when Multiline={true} in React Native(android)

### ISSUE THREAD

**Issue by nikasvan** [facebook/react-native#17825]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: macOS High Sierra 10.13.2
  Node: 7.10.1
  Yarn: Not Found
  npm: 4.2.0
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: https://github.com/expo/react-native/archive/sdk-21.0.2.tar.gz => 0.48.4

### Steps to Reproduce

On iOS there is no problem, but on Android when I have multiline TextInput, onSubmitEditing doesn't seem to work. User types some symbols in input and when pressing return key I am expecting to stop typing option, save already typed symbols, but instead new line appears below and user continues to type.

```
<TextInput
  multiline
  onSubmitEditing={text => this.saveCurrentValues()}
/>
```

### Expected Behavior

When 'return' key is pressed TextInput shouldn't break and on new line. Like it is on iOS, it should listen to onSubmitEditing()

### Actual Behavior

When 'return' key is pressed there shouldn't be a new line.

**Comment by rajivshah3** [comment]
Try this: https://facebook.github.io/react-native/docs/textinput.html#bluronsubmit
The `blurOnSubmit` prop works differently on multiline fields

**Comment by SuhairZain** [comment]
@rajivshah3 I believe that @nikasvan expects the exact same thing as given in the doc, that it will not insert a new line and instead call `onSubmitEditing`. But it doesn't happen, which is why he opened this issue. I'm also having this issue.

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (160/150 (106%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o10.sgmail.github.com ([167.89.101.201]:36575)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-a7b0-hello=salmanwaheed.info@sgmail.github.com>)
	id 1epQUu-003IzE-0t
	for hello@salmanwaheed.info; Fri, 23 Feb 2018 20:27:40 -0700
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=jmpzFN0deMfrbYD6uBqEIcl37eo=; b=MBNxJoMGKqDsrUEm
	jP+qxjip8XYmhfGozesrFFLbA4xuUtSHZz2nfoo0RghGRpZHHMrB2oII+Sc3zVkX
	//55T6vuH53QwBZRpsGkJ3IMmKSDnLph98LUo9eK7ULjntBiZuStWhAnxKezCZ40
	RTAAWTcxUhpRQseAxUmWnqyOtK0=
Received: by filter0315p1iad2.sendgrid.net with SMTP id filter0315p1iad2-28983-5A90DBA1-8
        2018-02-24 03:27:29.241462262 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0002p1iad2.sendgrid.net (SG) with ESMTP id EoxBTxkuR3m2scx8dRCawQ
	for <hello@salmanwaheed.info>; Sat, 24 Feb 2018 03:27:29.223 +0000 (UTC)
Date: Sat, 24 Feb 2018 03:27:29 +0000 (UTC)

**Comment by DeforeChen** [comment]
If the blurOnSubmit is set to true, although the onSubmitEditing would be called instead of inserting a new line, the keyboard would also dismiss at the same time. I do not want the keyboard be hidden when submit function fired, any way to solve this ?

**Comment by GitHubTracey** [comment]
I am experiencing the exact same as @DeforeChen. I have some inputs where I need to allow the user to be able to type multiple lines (with word wrap), but not allow them to actually enter a new line. It is especially weird behaviour when you are trying just go to the next field, and instead, it adds a new line, and then goes to the next field... so you can get multiple new lines in fields where you don't expect any.. I can clear after, but that's not a smooth experience for the user.
