### ISSUE TITLE
[ScrollView] Incorrect event coalescing causes onChangeVisibleRows to fail

### ISSUE THREAD

**Issue by paramaggarwal** [facebook/react-native#1782]
Performance sensitive issue - shows on iPhone 4s.

`ListView` has a method called `onChangeVisibleRows` that is called whenever the rows visible on screen change. This method is critical to be able to implement deletion/creation of views and hence be conservative in memory usage. I have an infinite scrolling view which uses this method to only render the full rows for what is visible on screen and put placeholders for everything else.

In the `RCTEventDispatcher`, we [coalesce events](https://github.com/facebook/react-native/blob/522fd33d6f3c8fb339b0dde35b05df34c1233306/React/Base/RCTEventDispatcher.m#L135-L152) that are meant to be sent across the bridge. They are [dequeued](https://github.com/facebook/react-native/blob/522fd33d6f3c8fb339b0dde35b05df34c1233306/React/Base/RCTEventDispatcher.m#L180-L188) on each and every `RCTFrameUpdate`.

But when we [coalesce the events](https://github.com/facebook/react-native/blob/522fd33d6f3c8fb339b0dde35b05df34c1233306/React/Views/RCTScrollView.m#L117-L120) for `RCTScrollView`, we are only picking the latest event. This means that the `updatedChildFrames` [generated here](https://github.com/facebook/react-native/blob/522fd33d6f3c8fb339b0dde35b05df34c1233306/React/Views/RCTScrollView.m#L533-L552) are lost and the `ListView` in JS, does not know about the new frames of the rows - and hence cannot correctly calculate the `onChangeVisibleRows` changes.

To test my theory, I turned off coalescing in code and JS receives all the events. Hence, the coalescing method needs to take into account the `childUpdatedFrames` object from previous events [here](https://github.com/facebook/react-native/blob/522fd33d6f3c8fb339b0dde35b05df34c1233306/React/Views/RCTScrollView.m#L117-L120):

```
- (id<RCTEvent>)coalesceWithEvent:(id<RCTEvent>)newEvent
{
  return newEvent;
}
```
Currently, it is blindly picking up the latest event. It should instead do a merge of the events taking care of `childUpdatedFrames`. I'll raise a PR with the change soon, till then looking for thoughts and comments.

**Comment by VonD** [comment]
@paramaggarwal how does the event fail ?

Possibly related issue here : the `visibleRows` param passed to the `onChangeVisibleRows` event has sometimes no rows : `{"s1": {}}`, even though several rows are visible on screen.

I haven't been able to find a strict test case for this, but it seems to happen after rendering some rows, when scrolling rapidly.

**Comment by paramaggarwal** [comment]
@VonD The problem you are seeing where `onChangeVisibleRows` gave you `{"s1": {}}` sometimes is exactly what I was facing also. And spending a few days on intense debugging brought me to the solution in this PR. Where multiple events were clubbed into one - and the critical `childUpdatedFrames` data was sometimes lost. With this fix, `onChangeVisibleRows` is much more reliable. 

If you are still facing the problem - maybe there are some other places also where this data is lost. Try debugging it! :)
