### ISSUE TITLE
[iOS] [Text] text component doesn't show it's text to value attribute

### ISSUE THREAD

**Issue by pgajeshwar-coupa** [facebook/react-native#17836]
### Is this a bug report?
Yes, The value attribute is 'nil' while checking text component field with accessibility inspector.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?
Yes.

### Environment
Environment:
  OS: macOS High Sierra 10.13.2
  Node: 4.8.0
  Yarn: Not Found
  npm: 5.5.1
  Watchman: 4.7.0
  Xcode: Xcode 9.1 Build version 9B55
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.0 => 0.52.0

### Steps to Reproduce
1. Create one text component field and check in iOS app client
2. Open Accessibility Inspector from xcode developer tools
3. Highlight text component in Accessibility inspector
4. Verify Value attribute in Accessibility inspector window

### Expected Behavior
Accessibility inspector should show actual text assigned to that Text component field.

### Actual Behavior
 Accessibility inspector is showing <nil> value to all Text component fields.

This is really required while doing automated testing to validate correct text is being shown or not in that specific text field.

![nil_value_of_text_component](https://user-images.githubusercontent.com/17845074/35734699-0918f05e-0848-11e8-8f60-eaa883c8b40e.png)

### Reproducible Demo
Can't connect accessibility inspector in provided site to show value attribute.

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (178/150 (118%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o7.sgmail.github.com ([167.89.101.198]:48849)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-a7b0-hello=salmanwaheed.info@sgmail.github.com>)
	id 1epQVm-003Jce-Vg
	for hello@salmanwaheed.info; Fri, 23 Feb 2018 20:28:36 -0700
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=mcOBcUbhRvdoMEhiOsCL+t0Bhyc=; b=n+hwtMFtpQPE2l+E
	V06OUZucdV2a17lAE3nptlwvCe4vQukr/QyAY1y5kKfr41JKbg3MUV9NVWI0DYAo
	F5OnJHr85Dr+xt3qT1cecapoGG5igdYtfU2LDkRPjSlqJJxikbLtkJ0bvK4GEVLP
	VisDqizTJBucI+okiMwh4henYYo=
Received: by filter0352p1iad2.sendgrid.net with SMTP id filter0352p1iad2-31272-5A90DBD6-D
        2018-02-24 03:28:22.468320049 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0015p1iad2.sendgrid.net (SG) with ESMTP id LtoOZdYAQGKcsLbICb3ymw
	for <hello@salmanwaheed.info>; Sat, 24 Feb 2018 03:28:22.458 +0000 (UTC)
Date: Sat, 24 Feb 2018 03:28:22 +0000 (UTC)
