### ISSUE TITLE
App become very slow/Laggy and crash when I set borderRadius with big value.

### ISSUE THREAD

**Issue by sandropoluan** [facebook/react-native#17833]
### Is this a bug report?

YES

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

YES

### Environment

  Environment:
    Android All version
    Node:  8.4.0
    npm:  5.4.0

   react-native:  >=  0.51.0
   react: 16.0.0

  Target Platform: Android

### Steps to Reproduce

1. Create 20 View with border radius = 1000

### Expected Behavior

App should run smooth without any issue.

### Actual Behavior

App become very slow, unresponsive, and crash.
I was with RN 0.48 and there is no issue.
This issue appear when I used RN >= 0.51

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (179/150 (119%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:43909 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1epQVp-003JdR-3P
	for hello@salmanwaheed.info; Fri, 23 Feb 2018 20:28:37 -0700
Date: Fri, 23 Feb 2018 19:21:54 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1519442901;
	bh=OIo75U42rYG8UaZEj+UWWBl8RvP2YZGC09KT+dwB7fI=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=o+/g+wRU99Bi4OjOwzzU+Il0YM4R/GSy4ELAclESA0rUKZ1RazDv/NjGpJFLWVD8w
	 oi31vLJBeam3IKbTAVOWxRPRrh99V6JMuZ7+kxAPiWqtdWgQmPD42wDMj3ouhyZBP4
	 QCk2iAnzgpMr5jKW6B+OZe+aT2X7KZZZzqClL/QI=

**Comment by sandropoluan** [comment]
@react-native-bot why is this closed? I'm use v0.53.0 and and still having this problem.

**Comment by huynhquangtoan** [comment]
+1 for me
react-native : 0.57.7
