### ISSUE TITLE
The development server returned response error code:404

### ISSUE THREAD

**Issue by vikaschauhan** [facebook/react-native#17838]
![capture](https://user-images.githubusercontent.com/3263646/35735845-15b07b3a-084c-11e8-856b-270a76caf4b7.PNG)

Created new project with **react-native init**.
When i run the command inside my project:
**react-native run-android**

The above error throws(above image inserted). I tried to emulate with Genymotion Emulator as well and there also, faced the
same issue.
Please help.

**Comment by chelseaisgood** [comment]
Check and see if your Metro Bundler started successfully. @vikaschauhan You should have seen a new command window pops up after you running "react-native run-ios/android".
