### ISSUE TITLE
The development server returned response error code:404

### ISSUE THREAD

**Issue by vikaschauhan** [facebook/react-native#17840]
### Is this a bug report?

(Yes)

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Yes)

### Steps to Reproduce

(Write your steps here:)

1. Run the command react-native run-android in the terminal.
2. Shows the result BUILD SUCCESSFUL.
3. Last line before exist was: Starting: Intent { cmp=com.projectfirst/.MainActivity }.

### Expected Behavior

(Should have seen the result for the project rather than this error.)

### Actual Behavior

(There was no code change but emulation didn't happen.)

-->
![capture](https://user-images.githubusercontent.com/3263646/35737562-faa621d6-0851-11e8-8163-aef2d10da994.PNG)

**Comment by SJOwl** [comment]
I had same error. In my case I did:
run in cmd :
`react-native start`
if it's complain that can't listen on some port (in my case it was 8081), kill all processes on this port:
on linux: 
`fuser -k 8081/tcp`
then run 
`react-native start`

**Comment by mangal511** [comment]
![image](https://user-images.githubusercontent.com/17899136/39464873-9589b066-4d3d-11e8-9945-65b6b3484580.png)
Run the command react-native run-android in the terminal.
Shows the result BUILD SUCCESSFUL.
Last line before exist was: Starting: Intent { cmp=com.projectfirst/.MainActivity }.
Please error solve

**Comment by asnad** [comment]
Did you solve this?

**Comment by Mislavoo7** [comment]
I'm see the same red screen. Is some new update the cause of this error? In the terminal i get

`::ffff:127.0.0.1 - - [15/May/2018:12:50:43 +0000] "GET /index.android.delta?platform=android&dev=true&minify=false HTTP/1.1" 404 79 "-" "okhttp/3.6.0"`

**Comment by sujitpk-perennial** [comment]
@Mislavoo7 I faced this issue in Android only. I created index.bundle file using following command and run the app again solved my problem.

`curl "http://localhost:8081/index.android.bundle?platform=android" -o "android/app/src/main/assets/index.android.bundle"`

**Comment by CheeOnn9322** [comment]
Hi @sujitpk-perennial, I followed your way but it does not solve the problem. Is there anyone know what's the problem? 

version running with my application
react-native: 0.44.3
react: 16.0.0-alpha.6

Thanks

**Comment by Mislavoo7** [comment]
@sujitpk-perennial thank you four your response. I also followed your way but it does not solve the problem. I also tried to update react-native and than android-studio asked for some updates but the red screen remains. There is no error in the logs...

**Comment by augisticz** [comment]
I have same problem

**Comment by maximten** [comment]
Have the same problem too

**Comment by sujitpk-perennial** [comment]
Can you try by stopping Debug JS remote?

**Comment by sujitpk-perennial** [comment]
It looks like the problem is faced by lot of now from yesterday onwards. I can see this error says server is trying to connect to 192.168.2.2 Not sure why server is trying to connect to this address instead of localhost.

**Comment by maximten** [comment]
I found a solution, that helped me
[https://stackoverflow.com/questions/50344830/react-native-cannot-read-index-android-delta](https://stackoverflow.com/questions/50344830/react-native-cannot-read-index-android-delta)

**Comment by Victoriayangx** [comment]
we met this issue too.  Pls help!! thanks.
<img width="294" alt="2018-05-16 02 38 22 pm" src="https://user-images.githubusercontent.com/16059820/40100549-dbfbd6de-5916-11e8-96bc-c73ee5149401.png">
<img width="579" alt="2018-05-16 02 38 38 pm" src="https://user-images.githubusercontent.com/16059820/40100552-e007e7b8-5916-11e8-84da-837f6ed1b959.png">

**Comment by liplylie** [comment]
This worked for me: https://stackoverflow.com/questions/44446523/unable-to-load-script-from-assets-index-android-bundle-on-windows

**Comment by Victoriayangx** [comment]
@maximten ,thanks, it worked for me.
https://stackoverflow.com/questions/50344830/react-native-cannot-read-index-android-delta

**Comment by huangkaiw3n** [comment]
Seems like something changed on FB's side.

I changed the following to make my project work again.
This forces the correct version:
1. build.gradle (note that resolutionStrategy is only available from a certain gradle version onwards. I'm on 3.1.0)
```
allprojects {
    ...
    repositories {
        configurations.all {
            resolutionStrategy.eachDependency { DependencyResolveDetails details ->
                def requested = details.requested
                if (requested.group == 'com.facebook.react' && requested.name == 'react-native') {
                  details.useVersion '0.44.3'
                }
            }
        }
    }
}
```

2. app/build.gradle
Change this 
```
compile "com.facebook.react:react-native:+"
```
to
```
compile ("com.facebook.react:react-native:0.44.3") {
    force = true;
}
```

**Comment by Mislavoo7** [comment]
Thank you all for the help! I added 
`compile ("com.facebook.react:react-native:0.55.4") { force = true }` to app app/build.gradle and I had to update react-native: `yarn add react-native`

Now I get a new error from RNFS that is probably not properly linked but that's another story :)

**Comment by asnad** [comment]
Please have a look I was able to fix with following solution at stackoverflow [here](https://stackoverflow.com/questions/50344830/react-native-cannot-read-index-android-delta)
