### ISSUE TITLE
fetch does not throw error with a malformed URL

### ISSUE THREAD

**Issue by suparng-medallia** [facebook/react-native#17843]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.)

### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.9.1
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.52.0 => 0.52.0

### Steps to Reproduce

(Write your steps here:)

1. Make a fetch request to a malformed url like https://http:.malformedurl.com
2. The error is not propagated to the promise resolvers
3.

### Expected Behavior

The error  should be thrown in the Javascript so that it can be caught in the catch block

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

```
test = async () => {
    try {
      await fetch('https://http:.malformedurl.com/.jsapi/info')
      console.log('Fetch successful')
    }
    catch(error) {
      console.error(error); // never goes here
    }
    
  }
  componentDidMount() {
    this.test();
  }
  
```
![screenshot_1517611982](https://user-images.githubusercontent.com/17259683/35758416-c99d1d52-0828-11e8-962b-bb28ad7fbaa4.png)

**Comment by gedeagas** [comment]
Hello, @suparng-medallia thank you for your bug report.

after reviewing your code I must conclude this is not a bug and the code run as it should have.

` catch(error) {
      console.error(error); // never goes here
    }`

This part of the code is executed hence the red screen. if you want the error to be "thrown in the Javascript" ( log the error on debugger ) you can do that easily by changing the `console.error()` to `console.log()`.

If you want to read more about debugging in react-native I suggest that you read the docs here 
https://facebook.github.io/react-native/docs/debugging.html#in-app-errors-and-warnings
