### ISSUE TITLE
Path Traversal  Your app(s) are using a content provider with an unsafe implementation of openFile.

### ISSUE THREAD

**Issue by rakeskun** [facebook/react-native#17844]
### Is this a bug report?
Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.)

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by charpeni** [comment]
Duplicate of #17752.
