### ISSUE TITLE
When the web page in `WebView` uses "history.pushState ()" to change URL, "onNavigationStateChange" does not execute 

### ISSUE THREAD

**Issue by iwangx** [facebook/react-native#17856]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

    OS:  macOS Sierra 10.12.6
    Node:  8.4.0
    Yarn:  1.27.5
    npm:  5.4.0
    Watchman:  4.7.0
    Xcode:  Xcode 8.3.3 Build version 8E3004b

    Packages: (wanted => installed)
    react-native: 0.51.0
    react: 16.0.0

### Steps to Reproduce

1.`WebView` opens `http://antd-admin.zuiidea.com/login` and logs in
2.Click to jump to other pages

When the web page in `WebView` uses `history.pushState ()` to change URL, `onNavigationStateChange` does not execute 

### Expected Behavior

`onNavigationStateChange` executes after each URL change

### Actual Behavior

`onNavigationStateChange` does not execute every time URL changes

### Reproducible Demo

```
<WebView
  onNavigationStateChange={this.onNavigationStateChange.bind(this)}
  source={{uri:"http://antd-admin.zuiidea.com/login"}}
  allowsInlineMediaPlayback={true}
  domStorageEnabled={true}
  javaScriptEnabled={true}
  scalesPageToFit={false}
/>
```

**Comment by yejing2017** [comment]
+1

**Comment by leoyb** [comment]
@iwangx I have the same problem, have you solved it?
