### ISSUE TITLE
With socket.io: setting a timer for a long period of time warning

### ISSUE THREAD

**Issue by aprilmintacpineda** [facebook/react-native#17859]
<img width="308" alt="screen shot 2018-02-05 at 6 04 11 pm" src="https://user-images.githubusercontent.com/21032419/35799265-18cb8d90-0aa0-11e8-97e0-c54a337ba07a.png">
<img width="310" alt="screen shot 2018-02-05 at 6 04 38 pm" src="https://user-images.githubusercontent.com/21032419/35799270-1c8287fe-0aa0-11e8-9a3c-f93164676d71.png">
<img width="309" alt="screen shot 2018-02-05 at 6 04 50 pm" src="https://user-images.githubusercontent.com/21032419/35799279-1fb90dbc-0aa0-11e8-80f4-e2dc4c7aea26.png">

**Comment by aprilmintacpineda** [comment]
the "encountered X times" seem to increase as time passes by, as I am writing this comment it's on 18.

**Comment by adirzoari** [comment]
Did you find any solution for it?

**Comment by aprilmintacpineda** [comment]
@adirzoari It's just a warning so you can ignore it as a lot of devs do. As for me, even a warning concerns me.

```
const io = socketIO(server, {
  pingTimeout: 30000,
  pingInterval: 30000
});
```

I think the default was `85000`, which react-native doesn't like. So the only solution is to change it to a lower value.
