### ISSUE TITLE
Issue with bundler while using Platform.select in release build

### ISSUE THREAD

**Issue by varungupta85** [facebook/react-native#17852]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.2.1
  Yarn: 1.1.0
  npm: 5.3.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: ^16.2.0 => 16.2.0
  react-native: ^0.52.2 => 0.52.2

  Target Platform: iOS and Android

### Steps to Reproduce

I have a react-native app in production for the last few months. I updated to latest `react-native 0.52.2` and started to see some strange problems with `Platform.select` behaviour **only in the release app**. Values set using `Platform.select` were not set in certain cases. I was able to confirm it by updating the release app to print logs. I want to emphasise again that it happens only in release app and NOT in development app. Below are some code excerpts that work and don't work.

```javascript
// I have a reusable module to show a context menu.
// It exposes an API `ContextMenu.show(options)` that can be used to show the context menu.
// The items in the context menu could be different on iOS vs Android. 
// Below piece of code used to work before I updated to 0.52.2 but it doesn't work now.

let ctxOptions = {
  items: Platform.select({
    'ios': showDelete ? [I18n.t('takePhoto'), I18n.t('chooseFromLibrary'), I18n.t('delete'), I18n.t('cancel')] :
      [I18n.t('takePhoto'), I18n.t('chooseFromLibrary'), I18n.t('cancel')],
    'android': showDelete ? [I18n.t('takePhoto'), I18n.t('chooseFromLibrary'), I18n.t('delete')] :
      [I18n.t('takePhoto'), I18n.t('chooseFromLibrary')]
  }),
  info: Platform.select({
    'ios': {
      destructiveButtonIndex: showDelete ? 2 : undefined,
      cancelButtonIndex: showDelete ? 3 : 2
    },
    'android': {}
  })
}

// Both info and items are undefined on both iOS and Android
ContextMenu.show(ctxOptions)

// I changed the above code to not use Platform.select but just pick the right object based on Platform.OS value without changing anything else and this works

let ctxOptions = {
  items: ({
    'ios': showDelete ? [I18n.t('takePhoto'), I18n.t('chooseFromLibrary'), I18n.t('delete'), I18n.t('cancel')] :
      [I18n.t('takePhoto'), I18n.t('chooseFromLibrary'), I18n.t('cancel')],
    'android': showDelete ? [I18n.t('takePhoto'), I18n.t('chooseFromLibrary'), I18n.t('delete')] :
      [I18n.t('takePhoto'), I18n.t('chooseFromLibrary')]
  })[Platform.OS],
  info: ({
    'ios': {
      destructiveButtonIndex: showDelete ? 2 : undefined,
      cancelButtonIndex: showDelete ? 3 : 2
    },
    'android': {}
  })[Platform.OS]
}

// Both info and items are set according to the OS
ContextMenu.show(ctxOptions)

// I also changed the above statements to ternary statements using Platform.OS and that works as well.
```

I am using `Platform.select` at other places such as styles such as below where it works as expected.

```javascript
const styles = StyleSheet.create({
  container: Platform.select({
    android: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.4)',
    },
    ios: {
      justifyContent: 'center',
      alignItems: 'center',
    },
  })
})
```

This leads me to believe that this may be an issue with the bundler used in the release app causing the values to be not set.

### Expected Behavior

The values set using `Platform.select` should be set according to the OS

### Actual Behavior

The values were not set as described above.

### Reproducible Demo

I have created a new project which can be downloaded from [here](https://github.com/varungupta85/ReactNativeBundlerIssue). In the `App.js` file, in `componentDidMount`, there are two calls: one with `Platform.select` and the other with `Platform.OS` as described above. The app will abort when `Platform.select` section is not commented out and wouldn't abort when `Platform.OS` section is not commented out **only in the release builds**.

**Comment by brunolemos** [comment]
Hi @varungupta85, thanks for reporting!
I was able to reproduce the bug.

Here is a smaller version for reproduction:
```js
const select1 = Platform.select({ ios: 'ios', default: 'default' })
const select2 = Platform.select({ 'ios': 'ios', default: 'default' })
const select3 = Platform.select({ 'ios': 'ios', 'default': 'default' })

alert(`OS: ${Platform.OS}, 1: ${select1}, 2: ${select2}, 3: ${select3}`)
// expected:          OS: ios, 1: ios, 2: ios, 3: ios
// result on release: OS: ios, 1: ios, 2: default, 3: undefined
```

As you can see, this bug is happening when you write the object keys using quotes.

As a workaround , please remove the quotes for now, while this issue is not fixed.

Thank you!

**Comment by brunolemos** [comment]
After more investigation, it works fine on 0.51.0 and was introduced on 0.52.0.
Not sure which commit, but my guess would be this metro bundler version bump: https://github.com/facebook/react-native/commit/0bbd9f042a8ad7c7be094bd7636ca767c6f7b231

cc @rafeca

**Comment by varungupta85** [comment]
@brunolemos Thanks for investigating the issue further and wow, I didn't realise that the quotes in the key names could have caused this. I guess, I shouldn't take anything for granted 😃  Thanks for the workaround. I will check other places in my code as well where I may be using quotes in the key names.

**Comment by varungupta85** [comment]
I am a little confused by where does this problem affect and where it doesn't. For e.g., I have an object defined as below:

```javascript
    CascadingAlarmIntervals: {
      '5mins': {
        label: I18n.t('minutes', {count: 5}),
        value: 300000
      },
      '10mins': {
        label: I18n.t('minutes', {count: 10}),
        value: 600000
      },
      '15mins': {
        label: I18n.t('minutes', {count: 15}),
        value: 900000
      },
      '30mins': {
        label: I18n.t('minutes', {count: 30}),
        value: 1800000
      },
      '1hr': {
        label: I18n.t('hours', {count: 1}),
        value: 3600000
      },
      '2hr': {
        label: I18n.t('hours', {count: 2}),
        value: 7200000
      },
      '3hr': {
        label: I18n.t('hours', {count: 3}),
        value: 10800000
      }
    }
```

This works fine even though the key names have strings.

**Comment by rafeca** [comment]
This could have been caused by one of the changes in metro. At this point it's hard for me to bisect the actual metro change since lots of things changed between the metro version in RN 0.51 and 0.52 (we almost rebuilt the bundling logic).

If anybody is up to fix it, the logic that needs to be updated is the one in [inline-platform.js](https://github.com/facebook/metro/blob/master/packages/metro/src/JSTransformer/worker/inline-platform.js), which transform the `Platform.select()` calls in prod to remove the non-used platforms (so if you have `Platform.select({ios: require('implementation-ios.js'), android: require('implementation-android.js')});`, when you build the iOS app the android code won't be included in the bundle, and viceversa).

@varungupta85 : the last code you posted should work fine (the issue only affects `Platform.select()` calls).
