### ISSUE TITLE
Dead link in Documentation 

### ISSUE THREAD

**Issue by blazergame** [facebook/react-native#17850]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: Windows 10
  Node: 9.2.0
  Yarn: 1.3.2
  npm: 5.5.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.0.0.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.2 => 0.52.2

### Steps to Reproduce

(Write your steps here:)

1. Navigate to https://facebook.github.io/react-native/docs/navigation.html
2. Ctrl + f and type in: React Navigation Getting Started Guide
3. Ctrl + f and type in: Intro to Navigators

### Expected Behavior

The links should reroute to the Navigation guide. However, now it's just a dead link since the Navigation docs has been changed.

### Actual Behavior

Dead link
![404](https://user-images.githubusercontent.com/11071078/35774412-6277804e-0923-11e8-9708-fd2871e9ebdf.PNG)

### Reproducible Demo

N/A

**Comment by blazergame** [comment]
I don't know if we should remove the whole line or change the link to something else so I just submitted a report to see what you guys think.

**Comment by gedeagas** [comment]
Hi, @blazergame thank you for your report.

let's discuss this matter in the react-native-website issue below.
https://github.com/facebook/react-native-website/issues/182

**Comment by gedeagas** [comment]
Quick update @blazergame, there is already a commit to fix this in the documentation (https://github.com/facebook/react-native-website/commit/a9519f143ac1c3928967073562e0815912d23c9a)
( my bad, I didn't see it  🤦  )

**Comment by blazergame** [comment]
Didn't see that either haha. I'll close this.
