### ISSUE TITLE
'CFBundleIdentifier does not exist' issue after *Build Succeeded*

### ISSUE THREAD

**Issue by andrewschreiber** [facebook/react-native#17855]
### Is this a bug report?
Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?
Yes

### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.1.0
  Yarn: 1.2.1
  npm: 5.5.1
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: ^16.0.0 => 16.0.0
  react-native: ^0.50.4 => 0.50.4

### Steps to Reproduce

(Write your steps here:)

1. Open the iOS simulator (iPhone SE)
2. Run `react-native run-ios` in the root directory with a fresh clone of the repo.

### Expected Behavior

The simulator runs the latest build, starting the app. (*The app does successfully open when running from Xcode*)

### Actual Behavior
The build succeeds but then the run fails:

```
...

** BUILD SUCCEEDED **



The following commands produced analyzer issues:
	Analyze /Users/andrew/go/src/github.com/andrewschreiber/hyperdash/app/node_modules/react-native/ReactCommon/yoga/yoga/YGNodeList.c
	Analyze /Users/andrew/go/src/github.com/andrewschreiber/hyperdash/app/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.c
	Analyze Base/RCTModuleMethod.mm
(3 commands with analyzer issues)

Installing build/Build/Products/Debug-iphonesimulator/HyperDash.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/HyperDash.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
```

Cheers!

**Comment by andrewschreiber** [comment]
Turned out I needed to set my Location in settings back to unique:

![image](https://user-images.githubusercontent.com/1892071/35793033-d1924e32-0a04-11e8-946d-3c772adc811f.png)

**Comment by jdnichollsc** [comment]
any solution without use Xcode?
