### ISSUE TITLE
KeyboardAvoidingView incorrectly calculates padding when in-call status bar is active

### ISSUE THREAD

**Issue by buoyad** [facebook/react-native#17862]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS:  macOS High Sierra 10.13.3
  Node:  8.7.0
  Yarn:  1.2.1
  npm:  5.4.2
  Watchman:  4.9.0
  Xcode:  Xcode 9.2 Build version 9C40b
  Android Studio:  2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.51.0 => 0.51.0

Target platform: iOS (11.2)

### Steps to Reproduce

1. Create a fullscreen flex-column `KeyboardAvoidingView` (`behavior="padding"`) with two children
   1. A `View` with `flexGrow: 1`
   2. A `View` containing a `TextInput` with a clear border to help illustrate the problem
   3. Example code [here](https://snack.expo.io/HyigbHULf)
2. in iOS simulator, use CmdOrCtrl+Y or `Hardware > Toggle In-call Status Bar`
3. Tap the input to summon the _on screen_ keyboard (CmdOrCtrl+K to toggle)

### Expected Behavior

I expect the KeyboardAvoidingView to compensate for the offset created by the larger status bar and not allow the keyboard to block the input area.

### Actual Behavior

The keyboard blocks about 20px of the input area.

It looks like [this function](https://github.com/facebook/react-native/blob/master/Libraries/Components/Keyboard/KeyboardAvoidingView.js#L94) calculates the bottom padding based on the layout frame of the `KeyboardAvoidingView` and the final `ScreenRect` given by the `KeyboardChangeEvent`. Debugger shows the layout frame decreases in size when the in-call status bar is active, but `keyboardFrame.screenY` (distance from top(?) of screen) does not decrease, causing the bug.

### Reproducible Demo

The code is [here](https://snack.expo.io/HyigbHULf),  but AFAIK it's not possible to bring up the in-call status bar in expo. The bug is reproducible in simulators of all iPhones except the iPhone X due to the changed status bar.

**Comment by binle** [comment]
look like this issue was not resolved.
Please recheck!

**Comment by dennishansen** [comment]
Hi, is there a plan to fix this? Curious, since iPhone X is an increasing segment of the market.

**Comment by lxcid** [comment]
This still happening

**Comment by irfaan** [comment]
````
// Include
	const {StatusBarManager} = NativeModules;


// Inside componentDidMount
		StatusBarManager.getHeight((statusBarFrameData) => {
			this.setState({statusBarHeight: statusBarFrameData.height});
		});
		this.statusBarListener = StatusBarIOS.addListener('statusBarFrameWillChange', (statusBarData) => {
			this.setState({statusBarHeight: statusBarData.frame.height});
		});

// Use w/ keyboardVerticalOffset in <KeyboardAvoidingView>
````
