### ISSUE TITLE
Android: Modal + ViewPagerAndroid rendered is blank

### ISSUE THREAD

**Issue by rskull** [facebook/react-native#17865]
### Is this a bug report?

Yes, this bug is Android only

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: macOS High Sierra 10.13.2
  Node: 6.11.0
  Yarn: 1.3.2
  npm: 3.10.10
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.0 => 0.53.0

  Target Platform: iOS (10.3) and Android (API 21 and up)

### Steps to Reproduce

1. ViewPagerAndroid in Modal Component
2. open Modal
3. ViewPagerAndroid rendering is blank

### Expected Behavior

ViewPagerAndroid is renderd

### Actual Behavior

ViewPagerAndroid rendering is blank

### Reproducible Demo

https://snack.expo.io/ByVzNkwLz

![2018-02-06 17_14_56](https://user-images.githubusercontent.com/886268/35848383-5021aaba-0b61-11e8-9899-87f1b98383e4.gif)

**Comment by hunterway55** [comment]
we have this issue too, we are looking at using a third party library to get around this.

**Comment by rskull** [comment]
v0.48.4 or less were working properly.

**Comment by ardmn** [comment]
Same issues . I think the maintainers are have only iOS devices and don't want support android. I think they  do work on react-native only because they  likes write code on js for iOS.

**Comment by rskull** [comment]
RN < v0.55

This issue is already resolved.

**Comment by MSchmidt** [comment]
So you are saying it's resolved by updating to RN v0.55+?
