### ISSUE TITLE
Unicode decoding produce unexpecting output for incremental networking 

### ISSUE THREAD

**Issue by jonakyd** [facebook/react-native#17863]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

```
Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.7.0
  Yarn: 1.3.2
  npm: 5.4.2
  Watchman: Not Found
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.50.4 => 0.50.4
```
#### When will this bug happen?
The bug happens if your API response is larger, for that case, `RCTNetworking.mm` will split the response into multiple sections and handle by `incrementalDataBlock`.

#### What is the bug?
The last three bytes of the first fragment of the API response will be wrongly duplicated to the second fragment, which breaks the combined stringify JSON format. 

Let's say the ending of the first fragment is 

```javascript
"homeTeam": {
  "score": 0,
  "position": 0,
  "teamId": 500057,
  "name": "Northern Pride",
  "nickName": "Pride",
  "theme": 
```

Somehow the last three bytes `": ` of the first fragment will be carried over to the second fragment, and makes the second fragment become an invalid JSON format string

```javascript
// `": ` the duplication of the first fragment ending
": 
{
  "key": "pride",
  "logoVariants":
    [
      "badge.png"
```

#### Cause of the bug
I had a more profound look at `RCTNetworking.mm` and found that the issue was caused by the method `[RCTNetworking decodeTextData:fromResponse:withCarryData:]`. 

Inside the method, there are few lines I list below, which will subtract the input data by the delta of original raw data length and encoded string length.

```objc
NSUInteger encodedResponseLength = [encodedResponse dataUsingEncoding:encoding].length;
NSData *newCarryData = [currentCarryData subdataWithRange:NSMakeRange(encodedResponseLength, currentCarryData.length - encodedResponseLength)];
[inputCarryData setData:newCarryData];
```

This line causes the bug that the `newCarryData` length is three even the first fragment is a completely self-enclosed UTF-8 string data.

```objc
NSData *newCarryData = [currentCarryData subdataWithRange:NSMakeRange(encodedResponseLength, currentCarryData.length - encodedResponseLength)];
```

*The `encodedResponse` is three bytes less even the input `currentCarryData` is a completely self-enclosed UTF-8 string data.*

```objc
NSString *encodedResponse = [[NSString alloc] initWithData:currentCarryData encoding:encoding];
```

I have attached the demo project contains the example first fragment of the API response, and in the `ViewController.m` you can see the length differences between the encoded string and raw data.

The issue relative to the change of this PR, https://github.com/facebook/react-native/pull/10110

I'm not sure whether this is an expected behaviour or not, but it definitely will break my handling of API response.

It will be great if @LeoNatan can give some insight. 🙇 

### Expected Behavior

The `RCTNetworking.mm` should be able to handle large API response correctly.

### Actual Behavior

Due to the bug, I mention above, it caused randomly API request failing due to JSON parsing fail.

### Reproducible Demo

The demo project link https://github.com/jonakyd/react-native-decoding-demo

**Comment by LeoNatan** [comment]
@ "bot" Bugs don't magically fix themselves.
