### ISSUE TITLE
buildSettings.LIBRARY_SEARCH_PATHS.push is not a function

### ISSUE THREAD

**Issue by jomnius** [facebook/react-native#17864]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 9.4.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.2 => 0.52.2

### Steps to Reproduce

1. Type "react-native link" on command line
2. Error report requesting to create issue for you

### Expected Behavior

No error

### Actual Behavior

jmiettunen $ react-native link
Scanning folders for symlinks in /Users/jmiettunen/git/project/ern-miniapp/node_modules (11ms)
rnpm-install info Linking react-native-electrode-bridge android dependency 
rnpm-install info Android module react-native-electrode-bridge has been successfully linked 
rnpm-install info Linking react-native-electrode-bridge ios dependency 
rnpm-install WARN ERRGROUP Group 'Libraries' does not exist in your Xcode project. We have created it automatically for you.
rnpm-install ERR! Something went wrong while linking. Error: buildSettings.LIBRARY_SEARCH_PATHS.push is not a function 
Please file an issue here: https://github.com/facebook/react-native/issues 

buildSettings.LIBRARY_SEARCH_PATHS.push is not a function

### Reproducible Demo

Is there some more (debug) info you would like to have? Sorry, cannot send app source code.

**Comment by HasnainAD** [comment]
@jomnius can you tell the format/structure of the newly created array?
