### ISSUE TITLE
asset files in scoped packages are not transformed properly

### ISSUE THREAD

**Issue by atomanyih** [facebook/react-native#17879]
### Is this a bug report?

This is a bug when running jest tests on a react native project

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Steps to Reproduce

1. create a [scoped npm package](https://docs.npmjs.com/misc/scope) that exports an image
2. import that file in jest, or in a file under test
3. run tests

examples:
`@MyCoolScope/MyCoolPackage/image.png` is some image

`MyTest.js`:
```js
import image from '@MyCoolScope/MyCoolPackage/image.png'

describe( // ... etc ...
```

### Expected Behavior

Image should be transformed to something like `{ testUri: 'some/path/to/image.png'}`

### Actual Behavior

Image is not transformed, the binary data is parsed like javascript and the tests crash

### WHY?

The regex for `assetFileTransformer` in [`jest-preset.json#L17`](https://github.com/facebook/react-native/blob/master/jest-preset.json#L17) won't match anything with an `@` in the path.

`[./a-zA-Z0-9$_-]+` should be rewritten as `[@./a-zA-Z0-9$_-]+`

**Comment by hramos** [comment]
Good find! Do you want to open a PR? Please ping me and I'll have it looked at.

**Comment by ide** [comment]
BTW this is the fix that @brentvatne made in the past: `^.+\\.(extensions here)$`. Is there any reason we wouldn't want to match everything that way?
