### ISSUE TITLE
[WebView] additional options for media

### ISSUE THREAD

**Issue by yamill** [facebook/react-native#1787]
<strong>WebView should have properties added for media support:</strong>
<ul>
<li>allowsInlineMediaPlayback</li>
<li>mediaPlaybackRequiresUserAction</li>
</ul>

For example I added this to <strong>RCTWebView.m</strong> to autoplay videos and play them inline:

        - (instancetype)initWithEventDispatcher:(RCTEventDispatcher *)eventDispatcher
        {
          if ((self = [super initWithFrame:CGRectZero])) {
            super.backgroundColor = [UIColor clearColor];
            _automaticallyAdjustContentInsets = YES;
            _contentInset = UIEdgeInsetsZero;
            _eventDispatcher = eventDispatcher;
            _webView = [[UIWebView alloc] initWithFrame:self.bounds];
            _webView.delegate = self;
            _webView.allowsInlineMediaPlayback = YES;
            _webView.mediaPlaybackRequiresUserAction = NO;
            [self addSubview:_webView];
          }
          return self;
        }

Maybe someone can do a PR for this? :)

**Comment by alvaromb** [comment]
@yamill take a look at this PR I did: https://github.com/facebook/react-native/pull/1631

I'm pretty sure it can help you to make this pull request by yourself :shipit: 

Let me know if I can help you with something.

**Comment by yamill** [comment]
@alvaromb awesome thanks that's really helpful! will take a shot at making the pull request :+1:

**Comment by brentvatne** [comment]
Closing because this is stale :)
