### ISSUE TITLE
[Question] RCTWebView _webView instance var

### ISSUE THREAD

**Issue by jaygarcia** [facebook/react-native#1788]
I'm currently looking at extending RCTWebView to inject an executor styled after RCTWebViewExecutor. Is there any particular reason why the RCTWebView's instance of UIWebView is an instance variable instead of a property?

Would you guys accept a PR that changes _webView to a property from an instance var so that devs like myself who want to extend RCTWebView can have access to the UIWebView instance?
 
```
@implementation RCTWebView
{
  RCTEventDispatcher *_eventDispatcher;
  UIWebView *_webView;
}
```

My Goal is to use WebView to render song patterns where react native seems to have trouble (reference: https://www.youtube.com/watch?v=l1YnS9p0hJE)

**Comment by jaygarcia** [comment]
Bump?

I ended up copying  a lot of code to make this happen.

Please correct me if i'm wrong: Seems like I'm not the only person who is running into this.  The React Native core library seems to limit extensibility by virtue of the code patterns leveraged in its development. :(

https://github.com/facebook/react-native/issues/1908

**Comment by brentvatne** [comment]
@jaygarcia - I can't see any reason why such a PR would not be accepted, worth submitting!

**Comment by jaygarcia** [comment]
^--- Thank you. =D

**Comment by nicklockwood** [comment]
I don't see any problem with exposing this property. The reason we didn't is simply that I/we consider it good practice to make properties private by default, and ivars carry less runtime overhead than properties, so again, we use ivars by default unless there's a good reason to expose the functionality.

FWI, Objective-C is incredibly flexible, so you can access the private ivars of a class you are subclassing by using `[self valueForKey:@"ivarName"]`, but this is obviously quite kludgy, so if there's a legit reason to expose the property, go ahead and file a PR :-)
