### ISSUE TITLE
Fetch throws 'Network request failed' on Android SDK Platform 24

### ISSUE THREAD

**Issue by paulus6lau** [facebook/react-native#17891]
# Is this a bug report?
Yes

# Have you read the Bugs section of the Contributing to React Native Guide?
Yes

# Environment
react-native -v: react-native-cli: 2.0.1 react-native: 0.46.3
node -v: v7.7.3
npm -v: 4.1.2
yarn --version (if you use Yarn): ---
Then, specify:

Target Platform: Android
Development Operating System: macOS Sierra 10.12.5 (16F73)
Build tools: Android Studio
# Steps to Reproduce
fetch('https://pricesea.ru/api/auth/info', {
      credentials: 'include'
    }).then(res => {
        ...
      }).catch((e) => {
        console.log(e);
      });
# Expected Behavior
Request should return HTTP code 200 and some data or HTTP code 401.

# Actual Behavior
I have an error:

TypeError: Network request failed
at XMLHttpRequest.xhr.onerror (fetch.js:441)
at XMLHttpRequest.dispatchEvent (event-target.js:172)
at XMLHttpRequest.setReadyState (XMLHttpRequest.js:546)
at XMLHttpRequest.__didCompleteResponse (XMLHttpRequest.js:381)
at XMLHttpRequest.js:485
at RCTDeviceEventEmitter.emit (EventEmitter.js:181)
at MessageQueue.__callFunction (MessageQueue.js:260)
at MessageQueue.js:101
at MessageQueue.__guard (MessageQueue.js:228)
at MessageQueue.callFunctionReturnFlushedQueue (MessageQueue.js:100)
# Reproducible Demo
the bug(https://github.com/facebook/react-native/issues/15100) is reported by @DmitryMaksakov but closed with not-finding root cause.

(Paste the link to an example project and exact instructions to reproduce the issue.)

I have tested different API SDK Platform versions (from 22 up to 26), the problem reproduces only on API SDK Platform 24 (Android 7.0).
I also did this request via native Android app and it was successful on all Platform versions, even 24.

**Comment by paulus6lau** [comment]
https://snack.expo.io/rJYNZk0B- can repro the issue consistently for me with Android 24 sdk.

if it is android 7.0 bug, why does native request work well on Android 7.0 for the same url.

**Comment by mnshkv** [comment]
https://stackoverflow.com/questions/39133437/sslhandshakeexception-handshake-failed-on-android-n-7-0

adding ssl_ecdh_curve prime256v1; to your /etc/nginx/snippets.d/ssl_default

it's android 7.0 bug( not react native)

**Comment by paulus6lau** [comment]
@mnshkv if it is android 7.0 bug, then why does native http request code work well?

**Comment by ajithes1** [comment]
@harikrishnanp thank you :)

**Comment by mnshkv** [comment]
@paulus6lau i think problem in RCT-Network

**Comment by woodenlim** [comment]
Same.. Latest RN version.. Axios and Fetch also not able to fetch https request but http yes.. Android

**Comment by woodenlim** [comment]
same issue on 0.55.. please fix.. Orz

**Comment by lcssanches** [comment]
Same here, but both http and https failed.

- react-native-cli: 2.0.1
- react-native: 0.55.1
- node: v8.9.4
- npm: 5.6.0

Target Platform: Android
Development Operating System: Windows 10
Build tools: VSCode

**Comment by havinhthai** [comment]
+1

**Comment by sooxiaotong** [comment]
I had added TRY ... CATCH ... within it, but it still cant handle the exception :( .  +1

**Comment by havinhthai** [comment]
We can catch error by this way (from docs):

```
axios.get('/user/12345')
  .catch(function (error) {
    if (error.response) {
      // The request was made and the server responded with a status code
      // that falls out of the range of 2xx
      console.log(error.response.data);
      console.log(error.response.status);
      console.log(error.response.headers);
    } else if (error.request) {
      // The request was made but no response was received
      // `error.request` is an instance of XMLHttpRequest in the browser and an instance of
      // http.ClientRequest in node.js
      console.log(error.request);
    } else {
      // Something happened in setting up the request that triggered an Error
      console.log('Error', error.message);
    }
    console.log(error.config);
  });
```

Case you want to config (from docs):

```
  // `validateStatus` defines whether to resolve or reject the promise for a given
  // HTTP response status code. If `validateStatus` returns `true` (or is set to `null`
  // or `undefined`), the promise will be resolved; otherwise, the promise will be
  // rejected.
  validateStatus: function (status) {
    return status >= 200 && status < 300; // default
  }
```

**Comment by sooxiaotong** [comment]
@havinhthai What can i do next ><
![image](https://user-images.githubusercontent.com/13378059/39198960-f7182218-481a-11e8-947e-21e17b2434dc.png)

**Comment by havinhthai** [comment]
@sooxiaotong I solved this issue by replace url (ex: https://wifi.unifi.com.my) to IP of Server.

example: If in local, you can replace http://localhost:3000 to http://23.45.42.23:3000 (23.45.42.23 is IP of your laptop)

**Comment by hugohow** [comment]
+1

**Comment by zekiunal** [comment]
Turn of Windows Firewall

**Comment by ericLoansnap** [comment]
This remains an issue with react-native 0.55.4, and is present on 0.55.3, 0.55.2, 0.55.1, and 0.55.0.  It turns out that the react-apollo library also depends on this.

**Comment by Chatharaju** [comment]
Am using react-native 0.55.1, Android seems working fine on my end but I have this issue with iOS. I have played with AppTransportSecurity protocol as well. Any solutions other than downgrading RN version

**Comment by ethanyuwang** [comment]
Having the same problem. Works fine on iOS

**Comment by ericLoansnap** [comment]
Turns out the problem is the Android bug, and here is how to fix it:
https://developers.google.com/pay/api/android/guides/resources/payment-data-cryptography#the-signature-algorithm

I think this should return an Exception when the version is Android 7 to verify that the security settings are correct. 

For reference, this is how the solution was found:  https://stackoverflow.com/questions/45170365/react-native-fetch-throws-network-request-failed-on-android-7-but-works-fin#45278124

**Comment by KthProg** [comment]
I'm having this issue. I also get some error about "Tunnels" that I can't log so I don't know anything else. This is https POSTing to an azure web service. The certificate chain is just fine.

**Comment by yeknava** [comment]
Im experiencing same issue, im updating (rewriting) my app with newer version (RN 56). but funny thing is my old app works pretty fine with same request to same https server on same android 7 device and it was written by RN 42. i think there is something between android 7 and okhttp that cause this problem.

**Comment by KthProg** [comment]
I detached with Expo. That seemed to be a cause of the issue. To fix it, I had to run `exp publish` before I run `gradlew assembleRelease`. I have to do this for every single build. It seems like there's needs to be some more communication and testing between the two teams because almost nothing worked the way it should when I detached from a project started with Expo and I had to implement _many_ custom fixes.

**Comment by yeknava** [comment]
@KthProg I dont use expo and building my apps with native code but still experiencing same issue.

**Comment by KthProg** [comment]
I can't be totally sure what the cause is then. Mine was fixed once the bundle scripts were generated. There may have been an issue with the version on React Native/Expo I was using. I deleted everything I had and brought it all down from source control, then installed all the packages again and upgraded Expo to the latest.

**Comment by KthProg** [comment]
My issue was only in production by the way, so it may have been a different issue related to Expo.

**Comment by ethanyuwang** [comment]
it seems like it has something to do with gzip. If I add the header `'Accept-Encoding': 'gzip'`, I was able to log the response. However, the response body is empty:


```
{ type: 'default',
status: 200,
ok: true,
statusText: undefined,
headers: 
{ map: 
{ date: 'Mon, 27 Aug 2018 18:39:23 GMT',
'content-type': 'application/json',
'content-length': '215',
'content-encoding': 'gzip',
'cache-control': 'no-cache' } },
url: 'http://test....list',
_bodyInit: '',
_bodyText: '' }
```

**Comment by balwinder4264** [comment]
If it is working with Ios then replace localhost to main ip address of Your computer.

**Comment by adirzoari** [comment]
@paulus6lau  same issue in android. any solution?

**Comment by balwinder4264** [comment]
@adirzoari use network ip address where you are using localhost for sending request.

**Comment by adirzoari** [comment]
@balwinder4264  it happen my in production version (not with localhost address).. I send to real address and it happen when no internet connection

**Comment by balwinder4264** [comment]
@adirzoari if there is no internet connection use 127.0.0.1 instead localhost. If you maintain server in your machin. Or if you are sending request outside obviously you should have internet connection.

**Comment by adirzoari** [comment]
@balwinder4264 umm but if suddenly there is no internet connection, I can't replace it to 127.0.0.1.. I work with specific url to get data, but if no internet it shows me 'Network request failed'

**Comment by balwinder4264** [comment]
@adirzoari  because you can’t access intrnet URL without internet.!! As u can not send message on whatsapp without internet

**Comment by adirzoari** [comment]
@balwinder4264  I know I agree with it, but how I catch this error and show the users specific error in this case?

**Comment by balwinder4264** [comment]
@adirzoari put your request in try catch and make alert in catch block alert(“network error”)

**Comment by nickjuntilla** [comment]
The problem for me was that React Native brought back the type 'image' for images from the picker. The type passed to the file uploader needed to be like 'image/jpg'

```
    form.append(uploadFileName, {
      uri : localImage.full,
      type: 'image/jpeg',
      name: uploadFileName
     })
```

**Comment by jifromz09** [comment]
> @sooxiaotong I solved this issue by replace url (ex: https://wifi.unifi.com.my) to IP of Server.
> 
> example: If in local, you can replace http://localhost:3000 to http://23.45.42.23:3000 (23.45.42.23 is IP of your laptop)

-The most suggested answer even on stackoverflow, I tried this solution many times, but the issue still persist.

**Comment by Dgs-asohail4** [comment]
I cannot understand whats the point of error message "Network request failed" ... what happened the cold weather caught it or the aliens from the future took it... a bit more detail would be appropriate @nickjuntilla answer was close to my use case but it didn't work either.

`  const { name, date, description, location, uri, mime, time } = this.state;


    const value = {
      name,
      date,
      description,
      location,
      time
    }

    const formData = new FormData();
    formData.append('name', name)
    formData.append('date', date)
    formData.append('description', description)
    formData.append('location', location)
    formData.append('time', time)

    formData.append('image',{
      uri:uri,
      mime:'image/jpeg',
      name:`image${moment()}`
    })


    alert(JSON.stringify(formData));
    const config = {
          method: 'POST',
          headers: {
            'Accept': 'application/json',
          },
          body: formData,
      };

    fetch(`http://${Config.apihost}:${Config.port}/events`,config).then((res) => res.json())
      .then((res) => {
        this.setState({ modalVisible: false, name:'', date: moment().format('YYYY-MM-DD'), description:'', Location: 'AlHedaya Masjid' })
        this.props.addEvent(res.message);

      // this.props.navigation.goBack();
      }).catch((err) => alert(err));
`
