### ISSUE TITLE
iOS Pod issues

### ISSUE THREAD

**Issue by Plo4ox** [facebook/react-native#17893]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 9.4.0
  Yarn: Not Found
  npm: 4.6.1
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.0 => 0.53.0

Target Platform: iOS (11.2)

### Steps to Reproduce

Follow the tutorial presented here:
https://facebook.github.io/react-native/docs/integration-with-existing-apps.html

### Expected Behavior

Succeed to build the app.

### Actual Behavior

it doesn't work .

I'm kidding, the build just failed with the following errors:
 - Yoga-internal.h:11:10 : fatal error: 'algorithm' file not found: #include <algorithm>
 - RCTConvert.h:19:9 : fatal error: could not build module 'yoga': #import <yoga/Yoga.h>

Those errors occur while building module 'yoga' imported from `React/Base/RCTConvert.h`

<img width="293" alt="screen shot 2018-02-07 at 10 28 39" src="https://user-images.githubusercontent.com/7001412/35908923-54844b44-0bf2-11e8-9cb1-9f36050599e6.png">

### Reproducible Demo

You can get the non working project on the following repo:

% git clone https://github.com/Plo4ox/ReactNativeIssues.git
% cd ReactNativeIssues
% npm install
% cd ios
% pod install
% cd ..
% react-native run-ios

Or just follow the steps:

% create-react-native-app AwesomeProject
% cd AwesomeProject
% mkdir ios

// Modify the package.json file fill it content indicated in the documentation:
```
{
  "name": "MyReactNativeApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  }
}
```

% npm install --save react@16.2.0 react-native

// Create a new single view app project into the iOS directory, using Xcode

% cd ios
% pod init

// Fill the Podfile with the content indicated in the documentation, be sure to keep your default target
```
 use_frameworks!

  # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'GLog', :podspec => '../node_modules/react-native/third-party-podspecs/GLog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
``` 

% pod install
% cd ..
% react-native run-ios

### Pull Request

A PR related to this issue has already been created here:
https://github.com/facebook/react-native/pull/17764

**Comment by Titozzz** [comment]
Same issue

**Comment by xiaoyongchen** [comment]
Same issue 
'algorithm' file not found 
Could not build module 'yoga'
-    "react": "16.0.0-alpha.12"=>"react": "^16.2.0",
-    "react-native": "0.47.1",=>"react-native": "^0.53.0",
pod 'React', :path => '../zm_parents/node_modules/react-native', :subspecs => [
'Core',
'RCTText',
'RCTNetwork',
'RCTWebSocket', # needed for debugging
'RCTVibration',
'RCTLinkingIOS',
'RCTImage',
'RCTAnimation',
#'RCTAdSupport',
'RCTSettings',
'BatchedBridge',
'DevSupport',
'ART',
# Add any other subspecs you want to use in your project
]
# 如果你的RN版本 >= 0.42.0，请加入下面这行
pod "yoga", :path => "../zm_parents/node_modules/react-native/ReactCommon/yoga"

**Comment by xiaoyongchen** [comment]
How to solve this problem

**Comment by makovkastar** [comment]
I have fixed the issue by downgrading React Native to [0.51.0](https://github.com/facebook/react-native/releases/tag/v0.51.0).

**Comment by msand** [comment]
Archiving an iOS build seems broken with the new Cocoapods 1.4.0 as well. Downgrading it to 1.3.1 seems to help.

**Comment by amardeepranu** [comment]
Also getting this

**Comment by Plo4ox** [comment]
@makovkastar That's what I did at first, and indeed it works, but it would be cool to be able to use the latest version :)

**Comment by ushu** [comment]
@Plo4ox downgrading seems the most reliable option: I tried 0.52, 0.53 and even 0.54-rc with no more success...

**Comment by FlyOrDie** [comment]
Same issue here. Don't think, that downgrading is something, that is supposed to be the best solution :)

**Comment by msand** [comment]
@FlyOrDie I also had to remove the inherited header search paths to get it to build, haven't had time to investigate further.

**Comment by FlyOrDie** [comment]
@msand A strange thing helped me to solve the problem. I don't even know, why I did it. In **pods** file, I changed the sequence...

from:
    'RCTText',
    'RCTNetwork',

to:
    'RCTNetwork',
    'RCTText',

Started working. It is not related to cache in any way, because I was dropping caches of everything, including _NPM_ every time to make experiments clean :D

**Comment by eapostol** [comment]
+1 encountering this issue as well, if one has to downgrade so be it, but this should not be the solution.

**Comment by krmao** [comment]
it's still exists !

**Comment by simonas88** [comment]
I am also encountering this issue when trying to upgrade from 0.51.0 to 0.52+

**Comment by msand** [comment]
I hadn't noticed this was using the "use_frameworks!" my issues we're probably unrelated. Managed to get use_frameworks building with the patches from here: https://github.com/facebook/react-native/pull/17764#issuecomment-367943213 but archiving fails with 0.54 with this: https://github.com/facebook/react-native/issues/18205

**Comment by Plo4ox** [comment]
@msand I wrote a comment on this issue [#18205](https://github.com/facebook/react-native/issues/18205)
The developer used Objc++ to pass object by references, and as Apple says [here](https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/index.html):
`You cannot import C++ code directly into Swift. Instead, create an Objective-C or C wrapper for C++ code.`
The fix here is to do something like `CGSize * minimumSize` instead of `CGSize &minimumSize` and of course to change the impacted files.
But as I said in my [PR](https://github.com/facebook/react-native/pull/17764), I don't know if  we should create a huge PR with all the fixes or keeping small PRs, and I'm still waiting for an answer ^^

**Comment by msand** [comment]
I think at this point it's probably good to made a single PR with all the needed patches to have it working with manual linking, normal cocoapods, and cocoapods with use_frameworks! on.
I managed to get it working with 0.53.3, but building and archiving from XCode breaks, while it works from the CLI, not sure what command XCode runs, or what environment variables are different enough to cause the failure. https://github.com/facebook/react-native/issues/14749#issuecomment-372046477

**Comment by msand** [comment]
Found another workaround for the non use_frameworks case: https://github.com/facebook/react-native/issues/15838#issuecomment-372681307 Essentially a duplicate target for debugging with manually linked React Native modules, and using the xcodebuild cli to build release for simulator and archive for TestFlight / AppStore.

**Comment by The0racle** [comment]
Having this issue on version 0.55. Did anybody find a solution?

**Comment by Plo4ox** [comment]
@The0racle After a quick glance at the version 0.55.2, and I had the following issue:
<img width="275" alt="screen shot 2018-04-10 at 00 29 53" src="https://user-images.githubusercontent.com/7001412/38526364-54a6e53e-3c56-11e8-8293-116f24c809f9.png">
Is this the one you are referring to?
If so, it seems that it has been corrected in the current version of Master by the following commit: https://github.com/facebook/react-native/commit/c787e0e25216d04a76ce2e3c0c88218ab9db3545
As @fkgozali said [here](https://github.com/facebook/react-native/pull/17764#issuecomment-376043639), the `RCTFabricUIManagerWrapper.mm shouldn't have been linked to the existing project since it's experimental`.

**Comment by NrqhEIcsRi004** [comment]
Change  use_frameworks! ==> #  use_frameworks! ?

**Comment by koenpunt** [comment]
To apply patches automatically you can use the [`cocoapods-fix-react-native`](https://github.com/orta/cocoapods-fix-react-native/) CocoaPods plugin. It currently has support for 0.53.3, 0.54.2, 0.54.4, and 0.55.3

**Comment by varakumar1105** [comment]
@Plo4ox Any progress on this ??

Thanks in advance

**Comment by sethdeckard** [comment]
@xiaoxiaocainiao I am experiencing this problem in a new project using version 0.55.4. I am also not using `use_frameworks!`.

**Comment by lazyjean** [comment]
react-native @0.55.4 have the same issue
My project need use use_frameworks!,
I fix the issue by change project settings
1. navigate to target React
2. Build Settings -> Always Search user Path(Deprecated) YES
3. fix some easy header import errors

**Comment by ggsrivas** [comment]
I am using react-native@0.53.3. I faced all these issues. As suggested by others, I tried below steps,
1. `Build Settings -> Always Search user Path(Deprecated) YES` for React Target.
2. change `#import <RCTAnimation/RCTValueAnimatedNode.h>` to` #import "RCTValueAnimatedNode.h"`
3. change `#import <fishhook/fishhook.h>` to `import "fishhook.h"`
after all this I am getting below error,

```

Undefined symbols for architecture x86_64:
  "google::LogMessageFatal::LogMessageFatal(char const*, int)", referenced from:
      facebook::react::customJSCWrapper() in JSCWrapper.o
      facebook::react::setCustomJSCWrapper(facebook::react::JSCWrapper const*) in JSCWrapper.o
  "google::LogMessage::stream()", referenced from:
      facebook::react::customJSCWrapper() in JSCWrapper.o
      facebook::react::setCustomJSCWrapper(facebook::react::JSCWrapper const*) in JSCWrapper.o
  "google::LogMessageFatal::~LogMessageFatal()", referenced from:
      facebook::react::customJSCWrapper() in JSCWrapper.o
      facebook::react::setCustomJSCWrapper(facebook::react::JSCWrapper const*) in JSCWrapper.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Anyone else faced similar issue? Any suggestions on fixing it?

**Comment by ggsrivas** [comment]
I copied snipped from below location in my podfile and it seems to work fine,
https://gist.github.com/Jpunt/3fe75effd54a702034b75ff697e47578

It would have been awesome if react team could have fixed all these in a patch to 0.53 version and corresponding dependencies.

**Comment by hramos** [comment]
Please verify using the `0.56` release candidate.

**Comment by willswinson** [comment]
Getting this no matter what I do.  I've updated the header search paths to search the React folder in the node module folder and I've linked all libs.

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RCTBundleURLProvider", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_RCTConvert", referenced from:
      objc-class-ref in libRNImageCropPicker.a(ImageCropPicker.o)
  "_OBJC_CLASS_$_RCTRootView", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_RCTViewManager", referenced from:
      _OBJC_CLASS_$_BlurViewManager in libreact-native-blur.a(BlurViewManager.o)
      _OBJC_CLASS_$_VibrancyViewManager in libreact-native-blur.a(VibrancyViewManager.o)
  "_OBJC_METACLASS_$_RCTViewManager", referenced from:
      _OBJC_METACLASS_$_BlurViewManager in libreact-native-blur.a(BlurViewManager.o)
      _OBJC_METACLASS_$_VibrancyViewManager in libreact-native-blur.a(VibrancyViewManager.o)
  "_RCTRegisterModule", referenced from:
      +[ImageCropPicker load] in libRNImageCropPicker.a(ImageCropPicker.o)
      +[BlurViewManager load] in libreact-native-blur.a(BlurViewManager.o)
      +[VibrancyViewManager load] in libreact-native-blur.a(VibrancyViewManager.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)



** BUILD FAILED **
```

**Comment by hramos** [comment]
@willswinson can you confirm this is happening in 0.56?

**Comment by ricsam** [comment]
Are you guys removing all *.xcodeproj from the Libraries section to prevent libraries from being compiled and linked twice?

**Comment by iDay** [comment]
@ricsam yes, but you need to add a new start package script in your project build phrase
<img width="858" alt="2018-07-31 9 48 01" src="https://user-images.githubusercontent.com/3729025/43458541-2f7e798e-94fd-11e8-9eaf-afc6daee3fd7.png">

**Comment by viktorlarsson** [comment]
@willswinson  @hramos Experiencing the same issue with 0.56
