### ISSUE TITLE
[Bridge] Allow RCTViewManager to define view instance methods exposed to JS

### ISSUE THREAD

**Issue by ide** [facebook/react-native#179]
(Related to the discussion in #114)

The gist of what I want to do is to call methods on view instances where setting a prop doesn't make sense. A common example of this is focusing/blurring a text field. The current API (`this.refs.textInput.focus()`) is right on, but the implementation is a bit roundabout going through a static method on the UIManager to look up the view and set the first responder state. It would be much better for module implementors to be able to expose methods on the view instances directly and not have to think about the node handle -> view lookup.

A rough sketch of what this could look like is:
```objc
// in RCTTextFieldManager.m
RCT_CUSTOM_VIEW_METHOD(focus, RCTTextField)
{
  // "view" is defined w/static type RCTTextField
  dispatch_async(dispatch_get_main_queue(), ^{
    [view becomeFirstResponder];
  });
}
```

I haven't thought too much about how arguments and return values should be handled though arguments in particular seem important to support.

**Comment by chirag04** [comment]
Seems like it can be useful to extend RCTTextField for tooltip. :)

**Comment by brentvatne** [comment]
This is a neat idea cc @tadeuzagallo

**Comment by tadeuzagallo** [comment]
That's interesting, and I've talked about something similar with @nicklockwood before, but the problem that always comes up is that in most of the use cases the method would have to be sync...

**Comment by nicklockwood** [comment]
Yeah, we do this already for stuff like RCTWebView, and it's a pain doing the same lookup code every time. Makes sense to have a simple macro to wrap that logic.

**Comment by nicklockwood** [comment]
It should probaby wrap the UIBlock logic as well for view methods, to avoid accidents. Then there would be no need to dispatch to main queue inside the method.

**Comment by brentvatne** [comment]
Who wants to take lead on this one? @ide? :smile:

**Comment by sahrens** [comment]
Ping on this?

**Comment by olivierlesnicki** [comment]
+1

**Comment by olivierlesnicki** [comment]
how would one obtain the same behavior now?

**Comment by ide** [comment]
You need to pass the reactTag of the component to the native layer and look it up in a dictionary that maps tags -> views. Some of the native components in this repo do this like the focus/blurring of text inputs.

**Comment by olivierlesnicki** [comment]
I get `property uiManager` not found on object of type RCTBridge*

**Comment by ide** [comment]
You probably need to import the header that defines the category that adds uiManager --  RCTUIManager.h I think.

**Comment by olivierlesnicki** [comment]
spot on

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/bridge-allow-rctviewmanager-to-define-view-instance-methods-exposed-to-js

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.
