### ISSUE TITLE
[Packager] New error after upgrading to 0.7.0-rc.2

### ISSUE THREAD

**Issue by andrewngu** [facebook/react-native#1790]
I'm currently getting an error "undefined is not an object (evaluating 'NativeModules.ProgressViewManager.ComponentHeight') after upgrading to latest version of react-native. 

![screen shot 2015-06-29 at 3 27 39 pm](https://cloud.githubusercontent.com/assets/2625231/8420010/680dc10a-1e73-11e5-8ed3-ebe34977fb34.png)

**Comment by ide** [comment]
This sounds like you might have an old copy of React Native somewhere that is conflicting. Make sure that under your node_modules directory (and its subdirectories) there's only one copy of react-native and it's 0.7.0-rc.2.

**Comment by chirag04** [comment]
Use ``find . -name 'react-native' -print`` to list all the react-native versions installed. Remove all those versions which are inside a sub-directory.

**Comment by andrewngu** [comment]
Turns out this error was a result of me changing my app name and not updating the bundle identifier with Facebook. I'm using Facebook Login with my app.

**Comment by PhilippKrone** [comment]
I have the very same error while using the Facebook login, but my bundle identifier has not changed. Any idea?

**Comment by PhilippKrone** [comment]
@brentvatne could you reopen please?

**Comment by ide** [comment]
@philippkrone if you clean your node_modules and ensure there's only one copy of react native this should go away.

**Comment by PhilippKrone** [comment]
Hi,

is there any necessity to clear the cache?

my-MBP: PhilippKrone$ find . -name 'react-native' -print
./node_modules/react-native
./node_modules/react-native/Libraries/react-native

**Comment by ide** [comment]
That looks correct to me. Can you try running the packager manually to be totally sure that no other copy of React Native is possibly running? The command is `node_modules/react-native/packager/packager.sh`.
