### ISSUE TITLE
INSANE Memory Leaks !!!!!

### ISSUE THREAD

**Issue by azamsharp** [facebook/react-native#17913]
### Is this a bug report?

Yes

Here is the video: 

https://twitter.com/azamsharp/status/961667289815900160

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.)

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by anderskev** [comment]
This appears to be a bug with Expo, not React Native, also you didn't fill out the template.

**Comment by azamsharp** [comment]
I did reinstall and even reset the content settings and still the same issue. Also, on Android it is not working: 

I run npm run android and this is what I get: 

<img width="566" alt="screen shot 2018-02-08 at 2 56 19 pm" src="https://user-images.githubusercontent.com/16604/35997837-5e06b05a-0ce0-11e8-90b8-7786dc380317.png">

The link in the error goes to 404.

**Comment by brentvatne** [comment]
here ya go: https://stackoverflow.com/questions/8624519/simulator-slow-motion-animations-are-now-on

**Comment by brentvatne** [comment]
oh and as for the error on android, you left out a lot of the message it looks like. we don't know what command you ran or anything. please re-post that issue and fill out the issue template if it persists!

**Comment by brentvatne** [comment]
(and the broken link is fixed in the latest version, in 0.53 https://github.com/facebook/react-native/commit/6661633390276f707faa60509b2805a83929e747)
