### ISSUE TITLE
[Bridge] Destruction order is not being guaranteed between managers and views

### ISSUE THREAD

**Issue by jwyld** [facebook/react-native#1791]
I've got a situation where a RCTRootView is being torn down.  Inside the React world, there is a MapView being used.  RCTMapManager makes itself the delegate of the RCTMapView it hands out (this pattern is used all over).  On tear down though, I'm seeing the manager being torn down after the RCTMapView instance.  The problem is that in some cases the RCTMapView is still going through region changes.  MKMapView is attempting to perform the callback to the delegate, but the delegate is long since destroyed.

Since this pattern is used quite a bit, I believe a solution needs to be created in order to enforce an order to destruction.

**Comment by brentvatne** [comment]
Closing because stale, please reopen if this is important :)
