### ISSUE TITLE
PanResponder.onStartShouldSetPanResponder reports 1 single touch on multi touch gestures

### ISSUE THREAD

**Issue by hardcodet** [facebook/react-native#17928]
### Is this a bug report?

Yes (potentially)

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: Windows 10
  Node: 8.9.1
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.0.0.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.0 => 0.52.0

### Steps to Reproduce

If I touch the screen with two fingers, I get two events using `View.onTouchStart`, but only one invocation on a `PanResponder`'s `onStartShouldSetPanResponder` callback (since I guess it aggregates those events). However, the number of reported touches is always just `1`. There is simply no way to determine whether my PanResponder should actually handle a given touch event based on the supplied gesture information, as it's lacking the aggregated context. I assume that is not the desired behavior...

My use case: A view with a PanResponder within a FlatList. Depending on whether this is a pinch gesture or just a swipe, I need to grab the gesture or not in order to have the FlatList handle it.
            

### Expected Behavior

On multi-touch gestures (e.g. two fingers touching the screen at the same time), the event and gestureState that are submitted to `onStartShouldSetPanResponder` should contain all active touches, not just one.

### Actual Behavior
I only get a single callback on a multi-touch gesture, with only a single touch inside.

### Reproducible Demo

Create an app, run it locally with a PanResponder like this. You'll get three times "1":

    this.myResponder= PanResponder.create({
            onStartShouldSetPanResponder: (evt, gestureState) =>  {
                alert("active touches: " + gestureState.numberActiveTouches + ", evt touches: " + evt.nativeEvent.touches.length + ", " + evt.nativeEvent.changedTouches.length);
                return true,

**Comment by DanielBoening** [comment]
I have the same bug. On iOS multitouch works fine but on Android PanResponder always returns one touch only.
React Native Version 0.54.2, it seems that there is no change in version 0.55.0 according to the changelog.

**Comment by yuoppp** [comment]
Same issue for me. But on Android it works fine, on iOS I receive only one touch

**Comment by diego-caceres-galvan** [comment]
I'm having the same issue as reported but only for Android. Which version of RN are you using @yuoppp ? 
Thanks

**Comment by diego-caceres-galvan** [comment]
Has anyone found a workaround for this?

**Comment by DanielBoening** [comment]
No, not so far.

**Comment by diego-caceres-galvan** [comment]
I was able to fix my problem yesterday with a workaround. I first thought that this was caused because I had the View with the PanResponder inside a FlatList. But it was also inside a TouchableOpacity and, at least in my case, this was the problem for Android not getting 2 touches. 

Switching these two (putting the View with the PanResponder outside the TouchableOpacity) made it work for me. I know get the 2 touches both in Android and in iOS (in the original order, iOS was already working for me).

**Comment by utkarshGithub** [comment]
facing the same issue any help ?

**Comment by DanielBoening** [comment]
Actually it seems to work now on react native 0.56. What rn version are you using?
