### ISSUE TITLE
[Packager] Seemingly pointless call to depGraph.load() in HasteDependencyResolver.prototype.getDependencies

### ISSUE THREAD

**Issue by aleclarson** [facebook/react-native#1792]
It seems like there's [a pointless call](https://github.com/facebook/react-native/blob/master/packager/react-packager/src/DependencyResolver/index.js#L81-L82) to `depGraph.load()` inside `HasteDependencyResolver.prototype.getDependencies`.

`DependencyGraph.prototype.getDependencies` already calls `this.load()` [at the beginning](https://github.com/facebook/react-native/blob/master/packager/react-packager/src/DependencyResolver/DependencyGraph/index.js#L150-L151).

It's a minor detail, but something seemed fishy so I figured I should report it.

**Comment by amasad** [comment]
Yes, you're write :)
