### ISSUE TITLE
Create new project, iOS release build crashes on open

### ISSUE THREAD

**Issue by jackdewhurst** [facebook/react-native#17930]
### Is this a bug report?

YES

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

YES

### Environment

OS: macOS High Sierra 10.13.2
Node: 6.9.4
Yarn: 1.3.2
npm: 5.6.0
Watchman: 4.7.0
Xcode: Xcode 9.2 Build version 9C40b
Android Studio: 2.3 AI-162.3871768

Packages: (wanted => installed)
react: 16.2.0 => 16.2.0
react-native: 0.53.0 => 0.53.0

Target Platform: iOS (8.0)

### Steps to Reproduce

1. Create new blank project with `create-react-native-app`.

2. cd to project and `run yarn run ios`. Verify it runs fine in simulator.

3. Run `npm run eject` to generate Xcode project. Choose option *React Native: I'd like a regular React Native project.*

4. Open Xcode project, follow the official documentation here - https://facebook.github.io/react-native/docs/running-on-device.html to edit project for Release builds. Specifically all the steps in the *Building your app for production* section.

5. Build and run the app through Xcode on device or simulator.

### Expected Behavior

I would expect the simulator or device (depending on destination) to run the app and display the standard default layout created using `create-react-native-app`.

### Actual Behavior

The app crashes on open with the following exception:

```2018-02-08 09:31:38.089 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: Super expression must either be null or a function, not string
2018-02-08 09:31:38.089867+0000 FB[658:508707] Unhandled JS Exception: Super expression must either be null or a function, not string
2018-02-08 09:31:38.090 [error][tid:com.facebook.react.JavaScript] Module AppRegistry is not a registered callable module (calling runApplication)
2018-02-08 09:31:38.090165+0000 FB[658:508728] Module AppRegistry is not a registered callable module (calling runApplication)
2018-02-08 09:31:38.101757+0000 FB[658:508707] *** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: Super expression must either be null or a function, not string', reason: 'Unhandled JS Exception: Super expression must either be null or a function,..., stack:
inherits@11:1777
<unknown>@300:387
<unknown>@300:810
a@2:837
<unknown>@12:86
a@2:837
<unknown>@2:309
global code@362:9
'
*** First throw call stack:
(0x18118a364 0x1803d0528 0x18118a2ac 0x100d3982c 0x100d374f0 0x181191cd0 0x18107056c 0x18107501c 0x100d4a4ec 0x100d8a208 0x100d89f68 0x1013652cc 0x10136528c 0x101373f80 0x1013687ec 0x101374f6c 0x10137c020 0x180daef1c 0x180daeb6c)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

After hours of searching I can only come to the conclusion that index.js is not being found as it's logging errors regarding AppRegistry not being registered. I've tried modifying my Build Phase script to specify an exact index.js file location as such:

```
export NODE_BINARY=node
 ../node_modules/react-native/scripts/react-native-xcode.sh ./index.js
```

But it makes no difference.

### Reproducible Demo

Project here - https://github.com/jackdewhurst/TestReactNative
Instructions - Clone and run release configuration in Xcode. The app crashes.

**Comment by jackdewhurst** [comment]
I've just tried this on a different machine, new install of High Sierra, fresh install of `npm 4.6.1` and `create-react-native-app` and latest Xcode from App Store.. But the same exception occurs.

I don't understand what I'm doing wrong. Is anyone able to get working production iOS builds from react native 0.53.0 ??

**Comment by jackdewhurst** [comment]
For anyone who has this problem I fixed it eventually by making sure every subclassed component is declared as such:

```
import React from 'react';

export default class {NAME} extends React.Component {
} 
```

Before I had a class declared as:

```
import {View} from 'react-native'

export default class {NAME} extends View {
}
```

Which works on debug but not on release..

No idea how this was affecting new unedited projects with `create-react-native-app`.. cache issues maybe? In any case i've switched to `react-native-cli` and made made the change in my component classes above. Release iOS builds now work.

**Comment by sasayah** [comment]
I have a same problem.
Did you resolve this?
