### ISSUE TITLE
CameraRoll does not provide thumbnail URIs and Image components don't choose smallest size to display

### ISSUE THREAD

**Issue by daku** [facebook/react-native#17931]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 9.3.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.1 => 0.52.1

  Target Platform: iOS (11.2)

### Steps to Reproduce

(Write your steps here:)

1. Use `CameraRoll` API to get any subset of images
2. Display the image using the included URI

### Expected Behavior

In addition to the full-size image URI there will be thumbnail URIs as well. For example, on Android it would be nice to include thumbnail URIs (can be queried from the `MediaStore` as described here https://stackoverflow.com/a/5630543). If not this, then maybe Image components can display the thumbnails since they are stored natively in both iOS and Android.

### Actual Behavior

No thumbnail URIs are present. Thus, full images must be resized by the `Image` component to show as thumbnails. My investigation of `CameraRollManager.java`  and other files in `ReactAndroid/.../moduels/image` or `ReactAndroid/.../views/[image |  imageHelper]` did not indicate that thumbnail URIs were being retrieved or the closest possible size to the one requested was being displayed by the `Image` component. This maybe true for iOS like existing `react-native` documentation suggests, but I have not investigated the iOS side yet. 

### Reproducible Demo

https://github.com/jeanpan/react-native-camera-roll-picker or any of its forks.

**Comment by pontusab** [comment]
This is still an issue in `0.57.1`, is there a way to get a smaller image in cameraRoll?
