### ISSUE TITLE
No component found for view with name RCTText

### ISSUE THREAD

**Issue by anderskev** [facebook/react-native#17933]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?
Yes

### Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 9.3.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.0.0 => 16.2.0
  react-native: 0.53.0 => 0.53.0

  Target Platform: iOS (11.1)

### Steps to Reproduce

1. Create a new xcode project and add react native according to [Integration with Existing Apps](https://facebook.github.io/react-native/docs/integration-with-existing-apps.html)
2. Add a `TextInput` anywhere
3. Run in xcode or `react-native run-ios`

### Expected Behavior

The app runs.

### Actual Behavior
 RSOD with `No component found for view with name 'RCTRawText'`

![screenshot](https://i.imgur.com/YwFk71J.png)

Additionally, running in xcode reveals the following:
```2018-02-09 19:20:15.963 [error][tid:com.facebook.react.JavaScript] Invariant Violation: Native component for "RCTSinglelineTextInputView" does not exist

This error is located at:
    in RCTSinglelineTextInputView
    in TouchableWithoutFeedback
    in TextInput
```

I originally encountered this bug using the third party package [react-native-material-textfield](https://github.com/n4kz/react-native-material-textfield). The xcode error was the same, however the RSOD error was looking for RCTText instead of RCTRawText. Upon some digging, I assume this is related to these changes from 0.52.0 [The New Text on iOS ](https://github.com/facebook/react-native/commit/2716f53220f947c690d5f627286aad51313256a0). I have seen this behavior on 0.52.0 and 0.53.0.

Also of note, this only happens when integrating React Native via CocoaPods (as the docs recommend). This does not occur with a project that is started via `react-native init`, so perhaps this is related to how the RCText subspec is included somehow? For what it's worth, the subspecs included in the project experiencing this bug are as follows:

```  pod 'React', :path => react_path, :subspecs => [
    'Core',
    "CxxBridge",
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTBlob',
    'RCTImage',
    'RCTText',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTImage',
    'RCTWebSocket',
  ]
```

### Reproducible Demo

Will add in a few hours once I get home. Additionally I'd be willing to submit a PR if someone could point me in the correct direction just to get started.

**Comment by ide** [comment]
@grabbou there's a fix for this on 0.53-stable already (https://github.com/facebook/react-native/commit/2c63f4926945904a076d9cc921e1490608ce1e75) - can you release 0.53.1?

**Comment by anderskev** [comment]
Well that's good news. Thanks guys.

**Comment by grabbou** [comment]
Yup, I am going to close it as it's also a part of `0.54.0-rc.0` now. I am waiting for a one more PR for UWP as well and getting it out there.

**Comment by MrsBookik** [comment]
Is there any way to patch the podspec locally for being able to work with 0.53?

**Comment by grabbou** [comment]
Not really sure, 0.53 will be out shortly (today or tomorrow).

**Comment by pritasam** [comment]
hey any solution to this

**Comment by Salinn** [comment]
As I commented on https://github.com/facebook/react-native/issues/17920, I am also still having an issue with this as well. On the latest version

**Comment by NicWickman** [comment]
I am having this issue in 0.57, does anybody have any more information? I have checked that my pod spec file is updated as noted above, so I'm not sure where this error is coming from.
