### ISSUE TITLE
Debug JS Remotely crashes

### ISSUE THREAD

**Issue by Graham42** [facebook/react-native#17941]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Partly

### Environment

Environment:
  OS: Linux 4.4
  Node: 8.9.4
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.0 => 0.52.0

### Steps to Reproduce

1. Create a project following the [Getting Started guide](https://facebook.github.io/react-native/docs/getting-started.html) (Quick start tab)
2. Switch to the _Building Projects with Native Code_ tab of [the guide](https://facebook.github.io/react-native/docs/getting-started.html), and follow the steps there to create an Android Virtual Device 
3. Start the Android Virtual Device
4. Run `npm run android` in the fresh project
5. Once the app has loaded in the Android emulator, press <kbd>Ctrl+M</kbd> to bring up the dev tools menu
6. Select "Debug JS Remotely"
7. In the Chrome browser that opens, open the web console <kbd>Ctrl+Shift+I</kbd>
8. Enable _Pause on exceptions_
9. Reload the Chrome page
10. Error will occur here

### Expected Behavior

The debugger to not crash

### Actual Behavior

The debugger crashed. 

Stacktrace: 
```
(index):94 Uncaught TypeError: Cannot set property 'volume' of null
    at Object.render ((index):94)
    at Object.setState ((index):48)
    at WebSocket.ws.onopen ((index):152)
```

![image](https://user-images.githubusercontent.com/2476733/36080845-b34fb83c-0f64-11e8-9763-059e38da216a.png)

### Reproducible Demo

No project code changes are need to reproduce this. Just run 
```sh
npx create-react-native-app TestProject
```

Note: `npx` is available if you have the at least `npm@5.2.0` installed

**Comment by KunwarSingh** [comment]
any updates on this issue, I'm facing this as well

**Comment by Meligy** [comment]
I'm having the same issue with react-native react-native@0.53.0 

Can we please reopen this issue?

**Comment by megelismi** [comment]
I'm also facing this issue with react-native react-native@0.53.0

**Comment by KunwarSingh** [comment]
Its working now on 0.53.0
Just turn off all your google chrome extensions and restart it. Then debug-mode works like charm.

**Comment by afilp** [comment]
I am also having the issue in 0.53.0. Sometimes it works sometimes not. Disabling all extensions should not be the solution (not even tried this), because we will not be able to work on chrome with many other websites during development.

**Comment by Pastromhaug** [comment]
I'm having the same issue on 0.53.0

**Comment by afilp** [comment]
Can this issue be reopened please? Why do bots close it?

It is obvious that when using Android Studio to "Debug app" then we get the `Uncaught TypeError: Cannot set property 'volume' of null` problem.

**Comment by jaredgalanis** [comment]
For me adding `export default` to this line:
```
export default class App extends Component {
```
In `App.js` is what got rid the issue.

**Comment by afilp** [comment]
Thanks but I already have this `export default` in class.

**Comment by Lxxyx** [comment]
Same issue in 0.54

**Comment by dhrubesh** [comment]
![image](https://user-images.githubusercontent.com/11453045/37539480-d4d3b858-2979-11e8-973b-796209bc85cc.png)
![image](https://user-images.githubusercontent.com/11453045/37539496-e25f6936-2979-11e8-987d-52e6f534c360.png)
![image](https://user-images.githubusercontent.com/11453045/37539522-f06f9ab4-2979-11e8-998a-522ac9992672.png)

Can anyone help me on this?

**Comment by nikitabuyevich** [comment]
Here is a temporary fix for everyone:

Download the [Allow-Control-Allow-Origin](https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi?hl=en) Chrome extension.

Set it up so you only allow the localhost and the fetched packager from Expo:
![alt text](https://i.imgur.com/sEYTIjB.png "Enter intercepted URLs")

And here is how you get the fetched URL from Expo:
![alt text](https://i.imgur.com/cLHIRtV.png "Enter intercepted URLs")

![alt text](https://i.imgur.com/FNA1eFE.png "Enter intercepted URLs")

Lastly, you have to manually reload the chrome browser and the app with every change.

Hopefully this is fixed soon.

**Comment by ldco2016** [comment]
I am also getting this issue in the http://localhost:8081/debugger-ui/.

Turning react extension off and on did not work.

Please help.

**Comment by speculees** [comment]
Any updates on this?
`{}`

**Comment by speculees** [comment]
...  "private": true,
  "devDependencies": {
    "babel-preset-react-native-stage-0": "^1.0.1",
    "jest": "^23.1.0",
    "jest-react-native": "^18.0.0",
    "react-test-renderer": "16.3.1"
  },
  "scripts": {
    "start": "react-native start",
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "test": "jest"
  },
  "jest": {
    "preset": "react-native"
  },
  "dependencies": {
    "react": "16.3.1",
    "react-native": "~0.55.2",
    "react-native-maps": "^0.21.0"
  }...

**Comment by Graham42** [comment]
React native folks generally don't check old issues, @speculees ,recommend you open a new issue with the latest version

**Comment by iwenchao** [comment]
昨天我也遇到了这个问题,enable debug remotely  crash. 不过我发现chrome 出现cached bundle. 所以清除了缓存.然后重新进入就好了 . 花了4个小时,有点心痛
