### ISSUE TITLE
Intl.DateTimeFormat.resolvedOptions.timeZone doesn't change when iOS device timezone changes

### ISSUE THREAD

**Issue by jonahkagan** [facebook/react-native#17958]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

```
Environment:
  OS: macOS High Sierra 10.13.2
  Node: 8.9.1
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: Not Found

Packages: (wanted => installed)
  react: ^16.0.0-beta.5 => 16.0.0-beta.5
  react-native: ^0.53.0 => 0.53.0

Target Platform: iOS
```

### Steps to Reproduce

1. Create a React Native app that displays the result of evaluating this expression: `new Intl.DateTimeFormat().resolvedOptions().timeZone`.
2. Build the app with Xcode and export it to an iOS device. I'm using an iPhone 5s running the latest version of iOS.
3. Open the app. I see `America/Los_Angeles` - you should see your local timezone name.
4. Switch to the device Settings app and change the timezone to a different timezone, let's say New York.
5. Switch back to your app and trigger a rerender.

### Expected Behavior

I expect to see the new timezone name, `America/New_York`

### Actual Behavior

I still see `America/Los_Angeles`.

### Reproducible Demo

https://snack.expo.io/HkWYUYyDG

To reproduce:
1. Open the app, note the initial timezone.
2. Go to Settings, change the timezone.
3. Switch back to the app. Click "Rerender" in the app.
4. Note that the timezone offset changed, but not the timezone name.

Let me know if I can give you any more useful info. If you point me to somewhere in the codebase that might be causing this issue, I'd be happy to do the work to submit a PR. I just don't know where to look and don't have time to learn the codebase.

**Comment by jonahkagan** [comment]
This is still an issue. I had to work around it by writing a native module that I can poll for the correct timezone.

**Comment by christophermark** [comment]
We had similar issues on an Android phone and resolved it by using https://github.com/rebeccahughes/react-native-device-info for getting an updated timezone natively from a non-JS source.
