### ISSUE TITLE
open two projects in xcode :[error] unable to resolve module

### ISSUE THREAD

**Issue by MAYDAY1993** [facebook/react-native#17950]
I've two projects and want to open them in xcode in the same time

since I've opened project  A,I opened a new window to run Project B, both projects are separated from each other, but get error:

![jietu](https://user-images.githubusercontent.com/14831051/36088896-1611a9c6-1014-11e8-907d-7d1f8c6fd509.jpg)

**audioDemo** file is in project A , not used in B ,so I'm wondering why

in Project A ,I write the code like this:

```js

import AudioDemo from './AudioDemo';
```

**Comment by tracinah** [comment]
Yep I tried....the last fully spelled word on the page said Fatal....I left
it alone
