### ISSUE TITLE
Text Input issue ios

### ISSUE THREAD

**Issue by DevillBuster** [facebook/react-native#17951]
Hi,
I am here to report an issues that i am facing when i try to write hastily in text input , text cursor lags behind and text move forward which causes distortion of text. I am using text input in React native modal and using multi line prop true. Here below is the code and gif to illustrate the issue...

Redux form Field

       <Field
          placeholder={'Write a Review'}
          name='review'
          component={Input}
          keyboardType='default'
          multiline
          numberOfLines={5}
          autoCapitalize={'sentences'}
          inputContainerStyle={{ height: 120, justifyContent: 'flex-start', position: 'relative' }}
          inputStyle1={{ flex: 1, position: 'absolute', top: 10, left: 10, right: 10 }}
          multiline={true}
        />

Input Component

const Input = (props) => {
  const { input, label, placeholder, autoCapitalize, multiline, meta, secureTextEntry, keyboardType, maxLength, returnKeyType, onSubmitEditing, autoFocus, blurOnSubmit } = props;
  const { inputStyle, labelStyle, containerStyle, errorContainerStyle } = styles;

  return (
    <View style={containerStyle}>
      <Text style={labelStyle}>{label}</Text>
      <View style={errorContainerStyle}>{renderErrors(meta)}</View>
      <TextInput
        style={inputStyle}
        placeholder={placeholder}
        underlineColorAndroid='transparent'
        placeholderTextColor={'#dcdcdc'}
        keyboardType={keyboardType}
        multiline={multiline}
        maxLength={maxLength}
        autoCapitalize={autoCapitalize}
        onSubmitEditing={onSubmitEditing}
        returnKeyType={returnKeyType}
        autoFocus={autoFocus}
        blurOnSubmit={blurOnSubmit}
        {...input}
      />
    </View>
  );
};

![issue](https://user-images.githubusercontent.com/15182772/36095764-654a6ff4-1015-11e8-81a0-bea4e49d1232.gif)

**Comment by ahetawal-p** [comment]
I am seeing the same issue on `v055.4`. Did you find any fix for this @DevillBuster  ?
