### ISSUE TITLE
Nothing happens when using AsyncStorage at try-catch block at async function

### ISSUE THREAD

**Issue by kamenminkovcom** [facebook/react-native#17964]
###Is this a bug report?
-Yes.

I am observing the the following issue. Trying to set data at the AsyncStorage **nothing happens**.

`// @flow`
`import {AsyncStorage} from 'react-native';`
`import type {Dispatch} from '../../../types/Dispatch';`
`import type {AuthModel} from '../../../types/AuthModel';`
`import type {ThunkAction} from '../../../types/ThunkAction';`
`import {login as loginService} from '../../../services/auth';`
`import {dataFetching, dataFetchingDone} from '../../../actions/actions';`
`import {clearRedirect, setRedirect} from '../../../actions/redirectActions';`

`export const login = (formData: AuthModel): ThunkAction => async (dispatch: Dispatch): void => {`
   `try {`
        `dispatch(dataFetching());`
        `const data = await loginService(formData);`
        `debugger`
        `await AsyncStorage.setItem('user', JSON.stringify(data));`
        `debugger`
        `dispatch(dataFetchingDone());`
    `} catch (e) {`
`        debugger`
`       console.log(e);`
`      }`
`};`

I literally mean that nothing happens after `await AsyncStorage.setItem('user', JSON.stringify(data));`, it doesn't go on the next line, it doesn't enter at the catch block.

###Environment:
  OS: Windows 10
  Node: 8.9.4
  Yarn: Not Found
  npm: 4.6.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.0.0.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.50.3 => 0.50.3

### Expected Behavior
To set the item into the storage and to go on the next line or to throw an error.

### Actual Behavior
Nothing happens after AsyncStorage is called

**Comment by lanlin** [comment]
RN: 0.54.2 same problem.
only rerun run-android can make it work.
but when reload again, it happened again.
https://github.com/facebook/react-native/issues/12830
