### ISSUE TITLE
Hot reloading breaks on iOS and Android with circular dependencies

### ISSUE THREAD

**Issue by dannycochran** [facebook/react-native#17969]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 6.10.3
  Yarn: Not Found
  npm: 3.10.10
  Watchman: Not Found
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.0 => 0.53.0

### Steps to Reproduce

Creating a simple circular dependency chain will cause hot reloading to no longer work, and eventually the app will crash with "Maximum call stack size exceeded." This happens on both iOS and Android.

### Expected Behavior

1. Hot reloading reloads the UI in place and can resolve any issues with circular dependencies.
2. The app does not crash.

### Actual Behavior

1. Hot reloading doesn't work.
2. For Android, the app will crash with a red screen:

<img width="402" alt="screen shot 2018-02-13 at 10 23 11 am" src="https://user-images.githubusercontent.com/1217178/36167107-91a65e70-10a9-11e8-8b29-ac6a86663920.png">

For iOS, the app will exit without a red screen:

https://drive.google.com/open?id=1BWmmp2yPqtL9zmx4yYQ-yRyrg7nioDhB

### Reproducible Demo

Repro steps (feel free to do react-native run-ios as well):

```sh
git clone https://github.com/dannycochran/react-native-hot-reloading
cd react-native-hot-reloading
react-native run-android
```

1. Enable hot reloading.
2. Change the text in either "Dependency0.js" or "Dependency1.js", the app should show the "Hot Reloading..." badge, but nothing will change.
3. On iOS, the app will exit without a red screen. On android, the app should show a red screen with the warning "Maximum call stack exceeded" after a few seconds.

If the app is not crashing, check out the branch with more circular dependencies and repeat the steps above. It almost always crashes for me with the use case on master (which I tried to make as simple as possible), but this branch is a little more complex in terms of the dependency tree, but always fails:

```sh
git fetch
git checkout moreCircularDependencies
```

### Similar bugs:

https://github.com/facebook/react-native/issues/16613
https://github.com/facebook/react-native/issues/7288

**Comment by dannycochran** [comment]
This is fixed on RN master since updating to metro 0.26.0:

https://github.com/facebook/react-native/commit/b1d8af48ae251f57bdcd55f89d8fc62aa9eca872

Hopefully it can get patched into 0.54

**Comment by K-Leon** [comment]
@grabbou Can you check if this commit can be cherry picked in 0.54?

**Comment by grabbou** [comment]
Yup, see no reason not to update the dependency.

**Comment by dannycochran** [comment]
@grabbou will this end up making it into 0.54?

**Comment by grabbou** [comment]
Yup, we've bumped Metro already in latest RC. I think it can be closed in that case.

**Comment by bjornegil** [comment]
In general, circular dependencies should be avoided. Checkout [madge](https://github.com/pahen/madge) for dependency analysis, also pointing out circular dependencies.
