### ISSUE TITLE
Text cut-off on iPhone X

### ISSUE THREAD

**Issue by nicemanis** [facebook/react-native#17960]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

  Environment:
    OS: macOS High Sierra 10.13.3
    Node: 8.5.0
    Yarn: Not Found
    npm: 5.6.0
    Watchman: 4.9.0
    Xcode: Xcode 9.2 Build version 9C40b
    Android Studio: 3.0 AI-171.4443003

  Packages: (wanted => installed)
    react: 16.0.0 => 16.0.0
    react-native: 0.51.0 => 0.51.0

  Target Platform: iOS (10.3)

### Steps to Reproduce

1. Create new react native project
2. Add these lines to the `App.js`:
```
import {
  ...
  Dimension
} from 'react-native';
...
const SCREEN_WIDTH = Dimensions.get('window').width;
...
export default class App extends Component<Props> {
  render() {
    return(
      ...
      <Text style={{
        paddingLeft: SCREEN_WIDTH / 20,
        fontSize: SCREEN_WIDTH / 25,
      }}>
        Change PIN
      </Text>
    );
  }
}
```
3. Run the project on iPhone X

### Expected Behavior

![image](https://user-images.githubusercontent.com/9463816/36143225-28b2e03c-10b3-11e8-9985-85c7f525e8d9.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/9463816/36143233-335862c8-10b3-11e8-8341-58da9ee306bc.png)

### Reproducible Demo

```
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  Platform,
  StyleSheet,
  TouchableHighlight,
  Text,
  View,
  Dimensions
} from 'react-native';


const SCREEN_WIDTH = Dimensions.get('window').width;
const instructions = Platform.select({
  ios: 'Press Cmd+R to reload,\n' +
    'Cmd+D or shake for dev menu',
  android: 'Double tap R on your keyboard to reload,\n' +
    'Shake or press menu button for dev menu',
});

type Props = {};
export default class App extends Component<Props> {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          {instructions}
        </Text>
        <Text style={{
          paddingLeft: SCREEN_WIDTH / 20, // if this is changed to SCREEN_WIDTH / 21 everything works
          fontSize: SCREEN_WIDTH / 25,
        }}>
          Change PIN
        </Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

```

**Comment by bohdanbirdie** [comment]
Adding `paddingRight: SCREEN_WIDTH / 20` for text will fix the problem, and will center it as well.

I played a bit with it, and my guess is that your text happened to be in size range that is not wrapping and does not show as well, so probably this might be considered as an issue.

**Comment by nicemanis** [comment]
I know how to fix the problem - just add the `paddingLeft` to the container view instead of the Text element. The question is not how to fix this, but why doesn't it render certain words with certain `paddingLeft` and `fontSize` combinations.

As I commented in the sample code, if you set `paddingLeft: SCREEN_WIDTH / 21` then the all of the text renders as expected. I have also tested a scenario where e.g. word "Policy" would render normally, word "Poolicy" would not bet rendered and word "Pooolicy" would again render normally.

**Comment by bohdanbirdie** [comment]
@nicemanis yea, seems like there is some range in which text is wrapping, but it doesn't affect geometry of element

**Comment by paour** [comment]
This happens to me on v0.53.4.

![simulator screen shot - iphone 6 - 2018-09-12 at 10 52 27](https://user-images.githubusercontent.com/90963/45413711-12a70080-b67a-11e8-804b-ffe9879aac6b.png)
![simulator screen shot - iphone x - 2018-09-12 at 10 52 35](https://user-images.githubusercontent.com/90963/45413712-12a70080-b67a-11e8-993d-2695bc25279f.png)

**Comment by rpavlovs** [comment]
Same for iPhone X Max
RN: 0.55.4

![image](https://user-images.githubusercontent.com/634881/46900533-79296500-ce58-11e8-81c4-e817cd017582.png)

**Comment by rpavlovs** [comment]
The cut-off line seems to move further throughout the app use:
https://streamable.com/59hx4

**Comment by jacklj** [comment]
Having the same problem on v55.3
