### ISSUE TITLE
The --device option fails on command line in v53.0

### ISSUE THREAD

**Issue by Gulci** [facebook/react-native#17973]
### Is this a bug report?
Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.9.1
  Yarn: Not Found
  npm: 5.5.1
  Watchman: Not Found
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.0 => 0.53.0

### Steps to Reproduce

1. Initiate a new React Native project using `react-native init projectName`
2. Run the command `react-native run-ios --device deviceName`

### Expected Behavior

The app should have launched on my physical device. Additionally, if I already have an instance of Metro Bundler running using `react-native start`, it should just hook into that one and use that.

### Actual Behavior

Metro Bundler opens and complains that `Metro Bundler can't listen on port undefined`. It then prompts the user to hit enter because the process has terminated. I've run into other random errors too. I've included one of those here as well.

[Metro Bundler error 1](https://i.imgur.com/SuPoZ8H.png)
[Metro Bundler error 2](https://i.imgur.com/3JTbYbb.png)

Additionally, there is a lot of output in my main terminal about the Xcode build failing. I can include the full output in a comment below if requested.

[Build error 1](https://i.imgur.com/SIWdahw.png)
[Build error 2](https://i.imgur.com/znhf8PW.png)

Even if I try running an instance of Metro Bundler using `react-native start` before running `react-native run-ios --device deviceName`, it just starts a new instance in a new terminal window.

### Reproducible Demo

You can reproduce this with a brand new project created using `react-native init projectName`.

However, (here)[https://github.com/Gulci/LegitCheckApp] is the project I'm currently working on because I don't feel like creating a brand new example for this easily reproducible issue and I don't want this issue to be closed like the last one mentioning this problem was.

**Comment by nuke99** [comment]
I have the same issue

**Comment by johanleroch** [comment]
Same issue too

**Comment by Gulci** [comment]
This has already been fixed for me. Update to the latest react-native.

**Comment by mlazari** [comment]
@Gulci Which version fixed the error? I have the same error with "react-native": "0.54.0". Running from Xcode works fine. The error appears only when I'm trying to run from the terminal with `react-native run-ios --device="Mihai"`

**Comment by Gulci** [comment]
@mlazari

Lol wow. Want me to open a new issue? Yeah I was on 0.53.3.

**Comment by johanleroch** [comment]
@Gulci 

Haha if you want yes :) 
I have the same problem on the 0.54.0

**Comment by Gulci** [comment]
I'll open the exact same issue. ;)

**Comment by tintorres** [comment]
I have the same issue v0.55.0-rc . I'm on
macOS High Sierra 10.13.3
yarn 1.3.2

Problem does not exists on v0.52
So I'm guessing this issue introduced in v0.53

**Comment by grabbou** [comment]
@tintorres the fix for this issue is on `0.55-stable` branch so technically, there should be no errors on latest RC. Please double check.

To everyone else in this thread, this has been fixed in `0.55.0-rc.0` and will soon be available in the stable channel.
