### ISSUE TITLE
Gradle error while creating android build with react-native

### ISSUE THREAD

**Issue by chiragebiztrait4** [facebook/react-native#17980]
### Is this a bug report?
**Yes**

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?
**Yes**

### Environment
Environment:
  OS: Linux 4.4
  Node: 8.9.4
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.0 => 0.53.0

### Steps to Reproduce
(Write your steps here)

1. react-native init <Project Name>
2.react-native run-android
and error of gradle comes
`A problem occurred configuring root project 'Hello'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:3.0.1.
     Required by:
         project :
      > Could not resolve com.android.tools.build:gradle:3.0.1.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.0.1/gradle-3.0.1.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.0.1/gradle-3.0.1.pom'.
               > sun.security.validator.ValidatorException: No trusted certificate found

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
`
### Expected Behavior

App will run on emulator
(Write what you thought would happen.)

### Actual Behavior

Same as ### Steps to Reproduce

(Write what happened. Add screenshots!)
[https://ibb.co/kJcvFn](error image)
Gradle error

### Links
https://stackoverflow.com/questions/48782303/gradle-error-in-android-build-react-native?noredirect=1#comment84567024_48782303

**Comment by hramos** [comment]
This is being fixed on master.
