### ISSUE TITLE
Shadow was working on 0.51.0 , doesn't work on 0.53.0

### ISSUE THREAD

**Issue by ataomega** [facebook/react-native#17984]
### Is this a bug report?

Maybe not

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Steps to Reproduce

(Write your steps here:)

A view with styles below, was working fine on 0.51.0 , but doesnt work on 0.53.0
```
circle: {
      width: size,
      height: size,
      borderRadius: size / 2,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: size / 20,
      elevation: 5,
      padding: padding,
    }
```

I've read the documentations, nothing have been changed for shadows

### Expected Behavior

To show the shadow

(Write what you thought would happen.)

### Actual Behavior

View doesnt have shadow
![simulator screen shot - iphone x - 2018-02-14 at 17 44 28](https://user-images.githubusercontent.com/16841537/36216341-ccdedf0c-11ae-11e8-926a-a816a0062492.png)
![simulator screen shot - iphone x - 2018-02-14 at 17 50 55](https://user-images.githubusercontent.com/16841537/36216637-9dd98102-11af-11e8-8a26-db1f9fb83a0c.png)

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by Knjaz89** [comment]
0.52.2 working

**Comment by ataomega** [comment]
Setting backgroundColor fixes the issue

**Comment by SupriyaKalghatgi** [comment]
@ataomega I have `backgroundColor` set, still doesn't work for me
No elevation
