### ISSUE TITLE
Native component for "MyRCTViewManager" does not exist

### ISSUE THREAD

**Issue by jeromjoy** [facebook/react-native#1798]
Hi I have a issue. If someone have faced similar issue kindly reply. 
I created a UIView MyTextLabel.h, MyTextLabel.m also attached a xib file MyTextLabel.xib. It just contains two labels.
Next i created RCTTextLabelManager.m which returns MyTextLabel at

```
 @implementation RCTTextLabelManager
RCT_EXPORT_MODULE()

-(UIView *) view
{MyTextLabel * theView;
    theView = [[MyTextLabel alloc] init];
    return theView;
}
@end
```

The issue is that when i run the app, in console debug it says "Native component for "RCTTextLabelManager" does not exist". By debuting i notice that it is coming from RCTUIManager.

**Comment by jaygarcia** [comment]
Stupid question: Is RCTTextLabelManager.m file being compiled and linked?

**Comment by jeromjoy** [comment]
Yes it is compiled

**Comment by brentvatne** [comment]
What does your header file for the manager look like?

```
#import "RCTViewManager.h"

// You should avoid using the RCT prefix, that's meant for core modules
@interface JJTextLabelManager : RCTViewManager

@end
```

Hope that helps, if not I would re-post this to StackOverflow - the issues are meant for bugs :smile: And if you don't have any luck with the above or StackOverflow, then feel free to ping me on this issue again.
