### ISSUE TITLE
react-test-renderer's createNodeMock does not work as expected

### ISSUE THREAD

**Issue by khirakawa** [facebook/react-native#17987]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

```
Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.6.0
  Yarn: 1.1.0
  npm: 5.3.0
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: ^0.53.0 => 0.53.0
```

### Steps to Reproduce

1. `react-native init NodeMockTest`
2. `cd NodeMockTest`
3. Open `__tests__/App.js` and replace with this code:

    ```
    import 'react-native';
    import React, { Component } from 'react';
    import { View } from 'react-native';

    // Note: test renderer must be required after react-native.
    import renderer from 'react-test-renderer';

    class Test extends Component {
      componentDidMount() {
        this._root.test();
      }

      render() {
        return (
          <View ref={component => (this._root = component)} />
        );
      }
    }

    it('renders correctly', () => {
      const tree = renderer.create(
        <Test />,
        {
          createNodeMock: element => {
            return {
              test: () => { console.log('it works'); }
            };
          }
        }
      );
    });
    ```

4. Run `npm test`

### Expected Behavior

I expect the test to not throw an error

### Actual Behavior

Test fails with:

```
TypeError: this._root.test is not a function
```

Screenshot:
![screen shot 2018-02-15 at 3 32 48 pm](https://user-images.githubusercontent.com/613822/36243603-ac136736-1265-11e8-8b9c-d27ec3894a7b.png)

### Reproducible Demo

Please see steps above for code.

I was not able to reproduce this issue with Expo.  Please see https://snack.expo.io/SkpvqjfwM.

**Comment by hramos** [comment]
I'm not very familiar with this - is it supposed to work? Do you have a reference if so?

**Comment by khirakawa** [comment]
@hramos I learned about `createNodeMock` here https://reactjs.org/blog/2016/11/16/react-v15.4.0.html#mocking-refs-for-snapshot-testing

**Comment by daviddelusenet** [comment]
This worked for me:

```
test('Compare snapshots', () => {
  const component = renderer.create(<ErrorMessage {...errorMessageData} />, {
    createNodeMock: () => ({}),
  });

  const tree = component.toJSON();
  expect(tree).toMatchSnapshot();
});
```
