### ISSUE TITLE
Cannot connect to VS Android Emulator - DeviceException: No connected devices

### ISSUE THREAD

**Issue by jurosh** [facebook/react-native#17982]
### Is this a bug report?

Possibly.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

y.

### Environment

Windows 10 with HyperV enabled.
Visual Studio Android Emulator.
"react-native": "0.53.0"
Android Studio 3.0.1

### Steps to Reproduce

1. Start Visual Studio Android Emulator - work's fine, device is functional
2. Run just to see adb console can see machine:
```
./adb devices
List of devices attached
169.254.138.177:5555    device
```
3. Run in react native project:
```
react-native run-android
// ...
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:installDebug'.
> com.android.builder.testing.api.DeviceException: No connected devices
```

### Expected Behavior

React native should connect to running machine in Visual Studio Code Emulator.

## PS

I cannot use default Android emulator because of incompatibility with HyperV which is required to run on my system because of other virtual machines and Docker.

**Comment by Lechus** [comment]
Windows 10 with HyperV disabled.
Working Android Emulator.
"react-native": "0.54.0"
Android Studio 3.0.1

Same issue
