### ISSUE TITLE
[Navigator] leftButtonTitle can't work with leftButtonIcon

### ISSUE THREAD

**Issue by lazywei** [facebook/react-native#1799]
When using navigator push, if I set both leftButtonTitle and leftButtonIcon at the same tile, only one of them will show on the navigation bar. I expect both of them should display on the bar. Or did I miss anything?

For example,

```javascript
    this.props.navigator.push({
      component: Chat,
      title: user.name,
      leftButtonIcon: require('image!back'),
      leftButtonTitle: backBtnTitle,
      onLeftButtonPress: () => {
        this.props.navigator.popToTop();
        this.getInChat = false;
      },
      passProps: {
        receiver: user
      }
    });
```

Thanks.

**Comment by christopherdro** [comment]
Looking through the docs it looks like you have a few options...
```
backButtonIcon: Image.propTypes.source, 
backButtonTitle: string,
leftButtonIcon: Image.propTypes.source,
leftButtonTitle: string
```
Since your using `onLeftButtonPress` try replacing `backButtonIcon ` with `leftButtonIcon` and see if that does the trick.

**Comment by lazywei** [comment]
@christopherdro hi, sorry that was a typo. in fact, i'm using `leftButtonIcon` indeed, but it still doesn't work

**Comment by iSimar** [comment]
````
````

**Comment by liu-yuhuan** [comment]
i've got the same problem ... 
i'm using leftButtonIcon and leftButtonTitle
but leftButtonTitle doesn't show
