### ISSUE TITLE
Artifacts on View with borderRadius on only 2 corners on iOS

### ISSUE THREAD

**Issue by SupriyaKalghatgi** [facebook/react-native#17998]
### Is this a bug report?

This is a bug

### Environment

OS:  macOS Sierra 10.12.6
    Node:  7.6.0
    Yarn:  1.3.2
    npm:  4.1.2
    Watchman:  4.7.0
    Xcode:  Xcode 9.2 Build version 9C40b
    Android Studio:  Not Found

  Packages: (wanted => installed)
    react: 16.0.0 => 16.0.0
    react-native: 0.53.0 => 0.53.0

### Steps to Reproduce

```
<View>
  <View
    style={{
      margin: 20,
      width: 100,
      height: 50,
      borderWidth: 1,
      borderColor: "blue",
      borderTopLeftRadius: 5,
      borderBottomLeftRadius: 5
    }}
  />
</View>
```
Run this on iOS device

### Expected Behavior

![image](https://user-images.githubusercontent.com/13464885/36296219-43283c12-1312-11e8-891d-a24dd615556a.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/13464885/36296233-503676da-1312-11e8-8872-62f629835ad5.png)

### Reproducible Demo

It was said in 11987 thats this was fixed, though it still continues [#11897](https://github.com/facebook/react-native/issues/11897#issuecomment-352614174)

**Comment by Nyadesune** [comment]
this is still happening, anyone got a workaround?

**Comment by SupriyaKalghatgi** [comment]
https://github.com/facebook/react-native/pull/19451 fixes the issue, but no status on merging this
