### ISSUE TITLE
[Tests][Flow] Use flow-bin so new releases to Flow don't break RN tests

### ISSUE THREAD

**Issue by ide** [facebook/react-native#1800]
Whoever is on-call probably wants to take a look at this --

Flow 0.13.1 was published recently and when the tests run `brew reinstall flow` they get the latest version. The tests fail fast if they aren't on Flow 0.12 so the tests are complaining about a Flow version mismatch.

AFAIK brew doesn't have an easy way to install an old version of a package so the recommended way is to upload a versioned formula to https://github.com/Homebrew/homebrew-versions and run:
```
brew install homebrew/versions/flow-0.12.0
```

(btw the formula naming scheme seems pretty shortsighted... following the pattern there, lib v1.1 would be named lib11.rb but so would lib v11! So probably best to keep the dots in the version string and call the formula something like flow-0.12.0.rb)

**Comment by ide** [comment]
One thing that's kind of burdensome for the Flow team is that each new Flow release would need to publish a versioned formula to homebrew-versions. Maybe if the release process is scriptable it won't be an issue.

cc @jeffmo @gabelevi, you guys were the most recent publishers of flow.rb

**Comment by jeffmo** [comment]
I think @gabelevi has discussed this before (and so there must have been a reason it wasn't decided on) -- but `flow-bin` seems like a good option since it's an npm package that's semver and will point at the "right" version of flow no matter what the latest version in brew is...

@gabelevi care to chime in? I'm sure there's context I'm not aware of here.

**Comment by brentvatne** [comment]
ping @gabelevi

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/testsflow-use-flow-bin-so-new-releases-to-flow-dont-break-rn-tests
