### ISSUE TITLE
iOS status bar disappears in landscape orientation

### ISSUE THREAD

**Issue by nathan815** [facebook/react-native#18005]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes.

### Environment

  OS: macOS High Sierra 10.13.3
  Node: 9.5.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 2.2 AI-145.3537739

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.0 => 0.53.0

  Target Platform: iOS (11)

### Steps to Reproduce

(Write your steps here:)

1. Open a React Native app that allows landscape orientation, and has a visible status bar
2. Turn device/simulator to landscape orientation

### Expected Behavior

The status bar should remain visible.

### Actual Behavior

The status bar disappears.

### Reproducible Demo

- `react-native init AppName`

- https://github.com/nathan815/RN-Todo

I've also noticed this issue in other React Native apps, such as [Git Point](https://github.com/gitpoint/git-point).

I realize there was a previous issue (#10751) regarding this, but it seems to have been closed before it was fixed.

**Comment by Zycon42** [comment]
This is default iOS behavior. It hides status bar in "vertically compact environment" (all iPhones in landscape). You can override it, see https://developer.apple.com/documentation/uikit/uiviewcontroller/1621440-prefersstatusbarhidden

**Comment by nathan815** [comment]
@Zycon42 Oh, interesting. Good to know. Do you know if it is possible to override this in React Native?
