### ISSUE TITLE
RN 0.54.0 RC 3 can't be installed with npm

### ISSUE THREAD

**Issue by vovkasm** [facebook/react-native#18010]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

```
react-native info
Command `info` unrecognized. Make sure that you have run `npm install` and that you are inside a react-native project.
```
Custom filled environment:
  Environment:
    OS:  macOS Sierra 10.12.6 (16G1212)
    Node:  9.5.0
    Yarn:  -
    npm:  5.6.0
    Watchman:  4.9.0
    Xcode:  Xcode 9.2 Build version 9C40b

### Steps to Reproduce

1. Add `"react-native": "0.54.0-rc.3"` as dependency to `package.json`
2. `npm install`

### Expected Behavior

Have `react-native` package inside `node_modules` folder.

### Actual Behavior

```
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "npm:": npm:babylon@^7.0.0-beta
```

### Cause

Actually this is result of incorrect dependency format in `metro` npm package: https://github.com/facebook/metro/issues/142

As it is critical bug for RN, I created this issue to be sure that release of 0.54.0 will not happen until metro deps will be fixed.

**Comment by iorikingdom** [comment]
+1

**Comment by koloff** [comment]
+1

**Comment by rexchen** [comment]
+1

**Comment by suuzee** [comment]
You can try use `yarn`.

**Comment by vovkasm** [comment]
@suuzee Yes, you are right ))) I can use yarn... Also I can fork & fix broken modules same way as I use patched RN... But I hope that it will not be needed. Using yarn is not an option for me.

**Comment by hramos** [comment]
Thanks for the report. We're following up on this soon.

**Comment by vovkasm** [comment]
Just to track it here: fix landed in metro master: https://github.com/facebook/metro/pull/143

**Comment by vovkasm** [comment]
Thanks! Now `react-native@0.54.0-rc.4` can be successfully installed with npm, so close!
