### ISSUE TITLE
Invalid drawable tag vector

### ISSUE THREAD

**Issue by sm2017** [facebook/react-native#18011]
### Is this a bug report
May be

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

OS: Windows 10

Node: 8.1.3

Yarn: 0.27.5

npm: 5.0.3

Watchman: Not Found

Xcode: N/A

Android Studio: Version 2.3.0.0 AI-162.4069837

Packages: (wanted => installed)

react: 16.2.0 => 16.2.0

react-native: 0.53.0 => 0.53.0

### Steps to Reproduce

After upgrading react native , sometimes when I open app the error shown , I don't know how and why it happens

### Actual Behavior

![image](https://user-images.githubusercontent.com/19644997/36354267-0b947122-14e7-11e8-9c0d-f049af343fe7.png)

Randomly when I open app I see the error , But never see error when app is open

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by sm2017** [comment]
What is this error exactly?

**Comment by sm2017** [comment]
@facebook any idea?

**Comment by kelset** [comment]
As the error says, it seems that some resource on the Android side (the `abc_vector_test.xml` file) is not being imported properly.

**Comment by sm2017** [comment]
@kelset The question it , what is `abc_vector_test.xml` and why it cannot be imported? Why after upgrading react native to 0.53.0 , just sometime when I open app it happens?

**Comment by sm2017** [comment]
@kelset you add ` Incomplete Reproduction Steps 📝 ` label , I really don't know what is it , I just know when I upgrade react native I have the issue , I never ever have `abc_vector_test.xml` in my android side and I don't think the issue if from my dependencies because I just upgrade react native

**Comment by Jhonsem** [comment]
What is this error exactly?

**Comment by ozmaat** [comment]
I got the same error. 

"file res/drawable/abc_vector_test.xml from drawable resource id".

In my case,  one of the external modules - "react-native-share" has this file. 

The view that reference to this module raise this error from time to time while loading the view.  Any method of the module not used yet.

The error occurs on android version - 4.4.2

React native version - 0.55.3

[https://github.com/facebook/react-native/issues/19455](url)

**Comment by sm2017** [comment]
@ozmaat Can you tell me where is `abc_vector_test.xml` in react-native-share?
![image](https://user-images.githubusercontent.com/19644997/41955033-89a989a0-79f3-11e8-967a-ed2ba95ba268.png)

**Comment by ozmaat** [comment]
@sm2017 - it is under `node_modules\react-native-share\android\build\intermediates\res\merged\release\drawable` directory.  

I have still not have been able to resolve this bug.
