### ISSUE TITLE
StatusBar BackgroundColor not working

### ISSUE THREAD

**Issue by salihkiraz** [facebook/react-native#18018]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

  Environment:
    OS:  Win 10
    Node:  8.9.2
    Yarn:  1.3.2

  Packages: (wanted => installed)
    react-native:  0.52.0  =>  0.52.0 
    react:  16.2.0 =>  16.2.0

  Target Platform: Android

### Steps to Reproduce

  `     
        <StatusBar 
        backgroundColor = "blue"
        />
        `

### Expected Behavior

StatusBar color must be blue

### Actual Behavior

![image](https://user-images.githubusercontent.com/7440402/36369525-93872fea-156c-11e8-97da-e80703841877.png)

### Reproducible Demo

https://snack.expo.io/BJtpkfOwG

**Comment by jpotterm** [comment]
If you're using Expo, try configuring it in `app.json` instead: https://docs.expo.io/versions/latest/guides/configuring-statusbar
