### ISSUE TITLE
git-upgrade fails if email is not set global for git

### ISSUE THREAD

**Issue by voxspox** [facebook/react-native#18020]
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

no

### Environment

Environment:
  OS: Linux 4.13
  Node: 9.5.0
  Yarn: Not Found
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.2.0 => 16.2.0
  react-native: ^0.53.2 => 0.53.2

### Steps to Reproduce

1. Do not setup your email for git globally
2. But do setup your git email for the local project
3. run react-native-git-upgrade

### Expected Behavior

no errors

### Actual Behavior

    $ git commit -m "Project snapshot"
    On branch master
    nothing to commit, working directory clean
    $ react-native-git-upgrade 
    git-upgrade info Check for updates 
    ...
    git-upgrade info Add all files to commit 
    git-upgrade info Commit current project sources 
    
    *** Please tell me who you are.
    Run
    git config --global user.email "you@example.com"
    git config --global user.name "Your Name"
    
    to set your account's default identity.
    Omit --global to set the identity only in this repository.
    
    fatal: unable to auto-detect email address (got 'locus@cobalt.(none)')
    git-upgrade ERR! An error occurred during upgrade: 
    git-upgrade ERR! Error: Command 'git commit -m "Project snapshot"' exited with code 128:
    stderr: undefined
    ...

If I setup my email per `git config --global user.email ...` there are no errors.

It seems that `git` runs within `react-native-git-upgrade` differently compared to in the shell.

**Comment by voxspox** [comment]
This is still an issue

**Comment by voxspox** [comment]
ok. I found out what is the problem:

`react-native-git-upgrade` creates a temporary git repository. Therefore the default email is used. If it is not set the described malicious behavior occurs.

**Comment by hramos** [comment]
The command line tools have their own repository and issue tracker over at https://github.com/react-native-community/react-native-cli.

**Comment by grabbou** [comment]
Reopening, since "react-native-git-upgrade" is still part of this repository.

**Comment by thymikee** [comment]
We're deprecating `react-native-git-upgrade` in favor of `react-native upgrade` using https://github.com/react-native-community/rn-diff-purge/ under the hood since RN 0.59.0. Please try that :)
