### ISSUE TITLE
Linker clash with GVRSDK (vlog_is_on.o)

### ISSUE THREAD

**Issue by shauntc** [facebook/react-native#18022]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 7.9.0
  Yarn: 0.23.2
  npm: 4.2.0
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.2.0 => 16.2.0
  react-native: ^0.53.0 => 0.53.0

### Steps to Reproduce

1) Initialize a react-native project with react-native init
2) Initialize cocoapods and add "pod 'GVRSDK'" to the pod file, run pod install
3) open workspace, run project in xcode or via react-native run-ios

### Expected Behavior

Run without linker error

### Actual Behavior

Fails to link with the following error:

```
duplicate symbol __ZN3fLI9FLAGS_novE in:
 /test_proj/ios/Pods/GVRSDK/Libraries/libGVRSDK.a(vlog_is_on_8d2e7d29c7bb2e5dfa3670dcea4320a0.o)
    /Library/Developer/Xcode/DerivedData/test_proj-btwdvvwnrjygbfeqvozqudjeesra/Build/Products/Debug-iphoneos/libReact.a(vlog_is_on.o)
duplicate symbol __ZN3fLI7FLAGS_vE in:
    /test_proj/ios/Pods/GVRSDK/Libraries/libGVRSDK.a(vlog_is_on_8d2e7d29c7bb2e5dfa3670dcea4320a0.o)
    /Library/Developer/Xcode/DerivedData/test_proj-btwdvvwnrjygbfeqvozqudjeesra/Build/Products/Debug-iphoneos/libReact.a(vlog_is_on.o)
ld: 2 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Reproducible Demo

https://github.com/shauntc/ReactNativeGVRSDKLinkerFailure
run 'pod install' in ios/ to install cocoapods

**Comment by Tankerxyz** [comment]
+1

**Comment by shauntc** [comment]
@Tankerxyz 

Our temporary fix for this is to remove it from the GVRSDK lib using this shell script:
```
#!/bin/bash

cd ./Pods/GVRSDK/Libraries/
lipo -info libGVRSDK.a

architectures="armv7 i386 x86_64 arm64"
for arch in $architectures
do
    echo Create thin archive libGVRSDK_$arch
    lipo -thin $arch libGVRSDK.a -output libGVRSDK_$arch
    chmod 777 libGVRSDK_$arch

    remove=""
    for object in $(ar -t libGVRSDK_$arch)
    do
        if [[ ${object} == vlog_is_on_* ]]
        then
            echo $object
            remove=$object
        fi
    done

    if [ $remove ]
    then
        echo removing $remove from $arch
        ar -dv libGVRSDK_$arch $remove
    else
        echo No symbol matching "vlog_is_on_*" found for $arch
    fi

done

echo Rebuild libGVRSDK.a
lipo -create libGVRSDK_armv7 libGVRSDK_i386 libGVRSDK_x86_64 libGVRSDK_arm64 -output libGVRSDK.a

for arch in $architectures
do
    rm libGVRSDK_$arch
    echo Delete thin archive libGVRSDK_$arch
done

cd ../../../
```

Adding this to the end of our podfile to run it after each time we run pod install:
```
# Hack to fix linker error between GVRSDK and React
post_install do |installer|
    system(". ./pod_post_install.sh")
end
```
(the script is saved in the same directory as the podfile as "pod_post_install.sh")

**Comment by Tankerxyz** [comment]
@shauntc thanks, it works for me.

**Comment by ttDemon** [comment]
I have followed the guide, but it generates this error when running.
<img width="864" alt="screen shot 2018-05-11 at 11 25 12 am" src="https://user-images.githubusercontent.com/26439136/39906689-5c891986-550e-11e8-8b79-5aa3ff63e5a8.png">

**Comment by shauntc** [comment]
@ttDemon Need some more context here:
What versions of react/gvrsdk are you running?
What symbols were clashing before?
What does your post install script look like?

**Comment by ttDemon** [comment]
---------------------
"react": "16.3.0-alpha.1",
"react-native": "0.54.3",
"GVRSDK": "1.140.0",
---------------------
symbols were clashing before: 

![screen shot 2018-05-10 at 10 37 05 am](https://user-images.githubusercontent.com/26439136/39959641-dc9d3d92-563e-11e8-9722-691d5a79e681.png)

---------------------
my post install script: 

#!/bin/bash

cd ./Pods/GVRSDK/Libraries/
lipo -info libGVRSDK.a

architectures="armv7 i386 x86_64 arm64"
for arch in $architectures
do
    echo Create thin archive libGVRSDK_$arch
    lipo -thin $arch libGVRSDK.a -output libGVRSDK_$arch
    chmod 777 libGVRSDK_$arch

    remove=""
    for object in $(ar -t libGVRSDK_$arch)
    do
        if [[ ${object} == vlog_is_on_* ]]
        then
            echo $object
            remove=$object
        fi
    done

    if [ $remove ]
    then
        echo removing $remove from $arch
        ar -dv libGVRSDK_$arch $remove
    else
        echo No symbol matching "vlog_is_on_*" found for $arch
    fi

done

echo Rebuild libGVRSDK.a
lipo -create libGVRSDK_armv7 libGVRSDK_i386 libGVRSDK_x86_64 libGVRSDK_arm64 -output libGVRSDK.a

for arch in $architectures
do
    rm libGVRSDK_$arch
    echo Delete thin archive libGVRSDK_$arch
done

cd ../../../

--------------------
If I do not add post install script then I run release mod ok, but debug will report duplicate error as above image

**Comment by crakaC** [comment]
This problem still occurs.

React-Native v0.55.4
Xcode 9.3.1
GVRSDK 1.140.0

**Comment by crakaC** [comment]
@react-native-bot ping

**Comment by fabianlee1211** [comment]
I am having the same issue as @ttDemon.
Any solution up until now?
I'm running 
RN 0.56.0
XCode 9.1
GVRSDK 1.140.0

**Comment by tranhiepqna** [comment]
I am getting the same  issue as @ttDemon  and @fabianlee1211. 
RN 0.56.0
XCode 9.2
GVRSDK 1.140.0
