### ISSUE TITLE
Let's encrypt CA websocket fails on Android api < 20 

### ISSUE THREAD

**Issue by perrosnk** [facebook/react-native#18032]
### Is this a bug report?

Yes

### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 9.3.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 2.1 AI-143.2915827

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: 0.49.3 => 0.49.3
  Target Platform: iOS (10.3)

### Steps to Reproduce

I have a node server which uses Let's Encrypt CA. I try to connect to it using websockets.
On iOS and newer Android versions (API  > 20) it connects successfully.
When running on older Android versions (both on simulator and actual devices) it never connects.
I have tried to connect using older Android version to a server that's not using Let's encrypt CA, and it also connects successfully.

The error I get when using this: 

```javascript
    ws.onerror = (e) => {
      // an error occurred
      console.log(e.message);
    };
```

is `Connection closed by peer`

and this:

```javascript
    ws.onclose = (e) => {
      // connection closed
      console.log(e.code, e.reason);
    };
```

logs `undefined, undefined`

### Expected Behavior

Connect to the server

### Actual Behavior
Fails

### Reproducible Demo

```javascript
    var ws = new WebSocket('wss://example.now.sh');

    ws.onerror = (e) => {
      // an error occurred
      console.log(e.message);
    };

    ws.onclose = (e) => {
      // connection closed
      console.log(e.code, e.reason);
    };
```

**Comment by perrosnk** [comment]
It seems it is indeed a problem with Okhttp.
Based on this [comment](https://github.com/square/okhttp/issues/3880#issuecomment-367895999) I need to set up a custom trust store that trusts LetsEncrypt like this [example](https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/okhttp3/recipes/CustomTrust.java). 

@tuncaulubilge Do you have an idea how can I achieve this in react native?

**Comment by tuncaulubilge** [comment]
There was a way to instantiate your own OkHttpClient and provide it to react-native, but OkHttpClientProvider has been broken for some time. Here is the issue: https://github.com/facebook/react-native/issues/13487

Another option is to fork the react-native repo and add your custom trust store to okhttp

**Comment by perrosnk** [comment]
@tuncaulubilge Thank you very much for your help!
I changed my files as mentioned in this [commit](https://github.com/facebook/react-native/commit/22efd95be1f0b236eeaaa8a8e6d01e89771c9543) and mentioned in this [comment](https://github.com/facebook/react-native/issues/13487#issuecomment-363288537)

As far as I understand I also need to change MainReactPackage in MainApplication.java and NetworkingModuleUtils.java as mentioned in this [comment](https://github.com/facebook/react-native/issues/13487#issuecomment-319984503)

But then how can I instantiate your own OkHttpClient and provide it to react-native in order to provide a custom trust store?

**Comment by perrosnk** [comment]
I fixed it based on this [comment](https://github.com/square/okhttp/issues/2372#issuecomment-331623598) and this [gist](https://gist.github.com/patrickhammond/0b13ec35160af758d98c).

**Comment by svlada** [comment]
This issue should be reopened.

**Comment by perrosnk** [comment]
@svlada From what I understood, it's more a problem with okhttp and android that a problem with react native

**Comment by shamilsun** [comment]
@perrosnk please provide your solution. Or example please

**Comment by perrosnk** [comment]
@shamilsun put this into your MainApplication.java file:

```java
  private void upgradeSecurityProvider() {
    ProviderInstaller.installIfNeededAsync(this, new ProviderInstallListener() {
        public void onProviderInstalled() {
          // You can do something here
        }

        public void onProviderInstallFailed(int errorCode, Intent recoveryIntent) {
            GooglePlayServicesUtil.showErrorNotification(errorCode, MainApplication.this);
        }
    });
  }

```

I hope that helps
