### ISSUE TITLE
How to display Superscript in a text with RN

### ISSUE THREAD

**Issue by Ayyagaries** [facebook/react-native#18041]
### Is this a bug report?
No this is not a bug. 
 
  If you answered "No":

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?
Yes, I read and did not find in the documentation for Text

Targeted platforms -- IOS and Android

**Comment by Ayyagaries** [comment]
Found a solution.

**Comment by riteshg** [comment]
@Ayyagaries - What is the solution? I am facing the same issue.
