### ISSUE TITLE
Search button on docs not working

### ISSUE THREAD

**Issue by TheDutchCoder** [facebook/react-native#18046]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Steps to Reproduce

Try to use the search on the site, it won't do anything.

(Write your steps here:)

1. Go to the site: https://facebook.github.io/react-native/docs/getting-started.html
2. Enter search term
3. Hit enter

### Expected Behavior

Search to work

### Actual Behavior

Search doesn't work

**Comment by lwinkyawmyat** [comment]
Hi @TheDutchCoder, Can you make issues [here](https://github.com/facebook/react-native-website) when it is related to the website? Now, website's repo moved `https://github.com/facebook/react-native-website`.

I was found similar issue facebook/react-native-website#61
