### ISSUE TITLE
"Start/Stop Sampling Profiler" not working on Android

### ISSUE THREAD

**Issue by dannycochran** [facebook/react-native#18044]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 6.10.3
  Yarn: 1.3.2
  npm: 3.10.10
  Watchman: Not Found
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.3 => 0.53.3

 Target Platform: Android API 23, Nexus 5X

### Steps to Reproduce

1. create a new react-native app from scratch (or use the repo I provided below)
2. react-native run-android
3. open debugging menu
4. tap "Start/Stop Sampling Profiler"
5. get red screen and error

### Expected Behavior

I would be able to start profiling memory usage in my react-native app

### Actual Behavior

"TypeError: undefined is not a function (evaluating 'global.pokeSamplingProfiler()')"

<img width="401" alt="screen shot 2018-02-21 at 9 55 19 am" src="https://user-images.githubusercontent.com/1217178/36496640-c0b7c344-16ed-11e8-800f-5fef04cfa6fd.png">

### Reproducible Demo

Either create a react-native repo from scratch, or use this repo here which is just that (no local modifications made after react-native init):

https://github.com/dannycochran/rn-profiler

**Comment by evanjmg** [comment]
Same here for Nexus 4, 5.1.1 +1

**Comment by Lidanha** [comment]
Hey guys,

I have the same issue, is there a workaround for finding performance issues?

Thanks,
Lidan

**Comment by 337240552** [comment]
android 6.0 Rn 0.55.0

**Comment by JulianKingman** [comment]
I get the same `global.pokeSamplingProfiler`. I'm using ExpoKit 28.0.0, fwiw

**Comment by haggholm** [comment]
Ditto. Same as https://github.com/facebook/react-native/issues/15003?

**Comment by fzyzcjy** [comment]
same +1, rn 0.55

**Comment by fzyzcjy** [comment]
Any ideas? :/

**Comment by tuomohopia** [comment]
Still getting this at RN 0.57.2 - anyone got any closer to understanding the root of the problem?

**Comment by sesam** [comment]
Getting this on both 0.55.4 and 0.57.1

**Comment by henrymoulton** [comment]
Same on android with RN 0.55.4

**Comment by axe-fb** [comment]
I am working on a fix for this.
