### ISSUE TITLE
Composing/Nesting View and custom native layout components.

### ISSUE THREAD

**Issue by msand** [facebook/react-native#18052]
### Is this a bug report?

No. Question relates to third party React-Native library authors and integration with React/Yoga.
Couldn't find more suitable forum.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment
Environment:
  OS: macOS High Sierra 10.13.3
  Node: 9.5.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.3 => 0.53.3
  react-native-svg: https://github.com/react-native-community/react-native-svg/pull/596 => https://github.com/msand/react-native-svg/commit/f3ea54c

  Target Platform:
    iOS (8.0)
    Android
        compileSdkVersion 23
        minSdkVersion 16
        targetSdkVersion 22

### Steps to Reproduce

Nest React-Native view components inside e.g. react-native-svg components.

### Expected Behavior

Unknown, what should it be?

### Actual Behavior

Latest version, exception is thrown.
New PR https://github.com/react-native-community/react-native-svg/pull/596/commits renders View in the origin of the Svg canvas. How should layout of View and Svg interact? And other custom native components allowing composition with RN View (iOS UIView and Android ViewGroup/View extending) components ?

### Reproducible Demo
https://github.com/msand/RNViewSvgNestingDemo

**Comment by msand** [comment]
Also, a review of the logic for shadow node layout calculation and actual view layout/rendering would be great. The integration probably isn't as efficient as it should be. Could someone look over it or recommend someone (preferably knowledgeable in the layout batching / optimisation) I could have a chat with?

**Comment by vovkasm** [comment]
I know, that @shergin recently do hard work in this area at least in iOS part.

**Comment by shergin** [comment]
I recently implemented same for <Text> on iOS. (And then I revamped whole ShadowNode's layout API to make everything much more logical and pretty.) I think we can use same approach for SVG.
@msand I would love to talk about that, especially about iOS part.

**Comment by msand** [comment]
@shergin Sounds great. Another thing relating to this, would be to allow the native animation to change properties on the shadow nodes for the virtual and layout only nodes. This would allow animating svg, without having to incur the cost of a View or ViewGroup for each node on Android, as this is the only way I've found to get it working so far: https://github.com/msand/react-native-svg/compare/NestedSvg...msand:NativeAnimationExperiment
But its plain absurd to create a View, when all its used for is the .getId() to find the shadowNode and set the values on that.
