### ISSUE TITLE
Nested Text components ignore opacity style on Android

### ISSUE THREAD

**Issue by bkDJ** [facebook/react-native#18057]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
>OS: macOS High Sierra 10.13.3
  Node: 8.9.4
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
>react: 16.2.0 => 16.2.0
  react-native: 0.53.0 => 0.53.0

Target Platforms:
>Android 5.1
  iOS 8.0

### Steps to Reproduce

1. Start a new project.
2. Render nested Text components with an inner component styled with reduced opacity
Example:
```
<Text>
  One
  <Text style={{opacity: 0.4}}>
    Two
    <Text style={{opacity: 0.4}}>
      Three
    </Text>
  </Text>
  .
</Text>
```

### Expected Behavior

Both iOS and Android would show the text, with the contents of the nested component rendering slightly transparent.

### Actual Behavior

| iOS | Android |
|---|---|
| <img src="https://user-images.githubusercontent.com/6138914/36551570-2c133424-17f8-11e8-9d39-f8a2fc643fc2.png" width="100%" title="Nested Text iOS" /> | <img src="https://user-images.githubusercontent.com/6138914/36551823-c82c366c-17f8-11e8-8d70-c58ca9d08b4d.png" width="100%" title="Nested Text Android" /> |
| Ok. Notice "Two" and "Three" are respecting their opacity style. | Nested text component ignores opacity style. "Two" and "Three" have the same opacity as "One" |

### Reproducible Demo

Snack demo [here](https://snack.expo.io/HJPWp1jPz). You can see that "Two" and "Three" are rendered incorrectly on Android, as shown in the screenshots above.

**Comment by bkDJ** [comment]
[This issue comment](https://github.com/facebook/react-native/issues/1314#issuecomment-153898831) would lead one to believe that this should work on all platforms.

**Comment by eriklarko** [comment]
I have encountered the same issue.

I can also reproduce it with border props, as in
```javascript
return (
    <Text>
        foo
        <Text style={{ borderWidth: 2, borderColor: 'black' }}>bar</Text>
    </Text>
)
```
renders as
![no-border](https://user-images.githubusercontent.com/492506/37485255-39ab0474-288b-11e8-9aab-3e52642a20a6.png)



I'm just guessing here but border styles and the opacity are all in the [view style props](https://facebook.github.io/react-native/docs/view-style-props.html#style), could it be that only text style props work for nested texts?
