### ISSUE TITLE
[Cocoapods] Pod install not working

### ISSUE THREAD

**Issue by avnerbarr** [facebook/react-native#1807]
I'm getting an error  installing through pods:

~/Developer/Testing/Temp/ReactTesting : pod install
Analyzing dependencies

CocoaPods 0.38.0.beta.1 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Downloading dependencies
Installing React (0.6.0)
[!] /bin/bash -c 
set -e
npm install

> ws@0.4.31 install /Users/Avner/Library/Caches/CocoaPods/Pods/Release/React/0.6.0-4d63c/node_modules/ws

> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o

> fsevents@0.3.6 install /Users/Avner/Library/Caches/CocoaPods/Pods/Release/React/0.6.0-4d63c/node_modules/babel/node_modules/chokidar/node_modules/fsevents

> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node

> contextify@0.1.14 install /Users/Avner/Library/Caches/CocoaPods/Pods/Release/React/0.6.0-4d63c/node_modules/jest-cli/node_modules/jsdom/node_modules/contextify

> node-gyp rebuild

  CXX(target) Release/obj.target/contextify/src/contextify.o

  SOLINK_MODULE(target) Release/contextify.node
npm WARN engine jest-cli@0.4.5: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"0.12.4","npm":"2.10.1"})

npm WARN engine stacktrace-parser@0.1.1: wanted: {"node":"~0.10"} (current: {"node":"0.12.4","npm":"2.10.1"})

ld: library not found for -lgcc_s.10.5

clang: error: linker command failed with exit code 1 (use -v to see invocation)

make: *** [Release/.node] Error 1

gyp ERR! build error 

gyp ERR! stack Error: `make` failed with exit code: 2

gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)

gyp ERR! stack     at ChildProcess.emit (events.js:110:17)

gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)

gyp ERR! System Darwin 14.3.0

gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"

gyp ERR! cwd /Users/Avner/Library/Caches/CocoaPods/Pods/Release/React/0.6.0-4d63c/node_modules/babel/node_modules/chokidar/node_modules/fsevents

gyp ERR! node -v v0.12.4

gyp ERR! node-gyp -v v1.0.3

gyp ERR! not ok 

npm WARN optional dep failed, continuing fsevents@0.3.6

ld: library not found for -lgcc_s.10.5

clang: error: linker command failed with exit code 1 (use -v to see invocation)

make: *** [Release/contextify.node] Error 1

gyp ERR! build error 

gyp ERR! stack Error: `make` failed with exit code: 2

gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)

gyp ERR! stack     at ChildProcess.emit (events.js:110:17)

gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)

gyp ERR! System Darwin 14.3.0

gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"

gyp ERR! cwd /Users/Avner/Library/Caches/CocoaPods/Pods/Release/React/0.6.0-4d63c/node_modules/jest-cli/node_modules/jsdom/node_modules/contextify

gyp ERR! node -v v0.12.4

gyp ERR! node-gyp -v v1.0.3

gyp ERR! not ok 

npm ERR! Darwin 14.3.0

npm ERR! argv "node" "/usr/local/bin/npm" "install"

npm ERR! node v0.12.4

npm ERR! npm  v2.10.1

npm ERR! code ELIFECYCLE

npm ERR! contextify@0.1.14 install: `node-gyp rebuild`

npm ERR! Exit status 1

npm ERR! 

npm ERR! Failed at the contextify@0.1.14 install script 'node-gyp rebuild'.

npm ERR! This is most likely a problem with the contextify package,

npm ERR! not with npm itself.

npm ERR! Tell the author that this fails on your system:

npm ERR!     node-gyp rebuild

npm ERR! You can get their info via:

npm ERR!     npm owner ls contextify

npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

npm ERR!     /Users/Avner/Library/Caches/CocoaPods/Pods/Release/React/0.6.0-4d63c/npm-debug.log

**Comment by brentvatne** [comment]
What version of Cocoapods? Is the project that you're trying this on public anywhere?

**Comment by ide** [comment]
The lgcc error went away for me after restarting my computer so you could try that.

**Comment by rxb** [comment]
Never occurred to me to restart, but it fixed it. Thanks!

**Comment by sany620** [comment]
npm install --save react-native` failed

**Comment by sghiassy** [comment]
A lot of CocoaPods errors can be resolved by resetting your Pods cache

`rm -rf ~/.cocoapods`

**Comment by sany620** [comment]
npm WARN engine stacktrace-parser@0.1.1: wanted: {"node":"~0.10"} (current: {"node":"0.12.7","npm":"2.11.3"})
