### ISSUE TITLE
requestIdleCallback may never fire again after app is backgrounded

### ISSUE THREAD

**Issue by berickson1** [facebook/react-native#18076]
Re-opening #17645 

### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

ReactNative: 0.53.3
Latest Expo App: SDK 25
Target Platform: Android 7.0

### Steps to Reproduce

1. Run Expo Sample https://snack.expo.io/Sy76vPCwM
2. Background Expo Sample
3. Foreground Expo Sample

This occurs if I always maintain at least one setIdleCallback queued at the time the app is backgrounded.

### Expected Behavior

Counter continues to increment

### Actual Behavior

Counter stops running

### Reproducible Demo

https://snack.expo.io/r1HW4J0EG
```
export default class App extends Component {
  doIdleWork() {
    requestIdleCallback(() => {
      this.setState({number: this.state ? this.state.number +1 : 0 });
      // setup another requestIdleCallback before we're done
      this.doIdleWork();
    });
  }
  componentDidMount() {
    this.state = { number:1 };
    this.doIdleWork();
  }
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.paragraph}>
         {this.state ? this.state.number : 0 }
        </Text>
        <Card title="Local Modules">
          <AssetExample />
        </Card>
      </View>
    );
  }
}
```

**Comment by berickson1** [comment]
This issue still exists, has not been fixed and requires attention. I'm unable to alter the tags on this issue...

**Comment by berickson1** [comment]
This issue still exists, has not been fixed and requires attention

**Comment by dulmandakh** [comment]
JS runs only if app is in the foreground.

**Comment by berickson1** [comment]
@dulmandakh, yes JS only runs in the foreground but requestIdleCallback callback should fire once the app is foregrounded again. Until this is fixed, nobody should ever rely on requestIdleCallback in RN since the callback behaviour is unpredictable/broken when app state changes are involved

**Comment by cwhenderson20** [comment]
I can confirm that this is still happening on Android. It seems to work as expected on iOS.

**Comment by mrozbarry** [comment]
Just to clarify (I'm not the guy to fix this), which scenario is bugged:

# Scenario 1

 - Start an idle callback
 - Background app
 - Foreground app
 - idle callback does not run

Expectation is that idle callback shouldn't be dropped between background and foreground

# Scenario 2

 - Background app
 - Foreground app
 - start an idel callback
 - idle callback never runs

Expectation is that idle callbacks should continue to work after re-opening a background app.

**Comment by aleclarson** [comment]
@cpojer Let's reopen this since it's still a problem. :)
