### ISSUE TITLE
Simulator not responding to Reload/Remote Debugging after setting up with react native config 

### ISSUE THREAD

**Issue by Ayyagaries** [facebook/react-native#18074]
I have my app setup for react-native-config.

I run the app from npm run ios works fine, I can reload the app with cmd+r reload the app and cmd+d open the debugger.
I open my Xcode and pick the schema that I have set up, the app runs fine build successful but, if I click cmd+r and cmd+d nothing happens. I don't see any kind of error anywhere.
I am using Simulator in my case.

Am I missing something

**Comment by Lxxyx** [comment]
Same issue. Plz reopen this issue. @react-native-bot
