### ISSUE TITLE
HTTP/2 + cloudflare not working in Brazil

### ISSUE THREAD

**Issue by NikolaBorislavovHristov** [facebook/react-native#18071]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

YES

### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 6.9.5
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: Not Found
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.0 => 0.53.0

### Steps to Reproduce

fetch http/2 url served through cloudflare when connected to vpn in Brazil

### Expected Behavior

response with status 200

### Actual Behavior

response error is `':status' header not present...`
accordingly to many stackoverflow [answers](https://stackoverflow.com/questions/48081624/sending-http-request-throws-exception-expected-status-header-not-present) it is related to OkHttp

### Reproducible Demo

when i disable http2 option in the cloudflare platform the request in Brazil are successful.

**Comment by lfalcao** [comment]
hey @NikolaBorislavovHristov 

I'm from brazil, i tried to fetch a cloudflare url with http2 and worked fine...
Can you provide the response headers of the request and/or the url so I can give a try here?
