### ISSUE TITLE
Unable to find a specification for 'boost-for-react-native' depended upon by `Folly`

### ISSUE THREAD

**Issue by brenmcnamara** [facebook/react-native#18085]
I get the error: `Unable to find a specification for 'boost-for-react-native' depended upon by 'Folly'` when running `pod install`

I am creating a Podfile that is identical to the one specified in the docs [here](https://facebook.github.io/react-native/docs/0.53/integration-with-existing-apps.html)

I can see that `boost-for-react-native` was introduced because of this issue [here](https://github.com/facebook/react-native/issues/16381).

[This](https://github.com/facebook/react-native/commit/cf19833ad856d04526226698e36b37809b99684b) is the commit that is adding `boost-react-native` and most-likely causing this error for me. I am not that familiar with podspecs and the specifics of the dependencies of boost vs boost-for-react native, but I'm pretty sure this is the cause.

### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.9.3
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.3 => 0.53.3

**CocaPods version 1.3.1**
**React Native CLI: 2.0.1**

### Steps to Reproduce

1. From CLI: `react-native init Temp`
2. Create a new file: `ios/Podfile` with the following contents:

```
platform :ios, '9.0'

# Remove this line to see the warnings that happen when calling 'pod install'.
# Refer to this issue: https://github.com/CocoaPods/CocoaPods/issues/4370
install! 'cocoapods', :deterministic_uuids => false

target 'Temp' do

  # Dependencies for react native firebase. Refer to this documentation:
  # https://rnfirebase.io/docs/v2.2.*/installation-ios#2.1)-Add-the-required-pods
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    # Add any other subspecs you want to use in your project
  ]

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'GLog', :podspec => '../node_modules/react-native/third-party-podspecs/GLog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  target 'TempTests' do
    inherit! :search_paths
  end

end
```

3. cd /path/to/repo/ios && pod install

### Expected Behavior

Cocoa pods installs all the dependencies without any errors.

### Actual Behavior

<img width="1140" alt="screen shot 2018-02-25 at 11 49 19 am" src="https://user-images.githubusercontent.com/2343120/36645735-187e17e0-1a22-11e8-95ec-1c9fdd2890a7.png">

### Reproducible Demo

[Here](https://github.com/brenmcnamara/RN-Boost-Bug/tree/master) is the repo with the bug.

**Comment by milawoai** [comment]
same error

**Comment by clairewli** [comment]
I got the same error too.

**Comment by milawoai** [comment]
add  " pod 'boost-for-react-native' " into Podfile , It fix my problem

**Comment by zhantx** [comment]
do a `pod update` first

**Comment by pranavjandial123** [comment]
Any update on the issue?? I am still facing it..

**Comment by annaayond** [comment]
same error

**Comment by Soweyln** [comment]
Run `pod update` first, it will update the podspecs so that it will include `boost-for-react-native`.

**Comment by annaayond** [comment]
I solved it by running pod update, removing the build folder and rebuild the project with yarn/npm.

**Comment by lengqingfeng** [comment]
same error

**Comment by brenmcnamara** [comment]
The `pod update` solution worked for me. I'm closing this task since it seems to be resolved. Thanks for the help!

**Comment by scutHuqiang** [comment]
not working for me

**Comment by kevinzhangftw** [comment]
seems like after running pod update does installation automatically, anyone can confirm?

**Comment by brianfoody** [comment]
I'm stuck with version 1.56.0 in my pods folder after clearing build, usual React Native clean of everything and  `pod update`. Really frustrating.

**Comment by rkretzschmar** [comment]
I had the same error until I added the following line to my projects Podfile:

```
pod 'boost-for-react-native', :podspec => 'https://raw.githubusercontent.com/react-native-community/boost-for-react-native/master/boost-for-react-native.podspec'
```

But that smells a bit.
