### ISSUE TITLE
【iOS】app crashed randomly when reload bridge in short time version 0.53.3

### ISSUE THREAD

**Issue by fishmwei** [facebook/react-native#18089]
### Is this a bug report?

YES

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

YES

### Environment
 
Environment:
  OS: macOS High Sierra 10.13.2
  Node: 8.4.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.0 Build version 9A235
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.3 => 0.53.3
	 

### Steps to Reproduce

1. use cocoapods, pod React 0.53.3 into project  , or just create by run `react-native init TESTRNCrash`
2. react-native bundle a jsbundle, then put it into project
3. create a RCTRootView then execute the jsbundle, then reload many times (to improve the probability to hit the bug)

### Expected Behavior

everything is OK at last, don't crash.

### Actual Behavior

it crashed!!!!

just like #17886 

### Reproducible Demo

https://github.com/fishmwei/test-react-native-spec.git  :branch => 'fix/reload-crash'
TestRN53 project

**Comment by Lxxyx** [comment]
Same issue

**Comment by Lxxyx** [comment]
![image](https://user-images.githubusercontent.com/13161470/36943336-b9f77b16-1fc2-11e8-8ee6-34767b6fd8a9.png)


White screen and then crash.

**Comment by fishmwei** [comment]
For Discussion
