### ISSUE TITLE
[PerformanceLogger] Massive amounts of "PerformanceLogger: Attempting to add a timespan that already exists"

### ISSUE THREAD

**Issue by jwyld** [facebook/react-native#1809]
Our RCTRootView is contained in a UICollectionView and is scrolled around.  It's very possible for the view to go out of bounds and come back as a result of scrolling.  RCTPerformanceLogger is set up for RCTContentDidAppearNotification.  Since the view is coming and going in terms of visibility, -sendTimespans can be called multiple times.  This ends up causing the JS to log with every re-display of the view.  This is only on __DEV__, but it produces way too much noise in the console and kills the performance while debugging as well.

**Comment by brentvatne** [comment]
@jwyld - could you submit a pull request to handle this?

**Comment by ide** [comment]
cc @tadeuzagallo

**Comment by tadeuzagallo** [comment]
I landed a fix internally, should be out on the next sync.
