### ISSUE TITLE
[SectionList] scrollToLocation scrolls past content on iOS

### ISSUE THREAD

**Issue by Jpunt** [facebook/react-native#18098]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.2.1
  Yarn: 0.27.5
  npm: 5.3.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.2.0 => 16.2.0
  react-native: ^0.53.3 => 0.53.3

### Steps to Reproduce

Implement a `SectionList` and use `scrollToLocation` to scroll to the last section.

### Expected Behavior

It scrolls to the last section, while making sure it doesn't scroll past the content. On Android this works as expected: 

![screen shot 2018-01-08 at 11 54 05](https://user-images.githubusercontent.com/190501/34667961-909e16ee-f46b-11e7-8a5d-0e7cfdd0b6c1.png)

### Actual Behavior

On iOS `scrollToLocation` scrolls to far:

![img_362ddaf36c23-1](https://user-images.githubusercontent.com/190501/34668105-2be376d0-f46c-11e7-889a-d7f49aaaf28a.jpeg)

This also introduces some weird issues when the user starts scrolling from there on.

### Reproducible Demo

[https://snack.expo.io/HJgTyClEG](https://snack.expo.io/HJgTyClEG)

**Comment by Jpunt** [comment]
This issue is still relevant to RN 0.55.4

https://snack.expo.io/@jpunt/scrolltolocation

```
Environment:
  OS: macOS High Sierra 10.13.5
  Node: 8.2.1
  Yarn: 1.5.1
  npm: 5.3.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz => 0.55.4
```

**Comment by DannyvanderJagt** [comment]
Got the same issue on IOS.  After fiddling around I found a temporary solution for my app:

```js
this.sectionListRef.scrollToLocation({
	itemIndex: -1 , // IOS only
	sectionIndex: index,
})
```
After this the `scrollToLocation` works as expected. 
Let me know if this works for others too

**Comment by megalithic** [comment]
just confirming this is an issue with Expo 27 for sure. Still getting this issue.

**Comment by cpojer** [comment]
You should be able to use `overScrollMode="never"` to fix your issue.
