### ISSUE TITLE
Nesting an Image and a Text which has lineHeight in an Text will display wrong

### ISSUE THREAD

**Issue by JosephPoplar** [facebook/react-native#18094]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

  OS: macOS High Sierra 10.13.3
  Node: 8.9.1
  Yarn: Not Found
  npm: 4.6.1
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4408382

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.3 => 0.53.3

  Target Platform: iOS (11)

### Steps to Reproduce

1.nest a **Text** with some text and an **Image** in a **Text**
2.give the nested **Text** a style with **lineHeight** 12
3.run the app 

### Expected Behavior

nest Text should render normal with lineHeight 12 , and there should be an Image below it.
<img width="359" alt="rnbug-01" src="https://user-images.githubusercontent.com/13551410/35490430-85879c42-04da-11e8-96d2-683cb71828c1.png">

### Actual Behavior

the Image was lost ,and the content of the nested Text  render as one single line without line break.
<img width="334" alt="rnbug-02" src="https://user-images.githubusercontent.com/13551410/35490437-8cf1a1b2-04da-11e8-90ad-0ad858f6c59e.png">

### Reproducible Demo

[ReactNativeTextDemo.zip](https://github.com/facebook/react-native/files/1758057/ReactNativeTextDemo.zip)
please run `npm install` after opening the project.

**Comment by Dorentin1997** [comment]
Show some code please.

**Comment by JosephPoplar** [comment]
```
import React from 'react';
import {StyleSheet, Text,Image} from 'react-native';


const htmlContent = `
  One Two Three
  One Two Three
  One Two Three
  One Two Three
  One Two Three
`;

export default class LineHeightDemo extends React.Component {
	render() {
		return <Text style={{flex:1}}>
				<Text style={styles.text} >{htmlContent}</Text>
				<Image  source={{uri :"https://i.redd.it/1l01wjsv22my.jpg"}} style={{width:400,height:400}}/>
			</Text>
	}
}

const styles = StyleSheet.create({
  text:{
    fontSize: 10,
		color: '#1E1E1E',
		lineHeight:12
  },
});
```
