### ISSUE TITLE
init can't run in 0.53.3

### ISSUE THREAD

**Issue by Timson020** [facebook/react-native#18102]
### Is this a bug report?

(write your answer here)
Yes

I run this cmd at step
```
react-native init demo
./demo
react-native run-android
```
You can run to try 
init can't run in 0.53.3 at android

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.)

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by matthamil** [comment]
Can you provide more details about your environment?
