### ISSUE TITLE
Picker state not changing within Flatlist

### ISSUE THREAD

**Issue by vigneshwarrao** [facebook/react-native#18113]
### Is this a bug report?

Not exactly. It closely resembles as issue.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

  Environment:
  OS: Windows 10
  Node: 6.11.3
  Yarn: Not Found
  npm: 3.10.10
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  2.3.0.0 AI-162.4069837

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.2 => 0.52.2

### Steps to Reproduce

Snack: https://snack.expo.io/rkiO3NBOz

1. We have a list to bind the data with the help of Flatlist.
2. Inside each list item, we have a Picker to choose his quantity of that particular item.
3. But when we are changing the picker value: it is changing and immediately refreshing and coming back to default value. [Eg: default value: 'Select', changed to: '3', coming back: 'Select']
4. Tried with "shouldItemUpdate" option so the value is changing but applying same picker value for all list items. [Eg: default value: 'Select', changed to: '3', all items values are '3']
5. **State Name** provided to **picker is dynamic** so there is no problem with that.
6. This is happening only when we are applying the Flatlist, but normal binding with Map is fine.
7. I think the state is again refreshing the flatlist.
8. Can anybody help us, how to solve the above situation

### Expected Behavior
Since i provided dynamic state name, it should select the individual picker value seperately
Eg: default value: 'Select', changed to:'3' only for selected list item., all other items will have 'Select'

### Actual Behavior
. [Eg: default value: 'Select', changed to: '3', coming back: 'Select']
. shouldItemUpdate -- [Eg: default value: 'Select', changed to: '3', all items values are '3'];

Following is the code i used for above process:
<FlatList data={this.state.mainData}
   renderItem={({ item, ival }) => this.renderPickerData(item, ival)}
   keyExtractor={(item) => item.id}
   shouldItemUpdate={this.shouldItemUpdate.bind(this)} // optional, got it from one of the forum while searching
/>

renderPickerData = (item, iVal) => {
    return (<View><Text>{item.categoryName}</Text>{this.renderPicker(iVal)}</View>)
};

renderPicker(iVal){
    return (<Picker selectedValue={this.state['pickValue' + iVal]} onValueChange={(value) => this.setState({ ['pickValue' + iVal]:value })}>
      <Picker.Item label="1" value="1" />
      <Picker.Item label="2" value="2" />
      <Picker.Item label="3" value="3" />
    </Picker>);
};

// got it from one of the forum while searching
shouldItemUpdate(props, nextProps) { return true; }

**Comment by hramos** [comment]
Thanks for reporting this. Any chance you could fill out the Environment section? Is this reproducible on Snack?

**Comment by vigneshwarrao** [comment]
Thank you for quick reply hramos: I updated the environment section. I didn't get "Is this reproducible on Snack?". Can you explain me ?

**Comment by hramos** [comment]
Sure! Snack is covered in the Contribution Guidelines, here: http://facebook.github.io/react-native/docs/contributing.html#reporting-new-issues

**Comment by vigneshwarrao** [comment]
Hi hramos, I had done the project in Snack (https://snack.expo.io/rkiO3NBOz).
Now if you check : when selecting the dropdown under Fruits to 2, it is changing to 2 & immediately changes to 1 again.
If you put "shouldItemUpdate" : now select Fruits 2 then it is changing all dropdown values to 2

**Comment by hramos** [comment]
Thanks for the repro!

**Comment by yanchenko** [comment]
It's happening when a `Picker` is in a row of `FlatList`.
Then, if each picker data item has a `key`, the picker works correctly. But with `keyExtractor: item => item.id.toString()` instead it always scrolls to the first element.

**Comment by yatatsu** [comment]
@vigneshwarrao @hramos `FlatList#renderItem` does not be called again in your code. Update `data` or use `extraData`.

> A marker property for telling the list to re-render (since it implements PureComponent). 
https://facebook.github.io/react-native/docs/flatlist#extradata

The repro code is following.
https://snack.expo.io/SJZ3vI8Um
