### ISSUE TITLE
"Cannot record touch end without touch start." error when taking a screenshot with 3-finger gesture on Android. 

### ISSUE THREAD

**Issue by mutiadianita** [facebook/react-native#18112]
### Is this a bug report?

Yes.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes.

### Environment

  Environment:
    OS:  Windows 10 Pro
    Node:  8.9.4
    Yarn:  1.3.2
    npm:  5.6.0
    Watchman:  Not Found
    Xcode:  N/A
    Android Studio:  3.0 AI-171.4443003

  Packages: (wanted => installed)
    react-native: ^0.53.0 => 0.53.0
    react: ^16.2.0 => 16.2.0

  Target Platform: Android (6.0.0)

### Steps to Reproduce

(Write your steps here:)

1. Use "Oppo F1s"phone.
2. Run "react-native run-android"
3. Use three-finger screenshot gesture

### Expected Behavior

Taking a screenshot of the page.

### Actual Behavior

Red screen error
![errortouch](https://user-images.githubusercontent.com/22410196/36705536-45503344-1b98-11e8-93f2-7c308e25e971.png)

**Comment by liqing338** [comment]
is this problem solved？
