### ISSUE TITLE
[MapView] MapView has no propType for native prop `RCTMap.mapType` of native type `MKMapType`

### ISSUE THREAD

**Issue by danscan** [facebook/react-native#1812]
Getting this bug in `react-native 0.7.0-rc.2` at 
```javascript
React = require('react-native')
```

I'm not using `MapView` anywhere.

**Comment by brentvatne** [comment]
It looks like we're missing an entry in `RCTConvert` to handle this, PR coming, thanks for the report!

**Comment by brentvatne** [comment]
Scratch that, looks like those are in place - you might have to clean your Xcode build

**Comment by danscan** [comment]
This seems fine now– my React Pod's version didn't match my react-native version.

**Comment by asamiller** [comment]
I ran into this same error by creating a new project `react-native init TestProject` and then changing the version in `package.json` to `"react-native": "0.7.0-rc.2"` and running `npm install`.

![image](https://cloud.githubusercontent.com/assets/5133623/8535777/00fb0b72-23fe-11e5-862d-e42010417826.png)

**Comment by brentvatne** [comment]
@asamiller - are you using cocoapods? Did you restart your packager after upgrading?

**Comment by Intellicode** [comment]
I had the same error, it is indeed resolved by restarting the packager

**Comment by jawadrehman** [comment]
@brentvatne got this error and it doesnt make any sense to me. have been trying to upgrade my app to react native 0.8.0
![ios simulator screen shot 21-aug-2015 5 46 00 pm](https://cloud.githubusercontent.com/assets/1839153/9413862/8cba1c8c-482c-11e5-8b6a-b0f2aef05034.png)

**Comment by brentvatne** [comment]
@jawadrehman - did you restart the packager? try doing that as well as re-opening Xcode

**Comment by bendellarocco** [comment]
I am seeing this on android.  I have restarted packager about 10 times, I have reinstalled react 10 times,  restarted the computer, restarted android studio.  I am using rn 19.
![screen shot 2016-05-17 at 6 23 59 pm](https://cloud.githubusercontent.com/assets/9866222/15476246/0461ce32-20dc-11e6-8b18-32f24b60f8b3.png)

**Comment by chufengma** [comment]
same error : 
![image](https://cloud.githubusercontent.com/assets/7855703/15744115/a1d14300-28fc-11e6-8a43-be31eaf3d07b.png)

**Comment by bendellarocco** [comment]
I was able to fix this by updating react from 19 to 25
