### ISSUE TITLE
Text to emoji Gboard in textinput crash

### ISSUE THREAD

**Issue by albert-carreras** [facebook/react-native#18126]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes
### Environment

  Environment:
    Node:  8.4.0
    npm:  5.4.0

  Packages:
    react-native: 0.53
    react: 16.2.0

### Steps to Reproduce

1. Start inputting text on any textinput component.
2. Write a word that Gboard can transform (suggests) into an emoji.
3. Accept the change.
4. App crash

### Expected Behavior

No crash.

**Comment by hramos** [comment]
This may have been fixed by https://github.com/facebook/react-native/pull/18114 which is now on master.

**Comment by albert-carreras** [comment]
Still present in 0.54.0

**Comment by hramos** [comment]
The fix, b60a727adbcfa785e3d1b13bf069b766216e60f8, landed in master after the 0.54 release was cut, so that's expected.
