### ISSUE TITLE
Can not run multiple RN instances on Android

### ISSUE THREAD

**Issue by henrydf** [facebook/react-native#18149]
I can run multiple RN instances on iOS platform with RCTRootView.
But I got an error on Android.

FATAL EXCEPTION: mqt_native_modules
Process: com.myapp, PID: 3790
com.facebook.react.common.JavascriptException: undefined is not an object (evaluating 'viewConfig.Manager'), stack:
<unknown>@9962:19
<unknown>@9960:33
loadModuleImplementation@127:12
guardedLoadModule@86:36
_require@64:77
<unknown>@9875:24
loadModuleImplementation@127:12
guardedLoadModule@86:36
_require@64:77
<unknown>@3970:33
<unknown>@8443:2
loadModuleImplementation@127:12
guardedLoadModule@86:36
_require@64:77
<unknown>@3950:24
loadModuleImplementation@127:12
guardedLoadModule@86:36
_require@64:77
<unknown>@9866:23
loadModuleImplementation@127:12
guardedLoadModule@86:36
_require@64:77
<unknown>@22599:38
loadModuleImplementation@127:12
guardedLoadModule@86:36
_require@64:77
StyleSheet@3151:19
<unknown>@55839:26
loadModuleImplementation@127:12
guardedLoadModule@86:36
_require@64:77
<unknown>@55640:26
loadModuleImplementation@127:12
guardedLoadModule@86:36
_require@64:77
<unknown>@55360:28
loadModuleImplementation@127:12
guardedLoadModule@86:36
_require@64:77
<unknown>@1303:33
loadModuleImplementation@127:12
guardedLoadModule@79:45
_require@64:77
global code@75616:9

### Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.9.1
  Yarn: 1.3.2
  npm: 5.5.1
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.50.1 => 0.50.1

### Expected Behavior

Everything is ok as iOS.

### Actual Behavior

not ok on Android.

### Steps to Reproduce

Create a another RCTRootView out MainActivity.

**Comment by hey99xx** [comment]
I don't know what you did wrong, but you can absolutely have multiple `ReactInstanceManager ` instances and multiple `ReactRootView` instances attached to each. It does work. You may have a different issue.

**Comment by henrydf** [comment]
ok.... I used wrong bundle which is builded for ios.
