### ISSUE TITLE
fix missing lines in the ios picker

### ISSUE THREAD

**Issue by adnanbabar** [facebook/react-native#18155]
Hi,

Just opening this issues again this is a case where the picker is missing the highlight lines for the currently selected picker item. 

http://stackoverflow.com/questions/39564660/uipickerview-selection-indicator-not-visible-in-ios10

Issue was raised here as well
https://github.com/facebook/react-native/issues/14442

Fixed was proposed in another issue(link below) but it was never merged.
https://github.com/facebook/react-native/pull/13342

**Additional Information**
"react-native": "0.53.3",
Platform: iOS 10.2 
Development Operating System: macOS

Thanks 
Ad

**Comment by yangtaufoo** [comment]
I’m having this issue too. It’s completely missing.

React Native 0.53.3 & 0.53.0
Platform: iOS 11.2

**Comment by adnanbabar** [comment]
Okay, I will try my best to provide more information.

**React native 0.53.3 on 
Mac OSX 10.13.1.
Simulator 11.3**

After adding a picker component first time to the screen I can see the "separator lines" the minute I interact and reload simulator the lines disappear. After this even if I restart the whole app by running "react-native run-ios" command I don't see the separator lines. Screenshot link below 
**https://raw.githubusercontent.com/louietan/PickerIOSIssue/master/demo.png**

**Reproduction steps:**

1. Add Picker component with some values
2. Interact with picker
3. And reload ios simulator by cmd+R 
4. Separator lines disappear at this point.

Again issues have already been raised twice below


**Issue was raised here as well**
https://github.com/facebook/react-native/issues/14442

**Fixed was proposed in another issue(link below) but it was never merged.**
https://github.com/facebook/react-native/pull/13342


Please let me know if you need anymore information

**Comment by adnanbabar** [comment]
@hramos  Any update on this, please?

**Comment by hramos** [comment]
I don't have anything to add, other than making sure you fill in the template in your original post and to provide sample code that reproduces the issue.

**Comment by yangtaufoo** [comment]
@hramos Can i know the rationale for the dispatch action in `setSelectedIndex` in `RCTPicker.m`?

I have the missing picker lines issue and it seems that modifying from,
```
dispatch_async(dispatch_get_main_queue(), ^{
      [self selectRow:selectedIndex inComponent:0 animated:animated];
    });
```

to this,

```
[self selectRow:selectedIndex inComponent:0 animated:animated];
```

will allow for the lines to show
