### ISSUE TITLE
gestureState.numberActiveTouches of callback function `onStartShouldSetPanResponderCapture` always return 1 when I use two fingers touching the screen. 

### ISSUE THREAD

**Issue by tsaohucn** [facebook/react-native#18151]
### Environment

"react": "16.0.0-alpha.12",
"react-native": "0.46.4",

### Expected Behavior

I expect gestureState.numberActiveTouches return value 2

### Actual Behavior

gestureState.numberActiveTouches return value 1

### Steps to Reproduce

When I start use two fingers on screen of phone, the gestureState.numberActiveTouches of callback onStartShouldSetPanResponderCapture always return 1, it's very weird, but the callback function onPanResponderMove works correctly with returning 2 value when I use two fingers move on screen of phone.

**Comment by MiLeung** [comment]
@tsaohucn Find a solution?
