### ISSUE TITLE
Deep Linking Broken on iOS when Application Not in Memory

### ISSUE THREAD

**Issue by kyledecot** [facebook/react-native#18154]
I believe that there is a bug in React Native's Deep Linking functionality on iOS. The issue is that the event listener appears to get added **after** the first deep link when launching the application for the first time (out of memory). This causes the first deep link to not be caught–deep links after the app is in memory but in the background appear to work correctly. This appears to be the case for both regular deep links as well as Universal/App Links.

### Related Issues

https://github.com/react-navigation/react-navigation/issues/798
https://github.com/facebook/react-native/issues/11191

### Environment

Node: 8.4.0
React Native: 0.50.4
React: 16.0.0

### Expected Behavior

I would expect that when the app is not in memory that the first deep link work correctly.

### Actual Behavior

When the application is launched for the first time via a deep link the deep link, the event listener will not receive the first deep link. All deep links after the application is in memory seem to work correctly.

### Steps to Reproduce

Follow the steps on the [React Native documentation](https://facebook.github.io/react-native/docs/linking.html) for Linking. Then launch the application via a deep link. You will notice that the initial one does not get caught by the event listener.

**Comment by amitassaraf** [comment]
This issue occurs in the latest version of React Native 0.58.4
