### ISSUE TITLE
Deprecation warnings are showing up after updating to 0.54

### ISSUE THREAD

**Issue by jhnferraris** [facebook/react-native#18165]
Since we updated to 0.54, we received a lot of deprecation warnings. 

The reason that we updated was to address this [issue](https://github.com/facebook/react-native/issues/15059#issuecomment-368195535). App works as expected, however, warnings are showing up.

Do we have a document or a website showing the full list of deprecations so we can act accordingly? Thank you!

**Comment by hackdie** [comment]
+1 Make release notes great again.

**Comment by gre** [comment]
I'm also receiving a lot of deprecation warnings. I think those are great to make libraries do the changes as early as possible. however not so great for the end user app dev experience ('cause RN show the yellow warning in the App itself.. maybe they should only be displayed in the console for so called ["lowPriorityWarning"](https://github.com/facebook/react/blob/86ee9e84880cab9f3804e7e59ec75bb75a4cf455/packages/react-reconciler/src/ReactStrictModeWarnings.js#L130)).

Anyway, so if you are looking for a way to temporarily disable this as I am, I've figured you can do:

```js
require("ReactFeatureFlags").warnAboutDeprecatedLifecycles = false;
```

**Comment by gre** [comment]
For the change logs you can probably already read https://medium.com/@baphemot/whats-new-in-react-16-3-d2c9b7b6193b and especially this RFC: https://github.com/reactjs/rfcs/blob/master/text/0006-static-lifecycle-methods.md

**Comment by jhnferraris** [comment]
@gre thanks dude!

**Comment by DimitryDushkin** [comment]
Hey, @gre! Where did you placed `warnAboutDeprecatedLifecycles = false` thing? I've tried to put it in `index.js` with no luck. I've also restarted and reset cache for metro bundler.

**Comment by DimitryDushkin** [comment]
Answer my own question. Because `import` is moved to top in compiled code I've rewrote it to require. So the code is:
```js
require('ReactFeatureFlags').warnAboutDeprecatedLifecycles = false;

const {AppRegistry} = require('react-native');
const App = require('./App').default;

AppRegistry.registerComponent('iosapp', () => App);
```

**Comment by laiba421** [comment]
@DimitryDushkin I tried your fix but I am getting a weird error saying reducer is not a function:

> require("ReactFeatureFlags").warnAboutDeprecatedLifecycles = false;
> const React = require('react');
> const { AppRegistry } = require('react-native');
> const App = require('./src/containers/App').default;
> const rootReducer = require('./src/reducers/index');
> const { createStore } = require('redux');
> const { Provider } = require('react-redux');
> const store = createStore(rootReducer);
> const AppContainer = () =>
> <Provider store={store}>
>     <App/>
> </Provider>
> AppRegistry.registerComponent('todoappnative1', () => AppContainer);
> console.log(store.getState());

Can you check it what's wrong with my require usage?

**Comment by gre** [comment]
@DimitryDushkin I have a separated file that I call polyfill.js, and in my entry point, i'll do `import "./polyfill";` at first line. if it important it is the first import so there is not the problem you mentioned.

**Comment by sameer421** [comment]
@gre can you help me it's just very annoying.

**Comment by DimitryDushkin** [comment]
@sameer421 if you have export default in rootReducer.js you should `require('...').default;`

@gre oh,  that's clever :)

**Comment by sameer421** [comment]
@DimitryDushkin Thanks it worked. Removed All my warnings.

**Comment by izikandrw** [comment]
in your AppRegistry file add an array of messages you want to ingore `console.ignoredYellowBox = ['View #']` see http://www.joshualyman.com/2016/03/react-native-debugging-tips/ for more details

**Comment by gaearon** [comment]
These warnings got into the release in this state by accident. It wasn't intentional.

Please follow this thread: https://github.com/facebook/react-native/issues/18175.
