### ISSUE TITLE
Android app crashes while passing `WritableMap` from native to javascript. 

### ISSUE THREAD

**Issue by Josh2941** [facebook/react-native#18163]
Android app crashes while passing `WritableMap` from native to javascript. It only happens sometimes like 4 to 5 times a day, since its a background process. But it also happens in foreground. I am **highly relying for a fix**, since its affecting the stability. Seeing the stacktrace, I assume that its trying to log something about MyModule (I am not logging it) and fails expecting a String.  

### Environment
Environment:
  OS: Linux 4.8
  Node: 6.11.1
  Yarn: 0.26
  npm: 3.10.10
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.52.0 => 0.52.0

I don't know why its showing Not Found for Android Studio, but I have it.

### Expected Behavior

It should pass the `WritableMap` from native to javascript **without error** (Crash occurs only few times, But, it may affect other processes. So its important for stability).

### Actual Behavior
Stacktrace: 
```
com.facebook.react.bridge.NativeArgumentsParseException TypeError: expected dynamic type `string', but had type `object' (constructing arguments for MyModule.log at argument index 1) 
    JavaMethodWrapper.java:368 com.facebook.react.bridge.JavaMethodWrapper.invoke
    JavaModuleWrapper.java:162 com.facebook.react.bridge.JavaModuleWrapper.invoke
    NativeRunnable.java:-2 com.facebook.react.bridge.queue.NativeRunnable.run
    Handler.java:743 android.os.Handler.handleCallback
    Handler.java:95 android.os.Handler.dispatchMessage
    MessageQueueThreadHandler.java:31 com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage
    Looper.java:150 android.os.Looper.loop
    MessageQueueThreadImpl.java:194 com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run
    Thread.java:833 java.lang.Thread.run


Caused by: com.facebook.react.bridge.UnexpectedNativeTypeException TypeError: expected dynamic type `string', but had type `object' 
    ReadableNativeArray.java:-2 com.facebook.react.bridge.ReadableNativeArray.getString
    JavaMethodWrapper.java:75 com.facebook.react.bridge.JavaMethodWrapper$5.extractArgument
    JavaMethodWrapper.java:71 com.facebook.react.bridge.JavaMethodWrapper$5.extractArgument
    JavaMethodWrapper.java:361 com.facebook.react.bridge.JavaMethodWrapper.invoke
    JavaModuleWrapper.java:162 com.facebook.react.bridge.JavaModuleWrapper.invoke
    NativeRunnable.java:-2 com.facebook.react.bridge.queue.NativeRunnable.run
    Handler.java:743 android.os.Handler.handleCallback
    Handler.java:95 android.os.Handler.dispatchMessage
    MessageQueueThreadHandler.java:31 com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage
    Looper.java:150 android.os.Looper.loop
    MessageQueueThreadImpl.java:194 com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run
    Thread.java:833 java.lang.Thread.run

```
### Steps to Reproduce

1. Create a bridge for connecting react-native and native Android.
2. Create a bridging function in native android bridging module and send a `WritableMap` with some sample key-value pairs as Callback.
3. Create a function in javascript to handle the callback from native.
4. Call the javascript function in `componentWillMount` or `componentDidMount` to make the native access through the bridge.
5. The error will occur after it executes `callback.invoke(writableMap)` in native.

**Example:**

Native Code:
```
@ReactMethod
public void getMap(Callback callback) {
    try {
        WritableMap writableMap = Arguments.createMap();
        writableMap.putString("key1", "value1");
        writableMap.putString("key2", "value2");
        callback.invoke(writableMap);
    } catch (Exception e) {
         e.printStackTrace();
    }
}
```

React-Native Code:
```
componentWillMount() {
     MyModule.getMap(map => {
          console.log("Map", map);
     });
}
```

**Comment by hey99xx** [comment]
Please put real code example, your Java native module + your JS code calling this native module. Current information is not sufficient for anyone to handle. And I feel this should go to Stackoverflow but I'm not sure since it could as well be real issue (but I'm not actually convinced).

**Comment by Josh2941** [comment]
@hey99xx, please view the updated issue. I have added a sample code.

**Comment by hramos** [comment]
Just a comment that sporadic crashes, especially those that affect a particular application, that are submitted as issues without a good enough repo, are unlikely to get attention from others in the repo.
