### ISSUE TITLE
Header comment still saying "BSD-style license" in xcodeproj

### ISSUE THREAD

**Issue by jamesguan** [facebook/react-native#18161]
To reproduce, use `react-native init`. Even for the latest v0.54 version, the header comments in AppDelegate.h, AppDelegate.m, main.m, etc, are still saying:

> /**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */

This also shows up for Android builds.

**Comment by hramos** [comment]
The license change landed in master after the 0.54 RC had already been cut. If you build from source (i.e. master), you should not see the previous BSD header. If all goes well, the change should make it to a stable release in v0.55.

Note that we have [checks in place](https://github.com/facebook/react-native/blob/master/scripts/circleci/check_license.sh) that should catch any regressions here, and they are green at this moment.
