### ISSUE TITLE
WebView has no goback()?

### ISSUE THREAD

**Issue by KuoKongQingYun** [facebook/react-native#18169]
I find there is a method of WebView named goBack in old version document. [https://facebook.github.io/react-native/docs/0.31/webview.html#goback](url)
but in latest version,it disappeared?
[https://facebook.github.io/react-native/docs/webview.html](url)

I also find that this method is still valid in latest react native,so what happened?

**Comment by hramos** [comment]
Closing as this is not a valid bug report. For issues in the docs, please go to facebook/react-native-website, or hit EDIT on the relevant document to submit a PR.
