### ISSUE TITLE
[Docs] Improve style docs

### ISSUE THREAD

**Issue by brentvatne** [facebook/react-native#1816]
Based on questions I've heard a lot / from a co-worker's experience:
- Style & Touchable elements (eg: how do I round a corner on TouchableHighlight?)
- Styling Text vs View - Text has a link to View styles so presumably it should support those styles as well
- "How do I do a percentage width?" - talk about Flex
- Transparency and text

**Comment by brentvatne** [comment]
Feel free to pitch in with any other questions you have / issues that you have run into with styling

**Comment by grabbou** [comment]
`Styling Text vs View` I often find my iOS knowledge helpful when it comes down to writing a good UI hierarchy. There are few things missing btw - I haven't found any good examples of `transforms`, e.g. `scale` and so on, especially regarding transform property can accept an array.

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/docs-improve-style-docs
