### ISSUE TITLE
Frame drop with scrolling and animations with 0.53.x, 0.54 update

### ISSUE THREAD

**Issue by daesan** [facebook/react-native#18162]
FlatList scrolling and Animated animations started dropping frames with 0.53.x or 0.54.0 update. Scrolling and animations used to be very fluid but is now consistently choppy. When I downgrade to 0.52.3, this problem goes away.

This problem occurs only on iOS.

### Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 6.11.0
  Yarn: Not Found
  npm: 3.10.10
  Watchman: Not Found
  Xcode: Not Found
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: ^0.54.0 => 0.54.0

### Expected Behavior

Scrolling or animations should be fluid. I am using FlatList for contents and Animated for page transition (via custom navigator) and image zooming. Even animations with "ActionSheetIOS.showActionSheetWithOptions" is now choppy.

### Actual Behavior

Animations are now choppy. Instead of 60 frames per second, it feels like 15 frames per second and thus it causes eye strain. The (slow) frame rate seems to be pretty consistent though.

### Steps to Reproduce

I am not sure. The choppy scrolling and animation is not local to the specific part of the app. The entire app has become choppy. Even native animation (I assume) via ActionSheetIOS is choppy. I think some change with 0.53.0 causing the conflict. Could someone familiar with 0.53.0 update imagine what change might be the source of this problem?

**Comment by joshyhargreaves** [comment]
Do you think you'd be able to produce a reproducible demo project?

**Comment by vovkasm** [comment]
I'm also interested in this, if no one will produce demo in a week, I will try to create demo myself. To be sure, we need to compare 0.52 and 0.53 versions, right?

**Comment by ShiChenlong** [comment]
I'm also interested in this，I hope that we can collect reliable samples not use computers to find random numbers.Then we can put these data into Matlab，which is very convenient to develop.

**Comment by daesan** [comment]
@joshyhargreaves Thanks for the response. However, I'm not quite sure about that though.

My app is quite complicated and has many pages. It currently has 150+ pages. While the choppy animations are present with my app all the time as of 0.53.x or 0.54.0, once I log out, it is gone. When my app isn't logged in, the login and signup section of my app is composed of only about 13 pages. This lighter section of my app isn't suffering from the choppy animations issue I reported above.

Though I am not sure what is triggering the choppy animation problem, "log in" section of my app isn't suffering from it. This makes me think that a simpler version of my app, a.k.a. the demo app isn't likely to reproduce the issue. Could that be the number of pages loaded that is causing this issue? Or maybe could the custom native modules I am using be causing the issue?

If anyone can give me some directions or hints, I could try those out. But as of now, I don't have much clue about what is causing this choppy animations problem..

**Comment by vovkasm** [comment]
@daesan 
I can suggest (at least I would do these steps)
1. determine minimal "context" for test, e.g. ok, no minimal sample, but you can find one place in your app where you can clearly see choppy animation (ex. press button on page A, to switch to page B, animation of A -> B clearly shows lag, it is best if A and B contains minimal set of elements, especially without heavy elements such as FlatList, ScrollView, ever Text is relatively heavy). Ensure that this test shows the problem, i.e. RN 0.52 smooth, but RN 0.53 choppy.
2. Having this test, I can run profile with RN 0.53, then with RN 0.52 and compare. Firstly, I would try JS profile: http://facebook.github.io/react-native/docs/debugging.html#chrome-developer-tools
Bad, is that it is not real js profile, but should be ok for compare in this concrete case :-)
Analyze. Try to find what exact function or functionality in RN 0.53 now take more time.
3. RN 0.53 contains some internal refactoring of RNView/RNShadowView parts (also yoga moved to C++, if I not misunderstood the code), so next step is Xcode instruments for profile native code.
Analyze... same as in step 2.
4. Analyze changelog and diff (`git diff 0.52-stable...0.53-stable` of RN itself) to find some interesting changes. For example commit 7d1dedadd7a9 may be involved (may be not, without profile data we can't say)

**Comment by daesan** [comment]
@vovkasm Thank you for the detailed suggestion. (And sorry that I'm replying late. I'm very much caught up with work these couple days that I am only now catching up with my email backlogs.)

It may take some time on my part, but I will follow your suggestion and share them here. Thank you again for sharing your insight!

**Comment by daesan** [comment]
It turned out that starting with RN 0.53.0, a parent view containing vertically stacked subviews overlapping one another causes animation to drop frames and become jittery when it is involved in such animation.

I would guess that previously there was an optimization to not render the overlapped (thus not visible) views and now such implicit optimization is removed. Once I set the overlapped views' opacity to zero explicitly, the frame dropping issue disappears.
