### ISSUE TITLE
The --device option fails on command line in v54.0

### ISSUE THREAD

**Issue by Gulci** [facebook/react-native#18174]
# Note

This issue was previously fixed / patched and it has returned. This is a duplicate of issue #17973. A fix can be found here #17983 

### Is this a bug report?
Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.9.1
  Yarn: Not Found
  npm: 5.5.1
  Watchman: Not Found
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.54.0 => 0.54.0

### Steps to Reproduce

1. Initiate a new React Native project using `react-native init projectName`
2. Run the command `react-native run-ios --device deviceName`

### Expected Behavior

The app should have launched on my physical device. Additionally, if I already have an instance of Metro Bundler running using `react-native start`, it should just hook into that one and use that.

### Actual Behavior

Metro Bundler opens and complains that `Metro Bundler can't listen on port undefined`. It then prompts the user to hit enter because the process has terminated. I've run into other random errors too. I've included one of those here as well.

[Metro Bundler error 1](https://i.imgur.com/SuPoZ8H.png)
[Metro Bundler error 2](https://i.imgur.com/3JTbYbb.png)

Additionally, there is a lot of output in my main terminal about the Xcode build failing. I can include the full output in a comment below if requested.

[Build error 1](https://i.imgur.com/SIWdahw.png)
[Build error 2](https://i.imgur.com/znhf8PW.png)

Even if I try running an instance of Metro Bundler using `react-native start` before running `react-native run-ios --device deviceName`, it just starts a new instance in a new terminal window.

### Reproducible Demo

You can reproduce this with a brand new project created using `react-native init projectName`.

**Comment by hramos** [comment]
Fixed in f8fee0a631d77313d7cb5e65a3dd04a5a8ba3d03 and should land with v0.55.
