### ISSUE TITLE
Modal component does not support SafeAreaView bottom margin

### ISSUE THREAD

**Issue by LutherBaker** [facebook/react-native#18177]
`SafeAreaView` bottom margin is not honored inside of a `Modal` on an iPhone X.

### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 9.7.1
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.1 Build version 9B55
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.3 => 0.53.3

### Expected Behavior

On an iPhone X, when a full screen component wrapped in a `SafeAreaView` renders correctly on the root view of the application, it should also render correctly when used inside of a `Modal`.

### Actual Behavior

On an iPhone X, a full screen component wrapped in a `SafeAreaView` renders correctly on the root view of the application **but** it does not render correctly when used inside of a `Modal`.

Specifically, the HEADER margin is present but the FOOTER margin is missing. The full screen component goes to the bottom edge of the iPhone X (simulator).

### Steps to Reproduce

1. Run the Snack on an iPhone X simulator
2. Find `render()` and note the two options (one with modal, one not)
3. Comment the options appropriately and see the issue
4. Remember, you need to run this on an iPhone X to see the problem

https://snack.expo.io/@lutherbaker/modal---safeareaview

**Comment by LutherBaker** [comment]
_`SafeAreaView` bottom margin is not being honored in a `Modal`_

When components wrapped in `SafeAreaView` are rendered to the root view:

<img width="320" alt="iphonex-root" src="https://user-images.githubusercontent.com/144541/36939387-abcecc74-1ef5-11e8-9e3f-bf3da0bf4d1e.png">

When (the same) components wrapped in `SafeAreaView` are provided to a `Modal`:

<img width="334" alt="iphonex-modal" src="https://user-images.githubusercontent.com/144541/36939396-d0fd21da-1ef5-11e8-877c-fd8d24b67511.png">

**Comment by LutherBaker** [comment]
I upgraded to React Native 54.0 but the provided snack demonstration still holds. The bottom safe area margin is not honored within a `Modal`.

Environment:
  OS: macOS Sierra 10.12.6
  Node: 9.7.1
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.1 Build version 9B55
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.2.0 => 16.2.0
  react-native: 0.54.0 => 0.54.0

**Comment by MrGurns** [comment]
Subscribing

**Comment by ChrisJVoss** [comment]
I have the same issue. Modal overlays only the bottom SafeAreaView.

**Comment by damikdk** [comment]
You can use SafeAreaView from react-navigation. It works for me

`import { SafeAreaView } from 'react-navigation';`

**Comment by hyungtae3713** [comment]
it works for me thanks!

**Comment by zhanggeyi** [comment]
"SafeAreaView bottom margin is not being honored in a Modal" is still bothering me （react-native: 0.55.4）

**Comment by AlexanderPodvoyski** [comment]
Hi, guys. @damikdk, @hyungtae3713 
We can use [react-native-safe-area-view](https://github.com/react-community/)
instead of `react-navigation`. Because `react-native-safe-area-view` package is used [inside](https://github.com/react-navigation/react-navigation/blob/73c76f1e4bbb015581eaae79a22e0076615ef392/src/react-navigation.js#L126) `react-navigation`.

**Comment by bhardman1986** [comment]
Just as an update as of v 0.57.1 the issue still exists.

**Comment by erickjth** [comment]
I am having the same issue in 0.56.

**Comment by levibuzolic** [comment]
Still exists in `0.57.x`, here's an updated Snack with a toggle to show the behaviour of in/out of a modal without needing to be edited: https://snack.expo.io/@levibuzolic/modal---safeareaview

**Comment by alessiocancian** [comment]
For modals or absolute positioned views use SafeAreaView from react-navigation (instead of react-native), like mentioned here:
https://medium.com/@wcandillon/if-you-are-working-within-a-modal-component-in-the-case-of-an-actionsheet-for-instance-6231c0815eb4

**Comment by alessiocancian** [comment]
As said by @AlexanderPodvoyski for modals or absolute positioned views you can use SafeAreaView from react-navigation instead of the one imported from react-native, which doesn't work.
https://medium.com/@wcandillon/if-you-are-working-within-a-modal-component-in-the-case-of-an-actionsheet-for-instance-6231c0815eb4

**Comment by alessiocancian** [comment]
@bhardman1986 @erickjth @levibuzolic for modals and absolute positioned views use SafeAreaView from react-navigation (instead of react-native) like said before

**Comment by amardeepranu** [comment]
Having the same issue here

**Comment by elelad** [comment]
I had the same problem on 0.58.4
I think it's a simple fix to [Modal.js](https://github.com/facebook/react-native/blob/ef3c053d1bc39a23292ed2f5c01fc65d951f9f93/Libraries/Modal/Modal.js) file.

Use SafeAreaView instead of View.. I opened PR.

**Comment by alvarotala** [comment]
still a thing..

**Comment by michalchudziak** [comment]
It works correctly with `emulateUnlessSupported` property. Without it, it's still broken.

**Comment by cjpete** [comment]
Is there a recommended workaround for this? `react-native-safe-area-view` has some issues, and doesn't seem to be a straight replacement.

**Comment by nathggns** [comment]
This bug 100% still exists and is over a year old. Has anything been done on addressing this? 

@michalchudziak what is the emulateUnlessSupported property?

**Comment by tncbbthositg** [comment]
What version of react-navigation's SafeAreaView fixed it for you guys?  It's still broken for me with react-native's SafeAreaView and react-navigation's.

**Comment by oxy88** [comment]
Is there any way I can use SafeAreaView with Modal ?

**Comment by ericlewis** [comment]
Looking at this, and `setSafeAreaInsets` is being called often, without all of the actual values. I.e. only top value is returned, only bottom value is returned, multiple times. Doing this:
```
safeAreaInsets.bottom = safeAreaInsets.bottom == 0 ? safeAreaInsets.top : safeAreaInsets.bottom;
```

appears to fix the problem without anything weird, but seems like a hack. Will open a PR anyway.

**Comment by clanwce** [comment]
Still having issue with this.. Neither SafeAreaView from React Native nor the one from react-navigation is working for me.

**Comment by zhongwuzw** [comment]
Anyone can try https://github.com/facebook/react-native/pull/25150?

**Comment by adimshev** [comment]
Still not working (RN 0.59.9)

**Comment by nathggns** [comment]
We fixed this by using https://github.com/react-native-community/react-native-safe-area-view

**Comment by zhongwuzw** [comment]
@adimshev Hey, 0.59.9 don't apply the patch, you can cherry pick #25150.

**Comment by adimshev** [comment]
Me too, but I want to use native SafeAreaView.

**Comment by adimshev** [comment]
Is it applied in 0.59.10 ?

**Comment by zhongwuzw** [comment]
Still not, only in `master` branch and under test.

**Comment by adimshev** [comment]
Thank you!

And what about forceInset in native realization? Can we hope?

**Comment by yeong0809** [comment]
it's working now. just put SafeAreaView in the Modal.

By using
import { SafeAreaView } from "react-native";
import RNModal from "react-native-modal";

**Comment by caphun** [comment]
I have an older version of ReactNative so got it to work like this:

```
import {SafeAreaView} from 'react-navigation'
...
<Modal>
  <SafeAreaView>
    ...
  </SafeAreaView>
</Modal>
```

Using:
- react-native v0.59.10
- react-navigation v3.11.1
