### ISSUE TITLE
help me plz

### ISSUE THREAD

**Issue by bawhari** [facebook/react-native#18176]
Hi, I'm beginner on react native
And I encountered this error
...
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
...
 but I did not understand your solutions
  Please tell me more precisely

**Comment by chirag04** [comment]
@facebook-github-bot stack-overflow

**Comment by kelset** [comment]
It seems to me that you haven't followed the guide on how to run Android, please check [this section](https://facebook.github.io/react-native/docs/getting-started.html#preparing-the-android-device) of the documentation.

**Comment by bawhari** [comment]
Thaaaanks😍😍😍😍😍😍😍😍😍
