### ISSUE TITLE
TextInput in Android strange behavior

### ISSUE THREAD

**Issue by gekamikh** [facebook/react-native#18182]
I have some troubles with text input on Android. I have TextInput with the long default value. This Input placed inside View component with some width. Here the problem: On ios cutting text inside TextInput looks like: 
<img width="335" alt="2018-03-03 08 00 56" src="https://user-images.githubusercontent.com/18705338/36944721-b0d34c1c-1faa-11e8-9abc-f8779913683c.png">

 - It shows the beginning of the value and cut the end of the value. 

But on Android it strange: 
<img width="391" alt="2018-03-03 07 59 26" src="https://user-images.githubusercontent.com/18705338/36944725-c4a32df2-1faa-11e8-8f27-da46e48936a2.png">

 - it cuts the beginning of the value and shows only end.

How can I make Android behavior same as IOS? Or it's specific Android behavior?

Thank You!

### Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.4.0
  Yarn: Not Found
  npm: 4.6.1
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.0 => 0.52.0

### Component code

`
import React from 'react';
import { StyleSheet, Text, View, TextInput } from 'react-native';

export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <View style={styles.textInputContainer}>
          <TextInput
            style={styles.textInput}
            value={'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.'}
            underlineColorAndroid={'transparent'}
          />
        </View>
      </View>
    );
  }
}

const styles = StyleSheet.create({
    container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  textInputContainer: {
    width: 200
  },
  textInput: {
    width: 200,
    borderWidth: 1,
    padding: 5
  }
});
`

**Comment by hramos** [comment]
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.
