### ISSUE TITLE
SafariSafeView not fully supported?

### ISSUE THREAD

**Issue by hkung77** [facebook/react-native#18193]
Environment
  react: 16.0.0
  react-native: 0.51.1

Expected Behavior:
Modals aren't affected by the SafariSafeView.
Even if I nest the SafariSafeView within the Modal component, the footer safe area is not displayed.

Components that are positioned absolute are not affected by SafariSafeView either. 

Expected Behavior:
SafariSafeView would persist when modals are present.
Positioned absolute components would be able to adjust from SafariSafeView.

**Comment by hackdie** [comment]
SafariSafeView?

**Comment by hramos** [comment]
Closing as it does not seem like a lot of time was spent writing up the issue, and it is not actionable at this point. Feel free to open a new one!
