### ISSUE TITLE
Build Failed In ubunutu.

### ISSUE THREAD

**Issue by hunnain** [facebook/react-native#18195]
Hi everyone,
Iam new in react-native but i have already use react.js im using UbuntuOS i have installed node jdk8 watchman and everything but i am getting error build failed i have install adb and my phone is connect and adb devices showing my phone list but i dont know why error comin
Error: com.android.ide.common.perocess.ProcessException: Failed to execute aapt
please help me

![screenshot from 2018-03-05 12-20-02](https://user-images.githubusercontent.com/24963356/36962005-9361cddc-206f-11e8-95ba-e2b8712e536d.png)

**Comment by hramos** [comment]
I'm sorry you're running into this. I highly advise updating your post to use the template. We need to know more - specific React Native version you're using, all the steps you've followed, and what you have tried in order to debug this yourself, for example.
