### ISSUE TITLE
Class RCTCxxModule was not exported. Did you forget to use RCT_EXPORT_MODULE()?

### ISSUE THREAD

**Issue by vshab** [facebook/react-native#18201]
There are warnings on app start:
```
2018-03-05 21:10:33.505 [warn][tid:main][RCTBridge.m:120] Class RCTCxxModule was not exported. Did you forget to use RCT_EXPORT_MODULE()?
2018-03-05 21:10:33.505169+0700 AwesomeProject[23617:4551316] Class RCTCxxModule was not exported. Did you forget to use RCT_EXPORT_MODULE()?
```

### Environment

```
Environment:
  OS: macOS High Sierra 10.13.3
  Node: 9.7.1
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: 0.54.0 => 0.54.0
```

### Expected Behavior

No warnings.

### Actual Behavior

There are warnings.

### Steps to Reproduce

1. `react-native init AwesomeProject`
2. Open `ios/AwesomeProject.xcodeproj`
3. Run the app and look at the output.
4. There will be warnings among first several lines.

I've tested several versions back (0.49) and the issue is there as well.

### Sample project

https://github.com/vshab/react-native-0.54-run-warning

**Comment by leoneparise** [comment]
I'm having the same issue when I upgraded to RN 0.54.

**Comment by leejones45** [comment]
I have this issue too.  If I reload the app in the simulator the warning goes away.

**Comment by isaachinman** [comment]
Same as @leejones45, getting this error after upgrading and only on first load.

**Comment by ntanduc2288** [comment]
Same with me 
react-native: 0.55.1

**Comment by janreyho** [comment]
Same with me
react-native: 0.55.2

**Comment by krewllobster** [comment]
Same here
react-native: 0.55.3

**Comment by mateoguzmana** [comment]
Same here with `react-native: 0.55.3`. Seems it happens after upgrade react-native to a version > 0.54.

**Comment by jmeyers91** [comment]
Also seeing this with `react-native 0.55.3`.

**Comment by mac-cain13** [comment]
This is a duplicate of #14806 

It's a harmless issue and you can ignore it, but quite confusing when you encounter it at first. Sadly it seems that nobody had the time to fix this yet.

**Comment by dooboolab** [comment]
Me too in RN@0.55

**Comment by lafayea** [comment]
me too

**Comment by hahtml** [comment]
me too

**Comment by gtsluk** [comment]
me too

**Comment by JacobbLu** [comment]
me too

**Comment by vgm8** [comment]
Any update on this issue? I know it's harmless but it still bothers me

**Comment by peacechen** [comment]
The message should be removed if it's really an issue.  Or FB needs to fix the condition that checks for whatever it is this is trying to check for.

**Comment by PierreBresson** [comment]
Any update on this?

When I want to run on device, I need to have RCTNetwork.xcodeproj and RCTWebSocket.xcodeproj manually linked but when I archive my app I have to delete both and add this code to my pod file and run pod install :

```
 pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'DevSupport',
    'CxxBridge',
    'RCTNetwork'
 ]
```

Otherwise I have errors. I also upgrade react-native to 55.3 from 51.

**Comment by peacechen** [comment]
Dear Mr bot,

This occurs with RN 0.55.3 and probably any newer version.

**Comment by dhei** [comment]
same with me in react-native@0.55.4

**Comment by frayhan32** [comment]
So what is the solution then ?

**Comment by charlot567** [comment]
@frayhan32 For now it's not the best solution, but to avoid the warning we can ignore it:

`import { YellowBox } from 'react-native';`
`YellowBox.ignoreWarnings(['Class RCTCxxModule']);`

**Comment by pstanton** [comment]
I haven't proven my theory but I just started getting this (and the "RCTImageLoader requires main queue setup") and the only change I made was to use YellowBox (as per prev comment) instead of the old `console.ignoredYellowBox` method.

**Comment by harrybui2804** [comment]
`pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'DevSupport',
    'CxxBridge',
    'CxxModule', #missing it
    'RCTNetwork'
 ]`

**Comment by ArthurInTheShell** [comment]
@charlot567 Note that same method is used to prevent the "isMounted(...) is deprecated" yellow box appear in 
https://github.com/react-navigation/react-navigation/issues/3956
They persist in react-native@0.55

**Comment by kelset** [comment]
This is a duplicate of #14806 so I'll close and lock this to avoid spam/useless comments
