### ISSUE TITLE
Border not scaling on Android 7.0

### ISSUE THREAD

**Issue by AyoCrazy** [facebook/react-native#18208]
Border not scaling on Android 7.0 in RN [0.51 - 0.54]

### Environment
Environment:
  OS: Windows 10
  Node: 9.5.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.54.0 => 0.54.0

### Expected Behavior
![image](https://user-images.githubusercontent.com/11539294/37012008-7f1bdcfa-212d-11e8-8a11-2cc0212c512f.png)

### Actual Behavior
![image](https://user-images.githubusercontent.com/11539294/37011567-b593f382-212b-11e8-9667-952a70d762fd.png)

### Steps to Reproduce
``` javascript
import React, {Component} from 'react';
import {StyleSheet, Text, View} from 'react-native';

export default class TestScreen extends Component {
    render() {
        return (
            <View style={styles.container}>
                <View style={[styles.bg, {transform: [{scale: 0.5}]}]}>
                    <Text style={styles.text}>Scaled by 0.5</Text>
                </View>
                <View style={[styles.bg, {transform: [{scale: 1}]}]}>
                    <Text style={styles.text}>Scaled by 1</Text>
                </View>
                <View style={[styles.bg, {transform: [{scale: 2}]}]}>
                    <Text style={styles.text}>Scaled by 2</Text>
                </View>
            </View>
        );
    }
}

const styles = StyleSheet.create({
    container: {
        alignItems: 'center',
        justifyContent: 'center',
        flex: 1
    },
    bg: {
        backgroundColor: 'orange',
        borderRadius: 5,
        borderWidth: 5,
        borderColor: 'red',
        width: 300,
        height: 80,
        margin: 30
    },
    text: {
        fontSize: 20
    }
});
```
### Be sure the android version is 7.0 and react-native version is above 0.51.
I just test it on Android 4.4, and it workd well, but not on Android 7.0.
I did not test on other Android devices.

**Comment by AyoCrazy** [comment]
@react-native-bot It appears in RN 0.51 - 0.54.

**Comment by filbertteo** [comment]
I'm encountering this issue as well. It's already been reported in https://github.com/facebook/react-native/issues/17224, but no one followed up with a fix, so it was closed by @react-native-bot. Hope someone will come up with a fix this time round.

**Comment by VinceBT** [comment]
Getting this issue on 0.54.0 too
Also, setting borderRadius to 99999 is not working anymore.

**Comment by Elf2707** [comment]
Having the same issue on RN 0.53.3 scale not working on devices and simulators with Android 7.0.0 if View has borderRadius property.

**Comment by Fsarmento** [comment]
I am still having this exact same issue on 0.56. it only happens when borderRadius is set to a value bigger than 0.

react: 16.4.1 => 16.4.1
react-native: 0.56.0 => 0.56.0

**Comment by nicollecastrog** [comment]
I'm also still having issues with this on 0.56, details [in this issue](https://github.com/facebook/react-native/issues/17224#issuecomment-421323647)

**Comment by yaronlevi** [comment]
Still seeing this in 0.55

When trying to make a round button with a pulse border, applying transfrom->scale to the border won't increase it by size. It will just move it as is. Very buggy.
