### ISSUE TITLE
Is it possible to use custom Activity instead of ReactFragmentActivity?

### ISSUE THREAD

**Issue by rusfearuth** [facebook/react-native#18215]
I need to extend activity from AppCompatActivity, but ReactNative has got only 2 variants of Activity (ReactActivity and ReactFragmentActivity). I try to use ReactActivityDelegate, but result is failure, because it has some protected methods which I can't use.

### Environment

```
Environment:
  OS: macOS High Sierra 10.13.3
  Node: 9.5.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.2.0 => 16.2.0
  react-native: ^0.53.0 => 0.53.3
```

### Expected Behavior

I want some construction for adding into existing Activity or construction extends existing Activity. I mean that we need to have mechanisme for using custom Activity instead of predefined.

### Actual Behavior

I can't use custom activity instead of predefined ReactNative.

### Steps to Reproduce

Nothing for reproduction.

**Comment by vovkasm** [comment]
You can also make your own delegate by inherit from `ReactActivityDelegate`, isn't it?

I recently simple copy & pasted logic from `ReactActivityDelegate` and `ReactActivity` to implement custom `ReactFragment` (only bad things is that my solution most probably will broke with future releases) :-(
May be we need to finish #12199 already... Refactoring that started in this PR will allow to do such things much easier.

**Comment by Plo4ox** [comment]
You should be able to use an AppCompatActivity with ReactNative by using your `ReactInstanceManager`.
By doing, 
in the `onPause` something like:
`if (reactInstanceManager != null) { reactInstanceManager.onHostPause(this); }`
in the `onDestroy` something like:
`if (reactInstanceManager != null) { reactInstanceManager.onHostDestroy(this); }`
int the `onResume` something like:
`if (reactInstanceManager != null) { reactInstanceManager.onHostResume(this, null); }`

@rusfearuth As @vovkasm said the idea is to look at the `ReactActivityDelegate` and `ReactActivity` ;)

I'm just thinking. Don't know but it may be great, as the `reactInstanceManager` may be used through all the app, to set these lines into an `Application.ActivityLifecycleCallbacks` if it is necessary.

**Comment by hramos** [comment]
It does not look like this has been reproduced in 0.54 or later. There has been no follow up from the author in over seven days, so we're closing this issue.
