### ISSUE TITLE
Issue in Remote Js Debugging

### ISSUE THREAD

**Issue by sathishu37** [facebook/react-native#18212]
Create a new project using the latest version of react native(react-native": "0.54.0) causing an error when in open Remote Js Debugger.
### Environment

(Environment:
  OS: Linux 4.10
  Node: 8.9.4
  Yarn: Not Found
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: 0.54.0 => 0.54.0

### Expected Behavior

When I connect with remote Debugger it opens normally

### Actual Behavior

When I connect with remote Debugger it shows following error in console.
 
![error](https://user-images.githubusercontent.com/30067630/37015760-097c52a2-212f-11e8-976d-9ca55b9e67b2.png)

**Comment by AdrianMrn** [comment]
Usually this Chrome Extension fixes this issue for me: https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi?hl=en

**Comment by MrZhang123** [comment]
I have same trouble in genymotion, when i run android app in genymotion, debug open http://10.0.3.2:8081/debugger-ui ,   not http://localhost:8081/debugger-ui , and the app can't connect debuger #18237

**Comment by rikur** [comment]
Copying in my short term solution from the duplicate issue:

Pulling in #17983 and reverting #17720 fixed remote JS debugging for me.

**Comment by ld-ucaya** [comment]
I get the same error with React Native 0.55.3 on a Honor 7A device with Android 8.0.0.
Though it seems to be ok when I connect to the debugger through http://localhost:8081 instead of http://<ip address>:8081

**Comment by aloifolia** [comment]
This happens for me with React Native 0.55.4. Why was this issue closed?

**Comment by thunderclap1030** [comment]
If you use gennymotion, you need setting in debug server host & port mapping with ipv4 your computer, you can explore it in **Dev Settings** inside menu control device.
Example find ip device  for mac : ifconfig -> inet 192.168.1.6
