### ISSUE TITLE
NullPointerException:tempt to invoke virtual method 'android.graphics.drawable.Drawable android.graphics.drawable.Drawable$ConstantState.newDrawable(android.content.res.Resources)' 

### ISSUE THREAD

**Issue by sksahil030** [facebook/react-native#18214]
(Describe your issue in detail.)

### Environment

react-native 0.53.3
![screenshot_1520320748](https://user-images.githubusercontent.com/13555404/37019654-1f136258-213f-11e8-8578-357fc0844c83.png)

**Comment by hramos** [comment]
Closing due to lack of sufficient details. Can you take a look at the template and make sure to provide all the details when opening a new issue?

**Comment by ahmaddehnavi** [comment]
don't set 'underlineColorAndroid' props to any TextInput and remove all text input background by native styles.

goto android\app\src\main\res\values\styles.xml

change that like below :
<resources>

 

<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">

 

 <item name="android:editTextStyle">@style/AppEditTextStyle</item>

</style>

<style name="AppEditTextStyle" parent="@style/Widget.AppCompat.EditText">

 

 <item name="android:background">@android:colors/transparent</item>

</style>

</resources>
