### ISSUE TITLE
Earlier versioned documentation Guides serve latest documentation

### ISSUE THREAD

**Issue by ajwhite** [facebook/react-native#18232]
Earlier versions of documentation for earlier React Native distributions can be accessed via https://facebook.github.io/react-native/versions.html

After documentation site redesign, it looks like the Guides documentation is serving the latest version, even if you're browsing an earlier version. 

For example, take `0.27`, this dates back to June 2016. 

Viewing the Animations Guide documentation, https://facebook.github.io/react-native/docs/0.27/animations.html, it links to content that didn't exist in 2016, such as this 2017blog post: http://facebook.github.io/react-native/blog/2017/02/14/using-native-driver-for-animated.html

These guides still exist in their original form in https://github.com/facebook/react-native/tree/0.27-stable/docs. **Can we serve earlier version's corresponding Guides?**

---

Component/Module API documentation is serving as expected. Example:
- `0.53`: https://facebook.github.io/react-native/docs/0.53/text.html
- `0.27`: https://facebook.github.io/react-native/docs/0.27/text.html

**Comment by hramos** [comment]
This is intentional. Guides are considered "unversioned", save for a few exceptions (CocoaPods instructions varied across a few recent versions).

Closing as documentation issues are tracked in github.com/facebook/react-native-website these days.
