### ISSUE TITLE
'72 duplicate symbols for architecture armv7' error when execute [Product] => [Archive] in Xcode

### ISSUE THREAD

**Issue by IveHD** [facebook/react-native#18239]
There are an error when I execute [Product] => [Archive] in Xcode;

### Environment

react-native@0.53.0   with pod installed 'react-native-amap3d'、'react-native-cookie';

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

Execute [Product] => [Archive] in Xcode;
![image](https://user-images.githubusercontent.com/17447867/37072936-daa74db2-21fe-11e8-992d-b586b1dfa907.png)

### Steps to Reproduce

(Link to Snack, or steps to reproduce.)

**Comment by IveHD** [comment]
I think i have fixed it.  It's because I have installed 'react-native-amap3d' via Pod. The error will be fixed  if I remove libRTCBlob.a and libRTCWebSocket.a from link binary with libraries.

**Comment by kelset** [comment]
Probably you have duplicate imports.
