### ISSUE TITLE
onPress event does not always fire, while onPressIn and onPressOut work fine

### ISSUE THREAD

**Issue by nxz91** [facebook/react-native#18235]
### Environment
Environment:
  OS: macOS High Sierra 10.13.3
  Node: 6.10.0
  Yarn: 1.3.2
  npm: 3.10.10
  Watchman: Not Found
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 1.5 AI-141.2456560

Packages: (wanted => installed)
  react: ^16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: 0.54.0 => 0.54.0

### Expected Behavior

When I press a collapsed item (TouchableWithoutFeedback or TouchableHighlight) in the list, or when I press above or below an expanded item, the `onPress` event should get fired at all times, resulting in the item expanding or collapsing. At the same time, it becomes a horizontal ScrollView and scrolling on the wrapping vertical ScrollView gets disabled.

### Actual Behavior

When I press a collapsed item in the list, or when I press above or below an expanded item, the `onPress` event only gets fired occasionally, while `onPressIn` and `onPressOut` always fire. The issue was not reproducible in the simulator, but only on the actual device as well as in the Expo Snack that is attached.

Feels super weird :-)

### Steps to Reproduce

https://snack.expo.io/@leonard91/bug-report

**Comment by nxz91** [comment]
Someone else seems to have had the issue before as well: https://github.com/facebook/react-native/issues/17577 I tried using ugly workarounds with onPressIn or onPressOut as well, but I could not make it work reliably as well.

As opposed to the poster of #17577, the first touch does not always work for me.

I was on 0.52.0 previously, and upgraded to see if it solves the issue. So the issue already existed back then.

**Comment by dlowder-salesforce** [comment]
@nxz91 just curious, did you try adding `removeClippedSubviews={false}` to your ScrollView?

**Comment by nxz91** [comment]
@dlowder-salesforce did it now, but that doesn't work either (see Expo Snack).

**Comment by kadoshms** [comment]
I can also confirm this issue.
In my case, I have a `SectionList` and a `TouchableOpacity` above it (inside a fixed header), and `onPress` is completly ignored while scrolling, while `onPressIn` works.

**Comment by jaychenjun** [comment]
Same issue, and I am not even in the list, just a regular button on header, sometimes onPress() won't fire, onPressIn and out always fire though.

And I noticed the issue only happens on the left side, where also triggers a swipe back gesture, maybe has something to do with PanResponder??
