### ISSUE TITLE
[Image] how to load animated gif from local images

### ISSUE THREAD

**Issue by magicismight** [facebook/react-native#1823]
I have tried this
`<Image source={{uri: 'load.gif'}} style={{height: 40, width: 40}} />`
but it will throw an exception in RCTGIFImage.m
`<Error>: ImageIO: CGImageSourceGetType image source parameter is nil`

And `source={require('image!load')}` didn\`t work either.

I have put `load.gif` in the imageset.

**Comment by jhabdas** [comment]
@magicismight How'd you manage to get a `gif` into an an *Image Set*? Xcode 7 won't allow me to do it.

**Comment by ide** [comment]
You can hack the JSON files yourself (it's easy) in xcassets.

**Comment by jhabdas** [comment]
Thanks for the info and all your hard work @ide. I'm doing a tiled, animated background image and [decided to go](https://github.com/jhabdas/SmartphoneSymphony/blob/master/src/components/WebView.js) with a `WebView` as shown:

![screen shot 2015-09-21 at 10 00 47 pm](https://cloud.githubusercontent.com/assets/440298/10010240/dd3f003e-60ad-11e5-9426-5326a52a7a36.png)

I have yet to try [FLAnimatedImage](https://github.com/Flipboard/FLAnimatedImage), though I was happy to see someone mention it in a recent issue.

**Comment by marcshilling** [comment]
Local, animated gifs used to work fine for me within an `<Image>` tag before upgrading to 0.11.

Now, `<Image style={{width: 29, height: 13}} source={{uri: 'loader.gif'}} />` just displays the static image (does not animate). What happened?

**Comment by jrichardlai** [comment]
Same things is happening to me gif were working with `source={{uri: 'loader.gif'}}`, now they don't animate either.

**Comment by mattmo** [comment]
We're seeing something similar. Was working fine with 0.8. We just updated to 0.12 and none of our local gifs animate. They do work fine if we load them remote (from a webserver). cc: @brentvatne

**Comment by mattmo** [comment]
Interestingly gifs start working again in 0.13. Haven't been able to track down what change fixed it. Note we're only working on iOS at the moment.

**Comment by christopherdro** [comment]
Animated gif images are supported using the new asset system that was introduced in version 0.14.
