### ISSUE TITLE
the last version can't debug in Genymotion

### ISSUE THREAD

**Issue by MrZhang123** [facebook/react-native#18237]
## Describe

I run android app in genymotion , debug will open `http://10.0.3.2:8081`, not `localhost:8081`,  and app can't connect 10.0.3.2 , but in devices, it work well ,how to set let debug open localhost not 10.0.3.2 in genymotion? 

## Environment

react native : 0.54
genymotion: 2.12.0
macOS: 10.13.3

**Comment by ThaJay** [comment]
same with normal Android emulator.
When I click `Debug JS Remotely` it opens chrome at `http://10.0.2.2:8081/debugger-ui` and says "This site can’t be reached" with a connection timeout.

**Comment by rikur** [comment]
+1, the debugger no longer uses xip.io but rather tries to connect to localhost:8081 and fails. It seems to also crash my app after I dismiss the error.
