### ISSUE TITLE
Can one android app embed two different version on React-Native ?

### ISSUE THREAD

**Issue by wangxiexe** [facebook/react-native#18246]
(Describe your issue in detail.)

### Environment

We have an android app with some parts already been built with an old version of react native, 
now we are going to have some new features built with the latest version of react native, 

but as the old feature's maintainer is not available so we can not update it to RN latest.

So the question here is : can we embed two RN version in one android application ? 

Thanks a lot!

**Comment by kelset** [comment]
No.

**Comment by wangxiexe** [comment]
Thanks @kelset
