### ISSUE TITLE
Auto Linking Fails for Android if build.gradle uses CRLF line endings

### ISSUE THREAD

**Issue by sujayjaju** [facebook/react-native#18244]
Native projects don't get added to build.gradle if the file uses CRLF (\r\n)

### Environment
Environment:
  OS: Windows 10
  Node: 8.9.4
  Yarn: 1.3.2
  npm: 5.2.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.0.0.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.50.4 => 0.50.4

### Expected Behavior

`compile project(':react-native-package-name')` should get added to `dependencies` in build.gradle

### Actual Behavior

MainApplication.java and settings.gradle get updated. But build.gradle does not.

### Steps to Reproduce
1. Change android/app/build.gradle file's line ending format to CRLF
2. Install an native package and run 'react-native link {native-package-name}

**Comment by hramos** [comment]
Have you reproduced this in 0.54?

**Comment by sujayjaju** [comment]
Yes. The issue is clear in the code base. Its a simple fix as per the PR.

**Comment by ssonalm** [comment]
build.gradle error expecting ''', found '\n' @ line.
what this error is???
