### ISSUE TITLE
Project won't build: missing directory. Help

### ISSUE THREAD

**Issue by AlexStickler** [facebook/react-native#18242]
Project will not build anymore after installing react-native-maps. Here's the error I got when trying to run my .xcworkspace in:

ld: warning: directory not found for option '-L/Users/name/Library/Developer/Xcode/DerivedData/project-cogbqkfqcwttvxaipnswqlsfewpq/Build/Products/Debug-iphonesimulator/React'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### Environment

  OS: macOS High Sierra 10.13.3
  Node: 8.9.1
  Yarn: 1.3.2
  npm: 5.7.1
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.0 => 0.53.0

### Expected Behavior

expected project to compile

### Actual Behavior

Getting error above. Any help would be much appreciated

**Comment by kelset** [comment]
It looks like you need to clean your XCode project & remove the folders inside `DerivedData`

**Comment by elmage** [comment]
I'm still having this issue. I've cleaned my project.

**Comment by joaom182** [comment]
@kelset you are using CocoaPods?

**Comment by mklmzrs** [comment]
Exactly same issue here. I've cleaned XCode project, deleted Derive Data Folder, deintegrated pods and re-install them but nothing work.

**Comment by fuzunspm** [comment]
i have the same issue

**Comment by smakosh** [comment]
Same here
