### ISSUE TITLE
[Metrics] How to fetch the download time for javascript？

### ISSUE THREAD

**Issue by dolphinux** [facebook/react-native#1825]
https://github.com/facebook/react-native/pull/1173

I want to get the consume time for javascript download time，but I don't know how to got it？
@nicklockwood

**Comment by brentvatne** [comment]
@dolphinux - check out https://github.com/facebook/react-native/blob/60b56455c4b30cbd0cb29790a7751329576ae8d6/React/Base/RCTBatchedBridge.m#L268-L273 - notice that this is passed in to both `RCTPerformanceLogger` and `RCTProfile` - does that help?

**Comment by brentvatne** [comment]
Have a look at the Inspect Element tool, specifically in the Perf tab, that will have the data for you!
