### ISSUE TITLE
SafeAreaView backward support(ios 9 & 10)

### ISSUE THREAD

**Issue by sushantsaho** [facebook/react-native#18255]
I am using SafeAreaView in my project, its working fine in ios 11, But in ios 10 the content going behind Status bar, How to make SafeAreaView backward compatibility.

### Environment

OS: macOS High Sierra 10.13.1
  Node: 9.4.0
  Yarn: 1.3.2
  npm: 4.6.1
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.51.0 => 0.51.0

### Expected Behavior

SafeAreaView Should start its content after status bar

### Actual Behavior

The content going behind Status bar

### Steps to Reproduce

(Link to Snack, or steps to reproduce.)

**Comment by vovkasm** [comment]
See #17638

**Comment by bkDJ** [comment]
It's still a problem in RN 0.54, but according to [this](https://github.com/facebook/react-native/issues/17638#issuecomment-370512300), writing ios-only version-specific code is a reasonable workaround to SafeAreaView not always being safe.

**Comment by wcandillon** [comment]
The stale tag on this issue can be removed
