### ISSUE TITLE
TouchableWithoutFeedback doesn't support styling

### ISSUE THREAD

**Issue by TheDutchCoder** [facebook/react-native#18257]
`TouchableWithoutFeedback` doesn't support styling on itself, which is odd as all other touchables do support styling. This leads to unexpected behaviour.

### Expected Behavior

`TouchableWithoutFeedback` to take styles.

### Actual Behavior

`TouchableWithoutFeedback` does not take in any styles.

### Steps to Reproduce

Snack: https://snack.expo.io/BJHqfjpOf
Here you can see that the `TouchableWithoutFeedback` component doesn't get styled properly. It works when the styling is applied to the child View, but this isn't always desirable.

The `TouchableOpacity` on the other hand styles fine.

One reason to use `TouchableWithoutFeedback` for example would be a background overlay where you want to hide the overlay on pressing the background.

Currently you have to use `TouchableOpacity` with `activeOpacity={1}` to mimic the desired behaviour.

**Comment by TheDutchCoder** [comment]
@react-native-bot this issue contained enough information and a Snack.

Would eb great if a team member could reply to this and open it up again, it's a real bug.

**Comment by NelGarbuzova** [comment]
It would be great to implement style prop for TouchableWithoutFeedback like the others (TouchableHighlight and TouchableOpacity).

**Comment by valensto** [comment]
@ysthedood Hey, you can make a View with your style under TouchableWithoutFeedback.
