### ISSUE TITLE
Extra Space showing on top of keyboard

### ISSUE THREAD

**Issue by sushantsaho** [facebook/react-native#18271]
While using SafeAreaView in iPhoneX, There is a extra space on top of keyboard

### Environment

OS: macOS High Sierra 10.13.1
  Node: 9.4.0
  Yarn: 1.3.2
  npm: 4.6.1
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.51.0 => 0.51.0

### Expected Behavior

Extra space should not not be there on Top of keyboard.

### Actual Behavior

Keyboard has extra space
![simulator screen shot - iphone x - 2018-03-08 at 15 42 13](https://user-images.githubusercontent.com/35450162/37145761-c1b5af80-22e7-11e8-8841-1cd3565ae44b.png)

### Steps to Reproduce

(Link to Snack, or steps to reproduce.)

**Comment by catherinepricillas** [comment]
hi, do you find any solution to this problem? I'm currently dealing with same issue @b4stien @sushantsaho
