### ISSUE TITLE
Facebook Log In/ Sign up stopped work in IOS after updating react-native-fbsdk to 0.7.0

### ISSUE THREAD

**Issue by Luckygirlllll** [facebook/react-native#18276]
Facebook Log In/ Sign up stopped work in IOS after updating react-native-fbsdk to 0.7.0, I see just empty screen, no errors, no warnings, just empty screen and nothing going on after that 
 

### Environment
react-native-cli: 2.0.1
react-native: 0.47.2

### Expected Behavior

Facebook Log In/ Sign up should works 

### Actual Behavior

Show empty Facebook screen after clicking button Continue in Log in/Sign up, no errors, in Android works fine 

### Steps to Reproduce

Upgrade  react-native-fbsdk to 0.7.0, test on IOS

**Comment by AutomaticWaffle** [comment]
Quick question: what is the version of the Facebook SDK for iOS?

Perhaps maybe try updating the `Facebook SDK for iOS` to either `4.26.0` or `4.31.1`?
And then updating the `Framework Search Paths` to point to the updated one and that should fix it.

Hope it helps!

**Comment by Luckygirlllll** [comment]
@AutomaticWaffle  Updating Facebook SDK to 4.31.1, solved my issue! Thanks!

**Comment by hramos** [comment]
Closing after seven days with no follow up from the author.
