### ISSUE TITLE
Inconsistent map.reverse function between Android and IOS when position styling absolute

### ISSUE THREAD

**Issue by isaaclem** [facebook/react-native#18284]
(Describe your issue in detail.)

### Environment

Expo Snack

### Expected Behavior

Items are showing in a correct order

### Actual Behavior

On IOS, everything seems fine where first item showing on screen.
On Android, second item being rendered as first item. Ordered wrongly.
![capture_ios](https://user-images.githubusercontent.com/32945572/37188387-c8b4bb58-2389-11e8-9983-79ec620c3ada.PNG)
![capture_andoird](https://user-images.githubusercontent.com/32945572/37188388-ca10f188-2389-11e8-9677-6965096afcb0.PNG)

### Steps to Reproduce

Refer to https://snack.expo.io/@cclem65/swipe

**Comment by hramos** [comment]
Closing after seven days with no follow up from the author.
