### ISSUE TITLE
[Navigator] How to make Navigator.SceneConfigs.FloatFromBottom look more native?

### ISSUE THREAD

**Issue by aksonov** [facebook/react-native#1828]
Currently some "pop" effect for background view ("previous" controller) exists, but native iOS UINavigationController doesn't have it during 'present' modal controller. How to disable it and make it more natural?

**Comment by rxb** [comment]
You can make your own SceneConfig or modify an existing one. You'd probably want to do something like I did with FloatFromRight to remove the scaling transition on the out:

```
// Scene Config
var Dimensions = require('Dimensions');
var PixelRatio = require('PixelRatio');
var buildStyleInterpolator = require('buildStyleInterpolator');
var FlatFloatFromRight = Object.assign({}, Navigator.SceneConfigs.FloatFromRight);
var FlatFadeToTheLeft = {
  transformTranslate: {
    from: {x: 0, y: 0, z: 0},
    to: {x: -Math.round(Dimensions.get('window').width * 0.3), y: 0, z: 0},
    min: 0,
    max: 1,
    type: 'linear',
    extrapolate: true,
    round: PixelRatio.get(),
  },
  opacity: {
    from: 1,
    to: 0.3,
    min: 0,
    max: 1,
    type: 'linear',
    extrapolate: false,
    round: 100,
  },
  translateX: {
    from: 0,
    to: -Math.round(Dimensions.get('window').width * 0.3),
    min: 0,
    max: 1,
    type: 'linear',
    extrapolate: true,
    round: PixelRatio.get(),
  },
};
FlatFloatFromRight.animationInterpolators.out = buildStyleInterpolator(FlatFadeToTheLeft);

```

So now, using FlatFloatFromRight in my Navigator configureScene prop works the same as FloatFromRight except that the view on the way out doesn't scale down, looking a little more iOS-standard.

**Comment by aksonov** [comment]
Thanks, it is better now, but still far from iOS native animations. Native animations are:
1) MUCH faster - do you know how to regulate speed?
2) No opacity change of 'background' view. New view just coming from bottom to top.
With reactNative I see 'background' view under new controller for few milliseconds, it looks quite weird... I've tried to remove 'opacity' at all but it didn't help. Also I've tried to change opacity.from to 0 to avoid seeing old background, but this way whole 'background' view is disappeared and then even not restored after returning to the previous controller...

**Comment by aksonov** [comment]
```
  opacity: {
    value: 1.0,
    type: 'constant',
  },
```

helped a little to avoid opacity change, but still i see 'transparent' new view until it animates.

**Comment by aksonov** [comment]
Thanks, helped, but speed still much lower than in native ones, do you know how to increase the speed of animations?

**Comment by DickyT** [comment]
@aksonov You can locate this file `Libraries/CustomComponents/Navigator/NavigatorSceneConfigs.js` and modify the `FadeToTheLeft` variable, you can see there is a property `transformScale`, and change the `to: {x: 0.95, y: 0.95, z: 1}` into `to: {x: 0.95, y: 1, z: 1}`, that solves everything
