### ISSUE TITLE
Modal onRequestClose won't fire on tvOS when in "Release" mode

### ISSUE THREAD

**Issue by psegalen** [facebook/react-native#18289]
Modal onRequestClose gets called on tvOS only for "Debug" scheme, for "Release" one it just doesn't seem to fire.
My app is behaving as expected when I'm in debug mode but not on an actual device installed via TestFlight.

### Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.9.4
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.1
  Xcode: Not Found
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: ^0.54.0 => 0.54.0

### Expected Behavior

onRequestClose should be called for the Modal component wether the scheme is "Debug" or "Release"

### Actual Behavior

onRequestClose isn't called for the Modal component when the scheme is "Release"

### Steps to Reproduce

Repo: https://github.com/psegalen/rn-tvos-modal-bug

Steps:

1. Get the code, run it in Apple TV simulator with XCode
2. If you press the touchable, the modal shows, if you press the Apple TV remote's menu button, it hides, it's ok but onRequestClose isn't called (you can see that because the state hasn't changed, isModalOpen remains true)
3. If you do the same test after switching the "Run" scheme to "Debug" in XCode, you'll see that the behaviour is correct since the state is correctly changed (isModalOpen become false after closing the modal)

**Comment by dlowder-salesforce** [comment]
I can reproduce this in a debug environment as well.  Looks like the native `setOnRequestClose` in `RCTModalHostView` isn't setting the required menu key gesture recognizer, because `_reactSubview` doesn't exist at the time this is called.  Investigating.

**Comment by dlowder-salesforce** [comment]
Tested this today by creating a new project with latest master code:

`react-native init --version=https://github.com/facebook/react-native rnTvosModalBug` 

and copying in the same code provided by @psegalen .

The issue is no longer reproducible for me.  @psegalen can you please try?

**Comment by psegalen** [comment]
Hi @dlowder-salesforce, I just tried what you described, the behaviour is still the same: isModalOpen is still true when pressing the remote Menu button.

**Comment by dlowder-salesforce** [comment]
@psegalen I made a repo to test this issue at https://github.com/dlowder-salesforce/rn-tvos-modal-bug .  I found a workaround -- if you include a TouchableHighlight in the modal that also resets isModalOpen, then the menu button works as expected.  See App.js in the above repo.  I'll investigate further to see why this might be happening.

**Comment by psegalen** [comment]
Thank you @dlowder-salesforce! I've worked around it another way: by doing "my own modal" with a fullscreen view over everything. 😄 
Closing

**Comment by euroclydon37** [comment]
I'm currently dealing with this, too. But when creating my own view that fades in, the nested Flatlists (a grid of videos) is still scrollable below the new "modal". Did you have any issues like this? I don't know how to disable the navigation below the modal.

**Comment by euroclydon37** [comment]
Actually, I just tested it, and after setting the visible prop to true (permanently), I'm still able to dismiss the modal with the menu button. So the normal "close on visible=false" behavior is being short circuited.
