### ISSUE TITLE
Expo Unfortunately Expo has stopped

### ISSUE THREAD

**Issue by zedukas** [facebook/react-native#18294]
import React from 'react';
import { Text, View, Button, Image, AppRegistry, TextInput, StyleSheet} from 'react-native';
import QRCode from 'react-qr-code';

export default class FirstScreen extends React.Component {
    state= {
        text: 'http://www.facebook.github.io/react-native/',
    };

    static navigationOptions = {
        tabBarLabel: 'QR Code',
        tabBarIcon: ({tintColor}) => (
            <Image
                source={require('../images/icon-qrcode.png')}
                style={{width:24, height:24, tintColor:'white'}}>
            </Image>
        ) 
    }

    render() {
        return (
         <View style={styles.container}>
            <TextInput 
                style={styles.input}
                onChangeText={(text) => this.setState({text: text})}
                value={this.state.text}
            />  
           <QRCode
               value={this.state.text}
               size={200}
               bgColor='purple'
               fgColor='white' />
        </View>
      );
    };
}

const styles = StyleSheet.create({
    container:{
        flex: 1,
        backgroundColor:'white',
        alignItems: 'center',
        justifyContent:'center'
    },

    input:{
        height:40,
        borderColor: 'gray',
        borderWidth:1,
        margin:10,
        borderRadius:5,
        padding:5,
    }
});

<img width="199" alt="untitled" src="https://user-images.githubusercontent.com/37214046/37207310-5a5084de-2394-11e8-96aa-e00fad166d01.png">

Already tested the suggestions given in command line 

<img width="958" alt="untitled2" src="https://user-images.githubusercontent.com/37214046/37207517-50234dc4-2395-11e8-9864-05a519d99215.png">

**Comment by hramos** [comment]
Hi! Thanks for reporting this. I appreciate that you have provided a sample of your code. However we need a bit more effort to be spent on writing up the bug report - a general guideline can be found in both our issue template as well as in the contribution guidelines, which are linked on the sidebar to the right.
