### ISSUE TITLE
watchman@4.9.0 start failed on MacOS high sierra 10.13.3

### ISSUE THREAD

**Issue by zhaiduo** [facebook/react-native#18297]
when I run 
> react-native start --reset-cache

The error like this:
> Metro Bundler ready.

>ERROR  spawn watchman EAGAIN
Loading dependency graph...Process terminated. Press <enter> to close the window

Try to ulimit to 1024, it seems not work.

### Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.4.0
  Yarn: 1.5.1
  npm: 5.3.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: ^0.54.0 => 0.54.0

**Comment by zhaiduo** [comment]
when change another project, react-native run-android, it seems works.
>Metro Bundler ready.

>Loading dependency graph, done.

**Comment by taoveweb** [comment]
Metro Bundler ready.

 ERROR  spawn watchman EAGAIN
Loading dependency graph...npm ERR! code ELIFECYCLE
npm ERR! errno 11
npm ERR! tuwei@0.0.1 start: `node node_modules/react-native/local-cli/cli.js start`
npm ERR! Exit status 11
npm ERR! 
npm ERR! Failed at the tuwei@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/taowei/.npm/_logs/2018-05-19T17_45_47_777Z-debug.log

**Comment by wenwangzhishang** [comment]
这个问题怎么解决的啊。也碰到了同样的问题

**Comment by NicWickman** [comment]
I'm also having this issue. Any ideas?
