### ISSUE TITLE
JSON.Stringify cannot seralize cyclic structures  using  canvas property ctx.drawImage()

### ISSUE THREAD

**Issue by yogeshR5** [facebook/react-native#18296]
Draw Roulette use Canvas property but it's not working on this line ctx.drawImage() 
I got Error like JSON.Stringify cannot serialize cyclic structures

### Environment

 OS: Linux 4.4
  Node: 6.13.1
  Yarn: 0.22
  npm: 3.10.10
  react: ^16.2.0 => 16.2.0
  react-native: 0.53.0 => 0.53.0

### Expected Behavior

Draw roulette use  Canvas properties in react native

### Actual Behavior

ctx.drawImage()  while using JSON.Stringify cannot seralize cyclic structures

### Steps to Reproduce

(Link to Snack, or steps to reproduce.)

https://stackoverflow.com/questions/49193572/react-native-json-stringify-cannot-serialize-cyclic-structure

**Comment by delavago** [comment]
ass holes
