### ISSUE TITLE
json parse error unrecognized token '<' react native 

### ISSUE THREAD

**Issue by youssefazouhri** [facebook/react-native#18293]
hey heros
i m really in a big trouble with fetching data from API rest asp.net using my localhost i change localhost to ip adress but not work 
`
import React, { Component } from 'react';
import {
  TextInput,
  StyleSheet,
  Text,
  View,
  TouchableOpacity,
  KeyboardAvoidingView,
  AsyncStorage,
  Platform

} from 'react-native';

import {StckNavigator} from 'react-navigation';

export default class Login extends Component {

 
  constructor(props) {
    super(props);
    
    this.state = {
        username:'',
        password:'',
    };
  }

componentDidMount(){

  this._loadInitialState().done();  
}

_loadInitialState = async () => {

  var  value = await AsyncStorage.getItem('users');
  if(value!==null){
    this.props.navigation.navigate('Profile');
  }
}

  render() {
    return (
   
       <View style = {styles.container}>
          <Text style = {styles.header}> LOGIN </Text>

          <TextInput 
             style = {styles.textInput} placeholder='Username'
             onChangeText={(username) => this.setState({username})}
             underlineColorAndroid = 'transparent'
          />

          <TextInput 
             style = {styles.textInput} placeholder='Password'
             onChangeText={(password) => this.setState({password})}
             underlineColorAndroid = 'transparent'
          />
          <TouchableOpacity
         style={styles.btn}
         onPress ={this.login}
          >
            <Text> Log in </Text>

          </TouchableOpacity>

       </View>
    
   
    );
  }

  login = ()=>{

    fetch('http://192.168.1.26:1543/api/Users',{
        
        method:'POST',
        header : {
      //   Accept: 'application/json',
        'Content-Type': 'application/json',
          
        },
        body : JSON.stringify({
           username : this.state.username,
           password : this.state.password,
        })

    })
  
 .then((response)=> response.json())

    .then((res) => {
      if(res.success === true){
        AsyncStorage.setItem('users',res.users);
        this.props.navigation.navigate('Profile');
      }
      else {
        alert('test test not work',res.message);
      }

    })

     .done();
  }
}

const styles = StyleSheet.create({
  
 wrapper :{

  flex : 1 ,
},
container: {
  flex: 1,
  justifyContent: 'center',
  alignItems: 'center',
  backgroundColor: '#2896d3',
  paddingLeft : 40,
 paddingRight: 40,
},
header: {
  fontSize: 24,
  marginBottom: 60,
  color : '#fff',
  fontWeight : 'bold',
},
textInput: {

  alignSelf: 'stretch',
  padding: 16,
  marginBottom : 20,
  backgroundColor:'#fff',
},
btn: {

  alignSelf: 'stretch',
  padding: 16,
  marginBottom : 20,
  alignItems : 'center',
  backgroundColor:'#01c853',
}

});

`

i do every things without any results but when i comment  '''  .then((response)=> response.json()) ''' that s work but without any data 
please i need your help ..

**Comment by drewacs** [comment]
This happen when you receive response from the server with HTML format (error) instead of JSON format correct response.

**Comment by akhilkumaramarneni** [comment]
> This happen when you receive response from the server with HTML format (error) instead of JSON format correct response.

then how to solve it same code working in IOS correctly but on android it is not
