### ISSUE TITLE
react-native link adds duplicated lines to ios project.pbxproj file

### ISSUE THREAD

**Issue by oyyq99999** [facebook/react-native#18295]
Say you link 2 or more native modules, it will result in a file with these lines or something similar, which is weird:

```
LIBRARY_SEARCH_PATHS = (
	"$(inherited)",
	"\"$(SRCROOT)/$(TARGET_NAME)\"",
	"\"$(SRCROOT)/$(TARGET_NAME)\"",
	"\"$(SRCROOT)/$(TARGET_NAME)\"",
	"\"$(SRCROOT)/$(TARGET_NAME)\"",
	"\"$(SRCROOT)/$(TARGET_NAME)\"",
);
```
### Environment

```
Environment:
  OS: macOS High Sierra 10.13.3
  Node: 9.7.1
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.0 => 0.52.0
```

### Expected Behavior

if the required line exists, don't add new duplicated lines

### Actual Behavior

it adds repeating lines

### Steps to Reproduce

just link 2 or more native modules

**Comment by oyyq99999** [comment]
I've tried with
```
Environment:
  OS: macOS High Sierra 10.13.3
  Node: 9.7.1
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: 0.54.0 => 0.54.0
```
It's still adding duplicated lines

**Comment by s-nel** [comment]
I'm experiencing the same issue on Mac High Sierra. Each time `react-native link` is used. Duplicate entries are created in several files.

**Comment by simonbuchan** [comment]
Sounds like the same thing I'm seeing on android, duplicate additions to `android/gradle.properties` and `.../MainApplication.java`.

**Comment by jiteshgupta1995** [comment]
+1. Same here. Occurring this issue for Android as well, in latest React-native v0.54 but not for older version. Adds duplicate lines in `android/build.gradle` and `MainApplication.java`.

**Comment by TakaGoto** [comment]
i'd like to work on this if its still available.

**Comment by hramos** [comment]
Feel free to work on it.

**Comment by hramos** [comment]
The command line tools have their own repository and issue tracker over at https://github.com/react-native-community/react-native-cli.

**Comment by saraervik** [comment]
I reported this issue in react-native-cli since I could not find that it had been reported over there

https://github.com/react-native-community/react-native-cli/issues/236
