### ISSUE TITLE
How to set textarea focus in react-native webview

### ISSUE THREAD

**Issue by TryImpossible** [facebook/react-native#18327]
I want to set textarea autoFoucs in react-native webview, but it doesn't work?
somebody know how to slove it ? please contact me， thanks!

### Environment

"react": "16.2.0",
"react-native": "0.54.0",

This is ReactNative code: 
<WebView
                    ref={ref => this.webView = ref}
                    automaticallyAdjustContentInsets={false}
                    style={{ width: this.mScreenWidth, flex: 1, backgroundColor: '#fff', marginTop: this._getSize(5), paddingHorizontal: this._getSize(16), paddingTop: this._getSize(5) }}
                    source={{ uri: 'http://localhost:8081/richEditor/richEditor.html' }}
                    javaScriptEnabled={true}
                    dataDetectorTypes='none'
                    startInLoadingState={true}
                    scrollEnabled={true} />

This is Html code: 
<body>
  <textarea id="textarea" autofocus="autofocus"></textarea>
  <script type="text/javascript" charset="utf-8">
    document.getElementById("textarea").focus();
  </script>
</body>

### Actual Behavior

![image](https://user-images.githubusercontent.com/23582577/37270720-d0078b3c-260a-11e8-93db-1e26f8af4d4f.png)

**Comment by asmakhalfallah2018** [comment]
Do you get the solution please ? @TryImpossible
