### ISSUE TITLE
[0.7] EXC_BAD_INSTRUCTION when pressing cmd+R

### ISSUE THREAD

**Issue by ilansas** [facebook/react-native#1833]
Hi, 

After almost a day of trying to update React-Native to 0.7 on my project, I finally had my app displayed on the simulator. But when I'm trying to refresh the app I'm getting this : 

    Thread 7: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)

on this line : 
    
    threadName = @(dispatch_queue_get_label(dispatch_get_current_queue()));

in the file : `RCTAssert.m`

Do you have any idea ? Thanks

**Comment by ilansas** [comment]
FYI : When using v0.6 (master) I'm getting the same problem...

**Comment by a2** [comment]
I have fixed this internally and the change will go out in tomorrow's sync.

**Comment by ilansas** [comment]
Ok great I'll wait for it
