### ISSUE TITLE
Unable to run application on API 16 device. Cannot read property 'length' of null.

### ISSUE THREAD

**Issue by JamesTheHacker** [facebook/react-native#18330]
### Environment

```
Environment:
  OS: macOS Sierra 10.12.6
  Node: 9.5.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: Not Found
  Xcode: Not Found
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.0 => 0.52.0
```

### Expected Behavior

I expect the example application to load on an Android device running API 16.

### Actual Behavior

I have created a demo application with `create-react-native-app`. The demo application is untouched. I am attempting to run my application a Samsung Galaxy S3 running `4.1.2` (API 16), but I am getting the following error after running `yarn run android`:

```
Error running adb: Error running app. Error: Activity not started, unable to resolve Intent { act=android.intent.action.VIEW dat=exp://192.168.0.10:19000 flg=0x10000000 }
(node:58131) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of null
    at /xdl/src/Android.js:88:18
    at Generator.next (<anonymous>)
    at step (/Users/spongebob/Projects/AwesomeProject/node_modules/xdl/build/Android.js:473:191)
    at /Users/spongebob/Projects/AwesomeProject/node_modules/xdl/build/Android.js:473:361
    at <anonymous>
(node:58131) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

My phone is connected and in development mode:

```
adb devices
List of devices attached
4790207223d13060    device
```

I had the same error when I ran with Genymotion, but I was able to solve it by creating an emulator that runs API 19. My problem is I need to be able to test apps on API 16 so I can't update this S3. I have a feeling this is related to API 16.

### Steps to Reproduce

1. Create a demo application: `create-react-native-app demo`
2. Change into directory: `cd demo`
3. Connect Android running `4.2.1` and ensure device is in development mode and shows up when running `adb devices`
4. Run `yarn run android`

You can also replace step 3 with an emulator running `4.2.1`. I get the same results with a Genymotion emulator running `4.2.1`.

If you need any more information I would be happy to provide.

**Comment by JamesJefferyUK** [comment]
I have updated to `0.54`. The same error occurs.

```
Environment:
  OS: macOS Sierra 10.12.6
  Node: 9.5.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: Not Found
  Xcode: Not Found
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.54.0 => 0.54.0
```
