### ISSUE TITLE
generate (un)signed apk

### ISSUE THREAD

**Issue by montao** [facebook/react-native#18342]
can we somehow generate an apk without the keystore for Android testing purposes? I don't think that I should be forced to create a keystore just for testing purposes. I have my app running with expo and would like it working with expo and try it out as a apk. I also think that the docs for the signed apk is insufficient - what is the procedure getting my development files into Android Studio and generating the apk?

**Comment by Lxxyx** [comment]
This question you can ask at StackOverflow. @react-native-bot stackoverflow

**Comment by chirag04** [comment]
@facebook-github-bot stack-overflow

**Comment by Lxxyx** [comment]
...
Maybe this will help you: https://stackoverflow.com/questions/16709848/build-unsigned-apk-file-with-android-studio
@montao
