### ISSUE TITLE
[Packager] Requiring a file with the .ios.js extension

### ISSUE THREAD

**Issue by avnerbarr** [facebook/react-native#1834]
The documentation is really bad here: 

https://facebook.github.io/react-native/docs/nativecomponentsios.html#content

I created a file - "CloseButton.ios.js" containing the JS code

In index.ios.js added the "require"
```
'use strict';

var React = require('react-native');
var CloseButton = require('./CloseButton');

var {
  AppRegistry,
  Image,
  ListView,
  StyleSheet,
  Text,
  View,
} = React;
```

But when it crashes with the red screen 

"Error: Requiring unknown module "./CloseButton". If you are sure the module is there, try restarting the packager.
 stack: 
  <unknown>       index.ios.bundle:1118
  require         index.ios.bundle:244
  applyWithGuard  index.ios.bundle:880
  require         index.ios.bundle:195
  <unknown>       index.ios.bundle:42255
 URL: http://localhost:8081/index.ios.bundle
 line: 203
 message: Requiring unknown module "./CloseButton". If you are sure the module is there, try restarting the packager."
2015-07-01 17:17:56.910 [info][tid:com.facebook.React.JavaScript] "Running application "ReactTesting" with appParams: {"rootTag":1,"initialProps":{}}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF"
2015-07-01 17:17:56.912 [error][tid:com.facebook.React.JavaScript] "Error: Invariant Violation: Application ReactTesting has not been registered. This is either due to a require() error during initialization or failure to call AppRegistry.registerComponent.
 stack: 
  runApplication          index.ios.bundle:36264
  jsCall                  index.ios.bundle:7313
  _callFunction           index.ios.bundle:7579
  <unknown>               index.ios.bundle:7608
  <unknown>               index.ios.bundle:7602
  perform                 index.ios.bundle:6135
  batchedUpdates          index.ios.bundle:13856
  batchedUpdates          index.ios.bundle:4678
  <unknown>               index.ios.bundle:7601
  applyWithErrorReporter  index.ios.bundle:7348
  guardReturn             index.ios.bundle:7370
  processBatch            index.ios.bundle:7600
 URL: http://localhost:8081/index.ios.bundle
 line: 1699
 message: Invariant Violation: Application ReactTesting has not been registered. This is either due to a require() error during initialization or failure to call AppRegistry.registerComponent."

**Comment by chirag04** [comment]
You should require like this i guess: ``var CloseButton = require('./CloseButton.ios.js');``

**Comment by avnerbarr** [comment]
Simple enough.

I wish the documentation had these little things!

Hours of work...

The examples don't have this syntax...

**Comment by chirag04** [comment]
This is more of a node.js thing which is out of scope of this project. Read more on the require system of node.js. Mind closing this issue?

**Comment by brentvatne** [comment]
@avnerbarr - I would leave out the `ios.js` extension and then require it exactly as you did. I'm not entirely sure about what the plan is for how to handle this with multiple platforms because the Android release isn't out yet, I had assumed that it would work in the same way that you did; internally React Native uses both `.ios.js` and `.android.js` extensions, and when `Image` is require'd for example, it will pick the correct one depending on the platform.

cc @amasad

**Comment by JonasJonny** [comment]
I am also using 
``var MainScreen = require('./MainScreen');``

Didn't you forget 
``module.exports = MainScreen;``
at the end of the file?

**Comment by avnerbarr** [comment]
```

var React = require('react-native');
var { requireNativeComponent } = React;
var RCTButton = requireNativeComponent('RCTButton', CloseButton);

class CloseButton extends React.Component {
  render() {
    return <RCTButton {...this.props} />;
  }
}

module.exports = CloseButton;

```
