### ISSUE TITLE
app crashes and kickout when textinput become empty (length ==0)

### ISSUE THREAD

**Issue by Arshiamidos** [facebook/react-native#18359]
### Environment
react-native-cli: 2.0.1
react-native: 0.53.0

### Expected Behavior
i want simply clear textinput with keyboard input
in simulator ios and andorid emulator it's fine 
but in real android devices it  crashes HUAWEI Y7 and other android devices that i tested i have this problem !!! 
### Actual Behavior
when clear textinput with keyboard backspace, app crashes and kickout 
it writes string as well but when clear text and text length become zero app crashes

**Comment by Arshiamidos** [comment]
seriously?!
can you hint me where the problem is in RN code?
i will update ASAP and report again

**Comment by Arshiamidos** [comment]
i catched this error 
```
error: patch failed: .flowconfig:51
Falling back to three-way merge...
Applied patch to '.flowconfig' cleanly.
error: android/app/src/main/AndroidManifest.xml: does not exist in index
git-upgrade WARN The upgrade process succeeded but there might be conflicts to be resolved. See above for the list of files that have merge conflicts.
git-upgrade info Upgrade done
```

**Comment by Arshiamidos** [comment]
you must close all IDE and close termial. just exit from debuging mode

**Comment by Arshiamidos** [comment]
now textinput corrected 
and you must init a new project

**Comment by hramos** [comment]
It does not look like this has been reproduced in 0.54 or later. There has been no follow up from the author in over seven days, so we're closing this issue.
