### ISSUE TITLE
React Native linking - Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by MayeuldP** [facebook/react-native#18353]
I m trying to build an app on macOS for iOS, and the build is indeed success, but then I got a red screen (see Actual behaviors concerning the error message).
I used Carthage for several libraries and thought maybe that my problem could come from the linking because when I run react-native link I got `everyhings is already linked`, and at the very end, this message : 
```
info Linking assets to ios project 
rnpm-install ERR! Something went wrong while linking. Error: Cannot read property 'value'
of undefined

```
I tried rm -rf node module, re starting Xcode...unlink, relink... But still got this problem

### Environment

```

Environment:
  OS:  macOS Sierra 10.12.6
  Node:  8.10.0
  Yarn:  1.5.1
  npm:  5.6.0
  Watchman:  Not Found
  Xcode:  Xcode 9.2 Build version 9C40b
  Android Studio:  Not Found

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: 0.49.3 => 0.49.3
```

### Expected Behavior

App launching... Just work..

### Actual Behavior
Build success
Red screen with this message : 
`this._nativeModule.addListener is not a function ... this._nativeModule.addListener is undefined
`
Thank for your help

**Comment by edward8628** [comment]
facebook chatbots just want to close all the issues without answering
