### ISSUE TITLE
Release APK fails immediately on launch (Version 0.54)

### ISSUE THREAD

**Issue by hardnett** [facebook/react-native#18357]
I have a web view app that is very straightforward. The iOS version is running perfectly. The android version runs perfectly in debug mode using the package server. However, the release version of the apk crashes immediately when launched. 

The errors I am getting from logcat are:

```
03-12 22:12:07.665 16051-16068/? E/AndroidRuntime: FATAL EXCEPTION: Thread-2
                                                   Process: com.gtcworx, PID: 16051
                                                   java.lang.RuntimeException: Unable to load script from assets 'index.android.bundle'. Make sure your bundle is packaged correctly or you're running a packager server.
                                                       at com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromAssets(Native Method)
                                                       at com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromAssets(CatalystInstanceImpl.java:216)
                                                       at com.facebook.react.bridge.JSBundleLoader$1.loadScript(JSBundleLoader.java:33)
                                                       at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:234)
                                                       at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1113)
                                                       at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:113)
                                                       at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:920)
                                                       at java.lang.Thread.run(Thread.java:764)
03-12 22:12:07.789 2055-2075/? E/ResourcesManager: failed to add asset path /data/app/com.google.android.videos-fSpP8T16jLfLPEk3Hl3pmw==/base.apk
03-12 22:12:07.790 2055-2075/? E/ResourcesManager: failed to add asset path /data/app/com.google.android.videos-fSpP8T16jLfLPEk3Hl3pmw==/base.apk
03-12 22:12:07.790 2055-2075/? E/ResourcesManager: failed to add asset path /data/app/com.google.android.videos-fSpP8T16jLfLPEk3Hl3pmw==/base.apk
03-12 22:12:07.794 2055-2075/? E/ResourcesManager: failed to add asset path /data/app/com.google.android.apps.docs.editors.slides-9EEF5YDNu3OKNBNwayfu9g==/base.apk
03-12 22:12:07.794 2055-2075/? E/ResourcesManager: failed to add asset path /data/app/com.google.android.apps.docs.editors.slides-9EEF5YDNu3OKNBNwayfu9g==/base.apk
03-12 22:12:07.794 2055-2075/? E/ResourcesManager: failed to add asset path /data/app/com.google.android.apps.docs.editors.slides-9EEF5YDNu3OKNBNwayfu9g==/base.apk
03-12 22:12:07.795 2055-2075/? E/ResourcesManager: failed to add asset path /data/app/com.google.android.contacts-2KRJls5awi4KQQ6cjkUQQA==/base.apk
03-12 22:12:07.795 2055-2075/? E/ResourcesManager: failed to add asset path /data/app/com.google.android.contacts-2KRJls5awi4KQQ6cjkUQQA==/base.apk
03-12 22:12:07.797 2055-2075/? E/ResourcesManager: failed to add asset path /data/app/com.google.android.dialer-1BN26SkEVNcra4NPGyK-nA==/base.apk
03-12 22:12:07.797 2055-2075/? E/ResourcesManager: failed to add asset path /data/app/com.google.android.dialer-1BN26SkEVNcra4NPGyK-nA==/base.apk
03-12 22:12:07.797 2055-2075/? E/ResourcesManager: failed to add asset path /data/app/com.google.android.dialer-1BN26SkEVNcra4NPGyK-nA==/base.apk
03-12 22:12:07.798 2055-2075/? E/ResourcesManager: failed to add asset path /data/app/com.gtcworx-XlyWECmWk-Pjfh6CE3jV4Q==/base.apk
03-12 22:12:07.799 2055-2075/? E/ResourcesManager: failed to add asset path /data/app/com.gtcworx-XlyWECmWk-Pjfh6CE3jV4Q==/base.apk
03-12 22:12:07.799 2055-2075/? E/ResourcesManager: failed to add asset path /data/app/com.gtcworx-XlyWECmWk-Pjfh6CE3jV4Q==/base.apk
03-12 22:12:07.799 2055-2075/? E/ResourcesManager: failed to add asset path /data/app/com.gtcworx-XlyWECmWk-Pjfh6CE3jV4Q==/base.apk
03-12 22:12:07.800 2055-2075/? E/ResourcesManager: failed to add asset path /data/app/com.gtcworx-XlyWECmWk-Pjfh6CE3jV4Q==/base.apk
03-12 22:12:07.805 2055-2075/? E/ResourcesManager: failed to add asset path /data/app/com.gtcworx-XlyWECmWk-Pjfh6CE3jV4Q==/base.apk
```

since this does not use the package server, I figured the problem is that the bundle is packaged incorrectly. However, I am not sure that I can do to fix the way the package is bundled.

I did some searches and noticed that this problem is caused the View.propTypes references. I followed the steps to see if there were any such references in my modules and there are not. There are only comments referring to the issue and explaining the patches put into place. 

I also found an article that suggested I check the name of the app in the index.js file and compare that with the name in the MainActivity. I checked those and they are identical. I also checked my package.json for the same name. 

I have also done several cleans of the project using Gradle.

 Thanks for any help that can be provided. 

### Environment

```
Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.8.1
  Yarn: 1.3.2
  npm: 5.4.2
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: ^16.2.0 => 16.2.0
  react-native: ^0.54.2 => 0.54.2
```

### Expected Behavior

I expected the app to launch and show the website in the webView. 

I am unable to reproduce the error in snack, but here is the link that shows how it should work: https://snack.expo.io/r1JzDYSFG

### Actual Behavior

dialog box shows up saying "app has stopped" and ask to open again. 

### Steps to Reproduce

1. Create a web view app
2. Build it using the versions of the libs I have above
3. Generate a signed release apk
4. Install release apk onto device
5. Run the app

**Comment by Lxxyx** [comment]
How did you pack the release version of App?
May be still running at dev mode?

**Comment by hardnett** [comment]
Im using Android Studio to generate the release version of the app. Its taking me through the same steps that I have using for Java-based Android apps without problems.

**Comment by alexmbp** [comment]
Have the same issue. I'm using Build -> Generate signing APK in android studio.

**Comment by hardnett** [comment]
I just updated to 0.54 which actually took me to 0.54.2 and I have the same result. 

my new react-native info dump:

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.8.1
  Yarn: 1.3.2
  npm: 5.4.2
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: ^16.2.0 => 16.2.0
  react-native: ^0.54.2 => 0.54.2

**Comment by alexmbp** [comment]
Well. It's working with
react-native run-android --variant=release
and with ./gradlew assembleRelease and configuring signing.
Also I've updated gradle and should set android.enableAapt2=false.
Probably issue connected with gradle update.

**Comment by hardnett** [comment]
Thanks that definitely worked. I did not use the --variant=release, but the command-line process works fine. It may be gradle, but it appears that Android Studio is using the same commands.

**Comment by abrajeethan** [comment]
This issue is still present! However the fix is setting android.enableAapt2=false and the using "Generate signed APK" command. If react-native is boasting of supporting both frameworks then they should take care of announcing these issue fixes too.

**Comment by hardnett** [comment]
Wow. I’ll

**Comment by hardnett** [comment]
Sorry. Hit the wrong button. I’m reopening this until it’s fixed.

**Comment by deepeshkarkee** [comment]
Please note! RN 0.54.0 - 0.54.2 has issue with fetch call. It returns Blob, instead of returning the InitBody as string. I suggest you downgrade your RN to any version between 0.51 to 0.53

**Comment by doertli** [comment]
@deepeshkarkee do you know if 0.55RC have fixed the fetch issues?

**Comment by deepeshkarkee** [comment]
@doertli: I haven't tried RN0.55 RC.
I am thinking of avoiding reactive native upgrade until they release .60 or a stable release of the series. 
Reason: they are planning to deprecate ComponentWillMount(), and are suggesting to use CompinentDidMount().

**Comment by puckey** [comment]
Experiencing the same issue with RN 0.55.3

**Comment by wedneyyuri** [comment]
I'm using version `0.55.4` and it's not working, currently using a hacky workaround to use Android Studio:

- `cd android && ./gradlew assembleRelease` (create the bundle)
- Android Studio -> Build -> Generate Signed APK (generate a signed apk)

Another option is generating signed apks using command line as suggested by @alexmbp. [This procedure is described here](https://facebook.github.io/react-native/docs/signed-apk-android.html).

**Comment by gderaco** [comment]
Add this lines

`project.ext.react = [
        entryFile: "index.js",
        bundleAssetName: "index.bundle",
        bundleInAlpha: true,
        bundleInBeta: true
]`

before
`apply from: "../../node_modules/react-native/react.gradle"` in build.gradle

**Comment by arambrosius** [comment]
I am having the same issue. Works fine in debug but once I release the APK it crashes on load. Here are my packages. 
	"dependencies": { 

		"axios": "^0.18.0",
		"react": "16.4.1",
		"react-native": "0.55.4",
		"react-native-elements": "^0.19.1",
		"react-native-material-dropdown": "^0.11.1",
		"react-native-push-notification": "^3.0.2",
		"react-native-swipeout": "^2.3.3",
		"react-native-vector-icons": "^4.6.0",
		"react-navigation": "^2.6.2",
		"react-redux": "^5.0.7",
		"redux": "^4.0.0",
		"redux-axios-middleware": "^4.0.0",
		"redux-thunk": "^2.3.0",
		"round-to": "^3.0.0"
	},
	"devDependencies": {
		"babel-jest": "23.2.0",
		"babel-preset-react-native": "^4.0.0",
		"jest": "23.3.0",
		"react-test-renderer": "16.4.1"
	},
	"jest": {
		"preset": "react-native"
	}

I see info on downgrading react-native but nothing has worked for me. My app is in production and need help asap. Any ideas?

**Comment by brayanL** [comment]
I have the same problem @react-native-bot , your solution is not feasible to change the native version of react, which requires making many changes in the project: As you could verify that the generated apk is correct, there is some way. Please help us thanks

**Comment by mowbell** [comment]
Maybe, It can help 
It's working for me
if in your**graddle.properties** you have:
`org.gradle.configureondemand=true`
Task for assemble JS and Assets is not running

If it's removed, all work as expected

**Comment by AliRadmanesh** [comment]
I have the same issue. and it's related to this line in android/gradle.properties: (as @mowbell mentioned)

`org.gradle.configureondemand=true`

after deleting this line, everything works fine!

**Comment by bmaehr** [comment]
I have the same problem with latest gradle (4.10.1) and latest react-native (0.57). I'm building without Android Studio, just from the command line with `gradlew clean assembleRelease`.

The apk is created, but in `assets` the file `index.android.bundle` is missing. It is created during build to `build\intermediates\assets\release` and `build\generated\assets\react\release` but not included into the apk.

I have tried several things like setting `org.gradle.configureondemand=false` even if it was missing, adding `bundleInRelease: true`, manually setting `main.assets.srcDirs` to the directories above, turning of `org.gradle.parallel`, changing the order of entries in build.gradle, ... Nothing worked.

An other thing I'm wondering: After the apk is already created still a lot of tasks buliding react-nativ projects are running. I would expect building the apk must be the last step.

**Comment by Anujmoglix** [comment]
> react-native run-android --variant=release



> Well. It's working with
> react-native run-android --variant=release
> and with ./gradlew assembleRelease and configuring signing.
> Also I've updated gradle and should set android.enableAapt2=false.
> Probably issue connected with gradle update.

HI , on which file to write  android.enableAapt2 ?

**Comment by sturmenta** [comment]
Same Problem `react-native: 0.56.0`

**Comment by Anujmoglix** [comment]
nothing is working , it is very annoying ,

**Comment by Zkog** [comment]
@bhardman1986 You are my hero!

**Comment by danielshin** [comment]
@edilaic #21409 workaround seems to only work when generating an apk, but not when generating an android app bundle

**Comment by Blackfaded** [comment]
@bhardman1986 Thanks! That was my issue!

**Comment by Anujmoglix** [comment]
Task 'installRelease' not found in root project 'xyz'. Some candidates are: 'uninstallRelease'.

I am getting this on running this command "react-native run-android --variant=release"

**Comment by jsaraiva** [comment]
@bhardman1986 Thanks! That solved it for me too!

**Comment by Anujmoglix** [comment]
dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'
}  I have 2.3.3 now . should i update it ?

**Comment by tuononh** [comment]
@Anujmoglix Read [this](https://facebook.github.io/react-native/docs/signed-apk-android.html#testing-the-release-build-of-your-app)

**Comment by Anujmoglix** [comment]
I read this and fix that issue  but in some device it is not installing and some device it is creating same issue .

**Comment by IndianAg0711** [comment]
@bhardman1986 if you're accepting beer/coffee money, I owe you a couple!

**Comment by radin-reth** [comment]
@bhardman1986 , save my hair 👍

**Comment by miladino43** [comment]
I am using:
com.android.tools.build:gradle:3.2.1
react-native": "0.53.0
gradle 4.6

first make sure you have no untracked files/directories that you would like to commit. **(VERY IMPORTANT)**
run this command:
```
react-native` bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
```

This will create the bundle and bundle.meta file in android/app/src/main/assets/
and some other files and directories in android/app/src/main/res/

Add the files in android/app/src/main/assets/ 
```
git add android/app/src/main/assets/*
```

Next remove the files and directories that are not needed

To see what will get removed(This will not actually remove them so you are safe)
```
git clean -n
```

If you are ok with this output remove them all.(Make sure you dont have files/directories that you want to keep in this ourput. You will lose them. **You have been warned**)
```
git clean -d -f
```
Build the release app with
```
react-native run-android --variant=release
```

**Comment by paalex** [comment]
The [suggestion](https://github.com/facebook/react-native/issues/18357#issuecomment-425728542) above by @bhardman1986 solved it for me! Thanks
However:
`The option 'android.enableAapt2' is deprecated and should not be used anymore.
Use 'android.enableAapt2=true' to remove this warning.
It will be removed at the end of 2018..`

The only solution is upgrading to RN 0.57.4?

**Comment by jsaraiva** [comment]
@paalex I managed to get it to work without the `enableAapt2 = false` part. What was mandatory was downgrading gradle to 3.1.4.
RN 0.57.2

**Comment by paalex** [comment]
@jsaraiva got it, thanks! I'll try that

**Comment by thousight** [comment]
Another thing that's like `Don't ask me why it worked cuz I really don't know...`

**Comment by jsaraiva** [comment]
Apparently, Gradle 3.2.0 changed the location to which it generates asset bundles. RN expects its JS asset bundle to be in a specific path, which is the path used by Gradle 3.1.4. Because G3.2.0 puts them in a different spot, RN cannot find the JS asset bundle, and thus the files with the Javascript to run. Ergo, the crash in release mode.

In debug mode, the JS files are provided by the Metro daemon, and there is no JS asset bundle to be loaded. That's why this error only manifests itself in release mode.

This is why lots of people suggest fixes that involve creating the asset bundle manually (via CLI), copying it manually to a specific folder, and then running the apk generator. But, let's face it, it's way easier to just downgrade Gradle to a version that works the way RN expects.

Now, why the RN devs didn't update the native source code to get the bundle from its new location, that is a mystery that I haven't figured out.

**Comment by zvs001** [comment]
For `com.android.tools.build:gradle:3.2`
Issue was fixed after upgrading to react-native@^0.57.4

**Comment by gumelartejasukma** [comment]
@bhardman1986 thanks bro, you save me a lot of time

**Comment by alvelig** [comment]
The fix is upgrading RN to 0.57.4 or downgrading gradle to 3.1.4.

For those who want a really neat workaround without having to upgrade/downgrade:
`app/build.gradle:`
```
project.ext.react = [
    entryFile: "index.js",
    jsBundleDirRelease: "$buildDir/intermediates/merged_assets/release/mergeReleaseAssets/out"
]
```

**Comment by LeoUrushi** [comment]
I’m having the same problem but my react native and gradle versions seem newer. 
Thanks for all the suggestions. 
So far, I’ve tried the methods suggested by @bhardman1986 , @gderaco  + @sacchykhedkar  and @alvelig  so far with no success. 
Has anyone found a solution for this in newer versions? 

My environment:
package.json
…
    "react": "^16.6.3",
    "react-dom": "^16.8.1",
    "react-native": "0.58.4",
    "react-native-gesture-handler": "^1.0.15",
    "react-native-image-pan-zoom": "^2.1.11",
    "react-navigation": "^3.2.1"
…


android/ build.gradle 
…
buildscript {
    ext {
        buildToolsVersion = "28.0.2"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 27
        supportLibVersion = "28.0.0"
    }
…
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'

    }
}
…

**Comment by JordanB** [comment]
Root cause well explained here --> https://github.com/facebook/react-native/issues/18357#issuecomment-437186504, thanks @jsaraiva 

`"react-native": "0.58.5"` with `com.android.tools.build:gradle:3.3.0` is also a working combination if you want to use a newer version of gradle.

Thanks everyone for your help, it was painful to face this issue.

**Comment by ShokiiCookiie** [comment]
Still have this issue with `"react-native": "0.58.5"` and `com.android.tools.build:gradle:3.3.0` downgrading to `com.android.tools.build:gradle:3.1.4` fixed it for me.

**Comment by chardnett** [comment]
This is still an issue apparently. Which is amazing.

**Comment by mpalmerlee** [comment]
I've been using RN 0.57.4 and gradle 3.2+ up to this point without any issues. I recently added `productFlavors` for different environments for testing (dev, stage, prod, etc...) and hit this same issue. If I downgrade to gradle 3.1.4 then my release build works fine, so @ShokiiCookiie it's possible that you are hitting this issue due to RN's handling of gradle 3.2+ directories when using `productFlavors` in your build.gradle file.

Here is some more information on how to repro:
in app/build.gradle
```
flavorDimensions "env"
    productFlavors {
        dev {
            dimension "env"
            applicationIdSuffix ".dev"
        }
        stage {
            dimension "env"
            applicationIdSuffix ".stage"
        }
        prod {
            dimension "env"
        }
    }
```

Build on a device for release using one of the flavors:
`./gradlew installStageRelease`

With `com.android.tools.build:gradle:3.2.1` I get an immediate crash opening the app (the same bundling error: `Unable to load script from assets 'index.android.bundle'. Make sure your bundle is packaged correctly or you're running a packager server.
com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromAssets` if I use `com.android.tools.build:gradle:3.1.4` it works like a charm.

**Comment by frysukarto** [comment]
i have same trouble.
apps can running at another device but not oppo. how can i handle this?

**Comment by ShokiiCookiie** [comment]
@mpalmerlee  Yes I'm using productFlavors. 
Still facing this with `"react-native": "0.59.3"` 😩

**Comment by gangilanoop** [comment]
Any update on this issue ?

**Comment by nadirHomeFriend** [comment]
> The fix is upgrading RN to 0.57.4 or downgrading gradle to 3.1.4.
> 
> For those who want a really neat workaround without having to upgrade/downgrade:
> `app/build.gradle:`
> 
> ```
> project.ext.react = [
>     entryFile: "index.js",
>     jsBundleDirRelease: "$buildDir/intermediates/merged_assets/release/mergeReleaseAssets/out"
> ]
> ```

hello, it is not working for me , help plz

**Comment by firebluetom** [comment]
Facing same issue. Using latest RN 59 and gradle 3.4, works in debug mode but on --variant=release it just crashes.

**Comment by gauravsbagul** [comment]
does anybody has any solution on this please... we all are having same issue i followed all the steps but build still fails and i get same error "Task 'installRelease' not found in project ':app'. Some candidates are: 'uninstallRelease'" 
Microsoft Windows [Version 10.0.17134.706]
(c) 2018 Microsoft Corporation. All rights reserved.
----->
E:\Developement\***\***>react-native run-android --variant=release
info Starting JS server...
info Building and installing the app on the device (cd android && gradlew.bat app:installRelease)...
Starting a Gradle Daemon, 2 incompatible and 1 stopped Daemons could not be reused, use --status for details

FAILURE: Build failed with an exception.

* What went wrong:
Task 'installRelease' not found in project ':app'. Some candidates are: 'uninstallRelease'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 41s
error Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
error Command failed: gradlew.bat app:installRelease. Run CLI with --verbose flag for more details.

**Comment by jhchong92** [comment]
> does anybody has any solution on this please... we all are having same issue i followed all the steps but build still fails and i get same error "Task 'installRelease' not found in project ':app'. Some candidates are: 'uninstallRelease'"
> Microsoft Windows [Version 10.0.17134.706]
> (c) 2018 Microsoft Corporation. All rights reserved.
> ----->
> E:\Developement******>react-native run-android --variant=release
> info Starting JS server...
> info Building and installing the app on the device (cd android && gradlew.bat app:installRelease)...
> Starting a Gradle Daemon, 2 incompatible and 1 stopped Daemons could not be reused, use --status for details
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Task 'installRelease' not found in project ':app'. Some candidates are: 'uninstallRelease'.
> * Try:
>   Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 1m 41s
> error Could not install the app on the device, read the error above for details.
> Make sure you have an Android emulator running or a device connected and have
> set up your Android development environment:
> https://facebook.github.io/react-native/docs/getting-started.html
> error Command failed: gradlew.bat app:installRelease. Run CLI with --verbose flag for more details.

@gauravsbagul I have faced this before the fix was to setup signingConfigs for your buildType

```
signingConfigs {
        release {
            Properties properties = new Properties()
            properties.load(project.rootProject.file('local.properties').newDataInputStream())
            storeFile file(properties.getProperty('APP_RELEASE_STORE_FILE'))
            keyAlias properties.getProperty('APP_RELEASE_KEY_ALIAS')
            storePassword properties.getProperty('APP_RELEASE_STORE_PASSWORD')
            keyPassword properties.getProperty('APP_RELEASE_KEY_PASSWORD')

        }
    }
...
buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
    }
```

**Comment by jhchong92** [comment]
Downgrading to 3.1.4 for gradle fixed the problem for me.. finally.. lost a lot of hair on this. As @mpalmerlee mentioned, upgrading to newer versions of react native didn't resolve this if you're using productFlavors. In my case, I was using RN 0.57.4

**Comment by Bvida100** [comment]
I had same problem with android 3.4.0 and gradle 5.4.1, I downgrade to android 3.3 and gradle 4.10.1 and the issue is gone. I use React Native 0.59.5.

**Comment by remarcus** [comment]
I can confirm versions that @Bvida100 stated.

For beginners or confused how to downgrade you can do that in following config files:

`android/gradle/wrapper/gradle-wrapper.properties:`

```
distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip
```

and

`android/build.gradle:`

```
dependencies {
...
    classpath 'com.android.tools.build:gradle:3.3.0'
```

**Comment by thib92** [comment]
@remarcus looks like the best answer to me.

**Comment by taeminpak** [comment]
I have tried upgrading to versions suggested by @remarcus and @thib92 and am still finding the app crash on launch (for release versions only).
My RN version is "0.57.4".
I am following these directions to generate the release APK: https://medium.com/@impaachu/react-native-android-release-build-crash-on-device-14f2c9eacf18
I have also tried generating the release APK through Android Studio, but I get the same result.
Anyone have any suggestions?
Also does anyone know if using AndroidX has any effect on the release build process?

**Comment by remarcus** [comment]
@taeminpak I believe there were a lot of changes since 0.57.4 and even some breaking ones with the releases of 0.58 and 0.59.

If possible you could try [RN v0.59.9](https://github.com/facebook/react-native/releases/tag/v0.59.9), because it has support for more recent build tools. If not I would suggest retrieving logs from device running release version of your app and the issue might not be connected to this one.

Regarding AndroidX recent release of Google Play Services has impacted some libraries that were using its latest version (i.e. react-native-device-info), but that's unlikely because it would probably crash on build first.

I also had some issues in the past regarding drawables and not having asset of required density so app would crash.

Would suggest you to create a new fresh project and add your current dependencies to see if problem is actually in current build tools and RN version.

Good luck! :)

**Comment by taeminpak** [comment]
@remarcus 
could you elaborate on your issues regarding 'drawables and not having asset of required density'?

**Comment by StarkAndy** [comment]
Please check your render() function and see if your are using any Component which been deprecated checking by commenting each one of them one by one .Hope it might help
