### ISSUE TITLE
[MapView] some incorrect values in region properties lead to crash

### ISSUE THREAD

**Issue by blax** [facebook/react-native#1836]
LongitudeDelta and LatitudeDelta expect numbers, but some of the values are still not supported. 

For instance, providing:
```javascript
region: {
  latitude: 0,
  longitude: 0,
  latitudeDelta: 200,
  longitudeDelta: 100,
};
```
causes the whole app to crash and the following exception is raised:
`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Invalid Region <center:+0.00000000, +0.00000000 span:+200.00000000, +100.00000000>'```

**Comment by a2** [comment]
`latitudeDelta` and `longitudeDelta` are changes in the respective *degree values* of the properties, not the meter values.

**Comment by blax** [comment]
I'm aware of that, but the issue is that documentation never mentions that, as it only says 
> The region is defined by the center coordinates and the span of coordinates to display.

In addition the "developer experience" would be much better if the framework communicated the error in some better way, not crashing the whole app and forcing developer to look at Xcode logs.

**Comment by a2** [comment]
I agree this could be better. Perhaps we could show a red box error if the region is invalid.

**Comment by a2** [comment]
If you have time, could you throw together a small pull request?

**Comment by blax** [comment]
Sure, once I'm back from react-europe :)
