### ISSUE TITLE
Fetch is not working

### ISSUE THREAD

**Issue by vladinko0** [facebook/react-native#18369]
### Environment

Environment:
  OS: Windows 10
  Node: 8.10.0
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.0.0.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: 0.54.2 => 0.54.2

### Expected Behavior

I am waiting for successful JSON from server:
{"PHPSESSID":"1l5jm09fsbk9061dllmecn4v22","phoneNumber":"+421900123456","clientRole":1,"clientToken":"tokenasinepotrebujeme","specialId":291,"name":"Tester","distance":"250","organizationId":2}

### Actual Behavior

I get 

> SyntaxError: Unexpected token b in JSON at position 0

.
b is the first letter of word "badlogin". It responds server when sent wrong combination of userName and password. But when I use Postman with the same key vaules combination on the same addres I get correct rosponse from the server. 

### Steps to Reproduce

```
import React, { Component } from 'react';
import {
  StyleSheet,
  Text,
  View, TouchableOpacity
} from 'react-native';


export default class App extends Component {
  render() {
    return (
      <View style={styles.container}>
        <TouchableOpacity
          style={styles.btn}
          onPress={this.login}>
          <Text>Log in</Text>
        </TouchableOpacity>
      </View>
    );
  }

  login = () => {
   
    fetch('http://stemiglobal.sk/stemibase/app-login', {
        method: 'POST',
        headers: {
          'Accept': 'application/json',
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          userName: "react",
          password: "123",
        })
      }).then((response) => response.json())
      .then((responseJson) => {
        console.log(responseJson.message);  
        if(responseJson.success === true) {
            alert('successufuly loged');
        }
        else{
            console.log(responseJson.message);  
            alert(responseJson.message);
        }
      })  
    }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#2896d3',
    paddingLeft: 40,
    paddingRight: 40,
  }, btn: {
    alignSelf: 'stretch',
    padding: 20,
    alignItems: 'center',
    backgroundColor: '#01c853',
  }
});
```

**Comment by sfm2222** [comment]
share the alert results.
```
 fetch( ''http://stemiglobal.sk/stemibase/app-login'', {
                method: 'POST',
                headers: {
                  'Accept': 'application/json',
                  'Content-Type': 'application/json',
                },
                body: JSON.stringify({
                  userName: "react",
          password: "123",
                })
              })
          .then((response) =>  response.json())
          .then((responsenew) =>  
          {
             alert(JSON.stringify(responsenew));
          })
```

**Comment by vladinko0** [comment]
> Possible Unhandled Promise Rejection (id: 0):
> SyntaxError: Unexpected token b in JSON at position 0
> SyntaxError: Unexpected token b in JSON at position 0
>     at parse (<anonymous>)
>     at tryCallOne (blob:http://localhost:8081/787e7734-5be8-48c3-9c5c-15656560c3e2:14083:14)
>     at blob:http://localhost:8081/787e7734-5be8-48c3-9c5c-15656560c3e2:14184:17
>     at blob:http://localhost:8081/787e7734-5be8-48c3-9c5c-15656560c3e2:15504:21
>     at _callTimer (blob:http://localhost:8081/787e7734-5be8-48c3-9c5c-15656560c3e2:15393:9)
>     at _callImmediatesPass (blob:http://localhost:8081/787e7734-5be8-48c3-9c5c-15656560c3e2:15429:9)
>     at Object.callImmediates (blob:http://localhost:8081/787e7734-5be8-48c3-9c5c-15656560c3e2:15648:14)
>     at MessageQueue.__callImmediates (blob:http://localhost:8081/787e7734-5be8-48c3-9c5c-15656560c3e2:2346:18)
>     at blob:http://localhost:8081/787e7734-5be8-48c3-9c5c-15656560c3e2:2173:18
>     at MessageQueue.__guardSafe (blob:http://localhost:8081/787e7734-5be8-48c3-9c5c-15656560c3e2:2330:11)
> console.warn	@	C:\Users\admin\Docum…ive\YellowBox.js:82
> onUnhandled	@	C:\Users\admin\Docum…aries\Promise.js:44
> onUnhandled	@	C:\Users\admin\Docum…tion-tracking.js:71
> (anonymous)	@	C:\Users\admin\Docum…ers\JSTimers.js:258
> _callTimer	@	C:\Users\admin\Docum…ers\JSTimers.js:154
> callTimers	@	C:\Users\admin\Docum…ers\JSTimers.js:407
> __callFunction	@	C:\Users\admin\Docum…MessageQueue.js:353
> (anonymous)	@	C:\Users\admin\Docum…MessageQueue.js:118
> __guardSafe	@	C:\Users\admin\Docum…MessageQueue.js:316
> callFunctionReturnFlushedQueue	@	C:\Users\admin\Docum…MessageQueue.js:117
> (anonymous)	@	debuggerWorker.js:72

**Comment by sfm2222** [comment]
are you using the same user name and password because it gives badlogin in reponse on postman as well.

**Comment by vladinko0** [comment]
Are you using the same key value combination as me in Postman:
See:

![snimka](https://user-images.githubusercontent.com/16008547/37398022-6d67d3e6-277d-11e8-85ab-15263a5173b0.PNG)

**Comment by sfm2222** [comment]
yes just the same.

**Comment by vladinko0** [comment]
With alert(JSON.stringify(responseJson)); I get:

![snimka](https://user-images.githubusercontent.com/16008547/37398831-04a7d402-2780-11e8-8397-0f75cbcf6875.PNG)

**Comment by vladinko0** [comment]
I solved this issue by using FormData instead to prepare data for sending:

```
......
login = () => {
    var formData = new FormData();
    formData.append('username', 'react');
    formData.append('password', '123');

    fetch('http://......', {
     method: 'POST',
     body: formData
........

```

**Comment by kaushal9678** [comment]
for posting data using redux saga, you have to create Formdata as @vladinko0 said above. It worked for me.

**Comment by vinceyuan** [comment]
I had the same problem as this one and https://github.com/facebook/react-native/issues/11236 . All `POST` becomes `GET`. I thought it's `fetch`'s problem. But actually it's my problem.

There is an extra `/` in my url, e.g. `https://example.com//endpoint`. The server redirects it to `https://example.com/endpoint`, but `POST` becomes `GET` because https://developer.mozilla.org/en-US/docs/Web/HTTP/Redirections#attr1 . Removing the extra `/` solves the problem. This problem cost me one night. Hope it helps others.
