### ISSUE TITLE
WebView load smooth on IOS device, but break on Android device

### ISSUE THREAD

**Issue by thoth-nexlesoft** [facebook/react-native#18365]
I'm run code.
```
import React, { Component } from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  View,
  WebView
} from 'react-native';

export default class App extends Component<{}> {
  render() {
    return (
      <View style={styles.container}>
        <WebView
        source={{uri: 'https://en.wikipedia.org/wiki/Wiki'}}
        javaScriptEnabled
      />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  }
});
```

### Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 9.6.1
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.50.4 => 0.50.4

### Expected Behavior

App will load link uri with same smooth font-family on Android  and IOS

### Actual Behavior

App load WebView with font-family smooth on IOS. But font-family don't smooth on Android.

**WebView on IOS**
![WebView IOS](https://user-images.githubusercontent.com/25680402/37386728-39cab224-278c-11e8-9597-7d9e1eafba2f.png)

**WebView on Android**
![webview_android](https://user-images.githubusercontent.com/25680402/37386763-65e0c754-278c-11e8-8019-2586f5235904.png)

### Steps to Reproduce

You can create react-native project and copy code above. After you run app.

**Comment by thoth-nexlesoft** [comment]
I have used react-native latest version (react-native 0.54.0). But app load with same issue.

**Comment by MurshidMac** [comment]
try these changes to your class
```
type Props = {};
export default class App extends Component<Props>
```
these to your WebView
 ```
     <WebView
        source={{uri: 'https://en.wikipedia.org/wiki/Wiki'}}
        javaScriptEnabled
        domStorageEnabled
      />
 ```
