### ISSUE TITLE
Android padStart is undefined, likely needs to be polyfilled

### ISSUE THREAD

**Issue by callmetwan** [facebook/react-native#18375]
When testing on Android 5.0+ (Google API 22+) I found that calls to padStart would result in "undefined is not a function". Polyfilling it manually resolved the issue in Android 5.0+. My polyfill fix was a verbatim copy/paste of the [polyfill example on MDN's padStart](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart) . This error **does not** happen when debugging remotely. If my understanding is correct, this is due to differences in Chrome's JS engine vs React Natives implementation.

I found related issue #17442 where this error was occurring on iOS. I opened a separate issue because this was happening on Android.

### Environment

#####Environment:
  OS: macOS Sierra 10.12.6
  Node: 9.5.0
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

#####Packages: (wanted => installed)
  react: ^16.2.0 => 16.2.0
  react-native: ^0.53.3 => 0.53.3

### Expected Behavior

Calls to padStart should return a value according to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart)

### Actual Behavior

Calls to padStart result in an error of "undefined is not a function"

### Steps to Reproduce

Call padStart on a string.

```
const test = 'hello'
console.log(test.padStart(2, '0')) // results in 'undefined is not a function'
```

### Reproducible Demo
https://snack.expo.io/ByAN82Itz

**Comment by callmetwan** [comment]
Oof, didn't even notice there was a new RN version.

That being said, the Expo Snack test I included still fails, I assume that is running the latest version of RN.

**Comment by csamyphew** [comment]
I went into same problem, instead of updating version. I use lodash padstart function and it works!!

**Comment by Tonacatecuhtli** [comment]
Hi,

I'm using react-native version "0.54.2" and the error still occurs.

**Comment by og24715** [comment]
I got the same error using react-native version 0.55.2.

**Comment by phzbox** [comment]
Same on 0.54.0

**Comment by iiqmohamad** [comment]
Any update?

**Comment by Tonacatecuhtli** [comment]
Still an issue with "0.55.4"

**Comment by ulfgebhardt** [comment]
Bump - same Problem

**Comment by numen31337** [comment]
Can reproduce with "0.56". For some reason only on the Android without attached debugger.

**Comment by rptwsthi** [comment]
Happening to me too, on iOS it works fine but android give the issue.

**Comment by HighSoftWare96** [comment]
With Android 7.0 and latest version of react native this bug does not occurs anymore... For the older version is there some workaround?

**Comment by esutton** [comment]
This is frustrating.  

I had removed and quit using lodash padStart() because I had discovered it was not needed anymore.

I started testing my app on Android again and now I learn I need to go back and replace it all with lodash padStart() all over again.

**Comment by thymikee** [comment]
React Native 0.59 shipped with modern JSC (JavaScriptCore engine) on Android, which supports `String.padStart`, so please upgrade :)
