### ISSUE TITLE
TextInput's caret always move to beginning when toggling secureTextEntry

### ISSUE THREAD

**Issue by williamliangwl** [facebook/react-native#18377]
I am using ReactNative v.0.52.0 and currently developing a TextInput for password, but want to enable user to show / hide their typed input. The problem when toggling the value of secureTextEntry, the caret always move to the beginning of the input. 

I have only tested this in Android device.

### Environment

Environment:
* OS: Windows 10
* Node: 6.11.5
* Yarn: 1.3.2
* npm: 4.6.1
* Watchman: Not Found
* Xcode: N/A
* Android Studio: Version  3.0.0.0 AI-171.4443003

Packages: (wanted => installed)
* react: 16.2.0 => 16.2.0
* react-native: 0.52.0 => 0.52.0

### Expected Behavior

I expect the caret will always stay at the end of the input, when toggling the secureTextEntry

### Steps to Reproduce

I manage to reproduce this using a very simple code, I put it at the App.js
```
export default class App extends Component {

  constructor() {
    super();
    this.state = {
      showPassword: false
    };
  }

  toggleShow() {
    this.setState({
      showPassword: !this.state.showPassword
    });
  }

  render() {
    return (
      <View>
        <TextInput secureTextEntry={this.state.showPassword} />
        <Button title={'Toggle'} onPress={this.toggleShow.bind(this)} />
      </View>
    );
  }
}
```

**Comment by williamliangwl** [comment]
@react-native-bot Yes tested in v.054.2 and still having same issue in Android device

**Comment by williamliangwl** [comment]
I do realize that in version 0.54, a fix has been submitted, but it looks like not working although I test it using 0.54.2. The commit is 09b43e4

**Comment by williamliangwl** [comment]
@react-native-bot I don't think Old Version label is still valid here as it is tested not working in v0.54.2 and I still can't find a solution for it

**Comment by LiHaoTan** [comment]
Is there a workaround for this? It does not appear the fix works like @williamliangwl mentioned.

**Comment by LucasLpr** [comment]
Same issue

**Comment by minhtamwebmaster** [comment]
same issue

**Comment by vitorsilvalima** [comment]
I have the same issue too

**Comment by jainkuniya** [comment]
Hi, this issue will be fixed by https://github.com/facebook/react-native/pull/17990
