### ISSUE TITLE
Getting started guide fails because of flow version mismatch

### ISSUE THREAD

**Issue by seanhess** [facebook/react-native#1838]
I'm trying react native out for the first time, following the directions here: https://facebook.github.io/react-native/docs/getting-started.html

I initialized the project, and it specifies that it requires flow 0.11 to be installed. I have 0.12 installed, so I changed it in .flowconfig file, but I get many errors. There are close to 20, but here's one example:

    /Users/seanhess/sandbox/AwesomeProject/node_modules/react-native/Libraries/Components/Navigation/NavigatorIOS.ios.js:224:18,33: undefined
    This type is incompatible with
    /Users/seanhess/sandbox/AwesomeProject/node_modules/react-native/Libraries/Components/Navigation/NavigatorIOS.ios.js:86:14,19: object type

I checked the package.json and it seems to be pointing at the latest version of react-native. I expected the latest release to work with the latest flow. Is there a workaround for now? Perhaps the guide needs updating?

**Comment by a2** [comment]
We are now running flow v0.13.1. Can you update to this version and try again?
