### ISSUE TITLE
plz help me

### ISSUE THREAD

**Issue by bawhari** [facebook/react-native#18380]
Hello friends
I encountered this error in running the react native on nox

With the command line : react-native run-android

Could not install the app on the device, read the error above for detail s. Make sure you have an Android emulator running or a device connected and have set up your Android development environment:

**Comment by Lxxyx** [comment]
duplicated #18210 .
@facebook-github-bot close

**Comment by Lxxyx** [comment]
@facebook-github-bot stack-overflow
