### ISSUE TITLE
[TextInput] autoGrow documentation is missing

### ISSUE THREAD

**Issue by rhazegh** [facebook/react-native#18383]
Clicking on `autoGrow` in documentation leads nowhere:

<img width="807" alt="screenshot 2018-03-14 14 48 04" src="https://user-images.githubusercontent.com/2200559/37424437-d396d306-2796-11e8-90b5-970ec71588c0.png">

http://facebook.github.io/react-native/docs/textinput.html#autogrow leads nowhere.

**Comment by hramos** [comment]
Mind opening this in https://github.com/facebook/react-native-website instead?

**Comment by rhazegh** [comment]
Not at all. Thank you.
