### ISSUE TITLE
TextInput value not binding on IOS 

### ISSUE THREAD

**Issue by jinshin1013** [facebook/react-native#18389]
### Environment
Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.10.0
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.3.0-alpha.1 => 16.3.0-alpha.2
  react-native: 0.54.2 => 0.54.2

### Expected Behavior
TextInput value binding to state 

Set state for TextInput to use
`state = {  text: "useless text" }`

In component render method
`render() {`
`   return ( `
`<TextInput value={this.state.text} />`
`)`
`}`

On TextInput text change, the value of the text input should still be "useless text"
 
### Actual Behavior
On Android Emulator it works as expected. However on IOS simulator, the value changes. Not sure if this is an intended behaviour. 

![textinput bug](https://user-images.githubusercontent.com/17612922/37444613-55937ac2-285e-11e8-938c-00f03cbabc80.gif)

### Steps to Reproduce
Fresh project from react-native init.

**Comment by maraujop** [comment]
This was already reported here https://github.com/facebook/react-native/issues/18219 and there is a proposed PR to fix it here https://github.com/facebook/react-native/pull/18278

**Comment by jinshin1013** [comment]
Cheers, @maraujop . I will close this issue.

**Comment by maraujop** [comment]
Cheers @jinshin1013 good reporting though
