### ISSUE TITLE
failure to install due to missing babel version

### ISSUE THREAD

**Issue by stephen-james** [facebook/react-native#18393]
When installing react-native, using either react-native-cli (`react-native init myProject`, or manually `yarn add react-native --exact`) the installation fails due to a missing babel 7 beta dependency.

`Couldn't find package \"@babel/core@^7.0.0-beta\" required by \"metro@^0.28.0\" on the \"npm\" registry.`

### Environment

macOS
yarn: v1.5.1
react-native-cli: 2.0.1

```
$ yarn info react-native
yarn info v1.5.1
{ name: 'react-native',
  'dist-tags':
   { latest: '0.54.2',
     next: '0.55.0-rc.0' },
   . . .
```

### Expected Behavior

React native, or project with react native will install without issue.

### Actual Behavior

`Couldn't find package \"@babel/core@^7.0.0-beta\" required by \"metro@^0.28.0\" on the \"npm\" registry.`

### Steps to Reproduce

Run

`yarn add react-native@0.54.2 --exact`

or _!time sensitive!_

`react-native init myProject`

or _!time sensitive!_

`yarn add react-native@latest`

or _!time sensitive!_

`yarn add react-native@next`

### Additional Info
Babel 7 beta has no npm entry `7.0.0-beta` see summarized list below... 

```
$ npm show babel-core versions

[ ...
  '7.0.0-alpha.1',
  '7.0.0-alpha.2',
  '7.0.0-alpha.3',
  '7.0.0-alpha.6',
  '7.0.0-alpha.7',
  '7.0.0-alpha.8',
  '7.0.0-alpha.9',
  '7.0.0-alpha.10',
  '7.0.0-alpha.11',
  '7.0.0-alpha.12',
  '7.0.0-alpha.14',
  '7.0.0-alpha.15',
  '7.0.0-alpha.16',
  '7.0.0-alpha.17',
  '7.0.0-alpha.18',
  '7.0.0-alpha.19',
  '7.0.0-alpha.20',
  '7.0.0-beta.0',
  '7.0.0-beta.1',
  '7.0.0-beta.2',
  '7.0.0-beta.3',
  '7.0.0-bridge.0' ]
```

Is it possible that babel team removed 7.0.0-beta and replaced it with 7.0.0-beta.x (numbered packages)?

**Comment by stephen-james** [comment]
After manually trying to debug available versions for "@babel/core" I got this result...

```
$ npm show @babel/core versions
npm ERR! code E404
npm ERR! 404 User not found : @babel/core
```

It was evident after this that there was a problem with the npm registry rejecting my user credentials which were set in `{HOME}/.npmrc`.

It seems that "scoped" packages (ie. @scope/packagename) force or imply the use of these credentials, whereas "normal" (unscoped) packages don't.

This meant that I'd been able to install unscoped packages from the standard npm registry, and scoped packages from my private npm registry (artifactory) without noticing any problem.

**Solution**
The solution was to remove the `always-auth=true` from .npmrc, or to scope the credentials in my .npmrc to only apply them for the scopes that I use in my private repo.

**Comment by Anurag690** [comment]
Couldn't find package "@babel/core@^7.0.0-beta" required by "metro@^0.30.0" on the "npm" registry.
@stephen-james solution provided by you didnt worked for me.
Can someone help here.
