### ISSUE TITLE
FlatList's `renderItem` renders twice, instead of once

### ISSUE THREAD

**Issue by TheDutchCoder** [facebook/react-native#18396]
When using a `FlatList` and you're using the `renderItem` method to create an "inline" list item, it will be rendered twice, instead of once on a `data` change.

### Environment

```
Environment:
  OS: macOS High Sierra 10.13.3
  Node: 4.8.2
  Yarn: Not Found
  npm: 4.6.1
  Watchman: Not Found
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.0 => 0.53.0
```

### Expected Behavior

List items should be re-rendered only once, not twice when the `data` property changes.

### Actual Behavior

All items are re-rendered twice.

### Steps to Reproduce

https://snack.expo.io/HkCbeluKG

### Source
```js
import React, { Component } from 'react';
import { Text, FlatList } from 'react-native';

export default class App extends Component {
  constructor(props) {
    super(props)

    this.state = {
      foo: [{ id: '1', name: 'one' }],
      bar: []
    }

    setTimeout(() => {
      this.setState({
        foo: [{ id: '1', name: 'one' }, { id: '2', name: 'two' }]
      })
    }, 1000)
  }

  componentDidMount() {
    console.log('mounted FlatList')
  }

  _keyExtractor = (item) => item.id

  _renderItem = ({item}) => {
    console.log(`rendering ${item.name}`) // This should fire only once when this.state.foo changes!
    return (
      <Text>{item.name}</Text>
    )
  }

  render() {
    return (
      <FlatList
        data={this.state.foo}
        extraData={this.state.bar}
        renderItem={this._renderItem}
        keyExtractor={this._keyExtractor}
      />
    )
  }
}
```

### Working source
When using a PureComponent instead, it works as expected:

```js
class ListItem extends React.PureComponent {
  constructor(props) {
    super(props)

    console.log(`created ListItem ${this.props.name}`)
  }

  componentDidUpdate() {
    console.log(`updated ListItem ${this.props.name}`)
  }

  render() {
    return (
      <Text>{this.props.name}</Text>
    )
  }
}

class PhotoPickerScreen extends React.Component {

  constructor(props) {
    super(props)

    this.state = {
      foo: [{ id: '1', name: 'one' }],
      bar: []
    }

    setTimeout(() => {
      this.setState({
        foo: [{ id: '1', name: 'one' }, { id: '2', name: 'two' }]
      })
    }, 1000)
  }

  componentDidMount() {
    console.log('mounted FlatList')
  }

  _keyExtractor = (item) => item.id

  _renderItem = ({item}) => (
    <ListItem name={item.name} />
  )

  render() {
    return (
      <FlatList
        data={this.state.foo}
        extraData={this.state.bar}
        renderItem={this._renderItem}
        keyExtractor={this._keyExtractor}
      />
    )
  }
}
```

**Comment by TheDutchCoder** [comment]
Will do, just an FYI that 0.53 is still installed when using npm.

**Comment by kelset** [comment]
Potentially related to https://github.com/facebook/react-native/issues/14528?

**Comment by TheDutchCoder** [comment]
@kelset correct, looks like the same issue, will close this one.

Also: please configure the bot, it suggests using a RN version that's tied to an Alpha release of React, i don't think that's something people would want to use in production.

**Comment by andyhuai** [comment]
I had the SAME question, 
but #14528 i can't reply, so is there any way to solve this?

**Comment by shubhang93** [comment]
Yeah , I am facing the same issue in react native 0.55.4, shouldComponentUpdate doesn't help there because this happens on initial render. I guess it is a bug which is not being addressed. For now I am using legacy implementation, which solves it but memory consumption is through the roof for large lists.

**Comment by amirpervaiz086** [comment]
Tried caching as well for images but found even If use empty list with headers it uses memory upto 150MB. This behavior is observed on iPod 5 where on iPhone X it seems to be pretty smooth but memory wise it shoots likewise. Any solution would be appreciated. Thanks

**Comment by amirpervaiz086** [comment]
@shubhang93 I am using pureComponent but still memory issue is great...

**Comment by sharoneh** [comment]
same about the repetitive re-rendering here (for each 10 items)
I noticed in my environment that it doesn't happen if I disable redux-persist at the state where the items of the list are
let me now if anyone's experiencing something like this

**Comment by sharoneh** [comment]
found something that can help: https://stackoverflow.com/questions/48357524/flatlist-calling-twice

**Comment by geeklevel1000** [comment]
I recreated the issue in this snack. https://snack.expo.io/B1KoX-EUN - I confirmed you can use shouldComponentUpdate(nextProps, nextState) to diff this.state or this.props and return true/false - https://reactjs.org/docs/react-component.html#shouldcomponentupdate docs say this callback should be used only for optimization which is what we're doing here.
