### ISSUE TITLE
How-to: make a square view

### ISSUE THREAD

**Issue by ide** [facebook/react-native#184]
I was trying to make a square view where width=100% and height=width. The approach I'm taking is to measure the parent view in `componentDidMount` and use its dimensions to manually set the size of the square view, one render frame later. This seems reasonable and mostly good but I want to know if I'm overlooking a way to do this in a single render pass.

**Comment by pie6k** [comment]
What about `aspectRatio`? - https://facebook.github.io/react-native/docs/layout-props.html#aspectratio

Setting it to `1` should make your view square.
