### ISSUE TITLE
Debugger does not work with localhost tunnel.

### ISSUE THREAD

**Issue by jtremback** [facebook/react-native#1840]
I'm trying to use a localhost tunnel provided by https://forwardhq.com/ to avoid having to change the IP address in the source code all the time, and to debug my app on other people's devices.

It is able to load the JS code over the tunnel with no problem. However, trying to run the debugger over the tunnel breaks with a timeout error.

**Comment by ide** [comment]
Sounds like a "bug" with forwardhq -- they need to support web sockets.
