### ISSUE TITLE
Non-portable path to file '<Stdio.h>'; specified path differs in case from file name on disk

### ISSUE THREAD

**Issue by xiaoyongchen** [facebook/react-native#18406]
(Describe your issue in detail.)
0.48 react-native-git-upgrade =>0.54
pod install 

error:Non-portable path to file '<Stdio.h>'; specified path differs in case from file name on disk

### Environment
react:16.3.0-alpha.1,
react-native:0.54.2
platform:ios
xcode:9.2
macOS:10.13.1
(Run `react-native info` in your terminal and paste its contents here.)

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Include screenshots if needed.)

### Steps to Reproduce

(Link to Snack, or steps to reproduce.)

**Comment by YangYunLong** [comment]
@xiaoyongchen please how to fix it ? thank you
