### ISSUE TITLE
(Android) crash on TextInput onKeyPress when inputting an emoji via auto-complete

### ISSUE THREAD

**Issue by akalin-keybase** [facebook/react-native#18405]
On 0.53.0 and later, including 0.54.2, if I input an emoji into a TextInput via auto-complete, the app crashes.

I've tracked down the root cause; I'll put more details in a follow-up comment.

### Environment

```
Environment:
  OS: macOS High Sierra 10.13.3
  Node: 9.7.1
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.3 => 0.53.3
```

### Expected Behavior

No crash!

### Actual Behavior

Crash stack:

```
Error calling RCTEventEmitter.receiveEvent

Failed to create Value from JSON: 
run
    NativeRunnable.java
handleCallback
    Handler.java:790
dispatchMessage
    Handler.java:99
dispatchMessage
    MessageQueueThreadHandler.java:31
loop
    Looper.java:164
run
    MessageQueueThreadImpl.java:194
run
    Thread.java:764
```

### Steps to Reproduce

Fortunately, this repros with the example project from https://github.com/facebook/react-native/issues/18262 .

- Clone and run this repo https://github.com/lxcid/ReactNative-AndroidKeyPress
- Make sure you have an Android device attached for debugging.
- react-native run-android
- select the TextInput
- type 'potato'
- tap the potato emoji that shows up in autocomplete.

![screenshot_1521183883](https://user-images.githubusercontent.com/13270622/37507853-c5228f8c-28ad-11e8-9a9d-72686f1923d2.png)

**Comment by akalin-keybase** [comment]
Yes, I can repro with 0.54.0.

**Comment by akalin-keybase** [comment]
So the "Failed to create value from JSON: " exception is thrown from: https://github.com/facebook/react-native/blob/0ee502d1254b828efb119cc06bcd213c3d843269/ReactCommon/jschelpers/Value.cpp#L74 (i.e., it's trying to parse JSON from an empty string)

Debugging this code, this is called from:
https://github.com/facebook/react-native/blob/0ee502d1254b828efb119cc06bcd213c3d843269/ReactCommon/jschelpers/Value.cpp#L98

The conversion to JSON produces the string:

```
[258,"topKeyPress",{"key":"�"}]
```

(I'm not 100% sure if the �, which is supposed to be the potato emoji, is messed up because of the JSON conversion messing up or my debugging output.)

It is the `String(ctx, json.c_str())` conversion that is failing and returning an empty string. This leads to the line
https://github.com/facebook/react-native/blob/0ee502d1254b828efb119cc06bcd213c3d843269/ReactCommon/jschelpers/Value.h#L32

so it looks like `JSC_JSStringCreateWithUTF8CString` is having problems with the emoji character.

**Comment by akalin-keybase** [comment]
Digging into the git history, this C++ code has been around forever. So why is it only showing up now? I'm almost certain it's because of this commit included in 0.53.0: https://github.com/facebook/react-native/commit/c9ff0bc . It implements the onKeyPress events for Android, and this line https://github.com/facebook/react-native/commit/c9ff0bc#diff-6bb282dadefaebe4c849ce7b47fa47a0R44 triggers the C++ code above.

Paging @joshyhargreaves who implemented the above commit. Do you know of any way to work around this bug, i.e. turn off the Android keypress events?

**Comment by akalin-keybase** [comment]
Also, if I set `USE_FAST_FOLLY_DYNAMIC_CONVERSION` to make the C++ code go through this path: https://github.com/facebook/react-native/blob/0ee502d1254b828efb119cc06bcd213c3d843269/ReactCommon/jschelpers/Value.cpp#L84
and comment out everything in that block but https://github.com/facebook/react-native/blob/0ee502d1254b828efb119cc06bcd213c3d843269/ReactCommon/jschelpers/Value.cpp#L92 , that fixes the problem. I don't know all the consequences of turning that on in general, though.

**Comment by joshyhargreaves** [comment]
@akalin-keybase thank you for reporting & providing a great error report!

Hmm, wow this is interesting! I'll do some debugging and see what I can find. You're right right it is unclear as to why this is only happening now. Is this bug reproducible on android simulators from your findings?

Yep so I can put together a quick PR that disables this codepath unless explicitly enabled, which would probably be for the best. It'd obviously be good to get to the bottom of why this is happening also. @hramos what do you think?

**Comment by akalin-keybase** [comment]
Yeap, it's reproducible with the android simulator. Yeah, a PR to disable the codepath unless needed seems like a good idea, thanks!

**Comment by joshyhargreaves** [comment]
@akalin-keybase, I’m going to get to this today or tomorrow.

**Comment by joshyhargreaves** [comment]
@akalin-keybase @hramos I opened a PR to disable the `onKeyPress` logic any thoughts and comments on that would be great 💯.

I'm also going to have a look into the onKeyPress logic, it looks like the logic itself doesn't work particularly well with unicode characters as it assumes key's pressed can only have a width of 1. 
The potato emoji, as per the character string is encoded in java as '\uD83E\uDD54' which results in two characters in the text input, and the key emitted will be the second of those two (\uDD54). There may be something wrong with the value conversion itself, but it's never been an issue for the `onChangeText` callback.

**Comment by mjmasn** [comment]
@joshyhargreaves @akalin-keybase I think we've hit this issue here although not with autocomplete, seems just using the emoji keyboard does the trick and causes a crash with the `Failed to create Value from JSON` error. 

Can only replicate if the app is running on-device, and only so far with the stock android keyboard. Swiftkey and Samsung keyboard seem to be immune, as does any keyboard if the app is running in the Chrome devtools debugger.

**Comment by joshyhargreaves** [comment]
@mjmasn that is interesting. Yep, different keyboards can chose to use the InputConnection differently with can result in different code path execution. I need to give some thought as to the best approach for emoji and `onKeyPress` in general it looks like.

 In the meantime, https://github.com/facebook/react-native/pull/18443 will make this code explicitly opt-in and should fix the 'regression', as it were.

**Comment by mjmasn** [comment]
@joshyhargreaves correction - it does appear to be auto-complete related here too - the original reproduction I was given was when typing something like `@mention hiya😀`, and seemingly `hiya😀` or just `😀` wasn't enough to trigger it. I've noticed that `a hiya😀` will trigger the bug and it's to do with autocomplete turning that into `a Hiya😀` (or `@mention Hiya😀` for the previous example). Not really sure why it's trying to auto-complete to the capitalised version of the word without it being the start of a sentence but it looks like there's a company called Hiya so maybe that's ended up in Google's dictionary. With typing `hiya😀` the output is actually `Hiya😀` due to text input sentence auto-capitalisation so the auto-complete isn't triggered in that case, hence no crash.

This was definitely winning weird unexplained bug of the month before I found this issue report, so thanks @akalin-keybase 👍

**Comment by nickofthyme** [comment]
Are there any updates on this issue? Thanks

**Comment by miguelacio** [comment]
I'm having the same issue 0.53.0, any workaround or update on this?

**Comment by mjmasn** [comment]
@miguelacio looks like it'll be fixed soon - https://github.com/facebook/react-native/pull/18443#pullrequestreview-123130008

**Comment by nickofthyme** [comment]
@miguelacio correct me if I'm wrong but it looks like [#18443](https://github.com/facebook/react-native/pull/18443) is only a workaround provided you don't use/need `onKeyPress`. It doesn't address the root issue to allow unencumbered use of `<TextInput />` (i.e. using `onKeyPress`).

**Comment by joshyhargreaves** [comment]
@nickofthyme yes you are correct.

I haven't had any time to fix the route cause of the issues, the logic behind this is the route cause of the issue: https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditTextInputConnectionWrapper.java#L102.
When the cursor moves forward, the character behind the cursor is taken, as it deemed to be the character that has been pressed. I believe that `TextInput#getText` returns an [Editable](https://developer.android.com/reference/android/text/Editable). I will have to investigate as I am unfamiliar with unicode support in Java, but on first impressions I do know that the unicode spec does support the combination of different unicode/emoji symbols to encode other emojis.

**Comment by kevinkevw** [comment]
@joshyhargreaves thanks a lot for the commit, it reduced the crashes a lot after applying that.
However, it still happens and shows up on Crashlytics ( Caused by com.facebook.jni.CppException
Failed to create Value from JSON: )

My TextInput is uncontrolled with just `onChangeText` & `styles` props. I don't know if it helps. 
This bug is really annoying. Considering a user typing a long message and it suddenly just crashes.

Hope someone will be able to fix it soon.

**Comment by joshyhargreaves** [comment]
@kevinkevw hmm, that is strange.
@akalin-keybase have you seen crashes since `0.56`?

**Comment by akalin-keybase** [comment]
we're not on 0.56 yet, unfortunately (we had to branch and patch a few other bugs ourselves)

**Comment by kevinkevw** [comment]
@akalin-keybase Do you have any solution for now? I have applied the commit that disabled the onKeyPress event but it still happens 😢

**Comment by joshyhargreaves** [comment]
@kevinkevw, to sanity check this you never create the InputConnection at all. However I do highly suspect there is another cause.

**Comment by kevinkevw** [comment]
@joshyhargreaves How to check? I am not sure what InputConnection is.

**Comment by joshyhargreaves** [comment]
@kevinkevw, stupid question, but are you building react native from source for Android?

**Comment by kevinkevw** [comment]
@joshyhargreaves No, I build by react-native run-android

**Comment by kevtran410** [comment]
I got this error when delete emoji in TextInput, anyone have a solution to fix that bug
My system on react-native 0.55.4 and can't upgrade to latest version right now because of getting bugs in another part.

**Comment by danielreuterwall** [comment]
Just upgraded to 0.56 and the problems seems to have been resolved.

**Comment by tandat2209** [comment]
Any workarounds other than upgrade to 0.56 ??

**Comment by NicWickman** [comment]
Upgrading to 0.56 is not an option for me at the moment. Is there a fix I can do myself?

**Comment by yogini-bende** [comment]
Any updates on this issue @joshjhargreaves @akalin-keybase  ? I am still searching to find some workaround for this issue. I am using react-native 0.55.2.
