### ISSUE TITLE
[iOS][WebView] Url hash change doesn't be supported in iOS WebView

### ISSUE THREAD

**Issue by Jancat** [facebook/react-native#18402]
iOS **WebView** doesn't support **hash url** change. The `onNavigationStateChange` listener will not be called when url hash changes.

But well on Android.

### Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 9.2.1
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.1 => 0.52.1

### Expected Behavior

When url hash change, the `webivew onNavigationStateChange` listener will be invoked, and the `canGoBack` properties is `true`

### Actual Behavior

When url hash changes, the `webivew onNavigationStateChange` hasn't been invoked

**Comment by iamdurui** [comment]
@react-native-bot yes,I try it  on the latest release, v0.54.2, but  the webivew onNavigationStateChange hasn't been called.

**Comment by yejing2017** [comment]
the same to #17856
