### ISSUE TITLE
Change Text in TextInput when value is fixed

### ISSUE THREAD

**Issue by mounlion** [facebook/react-native#18410]
(Describe your issue in detail.)

### Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.9.3
  Yarn: Not Found
  npm: 4.6.1
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: 0.54.0 => 0.54.0

### Expected Behavior

Value can't be changed

### Actual Behavior

value is changed

### Steps to Reproduce

```
<TextInput
value={'test'}
style={{color: 'white'}}
/>
```

I need fixed value in textinput but i can change text
<img width="329" alt="2018-03-16 13 33 24" src="https://user-images.githubusercontent.com/17071211/37516271-9eeeb50e-291e-11e8-8637-b541d404780d.png">

**Comment by kelset** [comment]
This is not a bug, you haven't used the [dedicated option](https://facebook.github.io/react-native/docs/textinput.html#editable).

**Comment by computerjazz** [comment]
@kelset this isn't how TextInput worked in [previous versions](https://facebook.github.io/react-native/docs/textinput.html#value):

``` TextInput is a controlled component, which means the native value will be forced to match this value prop if provided.```

In the example above, the TextInput should remain `'test'` despite user input.
There is currently no way to create a controlled TextInput. This issue should be re-opened.

**Comment by dann1609** [comment]
@kelset 
1) what shit is dedicated option? I search for that and don't find anything.
2) please try @mounlion code in web simulador at TextInput Page (https://facebook.github.io/react-native/docs/textinput.html#value). So you will check that normal behavior in last versions was keep value no matter if user tip keys.
3) reopen this issue cause there is an acceptable solution yet.

Thanks.
