### ISSUE TITLE
uncaught TypeError: Cannot read property 'major' of undefined

### ISSUE THREAD

**Issue by PrabhakarVoonik** [facebook/react-native#18412]
### ENVIRONMENT :

```
Environment:
  OS: macOS Sierra 10.12.6
  Node: 7.9.0
  Yarn: 0.22.0
  npm: 4.5.0
  Watchman: 4.7.0
  Xcode: Not Found
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: ^16.3.0-alpha.2 => 16.3.0-alpha.2
  react-native: ^0.54.2 => 0.54.2
```

After updating the react native and the dependencies, whenever the development server scripts(locally ) were loaded into the device, it's giving the following error in the typical red screen:

```
com.facebook.react.common.JavascriptException: Uncaught TypeError: Cannot read property 'major' of undefined

loadApplicationScript
WebSocketJavascriptExecutor.java:173

run
NativeRunnable.java

handleCallback
Handler.java:836
```

My dependencies list : (from package.json)

```
"dependencies": {
"create-react-class": "^15.6.3",
"lodash": "^4.17.5",
"minutes-seconds-milliseconds": "^1.0.3",
"prop-types": "^15.6.1",
"react": "^16.3.0-alpha.2",
"react-native": "^0.54.2",
"react-native-carousel": "^0.11.0",
"react-native-checkbox": "^2.0.0",
"react-native-code-push": "^5.3.1",
"react-native-communications": "^2.2.1",
"react-native-deprecated-custom-components": "^0.1.2",
"react-native-elements": "^0.19.0",
"react-native-masked-text": "^1.6.5",
"react-native-modal-dropdown": "^0.6.2",
"react-native-modal-picker": "0.0.16",
"react-native-parsed-text": "0.0.20",
"react-native-selectbox": "^0.1.2",
"react-native-simple-radio-button": "^2.7.1",
"react-native-tab-view": "0.0.74",
"react-native-tabbed-view-pager-android": "^1.0.4",
"react-native-vector-icons": "^4.5.0",
"react-redux": "^5.0.7",
"react-timer-mixin": "^0.13.3",
"redux": "^3.6.0"},

 "devDependencies": {
"babel-jest": "22.4.1",
"babel-preset-react-native": "4.0.0",
"babel-polyfill": "^6.26.0",
"jest": "22.4.2",
"react-native-bundle": "0.0.4",
"react-test-renderer": "16.2.0"}, 
```

In the JS console, it's giving following error :

```
Cannot read property 'major' of undefined
 Failed to print error:  regeneratorRuntime is not defined 
```

**Comment by PrabhakarVoonik** [comment]
issue contains the relevant information

**Comment by lbrdar** [comment]
Any update on this? @PrabhakarVoonik did you find a solution for this?

**Comment by jackyang1984** [comment]
me too
    "react": "^16.3.2",
    "react-native": "^0.55.2",
    "jest": "^22.4.3",
    "jest-react-native": "^18.0.0",

**Comment by jlala** [comment]
@jackyang1984 ok 了 没？

**Comment by sahil290791** [comment]
@lbrdar The fix for me was doing `pod install` after upgrading to RN.

**Comment by ChrisRyuGS** [comment]
Me too

  "devDependencies": {
    "axios-debug-log": "^0.4.0",
    "babel-eslint": "7.2.3",
    "babel-preset-react-native": "^4.0.0",
    "eslint": "4.4.1",
    "eslint-plugin-flowtype": "2.35.0",
    "eslint-plugin-import": "2.7.0",
    "eslint-plugin-jsx-a11y": "6.0.2",
    "eslint-plugin-prettier": "2.1.2",
    "eslint-plugin-react": "7.1.0",
    "eslint-plugin-react-native": "3.0.1",
    "flow-bin": "0.52.0",
    "flow-typed": "2.1.5",
    "husky": "0.14.3",
    "jest": "20.0.4",
    "jest-expo": "19.0.5",
    "prettier": "1.5.3",
    "react-native-clean-project": "^1.0.6",
    "react-test-renderer": "16.0.0-alpha.12",
    "remote-redux-devtools": "^0.5.12",
    "remotedev-rn-debugger": "^0.8.3"
  },
  "scripts": {
    "postinstall": "remotedev-debugger",
    "start": "react-native start",
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "test": "jest && eslint",
    "precommit": "yarn test"
  },
  "jest": {
    "preset": "react-native",
    "transformIgnorePatterns": [
      "node_modules/(?!(react-native|lottie-react-native|expo|react-native-maps|react-native-svg|react-native-branch|native-base-shoutem-theme|react-native-easy-grid|react-native-drawer|react-native-vector-icons|react-native-keyboard-aware-scroll-view|react-native-swiper|react-navigation|native-base|@expo|react-native-scrollable-tab-view|react-native-simple-modal)/)"
    ]
  },
  "dependencies": {
    "color": "1.0.3",
    "jest-cli": "20.0.4",
    "lodash": "^4.13.1",
    "moment": "2.13.0",
    "native-base": "^2.4.5",
    "npm": "^6.1.0",
    "parse-link-header": "^1.0.1",
    "react": "^16.3.1",
    "react-native": "^0.55.4",
    "react-native-async-storage-dev-menu-item": "^0.0.4",
    "react-native-axios": "^0.17.1",
    "react-native-calendars": "^1.19.3",
    "react-native-carousel-view": "^0.5.1",
    "react-native-device-info": "^0.13.0",
    "react-native-easy-grid": "0.1.15",
    "react-native-elements": "^0.18.5",
    "react-native-fcm": "^10.0.3",
    "react-native-htmlview": "^0.12.1",
    "react-native-modalbox": "1.4.2",
    "react-native-vector-icons": "^4.6.0",
    "react-navigation": "^2.0.4",
    "react-redux": "5.0.5",
    "redux": "3.7.2",
    "redux-form": "7.0.3",
    "redux-persist": "4.8.3",
    "redux-saga": "^0.16.0",
    "redux-thunk": "2.2.0",
    "reduxsauce": "^0.7.0",
    "regenerator-runtime": "^0.11.0",
    "url": "^0.11.0"
  }

**Comment by hramos** [comment]
Please follow one of the templates when filing a bug report: https://github.com/facebook/react-native/issues/new/choose
