### ISSUE TITLE
TextInput freeze and crash, Android

### ISSUE THREAD

**Issue by kulicuu** [facebook/react-native#18411]
#### Description
I coded a simple signin screen prototype with four `TextInput`s.  In both the simulator and my usb-connected Galaxy S8+, whichever TextInput is selected first is the only I can type into.  The others become unselectable.

### Environment

The Galaxy is now running Oreo.  The emulator is running 7.1.1.

`react-native info`:

```
Environment:
  OS: macOS High Sierra 10.13.3
  Node: 9.3.0
  Yarn: Not Found
  npm: 5.7.1
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: 0.54.0 => 0.54.0
```

### Expected Behavior

Click in one TextInput, enter some text... Select another TextInput, enter some text,...

### Actual Behavior

Click in one TextInput, enter some text,.. Then, attempt to select another TextInput but it is not selectable.

### Steps to Reproduce

I don't have time to set up a repo specifically to reproduce this issue.

**Comment by kelset** [comment]
> I don't have time to set up a repo specifically to reproduce this issue.

Then you could at least share the code because it looks like you have not wired the four TextInputs properly.

**Comment by kulicuu** [comment]
I fixed it somehow.  It may have been that I was subscribing to `onChange` events, whereas now I'm only subscribing to `onChangeText` events.
