### ISSUE TITLE
New in RN 0.54, Debugging on Android no longer resolve source maps 

### ISSUE THREAD

**Issue by aarondail** [facebook/react-native#18416]
Prior to Android 0.54 (at least as of 0.52.2) when I run my app on iOS or Android and turn on JS Debugging, then in Chrome I can find, see, and debug my source files (rather than the bundled file).

As of 0.54, this still seems to work on iOS, but no longer works on Android.

### Environment

```
Environment:
  OS: macOS Sierra 10.12.6
  Node: 9.8.0
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.5.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 2.3 AI-162.3934792

Packages: (wanted => installed)
  react: ^16.3.0-alpha.1 => 16.3.0-alpha.2
  react-native: 0.54.2 => 0.54.2
```

### Expected Behavior

When I run a RN app on Android, and launch the Chrome debugger I can see my source files, and debug them. 

### Actual Behavior

I can only see and debug the bundled file.

### Steps to Reproduce

Create a sample app using `react-native init` and run it on Android, and start JS Debugging.  Note that you can't find `App.js` via `CMD+P` and on the console lists all statements as coming from some `blob:http....` path.  E.g.
![android_source_maps_broken](https://user-images.githubusercontent.com/3768353/37542044-05819804-291a-11e8-906d-cf5758feb574.png)

*NOTE* you can workaround this by going to the dev settings (via CMD+M) and turning OFF `Use JS Deltas`

**Comment by suhshinhwang** [comment]
I also had to reset the packager and reload in Android.

**Comment by brookhong** [comment]
For those who need to work around this issue, https://stackoverflow.com/questions/49340074/chrome-debug-tools-for-react-native-mutiple-issues/49676564
