### ISSUE TITLE
Require error

### ISSUE THREAD

**Issue by rashthedude** [facebook/react-native#1841]
I might be missing something here even found a stackoverflow thread which was to no avail to me. So it seems that when I create standalone .js files and then module.exports = <className> and then try to require it in index.ios.js it throws this error: "Invariant Violation: Application <applicationName> has not been registered. This is either due to a require() error during initialization or failure to call AppRegistry.registerComponent". I have a strong suspicion that it's require related as opposed to AppRegistry. Any pointers?

**Comment by ide** [comment]
You could look in the Xcode console logs to see if there are any errors printed.

**Comment by rashthedude** [comment]
ld: warning: instance method 'eventDispatcher' in category from /Users/rashthedude/Library/Developer/Xcode/DerivedData/mobile_react-fquclettujfofmbvwahkxmoxvcdb/Build/Products/Debug-iphonesimulator/libReact.a(RCTEventDispatcher.o) overrides method from class in /Users/rashthedude/Library/Developer/Xcode/DerivedData/mobile_react-fquclettujfofmbvwahkxmoxvcdb/Build/Products/Debug-iphonesimulator/libReact.a(RCTBridge.o)

**Comment by rashthedude** [comment]
Not sure if that's the correct log since my knowledge of Xcode is non-existing at its best

**Comment by a2** [comment]
@rashthedude What does it show in the console? View > Debug Area > Activate Console

**Comment by rashthedude** [comment]
2015-07-02 23:05:31.273 [error][tid:com.facebook.React.JavaScript] "Error: Requiring unknown module "../Styles". If you are sure the module is there, try restarting the packager.
 stack: 
  <unknown>       index.ios.bundle:1119
  require         index.ios.bundle:244
  applyWithGuard  index.ios.bundle:880
  require         index.ios.bundle:195
  <unknown>       index.ios.bundle:42286
 URL: http://localhost:8081/index.ios.bundle
 line: 203
 message: Requiring unknown module "../Styles". If you are sure the module is there, try restarting the packager."
2015-07-02 23:05:31.362 [info][tid:com.facebook.React.JavaScript] "Running application "mobile_react" with appParams: {"rootTag":1,"initialProps":{}}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF"
2015-07-02 23:05:31.363 [error][tid:com.facebook.React.JavaScript] "Error: Invariant Violation: Application mobile_react has not been registered. This is either due to a require() error during initialization or failure to call AppRegistry.registerComponent.
 stack: 
  runApplication          index.ios.bundle:36295
  jsCall                  index.ios.bundle:7344
  _callFunction           index.ios.bundle:7610
  <unknown>               index.ios.bundle:7639
  <unknown>               index.ios.bundle:7633
  perform                 index.ios.bundle:6166
  batchedUpdates          index.ios.bundle:13887
  batchedUpdates          index.ios.bundle:4709
  <unknown>               index.ios.bundle:7632
  applyWithErrorReporter  index.ios.bundle:7379
  guardReturn             index.ios.bundle:7401
  processBatch            index.ios.bundle:7631
 URL: http://localhost:8081/index.ios.bundle
 line: 1730
 message: Invariant Violation: Application mobile_react has not been registered. This is either due to a require() error during initialization or failure to call AppRegistry.registerComponent."

**Comment by a2** [comment]
Are you trying to require a module outside of the root of the project? Why are you requiring '../Styles' and not "./Styles' or 'Styles'?

**Comment by rashthedude** [comment]
I'm trying to require a module that sits on the same path level as index.ios.js, even tried './Styles' and also 'Styles' same error is persistent.

**Comment by a2** [comment]
If *index.ios.js* is in the same directory as *Styles.js* then `require('./Styles')` should work. Can you set up a simple repro case app that has the bug you're describing?

**Comment by rashthedude** [comment]
I'm silly and sorry to have wasted your time but I forgot to require react-native in the Styles file and deconstruct the StyleSheet to be used.

**Comment by jmarakelian** [comment]
where would this require be placed. I've run across the same thing now and I'm trying to figure out where I am going wrong. Any help would be greatly appreciated.
