### ISSUE TITLE
NetInfo can't detect the wifi without Internet connection

### ISSUE THREAD

**Issue by armanbabai** [facebook/react-native#18423]
I use my device to connect to a wifi that does't connect to Internet. ButNetInfo.isConnected return true, I really can not visit Internet.

## Environment

Environment:
  OS: Windows 10
  Node: 9.4.0
  Yarn: 1.3.2
  npm: 5.7.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.0 => 0.54.0

**Comment by hramos** [comment]
Duplicate of #18424
