### ISSUE TITLE
[...Array(5).keys()] not working in Android

### ISSUE THREAD

**Issue by James2516** [facebook/react-native#18426]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

  OS: macOS Sierra 10.12.6
  Node: 9.8.0
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.3.0-alpha.1 => 16.3.0-alpha.2
  react-native: 0.54.2 => 0.54.2

### Steps to Reproduce

`console.log([...Array(2).keys()])` does not produce `[0, 1]`.

1. Run https://snack.expo.io/SJT6PCPPZ on Android (works)
2. Run https://snack.expo.io/H1elODwPb on Android (nothing rendered on screen)
Additional note: both works on iOS.

### Expected Behavior

https://snack.expo.io/H1elODwPb should render data on screen

### Actual Behavior

https://snack.expo.io/H1elODwPb renders nothing on screen

### Reproducible Demo

see above

**Comment by hramos** [comment]
Seems like a JavaScriptCore issue (this is the JavaScript engine used by React Native).

As a point of comparison, using V8 we get identical results:
```
[...Array(5).keys()].map(String)
(5) ["0", "1", "2", "3", "4"]
['0', '1', '2', '3', '4'].map(String)
(5) ["0", "1", "2", "3", "4"]
```

IIRC, we use a fork of the JSC on Android which diverged from what iOS provides.

**Comment by guhungry** [comment]
I also found this problem.
When I turn off 'Remote JS Debugging' it shows as [].
But when I turn on 'Remote JS Debugging' it shows [0, 1, 2, 3, 4].

![screenshot](https://user-images.githubusercontent.com/4032276/37819555-718a2476-2eb0-11e8-85d9-11b6b3ae2bfd.gif)

**Comment by hramos** [comment]
You're using a different JavaScript engine when remote JS debugging is turned on - possibly Chrome's (V8).

**Comment by James2516** [comment]
still not fixed.

**Comment by sonaye** [comment]
Workaround:

```js
Array(5).fill().map((_, index) => index)
```

**Comment by paulotfilho** [comment]
Workaround by @sonaye works properly, but issue is still not fixed.

**Comment by liuqiang1357** [comment]
+1

**Comment by James2516** [comment]
not yet fixed

**Comment by waveChand** [comment]
Not yet fixed. still happens when remote debugging turned off.

**Comment by hramos** [comment]
The JSC in Android was updated in December, it's in master. The new JSC will be part of the 0.59 release. Can you verify on master and let us know if it's still an issue?

**Comment by guhungry** [comment]
alert([...Array(2).keys()]) works in 0.59.0
![Screen Shot 2562-03-14 at 14 19 08](https://user-images.githubusercontent.com/4032276/54338363-42a08200-4664-11e9-8292-e4f269cab310.png)
