### ISSUE TITLE
iPhone 4 support?

### ISSUE THREAD

**Issue by jtremback** [facebook/react-native#1843]
Trying to start up `react-native init` project on an iphone 4. After a few minutes, a red screen comes up with an invariant violation.

A different app that I tried will start up, but has a lot of issues with the debugger websocket, and then a bunch of other issues.

Seems like iOS7, at least on this model of iPhone 4 is not supported?

**Comment by jtremback** [comment]
Just got the init project to work, I'm going to close this until I find out more about what is making my main project crash.

**Comment by MossP** [comment]
I know this is closed but just incase anyone else hits this... iOS7 responds differently to re-declared styles e.g.

```
var styles = StyleSheet.create({
    myStyle:{
        color:'#fff',
        color:'#fff',
    }
});
```

Will work on iOS 8 but will crash with a vague error message about unexpecten token ','.
