### ISSUE TITLE
KeyboardAvoidingView bug in Android in Screen pushed from a Screen with ScrollView!!!!

### ISSUE THREAD

**Issue by ibrahimyilmaz** [facebook/react-native#18433]
When I was building my project, I noticed a bug like that:

Screen A : It is react native component without `ScrollView` or `FlatList` or something containing ScrollView.

Screen B: It is react native component with `ScrollView` or `FlatList` or something containing ScrollView.

Screen C: It is react native component containing `KeyboardAvoidingView`

I open screen C classical this.props.navigator.push({ ScreenC some other params}) from both A and B.

KeyboardAvoidingView works as expected when it is called from A.

KeyboardAvoidingView works not normally when it is called from C. It is impossible to see the TextInput while typing.

My workaround was:

checking platform and if it is android, I remove `KeyboardAvoidingView` and changing `android:windowSoftInputMode` from adjustResize to adjustPan.

if it is ios, KeyBoardAvoidingView works perfectly. I don't remove anything. 

What is wrong with `ScrollView`  or something containing this component?

Thanks.

**Comment by ibrahimyilmaz** [comment]
How can I remove No Template label?

**Comment by hramos** [comment]
You can use the template.
