### ISSUE TITLE
Alert.alert without message kills apps even after refreshing

### ISSUE THREAD

**Issue by fullhdpixel** [facebook/react-native#18439]
Unrecognized selector sent to instance was thrown while invoking alertWithArgs on target AlertManager

![image](https://user-images.githubusercontent.com/7371397/37571169-568b47f0-2af9-11e8-8eb9-931736883f9f.png)
  
## Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 9.2.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.0 => 0.52.0

### Steps to Reproduce

https://snack.expo.io/SJG9v82Kz

See: https://stackoverflow.com/questions/41942681/alert-alert-alertmanager-with-params-exception

## Expected Behavior

No crash

## Actual Behavior

Crash

**Comment by fullhdpixel** [comment]
It has all necessary information

**Comment by siamakEsh** [comment]
Same issue.

**Comment by trev91** [comment]
Same issue. Anyone have a work around?

**Comment by fullhdpixel** [comment]
To fix it at least supply an empty string ''

Here is a fix for the reproduction 

 ```
Alert.alert('Uitloggen', 'Weet je zeker dat je wilt uitloggen?', [
      {
        text: 'Annuleer',
        style: 'cancel'
      }, {
        text: 'Ok',
        onPress: () => { //Go to walkthrough
          Meteor.logout()

          this
            .props
            .navigation
            .dispatch(NavigationActions.reset({
              index: 0,
              actions: [NavigationActions.navigate({routeName: 'Walkthrough'})]
            }))
        }
      }
    ], {cancelable: false})
```

**Comment by shamanking** [comment]
I have same issue with react-native version 0.55.2

**Comment by Tnarita0000** [comment]
If there is anything other than a string in the second argument, how do you issue an appropriate warning message in `console.warn`?

https://github.com/facebook/react-native/blob/d01ab66b47a173a62eef6261e2415f0619fefcbb/Libraries/Alert/AlertIOS.js#L89-L94  
If the type is not matched with the above optional argument of alert, it is better to issue an appropriate error.

I can add error message for not matched type errror.

**Comment by Samiksha19** [comment]
Alert.alert(
            '', /*/*You can add title here, if you don't want to then put only quotes here*/*/
            '', /*You can add message here, if you don't want to then put only quotes here*/
            [
                { text: 'Cancel', onPress: () => {}, style: 'cancel' },
                { text: 'OK', onPress: () => {
                    /* Your code goes here */
                    }
                }
            ],
        );

**Comment by ferrannp** [comment]
Hey, checking at your snack, you are calling `Alert.alert` like:

```js
Alert.alert('Uitloggen', [
{
  text: 'Annuleer',
  style: 'cancel'
},
{
  text: 'Ok',
  onPress: () =>
  console.log('not rekt')
}
], {cancelable: false})
```

This is not valid as you are passing an array as a second parameter. There is not such constructor. If you do not want a message (second parameter), just pass empty `string` or `null`.

If you think we should change the API for `Alert`, I encourage you to write your proposal at https://github.com/react-native-community/discussions-and-proposals.
