### ISSUE TITLE
Long TextInput not ellipsized on Android.

### ISSUE THREAD

**Issue by gourav-singhal** [facebook/react-native#18446]
Is this a bug report?
Yes.

Environment:
  OS: macOS High Sierra 10.13.1
  Node: 8.0.0
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.2 => 0.52.2

Steps to Reproduce
(Write your steps here:)

Create TextInput with long, text value, set editable to false
The text does not add ellipses at end  on Android whereas on iOS it does.

Actual Behavior
Text is cut short, like this on Android:
![screen shot 2018-03-19 at 2 59 02 pm](https://user-images.githubusercontent.com/22169281/37588130-53fa7b4e-2b87-11e8-8c0d-7ade1e0538c5.png)

 whereas on iOS it is properly ellipsized:- 
![screen shot 2018-03-19 at 3 03 45 pm](https://user-images.githubusercontent.com/22169281/37588161-6f710adc-2b87-11e8-9f85-6f86baea88b8.png)

**Comment by gourav-singhal** [comment]
Updated the environment info

**Comment by gourav-singhal** [comment]
Can anyone help me how to handle this?  As this doesn't seem something related to styling of component and seems to be a bug how react native is internally handling the entered input text when it is non editable.

**Comment by hramos** [comment]
Have you tried 0.54? TextInput was reworked recently.
