### ISSUE TITLE
[WebView Regression: commit ffbd3db] It is no longer possible (0.49-0.54) to retrieve Google AMP urls

### ISSUE THREAD

**Issue by ksegla** [facebook/react-native#18442]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

Google AMP is now how most news articles are loaded when someone makes a query on Google. Up to 0.48.4, it was possible to detect and manage (bookmark, etc.) page changes in that setting. I was on 0.48.4 and recently made the jump to 0.54. And my app can no longer detect those urls. I believe it is because of the commit [ffbd3db](https://github.com/facebook/react-native/commit/ffbd3db61bce21b9332f7783086fce703706031f) which went into effect starting from 0.49.

## Environment

Environment:
  OS: Windows 10
  Node: 6.11.4
  Yarn: Not Found
  npm: 5.7.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: 0.54.0 => 0.54.0

## Steps to Reproduce

```

import React, { Component } from 'react';
import { WebView } from 'react-native';

class MyWeb extends Component {

  onNavigationStateChange(navState) {
    alert(JSON.stringify(navState);
  }
  render() {
    return (
      <WebView
        source={{uri: 'https://www.google.ca/search?q=canada'}}
        onNavigationStateChange={ this.onNavigationStateChange.bind(this) }
        style={{marginTop: 20}}
      />
    );
  }
}

```

Use the component as a WebView and click on any news in the search results. It will likely be an AMP page. The first will fire the alert but with an outdated url. The subsequent pages won't do anything.

## Expected Behavior

Google AMP pages url are detected. An alert is generated for every AMP page and with the right url (i.e., contains an "/amp/")

## Actual Behavior

onNavigationStateChange() no longer detects change of url for pages like those from Google AMP. It used to, up to 0.48.4. This means those pages can no longer be directly bookmarked or simply managed.
This commit [ffbd3db](https://github.com/facebook/react-native/commit/ffbd3db61bce21b9332f7783086fce703706031f) is likely the cause of this regression.

**Comment by ksegla** [comment]
[ffbd3db](https://github.com/facebook/react-native/commit/ffbd3db61bce21b9332f7783086fce703706031f) is of benefit to many developers but I believe the best way to solve the problem would've been to introduce some boolean attribute and let developers decide for each WebView. Default value would give the new behavior. 
I'm looking into this but I'm not sure where to place that attribute. @rigdern Any way you could help with this?

**Comment by rigdern** [comment]
@ksegla I'm not familiar with AMP. Can you elaborate on the process used for doing a navigation when clicking on a link for an AMP page? For example, is the AMP page loaded within an iframe? React Native's `onNavigationStateChange` is hooked up to Android's [`onPageStarted`](https://developer.android.com/reference/android/webkit/WebViewClient.html#onPageStarted(android.webkit.WebView%2C%20java.lang.String%2C%20android.graphics.Bitmap)) event which fires for toplevel page loads.

I think we should get a better shared understanding of the problem and the scenario before picking a solution. As described in my commit message for ffbd3db61bce21b9332f7783086fce703706031f, the intent of the change was to make the Android API consistent with the iOS API and to enable the scenario of tracking toplevel page navigations which was previously hard/impossible due to the Android's `doUpdateVisitedHistory` event causing the navigation event to fire extra times.

Adam Comella
Microsoft Corp.

**Comment by ksegla** [comment]
@rigdern I couldn't confirm for sure that the AMPs are loaded within an iframe but it certainly looks like it. AMPs are only on mobile so I can't directly check the code and couldn't find definitive information on that. You can test AMP by entering terms likely to be in Top Stories: e.g. Game of Thrones etc. Those, on mobile, will have a flash icon near them and will be loaded in structures that look like Modals.

I understand your point about consistency with iOS but I don't think devs on Android should be held back by iOS limitations and vice versa. I'm not advocating for reverting the commit. It would cause a lot of pain for many projects. An Android only property on WebView would do the trick. I'm just not sure how to take it from a WebView all the way to `doUpdateVisitedHistory `.
Will try to find some time doing this in the next days.

**Comment by ksegla** [comment]
@rigdern 
FYI, I submitted PR [#18548](https://github.com/facebook/react-native/pull/18548) that introduces a new boolean parameter handleIFrameLoadingEvent. I tested it and it works as intended.

**Comment by jamonholmgren** [comment]
Migrated to https://github.com/react-native-community/react-native-webview/issues/15. This issue can be closed.
