### ISSUE TITLE
react-native run-android不动

### ISSUE THREAD

**Issue by ronniesir** [facebook/react-native#18445]
react-native run-android 卡在Loading from localhost：8081不动了
浏览器访问http://localhost:8081/显示React Native packager is running.

**Comment by robinxb** [comment]
Please try to describe your problem in English, and follow the the [Issue Template](https://raw.githubusercontent.com/facebook/react-native/master/.github/ISSUE_TEMPLATE.md).
请尽量尝试用英文描述您的问题，并且参考[问题模板](https://raw.githubusercontent.com/facebook/react-native/master/.github/ISSUE_TEMPLATE.md)。
