### ISSUE TITLE
[Android] react-native ART and RadialGradient

### ISSUE THREAD

**Issue by anthony-skr** [facebook/react-native#18448]
- [X] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [X] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment
  OS: Windows 10
  Node: 8.9.4
  Yarn: 1.5.1
  npm: 4.6.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.0.0.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.0 => 0.52.0

## Steps to Reproduce
Use react-native ART to draw a shape and fill it with RadialGradient.

```
import React from "react";
import { View, ART, StyleSheet } from "react-native";

const { Surface, Shape, Group, Path, RadialGradient, LinearGradient } = ART;

const fullRectangle = (width, height) => {
  const d = new Path();
  d.moveTo(0, 0);
  d.lineTo(width, 0);
  d.lineTo(width, height);
  d.lineTo(0, height);
  d.lineTo(0, 0);
  return d;
};

export default (props) => (
    <Surface style={styles.surface} width={props.width} height={props.height}>
      <Group>
        <Shape
          d={fullRectangle(props.width, props.height)}
          fill={
            new RadialGradient(
              {
                ".1": "blue", // blue in 1% position
                "1": "rgba(255, 255, 255, 0)" // opacity white in 100% position
              },
              "200",
              "200",
              "0",
              "0",
              "0",
              "400"
            )
          }
        />
      </Group>
    </Surface>
);
```

## Expected Behavior
Shape should be filled with a radial gradient. 

## Actual Behavior
Shape filled in black. 
Whatever parameters/colors I use.

note: fill with a solid color or linear gradient is working.

**Comment by anthony-skr** [comment]
same with 0.54

**Comment by carmenchapa** [comment]
@anthony-skr did you find a solution for that?

**Comment by hramos** [comment]
Looks like the original author found a workaround. If anyone else wants to open a new issue, feel free to do so.
