### ISSUE TITLE
scrollEventThrottle has no effect on SectionList

### ISSUE THREAD

**Issue by hugofelp** [facebook/react-native#18441]
`scrollEventThrottle` doesn't seem to make any difference when applied to `SectionList`. It works as expected with `ScrollView`.

## Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.9.4
  Yarn: 1.2.1
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.3.0-alpha.1 => 16.3.0-alpha.2
  react-native: 0.54.2 => 0.54.2

## Steps to Reproduce
```
export default class App extends Component<Props> {
  render() {
    return (
      <View style={styles.container}>
        <ScrollView
          scrollEventThrottle={ 1000 }
          onScroll={ e => console.log( Date.now() ) }
        >
          <Text>ScrollView Text</Text>
        </ScrollView>


        <SectionList
          renderItem={ ( { item } ) => <Text>SectionList Text</Text> }
          sections={ [ {
            title: 'section title',
            data: [ 'item' ]
          } ] }
          scrollEventThrottle={ 1000 }
          onScroll={ e => console.log( Date.now() ) }
        />
      </View>
    );
  }
}
```

## Expected Behavior
The events logged to the console should have at least 1000ms between them.

## Actual Behavior
SectionList logs events at high rates regardless of the value passed to `scrollEventThrottle`

**Comment by tangkunyin** [comment]
Is this problem solved now?

**Comment by hugofelp** [comment]
I don't know stale bot! I don't know...

**Comment by grabbou** [comment]
I see there's a `todo` note around `scrollEventTrottle` in VirtualizedList -> https://github.com/facebook/react-native/blob/master/Libraries/Lists/VirtualizedList.js#L921. Are you running this on Android by any chance?

CC: @sahrens do you happen to have some context into what's left there to support it and whether this issue could be related?

**Comment by BrodaNoel** [comment]
This has effect even in `<ScrollView>`: https://snack.expo.io/rkgPA5FkH
