### ISSUE TITLE
How about `Animated.subtract`?

### ISSUE THREAD

**Issue by dgreensp** [facebook/react-native#18451]
I'm finding myself typing `Animated.add(x, Animated.multiply(-1, y))` a lot.

Would you take a PR that adds an `Animated.subtract`?

**Comment by hramos** [comment]
cc @janicduplessis

**Comment by janicduplessis** [comment]
Sure, we have Animated.divide so I guess substract does make sense too. If you want to make a PR for it I can review it, it should be relatively simple if you start from the add implementation.

**Comment by avendiart** [comment]
Hey, @dgreensp are you working on it? Or is it something I could take on?

**Comment by dgreensp** [comment]
@avendiart Go for it!
