### ISSUE TITLE
autoCorrect not working on android api 27

### ISSUE THREAD

**Issue by jimji1005** [facebook/react-native#18457]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

On android api 27, autoCorrect={false} of TextInput does not disable auto suggest.

## Environment
Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.6.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.3.0-alpha.1 => 16.3.0-alpha.2
  react-native: 0.54.2 => 0.54.2

## Steps to Reproduce
1. clone repo, yarn, run-android
https://github.com/jimji1005/rn-android-keyboard-bug
or

1. react-native init testProject
2. add TextInput and autoCorrrect={false}
3. launch on android emulator or device with api 27
4. type into textinput

## Expected Behavior
auto suggest would be disabled

## Actual Behavior
auto suggest still working

![rn0bug-android-keyboard](https://user-images.githubusercontent.com/5834998/37637302-1b94f0a8-2bc4-11e8-97c0-f3af09993c88.gif)

**Comment by jimji1005** [comment]
Works correctly on API26

![rn0bug-android-keyboard0](https://user-images.githubusercontent.com/5834998/37638994-ed00862c-2bcc-11e8-92da-d8e74c2423ca.gif)

**Comment by tomdev-biz** [comment]
@jimji1005 till the bug is fixed, you can use 'email-address' keyboard type.

**Comment by SwiftPolar** [comment]
@tomdev-biz That's the workaround I'm currently using too

Can confirm on this particular bug.

**Comment by pennyandsean** [comment]
Unfortunately `visible-password` doesn't work for my application as I need `autoCapitalize="characters"` as well which isn't available with `visible-password`

**Comment by tomdev-biz** [comment]
@pennyandsean if you update your react-native version, `visible-password` will work.
On some android devices, `email-address` not working as expected, so I also suggest to use `visible-password` with updating your react-native version.

**Comment by binki** [comment]
Even though you say that Android isn’t respecting `autoCorrect={false}`, it actually is. It will not automatically highlight the most likely candidate and replace it when you type `.`, ` `, etc.. However, if you put `autoCorrect={true}`, it will automatically choose and correct with the most likely candidate. I.e., autocorrect is disabled but autosuggestions aren’t.

Have you actually tried typing? In your video, I only see you clicking directly on the autosuggestions but not actually demonstrating autoCorrect in action.

Sorry I am unable to actually try building with Android Studio at the moment. My observations are from using Expo on my Android-8.1 phone. I made a [video demonstrating that `autoCorrect={false}` works as I described](https://www.youtube.com/watch?v=T7o9uBlwFHs).

**Comment by kevinkevw** [comment]
Unfortunately, both `email-address` and `visible-password` doesn't fit the multi-line usage. It will cause the textInput to ignore the multiline props and/or the return key not going to the next line.

**Comment by florindumitru** [comment]
I have the same problem :(

**Comment by Haskkor** [comment]
Working for us with `visible-password` but we had to remove our `autoCapitalize` and our `multiline` configuration.

**Comment by ericjames** [comment]
Confirm visible-password disables autocorrect on Android 6.0
