### ISSUE TITLE
Cannot run React Native app on Android device

### ISSUE THREAD

**Issue by t0msk** [facebook/react-native#18450]
Hello, I followed this tutorial https://facebook.github.io/react-native/docs/getting-started.html, when I type `npm start`, and I press `a to open Android device`, then I get this error message on my Android phone https://i.imgur.com/bVbNgRF.png

Please how to fix it?
That app what I am trying to run is from default `create-react-native-app` command.

IDE: Atom
OS: Windows 7 x64 Home Premium
Android version: 8 oreo
React Native version: Latest

**Comment by t0msk** [comment]
Yes, I think that I provided all the relevant information.

And command `react-native info` doesn't work on Windows 7.

**Comment by danielFmitchell** [comment]
Try troubleshooting as outlined in <a href="https://github.com/react-community/create-react-native-app/issues/598">this </a>issue.

**Comment by hramos** [comment]
This issue belongs in https://github.com/react-community/create-react-native-app
