### ISSUE TITLE
rctfatal + 400

### ISSUE THREAD

**Issue by aantonyuk** [facebook/react-native#18452]
Many users when work with app face the issue: app crashes.
The only thing that was able to track:

<img width="1349" alt="screenshot at mar 19 21-53-07" src="https://user-images.githubusercontent.com/26109453/37616113-fefd10a0-2bbf-11e8-8ffc-64a321d1080a.png">

My dependencies:

<img width="1212" alt="screenshot at mar 19 21-53-27" src="https://user-images.githubusercontent.com/26109453/37616147-13a4deca-2bc0-11e8-9e8e-f41d00fc01f1.png">

**Comment by aantonyuk** [comment]
@react-native-bot Yes, I think that I provided all the relevant information.

**Comment by hramos** [comment]
Can you please fill out the template? You're missing quite a bit of required information. Thanks!

**Comment by gauravds** [comment]
Any solution about this issue, my all 5 apps are facing the same launch crashing, I don't have any clue. What's wrong, where to start debugging, unable to reproduce, crashes on random devices.

**Comment by hramos** [comment]
@gauravds please open a new issue with more details about your situation.

**Comment by tessy2728** [comment]
Same issue happening here.
RCTFatal + 400
"react": "16.2.0",
"react-native": "0.51.0",
Debug build just works fine on devices (ios), but the release not.
This app requires pushnotification permission 

![screen shot 2018-09-06 at 8 27 53 pm](https://user-images.githubusercontent.com/19467909/45434803-e4064580-b6cc-11e8-9128-3062ef71b4ce.png)
