### ISSUE TITLE
Flatlist with Combobox (react-native-element) works in-case the screen re-rendering

### ISSUE THREAD

**Issue by zxccvvv** [facebook/react-native#18459]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [ ] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment:
  OS: Windows 10
  Node: 8.9.1
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  2.1.0.0 AI-143.2915827

Packages: (wanted => installed)
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: ^0.53.0 => 0.53.0

## Steps to Reproduce
I want to create dynamic checkbox depending of json fetching, but I don't know why the checkbox works in-case the screen re-render with `Hot Reloading Enabled`

here's the full code :

```
import React, { Component } from 'react';
import {
  Text, View, StyleSheet, Alert, FlatList
} from 'react-native';
import Dimensions from 'Dimensions';
import { CheckBox } from 'react-native-elements'

const DeviceWidth = Dimensions.get('window').width;
const DeviceHeight = Dimensions.get('window').height;

class MedicalClearlance extends React.Component {

  constructor(props){
    super(props); 
    this.state = {
      checked:[],
      data : [
      {
        "name": "ALL",
      },
      {
        "name": "Android",
      },
      {
        "name": "iOS",
      },
      {
        "name": "React Native",
      }
    ]}
  }

  componentWillMount() {
    let { data, checked } = this.state;
    let intialCheck = data.map(x => false);
    this.setState({ checked: intialCheck })
  }

  handleChange = (index) => {
    let { checked } = this.state;
    checked[index] = !checked[index];
    this.setState({ checked });
  }

  render() {
    let { data, checked } = this.state;
    return (
      <FlatList
        data={data}
        renderItem={({ item, index }) =>
          <CheckBox
            center
            title={item.name}
            onPress={() => this.handleChange(index)}
            checked={checked[index]} />
        }
      />
    );
  }
}
export default MedicalClearlance;
```

## Expected Behavior
the checkbox component must changed from checked to uncheck or reversing the state without re-rendering,

## Actual Behavior
the checkbox component work's in-case the screen re-render with `Hot Reloading`

**Comment by zxccvvv** [comment]
@react-native-bot edited

**Comment by hramos** [comment]
This reads more like a call for help rather than a description of a particular issue. Unless this describes a regression (this used to work on version X), this type of issue is not something we're tracking in the repo.
