### ISSUE TITLE
Use android's WebViewClient (shouldOverrideUrlLoading) for rn (onShouldStartLoadWithRequest) WebView?

### ISSUE THREAD

**Issue by IljaDaderko** [facebook/react-native#18463]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 9.8.0
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.3.0-alpha.1 => 16.3.0-alpha.2
  react-native: ^0.54.2 => 0.54.2

## Steps to Reproduce

Implement https://facebook.github.io/react-native/docs/webview.html#onshouldstartloadwithrequest and test functionality in Android, it won't work as only iOS is supported as platform.
I was scouting through Android WebViewCLient docs and found this:

https://developer.android.com/reference/android/webkit/WebViewClient.html#shouldOverrideUrlLoading(android.webkit.WebView,%20android.webkit.WebResourceRequest)

To me above seems like possible implementation for Android `<WebView />` to support  `onShouldStartLoadWithRequest`? If I am correct I could try and give this a shot in terms of PR, could you give me some guides on how to start though? Never worked with any sort of Android to react-native bridging.

## Expected Behavior

For cross platform consistency `onShouldStartLoadWithRequest` could be added to Android.

## Actual Behavior

`onShouldStartLoadWithRequest` only supported in iOS at the moment.

**Comment by hramos** [comment]
There's a lot of existing discussion around what we should do with WebView in the repo. I would not open a PR against WebView at this point. If you search for issues tagged with WebView and "For Discussion" you'll find the thread where this is being discussed. Thanks!

**Comment by braydo25** [comment]
https://github.com/lucasferreira/react-native-webview-android/pull/98
