### ISSUE TITLE
textAlign does not work for components wrapped in a View inside Text 

### ISSUE THREAD

**Issue by n-kumari** [facebook/react-native#18469]
## Description

`textAlign ` style prop does not work when the components nested in a `Text` are wrapped in a `View`.

This happens only on iOS and looks like it broke in 0.54.2 version.

## Environment
  OS: macOS Sierra 10.12.6
  Node: 8.9.1
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.0 Build version 9A235
  Android Studio: Not Found

Packages: (wanted => installed)
  react: ^16.3.0-alpha.1 => 16.3.0-alpha.2
  react-native: 0.54.2 => 0.54.2

## Steps to Reproduce

[Could not use snack to reproduce this issue since it happens only on React Native 0.54.2]

Use following code in your render function

```
  render() {
    if (Platform.OS === 'ios') {
      return (
        <Text style={{textAlign: 'right'}}>
          <View style={{paddingTop: 50}}>
            <Text>
            {'I should be aligned right'}
            </Text>
          </View>
          </Text>
      );
    }
      return (
        <Text style={{textAlign: 'right'}}>
          <Text>
          {'I should be aligned right'}
          </Text>
        </Text>
      );
  }
```

Note: `View` is not supported inside `Text` on Android. Hence, this code does a platform check and does not nest `View` inside `Text` on Android. The issue is seen only when `View` is nested inside `Text` i.e., only on iOS.

## Expected Behavior

The text should be aligned to the right

## Actual Behavior

For iOS, in React Native 0.54.2, the text is aligned to the left.

| Android (RN 0.54.2) :white_check_mark: | iOS  (RN 0.54.2) :x: |
| --- | --- |
|<img width="399" alt="android54 2" src="https://user-images.githubusercontent.com/30132665/37675059-a8ff13f2-2c4a-11e8-8ee4-1b53e957956a.png">|<img width="408" alt="ios54 2" src="https://user-images.githubusercontent.com/30132665/37675071-b0b1cce8-2c4a-11e8-9330-d449195898e6.png">|

As seen from screenshots below, it works correctly in React Native 0.53.3 

| Android (RN 0.53.3) :white_check_mark: | iOS  (RN 0.53.3) :white_check_mark:|
| --- | --- |
|<img width="398" alt="android53 3" src="https://user-images.githubusercontent.com/30132665/37673835-a7ab1e54-2c47-11e8-9aab-40b0936f1b1c.png">|<img width="412" alt="ios53 3" src="https://user-images.githubusercontent.com/30132665/37673857-b1d7ceb8-2c47-11e8-87f7-0d92c1555706.png">|

**Comment by n-kumari** [comment]
This issue is resolved if we add text to the `Text` component. I added a text `Here` to the previous code.

```
render() {
    if (Platform.OS === 'ios') {
      return (
        <Text style={{textAlign: 'right'}}>
        {'Here'}
          <View style={{paddingTop: 50, height: 100, width: 170}}>
            <Text>
            {'I should be aligned right'}
            </Text>
          </View>
          </Text>
      );
    }
      return (
        <Text style={{textAlign: 'right'}}>
          <Text>
          {'I should be aligned right'}
          </Text>
        </Text>
      );
  }
```

Adding a text fixes the alignment (as seen in the scrrenshot below)
<img width="411" alt="screen shot 2018-03-20 at 2 37 46 pm" src="https://user-images.githubusercontent.com/30132665/37675743-6eb30a62-2c4c-11e8-8279-322135dc8671.png">

**Comment by asowayan** [comment]
@shergin I am wondering if this is related to the recent Text refactoring on iOS (which were awesome)

**Comment by asowayan** [comment]
@hramos I am wondering if this is related to the recent Text refactoring on iOS (which were awesome)

**Comment by n-kumari** [comment]
Yes, this can be reproduced with the latest release, v0.55
