### ISSUE TITLE
Is RNTester still in maintain?

### ISSUE THREAD

**Issue by gengjiawen** [facebook/react-native#18460]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

From the commit history, it looks like that it not active for a while (like old api like mixin and no actual change to js file). And it also contains build bug in android (react root is not configure right). 

So my question is that:
* If it is not in the plan, can I create a pr to replace it with a simple Hello world app for easily do the android test. 
* If it still in the plan, I will create a pr to fix the android build problem.

**Comment by hramos** [comment]
RNTester is still maintained, as it's part of our test infrastructure. It was renamed last year to RNTester to make it clear it's part of the test suite and not intended to be a showcase of example code (as it was originally intended).

I am not aware of the Android issue, and I would appreciate a PR to address it.

**Comment by hramos** [comment]
Answered.

**Comment by gengjiawen** [comment]
Thanks, I will create a pr to fix this, maybe integrate this into ci.
