### ISSUE TITLE
[WebView] Error trying to display PDF in web view component

### ISSUE THREAD

**Issue by javierM84** [facebook/react-native#1846]
Hello,

I am trying to display a pdf file from the app bundle but I could not do it, this is what I have done:

                <WebView
                    startInLoadingState={true}
                    style={styles.web}
                    url={"localFile.pdf"}
                    />

localFile.pdf is obviously included in the bundle but when I try to display this webview it doesn't show it properly.

From xcode I have got these error messages:

[85869:8794860] DiskImageCache: Could not resolve the absolute path of the old directory.
[85869] <Error>: CGAffineTransformInvert: singular matrix.
[85869] <Error>: CGAffineTransformInvert: singular matrix.
[85869] <Error>: CGAffineTransformInvert: singular matrix.

And I can't see it

**Comment by javierM84** [comment]
TEMPORARY SOLUTION:

I have modified the class RCTWebView and method initWithEventDispatcher to have something like this:

- (instancetype)initWithEventDispatcher:(RCTEventDispatcher *)eventDispatcher
{
  RCTAssertParam(eventDispatcher);

  if ((self = [super initWithFrame:CGRectZero])) {
    super.backgroundColor = [UIColor clearColor];
    _automaticallyAdjustContentInsets = YES;
    _contentInset = UIEdgeInsetsZero;
    _eventDispatcher = eventDispatcher;
    _webView = [[UIWebView alloc] initWithFrame:[[UIScreen mainScreen]bounds]];
    _webView.delegate = self;
    [self addSubview:_webView];
  }
  return self;
}

the key to solve the problem it has been the line:

**_webView = [[UIWebView alloc] initWithFrame:[[UIScreen mainScreen]bounds]];**

previously it was something like this: 

**_webView = [[UIWebView alloc] initWithFrame:self.bounds];**

I guess there is  some issue getting the bounds of the webview, that's why I have specified the main screen bounds.

**Comment by adnanakbar** [comment]
@javierM84 you are a champion! Been struggling with this for days and today thought to put this as an issue and you already have a work around and it works! :)

**Comment by michaelfranz** [comment]
Great job!

**Comment by javierM84** [comment]
thx for the compliment,  I was struggling with this issue too and I thought that maybe this could help to more people temporarily

**Comment by nicklockwood** [comment]
Hmm, the issue I have with this is that the webview may not be the full size of the screen, so using :`[[UIScreen mainScreen] bounds]` seems questionable.

If I understand correctly, the problem is that self.bounds is {0,0,0,0} when the view is first created, and the webview doesn't like trying to display a PDF when it's size is zero. I guess the solution is either to defer setting the content until the webview has been sized correctly, or to init the webview with some temporary nonzero size, and then set it correctly later.

**Comment by javierM84** [comment]
yes totally  agree this not a correct solution,  we should provide the correct size of the webview. 

I guess it works because internally the value is adjusted

**Comment by brentvatne** [comment]
I agree with @nicklockwood's assessment - if you are using `flex` attributes, add an `onLayout` callback and set the state to point to the pdf in there.

**Comment by booxood** [comment]
Finally, how to solve? 

I also have the questions...  :joy:  #2188

**Comment by sbdd** [comment]
If this is still an issue you can just inject the html and open the file with javascript eg.
```javascript
var html = '<body style="margin:0;padding:0;width:100%;height:100%;">' +
            '<div class="">Opening PDF</div>' +
            '<script type="text/javascript">window.location.href="' + this.props.url + '"</script>' +
            '</body>';
        var options = {
            automaticallyAdjustContentInsets: false,
            html: html,
            style: {
                flex: 1,
                marginTop: 55
            }
        };
        return React.createElement(WebView, options);```

**Comment by julianacipa** [comment]
@javierM84 Thank you for your help Javier!

**Comment by julianacipa** [comment]
``` <WebView
                startInLoadingState={true}
                style={styles.web}
                url={"localFile.pdf"}
                /> ```
Removing the startInLoadingState={true} line fixes the issue. The pdf gets displayed

**Comment by brentvatne** [comment]
Thanks @julianacipa for the follow up!

**Comment by SFantasy** [comment]
@julianacipa Thank you for help :+1:

**Comment by alvaromb** [comment]
Does this work on Android? I can show the pdf in iOS but not in Android.

**Comment by tommywu23** [comment]
great job!

**Comment by esthersweon** [comment]
I also am not able to get this working in Android.

**Comment by bomalley** [comment]
I can't even get this to work on iOS.  I must be missing something in the source attribute now the URL is deprecated.  

`<WebView source={require('./foobar.pdf')}/>`

That fails with _Unable to resolve module_.

Can anyone point me in the right direction?

**Comment by bomalley** [comment]
Okay, for future generations, here's how I solved this problem:

**iOS only**

    render: function() {
      return <WebView source={{uri: 'My.pdf'}}/>
    }

The trick is that you need to include `My.pdf` into your project in Xcode and make sure it's added to your build target.

Just copying it into your React Native project folder wasn't enough. It had to be part of the Xcode project itself.

**Comment by bomalley** [comment]
@nicklockwood The require syntax did not work for me.  It worked if I wanted to load an html file, but replace `.html` with `.pdf` and it fails.

**Comment by ivesy85** [comment]
@brentvatne The only way I have ben able to get this to work is using the hack method that @javierM84 originally posted. Just wondering f you could elaborate on your solution of adding an onLayout callback. My code is like this

var React = require('react-native');

var {
    StyleSheet,
    WebView
    } = React;

var styles = StyleSheet.create({
    container: {
        flex: 1,
        flexDirection: 'column'
    }
});

class ContentView extends React.Component {
    render(){
        var url = this.props.url;
        return (
            <WebView
                ref={'webView'}
                style={styles.container}
                source= {{uri: url}}
                scalesPageToFit={true}
                javaScriptEnabled={true}
                domStorageEnabled={true}
                decelerationRate="normal"
                startInLoadingState={true}
                automaticallyAdjustContentInsets={true}
            />
        )
    }
}

module.exports = ContentView;

**Comment by nicklockwood** [comment]
@bomalley The fix is just to add the "pdf" file extension in all the places where I added "html" and other extensions in this PR:

https://github.com/facebook/react-native/commit/81fb985335a8ee3657905177abe32380b6b5fdc0#commitcomment-15932047

If you want to put up a PR for that, I'll accept it.

**Comment by agtb** [comment]
@javierM84 thanks, your [temp fix](#issuecomment-118001234) fixed the intermittent `CGAffineTransformInvert: singular matrix` errors I was seeing and associated rendering fail (white screen) loading PDFs in a WebView on iOS.

**Comment by andy9775** [comment]
I still seem to be getting this error in RN 0.44, although it's intermittent

**Comment by stantoncbradley** [comment]
for anyone looking to fix this with layoutChanged, this worked for me:
```
constructor() {
    super();
    this.state = {
      layoutChanged: false,
    };
  }

  renderPDF = () => (
    <WebView
      source={{ uri: this.props.navigation.state.params.url }}
    />
  )

  render() {
    return (
      <View
        style={styles.container}
        onLayout={() => this.setState({ layoutChanged: true })}
      >
        {this.state.layoutChanged ? this.renderPDF() : <View style={styles.container} />}
      </View>
    );
  }

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.nearWhitePrimary,
  },
```

**Comment by Elijen** [comment]
@brentvatne online PDFs not loading with `startInLoadingState={true}` seems to be a bug in `WebView`. Shouldn't this issue be re-opened?

**Comment by brunoti** [comment]
> @brentvatne online PDFs not loading with startInLoadingState={true} seems to be a bug in WebView. [...]

Same here

**Comment by brunoti** [comment]
With ``startInLoadingState={true}`` and ``renderLoading={() => <Spinner />}`` to load an online PDF it only shows a blank screen. Removing the quoted props it works normally, but shows an annoying black screen while loading the PDF

**Comment by sooyang** [comment]
I need to render a pdf online which is why `startInLoadingState={true}` to be helpful to indicate that the page is loading to users. But I came across the same issue that the pdf does not render after setting `startInLoadingState={true}`.

My workaround for this is as follows: 
```
class MyWeb extends Component {
  constructor() {
    super();
    this.state = {
      loaded: false,
    };
  }

  render() {
    return (
      <View style={{flex: 1}}>
        <WebView
          source={{ uri: 'facebook.com' }}
          style={{ flex: 1 }}
          onLoadEnd={() => this.setState({ loaded: true })}
        />
        {this.state.loaded ? null : <ActivityIndicator animating size="large" style={{flex: 1}} />}
      </View>
    );
  }
}
```

Using `state`, if the page is not loaded I will display my own `ActivityIndicator`. 
`WebView` have a function `onLoadEnd` which is called when `WebView` load succeeds or fails. I will use the callback to set the state `loaded` to `true` thus hiding the `ActivityIndicator` and display the `WebView` instead

**Comment by brunoti** [comment]
Sometimes the PDF don't open and it just shows a white screen.

Is this a react-native problem or an iOS Webview problem? Any news?

I think this issue should be reopened.

**Comment by willdurand** [comment]
We are experiencing the same issue as reported by @brunoti. PDFs fail to load for no obvious reason.
