### ISSUE TITLE
KeyboardAvoidingView not working with TabNavigator

### ISSUE THREAD

**Issue by thangkho** [facebook/react-native#18465]
I use StackNavigator and Tabnatigator in my app.
Struct of StackNavigator:
StackNaviGator
-Login
-TabNavigator
---- Home
---- List
---- Setting
In Setting component I have TextInput multiple line. I want when focus in text input and enter more line keyboard will push text so I used KeyboardAvoidingView.
When I test KeyboardAvoidingView in Login.js it work fine but when I add it in Setting.js it have bug.
Here is my code in component and result
https://ibb.co/dJTBsx

**Comment by thangkho** [comment]
I asked it in  https://stackoverflow.com/questions/49363932/keyboardavoidingview-not-working-with-tabnavigator before ask in here

**Comment by MuruganandaMukesh** [comment]
@thangkho How did you fixed it? I have the same issue here. Do help me out..
