### ISSUE TITLE
Pointlessly cryptic error message when creating a component starting with a lowercase letter

### ISSUE THREAD

**Issue by getaaron** [facebook/react-native#18473]
If you try to render a component and it starts with a lowercase letter, you'll see an error like:

> Invariant Violation: View config not found for name myComponent

This error message is confusing and doesn't offer any recovery suggestions.

We should change this to say:

> Invariant Violation: View config not found for name myComponent. You probably made a component that starts with a lowercase letter. Try changing it to an uppercase letter.

Looks like this would need to be changed in a total of four places (twice in each of two files):

https://github.com/facebook/react-native/blob/22004db81912f66650e9f9776d0045b88df61b5b/Libraries/Renderer/ReactFabric-prod.js#L5652-L5663

https://github.com/facebook/react-native/blob/22004db81912f66650e9f9776d0045b88df61b5b/Libraries/Renderer/ReactNativeRenderer-prod.js#L6060-L6069

I would be happy to open a PR to resolve this if someone can explain the difference between `ReactFabric-prod.js` and `ReactNativeRenderer-prod.js` and which of the 4 strings should be modified.

**Comment by hramos** [comment]
Feel free to open a PR. You'll need to update all occurrences of the string for the time being until the ReactFabric experiment is merged in or removed.

**Comment by hramos** [comment]
Answered.

**Comment by getaaron** [comment]
@hramos Thanks for the quick answer. I don't know what "the ReactFabric experiment" is but I opened a PR (#18488) replacing all instances of the string.
