### ISSUE TITLE
shake phone in android release mode opens debug menu

### ISSUE THREAD

**Issue by JFE84** [facebook/react-native#18478]
- [X] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [X] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [X] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

issue on current and latest version (downgraded due to another bug in latest version which prevents me from building app but, it isn't present in this version)

## Environment
Environment:
  OS: macOS High Sierra 10.13.3
  Node: 9.8.0
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: ^0.53.0 => 0.53.0

## Steps to Reproduce
Build release mode on android and shake the phone

## Expected Behavior
nothing

## Actual Behavior
debug menu comes up

**Comment by hramos** [comment]
Interesting, the debug menu should not open in release mode. Can you include the specific steps followed to enable release mode? I am surprised this has not been brought up before.

**Comment by JFE84** [comment]
first I run this in terminal
react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res

then android studio
build --> generate signed apk
build type: release
signature versions: [x]V1 (Jar Signature) [x]V2 (Full APK Signature)
