### ISSUE TITLE
Height of the root view is incorrect after device is rotated from landscape to portrait

### ISSUE THREAD

**Issue by liubolightning** [facebook/react-native#18475]
## Steps to Reproduce
My react native app is integrated with native android app. And react native root view is hosted in a DialogFragment. Whenever the device has rotated from landscape to portrait while the dialog is on, the height of the root view is shorter than it should be (the height of dialog fragment). I have tried to debug and found that the height on e.nativeEvent.layout in onLayout method of my react native component is wrong.

## Expected Behavior
On rotation from landscape to portrait, height of the root react native component should be that of the host window.

## Actual Behavior
height is shorter than that of the host window

**Comment by hramos** [comment]
Please fill out the rest of the template, this issue is lacking some required fields. Thanks!

**Comment by liubolightning** [comment]
Deeper debugging reveals that height from ReactRootView::OnMeasure() is wrong in the case of rotation from landscape to portrait.
