### ISSUE TITLE
Animated.timing() with useNativeDriver laggy / slow on Android

### ISSUE THREAD

**Issue by jeremyblalock** [facebook/react-native#18476]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment

```
Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.6.0
  Yarn: 1.3.2
  npm: 5.7.1
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.0 => 0.52.0
```

**Note:** Running on Galaxy S8 running Android version 7.x.

## Steps to Reproduce

* Create a `new Animated.Value()`
* Animated the value using `Animated.Timing()`, with `useNativeDriver = true`
* Set the style attribute of a large `Animated.View` to:
  `{[styles, { transform: { translateX: myValue } }]}`
* Create a trigger element to trigger the animation

**I have created an example project here which exhibits this behavior: https://github.com/jeremyblalock/RNAnimationTest**

## Expected Behavior

Because we're using `useNativeDriver: true`, I expected the animation performance to be high, comparable to a native animation.

## Actual Behavior

* The frame rate on android appears to be around 10-15 fps, much lower than expected
* This is the case even for _very_ simple apps with no HTTP calls / etc.
* For simple apps, `useNativeDriver` actually significantly _decreases_ performance on Android

**Comment by jeremyblalock** [comment]
@react-native-bot: 0.52.0 is the latest version supported by [create-react-native-app](https://github.com/react-community/create-react-native-app), as well as Expo. Hence it is easier to demonstrate the issue at this version. The issue seems to persist in 0.54 though, from my testing.

**Comment by hramos** [comment]
That's fine, we can make an exception for issues that are reproduced using Expo and that are likely to still be present in latest.

**Comment by slegaitis** [comment]
Same here

**Comment by pohsiu** [comment]
find out it was background image cause this issue
