### ISSUE TITLE
[Android] Picker inside <View style=flexDirection:'row'> makes Picker invisible to add Icon next to Picker Component

### ISSUE THREAD

**Issue by zxccvvv** [facebook/react-native#18480]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [ ] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment
  OS: Windows 10
  Node: 8.9.1
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  2.1.0.0 AI-143.2915827

Packages: (wanted => installed)
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: ^0.53.0 => 0.53.0

## Steps to Reproduce
I want to add an Icon next to picker, so I'm tried to do like TextInput ( Using flex:1, flexDirection:'row', justifyContent&AlignItem : 'center'), but I don't now why when I'm using `flexDirection:'row'`, the picker itself seems like disappear, 
Reference : [#18280](https://github.com/facebook/react-native/issues/18280)

without `flexDirection:'row' :

![image](https://user-images.githubusercontent.com/19633881/37699012-08a0672a-2d18-11e8-9ccc-503e303b3d83.png)

with `flexDirection:'row' and add an Icon :

![image](https://user-images.githubusercontent.com/19633881/37699048-3148ea9e-2d18-11e8-8e01-cc603d92edfc.png)

Recent Code :
```
import React, { Component } from 'react';
import {
  Text, View, Picker, TouchableOpacity, StyleSheet, ScrollView
} from 'react-native';
import Dimensions from 'Dimensions';
import FontAwesome from 'react-native-vector-icons/FontAwesome';

const DeviceWidth = Dimensions.get('window').width;
const DeviceHeight = Dimensions.get('window').height;

class App extends React.Component {
  constructor(props){
    super(props); 
    this.state = {
      selectedValueType : '',
      type : '',
      diagnosis: {
        type: [{
            "menu": "Oncology",
            "value": "Oncology"
          },{
            "menu": "Hip And Knee",
            "value": "Hip And Knee"
          }]
        }
      }
  }

  render() {
    return (
      <ScrollView>
      <View style={{justifyContent: 'space-between', alignSelf:'center', width:DeviceWidth*0.8, marginTop:10}} >
        <Text style={styles.TextStyles}>Type</Text>
        <View style={[styles.ViewDropdown,{}]}>
          <Picker
            selectedValue={this.state.selectedValueType}
            style={{ backgroundColor:'red'}}
            onValueChange={(itemValue, itemIndex) => this.setState({selectedValueType: itemValue})}>
            {this.state.diagnosis.type.map((item, key)=>(
              <Picker.Item label={item.menu} value={item.value} key={key}/>)
            )}
            {/* <FontAwesome name='sort-down' size={20}/> */}
          </Picker>
        </View>
        <TouchableOpacity activeOpacity={0.5} onPress={this._onClickNextDiagnosis}>
          <View style={styles.ViewButton}>
            <Text style={styles.TextButtonStyle}>Next</Text>
          </View>
        </TouchableOpacity>
      </View>
      </ScrollView>
    );
  }
}

const styles = StyleSheet.create({
  TextStyles:{fontSize:14, fontWeight:'bold'},
  ViewDropdown:{borderWidth:2, borderColor:'lightgrey', borderRadius:50, marginTop:10, marginBottom:10, height:DeviceWidth*0.1, justifyContent:'center', paddingLeft:DeviceWidth*0.03},
  DropdownLatestStyle:{borderWidth:2, borderColor:'lightgrey', borderRadius:DeviceWidth*0.1, marginTop:DeviceWidth*0.02, marginBottom:DeviceWidth*0.05, height:DeviceWidth*0.1, justifyContent:'center', paddingLeft:DeviceWidth*0.03},
  ViewButton:{width:DeviceWidth*0.8, justifyContent:'center', alignItems:'center', height:DeviceWidth*0.1, backgroundColor:'#005a00', borderRadius:DeviceWidth*0.1},
  TextButtonStyle:{textAlign:'center', fontSize:DeviceWidth*0.04, fontWeight:'bold', color:'white'}
});

export default App;
```

## Expected Behavior
Add an Icon next to Picker column

## Actual Behavior
Picker column disappear and the Icon displaying on the center column

**Comment by bcfoo** [comment]
To **fix this issue** you just have to style the Picker component like **" style={{ flex: 1 }} "** and you should be **good to go**. This happens because by default it has a width of 0, so inside a <View> it doesn't render properly. Why ? I do not know the answer.
