### ISSUE TITLE
more than one library with package name 'com.google.android.gms.license'

### ISSUE THREAD

**Issue by Lifesoftware** [facebook/react-native#18485]
issue regarding to firebase plugin.

![issue](https://user-images.githubusercontent.com/14052916/37711615-4860917c-2d37-11e8-94ad-3913f7fc871d.png)

**Comment by radko93** [comment]
Duplicate of #18479. Also look at https://github.com/evollu/react-native-fcm/issues/857 if it's `react-native-fcm`.
