### ISSUE TITLE
peer invalid: @babel/core@7.0.0-beta.38 for metro bundler

### ISSUE THREAD

**Issue by NachtRitter** [facebook/react-native#18490]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

Can not generate npm-shrinkwrap.json file. 
With command `npm ls @babel/plugin-check-constants@7.0.0-beta.38` I discovered that problem is in metro bundler package

```
└─┬ react-native@0.54.2
  └─┬ metro@0.28.0
    ├── UNMET PEER DEPENDENCY @babel/core@7.0.0-beta.42
    └── @babel/plugin-check-constants@7.0.0-beta.38
```

## Environment

Environment:
  OS: Linux 4.4
  Node: 6.13.1
  Yarn: Not Found
  npm: 3.10.10
  Watchman: 4.9.0
  Xcode: N/A
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: 0.54.2 => 0.54.2
## Steps to Reproduce

install node packages and run `npm shrinkwrap` command
## Expected Behavior

Generated npm-shrinkwrap.json file
## Actual Behavior

Error:
```
npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! peer invalid: @babel/core@7.0.0-beta.38, required by @babel/plugin-check-constants@7.0.0-beta.38
```

**Comment by hramos** [comment]
Should we be tracking this at github.com/facebook/metro instead?

**Comment by NachtRitter** [comment]
@hramos yeap. this issue is related to metro bundler repo, but it affects RN too because you should update used version of metro package for RN.

**Comment by hramos** [comment]
Please do. The Metro folks usually take care of bumping the version used by RN whenever they publish a new version.

**Comment by NachtRitter** [comment]
@hramos done
https://github.com/facebook/metro/issues/157

**Comment by lightman73** [comment]
Just for information. 

You can spot the problem by simply creating a new project with react-native init, and then checking it with yarn check. 
```
yarn check v1.5.1
warning "sane#fsevents#node-pre-gyp@^0.6.39" could be deduped from "0.6.39" to "node-pre-gyp@0.6.39"
error "metro#@babel/plugin-check-constants#@babel/core@7.0.0-beta.38" doesn't satisfy found match of "@babel/core@7.0.0-beta.42"
error An unexpected error occurred: "Found 1 errors.".
```

**Comment by NachtRitter** [comment]
Issue was fixed in https://github.com/facebook/metro 
closed.
