### ISSUE TITLE
[bug]Image.prefetch

### ISSUE THREAD

**Issue by xiehui999** [facebook/react-native#18498]
## Environment
  OS:  macOS High Sierra 10.13.2
  Node:  9.2.1
  Yarn:  1.3.2
  npm:  5.6.0
  Watchman:  4.9.0
  Xcode:  Xcode 9.2 Build version 9C40b
  Android Studio:  3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.0 => 0.52.0
## Steps to Reproduce
        Image.prefetch("https://github.com").then(() => {
                console.log("success")
            }, () => {
                console.log("fail")
            })
## Expected Behavior
console should printed fail.  
## Actual Behavior
Console printed success

**Comment by xiehui999** [comment]
Upload an invalid image url in the android simulator, still executing a successful callback.ios simulator is no problem。

**Comment by ingvardm** [comment]
```javascript
componentDidMount(){
  Image.prefetch(this.props.uri).then(this.onLoad,this.onError)
}
```
works like a charm on both platforms with RN 0.54

**Comment by radko93** [comment]
Maybe try creating https://snack.expo.io/ to reproduce this?

**Comment by xiehui999** [comment]
Environment:
  OS: macOS High Sierra 10.13.2
  Node: 9.2.1
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.3.0-alpha.1 => 16.3.0-alpha.2
  react-native: 0.54.2 => 0.54.2

```
 componentDidMount() {
        Image.prefetch("https://github.com").then(()=>{
            console.log("success");
        },()=>{
            console.log("fail")
        })
    }
```
Still having problems,when url is not a image,fail callback should invoke.

**Comment by hramos** [comment]
I'm not sure if failing here is the right approach. This is, after all, prefetching whatever URL you provide. If the network request succeeds and the API is able to cache the response, a success is valid.

I'd argue it's not up to the implementation of this API to ensure the URL being passed to this method is an image.
