### ISSUE TITLE
[Andriod] TextInput should have intrinsic size based on `placeholder`

### ISSUE THREAD

**Issue by JaEdmuva** [facebook/react-native#18507]
- [X] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [X] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [X] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment
Environment:
  OS: macOS High Sierra 10.13.3
  Node: 9.8.0
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.2.0 => 16.2.0
  react-native: ^0.54.2 => 0.54.2

## Steps to Reproduce
In Android, TextInput with width set to null and flex: 0, so it can grow or shrink depending on its content, is shrinking and not displaying complete 'placeholder' text. This was reported and solved for iOS in #12904 and works as expected

The view has this style: 

style {
height: 60,
paddingBottom: 0,
paddingTop: 0,
color: #0A1F8F,
flex: 0,
fontSize: 58,
lineHeight: null,
width: null
}

## Expected Behavior
TextInput should grow or shrink based on content (user input or placeholder when the field is empty)
![image](https://user-images.githubusercontent.com/3227066/37777932-b1739a72-2db6-11e8-90be-1efcbe8cf301.png)
![image](https://user-images.githubusercontent.com/3227066/37777987-d3321bf2-2db6-11e8-89e3-8ad6ecfc8751.png)

## Actual Behavior
TextInput shrinks not showing complete placeholder text
![image](https://user-images.githubusercontent.com/3227066/37778143-35dd1522-2db7-11e8-8364-e427573d9206.png)

If I'm missing something to replicate the scenario, please let me know. 

PD.: Sorry for the extra lines in the images, I couldn't take a screen shot because I'm blocking it in my app, so I used layout inspector.

**Comment by liuqiang1357** [comment]
Any solution for this? I am having the same problem.

**Comment by lynrose10** [comment]
I am having a problem in the placeholder when auto font sizing.
I've set allowFontScaling={false}
Placeholder: 0000

Device default font size
![screen shot 2018-05-24 at 3 07 09 pm](https://user-images.githubusercontent.com/29659291/40469932-9e4365e2-5f64-11e8-94cd-66bc72eff032.png)
![screen shot 2018-05-24 at 3 07 17 pm](https://user-images.githubusercontent.com/29659291/40469959-b35d84bc-5f64-11e8-96bc-84d7ca22cfce.png)

Device changed to max font size
![screen shot 2018-05-24 at 3 06 04 pm](https://user-images.githubusercontent.com/29659291/40469974-bfbb8bd2-5f64-11e8-9e29-e31323e3ff6d.png)
![screen shot 2018-05-24 at 3 06 42 pm](https://user-images.githubusercontent.com/29659291/40469977-c303bb66-5f64-11e8-8680-4e291f9de13c.png)

**Comment by Blackrush** [comment]
Is there any workaround this issue ?

**Comment by sangagung** [comment]
Is there any update or workaround on this issue? I'm having the same problem
