### ISSUE TITLE
algorithm file not found in 'Yoga-internal.h'

### ISSUE THREAD

**Issue by matteocollina** [facebook/react-native#18504]
algorithm file not found in 'Yoga-internal.h'

- [x] I have followed the [documentation](https://facebook.github.io/react-native/docs/integration-with-existing-apps.html)

## Environment
  OS: macOS High Sierra 10.13.3
  Node: 9.8.0
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: ^0.54.2 => 0.54.2

## Steps to Reproduce (from {ROOT})
- `cd js`
- `yarn add react-native`
- `cd ../`
- `pod install` :  dependecies installed √
-  **try to build my app but it doesn't work X**

I've also tried to remove "Pods" directory and "Podfile.lock" and retry

## Podfile
I have "node_modules" on a directory called {ROOT}/js
....
pod 'React', :path => 'js/node_modules/react-native', :subspecs => [
      'Core',
      'CxxBridge', 
      'DevSupport', 
      'RCTText',
      'RCTNetwork',
      'RCTWebSocket', 
  ]
  pod "yoga", :path => "js/node_modules/react-native/ReactCommon/yoga"
  pod 'DoubleConversion', :podspec => 'js/node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => 'js/node_modules/react-native/third-party-podspecs/GLog.podspec'
  pod 'Folly', :podspec => 'js/node_modules/react-native/third-party-podspecs/Folly.podspec'
...

**Comment by hramos** [comment]
This is fixed, to my understanding, by https://github.com/facebook/react-native/pull/18492 which is now on `master`. You'll need to build from source or wait for a new release to be cut.

**Comment by matteocollina** [comment]
@hramos I'd like to install pod specs automatically. I think it's not a good idea editing code manually to keep my CLI pipeline clean.

**Comment by hramos** [comment]
That’s fine. Fix will be part of the next release, you only need to build from source if you can’t wait until then.
