### ISSUE TITLE
`react-native link` doesn't link to all xCode project targets

### ISSUE THREAD

**Issue by andreyslyusar** [facebook/react-native#18503]
Is this a bug report?
yes

Have you read the Contributing Guidelines?
yes

Environment
Environment:
OS: macOS Sierra 10.13.3
Xcode: xcode 9.2

Packages:
react-native: 0.54.2
react: 16.3.0-alpha.2

Target Platform: iOS (11.2.1)

Steps to Reproduce
I have two targets in one project, App and App-production
when using react native link, there's only App can be successfully link the RNLibrary and there's no rn lib link in App-production

include rn any third party library
command react native link
doesn't link to all my targets in ios project
Expected Behavior
React Native link needs to properly link the ios for all targets

Actual Behavior
doesn't link to all my targets in ios project

Original issue https://github.com/facebook/react-native/issues/17381

**Comment by andreyslyusar** [comment]
Environment:
  OS: macOS High Sierra 10.13.3
  Node: 9.7.1
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.0-alpha.2 => 16.3.0-alpha.2
  react-native: 0.54.2 => 0.54.2

**Comment by bliang** [comment]
Any solution around this?

Also, would be nice to specify the target instead of just choosing the first one.
