### ISSUE TITLE
Webview postMessage slow in Release/Production build 

### ISSUE THREAD

**Issue by Thomsos** [facebook/react-native#18506]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [ ] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

I'm using a webview to send click events back to react-native. When building for debug, the time to receive the message is quick ( 0.5 seconds), but when building for release/production the time is ~ 5 seconds in the simulator and ~10 seconds on device. I have also tried using react-native-wkwebview-reborn with the same result.

## Environment
 OS: OS X El Capitan 10.11.6
  Node: 6.4.0
  Yarn: Not Found
  npm: 3.10.3
  Watchman: 4.6.0
  Xcode: Xcode 8.0 Build version 8A218a
  Android Studio: 2.1 AI-143.3101438

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: ^0.51.0 => 0.51.0

## Steps to Reproduce
index.html

```
<script>
    function sendMessage(){
        window.postMessage('{"key":' + 1 +'}')
    }
</script>
<body>
    <button onclick='sendMessage()'>
        Send 
    </button>
</body>
```

index.js
```
onWebViewMessage(event) {
    console.log("Message received from webview", event);
  }
....
<WebView
            ref={webview => {
              this.myWebView = webview;
            }}
            scrollEnabled={true}
            source={require("./index.html")}
            onMessage={this.onWebViewMessage}
            style={{flex: 1}}
   />
```

## Expected Behavior
Similar performance and speed to debug.

## Actual Behavior
Much slower.

**Comment by Thomsos** [comment]
I haven't had the chance to update to Sierra/XCode9, running into the same issue here when building: https://github.com/facebook/react-native/issues/18238

Could someone try to reproduce in 0.54?

**Comment by bestsamcn** [comment]
same issue for me, dose anyone solve this?

**Comment by sambernaerdt** [comment]
Hi, just want to let you know that I'm having the same issue.

Fetching data from the server goes fast (<1s) when running in debug mode with **Remote JS Debugging enabled**. If Remote debugging is disabled or running the release version, the same action takes >10s.

Using
    "react-native": "0.55.4"

I don't know if it's related to this issue, but I'm using 
    "cross-fetch": "^2.2.0"
to fetch data.

It would be great if anyone knows how to solve this... Thanks.

**Comment by hramos** [comment]
Closing as author did not respond to followup.

**Comment by miraan** [comment]
@sambernaerdt Interesting, was the logging on the React Native side, or from inside the WebView?

**Comment by staroflead** [comment]
@sambernaerdt thanks for the hint, I have remove the logging and it's no longer delay
