### ISSUE TITLE
Android adjustNothing is not working inside modal in RN 0.54.2

### ISSUE THREAD

**Issue by swingywc** [facebook/react-native#18518]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

I have used `android:windowSoftInputMode="adjustNothing"` inside `AndroidMainfest.xml`. The keyboard didn't cost any space when inside a normal page (what I expected). However, inside the modal, the keyboard still cost bottom space which will break my layout. What I expected is the modal layout remains full height when keyboard comes out.

## Environment
Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.9.1
  Yarn: Not Found
  npm: 4.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: ^0.54.2 => 0.54.2

## Expected Behavior
Keyboard inside modal will not resize the layout.

## Actual Behavior
Keyboard come out and layout shrink up.

### Before focus TextInput inside Modal
![whatsapp image 2018-03-23 at 18 10 55](https://user-images.githubusercontent.com/9659080/37823830-a7f84cda-2ec5-11e8-9ccb-13fe1ea05289.jpeg)

### After focus TextInput inside Modal (layout shrink up and break)
![whatsapp image 2018-03-23 at 18 10 55 1](https://user-images.githubusercontent.com/9659080/37823829-a7cbc5a2-2ec5-11e8-859d-1548042bbae4.jpeg)

**Comment by swingywc** [comment]
I have seen someone said that the `windowSoftInputMode` setting inside activity tag is not passed to the android modal, therefore need to create a `<style></style>` in `app/src/main/res/values/styles.xml`. Does anyone know what is the name of the modal inside react native?

**Comment by swingywc** [comment]
I saw someone said that adding the following styles to `android/app/src/main/res/values/styles.xml` will work:
```
<style name="Theme.FullScreenDialog">
     <item name="android:windowSoftInputMode">adjustNothing</item>
</style>
```

but for me it's not working, is there any method I can pass the styles into the `<Modal></Modal>`? If possible I don't want to use `<KeyboardAvoidingView></KeyboardAvoidingView>`.

**Comment by swingywc** [comment]
@react-native-bot Have already updated to v0.54.2.

**Comment by yuoppp** [comment]
Facing the same issue. Any workaround?

**Comment by ebaynaud** [comment]
Reproduced with RN 0.56

**Comment by kk412027247** [comment]
Just add a fix height to the first child of Modal. 
`android:windowSoftInputMode="adjustNothing"` will work.

The following code works for me.
```
import React, {Component} from 'react';
import { View, Modal, TextInput, Dimensions} from 'react-native';
const {width ,height} = Dimensions.get('screen');

export default class App extends Component<Props> {
  render() {
    return (
      <Modal visible={true} onRequestClose={()=>{}}>
        <View style={{
          height,
          width,
          justifyContent:'center',
          alignItems:'center',
          backgroundColor:'rgba(0,0,0,0.51)',
        }}>
          <TextInput
            style={{width: 0.5 * width, backgroundColor:'#fff'}}
            placeholder={'Type here'}
          />
        </View>
      </Modal>
    );
  }
}
```

**Comment by kk412027247** [comment]
@swingywc 老铁，如果代码好事的话，给我双击个六六六，斜眼笑。
