### ISSUE TITLE
ImageBackground in TouchableNativeFeedback is crashing

### ISSUE THREAD

**Issue by dulmandakh** [facebook/react-native#18519]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment
Environment:
  OS: macOS High Sierra 10.13.3
  Node: 9.9.0
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.3.0-alpha.1 => 16.3.0-alpha.3
  react-native: 0.54.2 => 0.54.2

## Steps to Reproduce

```
<TouchableNativeFeedback onPress={() => {console.log('clicked')}}>
  <ImageBackground source={{uri: <url to any image>}} style={{ width: 300, height: 100}} />
</TouchableNativeFeedback>
```
and try to click it

## Expected Behavior
It'll print "clicked" in logcat

## Actual Behavior
It won't react to a click as expected and crashing with "Trying to send to a non-existing view with a tag <number>" error

**Comment by hramos** [comment]
Does this only happen when a ImageBackground is nested inside a TouchableNativeFeedback? Does it happen if ImageBackground is nested inside a different Touchable*? How did you reproduce this (on device, emulator?)

**Comment by FlaviooLima** [comment]
This only happens on the following case:
```
<TouchableNativeFeedback>
    <ImageBackground source={require("../image.png")} style={{ width: 300, height: 200 }}>
    </ImageBackground>
</TouchableNativeFeedback>
```

**Comment by FlaviooLima** [comment]
Still Happening in React-Native V0.55.3 and Android "P"
