### ISSUE TITLE
underlineColorAndroid default color?

### ISSUE THREAD

**Issue by JoeRoddy** [facebook/react-native#18510]
What is the default color for this?  Using a third party input that sets it to transparent unless I pass it in, so I simply want to pass the default color. 

Can't seem to find it anywhere.

**Comment by hramos** [comment]
This is backed by a native TextInput on Android, so it probably uses the theme's default. Closing as this is a question and not a bug report.

**Comment by JoeRoddy** [comment]
Definitely a question..

Where do I ask questions?

**Comment by hramos** [comment]
@JoeRoddy this is covered in the new issue template that you deleted when you opened this issue.

**Comment by JoeRoddy** [comment]
@hramos  Thanks Hector! And thanks for the sass, hope your day gets better. :D
