### ISSUE TITLE
PushNotificationIOS.requestPermissions() promise still does not resolve

### ISSUE THREAD

**Issue by jayporta** [facebook/react-native#18523]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

I'm trying to call a function based on the results of the requestPermissions promise, but the promise doesn't resolve.

I've read through [this thread](https://github.com/facebook/react-native/issues/13012) but the fix does not work, and I've been told to refrain from commenting in closed threads. 

## Environment
  OS: macOS High Sierra 10.13.3
  Node: 8.9.4
  Yarn: Not Found
  npm: 4.6.1
  Watchman: 4.9.1
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003
 React: 54

## Steps to Reproduce

`PushNotificationIOS.requestPermissions().then(console.log('hello'));` will log "hello", as soon as the permissions dialogue appears, however...

`PushNotificationIOS.requestPermissions().then((result) => { console.log('Result is: ', result) });` doesn't log anything at all. Even if I add a catch, nothing happens; there is nothing to log out. My anonymous function won't even run.

## Expected Behavior
Get some feedback on tap of the native iOS permissions dialogue's "Allow" or "Don't Allow"

## Actual Behavior
Nothing happens.

**Comment by jayporta** [comment]
wtf, bot?

**Comment by jdmunro** [comment]
I'm also experiencing this issue.

**Comment by jongirard** [comment]
also experiencing this issue on react-native version 0.5.6
