### ISSUE TITLE
Updating to Xcode 6.4 caused hanging from launchscreen to CMD + D

### ISSUE THREAD

**Issue by kphed** [facebook/react-native#1853]
Hi, after updating to Xcode 6.4 via the Appstore last night, I haven't been able to run my projects like before -- even React Native examples or the PropertyFinder one from RayWenderlich's tutorial. 

Upon starting the application, the launch screen will come up, hang for maybe 2-3x as long as it did before the update, then when I press CMD + D, it'll open extremely slowly and be unresponsive for a good 30 seconds to a minute, not letting me do anything from there. Another odd thing I noticed was that when I clicked on a TextInput, it'd open up the native iOS keyboard, which never happened before. 

I've tried resetting the iOS simulator, doing a 'clean build' and CMD + shift + K on Xcode, to clearing the derived data for all my projects. The weird thing is that my uncle cloned down my repo to his machine and has none of the issues, so I don't believe it's my project, just something up with my Xcode.

Has anyone had a similar issue? I'd really appreciate anyone shedding some light or assistance, thanks a lot in advance!

**Comment by kphed** [comment]
Solution: never press CMD + T!

**Comment by srashtiagrawal** [comment]
I am having the same issue.I have xcode 6.4 and OSX 10.10.4 when I am running project,simulator is just showing black screen and doing nothing,also xcode gets hang all the time.I have to force quit it.
I have tried deleting derive data,restating system,trying with all simulators,reseting simulator contents etc.
Can anyone please help me out.?

**Comment by kphed** [comment]
Sure thing - did you try pressing CMD + T? I forgot exactly what it did, but it had something to do with slowing the simulation down.
