### ISSUE TITLE
Use React-Hot-Loader v4

### ISSUE THREAD

**Issue by theKashey** [facebook/react-native#18531]
Source issue - https://github.com/gaearon/react-hot-loader/issues/907

Look like the time has come to replace react-transform-hmr(react-hot-loader v1) by react-hot-loader v4, and it should work.

I will start preparations and experiments in hot-loader repo. For React-Native it will be one line change - just replace metro-babel7-plugin-react-transform by the RHL's babel plugin.

However - if anyone has something to add - ideas, concerns, issues and wishes - say it now, dont hold your peace.

**Comment by hramos** [comment]
https://discuss.reactjs.org seems like a better place for this.
