### ISSUE TITLE
[Bridge] dose the _loading variable need to be locked in RCTBridgeModule?

### ISSUE THREAD

**Issue by dolmens** [facebook/react-native#1854]
The _loading variable may be used in main and background thread, so, dose it need to be locked?
RCTBatchedBridge
```objc
[loader loadBundleAtURL:bundleURL onComplete:^(NSError *error, NSString *script) {
	_loading = NO;
	// this is in background thread, ...
}
```

and RCTRootView in main thread
```
- (instancetype)initWithBridge:(RCTBridge *)bridge
                    moduleName:(NSString *)moduleName
{
  RCTAssertMainThread();
    if (!_bridge.batchedBridge.isLoading) {
      [self bundleFinishedLoading:_bridge.batchedBridge];
    }
}
```

**Comment by brentvatne** [comment]
I had a quick look through the code and this seems pretty unlikely to cause any issues - `loadBundleAtURL` would have to run incredibly quickly for any problems to arise, as far as I can tell.

But cc @tadeuzagallo just to be sure

**Comment by tadeuzagallo** [comment]
@javache has moved it to happen on the same thread.
