### ISSUE TITLE
Emojis inside <Text> increase line-height or stretch the element

### ISSUE THREAD

**Issue by rikur** [facebook/react-native#18559]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 9.4.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.3.0-alpha.1 => 16.3.0-alpha.3
  react-native: 0.54.2 => 0.54.2

## Steps to Reproduce

Render a `<Text>` component with an emoji inside it.

## Expected Behavior

Have text with emojis inside a text not change the line-height. Also expecting `textDecorationLine: 'line-through'` to work seamlessly with emojis inside text.

## Actual Behavior

The line-height of the entire text is increased. It's even more prevalent if you apply `textDecorationLine: 'line-through'` on the text, as shown below.

<img width="172" alt="screen shot 2018-03-26 at 3 11 18 am" src="https://user-images.githubusercontent.com/4004/37891793-992a9958-30a3-11e8-9f46-3c9b0803eb6f.png">
<img width="134" alt="screen shot 2018-03-26 at 3 11 31 am" src="https://user-images.githubusercontent.com/4004/37891794-9937d280-30a3-11e8-8b12-cbd625d42982.png">

**Comment by rikur** [comment]
Here's my far from perfect workaround that obviously is tied to the styles of my font in question:

```
const emojiRe = /(?:[\u2700-\u27bf]|(?:\ud83c[\udde6-\uddff]){2}|[\ud800-\udbff][\udc00-\udfff]|[\u0023-\u0039]\ufe0f?\u20e3|\u3299|\u3297|\u303d|\u3030|\u24c2|\ud83c[\udd70-\udd71]|\ud83c[\udd7e-\udd7f]|\ud83c\udd8e|\ud83c[\udd91-\udd9a]|\ud83c[\udde6-\uddff]|[\ud83c[\ude01-\ude02]|\ud83c\ude1a|\ud83c\ude2f|[\ud83c[\ude32-\ude3a]|[\ud83c[\ude50-\ude51]|\u203c|\u2049|[\u25aa-\u25ab]|\u25b6|\u25c0|[\u25fb-\u25fe]|\u00a9|\u00ae|\u2122|\u2139|\ud83c\udc04|[\u2600-\u26FF]|\u2b05|\u2b06|\u2b07|\u2b1b|\u2b1c|\u2b50|\u2b55|\u231a|\u231b|\u2328|\u23cf|[\u23e9-\u23f3]|[\u23f8-\u23fa]|\ud83c\udccf|\u2934|\u2935|[\u2190-\u21ff])/g

const EmojiText = (props) => {
  const content = props.children
  const fontSize = 11
  const emojis = content.match(emojiRe)
  const strings = content.split(emojiRe)
  return <Text {...props}>{strings.map((v, i) => <Text>{v}<Text style={{ fontSize }}>{emojis[i]}</Text></Text>)}</Text>
}```

I noticed that similar issues with emojis happen outside of React Native. Pages renders the emojis correctly, Sketch doesn't. It seems like Sketch automatically assign a special font for emojis that I can't even change.

**Comment by ccfz** [comment]
I have been looking into this issue for a while now and there are some hacky solutions out there related to adjusting the `fontSize / lineHight` etc. The issue does not arise when one uses `System` in `FontFamily`, which to my understanding is related to the way `System` font was implemented in react-native with IOS/Android presets #1635. The problem with `System`is that it does not allow for font variations such as `SF UI Display`. @rikur solution worked for me but I was looking for a way to avoid the font style dependency What I discovered is that if I apply the `System` fontFamily to just the emoji it will behave as expected without having to add custom `fontSize`. 

So based on the code from @rikur I just changed the `fontSize: 11` to `fontFamily: System`.

In our project we are only using variants of `San Fransico` font and since `System` is `SF UI Text` it might only work with variants of the default system fonts. I am interested to see if this works with other custom fonts as well. 

For convenience the snippet from @rikur the way I implemented it and with the `fontFamily`change.

```javascript
import React from 'react';
import { Text } from 'react-native';

const EmojiText = ({ style, children, ...rest }) => {
  // eslint-disable-next-line
  const emojiRe = /(?:[\u2700-\u27bf]|(?:\ud83c[\udde6-\uddff]){2}|[\ud800-\udbff][\udc00-\udfff]|[\u0023-\u0039]\ufe0f?\u20e3|\u3299|\u3297|\u303d|\u3030|\u24c2|\ud83c[\udd70-\udd71]|\ud83c[\udd7e-\udd7f]|\ud83c\udd8e|\ud83c[\udd91-\udd9a]|\ud83c[\udde6-\uddff]|[\ud83c[\ude01-\ude02]|\ud83c\ude1a|\ud83c\ude2f|[\ud83c[\ude32-\ude3a]|[\ud83c[\ude50-\ude51]|\u203c|\u2049|[\u25aa-\u25ab]|\u25b6|\u25c0|[\u25fb-\u25fe]|\u00a9|\u00ae|\u2122|\u2139|\ud83c\udc04|[\u2600-\u26FF]|\u2b05|\u2b06|\u2b07|\u2b1b|\u2b1c|\u2b50|\u2b55|\u231a|\u231b|\u2328|\u23cf|[\u23e9-\u23f3]|[\u23f8-\u23fa]|\ud83c\udccf|\u2934|\u2935|[\u2190-\u21ff])/g
  const emojis = children.match(emojiRe);
  const strings = children.split(emojiRe);

  function renderEmoji(index) {
    if (emojis === null) { return null; }

    return (
      <Text style={{ fontFamily: 'System' }}>
        {emojis[index]}
      </Text>
    );
  }

  return (
    <Text style={style} {...rest}>
      {strings.map((value, index) => (
        <Text>
          {value}
          {renderEmoji(index)}
        </Text>
      ))}
    </Text>
  );
};

export default EmojiText;

```

**Comment by rikur** [comment]
Thanks for the update. I just tried your snipped at it doesn't seem to work when used with custom fonts.

**Comment by jakehasler** [comment]
@rikur I was able to get this working decently with a custom font. I updated the last return block to the following:
```
return (
    <Text {...rest}>
      {strings.map((value, index) => (
        <Text style={style} key={index}>
          {value}
          {renderEmoji(index)}
        </Text>
      ))}
    </Text>
  );
```

**Comment by scottmas** [comment]
The best solution I've found is the use [react-native-parsed-text](https://www.npmjs.com/package/react-native-parsed-text) like so:
```javascript
const EMOJI_REGEX = /(?:[\u2700-\u27bf]|(?:\ud83c[\udde6-\uddff]){2}|[\ud800-\udbff][\udc00-\udfff]|[\u0023-\u0039]\ufe0f?\u20e3|\u3299|\u3297|\u303d|\u3030|\u24c2|\ud83c[\udd70-\udd71]|\ud83c[\udd7e-\udd7f]|\ud83c\udd8e|\ud83c[\udd91-\udd9a]|\ud83c[\udde6-\uddff]|[\ud83c[\ude01-\ude02]|\ud83c\ude1a|\ud83c\ude2f|[\ud83c[\ude32-\ude3a]|[\ud83c[\ude50-\ude51]|\u203c|\u2049|[\u25aa-\u25ab]|\u25b6|\u25c0|[\u25fb-\u25fe]|\u00a9|\u00ae|\u2122|\u2139|\ud83c\udc04|[\u2600-\u26FF]|\u2b05|\u2b06|\u2b07|\u2b1b|\u2b1c|\u2b50|\u2b55|\u231a|\u231b|\u2328|\u23cf|[\u23e9-\u23f3]|[\u23f8-\u23fa]|\ud83c\udccf|\u2934|\u2935|[\u2190-\u21ff])/g;
function EmojiText({children, ...rest}) {
  return (
    <ParsedText {...rest} parse={[{ pattern: EMOJI_REGEX, style: { fontFamily: "System" } }]}>
      {children}
    </ParsedText>
  );
}
```
