### ISSUE TITLE
Feature Request: TextInput onPaste event

### ISSUE THREAD

**Issue by jiteshgupta1995** [facebook/react-native#18551]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

I am trying to make OTC field using **TextInput** but as of React-Native v0.54, it doesn't support onPaste event unlike ReactJS.

## Environment

  OS: Linux 4.13
  Node: 9.4.0
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.7.0
#### Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.54.1 => 0.54.1
## Actual Behavior

Can it be possible to add this as Feature Request? Thanks.

**Comment by pronebird** [comment]
This has been closed by mistake by @react-native-bot

**Comment by MohamadKh75** [comment]
+1

**Comment by evanjmg** [comment]
my android app is crashing from pasting images into the view
