### ISSUE TITLE
build failed shell script invocation error : File /Users/louis/Library/Developer/Xcode/DerivedData/Scavenger-evyvzocndqoghkclcbwewolywniz/Build/Products/Release-iphoneos/Scavenger.app/main.jsbundle does not exist

### ISSUE THREAD

**Issue by louiskurniawan03** [facebook/react-native#18562]
- [Yes] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [Yes] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [No] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment
Environment:
  OS: macOS Sierra 10.12.6
  Node: 9.3.0
  Yarn: Not Found
  npm: 5.5.1
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.0.0 => 16.2.0
  react-native: ^0.50.3 => 0.50.4

## Expected Behavior
I'm not sure why I'm getting this error. But this happen after I tried to switch to configuration Release. I want to archive my project

## Actual Behavior
Build failed from xcode. The build phase already using 
export NODE_BINARY=node ../node_modules/react-native/scripts/react-native-xcode.sh

<img width="759" alt="screen shot 2018-03-26 at 5 51 52 pm" src="https://user-images.githubusercontent.com/28404289/37902401-86e73e24-311e-11e8-963b-90e68d8f7f5c.png">

**Comment by edxe** [comment]
I have the same problem after installing `react-native-fbsdk`, still no solution found. Running the app on simulator works just fine, but when doing the build/archive it fails with this same issue. Im running over `react-native 0.53.0`

**Comment by Linrasis** [comment]
Same error too.. work fine on iOS Simulator / Device, when create archive i have error and now i have same error when i launch simulator.

`+ DEST=/Users/julienschmidt/Library/Developer/Xcode/DerivedData/Prenomsaleatoire-bioyrajacoovpubqfaussbssxixp/Build/Intermediates.noindex/ArchiveIntermediates/Prenomsaleatoire/BuildProductsPath/Release-iphoneos/Prenomsaleatoire.app
+ [[ Release = \D\e\b\u\g ]]
+ BUNDLE_FILE=/Users/julienschmidt/Library/Developer/Xcode/DerivedData/Prenomsaleatoire-bioyrajacoovpubqfaussbssxixp/Build/Intermediates.noindex/ArchiveIntermediates/Prenomsaleatoire/BuildProductsPath/Release-iphoneos/Prenomsaleatoire.app/main.jsbundle
+ node /Users/julienschmidt/Google Drive/Applications/GIT/Prenoms Aleatoire/node_modules/react-native/local-cli/cli.js bundle --entry-file index.js --platform ios --dev false --reset-cache --bundle-output /Users/julienschmidt/Library/Developer/Xcode/DerivedData/Prenomsaleatoire-bioyrajacoovpubqfaussbssxixp/Build/Intermediates.noindex/ArchiveIntermediates/Prenomsaleatoire/BuildProductsPath/Release-iphoneos/Prenomsaleatoire.app/main.jsbundle --assets-dest /Users/julienschmidt/Library/Developer/Xcode/DerivedData/Prenomsaleatoire-bioyrajacoovpubqfaussbssxixp/Build/Intermediates.noindex/ArchiveIntermediates/Prenomsaleatoire/BuildProductsPath/Release-iphoneos/Prenomsaleatoire.app
module.js:538
    throw err;
    ^

Error: Cannot find module '/Users/julienschmidt/Google'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
+ [[ false != true ]]
+ [[ ! -f /Users/julienschmidt/Library/Developer/Xcode/DerivedData/Prenomsaleatoire-bioyrajacoovpubqfaussbssxixp/Build/Intermediates.noindex/ArchiveIntermediates/Prenomsaleatoire/BuildProductsPath/Release-iphoneos/Prenomsaleatoire.app/main.jsbundle ]]
+ echo 'error: File /Users/julienschmidt/Library/Developer/Xcode/DerivedData/Prenomsaleatoire-bioyrajacoovpubqfaussbssxixp/Build/Intermediates.noindex/ArchiveIntermediates/Prenomsaleatoire/BuildProductsPath/Release-iphoneos/Prenomsaleatoire.app/main.jsbundle does not exist. This must be a bug with'
error: File /Users/julienschmidt/Library/Developer/Xcode/DerivedData/Prenomsaleatoire-bioyrajacoovpubqfaussbssxixp/Build/Intermediates.noindex/ArchiveIntermediates/Prenomsaleatoire/BuildProductsPath/Release-iphoneos/Prenomsaleatoire.app/main.jsbundle does not exist. This must be a bug with
+ echo 'React Native, please report it here: https://github.com/facebook/react-native/issues'
React Native, please report it here: https://github.com/facebook/react-native/issues
+ exit 2
`

**Comment by r0bbarnk** [comment]
For anyone who struggles with this issue. Take a look at your folder-structure and make sure that the outer folder-bane for the project does not contain space.
I changed my outer folder name from "Good Morning" to "GoodMorning". Error went away.

**Comment by adamgins** [comment]
@r0bbarnk the top of my project is `/Users/adamginsburg/Documents/development/buzzy_rn` and I still have the issue. Works fine in debug mode on both emulator and phone... just cannot release build/archive

**Comment by creightontaylor** [comment]
Umm someone? I have the same problem

**Comment by ruci06** [comment]
same problem on rn 0.56.0
is there any solution?

**Comment by r0bbarnk** [comment]
@adamgins I would suggest to remove the underscore!

**Comment by ruci06** [comment]
I'm using nvm, and node versions are 6.x, 8.x, 10.x.
I got 'build failed shell script invocation error' but above it there was checkNodeVersion.js (43) error.
I removed 6.x version from nvm and it works.
