### ISSUE TITLE
AppState.addEventListener('change' ... not giving proper results

### ISSUE THREAD

**Issue by BlueBeetle13** [facebook/react-native#18575]
- [X] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [X] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [X] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

AppState.addEventListener('change', (state) => { console.log(state) });

Drag down the notification screen on iOS 11+ device. When the notification screen nears the bottom of the device screen the app state quickly flips from `inactive` to `active` and then back to `inactive`.

This doesn't happen on < iOS 11.

This happens with both simulator and real device.

## Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 6.9.1
  Yarn: Not Found
  npm: 3.10.8
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.3.0-alpha.1 => 16.3.0-alpha.3
  react-native: ^0.54.1 => 0.54.2

## Steps to Reproduce

Add this code to your app.js file. Run your app.

AppState.addEventListener('change', (state) => { console.log(state) });

Now drag down the notification window and monitor the console.

## Expected Behavior

App state consistently stays in `inactive` state while the notification window is dragged down. Works this way in iOS 9, 10

## Actual Behavior

While dragging down the notification window, when near the bottom of the screen the app state toggles from inactive->active->inactive

**Comment by toppy42** [comment]
I've experienced this when trying to make a phone call from React Native.  When the call initiates, the handler picks up `inactive => active => inactive`.  This also happens on Android (`background => active => background`)
