### ISSUE TITLE
TextInput behavior on programmatic value change differs between iOS/Android

### ISSUE THREAD

**Issue by akalin-keybase** [facebook/react-native#18578]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

If one has a `TextInput` and changes its `value` prop, selection behavior differs between iOS and Android. On iOS, the cursor jumps to the end. On Android, the cursor moves to the right by some varying amount.

Also, if the `TextInput` has focus, on iOS no `onSelectionChange` even is fired, but one is on Android.

Finally, it would be nice if it were documented somewhere that the initial selection is at the end of the initial value.

## Environment
Environment:
  OS:  macOS High Sierra 10.13.3
  Node:  9.9.0
  Yarn:  1.5.1
  npm:  5.8.0
  Watchman:  4.9.0
  Xcode:  Xcode 9.2 Build version 9C40b
  Android Studio:  Not Found

Packages: (wanted => installed)
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: 0.54.2 => 0.54.2

## Steps to Reproduce
See https://snack.expo.io/BJUeRfw5M

## Expected Behavior
Consistent behavior between platforms. Jumping to the end of the line/value, perhaps, and firing an onSelectionChange event.

Documentation stating that the initial selection is at the end of the initial value.

## Actual Behavior
On iOS, the cursor jumps to the end of the line, or the end of the replace text, sometimes. On Android, the cursor moves to the right by some varying amount.

Also, if the `TextInput` has focus, on iOS no `onSelectionChange` even is fired, but one is on Android.

**Comment by akalin-keybase** [comment]
A workaround is just to set `selection` explicitly. But doing so runs into https://github.com/facebook/react-native/issues/18316 , which also has its own workaround. https://github.com/akalin-keybase/rn-text-input-bugs has a demo that implements these workarounds.

**Comment by akalin-keybase** [comment]
Not fixed AFAIK

**Comment by proof666** [comment]
any news on this issue?
I also ran into this problem, at least in part "if the TextInput has focus, on iOS no onSelectionChange even is fired" when programaticaly change value prop.
