### ISSUE TITLE
[Rendering] Views with border radius + image with alpha issue

### ISSUE THREAD

**Issue by yelled3** [facebook/react-native#1857]
I'm not entirely sure if this is a bug or not, but this behaviour surprised me.
when creating a View with `backgroundColor` and a `borderRadius` (i.e `circle`) and have an Image with alpha inside it (i.e `icon`) the alpha part of the icon will be colored as same as the circle.
this is fine as long as the icon is inside the circle, but if you place it outside of the it (on top of the round corner) then you'll get the following result:

![ios simulator screen shot jul 3 2015 1 45 37 am](https://cloud.githubusercontent.com/assets/818124/8495292/204545f0-2175-11e5-87c0-b0a636535d82.png)

my current solution of this issue is adding `backgroundColor: 'transparent'` to the icon.

see RN playground:
https://rnplay.org/apps/1wioYA

it seems like a rendering bug...

@brentvatne @vjeux  /cc

**Comment by ide** [comment]
This is an intentional rendering optimization to avoid blending, since most of the time your transparent images are fully on top of an opaque background. Your solution of adding a transparent background color is correct.
