### ISSUE TITLE
Double Developer menu?

### ISSUE THREAD

**Issue by DLevai94** [facebook/react-native#18577]
## Environment
Environment:
  OS: macOS High Sierra 10.13.3
  Node: 9.2.0
  Yarn: 1.3.2
  npm: 5.8.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: 0.49.5 => 0.49.5

## Steps to Reproduce
Created a new project with `react-native init` at 0.50 then some later time downgraded and maybe I did a new init too. Can't really remember this was some months ago.

## Expected Behavior
When I shake my device only 1 dev menu opens.

## Actual Behavior
Sometimes there are dev menus.
Screencap:
https://media.giphy.com/media/ujjHCx31kAy0RRCFui/giphy.gif

**Comment by pvinis** [comment]
your gif doesnt show for me, but i know what you mean, and i have it event with the latest version 0.54.3.

**Comment by DLevai94** [comment]
@react-native-bot I can reproduce with the latest release, v0.54

**Comment by vrgimael** [comment]
I also have this problem

**Comment by DLevai94** [comment]
It present on 0.56 !!!
