### ISSUE TITLE
Layout Animation does not work on Android even with UIManager experimental settings in a constructor

### ISSUE THREAD

**Issue by olejka91** [facebook/react-native#18583]
Do I miss something or this is an issue ?

I have reviewed the documentation about LayoutAnimation and looked through all the issues on a github regarding to LayoutAnimation,
I have asked a question on Discord and event on [stackoverflow](https://stackoverflow.com/questions/49505995/react-native-layoutanimation-not-working-on-android-even-with-uimanager-settings)

I am using the 0.53.0 version of react-native

I am trying to remove an element and use LayoutAnimation for smooth animation it works well on iOS, but not on Android even if I add UIManager experimental settings.

I have described my situation on the stackoverflow with a code. Please check.
In my case Layout Animation does not work even with experimental settings for Android and I don't want to use a 3d part library for that

## Environment
  react-native

## Steps to Reproduce
No steps

## Expected Behavior
Animation works fine

## Actual Behavior
Animation does not work on Android

**Comment by kirankalyan5** [comment]
@olejka91 I have the same Issue! Do you have any fixes for this?

**Comment by dennyabrain** [comment]
Similar issue. 
animation works great on iOS. doesnt work on android even after adding the UIManager experimental settings in constructor AND right before using configureNext()
