### ISSUE TITLE
[Idea] Expose app version, bundle identifier etc.

### ISSUE THREAD

**Issue by paramaggarwal** [facebook/react-native#1859]
How about exposing `[[NSBundle mainBundle] infoDictionary]` into JS? Then if and when the JS is updated remotely - it can check for the app version and modify behaviour accordingly. For example, if the app version is less than a particular version, then the JS would not attempt to use a native module that does not exist in that older version.

Any interest in the same?

**Comment by ide** [comment]
Sounds like a great third-party module to me.

**Comment by paramaggarwal** [comment]
I tried it out and there are some unsupported data types in the dictionary returned from `[[NSBundle mainBundle] infoDictionary]`. Anyways, the useful parameters out of it are pretty much this:

```
RCT_EXPORT_MODULE();

- (NSDictionary *)constantsToExport {
  return @{
           @"identifier": [[NSBundle mainBundle] objectForInfoDictionaryKey:@"CFBundleIdentifier"],
           @"version": [[NSBundle mainBundle] objectForInfoDictionaryKey:@"CFBundleShortVersionString"],
           @"build": [[NSBundle mainBundle] objectForInfoDictionaryKey:@"CFBundleVersion"],
           };
}
```
