### ISSUE TITLE
WebView for PDF on Android

### ISSUE THREAD

**Issue by peni4142** [facebook/react-native#18592]
There is no need to support versions of Android before Lollipop. You can mention it in the docs, that it would not work for the old versions of Android. I already tested several alternatives, but they didn't worked. Please use native rendering of Anroid!

One Code for two platforms!

## Environment

Environment:
  OS: Windows 10
  Node: 6.11.3
  Yarn: 1.2.1
  npm: 5.5.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.0.0.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.50.3 => 0.50.3

## Steps to Reproduce
Run following Code on Android
 `
      <WebView
        source={{uri: 'http://www.lagotzki.de/pdftk/beispiel_neu.pdf'}}
        style={{ flex:1}}
      />`

## Expected Behavior
Showing an PDF

## Actual Behavior
Nothing............................

**Comment by peni4142** [comment]
Tried to upgrade with `react-native-git-upgrade 0.54.3` Now I have a verion mismatch:

JavaScript version:0.54.3
Native version: 0.50.3

Don't know how to resolve that. I have done that, I will report if the issue is reproduceable.

**Comment by peni4142** [comment]
Ok I don't get the version mismatch solved. I would mention it as a own Issue, but I think, I am the only one with that bug.

So you can close this issue, I give up on updating and try to solve it in an other way.

**Comment by wedneyyuri** [comment]
Hi @peni4142,

the android webview doesn't support displaying PDF files. See https://github.com/facebook/react-native/issues/6488#issuecomment-218444035 and https://github.com/wonday/react-native-pdf for a workaround.

You can also vote for this feature here: https://react-native.canny.io/feature-requests/p/android-webview-cannot-display-pdf-

**Comment by MassivDash** [comment]
Actually you can use, mozilla pdf.js web online viewer, to bypass this issue. 
In webview component source={{ uri: 'http://mozilla.github.io/pdf.js/web/viewer.html?file={your server link here}' }}. Works like a charm.
