### ISSUE TITLE
AsyncStorage throws `JSON value '<null>' of type NSNull cannot be converted to NSString` error when saving empty array.

### ISSUE THREAD

**Issue by schumannd** [facebook/react-native#18602]
This error occurs on:

`AsyncStorage.setItem(my_key, JSON.dumps([]));`
or 
`AsyncStorage.setItem(my_key, '[]');`

When using chrome debugger with `pause on caught exceptions` the exception is in Blob.js:

TypeError: Cannot read property 'forEach' of undefined.

line 98

**Comment by schumannd** [comment]
The issue was actually caused by my key being undefined. I will close it

**Comment by arled** [comment]
This bug is stupid

**Comment by schumannd** [comment]
Do you care to elaborate? Did you encounter it as well? If many people are confused by this error message maybe a better error message would be suitable?
