### ISSUE TITLE
There is a bug in iphone8

### ISSUE THREAD

**Issue by lovepluskaka** [facebook/react-native#18605]
Text element comes with an overline in iphone8 plus,but it show normal with others .

![text](https://user-images.githubusercontent.com/20063934/38032011-311c6570-32cf-11e8-8874-cef09a66dd18.jpeg)

**Comment by lovepluskaka** [comment]
I am using the version 0.51.0, and my code is 
```
<Text style={{ color: "#ABABAB", fontSize: 12, textDecorationLine: 'none' }}>
         {item.source ? `来源：${item.source}` : ""}
 </Text>
```
There seems normal in orther device excepts iphone8 plus.
--

**Comment by s349856186** [comment]
@lovepluskaka Has this problem been solved?
