### ISSUE TITLE
[0.54.3] React Native screens are blank or partially rendered until reloaded

### ISSUE THREAD

**Issue by buchereli** [facebook/react-native#18610]
- [X] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [X] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [X] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

This seems to me like a simple issue with a simple fix that I missed. I searched extensively for such a fix and failed to find one, sorry if this is a duplicate.

I upgraded from react 48 to 54. When I open a react native screen in my android app it is either partially rendered or just a blank white screen. Upon reloading react native (either through the menu or updating my code) the react screen works perfectly. In addition any react screens that are linked to from the screen I reloaded on work. However, any react screen which can not be reached through react screens from where I reloaded will not work.

For example screen A -> (B, C) and B -> D where A is native and B, C and D are react screens. I start on A go to B see a white screen. Reload on B, B works fine. Go to D, D works fine. Go back to A and then to C and see a white screen. If I go back to B/ D they will still be working fine. If I reload on C, C will work and B and D will not.

## Environment
Environment:
  OS: macOS Sierra 10.12.6
  Node: 9.6.1
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: ^0.54.0 => 0.54.3

## Steps to Reproduce

1. Start packager
2. Run native app
3. Open any react-native screen

`"dependencies": {
    "currency-symbol-map": "^4.0.4",
    "intl": "^1.2.5",
    "locale-currency": "^0.0.2",
    "lodash": "^4.17.5",
    "metro-bundler": "^0.22.1",
    "mobx": "^3.6.1",
    "mobx-persist": "^0.3.4",
    "mobx-react": "^4.4.3",
    "numeral": "^2.0.6",
    "onesky-utils": "^1.2.0",
    "parse": "^1.10.0",
    "rc-swipeout": "^2.0.4",
    "react": "16.3.0-alpha.1",
    "react-intl": "^2.4.0",
    "react-native": "^0.54.0",
    "react-native-animatable": "^1.2.3",
    "react-native-datepicker": "^1.6.0",
    "react-native-image-crop-picker": "^0.18.0",
    "react-native-image-picker": "^0.26.3",
    "react-native-keyboard-aware-scroll-view": "^0.5.0",
    "react-native-keyboard-aware-view": "0.0.14",
    "react-native-masked-text": "^1.3.4",
    "react-native-navigation": "^1.1.134",
    "react-native-tab-view": "^0.0.75",
    "react-native-vector-icons": "^4.5.0",
    "react-navigation": "^1.5.0",
    "realm": "1.13.0",
    "seaq": "^1.0.0",
    "styled-components": "^3.2.1",
    "uuid": "^3.2.1"
  },`

## Expected Behavior
I expect the react screens to work without me needing to reload them.

## Actual Behavior
Native Screen
![screenshot_1522270875](https://user-images.githubusercontent.com/5589760/38056196-af97dd06-3290-11e8-97ce-ce571a4562b2.png)
Select React Screen (White Screen)
![screenshot_1522270882](https://user-images.githubusercontent.com/5589760/38056195-af787600-3290-11e8-90cf-52eabe15a801.png)
Open Menu (Select Reload)
![screenshot_1522270886](https://user-images.githubusercontent.com/5589760/38056194-af60e36e-3290-11e8-84c3-ff43d4329a94.png)
React Screen (Now Working Correctly)
![screenshot_1522270891](https://user-images.githubusercontent.com/5589760/38056193-af470b60-3290-11e8-944a-388a25d3a38c.png)

**Comment by heluotian** [comment]
Have you solved the problem ? It's happening the same to me. No console errors. Nothing. Just a blank screen.

**Comment by buchereli** [comment]
@heluotian No sorry

**Comment by rotemmiz** [comment]
Since moving Detox test project to 0.56.x I did not see any reproduction of this bug

**Comment by amerllica** [comment]
I have the same issue, my version is 0.57. I connected the App to React Native Debugger and search one of my components inside rendered DOM, the React Native Debugger found my components and when I hover them on React Native Debugger in the App they were highlighted. but all of them are white. I have no idea why this happens and have no Idea to fix it.
