### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by rishiankush** [facebook/react-native#18612]
I can't find any support for Iphone X in recent documentation for react native(after 0.51)
`SafeAreaView` is not displayed in the documentation after release of 0.51, i.e. from 0.52 version and there is nothing explained in the release notes why it is not displayed or removed.

Kindly update.

**Comment by rishiankush** [comment]
what information do I need to provide in this question?
It clearly says that `SafeAreaView` is missing from react native documentation from the release of version 0.52

**Comment by hramos** [comment]
Hi @rishiankush, we have a separate repo for documentation matters. This is covered in the template that is shown when a new issue is opened:

> We use GitHub Issues exclusively for tracking bugs in React Native.
>  Questions? Visit http://facebook.github.io/react-native/help.html
>  If this issue is about documentation or the website, please file it at:
>  https://github.com/facebook/react-native-website/issues/new
