### ISSUE TITLE
How to use RCTRootView launch options or initialProperties 

### ISSUE THREAD

**Issue by avnerbarr** [facebook/react-native#1862]
I want to pass in some JSX to the view when creating it in the native code (using launch options or initialProperties?):
```objective-c
RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"ReactTesting"
                                                   launchOptions:@{@"initialProps" : @"<Text>Hello from native code</Text>"}];

rootView.initialProperties = @{@"initialProps" : @"<Text>Hello from native code</Text>"}; // ???
```
And in my module use those values for rendering the view:
```javascript
var ReactForTesting = React.createClass( {

render: function() {
  return (The Launch Options that were sent to this view);
  }
});
```

How do I do that?

**Comment by brentvatne** [comment]
Why not just pass in some data structure that describes what you want, and then build the JSX from it? You won't be able to do what you propose above because the JSX passed in won't be run through a preprocessor.

Hope that helps! If you have any more questions about it, try out StackOverflow :smile: - if you run into a bug then please open an issue here for it!

**Comment by avnerbarr** [comment]
I will try SO , but :). ...

How do I pass in a data structure from my native code and access it from the React code? (I am a iOS developer...)
I would be really happy to see an example of what you mean...

Also, why would the JSX need to be passed through a pre-processor? Wouldn't I be able to build a JSX statement for the render method at runtime depending on the internal structure of the component ? i.e:
```javascript
React.createClass( {
render : function() {
   ... Lots of code to calculate something 
   if expression_1 {
     return (some sort of JSX I dynamically construct at at runtime)
   } else {
      return (different JSX I construct at runtime)
   }
}
}
```
