### ISSUE TITLE
Default TextInput autoCorrect prop to false

### ISSUE THREAD

**Issue by malimichael** [facebook/react-native#18622]
Defaulting `autoCorrect` to true does not feel like the expected behaviour when using the TextInput component. Having opened pretty much every other app on my phone, including facebook & instagram, more often than not autoCorrect is not enabled so it feels like a reasonable default. Happy to open a PR for this

**Comment by hramos** [comment]
Feel free to send a PR. Closing as we are not currently tracking feature requests in this repo.
