### ISSUE TITLE
Flatlist nested Flatlist user error reporting.

### ISSUE THREAD

**Issue by giantss** [facebook/react-native#18625]
`Invariant Violation: Tried to get frame for out of range index NaN`
![image](https://user-images.githubusercontent.com/13778798/38122111-a69d9260-3405-11e8-9a00-495f74638106.png)

Environment:
  ```
OS: macOS Sierra 10.12.6
  Node: 6.11.0
  Yarn: 0.24.5
  npm: 4.6.1
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 2.3 AI-162.3934792
```
Packages: (wanted => installed)
```
  react: 16.2.0 => 16.2.0
  react-native: 0.53.0 => 0.53.0
```

@react-native-bot

**Comment by mohanad-najeeb** [comment]
Same issue

Environment:
  OS: macOS High Sierra 10.13.1
  Node: 8.9.0
  Yarn: 1.6.0
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: 16.3.2 => 16.3.2
  react-native: 0.55.3 => 0.55.3
