### ISSUE TITLE
React native run error

### ISSUE THREAD

**Issue by nembangallen** [facebook/react-native#18633]
- [ ] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [ ] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [ ] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

11:41:27: Launching Dev Tools...
11:41:27: Google Chrome exited with error: Error: Exited with code 1
11:41:27:     at ChildProcess.<anonymous> (/home/allen/Documents/react/FirstApp/node_modules/opn/index.js:86:8)
11:41:27:     at Object.onceWrapper (events.js:317:30)
11:41:27:     at emitTwo (events.js:126:13)
11:41:27:     at ChildProcess.emit (events.js:214:7)
11:41:27:     at maybeClose (internal/child_process.js:925:16)
11:41:27:     at Socket.stream.socket.on (internal/child_process.js:346:11)
11:41:27:     at emitOne (events.js:116:13)
11:41:27:     at Socket.emit (events.js:211:7)
11:41:27:     at Pipe._handle.close [as _onclose] (net.js:567:12)

**Comment by lprhodes** [comment]
I'm seeing this too:

```
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 10.0.0
  Yarn: 1.6.0
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Not Found
  Android Studio: Not Found

Packages: (wanted => installed)
  react: ^16.2.0 => 16.3.2
  react-native: ^0.55.4 => 0.55.4
```

It was after having selected to debug remotely.

**Comment by lprhodes** [comment]
Which turned out to simply be because I was using google chrome canary and not google chrome actual. I renamed the application to just Google Chrome and it started working again.
