### ISSUE TITLE
gradlew assembleRelease producing old APK

### ISSUE THREAD

**Issue by rococtz** [facebook/react-native#18639]
After publishing my first version of the APK to Google Play store, I am now trying to produce a next version. I am running `gradlew assembleRelease` but it keeps producing the old APK.

The app was signed.

I tried `gradlew clean`, but no success.
I also tried everything that I could find in this issue, still no success:
https://github.com/facebook/react-native/issues/6745

Any suggestion, please?

## Environment
Environment:
  OS: Windows 10
  Node: 8.1.3
  Yarn: 0.27.5
  npm: 5.4.2
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  2.3.0.0 AI-162.4069837

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.0 => 0.52.0

**Comment by xanderberkein** [comment]
Hey rococtz, did you ever find the solution to this? I'm stuck at the same problem.

**Comment by KthProg** [comment]
I'm getting this issue as well and it doesn't seem like cleaning the project is fixing it. This is driving me nuts.

**Comment by KthProg** [comment]
I had to upgrade Expo CLI and run `exp publish` before each `gradlew assembleRelease`. I blew out all my code first and pulled it back down from source control. It looks like the way bundling is done has changed at some point, there are no `index.*.js` files and lots of old answers refer to that. It may also be an issue with ejecting from Expo, that the normal documentation doesn't quite work anymore.

**Comment by KthProg** [comment]
@react-native-bot Please re-open this issue (hopefully it's a smart and obedient bot lol)

**Comment by mike-niemand** [comment]
This is ludicrous. App has worked fine for months through several iterations of dev. If I run 'react-native run-android' the app builds the correct version and deploys to my device. Running 'gradlew assemblerelease' it builds an older version. BUT Play Store accepts it as a newer version. It's almost as if the react code is being recompiled.

**Comment by mike-niemand** [comment]
> This is ludicrous. App has worked fine for months through several iterations of dev. If I run 'react-native run-android' the app builds the correct version and deploys to my device. Running 'gradlew assemblerelease' it builds an older version. BUT Play Store accepts it as a newer version. It's almost as if the react code is being recompiled.

https://stackoverflow.com/questions/45441217/release-apk-not-updating-with-javascript-code
