### ISSUE TITLE
RCTTextField build fails iOS

### ISSUE THREAD

**Issue by DLevai94** [facebook/react-native#18632]
When trying to build with the latest Xcode (Version 9.3 (9E145)) to iOS 11.3 iPhone X it fails with this:

`/Users/*****/node_modules/react-native/Libraries/Text/RCTTextField.m:131:108: Values of type 'NSInteger' should not be used as format arguments; add an explicit cast to 'long' instead`

`RCTLogWarn(@"Native TextInput(%@) is %zd events ahead of JS - try to make your JS faster.", self.text, eventLag);`

"react-native": "0.43.2"

Anybody knows about this anything?

**Comment by DLevai94** [comment]
At this version of RN, there's no info so this is all the info :)

**Comment by DLevai94** [comment]
Sometimes it's RCTImage, RCTImageCache.

**Comment by dioxide** [comment]
me too

**Comment by cvongrim** [comment]
Same issue here. I am on 42.3 though. The app builds out to an simulator but I can not do a release build.

**Comment by ErickMaeda** [comment]
Same issue here. I'm using RN 0.44

The app runs well in debug mode. But not able to build in release

**Comment by hramos** [comment]
These are substantially old versions of RN. Please let us know if this is reproduced in 0.54.

**Comment by wenkangzhou** [comment]
Same issue here. I'm using RN 0.49

**Comment by DLevai94** [comment]
@hramos Maybe this guy is on 0.54.4 and same issue? https://github.com/facebook/react-native/issues/18650

**Comment by hramos** [comment]
You'll need to update to a more recent RN release, such as 0.54 or 0.55.

**Comment by ChrisRyuGS** [comment]
In my case, I can build with in cli "npm run ios".
