### ISSUE TITLE
Call iOS native presentViewController fail when <Modal /> visible.

### ISSUE THREAD

**Issue by FaiChou** [facebook/react-native#18645]
RN code:

```
<View style={{flex: 1}}>
  <Modal visible transparent>
    <Button
      onPress={() => NativeModules.Tools.TestPresent()}
      title="Present"
    />
  </Modal>
</View>
```

Objective-C code: 

```
RCT_EXPORT_METHOD(TestPresent) {
  dispatch_async(dispatch_get_main_queue(), ^{
     RCTLog(@"in function");
    TestController *controller = [[TestController alloc] init];
    UIViewController *rooterController = [UIApplication sharedApplication].keyWindow.rootViewController;
    UINavigationController *nav = [[UINavigationController alloc] initWithRootViewController:controller];
    [rooterController presentViewController:nav animated:YES completion:^{
      RCTLog(@"in blocks");
    }];
  });
}
```
When I click `Present` button, nothing happens. `TestController` not present.
But in Xcode console area only ` RCTLog(@"in function");` logs, the ` RCTLog(@"in blocks");` not log;
And yes, breakpoints will go to `[rooterController presentViewController:nav animated:YES completion:^{` and rootController is right, and then nothing will happen, so the completion block won't run.

But If I change RN code this:

```
<View style={{flex: 1}}>
    <Button
      onPress={() => NativeModules.Tools.TestPresent()}
      title="Present"
    />
</View>
```
Everything back to successful without Modal. The TestController will present when press `Present` button.

###  Necessary Information

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.5.0
  Yarn: 1.5.0
  npm: 5.7.1
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.50.1 => 0.50.1

**Comment by vovkasm** [comment]
Because RN presenting its own view controller for modals [see RCTModalHostView.m](https://github.com/facebook/react-native/blob/0.54-stable/React/Views/RCTModalHostView.m#L195).
From this answer https://stackoverflow.com/a/39175552/2266462
> A View Controller can only present one presented controller at a time. Indeed, there is a property: presentedViewController: UIViewController? that implies this.

**Comment by FaiChou** [comment]
@vovkasm 

Thanks, I see.

It's not like react `ReactDOM.createPortal` creates a view on the same level of top view.

RN's `Modal` just a present `vc` instead of a view.

And what's the right way to present a controller on Modal visible using native function?

**Comment by getaaron** [comment]
https://github.com/facebook/react-native/blob/26684cf3adf4094eb6c405d345a75bf8c7c0bf88/React/Views/RCTModalHostViewManager.m#L78

@FaiChou you can present a view controller from the topmost view controller, but presenting from other VCs will silently fail

If you make a native bridge you can use an approach like this to find the top-most VC:

```objective-c
- (void)present:(UIViewController *)newVC {
  UIViewController *rootVC = UIApplication.sharedApplication.delegate.window.rootViewController;
  
  while (rootVC.presentedViewController != nil) {
    rootVC = rootVC.presentedViewController;
  }
  
  [rootVC presentViewController:newVC
                       animated:YES
                     completion:nil];
}
```

But that is a code smell IMO, since you should already know the topmost VC

**Comment by FaiChou** [comment]
thanks all
