### ISSUE TITLE
Flatlist gives error first time

### ISSUE THREAD

**Issue by udarts** [facebook/react-native#18641]
Hi there,

I have a weird error when trying to view the flatlist for the first time.
Let me explain.

I am building an app, where when running the home, it gets data from the google firebase and stores it on the device using asyncstorage. When I am trying to access the page (it get the stored data and adds it to a state item), where the flatlist is , for the first time, I get the following error:

Error with task : Invariant Violation: Tried to get frame for out of range index NaN

But when I refresh the page, the flatlist shows the items correctly.

Why is the error happening only the first time?

This is the code I use (where the flatlist is suppose to show the items from the firebase):
`constructor(props) {
        super(props);
        this.state = {
            loading: true,
            data: [],
            error: null,
            refreshing: false,
            firebaseItems: {}
        }
    }

    _keyExtractor = (item, index) => item.id;

    componentWillMount() {
        this.getItems();
    };

    getItems = () => {

        this.setState({ loading: true });
        AsyncStorage.getItem('firebaseItems')
            .then(result => {
                this.setState({firebaseItems: JSON.parse(result), loading: false, refreshing: false})
            })
            .catch(error => console.log(error));
    };

    handleRefresh = () => {
        this.setState(
          {
            refreshing: true
          },
          () => {
            this.getItems();
          }
        );
    };

    renderFooter = () => {
        if (!this.state.loading) return null;
    
        return (
          <View
            style={{
              paddingVertical: 20,
              borderTopWidth: 1,
              borderColor: "#FFFFFF"
            }}
          >
            <ActivityIndicator animating size="large" color="white" />
          </View>
        );
    };

    goToAnnouncement = (item) => {
        Actions.announceDetails({announcement: item});
    }

    render() {
        return (
            <LinearGradient colors={['#67B26F', '#4ca2cd']} style={styles.container}>
                <FlatList
                    style={styles.flatlist}
                    data={this.state.firebaseItems}
                    renderItem={({ item, index }) => (
                        <TouchableOpacity onPress={this.goToAnnouncement.bind(this, item)}>
                            <View style={styles.separator}>
                                <Text style={styles.text} >{item.title}</Text>
                            </View>
                        </TouchableOpacity>                   
                    )}
                    keyExtractor={this._keyExtractor}
                    ListFooterComponent={this.renderFooter}
                    onRefresh={this.handleRefresh.bind(this)}
                    refreshing={this.state.refreshing}
                />
            </LinearGradient>
        );
    }`

Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.10.0
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.1 AI-173.4670197

Packages: (wanted => installed)
  react: ^16.3.0-rc.0 => 16.3.0-rc.0
  react-native: ^0.54.3 => 0.54.3

What is expected:
Showing items in the flatlist.

What is actually happening:
The first time the page loads, I am getting that error. When refreshing, it shows the items correctly.

**Comment by udarts** [comment]
Thanks, I have updated my issue.

**Comment by udarts** [comment]
I have provided all relevant information. Can you remove the no template label

**Comment by udarts** [comment]
Oh btw, it seems to only occur on Android

**Comment by d41z** [comment]
I have had a simila rproblem....

**Comment by marcpassarelli** [comment]
@udarts have you been able to solve this issue?

**Comment by luskin** [comment]
bump

**Comment by ernestii** [comment]
I had a problem like this when I was returning an empty object in some of my reducers instead of an empty array.

**Comment by gdtrice** [comment]
FYI: hit this issue by accidentally putting an object into a FlatList instead of an array...pretty much the same as @ernestii
