### ISSUE TITLE
deprecated gulp-util@3.0.8 used on react-native@0.54.3 > fbjs-scripts@0.8.1

### ISSUE THREAD

**Issue by dwisetiyadi** [facebook/react-native#18649]
deprecated gulp-util@3.0.8 used on react-native@0.54.3 > fbjs-scripts@0.8.1

- [v ] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [ v] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [ v] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment
Environment:
  OS: macOS High Sierra 10.13.3
  Node: 9.9.0
  Yarn: 1.5.1
  npm: 5.8.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.3.0-alpha.3 => 16.3.0
  react-native: ^0.54.4 => 0.54.4

## Steps to Reproduce
npm i <some package> --save

## Expected Behavior
No error warning come out

## Actual Behavior
Error warning that React Native use deprecated Gulp Util and Babel Core.

**Comment by Rah1x** [comment]
Any solution? Ive running into the same when I do the upgrade:
`react-native-git-upgrade`
=
`gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5)`

**Comment by kelset** [comment]
I think that this can be closed now, as it seems that fbjs > 1.x is not using that lib anymore.
