### ISSUE TITLE
ios swift cocoapods  'algorithm' file not found,Could not build module 'yoga'

### ISSUE THREAD

**Issue by laibinCN** [facebook/react-native#18656]
- [ !] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [ !] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [ !] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment
Scanning folders for symlinks in /Users/miaoyang/Desktop/RN/node_modules (10ms)

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.9.1
  Yarn: 1.5.1
  npm: 5.8.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: ^0.54.4 => 0.54.4
## Steps to Reproduce

ios app 
pod init
vim Podfile
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
react_native_path = '../node_modules/react-native'
target 'RNTest' do
    use_frameworks!
    pod 'yoga', :path => react_native_path + '/ReactCommon/yoga'
    pod 'DoubleConversion', :podspec => react_native_path + '/third-party-podspecs/DoubleConversion.podspec'
    pod 'glog', :podspec => react_native_path + '/third-party-podspecs/glog.podspec'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
    pod 'React', :path => react_native_path, :subspecs => [
    'Core',
    'CxxBridge',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    'RCTImage',
    'RCTNetwork',
    'DevSupport'
    ]
end

React Group
Lexical or Preprocessor Issue Group
/Users/***/Desktop/RN/node_modules/react-native/ReactCommon/yoga/yoga/Yoga-internal.h:11:10: 'algorithm' file not found
Parse Issue Group
/Users/***/Desktop/RN/node_modules/react-native/React/Base/RCTConvert.h:19:9: Could not build module 'yoga'

![image](https://user-images.githubusercontent.com/13825960/38200327-72f50042-36c6-11e8-995d-b899dc49071a.png)

**Comment by laibinCN** [comment]
Finally, manual integration is used.

**Comment by sunny635533** [comment]
@laibinCN how to integration by manually?

**Comment by sunny635533** [comment]
@jerome-bfan i solved by add it to the pod file.

**Comment by laibinCN** [comment]
@sunny635533

**Comment by laibinCN** [comment]
# Uncomment the next line to define a global platform for your projectaa
platform :ios, '8.0'
#install! 'cocoapods', :determiniscd tic_uuid => false
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'
use_frameworks!

target 'AssociationAssistant' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks new
    pod 'Alamofire'

    #====================================
    
    # Pods for ios
    
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
    
    "ART",
    "RCTActionSheet",
    "RCTAnimation",
    "RCTCameraRoll",
    "RCTGeolocation",
    "RCTImage",
    "RCTVibration",
    "DevSupport",
    "RCTLinkingIOS",
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    # Add any other subspecs you want to use in your project
    ]
    # Explicitly include Yoga if you are using RN >= 0.42.0
    pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
    
    # Third party deps podspec link
    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
    pod 'react-native-orientation',:path => "../node_modules/react-native-orientation"
    pod 'react-native-keep-awake', :path => "../node_modules/react-native-keep-awake"
    pod 'RNVectorIcons', :podspec => '../node_modules/react-native-vector-icons/RNVectorIcons.podspec'
    pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
    pod 'react-native-video', :path => '../node_modules/react-native-video'
    pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'

end
def change_lines_in_file(file_path, &change)
    print "Fixing #{file_path}...\n"
    
    contents = []
    
    file = File.open(file_path, 'r')
    file.each_line do | line |
        contents << line
    end
    file.close
    
    File.open(file_path, 'w') do |f|
        f.puts(change.call(contents))
    end
end

post_install do |installer|
    # https://github.com/facebook/yoga/issues/711#issuecomment-381098373
    change_lines_in_file('./Pods/Target Support Files/yoga/yoga-umbrella.h') do |lines|
        lines.reject do | line |
            [
            '#import "Utils.h"',
            '#import "YGLayout.h"',
            '#import "YGNode.h"',
            '#import "YGNodePrint.h"',
            '#import "YGStyle.h"',
            '#import "Yoga-internal.h"',
            ].include?(line.strip)
        end
    end
    
    # https://github.com/facebook/yoga/issues/711#issuecomment-374605785
    change_lines_in_file('../node_modules/react-native/React/Base/Surface/SurfaceHostingView/RCTSurfaceSizeMeasureMode.h') do |lines|
        unless lines[27].include?("#ifdef __cplusplus")
            lines.insert(27, "#ifdef __cplusplus")
            lines.insert(34, "#endif")
        end
        lines
    end
    
    # https://github.com/facebook/react-native/issues/13198
    change_lines_in_file('../node_modules/react-native/Libraries/NativeAnimation/RCTNativeAnimatedNodesManager.h') do |lines|
        lines.map { |line| line.include?("#import <RCTAnimation/RCTValueAnimatedNode.h>") ? '#import "RCTValueAnimatedNode.h"' : line }
    end
    
    # https://github.com/facebook/react-native/issues/16039
    change_lines_in_file('../node_modules/react-native/Libraries/WebSocket/RCTReconnectingWebSocket.m') do |lines|
        lines.map { |line| line.include?("#import <fishhook/fishhook.h>") ? '#import "fishhook.h"' : line }
    end
end
