### ISSUE TITLE
TextInput bounces sometimes inside a ScrollView

### ISSUE THREAD

**Issue by dgruseck** [facebook/react-native#18653]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

If I have a multiline TextInput in a ScrollView and add some lines to the TextInput the TextInput gets sometimes a bounce and you are not able to scroll the ScrollView. Please see my gif and the expo project I created.

## Environment
Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.6.0
  Yarn: 1.5.1
  npm: 5.3.0
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 2.2 AI-145.3537739

Packages: (wanted => installed)
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: https://github.com/expo/react-native/archive/sdk-26.0.0.tar.gz => 0.54.2

The bug is not occuring with expo sdk 25 but with sdk 26, so the bug was propably introduced with the TextInput improvements.
I can also reproduce the bug without expo and react-native 0.54.4.
If you need more information, I'm glad to help you out.

## Steps to Reproduce
https://snack.expo.io/S11euYkjM

## Expected Behavior
The TextInput should not have a bounce or scroll if the content is not bigger than the TextInput.

## Actual Behavior
![textinputscroll](https://user-images.githubusercontent.com/3001347/38193653-5a3e8ee0-3673-11e8-8525-b0629d926b4b.gif)

**Comment by hawkrives** [comment]
I believe this is due to the following line, which makes the TextInput always scrollable:

https://github.com/facebook/react-native/blob/26684cf3adf4094eb6c405d345a75bf8c7c0bf88/Libraries/Text/TextInput/Multiline/RCTMultilineTextInputView.m#L34

**Comment by Panl** [comment]
Any solution ?

**Comment by pozdena** [comment]
Also having this issue.

**Comment by cmedinadeveloper** [comment]
Any solution for this issue?

**Comment by samu** [comment]
The behaviour i'm experiencing is really weird:

* the input is _not_ scrollable if it contains only up to 3 lines
* the input _is_ scrollable if it contains 4 to 7 lines
* the input is _not_ scrollable if it contains more than 7 lines

Plus: onScroll does not fire...

**Comment by traviscrampton** [comment]
Has anybody found a solution for this?

**Comment by steobrien** [comment]
https://github.com/facebook/react-native/pull/19330 was recently merged, which could help with this.
