### ISSUE TITLE
Views inside ScrollView should receive touch event when a TextInput is currently focused.

### ISSUE THREAD

**Issue by BrianSo** [facebook/react-native#18666]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment

**Note: I am using Snack (react-native 0.54 at the time)**. But my local react-native (older version) also reproduces this issue.

Environment:
  OS: macOS High Sierra 10.13.2
  Node: 8.9.0
  Yarn: 1.3.2
  npm: 5.5.1
  Watchman: 4.7.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.1 => 0.52.1

## Steps to Reproduce
https://snack.expo.io/BkmqQiesM

1. Click any TextInput
2. Click any View which is inside `ScrollView`
3. For Android you will see no response from the view you clicked and the keyboard is dismissed. Except for `TextInput` which have a few ms focused.
4. For iOS you will see no response from the view you clicked and the keyboard is dismissed. Except for `TextInput` which behave normally.

## Expected Behavior
Views inside ScrollView should receive touch event when a `TextInput` is currently focused.

## Actual Behavior
Views inside ScrollView do not receive touch event when a `TextInput` is currently focused.

The native `TextInput` inside a ScrollView have a native response (focused) for a few ms but get back to not focused later.

**Comment by BrianSo** [comment]
This issue is related to the property `keyboardShouldPersistTaps` in ScrollView which i didn't expected. https://facebook.github.io/react-native/docs/scrollview.html#keyboardshouldpersisttaps 

Setting `keyboardShouldPersistTaps` to `always` or `handled` will solve the problem.

I think this props should set `always` as the default value so the behaviour of `ScrollView` consists with other Views.

**Comment by ltankey** [comment]
Except if `keyboardShouldPersistTaps` is set to "never", iOS doesn't behave normally, as surely the expected behaviour here is that even moving between `TextInputs` within a `ScrollView`, the keyboard should dismiss each time?

**Comment by BrianSo** [comment]
@ltankey Yes. The behavior is not consistent for `TextInput` when `keyboardShouldPersistTaps` is set to `never`. We can open an issue for this.
