### ISSUE TITLE
Unable to create a new app

### ISSUE THREAD

**Issue by aswinramakrish** [facebook/react-native#18661]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment

Running `react-native info` from the new project failed with the same error (the one specified below). Had to run it from a separate / older project to get the environment info. 

Environment:
OS: macOS Sierra 10.12.6
Node: 6.9.2
Yarn: 1.5.1
npm: 5.8.0
Watchman: 4.9.0
Xcode: Xcode 9.2 Build version 9C40b
Android Studio: Not Found

Packages: (wanted => installed)
react-native: 0.54.4 (Found this in `package.json` of the application that failed, since `react-native info` didn't work)

## Steps to Reproduce

Run `react-native init HelloWorld`.

## Expected Behavior

Build Successful

## Actual Behavior

    /node_modules/@babel/traverse/lib/path/evaluation.js:299`
         return left ** right;
 
    SyntaxError: Unexpected token *
      at Object.exports.runInThisContext (vm.js:76:16)
      at Module._compile (module.js:542:28)
      at Module._extensions..js (module.js:579:10)
      at Object.require.extensions.(anonymous function) [as .js]  (/node_modules/babel-register/lib/node.js:152:7)
      at Module.load (module.js:487:32)
      at tryModuleLoad (module.js:446:12)
      at Function.Module._load (module.js:438:3)
      at Module.require (module.js:497:17)
      at require (internal/module.js:20:19)
      at Object.<anonymous> (/node_modules/@babel/traverse/lib/path/index.js:62:51)

I believe this is because of the `babel` dependency as specified in this issue https://github.com/babel/babel/issues/7654

**EDIT:**  Looking at the dependency tree, it looks like it's pointing to `metro`

![screen shot 2018-04-02 at 3 43 00 pm](https://user-images.githubusercontent.com/1799620/38217735-9b7702b6-368c-11e8-91cc-881b32ce87d0.png)

**Comment by aswinramakrish** [comment]
Apparently it's an issue with the `metro` bundler which has `beta` dependencies on babel 

## React-Native 0.54.4 - Metro's package.json

![screen shot 2018-04-02 at 3 32 35 pm](https://user-images.githubusercontent.com/1799620/38218309-8a6e01f2-368e-11e8-8711-939b4727dd77.png)

## React-Native 0.52.2 - Metro's package.json

![screen shot 2018-04-02 at 3 55 58 pm](https://user-images.githubusercontent.com/1799620/38218328-974dd064-368e-11e8-8472-87642c739ba7.png)

For time being, I'm downgrading to `react-native@0.52.2`. If anyone is interested to know how to do that, here's how - `react-native init HelloWorld --version react-native@0.52.2`

**Comment by aswinramakrish** [comment]
https://github.com/facebook/metro/issues/158

**Comment by kelset** [comment]
I think has been fixed a while back, it was indeed related to versioning connected to babel.

Please let me know if this need to be reopened by providing a repro case (wasn't able to repro at all)
