### ISSUE TITLE
Regression with Alert, AlertIOS, ActionSheetIOS on React Native 0.54.2

### ISSUE THREAD

**Issue by wcandillon** [facebook/react-native#18667]
Hello team 🙋🏼‍♂️

I just upgraded to RN 16.3 and launching an alert of an action sheet from a modal makes it appear below the modal the first time and above the modal if an alert is already below the modal.
You can see the behaviour in this video: https://www.dropbox.com/s/i17nlr5psnxqu6h/modal-bug.mp4?dl=0

Thank you for your great work ❤️

- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment
Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.6.0
  Yarn: 1.1.0
  npm: 5.3.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: https://github.com/expo/react-native/archive/sdk-26.0.0.tar.gz => 0.54.2

## Steps to Reproduce
Launch an alert on iOS from a modal

## Expected Behavior
The alert is shown on top of the modal

## Actual Behavior
The alert is shown below the modal as seen [here](https://www.dropbox.com/s/i17nlr5psnxqu6h/modal-bug.mp4?dl=0)

**Comment by rafaelmotta** [comment]
We are having the issue here.

**Comment by trevorkirpaul** [comment]
If you're all using expo, I found [this](https://forums.expo.io/t/actionsheetios-alert-appear-behind-modal/8338/7) ticket on their forums.

The expo team is helping there so hopefully it might help some of you.

**Comment by rafaelmotta** [comment]
I've switched from 
"react-native": "https://github.com/expo/react-native/archive/sdk-26.0.0.tar.gz"

To

"react-native": "0.54.2"

And now it is working. Seems like is a problem with the expo build.

**Comment by LouisJS** [comment]
Any news ? I still have the issue. Should I update to Expo 16 ?

**Comment by trevorkirpaul** [comment]
[I posted a ticket on Expo's github](https://github.com/expo/expo/issues/1616).

Seems like it's not a React Native issue based on the fact that I didn't have the issue on an older Expo app version, using the same code.

Hopefully, it gets some attention, I linked a small app that showcases the issue as well as a GIF of the issue.

**Comment by rafaelmotta** [comment]
Use another expo package? Really? I’m getting afraid of this.

**Comment by brentvatne** [comment]
@rafaelmotta - you're welcome to use whatever solution you want, we just have one in the SDK for your convenience.

anyhow, closing this issue as it is related to Expo and not react-native itself, as far as I know

**Comment by wcandillon** [comment]
Thank you @brentvatne 🙌🏻
