### ISSUE TITLE
[Layout] Combining `flexWrap: 'wrap'`, `flexDirection: 'row'` causes React to fail silently.

### ISSUE THREAD

**Issue by jtremback** [facebook/react-native#1866]
Observe: https://rnplay.org/apps/5v2yRQ

**Comment by sahrens** [comment]
@vjeux: want to write a quick error checker for this?

**Comment by charlieschwabacher** [comment]
This appears to only be an issue if a child view is wider than the containing view

**Comment by browniefed** [comment]
@jtremback is this still happening?

@ide @brentvatne always suspicious seeing the wrap/row combo since it's now fixed.

**Comment by ide** [comment]
> ...the wrap/row combo since it's now fixed.

I think so too. Closing for now.
