### ISSUE TITLE
[Image] tintColor is not supported with remote images

### ISSUE THREAD

**Issue by ide** [facebook/react-native#1867]
It should be possible to specify a tintColor for a remote image and would be good for parity between static and remote images. Ex:

```js
<Image
  style={{width: 33, height: 29, tintColor: 'blue'}}
  source={{uri: 'http://facebook.github.io/react-native/img/header_logo.png'}}
/>
```

**Comment by ccheever** [comment]
+1
if you've only done web programming you don't realize how useful this is.
implementing this would make react native much more usable for anyone coming from an iOS development background.

**Comment by brentvatne** [comment]
Should `tintColor` be a direct prop rather than part of style? For consistency with other components and because it's not a CSS property

**Comment by ide** [comment]
@brentvatne It probably should be a separate prop.
