### ISSUE TITLE
onLayout calling after componentDidMount

### ISSUE THREAD

**Issue by mastersam92** [facebook/react-native#18684]
As [documentation](https://facebook.github.io/react-native/docs/view.html#onlayout) tells us,
> onLayout
> Invoked **on** mount and layout changes with:..

onLayout must be fired **on** mount.
So, on **Did**Mount, it must be done..

But, onLayout always fires only **after** DidMount

(offtop): For what this function in RN( `componentDidMount` ) is needed, if, in fact, main data( such as component coords etc ) absolutely not ready yet

## Environment
Environment:
  OS: macOS Sierra 10.12.6
  Node: 9.3.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: Not Found
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.53.0 => 0.53.0

## Steps to Reproduce
1. Add this classes( see below ) to project
2. Render `<Parent />` component
3. See console output

```
class Child extends PureComponent {
  componentDidMount() {
    console.log('Child did mount');
  };

  render() {
    console.log('Child on render');
    return (
      <View onLayout={() => console.log('Child onLayout')} />
    );
  };
}

class Parent extends PureComponent {
  componentDidMount() {
    console.log('Parent did mount');
  };

  render() {
    console.log('Parent on render');
    return (
      <View onLayout={() => console.log('Parent onLayout')}>
        <Child />
      </View>
    );
  };
}


```
## Expected Behavior
`onLayout` fires & done before `componentDidMount`
So, in `componentDidMount`, can use result of onLayout

## Actual Behavior
`onLayout` fires after `componentDidMount`

Console output( from code, see above ):
```
Parent on render
Child on render
Child did mount
Parent did mount
Parent onLayout
Child onLayout
```

**Comment by kelset** [comment]
What your code proofs is that your runtime arrow function that uses console log doesn't "show up" in the order you expect. Which is way different than saying that onLayout is not respecting is place in the lifecycle.

**Comment by redbar0n** [comment]
@kelset is there something special with runtime arrow functions using console log? in what other way could it be tested that onLayout respects its place in the lifecycle?

**Comment by mastersam92** [comment]
@kelset I told about expected order:

> As documentation tells us,
> 
>>     onLayout
>>     Invoked on mount and layout changes with:..
> 
> onLayout must be fired on mount.
> So, on DidMount, it must be done..
> 
> But, onLayout ALWAYS fires ONLY AFTER componentDidMount


I'm expect, that `componentDidMount` fires AFTER mount component and other, related with it, tasks( for ex: onLayout, that, as documentation says, fires ON MOUNT, so when fires componentDidMount, it, logically, must be done ), but, it always fires AFTER.

**Comment by redbar0n** [comment]
@mastersam92 I think it's the documentation that ought to be updated to:

_"Invoked **after** mount and layout changes with ..."_

Since layout is apparently done after mounting, according to your experiment. Do you have a change to verify it works the same way in react v0.55 ?

Maybe the doc for onLayout should include something like this, too:

_"
onLayout is fired after the component is rendered (and after all callbacks, like componentDidMount are executed) because then all sizes have been calculated based on the styles and the (possibly dynamic) content.
"_

I'm quite amazed and puzzled that the docs for [the component lifecycle](https://reactjs.org/docs/react-component.html#the-component-lifecycle) doesn't say anything about onLayout...

**Comment by djErock** [comment]
Any resolution here? It seems in my app that if you are rendering something based on prop data or if you push prop data into state inside the constructor, onLayout will finish before DidMount is called... Now if you I massage data inside render for any reason the behavior will be opposite and onLayout will finish after DidMount..

**Comment by redbar0n** [comment]
@djErock 

I found this:

> Summary: `onLayout` event is fired when some layoutable node got inserted or updated (with changed layout) during commit phase.
https://github.com/facebook/react-native/commit/9b7f6abd877cb8f39a01eae716919ae821436c4d

See also:

https://reactjs.org/docs/react-component.html#componentdidmount

My best guess is that the behavior you are seeing has to do with calling setState.

See:

https://itnext.io/react-setstate-usage-and-gotchas-ac10b4e03d60

Also see the setState "Guarantees" at the bottom here. It was very elucidating for me, at least:

http://reactkungfu.com/2016/03/dive-into-react-codebase-handling-state-changes/
