### ISSUE TITLE
Fabric should be excluded from Podspec build

### ISSUE THREAD

**Issue by slycoder** [facebook/react-native#18683]
- [X] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [X] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [X] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

Version 0.55 of React Native includes an experimental `Fabric` library which has some issues building in a Podspec environment.  In particular, it is pulled into `Core` via the `source_files` wildcard and directly includes headers from folly --- however without `folly_compiler_flags` being set on the `Core` subspec, this causes build breakage.

## Environment
  OS: macOS High Sierra 10.13.3
  Node: 9.6.1
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.0 => 0.55.0

## Steps to Reproduce
Create a Pods based project.  Here's an example Podfile snippet:

```
pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'
pod 'DoubleConversion', podspec: '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
pod 'glog', podspec: '../node_modules/react-native/third-party-podspecs/glog.podspec'
pod 'Folly', podspec: '../node_modules/react-native/third-party-podspecs/Folly.podspec'
pod 'React', path: '../node_modules/react-native', :subspecs => [
  'Core',
  'CxxBridge',
  'DevSupport',
  'RCTWebSocket',
  'RCTGeolocation',
  'RCTLinkingIOS',
  'RCTSettings',
  'RCTText',
  'RCTVibration',
  'RCTImage',
  'RCTAnimation',
  'RCTActionSheet',
  'RCTCameraRoll',
]
```

## Expected Behavior
The project builds.

## Actual Behavior
An error is thrown while building complaining that folly/folly-config.h is not found:

```
In file included from <redacted>/node_modules/react-native/React/Fabric/RCTFabricUIManagerWrapper.mm:10:
In file included from <redacted>/node_modules/react-native/ReactCommon/fabric/FabricUIManager.h:10:
In file included from <redacted>/ios/Pods/Folly/folly/dynamic.h:77:
In file included from <redacted>/ios/Pods/Folly/folly/Range.h:22:
In file included from <redacted>/ios/Pods/Folly/folly/FBString.h:41:
In file included from <redacted>/ios/Pods/Folly/folly/Portability.h:23:
<redacted>/ios/Pods/Folly/folly/portability/Config.h:20:10: fatal error: 'folly/folly-config.h' file not found
#include <folly/folly-config.h>
         ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

Inspection of the compile command being executed confirms that `-DFOLLY_NO_CONFIG` is *NOT* being set.

Adding 

```
                              "React/Fabric/*"
```

to the `exclude_files` section of the `Core` subspec fixes the issue.

**Comment by slycoder** [comment]
Domo arigato, Mr React-native-bot-o, but isn't v0.55 > v0.54?

**Comment by hramos** [comment]
0.55.0 has some issues and we are asking people to stay on 0.54.x for now, which is why the latest release (github.com/facebook/react-native/releases) is no longer 0.55.

It's alright to ignore the bot for now.

**Comment by peacechen** [comment]
@hramos 
React Native's official site shows 0.55 as current stable
https://facebook.github.io/react-native/

**Comment by hung-yueh** [comment]
Looks like this issue still there if you do upgrade from old react-native version, so 0.55 shouldn't be the stable version at this point. Should we re-open this issue? or create a new one?

**Comment by youhaowei** [comment]
add `React/Fabric/*` as mentioned above fixed the issue, just wondering if this would make to the next version or not.

**Comment by shafy** [comment]
How do I add it to `exclude_files`. Could you show me your Podfile?

**Comment by shafy** [comment]
Oh ok, thanks!

**Comment by grabbou** [comment]
It's now part of 0.55.3.

**Comment by lyayun** [comment]
add "React/Fabric/*"  did not work for me, Are there any other solutions？？

**Comment by khorark** [comment]
@lyayun, I have version 0.55.4 and problem solution for me. But 0.55.3 I had problem.

**Comment by walker-ll** [comment]
the release to 0.55.4, but there were still problems。
![image](https://user-images.githubusercontent.com/7478867/40479761-09b7fb8e-5f7f-11e8-8cd0-30efc588c085.png)

**Comment by georgecr0ss** [comment]
@lyayun  have you searched for this flag -DFOLLY_NO_CONFIG ? If it's set remove it

**Comment by YVvanessa** [comment]
> @shafy, I just edited the node_modules/react-native/React.podspec, and reran `pod install`. Not pretty but worked.

like this👇👇？？  
but there were still problems😯😯

 s.subspec "Core" do |ss|
    ss.dependency             "yoga", "#{package["version"]}.React"
    ss.source_files         = "React/**/*.{c,h,m,mm,S,cpp}"
    ss.exclude_files        = "**/__tests__/*",
                              "IntegrationTests/*",
                              "React/DevSupport/*",
                              "React/Inspector/*",
                              "ReactCommon/yoga/*",
                              "React/Cxx*/*",
                              "React/Fabric/**/*",
			      "React/Fabric/*"
