### ISSUE TITLE
[0.55.0] Metro Bundler can't listen on port undefined

### ISSUE THREAD

**Issue by ASteinheiser** [facebook/react-native#18681]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)

I am following up on closed issue [#18673](https://github.com/facebook/react-native/issues/18673). This still seems to be an issue. Here's a screenshot of what I'm experiencing. Is there something I am missing?

![screen shot 2018-04-03 at 2 44 27 pm](https://user-images.githubusercontent.com/9949512/38277525-88b64012-374d-11e8-9f2e-f925c4fa2d8b.png)

## Environment

  OS: macOS High Sierra 10.13.3
  Node: 7.9.0
  Yarn: Not Found
  npm: 4.2.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.1 AI-173.4670197

Packages: (wanted => installed)
  react: 16.3.0 => 16.3.0
  react-native: 0.55.0 => 0.55.0

## Steps to Reproduce

```
react-native init AwesomeProject
cd AwesomeProject
react-native run-ios
```

## Expected Behavior

Build Successful!

## Actual Behavior

Metro Bundler can't listen on port undefined

**Comment by ASteinheiser** [comment]
Can confirm that using react-native: 0.52.2 fixed this issue for me.

**Comment by leofontes** [comment]
This is happening to me too, 0.52.2 with React 16.2.0 fixed it.

**Comment by shivawu** [comment]
Apparently this is related to #18525, that issue fixes device but simulator is still broken, because `port` is not passed into `buildProject`. 

https://github.com/facebook/react-native/blob/master/local-cli/runIOS/runIOS.js#L130

Adding `, port` to this function call should temporarily fix the issue

**Comment by kaushal9678** [comment]
after updating npm i also get  error when running command **react-native init-ios**. 
**React Native 0.55.0 CFBundleIdentifier error after fixing metro port**
But the projects that are created with lower version is works fine without any error.

I have following versions of NPM, react-native, node js
**react-native-cli: 2.0.1
react-native: 0.55.0,
 I downgrade NPM version to this npm 3.10.10
node -verison v6.14.1**

**Comment by hatlestad** [comment]
I am experiencing the same issue with 0.55.0.

**Comment by karlmosenbacher** [comment]
same here

**Comment by donjordano** [comment]
Same here!

**Comment by kelset** [comment]
First off, **PLEASE** don't pollute the issue with useless 'same issue' comments.

There are the reactions for indicating that this issue is present.

That said, please don't use 0.55.0 because [it ships with the wrong version of React](https://github.com/react-native-community/react-native-releases/issues/2#issuecomment-378351125). We are going to release soon a new version.

**Comment by grabbou** [comment]
I believe we need to fix this as soon as possible - @kitze was reporting this to me yesterday. I will take a closer look before releasing a new version.

**Comment by shivawu** [comment]
@wouterds if you read through my comment, I provided another fix for this current problem, that issue is only a reference

**Comment by shivawu** [comment]
I have to say the release process has been very carelessly, recently. 

- With 0.55, it’s this and the wrong dependency on react itself. 
- With 0.54 it’s #18175 and #18223. 
- With 0.53, not really react-native fault, but it’s https://github.com/oblador/react-native-vector-icons/issues/626.

Each major release has flaws that makes it unusable. Especially with 0.54 and 0.55. I always have postinstall script setup to fix react-native. Feel like it’s SEV worthy and time to revise the process

**Comment by hramos** [comment]
@shivawu the release spends around a month as a release candidate. That's a great time to give the RC a try and surface any issues, prior to the stable release being cut.

**Comment by shivawu** [comment]
I’m aware of the Rc version and really appreciated the effort. Yet these seems-easy-to-discover bugs slipped through into the stable release, just saying there seems the process can be improved

**Comment by wouterds** [comment]
@shivawu: No, we're talking about the same issue. See thread of OP mentioning #18673 which mentions #17983 which is exactly the fix you provided, and is already included in 0.55.

**Comment by shivawu** [comment]
I see, good catch. But apparently this change is not included in 0.55.0 for some reason, from the git commit of that particular release:

https://github.com/facebook/react-native/blob/2e384184bc7b3173e3bb41e2128eb75ba8aee8db/local-cli/runIOS/runIOS.js#L130

**Comment by wouterds** [comment]
@shivawu: I rest my case 😅.

**Comment by shivawu** [comment]
I know, it's super confusing, for a minute I bought what you said, lol 😂

**Comment by grabbou** [comment]
You can find a fix here: https://github.com/facebook/react-native/commit/589eae1432cc4bbc16221f841e27b038099fd128

**Comment by grabbou** [comment]
@shivawu The releases are cut very carefully, but there's just too many pieces to test at one time. That's why having people to use release candidates would prevent such obvious errors from leaking into production. 

Recent issues have to do with `runIOS` which is not part of our manual and automated testing.

**Comment by mateoguzmana** [comment]
With this solution https://github.com/facebook/react-native/issues/18681#issuecomment-378441952 the metro bundler works. But, still appearing this error.

![image](https://user-images.githubusercontent.com/20783123/38393680-3285f4ee-38f1-11e8-9fee-4fcd385e2ca2.png)

**Comment by grabbou** [comment]
Yeah, I fixed both in 0.55.
https://github.com/react-native-community/react-native-releases/issues/11#issuecomment-378889572

**Comment by wellyshen** [comment]
@grabbou I upgraded to 0.55 and run `react-native run-ios` it build success but the simulator won't be triggered. so wired...

**Comment by wellyshen** [comment]
@grabbou Thank you for this temporary solution.

**Comment by grabbou** [comment]
Here's my proposed fix:
https://github.com/facebook/react-native/commit/2ad34075f1d048bebb08ef30799ac0d081073150#r28448345
Waiting
for feedback and will release a patch.

I am really sorry for all the inconvenience issues with the command line
tools caused for you. For the future, we will make sure to pay even more
attention to commits affecting the CLI.

**Comment by grabbou** [comment]
Here's PR: https://github.com/facebook/react-native/pull/18721. I'll probably merge it today and once 0.55 is out, make a PR back to `master` to make sure it has all the fixes.

**Comment by markzero** [comment]
This doesn't happen with React `16.3.1` and React Native `0.55.4`.
