### ISSUE TITLE
Getting RCTText related errors while taking release build from XCode

### ISSUE THREAD

**Issue by sahil290791** [facebook/react-native#18693]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [ ] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Issue:
I am able to test using `react-native run-ios` but I get the below error while taking a release build from XCode. It was working prior to updating XCode(9.2)

![screen shot 2018-04-04 at 3 40 42 pm](https://user-images.githubusercontent.com/7287280/38302464-6b605402-3820-11e8-8478-05fe734f723e.png)

**Podfile**
```Podfile
react_native_path = '../node_modules/react-native'
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'app' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for app
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'
  pod 'Google/SignIn'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Firebase/Core', '4.0.0'
  pod 'Firebase/Messaging'

 # To use CocoaPods with React Native, you need to add this specific Yoga spec as well
 pod 'Yoga', :path => react_native_path + '/ReactCommon/yoga'

 # You don't necessarily need all of these subspecs, but this would be a typical setup.
 pod 'React', :path => react_native_path, :subspecs => [
   'Core',
   'BatchedBridge',
   'RCTNetwork',
   'RCTText',
   'RCTWebSocket', # needed for debugging
   'RCTImage',
   # Add any other subspecs you want to use in your project
   'DevSupport'
 ]

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    # if target.name == "react-native-google-maps"
    #   target.build_configurations.each do |config|
    #     config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
    #   end
    # end

    if target.name == "React"
      target.remove_from_project
    end
  end
end
```

## Environment
Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.9.3
  Yarn: 1.3.2
  npm: 5.5.1
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.1 AI-173.4670197

Packages: (wanted => installed)
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: 0.45.1 => 0.45.1

**Comment by sahil290791** [comment]
@react-native-bot react-native info command is giving this error:
```
Unrecognized command 'info'
  Run react-native --help to see list of all available commands
```

**Comment by markjongkind** [comment]
I had the same issues, my (temporary) fix was to downgrade Xcode from 9.3 to 9.2 so I could finish the release build.

**Comment by smooJitter** [comment]
Downgrade Xcode?  That's drastic. I am having a similar issue RCTText 'React/RCTUtils.h' file not found.  Totally clean install of most recent react-native

**Comment by hramos** [comment]
You'll need to use a more recent version of RN with Xcode 9.3.

**Comment by sahil290791** [comment]
@hramos can you please mention which RN version onwards it will start working with XCode 9.3?

**Comment by hramos** [comment]
0.54 is known to work with Xcode 9.3.

**Comment by leoabacade** [comment]
@sahil290791 did you solve this?

**Comment by sahil290791** [comment]
@leoabacade I ended up upgrading to RN 49+ and it works now. Or the other way is to downgrade XCode to previous working version.
