### ISSUE TITLE
version 0.54 error Share on facebook android

### ISSUE THREAD

**Issue by trung1008** [facebook/react-native#18698]
'i'm using react-native version 0.54 and Share of react-native
everything ok except share facebook on android not show anything (title, message or url)
anyone can help me
thanks

**Comment by trung1008** [comment]
i'm using react-native version 0.54 and Share of react-native
everything ok except share facebook on android not show anything (title, message or url)
anyone can help me
thanks

**Comment by trung1008** [comment]
probliem still not resovled.

**Comment by MarkOSullivan94** [comment]
Could be linked to #18993
