### ISSUE TITLE
Touch ID support

### ISSUE THREAD

**Issue by tmszyman** [facebook/react-native#18699]
Any plans for Touch ID support?

**Comment by jtich** [comment]
@hramos I too am wondering this same thing... it appears React Native supported Touch ID at some point in time (as there are multiple libraries that expect NativeModules to include a TouchID object). Can you confirm and/or expalin this @hramos?

Many thanks!

**Comment by hramos** [comment]
You may want to try the discussion forum instead. I don't want to encourage questions to be posted as issues.
