### ISSUE TITLE
xxx/node_modules/react-native/Libraries/Text/RCTTextView.m:238:108: Values of type 'NSInteger' should not be used as format arguments; add an explicit cast to 'long' instead

### ISSUE THREAD

**Issue by yusheng-jia** [facebook/react-native#18694]
when I update xcode to 9.3 ,it happened!(xcode 9.2 is OK)

[xxx/node_modules/react-native/Libraries/Text/RCTTextView.m:238:108:](url) Values of type 'NSInteger' should not be used as format arguments; add an explicit cast to 'long' instead

- [1 ] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [1 ] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [ ] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment

Environment:
  OS:  macOS High Sierra 10.13.3
  Node:  8.10.0
  Yarn:  1.1.0
  npm:  5.8.0
  Watchman:  4.9.0
  Xcode:  Xcode 9.3 Build version 9E145
  Android Studio:  3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: 0.48.4 => 0.48.4

**Comment by hramos** [comment]
You'll need to use a more recent version of RN with Xcode 9.3.

**Comment by niranjan-b-prajapati** [comment]
I am using RN v 0.44 and yesterday i updated Xcode to 9.3 and i have started facing the same issue, we can't upgrade the RN to latest as there is currently some development going on which needs to go live, after which we can upgrade RN version. But currently need a fix for RN 0.44 with Xcode 9.3

**Comment by farhanmannan** [comment]
@hramos what's the oldest version of RN that will work with Xcode 9.3 ? 
I'm in a similar boat to @niranjan-b-prajapati because we are on RN 0.45.1 and running `react-native-git-upgrade` always introduces time-consuming errors

**Comment by niranjan-b-prajapati** [comment]
@farhanmannan It was very much urgent for me to fix that issue. I eventually ended up rolling back my Xcode to 9.2 again.

**Comment by farhanmannan** [comment]
@niranjan-b-prajapati Cool, I've actually done the same but when I archive the build and upload it to the app store, I get an email saying "Invalid Swift Support - The SwiftSupport folder is empty" - did you have this issue?
