### ISSUE TITLE
Unable to load script from assets 'index.android.bundle'.make sure you bundle is packaged correctly.....

### ISSUE THREAD

**Issue by wuyunqiang** [facebook/react-native#18692]
Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.3.0
  Yarn: 0.27.5
  npm: 5.5.1
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.3.0-alpha.0 => 16.3.1
  react-native: 0.55.0 => 0.55.0

## Steps to Reproduce
1:react-native init Test
2:cd Test
3:react-native run-andorid
use android virtual genymotion google nexus 6p-7.1.0

## Expected Behavior
run normal like ios is ok.

## Actual Behavior
if release is ok .
can't load script and can't debug start chrome.
```
Unable to load script from assets 'index.android.bundle'.make sure you bundle is packaged correctly.....
```
![node](https://user-images.githubusercontent.com/13480948/38301871-6f48ff34-3833-11e8-9e24-97b641642c48.png)

<img width="469" alt="bundle" src="https://user-images.githubusercontent.com/13480948/38301853-64708b86-3833-11e8-8a9e-e9824874829f.png">

![installsuccess](https://user-images.githubusercontent.com/13480948/38301911-8650642e-3833-11e8-9126-d6a4c8763126.png)

**Comment by lucasbento** [comment]
@wuyunqiang: can you run `adb reverse tcp:8081 tcp:8081` and try again?

**Comment by wuyunqiang** [comment]
yes I try.
like that 
https://stackoverflow.com/questions/32572399/react-native-android-failed-to-load-js-bundle
no work.

**Comment by lucasbento** [comment]
@wuyunqiang: try selecting "Dev Settings" from the Developer Menu, then update the "Debug server host for device" setting to match the IP address of your computer.

**Comment by wuyunqiang** [comment]
before I meet this bug,and I sudo npm start run will be ok.
and now it's no work.
please help.

**Comment by lucasbento** [comment]
@wuyunqiang: move your issue to [stackoverflow](https://stackoverflow.com) because this not a bug report and you will get much more chances of help in there.

**Comment by chinmaygit** [comment]
Why is this issue closed? I am sure this issue is occurring after 0.54.** to 0.55.0 upgrade.

Android Logcat:- java.lang.RuntimeException: Unable to load script from assets 'index.android.bundle'. Make sure your bundle is packaged correctly or you're running a packager server.

after reversing the adb ports, started working in debug mode, but crashing with above error in production.

**Comment by wuyunqiang** [comment]
I run "sudo npm start run" and show
![watchman](https://user-images.githubusercontent.com/13480948/38535291-6233f84a-3cb5-11e8-80da-a538292a30fb.png)
it's about watchman? 
1:npm r -g watchman
2:brew uninstall watchman 
3:brew link pcre 
4:brew install --HEAD watchman
but no work still bug.

**Comment by sequencer08** [comment]
Hi guys. I have the same issue. Here's my logcat output:

![screen shot 2018-04-24 at 2 56 15 pm](https://user-images.githubusercontent.com/38305614/39170901-b0b82124-47cf-11e8-95d7-1d092b5d14d0.png)

**Comment by gurbela** [comment]
**For IOS:**

In a terminal: `cd ios`

Remove the build folder with: `rm -r build`

Run again: `react-native run-ios`

Alternatively, you could open Finder, navigate to Y**OUR_PROJECT/ios** and **delete the build folder**.

Then run again: `react-native run-ios`

**For ANDROID:**

In a terminal: `cd android/app`

Remove the build folder with: `rm -r build`

Run again: `react-native run-android`

Alternatively, you could open Finder, navigate to **YOUR_PROJECT/android/app** and **delete the build folder.**

Then run again: `react-native run-android`

**Comment by darkmantle** [comment]
I have tried ALL the answers here, but none work at all. Including removing build folder, clearing watchman, running as sudo, etc.

**Comment by Hanv2itedu** [comment]
@darkmantle me neither :(

**Comment by OmalPerera** [comment]
same problem

**Comment by giovannigenna** [comment]
same problem here.....

**Comment by vauruk** [comment]
same problem here...

**Comment by giovannigenna** [comment]
I have resolved doing this commands:
`// create new project
react-native init awesomeproject

// use react native 0.55.4
npm remove --save react-native
npm i --save react-native@0.55.4

npm remove babel-preset-react-native
npm i --save babel-preset-react-native@2.1.0

// create folder assets in android\app\src\mainoid
mkdir android\app\src\main\assets

// create the "index.android.bundle" file
react-native bundle --platform android --dev false --entry-file index.js --bundle-output android\app\src\main\assets\index.android.bundle --assets-dest android\app\src\main\res

// run the app on android device
react-native run-android`

Hope to help someone ;)

**Comment by oguzkaganeren** [comment]
If you work on the Windows, you should run `react-native bundle --platform android --dev false --entry-file index.js --bundle-output android\app\src\main\assets\index.android.bundle --assets-dest android\app\src\main\res`  with cmd run as administrator(İmportant). Thus the problem was fixed :)

**Comment by amitbravo** [comment]
this trick "creating assets folder etc"  sucks , neither I can not use debugger nor hot reloading ..

**Comment by kilobyteforce** [comment]
thnx  ovannigenna, finally i got evaded from this thing. thnx buddy.

**Comment by picninim** [comment]
If you don't and to keep generating the bundle through command line all the time, you could use the Debbuger mode:

http://facebook.github.io/react-native/docs/debugging#debugging-on-a-device-with-chrome-developer-tools

This would make the Chrome to run the JS:
https://facebook.github.io/react-native/docs/javascript-environment
 
So a new bundle will created so the browser can run, and the app will use that bundle.

**Comment by chinmaygit** [comment]
It seems that the bundle name is changed from index.bundle to index.android.bundle not sure, best you can do is 
- Remove the ios and android folders and `react-native eject` to recreate those folders.
- Creating `android\app\src\main\assets` folder. 

There is some relation between, name in package.json, app.json, application Id in build.gradle file, Activity class, and Application class package name, method getMainComponentName() 
 in MainApplication.java class which returns the component name. Check the names are correct or not. I am not clear how those things work together if anyone can guide me about this, but by making sure the app name in app.json and getMainComponentName() are same, solved my problem.

Not perfect solution for this issue. lots of things are unclear.

RN people need to use the latest versions of android gradle libs, and some info about if not already there, how it generates android project on react-native init, it will be helpful.

**Comment by a-oboh** [comment]
> If you work on the Windows, you should run `react-native bundle --platform android --dev false --entry-file index.js --bundle-output android\app\src\main\assets\index.android.bundle --assets-dest android\app\src\main\res` with cmd run as administrator(İmportant). Thus the problem was fixed :)

I've tried this countless times but i keep getting this type of error: 

`Error: Unable to resolve module `@babel/runtime/helpers/interopRequireDefault` from `C:\Users\Albert\reactnative apps\test2\index.js`: Module `@babel/runtime/helpers/interopRequireDefault` does not exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
    at ModuleResolver.resolveDependency (C:\Users\Albert\reactnative apps\test2\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:209:1301)
    at ResolutionRequest.resolveDependency (C:\Users\Albert\reactnative apps\test2\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:83:16)
    at DependencyGraph.resolveDependency (C:\Users\Albert\reactnative apps\test2\node_modules\metro\src\node-haste\DependencyGraph.js:238:485)
    at Object.resolve (C:\Users\Albert\reactnative apps\test2\node_modules\metro\src\lib\transformHelpers.js:180:25)
    at dependencies.map.result (C:\Users\Albert\reactnative apps\test2\node_modules\metro\src\DeltaBundler\traverseDependencies.js:311:29)
    at Array.map (<anonymous>)
    at resolveDependencies (C:\Users\Albert\reactnative apps\test2\node_modules\metro\src\DeltaBundler\traverseDependencies.js:307:16)
    at C:\Users\Albert\reactnative apps\test2\node_modules\metro\src\DeltaBundler\traverseDependencies.js:164:33
    at Generator.next (<anonymous>)
    at step (C:\Users\Albert\reactnative apps\test2\node_modules\metro\src\DeltaBundler\traverseDependencies.js:266:307)`

**Comment by landongme** [comment]
> > If you work on the Windows, you should run `react-native bundle --platform android --dev false --entry-file index.js --bundle-output android\app\src\main\assets\index.android.bundle --assets-dest android\app\src\main\res` with cmd run as administrator(İmportant). Thus the problem was fixed :)
> 
> I've tried this countless times but i keep getting this type of error:
> 
> `Error: Unable to resolve module`@babel/runtime/helpers/interopRequireDefault`from`C:\Users\Albert\reactnative apps\test2\index.js`: Module`@babel/runtime/helpers/interopRequireDefault` does not exist in the Haste module map
> 
> This might be related to #4968
> To resolve try the following:
> 
> 1. Clear watchman watches: `watchman watch-del-all`.
> 2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
> 3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
> 4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
>    at ModuleResolver.resolveDependency (C:\Users\Albert\reactnative apps\test2\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:209:1301)
>    at ResolutionRequest.resolveDependency (C:\Users\Albert\reactnative apps\test2\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:83:16)
>    at DependencyGraph.resolveDependency (C:\Users\Albert\reactnative apps\test2\node_modules\metro\src\node-haste\DependencyGraph.js:238:485)
>    at Object.resolve (C:\Users\Albert\reactnative apps\test2\node_modules\metro\src\lib\transformHelpers.js:180:25)
>    at dependencies.map.result (C:\Users\Albert\reactnative apps\test2\node_modules\metro\src\DeltaBundler\traverseDependencies.js:311:29)
>    at Array.map ()
>    at resolveDependencies (C:\Users\Albert\reactnative apps\test2\node_modules\metro\src\DeltaBundler\traverseDependencies.js:307:16)
>    at C:\Users\Albert\reactnative apps\test2\node_modules\metro\src\DeltaBundler\traverseDependencies.js:164:33
>    at Generator.next ()
>    at step (C:\Users\Albert\reactnative apps\test2\node_modules\metro\src\DeltaBundler\traverseDependencies.js:266:307)`

it works, try :
npm add @babel/runtime

**Comment by km16** [comment]
My project runs in debug mode, but the release apk crashes. The logs have the same error -> `Unable to load script from assets 'index.android.bundle'`. What should I do to fix this?

The apk was generating fine, until today. I don't see how I caused it.

**Comment by wikieswan** [comment]
@km16  i fixed this.
i use android studio ,not eclipse.``` assets``` dir in android studio is ```android/app/assets```,however,  in eclipse is ```android/app/src/main/assets``` . So move ```index.android.bundle index.android.bundle.meta``` from  ```android/app/src/main/assets``` to ```android/app/assets```.  it works for me

**Comment by phips28** [comment]
I have a problem on creating a release build, since today its not building correctly anymore (I dont know why):

1) Task `:app:bundleReleaseJsAndAssets` successfully creates the index.android.bundle

```
PATH..../android/app/build/intermediates/assets/release/index.android.bundle
bundle: Done writing bundle output
bundle: Copying 196 asset files
bundle: Done copying assets
```

2) but when I install the .apk release file, it is unable to load the bundle file. Because its not in the apk. also the assets (images) are not in the .apk.
How can this happen?

**Comment by neurosnap** [comment]
I spent hours reading every single issue remotely related to the error to figure out how to fix this problem.  The issue was `useClearText` is disabled by default on Android > 9.0.

 https://stackoverflow.com/a/53326616/1713216

**Comment by flexaddicted** [comment]
> I have spent hours trying to figure this issue out.
> 
> Accessing the development server worked locally and in the emulator's browser. The only thing that did not work was accessing the development server in the app.
> 
> > Starting with Android 9.0 (API level 28), cleartext support is disabled by default.
> 
> AndroidManifest.xml
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <manifest ...>
>     <uses-permission android:name="android.permission.INTERNET" />
>     <application
>         ...
>         android:usesCleartextTraffic="true"
>         ...>
>         ...
>     </application>
> </manifest>
> ```
> See for more info: https://stackoverflow.com/a/50834600/1713216

Thank you!

**Comment by akshaysargar** [comment]
@phips28 , @km16 did you guys get any solution?
My app works fine on physical device when debugging over USB but the release apk crashes.

**Comment by phips28** [comment]
@akshaysargar I updated to the latest RN 0.57 with the new metro bundler. then it worked

**Comment by rgaraev** [comment]
@akshaysargar  I faced the same problem. Signed app doesn't work on device.  I spent a whole day but  there is no success yet. I will write when find the soulution.

**Comment by mtkopone** [comment]
I caused this to myself by upgrading the gradle to com.android.tools.build:gradle:3.2.1. And that was because of trying to integrate firebase. Solved by upgrading RN to the latest version.

**Comment by tsvetan-ganev** [comment]
I also lost a lot of time trying to debug the reason. Everything worked perfectly when running with the packager server running, but the application froze on start when running the production build. 

In the end I deleted and then re-generated the `index.android.bundle` file:

```bash
$ rm android/app/src/main/assets/index.android.bundle
$ react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
```

And then did a clean Gradle build:

```bash
$ cd ./android
$ ./gradlew clean && ./gradlew assembleRelease
```

**Comment by rgaraev** [comment]
@mtkopone @phips28 thank you. Problem was solved after updating rn to 0.57.5
@akshaysargar have you tried to update rn?

**Comment by akshaysargar** [comment]
Yes updated RN to 0.57.5 and finally it worked !!! 
This issue took me few days to solve it. I was working on RN 0.55.4 initially but was cautiously updating  the RN as I had to take care of lot of dependencies. So just to inform, this issue that we are solving occurs on versions 0.56.0, 0.57.0 but finally I updated to the latest version 0.57.5 and that worked. Thanks @phips28, @mtkopone, @rgaraev

**Comment by phonganhhung9xtb** [comment]
i meet same error with RN 0.57 at log cat of Android studio? i tried all way above but not solution. anyone same me?

**Comment by rgaraev** [comment]
> i meet same error with RN 0.57 at log cat of Android studio? i tried all way above but not solution. anyone same me?

@phonganhhung9xtb,  What version of react native do you have exactly? I updated to 0.57.7 and the problem was solved.

**Comment by jeffmwells** [comment]
I am having the same issue with 0.57.7. If i add the `import com.facebook.react.BuildConfig;` to MainApplication.java, the app crashes entirely rather than giving a red screen of death. Same happens if i just return true or false from `getUseDeveloperSupport()`. I don't think generating the bundle is a valid solution.

**Comment by rafedweb** [comment]
I also have same issue. nothing work to me.

**Comment by IsraelSouza** [comment]
Simple as that: https://medium.com/@adityasingh_32512/solved-unable-to-load-script-from-assets-index-android-bundle-bdc5e3a3d5ff

Saved my life!

**Comment by GospelHW** [comment]
I updated to v0.58.3 I also have same issue now...

**Comment by GospelHW** [comment]
<img width="1220" alt="2019-02-02 3 42 01" src="https://user-images.githubusercontent.com/24928406/52161531-23c3dd00-2701-11e9-9f69-dbc9c1f4237d.png">
<img width="388" alt="2019-02-02 3 45 45" src="https://user-images.githubusercontent.com/24928406/52161560-a187e880-2701-11e9-833d-53e05e99848d.png">

**Comment by nuwan-dammika** [comment]
> 
> 
> Simple as that: https://medium.com/@adityasingh_32512/solved-unable-to-load-script-from-assets-index-android-bundle-bdc5e3a3d5ff
> 
> Saved my life!

Saved lots of my hours too, thanks

**Comment by uzunF** [comment]
> adb reverse tcp:8081 tcp:8081

it works for me, thanks.
