### ISSUE TITLE
DatePickerIOS is showing date decreased by 1 day

### ISSUE THREAD

**Issue by michaltaberski** [facebook/react-native#18704]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [ ] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)
Presonally I didn't run int on a latest RN, but I reproduced the bug on Expo [link to app](https://expo.io/--/to-exp/exp%3A%2F%2Fexpo.io%2F%40snack%2Fsdk.26.0.0-B1SsZgMoM)?

## Environment
```
react-native --version

react-native-cli: 2.0.1
react-native: 0.35.0
```

## Steps to Reproduce
Run the code below:
```
import React, { Component } from 'react';
import { Text, View, DatePickerIOS } from 'react-native';
import moment from 'moment';

export default class Demo extends Component {
  render() {
    const date = moment('06/06/1972', 'DD/MM/YYYY').toDate();
    return (
      <View style={{paddingTop: 50}}>
        <Text>{date.toString()}</Text>
        <DatePickerIOS date={date} mode="date"/>
      </View>
    );
  }
}

```

__pay attention:__ the date is important - it has to be date before 1976. `06/06/1972` is a good example. Younger dates likes 90's or later works fine.

## Expected Behavior
Date picker should show the date `June 06 1972`

## Actual Behavior
Date picker is showing the date `June 05 1972`
![issue](https://user-images.githubusercontent.com/202033/38292894-cd470f0c-37e5-11e8-901a-1f803ea023b5.png)

**Comment by deecewan** [comment]
just created a new app with `create-react-native-app`, then ran `yarn add moment` and then `yarn start`, and spawned the iOS simulator.

All looks pretty normal to me:

![image](https://user-images.githubusercontent.com/4755785/38343548-ef7d62be-38c7-11e8-9a22-de2e794827a2.png)

**Comment by ratkus91** [comment]
I have the same problem:
Date does not change sometimes when I scroll hours.

![default](https://user-images.githubusercontent.com/7541905/38369096-9e0b0936-38ef-11e8-8dc3-414759e409b0.png)

**Comment by michaltaberski** [comment]
@deecewan Thanks for checking the issue. I have prepared Expo app with exactly the code I am showing above.  The issue is is still happening

## https://snack.expo.io/rJ4cK3QiM
<img width="240" alt="screen shot 2018-04-05 at 17 05 53" src="https://user-images.githubusercontent.com/202033/38374323-9f67f466-38f3-11e8-8602-854c6f4069b2.png">

**Comment by Fokey** [comment]
https://snack.expo.io/B12VAc3RQ

Not sure if related or if it's just not being updated in time for the console.log to fire off, but when logging the state being changed by the DatePickerIOS you're given the value of the previous date.
