### ISSUE TITLE
BlobModule supports invokes virtual method String.equals() on null

### ISSUE THREAD

**Issue by zhaonian** [facebook/react-native#18709]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

app breaks after upgrading to RN-0.54 due to exception in native call.

## Environment

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.7.1
  Yarn: 1.3.2
  npm: 5.8.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.1 AI-173.4670197

Packages: (wanted => installed)
  react: ^16.3.0-alpha.1 => 16.3.0-alpha.3
  react-native: 0.54.2 => 0.54.2

## Steps to Reproduce

* upgrade to RN 0.54
* debug in release mode on Android
## Expected Behavior

the app should not break
## Actual Behavior

```
04-05 06:43:35.824 20182-20198/com.science.ure E/Surface: getSlotFromBufferLocked: unknown buffer: 0xea08c500
04-05 06:43:37.388 20182-20211/com.science.ure E/unknown:ReactNative: Exception in native call
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
        at com.facebook.react.modules.blob.BlobModule$2.supports(BlobModule.java:83)
        at com.facebook.react.modules.network.NetworkingModule.sendRequest(NetworkingModule.java:257)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
        at android.os.Looper.loop(Looper.java:148)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
        at java.lang.Thread.run(Thread.java:818)
```
![image](https://user-images.githubusercontent.com/15934059/38351701-89d74c8e-3865-11e8-812b-1f293aafd424.png)

the line of code that break in `BlobModule` is:
```
        boolean isRemote = scheme.equals("http") || scheme.equals("https");
```
looks like it did not successfully get the `scheme`, which should be returned by `getScheme()` from `NetworkingModule`. 

Potential solution:
Add null-checking on `scheme`? #

**Comment by shockdesign** [comment]
An easy fix would be just to replace that line with
```
boolean isRemote = "http".equals(scheme) || "https".equals(scheme);
```

**Comment by zhaonian** [comment]
@shockdesign   thanks for your reply! :D I found what is causing this error. 
I simply set a break point on this line and i found that `react-native-svg-uri` is passing local svg file as a uri, so this function `getScheme()` in the `NetworkingModule.java` returns `null` and breaks `"http".equals(scheme)`.

**Comment by Brian-Azizi** [comment]
has this been fixed now?

**Comment by jh3141** [comment]
@Brian-Azizi  - no, not fixed.  Current master [still has the same issue](https://github.com/facebook/react-native/blob/1490ab12ef156bf3201882eeabfcac18a1210352/ReactAndroid/src/main/java/com/facebook/react/modules/blob/BlobModule.java#L82).  Original poster found a workaround for his specific instance of the problem and therefore closed it, but the problem still persists for the rest of us...

**Comment by zhaonian** [comment]
Hi guys. Try to pen Android studio and set a break point at this line and see where this 'null' comes from. Then you can go back to your react native code to fix it.

**Comment by thymikee** [comment]
I, for example, bump into this while calling `/graphql` endpoint through non-native library (`apollo-client`).

**Comment by shockdesign** [comment]
Submitted the fix ^^

**Comment by vendramini** [comment]
Even using the fix, the problem persists here. Anyone else?

**Comment by hayait599** [comment]
same issue :(

**Comment by diegohdez90** [comment]
Same here.
