### ISSUE TITLE
KeyboardAvoidingView pushing the content off screen.

### ISSUE THREAD

**Issue by ishrak-imam** [facebook/react-native#18717]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

I am using the `KeyboardAvoidingView` to make my UI respond gracefully when the keyboard is open, but it's not reflecting the expected behavior. It pushes the UI upward and hides the content at the top.
![screenshot from 2018-04-06 12-37-27](https://user-images.githubusercontent.com/16683923/38406548-5b730bac-3997-11e8-9cf0-fd91f6728bbc.png)
![screenshot from 2018-04-06 12-37-45](https://user-images.githubusercontent.com/16683923/38406550-5ebed2c8-3997-11e8-90be-291e37df4f0d.png)

Environment:
  OS: Linux 4.13
  Node: 8.9.4
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: ^16.2.0 => 16.2.0
  react-native: ^0.54.2 => 0.54.4

## Steps to Reproduce
[here](https://github.com/ishrak-imam/native-navigation-starter) is the repository with reproducible code. After running the application a login screen will appear and initially it will work fine. But When create new account is pressed it navigates to register screen and after coming back to login screen the `KeyboardAvoidingView` doesn't works as expected. The view is pushed up and the view hides at the top of the screen like the screenshots provided.

**Comment by ishrak-imam** [comment]
I have edited the issue with detailed environment information.

**Comment by asparism** [comment]
Also having this issue

**Comment by kimobrian** [comment]
Experienced this issue today:
```

**Comment by kimobrian** [comment]
Experienced this issue today. Here's my environment:
```sh
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 285.18 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 9.11.2 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 26.0.3, 27.0.3, 28.0.1
        API Levels: 22, 24, 26, 28
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1
      react-native: 0.56.0 => 0.56.0
    npmGlobalPackages:
      react-native-cli: 2.0.1
```
