### ISSUE TITLE
[Packager] should use compatible versions of node core modules

### ISSUE THREAD

**Issue by quarterto** [facebook/react-native#1871]
Many npm modules are currently not compatible with React Native because they depend on node's core modules. A good example of such a module is [`through`](https://www.npmjs.com/package/through), which depends on the `stream` module, and has nearly 1500 modules that depend on it. Currently, if a module like `through` is depended on, you get a slightly opaque runtime error such as `Requiring unknown module 'stream'`, with no further information.

Browserify uses [various npm modules](https://github.com/substack/node-browserify/blob/master/lib/builtins.js) in place of node core modules. I guess Webpack must be doing something similar.

Ideally, I'd like to see:

- Packager resolving node modules with a list akin to Browserify's
- "unknown module" errors be promoted to compile-time, with helpful debugging information, possibly including the module hierarchy that led to the unknown module

What do you think?

**Comment by brentvatne** [comment]
Seems reasonable... this might have to be community driven, if you were to submit a PR it would be very helpful to get this moving along further

**Comment by ide** [comment]
Could you define a set of polyfills and require them from your index.js file? Seems simpler and more amenable to evolution to me.

**Comment by quarterto** [comment]
@ide The problem is when some module deep in your dependencies does e.g. `require('stream')`. Packager doesn't know about that module so the entire bundle fails. The app never even gets to index.js, so there's no way to polyfill there (even if I could hook into `require` somehow).

**Comment by quarterto** [comment]
@brentvatne I'm not familiar with Packager's internals, any pointers for where this should go?

**Comment by brentvatne** [comment]
@quarterto - unfortunately I'm very much in the same boat as you

**Comment by mvayngrib** [comment]
+1, would appreciate a pointer for where in packager it would be best to do this. 

I would love for react-native to accept a "fallbacks" mapping, i.e. if some module does require('fs'), and 'fs' can't be resolved, check fallbacks.

Browserify and webpack currently (unfortunately) make the choice for you with core module fallbacks, so if you want to add some that are missing (fs, dgram, net, a few others), or choose different fallbacks for a different environment -- browser vs chromeapp vs react-native, etc. -- there's no convenient way. I'm currently using [react-native-webpack-server](https://github.com/mjohnston/react-native-webpack-server) and a [fork of node-libs-browser](https://github.com/mvayngrib/react-native-node-libs) that adds [fs](https://github.com/tradle/react-native-level-fs), [dgram](https://github.com/tradle/react-native-udp) and others. It works, but it's not terribly convenient. I'd prefer to be able to use react-native's packager.

**Comment by mvayngrib** [comment]
@amasad maybe you're the one to give us a hint? :)

**Comment by amasad** [comment]
hey @mvayngrib. Currently, we only support "script polyfills". Meaning they run before the `require` library. We can potentially have a way to define "core" modules. Support for this needs changes across the resolver and the bundler parts of the packager. Feel free to dig into the packager code (found in packager/react-packager) and try to figure it out. Let me know if you have any specific questions.

Also, FYI, we're moving the packager to it's own repo some time soon, so I'll ping you to move the discussion there.

**Comment by zsszatmari** [comment]
+1

**Comment by jsierles** [comment]
A more detailed discussion here #6253. To keep issues more focused, I'm closing this in favor of discussion there. @amasad @mvayngrib feel free to reopen here or discuss there.

**Comment by aleclarson** [comment]
```
git clone https://github.com/facebook/react-native.git
cd react-native
npm install --save path-browserify

mkdir Libraries/NodeJS
touch Libraries/NodeJS/path.js
```

Set the contents of `Libraries/NodeJS/path.js` to:

```js
/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 *
 * @providesModule path
 */

module.exports = require('../../node_modules/path-browserify');
```

This technique can be applied generically.
But I suppose this should be possible without cloning `react-native`.

Any thoughts?
