### ISSUE TITLE
rnpm-install ERR! Something went wrong while linking. 

### ISSUE THREAD

**Issue by ms853** [facebook/react-native#18719]
Hello Everyone, I tried to link the react-native-fs package to my project and after successfully installing the package, whenever I try to run 'react-native link react-native-fs or react-native link', it does not work.
This is the output I get: 

rnpm-install ERR! Something went wrong while linking. Error: Expected "/* Begin ", "/* End ", "\"", or [A-Za-z0-9_.] but "<" found.

Please is there a way I can solve this issue? I desperately need to resolve this problem as soon as possible. 

![image](https://user-images.githubusercontent.com/22614053/38414907-bb3b2f3e-3987-11e8-9930-193dc7a5de7c.png)

**Comment by kelset** [comment]
I suggest you open this issue in the [library](https://github.com/itinance/react-native-fs) repo.

**Comment by ms853** [comment]
But I am getting this error regardless of the library and I don't know how to approach this problem.
