### ISSUE TITLE
RNTester: Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by TheWattAge** [facebook/react-native#18714]
- <input type="checkbox" default="checked" disabled/> I have reviewed the [documentation](https://facebook.github.io/react-native)
- <input type="checkbox" default="checked" disabled/> I have searched [existing issues](https://github.com/facebook/react-native/issues)
- <input type="checkbox" default="checked" disabled/> I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

I am currently following the Lynda.com React-Native Essential Training course, which has lead me to cloning the RNTester file via the git repository. I have followed the steps outlined in the RNTester documentation to launch the project in Xcode Version 9.

The build continually fails when I attempt to run the example in the simulator and delivers the error:

Undefined symbols for architecture x86_64:
  "YGConfig::YGConfig(int (*)(YGConfig*, YGNode*, YGLogLevel, char const*, __va_list_tag*))", referenced from:
      _YGConfigNew in libReact.a(Yoga.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

## Environment

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.10.1
  Yarn: 1.5.1
  npm: 5.8.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.1 AI-173.4670197

Packages: (wanted => installed)
  react: ^16.3.0-alpha.1 => 16.3.0
  react-native: 0.54.4 => 0.54.4

## Steps to Reproduce
git clone https://github.com/facebook/react-native.git
cd react-native
npm install

Open RNTester/RNTester.xcodeproj in Xcode
Hit the Run button

## Expected Behavior

To compile and run the "RNTester.xcodeproj" file.

## Actual Behavior

Build Fails with Error message:
Undefined symbols for architecture x86_64:
  "YGConfig::YGConfig(int (*)(YGConfig*, YGNode*, YGLogLevel, char const*, __va_list_tag*))", referenced from:
      _YGConfigNew in libReact.a(Yoga.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by hramos** [comment]
Fixed in 95f625e151c7abbb05efcd14404c8aa9583faa83

**Comment by roots-ai** [comment]
How to resolve this?

**Comment by eurobob** [comment]
@hramos This error is occurring on my upgrade from RN 0.54.0 to 0.57.6, the solution in the "fix" is not applicable

**Comment by cihati** [comment]
@eurobob have you been able to fix this? I'm having this issue when I run `react-native run-ios`. I've spent many hours with no luck so far =/ We are on RN 0.57.5.

relevant portion of `Podfile`

```
  platform :ios, '9.0'

  rn_path = '../node_modules/react-native'
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga"

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
```

**Comment by hramos** [comment]
This issue was closed back when the original fix landed. If it's still affecting the latest release, would you mind opening a new issue?

**Comment by cihati** [comment]
@hramos done: https://github.com/facebook/react-native/issues/23218
