### ISSUE TITLE
FlatUIImplementationProvider no longer exists and Nodes' readme is outdated

### ISSUE THREAD

**Issue by kevinresol** [facebook/react-native#18726]
`FlatUIImplementationProvider`  is removed in this commit: https://github.com/facebook/react-native/commit/387a3557ae9e90b3694de5e47f3b8bd62e5f443b#diff-daab33309f905d4a8c90f5c38ec6edf5

Due to that, the Nodes' README is no longer relevant: https://github.com/facebook/react-native/blob/3998650/ReactAndroid/src/main/java/com/facebook/react/flat/README.md#how-to-test

It needs an update.

**Comment by hramos** [comment]
Thanks for noticing this! Do you want to send a PR?

**Comment by koxen** [comment]
is there any reason _why_ it was removed? it looks like a pretty good optimization 😢

**Comment by kevinresol** [comment]
> Do you want to send a PR?

I wished to, if I knew what is happening. But unfortunately I have no idea.

**Comment by kevinresol** [comment]
Dumb bot
