### ISSUE TITLE
Unable to import module from outside react native folder even with a symlink

### ISSUE THREAD

**Issue by Alphapage** [facebook/react-native#18725]
- [ x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [ x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [ x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment
Environment:
  OS: Windows 10
  Node: 8.11.1
  Yarn: Not Found
  npm: 5.8.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.1.0.0 AI-173.4670197

Packages: (wanted => installed)
  react: ^16.3.1 => 16.3.1
  react-native: ^0.55.1 => 0.55.1

## Steps to Reproduce
In App.js, `import something from '../AnotherProject` . 
Execute `react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/`

## Expected Behavior
react native should be able to import the index.js file

## Actual Behavior
Error: unable to find the module

**Comment by vonovak** [comment]
I don't think this is react-native related, this more of a metro bundler issue; and Metro is known to not follow symlinks. As for importing files from a different project, I cannot comment on that.

**Comment by Alphapage** [comment]
I have transfer this issue to metro bundle: https://github.com/facebook/metro/issues/159
