### ISSUE TITLE
[CLI] Using Yeoman for react-native init

### ISSUE THREAD

**Issue by SBoudrias** [facebook/react-native#1873]
Would you be interested in using Yeoman the init command of the react-native-cli?

The advantage would be first a more abstracted code generation framework and second this would allow people to easily compose your base generator and make their own flavor. Also, I see you have currently no unit test for that functionality, adding them would be easy with Yeoman.

If you're interested into this change, I'm ready to work on it and send a PR.

**Comment by brentvatne** [comment]
Thoughts @frantic @amasad?

**Comment by browniefed** [comment]
@brentvatne looks like the packager does use yeoman now. Close

**Comment by ide** [comment]
Thanks @foghina!
