### ISSUE TITLE
KeyboardAvoidingView lacking documentation

### ISSUE THREAD

**Issue by James2516** [facebook/react-native#18738]
- [ x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [ x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [ x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment
Environment:
OS: macOS Sierra 10.12.6
Node: 9.8.0
Yarn: -
npm: 5.6.0
Watchman: 4.7.0
Xcode: Xcode 9.2 Build version 9C40b
Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
react: 16.3.1 => 16.3.1
react-native: 0.55.1 => 0.55.1

## Steps to Reproduce

https://facebook.github.io/react-native/docs/keyboardavoidingview.html
The difference between `height`, `position` and `padding` for the `behavior` prop should be documented.

## Expected Behavior
N/A

## Actual Behavior
N/A

**Comment by James2516** [comment]
still not fixed

**Comment by kelset** [comment]
There is a dedicated repo for documentation and the website, open a PR there: https://github.com/facebook/react-native-website
