### ISSUE TITLE
Fails to compile: RCTFabricUIManagerWrapper.h is included when using Cocoapods [0.55.x regression]

### ISSUE THREAD

**Issue by itchingpixels** [facebook/react-native#18741]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

The file `RCTFabricUIManagerWrapper.h` is included  included when using Cocoapods (the local "React" pod). `RCTFabricUIManagerWrapper.h` does not compile: it throws an error that folly-config.h is not found.

The app builds fine with react-native 0.54.x.

The root cause of the problem is that this specific file is unintentionally included among the compiled files. According to @fkgozali 's comment on https://github.com/facebook/react-native/pull/17764 

## Environment
Environment:
  OS:  macOS High Sierra 10.13.3
  Node:  9.10.1
  Yarn:  1.5.1
  npm:  5.6.0
  Watchman:  4.9.0
  Xcode:  Xcode 9.3 Build version 9E145
  Android Studio:  3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.1 => 0.55.1

## Steps to Reproduce
1. Create a new Xcode project
2. Follow the guide how to integrate react-native into an existing project
3. Run the app

## Expected Behavior
The app builds without an error.

## Actual Behavior
The app does not compile

**Comment by itchingpixels** [comment]
@fkgozali originally CCd @shergin & @hramos, so I'll do that here as well.

**Comment by fkgozali** [comment]
Thanks for the report. I think this was addressed with https://github.com/facebook/react-native/pull/18688 (now in master).

**Comment by fkgozali** [comment]
@hramos: may want to get that fix picked to 0.55 or whatever the latest release is?

**Comment by hramos** [comment]
@fkgozali for sure. @ptomasroos requested this be cherry-picked into 0.55 here: https://github.com/react-native-community/react-native-releases/issues/11#issuecomment-379693797
