### ISSUE TITLE
[iOS] geolocation.watchPosition() method errorCallback function is NOT invoked if user denies location permission

### ISSUE THREAD

**Issue by arleytriana** [facebook/react-native#18744]
- [X] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [X] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [X] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.11.1
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.1 AI-173.4670197

Packages: (wanted => installed)
  react: ^16.3.1 => 16.3.1
  react-native: ^0.55.1 => 0.55.1

## Steps to Reproduce

1. Open the [app](https://snack.expo.io/@arleytriana/navigator.geolocation.watchposition) on iOS
2. Activate the "Don't Allow" button

Notice that the supported `useSignificantChanges` option is set to `true`.

## Expected Behavior

If the user denies location permission, the `errorCallback` function MUST be invoked with code `PERMISSION_DENIED` as documented in the [W3C Geolocation API Specification](https://w3c.github.io/geolocation-api).

## Actual Behavior

If the user denies location permission on iOS, the `errorCallback` function is NOT invoked.
Tested on iPhone 10 - 11.3 (Simulator)

**Comment by wuppious** [comment]
I believe this is a related issue on Android as well. Denying permission on prompt does not call the errorCallback on `getCurrentPosition`. Extending on this, no error/prompt is given, if the user hasn't accepted the use of Google Location Services, which RN geolocation apparently requires to work.
