### ISSUE TITLE
index of getItemLayout return -1 when use initialScrollIndex props on FlatList

### ISSUE THREAD

**Issue by tsaohucn** [facebook/react-native#18743]
## Environment

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.6.1
  Yarn: Not Found
  npm: 4.6.1
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.0 => 16.3.0
  react-native: 0.54.4 => 0.54.4
## Steps to Reproduce
use getItemLayout and initialScrollIndex on the flatList at same time

## Expected Behavior
as same as normal and getItemLayout callback index return always >= 0

## Actual Behavior
getItemLayout callback index return -1

I find this because of the index of array raise error of undefined 
```
  getItemLayout = (data, index) => {
    if (index >= 0) {
      return { length: this.scaleImageHeightArray[index].scaleImageHeight, offset: this.scaleImageHeightArray[index].scaleImageHeightOffset - this.scaleImageHeightArray[0].scaleImageHeightOffset, index }
    } else {
      console.warn(index) // -1
      return { length: 0, offset: 0, index }
    }
  }
```

**Comment by tsaohucn** [comment]
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.6.1
  Yarn: Not Found
  npm: 4.6.1
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.1 => 0.55.1

It's still the same situation

**Comment by pohsiu** [comment]
same issue
