### ISSUE TITLE
Manually installing a release APK, then opening, closing, and re-opening the app causes the root component to be mounted multiple times

### ISSUE THREAD

**Issue by EdwardNickson** [facebook/react-native#18764]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

Manually installing an APK for the first time ( by copying to the device and then installing the APK), then pressing home, and then reopening the app causes a new root component to be mounted while leaving the old root component still mounted in the background.

## Environment
Environment:
  OS: Windows 10
  Node: 8.1.2
  Yarn: 1.5.1
  npm: 5.7.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.1.0.0 AI-173.4670197

Packages: (wanted => installed)
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: ^0.55.1 => 0.55.1 (I've also reproduced the bug on RN 0.50)

## Steps to Reproduce
Uninstall any previous version of the app from your android device (installing over the top will cause the bug to not happen).
Build a signed release APK in Android Studio.
Copy the APK to a device. (This bug won't happen if the app is auto installed when copying it across, so  rename the apk file from *.apk to *.ap to get it onto the device and then rename it back to *.apk on the device)
Open the APK using a file manager and install it. 
Press "Open" when the install is complete (pressing "Done" will cause the bug to not happen).
Press the Android home button once the app has loaded.
Reopen the app from the launcher.

What appears to happen is that it will mount a new root component while leaving the old one mounted in the backgound. Repeatedly opening and closing the app causes new root components to be mounted without unmounting old ones.

The bug can be fixed by pressing the Android menu button and closing the app from the list of open apps, or by force stopping the app. 

The following example highlights the problem:
Run create-react-native-app then replace app.js with. 
```
import React from 'react';
import { StyleSheet, Text, View, findNodeHandle } from 'react-native';

export default class App extends React.Component {

  interval;

  constructor(props) {
    super(props);
    this.state = {nodeHandle: ''};
  }

  consoleOutput = () => {
    console.debug('RemountTest: I should appear every 2 seconds with the same handle. Handle = ' + findNodeHandle(this) );
  }

  componentDidMount() {
    console.debug('RemountTest: App Did Mount');
    this.interval = setInterval(this.consoleOutput, 2000);
    this.setState({nodeHandle: findNodeHandle(this) })
  }

  componentWillUnmount() {
    console.debug('RemountTest: App Will Unmount');
    clearInterval(this.interval);
  }

  render() {
    return (
      <View style={styles.container}>
        <Text>{'Remount Test. Node Handle: ' + this.state.nodeHandle}</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

To see the debug output in Logcat add 
```
android:debuggable="true"
```
to the application tag in AndroidMainfest.xml and add 
```
android {
    lintOptions {
        checkReleaseBuilds false
    }
}
``` 
to app\build.gradle

## Expected Behavior
When the app is closed and reopened, the app state should be saved.
Therefore, after reopening the app, the timer should still get called once every 2 seconds with the same App node handle that was shown before closing it, and the App node handle shown in the render should not change.

## Actual Behavior
A new timer is created every time the app is reopened and each new timer has a different node handle in the debug message. The old timers still remain active. The App node handle displayed in the render also changes every time the app is reopened. 
It appears that a new App component is mounted every time the app reopens, while leaving the old ones still mounted in the background.

The following is a screengrab of Logcat. The first four lines are from when I first opened the app. The node handle for the App component is initially shown in the render as 4. Then I pressed home and reopened the app. On the screen it went from showing "Node Handle: 4" to "Node Handle: 9". It also creates a new timer with "Handle = 9" in the debug message, but the timer with the previous message of "Handle = 4" is still active, so there are two messages every two seconds. 

![capture](https://user-images.githubusercontent.com/26862861/38528150-ad46b264-3ca1-11e8-85dd-d666e686714c.PNG)

Screenshot before reopening the app
![before](https://user-images.githubusercontent.com/26862861/38528013-186c7ed0-3ca1-11e8-916e-3896d6e9f837.png)

Screenshot after reopening the app
![after](https://user-images.githubusercontent.com/26862861/38528016-1c8898b4-3ca1-11e8-92b3-169db6c94544.png)

**Comment by wangluu** [comment]
+1.same problem , version 0.55.3.
when I remove the SplashActivity, use MainActivity(ReactActivity) as the LAUNCHER activity, this only happened once if I open the app from the system install complete page , then click Home button, and then reopen the app from desktop.  (**Manually** installing a **RELEASE** app)  

so maybe  add a SplashActivity can reproduce it easily?I haven't  tried yet.

**Comment by kelset** [comment]
Are you sure this is a React Native related bug and not an Android one? The series of steps you need to make to recreate this conditions seems to tell me that is something related to the Android OS (and prob device) you are testing on.

Could you:
1) test with a different version of Android
2) test with a different device
3) test with a 'fully native' Android test app

And report back?

**Comment by wangluu** [comment]
wow ,I just fixed this issue by set the MainActivity( launcher activity and my ReactActivity) 's launchMode to singleTask in my situation.  
then I did some more test and now I think it maybe a Android Bug or just the behavior !?
 steps I did:
1 .create a simple  android native app the have a Bottom Navigation Activity.
2. "./gradlew assembleDebug",generate an apk and upload to the mobile's sdcard.
3.install it and open it from the install success page. 
4. change the tab to tab 3 (as a indicator).
5. click Home button  and open it from desktop.

you will see the tab is at first position(default),then click Back button, you will see the tab  is at the  third position(step 4). so it must be that launch from the install success page and desktop started different  TaskStack.
and this also exist when installing via the Play Store too.
