### ISSUE TITLE
React-navigation problems after react-native link

### ISSUE THREAD

**Issue by Ternowy** [facebook/react-native#18779]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

After connecting new fonts by this [method](https://medium.com/react-native-training/react-native-custom-fonts-ccc9aacf9e5e)
Right _after_ **react-native link** i can't run my app
FIXED BY DELETING FROM MainApplication.java some rows
## Environment

Environment:
  OS: Windows 10
  Node: 9.10.1
  Yarn: Not Found
  npm: 5.8.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.0.0.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.1 => 0.55.1

## Steps to Reproduce
I tried to fix this problem with navigation with forums but it's not worked

## Expected Behavior

**AFTER react-native run-android**

MainApplication.java:27: error: cannot find symbol
            new NavigationReactPackage()
                ^
  symbol: class NavigationReactPackage
2 errors
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

## Actual Behavior

I've edited \android\app\src\main\java\com\GoApp\MainApplication.java 

- [ ] **Deleted** form **imort** section **ReactNativeNavigation** 
- [ ] deleted from **getPackages**   new NavigationReactPackage()
- [ ] I was surprised, it working right now

So why it happened with navigation? How work react-native link with navigation

**Comment by kelset** [comment]
By looking at the error it's clear that something in the MainApplication.java is not working correctly,

```
MainApplication.java:27: error: cannot find symbol
new NavigationReactPackage()
```

Probably something failed during the linking and you need to try [do the manual steps](https://wix.github.io/react-native-navigation/#/installation-android).

That said, this is not the correct repo to open this issue into. [This is](https://github.com/wix/react-native-navigation).
