### ISSUE TITLE
[Image] Serious Error on Image Component with HTTPS

### ISSUE THREAD

**Issue by darkrishabh** [facebook/react-native#1877]
I have the navigator setup, and when I go to the next page and mount an image, whose URI is over Https, and then go back to the previous page. I get this error in XCode 6.4

```Jul  6 03:54:35 Rishabhs-MBP demoapp[56623] <Error>: CGContextSetFillColorWithColor: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
Jul  6 03:54:35 Rishabhs-MBP demoapp[56623] <Error>: CGContextGetCompositeOperation: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
Jul  6 03:54:35 Rishabhs-MBP demoapp[56623] <Error>: CGContextSetCompositeOperation: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
Jul  6 03:54:35 Rishabhs-MBP demoapp[56623] <Error>: CGContextFillRects: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
Jul  6 03:54:35 Rishabhs-MBP demoapp[56623] <Error>: CGContextSetCompositeOperation: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.```

My code for the image viewing : 

```

var SearchPage = React.createClass({

    render: function () {
        var me = this;
        var background = 'https://res.cloudinary.com/crunchbase-production/image/upload/v1397184125/2ddb1f4e6962ed4481e97b9cc887a68a.png';

        return (
            <View style={styles.body}>
                <View style={styles.imageBlock}>
                    <Image source={{uri: background}} style={styles.backdrop}>
                        <Text> Hello </Text>
                    </Image>
                </View>

            </View>
        )
    }
});
var styles = StyleSheet.create({
    body: {
        flex: 1,
        flexDirection: "row",
        backgroundColor: '#FFF',
    },

    imageBlock: {
        flex: 1,
        flexDirection: "row",
        justifyContent: "center",

    },
    backdrop: {
        flex: 0.5,
        resizeMode: "stretch"
    },

})

module.exports = SearchPage

```

We go to this page by the navigator call. I will push the project in a git repo soon. If I am unable to debug it in few days.

**Comment by sghiassy** [comment]
Seems similar to https://github.com/facebook/react-native/issues/1534.

Is your issue only reproducible with HTTPS?

**Comment by darkrishabh** [comment]
Yes. I just did 2 times.

**Comment by ide** [comment]
The app shouldn't crash if it gets bad image data. Probably better to render a big red element in its place similar to how unsupported components are treated.

@nicklockwood are you the right person to look into this?

**Comment by darkrishabh** [comment]
@ide The app doesn't crash

**Comment by darkrishabh** [comment]
@sghiassy @nicklockwood  to reproduce, you can just take my code and have it rendered by navigator, not as the first route but a second.

when you move out from this page you will see the error logs.

**Comment by nicklockwood** [comment]
I'll take a look. This error crops up quite a lot, and seems to be harmless at the moment. It's typically caused by trying to draw into a zero-sized context.

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/image-serious-error-on-image-component-with-https
