### ISSUE TITLE
SIGSEGV in production for all instances invoking setReachabilityStatus

### ISSUE THREAD

**Issue by lwansbrough** [facebook/react-native#18776]
- [ x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x ] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x ] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

We're seeing elevated crash reports relating to a member invocation `setReachabilityStatus` on several instance types, resulting in a SIGSEG triggered by `unrecognized selector sent to instance`.

Here's info from a crash report:

<img width="817" alt="screen shot 2018-04-09 at 1 17 34 pm" src="https://user-images.githubusercontent.com/186674/38520735-79cec7ae-3bf8-11e8-8d55-fc4d0187f53a.png">
<img width="1191" alt="screen shot 2018-04-09 at 1 17 40 pm" src="https://user-images.githubusercontent.com/186674/38520736-79f03e0c-3bf8-11e8-8c34-e1e0e5a84055.png">

## Environment
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.4.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.0 => 16.3.0
  react-native: 0.55.0 => 0.55.0

## Steps to Reproduce
1. Open app that uses the `setReachabilityStatus` method in native code somewhere.
2. Go home, then change your network (disable cellular service)
3. Open the app back up
4. The app will crash

## Expected Behavior
No crashes :)

## Actual Behavior
Lots of crashes

**Comment by lwansbrough** [comment]
Looked into this more, the only place `setReachabilityStatus` is invoked is in RCTNetInfo.m -- it's invoked after an unsafe cast here: https://github.com/facebook/react-native/blob/master/Libraries/Network/RCTNetInfo.m#L51

**Comment by lwansbrough** [comment]
I am able to reproduce this issue. Listening for `connectionChange` via NetInfo will lead to this `EXC_BAD_ACCESS` if the network is changed while listening but the reference was released.

The reproduction steps I claim above are correct, except that step one should be:

1. Listen for `connectionChange` via `NetInfo.addEventListener`

Note that the app will not consistently crash, as the reference has to be released, which only happens occasionally. I've found after trying 3-5 times you'll usually hit the exception.

**Comment by lwansbrough** [comment]
Going to loop in @alburdette619 @mmmulani as they authored the (potentially) offending commits.

**Comment by lwansbrough** [comment]
Potential solution could be calling `stopObserver` during deallocation?

**Comment by mmmulani** [comment]
are you able to repro this on master? my understanding is that https://github.com/facebook/react-native/commit/9d45de60accda028d11b715a3407119353a81d2c#diff-82c5d95c19a17c3f2375f0b1e09f6da4 solves this

**Comment by mmmulani** [comment]
oh hmm actually says you're using 0.55 which has my fix 🤔

**Comment by mmmulani** [comment]
stopObserver should already get called during dealloc because of RCTEventEmitter. I'll try reproing on device now

**Comment by lwansbrough** [comment]
@mmmulani Thought this change made it into 0.55.2. I'll try master.

**Comment by lwansbrough** [comment]
FYI I'm using the module like so:

```javascript
function handleConnectionStateChange(state) {
    // do stuff
    NetInfo.removeEventListener('connectionChange', handleConnectionStateChange);
}

NetInfo.getConnectionInfo().then(info => {
    // do stuff
    NetInfo.addEventListener('connectionChange', handleConnectionStateChange);
}).catch((...args) => console.warn("Error: ", args));
```

**Comment by lwansbrough** [comment]
I think I can confirm that this is resolved via the fix that was committed earlier. I've hot-patched React Native for my app and I can no longer reproduce the issue.

**Comment by mmmulani** [comment]
no problem! thanks for the repro steps btw, wasn't actually able to repro it locally so I wasn't 100% sure about the fix 🙈

**Comment by peacechen** [comment]
Will this fix be included in the next 0.55 release?

**Comment by grabbou** [comment]
It's not included as no-one requested a cherry-pick. I'll do it for you. For the future, please send reports over here: https://github.com/react-native-community/react-native-releases/issues/11

**Comment by devey** [comment]
Just to inform; As of `0.55.3` the app crashes if running in `debug` mode and using `NetInfo`.

**Comment by devey** [comment]
@mmmulani sorry for the delay.
I tried with `0.55.4` and works smoothly so it would be great to cheery into `0.55.3`.

Thanks.
