### ISSUE TITLE
ListView doesn't load if I don't scroll

### ISSUE THREAD

**Issue by ozican** [facebook/react-native#18772]
Hello people, I try lots of solutions about this topic but I could'nt resolve.
This is my ListView, please help me!
Same issue: https://github.com/react-navigation/react-navigation/issues/368 
but `removeClippedSubviews={false}` doesn't work!
```
  <ListView
        enableEmptySections
        dataSource={this.dataSource}
        renderRow={(rowData) => this.renderRow(rowData)}
        style={{ backgroundColor: 'blue' }}
        removeClippedSubviews={false}
      />
```
```

  "dependencies": {
    "firebase": "^4.12.1",
    "lodash": "^4.17.5",
    "react": "16.3.0-alpha.1",
    "react-native": "0.55.2",
    "react-native-elements": "^0.19.1",
    "react-native-fcm": "^14.1.3",
    "react-native-fetch-blob": "^0.10.8",
    "react-native-image-crop-picker": "^0.20.1",
    "react-native-image-header-scroll-view": "^0.8.2",
    "react-native-vector-icons": "^4.6.0",
    "react-native-video": "^2.0.0",
    "react-navigation": "^1.5.11",
    "react-redux": "^5.0.7",
    "redux": "^3.7.2",
    "redux-thunk": "^2.2.0"
  },
```

**Comment by ozican** [comment]
sir I am sorry my english is not good but I am sure this is a bug because I figure it....
If some list items are empty, this is happening! Ok? I delete my empty Items...
You can ask, how can you receive empty items?
I receive from my firebase server. Why I create them?
I create empty items because sometimes I need add an item but it have to don't look new!! Do you understand me? Sb? :*

**Comment by anil-kumar-singh** [comment]
Any solution for this issue i am having the same problem.
