### ISSUE TITLE
[Android][Question] DatePicker / TimePicker without dialog

### ISSUE THREAD

**Issue by sidferreira** [facebook/react-native#18783]
- [X] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [X] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [X] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

Hi!
I'm making this issue for a single reason: `I really would like to have access to DatePicker and TimePicker without using dialog.`

But before I start developing it, I would like to know from the team if they are open to this change, or if there are strong reasons to avoid this change, which would allow renaming `DatePickerIOS` to `DatePicker` and `DatePickerAndroid` to `DatePickerDialogAndroid`.

Yes, I do plan to first make it into a module, but the decision above may change priority, tests, etc.

Thanks in advance

## Environment
```
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.9.4
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.1 AI-173.4697961

Packages: (wanted => installed)
  react: ^16.3.0-alpha.1 => 16.3.0-alpha.2
  react-native: 0.54.2 => 0.54.2
```

## Steps to Reproduce

None for now, as it's much more a question

## Expected Behavior

An input for a team member in order to discuss/think/plan the feature

## Actual Behavior

Waiting for reply, but really happy with the team's work

ps: I just wanted to avoid the No Template label.

**Comment by kelset** [comment]
(ignore the bot, it's not really good in handling these kind of issues)

You should probably cc in the people who committed into those files. Or, if you need this implementation for your team, do them anyway in a fork and eventually PR them (ideally as separate PRs, one for `DatePickerIOS` and the other for `DatePickerAndroid`). It's usually easier to discuss these things with a PR with code,

**Comment by sidferreira** [comment]
@kelset So your suggestion is basically: Do it anyway, create the PR and discuss it later? hahaha
Will check the other devs and tag them indeed. It's a next week thing so I have some time...

**Comment by sidferreira** [comment]
@mkonicek @AaaChiuuu @pandiaraj44 @BurntBrunch @bolinfest @jkeljo @ttsugriy @sophiebits

**Comment by sidferreira** [comment]
FYI: Android-wise, it's basically this code I'll implement (and some API version checks to avoid errors)

```
DatePicker datePicker = new DatePicker(this.getBaseContext(), null, R.style.DatePickerSpinner);
        datePicker.setCalendarViewShown(false);
```

```
    <style name="DatePickerSpinner">
        <!-- Customize your theme here. -->
        <item name="android:datePickerMode">spinner</item>
    </style>
```

**Comment by sidferreira** [comment]
Note to self: #12384 #10932

**Comment by kelset** [comment]
> Do it anyway, create the PR and discuss it later? 

I mean, if you need it, and you need it quickly, that's surely the fastest approach.

**Comment by sidferreira** [comment]
@kelset Not exactly needing it... but really want to have an Android version to DatePickerIOS's component

**Comment by hramos** [comment]
It looks like this is an enhancement request rather than a bug report, so I will go ahead and close it. There's some related discussion going on at https://github.com/react-native-community/discussions-and-proposals/pull/85, which didn't exist when this issue was originally created. Can you continue any discussion over there?
