### ISSUE TITLE
Running react-native link cause error

### ISSUE THREAD

**Issue by mannok** [facebook/react-native#18781]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [ ] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment
Environment:
  OS: Windows 10
  Node: 8.11.1
  Yarn: Not Found
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.1.0.0 AI-173.4670197

Packages: (wanted => installed)
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: 0.54.0 => 0.54.0

## Steps to Reproduce
(As I am using create-react-native-app, I cannot use the latest version of RN (0.55))
1. Run: $ npm install react-native-vector-icons --save
2. Run: $ react-native link

## Expected Behavior
Platform bridged library should be linked successfully.

## Actual Behavior
Error occured as follow:

PS C:\Projects\proj> react-native link
Scanning folders for symlinks in C:\Projects\proj\node_modules (81ms)
rnpm-install info Linking assets to ios project
rnpm-install ERR! Something went wrong while linking. Error: Cannot read property 'pbxprojPath' of null
Please file an issue here: https://github.com/facebook/react-native/issues

Cannot read property 'pbxprojPath' of null

**Comment by ccwukong** [comment]
+1
After upgraded RN to 0.55.2 and run react-native link, the error persists.

**Comment by LeonFedotov** [comment]
i'm having the same issue trying to link in external fonts...

**Comment by eeu479** [comment]
Getting the same issue when trying to link fonts.

```
Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.1.4
  Yarn: 1.0.2
  npm: 5.0.3
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.1 AI-173.4697961

Packages: (wanted => installed)
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: 0.54.0 => 0.54.0
```

**Comment by ZeeStorm** [comment]
Received this same error in both 0.54 and 0.55.2 (just upgraded) when trying to `react-native link` after npm installing `native-base`

**Comment by ZeeStorm** [comment]
I somehow managed to make the error go away by downgrading back to 0.54.2, `watchman watch-del-all`, deleting all node modules, clearing cache, `npm i`.. no other modules (or versions) were changed.

**Comment by ccwukong** [comment]
As a matter of fact, this only occurred when I used **create-react-native-app** to create a new RN project, and things are totally ok when I used **react-native init ProjectName**

**Comment by LeonFedotov** [comment]
Im guessing the font linking operation is looking for an xcode project to link them but since i used create-react-native-app and it uses expo instead and there is no xcode project directly in the project... in any case iv'e leaned that i can use Expo's api to include fonts instead.

**Comment by CaptainYouz** [comment]
Same behavior here with react-native 0.55.3

**Comment by shivaprakashpokala** [comment]
same case with react-native: 0.55.4 after "yarn add react-navigation native-base" and "react-native link"

**Comment by shivaprakashpokala** [comment]
@ZeeStorm Hi, Can you please provide detailed steps
"I somehow managed to make the error go away by downgrading back to 0.54.2, watchman watch-del-all, deleting all node modules, clearing cache, npm i."

**Comment by ZeeStorm** [comment]
@shivaprakashpokala I've since ejected and no longer face any issues. Unfortunately, I don't remember the process I used to get around the errors outside of removing custom fonts.

**Comment by luoshuisheng** [comment]
how to resolve this problem,

**Comment by bySegunMoses** [comment]
Good Day, I'm using Exp not react-native init, please is there solution for me??

**Comment by deathnopool** [comment]
same problem with 0.57.1. Any solution?

**Comment by BCT-Otis** [comment]
same problem with 0.57.4

**Comment by michaelroevievictoria** [comment]
Any update ?

**Comment by hramos** [comment]
The command line tools have their own repository and issue tracker over at https://github.com/react-native-community/react-native-cli.

**Comment by methodbox** [comment]
So you left this open for 9 months with no response and then just closed it saying, "wrong repo"?

Kind of a dick move.
