### ISSUE TITLE
`allowFontScaling={false}` on TextInput have no effect on Android

### ISSUE THREAD

**Issue by idrakimuhamad** [facebook/react-native#18786]
I'm actually opening this in reference to #17898 which was closed.

I'm using React native 0.54.4 and this still happening. If you refer to the #17898 snack example, this still happened. On iOS, if the system font size setting was changed to small or bigger size, it doesn't have any effect on `TextInput` with `allowFontScaling` set to `false` but not the case with Android.

I've tested this in Android Simulator running android 8.1.0 on Nexus 6. 

For example, if I set the `fontSize` to the value of 16, it seems to be scale down. I can work around this by using the `PixelRatio.getFontScale()` divided by the actual value I wanted.

Below are the image of the issue, the font size set to 16.

<img width="353" alt="screen shot 2018-04-10 at 6 46 10 pm" src="https://user-images.githubusercontent.com/1400323/38552735-bc40561e-3cef-11e8-9a8e-fdb2b9748877.png">

_With font size set to default_

<img width="347" alt="screen shot 2018-04-10 at 6 48 02 pm" src="https://user-images.githubusercontent.com/1400323/38552758-cb02d550-3cef-11e8-9d63-55fcea2db236.png">

_With font size set to smallest_

**Comment by idrakimuhamad** [comment]
Just to add, upgrading to 0.55.2 this still exists.

I'll try to add some repro snack later

**Comment by iamdurui** [comment]
Just to add, upgrading to 0.55.3 this still exists.

I'll try to add some repro snack later

**Comment by iamdurui** [comment]
please re-open this issue

**Comment by hramos** [comment]
I suggest you open a new issue, with all relevant details in the body of the issue. Thanks!

**Comment by NelGarbuzova** [comment]
Guys, I faced with the same problem. I created this lib for resolving this issue in my project. Maybe, it will help you: https://github.com/NelGarbuzova/react-native-stylized-placeholder

**Comment by anirudha-ani** [comment]
For placeholder fontSize change issue @NelGarbuzova 's solution works. To fix font changing while inputting text the workaround is to - 

1. import PixelRatio from react-native 
2. In TextInput style set your fontSize to {intendedFontSize / PixelRatio.getFontScale()}

It will fix your fontSize and won't change because of system settings for both android and iOS. For this workaround don't set allowFontScaling to false.
