### ISSUE TITLE
[Android] textAlignVertical doesn't work on nested text

### ISSUE THREAD

**Issue by megantracy93** [facebook/react-native#18790]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

textAlignVertical works fine when set on the top-most Text component.  However, if you have any nested texts (a common use case), you can not override the alignVertical in the child Text component.

## Environment

  OS: macOS Sierra 10.12.6
  Node: 9.3.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 2.3.3

Packages: (wanted => installed)
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: 0.55.0 => 0.55.0

## Steps to Reproduce
1. Use this [expo app](https://snack.expo.io/@meganltracy/text-test) OR create a nested Text component with the same height as its parent & give it a textAlignVertical

## Expected Behavior
The child Text's textAlignVertical should be honored.

## Actual Behavior
The child Text's textAlignVertical is NOT honored. See screenshots below for two different cases:

textAlignVertical on parent Text | textAlignVertical on child Text
------------------------------- | ------------------------------
<img width="300" alt="screen shot 2018-04-10 at 12 45 05 pm" src="https://user-images.githubusercontent.com/13631097/38571154-baab4912-3cbd-11e8-9024-0f6ab4e90a74.png"> | <img width="300" alt="screen shot 2018-04-10 at 12 44 47 pm" src="https://user-images.githubusercontent.com/13631097/38571156-bc3089be-3cbd-11e8-8c80-1653602d7afa.png">

**Comment by n-kumari** [comment]
This issue still exists in React Native 0.55.2

**Comment by soyanakagawa** [comment]
Version 0.56.0

Parent Component have high priority than Nested Text.
So Child component's Text style props is ignored. 

I think it should reverse. Child component should have more high priority than parent.

**Comment by hoda-oz** [comment]
@megantracy93 
Even if Text components are nested in other Text components,
they are merged into a single TextView of Android
So you cannot manipulate text position in nested Text components. 

In this case, you can manipulate vertical position  by `lineHeight` property.

**Comment by burkeshartsis** [comment]
Still a meaningful issue. Please fix 😘

**Comment by megantracy93** [comment]
@hoda-oz lineHeight is not the correct property for my use case as I have a multi-line string that should be center-aligned. Using lineHeight on a multi-line string results in each line having that height, rather than the combination of all the lines.

**Comment by thekevinbrown** [comment]
A coping strategy for anyone that finds this is wrapping the `<Text>` with another `<View>`, e.g.

```
<View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
    <Text>Whatever here</Text>
</View>
```

In this case even multiline text is correctly centred in the view. It'd certainly be easier if `textAlignVertical` worked, but this might help you in the meantime.
