### ISSUE TITLE
XMLHttpRequest POST unrecognized selector exception

### ISSUE THREAD

**Issue by agentS** [facebook/react-native#1879]
I'm currently writing an application requiring JSON data to be sent to a web service using HTTP's POST feature. However, when submitting the data using XMLHttpRequest I get a red box and the following error is displayed in Xcode's console:

    [error][tid:com.facebook.React.BridgeMethodQueue][RCTBridge.m:1449] Exception thrown while invoking queryData on target <RCTDataManager: 0x171a8320> with params (
    http,
        {
        data = "{\"MACAddress\":\"00:13:43:0c:20:6e\",\"SoftwareRevision\":\"2885\",\"HardwareRevision\":\"2\",\"WaitingTimeColdStart\":\"30\",\"WaitingTimeWarmStart\":\"10\",\"TimeDelayColdStart\":\"30\",\"TimeDelayWarmStart\":\"30\",\"TemperatureDropA\":\"0\",\"WaitingTimeB\":\"7\",\"WaitingTimeC\":\"4\",\"MotorA\":\"3.0\",\"MotorB\":\"2.0\",\"MotorC\":\"0.5\",\"TemperatureDropBColdStart\":\"9\",\"TemperatureDropBWarmStart\":\"5\",\"ColdBurnOffDetectionTime\":\"60\",\"ColdBurnOffDetectionTemperature\":\"3\",\"WarmBurnOffDetectionTime\":\"180\",\"WarmBurnOffDetectionTemperature\":\"25\",\"DoorOpenTime\":\"20\",\"MotorCurrentLimit\":\"600\",\"ThermalElementRMin\":\"2.0\",\"ThermalElementRMax\":\"30.0\",\"ThermalElementRCurrent\":\"65535000.0\",\"CyclesOfOperation\":\"14\",\"BatteryVoltage\":\"2.9065\",\"MaximumBoardTemperature\":\"34.556\",\"MaximumFireRoomTemperature\":\"20.0\",\"RecordDate\":\"2015-07-06T13:05:22.758Z\"}";
        headers =         {
            connection = close;
            "content-length" = 804;
            "content-type" = "application/json";
        };
        method = 1;
        url = "https://webservice.example.com:4443/records/00:13:43:0c:20:6e";
    },
    159
	): -[__NSCFNumber length]: unrecognized selector sent to instance 0x171aaa40

I have used the following source code for creating and submitting the HTTP request:

	var httpOperator = new XMLHttpRequest();
				
	httpOperator.onreadystatechange = function()
	{
		if (httpOperator.readyState !== XMLHttpRequest.DONE)
		{
			return;
		}
		
		if (httpOperator.status === 200)
		{
			onFullfilled();
		}
		else
		{
			onRejected(httpOperator.statusText);
		}
	};
	
	httpOperator.open(this.HTTPOperationType, this.URL, true);
	
	httpOperator.setRequestHeader("Content-type", "application/json");
	httpOperator.setRequestHeader("Content-length", this.DataToTransmit.length);
	httpOperator.setRequestHeader("Connection", "close");
	
	httpOperator.send(this.DataToTransmit);

**Comment by grabbou** [comment]
Can you please wrap your code in snippets for readability sake? (tripe `) :)

**Comment by agentS** [comment]
Sorry, copy&paste error.

**Comment by nicklockwood** [comment]
I think the issue is that contentLength needs to be a string, so "804", not 804.

**Comment by agentS** [comment]
Thanks a lot. That worked. I'm closing the issue.
