### ISSUE TITLE
Cannot prevent ViewPagerAndroid from being the responder when using PanResponder on its Parent

### ISSUE THREAD

**Issue by dopey2** [facebook/react-native#18808]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [ ] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

Hello !! I use  PanResponder for my drawer. In some case I want to prevent children from becoming the responder but it doesn't work if children is ViewPagerAndroid. Here is what i tried

```
onStartShouldSetPanResponderCapture: (evt, gestureState) => true, // not working
onMoveShouldSetPanResponderCapture(evt , gestureState) => true, // not working
onShouldBlockNativeResponder(evt , gestureState) => true,  // not working
onPanResponderTerminationRequest(evt , gestureState) => true , // never called

```

 

## Environment

Environment:
  OS: Windows 10
  Node: 6.11.3
  Yarn: 0.23.2
  npm: 4.4.4
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  2.3.0.0 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: 0.48.3 => 0.48.3

## Expected Behavior

Should prevent ViewPagerAndroid from being scrollable when returning **true** from **onStartShouldSetPanResponderCapture** 
**onMoveShouldSetPanResponderCapture**
**onShouldBlockNativeResponder**

## Actual Behavior
ViewPagerAndroid is scrollable when i return true from these 3 functions above

**Comment by mjmasn** [comment]
@react-native-bot I can reproduce this issue on the latest release.

```
Environment:
  OS: Linux 4.13
  Node: 8.9.4
  Yarn: 1.6.0
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: ^16.3.0 => 16.3.1
  react-native: ^0.55.2 => 0.55.2
```

**Comment by mjmasn** [comment]
@Dani93380 in case you're looking for a workaround... We have a View + PanResponder containing ViewPagerAndroid which contains multiple SectionLists. Setting `scrollEnabled={false}` on both the ViewPagerAndroid and SectionLists seems to work. Replace 'false' with some state that determines if you should be allowing the top level pan responder to take over.

**Comment by Dani93380** [comment]
@mjmasn Thanks! I'll try that

**Comment by mike-marcacci** [comment]
This is true on iOS as well, and is detailed in #11206 which became stale and got locked.

Can we get a comment from the RN team here just confirming whether you consider this is a bug or not? If not, I'd be happy to submit changes to the docs so we don't expect this to work.
