### ISSUE TITLE
Changing contents of an item in "FlatList" while using "onViewableItemsChanged"

### ISSUE THREAD

**Issue by asadallahi** [facebook/react-native#18804]
I was trying to **`change`** some contents inside an item of **`FlatList`** (like title text of a list) while using **`onViewableItemsChanged`** for viewable items it gives me error:
```
ExceptionsManager.js:65 Invariant Violation: Changing onViewableItemsChanged on the fly is not supported
```
## Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.9.4
  Yarn: 1.5.1
  npm: 5.8.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: 0.54.0 => 0.54.0
## Steps to Reproduce

I used this code for my FlatList:
```
handleViewableItemsChanged(info) {
        if (info.length) {
            info.map(async (item) => {
                let response = await ajax.timeline_item_update(item.item);
                 this.setState({updated_item: response});
            });
        }
    }
render() {
        const {timeline} = this.state;
        return (
            <View style={styles.container}>
                <FlatList
                    key="data_flatlist"
                    extraData={this.state}
                    data={timeline}
                    renderItem={({item}) => this.renderTimelineList(item)}
                    viewabilityConfig={this.viewabilityConfig}
                    onViewableItemsChanged={({viewableItems}) => this.handleViewableItemsChanged(viewableItems)}
                />
            </View>
        );

    };
```
## Expected Behavior

Changing the state for updating the list item
## Actual Behavior

but I got: **invariant Violation: Changing onViewableItemsChanged on the fly is not supported**

**Comment by kelset** [comment]
As the error states, what you are trying to do **is not supported**.
