### ISSUE TITLE
SafeAreaView - option to choose only top or bottom spacing

### ISSUE THREAD

**Issue by pie6k** [facebook/react-native#18825]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

```
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.4.0
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.1 AI-173.4670197

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.2 => 0.52.2
```

I need a view that respect top safe area (including iPhone X), but will stretch all the way down to the bottom. 

Right now, `SafeAreaView` doesn't have any customisation options.

Is it possible to ignore bottom spacing using it?

**Comment by MayeuldP** [comment]
Yeah, any suggestions ? Same problem here !

**Comment by pie6k** [comment]
@MayeuldP works great!

Also, you might use https://github.com/react-community/react-native-safe-area-view - that is extracted from `react-navigation` if you don't need entire `react-navigation`

**Comment by vjsingh** [comment]
Re-opened this issue here: https://github.com/facebook/react-native/issues/23279
