### ISSUE TITLE
Textinput onChange/onChangeText are not triggered on Android if the underlying text does not change

### ISSUE THREAD

**Issue by Jyrno42** [facebook/react-native#18822]
- [*] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [*] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [*] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

On android onChange/onChangeText are not triggered if the underlying text does not change. On IOS however the callbacks are always called.

## Environment

Environment:
  OS: Linux 4.13
  Node: 8.9.4
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: ^16.3.1 => 16.3.1
  react-native: latest => 0.55.2

## Steps to Reproduce

Repro here: https://snack.expo.io/@jyrno42/textinput-onchange-onchangetext-issue

Test it by:

- Enter 1 into both inputs

## Expected Behavior

- Observe the eventLog, it should contain 2 items:
  - onChange: 1
  - onChangeText: 1

## Actual Behavior

- On android the events are not triggered

**Comment by Jyrno42** [comment]
Added missing env @react-native-bot

**Comment by egemon** [comment]
@react-native-bot status? Do we need to make some noise asking to fix this?

**Comment by lunatolun** [comment]
We can reproduce this on multiple android devices. RN v0.56.0

**Comment by acrosson** [comment]
@Jyrno42 Any solution? I'm experience this

**Comment by Jyrno42** [comment]
not stale
