### ISSUE TITLE
AppState change doesn't fire on launch on iOS

### ISSUE THREAD

**Issue by esprehn** [facebook/react-native#18836]
- [ ✔️] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [ ✔️] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [ ✔️] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

AppState's change event doesn't fire on first launch on iOS, but does fire on Android. The currentState does change however because the RCTAppState.getCurrentAppState call eventually returns with the active state.

## Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.9.4
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.54.3 => 0.54.3

## Steps to Reproduce

```js
AppState.addEventListener('change', () => console.log('changed', AppState.currentState));
console.log('start state', AppState.currentState);
setInterval(() => {
    console.log('current state', AppState.current);
});
```

This prints:

```
start state unknown
current state unknown
current state active
current state active
current state active
...
```

## Expected Behavior
The change handler should fire since the currentState does change from unknown to active.

## Actual Behavior
change handler never fires.

To fix either:

1) The RCTAppState.getCurrentAppState callback needs to compare currentState to appStateData.app_state and manually fire the event
2) RCTAppState.getCurrentAppState should be removed and native side should always fire one event at startup to initialize the state, then you don't need this separate init step either.

I'm not sure how to do (2) since it means dispatching an event always on startup, not sure where you'd put that code? (1) is easy enough change RCTAppState.getCurrentAppState to not take a callback at all and just dispatch an event instead.

```objc
RCT_EXPORT_METHOD(getCurrentAppState:(RCTResponseSenderBlock)callback
                  error:(__unused RCTResponseSenderBlock)error)
{
  callback(@[@{@"app_state": RCTCurrentAppBackgroundState()}]);
}
```

becomes

```objc
    [self sendEventWithName:@"appStateDidChange"
                       body:@{@"app_state": RCTCurrentAppBackgroundState()}];
```

**Comment by markusekblad** [comment]
I'm having a similar issue on RN55.2 but only in release builds... which took some time to debug.

**Comment by esprehn** [comment]
Yes this still reproduces. I'm still waiting for a review on the merge request. :/

**Comment by yung93** [comment]
It seems only happening on > iOS11 and in release mode.

**Comment by kahoowkh** [comment]
Same with @yung93. Got the issue on iOS 11 release mode only.

**Comment by spedy** [comment]
not working for us on debug either

**Comment by akiradeveloper** [comment]
reproduced in 0.46 and so annoying.

**Comment by joelgetaction** [comment]
I'm seeing cases where the app state never transitions to active and stays at `unknown`.  Any ideas?

**Comment by Eyesonly88** [comment]
I also see this issue in RN 55.3. I get appState 'unknown' when it should be 'active'.

**Comment by jhalborg** [comment]
+1, RN 0.55 / Expo SDK 27. Fires correctly in dev environment, but not on production build

**Comment by slootmaekersdirk** [comment]
+1 Ihave the same issue on RN 0.57 (debug mode)

**Comment by elizamaria** [comment]
Any update on the issue? It happens to me on IOS on release mode as well.

**Comment by markunmind** [comment]
This issue still exists on RN 0.59.

**Comment by vitriolix** [comment]
I am seeing this as well with React Native 0.59.4, on iOS 11.4.1
