### ISSUE TITLE
[TextInput] Multiline placeholder position when default font-size is changed

### ISSUE THREAD

**Issue by JonasJonny** [facebook/react-native#1883]
I changed TextInput ``multiline={true}`` default font to `` fontFamily: 'Iowan Old Style',`` and text placeholder is a few pixels below than written text. Text is jumping when I enter first character into TextInput.

The cause is ``_contentInset.top`` in RCTTextView.m.
If anyone wants to use 'Iowan Old Style' and have the same problem you can change the value to ``- 7`` and restart Xcode.

Not a best solution but it works.

**Comment by brentvatne** [comment]
@JonasJonny - could you have a crack at submitting a PR to fix this?

**Comment by JonasJonny** [comment]
I guess there is no easy or elegant way to do that.
I think default font (Helvetica) have different base line than Iowan Old Style and maybe some others.
Then ``- 5`` is fine for some fonts and different value for another.

**Comment by brentvatne** [comment]
@JonasJonny - is the placeholder font different than the input font? If so maybe just making them the same will help?

**Comment by JonasJonny** [comment]
Input and its placeholder have the same font.

The problem is font-size. 
I just find out the same problem is also with default font if I increase font-size (18+).
I changed default (14) to 16 and problem occurred with Iowan Old Style but Helvetica have similar problem for size 18+. To fix it and have bigger text I have to manually change RCTTextView.m ``_contentInset.top``.

It's only multiline specific problem.
(There are more important issues than this one)

I don't know if RNPlay is reliable but you can see the problem here. https://rnplay.org/apps/wI0b_Q

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/textinput-multiline-placeholder-position-when-default-font-size-is-changed

**Comment by RWOverdijk** [comment]
@brentvatne Can this be reopended? Or should I create a new issue? This is a problem in my app and I'm on the latest version of RN.
