### ISSUE TITLE
`Fetch` no longer returns all rows of the same-name response headers after RN Upgrade

### ISSUE THREAD

**Issue by Rah1x** [facebook/react-native#18837]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

`Fetch` is no longer returning all rows of the same-name response headers! This only just happened after recent upgrade. 

## Environment
Environment:
  OS: Windows 10
  Node: 9.2.0
  Yarn: 1.3.2
  npm: 5.8.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.0.0.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: ^0.55.3 => 0.55.3

## Steps to Reproduce
**Server returns the following response**
```
return response()->json(['msg'=>'1'], 200)
->withHeaders(['Content-Type'=>'application/json', 't1'=>[1, 2]]);
```

** react native code **
```
let response = await fetch('http://im-sick-and-tired-of-hunting-react-native-bugs',
{
            credentials: 'include',
            method: 'GET',
            cache: 'no-cache',
            mode: 'cors',
            headers: {'Cache-Control': 'no-cache', 'Accept':'*/*', 'Content-Type':'application/json'},
});
console.log(response.headers.get('t1')); 
```

## Expected Behavior
The test hdr (t1) must have both values but only the 2nd one is received. See the response from `postman`

![image](https://user-images.githubusercontent.com/841857/38720830-0d78ed46-3f3b-11e8-8a9c-59cae3176c13.png)

## Actual Behavior
![image](https://user-images.githubusercontent.com/841857/38720924-6be654b8-3f3b-11e8-9dfa-606d398c4945.png)

**Comment by Rah1x** [comment]
Not to mention like 20 different dependencies are causing `isMounted` warning!! But thats another story

**Comment by Rah1x** [comment]
This btw JUST STARTED!! so dont tell me the code / server etc is wrong.. cause it was working for long while

**Comment by Dani93380** [comment]
Same problem after upgrading from **48.3** to **55.2**

**Comment by Rah1x** [comment]
im this close to giving up on RN (that after wasting 6 months). cause each month i circle in loops and rebuild the same wheel.. either RN or one of the dependencies (such as RN Elements) change the entire system to crap level and ive to spend a week trying to fix it..

**Comment by Rah1x** [comment]
So ive upgraded to latest commit and still same issue:

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: ^0.55.3 => 0.55.3

**Comment by Rah1x** [comment]
my project is now stuck until this is resolved. I cant do any network activity on the app as I dont get the tokens I need for my app.

**Comment by ajaykumar97** [comment]
I have just resolved this problem by converting fetch() response into json using response.json() method, which in-turns, returns a promise which returns the actual response from server using .then().

fetch('https://facebook.github.io/react-native/movies.json')
    .then((response) => response.json())    <----converting response into json
    .then((responseJson) => {         <----handeling promise
      return responseJson.movies;
    })
    .catch((error) => {
      console.error(error);
    });

reference: [https://facebook.github.io/react-native/docs/network.html](https://facebook.github.io/react-native/docs/network.html)

**Comment by Rah1x** [comment]
@ajaykumar97 your problem was with the `body` and not with the `header`. So actually you didnt have a problem on this thread, as the body is always there and retrieved using response.json()

**Comment by Rah1x** [comment]
Sooo... Dear Bot! where is the solution?!

**Comment by Rah1x** [comment]
Awesome man @ciaranw thanks for the investigation. I hope someone picks it up and solves it.. As a temporary solution I had to push the CSRF tokens from the api framework into the body instead..

**Comment by ciaranw** [comment]
I suspect the issue was introduced in commit 7891805 but i'm not an expert on android or C++ so I can't be sure!

**Comment by kelvinlawson** [comment]
I'm seeing the same thing happening since upgrading from RN 0.52 to 0.54.

Headers being returned by some servers we use have the same fields spread across multiple lines. Since 0.54 it is not possible to talk to these devices any more using RN on Android! RN on iOS is fine.

**Comment by patricksmith** [comment]
We were affected by this issue after upgrading our Android app from RN 0.53.3 to RN 0.54.4, and I see that it's still an issue in RN 0.55.4. We're using an API that returns multiple `Link` headers and we're now only receiving one of those headers in our app.

**Comment by patricksmith** [comment]
I found a workaround for this issue, but I'm not sure of any additional implications of it. Inspired by comments on [a `ReadableNativeArray` issue](https://github.com/facebook/react-native/issues/18292), if you add the following lines to `MainApplication.java`, the duplicate headers are properly parsed:

```
ReadableNativeArray.setUseNativeAccessor(true);
ReadableNativeMap.setUseNativeAccessor(true);
```

I created a repo to reproduce the issue using 0.55.4: https://github.com/patricksmith/rn-headers. You can see the workaround in this commit: https://github.com/patricksmith/rn-headers/commit/e666aa814bf36616d73e015bef75654fc315ec10. I can't find any documentation on what `setUseNativeAccessor` is doing, so it may have additional unintended repercussions.

**Comment by Rarapony** [comment]
I've been trying to deal with this issue for a while. The fix above seems to do nothing to fix the issue for me. I still only see an array of a single value in the "set-cookie" header.

**Comment by mtt87** [comment]
Facing the same issue, spent the morning trying to debug why on iOS we had 3 cookies and on Android only 1 cookie and the problem happens when there are more headers with the same name, on Android it takes only the last one ignoring the others.

An easy way to reproduce, using an express server
```js
    app.get('/test', noCache, (req, res) => {
      res.cookie('mattia1', 'hello');
      res.cookie('mattia2', 'world');
      res.sendStatus(200);
    });
```

Then on the app
```js
fetch({
  url: 'http://localhost:3000/test'
}).then(res => {
  console.log(res.headers);
})
```
On Android you get `mattia2=world; Path=/`
On iOS you get `mattia1=hello; Path=/, mattia2=world; Path=/`

**Only if you control the server the workaround is to not send 2 headers of the same type**

In this case with cookies you have to manually set the header with
```js
// doesnt work
// res.cookie('mattia1', 'hello');
// res.cookie('mattia2', 'world');
// works
res.set('Set-Cookie', 'mattia1=hello; Path=/, mattia2=world; Path=/');
```

**Comment by km16** [comment]
For me it surprisingly work on the emulator, but not on a real device. The api's I make use of have cookies. There seems to be a problem in sending these cookies(which is part of the header) from a real device, but somehow works on an emulator.

**Comment by MetalGuardian** [comment]
This is still an issue on RN `v0.57.0-rc.3`

**Comment by kanerogers** [comment]
I am having this issue on `v.0.57`.
