### ISSUE TITLE
Cannot archive a build. Throws error main.jsbundle does not exist

### ISSUE THREAD

**Issue by VanessaChu** [facebook/react-native#18834]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment
"react": "16.0.0-alpha.12"
"react-native": "0.46.4"

## Steps to Reproduce
It successfully builds and debugs on VSCode. Tried to archive a build. But throws an build failure message.

## Expected Behavior
Supposed to create a build on testflight

## Actual Behavior
Throws the error: 
Showing Recent Messages
error: File /Users/vanessachu/Library/Developer/Xcode/DerivedData/Vericare-dghgyltdrgtuoydoutlithrfxyav/Build/Intermediates/ArchiveIntermediates/Vericare/BuildProductsPath/Release-iphoneos/Vericare.app/main.jsbundle does not exist. This must be a bug with

![screen shot 2018-04-12 at 5 11 30 pm](https://user-images.githubusercontent.com/11250498/38710273-54d85874-3e74-11e8-961b-70a2d397c4e3.png)

**Comment by fishstix-airware** [comment]
I'm also getting this issue while archiving.

I'm not on the latest, but more recent version of React Native:

[4mEnvironment:[0m
  OS: macOS High Sierra 10.13.4
  Node: 6.9.5
  Yarn: 1.3.2
  npm: 3.10.10
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 2.3 AI-162.3764568

[4mPackages:[0m (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.51.0 => 0.51.0
