### ISSUE TITLE
Why registerAdditionalPackages be removed at v0.55.0

### ISSUE THREAD

**Issue by ckitterl** [facebook/react-native#18838]
## Environment
```
Environment:
  OS: Linux 4.2
  Node: 8.10.0
  Yarn: 1.2.0
  npm: 5.6.0
  Watchman: 4.1.0
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.2 => 0.55.2

```

## Steps to Reproduce
Start any android application with react-native highter 0.55.0.

## Expected Behavior
Can use the function registerAdditionalPackages with ReactInstanceManager

## Actual Behavior
registerAdditionalPackages is gone.

 ---------------------------------
After upgrade v0.55.0, I found the function of registerAdditionalPackages has removed from ReactInstanceManager! I found out the [commit](https://github.com/facebook/react-native/commit/6b45fb2cb1ca44fa7375bc7696bf90a68a85df3c#diff-dc0f3a09c238b372cb1c27aa5f7dcbce) to look for why it be deleted but got nothing. Now how do I  do to replace  the function with this  version?

**Comment by hpyfei** [comment]
did you find out the reason? I have the same question
