### ISSUE TITLE
Property with 'retain (or strong)' attribute must be of object type

### ISSUE THREAD

**Issue by kyledecot** [facebook/react-native#18853]
When attempting to build my Xcode project I am receiving the following error:

> Property with 'retain (or strong)' attribute must be of object type

https://github.com/facebook/react-native/blob/7500b3ec839ada6d8e1f7a88d30743dfb0ad7e70/React/Base/RCTBridgeModule.h#L109-L114

## Environment

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.11.1
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.50.4 => 0.50.4

## Steps to Reproduce

Install React/React Native Versions Listed Above, initialize cocoapods with `pod init` and Attempt to build your iOS Project.

### Podfile
```
source 'https://github.com/CocoaPods/Specs.git'

# platform :ios, '8.0'

target 'Example' do
  pod 'react-native-drivers-license-barcode-scanner', path: '../../'
  pod 'yoga', path: "../../node_modules/react-native/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: '../../node_modules/react-native', subspecs: [
    'Core',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]

  pod 'DoubleConversion', :podspec => "../../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "../../node_modules/react-native/third-party-podspecs/glog.podspec"
  pod 'Folly', :podspec => "../../node_modules/react-native/third-party-podspecs/Folly.podspec"
end
```

## Expected Behavior

Project should build without error.

## Actual Behavior

Project Fails to Build

**Comment by OceanHorn** [comment]
Same problem with version 0.55.4 .
```
...
- React (0.55.4):
    - React/Core (= 0.55.4)
...
```

**Comment by OceanHorn** [comment]
@kyledecot Which's the build target in your project?
