### ISSUE TITLE
High/medium nsp vulnerabilities for dependency ws and hoek

### ISSUE THREAD

**Issue by CapitanRedBeard** [facebook/react-native#18854]
Similar to vulnerability issues in the past ([here](https://github.com/facebook/react-native/issues/18394) and [here](https://github.com/facebook/react-native/issues/7643)), we have 2 outstanding nsp vulnerabilities.
Running `nsp check` produces the following:
```
(+) 2 vulnerabilities found
┌────────────┬────────────────────────────────────────────────────────────────────┐
│            │ Denial of Service                                                  │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Name       │ ws                                                                 │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ CVSS       │ 7.5 (High)                                                         │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Installed  │ 2.3.1                                                              │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Vulnerable │ <1.1.5 || >=2.0.0 <3.3.1                                           │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Patched    │ >= 1.1.5 <2.0.0 || >=3.3.1                                         │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Path       │ my-app@0.1.0 > react-native@0.55.2 > react-devtools-core@3.1.0     │
│            │ > ws@2.3.1                                                         │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ More Info  │ https://nodesecurity.io/advisories/550                             │
└────────────┴────────────────────────────────────────────────────────────────────┘

┌────────────┬────────────────────────────────────────────────────────────────────┐
│            │ Prototype pollution attack                                         │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Name       │ hoek                                                               │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ CVSS       │ 4 (Medium)                                                         │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Installed  │ 2.16.3                                                             │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Vulnerable │ <= 4.2.0 || >= 5.0.0 < 5.0.3                                       │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Patched    │ > 4.2.0 < 5.0.0 || >= 5.0.3                                        │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Path       │ my-app@0.1.0 > react-native@0.55.2 > metro@0.30.2 >                │
│            │ jest-haste-map@22.4.2 > sane@2.5.0 > fsevents@1.1.3 >              │
│            │ node-pre-gyp@0.6.39 > hawk@3.1.3 > hoek@2.16.3                     │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ More Info  │ https://nodesecurity.io/advisories/566                             │
└────────────┴────────────────────────────────────────────────────────────────────┘
```

## Environment
```
Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.9.4
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.0.0 => 16.2.0
  react-native: ^0.55.0 => 0.55.2
```

## Steps to Reproduce
```
npm install -g nsp
nsp check
```

## Expected Behavior
```
(+) 0 vulnerabilities found
```

## Actual Behavior
```
(+) 2 vulnerabilities found
```
( Details above )

These are getting picked in the whitesource vulnerability audit, resolving these would be a huge confidence booster.

**Comment by Summys** [comment]
Also check, https://snyk.io/test/github/facebook/react-native

**Comment by Rohithzr** [comment]
any way to manually fix it? this is my first time facing such an issue.

**Comment by CapitanRedBeard** [comment]
@Rohithzr Sadly this is something that you sort of just have to deal with when using a framework with 1000+ sub dependencies. 

If its an absolute must that you have to ship a produce without these security vulnerabilities you can always fork `react-native` and see if you can perform the upgrades yourself to prevent using versions of packages with known vulnerabilities. 

I don't recommend this as it will be near impossible to maintain moving forward, so I think the best option is to just sit tight and bump the thread.

**Comment by xlcrr** [comment]
I am getting the same errors 

react-native ^0.55.4 has a dependency of ws@^1.1.0, but I am prompted to run npm audit which returns 

```

┌───────────────┬──────────────────────────────────────────────────────────────┐
│ high          │ Denial of Service                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ ws                                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ react-native                                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ react-native > react-devtools-core > ws                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/550                       │
└───────────────┴──────────────────────────────────────────────────────────────┘

```

./node_modules/react-native/node_modules/ws/package.json "ws@^1.1.0" <- should I update this ??

**Comment by Rohithzr** [comment]
@CapitanRedBeard maybe i can fix and create a pull request. atleast go past the severe ones.

**Comment by byCedric** [comment]
`react-devtools-core`'s `ws` security issue has been patched just now starting from `>=3.2.2` 🎆 Please note that the current `react-devtools-core` is using a hardcoded `3.1.0`, so that should be updated I think. I'll create a PR containing this and the `plist` update to fix all currently known (non-dev) security issues.

**Comment by Oraclesports** [comment]
Any updates on this?

**Comment by byCedric** [comment]
@Oraclesports see the attached PR, https://github.com/facebook/react-native/pull/19373

**Comment by tetreault** [comment]
new to react native, so not really sure what any of the above means as i've never seen it in my normal node projects. I have the exact same output of @byCedric (`ws` high vulnerability and `lodash` as a low vulnerability). For react native novices -- is there anything for us to do here or should i just look the other way in regards to this for now? 

This only popped up after installing `react-navigation` v^2.0.4

**Comment by byCedric** [comment]
Haha, well, these security issues live in React Native itself. So I'm guessing our friendly friends from Facebook are really the only one who can resolve this anytime soon. I guess the only thing anyone can do is contacting Facebook, pinging maintainers from the repository or stalking anyone who can speed up the process. 

When I created an issue in the [official forms](https://discuss.reactjs.org/) they resolved the `react-devtools-core`'s `ws` issue (the cause of these issues here), they resolved the issue over there in about 6 hours. So anyone reading this and thinking "why the hell isn't it merged/fixed already", try flagging this in the forums or any communication channel. Maybe it helps, but for now I would say sit tight.

**Comment by tetreault** [comment]
thanks for the reply! appreciate the info @byCedric :)

**Comment by Shazam14** [comment]
Ok so until now do we still have to flag them? for support?
