### ISSUE TITLE
Android overscroll effect is not displayed in ScrollViews and FlatLists

### ISSUE THREAD

**Issue by mannok** [facebook/react-native#18857]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [ ] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment
Environment:
  OS: macOS Sierra 10.12.6
  Node: 9.11.1
  Yarn: Not Found
  npm: 5.6.0
  Watchman: Not Found
  Xcode: Not Found
  Android Studio: 3.1 AI-173.4697961

Packages: (wanted => installed)
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: https://github.com/expo/react-native/archive/sdk-26.0.0.tar.gz => 0.54.2

## Steps to Reproduce
```
import React from 'react';
import { StyleSheet, Text, View, ScrollView } from 'react-native';

export default class App extends React.Component {
    render() {
        return (
            <ScrollView overScrollMode="always">  // No difference for setting either overScrollMode or not
                <View style={{ height: 800 }}></View>
            </ScrollView>
        );
    }
}
```

## Expected Behavior
When I scroll the view in android, some overscroll effect will be shown.

## Actual Behavior
No any effect even when I scrolled to the start/end of the page

**Comment by lunciwatari** [comment]
(imej jacke ..splash.png)Hlep online games Street wars pvp tampk super mod kile hacker??..Street wars pvp Super mod500 like por link??

**Comment by landandan** [comment]
same problem

**Comment by noidsoup** [comment]
same problem :(

**Comment by ishigamii** [comment]
I am experimenting the same issue using 
`react-native 0.53.0` and also `react-native: 0.54.4 `

**Comment by kddc** [comment]
+1

**Comment by kddc** [comment]
I had a further look on that and noticed, that this overscroll effect was there, but not visible. I had to change the color by adding `<item name="android:colorEdgeEffect">#1C76D6</item>` to the android `styles.xml`. Maybe this solves the issue for you as well?

**Comment by SASoto** [comment]
Has there been any update/change with this? I am experiencing the same problem on react native 0.56.0. Whether I try overScrollMode="always" or overScrollMode={'always'}, the scrollview on my Android project only scrolls to the end of its children components.

**Comment by mjmasn** [comment]
@SASoto overscroll on android doesn't scroll past the end, it just shows 'overscroll indicators', like a kind of stretchy bubble appearing from the edge of the screen. It seems you need to set the colour in `android/app/src/main/res/values/styles.xml` for them to be visible: See @kddc's comment above: `<item name="android:colorEdgeEffect">#1C76D6</item>`  

For example:
```xml
<resources>
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="android:colorEdgeEffect">#1C76D6</item>
    </style>
</resources>

```

**Comment by ishigamii** [comment]
@mjmasn which explains why indeed. But is there a way to let the user (in Android) scroll passed the first / last element of the list like in iOS ?
