### ISSUE TITLE
[CameraRoll] cannot display iCloud/Photo Stream photo

### ISSUE THREAD

**Issue by Fanghao** [facebook/react-native#1885]
I am following the UIExplorer example to display the iCloud/Photo Stream via `<Image>`, but nothing displays at all. However, using ALAssetsLibrary is able to display the image via the url getting from CameraRoll. I believe that means local assets url is correct.

Any help is appreciated!

**Comment by brentvatne** [comment]
Hi there! Please share a minimal code example either via rnplay.org or a Github repo, as per the contribution guidelines! Thanks! :smile:

**Comment by Fanghao** [comment]
Thanks for the reply.

Actually CameraRollExample of UIExplorer cannot display my iCloud/Photo Stream photos although the infos like asset url and timestamp are correct.

**Comment by browniefed** [comment]
@Fanghao anything on this?
@brentvatne @ide close until more info is provided

**Comment by Fanghao** [comment]
OK. I just tried UIExplorer of 0.11.0-rc and it was able to show some of the iCloud images but not all of them. So I guess it is not fully fixed yet.

**Comment by samuelkraft** [comment]
I have the same issue for images stored in iCloud photo library. 
I suspect this might be due to the setting "Optimise iPhone Storage" being enabled, which only keeps low-res thumbnails and not the actual photos on the device unless there is enough space.

CameraRoll.getPhotos only returns a few photos for me - I think those photos are ones that have originals downloaded.

Tested on latest UIExplorer with iCloud Photo library and Optimise iPhone Storage enabled.

@brentvatne can you re-open?

**Comment by samuelkraft** [comment]
Added this to product pains: https://productpains.com/post/react-native/add-support-for-icloud-photo-library-to-cameraroll

**Comment by wootwoot1234** [comment]
Any updates on this?  Has anyone found a work around to show all photos and download any icloud hosted images when selected?

**Comment by wootwoot1234** [comment]
@ide @brentvatne can you re-open?

**Comment by olofd** [comment]
I'm working on a library called [react-native-photos-framework](https://github.com/olofd/react-native-photos-framework) that can access assets from local camera-roll and iCloud using Apples Photos-framework. Its starting to take form and will be able to do most things you can do with Apples native API's. This includes: Loading images from iCloud (Custom RN-Image-Loader), Loading albums and collections from iCloud, Creating Albums, Deleting and saving assets in albums etc. 

I'm also implementing more low-lever features such as change-detection in asset-collections. And caching for large number of assets. Check it out if your interested.

**Comment by wootwoot1234** [comment]
Very cool!  Thanks for sharing!

**Comment by olofd** [comment]
@wootwoot1234 Absolutely! But do remember that I'm working on it right now and have not tested/built everything yet. So wait a week before you depend on it or help me build it 😄 .

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
