### ISSUE TITLE
gradlew assembleRelease issue Cannot find entry file index.js

### ISSUE THREAD

**Issue by piloulac** [facebook/react-native#18861]
## Steps to Reproduce
When trying to build the release version for the android app I execute: 

```
cd android && ./gradlew assembleRelease
```

## Expected Behavior
Normally it should succeed and build the release version.

## Actual Behavior
However, I get this issue:

```
Scanning folders for symlinks in /Users/.... (10ms)
Loading dependency graph, done.

Cannot find entry file index.js in any of the roots: ["....."]

:app:bundleReleaseJsAndAssets FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command 'node'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

```

I'm only getting this issue for the release version... 
I did try everything I found on the internet to fix this issue but I didn't manage to fix it.

**Comment by mehrdaad** [comment]
I'm having the same problem too.

**Comment by mehrdaad** [comment]
@piloulac could you fix it? can you share your solution?
