### ISSUE TITLE
react native error: Must pass all fields to buffer

### ISSUE THREAD

**Issue by yufusong** [facebook/react-native#1887]
I use the order "react-native init ApplicationTest" created project,and run as Xcode,and they told me error"Must pass all fields to buffer - expected 5, saw 3".how to solve this?

**Comment by ilansas** [comment]
+1 I'm getting the same.

**Comment by ilansas** [comment]
I'm getting this too, here is the full stacktrace. Seems to come from RCTWebView (which I don't use in my code) and/or RCTNetworking module. 

    [tid:com.facebook.React.JavaScript] 'Error: `WebView` has no propType for native prop `RCTWebView.shouldInjectAJAXHandler` of native type `BOOL`
    stack: 
    verifyPropTypes        index.ios.bundle:22980
    requireNativeComponent  index.ios.bundle:22814
    <unknown>               index.ios.bundle:36478
    require                 index.ios.bundle:254
    <unknown>               index.ios.bundle:1523
    require                 index.ios.bundle:254
    <unknown>               index.ios.bundle:1438
    require                 index.ios.bundle:254
    require                 index.ios.bundle:200
    <unknown>               index.ios.bundle:48928
    URL: http://10.0.2.10:8081/index.ios.bundle
    line: 22983
    message: `WebView` has no propType for native prop `RCTWebView.shouldInjectAJAXHandler` of native type `BOOL`'
    2015-07-07 14:50:59.807 [warn][tid:com.facebook.React.JavaScript] 'Unable to load source map: RCTNetworking module is not available'
    2015-07-07 14:50:59.809 [error][tid:com.facebook.React.JavaScript][RCTBridge.m:1351] Must pass all fields to buffer - expected 5, saw 3

**Comment by nicklockwood** [comment]
This is caused by having a stale copy of the javascript code on your machine. See https://github.com/facebook/react-native/issues/1606

**Comment by ilansas** [comment]
Sorry I'm not sure I'm following you... Do you mean a stale copy of React-Native or a stale copy of my actual code (like using some concepts that are no longer supported in React-Native API) ?

**Comment by nicklockwood** [comment]
You have an old copy of the React Native javascript code cached on your machine that conflicts with the latest native code. There are instructions in the comments in the issue I linked to for how to clear the cache.

**Comment by grabbou** [comment]
Unfortunately, doesn't work for me. I am having the @ilansas error being thrown straigh away when I run app with --reset-cache. It looks like a bug as these checks shouldn't throw during runtime for core packages? I have only one react-native 0.8 version installed.

**Comment by grabbou** [comment]
Unfortunately, this doesn't work for me. Still getting that issue about `shouldInjectAJAXHandler` and I only have one react-native installed (0.8). The issue occurs when I click `login with facebook button`  - app redirects me to the Safari. When I come back, that red box appears straight away. Tried to debug `react-native-facebook-login` but they are not referring to WebView at all.

**Comment by grabbou** [comment]
BTW, this issue will happen also when you have two copies of your app installed on the device and you use e.g. `facebook-login` that redirects back to your app. In my case, the wrong app was being opened and (despite the fact debugging worked flawlessly) the wrong (older) RCTWebView was used throwing the error about AJAX handler.

**Comment by kothavishal** [comment]
I am facing the same error while loading RCTWebView on Android app. I tried to reset the cache and that did not help. 

'WebView' has no proptype for native prop RCTWebView.domStorageEnabledAndroid of native type 'boolean'
verifyPropTypes
verifyPropTypes.js:53

requireNativeComponent
requireNativeComponent.js:90
