### ISSUE TITLE
您好 我把flastlist替换成这个后 调用 scrollToIndex时报错 undefined is not a function  

### ISSUE THREAD

**Issue by gaokaikai** [facebook/react-native#18873]
TypeError: undefined is not a function (evaluating '_this._flatList.scrollToIndex')

This error is located at:
    in Main7 (at SceneView.js:17)
    in SceneView (at CardStack.js:455)
    in RCTView (at View.js:71)
    in View (at CardStack.js:454)
    in RCTView (at View.js:71)
    in View (at CardStack.js:453)
    in RCTView (at View.js:71)
    in View (at createAnimatedComponent.js:147)
    in AnimatedComponent (at Card.js:12)
    in Card (at PointerEventsContainer.js:39)
    in Container (at CardStack.js:498)
    in RCTView (at View.js:71)
    in View (at CardStack.js:414)
    in RCTView (at View.js:71)
    in View (at CardStack.js:413)
    in CardStack (at CardStackTransitioner.js:67)
    in RCTView (at View.js:71)
    in View (at Transitioner.js:142)
    in Transitioner (at CardStackTransitioner.js:19)
    in CardStackTransitioner (at StackNavigator.js:41)
    in Unknown (at createNavigator.js:13)
    in Navigator (at createNavigationContainer.js:226)
    in NavigationContainer (at renderApplication.js:35)
    in RCTView (at View.js:71)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:71)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:34)
_scrollToIndex
    D:\workspace\ThirdApp\src\js\Main7.js:199:37
<unknown>
    D:\workspace\ThirdApp\src\js\Main7.js:178:20
commitCallbacks
    D:\workspace\ThirdApp\node_modules\react-native\Libraries\Renderer\ReactNativeRenderer-dev.js:5558:19
commitLifeCycles
    D:\workspace\ThirdApp\node_modules\react-native\Libraries\Renderer\ReactNativeRenderer-dev.js:8993:26
commitAllLifeCycles
    D:\workspace\ThirdApp\node_modules\react-native\Libraries\Renderer\ReactNativeRenderer-dev.js:10214:25
_invokeGuardedCallback
    D:\workspace\ThirdApp\node_modules\react-native\Libraries\Renderer\ReactNativeRenderer-dev.js:134:15
invokeGuardedCallback
    D:\workspace\ThirdApp\node_modules\react-native\Libraries\Renderer\ReactNativeRenderer-dev.js:67:32
commitRoot
    D:\workspace\ThirdApp\node_modules\react-native\Libraries\Renderer\ReactNativeRenderer-dev.js:10327:32
completeRoot
    D:\workspace\ThirdApp\node_modules\react-native\Libraries\Renderer\ReactNativeRenderer-dev.js:11502:46
performWorkOnRoot
    D:\workspace\ThirdApp\node_modules\react-native\Libraries\Renderer\ReactNativeRenderer-dev.js:11452:23
performWork
    D:\workspace\ThirdApp\node_modules\react-native\Libraries\Renderer\ReactNativeRenderer-dev.js:11364:8
batchedUpdates
    D:\workspace\ThirdApp\node_modules\react-native\Libraries\Renderer\ReactNativeRenderer-dev.js:11547:20
batchedUpdates
    D:\workspace\ThirdApp\node_modules\react-native\Libraries\Renderer\ReactNativeRenderer-dev.js:2517:31
_receiveRootNodeIDEvent
    D:\workspace\ThirdApp\node_modules\react-native\Libraries\Renderer\ReactNativeRenderer-dev.js:2670:17
receiveEvent
    D:\workspace\ThirdApp\node_modules\react-native\Libraries\Renderer\ReactNativeRenderer-dev.js:2685:26
__callFunction
    D:\workspace\ThirdApp\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:353:47
<unknown>
    D:\workspace\ThirdApp\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:118:26
__guardSafe
    D:\workspace\ThirdApp\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:316:6
callFunctionReturnFlushedQueue
    D:\workspace\ThirdApp\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:117:17

**Comment by Lxxyx** [comment]
Please show your code.

**Comment by gaokaikai** [comment]
import React,{Component} from 'react';
import {
    View,
    Text,
    StyleSheet,
    TextInput,
    Button,
    Dimensions,
    Image,
    FlatList,
    Touchable,
    PanResponder,
    AsyncStorage, UIManager, findNodeHandle
} from 'react-native';
import Toast, {DURATION} from 'react-native-easy-toast';
import {OptimizedFlatList} from 'react-native-optimized-flatlist'
import PersonalVideo from './PersonalVideo';
import Config from './Config';
const url = Config.url;
const {height, width} = Dimensions.get('window');
const videoHeight = height;
console.log(videoHeight);
const styles =StyleSheet.create({
    content:{
        width:width*0.9,
        marginLeft:'auto',
        marginRight:'auto',
        marginTop:width*0.05,
    },
    title:{
        flex:1,
        textAlign:'center',
        fontSize:16,
        fontWeight:'bold',
        color:'#fff'
    },
    item: {
        width:width,
        height: videoHeight,
    },
})
export default class Main7 extends Component{
    constructor(props){
        super(props);
        this.state={
            videos:[],
            starts:0,
            nums:5,
            refreshing:false,
            index:0,
            starty:0,
            endy:0,
            disable:false,

        }
        let sid = AsyncStorage.getItem('sid');
        if(!sid){
            const { navigate } = this.props.navigation;
            setTimeout(()=>{
                navigate('Login', { name: 'Login'});
            },500)
        }
    }
    static navigationOptions = ({navigation}) => ({
        header:null,
        headerLeft:(<Text></Text>),
        headerRight:(<Text></Text>),
        headerTitle:(<Text style={styles.title}>首页</Text>),
        headerStyle:{backgroundColor:'#00AAEE'},
        headerTintColor:'#ffffff'
    });
    getVideoList = ()=>{
        this.setState({
            refreshing: true,
            disable:true
        })//开始刷新
        let {starts,nums} = this.state;
        fetch(url+'/getResource.php',{
            method: 'POST',
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded',
            },
            body:`start=${starts}&num=${nums}`
        })
            .then((response) =>response.text())
            .then((responseData)=>{
                // console.log(responseData);
                let {data} = JSON.parse(responseData);
                console.log(data);
                if(data.length==0){
                    console.log('暂无更多数据');
                    return false;
                }
                // console.log('执行');
                let arr = [];
                for(let i=0,len=data.length;i<len;i++){
                    arr.push({
                        key:data[i].id,
                        value:data[i]
                    })
                }
                // console.log('arr',arr);
                this.setState({
                    videos:arr,
                    refreshing: false,
                    disable:false
                })//开始刷新
            })
            .catch((error)=>{console.error('error',error)});

    }
    // 下拉刷新
    _renderRefresh = () => {
        let {starts,nums,disable} = this.state;
        // if(disable){
        //     return false;
        // }
        // console.log('执行下拉刷新');
        starts = starts+nums;
        this.setState({
            starts:starts,
            nums:nums,
        },()=>{
            this.getVideoList();
        })

    };
    // 上拉加载
    _onEndReached = () => {
        let {starts,nums,disable} = this.state;
        // if(disable){
        //     return false;
        // }
        // console.log('执行上拉加载');
        nums = nums+5;
        this.setState({
            starts:starts,
            nums:nums
        },()=>{
            this.getVideoList();
        })
    };

    componentDidMount(){
        this.getVideoList();
    }
    _renderItem=({item,index})=>{
        // noinspection JSAnnotator
        return(
            <PersonalVideo
                source={{uri:item.value.videosrc}}
                imgsource={{uri:item.value.imgsrc}}
                index={index}
                playindex={this.state.index}
                videoid={item.value.id}
                userid={item.value.userid}
                headimg={{uri:item.value.headimg}}
                username={item.value.name}
                stars={item.value.stars}
            >
            </PersonalVideo>
        )
    }
    _onScrollBeginDrag=(e)=>{
        this.setState({
            starty:e.nativeEvent.contentOffset.y
        })
    }
    _onScrollEndDrag=(e)=>{
        this.setState({
            endy:e.nativeEvent.contentOffset.y
        },()=>{
            let {starty,endy,index} = this.state;
            if(endy-starty>=videoHeight*0.2){
                this.setState({
                    index:index+1
                },()=>{
                    this._scrollToIndex();
                })
            }else if(starty-endy>=videoHeight*0.2){
                index = index-1;
                if(index<0){
                    index=0;
                }
                this.setState({
                    index:index
                },()=>{
                    this._scrollToIndex();
                })
            }else{
                this._scrollToIndex();
            }

        })

    }
    _scrollToIndex=()=>{
        let _index = this.state.index;
        this._flatList.scrollToIndex({animated:true, index:_index, viewOffset:0,viewPosition: 0});
    }

    render() {
        const {videos,refreshing} = this.state;
        return (
            <View
                style={styles.container}
            >
                <OptimizedFlatList
                    onScrollBeginDrag={this._onScrollBeginDrag}
                    onScrollEndDrag={this._onScrollEndDrag}
                    data={videos}
                    ref={(flatlist)=>this._flatList=flatlist}
                    renderItem={this._renderItem}
                    getItemLayout={(data,index)=>(
                        {length: videoHeight, offset: videoHeight * index, index}
                    )}
                    onRefresh={ this._renderRefresh }
                    refreshing={ refreshing }
                    onEndReached={ this._onEndReached }
                    onEndReachedThreshold={0.2}
                    showsVerticalScrollIndicator={false}
                    // keyExtractor={this._keyExtractor}
                />

            </View>
        );
    }
}

**Comment by gaokaikai** [comment]
@Lxxyx
