### ISSUE TITLE
Task 'installDebug' not found in root project 'android'. Some candidates are: 'installDevDebug'.

### ISSUE THREAD

**Issue by nahidmbstu** [facebook/react-native#18877]
react-native run-android

Scanning folders for symlinks in /home/ubuntu/code/nodejs/Untitled Folder/testprojectnotification/node_modules (9ms)
JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug)...
Parallel execution with configuration on demand is an incubating feature.
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to /home/ubuntu/Public/ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

FAILURE: Build failed with an exception.

* What went wrong:
Task 'installDebug' not found in root project 'android'. Some candidates are: 'installDevDebug'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.296 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

**Comment by gouthamank** [comment]
Have you created product flavors by any chance?
