### ISSUE TITLE
Cannot add a child that doesn't have a YogaNode to a parent without a measure function!(Trying to add a 'ReactRawTextShadowNode' to a 'LayoutShadowNode')

### ISSUE THREAD

**Issue by sojimon** [facebook/react-native#18880]
Hi, when I run my react native app in android device using the command  `react-native run-android`, for a particular component I get the above error.But there is no error if it run on android simulator, ios simulator and ios devices.

## Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 7.10.0
  Yarn: Not Found
  npm: 4.2.0
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: 0.54.1 => 0.54.1

**Comment by sojimon** [comment]
My code is

```
/**
 * Dashboard Component
 */
import React, { Component } from 'react';
import {
    StyleSheet,
    Text,
    Image,
    ScrollView,
    Alert,
    TextInput
} from 'react-native';
import { Actions } from 'react-native-router-flux';
import {
    Container,
    Header,
    Content,
    List,
    ListItem,
    Left,
    Body,
    Right,
    Spinner,
    Card,
    CardItem,
    Thumbnail,
    Button,
    Icon,
    View
} from 'native-base';
import Post from './post';
import dashboard from '../api/dashboard';
// import Moment from 'moment';

export default class Dashboard extends Component {
    constructor(props) {
        super(props);
        this.state = {
            dashboardDetails: {},
            spinner: true
        }
    }
    componentWillMount() {
        dashboard.getDashboard()
            .then((response) => {
                if (response === false) {
                    console.log(response);
                } else {
                    console.log(response);
                    this.setState({
                        dashboardDetails: response.comments,
                        spinner: false
                    })
                }
            })
    }
    render() {
        return (
            <Content>
                {this.state.spinner ?<Container>
                    <Content> 
                        <Spinner style={{ alignSelf: 'center', marginTop: '50%' }} color='#17AFC7'/>
                    </Content>
                </Container>:<View>
                <Content>
                {(this.state.dashboardDetails.length > 0) ? this.state.dashboardDetails.map((item, key) => {
                    return (
                                <Post mapItem={item} mapKey={key}  getAllContentIdProp={(e, item) => { this.getAllContentId(e, item) }}/>
    
                    )
                }):<Container>
                <Content>
                    <Text style={{ alignSelf: 'center', marginTop: '25%' }} color='#ccc'>No Comments for this Retailer</Text>
                </Content>
    </Container>}
    </Content>
                </View>
            }





                  {/*  <Content>
                        {(this.state.dashboardDetails.length > 0) ? this.state.dashboardDetails.map((item, key) => {
                            return (
                                    <Post mapItem={item} mapKey={key} key={key} getAllContentIdProp={(e, item) => { this.getAllContentId(e, item) }}/>

                            )
                        })
                            : <Container>
                                <Content>
                                    <Text style={{ alignSelf: 'center', marginTop: '25%' }} color='#ccc'>No Comments for this Retailer</Text>
                                </Content>
                    </Container>} </Content> */}

            </Content>

        )

    }

}


```

**Comment by anderskev** [comment]
This is due to having plain text that is not inside of a Text component, please see [#13243](https://github.com/facebook/react-native/issues/13243).

**Comment by Billy-** [comment]
@sojimon You need to provide what code is causing the issue...

@anderskev I have had this issue with other types of node too, iirc.

**Comment by sojimon** [comment]
The error cleared when updated to `react-native":"^0.55.0`.

**Comment by johnckendall** [comment]
Here is another fun one that happens only in **android** (even in RN 0.55.3):

`{this.props.loadingURL&&
         <View style={{flexDirection:‘row’,alignItems:‘center’,justifyContent:‘center’,marginTop:40,marginBottom:10,}}>
           <Text style={{marginRight:10,fontSize:20}}>{this.props.loadingURL}</Text>
           <ActivityIndicator size=“large” color=“black” />
         </View>
       }`

This blows up Android with that error if loadingURL is an empty string.  It works fine if it's a non-empty string or a boolean or if I change it to this (basically convert it to a boolean):

`{!_.isEmpty(this.props.loadingURL)&&`

another 2 hours wasted!  👎

**Comment by mezod** [comment]
The error persists here with 0.55.3

**Comment by sfratini** [comment]
Another posibility is that you have not closed a tag correctly. 

This would also cause the problem <Component/>>

See the extra > at the end.

**Comment by phillmill** [comment]
This fix for me was to add a comparison in my conditional if this helps anyone:

Doesn't Work:

`{this.state.numPhoto &&
  <MyComponent />
}`

Works:

`{this.state.numPhotos > 0 &&
  <MyComponent />
}`

**Comment by joshuapinter** [comment]
@phillmill In your case, it's likely because `numPhotos` doesn't return a boolean. It probably returns an integer, which can be interpreted as a string, which it tries to join the `<MyComponent />` but two adjacent components need to be wrapped in a View.

**Comment by lyrl** [comment]
`<View style={[styles.test, {marginTop: 10}]}>
          <View style={[styles.test2, {marginLeft: 20, marginRight: 20}]}>
            <Divider style={{backgroundColor: 'grey'}} />
          </View>
        </View>q`

change to work

`<View style={[styles.test, {marginTop: 10}]}>
          <View style={[styles.test2, {marginLeft: 20, marginRight: 20}]}>
            <Divider style={{backgroundColor: 'grey'}} />
          </View>
        </View>`

**Comment by skptricks** [comment]
I have found solution for this issue. refer this link : https://www.skptricks.com/2018/08/react-native-cannot-add-child-that.html

**Comment by kylanhurt** [comment]
My solution was similar to @phillmill, I was only having the issue on Android (not iOS) and had to change my conditional to check for `this.props.defaultElectrumServer.length !== 0` rather than just `this.props.defaultElectrumServer.length`. I don't know why a blank screen wouldn't be considered falsey but oh well.

**Comment by DjarallahBrahim** [comment]
> ```
> <View style={[styles.test, {marginTop: 10}]}>
>           <View style={[styles.test2, {marginLeft: 20, marginRight: 20}]}>
>             <Divider style={{backgroundColor: 'grey'}} />
>           </View>
>         </View>q
> ```
> 
> change to work
> 
> ```
> <View style={[styles.test, {marginTop: 10}]}>
>           <View style={[styles.test2, {marginLeft: 20, marginRight: 20}]}>
>             <Divider style={{backgroundColor: 'grey'}} />
>           </View>
>         </View>
> ```

In my case: 
return (
            <ScrollView>
{dataCategories..............CODE.....................};
</ScrollView>
)

After 2h i found that i add #; hahaha !

**Comment by nandorojo** [comment]
This error persists, and the error does not indicate which line(s) are causing it.

**Comment by irajwani** [comment]
Hello, the specific error I'm getting is:
"Cannot add a child that doesn't have a YogaNode to a parent without a measure function! (Trying to add a 'RCTRawText [text: >]' to a 'RCTView' )". 

I've tried just about every solution above to no avail; I've isolated the issue to a single component but that component is like 2000 lines of code so it's really hard to know what is wrong because my linters and syntax checkers in vs code show no issues.

Please help!

react native version: 0.55.3 
App works just fine on iOS. This is purely an android issue.

**Comment by prabhu133** [comment]
> Hello, the specific error I'm getting is:
> "Cannot add a child that doesn't have a YogaNode to a parent without a measure function! (Trying to add a 'RCTRawText [text: >]' to a 'RCTView' )".
> 
> I've tried just about every solution above to no avail; I've isolated the issue to a single component but that component is like 2000 lines of code so it's really hard to know what is wrong because my linters and syntax checkers in vs code show no issues.
> 
> Please help!
> 
> react native version: 0.55.3
> App works just fine on iOS. This is purely an android issue.

I am also getting same issue. If anyone found solution, please help.

**Comment by macnmunasinghe** [comment]
hi face the same issue, 
problem was i had more than one children tag inside Text tag after removing extra tag issue was resolved

**Comment by TheSavior** [comment]
Hi all! Sorry for the long wait but I think [the fix for this just landed](https://github.com/facebook/react-native/commit/66601e755fcad10698e61d20878d52194ad0e90c).

We were able to repro and fix this issue with this sample code:

```
function PlaygroundContent(props: {}) {
  return (
    <View>
      <Text>
        <View style={{width: 10, height: 10}}>
          <Image source={ANY_IMAGE_SOURCE} />
        </View>
      </Text>
    </View>
  );
}
```
