### ISSUE TITLE
Attempt to invoke interface method 'boolean android.view.inputmethod.InputConnection.finishComposingText()' on a null object reference

### ISSUE THREAD

**Issue by SudoPlz** [facebook/react-native#18884]
Hey there,

here's a crash we received in Bugsnag from on of our production devices:

```java
java.lang.NullPointerException Attempt to invoke interface method 'boolean android.view.inputmethod.InputConnection.finishComposingText()' on a null object reference 
    InputConnectionWrapper.java:78 android.view.inputmethod.InputConnectionWrapper.finishComposingText
    InputMethodManager.java:852 android.view.inputmethod.InputMethodManager.reportFinishInputConnection
    ViewRootImpl.java:3523 android.view.ViewRootImpl$ViewRootHandler.handleMessage_aroundBody0
    ViewRootImpl.java:1 android.view.ViewRootImpl$ViewRootHandler$AjcClosure1.run
    ViewRootImplAO.java:82 android.view.ViewRootImplAO.ajc$around$android_view_ViewRootImplAO$3$dffdddeproceed
    ViewRootImplAO.java:87 android.view.ViewRootImplAO.ajc$around$android_view_ViewRootImplAO$3$dffddde
    ViewRootImpl.java:3341 android.view.ViewRootImpl$ViewRootHandler.handleMessage
    Handler.java:102 android.os.Handler.dispatchMessage
    Looper.java:148 android.os.Looper.loop
    ActivityThread.java:5585 android.app.ActivityThread.main
    Method.java:-2 java.lang.reflect.Method.invoke
    ZygoteInit.java:730 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run
    ZygoteInit.java:620 com.android.internal.os.ZygoteInit.main
```

## Steps to reproduce:

Looks like the user was just editing an `TextInput` field, and then tried to change the input method,
here's a breadcrumb we received in bugsnag milliseconds before the crash:

```
input_method_id: com.lge.ime/.LgeImeImpl
Intent Action: android.intent.action.INPUT_METHOD_CHANGED
```

and here's the exact text the client had been typing:

```
field: notes value: Told customer 9am - 1pm. We will give a 30 minute heads up phone call before arriving
Bosch power cord recall in Huxley in Hartford
```

The device where this happened was an LG LGUK750 running Android 6.0.1 (API 23)

Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.4.0
  Yarn: 1.5.1
  npm: 5.3.0
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.3 => 0.53.3

**Comment by SudoPlz** [comment]
We have not updated to 0.55 yet, and I'm not sure how to actually reproduce the issue.

**Comment by Khalef** [comment]
This has happened to me as well. There was no input when this happened. It was in an emulator. It works fine with API 26 and above. It happens when configuration changes portrait to landscape and vise versa. Here is the error produced:
java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.view.inputmethod.InputConnection.finishComposingText()' on a null object reference
                      at android.view.inputmethod.InputConnectionWrapper.finishComposingText(InputConnectionWrapper.java:78)
                      at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:362)
                      at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:78)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by Chivorns** [comment]
This happened to me because of _**Advanced Profiling**_ option is enabled.
To disable the advanced profiling, follow these steps:
1. Select **Run** > **Edit Configurations**.
2. Select your app module in the left pane.
3. Click the **Profiling** tab, and then uncheck **Enable advanced profiling**.
[Learn more](https://developer.android.com/studio/profile/android-profiler)

**Comment by LuckyYangChen** [comment]
After I tried, the problem was solved. Thank you very much

**Comment by Chivorns** [comment]
You're welcome!

**Comment by SudoPlz** [comment]
This sounds like a solution for the dev version of the app, but we received that issue from a production app..

**Comment by mehdiyari** [comment]
@Chivorns thank you

**Comment by Chivorns** [comment]
You're welcome bro

**Comment by Deklirk** [comment]
Thank you very much. It worked bro

**Comment by Chivorns** [comment]
welcome bro

**Comment by silo4** [comment]
@Chivorns thank you

**Comment by simonbuerger** [comment]
@SudoPlz also had this error in production

**Comment by simonbuerger** [comment]
Don't think this should have been closed

**Comment by haimlvov10** [comment]
It would be very nivce, if a message which will said something like: "Check if Advanced Profile is enabled, if it is, then disable it", will pop up....

**Comment by APasqualiSelle** [comment]
Thank you very much! It added me a lot!

**Comment by zasyadev** [comment]
Same issue. any work around?

**Comment by njleonzhang** [comment]
I haven't enable the profiling, but encounter same issue.

```
10-30 20:34:22.545 5970-5970/com.smartlifehousekeeper D/AndroidRuntime: Shutting down VM
10-30 20:34:22.549 5970-5970/com.smartlifehousekeeper E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.smartlifehousekeeper, PID: 5970
    java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.view.inputmethod.InputConnection.finishComposingText()' on a null object reference
        at android.view.inputmethod.InputConnectionWrapper.finishComposingText(InputConnectionWrapper.java:150)
        at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:427)
        at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:85)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:171)
        at android.app.ActivityThread.main(ActivityThread.java:6699)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
```
