### ISSUE TITLE
onEndReached callback trigger twice

### ISSUE THREAD

**Issue by tafelito** [facebook/react-native#18887]
- [X] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [X] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [X] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

FlatList onEndReached callback trigger twice sometimes or even 4 times. 

## Environment
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.9.4
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.54.4 => 0.54.4

## Steps to Reproduce
I'm using a FlatList with inverted={true}. I don't have exactly steps to reproduce it as it happens randomly. I saw a bunch of other issues having the same problem but none of them provided a solution. #14015 did not work for me. If I set the onEndReachedThreshold to 0.8 it doesn't happen all the time as opposed as using the default value of 0.5 that makes it happen constantly. I don't think a re-render is causing this either as it's only running once as you can see from the logs. 

## Expected Behavior
onEndReached to be called once.

## Actual Behavior
this is the render method
```js
render() {
    console.log("render messages", this.props.messages);
    return (
      <FlatList
        inverted
        data={this.props.messages}
        keyExtractor={this.keyExtractor}
        renderItem={this.renderItem}
        onEndReached={info => {
          console.log("onEndReached", info);
        }}
      />
    );
  }
```
And this is the output
![image](https://user-images.githubusercontent.com/5973652/38831178-93bb2ec0-418c-11e8-9e4f-77364c2f3cdf.png)

**Comment by tafelito** [comment]
same thing happens with latest version

**Comment by j0hnhan** [comment]
I have the same issue with react-native version 0.51.0, basically onEndReached triggered twice with different distanceFromEnd value but same state and props.

**Comment by nezaidu** [comment]
same thing

**Comment by nvchung** [comment]
This is my solution: https://github.com/facebook/react-native/issues/14015#issuecomment-389585034

**Comment by DoGooRi** [comment]
same too.
so i used debounce : https://github.com/facebook/react-native/issues/14015#issuecomment-402874026

**Comment by xuqingkuang** [comment]
> onEndReached = () => { let time = (new Date()).getTime() - this.time if (time < 500) return this.time = (new Date()).getTime() // TODO }

shit ... must be 500ms, less delay won't work.

**Comment by brunnohofmann** [comment]
Im facing the same problem, and my the following versions:
 "react": "16.8.3",
    "react-native": "0.59.1",

**Comment by hjaintech** [comment]
Is there any update on when this issue will be fixed ?

**Comment by hellpirat** [comment]
Same here

**Comment by brunnohofmann** [comment]
I saw that you cannot put FlatList inside a ScrolView. 
So I did put my flatlist in a separated screen while this problem still happens and now its working. But
