### ISSUE TITLE
[ActionSheetIOS] usage & documentation

### ISSUE THREAD

**Issue by PhilippKrone** [facebook/react-native#1889]
Hello,

I'm currently a little bit confused about how to use the ActionSheetIOS. To make it work, I had to do the following things:

* Add "RCTActionSheet.xcodeproj" to my project
* add the line   ActionSheetIOS: require('ActionSheetIOS') to react-native.js

I'm pretty sure thats not the way its supposed to be - however, I was not able to find anything in the docs: (https://facebook.github.io/react-native/docs/actionsheetios.html#content). Any hints and enhancements of the docs would be highly appreciated.

**Comment by PhilippKrone** [comment]
Any update here?
@brentvatne do you have a clue why its like that?

**Comment by chirag04** [comment]
@brentvatne closable?

**Comment by chirag04** [comment]
@philikon closing this for now. PR with better docs is most welcome :)
