### ISSUE TITLE
No bundle URL present on new project

### ISSUE THREAD

**Issue by captalgert** [facebook/react-native#18896]
- [X] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [X] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [X] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment

  OS: macOS High Sierra 10.13.4
  Node: 8.9.1
  Yarn: 1.6.0
  npm: 4.6.1
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.1 AI-173.4697961

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.2 => 0.55.2
## Steps to Reproduce
react-native init testProject
cd testProject
react-native run-ios

## Expected Behavior
Well I was expecting the app to run on the iOS emulator. I have tried at least 10 times, and 9/10 I get the same error with new projects.

## Actual Behavior
![simulator screen shot - iphone 6 - 2018-04-17 at 13 09 38](https://user-images.githubusercontent.com/18483911/38866407-10fd57c8-4241-11e8-929c-055413468617.png)

**Sometimes** there is also this error from the Metro Bundler: 

Metro Bundler ready.

 ERROR  ENOENT: no such file or directory, lstat '/Users/xxxxx/Desktop/test/testProject/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64/RCTImageSource.o-041d4dcd'

**Comment by minhphung210** [comment]
same issues

**Comment by anand-neema** [comment]
Have you find any solution?

**Comment by PrimeObjects** [comment]
same issue. lanchPackager.command window hanging at Loading dependency graph, done.

**Comment by juniovitorino** [comment]
I had the same issue and I was able to bypass it by run `npm start` before run `react-native run-ios`.

**Comment by LeXuanTien** [comment]
Same issue, and I solved by add three lines on host file.

Open hosts file: `sudo code /private/etc/hosts` (if you use VSCode)

Add three lines:

```
127.0.0.1 localhost
255.255.255.255 broadcasthost
::1 localhost
```
