### ISSUE TITLE
android PanResponder not work with view which not have backgroundColor

### ISSUE THREAD

**Issue by artOfWarBut** [facebook/react-native#18891]
- [yes] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [yes] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [yes] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

 
## Environment
Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.4.0
  Yarn: 0.27.5
  npm: 5.8.0
  Watchman: 4.1.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4408382

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.54.4 => 0.54.4

## Steps to Reproduce

 android PanResponder not work with view which not have backgroundColor!!!

i find out this bug with my chart view, it waste my days, 

I don't know why, so 

YOU just set its backgroundColor, it works, 

hope help some guys

**Comment by bonham000** [comment]
Same issue! This was very hard to track down. `PanResponder` fails to work at all on Android, surprisingly adding a background color to the parent `View` allows it to start working.

**Comment by olivierdelomez** [comment]
Same issue, I've added `BackgroundColor: 'transparent'`to make it work
