### ISSUE TITLE
Cannot read property 'major' of undefined

### ISSUE THREAD

**Issue by jackyang1984** [facebook/react-native#18900]
"react": "16.3.1",
"react-native": "0.55.2",

file:  node_modules/react-native/Libraries/Core/ReactNativeVersionCheck.js

i found the error in line 30  const nativeVersion = PlatformConstants.reactNativeVersion;

nativeVersion is undefined, so bug display, but when i comment these code, has another bug, oops

**Comment by sahil290791** [comment]
same issue after upgrading to RN 0.49 while running `react-native run-ios`
