### ISSUE TITLE
Error message & Error boundary

### ISSUE THREAD

**Issue by 7ynk3r** [facebook/react-native#18901]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

Looks like there's a difference between error handling between react-native and react (web). If you run the code described bellow, you'll see that react-native is serializing the whole error object inside message, instead of keep the original message. In react (web) everything works as expected.

Something in going on with `throw` and/or `componentDidCatch`, because just creating the error works fine.

## Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.9.4
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.2 => 0.55.2

## Steps to Reproduce

Run the following code

```js
import React from 'react';

class ErrorBoundary extends React.Component {
  state = {
    hasError: false
  }
  componentDidCatch(error, info) {
    this.setState({ hasError: true }, () => {
      alert(error.message);      
    });
  }
  render() {
    if (this.state.hasError) {
      return null;
    }
    return this.props.children;
  }
}

const ErrorComponent = () => {
  throw new Error('my best error!');
}

export default () => (
  <ErrorBoundary>
    <ErrorComponent/>
  </ErrorBoundary>
)
```

## Expected Behavior
I'd expect `error.message` to be **ONLY** `'my best error!'`

## Actual Behavior
After dismissing the "red screen"

![image](https://user-images.githubusercontent.com/6763798/38894800-22498e82-4243-11e8-9cb9-59af4152009a.png)

**Comment by agarwalankitn** [comment]
I have the same issue as well

**Comment by rohozhnikoff** [comment]
`error.message.slice('Error: '.length)`
