### ISSUE TITLE
[ActionSheetIOS] crash on iPad

### ISSUE THREAD

**Issue by jawadrehman** [facebook/react-native#1890]
The same issue can be seen here without react native ... http://stackoverflow.com/a/25644145/1813705 not sure how to sort it out here. 

@brentvatne

**Comment by jawadrehman** [comment]
i solved the issue by modifying RCTActionSheetManger.m with help from the above link

replace line 116 

//if iPhone
  if (UI_USER_INTERFACE_IDIOM() == UIUserInterfaceIdiomPhone) {
    // [self presentViewController:controller animated:YES completion:nil];
    [ctrl presentViewController:share animated:YES completion:nil];
  }
  //if iPad
  else {
    // Change Rect to position Popover
    UIPopoverController *popup = [[UIPopoverController alloc] initWithContentViewController:share];
    [popup presentPopoverFromRect:CGRectMake(ctrl.view.frame.size.width/2, ctrl.view.frame.size.height/4, 0, 0)inView:ctrl.view permittedArrowDirections:0 animated:YES];
  }

**Comment by brentvatne** [comment]
@jawadrehman - nice! can you submit a pull request for that?

**Comment by bradens** [comment]
Need this!

**Comment by chirag04** [comment]
Related: #2395 

A proposed fix: https://github.com/naoufal/react-native-activity-view/pull/13/files


Waiting for @tadeuzagallo's input on the fix.

**Comment by brentvatne** [comment]
Canonical issue: #2395
