### ISSUE TITLE
Could not build module 'React'

### ISSUE THREAD

**Issue by fenghanxu** [facebook/react-native#18913]
#import <React/RCTRootView.h>       Could not build module 'React'

**Comment by fenghanxu** [comment]
Have anyone ever met such a mistake

**Comment by fenghanxu** [comment]
What is the problem?

**Comment by fenghanxu** [comment]
Is there a solution

**Comment by arielLeverate** [comment]
I'm encountering the same problem when trying to upgrade to RN 0.55.3 and after downgrading back to 0.53.3?
