### ISSUE TITLE
react-native run-andriod stops at 97% -> no error no warning

### ISSUE THREAD

**Issue by feja1017** [facebook/react-native#18919]
- [ x ] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [ x ] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [ x ] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

whenever I try to start my application it stops at 97%.
It throws no error or warning...
before I had this issue it throws the following error

> Exception in thread "Device List Monitor"
> java.lang.NullPointerException
>         at com.android.ddmlib.EmulatorConsole.checkConnection(EmulatorConsole.java:317)
>         at com.android.ddmlib.EmulatorConsole.getConsole(EmulatorConsole.java:231)
>         at com.android.ddmlib.DeviceMonitor.queryAvdName(DeviceMonitor.java:248)
>         at com.android.ddmlib.DeviceMonitor.updateDevices(DeviceMonitor.java:220)
>         at com.android.ddmlib.DeviceMonitor.access$400(DeviceMonitor.java:65)
>         at com.android.ddmlib.DeviceMonitor$DeviceListUpdateListener.deviceListUpdate(DeviceMonitor.
>  java:662)

any idears where i messed?
I did [this](https://facebook.github.io/react-native/docs/getting-started.html) react-native instruction 

## Environment
OS: Windows 10
  Node: 9.11.1
  Yarn: Not Found
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.1.0.0 AI-173.4697961

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.3 => 0.55.3

**Comment by feja1017** [comment]
what i see if i run react-native run-android

```
PS C:\React-Native-TryOuts\AwesomeProject> react-native run-android
Scanning folders for symlinks in C:\React-Native-TryOuts\AwesomeProject\node_modules (43ms)
JS server already running.
Building and installing the app on the device (cd android && gradlew.bat installDebug)...
Incremental java compilation is an incubating feature.
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42301Library UP-TO-DATE
:app:prepareComFacebookFbuiTextlayoutbuilderTextlayoutbuilder100Library UP-TO-DATE
:app:prepareComFacebookFrescoDrawee130Library UP-TO-DATE
:app:prepareComFacebookFrescoFbcore130Library UP-TO-DATE
:app:prepareComFacebookFrescoFresco130Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipeline130Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipelineBase130Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipelineOkhttp3130Library UP-TO-DATE
:app:prepareComFacebookReactReactNative0553Library UP-TO-DATE
:app:prepareComFacebookSoloaderSoloader010Library UP-TO-DATE
:app:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:mergeDebugShaders UP-TO-DATE
:app:compileDebugShaders UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:bundleDebugJsAndAssets SKIPPED
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
:app:compileDebugJavaWithJavac UP-TO-DATE
:app:compileDebugNdk UP-TO-DATE
:app:compileDebugSources UP-TO-DATE
:app:transformClassesWithDexForDebug UP-TO-DATE
:app:mergeDebugJniLibFolders UP-TO-DATE
:app:transformNative_libsWithMergeJniLibsForDebug UP-TO-DATE
:app:processDebugJavaRes UP-TO-DATE
:app:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
:app:validateSigningDebug
:app:packageDebug UP-TO-DATE
:app:assembleDebug UP-TO-DATE
> Building 97% > :app:installDebug

```

**Comment by feja1017** [comment]
restart your device if this occures

**Comment by ZamirAmiri** [comment]
adb kill-server
adb start-server

worked for me
