### ISSUE TITLE
error when react-native run-android

### ISSUE THREAD

**Issue by androidwt** [facebook/react-native#18918]
## error when react-native run-android
win10, jdk1.8,nodejs,python2 sdk and all the tools about Android is installed.
 JAVA_HOME , ANDORID_HOME or adb work well

## A problem occurred evaluating project ':app'.
log:
Total time: 1.916 secs
FAILURE: Build failed with an exception.

## Build file 'D:\react_native_space\HelloRN\android\app\build.gradle' line: 1

What went wrong:
A problem occurred evaluating project ':app'.
com/google/protobuf/MessageOrBuilder

**Comment by androidwt** [comment]
win10,all the tools need by react native, I had re-installed last night,but it doesn't work neither

**Comment by morteza4545** [comment]
hi
how to fix error "Trailing char < > at index 22: D:\android\android-sdk \package.xml" when run project?
