### ISSUE TITLE
'folly/dynamic.h' file not found after pod install

### ISSUE THREAD

**Issue by totodot** [facebook/react-native#18924]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [ ] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment
Environment:
  OS: macOS High Sierra 10.13.2
  Node: 8.3.0
  Yarn: 0.23.4
  npm: 5.3.0
  Watchman: 4.9.0
  Xcode: Xcode 9.0.1 Build version 9A1004
  Android Studio: 2.2 AI-145.3330264

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.2 => 0.55.2

## Steps to Reproduce

- npm install react-native-svg --save
- react-native link react-native-svg
- cd ios && pod install

Podfile
```
# Add new pods below this line
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
pod 'RNSVG', :path => '../node_modules/react-native-svg'
pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'DevSupport'
]
```

## Expected Behavior
Xcode Build with no Errors

## Actual Behavior
'folly/dynamic.h' file not found
![alt text](https://image.ibb.co/f3qoNS/folly.png)

**Comment by sujitpk-perennial** [comment]
heee have you found any solution  ?

**Comment by totodot** [comment]
You have to update react-native to 0.55.3 and add this lines to podfile
```
# To use CocoaPods with React Native, you need to add this specific Yoga spec as well
pod 'yoga', :path =>  react_native_path + '/ReactCommon/yoga'

# React Native
pod 'React', :path => react_native_path, :subspecs => [
  'Core',
  'CxxBridge',
  'RCTText',
  'RCTNetwork',
  'RCTWebSocket',
  'RCTImage',
  'RCTNetwork',
  'DevSupport'
]

# Add new pods below this line
```

**Comment by matteocollina** [comment]
@totodot I have two issues (RN 0.55.3 , React 16.3.1): 
- algorithm not found (in Yoga-internal.h)
- could not build yoga (RCTConvert.h)

**Comment by filipef101** [comment]
@matteocollina did you add the pod yogo? ais it already working?

**Comment by matteocollina** [comment]
@filipef101 Yes, this is my pod: https://gist.github.com/matteocollina/fe2a9c3e2a96061ac1a15c0fcf2cbded

**Comment by filipef101** [comment]
@matteocollina Thank you! I managed to solve it, missed the instruction to update react native. did you not update react native?

**Comment by matteocollina** [comment]
@filipef101 Yes i've updated to RN 0.55.3 
This is my gist for this version : https://gist.github.com/matteocollina/b14eb877c35d6c796e370b6e55504bfa

**Comment by walker-ll** [comment]
I have the release to 0.55.4, but there were still problems
Undefined symbols for architecture x86_64：...
![image](https://user-images.githubusercontent.com/7478867/40480612-9e844036-5f81-11e8-87f4-8bfce9e30922.png)
