### ISSUE TITLE
Warning: isMounted(...) is deprecated when use NativeMethodsMixin

### ISSUE THREAD

**Issue by AndreiCalazans** [facebook/react-native#18921]
## Environment
  OS: macOS High Sierra 10.13.4
  Node: 9.4.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.1 => 0.55.1

## Steps to Reproduce

Use the following in your React Native code.

**rendered element:**
``` <View ref={e => this.renderedElement = e}>```
 
```
import NativeMethodsMixin from 'NativeMethodsMixin';

NativeMethodsMixin.measureInWindow.call(this.renderedElement, (x, y, width, height) => {
        this.setState({ xOffset: x, yOffset: y, elementWidth: width, elementHeight: height });
      });
```

## Expected Behavior
   Get layout information from referenced component without warnings.

## Actual Behavior
  It is throwing the following warning.

```
Warning: isMounted(...) is deprecated in plain JavaScript React classes. Instead, make sure to clean up subscriptions and pending requests in componentWillUnmount to prevent memory leaks.
```

**Comment by BatDroid** [comment]
had the same issue when used ref.measure for a view wrapping another component inside itself... would appreciate if someone could help though it can be done with onLayout as well

**Comment by FredyC** [comment]
https://github.com/facebook/react-native/issues/18868#issuecomment-382671739

**Comment by BatDroid** [comment]
@FredyC that seems to be only hiding the warning not solving it!

**Comment by FredyC** [comment]
Well, that was the intention 🤡  Obviously, the `isMounted` is totally legacy API coming from the age of `React.createClass`. Also if you actually read [release notes](https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md#054), you will understand why my solution is a correct one...

![image](https://user-images.githubusercontent.com/1096340/38993131-0c68689e-43e3-11e8-8dc9-a398d23334e8.png)

**Comment by bvaughn** [comment]
Dupilcate of #18868

**Comment by gtsluk** [comment]
"react": "16.3.1",
    "react-native": "0.55.3",

I found isMounted is called 
node_modules/react-native/Libraries/Components/Touchable/TouchableHighlight.js

**Comment by MacKentoch** [comment]
I just upgraded a whole application to 0.57.3, this warning has gone.

In my case, it did not have any incidence on my previous version of the application.
