### ISSUE TITLE
WebSocket https connection with self signed certificate on Android

### ISSUE THREAD

**Issue by emidiocroci** [facebook/react-native#18920]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

I tried to connect using websocket to a server using https with a self signed certificate. I customized the OkHttpClient using the factory reintroduced in the 0.54 version and it works as expected for https requests but it doesn't work for websocket connection. By looking at the WebSocketModule.java I found that in the connect method the OkHttpClient is created as a default OkHttpClient instead of using the OkHttpClientProvider.createClient() method that, from 0.54 version, allow us to customize the OkHttpClient.

## Environment

Environment:
 OS: macOS Sierra 10.12.5
 Node: 9.9.0
 Yarn: 1.5.1
 npm: 5.6.0
 Watchman: 4.9.0
 Xcode: Xcode 8.3.2 Build version 8E2002
 Android Studio: 3.0 AI-171.4408382

Packages: (wanted => installed)
 react: ^16.2.0 => 16.2.0
 react-native: ^0.54.0 => 0.54.4

## Steps to Reproduce

Try to establish a secure web socket connection to a web server with an https certificate by using a custom OkHttpClientFactory

## Expected Behavior

Connection established

## Actual Behavior

This error occur 

> java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

**Comment by tolbkni** [comment]
@react-native-bot Yeah, I can reproduce the issue on the latest release 0.55.4
