### ISSUE TITLE
InputAccessoryView not working in react-native 0.55

### ISSUE THREAD

**Issue by alinz** [facebook/react-native#18923]
None of the provided examples related to `InputAccessoryView` feature in 0.55 are not working. 

## Environment

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.5.0
  Yarn: 1.5.1
  npm: 5.3.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.3 => 0.55.3

## Steps to Reproduce
- react-native init sample
- copy and paste the code from either [here](https://facebook.github.io/react-native/docs/next/inputaccessoryview.html) or [here](https://github.com/facebook/react-native/blob/master/RNTester/js/InputAccessoryViewExample.js)
- run the code

## Expected Behavior
Should work and not presented with red screen

## Actual Behavior
provided an error in red screen as follows

![simulator screen shot - iphone 6 - 2018-04-18 at 10 40 39](https://user-images.githubusercontent.com/967050/38939013-f29e2f96-42f4-11e8-9e78-50c2bf98019e.png)

**Comment by marcosrdz** [comment]
I had to use:
const InputAccessoryView = require('InputAccessoryView')

Rather than:
import { InputAccessoryView} from 'react-native'

**Comment by alinz** [comment]
Thanks. Closing this issue.

**Comment by AndrewIngram** [comment]
@alinz Having a workaround doesn't mean the issue is resolved. The underlying issue is that InputAccessoryView hasn't been made available as an export on the main 'react-native' module, this contradicts the documentation about how to use it.

**Comment by AndrewIngram** [comment]
Looks like it's fixed in master though! 🎉
