### ISSUE TITLE
Make the default for underlineColorAndroid transparent

### ISSUE THREAD

**Issue by janicduplessis** [facebook/react-native#18938]
https://twitter.com/notbrent/status/986843528004292608

This will help reduce differences between iOS and Android, the default style is actually kind of broken right now because we no longer add extra padding on Android.

Before:
![image](https://user-images.githubusercontent.com/2677334/38977730-36eeed28-4383-11e8-9bcf-73dec76082ce.png)

After:
![image](https://user-images.githubusercontent.com/2677334/38977751-4b179994-4383-11e8-80f0-5bbf48f5bf65.png)

The easiest implement this might be just to add `underlineColorAndroid: 'transparent'` to TextInput default props.

**Comment by joefazz** [comment]
How about just making it underlineColor (with transparent default) and make it so it just adds a border bottom on iOS? I tend to underline most of my textinputs but always just make the android underline transparent so I can share the style for both platforms.

**Comment by janicduplessis** [comment]
@joefazz I think the underline is more of a material design thing, and poly-filling it on iOS is out of this scope. It's actually a bit different than border, both in the way it is positioned and is affected by focus. Also it could lead to some weird things if someone uses both border and underlineColor.

**Comment by AndrewIngram** [comment]
It’s worth pointing out this that API doesn’t produce an underline compatible with the Material design spec for form inputs. So right now, any dev who is trying to implement material is *also* setting this prop to transparent and doing all the work on top of a blank slate.

**Comment by mikaoelitiana** [comment]
I am willing to work on this one as a first issue.

**Comment by janicduplessis** [comment]
@mikaoelitiana Cool! You can mention me in the PR and I'll have a look.

**Comment by shubhnik** [comment]
@janicduplessis @mikaoelitiana with this commit, the underline color doesn't change to `colorAccent` defined in the theme in `styles.xml`. Is there anything else I need to do to get the desired behavior which was possible before this commit. This change and how to get the desired effect also isn't mentioned in the docs.

My RN version is 0.58.3.

**Comment by martnst** [comment]
@shubhnik you can get back the old behaviour by setting.
```
<TextInput underlineColorAndroid={null} … />
```
See more [this comment](https://github.com/facebook/react-native/pull/18988#issuecomment-462970368) for more finding of mine on this.
