### ISSUE TITLE
including renderLoading and startInLoadingState in a WebView causes its contentSize to change in iOS

### ISSUE THREAD

**Issue by michaeleisel** [facebook/react-native#18935]
- [X] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [X] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [X] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

When I use the `renderLoading` and `startInLoadingState` properties for my WebView on iOS and I try to load an image, the image turns out quite wide. The frame of the webview is the same, but the content inside is larger.

## Environment
Environment:
  OS: macOS High Sierra 10.13.2
  Node: 9.9.0
  Yarn: Not Found
  npm: 4.6.1
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.1 AI-173.4697961

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: ^0.55.2 => 0.55.2

## Steps to Reproduce
Run the following code:
```
import React, { Component } from 'react';
import { ActivityIndicator, View, StyleSheet, WebView } from 'react-native';
import { Constants } from 'expo';

export default class App extends Component {
	indicator() {
		return (<ActivityIndicator size="large" color="#ff0002" style={styles.indicator}/>);
	}

  render() {
    return (
			<WebView style={styles.webview} renderLoading={this.indicator} startInLoadingState={true} source={{uri: 'https://i.imgur.com/3DLTVY0_d.jpg?maxwidth=320&shape=thumb&fidelity=medium'}}/>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: Constants.statusBarHeight,
    backgroundColor: '#ecf0f1',
  },
	webview: {
		flex: 1,
	},
});
```

## Expected Behavior
The image's width in the webview matches the screen's.

## Actual Behavior
The image's width in the webview is much larger.

**Comment by forrestgrant** [comment]
@michaeleisel, did you solve this? I'm seeing the same thing.

**Comment by michaeleisel** [comment]
no, unfortunately. i just did my own loading spinner logic
