### ISSUE TITLE
Can't find variable:Symbol

### ISSUE THREAD

**Issue by bingfeng1225** [facebook/react-native#18932]
- [ YES] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [YES ] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [YES ] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.11.0
  Yarn: 1.5.1
  npm: 5.8.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.3 => 0.55.3

## Steps to Reproduce
1、Create a new RN project with WebStorm
2、Define a Symbol in App.js
3、Select the Android platform to run
4、Code：
`type Props = {};
const Test = Symbol('test');
export default class App extends Component<Props> {
    render() {
        return (
            <View style={styles.container}>
                <Text style={styles.welcome}>
                    Welcome to React Native!
                </Text>
                <Text style={styles.instructions}>
                    To get started, edit App.js
                </Text>
                <Text style={styles.instructions}>
                    {instructions}
                </Text>
            </View>
        );
    }
}`

## Actual Behavior
1、The following problems arise
![screenshot_20180419-091248_hiasst](https://user-images.githubusercontent.com/10192109/38966850-db8065c8-43b6-11e8-9517-24dadafc9b5e.png)

2、When selecting the "Debug JS Remotely" menu, the code works normally.

3、The code works well on the iOS platform。

**Comment by isnifer** [comment]
@bingfeng1225 
```js
import 'es6-symbol/implement'
```

**Comment by bingfeng1225** [comment]
@isnifer 
Thanks for your help

**Comment by Zacqary** [comment]
`es6-symbol` unfortunately isn't working in my project. Importing it results in a `Objects are not valid as a React child (found: object with keys {$$typeof, type, key, ref, props, _owner, _store}). If you meant to render a collection of children, use an array instead` error. Same with `babel-polyfill`.

Is Symbol support in the Android runtime on the roadmap? That's the broader issue here, and the fact that a workaround (sometimes) exists doesn't mean this isn't an implementation gap.

**Comment by jkirkpatrick24** [comment]
@Zacqary did you come up with a solution? I'm having the exact same issue.

**Comment by acro5piano** [comment]
I import `babel-polyfill` instead of `es6-symbol` and it works.
