### ISSUE TITLE
RNTester IOS throwing error upon launch from XCode

### ISSUE THREAD

**Issue by lessthanjake328** [facebook/react-native#18949]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

When launching RNTester from XCode, an error is thrown in XCode, Metro Bundler, and IOS Simulator red screen.  

## Environment
Environment:
  OS: macOS High Sierra 10.13.3
  Node: 9.9.0
  Yarn: 1.5.1
  npm: 5.8.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.1 AI-173.4697961

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.3 => 0.55.3

## Steps to Reproduce
Simply open RNTester.xcodeproj in XCode and press Run

## Expected Behavior
I was expecting the program to open

## Actual Behavior
The program crashed.  Information as follows:

`Last login: Wed Apr 18 11:28:38 on ttys003 -bash: /Users/<username>/.profile: No such file or directory /Users/\<username\>/Files/Programming/Learning/react-native/scripts/launchPackager.command ; exit;`

`Davids-MacBook-Pro:~ <username>$ /Users/\<username\>/Files/Programming/Learning/react-native/scripts/launchPackager.command ; exit;`

`/Users/\<username\>/Files/Programming/Learning/react-native/node_modules/babel-core/lib/transformation/file/index.js:590 throw err; ^`

`SyntaxError: /Users/\<username\>/Files/Programming/Learning/react-native/local-cli/core/index.js: Unexpected token (28:12)`

`26 | const path = require('path');`

`27 |`

`> 28 | import type {CommandT} from '../commands';`

`| ................ ^   **it is pointing at the opening { here**`

`29 | import type {ConfigT} from 'metro';`

`30 |`

`31 | export type RNConfig = {`

`at Parser.pp$5.raise (/Users/\<username\>/Files/Programming/Learning/react-native/node_modules/babylon/lib/index.js:4454:13)`

`at Parser.pp.unexpected (/Users/\<username\>/Files/Programming/Learning/react-native/node_modules/babylon/lib/index.js:1761:8)`

`at Parser.pp.expectContextual (/Users/\<username\>/Files/Programming/Learning/react- native/node_modules/babylon/lib/index.js:1723:39)`

`at Parser.pp$1.parseImport (/Users/\<username\>/Files/Programming/Learning/react-native/node_modules/babylon/lib/index.js:2869:10)`

`at Parser.pp$1.parseStatement (/Users/\<username\>/Files/Programming/Learning/react- native/node_modules/babylon/lib/index.js:1884:49)`

`at Parser.pp$1.parseBlockBody (/Users/\<username\>/Files/Programming/Learning/react- native/node_modules/babylon/lib/index.js:2268:21)`

`at Parser.pp$1.parseTopLevel (/Users/\<username\>/Files/Programming/Learning/react- native/node_modules/babylon/lib/index.js:1778:8)`

`at Parser.parse (/Users/\<username\>/Files/Programming/Learning/react-native/node_modules/babylon/lib/index.js:1673:17)`

`at parse (/Users/\<username\>/Files/Programming/Learning/react-native/node_modules/babylon/lib/index.js:7305:37)`

`at File.parse (/Users/\<username\>/Files/Programming/Learning/react-native/node_modules/babel- core/lib/transformation/file/index.js:517:15)`

`Process terminated. Press <enter> to close the window`

---

Simulator Red Screen says:

No script URL provided. Make sure the packager is running or you have embedded a JS bundle in your application bundle

unsanitizedScriptURLString = (null)

**Comment by himanshuchauhan** [comment]
same issue here .

**Comment by lessthanjake328** [comment]
I am now having a problem which says: 

![image](https://user-images.githubusercontent.com/10568923/39137971-e510a8da-46ec-11e8-93da-97f124f4b666.png)

**Comment by lessthanjake328** [comment]
error: bundling failed: SyntaxError: /Users/davidbowen/Files/Programming/Learning/react-native/Libraries/BatchedBridge/NativeModules.js: Support for the experimental syntax 'objectRestSpread' isn't currently enabled (119:5):

  117 |   const {
  118 |     message,
> 119 |     ...extraErrorInfo
      |     ^
  120 |   } = errorData || {};
  121 |   const error : ExtendedError = new Error(message);
  122 |   error.framesToPop = 1;

Add @babel/plugin-proposal-object-rest-spread (https://git.io/vb4Ss) to the 'plugins' section of your Babel config to enable transformation.
    at _class.raise (/Users/davidbowen/Files/Programming/Learning/react-native/node_modules/@babel/core/node_modules/babylon/lib/index.js:772:15)
    at _class.expectPlugin (/Users/davidbowen/Files/Programming/Learning/react-native/node_modules/@babel/core/node_modules/babylon/lib/index.js:2052:18)
    at _class.parseObj (/Users/davidbowen/Files/Programming/Learning/react-native/node_modules/@babel/core/node_modules/babylon/lib/index.js:3433:14)
    at _class.parseBindingAtom (/Users/davidbowen/Files/Programming/Learning/react-native/node_modules/@babel/core/node_modules/babylon/lib/index.js:2300:21)
    at _class.parseVarHead (/Users/davidbowen/Files/Programming/Learning/react-native/node_modules/@babel/core/node_modules/babylon/lib/index.js:4516:20)
    at _class.parseVarHead (/Users/davidbowen/Files/Programming/Learning/react-native/node_modules/@babel/core/node_modules/babylon/lib/index.js:7121:42)
    at _class.parseVar (/Users/davidbowen/Files/Programming/Learning/react-native/node_modules/@babel/core/node_modules/babylon/lib/index.js:4492:12)
    at _class.parseVarStatement (/Users/davidbowen/Files/Programming/Learning/react-native/node_modules/@babel/core/node_modules/babylon/lib/index.js:4325:10)
    at _class.parseStatementContent (/Users/davidbowen/Files/Programming/Learning/react-native/node_modules/@babel/core/node_modules/babylon/lib/index.js:3949:21)
    at _class.parseStatement (/Users/davidbowen/Files/Programming/Learning/react-native/node_modules/@babel/core/node_modules/babylon/lib/index.js:3899:17)
 BUNDLE  [ios, dev] RNTester/js/RNTesterApp.ios.js ░░░░░░░░░░░░░░░░ 0.0% (3/186), failed.

**Comment by Sooongz** [comment]
same issue.

**Comment by mattijsf** [comment]
Had the same message. Solved it by running:

```bash
rm -rf node_modules && npm cache clear --force && watchman watch-del-all && rm -rf $TMPDIR/react-*
```

Not sure if all "clean" commands are really necessary though...

**Comment by lessthanjake328** [comment]
@morenoh149 no there was no custom coded added to the RNTester.  I wouldn't have customized anything in the Tester.  I only wanted to use the tester to view various available components in RN.  The issue continued to occur as long as I tried using RNTester.   It has been a while, so there is a possibility it is fixed now, but I have not tried using RNTester since my last post.

BTW I am the OP :)

**Comment by lessthanjake328** [comment]
I'll go ahead and close this since it is an old issue and is just taking up space.
