### ISSUE TITLE
[SectionList][inverted] SectionSeparatorComponent displays in wrong places with inverted list

### ISSUE THREAD

**Issue by terrysahaidak** [facebook/react-native#18943]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment
Environment:
  OS: macOS High Sierra 10.13.1
  Node: 8.6.0
  Yarn: 1.5.1
  npm: 4.6.1
  Watchman: 4.9.0
  Xcode: Xcode 9.0.1 Build version 9A1004
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.3 => 0.55.3

## Steps to Reproduce

Clone [this repository](https://github.com/terrysahaidak/ReactNative-SeactionList-Bug-Example) and run it via `react-native run-ios`.
Observe the section separators are in wrong (randomly?) places.

## Expected Behavior

The section separators should be right after the sections and section headers (like the non-inverted section list does).

I've used the same code as below but without inverted prop.

#### Expected gif:
![kapture 2018-04-19 at 13 23 53](https://user-images.githubusercontent.com/7809008/38986378-ee6105f8-43d4-11e8-8e53-c08cc96c560e.gif)

## Actual Behavior

The section separator components are in wrong places in the list if the list is inverted. For a non-inverted list, it works as expected.

Sample code:
```jsx
export default class App extends React.Component {
  render() {
    return (
      <View style={s.container}>
        <SectionList
          inverted
          sections={mock.sections}
          maxToRenderPerBatch={10}
          initialNumToRender={10}
          style={{ flex: 1 }}
          keyExtractor={(item) => item.messageId}
          renderSectionHeader={sectionProps => (
            <SectionHeader
              {...sectionProps}
            />
          )}
          renderItem={({ item }) => (
            <ListItem
              item={item}
            />
          )}
          SectionSeparatorComponent={Separator}
          ItemSeparatorComponent={ItemSeparator}
        />
        />
      </View>
    );
  }
}

const Separator = ({ big }) => (
  <View style={[s.separatorContainer, big && s.separatorBig]} />
);

const s = StyleSheet.create({
  container: {
    marginTop: 24,
    flex: 1,
    backgroundColor: 'white',
  },
  sectionContainer: {
    // height: 16,
    marginTop: 8,
    marginBottom: 16,
    backgroundColor: '#b4c5ff',
    borderRadius: 16,
    alignSelf: 'center',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  separatorContainer: {
    height: 8,
    backgroundColor: 'gray',
    borderBottomWidth: 1,
    borderTopWidth: 1,
    borderBottomColor: 'blue',
    borderTopColor: 'blue',
  },
});
```

#### Problem Gif:
![kapture 2018-04-19 at 13 21 10](https://user-images.githubusercontent.com/7809008/38986271-9e8be1a6-43d4-11e8-9da8-5a43583b6b2e.gif)

**Comment by yanisakli** [comment]
try `stickySectionHeadersEnabled={false}`

**Comment by terrysahaidak** [comment]
@yanisakli Just tried it out with `stickySectionHeaderEnabled={false}`.
Nothing has changed:
![image](https://user-images.githubusercontent.com/7809008/43832498-480b8cda-9b10-11e8-8594-9b3881cdbe22.png)

**Comment by earle** [comment]
To clarify the issue here:  The section headers need to render before the section items when the SectionList is inverted -- currently when the SectionList is reversed the section headers are placed after each section

**Comment by nastynaz** [comment]
Any updates on this? I'm still getting this issue on the latest version of react native.

**Comment by terrysahaidak** [comment]
@nastynaz I did implement my own section-list using flatlist and conditional rendering of the current item, poor performance but at least it works.

**Comment by terrysahaidak** [comment]
This isn't fixed yet.

**Comment by terrysahaidak** [comment]
I will check the latest pr and write back here :)
