### ISSUE TITLE
Fetch/Axios stops receiving data only in RN

### ISSUE THREAD

**Issue by grobmeier** [facebook/react-native#18959]
- [X] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [X] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [ ] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

I am using Expo with running RN  0.52.0. I have read the release notes, my potential issue was not listed up to 0.55.

I am calling my backend server using React Native, Redux, Redux Thunk. In the end Fetch is running. The server responds with data (according to the log) and Fetch should continue - but it does never complete. I have seen this with thunk code like:

```
return fetch(BASE_URL +'/my/resource', {
        method: 'GET',
        headers: new Headers({ ... })   
      })
      .then((response) => {
        return response.text();
      })
      .then((response) => {
          return JsonUtils.readJsonFromResponse(response);
      }).catch(function(error) {
        throw error;
      });    
```
When adding console.log, it would never come to response.text(). However the faulty behavior is not always happening. It is only the case the response size is bigger. Currently, I tested it with 100kb, but it also happened with 50kb. It is working just fine with sizes below 10kb.

The same URL causing the problems is running as expected in any other scenario. Also, when I switch to another URL carrying a lot of data, the problem happens again.

## Environment

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.4.0
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.0 => 0.52.0

## Steps to Reproduce

- call data from an api service with size > 100kb on iOS simulator.

## Expected Behavior

- Fetch completes

## Actual Behavior

- Fetch never completes

**Comment by americoleonardo** [comment]
Hi, you are sending this request to another domain or inside app?

If you trying to get an information to external server, you will need use axios crossdomain: true, like this:

```
axios.get("my base url", {crossdomain: true})
     .then(function (response) {
        console.log("my json response");
    })
    .catch(function (error) {
        console.log("my json response");
    });
```

**Comment by grobmeier** [comment]
Actually I found out this was not related to any of my code (nor my servers). I have removed Expo and went with plain React Native, and all my issues were gone.

For some unknown reasons Expo was breaking my network activities. Since I don't this is RN related, closing this now.

**Comment by rayray-py** [comment]
I encountered the same bug.
I don't use Expo, but the bug occurs.
