### ISSUE TITLE
react-native-git-upgrade hangs

### ISSUE THREAD

**Issue by uriva** [facebook/react-native#18958]
Command does a bunch of stuff, but after printing

> rnpm-install info Assets have been successfully linked to your project 

it hangs forever.

react-native-cli: 2.0.1
react-native: 0.47.2

(already running with --verbose)

**Comment by uriva** [comment]
I've posted all relevant information.

**Comment by uriva** [comment]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [ ] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment
react-native-cli: 2.0.1
react-native: 0.47.2

## Steps to Reproduce
react-native-git-upgrade

## Expected Behavior
upgrade succeeds

## Actual Behavior
upgrade hangs

**Comment by alice-em** [comment]
I'm getting the same issue on `Ubuntu 17.10 & 18.04`

    react-native-cli: 2.0.1
    react-native: 0.55.3

I get this issue with `react-native link`
