### ISSUE TITLE
Inconsistent velocity time units in animation

### ISSUE THREAD

**Issue by dgreensp** [facebook/react-native#18953]
It seems to be the case that:
* PanResponder returns velocity in dp/millisecond
* Animated.spring takes initial velocity in dp/second
* Animated.decay takes initial velocity in in dp/millisecond

This means that to feed the velocity of a gesture into a spring animation, you have to multiply by 1000, but there is no documentation to indicate this.

I presume it's too late to change the API, but could we at least put the units of each velocity in the API documentation?

**Comment by autoric** [comment]
@dgreensp Thank you very much for calling this out. I've been super confused by how to cleanly transition velocity between chained animations and this was a big part of the problem.

Ugh.
