### ISSUE TITLE
Add ability to focus the <WebView>

### ISSUE THREAD

**Issue by vladikoff** [facebook/react-native#18965]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment

Environment:
  OS: macOS High Sierra 10.13.2
  Node: 8.10.0
  Yarn: 1.3.2
  npm: 5.8.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.1 AI-173.4697961

Packages: (wanted => installed)
  react: ~16.2.0 => 16.2.0
  react-native: ~0.54.2 => 0.54.2

## Expected Behavior

The https://facebook.github.io/react-native/docs/webview.html WebView component should have a way to autofocus itself. Once the autofocus is triggered, the HTML elements that have `autofocus` attributes will be focused in the loaded <WebView>

## Actual Behavior

No API available at this time

**Comment by vladikoff** [comment]
@react-native-bot sure buddy, here you go:

```
Environment:
  OS: macOS High Sierra 10.13.2
  Node: 8.10.0
  Yarn: 1.3.2
  npm: 5.8.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.1 AI-173.4697961

Packages: (wanted => installed)
  react: ~16.2.0 => 16.2.0
  react-native: ~0.54.2 => 0.54.2
```

**Comment by vladikoff** [comment]
Also filed under https://stackoverflow.com/questions/50024656/how-to-focus-a-webview-in-react-native

**Comment by hbarylskyi** [comment]
@vladikoff I think you should try changing react-native versions in issue description for the bot to understand you :)

**Comment by ocyedwin** [comment]
@vladikoff I'm also facing issue and wonder if you've found any solution.

**Comment by vladikoff** [comment]
@ocyedwin One solution i found was recompiling react-native from source and tweaking the WebView code so it requests focus

**Comment by ocyedwin** [comment]
@vladikoff Nice! Any intention sharing the tweak or even doing a PR?

**Comment by vladikoff** [comment]
@ocyedwin posted a solution in https://stackoverflow.com/a/50635924/216672 Let me know if you need help

**Comment by TryImpossible** [comment]
@vladikoff There is a solution in [react-native-enhance-webview](https://github.com/TryImpossible/react-native-enhance-webview)，you can know it if you need

**Comment by vladikoff** [comment]
@TryImpossible nice! thank you
