### ISSUE TITLE
[Code Style] automatic listener setup for componentWillMount & componentWillUnmount

### ISSUE THREAD

**Issue by kostiakoval** [facebook/react-native#1896]
If I want to handle some events, I need to register and unregister manually now
```js
 componentWillMount() {
    SomeComponent.addEventListener('event', this._event);
  }
  componentWillUnmount() {
     SomeComponent.removeEventListener('event', this._event);
  }
  _event() {
     ...
  }
```

Very often we forgot to unregister from events listening (a notification on iOS) and it could lead to dangerous result.
The component could automatically unregister from events when its become inactive (gets unmounted) 
Swift implementation - https://gist.github.com/jverkoey/dfa473635a810ab436d3

Some ideas for implementation, not perfect :)

```js
componentLifeBindings() {
   return [ {SomeComponent, 'event', this._event},
            {View, 'move', this._hadleMovement}]
}
```

**Comment by nicklockwood** [comment]
You can use mixins to manage lifecycle stuff like this (this is how timers are handled). Maybe @ericvicenti can provide more info?

**Comment by brentvatne** [comment]
Mixins are good for this, see [react-timer-mixin](https://github.com/reactjs/react-timer-mixin/blob/master/TimerMixin.js) for example.

Alternatively, you could use some kind of compositional technique like ES7 decorators or a component enhancing functions. For example, check out [@johanneslumpe's blog post about adding a gesture decorator](http://blog.lum.pe/gesture-detection-in-react-native/).

**Comment by christopherdro** [comment]
This might help. https://github.com/facebook/react-native/blob/8b93b99d4a769f86fffc95d65434f2f6a3fd827d/Libraries/Components/Subscribable.js

According to @ericvicenti from a previous issue...

"Subscribable.Mixin is something we use internally to make sure nobody forgets to unsubscribe to an emitter from a component on unmount. The mixin will automatically remove subscriptions added with this.addListenerOn"

**Comment by brentvatne** [comment]
Nice one @christopherdro :smile:

**Comment by kostiakoval** [comment]
Thanks for answers! Great resources

**Comment by browniefed** [comment]
@brentvatne still keep this open with all the solutions out there like Subscribable?

**Comment by brentvatne** [comment]
@browniefed - yeah I think those solutions are good, close seems appropriate!
