### ISSUE TITLE
Unable to load script from assets 'index.android.bundle'.make sure you bundle is packaged correctly or you're running a packager server................... How to fix it????????? Still not working !!!!!!!!!!!

### ISSUE THREAD

**Issue by moogiis** [facebook/react-native#18963]
![31073328_925833544255116_9219499874729328640_n](https://user-images.githubusercontent.com/21235622/39066956-8e35dcb8-4509-11e8-8ab3-776be3e26a58.png)

**Comment by kanyo33** [comment]
Not sure if that's the best solution, but: 
npm i core-js --save
worked.

**Comment by moogiis** [comment]
Thank you. But its still not working :(

**Comment by Reyske** [comment]
Maybe less punctuation marks and some more information will help.
