### ISSUE TITLE
App react works on simulator but not on IOS device

### ISSUE THREAD

**Issue by americoleonardo** [facebook/react-native#18966]
react: 16.0.0-alpha.12
react-native: "0.46.4
react-native-cli: "2.0.1

Xcode version: 9.2

Device IOS Version: 11.3
Device Simulator version: 11.2

- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)

I'm having trouble generating the application on the iphone 8 device. When I'm programming in the simulator, the application generates the bundle correctly, but when doing the same process for device, it returns me the following error:

'React/RCTUIManagerUtils.h' file not found

<img width="636" alt="screen shot 2018-04-21 at 01 14 00" src="https://user-images.githubusercontent.com/5607350/39080311-e7a69236-4501-11e8-9849-87afebe34dfd.png">

Someone has gone through this type of error and can help me?

**Comment by gidox** [comment]
any solutions ?, having same problem...
