### ISSUE TITLE
Cannot add task ':app:copyDebugIconFonts' as a task with that name already exists.

### ISSUE THREAD

**Issue by wangmao11111** [facebook/react-native#18970]
- [ ] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [ ] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [ ] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

**Comment by wangmao11111** [comment]
Cannot add task ':app:copyDebugIconFonts' as a task with that name already exists.

**Comment by RamashishTomar** [comment]
* Where:
Script 'D:\ramashish\Smap\Proj\SMAP\node_modules\react-native-vector-icons\fonts.gradle' line: 29
which is- 
 def currentFontTask = tasks.create(
                name: "copy${targetName}IconFonts",
                type: Copy) {


* What went wrong:
Cannot add task ':app:copyDebugIconFonts' as a task with that
name already exists.

D:\ramashish\Smap\Proj\SMAP>react-native info

  React Native Environment Info:
    System:
      OS: Windows 7
      CPU: (4) x64 Intel(R) Core(TM) i3 CPU         530  @ 2.93GHz
      Memory: 1.38 GB / 5.80 GB
    Binaries:
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.5.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5199772
