### ISSUE TITLE
Use Navigator simply

### ISSUE THREAD

**Issue by to175** [facebook/react-native#18975]
Hello.
I am doing an Android+IOS app. I want to learn Navigation first but I have errors. I have installed and created my first project 2 or 3 days ago. Everything is up to date.
 
I have first tried to import Navigator from react-native but it said it is deprecated.... awesome ! Even with adding the import "...deprecated" it doesn't work. So I came to official page where it sais I have to install some other things...

## Environment
OS: Windows 10
Node: 8.9.2
Yarn: 1.5.1
npm: 5.8.0
Watchman: 4.9.0
Xcode: Xcode 9.1 Build version 9B55
Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
react: 16.3.1 => 16.3.1
react-native: 0.55.2 => 0.55.2

> C:\Users\theo1\AwesomeProject>react-native info
> 'react-native' n’est pas reconnu en tant que commande interne
> ou externe, un programme exécutable ou un fichier de commandes.
> 
> C:\Users\theo1\AwesomeProject>npm react-native info
> 
> Usage: npm <command>
> 
> where <command> is one of:
>     access, adduser, bin, bugs, c, cache, ci, completion,
>     config, ddp, dedupe, deprecate, dist-tag, docs, doctor,
>     edit, explore, get, help, help-search, i, init, install,
>     install-test, it, link, list, ln, login, logout, ls,
>     outdated, owner, pack, ping, prefix, profile, prune,
>     publish, rb, rebuild, repo, restart, root, run, run-script,
>     s, se, search, set, shrinkwrap, star, stars, start, stop, t,
>     team, test, token, tst, un, uninstall, unpublish, unstar,
>     up, update, v, version, view, whoami
> 
> npm <command> -h     quick help on <command>
> npm -l           display full usage info
> npm help <term>  search for help on <term>
> npm help npm     involved overview
> 
> Specify configs in the ini-formatted file:
>     C:\Users\theo1\.npmrc
> or on the command line via: npm <command> --key value
> Config info can be viewed via: npm help config
> 
> npm@5.8.0 C:\Users\theo1\AppData\Roaming\npm\node_modules\npm

## Steps to Reproduce
I have opened the console and typed _cd AwesomeProject_ then I did : _npm install --save react-navigation_ in the AwesomeProject file.

## Expected Behavior
I don't know, maybe a working Navigation...

## Actual Behavior
I have errors, here are the logs : **https://pastebin.com/Bx6kDxNs**

What is the problem please ? Why I cannot use this basic (and so important) feature easily ?

Thx for your help

**Comment by to175** [comment]
I have added the template (I can't run the environment but it is the last release)

**Comment by to175** [comment]
I'm speaking to a bot, awesome....

**Comment by timwangdev** [comment]
`react-native` command should be available after run `npm install -g react-native-cli`

Please try to follow https://facebook.github.io/react-native/docs/getting-started.html and https://reactnavigation.org/ docs.
