### ISSUE TITLE
[0.55.3][iOS] Can not fetch http

### ISSUE THREAD

**Issue by someok** [facebook/react-native#18978]
## Environment

Environment:
>  OS: macOS High Sierra 10.13.4
  Node: 9.8.0
  Yarn: 1.5.1
  npm: 5.8.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.1 AI-173.4670197

Packages: (wanted => installed)
>  react: 16.3.1 => 16.3.1
  react-native: 0.55.3 => 0.55.3

info.plist:
```
<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>
```

## Steps to Reproduce
```
 fetch('http://www.qq.com/')
      .then(res => {
        console.log('res', res);
        return res.text();
      })
      .then(text => {
        console.log('text', text);
      })
```

## Expected Behavior

>html source

## Actual Behavior

> text: undefined

**Comment by uzarubin** [comment]
iOS blocks http requests, and it would be best to whitelist any unsecured domains by following instructions here: https://facebook.github.io/react-native/docs/integration-with-existing-apps.html#test-your-integration

**Comment by Caballarii** [comment]
this is because www.qq.com use charset gb2312, in old version it's ok, but now in 0.55 it brokes

**Comment by woshi82** [comment]
https://github.com/facebook/react-native/issues/19818#issuecomment-407057029 This maybe helped.
