### ISSUE TITLE
Improve install of templates from places other than `npm` registry

### ISSUE THREAD

**Issue by piranna** [facebook/react-native#18973]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

When trying to install a project template from other place than published as a `npm` package (github forks, local filesystem, local tarfile, http server...) I can't be able to do it due to several problems. Debuging them, I get to the conclussion the problem is at https://github.com/facebook/react-native/blob/26684cf3adf4094eb6c405d345a75bf8c7c0bf88/local-cli/generator/templates.js#L112-L120, not processing the template name correctly. Problems I've found in this code snippet are:

- lack of support to download a git project subpath (seems a problem in `npm` not supporting mono-repos)
- `templateName` gets not cleaned, file extension should be removed
- `templateName` can't be different of the package name at the template `package.json` file, correct name should be extracted once the template is installed
- when installed from `npm`, `installPackage` is just a concatenation of the string `react-native-template-` and the provided template name, not allowing to use scoped packages as templates. Provided template should be checked and splitted, and the scoped prefixed to the generated `templateName`

## Environment
```
Environment:
  OS: Linux 4.13
  Node: 9.11.1
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: N/A
  Android Studio: 3.1 AI-173.4697961

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.2 => 0.55.2
```
## Steps to Reproduce
Try to init a React Native project using a template from a git mono-repo, or from a local filesystem folder, or from a tarfile on the local filesystem or a web server, or from a scoped `npm` package.

## Expected Behavior
All the provided methods should be able to correctly install the provided template.

## Actual Behavior
All of them fails.

**Comment by piranna** [comment]
This issue still needs community's attention. Can someone review it?

**Comment by piranna** [comment]
Yes, it still happens.

**Comment by piranna** [comment]
Still happening with React Native 0.57.8.

**Comment by grabbou** [comment]
@piranna, would you be open to move this to CLI repository and work together with us to improve this support? We are working on `init` right now and templates support is on our radar. Our team doesn't check this repository actively and issues like this can skip from our attention.

**Comment by piranna** [comment]
Hi @grabbou, where's the CLI repository? How can I be able to move this?

**Comment by grabbou** [comment]
It's here -> https://github.com/react-native-community/react-native-cli/

I am afraid you just need to reopen issues there, close the ones here and (optionally), submit a PR again.

**Comment by rickhanlonii** [comment]
Closing as this should be filed in the CLI as noted above 👌
