### ISSUE TITLE
Missing peers ->  @babel/plugin-check-constants@7.0.0-beta.38 requires a peer of @babel/core@7.0.0-beta.38 but none was installed.

### ISSUE THREAD

**Issue by marcoroche** [facebook/react-native#18989]
- [X] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [X] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [X] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

I have just installed React Native following the instructions I have created the first project with create-react-native-app and I run "npm start" and all is OK but I can't add any package that I need for my project, I constantly have this error and if I install  "npm install @babel/core --save" it's worse I have more missing peers. 

## Environment
Environment:
  OS: Windows 10
  Node: 9.11.1
  Yarn: Not Found
  npm: 4.6.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.0 => 16.3.0
  react-native: ~0.54.1 => 0.54.4

## Steps to Reproduce
create-react-native-app test_splash
cd test_splash
npm install react-native-i18n --save
OR 
npm install react-native-localization --save

## Expected Behavior
No warning

## Actual Behavior
@babel/plugin-check-constants@7.0.0-beta.38 requires a peer of @babel/core@7.0.0-beta.38 but none was installed.

**Comment by marcoroche** [comment]
I don't know if there is an automatic way to update. I did the change manually so there no more dependencies error but it does not run 

```
I have a console error: "React Native version mismatch'

Javascript version: 0.55.3
Native version: 0.54.2
```

Here is the package.json I created. 
```

{
  "name": "testRN1",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "react-native-scripts": "1.13.2",
    "jest-expo": "26.0.0",
    "react-test-renderer": "16.3.1"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "jest"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "eslint": "^4.19.1",
    "expo": "^26.0.0",
    "react": "16.3.1",
    "react-native": "~0.55.3"
  }
}

```

**Comment by cglacet** [comment]
With `react-native@0.56.0-rc` there is still an explicit dependency to `@babel/core@7.0.0-beta.47`. Only solution I found to this is to use an older version `react-native@0.55.6`.

**Comment by 0paIescent** [comment]
Did you mean `react-native@0.55.4`? Because 0.55.6 isn't a valid version number.

**Comment by 0paIescent** [comment]
I was having a similar issue, and updating `babel-preset-react-native` to `v5.0.2` fixed all the missing dependency errors.

**Comment by cglacet** [comment]
Yes sorry, `react-native@0.55.4` is the version I have.

**Comment by kelset** [comment]
As  @0paIescent points out, this can be fixed by upgrading. Please let me know if it's not the case and I'll reopen

**Comment by GBGitUser** [comment]
Hi - I'm having this exact same problem. I am on version react-native-cli: 2.0.1, react-native: 0.57.3 - will try @0paIescent suggestion above but just to note I am on post 0.55 version.
