### ISSUE TITLE
Chain of errors in Mac

### ISSUE THREAD

**Issue by josedev123** [facebook/react-native#18981]
## Environment
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.11.1
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Not Found
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.3 => 0.55.3

## Steps to Reproduce
react-native run-android

## Actual Behavior
I got a chain of errors trying to build my react native app, first with java version (downgraded to 1.8.0), then got few more errors, managed to solve with help form github. This is what I got now, really frustrated. please help me to get it run. 

Or help me to clean everything and start from beginning. This is the forth time I am trying to reun a react native app.

<img width="315" alt="screen shot 2018-04-22 at 3 50 01 pm" src="https://user-images.githubusercontent.com/38633978/39099224-f28c7eba-4644-11e8-8af1-6ec95976fc81.png">
<img width="320" alt="screen shot 2018-04-22 at 3 53 51 pm" src="https://user-images.githubusercontent.com/38633978/39099253-690b0570-4645-11e8-973b-0e27cc3cfd07.png">
<img width="315" alt="screen shot 2018-04-22 at 3 54 00 pm" src="https://user-images.githubusercontent.com/38633978/39099254-692a4cdc-4645-11e8-8355-168e9e8c9dc3.png">

**Comment by DavidNorena** [comment]
I had the same error yesterday when i was testing the last version of metro...
