### ISSUE TITLE
[Navigator] How to remove route from navigator history after transition

### ISSUE THREAD

**Issue by olivierlesnicki** [facebook/react-native#1898]
i'm on route A, I want to navigate to route B (with transition) and then remove A from the history (and unmount it).

Is it possible?

the use case is I have a video playing on one of route A, I want the component playing the video to unmount post transition.

**Comment by chirag04** [comment]
You can try ``replace``. Not sure if animation is going to work for replace though.

**Comment by brentvatne** [comment]
@olivierlesnicki - you can add a listener to the navigator on the view with the video, then disable the video when the view transition is complete. [See this](https://facebook.github.io/react-native/docs/navigator.html#ondidfocus) (notice that the prop is deprecated). You can set some state when it becomes focused, and then when another route gets focus, update that state to indicate that it is not focused.

**Comment by olivierlesnicki** [comment]
Ah I see. Thanks for this.
