### ISSUE TITLE
InputAccessoryView renders on top of YellowBox warnings

### ISSUE THREAD

**Issue by davidpaulsson** [facebook/react-native#18987]
When using InputAccessoryView to create a sticky input, it renders on top and covers the "dismiss" and other options, making it impossible to close.

## Environment
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.11.1
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.2 => 0.55.2

## Steps to Reproduce
Create a sticky keyboard input with InputAccessoryView, get a warning.

## Expected Behavior
Yellowbox warning options (minimize, dismiss & dismiss all) should be reachable.

## Actual Behavior
![img_2351](https://user-images.githubusercontent.com/779321/39111458-7c430db4-46d5-11e8-8643-57ae3a469f02.PNG)

[Here's a video](https://www.dropbox.com/s/6saawwila3osjq4/InputAccessoryView-YellowBox.mp4?dl=0) (Dropbox, 4.9 MB)

**Comment by tapz** [comment]
If the navigation bar background is set to transparent, the yellowbox appears below the bar and is not clickable. One should be able to set the location or margin for the box to prevent this. Also, yellowbox does not respect iPhone X safe areas.

**Comment by orta** [comment]
Confirmed, still exists. 

I used this in a new RN app:

```js
import * as React from 'react';
import { Text, View, StyleSheet, InputAccessoryView, ScrollView, TextInput, Button } from 'react-native';
import { Constants } from 'expo';

// You can import from local files
import AssetExample from './components/AssetExample';

// or any pure javascript modules available in npm
import { Card } from 'react-native-paper';

 class UselessTextInput extends React.Component {
  constructor(props) {
    super(props);
    this.state = {text: 'Placeholder Text'};
  }

  render() {
    const inputAccessoryViewID = "uniqueID";
    return (
      <View>
        <ScrollView keyboardDismissMode="interactive">
          <TextInput
            style={{
              padding: 10,
              paddingTop: 50,
            }}
            inputAccessoryViewID={inputAccessoryViewID}
            onChangeText={text => this.setState({text})}
            value={this.state.text}
          />
        </ScrollView>
        <InputAccessoryView nativeID={inputAccessoryViewID}>
          <View style={{height: 30, backgroundColor: "red"}}>
            <Button onPress={() => console.warn("OK")} title="Reset Text"
          />
          </View>
        </InputAccessoryView>
      </View>
    );
  }
}

export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.paragraph}>
          Change code in the editor and watch it change on your phone! Save to get a shareable url.
        </Text>
        <Card>
          <UselessTextInput />
        </Card>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    paddingTop: Constants.statusBarHeight,
    backgroundColor: '#ecf0f1',
    padding: 8,
  },
  paragraph: {
    margin: 24,
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
  },
});

```

Looks like:

<img width="584" alt="Screen Shot 2019-03-19 at 4 43 20 PM" src="https://user-images.githubusercontent.com/49038/54624927-3a7e8300-4a66-11e9-9397-cbca3f8328ad.png">

**Comment by davidleee** [comment]
And it also renders on top of any views wrapped within a `<Modal>`, any way to avoid this behavior?
