### ISSUE TITLE
Image onLoad never fires in iOS

### ISSUE THREAD

**Issue by feliperaul** [facebook/react-native#18992]
<Image> onLoad={} callback never fires in iOs, but it does in Android. 

## Environment
Using expo.io sdk 25, which means RN version 0.52.0. 

## Steps to Reproduce
`<Image source={this.props.source} onLoad={()=> console.log('I loaded')}>`

You'll never see this log message in iOs, but you'll see it in Android.

We wanted to use this callback to change the state to hide the spinner (ActitvityIndicator), but i never fires in iOS. 

## Expected Behavior
The callback to fire when the image loaded. 

## Actual Behavior
Never fires.

**Comment by StanislavMayorov** [comment]
It's still reproduced on v0.56.0
