### ISSUE TITLE
How to make apk file

### ISSUE THREAD

**Issue by mojtabamarashee** [facebook/react-native#18991]
How to make apk file?
this is my app folder structure **there is no android folder**:

App.js    App.test.js    package.json       README.md
app.json  node_modules/  package-lock.json

**Comment by kunalqss** [comment]
@mojtabamarashee Check this out -> [Preparing a React Native Android App for Production](https://android.jlelse.eu/preparing-a-reach-native-android-app-for-production-f063413d5633)

**Comment by mojtabamarashee** [comment]
as the link says:
I installed react-native using the following commands:
`npm install -g react-native
`
now I got the following error:
```
$ react-native init nativeApp
Looks like you installed react-native globally, maybe you meant react-native-cli?
To fix the issue, run:
npm uninstall -g react-native
npm install -g react-native-cli

whats the problem?
```

**Comment by kunalqss** [comment]
Check [this](https://www.npmjs.com/package/react-native-cli) out. The very first line makes it clear.

> React Native is distributed as two npm packages, react-native-cli and react-native. The first one is a lightweight package that should be installed globally (npm install -g react-native-cli), while the second one contains the actual React Native framework code and is installed locally into your project when you run react-native init.

**Comment by mojtabamarashee** [comment]
thanks alot @kunalqss
