### ISSUE TITLE
Remote Debugger Not Working

### ISSUE THREAD

**Issue by sathishu37** [facebook/react-native#19003]
- [Yes ] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [ Yes] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [Yes ] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment

Environment:
  OS: Linux 4.10
  Node: 8.9.4
  Yarn: Not Found
  npm: 5.8.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: ^16.3.1 => 16.3.1
  react-native: ^0.55.3 => 0.55.3

## Expected Behavior
 When I turn on remote debugger it should be working properly.

## Actual Behavior
 When I turn on remote debugger it should Not work properly.

![issue](https://user-images.githubusercontent.com/30067630/39190312-f48f98f6-47f1-11e8-955d-6e6058a78b82.png)

**Comment by pierreneter** [comment]
try use localhost instead of xip.io

**Comment by ravirajn22** [comment]
I can't just understand, in every major release they say 'remote debugger is fixed'. But the problem still persists sometimes like,

1. We need to close and open the debugger 
2. Change manually the URL to work
3. Debugger opened in iOS does not work with Android

In v0.44.0 it was working flawlessly. It all happens in the latest versions of react native (> v0.55.0).

Add also Hot Reloading, which does not work when you have done manual reload of the app in the v0.55.0
