### ISSUE TITLE
How to get fps programatically

### ISSUE THREAD

**Issue by rekha110254** [facebook/react-native#19013]
How to get fps programatically which is shown in `show perf monitor` of developer tools?

react-native: 0.51
react: 16

**Comment by rekha110254** [comment]
@react-native-bot i am using react-native 0.51 and unable to find RCTPerfMonitor in react-native/Libraries/Performance/RCTPerfMonitor.

How can i get JS FPS logs programatically?

Environment:
OS: macOS High Sierra 10.13.3
Node: 8.9.4
Yarn: 1.3.2
npm: 5.6.0
Watchman: 4.9.0
Xcode: Not Found
Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
react: 16.0.0 => 16.0.0
react-native: 0.51.1 => 0.51.1

**Comment by timwangdev** [comment]
Please check https://github.com/facebook/react-native/blob/c6b96c0df789717d53ec520ad28ba0ae00db6ec2/Libraries/Utilities/PerformanceLogger.js
