### ISSUE TITLE
Deploying React native ios app to test flight.

### ISSUE THREAD

**Issue by nisharafic001** [facebook/react-native#19014]
Hi,

I have developed app using react native. this works well in both iOS and android simulator. I have moved this to testflight and facing following error.

Steps followed:
#1. react-native run-ios --configuration release
#2. product->build - Success
#3. product->archive->upload to playstore->success
#4. App appears in test flight - ok
#5. install app from testflight to real device - success
#6. when i open the app in real device. it open react-native screen and shows black screen and closes the app. - error

how can i resolve this. can any one advice me on this. thank you.

## Environment
"react": "16.0.0",
 "react-native": "0.50.3",

## Expected Behavior
no crash
## Actual Behavior
App runs in Release mode.

## Debug mode:
![simulator screen shot - iphone x - 2018-04-21 at 00 13 42](https://user-images.githubusercontent.com/37332180/39255063-34fbc12a-48de-11e8-890c-5eb5a519a763.png)

## Release mode:
![simulator screen shot - iphone 6 - 2018-04-25 at 23 15 30](https://user-images.githubusercontent.com/37332180/39255251-a5f95766-48de-11e8-9f67-d3e50cd6a97b.png)

and then closes the screen. when i run **$ react-native run-ios --configuration Release** in terminal

**Comment by mikaoelitiana** [comment]
I think there is a way to get the log from the device when you connect it to your cimputer. That would be a nice place tp start investigations.
