### ISSUE TITLE
How to get fps programatically which is show in `show perf monitor` in developer tools?

### ISSUE THREAD

**Issue by Janardhanrao** [facebook/react-native#19012]
- [ ] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [ ] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [ ] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

**Comment by rekha110254** [comment]
@react-native-bot  i am using react-native 0.51 and unable to find RCTPerfMonitor in react-native/Libraries/Performance/RCTPerfMonitor. 

How can i get JS FPS logs programatically?

**Comment by timwangdev** [comment]
Duplicated #19012

**Comment by AngelVenchev** [comment]
Why is this issue closed? It's marked duplicated but it's pointing to itself. I am also interested in getting this kind of information
