### ISSUE TITLE
React native new project error

### ISSUE THREAD

**Issue by mrkhoros** [facebook/react-native#19020]
According to [https://facebook.github.io/react-native/docs/getting-started.html](https://facebook.github.io/react-native/docs/getting-started.html) 
to make a new react native project I should run `npm install -g create-react-native-app`
and then `create-react-native-app AwesomeProject` but in return I get 

> Done in 16.45s.
> (node:4912) UnhandledPromiseRejectionWarning: Error: Cannot find module 'core-js/library/fn/json/stringify'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:497:25)
>     at Module.require (internal/modules/cjs/loader.js:626:17)
>     at require (internal/modules/cjs/helpers.js:20:18)
>     at Object.<anonymous> (C:\Users\shaha\Desktop\AwesomeProject\node_modules\babel-runtime\core-js\json\stringify.js:1:93)
>     at Module._compile (internal/modules/cjs/loader.js:678:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
>     at Module.load (internal/modules/cjs/loader.js:589:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:520:3)
> (node:4912) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:4912) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

what have I done so far to rectify this matter , uninstalled and remove node js , and restarting the windows after each installation , cmd is running in admin mode as well

please tell me how to overcome this issue

**Comment by timwangdev** [comment]
Hi, could you fire a issue to https://github.com/react-community/create-react-native-app instead?
