### ISSUE TITLE
Android keeps variables initialized from before dismissing/closing the app 

### ISSUE THREAD

**Issue by MKLOL** [facebook/react-native#19028]
- [X] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [X] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [ ] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

Android doesn't seem to reset the javascript context when you dismiss the app and relaunch it. Some variables, that are only initialized once at startup, are already initialized if you close the app and quickly restart it. This doesn't happen on iOS, and it doesn't happen on android if you wait for about a second after you dismiss the app. (I also get more errors/warnings, telling me some listeners are misbehaving, though I create those listeners only after the user logs in, and this happens before the login screen). 
The device I used is a galaxy S7.

## Environment
Environment:
OS: macOS High Sierra 10.13.4
Node: 8.9.4
Yarn: 1.3.2
npm: 5.6.0
Watchman: 4.9.0
Xcode: Xcode 9.3 Build version 9E145
Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
react: 16.2.0 => 16.2.0
react-native: ^0.55.3 => 0.55.3

## Steps to Reproduce
I have some code that basically looks like this, initialized is ONLY called when the program starts

```
let realmThing: Realm | undefined;

const RealmThing = {
    initialize: ) => {
        if (realmThing !== undefined) {
            throw Error("realm Already initialized); // This happens after dismiss and quick relaunch
        }
        realmThing = new Realm(...);
    },
```
If you dismiss the app / close the app and then open it fast enough, it will throw that error. (Note: If you wait 1 second after dismissing, it doesn't happen)
## Expected Behavior
The variable should not be initialized. 

## Actual Behavior
The variable is initialized.

**Comment by MKLOL** [comment]
Yes, it still happens in the latest version:

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.9.4
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: ^0.55.3 => 0.55.3

**Comment by bjlaub** [comment]
+1, having this issue as well. This seems like the same problem as #18764. Any ideas?

**Comment by jclalala** [comment]
+1, this happens to us too. We've tried 0.53 as well as 0.55 and the problem remain. We simply added a "console.log" on root component (App.js); by clicking hardware back then the APP to resume again we see the same console.log printed.

**Comment by bjlaub** [comment]
@jclalala @MKLOL i think the core issue here is that React Native will potentially attach an _existing_ javascript context to a new activity; when it does that, it always renders the "root" application from the top, as if it was starting it anew.

In my case, the issue happens to be that I had erroneously tied some global state (like a redux store) to the root component's lifecycle events, assuming that once the root component was created that it wouldn't get unmounted. On Android, it's possible to destroy the main activity without destroying the application.

One workaround (nuclear option?) is to override `ReactActivity#onDestroy` in your "main" activity and call `getReactInstanceManager().destroy();` to forcibly delete the JS context when the activity is destroyed. But this seems pretty undesireable from a user standpoint? I ended up re-factoring my javascript code under the assumption that the root component can get destroyed/re-created within the _same_ JS context, and should be able to restore itself based on any global state already in memory.

However, I think this assumption only holds if it's really true that the JS context stays alive regardless of the activity lifecycle? This may not be the case in all instances...
