### ISSUE TITLE
React Native ERROR :  "Cannot set property 'volume' of null"

### ISSUE THREAD

**Issue by meazou75** [facebook/react-native#19021]
When i try to run my app simulator with react-native run-ios on Osx, the application start well but my debugger at http://localhost:8081/debugger-ui/ doesn't show console.log and print this error : 

(index):92 Uncaught TypeError: Cannot set property 'volume' of null
    at Object.render ((index):92)
    at Object.setState ((index):46)
    at WebSocket.ws.onopen ((index):150)

My version:

"dependencies": {
    "react": "16.3.1",
    "react-native": "0.55.3",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0"
  }

Thanks for your help :) <3

**Comment by timwangdev** [comment]
Closing in favor of #19022

**Comment by westandy** [comment]
In your app's `ios` folder, look for a file called <yourAppName>.xcscheme.  There's a property called `runnableDebuggingMode = "0"` that I set to "1".  And all worked as the directions tell you.

**Comment by mustafaskir** [comment]
any help for android , got same issue :- @westandy

**Comment by MaheshSuranga** [comment]
same issue got in android debugger in chrome browser

**Comment by MaheshSuranga** [comment]
> When i try to run my app simulator with react-native run-ios on Osx, the application start well but my debugger at http://localhost:8081/debugger-ui/ doesn't show console.log and print this error :
> 
> (index):92 Uncaught TypeError: Cannot set property 'volume' of null
> at Object.render ((index):92)
> at Object.setState ((index):46)
> at WebSocket.ws.onopen ((index):150)
> 
> My version:
> 
> "dependencies": {
> "react": "16.3.1",
> "react-native": "0.55.3",
> "react-redux": "^5.0.7",
> "redux": "^4.0.0"
> }
> 
> Thanks for your help :) <3

disable all extensions on chrome web browser solve my problem.

**Comment by xiaowang1314** [comment]
Redux DevTools这个扩展工具禁用就可以了

**Comment by ZerozAndOnes** [comment]
In addition to westandy's solution, I had to restart the development server to make it work.

**Comment by allanjsx** [comment]
Open the /debugger-ui session in private/Incognito mode, then run `react-native run-ios` or `react-native run-android` again works for me.
