### ISSUE TITLE
React Native ERROR : "Cannot set property 'volume' of null"

### ISSUE THREAD

**Issue by meazou75** [facebook/react-native#19022]
- [X] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [X] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [X] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

When i try to run my app simulator with react-native run-ios on Osx, the application start well but my debugger at http://localhost:8081/debugger-ui/ doesn't show console.log and print this error :

(index):92 Uncaught TypeError: Cannot set property 'volume' of null
at Object.render ((index):92)
at Object.setState ((index):46)
at WebSocket.ws.onopen ((index):150)

## Environment
Environment:
  OS: macOS High Sierra 10.13.1
  Node: 6.11.3
  Yarn: Not Found
  npm: 3.10.10
  Watchman: Not Found
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.3 => 0.55.3

## Steps to Reproduce
I used the basic app created by React native init

## Expected Behavior
Show a console.log in console

## Actual Behavior
Show nothing from console.log but show :

(index):92 Uncaught TypeError: Cannot set property 'volume' of null
at Object.render ((index):92)
at Object.setState ((index):46)
at WebSocket.ws.onopen ((index):150)

**Comment by meazou75** [comment]
Solve ! CMD + D and solver JS Remotly 

https://facebook.github.io/react-native/docs/debugging.html

**Comment by HappyerKing** [comment]
I'm having the same issue with react-native react-native@0.44.3

**Comment by klapperkopp** [comment]
Same here when . I activate remote debugging. It sometimes comes up and sometimes not and I couldn't figure out why yet... Sometimes, instead of the above error message it shows "Another debugger is already connected", but none is running.

Node: 9.11.1
NPM: 5.6.0
React-Native: 0.53.0
React-Native-Cli: 2.0.1
XCode: Version 9.3 (9E145)

**Comment by westandy** [comment]
In your app's `ios` folder, look for a file called <yourAppName>.xcscheme.  There's a property called `runnableDebuggingMode = "0"` that I set to "1".  And all worked as the directions told me for debugging my RN app.

**Comment by ReneCode** [comment]
@westandy That works for me - Thank you.

**Comment by mohini14** [comment]
https://github.com/facebook/react-native/issues/19022#issuecomment-398563887
this is really  useful

**Comment by likern** [comment]
What about fixing this for Android? Will [this comment](https://github.com/facebook/react-native/issues/19022#issuecomment-398563887) work?

**Comment by MikeB2012** [comment]
@likern: my experience has been that is also works on Android ie. make the correction in the ios/ and the error disappeared.

**Comment by c-moss-talk** [comment]
I had this error log while I had two packagers running.
