### ISSUE TITLE
React Native - App Resume Bug [Duplicate Activity on top]

### ISSUE THREAD

**Issue by victorkvarghese** [facebook/react-native#19035]
Hi,

I started using my react native app. Gone to background and resumed after sometime (Open app from appdrawer). 

## Environment
Android
Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.8.1
  Yarn: 1.2.1
  npm: 5.4.2
  Watchman: 4.9.0
  Xcode: Xcode 9.1 Build version 9B46
  Android Studio: 3.1 AI-173.4697961

Packages: (wanted => installed)
  react: ^16.3.0-alpha.1 => 16.3.0-alpha.2
  react-native: ^0.54.2 => 0.54.2
## Expected Behavior
App should work normally

## Actual Behaviour [Some times]

A new activity / duplicate activity above the existing activity . You can see another status bar and a padding at the top . Pressing hardware back button dismisses the activity and show the original activity. I am seeing this behaviour couple of times.. (I don't have any steps to reproduce this .. happens when app is resumes)

## Reproduce issue
Open your app .. and go to background.
wait for sometime and open app from app drawer again

Any workaround for this issue or fixes??

any thing to do with launchMode in Android?

**Comment by victorkvarghese** [comment]
@react-native-bot Updated

**Comment by poberwong** [comment]
have same issue

**Comment by victorkvarghese** [comment]
@poberwong I added `  android:launchMode="singleTask"` to MainActivity in Android Manifest

Seems like issue was resolved .. not sure though

**Comment by boliveira** [comment]
Hi,

I was having the same problem and it's an Android thing. If you start the react native app with react-native run-android, it will launch the activity with a different intent than if it was launched via tapping the app icon on home screen. So, the default behavior on Android is to just add another activity when the intent launching it is different than the previous one. Just close the app on recents view and launch again and it will be fine.
