### ISSUE TITLE
Android view shadow increase while using same elevation

### ISSUE THREAD

**Issue by slorber** [facebook/react-native#19033]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [X] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [X] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment

```
Scanning folders for symlinks in /../client-demo/node_modules (20ms)

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.7.0
  Yarn: 1.2.1
  npm: 5.4.2
  Watchman: 4.7.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: https://github.com/expo/react-native/archive/sdk-26.0.0.tar.gz => 0.54.2
```

## Steps to Reproduce

deleted: sorry the original code was copied from https://github.com/facebook/react-native/issues/15832 and the snack was actually an hello world

## Expected Behavior

All shadows should be the same

## Actual Behavior

The shadow is increasing in a weird way:

![](https://user-images.githubusercontent.com/7360440/30111789-59144198-930f-11e7-898a-14bd215e3942.png)

**Comment by slorber** [comment]
This issue is there for a long time. It has already been reported but always closed by stale bot while it was still reproducible. I'm reopening it as it's clearly still there and won't disappear magically.

See original closed issue: 
- https://github.com/facebook/react-native/issues/15832
- https://github.com/facebook/react-native/issues/10411

**Comment by slorber** [comment]
Hmmmm actually it seems to always work fine with a background, but due to android not supporting overflow, the shadow can be clipped. Adding a parent with some padding can help (here I'm applying shadows to FlatList items)

Also this solution of @sibelius can be a nice alternative: https://medium.com/entria/solving-view-overflow-in-android-reactnative-f961752a75cd

**Comment by SupriyaKalghatgi** [comment]
#20501

**Comment by kientux** [comment]
Isn't it how `elevation` works on android? Imagine the light source is from the top, then shadow will be longer when the view is far from light source. Just test it on native android project to see the effect.
