### ISSUE TITLE
Clearing TextInput native value on Android

### ISSUE THREAD

**Issue by gitsad** [facebook/react-native#19036]
- [x] I have reviewed the [TextInput documentation](https://facebook.github.io/react-native/docs/textinput.html) and [Direct Manipulation documentation](https://facebook.github.io/react-native/docs/direct-manipulation.html)
- [x] I have searched [399](https://github.com/facebook/react-native/issues/399) [11948](https://github.com/facebook/react-native/issues/11948)
- [x] I am using the latest version of react-native(https://facebook.github.io/react-native/)

I have tried every way to clear input buffer on Android but every attemp failed. After clearing the input, on new typed letter the last word of cleared sentence is appearing. For instance: I wrote `foo foo` and clear that one. After that when I will try type again without hiding the native keyboard for example `react` I would receive `fooreact`.

## Environment

  OS: macOS High Sierra 10.13.4
  Node: 8.9.0
  Yarn: 1.5.1
  npm: 5.5.1
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.0 => 0.55.0

## Steps to Reproduce
Because of different approaches I have finished with something like that:
```
const SMessageInput = styled.TextInput`
    width: 100%;
    background-color: ${COLOR.WHITE};
    height: 40px;
    padding: 10px;
`;

class MessageInput extends React.Component {
    state = {
        value: '',
    };

    componentWillReceiveProps(newProps) {
        console.log(this.messageInput.root.isFocused());
        this.messageInput.root.setNativeProps({ text: '' });
        this.messageInput.root.clear();
        if(this.messageInput && this.props.input.value && newProps.input.value === '') {
            this.setState({
                value: '',
            }, () => console.log(this.state));
        } else {
            this.setState({
                value: newProps.input.value,
            }, () => console.log(this.state));
        }
    }

    render() {
        return(
            <SMessageInput
                clearButtonMode="always"
                autoCapitalize="none"
                clearTextOnFocus
                spellCheck={false}
                onEndEditing={(data) => console.log(data, 'on end editing')}
                blurOnSubmit
                value={this.state.value}
                autoCorrect={false}
                ref={component => this.messageInput = component}
                underlineColorAndroid="transparent"
                {...this.props}
                onChangeText={(text) => this.props.input.onChange(text)}
            />
        );
    }
};
```
I also use `redux-form` to manage input data that's why componentWillReceiveProps is used.

## Expected Behavior
Should type without cleared `last word of sentence` prefix.

## Actual Behavior
Receiving `last word of cleared sentence` as prefix before every new value. Everything works fine when after clearing blur function is executed or manually hide the native keyboard. Then typed new value is without `last word of cleared sentence` as prefix.

**Comment by gitsad** [comment]
## Environment

  OS: macOS High Sierra 10.13.4
  Node: 8.9.0
  Yarn: 1.5.1
  npm: 5.5.1
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.0 => 0.52.0

**Comment by gitsad** [comment]
I have updated react-native version to the latest and update everything in this post. Could anyone help with that and maybe provide some workaround to clear input completely on Android? Every help would be appreciated.

**Comment by gitsad** [comment]
Ok, after some digging again on the Internet, I've found other related pull request https://github.com/facebook/react-native/pull/12462 but it seems this bug still exists 😞 and also I have found workaround based on another module https://github.com/nikolaiwarner/react-native-text-input-reset 👍

**Comment by gitsad** [comment]
yes

**Comment by vrgimael** [comment]
Hey, we're having this issue too here but only on the Galaxy S8 and not on any other other of our test devices. What phone are you using?

Thanks

**Comment by gitsad** [comment]
Samsung Galaxy A5 2016

**Comment by tranvannhat** [comment]
samsung keyboard all device, same error!

**Comment by FLGMwt** [comment]
Seeing this on Galaxy J7, Samsung S6, Samsung S8, & Samsung S9 at least.

**Comment by kennethlynne** [comment]
Still an issue on react-native 0.55

**Comment by ginccc** [comment]
Reproducable on my HTC 10

**Comment by zvs001** [comment]
I also see this bug on android 6.0.
ReactNative version: `"^0.57.4"` react: `"16.6.0-alpha.8af6728"`
Steps to reproduce:
```
enter 'a' // => 'a'
enter 'b' // => 'ab'
clear state/ref // => ''
enter 'c' // => 'abc'
```
I know that we receive wrong values from Android sources: (last step)
```
console.log('_onTextInput before',event.nativeEvent.previousText) // => ''
console.log('_onTextInput current', event.nativeEvent.text) // => 'abc'
```


It works correctly only when I do `Keybord.dissmiss()`  (unfocus)

**Comment by AlexanderPinkerton** [comment]
Still an issue

**Comment by brianmak3** [comment]
Adding `secureTextEntry={false}` to the TextInput will solve the problem.

**Comment by linhtran-agilityio** [comment]
Try with `clear()`
Example: this.inputRef.current.clear()

**Comment by Salakar** [comment]
👋 hey all, there was a PR for this to address the issue in React Native specifically #12462 - but the PR went stale due to lack of feedback from the author and others, see [this comment](https://github.com/facebook/react-native/pull/12462#issuecomment-477295348).

I'm going to close this issue given that there is a third-party workaround for now (as mentioned above) and that the PR above can be re-looked at (if someone can volunteer to do so ❤️).

Thank you
