### ISSUE TITLE
React native web view zooms webpage on iOS.. works fine on android...

### ISSUE THREAD

**Issue by sarathvad1811** [facebook/react-native#19047]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

I am using WebView of react native to display a web page. It show correctly on android mobile. But it gets zoomed unnecessarily on iOS. I have this meta data added to the site url which webview is loading.
`<meta name="viewport" content="width=device-width, initial-scale=1.0">`
Still No Idea what's causing the issue.

It's opening quite well and correctly when I open the link in Safari browser of the same mobile

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.4.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.2 => 0.53.2

## Steps to Reproduce
1. Load this url: http://v4.vaave.net/albums.dz into react-native WebView component
2. Check the result on android and ios. On iOS you can observe the view is zoomed 
The code is 
import {WebView as NativeWebView} from "react-native";

`
<NativeWebView
            startInLoadingState
            scalesPageToFit
            source={{ uri: this.props.url }}
            ref={webview => {
              this.myWebView = webview;
            }}
 />
`

## Expected Behavior
1. It should not be zoomed on both iOS and android
It's opening quite well and correctly when I open the link in Safari browser of the same mobile like in the below screenshot which is actually a screenshot of android mobile

This One

![screenshot_20180427-161544](https://user-images.githubusercontent.com/37393312/39359574-2a29c598-4a38-11e8-8818-935807a91bc0.png)

## Actual Behavior
It is getting zoomed
![image uploaded from ios](https://user-images.githubusercontent.com/37393312/39359559-1b2240ca-4a38-11e8-91b9-41287c669853.png)

**Comment by sarathvad1811** [comment]
Yes the issue is on latest 0.55 too

**Comment by rsinnet** [comment]
Any update on this?

**Comment by forrestgrant** [comment]
Same. React Native: 0.55.4

**Comment by Feng999** [comment]
try to modify 'scalesPageToFit' of webview.

**Comment by forrestgrant** [comment]
@Feng999, thanks for the reply. I still experience the issue with `salesPageToFit` set to either `true` or `false`.

**Comment by forrestgrant** [comment]
I just got this working. The bug—for me—is not related to React Native. In my case, the page loaded insecure assets that were blocked by iOS App Transport Security. To check if this is affecting your app, try:
```
<key>NSAppTransportSecurity</key>
<dict>
  <!--Include to allow all connections (DANGER)-->
  <key>NSAllowsArbitraryLoads</key>
  <true/>
</dict>
```

**Comment by 452MJ** [comment]
+1

**Comment by 452MJ** [comment]
![wechatimg526](https://user-images.githubusercontent.com/13673008/42095352-f77a82c0-7be4-11e8-899f-d932f6be0e43.jpeg)
![wechatimg527](https://user-images.githubusercontent.com/13673008/42095353-f7e70512-7be4-11e8-9702-12c4f5b3cd5b.jpeg)

**Comment by 452MJ** [comment]
maybe you can try the folow code:
```js
window.onload = function(){
    //resize code
   ...
}
```

**Comment by ItsNoHax** [comment]
Try giving your webview a height and a width. For example your screen dimension's width/height.

**Comment by danaee123** [comment]
same,to show image in android
when 
my code is
   <WebView
         ref={ref => this.WEBVIEW_REF = ref}     
         style={{ justifyContent: 'center',alignItems: 'center',width:'100%',height:height,}}
         source={{uri: 'https://test.com/images/s1/s1.jpg'}}     
            />

zoomed unnecessarily in first load

**Comment by fangrm** [comment]
+1. The image uri is 'https://img.alicdn.com/imgextra/i1/4045187964/TB2z.KQpAomBKNjSZFqXXXtqVXa_!!4045187964.jpg'. it gets zoomed unnecessarily on iOS.

**Comment by Titozzz** [comment]
React-native Webview component is being extracted to https://github.com/react-native-community/react-native-webview. Please if that bug still exists with the extracted component, open an issue on the other repository, as it will probably be easier to get attention there.

Thank you !

**Comment by yakupad** [comment]
> try to modify 'scalesPageToFit' of webview.

Thanks! Worked for me 💯

**Comment by LBCross** [comment]
> try to modify 'scalesPageToFit' of webview.

https://github.com/ShivamKJJW/react-native/commit/d42290959364963f3cb3717b9a2464a78ce13f6f
