### ISSUE TITLE
onEndReached fire again and again when ListView nested in ScrollView

### ISSUE THREAD

**Issue by HouLinguo** [facebook/react-native#19041]
- [x]  I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [ ] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment
Android:
`react-native -v:0.42.3`
`node -v:v8.9.3`
`yarn -v:1.5.1`
`npm -v:5.5.1`

## Steps to Reproduce
1.ListView nested in ScrollView

```python
<ScrollView>
  ....otherCode
<ListView
	dataSource={this.getDataSource(this.state.buyHistoryDataSource)}
	renderRow={
	(rowData) => <BuyHistoryList rowData={rowData} />
	}
	enableEmptySections={true}
	onEndReachedThreshold={50}
	onEndReached={ this.handleEndLoad.bind(this)}
	refreshControl={
	<RefreshControl
	  refreshing={this.state.buyHistoryRefreshing}
	  onRefresh={() => this.refreshBuyHistory()}
	/>
        }
	style={{ flex: 1 }}
	/>
</ScrollView>
```

## Expected Behavior
main view can scroll and ListView reach the tail can fire onEndReached

## Actual Behavior
but it will fire again and again and load all data

**Comment by sofwu** [comment]
@react-native-bot 
IOS
react-native -v:0.57.1

me too

**Comment by Romaiin52** [comment]
@react-native-bot
Same problem on IOS / react-native 0.57.1
