### ISSUE TITLE
AsynStorage {“40”:0,“_65”:0,“_55”:null,“_72”:null} in React native

### ISSUE THREAD

**Issue by yogeshR5** [facebook/react-native#19049]
when i trying to store seesion id in Localstorage using AsynStorage in React native return {"40":0,"_65":0,"_55":null,"_72":null} value. how to getItem use in AsynStorage.

## Environment
Environment:
  OS: Linux 4.4
  Node: 6.14.1
  Yarn: 0.22
  npm: 3.10.10
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: ^16.2.0 => 16.3.2
  react-native: 0.53.0 => 0.53.0

## Steps to Reproduce
this is in my middlewareConfig 

config.headers["session_id"] = sessionId();

sessionId = async () => {
  try {
    const value = await AsyncStorage.getItem("session_id");
    if (value !== null) {
      console.warn(value); 
return value;
    }
  } catch (error) {
    console.warn("AsyncStorage Error: " + error.message);
  }
};

## Expected Behavior
when i return value session id should get

## Actual Behavior
but i got error {“40”:0,“_65”:0,“_55”:null,“_72”:null},
can't return any values

**Comment by nanjundas** [comment]
I am using v0.55.2 and i see the same issue.

**Comment by yogeshR5** [comment]
@nanjundas  i tried like this 

config.headers["session_id"] =sessionkey();

const sessionkey = async () => {
  try {
    let key = await AsyncStorage.getItem("session_key");
    return key;
  } catch (error) {
    console.warn("AsyncStorage Error: " + error.message);
  }
};

**Comment by Hack-Jay** [comment]
I have the same problem. How can I solve it  ......

**Comment by nanjundas** [comment]
Below is piece of code working for me. 

I have wrapped AsyncStorage methods into interface 

  ```
class MyPersistStore { 

  static async getItem(key) {
        try {
            return await AsyncStorage.getItem(this.perfixKey + key);
        } catch (error) {
            console.log("Error saving data" + error);
            return null
        }
    }
........ Other Methods.... 

}

```

Usage is as below -- 
```

MyPersistStore.getItem("ForSomeKey").then((obj) => {
   console.log(obj)
})
 .catch((error) => {
   console.log(error)
});

```
