### ISSUE TITLE
[Navigator] I want to know how to send message between two scenes?

### ISSUE THREAD

**Issue by soliury** [facebook/react-native#1904]
I mean in home scene , there is a meessageOverlay to show the unread messages, and then I push to message scene. Then I make the unread messages to read, return to home scene, I want to know how to make the home scene know the message count should update?

**Comment by alinz** [comment]
If I understand correctly, you want to maintain your state some where. You have couple of options.

1: You can create a super component which holds the entire state of your application and pass down the state to all it children, and its children will pass it down to their children. You can also pass down a callback, so children can call parent and modify the state.

2: Use [Flux](https://github.com/facebook/flux) or any flux like frameworks such as [reflux](https://github.com/spoike/refluxjs), [redux](https://github.com/gaearon/redux) and etc. Usually this is a very good option for larger applications.

3: Reinvent the wheel again :P

**Comment by josebalius** [comment]
@soliury like @alinz said I would use flux for this. Anytime you have 2 different components accessing the same data, use a store and come actions to change the store value and re render the components as needed.

**Comment by soliury** [comment]
But there is a problem, when pop message route, how home route know the message route is pop?

**Comment by brentvatne** [comment]
@soliury - you can add a listener to the navigation context, [like this](https://facebook.github.io/react-native/docs/navigator.html#ondidfocus) :smile:

**Comment by soliury** [comment]
@brentvatne I know this way. And in the [noder](https://github.com/soliury/noder-react-native) , I have done that:

```
<Navigator
				initialRoute={{name:'home', index:0}}
				configureScene={(route)=>{
                    if(route.sceneConfig){
                        return route.sceneConfig;
                    }
                    return Navigator.SceneConfigs.FloatFromRight;
                }}
				renderScene={this.renderScene.bind(this)}
				onDidFocus={(route)=>{
                    this[route.name]&&this[route.name].componentDidFocus && this[route.name].componentDidFocus()
                }}
				/>
```

And then in route Component , add a `componentDidFocus`,  But In this way to update the component is not the right way, it too complex.

I just want to a beauty and clear way

**Comment by brentvatne** [comment]
cc @ericvicenti

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/navigator-i-want-to-know-how-to-send-message-between-two-scenes
