### ISSUE TITLE
Vertical text

### ISSUE THREAD

**Issue by namtn** [facebook/react-native#19044]
Hi all,
I'm trying to write text in vertically as image.  
<img width="109" alt="screen shot 2018-04-27 at 16 29 05" src="https://user-images.githubusercontent.com/3005899/39355710-267118fc-4a38-11e8-9105-dfeada08c001.png">

Anybody can tell me how to do that. 
Thanks.

**Comment by bhandarijiwan** [comment]
```js
<Text style={{ transform : [ { rotate: '-90deg'}] }}>
BEVERAGES
</Text>
```
