### ISSUE TITLE
React-Native to C++ bridge

### ISSUE THREAD

**Issue by oneroman** [facebook/react-native#19058]
Hi,

There is understanding how to build iOS React-native project to have a bridge to C++ module using [SampleCxxModule.cpp](https://github.com/expo/expo/blob/master/android/ReactCommon/cxxreact/SampleCxxModule.cpp). But I could not find sample project how to build similar for ***Android*** app. Please share the sample app if any.

Thanks!

**Comment by msand** [comment]
Here is an example: https://github.com/sulewicz/djinni-react-native/tree/master/example-react-native/ExampleProject
