### ISSUE TITLE
Attempt to get native tag from node not marked as "native"

### ISSUE THREAD

**Issue by jeffreymendez1993** [facebook/react-native#19050]
- [ yes] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [yes ] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [yes ] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

Using Animated.ScrollView with useNativeDriver errors for me
## Steps to Reproduce

Basic implementation from docs
## Actual Behavior

Errors on load.
Unhandled JS Exception: Attempt to get native tag from node not marked as "native"

**Comment by jeffreymendez1993** [comment]
<img width="305" alt="screen shot 2018-04-27 at 8 46 48 am" src="https://user-images.githubusercontent.com/8095978/39363226-8b9feaa0-49f7-11e8-8912-3d9e92c7ec3a.png">
<img width="459" alt="screen shot 2018-04-27 at 8 47 49 am" src="https://user-images.githubusercontent.com/8095978/39363281-b868072a-49f7-11e8-8281-b90743ee50de.png">

**Comment by jeffreymendez1993** [comment]
Ahh you cannot pass down native Props is my issue. I define it top Level and pass it into a new component that is Animated.

**Comment by jemmyphan** [comment]
@jeffreymendez1993 i've faced this issue too, how did you resolve this?

**Comment by jeffreymendez1993** [comment]
@jemmyphan use  Create Animated  component and pass in the scrollview should work.
