### ISSUE TITLE
Print: Entry, ":CFBundleIdentifier", Does Not Exist in react-native run-ios

### ISSUE THREAD

**Issue by rascal-mobile56** [facebook/react-native#19055]
** BUILD FAILED **

The following commands produced analyzer issues:

	Analyze /Users/developer/AwesomeApp/node_modules/react-native/ReactCommon/yoga/yoga/YGNodeList.c
	Analyze /Users/developer/AwesomeApp/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.c
(2 commands with analyzer issues)

The following build commands failed:
	Ld build/Build/Products/Debug-iphonesimulator/AwesomeApp.app/AwesomeApp normal x86_64
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/AwesomeApp.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/AwesomeApp.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by BM9MobileBrasil** [comment]
+1

**Comment by daronwolff** [comment]
Same issue for me:

## Environment:
```
Os: Mac Os High Sierra 10.13.1 (17B1003)
Node: 8.9.0
npm: v5.5.1
Watchman: 4.7.0
Xcode: Version 8.3 (8E162)
React Native: 0.55.3
create-react-native-app: 1.0.0
```
## Steps to Reproduce
`create-react-native-app appName`
`cd appName`
`npm run eject` then select *React Native: I'd like a regular React Native project*
`npm run ios`

## Expected Behavior
A successful build.

## Actual Behavior
```
** BUILD FAILED **


The following build commands failed:

CompileC /Users/ksquarelabs/dev/courses/yucatan/ios/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64/RCTShadowView+Internal.o Views/RCTShadowView+Internal.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/yucatan.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/yucatan.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
```

**Comment by cuongta** [comment]
+1

**Comment by skaan** [comment]
Please Fix this. I have the same problem, other similar issues did not work

**Comment by mariowise** [comment]
+1
```
Os: Mac Os El Capitan 10.11.6
Node: 8.11.1
npm: 5.6.0
Watchman: 4.9.0
Xcode: Version 8.2.1
React Native: 0.55.3
```

**Comment by HaikelO** [comment]
I fixed this with updating my macOs and xcode.

**Comment by werkdruk** [comment]
I had this same problem... using:
Mac High Sierra
react-native-cli: 2.0.1
react-native: 0.57.3

Pulled my hair out, and could not find a solution.... Untill I went like this:

react-native init projectname
cd projectname
react-native start (this does the trick)
react-native run-ios

It will take a while, don't do Ctrl-c, the project will build.

:-)

**Comment by Alaa-mansour** [comment]
npm uninstall react-native

delete ios and android folder
then run :

npm install react-native

react-native upgrade
