### ISSUE TITLE
ImageBackground is always in absolute position even though I styled it to position relative

### ISSUE THREAD

**Issue by VanessaChu** [facebook/react-native#19056]
- [Yes] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [Yes] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [Yes] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

When I use the Image component, the outcome I want is correct 
![screen shot 2018-04-27 at 12 22 35 pm](https://user-images.githubusercontent.com/11250498/39380984-5e758c1a-4a15-11e8-973f-620f128d0f7f.png)

However it keeps throwing the message "Using image with children is deprecated and will be error in the near future"

But when I change Image to ImageBackground, the outcome looks like this.
![screen shot 2018-04-27 at 12 24 41 pm](https://user-images.githubusercontent.com/11250498/39381110-cfe110c2-4a15-11e8-86eb-9c2f6eb38cd3.png)

Even though I set the position to relative, upon inspecting, it is set to absolute.

My code:

```
        <TouchableWithoutFeedback style={{ position: 'relative', flex: 1, justifyContent: 'center' }} delayPressIn={500} onPressIn={() => this.onPressInMic()} onPressOut={() => this.onPressOutMic()}>
          <View style={{position: 'relative'}}>
            <ImageBackground style={{ position: 'relative' }} source={this.state.micOn ? Images.micOn : Images.micOff} >
              {
                this.state.micOn
                  ? (
                    <Text style={styles.micText}>PRESS TO{'\n'}STOP</Text>)
                  : (
                    <Text style={styles.micText}>PRESS TO{'\n'}RECORD</Text>
                  )
              }
            </ImageBackground>
          </View>
        </TouchableWithoutFeedback>
```

## Environment
"react-native": "0.46.4"

## Steps to Reproduce
Change Image to ImageBackground

## Expected Behavior
Image would position relatively

## Actual Behavior
Image is positioned absolutely

**Comment by VanessaChu** [comment]
This occurs when I run react-native info

Command `info` unrecognized. Make sure that you have run `npm install` and that you are inside a react-native project.

**Comment by bhandarijiwan** [comment]
Try passing `imageStyle` prop with
 ```js
  {{ position:'relative' }}
```
Try this.
```js
<ImageBackground imageStyle={{ position: 'relative' }} source={this.state.micOn ? Images.micOn : Images.micOff} >
              {
                this.state.micOn
                  ? (
                    <Text style={styles.micText}>PRESS TO{'\n'}STOP</Text>)
                  : (
                    <Text style={styles.micText}>PRESS TO{'\n'}RECORD</Text>
                  )
              }
            </ImageBackground>
```

**Comment by VanessaChu** [comment]
@bhandarijiwan  Thanks! that fixes my Imagebackground position being off. But for some reason, after adding imageStyle={{position: 'relative'}}, my text disappears!
