### ISSUE TITLE
Network request failed in Android emulator without connection

### ISSUE THREAD

**Issue by jy1989** [facebook/react-native#19060]
Just use simple fetch function with the url without ssl:

```
  fetch(
      'http://my-url',
    ).then((response) => {
        return response.json()
    })
```
and it works fine in my real phone, but always get error 

> Network request failed 

on my Android emulator.

## Environment
Environment:
  OS: macOS Sierra 10.12
  Node: 8.11.1
  Yarn: 0.18.1
  npm: 5.6.0
  Watchman: 4.6.0
  Xcode: Xcode 8.3.3 Build version 8E3004b
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.3 => 0.55.3

## Steps to Reproduce
```
  fetch(
      'http://my-url',
    ).then((response) => {
        return response.json()
    })
```

## Actual Behavior

![image](https://user-images.githubusercontent.com/1291756/39391927-b4b47834-4add-11e8-880c-3ed1122d37fa.png)

And both real phone and emulator work fine when I use the url starts with `https`

So is it a feature with android emulator? 
can I disabled it?
Thank you.

**Comment by tuanmai** [comment]
@jy1989 did you fix this issue? what happened. Since I'm encountering a similar issue.
