### ISSUE TITLE
Linking module borken on Android

### ISSUE THREAD

**Issue by Gerharddc** [facebook/react-native#19061]
Trying to use the Linking module to open tel or mailto urls on Android fails.

## Environment
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.11.1
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.1 AI-173.4697961

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz => 0.55.2

## Steps to Reproduce
1. Create a blank project
2. Follow the instructions on https://docs.expo.io/versions/latest/guides/linking.html
3. Try to use a 'mailto' or 'tel' link

## Expected Behavior
It is expected that these links should be properly opened without some sort of crash.

## Actual Behavior
Android throws an error and does not open the links.

![screenshot_1524906454](https://user-images.githubusercontent.com/11624490/39394632-779395ce-4ad4-11e8-82d3-2c3e2226f288.png)

**Comment by patrickkempff** [comment]
Thank you for reaching out. I am closing this issue as it appears to be related to Expo. I have failed to reproduce your issue with react-native v0.56.

If this issue still occurs please file an issue at https://github.com/expo/expo

Reproduction code:
```jsx
export default class App extends Component<Props> {
  openMailTo () {
    Linking.openURL('mailto:test@example.com').catch(err => alert(err));
  }
  openTel () {
    Linking.openURL('tel:0123456789').catch(err => alert(err));
  }  
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome} onPress={this.openMailTo}>Welcome to React Native!</Text>
        <Text style={styles.instructions} onPress={this.openTel}>To get started, edit App.js</Text>
        <Text style={styles.instructions}>{instructions}</Text>
      </View>
    );
  }
}
```
