### ISSUE TITLE
"react native version mismatch"

### ISSUE THREAD

**Issue by pashute** [facebook/react-native#19071]
- [v] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [v] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [v] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

After an upgrade with react-native-git-update  and re-install of npm packages needed for my project I get an error: React native version mismatch.  See details in actual behavior. 

## Environment

Environment:
  OS: Windows 10
  Node: 8.5.0
  Yarn: 1.5.1
  npm: 4.6.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.1.0.0 AI-173.4670197

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.3 => 0.55.3

## Steps to Reproduce

* Updated from 0.54 to 0.55  with react-native-git-update
* Created a new Genymotion device (Samsung 7 emulator). 
* Ran all npm install needed for the packages of my project (will list packages below)
* Closed all cmd windows and VSCode. 
* In a newly opened admin cmd screen ran `react-native start --reset-cache`
* Could not do a watchman clear, because no "watchman" program on windows. 
* and then did a Yarn Start and a for android from a single newly opened Administrator-Command window in Windows 10. 

## Expected Behavior

As before the upgrade, the program should run in the emulator. 

## Actual Behavior

console error: "React Native version mismatch"

    JavaScript version: 0.55.3
    Native version: 0.54.2

    Make sure that you have rebuilt the native code. If the problem persists try clearing the Watchman and packager caches with 'watchman watch-del-all && react-native start --reset-cache.

**Comment by pashute** [comment]
I upgraded to Yarn 1.6.1  and did not help.  Help!!!!

**Comment by JFE84** [comment]
This happens to me too. After clearing watchman android is fixed but iOS still complains.
I am still trying to figure it out but I found something that might fix your issue, check if the react-native version inside yarn.lock is the right one.

**Comment by pashute** [comment]
I made a new project with init, and that one works (with expo 27). Except that the expo is not running, but rather directly it's running as android dev. (In other words, I don't see the blue arrow and it does not refresh when I change code). I run it by calling `react-native run-android` which runs a separate cmd window with the "Metro Bundler ready" and "loaded done".  This window which opens automatically is not administrator. Wait!  Maybe that's the problem?...  trying and will post here. 

I have android/gradle/wrapper/gradle-wrapper.properties:

    distributionUrl=https\://services.gradle.org/distributions/gradle-2.14.1-all.zip

I'm using packages.json: (after installed these with npm)
note I changed from 
`"start": "node node_modules/react-native/local-cli/cli.js start"` to the following :  

    {
      "name": "noam",
      "version": "0.0.1",
      "private": true,
      "scripts": {
        "start": "react-native-scripts start",
        "eject": "react-native-scripts eject",
        "android": "react-native-scripts android",
        "ios": "react-native-scripts ios",
        "test": "jest"
      },
      "dependencies": {
        "eslint": "^4.19.1",
        "expo": "^27.0.1",
        "object-path": "^0.11.4",
        "react": "16.3.1",
        "react-native": "0.55.3",
        "react-native-action-bar": "^2.0.5",
        "react-native-checkbox": "^2.0.0",
        "react-native-collapsible": "^0.11.2",
        "react-native-exit-app": "^1.0.0",
        "react-native-material-dropdown": "^0.11.1",
        "react-native-scripts": "^1.14.0",
        "react-native-simple-radio-button": "^2.7.1",
        "rn-stack-router": "^1.0.0"
      },
      "devDependencies": {
        "babel-jest": "22.4.3",
        "babel-preset-react-native": "4.0.0",
        "jest": "22.4.3",
        "react-test-renderer": "16.3.1"
      },
      "jest": {
        "preset": "react-native"
      }
    }

**Comment by JFE84** [comment]
so its working now? apparently upgrading mid project causes some issues and is not that simple to upgrade. I deleted my project from local, clone the branch again and iOS is working now.
