### ISSUE TITLE
Android: Controlled TextInput Issue on Some Androids

### ISSUE THREAD

**Issue by Noitidart** [facebook/react-native#19085]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

All my tests are done on a real device.

On some Android's, the controlled `TextInput` is not being controlled correctly and causes all kinds of problems. For demo I simplified it down to `<TextInput value="Hello" />`, and now typing in this box you will see weird characters show momentarily.

Here are some bigger issues caused by this root issue:

* On autocomplete - new characters are introduced - https://github.com/HandlebarLabs/code-and-coffee/issues/15#issue-302470239 (gif included)
* After ".clear" - and then tyep another character - old value comes back - https://github.com/HandlebarLabs/code-and-coffee/issues/15#issuecomment-379606414 (gif included)
* Another - I dont have a gif of yet, I use redux-form, when I have `enableReinitialize:true` and `keepDirtyOnReinitialize: true`. On first re-initialization, the field is getting changed even if it is dirty - only on first re-initialization, future re-initializations have no problem interestingly.

This has been impacting me in all RN versions (I think I started RN with something in the 50s). I have two Android devices. This bug happens to me only on one of them.

## Environment

Environment:
  OS: Windows 10
  Node: 8.4.0
  Yarn: 0.19.1
  npm: 6.0.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  2.3.0.0 AI-162.3764568

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.3 => 0.55.3

## Steps to Reproduce

1. Render `<TextInput value="Hello" />`
2. Type in it, you will see flashes of bad text (characters you did not just push)

Here is a snack - https://snack.expo.io/@noitsnack/controlled-textinput-issue-on-some-androids

## Expected Behavior

Only the character I just typed should flash. Flash because native side gets new character and then syncs with js, which is controlled value. (ideally we have no flash, but this is understandable, and this is not the goal of this issue)

## Actual Behavior

Here is a gif, we see my original text gets "duplicated" on second character press.

![](https://thumbs.gfycat.com/InfamousOrneryDingo-small.gif)

**Comment by thymikee** [comment]
Just to chime in, I can reproduce this behavior on RN 0.55.3, LG G2, Android 5.0.1.

**Comment by Noitidart** [comment]
Thank you very much @thymikee - are you able to reproduce the externally linked snacks too for the more complex examples?

**Comment by thymikee** [comment]
@Noitidart yep, exact the same bahvior as on attached gifs

**Comment by Noitidart** [comment]
Thank you very much for the note on reproduction. I was having a hard time finding others, but after having this bug for a couple months I was sure of it so posted here.

**Comment by Noitidart** [comment]
"For Discussion"

This hasn't been fixed, it's a major issue that still needs discussion to figure out which devices are causing this. And then troubleshooting on those devices.

**Comment by CptFabulouso** [comment]
For me this happens on phone LG G4, android 6.0, RN version 0.56.0

**Comment by jettandres** [comment]
Same thing happening for Android Emulator Pixel 2 API 28

**Comment by dsgoers** [comment]
I'm getting this issue too.  Has anyone found a workaround?

**Comment by Noitidart** [comment]
Not yet @dsgoers :(

**Comment by dsgoers** [comment]
Ah ok.  Thanks for the quick response.  Hopefully this can get fixed soon.

**Comment by NotedToSelf** [comment]
I'm having the exact same issue, just chiming in to say it's happening on a Pixel 2 XL

**Comment by Noitidart** [comment]
Thanks for the vote @NotedToSelf - I am also still having the problem.

**Comment by cawfree** [comment]
Just want to highlight that I was having this issue when declaring the `<TextInput />` within an anonymous class declaration.

Using the standard `class MyTextInputClass extends React.Component` resolves the issue.

**Comment by dreadrocksean** [comment]
#metoo

**Comment by tattivitorino** [comment]
I'm having this issue as well! It wasnt like this untill I ejected my app from Expo! I'm using redux-form so I have a Field that renders the component with the native-base Input which renders the react-native TextInput.

**Comment by tattivitorino** [comment]
The main problem seems to be related to redux-form! When wrapped by Field the problem occurs on both IOS and Android!

**Comment by Noitidart** [comment]
> The main problem seems to be related to redux-form! When wrapped by Field the problem occurs on both IOS and Android!

This happens without redux-form -  2 of the 3 examples are not redux-form.

**Comment by tattivitorino** [comment]
@Noitidart in my case it is the Field of redux-form!

**Comment by WoodyWoodsta** [comment]
I'm having the same issue as well. I'm on:

* RN `0.60.4`
* Redux Form `8.2.5`
* Pixel 3XL and Pixel 2XL
* Hermes and no-Hermes

**Comment by ITsolution-git** [comment]
This problem still persists. Is there any progress?

**Comment by Noitidart** [comment]
I couldn't find a solution.

**Comment by edipkavvas** [comment]
This happens when autocomplete is active on the phone and if the keyboard type of the TextInput supports autocomplete suggestions (like default or email). If you assign 'visible-password' to keyboardType of TextInput, the problem will dismiss. But still this situation is a bug

**Comment by Noitidart** [comment]
This still has not been fixed.
