### ISSUE TITLE
(undocumented) RN.createPortal works but leaves fiber tree in weird state

### ISSUE THREAD

**Issue by EmielM** [facebook/react-native#19084]
I know portals aren't officially support on React Native, but using them seems to work just great and allows me to cheaply render eg a title outside the root view (in my case the titleView of a native UINavigationController):

```js
class MyScreen extends React.Component {

    render() {
        const portal = require('ReactNative').createPortal(<Text>My Title</Text>, this.props.titleTag);
        return <View>{portal}<Text>My screen content</Text></View>;
    }
}
AppRegistry.registerComponent('MyScreen', () => MyScreen);
```

on the native (iOS) side, I add a separate `RCTRootContentView` where I want the portal to render to, and then pass that view's tag to my main render method:

```objc
- (void)loadView {
  NSNumber* titleTag = RCTAllocateRootViewTag();
  self.titleView = [[RCTRootContentView alloc] initWithFrame:CGRectMake(0,0,100,100)
                                                                     bridge:self.bridge
                                                                   reactTag:titleTag
                                                             sizeFlexiblity:RCTRootViewSizeFlexibilityWidth];
 
  self.view = [[RCTRootView alloc] initWithBridge:self.bridge
                                       moduleName:@"MyScreen"
                                initialProperties:@{@"titleTag": titleTag}];
}
```

Initial rendering works as expected (and my react components are portaled to outside the original `RCTRootView`, really cool). It is when `MyScreen` is redrawn and the portal needs to be removed an internal error is triggered in `unmountHostComponents`:

`undefined is not an object (evaluating children.indexOf)`

Trying to debug this proves rather challenging. I suspect the fiber tree is already in an incorrect state by then. What happens is that on https://github.com/facebook/react-native/blob/master/Libraries/Renderer/oss/ReactNativeRenderer-dev.js#L10776, `currentParent` is a number instead of an object. 

Any clues on how to debug this issue further? Eg determine at which point the tree ends up in this weird state.

Thanks!

**Comment by EmielM** [comment]
All relevant info is in the ticket. Reproducible on 0.55.3.

**Comment by satya164** [comment]
https://twitter.com/notbrent/status/982036500899512321

**Comment by satya164** [comment]
cc @sebmarkbage @gaearon

**Comment by Titozzz** [comment]
I have the exact same issue, I'm going to start to investigate

**Comment by Titozzz** [comment]
Got the fix, a line was missing ! I'll submit a PR and link it here
