### ISSUE TITLE
Flatlist scrollToIndex scrolls item all the way to the top of the list and produces whitespace

### ISSUE THREAD

**Issue by tvelev92** [facebook/react-native#19080]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

I am rendering a flatlist and on iOS, when scrolltoindex is called on a item that is close to the bottom of the list, it is pushed to the top and leaves whitespace below it. When you touch the list, it snaps back down. On android it works perfectly. I would like to add that get item layout is implemented. 
## Environment

Environment:
  OS: macOS High Sierra 10.13.2
  Node: 7.10.1
  Yarn: Not Found
  npm: 4.2.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.0 => 0.52.0
## Expected Behavior

Expected behavior is what happens on android, it will only scroll a item far enough to leave whatever is below it without any whitespace under the last item.

**Comment by tvelev92** [comment]
upgraded still same issue. There are items above the index that is scrolled to
![screen shot 2018-05-11 at 4 10 17 pm](https://user-images.githubusercontent.com/10441720/39949077-f162aae6-5535-11e8-9675-68eb7e6cace0.png)

**Comment by scottmas** [comment]
Can confirm this is happening on React Native 55.4.

I have to do some janky logic to offset the scroll position by the max number of rows that can be rendered at a time. Like
```javascript
//Scroll to last item
let scrollIndex = data.length - 1; 

//Correct for the bug
const maxNumRows = Math.floor(windowHeight / ROW_HEIGHT);
if (data.length - scrollIndex < maxNumRows) {
  const diff = maxNumRows - (data.length - scrollIndex) - 2;
  scrollIndex = scrollIndex - diff;
}
````

**Comment by TheSavior** [comment]
Is this related to this PR? https://github.com/facebook/react-native/pull/22769

**Comment by scottmas** [comment]
Yes, that PR appears as though it would fix it.

**Comment by TheSavior** [comment]
Can you test it on your problem and verify?

**Comment by scottmas** [comment]
I think so. Is the RN build process complicated or can I just point my package.json at his forked repo?

**Comment by TheSavior** [comment]
https://facebook.github.io/react-native/docs/building-from-source

**Comment by bartolkaruza** [comment]
@scottmas Were you able to verify that the PR fixed your issue? You don't actually have to worry about building from source for iOS (that's Android specific), so you can just npm/yarn add the github link to that branch to test your change.
```
"react-native": "cabelitos/react-native#scrollFix"
```
