### ISSUE TITLE
[Bridge - Swift] Show error when Swift method exposed to JS has a return type

### ISSUE THREAD

**Issue by kostiakoval** [facebook/react-native#1909]
Show an error when I export a Swift function with a return type.

```Swift 
@objc(SomeAPI)
class SomeAPI : NSObject {
  
  @objc func getName(name: String) -> String {
    println("Name!!")
    return "Name"
  }
}
```
Bridge file
```objc
#import "RCTBridgeModule.h"

@interface RCT_EXTERN_MODULE(SomeAPI, NSObject)
RCT_EXTERN_METHOD(getName:(NSString *)name)

@end
```
The `getName` has a return type that will never be used. It shouldn't be possible

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/bridge-swift-show-error-when-swift-method-exposed-to-js-has-a-return-type

**Comment by kostiakoval** [comment]
sure, Thanks!
