### ISSUE TITLE
Android: Hyphenation broken with nested text

### ISSUE THREAD

**Issue by Jpunt** [facebook/react-native#19098]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Context

This issue is identical to https://github.com/facebook/react-native/issues/17292 and is still apparent in the latest version of RN.

## Environment

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.2.1
  Yarn: 1.5.1
  npm: 5.3.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.1 AI-173.4670197

Packages: (wanted => installed)
  react: ^16.3.2 => 16.3.2
  react-native: ^0.55.3 => 0.55.3

## Steps to Reproduce

Using a Text view nested inside of a Text (both with style) in Android and iOS to show text with hyphenation characters: in iOS the text is displayed using the whole line width with hyphen characters but in Android the text lines break without ever showing hyphen characters at the end of the line.

Examples:

Current Adnroid outcome:
"very long sentences
always break line incorrectly"

Expected Adnroid outcome:
"very long sentences al-
ways break line correctly"

Reproduction steps

1. Create a View component
2. Use these nested Text views inside the View

```jsx
<Text style={[styles.paragraph, {textAlign: 'left'}]}>
  Free&shy;lan&shy;ce&shy;jour&shy;na&shy;list <Text style={{color: 'red'}}>Free&shy;lan&shy;ce&shy;jour&shy;na&shy;list 
  Free&shy;lan&shy;ce&shy;jour&shy;na&shy;list</Text>
  Free&shy;lan&shy;ce&shy;jour&shy;na&shy;list Free&shy;lan&shy;ce&shy;jour&shy;na&shy;list Free&shy;lan&shy;ce&shy;jour&shy;na&shy;list Free&shy;lan&shy;ce&shy;jour&shy;na&shy;list Free&shy;lan&shy;ce&shy;jour&shy;na&shy;list Free&shy;lan&shy;ce&shy;jour&shy;na&shy;list
</Text>
```

3. Make sure the screen width is small enough so the text has to break a couple of times (phone portrait mode)

## Expected Behavior
At the end of the lines there are hyphen characters breaking long words before text continues to the next line.
The text has a similar line breaking with hyphens in Android and iOS.

Working in iOS:
![iOS](https://camo.githubusercontent.com/7e4c49380369db4a2fa839275245aa372327039d/68747470733a2f2f692e696d6775722e636f6d2f366e756d71717a2e706e67)

## Actual Behavior

At the end of the lines there are no hyphen characters breaking long words before text continues to the next line and text lines don't use the full width of the text view, leaving big white spaces at the end of a line.
The text has different line breaking structure and there are no hyphens in Android compared to iOS.

Problem in Android:
![Android](https://camo.githubusercontent.com/1ba9f7f96920c4300d98bda709c7a61d0e8ea891/68747470733a2f2f692e696d6775722e636f6d2f4a6f69664831722e706e67)

## Reproducible demo
https://snack.expo.io/BkF0SxOzf

**Comment by Frank1234** [comment]
This issue is still present on RN 0.55.4.
