### ISSUE TITLE
Textinput (Android) - Support onKeyPreIme. && BackHandler while keyboard shown.

### ISSUE THREAD

**Issue by TronNatthakorn** [facebook/react-native#19096]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

In native code (java) I can create TextInput with handle `onKeyPreIme` for force keyboard do not hide after Back press like this

[Textinput (React Native - Android) - Support onKeyPreIme](https://stackoverflow.com/questions/50127094/textinput-react-native-android-support-onkeypreime)

Does TextInput support `onKeyPreIme` ?

## Expected Behavior
Expect keyboard do not hide after Back press. (In native code I can do with `onKeyPreIme`)

## Actual Behavior
Keyboard hide after Back press.

## Environment
Environment:
  OS: macOS High Sierra 10.13.2
  Node: 8.9.3
  Yarn: 1.3.2
  npm: 5.5.1
  Watchman: 4.9.1
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.1 AI-173.4697961

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.3 => 0.55.3

**Comment by assafb81** [comment]
any updates?

**Comment by whhotw** [comment]
same problem

**Comment by whhotw** [comment]
[my solution](https://whhotw.github.io/blog/2018/08/10/textinput-cannot-blur-on-press-back-button-of-android/)
