### ISSUE TITLE
StyleSheet Flow types (StyleSheetTypes.js)

### ISSUE THREAD

**Issue by breadadams** [facebook/react-native#19093]
- [X] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [X] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [ ] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

Some of the types defined in [`StyleSheetTypes.js`](https://github.com/facebook/react-native/blob/master/Libraries/StyleSheet/StyleSheetTypes.js) are cast as `number`, and therefore when applying a value handled by the `Animated` API, Flow complains.

## Environment

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.10.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: ^16.3.0-alpha.1 => 16.3.0-alpha.2
  react-native: 0.54.2 => 0.54.2

## Steps to Reproduce

1. Create _component X_.
2. Add a prop (eg. `backgroundStyle`) and define it as `ViewStyleProp` in _component X_.
3. Create _component Y_ and add _component X_ as its only child.
4. Add an `Animated` value to _component Y's_ state.
5. Use the animated state value to apply `borderRadius` via _component X's_ `backgroundStyle` prop.

## Expected Behavior

There should be no Flow errors.

## Actual Behavior

Flow doesn't accept the `AnimatedValue`/`AnimatedNode` type for `borderRadius` (it's cast [as a number](https://github.com/facebook/react-native/blob/master/Libraries/StyleSheet/StyleSheetTypes.js#L141)), so we get a `this type is incompatible with props` error in IDE.

![image](https://user-images.githubusercontent.com/5795227/39504223-6521d1f0-4dca-11e8-8043-0115fd01de77.png)

(Note, I'm mentioning `borderRadius` because it's the property I came across the _issue_ with, but the same goes for other properties that can be animated)

___

Happy to submit a PR if wanted, just thought I'd create an issue first 🙂

**Comment by breadadams** [comment]
The version of React Native ran on this project _is_ old, however this still applies to the latest release's Flow types.

**Comment by hramos** [comment]
Can you check `0.56.0-rc` (release candidate)? Lots of Flow improvements made it to this latest release.

**Comment by TheSavior** [comment]
This is still a problem in the RC.
