### ISSUE TITLE
0.55.4 is not updating using `react-native-git-upgrade`

### ISSUE THREAD

**Issue by Rah1x** [facebook/react-native#19091]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment
Environment:
  OS: Windows 10
  Node: 9.2.0
  Yarn: 1.3.2
  npm: 5.8.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.0.0.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: ^0.55.3 => 0.55.3

## Steps to Reproduce
`$> react-native-git-upgrade 0.55.4`

## Expected Behavior
successfully upgrade as it did with previous versions

## Actual Behavior
`

git-upgrade ERR! An error occurred during upgrade:
git-upgrade ERR! Error: The specified version of React Native 0.55.4 doesn't exist.
Re-run the react-native-git-upgrade command with an existing version,
for example: "react-native-git-upgrade 0.38.0",
or without arguments to upgrade to the latest: "react-native-git-upgrade".
    at parseInformationJsonOutput (/AppData/Roaming/npm/node_modules/react-native-git-upgrade/cliEntry.js:110:11)
    at Object.<anonymous> (/AppData/Roaming/npm/node_modules/react-native-git-upgrade/cliEntry.js:264:48)
    at Generator.next (<anonymous>)
.
.
`

**Comment by Rah1x** [comment]
usually its published in a day or 2, now its been 5 days an im waiting for a couple of particular bugs that might have been resolved

**Comment by LordParsley** [comment]
Testing again today, this appears to have been resolved.

**Comment by saaksshi** [comment]
Still same issue 

An error occurred during upgrade: 
git-upgrade ERR! Error: Command 'yarn add react-native@0.55.4' exited with code 1:
