### ISSUE TITLE
Rename the framework/static library to React

### ISSUE THREAD

**Issue by ide** [facebook/react-native#191]
This is just to avoid conflicts with ReactKit which seems pretty popular: https://github.com/ReactKit/ReactKit.

For this React the umbrella header import would read `#import <ReactNative/ReactNative.h>` and the framework module import would be `@import ReactNative;`. Simple change but probably best to do from the Facebook side.

**Comment by tadeuzagallo** [comment]
Closed by 6500ba7bfbdc2bd8e3301813b3cb606aeea35331
