### ISSUE TITLE
Crash when loading multiple RCTRootViews at the same time

### ISSUE THREAD

**Issue by awaseem** [facebook/react-native#19108]
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)

Hi there,

We recently started an upgrade process from React Native version 0.49 to the latest 0.55.4. Our iOS app is a hybrid Swift/RN app. It has 5 tabs where one is a native Swift tab and the other 4 are all React Native. We register our components within our index.js like so: 

```
 AppRegistry.registerComponent('AppRoot', () => AppRoot);
 AppRegistry.registerComponent('TabOne', () => TabOneContainer);
 AppRegistry.registerComponent('TabTwo', () => TabTwoContainer);
 AppRegistry.registerComponent('TabThree', () => TabThreeContainer);
 AppRegistry.registerComponent('TabFour', () => TabFourContainer);
```

Then within our native code, we create the React Native tabs each with their own RCTRootView, like so:

```

// AppDelegate snippet:
let jsCodeLocation = RCTBundleURLProvider.sharedSettings().jsBundleURL(forBundleRoot: "index", fallbackResource: nil)
let bridge = RCTBridge(bundleURL: jsCodeLocation, moduleProvider: nil, launchOptions: launchOptions)

// Function that creates the RN tabs:
func createReactNativeViewController(moduleName: String) -> UIViewController {
    // Using a shared RCTBridge object for all of these view controllers
    let delegate = UIApplication.shared.delegate as! AppDelegate
    let rootView = RCTRootView(bridge: delegate.bridge!, moduleName: moduleName, initialProperties: nil)
    let rnViewController = UIViewController()
    rnViewController.view = rootView
    return rnViewController
}


let tabOne = createReactNativeViewController(moduleName: "TabOne")
let tabTwo = createReactNativeViewController(moduleName: "TabTwo")
let tabThree = createReactNativeViewController(moduleName: "TabThree")
let tabFour = createReactNativeViewController(moduleName: "TabFour")
```

All 4 of these tabs get created an loaded at the exact same time in a `UITabBarController`.

On version 0.52 and below, this seems to work fine but as of version 0.53.0 and beyond our app sometimes crashes. It appears to be a race condition. The more tabs we load at the same time, the more likely the crash is.

After looking at the release notes, it seems that there was a drastic change with the way the these views are being loaded after removing `reactBridgeDidFinishTransaction` based on the following commits: 

* d2dc4514077ae868f85d45ccdcc7c69df7b7648b
* 099b28006b59abb11eae1f27424566b280860b0d
* b263560c73af5559fdc3bba411f16c588abbffef
* a255204e3e7fddefd2d7b0de224101768757ca7a
* d2dc4514077ae868f85d45ccdcc7c69df7b7648b

We believe that our current logic is causing a race condition because all the RCTRootView are loading asynchronously vs. loading one at a time (based on the previous logic from `reactBridgeDidFinishTransaction`). The crash happens on the following RCTAssert within `RCTNavigator.m`. The value of `self.superview` is `nil`:

```
RCTAssert(!_bridge.isValid || self.superview != nil, @"put reactNavSuperviewLink back");
```

@shergin, we noticed that you had made the changes above. We were hoping to find out if there are any workarounds or recommended approaches to using multiple `RCTRootView`? We started using `RCTSurface` but haven't had any luck. We also tried lazy-loading these view controllers instead of loading them all at the same time. It seems to help, but if the user starts going crazy, tapping the different tabs very quickly, we are still able to replicate the crash.

Thank you!

## Environment

```
Environment:
  OS:  macOS Sierra 10.12.6
  Node:  6.2.2
  Yarn:  0.24.6
  npm:  5.0.3
  Watchman:  4.7.0
  Xcode:  Xcode 9.2 Build version 9C40b
  Android Studio:  3.1 AI-173.4697961

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.3 => 0.55.3
```
## Steps to Reproduce
We created a repo for people who want to create hybrid apps with React Native, its out of date but its very similar to our production app's code structure for the tab navigators: https://github.com/solium/swift-react-native-hybrid

## Expected Behavior

App is crashing with the following message: `put reactNavSuperviewLink back`

## Actual Behavior

App should not crash

**Comment by rziehl** [comment]
Can anyone on the React Native team weigh in on this?

**Comment by hramos** [comment]
Unfortunately our GitHub notifications are flooded with pings, so it's hard to keep track of issues that need further attention. Before I raise this with the rest of the React Native team, I encourage you to reach out directly to other core contributors for help, or ask in Discuss for help. We're still going through open issues and it may take a while before we can dive into this particular issue you're facing.
