### ISSUE TITLE
[Image] Load Image content from the ios filesystem

### ISSUE THREAD

**Issue by menetrier** [facebook/react-native#1910]
Hello,

I have an image stored as base64 on the ios file system, and i cannot think of any way to import an image component (\<Image\>) using the stored base64. Should i create a native module to take care of this ?

**Comment by jeanregisser** [comment]
One way of doing it would be load the image data using [react-native-fs](https://github.com/johanneslumpe/react-native-fs).

**Comment by arbesfeld** [comment]
This should be fixed in #1740. You can use `~` to get image content from the local file system.

**Comment by menetrier** [comment]
@jeanregisser Yep, i am already doing this :)
@arbesfeld Perfect, exactly what i was looking for!

Thanks you all
