### ISSUE TITLE
0.55.4 is not published

### ISSUE THREAD

**Issue by VincentLanglet** [facebook/react-native#19100]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

The 0.55.4 release is created but not published on https://www.npmjs.com/package/react-native

## Steps to Reproduce
npm install react-native

## Environment
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.5.0
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: Not Found
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.0 AI-171.4443003

## Expected Behavior
The 0.55.4 version is installed

## Actual Behavior
The 0.55.3 version is installed

**Comment by LordParsley** [comment]
Testing again today, this appears to have been resolved.

**Comment by VincentLanglet** [comment]
Thanks
