### ISSUE TITLE
FAILURE: Build failed with an exception. when i run "npm run android"

### ISSUE THREAD

**Issue by shafinr23** [facebook/react-native#19109]
i have a another project on going and that run pretty well and currently i am working on in ,  but when i create this new project  says this BUILD failed 
in package.json i am using 

"dependencies": {
"react": "16.3.1",
"react-native": "~0.55.2"
}

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> Error: java.util.concurrent.ExecutionException: java.lang.RuntimeException: AAPT process not ready to receive commands

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 11.282 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
```

**Comment by VivekHA** [comment]
Hello,
I'm also getting same error message.
after i ran the react-native info i got below data.
*****************************

Environment:
  OS: Windows 7
  Node: 9.11.1
  Yarn: Not Found
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.1.0.0 AI-173.4670197

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.3 => 0.55.3
*********************************************
I have installed android studio and made sure that emulator is running
