### ISSUE TITLE
[Android] NativeMethodsMixin.measure.call returning undefined values for a component

### ISSUE THREAD

**Issue by jgfidelis** [facebook/react-native#19103]
Is this a bug report?
Yes

Have you read the Contributing Guidelines?
Yes.

Environment

  OS: macOS High Sierra 10.13.4
  Node: 9.4.0
  Yarn: 1.5.1
  npm: 3.10.10
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.0 => 0.53.0

Test device: Android simulator: Pixel running Android 5.1

Steps to Reproduce

This is an Android only issue, on iOS it is fine.

This code:
```
NativeMethodsMixin.measure.call(this.iconRef, (x, y, width, height, pageX, pageY) => {
          setTooltipPosition({ x: pageX, y: pageY });
          setLabelPosition({ x: pageX, y: pageY });
          toggleModal();
        });
...
render() {
...
<Icon
              color={Colors.white}
              icon={icon}
              size={8}
              style={styles.icon}
              ref={el => (this.iconRef = el)}
            />
}
```
`(x, y, width, height, pageX, pageY)` all are undefined. This happens only on one of our components, called `Icon`, like in the example above.

If I do:
```
<View style={styles.iconBackground} ref={el => (this.iconRef = el)}>
            <Icon
              color={Colors.white}
              icon={icon}
              size={8}
              style={styles.icon}
            />
```

The `NativeMethodsMixin.measure.call` works just fine, so the problem is with our `Icon` component.

Our Icon component is:
```
const Icon = props => <InlineIcon {...props} />;
export default compose(customHOC)(Icon);
```
And `InlineIcon` is:
```
const InlineIcon = ({ color, icon, opacity, size, customStyles }: Props) => (
  <Animated.Text
    style={[
      styles.text,
      {
       ...more styles...,
      },
      customStyles,
    ]}
  >
    {icon}
  </Animated.Text>
);
```

Expected Behavior

Measure method return correct values.

Actual Behavior

Measure method returns undefined values on my `Icon` component.

Can anyone give an insight about this? I am just curious... I tried to omit some code, but if you need more information, let me know.

Thanks

PS: already tried all solutions specified here: https://github.com/facebook/react-native/issues/3282

**Comment by Chersquwn** [comment]
same issue.
```javascript
componentDidMount() {
    setTimeout(() => {
      this.body.measure((x, y, width, height, pageX, pageY) => {
        console.log(pageY)
      })
    })
  }
```
x, y, width, height, pageX, pageY, all are undefined in android, but ok in iOS

**Comment by hannigand** [comment]
I get the same problem - reproducible [Snack](https://snack.expo.io/SkUJ7K_pG)

Within my project, if I set `collapsible={false}` it returns zero values. Omitting that prop returns `undefined`.

Either way these are not the correct values. As mentioned, works perfectly on iOS.

**Comment by jgfidelis** [comment]
@hannigand On my case, no solution like setting `collapsible` to false, set an empty onLayout or set prop render`ToHardwareTextureAndroid` worked on my `Icon` component.

**Comment by hannigand** [comment]
@jgfidelis I'm not still able to get anything over than 0 values. 

I added the following props on all `View`s, but it didn't work:

```javascript
 onLayout={this.getMeasurements}
 renderToHardwareTextureAndroid
 collapsible={false}
```

[Updated Snack](https://snack.expo.io/B1R72q_aG)

**Comment by jgfidelis** [comment]
Please reopen this as other people have expressed the problem as well.

I think it follows the templates too.

**Comment by sibelius** [comment]
wrapping the component in a `<View>` component solves the problem?

**Comment by jasperkuperus** [comment]
I had the same issue with a view outside of the viewport. Adding `collapsable={false}` works for me.

It was hard to find this solution. I suggest we can add this to the documentation of the [measure method](https://facebook.github.io/react-native/docs/direct-manipulation#measurecallback). A small notice on Android optimizing views and returning `undefined`, pointing to the solution with [`collapsable`](https://facebook.github.io/react-native/docs/view.html#collapsable) would be awesome.

**Comment by jsamr** [comment]
I could reproduce this issue.

**Comment by alshirokov81** [comment]
I also have this problem in rn 0.59.5 in Android
Solution suggested by @jasperkuperus helped me, but all touchable opacities inside my View with  prop collapsable={false} stopped working ((.
I had to create separate View item with prop collapsable={false} just for calling measure().
