### ISSUE TITLE
[WebView] Android performance issue when using large webviews

### ISSUE THREAD

**Issue by Athaphian** [facebook/react-native#19112]
When using a webview that has a large height, for example 5000, the performance is drastically reduced. Scrolling in the webview or a surrounding ScrollView becomes unbearably slow.

When the webview has a height of 100%, the scrolling occurs within the webview itself and everything works fine. It's just webviews that have a huge outer height make everything slow.

This example demonstrates the behaviour. It only occurs on android. On IOS, webviews like this are still blazing fast.

`<View style={{height: 5000}}>
	<WebView
		source={{uri: 'https://en.wikipedia.org/wiki/Financial_crisis'}}
		style={{
			height: 5000,
			width: '100%'
		}}
	/>
</View>`

## Environment
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.2.0
  Yarn: 1.2.1
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.0 => 0.53.0

## Steps to Reproduce
See the code example above. Put this code in a simple component and try to scroll through the wikipedia page on an android device and ios device. On ios it will scroll fluently, while on android it will be sluggish and non responsive.

## Expected Behavior
On android I expect no performance penalty when using webviews with a large height, just as it has no performance penalty on ios devices.

## Actual Behavior
On android all swipe / scroll gestures become slow to a point that we cannot give this functionality to a user.

**Comment by habibi-dev** [comment]
+1
