### ISSUE TITLE
Document that Native Module with same method name but different arity are not allowed

### ISSUE THREAD

**Issue by karanjthakkar** [facebook/react-native#19116]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment

NA

## Steps to Reproduce

```
//...

public class NavigationModule extends ReactContextBaseJavaModule {

    @ReactMethod
    @SuppressWarnings("unused")
    public void push(@Nonnull String methodName, @Nonnull ReadableMap parameters, @Nonnull Promise promise) {
        //...
    }

    @ReactMethod
    @SuppressWarnings("unused")
    public void push(@Nonnull String methodName, @Nonnull ReadableMap parameters, @Nonnull String testing, @Nonnull Promise promise) {
        //...
    }
}

```

## Expected Behavior

Would there be interest in augmenting the documentation for [Native Modules for Android](https://facebook.github.io/react-native/docs/native-modules-android.html) to include [this](https://github.com/facebook/react-native/blob/786c1ecc2a6856967d676da68eb02f89eb38fb79/ReactAndroid/src/main/java/com/facebook/react/bridge/BaseJavaModule.java#L35):

```
Please note that it is not allowed to have multiple methods annotated with `@ReactMethod` with the same name.
```

I was just suggesting this because the errors that show up if you do this (Expected x arguments but got y) are not indicative of the exact issue and it is hard to understand. More so, this is unintuitive as Android allows overloading methods based on arguments. So having this documented would make sure that folks know there is a difference between ios and android.

Alternatively, if it is possible to make this happen somehow and someone would like to point me in the right direction, I'm happy to give this a shot.

## Actual Behavior

NA

**Comment by karanjthakkar** [comment]
@react-native-bot It contains all relevant information.

**Comment by iamchathu** [comment]
Go in to this issue recently. I created a method with a parameter and and a non-parameter version for method overloading and got the same  error
