### ISSUE TITLE
Text numberOfLines={2} and ellipsizeMode="middle" breaks on Android

### ISSUE THREAD

**Issue by Daniel-J-Fisher** [facebook/react-native#19117]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [ ] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

Line restriction with `ellipsizeMode` set in a `Text` componenet fails to preform any truncation on Android when `numberOfLines={2}` is set.

This fails: `<Text numberOfLines={2} ellipsizeMode="middle" >Some long text • 10</Text>`
This works: `<Text numberOfLines={1} ellipsizeMode="middle" >Some long text • 10</Text>`
Both of the above snippets work as expected on iOS.

## Environment
Environment:
  OS: macOS Sierra 10.12.6
  Node: 7.0.0
  Yarn: Not Found
  npm: 3.10.8
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.53.0 => 0.53.0

## Steps to Reproduce

On Android, combination of `numberOfLines={2}` and `ellipsizeMode="middle"` on a `Text` component fails to truncate the text and no ellipses are visible. When I remove `ellipsizeMode` it defaults to `tail` and it truncates the text without issue.

Code Snippet
```JavaScript
//...
<Text 
  style={styles.text_name}
  numberOfLines={2}
  ellipsizeMode="middle"
>
  {`${this.props.listItem.name} • ${this.props.listItem.quantity}`}
</Text>
//...
const styles = StyleSheet.create({
  //...
  text_name: {
    color: ColorPalette.GREY.BLACK,
    fontSize: 18,
    fontFamily: fonts.proxima.semibold
  },
  //...
});
```

Check out my **Snack** reproducing this: [FAILING WITH 2 LINES](https://snack.expo.io/SyqdOCdTG)
Here's a Snack of it working with one line: [WORKING WITH 1 LINE](https://snack.expo.io/SJYSb0uaM)

## Expected Behavior

I expect Android should have the same functionality as iOS

Correct iOS Screenshot
<img width="316" alt="screen shot 2018-05-03 at 2 25 54 pm" src="https://user-images.githubusercontent.com/8268617/39595768-64298620-4ede-11e8-899a-3bfd71ae6215.png">

## Actual Behavior

I have been working on this within my app and below is a screenshot of the section of my app where this is used.

Incorrect Android Screenshot
<img width="308" alt="screen shot 2018-05-03 at 2 26 04 pm" src="https://user-images.githubusercontent.com/8268617/39595718-41e1703c-4ede-11e8-9d3f-4f61f8051ca3.png">

## Extra Info

The reason I need `ellipsizeMode="middle"` is because I have a title and a number that I append to the title and want to always ensure that the number at the end is shown.

I have read through many of the issues about `numberOfLines` on this repo and I have not found anything that proposed a solution.

Any ideas?

**Comment by Daniel-J-Fisher** [comment]
The Snack examples I posted reproduce this issue on the latest release.

**Comment by geminiyellow** [comment]
nobody care this ?

![image](https://user-images.githubusercontent.com/929878/47068501-61baf500-d227-11e8-909c-d04e75ef02e9.png)

**Comment by Manhazito** [comment]
Still present on React Native 0.57.1… :-/

**Comment by GauthierG** [comment]
Still present on 57.7 ...

**Comment by kelset** [comment]
This issue appears to be solved in RN 0.59:

<img width="800" alt="Screenshot 2019-03-19 at 17 18 06" src="https://user-images.githubusercontent.com/16104054/54627265-02c60a00-4a6b-11e9-8e06-b8f526741b47.png">

Using this snippet:
```
import React, { Component } from 'react';
import { StyleSheet, View, Text } from 'react-native';

export default class App extends Component<> {
  render() {
    return (
      <View style={styles.container}>
        <Text numberOfLines={2} ellipsizeMode="middle">
          Lorem Ipsum is simply dummy text of the printing and typesetting
          industry. Lorem Ipsum has been the industry's standard dummy text ever
          since the 1500s, when an unknown printer took a galley of type and
          scrambled it to make a type specimen book. It has survived not only
          five centuries, but also the leap into electronic typesetting,
          remaining essentially unchanged. It was popularised in the 1960s with
          the release of Letraset sheets containing Lorem Ipsum passages, and
          more recently with desktop publishing software like Aldus PageMaker
          including versions of Lorem Ipsum.
        </Text>
        <Text
          numberOfLines={1}
          ellipsizeMode="middle"
          style={{ marginTop: 20 }}
        >
          Some long text • 10
        </Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
    justifyContent: 'center',
    paddingTop: 40,
    paddingHorizontal: 50
  }
});

```

Closing.

**Comment by deathnopool** [comment]
same isuee.
numberOfLines=1 works fine, but not for numberOfLine=2, 3, 4 ...

**Comment by Temirtator** [comment]
For some reason this doesnt work for Android

> same isuee.
> numberOfLines=1 works fine, but not for numberOfLine=2, 3, 4 ...

**Comment by jinshin1013** [comment]
@kelset Wait your example shows it it's broken on the Android.

This is still happening on 0.61.5.
