### ISSUE TITLE
Option to display custom context menu on <Text /> and <WebView />

### ISSUE THREAD

**Issue by GaudamThiyagarajan** [facebook/react-native#19111]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Expected Behavior
On holding a content of `<Text selectable />` and `<WebView />` a context menu appears. We should  be able to over ride the context menu with a custom view and do custom actions on them with each action triggering a event / function with selected text as argument.

## Actual Behaviour
Currently android's default behaviour shows up and there are only default options like copy, paste and web search.

## References
 - these references were found in stackoverflow.com which were left unanswered
    [React Native | add option to Text context menu](https://stackoverflow.com/questions/48883406/react-native-add-option-to-text-context-menu)
 [Handle Context Menu on selectable Text in react-native](https://stackoverflow.com/questions/50133568/handle-context-menu-on-selectable-text-in-react-native?noredirect=1&lq=1)
  [Selection/Edit menu in React Native](https://stackoverflow.com/questions/35845503/selection-edit-menu-in-react-native)

**Comment by Balasnest** [comment]
@GaudamThiyagarajan I am also facing the same scenario. Did you find out any solution?

**Comment by ammoradi** [comment]
please reopen this.
I actually need this feature.

**Comment by vitorebatista** [comment]
I need this too, please reopen.

**Comment by rickhanlonii** [comment]
Hey all - thanks for bumping!

This issue was closed because it is not properly submitted (as the bot text outlines)

For webview please open an issue in [react-native-webview](https://github.com/react-native-community/react-native-webview)

For a feature request to the core Text module please file an issue in [discussions and proposals](https://github.com/react-native-community/discussions-and-proposals/)

**Comment by vitorebatista** [comment]
It's possible to display custom context menu with this project: https://github.com/Astrocoders/react-native-selectable-text
