### ISSUE TITLE
Ignore empty strings outside of Text component

### ISSUE THREAD

**Issue by Elijen** [facebook/react-native#19127]
There is nice article about an issue that can cause unexpected app crashes here: 
https://reubenab.github.io/blog/2017/10/18/buggy-react-native-pattern

**TL;DR:** `{x && <Foo boo={x} />}` will crash the app when `x === ''`

Would it make sense to workaround this issue by checking for empty string and not trying to render it outside of Text component?

**Comment by Elijen** [comment]
@react-native-bot ¯\_(ツ)_/¯

**Comment by bhandarijiwan** [comment]
@Elijen Yeah, I think you could

```js
x.length > 0 &&  <Foo bar={x}>
```
or 

```js
{ x ? <Foo bar={x}> ? null }
```
. Both are legit.

**Comment by Elijen** [comment]
@bhandarijiwan I know, it's just a common practice/mistake to just do: `{x && <Foo boo={x} />}` which in React for web is completely fine, but throws crashes the app in React Native.

That's why I though simply ignoring empty strings in React Native renderer could solve the problem easily. I'd maybe go as far as saying that all strings could be ignored on production to prevent app crashes (but still produce an error in dev mode).
