### ISSUE TITLE
[iOS] Multiple TextInput components inside a ScrollView - Keyboard not closing on Keyboard.dismiss()

### ISSUE THREAD

**Issue by hbarylskyi** [facebook/react-native#19125]
- I have reviewed the [documentation](https://facebook.github.io/react-native)
- I have searched [existing issues](https://github.com/facebook/react-native/issues)
- I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

Having multiple TextInputs inside a ScrollView with `keyboardShouldPersistTaps="handled"` will prevent Keyboard from closing.

## Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.9.0
  Yarn: 1.2.1
  npm: 5.8.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.2 => 0.55.2

## Steps to Reproduce

```
import React, { Component } from 'react';
import { ScrollView, TextInput, Button, Keyboard, View } from 'react-native';

class App extends Component {
  render() {
         <ScrollView>
             <TextInput style={{ backgroundColor: 'red', margin: 1, marginTop: 20 }} />
             <TextInput style={{ backgroundColor: 'red', margin: 1 }} />
             <Button onPress={Keyboard.dismiss} title={'Close keyboard'} />
         </ScrollView>
   }
}
```

Tap on the first TextInput, after Keyboard was shown, tap on the second one. Then tap on the button.

## Expected Behavior
Keyboard should hide after button tap

## Actual Behavior
Keyboard is not being hidden

**Comment by hbarylskyi** [comment]
Looks like removing View component that's wrapping the ScrollView makes it behave as expected

**Comment by AliDroid** [comment]
only ios

**Comment by fungilation** [comment]
I'm seeing the same thing, on Android only. I have in AndroidManifest.xml, `android:windowSoftInputMode="adjustResize"`. And instead of 2 native inputs, my input is within a webview. After focusing on a web input inside webview, I cannot dismiss keyboard via `Keyboard.dismiss()` (nothing happens).

**Comment by fungilation** [comment]
Hey bot, here's some activity.

**Comment by bduyng** [comment]
hi guys, any updates on this issue?

**Comment by michalchudziak** [comment]
Hello there 👋 by using the repro / the list of steps to reproduce, we can't actually see the reported bug on RN 0.59 so we'll close this issue. It may have something to do with your local setup, please double check that you are using the correct version of Android Studio / XCode / Android NDK / Yarn / etc.
