### ISSUE TITLE
FlatList，Bug

### ISSUE THREAD

**Issue by jiasongs** [facebook/react-native#19124]
- [ yes ] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [ yes ] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [ yes ] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

The name of the component is `FlatListView`：

` <FlatList 
                onEndReachedThreshold={0.01}
                onEndReached={this._onEndReached}
                {...this.props}
            />`
When I use it：
` {this.state.data.length > 0 ? (
                    <FlatListView 
                        data={this.state.data}
                        renderItem={this._renderItem}
                    />) : null}`

When {...this.props} is below `onEndReachedThreshold`, 
onEndReached will only fire on the first render. It will not be triggered at any other time, including sliding to the bottom.

When {...this.props} is above `onEndReachedThreshold`，
 {...this.props} is no problem when onEndReached. Just note that onEndReached triggers the data source to be up-to-date.

Is there an order for es6's {...this.props}?

## Environment

  react-native:0.55.3
  OS: macOS High Sierra 10.13.4
  Node: 8.9.4
  Yarn: 1.5.1
  npm: 5.8.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2
  Android Studio: 3.1 
## Steps to Reproduce

As described above

**Comment by anhtuank7c** [comment]
I getting same problem.
This doesn't happen on RN 54.4

**Comment by anhtuank7c** [comment]
I see previous RN version, Flatlist height will be 0 if data is empty, then it trigger onEndReached.
In RN 55.3 Flatlist seem to have flex: 1 by default and that why doesn't trigger onEndReached if data is empty.
