### ISSUE TITLE
How is the Navigator title set?

### ISSUE THREAD

**Issue by ccorcos** [facebook/react-native#1912]
https://facebook.github.io/react-native/docs/navigator.html#content

How does the Navigator set the title based on MyComponent's title prop? As in, how was it coded? How did the Navigator get that information?

**Comment by brentvatne** [comment]
Hi there,

This kind of question is best suited for StackOverflow - issues are for bugs and feature requests :smile:

The navigator gets that information from the route object that you push to it. If you need more detail I encourage you to create a question on StackOverflow!

Thanks!
