### ISSUE TITLE
React/RCTAssert.h' file not found React Native 

### ISSUE THREAD

**Issue by courptwayne** [facebook/react-native#19134]
- [ ] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [ ] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [ ] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

**Comment by courptwayne** [comment]
Environment:
  OS: macOS High Sierra 10.13
  Node: 9.11.1
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.2 => 0.55.2

**Comment by nopedev** [comment]
same issue here.
```
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.11.1
  Yarn: 1.6.0
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: 16.3.0 => 16.3.0
  react-native: ^0.54.4 => 0.54.4

```

**Comment by nopedev** [comment]
@courptwayne  
In case you added `Objective-C Bridge-Header` in  project's `Build Setting` when applying other plugins. Maybe this could help you. (It worked for me.)

At the `Build Settings` In your \<ProjectName\>Tests target, search `Bridging` as keyword and you will see
`SWIFT_OBJC_BRIDGING_HEADER` under `User-defined` group.

![screen shot 2018-05-08 at 4 37 56 pm](https://user-images.githubusercontent.com/25583777/39744259-9ef14b22-52de-11e8-9bf0-4b3867421051.png)

If the property value of \<ProjectName\>Tests target is empty, then copy the value of `Objective-C Bridging Header` of your project(like below screenshot) and paste it to your \<ProjectName\>Tests target.

![screen shot 2018-05-08 at 4 43 03 pm](https://user-images.githubusercontent.com/25583777/39744656-faf8febe-52df-11e8-97f8-76068e1d2033.png)

**Comment by mmokrani** [comment]
ADD the path to React in Podfile
platform :ios, '9.0'

target 'YourProject' do
 ...
  pod 'React', :path => '../node_modules/react-native' 

end

target 'RNFirebaseTests' do
  ...
  pod 'React', :path => '../node_modules/react-native' 
  
end

**Comment by ue** [comment]
run these commands

`react-native link`
`cd ios/`
`pod install`

**Comment by GreenRidingHood** [comment]
i dont use pod, 
but that accepted answer from Stef, help that error

xcode 10
node v10.15.3
react-native-cli: 2.0.1
react-native: 0.58.6
