### ISSUE TITLE
Unrecognised font family 'Ionicons'

### ISSUE THREAD

**Issue by ghost** [facebook/react-native#19135]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 6.11.5
  Yarn: 0.27.5
  npm: 3.10.10
  Watchman: 4.9.0
  Xcode: Xcode 9.1 Build version 9B55
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.3 => 0.55.3
## Steps to Reproduce

yarn add react-native-vector-icons

react-native link

```
import Ionicon from 'react-native-vector-icons/Ionicons'

<Ionicon 
		style={styles.actionIcon}
		name="ios-headset-outline"
		color="white"
		size={50}
/>
```

## Expected Behavior

No error should appear for fonts

## Actual Behavior

Error thrown: Unrecognised font family 'Ionicons'

**Comment by idevelopappsandmore** [comment]
Solution: after a long wait for a response, this is what I tried my self and it worked!

For others who will land here with similar issues:

Run below command:

`rm -rf ios/build`

and then, 

 `react-native run-ios`

**Comment by timwangdev** [comment]
Closing due to @ghost account
