### ISSUE TITLE
Object.is is undefined in Android

### ISSUE THREAD

**Issue by thevishnupradeep** [facebook/react-native#19139]
When I try to run my JS Code in Android I get error:
`E/ReactNativeJS: TypeError: undefined is not a function (evaluating 'Object.is(t.tasks,this.state.tasks)')`

This error comes only in Android. It works perfectly in iOS

- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [ ] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.11.1
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.3 => 0.55.3

## Steps to Reproduce
Use Object.is in code.

## Expected Behavior
Should just compare given objects and return a boolean value.

## Actual Behavior
Gets an undefined error.

**Comment by thevishnupradeep** [comment]
@react-native-bot  The issue now contains all the relevant information

**Comment by bhandarijiwan** [comment]
React native in android typically runs on older version of javascript engine than iOS so `Object.is`  might not work by default as it's es6 feature. So, you just have to polyfill it with something like [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is)

**Comment by bhandarijiwan** [comment]
@react-native-bot close

**Comment by pierreneter** [comment]
@bhandarijiwan but does `react-native` have `babel`? I still see it working normally with ES6 features.

**Comment by bhandarijiwan** [comment]
@pierreneter It does but not everything in es6  is supported out of the box. [Here](https://github.com/facebook/react-native/blob/master/babel-preset/plugins.js) is list of plugins that `preset: react-native` uses. Everything else you need supply the plugin/polyfill yourself.

**Comment by hramos** [comment]
Commented on the PR - people can use a Babel plugin as a workaround.
