### ISSUE TITLE
SectionList和flatList的 onEndReached method调用多次的bug

### ISSUE THREAD

**Issue by BeyWood** [facebook/react-native#19146]
SectionList和flatList onreachend method调用多次的bug 
onEndReachedThreshold 的value 0-1都试过

detail
在做下拉加载更多的时候尝试使用onreachend来解决，但是发现onreachend会调用多次而且无法预料和控制

Environment
reactnative version 0.44.3
IOS

**Comment by timwangdev** [comment]
Duplicated #16067

**Comment by donybin** [comment]
me too!
