### ISSUE TITLE
could not build: 'openURL:' is deprecated: first deprecated in iOS 10.0 - Please use openURL:options:completionHandler: instead

### ISSUE THREAD

**Issue by seeliang** [facebook/react-native#19143]
- [ ] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [X] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [ ] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 6.12.3
  Yarn: 1.3.2
  npm: 3.10.10
  Watchman: 4.4.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: Not Found

Packages: (wanted => installed)
  react: ^16.3.0 => 16.3.1
  react-native: ^0.54.4 => 0.54.4

## Steps to Reproduce

Not 100% sure which one, i think it happened after i had updated deploy target to 11.3 and Xcode version to 9.3

## Expected Behavior

can build

## Actual Behavior

build fail

RCT_EXPORT_METOD:

line 91
```swift 
{
  BOOL opened = [RCTSharedApplication() openURL:URL];
  if (opened) {
    resolve(nil);
  } else {
    reject(RCTErrorUnspecified, [NSString stringWithFormat:@"Unable to open URL: %@", URL], nil);
  }
}
```

**Comment by venux92** [comment]
I got the same issue on 
react-native: 0.55.3

Happened after I updated my deployment target to IOS 10

**Comment by Kuljo** [comment]
Hi, 

I changed:

`BOOL opened = [RCTSharedApplication() openURL:URL];`

to

`BOOL opened = [RCTSharedApplication() canOpenURL:(NSURL *)URL];`

**Comment by webbhead777** [comment]
This error does not exist in `0.56.0-rc`
