### ISSUE TITLE
attempt to invoke virtual method 'boolean java.lang.string.endtswith(java.lang.string) on a null object reference" ==> when i use linking from react-native

### ISSUE THREAD

**Issue by AbdelhalimAhmed** [facebook/react-native#19140]
# android only iso working perfect 

i upgrade my expo project to "expo": "^27.0.0",
and when useing linking to open Url or tel:number that issue shown to me: 

 **attempt to invoke virtual method 'boolean java.lang.string.endtswith(java.lang.string) on a null object reference**

> using: 
``` 
"expo": "^27.0.0",
"react": "16.3.1",
"react-native": "https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz"
```

> my code: 
```
console.log('Trying to access url')
let url = "https://expo.io"

try {
  Linking.canOpenURL(url).then(supported => {
     if (!supported) {
     console.log('Can\'t handle url: ' + url)
     } else {
        return Linking.openURL(url)
     }
  }).catch(err => console.error('An error occurred', err))
  }catch(err) {
     console.log('why this fucken not working', err)
  }
```

**Comment by nicholasstephan** [comment]
@AbdelhalimAhmed Were you ever able to solve this? I'm getting the exact same error reported by users, but I can't duplicate or track down where the issue is coming from.

**Comment by AbdelhalimAhmed** [comment]
@nicholasstephan i opened the issue on expo and i think still pending to fix it, that's my open issue https://github.com/expo/expo/issues/1733
