### ISSUE TITLE
Flatlist not supported for RTL

### ISSUE THREAD

**Issue by DanGDroid** [facebook/react-native#19150]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

`<Flatlist> horizontal true` component does not work properly on Rtl devices, it renders the items again and jumps to head of list. impossible to use

## Environment

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.2.1
  Yarn: 1.3.2
  npm: 5.5.1
  Watchman: 4.7.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.1 AI-173.4670197

Packages: (wanted => installed)
  react: 16.3.2 => 16.3.2
  react-native: 0.55.0 => 0.55.0
## Steps to Reproduce

```javascript
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  FlatList,
  I18nManager
} from 'react-native';

const getList = () => {
  let list = []
  for (i=0;i<100;i++)
    list.push({title:i,backgroundColor:getRandomColor()})
  return list
}

export default class AutoLinkDemo extends Component {
  constructor(props){
    super(props)
    this.state={
      data:getList()
    }
  }
  render() {
    return (
      <View style={styles.container}>
      <Text style={{fontWeight:'bold',fontSize:60}}>{`is RTL? ${I18nManager.isRTL}`}</Text>
      <View style={styles.list}>
        <FlatList 
          data={this.state.data}
          contentContainerStyle={{alignItems:'center', justifyContent:'center'}}
          renderItem={({ item }) => this.renderCardItem(item)}
          keyExtractor={(item, index) => index}
          horizontal
        />
      </View>
      </View>
    )
  }
  renderCardItem(item){
    return(
      <View style={[styles.cardItem,{backgroundColor:item.backgroundColor}]}>
        <Text style={{fontWeight:'bold',fontSize:40}}>{item.title}</Text>
      </View>
    )
  }
}

function getRandomColor() {
  var letters = '0123456789ABCDEF';
  var color = '#';
  for (var i = 0; i < 6; i++) {
    color += letters[Math.floor(Math.random() * 16)];
  }
  return color;
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5FCFF',
    alignItems:'center', justifyContent:'center',
  },
  list: {
    height:250,
    backgroundColor: 'yellow',
    alignItems:'center', justifyContent:'center',
  },
  cardItem:{
    height:200,
    width:250,
    alignItems:'center',
    justifyContent:'center',
    margin:5,
  },
});

AppRegistry.registerComponent('AutoLinkDemo', () => AutoLinkDemo);
```
## Expected Behavior

`<Flat list should adopt to relevant direction as `I18nManager.isRtl` returns
## Actual Behavior

`<Flatlist> horizontal true` component does not work properly on Rtl devices, it renders the items again and jumps to head of list. impossible to use

if i add attribute ` legacyImplementation={true}` it works fine but as said in [documents](https://facebook.github.io/react-native/docs/flatlist.html#legacyimplementation) i doent know what traits of Flatlist i loose.

![rtl1](https://user-images.githubusercontent.com/10976856/39674002-29091110-514e-11e8-94a5-de09bbe45cf1.gif)
![rtl](https://user-images.githubusercontent.com/10976856/39674003-292c303c-514e-11e8-822f-bbfa9f1db648.gif)

**Comment by DanGDroid** [comment]
not fixed yet on RN 0.56
is this issue being handled by some one?

**Comment by DanGDroid** [comment]
not fixed on RN 0.57

**Comment by kevinkevw** [comment]
still experiencing this error (RN 0.55.4). 
have to disable RTL if using horizontal flatlist / scrollview.

If the list data / content doesn't update, it works fine.
Otherwise everytime the inner content updated, the list jump back to the top,
and onEndReached event will keep firing as well.

Using legacyImplementation={true} helps. But you can't use scrollTo, onViewableItemsChanged or other interactive functions, because it will generate errors. 

Can someone look into this issue, please?

**Comment by DanGDroid** [comment]
@shergin @javache @hramos @sahrens 
still not fixed,
can some one please handle this bug for the sake of millions users that use RTL languages

**Comment by hramos** [comment]
@DanGDroid let me know if there's a pull request we can take a look at.

**Comment by adirzoari** [comment]
same issue. any solution?

**Comment by DanGDroid** [comment]
no solution but to do it your own, i implemented a lazy loader of ScrollView but does not have all the benefits of a virtualised list

**Comment by sahrens** [comment]
What about `disableVirtualization={true}`? Don't have much time to look at this now - would love a PR :)

**Comment by adirzoari** [comment]
@sahrens I tried now, it's not working. it's still from left to right.

**Comment by FadiAboMsalam** [comment]
any update on this ?? still facing this only in RTL react-native version 0.57.3

**Comment by FadiAboMsalam** [comment]
is there any plan to fix the horizontal flatlist for RTL ?

**Comment by sahrens** [comment]
We have an internal task tracking this: T42861459

**Comment by FadiAboMsalam** [comment]
@sahrens  would please let me know what is the status of this internal task is there going to be any solution soon ?

**Comment by hramos** [comment]
While we are tracking this internally, this issue is still up for grabs. If anyone from the community is interested in providing a pull request, please go ahead.

**Comment by sammy-SC** [comment]
Before this issue is resolved a quick workaround for now is to set `initialNumToRender` to number of items to be rendered.

**Comment by YazeedAsaad** [comment]
anyone found a solution to this yet ? as @sammy-SC  said i tried initialNumToRender but it causes huge performance issues with a large list

**Comment by ajithes111** [comment]
+1

**Comment by ENategh** [comment]
adding `inverted={true}` just worked for me:
`<FlatList
        inverted={true}
        horizontal={true} />`

**Comment by BeshoyEkram** [comment]
+1

**Comment by matinzd** [comment]
There is another problem with scrollToItem! It works perfectly on iOS but it will get lost in android!

**Comment by amusbahisa** [comment]
+1

**Comment by mm7mod** [comment]
> What about `disableVirtualization={true}`? Don't have much time to look at this now - would love a PR :)

the only solution that worked for me,  but in the react-native documentation it says : 

Deprecated. Virtualization provides significant performance and memory optimizations, but fully unmounts react instances that are outside of the render window. You should only need to disable this for debugging purposes.

not sure if there should be a better solution for this

**Comment by DanGDroid** [comment]
> > What about `disableVirtualization={true}`? Don't have much time to look at this now - would love a PR :)
> 
> the only solution that worked for me, but in the react-native documentation it says :
> 
> Deprecated. Virtualization provides significant performance and memory optimizations, but fully unmounts react instances that are outside of the render window. You should only need to disable this for debugging purposes.
> 
> not sure if there should be a better solution for this

this is only a work-arount
we should expect a buildin solution.

**Comment by blazk0** [comment]
Having the same issue here, its open since 2018 ..

**Comment by MoeMamdouh** [comment]
> What about `disableVirtualization={true}`? Don't have much time to look at this now - would love a PR :)

yes working, but loose the performance

**Comment by MoeMamdouh** [comment]
this library helped me in this issue 
[https://github.com/Flipkart/recyclerlistview](https://github.com/Flipkart/recyclerlistview)

**Comment by praveens96** [comment]
even LTR has the issue in horizontal

**Comment by FatemeMirzaeii** [comment]
It's 2020!

**Comment by dagan-arbox** [comment]
2020 is a bad year, but may be this will get a fix?!

**Comment by mehthabux** [comment]
Any luck ?

**Comment by arasrezaei** [comment]
Please fix this issue it's really anoying!

**Comment by mm7mod** [comment]
30 years later  : hey react native the issue still exits any luck , it has been open for 30 years now

**Comment by H4ckint0sh** [comment]
You really need to fix this!

**Comment by jesspinklet** [comment]
T_T

**Comment by DevineDecrypter** [comment]
why is this issue not getting fixed ! its been more than 3 years and this is a big issue when it comes down to writing react native apps with some rtl based languages

**Comment by DanGDroid** [comment]
i think we should share this thread as much as possible for people to comment
and mention RN contributors as much as possible

**Comment by mohammadrahmanian** [comment]
I'm facing the same issue and I cannot use `disableVirtualization={true}` because of performance issues it creates. 
Please fix this bug :((

**Comment by Mersall** [comment]
{ direction: userLanguage === "ar" ? "rtl" : "ltr" },

**Comment by jesspinklet** [comment]
@Mersall  
I don't think direction would work in this situation

**Comment by ozanhonamlioglu** [comment]
Still no luck!

**Comment by ozanhonamlioglu** [comment]
Hey Guys, I am working in an Arabic company, and I encountered this issue, and solved this problem.
Here is how I solved my problem and adopted FlatList into RTL.

Please read the comment lines,  I tried to explain everything through comment lines.

```typescript

/*
 Once this script is called, I need to scroll to a position in onMount state of the app, and even need to center it.
 If there was not a requirement for RTL then scrollToIndex was enough, but since this should be a RTL app, I needed to 
 make it via using offsets.
*/

const MyHorizontalRTLFriendlyProblematicFlatList: React.FC<Props> = props => {
	const { width } = useWindowDimensions();
	const listRef = useAnimatedRef<FlatList>();
	const listItemWidthRef = useRef<number[]>([]);
	const [didLayoutCalculationDone, setDidLayoutCalculationDone] = useState(false);

        // FlatList data comes from other page via rouiting
        const flatlistdata = props.navigationState.routes;

         // Those two parameter coming to this component from other page while routing.
	const currentIndex = props.navigationState.index;
	const currentItemKey = flatlistdata[currentIndex].key;

	useEffect(() => {
                // This one is simple as its name, I am repositioning once the Items are looped in the Flatlist and rendered.
               // Now it is time to scrollTo a specific offset.
		if (didLayoutCalculationDone) setTabItemPosition();
	}, [didLayoutCalculationDone]);

        // With this method, I am collection every horizontal flatlist element widths into reference
       // I will need this once I needed to use scrollToOffset
	const onLayout = (index: number, event: LayoutChangeEvent): void => {
		listItemWidthRef.current[index] = event.nativeEvent.layout.width;

                 // since I need to reposition flatlist onMount, I need to know when the layout calculations are done!
                // So I am simply comparing item index with the source length. And updating the state didLayouCalculationDone
		if (index === flatlistdata.length - 1) setDidLayoutCalculationDone(true);
	};


        // This is where all magic is happen. scroll to an offset, end even make it centered
	const setTabItemPosition = () => {
                // First I compare the item's width against window width.
		const viewOffset = width / 2 - listItemWidthRef.current[currentIndex] / 2;
                const totalWidth = listItemWidthRef.current?.reduce((previousValue, currentValue) => previousValue + currentValue);
                // Second, I calculate the total width towards the Item that I want to scroll but not including the item's own width.
		const totalWidthUntilCurrentIndex = listItemWidthRef.current?.reduce(
			(previousValue, currentValue, i) => previousValue + (i < currentIndex ? currentValue : 0)
		);

                // There is one thing to note. RTL and LTR is working well on android even we use horizontal Flatlist and scrollToIndex
                // But since we use scrollToOffSet we need to make some adjustments for Android aswell.
		const calculatePosition =
			Platform.OS === "android" && I18nManager.isRTL
				? totalWidth - (totalWidthUntilCurrentIndex + listItemWidthRef.current[currentIndex]) - viewOffset
				: totalWidthUntilCurrentIndex - viewOffset;

                 // Lets Rock! Now I have all the informations for scrolling to a position
                // actually it is enogh to call only with totalWidthUntilCurrentIndex parameter but
                // since i need to reposition the item in the center of the screen, simply extract viewOffset.
                // Then everything works now. It even works on LTR, RTL, iOS, Android
		listRef.current?.scrollToOffset({ animated: true, offset: calculatePosition });
	};

	return (
		<FlatList
			ref={listRef}
			horizontal
			data={flatlistdata}
			showsHorizontalScrollIndicator={false}
			renderItem={({ item, index }: any) => (
                                 // by calling onLayout method, I am simply gathering every items own width and storing them into ref.
				<Pressable px="3" onLayout={event => onLayout(index, event)}>
					<Text pt="3" pb="2" color="white">
						{item.title}
					</Text>
					<IfElse condition={currentItemKey === item.key}>
						<Box h="0.5" w="full" bg="secondary.500" />
					</IfElse>
				</Pressable>
			)}
		/>
	);
};


```

If you are familiar and comfortable with those calculation parameters, I promise you once you get the logic, it will definitely work.

**Comment by AMINEDGE** [comment]
> adding `inverted={true}` just worked for me:
> `<FlatList inverted={true} horizontal={true} />`

worked well, thanks

**Comment by fkazemi5236** [comment]
> 

maybe this is better for show data in list in RTL layout:

```
<FlatList
						nestedScrollEnabled
						data={Calendar.reverse()}
						keyExtractor={item => item.visit_day_identity}
						renderItem={renderItem}
						horizontal
						pagingEnabled
						showsHorizontalScrollIndicator={false}
						snapToEnd
						ref={element}
						inverted={true}
					/>**
```**

**Comment by matinzd** [comment]
> > 
> 
> maybe this is better for show data in list in RTL layout:
> 
> ```
> 
> <FlatList
> 	nestedScrollEnabled
> 	data={Calendar.reverse()}
> 	keyExtractor={item => item.visit_day_identity}
> 	renderItem={renderItem}
> 	horizontal
> 	pagingEnabled
> 	showsHorizontalScrollIndicator={false}
> 	snapToEnd
> 	ref={element}
> 	inverted={true}
> />
> ```

`scrollToIndex` or `scrollToItem` function will not properly work in this case.

**Comment by fkazemi5236** [comment]
> > > 
> > 
> > 
> > maybe this is better for show data in list in RTL layout:
> > ```
> > 
> > <FlatList
> > 	nestedScrollEnabled
> > 	data={Calendar.reverse()}
> > 	keyExtractor={item => item.visit_day_identity}
> > 	renderItem={renderItem}
> > 	horizontal
> > 	pagingEnabled
> > 	showsHorizontalScrollIndicator={false}
> > 	snapToEnd
> > 	ref={element}
> > 	inverted={true}
> > />
> > ```
> 
> `scrollToIndex` or `scrollToItem` function will not properly work in this case.

Yes that's right. What do you suggest?

**Comment by kirill0012** [comment]
2018 -> 2022 ! 
Good going !

Still exist...

**Comment by matinzd** [comment]
> @matinzd Yes that's right. What do you suggest?
> 
> I found this solution. `scrollToIndex` or `scrollToItem` work in this
> 
> ```
> <FlatList
> 		nestedScrollEnabled
> 		data={Calendar}
> 		keyExtractor={item => item.visit_day_identity}
> 		renderItem={renderItem}
> 		horizontal
> 		snapToEnd
> 		ref={ElementRef}
> 		style={{flexDirection: 'row-reverse'}}
> 	/>
> ```

There is not a good solution for it right now but you have some workarounds. React native core team should consider this problem I think and work on the fix. There are many works going on, especially for rolling out the new architecture.

**Comment by syedumerali** [comment]
2022 any solution for this?

**Comment by FadiAboMsalam** [comment]
I think we need to wait for another four years to have a fix 😂

**Comment by matinzd** [comment]
@FadiAboMsalam 
There are some other third party projects working on new list view with power of new architecture. Maybe that can help to get rid of these issues with FlatList. 

https://mobile.twitter.com/margelo_io/status/1519021945295151109

**Comment by Stevemoretz** [comment]
I'm in my 20s but I won't probably live long enough to see this would ever get fixed, so if you have a fixed item size you can still use : 

```tsx
flatListSlider.current.scrollToOffset({
    offset: width * index,
    animated: true,
});
```

This will give the result on RTL and LTR.

**Comment by noway** [comment]
This is still happening for us - FlatList with RTL on android simply jumps to second or third item instead of first item. We have 87 items in the list so it might precision issues with scrolling to the end.

**Comment by Stevemoretz** [comment]
> This is still happening for us - FlatList with RTL on android simply jumps to second or third item instead of first item. We have 87 items in the list so it might precision issues with scrolling to the end.

This issue has changed for the worse in the latest version, this isn't the same issue that you're describing.

The bug you are describing :
https://github.com/facebook/react-native/issues/34314

Right now there is no tricks to fix it with js anymore, also when you scroll a large list, it scrolls back to that weird position you mentioned.

This issue right now literally makes react native unusable for any app that supports rtl!!!

**Comment by arasrezaei** [comment]
Hello there,
Just please use flashlist:
https://shopify.github.io/flash-list/docs/usage
And contribute to it, much much better and performant option :)

**Comment by Stevemoretz** [comment]
> Hello there, Just please use flashlist: https://shopify.github.io/flash-list/docs/usage And contribute to it, much much better and performant option :)

Thank you for your kind suggestion however there are a few things wrong with it.

1. Rtl is not okay itself in flashlist https://github.com/Shopify/flash-list/issues/544
2. Even if they fix that there are many libraries using the flatlist internally.

This issue is old and the problem described here doesn't happen anymore a new problem occurs on the 0.68 or sdk 45 for expo

https://github.com/facebook/react-native/issues/34314

Maybe it's better to close this and move there? @DanGDroid

**Comment by Stevemoretz** [comment]
> We have an internal task tracking this: T42861459

And could you please also inform us about the state of that task and if you have considered the new issue? https://github.com/facebook/react-native/issues/34314

**Comment by matinzd** [comment]
> We have aninternal task tracking this: T42861459

Any updates on this internal issue? @cortinico

**Comment by Stevemoretz** [comment]
> 

These are all true but most of them are fixable with workaround the recent bug on the latest version though has no workarounds that's a terrible bug have you noticed it too?

On 0.68, just on start it will have a wrong scroll position and when you scroll far away it gets back that initial wrong position, this is like a major issue with no workarounds right now.

**Comment by matinzd** [comment]
> These are all true but most of them are fixable with workaround the recent bug on the latest version though has no workarounds that's a terrible bug have you noticed it too?
> 
> On 0.68, just on start it will have a wrong scroll position and when you scroll far away it gets back that initial wrong position, this is like a major issue with no workarounds right now.

I have been experiencing this since I started working with rn 6 years ago 😅

**Comment by Stevemoretz** [comment]
> > These are all true but most of them are fixable with workaround the recent bug on the latest version though has no workarounds that's a terrible bug have you noticed it too?
> > On 0.68, just on start it will have a wrong scroll position and when you scroll far away it gets back that initial wrong position, this is like a major issue with no workarounds right now.
> 
> I have been experiencing this since I started working with rn 6 years ago 😅

On expo sdk 44, everything was almost fine with flatlist there was one slight issue only which could be fixed via a workaround.

The issue I'm mentioning happened quite recently though.

**Comment by noway** [comment]
I'm currently working on switching `<FlatList` to https://github.com/Flipkart/recyclerlistview whilst using https://github.com/Flipkart/recyclerlistview/pull/629 as the RTL patch. Will report back if it's viable.

**Comment by noway** [comment]
Hi guys, recyclerlistview is working great for me - using it with 
```
								isHorizontal={true}
								pagingEnabled={true}
```
+ RTL language (Hebrew) on Android, and not having any issues.

Cheers.

**Comment by Stevemoretz** [comment]
> Hi guys, recyclerlistview is working great for me - using it with
> 
> ```
> isHorizontal={true}
> pagingEnabled={true}
> ```
> 
> and with RTL language (Hebrew) on Android, and not having any issues.
> 
> Cheers.

Thank you for reporting back, so you only applied that patch?

Isn't it more convenient for you to use flashlist from Shopify it works with recyclereview internally but provides a syntax same as FlatList.

That would make the migration of existing apps also easier I applied the patch of that PR and all yet couldn't get it working yet, didn't use the pagingEnabled though was that mandatory?

**Comment by noway** [comment]
I only had to apply the patch https://github.com/Flipkart/recyclerlistview/pull/629 on the latest version of `recyclerlistview` (4.1.1 at the moment)

`pagingEnabled` is not mandatory - we just use pages in our design.

I considered [flash-list](https://github.com/Shopify/flash-list) but it has fewer GitHub stars than [recyclerlistview](https://github.com/Flipkart/recyclerlistview).

**Comment by zanyar3** [comment]
> 2022 any solution for this?

add `inverted={true}` to **FaltList**.
Work for me

**Comment by demedos** [comment]
> > Hi guys, recyclerlistview is working great for me - using it with
> > ```
> > isHorizontal={true}
> > pagingEnabled={true}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and with RTL language (Hebrew) on Android, and not having any issues.
> > Cheers.
> 
> Thank you for reporting back, so you only applied that patch?
> 
> Isn't it more convenient for you to use flashlist from Shopify it works with recyclereview internally but provides a syntax same as FlatList.
> 
> That would make the migration of existing apps also easier.
> 
> I applied the patch of that PR [Shopify/flash-list#544 (comment)](https://github.com/Shopify/flash-list/issues/544#issuecomment-1203687961) and all yet couldn't get it working yet, didn't use the pagingEnabled though was that mandatory?

FlashList has some other issues with RTL, see https://github.com/Shopify/flash-list/issues/544 and https://github.com/Shopify/flash-list/issues/620. Recyclerlistview with this patch https://github.com/Flipkart/recyclerlistview/pull/629 is the best solution at the moment

**Comment by dev-arson** [comment]
Hello, I created solution for this bug, not perfect but almost working.

```

  import React, { useEffect, useRef, useState } from 'react'; 
  import { FlatList, I18nManager, Platform as DevicePlatform } from 'react-native';
  import { useFocusEffect, useNavigation } from '@react-navigation/native';
  import { Platform } from 'enums';

export default function UiFlatlist(props) {
  const ref = useRef();

  const {
    columnWrapperStyle = {},
    contentContainerStyle = {},
    data = [],
    getItemLayoutForScrollIndex,
    horizontal = false,
    initialNumToRender = 10,
    initialScrollIndex = 0,
    keyExtractor = ({ id }) => id,
    maxToRenderPerBatch = 1,
    numColumns = 1,
    onScroll = () => {},
    pagingEnabled = false,
    removeClippedSubviews = DevicePlatform.OS !== Platform.IOS, // for my own logic
    renderItem = () => {},
    scrollIndicatorInsets,
    setRef,
    inverted,
    showsHorizontalScrollIndicator = false,
    updateCellsBatchingPeriod = 100,
    // Note: 10 viewports above, 10 below, and one in between
    windowSize = 21,
  } = props;

  const overrideScroll = DevicePlatform.OS === Platform.ANDROID && inverted;

  const navigation = useNavigation();
  const [scrollPosition, setScrollPosition] = useState(0);
  const [canScrollToStart, setCanScrollToStart] = useState(true);
  const [wasRunned, setWasRunned] = useState(false);

  if (overrideScrolls) {
    useFocusEffect(() => {
      if (!wasRunned) {
        if (ref && ref.current) {
          setWasRunned(true);
          setTimeout(() => {
            ref.current.scrollToOffset({
              offset: scrollPosition
              });
            setCanScrollToStart(false);
          }, 100);
        }
      }
    });

    useEffect(() => {
      navigation.addListener('blur', () => {
        setCanScrollToStart(true);
        setWasRunned(false);
      });
    }, [navigation]);
  }

  useEffect(() => {
    if (setRef) {
      setRef(ref);
    }
  }, [ref]);

  const handleOnScroll = (e) => {
    setScrollPosition(e.nativeEvent.contentOffset.x);
    onScroll(e);
  };

  return (
    <FlatList
      columnWrapperStyle={numColumns > 1 ? columnWrapperStyle : null}
      contentContainerStyle={{
        ...contentContainerStyle,
        ...(overrideScrolls ? { flexDirection: 'row-reverse' } : {}),
      }}
      data={data}
      getItemLayout={getItemLayoutForScrollIndex}
      horizontal={horizontal}
      initialNumToRender={initialNumToRender}
      initialScrollIndex={initialScrollIndex}
      keyExtractor={keyExtractor}
      maxToRenderPerBatch={maxToRenderPerBatch}
      numColumns={numColumns}
      onScrollToIndexFailed={() => {}}
      onScroll={handleOnScroll}
      pagingEnabled={pagingEnabled}
      ref={ref}
      inverted={overrideScrolls}
      removeClippedSubviews={removeClippedSubviews}
      renderItem={renderItem}
      scrollIndicatorInsets={scrollIndicatorInsets}
      showsHorizontalScrollIndicator={showsHorizontalScrollIndicator}
      updateCellsBatchingPeriod={updateCellsBatchingPeriod}
      windowSize={windowSize}
    />
  );
}

```  

This code allow to use horizontal list in RTL app , but when we have paggination enabled after scroll and new page was added then list jump to last itemIndex %  maxToRenderPerBatch

Code is not perfect, after 5 years of inactivity from Facebook side I think
better that than nothing :)

**Comment by Stevemoretz** [comment]
> Hello, I created solution for this bug, not perfect but almost working.
> 
> ```
> 
>   import React, { useEffect, useRef, useState } from 'react'; 
>   import { FlatList, I18nManager, Platform as DevicePlatform } from 'react-native';
>   import { useFocusEffect, useNavigation } from '@react-navigation/native';
>   import { Platform } from 'enums';
> 
> export default function UiFlatlist(props) {
>   const ref = useRef();
> 
>   const {
>     columnWrapperStyle = {},
>     contentContainerStyle = {},
>     data = [],
>     getItemLayoutForScrollIndex,
>     horizontal = false,
>     initialNumToRender = 10,
>     initialScrollIndex = 0,
>     keyExtractor = ({ id }) => id,
>     maxToRenderPerBatch = 1,
>     numColumns = 1,
>     onScroll = () => {},
>     pagingEnabled = false,
>     removeClippedSubviews = DevicePlatform.OS !== Platform.IOS, // for my own logic
>     renderItem = () => {},
>     scrollIndicatorInsets,
>     setRef,
>     inverted,
>     showsHorizontalScrollIndicator = false,
>     updateCellsBatchingPeriod = 100,
>     // Note: 10 viewports above, 10 below, and one in between
>     windowSize = 21,
>   } = props;
> 
>   const overrideScroll = DevicePlatform.OS === Platform.ANDROID && inverted;
> 
>   const navigation = useNavigation();
>   const [scrollPosition, setScrollPosition] = useState(0);
>   const [canScrollToStart, setCanScrollToStart] = useState(true);
>   const [wasRunned, setWasRunned] = useState(false);
> 
>   if (overrideScrolls) {
>     useFocusEffect(() => {
>       if (!wasRunned) {
>         if (ref && ref.current) {
>           setWasRunned(true);
>           setTimeout(() => {
>             ref.current.scrollToOffset({
>               offset: scrollPosition
>               });
>             setCanScrollToStart(false);
>           }, 100);
>         }
>       }
>     });
> 
>     useEffect(() => {
>       navigation.addListener('blur', () => {
>         setCanScrollToStart(true);
>         setWasRunned(false);
>       });
>     }, [navigation]);
>   }
> 
>   useEffect(() => {
>     if (setRef) {
>       setRef(ref);
>     }
>   }, [ref]);
> 
>   const handleOnScroll = (e) => {
>     setScrollPosition(e.nativeEvent.contentOffset.x);
>     onScroll(e);
>   };
> 
>   return (
>     <FlatList
>       columnWrapperStyle={numColumns > 1 ? columnWrapperStyle : null}
>       contentContainerStyle={{
>         ...contentContainerStyle,
>         ...(overrideScrolls ? { flexDirection: 'row-reverse' } : {}),
>       }}
>       data={data}
>       getItemLayout={getItemLayoutForScrollIndex}
>       horizontal={horizontal}
>       initialNumToRender={initialNumToRender}
>       initialScrollIndex={initialScrollIndex}
>       keyExtractor={keyExtractor}
>       maxToRenderPerBatch={maxToRenderPerBatch}
>       numColumns={numColumns}
>       onScrollToIndexFailed={() => {}}
>       onScroll={handleOnScroll}
>       pagingEnabled={pagingEnabled}
>       ref={ref}
>       inverted={overrideScrolls}
>       removeClippedSubviews={removeClippedSubviews}
>       renderItem={renderItem}
>       scrollIndicatorInsets={scrollIndicatorInsets}
>       showsHorizontalScrollIndicator={showsHorizontalScrollIndicator}
>       updateCellsBatchingPeriod={updateCellsBatchingPeriod}
>       windowSize={windowSize}
>     />
>   );
> }
> ```
> 
> This code allow to use horizontal list in RTL app , but when we have paggination enabled after scroll and new page was added then list jump to last itemIndex % maxToRenderPerBatch
> 
> Code is not perfect, after 5 years of inactivity from Facebook side I think better that than nothing :)

Thanks for sharing, seriously what is wrong with Facebook, it's not like they don't have rtl apps themselves do yourself a favor at least

**Comment by AHMED-5G** [comment]
![ltrggg](https://user-images.githubusercontent.com/75797110/236608530-d50d5383-e4ff-4ca0-aa9a-cbb26b8fafaf.gif)

I made a solution for this issue, hope it's working good with you.

Try this package
https://www.npmjs.com/package/react-native-localized-flatlist-rtl-ltr

https://github.com/AHMED-5G/react-native-localized-flatlist-rtl-ltr

**Comment by Stevemoretz** [comment]
> I made a solution for this issue, hope it's working good with you.
> 
> Try this package https://www.npmjs.com/package/react-native-localized-flatlist-rtl-ltr
> 
> https://github.com/AHMED-5G/react-native-localized-flatlist-rtl-ltr
> 
> ![ltrggg](https://user-images.githubusercontent.com/75797110/236608530-d50d5383-e4ff-4ca0-aa9a-cbb26b8fafaf.gif) [ ![ltrggg](https://user-images.githubusercontent.com/75797110/236608530-d50d5383-e4ff-4ca0-aa9a-cbb26b8fafaf.gif) ](https://user-images.githubusercontent.com/75797110/236608530-d50d5383-e4ff-4ca0-aa9a-cbb26b8fafaf.gif) [ ](https://user-images.githubusercontent.com/75797110/236608530-d50d5383-e4ff-4ca0-aa9a-cbb26b8fafaf.gif)

Thank you finally something about this.
One question have you tried with more items try 50 instead of 5.

One huge problem with the current flatlist of react native is that when you scroll it scrolls back it starts at the middle also instead of beginning you scroll forward like go more than 10 items it suddenly scrolls back to the 5th items and so on.

Can you verify this problem doesn't exist with your package?

Also I checked you have android and ios folder in your github but in your readme's installation only mention `yarn` you probably forgot to mention it's not a Javascript library and needs more actions like `pod install`?

**Comment by AHMED-5G** [comment]
> Can you verify this problem doesn't exist with your package?
> 
> Also I checked you have android and ios folder in your github but in your readme's installation only mention `yarn` you probably forgot to mention it's not a Javascript library and needs more actions like `pod install`?

I'm sorry, my solution fixing margin when change language with LTR systems, so it's not solving these issues.

**Comment by dev-arson** [comment]
https://github.com/facebook/react-native/pull/37651
In rn-tester app this fix works

**Comment by kartiikeyabaleneni** [comment]
Issue Still Exists in React Native 0.70.10 , Any working solutions , Please let us know .
If RN team has fixed this issue in latest RN version ?

**Comment by mmujtabam** [comment]
Still open

**Comment by mohamed2m2018** [comment]
issue still exists

**Comment by NickGerleman** [comment]
This issue is fixed in RN 0.73.

**Comment by AmrAyman-G** [comment]
<img width="1153" alt="Screenshot 2023-10-30 at 10 21 54 PM" src="https://github.com/facebook/react-native/assets/100245739/1939211a-953e-446d-80c5-f1b09357adea">

This issue is still not fixed on android and RN  0.73 not released yet ?

**Comment by seyedmostafahasani** [comment]
I have released a new library where I attempted to address this issue. Please check it out. 
You can see it in this [link](https://github.com/seyedmostafahasani/react-native-horizon-list)

**Comment by codefreak13** [comment]
> I have released a new library where I attempted to address this issue. Please check it out. You can see it in this [link](https://github.com/seyedmostafahasani/react-native-horizon-list)

In your library, where did you implement the scroll ref?
FYI, this issue is about scroll ref on Android RTL not working properly

**Comment by codefreak13** [comment]
The solution for the Android RTL is to use scrollToIndex instead of scrollToOffset

`  
   const flatListRef = useRef<FlatList | null>(null);

   const scrollToSelectedFeed = useCallback(
      (offset?: boolean) => {
         if (flatListRef.current) {
            const selectedIndex = list?.findIndex((item) => item.name === current);
            if (selectedIndex !== -1) {
               const totalWidthBeforeSelected = list
                  .slice?.(0, selectedIndex)
                  .reduce?.((acc, item) => acc + calculateChipButtonWidth(item), 0);
               if (offset) {
                  flatListRef.current.scrollToOffset({ offset: totalWidthBeforeSelected, animated: true });
               } else {
                  flatListRef.current.scrollToIndex({ index: selectedIndex, animated: true });
               }
            }
         }
      },
      [current, list, flatListRef.current]
   );
   
   
       <FlatList
         ref={(ref) => (flatListRef.current = ref)}
         data={list}
         horizontal
         showsHorizontalScrollIndicator={false}
         renderItem={renderItem}
         keyExtractor={(item) => item.name}
         onScrollToIndexFailed={() => scrollToSelectedFeed(true)}
         inverted={I18nManager.isRTL}
      />`

**Comment by haipv01** [comment]
> I have released a new library where I attempted to address this issue. Please check it out. You can see it in this [link](https://github.com/seyedmostafahasani/react-native-horizon-list)

I see you custom RTL horizontal list view by ScrollView. It wrong in the began

**Comment by aattalla** [comment]
Has the fix for this issue been released yet?

**Comment by abdelhamied403** [comment]
quick hack i did

for RTL you can wrap the flat list in ltr view
and invert the flat list
don't forget to add a view to the renderItem function with the correct direction

so it's gonna look like this for it to work on both directions

```tsx
<View style={{ direction: "ltr" }}>
  <FlatList
    contentContainerStyle={{
      gap: 8,
    }}
    horizontal
    data={data}
    renderItem={(...props) => (
      <View style={{ direction: locale.dir }}>
        {renderItem?.(...props)}
      </View>
    )}
    {...props}
    inverted={locale.dir === "rtl"}
  />
</View>
```
