### ISSUE TITLE
marginBottom and marginTop cutting children? [Need better title]

### ISSUE THREAD

**Issue by FlaviooLima** [facebook/react-native#19164]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

[iOS] When you use percentage in marginBottom or marginTop it kind cuts the children inside. 
Tested with Text, and Views component

Devices:  [Simulator iPhone 5s, Simulator iPhone 7, Simulator iPhone X, Real device iPhone 6s]

[Android] Sometimes happens to the views only.
Devices: Samsung S5 mini

For some reason with marginHorizontal:"20%"  or if we remove the "flex:1" from the main View the bug doesn't occur. 
But sometimes even without "flex:1" property the bug still occurs. There should be a group of properties that activate this bug or not.

## Environment
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.8.0
  Yarn: 1.6.0
  npm: 6.0.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: ^16.3.1 => 16.3.1
  react-native: ^0.54.0 => 0.55.3

## Steps to Reproduce
https://snack.expo.io/rJtl8WR6G
```
      <View style={{ flex: 1, justifyContent:'center',alignItems:'center'}}>
   		<View style={{ marginTop: "8%"}}>
			<Text style={{ fontSize: 40, fontWeight: '700' }}>ASdsad</Text> 
		</View>
      </View>
```
## Expected Behavior
To not cut the children!

## Actual Behavior
Cutting the Children!

**Comment by FlaviooLima** [comment]
@hramos Please Evaluate the issue.
I believe this is a real issue.

**Comment by FlaviooLima** [comment]
@react-native-bot open

**Comment by nikolal** [comment]
@FlaviooLima 

Yes I am also using percentages and still have an issue.

The issue started once I upgraded to React native/Expo sdk 26.

Before that, everything worked normally.

**Comment by FlaviooLima** [comment]
@nikolal I use react-native only and this start happening after I upgraded to v54 and v55. v53 no bugs there.
it's a shame that this is happening, and I don't understand why people are not complaining more.
I believe this is a HUGE bug.

**Comment by NicholasBertazzon** [comment]
@FlaviooLima Not only margin, but also there are problems with padding and text. I get text truncated, images that doesn't have the same size as in 0.53. Padding that sometimes works as before, sometimes not.

**Comment by azabost** [comment]
Happens to me with RN 0.55.4 as well. This issue should be reopened.

**Comment by brettdh** [comment]
I also noticed this after an upgrade and while preparing a test repo for #22039.

Not sure how the bot identified this as a question rather than a bug, but that should also be addressed.

**Comment by nikolal** [comment]
My temporary solution is to convert % to px for each component and passing it down the tree. I am building dynamic app where users are choosing width and height so I don't have control of width and height  and users must use % values. I am not sure if it will help you.

It goes something like this:

`
  getDimensions = (layout) => {
    const { width, height } = layout;
    this.setState({ width: width });
    this.setState({ height: height });
  }

  <View
    style={this.styles.container}
    onLayout={(event) => { this.getDimensions(event.nativeEvent.layout); }}
  >
`
Later I calculate height based on those values. In example below, height and width are % value for current component, while parentHeight and parentWidth are values that i am passing from parents ( calculated above ).
`
      height: parentHeight ? parseFloat(height) / 100 * parentHeight : height,
      width: parentWidth ? parseFloat(width) / 100 * parentWidth : width,
`

I am rendering components dynamically using recursive loop so I auto pass these values from parents to children.

Probably not useful to manby people if you have to do this in each component.

This issue should really be fixed, especially since we know exactly when it started.

**Comment by nikolal** [comment]
This is the same issue:  https://github.com/facebook/react-native/issues/18911

**Comment by pechar** [comment]
Still and issue and nothing has been done about it. All worked well before. I can confirm it still happens on 0.57. The only solution I found was to add the margin to the first element within the wrapping view. So for example:
```
<View style={{marginTop:'5%'}}>
    <Text>Bla</Text>
</View>
// now needs to be:
<View>
    <Text style={{marginTop:'5%'}}>Bla</Text>
</View>
```

However if you try to inspect the elements you still get the error:
`JSON value '5%' of type NSString cannot be converted to NSNumber.`

This issue should be re-opened!
