### ISSUE TITLE
IOS bug - Error occurred, shutting down websocket connection

### ISSUE THREAD

**Issue by zaporozhetsAnton** [facebook/react-native#19160]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.3.0
  Yarn: 1.3.2
  npm: 5.5.1
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.3 => 0.55.3

## Steps to Reproduce
I have a project on react-native v 0.48.2 with many module dependencies.
I need to update this project to recent version of rn. For this I created new project by `react-native init AwesomeProject` and integrate there all dependencies and code from old working project.
Now when I open project in simulator i see error -
Error occurred, shutting down websocket connection: Websocket exception Error Domain=RCTSRWebSocketErrorDomain Code=2132 "received bad response code from server 400" 
http://prntscr.com/jettrx

## Actual Behavior
http://prntscr.com/jettrx

**Comment by zaporozhetsAnton** [comment]
This error appears again and again and app don't work correctly.

**Comment by dashakdsr** [comment]
+

**Comment by heronlyj** [comment]
same error in simulator, but work in device(iOS).

**Comment by ithustle** [comment]
+++++++++++++
