### ISSUE TITLE
IOS - Crashes in RCTImageLoader canHandleRequest when the app starts

### ISSUE THREAD

**Issue by aknad** [facebook/react-native#19179]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [ ] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

we use App Center to track crashes
in the last two months we saw a lot of _RCTImageLoader canHandleRequest_ crashes

<img width="973" alt="screen shot 2018-05-08 at 10 04 36" src="https://user-images.githubusercontent.com/7056879/39745380-5f59cc32-52a7-11e8-9396-095d3b58a4f7.png">

the app crashes 3 or 4 second after the start

## Environment
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 6.2.2
  Yarn: 0.27.5
  npm: 4.5.0
  Watchman: 4.1.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.51.0 => 0.51.0

## Steps to Reproduce
We can't reproduce it, we only saw it in the crash report

**Comment by xiaoyongchen** [comment]
Hi，@aknad 。I have the same question. How did you solve it?

**Comment by aknad** [comment]
> Hi，@aknad 。I have the same question. How did you solve it?

unfortunately we have not solved it
we'll try to update RN in the next days but I don't think it's related to the version
what's your RN version?

**Comment by xiaoyongchen** [comment]
@aknad 0.47-0.51 There are problems in these versions.

**Comment by killar4eto** [comment]
Same problem here... on iOS it's crashing too...

![screenshot 2018-11-02 at 12 06 58](https://user-images.githubusercontent.com/19361520/47909190-d5036e80-de97-11e8-8e84-3f4b8db9a173.png)

**Comment by yongqianvip** [comment]
The version（0.50.4） I'm currently using also has this problem
