### ISSUE TITLE
How can i create bundle file to nodeJS server in production environment?

### ISSUE THREAD

**Issue by ycman0307** [facebook/react-native#19175]
I am first time to use react native to develop app. I would like to develop a app and put it into Apple store and android market. However, i want to update/urgent fix my app without validation by apple and google.

can i create js bundle and deploy to nodeJS server directly??

or any suggestions for me to use?

**Comment by rush1506** [comment]
If you just want a service that can do it. You can use [CodePush](https://github.com/Microsoft/react-native-code-push) by Microsoft or [Expo](https://expo.io/). They help you to deploy your app on the cloud and update your app content instantly.

**Comment by ycman0307** [comment]
Thank you for your reply. Which one do you recommend to use?

**Comment by ycman0307** [comment]
Is CodePush free for us to use? I am confuse that "react-native-code-push" in guthub is same as codePush in app center?

https://microsoft.github.io/code-push/
https://github.com/Microsoft/react-native-code-push

**Comment by rush1506** [comment]
They are the same, and yes codepush is free

**Comment by ycman0307** [comment]
I cannot find any document for teach me how to create deployment Key and project. where can i find the procedure for creating codePush project??
