### ISSUE TITLE
android onPress不响应问题

### ISSUE THREAD

**Issue by zc-Mukden** [facebook/react-native#19180]
this._panResponder = PanResponder.create（{

        onStartShouldSetResponder: (evt, gestureState) => true,
        onStartShouldSetResponderCapture: () => true,
        onMoveShouldSetPanResponder: () => true,
        onMoveShouldSetPanResponderCapture: () => true,

        onPanResponderGrant: (evt, gestureState) => {
            for (let x in this._touches) {
                if (evt.nativeEvent.touches[x]) {
                    this._touches[x].x = evt.nativeEvent.touches[x].pageX;
                    this._touches[x].y = evt.nativeEvent.touches[x].pageY;
                    this._touches[x].identifier = evt.nativeEvent.touches[x].identifier
                }
            }
        },

        //移动回调
        onPanResponderMove: (evt, gestureState) => {
            if (evt.nativeEvent.touches.length === 1) {
                if (this._touches[0].identifier === undefined) {

                    for (let x in this._touches) {
                        if (evt.nativeEvent.touches[x]) {
                            this._touches[x].x = evt.nativeEvent.touches[x].pageX;
                            this._touches[x].y = evt.nativeEvent.touches[x].pageY;
                            this._touches[x].identifier = evt.nativeEvent.touches[x].identifier
                        }
                    }
                    return false
                } else {

                    let moveX = evt.nativeEvent.touches[0].pageX - this._touches[0].x;
                    let moveY = evt.nativeEvent.touches[0].pageY - this._touches[0].y;

                    this.state.left += moveX;
                    this.state.top += moveY;
                    this.setState({
                        left: this.state.left,
                        top: this.state.top
                    });

                    for (let x in this._touches) {
                        if (evt.nativeEvent.touches[x]) {
                            this._touches[x].x = evt.nativeEvent.touches[x].pageX;
                            this._touches[x].y = evt.nativeEvent.touches[x].pageY;
                            this._touches[x].identifier = evt.nativeEvent.touches[x].identifier
                        }
                    }
                }
            } else {

                if (this._zoom === undefined) {

                    this._zoom = {
                        x: (evt.nativeEvent.touches[0].pageX + evt.nativeEvent.touches[1].pageX) / 2,
                        y: (evt.nativeEvent.touches[0].pageY + evt.nativeEvent.touches[1].pageY) / 2,
                        distance: Math.sqrt(
                            Math.pow(evt.nativeEvent.touches[0].pageX - evt.nativeEvent.touches[1].pageX, 2)
                            + Math.pow(evt.nativeEvent.touches[0].pageY - evt.nativeEvent.touches[1].pageY, 2)
                        )
                    };
                    return false
                } else {

                    let distanceTemp = Math.sqrt(
                        Math.pow(evt.nativeEvent.touches[0].pageX - evt.nativeEvent.touches[1].pageX, 2)
                        + Math.pow(evt.nativeEvent.touches[0].pageY - evt.nativeEvent.touches[1].pageY, 2)
                    );
                    let distanceAdd = distanceTemp - this._zoom.distance;
                    let distanceScale = distanceAdd / this._zoom.distance;

                    let scaleAdd = 0;
                    if (distanceScale === 0) {

                    } else {
                        scaleAdd = this.state.scale * distanceScale
                    }
                    let setScale = this.state.scale + scaleAdd;

                    this.state.left = (setScale / this.state.scale) *
                        (0.5 * this.state.width + this.state.left - this._zoom.x) -
                        0.5 * this.state.width + this._zoom.x;
                    this.state.top = (setScale / this.state.scale) *
                        (0.5 * this.state.height + this.state.top - this._zoom.y) -
                        0.5 * this.state.height + this._zoom.y;

                    this.state.scale = setScale;

                    this._zoom.distance = distanceTemp;
                    this.setState({
                        scale: this.state.scale,
                        left: this.state.left,
                        top: this.state.top
                    })
                }
            }
        },

        //松开回调
        onPanResponderRelease: (evt, gestureState) => {
            this._touches = [
                {},
                {}
            ];
            this._zoom = undefined;
        }
    })

**Comment by zc-Mukden** [comment]
简单的来说就是父组件如果带有PanResponder属性，子组件的可触摸的事件在安卓真机上很难响应，几乎不响应！

**Comment by zc-Mukden** [comment]
我做了一个浮动的可拖动菜单，但是浮动的TouchableOpacity的onPress 事件不响应。只有它不响应，其他的都响应，比如onPressIn,onPressOut等等

**Comment by zc-Mukden** [comment]
![qq 20180508153846](https://user-images.githubusercontent.com/37661252/39746887-efb487da-52d5-11e8-8bc5-ffb1cc103e7c.png)

**Comment by woshi82** [comment]
https://github.com/facebook/react-native/issues/6993

**Comment by woshi82** [comment]
This works!
