### ISSUE TITLE
on Android setting TextInput keyboardType prop will not work as expected

### ISSUE THREAD

**Issue by mydesweb** [facebook/react-native#19183]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

on Android setting TextInput keyboardType prop will not work as expected with the following types: 'numbers-and-punctuation', 'url', 'number-pad', 'name-phone-pad', 'decimal-pad', 'twitter', 'web-search', 'visible-password'

## Environment
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.9.1
  Yarn: 1.6.0
  npm: 5.7.1
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.3 => 0.55.3

## Steps to Reproduce
I just tested with different types from documentation
enum('numbers-and-punctuation', 'url', 'number-pad', 'name-phone-pad', 'decimal-pad', 'twitter', 'web-search', 'visible-password')

## Actual Behavior
the keyboard is not the right one, it is the same as for ascii-capable

<img width="344" alt="number-pad" src="https://user-images.githubusercontent.com/5901386/39762275-dad676ae-52e2-11e8-8f0d-ff515989be11.png">

**Comment by zibs** [comment]
Right in the documentation it says:

```
iOS Only

The following values work on iOS only:

ascii-capable
numbers-and-punctuation
url
number-pad
name-phone-pad
decimal-pad
twitter
web-search
```
 https://facebook.github.io/react-native/docs/textinput.html

**Comment by mydesweb** [comment]
@zibs I see now, the documentation is confusing , right near under Android section there is a table and I was thinking is applying to Android only.. ok then, I will close this issue

**Comment by devey** [comment]
@zibs, i see that now the docs say:
```
The following values work across platforms:

default
number-pad
decimal-pad
numeric
email-address
phone-pad
```
but `Android` seems still to show `default` tab if set to `number-pad` or `decimal-pad` anyway.

Environment:
`react@16.4.1`
`react-native@0.55.3`

**Comment by mydesweb** [comment]
@devey  upgrade your RN version to 57
