### ISSUE TITLE
react-native link fails when MainApplication is Kotlin instead of Java

### ISSUE THREAD

**Issue by faithfracture** [facebook/react-native#19185]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

Pretty self explanatory. `react-native link` does not work if your `MainApplication` is a Kotlin file rather than java.

I've tried this in an existing project and in a brand new one with nothing done other than what is described in "Steps to Reproduce"

## Environment
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.6.1
  Yarn: Not Found
  npm: 5.8.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.3 => 0.55.3

## Steps to Reproduce
Create a new app with `react-native init`
Convert  `MainApplication.java` and `MainActivity.java` to Kotlin
Add something that requires linking (I'm using Amazon Cognito)
Run `react-native link amazon-cognito-identity-js`

## Expected Behavior
I expect the link to succeed.

## Actual Behavior
Linking fails with the following message:
```
➜  test  react-native link amazon-cognito-identity-js
Scanning folders for symlinks in /Users/myuser/projects/testing/reactNative/test/node_modules (20ms)
rnpm-install info Linking amazon-cognito-identity-js ios dependency
rnpm-install info Platform 'ios' module amazon-cognito-identity-js has been successfully linked
rnpm-install info Linking amazon-cognito-identity-js android dependency
rnpm-install ERR! Something went wrong while linking. Error: ENOENT: no such file or directory, open '/Users/myuser/projects/testing/reactNative/test/android/app/src/main/java/com/test/MainApplication.java'
Please file an issue here: https://github.com/facebook/react-native/issues

ENOENT: no such file or directory, open '/Users/myuser/projects/testing/reactNative/test/android/app/src/main/java/com/test/MainApplication.java'
```

Here are my Kotlin files:

MainApplication.kt
```
package com.test

import android.app.Application

import com.facebook.react.ReactApplication
import com.facebook.react.ReactNativeHost
import com.facebook.react.ReactPackage
import com.facebook.react.shell.MainReactPackage
import com.facebook.soloader.SoLoader

import java.util.Arrays

class MainApplication : Application(), ReactApplication
{
    override fun getReactNativeHost(): ReactNativeHost {
        return object : ReactNativeHost(this) {
            override fun getPackages(): MutableList<ReactPackage> {
                return Arrays.asList<ReactPackage>(
                        MainReactPackage()
                )
            }

            override fun getUseDeveloperSupport() = BuildConfig.DEBUG
            override fun getJSMainModuleName() = "index"
        }
    }

    override fun onCreate() {
        super.onCreate()
        SoLoader.init(this, false)
    }
}
```

MainActivity.kt
```
package com.test

import com.facebook.react.ReactActivity

class MainActivity : ReactActivity() {
    override fun getMainComponentName() = "test"
}
```

**Comment by dulmandakh** [comment]
I think that linking must be handled by npm package developer, because she/he only knows what it takes to make it work with react native. So I think that this issue is not relevant to react native.

please, close the issue

**Comment by othmanElj** [comment]
I had the same problem after integrating Kotlin (from memory), but after I cross checked with one of the articles (link below) I found out I was missing something, 

https://proandroiddev.com/react-native-bridge-with-kotlin-b2afde2f70b

Please double check, and If you have everything setup correctly it should work properly.

**Comment by jcleigh** [comment]
The default file is `MainApplication.java` [link](https://github.com/facebook/react-native/blob/84022321c437e597660ecd8a773e51bdf8855f4e/local-cli/core/android/index.js#L55)

This should probably be updated to use whichever file, `.java` or `.kt`, exists.

**Comment by friedger** [comment]
You can add the configuration for Android in your package.json like
```
{
  "name":"My RN project",
  ...
  "rnpm": {
    "android": {
	"mainFilePath": "src/main/java/com/blockstack/MainApplication.kt"
	}
   }
}
```

**Comment by hramos** [comment]
The command line tools have their own repository and issue tracker over at https://github.com/react-native-community/react-native-cli, but the
