### ISSUE TITLE
How to get values which are in TouchableOpacity when Button is click with redux

### ISSUE THREAD

**Issue by fcyln** [facebook/react-native#19182]
### **i am getting this error: undefined is not a function (evaluating '_this.props.submitAction(_this.state.text)')**

`import React, { Component } from 'react';
import { connect } from 'react-redux';
import {KeyboardAvoidingView, Image, TouchableOpacity } from 'react-native';
import {
    Button,
    Footer,
    FooterTab,
    Text,  
  } from "native-base";
  import { KeyboardAwareScrollView } from 'react-native-keyboard-aware-scroll-view';

import { View, Title, Screen, ScrollView, TextInput } from '@shoutem/ui';
import Messages from '../containers/Messages';
import Input from '../containers/Input';
import { sendMessage } from '../actions';

const mapStateToProps = (state) => ({
    chatHeight: state.chatroom.meta.height,
    user: state.user
});

class ChatUI extends Component {

    constructor(props){
        super(props)
    
        this.state = {
          text: '',

        }
      }

    state = {
        scrollViewHeight: 0,
        inputHeight: 0
    }
    componentDidMount() {
        this.scrollToBottom(false);
    }

    componentDidUpdate() {
        this.scrollToBottom();
    }

    onScrollViewLayout = (event) => {
        const layout = event.nativeEvent.layout;

        this.setState({
            scrollViewHeight: layout.height
        });
    }

    onInputLayout = (event) => {
        const layout = event.nativeEvent.layout;

        this.setState({
            inputHeight: layout.height
        });
    }

    scrollToBottom(animate = false) {
        const { scrollViewHeight, inputHeight } = this.state,
              { chatHeight } = this.props;

        const scrollTo = chatHeight - scrollViewHeight + inputHeight;

     if (scrollTo > 0) {
       this.refs.scroll.scrollToEnd();
      
    }
    }

    _scrollToInput(reactRef) {
        this.refs.scroll.scrollToFocusedInput(ReactNative.findNodeHandle(reactRef));
    }

    sendMessage = (text) => {
        return sendMessage(text, this.props.user)
    }

 
    onChangeText = text => this.setState({text: text});

    onSubmitEditing = () => {
        this.props.dispatch(
            this.props.submitAction(this.state.text)
        );

        if (!this.props.noclear) {
            this.setState({
                text: null
            });
        }
    }

    render() {
        return (         
       <Screen >
                <Title style={{paddingTop: 25, paddingLeft: 10, borderBottomWidth: 0.5, backgroundColor: 'white', paddingBottom: 10}}>
                <Image style={{width:80, height: 80}} source={require('../img/11.png')} />
                <Text>                    GENERAL CHAT</Text>
                </Title>
                <KeyboardAwareScrollView ref="scroll"
                                         onLayout={this.onScrollViewLayout}>

                    <Messages />
        </KeyboardAwareScrollView>
        <Footer style={{width:360,
                        height:30,
                        backgroundColor:'#fff',
                        borderRadius:20,
                        borderWidth: 0.5,
                        marginBottom: 3,
                        borderColor: 'gray',
                        paddingRight:250
             }}>
          <Input onLayout={this.onInputLayout}
                          submitAction={this.sendMessage}
                          ref="input"
                          placeholder="Say something ..." 
                          onChangeText={(text) => this.setState({text})}
                          />
       
        </Footer>     
           <TouchableOpacity
                   onPress={this.onSubmitEditing}
                   submitAction={this.sendMessage}
            style={{marginLeft:280, backgroundColor:'gray', width: 70, height: 30}}
             styleName="dark"
             ref="sendit"
             title="Press Me"
              >
            </TouchableOpacity>
    
     </Screen>
     

           
            
        )
    }
}

export default connect(mapStateToProps)(ChatUI);`

**Comment by betiol** [comment]
Try import `submitAction` from your actions and run `this.props.dispatch(submitAction(this.state.text))`
