### ISSUE TITLE
[ART] Get the total length of a Shape for using in animations

### ISSUE THREAD

**Issue by brentvatne** [facebook/react-native#1919]
Currently shapes allow us to set `strokeDash` which is incredibly useful for animating paths, a la [Stroke Dash Interpolation](http://bl.ocks.org/mbostock/5649592). Currently you can just guess the length of a shape and animate the dash accordingly, but it would be nice if we could grab the total length once it is drawn, eg: 

```
// In render..
<Shape ref={(shape) => this._shape = shape} d={SomePath} />

// Elsewhere..
this.shape.getTotalLength().then((length) => this.setState({length});
```

This is exposed via `getTotalLength` on SVG as well, thus the name. Implementing this will allow us to just do:

```
<Shape {...whatever} strokeDash={[this.state.value, this.state.length]} />
```

Then we can just animate `this.state.value` until it reaches the length.

Example:

![simple-line](https://cloud.githubusercontent.com/assets/90494/8588052/f98516ae-25b9-11e5-813a-69a38fc07464.gif)

```javascript
class SampleApp extends Component {
  constructor(props) {
    super(props);

    this.state = {
      value: 0,
    }
  }

  componentDidMount() {
    this._animateEntrance();
  }

  _animateEntrance() {
    requestAnimationFrame(() => {
      this.setState({value: this.state.value + 15});
      // This is some random number that I guessed to be the length of the Shape
      if (this.state.value <= 700) {
        requestAnimationFrame(this._animateEntrance.bind(this));
      }
    });
  }

  render() {
    return (
      <View style={styles.container}>
        <Surface width={320} height={600}>
          <Shape d="M1,1L200,200L202,200L150,200L300,500L350,550"
                       stroke="black" strokeDash={[this.state.value,700]}
                       strokeWidth={2} />
        </Surface>
      </View>
    );
  }
}
```

**Comment by brentvatne** [comment]
ping @nicklockwood because he knows all things drawing in iOS

**Comment by jeanregisser** [comment]
We could estimate the length of the path using the technique described in [this article](http://blog.2doconsulting.com/blog/2012/10/14/measuring-the-length-of-an-nsbezierpath/).

We can easily convert the `CGPathRef` used by `ARTShape` to a `UIBezierPath` using `bezierPathWithCGPath:`.

However, unlike what's written in the post, `bezierPathByFlatteningPath` is only available on `NSBezierPath` on OSX.

Thankfully @adamwulf already did the hard work and and wrote an [iOS version](https://github.com/adamwulf/PerformanceBezier/blob/master/PerformanceBezier/UIBezierPath%2BNSOSX.m#L262).

**Comment by nicklockwood** [comment]
Since bezier paths are fairly simple math, and this doesn't seem to depend on any flex logic, it might make more sense if this was calculated on the JS side, then it would be available synchronously. Also, if it was implemented as part of the ReactART js code, it would be available on Web and Android too, not just iOS.

What do you think, @vjeux?

**Comment by vjeux** [comment]
I have never used ReactART nor svg so I'm not really the best person to have an opinion on this. Cc @sebmarkbage who built it

**Comment by sebmarkbage** [comment]
In ART the regular Path module is write only so that it can be optimized for the target environment and asynchronous.

The MetricsPath module in art/metrics/path allow you to measure points along a path and measure the length of a path. It is designed for this use case. 

Here is a bad example for art:

https://github.com/sebmarkbage/art/blob/master/demos/paths/path.js

Got to run but I'll be back with a react-native specific example.

**Comment by sebmarkbage** [comment]
Here's a complete example:

https://rnplay.org/apps/0EzqNQ

You can create a MetricsPath like this:

```js
var MetricsPath = require('art/metrics/path');
var SVG_PATH = 'M30,30L200,200L202,200L150,200L300,500L305,550';
var pathMetrics = new MetricsPath(SVG_PATH);
```

or using the method based API to build up the path.

`pathMetrics.length` will get you the length of the path.

You can get any point (x,y) along the path using `pathMetrics.point(offset)`. I use this in the example to draw a box around the corner as it is animating.

You can also use it to get the bounding box (but I noticed that there is a bug in the bounding box code).

Would this solve your use case?

**Comment by brentvatne** [comment]
That addresses my use case and then some (`var point = pathMetrics.point(this.state.value);` is a beauty). Thanks @sebmarkbage for this and ReactART!
