### ISSUE TITLE
Automatically size images if no size is specified in the style property

### ISSUE THREAD

**Issue by ide** [facebook/react-native#192]
This is a feature request for `<Image source={require('image!a.png')} />` to display the image even though there is no style property that specifies the size. For static images, the packager can compute the size of the image up front (and with a module like [sharp](https://github.com/lovell/sharp), 2x-resolution images could be automatically generated from 3x ones when necessary).

For non-static images, I think the right thing is to resize the Image component after the image size is known, but to warn about the potentially janky user experience and extra reflow pass. So - basically like web but with warnings about suboptimal practices.

**Comment by joshbedo** [comment]
> The problem with image sizing is that it's not trivial to know from an arbitrary URL what the size is. So, if you give the developer a way to get away with not knowing the size, by paying the cost of a reflow, he will take it in a whim (my long experience in the fb codebase).

> Then, once you have an entire codebase that has no idea what sizes the images it display are, but sometimes you do need to know them, you are screwed. You add all sorts of hacks, threading them down, having all sorts of heuristics to figure them out, parsing the URI attempting to recover it...

> What you need is to ask the image size when you get the URI, and then always keep this metadata around. By forcing the developer to know the image size to render it, I hope that it's going to lead them to fall into the pit of success by implementing that pattern by themselves. While this is a pretty sneaky technique, this is the best I got.

@vjeux i also thought this was a little annoying but after reading that explanation i can totally understand where you're coming from. I've seen many people add 500x500 images and then resize them to 50x50 through the interwebs. It also encourages like you said creating design patterns.. I could have a Icon react class which sets default width and height to 50px as well as other properties and i can specify other props like rightCorner, leftCorner etc.

**Comment by brentvatne** [comment]
This is happening now with static images. To summarize the above: core will not include any auto-sizing of network images, but feel free to develop and publish a module to take care of this if you would like to see it :smile:
