### ISSUE TITLE
CameraRoll.getPhotos with assetType: "All" does not return Videos on Android

### ISSUE THREAD

**Issue by facuescobar** [facebook/react-native#19207]
`CameraRoll.getPhotos with assetType: "All"` only returns Photos instead of Videos and Photos

## Environment
```
Environment:
  OS:  macOS High Sierra 10.13.3
  Node:  7.9.0
  Yarn:  0.23.2
  npm:  5.8.0
  Watchman:  4.7.0
  Xcode:  Xcode 9.2 Build version 9C40b
  Android Studio:  2.3 AI-162.4069837

Packages: (wanted => installed)
  react: ^16.3.0-alpha.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4
```

## Steps to Reproduce
On Android try to fetch your library assets using:
``` 
CameraRoll.getPhotos({ first: 30, asstType: "All" });
```

The response will return Photos only, instead of Photos and Videos.

## Expected Behavior
`CameraRoll.getPhotos({ first:30, assetType: "All" })` should return Photos and Videos

## Actual Behavior
`CameraRoll.getPhotos({ first:30, assetType: "All" })`
Returns Photos - NOT OK, it should return photos and videos

`CameraRoll.getPhotos({ first:30, assetType: "Videos" })`
Returns Videos - OK

`CameraRoll.getPhotos({ first:30, assetType: "Photos" })`
Returns Photos - OK

**Comment by mopilo** [comment]
same

**Comment by mldb** [comment]
same

**Comment by ruckus** [comment]
same. this bug/behavior is obvious by looking at the android cameraroll source. 

I've solved it by building two promises:

```javascript
let tasks = [];

    if(Platform.OS === 'android') {
      let task1 = CameraRoll.getPhotos({
        first: pageSize,
        assetType: 'All',
        mimeTypes: mimes
      });
      tasks.push(task1);

      let task2 = CameraRoll.getPhotos({
        first: 20,
        assetType: 'Videos'
      });
      tasks.push(task2);
    }

    return Promise.all(tasks).then( (results) => {
      // process results here
    });
```

**Comment by dested** [comment]
The java code explicitly states this fact, the documentation needs to be updated accordingly. 

https://github.com/facebook/react-native/blob/26684cf3adf4094eb6c405d345a75bf8c7c0bf88/ReactAndroid/src/main/java/com/facebook/react/modules/camera/CameraRollManager.java#L214-L215
