### ISSUE TITLE
Special characters cannot be rendered correctly

### ISSUE THREAD

**Issue by quietautumn** [facebook/react-native#19206]
## Environment
        Environment:
        OS: macOS High Sierra 10.13.4
        Node: 9.3.0
        Yarn: 1.3.2
        npm: 5.6.0
        Watchman: 4.9.0
        Xcode: Xcode 9.3 Build version 9E145
        Android Studio: 2.3 AI-162.4069837

  Packages: (wanted => installed)
       react: 16.3.1 => 16.3.1
       react-native: 0.55.4 => 0.55.4

## Steps to Reproduce
    The data I submitted is like this, and I hope it is rendered.
![e1a93412-cfe7-462e-94d0-5556c1d15f12](https://user-images.githubusercontent.com/16301518/39855055-e9866f9e-545c-11e8-9925-cfb649b404cb.png)

## Actual Behavior
But some special characters cannot be rendered, and the characters are still escaped characters.

![4fb3893d-6d31-4e2b-bbd7-f7d63ad622c5](https://user-images.githubusercontent.com/16301518/39855176-7478ec6c-545d-11e8-8c9f-154365bfef01.png)
![aca9073a-bf67-49ca-8299-5ab5d170fc49](https://user-images.githubusercontent.com/16301518/39855180-7bcf14f0-545d-11e8-8521-6a02fcf32b1a.png)

**Comment by quietautumn** [comment]
No,I've tried the latest version of the mistake.

**Comment by quietautumn** [comment]
@react-native-bot 
![c48a0d61-61d9-46d7-9fb9-a613ae481152](https://user-images.githubusercontent.com/16301518/41325545-76b2e532-6eed-11e8-94d3-d18cd89e46f7.png)
The result is still the same as the previous version：
![e338c406-9b5a-4d7a-9823-a9d7608f6747](https://user-images.githubusercontent.com/16301518/41325584-b346e642-6eed-11e8-9f22-88dd164a2b70.png)
The effect of the rendering：
![a50a21fc-bcff-4b2f-969b-cb06383fe912](https://user-images.githubusercontent.com/16301518/41325607-d425adb2-6eed-11e8-8cc1-a1a45cfdca10.png)

**Comment by hramos** [comment]
I believe this is working as intended in React. You can see a related issue at https://github.com/facebook/react-native/issues/1016.
