### ISSUE TITLE
Image component does not show video preview from CameraRoll videos on Android

### ISSUE THREAD

**Issue by facuescobar** [facebook/react-native#19209]
`CameraRoll.getPhotos({assetType: "Videos", ...})` returns a list of videos, each video has the next object model.
 
```
{
  "node": {
    "timestamp": 1525887405.084,
    "group_name": "Camera",
    "type": "video/mp4",
    "image": {
      "height": 720,
      "width": 1280,
      "playableDuration": 11,
      "uri": "content://media/external/video/media/441"
    }
  }
}
```

Issues:
1 - CameraRoll.getPhotos does not return an image URI with the video preview.
2 - The **uri** provided does not work if I use it with: 
```
<Image source={{ uri: "content://media/external/video/media/441" }} style={{ width: 100, height: 100 }} /> 
```

**There is no way to obtain a preview of a video obtained from CameraRoll.getPhotos()**

## Environment
```
Environment:
  OS:  macOS High Sierra 10.13.3
  Node:  7.9.0
  Yarn:  0.23.2
  npm:  5.8.0
  Watchman:  4.7.0
  Xcode:  Xcode 9.2 Build version 9C40b
  Android Studio:  2.3 AI-162.4069837

Packages: (wanted => installed)
  react: ^16.3.0-alpha.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4
```

## Steps to Reproduce
Load Videos with:
```
CameraRoll.getPhotos({ first:30, assetType: "Videos" })
```

Render Video URI with:
```
<Image source={{ uri: "content://media/external/video/media/441" }} style={{ width: 100, height: 100 }} /> 
```

## Expected Behavior
**Image** component should be able to render the preview of a video URI

## Actual Behavior
Can not visualize video preview of videos returned from `CameraRoll.getPhotos({assetType: "Videos", ...})`

**Comment by mopilo** [comment]
try to use react-native-video

**Comment by facuescobar** [comment]
Thanks but that doesn't fix the issue!

**Comment by ereenyessamhanna** [comment]
any updates ?

**Comment by Daneyl** [comment]
I am even stuck in the same issue... any solution??? Cant get the proper uri from CameraRoll for videos thumbnail to get displayed by the Image tag.
