### ISSUE TITLE
[Android] Linking.openURL('tel:+123456789') error

### ISSUE THREAD

**Issue by shinobibash** [facebook/react-native#19215]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [ ] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

 Cannot open phone call with Linking.openURL('tel:+123456789') 

## Environment
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.5.0
  Yarn: Not Found
  npm: 5.8.0
  Watchman: Not Found
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz => 0.55.2
  expo: 27.0.1,

## Steps to Reproduce
    import ...
    export default class App extends React.Component {

    _pressCall=()=>{
        const url='tel:+123456789'
        Linking.openURL(url)
    }

    render() {
        return (
            <View style={styles.container}>
                <Button title='call' onPress={this._pressCall}/>
            </View>
        );
    }
    }
https://snack.expo.io/@kikoololmdrxdd/test-linking-phone-call

## Expected Behavior
open phone call

## Actual Behavior

![image](https://user-images.githubusercontent.com/32987394/39868746-2d11adfc-545b-11e8-9ecd-b6196d68d156.png)

**Comment by dulmandakh** [comment]
please, close the issue
