### ISSUE TITLE
Error: Cannot find module 'metro-bundler/src/babelRegisterOnly'

### ISSUE THREAD

**Issue by ArronJLinton** [facebook/react-native#19219]
## Bug Report

I'm trying to link native libraries by running `react-native link` and this is the error it returns - 
`Error: Cannot find module 'metro-bundler/src/babelRegisterOnly'`. 
I installed `react-native-google-signin`, which was successful. Then I attempted to link the library, and it return an error as a result. I don't think this is an npm package specific issue because now I can't link any other libraries after installing. 

## Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.10.1
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.50.3 => 0.50.3

Error: Cannot find module 'metro-bundler/src/babelRegisterOnly'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/arronlinton/Desktop/projects/fucci/fucci/node_modules/react-native/setupBabel.js:12:27)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)

Any thoughts?

**Comment by kingtross88** [comment]
i'm having the same issue. Does anyone have  a fix for the below?


module.js:471
    throw err;
    ^

Error: Cannot find module 'metro/src/babelRegisterOnly'

**Comment by williamwilliamwilliam** [comment]
For me, the issue was caused by a bad mix of dependencies. Using react-native 0.55.4, I had included the Metro dependencies to mess with starting an actual server to pull dev bundles from a server programmatically, but started seeing this error.

Dev Dependencies:

```
    "@babel/core": "^7.1.2",
    "babel-core": "^6.26.3",
    "babel-eslint": "^10.0.1",
    "babel-jest": "22.4.3",
    "babel-plugin-module-resolver": "^3.1.1",
    "babel-preset-react-native": "4.0.0",
    "metro": "^0.52.0",
    "metro-core": "^0.52.0",
```
