### ISSUE TITLE
SectionList renderItem duplicate

### ISSUE THREAD

**Issue by WangJian0** [facebook/react-native#19212]
When i use SectionList,console is duplicate.My code:
render() {
    return (
      <SectionList
        renderItem={this._renderItem}
        renderSectionHeader={({section}) => <Text>{section.title}</Text>}
        sections={[
          {title: 'Title1', data: ['item1', 'item2']},
          {title: 'Title2', data: ['item3', 'item4']},
          {title: 'Title3', data: ['item5', 'item6']},
        ]}
        keyExtractor={(item, index) => this._renderKeyExtractor(item,index)}
      />
    );
  }

  _renderItem({item,index}) {
    console.log(item)
    return <Text key={index} style={{textAlign:'center',color:'red'}}>{item}</Text>
  }

consoleResult:
item1
item2
item3
item4
item5
item1
item2
item3
item4
item5
item6
why is it so...

## Environment
Environment:
  OS: macOS Sierra 10.12.6
  Node: 6.10.1
  Yarn: 0.27.5
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 2.2 AI-145.3360264

Packages: (wanted => installed)
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: ^0.50 => 0.50.4

## Steps to Reproduce
1.new a project and nom install
2.copy code and run

**Comment by jamsch** [comment]
Your component containing the SectionList is likely doing a re-render which will make the SectionList re-render the items as well. To get around this you may want to pass the SectionList an "extraData" prop so that it only re-renders when the "extraData" prop changes.

https://facebook.github.io/react-native/docs/sectionlist.html#extradata

**Comment by WangJian0** [comment]
@jamsch Do you mean that SectionList is repeatedly rendered?

**Comment by jamsch** [comment]
@WangJian0 

Sorry, I didn't read the full question. Your SectionList is re-rendering because the "sections" prop on the SectionList has been updated. You should monitor the "sections" prop to see if there are any changes.

**Comment by WangJian0** [comment]
@jamsch But my sections are not changeable directly.
sections={
 [
   {title: 'Title1', data: ['item1', 'item2']},
   {title: 'Title2', data: ['item3', 'item4']},
   {title: 'Title3', data: ['item5', 'item6']},
 ]
}
