### ISSUE TITLE
XMLHttpRequest is very slow

### ISSUE THREAD

**Issue by levani** [facebook/react-native#19227]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.9.4
  Yarn: 1.6.0
  npm: 5.8.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3.1 Build version 9E501
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: 16.3.2 => 16.3.1
  react-native: 0.55.4 => 0.55.4

## Steps to Reproduce
Run the following code:

```
function reqListener() {
  console.log('reqListener');
  alert(this.responseText);
}
var oReq = new XMLHttpRequest();
oReq.addEventListener("load", reqListener);
oReq.open("GET", "http://localhost/someting");
oReq.send('{}');
```

## Expected Behavior

Return response as soon as possible.

## Actual Behavior

The request takes several seconds to complete even if the server returns response almost instantly. From what I've found so far this happens when the request method is `GET` and `send` method has some string parameter. If I make a `POST` request or change the last line with  `oReq.send();` it works as expected.

**Comment by hramos** [comment]
Is this unique to React Native? Do you see the same behavior when running with Node, or on V8 (e.g. using Chrome)?

**Comment by levani** [comment]
@hramos I tested in chrome 66 and it works as expected. Not sure how can I test XMLHttpRequest in node.
