### ISSUE TITLE
[Node 10] Prepare for Node 10

### ISSUE THREAD

**Issue by hramos** [facebook/react-native#19229]
# For Discussion

Node 10 is the current Node version as of this writing. While the project requires a minimum of Node 8, we should make sure Node 10 is well supported.

Things that need to be done:

- [x] Ensure tests can run on Node 10 (#19120)
- [x] Test with Node 10

cc @ide, @TheSavior, @grabbou 

## Environment

N/A

## Steps to Reproduce

N/A

## Expected Behavior

N/A

## Actual Behavior

N/A

**Comment by gengjiawen** [comment]
How about a new docker image instead of circle ci ?

**Comment by gengjiawen** [comment]
I also want to keep node 8 along side with node 10. I just think circle official node image not suitable for react native. The node 10 image will use reactnativeci/android as base image.

**Comment by hramos** [comment]
What's special about Node 10 that would not work on Circle? What I have in mind is something close to what we already have set up on Circle, but using Node 10 instead. You can see an example here: https://github.com/facebook/react-native/pull/19299

It's only testing JavaScript at the moment, but it could be expanded to run all tests in Node 10 in parallel as well (i.e. build the JS bundle using Node 10 and pass that along to test_android).

Note that the build in that PR is failing because `test_javascript` was failing on master using Node 8 as well.

**Comment by gengjiawen** [comment]
My thought is that the node 10 will bundle android related library so we just use one image. And also the image can be used by community for their ci system, which I think will save lots time.

**Comment by gengjiawen** [comment]
Also I have some idea simpilify current ci, like avoid setup avd by using more docker.

**Comment by hramos** [comment]
Most of the work required to get that working is already in place. Take a look at the [docker scripts here](https://github.com/facebook/react-native/blob/master/package.json#L131-L140). You may need to rebuild the images locally as I am not yet automatically pushing new images to Docker Hub at the moment. I last gave this a try about a week ago and I believe I was blocked on one of the buck failures that was plaguing master. Once we get test_android working again, it should be possible to get that image to work within Circle CI.

**Comment by hramos** [comment]
You may need to update some of the Dockerfiles in the Containership directory, especially now that we've been bumping SDK versions.

**Comment by ronayumik** [comment]
hi @gengjiawen , want to ask, why you specifically choose for node 8, not node 9?

I'm curious since one of my project is using react-native 0.4xx version, and we cannot run test/build using node 9, it's only works on node 8. Sort of confusing since both are unrelated. Do you have any idea about this?

**Comment by gengjiawen** [comment]
@ronayumik Can you try node 10 ?
@hramos I have add node 10 to appveyor.yml.

**Comment by hramos** [comment]
We have been running tests using Node 10 for a while now.
