### ISSUE TITLE
FlatList requires string as key

### ISSUE THREAD

**Issue by James2516** [facebook/react-native#19237]
- [-] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [-] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [-] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 9.8

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.2 => 0.55.2

## Expected Behavior

In a recent update, `FlatList` API is changed to [require strings as keys](https://github.com/facebook/react-native/issues/18291).

Why is this breaking change implemented? 
Many apps use an unique number id (eg. user id, item id) as the key. 
Shouldn't any necessary casting be done internally within RN rather than requiring apps to do it?

The API change also makes the `key` requirement in `FlatList` inconsistent (more stringent) with keys used in array of components produced by `map` etc.

**Comment by James2516** [comment]
@aniltonveiga what? did you post on the wrong issue thread?

**Comment by aniltonveiga** [comment]
@James2516 yes, I'm sorry!

**Comment by hramos** [comment]
The reasoning behind this has been covered in https://github.com/facebook/react-native/issues/18291. In short, using an index as a key is an anti-pattern. I don't think changing this back is something that would be considered.

**Comment by James2516** [comment]
@hramos but I'm not using index as key, I'm using unique item id (from database) which is the correct way.
