### ISSUE TITLE
JavascriptException: Maximum call stack size exceeded when running apk file

### ISSUE THREAD

**Issue by radi-cho** [facebook/react-native#19238]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment
```
OS: Windows 10
  Node: 8.4.0
  Yarn: 1.3.2
  npm: 5.5.1

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.3 => 0.55.3
```

## Steps to Reproduce
- Create blank project using `react-native` `init MyApp`
- Add `babel-plugin-transform-class-properties` (`^6.24.1`) and `stage-0`
Note that it works with the `react-native` and the `es2015` presets

```
// babelrc
{
  "presets": ["stage-0", "react-native", "es2015"],
  "plugins": ["transform-class-properties"]
}
```

- Build the app using `gradlew assembleRelease`

> Do not cahnge any code, just build after adding the listed presets and plugins to the `.babelrc` and installing them via `npm`

> Note that: Everything is working while debugging

When run:

## Expected Behavior
I expect everything just to work!

## Actual Behavior
The app is built successfully but when we install the app on whatever device we get `The app stopped working.` error. I researched it a bit and found this log in the `logcat`:

```
FATAL EXCEPTION: mqt_native_modules
   Process: com.PACKAGE, PID: 13125
   com.facebook.react.common.JavascriptException: Maximum call stack size exceeded., stack:
   <unknown>@11:410
   <unknown>@11:410
```

I searched a bit and find out these things (which may be helpful while resolving the issue):
- Possible solution is to remove some of these presets from the `package.json` file, shown here: https://stackoverflow.com/questions/46170844/maximum-call-stack-size-exceeded-in-react-native, DIDN'T WORK FOR ME
- The exact same issue is described here without ANY response: https://github.com/facebook/react-native/issues/16689#issuecomment-363238863
- Some similar logs are shown in this issue: https://github.com/facebook/nuclide/issues/900
- The apk works once again the `stage-0` preset and the plugin are removed, but in my case I need them.

Hopefully all listed information will be helpful.

**Comment by alvelig** [comment]
`react-native-git-upgrade 0.49.5`

**Comment by radi-cho** [comment]
Hi, @alvelig! Can you please explain why `react-native-git-upgrade` to `0.49.5` can help?

**Comment by alvelig** [comment]
It helped in my case. According to https://github.com/facebook/react-native/issues/16689 this doesn't happen in 0.49.5, so just downgrading helped in my case

**Comment by radi-cho** [comment]
@alvelig thanks. I'm not able to test it at the moment, but I'm gonna share if succeed with `0.49.5`.
Also question to the `react native team`: if this works in `0.49.5` what's the problem in the next versions?
@TheSavior, @shergin, @brentvatne Can someone share any opinion?

**Comment by alvelig** [comment]
https://github.com/facebook/react-native/releases/tag/v0.50.0 Then it should be there. Also try if it works in 0.50 just to confirm, then some of the breaking changes should be causing this.

**Comment by vidit-bhatia** [comment]
this is not possible to solve in the described way I removed all the @connect decorators still I am getting erros and I can not remove stage0 presets because react-navigation starts giving errors. So this is catch 22. Can someone please look into this problem.

**Comment by vidit-bhatia** [comment]
Also I tried changing my version to 49.5 I am getting exactly same error I can test my app but not release it .

**Comment by sebirdman** [comment]
I'm now seeing this issue in 0.56.0. I do have a lot of resolutions to fix the babel upgrade though...

**Comment by abartolo** [comment]
@sebirdman Any solution worked for you? I am seeing the error below only on Prod builds.

```
08-27 20:47:42.675 23560-23586/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: catWheels.main, PID: 23560
    com.facebook.react.common.JavascriptException: Invalid attempt to spread non-iterable instance, stack:
```
