### ISSUE TITLE
[Navigator] navigationContext....'willfocus'?

### ISSUE THREAD

**Issue by yamill** [facebook/react-native#1923]
In my renderScene function I'm defining:

    renderScene: function(route, nav){
        switch(route.id){
          case 'login':
              return <Login/>;
            break;

          case 'signup':
            return <Signup/>;
            break;

          case 'feed':
            return <Feed navigator={nav}/>;
            break;

          case 'profile':
            return <Profile objectId={route.objectId}/>;
            break;

          case 'video':
            return <Video url={route.url} poster={route.poster}/>;
            break;

          default:
            if(!this.data.user){
              return <Login/>;
            }

            return <Feed navigator={nav} />;
        }
      }

Then in my Feed componentDidMount:

         this.props.navigator.navigationContext.addListener('willfocus', (event) => {
           this.setState({
                autoplay: false
            });
         });

But I received "Cannot read property 'addListener'. 

I'm trying to do this here because I need to stop autoplaying all videos on the feed before switching over to the next route.

@ericvicenti maybe you can point me in the right direction?

**Comment by chirag04** [comment]
Which react-native version are you using?

**Comment by yamill** [comment]
@chirag04 I'm using 0.6.0

**Comment by ericvicenti** [comment]
Hey @yamill, sorry for the bug here!

I suspect your problem will be fixed if you go into Navigator and move the following line into `getInitialState` instead of `componentWillMount`:

https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/Navigator/Navigator.js#L291-L292

Let me know if that fixes it. If it does, a PR would be greatly appreciated!

**Comment by yamill** [comment]
Hey @ericvicenti thanks for the reply! 

Hmmm...my Navigator.js looks different than the one in Master. I am running 0.6.0 and I see Master is as well on 0.6.0, though, I see the push on July 7th. I tried pulling that... but I guess this update hasn't been pushed to the npm?

**Comment by yamill** [comment]
@ericvicenti Doh! Looks like the updated Navigator.js is in 0.7.0-rc.2. I'll run a test and get back to you :) 

Thanks!

**Comment by ericvicenti** [comment]
We may not have had a release since the latest changes here. Maybe you could check out the master version of RN into your node modules?

**Comment by yamill** [comment]
@ericvicenti Unfortunately I tried the above. But now <strong>react-native-video</strong> breaks with the latest build of React Native. 

@brentvatne a PR update to react-native-video would be helpful. I'm trying to pause videos playing using the willFocus event on the navigator. Unless you have a better suggestion? ;)

**Comment by brentvatne** [comment]
@yamill - I pushed an update, let me know if that helps

**Comment by yamill** [comment]
@ericvicenti @brentvatne thank you guys for your help!!! I was able to resolve this issue.

The code above worked with the latest react-native v0.7.1. I didn't have to modify the Navigator.js :smile:  

I'll post a git example soon in this thread sometime later today.

**Comment by yamill** [comment]
Here's the example for anyone interested. I think this will be helpful to some people who are making video apps.

https://gist.github.com/yamill/9ff0fe84e5b820cf80eb#file-video-scene-component-L7-L14

**Comment by browniefed** [comment]
@brentvatne looks like you solved this one.

**Comment by brentvatne** [comment]
:p
