### ISSUE TITLE
[Bug] Animated.ScrollView : "scrollTo" is not a function.

### ISSUE THREAD

**Issue by ATShiTou** [facebook/react-native#19235]
- [ ] I have reviewed the [documentation](https://facebook.github.io/react-native)
YES
- [ ] I have searched [existing issues](https://github.com/facebook/react-native/issues)
YES
- [ ] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)
YES

Animated.ScrollView : "scrollTo" is not a function, but ScrollView works well.(iOS & Android & Simulator)

## Environment
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 10.0.0
  Yarn: 1.6.0
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Not Found
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

## Steps to Reproduce
Code:
```
<Animated.ScrollView
    ref={ref=>(this.scrollView=ref)}
    />

action = ()=>{
    this.scrollView.scrollTo({x:100,y:100, animated:false});
}
```
## Expected Behavior
Animated module does not export method `scrollTo`.

## Actual Behavior
Getting an error on all platform devices and simulators:
"_this2.scrollView.scrollTo is not a function"

**Comment by ATShiTou** [comment]
If `scrollTo` is disabled, how can I change the offset of the scrollview by code.

**Comment by mikemerritt** [comment]
@ATShiTou I ran into this problem as well after changing an existing `ScrollView` to an `Animated.ScrollView`. You can access the underlying `ScrollView` with `this.scrollView.getNode()`.

Your action would then be: `this.scrollView.getNode().scrollTo({x:100,y:100, animated:false});`

**Comment by ATShiTou** [comment]
Thank you very much.

**Comment by muzammil-triffort** [comment]
It works only in iOS. For Android, I am still having issue with "scrollTo". Any suggestion?

**Comment by muzammil-triffort** [comment]
For Android, I set the top margin in my style. I didn't find any workaround with "ScrollTo" option.

**Comment by marquesm91** [comment]
Can't get this working in iOS neither Android using `React.createRef()`. After refering and trying to call `this.scroll.getNode().scrollTo({ ... })` I still getting `scrollTo is not a function`

**Comment by Cicko** [comment]
@marquesm91 In my case I get "getNode is not a function".

**Comment by rendomnet** [comment]
Bug still exist.

**Comment by RafaelFeiten** [comment]
> Bug still exist. `React.createRef()` It is not working in Animated.ScrollView and working in ScrollView

U are right @rendomnet, at a later time I was able to use `create.Ref`, but it is no longer working on `Animated.ScrollView`. Could you report the solution found?

**Comment by li2go** [comment]
i find that safari on macbook mini ".scrollTo" is not a function.

**Comment by li2go** [comment]
> i find that safari on macbook mini ".scrollTo" is not a function.

support:
https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTo

**Comment by rendomnet** [comment]
@RafaelFeiten no. No solution.

**Comment by KakarN** [comment]
For me, [this answer](https://stackoverflow.com/questions/42051368/scrollto-is-undefined-on-animated-scrollview) seems to work out. I am using expo 32.0.0, react 16.5.0, and react-native v0.57.1.

**Comment by euroclydon37** [comment]
Any findings on this? I can't get `ref.current.scrollTo()` or `ref.getNode().scrollTo()` to work on iOS (haven't tried Android. I'm sure it's not working either.)

**Comment by RafaelFeiten** [comment]
Not working, read about React Memo. It can help u...
