### ISSUE TITLE
ios  Unsupported top level event type "topVideoProgress" dispatched

### ISSUE THREAD

**Issue by xuyuanzhou** [facebook/react-native#19249]
Unhandled JS Exception: Unsupported top level event type "topVideoProgress" dispatched
reactConsoleErrorHandler @ ExceptionsManager.js:73
console.error @ YellowBox.js:71
logToConsole @ RCTLog.js:48
logIfNoNativeHook @ RCTLog.js:31
__callFunction @ MessageQueue.js:353
(anonymous) @ MessageQueue.js:118
__guardSafe @ MessageQueue.js:316
callFunctionReturnFlushedQueue @ MessageQueue.js:117
(anonymous) @ debuggerWorker.js:72

version:
react-native: 0.54.0
react: 16.3.0-alpha.0

![image](https://user-images.githubusercontent.com/13957655/39993930-3989239c-57aa-11e8-8d52-c21e9e8c344f.png)

**Comment by xuyuanzhou** [comment]
use deprecated method

**Comment by MrPluto** [comment]
any detail ? @xuyuanzhou
