### ISSUE TITLE
OnPress of item in FlatList not Working Correctly on android when when style of FlatList contains scaleX=-1

### ISSUE THREAD

**Issue by BatDroid** [facebook/react-native#19245]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.0.0
  Yarn: 0.27.5
  npm: 5.8.0
  Watchman: 4.7.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: Not Found

Packages: (wanted => installed)
  react: ^16.3.1 => 16.3.1
  react-native: ^0.55.1 => 0.55.1

## Steps to Reproduce

i have a flat list in which there are clickable elements (mostly image). for the ui reasons i wanted it to be rtl and the only workaround worked for me was to give the `{transform: [{scaleX: -1}]}` style to The FlatList.everything works perfect in ios but in android the Touchables (TouchableOpacity/TouchableWithoutFeedback/TouchableHighlight) ui response to press (eg: in TouchableOpacity) works perfect but the onPress is called if only user press the top right edge of element. when i remove style for FlatList everything works in android/ios perfect.
here is the code:

```
type Props = {
    elements : List<GalleryItem>,
}

const GalleryImageViewer = (props: Props) => {
    let images = props.elements.toArray();
    return (
        <FlatList
            style={styles.flatList}
            numColumns={3}
            data={images}
            renderItem={renderItems}
            ItemSeparatorComponent={renderSeparator}
            keyExtractor={(item,index) => item.key}
        />
    );
};

function renderSeparator() {
    return (
        <View style={{height: 1}}/>
    );
}

function renderItems(obj) {
    const item: GalleryItem = obj.item;
    const index = obj.index;
    let childElement = item.element;
    let style = (index === 1 || index % 3 === 1) ? {paddingRight: 1, paddingLeft: 1} : {};
    return (
        <TouchableOpacity onPress={() => item.onPress()}>
            <View style={style}>
                {childElement}
            </View>
        </TouchableOpacity>
    );
}

const {width, height} = Dimensions.get("window");
const styles = StyleSheet.create({
    flatList: {transform: [{scaleX: -1}]},
});


export default GalleryImageViewer;
```

## Expected Behavior

onPress of Touchables work in android without bug (like ios) when i try to have an rtl flat list by adding `{transform: [{scaleX: -1}]}` as style.

## Actual Behavior

though the ui response works where ever on an element, the onPress is not called if the touch is not on the top right edge

**Comment by aniltonveiga** [comment]
@BatDroid try to use the inverted property of the component itself (https://facebook.github.io/react-native/docs/flatlist.html#inverted), maybe this will help.

But you can also add a style to your TouchableOpacity, so you can view the useful area that it is filling and add an appropriate width and height.

Ex: <TouchableOpacity style = {{borderWidth: 1}} onPress = {() => item.onPress ()}>

And take a look at the customization you're putting inside the variable style, because it's not being recognized for being outside StyleSheet.create ()
