### ISSUE TITLE
[Packager] Command or flag to clean cache

### ISSUE THREAD

**Issue by brentvatne** [facebook/react-native#1924]
When introducing a custom `.babelrc`, it's necessary to [add the resetCache](https://gist.github.com/brentvatne/794a77917d7a4b3cce5b/revisions) flag to the packager. This requires digging into `node_modules` and isn't the most developer friendly (DX anybody? :P)

So we should either allow users to do:

`./node_modules/react-native/packager/packager.sh clean`

or

`./node_modules/react-native/packager/packager.sh -root . -clean`

Also open to other solutions! cc @amasad

**Comment by cyprusglobe** [comment]
+1

**Comment by dozoisch** [comment]
:+1:

**Comment by shlomiatar** [comment]
We use this quick and dirty gulp task:
```js
gulp.task('clear-cache', function () {
  // Clear react-packager cache

  const tempDir = os.tmpdir();

  const cacheFiles = fs.readdirSync(tempDir).filter(function (fileName) {
    return fileName.indexOf('react-packager-cache') === 0;
  });

  cacheFiles.forEach(function (cacheFile) {
    const cacheFilePath = path.join(tempDir, cacheFile);
    fs.unlinkSync(cacheFilePath);
    console.log('Deleted cache: ', cacheFilePath);
  });

  if (!cacheFiles.length) {
    console.log('No cache files found!');
  }
});
```

**Comment by brentvatne** [comment]
Nice one @shlomiatar! Could you submit a pull request to add that command to the packager?

**Comment by fabiomcosta** [comment]
+1

**Comment by fabiomcosta** [comment]
ideally the cache key would consider the current babel transforms

**Comment by zallek** [comment]
+1 thanks for the tip, and yeh a clean command would be appreciated :)

**Comment by amasad** [comment]
@martinbigio just shipped a diff that adds support for this. Should land soon.

**Comment by gaearon** [comment]
```
hours_spent_here += 3;
```

**Comment by alejomendoza** [comment]
:+1: this is such an annoying bug :beetle: where do we add the gulp task?

**Comment by shlomiatar** [comment]
@alejomendoza, 
You can install gulp by running `npm install -g gulp`.
then, you add `gulpfile.js` and add the task in it (and require the dependencies, `os` and `fs`)

you can run the task by typing `gulp clear-cache` on the same folder as the gulpfile. 
good luck! :)

**Comment by ide** [comment]
For the time being you also can run `rm -fr $TMPDIR/react-*`.

**Comment by dzannotti** [comment]
`hours_spent_here += 3;`

**Comment by niftylettuce** [comment]
I tried both, but `stage: 0` flag is still not working, I can't use things like `...` spread operator or `=>` arrow functions.

**Comment by niftylettuce** [comment]
Nevermind, resolved.

**Comment by LeoFidjeland** [comment]
hours_spent_here += 2;

**Comment by martinbigio** [comment]
Would it be possible not to rely on `.babelrc` and have the entire configuration on the transformer? cc @sebmck

**Comment by brentvatne** [comment]
Ping @kittens :)

**Comment by niftylettuce** [comment]
+1

**Comment by nevir** [comment]
hours_spent_here += 3;

`rm -fr $TMPDIR/react-*` wasn't enough to fix my particular issue (module still being emitted in the bundle after removing it from `node_modules` and all imports of it), still digging in

**Comment by martinbigio** [comment]
We recently added support to allow the transformer to specify a cache key (https://github.com/facebook/react-native/commit/b5f80065d48e2196f4b648cbb734e47b84284d0e). You should be able to make the key dependent on the plugins you're using (the preset + the specifics to your build if any).

**Comment by wtfil** [comment]
`watchman watch-del-all`

**Comment by saulshanabrook** [comment]
Now it's

```bash
watchman . watch-del-all
```

**Comment by jdmarshall** [comment]
It seems this problem still exists, but react no longer writes its cache to the tmp directory.  Where is it hiding now?

**Comment by kgowru** [comment]
Is there a solution here? My packager just fails to notice the updated .babelrc file. So annoying.

**Comment by janaka** [comment]
Let's not orget Windows.

**Comment by ide** [comment]
The command to clear the cache is `npm start --reset-cache` (specifically, however you invoke the RN server, pass the `--reset-cache` option to it).

**Comment by hybrisCole** [comment]
The config this guy proposes is really good to handle this https://medium.com/komenco/useful-react-native-npm-scripts-6c07b04c3ac3#.63boty1oh

**Comment by arthur31416** [comment]
These commands from [Ignite](https://github.com/infinitered/ignite) are great too:
```
"clean": "rm -rf $TMPDIR/react-* && watchman watch-del-all && npm cache clean"
"newclear": "rm -rf $TMPDIR/react-* && watchman watch-del-all && rm -rf ios/build/ModuleCache/* && rm -rf node_modules/ && npm cache clean && npm i"
```

**Comment by lprhodes** [comment]
npm start -- --reset-cache works much better than npm start --reset-cache

**Comment by hellogerard** [comment]
@lprhodes I see that `--` here and there, but I don't really know what it does. What's the difference between `npm start -- --reset-cache` and `npm start --reset-cache`?

**Comment by liuliangsir** [comment]
thx@hellogerard

**Comment by j2kun** [comment]
Is there any way to clear the cache while the packager is still running? Or more to my ultimate goal, just tell the react-native packager to re-transpile a specific javascript file on some filesystem event?

**Comment by lprhodes** [comment]
@j2kun  Enabling live reload should work for everything except after changes to node_modules.

**Comment by j2kun** [comment]
@lprhodes This doesn't work for non-javascript file changes. What I have been doing (a really crappy workaround) is creating a watchman trigger for my specific file to run

```
find $TMPDIR/react-native-packager-cache-* -name "mypattern" | xargs rm
```

But this doesn't even work because I have to restart the packager for it to pick up that these cache files got deleted. I would really love a way to say "Hey packager, when this file changes, please re-transpile this JS file!" But I've been searching and experimenting for a week and can't figure out how to do this.

**Comment by j2kun** [comment]
This was the solution I was able to come up with. Would appreciate any suggestions for improvements, or better yet a principled way to do it

http://stackoverflow.com/questions/42212314/tell-react-native-packager-to-watch-a-non-javascript-file/42497592#42497592

**Comment by david-a** [comment]
I had to remove both `react-native-packager-cache-*` AND `haste-map-react-native-packager-*`
thank you all

**Comment by tarheele** [comment]
On windows, I made the mistake of renaming node_modules to node_modules.todelete  in an effort to debug an issue.  Something cached this and gave me an error `P: error: bundling failed: ambiguous resolution: module [mymodule] tries to require 'react-native', but there are several files providing this module. You can delete or fix them: 

  * ...\node_modules.todelete\react-native\package.json
  * ...\node_modules\react-native\package.json`

The key for me was the haste removal tip by @david-a 

I am sharing this mainly so folks can find the error text I encountered

**Comment by leoi11** [comment]
https://gist.github.com/jarretmoses/c2e4786fd342b3444f3bc6beff32098d#gistcomment-2277722

> for RN50 the tmp cache files seems to have a different name

`"clear": "rm -rf $TMPDIR/react-native-packager-cache-* && rm -rf $TMPDIR/metro-bundler-cache-*"`
