### ISSUE TITLE
Image width shrinking when applying PanResponder to swipe in and out of the screen

### ISSUE THREAD

**Issue by sbkl** [facebook/react-native#19244]
## Environment
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 7.10.0
  Yarn: 1.3.2
  npm: 5.5.1
  Watchman: 4.7.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: Not Found

Packages: (wanted => installed)
  react: ^16.3.1 => 16.3.1
  react-native: ^0.55.3 => 0.55.3

## Steps to Reproduce
- Create a flat list
- Apply PanResponder on each list item with an image enabling to swipe the list item in and out of the screen.
- When the list item is swipe back to its initial position and the image is visible again, the image width is smaller.
- Issue on current library: react-native-swipeout. [#264](https://github.com/dancormier/react-native-swipeout/issues/264) illustrating the bug with screenshot,
- I created my own PanResponder to see if it was linked to the library but I got the exact same issue,
- Just downgraded to react-native 0.54.4 and it works properly.

## Expected Behavior
- Image should keep the same width.

## Actual Behaviour
- Image width is shrinking.

**Comment by pinguinjkeke** [comment]
react-native 0.55.4 has same issue.

**Comment by EyalSi** [comment]
Is there a label for "This is a basic behavior with very ugly consequences - we must fix it ASAP as it makes react native looks like an amateur env" that we can label this bug?😊

**Comment by jakallergis** [comment]
I have the same problem! This is related to #20215 as well and is really frustrating. the translateY/X workaround is working but it doesn't change drag the parent layout with it so its not for every scenario. This doesn't fix it.

For me it happend after I upgraded to 0.55.0

**Comment by wesleyamaro** [comment]
Same problem here! Only happens on iOS

**Comment by wesleyamaro** [comment]
That solution worked well for me https://github.com/facebook/react-native/issues/20215

**Comment by jakallergis** [comment]
I can confirm that this is fixed now.
My project deps:
react: 16.5.0
react-native: 0.57.1
