### ISSUE TITLE
[MapView] Ability to add an MKPolyline to a MapView

### ISSUE THREAD

**Issue by ekonstantinidis** [facebook/react-native#1925]
I was wondering if it is possible to add an `MKPolyline` to a `MapView`'s overlay. I couldn't find anything in the docs so thought I should ask/suggest here!

It would also be awesome to be able to use `MKDirections ` but I guess that's too much?

![route](https://cloud.githubusercontent.com/assets/6333409/8605007/0b703856-267a-11e5-8430-4afb7fe97ff6.png)

Ps. Thanks for both react & react native :smile:

**Comment by browniefed** [comment]
I'm not sure the state of who is working on `MapView` but it is likely no one. PRs for stuff like this are usually welcome.

@brentvatne is MapView community support status yet?

**Comment by brentvatne** [comment]
Yeah nobody is actively owning it at Facebook afaik so it's a community thing

**Comment by ide** [comment]
The Ads Manager uses parts of Map but not these aux features. So it's sort of community + the book.

**Comment by chris-erickson** [comment]
@ekonstantinidis Have you worked this at all?  I'll need this functionality for something soon.

**Comment by ekonstantinidis** [comment]
No @chris-erickson.. I haven't at all.. Unfortunately not :disappointed:

**Comment by browniefed** [comment]
@chris-erickson if you need PolyLine support checkout https://github.com/mapbox/react-native-mapbox-gl

**Comment by chris-erickson** [comment]
@browniefed: Thanks - I gave it a solid test run, and it wasn't optimal.  At this time, performance seems like it needs work, and the API isn't too flexible for continually adding new coordinates to a PolyLine.  You have to redraw the map on any new point, as best I can tell, when live tracking your path.  I might just plow forward to get this working with iOS provided API's.

**Comment by timfpark** [comment]
I am interested in this as well - and happy to work on a PR for it.

My proposal would be to add Polyline support as another type of annotation.  Ala:

this.state.annotations = [
 {
            "coordinates": [
                   { "lat": 35.5, "lon": -5.5 },
                   { "lat": 35.6, "lon": -5.6 },
                   ...
            ],
            "type": "polyline",
            "strokeColor": "#FF0000",
            "strokeWidth": 3,
            "strokeAlpha": 0.5
}];

Annotations would be by default "placemarks" so as to be backwards compatible, and you would explicitly need to define other types, like "polyline" above.

@brentvatne @ide If you can confirm this proposal would be acceptable as a PR I can work on it.

**Comment by browniefed** [comment]
If we go with something it should follow geojson spec!

**Comment by chris-erickson** [comment]
@timfpark That's similar to [what MapBox uses](https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/API.md#annotations), and seemed fine when I used it.  Hopefully the native implementation is more performant though.  Every annotation addition redrew the map, which resulted in a noticeable flicker.  I'd be happy to help out/test it.

**Comment by christopherdro** [comment]
Added via https://github.com/facebook/react-native/commit/8911b72d9e78d78b6f8eb99efe21b1205047fd16
