### ISSUE TITLE
[TextInput] onSubmitEditing dismisses keyboard automatically.

### ISSUE THREAD

**Issue by irfaan** [facebook/react-native#1926]
onSubmitEditing automatically dismisses keyboard. Perhaps this should be an option or we should be forced to programmatically close the keyboard in the function passed to onSubmitEditing for single-line inputs?

Noted as a possible bug here: https://github.com/facebook/react-native/issues/641#issuecomment-94579937

**Comment by christopherdro** [comment]
Fixed via https://github.com/facebook/react-native/commit/37042573b82e1c56ffabf80a505de80dee12c553
