### ISSUE TITLE
Text label backgroundColor has alpha display error

### ISSUE THREAD

**Issue by helele90** [facebook/react-native#19260]
- I have reviewed the [documentation](https://facebook.github.io/react-native)
- I have searched [existing issues](https://github.com/facebook/react-native/issues)
- I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

### code
```
import React, { Component } from 'react';
import { Text, View, StyleSheet } from 'react-native';

export default class App extends Component {
  render() {
    return (
      <View style={styles.container}>
      <Text style={[styles.text, {backgroundColor: '#f30301'}]}>backgroundColor: #f30301</Text>
      <Text style={[styles.text, {backgroundColor: '#f3030150'}]}>backgroundColor: #f3030150</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
  },
  text: {
    marginTop: 10,
    height: 40,
    width: 200,
    fontSize: 13,
    textAlign: 'center',
    color: 'white',
  },
});

```
### Image
![9d8b85aea74007e56e808264fca008f7](https://user-images.githubusercontent.com/4125469/40091469-879e8fae-58ea-11e8-918c-a158d3c9d1e4.png)

### Template
template: https://snack.expo.io/H1DvLbYRz

if Text style backgroundColor has alpha, the background display error.
## Environment
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.11.1
  Yarn: 1.6.0
  npm: 6.0.1
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: Not Found

Packages: (wanted => installed)
  react: ^16.3.2 => 16.3.2
  react-native: ^0.55.4 => 0.55.4

**Comment by hramos** [comment]
Can you please fill out the template?

**Comment by helele90** [comment]
@hramos I made a expo demo.
