### ISSUE TITLE
PDF file is not loaded in Image JSX

### ISSUE THREAD

**Issue by sarath-rp** [facebook/react-native#19266]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

I am try to load a pdf document in a image tag but it is not working.
## Environment
 OS: macOS High Sierra 10.13.4
  Node: 8.9.4
  Yarn: Not Found
  npm: 6.0.0
  Watchman: Not Found
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.0 AI-171.4443003
  react: 16.3.1
  react-native: 0.55.4
## Steps to Reproduce
Create a project . Try to load a pdf file like this.
<Image source={require('./img/edit.pdf')} style={ [ styles.iconContainer] } />

## Expected Behavior
The pdf document will be shown

## Actual Behavior
It doesn't showing.

**Comment by hramos** [comment]
I don't think the Image tag is meant to display PDFs.
