### ISSUE TITLE
AsyncStorage not working in iOS release build.

### ISSUE THREAD

**Issue by dooboolab** [facebook/react-native#19273]
ReactNative version 0.55.4

It works fine is debug scheme but when I build to real device with release scheme, it doesn't work.

**Comment by dooboolab** [comment]
Sorry for wasting your time. I've been debugging through this day and found out there is a strange thing happening which wasn't AsyncStorage problem. I think it is matter with `async` and `await` statement. I've been taking all `Alert.alert()` method to my code to find out what is going wrong in my release scheme. Still not sure what is going wrong but found out that it isn't AsyncStorage problem. Closing it.

**Comment by diaraujo13** [comment]
Have you found something?

**Comment by Faisal-Manzer** [comment]
Facing same issue.
Asyncstorage works fine in Debug but is not working on release.
