### ISSUE TITLE
[Navigator] Navigator.getContext is undefined is 0.8.0-rc

### ISSUE THREAD

**Issue by magicismight** [facebook/react-native#1928]
Navigator.getContext is undefined is 0.8.0-rc.
Is there a reason to abort the static method?
I think Navigator.getContext is very useful to me.

**Comment by ide** [comment]
It was removed on purpose to simplify Navigator. Also 0.8.0-rc hasn't been published yet -- do you mean 0.7.0-rc?

**Comment by magicismight** [comment]
@ide 
I downloaded from github,not installed by npm.
Just want to try something awesome in 0.8.0-rc.
Looking forward to it.

**Comment by ide** [comment]
OK, we'll hopefully be able to release 0.8.0-rc soon. I believe getContext was removed in 0.7.0 too BTW - https://github.com/facebook/react-native/commit/4690983c10a60d84a98a2a6f8bdf9a1c39d2ef74

**Comment by jawadrehman** [comment]
@ide is there an alternative to this ?

**Comment by ide** [comment]
No alternative, but you could use React's context to share access to the navigator.

**Comment by grabbou** [comment]
Just pass it down the components as a prop. At least that's what I am doing and I have no limitations to be fair (the routing is quite complex though)

**Comment by ide** [comment]
Good to be explicit about it. It's maybe complex, but the previous system with contextual navigation was complicated.

**Comment by grabbou** [comment]
It's actually quite powerful,
```js
renderScene(route, navigator) {
    var Handler = route.component;

    const navigation = {
      pop: navigator.pop,
      popToTop: navigator.popToTop,
      replaceAtIndex: navigator.replaceAtIndex,
      transitionTo: this.transitionTo,
      getRoute: this.getRoute,
      menu: this.refs.menu
    };

    return (
      <View style={[appStyle.sceneView, route.style]}>
        <Handler navigation={navigation} {...this.state} />
      </View>
    );
  }
```
and you can pass down your own method, like the ones above.

**Comment by ericvicenti** [comment]
Yep, sorry for the confusion, `Navigator` is still under active development. We will bring back context soon. @hedgerwang is working on it!
