### ISSUE TITLE
0.48.4 init project does not work

### ISSUE THREAD

**Issue by GregoryNative** [facebook/react-native#19283]
- [+] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [+] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [-] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

I have a project with react-native 0.48.4 and it stopped work yesterday. I even try to create react-native project with init command (version 0.48.4) did not work. I got this error
<img width="320" alt="screen shot 2018-05-16 at 9 36 51 am" src="https://user-images.githubusercontent.com/22578977/40100479-b28aecce-58ec-11e8-8063-c377abfec9b6.png">

## Environment
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.11.1
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3.1 Build version 9E501
  Android Studio: 2.3 AI-162.3934792

Packages: (wanted => installed)
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: 0.48.4 => 0.48.4

## Steps to Reproduce
react-native init testapp --version=0.48.4

## Expected Behavior
App works.

## Actual Behavior
App don't works.
<img width="320" alt="screen shot 2018-05-16 at 9 36 51 am" src="https://user-images.githubusercontent.com/22578977/40100479-b28aecce-58ec-11e8-8063-c377abfec9b6.png">

**Comment by GregoryNative** [comment]
No, I can't reproduce the issue on v0.55.

**Comment by zym2525** [comment]
I find this same issue on v0.48.3

**Comment by hope0922** [comment]
Do I have to upgrade my version to solve this problem?
