### ISSUE TITLE
[iOS] Unable to archive project if using a custom configuration and using Pods

### ISSUE THREAD

**Issue by gavin-gmlab** [facebook/react-native#19280]
- [Y ] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [Y ] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [N ] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

I've been struggling with this problem for weeks already with my project, and have not been able to resolve this problem.

I am using Cocoapods due to some of my dependencies requiring it. So I can debug using the default scheme and archive the project using the default 'Release' configuration. 

I need additional configurations for staging, beta etc, so when I create a new configuration by duplicating the release config, and then try to archive the project using the new Staging config, I get all sorts of errors. Have tried all kinds of suggestions with the header search path, framework search path and others, including adding $(BUILD_DIR)/Release$(EFFECTIVE_PLATFORM_NAME) to the framework search paths, but keep getting different kinds of errors, so I'm suspecting I'm digging myself into a deeper and deeper hole.

## Environment
Environment:
  OS: macOS High Sierra 10.13.3
  Node: 7.9.0
  Yarn: 1.3.2
  npm: 4.2.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.2 => 0.52.2

## Steps to Reproduce

Steps to reproduce

1. Ignite new archiveproject (Note need to modify the ReduxNavigation file to get it to run)
2. Modify the package.json file dependencies to the following:
`
"dependencies": {
    "apisauce": "^0.14.2",
    "format-json": "^1.0.3",
    "identity-obj-proxy": "^3.0.0",
    "lodash": "^4.17.4",
    "prop-types": "^15.6.0",
    "querystringify": "1.0.0",
    "ramda": "^0.25.0",
    "react": "16.2.0",
    "react-native": "0.52.2",
    "react-native-animatable": "^1.2.4",
    "react-native-audio": "4.1.3",
    "react-native-camera": "1.1.2",
    "react-native-code-push": "5.3.2",
    "react-native-config": "^0.11.5",
    "react-native-device-info": "0.21.5",
    "react-native-fabric": "0.5.1",
    "react-native-fetch-blob": "^0.10.8",
    "react-native-i18n": "1.0.0",
    "react-native-image-crop-picker": "0.20.1",
    "react-native-orientation": "3.1.3",
    "react-native-pdf": "3.0.6",
    "react-native-push-notification": "3.0.2",
    "react-native-sensitive-info": "5.1.0",
    "react-native-sound": "0.10.9",
    "react-native-vector-icons": "4.3.0",
    "react-native-video": "2.0.0",
    "react-navigation": "^1.0.0-beta.21",
    "react-navigation-redux-helpers":"1.0.5",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-persist": "^5.4.0",
    "redux-saga": "^0.16.0",
    "reduxsauce": "0.7.0",
    "seamless-immutable": "^7.1.3"
  },
`
3. cd ios && pod init
4. Modify Podfile to the following:
`

platform :ios, '8.0'

target 'archiveproject' do

    rn_path = '../node_modules/react-native'
    pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
    pod 'React', path: rn_path, subspecs: [
      'Core',
      'RCTActionSheet',
      'RCTAnimation',
      'RCTGeolocation',
      'RCTImage',
      'RCTLinkingIOS',
      'RCTNetwork',
      'RCTSettings',
      'RCTText',
      'RCTVibration',
      'RCTWebSocket',
      'BatchedBridge',
      'DevSupport'
    ]
    pod 'CodePush', :path => '../node_modules/react-native-code-push'
    pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
    pod 'ReactNativeFabric', :path => '../node_modules/react-native-fabric'
    pod 'react-native-camera', path: '../node_modules/react-native-camera'
    pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'
    pod 'RNAudio', :path => '../node_modules/react-native-audio'
    pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'
    pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'
    pod 'react-native-pdf', :path => '../node_modules/react-native-pdf'
    pod 'RNSound', :path => '../node_modules/react-native-sound'
    pod 'react-native-video', :path => '../node_modules/react-native-video'
  end  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
  end

`

5. npm install
6. pod install
7. Open project .xcworkspace file in Xcode
8. Create new configuration in project called 'Staging'
9. Change the archive to use the Staging config
10. Run product->archive (note, need to put in your signing key)

## Expected Behavior
I should be able to archive the project

## Actual Behavior
Archiving fails with the following errors
`ld: warning: directory not found for option '-L/Users/ldarren/react/archiveproject/archiveproject/ios/Build/Intermediates/ArchiveIntermediates/archiveproject/BuildProductsPath/Staging-iphoneos/CodePush'
ld: warning: directory not found for option '-L/Users/ldarren/react/archiveproject/archiveproject/ios/Build/Intermediates/ArchiveIntermediates/archiveproject/BuildProductsPath/Staging-iphoneos/QBImagePickerController'

...

ld: warning: directory not found for option '-L/Users/ldarren/react/archiveproject/archiveproject/ios/Build/Intermediates/ArchiveIntermediates/archiveproject/BuildProductsPath/Staging-iphoneos/react-native-video'
ld: warning: directory not found for option '-L/Users/ldarren/react/archiveproject/archiveproject/ios/Build/Intermediates/ArchiveIntermediates/archiveproject/BuildProductsPath/Staging-iphoneos/yoga'
`

Same error whether or not I have {$BUILD_DIR}/Release${EFFECTIVE_PLATFORM_NAME} in the various search paths.

**Comment by gavin-gmlab** [comment]
Updated to v0.55.4 and the problem still occurs

**Comment by Zycon42** [comment]
Following thing works for me:
In the end Podfile:
```
post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
      if config.name == 'Staging'
          config.build_settings['CONFIGURATION_BUILD_DIR'] = '$(BUILD_DIR)/Release$(EFFECTIVE_PLATFORM_NAME)'
      end
  end

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
        if config.name == 'Staging'
            config.build_settings['PODS_CONFIGURATION_BUILD_DIR'] = '${PODS_BUILD_DIR}/Release$(EFFECTIVE_PLATFORM_NAME)'
        end
    end
  end
end
```

And in main xcode project (**NOT** Pods) I set these variables in Staging configuration
```
CONFIGURATION_BUILD_DIR = "$(BUILD_DIR)/Release$(EFFECTIVE_PLATFORM_NAME)";
PODS_CONFIGURATION_BUILD_DIR = "${PODS_BUILD_DIR}/Release$(EFFECTIVE_PLATFORM_NAME)";
```

**Comment by gavin-gmlab** [comment]
@Zycon42, thanks for this. I tried this, but looking in the .xcconfig file for Staging, I still see that the PODS_CONFIGURATION_BUILD_DIR in that file is still $(PODS_BUILD_DIR)/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME).

Is that correct?

**Comment by gavin-gmlab** [comment]
I managed to solve the problem. Steps taken:
1. Rebuild project from scratch
2. Include react-native-schemes-manager in the process.
3. In custom schemes, seems like the react target is not always added, even after using react-native-schemes-manager. So needed to add React to the build target and make sure it is above the project build target in the build heirarchy
