### ISSUE TITLE
android 8.1 some image no show use require('../../images/icon.png')

### ISSUE THREAD

**Issue by meiqi1992** [facebook/react-native#19282]
android 8.1 some images no show use require('../../images/icon.png') 

React Native version: 0.55.4
Platform: Android

devices: Android 8.1

**Comment by meiqi1992** [comment]
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 10.1.0
  Yarn: 1.6.0
  npm: 5.6.0
  Watchman: 4.9.0
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

here this is my code:

<Image style = {{width:50,height:50,}}
              resizeMethod="resize"
              source = {require('../djImages/gear.png')} />


in android 7.0  image can show, but android 8.1 it no show. not all images can not show, just some can show some can not show .

**Comment by MiaoApple** [comment]
same question

**Comment by Deain** [comment]
Just the same question !!!!!!!!!
