### ISSUE TITLE
Keyboard doesnot show when tap on TextInput for Android OPPO A53m phone

### ISSUE THREAD

**Issue by sirhu11** [facebook/react-native#19290]
## Detail
 Keyboard doesnot show when tap on TextInput for Android OPPO A53m phone,RN version 0.53.3;
## Environment
 OS: Windows 10
  Node: 9.8.0
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found
  Android Phone: OPPO A53m
react: 16.2.0 => 16.2.0
  react-native: 0.53.3 => 0.53.3

more info:
Environment:
  OS: Windows 10
  Node: 9.8.0
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.3 => 0.53.3

## Steps to Reproduce
page NO.1 has two TextInput s, and page NO.2 has two TextInputs;
Step1: in the page NO.1, tap on one TextInput , the keyboard will show;
Step2: then navigate to page No.2  from page No.1 ;
Step3:  in the page NO.2, tap on one TextInput , the keyboard will show;
Step4: then go back to page NO.1;
Step5: in the page NO.1, tap on one TextInput , the keyboard will not show;

## Expected Behavior
The keyboard will show whenever  tapped on an TextInput ;

## Actual Behavior
The keyboard may not show when tap on an TextInput

**Comment by sirhu11** [comment]
@react-native-bot  I will Test on v0.55 later, then reply the result to u

**Comment by sirhu11** [comment]
@react-native-bot the issue also reproduce on the latest release, v0.55

**Comment by sirhu123** [comment]
@react-native-bot 
### page1.js
```
import React, { Component } from 'react';
import { View, TextInput, StyleSheet, Button } from 'react-native';

export default class Page1 extends Component {
    render() {
        const { navigate } = this.props.navigation;
        return (
            <View>
                <TextInput
                    style={styles.input}
                    placeholder='TextInput 1'
                />
                <TextInput
                    style={styles.input}
                    placeholder='TextInput 2' />
                <Button
                    color="#841584"
                    title='go to page2'
                    style={styles.button}
                    onPress={() => navigate('page2')} />
            </View>
        );
    }
}

const styles = StyleSheet.create(
    {
        input: { height: 40 },
        button: { height: 40 }
    }
)
```
### page2.js
```
import React, { Component } from 'react';
import { View, TextInput, StyleSheet } from 'react-native';

export default class Page2 extends Component {
    render() {
        return (
            <View>
                <TextInput
                    style={styles.input}
                    placeholder='TextInput 1'
                />
                <TextInput
                    style={styles.input}
                    placeholder='TextInput 2' />
            </View>
        );
    }
}

const styles = StyleSheet.create(
    {
        input: { height: 40 }
    }
)
```
### App.js
```
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React from 'react';
import { StackNavigator } from 'react-navigation';
import Page1 from './src/page1';
import Page2 from './src/page2';

const App = StackNavigator({
  page1: { screen: Page1 },
  page2: { screen: Page2 },
});

export default App;

```

**Comment by yuyao110120** [comment]
OPPO A59m have the same problem.

**Comment by hanning2014** [comment]
the latest version still has this problem , It is a bug. Can anyone help?

**Comment by kaixin321** [comment]
so many people offer so many example, why this bug is exist so long time

**Comment by shinian123456** [comment]
<TextInput
...
autoFocus={true}
...>

so easy .@kaixin321

**Comment by kaixin321** [comment]
> <TextInput
> ...
> autoFocus={true}
> ...>
> 
> so easy .@kaixin321
only one page is ok , two page,while input text in one keyboard, text is show in another page
if two page text input all have autoFocus={true} , pop(), then bug is also exsit.
so stupid solution!!!
