### ISSUE TITLE
React-Native 0.55.4 with gradle 4.4 not working

### ISSUE THREAD

**Issue by kolyneh** [facebook/react-native#19293]
Dependencies :

 dependencies {
        classpath 'com.android.tools.build:gradle:3.1.0'
    }

distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip

Result:
  Cannot resolve symbol 'SoLoader' in MainApplication

- [ ] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [ ] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment

Environment:
  OS: Windows 10
  Node: 8.10.0
  Yarn: Not Found
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: ^0.55.4 => 0.55.4

**Comment by 841660202** [comment]
i also encounter this problem

**Comment by kolyneh** [comment]
@idcmsbeta @841660202 
It works after removed "./gradle" and "./idea" then rebuild.

**Comment by kolyneh** [comment]
@idcmsbeta Yeah, it's closer day by day, and React-Native doesn't seem to have actions on it.

**Comment by idcmsbeta** [comment]
@kolyneh  in the discorpapp  they said will updated those old sdk 23 to 26 in early jun.. not sure it will done.. But 0.55.4 and new update gradle messing  up all of thing up.

**Comment by pavjacko** [comment]
For those who still encounter this issue,
I've managed to get it working with:
* react-native 0.56.0
* targetSdkVersion 27
* gradle: 4.9-RC1
* android-gradle: 3.3.0-ALPHA3

example project:
https://www.npmjs.com/package/react-native-vanilla
