### ISSUE TITLE
[XMLHttpRequest] How to use Fetch API to get excel file data from a link

### ISSUE THREAD

**Issue by bright-sea** [facebook/react-native#1929]
I can use fetch to get csv file data (text) from a link like:

               fetch(this.state.fileUrl)
                    .then((response) => {
                        console.log("response", response);
                        return response.text();
                    })

But if the fileUrl was a link to an excel file, the response.body was null and response.text was empty. 

I tried use XmlHttpRequest directly, like:

               var request = new XMLHttpRequest();
                
                request.responseType = "blob";
                request.onreadystatechange = (e) => {
                    if (request.readyState !== 4) {
                        return;
                    }
                    if (request.status === 200) {
                        console.log('success', request);
                    } else {
                        console.warn('error');
                    }
                };

                request.onload = function(oEvent) {
                    var blob = request.response;
                    console.log("blob", blob);
                    // ...
                };
                
                request.open('GET', this.state.fileUrl);
                request.send();

It was the same. I also tried use superagent library, still the same:

               agent.get(this.state.fileUrl)
                    .accept('application/vnd.ms-excel')
                    .end(function(err, response) {

                    console.log("agent response", response);
                });

Is fetch (and XmlHttpRequest) support in react native only can fetch text data, no binary data. Or I am doing something wrong at here?

**Comment by brentvatne** [comment]
@bright-sea - if you do the exact same request in the browser with superagent or fetch, does that work?

**Comment by bright-sea** [comment]
@brentvatne 

Just tried use fetch API in chrome, it doesn't work for cross domain resources (Same origin policy), but it works well for same origin resources. I can get response both for text data (for example, a link to a csv file) and binary data (for example, a link to an excel file).

In react native, it works for any resources link, but only text data populated in response.text.  For binary data, we can get response as well, but response.body is null and response.text is empty.

**Comment by brentvatne** [comment]
cc @nicklockwood

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/xmlhttprequest-how-to-use-fetch-api-to-get-excel-file-data-from-a-link
