### ISSUE TITLE
Opacity applied to View seams to bug border

### ISSUE THREAD

**Issue by jorgefernandes** [facebook/react-native#19306]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.5.0
  Yarn: 0.27.5
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.3.0-alpha.1
  react-native: https://github.com/expo/react-native/archive/sdk-22.0.1.tar.gz => 0.54.2

## Steps to Reproduce

My View have the following style: 

{
    borderWidth: 2,
    borderRadius: 100,
    paddingVertical: 15
    opacity: 0.15,
}

## Actual Behavior

![screenshot_20180516-180131](https://user-images.githubusercontent.com/415791/40144033-8fed895a-5933-11e8-9763-00d09336b951.jpg)

**Comment by hunterway55** [comment]
https://github.com/facebook/react-native/issues/17267
