### ISSUE TITLE
Strange width behavior on IOS

### ISSUE THREAD

**Issue by felippepuhle** [facebook/react-native#19302]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

I created a custom tab component and I got a strange width behavior on `IOS` (Android seems to be fine). Every time I use `Animated` to change the current tab, the previous one loses a bit of width. I tried a lot of implementations, and all of them got the same result... The strange fact is: if I use `setValue()` instead of `Animated.timing`, the bug won't occur.

PS: I decided to create this custom tab 'cause the existing one use `ScrollView` to handle the 'swipe gesture'(dragging to change tab), and I use a `FlatList` at the tab content... This was causing a lot of `onEndReached` calls... see https://github.com/react-native-community/react-native-tab-view/issues/501

[Demo](https://snack.expo.io/rksdq1qCf)

## Environment

```
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.9.0
  Yarn: 0.24.6
  npm: 5.7.1
  Watchman: 4.9.0
  Xcode: Xcode 9.1 Build version 9B55
  Android Studio: 3.1 AI-173.4670197

Packages: (wanted => installed)
  react: ^16.3.0 => 16.3.2
  react-native: 0.55.4 => 0.55.4
```

## Steps to Reproduce
See https://snack.expo.io/rksdq1qCf

## Expected Behavior
Don't change tab `width` whenever I change the current tab.

## Actual Behavior
Every time I change the tab, the previous one lost some `width`, overriding my style

**Comment by RomualdPercereau** [comment]
It looks like the bug only occurs then: 
`useNativeDriver: false`

**Comment by felippepuhle** [comment]
fixed! used `translateX` instead of `left`, `marginLeft` and others... 😄
