### ISSUE TITLE
Destructuring object with rest operator failed when using Number keys

### ISSUE THREAD

**Issue by riwu** [facebook/react-native#19307]
```
const obj = { 1: 'v1', 2: 'v2' };
const key = 1;

const { [String(key)]: a, ...b } = obj;
console.log(a, b); // a is 'v1', b is { 2: 'v2' }

const { [key]: c, ...d } = obj;
console.log(c, d); // c is 'v1', d is { 1: 'v1', 2: 'v2' }
```
Demo: https://snack.expo.io/@riwu/destructuring-number-key

Works as intended on [Chrome browser](https://jsfiddle.net/c5fh0ozf/), but gave the same output as above when using [Chrome debugging, which supposedly uses the same V8 engine as Chrome browser](https://facebook.github.io/react-native/docs/javascript-environment.html#javascript-runtime)? 

### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 9.10.1
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.2 => 0.55.2

**Comment by riwu** [comment]
Not yet resolved...

**Comment by riwu** [comment]
-stale

**Comment by patrickkempff** [comment]
@riwu, thank you for reaching out!
 
I tried the provided snack with the latest version of Expo (v32, see https://snack.expo.io/ry8rLgPr4) and it seems to be working as expected. 

The response I got:
<img width="106" alt="screenshot 2019-02-17 at 15 56 19" src="https://user-images.githubusercontent.com/310766/52914805-054b0d80-32cd-11e9-90ed-8f06bf6de2d8.png">

Therefore I'm closing this issue. If you don't agree or the issue still persists with the latest version of React Native, please feel free to file a new issue report.
