### ISSUE TITLE
[Navigator] Why the onItemRef be invoked only once？  

### ISSUE THREAD

**Issue by everfire130** [facebook/react-native#1931]
![image](https://cloud.githubusercontent.com/assets/11308837/8611781/c5080c66-26f8-11e5-9be8-6404c69df672.png)
The docs say 'onItemRef will be called with (ref, indexInStack, route) when the scene ref changes',but I find it be called when  navigator push,not will be called when navigator pop

**Comment by everfire130** [comment]
I have updated to 0.8.0-rc ,the problem has not happened againO(∩_∩)O~~

**Comment by brentvatne** [comment]
Thanks for the follow up @everfire130
