### ISSUE TITLE
Share Component not working on app Android

### ISSUE THREAD

**Issue by tranvannhat** [facebook/react-native#19322]
## Environment

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.11.1
  Yarn: 1.6.0
  npm: 5.6.0
  Watchman: Not Found
  Xcode: Xcode 9.3.1 Build version 9E501
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: ^0.55 => 0.55

Share component not working right on Android. When i using component and share on facebook android, content not trigger to fb app
I want to use component official, I check for errors on most versions, can you fix it?

![screenshot_2018-05-17-14-33-16-480_android 1](https://user-images.githubusercontent.com/28804941/40163079-0be2e22e-59e0-11e8-8d1d-ec1fa4b83953.png)
![screenshot_2018-05-17-14-33-29-646_com facebook katana](https://user-images.githubusercontent.com/28804941/40163081-0c1c04aa-59e0-11e8-86f0-8d4ddfffafa6.png)

**Comment by tranvannhat** [comment]
@hunterway55 
`handleShare = () => {
    Share.share(
      {
        message: this.state.articleDetail.title.rendered,
        url: this.state.articleDetail.link,
        title: this.state.articleDetail.title.rendered
      },
      {
        subject: 'Share',
        dialogTitle: 'Share Article',
        excludedActivityTypes: ['com.apple.UIKit.activity.PostToTwitter'],
        tintColor: 'green'
      }
    )
      .then(console.info('success'))
      .catch(e => console.info(e));
  };`
On iOS but Android Facebook not working, other social working right

**Comment by suwu150** [comment]
Can the Share component share files in android? I am prompted to "Get Resource Failed" when I use it. How do you do it?
