### ISSUE TITLE
Unable to resolve module react-native-router-flux/index

### ISSUE THREAD

**Issue by marcojr** [facebook/react-native#19329]
Hi ! Suddenly my app stopped to work...No reason...

![simulator screen shot - iphone 7 plus - 2018-05-17 at 11 39 08](https://user-images.githubusercontent.com/856617/40174447-07365156-59cd-11e8-9e32-8dc55e262ae3.png)

I checked the issue#4968. It's does not look compatible. So I decided to follow the steps...

1 - I'm not using watchman and when I use this command on my terminal, there is no "watchman" installed or on my $path

2- Yes, I deleted the modules...many times...installed with npm and yarn...no effect.

3- I don't have this directory on my computer.

I decided to check the node_modules..and yes, looks like the error is legit..there is no index.js over there. Instead, there is a index.d.ts which is a typescript file.

<img width="218" alt="captura de tela 2018-05-17 as 12 25 26" src="https://user-images.githubusercontent.com/856617/40174571-74699580-59cd-11e8-8660-48b85d3bd27f.png">

Any clue ?

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.11.1
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: Not Found
  Xcode: Xcode 9.3.1 Build version 9E501
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: 0.54.0 => 0.54.0

**Comment by marcojr** [comment]
Ok, updated to 0.55...this persists.

**Comment by xmannv** [comment]
Remove /index from "react-native-router-flux/index" will resolve your case.
