### ISSUE TITLE
PermissionsAndroid request - missing dismiss button for initial dialog (or custom buttons)

### ISSUE THREAD

**Issue by MarkOSullivan94** [facebook/react-native#19327]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [ ] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

I seen this had already been reported #13920 but had been closed so reopening this.

The dialog produced when requesting permissions isn't user friendly. There's no option to dismiss the dialog and so may seem confusing to the users. 

An quick  fix would be to include a dismiss button automatically but an additional field along with 'title' and 'message' called 'button' would be great for having custom text in the button.

## Environment

Environment:
  OS: Linux 4.4
  Node: 9.4.0
  Yarn: Not Found
  npm: 5.8.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: ^16.0.0-beta.5 => 16.0.0-beta.5
  react-native: ^0.50.4 => 0.50.4

## Steps to Reproduce

Add the following function to your project and call it.

```
async function requestPermission() {
	if (Platform.OS === "ios") {
		return true;
	}

	try {
		const granted = await PermissionsAndroid.request(
			PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE,
			{
				title: "Enable Permission",
				message:
					"Message here"
			}
		);
		switch (granted) {
			case PermissionsAndroid.RESULTS.GRANTED:
				return true;
			case PermissionsAndroid.RESULTS.DENIED:
				return false;
			case PermissionsAndroid.RESULTS.NEVER_ASK_AGAIN:
				await doAlert(neverAskAgainTitle, neverAskAgainMessage);
				return false;
		}
	} catch (e) {
		console.log(e);

		// fall through
	}
	return false;
}
```

## Expected Behavior

Expected the dialog to include a dismiss button so they can get to the actual permission dialog.

## Actual Behavior

Dialog produced shown below.
![screenshot_1526551341](https://user-images.githubusercontent.com/6950843/40170950-cce50c00-59c1-11e8-9bae-9b7763a5ee67.png)

**Comment by MarkOSullivan94** [comment]
I assume this is still the case in 0.55 as there's nothing been updated in the docs to suggest otherwise.

**Comment by MarkOSullivan94** [comment]
Yes.

**Comment by garrottkai** [comment]
definitely still an issue
