### ISSUE TITLE
React Native Modal Component not visible randomly in IOS 

### ISSUE THREAD

**Issue by srimalfernando** [facebook/react-native#19345]
## Environment

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.9.4
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: 9.3
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.50.4 => 0.50.4

## Steps to Reproduce

Issue occur randomly with toggle actoin

## Expected Behavior

showing the modal view from toggle action

## Actual Behavior

React Native Modal view invisible randomly in IOS

**Comment by jpamarohorta** [comment]
I'm having the same issue. When toggling only, sometimes the modal doesn't show up although it appears in the component structure when inspected. Did you find a solution @srimalfernando ?
