### ISSUE TITLE
Dropping Support for iOS 8

### ISSUE THREAD

**Issue by hramos** [facebook/react-native#19346]
iOS 8 was released almost 4 years back, an eternity for iOS releases. Thanks in part to the fact that any device that can run iOS 8, can also run iOS 9, it's used by less than 0.5% of devices. Anyone who wants to, can upgrade to iOS 9.

With these facts in mind, we will be dropping official support for iOS 8 starting next week. The core React Native team will no longer run tests on iOS 8 devices and will not maintain any workarounds that may be in place to support iOS 8. Dropping support for iOS 8 will also help React Native achieve consistency with the rest of the codebase at Facebook. 

### Workarounds

Developers who support iOS 8 in their apps may continue doing so as this is a Xcode-level setting (`IPHONEOS_DEPLOYMENT_TARGET`). Please be aware that any issues you may encounter when your app is running on iOS 8 devices will not be considered a priority.

**Comment by jeveloper** [comment]
@hramos  Thanks, Out of curiosity, is 0.56 coming out soon? thanks

**Comment by newyankeecodeshop** [comment]
Will you also be able to upgrade the JavaScriptCore shipped with Android to a version compatible with the iOS 9 version of JavaScriptCore? That would allow some of the older polyfills (e.g `Map`,`Set`, `Object.assign`) to be removed, and keep some consistency in the JavaScript runtime between iOS and Android.

**Comment by fkgozali** [comment]
https://github.com/facebook/react-native/commit/f50df4f5eca4b4324ff18a49dcf8be3694482b51 updated target deployment for RNTester/React xcode project to 9.0, and also removed RCTFont specific overrides for iOS <8.2.

**Comment by ikesyo** [comment]
@fkgozali You should also update `React.podspec`’s `ios => "8.0"` to 9.0.

**Comment by fkgozali** [comment]
https://github.com/facebook/react-native/commit/092103e7525e58e04346e0a1a16a67ca4f31c2e9 updates a few .podspec files to iOS 9.0

**Comment by hramos** [comment]
Support for iOS 8 has been dropped. Thanks @fkgozali for working on this. There's a few deprecated methods that are yet to be removed but it's been worked on. This issue can now be closed.
