### ISSUE TITLE
Android - User defined process.env.NODE_ENV is overwritten on build

### ISSUE THREAD

**Issue by sam-adam** [facebook/react-native#19341]
## Environment
react-native-cli: 2.0.1
react-native: 0.47.1

## Steps to Reproduce
- Added `staging` flavor to `android/app/build.gradle`
- Run `export NODE_ENV=staging && cd android && ./gradlew assembleStaging`
- Review the value using `console.log(process.env.NODE_ENV);`

## Expected Behavior
It would printed `'staging'`

## Actual Behavior
It printed `'production'`

## Additional Info
It could be an effect of this line 
https://github.com/facebook/react-native/blob/9347583d8a0747f476b8f2ecaa5dcbc6a91502f9/local-cli/bundle/buildBundle.js#L43-L45

Upon further inspection, my expected behavior is already implemented in a this commit https://github.com/facebook/react-native/commit/402e7eaac2f15b98bb15ce13198afe2393cb2503 but it gets undone when this commit gets merged https://github.com/facebook/react-native/commit/e8b508144fdcdea436cf4d80d99daec757505c70#diff-39b89923b957ebc1221d83f686f77f41

Another user already mentioned about the same thing, as can be seen in the image below.

![image](https://user-images.githubusercontent.com/2836541/40233092-c980eff6-5acb-11e8-92e9-14632a92187d.png)

**Comment by sam-adam** [comment]
Info added

**Comment by hramos** [comment]
0.47.1 is quite old and we're only tracking issues on the latest release (0.55 as of this writing).
