### ISSUE TITLE
error: bundling failed: "Unable to resolve module `Image` from `/Users/Harbey/Documents/React/page_app/node_modules/react-native/Libraries/react-native/react-native-implementation.js`

### ISSUE THREAD

**Issue by ayobami303** [facebook/react-native#19344]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [ ] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

error: bundling failed: "Unable to resolve module `Image` from `/Users/Harbey/Documents/React/page_app/node_modules/react-native/Libraries/react-native/react-native-implementation.js`: Module does not exist in the module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`."

i got this error after adding ios app icon. everything works before but after adding the icons i get the above error.

i am running react-native 0.47.1

package.json
---------------
    "axios": "^0.16.2",
    "currency-formatter": "^1.2.1",
    "html-entities": "^1.2.1",
    "lodash": "^4.17.4",
    "moment": "^2.18.1",
    "querystring": "^0.2.0",
    "react": "16.0.0-alpha.12",
    "react-native": "^0.47.1",
    "react-native-calendar-strip": "^1.2.1",
    "react-native-credit-card-input": "^0.3.3",
    "react-native-device-info": "^0.11.0",
    "react-native-elements": "^0.15.0",
    "react-native-keyboard-aware-scroll-view": "^0.2.9",
    "react-native-navigation": "^1.1.182",
    "react-native-pages": "^0.5.3",
    "react-native-swipe-list-view": "^0.4.1",
    "react-native-timer": "^1.3.1",
    "react-native-ui-lib": "^2.0.71",
    "react-native-vector-icons": "^4.6.0",
    "react-redux": "^5.0.5",
    "redux": "^3.7.2",
    "redux-form": "^7.0.3",
    "redux-logger": "^3.0.6",
    "redux-persist": "^4.8.3",
    "redux-persist-migrate": "^4.1.0",
    "redux-thunk": "^2.2.0",
    "rn-viewpager": "^1.2.3"

**Comment by SFRohan** [comment]
I am facing the same issue. Any luck ?

**Comment by zetekla** [comment]
same here
