### ISSUE TITLE
[Inspector] Broken in master

### ISSUE THREAD

**Issue by brentvatne** [facebook/react-native#1934]
@jaredly - clicking on any View appears to have no effect

![nothing](https://cloud.githubusercontent.com/assets/90494/8612746/58597f1e-268a-11e5-8865-dd79ad94df0c.gif)

(also, very minor but the text "Tap something to inspect it" on the overlay should probably be white)

**Comment by ide** [comment]
cc @a2, maybe related to view hierarchy flattening?

**Comment by brentvatne** [comment]
If we can get this fix in before 0.8.0-rc release which we hope to do tomorrow, that would be ideal @jaredly

**Comment by vjeux** [comment]
cc @frantic

**Comment by vjeux** [comment]
cc @shayne

**Comment by jaredly** [comment]
@vjeux looks like the objc side is messed up -- I'll look into it

**Comment by jaredly** [comment]
@vjeux now fixed internally

**Comment by ide** [comment]
Could you guys sync the fix shortly? We can always include it with rc.2 but would be nice to include it with the rc since the issue's already been fixed.

**Comment by jaredly** [comment]
yeah I'll get on it

**Comment by brentvatne** [comment]
thanks @jaredly - waiting on this then we will ship the 0.8.0-rc release :heart_eyes:

**Comment by shayne** [comment]
Thanks @jaredly!

**Comment by ide** [comment]
@jaredly - fantastic, RC is ready to go =D
