### ISSUE TITLE
Unable to use local version of React Native

### ISSUE THREAD

**Issue by MarkOSullivan94** [facebook/react-native#19358]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

Currently trying to make changes to the React Native source to help improve the share functionality for Android (or at least try to).

Was following this guide: https://facebook.github.io/react-native/docs/building-from-source.html#3-adding-the-reactandroid-project

I got to this step: https://facebook.github.io/react-native/docs/building-from-source.html#3-adding-the-reactandroid-project

Unfortunately after running `react-native run-android`, I was no longer getting a successful build.

app build.gradle - https://github.com/MarkOSullivan94/ReactNativeShareExample/blob/master/android/app/build.gradle

settings.gradle - https://github.com/MarkOSullivan94/ReactNativeShareExample/blob/master/android/settings.gradle

## Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 10.1.0
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: github:MarkOSullivan94/react-native#master => 1000.0.0

## Steps to Reproduce

Clone my example project which I was building to test out the changes to the RN source: https://github.com/MarkOSullivan94/ReactNativeShareExample

Then run it with `react-native run-android`.

## Expected Behavior

The app would build successfully.

## Actual Behavior

```
 react-native run-android
Scanning folders for symlinks in /Users/mos/Projects/ReactNative/ShareExample/node_modules (12ms)
(node:92189) ExperimentalWarning: The fs.promises API is experimental
JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug)...

FAILURE: Build failed with an exception.

* Where:
Settings file '/Users/mos/Projects/ReactNative/ShareExample/android/settings.gradle' line: 6

* What went wrong:
A problem occurred evaluating settings 'ShareExample'.
> Cannot cast object '../node_modules/react-native/android' with class 'java.lang.String' to class 'java.io.File'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.08 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
```

**Comment by MarkOSullivan94** [comment]
@grabbou you told me to ping you and @hramos about seeking help this issue. Hoping one of you could help point me in the right direction.

**Comment by MarkOSullivan94** [comment]
Still requires community attention

**Comment by hramos** [comment]
Perhaps @dulmandakh or @gengjiawen can help.

**Comment by gengjiawen** [comment]
@MarkOSullivan94 Can you upgrade the project to to 0.57.rc3. The forked react-native now is not working on windows.

**Comment by gengjiawen** [comment]
Okay, using circleci find out the reason, in `setting.gradle` line 6, it should be `,` not `=`
```
project(':ReactAndroid').projectDir = new File(
    rootProject.projectDir = '../node_modules/react-native/android'
)
```

**Comment by gengjiawen** [comment]
Actually you project has inconsistency. You may need to cleanup. For your project now, You need to add to `build.gradle`
```gradle
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
```

**Comment by MarkOSullivan94** [comment]
Thanks for the help @hramos @gengjiawen. Now stuck on another issue which I've opened as a new issue: https://github.com/facebook/react-native/issues/21776
