### ISSUE TITLE
[Perf] Memory leak in application

### ISSUE THREAD

**Issue by VictorKoenders** [facebook/react-native#1935]
I seem to have hit an issue with my application, after loading data and re-rendering the screen, the application seems to freeze. The data does get rendered, because the console.After that the memory spikes up and after a little while the application crashes in RCTShadowView. I've attached the source code of the app.

I'm using version 0.6.0 from NPM. The modules I use are es6-promise, react-native-sqlite (slightly modified to allow for temp folder loading and BLOB to base64 loading) and react-native-viewport.

If you're trying to load the app and it says there's 'no table Employee', just wait a second and restart it, it will automatically have downloaded the database in the background (See main.js and DownloadManager.m)

The view that triggers the memory leak can be found here https://gist.github.com/VictorKoenders/8e030bda22729c27bc91 but this has happened in different locations in the app as well.

![screen shot 2015-07-10 at 09 17 15](https://cloud.githubusercontent.com/assets/2743142/8613900/7d77cf6c-26e4-11e5-9a2d-f738a593f1b0.png)

![screen shot 2015-07-10 at 09 00 39](https://cloud.githubusercontent.com/assets/2743142/8613877/1a1f166e-26e4-11e5-9d7f-809a7caa24ed.png)

The entire app can be downloaded here: *removed*

**Comment by MossP** [comment]
That's a lot of work for anyone to debug. See if you can nail it down to a smaller example set of code if possible.

**Comment by jaygarcia** [comment]
Does this happen on a device too?  I recall seeing an issue with the debugging portion of the code having a memory leak some time ago.

**Comment by VictorKoenders** [comment]
So I did some experimentation and found out where exactly the memory leak occurs. https://gist.github.com/VictorKoenders/75fc8c5bfcf47ffd197a

I have a list of components that need to be rendered. In the Visualizer.js I render these on the page (the idea is that in the future we can display them differently based on the screen dimensions)

The visualizer adds some styles to a parent view of the component it's rendering. If I remove these styles the application works fine, when I re-add them it freezes again.

At least I'm able to continue developing. If a solution pops up let me know.

@jaygarcia I have no device at the moment, so I can't test this

**Comment by brentvatne** [comment]
@VictorKoenders - if you disable only `flexWrap: 'wrap'` does it still cause perf issues?

**Comment by browniefed** [comment]
@brentvatne is this the css-layout wrap issue that was fixed? Seems like it

**Comment by ide** [comment]
Please reopen if this is persists on 0.11 or master.
