### ISSUE TITLE
Slider maximumValue with some special numbers like 1006.5824985 has some calculate problem

### ISSUE THREAD

**Issue by Xaber20110202** [facebook/react-native#19364]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.3.0
  Yarn: 1.6.0
  npm: 5.5.1
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.2
  react-native: ~0.55.2 => 0.55.4

## Steps to Reproduce

Set Slider with a special amount 1006.5824985, there is a problem

The code is that

```
import * as React from 'react'
import { View, Slider, Text } from 'react-native'

class SlderTest extends React.Component {
  constructor(props) {
    super(props)
  }

  state = {
    amount: 1,
  }

  handleSlidingChange = (amount) => {
    console.log(amount)
    this.setState({ amount })
  }

  render () {
    return <View style={{ paddingTop: 30, width: 300 }}>
      <Text>{this.state.amount}</Text>
      <Slider
        minimumValue={0}
        maximumValue={1006.5824985}
        value={this.state.amount}
        onValueChange={this.handleSlidingChange}
        onSlidingComplete={this.handleSlidingChange}
      />
    </View>
  }
}
export default SlderTest

```

## Expected Behavior

The amount should not be larger then 1006.5824985

## Actual Behavior

But the handleSlidingChange will receive like 1006.58251953125

Another test maximumValue, like 150.00007582, has wrong behavior too.

Thanks!
Same issue https://github.com/facebook/react-native/issues/18957

**Comment by ioss** [comment]
@Xaber20110202 maximumValue is a float value in the native component, and 1006.5824985 is 1006.58251953125 as float.

**Comment by Xaber20110202** [comment]
This problem is still exist on react-native@0.56

**Comment by Xaber20110202** [comment]
May be it's not a very serious problem, but may cause some unexpected behaviors
