### ISSUE TITLE
possible memory leak

### ISSUE THREAD

**Issue by jcharbo** [facebook/react-native#19375]
I have noticed a significant increase in RAM usage as time is spent in my app and I think I've isolated it to React Native leaving memory in use after items are rendered and then no longer rendered.  

I have created a sample project to demonstrate the issue.  The sample loads 5,000 text components and then removes them from render yet much of the RAM is not released after removal.  

Although 5,000 text nodes at once is not realistic, the continual loading and removal of up to 5,000 text nodes throughout usage of the app is realistic.  

## Steps to Reproduce
Clone the following repository and follow the readme instructions.
https://github.com/thejump/react-native-leak-test

## Expected Behavior
RAM will be released when text items are no longer rendered.

## Actual Behavior
RAM continues to increase as text items are rendered and then no longer rendered.

**Comment by GantMan** [comment]
I pulled your repo and was able to validate your findings.  I've always thought GC would catch up and grab that DB but holding on to hundreds of megs and never letting go alarming.

**Comment by jcharbo** [comment]
Environment
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 10.1.0
  Yarn: 1.6.0
  npm: 6.0.1
  Watchman: 4.9.0
  Xcode: Xcode 9.3.1 Build version 9E501
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

**Comment by kelset** [comment]
Sorry folks, not sure why the bot is not complying with the labels, reopening since this is potentially a big issue

**Comment by ashokkumar88** [comment]
@kelset Did you find any solution for memory leak?

**Comment by kelset** [comment]
I'm fairly sure that this and similar memory leaks were fixed in the past few months of commit. You can check the changelog and the commit history for precise indications.
