### ISSUE TITLE
Can't find version 0.18 building on Android

### ISSUE THREAD

**Issue by RafaelOda** [facebook/react-native#19396]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment

```
Environment:
  OS:  macOS High Sierra 10.13.4
  Node:  9.11.1
  Yarn:  1.5.1
  npm:  5.6.0
  Watchman:  4.7.0
  Xcode:  Xcode 9.3 Build version 9E145
  Android Studio:  2.2 AI-145.3360264

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.3 => 0.55.3
```

## Steps to Reproduce

- Have a react-native build that depends on some lib that has the following line in `android/build.gradle` file:
`compile 'com.facebook.react:react-native:0.18.+'`
Try to build and verify an error occurs.

## Expected Behavior

Build succeeds.

## Actual Behavior

Build failed.
See the following sample error message:
* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-amplitude-analytics'.
      > Could not resolve all dependencies for configuration ':react-native-amplitude-analytics:_debugPublishCopy'.
         > Could not find any version that matches com.facebook.react:react-native:0.18.+.
           Versions that do not match:
               0.20.1
               0.14.0
               0.12.0
               0.55.3
           Required by:
               project :react-native-amplitude-analytics
>

**Comment by RafaelOda** [comment]
I know this might be solved by pinning a newer version or just making it target `com.facebook.react:react-native:+` but I find it rather strange that it was able to find older versions such as 0.14.0 but not 0.18.+. 
If this version was removed, how can we find out the status of each version? Is there a schedule for removal as well?

Thanks a lot.

**Comment by ccchen1213** [comment]
![image](https://user-images.githubusercontent.com/34128411/40404227-40032854-5e89-11e8-914b-ba46b00337a0.png)
Same issues

**Comment by mrfarahani** [comment]
I have the same issue. It was just working fine before, but now I get this error. I need to release my app. Even running `gradle clean` fails now.

**Comment by kelset** [comment]
Please refer to https://github.com/facebook/react-native/issues/19259

**Comment by RafaelOda** [comment]
Hi @kelset, thanks for replying here.

I'm having some trouble understanding how #19259 is related to this issue. It seems to me that it is a different problem.

Your comment on that thread was:

> As mentioned by @Wiltzu it seems that this issue surfaced when someone on maven 'upgraded' the react native dependency.
This means that you need to fix your dependency instead of just depending on "latest" (which is standard behaviour on Android when you don't explicitly say the version number - from my understanding).

>I urge you all to properly set fixed version numbers on your gradle files (and also your package.json, and so on) for each dependency in order to avoid these kind of side effects.

What I'm facing is exactly the opposite here. We have the version number set to `0.18.+`. I know it's very ancient, but I have also read #13094 and it looks like `0.18.0`is published both in Maven and Bintray. 

FYI, I have checked:
https://bintray.com/bintray/jcenter/com.facebook.react:react-native/view#
http://repo1.maven.org/maven2/com/facebook/react/react-native/0.18.0/

I understand that we can do something like the workaround of pinning libraries to a specific version, but I didn't get why I can build react-native from 
`compile 'com.facebook.react:react-native:0.18.+'`

**Comment by sgehly** [comment]
Just got the same thing, except mine didn't start failing until this morning. Strange - a `npm -g update` fixed it as you thought it might, but it's certainly a mystery.

**Comment by bitcrumb** [comment]
@kelset I am also not sure how this is related? I am well aware of the issue you refer to. But it seems that previously dependencies like "com.facebook.react:react-native:0.18.+" did resolve until today/yesterday?

**Comment by RafaelOda** [comment]
@bitcrumb from what I've read #19259 it might be related to this issue if after what happened they decided to remove builds that were not actually uploaded by facebook (this is my hypothesis, not something they stated). That's what I understood from reading #13094. I'd really appreciate some input from @kelset or @hramos here though.

**Comment by bitcrumb** [comment]
Something did happen over at jcenter:
https://bintray.com/bintray/jcenter/com.facebook.react%3Areact-native/0.18.0#statistics

Maybe the previous react-native packages were replaced by an 'official' upload? Either way, running `./gradlew --refresh-dependencies` fixed it for me.

**Comment by hramos** [comment]
Yes, this is related to #19259. If you're still unsure why, the explanation that is linked to at the end of that thread can be found here: https://github.com/facebook/react-native/issues/13094#issuecomment-389568018

**Comment by RafaelOda** [comment]
So what happened is that someone else probably uploaded some builds to that domain and now they were removed and official ones are being put there, is that correct @hramos ?

**Comment by kelset** [comment]
Yes, the TLDR is that.

**Comment by bitcrumb** [comment]
Cool thx. Clears that up :)

**Comment by RafaelOda** [comment]
Thanks! 💯
