### ISSUE TITLE
[Packager] DependencyResolver fails to handle ES6 modules import statements with new lines

### ISSUE THREAD

**Issue by shlomiatar** [facebook/react-native#1939]
We found out that while the packager does its module wrapping thing for lines like this:
```js
import theDefault, { named1, named2 } from 'src/mylib';
```
It fails to do the same for multi line imports:
```js
import theDefault, { 
  named1, 
  named2 
} from 'src/mylib';
```
We've tracked done the issue to a [faulty regular expression in replacePatterns.js](https://github.com/facebook/react-native/blob/master/packager/react-packager/src/DependencyResolver/replacePatterns.js#L12)

You can see various import statements with the problematic regular expression [here](http://regexr.com/3bc8m)

We've figure out a better regular expression (you can play around with it [here](http://regexr.com/3bd3s)), and I'll open a pull request soon with the fix + tests.

**Comment by alinz** [comment]
:+1:

**Comment by yelled3** [comment]
:+1:

**Comment by fabiomcosta** [comment]
Does replacing `.+` with `[\s\S]+` fixes it?
```js
exports.IMPORT_RE = /(\bimport\s+?(?:.+\s+?from\s+?)?)(['"])([^'"]+)(\2)/g;
```

becomes:
```js
exports.IMPORT_RE = /(\bimport\s+?(?:[\s\S]+\s+?from\s+?)?)(['"])([^'"]+)(\2)/g;
```

**Comment by fabiomcosta** [comment]
Oh, there is pull request already https://github.com/facebook/react-native/pull/1940, ok.
