### ISSUE TITLE
SafeViewArea not working right

### ISSUE THREAD

**Issue by ducNgbk** [facebook/react-native#19400]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.4.0
  Yarn: 1.5.1
  npm: 6.0.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3.1 Build version 9E501
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: 0.54.3 => 0.54.3

## Steps to Reproduce

I am using SafeViewArea for all screens in my app

> My simple code 

```
import React, { Component } from "react";
import { View, SafeAreaView } from "react-native";
class HomeEmptyCase extends React.Component<{}, {}> {
  render() {
    return (
      <SafeAreaView
        style={{ flex: 1, backgroundColor: "#49B95E" }}
        forceInset={{ top: "always", horizontal: "never" }}
      >
        <View style={{ flex: 1, backgroundColor: "red" }} />
      </SafeAreaView>
    );
  }
}
```
## Expected Behavior

SafeAreaView works fine, the red area not cover status bar
## Actual Behavior

> Everything works fine on iPhone 6s, 6s plus, but it doesn't work for iPhone 5

Captured screen on iPhone 6s
![img_4d62027eea40-1](https://user-images.githubusercontent.com/30441868/40401961-5c4bc3ce-5e73-11e8-8169-a9253cf9ca58.jpeg)

Captured screen on iPhone 5
![img_0850](https://user-images.githubusercontent.com/30441868/40402024-a53b8222-5e73-11e8-8811-31ca6e4be7b8.PNG)

> import { SafeAreaView } from "react-navigation"  **DID THE TRICK**

When I use SafeAreaView from react-navigation, problem solved

I've test on iOS 11 for iPhone 6s, 6s plus. iOS 10 for iPhone 5
Looking for your help

**Comment by ducNgbk** [comment]
Thank you, I did fill out based on your templete

**Comment by timwangdev** [comment]
It's a known issue and there is a PR at #18534 .
