### ISSUE TITLE
signed apk crashes immediately

### ISSUE THREAD

**Issue by ketankulkarni** [facebook/react-native#19404]
I have created signed apk it gets created without any error also installed without error but when i open, it crashes...
android studio -3.0.1
java - 1.8.0_60    

package.json
```{
  "name": "forapk",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.3.1",
    "react-native": "0.55.4"
  },
  "devDependencies": {
    "babel-jest": "22.4.4",
    "babel-preset-react-native": "4.0.0",
    "jest": "22.4.4",
    "react-test-renderer": "16.3.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
``` 

build.gradle 
```

apply plugin: "com.android.application"

import com.android.build.OutputFile
project.ext.react = [
    entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"

def enableSeparateBuildPerCPUArchitecture = false

def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion 26
    defaultConfig {
        applicationId "com.forapk"
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a": 1, "x86": 2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
    buildToolsVersion '26.0.2'
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:26.0.1'
    compile 'com.facebook.react:react-native:+'
    // From node_modules
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

```

**Comment by ketankulkarni** [comment]
step -1 Create Key-Store value from Build -> generate Signed APK...
step- 2 place that keystore.jks file under android/app directory
step -3 Edit the file ~/.gradle/gradle.properties or android/gradle.properties and add the following (replace 
            ***** with the correct keystore password, alias and key password)

              MYAPP_RELEASE_STORE_FILE= keystore.jks
              MYAPP_RELEASE_KEY_ALIAS=myKeyAlias
              MYAPP_RELEASE_STORE_PASSWORD=123456
              MYAPP_RELEASE_KEY_PASSWORD=123456
step-4 Edit the file android/app/build.gradle in your project folder and add the signing config,
```
----
android {
    ---
    defaultConfig { ... }
    signingConfigs {
        release {
            if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
                storeFile file(MYAPP_RELEASE_STORE_FILE)
                storePassword MYAPP_RELEASE_STORE_PASSWORD
                keyAlias MYAPP_RELEASE_KEY_ALIAS
                keyPassword MYAPP_RELEASE_KEY_PASSWORD
            }
        }
    }
    buildTypes {
        release {
            -----
            signingConfig signingConfigs.release
        }
    }
}
---
```

step -5 goto terminal  1) cd android 2) ./gradlew assembleRelease

**Comment by Saksham96** [comment]
hi, I am also facing the same issue. Does anybody has a solution?

**Comment by Anujmoglix** [comment]
Same issue for me , i did everything same as mentioned but app is crashing on launch ,

**Comment by mahmoudafer** [comment]
+1

**Comment by ketankulkarni** [comment]
i am facing this issue when i generate apk with meteor as backend but when i generate apk without meteor and removing all traces of meteor from react native it worked

**Comment by Anujmoglix** [comment]
I did this after some unexpected flow.  I created unsigned apk from react and then convert it to signed apk from my old ionic project ,use that keystore and all thing then it worked , Such an unexpected flow ,

**Comment by kozilla** [comment]
Same, anyone found a working solution ?

**Comment by kozilla** [comment]
Answering my own question. For me It turned out that I had to high gradle version.
Once i reverted/dwongraded to :   

buld.gradle:

       from    classpath 'com.android.tools.build:gradle:3.2.0'
        to        classpath 'com.android.tools.build:gradle:3.1.4'

gradle-wrapper.properties

    from distributionUrl=https\://services.gradle.org/distributions/gradle-4.6-all.zip
    to     distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip

all works for me again.
Hope it helps.

**Comment by Anujmoglix** [comment]
will try this

**Comment by e55o** [comment]
Same issue for me, i am trying on a huawei device.
When in debugging mode, the app works fine.
I generated the release apk.
First i tried without signing it, it failed at installing the app and output "App Not Installed" 
Using jdk `keytool`, i followed the [docs](https://facebook.github.io/react-native/docs/signed-apk-android.html) step by step, generated the signed version and installed it.
it was installed this time, but when opening, it shows blank page for 1 second and then closes without crashing. 
Weird

**Comment by henrikland** [comment]
Same issue here, release build of my app crashes on start after upgrading to `com.android.tools.build:gradle:3.2.0` and gradle 4.6. Debug build works fine.

**Comment by Anujmoglix** [comment]
Following link worked for me https://github.com/adamivancza/react-navigation/commit/db8be7cc0b4ac738242ce82bcc2d1f3254a028c0  . Try this.
