### ISSUE TITLE
Problem with react-native-push-notification in android

### ISSUE THREAD

**Issue by nguyenvulong031095** [facebook/react-native#19405]
Hi guys, I'm trying to use react-native-push-notification through 
https://github.com/…/a359e5c00954aa324136eaa98083…/README.md . 
Unfortunately, I'm getting this problem "(Duplicate zip entry [classes.jar:com/facebook/react/module/annotations/ReactModuleList.class]))" when I'm trying use react-native-push-notification in android
Need some help. Thanks for supporting 
<img width="1440" alt="screen shot 2018-05-23 at 2 38 04 pm" src="https://user-images.githubusercontent.com/19987627/40411438-a97bf2f0-5e9a-11e8-979f-742499e03096.png">

**Comment by kelset** [comment]
You should open an issue in that library repo
