### ISSUE TITLE
java.lang.Double.doubleValue()' on a null object reference

### ISSUE THREAD

**Issue by tapz** [facebook/react-native#19413]
Received this to Crashlytics. RN does not provide any information, which would help to find the cause of this (unless it is actually a bug in RN).

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference
       at com.facebook.react.bridge.ReadableNativeArray.getDouble(ReadableNativeArray.java:114)
       at com.facebook.react.bridge.JavaMethodWrapper$4.extractArgument(JavaMethodWrapper.java:64)
       at com.facebook.react.bridge.JavaMethodWrapper$4.extractArgument(JavaMethodWrapper.java:60)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:359)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
       at android.os.Looper.loop(Looper.java:164)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
       at java.lang.Thread.run(Thread.java:764)
```

**Comment by tasneembohra** [comment]
I am also facing this issue in production.

**Comment by tapz** [comment]
This is a React Native issue. It has something to do with the bridge, state changes and updating the UI. I changed the order in which I set the state an call native methods and the error does not occur anymore.

**Comment by iorikingdom** [comment]
+1

**Comment by jferas** [comment]
+1

**Comment by pilot4u** [comment]
+1

**Comment by developersoul** [comment]
+1

**Comment by sporteman** [comment]
+1

**Comment by C0dekid** [comment]
+1

**Comment by witalobenicio** [comment]
+1

**Comment by taufiqrohman** [comment]
+1

**Comment by steven-haddix** [comment]
+1

**Comment by seanmorton** [comment]
+1. @tapz, do clarify are you referring to redux state? Could you supply more specifics on your fix please?

**Comment by tapz** [comment]
@seanmorton Obsiously, I'm referring to React Component (local) state, which makes the component to update.

**Comment by seanmorton** [comment]
Thanks for the clarification!

**Comment by JiaYuZ** [comment]
I "fixed" the problem by making sure status bar color in ReactNative same as the status bar color in Android theme

**Comment by nes123** [comment]
+1

**Comment by DiegoOpenheimer** [comment]
This error happened to me when I used a bridge in the wrong way, causing the error, for example, to use the toastAndroid.show ('....') without passing the time

**Comment by nes123** [comment]
guys how are you debugging such crashes? is there a way to catch native errors?

**Comment by apotox** [comment]
the second param must be an Double or Int , not a string 
try `ToastExample.show('Awesome',300);`
it worked for me

**Comment by hoseineghbal** [comment]
i solved it in react native with redux and problem was related to style of store new state for redux ...


for this bug you must first get instance of state in redux reducer like this ::

const newState = state;
  
and then change and return it::

newState.check = true;

return newState;


bug did fix for me after 24 hours trying ...

**Comment by mthrsj** [comment]
> This error happened to me when I used a bridge in the wrong way, causing the error, for example, to use the toastAndroid.show ('....') without passing the time

That was my mistake, I forgot the duration for the `ToastAndroid.show()`

**Comment by ithustle** [comment]
I'm facing this error on RN 0.58.2. Any help?

**Comment by abendi** [comment]
> 
> 
> I'm facing this error on android, after upgrade to RN 0.58.2 ... Any help?

For me the issue was using `<StatusBar {...props} />` in `render` method. It seems that now you need to provide `backgroundColor` and `hidden` props as well or it will crash.
But using imperative API it works as previously:
```
componentDidMount() {
  StatusBar.setBarStyle(...);
}
```

**Comment by OctoD** [comment]
Also facing a similar one to this using Axios, did somebody fixed or found a work around for this?

**Comment by gustavo-franco-iw** [comment]
+1

**Comment by aweffr** [comment]
My Envirment: 
React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz
      Memory: 5.13 GB / 15.94 GB
    Binaries:
      Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.1.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338

I have got this problem too! I have tried to rollback to the production branch and still got this problem!

After 2h debug, I find that the first time it occurs, I ran `react-native run-android` and the logs says that gradle is downloading some pom file and blocked!(Network issue?)

So I delete all the cache files/dirs in home/.gradle/cache, then this bug resolved!
