### ISSUE TITLE
[ScrollView] Cannot find view with tag #XXX

### ISSUE THREAD

**Issue by ilansas** [facebook/react-native#1941]
Hello, 

Sometimes when I'm scrolling or doing some swipes I'm getting these kind of errors (crashing the app). The error can be thrown multiple time for a same scroll with a different tag for each of them :  

    2015-07-10 16:46:59.859 [error][tid:main][RCTScrollViewManager.m:105] Cannot find view with tag #208
    2015-07-10 16:46:59.866 [error][tid:main][RCTScrollViewManager.m:105] Cannot find view with tag #202
    2015-07-10 16:46:59.872 [error][tid:main][RCTScrollViewManager.m:105] Cannot find view with tag #175
    2015-07-10 16:46:59.879 [error][tid:main][RCTScrollViewManager.m:105] Cannot find view with tag #175
    2015-07-10 16:46:59.885 [error][tid:main][RCTScrollViewManager.m:105] Cannot find view with tag #175
    2015-07-10 16:46:59.892 [error][tid:main][RCTScrollViewManager.m:105] Cannot find view with tag #222
    2015-07-10 16:46:59.898 [error][tid:main][RCTScrollViewManager.m:105] Cannot find view with tag #215
    2015-07-10 16:46:59.905 [error][tid:main][RCTScrollViewManager.m:105] Cannot find view with tag #228
    2015-07-10 16:46:59.911 [error][tid:main][RCTScrollViewManager.m:105] Cannot find view with tag #195
    2015-07-10 16:46:59.918 [error][tid:main][RCTScrollViewManager.m:105] Cannot find view with tag #188
    2015-07-10 16:46:59.925 [error][tid:main][RCTScrollViewManager.m:105] Cannot find view with tag #182
    2015-07-10 16:46:59.931 [error][tid:main][RCTScrollViewManager.m:105] Cannot find view with tag #168
    2015-07-10 16:46:59.937 [error][tid:main][RCTScrollViewManager.m:105] Cannot find view with tag #162

![Screen error](http://image.noelshack.com/fichiers/2015/28/1436540774-img-0035.png)

This doesn't seem to happen in debug mode (it never happened until now).

**Comment by magicismight** [comment]
+1
It happened sometimes when I inspect element.

**Comment by MossP** [comment]
+1 Strangely I get the opposite trigger. I cannot get it to happen the JS in bundled into the app but it frequently happens when the app is running via the packager but I'm yet to see it unless I have https://github.com/Shuangzuan/RCTRefreshControl active for that particular `<ListView/>`

**Comment by aljs** [comment]
Are there any solutions?
Have this error (using https://github.com/Shuangzuan/RCTRefreshControl), while running on device as well.

**Comment by ilansas** [comment]
Updating React-Native with master doesn't seem to give me the error anymore...

**Comment by MossP** [comment]
Which version of RN are you running @ilansas?

**Comment by MossP** [comment]
Master looks like it's out of date. It currently says v0.6.0, @ilansas.

**Comment by ilansas** [comment]
Yep v0.6.0, I was working on the previous version of master, the error was thrown there. So I updated it.

**Comment by MossP** [comment]
My point is that the master that you have downloaded is out of date. v0.7.1 is current release and v0.8.0 will be out soon.

The bug began in v0.7.0.

You have, in fact, downgraded to fix the problem.

**Comment by sahrens** [comment]
Note that we haven't been very good about updating the version numbers in the source as we make new releases...

**Comment by ilansas** [comment]
@MossP Sorry, you might be right, the actual master is on v0.8, I didn't downgraded anything I just ran `npm i` which is based on master, so I was probably under 0.7.

**Comment by MossP** [comment]
@ilansas Yeah, master got updated just after we spoke.

**Comment by ilansas** [comment]
Well to be clear I'm under v0.8.0 and I'm getting the error

**Comment by MossP** [comment]
Yea, me too :) It all got a bit confusing then, sorry.

**Comment by brentvatne** [comment]
I've seen this before as well, definitely worth looking into :+1:

**Comment by cssoul** [comment]
+1 ，0.8.0.-rc ，when I onpress some element of scrollView, it crash.

**Comment by brentvatne** [comment]
@cssoul - I'm not having that problem, do you have a reproducible example project?

**Comment by ilansas** [comment]
Ok, I might have some news here. This seems to happen only when you enable Live Reload, here are the cases I observed : 
- Live Reload disabled, clic on Enable Live Reload --> the error doesn't seem to be thrown in the future
- Live Reload disabled, clic on Enable Live Reload, Reload (cmd + R) --> the error is thrown in the future
- Live Reload enabled, clic on Disable Live Reload --> the error is thrown in the future
- Live Reload enabled, clic on Disable Live Reload, Reload (cmd + R) --> the error doesn't seem to be thrown in the future

**Comment by NishanthShankar** [comment]
@ilansas I am not sure if that is true. I get the error on the iPhone too. 
My assumption is that this error occurs if you try to perform an action before the scrollview renders its rows have been rendered.

Will try to create a reproducible example project

**Comment by MossP** [comment]
@NishanthShanker, I don't think @ilansas was suggesting that it only happens on the simulator.

**Comment by ilansas** [comment]
Yep as said @MossP I wasn't suggesting that, I assume you based your thought on the (cmd+R), I just wanted to be precise about the "Reload".

**Comment by NishanthShankar** [comment]
@ilansas Sorry my bad.

**Comment by josebalius** [comment]
Anything else on this guys? I have been getting these errors more frequently as well.

**Comment by NishanthShankar** [comment]
I was able to bypass this error by adding a timeout before the interaction is executed. Though this reduces the responsiveness of the app by a bit, it doesn't throw the error anymore

**Comment by josebalius** [comment]
@NishanthShankar so did i, however at times i can still get it to throw the error. It's not the best solution (timeout) :/

**Comment by danscan** [comment]
Can confirm I'm encountering this when I press on `TouchableHighlight` or `TouchableOpacity` within a `ScrollView`/`ListView`, but I'm not encountering it with `TouchableWithoutFeedback` in the same place.

**Comment by admmasters** [comment]
Just seen this for the first time when jumping between tabs and I think I was touching the ListView while it happened.

**Comment by hmm29** [comment]
I was encountering this exact error when jumping between tabs / rapidly navigating between routes while testing my app

I fixed it by decreasing the intialListSize prop value from 10 to 3. I think the error occurs because I was navigating away so quickly before the initial render had time to fully complete.

```javascript
                <ListView
                  dataSource={this.state.dataSource}
                  renderRow={this._renderRow}
                  renderHeader={this._renderHeader}
                  initialListSize={3}
                  automaticallyAdjustContentInsets={false}
                  />
```
Perhaps try explicitly setting this prop's value to something small?

**Comment by ide** [comment]
Looking through ListView.js, I imagine the cause of this is several callbacks that don't check if the component is still mounted :/

**Comment by mattds** [comment]
I'm also getting this error, it's tricky to reproduce, may need to be reloaded a few times before it throws this error but here's an example of this: https://rnplay.org/apps/0OLARw

**Comment by soliury** [comment]
I'm also get this error, I don't know how it happen.

**Comment by Dictory** [comment]
Ok, i think i found answer why i had that crash:
I use ListView with `onEndReached`, like many people
``` javascript
<ListView
  dataSource={this.state.dataSource}
  onEndReached={handleLoadMore}
  onEndReachedThreshold={100}
  renderRow={this.renderRow}
/>
```
and simple loader after list:
``` javascript
{isFetchingMore && this.renderLoading()}
```
That work in "Container" with connect to Redux and other functions, but dosnt work in "Component". **But (!)** if wrap loader in `<View>`

``` javascript
<View>{isFetchingMore && this.renderLoading()}</View>
```
That problem gone!

I think react-native need know about elements after `<ListView>`.
I hove that can help someone =)
