### ISSUE TITLE
Not possible to make a drawing app (single-touch View in multi-touch ScrollView)

### ISSUE THREAD

**Issue by darknoon** [facebook/react-native#19411]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 10.1.0
  Yarn: 1.6.0
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3.1 Build version 9E501
  Android Studio: Not Found

Packages: (wanted => installed)
  react: ^16.3.2 => 16.3.2
  react-native: 0.55.0 => 0.55.2

## Steps to Reproduce
See this code:
https://snack.expo.io/@darknoon/paint-in-scroll-a
- Create a view that is supposed to become the Responder when a single-finger gesture occurs, and not otherwise
- Wrap in a scrollview with zooming (ie, two finger gesture)

I also tried monkey-patching the ScrollView js side, but didn't get anywhere. It seems that this is an issue with the interface to the native gesture system.

Here is an example of how you can create this UI easily with native code:
[PaintGestures.zip](https://github.com/facebook/react-native/files/2031947/PaintGestures.zip)

Ideally, I wouldn't need to eject to do this

## Expected Behavior
- Two finger gestures control scrollview
- One finger gesture moves white square

## Actual Behavior
- Single finger gesture works sometimes, then gets stuck
- Two-finger gesture works to pan scrollview

**Comment by kelset** [comment]
Closing as state. Please open a new issue if issue still occur.
