### ISSUE TITLE
Bridge extractArgument: doubleValue() on a null object reference

### ISSUE THREAD

**Issue by tapz** [facebook/react-native#19423]
- [X] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [X] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [X] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

I got this to Crashlytics from one of the users of my app. Would be nice to get more information and the actual cause of the error.

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference
       at com.facebook.react.bridge.ReadableNativeArray.getDouble(ReadableNativeArray.java:114)
       at com.facebook.react.bridge.JavaMethodWrapper$4.extractArgument(JavaMethodWrapper.java:64)
       at com.facebook.react.bridge.JavaMethodWrapper$4.extractArgument(JavaMethodWrapper.java:60)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:359)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
       at android.os.Looper.loop(Looper.java:164)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
       at java.lang.Thread.run(Thread.java:764)
```

## Environment

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.11.1
  Yarn: 1.6.0
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3.1 Build version 9E501
  Android Studio: 3.1 AI-173.4697961

Packages: (wanted => installed)
  react: 16.3.2 => 16.3.2
  react-native: 0.55.4 => 0.55.4

## Steps to Reproduce
No idea.

## Expected Behavior
No crash

## Actual Behavior
Crash

**Comment by coderdave** [comment]
This IS a bug. Why was it closed?

**Comment by tapz** [comment]
This is a React Native issue. It has something to do with the bridge, state changes and updating the UI. I changed the order in which I set the state an call native methods and the error does not occur anymore.

**Comment by pilot4u** [comment]
I'm having the same issue while executing this method:
https://reactnavigation.org/docs/en/navigating-without-navigation-prop.html
and navigating within componentWillReceiveProps

**Comment by bondansebastian** [comment]
Hi @tapz , i'm having the same issues as everyone here
Can you elaborate more what do you mean by 
> I changed the order in which I set the state an call native methods

**Comment by tapz** [comment]
Hi @bondansebastian , I modified my code to change the component state in one place instead of setting different fields separately. Also moved the calls to native bridge to different places. Can't really tell any systematic way. Just doing things differently seems to have bypassed the bug.

**Comment by mjugger** [comment]
So far this error only seems to happen when I use hot reload

**Comment by jnrepo** [comment]
I'm also seeing this in release mode w/ Android. Using react-native 0.55.3.

**Comment by gluons** [comment]
@tapz Can you reopen this issue?

**Comment by gluons** [comment]
I found the solution for my problem. My fault.

I forget to give a second parameter (`duration`) to [`ToastAndroid.show`](https://facebook.github.io/react-native/docs/0.56/toastandroid).

**Comment by seanmorton** [comment]
For me, this was also an issue with my own codebase. No need to reopen.

**Comment by ntomallen** [comment]
I'm trying to use `StatusBar.setBackgroundColor(color, true)` and getting this error. Only reason I'm using imperative API is because the status bar component isn't working for one specific component for some reason.

**Comment by tuononh** [comment]
@ntomallen Have you solve it? I have the same problem. Others `StatusBar` methods work fine.

**Comment by ntomallen** [comment]
I stopped trying to use that method. I think it was set incorrectly on the android side of things; maybe in the manifest

**Comment by im-aditya** [comment]
Having the same issue.
