### ISSUE TITLE
Android: App crashes when running without the remote debugger on

### ISSUE THREAD

**Issue by thiagoferolla** [facebook/react-native#19436]
- [X] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [X] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [X] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment

Environment:
  OS: Linux 4.15
  Node: 8.11.2
  Yarn: 1.7.0
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

## Steps to Reproduce

The code samples related to the Android configuration are in this gist: https://gist.github.com/thiagoferolla/14f617b337b4c476d05924f6d8d67319

These are the logs from `react-native log-android`:

> 05-22 23:09:58.703  7831  7921 D ReactNative: Initializing React Xplat Bridge.
> 05-22 23:09:58.704  7831  7921 D ReactNative: Initializing React Xplat Bridge before initializeBridge
> 05-22 23:09:58.718  7831  7921 D ReactNative: Initializing React Xplat Bridge after initializeBridge
> 05-22 23:09:58.718  7831  7921 D ReactNative: CatalystInstanceImpl.runJSBundle()
> 05-22 23:09:58.718  7831  7923 D ReactNative: ReactInstanceManager.setupReactContext()
> 05-22 23:09:58.718  7831  7923 D ReactNative: CatalystInstanceImpl.initialize()
> 05-22 23:09:58.719  7831  7923 D ReactNative: ReactInstanceManager.attachRootViewToInstance()
> 05-22 23:09:59.177  7831  7831 D ReactNative: CatalystInstanceImpl.destroy() start
> 05-22 23:09:59.243  7831  7831 D ReactNative: CatalystInstanceImpl.destroy() start

## Expected Behavior

The app should build and load the bundle successfully

## Actual Behavior

When trying to run the app `react-native run-android`, the build proccess ends successfully but crashes with the following error:
![lpneo](https://user-images.githubusercontent.com/24864429/40506190-161f58fc-5f6d-11e8-9c0d-9bd53790bbd4.jpg)

Apart from that, if I turn on the remote debugger that uses Chrome or run in an iOS device, the app loads without errors.

**Comment by chuntley** [comment]
Check for any exponential operators (**) in your code, looks like this is related to: https://github.com/facebook/react-native/issues/11371

Use Math.pow instead.

**Comment by thiagoferolla** [comment]
That's was actually the problem. Switching to Math.pow solved. Thanks
