### ISSUE TITLE
TextInput Max length does not work with special chars

### ISSUE THREAD

**Issue by assafb81** [facebook/react-native#19433]
-  I have reviewed the [documentation](https://facebook.github.io/react-native)
- I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [ ] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

I want to allow only  25 characters in my text input

## Environment
OS: macOS High Sierra 10.13.4
Node: 8.6.0
Yarn: 1.3.2
Xcode: Xcode 9.3.1 build version 9E501
react: 16.3.1
react-native: 0.55.4

iOS device: iPhone 6s
OS: 11.3.1

## Steps to Reproduce
1. Open application with Text input
2. type '-' in the text input

code:

```
<TextInput
    userName={userName}
    underlineColorAndroid="transparent"
    maxLength={25}
    autoCorrect={false}
/>
```

## Expected Behavior
User can't type more than maxLength, in my case 25.

## Actual Behavior
User Can type as many as he wants.

**Comment by assafb81** [comment]
## Environment (UPDATED)
OS: macOS High Sierra 10.13.4
Node: 8.6.0
Yarn: 1.3.2
Xcode: Xcode 9.3.1 build version 9E501
react: 16.3.1
react-native: 0.52

iOS device: iPhone 6s
OS: 11.3.1

**Comment by jamessawyer** [comment]
same issue.

 Iphone6 runs iOS 9.3.4 device.
 OS: macOS High Sierra 10.13.4
  Node: 8.11.1
  Yarn: 1.6.0
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  react: "16.3.0-alpha.1",
  react-native: "0.54.0",

However,works fine on my iphone6splus runs iOS 11.3.1

**Comment by assafb81** [comment]
I can't apply labels to it  :(, can you apply for me

**Comment by hramos** [comment]
This should be fixed as of https://github.com/facebook/react-native/commit/892212b (0.56).
