### ISSUE TITLE
[android] fetch with method:HEAD always fails

### ISSUE THREAD

**Issue by treemore** [facebook/react-native#19435]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x ] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

only happen in android phone
when i use a android phone. and the android version is android 7.0
iphone is right.

```js
 url = "http://www.google.com"
 fetch(url, {
// when set   method: "GET",   is ok
            method: "HEAD",
        }).catch(e=>console.error(e))
```
always throw the exception "Network request failed"
## Environment

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.9.1
  Yarn: 0.27.5
  npm: 6.0.1
  Watchman: 4.7.0
  Xcode: Xcode 9.3.1 Build version 9E501
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: ^0.55.3 => 0.55.3

## Steps to Reproduce

just exec the code  .
```js
 url = "http://www.google.com"
 fetch(url, {
            method: "HEAD",
        }).catch(e=>console.error(e))
```
## Expected Behavior

not throw catch
## Actual Behavior

always throw the exception and said  Network request failed

**Comment by hramos** [comment]
Actually, the fix for #18223 was for iOS. There's still an open question as to whether this is an issue on Android or not. 

Duplicate of #18440
