### ISSUE TITLE
Placeholder and textAlign dynamic changes

### ISSUE THREAD

**Issue by suwu150** [facebook/react-native#19442]
- [x] I have reviewed the [textinput.html](https://facebook.github.io/react-native/docs/textinput.html)
- [x] I am using the [ React-native version 0.51.0]
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues/12160)

## Environment
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.3.0
  Yarn: Not Found
  npm: 5.3.0
  Watchman: Not Found
  Xcode: Xcode 9.3.1 Build version 9E501
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: ^16.0.0 => 16.3.2
  react-native: ^0.51.0 => 0.51.1

## Expected Behavior

I have a dynamic input box, when my input box has no content, that is, when there is only a placeholder, I need to place the placeholder on the left, but when I click on the focus to enter, the input Still on the left, but when the input box has input content and loses focus, I need to display the text content on the right side. How do I do this?
## Actual Behavior

solution
1. Provide a placeholderTextAlign interface to control the position
2. Use value to control, when the value is null, control the textAlign in the textInput: 'left', when the value is not empty when the value exists, control the textAlign: 'right'

problem
The first solution I think can be a good solution, but I don't know if react-native will affect other places. If you can help implement the interface, you will be very grateful.
The second solution will encounter problems, when a lot of irregular data is placed in the input box to display a lot of data, the value of the value is not good to judge

I hope to provide an interface for everyone to use

**Comment by jsina** [comment]
cause you wanna change dynamically you have to use unique `key` props for each component have created.
