### ISSUE TITLE
react-native-git-upgrade fails trying to upgrade from 0.47.1 to 0.55.4

### ISSUE THREAD

**Issue by JoseVf** [facebook/react-native#19449]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [ ] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

When trying to upgrade to newer React Native version (from `0.47.1` to `0.55.4`) with `react-native-git-upgrade` command fails with following errors:
![captura de pantalla 2018-05-25 a la s 8 45 05 a m](https://user-images.githubusercontent.com/22102736/40547802-75496a3a-5ff8-11e8-9bc2-f9087680ea06.png)
![captura de pantalla 2018-05-25 a la s 8 30 56 a m](https://user-images.githubusercontent.com/22102736/40546984-4dba37c6-5ff6-11e8-99f7-09e03812a36d.png)
![captura de pantalla 2018-05-25 a la s 8 49 37 a m](https://user-images.githubusercontent.com/22102736/40547838-9766adee-5ff8-11e8-8a60-420eb3aea171.png)

## Environment

(Not sure if I'm doing something wrong but when I do `react-native info`...
![captura de pantalla 2018-05-25 a la s 8 37 42 a m](https://user-images.githubusercontent.com/22102736/40547208-e7f5e222-5ff6-11e8-8dd8-96c9af73690d.png))

Current RN version: `0.47.1`
React version: `16.0.0-alpha.12`
OS: `macOS High Sierra 10.13.4`
npm: `5.6.0`
xCode: `Version 9.3.1 (9E501)`
Watchman: `4.9.0`
## Steps to Reproduce

Just try to `$ react-native-git-upgrade` on a project with version `0.47.1`
## Expected Behavior

Upgrade successfully to version 0.55.4
## Actual Behavior

Fails with above errors.

**Comment by JoseVf** [comment]
As I said, when I run `react-native info` throws an error...

**Comment by hramos** [comment]
That's because you're on a significantly old version of React Native that did not yet have the `info` command. I'm not sure a GitHub issue is the best place to debug issues upgrading a particular project, but I'll let the authors of `react-native-git-upgrade` chime in if they're around.

**Comment by hramos** [comment]
Delete your `node_modules` folder and try upgrading again.
