### ISSUE TITLE
[TextInput] How do you implement maxLength for TextInput?

### ISSUE THREAD

**Issue by leonlxli** [facebook/react-native#1945]
Is there a way for you to limit the number of characters that you can enter into a textInput similar to how maxLength works?

**Comment by brentkirkland** [comment]
What if you checked onTextChange if the text was <= the desired length of characters?

**Comment by leonlxli** [comment]
onChangeText still makes the change. I want to make it so that if the user is not allowed to enter in more than the maxLength. When I used onChangeText, it still changes the input

**Comment by brentvatne** [comment]
We would need to handle this on the native side, eg: http://stackoverflow.com/questions/2523501/set-uitextfield-maximum-length

Overall, TextInput needs a lot of work. I know @sahrens is working on some improvements now but any community help on this one is very much appreciated!

What we would need to do:
- Look at the maxLength spec for web and ensure we understand all of its behaviours
  - This should be pretty easy - adding keystrokes to the text field contents once the length has reached. Something to consider though - do we provide a hook for the JS side to respond to press events after we have exceeded this? This line of thinking is necessary. We'll need to consider common use cases for maxlength and ensure we can handle those.
- Add a prop to TextInput with the same, make the backing logic on the ObjC side
- Add an example to UIExplorer

**Comment by dsibiski** [comment]
I implemented `shouldChangeCharactersInRange` in this PR: https://github.com/facebook/react-native/pull/2082 for issue https://github.com/facebook/react-native/issues/1882

These two definitely overlap. Would be nice to see a convergence of ideas here.

**Comment by sahrens** [comment]
This and several fixes landed internally and should sync out this week.

**Comment by brentvatne** [comment]
@sahrens - awesome, super excited! thanks!

**Comment by browniefed** [comment]
@brentvatne this landed into master so this can probably be closed?

**Comment by monyxie** [comment]
The current implementation doesn't seem to work with Chinese keyboard.
![textinput maxlength issue](https://cloud.githubusercontent.com/assets/703164/9030405/af3fbde0-39d4-11e5-923c-2aaebd0de4a1.gif)

**Comment by ide** [comment]
Closing this since maxLength has been implemented. Will open a new issue for the problem with Chinese characters.
