### ISSUE TITLE
Bundling Failed: Unable to resolve module '...

### ISSUE THREAD

**Issue by pazcur** [facebook/react-native#19460]
## Environment

Environment:

  OS: macOS Sierra 10.12.6
  Node: 10.1.0
  Yarn: 1.6.0
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: Not Found

Packages: (wanted => installed)
  react: ^16.0.0-beta.5 => 16.0.0-beta.5
  react-native: 0.49.3 => 0.49.3

## Steps to Reproduce

after running in the root directory 
`npm start -- --reset-cache`

I invariably get the following error:
![screen shot 2018-05-26 at 1 36 03 pm](https://user-images.githubusercontent.com/25714627/40578917-e417485e-60ea-11e8-86b1-a84584375790.png)

## Expected Behavior

Should be able to see a splash page with an image (../../app/image/splash.jpg)
![splash](https://user-images.githubusercontent.com/25714627/40578925-03919efa-60eb-11e8-924c-e01de400217b.jpg)

## Actual Behavior

on the ios simulator
![screen shot 2018-05-26 at 1 35 30 pm](https://user-images.githubusercontent.com/25714627/40578921-f40b4be8-60ea-11e8-9d45-12aac0af3d9f.png)

**Comment by ioss** [comment]
If your image is in app/images (as written above the attached image), your path is wrong.
You need to require '../images/splash.jpg' (or – going out of 'app' back into 'app' – as you have written above the image '../../app/image/splash.jpg instead of ../../images/splash.jpg)
