### ISSUE TITLE
(Android) TextInput lag when there are a lot of messages

### ISSUE THREAD

**Issue by aspidvip** [facebook/react-native#19464]
---
name: 🐛 Bug Report
about: Something is not working as expected.

---
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 6.11.1
  Yarn: 0.27.5
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.1 Build version 9B55
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.3 => 0.55.3

"react": "16.3.1",
"react-native": "0.55.3"

## Steps to Reproduce

When user enter large text (50+ characters) and remove it then repeat process again 2 or more times. 

![2018-05-27 14_06_19](https://user-images.githubusercontent.com/22605655/40582367-33f29d16-61b7-11e8-80ff-1967e8e0ba5c.gif)

**Comment by aspidvip** [comment]
```
<TextInput 
onChangeText={(text) => this.setState({text})}
value={
this.setState({text: this.state.text})
}
/>
```

**Comment by gnprice** [comment]
For cross-reference: it looks like this is a report of #19126 .
