### ISSUE TITLE
WebView in ScrollView calling refreshControl when swiping up React Native Android all the time

### ISSUE THREAD

**Issue by GAzevedo** [facebook/react-native#19476]
- [X] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [X] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [X] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

I have a WebView inside a ScrollView on a React Native app. The ScrollView has the refreshControl prop so I can refresh the WebView when I reach the top of the app.

Here's the problem: I scroll the WebView without a problem, but whenever I swipe up to go to the top of the page, doesn't matter if I'm on the end, the middle or the beginning of the page, the refreshControl is always triggered.

The RefreshControl is triggered when the scrollY: 0 and the scrollY is always 0, because what is being scrolled isn't the ScrollView but the WebView, so the ScrollView is always at scrollY: 0.

I already tried the scrollEnabled prop on both WebView and ScrollView but none worked.

Here's how the code looks right now:

    <View style={{flex: 1}}>
    	<ScrollView
    	  contentContainerStyle={{flex: 1}}
    	  refreshControl={
    	    <RefreshControl
    	      refreshing={this.state.refreshing}
    	      onRefresh={this._onRefresh.bind(this)}
    	    />
    	  }
    	>
    	  <WebView
    	    ref="webview"
    	    source={{uri: initialUrl}}
    	  />
    	</ScrollView>
    </View>

I've removed all the props to try to start over, but I always get the same problem. On iOS it's working alright, without this issue.

Yes, I do have other stuff inside this mother View.

## Environment
  OS: macOS High Sierra 10.13.4
  Node: 8.11.1
  Yarn: 1.6.0
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.3 => 0.55.3

## Steps to Reproduce
    <View style={{flex: 1}}>
    	<ScrollView
    	  contentContainerStyle={{flex: 1}}
    	  refreshControl={
    	    <RefreshControl
    	      refreshing={this.state.refreshing}
    	      onRefresh={this._onRefresh.bind(this)}
    	    />
    	  }
    	>
    	  <WebView
    	    ref="webview"
    	    source={{uri: initialUrl}}
    	  />
    	</ScrollView>
    </View>

**Comment by GAzevedo** [comment]
Well...

**Comment by codedogfish** [comment]
+1

**Comment by welladam** [comment]
+1

**Comment by welladam** [comment]
Hey @GAzevedo, I had the same problem, but using the FlatList. Try to remove the `contentContainerStyle`, more specifically the `flex: 1`.
In this way, worked for me!

**Comment by d12544** [comment]
same issue. Please update any solution

**Comment by FrederickEngelhardt** [comment]
Same issue.

**Comment by DavidKk** [comment]
Same issue. only in android, swiping up always trigger refreshControl event.

```
// container component
...
<ScrollView style={{ flex: 1 }} refreshControl={this._renderRefreshControl()}>
  // page component
  <ScrollView style={{ flex: 1 }}>...</ScrollView>
</ScrollView>
...
```

**Comment by rifrayugo** [comment]
i also have the same issue, is there any solution atm?

**Comment by rifrayugo** [comment]
@d12544 How about IOS?

**Comment by romreed** [comment]
Still have this issue 
 "react": "16.6.3",
 "react-native": "0.58.4",
OS: macOS High Sierra 10.13.4
xcode 9.4.1

**Comment by romreed** [comment]
Still have this issue on android.
"react-native": "0.57.7",
OS: macOS High Sierra 10.13.4
Node: 8.11.1
Android Studio: 3.1.3

**Comment by romreed** [comment]
@d12544   Thank you. Work for me.
"react": "16.6.3",
"react-native": "0.57.7",

```javascript
onMessage = e => {
        console.log('onMessage', e.nativeEvent.data);
        if (e.nativeEvent.data == 0 && !this.state.enablePTR) {
            this.setState({enablePTR: true});
        } else if (e.nativeEvent.data > 10 && this.state.enablePTR) {
            this.setState({enablePTR: false});
        }
    };
 <ScrollView
                            contentContainerStyle={{flex: 1,}}
                            refreshControl={
                                <RefreshControl
                                    refreshing={this.state.refreshing}
                                    onRefresh={this._onRefresh.bind(this)}
                                    enabled={Platform.OS === "ios" ? true : this.state.enablePTR}
                                />
                            }
                        >
<WebView
                                    source={{
                                        uri: HOME_URL,
                                        "Accept-Language": navigator.language,
                                        "User-Agent": Platform.OS,
                                    }}
                                    javaScriptEnabled={true}
                                    ref={(b) => this._bridge = b}
                                    onMessage={event => this.onMessage(event)}
                                    injectedJavaScript="setTimeout(() => {document.addEventListener('scroll', function (event) {window.ReactNativeWebView.postMessage(JSON.stringify(document.getElementsByClassName('topconteiner')[0].scrollTop));},true);}, 300);true;"
/>
   </ScrollView>
```
