### ISSUE TITLE
componentWillMount will dispatch immeidately my predefined function

### ISSUE THREAD

**Issue by ezekel** [facebook/react-native#19477]
I am just wondering why my _deleteRecord trigger immediately even I did not press the headerRightIcon.? . can someone help me please. I want only to trigger my _deleteRecord when I pressed it.

Thank you in advance.

```
_deleteRecord = (id) => {
   
        this.props.deleteRecord(id);
    };

componentWillMount () {
        this.props.navigation.setParams({ handleRemove: this._deleteRecord(this.props.navigation.state.params.id) })
    }

 static navigationOptions = ({ navigation}) =>{
return{
       headerRight: (
                <IconIonicons
                    color="white"
                    name="md-trash"
                    size={24}
                    onPress={() => params.handleRemove}
                    style={{color: '#ffffff', marginRight: 15}}
                />

            ),
 }

}
``

**Comment by chirag04** [comment]
You are actually calling deleteRecord instead of passing a function that deletes the record. Try to console log the value of handleRemove. It will be null instead of a function.

**Comment by ezekel** [comment]
actually that will delete record to my database. My concern is that when I navigate to that screen it will trigger immediately   because I put it on componentWillMount , if I will not used componentWillMount ,
like this. I will get an error undefind function.
``
 static navigationOptions = ({ navigation}) =>{
return{
       headerRight: (
                <IconIonicons
                    color="white"
                    name="md-trash"
                    size={24}
                    onPress={() => this._deleteRecord(params.id)}
                    style={{color: '#ffffff', marginRight: 15}}
                />

            ),
 }

}
``
