### ISSUE TITLE
[master iOS]Metro Bundler has encountered an internal error, please check your terminal error output for more details

### ISSUE THREAD

**Issue by ShiYongjieGitHub** [facebook/react-native#19478]
This is all the relevant information of the terminal error:
Looking for JS files in
   /Users/shiyongjie/Desktop/Git/Facebook/react-native 

Metro Bundler ready.

Loading dependency graph, done.
error: bundling failed: ReferenceError: SHA-1 for file /Users/shiyongjie/Desktop/Git/Facebook/react-native/node_modules/react/index.js is not computed
    at DependencyGraph.getSha1 (/Users/shiyongjie/Desktop/Git/Facebook/react-native/node_modules/metro/src/node-haste/DependencyGraph.js:224:3541)
    at /Users/shiyongjie/Desktop/Git/Facebook/react-native/node_modules/metro/src/Bundler.js:263:56
    at Generator.next (<anonymous>)
    at step (/Users/shiyongjie/Desktop/Git/Facebook/react-native/node_modules/metro/src/Bundler.js:11:657)
    at /Users/shiyongjie/Desktop/Git/Facebook/react-native/node_modules/metro/src/Bundler.js:11:817
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
 BUNDLE  [ios, dev] RNTester/js/RNTesterApp.ios.js ░░░░░░░░░░░░░░░░ 0.0% (0/2), failed.

And this is all all the relevant information of device red screen showing:
Metro Bundler has encountered an internal error, please check your terminal error output for more details

RCTFatal
__28-[RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
<redacted>
<redacted>
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
main
<redacted> # #

**Comment by ShiYongjieGitHub** [comment]
I run the RNTester project, and encounter this problem.

**Comment by ShiYongjieGitHub** [comment]
This is all the relevant information of the terminal error:
Looking for JS files in
   /Users/shiyongjie/Desktop/Git/Facebook/react-native 

Metro Bundler ready.

Loading dependency graph, done.
error: bundling failed: ReferenceError: SHA-1 for file /Users/shiyongjie/Desktop/Git/Facebook/react-native/node_modules/react/index.js is not computed
    at DependencyGraph.getSha1 (/Users/shiyongjie/Desktop/Git/Facebook/react-native/node_modules/metro/src/node-haste/DependencyGraph.js:224:3541)
    at /Users/shiyongjie/Desktop/Git/Facebook/react-native/node_modules/metro/src/Bundler.js:263:56
    at Generator.next (<anonymous>)
    at step (/Users/shiyongjie/Desktop/Git/Facebook/react-native/node_modules/metro/src/Bundler.js:11:657)
    at /Users/shiyongjie/Desktop/Git/Facebook/react-native/node_modules/metro/src/Bundler.js:11:817
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
 BUNDLE  [ios, dev] RNTester/js/RNTesterApp.ios.js ░░░░░░░░░░░░░░░░ 0.0% (0/2), failed.

And this is all all the relevant information of device red screen showing:
Metro Bundler has encountered an internal error, please check your terminal error output for more details

RCTFatal
__28-[RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
<redacted>
<redacted>
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
main
<redacted>

**Comment by ShiYongjieGitHub** [comment]
@react-native-bot
That's all.

**Comment by handeglc** [comment]
I removed node_modules and run `npm install` then restarted my computer, now it works

**Comment by rrrhys** [comment]
Possible solution; check in rn-cli.config.js that js is included as a sourceExt, e.g.:

module.exports = {
    resolver: {
        sourceExts: ['tsx', 'ts', **_'js'_**]
    },
    transformer: {
        babelTransformerPath: require.resolve("react-native-typescript-transformer")
    }
};
