### ISSUE TITLE
FLATLIST on android:  animation doesn't work as expected

### ISSUE THREAD

**Issue by aharon87** [facebook/react-native#19480]
## Environment
  OS: macOS High Sierra 10.13.4
  Node: 8.9.4
  Yarn: 0.23.2
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.3.1 Build version 9E501
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.3.1 => 16.3.2
  react-native: ^0.55.0 => 0.55.4

## Steps to Reproduce
copy the code

## Expected Behavior
Animation should be as on ios

## Actual Behavior
Animation on android diffrent then on ios  be as on ios

I am trying to make an animation on items that inside flatList.
Each item will appear from right to left.
On IOS It's work fine but on ANDROID not.

the animation contains fade in and transform: translateX animation.

If there another way to make like on IOS I will be glad to here, It's supposed to be a dynamic list 

**FadeInView component:**

 ```
   export class FadeInView extends Component {
    state = {
        rightToLeftAnim: new Animated.Value(450),
        fadeAnim: new Animated.Value(0),
    };

    componentDidMount() {
        Animated.sequence([
            Animated.delay((this.props.index + 1) * 1000),
            Animated.parallel([
                Animated.timing(
                    this.state.rightToLeftAnim,
                    {
                        toValue: 0,
                        duration: 1000,
                        easing: Easing.inOut(Easing.quad),
                        useNativeDriver: true,
                    }
                ),
                Animated.timing(
                    this.state.fadeAnim,
                    {
                        toValue: 1,
                        duration: 1000,
                        useNativeDriver: true,
                    }
                )
            ])
        ]).start();

    }

    render() {
        let { fadeAnim,rightToLeftAnim } = this.state;

        const rightToLeft = {
            transform: [{translateX: rightToLeftAnim}]
        };

        return (
            <Animated.View                
                style={[rightToLeft,{flex: 1, ...this.props.style, opacity: fadeAnim,}]}
            >
                {this.props.children}
            </Animated.View>
        );
    }
}

```
**parent component:**
        
```
 class MyPlans extends Component {
      constructor(props) {
        super(props);
       }
        render() {
        return (
            <View>
                    <FlatList
                        style={{marginTop: Platform.OS === 'ios' ? 0 : 60}}
                        data={[{key: 'module a'},{key: 'module b'},{key: 'module c'},{key: 'module d'}]}
                        horizontal={true}
                        renderItem={({item,index}) => <FadeInView index={index} style={this.moduleStyle}><Text>{item.key}</Text></FadeInView>}
                    />
            </View>);
    }
```
![ios](https://user-images.githubusercontent.com/12031960/40639683-dfaabf58-631a-11e8-9e46-7a18bad836ce.gif)
![android](https://user-images.githubusercontent.com/12031960/40639674-cd9ebf9e-631a-11e8-8773-c5577936a842.gif)

**Comment by aharon87** [comment]
Environment was added

**Comment by Fitzpasd** [comment]
@aharon87  - Did you find a fix for this?

**Comment by Fitzpasd** [comment]
If not, using this lib would fix it - https://github.com/entria/react-native-view-overflow
