### ISSUE TITLE
Show warning when using `URLSearchParams` in development mode

### ISSUE THREAD

**Issue by pie6k** [facebook/react-native#19487]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

As noted in https://github.com/facebook/react-native/issues/9596 - `URLSearchParams` is not avaliable in react-native. However - it's working fine in development mode. 

As `URLSearchParams` is related to async functionalities usually (eg fetching), you might forget (which is bad but happens) to add catch to some promies and have error swallowed with no idea what is not working. And not expecting issue to be `URLSearchParams`, and looking for something else for minutes or hours :)

## Environment
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 7.6.0
  Yarn: 1.5.1
  npm: 4.1.2
  Watchman: 4.9.0
  Xcode: Xcode 9.3.1 Build version 9E501
  Android Studio: 3.1 AI-173.4670197

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.2 => 0.52.2

## Steps to Reproduce
Create an app and use `URLSearchParams` somewhere

## Expected Behavior
It's not working both in dev and production at all so you know about it early on.

## Actual Behavior
It works in dev without problems and then it's not in production. As it's related to async functionality. It's likely to have it swallowed by some promise without catch leaving you with no idea what is not working.

**Comment by agrcrobles** [comment]
When you switch to development mode you are [switching the execution environment](https://facebook.github.io/react-native/docs/javascript-environment.html) and therefore using Chrome V8 instead of Safari JavascriptCore.

In order to use `URLSearchParams`, I think you should look into a polyfill.

**Comment by pie6k** [comment]
@agrcrobles thanks for replying

I'm aware I can use polyfill. It's not issue here. 

Issue is that I had no idea I'm not able to use it in production and it should show some warning in development when you use it.

It may become really hard to debug in production as you're not expecting native js function to cause crash, especially when it works in dev.

**Comment by pie6k** [comment]
Yes
