### ISSUE TITLE
Non-standard behavior of Promise.prototype.finally

### ISSUE THREAD

**Issue by leeyeh** [facebook/react-native#19490]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment

```
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.11.1
  Yarn: 1.7.0
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3.1 Build version 9E501
  Android Studio: 3.1 AI-173.4670197

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: ~0.55.2 => 0.55.4
```

## Steps to Reproduce

https://snack.expo.io/r1wCcj5JQ

## Expected Behavior

console: 42

## Actual Behavior

console: undefined

----

I did some digging around, finding that the polyfilled Promise imported from fbjs is not implemented [right](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally): 

https://github.com/facebook/fbjs/blob/v0.8.16/src/__forks__/Promise.native.js#L18-L23

There is already an issue about this years ago: https://github.com/facebook/fbjs/issues/132

Another related issue: https://github.com/facebook/react-native/issues/17972

**Comment by cpojer** [comment]
I'm currently landing a fix for this.

**Comment by HolySamosa** [comment]
@cpojer What is the appropriate issue to track to follow this fix?

**Comment by cpojer** [comment]
There is no issue, this was already landed on master last week.

**Comment by gianpaj** [comment]
For those looking for the commit like me:
https://github.com/facebook/react-native/commit/d5ae59ab2a09cda5109303abb9c269318a1e6686
