### ISSUE TITLE
Fatal error "style property 'right' is not supported by native animated module" when using native driver with opacity on same Animated.View

### ISSUE THREAD

**Issue by dereknelson** [facebook/react-native#19494]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment
Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.9.4
  Yarn: 1.6.0
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: https://github.com/expo/react-native/archive/sdk-26.0.0.tar.gz (0.54) => 0.54.2

## Steps to Reproduce

```
import React, { Component } from 'react'
import { Text, TouchableOpacity,  Animated, Dimensions, } from 'react-native'

const { height, width } = Dimensions.get('window')

export default class App extends Component {
    constructor(props){
        super(props)
        this.exampleOpacity = new Animated.Value(1)
        this.examplePosition = new Animated.Value(width * .45)
    }
    animateExample = () => {
        Animated.parallel([
            Animated.timing(this.exampleOpacity, {
                toValue: 1,
                duration: 400,
                useNativeDriver: true
            }),
        ]).start()
    }
    render(){
        return (
            <TouchableOpacity style={{ flex: 1, justifyContent: 'center' }} onPress={this.animateExample} >
                <Animated.View style={{ position: 'absolute', right: this.examplePosition, top: width * .5, opacity: this.exampleOpacity,  }} >
                    <Text>
                        Press me
                    </Text>
                </Animated.View>
            </TouchableOpacity>
        )
    }
}
```
Snack: https://snack.expo.io/r1_I1VgfX

## Expected Behavior
The native driver compatible animations (opacity) should work with the noncompatible animations (positions) that don't use the driver. The issue lies with using an animated position for "right":
`style={{ right: this.examplePosition, opacity: this.exampleOpacity }}` in tandem with an animated value for opacity, even if the animated position isn't being manipulated. Works as intended if `style={{ /*right: this.examplePosition*/ opacity: this.exampleOpacity }}`

## Actual Behavior
App crashes because position is not supported by using the native module.

**Comment by thg303** [comment]
it's documented in the [animation guide](https://facebook.github.io/react-native/docs/animations#caveats) 

> things like **transform** and **opacity** will work, but **flexbox** and **position properties** will not

looks like we need a PR to fix this

**Comment by dereknelson** [comment]
@thg303 but I'm not using the native driver on the position properties, I'm not even animating those properties at all
