### ISSUE TITLE
(Android) TextInput lag when there are a lot of messages

### ISSUE THREAD

**Issue by aspidvip** [facebook/react-native#19500]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native version: https://github.com/facebook/react-native/releases
  - [x] Run `react-native info` in your terminal and paste its contents under "Environment"
  - [ ] Let us know how to reproduce the issue. Include a code sample, share a project, or
    share an app that reproduces the issue using https://snack.expo.io/

## Environment

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 6.11.1
  Yarn: 0.27.5
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.1 Build version 9B55
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.3 => 0.55.3 & 0.55.4

## Description

When you type text on Android, hangs
## Steps to Reproduce

When user enter large text (50+ characters) and remove it then repeat process again 2 or more times. 

```
<TextInput 
onChangeText={(text) => this.setState({text})}
value={
this.setState({text: this.state.text})
}
/>
```

![40582367-33f29d16-61b7-11e8-80ff-1967e8e0ba5c](https://user-images.githubusercontent.com/22605655/40696950-bf0c299c-63b7-11e8-9e99-9c1456c54736.gif)

## Expected Behavior

-
## Actual Behavior

-

**Comment by stueynet** [comment]
I can confirm this but it does not require  lot of messages. It happens with any amount of text. Try the plain installation drop in a text input. Then type on android and try deleting. Gets slower over time.

**Comment by tuomohopia** [comment]
This is most definitely the same issue as reported here: https://github.com/facebook/react-native/issues/19126

**Comment by alwex** [comment]
I confirm, exact same issue with 0.55.4, it happens on android S5 mini after 20 input type/clear.

**Comment by s-nel** [comment]
It is the same issue as #19126 but I've reproduced on 0.56.0. Clearing doesn't seem to be required for me. If I type enough characters the framerate drops to single digits.

Here's a repository for reproduction https://github.com/s-nel/rn19126

![longtext](https://github.com/s-nel/rn19126/raw/master/frameloss.gif)

**Comment by kelset** [comment]
Closing in favour of #20119 which has more details.
