### ISSUE TITLE
How to send file to outside in react native ios app?

### ISSUE THREAD

**Issue by bright-sea** [facebook/react-native#1950]
In our RN app, we need send data in string format(very long string) or file format(we can save this data string in a file of app's document directory) to outside. For example, the best way is send it as attachment in an email.

If we use share by email function of RN, it can only pass in some message. No way to attach an attachment.

So we are looking for some node modules to send emails. And [nodemailer](http://www.nodemailer.com/) is a great email module we used quite well. But it can't be used in react native because it depends on some module, like "stream" which are not available in RN.  

So any solution for share data file in RN app to outside?

**Comment by dsibiski** [comment]
@bright-sea It seems like you need to use `MFMailComposeViewController`, which support attachments.

It looks like there is a 3rd party library for using `MFMailComposeViewController` here: https://github.com/chirag04/react-native-mail

However it seems like the library itself doesn't allow for attachments in it's API. I'm sure that would be something the author would love for you to add to his library.

Here is Apple's documentation: https://developer.apple.com/library/ios/documentation/MessageUI/Reference/MFMailComposeViewController_class/#//apple_ref/occ/instm/MFMailComposeViewController/addAttachmentData:mimeType:fileName:

...and here is how you could possibly implement it on the Obj-C side (add this to the `react-native-mail` library): http://stackoverflow.com/a/11915765/4932710

**Comment by bright-sea** [comment]
@dsibiski  Thanks a lot for all these info. It helps. :)

**Comment by brentvatne** [comment]
Closing this as it looks like @dsibiski handled it above :smile: :tada:
