### ISSUE TITLE
Repeatedly Trigger NativeModules Event

### ISSUE THREAD

**Issue by sendroid-laonan** [facebook/react-native#19506]
## Environment
Environment:
OS: Windows 10
Node: 8.9.4
Yarn: 1.6.0
npm: 5.8.0
Watchman: Not Found
Xcode: N/A
Android Studio: Not Found

Packages: (wanted => installed)
react: 16.3.1 => 16.3.1
react-native: 0.55.1 => 0.55.1

## Description
each time when i
 【click on button_1 and close the component, then open the component and click on button_1 again】:
 once method with button_1 Repeatedly trigger the same NativeModules event
 times of Repeated is growth in linear( **+1 times when close the component each times**)

## Steps to Reproduce
step①: first time open component_1 => 
step②: click on button_1 => 
step③: close the component_1 =>
step④: open component_1 again =>
step⑤: click on button_1 => 
step⑥: close the component_1 =>
step⑦: open component_1 again =>
step⑧: click on button_1 => 

## Expected Behavior
in step ②: Trigger NativeModules event for once
in step ⑤: Trigger NativeModules event for once
in step ⑧: Trigger NativeModules event for once

## Actual Behavior
in step ②: Trigger NativeModules event for once
in step ⑤: Trigger NativeModules event for twice
in step ⑧: Trigger NativeModules event for thrice

**Comment by hramos** [comment]
Can you provide a minimal reproduction of the issue? https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff
