### ISSUE TITLE
Connection refused when running android project

### ISSUE THREAD

**Issue by vbraeke** [facebook/react-native#19508]
## Environment

  OS: Windows 7
  Node: 8.11.1
  Yarn: Not Found
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4
## Description
Connection refused while running react-native run-android

## Steps to Reproduce

react-native run-android

## Expected Behavior

Build success

## Actual Behavior
`
[DeviceMonitor]: Unable to open connection to: localhost/xx.xxx.xxx.xx:5037, due
 to: java.net.ConnectException: Connection refused: connect
[DeviceMonitor]: Connection attempts: 1
[DeviceMonitor]: Unable to open connection to: localhost/xx.xxx.xxx.xx:5037, due
 to: java.net.ConnectException: Connection refused: connect
[DeviceMonitor]: Connection attempts: 2
`

**Comment by Piusha** [comment]
Any solution for this issue?

**Comment by warrence** [comment]
Any solution on this? im having the same problem, I suspect it was something to do with realm? since the port is 5037 and im seeing this piece of message when react-native run-android. 

`> Task :realm:forwardDebugPort 
* daemon not running; starting now at tcp:5037
* daemon started successfully`

**Comment by vbraeke** [comment]
It's due to fact that Win7 prefers to return IPV6 address for localhost and mine was not properly setup. So I forced java to use IPV4 adress by adding a new environment variable : 

`_JAVA_OPTIONS=-Djava.net.preferIPv4Stack=true`

And it fixed it.

**Comment by minhphung210** [comment]
i have same issue. 
i use macOS High Sierra 10.13.6 and react-native version: 0.57.7

**Comment by avoidchanges** [comment]
> It's due to fact that Win7 prefers to return IPV6 address for localhost and mine was not properly setup. So I forced java to use IPV4 adress by adding a new environment variable :
> 
> `_JAVA_OPTIONS=-Djava.net.preferIPv4Stack=true`
> 
> And it fixed it.

in what file?

**Comment by minhphung210** [comment]
> > It's due to fact that Win7 prefers to return IPV6 address for localhost and mine was not properly setup. So I forced java to use IPV4 adress by adding a new environment variable :
> > `_JAVA_OPTIONS=-Djava.net.preferIPv4Stack=true`
> > And it fixed it.
> 
> in what file?

cd your proẹct file and paste it to terminal
for mac:  `export _JAVA_OPTIONS=-Djava.net.preferIPv4Stack=true`

**Comment by ndel** [comment]
Thank you @minhphung210
