### ISSUE TITLE
 'config.h' file not found

### ISSUE THREAD

**Issue by LionBuer** [facebook/react-native#19529]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native version: https://github.com/facebook/react-native/releases
  - [x] Run `react-native info` in your terminal and paste its contents under "Environment"
  - [ ] Let us know how to reproduce the issue. Include a code sample, share a project, or
    share an app that reproduces the issue using https://snack.expo.io/

## Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.6.0
  Yarn: 1.2.1
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

## Description

when i  adding a single view to existing native applications, it works ok.
But an error occurred when I tried to package my app.

## Steps to Reproduce

Successfully integrated into existing applications
package
error

## Expected Behavior

package success 

## Actual Behavior

......./ios/Pods/glog/src/base/mutex.h:105:10: fatal error: 

      'config.h' file not found

**Comment by LionBuer** [comment]
emmmmm????

**Comment by TrustTheBoy** [comment]
Please  see https://github.com/facebook/react-native/issues/14382

**Comment by stepheljobs** [comment]
Fix my bug.

rm -rf node_modules/ && yarn cache clean && yarn install
node_modules/react-native/scripts/ios-install-third-party.sh

**Comment by ReggaePanda** [comment]
I need a little bit more, but then it works for me too :)



```
rm -rf node_modules/ && yarn cache clean && yarn install
node_modules/react-native/scripts/ios-install-third-party.sh
node_modules/react-native/third-party/glog-0.3.4/configure
```
(replace glog-0.3.X with yours)



<img width="1132" alt="bildschirmfoto 2018-09-24 um 09 47 51" src="https://user-images.githubusercontent.com/2183135/45941574-18d49f80-bfdf-11e8-915d-9f920e0dae99.png">
replace with `NULL`
<img width="670" alt="bildschirmfoto 2018-09-24 um 09 48 06" src="https://user-images.githubusercontent.com/2183135/45941586-2a1dac00-bfdf-11e8-9ee7-fc7c3d4686fe.png">


<img width="1130" alt="bildschirmfoto 2018-09-24 um 09 50 59" src="https://user-images.githubusercontent.com/2183135/45941621-63561c00-bfdf-11e8-8a1c-c20ade23111e.png">

Remove library libfishhook.a and add again
<img width="984" alt="bildschirmfoto 2018-09-24 um 09 52 00" src="https://user-images.githubusercontent.com/2183135/45941671-9ac4c880-bfdf-11e8-9ac6-717c3005259e.png">
<img width="918" alt="bildschirmfoto 2018-09-24 um 09 52 13" src="https://user-images.githubusercontent.com/2183135/45941673-9d272280-bfdf-11e8-8ae2-f7aa9aca34b0.png">

**Comment by fbartho** [comment]
@ReggaePanda I did indeed have to run that `/configure` script but I had to run it within the log directory!

**Comment by sospedra** [comment]
I had an error pointing to a missing `./config` file. Because the `ios-install-third-party.sh` uses relative paths.

Here's my solution: `cd ./node_modules/react-native/scripts/third-party/glog-0.3.4 && ../../scripts/ios-install-third-party.sh && cd ../../../../`

*Note* the `glog-0.3.4` version may change depending on your `react-native` version.

**Comment by renatobenks** [comment]
thank you @ReggaePanda, you helped me a lot!

**Comment by dahveed-rb** [comment]
@ReggaePanda YOU'RE THE MAN. After spending a 10 hours trying to figure this out, your process finally worked. Can't thank you enough!

**Comment by Gra55h0pper** [comment]
Same here. @ReggaePanda, thanks very much for sharing!

**Comment by lgandecki** [comment]
I'm always amazed - how do you guys figure out cryptic errors like those? Especially when it is what feels like an endless chain of fix/new error story.. 

Thanks for the fix @ReggaePanda .

**Comment by NNaidoo** [comment]
repost from: https://github.com/facebook/react-native/issues/19529#issuecomment-427209573

I wrote something a bit cleaner for my purposes and installed the fix within the node_modules/react-native package. Normally I would prefer not to modify a node_module directly, but under this circumsance I felt that it was worth it and allowed us to add a simple script in our yarn start script and we get a clean run from a fresh clone.

`npm install` or `yarn` - install packages
`cd node_modules/react-native` - go to node modules directory
`scripts/ios-install-third-party.sh`- install @ node_modules/react-native/third-party
`cd third-party` - go to newly created third party directory
`cd glog-0.3.x `  - `ls -la` to find your directory version number or just use tab to auto-complete)
`./configure` - run setup
`cd ../../../../`- change back to your project directory
`react-native run-ios` or `react-native run-android` - deploy

(maybe its even better inside the node_modules/react-native/node_modules directory?)

**Comment by NNaidoo** [comment]
I wrote something a bit cleaner for my purposes and installed the fix within the node_modules/react-native package. Normally I would prefer not to modify a node_module directly, but under this circumsance I felt that it was worth it and allowed us to add a simple script in our yarn start script and we get a clean run from a fresh clone.

### glog-0.3.4
`cd node_modules/react-native && scripts/ios-install-third-party.sh && cd third-party && cd glog-0.3.4 && ./configure && cd ../../../../`

### glog-0.3.5
`cd node_modules/react-native && scripts/ios-install-third-party.sh && cd third-party && cd glog-0.3.5 && ./configure && cd ../../../../`

### Manual Steps
`npm install` or `yarn` - install packages
`cd node_modules/react-native` - go to node modules directory
`scripts/ios-install-third-party.sh`- install @ node_modules/react-native/third-party
`cd third-party` - go to newly created third party directory
`cd glog-0.3.x `  - `ls -la` to find your directory version number or just use tab to auto-complete)
`./configure` - run setup
`cd ../../../../`- change back to your project directory
`react-native run-ios` or `react-native run-android` - deploy

**Comment by uamanager** [comment]
## For any glog ##

```bash
cd ./node_modules/react-native && scripts/ios-install-third-party.sh && cd third-party && cd $(ls | grep 'glog' | awk '{print $1}') && ./configure
```

**Comment by alqamabinsadiq** [comment]
This worked for me:
```
rm -rf node_modules/ && yarn cache clean && yarn install
node_modules/react-native/scripts/ios-install-third-party.sh
cd node_modules/react-native/third-party/glog-0.3.4
./configure
```

**Comment by mchambaud** [comment]
Latest version of react-native has not third-party folder. 

This solution is no longer working

**Comment by touqeerkhan11** [comment]
This worked for me 

File -> Project (Workspace) Settings -> Build System -> Legacy Build System

**Comment by MinhajJaved** [comment]
You need to change to the legacy build system in Xcode 10 and install third party scripts manually.

1:

File -> Project/Workspace settings
Build System: dropdown -> change to Legacy Build system

2: Follow this to manually install third party scripts for RN:

Clean RN cache

$ rm -rf ~/.rncache

Re-install the deps

$ cd your_project_path
$ rm -rf node_modules/ && npm install

Then install the third-party

$ cd node_modules/react-native/scripts
$ ./ios-install-third-party.sh

Run the commands below if glog installation failed.

$ cd ../third-party/glog-0.3.x
$ ./configure

It works for me, I hope it helps for you.

**Comment by albertoclarit** [comment]
> You need to change to the legacy build system in Xcode 10 and install third party scripts manually.
> 
> 1:
> 
> File -> Project/Workspace settings
> Build System: dropdown -> change to Legacy Build system
> 
> 2: Follow this to manually install third party scripts for RN:
> 
> Clean RN cache
> 
> $ rm -rf ~/.rncache
> 
> Re-install the deps
> 
> $ cd your_project_path
> $ rm -rf node_modules/ && npm install
> 
> Then install the third-party
> 
> $ cd node_modules/react-native/scripts
> $ ./ios-install-third-party.sh
> 
> Run the commands below if glog installation failed.
> 
> $ cd ../third-party/glog-0.3.x
> $ ./configure
> 
> It works for me, I hope it helps for you.


This instructions works as long as theres no space in project's path...

**Comment by m4v0** [comment]
I followed the pastures of @MinhajJaved ... however after executing the command "./ios-install-third-party.sh", I moved the "third-party" directory to a level below that is in the folder "node_modules / react-native "and I ran the next command" cd ../third-party/glog-0.3.xe ./configure "... it worked perfectly ...

Because I did this because the command "ios-install-third-party.sh" installs the "third-party" package in the "node_modules / react-native / scripts" folder and not at a level below that would be "node_modules / react-native ".

This for react-native 0.57.7

tks @MinhajJaved

**Comment by HarshalValanda** [comment]
i just remove spacing from project parent folder name 

Working On to Working-On 

Close Xcode --> Clean --> Run

**Comment by HarshalValanda** [comment]
Same error occurred in my project i tried all solutions but when i removed
space from main project name its working

Cab you pass your project directory screenshot?

**Comment by AlexM2807** [comment]
Thanks @NNaidoo  it's work

**Comment by HarshalValanda** [comment]
👌

**Comment by gurmundi7** [comment]
> @ReggaePanda I did indeed have to run that `/configure` script but I had to run it within the glog directory, aka `cd node_modules/react-native/third-party/glog-0.3.4/; ./configure`

This answer works just fine. Thanks

**Comment by jiawenbin2013** [comment]
@ReggaePanda 

Can't thank you enough!

**Comment by jiawenbin2013** [comment]
@ReggaePanda 
Can't thank you enough!

**Comment by aleclarson** [comment]
Reinstalling `react-native` should be enough, as `glog` is configured automatically during the first Xcode build.

**Comment by Lohins** [comment]
I have a similar issue. When I used the Default Build System, I got an error about double-conversion related to `glog-0.3.5`. Then I changed it to `Legacy Build System`. The error is gone.
But I still had an error about `third-party`.  Then I ran the following commands. Working
```
node_modules/react-native/scripts/ios-install-third-party.sh
cd node_modules/react-native/third-party/glog-0.3.4
./configure
```

**Comment by neoswallow** [comment]
I had this issue when I installed Xcode 10.2 and installed Xcode 10.1 in ~/Applications/ folder and opened Xcode project file with 10.1.
The root cause of the problem was that RN created/installed third-party directory at the root directory of the repo rather than under node-modules/react-native.
By removing Xcode 10.2 and put back Xcode 10.1 in /Applications folder resolved the issue.
Our project is running RN 0.54.4.
I am not sure why the location of Xcode matters but it should be fixed as many would do this to either test new version of Xcode or keep older version for compatibility issue.

**Comment by pphearun** [comment]
> @ReggaePanda I did indeed have to run that `/configure` script but I had to run it within the glog directory, aka `cd node_modules/react-native/third-party/glog-0.3.4/; ./configure`

Thanks it work for me

**Comment by jamesawer3** [comment]
still i have the same issue,

[config.log](https://github.com/facebook/react-native/files/3112169/config.log)

**Comment by hite** [comment]
> Fix my bug.
> 
> rm -rf node_modules/ && yarn cache clean && yarn install
> node_modules/react-native/scripts/ios-install-third-party.sh

Don't work for react-native@0.59.2

**Comment by nulijiao** [comment]
when i run ./configure always error so it run 
rm -r ~/.rncache/
cd node_modules/react-native/third-party/glog-0.3.4/
./configure --host arm-apple-darwin
maybe helpful

**Comment by TRIPTI-JAIN** [comment]
In the Terminal, navigate to the react-native/third-party/glog folder inside node_modules (for me, this was cd node_modules/react-native/third-party/glog-0.3.4)
Once actively in this folder, run ../../scripts/ios-configure-glog.sh
Glog is configured and the required config.h header file is created for Xcode to find
