### ISSUE TITLE
Execution failed for task ':app:mergeDebugResources'.

### ISSUE THREAD

**Issue by alihesari** [facebook/react-native#19532]
When I run `react-native run-android` get this error:
```
Execution failed for task ':app:mergeDebugResources'.
> Error: java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: AAPT2 error: check logs for details
```

React: `16.3.1`
React native: `0.55.3`
Gradle: `com.android.tools.build:gradle:3.1.2`
compileSdkVersion 27
buildToolsVersion '27.0.3'

**Comment by alihesari** [comment]
My problem solved. I have a mistake in the code.

**Comment by B4UGUYS** [comment]
hey @alihesari , could you please tell me how do you solve it ?I face the same problem and don't know the place where it occur.

**Comment by mbilalahsan** [comment]
@alihesari  i am also having the same issue since 3 days and cant resolve it can guide what was your mistake
