### ISSUE TITLE
[Navigator] Push without animation

### ISSUE THREAD

**Issue by PhilippKrone** [facebook/react-native#1953]
Hello,

is it currently possible to have a push / jumpTo / etc. without triggering an animation, kind of like "replace"? I don't see anything in the docs about sceneConfig really.

Thanks!
Philipp

**Comment by yamill** [comment]
Hey @PhilippKrone you can use the fade transition for Android introduced in 0.7.1. It's nice and works in iOS!

    sceneConfig: Navigator.SceneConfigs.FadeAndroid

**Comment by PhilippKrone** [comment]
hi @yamill - thanks for the hint. This looks really nice, but I'd prefer a transition without animation at all. Let me give some background: I have a navigation bar analogous to the facebook app and I basically want it to behave like that as well. I could use "replace" but then I'm loosing the state of the individual scenes and once I go back to a scene it starts on the main screen instead of the last one the user was navigating to (in the child navigators of each tab I mean). Do you have any idea how to solve that?

**Comment by PhilippKrone** [comment]
Update. I'm currently solving my issue by using the following:


````javascript
var NoTransition = {
  opacity: {
    from: 1,
    to: 1,
    min: 1,
    max: 1,
    type: 'linear',
    extrapolate: false,
    round: 100,
  },
};

    return  {
                ...Navigator.SceneConfigs.FloatFromLeft,
                gestures: null,
                defaultTransitionVelocity: 100,
                animationInterpolators: {
                  into: buildStyleInterpolator(NoTransition),
                  out: buildStyleInterpolator(NoTransition),
                },
            };
````
But thats kind of hacky, I know.

**Comment by brentvatne** [comment]
Thanks @PhilippKrone - glad you found a solution. If anyone would like to provide a cleaner API for that, please submit a PR :smile: I will if I ever run into the use case myself.

**Comment by vincentracine** [comment]
@PhilippKrone Thanks for the solution. I would bump the defaultTransitionVelocity up though to avoid flickering. 

```
'use strict';

import React, {
	Navigator
} from 'react-native';

const buildStyleInterpolator = require('buildStyleInterpolator');

var NoTransition = {
	opacity: {
		from: 1,
		to: 1,
		min: 1,
		max: 1,
		type: 'linear',
		extrapolate: false,
		round: 100
	}
};

const Transitions = {
	NONE: {
		...Navigator.SceneConfigs.FadeAndroid,
		gestures: null,
		defaultTransitionVelocity: 10000,
		animationInterpolators: {
			into: buildStyleInterpolator(NoTransition),
			out: buildStyleInterpolator(NoTransition)
		}
	}
};

export default Transitions;
```

**Comment by ds3783** [comment]
@vincentracine @PhilippKrone Thanks,although there also has 3-4 frames animation,on an old slow android phone, but this solution works much faster.

**Comment by ncuillery** [comment]
@PhilippKrone @vincentracine @ds3783 Have you try to run this hack on a real device ?

On an iphone, all the screen becomes white when the transition is finished: The new view is displayed during few millis and then the white screen pops (or the view becomes transparent, IDK...).

Work like a charm on iOS / Android simulators and on Android devices though...

We only way to get rid of this is to come back to the vanilla FadeAndroid transition.

**Comment by vincentracine** [comment]
@ncuillery Yes I tested this on my iPhone 6 but I sometimes received the issue you have mentioned when the 'defaultTransitionVelocity' was set higher than 1000. Im not too sure what is causing this problem though and if you have set your 'defaultTransitionVelocity' to 1000 then I really do not know sorry! Try 999? Really, what we need a proper way to set this behaviour rather than a hack.

**Comment by ncuillery** [comment]
I fixed the problem by defining a constant opacity transition, instead of a linear one from 1 to 1, inspired by [this line](https://github.com/facebook/react-native/blob/9a82c03e1f3415e255c5936aa2c35f0fd006a785/Libraries/CustomComponents/Navigator/NavigatorSceneConfigs.js#L47-L50) in RN source code.

Replace the `NoTransition` variable above by 

```javascript
var NoTransition = {
  opacity: {
    value: 1.0,
    type: 'constant',
  }
};
```

 💪

**Comment by Smallpath** [comment]
Thanks a lot , you are all my life saver

**Comment by aTable** [comment]
Summarizing the above for others (and my future self), put this in a new file possibly `CustomTransitions.js`

```
import React, { Navigator, } from 'react-native';
import buildStyleInterpolator from 'buildStyleInterpolator';

var NoTransition = {
    opacity: {
        value: 1.0,
        type: 'constant',
    }
};

const NONE = Object.assign({}, Navigator.SceneConfigs.FadeAndroid, {
    gestures: null,
    defaultTransitionVelocity: 1000,
    animationInterpolators: {
        into: buildStyleInterpolator(NoTransition),
        out: buildStyleInterpolator(NoTransition),
    },
});

const Transitions = {
    NONE,
};


export default Transitions;
```

And where you create your `<Navigator ... />`, e.g.
```
import CustomTransitions from '../shims/CustomTransitions';

...
...
render() {
    return (
      <Navigator
       ...
        configureScene={(route, routeStack) => CustomTransitions.NONE}
        />
    );
  }

```

**Comment by Etheryte** [comment]
Personally I've been using the following which is just a slightly modified unrolled version of the above suggestions.
```js
const InstantTransition = {
    gestures: null,
    defaultTransitionVelocity: null,
    springFriction: null,
    springTension: 1000,
    animationInterpolators: {
        into: r => r.opacity = 1,
        out: r => r.opacity = 1,
    },
};
```

However, the current scene configuration interface should really be expanded to disable animations altogether.  
Transitions are currently [so ingrained in the navigator module (Navigator.js#L969)](https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/Navigator/Navigator.js#L969) that it's hard to customize it without overriding most of the methods.

**Comment by MiLeung** [comment]
The solutions above only work if all the transitions for a navigator are none.  I think defaultTransitionVelocity applies to all transitions.

**Comment by Etheryte** [comment]
@MiLeung Not really? I'm successfully using the above solution along with other transitions in an application.

**Comment by MiLeung** [comment]
My configureScene looks like this

```javascript
configureScene = ({ title }) => {
    if (title === 'Play') {
      return {
        ...Navigator.SceneConfigs.FloatFromBottom,
        gestures: null,
      };
    }

    return {
      gestures: null,
      defaultTransitionVelocity: null,
      springFriction: null,
      springTension: 1000,
      animationInterpolators: {
        into: r => r.opacity = 1,
        out: r => r.opacity = 1,
      },
    };
  }
```

And the end result looks something like this

![](https://media.giphy.com/media/xUA7b4pjdjr0Xj2x56/giphy.gif)

The middle tab has the FloatFromBottom transition.  When you press it, the scene shows up very rapidly, but when you exit the scene, it transitions at a normal speed.
