### ISSUE TITLE
MaskedView support for Android

### ISSUE THREAD

**Issue by IljaDaderko** [facebook/react-native#19546]
## For Discussion
I've worked on view demonstrated below today, very pleasant experience while using [MaskedViewIOS](https://facebook.github.io/react-native/docs/maskedviewios.html)
In essence it masks Orc graphic with that dark cloud / smoky mask. On android however, I was not able to find anything similar from community and after 3h of trying to create a native component bridge for this, I came nowhere close :/

Hence I wanted to start this discussion, shall we make `MaskedView` more general and support it for Android as well, or are there some limitations that don't allow this (hence only IOS implementation at the moment?)

<img width="314" alt="screen shot 2018-06-03 at 14 55 47" src="https://user-images.githubusercontent.com/3154053/40886319-386c22a4-673e-11e8-9b15-d896a5ff5ed7.png">

**Comment by janhesters** [comment]
This would be great to have for Android!

**Comment by Bunlong** [comment]
React Native Core Team should make MaskedView more general and support it for Android as well. This would be great to have MaskedView for Android :+1:

**Comment by AlexandruVoica** [comment]
Yes! MaskedView is much needed on Android as well.

**Comment by iyegoroff** [comment]
To achieve similar effect on Android you can use my [react-native-image-filter-kit](https://github.com/iyegoroff/react-native-image-filter-kit) package:
```js
import { Image } from 'react-native'
import { DstATopComposition } from 'react-native-image-filter-kit'

const style = { width: 320, height: 320 }

const masked = (
  <DstATopComposition
    dstImage={
      <Image
        style={style}
        source={{ uri: 'https://i.ytimg.com/vi/_ebwvrrBfUc/hqdefault.jpg' }}
      />
    }
    srcImage={
      <Image
        style={style}
        source={{ uri: 'https://pluspng.com/img-png/download-smoke-effect-png-images-transparent-gallery-advertisement-advertisement-336.png' }}
      />
    }
  />
)
```

![android](https://user-images.githubusercontent.com/4447438/50552951-dcd06b00-0cae-11e9-915b-a6861d027765.jpg)


Text mask [example](https://stackoverflow.com/a/53982429/4134913)

**Comment by cpojer** [comment]
This issue has been moved to react-native-community/react-native-masked-view#3.
