### ISSUE TITLE
[IOS] Error running with release using pods

### ISSUE THREAD

**Issue by jampueroc** [facebook/react-native#19544]
- [X] Review the documentation: https://facebook.github.io/react-native
  - [X] Search for existing issues: https://github.com/facebook/react-native/issues
  - [X] Use the latest React Native version: https://github.com/facebook/react-native/releases
  - [X] Run `react-native info` in your terminal and paste its contents under "Environment"
  - [X] Let us know how to reproduce the issue. Include a code sample, share a project, or
    share an app that reproduces the issue using https://snack.expo.io/

## Environment

```
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.9.1
  Yarn: 1.6.0
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4 Build version 9F1027a
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4
```

## Description

I found an error when I try to run on Release using IOS (with device and simulator). I made a new project to compare differences and this still happen.
I added a basic Podfile with some fix to run the project, in debug it works but in release, crash when you tap some input.

## Steps to Reproduce

I upload a repo that you can reproduce. (I created a new project using react-native-cli, I added inputtext code and basic podfile ) => https://github.com/jampueroc/test-react-native

You need to run on RELEASE mode and tap blue INPUTTEXT.

## Expected Behavior

Running without error in Release. 

## Actual Behavior

Error  when you tap inputText but it happen only on release mode.
<img width="1138" alt="captura de pantalla 2018-06-02 a la s 3 07 02 p m" src="https://user-images.githubusercontent.com/9870984/40879952-b7a5188c-6676-11e8-8c24-6aa4242b56b2.png">

**Comment by vovkasm** [comment]
Hmm... TextInput without value? I guess that's not pods specific.

**Comment by jampueroc** [comment]
I tried not using Podfile and in this case it works, so something happen with Podfile (the repo only has react import and some fix of error)

**Comment by vovkasm** [comment]
@jampueroc You link application not only with Pods, but also with static libraries, it can be real cause.

**Comment by vovkasm** [comment]
@jampueroc yes, confirmed. I clone you repo and modify it to work. See https://github.com/vovkasm/test-react-native. Instead of auto-fix various issues on pod install, I prefer to maintain our own fixed version of RN, so sorry, I switched to it. It contains some patches + 2 patches to make it work with `use_frameworks` (Thanks, now I can cook RN with frameworks :-). Also I don't use yarn, only npm.
But anyway, commit that should fix things for you is https://github.com/vovkasm/test-react-native/commit/1ee8b2932aaf2854a038b07a054668f270491293

**Comment by vovkasm** [comment]
But this bug can be safely closed, yes? )
