### ISSUE TITLE
[Image] When is onLoadAbort fired?

### ISSUE THREAD

**Issue by jasper-lyons** [facebook/react-native#1954]
While reading through the documentation to get a nice broad knowledge of all of the standard elements implemented I've stumbled across the [Image element](https://facebook.github.io/react-native/docs/image.html#content) events.

One stuck out for me: __onLoadAbort__

I could certainly envision why this might be available but the doc only state: 
> 'Invoked on load abort'

So in an attempt to track down what 'abort' means in this context I went code diving and found that all of the other events have call sites.

* [onLoadStart](https://github.com/facebook/react-native/blob/f6d058dfeaf9f639998d0dc21822a44d23423e3f/Libraries/Image/RCTNetworkImageView.m#L101)

* [onLoadError](https://github.com/facebook/react-native/blob/f6d058dfeaf9f639998d0dc21822a44d23423e3f/Libraries/Image/RCTNetworkImageView.m#L119)

* [onLoadProgress](https://github.com/facebook/react-native/blob/f6d058dfeaf9f639998d0dc21822a44d23423e3f/Libraries/Image/RCTNetworkImageView.m#L110)

* [onLoaded](https://github.com/facebook/react-native/blob/f6d058dfeaf9f639998d0dc21822a44d23423e3f/Libraries/Image/RCTNetworkImageView.m#L124)

I could not find a call site for onLoadAbort. If I am missing something could someone shoot me a short  explanation? If it's unused is it not potentially confusing for users who might wish to rely on such functionality?

**Comment by brentvatne** [comment]
Good question!

Check this out: https://github.com/brentvatne/react-native/blob/master/Libraries/Image/RCTNetworkImageView.m#L70-L75

So:

- Set uri on an Image component to a network image
- Quickly change the uri on that same Image component to point to a different network image - quickly enough that the download will not be complete
- You will see that the onLoadAbort event will be fired!

If you'd like to add this to documentation that would be welcome! Feel free to open in a separate PR.
