### ISSUE TITLE
Can't upgrade the react-native project 

### ISSUE THREAD

**Issue by kk412027247** [facebook/react-native#19556]
## Environment
  OS: macOS High Sierra 10.13.4
  Node: 8.9.3
  Yarn: 1.6.0
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3.1 Build version 9E501
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: ^0.55.4 => 0.55.4

## Description

![simulator screen shot - iphone x - 2018-06-04 at 16 59 54](https://user-images.githubusercontent.com/30715186/40909276-bc823a0a-681b-11e8-8c01-ccb0a6d44c34.png)

I got an old react-native project some day before, the project dosen't adapt the iPhone X

I install a lastest version of react-native  in order to fix this, but nothing change.
```
yarn add  react-native
```

```
"dependencies": {
  "react": "16.2.0",
  "react-native": "^0.55.4",
}
```

Then i have found the manual [Upgrading to new React Native versions](https://facebook.github.io/react-native/docs/upgrading.html).

I run the command 'react-native-git-upgrade',  it doesn't work either.
<img width="967" alt="bash" src="https://user-images.githubusercontent.com/30715186/40909891-50a697f2-681d-11e8-9680-ffa7f96770c6.png">

![simulator screen shot - iphone x - 2018-06-04 at 18 02 08](https://user-images.githubusercontent.com/30715186/40911538-9e170c8e-6821-11e8-85b5-b61a58ba80dc.png)

I run the command  'react-native upgrade', I got a err finally.

`
error: bundling failed: NotFoundError: Cannot find entry file index.js in any of the roots:
`

<img width="1031" alt="wx20180604-182020 2x" src="https://user-images.githubusercontent.com/30715186/40912405-07ca3a0a-6824-11e8-920b-948fec4f02e1.png">

I create a index.js still can't fix this.

## Dependencies

```
 "dependencies": {
    "@remobile/react-native-qrcode-local-image": "^1.0.4",
    "animated": "^0.2.1",
    "es6-promise": "^4.2.2",
    "hoek": "^5.0.3",
    "humps": "^2.0.1",
    "isomorphic-fetch": "^2.2.1",
    "lodash": "^4.17.5",
    "normalizr": "^3.2.4",
    "offline-plugin": "^4.6.1",
    "path-to-regexp": "^2.1.0",
    "prop-types": "^15.6.1",
    "qrcode-react": "^0.1.16",
    "react": "16.2.0",
    "react-dom": "^16.2.0",
    "react-motion": "^0.5.2",
    "react-native": "^0.55.4",
    "react-native-easy-toast": "^1.1.0",
    "react-native-elements": "1.0.0-beta",
    "react-native-exit-app": "^1.0.0",
    "react-native-fetch-blob": "^0.10.8",
    "react-native-fs": "^2.9.11",
    "react-native-i18n": "^2.0.10",
    "react-native-image-picker": "^0.26.7",
    "react-native-modal": "^4.1.1",
    "react-native-parallax-scroll-view": "^0.20.1",
    "react-native-qrcode-svg": "^5.0.6",
    "react-native-share": "1.0.23",
    "react-native-smart-barcode": "^1.0.6",
    "react-native-smart-timer-enhance": "^1.0.3",
    "react-native-splash-screen": "^3.0.6",
    "react-native-stream": "^0.1.9",
    "react-native-svg": "^6.3.1",
    "react-native-vector-icons": "^4.6.0",
    "react-native-view-shot": "^2.3.0",
    "react-native-web": "^0.1.14",
    "react-navigation": "git+https://github.com/react-community/react-navigation.git#d5618ebd41ec1ac53cb40301d0f71610fbbb7172",
    "react-redux": "^5.0.6",
    "react-swipeable-views": "^0.12.12",
    "react-swipeable-views-native": "^0.12.9",
    "redux": "^3.7.2",
    "redux-logger": "^3.0.6",
    "redux-persist": "^5.4.0",
    "redux-saga": "^0.16.0",
    "redux-thunk": "^2.2.0",
    "styled-components": "^2.4.0"
  },
```

**Comment by hramos** [comment]
Upgrade issues are probably not a good fit for the repo, as they typically occur on particular projects and are hard to reproduce by any other contributor. If this is an issue that can be reliably reproduced on a minimal sample project, please do submit a new issue.
