### ISSUE TITLE
Animated.View not works in type scripte

### ISSUE THREAD

**Issue by shuangyu** [facebook/react-native#19553]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native version: https://github.com/facebook/react-native/releases
  - [x] Run `react-native info` in your terminal and paste its contents under "Environment"
  - [x] Let us know how to reproduce the issue. Include a code sample, share a project, or
    share an app that reproduces the issue using https://snack.expo.io/

## Environment
react-native: "0.54.0"
typescript: "2.8.1"
types/react-native:0.52.25

## Description

As title, when I want to use Animated.View in a ts file, it alway give me an error said "Animated has no export member View"

## Steps to Reproduce
use an Animated.View in typescript file

**Comment by hramos** [comment]
Can you provide a minimal reproduction of the issue? https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff
