### ISSUE TITLE
snapToInterval not implemented on android for vertical scroll view

### ISSUE THREAD

**Issue by nuKs** [facebook/react-native#19552]
## Environment
  OS: macOS High Sierra 10.13.4
  Node: 9.11.1
  Yarn: 1.0.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: react@16.0.0-alpha.12 => 16.3.2
  react-native: 0.55.0 => 0.55.0
## Description
`snapToInterval` is not implemented on android for vertical scroll view.

https://github.com/facebook/react-native/blob/8dc3ba0444c94d9bbb66295b5af885bff9b9cd34/Libraries/Components/ScrollView/ScrollView.js#L511

The official doc states the feature is actually implemented.

https://facebook.github.io/react-native/docs/scrollview.html#snaptointerval

**Comment by thecryptovalley** [comment]
How to merge the above commit to RN 0.56?
