### ISSUE TITLE
Unable to resolve module XXX from .... Module XXX does not exist in the Haste module map

### ISSUE THREAD

**Issue by dann1609** [facebook/react-native#19558]
## Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.0.0
  Yarn: Not Found
  npm: 5.0.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.1 AI-173.4697961

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

## Description

Basically I create a new react native project. Then I copy modules I want to package.json. Then I run nom install. when I tried to run my app. All of those modules made the  error "Unable to resolve module XXX from .... Module XXX does not exist in the Haste module map". So In order to work I tried to install one by one of those modules.  

## Steps to Reproduce

Create new app. Copy redux and react-navigation modules in package.json, run nom install and run app.
## Expected Behavior

ruin without problem
## Actual Behavior

Error screen with "Unable to resolve module XXX from .... Module XXX does not exist in the Haste module map" Where XXX is the module name.

**Comment by QinGuan2004** [comment]
To add modules you're supposed to run `npm install --save NAME` and not copy pasting the package name directly in package.json

If that still produces the error try restarting your Metro Packager Server and rerunning/reinstalling the app on the device

**Comment by dann1609** [comment]
@QinGuan2004 I have a question. If I copy code form a repository, package info is not only stored in package.json?

**Comment by anthonydelgado** [comment]
same issue.

**Comment by QinGuan2004** [comment]
@dann1609 all your dependencies should be from package.info, when you run ```npm install``` it should install dependencies from package.info
