### ISSUE TITLE
[Image] Null passed to a callee that requires a non-null argument

### ISSUE THREAD

**Issue by despairblue** [facebook/react-native#1955]
When upgrading my project to 0.8.0-rc I get:
```
.../node_modules/react-native/Libraries/Image/RCTDownloadTaskWrapper.m:65:49: Null passed to a callee that requires a non-null argument
```

I also get this for the UI Explorer on master, I don't get it if i checkout the tag 0.8.0-rc though :confused:

**Comment by sjmueller** [comment]
Same here.

**Comment by menetrier** [comment]
The patch has been submitted.

@sjmueller On my side, adding a completion handler didn't do it, the rct_completion handler did not fire.
I used the [- downloadTaskWithURL:](https://developer.apple.com/library/ios/documentation/Foundation/Reference/NSURLSession_class/#//apple_ref/occ/instm/NSURLSession/downloadTaskWithURL:) way.

**Comment by brentvatne** [comment]
This has been fixed!

**Comment by liuda101** [comment]
But the image can't load successfully
