### ISSUE TITLE
react-native link throws an exception with rn v 0.55.4

### ISSUE THREAD

**Issue by Dmytraw** [facebook/react-native#19565]
- [ ] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ ] Use the latest React Native version: https://github.com/facebook/react-native/releases
  - [x] Run `react-native info` in your terminal and paste its contents under "Environment"
  - [ ] Let us know how to reproduce the issue. Include a code sample, share a project, or
    share an app that reproduces the issue using https://snack.expo.io/

## Environment
```
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 10.1.0
  Yarn: 1.6.0
  npm: 6.0.1
  Watchman: 4.9.0
  Xcode: Xcode 9.4 Build version 9F1027a
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: ^16.3.1 => 16.3.1
  react-native: ^0.55.4 => 0.55.4
```

## Description
`react-native link` throws the following error
```
(node:8418) ExperimentalWarning: The fs.promises API is experimental
rnpm-install ERR! Something went wrong while linking. Error: Expected "/* Begin ", "/* End ", "\"", or [A-Za-z0-9_.] but "<" found. 
Please file an issue here: https://github.com/facebook/react-native/issues 
```

## Steps to Reproduce
1. `npm i`
2. `react-native link`

## Expected Behavior
Successful linking of packages

## Actual Behavior
Exception as described above

**Comment by Dmytraw** [comment]
Ive tried to update node and npm, it didnt help

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 10.3.0
  Yarn: 1.6.0
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4 Build version 9F1027a
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: ^16.3.1 => 16.3.1
  react-native: ^0.55.4 => 0.55.4

**Comment by hramos** [comment]
Is there a particular library you're linking? Or does this happen with all libraries you've tried?

**Comment by Dmytraw** [comment]
@hramos 
Hey)
I have only few - facebook sdk, react-native-linear-gradient. 
Maybe i should have mentioned that linking was working with previous version of RN before i ran `react-native-git-upgrade`.

**Comment by SimonErich** [comment]
I have the exact same error with 0.55.4 and to answer your question @hramos : For me it happens with every react-native link I call after the upgrade.
