### ISSUE TITLE
App doesn't run to completion with a mixture of promises and `new Function`

### ISSUE THREAD

**Issue by jlongster** [facebook/react-native#19572]
## Environment

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.11.1
  Yarn: 1.6.0
  npm: 4.6.1
  Watchman: 4.9.0
  Xcode: Xcode 9.4 Build version 9F1027a
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

## Description

I have code which constructs a dynamic function with `new Function` which executes asynchronous code. For some reason, it doesn't finish running, but pauses in the middle of execution, and then strangely continues execute when I interact with the screen. It seem to resume execution when any other JS code is run, like a gesture of a timer.

This code causes this behavior:

```js
function doSomething(str) {
  console.log('doSomething', str);
  return new Promise((resolve, reject) => {
    resolve();
  });
}

export default async function() {
  const code = `
    runMigration(async function() {
      await doSomething('foo1');
      await doSomething('foo2');
      await doSomething('foo3');
      await doSomething('foo4');
      await doSomething('foo5');
      await doSomething('foo6');
      await doSomething('foo7');
      await doSomething('foo8');
      await doSomething('foo9');
    });
  `;

  return new Promise((resolve, reject) => {
    const func = new Function('doSomething', 'runMigration', code);
    func(doSomething, asyncFunc => {
      asyncFunc().then(resolve, err => {
        console.log('Error applying JavaScript:', js);
        reject(err);
      });
    });
  });
}
```

This code will log to the console as it progresses. Check out this video for what happens: https://jlongster.com/s/rn-schedule-repro.mov

Here is a small repro which will run: https://github.com/jlongster/rn-scheduling-repro

## Steps to Reproduce

See above 

## Expected Behavior

It should print all the way to `foo9` on app startup and finish completion

## Actual Behavior

See above

**Comment by jlongster** [comment]
I took a shower and I know what the problem must be. The eval-ed code is not getting compiled by the packager, which I'm assuming compiles away async/await into something else. The eval-ed code is not being driven by RN like other async code is.

**Comment by jlongster** [comment]
@rmhartog Yep, post my comment before I saw yours. It doesn't execute in the global scope, but it does execute it outside of the current scope. React Native has its own version of promises? Well, that certainly explains it.

**Comment by rmhartog** [comment]
Yes, there are custom timers implemented so that they hook into the the bridge properly. Just updated my comment with a way to verify this behaviour. The function constructor creates a function in 'Global Scope' (https://developer.mozilla.org/nl/docs/Web/JavaScript/Reference/Global_Objects/Function), that is, separate from any polyfilled or overwritten timers.

**Comment by jlongster** [comment]
I didn't like the term "global scope" because I thought `new Function` created its own scope entirely separate from everything else (which is the whole reason I use it) and it would see global modifications like `x = 10`. But I think it might. The MDN page does use the word "global" and in fact your code snippet above returns `true`. So it is getting the same `Promise`, etc objects!

The issue though is that even though it gets the same objects, it's using native async/await which will always leverage the native async mechanism. Need to think of a different way to run this code.

**Comment by jlongster** [comment]
The best solution I can think of is instead of trying to eval this code, actually import it. React Native doesn't support dynamic requires (as far as I know) so that forces me to manually maintain a map of migration names to imported module (it's fine to import them all eagerly).

**Comment by jlongster** [comment]
Actually I can't do that because the migration directory is configurable, so the path to the module is dynamic. Might just need to avoid async/await in the migrations

**Comment by jlongster** [comment]
I fixed this by precompiling the JS files that I need to eval. Doing so gets rid of async/await and it ends up using the promises that React Native has installed instead.
