### ISSUE TITLE
React Native Scope Question.

### ISSUE THREAD

**Issue by techpanga** [facebook/react-native#19578]
## For Discussion

Hi All,

React Native got wide potential. And it's pluggable nature for wide combinations of features. 

Can React Native include the following features into core?

1. Background/LocationTracking , Speed, Heading etc.
2. Gyro/Sensors tracking.
3. Maps.
4. AR.
5. Camera.
6. Proximity.
7. Networking.
8. In Calls.

Relaying on Plugins for basic needs and updating every plugin whenever React Native library upgrades is not smooth development.

-Regards, dp.

**Comment by hramos** [comment]
I am not sure if these features belong in core. We're actually considering moving towards a slimmer core by moving out many of the "core" components that could just as easily be imported as modules. This would allow open source contributions to occur on these modules without necessarily worrying about the current "import to FB" process that prevents us from accepting as many PRs as we'd like.
