### ISSUE TITLE
Linking: iOS app Crashes when I try to open a file

### ISSUE THREAD

**Issue by GianniGM** [facebook/react-native#19575]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native version: https://github.com/facebook/react-native/releases
  - [x] Run `react-native info` in your terminal and paste its contents under "Environment"
  - [x] Let us know how to reproduce the issue. Include a code sample, share a project, or
    share an app that reproduces the issue using https://snack.expo.io/

## Environment
  OS:  macOS Sierra 10.12.6
  Node:  6.10.0
  Yarn:  1.2.1
  npm:  3.10.10
  Watchman:  4.7.0
  Xcode:  Xcode 9.1 Build version 9B55
  Android Studio:  3.1 AI-173.4720617

Packages: (wanted => installed)
  react: ^16.3.0-alpha.1 => 16.3.1
  react-native: 0.55.2 => 0.55.2

## Description
The app crashes when I try to open a local app PDF file using RNFS.DocumentDirectoryPath  

## Steps to Reproduce
```
const url = `${RNFS.DocumentDirectoryPath}/file.pdf`;

Linking.canOpenURL(url).
        then(supported => {
          if (!supported) {
            onError('Can\'t handle url: ' + url);
          } else {
            onSuccess(url);
            return Linking.openURL(url);
          }
        }).
        catch(err => console.error('An error occurred', err));
```

## Expected Behavior
Open a pdf File using an external app

## Actual Behavior
![simulator screen shot - iphone 6 - 2018-06-05 at 15 24 35](https://user-images.githubusercontent.com/5739601/40982010-946191da-68dc-11e8-9f4b-5daa9708d340.png)

**Comment by hramos** [comment]
Does it only crash when you use RNFS.DocumentDirectoryPath?

**Comment by GianniGM** [comment]
@hramos Hi! Unfortunately crashes also when I put a hardcoded path
