### ISSUE TITLE
[Bug] Strict mode does not allow function declarations in a lexically nested statement

### ISSUE THREAD

**Issue by jamesqo** [facebook/react-native#19582]
I'm not quite sure why this issue is appearing. It seems to happen currently whenever I open the app I'm debugging and select "Stop Remote JS Debugging" after shaking.

![screenshot_20180605-190730](https://user-images.githubusercontent.com/9159214/41007441-daf2db56-68f3-11e8-922e-3497313e1fd4.png)

When I visit the URL it refers to I get this blob: https://gist.githubusercontent.com/jamesqo/044cc1e4509e965af63007d603db1ef4/raw/784934ffc33be6f279575570c82dbaf69ed21ece/glob.json

It doesn't leave a stack trace of the location in the code where this occurs, so I assume the problem is with one of the JS scripts in the blob?

**Comment by designviacode** [comment]
similar issue here too :(
don't know how to make sense of this.
