### ISSUE TITLE
Image Component no working?

### ISSUE THREAD

**Issue by yulingyiyi** [facebook/react-native#19586]
## Environment
ios11.2  iponeX react-native0.55.3

## Description
<Image
           style={{width:200,height:300}}
                        source={{uri:'http://nimg-ts.jicai.com/image/mobile_img/banner/862f26c6-d673-4322-8c0e-6beac6d57a3c.jpeg'}}/>

## Steps to Reproduce
no working? it is ok in Android,but do not work in iOS. why?

**Comment by MacKentoch** [comment]
Same issue: RCTImage does not render anything
```
Environment:
  OS: macOS High Sierra 10.13.5
  Node: 8.11.1
  Yarn: 1.7.0
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4 Build version 9F1027a
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4
```

**Comment by betiol** [comment]
@MacKentoch 
I checked the image you are using and it does not exist.
Try this:

``` 
<Image
     source = {{uri: 'https://reactjs.org/logo-og.png'}}
     style = {width: 400, height: 400}}
/>
```

**Comment by MacKentoch** [comment]
OMG I'm so... 
I don't use `https://facebook.github.io/react/img/logo_og.png` but the uri I use does not work too.

Thank you @betiol , I feel like 😅(and gonna hide under my desk for the rest of the day 😂)

**Comment by betiol** [comment]
Haha happens. 😄

**Comment by hramos** [comment]
Closing as the original author did not respond with details.
