### ISSUE TITLE
Are Android Auto/Apple Carplay supported in RN or are they in the RoadMap?

### ISSUE THREAD

**Issue by vincenzovitale** [facebook/react-native#19585]
Are Android Auto/Apple Carplay supported in RN or are they in the RoadMap?

Thanks

**Comment by anthonydelgado** [comment]
That would be awesome

**Comment by nitaliano** [comment]
Has anyone tried to get RN running with Android Auto or Apple Carplay?

**Comment by mhdtouban** [comment]
duplicate of https://github.com/facebook/react-native/issues/19900
