### ISSUE TITLE
TvOS TabBarIOS Component Catch Menu Event

### ISSUE THREAD

**Issue by theasc** [facebook/react-native#19590]
## Environment
- Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.10.0
  Yarn: 1.7.0
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3.1 Build version 9E501
  Android Studio: Not Found

- Packages: (wanted => installed)
  react: ^16.3.0-alpha.2 => 16.3.0-alpha.2
  react-native: ^0.54.2 => 0.54.2

## Description
- The Issue is on TvOS
- Component **TabBarIOS** is catching menu event coming from the remote and I am unable to catch it on the first try (Need to press menu a second time to catch it) using TVEventHandler.

## Steps to Reproduce
- Press on the menu button while being inside TabBarIOS once ( The TabBarIOS catch it) 
- Try pressing a second time ( then the event is catched by TVEventHandler)

## Expected Behavior
- TVEventHandler catch it on the first try

## Actual Behavior
- TVEventHandler catch it on the second try

**Comment by dlowder-salesforce** [comment]
This is already being worked on in issue #18930.
