### ISSUE TITLE
[TextInput ][ Android ] fontStyle not updated on component re-render

### ISSUE THREAD

**Issue by ahetawal-p** [facebook/react-native#19592]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native version: https://github.com/facebook/react-native/releases
  - [x] Run `react-native info` in your terminal and paste its contents under "Environment"
 

## Environment
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.11.1
  Yarn: Not Found
  npm: 5.7.1
  Watchman: 4.7.0
  Xcode: Xcode 9.4 Build version 9F1027a
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

## Description
Applying `fontStyle` dynamically to a TextInput on **Android** doesn't reflect.

## Steps to Reproduce
Here is the sample render function
```
 const tester = this.state.enteredText.length == 0 ? {fontStyle:'italic'} : {fontStyle:'normal'}
    return (
      <View style={styles.container}>
        <TextInput
         onChangeText={txt => this.setState({enteredText: txt})}
         style={[styles.paragraph, tester]}
         placeholder={'This is a test'}
  />
      </View>
    );
```

## Expected Behavior
When user starts typing the `fontStyle` should be updated to `normal`

## Actual Behavior
The `fontStyle` always stick to `italic` even after the re-render of the TextInput has happened.

**Comment by dancherb** [comment]
Having the same issue with a redux-linked TextInput.

**Comment by mickadoua** [comment]
i have the same issue 
Others Styleq (e.g : color) are correctly applied  

If we come back to the same page, the Italic style is applied 

here is a video : 
[placeholder Italic.webm.zip](https://github.com/facebook/react-native/files/2385571/placeholder.Italic.webm.zip)

PS : The same style is applied to Text and TextInput component

**Comment by eleeffs** [comment]
I am also having similar issue. 

I am changing the style of the textInput once there is value then changing it back once the text field has been cleared.

The placeholder text is not fully updating the style. fontSize and color are working as @mickadoua mentioned but things like fontFamily or fontWeight are not changing the placeholder back to the original style.

**Comment by YangXiaomei** [comment]
I have the same issue.

It works on iOS:
![changetextfont](https://user-images.githubusercontent.com/8221990/47130063-7ac8b200-d2ca-11e8-8d0d-1c6e3da46342.gif)


But not works on Android:
![changetextfontandroid](https://user-images.githubusercontent.com/8221990/47130085-92a03600-d2ca-11e8-82ea-3acac83835f5.gif)
