### ISSUE TITLE
problem occurred  during react-native link react-native-vector-icons

### ISSUE THREAD

**Issue by Jopapy19** [facebook/react-native#19593]
$ react-native link react-native-vector-icons
Scanning folders for symlinks in /Users/annalundberg/Whereabouts/node_modules (23ms)
rnpm-install info Platform 'ios' module react-native-vector-icons is already linked
rnpm-install info Platform 'android' module react-native-vector-icons is already linked
rnpm-install info Linking assets to ios project
rnpm-install info Linking assets to android project
rnpm-install ERR! Something went wrong while linking. Error: EACCES: permission denied, unlink '/Users/annalundberg/Whereabouts/android/app/src/main/assets/fonts/Entypo.ttf'
Please file an issue here: https://github.com/facebook/react-native/issues

EACCES: permission denied, unlink '/Users/annalundberg/Whereabouts/android/app/src/main/assets/fonts/Entypo.ttf'

**Comment by bavachaucp0002** [comment]
some problem :((

**Comment by bavachaucp0002** [comment]
same problem :( .
