### ISSUE TITLE
Image.getSize(uri) not working

### ISSUE THREAD

**Issue by Paradox-AT** [facebook/react-native#19604]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native version: https://github.com/facebook/react-native/releases
  - [x] Run `react-native info` in your terminal and paste its contents under "Environment"
  - [x] Let us know how to reproduce the issue. Include a code sample, share a project, or
    share an app that reproduces the issue using https://snack.expo.io/

## Environment

  OS: Windows 10
  Node: 8.11.2
  Yarn: 1.6.0
  npm: 6.0.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.1.0.0 AI-173.4720617

## Description

Not able to use the static method of `Image` `getSize(uri)`

I tried the following syntax but with no success:
`Image.getSize("file:///storage/emulated/0/Download/Image.jpg")`
`Image.getSize("/storage/emulated/0/Download/Image.jpg")`
`Image.getSize("/sdcard/Download/Image.jpg")`

## Steps to Reproduce

`Image.getSize(uri)`

## Expected Behavior

Retrieve the width and height (in pixels) of an image prior to displaying it.

## Actual Behavior

Throws Warning:
`Failed to get size for image: file:///storage/emulated/0/Download/Image.jpg`

**Comment by hramos** [comment]
This seems to be working as intended. According to [the docs](http://facebook.github.io/react-native/docs/image.html#getsize), this method "Does not work for static image resources."

Your URIs appear to point to static image resources, the size of which you should be able to obtain in other ways. This method is intended for remote resources.

**Comment by Paradox-AT** [comment]
Hey @hramos can you tell me what are the other ways. The image is located in Downloads directory. I tried resolveAssetSource but with no success

**Comment by PeideAmonNg** [comment]
check if you have 'READ_EXTERNAL_STORAGE' and 'READ_INTERNAL_STORAGE' permissions in your AndroidManifest.

**Comment by rollsroyc3** [comment]
Ran into same issue and finally found `other ways`, couldn't get a local image that was being stored in Android storage directory. Came across this from eXist-FraGGer which worked perfectly.

https://github.com/eXist-FraGGer/react-native-image-size
