### ISSUE TITLE
npm ERR! 404 Not Found: react-native-sqlcipher-storage@latest

### ISSUE THREAD

**Issue by ruchita-android** [facebook/react-native#19602]
I am trying to install a plugin :  
npm install --save react-native-sqlcipher-storage
but it is throwing a 404 error
npm ERR! 404 Not Found: react-native-sqlcipher-storage@latest

## Environment
Windows 10 , Android React native

## Actual Behavior

I am trying to install a plugin :  
npm install --save react-native-sqlcipher-storage
reference from : https://github.com/axsy-dev/react-native-sqlcipher-storage
but it is throwing a 404 error
npm ERR! 404 Not Found: react-native-sqlcipher-storage@latest
<img width="711" alt="err" src="https://user-images.githubusercontent.com/35990904/41089474-831d245a-6a5f-11e8-8d94-1d0aeec9bcf6.PNG">

**Comment by hramos** [comment]
The error coming from the npm cli says the module does not exist. Closing as this is unrelated to React Native.
