### ISSUE TITLE
why we cannot supply any other values to it.

### ISSUE THREAD

**Issue by Shanie1331** [facebook/react-native#19600]
## For Discussion
https://github.com/facebook/react-native/blob/57919a3edd3d09f595224e0d92f95da1df75e884/Libraries/Components/Picker/PickerAndroid.android.js#L78

The only props that you can use for the Picker.Item are 
value: PropTypes.any,
label: PropTypes.string,
color: PropTypes.string

why we cannot supply any other values to it.

**Comment by hramos** [comment]
This is not the best place for this type of question.
