### ISSUE TITLE
npm ERR! 404 Not Found: react-native-sqlcipher-storage@latest

### ISSUE THREAD

**Issue by ruchita-android** [facebook/react-native#19603]
## For Discussion

I am trying to install a plugin :  
npm install --save react-native-sqlcipher-storage
reference from : https://github.com/axsy-dev/react-native-sqlcipher-storage
but it is throwing a 404 error
npm ERR! 404 Not Found: react-native-sqlcipher-storage@latest
<img width="711" alt="err" src="https://user-images.githubusercontent.com/35990904/41089522-a3f42ad4-6a5f-11e8-9e5d-9c6ae2630dc5.PNG">

**Comment by Paradox-AT** [comment]
It is because that lib is no longer present in npm repo.

You can still add => ```dependencies {
...
"react-native-sqlcipher-storage": "axsy-dev/react-native-sqlcipher-storage",
...
}``` in `package.json` and then do `npm install` or `yarn`. This will install that package for you
