### ISSUE TITLE
Xcode builds have over 450 warnings 

### ISSUE THREAD

**Issue by randyhill** [facebook/react-native#19628]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native version: https://github.com/facebook/react-native/releases
  - [x] Run `react-native info` in your terminal and paste its contents under "Environment"
  - [x] Let us know how to reproduce the issue. Include a code sample, share a project, or
    share an app that reproduces the issue using https://snack.expo.io/

## Environment
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 10.0.0
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4 Build version 9F1027a
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.0-alpha.2 => 16.3.0-alpha.2
  react-native: ^0.55.3 => 0.55.3

## Description
When building iOS app from react native project we get 451 compile warnings, all of which appear to be in the React Native objective C code.

## Steps to Reproduce
Build a react native project in XCode.

## Expected Behavior
There will be zero warnings. Warnings are a sign of poor coding practices, and even though many are just unused parameters, they can obscure very important warnings. Our own native code has warnings obscured by this long list of unfixed coding errors. And it makes finding compile errors in our code more difficult and tedious. 

## Actual Behavior
A mass of unfinished technical debt spewed across hundreds of lines of my build output.

**Comment by mannyhagman** [comment]
This has been a nightmare to deal with. I've tried so many things and spent an incredible amount of time trying to push a new release to the app store, with no success. I'm looking for any solution to get this release pushed.

**Comment by hramos** [comment]
As far as I am aware, these are standard Xcode warnings that show up with each Xcode release, e.g. they're recommendations for how your Xcode project settings should be updated. It only affects the base template used when you create a new project, and you should be able to deal with the same way you would with any regular Xcode project.

**Comment by rajivshah3** [comment]
@mannyhagman are you talking about errors (exclamation point inside a red octagon/stop sign)? 

Warnings such as the one below shouldn't be causing the build to fail: 
![image](https://user-images.githubusercontent.com/19519564/41247614-7a93583e-6d7c-11e8-9732-9ccac08fe958.png)

**Comment by rajivshah3** [comment]
@randyhill as a workaround, you can filter the issues for your own project and exclude the React warnings like this:

![image](https://user-images.githubusercontent.com/19519564/41247707-d30d76f2-6d7c-11e8-9e3a-e4712bd7b800.png)

**Comment by hramos** [comment]
We just released a new version, 0.56.0-rc, that should take care of a good number of these. Can you take a look?

**Comment by hramos** [comment]
Tracking all remaining warnings in https://github.com/facebook/react-native/issues/22609
