### ISSUE TITLE
Animated.ScrollView onScroll: native driver + js listener at the same time

### ISSUE THREAD

**Issue by slorber** [facebook/react-native#19623]
## For Discussion

Hi,

I've this usecase in my app:
- I need to implement a parallax scrollview (with native driver)
- I need to implement scroll-into-view feature on this scrollview, which requires access to the contentOffset. See the lib I published: https://github.com/slorber/react-native-scroll-into-view

Currently, the only way to get contentOffset is using an onScroll js listener. But as far as I know it's not possible to use both native driver event listener and js event listener, so I can only implement one of the above features at the same time :s

A solution would be for RN to permit to add a "composite" onScroll listener to support at the same time native driver usage + js listener.

There also was an issue to suggest to be able to retrieve that contentOffset imperatively but it was closed (https://github.com/facebook/react-native/issues/2215). CC @brentvatne who wanted an usecase for it.

**Comment by slorber** [comment]
I believe the issue contains all the relevant informations and the "no template" tag can be removed

**Comment by slorber** [comment]
I found a solution: there's a not very-known `Animated.forkEvent` which permit to merge a js listener to a user-provided `onScroll` prop (works with onScroll undefined/AnimatedEvent/js listener)

**Comment by evanjmg** [comment]
How do we use it? I don't see any examples and the types are very confusing

**Comment by slorber** [comment]
Here is an example: 
https://github.com/slorber/react-native-scroll-into-view/blob/133f0750800d25067fa40079ac9a58d341c21d22/src/hoc.tsx#L95
