### ISSUE TITLE
createAnimatedComponent should use forwardRef ?

### ISSUE THREAD

**Issue by slorber** [facebook/react-native#19650]
## For Discussion

Hi,

Currently createAnimatedComponent does not use forwardRef.
This is probably the case because we actually sometimes need access to the AnimatedComponent instance.

I propose to use `forwardRef` by default, and to use another prop like `animatedRef` to get a reference to the animated wrapper, as it is probably a less common usecase (not sure of that but it looks to me)

Currently, we need to call `getNode` on the animated component. This was added by @gre who seems to agree for using forwardRef by default (https://github.com/facebook/react-native/pull/9944#issuecomment-396199071)

This would simplify client code. 

For example in my case I created a ScrollView HOC [react-native-scroll-into-view](https://github.com/slorber/react-native-scroll-into-view), and it must work with both animated and normal scrollviews.

This forces me to provide a fragile implementation like this to be sure to I can use the ScrollView imperative methods to get the responder:

```js
  getScrollViewNode: ref => {
    if ( ref.getNode ) {
      return ref.getNode();
    }
    else {
      return ref;
    }
  };
```

**Comment by satya164** [comment]
FYI this will break all existing libraries which rely on `getNode` currently and they will need to be updated.

**Comment by TheSavior** [comment]
This probably makes sense but it would be useful to see a very small complete sample that will help us understand how this is being used and what value you are looking for from both of the refs you are proposing.

**Comment by satya164** [comment]
I don't think breaking all the libraries out there without any deprecation notice is a good idea.

> any library that want to migrate to forwardRef (react-intl, react-redux or anything else) will probably have to deal with a breaking change for that

Yeah, but react-native is not just a library, it's a framework. The change is more invasive and will break many libraries in its ecosystem. Whereas react-redux breaking this behavior will mostly require only the app code to be upgraded which is under user's control.

I'm not against change, but we need to figure out a proper deprecation cycle before changing the API.

**Comment by slorber** [comment]
yes I totally agree with that, here it's just to validate what we want in the future, I'm not asking for a breaking change right now :)

**Comment by TheSavior** [comment]
Got it, I understand better now. Thanks for helping me get there. I think I agree that we should have a supported way to get the underlying node, we just need a good plan. 👍

**Comment by gavrix** [comment]
There is a workaround to make `AnimatedComponent` that forwards ref of its wrapped component:
```
export default function createAnimatedComponentFrowardingRef<P, S>(Component: React.ComponentClass<P, S>) {
  return React.forwardRef<React.Component<P, S>, P>((props, ref) => {
    class Wrapper extends React.PureComponent<P, S> {
      render() {
        return <Component {...this.props} ref={ref} />
      }
    }
    const AnimatedWrapper = Animated.createAnimatedComponent(Wrapper)
    return <AnimatedWrapper {...props} />
  })
}
```

**Comment by cpojer** [comment]
I'm gonna close this, as the remaining discussion should probably be handled somewhere else (React repo?) and we aren't planning on changing this API on RN itself right now. If you feel strongly, please do come forward with a plan and start implementing it in PRs.

**Comment by nomi9995** [comment]
![forward](https://user-images.githubusercontent.com/36044436/55377844-36efff00-5530-11e9-96f5-293117a6cd27.png)

it is giving me this error @gavrix

**Comment by nomi9995** [comment]
you can use
`let getRef = this.refs.scroll.getNode();
    `
`getRef.function({ index: index });`
