### ISSUE TITLE
TouchableWithoutFeedback onLayout - Never called / triggered

### ISSUE THREAD

**Issue by MarkOSullivan94** [facebook/react-native#19657]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native version: https://github.com/facebook/react-native/releases
  - [x] Run `react-native info` in your terminal and paste its contents under "Environment"
  - [x] Let us know how to reproduce the issue. Include a code sample, share a project, or
    share an app that reproduces the issue using https://snack.expo.io/

## Environment

  OS: Linux 4.4
  Node: 9.4.0
  Yarn: Not Found
  npm: 6.1.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: ^16.3.1 => 16.4.0
  react-native: ^0.55.4 => 0.55.4

_Note: I actually have Android Studio installed, not sure why it states "Not Found"_

## Description

Trying to use onMeasure within View which is a child of TouchableWithoutFeedback so I can get the width of the View.

Unfortunately onLayout is never triggered and so I never see the console log mesage.

This does however work with TouchableOpacity as the parent component.

## Steps to Reproduce

Expo Snack: https://snack.expo.io/rJMkUQhl7

Or in case that doesn't work, the code for it is shown below.

```
import React, { Component } from 'react';
import {
  Text,
  View,
  StyleSheet,
  Modal,
  TouchableWithoutFeedback,
  Button,
} from 'react-native';
import { Constants } from 'expo';

// You can import from local files
import AssetExample from './components/AssetExample';

export default class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      showModel: false,
    };
  }

  showModel() {
    this.setState({
      showModel: true,
    });
  }

  hideModel() {
    this.setState({
      showModel: false,
    });
  }

  render() {
    return (
      <View style={styles.container}>
        <Modal
          visible={this.state.showModel}
          animationType={'fade'}
          onRequestClose={() => this.hideModel()}
          transparent>
          <TouchableWithoutFeedback onPress={() => this.hideModel()}>
            <View style={styles.modalBoxContainer}>
              <TouchableWithoutFeedback>
                <View
                  style={styles.modelBox}
                  onLayout={event => {
                    var { x, y, width, height } = event.nativeEvent.layout;
                    console.log('WIDTH: ' + width);
                  }}>
                  <Text>THIS IS AN EXAMPLE</Text>
                </View>
              </TouchableWithoutFeedback>
            </View>
          </TouchableWithoutFeedback>
        </Modal>
        <Button
          title="Show Model"
          onPress={() => {
            // test
            this.showModel();
          }}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: Constants.statusBarHeight,
    backgroundColor: '#ecf0f1',
  },
  modalBoxContainer: {
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
  },
  modelBox: {
    backgroundColor: '#fafafa',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 5,
    paddingTop: 5,
    paddingBottom: 5,
    width: 200,
    height: 100,
  },
});
```

## Expected Behavior

Console would have the width of the View.

## Actual Behavior

Nothing printed.

**Comment by TheSavior** [comment]
Why do you need the two `TouchableWithoutFeedback` elements?

Also, as you can see from the implementation of `TouchableWithoutFeedback`, it clones its child and sets `onLayout` to the onLayout prop you pass to `TouchableWithoutFeedback`.

Try either this:
```
<TouchableWithoutFeedback onPress={() => this.hideModel()}>
  <View style={styles.modalBoxContainer}>
    <View
      style={styles.modelBox}
      onLayout={event => {
        var { x, y, width, height } = event.nativeEvent.layout;
        console.log('WIDTH: ' + width);
      }}>
      <Text>THIS IS AN EXAMPLE</Text>
    </View>
  </View>
</TouchableWithoutFeedback>
```
Or this:

```
<TouchableWithoutFeedback onPress={() => this.hideModel()}>
  <View style={styles.modalBoxContainer}>
    <TouchableWithoutFeedback onLayout={event => {
      var { x, y, width, height } = event.nativeEvent.layout;
      console.log('WIDTH: ' + width);
    }}>
      <View style={styles.modelBox}>
        <Text>THIS IS AN EXAMPLE</Text>
      </View>
    </TouchableWithoutFeedback>
  </View>
</TouchableWithoutFeedback>
```

**Comment by MarkOSullivan94** [comment]
> Also, as you can see from the implementation of TouchableWithoutFeedback, it clones its child and sets onLayout to the onLayout prop you pass to TouchableWithoutFeedback.

Why is this behaviour different from TouchableOpacity?

**Comment by TheSavior** [comment]
Great question. As far as we can tell, not for a good reason. This is something that has bit us a bunch internally and we plan to consolidate and make them consistent. We are hoping to do this within the next few releases.

**Comment by MarkOSullivan94** [comment]
That's why I opened this, felt it must have been a bug if TouchableWithoutFeedback doesn't work but TouchableOpacity does
