### ISSUE TITLE
My react-native/Libraries/ReactNative folder is different from the Github repo

### ISSUE THREAD

**Issue by CharlieOrlando** [facebook/react-native#19659]
<img width="991" alt="screen shot 2018-06-11 at 6 00 50 pm" src="https://user-images.githubusercontent.com/25595536/41261468-7af18966-6da1-11e8-86d3-c54dee2d9bb3.png">

<img width="268" alt="screen shot 2018-06-11 at 5 56 43 pm" src="https://user-images.githubusercontent.com/25595536/41261445-59cc6fe4-6da1-11e8-8167-505bb21d34f2.png">

I am trying to use takeSnapshot.js, but it is missing from my react-native/Libraries/ReactNative folder. I am also missing a couple of the other files and have some additional ones that are not on the Github repo.

I'm running the most current version of react-native (0.55.4).

**Comment by hramos** [comment]
That file is not part of 0.55.4. Your GitHub screenshot is of master, but you're using a snapshot of the repository as it was back when 0.55.4 was cut.

**Comment by CharlieOrlando** [comment]
Ah. Thanks. 

I see there's a 0.56 stable version, but when I ran react-native-git-upgrade, it didn't upgrade from 0.55.4. Can I just run the upgrade again and specify the 0.56 stable version?

**Comment by hramos** [comment]
0.56-stable is in release candidate phase. It should hit stable in July. You can use it today by upgrading to `0.56.0-rc` explicitly.
