### ISSUE TITLE
Wrong code for babel-preset-react-native@5.0.1 published (rn 0.56.0-rc)

### ISSUE THREAD

**Issue by johakr** [facebook/react-native#19666]
It seems like the published version of babel-preset-react-native@5.0.1 doesn't match the code of https://github.com/facebook/react-native/tree/v0.56.0-rc/babel-preset, (Depending on babel 7.0.0-beta.40 instead of babel 7.0.0-beta.40 and metro-babel7-plugin-react-transform@0.34 instead of metro-babel7-plugin-react-transform@0.38.1).

This leads to an issue in react-native@0.56.0-rc depending on babel 7.0.0-beta.47 and metro-babel7-plugin-react-transform@0.38.1.

**Comment by johakr** [comment]
I think there is no need for the Issue Template in this case, since it's not really related to my environment and can be fixed by just publishing the right code under the right version tag to npm.

**Comment by hramos** [comment]
cc @pvdz

**Comment by johakr** [comment]
@kelset 5.0.0 also depends on outdated, (i.e. incompatible with `react-native@0.56.0-rc`) version of babel / metro-babel. My understanding is that this _"next version"_ actually is `0.56.0-rc` (which is currently unusable due to this issue).

Would be great if someone of the core team could clarify.

**Comment by kelset** [comment]
~Ah yeah sorry, ok let me try to clarify: my understanding is that:~

~* 0.56.0 rc should be coupled with babel-preset 5.0.0~
~* 0.5x will be coupled with 5.0.1~

~But I may be wrong (need to wait on Peter to confirm for that) - and yeah not sure about the Metro deps.~ (I'm 99% sure I'm wrong)

One more thing, have you tried requiring explicitly the new version of Babel? I mean writing
```
    "@babel/core": "7.0.0-beta.47",
    "babel-core": "7.0.0-bridge.0",
    "babel-preset-react-native": "5.0.1",
```

Yeah it's a bit weird but Babel is undergoing a lot of name changes ([read more about it here](https://babeljs.io/docs/en/next/v7-migration.html)).

And side question, can you also try to "force" the deps via [yarn resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/)?

**Comment by pvdz** [comment]
There's definitely something awry with 5.0.1 in terms of beta.40, I just can't figure out what. Perhaps republishing the package will resolve it. I'll try to push a 5.0.2 with the same contents later. Could be that something got corrupted. I'll also take a look at the yarn lockfile to ensure it's clean from beta.40 there too.

**Comment by johakr** [comment]
@pvdz Thanks for publishing 5.0.2. I guess, this ticket can be closed now.
