### ISSUE TITLE
unsupport to use Object.defineProperty to change the 'name' of a function.

### ISSUE THREAD

**Issue by fishmwei** [facebook/react-native#19674]
## Environment
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.4.0
  Yarn: 1.3.2
  npm: 6.0.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4
## Description

Cannot change the name of  anonymous function; like this: 

```
function _genSynMethod(moduleName, methodName) {
    return Object.defineProperty(
        function () {
           ... 
           }, 'name', {value:methodName}) ;
}
```

## Steps to Reproduce

just call function  _genSynMethod

## Expected Behavior
running normal , just like iOS.

## Actual Behavior

![2](https://user-images.githubusercontent.com/14887502/41291125-6749feda-6e81-11e8-8953-3743bf55d0f9.png)

**Comment by fishmwei** [comment]
@hramos 
Android does not support to use  `Object.defineProperty` to change the 'name' of a function.

**Comment by fishmwei** [comment]
For Discussion

**Comment by hramos** [comment]
This will likely be fixed once we move on from the old JSC used in Android: https://github.com/facebook/react-native/issues/19737

**Comment by hramos** [comment]
0.59 is now out. If anyone happens to verify this on 0.59 and it's still an issue, please let us know.
