### ISSUE TITLE
Latest react-native app doesn't work ":CFBundleIdentifier", Does Not Exist

### ISSUE THREAD

**Issue by ekkis** [facebook/react-native#19683]
this very long thread: https://github.com/facebook/react-native/issues/7308 was closed without a solution.  I have the same problem with the most modern environment

## Environment
Environment:
  OS: OS X El Capitan 10.11.6
  Node: 9.10.1
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 8.2.1 Build version 8C1002
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

## Description
the application never gets deployed to the simulator, as it should.  I've checked to make sure the port isn't the problem and have read through the aforementioned thread but find no solutions

## Steps to Reproduce
```
react-native init test
cd test
react-native run-ios

```
## Expected Behavior
a running application

## Actual Behavior

the build generates the following error:

> ** BUILD FAILED **
> 
> The following build commands failed:
> 	CompileC /Users/ekkis/dev/test/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64/RCTShadowView+Internal.o Views/RCTShadowView+Internal.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
> (1 failure)
> 
> Installing build/Build/Products/Debug-iphonesimulator/test.app
> An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
> Failed to install the requested application
> An application bundle was not found at the provided path.
> Provide a valid path to the desired application bundle.
> Print: Entry, ":CFBundleIdentifier", Does Not Exist
> 
> Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/test.app/Info.plist
> Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by ekkis** [comment]
thanks.  I added the information.  I've also found something curious: the previous thread was closed because the OP found that something was tying up the port.  when I run the `run-ios` command, it automatically spawns a process Metro Bundler on that port.  the previous thread was closed because apparently killing that process solves the problem. in my case it does not.  it breaks regardless the Metro Bundler is already running

**Comment by hramos** [comment]
The `CFBundleIdentifier` is a red herring, it basically means your project did not build "for reasons".

It looks like you can repro this on a new project using `react-native init`, which as of this writing would result on a project that depends on `0.55.4`. You're using Xcode 8, however. Updating to Xcode 9 will likely fix your issue. We just updated the docs to make it clear Xcode 9 is required in recent releases.

**Comment by GuillaumeLachaud** [comment]
Running in the same issue. @hramos Is there a place in the documentation where I can check what is the latest RN version that builds correctly on Xcode 8 ?

**Comment by ekkis** [comment]
an upgrade to XCode 9.4.1 fixed the problem.  of course, I had to upgrade to HighSierra for that :( thanks everyone for the help

**Comment by SilencerWeb** [comment]
Is there any way how to fix this problem without updating macOS to high sierra and update xcode to 9.4.1? It is not a good solution, you know

**Comment by ekkis** [comment]
@SilencerWeb you can't upgrade XCode unless you upgrade the OS

**Comment by SilencerWeb** [comment]
@ekkis i see, it sucks that you need high sierra for working with react-native >=0.56 :(
