### ISSUE TITLE
Allow control over AsyncStorage location on iOS

### ISSUE THREAD

**Issue by sam1463** [facebook/react-native#19692]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native version: https://github.com/facebook/react-native/releases
  - [x] Run `react-native info` in your terminal and paste its contents under "Environment"
  - [x] Let us know how to reproduce the issue. Include a code sample, share a project, or
    share an app that reproduces the issue using https://snack.expo.io/

## Environment
Environment:
  OS: macOS High Sierra 10.13.5
  Node: 9.4.0
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.2 => 0.52.2

## Description

Currently, AsyncStorage stores data in the Documents directory on iOS. However, as discussed in [this issue](https://github.com/facebook/react-native/issues/2477), [this abandoned PR](https://github.com/facebook/react-native/pull/4561), and [this abandoned PR](https://github.com/facebook/react-native/pull/10697), there should be an option to store elsewhere, as this location is not appropriate for non-user-created content, as it is visible for apps that enable file sharing with iTunes or the Files app on iOS.

## Steps to Reproduce
This is the case on AsyncStorage on all versions of react-native to my knowledge.

## Expected Behavior
Some sort of control over the location in which AsyncStorage stores data, so that it will not be exported to iTunes, viewable via the Files app, etc. on iOS

## Actual Behavior
AsyncStorage saves to the Documents directory.

**Comment by timotei-cliqz** [comment]
Any progress on this? @hramos @adamivancza

**Comment by timotei-cliqz** [comment]
@hramos what is wrong with @adamivancza's pull request? The code looks good. The two test cases that fail don't seem to be related to the code.

**Comment by hramos** [comment]
It probably won't scale if I have to look at test failures on every PR. I'd check if the tests are failing on master first, and go from there.

**Comment by timotei-cliqz** [comment]
@hramos thanks for taking the time to look at this!

**Comment by hramos** [comment]
We use Circle CI, and you can see the state of tests on master at any time here: https://circleci.com/gh/facebook/react-native/tree/master

**Comment by timotei-cliqz** [comment]
@hramos Thank you. I appreciate it!

**Comment by jovanxua** [comment]
what is the status of this? thanks.

**Comment by aethernet** [comment]
Any update?

**Comment by cpojer** [comment]
This issue has been moved to react-native-community/react-native-async-storage#13.
