### ISSUE TITLE
Performance issue with SectionList when sections include a lot of items

### ISSUE THREAD

**Issue by climam** [facebook/react-native#19698]
## Environment
React native 0.54.2 iOS/Android

## Description
When SectionList is used with a lot of items for each section, the list is very slowly rendered. 
The reason for this is that SectionList implementation provide to the underlying VirtualizedList 1 component per section. This component include the section header and all the items of that section.

## Steps to Reproduce
Render a SectionList with 3 sections, each section having 100 items.

## Expected Behavior
The 300 items are rendered gradually when the list is being scrolled (VirtualizedList behavior)

## Actual Behavior
The 300 items are directly rendered making the rendering of the SectionList very slow.

**Comment by climam** [comment]
I solved my issue by providing to the renderItem of SectionList a FlatList to render the items of my sections.

**Comment by samsonroy** [comment]
Having the same issue here.Can you please let me know the better implementation of renderItem. @climam

**Comment by climam** [comment]
Hi @samsonroy, I was making a mistake treating all my items of a section as one single item and rendering them all at once. 
After changing that, performance were better. However, I was still not really satisfied with the performance. I tried[ react-native-large-list](https://github.com/bolan9999/react-native-largelist) and it was way better.

**Comment by samsonroy** [comment]
I have sectionlist to display menuDetails:
`	<SectionList
	sections={this.render()}			
	/>`
````
render = () => {
this.sectionData = [];
this.sectionData.push({
			id: 0,
			title: TITLE1,
			data: data,
			renderItem: ({ item, index }) => {
						return this.renderItem();
					}
		});
		this.sectionData.push({
		        id: 1,
			title: TITLE2,
			data:data2,
			renderItem: ({ item, index }) => {
						return this.renderItem();
					}
				});
			}
		}

		this.sectionData.push({
		        id: 2,
			title: TITLE3,
			data:data3,
			renderItem: ({ item, index }) => {
						return this.renderItem();
					}
				});
			}
		}
        return this.sectionData;
}
``` 

I am currently doing it this way. When i have 100+ items it becomes very slow! Any idea on this to improve it? 
@climam

**Comment by dulmandakh** [comment]
@samsonroy why call this.renderItem in every section? If items are same just pass this.renderItem to SectionList.

```jsx
<SectionList
  sections={sectionData}
  renderItem={this.renderItem}
/>
```

Also please check if you are triggering re-rendering while scrolling, because you're preparing **sections** during render. Please consider move it to somewhere else.

**Comment by samsonroy** [comment]
@dulmandakh @climam  All the items  items are directly rendered  and not only on scrolling. Any idea why this is happening?

**Comment by dulmandakh** [comment]
@samsonroy Personally, I cannot say anything from the provided snippet. I suspect that there is a bug or issue in your code, than in RN. In my project I have list of more than 100+ items, and it's working just fine. I would suggest you to learn more about Reactjs, React Native.
