### ISSUE TITLE
string `startsWith` produces false negatives

### ISSUE THREAD

**Issue by armadillojim** [facebook/react-native#19699]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native version: https://github.com/facebook/react-native/releases
  - [x] Run `react-native info` in your terminal and paste its contents under "Environment"
  - [x] Let us know how to reproduce the issue. Include a code sample, share a project, or
    share an app that reproduces the issue using https://snack.expo.io/

## Environment
```
Environment:
  OS: Linux 4.9
  Node: 8.11.2
  Yarn: 1.6.0
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: ~0.55.2 => 0.55.4
```

## Description
I have a component that was filtering a list of suggestions, and I stumbled on a strange bug.  The list was mysteriously not including some items it should have, and I eventually figured out that the Javascript engine was producing incorrect results on strings that had UTF8 characters in them.  That is, `someString.startsWith(someOtherString)` was producing `false` when it shouldn't have.

## Steps to Reproduce
```
console.log('mother'.startsWith('m'));
console.log('mother\'s'.startsWith('m'));
console.log('mother’s'.startsWith('m'));
```
Note the Unicode apostrophe in the last case.

If it makes a difference, I used `create-react-native-app` to bootstrap my app, and I'm running it in Expo.

## Expected Behavior
```
true
true
true
```

## Actual Behavior
```
true
true
false
```

**Comment by TheSavior** [comment]
I get `true` for all three use cases:

![screen shot 2018-06-13 at 3 43 09 pm](https://user-images.githubusercontent.com/249164/41382321-8516f842-6f20-11e8-8daf-eed7ee1280e1.png)

**Comment by armadillojim** [comment]
@TheSavior Thanks for the suggestion.  However, I don't see any difference in the version of JavaScriptCore between 0.55 and 0.56.  Both https://github.com/facebook/react-native/blob/0.55-stable/ReactAndroid/build.gradle and https://github.com/facebook/react-native/blob/0.56-stable/ReactAndroid/build.gradle use WebKit/webkit/38b15a3ba3c1b0798f2036f7cea36ffdc096202e.

Are you using react-native in development mode?  I ask because I see in the documentation that that uses V8 instead of JavaScriptCore.  I also tried this in Chrome's JavaScript console (which uses V8), and got the expected result (3 `true`s).  Or am I confused about that?  I'm using create-react-native-app and expo, and I'm testing on an Android device (and not a simulator).

**Comment by TheSavior** [comment]
Ah, yeah, this sounds like a bug in JSC. 

https://github.com/facebook/react-native/issues/19737

**Comment by armadillojim** [comment]
Ok, thanks!

Yeah I saw that JavaScriptCore hasn't been updated since the beginning of react-native.  That'll be a bear to upgrade carefully.  D'oh.  Oh well.

Maybe it'd be worth noting in the "JavaScript Environment" documentation page which version is in use (and its release date)?

**Comment by MrPluto** [comment]
seem like startswith cant work well if a str contain  Chinese

**Comment by dmaksimovic** [comment]
```
const text = "abcde 😎"   // note the emoji
text.startsWith('abc'); // <-- returns false
```

**Comment by armadillojim** [comment]
@MrPluto and @dmaksimovic, React Native 0.56, 0.57, and 0.58 all continued to use the same JSC.  They finally updated it, though.  See https://github.com/facebook/react-native/issues/19737#issuecomment-454205028

I double checked, and you can see the change live now in 0.59.  https://github.com/facebook/react-native/blob/0.58-stable/ReactAndroid/build.gradle#L148 shows the old JSC, and https://github.com/facebook/react-native/blob/0.59-stable/ReactAndroid/build.gradle#L136 is now evergreen.

I haven't tried upgrading yet myself, but it seems that should fix this issue.
