### ISSUE TITLE
Enabling Geolocation

### ISSUE THREAD

**Issue by jnak** [facebook/react-native#197]
Hey,

When I try to use the Geolocation, I get:

```
message: undefined is not an object (evaluating 'RCTLocationObserver.getCurrentPosition')"
```

It seems that require('NativeModules').LocationObserver returns undefined in Geolocation.ios.js
I did add this to my info.plist:

```
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>You need to add NSLocationWhenInUseUsageDescription key in Info.plist to enable geolocation, otherwise it is going to *fail silently*!</string>
```

Am I missing something ?

Thanks!
J

**Comment by everystone** [comment]
What about when developing for Android on Windows?

**Comment by naoisegolden** [comment]
If you are working with Cocoapods, adding `RCTGeolocation` to the `Podfile` and then running `pod install` again should do the trick.

```
source 'https://github.com/CocoaPods/Specs.git'
pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'Core',
  'RCTGeolocation',
  'RCTImage',
  'RCTNetwork',
  'RCTText',
  'RCTWebSocket'
]
```

**Comment by mikelambert** [comment]
Why was there is no mention of any of this on https://facebook.github.io/react-native/docs/geolocation.html ? :(

**Comment by mobilesite** [comment]
@naoisegolden    I also got this error and i'm using pod too, but i can't fix this bug with the method you reminded. When I use ```pod search RCTGeolocation``` to search it, nothing can be find in the repos. Could you do me a favor to analyze about it? Thank you very much!

**Comment by smokinjoe** [comment]
@a2 is there a solution for Xcode 7.3.1?  I was able to follow until selecting the library.  I don't have libRCTGeolocation.a available.
![screen shot 2016-10-27 at 10 53 48 am](https://cloud.githubusercontent.com/assets/827945/19778934/bd612be4-9c33-11e6-93e5-d0af9c42b11a.png)
