### ISSUE TITLE
Unable to generate build after project initialization. ADB throwing error

### ISSUE THREAD

**Issue by VVBthe1** [facebook/react-native#19708]
Environment:
  OS: Linux 4.4
  Node: 6.14.3
  Yarn: Not Found
  npm: 3.10.10
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

OS: Ubuntu 16.04
Android Debug Bridge version: 1.0.40
ADB Version: 4797878
React Native Version: 0.55.4
Emulator: Genymotion
Debug Device: Nexus 5 Android 6

Here is my output:
$ react-native run-android
Scanning folders for symlinks in /home/vivekb/reactnative/tech_stack/node_modules (27ms)
JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug)...
Incremental java compilation is an incubating feature.
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42301Library UP-TO-DATE
:app:prepareComFacebookFbuiTextlayoutbuilderTextlayoutbuilder100Library UP-TO-DATE
:app:prepareComFacebookFrescoDrawee130Library UP-TO-DATE
:app:prepareComFacebookFrescoFbcore130Library UP-TO-DATE
:app:prepareComFacebookFrescoFresco130Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipeline130Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipelineBase130Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipelineOkhttp3130Library UP-TO-DATE
:app:prepareComFacebookReactReactNative0554Library UP-TO-DATE
:app:prepareComFacebookSoloaderSoloader010Library UP-TO-DATE
:app:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:mergeDebugShaders UP-TO-DATE
:app:compileDebugShaders UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:bundleDebugJsAndAssets SKIPPED
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
:app:compileDebugJavaWithJavac UP-TO-DATE
:app:compileDebugNdk UP-TO-DATE
:app:compileDebugSources UP-TO-DATE
:app:transformClassesWithDexForDebug UP-TO-DATE
:app:mergeDebugJniLibFolders UP-TO-DATE
:app:transformNative_libsWithMergeJniLibsForDebug UP-TO-DATE
:app:processDebugJavaRes UP-TO-DATE
:app:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
:app:validateSigningDebug
:app:packageDebug UP-TO-DATE
:app:assembleDebug UP-TO-DATE
:app:installDebug
02:28:58 E/adb: adb server version (39) doesn't match this client (40); killing...
02:28:58 E/adb: ADB server didn't ACK
02:28:58 E/adb: Full server startup log: /tmp/adb.1002.log
02:28:58 E/adb: Server had pid: 12578
02:28:58 E/ddms: '/home/vivekb/Android/Sdk/platform-tools/adb,start-server' failed -- run manually if necessary
02:28:58 E/adb: --- adb starting (pid 12578) ---
02:28:58 E/adb: adb I 06-14 14:28:58 12578 12578 main.cpp:56] Android Debug Bridge version 1.0.40
02:28:58 E/adb: adb I 06-14 14:28:58 12578 12578 main.cpp:56] Version 4797878
02:28:58 E/adb: adb I 06-14 14:28:58 12578 12578 main.cpp:56] Installed as /home/vivekb/Android/Sdk/platform-tools/adb
02:28:58 E/adb: adb I 06-14 14:28:58 12578 12578 main.cpp:56] 
02:28:58 E/adb: adb I 06-14 14:28:58 12578 12578 auth.cpp:421] adb_auth_init...
02:28:58 E/adb: adb I 06-14 14:28:58 12578 12578 auth.cpp:174] read_key_file '/home/vivekb/.android/adbkey'...
02:28:58 E/adb: adb I 06-14 14:28:58 12578 12578 auth.cpp:396] adb_auth_inotify_init...
02:28:58 E/adb: adb I 06-14 14:28:58 12578 12584 transport.cpp:103] 078e866ee0ad06d3: read thread spawning
02:28:58 E/adb: adb I 06-14 14:28:58 12578 12585 transport.cpp:116] 078e866ee0ad06d3: write thread spawning
02:28:58 E/adb: adb I 06-14 14:28:58 12578 12578 auth.cpp:472] Calling send_auth_response
02:28:58 E/adb: adb I 06-14 14:28:58 12578 12578 adb.cpp:145] 078e866ee0ad06d3: offline
02:28:58 E/adb: adb server killed by remote request
02:28:58 E/adb: adb I 06-14 14:28:58 12578 12578 transport.cpp:159] BlockingConnectionAdapter(078e866ee0ad06d3): stopping
02:28:58 E/adb: adb I 06-14 14:28:58 12578 12584 transport.cpp:107] 078e866ee0ad06d3: read failed: Invalid argument
02:28:58 E/adb: adb I 06-14 14:28:58 12578 12578 transport.cpp:177] BlockingConnectionAdapter(078e866ee0ad06d3): stopped
:app:installDebug FAILED
02:28:58 E/adb: 
02:28:58 E/adb: * failed to start daemon
02:28:58 E/adb: error: cannot connect to daemon

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:installDebug'.
> com.android.builder.testing.api.DeviceException: Could not create ADB Bridge. ADB location: /home/vivekb/Android/Sdk/platform-tools/adb

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 12.78 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

When I look for adb processes it shows something like this:
$ ps auwx | grep adb
vivekb   12588  0.0  0.0 331664  3736 ?        Ssl  14:28   0:00 adb -L tcp:5037 fork-server server --reply-fd 4
vivekb   12600  0.0  0.0  28268  3224 ?        Sl   14:29   0:00 /home/vivekb/genymotion/tools/adb -s 192.168.56.101:5555 shell
vivekb   12601  0.0  0.0  20072  3288 ?        S    14:29   0:00 /home/vivekb/genymotion/tools/adb -s 192.168.56.101:5555 logcat -v time
vivekb   12687  0.0  0.0  14232   824 pts/2    S+   14:30   0:00 grep --color=auto adb

after killing the process or firing "adb kill-server" adb server automatically starts after some time.

Stuck here as can't install the development app onto emulator or device.

Please help.

**Comment by VVBthe1** [comment]
Updated with react-native info output

**Comment by tarasovg** [comment]
[#8401](https://github.com/facebook/react-native/issues/8401#issuecomment-344628512) helped me.

**Comment by skoob13** [comment]
[#8401](https://github.com/facebook/react-native/issues/8401#issuecomment-344628512) helped me.
