### ISSUE TITLE
Add --noflow option to react native cli's 'init' command.

### ISSUE THREAD

**Issue by StasD** [facebook/react-native#19702]
## For Discussion

Is it possible to add an option, say, --noflow, to react native cli's 'init' command?
When used, the cli would produce project files which look similar to those on your [frontpage](https://facebook.github.io/react-native/), free from any "flow" code... :)
Or, even better, make this default behavior, and add the --flow option to create files with 'flow'.

**Comment by hramos** [comment]
The CLI has been moved to https://github.com/react-native-community/react-native-cli
