### ISSUE TITLE
Horizontal Flatlist within vertical FlatList focus on TV

### ISSUE THREAD

**Issue by stevenchenn** [facebook/react-native#19700]
## Environment
AndroidTV/FireOS Emulator Android7.1.1, React Native 0.55

## Description
I've implemented a multi dimension list view on React Native with a few horizontal FlatLists within a verticle FlatList. Everything displays correctly. However, when I move my focus all the way to the end of a row, the focus will automatically go to the row below when I try to go right (already at the end of the row). Simiarly, if I'm at the beginning of the row, focus will go to the row above if i try to go left.

Is there a solution to prevent this and make sure that focus will stop when it reaches the ends of a flatlist?

## Steps to Reproduce
Render a FlatList vertically with each row being another horizontal FlatList. Scroll to end of a row, try to move RIGHT and focus would go down to the next row. If we go to front of a row and try to move LEFT, focus would go to above row.

## Expected Behavior
Expected behavior should be none since we're at the ends of the current row.

## Actual Behavior
Focus goes to the next row if at the backend of a row and previous row if at the frontend of a row.

**Comment by stevenchenn** [comment]
Environment:
  OS: macOS Sierra 10.12.6
  Node: 9.11.1
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.3 => 0.55.3

**Comment by stevenchenn** [comment]
There was no answer to the problem on Stackoverflow/Google

**Comment by reidisaki** [comment]
i think i saw your question on Stackoverflow and it got removed.   I added it here:
https://stackoverflow.com/questions/51504320/react-native-flatlist-androidtv-focus-issue

I have hte same issue.
