### ISSUE TITLE
Custom component added in container state array not rendering in release mode 

### ISSUE THREAD

**Issue by Devid2727** [facebook/react-native#19713]
Hi Team,
i want to add component one above another in one screen, so i have maintained one array inside parent container. Whenever user click on button  i will add one component inside state array  and once state update it will automatically render call and render next view, but when i add third component in state , the component will add properly but its not showing on screen. this thing happen only in release mode. in debug mode its work properly, i dont understand whats the problem in release mode. 

Below some same code i have added 
```
//First Click
const view = this.getView1();
    const array = this.state.viewStack;
    array.push(view);
    this.setState({
      viewStack: array,
    });

```
   
```
//Second  Click
const view = this.getView2();
    const array = this.state.viewStack;
    array.push(view);
    this.setState({
      viewStack: array,
    });
```
```
//Third  Click
const view = this.getView3();
    const array = this.state.viewStack;
    array.push(view);
    this.setState({
      viewStack: array
    });
```

Please let me know if anyone face same issue.

**Comment by hramos** [comment]
Please use one of the provided issue templates.

**Comment by Devid2727** [comment]
Thanks hrams, I have resolved this issue.
