### ISSUE TITLE
[TouchHandler] touchesCancelled not called due to subclassing UIGestureRecognizer

### ISSUE THREAD

**Issue by paramaggarwal** [facebook/react-native#1971]
I'm still in the process of debugging here, but sharing my understanding till now. I have a `UIPanGestureRecognizer` on a view which contains an `RCTRootView`. When I pan the view, it moves the entire `RCTRootView` to the side to reveal a sidebar.

Now while doing so, taps are recorded inside the `RCTRootView`. I've been debugging and this is because `touchesCancelled` never gets called on `RCTTouchHandler` which is a subclass of `UIGestureRecognizer`. Further digging revealed (not completely 100% sure here) that a gesture recogniser continues to get touch events till it actually changes its state to `Failed` or `Cancelled`. This is because the recognizer might still be interested in the events. I can't figure out a way to have it accept `touchCancelled` events yet.

I have a reproducible sample demo of the issue here: https://github.com/paramaggarwal/gesture-issue-demo. (Clone, `npm install` and run.) There are two boxes on screen that can be dragged around. Both also recognise taps and change color - notice that the React one takes both panning and tapping together.

I'm trying out a possible solution that does not subclass a gesture recogniser.

**Comment by brentvatne** [comment]
Hey @paramaggarwal, most likely you won't hear much from the team for a while on this as they have other priorities, but I commend you for the awesome report :smile:

If you find out any more details a follow up would be great!
