### ISSUE TITLE
SectionList sticky headers drift around when scrolling to the ends

### ISSUE THREAD

**Issue by esprehn** [facebook/react-native#19725]
- [x ] Review the documentation: https://facebook.github.io/react-native
  - [ x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Run `react-native info` in your terminal and paste its contents here.

Environment:
  OS: macOS High Sierra 10.13.5
  Node: 8.9.4
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.55.0 => 0.55.0

## Description
We have a SectionList with sticky headers that's also inverted. The sticky headers seem to jump up and down when scrolling. Sometimes they also drift out of the viewport and then snap back to become stuck.

## Reproducible Demo
Let us know how to reproduce the issue. Include a code sample, share a project, or     share an app that reproduces the issue using https://snack.expo.io/. Please follow the guidelines for providing a MCVE: https://stackoverflow.com/help/mcve

**Comment by esprehn** [comment]
This seems to be the rest of getItemHeight reporting incorrect values for some items. The manifestation of that is badly broken scrolling, jumpiness and headers that drift. I'd be nice if VirtualizedList had some debug mode that reported errors when the heights disagreed with each other.

**Comment by CharlieOrlando** [comment]
@esprehn So did you end up finding a solution? I'm experiencing the same issue, as are other people... https://github.com/facebook/react-native/issues/15445

**Comment by Taylor123** [comment]
@CharlieOrlando have you been able to solve this at all? Seeing the StickyHeader flicker each time i call `scrollToOffset` on the FlatList.

This seems to only happen on Android, and works perfectly on iOS. Need to use the StickyHeaders since I can't move the components outside the list
