### ISSUE TITLE
Supporting custom fonts the Android Way

### ISSUE THREAD

**Issue by dulmandakh** [facebook/react-native#19736]
# For Discussion

Android SDK 26 introduced easy way to support custom fonts, where users define font family using XML and use it with ResourcesCompat.getFont(context, R.font.myfont). Read https://developer.android.com/guide/topics/ui/look-and-feel/fonts-in-xml

Current React Native support for custom fonts on Android implemented in ReactFontManager and CustomStyleSpan, and it's hard to use font weights other than bold and regular (normal), like medium, light etc. To use custom font weights on Android, I have to specify font file name without extension in fontFamily of style, which breaks iOS apps. Therefore, I check the platform in JS to support both Android and iOS, and set fontFamily and fontWeight accordingly.

Adding support for Android Way seemed trivial with fallback to old way.

1. check if font resource is exists
2. if exists, get resource id and get typeface using ResourcesCompat.getFont(context, <resource id>)
3. else fallback to old way (ReactFontManager)

But, font styling of Text in Android implemented in ReactBaseTextShadowNode, which have no access to context. So, I think support custom fonts the Android Way will require refactoring of Text and decide if RN will support the OLD WAY.

**Please consider this for FabricUIManager**

CC: @hramos @mdvacca

**Comment by ryanwhitney** [comment]
Is there currently any way to reference fonts in android by their appropriate weight? (Not by putting the weight in FontFamily.)

**Comment by hramos** [comment]
@dulmandakh now that we have https://github.com/react-native-community/discussions-and-proposals in place, perhaps that's a better place for this type of discussion?

**Comment by vjsingh** [comment]
It appears to me that any font-weight on android above '400' just gives bold text. Looking for a way to support in-between font weights of 500 or 600.

**Comment by fallenner** [comment]
RN 0.57.4  android  default font thickening !!   why????

**Comment by cpojer** [comment]
Thanks for sending a PR for this @dulmandakh, this feature is currently landing in #23865 so I'm gonna close this issue.

**Comment by chrisbobbe** [comment]
Just a note to say that https://github.com/facebook/react-native/pull/23865 was reverted in https://github.com/facebook/react-native/commit/eb40b09bfd0e617912663fb056d0bdea85ce0c2f, so maybe this issue should be reopened.

**Comment by dulmandakh** [comment]
it's landed in another PR and commit :D

**Comment by chrisbobbe** [comment]
Ooh, nice! For posterity, it looks like that PR was https://github.com/facebook/react-native/pull/24595 and the commit was https://github.com/facebook/react-native/commit/fd6386a07eb75a8ec16b1384a3e5827dea520b64.
