### ISSUE TITLE
where is console.log for ios without remote debug?

### ISSUE THREAD

**Issue by fatfatson** [facebook/react-native#19745]
## Environment
Run `react-native info` in your terminal and paste its contents here.
Environment:
  OS: macOS Sierra 10.12.6
  Node: 9.11.1
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: Not Found
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.4.0 => 16.4.0
  react-native: ^0.55.4 => 0.55.4

## Description

`react-native log-ios` shows nothing about console.log
sometime I don't like to use chrome for remote debug especially when run in real device,
I could not found anything by console.log in either `log-ios` output or the macos's consoleApp.

**Comment by charpeni** [comment]
You can see `console.log` through Xcode output while running the app without having to use chrome for remote debugging.

**Comment by Annihil** [comment]
`react-native log-ios` command is broken since version 0.5+,  
I wrote a small npm package to use it again.

    npm i -g react-native-log-ios
    react-native-log-ios <XCode Project Name>

**Comment by dholbrook86** [comment]
@Annihil Your npm package is just what the doctor ordered! Exactly what I needed! Thank you!
