### ISSUE TITLE
Feature Request: onCopy and onPaste for Clipboard API

### ISSUE THREAD

**Issue by MohamadKh75** [facebook/react-native#19759]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
Environment:
  OS: Windows 8.1
  Node: 8.11.2
  Yarn: 1.7.0
  npm: 6.1.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  2.3.0.0 AI-162.3871768

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4
```

## Description
Need handlers to be called when the user **copy** or **paste** using `Clipborard` API.
e.g. `onCopy` and `onPaste` props for `<TextInput>` or `<Text selectable >`

BTW it's been asked before #18551 but it's `closed` without being solved!
Also #13940 may be related somehow!

**Comment by Contrevien** [comment]
+1

**Comment by hramos** [comment]
Thanks for the feature request. We're only tracking bugs in the repo. To add a new feature, please send a pull request.
