### ISSUE TITLE
Some Style Props for nested Text component is not working

### ISSUE THREAD

**Issue by MohamadKh75** [facebook/react-native#19757]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
Environment:
  OS: Windows 8.1
  Node: 8.11.2
  Yarn: 1.7.0
  npm: 6.1.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  2.3.0.0 AI-162.3871768

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4
```

## Description
Some style props such as `borderBottomWidth `- `marginVertical `- `width` is NOT working for the nested Text components!

## Reproducible Demo
```
import React, { Component } from "react";
import { Text, View, StyleSheet } from "react-native";

export default class App extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Text>
          <Text>First</Text>
          <Text style={{ borderBottomWidth: 1 }}>Second</Text>
          <Text>Third</Text>
        </Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ECF0F1"
  }
});
```

**Comment by FabianoLothor** [comment]
+1

**Comment by hramos** [comment]
"not working" is not very descriptive. Can you elaborate?

**Comment by MohamadKh75** [comment]
@hramos the `borderBottomWidth: 1` has no effect for nested `<Text>`.
And so `margin: 10` or `width: 100` and some more.

**Comment by FabianoLothor** [comment]
I'm with a problem about this issue.

```
<View>
<Text>
<Text onLayout={e => {console.log("this isn't triggered!")}}>{"foo"}</Text>
</Text>
</View>
```

**Comment by hramos** [comment]
@FabianoLothor you might want to open a new issue to describe what you're encountering.

**Comment by MohamadKh75** [comment]
@hramos i guess it's somehow related to this issue! Some props of **Nested** `<Text>` component have no effect!

**Comment by MohamadKh75** [comment]
@hramos would you please add the related labels?

**Comment by hramos** [comment]
Which labels?

**Comment by lwinkyawmyat** [comment]
`borderBottomWidth`, `marginVertical`, `width` aren't Text component style props. You can see full list of **Text Style Props** by clicking [here](https://facebook.github.io/react-native/docs/text-style-props#props).

`Text Style Props` is working in nested Text component. Can you check demo [here](https://snack.expo.io/@lwinkyawmyat/nested-text-style-props-demo)?

**Comment by MohamadKh75** [comment]
@lwinkyawmyat then why i can use `borderBottomWidth` for a non-nested `<Text>`?

take a look:

```
import React, { Component } from "react";
import { Text, View, StyleSheet } from "react-native";

export default class App extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Text>
          <Text>First</Text>
          <Text style={{ borderBottomWidth: 3 }}>Second</Text>  {/* no effect */}
          <Text>Third</Text>
        </Text>

        <Text style={{ borderBottomWidth: 3 }}>Fourth</Text> {/* effected */}
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ECF0F1"
  }
});
```

**Comment by lwinkyawmyat** [comment]
> borderBottomWidth, marginVertical, width aren't Text component style props. 

Sorry for my mistake. Actually, Text component's style props is support `View Style Props`.

Text component has [limited  style inheritance](https://facebook.github.io/react-native/docs/text#limited-style-inheritance).

**Comment by MohamadKh75** [comment]
So you mean i can't use `style={{ borderBottomWidth: 3 }}` for a nested `<Text>`?

By the way, i can't find the **limited style inheritance** section in the docs.

**Comment by lwinkyawmyat** [comment]
Yes. Currently, nested `<Text />` component has [limited style inheritance](https://facebook.github.io/react-native/docs/text#limited-style-inheritance). I was found **feature request** post. you can check [here](https://react-native.canny.io/feature-requests/p/richer-styling-options-for-nested-text).

If you want to fix your problem. Please try it as follows(a quick way).
```javascript
<View>
  <Text style={[ styles.textContainer]}>First</Text>
  <Text style={[ styles.textContainer, { borderBottomWidth: 3 } ]}>Second</Text>
  <Text style={[ styles.textContainer, styles.textStyleThree ]}>Third</Text>
</View>
```

**Comment by MohamadKh75** [comment]
Then we have to wait for implementation of that feature request!
Thanks for you description and temporary solution 😁

**Comment by anoopmm** [comment]
@muham

> Then we have to wait for implementation of that feature request!
> Thanks for you description and temporary solution 😁

is there any workaround?
