### ISSUE TITLE
Image onLoad called twice on rerender

### ISSUE THREAD

**Issue by nikolas7892** [facebook/react-native#19765]
## Environment
Environment:
  OS: macOS High Sierra 10.13.5
  Node: 9.4.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.4.0 => 16.4.1
  react-native: ~0.54.4 => 0.54.4

## Description
Any time that a file re renders, the source={{uri '...'}} of the <Image /> refetches the image from the url even though the image had been already fetched..

I know this because visually the image flickers due to the refetch... and the onLoad / onProgress is recalled multiple times.. 

How can I limit the amount of fetch calls for an Image component to only once if already fetched?

**Comment by betiol** [comment]
Try use `React.PureComponent`
