### ISSUE TITLE
Is it possible to draw view in front of keyboard?

### ISSUE THREAD

**Issue by dooboolab** [facebook/react-native#19771]
I want to make UI like imessage.
<img width="376" alt="screen shot 2018-06-17 at 11 56 03 pm" src="https://user-images.githubusercontent.com/27461460/41509129-22bb9ce4-728a-11e8-95b3-3b06045c3415.png">
<img width="380" alt="screen shot 2018-06-17 at 11 56 09 pm" src="https://user-images.githubusercontent.com/27461460/41509130-2620d1d8-728a-11e8-927e-204283a8c15e.png">

<img width="372" alt="screen shot 2018-06-17 at 11 55 26 pm" src="https://user-images.githubusercontent.com/27461460/41509131-298bb6e4-728a-11e8-9bfc-7bed292d6a81.png">
<img width="375" alt="screen shot 2018-06-17 at 11 55 40 pm" src="https://user-images.githubusercontent.com/27461460/41509132-2a714ba0-728a-11e8-89fd-b0c368decf6a.png">

I don't want the `TextInput` to close and show bottom component when clicking on the `smile icon`. However, bottom view doesn't come in front of keyboard even I changed the zIndex to 9999. How is this possible?

**Comment by tiempham** [comment]
@dooboolab You can caculated keyboard height first and draw a view at the bottom of the screen
