### ISSUE TITLE
Expected to find at least one react renderer.

### ISSUE THREAD

**Issue by atishoo** [facebook/react-native#19782]
![image](https://user-images.githubusercontent.com/7723403/41519399-69a46b5c-72fa-11e8-89d0-a0ca4a1f4f3f.png)

RN 0.55, android 8.1 or android 6

I jsut truned on inspector . when I tried to tap something , this error appeared.

**Comment by oneroundseven** [comment]
same problem
Android 6.0.
RN: 0.55.4

**Comment by Vabery** [comment]
I've resolved this issue by adding flex: 1 to the top parent element in the hierarchy.

**Comment by farzer** [comment]
@Vabery no use in my problem.

also meet this problem

Android 6.0
RN: 0.55.4

**Comment by yasir-netlinks** [comment]
Hi guys, I am having the same problem , anyone found a solution for this ?

**Comment by fungilation** [comment]
This is still happening on 0.57. Not on tapping all components but some, when Inspector is toggled on in dev.

**Comment by golakmmt** [comment]
> I've resolved this issue by adding flex: 1 to the top parent element in the hierarchy.

Issue resolved. Thanks!

**Comment by AugustoAleGon** [comment]
@Vabery Thanks man you save me.

**Comment by fcolon** [comment]
> I've resolved this issue by adding flex: 1 to the top parent element in the hierarchy.

I'm running into this issue now and this suggested workaround isn't working
