### ISSUE TITLE
Why a sub <Text> don't trigger the onLayout event?

### ISSUE THREAD

**Issue by FabianoLothor** [facebook/react-native#19785]
I'm with a issue about the onLayout event

A Code
```
<View>
  <Text>
    <Text onLayout={e => {console.log("this isn't triggered!")}}>{"foo"}</Text>
  </Text>
</View>
```

B Code
```
<View>
  <Text onLayout={e => {console.log("here the event it is called, but I need call in a SubText")}}>{"foo"}</Text>
</View>
```

**Comment by FabianoLothor** [comment]
@hramos are you kidding me!?

Here: https://github.com/facebook/react-native/issues/19757#issuecomment-397841834

You ask me to open a issue about this!

And I open a SO problem about that to many days ago.

Well, good job You is doing here my friend. Clap, clap!

**Comment by hramos** [comment]
Your issue does not make use of any of the provided templates. Please read through the instructions before opening a new issue:

<img width="715" alt="screen shot 2018-06-18 at 10 43 55 am" src="https://user-images.githubusercontent.com/165856/41552778-b5896a74-72e4-11e8-8e4e-44c08080bd23.png">

You want to use the first template to report an issue.

**Comment by FabianoLothor** [comment]
Ok dude, you are the best!

Clap, clap!

The open source will go far with you!
