### ISSUE TITLE
[Touchable] Customizing "press rect offset" of touchable components

### ISSUE THREAD

**Issue by ide** [facebook/react-native#198]
The press-rect offset defines a box around a touchable component in which a touch still counts. I'd like to be able to customize this box (specifically set the press-rect offset to (0,0,0,0)) by exposing it as a prop. Looking for suggestions for what to name the prop, or maybe there is already a term for this in the HCI literature.

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by coderdave** [comment]
I like the idea of defining an area around a touchable component where the touch still counts. What's the way to handle this now? Just increase the size and padding which could potentially break the design?

**Comment by ide** [comment]
That's a bit different since that increases the area that you can tap to start a touch. This issue is about customizing an enclosing box in which a touch is retained but not necessarily started.
