### ISSUE TITLE
Can't find variable: Promise on react-native 0.56.0-rc2 release build

### ISSUE THREAD

**Issue by francisco-sanchez-molina** [facebook/react-native#19806]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases
## Environment
Run `react-native info` in your terminal and paste its contents here.

Scanning folders for symlinks in /Users/xxx/node_modules (16ms)

  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.4
      CPU: x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
      Memory: 25.53 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.1 - ~/.nvm/versions/node/v8.11.1/bin/node
      Yarn: yarn install v0.22.0
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 31.50s. - /usr/local/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.11.1/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 27.0.1, 27.0.2, 27.0.3
        API Levels: 23, 24, 25, 26, 27
    IDEs:
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.3.2 => 16.3.2
      react-native: 0.56.0-rc.2 => 0.56.0-rc.2
## Description

Ios App crash on release configuration setup (`react-native run-ios --configuration Release`)

`Jun 19 14:39:49 silver xxx[10026]: *** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: Can't find variable: Promise (/Users/xxxx/Library/Developer/CoreSimulator/Devices/68A9BE18-20F4-4E67-A4F5-0BE26E9117A0/data/Containers/Bundle/Application/D4F542F8-E577-4260-96B1-65C9AD91F2D4/xxxx/main.jsbundle:820)', reason: 'Unhandled JS Exception: Can't find variable: Promise (/Users/xxxx/Librar...'`

`react-native run-ios` works well

## Reproducible Demo

`react-native run-ios --configuration Release`

**Comment by viniychuk** [comment]
Got the same issue in `react-native 0.56.0-rc2`, but my error is with "fetch" variable. Update to the `node 10.4.1.` didn't help. Debug configuration works fine, but Release doesn't.

**Comment by eshikerya** [comment]
same issue but with message `Unhandled JS Exception: Can't find variable: regeneratorRuntime`

**Comment by TheSavior** [comment]
Can you see if moving these two lines: 

```
const ReactNativeVersionCheck = require('ReactNativeVersionCheck');
ReactNativeVersionCheck.checkVersions();
```
in [InitializeCore](https://github.com/facebook/react-native/blob/master/Libraries/Core/InitializeCore.js#L81-L82)

to be below the [timerSetup](https://github.com/facebook/react-native/blob/master/Libraries/Core/InitializeCore.js#L101-L104) fixes this crash?

**Comment by eshikerya** [comment]
@TheSavior moved down under line `defineLazyTimer('cancelIdleCallback');`still got same issue:
`Unhandled JS Exception: Can't find variable: regeneratorRuntime`

**Comment by kelset** [comment]
Closing this in favour of #19827 since even OP is moving the conv forward over there
