### ISSUE TITLE
wrong param order of function enqueueNativeCall in MessageQueue.js file

### ISSUE THREAD

**Issue by hyice** [facebook/react-native#19801]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.9.0
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4670197

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

## Description
While I'm reading the source code of MessageQueue.js, I found this part of code is quite confusing.

In MessageQueue.js file's `enqueueNativeCall` function, onFail is pushed to params before onSucc: 
```js
enqueueNativeCall(
    moduleID: number,
    methodID: number,
    params: any[],
    onFail: ?Function,
    onSucc: ?Function,
  ) {
  ...
  onFail && params.push(this._callID << 1);
  onSucc && params.push((this._callID << 1) | 1);
  ...
}
```

But in iOS's RCTModuleMethod.mm file, the order of this two params is reversed in `processMethodSignature` method:
```objective-c
   } else if ([typeName isEqualToString:@"RCTPromiseResolveBlock"]) {
      RCTAssert(i == numberOfArguments - 2,
                @"The RCTPromiseResolveBlock must be the second to last parameter in %@",
                [self methodName]);
      BLOCK_CASE((id result), {
        [bridge enqueueCallback:json args:result ? @[result] : @[]];
      });
    } else if ([typeName isEqualToString:@"RCTPromiseRejectBlock"]) {
      RCTAssert(i == numberOfArguments - 1,
                @"The RCTPromiseRejectBlock must be the last parameter in %@",
                [self methodName]);
      BLOCK_CASE((NSString *code, NSString *message, NSError *error), {
        NSDictionary *errorJSON = RCTJSErrorFromCodeMessageAndNSError(code, message, error);
        [bridge enqueueCallback:json args:@[errorJSON]];
      });
    }
```

So, I go back to javascript code to see how is function `enqueueNativeCall` called, I found two usages:
```javascript
  if (type === 'promise') {
    fn = function(...args: Array<any>) {
      return new Promise((resolve, reject) => {
        BatchedBridge.enqueueNativeCall(moduleID, methodID, args,
          (data) => resolve(data),
          (errorData) => reject(createErrorFromErrorData(errorData)));
      });
    };
  } else if (type === 'sync') {
    ...
  } else {
    fn = function(...args: Array<any>) {
      const lastArg = args.length > 0 ? args[args.length - 1] : null;
      const secondLastArg = args.length > 1 ? args[args.length - 2] : null;
      const hasSuccessCallback = typeof lastArg === 'function';
      const hasErrorCallback = typeof secondLastArg === 'function';
      hasErrorCallback && invariant(
        hasSuccessCallback,
        'Cannot have a non-function arg after a function arg.'
      );
      const onSuccess = hasSuccessCallback ? lastArg : null;
      const onFail = hasErrorCallback ? secondLastArg : null;
      const callbackCount = hasSuccessCallback + hasErrorCallback;
      args = args.slice(0, args.length - callbackCount);
      BatchedBridge.enqueueNativeCall(moduleID, methodID, args, onFail, onSuccess);
    };
  }
```

In the first case, resolve and reject function are passed to `enqueueNativeCall` function in the reversed order. In the second case, functions actually are not supposed to be fail or success callback. 

According to this two case, I think the order of this two params should be reversed in function `enqueueNativeCall`.

## Reproducible Demo
Don't need demo

**Comment by vovkasm** [comment]
Good catch! Probably code to work with `enqueueNativeCall` was added long before the type definition and signature always was dynamic... Oh... spagetti-code...

I think it should be fixed.

**Comment by kelset** [comment]
Closing as stale. Please open a new issue if issue still occur.
