### ISSUE TITLE
[solved] Undefined symbols for architecture x86_64 [ ios ] and transformDexArchiveWithDexMergerForDebug FAILED [android]

### ISSUE THREAD

**Issue by ALYREZA** [facebook/react-native#19805]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.9.4
  Yarn: 1.7.0
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4
```

## Description
I updated form version 0.53.0 to 0.55.4 but this error happen.

## Reproducible Demo
ios:
![console](https://image.ibb.co/hO4D9d/Screen_Shot_2018_06_19_at_16_51_42.png)
android:
![console](https://image.ibb.co/kYo9Xy/Screen_Shot_2018_06_19_at_17_17_35.png)

**Comment by vovkasm** [comment]
iOS error is most probably from one of extensions you are using, try searching for RCCManager (is it from this **deprecated** project https://github.com/wix/react-native-controllers?)...

**Comment by ALYREZA** [comment]
I deleted ios and android folder then upgraded react native again, problem disappeared.
