### ISSUE TITLE
Unexpected token ) with React Native 0.56.0-rc.2

### ISSUE THREAD

**Issue by SupriyaKalghatgi** [facebook/react-native#19819]
![image](https://user-images.githubusercontent.com/13464885/41651555-74625b94-749e-11e8-898a-9b6e5ee3561b.png)

**Comment by SupriyaKalghatgi** [comment]
I then get this
![simulator screen shot - iphone 7 - 2018-06-20 at 15 32 20](https://user-images.githubusercontent.com/13464885/41651909-5a3b5c9c-749f-11e8-8f6a-e19c153b61e8.png)

**Comment by gogulanareshkw** [comment]
Hi @SupriyaKalghatgi , please help me to resolve compatibilty issue.

"dependencies": {
"@babel/core": "^7.0.0-beta.55",
"@babel/preset-env": "^7.0.0-beta.55",
"@babel/preset-react": "^7.0.0-beta.55",
"native-base": "^2.6.1",
"react": "^16.4.1",
"react-native": "^0.55.4",
"react-native-code-push": "^5.4.1",
"react-native-vector-icons": "^4.6.0",
},
"devDependencies": {
"babel-eslint": "^6.1.2",
"babel-jest": "^23.4.2",
"babel-preset-react-native": "^4.0.0",
"chai": "^3.5.0",
"eslint": "^3.5.0",
"eslint-config-airbnb": "^11.1.0",
"eslint-plugin-import": "^1.14.0",
"eslint-plugin-jsx-a11y": "^2.2.1",
"eslint-plugin-react": "^6.2.0",
"eslint-plugin-react-native": "^2.0.0",
"jest": "17.0.0",
"jest-react-native": "17.0.0",
"mocha": "^2.5.3",
},


![image](https://user-images.githubusercontent.com/40063274/43506764-b9131944-9588-11e8-8f40-9d975677cff7.png)
