### ISSUE TITLE
Establish VPN connection inside app

### ISSUE THREAD

**Issue by Peretz30** [facebook/react-native#19816]
---

# For Discussion

Is there a way to establish VPN connection inside app? There is nothing about that in docs, but native class to work with VPN exists in Android and called VpnService and NetworkExtension for iOS.

**Comment by geoker** [comment]
Any @Peretz30  updates on this issue?

**Comment by Peretz30** [comment]
@geoker unfortunately, no. 😔

**Comment by hramos** [comment]
Hey, the Discussion template is meant for long-form discussions about React Native. This looks like a request for help. Please take a look at http://facebook.github.io/react-native/en/help.html for a list of help resources.

**Comment by fthrhmn2** [comment]
any update on this? @Peretz30

**Comment by Peretz30** [comment]
@fthrhmn2 nope

**Comment by BayCo** [comment]
@Peretz30 how we can solve this? did you made research?
