### ISSUE TITLE
Geolocation getCurrentLocation crashing on iOS

### ISSUE THREAD

**Issue by jgfidelis** [facebook/react-native#19829]
Relevant code:
```
export const getGeoLocation = async (options?: Object): Promise<?GeoLocation> => {
  return new Promise((resolve, reject) => {
    navigator.geolocation.getCurrentPosition(
      (position: GeoLocation) => {
        resolve(position);
      },
      error => {
        reject(error);
      },
      {
        enableHighAccuracy: Platform.OS !== 'android',
        timeout: Platform.OS === 'android' ? 10000 : 5000,
        maximumAge: 1000,
        ...options,
      },
    );
  });
};
```

## Environment
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 10.4.0
  Yarn: 1.7.0
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.0 => 0.53.0

Only happens on real devices and on iOS

## Description
The app crashes when calling `navigator.geolocation.getCurrentPosition`. It probably crashes on native code, since the JS code is inside a try catch and it still closes the app.

On our Info.plist we have:
`NSLocationAlwaysAndWhenInUseUsageDescription`, `NSLocationWhenInUseUsageDescription` and `NSLocationAlwaysUsageDescription`.
Started happening after adding the `NSLocationAlwaysAndWhenInUseUsageDescription` key, I believe.

On Capabilities -> Background Mode we have turned on `Location Updates`.

On the first time it happens OK, the permission popup appears and everything works as expected.

Happens even if user gave always permission. From the second time and forward it crashes. Are we doing something wrong? I think it is permission related.

**Comment by tappyy** [comment]
Did you manage to solve this? I am looking to call getCurrentLocation() while app is in the background but only seems to be working while app is in foreground. I have added `NSLocationAlwaysAndWhenInUseUsageDescription` and `NSLocationWhenInUseUsageDescription` to my info.plist.
