### ISSUE TITLE
Android: Programmatically changing focus from one TextInput to another causes Keyboard flicker

### ISSUE THREAD

**Issue by praveenav** [facebook/react-native#19824]
### Environment
  OS: Linux 4.15
  Node: 10.4.1
  npm: 6.1.0

### Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

## Description
I have a simple form with few TextInput fields. I am using onSubmitEditing and ref.current.focus() to shift focus from one TextInput to another. Focus should change when I press the Return key of onscreen keyboard. Keyboard flickers during this transition.
If I transition from one TextInput to another manually everything works fine. I tested the same with Android Native code using android:imeoptions="actionnext". If works perfectly.
There is no issue with iPhone at all.

## Demo
Note: First two transition in this demo are done by pressing Return key of onscreen keyboard. Keyboard flickers. Next three transition are done manually by tapping on the individual TextInput fields. These work fine.

![keyboardflickerbug](https://user-images.githubusercontent.com/6316188/41663921-28315562-74c2-11e8-84d5-536eefdcca85.gif)

## Code
```javascript
import React, { Component } from "react";
import { TextInput, View, Text } from "react-native";

export default class App extends Component {
  constructor(props) {
    super(props);
    this.a = React.createRef();
    this.b = React.createRef();
    this.c = React.createRef();
    this.d = React.createRef();
    this.e = React.createRef();
  }

  render() {
    return (
      <View>
        <Text>React Native Playground</Text>
        <TextInput
          ref={this.a}
          onSubmitEditing={() => this.b.current.focus()}
          placeholder="input a"
        />
        <TextInput
          ref={this.b}
          onSubmitEditing={() => this.c.current.focus()}
          placeholder="input b"
        />
        <TextInput
          ref={this.c}
          onSubmitEditing={() => this.d.current.focus()}
          placeholder="input c"
        />
        <TextInput
          ref={this.d}
          onSubmitEditing={() => this.e.current.focus()}
          placeholder="input d"
        />
        <TextInput
          ref={this.e}
          onSubmitEditing={() => this.a.current.focus()}
          placeholder="input e"
        />
      </View>
    );
  }
}
```

**Comment by maxim-c** [comment]
you should add blurOnSubmit={false} to you TextInput,
and for some versions, i think 0.55.4 too, you need also add returnKeyType='next'.

https://facebook.github.io/react-native/docs/textinput.html#bluronsubmit
https://facebook.github.io/react-native/docs/textinput.html#returnkeytype

**Comment by praveenav** [comment]
Thank you very much @maxim-c 
I just added blurOnSubmit={false}
It works perfectly now.
