### ISSUE TITLE
[Packager] Double inclusion of different modules with the same names

### ISSUE THREAD

**Issue by ide** [facebook/react-native#1983]
I noticed two different copies of invariant in my bundle, both defined with the same name. With my setup I manually run the packager, which is at `node_modules/react-native/packager/packager.sh`. The other copy of invariant is coming either from `node_modules/redux/node_modules/invariant/browser.js` or `node_modules/react-redux/node_modules/invariant/browser.js`. The latter copy should be scoped but it looks like the Haste docblock in it is taking precedence -- removing the docblock fixes the issue.

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/packager-double-inclusion-of-different-modules-with-the-same-names
