### ISSUE TITLE
Nested <Text/> ignores allowFontScaling={false}

### ISSUE THREAD

**Issue by MIREX** [facebook/react-native#19833]
## Environment:
  **OS**: macOS High Sierra 10.13.6
  **Node**: 10.4.1
  **Yarn**: 1.7.0
  **npm**: 6.1.0
  **Watchman**: 4.9.0
  **Xcode**: Xcode 9.4.1 Build version 9F2000
  **Android Studio**: 3.1 AI-173.4819257

### Packages: (wanted => installed)
  **react**: 16.3.0-alpha.1 => 16.3.0-alpha.1
  **react-native**: 0.54.3 => 0.54.3

> The same issue with RN v0.55.4 and others

## Description
Project is created via `react-native init`
I use `Text.defaultProps.allowFontScaling = false` to disable text scaling anywhere in project. It works well. But when use nested texts on Android, this props doesn't work on children even if I pass `allowFontScaling={false}` directly

I tried to create Expo Snack Example, but it works with CRNA.

## Reproducible Demo
```
<Text allowFontScaling={false}>
    <Text allowFontScaling={false}>
        This text ignores allowFontScaling
    <Text/>
    <Text allowFontScaling={false}>
        And this too
    <Text/>
<Text/>
```

**Comment by MohamadKh75** [comment]
Same issue here for other props! #19757

**Comment by gevorg94** [comment]
This is still an issue!

**Comment by NelGarbuzova** [comment]
I have this bug too.

**Comment by roysG** [comment]
Same for me

**Comment by anoopmm** [comment]
is there any update? I have still on 0.58.3.
