### ISSUE TITLE
Execution failed for task ':app:transformClassesWithDexForDebug'.

### ISSUE THREAD

**Issue by AibiTi** [facebook/react-native#19842]
- [√] Review the documentation: https://facebook.github.io/react-native
  - [√] Search for existing issues: https://github.com/facebook/react-native/issues
  - [√] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
  OS: Windows 7
  Node: 9.9.0
  Yarn: 1.7.0
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

## Description

> react-native run-android

![16530713385768](https://user-images.githubusercontent.com/40224479/41753916-c271afd2-7602-11e8-9680-8f24240f66cb.png)

## Reproducible Demo
nothing

**Comment by gengjiawen** [comment]
you imporrt the same library twice, this is not an issue with react native.

**Comment by gengjiawen** [comment]
Google `Multiple dex files define`, you will get the answer.
