### ISSUE TITLE
[Layout] "Remove layout only nodes" causing trouble

### ISSUE THREAD

**Issue by vishnevskiy** [facebook/react-native#1984]
I have tried to upgrade my app to 0.8 and it completely broke.

Most breakages have occurred in views that are just container views that power drawers or modals. 

Reverting JUST this https://github.com/facebook/react-native/commit/02db374e50861c30fd06c527b2b6c6a505d40feb fixes the problem.

I am wondering if this behavior is intended and the logic behind collapsable needs to be documented (like in what situations do I want to use it), were my patterns wrong or is this commit just buggy because I noticed it was reverted once before.

Thanks!

**Comment by vishnevskiy** [comment]
Another note. If I don't revert the commit and just modify the isLayoutOnly to always return NO my app works fine as well.

**Comment by a2** [comment]
Can you provide a repro case? That would help me fix it the fastest. Thanks!

**Comment by brentvatne** [comment]
@a2 - I'm having some issues as well, in particular in conjunction with LayoutAnimation - it looks like the layout is updated before the animation completes. For example, if you have a view where some child subviews collapse on top of each in response to onPress (and so the height of the layout-only container view changes), any views underneath it will move up to the new height before the animation is done. It's on a closed-source app but I can try to repro for you later or show you it over Google Hangouts if you prefer.

**Comment by sahrens** [comment]
Perhaps we should turn off layout collapsing by default and make it opt-in for apps that need/want the perf boost?  At least until it's more stable?

**Comment by a2** [comment]
I would need a repro case to diagnose and fix the problem.

**Comment by brentvatne** [comment]
@a2 - I can definitely get you that, sorry just on-site with client and can't take the time for it at the moment

**Comment by brentvatne** [comment]
@sahrens - this seems reasonable - it's an important feature but for people who want to use the latest version today, it may in some cases force us to create a fork to disable it if it's not toggleable

**Comment by vishnevskiy** [comment]
I can do a demo over screen share but refactoring a demo of some of the problems would take some time.

- I have some views that return an `<View />` when they don't actually want to render and I was doing this because return `null` wasn't working as you could in React for web. This caused the view to randomly disappear in 0.8 even though the box is there where it would go it was just black. I tried putting `collapsible={false}` to the empty vie wand it fixed it, then I tried null and it also worked (I guess this now works on react-native). 
- My drawer wrapper was designed such that it was a container view with the left, right, and center views inside it. I was using POP to grab a ref to the container and animate it. Since the view was never actually put in the hierarchy the animation never ran. Setting it to `collapsible={false}` made it work. I guess we could probably also solve this by using the new Animated instead.

**Comment by brentvatne** [comment]
This has been reverted in 0.8.0-rc.2, hopefully next time we can get it right. @a2 if you need help reproducing these issues just ping me and we can do a screenshare
