### ISSUE TITLE
In this environment the sources for assign MUST be an object. And they are.

### ISSUE THREAD

**Issue by JohnCdf** [facebook/react-native#19844]
I've created a component that looks like this:

```
import React, { Component } from 'react';
import { StyleSheet, View } from 'react-native';
import { Text } from 'react-native-elements';

export default class SignUp extends Component {
  render() {
    const {Maincontainer, container} = styles;
    return (
      <View style={Maincontainer}>
        <View style={container} >
          <Text h1>Sign Up</Text>
        </View>
        <View style={container}>
          <Text h1>Or Log in</Text>
        </View>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  Maincontainer: {
    display: 'flex',
    justifyContent: 'center',
    flex: 1
  },
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center'
  }
})
```
It runs well, until I change the `View style` from `<View style={container} >` to something like `<View style={{...container, backgroundColor: 'blue'}} >` is will throw a TypeError: "In this enviorment the sources for assign MUST be an object."

It can be on any one of the `View` tags, that one change will crash the app

**Comment by TheSavior** [comment]
The type of container is a number. Use the array syntax instead of spreading into an object:

style={[container, {background: ‘blue’}]}

**Comment by nandorojo** [comment]
I got this error by using `...StyleSheet.absoluteFill` in my stylesheet. Took a long time to find that as the cause. Any idea why that's happening?

**Comment by TheSavior** [comment]
@nandorojo, your situation is what `StyleSheet.absoluteFillObject` is for: https://github.com/facebook/react-native/blob/master/Libraries/StyleSheet/StyleSheet.js#L267
