### ISSUE TITLE
[Android]Modal becomes invalid state when power button is pressed.

### ISSUE THREAD

**Issue by satoshikumano** [facebook/react-native#19847]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Run `react-native info` in your terminal and paste its contents here.

```
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.3.0
  Yarn: 1.6.0
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4
```

## Description
This issue only confirmed in Android 7.x
Pressing power button when Modal component is displayed causes invalid state of Modal.
I see Modal contents disappears but its transparent  background remains after Pressing power button again and screens turns on.

With Android 6.x or 8.x, Both modal contents won't be hidden with the same operation.

![screenshot_1529650789](https://user-images.githubusercontent.com/1525882/41763014-be3ac1f8-7637-11e8-85d3-16651be97983.png)

## Reproducible Demo
The code is almost same as [Modal official document](https://facebook.github.io/react-native/docs/modal.html)

https://github.com/satoshikumano/RN-Modal-Test

**Comment by wzt1119** [comment]
I also met this problem, how to solve?

**Comment by satoshikumano** [comment]
My workaround is subscribe to `AppState` and hide modal if `AppState` is not `active`.
In this way, When the app come back to foreground, Modal is re-rendered and problem is recovered.

**Comment by tsvetan-ganev** [comment]
@satoshikumano, you sir, deserve a medal.
