### ISSUE TITLE
Ios app icon dosen't show out.

### ISSUE THREAD

**Issue by motogod** [facebook/react-native#19855]
Yes     Review the documentation: https://facebook.github.io/react-native
 Yes    Search for existing issues: https://github.com/facebook/react-native/issues
 Yes    Use the latest React Native release: https://github.com/facebook/react-native/releases

 Review the documentation: https://facebook.github.io/react-native
Yes   Search for existing issues: https://github.com/facebook/react-native/issues
Yes   Use the latest React Native release: https://github.com/facebook/react-native/releases

## Description
Have added all of icons under images.xcassets, when i `npm run ios` Ios app icon doesn't show out on simulator.   `MovieToGo`
<img width="1177" alt="2018-06-22 11 08 10" src="https://user-images.githubusercontent.com/17781603/41786204-75e910ae-7677-11e8-8508-286a58a13d6f.png">

env:
"react": "16.3.1",
"react-native": "^0.55.4",

I try to create another project `testnavigate` and use the same way to add app icon to the project. The icon shows out.
env:
"react": "16.3.1",
"react-native": "~0.55.2",

<img width="351" alt="2018-06-23 12 00 56" src="https://user-images.githubusercontent.com/17781603/41786605-8999fedc-7678-11e8-84c7-22cb2ff7005b.png">

The only difference things is build `testnavigate` shows BUILD SUCCEED , but build `MovieToGo` shows the error even though the project can be work.
```
** BUILD FAILED **


The following build commands failed:

	CompileC /Users/motogod19/ReactNativeTutorial/TestMovieToGoTickets/MovieToGo/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64/RCTUIManagerUtils.o Modules/RCTUIManagerUtils.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/motogod19/ReactNativeTutorial/TestMovieToGoTickets/MovieToGo/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64/RCTMultipartStreamReader.o Base/RCTMultipartStreamReader.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)
```

What are the differences between these two projects?  I don't think RN version `0.55.4` cause my can see my ios app icon.

Thanks in advance.

**Comment by gastonmorixe** [comment]
This is happening to me on some versions too.

**Comment by motogod** [comment]
@gastonmorixe  Which version do you use ? I have no idea how to find the problem because i have add all of icons on XCode.  

So my solution is re-create my project again and make sure the icon can be show out first...(The version is still 0.55.2)

**Comment by gastonmorixe** [comment]
@motogod I think it was happening rc2 but fixed in rc3. It was intermittent. xCode 10 beta 2.
