### ISSUE TITLE
Elevation is not working for android 4.4

### ISSUE THREAD

**Issue by ggepenyan** [facebook/react-native#19874]
I try to set elevation to a View component. It works correct in latest versions of android, but not working for 4.4. What can I do? Any suggestions? Thanks for attention.

**Comment by ayushnawani** [comment]
@ggepenyan  i am also facing same issue. You got any solution ? @react-native-bot  please reopen this issue

**Comment by ikesyo** [comment]
FYI elevation is only works on Android 5.0 and later.

https://developer.android.com/training/material/shadows-clipping
