### ISSUE TITLE
Input text overflow not working on iOS

### ISSUE THREAD

**Issue by michael-molina** [facebook/react-native#19871]
## Environment
  OS: macOS High Sierra 10.13.5
  Node: 8.11.3
  Yarn: 1.7.0
  npm: 6.1.0
  Watchman: Not Found
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.2 => 0.55.2

## Description
Explain what you did:
Big text input with slashes (http://www.aaaaaaaaaaaaaaaaaaaaaaa.com/v1)

Expected behaviour:
Truncated text with ellipsis.

To Reproduce
When a big text input contains slashes ( / ) and you click on another input, the first input is truncated strangely. <b>Only happens on iOS<b>.

![1](https://user-images.githubusercontent.com/40404971/41849958-43304d92-7859-11e8-89e4-481426a08cae.JPG)![2](https://user-images.githubusercontent.com/40404971/41849960-4352608a-7859-11e8-96bd-eafc9b2683ef.JPG)

## Reproducible Demo
https://snack.expo.io/r1ly4yob7

**Comment by agrakovich** [comment]
I faced with a similar issue but in my case, I used whitespaces instead of slashes.
