### ISSUE TITLE
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=164): Unable to lookup in current state: Shutdown

### ISSUE THREAD

**Issue by MANTENN** [facebook/react-native#19870]
**Context:** Before this my simulator used to work until I followed the instructions I had on my error screen to clear an error. 

### Environment:
  OS: macOS High Sierra 10.13.5
  Node: 6.11.2
  Yarn: 1.3.2
  npm: 6.0.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4697961

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

I have spent already 4 hours to get it back working, and I am still in the same spot. 

In the terminal this is the end result when I execute `react-native run-ios`
> ** BUILD SUCCEEDED **
> 
> 
> 
> The following commands produced analyzer issues:
>         Analyze Base/RCTModuleMethod.mm normal x86_64
> (1 command with analyzer issues)
> 
> Installing build/Build/Products/Debug-iphonesimulator/application.app
> An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=164):
> Unable to lookup in current state: Shutdown
> Launching org.reactjs.native.example.application
> An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=164):
> Unable to lookup in current state: Shutdown

**Attempted:** I tried clearing my cache, and reinstalling modules. Creating a new application, the same error appears

Android Simulator Works, but does not connect/ display anything other than connecting...

**Comment by MANTENN** [comment]
Reason: https://forums.developer.apple.com/thread/66665#192972

**Comment by jyotirmaybanerjee** [comment]
Still seeing this issue. The above solution did not do much.
