### ISSUE TITLE
Position absolute view is not covering elevation view

### ISSUE THREAD

**Issue by 2dxgujun** [facebook/react-native#19894]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.2.1
  Yarn: 1.5.1
  npm: 6.0.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4 Build version 9F1027a
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  react: ^16.2.0 => 16.2.0
  react-native: ^0.55.4 => 0.55.4

## Description
The `<Text>` display below the view with red background, see https://github.com/facebook/react-native/issues/15823

## Reproducible Demo

![image](https://user-images.githubusercontent.com/8072733/41895975-ff1cb408-7955-11e8-9d30-3e83763257bf.png)

```javascript
render() {
  return (
    <View style={{ flex: 1 }}>
      <View
          style={{ height: 50, backgroundColor: 'red', elevation: 4 }}
      />
      <View style={StyleSheet.absoluteFill}>
        <Text>HELLO</Text>
      </View>
    </View>
  )
}
```

**Comment by Versus2017** [comment]
I have the same problem

**Comment by Versus2017** [comment]
Is there any solutions about that?

**Comment by megalithic** [comment]
@Versus2017 we are having a similar issue with iOS, removing `Stylesheet.absoluteFill` fixes it for us. In a couple cases we just had to replace that style with `height: '100%'`.
