### ISSUE TITLE
react-native run-ios error

### ISSUE THREAD

**Issue by ChengHanSummer** [facebook/react-native#19916]
** BUILD FAILED **

The following build commands failed:
	CompileC build/Build/Intermediates.noindex/xidebao.build/Debug-iphonesimulator/xidebao.build/Objects-normal/x86_64/AppDelegate.o xidebao/AppDelegate.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/xidebao.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/xidebao.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

from git clone run-ios error

**Comment by ChengHanSummer** [comment]
is node_modules version error Now is run

**Comment by zhenizhui** [comment]
@ChengHanSummer so, how to solve this problem?

**Comment by ChaoTzuJung** [comment]
clear all the file in ~/.rncache fix my problem
