### ISSUE TITLE
Watchman (Error: Watcher took too long to load) - HELP going to lose my mind.

### ISSUE THREAD

**Issue by KFoxder** [facebook/react-native#1991]
I have been trying to get 'npm start' to work for the past 4 days now. Probably should have opened this issue earlier, but here it goes.

Note: I have tried to reinstall everything multiple times. 

OS X Yosemite (10.10.4)
Node : v2.3.4
npm : v2.12.1
Xcode : 6.4

When I run 'npm start', I get:

17:50:59] <START> fs crawl
[17:51:03] <START> request:/index.ios.bundle
[17:51:03] <START> find dependencies
[17:51:18] <END>   fs crawl (19181ms)
 ERROR  Watcher took too long to load
Try running `watchman version` from your terminal
https://facebook.github.io/watchman/docs/troubleshooting.html
Error: Watcher took too long to load
Try running `watchman version` from your terminal
https://facebook.github.io/watchman/docs/troubleshooting.html
    at [object Object]._onTimeout (/Users/kevin_fox/Documents/react-native/AwesomeProject/node_modules/react-native/packager/react-packager/src/FileWatcher/index.js:98:16)
    at Timer.listOnTimeout (timers.js:89:15)

Running: 'watchman version' : 
{
    "version": "3.5.0"
}

**Comment by KFoxder** [comment]
Missed this the first time, but when I run 'react-native init AwesomeProject' I get this:

fsevents@0.3.6 install /Users/kevin_fox/Documents/react-native/AwesomeProject/node_modules/react-native/node_modules/babel/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 404 response dowloading http://nodejs.org/dist/v2.3.4/node-v2.3.4.tar.gz
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:251:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/npm/node_modules/request/request.js:985:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:415:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:305:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "/usr/local/Cellar/iojs/2.3.4/bin/iojs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/kevin_fox/Documents/react-native/AwesomeProject/node_modules/react-native/node_modules/babel/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v2.3.4
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing fsevents@0.3.6
react-native@0.7.1 node_modules/react-native

Looks to me like this is breaking my fsevents and thus watchman...

**Comment by KFoxder** [comment]
for now it looks like I solved the issue by globally installing:

npm install -g node-gyp

**Comment by sahrens** [comment]
Sorry you had so much trouble, but glad it's working now :)

**Comment by KFoxder** [comment]
@sahrens Not your fault! It is kind of amazing though how quickly one figures stuff out when they have "talk" through the problem even if your talking to no one :) 

Cheers!
