### ISSUE TITLE
How to use Share of react-native to share multiple images?

### ISSUE THREAD

**Issue by pigflymoon** [facebook/react-native#19912]
## Environment
Environment:
  OS: macOS Sierra 10.12.6
  Node: 6.14.3
   npm: 3.10.10
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  
Packages: (wanted => installed)
  react: ^16.2.0 => 16.4.1
  react-native: ^0.55.4 => 0.55.4
## Description
I am trying to use Share of react-native to share multiple images. I know how to share one image by Share as following:
```js
import {
     Share
} from 'react-native';
 let shareImage = {
                title: caption,//string
                message: message,//string
                url:imageUrl,// eg.'http://img.gemejo.com/product/8c/099/cf53b3a6008136ef0882197d5f5.jpg',
                subject: caption // string  for email
            };
            Share.open(shareImage).catch(err => console.log(err));

```
according to the [document actionsheetios](http://facebook.github.io/react-native/docs/actionsheetios.html#showshareactionsheetwithoptions)
url (string) - a URL to share,
The question is how to share multiple images？
Thanks in advance!

**Comment by patrickkempff** [comment]
@pigflymoon I think you should use [StackOverflow](http://stackoverflow.com/questions/tagged/react-native) for this type of question.

**Comment by alexlevy0** [comment]
@pigflymoon you can use this: https://github.com/chuangbo/react-native-multi-share
Have fun :)

**Comment by suwu150** [comment]
@pigflymoon Can the Share component share files in android? I am prompted to "Get Resource Failed" when I use it. How do you do it?
