### ISSUE TITLE
React Native Docs on Github Pages receiving 404

### ISSUE THREAD

**Issue by drdpedroso** [facebook/react-native#19911]
- [X] Review the documentation: https://facebook.github.io/react-native
  - [X] Search for existing issues: https://github.com/facebook/react-native/issues
  - [X] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
https://facebook.github.io/react-native/

## Description
Receiving a 404 (`File not found`) when accessing https://facebook.github.io/react-native/

## Reproducible Demo
SImply go to https://facebook.github.io/react-native/
<img width="755" alt="screen shot 2018-06-26 at 18 29 30" src="https://user-images.githubusercontent.com/12386985/41940407-0131893a-796f-11e8-9fc4-e71c0fefda61.png">

**Comment by OtacilioN** [comment]
Same here! I also asked for some friends and they got the same error

**Comment by allanrlima** [comment]
Same goes here!

**Comment by HalfdanJ** [comment]
Seems like react-bot deleted it? https://github.com/facebook/react-native/commit/30b387cc5d223ec05e590e2657433c631fb7af67

**Comment by megantracy93** [comment]
I can access here: https://facebook.github.io/react-native/docs/getting-started

**Comment by designorant** [comment]
It's been up and running for a few minutes now.

**Comment by drdpedroso** [comment]
Yeah, I guess its all working now
