### ISSUE TITLE
No documentation for linking ART in android.

### ISSUE THREAD

**Issue by sgarg24** [facebook/react-native#19927]
## Environment
  OS: macOS High Sierra 10.13.5
  Node: 8.11.3
  Yarn: Not Found
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: 0.54.0 => 0.54.0

## Description
I am having errors while linking the react-native ART in android.
I found a solution at https://github.com/facebook/react-native/commit/27ac04742ab4665cd529fe63fd68a30db9293b76

On `react-native run-android` I am getting following errors 
```java:11: error: cannot find symbol
import com.facebook.react.ARTPackage;
                         ^
  symbol:   class ARTPackage
  location: package com.facebook.react
app-path/MainApplication.java:28: error: cannot find symbol
            new ARTPackage()
                ^
  symbol: class ARTPackage
2 errors
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```
Without linking art manually I am getting following error:
<img width="290" alt="error" src="https://user-images.githubusercontent.com/30209755/41967219-c08f555a-7a1e-11e8-9d38-56f80772f83b.png">

This works fine on IOS device but gives error on android platform.

Also Is there a proper documentation on how to link Art with android namually?

**Comment by hramos** [comment]
Can you open an issue at https://github.com/facebook/react-native-website regarding the missing ART docs?
