### ISSUE TITLE
Build with new configuration in wrong Build/Products folder

### ISSUE THREAD

**Issue by lukaszgoworko** [facebook/react-native#19929]
- ✔️ Review the documentation: https://facebook.github.io/react-native
  - ✔️ Search for existing issues: https://github.com/facebook/react-native/issues
closed issue: #17650
  - ✔️ Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Environment:
  OS: macOS High Sierra 10.13.5
  Node: 10.5.0
  Yarn: 1.7.0
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 2.3 AI-162.3764568

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: ^0.55.4 => 0.55.4

## Description
Build fails, when using a new configuration (staging) where Icons, Bundle ID and Product Name are different to Debug and Release Config 

## Reproducible Demo
Creating new configuration and scheme in Xcode with own icons, name, and app-ID. Change debug configuration.

(Write your steps here:)

1. Dublicate Configuration "Release" => Named Staging
2. Add new IconsSets => AppIconStaging and AppIconDebug
3. Change Target Build Settings
    1. ASSETCATALOG_COMPILER_APPICON_NAME
        * Debug: AppIconDebug
        * Staging: AppIconStaging
        * Release: AppIconRelease
    2. PRODUCT_BUNDLE_IDENTIFIER
        * different for every configuration
    3. PRODUCT_NAME
        * different for every configuration
4. Dublicate Scheme => named: ProjectDebug and ProjectStaging
5. Edit Schemes
    1. Set Build Settings for Run, Profile and Archive
        * ProjectDebug => Debug
        * ProjectStaging => Staging

At this Point trying to run ProjectStaging on Simulator fails because the build fails.
I have noticed, that when building ProjectStaging with Staging configuration on an fresh git clone of my project, some files are build in **ios/build/Build/Products/Release-iphonesimulator**.

Because of this files the build fails, they can't be found in the **Staging-iphonesimulator** folder.

There are some links to solutions by changing some build settings for Staging configuration

Changing: _Header Search Paths_, _Framework Search Paths_, _Library Search Paths_ and _User Header Search Paths_ to
`$(BUILD_DIR)/Release$(EFFECTIVE_PLATFORM_NAME)`

Now all scheme builds failing when trying to run from Xcode:
`/Volumes/Workspace/Projects/Project/ios/ProjectTests/ProjectTests.m:11:9: 'XCTest/XCTest.h' file not found`

Running from console:
`node node_modules/react-native/local-cli/cli.js run-ios --device --scheme ProjectStaging --configuration Staging`
Build fails because of same issue, but App is installed and running well (cant find any errors for now)
```

❌  /Volumes/Workspace/Projects/tmp/RepApp/ios/RepAppTests/RepAppTests.m:11:9: 'React/RCTLog.h' file not found

#import <React/RCTLog.h>
        ^~~~~~~~~~~~~~~~


▸ Compiling RepAppTests.m

❌  /Volumes/Workspace/Projects/tmp/RepApp/ios/RepAppTests/RepAppTests.m:11:9: 'React/RCTLog.h' file not found

#import <React/RCTLog.h>
        ^~~~~~~~~~~~~~~~
```

** BUILD FAILED **

Building archive always working

### Expected Behavior
Project files for a configuration are in their own folder, so the build is always ok.

### Actual Behavior

Correct Build with all files in the right place

**Comment by lukaszgoworko** [comment]
Someone?

**Comment by badrange** [comment]
In our case, the build error is: `'React/RCTBridgeModule.h' file not found`. React native 0.56, both Xcode 9.4 and 10.0.
