### ISSUE TITLE
The Drawers are not loaded correctly. RACE CONDITION ISSUE!

### ISSUE THREAD

**Issue by veselinnguyen** [facebook/react-native#19933]
## Environment
Environment:
  OS: macOS High Sierra 10.13.5
  Node: 8.9.4
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: Not Found
  Xcode: Not Found
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: ^0.49.5 => 0.49.5

## Description
1] Given: SinglePageApplication with main screen and left and right drawers.
2] When the drawer is tried to be opened
3] Then the drawer is opened on the screen just partially 90% of the cases the rest 10% works good.

Has anyone experienced this sh** ?

## Reproducible Demo
<img width="356" alt="screen shot 2018-06-26 at 7 52 56 pm copy" src="https://user-images.githubusercontent.com/2046167/41995521-69db2c3c-7a52-11e8-834b-2c2466d5cbdd.png">
<img width="356" alt="screen shot 2018-06-26 at 7 52 56 pm" src="https://user-images.githubusercontent.com/2046167/41995524-6becdf70-7a52-11e8-8768-ead53fd9987d.png">

**Comment by hramos** [comment]
Can you share an example of your code or otherwise provide more details?
