### ISSUE TITLE
Switch Component: Can not change thumbTintColor, onTintColor and tintColor on Android 4.4 Kitkat

### ISSUE THREAD

**Issue by huunovahub** [facebook/react-native#19939]
## Environment
Environment:
  Node: 10.1.0
  Yarn: Not Found
  npm: 4.6.1
Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

## Sample code
```
<Switch 
  thumbTintColor={'#f2f2f2'} 
  onTintColor={'red'} value={this.state.switchChange} 
  onValueChange={this.handleSwitchChange) 
  style={{width: 50}}/>
```
Expectation (run on Android 5.0 and above):
![screen shot 2018-06-28 at 12 10 17 pm](https://user-images.githubusercontent.com/30712828/42014410-701831c4-7acc-11e8-83cc-045802a8c65e.png)

I got this on Android 4.4 Kitkat
![screen shot 2018-06-28 at 12 10 47 pm](https://user-images.githubusercontent.com/30712828/42014385-4ed6b620-7acc-11e8-920d-033b7f3a9783.png)

My client even got this on Samsung Galaxy S5:
<img width="78" alt="screen shot 2018-06-28 at 12 13 07 pm" src="https://user-images.githubusercontent.com/30712828/42014465-b5fa4830-7acc-11e8-9d6e-43dcdbacc866.png">

**Comment by dulmandakh** [comment]
please provide sample code and screenshot.

**Comment by huunovahub** [comment]
@dulmandakh I updated my issue with the code and screenshots

**Comment by dulmandakh** [comment]
Do you use Android Studio? or just plain React Native?

I would suggest to wait for 0.56 release and test with it.

**Comment by huunovahub** [comment]
I just used plain React Native.

**Comment by dulmandakh** [comment]
Ok, 0.56 landed many Android improvements and will be releases in few days.

**Comment by huunovahub** [comment]
Okay, many thanks.

**Comment by gengjiawen** [comment]
Acually this is appcompat bug, see https://issuetracker.google.com/issues/110570729.

**Comment by VincentCATILLON** [comment]
I'm reproducing it with Android 5.0 and the same environment than you (except Node: 8.x)

```
  <Switch
    onTintColor="#009ee0"
    thumbTintColor="#fff"
    value={props.value}
    onValueChange={props.onValueChange}
  />
```

And the render is:

![kapture 2018-07-11 at 17 47 50](https://user-images.githubusercontent.com/8419208/42584050-9cae5f40-8532-11e8-9b02-eb643145ec9c.gif)

**Comment by hramos** [comment]
Fixed in https://github.com/facebook/react-native/commit/965adee109b86cc36f39a713237ade9592f13dad
