### ISSUE TITLE
project name "new" creates invalid Android build

### ISSUE THREAD

**Issue by FLGMwt** [facebook/react-native#19956]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

Closest existing issue is #19473 which deals a different create-time error when using a numeric project name. 

## Environment
```
Scanning folders for symlinks in /Users/ryanstelly/code/new/node_modules (15ms)

  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.3
      CPU: x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
      Memory: 173.73 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.5.0 - /usr/local/bin/node
      Yarn: 1.7.0 - ~/.yarn/bin/yarn
      npm: 6.1.0 - /usr/local/bin/npm
      Watchman: 4.5.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 21.1.2, 23.0.1, 24.0.0, 24.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.2, 27.0.3
        API Levels: 21, 23, 24, 25, 26, 27
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0-rc.4 => 0.56.0-rc.4 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
```

## Description
Creating a project with the name "new" (`react-native init new --version 0.56.0-rc.4`) results in a project which fails to build on Android.

```
:app:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/Users/ryanstelly/code/new/android/app/src/main/java/com/new/MainApplication.java:1: error: <identifier> expected
package com.new;
            ^
/Users/ryanstelly/code/new/android/app/src/main/java/com/new/MainActivity.java:1: error: <identifier> expected
package com.new;
            ^
/Users/ryanstelly/code/new/android/app/build/generated/source/r/debug/com/new/R.java:8: error: <identifier> expected
package com.new;
            ^
/Users/ryanstelly/code/new/android/app/build/generated/source/buildConfig/debug/com/new/BuildConfig.java:4: error: <identifier> expected
package com.new;
            ^
4 errors
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.88 secs
```

![image](https://user-images.githubusercontent.com/4138357/42063350-e30e2056-7af6-11e8-9f5d-a5a8ef7d3e1a.png)

The issue seems to be that sections of JVM package names cannot be Java keywords. This also fails for `package com.class`, `package com.package`, `package `com.final`, etc.

## Reproducible Demo
From react-native init:

```bash
react-native init new --version 0.56.0-rc.4
react-native run-android
```

From example repo:

```bash
git clone git@github.com:FLGMwt/rn-android-project-name-bug-repro.git
cd rn-android-project-name-bug-repro
react-native run-android
```

## Suggested Solution

Blacklist all Java keywords for init project names.

This does *not* affect iOS as far as I can tell. `react-native run-ios` works fine.

![image](https://user-images.githubusercontent.com/4138357/42063721-944005fa-7af8-11e8-8e85-4e680faff67f.png)

**Comment by dulmandakh** [comment]
Hello, new is a keyword in Java, so you can't use it for variables and packages names, which is a part of your project name.

**Comment by FLGMwt** [comment]
Right, but can we blacklist Java keywords in the `react-native init` cli to surface this to users earlier? Happy to PR if this is welcome.

**Comment by dulmandakh** [comment]
@FLGMwt Welcome
