### ISSUE TITLE
[WINDOWS] Picker don't work in DrawerNavigation

### ISSUE THREAD

**Issue by paulbx81** [facebook/react-native#19967]
## Environment
Environment:
  OS: Windows 10
  Node: 9.11.1
  Yarn: 1.6.0
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.0.0.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: 0.54.0 => 0.54.0

## Description
When you use <Picker> component into a drawerNavigation, the picker appears but it don't work when you try to use it nothing append.

## Reproducible Demo
You can try with the Picker exemple on the DOC

**Comment by hramos** [comment]
Can you expand your description and repro steps? We need more information, a code sample, etc.
