### ISSUE TITLE
[RN 0.54.4, 0.56.0-rc.4] RNFetchBlob requires main queue setup since it overrides `constantsToExport` but doesn't implement `requiresMainQueueSetup`

### ISSUE THREAD

**Issue by fungilation** [facebook/react-native#19960]
## Environment
```
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.5
      CPU: x64 Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
      Memory: 36.54 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.5.0 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.1.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 23.0.3, 25.0.1, 25.0.3, 26.0.1, 27.0.3
        API Levels: 23, 25, 26, 27
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0-rc.4 => 0.56.0-rc.4 
    npmGlobalPackages:
      eslint-plugin-react-native: 1.2.0
      react-native-cli: 0.2.0
      react-native-git-upgrade: 0.2.7
```
## Reproducible Demo
`$ react-native run-ios`

yellowbox log:
Module RNFetchBlob requires main queue setup since it overrides `constantsToExport` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.

<img width="1178" alt="screenshot 2018-06-28 22 10 27" src="https://user-images.githubusercontent.com/3803466/42074336-9079430a-7b20-11e8-8ffc-71212b2cd35d.png">

Same kind of issue as https://github.com/facebook/react-native/issues/17504, needing similar kind of fix: https://github.com/facebook/react-native/pull/17679

**Comment by hramos** [comment]
Thanks for the issue! Someone want to send a quick PR to add this?

**Comment by patrickkempff** [comment]
@hramos I am not sure if `RNFetchBlob` is even part of RN

**Comment by patrickkempff** [comment]
@hramos I am not sure if `RNFetchBlob` is even part of RN

**Comment by fungilation** [comment]
Oops, you're right. Closed
