### ISSUE TITLE
[Rendering] Set allowsEdgeAntialiasing on rotated views by default

### ISSUE THREAD

**Issue by ide** [facebook/react-native#1997]
So many apps don't antialias away the jaggies and it looks crappy. In iOS 7+ you can set allowsEdgeAntialiasing on individual CALayers instead of needing to set it globally or resorting to hacks with transparent borders so I believe it's a good idea to automatically set it on rotated views for a good-looking default.

**Comment by zharinov** [comment]
BTW, it may be not so trivial for borderWidth > 0.

![](https://dl.dropboxusercontent.com/spa/ldgnhd4jmpyluas/35uahwjz.png)

**Comment by zharinov** [comment]
Enabling layer rasterization for non-iOS rendering solved this.

```
  layer.shouldRasterize = YES;
  layer.rasterizationScale = [UIScreen mainScreen].scale;
```

**Comment by nicklockwood** [comment]
This was already enabled in @ide's pull request I think. Unless that didn't make it in for some reason.

**Comment by brentvatne** [comment]
@nicklockwood - good point, #1999 covered this and related commit b362072c83b5fe883e913e5752735fc6e561219b

**Comment by l-urence** [comment]
Still have some issues with some jaggies with views inside a rotated view.
![jaggies_child_view_react-native](https://cloud.githubusercontent.com/assets/472753/11366320/de7dfab4-92ac-11e5-9649-edeb0bd68323.png)
Source: https://gist.github.com/l-urence/17fe144ac6a9003cde02
