### ISSUE TITLE
Keyboard.dismiss and TextInput.blur not working if used with FlatList

### ISSUE THREAD

**Issue by Elijen** [facebook/react-native#19978]
## Environment
Environment:
  OS: macOS 10.14
  Node: 10.1.0
  Yarn: 0.27.5
  npm: 6.1.0
  Watchman: 4.7.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz => 0.55.4

## Description
Keyboard.dismiss and TextInput.blur sometimes does not have any effect. 

## Reproducible Demo
https://snack.expo.io/@peller/keyboard-dismiss-bug

1) Press **TextInput.focus()** button
2) Manually focus the 1st or the 3rd input by tapping it
3) **TextInput.blur()** or **Keyboard.dismiss()** buttons now won't work.

**Comment by Elijen** [comment]
The original issue with lacking information: #19162

**Comment by Elijen** [comment]
This does not happen if `keyboardShouldPersistTaps="always"` prop is set on the FlatList (even though `onPress` that is calling `Keyboard.dismiss()` is called for both `never` and `always` values).

**Comment by Elijen** [comment]
@stale 💩

**Comment by UZIhuhuhu** [comment]
I also encountered this problem.

**Comment by UZIhuhuhu** [comment]
You can introduce a state to turn off automatic locking autoFocus
