### ISSUE TITLE
Build fails on actual iPhone but works fine on simulator

### ISSUE THREAD

**Issue by sja1n** [facebook/react-native#19975]
- [X] Review the documentation: https://facebook.github.io/react-native
  - [X] Search for existing issues: https://github.com/facebook/react-native/issues
  - [X] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Environment:
  OS: macOS High Sierra 10.13.5
  Node: 8.11.1
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  react: ^16.4.1 => 16.4.1
  react-native: ^0.55.4 => 0.55.4

## Description
App working fine on iOS simulator but while running on actual iOS device, it randomly starts giving lexical or preprocessor issue stating `'React/RCTBridge.h' file not found` error in random libraries

Screenshot:

![screen shot 2018-06-29 at 5 40 23 pm](https://user-images.githubusercontent.com/37500728/42091703-017a65b8-7bc4-11e8-989d-9a943267ae4c.png)

but the same code and settings works perfectly fine on simulator.

**Comment by hramos** [comment]
Do you run into this issue when using the 0.56 release candidate?

**Comment by anderskev** [comment]
Check that all of the libraries throwing the error have the specific build configuration you are using. Typically when I have seen this error it was due to that.

**Comment by sja1n** [comment]
@hramos  yes it still is happening. 
@anderskev Thanks for the suggestion it was all same.

Weirdly after code signing which i was not aware is important for devices and clean build it was working fine.

**Comment by anderskev** [comment]
@sja1n provisioning is a pain. I would recommend setting up fastlane especially if you are on a large team. Glad you figured it out!

**Comment by sja1n** [comment]
Thanks @anderskev for the suggestion, will surely look into it 😄
