### ISSUE TITLE
[0.56] WebView source={html: "<div>test<div>"} return error

### ISSUE THREAD

**Issue by tamirrab** [facebook/react-native#19986]
- [ ] Review the documentation: https://facebook.github.io/react-native
  - [ ] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment

  React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
      Memory: 97.80 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.9.4 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.1.0 - /usr/local/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.4.1 => 16.4.1 
      react-native: 0.56.0-rc.4 => 0.56.0-rc.4 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-communications: 2.2.1
      react-native-debugger-open: 0.3.11
      react-native-fetch-blob: 0.10.5
      react-native-git-upgrade: 0.2.7

## Description
`WebView source={html: <div>test<div>}` return error:

YellowBox.js:67 Possible Unhandled Promise Rejection (id: 0):
Error: Unable to open URL: about:blank
Error: Unable to open URL: about:blank
    at createErrorFromErrorData (blob:http://localhost:8081/dba704fb-6fe0-4995-81aa-6f0f037a217c:2270:17)
    at blob:http://localhost:8081/dba704fb-6fe0-4995-81aa-6f0f037a217c:2222:27
    at MessageQueue.__invokeCallback (blob:http://localhost:8081/dba704fb-6fe0-4995-81aa-6f0f037a217c:2658:18)
    at blob:http://localhost:8081/dba704fb-6fe0-4995-81aa-6f0f037a217c:2409:18
    at MessageQueue.__guard (blob:http://localhost:8081/dba704fb-6fe0-4995-81aa-6f0f037a217c:2561:13)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (blob:http://localhost:8081/dba704fb-6fe0-4995-81aa-6f0f037a217c:2408:14)
    at http://localhost:8081/debugger-ui/debuggerWorker.js:72:58
console.warn @ YellowBox.js:67
onUnhandled @ Promise.js:43
onUnhandled @ rejection-tracking.js:71
(anonymous) @ JSTimers.js:255
_callTimer @ JSTimers.js:151
callTimers @ JSTimers.js:404
__callFunction @ MessageQueue.js:344
(anonymous) @ MessageQueue.js:107
__guard @ MessageQueue.js:291
callFunctionReturnFlushedQueue @ MessageQueue.js:106
(anonymous) @ debuggerWorker.js:72

## Reproducible Demo
`<WebView source={{html: "<div>test</div>"}}/>`

**Comment by francisco-sanchez-molina** [comment]
Can you test this line?
`<WebView  originWhitelist={['*']} source={{ html: "<div>test</div>", baseUrl: '' }} />`

**Comment by tamirrab** [comment]
Working perfect after adding `originWhitelist={['*']}`
Thanks! 👍

**Comment by msageryd** [comment]
Thank you @francisco-sanchez-molina !
This made react-native-signature-pad working with RN 0.56. 

I'm sorry for posting in a closed issue. But if you have answers to my below questions I fell that they belong in this thread for clarification.

- why do we need to whitelist * now and not before?
- what is the webView trying to open when failing the whitelist test? "about:blank" is kind of hard to debug.

**Comment by rodrigobdz** [comment]
WebView documentation is very lacking. I spent endless hours figuring this out.
