### ISSUE TITLE
while running command react-native run android following error is showing for android * What went wrong: A problem occurred configuring project ':app'. > Could not resolve all dependencies for configuration ':app:_debugApk'.    > Configuration with name 'default' not found.

### ISSUE THREAD

**Issue by shures** [facebook/react-native#19983]
- [ ] Review the documentation: https://facebook.github.io/react-native
  - [ ] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Run `react-native info` in your terminal and paste its contents here.

## Description
Describe your issue in detail. Include screenshots if needed. If this is a regression, let us know.

## Reproducible Demo
Let us know how to reproduce the issue. Include a code sample, share a project, or     share an app that reproduces the issue using https://snack.expo.io/. Please follow the guidelines for providing a MCVE: https://stackoverflow.com/help/mcve

**Comment by hramos** [comment]
Please make sure to fill out the template, it's the minimum we ask when opening a new issue.

**Comment by niralivasoya** [comment]
i have the same issue please help to figure it out. react-native info is as follows:

> Environment:
>   OS: macOS High Sierra 10.13.6
>   Node: 8.11.4
>   Yarn: Not Found
>   npm: 5.6.0
>   Watchman: 4.9.0
>   Xcode: Xcode 9.4.1 Build version 9F2000
>   Android Studio: 3.1 AI-173.4819257
> 
> Packages: (wanted => installed)
>   react: ^16.3.0-alpha.1 => 16.3.2
>   react-native: 0.54.4 => 0.54.4

**Comment by hramos** [comment]
@niralivasoya please open a new issue, and follow the template.
