### ISSUE TITLE
[Image] RCTNetworkImage calls downloadImageForURL once per prop that is set

### ISSUE THREAD

**Issue by ide** [facebook/react-native#1998]
Each time a prop is set, RCTNetworkImage calls `_updateImage` which initiates a new download even if the image URL hasn't changed. This results in a lot of extra work because `downloadImageForURL` also decodes the image, and we only want to do that after all the props are set.

cc @nicklockwood, are you currently working on the image downloader code?

**Comment by nicklockwood** [comment]
Yeah, I'm working on this currently. I'll try to fix this today.

**Comment by nicklockwood** [comment]
Turns out that this is more complex than I anticipated. The image downloader resizes the image and bakes in background color, so it's affected by all those props. I'm investigating what the best solution might be.

**Comment by sahrens** [comment]
Perhaps something that batches up the changes then flushes them, like we might do with setImmediate in JS?

**Comment by nicklockwood** [comment]
Is this working as expected now?

**Comment by ide** [comment]
@nicklockwood Yes, this looks fixed with the new image loader. Will send a PR to clean up some left over bits.
