### ISSUE TITLE
Debugging brokes Chrome on Mac

### ISSUE THREAD

**Issue by btravel** [facebook/react-native#19988]
## Environment
OS: macOS High Sierra 10.13.5
Node: 10.4.1
Yarn: Not Found
npm: 6.1.0
Watchman: 4.9.0
Xcode: Xcode 9.4.1 Build version 9F2000
Android Studio: Not Found

react: 16.3.1
react-native: 0.55.4
chrome: 67.0.3396.99

## Description
I'm trying to debug a react-native app in ios simulator on mac. Debugging starts Chrome browser but it is non-functional - there are some rendering artefacts (black boxes). After disabling the dev mode the app is working normally. Reloading an app during debug mode leads to error "RCTFatal Runtime is not ready for debugging" and after some time the simulator starts overloading the CPU on my Mac.

<img width="300" alt="smile" src="https://user-images.githubusercontent.com/21336941/42133079-53c93754-7d2c-11e8-99e4-a645f0122a95.png">

<img width="200" alt="RCTFatal" src="https://user-images.githubusercontent.com/21336941/42132992-0a6bae8a-7d2b-11e8-9837-289e085ed5fb.png">

## Reproducible Demo
The problem doesn't depend on the app I'm debugging.

**Comment by CrazyPython** [comment]
@btravel I'm using a mid-2013 MacBook Air with Turbo Boost broken and off, and debugging works for me, so I don't think it's related to CPU usage. More than likely, you've made a mistake in your configuration. I encourage you to close this issue and ask on [Reactiflux](https://www.reactiflux.com/) or [StackOverflow](https://stackoverflow.com/). **React Native GitHub issues is for bug reports only.**

**Comment by btravel** [comment]
@CrazyPython Seems that I've a found a similar issue: [#13149](https://github.com/facebook/react-native/issues/13149) I have the same error in the bundler console: "Error: not opened at WebSocket.send". Debugging starts working after several restarts of the simulator and bundler. But it is totally non deterministic - sometimes works, sometimes not. Usually it stops working after I close the simulator and chrome and run `react-native run-ios` command again.

**Comment by CrazyPython** [comment]
Close this issue if you believe it's a duplicate

**Comment by dehlen** [comment]
For me it works when opening up chrome at [localhost:8081/debugger-ui ](localhost:8081/debugger-ui ) before starting the remote debugging session. However this is just a temporary workaround ...
