### ISSUE TITLE
ScrollView layout doesn't handle horizontal insets with contentInsetAdjustmentBehavior="always"

### ISSUE THREAD

**Issue by sharplet** [facebook/react-native#19984]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment

```
Environment:
  OS: macOS High Sierra 10.13.5
  Node: 10.5.0
  Yarn: 1.7.0
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4 Build version 9F1027a
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.2 => 16.3.2
  react-native: 0.55.2 => 0.55.2
```

## Description

With a full screen `ScrollView` having `contentInsetAdjustmentBehavior="always"` on an iPhone X in landscape, the scroll view content container's width is still laid out at 100% of the scroll view's width, not taking into account the content insets. This means that the scroll view unintentionally becomes horizontally scrollable, and is laid out outside the scroll view's bounds.

## Reproducible Demo

Wasn't able to provide a Snack because I couldn't find a way to preview on an iPhone X.

**Comment by lidonghua** [comment]
Same issue. +1

As a workaround, I use a `SafeAreaView` embedded in the `ScrollView`. But it doesn't work for `FlatList` or `SectionList`. 😒
