### ISSUE TITLE
[META] Kotlin in React Native

### ISSUE THREAD

**Issue by dulmandakh** [facebook/react-native#19991]
# For Discussion

Kotlin is a rising start in Android Development, because it easy to learn and supports Java interoperability. Adding Kotlin to RN might make contribution easier and grow RN Android community, features.

Gradle and Buck both support Kotlin.

Let's talk about adding Kotlin to RN.

**Comment by dulmandakh** [comment]
As for myself, I can implement features in Kotlin, but not proficient enough to write large chunk of code in Java. Kotlin is safer because it handles nullability very well. 

FYI, Okio project switched to Kotlin.

**Comment by gengjiawen** [comment]
For me, kotlin has some awesome feature, but still need some more time. And for the iOS part, react native still stick to oc instead of swift.

**Comment by dulmandakh** [comment]
During WWDC 18, Apple announced that Swift ABI becoming stable and Swift runtime will be included in OS in 2019, so apps don't have to embed Swift runtime.

**Comment by gengjiawen** [comment]
Swift has been out for 4 years, and still not much adopted from my exerience. Kotlin became android dev language officially by google is just happened last year. 

My point is this can wait. Okio switched to kotlin, but not okhttp, not retrofit, not rxjava.

**Comment by dulmandakh** [comment]
@gengjiawen IIRC, Kotlin has been around for more than Swift, and it got adopted to Android last year because developers started using it since the beginning and asked for official support. Google IO18 showed more and more developers use Kotlin.

I would like to hear from Facebook developers, managers: @hramos @mdvacca @sophiebits

**Comment by sophiebits** [comment]
We don't have any plans to support Kotlin directly in the React Native upstream project, but if there are generic changes to RN that would make it easier to use alternative languages I'd say we'd be open to them.

**Comment by hramos** [comment]
@salah-ghanim there's an outstanding PR that should add Gradle 4 support once merged.

**Comment by dulmandakh** [comment]
@sophiebits @hramos I created a PR to add null annotations to few Java classes and interfaces to make them work better Kotlin, so it's easier and safer to develop native modules in Kotlin. https://github.com/facebook/react-native/pull/19973#pullrequestreview-133207355

**Comment by fungilation** [comment]
How is Swift not much adopted? It's already ahead of ObjC by [most measures](https://medium.com/@guydaher/what-stats-and-surveys-are-saying-about-swift-in-2017-7e21dcce1f8b).

**Comment by dulmandakh** [comment]
Okio is rewritten in Kotlin https://medium.com/square-corner-blog/okio-2-6f6c35149525

**Comment by andylamax** [comment]
Being a kotlin dev, I think kotlinJS is production. KotlinJS makes kotlin react possible, so yes. I am down for kotlin react native as well

**Comment by hyochan** [comment]
What I really hope from this issue is to make `kotlin` standalone react-native modules possible. I saw many developers working with `react-native` project building their own `kotlin` module and couldn't port to standalone libraries to `npm`.

I hope `react-native` team is aware that many of android developers are willing to provide firm open-source native modules built in `kotlin` and not `java`.

**Comment by cpojer** [comment]
I'm going to close this as we aren't planning on any larger rewrites like this at the moment. If you'd like to use Kotlin with React Native, that should be possible. If it doesn't work well, please send PRs that add support for various things that you need. If you'd like to mostly discuss this topic, please create a new issue in the discussions-and-proposals repository.
