### ISSUE TITLE
Disable autoscroll on TextInput focus inside a ScrollView on Android

### ISSUE THREAD

**Issue by babara2** [facebook/react-native#19995]
Hey everyone, I am having trouble controlling ScrollView. Basically, I have a form and anytime I focus on a field, the content automatically moves to the top of the screen as soon as the keyboard pops up. It would be really helpful if there was an option to keep the content wherever it is on the screen and then just scroll up and down. I would really appreciate any insights that anyone might have.

Thanks!

**Comment by EdgarHSM** [comment]
> Hey everyone, I am having trouble controlling ScrollView. Basically, I have a form and anytime I focus on a field, the content automatically moves to the top of the screen as soon as the keyboard pops up. It would be really helpful if there was an option to keep the content wherever it is on the screen and then just scroll up and down. I would really appreciate any insights that anyone might have.
> 
> Thanks!
@babara2  Did you ever find a solution to this? I'm having the same problem.
