### ISSUE TITLE
modal background become dim

### ISSUE THREAD

**Issue by clycheng2015** [facebook/react-native#19999]
"react": "^16.2.0",
   "react-native": "^0.52.3",
    android moblie 7.0
what i meet a problem is about the modal blackground become blacker and blacker when my modal component was shown more than one time! I tried many times,kinds of phones,debug or release app,or third libs,still have the problem, about the modal inner  content view is complex,maybe that is why cause this,but why???the ui is likely this:
 <Modal>
        <View>
               <ScrollView>
                       <FlatList></FlatList>
                      <FlatList></FlatList>
                      <FlatList></FlatList>
                      <FlatList></FlatList>
                      <FlatList></FlatList>
                      <FlatList></FlatList>
              </ScrollView>
       </View>
</ Modal>
when i open the model and open a few pages in the app,and then reopen the modal page,the problem show,.....
when I clean my phone memory ,and then open the page that have the modal,the packground is ok,but reopen and close do like i first do,the problem come to me!
i don't thnow why?

**Comment by dulmandakh** [comment]
Could you please share a sample code? You can have a single modal windows at a time, and if you open more they'll overlap and become darker.

**Comment by clycheng2015** [comment]
<Modal>
        <View>
               <ScrollView>
                       <FlatList></FlatList>
                      <FlatList></FlatList>
                      <FlatList></FlatList>
                      <FlatList></FlatList>
                      <FlatList></FlatList>
                      <FlatList></FlatList>
              </ScrollView>
       </View>
</ Modal>****

**Comment by clycheng2015** [comment]
` <Modal>
        <View>
               <ScrollView>
                       <FlatList></FlatList>
                      <FlatList></FlatList>
                      <FlatList></FlatList>
                      <FlatList></FlatList>
                      <FlatList></FlatList>
                      <FlatList></FlatList>
              </ScrollView>
       </View>
</ Modal>`
