### ISSUE TITLE
npm start fails with "Watcher took too long to load"

### ISSUE THREAD

**Issue by mfikes** [facebook/react-native#20]
When I run `npm start`, it fails indicating a timeout. (This is on a circa-2011 Mac laptop.)

```
Mike-Fikess-MacBook-Pro:react-native mfikes$ npm start

> react-native@0.0.1 start /Users/mfikes/Documents/Projects/react-native
> ./packager/packager.sh


 ===============================================================
 |  Running packager on port 8081.       
 |  Keep this packager running while developing on any JS         
 |  projects. Feel free to close this tab and run your own      
 |  packager instance if you prefer.                              
 |                                                              
 |     https://github.com/facebook/react-native                 
 |                                                              
 ===============================================================


React packager ready.

[Error: Watcher took too long to load.]
Error: Watcher took too long to load.
    at null._onTimeout (/Users/mfikes/Documents/Projects/react-native/packager/react-packager/src/FileWatcher/index.js:37:16)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

  >>> ERROR: could not create packager - please shut down any existing instances that are already running.
```

I've rebooted just to be sure nothing else is running.

To rule out a race, I've increased the `MAX_WAIT_TIME` on line 21 of `react-native/packager/react-packager/src/FileWatcher/index.js` to as much as 2 minutes, but this doesn't resolve the issue.

I've installed `node` and `watchman` via `brew`:

```
Mike-Fikess-MacBook-Pro:~ mfikes$ brew list
node        pcre        watchman
```

and I'm running the latest version of OS X:

```
Mike-Fikess-MacBook-Pro:~ mfikes$ uname -a
Darwin Mike-Fikess-MacBook-Pro.local 14.1.0 Darwin Kernel Version 14.1.0: Mon Dec 22 23:10:38 PST 2014; root:xnu-2782.10.72~2/RELEASE_X86_64 x86_64
```

I have all of this running successfully on another machine, so this will probably boil down to finding out what the critical difference between the two is.

**Comment by brennanpayne** [comment]
I'm not sure how it all fell into place, but I ended up in the same place as @mfikes.  I followed his above steps and was able to resolve the issue. 

The odd part is that `pcre` appeared to have been installed by homebrew (it came up in `brew ls`).  I was also able to run `watchman` from the command line in other scenarios and it would work, it was only not working for react-native!  Anyway, uninstalling `pcre` and doing a fresh install of node and watchman resolved my issue.  Thanks for documenting how you fixed it @mfikes!
