### ISSUE TITLE
[Packager] Consider switching to babel-runtime instead of s_u polyfills

### ISSUE THREAD

**Issue by ide** [facebook/react-native#2000]
A couple of good things happen from switching to Babel's runtime polyfills:

- Several Babel transforms produce less code because babel-runtime provides helpers
- RN projects with async functions use Babel's copy of regenerator instead of their own
- Features like Symbols are polyfilled

This said, it is not trivial to start using babel-runtime. The require.js polyfill cannot run through Babel (with the "runtime" option on)  because Babel will prepend `require` calls to it, which breaks require.js. Also the transformed files have new require calls that import the runtime, so the packager's dependency graph needs to be updated during the transformation process.

**Comment by miracle2k** [comment]
So I wanted to use the forOf extension, which doesn't work on the device because "Symbol" is not polyfilled.

I added ``require("react-native/node_modules/babel/polyfill")`` to my index.ios.js file. Should I expect any complications?

**Comment by despairblue** [comment]
I suppose this is the reason for [`Map` not being polyfilled](https://github.com/facebook/react-native/issues/3480), right?

**Comment by ide** [comment]
@despairblue yes - it requires a bunch of work to get babel-runtime injected though so someone will need to sit down and focus on it for a day or two.

**Comment by zuhair-naqvi** [comment]
Any update on this?

**Comment by jsierles** [comment]
Since we're trying to focus Github issues on bugs, I'm closing this out in favor of discussion on Product Pains or a PR that implements the babel-runtime injection. Thanks!
