### ISSUE TITLE
Signed APK .gitignored, Now Starting From Scratch

### ISSUE THREAD

**Issue by thecodecafe** [facebook/react-native#20003]
This issue is me expressing my full dissatisfaction and displeasure for a very careless act done by somebody in the react native team, I don't know who in particular, but that person has out of his own disregard and reverence for care chosen to not pay attention to detail in his work. How in the world am I supposed to know that you excluded the keystore in the .gitignore file? I backed up my project via git when I was changing my computer and after pulling it back and installing all the dependencies I couldn't find my keystore file, now I can't push updates for my app on the Playstore because I don't have the same key I used to push my last release before the change. I now have to upload the app as a new mobile app on the Playstore and lose all my already existing users, you leterally cause me to start all over from scratch, for no damn good reason. I am very disappointed in this level of carelessness.
At the very list there should have been a notice on the docs in the documentation page for generating a signed APK page, stating this.

**Comment by dulmandakh** [comment]
Usually, APK signing key is stored somewhere outside of React Native project directory, and it's developers responsibility to backup everything. 

I'm sorry for what happened to you, but it's not RN developers fault.

**Comment by thecodecafe** [comment]
Thanks was able to find a work around and I'm close to pushing the release, fortunately I enabled google play app signing before now so they'll reset the certificate for me, will make edits to the react-native docs with a small notice on this, and see if it will be accepted.
