### ISSUE TITLE
react-native  how to get current version ，after code push

### ISSUE THREAD

**Issue by yupuyang** [facebook/react-native#20000]
react-native  how to get current version ，after code push
how to git label v20

│ Label │ Release Time │ App Version │ Mandatory │ Description │ Install Metrics              │
├───────┼──────────────┼─────────────┼───────────┼─────────────┼──────────────────────────────┤
│ v20   │ Mar 5        │ 1.3.1       │ No        │             │ Active: 11% (541 of 5,046)   │
│       │              │             │           │             │ Total: 628 (522 pending)     │
│       │              │             │           │             │ Rollbacks: 87

**Comment by yupuyang** [comment]
│ Label │ Release Time │ App Version │ Mandatory │ Description │ Install Metrics              │
│ v20   │ Mar 5        │ 1.3.1       │ No        │             │ Active: 11% (541 of 5,046)   │

**Comment by dulmandakh** [comment]
It's specific to Code Push, please read Code Push documentation.
