### ISSUE TITLE
code change wont update on device 

### ISSUE THREAD

**Issue by obiwankenoobi** [facebook/react-native#20013]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.9.4
  Yarn: 1.5.1
  npm: 4.6.1
  Watchman: 4.9.0
  Xcode: Xcode 9.4 Build version 9F1027a
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

## Description
Suddenly I cant see any updates to my code when debugging on device . I tried all solutions here #4357 accept deleting the `index.lock` file inside `.git` because I couldn't find this directory. Note that I just changes the name of my project using [this](https://github.com/junedomingo/react-native-rename) library. (I can't really say if it start when I did it because I rebuild my project only couple of hours later and that when it start to happened).

UPDATE: I get back to the commit before the name has changed but the issue is still exist so I dont think it was the issue

Running `npm start` in my root directory return : 

```
┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│  Running Metro Bundler on port 8081.                                         │
│                                                                              │
│  Keep Metro running while developing on any JS projects. Feel free to        │
│  close this tab and run your own Metro instance if you prefer.               │
│                                                                              │
│  https://github.com/facebook/react-native                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

Looking for JS files in
   /Users/Project/Client


Metro Bundler ready.

Loading dependency graph, done.
```
and when trying to reload or rebuild nothing is changing there.

## SOLUTIONS I TRIED 

I tried to look for `.lock` inside `.git` as suggested here #4357 but I can't find the `.git` directory so I believe it isnt the issue. 

I also tried `rm -rf /usr/local/var/run/watchman && brew uninstall watchman && brew install watchman` as suggested here #10889 without any luck.

Along the route I tried as well `watchman watch-del-all` and `rm -fr /usr/local/var/run/watchman/$USER-state` nothing seems to work!

## UPDATE

after all my phone wasn't logged in to the wifi so the debugger couldn't work.

**Comment by Tejas-narola** [comment]
We have to face the same issue in ios, please let me know how to solve it.

**Comment by hamidjafari** [comment]
I had similar problem that you've faced.
i tried all the solutions that you've mentioned and none of them worked.
but create `metro.config.js` with following setting worked for me.
`module.exports = { resolver: { useWatchman: false } };`
[https://stackoverflow.com/a/53411414/2611020](url)
hope this help

**Comment by crastyle** [comment]
same issue
