### ISSUE TITLE
iOS - Zoomed/Unzoomed content in ScrollView gets offset on device rotation

### ISSUE THREAD

**Issue by adrienbataille** [facebook/react-native#20016]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment

```
info Fetching system and libraries information...
System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 366.79 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.18.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_181 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Description

On iOS, when the content in the scrollview is zoomed (or unzoomed), and I rotate the device, it gets a weird offset.
If I rotated back the device, this content offset stays even I try to scroll or zoom / unzoom.

Here some pictures step by step:

* Initial launch
<img width="526" alt="screenshot_1" src="https://user-images.githubusercontent.com/1434301/42233901-d5e96976-7ec0-11e8-83a6-0060c850dee5.png">

* Unzoom the content
<img width="526" alt="screenshot_2" src="https://user-images.githubusercontent.com/1434301/42233903-d8c85d3c-7ec0-11e8-9f18-fa24f070e000.png">

* Rotate the device to landscape
<img width="848" alt="screenshot_3" src="https://user-images.githubusercontent.com/1434301/42233913-db27f420-7ec0-11e8-989d-a8e998690477.png">

* Rotate the device to portait
<img width="526" alt="screenshot_4" src="https://user-images.githubusercontent.com/1434301/42233918-ddbacb36-7ec0-11e8-98eb-fabbd35bb052.png">

## Reproducible Demo
You can find a MCVE here: https://github.com/adrienbataille/test-react-native

**Comment by adrienbataille** [comment]
I still have this bug after have updating to the latest version of react-native and I have updated my MCVE: https://github.com/adrienbataille/test-react-native

Here the new environnement info
```
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.5
      CPU: x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 4.07 GB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 24.0.3, 25.0.0, 27.0.2
        API Levels: 19, 22, 23, 24, 25
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

**Comment by turbuorange** [comment]
I got this bug too on my project with iPad.
Thanks to report it!

**Comment by adrienbataille** [comment]
Updated first post with latest info from `react-native info`.

**Comment by naimmustafa** [comment]
I am having a similar issue on Android. I am using a flat list to render apps feed. I have over 2000 item and I am using best practices to render that list partially. My problem is every time I rotate the screen all the card components in my list re-renders themselves regardless of the flat list updated or not. This causes styling issues every time screen rotates.  Some of the cards are even overlaps or content cuts out

**Comment by TheSavior** [comment]
I was able to repro this on 0.59 with the code snippet in the provided sample app:
```
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  View,
  ScrollView,
} from 'react-native';

const instructions = Platform.select({
  ios: 'Press Cmd+R to reload,\n' +
    'Cmd+D or shake for dev menu',
  android: 'Double tap R on your keyboard to reload,\n' +
    'Shake or press menu button for dev menu',
});

type Props = {};
export default class App extends Component<Props> {
  render() {
    return (
      <View style={styles.container}>
        <ScrollView
          zoomScale={1}
          minimumZoomScale={0.4}
          maximumZoomScale={4}
          centerContent
        >
          <View style={styles.wrapper}>
            <Text style={styles.welcome}>
              Welcome to React Native!
            </Text>
            <Text style={styles.instructions}>
              To get started, edit App.js
            </Text>
            <Text style={styles.instructions}>
              {instructions}
            </Text>
          </View>
        </ScrollView>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'stretch',
    backgroundColor: 'blue',
  },
  wrapper: {
    flex: 1,
    alignSelf: 'stretch',
    backgroundColor: 'red',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
```

**Comment by edwardmsmith** [comment]
I'm running across this as well on iOS.  I've tried all sorts of things to try to reset the size, position, zoom, etc. of the scrollview on rotation, but have not found anything that alleviates the issue.

**Comment by hiteshagja** [comment]
Issue is still there. Refer this post made by one of my team member. 
https://github.com/facebook/react-native/issues/26814

**Comment by fabriziobertoglio1987** [comment]
Tested on android react-native master branch. I could not zoom out. I can not reproduce on Android. Thanks.

<p align="center">
  <img src="https://user-images.githubusercontent.com/24992535/82190619-930f1180-98f1-11ea-9e81-de369cf8ea4d.png" width="500"/>
</p>
<p align="center">
  <img src="https://user-images.githubusercontent.com/24992535/82190623-93a7a800-98f1-11ea-8c36-020ffbcf3e73.png" width="200"/>
</p>

**Comment by adrienbataille** [comment]
@fabriziobertoglio1987 I have updated to title and the description. My issue is on iOS and I have never used and tried it on android.
