### ISSUE TITLE
[Navigator] Transition color

### ISSUE THREAD

**Issue by PhilippKrone** [facebook/react-native#2003]
As discussed in https://github.com/facebook/react-native/pull/654, the transition color of a navigator was set to transparent. However, there are use cases in which a different transition color might be useful. In my case, I have nested navigators and I see the parent navigator shining through when making transitions in child navigators. Is it reasonable to make this property dynamic? If it is, I'm going to make a PR here.

Regards
Philipp

**Comment by sahrens** [comment]
Sounds reasonable indeed :)

**Comment by PhilippKrone** [comment]
Just pushed a PR:
https://github.com/facebook/react-native/pull/2005

**Comment by ide** [comment]
Could you wrap the Navigator in a View with the desired background color to achieve the same effect?

**Comment by PhilippKrone** [comment]
as discussed in the PR, thats working.
