### ISSUE TITLE
Unable to use 'react-native-init {project}' (error)

### ISSUE THREAD

**Issue by alexharrisdcj** [facebook/react-native#20039]
I've been using React Native for a few weeks now, working through several learning projects.

However, I'm no longer able to init a new project, as I get the following error. I've used the init command as recently as a few days ago. Any ideas?

```
C:\ReactNative\{project}\node_modules\react-native\local-cli\cliEntry.js:30
import type {CommandT} from './commands';
^^^^^^

SyntaxError: Unexpected token import
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (module.js:613:28)
    at Module._compile (C:\ReactNative\manager3\node_modules\pirates\lib\index.js:91:24)
    at Module._extensions..js (module.js:660:10)
    at Object.newLoader [as .js] (C:\ReactNative\manager3\node_modules\pirates\lib\index.js:96:7)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
```

**Comment by LucasShaffer** [comment]
I am getting the same issue. I was able to create a new project as recently as last night and now running 'react-native init {project-name}' fails every time. I tried multiple version of NPM and NODE and have not found a way for it to work.

**Comment by pratikghosalkar** [comment]
Here's workaround, this is a known bug in RN 0.56
[https://stackoverflow.com/questions/51178688/error-creating-new-react-native-project](https://stackoverflow.com/questions/51178688/error-creating-new-react-native-project)

**Comment by devgunyogesh** [comment]
Still there...

import type {CommandT} from './commands';
^^^^^^

SyntaxError: Unexpected token import

**Comment by jovanxua** [comment]
same here when invoking react-native init <projectname>. I think we need to file new issue and follow new issue template? Any updates?

**Comment by N-Kumbhare** [comment]
Heyy..

You are using new version of react native please follow this and create new new project --
Definitely you will be not having any error while creating new project ..

react-native init --version="0.55.4" {projectName}

This was happened only because of newer version of react natve

Thanks!

**Comment by avinashkumar3497** [comment]
did this:
react-native init --version="0.55.4" {projectName}
And it worked

**Comment by faizlo** [comment]
Has any one found a solution to this issue?
I am using
`react-native init --version="0.55.4" {projectName}` when I work on Win 10. But if I try to install Redux, RN gets updated to the latest version and get this error back.
Your help is appreciated.

**Comment by jovanxua** [comment]
@faizlo  can you show us your package.json after project init ?
the command is below:

react-native init <proj_name> --version react-native@0.55.4
