### ISSUE TITLE
LineHeight dosen't work equally with english character and chinese word

### ISSUE THREAD

**Issue by zangguodong** [facebook/react-native#20046]
[✓] Review the documentation: https://facebook.github.io/react-native
[✓] Search for existing issues: https://github.com/facebook/react-native/issues
[✓] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
  OS: macOS High Sierra 10.13.3
  Node: 8.11.1
  Yarn: 1.7.0
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4 Build version 9F1027a
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: ~0.55.2 => 0.55.4

## Description
We meet this  problem.when we set parent View width to 20,and inner text as 'aaaaaaaaaa'.We set parent View as lineHeight=20,height=40.so we espect it as showing 2 lines.In English word situation,it work right and show 2 lines, we feel grateful for this  modification.However, when we write Chinese character as '啊啊啊啊啊', it dosen't work right, and just show 1 line. We find that we need to  set height to 42,and requirement met.

## Reproducible Demo
Here is an example
[https://snack.expo.io/ryk2MdjGX](https://snack.expo.io/ryk2MdjGX)

**Comment by ykforerlang** [comment]
Same problem here :'(
