### ISSUE TITLE
After upgrading to React-Native 0.56 app doesn't start

### ISSUE THREAD

**Issue by nicomontanari98** [facebook/react-native#20042]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.5
      CPU: x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
      Memory: 348.96 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.6.0 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.1.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 23.0.3, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 27.0.3
        API Levels: 23, 24, 25, 26, 27
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: 16.4.6 => 16.4.6 
      @types/react-native: 0.55.27 => 0.55.27 
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 
    npmGlobalPackages:
      create-react-native-app: 1.0.0

## Description
Terminal error: `bundling failed: TypeError: Cannot read property 'bindings' of null`
React Native Debugger error: 
![image](https://user-images.githubusercontent.com/15747776/42309565-36dd3108-8039-11e8-8b5a-f3cf879d5ce6.png)

**Comment by markholland** [comment]
Likely Babel related, 0.56 uses Babel 7, we had to add the latest beta as a dependency to our project.

**Comment by kelset** [comment]
I'll close this in favour of #19827, which is where we are "collecting" all the Babel-config related issues.

**Comment by Poukai** [comment]
@krystofbe How to update to 5.0.0 the on npm has a broken github like and its latest version is 4.0.0

**Comment by supermock** [comment]
@Poukai Very simple, just run: `yarn add babel-preset-react-native@5.0.0 --dev`
