### ISSUE TITLE
Sub-item deletion of listview

### ISSUE THREAD

**Issue by kaka2928** [facebook/react-native#2004]
I want use a listview with delete function in follow steps:

1.tap a row which have a sub component of TouchableOpacity;
2.in the onPress function, make a copy of the listview.dataSource._dataBlob.s1, then delete the rowData of this row,then pass the new dataSource by dataSource.cloneWithRows().

But sadly, I faild to achieve this function.

-----------------
When I read the introduction of cloneWithRows API in ListViewDataSource,find there is a confused note:

   * Note: This function does NOT clone the data in this data source. It simply
   * passes the functions defined at construction to a new data source with
   * the data specified. If you wish to maintain the existing data you must
-----------------
   * handle merging of old and new data separately and then pass that into
-----------------
   * this function as the `dataBlob`.
   */

What's the correct method to deal with existing data?
Thx

**Comment by brentvatne** [comment]
Hi there! This type of question is best suited for StackOverflow, we are more concerned here with bugs and critical missing features. If it turns out that there is a bug, please feel free to post here again :smile:
