### ISSUE TITLE
[0.57.0 Android BUG] Image display to wrong position when nested in Text component

### ISSUE THREAD

**Issue by tikkichan4** [facebook/react-native#20061]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.4
      CPU: x64 Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz
      Memory: 679.02 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.9.3 - /usr/local/bin/node
      Yarn: 1.9.2 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 23.0.2, 23.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.2, 27.0.3
        API Levels: 23, 25, 26, 27
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: 0.57.0 => 0.57.0 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
## Description

In 0.55.4, the image can be normally displayed when nested in Text component with PixelRatio on Android.
<img src="https://upload.cc/i1/2018/07/06/fInPQU.png" />

In 0.57.0, we don't need to use PixelRatio for displaying image normally anymore. But there will be some weird spacing on top of the image when nested in Text component.
<img src="https://upload.cc/i1/2018/07/06/zZS8qi.png" />

## Reproducible Demo
Image can be display normally with no bug in 0.55.4:

```
import React, {Component} from 'react';
import {PixelRatio, Image, StyleSheet, Text, View} from 'react-native';

export default class App extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.text}>
          123
          <Image
            resizeMode="contain"
            source={{uri: 'http://via.placeholder.com/65x94'}}
            style={{width: 65 * PixelRatio.get(), height: 94 * PixelRatio.get()}}
          />
          456
        </Text>
      </View>
    );
  }
}
const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  text: {
    backgroundColor: 'pink'
  }
});
```
Some weird spacing on top of image in 0.57.0:
```
import React, {Component} from 'react';
import {Image, StyleSheet, Text, View} from 'react-native';
export default class App extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.text}>
        123
          <Image
            resizeMode="contain"
            source={{uri: 'http://via.placeholder.com/65x94'}}
            style={{width: 65, height: 94}}
          />
          456
        </Text>
      </View>
    );
  }
}
const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  text: {
    backgroundColor: 'pink',
  }
});
```

**Comment by tikkichan4** [comment]
I also have the same problem. It is a serious problem for me because my app is supporting text with emoji. And now the layout become so weird. I just decided to downgrade to 0.55.4 util the problem fixed.

**Comment by thlkaitlyn** [comment]
I also have the same problem. It is a serious problem for me because my app is supporting text with emoji. And now the layout become so weird. I just decided to downgrade to 0.55.4 util the problem fixed.

**Comment by tikkichan4** [comment]
Just wanna to update status of the issue. The bug still exists in 0.57.0.
