### ISSUE TITLE
RefreshControl in ScrollView bounses onRefresh

### ISSUE THREAD

**Issue by godofmadness** [facebook/react-native#20081]
## Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 7.10.0
  Yarn: 1.3.2
  npm: 5.8.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  react: ^16.4.1 => 16.4.1
  react-native: ^0.49.5 => 0.49.5

## Description
I have RefreshControl in ListView with refreshing state and onRefresh callback. 

```
return (
        <ListView contentContainerStyle={styles[RENDER_METHOD]}
                  removeClippedSubviews={false}
                  scrollEnabled={true}
                  refreshControl={this.props.refreshControl ? <RefreshControl refreshing={this.state.refreshing} onRefresh={this.onRefresh}/> : undefined}
                  dataSource={this.state.dataSource}
                  renderRow={(card) => this.renderCard(card, RENDER_METHOD)}
        />
    )
```

onRefresh (like all samples)
```
  onRefresh = () => {
    this.setState({
        refreshing: true
    }, async () => {

        await this.loadData();

        this.setState({
            refreshing: false
        });
    });

  }
```

so when hold refresh on list view it bounces after certain amount of time. As i understand it caused by new data load.

**Comment by godofmadness** [comment]
Issue always present at latest version

**Comment by TheSavior** [comment]
This was fixed many versions ago. Are you *sure* this is present on 0.56.0?

**Comment by godofmadness** [comment]
ok, i fully upgraded to 0.56.0 and issue disappeared, thank you.
