### ISSUE TITLE
[0.56.0] Text strings must be rendered within a <Text> component

### ISSUE THREAD

**Issue by jayporta** [facebook/react-native#20084]
- [ x] Review the documentation: https://facebook.github.io/react-native
  - [ x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.5
      CPU: x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 33.70 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.2 - /usr/local/bin/node
      npm: 5.6.0 - /usr/local/bin/npm
    SDKs:

      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 26.0.1, 26.0.2, 28.0.0
        API Levels: 21, 23, 25, 26, 28
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.4.1 => 16.4.1
      react-native: ^0.56.0 => 0.56.0
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

## Description
![simulator screen shot - iphone x - 2018-07-06 at 21 47 13](https://user-images.githubusercontent.com/15250836/42405558-31f60772-8166-11e8-892d-ba1971d43dc4.png)

## Reproducible Demo
I uploaded from 0.55 to 0.56 resolved dependencies, and then this happened when I started the app again. This issue did not exist in 0.55, and I can't seem to find the cause of this error since there is no text outside of a Text component in any of the recognizable locations listed in the error screen.

**Comment by jayporta** [comment]
There are no spaces between components.

**Comment by dulmandakh** [comment]
This usually happens when you do inline conditional rendering like {var &&
<MyComponent />} which will render MyComponent if var is true. But it tried
to render value of var. The fix is change conditions to make sure it's
Boolean expression like {var !== 0 && <MyComponent/ >}.

**Comment by jayporta** [comment]
That was it. Thanks. This is a new problem as of React Native 0.56.

**Comment by ravirajn22** [comment]
@jayporta this is not a new problem, this is how it's working for a long time.Please Close this issue.

**Comment by jayporta** [comment]
But the app I’m building tabs perfectly fine until I upgraded to 0.56. So
obviously it’s related.

**Comment by radko93** [comment]
Just don't pass values when rendering, why do it things it's a bug in RN?

**Comment by radko93** [comment]
@facebook-github-bot expected

**Comment by Zohaibmalikdev** [comment]
@jayporta  i got the same issue today, and i don't understand your solution since you mention it's solved. can you give a detail answer on what exactly is causing this issue to occur.

**Comment by radko93** [comment]
@dulmandakh posted a solution. Don't pass values to render function and you will be ok.

**Comment by jayporta** [comment]
@Zohaibmalikdev @radko93

Here’s an example of what broke the majority of my components in React Native 0.56 but never in previous versions:

{
myValue
? <View>...</View>
: null
}

(The null is there as a fallback for Android, which will crash without it when rendering a Text component. That error is notoriously difficult to track down if you’ve been working on iOS and test on Android hours or days later, but that’s irrelevant.)

I’ve been building React and React Native apps for my employer for a year now and have *never* run into this issue, which is what leads me to believe that it’s a new issue with React Native 0.56. 

To answer your question, @radko94 (why do you think it’s a bug in RN?):

If a problem never occurred before and it suddenly began to occur immediately after upgrading, then common sense tells me that the error was introduced when upgrading.

**Comment by mrfair** [comment]
@Zohaibmalikdev  Don't return string value outside `<Text></Text>`

**Comment by radko93** [comment]
@jayporta I can understand your frustration, I will reopen this for now for more investigation.

**Comment by kelset** [comment]
So, the error clearly states that "Text strings must be rendered within a <Text> component", but in this small snippet by @jayporta I can't see any text.

My guess is that that snippet has some Text somewhere (?) without a Text tag. In the [changelog](https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md) there are clear mentions to Text related cleanup/fixes/refactors (like these two [1](https://github.com/facebook/react-native/commit/06c05e744d8af9582bde348210f254d76dae48b9) [2](https://github.com/facebook/react-native/commit/ab92c00245c0ce717819ddb0ab8b9204d4c13c34)), so until proven otherwise via a repo with a repro of a bug, I have to assume that the bug was in fact pre-exisiting in your code and this refactoring simply "bubbled it up".

**Comment by Yuto-I** [comment]
I got the same issue.
In my situation, when I wrote comments in components, the error occured.
After removing them, it solved.

Below code got the error.
```
...
return (
      <View style={styles.containerStyle}>
        <ScrollView> // Comments
          <GenreContainer genres={genres} navigation={navigation} />
...
```

Below code didn't get the error
```
...
return (
      <View style={styles.containerStyle}>
        <ScrollView>
          <GenreContainer genres={genres} navigation={navigation} />
...
```


I think this is React Native 0.56's problem...

**Comment by radko93** [comment]
@xtrycatchx probably the errors is the same, but the reason is different. At least for @jayporta

**Comment by xtrycatchx** [comment]
yes, i agree you are right @radko93 thanks. Im just adding the comment here in case there will be others who experienced the same like i do.

**Comment by ulises-castro** [comment]
I had this problem, it seems occured when inside of your Text tags its empty, like this <Text></Text>, because Text component can't be empty.

**Comment by tezahzulueta** [comment]
Hi, 

I'm having the same issues. I tried the solutions in the comment but nothing works. Please help. I'm stuck.

<img width="1280" alt="screen shot 2018-07-16 at 11 12 08 am" src="https://user-images.githubusercontent.com/7932103/42741940-1d3554f2-88e9-11e8-810d-26d93416b040.png">

**Comment by tezahzulueta** [comment]
Hi @kelset

Here's the repo

https://github.com/tezahzulueta/authentication

**Comment by kelset** [comment]
@tezahzulueta you had in `Header` a ; after the `Text` component, [here](https://github.com/tezahzulueta/authentication/blob/a0f0261af38bca80722874d4bb31c6dde69faf74/src/components/common/Header.js#L12).

Since OP is not replying I'll assume it was actually a non bug. Closing this until further evidences that there is actually a bug.
