### ISSUE TITLE
Passing a number to fontWeight should have a better error message, or be supported

### ISSUE THREAD

**Issue by lwiecek** [facebook/react-native#20080]
## Environment
```
Environment:
  OS: macOS High Sierra 10.13.5
  Node: 8.0.0
  Yarn: 1.3.2
  npm: 5.0.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4697961

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz => 0.55.4
```
## Description
`fontWeight: 500` style is crashing the app.
I know only string values are allowed but perhaps (if casting to a string is not an option) there should be some sort of validation and RSOD in this case.

## Reproducible Demo
https://snack.expo.io/SyDg_1aGQ
```
import React, { Component } from 'react';
import { Text } from 'react-native';

export default class App extends Component {
  render() {
    return (
      <Text style={{fontWeight: 500}}>test</Text>
    );
  }
}
```

**Comment by lwiecek** [comment]
Exported Expo's Snack to XDE and ran `yarn install` followed by `react-native info`.

**Comment by TheSavior** [comment]
Does this repro on 0.56.0?

**Comment by kuangmichael07** [comment]
Hi @TheSavior Eli,
I am trying to make first contribution, can I give it a try? Thank you

**Comment by lwiecek** [comment]
You may find this helpful - I checked the behavior on the recent react-native version:

- When fontWeight is set using inline `style={{fontWeight: ...}}` I was getting exceptions coming from the the native code (like using number instead of string)
- When fontWeight is set using stylesheet the exceptions were coming from react-native stylesheet validator

I think the real issue might be that stylesheet validation isn't triggered for inline styles.
