### ISSUE TITLE
[Packager] Error resolving modules in 0.8.0-rc

### ISSUE THREAD

**Issue by evansolomon** [facebook/react-native#2009]
I am trying to update an app to 0.8.0 to get the `renderScrollComponent` changes (I had previously been maintaining a fork with that patch). I ran into a problem in the packager when loading a bunch of modules. I tracked it down to the `_resolveHasteDependency` function in `DependencyResolver` [here](https://github.com/facebook/react-native/blob/v0.8.0-rc/packager/react-packager/src/DependencyResolver/DependencyGraph/index.js#L220-L258).

I am using NPM 3.0.0 here, so I also applied the change from #1752.

These are the modules that cause errors:

* ReactChildren
* ReactDefaultPerf
* ReactInstanceMap
* ReactPropTypes
* TouchEventUtils
* cloneWithProps
* emptyFunction
* invariant
* keyMirror
* keyOf
* onlyChild
* requestAnimationFrame
* warning

In these cases, the `_hasteMap` variable doesn't have a key for the module name, so an error gets thrown. I haven't figured out the actual problem yet, but since the relevant code came from a pretty big change (2d4055e) I wanted to see if anyone had any ideas to start with.

I tried starting a new project with v0.8.0 but the default app seemed to work fine. Obviously that means this could be a problem with my specific app, but since none of these are modules that I actually load myself it seemed like React Native is probably involved as well.

**Comment by soliury** [comment]
I also meet this error in 0.7.1

```
Unable to resolve module ../components/overlay/UserOverlay from /Users/soliury/soliury/work/git/noder/app/containers/Home.js
Unable to resolve module ../components/TopicsInTab from /Users/soliury/soliury/work/git/noder/app/containers/Home.js
Unable to resolve module ../components/overlay/MessageOverlay from /Users/soliury/soliury/work/git/noder/app/containers/Home.js
```

**Comment by amasad** [comment]
Most likely that this is an issue with your existing code and we just started warning about them

**Comment by brentvatne** [comment]
You might have to clean up the packager cache @evansolomon - if that doesn't work, then it may be as @amasad suggests
