### ISSUE TITLE
evaluating '_iterator2[typeof Symbol === "function" ? Symbol.iterator : "@@iterator"]()'

### ISSUE THREAD

**Issue by emmadal** [facebook/react-native#20090]
## Description
When i import some component in the `App.js` and install some packages like react-native-fontawesome, i found this error  since `react-native@0.56`:
`undefined is not a function (evaluating '_iterator2[typeof Symbol === "function" ? Symbol.iterator : "@@iterator"]()')
handleUpdate
    index.delta?platform=android&dev=true&minify=false:58236:198
add
    index.delta?platform=android&dev=true&minify=false:58316:19
registerWarning
    index.delta?platform=android&dev=true&minify=false:56344:28
warn
    index.delta?platform=android&dev=true&minify=false:56300:34
onUnhandled
    index.delta?platform=android&dev=true&minify=false:27356:21
onUnhandled
    index.delta?platform=android&dev=true&minify=false:27768:30
<unknown>
    index.delta?platform=android&dev=true&minify=false:3070:26
_callTimer
    index.delta?platform=android&dev=true&minify=false:2987:17
callTimers
    index.delta?platform=android&dev=true&minify=false:3194:19
__callFunction
    index.delta?platform=android&dev=true&minify=false:2593:49
<unknown>
    index.delta?platform=android&dev=true&minify=false:2370:31
__guard
    index.delta?platform=android&dev=true&minify=false:2546:15
callFunctionReturnFlushedQueue
    index.delta?platform=android&dev=true&minify=false:2369:21
`

## Environment
`   System:
      OS: Linux 4.15 Ubuntu 18.04 LTS (Bionic Beaver)
      CPU: x64 Intel(R) Core(TM) i5 CPU       M 520  @ 2.40GHz
      Memory: 101.47 MB / 3.64 GB
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 10.6.0 - /usr/bin/node
      Yarn: 1.7.0 - /usr/bin/yarn
      npm: 6.1.0 - /usr/bin/npm
    SDKs:
      Android SDK:
        Build Tools: 25.0.0, 26.0.3, 28.0.1
        API Levels: 23, 26, 27, 28
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 
    npmGlobalPackages:
      react-native-cli: 2.0.1
`

**Comment by okuskov** [comment]
@emmadal , did you solve the issue? I have the same one

**Comment by emmadal** [comment]
no, i have installed a older version 0.54.3 for work with that. it's a stable version of react-native
