### ISSUE TITLE
Upload a picture to a server

### ISSUE THREAD

**Issue by jnak** [facebook/react-native#201]
Hey,

I'm trying to upload to a server a picture from the Camera Roll. 

I can access an image representation that looks like this:
```
{
"node": {
  "type":"ALAssetTypePhoto",
  "group_name":"Camera Roll",
  "location":{},
  "image" :{
    "isStored":true,
     "width":1280,
    "uri":"assets-library://asset/asset.JPG?id=AC072879-DA36-4A56-8A04-4D467C878877&ext=JPG",
    "height":850},
    "timestamp":1405312098
  }
}
``` 

I was thinking of (somehow) read the binary file, convert that to base64 and post this as JSON using fetch. Is that the best way to upload this to a server for now ?

**Comment by jaygarcia** [comment]
> FYI transferring data back and forth between JS and Obj-C is relatively slow 
> 
I've found that React Native's bridge impl seems to be slower that cordova's :(

I don't have specific bench marks, but if the queue is rapidly utilized, the UI becomes non-responsive whereas with a cordova app, the UI works fine.  

I understand the mechanics of why a RN app would be come unresponsive, but I just had to add my experience.  

JG

:: sent from my mobile device ::

**Comment by jnak** [comment]
I d be down implementing this in objective c, but since I know you guys are
about to release the internal fb component, I d rather spend my time doing
something else :)

**Comment by sahrens** [comment]
It might actually be awhile (or never) before we release the networking module we use internally, so I wouldn't wait for that if you need the functionality...

**Comment by scottdixon** [comment]
I faced the same issue. Here's a work around for the time being. https://medium.com/@scottdixon/react-native-posting-uploading-ios-camera-roll-images-to-a-server-6c74766154cd

@ide is correct, it's really slow transferring data back and forth. Thumbnails seem to hold up OK.

**Comment by jnak** [comment]
awesome!

**Comment by brentvatne** [comment]
@scottdixon - awesome :smile:

For the lazy, here's a link [@scottdixon's github repo](https://github.com/scottdixon/react-native-upload-from-camera-roll)

**Comment by kamilkp** [comment]
Check out my [react-native-file-transfer](https://github.com/kamilkp/react-native-file-transfer). It makes the request directly from Obj-C which is faster.

**Comment by lifuzu** [comment]
@kamilkp Thank you for the sharing, the lib is really cool.

**Comment by josebalius** [comment]
@kamilkp your plugin doesn't seem to work any more in 0.8.0-rc, any ideas why?

**Comment by nicklockwood** [comment]
This feature is now built into React Native's XHR implementation anyway. You can attach multiple file attachments to a request body by specifying local file or asset library urls.

**Comment by unknownexception** [comment]
In case anyone is interested XHR upload example: https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/XHRExample.js#L184

**Comment by narychen** [comment]
Though it's closed, I wonder how to compress an image before uploading in react-native because the image in camera roll is too big.

**Comment by nicklockwood** [comment]
@narychen the best option is currently to use the ImageEditor module to resize the image, then upload the resized one.

**Comment by narychen** [comment]
It seems ImageEditor not available on android. And the compression quality is not specified.
Maybe write a native module is a better choice?

**Comment by nicklockwood** [comment]
@narychen you're right that ImageEditor doesn't support a quality parameter, but we could probably add one - resizing the image will make the file much small though, and you probably don't need it at 8MP resolution.

ImageEditor is backed by a native module (ImageEditingManager), and it's available on Android, but it looks like it hasn't been open-sourced yet for some reason - @dmmiller, can we move this to the Android OSS folder? - it's already in iOS open source.

**Comment by dmmiller** [comment]
@nicklockwood  I can look into that.

**Comment by anback** [comment]
let me kow when there is progress! +1!

**Comment by dmmiller** [comment]
@mkonicek and @bestander are working on open sourcing modules.  They would know better if this is planned and when.

**Comment by bestander** [comment]
Today I plan to release maps.
And this one is next in queue.

**Comment by bestander** [comment]
And Image editor is released to master.

**Comment by apastel** [comment]
Anybody have an Android solution for OP's problem?

**Comment by mozillo** [comment]
Android+1

**Comment by anton6** [comment]
For those who need a solution for Android, have a look if this works for you.

https://github.com/Wraptime/react-native-get-real-path

**Comment by Mastergalen** [comment]
Is it possible to upload an image using `fetch()` instead?

**Comment by woniesong92** [comment]
This is a solution that works for Android as well. Copied from https://github.com/marcshilling/react-native-image-picker/issues/31, written by alvaromb.

```
export function postData (url, params, fileURL) {
  let data = new FormData()
  if (fileURL) {
    data.append('image', {uri: fileURL, name: 'image.jpg', type: 'image/jpg'})
  }
  _.each(params, (value, key) => {
    if (value instanceof Date) {
      data.append(key, value.toISOString())
    } else {
      data.append(key, String(value))
    }
  })
  const config = {
    method: 'POST',
    headers: {
      'Accept': 'application/json',
      'Content-Type': 'multipart/form-data; boundary=6ff46e0b6b5148d984f148b6542e5a5d',
      'Content-Language': React.NativeModules.RNI18n.locale,
      'Authorization': 'Token ABCDEF123457890',
    },
    body: data,
  }
  return fetch(API_URL + url, config)
    .then(checkStatusAndGetJSONResponse)
}
```

**Comment by Rashhh** [comment]
Can anybody would tell me where I am getting it wrong? using form data to upload image to server.

         uploadData()
  {

   let formdata = new FormData();
   formdata.append("case_date", "2016-12-27")
   formdata.append("case_time","17:32")
   formdata.append("category",1)
   formdata.append("description", "this is car accident")
   formdata.append("image_list", {uri: 'file:///storage/emulated/0/DCIM/IMG_20161227_170739.jpg', name: 'IMG_20161227_170739.jpg.', type: 'multipart/form-data'})


    fetch('myapi',{
      method: 'post',
      headers: {  
                'Content-Type': 'multipart/form-data', 
                'Authorization':'Bearer '+'sdlDpbzyp1DfqcX7ZJ74FLi8WHha06'

             },
    body: formdata
    }).then((response)=>{if(response.status==200)
                           {
                             console.log('response:',response);
                             response.json().then((responseData) => { 
                             console.log("inside responseData 200:",responseData);
                             console.log('responseData:',responseData);

                            })}
                            else
                            if(response.status==400)
                            { 
                            response.json().then((responseData) => { 
                            console.log("inside responseData 400:",responseData);

                            })
                            }
            else

             {console.log('hi else',response.status)}


       }).done();


     }

**Comment by ViGi-P** [comment]
@Rashhh did you find a solution???
I'm facing the same problem.

**Comment by JulianKingman** [comment]
If you still have this problem, or encounter it fresh, try adding a boundary to your content type
`'Content-Type': 'multipart/form-data; boundary=someArbitraryStringEndingInDashes--`

**Comment by s123121** [comment]
If anyone coming here searching for why upload to an S3 pre-signed url not working as expect --> `USE xhr! It works`. There is a problem with fetch regarding `Content-Type` header. I don't really understand the detail though
