### ISSUE TITLE
[WebView] in >= 0.7 crashes if wraps by another component

### ISSUE THREAD

**Issue by alinz** [facebook/react-native#2010]
If WebView component in version 0.7 and above, wraps by another custom component, after couple of refreshes, crashes the react-native. 

Here's the code the sample code which causes crash after refresh the view couple of times.

```js
'use strict';

var React = require('react-native');

var {
  AppRegistry,
  View,
  WebView,
  Component
} = React;

class CustomWebView extends Component {
  reload() {
    this.refs.internalWebView.reload();
  }
  render() {
    return (
      <WebView ref="internalWebView" {...this.props}/>
    );
  }
}

var Sample1 = React.createClass({
  componentDidMount() {
    this.refs.AWESOME.reload();
  },
  render: function() {
    var url = "http://google.com";
    return (
      <CustomWebView ref="AWESOME" url={url}/>
    );
  }
});

AppRegistry.registerComponent('Sample1', () => Sample1);
```

Here's the error code
```bash
RCTWebViewManager.m:78
2015-07-15 15:29:12.885 Sample1[32006:13476976] *** 
Terminating app due to uncaught exception 'NSInternalInconsistencyException',
 reason: 'Invalid view returned from registry, expecting RKWebView, got: (null)'
```

So it seems that `viewRegistry` contains only `RCTRootContentView` and `React.findNodeHandle(this.refs[RCT_WEBVIEW_REF])` returns a handler that doesn't exists in `viewRegistry`. 

** btw, It works perfectly fine on 0.6 **

Any thoughts?

**Comment by lightsofapollo** [comment]
seeing this too (and general issues around finding views by ref in 0.7)

**Comment by alinz** [comment]
Thanks @lightsofapollo for confirming it. I thought something seriously wrong with my laptop. 
@brentvatne  I'd really want to use the new `Animated` api in my app but I can't, because of this issue? Any suggestions?

**Comment by brentvatne** [comment]
@alinz - is this happening on 0.8.0-rc.2 as well? This might be a layout only node issue

**Comment by alinz** [comment]
@brentvatne yes it does happen with 0.8-rc2. if I reload the simulator with `cmnd+r` couple of times it crashes.

**Comment by brentvatne** [comment]
@alinz - ok this makes sense, probably what is happening is that you are reloading the view, that action is being batched and then when you refresh the simulator it is actually executed but at this point the backing view no longer exists: https://github.com/facebook/react-native/blob/master/React/Views/RCTWebViewManager.m#L71-L80

**Comment by alinz** [comment]
@brentvatne I might be wrong but when we reload the app by using `cmnd+r`, react-native will keep the old components? or create a brand new component? Why this is not happening in 0.6 and below? :( I think I should start diff and see what has been changed on those files.

**Comment by brentvatne** [comment]
It will not keep the old components - no idea why it's not happening in 0.6 and below. Can you reproduce this without cmd+r?

**Comment by lightsofapollo** [comment]
In my case this happens at "boot" no refreshing required.

**Comment by brentvatne** [comment]
Thanks @lightsofapollo - can you post the code so whoever wants to work on this can have some test cases?

**Comment by liuda101** [comment]
@lightsofapollo please..

**Comment by lightsofapollo** [comment]
Hrm- let me try to reduce a test case... I cannot post the original code.

**Comment by lightsofapollo** [comment]
Okay after a minimum of digging it turns out that it's a fairly simple race... It looks like pre 0.7 attempting to access viewRegistry for a particular reactTag was more deterministic (or the race was smaller) ... In my case I wrap my access to viewRegistry in a retry (which itself is only called in addUIBlock blocks).

**Comment by alinz** [comment]
So any updates on this? Any plan to tackle this issue? Any suggestion so I can patch react-native and start using goodies of 0.8? I kind of stuck at 0.6.

**Comment by skitterm** [comment]
I'm broken at 0.8 trying to use @alinz's WebViewBridge... any updates?

**Comment by alinz** [comment]
So there is a hack which I can use to get this example to work. if one wraps `this.refs.internalWebView.reload();` with `setTimeout` with `timeout` of `0`, the crash will be gone. This hack can be used for now until we get the proper patch from react-native's team!

**Comment by alinz** [comment]
@lightsofapollo, would you post a sample code for your retry code?

**Comment by hyusetiawan** [comment]
@alinz I am using your webview bridge and I am getting the same crashes, will the setTimeout reload fix the crash? (it's the same error message) and also, where should the setTimeout live? in componentWillUnmount?

**Comment by alinz** [comment]
@hyusetiawan can you test it on device. Somehow `WebView.getWebViewHandle` returns a different id. I have seen this on Simulator but not running on the device itself.

**Comment by CorpusCallosum** [comment]
I am getting the same issues when loading/unloading instances of the webview inside a ScrollView component.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/webview-in-07-crashes-if-wraps-by-another-component

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
