### ISSUE TITLE
[REACT-NATIVE-WINDOWS] Picker don't work inside a DrawerNavigator

### ISSUE THREAD

**Issue by paulbx81** [facebook/react-native#20108]
- [ ] Review the documentation: https://facebook.github.io/react-native
  - [ ] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Environment:
  OS: Windows 10
  Node: 9.11.1
  Yarn: 1.6.0
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.0.0.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.4.1 => 16.4.1
  react-native: ^0.55.0 => 0.55.4

## Description
When i try to use the <Picker> element inside a StackNavigator it work perfectly but it don't work when i am into a drawernavigator.

For exemple : my login screen : 

`const AuthStack = createStackNavigator({ Login: Login },{headerMode:'none'});`

If i use a Picker inside this screen it will work perfectly : 

![screen1](https://user-images.githubusercontent.com/40029591/42439399-1c11a6c4-8363-11e8-94d3-7807a498fde6.PNG)
![screen2](https://user-images.githubusercontent.com/40029591/42439404-1dcb0d02-8363-11e8-8ac7-bf0396d20316.PNG)

But if i change : 

`const AuthStack = createStackNavigator({ Login: Login },{headerMode:'none'});`

with : 

`const AuthStack = createDrawerNavigator({ Login: Login },{headerMode:'none'});`

my Picker is always visible but nothing append when i try to use it, nothing... and this is the same result for all my other screen..

![screen3](https://user-images.githubusercontent.com/40029591/42439511-67940e66-8363-11e8-8676-609e30d6dbb5.PNG)

## Reproducible Demo

    this.state = {
        villeRisk : "prs",
    }

    <Picker
        selectedValue={this.state.villeRisk}
        style={{ height: 30, width: 200 }}
        onValueChange={(itemValue, itemIndex) => this.setState({villeRisk: itemValue})}
    >
        <Picker.Item label="Toulouse" value="tls" />
        <Picker.Item label="Paris" value="prs" />
    </Picker>

**Comment by kelset** [comment]
It seems to me that this issue actually belongs in the navigation library which you are using, please open one there.
