### ISSUE TITLE
[TabBarIOS] TabBarIOS.Item label kerning scrunched after navigator.pop()

### ISSUE THREAD

**Issue by dizlexik** [facebook/react-native#2011]
I've run into a strange issue where the label character spacing of a TabBarIOS.Item is reduced (scrunched) after a `navigator.pop()`.

This is happening in an app I'm about to push to production but I've also gone ahead and created an example on React Native Playground here: https://rnplay.org/apps/bIXGMQ

To reproduce the issue, tap "Push" on Tab A and then switch over to Tab B and tap on "Pop". Notice the difference in label kerning on the tabs at the bottom.

The example is running on v0.6.0 but I can confirm that this is happening for me currently in v0.8.0-rc.

**Comment by brentvatne** [comment]
@dizlexik - do you have a chance to look into this? Nobody on the team is currently working on TabBarIOS

@ericvicenti - do you have any idea why this might be happening to help guide @dizlexik or other interested contributors?

**Comment by dizlexik** [comment]
I'm a little out of my element when it comes to native iOS development, but I did find this (http://stackoverflow.com/q/27064138/1946792) and the two answers look promising. I imagine something may need to be changed within `/React/Views/RCTTabBarItem.m` but that's about the extent to which I can help out on this. Sorry :/

**Comment by brentvatne** [comment]
Nice find @dizlexik! If someone is interested in looking into this further, feel free to claim this issue! I can help with a code review

**Comment by ide** [comment]
My guess is that Navigator when zeros the width of the scene that is covered up, that triggers some layout bug in UITabBar. A potential fix for this specific issue and one that seems generally less disruptive would be to zero its height instead.

**Comment by brentvatne** [comment]
Interesting idea @ide, a great starting point if someone wants to have a crack at fixing this!
