### ISSUE TITLE
React Native with Genymotion causes a bug

### ISSUE THREAD

**Issue by 3lhagvaasuren** [facebook/react-native#20113]
- [ ] Review the documentation: https://facebook.github.io/react-native
  - [ ] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Environment:
  OS: Windows 10
  Node: 8.11.3
  Yarn: 1.7.0
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.1.0.0 AI-173.4819257

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: ~0.55.2 => 0.55.4

## Description
First, I created new app with create-react-native-app and tested it with expo on my android phone. And that worked fine. But I wanted to test it on my windows. So I decided to install Genymotion and Genymotion came with Virtual Box. After I installed Genymotion with Virtual Box everything did not work properly. I think there are too many issues with it. At least I had to set REACT_NATIVE_PACKAGER_HOSTNAME with proper ip address from ipconfig command. And I still don't know what to fix next. Is there any easier way to test react native app on my windows?

## Reproducible Demo
Let us know how to reproduce the issue. Include a code sample, share a project, or     share an app that reproduces the issue using https://snack.expo.io/. Please follow the guidelines for providing a MCVE: https://stackoverflow.com/help/mcve

**Comment by radko93** [comment]
@facebook-github-bot stack-overflow
