### ISSUE TITLE
injectedJavaScript on WebView doesn't work.

### ISSUE THREAD

**Issue by alinz** [facebook/react-native#2012]
Based on my simple example `` doesn't work. Am I doing something wrong?

Example available on [rnplay](https://rnplay.org/apps/FxUbpQ)

```js

var React = require('react-native');
var {
  AppRegistry,
  WebView
} = React;

var SampleApp = React.createClass({
  render: function() {
    var url = 'http://google.com';
    
    var script = 'alert("Hello")';
    
    return (
      <WebView injectedJavaScript={script} url={url} style={{flex: 1}}/>
    );
  }
});

AppRegistry.registerComponent('SampleApp', () => SampleApp);

module.exports = SampleApp;
```

Expected behaviour : an alert box should popup with `Hello` message

**Comment by alinz** [comment]
@brentvatne  it would be a good idea to have a version number for the Doc on website. It becomes very difficult to keep track of what's available on each version. I have checked the release note and I couldn't find anything related to this issue until I went to source and realized that it has been added to 0.8-stable.

**Comment by pavlelekic** [comment]
+1

It's working if you are passing html as a prop, but if you are using source={{uri: ...}} then it doesn't work.

**Comment by logicalicy** [comment]
FYI for those coming this thread who forgot to set [`WebView` prop `javaScriptEnabled={true}` on Android](https://facebook.github.io/react-native/docs/webview.html#javascriptenabled). With that prop set, `injectedJavaScript` is called.
