### ISSUE TITLE
React Native not work in Node

### ISSUE THREAD

**Issue by silveiralordes** [facebook/react-native#20133]
![node](https://user-images.githubusercontent.com/41028704/42510924-cd35ff72-8426-11e8-821b-a687e7aaacf7.jpg)

I can not create a react native project.
Whenever I run the "react-native init MyProjectName" command it returns me this error as the image

**Comment by nosferatu500** [comment]
+

**Comment by victorhugoweb** [comment]
React 0.56 doesn't work in Windows ;(
nobody tested in Windows before this release 
so sad ;(
