### ISSUE TITLE
[Android] Wrapped multi-line text have extra space on Samsung S8

### ISSUE THREAD

**Issue by jackylimel** [facebook/react-native#20142]
## Environment
Environment:
  OS: macOS High Sierra 10.13.5
  Node: 6.10.3
  Yarn: 1.6.0
  npm: 3.10.10
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: ^16.3.2 => 16.3.2
  react-native: 0.54.2 => 0.54.2

## Description

when displaying multiple line text inside a <Text>, it adds extra spaces on Samsung.

in the sample below, left side is Huawei and right side is Samsung S8, you can see the extra space in the red area.

![img_8489](https://user-images.githubusercontent.com/173646/42545204-e70a4196-84f9-11e8-8c26-e52cc999912a.JPG)

**Comment by lnwanghao** [comment]
This problem still exist on react-native: **0.55.4**

**Comment by YoujustneedAjob** [comment]
may the same issue,in android OS 5.0.2, Text tag seem auto change to next line,can't full in one line.
