### ISSUE TITLE
[ScrollView] Support CollectionView targetContentOffsetForProposedContentOffset:

### ISSUE THREAD

**Issue by fatuhoku** [facebook/react-native#2015]
It's useful to manipulate the scrolling behaviour so that no matter where the user drags, the view would gravitate and 'snap' back towards one of the cells.

**Comment by mrspeaker** [comment]
I'm not sure if this is exactly what you're talking about, but isn't that what [Paging Enabled](https://facebook.github.io/react-native/docs/scrollview.html#pagingenabled) does?

**Comment by fatuhoku** [comment]
@mrspeaker Ah, no I'm actually more talking about CollectionViewLayout's `targetContentOffsetForProposedContentOffset:` method. I wonder how React Native could expose that?

**Comment by ide** [comment]
The way I'd do it is to have JS get notified on start of a scroll gesture -> JS computes its desired target content offset during each frame and sends it to native -> when the user ends dragging and the inertial scroll begins, the native delegate uses the last target content offset it received from JS. There's a couple frames of lag plus it eats CPU with computing unused target content offsets each frame so I don't love this approach though.

**Comment by ide** [comment]
Much better either to build out the architecture for main-threaded JS that runs synchronously or to use paging enabled or the snap scrolling PR that a contributor put up a while ago.

**Comment by brentvatne** [comment]
This would be nice to have, @ide's suggestions are all great as usual. :smile:

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/scrollview-support-collectionview-targetcontentoffsetforproposedcontentoffset
