### ISSUE TITLE
main.jsbundle does not exist

### ISSUE THREAD

**Issue by pearlsrvcs** [facebook/react-native#20179]
## Environment
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.5
      CPU: x64 Intel(R) Core(TM) i7 CPU       M 620  @ 2.67GHz
      Memory: 252.35 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.3 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.1.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
    IDEs:
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.3.1 => 16.4.1 
      react-native: ^0.56.0 => 0.56.0 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

## Description
When I tried to create a archive for loading to TestFlight, I get an error from XCode, saying this is a error with react-native.

## Reproducible DemoReact Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.5
      CPU: x64 Intel(R) Core(TM) i7 CPU       M 620  @ 2.67GHz
      Memory: 252.35 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.3 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.1.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
    IDEs:
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.3.1 => 16.4.1 
      react-native: ^0.56.0 => 0.56.0 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

This project has many libraries, including maps, camera, firebase messaging, push notifications and camera roll. It builds fine in xcode, but throws this error when creating an archive. I have tried deleting the build folder, but get the same error. I have tried building first, and then try to create the archive, but get the same error.

"private": true,
  "devDependencies": {
    "babel-jest": "22.0.6",
    "babel-preset-react-native-stage-0": "^1.0.1",
    "fs-extra": "^4.0.2",
    "jest": "22.0.6",
    "react-test-renderer": "16.2.0",
    "replace-in-file": "^3.0.0"
  },
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "rename": "node ./bin/rename.js",
    "start": "react-native start",
    "test": "jest"
  },
  "jest": {
    "preset": "react-native"
  },
  "dependencies": {
    "fbjs": "^0.8.16",
    "node-fetch": "^2.1.2",
    "react": "^16.3.1",
    "react-native": "^0.56.0",
    "react-native-camera": "^1.1.4",
    "react-native-communications": "^2.2.1",
    "react-native-firebase": "^4.1.0",
    "react-native-fs": "^2.10.14",
    "react-native-image-resizer": "^1.0.0",
    "react-native-maps": "^0.21.0",
    "react-native-push-notification": "^3.0.2",
    "react-native-push-notifications": "^3.0.10",
    "react-native-router-flux": "^4.0.0-beta.31",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0",
    "redux-thunk": "^2.3.0"
  }
}

**Comment by kelset** [comment]
On top of my head, by looking at the package.json:

1.  You need to update the version of React
1. You should not be using "babel-preset-react-native-stage-0": "^1.0.1",
1. You have not updated to Babel 7 in any way (check the [Changelog](https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md#react-native-now-uses-babel-7))
1. you'll need to update jest too
1. are you still able, after a full clean ([example](https://github.com/tiaanduplessis/react-native-surrender)) to run the proj in debug mode?

**Comment by pearlsrvcs** [comment]
I have updated React, jest and began using babel-cli, as instructed by npm when trying to install babel@7.0.0-beta.4.0. The project still builds in debug mode, but when trtying to archive for upload to Apple Store, I get the following error:

/Users/k.mosher/Desktop/nSide/nSideMobile/index.js: Import statement may only appear at top level in file /Users/k.mosher/Desktop/nSide/nSideMobile/index.js at 2:2

+ [[ false != true ]]
+ [[ ! -f /Users/k.mosher/Library/Developer/Xcode/DerivedData/build/Build/Intermediates/ArchiveIntermediates/nsidemobile/BuildProductsPath/Release-iphoneos/nsidemobile.app/main.jsbundle ]]
+ echo 'error: File /Users/k.mosher/Library/Developer/Xcode/DerivedData/build/Build/Intermediates/ArchiveIntermediates/nsidemobile/BuildProductsPath/Release-iphoneos/nsidemobile.app/main.jsbundle does not exist. This must be a bug with'
error: File /Users/k.mosher/Library/Developer/Xcode/DerivedData/build/Build/Intermediates/ArchiveIntermediates/nsidemobile/BuildProductsPath/Release-iphoneos/nsidemobile.app/main.jsbundle does not exist. This must be a bug with
+ echo 'React Native, please report it here: https://github.com/facebook/react-native/issues'
React Native, please report it here: https://github.com/facebook/react-native/issues
+ exit 2

my index.js:
Import { AppRegistry } from 'react-native';
import App from './App';

AppRegistry.registerComponent('nSideMobile', () => App);

When I build for running, it goes fine, the only errors I get is when trying to archive. What am I doing wrong?

**Comment by patrickkempff** [comment]
@pearlsrvcs can you run `react-native bundle --entry-file index.js --platform ios --dev false --bundle-output ios/main.jsbundle --assets-dest ios/assets` and report the results here?

**Comment by pearlsrvcs** [comment]
I literally don't know how, but it's working now. I did the upgrades, as previously explained, I did change my .babelrc: { "presets": ["react-native"] }, build for running, and then archived it, and it worked.

**Comment by kelset** [comment]
Closing then.
