### ISSUE TITLE
[Borders] Halo shows through rounded borders 

### ISSUE THREAD

**Issue by ide** [facebook/react-native#2017]
If you have a view with a background color that is different than the border's color, the background color seeps through the rounded borders.

![example](https://cloud.githubusercontent.com/assets/379606/8715396/2065d03e-2b36-11e5-9f28-f1adbf3d0782.png)

Repro:
```js
  <Text style={styles.marker}>1</Text>

  marker: {
    color: 'white',
    backgroundColor: 'blue',
    width: 17,
    height: 17,
    lineHeight: 15,
    borderWidth: 1.5,
    borderColor: 'white',
    borderRadius: 17 / 2,
    overflow: 'hidden',
  }
```

**Comment by sahrens** [comment]
As far as I can tell this is just an iOS bug - do you know if there is much we can do about it besides custom drawing?  We're already doing come custom drawing for multiple border radii so more custom drawing isn't out of the question.

cc @a2, @nicklockwood

**Comment by nicklockwood** [comment]
Yeah, we still need to fix a few bugs in the border drawing to make it behave more like CSS. I can't tell at a glance whether it's using standard iOS drawing in this case, or our custom implementation, though I'd assume it's the former since the radii are equal.

**Comment by sahrens** [comment]
We've had this problem since before the custom borders so I'm pretty sure it's just an iOS thing.

**Comment by ide** [comment]
Yeah, this is iOS's rendering. Unfortunately it repros on iOS 9b3 as well.

**Comment by admmasters** [comment]
I guess we should file a radar with Apple, in this case. Presumably as iOS9 is believed to be a bug fixing type update, its a good time for things like this to be addressed. Maybe I'm expecting too much :-D

**Comment by grabbou** [comment]
BTW, can this be related somehow to https://github.com/facebook/react-native/issues/1870 ?

**Comment by ide** [comment]
@grabbou This issue is different and has to do with Apple's implementation of cornerRadius.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/borders-halo-shows-through-rounded-borders-

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by nikoloza** [comment]
The same issue here. Problem with borderWidth + borderRadius rendering:

![image](https://user-images.githubusercontent.com/962224/33543886-0439ea1e-d8d9-11e7-9dad-bf45629b3f98.png)

**Comment by nikoloza** [comment]
Actually, using `boxShadows` instead of `border` did the great workaround.
