### ISSUE TITLE
No way to keep a button/touchable focused for AndroidTV?

### ISSUE THREAD

**Issue by JarrodS846** [facebook/react-native#20181]
We're making an AndroidTV application so we're using `TouchableHighlight` as it seems to be the only component with an onBlur and onFocus events. (`onHideUnderlay` and `onShowUnderlay`) which works ok for most cases. Now we had to make a pretty big wrapper around it as it doesn't really have everything you need but it's pretty bad.

The main problem is whenever you press a `TouchableHighlight` it emits it's onBlur event which makes sense for a phone environment which is what it was designed for however on TVs we always want whatever you're on to remained focused however I can't see any way for this to be achieved. We can do tricks with the state to try and keep it focused but it's not very reliable.

Is there some way to achieve this that we missed or a way to make TouchableHighlight not emit an onBlur?

I remember reading somewhere in the docs there were handlers for like onFocus and onBlur for Touchables but we couldn't really figure out how to use them and if they would even work.

Sorry if this is not the place or if it's been answered.

Thank you.

**Environment**
```
Environment:
  OS: Windows 10
  Node: 9.10.0
  Yarn: 1.7.0
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.1.0.0 AI-173.4819257

Packages: (wanted => installed)
  react: 16.4.1 => 16.4.1
  react-native: ^0.55.4 => 0.55.4
```

**Comment by Weetbix** [comment]
Hi Jarrod, I'm also making an Android TV app (with `0.55` atm)

Focusing on touchables works, as long as you are using the D-Pad to navigate the app and not actually clicking it with a mouse. You can bring up the d-pad by pressing Ctrl+Shift+D in the emulator. 

Secondly, you can use Touchable or any of its subclasses for this functionality and blur/focus events, not just `TouchableHighlight`. Touchable has two props `onPressIn` and `onPressOut` which can have handlers attached.
https://facebook.github.io/react-native/docs/touchablewithoutfeedback#onpressin

For example in my App I am styling a card when its focused with something like this:
```
setFocus(focused)
{
    this.setState( { focused } );
}

render() {
    return (
        <TouchableWithoutFeedback
        onPress={() => this.props.onPress && this.props.onPress()}
        onPressIn={() => this.setFocus(true)}
        onPressOut={() => this.setFocus(false)}
        >
            // Render card content, this.state.focused is the focused value
        </TouchableWithoutFeedback>
    );
}
```

**Comment by JarrodS846** [comment]
Yeah i'm using a remote, the problem was the TouchableHighlight clears the underlay when you press it (which is working as expected) however what you just showed will solve this issue.

I'm not sure how we missed these but these seem to be perfect. I'm always getting confused in the documentation because I don't associate `onPressX` with an focus/blur event also in the case of TouchableHighlight it doesn't show these props as they are part of TouchableWithoutFeedback, i suppose we should have looked a little deeper.

Either way TouchableHighlight still seems the better one to use as it has `hasTVPreferredFocus` which TouchableWithoutFeedback does not.

Thank you for the help! I suppose this issue is closed now?

**Comment by Weetbix** [comment]
No worries, by the way `hasTVPreferredFocus` is iOS only 😉

**Comment by JarrodS846** [comment]
It seems to work correctly for me us in Android TV.
