### ISSUE TITLE
Issue with babel-preset-react-native plugin on v0.56

### ISSUE THREAD

**Issue by jinxac** [facebook/react-native#20186]
## Environment
 React Native Environment Info:
    System:
      OS: macOS Sierra 10.12.6
      CPU: x64 Intel(R) Core(TM) i5 CPU       M 540  @ 2.53GHz
      Memory: 302.29 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 9.9.0 - /usr/local/bin/node
      Yarn: 1.3.2 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.2, macOS 10.13, tvOS 11.2, watchOS 4.2
      Android SDK:
        Build Tools: 23.0.1, 23.0.2, 23.0.3, 24.0.0, 25.0.0, 25.0.2, 25.0.3,26.0.0, 26.0.1, 26.0.2, 27.0.0, 27.0.1, 27.0.2, 27.0.3
        API Levels: 23, 24, 25, 26, 27
    IDEs:
      Xcode: 9.2/9C40b - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1
      react-native: 0.56.0 => 0.56.0
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      react-native-rename: 2.2.2

## Description
I have a `babel-preset-react-native` depedency in my package.json. I am using v0.56 of react native.

**Issue**

If I use v5.0.0 of `babel-preset-react-native` the **jest** cases do not run and throw an error as follows  :- 

```
Cannot read property 'throwIfClosureRequired' of undefined (Wh
ile processing preset: "/Users/harkirat/wealthy/thrift/node_modules/babel-pre
set-react-native/index.js")
```

If I use v4.0.0 of `babel-preset-react-native` the react native application does not start as seen in [https://github.com/facebook/react-native/issues/20042](https://github.com/facebook/react-native/issues/20042)

Can someone please help me resolving this?

**Comment by kelset** [comment]
For issues related to jest/testing refer to #19859

**Comment by jinxac** [comment]
thanks a lot @kelset
