### ISSUE TITLE
RNTester Error: No Script URL Provided

### ISSUE THREAD

**Issue by Jonnyapples** [facebook/react-native#20180]
- [ x] Review the documentation: https://facebook.github.io/react-native
  - [ x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-2557M CPU @ 1.70GHz
      Memory: 56.45 MB / 4.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.6.0 - /usr/local/bin/node
      npm: 6.1.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 26.0.3, 28.0.1
        API Levels: 23, 26, 28
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description

-I am simply trying to run the RNTester for the first time in Xcode. The build succeeds, but then I get an error in Xcode and a red screen on the simulator which both read: 

"No script URL provided. Make sure the packager is running or you have embedded a JS bundle in your application bundle.

unsanitizedScriptURLString = (null)"

-In the Metro Bundler terminal window, I am getting this warning: "Warning! Your metro configuration contains a deprecated function "projectRoots". Please, consider changing it to "getProjectRoot" with "watchFolders" (if needed)"

-Also, running "react-native info" in the react-native directory or the RNTester directory yields "Command `info` unrecognized. Make sure that you have run `npm install` and that you are inside a react-native project." The "react-native info" output I posted above is within a different react native directory which I initialized. I don't know if this is related to my problem. 

## Reproducible Demo
To reproduce the problem, git clone https://github.com/facebook/react-native.git, cd react-native, npm install, and then open RNTester/RNTester.xcodeproj (these are the instructions on the facebook/react-native github page.). When Xcode opens, click the run button. Use the latest versions of react-native, node, and Xcode.

**Comment by fztelecomqk** [comment]
I met the same mistake.

**Comment by canastro** [comment]
I have the same issue, tried both with and without CocoaPods.

**Comment by canastro** [comment]
@Jonnyapples I just updated my fork and I don't face this issue anymore
