### ISSUE TITLE
Text wrap still buggy on IOS

### ISSUE THREAD

**Issue by rayj10** [facebook/react-native#20188]
## Environment
Environment:
  OS: Windows 10
  Node: 9.11.1
  Yarn: Not Found
  npm: 5.8.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.1.0.0 AI-173.4670197

Packages: (wanted => installed)
  react: ^16.3.1 => 16.4.1
  react-native: https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz => 0.55.4

## Description
This issue only happens when I wrap my `Text` in a `View` with `flexDirection: 'row'` it seems, and only on IOS (I tried on iphone 5s device)

![img_0218](https://user-images.githubusercontent.com/38281328/42687436-02f01f32-86c3-11e8-9f34-048fd374281c.PNG)

As you can see in the screenshot, the item piece number data is not shown fully nor it is wrapped.

I have tried all available solutions on the internet from preceding posts but still nothing works for me (i.e. wrapping the text in a view with `flex : 1` `width` set to a number, `flexGrow`, `flexWrap`, etc.) 

Here's a snippet of the buggy part:

```
<View style={styles.verticalSubPanel}>
                        <View style={styles.horizontalSubPanel}>
                            <Text style={styles.titleTextStyle}>{"Mac Address:"}</Text>
                            <Text style={styles.textStyle}>{item[keys['mac']]}</Text>
                        </View>
                        <View style={styles.horizontalSubPanel}>
                            <Text style={styles.titleTextStyle}>{"Item Piece No.:"}</Text>
                            <Text style={styles.textStyle}>{item[keys['piece']]}</Text>
                        </View>
                    </View>
```

with the styles defined as:

```
verticalSubPanel: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center'
  },

  horizontalSubPanel: {
    flex: 1,
    flexDirection:'column',
    marginRight:10,
    justifyContent: 'space-evenly',
    marginRight: normalize(3)
  },

  titleTextStyle: {
    flex: 1,
    marginTop: normalize(3),
    fontSize: fontSize.small,
    fontFamily: fontFamily.bold,
    marginLeft: normalize(15)
  },

  textStyle: {
    flex: 2,
    marginTop: normalize(3),
    fontSize: fontSize.small,
    fontFamily: fontFamily.light,
    marginLeft: normalize(15)
  },
```

Can anyone please help me find a workaround and/or fix this soon? 
I found stale posts all over the place with no actual solution, with only case-specific workarounds, and my project is data-forward so I really need it to wrap :(

Thanks in advance for any suggestion!

## Reproducible Demo
Unfortunately snack wouldn't represent the issue as this is a very specific case (all other parts of my app behaving as expected with the wrapping). I can only provide you guys with my repo to inspect: https://github.com/rayj10/WAMS

**Comment by hramos** [comment]
Can you provide a minimal repro? Your current sample depends too much on your particular app.

**Comment by rayj10** [comment]
@hramos That's the thing, I actually tried recreating this on snack, but snack's ios wouldn't represent the same issue.
I copied over the whole template to snack but just without the font size and style editting, and it works with the bare representation of that data.
I suspect the bug might have something to do with the styling I'm applying to the fonts, i.e. size and family, the use of normalize method and combination of all those things that's messing up with the wrap calculations..
not sure how I would recreate this, not really familiar with snack. How would you  suggest I go about this?  Can I just copy over the font files to snack and import normalize etc? you reckon that'll work?

Sorry about the trouble

**Comment by rayj10** [comment]
after comparing the rendering style thoroughly I can confirm that it isn't a bug.

I have been developing on Android mainly and Android would usually cut off the text if it doesn't fit like shown here:
![screenshot_1531794166](https://user-images.githubusercontent.com/38281328/42793272-88f1c54e-89a3-11e8-81d0-031c0e9aa5de.png)

However, when it comes to IOS, it will delete off the entire line of text altogether when it doesn't fit (as shown in original post).

That's why I was under the impression that it simply doesn't wrap because I can still see empty space to be filled and none of the lines have been cut-off. This is the reason I didn't think to check the box size itself.

So having said that, sorry for the false alarm and I'm closing this issue.
