### ISSUE TITLE
the development server returned response code 500

### ISSUE THREAD

**Issue by kishanmahor** [facebook/react-native#20191]
![screenshot_2018-07-13-17-57-14-241_com awesomeproject](https://user-images.githubusercontent.com/24253970/42693049-63432322-86cb-11e8-9e04-48b2a765d4c2.png)

new in reactnative,I am using -g react-native-cli.
cli:2.0.1
react-native:0.55.4

**Comment by kelset** [comment]
Refer to https://github.com/facebook/react-native/issues/19953
