### ISSUE TITLE
How to keep focused element centered within a ScrollView (horizontal) on Android TV

### ISSUE THREAD

**Issue by luigiplr** [facebook/react-native#20199]
Normally on Android TV's when you scroll through a horizontal scroll view it will keep the focused element in the center of the screen until you reach the end of the row.

Is there a way to replicate this behavior with React Native ScrollView's?

Side-note: I have been able to replicate the behavior with `ScrollView.scrollTo` and some `onFocus` handlers however since I'm unable to cancel out the native scroll to behavior when an element is off screen it results in a super janky animation conflict...

## Environment

```PS C:\git\...> react-native info
Environment:
  OS: Windows 10
  Node: 9.10.1
  Yarn: 1.7.0
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.1.0.0 AI-173.4819257

Packages: (wanted => installed)
  react: 16.4.1 => 16.4.1
  react-native: ^0.55.4 => 0.55.4
```

**Comment by Ankush049** [comment]
Has this been resolved in the recent releases? Any workarounds?

**Comment by luigiplr** [comment]
We ended up implementing our own version of the android's focusable framework.
