### ISSUE TITLE
NSAppTransportSecurity produces No bundle URL present error

### ISSUE THREAD

**Issue by yooouuri** [facebook/react-native#20207]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Run `react-native info` in your terminal and paste its contents here.

```
Environment:
  OS: macOS High Sierra 10.13.6
  Node: 8.11.3
  Yarn: 1.7.0
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.3 => 0.53.3
```

## Description
I wan't to add a (local) domain to use http. I add the following to my Info.plist

```
<key>NSAppTransportSecurity</key>
<dict>
  <key>NSExceptionDomains</key>
  <dict>
    <key>example1.test</key>
    <dict>
      <key>NSExceptionAllowsInsecureHTTPLoads</key>
      <true/>
      <key>NSExceptionRequiresForwardSecrecy</key>
      <false/>
      <key>NSIncludesSubdomains</key>
      <true/>
    </dict>
  </dict>
</dict>
```

In debug it crashed with: `No bundle URL present ....`

This is because in `node_modules/react-native/scripts/react-native-xcode.sh` is:

```
if [[ "$CONFIGURATION" = "Debug" && ! "$PLATFORM_NAME" == *simulator ]]; then
```

And I noticed something about `NSAppTransportSecurity `.

When I add the following code and remove the NSAppTransportSecurity part in my plist.info:

```
$PLISTBUDDY -c "Add NSAppTransportSecurity:NSExceptionDomains:example1.test:NSTemporaryExceptionAllowsInsecureHTTPLoads bool true" "$PLIST"
```

The error is gone.

So it have to be something with adding NSAppTransportSecurity and react-native-xcode.sh.

## Reproducible Demo
Because its platform specific, I don't know if I can share some code. Just add the above mentioned NSAppTransportSecurity to your Info.plist and it will crash in Debug mode.

**Comment by KouSyurei** [comment]
Lord, I'd like to ask you what your "example1.test" is pointing to.

**Comment by yooouuri** [comment]
@KouSyurei 

"example1.test" is a local website created with Laravel valet

**Comment by Adenon** [comment]
try this : 

`<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
		<key>NSAllowsArbitraryLoadsInWebContent</key>
		<true/>
		<key>NSAllowsLocalNetworking</key>
		<true/>
	</dict>
</key>`
