### ISSUE TITLE
[Packager] fs crawl

### ISSUE THREAD

**Issue by ilansas** [facebook/react-native#2020]
When I hit "play" on XCode, I'm getting these lines on the packager Console : 

    [13:34:32] <START> fs crawl
    [13:34:33] <END> fs crawl (513ms)

Everything stops there. Does anyone has any idea to get rid of this ? Thanks

**Comment by dsibiski** [comment]
@ilansas `fs crawl` is normal behavior when the packager loads.

Is your app not loading the bundle? Are you sure you have the bundle url set properly in the AppDelegate?

**Comment by ilansas** [comment]
Well... I don't know what was wrong last week, but today everything decided to work. Sorry for the useless post
