### ISSUE TITLE
TextInput.State.currentlyFocusedField() retrun undefined when TextInput with  prop multiline=true

### ISSUE THREAD

**Issue by wangshangming** [facebook/react-native#20203]
## Environment
System:
      OS: macOS High Sierra 10.13.5
      CPU: x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
      Memory: 865.03 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.1.0 - ~/.nvm/versions/node/v10.1.0/bin/node
      npm: 6.1.0 - ~/.nvm/versions/node/v10.1.0/bin/npm
      Watchman: 4.1.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 25.0.2, 26.0.1, 26.0.2, 26.0.3, 28.0.0
        API Levels: 23, 25, 26, 28
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1
      react-native: 0.56.0 => 0.56.0
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

## Description
TextInput.State.currentlyFocusedField() can not work once i add prop multiline=true on TextInput after i upgraded RN from 0.55.4 to 0.56.0

**Comment by canastro** [comment]
@wangshangming please remove the formatting from the environment description, so that the issue can be considered valid.

**Comment by wangshangming** [comment]
@canastro thanks for reminding

**Comment by canastro** [comment]
@janicduplessis did your commit: https://github.com/facebook/react-native/commit/b4b594cec1d91c38faac11a90a787ae692e35296 fixed this issue as well?

**Comment by allmaxgit** [comment]
Some problem even if TextInput is **not multiline**. Any solution?

**Comment by soumyamishra89** [comment]
+1

**Comment by janicduplessis** [comment]
b4b594c does fix this but has not made it into the 0.56 release, I requested a cherry pick in the next release but for now you can either use 0.57-rc or stay on 0.55 until it is cherry-picked.
