### ISSUE TITLE
Scroll Event lags

### ISSUE THREAD

**Issue by jaulz** [facebook/react-native#2021]
I have a requirement that a label inside a view should move with the scrolling of the view (which is obviously standard). But additionally this label should always be visible which means that a certain scroll position the label should stop moving (e.g. x = 0). Unfortunately the scroll event is not enough because there is a small delay and thus it is not synchronous. Is there any possibility to achieve this?

**Comment by ide** [comment]
I believe this isn't possible without having a way to run JS on the main thread or reimplementing ScrollView in JS. In the long term issues like these need to be addressed but currently the two best options are using a ListView if the sticky header behavior meets your use case, or writing your own native view that you expose to JS.

**Comment by sahrens** [comment]
You can do a lot of crazy stuff with goofy sticky header layout.
