### ISSUE TITLE
When  drag the animated view to top(child component out of sight),the child content became shorter

### ISSUE THREAD

**Issue by monkingame** [facebook/react-native#20219]
## Environment
Environment:
  OS: macOS High Sierra 10.13.6
  Node: 10.4.1
  Yarn: 1.7.0
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

## Description
My project is a Animated view based on PanResponder. The Animated.View has three child components.

When I dragged the animated view to top(and child component out of sight of the screen),the child content became shorter and shorter.

## Reproducible Demo
https://snack.expo.io/SkZ396FQm

#Video screenshot
https://www.youtube.com/watch?v=qoXHpZdMRh8&feature=youtu.be

**Comment by guiyom19** [comment]
I have exactly the same problem on iOS (not on Android).
Is this something we can bypass with the 0.55.4 version or do we have to upgrade to 0.56 ?

**Comment by guiyom19** [comment]
I sorted the problem using translateY instead of top

**Comment by jakallergis** [comment]
I have the same problem! This is related to #20215 and is really frustrating. the translateY/X workaround is working but it doesn't change drag the parent layout with it so its not for every scenario. This doesn't fix it.
