### ISSUE TITLE
Cannot Add a child that doesn't have a YogaNode to a parent with out a measure function

### ISSUE THREAD

**Issue by softglance** [facebook/react-native#20225]
The app works on IOS emulator but it gives error on android mobile. 

  - [ ] Review the documentation: https://facebook.github.io/react-native
  - [ ] Search for existing issues: https://github.com/facebook/react-native/issues
This is existing issue on RN 0.46 and it is locked. But the issue is still there. 
  - [ ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Run `react-native info` in your terminal and paste its contents here.

nvironment:
  OS: macOS High Sierra 10.13.6
  Node: 8.11.3
  Yarn: 1.7.0
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  react: 16.4.1 => 16.4.1
  react-native: https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz => 0.55.4

## Description
Describe your issue in detail. Include screenshots if needed. If this is a regression, let us know.

## Reproducible Demo
Let us know how to reproduce the issue. Include a code sample, share a project, or     share an app that reproduces the issue using https://snack.expo.io/. Please follow the guidelines for providing a MCVE: https://stackoverflow.com/help/mcve

**Comment by softglance** [comment]
With different approach and re-organising the components the issue is no more occurring.

**Comment by TheSavior** [comment]
Sorry for the long wait but I think [the fix for this just landed](https://github.com/facebook/react-native/commit/66601e755fcad10698e61d20878d52194ad0e90c).

We were able to repro and fix this issue with this sample code:

```
function PlaygroundContent(props: {}) {
  return (
    <View>
      <Text>
        <View style={{width: 10, height: 10}}>
          <Image source={ANY_IMAGE_SOURCE} />
        </View>
      </Text>
    </View>
  );
}
```
