### ISSUE TITLE
Webview unable to load local assets or from CDNs along with window.postMessage not working in iOS release build

### ISSUE THREAD

**Issue by sja1n** [facebook/react-native#20226]
- [X] Review the documentation: https://facebook.github.io/react-native
  - [X] Search for existing issues: https://github.com/facebook/react-native/issues
  - [X] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.5
      CPU: x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
      Memory: 310.16 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.1 - /usr/local/bin/node
      Yarn: 1.5.1 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 26.0.3, 27.0.3
        API Levels: 26, 27
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1
      react-native: ^0.56.0 => 0.56.0
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1

## Description

I am using webview to display chart for my app using `chartjs` and `jquery` library I am able to view charts fine in iOS debug mode but in release config, all I get is a white screen,  I tried to check if atleast `window.postMessage` was working using setinterval code in my .html file, but I dont get any response from webview.

To check for window.postMessage I have also tried to possible solution from [issue](https://github.com/facebook/react-native/issues/10865) , still its not working

I have tried to inject the complete html code as well instead of serving the html as local asset file, still not success.

This issue is only present in iOS, works perfectly fine for android.

**Comment by hannigand** [comment]
I've got the same problem when trying to render a local HTML file in a WebView. When building an iOS release, I get a blank white screen. It works perfectly fine on the iOS Simulator.

I'm running React Native 0.56. I have another project running 0.55.4 and it this problem does not exist.

I added `onLoadStart` and `onLoadEnd` props to check that the WebView had in fact starting to load (at minimum), none of the callbacks were called.

**Reproducible**: 
```javascript

```
import content from './index.html';

<WebView
  source={content}
  scalesPageToFit={Platform.select({
   ios: true,
   android: false,
  })}
  startInLoadingState
  renderLoading={() => <Loader />}
/>

The HTML file can contain anything. 

It never resolves from `startInLoadingState`.

**Comment by echo8795** [comment]
I also faced a similar problem and this https://github.com/facebook/react-native/issues/19986#issuecomment-401685826 resolved it. Not sure what the issue is.

**Comment by sja1n** [comment]
@echo8795 Thanks for the update, this is working fine. 
But, since I have bit more of the html and i wanted to serve html other JS assets locally, if by some way I could do that it would really be helpful.

**Comment by echo8795** [comment]
@sja1n I think I understand your use case, I had a similar requirement where I was creating a stringified html document for webviews and i had to include js libraries from inside the app bundle. So I added my js and css and font files inside my bundles by adding it `/ios` and `android/app/src/main/assets/_folder_name_`. 

I then used `react-native-fs` library to refer the assets folder inside my js. 
To include those files inside a webview you first need to provide the path of the assets folder as the `baseUrl` of the 'source' prop of webview.
`
const RNFS = require( 'react-native-fs' );

let html = getHTMLToDisplay();

let htmlSource = { html: html };
if ( Platform.OS == Constants.Platform.ANDROID ) {
	htmlSource.baseUrl = "file:///android_asset";
} else {
	htmlSource.baseUrl = RNFS.MainBundlePath;
}

return ( <WebView originWhitelist={[ '*' ]} source={htmlSource} /> )
`

and the html went something like this
`js
function getHTMLToDisplay() {
    if ( Platform.OS == Constants.Platform.ANDROID ) {
		this.mathQuillJSPath = "file:///android_asset/js/mathquill.js";
    } else {
		this.mathQuillJSPath = RNFS.MainBundlePath + "/mathquill.js";
    }

    return '''
	<!DOCTYPE html>
		<html>
			<head>
				<style type="text/css">
                                      // For android(ios automatically adds the fonts in bundles to webviews)
                                     @font-face {
					font-family: 'Quicksand';
					src: url("file:///android_asset/fonts/Quicksand.ttf")
				    }
				</style>
				<script type='text/javascript' src='${this.mathQuillJSPath}'></script>
			</head>

			<body>
			</body>
		</html>
	''';
}
`

**Comment by sja1n** [comment]
Yeah I think maybe I all I needed was to know how to give proper path for html file in ios, Thanks @echo8795  for the info, I'll definitely try this and update.

**Comment by seanyu4296** [comment]
@echo8795 the solution in #19986 worked for me when loading local html files in ios

**Comment by jamonholmgren** [comment]
Migrated to https://github.com/react-native-community/react-native-webview/issues/21 and can be closed here.
