### ISSUE TITLE
react-timer-mixin still contains patent grant

### ISSUE THREAD

**Issue by KevinVlaanderen** [facebook/react-native#20231]
## Environment
n/a

## Description
Last year, Facebook actively dropped the patent grant from e.g. React. Unfortunately, react-timer-mixin still contains it, which raises the alarms we have set up internally.
Would it be possible to drop the patent grant?

## Reproducible Demo
n/a

**Comment by hramos** [comment]
Closing as a duplicate of https://github.com/reactjs/react-timer-mixin/issues/18 (thanks for raising this, by the way).
