### ISSUE TITLE
Xcode Archive error :ld: 283 duplicate symbols for architecture arm64

### ISSUE THREAD

**Issue by miyaliunian** [facebook/react-native#20237]
## Environment
OSX: macOS High Sierra 10.13.5
react-native :0.55.4
Node: 8.0.0
Yarn: 1.3.2
npm: 5.0.0
Watchman: 4.9.0
react: 16.3.1 => 16.3.1
react-native: https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz => 0.55.4

## Description
When I Archive ipa，Xcode prompts for error messages： ld: 283 duplicate symbols for architecture arm64 clang: error: linker command failed with exit code 1 (use -v to see invocation)
But，When I run the simulator，everthing is ok.

### Xcode error info

ld: 283 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### this is my Podfile

# platform :ios, '9.0'

target 'AwesomeProject' do
 
pod 'React', path:'../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', 
    'DevSupport', 
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', 
  ]
  

  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', podspec: '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec' 
  pod 'glog', podspec: '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', podspec: '../node_modules/react-native/third-party-podspecs/Folly.podspec' 	 	
  pod 'react-native-amap3d', path: '../node_modules/react-native-amap3d/lib/ios'
end

**Comment by vovkasm** [comment]
@miyaliunian Are you sure that you removed any links to React libraries from your main xcodeproj file after migrating to CocoaPods (see https://github.com/facebook/react-native/issues/19544 for example)?
