### ISSUE TITLE
measureLayoutRelativeToParent broken in ListView in 0.8.0-rc

### ISSUE THREAD

**Issue by mrspeaker** [facebook/react-native#2023]
I was using `UIManager.measureLayoutRelativeToParent` to get the scroll offset of an element contained in a ListView (click on the element, and the view would scroll so the element was at the top of the screen). This stopped working between `0.7.1` and `0.8.0-rc` (I can't find exactly which commit).

Here's some code showing it. Click on an element and it should log the Y offset - it works in `0.7.1`, but always returns the first element's offset in `0.8.0-rc`. Also, it works as expected in `0.8.0-rc` if it's a ScrollView, not a ListView.

```js
var React = require('react-native');
var UIManager = require('NativeModules').UIManager;
var { AppRegistry, StyleSheet, ListView, Text, TouchableOpacity,} = React;

var Row = React.createClass({
  measure: function () {
    var handle = React.findNodeHandle(this.refs['scrolly']);
    UIManager.measureLayoutRelativeToParent(handle, () => {}, (x, y) => {
      // Should be the y offset of the element. 
      // Works correctly in 0.7.1, 
      // always returns the first element offset in 0.8.0-rc.
      console.log(y); 
    });
  },
  render: function() {
    return (<TouchableOpacity ref={`scrolly`} onPress={this.measure}>
      <Text style={styles.row}>{this.props.txt}</Text>
    </TouchableOpacity>);
  }
});

var dataSource = new ListView.DataSource({rowHasChanged: (r1, r2) => r1 !== r2});
dataSource = dataSource.cloneWithRows([...new Array(50)].map((_, i) => {{txt: 'txt' + i}}));
var test = React.createClass({
  render: function() {
    return (<ListView
      dataSource={dataSource}
      renderRow={row => <Row txt={'test'} />}>
    </ListView>);
  }
});

var styles = StyleSheet.create({
  row: { fontSize: 30, textAlign: 'center', margin: 10, },
});

AppRegistry.registerComponent('test', () => test);
```

**Comment by mrspeaker** [comment]
I traced the error back to this commit: https://github.com/facebook/react-native/commit/bfbc280fb441ad76680b6f6ac00d840d10e5d831

I have a [fix for the immediate problem](https://github.com/facebook/react-native/pull/2024) - but I'm also concerned that `measureLayoutRelativeToParent` will behave unpredictably when you have `stickyHeaderIndices` set: in this case [the children are wrapped](https://github.com/facebook/react-native/blob/bfbc280fb441ad76680b6f6ac00d840d10e5d831/Libraries/Components/ScrollView/ScrollView.js#L283) - and I guess that will change the parent.

**Comment by yamill** [comment]
@mrspeaker @a2 I'm facing a similar issue in 0.8.0-rc.

<strong>onLayout</strong> was working fine in 0.7.1 - calculating the y offset of view in a listview. Now seems to be broken and always returns y: 0, x: 0.

<img width="696" alt="screen shot 2015-07-16 at 11 16 21 pm" src="https://cloud.githubusercontent.com/assets/755943/8739990/b65b148e-2c10-11e5-8121-f2198313354a.png">

**Comment by sahrens** [comment]
yeah, we're going to revert bfbc280
<https://github.com/facebook/react-native/commit/bfbc280fb441ad76680b6f6ac00d840d10e5d831>
and
Layout-only node removal (again) as well...very hard to get right.

On Fri, Jul 17, 2015 at 5:18 AM, Yamill Vallecillo <notifications@github.com

**Comment by sahrens** [comment]
reverts landed - sorry for the trouble.

**Comment by holmesal** [comment]
Is this working for anyone? I'm still having the issue described above, where measuring a ListView cell  returns `0` for `x` and `y`.
