### ISSUE TITLE
After upgrading to React-Native 0.56.0 metro build fails (TypeError: Cannot read property 'ast' of null)

### ISSUE THREAD

**Issue by djschilling** [facebook/react-native#20247]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Run `react-native info` in your terminal and paste its contents here.

```
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.5
      CPU: x64 Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
      Memory: 45.86 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 25.0.1, 26.0.2, 27.0.3, 28.0.0
        API Levels: 23, 25, 26, 27
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 9.4/9F1027a - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1
      react-native: 0.56.0 => 0.56.0
    npmGlobalPackages:
      react-native-cli: 2.0.1
```
## Description
After upgrading to react-native version `0.56.0` my metro build fails with the error message `TypeError: Cannot read property 'ast' of null`.
I also read this issue #19827 but could not fix my issue with the suggestions there.

From the error message it seams the bug is in the metro src.

Detailed error message:

```
error: bundling failed: TypeError: Cannot read property 'ast' of null
    at Object.transform (/Users/david/projects/churchtools-mobile/node_modules/metro/src/reactNativeTransformer.js:167:48)
    at Object.<anonymous> (/Users/david/projects/churchtools-mobile/node_modules/metro/src/JSTransformer/worker.js:204:23)
    at Generator.next (<anonymous>)
    at step (/Users/david/projects/churchtools-mobile/node_modules/metro/src/JSTransformer/worker.js:328:291)
    at /Users/david/projects/churchtools-mobile/node_modules/metro/src/JSTransformer/worker.js:328:521
    at new Promise (<anonymous>)
    at Object.<anonymous> (/Users/david/projects/churchtools-mobile/node_modules/metro/src/JSTransformer/worker.js:328:202)
    at Object.transformCode [as transform] (/Users/david/projects/churchtools-mobile/node_modules/metro/src/JSTransformer/worker.js:292:93)
    at execMethod (/Users/david/projects/churchtools-mobile/node_modules/jest-worker/build/child.js:90:29)
```

**Comment by ptmt** [comment]
Do you have `ignore` section in your `.babel.rc` by any chance? It doesn't work for me well (config gets unresolved, and babel transformation fails), so I removed this section for now. Probably also need to test with newer babel / metro and file an issue.

**Comment by helenaford** [comment]
Wish there was a solution for this. Ignore was working for me before I upgraded my babel from beta.47 to 7.0.0. Issue is with React-Native 0.57.0 too.

**Comment by jkimbo** [comment]
This looks like a bug in metro. I found a patch that fixes it: https://github.com/facebook/metro/issues/255#issuecomment-423819590
