### ISSUE TITLE
ld: library not found for -lReact when using Cocoapods

### ISSUE THREAD

**Issue by fatuhoku** [facebook/react-native#2025]
When I use Cocoapods to get React 0.8-rc and build a simple application, I get  `ld: library not found for -lReact`.

Podfile contents:

```
pod 'React', '~> 0.8.0-rc'
pod 'React/RCTActionSheet'
pod 'React/RCTGeolocation'
pod 'React/RCTImage'
pod 'React/RCTLinkingIOS'
pod 'React/RCTNetwork'
pod 'React/RCTSettings'
pod 'React/RCTText'
pod 'React/RCTVibration'
pod 'React/RCTWebSocket'
```

**Comment by fatuhoku** [comment]
Ooops this was just me forgetting to remove the entries under `Link Binary With Libraries` section

**Comment by haledeng** [comment]
@fatuhoku  can you describe it in detail? Because I have the same problem.

**Comment by fatuhoku** [comment]
@haledeng Go to your Project -> Your Target -> `Build Settings` -> `Link Binary With Libraries` and you might see some red entries there referring to the React library files here. Just remove those red entries and you should be good to go.

**Comment by adamski** [comment]
I have the same problem (Using React (0.18.0-rc) - I've checked the `Build Settings` and can't see any red entries there. Anything else I could check?
