### ISSUE TITLE
InputAccessoryView only rarely responds to touch

### ISSUE THREAD

**Issue by calebnelson** [facebook/react-native#20255]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
      Memory: 458.40 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.9.4 - /usr/local/bin/node
      Yarn: 1.3.2 - /usr/local/bin/yarn
      npm: 5.8.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
    IDEs:
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.3.2 => 16.3.2 
      react-native: 0.56 => 0.56.0 
    npmGlobalPackages:
      create-react-native-app: 0.0.6
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

## Description
I have a simple InputAccessoryView of TouchableOpacities to navigate a gradebook table of TextInputs [as pictured here](https://i.stack.imgur.com/1jtzT.jpg). However, this InputAccessoryView does not respond to touch very well at all. Most of the time, the keyboard closes immediately when one of the opacities is touched, sometimes it does nothing, and only very rarely is the onPress callback called.

## Reproducible Demo
Unfortunately I can't share my code as it's proprietary, but I have around 160 of these TextInputs with accessory views in a table, so perhaps the problem lies in the number of views I'm creating

**Comment by hramos** [comment]
Can you please provide a minimal reproduction? No need to share your proprietary code, as you should be able to reproduce the issue on a brand new project.

**Comment by marekpiechut** [comment]
@calebnelson Are elements inside accessory view enclosed in `FlatList` or `ScrollView`? If so try to set `keyboardShouldPersistTaps="always"` on it. I had similar issues without it.

**Comment by nicolasdanelon** [comment]
@calebnelson any news about this?
