### ISSUE TITLE
React Native Android: Unfortunately, Application has stopped

### ISSUE THREAD

**Issue by bashirpour** [facebook/react-native#20268]
My app worked properly !

When `run android` 
The application is compiled without error, but returns the message when it's displayed.

>Unfortunately, application has stopped

It happened when i install and link these two packages

 `react-native-push-notification` AND `react-native-google-analytics-bridge`

	{
	  "rnpm": {
	    "assets": [
	      "./assets/fonts/"
	    ]
	  },
	  "name": "Melkana",
	  "version": "0.0.1",
	  "private": true,
	  "scripts": {
	    "start": "node node_modules/react-native/local-cli/cli.js start",
	    "test": "jest"
	  },
	  "dependencies": {
	    "@ptomasroos/react-native-multi-slider": "0.0.14",
	    "expo": "^28.0.0",
	    "expo-analytics": "^1.0.7",
	    "lodash": "^4.17.10",
	    "react": "16.3.1",
	    "react-native": "0.55.3",
	    "react-native-check-box": "^2.1.0",
	    "react-native-elements": "^0.19.1",
	    "react-native-google-places-autocomplete": "^1.3.6",
	    "react-native-map-clustering": "^1.3.0",
	    "react-native-maps": "*",
	    "react-native-modal-picker": "0.0.16",
	    "react-native-simple-radio-button": "^2.7.2",
	    "react-native-ui-kitten": "^3.0.1",
	    "react-native-vector-icons": "^4.6.0",
	    "react-navigation": "^2.0.2",
	    "rn-sliding-up-panel": "^1.2.1"
	  },
	  "devDependencies": {
	    "babel-jest": "22.4.3",
	    "babel-preset-react-native": "4.0.0",
	    "jest": "22.4.3",
	    "react-test-renderer": "16.3.1"
	  },
	  "jest": {
	    "preset": "react-native"
	  }
	}

When run this in Android Studio look this logged errors at Logcat

> E/AndroidRuntime: FATAL EXCEPTION: Thread-1480 
> Process: com.melkana, PID: 11733 java.lang.NoSuchMethodError: No static method  loadLibrary(Ljava/lang/String;)V in class Lcom/facebook/soloader/SoLoader; or its super classes (declaration of 'com.facebook.soloader.SoLoader' appears in /data/app/com.melkana-2/base.apk)

>at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:18)

> at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:19)

> at com.facebook.react.bridge.JSCJavaScriptExecutorFactory.create (JSCJavaScriptExecutorFactory.java:21)

> at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:912)

> at java.lang.Thread.run(Thread.java:818)

**Comment by se-bastiaan** [comment]
This seems to be the same issue as #20242, #20252 and #20251. You can find more information here: https://github.com/facebook/SoLoader/issues/13
