### ISSUE TITLE
[packager] Support requiring multiple modules at once in DependencyResolver

### ISSUE THREAD

**Issue by aleclarson** [facebook/react-native#2026]
It would be nice to reduce some repetition if the React Packager's dependency resolver recognized this syntax for requiring many modules at once.

```JavaScript
var routes = require([
  './route-1',
  './route-2',
  './route-3',
]);
```

The returned `Array` would contain the exports of each module path.

This is the current workaround:

```JavaScript
var routes = [
  require('./route-1'),
  require('./route-2'),
  require('./route-3'),
];
```

[DependencyResolver/Module](https://github.com/facebook/react-native/blob/master/packager/react-packager/src/DependencyResolver/Module.js) and the `require` [polyfill](https://github.com/facebook/react-native/blob/master/packager/react-packager/src/DependencyResolver/polyfills/require.js) would be the files to change.

Thoughts?

**Comment by ide** [comment]
I believe it's unlikely this will happen unless you can make a strong case for it since this isn't standard CommonJS and React's require.js would need modifications. As a general point, you'll have a better time migrating to ES6 modules if you treat `require` as a keyword instead of a function.

**Comment by aleclarson** [comment]
Yeah I figured the same thing after I posted this. Thanks for the reply, though!
