### ISSUE TITLE
RCTUITextView.m implementing unavailable method

### ISSUE THREAD

**Issue by rahuls2704** [facebook/react-native#20271]
**Environment**

OS: macOS High Sierra 10.13.6
Xcode: Xcode 9.4.1 Build version 9F000

Packages: (wanted => installed)
react-native: 0.55.0 => 0.56.0

Steps to Reproduce
In xcode when I try to build I get the following error:
'RCTUITextView.m implementing unavailable method' and it refers to this function in objective C

- (void)setText:(NSString *)text
{
  [super setText:text];
  [self textDidChange];
}

**Comment by radko93** [comment]
Please provide a repository with code to reproduce this and I will reopen this issue.
