### ISSUE TITLE
Android Application stuck at Splashscreen

### ISSUE THREAD

**Issue by M47h13u** [facebook/react-native#20274]
## Environment
Android any version 

package.json:  

    "react": "16.0.0-alpha.6",
    "react-native": "0.43.3",
    "react-native-navigation": "1.1.398",
    "redux": "^3.7.0",
    "redux-logger": "^3.0.1",
    "redux-observable": "^0.14.1",
    "redux-persist": "^4.8.1",
    "redux-persist-transform-filter": "0.0.13",
    "react-redux": "^5.0.5",

## Description

In debug mode, when I enable "don't keep activities" and then launch my application it crashes and display this log in android studio logcat:

> E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #8
>     Process: com.situaction, PID: 20329
>     java.lang.RuntimeException: An error occurred while executing doInBackground()
>         at android.os.AsyncTask$3.done(AsyncTask.java:318)
>         at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
>         at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:242)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
>         at java.lang.Thread.run(Thread.java:761)
>      Caused by: java.lang.IllegalStateException: closed
>         at okhttp3.internal.ws.RealWebSocket.close(RealWebSocket.java:164)
>         at com.facebook.react.packagerconnection.ReconnectingWebSocket.closeWebSocketQuietly(ReconnectingWebSocket.java:110)
>         at com.facebook.react.packagerconnection.ReconnectingWebSocket.closeQuietly(ReconnectingWebSocket.java:103)
>         at com.facebook.react.packagerconnection.JSPackagerClient.close(JSPackagerClient.java:96)
>         at com.facebook.react.devsupport.DevServerHelper$2.doInBackground(DevServerHelper.java:158)
>         at com.facebook.react.devsupport.DevServerHelper$2.doInBackground(DevServerHelper.java:154)
>         at android.os.AsyncTask$2.call(AsyncTask.java:304)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
>         at java.lang.Thread.run(Thread.java:761) 

In release mode it makes the application freeze at splashscreen

## Code  

index.js:

```
import Situaction from '@situaction/App';

const app = new Situaction();
```

situaction/App.js

```
import React from 'react';

import { Provider } from 'react-redux';

import { registerScreens } from '@screens/';

import store from '@situaction/store';

import { startLogin } from '@screens/goToLogin'
import { startLoading } from '@screens/goToLoading'

import Config from 'react-native-config'

import * as session from '@session/';

// Init registers screens
registerScreens(store, Provider);

export default class Situaction {
  constructor() {
    if (__DEV__) {
      console.log(Config);
    } else {
      console.disableYellowBox = true; // -> Disable Warning in RELEASE
    }

    // LINK STORE REDUX TO APP
    const unsubscribe = store.subscribe(() => {
			if (store.getState().services.persist.isHydrated) {
				unsubscribe();
				this.autoLogin();
			}
		});
  }

  // AUTO LOGIN CHECK IF SESSION EXIST AND VALIDITY
  autoLogin() {
    session.refreshToken().then(() => {
      startLoading() // HAVE SESSION
    }).catch(() => {
      startLogin() // NO SESSION
    });
	}
}
```

**Comment by M47h13u** [comment]
$ react-native info:

> Scanning 741 folders for symlinks in E:\insitumobile3\node_modules (42ms)
> 
>   Unrecognized command 'info'
>   Run react-native --help to see list of all available commands

**Comment by radko93** [comment]
Please reproduce this with latest react native version and open another issue when this problem occurs.
