### ISSUE TITLE
Upgrade compileSdkVersion and buildToolsVersion for use `react-native-onesignal`

### ISSUE THREAD

**Issue by bashirpour** [facebook/react-native#20280]
I want use ‍‍‍`react-native-onesignal` in my project
=
How to upgrade `compileSdkVersion` and `buildToolsVersion` in my project.

My current version:

    compileSdkVersion 23
    buildToolsVersion "23.0.1"

I am going to uograde to:

    compileSdkVersion 27
    buildToolsVersion '27.0.3'

**Comment by MaximusBaton** [comment]
Version 3.2.5 of react-native-oneisgnal uses 'ext' variables got from the root build.gradle file
That means you need to add at './android/build.gradle' the following code:

```
ext {
    compileSdkVersion = 27
    buildToolsVersion = "27.0.3"
}
```

**Comment by kelset** [comment]
You should also refer to https://documentation.onesignal.com/v5.0/docs/react-native-sdk-setup
