### ISSUE TITLE
React native server doesn't start

### ISSUE THREAD

**Issue by nicomontanari98** [facebook/react-native#20286]
- [X] Review the documentation: https://facebook.github.io/react-native
  - [X] Search for existing issues: https://github.com/facebook/react-native/issues
  - [X] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
React Native Environment Info:
   

-      System:
       OS: macOS High Sierra 10.13.6
       CPU: x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
       Memory: 27.39 MB / 8.00 GB
       Shell: 3.2.57 - /bin/bash
-     Binaries:
       Node: 10.6.0 - /usr/local/bin/node
       Yarn: 1.7.0 - /usr/local/bin/yarn
       npm: 6.1.0 - /usr/local/bin/npm
       Watchman: 4.9.0 - /usr/local/bin/watchman
-     SDKs:
       iOS SDK:
         Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
       Android SDK:
         Build Tools: 23.0.1, 23.0.3, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 27.0.3
         API Levels: 23, 24, 25, 26, 27
-     IDEs:
       Android Studio: 3.1 AI-173.4819257
       Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
-     npmPackages:
       @types/react: 16.4.6 => 16.4.6 
       @types/react-native: 0.56.3 => 0.56.3 
       react: 16.4.1 => 16.4.1 
       react-native: 0.56.0 => 0.56.0 
       npmGlobalPackages:
       create-react-native-app: 1.0.0

## Description
When i run "yarn jest && react-native start" command babel gives me this error:
`Plugin 0 specified in "/Users/***/Documents/***/Sviluppo/**-native/node_modules/babel-preset-react-native/index.js" provided an invalid property of "default" (While processing preset: "/Users/***/Documents/***/Sviluppo/**-native/node_modules/babel-preset-react-native/index.js")`

## Reproducible Demo
After upgrading react-native to 0.56

**Comment by patrickkempff** [comment]
I see you are running Node: 10.6.0, Can you try running with Node LTS (8.11.x) and see if you get the same error?

**Comment by kelset** [comment]
Same error as -> https://github.com/facebook/react-native/issues/19859
