### ISSUE TITLE
flow errors after upgrade 0.56.0

### ISSUE THREAD

**Issue by yeomann** [facebook/react-native#20282]
# For Discussion

after upgrading to 0.56.0 I have many random flow errors in my vscode. is it me only or someone also experiencing it?

<img width="743" alt="screen shot 2018-07-18 at 18 18 53" src="https://user-images.githubusercontent.com/5970751/42891180-61a916f8-8ab7-11e8-9386-4773d695ff52.png">

if I navigate through some node_modules then flow start to log so many errors. it just so annoying.
but if you see the picture, It is complaining all about the React native libraries.

**Comment by TheSavior** [comment]
I think you need to update your flow config. Check out the flow config in a new react native project and  see if copying the changes to the module options resolve this problem.

**Comment by yeomann** [comment]
hey, thanks for reply @TheSavior my flow version I recently update for upgrading 0.56.0
```
Warning: `flow --version` is deprecated in favor of `flow version`
Flow, a static type checker for JavaScript, version 0.75.0
```

so clearly you can see I have done the update of flow and also added the necessary template for `.flowconfig` 

after creating newly project it doesn't show until as I said above, until I browse through `node_mdules` it starts to pick up errors from `node_modules` specially from react native package itself. so annoying those errors really. after sometimes vscode won't show and sometimes they just there like that. have you ever experienced such errors?

**Comment by yeomann** [comment]
after so many months of annoying flow error is 1 file, it turns out that, mentioning of `@flow` in comment as causing this, comment was in start of file as
```
/**
 * App file to Start everything
 * https://github.com/facebook/react-native
 * @flow
 */
```

removed it and everything is fine.

**Comment by TheSavior** [comment]
Flow only checks files that have @flow. So you are turning off flow by removing that, vs fixing the config to not have flow errors.

**Comment by yeomann** [comment]
yup you are right, but I have no clue what is wrong. @TheSavior my App.js was simple as this
<img width="372" alt="screen shot 2018-08-10 at 15 00 48" src="https://user-images.githubusercontent.com/5970751/43956799-34e563de-9cae-11e8-9a52-428950965e9b.png">
