### ISSUE TITLE
problem when releasing android

### ISSUE THREAD

**Issue by jsina** [facebook/react-native#20295]
I want to release android with command  `react-native run-android --variant=releaseStaging` but after deploying I've get this error:
`
 react-native run-android --variant=releaseStaging
ReactNativeJS: Module AppRegistry is not a registered callable module (calling runApplication)
`
here is my package.json
```
   "react": "16.3.1",
    "react-native": "0.55.2",
```
I've search a lot about the problem but I don't get any answer for it.

**Comment by patrickkempff** [comment]
@jsina  Thank you for reaching out. To investigate this further it would be really helpful to provide additional information.

To prevent this issue from being autoclosed, please make use of the [bug report template](https://github.com/facebook/react-native/issues/new?template=bug_report.md) to let us know about a **reproducible bug or regression** in the **core** React Native library.
