### ISSUE TITLE
Missing method in the Typescript declaration file.

### ISSUE THREAD

**Issue by diego-caceres** [facebook/react-native#20299]
The UIManager method

>  measureLayoutRelativeToParent

 is not present in the index.d.ts file. 

I'm not sure if this issue should be reported here, since I didn't find the file itself in this repo, but is the file that comes in node_modules with react-native:

<img width="281" alt="screen shot 2018-07-19 at 12 46 14 pm" src="https://user-images.githubusercontent.com/7662285/42966379-c7f8d070-8b51-11e8-9619-907d07211b37.png">

Thanks

**Comment by patrickkempff** [comment]
@diego-caceres  Thank you for reaching out. The TypeScript definitions are maintained at https://github.com/DefinitelyTyped/DefinitelyTyped. 

You can find the specific definitions here: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-native

It would be awesome if you can create a Pull Request to help make the React Native TypeScript definitions better!

**Comment by diego-caceres** [comment]
Yes, great, I'll head there then. 

Thank you for the guidance.
