### ISSUE TITLE
":CFBundleIdentifier"  if project directory lives in an external drive

### ISSUE THREAD

**Issue by pkhodaveissi** [facebook/react-native#20291]
Environment: 
MacOS: 10.13.6
react-native-cli: 2.0.1
react-native: 0.55.4

It took me lots of headache and hours to finally find out that if the project exists on an external drive, when building ios, it'll end up outputting different kinds of error at compile time with ":CFBundleIdentifier"  in the final message...

I'll be more than happy to provide other information if you guys need
happy coding

**Comment by kelset** [comment]
👋 I think that a PR to [`react-native-website`](https://github.com/facebook/react-native-website) with a guide on how to behave in that scenario will surely be appreciated!
