### ISSUE TITLE
State value is null on the first render, even if hard coded.

### ISSUE THREAD

**Issue by SeamusY** [facebook/react-native#20294]
## Environment
React-native 0.56 (Standard react-native default build)

## Description
I had this weird attempt that if i set the initial state to be a string, i alerted it but it's entirely null. Is it a bug? or is it just me?

![screenshot 31](https://user-images.githubusercontent.com/26731487/42957127-54c8b274-8bb4-11e8-906a-61ac6ce70439.png)

## Reproducible Demo
On the Snack it doesn't even show me the alert, which is kinda silly.
I even tried making a constructor and a super, still the same result.
```
`export default class App extends Component {
  state={
    text:"Hi"
  }
  checker = () =>{
    alert("The state is " +this.state.text);
  }
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>Welcome to React Native!</Text>
        <Text style={styles.instructions}>To get started, edit App.js</Text>
        <Text style={styles.instructions}>{instructions}</Text>

        <TextInput
        placeholder={"something Here"}
        onChangeText={(text)=>{this.setState({text})}}
        value={this.state.text}
        />
        <Button
        title={"Check state"}
        onPress={this.checker}
        />
      </View>
    );
  }
}`

```
https://repl.it/repls/MeekLumpyMedian

Not sure if that would work, but i hope it does.  If it doesn't the steps are the follow:
-react-native init App
-copy and paste my code in
-react-native run-android.

**Comment by patrickkempff** [comment]
@SeamusY Thank you for reaching out. I copied your reproduction code to the following snack which seems to work: https://snack.expo.io/SywEdHC7X, can you take a look and verify this approach works?

**Comment by SeamusY** [comment]
The snack is ok! the odd thing is i repeated this process in 3 different laptops react-native init and then just did what i did there, and it would break the phone and the emulator.

**Comment by patrickkempff** [comment]
If I you your example I can reproduce it. But in my snack I cannot, the difference is that I typed in manually to make sure no hidden characters got copied. Can you try to implement my example, and see if that works?

**Comment by SeamusY** [comment]
Oddly, with yours it worked fine. So why? is it just spacing that caused it?

**Comment by patrickkempff** [comment]
@SeamusY I am not sure.

**Comment by SeamusY** [comment]
@patrickkempff ill just close this, since there seems to be no answer. Unless you want to keep it open.
