### ISSUE TITLE
npm/yarn start: UnhandledPromiseRejectionWarning or stuck in Starting packager...

### ISSUE THREAD

**Issue by gustavovaliati** [facebook/react-native#20305]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Environment:
  OS: Linux 4.15 (additional info: Ubuntu 16.04)
  Node: 8.11.3
  Yarn: 1.7.0
  npm: 6.2.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: ~0.55.2 => 0.55.4

## Description

**Main behavior:**
The `npm start ` does not complete, getting stuck in "Starting packager..." after the user rebooting the machine for the first time. In other words, after creating a project using CRNA, I can work on it while I do not reboot the system. After rebooting the system, the project cannot be normally started anymore. This is the output:
```
~/workspace/react-native/my-project: yarn start         
yarn run v1.7.0
$ react-native-scripts start
19:44:25: Starting packager...

```

**Workaround:**
If I use `sudo rpm/yarn start` the project starts up normally.

**Other behaviors:**
Sometimes, instead of only getting stuck it additionally outputs this error:

```
~/workspace/react-native/my-project: yarn start                     
yarn run v1.7.0
$ react-native-scripts start
19:23:09: Starting packager...
***ERROR STARTING PACKAGER***
Starting React Native packager...
Scanning folders for symlinks in (...)workspace/react-native/my-project/node_modules (21ms)
Loading dependency graph.

(node:9647) UnhandledPromiseRejectionWarning: Error: watch (...)workspace/react-native/tagger ENOSPC
    at _errnoException (util.js:992:11)
    at FSWatcher.start (fs.js:1382:19)
    at Object.fs.watch (fs.js:1408:11)
    at NodeWatcher.watchdir (/home/gustavo/workspace/react-native/tagger/node_modules/sane/src/node_watcher.js:175:20)
    at new NodeWatcher (/home/gustavo/workspace/react-native/tagger/node_modules/sane/src/node_watcher.js:45:8)
    at createWatcher (/home/gustavo/workspace/react-native/tagger/node_modules/metro/node_modules/jest-haste-map/build/index.js:572:23)
    at Array.map (<anonymous>)
    at HasteMap._watch (/home/gustavo/workspace/react-native/tagger/node_modules/metro/node_modules/jest-haste-map/build/index.js:683:44)
    at _buildPromise._buildFileMap.then.then.hasteMap (/home/gustavo/workspace/react-native/tagger/node_modules/metro/node_modules/jest-haste-map/build/index.js:280:21)
    at <anonymous>
***ERROR STARTING PACKAGER***

(node:9647) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

> For sanitization, in this post the root path in the log has been replaced by "(...)".

If I remove the node_modules files and run npm/yarn install again, the error message does not show up anymore. Just the "Starting Packager..." message is kept stuck there.

Problem research:
I have looked up in the community for this problem and seems to occur a lot. Though, the majority of the reported problems are related to MacOS users (while I am a linux user), which are able to solve the issue just by installing the watchman.

I have set the flags as they are requirements, as well inserted in the file `/etc/sysctl.conf`:
```
sudo sysctl -w fs.inotify.max_user_instances=1024
sudo sysctl -w fs.inotify.max_user_watches=12288
```

> I ensure to execute those commands before every test I do, just to guarantee. 

I have checked permissions, tryied different package versions and a lot of different ideias I have found in the Internet. None of them seems to work.

## Reproducible Demo
The problem happens in my environment every time I do this:

1. Create a brand new project with the following command as referenced in [Getting Started](https://facebook.github.io/react-native/docs/getting-started.html): `create-react-native-app my-project`
2. Run `npm start` or `yarn start` and everything works just fine!
3. Reboot the machine
4. Run `npm start` or `yarn start` back in the project's folder, and it get stuck in the referenced problem with message "Starting Packager..."

> If I run the npm start with sudo, it works properly.

**Comment by gustavovaliati** [comment]
Forgot to mention that I have tested with the latest version (v0.56.0) of react-native and the problem remains.

In the last minute, while opening a [question](https://stackoverflow.com/a/47518500/7353853) in the StackOverflow, I have found an answer for the problem that I could not find in my searches. I am checking it right now.

**Comment by gustavovaliati** [comment]
Seems like compiling and installing the github.com/facebook/watchman on my Ubuntu 16.04 did solve the problem.

Am I wrong, or there are no explicit requirements for Linux to install watchman?

**Comment by hramos** [comment]
Watchman is listed as being [optional, but highly recommended,](http://facebook.github.io/react-native/docs/getting-started.html#watchman-optional) for this, among other reasons.

Perhaps it's time to update the docs to make this an explicit requirement?

**Comment by gustavovaliati** [comment]
Hi @hramos , thanks for your response.

Yah, in my point of view the docs should be updated to include the watchman requirement. 

I have never clicked the button "Building Projects with Native Code" on the page because that was not what I wanted to do. I was just trying to prepare a HelloWorld (quick start).

Also, the webpage let be implicit that the watchman is not part of the Quick Start:
> Follow these instructions if you need to build native code in your project. For example, if you are integrating React Native into an existing application, or if you "ejected" from Create React Native App, you'll need this section.

I suppose there are many other people having this kind of trouble by the incorrect guide.

Kindly appreciate your help. Thanks.

**Comment by hramos** [comment]
Good point on this not being mentioned as part of the CRNA flow. You can try filing an issue against the crna repo at https://github.com/react-community/create-react-native-app to make sure they're aware of this.
