### ISSUE TITLE
onScroll event not firing for multiline TextInput

### ISSUE THREAD

**Issue by dereksweet** [facebook/react-native#20309]
## Environment
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 6.9.0
  Yarn: 1.6.0
  npm: 3.10.8
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 2.3 AI-162.3934792

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: ~0.55.2 => 0.55.4

## Description
I noticed recently that multiline <TextInput> controls stopped firing the onScroll event when the user slides their thumb/finger to scroll the contents of the input. See the app linked in Reproducible Demo, it is as simple as can be. The console shows the output 'focusing' onFocus, but it does not display anything for onScroll. 

## Reproducible Demo
https://github.com/dereksweet/MultilineScrollTest

**Comment by zubko** [comment]
This issue is still happening on RN 0.57.8

Quick fix:

In `node_modules/react-native/Libraries/Text/TextInput/RCTBackedTextInputDelegateAdapter.m`

Add 

```objective-c
#pragma mark - UIScrollViewDelegate

- (void)scrollViewDidScroll:(UIScrollView *)scrollView
{
  id<RCTBackedTextInputDelegate> delegate = _backedTextInputView.textInputDelegate;
  if ([delegate respondsToSelector:@selector(scrollViewDidScroll:)]) {
    [delegate performSelector:@selector(scrollViewDidScroll:) withObject:scrollView];
  }
}

```

**Comment by antonellil** [comment]
@zubko that fix works great. this seems worthy of a PR into RN to fix this?
