### ISSUE TITLE
React Native app crashing due to assertion error

### ISSUE THREAD

**Issue by tclarke-scottlogic** [facebook/react-native#20318]
Started experiencing this crash today, have not encountered it before:

Build and run project in Xcode

Works for a while, then suddenly exits the app:

In system log, I see this:

> Jul 20 17:37:34 Thomass-MacBook-Pro Acuris[21009]: assertion failed: 17G65 15F79: libxpc.dylib + 71445 [C070AA3B-6F2B-3D85-887C-5A00FAE39163]: 0x7d
> Jul 20 17:37:35 Thomass-MacBook-Pro Acuris[21009]: DEPRECATED USE in libdispatch client: Setting timer interval to 0 requests a 1ns timer, did you mean FOREVER (a one-shot timer)?

--------

dev/mobile-notifications-native >react-native info
Scanning folders for symlinks in /Users/thomasclarke/dev/mobile-notifications-native/node_modules (15ms)

Environment:
  OS: macOS High Sierra 10.13.6
  Node: 10.7.0
  Yarn: 1.7.0
  npm: 6.2.0
  Watchman: Not Found
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.2 => 16.3.2
  react-native: 0.55.4 => 0.55.4

**Comment by radko93** [comment]
Please provide repro (steps or code) on how to reproduce this. For me, it seems that it's unrelated to react native.

**Comment by mikehuebner** [comment]
I just started getting this on a release build. Not sure if this is related but same error and all. Here are some more logs...
```
Jul 20 16:15:40 COMPUTER_NAME APP_NAME[19094]: assertion failed: 17G65 15F79: libxpc.dylib + 71445 [C070AA3B-6F2B-3D85-887C-5A00FAE39163]: 0x7d
Jul 20 16:15:43 COMPUTER_NAME com.apple.CoreSimulator.SimDevice.7D3870F0-2782-4EF7-9E6C-E1068F3DE8EB[89769] (com.apple.securityuploadd): Service only ran for 6 seconds. Pushing respawn out by 4 seconds.
Jul 20 16:15:47 COMPUTER_NAME com.apple.CoreSimulator.SimDevice.7D3870F0-2782-4EF7-9E6C-E1068F3DE8EB[89769] (com.apple.videosubscriptionsd[19106]): Service exited with abnormal code: 1
Jul 20 16:15:47 COMPUTER_NAME com.apple.CoreSimulator.SimDevice.7D3870F0-2782-4EF7-9E6C-E1068F3DE8EB[89769] (com.apple.videosubscriptionsd): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Jul 20 16:15:53 COMPUTER_NAME com.apple.CoreSimulator.SimDevice.7D3870F0-2782-4EF7-9E6C-E1068F3DE8EB[89769] (com.apple.securityuploadd): Service only ran for 5 seconds. Pushing respawn out by 5 seconds.
```

**Comment by joshspicer** [comment]
Was a solution ever found? Happens to me only on release when upgraded to RN 0.56.0

**Comment by kulack** [comment]
Happening to us as well, only on iPhone X inside Expo or in the native built app.
Not finding much help here.
I know this is closed, but I have an App Store app that experiences it on iPhone X if that's any help.

**Comment by macnibblet** [comment]
I just rant into very much the same problem, but we are not using firebase

**Comment by PurnimaNaik** [comment]
@macnibblet did you find a solution? I have the same issue

**Comment by rimiti** [comment]
Is anyone has information about this issue ?

**Comment by treynolds110** [comment]
I've also just encountered this issue. Any updated information?

**Comment by tclarke-scottlogic** [comment]
@treynolds110 
This fixed it for me, can't speak to anyone else.
 https://github.com/facebook/react-native/issues/20318#issuecomment-415349996
