### ISSUE TITLE
[FlatList] Some questions about onEndReached

### ISSUE THREAD

**Issue by sunhailongisme** [facebook/react-native#20313]
###  Environment  ### 
React Native Environment Info:
System:
  OS: macOS High Sierra 10.13.6
  CPU: x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  Memory: 2.21 GB / 16.00 GB
  Shell: 3.2.57 - /bin/bash
Binaries:
  Node: 8.11.1 - ~/.nvm/versions/node/v8.11.3/bin/node
  npm: 5.6.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
  Watchman: 4.9.0 - /usr/local/bin/watchman
SDKs:
  iOS SDK:
    Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
  Android SDK:
    Build Tools: 23.0.1, 26.0.1, 26.0.3, 28.0.1
    API Levels: 23, 26, 28
IDEs:
  Android Studio: 3.1 AI-173.4819257
  Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
npmPackages:
  react: 16.4.1 => 16.0.0 
  react-native: 0.48.0 => 0.48.1
npmGlobalPackages:
  create-react-native-app: 1.0.0
  react-native-cli: 2.0.1

### Description ### 

             <FlatList
                            keyboardShouldPersistTaps={'handled'}
                            data={this.state.listData}
                            initialNumToRender={this.initialNumToRender}
                            keyExtractor={this._keyExtractor}
                            renderItem={this.getView}//渲染每一条记录
                             ListEmptyComponent={this.emptyComponent}
                            ListFooterComponent={this.footer}//尾部
                            //下拉刷新，必须设置refreshing状态
                            onRefresh={this.onRefresh}
                            refreshing={this.state.refreshing}
                            //上拉加载
                            onEndReachedThreshold={0.1}
                            onEndReached={this.onEndReached}
                        >
             </FlatList>

    onEndReached  =() => {
        currentPage++;
        if (this.state.showFoot === 0){
          this.setState({refreshing:false});
        }
        params.reqParams.page = currentPage;
        if (this.state.data.totalpage&&this.state.data.totalpage !== undefined){
          if(currentPage == this.state.data.totalpage){
            this.setState({showFoot:1});//底部显示没有更多数据
          }else if(currentPage>this.state.data.totalpage){
            return
          }
        }
        Fetch.fetchData('jsonpost',{},(res) => {
          if (res.success!==undefined&&res.success === false){
            this.setState({msg:'连接超时,请重试！'});
            this.alertSearch._show();
          }
          if (res.respCode === 'success'){
            this.setState({
              listData:this.state.listData.concat(res.data.ENTERPRISES),
              showFoot:0,
              refreshing:false,
              totalnum:res.totalnum,
            });
          }else if(res.respCode === 'failed'){
            this.setState({msg:res.Errmsg,refreshing:false});
            this.alertSearch._show();
          }
        })
    };

onEndReached triggered 2 times on ios ，but，it is normal on android .If I change a way of writing:

    onEndReached  =() => {
        currentPage++;
        if (this.state.showFoot === 0){
          this.setState({refreshing:false});
        }
        params.reqParams.page = currentPage;
        if (this.state.data.totalpage&&this.state.data.totalpage !== undefined){
          if(currentPage == this.state.data.totalpage){
            this.setState({showFoot:1});//底部显示没有更多数据
          }else if(currentPage>this.state.data.totalpage){
            return
          }
        }
        Fetch.fetchData('jsonpost',{},(res) => {
          if (res.success!==undefined&&res.success === false){
            this.setState({msg:'连接超时,请重试！'});
            this.alertSearch._show();
          }
          if (res.respCode === 'success'){
           const getNewData = (res) =>{
             let oldData = this.state.listData;
             for (let i = 0;i<res.data.ENTERPRISES.length;i++){
              oldData.push(res.data.ENTERPRISES[i]);
             }
              return oldData 
            }
            const newData = getNewData(res);
            this.setState({
              listData:newData,
              showFoot:0,
              refreshing:false,
              totalnum:res.totalnum,
            });
          }else if(res.respCode === 'failed'){
            this.setState({msg:res.Errmsg,refreshing:false});
            this.alertSearch._show();
          }
        })
    };

   The method of "onEndReached" on IOS will not be executed two times.But there will be another problem，
When I first scrolled to the bottom of the list to trigger the "onEndReached" method, if the network request failed and 

no new list data was rendered, I scrolled again to the bottom of the list and the "onEndReached" method could not be 

triggered again

The problems of the above two ways of writing：

   1、When I am not on the first page list, if I afresh render the list, It will still automatically execute a 

"onEndReached" method, but I do not scroll to trigger the "onEndReached" method 。
   2、When the first render list is less than one screen, the "onEndReached" method will still execute automatically.
I really don't know why these problems will arise. If anyone knows the reasons, please explain them.

### Reproducible Demo ###

    onEndReached  =() => {
        currentPage++;
        if (this.state.showFoot === 0){
          this.setState({refreshing:false});
        }
        params.reqParams.page = currentPage;
        if (this.state.data.totalpage&&this.state.data.totalpage !== undefined){
          if(currentPage == this.state.data.totalpage){
            this.setState({showFoot:1});//底部显示没有更多数据
          }else if(currentPage>this.state.data.totalpage){
            return
          }
        }
        Fetch.fetchData('jsonpost',{},(res) => {
          if (res.success!==undefined&&res.success === false){
            this.setState({msg:'连接超时,请重试！'});
            this.alertSearch._show();
          }
          if (res.respCode === 'success'){
           const getNewData = (res) =>{
             let oldData = this.state.listData;
             for (let i = 0;i<res.data.ENTERPRISES.length;i++){
              oldData.push(res.data.ENTERPRISES[i]);
             }
              return oldData 
            }
            const newData = getNewData(res);
            this.setState({
              listData:newData,
              showFoot:0,
              refreshing:false,
              totalnum:res.totalnum,
            });
          }else if(res.respCode === 'failed'){
            this.setState({msg:res.Errmsg,refreshing:false});
            this.alertSearch._show();
          }
        })
    };

**Comment by jiangsumadai** [comment]
Thanks for your patience, but when I upgrade react-native to 0.57.4, the issue exits as before.
I implemented onEndReached and fetched some data in componentDidMount, the server returned 20 items which could not displayed in one screen, and then onEndReached was invoked automatically.
