### ISSUE TITLE
Android Permission never granted, nor asked.

### ISSUE THREAD

**Issue by SeamusY** [facebook/react-native#20311]
## Environment
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7 CPU         870  @ 2.93GHz
      Memory: 306.79 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.6.0 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 23.0.3, 24.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.0
        API Levels: 21, 22, 23, 24, 25, 26, 27
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: ^0.56.0 => 0.56.0 

## Description
Android Permission doesn't prompt anything, instead it's alert. The documentation of IF and Else never gets there and the catch itself never gets there.

## Reproducible Demo

![screen shot 2018-07-20 at 2 28 07 pm](https://user-images.githubusercontent.com/26731487/42986755-6975edac-8c29-11e8-88d9-eb7ec5d2845d.png)

Copy and paste the function, and set it up with react-native-barcode-scanner-google.

**Comment by hramos** [comment]
This issue needs repro steps and/or sample code.

**Comment by SeamusY** [comment]
Never mind, i close it because the permission is asked prior before arriving at the camera or it resorts to this pop up of No Camera Permission and it's denied.
