### ISSUE TITLE
AsyncStorage awaits indefinitely

### ISSUE THREAD

**Issue by Kireeti-K** [facebook/react-native#20310]
## Environment
    React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
      Memory: 2.21 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
      npm: 6.2.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 26.0.1, 26.0.3, 28.0.1
        API Levels: 23, 26, 28
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1

## Description
Hello Im building an authentication system for my app now. and I am trying to hit my api, authenticate details and fetch a token. Code I used can be seen below

    saveUserDataAndNavigate = (fulfilled) => {
         const userData = fulfilled.data;
          alert("saving user data");  // this runs
          _storeData = async () => {
              try {
                   await AsyncStorage.setItem("userData ", JSON.stringify(userData));  // stucks here
                   closePopupAndGoToHome(userData);   // never gets here
                } catch (error) {
                    alert("Something went wrong, please try again");   // nor throws error
                    this.scaleAnimationDialog.dismiss();
                }
            }
    }

    closePopupAndGoToHome = (userData) => {
        alert("UserData saved ", userData);
        this.scaleAnimationDialog.dismiss();
        setTimeout(() => this.props.navigation.navigate("Home", userData), 500);
    }

    axios.post("mywebsite.in/parent/api/token-auth", {
        username: this.state.username,
        password: this.state.password
    })
    .then(
        saveUserDataAndNavigate,
        (error) => {
            this.scaleAnimationDialog.dismiss();
            alert("Authentication failed, please try again");
        }
    )

In my tests, when I provide invalid username and password, I get an alert with Authentication failed, which is completely expected and also when the details are valid, It calls saveUserDataAndNavigate function, It somehow is getting stuck awaiting for AsyncStorage to setItem. 

## Reproducible Demo
     _storeData = async () => {
         try {
             await AsyncStorage.setItem("userData ", JSON.stringify(userData));
             closePopupAndGoToHome(userData);  // this line never executes
         } catch (error) {
              alert("Something went wrong, please try again"); // nor this.
              this.scaleAnimationDialog.dismiss();
         }
    }

**Comment by hieunc229** [comment]
I guess that the variable `_storeData` in the code was just a function declaration, which means it has never get called. You can either call the function or run with async style. For example:
```javascript
(async () => {
   try {...} 
   ...
})()
```
Note that the brackets at the end `()` is calling the function.

**Comment by radko93** [comment]
I think the question was answered, I will close this one. Please ask if you have further questions.

**Comment by Kireeti-K** [comment]
Hey @hieunc229 I tried calling the _storeData function, thanks for the correction. Now my functions is getting executed. But the values are not getting saved. I am trying getItem and also getAllKeys right after setItem, but they just returning nothing and I am not able to persist any data. My issue may be related to this? https://github.com/facebook/react-native/issues/18372

**Comment by ravi-ojha** [comment]
@Kireeti-K I faced similar issue today with `setItem` using `AsyncStorage` with `await`. It would just wait indefinitely. Tried the alternative `SecureStore` from Expo and worked at the first try.
