### ISSUE TITLE
RN 0.56.0 Production build crash

### ISSUE THREAD

**Issue by keshk26** [facebook/react-native#20321]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
 React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.5
      CPU: x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 6.11 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.3 - /usr/local/bin/node
      Yarn: 1.5.1 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 23.0.2, 23.0.3, 24.0.2, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 27.0.1
        API Levels: 23, 24, 25, 26
    IDEs:
      Android Studio: 2.2 AI-145.3537739
      Xcode: 9.4/9F1027a - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 

## Description
I have upgraded to RN 0.56.0 successfully. My app builds and runs in my development environment but it crashes in my production environment. Below is my stack trace. It seems to be an issue with the react package (com.facebook.react) but I am unsure how to troubleshoot this and haven't seen this issue asked before. 

```
2018-07-20 16:45:47.219 [error][tid:com.facebook.react.JavaScript] undefined is not an object (evaluating 'Sn')
2018-07-20 16:45:47.221 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: undefined is not an object (evaluating 'Sn')
2018-07-20 09:45:47.232 ServiceNative[92286:609162] *** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: undefined is not an object (evaluating 'Sn')', reason: 'Unhandled JS Exception: undefined is not an object (evaluating 'Sn'), stack:
extractEvents@112:27183
extractEvents@112:23682
handleTopLevel@112:27390
<unknown>@112:28875
perform@113:3484
K@112:6111
_receiveRootNodeIDEvent@112:28846
receiveEvent@112:28958
value@18:2853
<unknown>@18:280
value@18:2304
callFunctionReturnFlushedQueue@18:252
'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010af6334b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000109e7121e objc_exception_throw + 48
	2   ServiceNative                       0x00000001081c69c5 RCTFormatError + 0
	3   ServiceNative                       0x00000001081c34a0 -[RCTExceptionsManager reportFatalException:stack:exceptionId:] + 507
	4   CoreFoundation                      0x000000010aeea05c __invoking___ + 140
	5   CoreFoundation                      0x000000010aee9ee1 -[NSInvocation invoke] + 289
	6   CoreFoundation                      0x000000010af01ed6 -[NSInvocation invokeWithTarget:] + 54
	7   ServiceNative                       0x00000001081da229 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 602
	8   ServiceNative                       0x0000000108220b22 _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicE + 266
	9   ServiceNative                       0x000000010822089c ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 78
	10  libdispatch.dylib                   0x000000010eaff980 _dispatch_call_block_and_release + 12
	11  libdispatch.dylib                   0x000000010eb290cd _dispatch_client_callout + 8
	12  libdispatch.dylib                   0x000000010eb06e6b _dispatch_queue_serial_drain + 236
	13  libdispatch.dylib                   0x000000010eb07b9f _dispatch_queue_invoke + 1073
	14  libdispatch.dylib                   0x000000010eb0807f _dispatch_queue_override_invoke + 683
	15  libdispatch.dylib                   0x000000010eb0a3b7 _dispatch_root_queue_drain + 720
	16  libdispatch.dylib                   0x000000010eb0a08b _dispatch_worker_thread3 + 123
	17  libsystem_pthread.dylib             0x000000010eedd169 _pthread_wqthread + 1387
	18  libsystem_pthread.dylib             0x000000010eedcbe9 start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

## Reproducible Demo
Run on simulator/device pointing to your production environment.

**Comment by keshk26** [comment]
@react-native-bot  I ran `react native info` and updated the Environment Section.

**Comment by nicholasrq** [comment]
possible duplicate of #19827

**Comment by keshk26** [comment]
This was issue with [react-native-code-push](https://github.com/Microsoft/react-native-code-push). I needed a new codepush version for production. You can see my issue posted here: https://github.com/Microsoft/react-native-code-push/issues/1359
