### ISSUE TITLE
ScrollView broken in 0.56.0 for a brownfield edge case in iOS

### ISSUE THREAD

**Issue by karanjthakkar** [facebook/react-native#20324]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.5
      CPU: x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 2.86 GB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
      Yarn: 1.7.0 - ~/.nvm/versions/node/v8.11.3/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 9.4/9F1027a - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1
      react-native: 0.56.0 => 0.56.0
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

## Description

[This commit](https://github.com/facebook/react-native/commit/f96d7ae6486eb245496c0fef07239ae0480e88b6) broke `ScrollView` in certain cases. Details for it are copied from [this comment](https://github.com/facebook/react-native/commit/f96d7ae6486eb245496c0fef07239ae0480e88b6#r29777891).

---
In our brownfield project, we had a UIView category (UIView+Something.h) which implemented the protocol UITextViewDelegate which in turn extends UIScrollViewDelegate. Due to this, after upgrading to RN 0.56, our scroll views stopped working coz these lines are missing in the new else if block:

```
_contentView = view;
RCTApplyTransformationAccordingLayoutDirection(_contentView, self.reactLayoutDirection);
```

It took us a long time to investigate the issue, so I was wondering if you knew whether this usecase was missed out when this block was added? Is there is a better way to handle this? I know most greenfield apps won't run into this but you never know what legacy code brownfield apps have and making this better might avoid the pain we had to go through after the upgrade.

---

## Reproducible Demo
Its hard to extract an example to share this but the description is self sufficient to identify the issue.

cc'ing @PeteTheHeat as he was planning on looking into this issue and coming up with an appropriate fix.

**Comment by PeteTheHeat** [comment]
@karanjthakkar ^ should fix the issue

**Comment by karanjthakkar** [comment]
Thanks! 💯
