### ISSUE TITLE
Upgrade to soloader 0.5.1

### ISSUE THREAD

**Issue by hramos** [facebook/react-native#20323]
## Environment

[skip envinfo]

## Description

[SoLoader](https://github.com/facebook/SoLoader/issues/13) had an ABI-breaking change in 0.5.0.

Because React Native links against SoLoader, this can cause really frustrating experiences for our users because as soon as you mix two or more dependencies built against pre- 0.5 and post-0.5 releases, you end up with errors like

```
java.lang.NoSuchMethodError: No static method loadLibrary(Ljava/lang/String;)V in class Lcom/facebook/soloader/SoLoader; or its super classes (declaration of 'com.facebook.soloader.SoLoader' appears in /data/app/com.someapp.android.someapp-1/base.apk:classes2.dex)
```

React Native is using SoLoader [0.3.0](https://github.com/facebook/react-native/blob/75a0273de21948b0b959263100f09111f738ec35/ReactAndroid/build.gradle#L302) at the moment.

## Reproducible Demo

See https://github.com/facebook/react-native/issues/20242 where a handful of people in the [comments](https://github.com/facebook/react-native/issues/20242#issuecomment-405534869) ran into the same issue.

## Solution

Update React Native's SoLoader dependency to 0.5.0 or newer.

**Comment by hramos** [comment]
cc @dulmandakh @gengjiawen this might be as simple as updating the one file

**Comment by passy** [comment]
Buck dependency, too, I would imagine.
