### ISSUE TITLE
RN app setTimeout() is very  slow when debugging with chrome and windows7

### ISSUE THREAD

**Issue by JQiMeng** [facebook/react-native#20328]
thanks for help.
I meet the problem when I use setTimeout in RN app. RN app setTimeout is very  slow when debugging with chrome and windows 7. And it will be fine shutdown the debug mode. 
it looks like this:
```
    let initTime = new Date().getTime();
    console.log(new Date().getTime() - initTime,data);
    if(data){
      let { navigation } = this.props;
      this.timer = setTimeout(function () {
        console.log(`inner ${new Date().getTime() - initTime}`,data);
        let updateState =  navigation.getParam('updateState')
        if(typeof updateState === 'function'){
          updateState(data)
          navigation.goBack()
        }else{
          navigation.navigate('SendDetail', {address: data});
        }
      }, 700);
    }
```
```
0 {data: "fjdkfjdknakfnd", type: "QR_CODE", bounds: Array(3)}
inner 100348 {data: "fjdkfjdknakfnd", type: "QR_CODE", bounds: Array(3)}
```
even though the computer tell me it only **100348ms**.  Actually the real time is **1min40s.**
I think this may happen only in the windows machine. the mac machine probably will not have this problem

**Comment by dkoo761** [comment]
I'm also experiencing that a very minimal setTimeout is taking almost 1,000ms per call on Android with Remote JS Debugging enabled vs only around 5ms with it disabled. This is in RN 0.57.8.

**Comment by jpodpro** [comment]
also experiencing ~1000ms from setTimeout even what i have it set to very short (1ms).

Remote JS Debugging enabled, RN 0.59.8, Chrome 74, MacOS High Sierra 10.13.6
