### ISSUE TITLE
Development menu broken?

### ISSUE THREAD

**Issue by lelandrichardson** [facebook/react-native#2034]
I'm not sure what I'm doing wrong, but this seems to be happening to me in 0.8.0

The developer menu opens and animates in *really* slowly, and cannot be clicked/tapped on (ie, does nothing) and then can also not be closed.

Perhaps relatedly, the splash screen fades out much slower than it used to.

My entire app is nothing but a single View + Text:

```jsx
var react_native_animation_examples = React.createClass({
    render: function () {
        return (
            <View style={styles.container}>
                <Text>Hello</Text>
            </View>
        );
    }
});
```

![](http://i.giphy.com/l41m4kXaifFDWdlaE.gif)

This can't be happening to everybody, but I can't figure out what I'm doing wrong/different. Any help appreciated.

**Comment by ide** [comment]
You probably have slow animations enabled in the simulator.

**Comment by lelandrichardson** [comment]
lmao. that was it. I never even knew that existed...  thanks for your quick response!
