### ISSUE TITLE
stuck at Loading Dependency Graph then Bundling `index.js` [development, non-minified] ░░░░░░░░░░░░░░░░ 0.0% (0/1)

### ISSUE THREAD

**Issue by Deepjyoti120** [facebook/react-native#20346]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
React Native Environment Info:
    System:
      OS: Windows 10
      CPU: x64 Intel(R) Pentium(R) CPU 3825U @ 1.90GHz
      Memory: 2.17 GB / 7.92 GB
    Binaries:
      npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.1.0.0 AI-173.4720617

## Description
Describe your issue in detail. Include screenshots if needed. If this is a regression, let us know.

## Reproducible Demo
Let us know how to reproduce the issue. Include a code sample, share a project, or     share an app that reproduces the issue using https://snack.expo.io/. Please follow the guidelines for providing a MCVE: https://stackoverflow.com/help/mcve

1. 
![screenshot 1](https://user-images.githubusercontent.com/31041000/43077034-df59c242-8ea3-11e8-9d06-d925101c8f45.png)

**Comment by tobiastornros** [comment]
Happens all the time. Quit your simulator and exit your session in the terminal and try again.

**Comment by Deepjyoti120** [comment]
i try but same Issue not solved

**Comment by Deepjyoti120** [comment]
thanks for reply me sir , i try this methods but not working please help
i am bigenners in this feild

**Comment by tttunci** [comment]
It is a current issue in the latest version of react native, to avoid it best you can do is to run the react native on the previous version 0.55.4.

Follow steps: 
npm uninstall react-native@0.56
npm install react-native@0.55.4

go to your file get in to package.json delete babel-preset-react-native 5.x.x
then from the console
npm install babel-preset-react-native@4.0.0

**Comment by gengjiawen** [comment]
Are you using 0.56. If that's the case, please downgrade, it's an known issue. And @kelset and I are working on this, hopefully we can release 0.57 in two days.

**Comment by Deepjyoti120** [comment]
thank your all off you sir, Downgraded solved my problem , and pease make 0.57 version and fixed this issue 
again thanks to tttunci sir and gengjiawen for solving my problem .
