### ISSUE TITLE
Problem when compile apk (Android)

### ISSUE THREAD

**Issue by nicomontanari98** [facebook/react-native#20344]
- [X] Review the documentation: https://facebook.github.io/react-native
  - [X] Search for existing issues: https://github.com/facebook/react-native/issues
  - [X] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
React Native Environment Info:
- System:
       OS: macOS High Sierra 10.13.6
       CPU: x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
       Memory: 29.13 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash

- Binaries:
      Node: 10.6.0 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.1.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman

- SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3

- IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild

- npmPackages:
      @types/react: 16.4.6 => 16.4.6 
      @types/react-native: 0.56.4 => 0.56.4 
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 

- npmGlobalPackages:
      create-react-native-app: 1.0.0

## Description
When i try to compile APK gradle gives me this issue:
Task :ReactAndroid:buildReactNdkLib UP-TO-DATE

## Reproducible Demo
Upgrade react-native to 0.56 and compile apk

**Comment by radko93** [comment]
It's not the real error message, can you can again?
Might be related to https://github.com/facebook/react-native/issues/18658.
