### ISSUE TITLE
textInput value proper is invalid

### ISSUE THREAD

**Issue by 2248157705** [facebook/react-native#20341]
React Native Environment Info:
System:
OS:  IOS  
"react": "16.3.1",
"react-native": "0.55.3",

   <TextInput 
                         value={this.state.showValue}
                       onChangeText={(text)=>{
                          this.customValue(text)
                       }} />
  customValid(text)
    {
        this.setState({
            showValue:'text'
        })

    }

i want to custom valid  the textinput value in every time user input , but the value proper can not  work

**Comment by iamdurui** [comment]
I hava this problem ,
React Native Environment Info:
System:
OS: IOS
"react": "16.4.1",
"react-native": "0.56.0",  but android is ok!! @react-native-bot  thanks
