### ISSUE TITLE
0.56.0 crashes at startup (in YellowBoxList.js)

### ISSUE THREAD

**Issue by swapkids** [facebook/react-native#20355]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.4
      CPU: x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
      Memory: 695.62 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.6.0 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.1.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
    IDEs:
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.4.1 => 16.4.1 
      react-native: ^0.56.0 => 0.56.0 
    npmGlobalPackages:
      react-native: 0.56.0

## Description
After upgrading from version 0.44 -> 0.56 I keep getting this at the first render loop.

This error is located at:
    in FlatList (at YellowBoxList.js:87)
    in RCTView (at View.js:43)
    in YellowBoxList (at YellowBox.js:104)
    in YellowBox (at AppContainer.js:93)
    in RCTView (at View.js:43)
    in AppContainer (at renderApplication.js:31)

_checkProps
    FlatList.js:489:6
FlatList
    FlatList.js:433:21
<unknown>
    createClassProxy.js:98:23
instantiate
    createClassProxy.js:96:6
constructClassInstance
    ReactNativeRenderer-dev.js:7577:26
updateClassComponent
    ReactNativeRenderer-dev.js:9868:8
performUnitOfWork

**Comment by radko93** [comment]
We need to have your code to reproduce this issue.

**Comment by svenlombaert** [comment]
I'm having the same problem, but I do have some more info. I can run my app without a problem until I run packager with whackage (https://github.com/FormidableLabs/whackage). After that, I do get this error as well. Then it doesn't matter what I try to do, I can clear every cache, I keep getting this error, also when I just run `react-native start`.

@swapkids Do you, by any chance, use(d) whackage as well? If so, I think it might be related.

**Comment by svenlombaert** [comment]
Okay, did some more digging around (started upgrading to 0.56 yesterday) and can reproduce 10/10 times when I run `react-native start --reset-cache`. Without the flag, everything works fine.

**Comment by gcolombani** [comment]
Same problem here.

**Comment by radko93** [comment]
Please reproduce with the latest version.
