### ISSUE TITLE
cannot set property '_currentvalue' of undefined

### ISSUE THREAD

**Issue by luvita** [facebook/react-native#20369]
hi all, i have a issue : "cannot set property '_currentvalue' of undefined" when i run on android
this is my project: 
https://github.com/luvita/changeLaucher

pls, help me. :(

version:
"firebase": "^5.3.0",
    "react": "16.3.0-alpha.1",
    "react-native": "0.55.4",
    "react-native-firebase": "^4.3.7",
    "react-navigation": "^2.9.0",
    "redux-devtools-extension": "^2.13.5"

<img width="302" alt="screen shot 2018-07-24 at 10 52 49 pm" src="https://user-images.githubusercontent.com/41312974/43151357-071d9180-8f96-11e8-8685-effd025eb202.png">

**Comment by pzatorski** [comment]
Hi @luvita The problem is in your App.js file you are using SwitchNavigator but you actually didn't create any StackNavigator or SwitchNavigator before.
That should help you understand it a bit better:

https://reactnavigation.org/docs/en/hello-react-navigation.html

**Comment by luvita** [comment]
@pzatorski 
this is my App.js
import React, { Component } from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  View,
  TouchableHighlight,
  NativeModules,
  TextInput,
  StatusBar,
  TouchableOpacity, WebView
} from 'react-native';
import firebase from 'react-native-firebase';
import { SwitchNavigator } from 'react-navigation';

// import the different screens
import Loading from './src/component/Load/Load'
import SignUp from './src/component/SignUp/SignUp'
import Login from './src/component/Login/Login'
import Main from './src/component/Main/Main'


const App = SwitchNavigator({
    Loading: {
      screen: Loading,
    },
    SignUp: {
      screen: SignUp,
    },
    Login: {
      screen: Login,
    },
    Main: {
      screen: Main,
    },
  },
  {
    initialRouteName: 'Loading'
  });

export default App;

i has create StackNavigator :( i dont understand
