### ISSUE TITLE
TextInput intercepted the screen slipping[Android]

### ISSUE THREAD

**Issue by fujiyuer** [facebook/react-native#20360]
## Environment
Environment:
  OS: Windows 10
  Node: 8.11.2
  Yarn: 1.7.0
  npm: 6.1.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

## Description
When IOS is normal, the following problems arise in Android:
When I set style={{textAlign:'right'}} for TextInput, and put my fingle on the TextInput to slide the screen, failed.
But if I set multiline={true} at the same time,  success.
I hope a singleline TextInput without intercepting screen slipping.

**Comment by radko93** [comment]
Please provide a repro for that issue.

**Comment by fujiyuer** [comment]
Thank you for answering me in your busy schedule. I tried to upgrade react-native to 0.56.0 to test, but for some reasons, I couldn't see the result immediately. I will try to solve the problem in the next few days.
Here is a reproducing code for a problem and a dynamic diagram for demonstrating problems
![gif](https://user-images.githubusercontent.com/11517017/43303786-fdaf7fe0-91a3-11e8-922b-79c09f0141df.gif)
:
`import React, {Component} from 'react';
import {
    StyleSheet,
    TextInput,
    ScrollView,
    View,
} from 'react-native';

type Props = {};
export default class App extends Component<Props> {
    render(){
        return (
            <ScrollView style={{ flex: 1 }}>
                <TextInput style={[styles.ipt]}
                           defaultValue={"default => can sroll"}/>
                <View style={styles.seize}/>
                <TextInput style={[styles.ipt, { textAlign: 'right' }]}
                           defaultValue={"right => can't sroll"}/>
                <View style={styles.seize}/>
                <TextInput style={[styles.ipt, { textAlign: 'center' }]}
                           defaultValue={"center => can't sroll"}/>
                <View style={styles.seize}/>
                <TextInput style={[styles.ipt, { textAlign: 'right' }]}
                           multiline={true}
                           defaultValue={"right & multiline => can sroll"}/>
                <View style={styles.seize}/>
                <TextInput style={[styles.ipt, { textAlign: 'center' }]}
                           multiline={true}
                           defaultValue={"center & multiline => can sroll"}/>
                <View style={styles.seize}/>
            </ScrollView>
        );
    }
}
const styles = StyleSheet.create({
    seize: { backgroundColor: 'pink', height: 100, },
    ipt: { backgroundColor: '#fafafa', height: 100, }
});
`
