### ISSUE TITLE
cannot set property '_currentvalue' of undefined

### ISSUE THREAD

**Issue by luvita** [facebook/react-native#20371]
## Environment
version:
"firebase": "^5.3.0",
"react": "16.3.0-alpha.1",
"react-native": "0.55.4",
"react-native-firebase": "^4.3.7",
"react-navigation": "^2.9.0",
"redux-devtools-extension": "^2.13.5"

## Description
this is my project on github: https://github.com/luvita/changeLaucher
this is my issue: "cannot set property '_currentvalue' of undefined" when i run on android
i connected firebase, i use react-native-firebase with react-navigation

## Reproducible Demo

<img width="302" alt="screen shot 2018-07-24 at 10 52 49 pm" src="https://user-images.githubusercontent.com/41312974/43155355-61f49e72-8fa1-11e8-8be5-c88c078d5f58.png">

**Comment by victoriafeng** [comment]
react-native -v . 0.54.0
macos has this problem ？
