### ISSUE TITLE
Failed to execute aapt. when upgraded from RN 0.54.0 to 0.56.0 -- Android

### ISSUE THREAD

**Issue by EyreGe** [facebook/react-native#20391]
"react": "^16.2.0",
    "react-native": "0.54.0",
    "react-native-blur": "^3.2.2",
    "react-native-code-push": "^5.3.2",
    "react-native-device-info": "^0.21.5",
    "react-native-drawer": "^2.5.0",
    "react-native-exception-handler": "^2.8.9",
    "react-native-fast-image": "^2.2.6",
    "react-native-fbsdk": "^0.7.0",
    "react-native-fs": "^2.9.11",

the list above is my developing enviroment,  during the upgrading to react-native 0.56, most of 3rd party dependencies got errors like those below:

../node_modules/react-native-exception-handler/android/build/intermediates/res/merged/debug/values-v24/values-v24.xml

Error:(3) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.

../node_modules/react-native-exception-handler/android/build/intermediates/res/merged/debug/values-v26/values-v26.xml

Error:(15, 21) No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.

Error:Execution failed for task ':react-native-exception-handler:processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

anyone faces the same issues?

**Comment by ukasiu** [comment]
@EyreGe I do

**Comment by EyreGe** [comment]
@ukasiu I solved the problem. 
![image](https://user-images.githubusercontent.com/19946413/44445042-1fec4480-a612-11e8-99d4-bcce947fe58b.png)
Modified  to:
![image](https://user-images.githubusercontent.com/19946413/44445076-3d211300-a612-11e8-9102-9db60e1496bc.png)
