### ISSUE TITLE
ERROR Metro Bundler can't listen on port 8081

### ISSUE THREAD

**Issue by anil-sidhu** [facebook/react-native#20399]
![screenshot from 2018-07-26 00 56 46](https://user-images.githubusercontent.com/14924211/43223297-48392514-9070-11e8-8d3b-2845ee9be571.png)

**Comment by Berkodev** [comment]
You probably have another application listening to port 8081, likley another instance of Metro Bundler.

Try the command "lsof -i" to find that process.

**Comment by anil-sidhu** [comment]
@Berkodev  no. 8081 port is totally free.
