### ISSUE TITLE
[Android] Custom fonts not applied on nested text

### ISSUE THREAD

**Issue by mikeygee** [facebook/react-native#20398]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
 React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 557.12 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.9.4 - /usr/local/bin/node
      Yarn: 1.3.2 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
    IDEs:
      Android Studio: 3.0 AI-171.4408382
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1

## Description
On Android only, when nesting text elements, and applying custom fonts to both the outer and inner text elements, the inner text does not apply the font, it falls back to default. This issue does not occur when using system fonts such as `serif` or `monospace`, it only happens when using two custom fonts. One custom font nested with a system font works fine. I am not sure if it is a problem with these specific fonts, but it works fine in iOS.

## Reproducible Demo
https://github.com/mikeygee/AndroidFontIssue - I made a repo with a couple custom fonts added to assets/fonts directory. In App.js, there are several combinations to demonstrate the issue.
```
<View style={styles.container}>
    <Text style={{fontFamily: 'customthickfont', fontSize: 20}}>
      Test
      <Text style={{fontFamily: 'customthickfont', fontSize: 20}}>Nested</Text>
    </Text>
    <Text style={{fontFamily: 'customthickfont', fontSize: 20}}>
      Test
      <Text style={{fontFamily: 'Roboto', fontSize: 20}}>Nested</Text>
    </Text>
    <Text style={{fontFamily: 'customthickfont', fontSize: 20}}>
      Test
      <Text style={{fontFamily: 'serif', fontSize: 20}}>Nested</Text>
    </Text>
    <Text style={{fontFamily: 'customitalicfont', fontSize: 20}}>
      Test
      <Text style={{fontFamily: 'customitalicfont', fontSize: 20}}>Nested</Text>
    </Text>
    <Text style={{fontFamily: 'customitalicfont', fontSize: 20}}>
      Test
      <Text style={{fontFamily: 'customthickfont', fontSize: 20}}>Nested</Text>
    </Text>
    <Text style={{fontFamily: 'serif', fontSize: 20}}>
      Test
      <Text style={{fontFamily: 'customthickfont', fontSize: 20}}>Nested</Text>
    </Text>
    <Text style={{fontFamily: 'serif', fontSize: 20}}>
      Test
      <Text style={{fontFamily: 'monospace', fontSize: 20}}>Nested</Text>
    </Text>
</View>
```
![image](https://user-images.githubusercontent.com/885069/43221751-a37434aa-9002-11e8-8859-7a4c09f9e655.png)

**Comment by OmriSama** [comment]
+1, I think I'm running into the same issue :/

**Comment by gurol** [comment]
I have the same problem in Android (it works in iOS).

**Comment by OmriSama** [comment]
I think I got this to work by enabling font scaling?

**Comment by duongntb94** [comment]
I have the same issue in Android

**Comment by rikur** [comment]
+1, works fine on iOS but Android ignores the fontFamily of nested <Text> elements.

**Comment by creativefctr** [comment]
Same issue here!

**Comment by nzliu** [comment]
Getting the same issue.

**Comment by rikur** [comment]
Still a bug on latest react-native.

**Comment by OmriSama** [comment]
@rikur @Chalked do you guys have font scaling disabled?

**Comment by jdgarcia1381** [comment]
Same problem here. `fontFamily` is being ignored on nested Text and I can't find a solution for this. Enabling font scaling doesn't solve it for me.
If I apply the same `fontFamily` on nested Text, it is ignored.

**Comment by DmytroT** [comment]
any news? 
it works in <=0.49.5 versions.
and it doesn't work since 0.50 version.
it is important for our app  and we can't use latest RN versions anymore... :(

**Comment by ospiewok** [comment]
We've found a solution, which worked in our case. 
You have to set the style properties of your nested text component, so that the parent style properties do not have an effect on your nested text.

In our case we had a custom nested text inside a common text component and we were missing to set the fontWeight style property inside our nested custom text. 
This was only an Android issue.

`<Text style={{ fontFamily: baseFont, fontSize: 42, lineHeight: 48, fontWeight: '700', color: colors.white, }} numberOfLines={1}>
<Text style={{ fontFamily:'our-custom-icons', fontWeight:'normal', color:'white', lineHeight: 50 }}>{'\uE921'} </Text>   Some custom text follow up!} </Text>`

**Comment by lewie9021** [comment]
I've written a Medium post that goes more in depth, detailing my findings and an interim fix :) https://medium.com/@lewie9021/custom-fonts-in-react-native-85d814ca084#a01b

**Comment by rikur** [comment]
@lewie9021 thanks for sharing. Do you think this could be turned into an NPM package as a replacement for `Text` from RN?

**Comment by lewie9021** [comment]
I don't see why it couldn't be, but I'd prefer if the bug was fixed instead of releasing an NPM package that patches it. I just felt that it was pretty basic behaviour that should at least have a workaround for now.

**Comment by rikur** [comment]
Alright, I'll try to strip away the parts that don't apply to me, like Contexes and stuff. Thanks again!

**Comment by lewie9021** [comment]
You'll still need a form of Context. The `FontFamilyContext` is used collect the styling as you nest, only applying the font family when a leaf Text component is encountered. Without it, if a containing Text component applied a bold font weight, the nested leaf Text component wouldn't know that it should apply a bold font family variant (unless overwritten through the component tree or directly).

**Comment by rikur** [comment]
I see. Thanks for the heads-up -- I might just have to wait for this to be fixed in RN then as I don't use Contexes and prefer to keep things that way.

**Comment by lewie9021** [comment]
I can understand not wanting to use Context :) In my article, I do briefly talk about another approach that uses `React.Children.map` and `React.cloneElement` to automatically delegate the props down through the tree. The main issue I had with the approach was that if custom Text components were used when nested (e.g. `Heading`), it's not guaranteed to pass through the styling. As a result, it could become difficult to track down why the correct font variation isn't applied.

**Comment by wandhi** [comment]
fontFamily its not work in inlinstyle you must change from

<Text style={{fontFamily:'SantPro'}} />
to
<Text style={styles.text} />

const styles = StyleSheet.create({
   text: {
        fontFamily:'SantPro',
        
    },
    

})

**Comment by rikur** [comment]
Still a bug AFAIK

**Comment by NappyPirate** [comment]
Still an issue

**Comment by harshit-prog** [comment]
Still not fixed...

**Comment by qstrauss** [comment]
Hey there,

It seems that a Text with custom font can't be nested in another Text with custom font, but they can be nested together in a simple react-native Text to fix the issue :

Broken : 
```
<Text style={{fontFamily: 'customFontFamily-Bold'}}>
      Custom font text
      <Text style={{fontFamily: 'customFontFamily-LightItalic'}}>Nested custom font text</Text>
</Text>
```

**Works for me :**
```
<Text>
      <Text style={{fontFamily: 'customFontFamily-Bold'}}>
            Nested custom font text
      </Text>
      <Text style={{fontFamily: 'customFontFamily-LightItalic'}}>
            Different nested custom font text
      </Text>
</Text>
```

**Comment by rikur** [comment]
@qstrauss thanks for the heads up, I'll give this a go

**Comment by Youngdi** [comment]
Hi Guys. I figured that it is not only font family has the bug. I think all the customize style in nested text all has issue.

Here is the simple text code with fontSize and I just tested it on React Native API website.

```
import React, { Component } from 'react'
import {
  ActivityIndicator,
  StyleSheet,
  Text,
  View,
  ScrollView
} from 'react-native'

const TEST_DATA = new Array(100).fill(1).map(i => 'i love to code')
export default class App extends Component {
  renderVerse = (verseItem) => 
    <Text style={{ fontSize: 26}}>{verseItem}</Text>
  renderNumber = (verseItem) =>
    <Text style={{ fontSize: 26}}>{verseItem}</Text>
  render() {
    return (
      <View style={[styles.container, styles.horizontal]}>
        <ScrollView>
           <Text>
              {TEST_DATA.map((verseItem, i) => [
                React.cloneElement(this.renderNumber(i)),
                React.cloneElement(this.renderVerse(verseItem)),
              ])}
           </Text>
         </ScrollView>
      </View>
    )
  }
}
const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center'
  },
  horizontal: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    padding: 10
  }
})
```

**Comment by brambang** [comment]
> Hey there,
> 
> It seems that a Text with custom font can't be nested in another Text with custom font, but they can be nested together in a simple react-native Text to fix the issue :
> 
> Broken :
> 
> ```
> <Text style={{fontFamily: 'customFontFamily-Bold'}}>
>       Custom font text
>       <Text style={{fontFamily: 'customFontFamily-LightItalic'}}>Nested custom font text</Text>
> </Text>
> ```
> 
> **Works for me :**
> 
> ```
> <Text>
>       <Text style={{fontFamily: 'customFontFamily-Bold'}}>
>             It seems to be
>       </Text>
>       <Text style={{fontFamily: 'customFontFamily-LightItalic'}}>
>             the solution
>       </Text>
> </Text>
> ```

yes it works for me too.
thanks!

**Comment by t-ricci-enhancers** [comment]
Same problem with two custom fonts...

I need to be able to do:

```jsx
<Text style={{fontFamily: 'Ubuntu-Regular'}}>
  <Text style={{fontFamily: 'Icons-Font'}}>□</Text>
  Text prepended by icon
</Text>
```

**Comment by BillTuan** [comment]
Works for me by adding fontWeight: 'normal' & fontStyle: 'normal'
`
<Text style={{ fontFamily: 'Quicksand-Medium', fontWeight: 'normal',  fontStyle: 'normal' }}>
      text abc
      <Text style={{ fontFamily: 'Gilroy-Bold' }}>Nested font text</Text>
</Text>
`

**Comment by hmol** [comment]
> Works for me by adding fontWeight: 'normal' & fontStyle: 'normal'
> 
> ```
> <Text style={{ fontFamily: 'Quicksand-Medium', fontWeight: 'normal',  fontStyle: 'normal' }}>
>       text abc
>       <Text style={{ fontFamily: 'Gilroy-Bold' }}>Nested font text</Text>
> </Text>
> ```

I hade the same problem, only on Android phones. The solution metioned above, solved it for me. Having a parent element with ```fontStyle: "normal"``` was what fixed it.

**Comment by muhammadwafa** [comment]
2020 still cant style nested text, this properties does not work in `nested Text`:

`padding, margin, borderColor, borderWidth, borderRadius, lineheight, top, bottom, left, right, ...`

**Comment by DmytroT** [comment]
The issue has not been fixed. It looks like guys just ignore that.

**Comment by muhammadwafa** [comment]
This is still an issue

**Comment by fabriziobertoglio1987** [comment]
I could not reproduce this in `rn-tester` using `notoserif` and `rubik`. I believe they are custom fonts https://github.com/react-native-training/react-native-fonts

```jsx
<Text style={{fontFamily: 'notoserif', fontSize: 20}}>NotoSerif</Text>
   <Text style={{fontFamily: 'rubik', fontSize: 20}}>
     Rubik
   <Text style={{fontFamily: 'notoserif', fontSize: 20}}>NotoSerif</Text>
</Text>
```

**<details><summary>CLICK TO OPEN TESTS RESULTS</summary>**
<p>

| **RN MASTER** |
|:-------------------------:|
| <img src="https://user-images.githubusercontent.com/24992535/106876920-837e6580-66d8-11eb-9107-e368eabea4dc.png" width="300" height="" /> |

</p>
</details>

**Comment by devethan** [comment]
Still an issue, the problem looks like related to `custom font style` on the `Text` of `react-native` module.
@qstrauss said we should use nested text like below

```html
<Text>
      <Text style={{fontFamily: 'customFontFamily-Bold'}}>
            It seems to be
      </Text>
      <Text style={{fontFamily: 'customFontFamily-LightItalic'}}>
            the solution
      </Text>
</Text>
```

But I don't understand those style adoption because of [the docs of react-native said](https://reactnative.dev/docs/text#nested-text)

Theoretically speaking in above document, nested fonts inherit it's parents' style. But it cannot be worked in currently, and then default styles of font(the system font) will be adopted.

**Comment by 1280103995** [comment]
Still unresolved.    RN v0.64.2

**Comment by apedroferreira** [comment]
2021 reporting in! still have this issue, let's go all the way to 2025

**Comment by liamjones** [comment]
Looks like this might be working in 0.66.3? I've not tried the minimal repro but I'm looking at an area of our app where I believe we had this issue it seems to be working now. Can anyone else confirm/deny?

**Comment by DmytroT** [comment]
It still doesn't work in 0.66.1
Going to check it in 0.66.3

**Comment by maxilie** [comment]
I'm on RN 0.68.2 with expo-font, and none of the suggested solutions are working for me. I've tried nesting Text elements horizontally instead of going deep, and I've also tried setting parent's fontStyle and fontWeight to 'normal'. Neither approach solves the problem.

Has anyone found another solution?

**Comment by SaikalSdd** [comment]
I found the SOLUTION !!! 
Add `fontWeight: 'normal', fontStyle: 'normal'` to the NESTED child, and that's it !

`<Text style={{ fontFamily: NotoSans.Bold }}>
      <Text style={{ fontFamily: NotoSans.BoldItalic, fontWeight: 'normal', fontStyle: 'normal', color: 'red' }}>Sdd</Text>
</Text>`

<img width="94" alt="image" src="https://user-images.githubusercontent.com/38737621/203180113-7f711158-7b68-4dbc-af08-818ff576a899.png">
