### ISSUE TITLE
RN Modal component some times doesn't show when toggled after the initial render

### ISSUE THREAD

**Issue by jpamarohorta** [facebook/react-native#20394]
## Environment
```
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-5675R CPU @ 3.10GHz
      Memory: 36.66 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 9.5.0 - /usr/local/bin/node
      Yarn: 1.0.0 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1
      react-native: 0.56.0 => 0.56.0
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

## Description
RN Modal component some times doesn't show when toggled after the initial render.

Example code:
```
...
render() {
   return (
      <View>
         ...
         { this.state.stateVariable &&
         <Modal
            animationType="fade"
            transparent
            visible
            onRequestClose={() => {}}>
            ...
         </Modal>
         }
      </View>
   )
}
...
```

When I set the state `stateVariable` to true, sometimes the modal appears, sometimes it doesn't. If I show the modal from the beginning it always shows. The same behaviour happens if I pass to the `visible` prop the value of `stateVariable` instead of handling the rendering toggle outside.

I also noticed that the Modal element and its contents are present in the app structure when inspected using React Native Debugger, they just don't show.

This is exactly the same issue as https://github.com/facebook/react-native/issues/19345 .

## Reproducible Demo
I'm still trying to make a repo that reproduces this issue but it has been difficult since it doesn't happen every time.

**Comment by tomoakley** [comment]
I'm experiencing this issue too, except I can't show the Modal at all. As @jpamarohorta said, the Modal markup is visible in the Inspector but doesn't show. I'm also passing the props slightly differently:

```
...
render() {
   return (
      <View>
         ...
         <Modal
            animationType="fade"
            transparent
            visible={this.state.stateVariable}
            onRequestClose={() => {}}>
            ...
         </Modal>
         ...
      </View>
   )
}
...
```

**Comment by ThomasStubbe** [comment]
Any progress on this? I'm experiencing a very similar problem. For me it shows on the initial render, it can be hidden, but when made visible again, nothing happens, although, it is changed in the inspector...

**Comment by LeXuanTien** [comment]
I am facing this issue on reac-native 0.57.5

```
<Modal
              animationType={"slide"}
              transparent={true}
              visible={this.state.modalAccessoryVisible}
...
```

Issue: when I try to run this.setState, the modal auto close, I logged this.state.modalAccessoryVisible, it show true

This issue appear on iOS.

Android worked great.

**Comment by evaleirasclapps** [comment]
Same here!

**Comment by DavidWangDev** [comment]
same here, Too!

**Comment by pankti1210** [comment]
i had the same issue in iOS...
using two modals at the same time.. for the second modal i used setTimeout function.. and its working perfectly in iOS...

**Comment by thinhlm** [comment]
I have the same issue on React 0.59.9. Does anyone have a solution?

**Comment by arjanvanham** [comment]
Same here. It _seems_ to work more reliable with https://github.com/react-native-community/react-native-modal
