### ISSUE TITLE
[Animated] bundle --minify Error

### ISSUE THREAD

**Issue by qingfeng** [facebook/react-native#2039]
js code:
`translateY: new Animated.Value(100),` 

Executed `react-native bundle --minify --out main.jsbundle`
after: `translateY:new I.Value(100)`

Error:
```
2015-07-18 14:48:24.143 [error][tid:com.facebook.React.JavaScript] 'Error: undefined is not an object (evaluating \'new I.Value\')\n stack: 
```

**Comment by chirag04** [comment]
did u require Animated?

**Comment by warrenshen** [comment]
@qingfeng You probably didn't update react native to the 0.8.0 release.

**Comment by brentvatne** [comment]
@chirag04 and @warrenshen's tips are right, also make sure you restart packager when you update!
