### ISSUE TITLE
Invalid code coverage with react-native/jest/preprocessor.js

### ISSUE THREAD

**Issue by retyui** [facebook/react-native#20404]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```bash
  React Native Environment Info:
    System:
      OS: Linux 4.15 Linux Mint 18.3 (Sylvia)
      CPU: x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
      Memory: 1.10 GB / 7.67 GB
      Shell: 2.7.1 - /usr/bin/fish
    Binaries:
      Node: 8.11.3 - /usr/bin/node
      Yarn: 1.7.0 - /usr/bin/yarn
      npm: 6.2.0 - /usr/bin/npm
    SDKs:
      Android SDK:
        Build Tools: 23.0.1, 26.0.3, 27.0.3, 28.0.1
        API Levels: 23, 25, 26, 28
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: ^0.56.0 => 0.56.0 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

## Description
We use js Generators in own project, and when we run test `jest --coverage` we have a bad result because of the `react-native/jest/preprocessor.js` polyfilled `function*(){}` and create some helper function that affect to coverage result

## Reproducible Demo
**Info**: https://gist.github.com/retyui/760ff91c0fab7310f8cea8c7e5c43978
Result: 
![image](https://user-images.githubusercontent.com/4661784/43256226-c9551f86-90d4-11e8-8b44-23d9dcc22915.png)

**Comment by retyui** [comment]
Good first issue

**Comment by retyui** [comment]
Anyone help me?

**Comment by Traviskn** [comment]
@retyui Did you find a solution to this? I am also having issues with code coverage reports after upgrading to react-native 0.57

**Comment by retyui** [comment]
@Traviskn I didn't find a solution to this problem

**Comment by vidit-bhatia** [comment]
@retyui I think we must open this issue again. This does not make sense I see exact same thing and this does not mkae sense my team has a mandate for 80% code coverage per component and I do not think anyone can achieve it with this bug

**Comment by cpojer** [comment]
I recognize this issue exists but it's unlikely anyone will spend time on fixing this. I'll close this issue but if you need this fixed I recommend investigating and sending a PR with a fix :)

**Comment by alexcanessa** [comment]
I'm just using `babel-jest` as a `transform`, instead of using the preprocessor and it worked.
Not sure yet if it's going to have bad consequences 😂
