### ISSUE TITLE
[Error Handling] Root stacktraces to a js call, always

### ISSUE THREAD

**Issue by mschipperheyn** [facebook/react-native#2040]
I'm trying to debug an issue I have with 0.8.0-rc where I get a really cryptic stacktrace and it's really hard to trace it back to the js-source. I find I run into this situation quite often in React.

In most cases, the root of an exception will be some method call or jsx tag in a js file. And knowing its location would seriously speed up debugging.

Therefore I would recommend always displaying at least the js root location that originates the exception. 

To illustrate, I've attached a screenshot of the exception I got (it doesn't show up as such in Chrome debugger). 
![ios simulator screen shot jul 18 2015 10 03 22](https://cloud.githubusercontent.com/assets/384959/8761678/638979b0-2d34-11e5-8484-022e517d648e.png)
This is not intended as a report on that exception itself, but just as an illustration. 

The same goes for some of the warnings you get such as 
Warning: LoadingScreen.type is deprecated. Use LoadingScreen directly to access the class. 
with as root: WarningBox.js. 
That's only the root for the messaging component that logs the message, not the actual root of the exception.

**Comment by brentvatne** [comment]
I've run into this as well, cc @ccheever :smile:

**Comment by tadeuzagallo** [comment]
Can any of you guys provide a sample of this? I'll try to improve it, I agree it's pretty bad right now.

**Comment by brentvatne** [comment]
@mschipperheyn - ping

**Comment by mschipperheyn** [comment]
@brentvatne Oh hi, yeah. I think I started seeing this when I started using the Animated library for the first time after upgrading to 0.8.0-rc. I am trying to think what I did to resolve it, although I did have things such as trying to animate values that haven't been set with new Animated.Value but are straight ints, which creates its own confusing exception, or it might have been that 0.8.0-rc2 just creates better exceptions. But I have a number of issues since that upgrade such as fetch and Netinfo not working anymore. So maybe I just need to do a clean install

**Comment by mschipperheyn** [comment]
@brentvatne Ok, after a night of sleep I remembered. This stacktrace occurred because I was using a custom font file in the project that was not present anymore. This font configuration was based on react-native-vector-icons. It went away after I made sure the font was in the expected place again.

**Comment by browniefed** [comment]
@brentvatne looks like this got resolved.
