### ISSUE TITLE
[ScrollView] nestedScrollEnabled prop not working?

### ISSUE THREAD

**Issue by hovoodd** [facebook/react-native#20403]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.5
      CPU: x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 2.45 GB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 9.5.0 - ~/.nvm/versions/node/v9.5.0/bin/node
      npm: 6.0.1 - ~/.nvm/versions/node/v9.5.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1
      react-native: 0.56.0 => 0.56.0
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

## Description
ScrollView [nestedScrollEnabled](https://facebook.github.io/react-native/docs/scrollview#nestedscrollenabled) prop not working? I mean, I haven't been able to use nested scrollView on both platforms.

Prop really doesn't work (should be removed from the doc?) or work, but different somehow? 🤔

## Reproducible Demo
[Minimal example](https://snack.expo.io/BkyKs-PVX)

**Comment by hhunaid** [comment]
Any update? I have to update to 0.56 for this feature only. If it doesn't work, I don't wanna bother upgrading just yet.

**Comment by onusgit** [comment]
any update yet?

**Comment by roysG** [comment]
any update?

**Comment by roysG** [comment]
What is your version of react native?

**Comment by hovoodd** [comment]
@roys `0.56.0`

**Comment by snehalhumne** [comment]
Hey, this is working fine for me for Android and iOS both!

**Comment by machester4** [comment]
In my case it only works in IOS. My nesting is somewhat complex. I have the following structure
```
 Vertical List
      Horizontal List
          Vertical List (no scroll)
```
I'm using expo SDK 30. react native 56.4

**Comment by machester4** [comment]
Hi @hhunaid , [here](https://snack.expo.io/rJ6Ah6st7) is an example.

**Comment by machester4** [comment]
Sorry `Expo SDK 30` uses `react-native 55.4`.

**Comment by nighttiger1990** [comment]
+1 on Android `react-native 0.57.0`

**Comment by zhangjialegh** [comment]
+1 on Android react-native 0.57.0

**Comment by zhangjialegh** [comment]
I am sure that is a bug! It words well when vetical scroll

**Comment by zhangjialegh** [comment]
Any update?

**Comment by zhulin2609** [comment]
same issue

**Comment by Titozzz** [comment]
Hello there 👋 this issue has been reported for an old version of React Native. Ideally we'd like everyone to be using 0.59 (see the [awesome changes](https://facebook.github.io/react-native/blog/2019/03/12/releasing-react-native-059) it brought) but we know updating can be a pain. We are going to close this issue because it's from a version before 0.57, which is really old.

But please, if it's actually still an issue with 0.59 please comment below and we can reopen it. Even better, please send us a pull request with a fix 😊

**Comment by mrquanghuy** [comment]
im using 0.59.3 and till not working :(

**Comment by jeffmon** [comment]
Hi, we're having this issue as well. We have two nested horizontal ScrollViews both with `nestedScrollEnabled={true}` and it doesn't work on Android. iOS works perfectly. 

On react-native `v0.59.8`.

**Comment by aanah0** [comment]
Why it closed? Have the same issue too

**Comment by neilzhengzx** [comment]
its should enable the prop on all the lists
