### ISSUE TITLE
Rotation with pivot point

### ISSUE THREAD

**Issue by hamzaawais** [facebook/react-native#20408]
I want to rotate this image around  a pivot point using pan responder.

<img width="281" alt="screen shot 2018-07-26 at 6 15 56 pm" src="https://user-images.githubusercontent.com/39099632/43264600-04b175a4-9100-11e8-8d7d-2b6dd4af2f03.png">

I am using transformMatrix for rotation around a pivot point but its not smooth as i want.
There is a Transform origin property in css styling which use to rotate image around pivot point. Is there any property just like "transform-origin" in react native?

**Comment by pandasoft0** [comment]
the same problem

**Comment by evansherry** [comment]
I think this problem should be reopened.
