### ISSUE TITLE
App orientation resets after closing Modal

### ISSUE THREAD

**Issue by IanCStewart** [facebook/react-native#20402]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Environment:
  OS: macOS High Sierra 10.13.5
  Node: 8.11.3
  Yarn: 1.7.0
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-28.0.1.tar.gz => 0.55.4

## Description
App orientation resets after closing a Modal. This occurs when opening the Modal after orientation change. As well as when changing the orientation while the Modal is opened.

![43209265-81632496-902c-11e8-92ba-d76a9bd22e28-1](https://user-images.githubusercontent.com/14125280/43252578-2e9f1566-90c3-11e8-9cc3-d62e5e339030.gif)

## Reproducible Demo
https://snack.expo.io/SJUe2-D4m

**Comment by kadoshms** [comment]
I can confirm that.
