### ISSUE TITLE
[WebView] postMessage doesn't follow the spec

### ISSUE THREAD

**Issue by brunobar79** [facebook/react-native#20400]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Run `react-native info` in your terminal and paste its contents here.
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
      Memory: 29.69 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 9.9.0 - ~/.nvm/versions/node/v9.9.0/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.1.0 - ~/.nvm/versions/node/v9.9.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 23.0.3, 25.0.0, 25.0.1, 26.0.1, 26.0.2, 26.0.3, 27.0.3
        API Levels: 23, 25, 26, 27
    IDEs:
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1
      react-native: 0.56.0 => 0.56.0
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1

## Description
The original spect of postMessage allows different types of data (aside of string) and as you can see [here](http://gregers.no/browserscope/postmessage-object-test.html), this feature it's supported by all the major browsers.

However, the WebView component in React Native only accepts a string, and if you pass an object you get "[object Object]" in  the React Native JS side.

## Reproducible Demo
Create a new project, add a webview with the following prop and test on Android & iOS

```
<WebView
    injectedJavaScript={"setTimeout( _=> {window.postMessage({'a':34}, '*');}, 1000) "}
    onMessage={ e=> { console.log(e.nativeEvent.data) } }
    source={{ uri: 'https://google.com'}}
/>
```

Expected output: {a:34}
Current output: [object Object]

BTW, this issue has been solved correctly in this library: https://github.com/CRAlpha/react-native-wkwebview#advanced-communication-between-react-native-and-wkwebview which uses [WKscriptMessage](https://developer.apple.com/documentation/webkit/wkscriptmessage/1417901-body?language=objc) and the body property accepts the correct type.

**Comment by jamonholmgren** [comment]
Migrated to https://github.com/react-native-community/react-native-webview/issues/23 and can be closed here.
