### ISSUE TITLE
"Stream" is read-only error on run-time (occurred after migration from RN 0.53.3 to 0.56)

### ISSUE THREAD

**Issue by Ketn** [facebook/react-native#20415]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
  React Native Environment Info:
    System:
      OS: macOS Sierra 10.12.2
      CPU: x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 640.39 MB / 8.00 GB
      Shell: 3.2.57 - /bin/sh
    Binaries:
      Node: 10.7.0 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.2.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 10.3, macOS 10.12, tvOS 10.2, watchOS 3.2
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 8.3.3/8E3004b - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description
I just migrated from `react-native@0.53.3` to `react-native@0.56`. Also, as required, upgraded my node to 8+ (10.7.0) and babel to 7.0.0-beta.54. After completing the migration process, the following error showed up:

![rn-0 56-error](https://user-images.githubusercontent.com/7762370/43292286-3f182c68-9152-11e8-974f-abcbaad01fb6.jpeg)

Here are babel devDependencies:

> "devDependencies": {
>     "@babel/core": "7.0.0-beta.54",
>     "@babel/preset-flow": "7.0.0-beta.54",
>     "babel-core": "^7.0.0-bridge.0",
>     "babel-jest": "22.1.0",
>     "babel-preset-react-native": "5.0.2",
>     "jest": "22.1.4",
>     "react-test-renderer": "16.2.0"
>   },
>   "jest": {
>     "preset": "react-native"
>   }

I cannot find an issue similar to this anymore, hence posted it over here. Am I doing something wrong?

**Comment by john-hu** [comment]
+1. I had met the same issue after migrating to RN 0.56.

**Comment by Ketn** [comment]
@john-hu Thanks. Fixed for me after uninstalling `react-native-cheerio`. Is there any way to allow overriding Stream?

**Comment by john-hu** [comment]
It's just a workaround. I think the issue still exist. I don't know how to make Stream overridable....
