### ISSUE TITLE
Received data was not a string, or was not a recognised encoding

### ISSUE THREAD

**Issue by dbyilmaz** [facebook/react-native#20418]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```Environment:
  OS: macOS High Sierra 10.13.5
  Node: 9.8.0
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  react: ^16.2.0 => 16.4.1
  react-native: ^0.53.0 => 0.53.3
```
## Description
I want to get image etag. App request image url for this. Request retur success response. But ios app warn `Received data was not a string, or was not a recognised encoding`.
By the wat I tried to `fethc`. There is same problem.
```
  axios(url, requestHeader)
        .then(res => {})
        .catch(() => {});
```

I checked this issue https://github.com/facebook/react-native/issues/1780

**Comment by Ashoat** [comment]
This can happen if you're trying to use Blob on iOS without linking `RCTBlob`. Note that the RN Blob API has a lot of missing parts, so it's fairly unlikely to work with a library (which probably expects a full implementation).

**Comment by fungilation** [comment]
I've linked `libRCTBlob.a` and have `RCTBlob.xcodeproj` in my app. I'm seeing the same `Received data was not a string, or was not a recognised encoding` yellowbox warning, which I've never seen on my app without any logic changes that would have caused this. What's changed is upgrading RN from 0.57.8 to 0.59.5. FYI for tracing what might be causing this warning anew, if there's a surge of this warning seen by others besides me?

Stack trace isn't useful to me, all internal to RN. Similar to original issue, it happens on async `fetch()`:
![image](https://user-images.githubusercontent.com/3803466/56464719-8180d080-63a4-11e9-9b3a-aa1c9c5a2121.png)
