### ISSUE TITLE
TouchableOpacity loose context

### ISSUE THREAD

**Issue by Crysp** [facebook/react-native#20426]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
      Memory: 27.57 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.6.0 - ~/.nvm/versions/node/v10.6.0/bin/node
      Yarn: yarn install v0.20.3
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.70s. - /usr/local/bin/yarn
      npm: 6.1.0 - ~/.nvm/versions/node/v10.6.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 25.0.0, 25.0.1, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.0
        API Levels: 21, 23, 25, 26, 27, 28
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
```

## Description
There is an issue with `TouchableOpacity`.

This issue got only in app environment. When i create new clean project everything is ok.

Can you tell me where to look?

![](https://monosnap.com/image/TCIkMzgbSOKZQghLd6RH9pbARxHyOO.png)

## Reproducible Demo
[https://github.com/Crysp/solver](https://github.com/Crysp/solver)

__Update__
Add link to repo with reproducible error

**Comment by hramos** [comment]
Is there any way you can get this to reproduce on a brand new app? This is a minimum requirement as otherwise a contributor would have no way of testing a fix.

**Comment by Crysp** [comment]
@hramos, Add link to repo with reproducible error

**Comment by Crysp** [comment]
small correction. all projects in my env reproduce this issue
