### ISSUE TITLE
_OBJC_CLASS_$_RCTSRWebSocket

### ISSUE THREAD

**Issue by udarts** [facebook/react-native#20423]
- [X] Review the documentation: https://facebook.github.io/react-native
  - [X] Search for existing issues: https://github.com/facebook/react-native/issues
  - [X] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
    React Native Environment Info:
        System:
            OS: macOS High Sierra 10.13.6
            CPU: x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
            Memory: 22.10 MB / 8.00 GB
            Shell: 3.2.57 - /bin/bash
        Binaries:
            Node: 8.10.0 - /usr/local/bin/node
            npm: 6.1.0 - /usr/local/bin/npm
            Watchman: 4.9.0 - /usr/local/bin/watchman
        SDKs:
            iOS SDK:
                Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
            Android SDK:
                Build Tools: 23.0.1, 23.0.3, 24.0.1, 25.0.1, 25.0.2, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.3
                API Levels: 16, 17, 18, 19, 20, 21, 23, 24, 25, 26, 27
        IDEs:
            Android Studio: 3.1 AI-173.4819257
            Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
        npmPackages:
            react: 16.4.1 => 16.4.1 
            react-native: 0.56.0 => 0.56.0 
        npmGlobalPackages:
            react-native-cli: 2.0.1
            react-native-git-upgrade: 0.2.7

## Description
I am trying to run my app on my iPhone, but getting the following error in xCode:

    Undefined symbols for architecture arm64:
    "_OBJC_CLASS_$_RCTSRWebSocket", referenced from:
      objc-class-ref in libReact.a(RCTInspectorPackagerConnection.o)
    "_OBJC_CLASS_$_RCTReconnectingWebSocket", referenced from:
      objc-class-ref in libReact.a(RCTPackagerConnection.o)
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

It was working a couple of days ago and I haven't changed the code since then.

**Comment by stoneWeb** [comment]
@udarts So did you solve it? How do you solve it?

**Comment by shide1989** [comment]
same here, if you have a solution

**Comment by giantss** [comment]
same here

**Comment by shide1989** [comment]
@giantss i ended up adding the **libFishHook.a** library to my project's target and it solved my problem

**Comment by giantss** [comment]
@shide1989 Thanks, I didn't see a similar problem after I recreated the new project.

**Comment by jblancoh** [comment]
add libRCTWebsocket.a at xcode "Link Binary whit libraries ", works for me

**Comment by johannmiller** [comment]
This problem appeared out of nowhere for me. Everything had been building fine, until suddenly it didn't. I tried virtually all suggestions involving xcode build paths, schemes, library linking ordering etc. Did not help.  Finally, this is what got my build going again: `rm -rf node_modules && npm install`.

**Comment by FakeBounce** [comment]
Same as @johannmiller here, problem appeared from nowhere. `rm -rf node_modules && npm install` did the trick ! Thanks a lot
