### ISSUE TITLE
Code not updating 

### ISSUE THREAD

**Issue by omi10859** [facebook/react-native#20436]
## Environment
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
      Memory: 22.86 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.7.0 - /usr/local/bin/node
      npm: 6.2.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description
I'm new to react-native 
So, it started when some random syntax error came once when I changed my code using a text editor(in my case atom) and reloading app not solving my problem and getting that same error same error same error 
![screen shot 2018-07-28 at 1 54 49 pm](https://user-images.githubusercontent.com/26123416/43354652-e9a7b24a-926d-11e8-848f-8c512bb331a7.png)
![screen shot 2018-07-28 at 1 56 43 pm](https://user-images.githubusercontent.com/26123416/43354666-1dfafa02-926e-11e8-9527-b6a64d0d8dbc.png)

## Things i tried 
ok sharing this is bit interserting for me
I started from watchman uninstalling and installing doesn't solve it 
So, i thought it may be react-native error so, downgrading react-native and it also doesn't work 
ok,so maybe its node or npm error reinstalling doesn't work 
I was using Mojave beta maybe that was the error, so lets came back to macOS high sierra and i'm still getting this error      

Now, I'm thinking to move to flutter but again have to learn so much more things that i don't want now.
so, someone please help me solve this ..
Thanks

**Comment by hieunc229** [comment]
The error you got means it is unable to find the class "Home" from "./src/home.js" location.

Besides, I think anyone who started to use a new framework should learn from a tutorial or any available sources. When the error appears, try to read it carefully to understand what it tells, as the error message will be pretty obvious. It's also a good way to learn about the framework and help you troubleshoot.

**Comment by hieunc229** [comment]
Could you show a demo of your code? I think both "App.js" and "Home.js" files would be helpful
