### ISSUE TITLE
Promise Unhandled Promiss Rejection: undefined is not an object (evaluating "......

### ISSUE THREAD

**Issue by lasthrun** [facebook/react-native#20441]
## Environment
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz
      Memory: 28.23 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.1 - /usr/local/bin/node
      npm: 6.1.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
    IDEs:
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description
every things work fine on "Debug JS Remotely", but when i turn it down, some where error and show yellow box for `Promise Unhandled Promiss Rejection: undefined is not an object (evaluating "some variables"`.

i found a [issue](https://github.com/facebook/react-native/issues/15902), but i don't know it is related to this error

## Reproducible Demo
no

**Comment by radko93** [comment]
What do you mean by `some variables`?

**Comment by hramos** [comment]
It's unlikely we'll be able to be of any assistance with the amount of information we have at the moment. You may want to dig a bit deeper into the issue, and come back once you have narrowed down the steps to reproduce the issue.
