### ISSUE TITLE
[PanResponder] Grant is followed by a reject.

### ISSUE THREAD

**Issue by vishnevskiy** [facebook/react-native#2044]
Ever since upgrading to 0.8 there is a PanResponder that I have setup now grants and rejects at the same time. This usually happens when I am touching a custom native ScrollView.

I figured that if you are granted the next possible outcome is an end or terminate? Is it really possible to get granted then rejected?

**Comment by vishnevskiy** [comment]
It looks like for whatever reason now AFTER my scroll view captures my input for vertical scrolling. React seems to still be firing `onMoveShouldSetPanResponder` and if the logic returns true it grants it and rejects it instantly. Looks like in previous versions once the user started scrolling horizontally it was not calling `onMoveShouldSetPanResponder`.

**Comment by brentvatne** [comment]
@vishnevskiy - could you post a small reproducible example of this that we can run on 0.7 and 0.8 to see the diffference? that would help a lot!

**Comment by ericvicenti** [comment]
I think @a2 may have affected this with the the recent layout node removal optimization. If we get a small reproduction of this bug, I bet @tadeuzagallo can figure this out.

**Comment by brentvatne** [comment]
@vishnevskiy - any chance you could verify that this is still happening on 0.8.0-rc.2? That would be a great way to verify that the layout node removal optimization is the source of the problem

**Comment by vishnevskiy** [comment]
I have removed the layout node commit myself before and then followed up by syncing with latest master and the issue persists.

I am not sure when I will get to creating a repro for this that is standalone because it requires making an xcode project with a bit of native and js code and I am swamped.

In meantime we have worked around it by hiding the issue from the user.

**Comment by ericvicenti** [comment]
Oh, what does the native code that helps demonstrate this issue? We usually need to add extra code to make sure the JS touch responder system works with native components, and we haven't gotten very good at it yet.

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/panresponder-grant-is-followed-by-a-reject
