### ISSUE TITLE
The value entered in TextInput is set according to the value settings of the attribute.

### ISSUE THREAD

**Issue by iwangx** [facebook/react-native#20448]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Environment:
  OS: macOS High Sierra 10.13.3
  Node: 9.9.0
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.0 AI-171.4408382

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

## Description
![image](https://user-images.githubusercontent.com/11516318/43373683-df207d22-93dd-11e8-8e69-789b6a4f90cc.png)

The value of TextInput is the value after input. The value of the next row is the value of the state of the current component, and the value of TextInput is not set to the state value of the component.

## Reproducible Demo
```javascript
import React, {PureComponent} from "react"

import PropTypes from "prop-types"

import {
    View,
    TextInput,
    Text
} from "react-native"

class test extends PureComponent {

    constructor(props) {
        super(props);
        this.state={
            text:""
        };
    }

    static propTypes = {};

    static defaultProps = {};

    componentDidMount() {

    }


    onChangeText = (text)=>{
        let oldText = this.state.text;
        if(/\d$/.test(text)){
            this.setState({text:text});
        }else{
            this.setState({text:oldText})
        }
    };

    render() {
        const {
            state
        } = this;

        let {
            text
        } = state;

        return (
            <View>
                <TextInput
                    style={{marginTop:30,width:"100%",borderWidth:1,borderColor:"#000"}}
                    onChangeText={this.onChangeText}
                    value={text}
                />
                <Text>Text value by state:{text}</Text>
            </View>
        )
    }
}

export default test
```

**Comment by mmmulani** [comment]
maybe this happens because you aren't changing this.state, so the object isn't re-rendering. Try doing something like `this.setState({ text: oldText, lastInputText: text });`

**Comment by gwmccull** [comment]
This is occurring because your RegEx test is failing in `onChangeText`, which means that you're setting the `state.text` back to `oldText`.  If you want to filter the input, you'll need to use a different JavaScript function to clean the non-numeric characters from the input.  

You can also provide some safeguards by changing the `keyboard` prop of `TextInput` to `"numeric"` (although, that won't prevent users from using an external keyboard to enter alpha characters)

**Comment by gwmccull** [comment]
@kelset I think you can close this one
