### ISSUE TITLE
react native background fetch linking gives error

### ISSUE THREAD

**Issue by pulkitsapra** [facebook/react-native#20455]
```
react-native link react-native-background-fetch                                                                                               
Scanning folders for symlinks in /Users/pulkit/myproject/node_modules (11ms)
rnpm-install info Linking react-native-background-fetch ios dependency 
rnpm-install ERR! Something went wrong while linking. Error: Cannot read property 'buildConfigurationList' of undefined 
Please file an issue here: https://github.com/facebook/react-native/issues 

Cannot read property 'buildConfigurationList' of undefined

```

**Comment by EugeneBichel** [comment]
> ```
> react-native link react-native-background-fetch                                                                                               
> Scanning folders for symlinks in /Users/pulkit/myproject/node_modules (11ms)
> rnpm-install info Linking react-native-background-fetch ios dependency 
> rnpm-install ERR! Something went wrong while linking. Error: Cannot read property 'buildConfigurationList' of undefined 
> Please file an issue here: https://github.com/facebook/react-native/issues 
> 
> Cannot read property 'buildConfigurationList' of undefined
> ```

You can try with yarn https://github.com/transistorsoft/react-native-background-fetch/issues/102#issuecomment-433512560
