### ISSUE TITLE
TextInput Cursor does not disappear after click events.

### ISSUE THREAD

**Issue by kunalqss** [facebook/react-native#20453]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
  OS: Linux 4.13
  Node: 9.11.2
  Yarn: 1.7.0
  npm: 6.1.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found
Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.55.3 => 0.55.3

## Description
I have a form on the screen that shows a TextInput to enter Server Address. 
When I long press the TextInput, a small green cursor is shown below the TextInput. On pressing the SAVE button, I am redirected to a new screen, however the cursor pointer remains like a ghost from the past after having selected a <TextInput/> in a previous screen. Switching screens doesn't make it go away, pressing it doesn't do anything - it just floats there in the same spot. The issue could only be reproduced on Samsung 5.1.1 devices like the Samsung J3 Pro.

The following screenshot shows the cursor after the user moves to next screen - 

![6blyp](https://user-images.githubusercontent.com/33343995/43385713-16bea788-93ff-11e8-8386-4014e4cd3c3d.png)

## Reproducible Demo
The above stated issue can be reproduced using the code shown below - 

```
import React, { Component } from 'react';
import { Text, View, TextInput, TouchableOpacity, StyleSheet } from 'react-native';
import { Constants } from 'expo';

// You can import from local files
import AssetExample from './components/AssetExample';

// or any pure javascript modules available in npm
import { Card } from 'react-native-elements'; // Version can be specified in package.json

export default class App extends Component {
  render() {
    return (
      <View style={styles.container}>
        <TextInput style={{width:'100%', paddingBottom:10}} placeholder="Enter Text Here"></TextInput>

<TouchableOpacity onPress={()=>{this.moveToNewScreen()}}><Text style={{color:'white', backgroundColor:'blue', paddingTop:10, paddingBottom:10, width:150, justifyContent:'center', alignItems:'center', textAlign:'center'}}>SAVE</Text></TouchableOpacity>
        
      </View>
    );
  }

moveToNewScreen() {
  // enter navigation code here to move to new screen
}

}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: Constants.statusBarHeight,
    backgroundColor: '#ecf0f1',
  },
});

```

**Comment by Udbhav12** [comment]
@kunalqss - Did you manage to resolve this? I am facing the exact same problem in RN 0.57 as well

**Comment by saulojoab** [comment]
@kunalqss Hey, any luck solving that? I'm facing the same issue and can't seem to find any solution!

**Comment by kunalqss** [comment]
No I kept this issue aside as low priority, as it only occurred on a particular Samsung J3 with Android 5.1, but not on others.

**Comment by saulojoab** [comment]
Weeeeird, it's kind of sad that this wasn't (or can't) be fixed yet. I'll stick with my workaround, then.
