### ISSUE TITLE
[Document Request] Include Comperhensive Documentation on how to change PORT

### ISSUE THREAD

**Issue by meehanman** [facebook/react-native#20466]
There are lots of different methods online on how to change the port used by React-Native which is a breaking feature if port 8081 is blocked. There should be a tool created or good documentation that is updated with the steps in order to run React-Native, not on port 8081. 

McAfee uses this port and is required on many corporate servers and closing the process is not recommended.

I'd like to see this included in Getting Started // Troubleshooting.

**Comment by Nkzn** [comment]
This docs helps you?

```
$ react-native start --port=8088
```
https://facebook.github.io/react-native/docs/troubleshooting#using-a-port-other-than-8081
