### ISSUE TITLE
CameraRoll.getPhotos return just a few on iOS

### ISSUE THREAD

**Issue by andresespinosapc** [facebook/react-native#20462]
## Environment
Environment:
  OS: Linux 4.15
  Node: 10.6.0
  Yarn: 1.7.0
  npm: 6.1.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz => 0.55.4

## Description
The CameraRoll.getPhotos function only returns some photos on iOS, while it works perfectly on Android. For example, if I use the following parameters
```javascript
{
  first: 100,
  assetType: 'All',
  groupTypes: 'All',
}
```
I only get 39 photos, while I have more than a thousand in my camera roll. I have also tried with multiple different parameters, but the result is the same (or fewer photos because of a filter).

## Reproducible Demo
https://snack.expo.io/Hyw-kQa4X

- I think it must be run on a physical iOS device, because it has to access the camera roll.
- The demo prints the length of response.length, where response is the resolved value of CameraRoll.getPhotos with the parameters I mentioned earlier.

**Comment by hramos** [comment]
I just ran your Snack example on an iPhone X running iOS 11.4, and it's showing that it got 100 photos back 
![img_8307d70beff2-1](https://user-images.githubusercontent.com/165856/43492000-d069368a-94db-11e8-865b-150caf1e91c0.jpeg).

**Comment by hramos** [comment]
After tapping Load Images a few more times, it looks like it's successfully getting pages with 100 photos each.
![img_af757782ce99-1](https://user-images.githubusercontent.com/165856/43492090-345fec60-94dc-11e8-9069-dac144c4fa40.jpeg)

**Comment by radreamer** [comment]
I have the same issue, but the number of photos is equal to 17

![img_1566](https://user-images.githubusercontent.com/16123063/45303947-aca66600-b51f-11e8-8208-2c6d029bfd81.png)

**Comment by airlaser** [comment]
This may relate to `CameraRoll`'s underlying use of deprecated `ALAssetsLibrary ` instead of the new `PHPhotoLibrary `. For example, it has trouble detecting photos and videos which are in iCloud but not stored locally. 

A test - 

Run 

```
let assets = PHAsset.fetchAssets(with: .image, options: nil)
print(assets.count)
```

in a bridged Swift method. See what count that gives.

**Comment by hramos** [comment]
It may be that migrating to PHPhotoLibrary solves the issue, but it looks like that theory has not been put to the test yet.

@airlaser do you want to open a new separate issue to track the migration from ALAssetsLibrary to PHPhotoLibrary?

**Comment by bartolkaruza** [comment]
As part of lean core initiative CameraRoll has been moved to https://github.com/react-native-community/react-native-cameraroll
On https://github.com/react-native-community/discussions-and-proposals/issues/104 both this issue and #21836 have been marked as 'done' by @JoshuaGross .
All the commits from master regarding CameraRoll have been merged into the community repo, so if this issue is resolved, feel free to close it. If it is still relevant, I think it's best to continue the discussion on a new issue at the [new home for CameraRoll](https://github.com/react-native-community/react-native-cameraroll).

**Comment by scarlac** [comment]
@bartolkaruza After upgrading to 0.59.1 I just discovered that CameraRoll no longer works. No errors, no warning. There are no mentions in change logs and no mentions of breaking changes planned or deprecations for CameraRoll. Am I correct in understanding that CameraRoll is no longer going to be maintained within the RN codebase and we should use the community version from v0.59 and forward?

**Comment by airlaser** [comment]
On top of that, it seems that `Image` still does not work with `photos://uuid` URIs given by `PHAsset` and on some models of phone `assets-library://uuid` URIs have stopped working.

**Comment by bartolkaruza** [comment]
> @bartolkaruza After upgrading to 0.59.1 I just discovered that CameraRoll no longer works. No errors, no warning. There are no mentions in change logs and no mentions of breaking changes planned or deprecations for CameraRoll. Am I correct in understanding that CameraRoll is no longer going to be maintained within the RN codebase and we should use the community version from v0.59 and forward?

The deprecation is taking place from 0.60 forward. The issues you are facing are related to recent changes in RN core, but the fixes should be made to the RNC repo, as that is the 'official' CameraRoll going forward.

I see you have already picked up on that here https://github.com/react-native-community/react-native-cameraroll/issues/18, so I'm just posting this for anyone coming through here from search.

**Comment by bartolkaruza** [comment]
> On top of that, it seems that Image still does not work with photos://uuid URIs given by PHAsset and on some models of phone assets-library://uuid URIs have stopped working.

@airlaser Can you post these as separate issues please? No-one is tracking this closed issue.
