### ISSUE TITLE
Problem WebView - Cookie not working with Payment Geteway.

### ISSUE THREAD

**Issue by abdelhakimkotti** [facebook/react-native#20470]
- [ ] Review the documentation: https://facebook.github.io/react-native
  - [ ] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment

React Native Environment Info:
System:
OS: macOS High Sierra
CPU: 2,53 GHz Intel Core i5
Memory: 8 Go 1067 MHz DDR3 
IDEs:
Android Studio: Version 3.0
Xcode: Version 9.2

## Description
Am implementing  party payment gateway in a webview And when the user got redirected to the result page, i got a message saying that "cookies are not enabled in the browser ". 
To access the payment pages you need to have enabled cookie.

## Code
         <WebView 
              source={{ uri: this.state.url }}
              scalesPageToFit={true} 
              javaScriptEnabled={true}
              thirdPartyCookiesEnabled={true} 
              onNavigationStateChange={this.onNavigationStateChange} 
         />

## Reproducible Demo
For  iOS:
https://developer.apple.com/documentation/foundation/nshttpcookiestorage/1418390-cookies?language=objc

For Android:
https://developer.android.com/reference/java/net/CookieStore

**Comment by jamonholmgren** [comment]
Migrated to https://github.com/react-native-community/react-native-webview/issues/25 and can be closed here.

**Comment by Johncy1997** [comment]
I am trying to display the payment integration webview on react-native-webview. Still, i see *session has ended.Please click pay button to sign in again*. Is there any other option for this?
