### ISSUE TITLE
Set page not working 

### ISSUE THREAD

**Issue by yeomann** [facebook/react-native#20475]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
      Memory: 1.46 GB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 9.11.1 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.2.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 25.0.2, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.0
        API Levels: 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.4.1 => 16.4.1
      react-native: ^0.56.0-rc.5 => 0.56.0
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

## Description
setPage on `ViewPagerAndroid ` not working. upon click it does nothing. 

## Reproducible Demo

```
<View>
    <Button
        onPress={() =>
            this.setState({
                index: 2
            })
        }
        title="click"
    />
    <Text>{this.state.index}</Text>
</View>
<ViewPagerAndroid
    style={styles.viewPager}
    initialPage={0}
    setPage={this.state.index}
    scrollEnabled
>
    <View style={styles.pageStyle} key="1">
        <Text>First page</Text>
    </View>
    <View style={styles.pageStyle} key="2">
        <Text>Second page</Text>
    </View>
    <View style={styles.pageStyle} key="3">
        <Text>3 page</Text>
    </View>
    <View style={styles.pageStyle} key="4">
        <Text>4 page</Text>
    </View>
</ViewPagerAndroid>
```

**Comment by karanjthakkar** [comment]
@yeomann Based on some googling, this is how `setPage` needs to be used:

```
<View>
    <Button
        onPress={() =>
            this.pager.setPage(2);
        }
        title="click"
    />
    <Text>{this.state.index}</Text>
</View>
<ViewPagerAndroid
    style={styles.viewPager}
    initialPage={0}
    ref={c => { this.pager = c; }}
    scrollEnabled
>
    <View style={styles.pageStyle} key="1">
        <Text>First page</Text>
    </View>
    <View style={styles.pageStyle} key="2">
        <Text>Second page</Text>
    </View>
    <View style={styles.pageStyle} key="3">
        <Text>3 page</Text>
    </View>
    <View style={styles.pageStyle} key="4">
        <Text>4 page</Text>
    </View>
</ViewPagerAndroid>
```

setPage isn't a callback that RN calls for you. It is a method that YOU call to let RN know that you want to animate to that page. Let me know if that helps 🙂
