### ISSUE TITLE
Utilize xcworkspace in addition to Podfile for Cocoapods detection

### ISSUE THREAD

**Issue by dcramer** [facebook/react-native#20486]
## Environment

```
  OS: macOS High Sierra 10.13.4
  Node: 8.11.3
  Yarn: 1.9.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: ~0.55.2 => 0.55.4
```

## Description

Let me preface this with: I have no idea what I'm doing. Hadn't touched RN before earlier this week.

I had a Podfile present in my path (I was intending to use it in the future), and RN's linker seems to utilize that to detect if we're using Cocoapods or not.

This caused errors such as the following from ``react-native-sentry``:

```
/Users/redacted/Development/redacted/ios/redacted/AppDelegate.m:15:9: fatal error: ‘RNSentry.h’ file not found
#import “RNSentry.h” // This is used for versions of react < 0.40
```

I ultimately discovered that it had modified the Podfile and was expecting the dependencies to be linked from Cocoapods. After doing unlink on the modules, renaming the Podfile, and re-linking them, my project was able to successfully compile.

**Comment by hramos** [comment]
Removing old version label as this is unlikely to have been fixed in 0.56.
