### ISSUE TITLE
main.jsbundle does not exist

### ISSUE THREAD

**Issue by jiajun1203** [facebook/react-native#20481]
+ [[ ! -f /Users/goboo/Library/Developer/Xcode/DerivedData/Manager-cpzuvbhlfohmqodpxdwxwkotutfc/Build/Intermediates.noindex/ArchiveIntermediates/Manager/BuildProductsPath/Release-iphoneos/Manager.app/main.jsbundle ]]

+ echo 'error: File /Users/goboo/Library/Developer/Xcode/DerivedData/Manager-cpzuvbhlfohmqodpxdwxwkotutfc/Build/Intermediates.noindex/ArchiveIntermediates/Manager/BuildProductsPath/Release-iphoneos/Manager.app/main.jsbundle does not exist. This must be a bug with'

error: File /Users/goboo/Library/Developer/Xcode/DerivedData/Manager-cpzuvbhlfohmqodpxdwxwkotutfc/Build/Intermediates.noindex/ArchiveIntermediates/Manager/BuildProductsPath/Release-iphoneos/Manager.app/main.jsbundle does not exist. This must be a bug with

+ echo 'React Native, please report it here: https://github.com/facebook/react-native/issues'
React Native, please report it here: https://github.com/facebook/react-native/issues

+ exit 2

**Comment by Nitingadhiya** [comment]
How to solve your problem , please give me solution.

**Comment by Kikketer** [comment]
Indeed, you are not alone.  Please inform us of what you did to solve the issue.

**Comment by benjarwar** [comment]
Installing `watchman` with `brew` worked for us when we encountered this issue on CircleCI using their Xcode 10 executor. See https://stackoverflow.com/a/54464135/1489537
