### ISSUE TITLE
Can't start packager while building RN android from source

### ISSUE THREAD

**Issue by brunobar79** [facebook/react-native#20493]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
I can't run react-native info because it fails with the same error. However this is my the output for when I don't try to build from source:

```
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
      Memory: 291.82 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 9.9.0 - ~/.nvm/versions/node/v9.9.0/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.1.0 - ~/.nvm/versions/node/v9.9.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 23.0.3, 25.0.0, 25.0.1, 26.0.1, 26.0.2, 26.0.3, 27.0.3
        API Levels: 23, 25, 26, 27
    IDEs:
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1
      react-native: 0.56.0 => 0.56.0
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
```

## Description
I'm not able to run my app if I build from source (using master as of now) because I can't launch the packager.  It exits with the following error: 

`(node:26449) UnhandledPromiseRejectionWarning: Error: Could not find configuration for metro, did you create a 'metro.config.js'?`

<img width="808" alt="screen shot 2018-08-01 at 12 08 40 pm" src="https://user-images.githubusercontent.com/1247834/43533807-bb0d1e20-9583-11e8-876d-3c923895a654.png">

I have a strong feeling that this is related to #20458 since I've checked out a commit from 8 days ago (201ba8c69d2defc284a04acadcd13df001028ada) and the packager works fine.

## Reproducible Demo

Create a new app with react-native init, then follow the instructions for [Building React Native from source](https://facebook.github.io/react-native/docs/building-from-source) and then try to start the packager by running npm start (as the docs says)

Pinging  @CompuIves @rafeca  since you guys worked / reviewed the metro config change.

**Comment by hramos** [comment]
Agree, this appears to be covered by the CI failure described in #20458.
