### ISSUE TITLE
TextInput dictation mode bugged on iOS

### ISSUE THREAD

**Issue by clems36** [facebook/react-native#20499]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ ] Use the latest React Native release: https://github.com/facebook/react-native/releases
I'm using 0.55.4 but checked the Change Log for dictation changes and found nothing.

## Environment

 OS: Windows 10
  Node: 8.1.2
  Yarn: 1.2.1
  npm: 6.1.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  2.3.0.0 AI-162.4069837

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz => 0.55.4

## Description

Using dictation mode on a TextInput in iOS works partially. It only writes 1 word down then the dictation ends. Everything works as expected on Android.
I've tried the solutions mentioned in https://github.com/facebook/react-native/issues/18890 without success.

**Comment by raymondchooi** [comment]
Possibly related to https://github.com/facebook/react-native/issues/18890 and the possible PR for it here: https://github.com/facebook/react-native/pull/19687

**Comment by clems36** [comment]
Fixed
