### ISSUE TITLE
Error: Cannot read property 'pbxprojPath' of null

### ISSUE THREAD

**Issue by khat33b** [facebook/react-native#20506]
Result of `react-native info`:

```
  React Native Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
      CPU: x64 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
      Memory: 634.73 MB / 7.53 GB
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 8.11.3 - /usr/bin/node
      Yarn: 1.9.2 - /usr/bin/yarn
      npm: 6.3.0 - /usr/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    npmPackages:
      react: 16.3.1 => 16.3.1 
      react-native: ^0.56.0 => 0.56.0 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
```

When I try to run `react-native install react-native-vector-icons`, I get the error: 

```
Scanning folders for symlinks in /home/tivintis/react-native/Docurama/node_modules (15ms)
rnpm-install info Linking assets to ios project 
rnpm-install ERR! Something went wrong while linking. Error: Cannot read property 'pbxprojPath' of null 
Please file an issue here: https://github.com/facebook/react-native/issues
```

**Comment by gitjps** [comment]
I got the same error when I ran react-native link as advised on https://docs.nativebase.io/docs/GetStarted.html

MacBook-Pro-3:my-new-expo-image-project jps$ react-native link
Scanning folders for symlinks in /Users/jps/Projects/my-new-expo-image-project/node_modules (10ms)
rnpm-install info Linking assets to ios project 
rnpm-install ERR! Something went wrong while linking. Error: Cannot read property 'pbxprojPath' of null

**Comment by ng-darren** [comment]
Maybe you can try `react-native upgrade`

[https://github.com/facebook/react-native/issues/20035](url)

**Comment by shrijan** [comment]
react-native upgrade wont fix the issue

**Comment by kessler9** [comment]
Same issue here.  No react-native upgrade doesn't work.

**Comment by tomjdickson** [comment]
Likewise, react-native upgrade didn't work.
I have also performed the following:

- Deleted Node_modules
- Deleted all .lock files
- ran npm install

"react-native link" still not working

**Comment by robertalv** [comment]
npm update then react-native link worked for me.
