### ISSUE TITLE
Overriding previous layout animation with new one before the first began 

### ISSUE THREAD

**Issue by nikolas7892** [facebook/react-native#20511]
I'm using Layout Animations to produce high quality animations. I need to toggle it on and off. In order to do that, I run the command `LayoutAnimation.configureNext(null)` on the unmount which all works. The only problem is i get a plethora of warnings which is very frustrating. 

How can I fix this huge propagation of warnings while also switching Layout Animations on and off? And I am not interested in ignoring it.

**Comment by francisdelgad** [comment]
I'm also having the same issue.

**Comment by VicFrolov** [comment]
Experiencing same issue.
