### ISSUE TITLE
Circular dependency between the following tasks: :app:bundleReleaseJsAndAssets \--- :app:recordFilesBeforeBundleCommandRelease

### ISSUE THREAD

**Issue by noellaby** [facebook/react-native#20525]
Hello
After I add plugin code Push, i have this error ( https://scans.gradle.com/s/u65liapjhvcyo/console-log )
```
  STACK TRACE AND/OR SCREENSHOTS
```
https://scans.gradle.com/s/u65liapjhvcyo/console-log

### Environment
Environment:
  OS: Windows 10
  Node: 8.11.1
  Yarn: 1.6.0
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.0.0.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

* react-native-code-push version: 5.4
* react-native version: 0.55.4
Gradle Version : 3.1.3

Please how to do to pass ?

Thanks

**Comment by noellaby** [comment]
@ConnorJWilliams Help me

**Comment by noellaby** [comment]
i add org.gradle.configureondemand=true in file gradle.properties , I resolve my problem. I do not know how to create another problem or not, but if a person has a better proposal I am interested.
Thank you

**Comment by noellaby** [comment]
@react-native-bot i update with information Environnement

**Comment by noellaby** [comment]
@noellaby this solution add org.gradle.configureondemand=true is file gradle.properties , impossible your run command react-natibe run-android ,  the server window closes after the build , impossible to work in mode  development

**Comment by noellaby** [comment]
i resolve this problem : 
 remove line runBefore("bundle${targetName}JsAndAssets", recordFilesBeforeBundleCommand) in file codePush.gradle

**Comment by kelset** [comment]
I suggest you open an issue in the codepush repository, since it seems that what you are reporting is related to that library.
