### ISSUE TITLE
WebView's source prop should not require whitelist for static HTML.

### ISSUE THREAD

**Issue by squirly** [facebook/react-native#20527]
## Description
Due to how HTML is opened in iOS, it seems that using `source` as `{html: string}` no longer works, without white-listing `about:blank`.

This is a possible regression/side effect of https://github.com/facebook/react-native/commit/634e7e11e3ad39e0b13bf20cc7722c0cfd3c3e28.
> iOS only: Breaking Change: Restrict WebView to only http(s) URLs
>
> Summary:
> To prevent people from linking file:// or other URLs inside RN WebViews, default <WebView> to not allowing those types of URLs.
> This adds the originWhitelist to specify other schemes or domains to be allowed.

## Solutions
There are two potential solutions:
1. Add `about:blank` to the whiltelist.
1. Do not enforce the whitelist when loading `about:blank` for a static HTML source, passed through props.

If (1) is chosen I, @squirly, can write a fix for this.

## Environment
```
  React Native Environment Info:
    System:
      OS: Linux 4.13 Ubuntu 16.04.5 LTS (Xenial Xerus)
      CPU: x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
      Memory: 586.73 MB / 15.55 GB
      Shell: 4.3.48 - /bin/bash
    Binaries:
      Node: 8.11.3 - ~/bin/node
      npm: 6.2.0 - ~/bin/npm
    SDKs:
      Android SDK:
        Build Tools: 23.0.1, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 27.0.3
        API Levels: 23, 25, 26, 27
    npmPackages:
      react: 16.4.2 => 16.4.2 
      react-native: 0.56.0 => 0.56.0
```

## Reproducible Demo
Remove the line below and run tests.
https://github.com/facebook/react-native/blob/a286c0e75358dd3d917df51189ee306ef00a5e7e/IntegrationTests/WebViewTest.js#L67

### Related Error
```
[warn][tid:com.facebook.react.JavaScript] Possible Unhandled Promise Rejection (id: 0):
Error: Unable to open URL: about:blank
```

<details><summary>Stacktrace</summary>

```
createErrorFromErrorData@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:2268:26
__invokeCallback@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:2656:23
__guard@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:2559:15
invokeCallbackAndReturnFlushedQueue@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:2406:21
invokeCallbackAndReturnFlushedQueue@[native code]
```

</details>

**Comment by squirly** [comment]
@react-native-bot This should be tagged iOS, and the Linux tag should be removed.

**Comment by jamonholmgren** [comment]
Migrated to https://github.com/react-native-community/react-native-webview/issues/26 and can be closed here.
