### ISSUE TITLE
[ScrollView] Why the top of ScrollView has more than 20 pixels

### ISSUE THREAD

**Issue by cssoul** [facebook/react-native#2052]
![ScrollView Bug](http://s17.mogucdn.com/p1/150720/upload_ie2tinjvmiytcmjygizdambqhayde_374x487.jpg "Watch here")

**Comment by cssoul** [comment]
Code:

<ScrollView
        ref='scrollWrap'
        stickyHeaderIndices={[3]}
        style={styles.scrollView}>
    <Banner data={jsonData.banner} />
    .......
</ScrollView>

**Comment by cssoul** [comment]
I use this code to solve this problems
contentContainerStyle={{marginTop:-20}} 

... ...

**Comment by Nirvana-icy** [comment]
I meet the same issue.It's ok in 0.6.0.So what's the change in 0.8.0 to cause this issue?

**Comment by keyhui-heha** [comment]
To my case, this issue is found since 0.7.1

**Comment by grabbou** [comment]
That's duplicate of https://github.com/facebook/react-native/issues/1779#issuecomment-122330031

**Comment by MossP** [comment]
We should close this one and just keep the existing one live. @brentvatne close duplicate

**Comment by brentvatne** [comment]
@MossP - thanks for pointing that out. I closed the other because it seems like that works for ListView now with the props that @grabbou suggested, but I personally was not able to fix this issue using those props on a ScrollView, so I'll keep this one open

**Comment by grabbou** [comment]
This is getting more and more interesting, esp. as these props are as far as I know passed to ScrollView anyway? :D

**Comment by jaygarcia** [comment]
I've been able to solve this issue by turning off translucency and wrapping the list view itself. 

See https://github.com/facebook/react-native/issues/2151#issuecomment-128159054

**Comment by christopherdro** [comment]
@ide @brentvatne Issue can be closed.
