### ISSUE TITLE
[SoftJSException]  Strange symbol   ..l[e]()..

### ISSUE THREAD

**Issue by Nirvana-icy** [facebook/react-native#2053]
"SoftJSException":"undefined is not a function (evaluating 'l`[e`]()')",

l[e]() this is so strange.I can not get any clue to solve this issue..And this issue is not happen 100%.

I got the log from 2% user. I want to know how to find some clue to solve this issue?

Thank you.

**Comment by MossP** [comment]
Do you have any code to support this illustrating where it might be happening? You haven;t included much information.

**Comment by brentvatne** [comment]
Hi @Nirvana-icy! Agreed with @MossP above, this is a bit hard to trace. That said, it looks like this is some code on your end that is throwing an exception that is running through here: https://github.com/facebook/react-native/blob/0.8-stable/React/Modules/RCTExceptionsManager.m#L39-L48

@sahrens it looks like there is a lingering TODO in there, perhaps not relevant to OSS

**Comment by Nirvana-icy** [comment]
@brentvatne Thank you.I got the clue in the jsBundle which is compressed.As the log from user is match with the compressed js file.So it made a little difficult to debug.
Do we have bettter ways to debug in this situation?
Finally thank you all for the support.

**Comment by brentvatne** [comment]
@Nirvana-icy - we definitely need some better tracing here, being discussed in #2040
