### ISSUE TITLE
ScrollView's KeyboardDismissMode= 'on-drag' doesn't work with KeyboardAvoidingView

### ISSUE THREAD

**Issue by KeegsMcGeegs** [facebook/react-native#20540]
## Environment
Environment:
  OS: Windows 10
  Node: 10.0.0
  Yarn: 1.6.0
  npm: 6.0.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.1.0.0 AI-173.4720617

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

## Description
When Using KeyboardAvoidngView with ScrollView's `keyboardDismissMode= 'on-drag'`, the keyboard gets dismissed when clicking on an input field at the bottom of the screen. When clicking on the last input field within the ScrollView, the keyboard can't even be accessed because the View moving out of the way of the keyboard is being considered a drag.

## Reproducible Demo
```
<KeyboardAvoidingView style={styles.container} enabled>
  <ScrollView
    style={{flex: 1}}
    keyboardShouldPersistTaps= 'handled'
    keyboardDismissMode= 'on-drag'
  >
    <TextInput
      style={{height: 40, borderColor: 'gray', borderWidth: 1}}
      onChangeText={(text) => this.setState({text})}
      value={this.state.text}
    />
    //About 10 more TextInputs
  </ScrollView>
</KeyboardAvoidingView>

```

**Comment by icastillejogomez** [comment]
This is still an issue. React native 0.56.1

**Comment by shyaniv7** [comment]
work around

```js
    const keyboardDismissProp = Platform.OS === "ios" ? { keyboardDismissMode: "on-drag" } : { onScrollEndDrag: Keyboard.dismiss };

```

**Comment by hakkikonu** [comment]
Still an issue. IOS working well but on Android it is not working!

react-native: 0.58.4
