### ISSUE TITLE
 Invariant Violation Text strings must be rendered within a <Text> component

### ISSUE THREAD

**Issue by zenger7** [facebook/react-native#20543]
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.9.4 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.1.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
 
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.4.2 => 16.4.2 
      react-native: ^0.56.0 => 0.56.0 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      react-native-rename: 2.2.2 

Invariant Violation: Text strings must be rendered within a <Text> component.

This error is located at:
    in RCTView (at View.js:43)
    in AnimatedComponent (at TouchableOpacity.js:256)
    in TouchableOpacity (at AnimatedSwitch.js:85)
    in RCTView (at View.js:43)
    in AnimatedSwitch (at TypeList.js:100)
    in RCTView (at View.js:43)
    in RCTView (at View.js:43)
    in RCTScrollContentView (at ScrollView.js:955)
    in RCTScrollView (at ScrollView.js:1070)
    in ScrollView (at TypeList.js:93)
    in RCTView (at View.js:43)
    in RCTView (at View.js:43)
 
<img width="311" alt="screen shot 2018-08-06 at 11 13 00 am" src="https://user-images.githubusercontent.com/26716357/43705150-6f832fc2-996a-11e8-999c-2aa8fa4f78fa.png">

The problem came up after I made updates to react and other . In more than one class the problem was not in the previous problems

import React, { Component } from 'react';
import {
  View,
  Text,
  TouchableOpacity,
  TouchableHighlight,
  StyleSheet,
  Keyboard,
  KeyboardAvoidingView,
  ScrollView,
  Button,
  Image,
} from 'react-native';
import { connect } from 'react-redux';
import { bindActionCreators } from 'redux';
import { ActionCreators } from '../redux/actions';
import IconF from 'react-native-vector-icons/FontAwesome';
import Icon from 'react-native-vector-icons/Ionicons';
import FontAwesomeIcon from 'react-native-vector-icons/FontAwesome';
import colors from '../styles/colors';
import { transparentHeaderStyle } from '../styles/navigation';
import InputField from '../components/form/InputField';
import RadioInput from '../components/form/RadioInput';
import RoundedButton from '../components/buttons/RoundedButton';
import Rounded2Button  from '../components/buttons/Rounded2Button';
import Stars from '../components/Stars';
 

export default class ViewBuilding extends Component <{}> {

  static navigationOptions = {
    tabBarVisible: false,
    header: null,
    //headerStyle: styles.headerStyle,
  };

  render() {

    return (
      <View style={styles.wrapper}>

        <View style={styles.headerButton}>

          headerLeft: <TouchableOpacity
            style={styles.closeButton}
            onPress={() =>  this.props.navigation.navigate('ExploreContainer')}
          >
            <IconF
              name="angle-left"
              size={30}
              color={colors.white}
            />
          </TouchableOpacity>,

          headerRight: <TouchableOpacity
            style={styles.closeButton2}
            onPress={() =>  this.props.navigation.navigate('ExploreContainer')}
          >
            <IconF
              name="retweet"
              size={25}
              color={colors.white}
            />
          </TouchableOpacity>,

          headerRight: <TouchableOpacity
            style={styles.closeButton3 }
            onPress={() =>  this.props.navigation.navigate('ExploreContainer')}
          >
            <IconF
              name="heart"
              size={25}
              color={colors.white}
            />
          </TouchableOpacity>,
        </View>

        <ScrollView
        style={styles.scrollView}
        contentContainerStyle={styles.scrollViewContent}
        >

        <View style={styles.content}>
            <Image
            source={require('../data/photos/listing1.png')}
            style={{width: 100 + "%", height: 100 + "%"}} />
         </View>
         <View style={styles.ContentSnter}>

          <View style={styles.Buildingcontent}>
           <Text style={styles.BuildingName}> شاليهات الخليج </Text>
          </View>

           <View style={styles.AmenitiesContent}>
           <View>
           <Icon
             name="md-close"
             size={45}
             color={colors.lightBlack}
           />
           <Text > حجر </Text>
           </View>
           <View>
           <Icon
             name="md-close"
             size={45}
             color={colors.lightBlack}
           />
           <Text > حجر </Text>
           </View>
           <View>
           <Icon
             name="md-close"
             size={45}
             color={colors.lightBlack}
           />
           <Text > حجر </Text>
           </View>
           <View>
           <Icon
             name="md-close"
             size={45}
             color={colors.lightBlack}
           />
           <Text > حجر </Text>
           </View>

            </View>

            <View style={styles.AmenitiesContent}>
            <View>
            <Icon
              name="md-close"
              size={45}
              color={colors.lightBlack}
            />
            <Text > حجر </Text>
            </View>
            <View>
            <Icon
              name="md-close"
              size={45}
              color={colors.lightBlack}
            />
            <Text > حجر </Text>
            </View>
            <View>
            <Icon
              name="md-close"
              size={45}
              color={colors.lightBlack}
            />
            <Text > حجر </Text>
            </View>
            <View>
            <Icon
              name="md-close"
              size={45}
              color={colors.lightBlack}
            />
            <Text > حجر </Text>
            </View>

            </View>

            </View>

            <View style={styles.BuildingMap}>
            <Image
            source={require('../img/map.jpg')}
            style={{width: 100 + "%", height: 100 + "%"}} />
             </View>
             <View style={styles.ContentSnter}>
            <View style={styles.Buildingcontent}>
               <Text style={styles.BuildingMessage}> ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ</Text>
           </View>

           <View style={styles.Buildingcontent}>
             <View style={styles.Buildingcontent2}>
               <Text style={styles.BuildingENamber}> 8.7</Text>
               <Text style={styles.BuildingEvaluation}>  تقييم  </Text>

             </View>
          </View>

          <View style={styles.Buildingcontent}>

              <TouchableOpacity style={styles.linkButton}
               onPress={() => this.props.navigation.navigate('LoggedOut')}
              >
             <View style={{ flex: 1, flexDirection: 'row' ,  justifyContent: 'space-between'}}>
             <IconF style={styles.IconStylx} name="angle-left" color={colors.gray04} size={30}    />
             <Text style={styles.TButton}> شروط الإستخدام </Text>
             </View>
             </TouchableOpacity>

             <TouchableOpacity style={styles.linkButton}
              onPress={() => this.props.navigation.navigate('LoggedOut')}
             >
            <View style={{ flex: 1, flexDirection: 'row' ,  justifyContent: 'space-between'}}>
            <IconF style={styles.IconStylx} name="angle-left" color={colors.gray04} size={30}    />
            <Text style={styles.TButton}> شروط الإلغاء </Text>
            </View>
            </TouchableOpacity>

            <TouchableOpacity style={styles.linkButton}
             onPress={() => this.props.navigation.navigate('LoggedOut')}
            >
           <View style={{ flex: 1, flexDirection: 'row' ,  justifyContent: 'space-between'}}>
           <IconF style={styles.IconStylx} name="angle-left" color={colors.gray04} size={30}    />
           <Text style={styles.TButton}> تواصل مع المالك </Text>
           </View>
           </TouchableOpacity>

           <TouchableOpacity style={styles.linkButton}
            onPress={() => this.props.navigation.navigate('LoggedOut')}
           >
          <View style={{ flex: 1, flexDirection: 'row' ,  justifyContent: 'space-between'}}>
          <IconF style={styles.IconStylx} name="angle-left" color={colors.gray04} size={30}    />
          <Text style={styles.TButton}> شكاوي </Text>
          </View>
          </TouchableOpacity>

           <TouchableOpacity
            onPress={() => this.props.navigation.navigate('LoggedOut')}
           >
          <View style={{ flex: 1, flexDirection: 'row' ,  justifyContent: 'space-between'}}>
          <IconF style={styles.IconStylx} name="angle-left" color={colors.gray04} size={30}    />
          <Text style={styles.TButton}> تقويم </Text>
          </View>
          </TouchableOpacity>
          </View>

          </View>

        </ScrollView>
        <View style={styles.BookingButton}  >
          <Rounded2Button
            text=" حجز "
            textColor={colors.white}
            background={colors.tomato}
            borderColor="transparent"
          />
        <View  style={styles.BookingView} >
            <Text style={styles.BButton}> 890 ريال </Text>
              <Stars
                votes={2}
                size={15}
                color={colors.green02}
              />
          </View>
        </View>

      </View>

    );
  }

};

    const styles = StyleSheet.create({
       wrapper: {
        backgroundColor: colors.white,
        position: 'absolute',
        left: 0,
        right: 0,
        top: 0,
        bottom: 0,
      //  paddingLeft: 25,
      //  paddingRight: 25,
      },

      headerStyle: {
        //backgroundColor: colors.white,
        borderBottomWidth: 0,

      },
      headerButton:{
        zIndex: 99,
        width: 400,
        backgroundColor: 'rgba(255,10,10,1)',
      },
      closeButton: {
       position: 'absolute',
        left: 20,
        marginTop: 20,
        marginLeft: 20,
        // zIndex: 99,
      },
      closeButton2: {
       position: 'absolute',
        right: 20,
        marginTop: 20,
        marginRight: 20,
        // zIndex: 99,
      },
      closeButton3: {
       position: 'absolute',
        right: 20,
        marginTop: 20,
        marginRight: 70,
        // zIndex: 99,
      },

       content: {
         flex: 1,
      //  paddingTop: 5,
        height: 350,
        width: 400,

      },
      image: {
        width: undefined,
        flex: 1,
        height: 200,
        borderRadius: 8,
        marginBottom: 7
      },
      BookingButton:{
        position: 'absolute',
        bottom: 0,
        right: 0,
        //width: 110,
        backgroundColor: colors.gray07,
        width: 100 + "%",

      },
      BookingView:{
        position: 'absolute',
      //  flexDirection: 'column',
        justifyContent: 'space-evenly',
       marginBottom: 30,
        marginLeft: 25,
      },
      Buttonstyle:{
        padding: 20,
        borderRadius: 10,
        shadowColor: 'rgba(0,0,0,.25)',
        backgroundColor: colors.pink,
        borderBottomColor: colors.gray08,
        shadowOpacity: 0.7,

      },
      Buildingcontent:{
        borderBottomWidth: 1,
        padding: 5,
        marginBottom: 5,
        shadowColor: 'rgba(0,0,0,.25)',
        borderBottomColor: colors.gray08,
        textAlign: 'right',
      //  paddingLeft: 25,
      //  paddingRight: 25,
        //right: 25,
        //left: 25,
      },
      Buildingcontent2:{
        borderBottomColor: colors.gray08,
        textAlign: 'right',
        flexDirection: 'row',
        alignSelf: 'flex-end',
      },
      BuildingMap:{
        borderBottomWidth: 1,
        //padding: 5,
        //marginBottom: 5,
        shadowColor: 'rgba(0,0,0,.25)',
        borderBottomColor: colors.gray08,
        textAlign: 'right',
        //paddingTop: 5,
        height: 300,
        width: 400,
      },
      AmenitiesContent:{
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'space-between',
        borderBottomWidth: 1,
        //marginBottom: 5,
        padding: 15,
        shadowColor: 'rgba(0,0,0,.25)',
        borderBottomColor: colors.gray08,
        textAlign: 'right',
      },

      BuildingName: {
        fontSize: 30,
        color: colors.gray04,
        fontFamily: 'Geeza Pro',
        fontWeight: '300',
        marginBottom: 30,
        marginTop: 20,
        fontWeight: 'bold',
        //right: 40,
        textAlign: 'right',
      },
      BuildingMessage: {
        fontSize: 14,
        color: colors.gray04,
        fontFamily: 'Geeza Pro',
        fontWeight: '300',
        marginTop: 20,
        padding: 10,
        marginBottom: 40,
        textAlign: 'right',
      },
      BuildingEvaluation:{
        fontSize: 23,
        color: colors.gray04,
        fontFamily: 'Geeza Pro',
        fontWeight: '300',
        marginTop: 8,
        //  padding: 5,
        marginBottom: 8,
       fontWeight: 'bold',
    //  marginLeft:20,
        //right: 20,
      //  left:10,
        textAlign: 'right',
      },
      BuildingENamber:{
        fontSize: 23,
        color: colors.green01,
        fontFamily: 'Geeza Pro',
        fontWeight: '300',
        marginTop: 8,
        marginRight: 20,
        marginBottom: 8,
       fontWeight: 'bold',
        textAlign: 'right',
      },
      ButtonText: {
        fontSize: 24,
        color: colors.gray04,
        fontWeight: '300',
        fontFamily: 'Geeza Pro',
        fontWeight: 'bold',
        right: 20,
        marginBottom: 1,
        marginTop: 1,
        textAlign: 'right',
      },
      scrollViewContent: {
        paddingBottom: 80,
      },
      scrollView: {
        marginTop: 0,
        flex: 1,
        padding: 0,
        position: 'absolute',
        left: 0,
        right: 0,
        top: 0,
        bottom: 0,

      },

      ContentSnter:{
        paddingLeft: 25,
        paddingRight: 25,
     },
      IconStylx:{
        padding: 5,
        marginTop: 5,
      },
      TButton: {
        color: colors.gray09,
        fontSize: 17,
        //  backgroundColor: 'rgb(94,255,96)',
        fontFamily: 'Geeza Pro',
        fontWeight: '300',
        textAlign: 'right',
        paddingTop: 5,
        marginBottom: 25,
        marginTop: 10,
      },
      BButton: {
        color: colors.gray09,
        fontSize: 17,
        //  backgroundColor: 'rgb(94,255,96)',
        fontFamily: 'Geeza Pro',
        fontWeight: '300',
    //    textAlign: 'right',
        marginBottom: 5,
        marginTop: 15,
      },
      linkButton: {
    //backgroundColor: colors.green01,
        borderBottomWidth: 1,
      //  marginLeft: 5,
        marginBottom: 5,
        shadowColor: 'rgba(0,0,0,.25)',
        borderBottomColor: colors.gray08,
        textAlign: 'right',
      },

      });

**Comment by rafauke** [comment]
@zenger7 Are you sure that all the text in your component is wrapped with `<Text />`?  Maybe you have a comma somewhere that is not wrapped (pretty common):

```js
<MyComponent>
  <View>
    <Text>Hey there</Text>,  // <---- this thingy
  </View>
</MyComponent>
```

**Comment by karanjthakkar** [comment]
Can you show us the `TypeList` component implementation to figure out where the issue could be coming from?

**Comment by karanjthakkar** [comment]
That looks like a pretty big component. Without all the pieces and fiddling it myself, I can't help much. The only thing I can recommend is to comment out pieces of the code to figure out which part is causing this issue.

**Comment by dblock** [comment]
Mine looked like this:

```
        <TouchableOpacity onPress={() => 
          this.props.navigation.navigate('Meeting', { 
            meeting: this.props.meeting,
            user: this.props.user
          })}>
        }>
          <Text style={styles.meetingTitle}>{
            this.props.meeting.title
          }</Text>
        </TouchableOpacity>
```

Moving the function call fixed it? 

```
  _navigate() {
    this.props.navigation.navigate('Meeting', { 
      meeting: this.props.meeting,
      user: this.props.user
    })      
  }
```

```
        <TouchableOpacity onPress={() => this._navigate()}>
          <Text style={styles.meetingTitle}>{
            this.props.meeting.title
          }</Text>
```

Go figure. Looks like a bug to me still but hope this helps someone.

**Comment by China-Robin** [comment]
@dblock Thank you. You saved me

**Comment by jesus143** [comment]
Hi Everyone, I am also experiencing this issue now and it's from package  "@expo/videoplayer": "^0.4.0" with this specific component <VideoPlayer />

Anyone could help would much very be appreciated.


Thanks,
Jesus

**Comment by itolimaesther** [comment]
am having similar issues.  Please can someone help

import React, { Component } from 'react'

import {
    View,
    Text,
    StyleSheet,
    TouchableOpacity,
    TouchableHighlight,
    TouchableWithoutFeedback,
    Image
} from 'react-native'

import InfoImage from 'images/info.png'

export default class ResturantRow extends Component {

    state ={
        showInfo: false
    }

    infoPressed = () => {
      this.setState({ showInfo: !this.state.showInfo })  
    }

    render() {

        const {
            place,
            index
        } = this.props

        return (
            <View
            key={place.name}
            style={{backgroundColor: index % 2 === 0 ? 'white' : '#F3F3F7' }}>
            
            <View style={styles.row}>
                <View style={styles.edges}>
                    <Text>{index + 1}</Text>
                </View>

                <View style={styles.nameAddress}>
                    <Text>{place.name}</Text>
                    <Text style={styles.addressText}>{place.address}</Text>
                </View>

                <View style={styles.edges}>
                <TouchableHighlight
                    onPress={this.infoPressed}
                    style={styles.button}
                    underlayColor='#539BDC'
                >
                    <Text style={styles.buttonText}>Info</Text>
                </TouchableHighlight>
                </View>
            </View>

            {
                this.state.showInfo &&
                <View style={styles.info}>
                    <Text>Restaurant Info</Text>
                    <Image source={InfoImage} 
                    style={{
                        flex: 1,
                         height: 100
                     }}/>
                    resizeMode="contain"
                </View>
            }

          </View>
        )
    }
}

const styles = StyleSheet.create({
    row: {
        flexDirection: 'row',
      },
      edges: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        padding: 5,
        minWidth: 50
      },
      nameAddress: {
        flexDirection: 'column',
        flex: 8
      },
      addressText: {
        color: 'grey',
      },
      button: {
        borderWidth: 1,
        borderColor: '#0066CC',
        borderRadius: 14,
        paddingHorizontal: 10,
        paddingVertical: 3,
        backgroundColor: '#fff',
        color: '#912B04',
        fontSize: 12
     },
     buttonText: {
        color: '#0066CC',
        fontSize: 12
    },
    info: {
        marginHorizontal: 40,
        marginVertical: 10,
        padding: 10,
        backgroundColor: '#fff',
        borderWidth: 1,
        borderColor: '#ddd',
        borderRadius: 4
    }
})

**Comment by itolimaesther** [comment]
![Screenshot from 2019-05-20 11-17-48](https://user-images.githubusercontent.com/18469407/58014697-55668580-7af1-11e9-9634-6c7a04cd4f61.png)

**Comment by jdarrohn** [comment]
Getting this randomly too -- reviewed code history in the repository and this file has not changed. 🤔

**Comment by thamiresfm** [comment]
> estou tendo problemas semelhantes. Por favor alguém pode ajudar
> 
> import React, {Component} from 'react'
> 
> import { 
> Visualização, 
> texto, 
> StyleSheet, 
> TouchableOpacity, 
> TouchableHighlight, 
> TouchableWithoutFeedback, 
> Image 
> } de 'react-native'
> 
> import InfoImage de 'images / info.png'
> 
> classe padrão de exportação ResturantRow estende o componente {
> 
> ```
> state ={
>     showInfo: false
> }
> 
> infoPressed = () => {
>   this.setState({ showInfo: !this.state.showInfo })  
> }
> 
> render() {
> 
>     const {
>         place,
>         index
>     } = this.props
> 
>     return (
>         <View
>         key={place.name}
>         style={{backgroundColor: index % 2 === 0 ? 'white' : '#F3F3F7' }}>
>         
>         <View style={styles.row}>
>             <View style={styles.edges}>
>                 <Text>{index + 1}</Text>
>             </View>
> 
>             <View style={styles.nameAddress}>
>                 <Text>{place.name}</Text>
>                 <Text style={styles.addressText}>{place.address}</Text>
>             </View>
> 
>             <View style={styles.edges}>
>             <TouchableHighlight
>                 onPress={this.infoPressed}
>                 style={styles.button}
>                 underlayColor='#539BDC'
>             >
>                 <Text style={styles.buttonText}>Info</Text>
>             </TouchableHighlight>
>             </View>
>         </View>
> 
>         {
>             this.state.showInfo &&
>             <View style={styles.info}>
>                 <Text>Restaurant Info</Text>
>                 <Image source={InfoImage} 
>                 style={{
>                     flex: 1,
>                      height: 100
>                  }}/>
>                 resizeMode="contain"
>             </View>
>         }
> 
>       </View>
>     )
> }
> ```
> 
> }
> 
> const estilos = StyleSheet.create ({ 
> row: { 
> flexDirection: 'row', 
> }, 
> arestas: { 
> flex: 1, 
> alignItems: 'center', 
> justifyContent: 'center', 
> preenchimento: 5, 
> minWidth: 50 
> }, 
> nameAddress: { 
> flexDirection: 'column', 
> flex: 8 
> }, 
> addressText: { 
> cor: 'gray', 
> }, 
> botão: { 
> borderWidth: 1, 
> borderColor: '# 0066CC', 
> borderRadius: 14, 
> preenchimentoHorizontal: 10, 
> paddingVertical: 3, 
> backgroundColor: '#fff', 
> cor: '# 912B04', 
> fontSize: 12 
> }, 
> buttonText: { 
> color: '# 0066CC ',
> fontSize: 12 
> }, 
> info: { 
> marginHorizontal: 40, 
> marginVertical: 10, 
> preenchimento: 10, 
> backgroundColor: '#fff', 
> borderWidth: 1, 
> borderColor: '#ddd', 
> borderRadius: 4 
> } 
> })
No seu caso a declaração está "texto" e o correto é "Text"
