### ISSUE TITLE
export native ios method to react native

### ISSUE THREAD

**Issue by dverma4u** [facebook/react-native#20556]
I'm bridging native ios to react native for the first time. I'm implementing a calendar which is having a method (in objective c) which returns date tappped by user.

i want to use those dates inside react native for further actions.

i have tried something with RCT_EXPORT_METHOD but this only logs the date to react-native. My current code looks like:

```
RCT_EXPORT_METHOD(dateTapped:(NSDate *)date){

  RCTLogInfo(@"Date in METHOD %@ ", date );

}
```
Someone please tell how can i export these dates to react-native so that i can store them in a state?

**Comment by karanjthakkar** [comment]
@dverma4u You can use one of these two techniques to send data back to RN from Native:

1 - Callbacks: https://facebook.github.io/react-native/docs/next/native-modules-ios.html#callbacks
2 - Promises: https://facebook.github.io/react-native/docs/next/native-modules-ios.html#promises

**Comment by dverma4u** [comment]
@karanjthakkar callbacks and promises can only be invoked only once. but i want to take action everytime i tap a date.

Events can help me, but i'm having some trouble in implementing events. Can you please help me in that?

**Comment by karanjthakkar** [comment]
In that case, you need to create an event emitter. Check these files for the implementation:

1. Bridge: https://github.com/karanjthakkar/RNLazyBundleLoading/blob/master/ios/EventBusBridge.m
2. Invocation from Native: https://github.com/karanjthakkar/RNLazyBundleLoading/blob/master/ios/ReactNativeViewController.m#L31
3. Setup on RN side: https://github.com/karanjthakkar/RNLazyBundleLoading/blob/master/ScreenA.js#L12 https://github.com/karanjthakkar/RNLazyBundleLoading/blob/master/ScreenA.js#L34

**Comment by dverma4u** [comment]
@karanjthakkar my interface looks like this 
`@interface CalendarViewController : RCTViewManager  <TEAContributionGraphDataSource> 
`

how can i use both `RCTViewManager` and `RCTEventEmitter `?

**Comment by karanjthakkar** [comment]
1. You will copy the EventBusBridge as it is to your code.
2. Store the RN bridge instance globally somewhere to be accessible.
3. Then use that bridge instance in your CalendarViewController like this: `BridgeInstance moduleForName:@"EventBusBridge"` to get the event bus native module.
4. Check pt 2 to understand how to invoke the event from Native and pt 3 to see how to read it on RN side.
