### ISSUE TITLE
WebView doesn't support `width: 100%` and `alignSelf: stretch`

### ISSUE THREAD

**Issue by sesm** [facebook/react-native#20551]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Environment:
  OS:  macOS High Sierra 10.13.4
  Node:  8.11.3
  Yarn:  1.7.0
  npm:  5.6.0
  Watchman:  4.9.0
  Xcode:  Xcode 9.2 Build version 9C40b
  Android Studio:  3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.2 => 16.3.2
  react-native: 0.55.4 => 0.55.4

Also reproducible on latest version of react-native on Expo.

## Description
WebView doesn't support `width: 100%` and `alignSelf: stretch`. The only way to horizontally stretch a WebView is to set explicit width.

## Reproducible Demo
https://snack.expo.io/rk8HNfLSQ
In this example  `width: 100%` and `alignSelf: stretch` work perfectly well on View but don't work on WebView.

**Comment by sesm** [comment]
This is what happened to all previous issues: this problem is so easily reproducible, that noone bothered to post `react-native info`. Then the bot put `No Environment Info` label, nobody bothered to look at the issue, then it got closed down due to inactivity.

**Comment by sesm** [comment]
I wonder, how ticket can have `No environment info` and `Old version` at the same time, when version is determined from environment info?

**Comment by hramos** [comment]
Removing both labels, as WebView has intentionally not being updated in recent releases, save for one security-related issue in 0.56. The component is not actively updated, and we are proposing it be removed from the core library. You can follow https://github.com/react-native-community/discussions-and-proposals/pull/3 for updates.

In the meantime, the issue shall remain open as whoever takes over the component will also inherit all open WebView issues.

**Comment by sesm** [comment]
@hramos Thanks for clarification!

**Comment by jamonholmgren** [comment]
Migrated to https://github.com/react-native-community/react-native-webview/issues/27 and can be closed here.
