### ISSUE TITLE
React Native Flux Navigation Discussion.

### ISSUE THREAD

**Issue by piyushchauhan2011** [facebook/react-native#2056]
[React Native Flux Navigation Discussion](http://stackoverflow.com/questions/31511916/react-native-navigator-best-way-to-model-in-a-large-app)

[Repo for Test Code](https://github.com/piyushchauhan2011/react-native-flux-navigation)

Branch: Navigation

react-native version: 0.7.1

![screen shot 2015-07-20 at 6 52 04 pm](https://cloud.githubusercontent.com/assets/693487/8772531/7256189e-2f10-11e5-85a6-5e6a410d0c5e.png)

**Comment by piyushchauhan2011** [comment]
@jsierles

**Comment by jsierles** [comment]
This looks like a fine example combining flux and Navigator, but issues should be used for bug reports or questions. Is there an issue here? Cheers!

**Comment by MossP** [comment]
Agree with @jsierles Issues should be kept for issues.
@brentvatne close

**Comment by brentvatne** [comment]
Thank you so much for looking into this! @piyushchauhan2011 - can you repost this on https://discuss.reactjs.org please? I'd love to chat about it there, I think there is a lot of work that needs to be done in thinking about how we can manage the Navigator routes in a clean way for larger apps, or those with more complicated nested navigation structures.

**Comment by piyushchauhan2011** [comment]
Yep will do :smile: Thanks :+1:

**Comment by piyushchauhan2011** [comment]
@brentvatne https://discuss.reactjs.org/t/react-native-navigator-best-way-to-model-in-a-large-app/888?u=piyushchauhan2011
