### ISSUE TITLE
Cannot use ScrollView inside TouchableOpacity

### ISSUE THREAD

**Issue by pstanton** [facebook/react-native#20575]
## Environment
Environment:
  OS: Windows 10
  Node: 9.0.0
  Yarn: 1.6.0
  npm: 6.1.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.1.0.0 AI-173.4819257

Packages: (wanted => installed)
  react: ^16.3.1 => 16.4.0
  react-native: ^0.55.4 => 0.55.4

## Description
```
      <TouchableOpacity style={styles.container} onPress={()=>{Alert.alert("touched")}}>
        <Text style={styles.paragraph}>Touching here should fire the events for TouchableOpacity.</Text>
        <Button title="If a button inside a touchable still clicks" onPress={ () => {Alert.alert("clicked")}}/>
        <ScrollView>
          <Text style={styles.paragraph}>
            Shouldn't the ScrollView still scroll? Shouldn't the ScrollView still scroll? Shou... (much more)
          </Text>
        </ScrollView>
      </TouchableOpacity>
```

In this scenario, the ScrollView does not receive any events.

It may seem like a pointless snippet, but I have set up my modal component to actually be 2x TouchableOpacity components - the first is my shaded curtain, who's onPress closes the modal (enabling the common "touch outside to close" functionality) and the 2nd sits inside with no event handler which creates the usable portion of the modal. Then inside the modal I have buttons (which work fine), text and the ScrollView in question, which doesn't scroll.

## Reproducible Demo

https://snack.expo.io/HJshe-_SX

**Comment by pstanton** [comment]
no because i can't get my project to build

https://github.com/facebook/react-native/issues/4968

**Comment by vdlindenmark** [comment]
You can't have multiple onPress functions inside each other. I think that the ScrollView has also some TouchEvents so they can't be in each other. But I'm not sure.

**Comment by pstanton** [comment]
@vdlindenmark you can, and it works quite well usually - in that the highest (draw order) touch sensitive component wins - no bubbling essentially. as i tried to describe - my real world use case puts one TouchableOpacity (a) inside another (b), so that pressing outside of the box (a), closes the box (b). How else would you achieve this functionality?

**Comment by pstanton** [comment]
does snack not run the latest version? bots are stupid.

**Comment by dwqs** [comment]
reproduce it at 0.57.7
