### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by masumbillah** [facebook/react-native#20573]
MSs-Mac-mini:tojbhi ms$ sudo react-native run-android
Password:
Scanning folders for symlinks in /Users/ms/dev/apps/tojbhi/node_modules (40ms)
Starting JS server...
Building and installing the app on the device (cd android && ./gradlew installDebug)...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.802 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

**Comment by masumbillah** [comment]
My evn `.bash_profile` 

export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools

**Comment by masumbillah** [comment]
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
      Memory: 20.67 MB / 8.00 GB
      Shell: 3.2.57 - /bin/sh
    Binaries:
      Node: 8.11.1 - /usr/local/bin/node
      Yarn: 1.3.2 - /usr/local/bin/yarn
      npm: 6.0.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 23.0.2, 23.0.3, 27.0.3, 28.0.1
        API Levels: 23, 28
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1

**Comment by masumbillah** [comment]
I can not solved this problem. please any suggestion.

**Comment by shivangi4742** [comment]
Hi Masumbillah ,

I'm getting the same issue. Have you resolved ? if yes then please suggest


Building and installing the app on the device (cd android && gradlew.bat installDebug)...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.578 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

**Comment by masumbillah** [comment]
Yes I solved It @shivangi4742 
Please checked `local.properties` file in your app folder. If this file is not existing then create `local.properties` and add your sdk link
 `sdk.dir=/Users/<yourUserName>/Library/Android/sdk`. 

I faced more error in my app. finally  solved every things. and run my app.

**Comment by shivangi4742** [comment]
@masumbillah ,Thank you so much. i solved that one .

now I'm getting this error. 

Building and installing the app on the device (cd android && gradlew.bat installDebug)...

Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

please suggest , because I'm running this app in windows , and I'm unable to connect the emulator on my laptop.

thanks,
shivangi

**Comment by shivangi4742** [comment]
@masumbillah 
Is it possible to debugging the app on my mobile?

I'm having trouble starting my android emulator. Nothing appears to load. I'm getting Emulator: Process finished with exit code 1.

so please suggest. what should i do?

**Comment by kelset** [comment]
Does look to me that this is a react-native side issue but a local config. Closing unless I get strong evidences and a repro to prove it.
