### ISSUE TITLE
[Hit Detection] Components still receive touches in a container with overflow: 'hidden'

### ISSUE THREAD

**Issue by marcshilling** [facebook/react-native#2057]
Run this playground app: https://rnplay.org/apps/cZz3ug

You'll notice that when you click in the blue area, "hey" is logged to the console. 
Now, uncomment `overflow: 'hidden'` from the container style and reload the app. You'll see the blue TouchableHighlight is now hidden, yet you can still click where it used to be.

I would expect things that are clipped via `overflow: 'hidden'` to not receive touches.

**Comment by marcshilling** [comment]
Ahhh, nevermind. I needed to use the `removeClippedSubviews` prop on the container view and set `overflow: 'hidden'` on the child views.

**Comment by brentvatne** [comment]
Thanks for the follow up @marcshilling :eyeglasses:
