### ISSUE TITLE
WebView in RN 0.56 does not allow geolocation requests on Android with proper app permissions & geolocationEnabled={true} prop

### ISSUE THREAD

**Issue by levi-beers** [facebook/react-native#20570]
- [ x ] Review the documentation: https://facebook.github.io/react-native
  - [ x ] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ x ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.5
      CPU: x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 676.74 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.8.0 - ~/.nvm/versions/node/v10.8.0/bin/node
      Yarn: 1.9.4 - ~/.yarn/bin/yarn
      npm: 6.2.0 - ~/.nvm/versions/node/v10.8.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 23.0.2, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.2, 27.0.3
        API Levels: 23, 25, 26, 27
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 
    npmGlobalPackages:
      create-react-native-app: 1.0.0

## Description
In RN 0.56 WebView fails to pass geolocation results to an https URL that requests it even if you include "geolocationEnabled={true}" prop, you have user approval from PermissionAndroid & you've explicitly set "ACCESS_FINE_LOCATION" permissions in AndroidManifest.xml 

## Reproducible Demo
https://github.com/levi-beers/geowebview
* note: for simplicity in viewing, I did not code the example with Redux so that WebView "waits" until permissions are given. If you launch the app, it asks for location permissions and loads an HTML5 geolocation test that fails. If you "Approve" location permissions, then restart the app you'll be alerted you have location permission but WebView still fails. It seems with or without explicit permissions, geolocation still fails on webview. Or possibly I'm just doing this entirely wrong.

**Comment by levi-beers** [comment]
Hi, just a note for why I didn't check Regression -- I didn't see the [geolocationEnabled prop in 0.55's documentation](https://facebook.github.io/react-native/docs/0.55/webview). Only in 0.56 did I notice [it was an option](https://facebook.github.io/react-native/docs/webview). I was using RN 0.55.4 in my app and tried the geolocationEnabled prop with no success so I upgraded to 0.56 and the issue persisted. Before I submitted the report & just to make sure I wasn't crazy, I reproduced with the repo off a new 0.56 install.

**Comment by jamonholmgren** [comment]
Migrated to https://github.com/react-native-community/react-native-webview/issues/28 and can be closed here.

**Comment by Mubashar639** [comment]
> Task :react-native-geolocation-service:compileDebugJavaWithJavac FAILED
E:\gamica\android2\humApp\node_modules\react-native-geolocation-service\android\src\main\java\com\agontuk\RNFusedLocation\LocationUtils.java:8: error: cannot find symbol
import android.support.v4.app.ActivityCompat;
                             ^
  symbol:   class ActivityCompat
  location: package android.support.v4.app
E:\gamica\android2\humApp\node_modules\react-native-geolocation-service\android\src\main\java\com\agontuk\RNFusedLocation\LocationUtils.java:21: error: cannot find symbol
        return ActivityCompat.checkSelfPermission(context, Manifest.permission.ACCESS_FINE_LOCATION) == PackageManager.PERMISSION_GRANTED ||
               ^

**### **discription : :react-native-geolocation-service work fine. when i include react-native-webview this i find these types of error.please tell how can i resolve it****
