### ISSUE TITLE
[WebView] There is an empty space showing when rendering WebView

### ISSUE THREAD

**Issue by alinz** [facebook/react-native#2060]
It does not happen on 0.6 and below. It only happens if I use 0.7 and above.

Here's a sample code:

```js
'use strict';

var React = require('react-native');

var {
  AppRegistry,
  View,
  WebView,
  Component
} = React;

class CustomWebView extends Component {
  reload() {
    this.refs.internalWebView.reload();
  }
  render() {
    return (
      <WebView ref="internalWebView" {...this.props}/>
    );
  }
}

var Sample1 = React.createClass({
  componentDidMount() {
    this.refs.AWESOME.reload();
  },
  render: function() {
    var url = "http://google.com";
    return (
      <CustomWebView ref="AWESOME" url={url}/>
    );
  }
});

AppRegistry.registerComponent('Sample1', () => Sample1);
```

![screen shot 2015-07-20 at 5 16 04 pm](https://cloud.githubusercontent.com/assets/967050/8787644/5149f33a-2f03-11e5-8805-4e63bc3de94b.png)

**Comment by dsibiski** [comment]
@alinz Do you mean the status bar at the top?

**Comment by alinz** [comment]
@dsibiski Yes!

**Comment by brentvatne** [comment]
Related #2052

**Comment by ide** [comment]
@alinz can you try setting automaticallyAdjustContentInsets={false}?

**Comment by chirag04** [comment]
@ide How about making automaticallyAdjustContentInsets={false} as the default behavior? Not sure if this is already been discussed.

**Comment by alinz** [comment]
@ide Awesome, it works! big thanks.

**Comment by ide** [comment]
@chirag I opened a PR to discuss this but I don't know if it's the best solution especially considering Android. My sense is it that it's a useful prop but currently is too entangled with native code, and instead should optimize for JS chrome components like Navigator.
