### ISSUE TITLE
react-native run-ios --device "xxx" stuck at "installing and launching your app on xxx..."

### ISSUE THREAD

**Issue by beobungbu** [facebook/react-native#20609]
After init Demo folder, i tried to debug on real device but it always stuck at "installing and launching your app on xxx..."
here is some last of terminal : 

>  ** BUILD SUCCEEDED **
> 
> 
> 
> The following commands produced analyzer issues:
> 	Analyze Base/RCTModuleMethod.mm normal arm64
> (1 command with analyzer issues)
> 
> installing and launching your app on xxx...
> 
on the terminal title : 

> Demo ---node /usr/local/bin/react-native run-ios --device xxx > lldb

if uses Xcode for debug so it is running fine.

what happening  to me ?  

Project init by react-native init demo 
Scanning folders for symlinks in /Users/lantranduc/workspace/PropertyFinder/node_modules (20ms)

  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
      Memory: 18.70 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.8.0 - /usr/local/bin/node
      npm: 6.2.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      eslint-plugin-react-native: 3.2.1
      react-native-cli: 2.0.1

**Comment by mariorodriguespt** [comment]
My CI (MS AppCenter) is stuck on this issue, it's far from being a SO questions.

**Comment by smitthakkar1** [comment]
same here
please let me know if you found any solution

**Comment by yonghongren** [comment]
I had the same symptom this morning. In my case the problem was caused by a python environment change. The hang is wating to spawn 'ios-deploy' (see ./node_modules/react-native/local-cli/runIOS/runIOS.js), which won't start due to a change to python environment I made last night.  You may want to check ./node_modules/react-native/local-cli/runIOS/runIOS.js to understand why the spawn won't succeed.
