### ISSUE TITLE
[Android] TextInput secureTextEntry doesn't work if it have a keyboardType prop with values 'email-address' or 'phone-pad'

### ISSUE THREAD

**Issue by samuelpismel** [facebook/react-native#20606]
- [ ✓ ] Review the documentation: https://facebook.github.io/react-native
  - [ ✓ ] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ ✓ ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Environment:
  OS: Linux 4.4
  Node: 8.11.3
  Yarn: 1.9.2
  npm: 6.3.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz => 0.55.4

## Description
[Android Only]

If you have an `keyboardType` prop with values 'email-address' or 'phone-pad' in your **TextInput** the `secureTextEntry` doesn't work and the input shows its value as a normal input (not like an password input).

## Reproducible Demo

Snack full example: https://snack.expo.io/HkqrRfqS7

```
<TextInput
  secureTextEntry
  keyboardType="email-address"
/>

<TextInput
  secureTextEntry
  keyboardType="phone-pad"
/>
```

**Comment by isis1234** [comment]
omg that useful for me!! thank you very much!

**Comment by shmilyiselephant** [comment]
Hi, thank you for your answer. I have met the same problems.

After resolving it, I think for the password input the keyboardType="default" is better than others in android.

**Comment by slorber** [comment]
can confirm, setting keyboardType default seems to fix this :o

**Comment by NativLouie** [comment]
wow thanks just saved me from 3 hrs of debugging
