### ISSUE TITLE
ios flatlist props contentOffset - 100, first render onscroll handler contentOffset.y begin is -100, soon is 0 

### ISSUE THREAD

**Issue by tabfed** [facebook/react-native#20610]
## Environment
nvironment:
  OS: macOS High Sierra 10.13.5
  Node: 10.4.0
  Yarn: 1.7.0
  npm: 6.1.0
  Watchman: Not Found
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: ^0.55.4 => 0.55.4

## Description
in ios
<AnimatedFlatList
          ref={(ref) => {
            if (!ref) return;
            if (ref.getNode) {
              this.theFlatList = ref.getNode();
            } else {
              this.theFlatList = ref;
            }
          }}
          style={[styles.scrollContainer]}
          data={this.state.productData}
          renderItem={this.renderItem.bind(this)}
          keyExtractor={this.keyExtractor}
          onEndReachedThreshold={1}
          onEndReached={this.onUpPull.bind(this)}
          scrollEventThrottle={1}
          onScroll={
            Animated.event(
              [{nativeEvent: {contentOffset: {y: this.state.scrollY}}}],
              {listener: this.flatListOnScrollListener.bind(this)}, 
              {useNativeDriver: true},
            )
          }
          // iOS offset for RefreshControl
          contentInset={{
            top: this.HEADER_MAX_HEIGHT,
          }}
          contentOffset={{
            y: -this.HEADER_MAX_HEIGHT,
          }}
        >
        </AnimatedFlatList>

like this code ,in ios use flatlist ,i set contentOffset, 

but, start event.nativeevent.contentOffset.y is -this.HEADER_MAX_HEIGHT, then event.nativeevent.contentOffset.y is 0,like flatlist`s contentOffset dont work

expect first render  event.nativeevent.contentOffset.y is   -this.HEADER_MAX_HEIGHT, no change to 0

**Comment by wns3645** [comment]
Same issue for me, too. Does anyone have this issue?
