### ISSUE TITLE
Android - Transparent Modal messes up StatusBar style.

### ISSUE THREAD

**Issue by adamivancza** [facebook/react-native#20623]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz
      Memory: 31.93 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.9.0 - /usr/local/bin/node
      npm: 6.3.0 - /usr/local/bin/npm
      Watchman: 4.5.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 23.0.2, 23.0.3, 24.0.2, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.3
        API Levels: 19, 22, 23, 24, 25, 26, 27
    IDEs:
      Android Studio: 2.2 AI-145.3360264
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1
      react-native: 0.56.0 => 0.56.0
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

## Description
I found this problem when I wanted to display a transparent modal over a screen which has a white status bar. Attached some screenshots about the issue:

![default_statusbar](https://user-images.githubusercontent.com/19835917/43971088-2087b14a-9cd0-11e8-864c-e0bc55d3baf2.png)

So this is the default state - the screen's status bar is set to white background with `dark-content` style.

![modal_transparent_statusbar](https://user-images.githubusercontent.com/19835917/43971120-3a002558-9cd0-11e8-89c6-83297a49a853.png)

Now this happens if I display a transparent Modal. As you can see the status bar's style is either changed or the transparent modal just overlaps the StatusBar somehow and causing this weirdness.

![modal_non_transparent_statusbar](https://user-images.githubusercontent.com/19835917/43971195-7a811402-9cd0-11e8-907f-5fe7bede861c.png)

There isn't any problem if Modal isn't transparent.

I think there shouldn't be any difference in the StatusBar regardless of Modal is transparent on not. On iOS this is completely consistent:

![ios_default_statusbar](https://user-images.githubusercontent.com/19835917/43971386-1ba7b9d0-9cd1-11e8-9534-a1f14136fb95.png)
![ios_modal_transparent_statusbar](https://user-images.githubusercontent.com/19835917/43971398-2bcb43a4-9cd1-11e8-867d-ce14664abbf6.png)
![ios_modal_transparent_statusbar](https://user-images.githubusercontent.com/19835917/43971422-40caab00-9cd1-11e8-90dc-46b0a4d0b53b.png)

## Reproducible Demo
https://github.com/adamivancza/rn-modal-statusbar-android-problem-repro

**Comment by Zjarr** [comment]
I tried `onShow()` method to see if it was possible to change status bar and content color, but got the same behavior.

**Comment by hxkuan** [comment]
<style name="AppTheme" parent="Theme.ReactNative.AppCompat.Light.NoActionBar.FullScreen"> </style>
it is work in react-native0.52, but in react-native0.56 it  not work。

**Comment by andrewzey** [comment]
I went with this library, which implements a modal separately, and doesn't ruin the statusbar: https://github.com/maxs15/react-native-modalbox

**Comment by adamivancza** [comment]
Issue still exists

**Comment by GollyJer** [comment]
Following. Definitely still an issue.

**Comment by Zver64** [comment]
+1

**Comment by cpojer** [comment]
This issue has been moved to react-native-community/react-native-statusbar#6.

**Comment by RichardLindhout** [comment]
I'm not sure if that library is the problem. Maybe this line is: https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/modal/ModalHostHelper.java#L54

+ I'm seeing a commit there which maybe fixes this https://github.com/facebook/react-native/commit/f8a4d281e2be5b68fbebf53f930d37d96236829c

**Comment by RichardLindhout** [comment]
Maybe this pull request
https://github.com/facebook/react-native/pull/13411

Also fixes our issue but it was never merged.

**Comment by jacek213** [comment]
Big issue...

**Comment by headfire94** [comment]
I described possible workaround here: https://github.com/react-native-community/react-native-modal/issues/50#issuecomment-526628352
