### ISSUE TITLE
Assigning percentage strings to padding, it works incorrect.

### ISSUE THREAD

**Issue by one-smiling** [facebook/react-native#20627]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Is this a bug report?
YES

## Environment
System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
      Memory: 374.75 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.3 - /usr/local/bin/node
      Yarn: 1.0.2 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 25.0.2, 26.0.1, 27.0.3
        API Levels: 23, 25, 26, 27
    IDEs:
      Android Studio: 3.1 AI-173.4697961
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      react-native-material-design: 0.3.7

## Description
assigning percentage strings to padding, it works incorrect,the paddingBottom is wrong,it should be same as paddingTop

#### react-native: 0.56.0 and 0.55.4
![simulator screen shot - iphone se - 2018-08-11 at 15 40 12](https://user-images.githubusercontent.com/6986063/43989548-79d149b0-9d7e-11e8-81fe-05645f1a7ce8.png)

#### use same code with react-native 0.51.0 ,it works correct.
![simulator screen shot - iphone se - 2018-08-11 at 15 48 06](https://user-images.githubusercontent.com/6986063/43989521-fb61b20e-9d7d-11e8-8188-9a24b8cad457.png)

## Reproducible Demo
**1.react-native init PaddingTestLatest**
**2.Just replace the default App.js file with this one.**

```
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
    StyleSheet,
    Text,
    View
} from 'react-native';

export default class App extends Component {
    render() {
        return (
            <View style={{
                flex: 1,
                justifyContent: 'center',
                alignItems: 'center',
                backgroundColor: '#F5FCFF',
            }}>
                <View style={styles.testStyle}>
                    <View style={{flex:1, backgroundColor:'red'}}>
                        <Text>内容</Text>
                    </View>
                </View>
            </View>

        );
    }
}


const styles = StyleSheet.create({
    testStyle: {
        width:100,
        height:100,
        backgroundColor: 'blue',
        padding:'5%',
        alignItems: 'center'
    },
});

```

**Comment by OdaDaisuke** [comment]
First, I think `padding` property of the outer box is calculating its value based on device width, not based on its `width` and `height`  value.

I tried this code. Please focus `onLayout`.

```js
...
      <View style={{
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#F5FCFF',
      }}
      onLayout={(e) => {console.log("A", e.nativeEvent.layout)}}
      >
      <View
        style={styles.testStyle}
        onLayout={(e) => {console.log("B", e.nativeEvent.layout)}}
      >
            <View
              style={{flex:1, backgroundColor:'red'}}
              onLayout={(e) => {console.log("C", e.nativeEvent.layout)}}
            >
                <Text>内容</Text>
            </View>
        </View>
    </View>
...
```


The console output results is.

```
C {y: 19, width: 27, x: 36.5, height: 33}
A {y: 0, width: 375, x: 0, height: 667}
B {y: 283.5, width: 100, x: 137.5, height: 100}
```

This is strange. X and Y axis is relative position of parent element.
C.y should `5`, shouldn't `19` because B.height is 100px.
