### ISSUE TITLE
Unable to stop Metro Bundler correctly [Windows]

### ISSUE THREAD

**Issue by MohamadKh75** [facebook/react-native#20633]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
[skip envinfo]

````
Environment:
  OS: Windows 8.1
  Node: 8.11.2
  Yarn: 1.7.0
  npm: 6.1.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  2.3.0.0 AI-162.3871768

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4
````
**UPDATE:**
```
E:\React Native\AirFreight>react-native -v
react-native-cli: 2.0.1
react-native: 0.56.0

E:\React Native\AirFreight>react-native info
Scanning folders for symlinks in E:\React Native\AirFreight\node_modules (25ms)

  React Native Environment Info:
    System:
      OS: Windows 8.1
      CPU: x64 Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz
      Memory: 13.07 GB / 15.92 GB
    Binaries:
      Yarn: 1.7.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.1.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  2.3.0.0 AI-162.3871768
```

## Description
I use `npm start` to start developing and when I want to stop my work, I use <kbd>Ctrl</kbd> + <kbd>c</kbd> to stop it (I use this way for a year). That was ok but it's been a while that i can't use npm start:

> **ERROR**  Metro Bundler can't listen on port 8081

I've run EVERY command I found on the net such as `netstat -abon | findstr ":8081"` to find the process but no result.

By the way, I tried new port and use `react-native start --port=8082` but again, after using <kbd>Ctrl</kbd> + <kbd>c</kbd> OR closing the cmd, I can't use that port again. I used `8082`, `8083` and `6969` but I think it's not the correct way to stop that!

## Reproducible Demo
...

**Comment by MohamadKh75** [comment]
@hramos

**Comment by hramos** [comment]
Can you update your post? It still says 0.55.4, you can re-run `react-native info` to get updated numbers.

**Comment by MohamadKh75** [comment]
@hramos i tried `react-native info` but i didn't see the RN version there so i added `react-native -v` - Updated!
