### ISSUE TITLE
RSOD Memory Usage

### ISSUE THREAD

**Issue by anthonyhumphreys** [facebook/react-native#20637]
## Environment
```
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
      Memory: 11.73 GB / 32.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.7.0 - /usr/local/bin/node
      npm: 6.2.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 25.0.0, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.1, 28.0.2
        API Levels: 23, 25, 26, 28
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1
      react-native: 0.56.0 => 0.56.0
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```
## Description
I will conduct more investigation to obtain some more solid info on this one, but so far I can only report high memory usage/leak when an RSOD is encountered in a RN project whilst Remote Debug was enabled - A RSOD occurred while my machine was unattended, on my return i found the attached usage (and a hot, loud MacBook! 😛) only affects iOS.

The project is a boilerplate I'm working on and is currently a testbed for some UX work - there are no debugging tools installed in it, only apollo-client and native-base. The same behaviour seems to occur in an independent project, and the error has been encountered on colleagues' machines.

<img width="1232" alt="screen shot 2018-08-12 at 15 13 57" src="https://user-images.githubusercontent.com/10463314/44002992-7f22d92c-9e43-11e8-98ce-a316a1e067e6.png">

## Reproducible Demo
Have a component throw an error on render to trigger RSOD and leave for a while. Memory usage rapidly goes up. Seems to only happen when chrome debugger is attached.

More details to follow after investigating some more.

**Comment by anthonyhumphreys** [comment]
Hello,
Not got round to providing more issues but can confirm this behaviour does seem to still occur.

Reproduce - react native init -> throw an error in first render -> leave on RSOD and monitor resource usage

**Comment by kelset** [comment]
Hello there 👋 this issue seems to have been inactive for the past few weeks. Because of this, it's likely that the issue is not a high priority anymore or it has been solved by OP; for these reasons, we'll close it.

But please, if it's actually still an issue with 0.59 please comment below and we can reopen it or please send us a Pull Request with a fix 😊

**Comment by mikehardy** [comment]
@kelset this is super old but I just experienced this and @Salakar mentioned it to me today as well. This is with react-native 0.59.9

reproduction is to run a react-native app in an iOS simulator, chuck an error that causes an RSOD / redbox / error screen then...wait. For me after just a couple hours I had about 30GB being used (!)

**Comment by anthonyhumphreys** [comment]
Yep same here. Those are the exact repro steps.

I’d send some dumps etc but my main machine is out of action at the moment

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kelset** [comment]
Oh, interesting!

Thanks for the update, let's reopen this.

So this wasn't happening with 0.59.8? I can't really see any commits that I have cherrypicked for 0.59.9 that could be related to this: https://github.com/facebook/react-native/commits/0.59-stable

**Comment by anthonyhumphreys** [comment]
Not really sure! Will do some testing when I get a sec but I’m fairly sure it’s been an issue for a few versions now, think it’s just an evasive one.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kelset** [comment]
Oh ok - any chance you can do your testing against 0.60 rc too?

**Comment by anthonyhumphreys** [comment]
Sure thing

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by KingAmo** [comment]
![image](https://user-images.githubusercontent.com/29938227/61949201-92ad2f00-afdc-11e9-82ac-74fe41b9d1a2.png)
the same problem here, `rn 0.59.10`

**Comment by anthonyhumphreys** [comment]
Hi @kelset i'm slowly putting together some tests in here: https://github.com/anthonyhumphreys/rsod-tests - should have a few more bits in there this evening. Apologies for the delay in getting this to you.

**Comment by KingAmo** [comment]
still has this issue in  `react native 0.61.2`
