### ISSUE TITLE
Nested Text component has incorrect touch area

### ISSUE THREAD

**Issue by jm-david** [facebook/react-native#20645]
## Environment
```
Environment:
  OS: macOS High Sierra 10.13.6
  Node: 9.11.1
  Yarn: Not Found
  npm: 6.3.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz => 0.55.2
```

## Description
When the parent `Text` component has padding, the touch area for any nested `Text` components is not calculated correctly (ie. padding offset is not applied).

## Reproducible Demo
https://snack.expo.io/H1A3ysRH7

**Comment by ggtmtmgg** [comment]
You cannot pass `onPress()` to nested `Text`.
On Android, nested `Text` is going to be converted [`SpannableString`](https://developer.android.com/reference/android/text/SpannableString) and then pass `SpannableString` to the single `TextView`.
I don't know how hundled on iOS, but it's supposed to be similar to Android.

If you want to pass `onPress` to the specific `Text`, you could do like below.
```
<Text>
  Hello 
</Text>
<Text style={styles.link} onPress={this.onPressLink.bind(this)}>
  React 
</Text>
<Text>
  Native
</Text>
```

Expo demo: https://snack.expo.io/Sk3m3EZ87
