### ISSUE TITLE
Could not connect to development server on android emulator and on real device

### ISSUE THREAD

**Issue by MaxToyberman** [facebook/react-native#20646]
## Environment
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
      Memory: 132.19 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.4.1 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.1.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 23.0.2, 25.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.2, 27.0.3, 28.0.1
        API Levels: 23, 24, 26, 27
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: ^3.4.8 => 3.4.8
      react: 16.4.1 => 16.4.1
      react-native: 0.56 => 0.56.0
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-create-library: 3.1.2
      react-native-git-upgrade: 0.2.7

## Description
Adding `android:targetSandboxVersion="2"` to manifest tag in AndroidManifest.xml causes red screen with  Could not connect to development server error.
this happens almost on all devices and simulators.

## Reproducible Demo
just add  `android:targetSandboxVersion="2"` to manifest tag in AndroidManifest.xml

**Comment by quachsimon** [comment]
I am getting something similar but, on iOS. This is a fresh project that was just created:
Been scratching my head for the last 2 hours on this... 
Tried:  
- deleting project and making new
- going through the docs
- restart computer
- change ports

![simulator screen shot - iphone 8 - 2018-08-13 at 02 01 47](https://user-images.githubusercontent.com/20729321/44016696-d144a16c-9ea3-11e8-9955-8d774daa3e43.png)

**Comment by MaxToyberman** [comment]
@quachsimon can you show me your podfile ?

**Comment by quachsimon** [comment]
@MaxToyberman This is a project literally just created from `react-native init` so there is no podfile added

**Comment by quachsimon** [comment]
@react-native-bot Yes, this is on `v0.56`

**Comment by MaxToyberman** [comment]
@react-native-bot yes.
