### ISSUE TITLE
Let developer "Enable Live Reload" programmatically

### ISSUE THREAD

**Issue by fatuhoku** [facebook/react-native#2064]
I want an alternative way of activating this option without necessarily going through the RN dev menu. Reasons for this may be because the menu cannot be activated from the modal (see #2063), or that your shake gesture is already bound to something else useful in your app.

RN appears to persist the Enable Live Reload preference across sessions — I'm assuming it uses `NSUserDefaults` or some such, so a simple solution might be to document the exact key for which this preference is stored. I could then write into that key the value I want (`YES`, always) and enable it without the UI.

**Comment by ide** [comment]
Yeah it's stored in NSUserDefaults as a dictionary. Here's the documentation :P https://github.com/facebook/react-native/blob/master/React/Base/RCTDevMenu.m#L191

**Comment by fatuhoku** [comment]
@ide Haha. Works a charm. The exact snippet I used:

```objc
    // Enables live reload programmatically...!
    NSUserDefaults *defaults = [NSUserDefaults standardUserDefaults];

    NSMutableDictionary *settings = [(NSDictionary *)[defaults valueForKey:@"RCTDevMenu"] mutableCopy];
    settings[@"liveReloadEnabled"] = @YES;

    [defaults setObject:settings forKey:@"RCTDevMenu"];
    [defaults synchronize];
```

**Comment by faceyspacey** [comment]
it seems to be different now. How would I go about this now? I just want to be able to assign a button in my app the ability to reload so I can just press it, or call a command from the chrome console. This is especially important with hot loading since regular reload isn't used anymore.
