### ISSUE TITLE
[AppRegistry] Invariant Violation: Application xxx has not been registered happen with 0.3% users..

### ISSUE THREAD

**Issue by Nirvana-icy** [facebook/react-native#2066]
Hello everyone..

We get this log from user:

FatalJSException":"Invariant Violation: Application maimaimai has not been registered.

Actually, in the dev mode we do not meet this issue.In the dev mode we can find this page normally.

Then we publish the jsBundle file to the user.About 0.3% user meet this issue.Then can not find maimaimai page.

So what will cause this situation? I try to reproduce this issue in the dev mode,it does not happen.

BRs.

**Comment by brentvatne** [comment]
@Nirvana-icy - do you have any more context around the users who experience this? Or anything that is non-standard about your app, if that is the case? We'll need as much information as you can possibly share for this

**Comment by grabbou** [comment]
Are you serving bundle from app or from remote URL? Maybe connectivity issues?

**Comment by Nirvana-icy** [comment]
@brentvatne I do not have more context from the crash log upload by our native app.The link of the jsBundle is : http://s6.mogucdn.com/other/150716/1ufz_iezgenbwmjqtazjwgizdambqmmyde_m.amr
@grabbou The bundle is from remote URL in CDN.
First the bundle is downloaded to the app,then the app unzip it.If RN try to load the undownloaded bundle,it report another issue not this issue.

**Comment by ide** [comment]
You need to collect more information to figure out if this is a problem with a specific phone + OS, content corruption, etc. When you find what the issue is, feel free to open a new issue if the problem is with React.

**Comment by grabbou** [comment]
That's what I said, I had these issues when my bundle was offline. What I do is I bundle jsbundle with the app and we update nightlies to CDN. In case update cannot be downloaded, the bundled version is served. Then, the bundled version is updated once a month within Apple Store.

**Comment by grabbou** [comment]
The bundle gives me 502 error btw.

**Comment by jackyanjiaqi** [comment]
last night is ok,today once I run-android on my device this error given what's happening

**Comment by liemlyquan** [comment]
@jackyanjiaqi I has the same problem with this too. Have you solved the problem yet ?
