### ISSUE TITLE
Animated.View is not cropped by parent View size in iOS

### ISSUE THREAD

**Issue by lucasharada** [facebook/react-native#20671]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Environment:
  OS: macOS High Sierra 10.13.6
  Node: 8.11.2
  Yarn: 1.3.2
  npm: 6.2.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-28.0.1.tar.gz => 0.55.4

## Description
I implemented an InputBar component that is built by an Animated.View component containing 3 Components: LeftComponent, CenterComponent and RightComponent. The InputBar itself can have 2 main states: (a) when receiving text input or (b) when recording audio.

While in (a), the LeftComponent is a TouchableOpacity, the CenterComponent is a TextInput and the RightComponent is an Animated.View.
While in (b), the LeftComponent is an Image, the CenterComponent is a Text and the RightComponent remains an Animated.View.

When recording audio, the AnimatedView from RightComponent needs to expand in a circular way just like WhatsApp (see image below).

![image](https://user-images.githubusercontent.com/18669473/44109229-def97c80-9fd2-11e8-9fc4-5f30633ba050.png)

The problem here is that the RightComponent does not get cropped by the InputBar height in iOS. For Android, it behaves the way as expected: the circle expands, but when its size gets bigger then the parent View height, it is cropped leaving its top border as a straight line. On iOS, though, the circle expands ignoring the parent View height, remaining a complete circle on the top of the View. See images below to compare. The situation occurs even before animating.

![12312312112](https://user-images.githubusercontent.com/18669473/44109665-0120a2e2-9fd4-11e8-80f2-723171bee775.png)
<img width="398" alt="captura de tela 2018-08-14 as 15 22 05" src="https://user-images.githubusercontent.com/18669473/44110380-e5063728-9fd5-11e8-8d88-2d5d2a6be44c.png">

## Reproducible Demo
Since animating is not required to check the error, I implemented a static Expo: https://snack.expo.io/rkWvn9l8X

Switching from Android to iOS demonstrates the difference between the two implementations.

**Comment by lfkwtz** [comment]
More info about this issue here: https://github.com/facebook/react-native/issues/8968

This could help you: https://github.com/entria/react-native-view-overflow
