### ISSUE TITLE
[SoftJSException] undefined is not an object (evaluating 'l.KeyboardDismissMode.None') 

### ISSUE THREAD

**Issue by easunny** [facebook/react-native#2067]
i find a problem about the "ScrollView.js"
i think the "RCTScrollViewConsts.KeyboardDismissMode" don't return the right value every time
my reactNative's tag is 0.6
is my version too old or there is some code i don't write so good in scrollView ?

**Comment by brentvatne** [comment]
Hi @easunny - at this point in time, you should try to keep up to date with the newest version of React Native because improvements are coming in very rapidly and it's too difficult to support all old minor versions. Could you test this on 0.8.0-rc to see if you still have this problem?

**Comment by easunny** [comment]
@brentvatne - i will try it later, thanks very much :)
