### ISSUE TITLE
[render] Fails silently and blocks when exception occurs

### ISSUE THREAD

**Issue by grabbou** [facebook/react-native#2068]
As above, will fail silently and will block JS environment so e.g. Flux async actions and callbacks waiting in the event loop are not invoked (the UI freezes). This happens for all kinds of errors, including bad style, runtime exceptions or missing imports.

Initially I've encountered that in Navigator, when no transition is made (probably due to the above lock) and nothing happens. I would expect the red box with error to appear (at least in dev mode).

Another place I've found that was when refactoring some small components I forgot to import my custom `Button` component from another folder, thanks we have `eslint`, otherwise it would've been quite tricky. I would prefer either `packager` error or runtime error when this happens. Same happens when you forgot to import `Image` - in this case `eslint` needs to be tweaked as in normal case it won't warn you about that.

React 0.7.1

**Comment by ericvicenti** [comment]
Could you possibly post a code snippet that shows this bug? I'm curious when exceptions get swallowed during a render- that shouldn't ever happen.

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/render-fails-silently-and-blocks-when-exception-occurs
