### ISSUE TITLE
Scrollable FlatList nested in ScrollView not rendering all elements

### ISSUE THREAD

**Issue by adamczyk777** [facebook/react-native#20684]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
 React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
      Memory: 1010.70 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.1 - /usr/local/bin/node
      Yarn: 1.6.0 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 23.0.3, 25.0.0, 25.0.2, 25.0.3, 26.0.2, 26.0.3, 27.0.2, 27.0.3
        API Levels: 23, 24, 25, 26, 27
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1
      react-native: 0.56.0 => 0.56.0

## Description
When using a flatList with defined renderScrollComponent prop nested in an external ScrollView element, the inner flat list renders only initial 10 elements and resists to render further elements, probably an issue with onEndReached as it is not being invoked even if the threshold is changed from default.

## Reproducible Demo
Here is a repository with a project created with rn init to reproduce the issue.
https://github.com/adamczyk777/nested-scroll-view-bug-report

**Comment by JLVilleminot** [comment]
Try to pass the Flatlist's props to your scrollComponent like this 
`  _renderScrollComponent = (props) => (
    <ScrollView nestedScrollEnabled={true} {...props} style={{ height: 100 }} />
  );`

It should do the job!
