### ISSUE TITLE
Saving mongodb _id in Asyncstorage works, but clearing the asyncstorage or deleting the _id doesn't.

### ISSUE THREAD

**Issue by leksyib** [facebook/react-native#20682]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Run `react-native info` in your terminal and paste its contents here.
Environment:
  OS: macOS High Sierra 10.13.6
  Node: 10.1.0
  Yarn: 1.6.0
  npm: 6.1.0
  Watchman: Not Found
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  react: ^16.4.1 => 16.4.1
  react-native: ^0.55.4 => 0.55.4

## Description
In my app, I tried to save a user's id which is a mongodb ObjectId in the AsyncStorage. Saving it works, but when I call the `AsyncStorage.getItem('userId')` , it returns random mongodb objectIds.
I cleared the device, installed the app again and it still returns random mongodb ids.

## Reproducible Demo
Build a simple app that gets an api endpoint, I set one up here: http://blurgscrape.herokuapp.com/movies/5b642c40d1551a74e99a9d14, it returns json like this:

```
{
  "_id": "5b642c40d1551a74e99a9d14",
  "title": "Anchorman 2: The Legend Continues (2013)",
  "release": "18 December 2013 (USA)",
  "summary": "With the 1970s behind him, San Diego's top-rated newsman, Ron Burgundy, returns to take New York City's first twenty-four-hour news channel by storm.",
  "__v": 0
}
```
Save the `_Id` field in AsyncStorage as `userid`, then make a function to get the `userId` item from asyncstorage and alert. it'll keep returning random mongodb Id strings.

**Comment by leksyib** [comment]
The issue still persists on v0.56

**Comment by Prash99** [comment]
AsyncStorage.clear() not clearing the data with React Native version 0.57.8 . data will be cleared once I refresh the Application.
