### ISSUE TITLE
[ListView] Exception in `renderSectionHeader` is overwritten by another one

### ISSUE THREAD

**Issue by grabbou** [facebook/react-native#2069]
When in renderSectionHeader of ListView there's an exception (e.g. bad style property), instead of it, another one is being showed:

<img width="250" alt="screen shot 2015-07-21 at 08 46 14" src="https://cloud.githubusercontent.com/assets/2464966/8794558/fbd8384e-2f84-11e5-91d4-147628992712.png">

It also looks like ListView keeps looping as the above exception is being printed to the console infinitely.

React 0.7.1

**Comment by ericvicenti** [comment]
This would probably make a good first task. Plus it would be great to get more contributors thinking about ListView

**Comment by ericvicenti** [comment]
Seems similar to #1965 . Leaving both open for now because this is about errors swallowed in `renderSectionHeader`

**Comment by grabbou** [comment]
Going to reproduce it on master and if it still happens - will try to make the error better. @ericvicenti definitely, ListViews has always been crucial bits of every iOS application, so the more effort we put into its development the better developer experience we get in the end.

**Comment by ide** [comment]
Thanks @grabbou. I also like that handling the error in JS improves the state of Android too.

**Comment by grabbou** [comment]
Ok, thanks for the tip :dancers:

**Comment by MattFoley** [comment]
I noticed the other related issues were closed, but on 0.15rc this still seems to be a problem.

**Comment by brentvatne** [comment]
Looks like this is a dup of #1379
