### ISSUE TITLE
onKeyPress event is not working for TextInput 

### ISSUE THREAD

**Issue by sayantanbasu** [facebook/react-native#20713]
## Environment
Environment:
  OS: Windows 10
  Node: 8.11.2
  Yarn: Not Found
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.1.0.0 AI-173.4819257

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: ^0.50.3 => 0.50.3

## Description
onKeyPress event is not working for TextInput 

## Reproducible Demo
import React, { Component } from 'react';
import { Text, View, StyleSheet, Alert, Button, TextInput } from 'react-native';

export default class App extends Component {
    constructor(props) {
        super(props);
        this.state = {
            inpText: ''
        }
    }

    componentDidMount() {
    }

    openScanner(event) {
        Alert.alert("Error", "Unable to detect Zebra TC-20 scanner");
    }

    _handleBarCodeRead = data => {
        var keyPressed = data.nativeEvent.key;

        if (keyPressed == "Enter") {
            alert("Barcode value is : "+this.state.inpText);
        }
    };

    render() {
        return (
            <View style={styles.container}>
                <View style={{ marginTop: 50, flexDirection: 'column' }}>
                    <TextInput numberOfLines={1} autoFocus={true} style={{width:300,fontSize:25,padding:10,backgroundColor:'black',color:'white',hight:30 }} onKeyPress={this._handleBarCodeRead} multiline={true} value={this.state.inpText} onChangeText={(text) => this.setState({ inpText: text })} />
                    <Text>Barcode value : {this.state.inpText}</Text>
                </View>
            </View>
        );
    }
}

const styles = StyleSheet.create({
    container: {
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#ecf0f1',
    },
});

**Comment by franzejr** [comment]
Are you trying that on iOS or Android?

[Checking on the documentation](https://facebook.github.io/react-native/docs/0.50/textinput#onkeypress), we can see `onKeyPress` is iOS only. Check out also this issues [here](https://github.com/facebook/react-native/issues/18339) to give you more ideas.

**Comment by Guar1** [comment]
@react-native-bot....

No, it is old version only.

**Comment by sayantanbasu** [comment]
Hi,
I am developing Android only. and also gone through with the documentation. @franzejr . After updating the React Native SDK issue is now resolved. 

Thanks you. :)
