### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by nsmith1024** [facebook/react-native#20726]
I just installed react native on windows, then i typed

react-native init IslandFun
then
react-native start

in another DOS shell i typed

react-native run-android
then i get this error below, Does anybody know whats wrong???

.....
[snip]
Download https://jcenter.bintray.com/com/android/tools/jack/jack-api/0.13.0/jack-api-0.13.0.jar
Download https://jcenter.bintray.com/org/eclipse/jdt/core/compiler/ecj/4.6.1/ecj-4.6.1.jar
Download https://jcenter.bintray.com/net/sf/proguard/proguard-base/5.3.2/proguard-base-5.3.2.jar
Download https://jcenter.bintray.com/com/android/tools/external/com-intellij/uast/162.2228.14/uast-162.2228.14.jar
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to D:\Android\sdk \ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Trailing char < > at index 14: D:\Android\sdk \package.xml

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 53.315 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

**Comment by gengjiawen** [comment]
remove space in your sdk folder `D:\Android\sdk \package.xml`.

**Comment by nsmith1024** [comment]
you mean space in my sdk folder name? there isnt any space

**Comment by gengjiawen** [comment]
Maybe try to reconfigure you android sdk, possible just use the one bundled with android studio.

**Comment by nsmith1024** [comment]
PROBLEM SOLVED - i started over and follows the steps at https://facebook.github.io/react-native/docs/getting-started.html

error went away, but now have different error..

I have the Android emulator open, and the adb server has already started, but still i get this error

112:21:08: Starting Android...
Error running adb: protocol failure

 › Press a to open Android device or emulator.
 › Press s to send the app URL to your phone number or email address
 › Press q to display QR code.
 › Press r to restart packager, or R to restart packager and clear cach
 › Press d to toggle development mode. (current mode: development)

**Comment by gengjiawen** [comment]
can you run `adb devices` in your terminal. Also you should ask such questions in stackoverflow.

**Comment by nsmith1024** [comment]
never mind i tried Expo and it worked, everything work now, thanks

**Comment by nsmith1024** [comment]
This is so F*** AMAZING!!!
