### ISSUE TITLE
Fetch takes so much time to start

### ISSUE THREAD

**Issue by msafayasar** [facebook/react-native#20728]
- [+] Review the documentation: https://facebook.github.io/react-native
  - [+] Search for existing issues: https://github.com/facebook/react-native/issues
  - [+] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Environment:
  OS: macOS High Sierra 10.13.6
  Node: 8.9.1
  Yarn: 1.3.2
  npm: 5.5.1
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: ^0.55.4 => 0.55.4

## Description
   In both on Android (emulator and device) and IOS (simulator and device) **sometimes** fetch request does not start immediately. Most of the time I need to wait for 10-60 secs in order to start fetch. It happens at all of the fetch requests all over the app. I wrote a middleware to inform me when a request comes and most of the time it is about 10-60 seconds. But sometimes it works immediately. I am sure my server side code is not that slow. I tested it. But I cannot understand this behavior of fetch. Also my website is https, not http. 

   On the other hand, it happens more on Android than IOS. I think there is some kind of bug in fetch or maybe there is a conflict in node modules.

## Reproducible Demo
  I am not sure if we can reproduce this issue but I googled it for over 2 weeks and I nearly read all posts, comments about fetch in github and stackoverflow. I couldn't find any solution for it. Thus, I think there is some kind of bug or maybe there is a conflict in node modules but I am not sure.

**Comment by franzejr** [comment]
@msafayasar maybe if you create a simple example that it happens **sometimes** other person could try to reproduce it too ?  I've been using fetch and I'm not seeing this issue.

**Comment by msafayasar** [comment]
Actually I am facing the same problem with #20405
