### ISSUE TITLE
RTL issue - English on Hebrew Android phones

### ISSUE THREAD

**Issue by pashute** [facebook/react-native#20730]
Continued issue following #20362

[v] Review the documentation: https://facebook.github.io/react-native
[v] Search for existing issues: https://github.com/facebook/react-native/issues
[v] Use the latest React Native release: https://github.com/facebook/react-native/releases
Environment
Phones:

Galaxy J7 Nxt, Android 7.0, updated Feb 1, 2018, Language chosen: Hebrew
Galaxy S7, Android 7.0, updated Oct 1, 2017, Language chosen: Hebrew
React-native Environment:
   OS: Windows 10
   Node: 8.11.1
   Yarn: 1.7.0
   npm: 6.1.0
   Watchman: Not Found
   Xcode: N/A
   Android Studio 3.1.4
   Build #AI-173.4907809, built on July 24, 2018
   JRE: 1.8.0_152-release-1024-b02 amd64
   JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
   Windows 10 10.0

    Packages: (wanted => installed)
    react: 16.3.1 => 16.3.1
    react-native: 0.55.3 => 0.55.3

Description
On emulator, everything looks ok. When I build and run in debug or actual app, everything is right-to-left.

order of objects in view
texts justified to right
chevron to be shown on right of a list (with flex) is on far left
Adding i18n with force rtl true or false does not help.

Reproducible Demo
https://github.com/pashute/rnUtubeUI

**Comment by jamsch** [comment]
I believe you need to set supportsRtl to "false" in your AndroidManifest file.

```xml
<application
    android:supportsRtl="false"
>
...
</application>
```

**Comment by pashute** [comment]
Your older post is, in fact, this issue exactly. 
https://github.com/facebook/react-native/issues/10204#issuecomment-370581812 

Shukran Jazilan!! شكرا جزيلا
