### ISSUE TITLE
The development server returned response error code: 500 - running React Native project

### ISSUE THREAD

**Issue by codingsuccessfully** [facebook/react-native#20736]
I am trying to run my first application, but this error persists, I already typed the commands: 
1.watchman watche-del-all (this is not recognized as an internal or external command) 
2.rm -rf node_modules && npm install 
3. reset

But nothing worked,

Someone knows how to solve this????? I will appreciate it!!!
![captura](https://user-images.githubusercontent.com/31166319/44310825-99c1cb00-a391-11e8-8212-1cff09432f74.JPG)

**Comment by nsmith1024** [comment]
im in the same boat, i just installed react-native, then did a build and it works on the phone. Then i installed google maps from the command like without changing any code, when i try to build it doesnt work, react-native stop working completely, not even the command line works anymore.
