### ISSUE TITLE
iOS: Text Line Height issue when using custom font & system language is Japanese

### ISSUE THREAD

**Issue by wxlittle** [facebook/react-native#20732]
- [v] Review the documentation: https://facebook.github.io/react-native
  - [v] Search for existing issues: https://github.com/facebook/react-native/issues
  - [v] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
      Memory: 485.86 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.9.1 - /usr/local/bin/node
      Yarn: 1.3.2 - /usr/local/bin/yarn
      npm: 5.5.1 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 26.0.3, 27.0.3, 28.0.2
        API Levels: 21, 26, 27, 28
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.4.0 => 16.4.0 
      react-native: ^0.56.0 => 0.56.0 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description
Using Roboto as custom font, under english language, everything is rendered correctly.
Once switched the system language to **Japanese**, you can see the line height for Chinese & Japanese Characters become very big & the text is aligned to the top of the bounding box. 
This is only happened in **iOS** when system language is Japanese
Text is rendered correctly when system language is English / Korean / Simplified Chinese / Traditional Chinese. 

![system lang en](https://user-images.githubusercontent.com/3414637/44309376-40d94d80-a3f8-11e8-9b8d-335c9ca530b3.png)
![system lang ja](https://user-images.githubusercontent.com/3414637/44309377-4171e400-a3f8-11e8-93ba-aa1db95badbc.png)

## Reproducible Demo
Remember to set device language to Japanese
https://snack.expo.io/SyW6BCLUX

**Comment by wxlittle** [comment]
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
      Memory: 485.86 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.9.1 - /usr/local/bin/node
      Yarn: 1.3.2 - /usr/local/bin/yarn
      npm: 5.5.1 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 26.0.3, 27.0.3, 28.0.2
        API Levels: 21, 26, 27, 28
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.4.0 => 16.4.0 
      react-native: ^0.56.0 => 0.56.0 
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by wxlittle** [comment]
Anyone could help on this?

**Comment by wxlittle** [comment]
https://snack.expo.io/SyW6BCLUX

Make any changes, then "Save changes" and "Export".
You could find the font from the download file.

<img width="513" alt="export" src="https://user-images.githubusercontent.com/3414637/45472483-ecab5a00-b766-11e8-8121-e6264c65e563.png">

**Comment by nguyenhaininh** [comment]
> > Please tell me how can I download this font?
> 
> https://snack.expo.io/SyW6BCLUX
> 
> Make any changes, then "Save changes" and "Export".
> You could find the font from the download file.
> 
> <img alt="export" width="513" src="https://user-images.githubusercontent.com/3414637/45472483-ecab5a00-b766-11e8-8121-e6264c65e563.png">

yep, I got it. Thank you so much.
