### ISSUE TITLE
[DevMenu] Long press the status bar to open dev menu

### ISSUE THREAD

**Issue by aleclarson** [facebook/react-native#2073]
Shaking my phone every time is kinda annoying.

A simple long press on the status bar would be much easier, IMO.

**Comment by browniefed** [comment]
You can press Cmd + D to open it up.

**Comment by jaygarcia** [comment]
@browniefed , doesn't help when you're testing on a physical device.

**Comment by browniefed** [comment]
@jaygarcia I realized that as soon as I posted. xD

**Comment by jaygarcia** [comment]
@aleclarson , only helps if the Status bar isn't hidden, but I agree. =)

What fun is demo'ing the menu popping up to people. I look like a tool waving my phone around.

**Comment by brentvatne** [comment]
@aleclarson - the dev menu exposes a `show` function that you can call from anywhere, so you can build in some custom entry point if you like:

```javascript
var { NativeModules } = require('react-native');
var { DevMenu } = NativeModules;

DevMenu.show()
```

You could attach that `DevMenu.show()` to some button press in your app.

(Didn't test this but it should work, might require some slight modification)

Let me know if that helps :smile:

**Comment by browniefed** [comment]
@brentvatne @aleclarson yep seems to work.
https://rnplay.org/apps/DIScsg/

**Comment by mrspeaker** [comment]
I'm already using long-press-the-status-bar as a feature in my app, so would appreciate a way to switch that off!

**Comment by brentvatne** [comment]
Closing this as the option I mentioned above allows you to customize in any way you like. If you'd like to propose an alternative, please implement and submit a PR so we can try it out and discuss!

**Comment by ritz078** [comment]
is it no longer present ?
