### ISSUE TITLE
RCTImageLoader cause crash

### ISSUE THREAD

**Issue by kobe1941** [facebook/react-native#20746]
## Environment
Environment:
  OS: macOS High Sierra 10.13.5
  Node: 8.6.0
  Yarn: Not Found
  npm: 5.5.1
  Watchman: 4.7.0
  Xcode: Xcode 9.4 Build version 9F1027a
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: 0.48.4 => 0.48.4

## Description

RCTImageLoader's function canHandleRequest: may cause crash.

![image](https://user-images.githubusercontent.com/7099017/44324479-5dbd6180-a488-11e8-9982-4fe6f5f3a7e4.png)

this is not thread safe code.
In my app ，I found some crash when app launch in 10 second , this method is not thread safe.
maybe disaptch_one should use for videoRegex ?

crash signal is  SIGSEGV. 
and our crashreport is like this:
![image](https://user-images.githubusercontent.com/7099017/44324594-b7be2700-a488-11e8-9fcc-e6f9b99919e0.png)

## Reproducible Demo
It looks a normal multi-thread crash,  just make mutil-thread to access the canHandleRequest: method , you will reproduce it.

**Comment by kobe1941** [comment]
@react-native-bot I noticed that , for RN latest 0.56 version ,  RCTImageLoader's canHandleRequest function is not modify since RN 0.48 version.
so I think it is also exsit this problem in latest version 0.56.

**Comment by kobe1941** [comment]
@hramos the crash happens  ocasionally in our on-line app, we received some crashreport then  we knew this.
I noticed that, the crash stack mentiond the code is not modify since 0.48 version, so if only to update 
to version 0.56, I think it is useless.
and even , update version for reactnative in our app will cost too much time, the suitable way to reproduce the crash is to write a demo, and use the latest version.
I will write a demo to verify.
but I am still think, the method canHandleRequest: is not thread safe, Obviously.

**Comment by hramos** [comment]
I appreciate your effort to test this in 0.57. We have a high number of open issues, so it's typically not a good use of a maintainer's time to investigate reports that haven't been confirmed on the latest release.

I understand it can take some effort to update an individual app, which is why we only request a minimal example that isolates the issue. This is preferred as investigating crashes in a individual app is out of scope of this issue tracker.

**Comment by kobe1941** [comment]
@hramos okay, i will update version and keep watching. thanks a lot~

**Comment by xiaoyongchen** [comment]
@kobe1941
I have the same problem. How do you solve it?

**Comment by kobe1941** [comment]
@xiaoyongchen it is not suitable to change the code for react-native, so I am update version now.
a large of errors in my project, I want to cry...

**Comment by hramos** [comment]
Closing as this is a report for an older version....

**Comment by xiaoyongchen** [comment]
@hramos 
hi，
0.51 there is another mistake.
Upgrade to that version?

**Comment by xiaoyongchen** [comment]
@kobe1941 
How do you solve it?

**Comment by xiaoyongchen** [comment]
@hramos 
Which version do you upgrade to now?

**Comment by kobe1941** [comment]
@xiaoyongchen I fixed it by method swizzling the method canHandleRequest:
and i just add a lock to this method.
but my app is not review success by Apple, so I am not sure , if it not crash anymore when I add a lock to the method.

**Comment by xiaoyongchen** [comment]
@kobe1941 ￼ ￼
_brage = nil  => This led to the collapse.
but,I don't know why it turned into nil.

  RCTNetworking *networking = [_bridge networking];

    if (RCT_DEBUG && ![networking canHandleRequest:request]) {
        RCTLogError(@"No suitable image URL loader found for %@", request.URL.absoluteString);
        return NULL;
    }

**Comment by kobe1941** [comment]
@xiaoyongchen 我们的崩溃可能不一样，你可以看我的截图，我是因为启动时多线程访问同一个函数导致的SIGSEGV类型崩溃，典型的野指针，跟你的不一样哈

**Comment by xiaoyongchen** [comment]
@kobe1941 
![wechatimg39](https://user-images.githubusercontent.com/15923188/45814763-323cc980-bd09-11e8-884b-f053fa906605.jpeg)

**Comment by kobe1941** [comment]
@xiaoyongchen 访问了无效的内存地址，如果是刚刚使用了RN的Image就崩溃，那就跟我的问题是一样的。

**Comment by xiaoyongchen** [comment]
@kobe1941 你是如何解决的，感觉加锁没没解决问题。
或者你给我看下你的代码。
前面提到升级，升级有用吗？
你升了级吗

**Comment by kobe1941** [comment]
@xiaoyongchen 
我的崩溃日志看是因为videoRegex这个static的变量，其初始化的过程是非线程安全的，可能多个线程同时进行初始化，在一个线程继续往下走执行firstMatchInString:这个函数的时候，videoRegex这个变量被重新赋值了，所以之前那块内存就会没有人持有而被系统回收，而有一个函数却还在执行中，导致野指针。

![image](https://user-images.githubusercontent.com/7099017/45863033-e9d3e900-bda6-11e8-8c99-3a8da7379fa9.png)

**Comment by kobe1941** [comment]
it  works in my app.
so this is just a easy crash to fixed, but facebook don't want to face it.

**Comment by geastwood** [comment]
@kobe1941 nice finding. Why not open a PR and see whether it will be merged.

**Comment by kobe1941** [comment]
@geastwood Thanks for reminding, I will try it.

**Comment by geastwood** [comment]
@kobe1941 We are facing the same problem. Can you reliably reproduce this?

**Comment by kobe1941** [comment]
@geastwood I can not reproduce it by debug, but the SIGSEGV crash never appear again after add this code to my project.

**Comment by tayyabaAslam** [comment]
I am using RN version 0.57.7 and faced the same crash. There is not any scenario for the crash to appear it just appeared while using app.
