### ISSUE TITLE
Error anytime I run react-native run-android: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference getBoolean

### ISSUE THREAD

**Issue by spiritman110** [facebook/react-native#20754]
## Environment
```
Environment:
  OS: macOS High Sierra 10.13.6
  Node: 8.4.0
  Yarn: 0.27.5
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4
```

## Description
Anytime I run my app in android, I am presented with the error:
```
Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
getBoolean
    ReadableNativeArray.java:104
extractArgument
    JavaMethodWrapper.java:37
extractArgument
    JavaMethodWrapper.java:33
invoke
    JavaMethodWrapper.java:359
invoke
    JavaModuleWrapper.java:160
run
    NativeRunnable.java
handleCallback
    Handler.java:789
dispatchMessage
    Handler.java:98
dispatchMessage
    MessageQueueThreadHandler.java:29
loop
    Looper.java:164
run
    MessageQueueThreadImpl.java:192
run
    Thread.java:764
```

## Reproducible Demo
This is the code that is producing the error:
```java
@Override
  public boolean getBoolean(int index) {
    if (mUseNativeAccessor) {
      jniPassCounter++;
      return getBooleanNative(index);
    }
    return ((Boolean) getLocalArray()[index]).booleanValue();
  }
```

**Comment by spiritman110** [comment]
@react-native-bot: I am unable to test this as some of my other dependencies break when updating to v0.56.

**Comment by mckeowbc** [comment]
I think @spiritman110 and I have narrowed this down to something in react-native-google-signin. The arguments changed to GoogleSignin.hasPlayServices in a recent update. Using the old calling convention appears to be causing this Java error. Passing the new parameters got rid of the Java crash.

**Comment by dkfl1995** [comment]
@spiritman110  @mckeowbc Guys I have absolutely same error. Have a headache with this. It reproduces also on RN 0.56.0 (I have upgraded on it today).
 Please explain what it can be for me localize and fix this issue. It stops my sprint to be finished(

I also have react-native-google-signin. What should I do to go over this issue?

**Comment by mikrstic** [comment]
I used to call it with 
`hasPlayServices({ autoResolve: true })`

In v1.0.0-rc3 calling hasPlayServices has been changed. Not it says:
> hasPlayServices accepts one parameter, an object which contains a single key: showPlayServicesUpdateDialog (defaults to true).

So calling it with
`hasPlayServices()`
solves the issue.

**Comment by hramos** [comment]
Closing as this is a report for an older version....
