### ISSUE TITLE
[ListView] Touches callbacks do not work in ListView section headers [0.6.0v and higher]

### ISSUE THREAD

**Issue by MattFoley** [facebook/react-native#2075]
I have a few native modules that were working in 0.5.0v. As of 0.6.0v, and in both v0.7.0, v0.7.1 they no longer receive touches.

I'm overriding touchesBegan/Moved/Cancelled/Ended, and these methods are never called on any item rendered in a sectionHeader.

If I comment out [this method in RCTScrollView.h](https://github.com/facebook/react-native/blob/master/React/Views/RCTScrollView.m#L340), everything works just peachy. This method was introduced in 0.6.0v, so my guess is that this is the culprit. I am not sure what it was introduced for, so I'm not sure how best to fix it.

**Comment by sahrens** [comment]
@nicklockwood

**Comment by MattFoley** [comment]
I should add to this that once that method is removed, when a cell is scrolled behind a sticky header touches are then passed to the cell behind the section header, instead of the tappable item in the sticky header. This was the behavior in 0.5.0v as well.

**Comment by MattFoley** [comment]
It's been a little over a week since I opened this issue, @nicklockwood @brentvatne do you have any advice? This will be a blocking issue for me before too long. Thanks!

**Comment by browniefed** [comment]
Seems to be similar issue to #2166

**Comment by ide** [comment]
Merged into 0.10.0-rc.

**Comment by jaygarcia** [comment]
@vjeux @ide @nicklockwood , seems like this issue still exists, per this recent post: https://github.com/facebook/react-native/issues/3577

**Comment by ide** [comment]
@jaygarcia Looks a different issue, no? This issue was about the touch events not making their way to the event listeners.

**Comment by jaygarcia** [comment]
Thanks @ide. My head is a bit fuzzy arm -- dealing with a cold.
