### ISSUE TITLE
Metro bundler crashes when checking the NodeJS version (NodeJS <= 8.2.1)

### ISSUE THREAD

**Issue by keksipurkki** [facebook/react-native#20769]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
[skip envinfo]
Any environment where nodeJS version is less than 8.2.1.

## Description
The script `local-cli/server/checkNodeVersion.js`crashes with a `SyntaxError` when run with node versions older than [8.2.1](https://node.green/#ES2017-features-trailing-commas-in-function-syntax) due to the backwards-incompatible commas in function argument list. 

The expected behaviour is that the script shows the banner and prompts the developer to upgrade their NodeJS runtime. That is, the script itself has to be written in ES5.

I suspect you format your code programatically. It would be perhaps wise to adjust your style guide so that trailing commas in function argument lists are disallowed. See https://github.com/prettier/prettier/issues/2788.

**Comment by kelset** [comment]
> The expected behaviour is that the script shows the banner and prompts the developer to upgrade their NodeJS runtime

Can you submit a PR for that? Would be really helpful.

Aside from that, please fill the Env Info section.
