### ISSUE TITLE
iOS projects using pod manage always build failed

### ISSUE THREAD

**Issue by FaiChou** [facebook/react-native#20762]
My project was managed by pod, and if adding some other libraries will to `Libraries` folder not to `podfile`(some library don't include a `podspec`) , then build project, it will crash of `'React/RCT**.h' file not found`.

There is a way to solve this: **[creating own pod files](https://guides.cocoapods.org/making/making-a-cocoapod.html#the-pod-files)**

But if there is a very complex libraries that I don't know how to create a `podspec`. How to overcome this?

## Environment

Run `react-native info` in your terminal and paste its contents here.
Environment:
  OS: macOS High Sierra 10.13.6
  Node: 9.5.0
  Yarn: 1.7.0
  npm: 5.7.1
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.50.1 => 0.50.1

![image](https://user-images.githubusercontent.com/18500846/44378974-5d7b9f80-a536-11e8-8768-97a050d41b34.png)

**Comment by MrPluto** [comment]
it seems you are using both pod and react native link to manage third libs?
try to  check your react native linked third project's `header search path`  and see if this `${SRCROOT}/../../../ios/Pods/Headers/Public/\*\*` exists or not

**Comment by FaiChou** [comment]
@MrPluto  Thank you, build success after adding the `search path` to the third lib
