### ISSUE TITLE
multiple build target with custom styles, images, icon, app name,…

### ISSUE THREAD

**Issue by masoudltf** [facebook/react-native#20765]
In a react-native project we need to create multiple target with custom styles, images, icon, app name and application id. I know that we can define productFlavor in android gradle build tools and create multiple schemes in xcode for ios app, but it's only works for the app icon, app name and application id.

Unfortunately I couldn't find any solution for custom styles and custom images per target and the problem is still there.

Imagine this:

--assets
------**customer1**
------------_images_
------------_colors_
------------_styles_
------**customer2**
------------_images_
------------_colors_
------------_styles_
------**customer3**
------------_images_
------------_colors_
------------_styles_

It is the same application with exactly same functionalities, but each customer need to have the app with its own icon, images, styles and colors.

thanks for helping

**Comment by songxiaoliang** [comment]
@masoudltf How to solve, I configured productFlavors, but hit the apk, crash
