### ISSUE TITLE
[Docs] NS_ENUM exported to JS, used as method arguments for native modules, must use RCT_ENUM_CONVERTER in RCTConvert class extension

### ISSUE THREAD

**Issue by MattFoley** [facebook/react-native#2077]
I think this [section](https://facebook.github.io/react-native/docs/nativemodulesios.html#exporting-constants) of the docs needs to be further expanded to explain the use of `RCT_ENUM_CONVERTER`.

In v0.5.0, I was able to export NS_ENUM defined constants, and use them as method arguments. Example code below.

Enum Definition:
```objc
    typedef NS_ENUM(NSInteger, MyEnumType)
    {
        kEnumOne,
        kEnumTwo,
        kEnumThree,
    };
```
Constants:
```objc
    - (NSDictionary *)constantsToExport
    {
        return @{@"OnError": @{ @"enumOne" : @(kEnumOne),
                                @"enumTwo"  : @(kEnumTwo),
                                @"enumThree"   : @(kEnumThree)}
                      }
    };
```
Method Definition:
```objc
RCT_EXPORT_METHOD(doSomethingWithEnum:(MyEnumType)enum
                           completion:(RCTResponseSenderBlock)callback)
```

In v0.7.0, this failed with the following log:

    Unknown argument type 'MyEnumType' in method -[MyNativeModule
    doSomethingWithEnum:completion:]. Extend RCTConvert to support this type.

I was only able to puzzle the solution out after reading through the internal React Native code for quite some time. (Create a class extension for RCTConvert, use RCT_ENUM_CONVERTER to implement a converter method.)
```objc
    @implementation RCTConvert (MyEnumExtension)
    RCT_ENUM_CONVERTER(MyEnumType, (@{ @"enumOne" : @(kEnumOne),
                                       @"enumTwo"  : @(kEnumTwo),
                                       @"enumThree"   : @(kEnumThree)), 
                       kEnumOne, integerValue)
    @end
```

**Comment by brentvatne** [comment]
@MattFoley - thanks for the detailed description! If you can write up the docs for this and submit a PR I'll be happy to review, just ping me on it!

**Comment by MattFoley** [comment]
Will do, thanks @brentvatne.
