### ISSUE TITLE
TextInput text is undefined on blur in android

### ISSUE THREAD

**Issue by dmoss18** [facebook/react-native#20771]
- [ ] Review the documentation: https://facebook.github.io/react-native
  - [ ] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Environment:
  OS: macOS High Sierra 10.13.6
  Node: 10.3.0
  Yarn: 1.9.2
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: ^16.4.1 => 16.4.1
  react-native: 0.55.4 => 0.55.4

## Description
I have an `onBlur` handler for a TextInput that should pass in the text via the `nativeEvent`. However, the text is always undefined on android. It works on iOS.
```
handleBlur = (event: NativeSyntheticEvent<TextInputFocusEventData>) => {
  console.log(event.nativeEvent.text)
}

render() {
  return (
    <TextInput onBlur={this.handleBlur} value="Test" />
  )
}
```

## Reproducible Demo
https://snack.expo.io/By6uT3F87

**Comment by dmoss18** [comment]
This issue was originally reported [here](https://github.com/facebook/react-native/issues/16863) but they didn't really provide examples/follow the template.

**Comment by dmoss18** [comment]
I found a workaround [here](https://stackoverflow.com/a/47379303/683235)

`onEndEditing` instead of `onBlur` works exactly the same and provides the text

**Comment by dulmandakh** [comment]
IMHO, it's better to use onChangeText and store the text in the state, then access text from state. 

```jsx
handleBlur = () => {
  // access this.state.text
}

handleChangeText = text => {
  this.setState({ text })
}

render() {
  return (
    <TextInput onChangeText={this.handleChangeText} value={this.state.text} />
  )
}
```

**Comment by Elijen** [comment]
@dulmandakh Why did you close the issue though? The bug should still be fixed.
