### ISSUE TITLE
Error:Program type already present: bolts.AggregateException

### ISSUE THREAD

**Issue by roy2393** [facebook/react-native#20776]
I'm getting the above error  **Error:Program type already present: bolts.AggregateException** when I'm using 
**com.facebook.android:facebook-android-sdk:4.6.0** along **with com.facebook.react:react-native:+**

> React Native Environment Info:
>     System:
>       OS: Linux 4.15 Ubuntu 16.04.5 LTS (Xenial Xerus)
>       CPU: x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
>       Memory: 514.36 MB / 7.26 GB
>       Shell: 4.3.48 - /bin/bash
>     Binaries:
>       Node: 10.0.0 - ~/.nvm/versions/node/v10.0.0/bin/node
>       Yarn: 1.9.4 - /usr/bin/yarn
>       npm: 6.0.0 - ~/.nvm/versions/node/v10.0.0/bin/npm
>       Watchman: 4.7.0 - /usr/local/bin/watchman
>     IDEs:
>       Android Studio: 3.0 AI-171.4443003
>     npmPackages:
>       react: 16.4.1 => 16.4.1 
>       react-native: ^0.56.0 => 0.56.0 
>     npmGlobalPackages:
>       create-react-native-app: 1.0.0
>       react-native-cli: 2.0.1

**Comment by lechucan5** [comment]
React native bot
