### ISSUE TITLE
app crash on start with android 4.3, work good on >= 5.x 

### ISSUE THREAD

**Issue by alainib** [facebook/react-native#20781]
## Environment
 
  OS: Windows 10
  Node: 8.9.3
  Yarn: Not Found
  npm: 5.5.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: ^16.4.1 => 16.4.1
  react-native: ^0.55.4 => 0.55.4

## Description

I create an app who work good on android 5 and higher. today i wanted to test it on android 4.3 but the app crash on startup. not working on debug or release mode

## Reproducible Demo

I cannot share code because i don't know from where the bug come.

It get the error with adb : 

	W/dalvikvm( 4508): VFY:  rejected Lbr/com/classapp/RNSensitiveInfo/RNSensitiveInfoModule;.decryptWithAes (Ljava/lang/String;Lcom/facebook/react/bridge/Promise;Ljavax/crypto/Cipher;)V
	W/dalvikvm( 4508): Verifier rejected class Lbr/com/classapp/RNSensitiveInfo/RNSensitiveInfoModule;
	W/dalvikvm( 4508): threadid=18: thread exiting with uncaught exception (group=0x4174b700)
	E/AndroidRuntime( 4508): FATAL EXCEPTION: Thread-224
	E/AndroidRuntime( 4508): java.lang.VerifyError: br/com/classapp/RNSensitiveInfo/RNSensitiveInfoModule
	E/AndroidRuntime( 4508):        at br.com.classapp.RNSensitiveInfo.RNSensitiveInfoPackage.createNativeModules(RNSensitiveInfoPackage.java:20)
	E/AndroidRuntime( 4508):        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106)
	E/AndroidRuntime( 4508):        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1172)
	E/AndroidRuntime( 4508):        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1142)
	E/AndroidRuntime( 4508):        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1080)
	E/AndroidRuntime( 4508):        at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:113)
	E/AndroidRuntime( 4508):        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:911)
	E/AndroidRuntime( 4508):        at java.lang.Thread.run(Thread.java:841)
	W/ActivityManager(  688):   Force finishing activity org.plantnet/.MainActivity

Any advice are welcome
thanks

**Comment by hey99xx** [comment]
Your error is very likely an issue with RNSensitiveInfoModule class, not react-native framework itself. You should open the Github issue to https://github.com/mCodex/react-native-sensitive-info Btw your issue may be the same as https://github.com/mCodex/react-native-sensitive-info/issues/90

**Comment by dulmandakh** [comment]
Closing this issue, because as @hey99xx noted, this issue is not related to React Native.
