### ISSUE TITLE
[RCTImageDownloader] 0.8-rc crashes on iOS 7.1 when downloading Image

### ISSUE THREAD

**Issue by Fanghao** [facebook/react-native#2078]
Run the UIExplorer example on iOS 7.1 and choose Image for example. It will crash with following info:

2015-07-21 11:45:58.084 UIExplorer[28870:5707] -[__NSCFLocalDownloadTask rct_setCompletionBlock:]: unrecognized selector sent to instance 0x7f813a6907c0
2015-07-21 11:45:58.085 UIExplorer[28870:5707] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFLocalDownloadTask rct_setCompletionBlock:]: unrecognized selector sent to instance 0x7f813a6907c0'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010be25495 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010b3ef99e objc_exception_throw + 43
	2   CoreFoundation                      0x000000010beb665d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x000000010be16d8d ___forwarding___ + 973
	4   CoreFoundation                      0x000000010be16938 _CF_forwarding_prep_0 + 120
	5   UIExplorer                          0x000000010add53a5 -[RCTDownloadTaskWrapper downloadData:progressBlock:completionBlock:] + 181
	6   UIExplorer                          0x000000010adc77b7 __62-[RCTImageDownloader _downloadDataForURL:progressBlock:block:]_block_invoke27 + 1031
	7   libdispatch.dylib                   0x000000010e8f1851 _dispatch_call_block_and_release + 12
	8   libdispatch.dylib                   0x000000010e90472d _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x000000010e8f3dcf _dispatch_queue_drain + 481
	10  libdispatch.dylib                   0x000000010e8f3b94 _dispatch_queue_invoke + 112
	11  libdispatch.dylib                   0x000000010e8f49fc _dispatch_root_queue_drain + 81
	12  libdispatch.dylib                   0x000000010e8f4d12 _dispatch_worker_thread2 + 40
	13  libsystem_pthread.dylib             0x000000010ec4c6b3 _pthread_wqthread + 853
	14  libsystem_pthread.dylib             0x000000010ec4a40d start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by ssssssssssss** [comment]
This issue crashes our application on App Store, would be nice to get hot fix.

**Comment by urbanappetite** [comment]
I've just come across this one too, working on a hot fix but let me know if someone has something already.

**Comment by ssssssssssss** [comment]
Should be similar issue, here:
http://whoisryannystrom.com/2015/01/15/NSURLSessionTask-Debugging/

**Comment by urbanappetite** [comment]
Changing the category to NSURLSessionDownloadTask didn't work for me. I've got a hotfix I'm about to commit, it's not the nicest but for anyone who needs this now...it'll be up in 5.

**Comment by urbanappetite** [comment]
Let me know how it goes.

**Comment by ide** [comment]
Does this commit from today fix things? https://github.com/facebook/react-native/commit/09bb761b25a7cdf9f6332441c35fe7edf85e7088

**Comment by urbanappetite** [comment]
I imagine it would. Just ignore my pull request in that case.

**Comment by nicklockwood** [comment]
Fixed by https://github.com/facebook/react-native/commit/09bb761b25a7cdf9f6332441c35fe7edf85e7088
