### ISSUE TITLE
iOS: Cannot Use specific font weight of custom font

### ISSUE THREAD

**Issue by swissmanu** [facebook/react-native#20788]
## Environment
```
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
      Memory: 957.13 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 25.0.2, 25.0.3, 26.0.2, 27.0.3
        API Levels: 23, 25, 26, 27
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: 3.4.10 => 3.4.10
      @types/react: 16.3.5 => 16.3.5
      @types/react-native: 0.56.8 => 0.56.8
      react: 16.4.1 => 16.4.1
      react-native: 0.56.0 => 0.56.0
    npmGlobalPackages:
      react-native-git-upgrade: 0.2.7
```

### Scenario
To integrate a custom font to my `react-native` project, I followed the common known steps:

* add font files to `assets/font` directory (in my case OTF files)
* specify `rnpm` with its `assets` array in the `package.json`
* run `react-native link` to set things ready

### Expected Behavior
`react-native` uses correct font and weight when given specific `fontFamily`.

### Actual Behavior
The runtime uses the bold font weight, no matter what. I tried various combinations of `fontFamily`, `fontWeight` and `fontStyle`, the result is always the same:

<img width="243" alt="screen shot 2018-08-22 at 16 53 18" src="https://user-images.githubusercontent.com/170832/44471311-e6283780-a62b-11e8-83b8-16ea1df2b724.png">

### Analysis so far
* The OTF files are included correctly in the generated intermediate `.app` file
* Behavior is the same for an actual device and the simulator
* As soon as I include only one of the OTF files in the app bundle, that particular weight is available for rendering though.
* `react-native` uses `CALayer`s to render text, whereas the interface builder version of the app uses "real" `UILabel`s (see https://github.com/facebook/react-native/issues/20788#issuecomment-415300199 for screenshots)
* Renaming the font files as suggested by https://twitter.com/dan_tamas/status/1032548654861705216 does not change behavior (plays probably with Android... but this is another story ;) )
* Listing the available fonts using `[UIFont familyNames]`/`[UIFont fontNamesForFamilyName]` shows that the font is available to the app:

```
2018-08-23 11:22:18.158162+0200 fontproblem[83530:36797568] FreightSans Pro: (
    "FreightSansProBold-Regular",
    "FreightSansProBlack-Regular",
    "FreightSansProMedium-Regular",
    "FreightSansProSemibold-Regular",
    "FreightSansProLight-Regular",
    "FreightSansProBook-Regular"
)
```

* To ensure that there is no bug  due to the files themselves, I created a small demo within a "vanilla" iOS app using interface builder and `UILabel` instances; the font gets rendered correctly:

<img width="243" alt="screen shot 2018-08-22 at 16 52 47" src="https://user-images.githubusercontent.com/170832/44471365-05bf6000-a62c-11e8-8ac8-146f8f2822a5.png">

## Reproducible Demo
See https://github.com/swissmanu/react-native-fontproblem for demonstration.

**Comment by joelgetaction** [comment]
@swissmanu - I've seen issues with fonts myself and it's because I wasn't using the correct `Postscript Name` of the font, which may be different than the file name of the font and may also be different than the "human name/formal name" of the font.  You can see the actual Postscript name of the font in the FontBook app that comes with macOS.

For example, if I use `fontFamily: "SF Pro Text", fontWeight: "bold"` it doesn't work.  If I use the name of the file `SF-Pro-Text-Bold.otf` it also doesn't work.  But if I use just `fontFamily: SFProText-Bold` (with no `fontWeight`) it works perfectly.  I got `SFProText-Bold` as the Postscript Name from FontBook, see attached screenshot:

![screen shot 2018-08-22 at 12 28 41 pm](https://user-images.githubusercontent.com/40219063/44485887-efeb7400-a606-11e8-995c-9e15b2068517.png)


This may not help you but I thought I'd try to help out if I could.  :-)

**Comment by swissmanu** [comment]
Thx for your suggestion @joelgetaction. I already use the proper postscript name (see [demo here](https://github.com/swissmanu/react-native-fontproblem/blob/master/App.js#L20) for example) without any weights and stuff. Unfortunately, this doesn't work as any `fontFamily`/`fontWeight`/`fontStyle` combination does.

Here's a screenshot of fontbook for the record:

<img width="887" alt="screen shot 2018-08-23 at 07 46 48" src="https://user-images.githubusercontent.com/170832/44506905-c551f780-a6a8-11e8-9161-0401a3b2171f.png">

Something additional I recognized today: When inspecting the apps view hierarchy using Xcode, I can see that the "real" iOS application renders `UILabel`s, whereas the `react-native` one uses `CALayer` instead. Might be an implementation detail of `react-native`, though it could make a difference...? 🧐

![screen_shot_2018-08-23_at_07_51_41](https://user-images.githubusercontent.com/170832/44507107-a1db7c80-a6a9-11e8-870a-9e737237870a.png)

![screen_shot_2018-08-23_at_07_51_14](https://user-images.githubusercontent.com/170832/44507104-9e47f580-a6a9-11e8-813e-4dac67a8cde0.png)

**Comment by swissmanu** [comment]
after debugging my way through [RCTFont.mm](https://github.com/facebook/react-native/blob/master/React/Views/RCTFont.mm), i finally was able to dig down to the problem:

our font uses `-Regular` and `-Italic` suffix' in the postscript name to differentiate font style variations. [RCTFont.mm#L56](https://github.com/facebook/react-native/blob/master/React/Views/RCTFont.mm#L56) does a string based suffix check to detect a fonts weight.

[RCTFont.mm#L40](https://github.com/facebook/react-native/blob/master/React/Views/RCTFont.mm#L40) defines `regular` as weight, not as style. this made the whole font lookup mess things up.

we were able to get rid of the suffix in our font files and finally everything works smooth.

**Comment by panupongvmaqe** [comment]
@swissmanu - I also have the same problem, could you please advice me how do you get rid of suffix in the font files?

**Comment by swissmanu** [comment]
@panupongvmaqe phew, already thought we are the only ones here facing this problem 😅

you can approach this in two ways:

* 😇 right way: contact the font foundry where you bought the font and ask them to provide a version with the needed changes
* 🤩 quick way: use something like [Fontographer](https://old.fontlab.com/font-editor/fontographer/) and the postscript name accordingly

hope this helps.

**Comment by panupongvmaqe** [comment]
@swissmanu - Thanks you very much, I am able to see the font weight. Kudos to you for finding a way to solve this.
