### ISSUE TITLE
Compared with appgyver and more

### ISSUE THREAD

**Issue by RWOverdijk** [facebook/react-native#2080]
Hello,

Today I noticed this project and thought it might be interesting for us to use and contribute to. I do have a couple of questions I hope you could answer...

1. How much of this is actually native?
2. When is android support coming?
3. How does this compare to [AppGyver](http://www.appgyver.com/)?
4. How does this compare to [nativescript](https://github.com/NativeScript/NativeScript)?
5. How does one use native plugins for stuff like local push notifications, facebook login (heh :)) etc using react-native?
6. How much of the stuff being created by react-native is actually native?
7. Finally, perhaps a bit more react specific, is it possible to write the markup elsewhere? So not inside of the javascript code?

I must admit I didn't fully research all of these questions, but I was hoping they'd inspire whoever answers this to feed me with even more information.

Thanks!

**Comment by brentvatne** [comment]
Hi @RWOverdijk! Your enthusiasm is very welcome here, that said the issues are probably not the best place to ask these questions. Some quick answers for you below, hope it helps, please direct further questions to the irc channel #reactnative on Freenode or StackOverflow.

1. As much as you want it to be
2. http://www.reactnativeandroid.com/
3. React powered (huge win), Facebook backed, already deployed on large apps. Never used AppGyver.
4. React powered (huge win), Facebook backed, already deployed on large apps. Never used NativeScript, similar idea though (same goes for Titanium)
5. See other issues for push notifications, local notifications work but the API isn't great at the moment, we'll be improving soon. Remote push works fine at the moment. Facebook login: https://github.com/brentvatne/react-native-login or https://github.com/magus/react-native-facebook-login
6. Everything you see on the screen is native backed. Whether it is an actual native component or one built in JS by using native primitives depends.
7. Nope ;)

Best,
Brent

**Comment by RWOverdijk** [comment]
@brentvatne Thanks! I'll direct further questions (which I already have) to IRC tomorrow.

**Comment by browniefed** [comment]
@RWOverdijk there is additionally https://discuss.reactjs.org/ which may be of some help.

**Comment by brentvatne** [comment]
And previous issues of http://brentvatne.ca/react-native-newsletter
And https://github.com/ericvicenti/react-native-community (although not entirely kept up to date)
And https://www.youtube.com/results?search_query=react+native
