### ISSUE TITLE
iOS: NetInfo.isConnected returns always false (still)

### ISSUE THREAD

**Issue by assafb81** [facebook/react-native#20804]
## Environment
OS: win 8.1 / Sierra 10.13.6
Node: 8.11.3
Yarn: 6.3.0
npm:6.3.0
Android Studio: 3.1.0.0
XCode: 9.4.1

React: 16.3.1
React-native: 0.55.4

## Description
Hi @hramos I've opened new issue about this, since #8615 is closed.
This issue still open also in RN version 0.56

## My Working Workaround
As I wrote in my comment - > https://github.com/facebook/react-native/issues/8615#issuecomment-394715447

- my `api.js` file:

```
import { NetInfo } from 'react-native';
import { url } from '[AppName]/src/config';

export const onInitialNetConnection = () => {
    NetInfo.isConnected.removeEventListener(onInitialNetConnection);
};

const getDataById = async (dataId) => {
    // both now work on the first call.
    await NetInfo.getConnectionInfo();
    const isConnected = await NetInfo.isConnected.fetch();
    if (!isConnected) {
        throw new Error('networkError');
    }
    const response = await fetch(`${url}${dataId}`, {
        headers: {
            'Cache-Control': 'no-cache, no-store, must-revalidate',
            Pragma: 'no-cache',
            Expires: 0,
        },
    });
    if (response.ok) {
        return response.json();
    }
    throw new Error('invalidCode');
};

export default getDataById;
```

- my `App.js` file
```
NetInfo.isConnected.addEventListener(
            'connectionChange',
            onInitialNetConnection,
        );
```

**Comment by nol13** [comment]
Also, the partial fix in 55.4 actually broke the workaround we're using to get the connectionChange listeners to work reliably, which don't think the above workaround helps with.

Really annoying to test/replicate though, was only happening on real device, and even then only every day or so after numerous connection changes, usually right after unlocking.
