### ISSUE TITLE
Settings is not yet supported on Android

### ISSUE THREAD

**Issue by RohanChawla01** [facebook/react-native#20814]
## Environment
Environment:
  OS: Linux 4.4
  Node: 8.11.4
  Yarn: 1.7.0
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.4.1 => 16.4.1
  react-native: 0.54.4 => 0.54.4

## Description
As written in official react-native docs(https://facebook.github.io/react-native/docs/settings), i used Settings.set and Settings.get in my app, but it works for ios and not for android. I went through the git-hub code for Settings.js file (Libraries/Settings/Settings.android.js) where mentioned as a warning "Settings is not yet supported for Android".

I have a use case in my app where i can't wait for a promise, so i cannot use AsyncStorage.

**Comment by hramos** [comment]
Thanks for bringing this up. It looks like a docs issue. Can you report this to https://github.com/facebook/react-native-website? A PR would be ideal.

**Comment by RohanChawla01** [comment]
@hramos Thanks for the response. Can you please let me know how i can achieve this functionality in Android?

**Comment by hramos** [comment]
Probably best to ask elsewhere - we're only tracking issues in this repo.
