### ISSUE TITLE
PushNotificationIOS.requestPermissions never resolves in RN 0.56.0

### ISSUE THREAD

**Issue by jongirard** [facebook/react-native#20821]
- [ √ ] Review the documentation: https://facebook.github.io/react-native
  - [ √ ] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ √ ] Use the latest React Native release: https://github.com/facebook/react-native/releases

(Related issue marked as fixed but problem still exists: https://github.com/facebook/react-native/issues/9105)

## Environment

```React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.5
      CPU: x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 29.44 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.5.0 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.1.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
    IDEs:
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

## Description
As per the React Native documentation, `PushNotificationIOS.requestPermissions` method should return a promise to wait for user input, but nothing is ever returned. I've also tried adding an event listener in `componentWillMount` like `PushNotificationIOS.addEventListener('register', (token) => {});` which also does not resolve the requestPermissions promise.

## Reproducible Demo
`PushNotificationIOS.requestPermissions().then((permissions) => console.log(permissions));`

**Comment by Titozzz** [comment]
iOS Apps can only ask once for permission with the system UI and you can't really know if that code will resolve. Some library such as react native permission store a value to remember if you already asked.

**Comment by jyurek** [comment]
Whether the function asks for permission is immaterial. As @jongirard mentioned, [from the docs](https://facebook.github.io/react-native/docs/pushnotificationios#requestpermissions): "This method returns a promise that will resolve when the user accepts, rejects, or if the permissions were previously rejected. The promise resolves to the current state of the permission."

It should always resolve or reject.

This is still happening in 0.57.0

**Comment by cpojer** [comment]
This issue has been moved to react-native-community/react-native-push-notification-ios#7.
