### ISSUE TITLE
Unable to resolve module `ProgressBarAndroid` 

### ISSUE THREAD

**Issue by intothefantasy** [facebook/react-native#20831]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Environment:
  OS: Windows 10
  Node: 10.9.0
  Yarn: Not Found
  npm: 6.2.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.1.0.0 AI-173.4907809

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

## Description
Unable to resolve module `ProgressBarAndroid` for my new react-native project

## Reproducible Demo
i am currently using my previous project package.json and here it is

> {
  "name": "yuyuteiAPK",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "rc-start": "npm start -- --reset-cache",
    "clean": "rm -rf $TMPDIR/react-* && watchman watch-del-all && npm cache clean",
    "clean-start": "npm run clean && npm run rc-start",
    "fresh-install": "rm -rf $TMPDIR/react-* && watchman watch-del-all && rm -rf ios/build/ModuleCache/* && rm -rf node_modules/ && npm cache clean && npm install",
    "fresh-start": "npm run fresh-install && npm run rc-start",
    "tron": "node_modules/.bin/reactotron"
  },
  "dependencies": {
    "babel-loader": "^7.1.5",
    "babel-preset-react": "^6.24.1",
    "dot-prop-immutable": "^1.4.0",
    "native-base": "^2.7.2",
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-easy-grid": "^0.2.0",
    "react-native-elements": "^0.19.1",
    "react-native-modal-dropdown": "^0.6.2",
    "react-native-multiple-select": "^0.4.4",
    "react-native-router-flux": "^4.0.1",
    "react-native-sectioned-multi-select": "^0.5.2",
    "react-native-ultimate-listview": "^3.3.0",
    "react-native-vector-icons": "^5.0.0",
    "react-navigation": "^2.11.2",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0",
    "redux-thunk": "^2.3.0"
  },
  "devDependencies": {
    "babel-jest": "23.2.0",
    "babel-preset-react-native": "4.0.0",
    "jest": "23.2.0",
    "react-test-renderer": "16.3.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
> 

i have try to not use this package.json as well for my new created project but i still hit the same error as this. Previously, my 1st project did not hit this error tho. Please help me in this

**Comment by intothefantasy** [comment]
resolved it by typing this

npm start -- --reset-cache

and then

react-native run-android

**Comment by charpeni** [comment]
It looks like it was a caching issue, glad to know it's now resolved.

Let's close this issue.
