### ISSUE TITLE
[CI] Fix build problem in master branch

### ISSUE THREAD

**Issue by gengjiawen** [facebook/react-native#20845]
It looks like it caused by buck miss config. I am not familiar with buck, so there is little I can help. With green ci we can catch bug like this early https://github.com/facebook/react-native/issues/20844.

@hramos Can you find some time to turn on appveyor on this project. Thanks.

**Comment by hramos** [comment]
Looks like this was only enabled for hramos/react-native. I'm asking for someone with the right access to enable this for facebook/react-native.
