### ISSUE TITLE
[ListView] 0.8-rc stickyHeaderIndices、removeClippedSubviews bug

### ISSUE THREAD

**Issue by cssoul** [facebook/react-native#2085]
when I use ListView to creat a trade activity, I meet some troubles about stickyHeaderIndices、removeClippedSubviews property.

![demo](https://github.com/cssoul/react-native-trade/raw/master/demo1/demo.jpg)

This is demo, Please check this out.
[https://github.com/cssoul/react-native-trade/tree/master/demo1](https://github.com/cssoul/react-native-trade/tree/master/demo1)

**Comment by cssoul** [comment]
today ,I white another demo,use ListView nesting in ScrollView, but it also has some troubles.

[https://github.com/cssoul/react-native-trade/tree/master/demo2](https://github.com/cssoul/react-native-trade/tree/master/demo2)

**Comment by ide** [comment]
Could you test with 0.8.0-rc.2? If the issue goes away that will tell us that the problem is related to a perf optimization that was reverted.

**Comment by cssoul** [comment]
I test with 0.8.0-rc.2, but still have this problem. We use a lot of this
layout,so I hope you can fix this bug.
Thanks for your attention.

2015-07-23 2:50 GMT+08:00 James Ide <notifications@github.com>:

> Could you test with 0.8.0-rc.2? If the issue goes away that will tell us
> that the problem is related to a perf optimization that was reverted.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/react-native/issues/2085#issuecomment-123825251>
> .
>



-- 
 /****************************************************

From  ：张军
旺旺ID：黑幕困兽
E-mail：hbjszj@gmail.com

*****************************************************/

**Comment by browniefed** [comment]
@cssoul is this still happening as of .11-rc?

**Comment by cssoul** [comment]
When I have time, try it. ）：

2015-09-14 5:39 GMT+08:00 Jason Brown <notifications@github.com>:

> @cssoul <https://github.com/cssoul> is this still happening as of .11-rc?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/react-native/issues/2085#issuecomment-139920344>
> .
>



-- 
 /****************************************************

From  ：张军
旺旺ID：黑幕困兽
E-mail：hbjszj@gmail.com

*****************************************************/

**Comment by cssoul** [comment]
0.11.0-rc,  it's still have some problem

**Comment by cssoul** [comment]
I upgrade to 0.11.0-rc today, it's still have some problem.

2015-09-16 10:40 GMT+08:00 张军 <hbjszj@gmail.com>:

> When I have time, try it. ）：
>
> 2015-09-14 5:39 GMT+08:00 Jason Brown <notifications@github.com>:
>
>> @cssoul <https://github.com/cssoul> is this still happening as of .11-rc?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/facebook/react-native/issues/2085#issuecomment-139920344>
>> .
>>
>
>
>
> --
>  /****************************************************
>
> From  ：张军
> 旺旺ID：黑幕困兽
> E-mail：hbjszj@gmail.com
>
> *****************************************************/
>



-- 
 /****************************************************

From  ：张军
旺旺ID：黑幕困兽
E-mail：hbjszj@gmail.com

*****************************************************/

**Comment by brentvatne** [comment]
Hey @cssoul - is this still a problem?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/listview-08-rc-stickyheaderindicesremoveclippedsubviews-bug

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
