### ISSUE TITLE
Image crashes app on release build Android (with crashreport)

### ISSUE THREAD

**Issue by rendomnet** [facebook/react-native#20858]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.4
      CPU: x64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
      Memory: 20.95 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.9.1 - ~/.nvm/versions/node/v8.9.1/bin/node
      Yarn: 1.9.4 - ~/.nvm/versions/node/v8.9.1/bin/yarn
      npm: 6.1.0 - ~/.nvm/versions/node/v8.9.1/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 23.0.3, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.3
        API Levels: 23, 25, 26, 27
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1
      react-native: 0.56.0 => 0.56.0
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

## Description

When I run my app in debug mode
Everything **works** fine.

But when I make a signed apk using

    react-native run-android --variant=release

It will run okay until it will encounter Image with source like this. The app will just crash, with only restart button:

    <Image source={{uri: "https://upload.wikimedia.org/wikipedia/commons/3/30/Googlelogo.png"}} />

But with source like this it will NOT have any error

    <Image source={{uri: "https://facebook.github.io/react-native/docs/assets/favicon.png"}} />

This error happens when <Image /> is inside FlatList and with some Images in a single <Image > element 
With some images removing resizeMode helps but then it breaks if I put this image inside FlatList.

This error happens only in release build. 
on iOS release works no Image bugs.

**Comment by vladrozhnev** [comment]
Hello, @rendomnet! I was got the same issue. In my side, it was solved by adding `android:largeHeap="true"` string to the `application` tag at the `AndroidManifest.xml`. Maybe, it will help you.

It should look like:
```
<application
  android:largeHeap="true"
  android:name=".MainApplication"
  android:label="@string/app_name"
  android:icon="@mipmap/ic_launcher"
  android:allowBackup="false"
  android:theme="@style/AppTheme">
```
