### ISSUE TITLE
Hot Reloading is not working when using inheritance

### ISSUE THREAD

**Issue by csdwd** [facebook/react-native#20866]
- [x ] Review the documentation: https://facebook.github.io/react-native
  - [x ] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
 React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
      Memory: 364.79 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.7.0 - /usr/local/bin/node
      Yarn: 1.9.2 - /usr/local/bin/yarn
      npm: 6.3.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 28.0.1
        API Levels: 23, 25, 26, 28
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 
    npmGlobalPackages:
      react-native-cli: 2.0.1
## Description
1. Create a new project
2. Create a bass class ,call it BaseComponent and `extends Component` (from react)
3. Change the App.js file to `extends BaseComponent`
4. Enable Hot Reloading
5. Make changes to the App.js, like editing the text. The change doesn't appear in the device.

**Comment by gaearon** [comment]
React Native 0.61 includes a complete reimplementation of this mechanism called Fast Refresh. It's not out yet as stable, but you can already try [React Native 0.61 RC 3](https://twitter.com/grabbou/status/1171472333313175552).
