### ISSUE TITLE
[v0.57.0-rc.3] Expected MIME-Type to be 'application/javascript' or 'text/javascript', but got 'application/octet-stream'.

### ISSUE THREAD

**Issue by tn0502** [facebook/react-native#20875]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
      Memory: 226.60 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.4 - /usr/local/opt/node@8/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/opt/node@8/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
```
## Description
We are currently preparing for React Native 0.57, upgrading from 0.56. With `v0.57.0-rc.3`, we keep getting this error message while trying to load from the dev server: `Expected MIME-Type to be 'application/javascript' or 'text/javascript', but got 'application/octet-stream'.`

I've tried looking into it and I'm not sure what's changed other than the metro version bump. With the latest version, "Content-Type" is now set using `mime-types` package. I don't know if this has always been the case, but we've never hit this issue before. Our output bundle is `index.mobile.bundle`, so it makes sense that `mime-types` is unable to resolve it, seeing as it simply uses a lookup table to map extensions to MIME types.

To make things work, I've added a workaround in React Native like this:
```diff
diff --git a/React/Base/RCTJavaScriptLoader.mm b/React/Base/RCTJavaScriptLoader.mm
index 983555dbd1..a31583737d 100755
--- a/React/Base/RCTJavaScriptLoader.mm
+++ b/React/Base/RCTJavaScriptLoader.mm
@@ -281,9 +281,12 @@ static void attemptAsynchronousLoadOfBundleAtURL(NSURL *scriptURL, RCTSourceLoad
     }

     // Validate that the packager actually returned javascript.
+    NSData *signature = [NSData dataWithBytes:"var __DEV__=true" length:16];
+    NSRange signatureMatch = [data rangeOfData:signature options:0 range:NSMakeRange(0, signature.length)];
     NSString *contentType = headers[@"Content-Type"];
     NSString *mimeType = [[contentType componentsSeparatedByString:@";"] firstObject];
-    if (![mimeType isEqualToString:@"application/javascript"] &&
+    if (signatureMatch.location != 0 &&
+        ![mimeType isEqualToString:@"application/javascript"] &&
         ![mimeType isEqualToString:@"text/javascript"]) {
       NSString *description = [NSString stringWithFormat:@"Expected MIME-Type to be 'application/javascript' or 'text/javascript', but got '%@'.", mimeType];
       error = [NSError errorWithDomain:@"JSServer"
```
But as you can see, it's far from ideal.

**Comment by kelset** [comment]
quick random questions to try and understand what could have caused it:
1. does it happen for both iOS and Android runs? (since you post there a workaround for iOS, right?)
1. have you tried `rc0` and `rc2`? (we did some massive cherry picks in between)
1. does it also happens with a fresh project (I think you can use `react-native init --version="0.57.0-rc.3" testVersion`) or only your implementation?

**Comment by tn0502** [comment]
Thanks for looking into this, @kelset :)

1. I've not been able to compile Android as I keep getting: `Could not find com.facebook.react:react-native:0.57.0-rc.3`. I can report back if I figure out what's wrong…
2. This repros on both `rc0` and `rc2`.
3. A fresh React Native app fails if I rename `index.js` to `index.bundle`. But _not_ if renamed to `index.jsbundle`. Afaics, `.jsbundle` is not in `mime-db` so it's being special-cased somwehere.

**Comment by tn0502** [comment]
An update on 1: Android does not hit this issue because it tries to load `index.js` instead of our bundle. When I tried to do the same for iOS, I'm getting all sorts of errors.

**Comment by tn0502** [comment]
Another update: I tried using `RCTBundleURLProvider` and it correctly creates the URL but we still hit the issue.
```objc
[RCTBundleURLProvider.sharedSettings jsBundleURLForBundleRoot:@"index.mobile"
                                             fallbackResource:nil];
```

**Comment by tn0502** [comment]
I think I know what happened. Something has changed that makes the Metro bundler look for files on disk before letting React Native (?) resolve the URL. This used to be the other way around. Since our configuration outputs the bundle to `index.mobile.bundle`, which happens to be the same magic word that starts the bundle process, Metro will serve the file instead. We can rename the bundle on our side to avoid this issue. Sorry for the noise.

@kelset Thanks for looking at this issue! Would like to keep this open or close it? I don't think we'd mind either way at this point.

**Comment by kelset** [comment]
Hey Tommy thanks for keeping the issue updated!

I think that this may be closed, but I don't know if this behaviour

> Something has changed that makes the Metro bundler look for files on disk before letting React Native (?) resolve the URL. 

would require a dedicated issue on the Metro repo. What do you think?

**Comment by tn0502** [comment]
I think I will file an issue there just to see if it's intended behaviour. Thanks for your help.

**Comment by tdinckaya** [comment]
hello,
you will main.jsbundle change to main.js :)
