### ISSUE TITLE
[WebView] startInLoadingState Causes page Scaling to Fail

### ISSUE THREAD

**Issue by MossP** [facebook/react-native#2087]
If a page requires scaling and `startInLoadState={true}` then the page will load larger than the screen size. Setting this to `{false}` fixes the error. I have created an example over at RNPlay.org

https://rnplay.org/apps/1PCy0Q

**Comment by browniefed** [comment]
@MossP is this still happening in .11-rc?

**Comment by MossP** [comment]
Yeah, this is still happening. I've changed the URL in the RNPlay to another (as apple have since remade their site) and can still trigger the bug in the same way.

**Comment by jasonmerino** [comment]
I ran into this yesterday with trying to load up the UPS tracking site (which apparently they don't have a mobile site for). I'm running 0.11.0 stable currently.

**Comment by miduga** [comment]
Same for me. I've noticed it today as well using 0.11.1.

**Comment by plrthink** [comment]
Same for me on 0.11.0

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/webview-startinloadingstate-causes-page-scaling-to-fail

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.

**Comment by WaterEye0o** [comment]
@MossP Did you solve this problem ,I now version is 0.35 found that the problem still exists.

**Comment by MossP** [comment]
@WaterEye0o No, I don't believe I did. I just settled with loading it in `startInLoadState={false}`

**Comment by WaterEye0o** [comment]
oh no,really unfortunate answer. Have you ever seen the reason for this bug? @MossP

**Comment by MossP** [comment]
Sorry, no @WaterEye0o. I was very new to ReactNative when I came across the bug and didn't have the knowledge to effectively hunt it down.

**Comment by jaunesarmiento** [comment]
I'm on RN 0.40 and it's still happening. Trying to load a Typeform breaks its layout.

**Comment by redtailjere** [comment]
On 0.50.3 and this is still happening. It would be great to get some momentum on this as this disallows me from using WebView's renderLoading functionality.

**Comment by rsommerard** [comment]
I have the same issue with react 0.52.
If I use the `startInLoadState`, the loaded website is not well scaled. When I change the device orientation and go back, the website comes with the good scale.
I also tried to load the website without the attribute `startInLoadState`, in this case, the website scale well.
