### ISSUE TITLE
trying to use matrix-js-sdk

### ISSUE THREAD

**Issue by moeinrahimi** [facebook/react-native#20872]
- [ ] Review the documentation: https://facebook.github.io/react-native
  - [ ] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
 React Native Environment Info:
    System:
      OS: Windows 10
      CPU: x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
      Memory: 962.29 MB / 7.86 GB
    Binaries:
      Yarn: 1.1.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 5.3.0 - C:\Program Files\nodejs\npm.CMD
      Watchman: 4.9.4 - C:\watchman\watchman.EXE
    IDEs:
      Android Studio: Version  2.2.0.0 AI-145.3276617

## Description
so basically i'm trying to use a library named matrix-js-sdk , it is working fine on another project built react itself , but on react-native when i require the library i get below error message  ,  the mentioned issue page in error message didin't help . and also if it helps this is my issue page on matrix-js-sdk repo 
https://github.com/matrix-org/matrix-js-sdk/issues/657

error: bundling failed: Error: Unable to resolve module events from
F:\projec ts\myApp\node_modules\matrix-js-sdk\lib\models\event.js:
Module events does n ot exist in the Haste module map

This might be related to facebook/react-native#4968
To resolve try the following:

Clear watchman watches: watchman watch-del-all.
Delete the node_modules folder: rm -rf node_modules && npm install.
Reset Metro Bundler cache: rm -rf /tmp/metro-bundler-cache-* or npm star t -- --reset-cache. 4. Remove haste cache: rm -rf /tmp/haste-map-react-native -packager-*.
at ModuleResolver.resolveDependency (F:\projects\myApp\node_modules\metro\sr c\node-haste\DependencyGraph\ModuleResolution.js:161:1460)
at ResolutionRequest.resolveDependency (F:\projects\myApp\node_modules\metro \src\node-haste\DependencyGraph\ResolutionRequest.js:91:16)
at DependencyGraph.resolveDependency (F:\projects\myApp\node_modules\metro\s rc\node-haste\DependencyGraph.js:272:4579)
at dependencies.map.relativePath (F:\projects\myApp\node_modules\metro\src\D eltaBundler\traverseDependencies.js:376:19)
at Array.map ()
at resolveDependencies (F:\projects\myApp\node_modules\metro\src\DeltaBundle r\traverseDependencies.js:374:16)
at F:\projects\myApp\node_modules\metro\src\DeltaBundler\traverseDependencie s.js:212:33
at Generator.next ()
at step (F:\projects\myApp\node_modules\metro\src\DeltaBundler\traverseDepen dencies.js:297:313)
at F:\projects\myApp\node_modules\metro\src\DeltaBundler\traverseDependencie s.js:297:473

## Reproducible Demo
Let us know how to reproduce the issue. Include a code sample, share a project, or     share an app that reproduces the issue using https://snack.expo.io/. Please follow the guidelines for providing a MCVE: https://stackoverflow.com/help/mcve

**Comment by dulmandakh** [comment]
Please check if matrix-js supports React Native, and refer to its documentation.
