### ISSUE TITLE
500 internal server Error when using react-native run-android

### ISSUE THREAD

**Issue by ngohungphuc** [facebook/react-native#20885]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
Environment:
  OS: Windows 10
  Node: 8.11.4
  Yarn: 1.9.4
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.1.0.0 AI-173.4907809

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.56.0 => 0.56.0
```
## Description
![image](https://user-images.githubusercontent.com/13591213/44708011-368e1200-aad0-11e8-99ee-dfdb5fd4e856.png)

**Comment by ps0305** [comment]
try deleting node_modules and clearing cache ,then install dependencies and run the bundle.If issue not resolved after all this, then try to deprecate the react-native version according to codes and syntax you have used, hope that will fix the issue.

**Comment by ngohungphuc** [comment]
try all method you mention the errors still occured

**Comment by gengjiawen** [comment]
please use 0.57.rc3.

**Comment by ngohungphuc** [comment]
Please open again. I'm havent verify it yet.

**Comment by gengjiawen** [comment]
actually this is duplicate, you can search the issue.
