### ISSUE TITLE
[Borders] Lines visible with borderRadius, borderWidth and borderColor

### ISSUE THREAD

**Issue by jeanregisser** [facebook/react-native#2089]
There's a rendering issue when using `borderRadius`, `borderWidth` and `borderColor`, you see lines appearing between each border:

<img width="209" alt="screen shot 2015-07-22 at 14 22 01" src="https://cloud.githubusercontent.com/assets/57791/8825235/c45cf7e8-307d-11e5-9648-7235f757d84b.png">

The above image was produced with the following code on the latest master (75b220d6cee2d2ccda25f420628454cf198e5466), same happens with the latest released version (0.7.1):

```jsx
'use strict';

var React = require('react-native');
var {
  AppRegistry,
  StyleSheet,
  Text,
  View,
} = React;

var SampleApp = React.createClass({
  render: function() {
    return (
      <View style={styles.container}>
        <View style={styles.circle}/>
      </View>
    );
  }
});

var styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  circle: {
    width: 100,
    height: 100,
    borderRadius: 50,
    borderWidth: 20,
    borderColor: 'green',
  },
});

AppRegistry.registerComponent('SampleApp', () => SampleApp);
```

**Comment by browniefed** [comment]
Yep, this is reported here #2017

**Comment by browniefed** [comment]
You can possibly accomplish the same with 2 circles? https://rnplay.org/apps/dhvHVw

**Comment by ide** [comment]
This looks different than #2017. My initial guess is that this is a bug w Facebook rendering while 2017 is about apple rendering.

**Comment by a2** [comment]
The visible lines are due to the anti-aliasing when drawing the four trapezoids for the border. Not quite sure how to make them less visible without drawing the image at an unnecessarily larger scale and downsizing the image to be drawn.

**Comment by rjoonas** [comment]
Another example of rendering glitches that appear when using both border width and border radius on React Native 0.14.2:

Screenshot | Code
--------------- | -------------
![img_0003](https://cloud.githubusercontent.com/assets/1095425/11206352/3707d790-8d17-11e5-9c42-8840eb72f478.png) | `<View style={{ backgroundColor: '#e6e6e6', borderWidth: 1, width: 70, height: 70, borderTopLeftRadius: 10 }}></View>`
![img_0004](https://cloud.githubusercontent.com/assets/1095425/11206356/3db13a14-8d17-11e5-9c9b-2d6aa87de228.png) | `<View style={{ backgroundColor: '#e6e6e6', width: 70, height: 70, borderTopLeftRadius: 10 }}></View>`

This glitch is only visible when I run the app on my device, not in iOS simulator.

**Comment by brentvatne** [comment]
Fixed in https://github.com/facebook/react-native/commit/b115277d00f54fa7af5d61062c9e3cf362b7c5da
