### ISSUE TITLE
TextInput capitalized all letter i's when there's an emoji before the text

### ISSUE THREAD

**Issue by dchersey** [facebook/react-native#20908]
- [x ] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
      Memory: 705.27 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 9.11.1 - ~/.nvm/versions/node/v9.11.1/bin/node
      Yarn: 1.9.2 - /usr/local/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v9.11.1/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 23.0.2, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.3, 27.0.0, 27.0.3, 28.0.0
        API Levels: 23, 24, 25, 26, 27
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description
TextInput capitalizes all letter I's within words when there's an emoji to the left of the characters and you are editing in the middle of a sentence. 

See #19389 for more context

## Reproducible Demo
When you have an emoji as the last character of your text input and then move the text cursor back (still with emoji as last character) and enter new letters somewhere in the middle of the string. It only capitalizes the letter i.  This also happens if you start your text with an emoji, then type some words, then go back in and start editing text; all i's will be capitalized, even in the middle of words.

**Comment by Balasnest** [comment]
**Facing everywhere in textInput component.** I tried adding **autoCaptialize = {none}** with some of the textInput. It seems to be working. _**But all the i's letter are caps still**_. 

Is there any way to fix without updating / changing react native version ?
```Environment:
  OS: macOS High Sierra 10.13
  Node: 8.9.4
  Yarn: 1.3.2
  npm: 4.6.1
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.54.4 => 0.54.4

**Comment by superandrew213** [comment]
Having this issue too in IOS since updating to RN0.56.

Also when enabling multiline and there is an emoji in the text:
  - All letters go all caps sometimes.
  - Adding new lines behaves glitchy when there is an emoji and it is out of view.
  - Auto correct suggestions also don't match the word being typed sometimes

Upgraded to RN0.57 and the issue is still there.

**Comment by Balasnest** [comment]
Anybody get solution for this?

**Comment by petekp** [comment]
We've received reports about this issue from our users — we're on RN 0.55. It's difficult to reproduce but seems to occur mostly around the letter `i` which begins to automatically capitalize when editing text or entering a new word between existing words. It's possible to get into a state where all subsequently entered words are capitalized automatically.

```jsx
<PATextInput
 multiline
 autoCapitalize="sentences"
 autoCorrect
 spellCheck
 autoGrow
 style={styles.messageInput}
 value={this.state.input}
 placeholder={inputPlaceholderText}
 onChangeText={input => this.setState({ input })}
/>
```

**Comment by TheRohitSharma** [comment]
@petekp Have you seen any progress regarding this issue? Our users have reported it as well, and I can reproduce it by ending a sentence with a period and then a space, and then going back to the middle of some text and typing. Every letter comes out capitalized.

**Comment by dchersey** [comment]
We've had this patch in production for a while; it definitively solved the issue. Patch is relatative to RN 0.57+.
https://github.com/facebook/react-native/issues/21243#issuecomment-435040610

The associated PR has been merged to master ... no info on when it will be released though.

**Comment by DISKONEKTeD** [comment]
I'm running React 59.10 and I have been receiving reports of people having this issue (regardless of emoji). I was on 57 previously. Did not have this issue prior.
