### ISSUE TITLE
IOS  Native  交互 浮点型精度丢失 问题

### ISSUE THREAD

**Issue by LinberDuan** [facebook/react-native#20907]
hello!
我在项目中 Native代码 与 React Native 调用，传递浮点型数值时， React Native 层出现精度丢失问题。
调用 方式：
RCT_EXPORT_METHOD(post:(NSString *)url
                  content:(NSDictionary*)content
                  callback:(RCTResponseSenderBlock)callback);

Native 传递 0.00003  ， React Native  收到的是  0.000030000000000004  。
请问该怎样避免这个问题呢？

**Comment by elanpang** [comment]
这个是js的锅，不怪rn，你在js层计算要么tofixed一下，要么用第三方的lib来做精确计算。
