### ISSUE TITLE
[Navigator] Overscrolling a ScrollView in a FloatFromBottom scene should pop route

### ISSUE THREAD

**Issue by oblador** [facebook/react-native#2090]
I'm trying to replicate the behavior in the Facebook Groups app. When tapping a group which opens as a modal that is pushed from the bottom, I can close it by swiping downwards anywhere as long as the scrollview is scrolled to the top. 

The Navigator component has a similar behavior when using `Navigator.SceneConfigs.FloatFromBottom`, but then you are required to swipe the upper part of the screen. If you're using iPhone 6+ this is quite a stretch and you're likely to access the notification center instead of closing which is quite annoying.

**Comment by brentvatne** [comment]
[Check this out](https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/Navigator/NavigatorSceneConfigs.js#L417-L431) - you can implement your own like this and try using `bottom-to-top` instead of `top-to-bottom` for the gesture. Let me know if you have any luck with that!

**Comment by ide** [comment]
+1 @brentvatne

Look at how existing scene configs are written and write / publish your own!

**Comment by oblador** [comment]
I don't really follow how I should be able to do it, I've read the code you linked to before but as far as I understand this config is responsible for popping the route via swiping the upper part down: 

```
    gestures: {
      pop: {
        ...BaseLeftToRightGesture,
        edgeHitWidth: 150,
        direction: 'top-to-bottom',
        fullDistance: SCREEN_HEIGHT,
      }
    },
```

I could change the `edgeHitWidth` to `SCREEN_HEIGHT` but then I'd guess any downward swipe would pop the route and thus rendering the scroll view unusable. What I'm trying to do is when my route has a scroll view, I should be able to pop the route by overscrolling like it works in the groups app. Not sure if I'm being unclear or stupid haha. Would a screencast of the groups app help?

Also, how can I define multiple gestures to pop? For example, viewing an image in a "modal" scene I might want to pop it by swiping both up or down like it works in the main Facebook app.  Maybe I should just try with an array, but it's never seen in the SceneConfigs.

**Comment by ericvicenti** [comment]
This use case is very tricky because of interactions with the ScrollView. We are working on enhancing our the ScrollView to play nicer with the JS touch responder system. Until then it may not be possible to do this with Navigator. This use-case is absolutely on our minds, and we should be able to support it pretty soon.

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/navigator-overscrolling-a-scrollview-in-a-floatfrombottom-scene-should-pop-route
