### ISSUE TITLE
undefined is not a function (evaluating '_iterator2[typeof Symbol === "function" ? Symbol.iterator : "@@iterator"]()'

### ISSUE THREAD

**Issue by ravirupareliya** [facebook/react-native#20902]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz
      Memory: 26.43 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.9.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.2.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 27.0.3, 28.0.2
        API Levels: 23, 27, 28
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
```

## Description
I am just using `firebase:5.4.1` and while importing firebase variable it is showing error `undefined is not a function (evaluating '_iterator2[typeof Symbol === "function" ? Symbol.iterator : "@@iterator"]()'`

However it is working fine with iOS, issue is only with android. Here i am attaching screenshot of the error.

![screenshot_1535540062](https://user-images.githubusercontent.com/17959204/44785860-f4d49880-abaf-11e8-942a-5dfc9fa12f4a.png)

## Reproducible Demo

I have just used import statement

    import firebase from 'firebase'

**Comment by dungps** [comment]
https://github.com/facebook/react-native/issues/15902#issuecomment-373964965

I had faced this issue before and I found it.

**Comment by ravirupareliya** [comment]
@dungps Yes i have seen that comment, but here issue is i am not using any loop or anything related to iterator. I have just used firebase library and that also just import statement of firebase, nothing else.

**Comment by bernacle** [comment]
@ravirupareliya I have the same issue here! Did you get a solution?

**Comment by ravirupareliya** [comment]
@bernacle Not yet with this version, i have downgraded it to `0.55.4`

**Comment by Asinox** [comment]
We are in the same page with this error.

**Comment by dungps** [comment]
Try this solution. It works for me

https://github.com/facebook/react-native/issues/15902#issuecomment-396963357

**Comment by RideShi** [comment]
We are in the same page with this error.

**Comment by NSShentu** [comment]
I have the same issue here

**Comment by adirzoari** [comment]
@ravirupareliya @dungps @bernacle @RideShi @nsimmons I have same issue. did you find solution?

**Comment by rahimrahman** [comment]
I upgraded to 0.57.2 from 0.55.4 and the only thing that worked for me was to add babel-polyfill.

> npm i --save-dev babel-polyfill

then in my index.js:

> import 'babel-polyfill';

I did not try what @dungps suggested.

**Comment by iamkaustubh1019** [comment]
I had the same issue while using firebase just add this to index.js
global.Symbol = require('core-js/es6/symbol');
require('core-js/fn/symbol/iterator');
require('core-js/fn/map');
require('core-js/fn/set');
require('core-js/fn/array/find');

**Comment by gorbyoz** [comment]
@iamkaustubh1019 your solution worked for me!! Thanks.

**Comment by tyagogoulart** [comment]
@rahimrahman solution works for me, using react native 0.58.3 with firebase 5.8.2

**Comment by lyson13** [comment]
@iamkaustubh1019 worked for me. thanks!!!

**Comment by iamkaustubh1019** [comment]
@lyson13 your welcome...

**Comment by NichAga** [comment]
Guys, I don't know if this could help but for me was just a catch of a Promise not managed. Still don't get why, usually these errors come out as yellow boxes.

**Comment by thearchibold** [comment]
@rahimrahman  please could you explain what was the issue and how polyfill was able to fix it. Thank you

**Comment by sacowiw** [comment]
Same issue too, who can explain this bug?
