### ISSUE TITLE
<ImageBackground> blurRadius prop. does not work on some actual iOS devices

### ISSUE THREAD

**Issue by Sam-DevZ** [facebook/react-native#20910]
- [ ] Review the documentation: https://facebook.github.io/react-native
  - [ ] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment

  React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 95.29 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.3 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 10.0/10L176w - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.4.1 => 16.4.1 
      react-native: ^0.56.0 => 0.56.0 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1

## Description
Creating an ImageBackground with a blurRadius is just not reliable enough to use in production. Sometimes it works on physical devices, sometimes it does not and the prop. is ignored completely. On my iPhone SE and iPhone 8 it never works, but on my iPhone 5s it sometimes works (I may have to reload a few times).

## Reproducible Demo

```
render(){ 
     return (
      <ImageBackground blurRadius={10} source={require("./stallsky.jpg")} style={{width: "100%", height: "100%"}}> . 
      </ImageBackground>
    }
}

```

Works perfectly on the simulator, does not work reliably on devices. Hard to test because it's so unreliable.

**Comment by Schwusch** [comment]
I am noticing this on Android too.
It works perfectly in debug mode, but fails in release mode.

**Comment by daniocean** [comment]
We have the same issue but only on iOS devices. On Android, it works consistently, but on iOS it is a hit and miss. It does work in the emulator

**Comment by TingAli** [comment]
Works on the emulator for me, but not on a device. (Android)

**Comment by hannojg** [comment]
Same issue here fails in a release. Even worked in debug mode on physical devices.

**Comment by ikishanoza** [comment]
Same issue worked in debug for ios and when I upload the app in TestFlight its not working 

:(

**Comment by jxzy999** [comment]
> Same issue here fails in a release. Even worked in debug mode on physical devices.

same issue, is any sulotion ?
