### ISSUE TITLE
React-Native doesn't recognize my phone/emulator

### ISSUE THREAD

**Issue by zaBogdan** [facebook/react-native#20912]
Hello, I have just installed react native on my windows and I can't get out of this error.

I tried with emulator and physical device but i doesn't work. What I am supposed to do?

Here is the error:
`E:\zaBogdan\React\albums>react-native run-android
Scanning folders for symlinks in E:\zaBogdan\React\albums\node_modules (1230ms)
Starting JS server...
Building and installing the app on the device (cd android && gradlew.bat installDebug)...
Error occurred during initialization of VM
java/lang/NoClassDefFoundError: java/lang/Object
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html`

and adb devices print:
![image](https://user-images.githubusercontent.com/35929785/44812443-dedecc00-abdf-11e8-8800-468f3e14f912.png)

Anyone?
[skip envinfo]

**Comment by zaBogdan** [comment]
[skip envinfo]

**Comment by jamsch** [comment]
Looks like you may need to install JDK

https://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

Have you also got Android Studio installed?

**Comment by zenz** [comment]
unplug your real android device or close the emulator. only one device available.

**Comment by zaBogdan** [comment]
jamsch 

Yes I have instaled Android Studio ( If I have emulator :))? )
I have reinstalled the kit and it worked. Thanks :)
