### ISSUE TITLE
Android[ClipboardManager] with event addPrimaryClipChangedListener 

### ISSUE THREAD

**Issue by isthaison** [facebook/react-native#20925]
Use https://github.com/react-native-community/discussions-and-proposals to propose changes or discuss feature requests. This helps us ensure bug reports and regressions are given the priority they require.

You may also use https://discuss.reactjs.org/ for discussions on topics that are not necessarily served by the Bug Report template.

---

# For Discussion

I have  using Clipboard wirh listen event  change data   ?

**Comment by hramos** [comment]
Hey, the Discussion template is meant for long-form discussions about React Native. This looks like a request for help. Please take a look at http://facebook.github.io/react-native/en/help.html for a list of help resources.
