### ISSUE TITLE
iOS build fails to archive with Xcode

### ISSUE THREAD

**Issue by kantorm** [facebook/react-native#20923]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 63.91 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 9.11.2 - ~/.asdf/shims/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 5.6.0 - ~/.asdf/shims/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 27.0.3, 28.0.2
        API Levels: 27, 28
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1
      react-native: 0.56.0 => 0.56.0
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description
While running archive in Xcode to get an .ipa file build is failing when running following command
```
node /Users/[USER_NAME]/[APP_DIRECTORY]/node_modules/react-native/local-cli/cli.js bundle --entry-file index.js --platform ios --dev false --reset-cache --bundle-output /Users/[USER_NAME]/Library/Developer/Xcode/DerivedData/[APP_NAME]-bysqsdhfdttsamgrgdrlrgcglgws/Build/Intermediates.noindex/ArchiveIntermediates/[APP_NAME]/BuildProductsPath/Release-iphoneos/[APP_NAME].app/main.jsbundle --assets-dest /Users/[USER_NAME]/Library/Developer/Xcode/DerivedData/[APP_NAME]-bysqsdhfdttsamgrgdrlrgcglgws/Build/Intermediates.noindex/ArchiveIntermediates/[APP_NAME]/BuildProductsPath/Release-iphoneos/[APP_NAME].app
```
It displays that error
```
File /Users/[USER_NAME]/Library/Developer/Xcode/DerivedData/[APP_NAME]-bysqsdhfdttsamgrgdrlrgcglgws/Build/Intermediates.noindex/ArchiveIntermediates/[APP_NAME]/BuildProductsPath/Release-iphoneos/[APP_NAME].app/main.jsbundle does not exist. This must be a bug with
```
<img width="742" alt="screen shot 2018-08-30 at 12 22 04" src="https://user-images.githubusercontent.com/17920007/44846505-d1155f00-ac50-11e8-9ade-ba0f5d0b5b7b.png">

**Comment by kantorm** [comment]
In addition. I've already reinstalled packages, cleared rncache & watchman, removed all previous builds.

**Comment by kantorm** [comment]
OK, I resolved it by myself. I upgraded packages with brew and then the new error came up with a missing path to `NODE_BINARY` so in Xcode -> Build Phases -> Bundle React Native code and images I put a direct path to my node installation.

**Comment by Utsho1868** [comment]
How to put a direct path to Node installation? I am really lost to archive my Xcode project of react native. Can anyone please show me the step by step procedure to archive my file?

**Comment by jaybowong** [comment]
@Utsho1868 Have you solved this?

![jietu20181218-200724](https://user-images.githubusercontent.com/1948533/50153171-99661c00-0300-11e9-8048-457a31078507.jpg)


Thank you for your workaround @kantorm .
But I think this issue should remain opened because the problem itself is not fixed.
