### ISSUE TITLE
[NavigatorIOS] Component Cannot be Push Into NavigatorIOS When it was required in different JS files

### ISSUE THREAD

**Issue by yonglam** [facebook/react-native#2092]
I have a react component ItemListScreen in ItemListScreen.js. 
If I do `require("./ItemListScreen.js")` both in index.ios.js and example.js, then push ItemListScreen into a NavigatorIOS in second file, the error occurs: `Invariant Violation: Expected a component class, got[object Object]`.
If I only require it in example.js, it works perfectly.
Any Help?

**Comment by ide** [comment]
Do you have any dependency cycles?

**Comment by yamill** [comment]
I had this issue in the past with the NavigatorIOS.

How I solve this is that you can require the component inside the function. Let me know if this works for you. I haven't tested this since v0.6.0.

For example:

```javascript

var MyView = React.createClass({
   render: function(){
       <View>
           <TouchableHighlight onPress={this.openList}>
              <Text>Open List</Text>
           </TouchableHighlight>
       </View>
   },
   openList: function(){
        var ListScreen = require("./ItemListScreen.js");
        this.props.navigator.push({title: 'ListScreen', component: ListScreen});
   }
});

```

**Comment by cyprusglobe** [comment]
stackoverflow answer here as well

https://stackoverflow.com/questions/30242154/react-native-navigator-recursive-children-crashes/30282297#30282297

**Comment by yonglam** [comment]
@ide Yes, I found a dependency cycle in my files.  @yamill @cyprusglobe , It works if I require it in the function. Thanks.
