### ISSUE TITLE
Well this is awkward; package had UID -1

### ISSUE THREAD

**Issue by jojjesv** [facebook/react-native#20938]
- [ x ] Review the documentation: https://facebook.github.io/react-native
  - [ x ] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ x ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Run `react-native info` in your terminal and paste its contents here.

React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-4250U CPU @1.30GHz
      Memory: 34.24 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.9.4 - /usr/local/bin/node
      npm: 6.2.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 25.0.2, 26.0.2, 26.0.3, 27.0.3, 28.0.0, 28.0.2
        API Levels: 23, 25, 26, 27, 28
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.4.13 => 16.4.13
      @types/react-native: ^0.55.28 => 0.55.28
      react: 16.4.1 => 16.4.1
      react-native: ^0.56.0 => 0.56.0
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

## Description
Describe your issue in detail. Include screenshots if needed. If this is a regression, let us know.

I've got the following error on one app in specific. Not a single clue what could cause it.
I can run the app on my device, but a white screen appears (and does not disappear) and the device becomes unresponsive.

<pre>
09-01 14:44:15.071 1326-1416/? E/PackageManager.DexOptimizer: Well this is awkward; package com.ens.japyo.MainApplication had UID -1
                                                              java.lang.Throwable
                                                                  at com.android.server.pm.PackageDexOptimizer.performDexOptLI(PackageDexOptimizer.java:150)
                                                                  at com.android.server.pm.PackageDexOptimizer.performDexOpt(PackageDexOptimizer.java:126)
                                                                  at com.android.server.pm.PackageManagerService.installPackageLI(PackageManagerService.java:19627)
                                                                  at com.android.server.pm.PackageManagerService.installPackageTracedLI(PackageManagerService.java:19187)
                                                                  at com.android.server.pm.PackageManagerService.-wrap35(Unknown Source:0)
                                                                  at com.android.server.pm.PackageManagerService$8.run(PackageManagerService.java:16463)
                                                                  at android.os.Handler.handleCallback(Handler.java:790)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                  at android.os.Looper.loop(Looper.java:164)
                                                                  at android.os.HandlerThread.run(HandlerThread.java:65)
                                                                  at com.android.server.ServiceThread.run(ServiceThread.java:46)
</pre>

Here's a sample of the log which precedes it:

<pre>
09-01 14:38:34.308 4024-4024/? D/FrequentAppsGrid: onIconPackChanged:com.ens.japyo
09-01 14:38:34.405 20538-20538/? I/Note.log: packageName == com.ens.japyo
09-01 14:38:34.454 1326-2781/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.ens.japyo flg=0x4000010 (has extras) } to com.google.android.googlequicksearchbox/com.google.android.apps.gsa.googlequicksearchbox.GelStubAppWatcher
09-01 14:38:34.464 2858-2858/? V/OPSkinReceiver: intent:Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.ens.japyo flg=0x4000010 cmp=com.oneplus.skin/.OPSkinReceiver (has extras) }
09-01 14:38:34.467 4063-20522/? I/ChromeSync: [Sync,SyncIntentOperation] Handling the intent: Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.ens.japyo flg=0x4000010 cmp=com.google.android.gms/.chimera.GmsIntentOperationService (has extras) }.
09-01 14:38:34.488 6130-6130/? I/Finsky: [2] com.google.android.finsky.wear.ef.run(6): Begin wear auto install for package com.ens.japyo
09-01 14:38:34.676 1326-2785/? I/ActivityManager: START u0 {flg=0x10000000 cmp=com.ens.japyo/.MainActivity} from uid 2000 pid 20590
09-01 14:38:34.681 1326-2785/? E/ANDR-IOP: IOP HAL: Received pkg_name = com.ens.japyo pid = -1
09-01 14:38:34.686 1326-1358/? D/RestartProcessManager: Update Total Launch Times :com.ens.japyo
09-01 14:38:34.686 1326-1358/? D/RestartProcessManager: updateSelf :  com.ens.japyo, size : 17
09-01 14:38:34.686 1326-1358/? D/RestartProcessManager: Increase Total Launch Time : com.ens.japyo, times : 8, index : 16
09-01 14:38:34.686 1326-1358/? D/RestartProcessManager: Last Running Package : com.ens.japyo , start time 1535805514686
09-01 14:38:34.695 20600-20600/com.ens.japyo I/zygote: Late-enabling -Xcheck:jni
09-01 14:38:34.696 1326-2781/? I/ActivityManager: Start proc 20600:com.ens.japyo/u0a450 for activity com.ens.japyo/.MainActivity
09-01 14:38:34.711 20600-20600/com.ens.japyo W/zygote: Using default instruction set features for ARM CPU variant (cortex-a9) using conservative defaults
09-01 14:38:34.719 1326-2781/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_REPLACED dat=package:com.ens.japyo flg=0x4000010 (has extras) } to com.google.android.apps.photos/.account.full.FetchAccountPropertiesAppUpgradeBroadcastReceiver
09-01 14:38:34.720 1326-1358/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_REPLACED dat=package:com.ens.japyo flg=0x4000010 (has extras) } to com.google.android.apps.photos/.account.full.SyncAccountsForLoginBroadcastReceiver
09-01 14:38:34.720 1326-1358/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_REPLACED dat=package:com.ens.japyo flg=0x4000010 (has extras) } to com.google.android.apps.photos/.experiments.phenotype.full.PhenotypeAppUpgradeBroadcastReceiver
09-01 14:38:34.720 1326-1358/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_REPLACED dat=package:com.ens.japyo flg=0x4000010 (has extras) } to com.google.android.apps.photos/.notificationchannels.AppUpdateBroadcastReceiver
09-01 14:38:34.736 4063-20224/? D/FA-SVC: Got package replaced intent: com.ens.japyo
09-01 14:38:34.745 20600-20612/com.ens.japyo I/zygote: Debugger is no longer active
09-01 14:38:34.747 20600-20620/com.ens.japyo I/zygote: The ClassLoaderContext is a special shared library.
09-01 14:38:34.755 1326-2781/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_REPLACED dat=package:com.ens.japyo flg=0x4000010 (has extras) } to com.google.android.googlequicksearchbox/com.google.android.apps.gsa.googlequicksearchbox.GelStubAppWatcher
09-01 14:38:34.799 20600-20600/com.ens.japyo V/FA: Registered activity lifecycle callback
09-01 14:38:34.810 20600-20632/com.ens.japyo W/DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.
09-01 14:38:34.814 20600-20600/com.ens.japyo D/FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
09-01 14:38:34.815 20600-20600/com.ens.japyo I/FirebaseInitProvider: FirebaseApp initialization successful
09-01 14:38:34.820 20600-20635/com.ens.japyo W/DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.
09-01 14:38:34.825 20600-20600/com.ens.japyo E/com.facebook.internal.AttributionIdentifiers: getAttributionIdentifiers should not be called from the main thread
09-01 14:38:34.837 20600-20626/com.ens.japyo V/FA: Collection enabled
09-01 14:38:34.838 20600-20626/com.ens.japyo V/FA: App package, google app id: com.ens.japyo, 1:50558120217:android:99167adb2b04dd71
09-01 14:38:34.838 20600-20635/com.ens.japyo I/FirebaseAuth: [FirebaseAuth:] Loading module via FirebaseOptions.
09-01 14:38:34.838 20600-20635/com.ens.japyo I/FirebaseAuth: [FirebaseAuth:] Preparing to create service connection to gms implementation
09-01 14:38:34.838 20600-20626/com.ens.japyo I/FA: App measurement is starting up, version: 13001
09-01 14:38:34.838 20600-20626/com.ens.japyo I/FA: To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
09-01 14:38:34.839 20600-20626/com.ens.japyo I/FA: To enable faster debug mode event logging run:
                                                     adb shell setprop debug.firebase.analytics.app com.ens.japyo
09-01 14:38:34.839 20600-20626/com.ens.japyo D/FA: Debug-level message logging enabled
09-01 14:38:34.858 20600-20637/com.ens.japyo D/NetworkSecurityConfig: No Network Security Config specified, using platform default
09-01 14:38:34.861 20600-20637/com.ens.japyo I/DpmTcmClient: RegisterTcmMonitor from: com.android.okhttp.TcmIdleTimerMonitor
09-01 14:38:34.862 20600-20637/com.ens.japyo I/DpmTcmClient: RegisterTcmMonitor from: com.android.okhttp.TcmIdleTimerMonitor
09-01 14:38:34.872 20600-20626/com.ens.japyo V/FA: Connecting to remote service
09-01 14:38:34.881 20600-20626/com.ens.japyo V/FA: Connection attempt already in progress
09-01 14:39:04.813 20600-20631/com.ens.japyo E/FirebaseInstanceId: Token retrieval failed: SERVICE_NOT_AVAILABLE
09-01 14:40:04.832 20600-20631/com.ens.japyo E/FirebaseInstanceId: Token retrieval failed: SERVICE_NOT_AVAILABLE
09-01 14:41:34.859 20600-20631/com.ens.japyo E/FirebaseInstanceId: Token retrieval failed: SERVICE_NOT_AVAILABLE
09-01 14:42:57.089 1326-1358/? D/RestartProcessManager: updateSelf :  com.ens.japyo, size : 17
09-01 14:42:57.090 1326-1358/? D/RestartProcessManager: com.ens.japyo got score 21.28882337940804 in DayDuration for duration : 637814
09-01 14:42:57.091 1326-1358/? D/RestartProcessManager: com.ens.japyo got score 100.0 in DayLRU for LRU diff : 45514686
09-01 14:42:57.091 1326-1358/? D/RestartProcessManager: com.ens.japyo got score 66.66666666666666 in DayLaunchTimes for launch times : 8
09-01 14:42:57.093 1326-1358/? D/RestartProcessManager: com.ens.japyo : X : 1133.3333333333333, Y : 361.90999744993667, Z : 1700.0
09-01 14:43:04.846 1326-1358/? D/RestartProcessManager: increase duration : 270159 for com.ens.japyo
09-01 14:43:05.346 1326-1358/? W/ActivityManager: Activity pause timeout for ActivityRecord{8e81e85 u0 com.ens.japyo/.MainActivity t1707}
09-01 14:43:15.351 1326-1358/? W/ActivityManager: Activity stop timeout for ActivityRecord{8e81e85 u0 com.ens.japyo/.MainActivity t1707}
09-01 14:43:48.235 20600-20650/com.ens.japyo W/DpmTcmClient: read failed bytes countRead: -1
09-01 14:44:04.879 20600-20631/com.ens.japyo E/FirebaseInstanceId: Token retrieval failed: SERVICE_NOT_AVAILABLE
09-01 14:44:05.231 1326-1358/? D/RestartProcessManager: Update Total Launch Times :com.ens.japyo
09-01 14:44:05.232 1326-1358/? D/RestartProcessManager: updateSelf :  com.ens.japyo, size : 17
09-01 14:44:05.232 1326-1358/? D/RestartProcessManager: Last Running Package : com.ens.japyo , start time 1535805845231
09-01 14:44:05.262 1326-1522/? W/WindowManager: TaskSnapshotSurface.create: Failed to find top fullscreen for task={taskId=1707 appTokens=[AppWindowToken{6f5427e token=Token{3ffb4da ActivityRecord{8e81e85 u0 com.ens.japyo/.MainActivity t1707}}}] mdr=false}
</pre>

package.json:

<pre>

{
  "name": "hangpyc",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "@mapbox/polyline": "^1.0.0",
    "@types/prop-types": "^15.5.3",
    "@types/react": "^16.4.13",
    "@types/react-native-fbsdk": "^0.6.2",
    "@types/react-navigation": "^2.0.19",
    "babel-plugin-transform-remove-console": "^6.9.2",
    "base-64": "^0.1.0",
    "prop-types": "^15.6.1",
    "react": "16.4.1",
    "react-native": "^0.56.0",
    "react-native-background-timer": "^2.0.1",
    "react-native-camera": "1.1.4",
    "react-native-device-info": "^0.21.5",
    "react-native-fbsdk": "^0.7.0",
    "react-native-fetch-polyfill": "^1.1.2",
    "react-native-firebase": "^4.2.0",
    "react-native-image-resizer": "^1.0.0",
    "react-native-maps": "^0.20.1",
    "react-native-open-map": "^1.9.1",
    "react-native-permissions": "^1.1.1",
    "react-native-render-html": "^3.10.0",
    "react-native-sound": "^0.10.9",
    "react-native-status-bar-height": "^2.0.0",
    "react-native-svg": "^6.3.1",
    "react-native-video": "^2.0.0",
    "react-navigation": "2.12.1"
  },
  "devDependencies": {
    "@types/react-native": "^0.55.28",
    "@types/react-native-video": "^2.0.6",
    "babel-jest": "21.2.0",
    "babel-plugin-root-import": "^6.1.0",
    "babel-preset-react-native": "5.0.0",
    "jest": "21.2.1",
    "react-native-slowlog": "^1.0.2",
    "react-test-renderer": "16.0.0",
    "typescript": "^2.9.2"
  },
  "jest": {
    "preset": "react-native"
  },
  "rnpm": {
    "assets": [
      "assets/fonts/"
    ]
  }
}

</pre>

All I can recall is it working just before installing <pre>react-native-fbsdk</pre> and attempting to run the app on iOS. I ran <pre>react-native-git-upgrade</pre> one or two times, could it be the cause?

**Comment by jojjesv** [comment]
Enabling breakpoints on exceptions reveals this:

![screen shot 2018-09-01 at 16 42 04](https://user-images.githubusercontent.com/12917478/44946955-1dee6680-ae06-11e8-9f55-626bebf8778e.png)

**Comment by jojjesv** [comment]
Solved it, some `com.facebook.marketing.internal` class from the Facebook SDK froze my app. Unlinked the `react-native-fbsdk` library and the app works fine.

**Comment by moulie415** [comment]
@jojjesv thank you!!! You have no idea how long i've had this issue, updating react-native-fbsdk to 0.8.0 seemed to solve my problems

**Comment by levynir** [comment]
Getting the same error with react-native-fbsdk 0.8.0 
Any ideas?
