### ISSUE TITLE
The height of Text is not respecting lineHeight

### ISSUE THREAD

**Issue by mydesweb** [facebook/react-native#20931]
## Environment
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
      Memory: 770.40 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.9.1 - /usr/local/bin/node
      Yarn: 1.6.0 - /usr/local/bin/yarn
      npm: 5.7.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 23.0.3, 25.0.2, 26.0.1, 26.0.2, 26.0.3, 27.0.3
        API Levels: 23, 25, 26, 27
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1
      react-native: 0.56.0 => 0.56.0
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description
The height of a text is more with 0.5 compared to lineHeight in iOS, check the screenshot on the right side
<img width="371" alt="screen shot 2018-08-31 at 04 33 25" src="https://user-images.githubusercontent.com/5901386/44887933-36139800-acd7-11e8-9760-9ed4925635b4.png">

## Reproducible Demo
Set lineHeight: 22 on Text style then Toogle Inspector and check the height

**Comment by aMarCruz** [comment]
@mydesweb , in iOS, RN takes into account the absolute position on the screen to calculate the dimensions and then sets the result to the closest size that corresponds to an integer number of pixels (no points). Depending on this, there will be a difference up to 1px compensated by yoga in other View ... almost always :)

This is an issue that I mention in [this readme](https://github.com/aMarCruz/react-native-text-size#incorrent-height-ios).
