### ISSUE TITLE
Adding drop down menu for Doc to reflect the version of react-native

### ISSUE THREAD

**Issue by alinz** [facebook/react-native#2093]
Would it make sense to add something(Drop down menu as an example) to doc, so developers can change the version of doc which reflects the version that they are using? I found myself reading doc and implementing one feature and realizing, that feature is not available in my current version of react-native.

**Comment by browniefed** [comment]
@brentvatne dupe of #1531

**Comment by alinz** [comment]
thanks @browniefed. I'm closing this.
