### ISSUE TITLE
UTFSequence module is not exported

### ISSUE THREAD

**Issue by aMarCruz** [facebook/react-native#20935]
## Environment

  React Native Environment Info:
    System:
      OS: Linux 4.13 Linux Mint 18.3 (Sylvia)
      CPU: x64 Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz
      Memory: 6.27 GB / 15.35 GB
      Shell: 4.3.48 - /bin/bash
    Binaries:
      Node: 8.11.2 - ~/.nvm/versions/node/v8.11.2/bin/node
      Yarn: 1.7.0 - ~/.nvm/versions/node/v8.11.2/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.11.2/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        Build Tools: 23.0.1, 26.0.2, 26.0.3, 27.0.3
        API Levels: 16, 23, 26, 27
    npmPackages:
      @types/react: ^16.4.11 => 16.4.12
      @types/react-native: ^0.56.10 => 0.56.14
      react: 16.4.1 => 16.4.1
      react-native: 0.56.0 => 0.56.0
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-create-library: 3.1.2
      react-native-kill-packager: 1.0.0

## Description

From the [Added: New Features](https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md#added-new-features-1) section of v0.55 changelog:

> There's a new UTFSequence module in the library for common Unicode sequences (Emoji!) (54870e0 and 4761d5a by @sahrens)

however, this module is not exported.

## Reproducible Demo
n/a

**Comment by janicduplessis** [comment]
If someone wants to open a PR to add the module to RN exports here https://github.com/facebook/react-native/blob/master/Libraries/react-native/react-native-implementation.js that would be great.

In the meantime you can always use haste imports to use the module (`import UTFSequence from 'UTFSequence'`).

**Comment by dantesolis** [comment]
hey folks has this issue bee taken? If not I would like to take it. Thanks :)

**Comment by flowkraD** [comment]
Is this still an open issue?
