### ISSUE TITLE
DatePickerAndroid is not open

### ISSUE THREAD

**Issue by brahmy** [facebook/react-native#20937]
I am getting the working of "Cannot open date picker". i am creating datepickerandroid like the following.
`  async openAndroidDatePicker() {
    try {
      const {action, year, month, day} = await DatePickerAndroid.open({
        date: new Date()
      });
    } catch ({code, message}) {
      console.warn('Cannot open date picker', message);
    }
  }
`

and calling this in button like bellow.

`  <Button
  onPress={() => {
    if(Platform.OS === 'ios') {
      console.log(" ios") 
     } else {
      this.openAndroidDatePicker()

           console.log("android") 
    } 
    // Alert.alert('You tapped the button!');
  }}
  title="Press Me"
/>`

please help me with this issue.

**Comment by MaxInMoon** [comment]
@brahmy try to have a look in this [function](https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/master/src/CustomDatePickerAndroid/index.js#L48) from [react-native-modal-datetime-picker](https://github.com/mmazzarolo/react-native-modal-datetime-picker).
Also, this error can come from a issue I recently identified, at least I guess: #21253
