### ISSUE TITLE
Webview does not update. Still having the old webpage even though I changed it.

### ISSUE THREAD

**Issue by Mr-Ingram** [facebook/react-native#20944]
## Environment
Environment:
  OS: Windows 10
  Node: 9.4.0
  Yarn: 1.5.1
  npm: 5.7.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  2.3.0.0 AI-162.3871768

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: ^0.52.0 => 0.52.0

## Description
When I update my website, it does update in the browser on a computer or outside the app. But in the webview, inside the app, it does not update. The page stays the same.

## Reproducible Demo
To reproduce: keep the same uri in your webview, but update the webpage itself. All I did was update text and css elements.

Code: 

```
`  <View style={{height: Dimensions.get('window').height, width: Dimensions.get('window').width, alignSelf: 'center', position: 'absolute'}}>
        <WebView
        source={{uri: 'https://www.exmaple.com/qotd.php'}}
        />
       </View>`
```

Maybe because it's php or css caching?

**Comment by jojjesv** [comment]
There's a `cache` option in the `source` prop, have you checked it out?

**Comment by ryanhomer** [comment]
To test for caching issues, try modifying the URL, e.g.: `https://www.exmaple.com/qotd.php?v=1`. If that works, then the content is being cached by the webview and you'll need to add proper cache headers in your server responses.

**Comment by posthighline** [comment]
I get this problem too, despite adding a cache header in the webview:
`<meta http-equiv="Cache-Control" content="no-cache">`

**Comment by Mr-Ingram** [comment]
Thank you everyone, it was a caching problem and what worked was @posthighline  solution and using a npm package called react-native-cache-clear.

**Comment by jamonholmgren** [comment]
It appears this issue has been resolved, so I'm not planning to migrate it to https://github.com/react-native-community/react-native-webview.
