### ISSUE TITLE
TypeError: undefined is not a function (evaluating 'instance.render()')

### ISSUE THREAD

**Issue by Decapitary** [facebook/react-native#20946]
I needed ```borderStyle: 'dashed'``` to work on android so I upgraded to 
```
react-native-cli: 2.0.1
react-native: 0.57.0-rc.3
```

everything worked fine but when I navigated to the screen (tabNavigator) I got this error (every other screen worked fine)
I changed the screen name to something else and now im getting this error on launch

```

TypeError: undefined is not a function (evaluating 'instance.render()')

This error is located at:
    in App (at renderApplication.js:34)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in AppContainer (at renderApplication.js:33)
finishClassComponent
    MYPROJECT\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:10428:21
updateClassComponent
    MYPROJECT\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:10371:4
beginWork
    MYPROJECT\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:11152:8
performUnitOfWork
    MYPROJECT\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:13671:21
workLoop
    MYPROJECT\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:13710:41
renderRoot
    MYPROJECT\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:13762:15
performWorkOnRoot
    MYPROJECT\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:14676:17
performWork
    MYPROJECT\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:14575:24
performSyncWork
    MYPROJECT\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:14528:14
requestWork
    MYPROJECT\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:14427:19
scheduleWork
    MYPROJECT\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:14201:16
scheduleRootUpdate
    MYPROJECT\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:14949:15
updateContainerAtExpirationTime
    MYPROJECT\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:14982:28
updateContainer
    MYPROJECT\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:15014:4
render
    MYPROJECT\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:15687:20
renderApplication
    MYPROJECT\node_modules\react-native\Libraries\ReactNative\renderApplication.js:59:34
run
    MYPROJECT\node_modules\react-native\Libraries\ReactNative\AppRegistry.js:101:10
runApplication
    MYPROJECT\node_modules\react-native\Libraries\ReactNative\AppRegistry.js:195:26
__callFunction
    MYPROJECT\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:349:47
<unknown>
    MYPROJECT\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:106:26
__guard
    MYPROJECT\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:297:10
callFunctionReturnFlushedQueue
    MYPROJECT\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:105:17

```
render is undefined??what is happening?

**Comment by jerinho** [comment]
> I needed `borderStyle: 'dashed'` to work on android so I upgraded to
> 
> ```
> react-native-cli: 2.0.1
> react-native: 0.57.0-rc.3
> ```
> everything worked fine but when I navigated to the screen (tabNavigator) I got this error (every other screen worked fine)
> I changed the screen name to something else and now im getting this error on launch
> 
> ```
> 
> TypeError: undefined is not a function (evaluating 'instance.render()')
> 
> This error is located at:
>     in App (at renderApplication.js:34)
>     in RCTView (at View.js:44)
>     in RCTView (at View.js:44)
>     in AppContainer (at renderApplication.js:33)
> finishClassComponent
>     MYPROJECT\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:10428:21
> updateClassComponent
>     MYPROJECT\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:10371:4
> beginWork
>     MYPROJECT\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:11152:8
> performUnitOfWork
>     MYPROJECT\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:13671:21
> workLoop
>     MYPROJECT\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:13710:41
> renderRoot
>     MYPROJECT\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:13762:15
> performWorkOnRoot
>     MYPROJECT\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:14676:17
> performWork
>     MYPROJECT\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:14575:24
> performSyncWork
>     MYPROJECT\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:14528:14
> requestWork
>     MYPROJECT\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:14427:19
> scheduleWork
>     MYPROJECT\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:14201:16
> scheduleRootUpdate
>     MYPROJECT\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:14949:15
> updateContainerAtExpirationTime
>     MYPROJECT\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:14982:28
> updateContainer
>     MYPROJECT\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:15014:4
> render
>     MYPROJECT\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:15687:20
> renderApplication
>     MYPROJECT\node_modules\react-native\Libraries\ReactNative\renderApplication.js:59:34
> run
>     MYPROJECT\node_modules\react-native\Libraries\ReactNative\AppRegistry.js:101:10
> runApplication
>     MYPROJECT\node_modules\react-native\Libraries\ReactNative\AppRegistry.js:195:26
> __callFunction
>     MYPROJECT\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:349:47
> <unknown>
>     MYPROJECT\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:106:26
> __guard
>     MYPROJECT\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:297:10
> callFunctionReturnFlushedQueue
>     MYPROJECT\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:105:17
> ```
> render is undefined??what is happening?

dude please just give what the bot want or provide your solution if any

**Comment by Quichei** [comment]
they need latest release of react native but latest release DOESNT WORK! you cant even run a blank project! 
there is no solution. it doesnt work for `react native 0.55.*`  and you cant upgrade cuz it wont run the code.

**Comment by huytran123** [comment]
Use this version to resolve this error :). I have tested it, and worked fine:
"react": "16.6.3",
"react-native": "0.58.0-rc.2"

**Comment by cassianomon** [comment]
Using render as:
`render = () => {`

solved for me, but is it necessary? Even if I just return:

```
render() {
	return <View />
}
```

it returns me this error...
