### ISSUE TITLE
Emulator works, but Phone doesn't

### ISSUE THREAD

**Issue by zaBogdan** [facebook/react-native#20954]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Run `react-native info` in your terminal and paste its contents here.
[
![image](https://user-images.githubusercontent.com/35929785/44999627-5d17e580-afc7-11e8-8abc-a678c8e2fa98.png)
](url)
## Description
I've recently finished to develop a simple login app with integration of Firebase and now when I try to use it on phone ( for native feedback ) it gives me this error screen and I don't know why beacuse on the emulator it works perfect. 

Phone error screen [
![image](https://user-images.githubusercontent.com/35929785/44998377-d3174f00-afbd-11e8-9014-3f96290831bb.png)
](url)
Same app but on pc [
![image](https://user-images.githubusercontent.com/35929785/44998333-57b59d80-afbd-11e8-8f96-41e2d27156fc.png)
](url)

## Reproducible Demo
What pice of code am I supposed to paste in there?

**Comment by samie820** [comment]
Please can you specify the environment in which your code is running,  also,  specify the android version of your device and emulator
