### ISSUE TITLE
[Regression] VirtualizedList jumpy header

### ISSUE THREAD

**Issue by danilobuerger** [facebook/react-native#20956]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment

```
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
      Memory: 64.78 MB / 16.00 GB
      Shell: 5.5.1 - /usr/local/bin/zsh
    Binaries:
      Node: 10.9.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.2.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 25.0.1, 25.0.2, 25.0.3, 26.0.2, 26.0.3, 27.0.3
        API Levels: 23, 25, 26, 27
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.57.0-rc.3 => 0.57.0-rc.3 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

## Description

The PR #18105, Issue #18104 by @rbrosboel now causes jumpy headers while scrolling. See Demo

## Reproducible Demo

Since expo doesn't provide 0.57.0-rc, see the following repo created with react-native-cli: https://github.com/danilobuerger/react-native-bug-virtualized-list

Scroll header 6 towards header 7, notice the jumping 

![qwe](https://user-images.githubusercontent.com/996231/45002562-462dbf00-afd8-11e8-98fc-9f848fd9c7c2.gif)

**Comment by Freddy03h** [comment]
Anyone find a workaround ? This issue is still valid on `0.57.3`.

**Comment by danilobuerger** [comment]
@Freddy03h reverting the linked PR fixes it.

**Comment by shashankkrjain** [comment]
We can add a condition at the line:

```
let leadSpace = stickyBlock.offset - (initBlock.offset + initBlock.length);

if (this.props.initialScrollIndex) {
   leadSpace = stickyBlock.offset - initBlock.offset;
}
```

**Comment by danilobuerger** [comment]
@shashankkrjain  Thanks for the inspiration, I created a PR here: #22025

**Comment by wontonst** [comment]
Do we have an update on this issue? This is causing production issues for our mobile app.

**Comment by wontonst** [comment]
yep but we haven't seen any pushes to get the PR reviewed and merged in so I believe the community would like an update on whether or not the fix would get merged in, and when that would happen.

**Comment by danilobuerger** [comment]
so ask in the PR, not the issue.

**Comment by wontonst** [comment]
already did, no response

**Comment by fcaride** [comment]
Any update on this?

**Comment by danilobuerger** [comment]
@fcaride What update are you expecting? The issue has been resolved, that is why its closed.

**Comment by fcaride** [comment]
Lol sorry i didnt read all the thread, do you know which version of react-native has included this PR?

**Comment by danilobuerger** [comment]
@fcaride You can easily look that up yourself. Click on the referenced commit and github will show you which tags include this commit.

**Comment by fcaride** [comment]
Sorry i cant see where, i can only find the "Merged" label
