### ISSUE TITLE
[TouchableOpacity] Button should not animate on touch down

### ISSUE THREAD

**Issue by ide** [facebook/react-native#2095]
The button should animate only when the touch ends or when the user moves out of the press rect bounds.

**Comment by ide** [comment]
This ends up being non-trivial to do since TouchableMixin's public API doesn't distinguish between pressIn events from new touches and pressIn events from moving a touch out of the press rect and back in. Would need to expose a new callback method or expose the touchable state to let TouchableOpacity determine the difference.

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/touchableopacity-button-should-not-animate-on-touch-down
