### ISSUE TITLE
[StatusBar] not respecting 'light-content' theme when bundling app

### ISSUE THREAD

**Issue by pkibbey** [facebook/react-native#2096]
<img width="354" alt="screen shot 2015-07-22 at 19 00 36" src="https://cloud.githubusercontent.com/assets/1381816/8841544/f6a1e8b4-30a3-11e5-9487-1fe06d097179.png">

I have the Status Bar Style set to to 'light' in Xcode, which works perfectly in IOS Simulator.

<img width="387" alt="screen shot 2015-07-22 at 19 04 38" src="https://cloud.githubusercontent.com/assets/1381816/8841584/8942f424-30a4-11e5-9ed2-3a8a5f46c8b6.png">

After compiling with "react-native bundle --minify" and submitting to the app store, the Status Bar renders as the default dark style.

I have a workaround for the moment by manually setting the style of StatusBarIOS on componentDidMount, but it seems redundant...

```
StatusBarIOS.setStyle('light-content');
```

This was working in version 0.5.0, and I jumped straight to 0.8.0-rc.2.

**Comment by browniefed** [comment]
@pkibbey any news on this, is it still happening in latest .11-rc?

**Comment by brentvatne** [comment]
@browniefed - could you try this out on .11-rc and report back? :Smile:

**Comment by pkibbey** [comment]
I can confirm that this is no longer an issue
