### ISSUE TITLE
allowFontScaling  is not working in webview for Android.

### ISSUE THREAD

**Issue by manoj2166** [facebook/react-native#20960]
## Environment
Environment:
OS: macOS High Sierra 10.13.5
Node: 6.9.4
Yarn: Not Found
npm: 3.10.10
Watchman: 4.9.0
Xcode: Xcode 9.4 Build version 9F1027a
Android Studio: 2.2 AI-145.3537739

Packages: (wanted => installed)
react: ^16.3.1 => 16.4.1
react-native: ^0.55.0 => 0.55.4

## Description
**allowFontScaling**  is not working in webview for Android.

## Reproducible Demo
Increase your Android device font size to the maximum and open url in webview you observe that font size of text in webview for Android is increases and when you put **allowFontScaling** value false then no effect for android in webview rather than ios is working fine.

**Comment by jamonholmgren** [comment]
Migrated to https://github.com/react-native-community/react-native-webview/issues/30 and this issue can be closed.
