### ISSUE TITLE
[0.57] Regression related to Yarn Workspaces

### ISSUE THREAD

**Issue by brunolemos** [facebook/react-native#20969]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

  React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
      Memory: 43.02 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.3 - /usr/local/bin/node
      Yarn: 1.9.4 - ~/.yarn/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 23.0.3, 24.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.0
        API Levels: 19, 22, 23, 24, 25, 26, 27
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.4.7 => 16.4.7 
      @types/react-native: ^0.56.10 => 0.56.10 
      react: 16.4.2 => 16.4.2 
      react-native: 0.57.0-rc.3 => 0.57.0-rc.3 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-macos-cli: 2.0.1

## Description

When using `react-native@0.56.0`, it looks for JS files on yarn workspaces just fine: 

```
Found alternate project roots:  [ '/Users/user/Projects/acme/projectB' ]

Looking for JS files in
   /Users/user/Projects/acme/projectA
   /Users/yser/Projects/acme/projectB 
```

When using `react-native@0.57.0-rc.3`, it does show:
```
Found alternate project roots:  [ '/Users/user/Projects/acme/projectB' ]
```

But on the `Looking for JS files in` part, it doesn't show projectB:
```
Looking for JS files in
   /Users/user/Projects/acme/projectA

Loading dependency graph, done.
```

**Comment by brunolemos** [comment]
Seems to be because the `metro` config file changed and doesn't support `getProjectRoots` anymore on `rn-cli.config.js`. I'll try to find a workaround...

**Comment by Titozzz** [comment]
Thank, had the same issue, I'm gonna add it to the patch notes so that other people dont get lost

**Comment by Titozzz** [comment]
@brunolemos Would you also know what happened to getBlacklistRE ?

**Comment by maitriyogin** [comment]
Hi, 
just dropped into this after trying to upgrade to expo 31 ...
My rn-cli.js config looks like this : 
```
const getConfig = require("metro-bundler-config-yarn-workspaces");
const config = getConfig(__dirname);
const blacklist = require("metro-config/src/defaults/blacklist");
const rnliConfig = {
  watchFolders: config.getProjectRoots(),
  resolver: {
    blacklistRE: blacklist
  }
};
```

When I start my app I get the following error : 
```
[08:31:56] (node:96887) UnhandledPromiseRejectionWarning: Error: Cannot find module 'metro/src/blacklist'
[08:31:56]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
```

any ideas?

/Stephen
