### ISSUE TITLE
[Android]"Cannot record touch end without touch start." error when taking a screenshot with 3-finger gesture on Android 8.1

### ISSUE THREAD

**Issue by JasonFes** [facebook/react-native#20977]
**Is this a bug report?**
Yes.

**Have you read the Contributing Guidelines?**
Yes.

**Environment**
OS: Windows 10
Node: 8.9.4
Yarn: 1.7.2
npm: 6.3.0
Watchman: Not Found
Xcode: N/A
Android Studio: Version 3.0.0.0 AI-171.4443003

Packages: (wanted => installed)
react: ^16.4.1 => 16.4.1
react-native: ^0.56.0 => 0.56.0

Target Platform: Android (8.1.0)
Build Tools: react-native run-android

**Steps to Reproduce**
1、Use "OnePlus 5" or "XiaoMi Redmi 6  Android 8.1"phone.
2、Run "react-native run-android"
3、Use 3-finger screenshot gesture

**Expected Behavior**
Taking a screenhot of the page.

**Actual Behavior**
Red screen error
![123](https://user-images.githubusercontent.com/16607607/45083694-134a0f00-b12f-11e8-8017-6c84be4859d8.jpg)

**Reproducible Demo**
You can use any "OnePlus 5" or "XiaoMi Redmi 6  Android 8.1" phone and any project. Then, turn on the three-finger screenshot gesture and try taking a screenshot.

**Comment by luck2011** [comment]
Run into this error today.

**Comment by hansfpc** [comment]
Any solution? :c

**Comment by dishantwalia** [comment]
This works for me
https://github.com/facebook/react-native/issues/15059#issuecomment-458492395
