### ISSUE TITLE
Cannot change TextInput fontSize after typing anything once

### ISSUE THREAD

**Issue by brunolemos** [facebook/react-native#20971]
Possibly related: #20224, #18874

  - [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
React Native Environment Info:
System:
OS: macOS 10.14
CPU: x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
Memory: 43.02 MB / 16.00 GB
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 8.11.3 - /usr/local/bin/node
Yarn: 1.9.4 - ~/.yarn/bin/yarn
npm: 5.6.0 - /usr/local/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
SDKs:
iOS SDK:
Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
Android SDK:
Build Tools: 23.0.1, 23.0.3, 24.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.0
API Levels: 19, 22, 23, 24, 25, 26, 27
IDEs:
Android Studio: 3.1 AI-173.4819257
Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
npmPackages:
@types/react: ^16.4.7 => 16.4.7
@types/react-native: ^0.56.10 => 0.56.10
react: 16.4.2 => 16.4.2
react-native: 0.57.0-rc.3 => 0.57.0-rc.3
npmGlobalPackages:
react-native-cli: 2.0.1
react-native-macos-cli: 2.0.1

## Description
I'm trying to implement a dynamic fontSize on React Native based on the content size, but I hit a React Native limitation / bug.

You can change the fontSize multiple times before typing anything in the TextInput, but once you type something you cannot change it anymore. See it in action in the link below.

## Reproducible Demo
https://snack.expo.io/@brunolemos/react-native-textinput-bug

![textinput](https://user-images.githubusercontent.com/619186/45063856-b135cf00-b086-11e8-9ad9-a82b75181a1a.gif)

**Comment by brunolemos** [comment]
Interesting. I just found that this only happens on uncontrolled TextInput. If I add the properties:

```diff
<TextInput
+    onChangeText={text => this.setState({ text })}
+    value={this.state.text}
/>
```

then it works.

Is that the expected behavior or is this a bug?
I'll leave this open since it may be a bug.

![textinput-w](https://user-images.githubusercontent.com/619186/45063912-17225680-b087-11e8-8e1b-3a4bc29ccbea.gif)

**Comment by yu629** [comment]
+1
