### ISSUE TITLE
Viewport Height not 100%.

### ISSUE THREAD

**Issue by kevupton** [facebook/react-native#20970]
## Environment

  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
      Memory: 12.50 GB / 31.92 GB
    Binaries:
      Yarn: 1.9.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.1.0.0 AI-173.4819257

## Description
Describe your issue in detail. Include screenshots if needed. If this is a regression, let us know.

![spacing-issue](https://user-images.githubusercontent.com/2093615/45063473-89c81c00-b0f1-11e8-80ad-62fa6a89aeb3.jpg)

As you can see in this image, there seems to be double the bottom spacing. Or the app is not at 100% height. 

This is only appearing on my phone: Xiaomi 8 on Android Orio 8.1

The spacing appears to be the same height as the menu down the bottom so it seems like it thinks the app is the full screen height.

This spacing is there when the app first loads (so on the splash screen as well.)

I think its to do with the hideable menu, as I have seen apps hide this menu, however I am not aware of how to do this. 

## Reproducible Demo

This seems to be more of a device specific issue which I have not been able to reproduce on any emulators. 

Xiaomi 8 Device

**Comment by LasseSLambertsen** [comment]
Update gradle and target sdk 😊
Had same issue on my own Mi8, it will look the same on all 18/9 screens

**Comment by kevupton** [comment]
Thanks @LasseSLambertsen 
Does this fix the issue after uprading ? 
Any chance your could let me know what versions of gradle and sdk you are using ? ❤️

**Comment by markhomoki** [comment]
Thanks @LasseSLambertsen. Upgrading the targetSdkVersion to 26 fixed the issue.

**Comment by LasseSLambertsen** [comment]
@markhomoki Good to hear, was not sure which one did the magic 😅

@kevupton Sorry, for never answering, completely forgot about the issue 😔

**Comment by s349856186** [comment]
@kevupton Have you solved this problem? what‘s version of gradle and targetSdkVersion? thanks
![image](https://user-images.githubusercontent.com/2498958/45987879-7122a480-c0a6-11e8-9627-8bf3eca1b4dd.png)

It's my xiaomi MIX 2S
