### ISSUE TITLE
boost-for-react-native/boost/compatibility/cpp_c_headers/cstddef:10:1: error: unknown type name 'namespace'

### ISSUE THREAD

**Issue by xiaoyongchen** [facebook/react-native#20988]
Is this a bug report?
Yes

Have you read the Contributing Guidelines?
Yes

Environment

Environment:
OS: macOS High Sierra 10.13.6
Node: 10.8.0
Yarn: 1.3.2
npm: 6.2.0
Watchman: 4.7.0
Xcode: Xcode 9.4.1 Build version 9f2000

Packages: (wanted => installed)
react: ^16.3.0-alpha.1
react-native:0.54.4

Steps to Reproduce
Install react-native via Cocoapods
Add CxxBridge instead of BatchedBridge to your Podfile
pod install
Expected Behavior
Download the same version & bundle of the boost library that is used by ios-install-third-party.sh.

Actual Behavior
The boost dependency defined in Folly.podspec points to:

Which is:
1.boost-for-react-native/boost/compatibility/cpp_c_headers/cstddef:10:14: error: expected ';' after top level declarator
2.boost-for-react-native/boost/tr1/tr1/utility:21:20: fatal error: 'utility' file not found
#     include_next <utility>
3./Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKitDefines.h:8:9: fatal error: could not build module 'Darwin'
#import <Availability.h>
 ~~~~~~~^
4./Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:10: fatal error: could not build module 'Darwin'
#include <sys/types.h>
 ~~~~~~~~^
5./Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk/usr/include/dispatch/dispatch.h:25:10: fatal error: could not build module 'Darwin'
#include <Availability.h>
 ~~~~~~~~^

**Comment by zenghao0708** [comment]
the same issue with RN 0.56.0 when integrated with my swift project, does any one know how to fix this?

**Comment by HannanShaikYara** [comment]
Did anyone fix this? I am facing this issue when I am running the build on ios device. 

RN: 0.56.0
XCode: 10.0

**Comment by gaiamobile** [comment]
Did anyone fix this? I am facing this issue when I am running the build on ios device.

RN: 0.57.2
XCode: 10.0

**Comment by putuyoga** [comment]
Whoever get this problem, you can refer to this [stackoverflow](https://stackoverflow.com/questions/50002039/rnappauth-ios-build-failed-unknown-type-name-namespace-react-native-app-aut)

configuration of header search path may be the root cause of the problem
