### ISSUE TITLE
 A problem occurred configuring project ':react-native-vector-icons'.

### ISSUE THREAD

**Issue by klxin** [facebook/react-native#20982]
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-vector-icons'.
      > Could not resolve all dependencies for configuration ':react-native-vector-icons:classpath'.
         > Could not download builder.jar (com.android.tools.build:builder:2.3.3)
            > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/builder/2.3.3/builder-2.3.3.jar'.
               > Could not HEAD 'https://jcenter.bintray.com/com/android/tools/build/builder/2.3.3/builder-2.3.3.jar'.
                  > Connect to d29vzk4ow07wi7.cloudfront.net:443 [d29vzk4ow07wi7.cloudfront.net/13.35.103.11, d29vzk4ow07wi7.cloudfront.net/13.35.103.174, d29vzk4ow07wi7.cloudfront.net/13.35.103.48, d29vzk4ow07wi7.cloudfront.net/13.35.103.62] failed: Read timed out

**Comment by ryanhomer** [comment]
Have you updated your gradle version? If you're on gradle 4.1 or higher, have you updated your `repositories` config?

- [Android Plugin for Gradle release notes](https://developer.android.com/studio/releases/gradle-plugin)
