### ISSUE TITLE
What happened to the Android integration tests when building from source?

### ISSUE THREAD

**Issue by ryanhomer** [facebook/react-native#20983]
# For Discussion

I would like to submit a PR, have built from source, have added changes locally and would now like to run the Android native unit and integration tests as detailed [here](https://facebook.github.io/react-native/docs/testing#android) before proceeding any further. However, I am unable to find these test anywhere.

Can someone guide me on what is currently being done for testing on the native Android side?

**Comment by jeveloper** [comment]
Hey @ryanhomer  i noticed the watchman problems lately in CI

i think the best place to suggest your PR is here

https://github.com/react-native-community/react-native-releases/issues/34
