### ISSUE TITLE
iOS app crashes in Release Config (but works in Debug)

### ISSUE THREAD

**Issue by sophiabk** [facebook/react-native#20985]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
      Memory: 1.89 GB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.9.0 - ~/.nvm/versions/node/v10.9.0/bin/node
      npm: 6.2.0 - ~/.nvm/versions/node/v10.9.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 27.0.3, 28.0.1
        API Levels: 23, 24, 25, 26, 27, 28
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.4.2 => 16.4.2 
      react-native: ^0.56.0 => 0.56.0 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description
1. App builds perfectly in debug mode (on device and simulator)
2. Android app builds in both debug and release perfectly.
3. THE PROBLEM: iOS app loads in release mode and immediately crashes on launch screen (e.g. build succeeds and then crashes)
4. Crash Report is here: http://crashes.to/s/11df9058d1f 
Fatal Exception: NSInvalidArgumentException
-[RCTRootView reactTag] unrecognized selector sent to instance 0x139e023c0

## What I've tried already (but didn't help)
- Building Active Architecture Only
- Not stripping dead code / Stripping dead code
- Checking Headers
- Checking Linked Binaries
- Checking Link Flags
- Reinstalling NPM/Pods
- https://github.com/facebook/react-native/issues/20150

## What I think might be wrong
- Something with Babel 7 and React-Native
- Something with React-Native-Navigation

**Comment by poprapas** [comment]
how to a solution?
