### ISSUE TITLE
[CI] Test failure: D9614432 adds thecount dependency, but it's missing from open source

### ISSUE THREAD

**Issue by hramos** [facebook/react-native#20994]
This can be observed in Circle CI with the following failure:

```
buck fetch ReactAndroid/src/test/java/com/facebook/react/modules
2018-09-06 00:08:43,732 [WARNING][buck_tool.py:450] Not using buckd because watchman isn't installed.
Picked up _JAVA_OPTIONS: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
PARSING BUCK FILES... 0.3s (100%)
No build file at ReactAndroid/src/main/java/com/facebook/thecount/BUCK when resolving target //ReactAndroid/src/main/java/com/facebook/thecount:thecount.
```

**Comment by empyrical** [comment]
Maybe the open source version could use a simple no-op shim?

**Comment by hramos** [comment]
@empyrical I think that's what we should go with.

**Comment by gengjiawen** [comment]
Any response from the author ?

**Comment by hramos** [comment]
Yeah, I already chatted with the author. The code referenced here is not meant to be open sourced. We need to either roll back, or add a no-op shim as @empyrical suggested.

We also need to toughen up our internal land blocking tests to ensure they can catch issues like these in the future.

**Comment by gengjiawen** [comment]
If the author can't fix it in short time, I am inclined to revert the commit, blocking master ci for a long time is not a good idea.

Also, for internal test, is it possible fb use something like docker to avoid some private code ?

**Comment by hramos** [comment]
No, we cannot use Docker.

**Comment by hramos** [comment]
We're reverting the change.
