### ISSUE TITLE
Watchman crawl failed

### ISSUE THREAD

**Issue by bramvbilsen** [facebook/react-native#20997]
## Environment
```
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
      Memory: 29.42 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.9.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.2.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.0.0 => 16.4.2 
      react-native: 0.56.0 => 0.56.0 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```
## Description
When trying to run our React Native app on iOS via `react-native run-ios`, we are running into issues with watchman, the build succeeds though. In the metro bundler, we are getting the following message:
```
Metro Bundler ready.

Loading dependency graph...
 BUNDLE  [ios, dev] ../../index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1)jest-haste-map: Watchman crawl failed. Retrying once with node crawler.
  Usually this happens when watchman isn't running. Create an empty `.watchmanconfig` file in your project's root folder or initialize a git or hg repository in your project.
  Error: Watchman error: The watchman connection was closed. Make sure watchman is running for this project. See https://facebook.github.io/watchman/docs/troubleshooting.html.
```
That is unfortunately all the output we are getting.  

We are fairly certain it is not code related as it was working just a few hours ago. We tried running an earlier version that did run, but no luck with that either.
We tried to solve the issue by cleaning the iOS project and by trying to stop all watchman instances and `watchman watch-del-all`.
The last thing we did before the issue started to occur is installing `react-native-vector-icons`, no error messages for that popped and code from before that doesn't work anymore either so that was most likely not the problem.

**Comment by LustSkills** [comment]
Bump

**Comment by hramos** [comment]
This seems like something that could have been sporadic. I apologize if I am closing this way too early, but it does not look like this has been a recurring issue due to the lack of reactions/comments on this thread.

**Comment by tanapaydin** [comment]
Same issue. Please reopen. Any solution?
