### ISSUE TITLE
:app:bundleReleaseJsAndAssets FAILED

### ISSUE THREAD

**Issue by happy32x** [facebook/react-native#21016]
## Environment
  React Native Environment Info:
    System:
      OS: Windows 8.1
      CPU: x64 Intel(R) Core(TM) i3-3217U CPU @ 1.80GHz
      Memory: 1.66 GB / 3.90 GB
    Binaries:
      Yarn: 1.7.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.3.0 - C:\Program Files\nodejs\npm.CMD
      Watchman: 4.9.4 - C:\Windows\system32\watchman.EXE
    IDEs:
      Android Studio: Version  3.1.0.0 AI-173.4907809

## Description
When I start a new react-native project on my TECNO-L8 PLUS via USB, I have this error, while on my virtual device Nexus_5X API 23 andorid 6.0 everything works well

## Reproduce issue
1) react-native init <project_name> 
2) cd <project_name>
3) react-native run-android --deviceId H80xxx

After step 3 i get 

:app:bundleReleaseJsAndAssets
Scanning folders for symlinks in X:\xxxxxxxxx\node_modules (56ms)
Scanning folders for symlinks in X:\xxxxxxxxx\node_modules (63ms)
warning: the transform cache was reset.
Loading dependency graph, done.

Unable to resolve module `AccessibilityInfo` from `X:\xxxxxxxxx\node_modules\react-native\Libraries\react-native\react-native-implementation.js`: Module `AccessibilityInfo` does not exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.

:app:bundleReleaseJsAndAssets FAILED

FAILURE: Build failed with an exception.

**note**
- The physical device is connected (TECNO L8 PLUS android 5.1)
- OS: windows 8.1
- android Studio is update
- nodeJS is update
- python2 is update
- react: 16.4.1
- react-native: 0.56.0

So what's wrong ?

**Comment by happy32x** [comment]
I solved this problem as follows:

1 - Uninstall the app from device and emutor
2 - Clear watchman watches: watchman watch-del-all
3 - Delete the node_modules folder: rm -rf node_modules
4 - Reset Metro Bundler cache: rm -rf /tmp/metro-bundler-cache-*
5 - Remove haste cache: rm -rf /tmp/haste-map-react-native-packager-*
6 - edit package.json : 
          + react-native version to "55.4"
          + babel-preset-react-native to "4.0.0"
7 - npm install
8 - react-native run-android

**Comment by hagar0459** [comment]
is there solution not to downgrade the version of react native  as im stuck here ?
