### ISSUE TITLE
[Android] pointerEvents + opacity - unstable

### ISSUE THREAD

**Issue by danielgindi** [facebook/react-native#21026]
- [X] Review the documentation: https://facebook.github.io/react-native
  - [X] Search for existing issues: https://github.com/facebook/react-native/issues
  - [X] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
      Memory: 31.40 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.9.0 - /usr/local/bin/node
      npm: 6.2.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.5.0 => 16.5.0
      react-native: ^0.57.0-rc.4 => 0.57.0-rc.4
    npmGlobalPackages:
      react-native-cli: 2.0.
```

## Description
On Android, using `pointerEvents='box-only'` is unstable in the presence of `opacity` style.
Specifically, I'm animating a view's opacity, and after animating and reverting to original value - the pointerEvents property is no longer respected.

This is similar to https://github.com/facebook/react-native/issues/10216

## Reproducible Demo
```
        <Animated.View 
          style= {
            opacity: this._anims.opacity
          }]}
          pointerEvents={'box-none'}>
          
              Something clickable here

        </Animated.View>
```

Now animate this._anims.opacity to 0 and back to 1.

## More info & workaround

* When starting with an opacity of 1, the touches pass through.
* After changing opacity to 0 and back to 1 (whether by animation or by changing state) - touches stop passing through.
* If I set the view with a `backgroundColor: 'transparent'` - it works even after setting opacity to 0.

My guess is (a bit of educated guess, because I actually looked at the code), that by setting opacity to `0` React marks the view as something that's meant only for layout, and not for actually viewing things, so it can optimize it out.
And coming back to opacity 1 - the view comes back (I see it in layout inspector) but it is not marked as `BOX_ONLY` anymore. A backgroundColor of 'transparent' forces it to always be treated like an actual view.
The backgroundColor workaround in my opinion is exposing another bug - which is an optimization bug, not something that affects functionality.
And it is kind of nice to have right now as it allows controlling how react optimizes the view hierarchy. Food for thought: Maybe consider adding a special prop for that?

## Edit:
As @kabbi mentioned, there actually *is* a [property for disabling optimization on view](https://react-native.org/doc/view.html#collapsable).

**Comment by kabbi** [comment]
Hey, I've struggled with this for a while too, before I've read your issue. Actually, there is a flag to control, whether view is optimized out or not, it's [collapsable](https://react-native.org/doc/view#collapsable.html). It works as a workaround.

**Comment by danielgindi** [comment]
@kabbi Thanks for your comment! This seems like the best workaround for this issue... will try it soon.

**Comment by tayfunyugruk** [comment]
@danielgindi  i solved this problem by setting `top` position of the component so that it stays out of the actual view.

in my case i had picture on the screen and when it is clicked i was displaying a detail view for the clicked image and between detail image and original image i was displaying a transition image which basically resizes to detail view's image by translateX and translateY. When the detail view is closed everything was turning back to initial state but when i try to click same image it was not responding due to the `pointerEvents="box-none"` issue on Android (iOS is working well). i changed top position of transition image when animation is completed so it is not blocking touches anymore.

**Comment by danielgindi** [comment]
Hey bot, it's not fixed, but there's a workaround.

**Comment by danielgindi** [comment]
Annoying bot
