### ISSUE TITLE
[Bridge] +[RCTBridge initialize] logs error for false positives

### ISSUE THREAD

**Issue by jwyld** [facebook/react-native#2102]
I've got a class hierarchy where the base class is exposed to the JS world.  There are multiple subclasses which are used exclusively in the native world and will never be seen across the boundary.  The debug code in +[RCTBridge initialize] throws up the red screen because it sees these subclasses as not being exported.  I claim this is not an error situation.  This method should probably be using RCTLogWarn instead.  Failure to call RCT_EXPORT_MODULE() is not an error until there is a call site which ends up using the class which was not exported.

**Comment by nicklockwood** [comment]
That's a good idea.

In the meantime, adding RCT_EXPORT_MODULE() to your subclasses will let you keep working.

**Comment by nicklockwood** [comment]
This is now fixed: https://github.com/frantic/react-native/commit/7996c322119be6562109b1e07dc80c1a94f15148
