### ISSUE TITLE
react-native init fails in Windows 10

### ISSUE THREAD

**Issue by ancodeUDW** [facebook/react-native#21029]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: x64 Intel(R) Core(TM) i7-7740X CPU @ 4.30GHz
      Memory: 8.38 GB / 15.93 GB
    Binaries:
      npm: 6.2.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  2.2.0.0 AI-145.3360264

[skip envinfo]

## Description
I develop with Windows. I started a new react-native project after updating react-native, using react-native init myApp. However, it fails before ending the the initialization of the project. The message it leaves is:

> warning Unmet peer dependency "@babel/core@7.0.0-beta.47".
> error An unexpected error occured, please open a bug report with the information provided in "C:\\proyects\\myapp\\yarn-error.log".
> info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
> child_process.js:644
>     throw err;
>     ^
> 
> Error: Command failed: yarn add jest babel-jest babel-preset-react-native@^5 react-test-renderer@16.4.1 --dev --exact
>     at checkExecSyncError (child_process.js:601:13)
>     at execSync (child_process.js:641:13)
>     at generateProject (C:\proyectos\react-native\cheerio2\myapp3\node_modules\react-native\local-cli\init\init.js:105:7)
>     at Object.init (C:\proyectos\react-native\cheerio2\myapp3\node_modules\react-native\local-cli\init\init.js:53:5)
>     at run (C:\Users\ancode\AppData\Roaming\npm\node_modules\react-native-cli\index.js:302:7)
>     at createProject (C:\Users\ancode\AppData\Roaming\npm\node_modules\react-native-cli\index.js:249:3)
>     at init (C:\Users\ancode\AppData\Roaming\npm\node_modules\react-native-cli\index.js:200:5)
>     at Object.<anonymous> (C:\Users\ancode\AppData\Roaming\npm\node_modules\react-native-cli\index.js:153:7)
>     at Module._compile (module.js:652:30)
>     at Object.Module._extensions..js (module.js:663:10)

when checking C:\proyects\myapp\yarn-error.log" its two last lines said:

> Trace: 
>   Error: ENOENT: no such file or directory, open 'C:\proyecto\myApp\node_modules\@babel\highlight\node_modules\ansi-styles\index.js'
> 

If I try to do a 
`npm install`

inside of the project's folder and when it is finished I execute 
`react-native run-android`

it gives the following error (I assume that it is becuse it was not properly initialized):
> Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

Before the update, I could use react-native init whitout any problem. I have been trying fixes and alternatives, like

`react-native init {proj_name} --version react-native@0.55.4`

but the same error arises. The only way I could create a react-native project by now is via "create-react-native-app", but it limits me because I cannot install native modules.

## Reproducible Demo
`react-native init myApp`

**Comment by ancodeUDW** [comment]
I have reinstalled node to the latest version, uninstall react-native-cli and installed it again with a global flag
`npm install react-native-cli -g`

After that, I tried to run 
`react-native init AwesomeProject`

It throws an error and it still the same:

```
warning Unmet peer dependency "@babel/core@7.0.0-beta.47".
error An unexpected error occured, please open a bug report with the information provided in "C:\\proyectos\\react-native\\cheerio2\\AwesomeProject\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
child_process.js:645
    throw err;
    ^

Error: Command failed: yarn add jest babel-jest babel-preset-react-native@^5 react-test-renderer@16.4.1 --dev --exact
    at checkExecSyncError (child_process.js:602:13)
    at execSync (child_process.js:642:13)
```

after doing `react-native info`  inside the created AwesomeProject it gives me the following info:

```
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: x64 Intel(R) Core(TM) i7-7740X CPU @ 4.30GHz
      Memory: 8.38 GB / 15.93 GB
    Binaries:
      npm: 6.2.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  2.2.0.0 AI-145.3360264
```

In this case no mention of the packages. I did an npm install inside the project, but the information running the same instruction is the same.

The AwesomeProject project's package.js content is the following:

> {
>   "name": "AwesomeProject",
>   "version": "0.0.1",
>   "private": true,
>   "scripts": {
>     "start": "node node_modules/react-native/local-cli/cli.js start"
>   },
>   "dependencies": {
>     "react": "16.4.1",
>     "react-native": "0.56.1"
>   }
> }

So I understand is the last react-native version. Checking the other projects I created before the reinstalation, I can see that their package.js was basically the same, only diference that the react-native installed was 0.56.0, I created several projects to test `react-native init` and only one had the react native version 0.55.4, so I presume I happened to enter to that precise project when I was creating this issue

**Comment by hramos** [comment]
This should be fixed in 0.57. Stable is right around the corner if you're willing to wait, otherwise you can use `react-native init --version react-native@0.57.0-rc.4`

**Comment by ancodeUDW** [comment]
> This should be fixed in 0.57. Stable is right around the corner if you're willing to wait, otherwise you can use `react-native init --version react-native@0.57.0-rc.4`

Thank you for your reply.

I tried to run `react-native init --version react-native@0.57.0-rc.4 test`, and it still gave me the same "throw err" message.

**Comment by FibreFoX** [comment]
I'm currently re-checking stable versions that are working on Windows, so I might have found some things:

For me working versions are `0.55.4` and `0.57.1` that are being able to create and to compile (and running on my virtual android device). But I have found that `latest`/`0.57.2` does not work (which is default when not having that version-flag specified), so you might want to create a new project using 0.57.1?

```
react-native init newproject0571 --version react-native@0.57.1 
```

@hramos for information, when using latest 0.57.2 on Windows I'm hitting issue #21617

**Comment by ancodeUDW** [comment]
Actually no, the problem has not been solved yet. I am using expo because it does work. I tried to install last react-native version again last December from scratch, and the same problems arise.

Expo is ok for my current project, but it might become a bit short for some projects I plan to start in the near future, so I would be interested to be able to develop properly with react-native.

**Comment by hramos** [comment]
What about React Native 0.57.8 or 0.58.0-rc.2?

**Comment by shaktalles** [comment]
I just experienced the same issue, but running on linux mint.
After 'react-native init newProject' I get:

error An unexpected error occurred: "/home/talles/.cache/yarn/v4/npm-jest-cli-24.1.0-f7cc98995f36e7210cce3cbb12974cbf60940843/node_modules/jest-cli/.yarn-metadata.json: Unexpected end of JSON input".

info If you think this is a bug, please open a bug report with the information provided in "/home/tallles/Projects/tests/compara/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
child_process.js:661
    throw err;
    ^

Error: Command failed: yarn add jest babel-core@^7.0.0-bridge.0 babel-jest metro-react-native-babel-preset react-test-renderer@16.6.3 --dev --exact
    at checkExecSyncError (child_process.js:621:11)
    at execSync (child_process.js:658:13)
    at generateProject (/home/talles/Projects/tests/compara/node_modules/react-native/local-cli/init/init.js:96:7)
    at Object.init (/home/talles/Projects/tests/compara/node_modules/react-native/local-cli/init/init.js:45:3)
    at run (/home/talles/.nvm/versions/node/v11.4.0/lib/node_modules/react-native-cli/index.js:302:7)
    at createProject (/home/talles/.nvm/versions/node/v11.4.0/lib/node_modules/react-native-cli/index.js:249:3)
    at init (/home/talles/.nvm/versions/node/v11.4.0/lib/node_modules/react-native-cli/index.js:200:5)
    at Object.<anonymous> (/home/talles/.nvm/versions/node/v11.4.0/lib/node_modules/react-native-cli/index.js:153:7)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)

----x----

Here is the yarn error log:

[yarn-error.log](https://github.com/facebook/react-native/files/2869575/yarn-error.log)

**Comment by shaktalles** [comment]
Using RN 0.57.8 or 0.58.0-rc.2 I get:

error An unexpected error occurred: "/home/tallles/.cache/yarn/v4/npm-p-locate-3.0.0-322d69a05c0264b25997d9f40cd8a891ab0064a4/node_modules/p-locate/.yarn-metadata.json: Unexpected end of JSON input".
info If you think this is a bug, please open a bug report with the information provided in "/home/tallles/Projects/tests/compara/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
child_process.js:661
    throw err;
    ^

Error: Command failed: yarn add jest babel-jest metro-react-native-babel-preset react-test-renderer@16.6.3 --dev --exact

**Comment by luziferAzazel** [comment]
> What about React Native 0.57.8 or 0.58.0-rc.2?

I use version 0.58.5 and I also have this issue, expo is working but it's not optimal.

**Comment by shaktalles** [comment]
Running 'yarn cache clean' solved for me.

**Comment by thymikee** [comment]
This seems like an environment issue (with Yarn or Android Studio or Node), there's likely nothing we can do more about it. I'm gonna close it, because it seems like there's not many users encountering this.

**Comment by FibreFoX** [comment]
`not many users encountering this` seems so Apple-like ... please don't advocate this form of "solution" by just turning against us "small number of users" ;)

**Comment by thymikee** [comment]
Does it still happen for you? We usually get quite a lot of upvotes for the issues that happen for more users, so I assume this is just environmental issue, as solutions vary per user

**Comment by ancodeUDW** [comment]
It always happened to me when working with react-native init. I tried everything. But as the system did work with expo I ended moving to it and to forget to use pure react-native.

over this last months I have been doing a lot of changes and updates in node, npm, react-native, expo and android studio. In order to test it for this comment I tried to do run

react-native init test

It also failed to finish the init. 

error message:

> child_process.js:645
>     throw err;
>     ^
> 
> Error: Command failed: yarn add -D @babel/core @babel/runtime jest babel-jest metro-react-native-babel-preset react-test-renderer@16.8.3
>     at checkExecSyncError (child_process.js:602:13)
>     at execSync (child_process.js:642:13)
>     at executeCommand (C:\proyectos\react-native\test\test\node_modules\@react-native-community\cli\build\tools\PackageManager.js:26:40)
>     at Object.installDev (C:\proyectos\react-native\test\test\node_modules\@react-native-community\cli\build\tools\PackageManager.js:48:35)
>     at generateProject (C:\proyectos\react-native\test\test\node_modules\@react-native-community\cli\build\commands\init\init.js:116:18)
>     at Object.init (C:\proyectos\react-native\test\test\node_modules\@react-native-community\cli\build\commands\init\init.js:94:3)
>     at run (C:\Users\ancode\AppData\Roaming\npm\node_modules\react-native-cli\index.js:302:7)
>     at createProject (C:\Users\ancode\AppData\Roaming\npm\node_modules\react-native-cli\index.js:249:3)
>     at init (C:\Users\ancode\AppData\Roaming\npm\node_modules\react-native-cli\index.js:200:5)
>     at Object.<anonymous> (C:\Users\ancode\AppData\Roaming\npm\node_modules\react-native-cli\index.js:153:7)

I might do more tests with it today if I have a bit of time.

**Comment by thymikee** [comment]
We're working on a new init command for 0.60, feel free to try it: https://github.com/react-native-community/cli/blob/master/docs/init.md

Here's sample template: https://github.com/Esemesek/react-native-new-template so you can use it like this for now:
```sh
npx @react-native-community/cli init ProjectName --template react-native-new-template
```

**Comment by Michel-Lobo** [comment]
This error happens because of some conflict between yarn and npm. I took off yarn and everything worked

**Comment by overbound** [comment]
Any fix for this yet? Happening to me in Windows 10 too.
