### ISSUE TITLE
error: bundling failed: Error: ENOENT: no such file or directory, uv_cwd

### ISSUE THREAD

**Issue by patrice4github** [facebook/react-native#21038]
Sorry this comes back again with the latest 0.56. No steps to reproduce, the startup just won't work.

## Environment
Patrices-iMac:adn-083 patricegagnon$ react-native info
Scanning folders for symlinks in /Users/patricegagnon/_projects/outs/adn-083/node_modules (15ms)
(node:71272) ExperimentalWarning: The fs.promises API is experimental

  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
      Memory: 34.46 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.1.0 - /usr/local/bin/node
      Yarn: 1.6.0 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
    IDEs:
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 
    npmGlobalPackages:
      create-react-native-app: 1

## Description
This appears to be a regression as we've seen this before. The app refuses to start.

## Reproducible Demo
The entire project is shared on Dropbox. It just refuses to start:

[The project](https://www.dropbox.com/sh/0te2y5di4ns3u40/AACCvI7i4MHeliSx9nZpIxT1a?dl=0)

**Comment by patrice4github** [comment]
Here is the console stacktrace:

`error: bundling failed: Error: ENOENT: no such file or directory, uv_cwd
    at Object.resolve (path.js:1086:25)
    at loadPrivatePartialConfig (/Users/patricegagnon/_projects/outs/adn-083/node_modules/@babel/core/lib/config/partial.js:44:39)
    at loadFullConfig (/Users/patricegagnon/_projects/outs/adn-083/node_modules/@babel/core/lib/config/full.js:43:39)
    at transformSync (/Users/patricegagnon/_projects/outs/adn-083/node_modules/@babel/core/lib/transform-sync.js:15:38)
    at Object.transform (/Users/patricegagnon/_projects/outs/adn-083/node_modules/metro/src/reactNativeTransformer.js:163:5)
    at Object.<anonymous> (/Users/patricegagnon/_projects/outs/adn-083/node_modules/metro/src/JSTransformer/worker.js:204:23)
    at Generator.next (<anonymous>)
    at step (/Users/patricegagnon/_projects/outs/adn-083/node_modules/metro/src/JSTransformer/worker.js:328:291)
    at /Users/patricegagnon/_projects/outs/adn-083/node_modules/metro/src/JSTransformer/worker.js:328:521
 BUNDLE  [ios, dev] ../../index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1), failed.
`

**Comment by mjonesjr90** [comment]
Seeing the same issue

**Comment by patrice4github** [comment]
Have you tried rebooting?

**Comment by atyenoria** [comment]
I came across the same issue just now. npm reinstalling and rebooting work fine.

**Comment by CodeMuz** [comment]
Check if `$ yarn start` works. The metro bundler wasn't able to run on port 8081 for me and I needed to run `$ killall node`

**Comment by patrice4github** [comment]
I think that's what it is, why rebooting fixes it.
The process gets a hang of the port 8081, and somehow won't release it.

I call this a bug. There should be a proper termination of the metro
bundler so the port is always released properly.

**Comment by mjonesjr90** [comment]
Restarting worked for me as well - thanks!

**Comment by DalerAsrorov** [comment]
Thanks @CodeMuz, `$ killall node` and then `$ rm -rf ios/build/ && react-native run-ios` worked for me.

**Comment by kaushal9678** [comment]
Just close your current terminal window and run again ios, android commands. It will work. It worked for me.

**Comment by Amos729** [comment]
> Check if `$ yarn start` works. The metro bundler wasn't able to run on port 8081 for me and I needed to run `$ killall node`

Thanks. It solved my problem

**Comment by Digvijaykumar21** [comment]
digvijay@digvijay:~/Desktop/test$ kilall node

Command 'kilall' not found, did you mean:

  command 'killall' from deb psmisc

Try: sudo apt install <deb name>

digvijay@digvijay:~/Desktop/test$ killall node
node: no process found
digvijay@digvijay:~/Desktop/test$ killall -s KILL node
node: no process found
digvijay@digvijay:~/Desktop/test$ killall --s KILL node
node: no process found
digvijay@digvijay:~/Desktop/test$ killall node
node: no process found

**Comment by ramseykes** [comment]
Maybe you moved the file

**Comment by kaushal9678** [comment]
Just **remove your app from the emulator or device and close the terminal that running bundler.** Now start the process again by calling **react-native run-android or iOS** it will work.

**Comment by kelset** [comment]
Closing as it seems that it's just a caching issue.

**Comment by Youn-ha** [comment]
Rebooting fixed my problem out too. I tried every other methods but all failed. thanks for everyone

**Comment by al-exe** [comment]
> Check if `$ yarn start` works. The metro bundler wasn't able to run on port 8081 for me and I needed to run `$ killall node`

you saved my life, thank you

**Comment by Goran7777** [comment]
I have had same problem when my wi-fi conection stack on milisecond when script runs.

**Comment by dvetal** [comment]
I saw this on 57.7 . just a note.

**Comment by Gian-08** [comment]
ENOENT: no such file or directory, scandir 'C:\Users\gian-\gsm-v3\pages\node_modules\imagenes'
Failed building JavaScript bundle.   HELP ME PLEASE :(

**Comment by raimonkh** [comment]
I've seen this on MacOS when building on CircleCI (the android app).
```
Error: ENOENT: no such file or directory, open '/Users/distiller/repo/android/app/build/generated/assets/react/<apname>/release/CodePushHash'
```

I haven't found the issue yet

**Comment by toro705** [comment]
> 
> 
> I've seen this on MacOS when building on CircleCI (the android app).
> 
> ```
> Error: ENOENT: no such file or directory, open '/Users/distiller/repo/android/app/build/generated/assets/react/<apname>/release/CodePushHash'
> ```
> 
> I haven't found the issue yet

found any answers yet?

**Comment by raimonkh** [comment]
@toro705 in our case we created those files manually as the build process only required they "existed" although empty...

**Comment by ryancwalsh** [comment]
> Just close your current terminal window and run again ios, android commands. It will work. It worked for me.

Thanks @kaushal9678 . I was in Homestead Vagrant. I exited out of that terminal session, ran `vagrant ssh` again to get back in, ran `npm install` again, and then `npm start` worked without error.
