### ISSUE TITLE
onEndReached don't work ,when use "ListHeaderComponent",help

### ISSUE THREAD

**Issue by git-Asir** [facebook/react-native#21067]
## Environment
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.3
      CPU: x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 352.75 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.10.0 - /usr/local/bin/node
      Yarn: 1.5.1 - /usr/local/bin/yarn
      npm: 6.1.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.3, macOS 10.13, tvOS 11.3, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 23.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.1, 27.0.3
        API Levels: 19, 23, 24, 25, 26, 27
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 9.3/9E145 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.4.1 => 16.5.0
      react-native: ^0.56.1 => 0.56.1
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-update-cli: 0.1.0

## Description
i update my react-native from 0.50.3 to the lastest version 0.56.1,then i found some problem;
i found the flatlist the onEndReached function don't ccallback;
`onEndReached={this._onLoading} <= this func don't callback`
then i  test it bit by bit, and get rid of some parameters；
when i del "ListHeaderComponent" , i slide to the bottom to load ok；
Previously, flatlist init loadding would call onEndReached，but now init couldn't call；Does that change the call？

## Reproducible Demo

        ```
    <View style={{flex:1}}>
            <FlatList tabLabel="全部" 
                data={this.state.alldata}
                initialNumToRender={20}
                maxToRenderPerBatch={15}
                ref={flat => (this._flatList = flat)}
                keyExtractor={(item, index) => index.toString()}
                ListEmptyComponent={this._renderEmpty()}
                // getItemLayout={this._itemLayout}
                // onEndReached={this._onLoading}
                renderItem={this._renderItem}
                // onScroll={this._onScroll}
                refreshing={false}
                onEndReachedThreshold={0.5}
                onEndReached={
                    this._onBottomRefreshAll
                }
                ListHeaderComponent={this._renderHeader()}  <=when i del this line ,the flatlist is ok
                refreshControl={
                    <RefreshControl
                    onRefresh={this._onTopRefreshAll}
                    refreshing={this.state.isRefreshing}
                    title={this.state.isRefreshing ? "刷新数据中" : "松开立即更新"}
                    />
                }
            />
            <View style={{width:Screenwidth,height:50}}>
                <View style={{justifyContent:'center',alignItems:'center',padding:10,backgroundColor:'white'}}>
                    <TouchableOpacity onPress={()=>{this._submitExchange();}} style={{backgroundColor:'coral',borderRadius:5,width:Screenwidth-40,paddingVertical: 5,}}>
                        <Text style={{fontSize: 20,color:'white',textAlign:'center'}}>马上兑换</Text>
                    </TouchableOpacity>
                </View>
            </View>
            <Toast 
                ref="toast"
                style={{backgroundColor:'black'}}
                position='top'
                positionValue={300}
                fadeInDuration={750}
                fadeOutDuration={1000}
                opacity={0.7}
                />

            </View>
```

Let us know how to reproduce the issue. Include a code sample, share a project, or     share an app that reproduces the issue using https://snack.expo.io/. Please follow the guidelines for providing a MCVE: https://stackoverflow.com/help/mcve

**Comment by starzle** [comment]
Also seeing the same issue. I think ListHeaderComponent is the culprit. Can someone take a look? onEndReached is a pretty important method if we want to achieve endless scroll.

**Comment by git-Asir** [comment]
@starzle when i update to 0.57.0, flatlist is ok,you can try it

**Comment by moyueating** [comment]
I have the same issue. when  use  ListHeaderComponent, onEndReach can't called. if I remove the ListHeaderComponent it works ok!   version 0.56.1
