### ISSUE TITLE
[React-native 0.56] [Toggle Inspector] renderer.getInspectorDataForViewTag is not a function

### ISSUE THREAD

**Issue by TranLuongTuanAnh** [facebook/react-native#21065]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
React Native Environment Info:
    System:
      OS: macOS Sierra 10.12.6
      CPU: x64 Intel(R) Core(TM) i7-4771 CPU @ 3.50GHz
      Memory: 613.02 MB / 32.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 9.1.0 - ~/.nvm/versions/node/v9.1.0/bin/node
      npm: 5.5.1 - ~/.nvm/versions/node/v9.1.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.2, macOS 10.13, tvOS 11.2, watchOS 4.2
      Android SDK:
        Build Tools: 23.0.1, 23.0.2, 23.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.2, 27.0.3
        API Levels: 23, 25, 26, 27
    IDEs:
      Android Studio: 3.1 AI-173.4697961
      Xcode: 9.2/9C40b - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.4.1 => 16.4.2
      react-native: ^0.56.0 => 0.56.0
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-git-upgrade: 0.2.7
```

## Description
After upgrate RN to 0.56, I'm try Toggle Inspector but that below error occur when I click anywhere in screen
![simulator screen shot - iphone 7 - 2018-09-12 at 17 35 21](https://user-images.githubusercontent.com/6303302/45414748-0e4d0880-b6b7-11e8-90f3-83d0f3b488c6.png)

**Comment by swellingt0n** [comment]
Can confirm that upgrading to 0.57.0 of just the react-native package.json dependency did not fix the issue.

**Comment by swellingt0n** [comment]
Found out the solution to this problem for us. We had a library, `react-metrics`, from which we imported a single named export. Turns out the lib goes ahead and enables screen tracking (taps, gestures) metrics for you even if you don't import those other functions. So we did a deep import e.g. `import blah from react-metrics/some/sub/folder` and this resolved the issue.

**Comment by CxxyLucifer** [comment]
> Found out the solution to this problem for us. We had a library, `react-metrics`, from which we imported a single named export. Turns out the lib goes ahead and enables screen tracking (taps, gestures) metrics for you even if you don't import those other functions. So we did a deep import e.g. `import blah from react-metrics/some/sub/folder` and this resolved the issue.

could you code here ?

**Comment by TranLuongTuanAnh** [comment]
@CxxyLucifer
My solution is here: https://github.com/facebook/react-native/pull/21237/files

**Comment by CxxyLucifer** [comment]
> @CxxyLucifer
> My solution is here: https://github.com/facebook/react-native/pull/21237/files

3Q ,  nice

**Comment by CxxyLucifer** [comment]
> @CxxyLucifer
> My solution is here: https://github.com/facebook/react-native/pull/21237/files

3Q, nice

**Comment by cpojer** [comment]
I'll land the attached PR to fix this issue.
