### ISSUE TITLE
cannot separate APKs with different architecture [RN 0.57]

### ISSUE THREAD

**Issue by zenz** [facebook/react-native#21072]
## Environment
Run `react-native info` in your terminal and paste its contents here.

> react-native info
> 
>   React Native Environment Info:
>     System:
>       OS: Windows 10
>       CPU: x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
>       Memory: 2.53 GB / 7.91 GB
>     Binaries:
>       Yarn: 1.9.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
>       npm: 6.1.0 - C:\Program Files\nodejs\npm.CMD
>     React-Native Version: 0.57.0

## Description
while changing android/app/build.gradle to use APK separation
def enableSeparateBuildPerCPUArchitecture = true
This will make the assemble failure. and got following error message:

> ./gradlew assembleDebug
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem occurred configuring project ':app'.
> > Conflicting configuration : 'armeabi-v7a,x86' in ndk abiFilters cannot be present when splits abi filters are set :
> x86,armeabi-v7a
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 1s

have to also comment out ndk section to make it work. in previous version, only modify the def is OK.

**Comment by zenz** [comment]
OK, I see the solution on wiki, comment out ndk section is a must procedure.

**Comment by willymulyana** [comment]
can it coexist (split abi & ndk)?
i face issue that i need to split APKs (with `split abi`) while a library should set `ndk` (`react-native-splash-screen). Still not found working solution.
