### ISSUE TITLE
com.squareup.SocketRocket.NetworkThread(18): EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by zhongwuzw** [facebook/react-native#21086]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 611.18 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 9.5.0 - /usr/local/bin/node
      Yarn: 1.6.0 - /usr/local/bin/yarn
      npm: 6.2.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
    IDEs:
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1
      react-native: 0.56.0 => 0.56.0
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1

## Description
Crash randomly when run on `iOS`, the cause is when `WebSocket`'s delegate callback, the delegate already released, leads to `EXC_BAD_ACCESS`.

More detail can see #6117.

## Reproducible Demo
Crash randomly.

## potential fix `PR`
#19489

**Comment by Ghstart** [comment]
I had updated the project from 0.56 to 0.57 today! God bless me    O(∩_∩)O

**Comment by Ghstart** [comment]
> It looks like you are using an older version of React Native. Please update to the [latest release, v0.57](https://github.com/facebook/react-native/releases/tag/v0.57.0) and verify if the issue still exists.
> 
> The "⏪Old Version" label will be removed automatically once you edit your original post with the results of running `react-native info` on a project using the latest release.

Still crashed on V0.57!!!!

**Comment by zhongwuzw** [comment]
@hramos Apologize if disturb, I see you already imported #19489 , any progress about this? 🤔

**Comment by hramos** [comment]
Left some comments in #19489.

**Comment by ishigamii** [comment]
no update on this issue, can we safely add this PR to our code ? if not what can we do to avoid the many crash caused by it ? 👍  Thanks a lot.

**Comment by hramos** [comment]
FYI: latest proposed fix is at #22439 (which is referenced above).
