### ISSUE TITLE
Image are no longer bundle on Android

### ISSUE THREAD

**Issue by keldorus** [facebook/react-native#21099]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
React Native Environment Info:
    System:
      OS: Windows 7
      CPU: x64 Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz
      Memory: 2.95 GB / 11.90 GB
    Binaries:
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.1.0.0 AI-173.490780

react: 16.5.0
react-native: 0.57.0

## Description
Since we pass from 0.55.4 to 0.57.0, assets images use with require are no longer bundle on our android release package.

I try the solution in this issue https://github.com/facebook/react-native/issues/20358, it's work BUT this copy my image in the android asset folder, and i think it's not the point of Image and the require system.

I think there is a problem with the bundler but only in Android.

## Reproducible Demo
Just use a require for a .png image and use on an Image source.
This can only reproduce on a build, not on a dev debug ...

**Comment by sharmilee** [comment]
I am also facing same issue! Any solution?

**Comment by keldorus** [comment]
For now, I downgrade React-Native to the 0.55.4 version, cause we have some dev on Windows and 0.56 won't work for them.

**Comment by keldorus** [comment]
So, I found the problem, I was using RN 0.57.0 but with an older version of graddle (cause of some lib)

I update to the good version of graddle, and the build package the images well.

**Comment by keldorus** [comment]
We move from Gradle 2.3.3 to 3.1.4.
And update compileSDKVersion frome 26 to 27 
And libVersion from 26.1.0 to 27.1.1

**Comment by danlugo92** [comment]
Having this issue with gradle 3.5.1 @keldorus :

```bash
$ react-native info
React Native Environment Info:
    System:
      OS: macOS Sierra 10.12.6
      CPU: x64 Intel(R) Core(TM) i5 CPU       M 520  @ 2.40GHz
      Memory: 113.66 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.9.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.2.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.0, macOS 10.13, tvOS 11.0, watchOS 4.0
      Android SDK:
        Build Tools: 23.0.1, 25.0.0, 26.0.3, 28.0.2
        API Levels: 23, 25, 26, 28
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 9.0/9A235 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.4.7 => 16.4.7 
      @types/react-native: ^0.56.5 => 0.56.5 
      react: 16.4.1 => 16.4.1 
      react-native: 0.57.1 => 0.57.1 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

```bash
$ cd android && ./gradlew -v
Gradle 3.5.1
------------------------------------------------------------

Build time:   2017-06-16 14:36:27 UTC
Revision:     d4c3bb4eac74bd0a3c70a0d213709e484193e251

Groovy:       2.4.10
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_144 (Oracle Corporation 25.144-b01)
OS:           Mac OS X 10.12.6 x86_64

```

**Comment by keldorus** [comment]
Now we are here:

```
------------------------------------------------------------
Gradle 4.4
------------------------------------------------------------

Build time:   2017-12-06 09:05:06 UTC
Revision:     cf7821a6f79f8e2a598df21780e3ff7ce8db2b82

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_181 (Oracle Corporation 25.181-b13)
OS:           Windows 7 6.1 amd64
```
