### ISSUE TITLE
Xcode 10 GM seed report stdc++ missing

### ISSUE THREAD

**Issue by SuperMarioBean** [facebook/react-native#21091]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Environment:
  OS: macOS 10.14
  Node: 8.12.0
  Yarn: 1.9.4
  npm: 6.4.1
  Watchman: 4.9.0
  Xcode: Not Found
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: 0.48.0 => 0.48.0

## Description
hi there, I use Xcode 10 GM seed recently and I found apple remove the stdc++ lib, and I check the lastest version of react-native and I found subspec "Core" has the stdc++ as its dependency, so, I want to know How can I get my project with react native build success with Xcode 10 GM seed...thanks

**Comment by hramos** [comment]
You'll likely need to update your project to use a more recent version of React Native, in order to use Xcode 10. Closing as this issue is more of a question.
