### ISSUE TITLE
Slider jumps if you tap it

### ISSUE THREAD

**Issue by aalzanki** [facebook/react-native#21103]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
[skip envinfo]
I'm running on iPhone SE, iOS 11.4, RN version 0.57.

## Description
If you tap the circle of a slider, you'll see it jump. It seems like the slider might not be calculating the delta between the touch's position and the position of the circle at the start of the drag. It's a lot more noticeable in the simulator than on device. 

## Reproducible Demo
https://snack.expo.io/rJnz7mOOQ

**Comment by hramos** [comment]
Thanks for the repro. This is what it looks like:

![ezgif-5-89181f93a6](https://user-images.githubusercontent.com/165856/45515004-d1871d00-b75b-11e8-9836-a77e38720a56.gif)

**Comment by zhongwuzw** [comment]
@aalzanki , It's a bug of `iOS`, which means `UISlider` has this issue, you can try set a `thumbImage` explicitly like below to fix:

```
<Slider style={{width: 300}} thumbImage={require('./thumb.png')}/>
```
