### ISSUE TITLE
Cannot iterate over any array.entries()

### ISSUE THREAD

**Issue by TheBlusky** [facebook/react-native#21114]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: x64 Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
      Memory: 6.06 GB / 15.94 GB
    Binaries:
      Node: 10.8.0 - D:\Installs\nodejs\node.EXE
      npm: 6.1.0 - D:\Installs\nodejs\npm.CMD

React-Native 0.57.0
```

## Description
Array `entries()` method does not work / is not spec. compliant, iterator over it (using `of` or `next` throws error).

Is probably linked to https://github.com/facebook/react-native/issues/19446

## Reproducible Demo

The following codes snippet does not work and provide misc. exceptions:

### Example 1
```
var arr = ['a', 'b', 'c'];
var eArr = arr.entries();

for (let e of eArr) { // Break
  console.log(e);
}

```

Error: `TypeError: undefined is not a function (evaluating '_iterator[typeof Symbol === "function" ? Symbol.iterator : "@@iterator"]()')`
### Example 2

```
    const arr = ['a', 'b', 'c']
    var eArr = arr.entries();
    console.log(eArr.next().value); // Break
    console.log(eArr.next().value);
    console.log(eArr.next().value);
```

Error: `TypeError: undefined is not a function (evaluating 'eArr.next()')`

**Comment by vonovak** [comment]
Does this happen on android / ios / both? Does it happen when running in debugger? Could be this is something specific to the JSC that ships with android.

**Comment by TheBlusky** [comment]
- I only tested with Android (I don't have an IOS phone).
- I did not try it with a debugger (my app have native synchronous depedencies)

However, I updated the JSC using https://github.com/react-community/jsc-android-buildscripts and it ~~solved~~ worked arround the issue.

Is there any plan on updating Android JSC within react-native ?

**Comment by vonovak** [comment]
@TheBlusky I think there are plans to make it easier to run RN with any JS VM. More here https://github.com/facebook/react-native/issues/19737
