### ISSUE TITLE
resize and compress image before upload ?

### ISSUE THREAD

**Issue by alainib** [facebook/react-native#21112]
Hello. 
I work on an app who make pictures from camera and upload them to an API. 
Currently i use "react-native-image-crop-picker" package from npm who work very well for resizing and compressing but lost the EXIF data. 

Or i need EXIF , i opened a issue on "react-native-image-crop-picker" github but no response after few weeks. 

Is there a way to compress and or resize image stored on device with react ? i tryed js lib like "piexifjs" but didn't found how to make it work :(

any advice are welcomed. thanks

**Comment by NativLouie** [comment]
@alainib did you figure anything out?

**Comment by alainib** [comment]
@NativLouie

Do you need to keep exif ?
we make à package ton copy exif from an image to another one (compressed with ''react native image crop picker' '). It work good on Android

On ios It dont because systèm remove exif before upload It using post
Maybe or can work with upload base64 but we didnt test it
