### ISSUE TITLE
How can I open a specific component of my React Native application from an Native Android Activity in Java?

### ISSUE THREAD

**Issue by Aravind-WMG** [facebook/react-native#21128]
**Environment**

> > Environment:
> >   OS: Windows 10
> >   Node: 8.11.1
> >   Yarn: Not Found
> >   npm: 3.10.10
> >   Watchman: Not Found
> >   Xcode: N/A
> >   Android Studio: Version  3.1.0.0 AI-173.4720617
> > 
> > Packages: (wanted => installed)
> >   react: 16.5.0 => 16.5.0
>  react-native: 0.57.0 => 0.57.0
> > 

**Description**
An Android app is integrated with React Native(RN) following this [doc](https://facebook.github.io/react-native/docs/integration-with-existing-apps), where page A is in Android and page B is in RN. On click of a button in page A, RN activity started and page B get loaded..so my Question is how the button on page A can be RN component or How can I open a specific component of my React Native application from an Native Android Activity in Java?

**Reproducible Demo**
I cant have a demo for this since its question about an approach. I guess I have to check the ReactActivity in react-native repo to see how the a bundle gets rendered to the root view. The only thing that changes in my case is that I don't want to render to root view.
Here is files [Link1](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/ReactActivity.java) and [Link2](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/ReactActivityDelegate.java)

**Comment by radko93** [comment]
@facebook-github-bot stack-overflow
