### ISSUE TITLE
accessibilityStates = [disabled] can not be removed on iOS

### ISSUE THREAD

**Issue by benzman81** [facebook/react-native#21122]
## Environment
React Native Environment Info:
System:
OS: macOS High Sierra 10.13.5
CPU: x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
Memory: 40.76 MB / 8.00 GB
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 8.11.3 - /usr/local/bin/node
npm: 5.6.0 - /usr/local/bin/npm
SDKs:
iOS SDK:
Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
IDEs:
Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
npmPackages:
react: 16.5.0 => 16.5.0
react-native: 0.57.0 => 0.57.0
npmGlobalPackages:
react-native-app-id: 0.0.5
react-native-cli: 2.0.1

## Description
If accessibilityStates is set to [disabled] it can not be removed on iOS by setting accessibilityStates to empty array or null. The Accessibility Inspector still shows the button as disabled.

## Reproducible Demo
Simple attached App.js to reproduce by activating button on switch. (needed to rename to txt)
[App.txt](https://github.com/facebook/react-native/files/2383774/App.txt)

**Comment by markowork** [comment]
Any solution/workaround to this @benzman81? I'm having the same issue?

**Comment by jmensch1** [comment]
I'm having the same problem with the the 'selected' option for accessibilityStates -- once the state is set to 'selected', it can't be removed.

**Comment by markowork** [comment]
Yep, one possible workaround is to force recreating of your element, setting something like key=`new Date()` but it doesn't help in all cases (for example if your element has an animation)

**Comment by elucaswork** [comment]
This issue got fixed on v0.58.0 with this commit https://github.com/facebook/react-native/commit/5eaa2d29c0c4c633a40f7241408737c754edea84

cc @hramos @cpojer
