### ISSUE TITLE
Inverted scrollsToTop scrolls to bottom

### ISSUE THREAD

**Issue by raphaelrk** [facebook/react-native#21126]
## Environment
```
Environment:
  OS: macOS High Sierra 10.13.5
  Node: 10.4.1
  Yarn: 1.7.0
  npm: 6.4.1
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: Not Found

Packages: (wanted => installed)
  react: ^16.4.2 => 16.4.2
  react-native: https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz => 0.55.4
```

## Description
When a FlatList has both `scrollsToTop` and `inverted` enabled, tapping on the iOS status bar scrolls to the bottom of the list, which isn't a behavior I've seen in any native apps. It would be great if this was either changed or it was possible to do e.g. `scrollsToBottom={true}` or `scrollsToTopDirection={'inverted'}`.

## Reproducible Demo
[Expo Snack](https://snack.expo.io/@raphaelrk/inverted-scrollstotop)

**Comment by raphaelrk** [comment]
This has been an annoying UX issue since I started using React Native ~10 months ago, would be a really great fix for being able to quickly scroll to the top of a chat screen or other `inverted` screens!

**Comment by kelset** [comment]
It seems to me that you are using Expo, so I suggest you open a dedicated issue there 🤷‍♂️

Our can you reproduce on a new `react-native init` project with `0.57.2`?

**Comment by raphaelrk** [comment]
Tested with the same code from the snack on a new `react-native init` (`0.57.4`) and still have the issue that scrollsToTop scrolls to the bottom

**Comment by MartinMasek** [comment]
Have you found any workaround while it's getting fixed?

**Comment by emilioicai** [comment]
This PR should fix it: https://github.com/facebook/react-native/pull/27574
