### ISSUE TITLE
Android: Bundled assets not being included in generated (signed) APK

### ISSUE THREAD

**Issue by djw27** [facebook/react-native#21132]
## Environment
React Native Environment Info:
&nbsp;&nbsp;System:
&nbsp;&nbsp;&nbsp;&nbsp;OS: macOS High Sierra 10.13.6
&nbsp;&nbsp;&nbsp;&nbsp;CPU: x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
&nbsp;&nbsp;&nbsp;&nbsp;Memory: 2.79 GB / 16.00 GB
&nbsp;&nbsp;&nbsp;&nbsp;Shell: 3.2.57 - /bin/bash
&nbsp;&nbsp;Binaries:
&nbsp;&nbsp;&nbsp;&nbsp;Node: 8.11.1 - /usr/local/bin/node
&nbsp;&nbsp;&nbsp;&nbsp;Yarn: 1.0.2 - /usr/local/bin/yarn
&nbsp;&nbsp;&nbsp;&nbsp;npm: 6.1.0 - /usr/local/bin/npm
&nbsp;&nbsp;&nbsp;&nbsp;Watchman: 4.7.0 - /usr/local/bin/watchman
&nbsp;&nbsp;SDKs:
&nbsp;&nbsp;&nbsp;&nbsp;iOS SDK:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
&nbsp;&nbsp;&nbsp;&nbsp;Android SDK:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Build Tools: 23.0.1, 23.0.2, 24.0.0, 24.0.1, 24.0.2, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 27.0.1, 27.0.3
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;API Levels: 23, 24, 25, 26, 27
&nbsp;&nbsp;IDEs:
&nbsp;&nbsp;&nbsp;&nbsp;Android Studio: 3.1 AI-173.4907809
&nbsp;&nbsp;&nbsp;&nbsp;Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
&nbsp;&nbsp;npmPackages:
&nbsp;&nbsp;&nbsp;&nbsp;react: ^16.5.0 => 16.5.1 
&nbsp;&nbsp;&nbsp;&nbsp;react-native: ^0.57.0 => 0.57.0 
&nbsp;&nbsp;npmGlobalPackages:
&nbsp;&nbsp;&nbsp;&nbsp;create-react-native-app: 1.0.0
&nbsp;&nbsp;&nbsp;&nbsp;react-native-cli: 2.0.1
&nbsp;&nbsp;&nbsp;&nbsp;react-native-git-upgrade: 0.2.7

## Description
This has been an issue for a long time, however, we've put up with it until now.

When following the official guide on generating release builds for Android (https://facebook.github.io/react-native/docs/signed-apk-android), we correctly generate a signed APK at `android/app/build/outputs/apk/${flavorName}/app-${flavorName}.apk`, however, the app crashes on launch as there are no assets included in the APK:

<img width="1440" alt="screen shot 2018-09-15 at 17 16 51" src="https://user-images.githubusercontent.com/4228432/45588335-2b7a1500-b90b-11e8-87ae-11a416f25ea0.png">

During build, the assets are correctly generated at `android/app/build/intermediates/assets/${flavourName}/`, but simply aren't included in the output APK.

Now the workaround, which there seem to be a lot of people using in one form or another, is to copy the contents of `android/app/build/intermediates/assets/${flavourName}/` to `android/app/src/main/assets/` and generate the APK again (either through `$ ./gradlew assembleRelease` or Android Studio, it makes no difference).

A lot of people have put up with this as an issue by running `$ react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/` manually before running `assembleRelease`, which simply outputs the generated assets in the folder I mentioned above.

The question is, why aren't the assets generated during the build process (the ones found in `android/app/build/intermediates/assets/${flavourName}/`), included in the APK?

This is what the APK should look like:

<img width="1440" alt="screen shot 2018-09-15 at 17 13 25" src="https://user-images.githubusercontent.com/4228432/45588329-0f767380-b90b-11e8-96b3-d5a58cde6ee2.png">

Like I say, this has been a long term issue for us, and we're not on the latest version of react native but there have been no changes to the `react.gradle` since 0.53. I will of course test the latest version all the same.

EDIT: Upgrading to 0.57 this is still an issue

**Comment by Christian-Athom** [comment]
I have had the same problems on 0.56, upgrading to 0.57 and i'm unable to build my project because of a Metro crash "FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory"

**Comment by kigawas** [comment]
Same here. Using the latest RN.
```

  React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 262.17 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.11.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5014246
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0
      react-native: 0.57.1 => 0.57.1
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
```

**Comment by ttawan** [comment]
> Same here. Using the latest RN 😕
> 
> As the reference above, the PR #21408 can resolve the `index.android.bundle` problem 😄
> 
> ```diff
>          def currentAssetsCopyTask = tasks.create(
>              name: "copy${targetName}BundledJs",
>              type: Copy) {
>              group = "react"
>              description = "copy bundled JS into ${targetName}."
>  
>             from jsBundleDir
>             into file(config."jsBundleDir${targetName}" ?:
>                 "$buildDir/intermediates/assets/${targetPath}")
>                 
> +            // Workaround for Android Gradle Plugin 3.2+ new asset directory
> +            from jsBundleDir
> +            into file(config."jsBundleDir${targetName}" ?:
> +                "$buildDir/intermediates/merged_assets/${targetPath}/merge${targetName}Assets/out")
> ```

Thanks! for this. Problem is solved!

**Comment by GitHubGreg** [comment]
Is there a similar workaround for apps built using Expo?

**Comment by motogod** [comment]
@ttawan I face the similar issue recently, where is the file about `from jsBundleDir` ? Thanks.

**Comment by testshallpasswork** [comment]
I recently upgraded to 0.59.8 and this seem still be an issue. App Center creates the bundle but it is not included in final apk as issue states. I do see an assets and res dir but no `android.index.bundle`.

react: 16.8.3 
react-native: 0.59.8
build gradle: 3.3.1
