### ISSUE TITLE
React Native focus not changed in tvOS

### ISSUE THREAD

**Issue by skkakadiya** [facebook/react-native#21144]
I added [react-native-drawer](https://github.com/root-two/react-native-drawer) in [Video Player](https://www.npmjs.com/package/react-native-video) component and able to open/close drawer but not able to change focus inside the drawer.

Here is the drawer code:

```
<View 
    style={{ flex: 1, backgroundColor: '#fff'}}
>
    <View style={{ height: 150}}>
        <TouchableOpacity hasTVPreferredFocus={true} onPress={() => {this.props.callback(); }}>
            <View style={{ width: 40, backgroundColor: '#e6e6e6' , padding: 10, borderRadius: 5, marginLeft: 10, marginTop: 10 }}>
                <Image style={styles.image} source={require('./images/close.png')} />
            </View>
        </TouchableOpacity>
        <View style={styles.container}>
            <TouchableOpacity onPress={() => {this.setState({ selected: 'play' });}}>
                <View style={{ backgroundColor: this.state.selected === 'play'? '#fbd2c1' : '#FFFFFF' , padding: 10, borderRadius: 5, width: 40 }}>
                    <Image style={styles.image} source={require('./images/play.png')} />
                </View>
            </TouchableOpacity>                        
            
            <TouchableOpacity onPress={() => {this.setState({ selected: 'time' });}}>
                <View style={{ backgroundColor: this.state.selected === 'time'? '#fbd2c1' : '#FFFFFF' , padding: 10, borderRadius: 5, width: 40 }}>
                    <Image style={styles.image} source={require('./images/clock.png')} />
                </View>
            </TouchableOpacity>
            
            <TouchableOpacity onPress={() => {this.setState({ selected: 'user' });}}>
                <View style={{ backgroundColor: this.state.selected === 'user'? '#fbd2c1' : '#FFFFFF' , padding: 10, borderRadius: 5, width: 40 }}>
                    <Image style={styles.image} source={require('./images/user.png')} />
                </View>
            </TouchableOpacity>

            <TouchableOpacity onPress={() => {this.setState({ selected: 'resolution' });}}>
                <View style={{ backgroundColor: this.state.selected === 'resolution' ? '#fbd2c1' : '#FFFFFF' , padding: 10, borderRadius: 5 }}>
                    <Image style={styles.image} source={require('./images/computer.png')} />
                </View>
            </TouchableOpacity>
        </View>
    </View>
    <View style={{ flex: 1, flexDirection: 'column' }}>
        { this.renderUI() }    
    </View>
                    
</View>
```

**RN Info**:

React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.4
      CPU: x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
      Memory: 25.10 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.3.0 - /usr/local/bin/node
      npm: 6.4.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 24.0.1, 25.0.0, 25.0.2, 26.0.1, 26.0.3, 27.0.3, 28.0.2
        API Levels: 23, 24, 25, 26
    IDEs:
      Android Studio: 2.3 AI-162.4069837
      Xcode: 9.4/9F1027a - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0
      react-native: 0.57.0 => 0.57.0
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

**Comment by skkakadiya** [comment]
I created the demo to reproduce [this issue](https://github.com/skkakadiya/RNFocusDemo/tree/master).

**Comment by rickhanlonii** [comment]
Hey @skkakadiya, sorry for the delay, unfortunately there's not much that core can do here

This issue should be filed either in [react-native-drawer]( https://github.com/root-two/react-native-drawer/issues) or [react-native-video](https://github.com/react-native-community/react-native-video/issues)
