### ISSUE TITLE
ava.lang.NullPointerException Attempt to invoke virtual method 'int android.view.View.getId()' on a null object reference 

### ISSUE THREAD

**Issue by DanGDroid** [facebook/react-native#21149]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Environment:
  OS: macOS High Sierra 10.13.6
  Node: 10.7.0
  Yarn: 1.9.4
  npm: 6.1.0
  Watchman: 4.7.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4670197

Packages: (wanted => installed)
 react: 16.4.1 => 16.4.1 
 react-native: 0.56.0 => 0.56.0

## Description
as in #10845 that was labeled as resolved this bug still happens.
related:
#20288
#17178

`common crash Yuval
java.lang.NullPointerException Attempt to invoke virtual method 'int android.view.View.getId()' on a null object reference 
    NativeViewHierarchyManager.java:537 com.facebook.react.uimanager.NativeViewHierarchyManager.dropView
    NativeViewHierarchyManager.java:431 com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren
    UIViewOperationQueue.java:180 com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute
    UIViewOperationQueue.java:819 com.facebook.react.uimanager.UIViewOperationQueue$1.run
    UIViewOperationQueue.java:926 com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches
    UIViewOperationQueue.java:47 com.facebook.react.uimanager.UIViewOperationQueue.access$2100
    UIViewOperationQueue.java:986 com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded
    GuardedFrameCallback.java:31 com.facebook.react.uimanager.GuardedFrameCallback.doFrame
    ReactChoreographer.java:136 com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame
    ChoreographerCompat.java:107 com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame
    Choreographer.java:979 android.view.Choreographer$CallbackRecord.run
    Choreographer.java:790 android.view.Choreographer.doCallbacks
    Choreographer.java:718 android.view.Choreographer.doFrame
    Choreographer.java:967 android.view.Choreographer$FrameDisplayEventReceiver.run
    Handler.java:808 android.os.Handler.handleCallback
    Handler.java:101 android.os.Handler.dispatchMessage
    Looper.java:166 android.os.Looper.loop
    ActivityThread.java:7425 android.app.ActivityThread.main
    Method.java:-2 java.lang.reflect.Method.invoke
    Zygote.java:245 com.android.internal.os.Zygote$MethodAndArgsCaller.run
    ZygoteInit.java:921 com.android.internal.os.ZygoteInit.main
`

## Reproducible Demo
Let us know how to reproduce the issue. Include a code sample, share a project, or     share an app that reproduces the issue using https://snack.expo.io/. Please follow the guidelines for providing a MCVE: https://stackoverflow.com/help/mcve

**Comment by chrusart** [comment]
https://github.com/facebook/react-native/pull/20465 in master
