### ISSUE TITLE
[XMLHttpRequest] Sending file using XHR

### ISSUE THREAD

**Issue by eltoob** [facebook/react-native#2115]
I tried to send files using XHR to Amazon S3 and I noticed that the file is getting corrupted with added text
``` 
var url = "some_local_path/test.mp4"
var s3_url = "https://mybucket.s3.amazonaws.com/test.mp4"
xhr.open('PUT', s3_url, true)
xhr.setRequestHeader('Key', 'test.mp4')
xhr.setRequestHeader('Content-type', 'video/mp4')
xhr.setRequestHeader('X-Amz-Credential', 'credentials')
xhr.setRequestHeader('X-Amz-Signature', 'signature')
xhr.setRequestHeader('Date', 'Some Date')
xhr.setRequestHeader('X-Amz-Algorithm', 'AWS4-HMAC-SHA256')
xhr.setRequestHeader('X-Amz-Acl', 'public-read')

var formData = new FormData();
formData.append("test.mp4", {uri: url});

xhr.send(formData)

```

**Comment by nicklockwood** [comment]
Can you clarify what you mean by "adding text?"

**Comment by eltoob** [comment]
If I cat the test.mp4 it's containing extra characters

```
--zWGdmuxl4sxXXXXXXXXXXXXXXXxQjaHYwaodP7.FWOAa_-s7
content-disposition: form-data; name="test.mp4"

file:///myPath
--zXXdmuxl4sxqXSTnilUXXXXXXXXXXXXwaodP7.FWOAa_-s7--
```

**Comment by nicklockwood** [comment]
Cc: @philikon

**Comment by philikon** [comment]
This is not corruption, this is the intended result. `FormData` is the appropriate body for a `multipart/form-data` POST request. The REST API you're talking to seems to not support `multipart/form-data`, which makes sense, since it's a `PUT` request you're issuing. Lose the `FormData` and you should be fine:

    xhr.open('PUT', s3_url);
    ... // setRequestHeader calls
    xhr.send({uri: url});

**Comment by philikon** [comment]
Keep in mind that you'll still have to write an `RCTURLRequestHandler` implementation to handle whatever `url` you want to actually upload. React Native doesn't currently ship with a resolver for `file://` URIs out of the box (though we should probably add one, right @nicklockwood). It shouldn't be too hard to write one.

**Comment by nicklockwood** [comment]
@philikon actually the default RCTHTTPRequestHandler handles file:// urls as well as http(s). It's probably not optimal, and I've been considering providing a separate file request handler, but it should do the job.

**Comment by philikon** [comment]
Ah, I stand corrected. Sweet!

**Comment by eltoob** [comment]
That works great thanks @nicklockwood and @philikon

**Comment by 1stman** [comment]
@philikon, @nicklockwood , i trying to upload video with youtube v3 api, i fix my code like in your example, but `xhr.upload.onprogress` is not working with it. But when i use `FormData` it works. What i need to do to handle upload progress? Sorry for my english.
