### ISSUE TITLE
rn0.57 'React/RCTEventEmitter.h' file not found

### ISSUE THREAD

**Issue by orzhtml** [facebook/react-native#21161]
- [ ] Review the documentation: https://facebook.github.io/react-native
  - [ ] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Run `react-native info` in your terminal and paste its contents here.
React Native Environment Info:
    System:
      OS: macOS Sierra 10.12.6
      CPU: x64 Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
      Memory: 232.36 MB / 8.00 GB
      Shell: 5.2 - /bin/zsh
    Binaries:
      Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
      Yarn: 1.9.4 - ~/.yarn/bin/yarn
      npm: 6.3.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.2, macOS 10.13, tvOS 11.2, watchOS 4.2
      Android SDK:
        Build Tools: 23.0.1, 23.0.2, 23.0.3, 24.0.2, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 27.0.3
        API Levels: 23, 24, 25, 26, 27
    IDEs:
      Android Studio: EAP AI-171.4010489 AI-171.4010489
      Xcode: 9.2/9C40b - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: 0.57.0 => 0.57.0 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description
Describe your issue in detail. Include screenshots if needed. If this is a regression, let us know.
react-native init xxx
cd xxx
react-native run-ios

xxx/node_modules/react-native/Libraries/LinkingIOS/RCTLinkingManager.h:14:36: Pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)

xxx/node_modules/react-native/Libraries/LinkingIOS/RCTLinkingManager.h:25:29: Block pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)

xxx/node_modules/react-native/Libraries/LinkingIOS/RCTLinkingManager.h:10:9: 'React/RCTEventEmitter.h' file not found

## Reproducible Demo
Let us know how to reproduce the issue. Include a code sample, share a project, or     share an app that reproduces the issue using https://snack.expo.io/. Please follow the guidelines for providing a MCVE: https://stackoverflow.com/help/mcve

**Comment by hramos** [comment]
Can you try using Xcode 9.4 or newer, when using RN 0.57?

**Comment by tpisto** [comment]
Please check information from the issue: https://github.com/facebook/react-native/issues/21071

**Comment by kelset** [comment]
(closing as inactive, ty tpisto for the link)
