### ISSUE TITLE
SwipeableFlatList bleeding pixel

### ISSUE THREAD

**Issue by Dimous** [facebook/react-native#21167]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: x64 Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
      Memory: 589.87 MB / 5.45 GB
    Binaries:
      Yarn: 1.9.4 - C:\Users\kasim\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.1.0.0 AI-173.4907809

## Description
When you swipe an item, you can see "bleeding" on the right of it. It is noticable on a physical device. _I guess, "x" property should be rounded._

Please, wait till gif below is loaded

![swipablelistview](https://user-images.githubusercontent.com/283939/45687427-2a0e4e00-bb92-11e8-9aad-a4ef36857483.gif)

**Comment by hramos** [comment]
Thanks for the visual demonstration. Can you include a code sample that we can use to repro this?

**Comment by Dimous** [comment]
https://snack.expo.io/Bk54hV1tQ

You probably won't see it on emulator or a hdpi-device. _I use Samsung Galaxy Note II._

On the screenshot below there is a barely noticeable bleeding. Don't let the blurring of icons mislead you. The edges of swipable items should be crisp (and they are, when the horizontal position has an integer value).
![bleeding](https://user-images.githubusercontent.com/283939/45728677-61214580-bc0c-11e8-91d5-97c4276c6247.png)

**Comment by kelset** [comment]
Hello there 👋 this issue has been reported for an old version of React Native. Ideally we'd like everyone to be using 0.59 (see the [awesome changes](https://facebook.github.io/react-native/blog/2019/03/12/releasing-react-native-059) it brought) but we know updating can be a pain.

Also, both ListView and SwipeableListView are going to be removed, and your repro uses that.

But please, if it's actually still an issue with 0.59 please comment below and we can reopen it. Even better, please send us a pull request with a fix 😊
