### ISSUE TITLE
Use react-native as a framework on iOS about archive problem

### ISSUE THREAD

**Issue by baiwhte** [facebook/react-native#21160]
### Environment:
React Native Environment Info:
System:
OS: macOS High Sierra 10.13.6
CPU: x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
Memory: 48.41 MB / 8.00 GB
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 10.6.0 - /usr/local/bin/node
Yarn: 1.7.0 - /usr/local/bin/yarn
npm: 6.1.0 - /usr/local/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
SDKs:
iOS SDK:
Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
IDEs:
Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
npmPackages:
react: 16.5.0 => 16.5.0
react-native: 0.57.0 => 0.57.0
npmGlobalPackages:
react-native-cli: 2.0.1

### Description
according to the tutorial(https://facebook.github.io/react-native/docs/linking-libraries-ios) Manual linking into ios framework(mach-o type is static library) and quoted in the example project, the project can run on simulator and iphone device, **but cannot archive success.** See the attachment for the project.

How can I solve this problem.

note: before run the project , please copy the directroy of node_modules into the project
[AppletsFramework.zip](https://github.com/facebook/react-native/files/2390868/AppletsFramework.zip)

**Comment by baiwhte** [comment]
I update to the latest release, v0.57 but the issue still exits. cannot archive success.

![error](https://user-images.githubusercontent.com/20255561/45669615-2a3b2900-bb53-11e8-9e50-38c34ce47fcd.png)

React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 48.41 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.6.0 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.1.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
    IDEs:
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0
      react-native: 0.57.0 => 0.57.0
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by radex** [comment]
Edit Scheme → Build, and add React target ABOVE your app target
