### ISSUE TITLE
RCTDownloadTaskMapper is broken in 0.8.0

### ISSUE THREAD

**Issue by glennmartinez** [facebook/react-native#2117]
Hey guys, getting this error

'Null passed to a callee that requires a non-null argument'

 NSURLSessionDownloadTask *task = [_URLSession downloadTaskWithURL:url completionHandler:nil];

**Comment by difelice** [comment]
Are you using Xcode 7? It might be that, remove *completionHandler:nil* and retry.

**Comment by glennmartinez** [comment]
Yes, I am, ok will give that a try.
Btw, great work on this library, it's awesome!!

**Comment by joshparolin** [comment]
@difelice's answer worked for me as well. Cheers.

**Comment by ide** [comment]
Fixed in master.

**Comment by seanmthompson** [comment]
@difelice's answer worked for me too. +1
