### ISSUE TITLE
[Navigator]navigator transition,meantime setState,not smooth

### ISSUE THREAD

**Issue by everfire130** [facebook/react-native#2118]
if navigator transition (like push transition),meantime ,no matter what component setState,the transition will be not smooth.For example,A view get network data in componentDidMount,if the push transition was not finished ,the newwork data has gotten and the view setState,the transition will be bad

**Comment by everfire130** [comment]
Now my solution is that the component adds a navigator onDidFocus life cycle.The setState handle is executed in the onDidFocus.But I think my solution is not very good.Any solutions?

**Comment by ssssssssssss** [comment]
Wrap your setState() code
```
InteractionManager.runAfterInteractions(() => {  
    // ...your setstate here...
});
```

**Comment by everfire130** [comment]
@ssssssssssss Thank you.That's useful
