### ISSUE TITLE
Border radius not respected in SectionList

### ISSUE THREAD

**Issue by vjsingh** [facebook/react-native#21181]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Environment:
  OS: macOS High Sierra 10.13
  Node: 10.4.0
  Yarn: 1.7.0
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz => 0.55.2

## Description
When putting a SectionList inside of a view with rounded corners, the SectionList does not respect the rounded corners. This can be solved by putting a padding on the SectionList, but I would like a solution that avoids doing this.

![border radius bug](https://user-images.githubusercontent.com/318312/45716097-e997db80-bb63-11e8-8bec-b46137f8e26b.png)

## Reproducible Demo
https://snack.expo.io/@vjsingh/scrolltolocation
Pull the list downward to see that the scrollview is 'covering' the rounded corners. I would think that the container view should effectively 'mask' the inner scrollview here?

**Comment by vjsingh** [comment]
This issue is still relevant I believe.

**Comment by DaiYz** [comment]
same issue

**Comment by vjsingh** [comment]
Issue is still relevant

**Comment by vjsingh** [comment]
Still relevant
