### ISSUE TITLE
Can't uninstall RN app from android device

### ISSUE THREAD

**Issue by Colman** [facebook/react-native#21185]
- [X] Review the documentation: https://facebook.github.io/react-native
  - [X] Search for existing issues: https://github.com/facebook/react-native/issues
  - [X] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Environment:
  OS: Windows 7
  Node: 8.11.4
  Yarn: 1.9.4
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: ^16.5.0 => 16.5.1 
  react-native: ^0.57 => 0.57.0

## Description
I'm having issues uninstalling my react native app from my android phone. I have tried unplugging the device and restarting it, but I still can't uninstall it. Whenever I click remove, or go into the settings in android and click uninstall, it shows a message that the package manager has stopped and nothing else happens. I'm NOT using expo and my RN version is 0.55.4. The reason why this is different than what I wrote in the environment section is because the bot wouldn't let me ask the question if I didn't update it and I couldn't update my RN because another library had compatibility issues with the new version.

## Reproducible Demo
Install a RN app and try to uninstall it from an Android device.

**Comment by radko93** [comment]
Without a code to reproduce this, we can't help you out with this. Please add more details.
