### ISSUE TITLE
react-native 0.57.0 crash error on IOS 8

### ISSUE THREAD

**Issue by tiennguyen9988** [facebook/react-native#21193]
- [ ] Review the documentation: https://facebook.github.io/react-native
  - [ ] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
react-native 0.57.0

## Description
react-native 0.57.0 crash error on IOS 8 when run and export debug on xcode the same image atacked

## Reproducible Demo

![screen shot 2018-09-19 at 3 19 06 pm](https://user-images.githubusercontent.com/3782474/45743658-bd915e80-bc26-11e8-9f49-6f6342c38a1b.png)
![screen shot 2018-09-19 at 3 19 17 pm](https://user-images.githubusercontent.com/3782474/45743660-bd915e80-bc26-11e8-9490-10a95864f6b4.png)

**Comment by lostaloneesk** [comment]
Requirements
Supported target operating systems are >= Android 4.1 (API 16) and >= iOS 9.0. You may use Windows, macOS, or Linux as your development operating system, though building and running iOS apps is limited to macOS by default (tools like Expo can be used to get around this).

**Comment by lostaloneesk** [comment]
react-native 0.57.0 does not support iOS 8
