### ISSUE TITLE
How can one get support fragment manager from ThemedReactContext ?

### ISSUE THREAD

**Issue by akdsouza** [facebook/react-native#21194]
I'm writing a custom native android library that exposes a support fragment for display. I created a simple view manager on the android side of react in which I return a placeholder layout in `createViewInstance` and later intend to add the library fragment inside `receiveCommand` on user action from the react side. However in order to add the fragment to the aforementioned container I cannot get the support fragment manager from the ThemedReactContext obj that I capture in `createViewInstance`. Doing `fooThemedReactContext.getCurrentActivity()` yields the deprecated `android.app.FragmentManager`. How do I get `android.support.v4.app.FragmentManager` instead in my view manager?

**Comment by augustl** [comment]
For people on Google that end up here, you can make sure your activities extends `ReactFragmentActivity` rather than `ReactActivity`. That class has `getSupportFragmentManager()` and all that jazz.

**Comment by cgomezmendez** [comment]
@augustl ReactFragmentActivity is marked as deprecated and will be removed soon, you shouldn't be using it.

**Comment by augustl** [comment]
As far as I can tell, there's no other way of doing it in 0.56 that I can see, so I thought I'd just mention it here in case anyone else found this issue on Google :)

**Comment by kesha-antonov** [comment]
Any hints for RN 0.60+?
