### ISSUE TITLE
React native error on metro bundler & simulator CFNetwork/901.1 Darwin/17.7.0 & attempted to invoke (method ID)

### ISSUE THREAD

**Issue by buchidiai** [facebook/react-native#21202]
I have these 2 warnings and i dont know if they are related

I must say that i am still able to use the simulator with all its functionalities (meaning these warnings dont stop me from doing stuff)

Anyone have an idea? Thanks in advance.

![screen shot 2018-09-19 at 8 09 07 am](https://user-images.githubusercontent.com/31743169/45763201-a38b5800-bbf5-11e8-96c3-b59d03d474af.png)
![screen shot 2018-09-19 at 8 10 44 am](https://user-images.githubusercontent.com/31743169/45763202-a38b5800-bbf5-11e8-8260-ba53aeefd012.png)
![screen shot 2018-09-19 at 8 10 55 am](https://user-images.githubusercontent.com/31743169/45763203-a38b5800-bbf5-11e8-9451-b1a98a22a8e7.png)
![screen shot 2018-09-19 at 8 11 17 am](https://user-images.githubusercontent.com/31743169/45763204-a38b5800-bbf5-11e8-8eef-7a7eecd3526e.png)

    react-native-cli: 2.0.1 
    react-native: 0.57.0 
    $react-native -version  
     React Native Environment Info:
            System:
              OS: macOS High Sierra 10.13.6
              CPU: x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
              Memory: 47.93 MB / 10.00 GB
              Shell: 3.2.57 - /bin/bash
            Binaries:
              Node: 8.11.4 - /usr/local/bin/node
              Yarn: 1.9.4 - /usr/local/bin/yarn
              npm: 6.4.1 - /usr/local/bin/npm
              Watchman: 4.9.0 - /usr/local/bin/watchman
            SDKs:
              iOS SDK:
                Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
            IDEs:
              Android Studio: 3.1 AI-173.4907809
              Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
            npmPackages:
              react: 16.5.0 => 16.5.0 
              react-native: 0.57.0 => 0.57.0 
            npmGlobalPackages:
              react-native-cli: 2.0.1

  [1]: https://i.stack.imgur.com/T5Pqh.png
  [2]: https://i.stack.imgur.com/7EE7J.png
  [3]: https://i.stack.imgur.com/ESD4y.png
  [4]: https://i.stack.imgur.com/c4IQQ.png

**Comment by BooYeu** [comment]
Do you solve the problem , I have the same problem when I update react-native from 0.56 to 0.57.1

**Comment by BaderSerhan** [comment]
me too

**Comment by ravindraguptainfogain** [comment]
please reopen, how we can stop the logging of these request messages.

**Comment by robleds** [comment]
same here... 0.58 trying to reinstall dependences to fix it.
