### ISSUE TITLE
'React/RCTPushNotificationManager.h' file not found

### ISSUE THREAD

**Issue by Jordan4jc** [facebook/react-native#21225]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Run `react-native info` in your terminal and paste its contents here.

Environment:
  OS: macOS High Sierra 10.13.6
  Node: 8.0.0
  Yarn: 1.5.1
  npm: 6.4.1
  Watchman: 4.9.0
  Xcode: Xcode 10.0 Build version 10A255
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

## Description
Can't get PushNotifications to build at all, I've tried numerous different ways and fixes found online and nothing works

At this point I have followed to a T the manual linking procedure on this page

https://facebook.github.io/react-native/docs/linking-libraries-ios#manual-linking

Even, step 3, which I feel like may be where my issue lies which has a value of this currently (though I have tried many many different paths)

`${SRCROOT}/../node_modules/react-native/Libraries/PushNotificationIOS`
`non-recursive`

I would really love to figure this one out. BTW I am using ExpoKit if that makes a difference though I am seeing online that it shouldn't?

**Comment by tahirmq1** [comment]
> * [x]  Review the documentation: https://facebook.github.io/react-native
> * [x]  Search for existing issues: https://github.com/facebook/react-native/issues
> * [x]  Use the latest React Native release: https://github.com/facebook/react-native/releases
> 
> ## Environment
> Run `react-native info` in your terminal and paste its contents here.
> 
> Environment:
> OS: macOS High Sierra 10.13.6
> Node: 8.0.0
> Yarn: 1.5.1
> npm: 6.4.1
> Watchman: 4.9.0
> Xcode: Xcode 10.0 Build version 10A255
> Android Studio: Not Found
> 
> Packages: (wanted => installed)
> react: 16.3.1 => 16.3.1
> react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4
> 
> ## Description
> Can't get PushNotifications to build at all, I've tried numerous different ways and fixes found online and nothing works
> 
> At this point I have followed to a T the manual linking procedure on this page
> 
> https://facebook.github.io/react-native/docs/linking-libraries-ios#manual-linking
> 
> Even, step 3, which I feel like may be where my issue lies which has a value of this currently (though I have tried many many different paths)
> 
> `${SRCROOT}/../node_modules/react-native/Libraries/PushNotificationIOS`
> `non-recursive`
> 
> I would really love to figure this one out. BTW I am using ExpoKit if that makes a difference though I am seeing online that it shouldn't?

did you find any fix for this???

**Comment by annie-elequin** [comment]
I am also having this problem. Was a solution found?
