### ISSUE TITLE
Help, im getting error when running the app suddenly

### ISSUE THREAD

**Issue by warrence** [facebook/react-native#21228]
Hi all, 

It was working fine until I do npm update, im getting the error below:

react native undefined is not a function (evaluating 'windows.addEventListener('message', idleTick, false)')

Im searching around for few hours but didn't get any answer, anyone please help?

**Comment by teminnov** [comment]
I'm also getting the same problem

**Comment by santoshdahal12** [comment]
I got into the same issue. Spent an hour and tried to detect versions changes in  the package-lock.json. At the end figured its issue with react-dom which depends on some package called schedule. So the fix might be to lower the version of react-dom and re install it. I lowered react-dom to 16.5.0 which would use "schedule": "0.3.0".
