### ISSUE TITLE
iOS release crash with use "View.propTypes.style" for component style propTypes.

### ISSUE THREAD

**Issue by XinQiXiao** [facebook/react-native#21223]
## Environment
  OS: macOS High Sierra 10.13.6
  Node: 7.6.0
  Yarn: 1.7.0
  npm: 4.1.2
  Watchman: 3.3.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.1.1 => 16.5.2
  react-native: ^0.50.4 => 0.50.4

## Description

In a custom component, propsType is used for specifying the props type of the component. No error was reported in the debug environment, but after release was packaged, it broke.

## Code below
  ...
  someComponent.propTypes = {
    containerStyle: View.propTypes.style,
    ...
  }
  someComponent.defaultProps = {
     containerStyle: null,
     ...
  }
  ...

**Comment by rsnara** [comment]
How did you package the release? 

Just a hunch: Proptypes have a performance overhead. That may be the reason why you're seeing that `View.propTypes` is `null` with the release build of your app.
