### ISSUE TITLE
error: bundling failed: TypeError: Cannot read property 'filename' of undefined

### ISSUE THREAD

**Issue by hqwlkj** [facebook/react-native#21236]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
`React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
      Memory: 28.48 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.10.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
      Android SDK:
        Build Tools: 19.1.0, 20.0.0, 21.1.2, 22.0.1, 23.0.0, 23.0.1, 23.0.2, 23.0.3, 25.0.2, 25.0.3, 26.0.2, 26.0.3, 27.0.1, 27.0.3
        API Levels: 10, 15, 16, 17, 18, 19, 20, 21, 22, 23, 25, 26, 27, 8, 9
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.4.14 => 16.4.14 
      @types/react-native: ^0.56.23 => 0.56.23 
      react: 16.5.0 => 16.5.0 
      react-native: 0.57.0 => 0.57.0 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1

`

## Description
react-native run-ios : error: bundling failed: TypeError: Cannot read property 'filename' of undefined
![image](https://user-images.githubusercontent.com/12181423/45855874-bed89d80-bd84-11e8-8790-fd52c29a2b72.png)

![image](https://user-images.githubusercontent.com/12181423/45855884-c5671500-bd84-11e8-8245-c582dca0a0e6.png)

## Reproducible Demo
Let us know how to reproduce the issue. Include a code sample, share a project, or     share an app that reproduces the issue using https://snack.expo.io/. Please follow the guidelines for providing a MCVE: https://stackoverflow.com/help/mcve

**Comment by hqwlkj** [comment]
I am already using the latest version.
`npmPackages:
@types/react: ^16.4.14 => 16.4.14
@types/react-native: ^0.56.23 => 0.56.23
react: 16.5.0 => 16.5.0
react-native: 0.57.0 => 0.57.0
npmGlobalPackages:
create-react-native-app: 1.0.0
react-native-cli: 2.0.1
`

**Comment by Dsignmind** [comment]
I'm also experiencing this.
`react-native: 0.57.2`

**Comment by rava11** [comment]
+1
react-native: 0.57.3

**Comment by korede360** [comment]
+1. Any temporary workarounds yet?

**Comment by burivuhster** [comment]
I had this issue after updating Expo from v30 to v31.
Removing the strings
`  "env": {
    "development": {
      "plugins": ["transform-react-jsx-source"]
    }
  }` from my .babelrc helped.

**Comment by grabbou** [comment]
Hello there 👋 this issue doesn't have a repro (which means, a react-native init-ed project with the minimal changes that leads to creating the same issue you are reporting). Unfortunately, I have no way of helping you in a meaningful way – there is no easy way for me to recreate the situation and check that the issue reported is still there when changing the code.

Because of this, we are going to close this issue - but if a repro is shared, we are happy to reopen it 🤗
