### ISSUE TITLE
[Navigator] Cannot removeListener from NavigationContext

### ISSUE THREAD

**Issue by potsypantsy** [facebook/react-native#2123]
What is the best way to remove listener from NavigationContext? It seems like there is only public api to add a listener. Thanks!

**Comment by ide** [comment]
addListener returns a subscription object that lets you remove the listener. I don't remember the specific API off the top of my head (it might just be sub.remove()) but if you read through the code it's something simple like that.

**Comment by potsypantsy** [comment]
@ide thanks!

**Comment by myusuf3** [comment]
@potsypantsy what did you find?

**Comment by keeth** [comment]
this works for me:
```
  componentDidMount() {
    this.didFocusSubscription = this.props.navigator.navigationContext.addListener('didfocus', this.onDidFocus);
  }

  componentWillUnmount() {
    this.didFocusSubscription.remove();
  }
```
