### ISSUE TITLE
TouchableOpacity - onPress takes incorrect values

### ISSUE THREAD

**Issue by seco35** [facebook/react-native#21245]
## Environment
Using windows (so react-native info doesn't works) but these are my versions:
[skip envinfo]
react-native: 0.55.4
react: 16.3.1

## Description
Creating an array of TouchableOpacities with unknown amount of elements by using a for each gives each element the last index of Array when using in onPress={} 

## Reproducible Demo
```
this.vacationData = { BOR:[...], HIL:[....], LAB:[...] }
internalCounter = 0;
        for(i in this.vacationData){

            myViews.push(

                        <TouchableOpacity key={i} activeOpacity={0.8} style={{flex:1, flexDirection:'row', height:60, marginTop:5}} onPress={()=> { console.log(i) }}>
                            {myInnerViews[internalCounter]}
                            <Text style={{position:'absolute', marginTop:20, marginLeft:5}} > {i} </Text>
                        </TouchableOpacity>

            );
            internalCounter++;
        }
```

At the end I do get 3 TouchableOpacities with and the text is shown correclty, BOR, HIL & LAB.
For some reason, the console.log(i) in my onPress event displays 'LAB', no matter which TouchableOpacity I'm pressing, they all get kinda a reference of i and take the last updated one as they would do it with parameters in the state.

EDIT: Found a workaround for this->
```


this.vacationData = { BOR:[...], HIL:[....], LAB:[...] }
// Creating array with json data.
var arr = Object.keys(this.vacationData).map((s,i) => {
            return(this.vacationData[s]);
        });

// using .map() instead of for each.
let myMappedViews = arr.map((s,i) => {
            return(<TouchableOpacity key={i} style={{flexDirection:'row', height:60, marginTop:5}}
                        onPress={()=> console.log() )  }
                        >
                        {myInnerViews[i]}
                        <Text style={{position:'absolute', marginTop:20, marginLeft:5}}> {Object.keys(this.vacationData)[i]} </Text>
                    </TouchableOpacity>)
        });
```

I don't understand it. Isn't the index referrenced on same way with both for each and mapping through the data? 😮

**Comment by seco35** [comment]
You're drunk bot, I'd entered [skip envinfo] already in the Environment like you'd suggested 👎

**Comment by minhvuongrbs** [comment]
Bot want to force us to close the whole issues :'(
