### ISSUE TITLE
Warning clarification - ScrollView doesn't take rejection well

### ISSUE THREAD

**Issue by piyushchauhan2011** [facebook/react-native#2125]
Couldn't understand this warning!

![screen shot 2015-07-26 at 10 12 44 am](https://cloud.githubusercontent.com/assets/693487/8891904/021c9e22-337f-11e5-9008-e295f940c6b8.png)

**Comment by grabbou** [comment]
Imo dup of #41, CC: @brentvatne

**Comment by ericvicenti** [comment]
Yes I think this is the same as #41. I don't want to add more documentation in this regard, but we could clarify the warning.

> Warning: A View is trying to become touch responder, but ScrollView will still respond to the touch (See https://github.com/facebook/react-native/issues/41)

Is this better?
