### ISSUE TITLE
unfortunately app has stopped

### ISSUE THREAD

**Issue by kadirguloglu** [facebook/react-native#21258]
Thanks for help.

Environment
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
      Memory: 991.41 MB / 7.90 GB
    Binaries:
      Yarn: 1.1.0 - C:\Users\Kadir\AppData\Roaming\npm\yarn.CMD
      npm: 6.0.1 - C:\Users\Kadir\AppData\Roaming\npm\npm.CMD
    IDEs:
      Android Studio: Version  3.1.0.0 AI-173.4819257

my package.json file
{
  "name": "ustalazimapp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "@expo/vector-icons": "^6.3.1",
    "axios": "^0.18.0",
    "moment": "^2.22.2",
    "native-base": "^2.8.0",
    "prop-types": "^15.6.2",
    "react": "16.5.0",
    "react-native": "0.57.0",
    "react-native-animatable": "^1.3.0",
    "react-native-device-info": "^0.22.5",
    "react-native-image-picker": "^0.26.10",
    "react-native-maps": "^0.21.0",
    "react-native-vector-icons": "^5.0.0",
    "react-navigation": "^2.16.0",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0",
    "redux-axios-middleware": "^4.0.0"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.45.5",
    "react-test-renderer": "16.5.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
<img src="https://image.ibb.co/iog8SK/Capture.png" alt="Capture" border="0">

<img src="https://image.ibb.co/depj1e/Capture1.png" alt="Capture1" border="0">

**Comment by charleycesar** [comment]
Open android studio and look for crash in logcat.
Like this ===== Begin of Crash ======

**Comment by erandagan** [comment]
This belongs to StackOverFlow, not here.
