### ISSUE TITLE
TVEventHandler is not working with react-native-view in Android

### ISSUE THREAD

**Issue by TheHemantKaushik** [facebook/react-native#21259]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment

  React Native Environment Info:
    System:
      OS: Linux 4.15 elementary OS 0.4.1 Loki
      CPU: x64 Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
      Memory: 566.45 MB / 7.70 GB
      Shell: 4.3.48 - /bin/bash
    Binaries:
      Node: 8.11.1 - ~/Work/Installations/node/bin/node
      Yarn: 1.9.4 - ~/Work/Installations/node/bin/yarn
      npm: 6.1.0 - ~/Work/Installations/node/bin/npm
    SDKs:
      Android SDK:
        Build Tools: 26.0.0, 27.0.3, 28.0.0
        API Levels: 19, 23, 26, 27, 28
    npmPackages:
      @types/react: 16.4.14 => 16.4.14
      @types/react-native: 0.56.23 => 0.56.23
      react: 16.5.0 => 16.5.0
      react-native: v0.57.0 => 0.57.0
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description
I am developing an app for TV's. There is an intro video screen in this app. On this screen, I am using remote "select" button to play pause video. (There is no play/pause button in some remotes eg. MI Box). I am using "TVEventHandler" class to listen remote keys and printing values in console. But there is no value in console when I press any key from remote. It is not working as expected on Android.

## Reproducible Demo
I am logging events in console. You can attach debugger to check console logs.
Here is a dropbox link of demo app:
https://www.dropbox.com/s/1ch84lyo2lh5vjx/RN57.zip?dl=0

**Comment by TheHemantKaushik** [comment]
@react-native-bot I am using latest version 0.57. You can check it from environment info.

**Comment by sJJdGG** [comment]
@TheHemantKaushik You can only receive those kind of events if and only if a touchable is at focus in your root component.
You have no touchable component in your app.
if you don't need to have any, just add one with opacity 0 and make sure it has hasTVPreferredFocus prop set as true so it's already at focus at mount.
If you think this behavior is odd and/or a regression fell free to close this one make a new issue about the react native behavior to know maintainers thoughts on this.
