### ISSUE TITLE
Reload bridge with different bundleURL

### ISSUE THREAD

**Issue by PhilippKrone** [facebook/react-native#2126]
Is it possible to reload the bridge with a different bundleURL?

I'm currently trying the following, which does not seem to work:

````javascript
    self.bridge.bundleURL = [NSURL URLWithString:bundlePath];
    [self.bridge reload];
`````

It is reloading the bridge but setting the new bundleURL seems to have no effect.

**Comment by ericvicenti** [comment]
My guess is you need to instantiate a new bridge. @tadeuzagallo would know for sure.

**Comment by nicklockwood** [comment]
It's not currently possible. Can you explain your use case?

**Comment by PhilippKrone** [comment]
@nicklockwood sure. I'm using some live loading of javascript code, save it in the NSUserDefaults and load a bridge from there. There are certain situations in which I'm reloading code from my server and save it in my NSUserDefaults as well - but under a different bundle name (e.g. main01.jsbundle vs main02.jsbundle). I then want to reload the bridge using the new bundle file.

**Comment by nicklockwood** [comment]
The simplest solution in your case would probably be to save the files at different locations, but then move/copy the file you want to load to a standard location before reloading the bridge.

We will eventually add support for downloading and loading multiple js files, but that's a long way off for now.

**Comment by PhilippKrone** [comment]
Yeah, thats what I'm currently doing. I'm gonna close this issue then - thanks for your help!

**Comment by nicklockwood** [comment]
Update: @tadeuzagallo just pointed out to me that the `bundleURL` property is actually now readwrite, so it *is* in fact possible to change it again after creating the bridge.

You can disregard everything else I said :D

**Comment by PhilippKrone** [comment]
@nicklockwood Mhh, I was trying the following initially:

````javascript
 self.bridge.bundleURL = [NSURL URLWithString:bundlePath];
    [self.bridge reload];
`````
but this has still loaded the old URL - is it enough to just set it like that or do you need to re-initialize() something?

**Comment by nicklockwood** [comment]
I'm unable to explain why that wouldn't work - as far as I can see it should do.

If you're reasonably familiar with Xcode, maybe you can trace the reload process with breakpoints and see if you can figure out why the URL isn't propagating?

Otherwise, @tadeuzagallo might be able to help.

**Comment by PhilippKrone** [comment]
Sure, I’ll debug through it and give feedback - no need for you/tadeuzagallo to do that. Will come back to you once I found time to do it

**Comment by PhilippKrone** [comment]
@tadeuzagallo @nicklockwood  I was just debugging through it and although the URL is successfully set, whenever I call reload and print "_bundleURL", its still the old url. Is it possible that I actually set it on another instance (?) of the bridge?

I have 
````javascript
@synthesize bridge = _bridge;

...
    self.bridge.bundleURL = [NSURL URLWithString:bundlePath];
    [self.bridge reload];
````

**Comment by tadeuzagallo** [comment]
@PhilippKrone Is it inside a module? The "inner" instance of the bridge is not propagating the value, I'll fix it, and ping you.

**Comment by PhilippKrone** [comment]
@tadeuzagallo Yeah, it's inside a module. thanks a lot!
