### ISSUE TITLE
Toggle Inspector -> Network not working on Android (device +emulator).

### ISSUE THREAD

**Issue by MrIceman** [facebook/react-native#21264]
## Environment
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 114.14 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.9.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        Build Tools: 25.0.2, 26.0.3, 27.0.3, 28.0.1, 28.0.2
        API Levels: 16, 23, 25, 26, 27, 28
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.4.14 => 16.4.14 
      @types/react-native: ^0.56.23 => 0.56.23 
      react: 16.5.0 => 16.5.0 
      react-native: 0.57.0-rc.4 => 0.57.0-rc.4 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description
I can not open the Network section on the toggle inspector. Neither can I send any requests from my App. As soon as I press cmd + m, the RN Dev Menu pops up. I press on toggle inspection, click on the network tab and then red-screen with error-message you can see at the bottom. I tried to start a new project, same happened again. 

my package.json
}, "dependencies": { "@babel/runtime": "7.0.0", "es6-promise": "^4.2.5", "isomorphic-fetch": "^2.2.1", "react": "16.5.0", "react-native": "0.57.1", "ts-mockito": "^2.3.1" }, "devDependencies": { "@babel/plugin-proposal-class-properties": "^7.1.0", "@types/jest": "^23.3.2", "@types/react": "^16.4.14", "@types/react-native": "^0.56.23", "@types/react-test-renderer": "^16.0.2", "babel-jest": "^23.6.0", "jest": "^23.6.0", "metro-react-native-babel-preset": "^0.45.6", "react-native-typescript-transformer": "^1.2.10", "react-test-renderer": "16.4.1", "ts-jest": "^23.10.1", "typescript": "^3.0.3" },

stop to reproduce:
compile project on app or emulator, open the RN-Developer menu, select Toggle Inspector and click on the Network tab. You'll get a red screen saying this:
TypeError: undefined is not an object (evaluating '_this._captureRequestListView.bind')

This error is located at:
in NetworkOverlay (at InspectorPanel.js:52)
in RCTView (at View.js:44)
in InspectorPanel (at Inspector.js:258)
in RCTView (at View.js:44)
in RCTView (at View.js:44)
in Inspector (at AppContainer.js:62)
in RCTView (at View.js:44)
in AppContainer (at renderApplication.js:33)
NetworkOverlay
index.delta?platform=android&dev=true&minify=false:57751:68

index.delta?platform=android&dev=true&minify=false:36493:115
instantiate
index.delta?platform=android&dev=true&minify=false:36501:11
constructClassInstance
index.delta?platform=android&dev=true&minify=false:12963:32
updateClassComponent
index.delta?platform=android&dev=true&minify=false:14509:35
beginWork
index.delta?platform=android&dev=true&minify=false:14971:40
performUnitOfWork
index.delta?platform=android&dev=true&minify=false:16968:27
workLoop
index.delta?platform=android&dev=true&minify=false:17001:47
renderRoot
index.delta?platform=android&dev=true&minify=false:17033:21
performWorkOnRoot
index.delta?platform=android&dev=true&minify=false:17688:23
performWork
index.delta?platform=android&dev=true&minify=false:17611:30
performSyncWork
index.delta?platform=android&dev=true&minify=false:17582:20
batchedUpdates$1
index.delta?platform=android&dev=true&minify=false:17792:28
batchedUpdates
index.delta?platform=android&dev=true&minify=false:9193:33
_receiveRootNodeIDEvent
index.delta?platform=android&dev=true&minify=false:9252:23
receiveTouches
index.delta?platform=android&dev=true&minify=false:9282:34
__callFunction
index.delta?platform=android&dev=true&minify=false:2799:49

index.delta?platform=android&dev=true&minify=false:2572:31
__guard
index.delta?platform=android&dev=true&minify=false:2753:15
callFunctionReturnFlushedQueue
index.delta?platform=android&dev=true&minify=false:2571:21

**Comment by MrIceman** [comment]
still happens after downgrading back to 0.57.0

**Comment by ziyafenn** [comment]
Same problem here. On Android device toggle inspector doesn't work. On simulator i made it work by enabling remote JS debugging. But on the device that didn't help.
