### ISSUE TITLE
Can't disable vertical scrolling with ScrollView?

### ISSUE THREAD

**Issue by coderdave** [facebook/react-native#2127]
Is there a way to disable vertical scrolling with ScrollView? I only want it to scroll horizontally.

**Comment by jiraiyame** [comment]
`directionalLockEnabled` does't work?

**Comment by coderdave** [comment]
No, that only locks it after you start to drag in a particular direction.

**Comment by startsev** [comment]
try to add `automaticallyAdjustContentInsets={false}`

**Comment by coderdave** [comment]
Setting `automaticallyAdjustContentInsets={false}` worked, thanks.
