### ISSUE TITLE
open json flatlist clicked URL on browser

### ISSUE THREAD

**Issue by atiajabbar** [facebook/react-native#21277]
I'm fetching JSON data using api  key which contains Name, Rating and URL. I have flatlist on react-native which will display Fetched Name, Rating and all.I successfully get json data and already show it in a flatlist. Now my requirement is that when I click on flatlist it should open the URL fetched from JSON on browser.

![react native](https://user-images.githubusercontent.com/24921911/45931825-2844e180-bf28-11e8-9d40-02bef04606ec.png)

**Comment by emtiajium** [comment]
```
import {Linking} from 'react-native';
Linking.openURL(url)
      .catch( (err) => {
        // handle error
      });
```

**Comment by atiajabbar** [comment]
Thanks alot.
