### ISSUE TITLE
'config.h'  file not found when I upgraded xcode10.

### ISSUE THREAD

**Issue by kakahero** [facebook/react-native#21274]
![image](https://user-images.githubusercontent.com/4515415/45929816-8d7cef00-bf89-11e8-891d-923d977085e3.png)

## Environment:
  OS: macOS High Sierra 10.13.6
  Node: 10.8.0
  Yarn: 1.6.0
  npm: 6.4.1
  Watchman: 4.9.0
  Xcode: Xcode 10.0 Build version 10A255
  Android Studio: 3.1 AI-173.4819257

## Packages: (wanted => installed)
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: 0.54.2 => 0.54.2

**Comment by GodWar101** [comment]
Same issue running with React Native 0.55.4.

**Comment by chrisbull** [comment]
Changing the build system alone didn't work for me - Make sure to upgrade your react-native package with [`react-native-git-upgrade`](https://facebook.github.io/react-native/docs/upgrading)
