### ISSUE TITLE
React native app installed on phone, but not visible on home or app screen

### ISSUE THREAD

**Issue by mads0109** [facebook/react-native#21273]
## Environment
Environment:
  OS: Linux 4.15
  Node: 8.10.0
  Yarn: Not Found
  npm: 3.5.2
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: ^16.0.0 => 16.5.0
  react-native: ^0.51.0 => 0.51.1

## Description
I'm working on a react-native project, and I've run into an error. I can install the app on my phone using react-native run-android, it installs the app on my phone and launches it. The problem is that the app is not visible on the home screen or app menu, so if I close the app, I have to re-download the app again from CLI. According to settings the app is installed and is taking up memory, but it's not present on the home screen or the app menu.

I have tried to create APK's as well and download them on my phone, but I have the same problem. The app is downloaded and installed, but the open button is grayed out, and there's still no sign on the app on neither the home screen or the app menu.

![img_20180921_0001](https://user-images.githubusercontent.com/17144381/45926529-a9e64080-bf23-11e8-95f7-0f8ff532e021.jpeg)
![screenshot_20180921-100203](https://user-images.githubusercontent.com/17144381/45926530-a9e64080-bf23-11e8-91a6-dabcfc3344c7.png)

**Comment by mads0109** [comment]
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.test">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
        <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>
        <meta-data
            android:name="com.google.android.geo.API_KEY"
            android:value="sdfhwueyr34875893ytyt3y4yuw"/>
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
          android:screenOrientation="portrait"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustPan">
        <intent-filter>
            <data android:scheme="@string/fb_login_protocol_scheme" />
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>
```

**Comment by hramos** [comment]
I can't see how this is related to React Native, at least the way the problem is worded.
