### ISSUE TITLE
8 errors while debugging new react native app Execution failed for task ':app:compileDebugJavaWithJavac'. - React Native

### ISSUE THREAD

**Issue by jebasfrank** [facebook/react-native#21284]
8 errors :app:compileDebugJavaWithJavac FAILED

What went wrong: Execution failed for task ':app:compileDebugJavaWithJavac'.
Compilation failed; see the compiler error output for details.

But old apps are running on my machine, win 8.1 (64) Bit

:app:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.). F:\React2\appwn\android\app\src\main\java\com\appwn\MainApplication.java:5: error: cannot find symbol import com.facebook.react.ReactApplication; ^ symbol: class ReactApplication location: package com.facebook.react F:\React2\appwn\android\app\src\main\java\com\appwn\MainApplication.java:6: error: cannot find symbol import com.facebook.react.ReactNativeHost; ^ symbol: class ReactNativeHost location: package com.facebook.react F:\React2\appwn\android\app\src\main\java\com\appwn\MainApplication.java:14: error: cannot find symbol public class MainApplication extends Application implements ReactApplication { ^ symbol: class ReactApplication F:\React2\appwn\android\app\src\main\java\com\appwn\MainApplication.java:16: error: cannot find symbol private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) { ^ symbol: class ReactNativeHost location: class MainApplication F:\React2\appwn\android\app\src\main\java\com\appwn\MainApplication.java:36: error: cannot find symbol public ReactNativeHost getReactNativeHost() { ^ symbol: class ReactNativeHost location: class MainApplication F:\React2\appwn\android\app\src\main\java\com\appwn\MainActivity.java:5: error: MainActivity is not abstract and does not override abstract method getPackages() in ReactActivity public class MainActivity extends ReactActivity { ^ F:\React2\appwn\android\app\src\main\java\com\appwn\MainApplication.java:16: error: cannot find symbol private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) { ^ symbol: class ReactNativeHost location: class MainApplication F:\React2\appwn\android\app\src\main\java\com\appwn\MainApplication.java:35: error: method does not override or implement a method from a supertype @Override ^ 8 errors :app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

What went wrong: Execution failed for task ':app:compileDebugJavaWithJavac'.

Compilation failed; see the compiler error output for details.

Try: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by jasvinder797** [comment]
Execution failed for task ':app:compileDebugJavaWithJavac'
