### ISSUE TITLE
[TextInput] Retain Focus on TextInput

### ISSUE THREAD

**Issue by ksmth** [facebook/react-native#2129]
I'd like to make a `TextInput` keep focus, right after `onSubmitEditing`, but all I've come up with is also explained in this SO question:

http://stackoverflow.com/questions/29420251/how-do-i-get-a-react-native-textinput-to-maintain-focus-after-submit

TL;DR
call `.focus()` on the `ref`, which just doesn't work properly. The software keyboard is jumping up and down, which is definitely not desired behaviour. How do I implement this with react native?

**Comment by brentvatne** [comment]
I have noticed this issue as well and don't yet have a good solution, cc @ide

**Comment by dsibiski** [comment]
Hey guys, I'm working on this now. My concept is working, just need to expose a property to JS and submit a PR.

@ksmth & I had agreed that a good possible name for this option could be `blurOnSubmit`, it would be a boolean and default to true.

**Comment by dsibiski** [comment]
@ksmth There you go, I imagine this should work for you're needs. :)

**Comment by dsibiski** [comment]
@ksmth @brentvatne This can be closed now as this has been merged to master. :smiley:
