### ISSUE TITLE
":CFBundleIdentifier", Does Not Exist - Mitigating confusion around it

### ISSUE THREAD

**Issue by hramos** [facebook/react-native#21303]
[_Print: Entry, ":CFBundleIdentifier", Does Not Exist_](https://github.com/facebook/react-native/issues?utf8=%E2%9C%93&q=is%3Aissue+CFBundleIdentifier) pops up constantly in GitHub issues. This is the last line of output for a number of unrelated issues. 

### This message will appear in the logs whenever a React Native project fails to compile or link.

The _Print: Entry, ":CFBundleIdentifier", Does Not Exist_ error, by itself, is too generic to give direction, and does not indicate whether the error is in React Native, third party libraries, or application code.

With this in mind, we are automatically marking issues that mention the `:CFBundleIdentifier` error as duplicates of this issue. This issue will remain locked in order to avoid confusing matters any further, while still allowing core contributors to discuss ways to mitigate the problem.

# Troubleshooting

If you're landing on this issue because you've observed the _:CFBundleIdentifier_ message in your output, please read the following carefully:

* This error typically indicates a failure to compile or link the app.
* If you're having problems, look at the full build output, not just the last few lines.
* Open the project in Xcode and hit ⌘B to build it. The build errors in Xcode might help find the actual cause of the failure.

## Troubleshooting by Example

For an actual example of how such an issue can be investigated, take a look at 
 https://gist.github.com/mhorowitz/ea67d8e1793e803b2ca273395ac12ed2. The important lines are 9-10:

```
../../../ios/Pods/leveldb-library/port/win/stdint.h:11:2: error: This file should only be included when compiling with MSVC.
#error This file should only be included when compiling with MSVC.
 ^
/tmp/meeat-app/node_modules/react-native-google-signin/ios/RNGoogleSignin/RNGoogleSignin.m:68:45: warning: 'sendAppEventWithName:body:' is deprecated: Subclass RCTEventEmitter instead [-Wdeprecated-declarations]
        return [self.bridge.eventDispatcher sendAppEventWithName:@"RNGoogleSignInError"
```

Those messages appear about 80 lines before the _:CFBundleIdentifier_ line. As you can see, the hint for the root cause can sometimes be found much earlier in the logs. The root cause in the above example is completely unrelated to a missing `:CFBundleIdentifier` entry.

## Always provide a full repro

As you can see in the example above, having a full repro is very helpful. Someone trying to debug can see all the relevant errors and input files. Even with the errors in the example above, without being able to see the full list of dependences and look at project files, someone could not have identified the actual bug.

## Related issues

* https://github.com/facebook/react-native/issues/14423

# For Discussion

Let's come up with a plan to mitigate confusion here. If this error constantly shows up for any number of unrelated failures, we can likely do a better job of surfacing the actual issue rather than simply leading people on a wild goose chase.

**Comment by cpojer** [comment]
This should be fixed with 0.59 as it was fixed in the latest RN cli: https://github.com/react-native-community/react-native-cli/commit/6526bdd834993267f6f3fed2f8521bf1a9b7b859

Yay!
