### ISSUE TITLE
0.57.1 Release apk do not show static local images.

### ISSUE THREAD

**Issue by anjapadu** [facebook/react-native#21308]
```
System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
      Memory: 340.11 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.11.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
      Android SDK:
        Build Tools: 23.0.1, 26.0.3, 27.0.0, 27.0.3, 28.0.2
        API Levels: 23, 26, 27, 28
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0
      react-native: 0.57.1 => 0.57.1
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-rename: 2.2.2
```
 Description
Debug is all alright. After build release apk version can't see local images.
Tried the #20358  workaround but get duplicated  drawable-xhdpi-v4....n.png: Error: Duplicate resources of all my images. Any ideas?

**Comment by rcorrie** [comment]
@anjapadu have you found a solution to the `Error: Duplicate resources` error? Having the exact same issue as you

**Comment by anjapadu** [comment]
@rcorrie No... i still have the error can't use static assets. 
And when i use bundle got the duplicated error. Probably react navigation have something to do with it also.
At the moment as a dirty solution im saving all my static images as base64 strings/files and using those as image.
