### ISSUE TITLE
AsyncStorage hangs infinitely on real device in debug mode.

### ISSUE THREAD

**Issue by ThomasStubbe** [facebook/react-native#21317]
## Environment
Environment:
  OS: Windows 10
  Node: 8.11.1
  Yarn: 1.9.4
  npm: 6.0.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: ^16.3.0-alpha.1 => 16.3.0
  react-native: 0.54.0 => 0.54.0

## Description

The code that hangs infinitely: 
```
return AsyncStorage
      .multiRemove(['param1', 'param2'], (error) => console.warn("Problem with clearing state: ", error))
      .then(() => console.log('cleared storage'));
```

- Tested on real devices (one plus, lenovo tablet, ZTE, ... every tested phone so far has it).
- Happens a lot more on windows
- With 'Chrome Debugger' and 'React Native Debugger'
- Doesn't happen all the time, but when it does, it happens A LOT (like 30 times in row)
- Even after cleaning the project, uninstalling the app, rebuilding, cleaning the storage: nothing helps.
- Seems to happen a lot more if an error occurred (which happens 1/2 on first start up), and you reload afterwards
- The params are not necessarily available in the store at that time, but it doesn't seem to matter
- This happens to be the first AsyncStorage call of the app. by removing it, it happens at the next one.

## Reproducible Demo
Really hard to reproduce, but I suppose: any project which is developed and debugged on a real device.

By the way:

- We must use a real device, since our app requires bluetooth
- This costs us at least 1 hour a day / person, if we cannot fix it within the month, we will look into implementing another version of SQLite or step away from react-native altogether.

**Comment by hramos** [comment]
Let's reopen once you're on the current version.
