### ISSUE TITLE
DatePickerAndroid "spinner" mode in Tablet opens both "spinner" and "calendar"

### ISSUE THREAD

**Issue by angelos3lex** [facebook/react-native#21313]
## Environment
  React Native Environment Info:
    System:
      OS: Linux 4.13 Ubuntu 16.04.5 LTS (Xenial Xerus)
      CPU: x64 Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz
      Memory: 205.11 MB / 7.71 GB
      Shell: 4.3.48 - /bin/bash
    Binaries:
      Node: 8.12.0 - /usr/bin/node
      Yarn: 1.10.1 - /usr/bin/yarn
      npm: 6.4.1 - /usr/bin/npm
    SDKs:
      Android SDK:
        Build Tools: 23.0.1, 25.0.0, 25.0.1, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.1
        API Levels: 23, 25, 26, 27, 28
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: 0.57.1 => 0.57.1 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-create-library: 3.1.2
      react-native-smtp-mailer: 1.1.6

## Description
When i open DatePickerAndroid with mode "spinner" in API 23 phone (android 6.0) it opens correctly.
But if i change to a tablet (Nexus 9 2048x1563 xhdpi) with API 23 (android  6.0 x86), then both spinner and calendar open as you can see in screenshot: (Also tested on Android 8 and android 7.1 tablet and bug exists, tested with RN v0.56 and RN v0.57)
![tablet_both_spinner_and_calendar_open](https://user-images.githubusercontent.com/18629179/46012310-7d702700-c0d1-11e8-81d0-e2ccd13c0c0e.png)

Code used:
```
DatePickerAndroid.open({
      date: new Date(2020, 4, 25),
      mode: "spinner"
    });
```

**Comment by dooboolab** [comment]
@angelos3lex I think this is expected in pure android.

**Comment by odyodyodys** [comment]
> 
> 
> @angelos3lex I think this is expected in pure android.

If I understand correctly somebody concluded the following "Lets display two things that do the same thing on android, at the same time!" and another person implemented it?

Sorry for being sarcastic but this is utterly useless and bad in many ways.

This is not even a date picker (or time picker that has the same behavior), its two date pickers.
