### ISSUE TITLE
PushNotificationIOS IOS 12 doesn't recieve remote notifications

### ISSUE THREAD

**Issue by djleonskennedy** [facebook/react-native#21323]
## Environment
Environment:
  OS: macOS High Sierra 10.13.6
  Node: 8.8.1
  Yarn: 1.9.4
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: Xcode 10.0 Build version 10A255
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.4.2 => 16.4.2
  react-native: 0.55.4 => 0.55.4

## Description
have set https://github.com/zo0r/react-native-push-notification this library just wrapper a round yours.
All was fine until IOS 12 have been release, we're using FCM, your product instagram and facebook works fine, could you advise whether you face same problem

## Reproducible Demo
setup remote push and send to IOS 12 device

**Comment by cx5168** [comment]
@djleonskennedy  
I have the same problem, how do you solve it? Thank you
