### ISSUE TITLE
npm install，报如下的错。请帮忙解决一下。

### ISSUE THREAD

**Issue by zhengxuanyi** [facebook/react-native#21329]
- [ ] Review the documentation: https://facebook.github.io/react-native
  - [ ] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Run `react-native info` in your terminal and paste its contents here.
环境：
操作系统：macOS High Sierra 10.13.6 
节点：10.11.0 
纱线：1.9.4 
npm：6.4.1 
Watchman：4.9.0 
Xcode：未找到
Android Studio：3.1 AI-173.4720617

包:(通缉=>已安装）
反应：16.0.0 => 16.0.0 
react-native：0.55.0 => 0.55.0
## Description
Describe your issue in detail. Include screenshots if needed. If this is a regression, let us know.
操作步骤：打开项目 npm install ，就报错了。
## Reproducible Demo
Let us know how to reproduce the issue. Include a code sample, share a project, or     share an app that reproduces the issue using https://snack.expo.io/. Please follow the guidelines for providing a MCVE: https://stackoverflow.com/help/mcve
![46055688-b6ff6b80-c17f-11e8-91de-ff13500aea00](https://user-images.githubusercontent.com/24428401/46060282-42cfc280-c195-11e8-9561-5c7dbdfebf80.png)
报错内容是这样的

**Comment by zhengxuanyi** [comment]
当我新建项目，走npm install时，显示成功。
> fsevents@1.2.4 install /Users/zhengxuanyi/AllProject/ReactNativeDoc/Demo/AwesomeProject/node_modules/fsevents
> node install

[fsevents] Success: "/Users/zhengxuanyi/AllProject/ReactNativeDoc/Demo/AwesomeProject/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
added 943 packages from 526 contributors in 25.15s


   System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
      Memory: 370.00 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.11.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: 0.57.1 => 0.57.1 
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by zhengxuanyi** [comment]
> 你可能需要翻墙

我创建新项目时 也没有翻墙，能正常下载，我不太懂为什么咬要这样操作？

**Comment by Lxxyx** [comment]
有可能是你写代码的时候，墙又变高了，翻墙吧 @zhengxuanyi

**Comment by zhengxuanyi** [comment]
> 有可能是你写代码的时候，墙又变高了，翻墙吧@zhengxuanyi

好，我买个vpn 试试看

**Comment by Fi2zz** [comment]
> > 你可能需要翻墙
> 
> 我创建新项目时 也没有翻墙，能正常下载，我不太懂为什么咬要这样操作？

> Node: 10.11.0 - /usr/local/bin/node

试试降级node版本，安装偶数版本的nodejs,降级到10.8试试
可能是npm或node的错误

**Comment by radko93** [comment]
Node 10 is not fully supported yet, please try with any other version. Please use English when submitting an issue.
