### ISSUE TITLE
Youtube video in WebView: StatusBar is gone after fullscreen

### ISSUE THREAD

**Issue by sebk** [facebook/react-native#21335]
- [ x] Review the documentation: https://facebook.github.io/react-native
  - [ x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
      Memory: 529.69 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.2 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.1.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0
      react-native: 0.57.1 => 0.57.1
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

## Description
I'm including a youtube video via a WebView.

Code snippet:

```
<WebView 
  style={styles.videoWebView}
  source={{uri: 'https://www.youtube.com/embed/tgbNymZ7vqY?playsinline=1'}}
  allowsInlineMediaPlayback={true}
/>
```

When the video comes **back from fullscreen the StatusBar is gone**.

## Reproducible Demo
A react-native project can be found here: 
https://github.com/sebk/RN-WebViewTest

**Comment by Titozzz** [comment]
Can you please open that issue on the new repository react-native-community/react-native-webview ? We are getting the Webview out of the core repo.

Thanks :rocket:
