### ISSUE TITLE
Removing propTypes from core components

### ISSUE THREAD

**Issue by TheSavior** [facebook/react-native#21342]
We have been using Flow for our components for a long while and have enjoyed much stricter type safety, enabling us to validate our code at compile time instead of with propTypes at runtime. We want to replace the remaining callsites of propTypes with Flow and deprecate the propType shapes exposed by React Native core. To do this, we need your help!

*This is step 1 of our multi step goal. Step 2 can be [found here](https://github.com/facebook/react-native/issues/21485).*

There are two classes of things that need to happen to complete this work. The first step is removing references from propTypes in our core components. The following are the individual files that need to be converted / updated. Each file should be converted in its own PR and each file is about the size of a good first issue to learn and get familiar with a part of the React Native codebase. If you’d like to convert one, pick one from the list, comment on this issue that you are interested in converting it, and follow the tips in [@empyrical's comment for help](https://github.com/facebook/react-native/issues/21342#issuecomment-424907040) successfully updating that file.

## Remove callsites from components:
- [x] Libraries/Components/Button.js -> Delete PropTypes
 - [x] MaskedViewIOS.ios.js -> Delete PropTypes
 - [x] Picker/Picker.js -> Delete PropTypes
 - [x] PickerAndroid.android.js -> Delete PropTypes
 - [x] StaticRenderer.js -> Delete PropTypes
 - [x] StatusBar/StatusBar.js -> Delete PropTypes
 - [x] TabBarIOS/TabBarIOS.ios.js -> Delete PropTypes
 - [x] TabBarIOS/TabBarItemIOS.ios.js -> Convert to Flow Types
 - [x] ViewPagerAndroid.android.js -> Delete PropTypes
 - [x] IncrementalPresenter.js -> Delete PropTypes, leave contextTypes
 - [x] SwipeableFlatList.js -> Delete PropTypes
 - [x] SwipeableListView.js -> Delete PropTypes
 - [x] SwipeableQuickActions.js -> DeletePropTypes (style changed to ViewStyleProp)
 - [x] ElementProperties.js -> Delete PropTypes
 - [x] InspectorPanel -> Delete PropTypes
 - [x] InspectorOverlay.js -> Delete PropTypes
 - [x] SnapshotViewIOS.ios.js -> Delete PropTypes
 - [x] LinkingExample.js -> Convert to Flow Types
 - [x] RNTesterBlock.js -> Delete PropTypes, strengthen Flow Types
 - [x] RNTesterButton.js -> Delete PropTypes
 - [x] RNTesterPage.js -> Delete PropTypes
 - [x] Modal.js -> Convert to Flow Types, slightly bigger task
 - [x] IntegrationTestHarnessTest
 - [x] InputAccessoryView -> no propTypes, but flow types need to get cleaned up

## Move and Rename custom `propType` definitions
For these, I think we should create a new folder, `react-native/Libraries/DeprecatedPropTypes`. Many of these files have both the Flow definition and the propTypes definition. "Split" means split these into two files, in the example of `EdgeInsetsPropType` it would mean having an `EdgeInsetsPropType.js` file that contains the commented flow types, and a `DeprecatedEdgeInsetsPropType.js` file inside the `DeprecatedPropTypes` folder. Eventually that folder will become the source for the new repo that we move out. 
 - [x] Create a new folder at react-native/Libraries/DeprecatedPropTypes (should be done as part of one of the other tasks)
 - [x] DeprecatedViewPropTypes -> Move, comments to ViewPropTypes
 - [x] EdgeInsetsPropType -> Split
 - [x] PlatformViewPropTypes -> Move
 - [x] TVViewPropTypes -> Split
 - [x] StyleSheetPropType -> Move
 - [x] createStrictShapeTypeChecker -> Move
 - [x] ViewAccessibility -> Split (in progress)
 - [x] ViewStylePropTypes -> Move 
 - [x] ImageProps -> Split (in progress)
 - [x] ImageSourcePropType -> Move
 - [x] ImageStylePropTypes -> Move
 - [x] TextPropTypes -> Move
 - [x] ColorPropType -> Move
 - [x] LayoutPropTypes -> Move, comments to StyleSheetTypes
 - [x] ShadowPropTypesIOS -> Move, comments to StyleSheetTypes
 - [x] TransformPropTypes -> Move, comments to StyleSheetTypes
 - [x] PointPropType -> Split

**Comment by empyrical** [comment]
*Reserving this space*

**Comment by rmcp1g15** [comment]
Im taking on the Libraries/Components/Button.js delete PropTypes conversion

**Comment by TheSavior** [comment]
@rmcp1g15 Thanks for jumping in! It looks like that one is already checked off (completed). Would you be willing to take a different one?

**Comment by kdastan** [comment]
@TheSavior I'll take ElementProperties.js, InspectorOverlay.js

**Comment by nd-02110114** [comment]
@TheSavior 
 I'll take  MaskedViewIOS.ios.js, ViewPagerAndroid.android.js

**Comment by peaonunes** [comment]
Just noticed that there is no proptypes in PickerAndroid.android.js, can you confirm?I will take ViewPagerAndroid.android.js instead.

**Comment by TheSavior** [comment]
> PickerAndroid

Looks like PickerAndroid.android.js was taken care of in [this commit](https://github.com/facebook/react-native/pull/21281) and I forgot to mark it off. Thanks for flagging!

**Comment by empyrical** [comment]
@danibonilha Just giving you a heads up about this pull request I made:

https://github.com/facebook/react-native/pull/21349

**Comment by danibonilha** [comment]
@empyrical okay, thanks, I'll just split EdgeInsetsPropType then.

**Comment by exced** [comment]
Should ViewStylePropTypes be splitted as well ? 
There's a dependency with PlatformViewPropTypes.

**Comment by exced** [comment]
Replacing ViewPropTypes will be fun ! It has a loot of cascade dependencies

**Comment by danibonilha** [comment]
I'll move StyleSheetPropType and rename it to Deprecated

**Comment by empyrical** [comment]
I am currently focusing more on SwipableFlatList as it is turning out to be a bit complex. If anyone else wants to take on `SwipeableQuickActions.js` it's up for grabs!

**Comment by gvarandas** [comment]
I'll move `ShadowPropTypesIOS` as well.

**Comment by dkaushik95** [comment]
Hey, Can I take `InspectorPanel`?

**Comment by TheSavior** [comment]
@dkaushik95, sounds good!

**Comment by kabbany** [comment]
Can I make changes for `IntegrationTestHarnessTest ` ?

**Comment by exced** [comment]
I can split ViewAccessibility

**Comment by dkaushik95** [comment]
Need help with 5 functions definitions to resolve issues of [PR 21392](https://github.com/facebook/react-native/pull/21392)

Function names: 
- `setInspecting`
- `setPerfing`
- `setTouchTargeting`
- `setNetworking`
- `onClick`

**Comment by gvarandas** [comment]
I wanted to thank the whole React team to give this opportunity for people to contribute to a project they use and believe.
Sometimes contributing to a big Open Source project may seem a distant reality and efforts like this are what motivate developers to overcome that fear or insecurity to submit their first PR.

Props to you, guys. ❤️

**Comment by kaueburiti** [comment]
@TheSavior can I take the ` InspectorPanel -> Delete PropTypes`?

**Comment by sopranolinist** [comment]
I'd like to take the ImageProps split if that's still available.

**Comment by danibonilha** [comment]
I'm taking ViewAccessibility  =)

**Comment by danibonilha** [comment]
I'm taking ViewAccessibility =)

**Comment by joodroid** [comment]
Hello ...

Can I do the `LayoutPropTypes` ?
I've tried `find` on this page, no one mention it,
but it has `in progress` mark on Eli's post

I really want to contribute,

Thank You 🍻

**Comment by TheSavior** [comment]
Yeah, seems like that duplication is not great and that seems like a good idea!

**Comment by yash324** [comment]
could I work on createStrictShapeTypeChecker please?

**Comment by TheSavior** [comment]
Yeah, that would be great

**Comment by TheSavior** [comment]
> I wanted to thank the whole React team to give this opportunity for people to contribute to a project they use and believe.
Sometimes contributing to a big Open Source project may seem like a distant reality and efforts like this are what motivate developers to overcome that fear or insecurity to submit their first PR.
>
>Props to you, guys. ❤️

@gvarandas I'm glad you have appreciated this and that you felt like this process was welcoming.

To all of you that have contributed to this task so far, thank you so much for your help. I was completely surprised by all of your interest in contributing to the project and support in completing these tasks. @empyrical, @rmcp1g15, @kdastan, @nd-02110114, @peaonunes, @danibonilha, @exced, @ronal2do, @dkaushik95, @gvarandas, @sopranolinist, and @Thomas0c, this work and your excitement has impacted us here at Facebook. We see that the community wants these opportunities, so we're thinking about how we can do more of this in the future.

This work was a major first step to one of our team's goals of having our components strictly typed and modernized. We would like to figure out how to continue providing opportunities to all of you as well as others to contribute to this goal.

The next step is removing mixins from the components that are still using `createReactClass`. I have [created a new issue](https://github.com/facebook/react-native/issues/21485) for removing `TimerMixin` and if you are interested I would love to get your help on fixing up those as well.

Thanks again for all of your contributions so far.

P.S. To those of you who have contributed to this task, we'd like to send you a token of our appreciation. Please email Hector Ramos at hramos at fb dot com with your Github username, full name, and address. We've got something for you. :)

**Comment by yash324** [comment]
Hi guys, I tried adding the fixes for createStrictShapeTypeChecker but am unable to run the flow tests on my local machine. I'm getting 1222 'Cannot resolve module' errors on the master branch itself. Spent a lot of time trying to find a way to fix it but in vain. I'd really appreciate some help on this :)

**Comment by TheSavior** [comment]
@yash324, are you running on Windows? I heard somewhere that Flow for React Native Flow is broken on master for Windows. Unfortunately, nobody around me has a Windows computer to be able to test / fix it. >_<

**Comment by yash324** [comment]
Duh! I guess you can remove my assignment then :(

**Comment by TheSavior** [comment]
Can anyone take moving `createStrictShapeTypeChecker`? That is the only thing left on this issue and then we can close it out! ❤️

**Comment by exced** [comment]
I can take it @TheSavior

**Comment by TheSavior** [comment]
This step is all done! Yay!

**Comment by douglasjunior** [comment]
How to reuse these propTypes now? 

In some libraries that I maintain, I do something like this:

```js
import React, { Component } from 'react';
import { Modal } from 'react-native';
import PropTypes from 'prop-types';

class Dialog extends Component {
    ...
} 

Dialog.propTypes = {
   ...Modal.propTypes,
   myCustomProp: PropTypes.string,
}
```

Any suggestions?

**Comment by TheSavior** [comment]
We plan to pull these propTypes out into another npm package that the community can maintain but the goal is that we don’t want to support propTypes, we recommend people use Flow or TypeScript instead.

**Comment by TheSavior** [comment]
It's been a long journey, but @yungsters just landed https://github.com/facebook/react-native/commit/23717c6381a41b1c5f189376bfa5bc73c7a4da87 which removed the remaining prop-types usages and the DeprecatedPropTypes files that you all helped create from React Native. 

We are finally free of `prop-types`!
