### ISSUE TITLE
Get Unable to resolve module error when create empty project

### ISSUE THREAD

**Issue by peacecwz** [facebook/react-native#21344]
## Problem

I created a new project with React Native CLI and run project. I got this error

` Unable to resolve module "@babel/runtime/helpers/interopRequireDefault"`

### Environment

Environment:
  OS:  macOS High Sierra 10.13.6
  Node:  10.10.0
  Yarn:  1.9.4
  npm:  6.4.1
  Watchman:  4.9.0
  Xcode:  Xcode 10.0 Build version 10A255
  Android Studio:  3.1 AI-173.4907809

Packages: (wanted => installed)
  react: 16.5.0 => 16.5.0

### Steps to Reproduce

1. Run `react-native init testapp && cd testapp`
2. Run `react-native run-ios`

**Comment by zibs** [comment]
Tracked here: https://github.com/facebook/react-native/issues/21310
