### ISSUE TITLE
Error while updating property 'marginRight' in shadow node of type: RCTView

### ISSUE THREAD

**Issue by qianshui423** [facebook/react-native#21353]
I am not very good at English, please understand. Below is my issue:

## Environment

Only appear on android platfrom.

Below is my global environment, and I modify version of react and react-native by my package.json

`React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.3
      CPU: x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 26.08 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.4.0 - ~/.nvm/versions/node/v8.4.0/bin/node
      npm: 4.6.1 - ~/.nvm/versions/node/v8.4.0/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, X 10.11, macOS 10.12, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 23.0.2, 23.0.3, 24.0.0, 24.0.1, 24.0.2, 24.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 27.0.3, 28.0.0, 28.0.0, 28.0.1
        API Levels: 16, 23, 24, 25, 26, 27, 28
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.0.0-alpha.6
      react-native: 0.43.4 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7`

I so sorry, I can't run 'react-native info' success. So, I display a package.json and .babelrc information:

part of package.json：

`"dependencies": {
    "ajv": "^6.5.2",
    "mobx-utils": "^3.0.0",
    "fbemitter": "2.1.1",
    "mobx": "3.1.0",
    "mobx-react": "4.1.8",
    "raven-js": "3.11.0",
    "react": "16.0.0-alpha.6",
    "react-native": "0.43.4",
    "react-native-measureme": "0.0.1",
    "react-native-keyboard-aware-scroll-view": "^0.2.8"
  },
  "devDependencies": {
    "react-native": "0.43.4"
    "babel-eslint": "8.2.6",
    "babel-jest": "23.4.0",
    "babel-plugin-transform-decorators-legacy": "1.3.5",
    "babel-preset-react-native": "2.1.0",
    "babel-preset-react-native-stage-0": "1.0.1",
    "eslint": "3.19.0",
    "eslint-plugin-react": "6.10.3",
    "eslint-plugin-react-native": "2.3.2",
    "jest": "23.4.1",
    "react-test-renderer": "16.0.0-alpha.6"
  }`

.babelrc:

`{
  "presets": ["react-native"],
  "plugins": ["transform-decorators-legacy"],
  "sourceMaps": true
}`

## Description

Background Introduction: I have two activity react native container(such as A, B).

Scene Introduction: When I stay at A, then open B. then I open other a page(component) of B, at last, I close A container by native bridge(operation flow: B -> native bridge -> A -> A close self)

screenshot:

![error](https://user-images.githubusercontent.com/20347672/46121998-12496080-c249-11e8-8ed0-2d66a13ee3c0.png)

## Reproducible Demo
I so sorry, I can't provide a example project because my project is private. And my error unable to reproduce stably.please please understand. Thanks

**Comment by qianshui423** [comment]
> Can you run `react-native info` and edit your issue to include these results under the **Environment** section?
> 
> If you believe this information is irrelevant to the reported issue, you may write `[skip envinfo]` under **Environment** to let us know.

I am not sure if it is my environmental problem, so I gave the global environment configuration and I modified version of react and react-native by my package.json. I desire to get help. Thanks

**Comment by qianshui423** [comment]
> Can you run `react-native info` and edit your issue to include these results under the **Environment** section?
> 
> If you believe this information is irrelevant to the reported issue, you may write `[skip envinfo]` under **Environment** to let us know.

Remarks: Only appear on android platfrom.

**Comment by qianshui423** [comment]
> 大佬，解决了吗？我调试的时候也会经常报这个错，重新run-android就好了，完全找不到问题在哪。

没解决

**Comment by hramos** [comment]
Please update to the latest version of React Native. #21755, which @mvanroon flagged as being the same issue as this one, is fixed in the latest 0.57 as well as in 0.58-rc.

**Comment by starsion** [comment]
我们也会遇到这种类型的错
Error while updating property 'xxx' in shadow node of type: RCTText(RCTView....)
