### ISSUE TITLE
Navigator ref passes a null instance

### ISSUE THREAD

**Issue by yelled3** [facebook/react-native#2135]
consider the following:
```js
import React from 'react-native';
const {
  Component,
  Navigator
  } = React;

const NavigatorPropTypes = Navigator.propTypes;

class CustomNavigator extends Component {

  static propTypes = {
    ...NavigatorPropTypes
  }

  _setRef = (navigator)=> {
    if (!navigator) {
      return; // why would this be null?
    }
    this.navigator = navigator;
  }

  render(){
    return (
      <Navigator
        ref={this._setRef}
        {...this.props}
        />
    );
  }

}

export default RouteNavigator;
```

at what situation would `_setRef` receive a null instance, i.e `navigator === null` ?

**Comment by ide** [comment]
Unmounting nulls the ref.

**Comment by ericvicenti** [comment]
Yep- this is a feature, not a bug.

We want to set `this.navigator` to `null` when the navigator gets unmounted or else we will have a memory leak. (And also it makes no sense to try and interact with an unmounted `Navigator`)

**Comment by yelled3** [comment]
@ide @ericvicenti 
thanks - that makes sense :-)
FYI, I couldn't didn't find any mention to this in the docs, though.
