### ISSUE TITLE
React Native modal popup flickering

### ISSUE THREAD

**Issue by vasyl91** [facebook/react-native#21369]
## Environment
Environment:
  OS: Windows 10
  Node: 10.9.0
  Yarn: 1.9.4
  npm: 6.2.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.1.0.0 AI-173.4907809

Packages: (wanted => installed)
  react: react@16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: 0.51.0 => 0.51.0

## Description
I implemented an alarm function in my app which uses following code in MainActivity.java to display splash over the lock screen:
```
@Override
protected void onCreate(Bundle savedInstanceState) {

    super.onCreate(savedInstanceState);
    final Window win = getWindow();
    win.addFlags(WindowManager.LayoutParams.FLAG_SHOW_WHEN_LOCKED |
            WindowManager.LayoutParams.FLAG_DISMISS_KEYGUARD |
            WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON |
            WindowManager.LayoutParams.FLAG_TURN_SCREEN_ON);
}
```

Everything works fine, but my app also uses modal to display certain content what generates following problem: If I lock the screen for couple of minutes while the app is open, then unlock it and try to pick the button that uses modal - whole screen starts to flicker and the only thing I can do is to lock the screen again.

When I remove the code form above, modal works fine, but I cant display splash over the lock screen.

## Reproducible Demo
1. Paste the code form description into MainActivity. 
2. Create a button that displays modal popup. 
3. When app is installed - lock the screen and wait couple of minutes.
4. Unlock the screen and tap created button.

**Comment by RSNara** [comment]
@vasyl91, can you create a minimal reproducible demo (in the form of a react native app)? I think that would make it much easier for us to debug and fix the problem.
