### ISSUE TITLE
Website should redirect to /docs/getting-started.html for invalid URLs

### ISSUE THREAD

**Issue by mkonicek** [facebook/react-native#2137]
See e.g.:
- https://facebook.github.io/react-native/docs/native-modules-ios.html
- https://facebook.github.io/react-native/docs/

Both redirect to https://code.facebook.com/ which is a poor experience.

Redirecting to https://facebook.github.io/react-native/docs/getting-started.html would also allow us to refactor URLs - old browser bookmarks will bring people to docs.

**Comment by mkonicek** [comment]
Looking into this.

**Comment by mkonicek** [comment]
See https://github.com/facebook/react-native/pull/2145

**Comment by mkonicek** [comment]
Looks like adding `404.html` didn't fix this.

**Comment by zpao** [comment]
I just updated the 404 handling on facebook.github.io so this is working now (might take a few minutes for some caches to clear).

> ... would also allow us to refactor URLs - old browser bookmarks will bring people to docs.

My suggestion here while using GitHub pages is to actually do something like #2145 and redirect old pages. In React we're using Jekyll and a plugin that lets us define the old URL in the metadata of the new file and then empty pages with meta refresh redirects are created automatically (eg, we redirect docs/index.html to getting-started https://github.com/facebook/react/blob/master/docs/docs/getting-started.md).

**Comment by mkonicek** [comment]
It works now: http://facebook.github.io/react-native/docs/invalid-url.html

Thanks a lot @zpao!
