### ISSUE TITLE
error: uncompiled PNG file passed as argument. Must be compiled first into .flat file..

### ISSUE THREAD

**Issue by smaltby** [facebook/react-native#21373]
## Environment
  React Native Environment Info:
    System:
      OS: Linux 4.15 Linux Mint 19 (Tara)
      CPU: x64 Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
      Memory: 6.15 GB / 15.61 GB
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 8.10.0 - /usr/bin/node
      Yarn: 1.9.4 - /usr/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        Build Tools: 27.0.3, 28.0.2
        API Levels: 17, 23, 27, 28
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: 0.57.1 => 0.57.1 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

## Description
When trying to run ./gradlew assembleDebug, the build fails with the following error:

<project-directory>/android/app/build/intermediates/res/merged/debug/drawable-hdpi/node_modules_reactnavigationstack_dist_views_assets_backicon.png: error: uncompiled PNG file passed as argument. Must be compiled first into .flat file..
error: failed parsing overlays.

## Reproducible Demo
[This repo demonstrates the bug.](https://github.com/smaltby/ExampleProject)

The commands I'm using to build the apk after cloning the example repository are as follows:
```
yarn install
react-native run-android
react-native bundle --dev false --platform android --entry-file index.js --bundle-output ./android/app/build/intermediates/assets/debug/index.android.bundle --assets-dest ./android/app/build/intermediates/res/merged/debug
cd android
./gradlew assembleDebug
```

**Comment by yonigozman** [comment]
Duplicate of https://github.com/react-navigation/react-navigation/issues/3097
