### ISSUE TITLE
[TextInput] fontWeight and fontStyle are not applied to TextInput (v0.8.0)

### ISSUE THREAD

**Issue by zmxv** [facebook/react-native#2140]
See https://rnplay.org/apps/PDWePA to reproduce the bug.

**Comment by ericvicenti** [comment]
@sahrens, this might be related to your recent changes to TextInput

**Comment by morenoh149** [comment]
I've run into this as well.

**Comment by sahrens** [comment]
Looks like this is an iOS-only problem, and only occurs with `multiline={false}` (which is the default).

I haven't touched iOS for a while - @nicklockwood, can you take a look?

**Comment by sahrens** [comment]
Sorry for the super slow response, this totally fell off my radar and most of the syled inputs we have been using are all multiline so we didn't notice internally.

**Comment by ccpmark** [comment]
I've done some playing around with this, and there are a few unexpected behaviors:
- You must have `multiline={true}` to apply any font styling.
- `fontWeight` and `fontStyle` applied simultaneously will cause neither to be applied
- Setting `fontSize` will strip any font weight styling.

You can see some examples in play here:
https://rnplay.org/apps/iiZDsA

**Comment by ccpmark** [comment]
I just created a ProductPains post for this: https://productpains.com/post/react-native/text-styles-not-applied-correctly-in-textinput

**Comment by grabbou** [comment]
Took me 5 hours to find the issue, but... the good thing is -> PR on its way!

**Comment by grabbou** [comment]
<img width="358" alt="screen shot 2016-04-24 at 01 14 37" src="https://cloud.githubusercontent.com/assets/2464966/14764493/f1aa12a6-09b9-11e6-8b3b-09680e3cdcc0.png">

Looks like it works :)

**Comment by geirman** [comment]
@christophermark any chance you'd be willing to submit a PR for this? @grabbou what do you think next steps ought to be?

**Comment by barbatus** [comment]
It's actually quite frustrating that it can't get fixed for a year already.

**Comment by sahrens** [comment]
@javache or @mmmulani - do you guys have time to take a look?  Pretty buggy.

**Comment by javache** [comment]
Oh this is pretty stupid. We redefine the font for every property you set

```
RCT_CUSTOM_VIEW_PROPERTY(fontSize, CGFloat, RCTTextView)
{
  view.font = [RCTConvert UIFont:view.font withSize:json ?: @(defaultView.font.pointSize)];
}
RCT_CUSTOM_VIEW_PROPERTY(fontWeight, NSString, RCTTextView)
{
  view.font = [RCTConvert UIFont:view.font withWeight:json]; // defaults to normal
}
RCT_CUSTOM_VIEW_PROPERTY(fontStyle, NSString, RCTTextView)
{
  view.font = [RCTConvert UIFont:view.font withStyle:json]; // defaults to normal
}
RCT_CUSTOM_VIEW_PROPERTY(fontFamily, NSString, RCTTextView)
{
  view.font = [RCTConvert UIFont:view.font withFamily:json ?: defaultView.font.familyName];
}
```

I'll look into fixing it.

**Comment by javache** [comment]
Fix up internally.

**Comment by jaredly** [comment]
Hmm I'm still seeing this issue on RN 0.39 (which was released Dec 1st, after the fix was committed...).
Are other people getting this working?

**Comment by bsiddiqui** [comment]
I'm still seeing this issue on `0.49.0`

**Comment by shergin** [comment]
@bsiddiqui So, `fontWeight` and `fontStyle` do not work with <TextInput> for you? iOS or Android?

**Comment by bsiddiqui** [comment]
@shergin iOS, yeah `fontWeight` doesn't work unless I make the TextInput multiline

**Comment by shergin** [comment]
@bsiddiqui Oh, that's a bummer. 😢  Only `fontWeight`? 
Could you please create a new issue for that, add a Snack example, and cc me?
cc @rigdern

**Comment by AfflatusX** [comment]
@bsiddiqui can you share a snippet? I tried to make my TextInput multiline but fontWeight still does not apply.
