### ISSUE TITLE
clang: error: no such file or directory: '..../Debug-appletvsimulator/libRCTAnimation.a'

### ISSUE THREAD

**Issue by jonesn3** [facebook/react-native#21400]
## Environment
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 31.25 MB / 8.00 GB
      Shell: 4.4.23 - /usr/local/bin/bash
    Binaries:
      Node: 8.11.2 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.1.0 - /usr/local/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
      Android SDK:
        Build Tools: 23.0.1, 23.0.2, 23.0.3, 24.0.0, 24.0.1, 24.0.2, 24.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2
        API Levels: 23, 24, 25, 26
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0
      react-native: 0.57.1 => 0.57.1
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      react-native-rename: 2.2.2

## Description
Build for iOS fails with

`with clang: error: no such file or directory: '/Users/user/Library/Developer/Xcode/DerivedData/app-eziwvgytfcyckcazzowfryoaspuu/Build/Products/Debug-appletvsimulator/libRCTAnimation.a'`

libRCTAntimation seems to be linked correctly to me. I am unsure on why appletvsimulator should be an issue. This is targeted as a iPhone project.

**Comment by sidferreira** [comment]
@GloboM Me too... Mine is with libBVLinearGradient...

**Comment by sidferreira** [comment]
trying 

https://github.com/mxcl/PromiseKit/issues/907

**Comment by sidferreira** [comment]
@GloboM Man, I just found in `Workspace Settings` an option `Build System`. I changed to `Legacy` and also changed the `Derived Data` to be `relative`. Seem that worked.

**Comment by zackify** [comment]
https://github.com/facebook/react-native/issues/19573#issuecomment-424346136

This solved it for me: switching to the legacy build system

**Comment by smashed-potatoes** [comment]
I had the same issue with the 'Debug-appletvsimulator' DerivedData path being used - I tracked the issue down to linking the wrong target version of the library I was using. If you run into this, make sure to select "libxxx.a from 'xxx'...." and **not** "libxxx.a from 'xxx_**tvOS**'...." when adding the link under Build Phase (where xxx is the library).

**Comment by YoranRoels** [comment]
@smashed-potatoes Thanks, saved me tons of time. This actually fixes the errors instead of ignoring it. 

Beware that changing to the legacy build system just ignores the errors, it doesn't actually fix them, if Apple decides to make this new build system mandatory you'll have to fix the errors anyway. I would suggest reading your errors carefully and looking for a solution like the above solution by @smashed-potatoes.
