### ISSUE TITLE
SyntaxError: Unexpected token '...' after fresh npm install

### ISSUE THREAD

**Issue by KevinGrandon** [facebook/react-native#2141]
This started happening on both 0.8 and 0.6, so my guess is that a dependency broke.

![ilpzase](https://cloud.githubusercontent.com/assets/122602/8916398/11ef4d68-3460-11e5-8f4a-db8f67d48ba1.png)

**Comment by KevinGrandon** [comment]
In my local index.ios.bundle, this leads to this line:
`warning = function(condition,format,...args){`

**Comment by ericvicenti** [comment]
Transform error. cc @amasad @DmitrySoshnikov

**Comment by ericvicenti** [comment]
Dupe of #2134. A workaround is explained there.
