### ISSUE TITLE
[0.57] <Text> rendering last line truncated

### ISSUE THREAD

**Issue by musicode** [facebook/react-native#21410]
- [ ] Review the documentation: https://facebook.github.io/react-native
  - [ ] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment

```
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.5
      CPU: x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
      Memory: 109.75 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
      Yarn: 1.3.2 - /usr/local/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 23.0.2, 24.0.0, 24.0.1, 24.0.2, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.3, 28.0.1
        API Levels: 19, 22, 23, 24, 25, 26, 27
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0
      react-native: ^0.57.1 => 0.57.1
    npmGlobalPackages:
      react-native-create-library: 3.1.2
```

## Description

Only reproduced on ios. please test on iPhone 7/8 plus.

## Reproducible Demo

```js
<Text
  numberOfLines={3}
  style={{
    color: '#555',
    fontSize: 15,
    lineHeight: 22,
    textAlign: 'justify',
    marginTop: 10,
  }}
>
  没事看看这是妈妈的吗羡慕吗羡慕羡慕吗羡慕羡慕羡慕羡慕羡慕羡慕蜂蜜蜂蜜马芳吗多么吗羡慕羡慕羡慕羡慕羡慕们出门出门出门呢想念你承诺承诺发怒你想念羡慕羡慕羡慕吗羡慕羡慕羡慕羡慕多么多么美的你都目瞪口呆口袋空空的口袋宽松款的马德里队来了多么多么羡慕羡慕吗羡慕羡慕羡慕羡慕羡慕羡慕羡慕吗羡慕羡慕羡慕这么美...
</Text>
```

![image](https://user-images.githubusercontent.com/2732303/45726194-e4cd3900-bbf0-11e8-84a3-d67abc0a7a91.png)

**Comment by dooboolab** [comment]
![image](https://user-images.githubusercontent.com/27461460/46432774-077f5600-c78a-11e8-9930-6908eab2217c.png)
This isn't reproducible in my `env`. I think it will be better to share more code.

**Comment by musicode** [comment]
@dooboolab please try iPhone 8 Plus

**Comment by rikur** [comment]
I'm having similar issues, but it seems to me that if `numberOfLines > 2` the text is always truncated to two lines. `numberOfLines = 1` works fine.

**Comment by rikur** [comment]
`numberOfLines` works fine in Android. iOS always cuts the text at 2 lines for `numberOfLines > 2`.

**Comment by cranberyxl** [comment]
FWIW - I can confirm that in our app if there is a view in the same hierarchy with a non-integer height, that text fields will not wrap properly.

**Comment by rikur** [comment]
Found a workaround: using a static height on the `<Text>` that has enough space for all the lines. Something is pretty off with how heights are calculated on for texts using custom fonts, on both platforms..

**Comment by jiangleo** [comment]
The text is rendered normally , when the set `height` is bigger than the lineHeight*numberOfLines。eg: height > lineHeight * numberOfLines = 22 * 3 = 66 , `height = 70`

```
<Text
  numberOfLines={3}
  style={{
    color: '#555',
    fontSize: 15,
    lineHeight: 22,
    textAlign: 'justify',
    marginTop: 10,
    height: 70,
  }}
>
  没事看看这是妈妈的吗羡慕吗羡慕羡慕吗羡慕羡慕羡慕羡慕羡慕羡慕蜂蜜蜂蜜马芳吗多么吗羡慕羡慕羡慕羡慕羡慕们出门出门出门呢想念你承诺承诺发怒你想念羡慕羡慕羡慕吗羡慕羡慕羡慕羡慕多么多么美的你都目瞪口呆口袋空空的口袋宽松款的马德里队来了多么多么羡慕羡慕吗羡慕羡慕羡慕羡慕羡慕羡慕羡慕吗羡慕羡慕羡慕这么美...
</Text>
```

Chinese supplement：
问题：设置了 numberOfLines = 2 时， Text 还是只显示 1 行。
方案：可能是行间距导致的，需要把 height 设置的比 2*lineHeight 还高一点点。

**Comment by rikur** [comment]
Still a bug

**Comment by nnabinh** [comment]
still happening to me on 0.59

**Comment by nnabinh** [comment]
still happening to me on 0.59.9
