### ISSUE TITLE
com.facebook.react.JavaScript (17): EXC_BAD_ACCESS (code=1, address=0xda9bf7c08)

### ISSUE THREAD

**Issue by NijaahnandhRV** [facebook/react-native#21434]
**Environment:**

```
OS: macOS Sierra 10.12.6
Xcode: Xcode 9.2 Build version 9C40b
Node: 6.11.1
npm: 3.10.10
Watchman: 4.9.0
react-native-cli: 2.0.1
```

**Description:**

When I run my code the app gets crashes in this line `context = [JSC_JSContext(contextRef) contextWithJSGlobalContextRef:contextRef]` which is from /Users/mac1/Documents/test/project/node_modules/react-native/React/Executors/RCTJSCExecutor.mm. Can anyone help me with this issue

**Crashlytics Log:**

[crashlytics_log.txt](https://github.com/facebook/react-native/files/2433474/crashlytics_log.txt)

**Comment by atishoo** [comment]
+1 same

**Comment by kyungjoongo** [comment]
+1 same

**Comment by hramos** [comment]
Can you provide an example of the actual code that triggers this crash?

**Comment by andresmtz98** [comment]
Similar problem with release variant :/.

> React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
      Memory: 34.43 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.1 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.57.8 => 0.57.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1

![captura de pantalla 2019-02-11 a la s 16 58 48](https://user-images.githubusercontent.com/18200380/52596507-7480b780-2e1e-11e9-9426-91112719b774.png)

**Comment by tommypd** [comment]
> Similar problem with release variant :/.
> 
> > React Native Environment Info:
> > System:
> > OS: macOS 10.14
> > CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
> > Memory: 34.43 MB / 8.00 GB
> > Shell: 3.2.57 - /bin/bash
> > Binaries:
> > Node: 10.15.1 - /usr/local/bin/node
> > Yarn: 1.13.0 - /usr/local/bin/yarn
> > npm: 6.4.1 - /usr/local/bin/npm
> > SDKs:
> > iOS SDK:
> > Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
> > IDEs:
> > Android Studio: 3.3 AI-182.5107.16.33.5264788
> > Xcode: 10.1/10B61 - /usr/bin/xcodebuild
> > npmPackages:
> > react: 16.6.3 => 16.6.3
> > react-native: 0.57.8 => 0.57.8
> > npmGlobalPackages:
> > react-native-cli: 2.0.1
> 
> ![captura de pantalla 2019-02-11 a la s 16 58 48](https://user-images.githubusercontent.com/18200380/52596507-7480b780-2e1e-11e9-9426-91112719b774.png)
> 
> That happens once the app has been opened and i press any button or textinput

Same here, do you have resolved?

**Comment by andresmtz98** [comment]
> > Similar problem with release variant :/.
> > That happens once the app has been opened and i press any button or textinput
> 
> Same here, do you have resolved?

Sure. In my case, it was due the Podfile and manual dependencies. Make sure your dependencies are added once because if you have X module to add in Podfile and the same X dependency in Project build phases maybe throws that error.

Example: 
Note my Podfile and build phases
![whatsapp image 2019-02-12 at 09 13 52](https://user-images.githubusercontent.com/18200380/53195068-da213080-35e2-11e9-954f-6c86441faef3.jpeg)
![whatsapp image 2019-02-12 at 09 18 00](https://user-images.githubusercontent.com/18200380/53195101-edcc9700-35e2-11e9-950a-53f94ab66e1f.jpeg)

Some dependencies were already added manually but i didn't know (I didn't understand a lot of this because i'm new with Pods :v)

**Comment by tommypd** [comment]
Thank you! Solved

**Comment by Titozzz** [comment]
Closing as it seems solved

**Comment by hpelitebook745G2** [comment]
@andresmtz98 I'm having this problem as well and I'm also new and have just been familiarized to Pods. Can you specify on which did you retain or remove based from your screenshots? I see some listed in your Podfile that are in Build Phases, same as mine. There no duplicates, but I still got the error.

**Comment by anmol-appzoy** [comment]
Hi @andresmtz98, can you please tell me which libraries you removed from project to work out in your's I tried but I am getting more errors after that.

**Comment by MomenYasser** [comment]
Guys i'm still have this issue, RN 60.5 
![image](https://user-images.githubusercontent.com/6758791/65458203-65022c00-de4d-11e9-8b14-6eab73181599.png)
