### ISSUE TITLE
Something went wrong while linking. Error: Cannot read property 'UIAppFonts' of null

### ISSUE THREAD

**Issue by montooner** [facebook/react-native#21432]
## Environment

```
  React Native Environment Info:
    System:
      OS: Linux 3.10 CentOS Linux 7 (Core)
      CPU: x64 Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
      Memory: 903.03 MB / 1.80 GB
      Shell: 4.2.46 - /bin/bash
    Binaries:
      Node: 8.12.0 - /opt/node/bin/node
      Yarn: 1.10.1 - /opt/node/bin/yarn
      npm: 6.4.1 - /opt/node/bin/npm
    SDKs:
      Android SDK:
        Build Tools: 27.0.3
        API Levels: 27
    npmPackages:
      react: ^16.5.1 => 16.5.1
      react-native: 0.57.0-rc.4 => 0.57.0-rc.4
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

## Trigger

I get this error when running `react-native link native-base`. I'm trying this package out for the the first time. `native-base` is set to ` "native-base": "^2.8.0"`.

## Full error

```
[vagrant@myapp app]$ react-native link native-base
rnpm-install info Linking assets to ios project
rnpm-install WARN ERRGROUP Group 'Resources' does not exist in your Xcode project. We have created it automatically for you.
rnpm-install ERR! Something went wrong while linking. Error: Cannot read property 'UIAppFonts' of null
Please file an issue here: https://github.com/facebook/react-native/issues

Cannot read property 'UIAppFonts' of null

TypeError: Cannot read property 'UIAppFonts' of null
    at Object.linkAssetsIOS [as copyAssets] (/home/vagrant/app/node_modules/react-native/local-cli/link/ios/copyAssets.js:45:31)
    at Object.keys.forEach.platform (/home/vagrant/app/node_modules/react-native/local-cli/link/link.js:104:16)
    at Array.forEach (<anonymous>)
    at linkAssets (/home/vagrant/app/node_modules/react-native/local-cli/link/link.js:94:32)
    at tasks.push (/home/vagrant/app/node_modules/react-native/local-cli/link/link.js:171:20)
    at <anonymous> 
```

## Similar reports around the web

  * [Cannot read property 'UIAppFonts' of null while running react-native link after installing native-base](https://github.com/facebook/react-native/issues/20900) - issue in 'react-native' (2018-08-29)
  * [Throws error on Android](https://github.com/oblador/react-native-vector-icons/issues/795) - issue in 'react-native-vector-icons' (2018-07-27)
  * [Error: Cannot read property 'UIAppFonts' of null](https://stackoverflow.com/questions/41798737/error-cannot-read-property-uiappfonts-of-null) - issue reported on SO (2017-01-23, older issue)

## Additional troubleshooting

  * It was suggested [on SO](https://stackoverflow.com/a/44273850) and [in react-native-vector-icons issues](https://github.com/oblador/react-native-vector-icons/issues/795#issuecomment-410377968) that this could be because Info.plist was deleted. It's present in my application.

## Reproducible Demo

I don't have an easily shared demo, unfortunately.

**Comment by montooner** [comment]
Hmm, I can't reproduce on a clean project. native-base links properly.

My guess is that my ios files aren't correct somehow. Is there a way I can check or restore them?

**Comment by jamonholmgren** [comment]
I had this problem and in my case it was because I had renamed the project but forgotten a few folders.
