### ISSUE TITLE
AppState change event called for Android but not iOS on initial load

### ISSUE THREAD

**Issue by riwu** [facebook/react-native#21431]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment

>   React Native Environment Info:
>     System:
>       OS: macOS High Sierra 10.13.5
>       CPU: x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
>       Memory: 316.95 MB / 16.00 GB
>       Shell: 3.2.57 - /bin/bash
>     Binaries:
>       Node: 8.12.0 - /usr/local/bin/node
>       Yarn: 1.9.4 - /usr/local/bin/yarn
>       Watchman: 4.9.0 - /usr/local/bin/watchman
>     SDKs:
>       iOS SDK:
>         Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
>     IDEs:
>       Android Studio: 3.1 AI-173.4819257
>       Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
>     npmPackages:
>       react: 16.5.0 => 16.5.0 
>       react-native: 0.57.1 => 0.57.1 

## Description
```
AppState.addEventListener('change', newState => {
  Alert.alert('new state', newState);
});
```
When the app is first loaded (eg. close from background and reopen), the above event is called on Android, but not on iOS. Should this inconsistency be fixed?

## Reproducible Demo
https://snack.expo.io/@riwu/appstate

**Comment by riwu** [comment]
-stale

**Comment by michalchudziak** [comment]
Hello there 👋 this issue seems to have been inactive for the past few weeks. Because of this, it's likely that the issue is not a high priority anymore or it has been solved by OP; for these reasons, we'll close it. But please, if it's actually still an issue with 0.59 please comment below and we can reopen it or please send us a Pull Request with a fix 😊

**Comment by michalchudziak** [comment]
Duplicate of: https://github.com/facebook/react-native/issues/18836
