### ISSUE TITLE
{0 && <SomeComponent>} will make `Invariant Violation: Text strings must be rendered within a <Text> component.`

### ISSUE THREAD

**Issue by natsuki-yamanaka** [facebook/react-native#21440]
## Environment
```
$ react-native info

  React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz
      Memory: 39.08 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.1 - ~/.nvm/versions/node/v8.11.1/bin/node
      Yarn: 1.9.4 - ~/.nvm/versions/node/v8.11.1/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.11.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
      Android SDK:
        Build Tools: 20.0.0, 22.0.1, 23.0.1, 23.0.2, 25.0.0, 25.0.2, 26.0.2, 26.0.3, 27.0.1, 27.0.3
        API Levels: 10, 16, 17, 19, 20, 22, 23, 25, 26, 27, 4, 8
    IDEs:
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0
      react-native: 0.57.1 => 0.57.1
```

## Description
Error occured in some double ampersand syntax.
In any render(), just write like below, so you see the error.
```
render() {
  return (
    <View>
      {0 && <Text>some text</Text>}
    </View>
  );
}
```

## Reproducible Demo
https://github.com/natsuki-yamanaka/ReactNativeIssueSample
I confirmed RN 0.56.0 does also same behavior.

## ScreenShot
<img src="https://user-images.githubusercontent.com/5186470/46296314-0c4ed900-c5d5-11e8-8e21-e097a1796f91.jpg" width=320 />

**Comment by maxim-c** [comment]
```0 && <Text>some text</Text>``` returns ```0```.
number ```0``` retrited like string.
you can't use strings without wrapping in ```<Text />``` in react-native.

**Comment by ide** [comment]
Use `null` instead of `0` here, because 0 is treated like other numbers (i.e. as text).

**Comment by natsuki-yamanaka** [comment]
Thank you. I don't used just value 0, I used variables that is sometimes 0. So I felt this is bug.
But it's not wrong From the ReactNative, I understand.
