### ISSUE TITLE
FlatList snapToInterval is not precise in long list

### ISSUE THREAD

**Issue by chicken-suop** [facebook/react-native#21441]
## Environment

> Environment:
>   OS: macOS 10.14
>   Node: 8.12.0
>   Yarn: Not Found
>   npm: 6.4.1
>   Watchman: 4.9.0
>   Xcode: Not Found
>   Android Studio: 3.2 AI-181.5540.7.32.5014246
> 
> Packages: (wanted => installed)
>   react: 16.3.1 => 16.3.1
>   react-native: https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz => 0.55.4

## Description
I'm using the [FlatList](https://facebook.github.io/react-native/docs/flatlist) component with around 50 elements. When my element height (and subsequently snapToInterval prop) are set to floats, rather than integers, there seems to be a proportionality increasing offset from the correct interval to snap to. The affect of this is very noticeable with a lot of elements. The further I scroll down a list the bigger the offset, so that when I get to the bottom, it's very noticeable.

This offset is still there with integers, but it's a lot less pronounced.
Screenshots:

First two are with height set to `105.14285714285714`, which is an iPhone 6s Plus' height divided by seven. The last two have height set to `105`, which is just the truncated version of the previous height.

**Height: 105.14285714285714 (at bottom):**
![105 14285714285714 at bottom](https://user-images.githubusercontent.com/24547185/46305343-75bcf080-c5b1-11e8-8453-476cb4bb82bc.PNG)

**Height: 105.14285714285714 (second from top):**
![105 14285714285714 second from top](https://user-images.githubusercontent.com/24547185/46305344-76558700-c5b1-11e8-87f3-80ce8ac58b7f.PNG)

**Height: 105 (at bottom):**
![105 at bottom](https://user-images.githubusercontent.com/24547185/46305345-76558700-c5b1-11e8-91f9-d8cc0fcbe6ff.PNG)

**Height: 105 (second from top):**
![105 second from top](https://user-images.githubusercontent.com/24547185/46305347-76558700-c5b1-11e8-860a-683a5b14c0c1.PNG)

## Reproducible Demo
https://snack.expo.io/@elliotschep/flatlist-snaptointerval-is-not-precise-in-long-list

**Comment by mjmasn** [comment]
There is a similar issue on Android and horizontal ScrollView with devices like the Nexus 5X which apparently has a screen width of `411.428571429dp` (wtf?), both with pagingEnabled and with integer intervals you can see the rounding errors creeping up as you scroll further along the view. On devices with integer screen width there is no problem.

**Comment by ElChurros** [comment]
Hi,

I am experiencing the exact same issue on my end with react native 0.59.9. Have you guys found a workaround since you posted this issue in october @ratskin @mjmasn ?

**Comment by ratskin** [comment]
Not me. I had to change my UI to account for this

**Comment by mjmasn** [comment]
@stale bot, this is still an issue as far as I know

**Comment by sharma0611** [comment]
I'm also having this issue as well

**Comment by sharma0611** [comment]
To anyone else facing this: I got around this issue by using snapToOffsets to achieve the same effect.

**Comment by Amalgatito** [comment]
Having the same issue!

**Comment by ttaallll** [comment]
> To anyone else facing this: I got around this issue by using snapToOffsets to achieve the same effect.

snapToOffsets solved it for me too.

I just calculated the stops of the next snap by the number of items and the margin between them.

for example:
```
const { width } = Dimensions.get('window');
this.IMAGE_WIDTH = width * (1 / 2.5)
this.image_margin = 5
this.nishhar = width - ((this.IMAGE_WIDTH + this.image_margin) * 2 + this.image_margin * 2)

dataNum = [1, 2, 3, 4, 5, 6]

return (<FlatList
            data={dataNum}
            renderItem={item => {
                return (
                    <View style={{
                        backgroundColor: item.index % 2 == 0 ? 'red' : 'blue',
                        width: this.IMAGE_WIDTH,
                        height: this.IMAGE_WIDTH,
                        marginLeft: this.image_margin,
                        marginRight: this.image_margin,
                    }}>
                    </View>)
            }}
            keyExtractor={this.keyGenerator}
            horizontal={true}
            snapToAlignment={"start"}
            snapToOffsets={[...Array(dataNum.length)].map((x, i) => (i * (this.IMAGE_WIDTH + 2 * this.image_margin) - (this.nishhar * 0.5)))}
            decelerationRate={"fast"}
            pagingEnabled
        />)
```

**Comment by mjmasn** [comment]
not stale

**Comment by enheit** [comment]
not stale

**Comment by chicken-suop** [comment]
@ttaallll I believe I also solved it like this. I haven't measured it, but I'd think you'd take a hit in performance (especially for large data sources), so I wouldn't consider this a final solution.

**Comment by ayalfishey** [comment]
Still an issue

**Comment by adamsolomon1986** [comment]
> > To anyone else facing this: I got around this issue by using snapToOffsets to achieve the same effect.
> 
> snapToOffsets solved it for me too.
> 
> I just calculated the stops of the next snap by the number of items and the margin between them.
> 
> for example:
> 
> ```
> const { width } = Dimensions.get('window');
> this.IMAGE_WIDTH = width * (1 / 2.5)
> this.image_margin = 5
> this.nishhar = width - ((this.IMAGE_WIDTH + this.image_margin) * 2 + this.image_margin * 2)
> 
> dataNum = [1, 2, 3, 4, 5, 6]
> 
> return (<FlatList
>             data={dataNum}
>             renderItem={item => {
>                 return (
>                     <View style={{
>                         backgroundColor: item.index % 2 == 0 ? 'red' : 'blue',
>                         width: this.IMAGE_WIDTH,
>                         height: this.IMAGE_WIDTH,
>                         marginLeft: this.image_margin,
>                         marginRight: this.image_margin,
>                     }}>
>                     </View>)
>             }}
>             keyExtractor={this.keyGenerator}
>             horizontal={true}
>             snapToAlignment={"start"}
>             snapToOffsets={[...Array(dataNum.length)].map((x, i) => (i * (this.IMAGE_WIDTH + 2 * this.image_margin) - (this.nishhar * 0.5)))}
>             decelerationRate={"fast"}
>             pagingEnabled
>         />)
> ```

thank you so much for sharing....this was the only thing that worked for me.

**Comment by ValentineCodes** [comment]
> > To anyone else facing this: I got around this issue by using snapToOffsets to achieve the same effect.
> 
> snapToOffsets solved it for me too.
> 
> I just calculated the stops of the next snap by the number of items and the margin between them.
> 
> for example:
> 
> ```
> const { width } = Dimensions.get('window');
> this.IMAGE_WIDTH = width * (1 / 2.5)
> this.image_margin = 5
> this.nishhar = width - ((this.IMAGE_WIDTH + this.image_margin) * 2 + this.image_margin * 2)
> 
> dataNum = [1, 2, 3, 4, 5, 6]
> 
> return (<FlatList
>             data={dataNum}
>             renderItem={item => {
>                 return (
>                     <View style={{
>                         backgroundColor: item.index % 2 == 0 ? 'red' : 'blue',
>                         width: this.IMAGE_WIDTH,
>                         height: this.IMAGE_WIDTH,
>                         marginLeft: this.image_margin,
>                         marginRight: this.image_margin,
>                     }}>
>                     </View>)
>             }}
>             keyExtractor={this.keyGenerator}
>             horizontal={true}
>             snapToAlignment={"start"}
>             snapToOffsets={[...Array(dataNum.length)].map((x, i) => (i * (this.IMAGE_WIDTH + 2 * this.image_margin) - (this.nishhar * 0.5)))}
>             decelerationRate={"fast"}
>             pagingEnabled
>         />)
> ```

This improved my experience. Thanks!

**Comment by AhmedAbuelenin** [comment]
Still facing this issue with RN 0.70.6.

**Comment by rjdestigter** [comment]
Encountered the same issue on  horizontal list with 1000 items of the same width. Switching to `snapToOffset` resolved this for me as well. The odd part was that the issue only occured when the _FlatList_ component's width was less than the device width and only on Android devices. 

Giving the component a fixed width (to avoid the floating point widths) also didn't resolve the issue. Setting `initialScrollIndex` to `0` rather than `500` (half the data size) did seem to resolve the issue but I do wonder if the problem would show up if I scrolled enough.

**Comment by thanhnd1o2** [comment]
I found in native code that the type of `snapToInterval` is int (/node_modules/react-native/React/Views/ScrollView/RCTScrollView.h). Therefore, every Float value from JS will be cast as int.
I modified type of `snapToInterval` to Float64 and i worked like a charm

**Comment by JencirJamal** [comment]
Same issue exist's for me too in some android devices. It happens for my vertical posts (Full device height) inside FlatList. Although the workaround mentioned above fixed the issue but now there is black margin of 5 pixels appearing in between the posts which makes my UI a bit odd. Would be good if this issue get's fixed in a proper way.

**Comment by reckziegelwilliam** [comment]
Bump

**Comment by himanshut230** [comment]
Still facing this issue

**Comment by fedorovichandrey** [comment]
Still facing the issue
