### ISSUE TITLE
[0.57.1] Android overflow doesn't register taps (touchable) in the "overflowed" area

### ISSUE THREAD

**Issue by rborn** [facebook/react-native#21455]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
 React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
      Memory: 62.65 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.9.0 - /usr/local/bin/node
      Yarn: 1.7.0 - ~/.npm-packages/bin/yarn
      npm: 6.0.1 - ~/.npm-packages/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 21.1.2, 23.0.1, 23.0.2, 23.0.3, 24.0.1, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.1, 27.0.2, 27.0.3, 28.0.2
        API Levels: 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28
    IDEs:
      Android Studio: 2.3 AI-162.4069837
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: 0.57.1 => 0.57.1 
```

## Description
The "new" overflow feature works great now except the fact that it doesn't register the taps on the outside area. That's **Android** only.

## Reproducible Demo
```
<View
        style={{
        width: 50,
        height: 50,
        borderColor: 'blue',
        borderWidth: 2,
        overflow: 'visible'
    }}
>
    <TouchableOpacity style={{ width: 100, height: 100, backgroundColor: '#f006' }}>
        <Text>some button</Text>
    </TouchableOpacity>
</View>
```

Tap inside the blue square - works. Tap on the red square but outside the blue one - it doesn't

Am I doing something wrong?  

Thank you 🤗

**Comment by YanvegHD** [comment]
Same issue here ! Tried everything...

**Comment by YanvegHD** [comment]
Typo, it's "Touchable" not "Toucheable"

**Comment by rborn** [comment]
@YanvegHD 😅

**Comment by YanvegHD** [comment]
No one ? :disappointed:

**Comment by zacksleo** [comment]
Same issue

**Comment by summmmer** [comment]
same issue

**Comment by arqex** [comment]
Same here, isn't it a workaround or an explanation?

**Comment by gasparteixeira** [comment]
Same here. RN 0.57.1

**Comment by Liqiankun** [comment]
Overflow area is not touchable on Android!

**Comment by Liqiankun** [comment]
@gasparteixeira Man, then what did you do to this issue? Change design?

**Comment by gasparteixeira** [comment]
@Liqiankun I change design. It doesn't work!

**Comment by Liqiankun** [comment]
@gasparteixeira OK, this is the only way. Thanks.

**Comment by loginov-rocks** [comment]
In fact, it's not required to switch overflow (`overflow: 'visible'`), any kind of touchable component doesn't work outside the rectangular of **width** x **height**.

**Comment by renaekathleen** [comment]
Still seeing this on 0.59.3.

**Comment by fontesrp** [comment]
Still happening on 0.59.9

**Comment by danielgindi** [comment]
This PR #26374 is supposed to fix this.

I've tested the code in an isolated environment (ViewGroup subclass in a simple Android project).

I have two problems:
1. CI in this repo fails to compile - without any error details.
2. Locally I can't compile for use in an RN project, due to `error: package com.facebook.hermes.reactexecutor does not exist`

Anyone who knows the correct steps for compiling RN for Android - is welcome to try this. And push the staff to merge this.

**Comment by mahdinba97** [comment]
still an issue on 0.61.2

**Comment by danielgindi** [comment]
Hey stale-bot, not it's not fixed, and the PR was not merged.

**Comment by kazzkiq** [comment]
We need a solution for this since iOS works as expected. This odd behavior on Android leads to unpredictable bugs that happen only in one platform (Android).

**Comment by danielgindi** [comment]
No, bot, it's still pending #26374

**Comment by lgenzelis** [comment]
Still happening in RN 0.62 :(

**Comment by tickietackie** [comment]
Still not fixed. I'm also waiting for this. Can somebody explain how you changed the design to make it work in another way? I also really tried a lot now and cannot find a way to make get around this.

**Comment by kazzkiq** [comment]
@tickietackie In my case I redesigned my entire component in a way that nothing would need to be pushed outside, causing overflow.

Grab a pen and a paper, and try to re-imagine your layout in a way that the overflown element doesn't need to be.

**Comment by metawort** [comment]
Still happening in RN 0.63.3

**Comment by AndrewMorsillo** [comment]
Still broken. Just lost a good portion of a day to this one. It is intensely frustrating that there has been a PR open to fix this for 1.5 _years_ with no movement. @safaiyeh any ideas on how we can get that PR merged and this 2+ year old frustrating platform inconsistency finally fixed?

**Comment by safaiyeh** [comment]
> Still broken. Just lost a good portion of a day to this one. It is intensely frustrating that there has been a PR open to fix this for 1.5 _years_ with no movement. @safaiyeh any ideas on how we can get that PR merged and this 2+ year old frustrating platform inconsistency finally fixed?

Thanks for bringing this up. I pinged them hopefully we can get this in, I’ll try to push it a bit more

**Comment by anhkieet** [comment]
Any updates on this issue. I am doing autocomplete textinput and facing the same issue

**Comment by YanvegHD** [comment]
It's been YEARS since this issue was open.

My workaround is thatI had to create a component with `position: 'absolute'` to get the 'overflow' effect on a touchable component.

I can only advise you to do the same, this situation is so rare that no one will ever fix it.

May your code work 🙏🏼

**Comment by drmas** [comment]
Another work around that worked for me is to use `TouchableOpacity` from `react-native-gesture-handler`;
