### ISSUE TITLE
Cookies/localStorage is not shared across WKWebView:s (RN 0.57.1)

### ISSUE THREAD

**Issue by epiceros** [facebook/react-native#21450]
Hi, we have an app with several webviews within it. If you log in from one of the webviews you should be logged in, in all of them (This should be expected, right?). The cookie/localStarage sharing works in both UIWebview, and the third party WKWebview component. Here is the PR that fixed it for that component, if it helps:
https://github.com/CRAlpha/react-native-wkwebview/pull/123

 React Native Environment Info:
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      Yarn: 1.9.2 - ~/.yarn/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.1.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
    npmPackages:
      react: 16.5.2 => 16.5.2
      react-native: 0.57.1 => 0.57.1
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

**Comment by kelset** [comment]
Hey there - WebView is in the process of being extracted to its own repo, please open a dedicated issue [there](https://github.com/react-native-community/react-native-webview)
