### ISSUE TITLE
Can't find variable: require (http://localhost:8081/index.delta...)

### ISSUE THREAD

**Issue by lebronjl** [facebook/react-native#21451]
## Environment
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
      Memory: 5.93 GB / 15.43 GB
    Binaries:
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5014246

## Description
I tried to update our react native 0.55.4 to the latest release (0.57.1) and I got an error (see screenshot below). To check if I did something wrong a created a new project from scratch using the react native init awesomeproject and I got to the same error.

![screenshot_2018-10-02-14-11-41-648_com react057test](https://user-images.githubusercontent.com/493384/46347836-3c39c300-c64d-11e8-99c7-27262aeca039.png)

## Reproducible Demo
1) Create a new project: react-native init awesomeproject
2) Try to run it on android (react-native run-android) and we get an error about the @babel/runtime
3) Install the @babel/runtime dependency: npm install --save-dev @babel/runtime
4) Try to run it on android (react-native run-android)

**Comment by MrCEO63** [comment]
Having similar issue since last month can figure out why the current version of react-native is having a bug issue and its not yet fix?
![image](https://user-images.githubusercontent.com/36667083/46349029-6afd6c80-c640-11e8-82c3-8c6574985bfe.png)
I am currently new in react native and this issue is frustrating me.

**Comment by lebronjl** [comment]
After trying on a different computer, the application works as expected, so it may be related to the Android configuration part. Anyway I have reinstalled all from scratch and the versions are the same on both computers.
