### ISSUE TITLE
Cant find ReactNativeComponentTree file

### ISSUE THREAD

**Issue by c0d3er** [facebook/react-native#21467]
"dependencies": {
    "native-base": "^2.8.1",
    "react": "16.5.0",
    "react-native": "0.57.0",
    "react-native-fs": "^2.11.15"
  }
I can't find ReactNativeComponentTree this one.

If they deprecate this then please tell me the way to get current element or node from event.target or event.currentTarget

**Comment by supagu** [comment]
I've run into this also.

I'm trying to resolve a target:

ReactNativeComponentTree.getInstanceFromNode(event.target);

but ReactNativeComponentTree seems to no longer exist in react-native: "react-native": "0.57.7",

**Comment by waqaramjad** [comment]
same issue here
