### ISSUE TITLE
ListView does not support contentOffset

### ISSUE THREAD

**Issue by Zygro** [facebook/react-native#2146]
I don't know if it's supposed to or not, but either way it doesn't work for me.

I would like for the ListView to begin on the border of these two sections, but no matter what I put as offset (other than 0,0), there is error:

"Error setting property 'alwaysBounceVertical' of RCTScrollView with tag #8: Sticky header index 0 was outside range {0,0}"

If I try to set alwaysBounceVertical, either true or false will make the offset 0,0. If I don't set it, I get this error. 
I think that setting initial section would be great feature, or at least being able to set offset manually.

**Comment by dubert** [comment]
There is a bug (https://github.com/facebook/react-native/issues/1878#issuecomment-127382680) where if the content's height is taller than the ScrollView (which wraps the ListView) then `contentOffset` will not work.

I found a workaround by mounting my list view with one row, then adding more when the data loaded in.

**Comment by ide** [comment]
Setting contentOffset is going to set you up for a world of pain in nearly all cases because of the multithreaded nature of RN... Does scrollWithoutAnimationTo meet your use case?
