### ISSUE TITLE
Injected Javascript works only with the initial page of Webview

### ISSUE THREAD

**Issue by cyb3rsalih** [facebook/react-native#21469]
## Environment
  React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 30.01 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.4 - /usr/local/bin/node
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
      Android SDK:
        Build Tools: 23.0.1, 25.0.0, 25.0.3, 26.0.2, 26.0.3, 27.0.0, 27.0.3
        API Levels: 19, 22, 23, 24, 25, 26, 27
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0
      react-native: 0.57.0 => 0.57.0
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      react-native-rename: 2.2.2

## Description
Javascript Injection works proper with source I provided like `example.com` . But when I go to another page like `example.com/shop` InjectedJavascript doesn't work in Android. I tried with different classes in html and different js codes. The result is same.  

## Reproducible Demo
Here is my Webview configuration, you can try

```JSX

// lcb-navigation is a div class in the source I provided. It works.
const hideLcb = "var h=document.getElementsByClassName('lcb-navigation')[0];h.style.display='none';"

//card class is in the next page. Does not work.
const hideCard = "var x=document.getElementsByClassName('card')[0];x.style.display='none';"

const injectJS = hideLcb+hideCard

<WebView style={{flex:1}}
          useWebKit={true} // This is for iOS
          source={{uri: 'https://5te5.sozlerkosku.com/'}}
          javaScriptEnabled={true}
          domStorageEnabled={true}
          startInLoadingState={true}
          injectedJavaScript={injectJS}
        />
//The account for testing
//user : testacc@test.com
//pass:  testacc
```

**Comment by kelset** [comment]
Hey there - WebView is in the process of being extracted to its own repo, please open a dedicated issue [there](https://github.com/react-native-community/react-native-webview)
