### ISSUE TITLE
Cant find variable: require on IOS

### ISSUE THREAD

**Issue by DZuz14** [facebook/react-native#21466]
## Environment
```
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
      Memory: 107.53 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 9.6.1 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.0.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5014246
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0
      react-native: 0.57.1 => 0.57.1
    npmGlobalPackages:
      react-native-cli: 2.0.1

```
## Description
Right after doing a brand new `react-native init` and running `react-native run-ios`, I am met with the following screen:
<img width="438" alt="screen shot 2018-10-03 at 2 08 30 pm" src="https://user-images.githubusercontent.com/19492185/46430629-943cfc00-c717-11e8-8a88-32df35a80678.png">

I have not changed any code whatsoever, except for adding the "@babel/runtime" package due to that also causing react-native projects out of the box to fail(See [#21310](https://github.com/facebook/react-native/issues/21310)).

Running on android via `react-native run-android` works swimmingly, so this seems to be an IOS specific bug. I am currently in the process of trying to update XCode to see if an update will fix it.

**Comment by kelset** [comment]
Closing in favour of https://github.com/facebook/react-native/issues/21475 since they are the same error.
