### ISSUE TITLE
Typescript definition for Switch not updated for 0.57 

### ISSUE THREAD

**Issue by Hauglid** [facebook/react-native#21470]
## Environment
  React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
      Memory: 87.84 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.3 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.3.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
      Android SDK:
        Build Tools: 27.0.3
        API Levels: 23, 25, 26, 27, 28
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: 16.4.14 => 16.4.14
      @types/react-native: 0.57.1 => 0.57.1
      react: 16.5 => 16.5.0
      react-native: 0.57.0 => 0.57.0
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
## Description
The typescript definition for Switch is missing the new props thumbColor and trackColor in:
 "@types/react-native": "0.57.1",

Gives error 
TS2339:
Property 'thumbColor' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Switch> & Readonly<{ children?: ReactNode; }> & Readonly<SwitchProps>'.

Property 'trackColor' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Switch> & Readonly<{ children?: ReactNode; }> & Readonly<SwitchProps>'.

**Comment by radko93** [comment]
@Hauglid can you submit a PR with fixes for this issue if you're familiar with the matter?

**Comment by TheSavior** [comment]
I'm not sure who manages the TypeScript definitions for React Native but our team only officially supports and maintains the Flow defs. I'd recommend opening an issue or PR to the repo which maintains the TypeScript definitions.
