### ISSUE TITLE
getConnectionInfo returns wrong info

### ISSUE THREAD

**Issue by itcurves** [facebook/react-native#21476]
- [ ] Review the documentation: https://facebook.github.io/react-native
  - [ ] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Environment:
  OS: Windows 10
  Node: 8.11.2
  Yarn: Not Found
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.1.0.0 AI-173.4720617

Packages: (wanted => installed)
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: 0.54.4 => 0.54.4

## Description
I am using NetInfo.getConnectionInfo() to get the current connection info. It works fine for the first time, lets say I was connected to wifi the it will show my wifi as type, but when my app is in background and I switch off my wifi and call this method it still says wifi although I am on cellular now.
## Reproducible Demo
1. console.log the connectioninfo
2. run the app on wifi
3. move app in background (you might need some way to run in the background)
4. turn off wifi
5. console log still show you it is wifi

any help much appreciated, just for information I am storing that data on server and need to know the accurate one.

thanks

**Comment by AndrewHenderson** [comment]
I can verify that this is still an issue on the latest release `0.57.4`.

**Comment by AndrewHenderson** [comment]
@itcurves Were you able to find a workaround for this issue?

**Comment by filippoitaliano** [comment]
I have the same issue with `@react-native-community/netinfo@1.3.0` and `react-native@0.59.1`. If the network state changes when the app is in background, `NetInfo.getConnectionInfo()` returns the older state until the state changes again with the app in foreground. I'll open a new issue on the community repo.

**Comment by ersel** [comment]
@filippoitaliano We're experiencing the same issue as well!

**Comment by AndrewHenderson** [comment]
Perhaps we can use [`AppState`](https://facebook.github.io/react-native/docs/appstate#app-states) to update the value somewhere else, like the Group Preferences.

**Comment by ersel** [comment]
that's an interesting idea, wonder if that would keep the ConnectionInfo state consistent. 🤔

**Comment by AndrewHenderson** [comment]
@ersel After further consideration, I don't see how what I suggested would work.

**Comment by ersel** [comment]
Yes, I guess you would not get notified if the connection type changes whilst you're in background mode. You would need to wait for the app state to change as well... I believe @filippoitaliano has opened a new issue on the community repo now. Let's see if maintainers will address this issue soon.
