### ISSUE TITLE
[iOS] - Real device - not connected to development server 

### ISSUE THREAD

**Issue by franj0** [facebook/react-native#21480]
## Environment
 React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
      Memory: 1.94 GB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.1.0 - /usr/local/bin/node
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        **Platforms: iOS 12.0, macOS 10.14 **, tvOS 12.0, watchOS 5.0
      Android SDK:
        Build Tools: 19.1.0, 20.0.0, 21.1.2, 22.0.1, 23.0.1, 23.0.2, 23.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.3, 28.0.2
        API Levels: 23, 24, 25, 26, 27
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5014246
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1
      **react-native: 0.56.0 => 0.56.0**
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

## Description
My iPhone(**iOS 12)** **cannot connect to http://localhost:8081/debugger-ui** or **react-native-debugger**,  while on **simulator everything working fine**.

## Reproducible Demo
1. Clean && rebuild && run app from xCode 10
2. Clean/Build/Run it's OK
3. App started on iPhone **iOS 12** 
4. In terminal there is no any changes, just stuck at 

> Loading dependency graph, done.!

[screen shot 2018-10-04 at 4 23 10 pm](https://user-images.githubusercontent.com/11553585/46480701-0bdf5980-c7f2-11e8-8f72-9222a3c46554.png)

## **I tried**: 
- FIX `double-conversion`errors, `third party` errors, `libfishhook.a` errors, `glog-0.3.4` + arch erorrs.
- Mac and iPhone connected to same wi-fi (pinged OK)
- Turn ON hotspot on iPhone and connect mac to it/ ping IP from mac was OK but still not connected to development server
- clear npm cache, reinstall npm modules...
- some thing disabled in xCode under edit-scheme enviroment
- Legacy build system
- New `react-native init project` - **RN 0.57** and run it on iPhone and same issue happend again.

I was looking for a solution for 2-3 days and try everything from stackoverflow + github but still not fixed.

I don't know what to try next? Is anyone have this issues?  
Also I don't see point to spam with screenshots, if anyone require I'll post it.
To me this looks like network problem but not solution yet.

Thank you

**Comment by DaniyarJakupov** [comment]
Try to load JS via your Mac IP Address. In AppDelegate.m:

```jsCodeLocation = [NSURL URLWithString:@"http://YOUR_MAC_IP:8081/index.bundle?platform=ios&dev=true"];```

**Comment by franj0** [comment]
Tried with 0.57 on new simple project, not fixed.
@DaniyarJakupov , forgot to mention that on post, tried earlier, also not fixed

SS:
![img_2637](https://user-images.githubusercontent.com/11553585/46484005-2d900f00-c7f9-11e8-9bbd-2b1932a84f65.PNG)

**Comment by rajatbeck** [comment]
Facing the same issue here.Any fixes.

**Comment by franj0** [comment]
Anyone, anything?

**Comment by DaniyarJakupov** [comment]
> Anyone, anything?

just updated my rn version to 0.57.1. This solution still works fine for me:

> Try to load JS via your Mac IP Address. In AppDelegate.m:

```
jsCodeLocation` = [NSURL URLWithString:@"http://YOUR_MAC_IP:8081/index.bundle?platform=ios&dev=true"];
```

**Comment by Monte9** [comment]
Ran into the same issue when upgrading from react-native: `0.54.6 => 0.57.0`

**Comment by franj0** [comment]
Hi everyone, try set your IP manually or switch to manual and back to DHCP,
sometimes can fix this stupid issue

uto, 13. stu 2018. u 01:58 Yanick Sevigny <notifications@github.com>
napisao je:

**Comment by huynhtansi** [comment]
I had same issue. For my case, open Xcode -> Go to Build Phases -> Delete "Bundle React Native code and images" phase (Remember copy script) -> Create new Run Script with same name & paste script -> Clean project & build again.

Reason: Xcode sometimes not run this script (I have no idea), so App cannot find main.bundle. Re-creating will make xocdeproject generate new ID for this script.

**Comment by michalchudziak** [comment]
I tried to run freshly generated `react-native init` (0.59.1) app on iPhone X via Xcode. Indeed there is no output in the terminal where the metro is running. However, the app starts, possibly the different instance of `metro` is being used.

**Comment by SudoPlz** [comment]
I quit trying to get that to work,
just

1. `npm install -g localtunnel`
2. lt --port 8081
3. Copy the url that this command outputs, and place it to your `AppDelegate.m` like so
`return [NSURL URLWithString:@"https://blue-termites-13.localtunnel.me/index.bundle?platform=ios&dev=true"];`

Thank me later.
