### ISSUE TITLE
"onNavigationStateChange" Unable to listen for route changes for single-page applications

### ISSUE THREAD

**Issue by leoyb** [facebook/react-native#21497]
I use onNavigationStateChange to monitor the change of URL:

`onNavigationStateChange = (navState) => {
   console.log(navState)
}`

however,  it will not be called if the page your WebView is trying to open is a SPA.

# Environment
```
OS:  macOS Sierra 10.13.6
Node:  8.9.1
Yarn:  0.24.5
npm:  5.4.0

Packages: (wanted => installed)
react-native: 0.53.0
react: 16.3.1
```

## Steps to Reproduce

1.WebView opens https://eos.live and logs in
2.Click to jump to other pages

When the web page in WebView uses history.pushState () to change URL, onNavigationStateChange does not execute

## Expected Behavior
onNavigationStateChange executes after each URL change

## Actual Behavior
onNavigationStateChange does not execute every time URL changes

## Reproducible Demo
```
<WebView
  onNavigationStateChange={this.onNavigationStateChange.bind(this)}
  source={{uri:"https://eos.live"}}
  allowsInlineMediaPlayback={true}
  domStorageEnabled={true}
  javaScriptEnabled={true}
  scalesPageToFit={false}
/>
```

**Comment by kelset** [comment]
Hey there - WebView is in the process of being extracted to its own repo, please open a dedicated issue [there](https://github.com/react-native-community/react-native-webview)

**Comment by thisisirfan** [comment]
@leoyb did you found any solution ?
