### ISSUE TITLE
[ListView] wrapped by NavigatorIOS contentInsets inconsistency -- somehow linked to translucency of the titlebar 

### ISSUE THREAD

**Issue by jaygarcia** [facebook/react-native#2151]
At first I thought my implementation of List View was wonky, but then I started to realize that no, there's a bug.

I've created a repo for this issue that's easy to recreate: https://github.com/ModusCreateOrg/react-native-navigator-ios-bugs

The crux of the problem is that after a layout reflow, ListView has a problem repositioning the top of the content, which it somehow calculates further to the top than originally displaying. 

Demos:
*UIExplorer* version:
![uiexplorer](https://cloud.githubusercontent.com/assets/180031/8937616/c0fdb372-3527-11e5-8eb0-33f866368a39.gif)

*Github project above* version:

![demo1](https://cloud.githubusercontent.com/assets/180031/8937670/ffdc1f70-3527-11e5-8a24-9f6163901fc8.gif)

![demo2](https://cloud.githubusercontent.com/assets/180031/8937691/188542ea-3528-11e5-9d9d-0829f074a724.gif)

**Comment by shlomiatar** [comment]
Hmm. 
Maybe you should try to set the `automaticallyAdjustContentInsets` prop on your ListView to false?
We had a few issues with lists padding and turning it off helped:

```js
<ListView  automaticallyAdjustContentInsets={false} />
```

**Comment by jaygarcia** [comment]
@schlomiatar, I will give that a go. I still think it's a bug since it doesn't work properly. :(

**Comment by jaygarcia** [comment]
@shlomiatar , no dice. It actually makes things really bad. 
![breaking](https://cloud.githubusercontent.com/assets/180031/8985632/52003f28-36a6-11e5-9e52-3e9caef7e6ee.gif)

**Comment by jaygarcia** [comment]
Another weirdness: Changing `translucent : false` from default `true` fixes this issue!

![pulldown](https://cloud.githubusercontent.com/assets/180031/8991851/3c047766-36c9-11e5-9e22-f6ff7219c9f9.gif)

**Comment by jaygarcia** [comment]
So it seems that `translucent : false` prevents you from scrolling to the bottom. D:

![pulldown](https://cloud.githubusercontent.com/assets/180031/9011981/403fbce4-377f-11e5-915d-310845612e52.gif)

**Comment by jaygarcia** [comment]
Turns out that this is some type of layout bug with Navigator IOS and child items.

In an iPhone 6, the only way to resolve some of these issues is with fudging things around.

1) Turn off translucent as detailed above.
2) *wrap* the ListView with another view, whose height is window.height - 60px

```
            <View style={{height: window.height - 60, backgroundColor : '#0000FF'}}>
                <ListView 
                    style={styles.listView} 
                    dataSource={this.state.dataSource} 
                    initialListSize={30} 
                    pageSize={30} 
                    scrollRenderAheadDistance={50} 
                    renderRow={this._renderRow}
                />
            </View>
```

![pulldown](https://cloud.githubusercontent.com/assets/180031/9098809/0bcc87b6-3b9a-11e5-9249-dbe5d9fb2cdd.gif)

**Comment by alvaromb** [comment]
Sorry for the off-topic @jaygarcia, but how do you managed to use ``NavigatorIOS`` inside a modal component?

**Comment by christopherdro** [comment]
I think it's important to note the difference of behavior when using ListView with NavigatorIOS specifically.

Here's a sample from 0.11.0-rc that shows you don't need to make any adjustments to the ListView to get the content to line up properly, with either translucent set to true or false. https://rnplay.org/apps/WF7zAg

For others who are having similar issues but are NOT using NavigatorIOS then your going to have add `automaticallyAdjustContentInsets={false}` to your ListView. See #1779 

@alvaromb You could check out the UIExplorer demo included on the repo. I think this should help.

@ide @brentvatne

**Comment by jaygarcia** [comment]
@christopherdro , thanks.  I'll look to upgrade RN versions soon. I do so very cautiously because things keep changing causing breaks in my app :)

**Comment by jaygarcia** [comment]
Closing this.
