### ISSUE TITLE
Execution failed for task ':app:compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by DigitalHawk1** [facebook/react-native#21512]
## Environment
  OS: Windows 10
  Node: 10.11.0
  Yarn: 1.10.1
  npm: 6.4.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5014246

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

## Description

I'm trying react-native run-android and its not working. I always get this error: 
8 errors
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

## Reproducible Demo
Empty project, just trying this tutorial: https://www.youtube.com/watch?v=6ZnfsJ6mM5c&t=398s

**Comment by kelset** [comment]
That's because you are using Expo/CRNA, so I don't think that `react-native run-android` can work.
