### ISSUE TITLE
react-native link error

### ISSUE THREAD

**Issue by fkobon** [facebook/react-native#21537]
## Environment
Environment:
  OS: macOS 10.14
  Node: 8.11.3
  Yarn: 1.7.0
  npm: 6.4.1
  Watchman: 4.9.0
  Xcode: Xcode 10.0 Build version 10A255
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

## Description
I am using Expo, I cannot link my project

```
Run: $ npm install native-base --save
Run: $ react-native link
```

I have this after last command:

```
MacBook-Pro:irc kobon$ react-native link
Scanning folders for symlinks in /Users/kobon/Dev/irc/node_modules (10ms)
rnpm-install info Linking assets to ios project
rnpm-install ERR! Something went wrong while linking. Error: Cannot read property 'pbxprojPath' of null
Please file an issue here: https://github.com/facebook/react-native/issues

Cannot read property 'pbxprojPath' of null
```

**Comment by shrijan** [comment]
I am having same issue with custom font at the moment. Start project with expo init test. then npm install react-native-vector-icons --save  and then i do react native link. It give me error Error: Cannot read property 'pbxprojPath' of null
i have spend all day looking for sol. none of sol metioned works

**Comment by budet-b** [comment]
Did you tried to re-eject your project ? Try delete you ios folder and re-eject again
I have the same problem, no solution for the moment...
