### ISSUE TITLE
[ScrollView] Expose 'decelerationRate' in 'scrollProperties' and allow dynamicity

### ISSUE THREAD

**Issue by aleclarson** [facebook/react-native#2153]
I'm interested in setting the `decelerationRate` of a `ScrollView` when a touch is released.

Based on the velocity of the touch at release, I will set `decelerationRate` accordingly to allow hard flicks to decelerate at a slower rate.

Can someone implement that real quick, or will I have to do it myself?

Thanks! :+1:

**Comment by dsibiski** [comment]
@aleclarson The React Native core team is super open and welcoming about Pull Requests from the community, so I'd say give it a shot and when you submit a PR, they will look at it and offer suggestions if need be.

(Also, they're pretty busy, so the more help from us, the better!)

**Comment by brentvatne** [comment]
@aleclarson - I don't think anybody is going to work on this, if you can't figure out how to do this yourself then please create an issue on ProductPains and try to get people who want the feature to upvote :) https://productpains.com/product/react-native/?tab=top

**Comment by aleclarson** [comment]
The best way to achieve this is through a JS-based `ScrollView`.

**Comment by aranda-adapptor** [comment]
For people who find this via google, `decelerationRate` now exists in `ScrollViewPropertiesIOS`
