### ISSUE TITLE
Why am I having the bugs coming from nowhere?

### ISSUE THREAD

**Issue by jimzqw** [facebook/react-native#21541]
So after so many debugging, I finally made my wife her app to do her things. It runs perfectly on her iPhone and for a month or so but suddenly it crashes and there's no way to open it. I tried to open the test version on my iPad and it crashes as well. I thought it has something to do with Firebase but everything on the database seems fine. It looks like RN is secretly upgrading itself on my app and caused the error. I just couldn't understand why it suddenly got the bug from nowhere while all the actions have error handlers. I ran the code on the simulator and turned out it was this.registerEvents not defined which is an error came with RN 0.57. I tried to clean build the project and the same error happened. I cleaned the cache and everything was okay. I can take it if these types of error happen after I make changes to the code, but not to an app that has been running successfully for a month. 
So is the crash happening because of the cache? Should I handle the app cache to prevent such things from happening again? I am seriously thinking about turning to Flutter. I heard it has fewer tools and APIs but I am so tired of the RN mysterious bugs. I apologize if the whole thing doesn't make sense, cuz I just learned RN in less than a month for fun. Anyway, if anybody knows the cause of the error please comment. 
Ps: wife is seriously questioning my coding ability...

**Comment by matthewkwong2** [comment]
There is something you might to check.
1. Is that a release build or debug build?
2. Did you set your application for iPhone only in XCode? 
3. Some times, you will develop your app with remote debugging on (e.g. being able to read your error message in Chrome), did you forgot to turn it off?
