### ISSUE TITLE
bundling failed: Error: Unable to resolve module `./../../react-transform-hmr/lib/index.js`

### ISSUE THREAD

**Issue by gowthamans268** [facebook/react-native#21547]
Looking for JS files in
D:\LW_Mobile\Projects\helloworld

Loading dependency graph, done.
error: bundling failed: Error: Unable to resolve module ./../../react-transform-hmr/lib/index.js from D:\LW_Mobile\Projects\helloworld\App.js: The module ./../../react-transform-hmr/lib/index.js could not be found from D:\LW_Mobile\Projects\helloworld\App.js. Indeed, none of these files exist:

D:\LW_Mobile\react-transform-hmr\lib\index.js(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
D:\LW_Mobile\react-transform-hmr\lib\index.js\index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
at ModuleResolver.resolveDependency (D:\LW_Mobile\Projects\helloworld\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:209:697)
at ResolutionRequest.resolveDependency (D:\LW_Mobile\Projects\helloworld\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:83:16)
at DependencyGraph.resolveDependency (D:\LW_Mobile\Projects\helloworld\node_modules\metro\src\node-haste\DependencyGraph.js:222:485)
at Object.resolve (D:\LW_Mobile\Projects\helloworld\node_modules\metro\src\lib\transformHelpers.js:149:25)
at dependencies.map.result (D:\LW_Mobile\Projects\helloworld\node_modules\metro\src\DeltaBundler\traverseDependencies.js:316:29)
at Array.map ()
at resolveDependencies (D:\LW_Mobile\Projects\helloworld\node_modules\metro\src\DeltaBundler\traverseDependencies.js:312:16)
at D:\LW_Mobile\Projects\helloworld\node_modules\metro\src\DeltaBundler\traverseDependencies.js:169:33
at Generator.next ()
at step (D:\LW_Mobile\Projects\helloworld\node_modules\metro\src\DeltaBundler\traverseDependencies.js:271:307)
BUNDLE [android, dev] ....../index.js ░░░░░░░░░░░░░░░░ 5.5% (52/221), failed.
::ffff:127.0.0.1 - - [06/Oct/2018:17:30:21 +0000] "GET /index.delta?platform=android&dev=true&minify=false HTTP/1.1" 500 - "-" "okhttp/3.10.0"

Command
react-native run-android

Environment
npm: 6.4.1
node: v8.12.0
windows 10
yarn 1.10.1

Package.json
{
"name": "helloworld",
"version": "0.0.1",
"private": true,
"scripts": {
"start": "node node_modules/react-native/local-cli/cli.js start",
"test": "jest"
},
"dependencies": {
"@babel/runtime": "^7.1.2",
"babel-preset-react-native": "^4.0.0",
"react": "16.5.0",
"react-native": "0.57.2"
},
"devDependencies": {
"@babel/cli": "^7.1.2",
"@babel/core": "^7.1.2",
"babel-jest": "23.6.0",
"babel-plugin-functional-hmr": "^1.0.24",
"babel-plugin-react-transform": "^3.0.0",
"jest": "23.6.0",
"metro-react-native-babel-preset": "0.48.0",
"react-test-renderer": "16.5.0",
"react-transform-hmr": "^1.0.4"
},
"jest": {
"preset": "react-native"
}
}

babel.rc

{
"presets": ["module:metro-react-native-babel-preset"]
}

**Environment**
React Native Environment Info:
System:
OS: Windows 10
CPU: x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
Memory: 9.04 GB / 15.88 GB
Binaries:
Yarn: 1.10.1 - C:\Users\gowthaman.s\AppData\Roaming\npm\yarn.CMD
npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
IDEs:
Android Studio: Version 3.2.0.0 AI-181.5540.7.32.5014246

**Comment by gowthamans268** [comment]
- Update all the packages such as Node and react native cli
- In Android studio install intel X86 Atom System Image, intel X86 Atom_64 System Image
- Close all the npm Terminal
- Open a new Command prompt and run react-native start --reset-cache
- Open a new Command prompt and run react-native run-android

**Comment by GreatAuk** [comment]
> * Update all the packages such as Node and react native cli
> * In Android studio install intel X86 Atom System Image, intel X86 Atom_64 System Image
> * Close all the npm Terminal
> * Open a new Command prompt and run react-native start --reset-cache
> * Open a new Command prompt and run react-native run-android

@gowthamans268 It is a new rule or just a solution for this problem？

**Comment by diegomachado7** [comment]
I'm also having the same problem.

**Comment by KamauIan** [comment]
I also can't fix it with `npm --reset-cache`.
