### ISSUE TITLE
[NavigatorIOS] left button does not release press target when press + drag (demo inside)

### ISSUE THREAD

**Issue by jaygarcia** [facebook/react-native#2154]
Example code in this repo: https://github.com/ModusCreateOrg/react-native-navigator-ios-bugs

The issue is when a NavigatorIOS is nested inside of a Navigator, the "pull down to close" interaction gets caught up with the "press *Close* to close" interaction.

This does not happen with a custom view using  a TouchableHighlight. 

Demo (NavigatorIOS):
![show_navigator](https://cloud.githubusercontent.com/assets/180031/8940935/b8ce7e8a-353a-11e5-8367-f491164b41a7.gif)

Demo (Generic child with TouchableHighlight):
![show_child](https://cloud.githubusercontent.com/assets/180031/8940952/cf47ceaa-353a-11e5-8a33-ccac114e1cc4.gif)

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/navigatorios-left-button-does-not-release-press-target-when-press-drag-demo-inside
