### ISSUE TITLE
React Native Error

### ISSUE THREAD

**Issue by pdaivik** [facebook/react-native#21558]
Whenever i try to run the command "react-native run-android" i am getting an error with red screen saying com.facebook.react.common.JavascriptException:Uncaught SyntaxError:Unexpected token{ on my device
![react error](https://user-images.githubusercontent.com/29033040/46594309-de472880-caef-11e8-9e88-7ac3e0e70eaa.jpeg)  I dont know where the error is my command prompt screenshots are 
![capture](https://user-images.githubusercontent.com/29033040/46594324-f7e87000-caef-11e8-8548-6e6c50b7f5a4.PNG)

**Comment by israelidanny** [comment]
@pdaivik did you manage to resolve this one?

**Comment by pdaivik** [comment]
> @pdaivik did you manage to resolve this one?

no actually i did not find any solutions for these issue

**Comment by israelidanny** [comment]
@pdaivik I solved the issue. It had to do with this issue (there are suggested workarounds there that worked for me):
https://github.com/facebook/react-native/issues/20150

**Comment by pdaivik** [comment]
> @pdaivik I solved the issue. It had to do with this issue (there are suggested workarounds there that worked for me):
> #20150

I have got one another issue, whenever i create a new react native app with expo and when i eject it and try to run on android i get this issue  #21722. Can you please help out me with this?
