### ISSUE TITLE
useNativeDriver animation redraws inside animating Modal

### ISSUE THREAD

**Issue by anshuul-kai** [facebook/react-native#21552]
## Environment
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
      Memory: 2.55 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.9.4 - ~/.nvm/versions/node/v8.9.4/bin/node
      Yarn: 1.5.1 - ~/.yarn/bin/yarn
      npm: 6.0.1 - ~/.nvm/versions/node/v8.9.4/bin/npm
      Watchman: 3.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 23.0.2, 23.0.3, 24.0.0, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.1, 27.0.2, 27.0.3
        API Levels: 23, 24, 25, 26, 27
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0
      react-native: 0.57.2 => 0.57.2
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

## Description
Clone the below repository to notice the bug with `native driver` animations inside an animating `Modal`. Simply turn the switch to on and notice it reset to off when modal closes. Removing the `animationType` on the `Modal` component or disabling `native driver` fixes the problem.

## Reproducible Demo
`git clone https://akbn@bitbucket.org/akbn/custom-switch.git`

**Comment by a-koka** [comment]
Yes, it's still an issue. I'm happy to provide more information if needed.

**Comment by 3luyka** [comment]
Will it be fixed?

**Comment by a-koka** [comment]
Yes, this is indeed still a problem on the latest version of the library.

**Comment by mmazzarolo** [comment]
I guess this might be causing [this react-native-modal issue](https://github.com/react-native-community/react-native-modal/issues/268)

**Comment by didrikkvanvik** [comment]
Been an issue for over a year now. Is it going to be fixed? Is there any other solution than not using the native driver?

**Comment by a-koka** [comment]
I've been using react-native for over 3 years. And although I love this framework, the underlying functionality is quite challenging to achieve given it supports multiple platforms. You either have to bite the bullet and write native code for corner cases or wait a long time for these issues to be addressed, simply because they aren't simple to fix.

Having said that, I'm hoping this gets some attention soon :)

**Comment by a-koka** [comment]
Yes, this is still an issue with the latest version of react-native 0.61.5. Thanks!

**Comment by a-koka** [comment]
This still requires community attention!

**Comment by a-koka** [comment]
Yes, this is still an issue.
