### ISSUE TITLE
TypeError: undefined is not a function (evaluating '_iterator[typeof Symbol === "function" ? Symbol.iterator : "@@iterator"]()')

### ISSUE THREAD

**Issue by DVassilev** [facebook/react-native#21550]
I'm running into this error when deploying debug release on Android emulator

```
E/ReactNativeJS: TypeError: undefined is not a function (evaluating '_iterator[typeof Symbol === "function" ? Symbol.iterator : "@@iterator"]()')
    
    This error is located at:
        in YellowBoxList (at YellowBox.js:104)
        in YellowBox (at AppContainer.js:93)
        in RCTView (at View.js:44)
        in AppContainer (at renderApplication.js:33)
```

Any idea on how I can trace it down? I saw another issue which mentioned using for..of can lead to this, but I don't use it. My dependencies are: `{
    "@mapbox/react-native-mapbox-gl": "^6.1.3",
    "geopoint": "^1.0.1",
    "moment": "^2.22.2",
    "react": "16.5.0",
    "react-native": "0.57.2",
    "react-native-blur": "^3.2.2",
    "react-native-code-push": "^5.4.2",
    "react-native-google-analytics-bridge": "^6.1.0",
    "react-native-modalbox": "^1.6.0",
    "react-native-onesignal": "^3.2.7",
    "react-native-pathjs-charts": "0.0.34",
    "react-native-picker": "^4.3.7",
    "react-native-progress": "^3.5.0",
    "react-native-simple-store": "^1.3.0",
    "react-native-statusbar-alert": "^0.4.0",
    "react-native-vector-icons": "^6.0.1"
  }`

It runs without issue on iOS.

**Comment by laurentS** [comment]
@DVassilev In case this helps, I had the same issue with `0.57.3`. From searching around, it seems linked to a variety of possible problems.
I fixed it with https://github.com/facebook/react-native/issues/20902 (using `babel/polyfill`). I saw suggestions to use `es6-symbol` to correct the fact that `Symbol` is not defined in RN's JS. But I also read that RN on android uses an outdated JS Compiler, which might explain why we're getting the problem on android but not iOS. You can apparently build your RN app to use a fork of the default JSC that is more up-to-date, but it seems overkill to me.
