### ISSUE TITLE
React native iOS webview  app reload on photo upload through camera or gallery.

### ISSUE THREAD

**Issue by viv3kk** [facebook/react-native#21568]
## Environment

React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
      Memory: 1.61 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.6.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
    IDEs:
      Android Studio: 2.3 AI-162.4069837
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0
      react-native: 0.57.2 => 0.57.2
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1

Iphone 6 physical device and simulators
RN: 0.57.2

## Description
React native iOS webview  app reload on photo upload through camera or gallery.

When trying to upload photo the webview screen reload to the base url. The same is is working for RN 0.56.

I am using webview with `useWebKit={true}`

```
<WebView
                  useWebKit={true}
                  ref={r => this.webview = r}
                  javaScriptEnabled={true}
                  source={{uri:uri_source}}
                  onMessage={this.msgHandler.bind(this)}
                  onNavigationStateChange={this.onNavigationStateChange.bind(this)}
                  onLoadEnd={this.onLoadEnd.bind(this)}
                  onLoadStart={this.onLoadStart.bind(this)}
                  onError={this.onErrorLoad_Webview.bind(this)}
                  domStorageEnabled={true}
                  startInLoadingState={true}
                  mixedContentMode={'compatibility'}
                  mediaPlaybackRequiresUserAction={true}
                  allowUniversalAccessFromFileURLs={true}
                  //renderLoading={this.renderLoading.bind(this)}
                  //scalesPageToFit={true}
              />
```

**Comment by viv3kk** [comment]
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
      Memory: 1.61 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.6.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
    IDEs:
      Android Studio: 2.3 AI-162.4069837
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0
      react-native: 0.57.2 => 0.57.2
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1

**Comment by viv3kk** [comment]
<WebView
                  useWebKit={true}
                  ref={r => this.webview = r}
                  javaScriptEnabled={true}
                  source={{uri:uri_source}}
                  onMessage={this.msgHandler.bind(this)}
                  onNavigationStateChange={this.onNavigationStateChange.bind(this)}
                  onLoadEnd={this.onLoadEnd.bind(this)}
                  onLoadStart={this.onLoadStart.bind(this)}
                  onError={this.onErrorLoad_Webview.bind(this)}
                  domStorageEnabled={true}
                  startInLoadingState={true}
                  mixedContentMode={'compatibility'}
                  mediaPlaybackRequiresUserAction={true}
                  allowUniversalAccessFromFileURLs={true}
                  //renderLoading={this.renderLoading.bind(this)}
                  //scalesPageToFit={true}
              />

**Comment by kelset** [comment]
Hey there - WebView is in the process of being extracted to its own repo, please open a dedicated issue [there](https://github.com/react-native-community/react-native-webview)
