### ISSUE TITLE
[ActivityIndicator][iOS] color doesn't work on ActivityIndicator with a testID prop on iOS

### ISSUE THREAD

**Issue by Freddy03h** [facebook/react-native#21563]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment

  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
      Memory: 499.50 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 9.8.0 - ~/.nvm/versions/node/v9.8.0/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v9.8.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
      Android SDK:
        Build Tools: 23.0.1, 23.0.3, 24.0.3, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.1
        API Levels: 23, 24, 25, 26, 27
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: 3.4.11 => 3.4.11
      react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728
      react-native: 0.57.3 => 0.57.3

## Description
`color` doesn't work on ActivityIndicator with a `testID` prop on iOS.
The ActivityIndicator stay white if it also get a `testID` prop (only on iOS, work well on Android).

## Reproducible Demo

Snack here : https://snack.expo.io/rylAF2uqm

Code to reproduce :
```js
import * as React from 'react';
import { View, StyleSheet, ActivityIndicator } from 'react-native';

export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <ActivityIndicator
          testID='activity-indicator' // comment this line to see the indicator in red
          size="large"
          color="#CF000A"
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#D4D4D4',
  },
});
```

**Comment by Freddy03h** [comment]
I think there is an issue with @react-native-bot because I'm using the last React-Native version : 0.57.2 …

**Comment by jakemmarsh** [comment]
I just ran into this issue on `0.59.1`.

**Comment by Twinbird24** [comment]
I'm having the same issue as well, on `0.59.9`.
