### ISSUE TITLE
Print: Entry, ":CFBundleIdentifier", Does Not Exist

### ISSUE THREAD

**Issue by chm2211912096** [facebook/react-native#21562]
react-native version: 0.56.0
when i run `react-native run-ios`, the terminal show `Print: Entry, ":CFBundleIdentifier", Does Not Exist`, and i try almost methods from https://stackoverflow.com but no use, i need help.
best wishes.

**Comment by dnlowman** [comment]
Is your project using Cocoapods? You might have to execute `pod install` within the `ios` directory.
