### ISSUE TITLE
Android release builds with old code (react native: 0.57.1)

### ISSUE THREAD

**Issue by ilyakar** [facebook/react-native#21564]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
(node:63850) ExperimentalWarning: The fs.promises API is experimental

  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.5
      CPU: x64 Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
      Memory: 19.93 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.1.0 - ~/.nvm/versions/node/v10.1.0/bin/node
      Yarn: 1.6.0 - /usr/local/bin/yarn
      npm: 6.4.0 - ~/.nvm/versions/node/v10.1.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5014246
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: 0.57.1 => 0.57.1 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

## Description
When making a release build of my app either through Android Studio or by running ./gradlew assembleRelease, the code is used from the last bundle, not the latest changes I have made in the past few days. In the past running a release build would just reflect the latest changes, since upgrading to react native 0.57.1, this is no longer the case.

**Comment by FibreFoX** [comment]
Can you re-check with RN 0.57.2 ? I think this might be fixed with commit https://github.com/facebook/react-native/commit/a4fed6e203efd481175e61b7d2aa1c2b037a4279

**Comment by kelset** [comment]
Hello there 👋 this issue seems to have a really low activity on it. This is probably because OP managed to find a solution - also, it was most likely related their precise configuration. Because of this inactivity, we are closing it - but please feel free to comment and post a repro for version 0.59 and we'll gladly re-open it 🤗

**Comment by Josh2941** [comment]
Still facing this issue with 0.59.2.
