### ISSUE TITLE
Getting error while using react-native-search-bar library - related to react-native somehow.

### ISSUE THREAD

**Issue by piyushchauhan2011** [facebook/react-native#2156]
I included `react-native-search-bar` library in the project and its giving this error.

![screen shot 2015-07-28 at 11 31 21 am](https://cloud.githubusercontent.com/assets/693487/8948150/2f115b4c-35e7-11e5-9367-9349b8884d70.png)

I asked the library creator and he couldn't figured out why...

The repository is: https://github.com/umhan35/react-native-search-bar
and discussion is here: https://github.com/umhan35/react-native-search-bar/issues/12

I checked with my project if I have react-native library linked correctly and it's present.
![screen shot 2015-07-29 at 10 31 04 am](https://cloud.githubusercontent.com/assets/693487/8948166/5f190542-35e7-11e5-901a-158c6e8dd4bd.png)

## Does this appear to be a react-native issue ?

**Comment by browniefed** [comment]
@brentvatne solved in other repos related discussion topics
