### ISSUE TITLE
[TabBarIOS] Completely custom tab bar

### ISSUE THREAD

**Issue by alejomendoza** [facebook/react-native#2157]
I was able to create custom iOs tabs changing the icons and colors. But not one that looks like the one in the attached image, where the middle tab is rounded and goes above the tab bar. Is this posible to create with only react native and the TabBarIOS.Item/TabBarIOS components? Styling these won't work and I'm new to Objective-C. 

![customtab](https://cloud.githubusercontent.com/assets/5351127/8949427/dd11a130-3578-11e5-963a-a9ca7aa4bd48.png)

**Comment by ide** [comment]
You could do three things:

 - Create a plain tab bar with five buttons, and absolutely position a circular view on top of the middle button. This is probably the easiest.
 - Write a tab bar in pure JS (easy to modify and customize but requires work)
 - Write a native tab bar and bridge it to JS (not recommended, I don't think you get much out of this)

**Comment by alejomendoza** [comment]
Awesome, thank you @ide!

**Comment by alejomendoza** [comment]
I forgot to show you my final results. Here's how I did it! I went for the first solution you gave me.

https://github.com/skyhitz/skyhitz-react-native-ios/blob/master/app/components/tabviews/maintabbar.js

**Comment by ide** [comment]
Very cool, thanks for sharing! The native tab bar just doesn't have a way to change the backgrounds, but you're right that a pure JS one would. Maybe in a couple weeks I can get mine ready and open-source it.

**Comment by ide** [comment]
here's the pure JS tab bar i mentioned if you were interested: https://github.com/exponentjs/react-native-tab-navigator

**Comment by alejomendoza** [comment]
Awesome, thanks I'll check it out!
