### ISSUE TITLE
react-native-sound-recorder@1.3.2" has incorrect peer dependency "react-native@^0.46.0"

### ISSUE THREAD

**Issue by elizhang221** [facebook/react-native#21573]
React Native Environment Info:
    System:
      OS: Windows 10
      CPU: x64 Intel(R) Core(TM) i3-4130 CPU @ 3.40GHz
      Memory: 5.17 GB / 15.93 GB
    Binaries:
      Yarn: 1.10.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5014246

After adding react-native-navigation, unable to recognize react-native-sound-player
![image](https://user-images.githubusercontent.com/27387483/46624117-bbfbdd80-cae4-11e8-9f2a-86b0ab131643.png)

I guess this is just the issue.
![image](https://user-images.githubusercontent.com/27387483/46624428-97543580-cae5-11e8-96af-75a85a4161bb.png)

**Comment by radko93** [comment]
Open an issue on `react-native-sound-recorder` as it's not strictly related to react-native itself.
