### ISSUE TITLE
react-transform-hmr/lib/index.js could not be found

### ISSUE THREAD

**Issue by duckscorpion13** [facebook/react-native#21584]
Environment:
OS: macOS 10.13.6
Node: 10.11.0
Yarn: 1.10.1
npm: 6.4.1
Watchman: 4.9.0
Xcode: Xcode 10.0 Build version 10A255

Packages: (wanted => installed)
react: 16.5.0
react-native: 0.57.2
 "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.48.0",
    "react-test-renderer": "16.5.0"

------------------------------------------------
according "Building Projects with Native Code"
react-native init "MyProject"

but it's not working in iOS simulator

**Comment by visnix** [comment]
run `react-native start --reset-cache`

**Comment by duckscorpion13** [comment]
it's working, thanks
