### ISSUE TITLE
Convert components off of createReactClass

### ISSUE THREAD

**Issue by TheSavior** [facebook/react-native#21581]
As part of our goal to modernize and type our core components, we need to migrate off of `createReactClass`. This task is to track the work to remove `createReactClass` from our codebase.

We can only convert off of `createReactClass` if the components don't use any mixins. [Step 1](https://github.com/facebook/react-native/issues/21342) and [Step 2](https://github.com/facebook/react-native/issues/21485) were removing a few of the mixins. There are still a few mixins left and we will need to completely finish that before we can complete this issue. 

However, we can at least get started by removing `createReactClass` from the components that currently don't use any mixins. The following is that list:

- [x] ReactAndroid/src/androidTest/js/ScrollViewTestModule.js
- [x] ReactAndroid/src/androidTest/js/UIManagerTestModule.js
- [x] RNTester/js/ListViewExample.js
- [x] RNTester/js/ImageExample.js
- [x] RNTester/js/TimerExample.js
- [x] RNTester/js/TextExample.ios.js
- [x] RNTester/js/ProgressBarAndroidExample.android.js
- [x] RNTester/js/PanResponderExample.js
- [x] RNTester/js/ListViewGridLayoutExample.js
- [x] RNTester/js/SwipeableFlatListExample.js
- [x] RNTester/js/ProgressViewIOSExample.js
- [x] RNTester/js/CameraRollView.js
- [x] IntegrationTests/LayoutEventsTest.js
- [x] IntegrationTests/ReactContentSizeUpdateTest.js
- [x] Libraries/Experimental/SwipeableRow/SwipeableRow.js

I got this list by running `grep -L "mixins:" $(grep -l -r createReactClass .)`. None of these files seem to be convertible by the [codemod provided by the react team](https://github.com/reactjs/react-codemod#explanation-of-the-new-es2015-class-transform-with-property-initializers).

I'm providing less instructions on this one because I think there are a lot of posts online about how to convert off of `createReactClass`.

**Comment by peaonunes** [comment]
I will take `RNTester/js/TimerExample.js` :)

**Comment by nd-02110114** [comment]
I will take `RNTester/js/ImageExample.js` and `RNTester/js/TextExample.ios.js`

**Comment by sopranolinist** [comment]
I would like to reserve ScrollViewTestModule.js and UIManagerTestModule.js, will be able to start later this evening sometime.

**Comment by himanshusoni** [comment]
I will take `SwipeableFlatListExample.js` and `ProgressViewIOSExample`

**Comment by exced** [comment]
I'll take RNTester/js/CameraRollView.js

**Comment by gengjiawen** [comment]
@TheSavior How change the `exports` to esm ? I think this will make the RNTester more modern.

**Comment by TheSavior** [comment]
@gengjiawen Facebook is still using requires and hasn't yet migrated to import/export. Some of the React Native optimizations like inline-requires are specifically for requires and the one for import isn't ready to go. We probably won't convert react-native's core to import/export until Facebook makes the switch over.

**Comment by minhnhattonthat** [comment]
I will take `ReactAndroid/src/androidTest/js/ScrollViewTestModule.js`

**Comment by exced** [comment]
I'll take `Libraries/Experimental/SwipeableRow/SwipeableRow.js`

**Comment by andrew-pyle** [comment]
@TheSavior Which of these components, if any still need to be migrated off `createReactClass`? There are two unchecked files in the initial description, but Pull Requests have been made for them.

- RNTester/js/ProgressBarAndroidExample.android.js #21604 #21600 #21874
- Libraries/Experimental/SwipeableRow/SwipeableRow.js #21876

**Comment by exced** [comment]
Yeay ! 🎉

**Comment by TheSavior** [comment]
Thank you all for the work on this cleanup. This is amazing. This has all been building up to being able to improve our flow types for these components now that we aren't on `prop-types`. I created an issue with that work here: https://github.com/facebook/react-native/issues/21581. 

Thanks again for everything you all have done so far!
