### ISSUE TITLE
Build archive error vs Xcode10

### ISSUE THREAD

**Issue by tunm1228** [facebook/react-native#21583]
Multiple commands produce '/Users/tu/Library/Developer/Xcode/DerivedData/Tituk-fndmfujccqhdareyswrxhslqzyvn/Build/Intermediates.noindex/ArchiveIntermediates/Tituk/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libyoga.a':
1) Target 'yoga' has a command with output '/Users/tu/Library/Developer/Xcode/DerivedData/Tituk-fndmfujccqhdareyswrxhslqzyvn/Build/Intermediates.noindex/ArchiveIntermediates/Tituk/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libyoga.a'
2) Target 'yoga' has a command with output '/Users/tu/Library/Developer/Xcode/DerivedData/Tituk-fndmfujccqhdareyswrxhslqzyvn/Build/Intermediates.noindex/ArchiveIntermediates/Tituk/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libyoga.a'

**Comment by wd** [comment]
There should something like bellow in your Podfile
```
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end

    if target.name == "yoga"
      target.remove_from_project
    end
  end
```

**Comment by dreallday** [comment]
Thanks @wd !

I ran into the same problem as OP and by adding what you said to the `Podfile` fixed the issue.

`
    if target.name == "yoga"
      target.remove_from_project
    end
`

**Comment by AshokICreate** [comment]
The above solution works...

**Comment by ObidosDev** [comment]
Also do not forget call `pod install`

**Comment by prashen** [comment]
@wd Thanks it worked for me.

**Comment by joeljerushan** [comment]
`pod Install` then `File > Workspace Settings > Build System > Legacy Build System.` will work in all time :)

**Comment by gudbrand3** [comment]
I got following errors with react-native 0.60.5 

1) Target 'yoga' has a command with output '~/Library/Developer/Xcode/DerivedData/.../IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libyoga.a'
2) Target 'yoga' has a command with output '~/Library/Developer/Xcode/DerivedData/.../IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libyoga.a'

Solved it by adding below:

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end

    if target.name == "yoga"
      target.remove_from_project
    end
  end
end

at the end of the pod file followed by **pod update**
