### ISSUE TITLE
Via Cocoapods: No visible @interface for 'RCTRootView' declares the selector 'setReactPreferredFocusedView:'

### ISSUE THREAD

**Issue by itinance** [facebook/react-native#21593]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment

```
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.4
      CPU: x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
      Memory: 270.53 MB / 16.00 GB
      Shell: 4.4.23 - /usr/local/bin/bash
    Binaries:
      Node: 10.11.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.2, macOS 10.13, tvOS 11.2, watchOS 4.2
      Android SDK:
        Build Tools: 23.0.1, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.3, 28.0.0
        API Levels: 23, 24, 25, 26, 27
    IDEs:
      Android Studio: 3.1 AI-173.4670197
      Xcode: 9.2/9C40b - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0
      react-native: 0.57.2 => 0.57.2
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1

```
## Description

Installing ReactNative with Cocoapods gives the error mentioned in title:

> No visible @interface for 'RCTRootView' declares the selector 'setReactPreferredFocusedView:'

It will be fired in RCTTVView.m line # 240.

<img width="865" alt="screenshot 2018-10-09 10 42 31" src="https://user-images.githubusercontent.com/1758597/46657257-23cb2a80-cbb0-11e8-8235-c4e4caf18590.png">

## Reproducible Demo

A reproducible Repository can be found here:

https://github.com/itinance/rn-compilation-error

Steps to reproduce from scratch:

> cd /tmp
> react-native init test
> cd test/ios
> pod init

Open `Podfile` with an text editor and add the following Pods:

```
target 'test' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rn_compile_error
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'ART',
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
#    'BatchedBridge', # already removed
    'RCTText',
    'RCTImage',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    'RCTPushNotification',
    'RCTBlob',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTSettings',
    'RCTLinkingIOS',
    'RCTGeolocation',
    'RCTAnimation',
    'tvOS',
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

end
```

XCode -> Build -> Error

This compilation error doesn't occur with static bundled react native instead of the Cocoapods version.

**Comment by itinance** [comment]
Maybe it is worth to mention that both files (RCTTVView.m) are fully equal to each other in both the static bundled version and the version delivered by Cocoapods.

The same with RCTRootViewInternal.h, which offers the method `setReactPreferredFocusedView`

**Comment by dlowder-salesforce** [comment]
`RCTTVView.m` should not be in iOS targets, only in tvOS targets.  Seems like a Podfile error.

**Comment by itinance** [comment]
I confirm that this should also be fixed in Podfile. However, there is a blind method call in the code that will never be resolved since this method is not existing at all
