### ISSUE TITLE
Horizontal FlatList is not ok on Android (iOS is OK)

### ISSUE THREAD

**Issue by AlirezaAkbarix** [facebook/react-native#21595]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment

    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-2635QM CPU @ 2.00GHz
      Memory: 818.48 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.9.4 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.4.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.2, macOS 10.13, tvOS 11.2, watchOS 4.2
      Android SDK:
        Build Tools: 23.0.1, 23.0.2, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.2, 27.0.3
        API Levels: 16, 18, 19, 22, 23, 24, 25, 26, 27
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 9.2/9C40b - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.5.1 => 16.5.2 
      react-native: ^0.57.1 => 0.57.1 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
      react-native-macos-cli: 2.0.1

## Description
Code is so simple:

      <FlatList
            horizontal={true}
            data={this.state.data}
            style={{backgroundColor:'yellow'}}
            showsHorizontalScrollIndicator={false}
            keyExtractor={this._keyExtractor.bind(this)}
            renderItem={({item}) => <ProductItem navigation={this.props.navigation} dataItem={item} key= 
            {item.id}/>}/>

As you can see below when app is RTL and list has just one content (that doesn't fill it's width) on Android it goes to the end (left), iOS behavior is OK as expected. LTR is OK on both.

**LTR:**

- Android:
![image](https://user-images.githubusercontent.com/15062651/46650956-427af280-cbab-11e8-83fd-b0f2aaf7ba89.png)
- iOS:
![image](https://user-images.githubusercontent.com/15062651/46651047-9d144e80-cbab-11e8-8a0a-6fe032913453.png)

**RTL:**
- Android:
![image](https://user-images.githubusercontent.com/15062651/46650881-0182de00-cbab-11e8-9a6b-aa99417a5d9b.png)
- iOS:
![image](https://user-images.githubusercontent.com/15062651/46651033-8d950580-cbab-11e8-80d2-d8ca00daef18.png)

## Reproducible Demo
none

**Comment by kelset** [comment]
Can you try updating to 0.57.2?

**Comment by chrusart** [comment]
And if it's still NOT ok, try 0.56.

**Comment by AlirezaAkbarix** [comment]
Its `Android` issue (not `iOS`) and still exists on 0.57.2

**Comment by yaronlevi** [comment]
Seeing this also on 0.55.0 + Android

**Comment by MahmoudAliIbrahim** [comment]
+1 on 0.57

**Comment by FadiAboMsalam** [comment]
+1 on 0.57.3

**Comment by nirmalrevar** [comment]
Facing Same issue only in Android.

**Comment by matinzd** [comment]
It has also problem for large lists on RTL! When contents get too large flatlist will automatically scrolls to first items when ` horizontal={true}`
