### ISSUE TITLE
RunAndroid: startServerInNewWindow() issue in fresh project.

### ISSUE THREAD

**Issue by Utkarsh183** [facebook/react-native#21605]
Fresh created project with react-native init.

If running "npm run start PORT=8081" or  "react-native start" and thereafter  "run-android"  in another node.js command prompt window, it works fine.

When running  "react-native run-android", it should open Node.js server in new window, but gives following error.

![capture3](https://user-images.githubusercontent.com/43995458/46674884-e049de00-cbfa-11e8-92cd-cd480056f964.PNG)

Something needs to be fixed, maybe PATH environment variable.

**Comment by Utkarsh183** [comment]
//package.json

{
  "name": "TestPro2",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.5.0",
    "react-native": "^0.57.0"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.48.0",
    "react-test-renderer": "16.5.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by jamsch** [comment]
Looks like `adb` isn't in your PATH.

**Comment by Utkarsh183** [comment]
It's there. Checked!
