### ISSUE TITLE
 fedora 28 react-native run-android

### ISSUE THREAD

**Issue by 109171650** [facebook/react-native#21617]
React Native Environment Info:
    System:
      OS: Linux 4.18 Fedora 28 (Workstation Edition) 28 (Workstation Edition)
      CPU: x64 Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz
      Memory: 7.30 GB / 15.50 GB
      Shell: 4.4.23 - /bin/bash
    Binaries:
      Node: 8.12.0 - /usr/bin/node
      npm: 6.4.1 - /usr/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        Build Tools: 23.0.1, 26.0.3, 27.0.3, 28.0.2, 28.0.3
        API Levels: 23, 26, 27, 28
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: 0.57.2 => 0.57.2 
    npmGlobalPackages:
      react-native-cli: 2.0.1

The development server returned response error code: 500

URL: http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false

Body:
{"originModulePath":"/root/rose/App.js","targetModuleName":"./../react-transform-hmr/lib/index.js","message":"Unable to resolve module ./../react-transform-hmr/lib/index.js from /root/rose/App.js: The module ./../react-transform-hmr/lib/index.js could not be found from /root/rose/App.js. Indeed, none of these files exist:\n * /root/react-transform-hmr/lib/index.js(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)\n * /root/react-transform-hmr/lib/index.js/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)","errors":[{"description":"Unable to resolve module ./../react-transform-hmr/lib/index.js from /root/rose/App.js: The module ./../react-transform-hmr/lib/index.js could not be found from /root/rose/App.js. Indeed, none of these files exist:\n * /root/react-transform-hmr/lib/index.js(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)\n * /root/react-transform-hmr/lib/index.js/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)"}],"name":"Error","stack":"Error: Unable to resolve module ./../react-transform-hmr/lib/index.js from /root/rose/App.js: The module ./../react-transform-hmr/lib/index.js could not be found from /root/rose/App.js. Indeed, none of these files exist:\n * /root/react-transform-hmr/lib/index.js(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)\n * /root/react-transform-hmr/lib/index.js/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)\n at ModuleResolver.resolveDependency (/root/rose/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:209:697)\n at ResolutionRequest.resolveDependency (/root/rose/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:83:16)\n at DependencyGraph.resolveDependency (/root/rose/node_modules/metro/src/node-haste/DependencyGraph.js:222:485)\n at Object.resolve (/root/rose/node_modules/metro/src/lib/transformHelpers.js:149:25)\n at dependencies.map.result (/root/rose/node_modules/metro/src/DeltaBundler/traverseDependencies.js:316:29)\n at Array.map ()\n at resolveDependencies (/root/rose/node_modules/metro/src/DeltaBundler/traverseDependencies.js:312:16)\n at /root/rose/node_modules/metro/src/DeltaBundler/traverseDependencies.js:169:33\n at Generator.next ()\n at step (/root/rose/node_modules/metro/src/DeltaBundler/traverseDependencies.js:271:307)"}
processBundleResult
BundleDownloader.java:296
access$200
BundleDownloader.java:37
onResponse
BundleDownloader.java:174
execute
RealCall.java:153
run
NamedRunnable.java:32
runWorker
ThreadPoolExecutor.java:1162
run
ThreadPoolExecutor.java:636
run
Thread.java:764

**Comment by FibreFoX** [comment]
Same problem on Windows too.

**Comment by FibreFoX** [comment]
@109171650 I found this while searching in the closed issues:
https://github.com/facebook/react-native/issues/21584#issuecomment-428048129

```
react-native start --reset-cache
```

**Comment by Yangzhi1997** [comment]
it's working, thanks

**Comment by sryze** [comment]
Using `--reset-cache` didn't help in my case, WIndows 10 x64, react-native 0.57.2.

```

  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
      Memory: 6.06 GB / 15.94 GB
    Binaries:
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338
```

**Comment by dulmandakh** [comment]
could you please upgrade to React Native 0.59 and check if the issue still persists.
