### ISSUE TITLE
react-native 5.7  macOS 10.13.6

### ISSUE THREAD

**Issue by lidiwen** [facebook/react-native#21635]
** BUILD FAILED **

The following build commands failed:

        Analyze /Users/lidiwen/Desktop/myapp/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.c normal x86_64
        Analyze /Users/lidiwen/Desktop/myapp/node_modules/react-native/ReactCommon/yoga/yoga/YGNodeList.c normal x86_64
(2 failures)

Installing build/Build/Products/Debug-iphonesimulator/myapp.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/myapp.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by sw-tt-jigneshkumarchitaliya** [comment]
same issue
