### ISSUE TITLE
Unable to resolve ReactNativeART.js

### ISSUE THREAD

**Issue by mameya007** [facebook/react-native#21637]
![annotation](https://user-images.githubusercontent.com/22181661/46725934-29d70f00-cc75-11e8-8104-d2c58b3122c1.png)

## Environment
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 2.53 GB / 11.89 GB
    Binaries:
      Yarn: 1.9.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
      Watchman: 4.9.4 - E:\Downloads\Compressed\watchman\watchman.EXE
    IDEs:
      Android Studio: Version  3.1.0.0 AI-173.4720617
##Package
{
  "name": "Chat",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "firebase": "^5.5.3",
    "react": "^16.5.2",
    "react-native": "0.57.2",
    "react-native-gifted-chat": "^0.4.3",
    "react-navigation": "^2.17.0"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.48.0",
    "react-test-renderer": "16.5.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
## Description
i am just using firebase and react-native-gifted-chat , when i try to build that error comes any solution please ?

**Comment by flowkraD** [comment]
I faced this problem too with react-native 0.57.2
You can downgrade to 0.52.1 and everything works like a charm or you can follow [this](https://github.com/invertase/react-native-firebase/issues/278#issuecomment-334951055)

**Comment by mameya007** [comment]
> I faced this problem too with react-native 0.57.2
> You can downgrade to 0.52.1 and everything works like a charm or you can follow [this](https://github.com/invertase/react-native-firebase/issues/278#issuecomment-334951055)

![annotation](https://user-images.githubusercontent.com/22181661/46738387-f48ee900-cc95-11e8-9021-48c7d3221119.png)
i got this error this time :'(

**Comment by flowkraD** [comment]
IS this after downgrading? Or did you follow the instruction to fix the reactnativeART.js error?

**Comment by flowkraD** [comment]
Issue #21490 deals with the error you are facing currently. If you are on 57.2, [this  solution in comment](https://github.com/facebook/react-native/issues/21490#issuecomment-427240356) seems to work for most but if you still face any errors it's highly recommend to go back to 57.1. 57.1 may throw errors with Babel runtime but that can be fixed by running `npm install --save @babel/runtime` and you would be good to go

**Comment by kelset** [comment]
Ty @flowkraD for taking care of this, closing given that there has been no further activity.
