### ISSUE TITLE
React Native WebView Cross origin requests are only supported for protocol schemes: http, data, chrome, https

### ISSUE THREAD

**Issue by Shan7anu** [facebook/react-native#21641]
We're trying to load SPA app with Angular JS and HTMl in **Android React Native WebView.** The solution is working fine with Dev server but when we tried to load it in debug and release build it throws following error. We have debugged it in chrome and found that all the resources are loading except the html files. Only Index.html file is getting loaded.

Error in console:

```
Failed to load file:///android_asset/template.html: 
Cross origin requests are only supported for protocol schemes: http, data, chrome, https.
```

We are loading local html file in RN WebView:
```
<WebView 
  ref="webview"
  scalesPageToFit={true} 
  source={{uri: 'file:///android_asset/www/index.html'}}
  javaScriptEnabled={true}
  domStorageEnabled={true}
  nativeConfig={{props: {webContentsDebuggingEnabled: true}}}
  setAllowFileAccessFromFileURLs={true}
  setAllowUniversalAccessFromFileURLs={true}
 /> 
```

We have tried to change the **ReactWebViewManager.java** under this path

**MyReactProjectName\node_modules\react-native\ReactAndroid\src\main\java\com\facebook\react\views\webview\ReactWebViewManager.java** we made following changes:

```
settings.setDomStorageEnabled(true);

settings.setAllowFileAccess(true);
settings.setAllowContentAccess(true);
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN) {
  settings.setAllowFileAccessFromFileURLs(true);
  setAllowUniversalAccessFromFileURLs(webView, true);
}
```
Tried the solution as explained here, still not able to load the required HTML file.

**Is there any way to change ReactWebViewManager.java for local file access as RN WebView is not able to locate the local HTML file and throwing CORS Error??**

React Native: 0.57

**Comment by notlose** [comment]
@Shan7anu did you found any solution for this? i am facing the same problem

**Comment by Shan7anu** [comment]
> @Shan7anu did you found any solution for this? i am facing the same problem

@notlose Duplicate of #21642
