### ISSUE TITLE
[SegmentedControlIOS] segment tap doesn't work, when using it as stickyHeaderIndices in ScrollView

### ISSUE THREAD

**Issue by cendekia** [facebook/react-native#2166]
The code like so:
```
...
<ScrollView stickyHeaderIndices={[0]}>
    <View style={styles.someStyle}>
	 <SegmentedControlIOS tintColor={'#4A96AD'} values={['One', 'Two', 'Three', 'Four']} selectedIndex={0} />
    </View>
</ScrollView>
...
```

the segment tap doesn't work when i warp it with View, but when i remove the View, it's working fine.

Any solutions?

**Comment by ide** [comment]
Touch events in sticky headers currently don't work in general. Sorry I don't have a suggested fix for you but you're not doing anything wrong in your code.

**Comment by cendekia** [comment]
I see, so currently there is no way to fix this bug.
And for the time being i will use TouchableWithoutFeedback (and View in it) as a fake tab on top of SegmentedControlIOS, so i could put style (i.e padding dan border).

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/segmentedcontrolios-segment-tap-doesnt-work-when-using-it-as-stickyheaderindices-in-scrollview
