### ISSUE TITLE
[XMLHttpRequest] Exception thrown while invoking sendRequest on target RCTNetworking with params

### ISSUE THREAD

**Issue by venkysetty** [facebook/react-native#2167]
I am using XMLHttpRequest in my RN app to send REST request.
This is roughly the code:

var httpReq = new XMLHttpRequest();
httpReq.open(method, Url, true);

// set headers
httpReq.setRequestHeader(...);

httpReq.send(body);

Above code is wrapped in a function. 
Issue is that it works for the first call. For any subsequent calls to the same function, i hit an exception below:

[error][tid:com.facebook.React.RCTNetworkingQueue][RCTBatchedBridge.m:662] Exception thrown while invoking sendRequest on target RCTNetworking with params (
        {
        data = "<null>";
        headers =         {
            hdr1 =             (
                "test"
            );
        };
        incrementalUpdates = 0;
        method = GET;
        url = "https://testservice.com/v1/users?p1=test";
    },
    21
): -[__NSCFArray length]: unrecognized selector sent to instance 0x7feb2aa8cf20

My thinking is that it is due to some older reference to react native object for XMLHttpRequest. Is there way to cleanup react native object to workaround this issue?

**Comment by ide** [comment]
@venkysetty - to clarify, you are calling xhr.send() twice with the same xhr object? If so this might be intended behavior (though it should gracefully throw a JS error or print an error instead of crashing of course).

cc @nicklockwood

**Comment by venkysetty** [comment]
@ide - Thanks, I am calling send only once on an allocated xhr object. I am hitting exception if I allocate a new xhr object and call send on that (using the same function for subsequent request).

**Comment by venkysetty** [comment]
I changed my function to use fetch which seems to be working fine. I will leave issue open as XHR issue is still valid.

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/xmlhttprequest-exception-thrown-while-invoking-sendrequest-on-target-rctnetworking-with-params

**Comment by eshwartm** [comment]
Happening in relation to integrating `react-native-code-push`.
