### ISSUE TITLE
A wierd question about ES6

### ISSUE THREAD

**Issue by guodong000** [facebook/react-native#2171]
I was using `String.fromCodePoint` and `codePointAt` ES6 methods to build my app. 
It's functional when testing on the simulator.
But these two methods will be undefined when I test on the device, is this a weird bug or something?

**Comment by jaygarcia** [comment]
@guodong000 , try modifying appDelegate.m to point to your mac's IP address in stead of 'localhost', so that it load the bundled JSX dynamically.  Does it still fail then?

I'm asking because this is a step to isolate the problem to the minified bundled.

**Comment by alinz** [comment]
One other thing to add to @jaygarcia solution is using your computer name, which works pretty well.

for example, instead of typing your computer ip, you use your computer name. In my case I changed the `appDelegate.m` to point to `ali.local`.

**Comment by ide** [comment]
Do you have the same version of iOS?
