### ISSUE TITLE
Can't launch iOS simulator with WebStorm IDE

### ISSUE THREAD

**Issue by Joyreece** [facebook/react-native#21716]
- [*] Review the documentation: https://facebook.github.io/react-native
  - [*] Search for existing issues: https://github.com/facebook/react-native/issues
  - [*] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
  React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 93.62 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.6.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728
      react-native: ^0.57.4 => 0.57.4
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description
WebStorm could launch Metro Bundler and iOS simulator correctly In React Native version 0.56.

But in the 0.57 version with the same configuration, development environment and softwares, it can't launch iOS simulator. (Metro Bundler is correctly launched.)

I have no idea about this issue. Please how to fix this problem?

**Comment by imrepapp** [comment]
Same problem here:

  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
      Memory: 4.37 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.2.1 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
      Android SDK:
        Build Tools: 23.0.1, 25.0.2, 26.0.2, 27.0.3, 28.0.3
        API Levels: 23, 26, 27, 28
    IDEs:
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: 0.57.2 => 0.57.2 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      svg-to-react-native-cli: 0.0.3

**Comment by Joyreece** [comment]
so... what should i do ?

**Comment by Annihil** [comment]
Same issue, WebStorm starts the metro bundler but does not execute the `run-ios` command in parallel

**Comment by imrepapp** [comment]
With RN 0.56.x it's working like a charm.
Workaround for 0.57.x: remove "Start React Native Bundler" from before launch section in the configuration editor and start RNB manual in a Terminal window.

**Comment by rodrigoelp** [comment]
I am going to guess the issue in here is the introduction of the react native metro bundler as opposed of what was used before that.

I imagine this is an issue that needs to be raised with jetbrains as opposed to facebook.

**Comment by Annihil** [comment]
Unfortunately it is not the reason, RN 0.56 already had the metro bundler...

**Comment by imrepapp** [comment]
The newest EAP version of WebStrom is working well.
https://youtrack.jetbrains.com/issue/WEB-34895

**Comment by Annihil** [comment]
@imrepapp Indeed, fixed on WS 2018.3 EAP Build 183.3975.16 with React Native 0.57.4 👍

**Comment by Joyreece** [comment]
> @imrepapp Indeed, fixed on WS 2018.3 EAP Build 183.3975.16 with React Native 0.57.4 👍

I have updated to the latest versions of React Native (v0.57.4) and WebStorm (2018.2.5).
But still can't start normally, so I guess the real thing should be WebStorm 2018.3.
I am full of expectations for WebStorm 2018.3.

**Comment by rodrigoelp** [comment]
If this issue is not related to react native, it should be closed as the facebook team will have little to do here. Instead, this feedback should be directed to jetbrains so they can fix the environment.

**Comment by Joyreece** [comment]
> If this issue is not related to react native, it should be closed as the facebook team will have little to do here. Instead, this feedback should be directed to jetbrains so they can fix the environment.

However, 0.56 and 0.57 have different results in the same WebStorm environment.
I don’t know why.

**Comment by Joyreece** [comment]
it works well with WebStorm 2018.3.
