### ISSUE TITLE
[View] onLayout not called in reused view

### ISSUE THREAD

**Issue by isair** [facebook/react-native#2172]
I have conditional rendering in one of my components, it roughly works like the following. (My real component is much more complicated and only a small part of the view hierarchy gets swapped with something else.)

```js
render() {
  return (this.props.showA ? this._renderA() : this._renderB());
}
```

The top view returned by renderA and renderB are very similar, but the one returned by renderA has onLayout defined and the other does not. If renderB gets called first and then renderA, the onLayout handler never gets called. If I simply comment out the mechanism and return renderA() directly, the onLayout handler is called. I have simply assigned the same onLayout handler to the view returned by renderB as well as a workaround; I believe this to be a reuse issue.

Using react-native 0.8.0

**Comment by ide** [comment]
If you put key="a" and "b" on your components that will tell React not to reuse them. Does that fix your issue?

**Comment by isair** [comment]
Removed my workaround and added key properties to both views; yes, it does make the onLayout handler get called properly.
