### ISSUE TITLE
[0.57.2][ANDROID] Class property was missed on the UI Automator Viewer

### ISSUE THREAD

**Issue by aleksey89** [facebook/react-native#21725]
## Environment
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
      Memory: 123.66 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.3 - /usr/local/bin/node
      Yarn: 1.5.1 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
    IDEs:
      Android Studio: 3.1 AI-173.4697961
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: 0.57.2 => 0.57.2 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

## Description
Initialize project with react-native init. Property 'class' was missed for all react-native component like View, Text etc. We use this property in scope of end to end testing with Appium.

## Reproducible Demo
![2018-10-11 15 06 31](https://user-images.githubusercontent.com/12998236/46803750-7f8ce380-cd69-11e8-8354-1df0e318ba4f.png)

**Comment by ValentinBlokhin** [comment]
Same issue here, do you have a workaround?

**Comment by alexeyrakitskywork** [comment]
We found that due to this issue Appium is crashed when trying to use xpath navigation. Also this bug affects tree view in Android

**Comment by aleksey89** [comment]
@ValentinBlokhin Nope, any idea..

**Comment by neerajkumar-lad** [comment]
Same issue I am also facing..

**Comment by aleksey89** [comment]
Fixed for me in react-native 0.57.4 with react 16.6.0-alpha.8af6728

**Comment by pilsy** [comment]
https://github.com/appium/appium-uiautomator2-server/pull/202#issuecomment-434554162

**Comment by Srinija25** [comment]
@aleksey89  Hi I am working on react native version 0.57.1 all the class property values are missing. I want to confirm after upgrading to react-native version to 0.57.4 is the XPath variables working? Is the missing class property class value displaying again?
