### ISSUE TITLE
java.lang.String cannot be cast to java.lang.Boolean

### ISSUE THREAD

**Issue by Dofff** [facebook/react-native#21723]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
react 16.5.0
react-native 0.57.2

## Description
error occured
java.lang.String cannot be cast to java.lang.Boolean

ReadableNativeArray.java:104

 Please how to fix this problem?

![image](https://user-images.githubusercontent.com/26613612/46800061-7c0d5280-cd91-11e8-9fc5-d985381149f7.png)

**Comment by MortiTotti** [comment]
I have the same issue. I made a react-native application using `"react-native init"`, first run was successful, but whenever I wanted to put a button I received the same error.

### Package.json
 ```
 "dependencies": {
    "react": "16.6.0-alpha.8af6728",
    "react-native": "0.57.3"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.48.1",
    "react-test-renderer": "16.6.0-alpha.8af6728"
  },
```

### React Native Environment Info:
    System:
      OS: Windows 10
      CPU: x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
      Memory: 1.33 GB / 7.87 GB
    Binaries:
      Yarn: 1.6.0 - C:\Users\morteza.taghdisi\AppData\Roaming\npm\yarn.CMD
      npm: 6.0.1 - C:\Program Files\nodejs\npm.CMD

**Comment by MickeyMouse623** [comment]
React Native Environment Info:
    System:
      OS: Windows 10
      CPU: x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
      Memory: 2.31 GB / 7.64 GB
    Binaries:
      Yarn: 1.7.0 - C:\Users\admin\AppData\Roaming\npm\yarn.CMD
      npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD

**Comment by MickeyMouse623** [comment]
我也出现了这个错误
![image](https://user-images.githubusercontent.com/18524460/47268482-42ec9380-d584-11e8-94f2-2bd9ffd0fa2e.png)
