### ISSUE TITLE
[TextInput] paddingVertical not working in multiline mode

### ISSUE THREAD

**Issue by magrinj** [facebook/react-native#21720]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment

  React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
      Memory: 164.91 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.10.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0
      react-native: 0.57.2 => 0.57.2

## Description
Just create a `TextInput` and apply  a `paddingVertical` in style, in single line mode everything work as expected, but in multiline mode the padding doesn't works with the key `paddingVertical`, if I manually specify `paddingTop` and `paddingBottom` that seems to fix the problem.

**Comment by outaTiME** [comment]
Guys, any update with this issue ? thanks !!!

**Comment by godness84** [comment]
> I'm running 0.60.4 and paddingTop isn't working for me, when the TextInput is multiline

@chrissnape It seems that using `paddingTop` and `paddingBottom` instead of `paddingVertical` it works!
