### ISSUE TITLE
Text component cuts part of the text if fontWeight bold is used

### ISSUE THREAD

**Issue by vitorreis** [facebook/react-native#21729]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.5
      CPU: x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
      Memory: 514.83 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.9.0 - ~/.nvm/versions/node/v8.9.0/bin/node
      npm: 6.4.1 - ~/.nvm/versions/node/v8.9.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0
      react-native: 0.57.2 => 0.57.2
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
```

## Description
In some devices when using a <Text> component with the syle `fontWeight: 'bold'` **it removes the last word** of the content of the text. My guess is that it's related with the latest android version, I could test and reproduce this bug in the OnePlus 6 device.

See how the hello world app renders with/without the font style bold.

Before adding bold style to text
![screenshot_20181011-170135](https://user-images.githubusercontent.com/674229/46814170-75beac80-cd78-11e8-9f75-4c0c30a47ed7.jpg)
After adding bold style to text
![screenshot_20181011-170110](https://user-images.githubusercontent.com/674229/46814186-7b1bf700-cd78-11e8-83b5-79d430c11cd2.jpg)

## Reproducible Demo
```
1. react-native init bug 
2. Connect an android device OnePlus 6 with latest version of android on the computer
3. Add `fontWeight: 'bold',` to App.js line 45 (instructions styles)
4. Run the app in the device 
```

**Comment by vitorreis** [comment]
Yo, as described this happens to the latest version as well.

**Comment by kunal886496** [comment]
This still exists. Any solution?

**Comment by kunal886496** [comment]
This is the config:

"babylon": "^6.18.0",
    "react": "16.4.1",
    "react-actioncable-provider": "^1.0.3",
    "react-native": "0.57.0",
    "react-native-android-keyboard-adjust": "^1.1.1",
    "react-native-fs": "^2.11.15",
    "react-native-image-picker": "^0.26.10",
    "react-native-image-resizer": "^1.0.0",
    "react-native-keyboard-aware-scrollview": "^2.0.0",
    "react-native-loader": "^1.2.1",
    "react-native-material-design": "^0.3.7",
    "react-native-material-ui": "^1.30.1",
    "react-native-photo-upload": "^1.2.0",
    "react-native-push-notification": "^3.1.1",
    "react-native-sound": "^0.10.9",
    "react-native-vector-icons": "^5.0.0",
    "react-native-websocket": "^1.0.2",
    "react-redux": "^5.0.7",
    "react-router-native": "^4.3.0",
    "redux": "^4.0.0",
    "redux-thunk": "^2.3.0",
    "socket.io-client": "^2.1.1"

**Comment by vitorreis** [comment]
No solution so far, I've workarounded it by removing the font bold style.

**Comment by ps2qwert** [comment]
I set the width to solve the problem

**Comment by SanchezQb** [comment]
I also use a OnePlus and I had this issue. A workaround I used is to set fontFamily to 'Roboto'

**Comment by faridhub95** [comment]
I'm using oneplus 3t can confirm, the bug is still there even when using recent react version

**Comment by adititipnis** [comment]
One plus 6t.. same issue.

> I also use a OnePlus and I had this issue. A workaround I used is to set fontFamily to 'Roboto'

This works though.

**Comment by johnvillegas40** [comment]
> One plus 6t.. same issue.
> 
> > I also use a OnePlus and I had this issue. A workaround I used is to set fontFamily to 'Roboto'
> 
> This works though.
> 
> I've seen something similar happen on my Instagram as well! Now I see why...

I am also experiencing this issue. I switched from testing with a Pixel 2 XL to a OnePlus 6T and it broke all of my Text with fontWeight by chopping text off of it.

**Comment by jbrodriguez** [comment]
I've had reports of this issue in my app.

In all the cases, they were using a OnePlus, which comes standard with some font other than Roboto.

Making them set system font to Roboto fixed the issue.

I wonder if the Instagram screen that exhibits this behavior (https://github.com/facebook/react-native/issues/21729#issuecomment-453459081) is built with React Native as well.

**Comment by kunal886496** [comment]
Instagram is just a marketing strategy of my react-native.
I have used flutter now.
And its better.

**Comment by dharmen1901** [comment]
I am facing the same issue when using Unicode mangal Text (Hindi) in Samsung On6 & m30. I am not sure if the problem will be on all phones. I tried in these 2 only.

**Comment by gguidotti** [comment]
I can confirm that this is still happening in latest version of React Native when using OnePlus proprietary font (on OnePlus 6) instead of using Robot. Switching it solved the problem, but this is still something which I believe should be fixed

**Comment by house92** [comment]
Same problem here on OnePlus 6

**Comment by MewX** [comment]
Still having the same issue.

I worked around it by setting `lineHeight`:

```
fontStyle: {
    <your other styles>,
    lineHeight: <your font size> * 1.2,
},
```

**Comment by kunal886496** [comment]
Yes same here

**Comment by kinhhopbi0** [comment]
This still exists.  version 0.60.4

**Comment by gaberoganlingumi** [comment]
does setting `fontWeight: '700'` fix it? Sorry I don't have a OnePlus 6 to test this myself.

**Comment by Biplovkumar** [comment]
> Still having the same issue.
> 
> I worked around it by setting `lineHeight`:
> 
> ```
> fontStyle: {
>     <your other styles>,
>     lineHeight: <your font size> * 1.2,
> },
> ```

Thankyou so much sir, you saved my life

**Comment by Sreekesh363** [comment]
> does setting `fontWeight: '700'` fix it? Sorry I don't have a OnePlus 6 to test this myself.

Nope. If you are using fontWeight, it is advised to set fontFamily to 'Roboto' as for different phones which are not using stock Android OS, this can occur.

**Comment by jegathispandi** [comment]
I am facing the same issue in oppo A37 and OnePlus 6. could you please help me to resolve this issue?

**Comment by jegathispandi** [comment]
I am still facing this issue. This issue is react native uses different font. Android uses roberto font for native. but IOS uses different font. If I am using roberto font its working fine. but i need to add 

> const defaultFontFamily = {
> 		...Platform.select({
> 			android: { fontFamily: 'Roboto'}
> 		})
> 	};
> 
> 	const oldRender = Text.render
> 	Text.render = function (...args) {
> 		const origin = oldRender.call(this, ...args);
> 		return React.cloneElement(origin, {
> 			style: [{ fontFamily: 'Roboto'}, origin.props.style]
> 		});
> 	};

**Comment by Zakrevskijj** [comment]
+1 the same issue

**Comment by Harshaou** [comment]
One plus 3T same issue

**Comment by sunny635533** [comment]
@MewX you saved my life too!  it works in my app.

**Comment by priyankapakhale** [comment]
I added `alignSelf: "stretch"` and it worked for me. If you also want the text in the middle then just add `textAlign: "center"` as well.
Hope this helps someone.

**Comment by ritzblogs** [comment]
Checkout https://abodeofmystories.blogspot.com/2020/09/react-native-text-cut-issue.html
Have tested these solutions and it works for me

**Comment by aryankush25** [comment]
I have user `textAlign: 'center'`  `width: '100%'` to the `Text` styles and it worked beautifully.

**Comment by sanjaykmwt94222** [comment]
This issue occurs with the font Oneplus Slate change the font and boom the issue is resolved.

**Comment by 15110011** [comment]
in my case, just remove letterSpacing on Android? or set an int number not a float(if u want to use it) 
ex: letterSpacing: Platform.OS === 'ios' ? 0.5 : 1

**Comment by LorandP** [comment]
This worked for me and I have a OnePlus 7T. Thank you!

> I have added `textAlign: 'center'` & `width: '100%'` to the `Text` styles and it worked beautifully.

**Comment by jvmMachado** [comment]
> I have added `textAlign: 'center'` & `width: '100%'` to the `Text` styles and it worked beautifully.

Same issue Using OnePlus 6. That's the workaround that did the trick.

**Comment by safaiyeh** [comment]
> I have added `textAlign: 'center'` & `width: '100%'` to the `Text` styles and it worked beautifully.

Closing in favor of this work around

**Comment by cglacet** [comment]
Any real solution to this problem? I've noticed using react-native-element's text component doesn't yield the same issue.  Anyone had success with updating to a newer version?

**Comment by emaborsa** [comment]
```
"dependencies": {
    "@react-navigation/native-stack": "^6.9.8",
    "react": "18.2.0",
    "react-native": "0.71.1",
    "react-native-gesture-handler": "^2.9.0",
    "react-native-safe-area-context": "^4.5.0",
    "react-native-screens": "^3.19.0",
    "react-native-svg": "^13.7.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native-community/eslint-config": "^3.0.0",
    "@tsconfig/react-native": "^2.0.2",
    "@types/jest": "^29.2.1",
    "@types/react": "^18.0.24",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.2.1",
    "eslint": "^8.19.0",
    "jest": "^29.2.1",
    "metro-react-native-babel-preset": "0.73.7",
    "prettier": "^2.4.1",
    "react-test-renderer": "18.2.0",
    "typescript": "4.8.4"
  },
```

Still have the problem.

**Comment by Mihai-github** [comment]
+1

**Comment by chavanRk** [comment]
fontWeight : 500,700 is not working 
fontStyle : 'Nunito-Bold' is also not working

**Comment by derekblank** [comment]
Still experiencing this in 2024. I noted that `<Text>` appears to remove the end node of each word.

When there are two or more words in one <Text> element, the last word is removed:
```
<Text>Working Offline</Text>
→ "Working "
```

When there is one word in a <Text> element, the last letter is removed:
```
<Text>Working</Text><Text>Offline</Text>
→ "Workin Offlin"
```

When there are two or more words in one <Text> element and a space is added, the space is removed:
```
<Text>Working Offline </Text>
→ "Working Offline"
```

In our case, adding a space at the end of the string was a suitable workaround.

**Comment by zahid502** [comment]
@ps2qwert thanks,
by setting the width, it's solved.

**Comment by moksaiho** [comment]
> textAlign: 'center'



> Still experiencing this in 2024. I noted that `<Text>` appears to remove the end node of each text string.

This works for some cases for me. In one case: like  const category = ['Course Project ', 'Course Study ', 'ExtraCurricular '];  {category.map((item, index) => {
          return (
              <ButtonText style={styles.buttonText}>{item} </ButtonText>
          );
        })}  you need to add space in both category and behind {item} so that you word will not be chopped off

**Comment by amandaoneal** [comment]
Still experiencing this in 2025. This is pretty ridiculous.

**Comment by agonsgd** [comment]
```
import React from "react";
import { Text, TextProps } from "react-native";
import clsx from "clsx";
import { ReactNode } from "react";

interface StyledTextProps extends TextProps {
  children: ReactNode;
  className?: string;
}

const StyledText: React.FC<StyledTextProps> = ({ children, className, ...props }) => (
  <Text className={clsx("dark:text-white text-black", className)} {...props}>
  {children}{" "} {/* To fix android system wide bold text */}
  </Text>
);

export default StyledText;

```

This is what worked for me, adding a `{" "}`

**Comment by robgraeber** [comment]
Confirm this is still an issue as of RN 0.85.3. The extra space workaround seems to work well.

**Comment by daaugusto** [comment]
+1 This issue should be reopened because the problem still persists.
