### ISSUE TITLE
React Native bundler no longer scans for symlinks in node_modules

### ISSUE THREAD

**Issue by peat-psuwit** [facebook/react-native#21735]
- [ ] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
  React Native Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
      CPU: x64 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
      Memory: 116.35 MB / 3.77 GB
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 8.12.0 - /usr/bin/node
      Yarn: 1.10.1 - /usr/bin/yarn
      npm: 6.4.1 - /usr/bin/npm
    SDKs:
      Android SDK:
        Build Tools: 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 27.0.3, 28.0.2, 28.0.3
        API Levels: 23, 25, 26, 27, 28
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: 0.57.2 => 0.57.2 
```

## Description
In React Native 0.56, the bundler will "Scanning folders for symlinks" in the project's `node_modules` directory. It doesn't do that anymore in React Native 0.57.

## Reproduction procedure
1. Clone peat-psuwit/react-native-symlink-scan-demo@9711207, `cd linkingProject`, and `yarn install`. At this commit, the version of React Native is 0.56.1.
2. Run `react-native start`. Notice that in the very first line it said `Scanning folders for symlinks in /path/to/linkingProject/node_modules (__ms)`.
3. Go to http://localhost:8081/index.bundle?platform=android. Notice that it bundles successfully and there's a string `"I'm linked!"`.
4. Now checkout ~~peat-psuwit/react-native-symlink-scan-demo@4298dcc~~ peat-psuwit/react-native-symlink-scan-demo@8e5bb635969f2cf1184d187f16a36177c7e466f5. Run `yarn install` again. At this commit, the version of React Native is ~~0.57.2~~ 0.60.4 and react-native-community/cli is at 2.8.3.
5. Run `react-native start`. Notice that there isn't `Scanning folders for symlinks ...` anymore.
6. Go to http://localhost:8081/index.bundle?platform=android. The bundling will fail with `Unable to resolve module 'linked-package'`.

## Additional info
I believe this breaks in facebook/react-native@9a77ff5. I'll prepare the PR that fixes this problem.

**Comment by gohopo** [comment]
I also got this problem
react-native  0.55.4 => 0.57.3

**Comment by peat-psuwit** [comment]
Confirmed that this issue still exists in React Native 0.60.4, with react-native-community/cli 2.8.3. I'll migrate both the issue and the proposed PR to the react-native-community/cli repo.

**Comment by peat-psuwit** [comment]
Copied to react-native-community/cli#616
