### ISSUE TITLE
ld: library not found for -lReact while running Archive

### ISSUE THREAD

**Issue by Kamill90** [facebook/react-native#21732]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
  React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 32.00 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.3 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
      Android SDK:
        Build Tools: 23.0.1, 23.0.3, 25.0.0, 25.0.2, 26.0.1, 26.0.2, 27.0.3, 28.0.0, 28.0.1
        API Levels: 22, 23, 25, 26, 28
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.5.0 => 16.5.1
      react-native: ^0.57.2 => 0.57.2

## Description
While developing everything is fine. But while building .ipa I see:
ld: library not found for -lReact and following: 
[
<img width="1196" alt="zrzut ekranu 2018-10-11 o 18 48 14" src="https://user-images.githubusercontent.com/10708582/46820621-f389b480-cd86-11e8-8d31-07c19930209a.png">
](url)

I see that there were one or two topics about that but none is giving the solution. And none of them was referring to Xcode 10 which might make a difference.

https://github.com/facebook/react-native/issues/20502
https://github.com/facebook/react-native/issues/20503

**Comment by 25juan** [comment]
me toot ,how to resovle this problem?

**Comment by TheSavior** [comment]
I believe there have been a bunch of work done in this space for xcode 10 builds and I think this might be resolved with 0.59. I'm going to close this, but feel free to comment if it reproes on 0.59 and we can re-open it. Make sure to include repro steps explaining how someone else can experience this problem.
