### ISSUE TITLE
'placeholderTextColor' is not a valid style property.

### ISSUE THREAD

**Issue by ibiwan** [facebook/react-native#21736]
(Reopening #16761 because I'm having the same issue as he did)

  - [x ] Review the documentation: https://facebook.github.io/react-native
  - [ x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [  x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Environment:
  OS: macOS High Sierra 10.13.6
  Node: 10.8.0
  Yarn: 1.9.4
  npm: 6.2.0
  Watchman: 4.9.0
  Xcode: Xcode 10.0 Build version 10A255
  Android Studio: 3.1 AI-173.4907809

Packages: (wanted => installed)
  react: ^16.5.2 => 16.5.2
  react-native: ~0.55.4 => 0.55.4

## Description
I'm trying to change placeholder text color in TextInput component of react-native. But getting following error:

'placeholderTextColor' is not a valid style property.

My stylesheet code is:

Input: {
        paddingTop: 5,
        paddingBottom: 5,
        paddingLeft: 4,
        paddingRight: 4,
        fontSize: 14,

        color: black,
        placeholderTextColor: hintColor
    }
placeholderTextColor is given in react-native documentation but its not working at my end surprisingly.

## Reproducible Demo

```
StyleSheet.create({
  a: { placeholderTextColor: '#fff' },
});
```

**Comment by ProfessionalAmateur** [comment]
I have this same issue on react-native `0.57.1`
