### ISSUE TITLE
[ScrollView] add defaultZoomScale

### ISSUE THREAD

**Issue by gre** [facebook/react-native#2176]
Hi,

ScrollView is missing a `defaultZoomScale` that would allow to define the initial zoom scale.

The current `zoomScale` prop is controlled and flickers a lot. In my use-case, I just want to be able to define the initial zoom scale, not to control it.

I've also attempted to do this in `componentDidMount`:

```
this.refs.myScrollView.setNativeProps({
  zoomScale: 3
});
```

but this create inconsistency issue on the scrollview: I can basically zoom out of the bounds (it totally breaks the scrollview)

Thanks

**Comment by shaneosullivan** [comment]
I also have this problem - I load an image into a ScrollView that is larger than the viewport, and I want to to start zoomed out, so it fits the screen.  This is simply not possible with the current implementation.

**Comment by gre** [comment]
submitted https://productpains.com/post/react-native/scrollview-defaultzoomscale-prop-feature-request/

**Comment by gre** [comment]
I think we can consider this done with https://github.com/facebook/react-native/commit/963f26cea8b921caba1f98d45e91992d00e96664

`scrollResponderZoomTo(aRect, false)` can be used to initialize the scrollview without animation

**Comment by emrekenci** [comment]
I being able to define the default zoom would be a much more elegant way of doing this. Calling scrollResponderZoomTo method requires measuring the component, actually calling the method somewhere like componentDidMount and calculating the width and height of the scale that you need. People will inevitably lean towards setting the zoomScale property to accomplish this.

**Comment by ericvicenti** [comment]
Having a more elegant solution for this would be great, but this has been stagnant for a while so I think this is relatively low-pri.

**Comment by ahmetabdi** [comment]
Any updates on this?
