### ISSUE TITLE
No matching version found for react-native-elements@1.0.0-beta6

### ISSUE THREAD

**Issue by rareslupascu** [facebook/react-native#21760]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
  React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
      Memory: 33.29 MB / 24.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.12.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.6.0-alpha.8af6728 => 16.5.2
      react-native: ^0.57.3 => 0.57.2
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-rename: 2.2.2

## Description
After upgrading to 0.57.3 i get
No matching version found for react-native-elements@1.0.0-beta6

## Reproducible Demo
react-native init with 0.57.3

**Comment by rareslupascu** [comment]
useful info
[https://github.com/react-native-training/react-native-elements/commit/f01271b5af795b9774c64cae02d4dfa1b68807c4](https://github.com/react-native-training/react-native-elements/commit/f01271b5af795b9774c64cae02d4dfa1b68807c4)

**Comment by rodrigoelp** [comment]
Hi @rareslupascu, I am trying to understand what are you reporting here.

I've just tested a sample app as follows:

```sh
react-native init sampleElements
cd sampleElements
yarn add react-native-elements@beta # this installed beta 7
yarn add react-native-vector-icons
react-native link react-native-vector-icons
react-native run-ios # ignoring the bug preventing the compilation from working as expected
```

In my case, it works without issues.

Here is my project info:

```

  React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i7-4771 CPU @ 3.50GHz
      Memory: 717.82 MB / 24.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
      Yarn: 1.10.1 - ~/.nvm/versions/node/v8.12.0/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
    IDEs:
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728 
      react-native: 0.57.3 => 0.57.3 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

I am going to hazard to guess your upgrade wasn't successful or your node_modules have changed.

**Comment by rodrigoelp** [comment]
Based on @kaankotan comment I think this issue not related to react native.
