### ISSUE TITLE
Unable to make 3rd party modules / plugins use local forked version of React Native

### ISSUE THREAD

**Issue by MarkOSullivan94** [facebook/react-native#21776]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
      Memory: 4.87 GB / 32.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.12.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
      Android SDK:
        Build Tools: 23.0.1, 27.0.3, 28.0.2
        API Levels: 23, 26, 27, 28
    IDEs:
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728
      react-native: github:MarkOSullivan94/react-native#develop => 0.57.3
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

## Description

Following the steps of the Building React Native from source documentation and I'm stuck on [step 4](https://facebook.github.io/react-native/docs/building-from-source.html#4-making-3rd-party-modules-use-your-fork). 

It looked like everything was working fine until I noticed this in Android Studio

<img width="539" alt="screen shot 2018-10-13 at 22 19 55" src="https://user-images.githubusercontent.com/6950843/46910101-b82de800-cf36-11e8-8767-f9c23a558a6f.png">

Unfortunately this is preventing me from running a local version of React Native so I can test my changes.

My version of React Native can be found here: https://github.com/MarkOSullivan94/react-native/tree/develop

## Reproducible Demo

My project containing the error: https://github.com/MarkOSullivan94/ReactNativeShareExample

Clone the project, install the node modules and then try and run it in Android Studio and you'll see warning issues.

If you use the command `react-native run-android` it'll produce the following error.

` error: cannot find symbol import com.facebook.react.modules.core.PermissionAwareActivity;`

**Comment by gengjiawen** [comment]
Looks like this issue affect this: https://github.com/facebook/react-native/issues/13094.

**Comment by gengjiawen** [comment]
Contain build android aar.

**Comment by MarkOSullivan94** [comment]
Build android aar for the [share example project](https://github.com/MarkOSullivan94/ReactNativeShareExample/)  or my local version of [React Native](https://github.com/MarkOSullivan94/react-native/tree/develop) ? 

What would I do after that?

**Comment by guyca** [comment]
@MarkOSullivan94 Have you followed [this](https://facebook.github.io/react-native/docs/building-from-source#4-making-3rd-party-modules-use-your-fork) step from the documentation?

**Comment by MarkOSullivan94** [comment]
@gengjiawen could you provide a guide for what you want me to do?

**Comment by guyca** [comment]
@MarkOSullivan94 
Try the workaround posted [here](https://github.com/facebook/react-native/issues/11677#issue-198117545), basically it replaces the react native dependency of all third party moduels with your own.

**Comment by gengjiawen** [comment]
@MarkOSullivan94 After `yarn install`,  change `node_modules\react-native-image-crop-picker\android\build.gradle` to
```
dependencies {
    implementation project(':ReactAndroid')
    compile 'com.github.yalantis:ucrop:2.2.2-native'
    compile 'id.zelory:compressor:2.1.0'
}
```

**Comment by gengjiawen** [comment]
You may want to change this in `postinstall` hook in `package.json` for clearity.

**Comment by MarkOSullivan94** [comment]
@gengjiawen just tried your changes and I've some how got the app running again! Thank you!

Red error screens but at least the app's running now.
