### ISSUE TITLE
allowFontScaling is not working on Alert? 

### ISSUE THREAD

**Issue by kiritmodi2702** [facebook/react-native#21773]
Hi,
I want to disable the fontScaling for iOS, Text and TextInput support allowFontScaling, But I want to disable to Alert Text, Description and Button. It's look large after setting large text. There is not any property for alert scaling.

<img width="380" alt="screen shot 2018-10-13 at 9 11 22 pm" src="https://user-images.githubusercontent.com/10494663/46907198-a2b3c080-cf2c-11e8-8ae9-74b9446940e9.png">

**Comment by mazenchami** [comment]
@kiritmodi2702 were you able to solve this issue?

**Comment by ishaq-aym** [comment]
@mazenchami  @kiritmodi2702  did you guys solve this issue ? please comment a workaround

**Comment by mazenchami** [comment]
@ishaq-aym i haven't found a solution yet, short of building your own component which uses `<Text>`

**Comment by kiritmodi2702** [comment]
No Solution found.
