### ISSUE TITLE
getting "Unexpected token {" after updating to 0.57.3

### ISSUE THREAD

**Issue by israelidanny** [facebook/react-native#21777]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
  React Native Environment Info:
    System:
      OS: macOS 10.14.1
      CPU: x64 Intel(R) Core(TM) i7-4771 CPU @ 3.50GHz
      Memory: 50.90 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
      npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728
      react-native: ^0.57.3 => 0.57.3
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

## Description
After updating my project to RN v0.57.3 I'm getting this error. Metro bundler does not indicate that anything is wrong. The exact same codebase worked fine just before the update.

![screen shot 2018-10-14 at 12 16 37](https://user-images.githubusercontent.com/1970424/46914793-04b30b00-cfab-11e8-90c6-45df8f097554.png)

## Reproducible Demo
Update app to RN v0.57.3? I'm not 100% sure.

There is at least one more person who had this issue:
https://github.com/facebook/react-native/issues/21558

@pdaivik

**Comment by israelidanny** [comment]
Updating metro bundler and `react-native-cli` seemed to have cleared up the error a little bit:
![screen shot 2018-10-14 at 13 44 11](https://user-images.githubusercontent.com/1970424/46915676-51044800-cfb7-11e8-8367-b45dabe5728e.png)

**Comment by israelidanny** [comment]
Upon further investigation, this was the issue I encountered:
https://github.com/facebook/react-native/issues/20150

One of the workarounds worked out.

**Comment by RLesser** [comment]
Hey, I'm getting the same error as you were, which of the workarounds did you do that worked? Not sure what is causing this and it's not easy to debug.

**Comment by bmwertman** [comment]
I'm seeing this same error on the latest React-native

 React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: (4) x64 Intel(R) Core(TM) i7-3667U CPU @ 2.00GHz
      Memory: 38.86 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.2 - ~/.nvm/versions/node/v8.11.2/bin/node
      Yarn: 1.6.0 - /usr/local/bin/yarn
      npm: 6.7.0 - ~/.npm-packages/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 25
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.58.6 => 0.58.6 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
