### ISSUE TITLE
Temporary files should be stored in ~/LIbrary/Caches or elsewhere, not ~/.rncache

### ISSUE THREAD

**Issue by sryze** [facebook/react-native#21780]
Why does React Native put downloaded source code archives (e.g. Boost, glog) in `~/.rncache`? I don't want to track down the temporary garbage created by `react-native` next time I need to make more free disk space. 

Please put these files in `~/Library/Caches` or `/tmp` (or some other appropriate directory) on macOS.

**Comment by mcchrish** [comment]
I mean this seems to be a good point, and to not pollute the home directory. Why did you close the issue?

**Comment by sryze** [comment]
Reopened

I don't remember why I closed it, probably looked at the number of already open issues/PRs and thought nobody would care about such a small thing

**Comment by sryze** [comment]
I filled the template but I don't know how to reopen, sorry

**Comment by mcchrish** [comment]
Maybe let's ping @hramos?

**Comment by mcchrish** [comment]
Another suggestion is using `$XDG_CACHE_HOME` based on xdg directories.
