### ISSUE TITLE
I lost the dev menu after ejecting from Expo

### ISSUE THREAD

**Issue by kubaue** [facebook/react-native#21781]
## Environment
  OS: Linux 4.4
  Node: 10.6.0
  Yarn: 1.7.0
  npm: 6.2.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: ~0.55.2 => 0.55.4

## Description
After ejecting from Expo I have lost the ability to open dev menu inside application. I use a real device. Whenever I enter ` adb shell input keyevent 82 `which I believe should prompt the menu, nothing happens. I did not change any configuration on the phone. I'm using Android. I assured that it runs in debug mode. I really need to enable 'debug JS remotely' but I don't know how to do it outside of the dev menu.

Any help is appreciated.

**Comment by radko93** [comment]
Try to shake your device? Unfortunately, I don't think this issue is related to React Native and rather to Expo. So maybe try asking there.
