### ISSUE TITLE
Navigator view seems to have a rather large range for allowing users to "pull down" on the view. 

### ISSUE THREAD

**Issue by jaygarcia** [facebook/react-native#2178]
Is there any way to configure the height (or bounding box dimensions) of the drag area to allow users to pull a view down?  This seems to get in the way for things like list views.

Demo:
![pulldown](https://cloud.githubusercontent.com/assets/180031/8991087/4b9c5d9c-36c4-11e5-98e1-bfc70d90c1f7.gif)

**Comment by ericvicenti** [comment]
Sorry, this API is pretty lame and undocumented. We are currently overhauling the API to configure gestures at the navigator level and use the new Animated API to animate scenes.

The edge touch distance is specified in the scene config:

https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/Navigator/NavigatorSceneConfigs.js#L528

To override it:

````javascript
<Navigator
  configureScene={scene => ({
    ...Navigator.SceneConfigs.FloatFromBottom,
    gestures: {
      pop: {
        ...Navigator.SceneConfigs.FloatFromBottom.gestures.pop,
        edgeHitWidth: 60,
      },
    },
  })}
  ...
/>
```
