### ISSUE TITLE
No such file or directory .../react-native-xcode.sh

### ISSUE THREAD

**Issue by sure1243jupiter** [facebook/react-native#21786]
I am using

## Environment

  React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
      Memory: 36.65 MB / 4.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
    IDEs:
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: 3.3.15 => 3.3.15 
      react: 16.3.0-alpha.1 => 16.3.0-alpha.1 
      react-native: ^0.57.3 => 0.57.3 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description

`/Users/xcodeclub/Library/Developer/Xcode/DerivedData/Lea*****y/Build/Intermediates.noindex/demo.build/Debug-iphonesimulator/demo.build/Script-00DD1BFF1BD5951E006B06BC.sh: line 3: ../node_modules/react-native/scripts/react-native-xcode.sh: No such file or directory`

I am getting this issue and not able to run in iOS but able to run in android
 I have also checked the build phases of my project in Xcode and there 

```
export NODE_BINARY=node
../node_modules/react-native/scripts/react-native-xcode.sh
```

actually the file exists in the given path but when I am building the project it is giving error no such file or directory

 I am not able to understand what the exact issue may be

**Comment by ammoradi** [comment]
@sure1243jupiter how did you solve this problem?

**Comment by diivyu** [comment]
I'm using rn 0.59.1. And this issue still exists in this version.
I have also tried changing 
export NODE_BINARY=node
../node_modules/react-native/scripts/react-native-xcode.sh

to 

export NODE_BINARY=node
../../../node_modules/react-native/scripts/react-native-xcode.sh

but that also not worked for me.
