### ISSUE TITLE
java.lang.boolean cannot be cast to com.facebook.react bridge.readablenativemap 

### ISSUE THREAD

**Issue by vishakha7395** [facebook/react-native#21793]
I am facing this issue after upgrading react native. Can anyone please help?
![screenshot_2018-10-15-12-31-57](https://user-images.githubusercontent.com/35450197/46941723-68ac0100-d089-11e8-99ad-83b2d3e07e9b.png)

**Comment by RevoluPowered** [comment]
Can you provide code sample of the file you're having the issue with?

**Comment by vishakha7395** [comment]
> Can you provide code sample of the file you're having the issue with?

I dont know the file which is causing the problem. I have just upgraded the react native version from 0.45 to 0.57.  Bundle is loaded 100% from the react server and then I get the above red screen error
