### ISSUE TITLE
Bitrise error on xcode-archive

### ISSUE THREAD

**Issue by allmaxgit** [facebook/react-native#21807]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Error in: https://app.bitrise.io

But archive works on my machine:
>React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
      Memory: 1.72 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.3 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.2.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
      Android SDK:
        Build Tools: 23.0.1, 27.0.3, 28.0.2
        API Levels: 23, 25, 26, 27, 28
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728 
      react-native: 0.57.3 => 0.57.3 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description
After update to 0.57.3 we have error:
> Running script 'Bundle React Native code and images'
    the transform cache was reset.
❌  error: File /Users/vagrant/Library/Developer/Xcode/DerivedData/savl-bljozydeolcohtcaxkkpmaoifoej/Build/Intermediates.noindex/ArchiveIntermediates/savl/BuildProductsPath/Release-iphoneos/savl.app/main.jsbundle does not exist. This must be a bug with
Last lines of the Xcode's build log:
The following commands produced analyzer issues:
	AnalyzeShallow Vendors/FLAnimatedImage/FLAnimatedImage/FLAnimatedImage.m normal arm64
	AnalyzeShallow Vendors/libwebp/src/enc/analysis_enc.c normal arm64
	AnalyzeShallow Vendors/FLAnimatedImage/FLAnimatedImage/FLAnimatedImageView.m normal arm64
(3 commands with analyzer issues)
The following build commands failed:
	PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/vagrant/Library/Developer/Xcode/DerivedData/savl-bljozydeolcohtcaxkkpmaoifoej/Build/Intermediates.noindex/ArchiveIntermediates/savl/IntermediateBuildFilesPath/savl.build/Release-iphoneos/Savl\ Dev.build/Script-00DD1BFF1BD5951E006B06BC.sh
(1 failure)
You can find the last couple of lines of Xcode's build log above, but the full log is also available in the raw-xcodebuild-output.log
The log file is stored in $BITRISE_DEPLOY_DIR, and its full path is available in the $BITRISE_XCODE_RAW_RESULT_TEXT_PATH environment variable
(value: /Users/vagrant/deploy/raw-xcodebuild-output.log)
Archive failed, error: exit status 65

I deleted react-native-fast-image but another error popped up (in same place):

> Running script 'Bundle React Native code and images'
    the transform cache was reset.
❌  error: File /Users/vagrant/Library/Developer/Xcode/DerivedData/savl-bljozydeolcohtcaxkkpmaoifoej/Build/Intermediates.noindex/ArchiveIntermediates/savl/BuildProductsPath/Release-iphoneos/savl.app/main.jsbundle does not exist. This must be a bug with
Last lines of the Xcode's build log:
echo 'React Native, please report it here: https://github.com/facebook/react-native/issues'
React Native, please report it here: https://github.com/facebook/react-native/issues
exit 2
** ARCHIVE FAILED **
The following build commands failed:
	PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/vagrant/Library/Developer/Xcode/DerivedData/savl-bljozydeolcohtcaxkkpmaoifoej/Build/Intermediates.noindex/ArchiveIntermediates/savl/IntermediateBuildFilesPath/savl.build/Release-iphoneos/Savl\ Dev.build/Script-00DD1BFF1BD5951E006B06BC.sh
(1 failure)
You can find the last couple of lines of Xcode's build log above, but the full log is also available in the raw-xcodebuild-output.log
The log file is stored in $BITRISE_DEPLOY_DIR, and its full path is available in the $BITRISE_XCODE_RAW_RESULT_TEXT_PATH environment variable
(value: /Users/vagrant/deploy/raw-xcodebuild-output.log)
Archive failed, error: exit status 65

It worked good on 0.55.4

## Reproducible Demo
Init react native 0.57.3 and try to archive in Bitrise with xcode-archive 2.4.15

**Comment by allmaxgit** [comment]
Any ideas how possible to debug it?

**Comment by radko93** [comment]
You should consider asking Bitrise about it, we cannot help you debug third party tool not related to React Native. I'm not sure if you can use just their `xcode-archive` or you need some other dependencies.

**Comment by Jonovono** [comment]
@allmaxgit did you find a solution for this? We are seeing the same thing :(
