### ISSUE TITLE
iOSPushNotification, libRCTPushNotification-tvOS.a not found

### ISSUE THREAD

**Issue by DanKurf** [facebook/react-native#21803]
## Environment
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 85.26 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.9.0 - /usr/local/bin/node
      Yarn: 1.6.0 - /usr/local/bin/yarn
      npm: 5.5.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.1, macOS 10.13, tvOS 11.1, watchOS 4.1
      Android SDK:
        Build Tools: 23.0.1, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 27.0.1, 27.0.3
        API Levels: 23, 25, 26, 27
    IDEs:
      Android Studio: 2.3 AI-162.4069837
      Xcode: 9.1/9B55 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.3.1 => 16.3.1
      react-native: 0.57.0 => 0.57.0
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1

## Description

I have followed all steps in these articles:
https://facebook.github.io/react-native/docs/pushnotificationios
https://facebook.github.io/react-native/docs/linking-libraries-ios#manual-linking

And iOS build of my app throws this error:

clang: error: no such file or directory: '/Users/DanielKurfirst/Desktop/0917/2020-react-native/ios/build/Build/Products/Debug-iphonesimulator/libRCTPushNotification-tvOS.a'

Has anyone else experienced this?

**Comment by dlowder-salesforce** [comment]
You should be linking with `libRCTPushNotification.a`, not `libRCTPushNotification-tvOS.a`.  The second library is only for Apple TV apps.

**Comment by DanKurf** [comment]
@dlowder-salesforce Thank you! That was the culprit.

**Comment by cpojer** [comment]
This issue has been moved to react-native-community/react-native-push-notification-ios#6.

**Comment by LuisBonsembiante** [comment]
this issue still happen whe you try to do a release..any idea?..thanks
