### ISSUE TITLE
android cannot load latest bundle from url with RN 0.57.3

### ISSUE THREAD

**Issue by sunny635533** [facebook/react-native#21811]
## Environment
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.3
    Binaries:
      Node: 10.4.1 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5014246
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react:  16.6.0-alpha.8af6728 
      react-native: 0.57.3 

## Description
i have a native app need to intergrate RN in it. I update RN version to 0.57.3, i cannot load bundle from url when i press Dev's reload button. It didnt load any view. Like this:

![image](https://user-images.githubusercontent.com/4737071/47008452-f4e32480-d16c-11e8-97e9-869456e57c72.png)

Wait a long time, it still didnt show anything.But it can load latest bundle when press R in IOS , only android didnt. I tried to set my host ip in Simulator ,also didnt work.
 In android, i see some log at logcat :

![image](https://user-images.githubusercontent.com/4737071/47134573-d2254d00-d2df-11e8-919a-fc6ae4ddcd4c.png)

my package.json:

![image](https://user-images.githubusercontent.com/4737071/47134726-61cafb80-d2e0-11e8-882e-fe6cfa79bed8.png)
![image](https://user-images.githubusercontent.com/4737071/47134749-6ee7ea80-d2e0-11e8-8ab2-ea6c6cceb2dd.png)

 So I decided to reduce my RN's version to 0.55.4.
All is normal! Android can load bundle from Dev's reload button. I guess the problem only occurs in RN 0.57. I hope to know why I cannot load bundle in android. Please tell me.

**Comment by haipengz** [comment]
Same issue, In Android, it cannot load js bundle from Dev reload button with RN 0.56+, but it works perfectly well with RN 0.55.
My RN version is 0.56.0, now in Android the debug pkg is broken, and I can only package a release pkg to continue development. It has caused a lot of inconvenience.

**Comment by sunny635533** [comment]
@haipengz I tried to "react-native init Demo", android can load js bundle. Demo project is "react": "16.6.0-alpha.8af6728" and  "react-native": "0.57.3", it works perfect!  Now i confuse about the broblem very much. Maybe not related to the RN version.

**Comment by jonatslab** [comment]
[Maybe this issue will help](https://github.com/facebook/react-native/issues/18962)

**Comment by jonatslab** [comment]
[Maybe this issue #18962 can help you. ](https://github.com/facebook/react-native/issues/18962)

**Comment by jonatslab** [comment]
Maybe this issue #18962 can help you.

**Comment by sunny635533** [comment]
@jonatslab it already has "babel-preset-react-native": "4.0.0".

**Comment by grabbou** [comment]
I am glad your issue is resolved @sunny635533. Reproducing brownfield setups (integration into native apps) isn't something we can easily make.
