### ISSUE TITLE
undefined is not a function (evaluting optionalFlags[typeof Symbol === 'function'

### ISSUE THREAD

**Issue by adirzoari** [facebook/react-native#21813]
## Environment
 OS: Windows 10
  Node: 8.11.3
  Yarn: 1.5.1
  npm: 6.3.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: 0.49.3 => 0.49.3

## Description
I worked on my project today, the project worked fine but then I exit from the app and try to run again and I got this error
` undefined is not a function(evaluting 'optionalFlags[typeof Symbol === 'function' ? Symbol.iterator:`

![screenshot_20181016-141038](https://user-images.githubusercontent.com/20258998/47012889-197bd400-d14e-11e8-8e34-c62d57c431b6.png)

I saw many issues with same error, I tried to do some of them and nothing was helped.

**Comment by radko93** [comment]
Please provide repro steps.
