### ISSUE TITLE
when i use Button element from react-native, it dosen't work!

### ISSUE THREAD

**Issue by rosezzz** [facebook/react-native#21821]
my new project is baesd on version @0.57.3 of react-native. when i use Button element, he threw a mistake, i can not resolve.
error:  `java.lang.String cannot be cast to com.facebook.react.uimanager.AccessibilityDelegateUtil$AccessibilityRole`

**Comment by iamgilwell** [comment]
This solved it 
https://stackoverflow.com/questions/52784633/i-have-some-error-when-add-button-to-my-react-native-app
Yeah, it's a bug in react-native 0.57.3 but react-native 0.57.2 has its own issues!

So you have to downgrade to react-native 0.57.1 that is a bit more stable!

Do the following things in command prompt in the root directory of your project (these steps install some missed dependencies of this version):

1) delete your node_modules directory (command: rmdir node_modules /s in windows)

2) npm i -S react-native@0.57.1

3) npm add @babel/runtime

4) npm i schedule@0.4.0 --save-dev

5) npm i
