### ISSUE TITLE
ES6 import

### ISSUE THREAD

**Issue by AbrahamAlcaina** [facebook/react-native#2182]
Hi,
 I'm new in reactnative, (Could be it's a noov question), I tried to change the require
```javascript
var React = require('react-native');
````
to this form, ES6 way.
```javascript
import React from 'react-native';
````
and i received an issue syntaxError because it is a reserved word.  
I'm looking for in the documentation but I only found [this](https://github.com/facebook/react-native/blob/master/packager/transformer.js#L21). It is possible to use import/export? How I can activate? 

If it is not possible, what means import in reactnative?

Thanks

**Comment by ide** [comment]
You can turn it on (and other babel options) with a custom .babelrc file in your project root.

**Comment by AbrahamAlcaina** [comment]
@ide Thanks for the kick answer.
Now its working fine.

**Comment by ide** [comment]
@AbrahamAlcaina you're welcome

**Comment by olivierlesnicki** [comment]
How do you configure your babelrc to enable this?

**Comment by AbrahamAlcaina** [comment]
Sorry for the delay, yes it is working fine.

here you have my .babelrc 
```
{
  "retainLines": true,
  "compact": true,
  "comments": false,
  "whitelist": [
    "es6.arrowFunctions",
    "es6.blockScoping",
    "es6.classes",
    "es6.constants",
    "es6.destructuring",
    "es6.forOf",
    "es6.modules",
    "es6.parameters",
    "es6.properties.computed",
    "es6.properties.shorthand",
    "es6.spread",
    "es6.tailCall",
    "es6.templateLiterals",
    "es6.regex.unicode",
    "es6.regex.sticky",
    "es7.asyncFunctions",
    "es7.classProperties",
    "es7.comprehensions",
    "es7.decorators",
    "es7.exponentiationOperator",
    "es7.exportExtensions",
    "es7.functionBind",
    "es7.objectRestSpread",
    "es7.trailingFunctionCommas",
    "regenerator",
    "flow",
    "react",
    "react.displayName"
    ],
  "sourceMaps": false
}
```

If you need an example
