### ISSUE TITLE
Could not find iPhone XXX simulator

### ISSUE THREAD

**Issue by Liqiankun** [facebook/react-native#21824]
## Environment
  OS: macOS 10.14
  Node: 8.11.1
  Yarn: 0.22.0
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: Xcode 10.0 Build version 10A255
  Android Studio: Not Found

Packages: (wanted => installed)
  react: ^16.4.0 => 16.5.2
  react-native: ^0.55.4 => 0.55.4

## Description
When I run `xcrun simctl list devices`
```
== Devices ==
-- iOS 12.0 --
    iPhone 6 (03A77DAB-8642-4E03-95A8-08C57CA9A9C9) (Shutdown) 
    iPhone 8 (13AD8AD9-E701-4A71-A276-F49642976CB2) (Shutdown) 
    iPhone XS (42BB9356-A858-4AA2-BE08-1C87C14D4143) (Shutdown) 
-- tvOS 12.0 --
-- watchOS 5.0 --
-- Unavailable: com.apple.CoreSimulator.SimRuntime.iOS-12-1 --
    iPhone 8 (7119D9FD-3436-4302-A040-BD16DC5C96C5) (Shutdown) (unavailable, runtime profile not found)
    iPhone XS (0B3F56B2-F48F-4970-A7F5-DDB8361CA2EF) (Shutdown) (unavailable, runtime profile not found)
    iPhone XS Max (D35E1F7E-A558-449E-8084-AF420368B3DC) (Shutdown) (unavailable, runtime profile not found)
```
Then run `react-native run-ios --simulator="iPhone 8"`
```
Could not find iPhone 8 simulator
```

**Comment by Liqiankun** [comment]
Issue had been solved on react-native: ^0.57.0 !

**Comment by Liqiankun** [comment]
#19573

**Comment by Liqiankun** [comment]
#19573

**Comment by Liqiankun** [comment]
@react-native-bot Yes, If I update  to v0.57,  then more issues come! That's why I try to fix one issue on the old version!

**Comment by Liqiankun** [comment]
Here is the issue after I updated react naitve!

### Environment
```
      npm: 6.1.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
    IDEs:
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.0-alpha.8af6728  => 16.6.0-alpha.8af6728 
      react-native: ^0.57.3 => 0.57.3 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```
### Package
```
"dependencies": {
    "mobx": "^4.2.1",
    "mobx-react": "^5.2.3",
    "prop-types": "^15.6.1",
    "react": "16.6.0-alpha.8af6728 ",
    "react-native": "^0.57.3",
    "react-native-audio": "^4.1.3",
    "react-native-easy-toast": "^1.1.0",
    "react-native-elements": "^1.0.0-beta5",
    "react-native-image-picker": "^0.26.10",
    "react-native-push-notification": "^3.0.2",
    "react-native-sound": "^0.10.9",
    "react-native-vector-icons": "^4.6.0",
    "react-native-video": "^2.2.0",
    "react-navigation": "^2.3.0",
    "realm": "^2.8.1"
  },
  "devDependencies": {
    "babel-core": "^6.26.3",
    "babel-eslint": "^8.2.3",
    "babel-jest": "^23.0.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.5",
    "babel-preset-react-native": "^4.0.0",
    "babel-preset-react-native-stage-0": "^1.0.1",
    "eslint": "^4.19.1",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-react": "^7.8.2",
    "jest": "22.4.3",
    "react-test-renderer": "16.4.0"
  },
  "jest": {
    "preset": "react-native"
  }
```

### Issue
```
** BUILD SUCCEEDED **



The following commands produced analyzer issues:
	Analyze Base/RCTModuleMethod.mm normal x86_64
	Analyze RCTNetInfo.m normal x86_64
(2 commands with analyzer issues)
```
```
Looking for JS files in
   /Users/old_david/Desktop/NIM_ReactNative_Demo-master 

Loading dependency graph, done.
error: bundling failed: Error: The 'decorators' plugin requires a 'decoratorsBeforeExport' option, whose value must be a boolean. If you are migrating from Babylon/Babel 6 or want to use the old decorators proposal, you should use the 'decorators-legacy' plugin instead of 'decorators'.
```

**Comment by Liqiankun** [comment]
Help !!!!

**Comment by rsispal** [comment]
I just started a new project and I am also now experiencing the "Could not find iPad Pro (10.5-inch) simulator" error when trying to launch the 10.5 Inch iPad Pro simulator (and other devices) via `react-native run-ios --simulator 'iPad Pro (10.5-inch)' --configuration Debug` - a command which worked in RN 0.55 in other projects.

**Available simulators** (via `xcrun simctl list devices`):
```
== Devices ==
-- iOS 12.0 --
    iPhone 5s (2EA5629A-47F7-4860-8421-F3426EA90AFF) (Shutdown)
    iPhone 6 (E9C3982A-233E-4D6B-9786-EDD71860225F) (Shutdown)
    iPhone 6 Plus (4165F0E5-2755-4814-9061-056D8B0C4775) (Shutdown)
    iPhone 6s (4AAF6165-8C7B-4B5F-B599-BBDD17A9D98B) (Shutdown)
    iPhone 6s Plus (0097D065-CFFD-4089-B3AE-386C5FEA784C) (Shutdown)
    iPhone 7 (991A26FC-B08C-450F-A83A-89B3C6BA4293) (Shutdown)
    iPhone 7 Plus (C4C6FD4B-5480-44A6-A3B9-6877AA2F6718) (Shutdown)
    iPhone 8 (A414F90E-09DD-4C63-A85E-E0E679478D60) (Shutdown)
    iPhone 8 Plus (19EE78EA-EEE8-44BC-AD52-3F2E46BEDFC7) (Shutdown)
    iPhone SE (BC7E60FC-14D7-41A9-B655-4F67193DF008) (Shutdown)
    iPhone X (2AB9351C-FAF2-4006-A4A7-5D2CF447EF57) (Shutdown)
    iPhone XR (CC9B74AE-5AEC-4B87-B5FD-F7C1097454E6) (Shutdown)
    iPhone XS (1578EC06-1A28-4EF1-8FCC-AAE2FC5B9CC2) (Shutdown)
    iPhone XS Max (2297A78E-B800-48B1-90D7-A8B2D8499BE7) (Shutdown)
    iPad Air (712C297F-A990-4D7D-B608-5FF219486E36) (Shutdown)
    iPad Air 2 (3B2931B2-7DD9-46BC-9EE1-8FB5EBCDA014) (Shutdown)
    iPad (5th generation) (42336220-39DB-410C-B1F7-C9C0E1C87DB9) (Shutdown)
    iPad Pro (9.7-inch) (5B087869-BD44-465D-969B-F0FE430B049B) (Shutdown)
    iPad Pro (12.9-inch) (A475475C-E65F-465A-9391-E266D847B837) (Shutdown)
    iPad Pro (12.9-inch) (2nd generation) (953946B7-23A6-4C7A-BEF6-E2E36E937977) (Shutdown)
    iPad Pro (10.5-inch) (AF21FFCE-2CD4-4A55-ADDA-451ED91C3F0F) (Shutdown)
    iPad (6th generation) (7497B372-2B6F-4DD4-BD5B-72A410CA0003) (Shutdown)
-- tvOS 12.0 --
    Apple TV (53427572-C80E-4632-B60B-931021397939) (Shutdown)
    Apple TV 4K (5312C2D4-0152-4EF8-86C0-64699037C491) (Shutdown)
    Apple TV 4K (at 1080p) (68279ACA-BC34-4AAD-ADCD-934B891015E1) (Shutdown)
-- watchOS 5.0 --
    Apple Watch Series 2 - 38mm (73D7DB22-8016-4B47-A86E-A8A8EEB36387) (Shutdown)
    Apple Watch Series 2 - 42mm (02204887-F212-4134-8867-972F894C4905) (Shutdown)
    Apple Watch Series 3 - 38mm (3396FC6A-E6C8-4C1D-80DA-80A44A66EDAD) (Shutdown)
    Apple Watch Series 3 - 42mm (1F0120FB-A1FF-4522-9DE3-73C254A95CBD) (Shutdown)
    Apple Watch Series 4 - 40mm (25C0DD3A-6900-4E55-A7E1-5A19D00C2D3A) (Shutdown)
    Apple Watch Series 4 - 44mm (A86B5903-55F8-4C37-9B15-170BCCFCB375) (Shutdown)
```

**React Native Info:**
```
  React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
      Memory: 3.59 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.0.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
    IDEs:
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728 
      react-native: 0.57.4 => 0.57.4 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

**Comment by kelset** [comment]
@Liqiankun have you tried doing what the error says
> bundling failed: Error: The 'decorators' plugin requires a 'decoratorsBeforeExport' option, whose value must be a boolean. If you are migrating from Babylon/Babel 6 or want to use the old decorators proposal, you should use the 'decorators-legacy' plugin instead of 'decorators'.

@rsispal probably the string precisely identifying that model is different from the one you wrote.

**Comment by rsispal** [comment]
@kelset The exact command works in a different project running RN 0.55 so it appears there's potentially something in the newer version(s) (using 0.57.4) causing this issue. 

Below is the error I get from npm:

```
Error: Could not find iPad Pro (10.5-inch) simulator
    at resolve (/xxx/node_modules/react-native/local-cli/runIOS/runIOS.js:149:
13)
    at new Promise (<anonymous>)
    at runOnSimulator (/xxx/node_modules/react-native/local-cli/runIOS/runIOS.
js:134:10)
    at Object.runIOS [as func] (/xxx/node_modules/react-native/local-cli/runIO
S/runIOS.js:106:12)
    at Promise.resolve.then (/xxx/node_modules/react-native/local-cli/cliEntry
.js:117:22)
```

**Comment by leotm** [comment]
For anywhere else stumbling here like I did, if the above didn't work, https://github.com/facebook/react-native/issues/21498#issuecomment-476621627 may.

**Comment by ialmoqren** [comment]
Also, note that some [simulators' names have changed](https://github.com/facebook/react-native/issues/21498#issuecomment-478328230)

**Comment by erhanbicer** [comment]
worked for me https://github.com/facebook/react-native/issues/21498#issuecomment-479896601

**Comment by devnasim** [comment]
i am just updated react-native latest version "0.58.6"

**Comment by ahmadshahrour951** [comment]
As @ialmoqren mentioned, the naming convention changed for Xcode simulators.

For example, in my package.json I have a script written like this `"ios_big": "react-native run-ios --simulator='iPhone Xs Max'",`. Now I changed it to this: `"ios_big": "react-native run-ios --simulator='iPhone XS Max'",`

**Notice it changed from `iPhone Xs Max` to `iPhone XS Max`.**

If all fails, run it through Xcode directly at the very top of the GUI.
<img width="379" alt="Screen Shot 2019-04-12 at 5 47 10 PM" src="https://user-images.githubusercontent.com/33921028/56041969-0e93ac00-5d4b-11e9-9773-6526935497c0.png">

Pick your iPhone simulator and press the play button.
<img width="352" alt="Screen Shot 2019-04-12 at 5 47 25 PM" src="https://user-images.githubusercontent.com/33921028/56042004-1eab8b80-5d4b-11e9-838b-19c821e7cc8b.png">

**Comment by memory125** [comment]
The simulator error as the following screenshot showed.
![image](https://user-images.githubusercontent.com/10826147/58456089-d65af800-8155-11e9-99e7-ef548cb635b4.png)

**Comment by memory125** [comment]
The simulator error as the following screenshot showed.
![image](https://user-images.githubusercontent.com/10826147/58456256-4bc6c880-8156-11e9-9825-60ba377f92cd.png)

**Comment by Tranxuanvu** [comment]
@memory125 
Try this https://github.com/facebook/react-native/issues/23282#issuecomment-460623632

**Comment by memory125** [comment]
> @memory125
> Try this [#23282 (comment)](https://github.com/facebook/react-native/issues/23282#issuecomment-460623632)

Thanks, I'll try.

**Comment by Liqiankun** [comment]
After I download Xcode 11 beta, this issue happened again!

**Comment by salmazov** [comment]
> After I downloaded Xcode 11 beta, this issue happened again!

And I have this issue too. How to solve it?

**Comment by d3vhound** [comment]
Yep, downloading and using xcode 11 beta breaks `react-native run-ios`

**Comment by dowatugkins** [comment]
@rsispal fixed mine, even though I only had one iPad Pro (11-inch) in my device output, adding the OS version at the end fixed mine. 'iPad Pro (11-inch) (12.2)'

**Comment by Liqiankun** [comment]
I salved this issue this way.
```
1. npm start
2. Open Xcode, choose simulator and run.
```

**Comment by lukejsimonetti** [comment]
`'iPad Pro (11-inch) (12.2)'`
 adding the OS version matters.

**Comment by widimiras** [comment]
In my problem i just have to kill com.apple.CoreSimulator.CoreSimulatorService
see this [link](https://medium.com/%E5%BD%BC%E5%BE%97%E6%BD%98%E7%9A%84-swift-ios-app-%E9%96%8B%E7%99%BC%E6%95%99%E5%AE%A4/failed-to-find-a-suitable-device-for-the-type-ibsimdevicetypeipad2x-error-handling-b0f85050b415)

**Comment by maitrungduc1410** [comment]
> `'iPad Pro (11-inch) (12.2)'`
> adding the OS version matters.

You just saved my day

**Comment by wanghling** [comment]
I have the same problem.
You can do this ,find this file:   **/node_modules/react-native/local-cli/runIOS/findMatchingSimulator.js**  then adding  
`console.log(version)     console.log(simulator)`,
then you change the
 `    if (!version.startsWith('iOS') && !version.startsWith('tvOS')) {
      continue;
    }    or  simulator.available === 'YES'` 
to the console result. my platform is `
if (!version.startsWith('com.apple.CoreSimulator.SimRuntime.iOS') && !version.startsWith('com.apple.CoreSimulator.SimRuntime.tvOS')) {
      continue;
    } 
if (simulator.isAvailable !== true) {
        continue;
      }` then react-native run-ios
it may be  error for `":CFBundleIdentifier", Does Not Exist`
then `rm -rf node_modules`
`react-native upgrade` this may not need
`yarn install `
