### ISSUE TITLE
[MapView] Error setting property 'annotations' of RCTMap

### ISSUE THREAD

**Issue by keyhui-heha** [facebook/react-native#2183]
using react-native 0.8.0

It works on development realtime render.

However, after i run build production version by command "$ react-native bundle --minify"

I go to the MapView again, i got the error

Error setting property 'annotations' of RCTMap with tag #545: Exception thrown while attempting to set property 'annotations' of                 'RCTMap' with value '(
        {
        latitude = "23.15245630469985";
        longitude = "113.3288000000001";
        subtitle = "\U6797\U548c\U4e1c\U8def26\U53f7\U6d77\U68e0\U9601-2\U697c";
        title = "\U76ca\U5143\U5802";
    }
)': *** -[__NSArrayM insertObject:atIndex:]: object cannot be nil
2015-07-31 15:55:56.901 [error][tid:main][RCTMapManager.m:48] Error setting property 'annotations' of RCTMap with tag #545: RCTMap does not have setter for `annotations` property

![ios simulator screen shot 31 jul 2015 3 59 16 pm](https://cloud.githubusercontent.com/assets/12506046/9003101/96773d1c-379d-11e5-8f7b-398bffb13e32.png)

**Comment by browniefed** [comment]
@keyhui-heha is this still happening with .11-rc?

**Comment by brentvatne** [comment]
You may need to clean your build with ⌘+k in Xcode when you get these types of errors :) Should be working fine now
