### ISSUE TITLE
[Docs] I think it's time to add a showcase for react-native

### ISSUE THREAD

**Issue by soliury** [facebook/react-native#2184]
I think if there should have a showcase for react-native-app in the website.

Now I only know that, groups is power by react-native. The showcase will make more people know the power of react-native, and then they will try.

How do you think?

**Comment by chirag04** [comment]
+1. showcase will definitely improve confidence among the community. 

cc @vjeux @brentvatne

**Comment by vjeux** [comment]
Would be awesome to have 1-3min videos of apps using react native showing all the cool things they do

**Comment by soliury** [comment]
@vjeux yes, it's so cool. But how many people are use react-native. I want to know.

**Comment by chirag04** [comment]
video will be awesome but even just a list would be cool.

for the record, we use it in production: lrnapp.com

**Comment by soliury** [comment]
@chirag04 well done.

**Comment by xcarpentier** [comment]
+1

**Comment by chirag04** [comment]
@vjeux  i can spend some time on it over weekend unless somebody else beats me to it.  I'm planning to have a link next to newsletter and then just a list of images. click on image takes you to the app website in a new tab.

If fb team is having any specific design guideline let me know. A png of such design could help.

**Comment by brentvatne** [comment]
@chirag04 - take your best stab at it and I can clean up to ensure it fits in with the rest of the site :)

**Comment by chirag04** [comment]
Cool. I know what to do over the weekend then ;)

**Comment by vjeux** [comment]
Yeah, feel free to do whatever feels good to you :)
