### ISSUE TITLE
WebView render error

### ISSUE THREAD

**Issue by banli17** [facebook/react-native#21857]
## Environment
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 34.29 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5014246
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0
      react-native: 0.57.2 => 0.57.2
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-create-library: 3.1.2

## Description
```
import React, {Component} from 'react';
import {
    Alert, View, ActivityIndicator, Platform, WebView
} from 'react-native'

export default class CommonWebView extends Component {

    constructor(props) {
        super(props)
    }

    render() {
        return (
            <WebView
                source={{uri: 'https://10010nm.com/netShop/index.jhtml?shop=8427'}}
            />
        )
    }
}
```

## result

the dialog is not display clear. like this 

![image](https://user-images.githubusercontent.com/12556069/47195977-0147c700-d391-11e8-9df6-a84b49283175.png)

but . i use mobile self brower and other brower open link https://10010nm.com/netShop/index.jhtml?shop=8427 , it's below.

![image](https://user-images.githubusercontent.com/12556069/47196013-2805fd80-d391-11e8-81ac-4c61d4e877e2.png)

the dialog is ok.

**Comment by Titozzz** [comment]
React-native Webview component is being extracted to https://github.com/react-native-community/react-native-webview. Please if that bug still exists with the extracted component, open an issue on the other repository, as it will probably be easier to get attention there.

Thank you !
