### ISSUE TITLE
react-native start not using passed --sourceExts

### ISSUE THREAD

**Issue by elyalvarado** [facebook/react-native#21854]
## Environment
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 32.02 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 27.0.3
        API Levels: 27
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0
      react-native: 0.57.0 => 0.57.0

Also tested with the latest react-native version (0.57.3)

## Description
When starting the react-native packager either by using `react-native start --sourceExts e2e.js`, or by directly calling the `local-cli` included with the `react-native` package in `node_modules` the packager is not prioritizing the passed source extension.

## Reproducible Demo
```
react-native init TestProject
cd TestProject
cp App.js App.e2e.js
# Make a visible change in App.e2e.js
react-native start --sourceExts e2e.js
react-native run-ios
# Check to see that the packager is not taking the e2e.js file
```

**Comment by hramos** [comment]
The command line tools have their own repository and issue tracker over at https://github.com/react-native-community/react-native-cli.
