### ISSUE TITLE
ScrollView Horizontal jump to the end on Android 5

### ISSUE THREAD

**Issue by alfacommunication-alessandro** [facebook/react-native#21867]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
  React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz
      Memory: 783.50 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.11.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
      Android SDK:
        Build Tools: 23.0.1, 25.0.2, 26.0.0, 26.0.3, 27.0.3
        API Levels: 22, 23, 25, 26, 27
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: ^3.4.7 => 3.4.11
      react: 16.5.1 => 16.5.1
      react-native: 0.57.2 => 0.57.2
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

## Description
On Android 5.0/5.1, typing on a TextInput styled with textAlign "center" or "right" inside an horizontal ScrollView, make ScrollView scroll to the end.

## Reproducible Demo
Tested with React Native CLI and Expo Client. Reproducible demo [here]( https://snack.expo.io/@ale77dan/react-native-android-5-scroll-horizontal-bug)

**Comment by naomipol** [comment]
@react-native-bot I have verified this issue persist in latest release
Please re-open
