### ISSUE TITLE
[Packager] "Watcher took too long to load" (Mac OS X 10.10.4, RN 0.8 stable)

### ISSUE THREAD

**Issue by KaterMikesch** [facebook/react-native#2186]
Running AwesomeProject (following the steps in the docs) starts the app but shows the following red screen after the initial launch screen:

![ios simulator screen shot 31 07 2015 11 03 39](https://cloud.githubusercontent.com/assets/229389/9004142/cf91475c-3773-11e5-877f-c67286dfe3e1.png)

The packager terminal window shows the following:
```
[10:49:42] <START> fs crawl
[10:50:03] <START> request:/index.ios.bundle
[10:50:03] <START> find dependencies
Error: Watcher took too long to load
Try running `watchman version` from your terminal
https://facebook.github.io/watchman/docs/troubleshooting.html
    at [object Object]._onTimeout (/Users/axel/Projects/AwesomeProject/node_modules/react-native/packager/react-packager/src/FileWatcher/index.js:102:16)
    at Timer.listOnTimeout (timers.js:89:15)
 ERROR  Watcher took too long to load
Try running `watchman version` from your terminal
https://facebook.github.io/watchman/docs/troubleshooting.html
Error: Watcher took too long to load
Try running `watchman version` from your terminal
https://facebook.github.io/watchman/docs/troubleshooting.html
    at [object Object]._onTimeout (/Users/axel/Projects/AwesomeProject/node_modules/react-native/packager/react-packager/src/FileWatcher/index.js:102:16)
    at Timer.listOnTimeout (timers.js:89:15)

See http://facebook.github.io/react-native/docs/troubleshooting.html
for common problems and solutions.
Process terminated. Press <enter> to close the window
```

Watchman has been installed per brew and is version 3.3.0:
```
[axel@Ratz ~/Projects/AwesomeProject] watchman
{
    "error": "invalid command (expected an array with some elements!)",
    "cli_validated": true,
    "version": "3.3.0"
}
```

Tried the proposed solution (http://facebook.github.io/react-native/docs/troubleshooting.html) for this issue:

```
Watchman took too long to load 
Permission settings prevent Watchman from loading. A recent update solves this, get a HEAD install of Watchman if you are experiencing this error.

brew uninstall watchman
brew install --HEAD watchman
```

... but unfortunately to no avail. Same as before. Watchman said:

```
[axel@Ratz ~/Projects/AwesomeProject] watchman
{
    "error": "invalid command (expected an array with some elements!)",
    "cli_validated": true,
    "version": "3.6.0"
}
```

Strange thing is that watchman went kind of amok CPU wise (both old 3.3.0 and master 3.6.0 respectively):

<img width="833" alt="watchmanamok" src="https://cloud.githubusercontent.com/assets/229389/9004135/c39d9dec-3773-11e5-8013-4c26f2d1e407.png">

Any ideas? Thanks for your time!

**Comment by vjeux** [comment]
@amasad any idea what's going on?

**Comment by darkrishabh** [comment]
Try upgrading watchman. That worked for me.

**Comment by jacob-israel-turner** [comment]
@darkrishabh what version fixed it?

**Comment by darkrishabh** [comment]
3.3.0

**Comment by hzhu** [comment]
Hmm, my version of watchman is `3.7.0` but I'm getting the same exact errors. Any ideas?

**Comment by ide** [comment]
Try killing all packager processes (get the pids with `ps a | grep node | grep packager`) and running `watchman shutdown-server`.

**Comment by hzhu** [comment]
Killed all the processes (they end anyways if I close `packager` running on port 8081 tab. Also did `watchman shutdown-server`.

After doing so, (and closing Xcode), rebuilding React `.xcodeproj` still gets me the same error.

**Comment by hzhu** [comment]
I just cloned https://github.com/iSimar/HackerNews-React-Native and got it to work with the same steps.

I just can't seem to get the apps in Examples folder to work.

**Comment by KaterMikesch** [comment]
I updated react-native and still got an error in the packager terminal window.

Looking into ...

    tail /usr/local/Cellar/watchman/3.7.0/var/run/watchman/xxx.log

... revealed the following line:

    2015-08-17T11:56:34,656: [notify /Users/xxx] opendir(/Users/xxx/Library/Saved Application   State/com.adobe.flashplayer.installmanager.savedState) -> Permission denied. We don't know how to handle this.

After deleting the file /Users/xxx/Library/Saved Application   State/com.adobe.flashplayer.installmanager.savedState it worked.

This might be of interest for you guys. Maybe also for the watchman guys?

**Comment by wez** [comment]
FWIW, there's a bug in sane where the error events aren't bubbled up from the underlying watchman client.  I created https://github.com/amasad/sane/pull/55 yesterday for other reasons and found that issue.
I suspect that will help surface problems like these in a more actionable way

**Comment by wez** [comment]
Also: we probably don't do a great job about permission denied errors during crawling in watchman.

**Comment by amasad** [comment]
Sorry for the delay, been out for a while. The next sync the sane version should upgraded to bubble up watchman errors.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/packager-watcher-took-too-long-to-load-mac-os-x-10104-rn-08-stable

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is heavily focused working on performance.
