### ISSUE TITLE
When fontWeight is bold the text cuts SERIOUS BUG

### ISSUE THREAD

**Issue by kunal886496** [facebook/react-native#21869]
This is a very serious issue .
I have tried every solution.
Whatever fontSize i use 2 , 4 or more and the fontWeight property is 'bold' then the text cuts.
I also faced those tracking and register events problem.
Such minor releases can affect our projects and clients badly.

But yeah thanks for all the hard work you people did to create RN.

**Comment by HelloJack0** [comment]
@kunal886496 How to do fix it？

**Comment by kunal886496** [comment]
Just give width to the container containing the text
