### ISSUE TITLE
Webview wordpress Video 

### ISSUE THREAD

**Issue by mnoandh** [facebook/react-native#21873]
- [ ] Review the documentation: https://facebook.github.io/react-native
  - [ ] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Microsoft Windows [Version 6.1.7601]

Environment:
  OS:  Windows 7
  Node:  8.11.1
  Yarn:  1.9.4
  npm:  6.2.0
  Watchman:  Not Found
Error: unable to print environment info
{ Error: not found: xcodebuild
    at getNotFoundError (C:\Users\KL\expo\node_modules\which\which.js:13:12)
    at Function.whichSync [as sync] (C:\Users\KL\expo\node_modules\which\which.j
s:134:9)
    at getXcodeVersion (C:\Users\KL\expo\node_modules\envinfo\envinfo.js:17:25)
    at Object.module.exports.print (C:\Users\KL\expo\node_modules\envinfo\envinf
o.js:136:28)
    at Object.info (C:/Users/KL/expo/node_modules/react-native/local-cli/info/in
fo.js:17:13)
    at Promise.resolve.then (C:/Users/KL/expo/node_modules/react-native/local-cl
i/cliEntry.js:115:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16) code: 'ENOENT' }

## Description
Hi Guys!!
I am quite new in react native as well as the programming. I am using expo and I am trying to read data from WordPress. but the problem appeared when the post contains a video. .

the video is running well but the video size showed inside the is bigger than the screen size.
I have tried scalesPageToFit={true}, However, it did not work for me.
Is there any way to solve this issue?

![1464840430](https://user-images.githubusercontent.com/44123373/47259666-79240780-d4df-11e8-81ae-b662c142dc43.jpg)

## Reproducible Demo

    <View>
      <PostImage post={post} style={styles.featuredImage} showEmpty />
      <Text style={styles.title}>{entities.decode(post.title.rendered)}</Text>
      <PostMeta style={styles.meta} post={post} />
            <Container>
      <Content contentContainerStyle={{ flex: 1, height:350, width:408 }}>
    

                        <WebView 
                        scrollEnabled={false}
                    
                            ref={webview => { this.webview = webview; }}
                            injectedJavaScript={javascript}
                            javaScriptEnabled={true}
                            javaScriptEnabledAndroid={true}
                            onMessage={this._receivedMessage} 
                            scalesPageToFit={true}
                            allowsInlineMediaPlayback={true}
                            decelerationRate="normal"
                            style={styles.content}
                            automaticallyAdjustContentInsets={false}
                            domStorageEnabled={true}
                            startInLoadingState={true}
                            source={{html: HTML}} 

                             />

       
   
      </Content>
    </Container>
    </View>

**Comment by Titozzz** [comment]
React-native Webview component is being extracted to https://github.com/react-native-community/react-native-webview. Please if that bug still exists with the extracted component, open an issue on the other repository, as it will probably be easier to get attention there.

Thank you !

**Comment by mnoandh** [comment]
this one says: "Note: React Native WebView is not currently supported by Expo unless you "eject"."
and I am using expo @
