### ISSUE TITLE
How to make an effect like mask layer

### ISSUE THREAD

**Issue by xonyen** [facebook/react-native#2187]
Like the image bellow shows
![2 -](https://cloud.githubusercontent.com/assets/9267574/9004922/a5673156-37ac-11e5-9c1c-ca2d43dbd402.png)

**Comment by chirag04** [comment]
See if these components can be used

https://github.com/brentvatne/react-native-modal
https://github.com/voronianski/react-native-effects-view
https://github.com/brentvatne/react-native-overlay

Questions like these should be asked in the IRC though:
reactiflux.slack.com/messages/react-native/

**Comment by brentvatne** [comment]
@chirag04's answers should cover it, thanks! Let me know if this doesn't work for you and we can discuss, otherwise closing

**Comment by xonyen** [comment]
I'll have a try first and give you an answer later. Thanks

**Comment by xonyen** [comment]
@chirag04 react-native-modal works good, thank you very much!

**Comment by chirag04** [comment]
:+1:
