### ISSUE TITLE
How to make Background Color at Text like this?

### ISSUE THREAD

**Issue by dominicsavb** [facebook/react-native#21886]
Hi... 

How to make <Text> background like this (screenshot). Background color only at text, and there is a gap between text below.

![whatsapp image 2018-10-22 at 12 32 41](https://user-images.githubusercontent.com/6405946/47278913-c6df6380-d5f6-11e8-814d-70244bde47c0.jpeg)

I already try, and below is the result
![simulator screen shot - iphone x - 2018-10-22 at 12 01 43](https://user-images.githubusercontent.com/6405946/47278918-d8287000-d5f6-11e8-96f7-bcb67ddc5c01.png)

how to make it?
Thank you

**Comment by dulmandakh** [comment]
you can nest Text inside Text to have different styles.

**Comment by dominicsavb** [comment]
I already use nested Text, but same result. background still effect at space character.

> you can nest Text inside Text to have different styles.
