### ISSUE TITLE
'react-native info' unable to print environment info error

### ISSUE THREAD

**Issue by bockc** [facebook/react-native#21882]
## Environment
[skip envinfo]
The problem lies here... Here are the versions checked individually:
OS: Arch Linux 4.18.14-arch1-1-ARCH x86-64
Node: 10.12.0
Yarn: 1.10.1
npm: 6.4.1
Watchman: 4.9.0
Xcode: Not Found
Android Studio: 3.2.1

Packages:
react: 16.6.0-alpha.8af6728
react-native: 0.57.3

## Description
Tried to run 'react-native info' command in bash in order to open another issue and came up with this error

> $react-native info
> Error: unable to print environment info  
> TypeError: Cannot read property '1' of null  
>     at a.run.then.e (/home/godo/projects/o-rizon-mobile/node_modules/envinfo/dist/envinfo.js:1:97255)

## Reproducible Demo
Wether this is in my project or a newly 'react-native init <project>'-ed project, running the command 'react-native info' fails with that error. I am able to run the project on a physical android device though. I looked at the documentation and the existing issues but I could not find something related to it.

**Comment by bockc** [comment]
I don't really know what to do now, so I'm just gonna skip the envinfo

**Comment by rodrigoelp** [comment]
HA! the irony of this issue is flawless. I suggest you to populate the following fields with your data and pop it at the top

```
  React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i7-4771 CPU @ 3.50GHz
      Memory: 5.16 GB / 24.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
      Yarn: 1.10.1 - ~/.nvm/versions/node/v8.12.0/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
    IDEs:
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728 
      react-native: 0.57.4 => 0.57.4 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

**Comment by rodrigoelp** [comment]
Oh wow... I would really recommend you to go into reactiflux or whatever the discord channel is called and raise the issue there, in here is going to be discarded.

**Comment by xgqfrms** [comment]
# Q:

>how to show react-native Local PC / Mac Environment Info?

# A:

> just using the cli

```sh
$  react-native info 

```
