### ISSUE TITLE
TVEventHandler does not capture any events

### ISSUE THREAD

**Issue by acollazomayer** [facebook/react-native#21896]
## Environment
React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
      Memory: 2.49 GB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.5.0 - ~/.nvm/versions/node/v10.5.0/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.5.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
      Android SDK:
        Build Tools: 23.0.1, 25.0.0, 25.0.1, 26.0.1, 26.0.2, 27.0.0, 27.0.3, 28.0.1
        API Levels: 23, 24, 25, 26, 27, 28
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728
      react-native: 0.57.3 => 0.57.3
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-create-library: 3.1.2
      react-native-drm-video: 3.1.0
      react-native-git-upgrade: 0.2.7
      react-native-rename: 2.2.2

## Description
I implement the code from the documentation about TVEventHandlers and i do not receive any events when i press the buttons controls. The `adb logcat` throws that the events are reaching however the TVHandler does not capture them.

## Reproducible Demo
I dont use expo however just add this code to the react-native init. And you will see my point.

```constructor() {
    super();

    this._tvEventHandler = null;
  }

  _enableTVEventHandler() {
    this._tvEventHandler = new TVEventHandler();
    console.log(this._tvEventHandler)
    this._tvEventHandler.enable(this, function(cmp, evt) {
      console.log(evt)
   });
  }

  _disableTVEventHandler() {
    if (this._tvEventHandler) {
      this._tvEventHandler.disable();
      delete this._tvEventHandler;
    }
  }

  componentDidMount() {
    this._enableTVEventHandler();
  }

  componentWillUnmount() {
    this._disableTVEventHandler();
  }```

**Comment by tomashavlas** [comment]
I've encountered the same problem, but the handler will work if I put any touchable component on the screen.
