### ISSUE TITLE
Base64 encoded image not visible in IOS UI

### ISSUE THREAD

**Issue by AJAYVERMA95** [facebook/react-native#21890]
### Base64 encoded image not visible in IOS UI
###The Issue is happening only in IOS. In Android it is working fine.

The base64 image in fetched from server and pushed to redux store in some page namely "Dashboard".
In other page namely "Account", I am fetching the base64 image from redux store and storing it in state of Account's page and showing it in UI using "this.state.profilePic".
The image is not visible when I am using  "this.state.profilePic" but it is visible when I am pasting the complete base64 string in the "uri" of "source" prop of Image component.

### Here is the code
import React, { Component } from 'react';
import { Image } from 'react-native';

export default class Account extends Component {
  constructor(props)
  {
    super(props);
    this.state={
      userProfilePic: store.getState().user.profilePic
    }
  }

render() {
       return (
                <Image source={{ uri : `data:image/*;base64,${this.state.userProfilePic}` }} style={{width:90, 
                             height:90, marginTop: 10, borderRadius: 10 }}/> 
        )
  }
}

### Here is my specifications

React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i7-3635QM CPU @ 2.40GHz
      Memory: 1.84 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.4 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
      Android SDK:
        Build Tools: 23.0.1, 23.0.2, 25.0.0, 25.0.2, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.2
        API Levels: 23, 25, 26, 27, 28
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1

**Comment by gomdolkim** [comment]
I am using 0.59.9 and the problem still exists.
