### ISSUE TITLE
Could not find support-vector-drawable.aar

### ISSUE THREAD

**Issue by LintangWisesa** [facebook/react-native#21916]
I run react-native 0.57.1 app, then I got the following lines.

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not find support-vector-drawable.aar (com.android.support:support-vector-drawable:27.1.1).
  Searched in the following locations:
      https://jcenter.bintray.com/com/android/support/support-vector-drawable/27.1.1/support-vector-drawable-27.1.1.aar
> Could not find livedata-core.aar (android.arch.lifecycle:livedata-core:1.1.0).
  Searched in the following locations:
      https://jcenter.bintray.com/android/arch/lifecycle/livedata-core/1.1.0/livedata-core-1.1.0.aar
> Could not find viewmodel.aar (android.arch.lifecycle:viewmodel:1.1.0).
  Searched in the following locations:
      https://jcenter.bintray.com/android/arch/lifecycle/viewmodel/1.1.0/viewmodel-1.1.0.aar
> Could not find runtime.aar (android.arch.core:runtime:1.1.0).
  Searched in the following locations:
      https://jcenter.bintray.com/android/arch/core/runtime/1.1.0/runtime-1.1.0.aar
```
Any suggestions? Thx in advance

**Comment by ap050492** [comment]
Moving google() to the first element in the list helped me

allprojects {
  repositories {
      google() // now here
      mavenLocal()
      jcenter()
      maven {
          // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
        url "$rootDir/../node_modules/react-native/android"
      }
      // google() // was here
  }
}

**Comment by jeongsd** [comment]
Thank you @ap050492  it work for me

**Comment by p2mThinknet** [comment]
Thank you @ap050492 u save my day!!!

**Comment by LintangWisesa** [comment]
It works! Thx a lot @ap050492!

**Comment by LintangWisesa** [comment]
Closes #677

**Comment by dharmendrajadon** [comment]
It works! @ap050492!

**Comment by ALEKS2** [comment]
what is the name of the file containing that list

**Comment by dharmendrajadon** [comment]
@ALEKS2 build.gradle in android project/android

**Comment by xiaodehua** [comment]
谢谢你拯救了我 @ap050492!

**Comment by best-boy** [comment]
终于找到解决问题的地方了 @ap050492

**Comment by mukherjeesrijan2** [comment]
Any solution to fix this permanently?

**Comment by cairesr** [comment]
Thank you @ap050492 !

**Comment by rahulbajaj1995** [comment]
Thank you @ap050492 You saved my day..!! Cheers

**Comment by patosmack** [comment]
Thanks !

**Comment by c3098051** [comment]
@ap050492 thanks! it helped

**Comment by tokinonagare** [comment]
In my case, for gradle:2.2.3

```java
allprojects {
    repositories {
        maven { url 'https://maven.google.com' }  // now here
        mavenLocal()
        jcenter()
        maven { url "$rootDir/../node_modules/react-native/android" }
        maven { url 'https://maven.google.com' }  // was here
    }
}
```

**Comment by gluecklich0205** [comment]
thank you so much! @ap050492

**Comment by TomasYu** [comment]
@ap050492  You are right! You save me !

**Comment by nzrsrk** [comment]
allprojects {
  repositories {
      google() // now here
      mavenLocal()
      jcenter()
      maven {
          // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
        url "$rootDir/../node_modules/react-native/android"
      }
      // google() // was here
  }
} 

still same error what to do?

**Comment by robisatthefunction** [comment]
THANK YOU!!

**Comment by Karanveer-logiciel** [comment]
I am facing same issue in ionic app Anyone can help me please?

**Comment by FranciscoSalesCarvalho** [comment]
Thanks a lot. It works
