### ISSUE TITLE
clearTextOnFocus not working in react-native android

### ISSUE THREAD

**Issue by lavarajallu** [facebook/react-native#21914]
Hi , i want need clear textInput focus working fine in iOS coming to android it's not working as well.

I used like this this is not working at 
` onFocus= {() => this.setState({text : ''})}`

So, after i used textInput property  `clearTextOnFocus = {true}` but it's applicable in iOS not an android . How can i solve this problem in android also ??

**Comment by Udbhav12** [comment]
@lavarajallu : How did you solve this problem?
