### ISSUE TITLE
react-native-fbsdk error can't run react-native run-android

### ISSUE THREAD

**Issue by ydv0121** [facebook/react-native#21917]
can't able to run app because of react-native-fbsdk

## Environment
Task :react-native-fbsdk:compileDebugJavaWithJavac FAILED
/Users/jacmacos2/Desktop/Nishit/MWM/MWM/node_modules/react-native-fbsdk/android/src/main/java/com/facebook/reactnative/androidsdk/FBGraphRequestModule.java:155: error: no suitable constructor found for AccessToken(String,String,String,<null>,<null>,<null>,<null>,<null>)
           graphRequest.setAccessToken(new AccessToken(
                                       ^
   constructor AccessToken.AccessToken(String,String,String,Collection<String>,Collection<String>,AccessTokenSource,Date,Date,Date) is not applicable
     (actual and formal argument lists differ in length)
   constructor AccessToken.AccessToken(Parcel) is not applicable
     (actual and formal argument lists differ in length)
/Users/jacmacos2/Desktop/Nishit/MWM/MWM/node_modules/react-native-fbsdk/android/src/main/java/com/facebook/reactnative/androidsdk/Utility.java:64: error: no suitable constructor found for AccessToken(String,String,String,List<String>,List<String>,AccessTokenSource,Date,Date)
       return new AccessToken(
              ^
   constructor AccessToken.AccessToken(String,String,String,Collection<String>,Collection<String>,AccessTokenSource,Date,Date,Date) is not applicable
     (actual and formal argument lists differ in length)
   constructor AccessToken.AccessToken(Parcel) is not applicable
     (actual and formal argument lists differ in length)
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/jacmacos2/Desktop/Nishit/MWM/MWM/node_modules/react-native-fbsdk/android/src/main/java/com/facebook/reactnative/androidsdk/Utility.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-fbsdk:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
124 actionable tasks: 2 executed, 122 up-to-date
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

## Description

can't build apk or run the app in emulator..react-native run-android stuck at above error and BUILD FAILED

**Comment by nabeelpkl** [comment]
Having same issue

**Comment by gmneoh** [comment]
Suddenly having this issue since 10.30am. It still work fine at 9.30am. No code changes, and any library upgrade.

**Comment by jsartisan** [comment]
Same error. My Project was working fine yesterday. :/

**Comment by ydv0121** [comment]
> Having the same issue. It was working fine till now. No idea why this issue is coming when I run `react-native run-android`

yes i got this error when i run react-native run-android
now can't run app :-(

**Comment by wrongkitchen** [comment]
Same here, still work yesterday

Environment:
  OS: macOS High Sierra 10.13.6
  Node: 10.9.0
  Yarn: 1.7.0
  npm: 6.2.0
  Watchman: 4.7.0
  Xcode: Xcode 10.0 Build version 10A255
  Android Studio: 3.1 AI-173.4907809

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: ^0.52.3 => 0.52.3

**Comment by ydv0121** [comment]
> Suddenly having this issue since 10.30am. It still work fine at 9.30am. No code changes, and any library upgrade.

same here..
**issue with there 2 files**

![screen shot 2018-10-24 at 11 42 30 am](https://user-images.githubusercontent.com/37238045/47409977-ff5f7880-d781-11e8-8181-659beb1c869e.png)

**Comment by radko93** [comment]
Please report this bug `react-native-fbsdk` repo. Not sure how we can help over here.

**Comment by TakayukiCho** [comment]
The problem is that react-native-fbsdk repo doesn't accept issues 😢

**Comment by radko93** [comment]
@TakayukiCho I just updated my answer. Please refer to FB bug issue.

**Comment by nabeelpkl** [comment]
Got a work around. changed` node_modules/react-native-fbsdk/android/build.gradle` from `compile 'com.facebook.android:facebook-android-sdk:4.38.0'` to `compile 'com.facebook.android:facebook-android-sdk:4.37.0'`. Atleast its working now.

**Comment by krupalagravat** [comment]
i just updated two files and issue solved : 
<img width="1436" alt="screen shot 2018-10-24 at 11 54 16 am" src="https://user-images.githubusercontent.com/20594018/47410799-8e6d9000-d784-11e8-9a54-0b40de9a2e7c.png">
<img width="1436" alt="screen shot 2018-10-24 at 11 55 53 am" src="https://user-images.githubusercontent.com/20594018/47410800-8f062680-d784-11e8-9cfd-0217cd7b562c.png">
go to Utility file and add null below last refreshtime 72 line and
go to FBGraphRequestModule file and add null below 163 line .

**This is temporary solution** .

**Comment by ahmedkotb** [comment]
I had the same issue today as well, upgrading react-native-fbsdk to 0.8.0 seems to fix it

**Comment by pragneshpj** [comment]
@ahmedkotb Its working

**Comment by radko93** [comment]
Please discuss it in the corresponding issue not here.
