### ISSUE TITLE
[Android] Touching multiple buttons at the same time doesn't work 

### ISSUE THREAD

**Issue by achuvm** [facebook/react-native#21912]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Run `react-native info` in your terminal and paste its contents here.

```
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
      Memory: 56.11 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 9.4.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
      Android SDK:
        Build Tools: 23.0.1, 23.0.3, 24.0.0, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 27.0.2, 27.0.3
        API Levels: 14, 15, 21, 23, 24, 25, 26, 27
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728 
      react-native: 0.57.3 => 0.57.3 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```
## Description

See the below GIFs. On iOS touching multiple buttons give the correct callbacks to the individual buttons whereas on Android, touching other buttons trigger the callbacks on the first buttons.

I'm using `onTouchStart()` and `onTouchEnd()`.

I tried replacing `<View onTouchStart={} onTouchEnd={} />` with `<TouchableOpacity onPressIn={} onPressOut={} />` and in that case, touching the other buttons do nothing for both iOS and Android.

iOS:
![ios_touch_issue](https://user-images.githubusercontent.com/21074927/47393602-d1702a80-d6d4-11e8-8684-eabd30a30170.gif)

Android:
![android_touch_issue](https://user-images.githubusercontent.com/21074927/47393603-d208c100-d6d4-11e8-9b04-3349ff54425c.gif)

## Reproducible Demo
Here's the `App.js` (renamed to `.txt` to be able to upload) I used. Just create a new React Native project and replace the `App.js` with this file.
[App.txt](https://github.com/facebook/react-native/files/2508148/App.txt)

**Comment by markoradei** [comment]
Maybe this will help you https://facebook.github.io/react-native/docs/panresponder
