### ISSUE TITLE
[Unknown] query failed: synchronization failed: Operation timed out

### ISSUE THREAD

**Issue by jacob-israel-turner** [facebook/react-native#2191]
Today, alignItems and alignSelf suddenly stopped working on my project.  Anywhere I tried using it, there was no longer any effect.  I rebooted and got this error after building:

```
Launching Dev Tools...
tab id 736 of window id 116


[17:57:31] <START> request:/index.ios.bundle
[17:57:31] <START> find dependencies
[17:57:33] <START> request:/index.ios.bundle
Error: query failed: synchronization failed: Operation timed out

    at BunserBuf.<anonymous> (/Users/jacob/code/projects/CancerSpot/node_modules/react-native/node_modules/sane/node_modules/fb-watchman/index.js:93:23)
    at emitOne (events.js:77:13)
    at BunserBuf.emit (events.js:169:7)
    at BunserBuf.process (/Users/jacob/code/projects/CancerSpot/node_modules/react-native/node_modules/sane/node_modules/fb-watchman/bser.js:289:10)
    at /Users/jacob/code/projects/CancerSpot/node_modules/react-native/node_modules/sane/node_modules/fb-watchman/bser.js:244:12
    at doNTCallback0 (node.js:408:9)
    at process._tickCallback (node.js:337:13)
Error: query failed: synchronization failed: Operation timed out

    at BunserBuf.<anonymous> (/Users/jacob/code/projects/CancerSpot/node_modules/react-native/node_modules/sane/node_modules/fb-watchman/index.js:93:23)
    at emitOne (events.js:77:13)
    at BunserBuf.emit (events.js:169:7)
    at BunserBuf.process (/Users/jacob/code/projects/CancerSpot/node_modules/react-native/node_modules/sane/node_modules/fb-watchman/bser.js:289:10)
    at /Users/jacob/code/projects/CancerSpot/node_modules/react-native/node_modules/sane/node_modules/fb-watchman/bser.js:244:12
    at doNTCallback0 (node.js:408:9)
    at process._tickCallback (node.js:337:13)
```

I saw #2186 and tried upgrading to 3.6.0 to see if that solved it.  I got the same error that @KaterMikesch described.  After reverting to 3.3.0, I'm getting the error above.

I upgraded to 0.8.0 stable 12 hours after it was released.  I've been able to work, build, reboot, and repeat without any problems until now.

I'm on Mac OSX 10.10.4

**Comment by brentvatne** [comment]
If you disable chrome debugging will this work?

**Comment by jacob-israel-turner** [comment]
No, I get the same error.

**Comment by jacob-israel-turner** [comment]
After removing the project and re-installing, the error has stopped.  It looks like I'm still having problems with alignItems and alignSelf.  I'll play with it for a bit and log another issue if the problem persists.  Thanks!

**Comment by JoshKimmelman** [comment]
I'm having the same issue.  I've tried re-installing everything, still get an error.  I can't even get "hello world" to appear on the screen.

**Comment by hzhu** [comment]
+1 anyone able to solve this issue

**Comment by MatApple** [comment]
I get this issue when my project lives within my Dropbox. Moving project out of the Dropbox folder resolves the issue for me.

**Comment by jcutrell** [comment]
As it turns out, it seems as though maybe Hazel can cause these types of problems, too.

**Comment by wpapper** [comment]
I received the same issue when trying to run the Hello World example created by `react-native init`. I was also using a folder synced with Dropbox. Uninstalling Watchman and then running `brew install --HEAD watchman` fixed the issue.

**Comment by yunsankai** [comment]
wpapper's program a good solution to this problem. At least it work for me.

**Comment by brentvatne** [comment]
Sounds like this is solved by reinstalling watchman!

**Comment by ajmald** [comment]
I Did what facebook recommends us to do !
watchman shutdown-server
brew update
brew reinstall watchman

brew didn’t want to reinstall watchman, did chown and I did 

sudo chown root /usr/local/bin/brew

react-native run-ios

Build succeeded,
but still got the dependency graph error and Watchman not running )

jmals-MacBook-Pro:~ ajmal$ ps -ef | grep watchman

  501  5268     1   0 10:28PM ??         0:00.95 /usr/local/Cellar/watchman/4.6.0/libexec/bin/watchman --foreground --logfile=/usr/local/var/run/watchman/ajmal-state/log --log-level=1 --sockname=/usr/local/var/run/watchman/ajmal-state/sock --statefile=/usr/local/var/run/watchman/ajmal-state/state --pidfile=/usr/local/var/run/watchman/ajmal-state/pid
    0  5364     1   0 10:28PM ??         0:00.01 /usr/local/Cellar/watchman/4.6.0/libexec/bin/watchman --foreground --logfile=/usr/local/var/run/watchman/root-state/log --log-level=1 --sockname=/usr/local/var/run/watchman/root-state/sock --statefile=/usr/local/var/run/watchman/root-state/state --pidfile=/usr/local/var/run/watchman/root-state/pid
  501  5530  5502   0 10:39PM ttys000    0:00.00 grep watchma


So, Watchman is running in the foreground, where may be lying the ISSUE ?????

**Comment by ptaking** [comment]
@ajmald Given that `watchman` is running in the foreground. How will you fix that?

**Comment by neverlous** [comment]
I did't fix this .....
