### ISSUE TITLE
[Navigator] initialRouteStack - push another route

### ISSUE THREAD

**Issue by PhilippKrone** [facebook/react-native#2192]
I'm using the navigator with an initialRouteStack consisting out of 4 standard routes. I now have the following requirement:

* I'm currently on route number 0 and want to push() to a 5th (new route)
* When using pop() from the new route, I want to go back to route 0 (the one I came from)

What is the intended way to do that? I was thinking of something like pushToEnd(route), which does not exist yet. Is it worth creating a PR for that?

**Comment by ericvicenti** [comment]
You should be able to do this:

```
this.navigator.replaceAtIndex(newRoute, 4);
this.navigator.jumpTo(newRoute);
```

**Comment by PhilippKrone** [comment]
@ericvicenti OK, i will test that. I was just not testing it before as the code is:

````javascript
  replaceAtIndex: function(route, index, cb) {
    invariant(!!route, 'Must supply route to replace');
    if (index < 0) {
      index += this.state.routeStack.length;
    }

    if (this.state.routeStack.length <= index) {
      return;
    }
````

and this looks like the function is just gonna "return" without doing anything.

**Comment by ericvicenti** [comment]
Ah, you're probably right. Could you submit a PR that allows `replaceAtIndex` to replace the next available index? That seems pretty low risk to me

**Comment by PhilippKrone** [comment]
@ericvicenti there we go: https://github.com/facebook/react-native/pull/2197

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/navigator-initialroutestack-push-another-route
