### ISSUE TITLE
React native 0.57.3 broken after the powered by screen in ios

### ISSUE THREAD

**Issue by nisharafic** [facebook/react-native#21926]
## Environment
React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
      Memory: 918.54 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.7.0 - /usr/local/bin/node
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
    IDEs:

## Description
I have a issue when i run react-native ios app. it get closed after the splash screen shows in ios. android works fine. this happen after i updated to xcode 10. can you please help me what cause this issue. is there any setting need to be enable from xcode side. 

![image](https://user-images.githubusercontent.com/3440229/47442750-7d08a000-d7e5-11e8-8166-34a601631f67.png)

**Comment by kelset** [comment]
> this happen after i updated to xcode 10.

I suggest you try running the Xcode 10 workaround written here https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md#known-issues

**Comment by rodrigoelp** [comment]
Isn't this the same issue we have been following here? #21741

**Comment by rodrigoelp** [comment]
@nisharafic could you please confirm the following symptoms?

Steps to reproduce:

```sh
react-native init whatever
cd whatever
react-native run-ios
```

At that time, the project starts building and towards the end of it, you either do not get the metro bundler running or the metro bundler starts packaging and gets stuck at some point (in my case, it does it at times around 90% and other times around 75%... it depends on the number of dependencies).

If you have this issue, that is an xcode 10 issue we have been reporting for a while under the "react native is broken for 0.57.x and xcode 10"

Now... one of the steps I have found it works is, to kill or terminate all the node process (like mtro bundler) and start again calling `react-native start --reset-cache`... eventually this gets it to work and you can continue working.

If this is not your case, please supply the steps to reproduce (so somebody can follow these steps).
