### ISSUE TITLE
NetInfo: effectiveType only changes if type changes

### ISSUE THREAD

**Issue by fliPmitKlammern** [facebook/react-native#21923]
## Environment
    System:
      OS: Windows 10
      CPU: x64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
      Memory: 1.14 GB / 7.89 GB
    Binaries:
      Yarn: 1.10.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.1.0.0 AI-173.4907809
React Native: v0.57.1

## Description
Both `NetInfo.getConnectionInfo()` and the event listener that I added via `NetInfo.addEventListener('connectionChange')` don't seem to pick up changes of the network connection if the type stays the same and only the effectiveType changes.

In other words:
When I monitor the Android Emulator with cellular connection and the connection changes from 4g to 3g, the change is not reflected in the effectiveType. If I change to wifi and back to cellular, the effectiveType is adapted accordingly.

## Reproducible Demo
1. Start App on Android Emulator and deactivate wifi
2. Call `NetInfo.getConnectionInfo()` - it will correctly return the current effectiveType (e.g. '4g')
3. Change the network type in the Android Emulator (e.g. to "EDGE")
4. Call `NetInfo.getConnectionInfo()` - it will still return the previous effectiveType ('4g')
5. Activate wifi on the emulator
6. Deactivate wifi again
7. Call `NetInfo.getConnectionInfo()` - it will now return the correct effectiveType ('2g')

**Comment by JuRomand** [comment]
Same problem here with the following result to "react-native info": 

Environment:
  OS: macOS High Sierra 10.13.6
  Node: 10.5.0
  Yarn: Not Found
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: Xcode 10.0 Build version 10A255
  Android Studio: 3.2 AI-181.5540.7.32.5056338

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz => 0.55.2

**Comment by tepho** [comment]
same issue here, its only detecting changes between wifi <--> cellular , but Cellular: 4g <--> 2g it doesnt trigger 'connectionChange' listner
