### ISSUE TITLE
Jest/Enzyme snapshots show 'Component' instead of the native component

### ISSUE THREAD

**Issue by rajivshah3** [facebook/react-native#21937]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
      Memory: 189.02 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.4 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.config/yarn/global/node_modules/.bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        Build Tools: 27.0.3, 28.0.1, 28.0.3
        API Levels: 27, 28
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10O23u - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728 
      react-native: 0.57.3 => 0.57.3 
```

## Description
In React Native 0.57, the snapshots taken by Jest and Enzyme show `Component` instead of the actual native component (e.g. `View`, `Text`). [See diff](https://github.com/rajivshah3/rn-broken-snapshot/compare/master...0.55?expand=1#diff-9275259295fb7e8df5c67adafa9a8429). This is not only an issue when used with Jest, but also with Enzyme (https://github.com/airbnb/enzyme/issues/1743).

## Reproducible Demo
This can be reproduced by simply upgrading `react-native` as shown [here](https://github.com/rajivshah3/rn-broken-snapshot/compare/0.55...broken-example).

A full example is located at https://github.com/rajivshah3/rn-broken-snapshot. The `master` branch is the latest version of React Native with a working snapshot test, the `0.55` branch is v0.55 of React Native, and `broken-example` is an example of a project that is trying to upgrade from v0.55 to the latest version.

**Comment by rajivshah3** [comment]
It seems like `Button` and `Switch` [don't have this issue](https://github.com/rajivshah3/rn-broken-snapshot/compare/button). Is it possible that https://github.com/facebook/react-native/commit/e708010d18f938e2d6b6424cfc9485d8e5dd2800 or https://github.com/facebook/react-native/commit/3e534b9aab5156adac67762877b2457408fe8934 caused this?

**Comment by ljharb** [comment]
Yes; you’d have to explicitly set a displayName property on the forwardRef to get it to show up.

**Comment by jamesmcn1** [comment]
@rajivshah3 did your fix get released in a new RN version yet?

**Comment by jamesmcn1** [comment]
Seems to have fixed all my tests when I just upgraded from 0.57.0 ---> 0.57.8

Thanks guys :)

**Comment by rajivshah3** [comment]
Yep, it was included in 0.57.5

**Comment by linnett** [comment]
Still seeing this issue in `0.57.8`. `<Image>` showing as `<Component>` in my debug. Any ideas?

**Comment by linnett** [comment]
Good shout @rajivshah3 - PR: https://github.com/facebook/react-native/pull/23287
