### ISSUE TITLE
Could not resolve all files for configuration ':app:debugCompileClasspath'.

### ISSUE THREAD

**Issue by 0906014109** [facebook/react-native#21943]
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not find support-vector-drawable.aar (com.android.support:support-vector-drawable:27.1.1).
  Searched in the following locations:
      https://jcenter.bintray.com/com/android/support/support-vector-drawable/27.1.1/support-vector-drawable-27.1.1.aar
> Could not find livedata-core.aar (android.arch.lifecycle:livedata-core:1.1.0).
  Searched in the following locations:
      https://jcenter.bintray.com/android/arch/lifecycle/livedata-core/1.1.0/livedata-core-1.1.0.aar
> Could not find viewmodel.aar (android.arch.lifecycle:viewmodel:1.1.0).
  Searched in the following locations:
      https://jcenter.bintray.com/android/arch/lifecycle/viewmodel/1.1.0/viewmodel-1.1.0.aar
> Could not find runtime.aar (android.arch.core:runtime:1.1.0).
  Searched in the following locations:
      https://jcenter.bintray.com/android/arch/core/runtime/1.1.0/runtime-1.1.0.aar

**Comment by 0906014109** [comment]
{
  "errors" : [ {
    "status" : 404,
    "message" : "Could not find resource"
  } ]
}
Why ?What can I do to resolve this problem?

**Comment by JamalZafar04** [comment]
I have the same issue and nothing seems to work at all

**Comment by julienkermarec** [comment]
Same issue with ionic 3

**Comment by JamalZafar04** [comment]
I dont know about ionic 3 but in java i was moving the google() up but was not saving it. I saved,installed jdk and made environment variable and it worked. Give it a try if you have something similar
