### ISSUE TITLE
[0.57] - NetInfo methods fail to resolve or reject

### ISSUE THREAD

**Issue by GregoryCollett** [facebook/react-native#21953]
- [X] Review the documentation: https://facebook.github.io/react-native
  - [X] Search for existing issues: https://github.com/facebook/react-native/issues
  - [X] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
      Memory: 1.94 GB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.0.0 - /usr/local/bin/node
      Yarn: 1.9.2 - ~/.yarn/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.0 => 16.6.0 
      react-native: 0.57.3 => 0.57.3

## Description
`NetInfo.getConnectionInfo()` & `NetInfo.isConnected.fetch()` fail to resolve or reject

## Reproducible Demo
Able to reproduce this in the simplest of scenarios running on an iOS simulator in debug js mode (android untested)
`NetInfo.getConnectionInfo().then(console.log).catch(console.log)` <- neither log occurs

**Comment by JumalDB** [comment]
We have ismilar issue
https://github.com/facebook/react-native/issues/21862

**Comment by GregoryCollett** [comment]
Seem's this is working in 0.57.4 patch. Would be interested to know where this regression occurred and also if it had been noticed why it had not been mentioned in the changelog. Anyway, Seems this issue can be closed as it is rectified in the latest release (0.57.4).

**Comment by benjarwar** [comment]
Experiencing [similar issues](https://github.com/facebook/react-native/issues/22966) with `NetInfo.isConnected.addEventListener` in 0.57.8.

**Comment by juanfer0002** [comment]
Just to add. This is a problem that only occurs in iOS, it's working fine in Android.

A snippet like this would never print 'After isConnected':
```
static async checkConnection() {
    console.log('Before isConnected');
    let isConnected = await NetInfo.isConnected.fetch();
    console.log('After isConnected', isConnected);
}
```

**Comment by cpojer** [comment]
Heads up: we moved react-native-netinfo into its own repository, which should allow for making changes and fixes much faster. Please continue the discussion about this issue there: https://github.com/react-native-community/react-native-netinfo/issues/9

**Comment by matt-oakes** [comment]
Just a note to say that it looks like the cause of this issue is the same as #21862, which is now being tracked at https://github.com/react-native-community/react-native-netinfo/issues/10.

Please let me know if they are not the same root cause by opening an issue with an updated reproducible demo on [the new community repo](https://github.com/react-native-community/react-native-netinfo).
