### ISSUE TITLE
Absolutely positioned container does not shrink to fit children if a child contains flex-direction of row

### ISSUE THREAD

**Issue by bananatranada** [facebook/react-native#21957]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
[skip envinfo]
```

## Description
Absolutely positioned container does not shrink to fit children if a child contains flex-direction of row. Or if the child's child contains width: '100%'.

Dunno if I'm in that niche territory, but this has taken me a very long time to spot the source of the problem. I hope this can be fixed so that the next person doesn't have to.

## Reproducible Demo
Comment out either `flexDirection: row` or `width` under `headerContent`.
https://snack.expo.io/S1Pdpkgh7

And here's the expected behavior:
https://codepen.io/BANANATRANADA/pen/jeXoLj

**Comment by Daffodil12** [comment]
Have you tried it on your local emulator or real device rather then expo. It is working fine for me as expected result.

**Comment by bananatranada** [comment]
I'm using an outdated version so I tried it on expo. What version are you using? It looks like expo uses version 55.4
