### ISSUE TITLE
iOS/android behaviour inconsistency: [...Array(n).keys()]

### ISSUE THREAD

**Issue by joshbalfour** [facebook/react-native#21962]
## Environment

```
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 965.88 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.8.0 - /usr/local/bin/node
      Yarn: 1.3.2 - /usr/local/bin/yarn
      npm: 6.4.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728 
      react-native: ^0.57.3 => 0.57.3 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

## Description
I'm seeing inconsistent behaviour when using `[...Array(5).keys()]`
on iOS it outputs `[0,1,2,3,4]`
on Android it outputs `[]`

## Reproducible Demo
https://snack.expo.io/@joshbalfour/array-keys-inconsistency-demo

**Comment by joshbalfour** [comment]
Note: if you run this with remote debugging enabled it outputs `[0,1,2,3,4]`, regardless of platform (which makes sense because the JS is running in a webworker)

**Comment by gre** [comment]
This probably happens because Android is still on an old version of JSC. this is one of the symptoms but there are many other ones: https://github.com/facebook/react-native/issues/19737

The real fix would be React Native to upgrade JSC version, in the meantime you can manually use a more recent JSC following https://github.com/react-community/jsc-android-buildscripts

**Comment by gre** [comment]
it's also a dup of https://github.com/facebook/react-native/issues/18426 so you can probably close it

**Comment by joshbalfour** [comment]
@gre you're right- thanks!
