### ISSUE TITLE
[0.57.4-0.57.8/0.58.6] using textTransform causes text to disappear on Android, but works on iOS

### ISSUE THREAD

**Issue by kristerkari** [facebook/react-native#21966]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment

```
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
      Memory: 1.51 GB / 16.00 GB
      Shell: 2.7.1 - /usr/local/bin/fish
    Binaries:
      Node: 8.11.4 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.4.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
      Android SDK:
        Build Tools: 23.0.1, 23.0.3, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.0
        API Levels: 17, 18, 19, 21, 22, 23, 25, 26, 27
    IDEs:
      Android Studio: 3.1 AI-173.4670197
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728 
      react-native: 0.57.4 => 0.57.4 
```

## Description

React Native 0.57.4 brings support for using `textTransform` style property on Android. When setting `textTransform` value to `uppercase`, `lowercase` or `capitalize` the text is not shown at all on Android, but is shown correctly on iOS.

If the `textTransform` property is removed, then the text renders normally.

This can be easily reproduced by creating a new React Native project and setting the `textTransform` property to one of the texts inside `App.js`.

**Screenshots:**

iOS simulator (iPhone 8 / iOS 12):

<img width="471" alt="ios" src="https://user-images.githubusercontent.com/993108/47582471-1908e780-d95d-11e8-8405-a7a39858deea.png">

Android emulator (Nexus 5X / Android 5.0):

<img width="414" alt="android5" src="https://user-images.githubusercontent.com/993108/47582538-46559580-d95d-11e8-8d4a-6543fd82a7fb.png">

Android emulator (Nexus 5X / Android 8.0):

<img width="392" alt="android8" src="https://user-images.githubusercontent.com/993108/47582567-5c635600-d95d-11e8-99ce-7641b6e91f14.png">

## Reproducible Demo

Have a look at the demo that is a new 0.57.4 project with `textTransform` added to the welcome text.
https://github.com/kristerkari/react-native-text-transform-issue/blob/master/App.js#L43

**Comment by ziyafenn** [comment]
Enabling textTransform on android with RN0.57.4 breaks the styling of the text and renders the text very weirdly.

**Comment by kristerkari** [comment]
I tested with React Native 0.57.5, and the bug is still reproducible.

**Comment by marlosirapuan** [comment]
same here.. `"react-native": "0.57.4"` : (

**Comment by chrismcamp** [comment]
reproducible on react-native 0.58-rc.0

**Comment by gbfeliped** [comment]
same as here
react-native-cli: 2.0.1
react-native: 0.57.4

**Comment by harveyconnor** [comment]
I have the text displaying however it isn't applying my color styling to it.

**Comment by elucaswork** [comment]
I noticed something weird: If the text has some (any) emoji, the text appears.

**Comment by riso** [comment]
Can reproduce this on react-native 0.57.7 as well

**Comment by n1ru4l** [comment]
Seems like this issue was introduced in https://github.com/facebook/react-native/commit/22cf5dc5660f19b16de3592ccae4c42cc16ace69

**Comment by sumitjr** [comment]
experiencing the same issue in react-native 0.57.5

**Comment by aamalric** [comment]
Same here !
react-native-cli: 2.0.1
react-native: 0.57.4

**Comment by kelset** [comment]
Is this still happening on 0.57.7? Is this reproducible on master?

**Comment by soutot** [comment]
I'm facing the same issue ATM. On iOS ```textTransformation``` works fine, but it disappears on Android.

RN 0.57.7

A workaround for now is using JS to capitalize the string

```
capitalizeString = (text: string) => typeof text === 'string' && text.length > 0 && `${text[0].toUpperCase()}${text.slice(1)}`

this.capitalizeString('mystring') 
```

**Comment by kristerkari** [comment]
Still reproducible with 0.57.8

**Comment by kristerkari** [comment]
> Any Update on this issue?

There is a pull request that should fix the bug: #22670

**Comment by MrLoh** [comment]
Will f6f8b092f9dac03e81cb01a73e748f3df85ea519 be part of the next RC, would be great to get a version with the fix.

**Comment by kristerkari** [comment]
Still reproducible with v0.58.0

**Comment by kristerkari** [comment]
Still reproducible with v0.58.1

**Comment by kristerkari** [comment]
Still reproducible with v0.58.3

**Comment by sryze** [comment]
Same problem, 0.57.8, used to work with 0.57.2 before I ugpraded

**Comment by kristerkari** [comment]
Still reproducible with v0.58.4

**Comment by sryze** [comment]
I'm using [this function](https://gist.github.com/sryze/f67687f045c4aa806cf9b59495aa57b6) as a workraound, perhaps it could be useful to somebody

**Comment by kristerkari** [comment]
Looks like this is finally fixed in React Native 0.59.0-rc.0 and the fix is most likely going to be part of the 0.59.0 release.

**Comment by hbaseline** [comment]
> I noticed something weird: If the text has some (any) emoji, the text appears.

*Boss:* Why is there emoji?
*Me:* Ho that? it’s a bug fix.

**Comment by arnotixe** [comment]
Reproducible on 0.58.5… I'm using string.toUpperCase() as workaround

**Comment by trane294** [comment]
Confirming. Still happens on 0.58.5

**Comment by akhilsanker** [comment]
Anyone have any workaround to solve this bug?
Any suggestion is appreciable.

Thanks

**Comment by jpamarohorta** [comment]
Removing `lineHeight` fixes the issue. I guess the problem lies with that style attribute.

**Comment by MrLoh** [comment]
Wait for 0.59 to use text-transform

**Comment by reddeguzman** [comment]
User `upperCase` from Lodash instead

**Comment by reddeguzman** [comment]
does not fix the RN issue but fixes your problem

**Comment by artjos** [comment]
react-native 0.59.0
textTransform:"uppercase" on Text still not working...

**Comment by kelset** [comment]
0.59.0 is released, @kristerkari is it finally fixed, as you mentioned [here](https://github.com/facebook/react-native/issues/21966#issuecomment-463900194)?

**Comment by kristerkari** [comment]
>  is it finally fixed, as you mentioned [here](https://github.com/facebook/react-native/issues/21966#issuecomment-463900194)?

I will re-test 👍

**Comment by kristerkari** [comment]
I created a fresh 0.59.0 project, added some styling, and it seems to me that the bug is now fixed:

```js
const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F5FCFF"
  },
  welcome: {
    fontSize: 48,
    textAlign: "center",
    margin: 10,
    color: "red",
    lineHeight: 60,
    textTransform: "lowercase"
  },
  instructions: {
    textAlign: "center",
    marginBottom: 5,
    lineHeight: 20,
    color: "green",
    textTransform: "uppercase"
  }
});
```

<img width="414" alt="Skärmavbild 2019-03-12 kl  20 11 59" src="https://user-images.githubusercontent.com/993108/54225122-ac554a80-4503-11e9-9a8a-d1c264f8d28d.png">
<img width="837" alt="Skärmavbild 2019-03-12 kl  20 13 17" src="https://user-images.githubusercontent.com/993108/54225140-b70fdf80-4503-11e9-96fc-7d5ba228b1e3.png">
<img width="497" alt="Skärmavbild 2019-03-12 kl  20 12 01" src="https://user-images.githubusercontent.com/993108/54225152-bd9e5700-4503-11e9-9ede-84fe509803c1.png">

**Comment by kristerkari** [comment]
`textTransform: "capitalize"` is working too:
<img width="428" alt="Skärmavbild 2019-03-12 kl  20 38 42" src="https://user-images.githubusercontent.com/993108/54226621-e411c180-4506-11e9-9dbf-8e7c621afe1e.png">

**Comment by kelset** [comment]
Great, thanks @kristerkari!

**Comment by sboudouk** [comment]
Thanks, also works for me.

**Comment by marlosirapuan** [comment]
100%! thank you!

**Comment by Nayan014** [comment]
What I found is **textTransform: "uppercase"** will work and **textTransform: 'uppercase'** will not work.
