### ISSUE TITLE
Deal with +1 spam in a more productive way

### ISSUE THREAD

**Issue by coffenbacher** [facebook/react-native#21978]
---

# For Discussion

Check the history of #12830 for an example of how this is ineffective: 
- issue was opened, received many reactions (+1) instead of comments
- issue was closed due to lack of comments
- issue was re-opened due to helpful intervention of initial reporter / contributor @bartolkaruza 
- people posted basic "+1 this is still happening" comments to avoid it getting killed again for lack of comments
- issue got close due to too many comments, even reactions 

IMO these types of issues should be left open, and +1 spam should simply be dealt with or a bot should handle it.

This is a specific follow-up to some of the general issues raised on Hacker News:
https://news.ycombinator.com/item?id=17314315

**Comment by rodrigoelp** [comment]
I particularly feel the community should assign a maintainer to certain issues, either to remove the noise or to identify which items are really issues on the field.

I've seen lots of issues, open to discussion and to try to find workarounds to issues, no maintainer ever manifest in it and eventually people ran out of things to say other than "this is still happening to me"
It is extremely frustrating.

**Comment by gre** [comment]
https://twitter.com/mxstbr/status/1056175420763226112 should fix it

**Comment by coffenbacher** [comment]
Beautiful! Good timing. I wonder if that suppresses notifications as well.

**Comment by hramos** [comment]
The bot could be updated to treat reactions as activity on the issue, at which point we can communicate that adding a +1 is unnecessary.

I place less value on reactions as ideally we'd see some discussion on how the issue can be fixed, but I can see why we shouldn't automatically close an issue that people are still reacting to.

**Comment by kelset** [comment]
I'll write a note about this so that it will be discussed during the next core meeting.

That said, I hope you can understand that the amount of work required to do issue triaging is really high, and 

> I particularly feel the community should assign a maintainer to certain issues

is not a viable solution, given the number of maintainers (and considering that most people helping with this side of the OSS project are doing it during their free time).

**Comment by bartolkaruza** [comment]
> is not a viable solution, given the number of maintainers (and considering that most people helping with this side of the OSS project are doing it during their free time).

Why not divide and conquer? The surface area of React Native is vast, but I'm sure there would be many willing volunteers to maintain issues in particular areas; Someone that keeps an eye out for all Android TextView related issues, someone triaging the issues regarding networking on iOS. This would be similar to how all the separate projects surrounding RN are handled.

All you would have to provide from the core team side is a structure to make the above proposal available to specific community members with clear rules and perhaps some automation from the bot to support it. This community has all the know-how to fix __all__ React Native issues, but currently lacks the power.

**Comment by bartolkaruza** [comment]
> IMO, you are oversimplifying a more complex issue; that said the community **already** has the "power" you mention: PRs.

I agree, I didn't see the slimmening discussion before, the discussion is much further than I thought.

**Comment by hramos** [comment]
Thanks for raising this question. I'd welcome a solid proposal about how to better deal with this. You can use the following repo: https://github.com/react-native-community/discussions-and-proposals
