### ISSUE TITLE
Image Blur effect becomes more than 50% lighter with scheme "Release"

### ISSUE THREAD

**Issue by dylancompanjen** [facebook/react-native#21973]
## Environment
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz
      Memory: 340.12 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 9.8.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.3.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
    IDEs:
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.6.0-alpha.8af6728 => 16.6.0-alpha.f47a958 
      react-native: ^0.57.4 => 0.57.4 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      react-native-rename: 2.2.2

## Description
When using the blurRadius prop on Image (https://facebook.github.io/react-native/docs/image#blurradius) the effect becomes much lighter when building your app for production (scheme: Release).
In my case I was using blurRadius={100} in development (tested on device), but to achieve the same result in production I have to more than double it to a radius of like 230.

**Comment by orta** [comment]
I couldn't repro this when changing the Xcode scheme (from Debug to Release)

Debug
<img width="584" alt="Screen Shot 2019-03-19 at 12 01 31 PM" src="https://user-images.githubusercontent.com/49038/54604638-270bf180-4a3f-11e9-8255-ceb8f5d136b6.png">

Release
<img width="584" alt="Screen Shot 2019-03-19 at 12 02 55 PM" src="https://user-images.githubusercontent.com/49038/54604649-2c693c00-4a3f-11e9-9617-6f0ca18b3992.png">

Nor on my phone via Expo

![IMG_3758](https://user-images.githubusercontent.com/49038/54604785-8ec23c80-4a3f-11e9-98de-a58eecde2875.PNG)

- is this still a problem?

**Comment by rickhanlonii** [comment]
Hey @dylancompanjen, if you can provide a way to repro we're happy to re-open and take a look 👍
