### ISSUE TITLE
#0.57.2 #Android native view cause background transparent

### ISSUE THREAD

**Issue by yaoyi601131548** [facebook/react-native#21987]
react native 0.54.4 screen is ok but when upgrade to 0.57.2 there is a problem, The entire screen becomes transparent elsewhere。

![image](https://github.com/yaoyi601131548/image/blob/master/Screenshot_20181029-114612_eWeLink.jpg)

how to fix it? help (;

**Comment by zhonglaoban** [comment]
i have the same issue. witch troubled me a long time. can you tell me what's the solution? @yaoyi601131548

**Comment by zhonglaoban** [comment]
i have the same issue. witch troubled me a long time. can you tell me what's the solution? @yaoyi601131548

**Comment by yaoyi601131548** [comment]
@zhonglaoban  You can use the RelativeLayout package surfaceview
