### ISSUE TITLE
WebView can not display csv/tsv file on Android  

### ISSUE THREAD

**Issue by pomu0326** [facebook/react-native#21988]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Environment:
  OS: macOS 10.14
  Node: 10.8.0
  Yarn: 1.9.4
  npm: 6.2.0
  Watchman: 4.9.0
  Xcode: Xcode 10.0 Build version 10A255
  Android Studio: 3.1 AI-173.4907809

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.2 => 0.55.2

## Description
I open the locally saved text file (txt/csv/tsv) with WebView.
On Android, it is not displayed if the extension is "csv / tsv".
It can be displayed when the extension is "txt".
All extensions can be displayed on iOS
 
I expect to be displayed as PlainText.

How can I open up on Android?

## Reproducible Demo
```js
import {View, WebView, Platform} from 'react-native'

...
render() {
  return (
    <View style={{flex: 1}}>
      <WebView source={{uri: Platform.OS === 'android'
        ? 'file:///my/saved/dir/sample.csv' 
        : '/my/saved/dir/sample.csv'
      }}/>
    </View>
  );
}
...
```

**Comment by dulmandakh** [comment]
Please try https://github.com/react-native-community/react-native-webview and file a bug there if you have issues. Thank you
