### ISSUE TITLE
Image in webview on Android not shown

### ISSUE THREAD

**Issue by udarts** [facebook/react-native#21989]
- [ X] Review the documentation: https://facebook.github.io/react-native
  - [ X] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ X] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
      Memory: 499.04 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.0.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        Build Tools: 27.0.3, 28.0.2
        API Levels: 19, 21, 22, 23, 24, 25, 26, 27, 28
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.2 => 16.4.2 
      react-native: 0.56.0 => 0.56.0 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description
I am using a webview to display custom html taken from Cloud FireStore. In some cases there is an image in that html. On iOS the image shows, but on Android the image is not shown. I just get the alt text.

This is the image tag inside the html: 
`<img src="https://firebasestorage.googleapis.com/v0/b/sjaloom-connect.appspot.com/o/images%2Fdcf8ab78-e98f-46db-bdae-eab7b18ded1a.jpg?alt=media&token=e654671a-4320-464a-b1fd-7236170d48f7" alt="undefined" style="float:none;height: 100px;width: 120px"/>`

Is this a bug in webview or is there a setting I miss.

**Comment by dulmandakh** [comment]
Please try https://github.com/react-native-community/react-native-webview and file a bug there if you have issues. Thank you

**Comment by udarts** [comment]
Thanks, I have updated to the latest version for react-native. Issue still occurs.
And I am using: react-native-webhtmlview, which is using webview fro react-native directly.

It should be something in the webview component.

**Comment by udarts** [comment]
Hereby the updated react-native info:

React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
      Memory: 24.10 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.0.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        Build Tools: 27.0.3, 28.0.2, 28.0.3
        API Levels: 19, 21, 22, 23, 24, 25, 26, 27, 28
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728 
      react-native: 0.57.4 => 0.57.4 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

**Comment by dulmandakh** [comment]
Webview will be removed from React Native and it's recommended to use
react-native-webview, which is fork of RN webview but greatly improved.

**Comment by udarts** [comment]
ok, have installed react-native-webview and updated my code, but the result is still the same.
Image not shown. I use inline html (loaded from Firebase Firestore). And it works on iOS, but Android has an issue displaying the images.

**Comment by udarts** [comment]
I will post this same issue on their issues board as well.

**Comment by baguosiji** [comment]
I also met this problem.
