### ISSUE TITLE
Debug menu show even in release version [iOS]

### ISSUE THREAD

**Issue by PasinduDineth** [facebook/react-native#21983]
I made a react native app and i tried to upload it to appstore today. I followed the official guide and uploaded the app to appstore. Then i tested the app using testflight. But the app is still showing the debug menu and also showing " loading from pre-bundled file".

i have changed the edit schema to release also.  and added 
jsCodeLocation = [[NSBundle mainBundle] URLForResource: @"main" withExtension: @"jsbundle"];
 to AppDelegate.m also.
Can anyone help with this issue?

followed the following link also. But no good. -
https://alexanderpaterson.com/posts/why-is-react-native-launching-from-a-pre-bundled-file

**Comment by inodw1** [comment]
I also have same issue. when i was trying to generate release version. but problem is it is loading from pre-bundled file. please help me!
![img-20181028-wa0005](https://user-images.githubusercontent.com/23226783/47620836-37194800-db15-11e8-925e-187feabd1325.jpg)
