### ISSUE TITLE
[ES6] Conversion problem (getInitialState?)

### ISSUE THREAD

**Issue by tnguyen42** [facebook/react-native#2199]
Hi,
I'm currently trying to convert my code to ES6 and I encountered a problem with initially defining my states.
Before, I had:
```es6
	getInitialState: function() {
		console.log(Orientation);
		return {
			activeSection: {
				title: 'Homepage',
				component: Homepage,
			},
		};
	},

	navigate: function(route) {
		if (this.state.activeSection.component != route.component)
		{
			this.refs.navigator.push(route);
			this.setState({
				activeSection: {
					title: route.title,
					component: route.component,
				},
			});
		}
		this.refs.drawer.close();
	},
```
This perfectly works. I updated it to:
```es6
	constructor(props: any) {
		super(props);
		this.state = {
			activeSection: {
				title: 'Homepage',
				component: Homepage,
			},
		};
	}

	componentDidMount(){
		console.log(this.state.activeSection.component);
  	}

	navigate(route) {
		if (this.state.activeSection.component != route.component)
		{
			this.refs.navigator.push(route);
			this.setState({
				activeSection: {
					title: route.title,
					component: route.component,
				},
			});
		}
		this.refs.drawer.close();
	}
```
But now, even if console.log() correctly displays what it should, the simulator says "undefined is not an object (evaluating this.state.activeSection)".
Am I right to assume getInitialState is deprecated? Is there a reason why console.log() recognize this.state.activeSection in componentDidMount() but not in navigate()? How to solve this?

Another problem is that this.refs.navigator isn't recognized anymore either, so is ref property deprecated in ES6?

Thanks in advance!

**Comment by threepointone** [comment]
Taking a guess here, do you have some code like `onTouch={this.navigate}` in your `render` function? Classes made with React.createClass would autobind all its methods onto `this`, while those made ES6 classes don't. Try adding this line in your `constructor` - `this.navigate = this.navigate.bind(this)`

**Comment by tnguyen42** [comment]
Works perfectly! Thanks a lot!
