### ISSUE TITLE
Plain new project shows Unhandled JS Exception: _typeof3 is not a function

### ISSUE THREAD

**Issue by Val0429** [facebook/react-native#21990]
- [v] Review the documentation: https://facebook.github.io/react-native
  - [v] Search for existing issues: https://github.com/facebook/react-native/issues
  - [v] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.2
      CPU: x64 Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
      Memory: 122.16 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
      Yarn: 1.3.2 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 25.0.0, 25.0.2, 26.0.1, 26.0.2, 27.0.3
        API Levels: 23, 24, 25, 26, 27
    IDEs:
      Android Studio: 2.3 AI-162.4069837
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728 
      react-native: 0.57.4 => 0.57.4 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description
I followed instruction steps to start a new project with react-native v0.57.4.

With everything installed correctly (I've recheck a few times), I create native project with `react-native init MyProject`. but then I got this error after build iOS project:

`Unhandled JS Exception: _typeof3 is not a function
(In '_typeof3(typeof Symbol === "function" ? Symbol.iterator : "@@iterator")',
'_typeof3' is an instance of Object)`

<img width="249" alt="2018-10-29 3 31 11" src="https://user-images.githubusercontent.com/16552067/47637344-586e4880-db96-11e8-8bee-f1497e822638.png">

**Comment by Val0429** [comment]
> Can you run `react-native info` and edit your issue to include these results under the **Environment** section?
> 
> If you believe this information is irrelevant to the reported issue, you may write `[skip envinfo]` under **Environment** to let us know.

I've re-paste `Environment` part including header `React Native Environment Info:`.

**Comment by Val0429** [comment]
Tested with previous version

`react-native init MyProject --version 0.56.1`
no such problem.

**Comment by harrisrobin** [comment]
I'm also running into this. @Val0429 did you end up figuring it out?

**Comment by Val0429** [comment]
@harrisrobin I reinstall babels to version 7,

```
  "devDependencies": {
    "@babel/core": "7.0.0",
    "@babel/plugin-proposal-class-properties": "7.0.0",
    "@babel/plugin-proposal-decorators": "7.0.0",
    "@babel/plugin-proposal-object-rest-spread": "7.0.0",
    "@babel/preset-typescript": "7.0.0",
    "@babel/runtime": "7.0.0",
   }
```

please let me know if that works for you.

**Comment by GuillaumeRZ** [comment]
I have the exact same error... Adding previous dependencies does not resolved the issue...

**Comment by Salakar** [comment]
Hello there 👋 this issue doesn't have a repro (which means, a `react-native init`-ed project with the minimal changes that leads to creating the same issue you are reporting). Unfortunately, I have no way of helping you in a meaningful way without it – there is no easy way for me to recreate the situation and check that the issue reported is still there when changing the code.

Because of this, we are going to close this issue - but if a repro is shared, we are happy to reopen it 🤗

**Comment by KovalM** [comment]
Hi @Val0429 and @GuillaumeRZ! Do you have any progress on this issue?

**Comment by hitesh3001** [comment]
I am facing the same issue. I am using create react native app, and when I run this with expo on web, everything runs fine. But when I run it on android mobile by scanning the bar code, I run into this issue. Can anybody please help me resolve this?
