### ISSUE TITLE
`Animated` play speed with `useNativeDriver` does not change with "Slow Animations" in simulator

### ISSUE THREAD

**Issue by JofBigHealth** [facebook/react-native#22003]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.1.2
  Yarn: 1.7.0
  npm: 5.0.3
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.2 AI-181.5540.7.32.5014246

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4
```

## Description
Expected behaviour when using "Slow Animation" in iOS simulator: animations slow down considerably
Actual behaviour: animation do not slow

`LayoutAnimation` works fine. Some libraries I've worked with such as `react-native-snap-carousel` also work fine (and that one uses `Animated` also)

Note also that it seems to drop frames in high stress situations (i.e. not this demo) as if it were ran on the JS thread. Again, `LayoutAnimation` doesn't have this problem in the same setup.

## Reproducible Demo

1) `create-react-native-app demo`;
2) paste following in the code into App.js;
3) `expo start`
4) Simulator >  Debug > check "Slow Animations"

```
// App.js

import React from 'react';
import { Easing, View, Animated } from 'react-native';

export default class App extends React.Component {
  translateValue = new Animated.Value(0)
  componentDidMount () {
    this.animate()
  }
  animate () {
    this.translateValue.setValue(0)
    Animated.timing(
      this.translateValue,
      {
        toValue: 1,
        duration: 2000,
        easing: Easing.linear,
        useNativeDriver: true
      }
    ).start(() => this.animate())
  }
  render() {
    const translate = this.translateValue.interpolate({
      inputRange: [0, 0.5, 1],
      outputRange: [0, 200, 0],
    })
    return (
      <Animated.View style={{width: 200, height: 200, backgroundColor: "red", transform: [{translateX: translate}]}} />
    );
  }
}
```

```
// package.json
{
  "name": "empty-project-template",
  "main": "node_modules/expo/AppEntry.js",
  "private": true,
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "^30.0.1",
    "react": "16.3.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz"
  }
}
```

NOTE: investigations in my own codebase show `NativeAnimatedHelper.API.startAnimating` is called which I think is expected if `config.useNativeDriver` is working.

**Comment by JofBigHealth** [comment]
Ah... Maybe react-natve-snap-carousel is a bad example since it uses an animated FlatList and the animation we're seeing is the scrolling animation being slowed down... which I assume is 100% native.

**Comment by michalchudziak** [comment]
I'm observing this issue not only with `useNativeDriver`, but also with JS-based animations.

Siimilar JS repro:
```js
import React from 'react';
import { Easing, View, Animated } from 'react-native';

export default class App extends React.Component {
  translateValue = new Animated.Value(0)
  
  componentDidMount () {
    this.animate()
  }

  animate () {
    this.translateValue.setValue(0)
    Animated.timing(
      this.translateValue,
      {
        toValue: 1,
        duration: 200,
        easing: Easing.linear,
      }
    ).start(() => this.animate())
  }

  render() {
    const translate = this.translateValue.interpolate({
      inputRange: [0, 0.5, 1],
      outputRange: [0, 800, 0],
    });
    
    return (
      <Animated.View style={{width: 200, height: translate, backgroundColor: "red"}} />
    );
  }
}
```

**Comment by JofBigHealth** [comment]
@michalchudziak This is expected behaviour I think? (Albeit equally non-ideal)

**Comment by satya164** [comment]
Yea this is the expected behaviour. The workaround is to increase the duration manually.
