### ISSUE TITLE
WebView `onMessage` behaviour is not same in both OS

### ISSUE THREAD

**Issue by jl9404** [facebook/react-native#22001]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
System:
OS: macOS 10.13.1
CPU: x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
Memory: 500.23 MB / 16.00 GB
Shell: 3.2.57 - /bin/zsh
Binaries:
Node: 8.11.4 - /usr/local/bin/node
Yarn: 1.10.1 - /usr/local/bin/yarn
npm: 6.2.0 - /usr/local/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
SDKs:
iOS SDK:
Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
Android SDK:
Build Tools: 23.0.1, 25.0.2, 27.0.3, 28.0.0, 28.0.1
API Levels: 20, 23, 24, 25, 26, 27, 28
IDEs:
Android Studio: 3.1 AI-173.4819257
Xcode: 10.0/10A255 - /usr/bin/xcodebuild
npmPackages:
react: ^16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728
react-native: ^0.57.4 => 0.57.4
npmGlobalPackages:
create-react-native-app: 2.0.2
react-native-cli: 2.0.1
react-native-git-upgrade: 0.2.7

## Description
Android & iOS webview `onMessage` behaviour is not same, iOS will return `baseEvent` but Android wont.

## Reproducible Demo
https://snack.expo.io/@jl9404/webview-demo

**Comment by dulmandakh** [comment]
Please try https://github.com/react-native-community/react-native-webview and file a bug there if you have issues. Thank you
