### ISSUE TITLE
Build worked fine today, reinstalled node_modules => 'React/RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by sryze** [facebook/react-native#22000]
## Environment

Environment:
  OS: macOS High Sierra 10.13.6
  Node: 11.0.0
  Yarn: Not Found
  npm: 6.4.1
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.2 AI-181.5540.7.32.5056338

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

## Description

I can no longer run my project on iOS because of build errors that appeared out of nowhere. I was doing some cleanup and removed node_modules, then reinstalled all the packages with `npm install`. But now the project can't be built, I'm getting the same error every time for various native modules:

```
fatal error: 'React/RCTBridgeModule.h' file not found
```

Both `react-native run-ios` and Xcode give the same result. I literally changed nothing in my project except reinstalling node packages (I'm using Git so I can see that nothing changed).

**Comment by sryze** [comment]
Never mind... Apparently I deleted my Xcode scheme (it was not marked as shared) and my new auto-created scheme wasn't set up properly. It should have the React target before the project target in the build tab.

**Comment by lightninglu10** [comment]
@sryze I'm running into this issue now, what is the scheme you're talking about?

**Comment by sryze** [comment]
In Xcode go to upper left corner -> click on your app name -> Edit Scheme -> Build -> make sure in Targets you have React as your first target, and then your app's target. This tells Xcode to build React Native and all the modules before your project.

![screen shot 2018-11-13 at 15 40 50](https://user-images.githubusercontent.com/4525736/48404508-8dfc5f80-e75a-11e8-8c20-393ed5f039db.png)

**Comment by Kay0806** [comment]
doesn't work
