### ISSUE TITLE
[packager] support browser exclude ("node-module": false)

### ISSUE THREAD

**Issue by mvayngrib** [facebook/react-native#2202]
```json
{
  "browser": {
    "node-module": false
  }
}
```

require('node-module') should return an empty object

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/packager-support-browser-exclude-node-module-false
