### ISSUE TITLE
Run-android does not support launching Activity with different applicationId from package name defined in productFlavor

### ISSUE THREAD

**Issue by dev6james** [facebook/react-native#22022]
> * [x]  Review the documentation: https://facebook.github.io/react-native
> * [x]  Search for existing issues: https://github.com/facebook/react-native/issues
> * [x]  Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
      Memory: 1.51 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.9.1 - ~/.nvm/versions/node/v8.9.1/bin/node
      Yarn: 1.3.2 - ~/.nvm/versions/node/v8.9.1/bin/yarn
      npm: 5.5.1 - ~/.nvm/versions/node/v8.9.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
      Android SDK:
        Build Tools: 19.1.0, 20.0.0, 21.1.2, 22.0.1, 23.0.1, 23.0.2, 23.0.3, 24.0.0, 24.0.1, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.0, 28.0.1
        API Levels: 22, 23, 24, 25, 26, 27, 28
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.4.14 => 16.4.18
      @types/react-native: ^0.57.6 => 0.57.6
      react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728
      react-native: 0.57.3 => 0.57.3
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
      react-native: 0.50.3

## Description
We have the same issue as described here - https://github.com/facebook/react-native/issues/20565

We are using multiple product flavors to set different applicationIds so we can output multiple Android apps from a shared codebase.

If we use `run-android --variant=[flavor name]Debug` it tries to launch the intent with [packageName]/[packageName].MainActivity rather than [applicationId]/[packageName].MainActivity. This means that it fails to find the activity when we use the custom applicationId.

## Reproducible Demo
1. Define multiple product flavors in android/app/build.gradle
2. In one of the product flavors, declare a new applicationId that is different from the package name
3. Write a script that calls `run-android` with the flag `--variant=[flavor name]Debug`.
4. Note that it fails upon trying to start the activity

**Comment by bartolkaruza** [comment]
Moved this issue to the react-native-cli repo

@kelset close

**Comment by grabbou** [comment]
Commented here: https://github.com/react-native-community/react-native-cli/issues/40#issuecomment-447556337 in case any of the participants would like to follow up.
