### ISSUE TITLE
[FEATURE] Add docs for deploy react native fork to npm

### ISSUE THREAD

**Issue by gengjiawen** [facebook/react-native#22030]
Enable this will let community to make patch or share feature easily.

Related issue: 
https://github.com/facebook/react-native/issues/21776
https://github.com/facebook/react-native/issues/21967

cc @kelset

**Comment by IljaDaderko** [comment]
As far as I know npm can also install directly from github url, we might just need section in README or docs website that explains how to correctly build forked files.

@hramos posted these https://github.com/facebook/react-native/issues/21967#issuecomment-434113687 in one of the issues you mentioned, so thats renderer bit I guess.

**Comment by bartolkaruza** [comment]
Github dependency in package.json works fine if you commit the Android binary from [`installArchives`](https://facebook.github.io/react-native/docs/building-from-source#building-for-maven-nexus-deployment). The build output is in the [.gitignore](https://github.com/facebook/react-native/blob/580377201793314ca643250c1bd7cf1c47d49920/.gitignore#L30), but if you remove that line you can commit the build on your branch, which then works as a Github dependency. NPM or Maven dependencies for forks require much more effort (imho), which is not worth it considering the fork should be short lived.

**Comment by kelset** [comment]
This to me seems more like an issue for the https://github.com/facebook/react-native-website repo.
