### ISSUE TITLE
Multiple nested images in a <Text> causes ANR

### ISSUE THREAD

**Issue by enahum** [facebook/react-native#22038]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
      Memory: 408.56 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.11.0 - ~/.nvm/versions/node/v10.11.0/bin/node
      npm: 6.4.1 - ~/.nvm/versions/node/v10.11.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
      Android SDK:
        Build Tools: 23.0.1, 23.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 27.0.3, 28.0.0, 28.0.2
        API Levels: 23, 24, 25, 26, 27, 28
    IDEs:
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.1 => 16.5.1 
      react-native: 0.57.1 => 0.57.1 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

## Description
Android: when adding multiple images as children to a <Text> the app becomes unresponsive as in the UI gets totally blocked and after a short while android reports the app as ANR, it can happen after adding 30+ images, in our case is to display emoji's  in a sentence like this one: "trying to render multiple emojis in a text 👍 👍 ...." this obviously also happens with any type of inline images.

I'm not a java developer but perhaps something to do with `ReactTextInlineImageShadowNode`

This is part of the markdown implementation that we have in our app https://github.com/mattermost/mattermost-mobile/blob/master/app/components/markdown/markdown.js#L252

If we remove the <Text> wrapper then the images are all displayed and the app is totally responsive, this issue is Android only as iOS works just fine no matter the amount of nested images

## Reproducible Demo
https://github.com/mattermost/mattermost-mobile/blob/master/app/components/markdown/markdown.js#L252

**Comment by shermdog** [comment]
Updating the linked code @enahum posted as that blob has changed:  https://github.com/mattermost/mattermost-mobile/blob/78e5b99884528b1243b5ff6668660f2ecab4d063/app/components/markdown/markdown.js#L252-L254
