### ISSUE TITLE
[Packager] Unable to resolve module ./base64-vlq

### ISSUE THREAD

**Issue by Dave93** [facebook/react-native#2204]
Hi everyone.
Could someone help with this issue?
When app launches there are errors in packager.
```
Unable to resolve module ./base64-vlq from /private/var/root/Desktop/iBiznesApp/node_modules/react-native-router/node_modules/react-native/Libraries/JavaScriptAppEngine/Initialization/SourceMap.js
Unable to resolve module ./util from /private/var/root/Desktop/iBiznesApp/node_modules/react-native-router/node_modules/react-native/Libraries/JavaScriptAppEngine/Initialization/SourceMap.js
Unable to resolve module ./array-set from /private/var/root/Desktop/iBiznesApp/node_modules/react-native-router/node_modules/react-native/Libraries/JavaScriptAppEngine/Initialization/SourceMap.js
Unable to resolve module ./base64 from /private/var/root/Desktop/iBiznesApp/node_modules/react-native-router/node_modules/react-native/Libraries/JavaScriptAppEngine/Initialization/SourceMap.js
Unable to resolve module ./util from /private/var/root/Desktop/iBiznesApp/node_modules/react-native-router/node_modules/react-native/Libraries/JavaScriptAppEngine/Initialization/SourceMap.js
...
```
Therefore app simulator shows such error: "RCTExceptionsManager.reportFatalException was called with 2 arguments, but expects 3"
When i init new app and work with this app immediately it works fine.
But when I restart mac end launch app i have such errors.
Please, help me with this issue. I can't solve this myself.

**Comment by ahanriat** [comment]
I've got the same issue with the 0.9.0-rc, I'll let you know if I fix this :wink:

**Comment by ahanriat** [comment]
@Dave93 I've cloned my repo in a clean env, deleted my `node_modules`, updated react to 0.9.0-rc, run `npm install && npm start`, launched Xcode and everything is OK. I'm pretty sure the issue came from Xcode.. so check your `.gitignore`

Hope this helps !

**Comment by ahanriat** [comment]
@Dave93 for me it works fine when I remove the `"react-native-grid-view"` from the package.json

**Comment by Dave93** [comment]
Thanks. I'll try to delete something from package.json

**Comment by alejomendoza** [comment]
+1

**Comment by alejomendoza** [comment]
Making sure there aren't old react versions in dependencies solved it for me. https://github.com/facebook/react-native/issues/1606

**Comment by vitalbone** [comment]
I was able to resolve this by switching to the latest version of iojs, reinstalling node_modules and reverting to react-native v0.9.0

```
nvm use iojs-v3.2.0
rm -rf node_modules
npm i
rm -rf node_modules/react-native
npm i react-native@0.9.0
```

**Comment by browniefed** [comment]
@brentvatne seems like this can be closed now/ consolidated into https://github.com/facebook/react-native/issues/1606 especially with the packager being split out to a separate repo.
