### ISSUE TITLE
How can I disable touch screen when loading ActivityIndicator ?

### ISSUE THREAD

**Issue by huynguyen2903** [facebook/react-native#22054]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
[skip envinfo]
react: 16.4.1 => 16.4.1
      react-native: 0.56.0 => 0.56.0

## Description
I want to disable touch screen when loading (I use ActivityIndicator). I put pointerEvents = {'none} but it's not working. Can you give me a solution about this ?
```
 import React from "react";
import { TouchableWithoutFeedback, View, ActivityIndicator } from "react-native";
import Colors from "../../resources/colors/Colors";

const AppProgress = () => (
    <View pointerEvents={"none"}
      style={{
        width: "100%",
        height: "100%",
        backgroundColor: Colors.dimBlack,
        position: "absolute",
        alignSelf: "center",
        justifyContent: "center",
        alignItems: "center"
      }}>
      <ActivityIndicator size="large" color={Colors.green}/>
    </View>
);

export default AppProgress;
```

## Reproducible Demo
Let us know how to reproduce the issue. Include a code sample, share a project, or     share an app that reproduces the issue using https://snack.expo.io/. Please follow the guidelines for providing a MCVE: https://stackoverflow.com/help/mcve

**Comment by osamausmani** [comment]
How to again active the touchability[.](https://topinforma.com)?
