### ISSUE TITLE
Cannot change color of ActivityIndicator on iphone5c

### ISSUE THREAD

**Issue by jinxac** [facebook/react-native#22055]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```

  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5 CPU       M 540  @ 2.53GHz
      Memory: 48.68 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 9.10.0 - /usr/local/bin/node
      Yarn: 1.3.2 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
      Android SDK:
        Build Tools: 23.0.1, 23.0.2, 23.0.3, 24.0.0, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.3
        API Levels: 23, 24, 25, 26, 27
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728
      react-native: 0.57.3 => 0.57.3
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-create-library: 3.1.2
      react-native-git-upgrade: 0.2.7
      react-native-rename: 2.2.2
```

## Description
I recently upgraded from react-native `0.48.3` to react-native `0.57.3`. After upgrade `ActivityIndicator` is not reflecting the colour I pass as props. It is taking default colour which is `GRAY`.  This is happening only on iPhone 5c.  I tried checking on other models using simulator and it works fine over there.

Here is the common code which I am using for my application :- 

```
const WealthyActivityIndicator = function ({style, color}) {
  return (
    <ActivityIndicator
      animating
      color={color || "blue"}
      style={[styles.loader, style]}
    />
  );
};
```

We still have clients on this particular model of iPhone so wanted to get it working on this. Can someone please tell why is this breaking and how to fix it? TIA

**Comment by toupilsner** [comment]
I have the same issue on Iphone 5 as well

**Comment by ivanguimam** [comment]
Suffering from this in the version 0.57.8
