### ISSUE TITLE
Ability to obtain reference to native control

### ISSUE THREAD

**Issue by akaila** [facebook/react-native#2206]
Hi all,

I think refs should extend back to native code. Here is a scenario: I am trying to take a screenshot of a listview that I want to render atop the actual control while I animate icons in a different frame. I have defined a native manager and a view derivative that I inject in the UI and was trying to obtain the reference of source list view via refs. However it does not seem possible and for now I get a nil reference when I try to call: bridge.uiManager viewForReactTag:

Can someone shed some light on such scenarios where in native code one needs to cross collaborate with controls? If not, can this be assumed a feature request?

Thanks
Ashish

**Comment by brentvatne** [comment]
Hi there,

You're probably better off asking this question in IRC/Slack, StackOverflow or on Twitter :) I'm not personally familiar with how to do this but you will probably find qualified people in one of those! Sorry for the terrible response, good luck!

**Comment by grittymindy** [comment]
@akaila did you find a solution? I'm having this problem now.

**Comment by akaila** [comment]
Yes the solution is to pass the ref to the view manager using React.findNodeHandle(this.refs.myView) and then in the native module lookup the control using view registry. Here is a relevant snippet: http://stackoverflow.com/questions/31857583/how-to-access-native-ui-components-instance-methods-in-react-native

**Comment by erickreutz** [comment]
How would you accomplish this same thing with Android?

**Comment by Kennytian** [comment]
How would you accomplish this same thing with Android? +1   

View view =  currentActivity.findViewById(reactTag); //reactTag 625
but findViewById,  view is NULL

**Comment by rotemmiz** [comment]
The only way of doing it currently is by adding a `UIBlock` to `UIManagerModule`.

```
UIManagerModule uiManager = context.getNativeModule(UIManagerModule.class);
        uiManager.addUIBlock(new UIBlock() {
            @Override
            public void execute(NativeViewHierarchyManager nativeViewHierarchyManager) {
                view = nativeViewHierarchyManager.resolveView(reactTag);
            }
        });
```

**Comment by Sean-Snow** [comment]
@rotemmiz  i use UIBlock on RN 0.45.1 with android .the  nativeViewHierarchyManager always null,
I need to do？

**Comment by ivanzotov** [comment]
If it helps someone, I had findViewById returned null and @rotemmiz 's solution works for me – https://github.com/ivanzotov/react-native-text-input-mask/blob/master/android/src/main/java/com/RNTextInputMask/RNTextInputMaskModule.java#L59
