### ISSUE TITLE
"Set-Cookie" contains only last item

### ISSUE THREAD

**Issue by dakiesse** [facebook/react-native#22064]
## Environment
  ```
React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 65.45 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.0.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        Build Tools: 25.0.0, 26.0.3, 27.0.3
        API Levels: 23, 25, 26, 27
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728
      react-native: 0.57.4 => 0.57.4
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-create-library: 3.1.2
```

## Description
My backend send a response with several "Set-Cookie":
```
some1=value1
some2=value2
```
If I make a request to endpoint via Postman I'll get this:

![image](https://user-images.githubusercontent.com/5033716/47860616-9b7c2600-ddf9-11e8-9b18-ae5f47e6ac20.png)

That's OK!

If I make the request through React Native I'll get only last "Set-Cookie" in the response:

![image](https://user-images.githubusercontent.com/5033716/47860766-04fc3480-ddfa-11e8-93b4-c1e07d508422.png)

I made requests via `xmlHttpRequest` and `fetch`. The result is the same.

## Reproducible Demo
New project + append the code there:
```
export default class App extends Component<Props> {
  async componentDidMount() {
    const response = await fetch('http://localhost:3333/test')

    console.warn({fh: response.headers})
  }
}
```

**Comment by hey99xx** [comment]
If this is only happening on Android it's the same as https://github.com/facebook/react-native/issues/18837 and https://github.com/facebook/react-native/issues/21795.

RN has a bug in their `ReadableMap` class that's causing this. Current workaround people have until an official fix is made is calling `ReadableNativeMap.setUseNativeAccessor(true)` on the Java side, see the comments on those 2 issues for details.

**Comment by kelset** [comment]
Duplicate, closing.
