### ISSUE TITLE
Bracket/Comments placement seems to create "Text Strings must be rendered within a </Text> component" error

### ISSUE THREAD

**Issue by donatelucas** [facebook/react-native#22068]
## Images
[Code](https://www.dropbox.com/s/5580u151wibxakk/notWorking.jpg?dl=0)
[Error](https://www.dropbox.com/s/5kzplcs16wfr7rm/image.png?dl=0)

## Environment
  `React Native Environment Info:
    System:
      OS: Windows 10
      CPU: x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
      Memory: 1.39 GB / 7.90 GB
    Binaries:
      npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD`

## Description
Like the title says, I have an user that is doing the React Native tutorials, and when doing the Props one, when she copied the file from the site, it creates that error, the environment above is her environment. I tried to replicate the error on my machine by following the same procedure without any success.

## Reproducible Demo
A demo wasn't provided, unfortunately, just the print screens and the steps followed to get to it.

**Comment by bartolkaruza** [comment]
The comment in the JSX needs to be wrapped in curly braces: https://wesbos.com/react-jsx-comments/

**Comment by donatelucas** [comment]
Thanks!
