### ISSUE TITLE
iOS Keyboard Shortcut rapid double tap space for period

### ISSUE THREAD

**Issue by Kielan** [facebook/react-native#22078]
I want to start this discussion regarding react native's plans for this keyboard shortcut UX feature, is there the possibility of a 3rd party solution in the form of a package to insert this setting, or does some feature of the native bridge api need to be configured to read this native setting. Can this be implemented in a future version of react native and what are the current blockages?

![keyboardshortcut](https://user-images.githubusercontent.com/4452059/47907173-f2105100-de47-11e8-92bf-26a29849e84b.jpg)

**Comment by Kielan** [comment]
interestingly, I notice that this feature is respected, but in typescript if you use the wrong syntax, such as js constructor syntax, the double tap is not respected. Very interesting case.

**Comment by mhoran** [comment]
Hey @Kielan, did you find another solution to this issue other than setting multi line to true? I'd like the double tap for period behavior in my app, but the desired field does not need to be multi line.
