### ISSUE TITLE
真机设备上三指截屏事件

### ISSUE THREAD

**Issue by MickeyMouse623** [facebook/react-native#22075]
- [ ] Review the documentation: https://facebook.github.io/react-native
  - [ ] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```javascript
D:\work\demo>react-native info

  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
      Memory: 1.46 GB / 7.64 GB
    Binaries:
      Yarn: 1.7.0 - C:\Users\admin\AppData\Roaming\npm\yarn.CMD
      npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD
```

## Description
在 `小米` 设备上使用 `3指截屏` 时，出现这个错误。任何一个页面，无关代码和环境

## Reproducible Demo
![image](https://user-images.githubusercontent.com/18524460/47898815-68e23400-deb2-11e8-9548-c3d73f14f8df.png)

**Comment by zenz** [comment]
Confirm this issue. I'm using Mi Mix 2

**Comment by BruceeWang** [comment]
I dont think everyone is chinese,decription this issuse with English

**Comment by zenz** [comment]
@BruceeWang you are right.

While using 3fingers gesture to capture the screen on some Mi Phone, it will cause this problem.

**Comment by MickeyMouse623** [comment]
@zenz I'm using Mi5, Android 8.0,

```javascript
  "dependencies": {
    "@babel/runtime": "^7.1.2",
    "antd-mobile-rn": "^2.2.1",
    "axios": "^0.18.0",
    "jsencrypt": "^3.0.0-rc.1",
    "react": "16.6.0-alpha.8af6728",
    "react-native": "0.57.1",
    "react-native-image-crop-picker": "^0.21.2",
    "react-native-linear-gradient": "^2.4.2",
    "react-native-modal-datetime-picker": "^6.0.0",
    "react-native-swiper": "^1.5.13",
    "react-native-vector-icons": "^6.0.2",
    "react-navigation": "^2.17.0",
    "react-redux": "^5.1.0",
    "redux": "^4.0.1",
    "redux-persist": "^5.10.0",
    "redux-promise": "^0.6.0",
    "redux-thunk": "^2.3.0"
  },
```
