### ISSUE TITLE
YellowBoxButton css-problem in iOS 12.0 and above

### ISSUE THREAD

**Issue by folofse** [facebook/react-native#22079]
## Environment
React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
      Memory: 383.21 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.9.3 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        Build Tools: 23.0.1, 25.0.2, 27.0.3, 28.0.0, 28.0.1
        API Levels: 20, 23, 24, 25, 26, 27, 28
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.6.0-alpha.8af6728 => 16.6.0
      react-native: ^0.57.4 => 0.57.4
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

## Description
YellowBoxButton causes following css-error

Invalid prop `includeFontPadding` of type `number` supplied to `StyleSheet label`, expected `boolean`.
StyleSheet label: {
  "color": "rgba(255, 255, 255, 1)",
  "fontSize": 14.5,
  "includeFontPadding": 0,
  "lineHeight": 19
}

## Reproducible Demo
No available

**Comment by bartolkaruza** [comment]
The code looks to be OK on the `YellowBoxButton` [component](https://github.com/facebook/react-native/blob/adc8a33fcfeb8fc163f48ae4a4bc5aaac98bcb0d/Libraries/YellowBox/UI/YellowBoxButton.js#L48). Is this a react-native init based project? Do you get this when you create a new empty app using react-native init?

**Comment by hramos** [comment]
The title implies this does not occur on iOS 11, but the description does not address this. Can you clarify what's the case?

**Comment by folofse** [comment]
I'm trying to figure out what's causing the problem. It seems to be something else that fails before and later causes this error, so I close this until I figure out what the underlying problem is.
