### ISSUE TITLE
Unable to load script from assets 'index.android.bundle'. Make sure your bundle is packaged correctly or you're running a packager server. App crash in release build only

### ISSUE THREAD

**Issue by naody** [facebook/react-native#22076]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
Done in 2.05s. - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
      Android SDK:
        Build Tools: 23.0.1, 23.0.2, 23.0.3, 24.0.2, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 27.0.3, 28.0.0, 28.0.2, 28.0.3
        API Levels: 22, 23, 24, 25, 26, 27, 28
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0
      react-native: 0.57.1 => 0.57.1
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
```
## Description
I get the error below on release builds.  I don't see the issue in my dev environment i.e. `react-native run-android`. I installed the apk on my Pixle 2 XL - Android Pi and the app immediately crashes. I got the error below from my Firebase console (Crashlytics)
```
Fatal Exception: java.lang.RuntimeException: Unable to load script from assets 'index.android.bundle'. Make sure your bundle is packaged correctly or you're running a packager server.
       at com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromAssets(CatalystInstanceImpl.java)
       at com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromAssets(CatalystInstanceImpl.java:216)
       at com.facebook.react.bridge.JSBundleLoader$1.loadScript(JSBundleLoader.java:32)
       at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:243)
       at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1114)
       at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:116)
       at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:913)
       at java.lang.Thread.run(Thread.java:764)
```
## Reproducible Demo
Let us know how to reproduce the issue. Include a code sample, share a project, or     share an app that reproduces the issue using https://snack.expo.io/. Please follow the guidelines for providing a MCVE: https://stackoverflow.com/help/mcve

**Comment by vafada** [comment]
@naody 

Did you happen to upgrade gradle version?

I got the same issue when I upgraded:

`classpath 'com.android.tools.build:gradle:3.2.1'`

from

`classpath 'com.android.tools.build:gradle:3.1.4'

and

`distributionUrl=https\://services.gradle.org/distributions/gradle-4.6-all.zip`

from

`distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip`

**Comment by sinhpn92** [comment]
I have same issue when upgrade into latest version: 
`classpath 'com.android.tools.build:gradle:3.2.1'`
`distributionUrl=https\://services.gradle.org/distributions/gradle-4.6-all.zip`

**Comment by sryze** [comment]
It seems like an old problem...

https://stackoverflow.com/questions/44446523/unable-to-load-script-from-assets-index-android-bundle-on-windows

**Comment by sryze** [comment]
I was able to reproduce this bug by simply creating a new app:

1. react-native init TestApp
2. Open TestApp/android in Android Studio
3. Run the project on an emulator

**Comment by sryze** [comment]
For some reason I had `import com.facebook.react.BuildConfig;` in my MainAplication file, and therefore `BuildConfig.DEBUG` was set to false. Because of this:

```
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }
```

React Native was always trying to load index.android.bundle from the app pacakge, not from the dev server. Removing the `import com.facebook.react.BuildConfig` line fixed the issue for me 🎆 🍺 👍

**Comment by IgorBelyayev** [comment]
This worked for me:
https://github.com/facebook/react-native/issues/18357#issuecomment-460015070

In `app/build.gradle`

Add:
```
project.ext.react = [
    entryFile: "index.js",
    jsBundleDirRelease: "$buildDir/intermediates/merged_assets/release/mergeReleaseAssets/out"
]
```

Above the line:
```
apply from: "../../node_modules/react-native/react.gradle"
```

**Comment by deserthurricane** [comment]
I had this issue only on Mac OS and only while trying to build for Android. It started to happen after my update from RN 0.57 to 0.59.

To understand what is going on I started a new RN project and compared differences with my project. I noticed that there is a new folder in the new project - android/app/src/debug. And there is only one file in this folder - AndroidManifest.xml with the following contents:
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools">

    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>

    <application android:usesCleartextTraffic="true" tools:targetApi="28" tools:ignore="GoogleAppIndexingWarning" />
</manifest>
```
After adding this file to my old project Metro Bundler started working for Android as expected.

**Comment by vinnyhoward** [comment]
For me this combination worked using `"react-native": "0.59.4"`
- `distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip`
- in root `build.gradle` use `classpath 'com.android.tools.build:gradle:3.3.0'`
- in app `build.gradle` I have:

```
project.ext.react = [
        entryFile: "index.js",
        bundleAssetName: "index.android.bundle",
        bundleInAlpha: true,
        bundleInBeta: true
]
```
right above `apply from: "../../node_modules/react-native/react.gradle"`

**Comment by luizdotpro** [comment]
Thank you @vinnyhoward ! That worked perfectly for me.

**Comment by ajbarry** [comment]
Seriously @vinnyhoward Thank you! My release apk has been broken for days and I have been trying everything to get it to include the bundle. Android Studio "strongly recommends" upgrading gradle to 5.1.1 and it looks like that was my problem after all. Cheers! 🍻

**Comment by robertying** [comment]
It turned out to be a problem of `gradle plugin`

Use 3.3.* instead of 3.4.* works for me:

```
classpath 'com.android.tools.build:gradle:3.3.2'
```

I still use gradle 5.4.1. This does not cause the problem, though.

**Comment by MuhammadUsman786786** [comment]
@vinnyhoward answer works for me.

**Comment by buskerone** [comment]
@vinnyhoward solution works for me! Thanks

**Comment by cbsom** [comment]
@vinnyhoward solution works for me as well. 
This saved the few remaining hairs on my head.
No need to change distributionUrl though, gradle-5.1.1-all.zip worked fine.

**Comment by MakhouT** [comment]
@vinnyhoward That worked for me too. 
As @cbsom said, no need to change the distributionUrl
Took me a day to find this.

**Comment by Christopotamus** [comment]
@deserthurricane This worked for me, also going from ~57 to 59. I missed this step in my diff upgrade!

**Comment by aliazizi** [comment]
When I change gradle to `3.4` 
this issue should be repon

**Comment by wkmcyz** [comment]
For my project using react-native `0.57.0`, it is because I upgraded my Android gradle plugin from `3.1.4` to `3.4.1` to enable androidx support libraries. And the new gradle plugin uses a different intermidiate directory for assets, but the `react.gradle` copies the js bundle into the old directory.

So it builds with js bundle in assets after I changed the `react.gradle` as below.
```
// change currentAssetsCopyTask to below.
        def currentAssetsCopyTask = tasks.create(
            name: "copy${targetName}BundledJs",
            type: Copy) {
            group = "react"
            description = "copy bundled JS into ${targetName}."


             // Workaround for Android Gradle Plugin 3.4.1, new asset directory
            from jsBundleDir
            into file(config."jsBundleDir${targetName}" ?:
                "$buildDir/intermediates/merged_assets/${variant.name}/out")


            // mergeAssets must run first, as it clears the intermediates directory
            dependsOn(variant.mergeAssets)

            enabled currentBundleTask.enabled
        }


```

you can replace the new asset dir with the one your gradle plugin uses if it is not the same(for me it is ` "$buildDir/intermediates/merged_assets/${variant.name}/out"`). You can find it as following.
1. add any file like `a.a` to your `asset` directory.
2. run `./gradlew assembleDebug`
3. find `a.a` in `./app/build/intermidiates` folder. The folder contains `a.a` is the intermidiate directory for asset files, change the destination dir in `react.gradle ` to it.

**Comment by HeffZilla** [comment]
> For some reason I had `import com.facebook.react.BuildConfig;` in my MainAplication file (I guess due to some smart ass auto import fixing feature of IntelliJ), and therefore `BuildConfig.DEBUG` was set to false. Because of this:
> 
> ```
>     public boolean getUseDeveloperSupport() {
>       return BuildConfig.DEBUG;
>     }
> ```
> 
> React Native was always trying to load index.android.bundle from the app pacakge, not from the dev server. Removing the `import com.facebook.react.BuildConfig` line fixed the issue for me 🎆 🍺 👍

This worked for me :)
