### ISSUE TITLE
The development server returned response error code: 500. Cannot find module @babel/core

### ISSUE THREAD

**Issue by robrousejr** [facebook/react-native#22074]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
React Native Environment Info:
    System:
      OS: Windows 10
      CPU: x64 Intel(R) Core(TM) i7-6560U CPU @ 2.20GHz
      Memory: 1.66 GB / 7.85 GB
    Binaries:
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.1.0.0 AI-173.4819257

## Description

It's been one error after another, and it all has to do with @babel/core. 
I've tried doing 

> npm add @babel/core

but it doesn't make any difference sadly. 
Here is a picture of the full error: 
![screenshot_20181102-004539_test](https://user-images.githubusercontent.com/24664708/47894408-0f89ee80-de39-11e8-8f80-792c14e4f270.jpg)

## Reproducible Demo

I've not done anything to the code at all. This is just an issue of trying to get react-native setup properly on my computer.

**Comment by bartolkaruza** [comment]
Can you post your dependencies and devDependencies sections of your package.json?

**Comment by robrousejr** [comment]
> Can you post your dependencies and devDependencies sections of your package.json?

Yes! I'm not sure where to find the devDependencies though
```
  "bundleDependencies": false,
  "dependencies": {
    "chalk": "^1.1.1",
    "minimist": "^1.2.0",
    "prompt": "^0.2.14",
    "semver": "^5.0.3"
  },
```

**Comment by bartolkaruza** [comment]
That doesn't look like a `react-native` project package.json to me. Are you sure that's the right file? It should include ```"react-native": "0.57.0"``` at the least.

**Comment by robrousejr** [comment]
> That doesn't look like a `react-native` project package.json to me. Are you sure that's the right file? It should include `"react-native": "0.57.0"` at the least.

Sorry I gave you the `node_modules` package.json, oddly enough, my `react-native` one is kind've bare. Here it is --> 
`{
  "name": "test",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "jest": {
    "preset": "react-native"
  }
}`

**Comment by bartolkaruza** [comment]
This is the package.json output if I run `react-native init rntemplate`:

```
{
  "name": "rntemplate",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.6.0-alpha.8af6728",
    "react-native": "0.57.4"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.49.0",
    "react-test-renderer": "16.6.0-alpha.8af6728"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

What command did you use to initialize the project? Some essential bits appear to be missing  from your package.json.

**Comment by robrousejr** [comment]
> This is the package.json output if I run `react-native init rntemplate`:
> 
> ```
> {
>   "name": "rntemplate",
>   "version": "0.0.1",
>   "private": true,
>   "scripts": {
>     "start": "node node_modules/react-native/local-cli/cli.js start",
>     "test": "jest"
>   },
>   "dependencies": {
>     "react": "16.6.0-alpha.8af6728",
>     "react-native": "0.57.4"
>   },
>   "devDependencies": {
>     "babel-jest": "23.6.0",
>     "jest": "23.6.0",
>     "metro-react-native-babel-preset": "0.49.0",
>     "react-test-renderer": "16.6.0-alpha.8af6728"
>   },
>   "jest": {
>     "preset": "react-native"
>   }
> }
> ```
> What command did you use to initialize the project? Some essential bits appear to be missing from your package.json.

That's very strange... I used `react-native init test`, and I just created a new project and again got the same `package.json` file

**Comment by robrousejr** [comment]
Got it fixed! Had to install **yarn**, once I did that, for some reason it started working
