### ISSUE TITLE
0.57.4 navigator issuse

### ISSUE THREAD

**Issue by BruceeWang** [facebook/react-native#22077]
Environment:
OS: macOS 
Android Studio: 3.1 AI-173.4697961.
webstorm:2018 

Description
I want to use navigator to start other view and I look the official document,I have issue. 
this is my files.(sorry,I am not good at English)

AppDetail.js

export default class AppDetails extends Component {
    constructor(props) {
        super(props);
        this._pressButton = this._pressButton.bind(this);
    }

    _pressButton() {
        this.pixel = Platform.OS === "ios" ? 1 : PixelRatio.get();
        const {navigator} = this.props;
        console.log('this is some  '+navigator);
    }
  
   render{
ignore.........
.................................
}

index.android.js

/** @format */

import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';
import {createStackNavigator} from "react-navigation";
import HomeScreen from './App'
import Details from './Detail'
import AppDetails from './App'
import Detail from './Detail'
import React, {Component} from 'react';
import {StackNavigator}  from 'react-navigation';
import {Navigator} from "react-native-deprecated-custom-components";
AppRegistry.registerComponent(appName, () => App);

export default class Test extends Component{

    render() {
        return (
            <Navigator
                initialRoute={{name:'AppDetails',component:AppDetails}}
                configureScene={()=>{
                    return Navigator.SceneConfigs.PushFromRight;
                }}
                renderScene={(route, navigator) => {
                    let Component = route.component;
                    return <Component {...route.props} navigator={navigator} />
                }}
            />
        );
    }
}

The android log is " const {navigator} = this.props
        console.log('this is some  '+navigator)"
  navigator is [object object].
so, I cant use method navigator.push.how to i find out this navigator.
 "react-native": "0.57.4",this is that my base on version
.

**Comment by bartolkaruza** [comment]
There is no `Navigator` in the React Native core codebase: https://facebook.github.io/react-native/docs/navigator.html

I see you also have the `react-navigation` dependency. `react-navigation` is a separate navigation library with it's own [website](https://reactnavigation.org/) containing all the documentation you need to get going. You don't need the `react-native-deprecated-custom-components` if your are using `react-navigation`.

**Comment by BruceeWang** [comment]
> There is no `Navigator` in the React Native core codebase: https://facebook.github.io/react-native/docs/navigator.html
> 
> I see you also have the `react-navigation` dependency. `react-navigation` is a separate navigation library with it's own [website](https://reactnavigation.org/) containing all the documentation you need to get going. You don't need the `react-native-deprecated-custom-components` if your are using `react-navigation`.

your mean is that I should use this exmaple,but it is the same issuse as that.

 
const RootStack = createStackNavigator({
    Home: { screen: HomeScreen },
    Profile: { screen: ProfileScreen },
});
 export default RootStack;

I try two method,and i get the same issuse.

**Comment by BruceeWang** [comment]
> There is no `Navigator` in the React Native core codebase: https://facebook.github.io/react-native/docs/navigator.html
> 
> I see you also have the `react-navigation` dependency. `react-navigation` is a separate navigation library with it's own [website](https://reactnavigation.org/) containing all the documentation you need to get going. You don't need the `react-native-deprecated-custom-components` if your are using `react-navigation`.

next day is my weekend,i want to have a rest.I probably will not read your reply immediately,I will read your reply on next Monday.
