### ISSUE TITLE
Picker.Item missing testID

### ISSUE THREAD

**Issue by robertofrontado** [facebook/react-native#22084]
## Environment
```
React Native Environment Info:
System:
  OS: macOS High Sierra 10.13.6
  CPU: x64 Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz
  Memory: 82.27 MB / 8.00 GB
  Shell: 3.2.57 - /bin/bash
Binaries:
  Node: 8.11.3 - /usr/local/bin/node
  npm: 5.6.0 - /usr/local/bin/npm
SDKs:
  iOS SDK:
    Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
IDEs:
  Xcode: 10.0/10A255 - /usr/bin/xcodebuild
npmPackages:
  react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728
  react-native: 0.57.4 => 0.57.4
npmGlobalPackages:
  react-native-cli: 2.0.1
  react-native-git-upgrade: 0.2.7
```

## Description
As you can see `PickerIOS.Item` does not have a `testID`, even though `Picker.Item` does.

[Picker](https://github.com/facebook/react-native/blob/0ee23d0beb96180161ca6627ea03852f55ef0b29/Libraries/Components/Picker/Picker.js#L25-L47)
```js
type PickerItemProps = $ReadOnly<{|
  /**
   * Text to display for this item.
   */
  label: string,

  /**
   * The value to be passed to picker's `onValueChange` callback when
   * this item is selected. Can be a string or an integer.
   */
  value?: any,

  /**
   * Color of this item's text.
   * @platform android
   */
  color?: ColorValue,

  /**
   * Used to locate the item in end-to-end tests.
   */
  testID?: string,
|}>;
```
[PickerIOS](https://github.com/facebook/react-native/blob/1151c096dab17e5d9a6ac05b61aacecd4305f3db/Libraries/Components/Picker/PickerIOS.ios.js#L74-L78)
```js
type ItemProps = $ReadOnly<{|
  label: ?Label,
  value?: ?any,
  color?: ?ColorValue,
|}>;
```

So I can't find the `Items` using [Detox](https://github.com/wix/Detox)

**Comment by vonovak** [comment]
hi, why not just use `Picker`? It's the same thing as PickerIOS on ios...

**Comment by robertofrontado** [comment]
I'm using `Picker`, which relies on `PickerIOS`

**Comment by vonovak** [comment]
ah, I see. It wasn't clear from the description. You can match the item by text for now, just fyi.

**Comment by robertofrontado** [comment]
Yeah I'm aware, but the text might change since its coming from an API :/

**Comment by thymikee** [comment]
Thanks! `Picker` is moving to a community repo, I moved the issue there: https://github.com/react-native-community/react-native-picker/issues/8
