### ISSUE TITLE
React Native "GET /onchange HTTP/1.1" - - "-" "okhttp/3.6.0" log after react-native update

### ISSUE THREAD

**Issue by panda0603** [facebook/react-native#22095]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
[skip envinfo]

## Description
I've just updated from react native version 0.55 to 0.57. 

After I start the project, 

I keep on getting this log 

> [20:04:52] ::ffff:(IP address) - - [03/Nov/2018:11:04:52 +0000] "GET /onchange HTTP/1.1" - - "-" "okhttp/3.6.0"
> 
> [20:05:02] ::ffff:(IP address) - - [03/Nov/2018:11:05:02 +0000] "GET /onchange HTTP/1.1" - - "-" "okhttp/3.6.0"
> 
> [20:05:13] ::ffff:(IP address) - - [03/Nov/2018:11:05:13 +0000] "GET /onchange HTTP/1.1" - - "-" "okhttp/3.6.0"
> 
> [20:05:23] ::ffff:(IP address) - - [03/Nov/2018:11:05:23 +0000] "GET /onchange HTTP/1.1" - - "-" "okhttp/3.6.0"
> 
> [20:05:33] ::ffff:(IP address) - - [03/Nov/2018:11:05:33 +0000] "GET /onchange HTTP/1.1" - - "-" "okhttp/3.6.0"

on console.log every 10 seconds. The project works fine though. What is this and why is this outputted on the console log? can i disable it?

p.s. I'm using expo-cli. Could this be expo issue?

**Comment by Hermanyo** [comment]
I'm face this issue too, when I downgrade to 0.55.4, all works again

**Comment by soooji** [comment]
Me too. Is there any solution? I hate downgrade.

**Comment by aminnoura** [comment]
I have the same issue....

**Comment by enanda** [comment]
same here

**Comment by panda0603** [comment]
> * [x]  Review the documentation: https://facebook.github.io/react-native
> * [x]  Search for existing issues: https://github.com/facebook/react-native/issues
> * [x]  Use the latest React Native release: https://github.com/facebook/react-native/releases
> 
> ## Environment
> [skip envinfo]
> 
> ## Description
> I've just updated from react native version 0.55 to 0.57.
> 
> After I start the project,
> 
> I keep on getting this log
> 
> > [20:04:52] ::ffff:(IP address) - - [03/Nov/2018:11:04:52 +0000] "GET /onchange HTTP/1.1" - - "-" "okhttp/3.6.0"
> > [20:05:02] ::ffff:(IP address) - - [03/Nov/2018:11:05:02 +0000] "GET /onchange HTTP/1.1" - - "-" "okhttp/3.6.0"
> > [20:05:13] ::ffff:(IP address) - - [03/Nov/2018:11:05:13 +0000] "GET /onchange HTTP/1.1" - - "-" "okhttp/3.6.0"
> > [20:05:23] ::ffff:(IP address) - - [03/Nov/2018:11:05:23 +0000] "GET /onchange HTTP/1.1" - - "-" "okhttp/3.6.0"
> > [20:05:33] ::ffff:(IP address) - - [03/Nov/2018:11:05:33 +0000] "GET /onchange HTTP/1.1" - - "-" "okhttp/3.6.0"
> 
> on console.log every 10 seconds. The project works fine though. What is this and why is this outputted on the console log? can i disable it?

p.s. I'm using expo-cli. Could this be expo issue?

**Comment by clintjansen** [comment]
Yea, I believe this is an Expo issue only.
Happens since it updated to SDK 31.0

**Comment by Hermanyo** [comment]
My project is to react native cli, and I had the same problem

**Comment by fantasy525** [comment]
same issues,and there are too many Http infos.....

**Comment by panda0603** [comment]
update your expo-cli to latest version, should fix most of it except the
`"POST /symbolicate HTTP/1.1" 200 - "-" "okhttp/3.6.0"`.

**Comment by Hermanyo** [comment]
I'm not using expo-cli, I don't have expo in my project, and I face this problem, too... is there any solution? anyone?

**Comment by Hermanyo** [comment]
UP

**Comment by Thimeryan** [comment]
I only had this issue when I enabled live-reloading on the emulators. Once turned off the problem went away.

**Comment by TheSavior** [comment]
Based on @thimeryan's comment, it sounds like this network request is expected with live reloading.

**Comment by mwkthang1** [comment]
`set EXPO_DEBUG=true` and the **error** will be gone.

**Comment by muhyidin3222** [comment]
`sudo lsof -i`, and kill your java
