### ISSUE TITLE
cli tutorial yields broken project

### ISSUE THREAD

**Issue by rimunroe** [facebook/react-native#221]
Running `react-native init AwesomeProject/AwesomeProject.xcodeproj` will create a project at `AwesomeProject/AwesomeProject.xcodeproj/AwesomeProject.xcodeproj.xcodeproj`, which xcode will fail to open. The tutorial should probably say to run ``react-native init AwesomeProject`.

**Comment by amasad** [comment]
is this okay now?

**Comment by rimunroe** [comment]
Yes, it was my mistake.
