### ISSUE TITLE
[View] Rounded borders regression

### ISSUE THREAD

**Issue by aleclarson** [facebook/react-native#2210]
```js
var view = React.createElement(View, {
  style: {
    width: 200,
    height: 200,
    backgroundColor: '#FF16DD'
    overflow: 'hidden',
    borderRadius: 8,
    borderColor: '#000',
    borderWidth: 1 / PixelRatio.get(),
  }
});
```

This styling does not appear to round the border according to the `borderRadius`.

This results in a clipped border at the corners.

This should be a simple fix. Can you guys get this patched soon?

**Comment by browniefed** [comment]
This has apparently been fixed already according to #1235

**Comment by aleclarson** [comment]
Hmm, I already have the 81401064e5bc0e50de5d77ec9e2384a70e43e2f4 commit and the ff49d86aedc3afbed5c109d60d2b6c02230cb5d4 commit, but I'm still having problems.

Any ideas?

**Comment by brentvatne** [comment]
This works for me on 0.11-rc: https://rnplay.org/apps/e3mIsw
