### ISSUE TITLE
[Animated] AnimatedArray Prop

### ISSUE THREAD

**Issue by browniefed** [facebook/react-native#2211]
This may seem like limited use case, however `strokeDash` with React Art takes an array as documented on the #1919 issue. This doesn't work with the Animated API natively, and thus the workaround requires an `addListener` and setting state.

I was wondering if there was any thought about adding an AnimatedArray Prop. I don't know if there are any other use cases beside strokeDash that take an array as a property.

This seems to work after I added an AnimatedArray for the strokeDash prop explicitly. However would it make sense to do such a thing for all props that are arrays, or expose `Animated.AnimatedArrayProp` of some sort to allow users to create animated array props only when necessary?

```
    if (props.strokeDash) {
        props = {
            ...props,
            strokeDash: new AnimatedArray(props.strokeDash),
        };
    }

////......

class AnimatedArray extends AnimatedWithChildren {
  _array: Array;

  constructor(array: any) {
    super();
    this._array = array;
  }

  __getValue(): Array {
    var array = [];

    this._array.forEach((v, i) => {
      var value = this._array[i];
      if (value instanceof Animated) {
        array[i] = value.__getValue();
      } else {
        array[i] = value;
      }
    })
    
    return array;
  }

  getAnimatedValue(): Array {
    var array = [];
    this._array.forEach((v, i) => {
      var value = this._array[i];
      if (value instanceof Animated) {
        array[i] = value.getAnimatedValue();
      }
    })
    return array;
  }

  attach(): void {
    this._array.forEach((v, i) => {
      var value = this._array[i];
      if (value instanceof Animated) {
        value.addChild(this);
      }
    }, this)
  }

  detach(): void {

    this._array.forEach((v, i) => {
      var value = this._array[i];
      if (value instanceof Animated) {
        value.removeChild(this);
      }
    }, this)
  }
}
```

**Comment by brentvatne** [comment]
thoughts @vjeux @sahrens?

**Comment by vjeux** [comment]
This is an interesting use case. We already have Animated.ValueXY, Animated.Array seems like it could be useful as well. It kind of sucks that we have to write all of those manually, I'd love to be able to let developer in userland be able to write them

**Comment by browniefed** [comment]
Additionally with the proposal just made at #2410 would not work with animated to my knowledge since it's an array style prop.

**Comment by sahrens** [comment]
Hmm, or maybe AnimatedProps should also understand how to walk through arrays and bind values the same as if they were object keys?

**Comment by browniefed** [comment]
I believe that `contentOffset`similarly might not work since it takes an object with keys x/y. So walking may be the simplest and most effective solution at the moment.
