### ISSUE TITLE
Building React Native from source -> Project with path ':android-jsc' could not be found in project

### ISSUE THREAD

**Issue by MarkOSullivan94** [facebook/react-native#22118]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment

```
React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
      Memory: 7.19 GB / 32.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.12.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
      Android SDK:
        Build Tools: 23.0.1, 26.0.2, 27.0.3, 28.0.2, 28.0.3
        API Levels: 23, 25, 26, 27, 28
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728
      react-native: github:MarkOSullivan94/react-native#master => 1000.0.0
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

## Description

Happened after I merged the latest changes for the React Native project into my forked version of it (with only changes to share functionality included there).

## Reproducible Demo

1. Create a new React Native project `react-native init...`
2. Replace existing RN with my forked version
3. Configure all the gradle files: `build.gradle` replacing the existing RN project with the forked one and `settings.gradle` so the forked project is included.
4. Try and run the project `react-native run-android`

----

I have noticed that older versions of RN project used `compile 'org.webkit:android-jsc:r174650'` instead of `compile project(':android-jsc')` which is in the current master branch.

**Comment by gengjiawen** [comment]
That's because we add 64bit cpu support for this.
We are currently doing some work to make react native fork more easily https://github.com/facebook/react-native-website/issues/653.

**Comment by gengjiawen** [comment]
For now you can try
```
docker run --rm --name rn-build -v $PWD:/pwd -w /pwd gengjiawen/react-native /bin/sh -c "./gradlew installArchives"
```
Then remove `/android/` in .gitignore.
Also in this way you need not to hack around native dependency like `react-native-image-crop-picker`.

**Comment by gengjiawen** [comment]
Also you need this patch https://github.com/facebook/react-native/pull/22293.

**Comment by MarkOSullivan94** [comment]
I tried running the docker command and I received the following message

```
Unable to find image 'gengjiawen/react-native:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/gengjiawen/react-native/manifests/latest: unauthorized: incorrect username or password.
See 'docker run --help'.
```

**Comment by gengjiawen** [comment]
Looks like you have some network issue.

**Comment by MarkOSullivan94** [comment]
I've just copied and pasted exactly what you told me to run. I have no idea what I should do next.

**Comment by gengjiawen** [comment]
can you try run it on ci ?

**Comment by gengjiawen** [comment]
You can also try `docker run --rm -it node:11 bash -c "node -p process.versions"` to test docker work properly on your machine. If this still not works, there is little I can help since I don't know your network issue.

**Comment by MarkOSullivan94** [comment]
Yeah that didn't work either. I've never used docker before so I'm not sure if there's any additional steps I need to take to make it work on my machine for RN.

> can you try run it on ci ? Circle ci can use ssh debug.

I'm not sure I follow. I don't have Circle CI.

**Comment by gengjiawen** [comment]
You may need check the basic tutorial about docker. It likes git for me. You will love it.

**Comment by MarkOSullivan94** [comment]
Okay turns out that I was getting that error message because I was logged in with my email and not my username. Odd.

@gengjiawen where do I run that docker command? In the root level in my fork of the RN project?

**Comment by gengjiawen** [comment]
yeap.

**Comment by MarkOSullivan94** [comment]
Okay it's currently downloading. 

What do you mean by this:

> Also in this way you need not to hack around native dependency like react-native-image-crop-picker.

Curious what you mean exactly.

**Comment by MarkOSullivan94** [comment]
Ah yeah I already had that setup in the project.

Initially had issues with the RN build.gradle file, specifically this section: https://github.com/MarkOSullivan94/react-native/blob/master/ReactAndroid/build.gradle#L6

Had to fix it by removing two of the plugins from that section and using `apply plugin` instead.

```
plugins {
    id("maven")
}

apply plugin: 'com.android.library'
apply plugin: 'de.undercouch.download'
```

After that I was shown this error message

```
> Task :react-native-android:prepareJSC FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '.../ReactNativeShareExample/node_modules/react-native/ReactAndroid/build.gradle' line: 165

* What went wrong:
Execution failed for task ':react-native-android:prepareJSC'.
> Expected configuration ':react-native-android:compile' to contain exactly one file, however, it co
ntains no files.
```

**Comment by gengjiawen** [comment]
Don't remove them. And sync with upstream again as I mentioned earlier.

**Comment by hramos** [comment]
Looks like this can be closed?

The JSC in Android was updated in December, it's in master now.
