### ISSUE TITLE
expo-cli bug

### ISSUE THREAD

**Issue by PaulinPrize** [facebook/react-native#22113]
![capture](https://user-images.githubusercontent.com/41732884/47961668-b32cf780-e00f-11e8-99cb-c022bcd23351.PNG)
## Environment
I installed nodejs version:10.13.0

## Description
hello, i have a problem when i run the command npm install -g expo-cli as shown in the attached screenshot

**Comment by bartolkaruza** [comment]
I think this is not the right place for this issue. Have you tried posting it to [expo](https://github.com/expo/expo)? Expo builds on top of React Native, but the Expo CLI tooling is independently maintained by them.
