### ISSUE TITLE
[Image] resizeMode for a pattern background

### ISSUE THREAD

**Issue by yelled3** [facebook/react-native#2213]
Is there currently a way to implement an image with a repeated pattern?

similiar to `UIImageResizingModeTile`:
https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIImage_Class/#//apple_ref/c/tdef/UIImageResizingMode

from a quick lookup in the `Image` docs:
```
resizeMode enum('cover', 'contain', 'stretch') 
```
http://facebook.github.io/react-native/docs/image.html#resizemode

and in the source's docs:
```js
var ImageResizeMode = keyMirror({
  /**
   * contain - The image will be resized such that it will be completely
   * visible, contained within the frame of the View.
   */
  contain: null,
  /**
   * cover - The image will be resized such that the entire area of the view
   * is covered by the image, potentially clipping parts of the image.
   */
  cover: null,
  /**
   * stretch - The image will be stretched to fill the entire frame of the
   * view without clipping. This may change the aspect ratio of the image,
   * distoring it.
   */
  stretch: null,
});
```

**Comment by nicklockwood** [comment]
It's not currently possible, although I think there's a PR that adds tiling background image support to `<View>`.

I don't know if adding this as an ImageResizeMode makes sense, as you wouldn't be able to control the scale or alignment, which would make it less useful than the CSS background image spec.

Any thoughts @vjeux?

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/image-resizemode-for-a-pattern-background
