### ISSUE TITLE
Could not read path 'E:\RNdemo\node_modules\@babel\parser\.bin\parser'.

### ISSUE THREAD

**Issue by daiyuqing** [facebook/react-native#22138]
run ‘ ./gradlew assembleRelease’,
Failed to capture snapshot of input files for task ':app:bundleReleaseJsAndAssets' property '$1' during up-to-date check.
> Could not read path 'E:\RNdemo\node_modules\@babel\parser\.bin\parser'.

**Comment by tronginc** [comment]
I also encountered this. Seems to be a problem with newer Yarn versions on Windows.
