### ISSUE TITLE
react-native init not work if node 9 and yarn installed

### ISSUE THREAD

**Issue by wayne1203** [facebook/react-native#22130]
I have installed the latest version of yarn, but I need to use node 9 for my development.
When I "react-native init", it will using yarn to build and error appear
`error sane@3.1.0: The engine "node" is incompatible with this module. Expected version "6.* || 8.* || >= 10.*". Got "9.11.2" `

It will fine if I uninstalled yarn, can I force "react-native init" to use npm or any solution to fix the problem?

**Comment by brayanL** [comment]
Close a issue does not solve it thanks for nothing react native support.

**Comment by brunolemos** [comment]
Re-install Node.js, use the LTS version from their website.
