### ISSUE TITLE
react-native init not work if node 9 and yarn installed

### ISSUE THREAD

**Issue by wayne1203** [facebook/react-native#22131]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
>   React Native Environment Info:
>     System:
>       OS: macOS High Sierra 10.13.6
>       CPU: x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
>       Memory: 3.27 GB / 16.00 GB
>       Shell: 3.2.57 - /bin/bash
>     Binaries:
>       Node: 9.11.2 - /usr/local/bin/node
>       Yarn: 1.12.1 - /usr/local/bin/yarn
>       npm: 5.6.0 - /usr/local/bin/npm
>       Watchman: 4.9.0 - /usr/local/bin/watchman
>     SDKs:
>       iOS SDK:
>         Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
>     IDEs:
>       Android Studio: 3.2 AI-181.5540.7.32.5056338
>       Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
>     npmPackages:
>       react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728 
>       react-native: 0.57.4 => 0.57.4 
>     npmGlobalPackages:
>       react-native-cli: 2.0.1

## Description
The upper information are getting by other react-native project that I created before
<img width="568" alt="2018-11-05 1 09 50" src="https://user-images.githubusercontent.com/8578341/47979083-201dbb80-e0fc-11e8-81da-bf9053f222d9.png">

## Reproducible Demo
Just run "react-native init" with yarn installed and using node 9

**Comment by bartolkaruza** [comment]
Why not upgrade to the current Node version or one of the active LTS Node versions? https://github.com/nodejs/Release

Node 9 is no longer supported by the Node.js Foundation.

Perhaps we should add that 'engines' declaration from [Sane](https://github.com/amasad/sane/blob/c4d5b7f1329cf3894b6f876c850629023dae8540/package.json#L48 ) to the RN package.json?

**Comment by wayne1203** [comment]
@bartolkaruza I know that node 9 is not longer support. But I have a library need to using node 9 for compile. I'll ask them for support. Thanks for your reply.
