### ISSUE TITLE
Keyboard module not listener keyboardDidShow on Android 

### ISSUE THREAD

**Issue by ChengGPBU** [facebook/react-native#22168]
react-native 0.57.4

![image](https://user-images.githubusercontent.com/24949641/48048892-f043e600-e1d7-11e8-8148-1046c0583d96.png)

**Comment by Liqiankun** [comment]
Same Issue! 
![2019-02-20 11 40 07](https://user-images.githubusercontent.com/11532418/53064874-5264f480-3504-11e9-922c-722208f4d811.png)
