### ISSUE TITLE
Better error message when referencing a component that is not required properly

### ISSUE THREAD

**Issue by Will-Sommers** [facebook/react-native#2217]
Hello, I think this is definitely a nice to have but could make development for people starting with React-Native a lot better. There's been a few times while working through the API where I have not properly required the new component I'm learning and I get hit with an error message that looks as such: 

![screen shot 2015-08-03 at 10 47 04 pm](https://cloud.githubusercontent.com/assets/1354217/9052085/55de38be-3a31-11e5-805a-9ed516b74b50.png)

It'd be really great to have a nice hint for folks. Your console for web react already does a great job of this. In any event, thank you for your hard work on all of these projects.

**Comment by ide** [comment]
We'll track this in #1569.
