### ISSUE TITLE
[NavigatorIOS] is it possible to disable borderBottom on navigation bar?

### ISSUE THREAD

**Issue by plrthink** [facebook/react-native#2218]
Hi, I just ran into a situation where I need to put a SegmentedControlIOS into navigation bar, it would looks like top charts scene in app store on iOS. So I need some way to make navigation bar's borderBottom disappeared, but I failed to find api to do this.

Is there some workaround on this or some api that can directly achieve this?

**Comment by ide** [comment]
I think this is what you're looking for: https://facebook.github.io/react-native/docs/navigatorios.html#shadowhidden

**Comment by plrthink** [comment]
@ide I have tried this, but it doesn't help.

![image](https://cloud.githubusercontent.com/assets/2429369/9056270/8a21bf86-3ac4-11e5-939e-7b4a125b0d24.png)

**Comment by ide** [comment]
You may be on an older version of React Native.

**Comment by plrthink** [comment]
@ide I'm using react-native 0.80

**Comment by plrthink** [comment]
@ide And I want to disable that border, not the shadow.

**Comment by ide** [comment]
I'm not sure what border you're talking about but there's no APIs to hide any borders. If you can point at the property in Apple's documentation that you want to turn on or off that will make it easier to help you.
