### ISSUE TITLE
Unhandled JS Exception: Unexpected EOF

### ISSUE THREAD

**Issue by rauleb** [facebook/react-native#22183]
## Environment
  React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz
      Memory: 38.38 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.11.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        Build Tools: 27.0.3, 28.0.2, 28.0.3
        API Levels: 23, 26, 27, 28
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5014246
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: ^3.4.0 => 3.4.11 
      react: 16.4.1 => 16.4.1 
      react-native: 0.57.0 => 0.57.0 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

## Description
I installed a react-native-device-info library, and this error appeared, then delete the library, delete my node_modules, but continue with the problem. The error has no information

![simulator screen shot - iphone xs - 2018-11-06 at 15 53 42](https://user-images.githubusercontent.com/5591086/48086875-a7426080-e1dc-11e8-85e3-97fcad21e93f.png)

**Comment by rauleb** [comment]
Solved

**Comment by OneStromberg** [comment]
In my case it was **unrecognised symbol**. It was in my JSON file with localization(i18n)
I found it when open index.bunlde and went to the specified line that is in error message;
