### ISSUE TITLE
My IOS app crashed in release mode.

### ISSUE THREAD

**Issue by buraksak35** [facebook/react-native#22192]
## Environment

  React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 390.63 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.11.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
      Android SDK:
        Build Tools: 23.0.1, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.3, 28.0.2, 28.0.3
        API Levels: 22, 23, 25, 26, 27, 28
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1
      react-native: 0.56.0 => 0.56.0
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      react-native-rename: 2.2.2

## Description
My app is working perfect in emulator and my phone without release, but when I run react-native run-ios --configuration Release this command, my app crashed. This is my log.
![ekran resmi 2018-11-07 09 42 13](https://user-images.githubusercontent.com/39245976/48115291-7c571b80-e273-11e8-9e19-bed77acdcd80.png)

**Comment by buraksak35** [comment]
> It looks like you are using an older version of React Native. Please update to the [latest release, v0.57](https://github.com/facebook/react-native/releases/tag/v0.57.4) and verify if the issue still exists.
> 
> The "⏪Old Version" label will be removed automatically once you edit your original post with the results of running `react-native info` on a project using the latest release.

Not working....

**Comment by radko93** [comment]
You're using an old RN version, please upgrade first. Also without any repro we won;t help you.

**Comment by buraksak35** [comment]
I think problem is due to Mobx.Because I tried new clear project and I could build as release , but when I install mobx, I encountered crash again

**Comment by radko93** [comment]
Have you tried running with/without Chrome debugger?

**Comment by buraksak35** [comment]
> Have you tried running with/without Chrome debugger?
I am talking about release mode. In debug mode there is no problem.

**Comment by buraksak35** [comment]
<img width="1035" alt="ekran resmi 2018-11-08 18 46 12" src="https://user-images.githubusercontent.com/39245976/48210257-05f80d80-e388-11e8-9746-8e1326fe20e5.png">
<img width="1014" alt="ekran resmi 2018-11-08 18 55 08" src="https://user-images.githubusercontent.com/39245976/48210262-0690a400-e388-11e8-8831-d047fb6e5e01.png">
<img width="1072" alt="ekran resmi 2018-11-08 18 46 27" src="https://user-images.githubusercontent.com/39245976/48210265-07293a80-e388-11e8-8919-554be77879e2.png">
<img width="1040" alt="ekran resmi 2018-11-08 18 46 21" src="https://user-images.githubusercontent.com/39245976/48210267-07293a80-e388-11e8-9259-81f171f626b2.png">
<img width="876" alt="ekran resmi 2018-11-08 18 46 18" src="https://user-images.githubusercontent.com/39245976/48210270-085a6780-e388-11e8-97c8-0ddd1c193422.png">

Hey I found these. Please check and help me :( @kelset @radko93

**Comment by buraksak35** [comment]
I solved with downgrade to 0.55.4.
