### ISSUE TITLE
Will support webrtc?

### ISSUE THREAD

**Issue by qingfeng** [facebook/react-native#222]
thanks :beer:

**Comment by vjeux** [comment]
Unlikely to be implemented directly inside of react native core. The goal is for the plugin api to be good enough so that people from the community can build webrtc support

**Comment by brentvatne** [comment]
@qingfeng - if you're interested in building a WebRTC plugin that would be very welcome! ping me in irc if you want to know how to get started, I'm `notbrent`

**Comment by murugannode** [comment]
Any update about this #222

**Comment by qingfeng** [comment]
@brentvatne I am now doing ~

**Comment by mdauner** [comment]
@brentvatne @qingfeng 
any news about it?

**Comment by yniche** [comment]
@qingfeng awesome! Is there on GH yet? (I understand it's very much WIP, that's alright.)

**Comment by oney** [comment]
I have built a plugin to support WebRTC in React Native.
Please checkout https://github.com/oney/react-native-webrtc
