### ISSUE TITLE
[Navigator.NavigationBar]How to re-render the navigationBar's buttons or title elegantly?

### ISSUE THREAD

**Issue by everfire130** [facebook/react-native#2220]
8.0.0
for example 
![image](https://cloud.githubusercontent.com/assets/11308837/9057914/d8c9b304-3acf-11e5-8e2b-bb43d65c34b4.png)
I want to change the number in my view.But I don't know how to control the navigationbar well.
Now I only quote the navigationbar's button' instance to call func to change the button.
How can I do it elegantly?
And I find that when I use the initialRouteStack the routeMapper's call-back 
(like  LeftButton:function(route) ) always callback the last route

**Comment by gre** [comment]
this is exactly what Flux approach is for.

**Comment by metacortex** [comment]
@gre 
When I use `navigator.replace()` in order to re-render navbar buttons, `ListView` scrolls to top position and all `Image` views make flickering.

How did you solve this problem?

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/navigatornavigationbarhow-to-re-render-the-navigationbars-buttons-or-title-elegantly

**Comment by Yixi** [comment]
any update?

**Comment by phongyewtong** [comment]
any update?
