### ISSUE TITLE
KeyboardAvoidingView doesn't work when behavior is padding on ios

### ISSUE THREAD

**Issue by Liqiankun** [facebook/react-native#22207]
## Environment
```
npm: 6.1.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728
      react-native: 0.57.3 => 0.57.3
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

## Description
when `behavior="padding"`
![padding](https://user-images.githubusercontent.com/11532418/48177628-a7636d00-e350-11e8-88a6-3b676308e8f7.gif)

when behavior="position"
![position](https://user-images.githubusercontent.com/11532418/48177637-bd712d80-e350-11e8-8c6c-d48fb4675102.gif)

## Reproducible Demo
```js
export default class Test extends Component {
    render() {
        const { navigation } = this.props
        return (
            <SafeAreaView style={CommonStyles.container}>
                <KeyboardAvoidingView style={styles.keyborderView} behavior="padding">
                    <View style={styles.topView}></View>
                    <TextInput style={styles.input} />
                </KeyboardAvoidingView>
           </SafeAreaView> 
        )
    }
}

const styles = StyleSheet.create({
    input: {
        width: 300,
        height: 40,
        borderWidth: 1,
        borderColor: 'red'
    },
    topView: {
        height: 300,
    },
    keyborderView: {
        flex: 1
    }
})
```

**Comment by Liqiankun** [comment]
@react-native-bot It's right there!
![2018-11-08 1 20 23](https://user-images.githubusercontent.com/11532418/48179212-1218a680-e359-11e8-8e4e-fb2bd176d455.png)

**Comment by Ashoat** [comment]
I think you're using the wrong style for `behavior="padding"`. You can take a look into `KeyboardAvoidingView.js` to see how it's implemented, but if I recall correctly `behavior="padding"` basically works by varying the bottom padding. I think your style is implemented to layout from the top, which is why varying the bottom padding has no effect.

**Comment by Liqiankun** [comment]
@Ashoat Thanks! I will take a look. But In this demo, I didn't see any difference. [react-native-keyboard-avoidance-examples](https://github.com/spencercarli/react-native-keyboard-avoidance-examples/blob/master/app/styles.js)

**Comment by mirse** [comment]
> https://gist.github.com/vovkasm/8e2d2f6ac9b77e16a802e2900b9f9e40

I can not open your website,can you send again?

**Comment by orkylish** [comment]
I wanted a super simple way for this to work, and finally found one thanks to [this](https://stackoverflow.com/a/56579431) comment on stackoverflow

[react-native-keyboard-aware-scroll-view](https://www.npmjs.com/package/react-native-keyboard-aware-scroll-view)

works exactly as I wanted for my multi-input screen, view only adjusts enough to match the currently selected input box
