### ISSUE TITLE
Invisible content of large View with borderRadius > 0 (Android 7.0, RN >= 0.57.1)

### ISSUE THREAD

**Issue by mefjuu** [facebook/react-native#22213]
## Environment
```
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 31.61 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728 
      react-native: 0.57.4 => 0.57.4 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

```
AVD: Nexus_5X_API_24 (Android 7.0)
```

## Description
Large `<View /> ` with borderRadius > 0 gets invisible on Android 7.0 (API level 24) using RN **>= 0.57.1**.
It's regression, because it rendered correctly using RN 0.57.0.

## Reproducible Demo

This is rendered expectedly: 
```
export default class App extends React.Component {
    render() {
        return (
            <ScrollView style={{ flex: 1 }}>
                <View style={{ borderRadius: 10, backgroundColor: "violet", height: 731 }} />
            </ScrollView>
        );
    }
}
```

However after increasing the height, the violet content disappears, but ScrollView is aware of it so can be scrolled vertically.

**Comment by dsznajder** [comment]
It should not be related to the Old Version you sneaky @react-native-bot

**Comment by mefjuu** [comment]
It seems to be resolved in RN 0.57.5

**Comment by michbil** [comment]
> It seems to be resolved in RN 0.57.5

Updated 0.57.5, problem persists

**Comment by michbil** [comment]
Only one way to overcome this issue currently is to split big view to 3 subviews, with rounded corners assigned to top and bottom one, so big content will be without rounded corners at all

**Comment by mefjuu** [comment]
For me, as I've written, it started working properly after upgrading RN to 0.57.5.
However, on a cheap device equipped with poor GPU, screens containing those large `<View/>`s with rounded corners suffer for jerky scrolling again (in 0.57.1 i was smooth).

**Comment by Balasnest** [comment]
Facing exact issue. Not showing content in most of the Android 7.0 devices. 

Any workaround for this?

**Comment by meghaptg** [comment]
I'm getting the same issue, any update on this??

**Comment by georgian3688** [comment]
Recently, upgraded my project to react native 0.57.2. I am facing the same issue. Content(when content is big) is missing many places. It's very difficult to change all the places and split into 3 subviews.  Please fix this issue or let me know if there is any alternate solution.

**Comment by hramos** [comment]
Has anybody tried this on 0.58, or 0.59? 0.57.2 was released on October 4, 2018, that release is almost half a year old now.

**Comment by cpojer** [comment]
Closing this as we haven't gotten any recent repros for the latest version of RN. Happy to reopen if it is still an issue.

**Comment by ebaynaud** [comment]
This is still in an issue with RN 0.59.5

**Comment by CelsoTeixeira** [comment]
Hello, currently experiencing this issue on RN 0.59.8, if we have a larger view, when applying a borderRadius, the view dissapear, it's content dont.

Made this simple repo to show: https://github.com/CelsoTeixeira/rn-view-border-issue

Tested on two different phones that was available at the moment.

S9+ with Android 9.0 is displaying the view with the border.
S8 with Android 7.0 dont display the view, only it's content.

Following are two screenshots from both phones.

![S8](https://user-images.githubusercontent.com/6026577/58286268-c4a7d800-7d84-11e9-9d8e-160eaa20f6c9.jpeg)

![S9](https://user-images.githubusercontent.com/6026577/58286286-ca052280-7d84-11e9-8ff1-a0ff5976fda8.jpeg)
