### ISSUE TITLE
WARN react-native@0.57.4 requires a peer of react@16.6.0-alpha.8af6728 but none is installed. You must install peer dependencies yourself.

### ISSUE THREAD

**Issue by activephil** [facebook/react-native#22218]
I have a newly installed React-Native environment and proceeded to do a test project (react-native init test).

The INIT ended but with WARN react-native@0.57.4 requires a peer of react@16.6.0-alpha.8af6728 but none is installed. You must install peer dependencies yourself.
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
      Memory: 138.55 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      npm: 6.4.1 - ~/.npm-global/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
      Android SDK:
        API Levels: 25, 27
        Build Tools: 27.0.3
    IDEs:
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728 
      react-native: 0.57.4 => 0.57.4 
    npmGlobalPackages:
      react-native-cli: 2.0.1

The BUILD failed as well: 
The following build commands failed:
	CompileC /Users/ramonreyes/re/test/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/double-conversion.build/Objects-normal/x86_64/strtod.o /Users/ramonreyes/re/test/node_modules/react-native/third-party/double-conversion-1.1.6/src/strtod.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/ramonreyes/re/test/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/double-conversion.build/Objects-normal/x86_64/fixed-dtoa.o /Users/ramonreyes/re/test/node_modules/react-native/third-party/double-conversion-1.1.6/src/fixed-dtoa.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/ramonreyes/re/test/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/double-conversion.build/Objects-normal/x86_64/fast-dtoa.o /Users/ramonreyes/re/test/node_modules/react-native/third-party/double-conversion-1.1.6/src/fast-dtoa.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(3 failures)

Installing build/Build/Products/Debug-iphonesimulator/test.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/test.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/test.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:602:13)
    at Object.execFileSync (child_process.js:622:13)
    at Promise.then (/Users/ramonreyes/re/test/node_modules/react-native/local-cli/runIOS/runIOS.js:208:5)
    at <anonymous>

As a guy new to React-Native I do not have a clue how to move forward. 

Can anyone help?

**Comment by bartolkaruza** [comment]
Can you post the content of your package.json?

**Comment by zenz** [comment]
did you do ' npm install ' in your projects folder?

**Comment by activephil** [comment]
> Can you post the content of your package.json?

Thanks for responding.  This are the contents of package.json
{
  "name": "test",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.6.0-alpha.8af6728",
    "react-native": "0.57.4"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.49.0",
    "react-test-renderer": "16.6.0-alpha.8af6728"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by activephil** [comment]
> did you do ' npm install ' in your projects folder?

Hi. I don't remember doing that. I was following the "Get Started" at https://facebook.github.io/react-native/.  In a way I did do a 'npm install' because I installed the CLI from my home directory but I did not issue another 'npm install -g react-native-cli' inside the project folder.

These are  the terminal command issued from my root folder:
brew install node
brew install watchman
npm install -g react-native-cli
react-native init PROJECT-NAME -- in my case it was react-native init test

The results of the INIT is what is seen on my post message.
If you can point out where I made a mistake, that will be highly appreciated. Thanks.

**Comment by zenz** [comment]
I cannot remember the behavior of npm, I'm using yarn, so while I do react init App, it will get all base packages installed.
if you are using npm, then just try to run 'npm install' in you project's folder again, then you can try 'react-native run-ios' to test it.

**Comment by activephil** [comment]
> if you are using npm, then just try to run 'npm install' in you project's folder again, then you can try 'react-native run-ios' to test it.

Hi. I tried your suggestion and issued 'npm install' in the project folder. Finally the Welcome to React Native! splash appeared on the simulator. I guess it worked. Please bear with me but I am very curious as to what did the 'npm install' do to make the build successful?

The 'react-native run-ios'  ended with:
** BUILD SUCCEEDED **
The following commands produced analyzer issues:
	Analyze /Users/ramonreyes/re/test/node_modules/react-native/React/Base/RCTModuleMethod.mm normal x86_64
	Analyze /Users/ramonreyes/re/test/node_modules/react-native/Libraries/Network/RCTNetInfo.m normal x86_64
(2 commands with analyzer issues)
Installing build/Build/Products/Debug-iphonesimulator/test.app
Launching org.reactjs.native.example.test
org.reactjs.native.example.test: 11085

Having done all these I feel I have to do more digging to be sure that all is well with my react-native environment.

Thanks for your help.

**Comment by zenz** [comment]
@activephil Read the documents please.

**Comment by bartolkaruza** [comment]
@kelset close
