### ISSUE TITLE
Watchman / Metro Bundle cache don't update changes

### ISSUE THREAD

**Issue by ger86** [facebook/react-native#22214]
## Environment
  React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
      Memory: 36.08 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 26, 27
        Build Tools: 26.0.3, 27.0.3, 28.0.3
        System Images: android-25 | Google Play Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.0 => 16.6.0 
      react-native: 0.57.4 => 0.57.4 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description
Since React Native 0.57.4 when I am working with the iOS simulator, if I have an error importing a module (suppose I try to import ../A/someModule but someModule does not exists) I get the following error:

![simulator screen shot - iphone 6 - 2018-11-08 at 17 01 44](https://user-images.githubusercontent.com/1313445/48210694-2b7d1b00-e378-11e8-83f7-d529b86be516.png)

But when I fixed it, watchman can't detect the change done in the source code and I have to:
- reboot my computer
- reinstall watchman package 
- remove node_modules folder 

It is something weird but with a project with RC 57.1 doesn't happen to me... 

I try with a clean installation of react-native and it starts to happen radomly.

**Comment by jsaraiva** [comment]
Have you tried starting Metro with the --reset-cache flag?

In other words, in a terminal window, run `react-native start --reset-cache`. This will start a Metro bundler instance in that terminal window.
In another terminal window, run `react-native run-<your platform>`.

Usually does the trick for me, when that error appears. But I haven't upgraded to the latest version of RN, so YMMV.

**Comment by dev6james** [comment]
If the cache is dependent on strict semantic versioning i.e. only the 3 numbers, I would say that if it encounters a dependency that diverges from the standard format that it should only do a direct string equality check. I dont have any insight into the current logic though so I dont know if it's doing anything like this.

**Comment by ger86** [comment]
> Have you tried starting Metro with the --reset-cache flag?
> 
> In other words, in a terminal window, run `react-native start --reset-cache`. This will start a Metro bundler instance in that terminal window.
> In another terminal window, run `react-native run-<your platform>`.
> 
> Usually does the trick for me, when that error appears. But I haven't upgraded to the latest version of RN, so YMMV.

Nope, I have tried it and same results.... I have noticed the error starts to happen (most of the times) when there is a dependency error (ie, import A from 'MyApp/src/no-existing'). Then I have to reset my computer or reinstall watchman...

**Comment by Arlen22** [comment]
I've also started running into this problem. Except that all I have to do is ctrl+c and then run `expo start` again. But it is still very annoying. I'm using expo-cli 2.4.3

**Comment by cpojer** [comment]
This issue has been moved to facebook/metro#375.
