### ISSUE TITLE
const { } = this.props; blank screen only in release mode

### ISSUE THREAD

**Issue by grean** [facebook/react-native#22223]
## Environment
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 2.29 GB / 15.86 GB
    Binaries:
      Yarn: 1.5.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.2.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5014246

## Description
In debug mode, there is no warning or error when you let this code in the render function of a component :
const { } = this.props;
AND it works fine without no problem.
BUT in release mode, we have a blanck screen when the component that contains this line of code is loaded.. So, you have to comment and rebuild the release apk each time you try to understand what's happening.
I know it's useless to let this kind of code in a component but sometimes it happens lol..

## Reproducible Demo
simply had the line above et try in release mode.

**Comment by dulmandakh** [comment]
I would like to suggest to use eslint and check your code. it's not a bug in RN.
