### ISSUE TITLE
borderStyle is ignored on Android unless set on all sides with non-zero borderRadius

### ISSUE THREAD

**Issue by irasantiago** [facebook/react-native#22226]
- [X] Review the documentation: https://facebook.github.io/react-native
  - [X] Search for existing issues: https://github.com/facebook/react-native/issues
  - [X] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
 React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
      Memory: 523.12 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.11.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0
      react-native: 0.57.4 => 0.57.4
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

## Description
When the `borderStyle` property is set to `dashed` or `dotted`, Android will always render a solid border unless the `borderWidth` is set all around the element and a `borderRadius` greater than 0 is added. This means you cannot have a styled border on one, two or three sides.

Here's what it looks like in iOS and Android:
![iosandroidborderstyle](https://user-images.githubusercontent.com/8863094/48275478-8fa0ed00-e413-11e8-9a4a-b7ebfbeccf5c.png)

Seems like this is a regression which was mentioned in closed issues. The most recent is https://github.com/facebook/react-native/issues/18285

## Reproducible Demo
Expo Snack: https://snack.expo.io/SkE6cNfT7
Repo: https://github.com/irasantiago/rn-android-border-style

**Comment by ubbcou** [comment]
```
Run in Expo application
System:
  OS: Android 8.0.0
```
![](https://github.com/ubbcou/blog/blob/master/images/TIM%E5%9B%BE%E7%89%8720181113155736.png?raw=true)

**Comment by mrnagydavid** [comment]
With Expo 30.0.0 (RN 0.55.4) the issue is even worse, there is just no way to make `dashed` or `dotted` on a view border - not even with borderRadius.

**Comment by Donhv** [comment]
any update for this>
