### ISSUE TITLE
[CLI] react-native cli command could support -v (--version) parameter.

### ISSUE THREAD

**Issue by matiit** [facebook/react-native#2225]
It's widely used, standard way of checking version of any unix-like binary. I don't understand why not implement that.

**Comment by catalinmiron** [comment]
+1

**Comment by brentvatne** [comment]
@matiit - sure thing, pull request welcome! :smile:

**Comment by matiit** [comment]
Maybe will do. Don't know the project yet.



—

**Comment by nsimmons** [comment]
Just submitted a PR to add this.
