### ISSUE TITLE
[iOS] WKWebView reloads page each time it gets back into the foreground

### ISSUE THREAD

**Issue by petlys** [facebook/react-native#22259]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment

```
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
      Memory: 2.96 GB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
      npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 25, 26, 27
        Build Tools: 23.0.1, 25.0.1, 27.0.3
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728 
      react-native: 0.57.4 => 0.57.4 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

## Description

**iOS only!**

I have an simple app that simply renders a view with a `<WebView>` with and a `<Modal>`.
All good until you open and close the `<Modal>`, in which case the `<WebView>` will reload the webpage being displayed. 
The same goes for anything else that might put the `<WebView>` in the background and then in the foreground again. For instance opening a Safari view (https://github.com/naoufal/react-native-safari-view). Each time the `<WebView>` gets back into the foreground again, it reloads the page. 

This happens **only** with WKWebView (i.e `useWebKit` prop being passed). The old UIWebView works as expected. 

```javascript
<View>
  <Modal visible={this.state.showModal}>
    ...
  <Modal>

  <WebView useWebKit source={{ uri: 'https://some.web.page.com' }} />
</View>
```

**Comment by petlys** [comment]
> The WebView component is being extracted from the react native core into a separate repository. Could you check if you still have this issue when you use "react-native-webview" as a dependency instead of the soon to be deprecated Webview from rn? If so, please post this issue on that repo as you'll get a fix/answer sooner.

Thank you for the response. It does indeed work with `react-native-webview` 👍 
However, I experience the same issue as listed here: https://github.com/react-native-community/react-native-webview/issues/136

**Comment by kelset** [comment]
Thanks Bartol!

@petlys as mentioned, WebView is maintained there, so help the conversation more forward there: it would surely help fixing it
