### ISSUE TITLE
Question about PATENTS file in dependencies

### ISSUE THREAD

**Issue by iyegoroff** [facebook/react-native#22260]
# For Discussion

One of fresco [dependencies](https://github.com/facebook/fresco/search?q=bolts-tasks&unscoped_q=bolts-tasks) - [Bolts-Android](https://github.com/BoltsFramework/Bolts-Android) has a BSD + PATENTS style license. So it looks like legally nothing changed since removal of PATENTS file from react-native. Can you give some clarification on this issue? Thanks.

**Comment by hramos** [comment]
Resolved, Bolts-Android has been relicensed to MIT.
