### ISSUE TITLE
'config.h' file not found - mutex.h

### ISSUE THREAD

**Issue by MohamadKh75** [facebook/react-native#22267]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i7-2620M CPU @ 2.70GHz
      Memory: 7.40 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.13.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
    IDEs:
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.1 => 16.6.1
      react-native: 0.57.5 => 0.57.5
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

## Description
As mentioned [here](https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md#ios-specific-1), this must be fixed but i'm getting this error after using `react-native init MyTestProject`.

## Reproducible Demo
Simply use `react-native init MyTestProject` and you will get this error!
Also, i tried to set the `Project Settings` to `Legacy Build System` and cleaned the build folder but no result!

**Comment by sabirbasha** [comment]
Am also facing same issue can someone help me to resolve this

**Comment by MohamadKh75** [comment]
> Am also facing same issue can someone help me to resolve this

As a temporary fix, you could navigate to `..\node_modules\react-native\third-party\glog-0.3.5` and:

````
./configure
make
````

**Comment by fsarachu** [comment]
this solved my problem: https://github.com/facebook/react-native/issues/19529#issuecomment-423898864

**Comment by thymikee** [comment]
@facebook-github-bot duplicate #19529

**Comment by MohamadKh75** [comment]
> @facebook-github-bot duplicate #19529
> 
> If you use Yarn, running `yarn --check-files` usually fix that for me (also you may want to change Node to latest LTS)

It's not duplicate because:

> **As mentioned [here](https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md#ios-specific-1), this must be fixed**

This bug is still in the 0.57.5 so i opened this issue!

**Comment by sabirbasha** [comment]
> > @facebook-github-bot duplicate #19529
> > If you use Yarn, running `yarn --check-files` usually fix that for me (also you may want to change Node to latest LTS)
> 
> It's not duplicate because:
> 
> > **As mentioned [here](https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md#ios-specific-1), this must be fixed**
> 
> This bug is still in the 0.57.5 so i opened this issue!

Still we are facing same issue in React 0.57.5..

**Comment by alvgaona** [comment]
Same issue dragged from previous versions. After fixing with #19529 workarounds and running react-native run-ios, config.h disappears from /src/base and app does not run. Still need to fix this.

**Comment by brascene** [comment]
Same issue here, experiencing it after ejecting the default created app with expo init. I guess would get the same issue with react-native init..

I've tried with ..\node_modules\react-native\third-party\glog-0.3.5
and when I run ./configure , I receive this error:
checking whether build environment is sane... 
configure: error: unsafe absolute working directory name

Note, I'm using XCode 10.0, Legacy build system, RN 0.57.1, yarn 1.12.3

**Comment by alvgaona** [comment]
> Same issue here, experiencing it after ejecting the default created app with expo init. I guess would get the same issue with react-native init..
> 
> I've tried with ..\node_modules\react-native\third-party\glog-0.3.5
> and when I run ./configure , I receive this error:
> checking whether build environment is sane...
> configure: error: unsafe absolute working directory name
> 
> Note, I'm using XCode 10.0, Legacy build system, RN 0.57.1, yarn 1.12.3

My react-native info is the following. 

```
  React Native Environment Info:
    System:
      OS: macOS 10.14.1
      CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
      Memory: 54.82 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.2.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.1 => 16.6.1 
      react-native: 0.57.7 => 0.57.7 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

I have been able to run ```./configure``` and ```config.h``` appears in ```src``` folder. However, when running ```react-native run-ios``` all those files disappear.

**Comment by MohamadKh75** [comment]
> Same issue here, experiencing it after ejecting the default created app with expo init. I guess would get the same issue with react-native init..
> 
> I've tried with ..\node_modules\react-native\third-party\glog-0.3.5
> and when I run ./configure , I receive this error:
> checking whether build environment is sane...
> configure: error: unsafe absolute working directory name
> 
> Note, I'm using XCode 10.0, Legacy build system, RN 0.57.1, yarn 1.12.3

You can use `./configure` and then `make` in the `..\node_modules\react-native\third-party\glog-0.3.5` folder and then clean your build folder from XCode as a temporary solution!

@kelset I think this is not fixed yet (despite of mentioned in the changelog)

**Comment by brascene** [comment]
I can confirm that with react-native init everything works well, the previous issue was there because the folder where the project was created, was in iCloud... and that messed up the relative paths, after I created project in another directory, no issues. Sorry for taking your time :)

**Comment by alvgaona** [comment]
> I can confirm that with react-native init everything works well, the previous issue was there because the folder where the project was created, was in iCloud... and that messed up the relative paths, after I created project in another directory, no issues. Sorry for taking your time :)

Actually, react-native fails for me but expo init works like a charm.

**Comment by MohamadKh75** [comment]
@hramos i'll reach my Mac in a week! Will do that as soon as i can!

**Comment by MohamadKh75** [comment]
@hramos i used `0.58.0-rc.1` and i can confirm that didn't get the error for `'config.h' file not found` **BUT** i faced new issue.

I'll create a new issue for that!

**Comment by TRIPTI-JAIN** [comment]
In the Terminal, navigate to the react-native/third-party/glog folder inside node_modules (for me, this was cd node_modules/react-native/third-party/glog-0.3.4)
Once actively in this folder, run ../../scripts/ios-configure-glog.sh
Glog is configured and the required config.h header file is created for Xcode to find
