### ISSUE TITLE
Expected instance props to match memoized props before componentDidMount

### ISSUE THREAD

**Issue by marcocesarato** [facebook/react-native#22268]
After updgrade to react-native 0.57.5 and react 16.6.3 i've this error: `ExceptionsManager.js:84 Warning: Expected instance props to match memoized props before componentDidMount. This is likely due to a bug in React. Please file an issue.`
What mean this error? What i've to do?
UPDATE:
Resolved downgrading react-native to 0.57.4 but on 0.57.5 still have this error...

**Comment by jiasongs** [comment]
+1
