### ISSUE TITLE
[Android] double R in emulator brings keyboard after typing in TextInput

### ISSUE THREAD

**Issue by greenais** [facebook/react-native#22265]
## Environment
Environment:
  OS: Windows 8.1
  Node: 8.12.0
  Yarn: 1.3.2
  npm: 6.4.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.1.0.0 AI-173.4819257
Packages: (wanted => installed)
  react: 16.6.1 => 16.6.1
  react-native: 0.57.5 => 0.57.5

## Description
After I typed in TextInput in any of my components reloading app in Android emulator with double R always brings up Android keyboard - even if component is inactive already (i.e. app navigated to another component). It can be hided by Android standard button, but this behaviour is quite irritating.

Do I miss something in handling InputText or this is any kind of bug/feature?

**Comment by greenais** [comment]
Any toughths on this?
It still happens with all the most recent versions of RN and emulator...

If it's expected and normal - just confirm please and feel free to close this issue to clean the stack

**Comment by Averybeast1234** [comment]
I am having the same issue

**Comment by bobber205** [comment]
Is there a good reason why Command + R isn't used instead of double tapping R?

**Comment by Averybeast1234** [comment]
Command R is a MacOs thing. Also it is not just the double tapping of R. Anytime a textInput is used and you render to another component that doesn't have one, any press of a letter key on hardware keyboard brings up the software keyboard even if there is not textinput that is being rendered or mounted.
