### ISSUE TITLE
Inconsistent Perspective between iOS and Android

### ISSUE THREAD

**Issue by wcandillon** [facebook/react-native#22280]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
[skip envinfo]
App created with `create-react-native-app` running on both iOS and Android.

## Description
On Android, there is a default perspective transformation applied to the view. That leads to inconsistent transformations between Android and iOS. By reading the issues on Github, it looks like this default perspective is needed in order for some 2d transformation to work properly on some Android devices. I posted a question about this on stackoverflow: https://stackoverflow.com/questions/53300779/what-is-the-default-react-native-perspective-on-android

Unfortunately, I cannot find the inverse perspective transformation on Android that would lead me to build consistent 3d transformation between iOS and Android.
One suggestion I have (if my understanding of the problem is correct) is that if the transform set on the JS side has a perspective element, don't apply any another transform perspective on Android.

## Reproducible Demo
https://snack.expo.io/@wcandillon/test-3d-transform
In the snack above, the animation is 2d as expected on iOS and 3d on Android (not expected).

**Comment by wcandillon** [comment]
@hramos Why do you think that this isn't a bug report? Many 3d transforms are affected by this issue. I would love to help out, I would need someone to point me in the right direction.

**Comment by hramos** [comment]
@wcandillon we recently started using the "Type: Bug Report" label in place of "Bug Report". Notice I only removed the old label.

**Comment by wcandillon** [comment]
Maybe as an alternative, I would be very interested to know which transform on Android cancel the default perspective value set on Android?
