### ISSUE TITLE
android num-pad keyboard extreme lag after typing

### ISSUE THREAD

**Issue by piubellofelipe** [facebook/react-native#22283]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Run `react-native info` in your terminal and paste its contents here.

```
  React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 136.46 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.1.0 - /usr/local/bin/node
      Yarn: 1.0.1 - /usr/local/bin/yarn
      npm: 5.5.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.3, 25.0.0, 26.0.1, 26.0.3, 27.0.3, 28.0.3
        System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.1 => 16.6.1
      react-native: 0.57.5 => 0.57.5
```

## Description
I believe that RN's TextInput has some kind of bug related to "num-pad" or "numeric" keyboard on Android. This bug makes the Android keyboard pretty much unusable after a few minutes of typing straight. Closing the app doesn't help, restarting device does.

## Reproducible Demo
- https://snack.expo.io/SJatzv5aX
- https://github.com/piubellofelipe/num-pad-bug.git

Both the snack.expo and the repo are a simple TextInput with autoFocus and keyboardType='num-pad'. I had to type about ~800 characters before keyboard started to lag. At ~2000 it was pretty much unusable. 
I tested on a Xiaomi Redmi Note 5, Android 8.1.0 and Gboard (default) as device keyboard

I also believe this could be related to #20119, as I discovered this one while trying to solve #20119

**Comment by dfirmino** [comment]
No update for this?

**Comment by piubellofelipe** [comment]
> No update for this?

No, still facing this issue.

Also, I was able to reproduce it on 0.48.0 when using styled textinput (with color, brackgroundColor, fontSize and width). When not using styled textInput, it doesn't happen in 0.48.0

My next solution is to make a native TextInput component myself, or maybe someone has done it already?
