### ISSUE TITLE
Expected "/*" but "A" found 

### ISSUE THREAD

**Issue by Xifeat** [facebook/react-native#22297]
## Environment
 OS : Linux 4.9
 Node : 10.11.0
 npm: 6.4.1
 Watchman: 4.7.0

Packages : (wanted => installed)
   react: 16.3.0 => 16.3.0
   react-native 0.55.0 => 0.55.0

## Description
When I try to link a lib whatever it is I got 

rnpm-install ERR! Something went wrong while linking. Error: Expected "/*" but "A" found.
Please file an issue here: https://github.com/facebook/react-native/issues

Expected "/*" but "A" found.

## Reproducible Demo
We are a lot of people working on this project so i'm not sure when it started, and unfortunatly I can share it. 
But I had the trouble when I added https://github.com/react-native-community/react-native-camera
I tried to upgrade react version but it wasn't fixed with this

**Comment by prasad456** [comment]
I'm facing the same issue 
```
ERROR: 
rnpm-install ERR! Something went wrong while linking. Error: Expected "/* Begin ", "/* End ", "\"", or [A-Za-z0-9_.] but "<" found.
Please file an issue here: https://github.com/facebook/react-native/issues

Expected "/* Begin ", "/* End ", "\"", or [A-Za-z0-9_.] but "<" found.
```

This is my environment details
 React Native Environment Info:
    System:
      OS: Windows 10
      CPU: x64 Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz
      Memory: 1.03 GB / 7.89 GB
    Binaries:
      npm: 6.2.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338

**Comment by Xifeat** [comment]
@prasad456 , I managed to solve the issue by upgrading react native ! 
`react-native upgrade`
then 
`rm -rf node_modules`
`npm install`
`react-native link`
