### ISSUE TITLE
file:///data/user/0/ 的网页无法加载 net::ERR_ACCESS_DENIED 

### ISSUE THREAD

**Issue by zhllucky** [facebook/react-native#22291]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
 React Native Environment Info:
    System:
      OS: Windows 10
      CPU: x64 Intel(R) Core(TM) i7-3632QM CPU @ 2.20GHz
      Memory: 1.56 GB / 7.59 GB
    Binaries:
      Node: 8.9.4 - G:\node\node.EXE
      npm: 5.6.0 - C:\Users\Administrator\AppData\Roaming\npm\npm.CMD
    dependencies:
     "react": "16.6.0-alpha.8af6728",
     "react-native": "0.57.3",

## Description
failed to load internal html file from android emulator In WebView
![tim 20181115211036](https://user-images.githubusercontent.com/25603886/48555013-e9754b80-e91a-11e8-8a1d-8f91f76782c4.jpg)

## Reproducible Demo
<WebView
          ref="chart"
          scrollEnabled={false}
          injectedJavaScript={renderChart(this.props)}
          automaticallyAdjustContentInsets={false}
          style={{
            height: this.props.height || 400,
            backgroundColor: this.props.backgroundColor || 'transparent'
          }}
          scalesPageToFit={false}
          source={(Platform.OS == 'ios') ? require('./tpl.html') : {'uri': 'file:///android_asset/tpl.html'}}
          onMessage={event => this.props.onPress ? this.props.onPress(JSON.parse(event.nativeEvent.data)) : null}
        />

**Comment by IljaDaderko** [comment]
Hard to tell but at a first glance this might nor be react-native error, but rather access issue with file you are requiring?

**Comment by MaxLarue** [comment]
Could it be that you're lacking permissions to access storage? Try giving all permissions to your app throught your phone configuration.

**Comment by zhllucky** [comment]
@MaxLarue I allowed all permissions,its a strange question,now I Repackage again, its right

**Comment by zhllucky** [comment]
@IljaDaderko maybe react-native-webvie,but its right now, thanks

**Comment by joshien1997** [comment]
@zhllucky Have you solve it ??
