### ISSUE TITLE
Keyboard module: what does it's callback receive?

### ISSUE THREAD

**Issue by wzup** [facebook/react-native#22303]
I've read
this https://github.com/facebook/react-native/issues/7969
this https://github.com/facebook/react-native/issues/22168
this https://github.com/facebook/react-native/issues/7986
this https://github.com/facebook/react-native/issues/15387
No answers

https://facebook.github.io/react-native/docs/keyboard

What does keyboard module callback receive? How does the object look? What fields does it have?

```
Keyboard.addListener('keyboardDidShow', result => {
    console.log(result); // What is result? 
});
```

**Comment by nossbigg** [comment]
@wzup I was investigating the code surrounding `Keyboard`, and the `result` is of this shape:
https://github.com/facebook/react-native/blob/e4d7fc06cb74fde24b508212a52a03122de596fa/Libraries/Components/Keyboard/Keyboard.js#L35-L40

Related code files:
- [Apple Developer: Keyboard Notification User Info Keys](https://developer.apple.com/documentation/uikit/uiwindow/keyboard_notification_user_info_keys?language=objc): Keyboard-related events emitted from the device (before it reaches React Native)
- [`RCTKeyboardObserver.m`](react-native/React/Modules/RCTKeyboardObserver.m): The RN code that translates the Apple notifications to the `KeyboardEvent` object

You can also refer to [`KeyboardAvoidingView.js`](react-native/Libraries/Components/Keyboard/KeyboardAvoidingView.js) to see an example of its usage.

Hope this helps :)

**Comment by Liqiankun** [comment]
@wzup Had been solved?
