### ISSUE TITLE
ScrollView retains gap for StatusBar when nested

### ISSUE THREAD

**Issue by jossmac** [facebook/react-native#2230]
I have a ScrollView inside my main View. Is there a way to remove the gap from the top?

My current workaround is to set a negative margin of 20 against the `contentContainerStyle`

**Comment by ide** [comment]
Try setting this to false https://facebook.github.io/react-native/docs/scrollview.html#automaticallyadjustcontentinsets

**Comment by jossmac** [comment]
Perfect! Thank you @ide
