### ISSUE TITLE
Out of memory on press TouchableOpacity

### ISSUE THREAD

**Issue by tufailra97** [facebook/react-native#22327]
## Environment
 Expo CLI 2.4.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.9.4 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338
VS Code

=========

  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
      Memory: 1.06 GB / 7.84 GB
    Binaries:
      Yarn: 1.9.4 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338

## Description
I have a component where I display a button when certain conditions are met (based on component state). 

```
{
      this.state.inputTag !== null && this.state.inputTagFocused ? (
        <TouchableOpacity 
          style = {{backgroundColor : Colors.primary, padding : 15, paddingBottom : 5, paddingTop : 5, borderRadius: 2}}
          onPress = {this.handleAddTags}
        >
          <Text style = {{fontFamily : Fonts.primary, color : Colors.white}}>Add</Text>
        </TouchableOpacity>
      ) : null
    }
```

This is how I am updating the state
```
<TextInput
  style = {{ borderBottomColor : Colors.grey, padding : 15, paddingLeft :0, paddingRight : 0, marginRight : 15}}
  onChange = {(text)=> this.setState({inputTag : text})}
  onFocus = {() => this.setState({inputTagFocused : true})}
  placeholderTextColor = {Colors.grey}
  ref = {(tags) => {this.tags = tags}}
  underlineColorAndroid = 'transparent'
  placeholder = 'Add Tags'
  returnKeyType = 'done'
  multiline = {false}
/>
```
## Expected Behaviour 

- Be able run a function

## Current Behaviour 

- App crashes due 'Out of memory'

## Reproducible Demo
**[Snack](https://snack.expo.io/@tufailra97/onpress-issue-rn)**

## Additional information
Looking through Play store I noticed many recent negative feedback about app using React Native are crashing so I am guessing this is an issue related to React Native core library.

**Comment by tufailra97** [comment]
@react-native-bot  Updated the environment

**Comment by bartolkaruza** [comment]
@tufailra97 could you turn that snack into a minimal example of the problem? There is a lot of stuff around it that makes it hard to see where this issue belongs. If you clean it up a bit, I'll have a look on my end.
