### ISSUE TITLE
 Module `AccessibilityInfo` does not exist in the Haste module map --0.57.5 android

### ISSUE THREAD

**Issue by fantasy525** [facebook/react-native#22326]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
      Memory: 8.72 GB / 15.89 GB
    Binaries:
      Node: 10.13.0 - E:\node\node.EXE
      Yarn: 1.12.3 - E:\program\bin\yarn.CMD
      npm: 6.4.1 - E:\node\npm.CMD

## Description
Describe your issue in detail. Include screenshots if needed. If this is a regression, let us know.

## Reproducible Demo
just do this:
````
react-native init AwesomeProject

yarn install

yarn start

````

**Comment by nitrosalat** [comment]
Encountered the same issue on Mac OS with the same react-native/node configuration

**Comment by fantasy525** [comment]
> Encountered the same issue on Mac OS with the same react-native/node configuration

hello,I use
```
react-native run-android
```
and it work for me.you can try it
for issue above ,because I used android studio to install apk, and I used a browser to open metro's bundle address, and I got this issue,It's kind of weird.
