### ISSUE TITLE
[Image] Loading remote image URLs synchronously is a really bad idea.

### ISSUE THREAD

**Issue by wenkesj** [facebook/react-native#2233]
By far my favorite error via `react-native`:`^0.9.0-rc` @brentvatne. Are there any more funny ones like this?

**Comment by chirag04** [comment]
This could be in docs if not present already. 

@wenkesj I feel like IRC is the right place for this not github issues unless there is a real issue here.

**Comment by wenkesj** [comment]
There should probably be a better explanation, as to something along the lines of  `This will lock up the UI and possibly cause the user to think your app has crashed if the image doesn't download extremely fast.` Or `Loading a URL synchronously on the main thread on the main thread will cause poor performance, try loading the URI asynchronously.`.

**Comment by ide** [comment]
When does this happen? Also we should verify whether this happens with the latest code since @nicklockwood has been working on the image downloader and unifying it with other downloading code.

**Comment by wenkesj** [comment]
Occurs with a direct call to a URI from an Image component - Specifically a gif. Hope this helps, I'm trying to stay active with the community

**Comment by barbatus** [comment]
@ide Movies app in the Examples folder doesn't work with the latest code. Red screen with this message 'Loading remote image URLs synchronously...bad idea'  appears all the time.

**Comment by nicklockwood** [comment]
This was due to a bug in RCTImageLoader, which I thought I had fixed, but apparently not. I'll investigate further.

**Comment by nicklockwood** [comment]
It looks like the fix didn't make it into 0.9. It should be in the next release. If it's causing problems for you, change line 221 in RCTImageLoader from

    id image = RCTGIFImageWithFileURL([RCTConvert NSURL:imageTag]);

to

    id image = RCTGIFImageWithData(data);

**Comment by ms88privat** [comment]
That looks good. 

I have another question still. Is it possible to preload images in an elegant way and use them later with a ImageView?

**Comment by nicklockwood** [comment]
@ms88privat not at the moment - at least, not from JS. You can do it natively by using RCTImageLoader to preload the image. I guess you could wrap that in a module to expose it to JS.

**Comment by ms88privat** [comment]
@nicklockwood hm, I never did something in obj-c before. Maybe I open an issue for it?

**Comment by Sunny-L** [comment]
^0.8.0 it's work ,when this issue fix?
