### ISSUE TITLE
[Feature] Add android 4.1 emulator to test case to avoid future regression

### ISSUE THREAD

**Issue by gengjiawen** [facebook/react-native#22333]
Recent there are two regressions. If we have this, we can spot them early.

Like https://github.com/facebook/react-native/issues/22294.

**Comment by markcriswell1964** [comment]
I think it's doing a great job pointing out the problem and I think that I'm going to find out why Facebook has so many web crashes and react/native I guess that is what you call it

**Comment by dulmandakh** [comment]
Closing this because RN dropped Android 4.x.
