### ISSUE TITLE
getJSMainModuleName automatically adds `.js`

### ISSUE THREAD

**Issue by atrauzzi** [facebook/react-native#22347]
- [✔] Review the documentation: https://facebook.github.io/react-native
  - [✔] Search for existing issues: https://github.com/facebook/react-native/issues
  - [✔] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
      Memory: 6.39 GB / 15.94 GB
    Binaries:
      Yarn: 1.12.1 - C:\Users\atrauzzi\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
```

## Description
I'm using TypeScript in my project, so if I want to change my entrypoint, setting `getJSMainModuleName` to the path of a TypeScript file (with a `.ts` or `.tsx` extension) results in something like `src/Path/To/File.ts.js`.

## Reproducible Demo
Any generic React Native project with TS configured.  Edit [here](https://github.com/atrauzzi/react-native-tinkering/blob/master/android/app/src/main/java/com/reactnativetinkering/MainApplication.java).

**Comment by rickhanlonii** [comment]
Hey @atrauzzi, thanks for filing - this file _has_ to be a javascript file, we can't use a typescript file for this

**Comment by atrauzzi** [comment]
@rickhanlonii - Why not just resolve it as a module and let babel take care of what you get?

**Comment by rickhanlonii** [comment]
@atrauzzi in prod, when this code is run this code has _already been transpiled_ so you couldn't require the ts.
