### ISSUE TITLE
BuildReactNdkLib Failed

### ISSUE THREAD

**Issue by MovieSong** [facebook/react-native#22342]
Android+Windows+SDK(version is ok)+android-ndk-r10e
The log is:
:ReactAndroid:prepareJSC
:ReactAndroid:buildReactNdkLib
make.exe: Entering directory `F:/VE Project/VE8900_APP-11-19/App_Src/src/node_mo
dules/react-native/ReactAndroid/src/main/jni/react/jni'
F:/NDK/android-ndk-r10e/build/core/add-application.mk:49: F:\VE: No such file or
 directory
F:/NDK/android-ndk-r10e/build/core/add-application.mk:49: Project\VE8900_APP-11-
19\App_Src\src\node_modules\react-native\ReactAndroid/src/main/jni/Application.m
k: No such file or directory
Android NDK: NDK_PROJECT_PATH==null.  Please explicitly set APP_BUILD_SCRIPT.

make.exe: Leaving directory `F:/VE Project/VE8900_APP-11-19/App_Src/src/node_mod
ules/react-native/ReactAndroid/src/main/jni/react/jni'
F:/NDK/android-ndk-r10e/build/core/add-application.mk:206: *** Android NDK: Abor
ting.    .  Stop.
:ReactAndroid:buildReactNdkLib FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ReactAndroid:buildReactNdkLib'.
> Process 'command 'F:\NDK\android-ndk-r10e\ndk-build.cmd'' finished with non-ze
ro exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

I can't find any same problem.

**Comment by dingshaoran** [comment]
same issue when build with 0.54.4
