### ISSUE TITLE
[TextInput] Secure Text Entry for TextInput component doesn't update style on state changed.

### ISSUE THREAD

**Issue by andreechristian** [facebook/react-native#22340]
- [✔] Review the documentation: https://facebook.github.io/react-native
  - [✔] Search for existing issues: https://github.com/facebook/react-native/issues
  - [✔] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
      Memory: 63.66 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.1 - ~/.nvm/versions/node/v8.11.1/bin/node
      npm: 6.4.0 - ~/.nvm/versions/node/v8.11.1/bin/npm
      Watchman: 4.6.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        Build Tools: 25.0.2
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.2 => 16.5.2 
      react-native: 0.57.1 => 0.57.1 
    npmGlobalPackages:
      react-native-git-upgrade: 0.2.7

## Description
TextInput wont update style when state changed mid-typing. On the demo, i change text color from red to black upon the value is valid. But it is not reflected on the UI. While if i do not use secureTextEntry, the UI updated just fine.

## Reproducible Demo
https://snack.expo.io/H1eDf3JAX

**Comment by jacobarvidsson** [comment]
I am also experiencing this.

**Comment by ericlewis** [comment]
Fixed by: #23524

**Comment by superstar17** [comment]
I've got same issue on the latest version(0.59.2). It seems it's not been fixed yet.
