### ISSUE TITLE
CameraRoll returns photos if assetType is equal to "Videos"

### ISSUE THREAD

**Issue by indapublic** [facebook/react-native#22341]
- [ x] Review the documentation: https://facebook.github.io/react-native
  - [ x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz
      Memory: 29.58 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-27 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.1 => 16.6.1
      react-native: 0.57.5 => 0.57.5
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description
I receive photos in iOS app, despite the fact that I set assetType: 'Videos'

## Reproducible Demo
```
const defaultParams: GetPhotosParamType = {
    first: 6,
    groupTypes: 'All',
    after: undefined,
};
Promise.all([
    CameraRoll.getPhotos({
    ...defaultParams,
    assetType: 'Photos',
    }),
    CameraRoll.getPhotos({
    ...defaultParams,
    assetType: 'Videos',
    })
]).then(results => {
    console.warn(results[0]);
    console.warn(results[1]);
    console.warn(results[0].edges[0].node.image.uri === results[1].edges[0].node.image.uri);
});
```

![screen shot 2018-11-19 at 16 36 08](https://user-images.githubusercontent.com/856260/48690189-3e65da00-ec19-11e8-8d1e-b606cc7d86be.png)

**Comment by ZackLeonardo** [comment]
+1

**Comment by indapublic** [comment]
@ZackLeonardo FYI I used https://github.com/pentarex/react-native-gallery-manager for those purposes

**Comment by linux08** [comment]
@indapublic have you been able to find a fix, currently experiencing same issue.

**Comment by indapublic** [comment]
@linux08 As I said before, I moved to https://github.com/pentarex/react-native-gallery-manager

**Comment by cpojer** [comment]
This issue has been moved to react-native-community/react-native-cameraroll#15.
