### ISSUE TITLE
Text view missing text only in Device

### ISSUE THREAD

**Issue by finalquest** [facebook/react-native#2235]
Hi.
I've been facing some issues only when running the app on the device.

I have a TextView that render the text "Fin de Acuerdo"

```
<Text style={[styles.noticeLimit, titleColor]}>{this._getAgreementTitle()}</Text>

_getAgreementTitle: function() {
        if(this.props.agreementInfo.isOverdue) {
            return strings.agreementEndTitle;
        } else {
            return strings.agreementStartTitle;
        }
    },
```
In the simulator, everything works fine. I can see the "Fin de Acuerdo" sentence
But in the device, in the string is missing the word "Acuerdo". 
The strange part is that the view frame has the size of the entire sentence, not the cropped one.
If I replace the word "Acuerdo" for "acuerdo" (non capital A), the texts is displayed well. The same happens if I add a white space at the end of the string.

I don't know how to issolate this error, or if anyone else has this issue. 
This is no the only text view that have this type of issue in my app.

Regards

**Comment by ide** [comment]
Can you tell us what version of RN you are using and what kind of device? For device specific issues sometimes the processor architecture makes a difference.

**Comment by finalquest** [comment]
Hi. Sorry that I didnt specify this.
I'm in RN 0.9, but this happens to me also in RN 0.8.
Is an iPhone 6+

**Comment by yamill** [comment]
This happens in my app too. I'm running RN 0.9.
Instead of saying 'Katranada' it says 'Kaytranad'. If I change it to all caps I'm able to see the full name.

![img_3956](https://cloud.githubusercontent.com/assets/755943/9146832/2406a934-3d2e-11e5-9821-d26d236f838c.PNG)

**Comment by brentvatne** [comment]
Closing but happy to reopen if this hasn't been fixed yet, let me know @yamill

**Comment by yamill** [comment]
I think this was resolved @brentvatne - I haven't been having any issues with v0.10.0. Thanks.
