### ISSUE TITLE
Can't find variable: Promise

### ISSUE THREAD

**Issue by cihati** [facebook/react-native#22359]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
Run `react-native info` in your terminal and paste its contents here.
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 2.60 GB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.9.4 - ~/.nvm/versions/node/v8.9.4/bin/node
      Yarn: 1.10.1 - ~/.nvm/versions/node/v8.9.4/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.9.4/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        API Levels: 26, 28
        Build Tools: 27.0.3, 28.0.2
        System Images: android-25 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.1 => 16.6.1
      react-native: 0.57.5 => 0.57.5
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

## Description
Relevant issue/comment (cc @Titozzz ) : https://github.com/facebook/react-native/issues/19827#issuecomment-404156181

As I am trying to upgrade from React Native 0.55.0 to 0.57.5, I am running into issues. Specifically, in Android (no problems in iOS), I am running into this issue:

![image](https://user-images.githubusercontent.com/461998/48788782-73d6fa00-ece3-11e8-9c8c-a0e3fa9446b7.png)

react 16.6.1, react-native 0.57.5

```
yarn why metro
yarn why v1.10.1
[1/4] 🤔  Why do we have the module "metro"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "metro@0.48.3"
info Reasons this module exists
   - "react-native" depends on it
   - Hoisted from "react-native#metro"
   - Hoisted from "react-native#metro#metro-config#metro"
```

Any ideas how to resolve the problem?

## Reproducible Demo
Let us know how to reproduce the issue. Include a code sample, share a project, or     share an app that reproduces the issue using https://snack.expo.io/. Please follow the guidelines for providing a MCVE: https://stackoverflow.com/help/mcve

**Comment by thymikee** [comment]
React Native 0.57 is not actively maintained anymore. Can you try upgrading to 0.59? It should be fixed there.

**Comment by cihati** [comment]
I've already updated, and I don't see this issue anymore.
