### ISSUE TITLE
Text on Android has shadow by default

### ISSUE THREAD

**Issue by lukasgeiter** [facebook/react-native#22367]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Description
On Android, all text has a faint shadow. This is barely noticeable in most cases but becomes visible with light colored text. As an extreme example, this is "Test" in white font on white background:

![image](https://user-images.githubusercontent.com/5907946/48830851-d678d600-ed75-11e8-8eb9-cd82091112f8.png)

I would expect the text to be completely invisible but instead there is a faint shadow.

## Cause

This is a regression which has been introduced by b7ba2255df109b9cb8999d0e1584bc2b95a4e07c and is present since version 0.57.2.
The problem is that the default value for `textShadowRadius` is `1`. I'm not sure why that is, but I think it probably should be `0` which would solve this issue.

## Workaround

The workaround is to manually set the radius to 0:
```jsx
<Text style={{ textShadowRadius: 0 }}>
    Test
</Text>
```

**Comment by lukasgeiter** [comment]
@react-native-bot Issue updated, please reopen.

**Comment by sterlingwes** [comment]
Seems related to https://github.com/facebook/react-native/issues/21507

**Comment by lukasgeiter** [comment]
@sterlingwes It definitely is. I've retested with v0.57.8 and it's fixed, so this issue can stay closed 🙂
