### ISSUE TITLE
Wrong ripple color in Switch component

### ISSUE THREAD

**Issue by luissmg** [facebook/react-native#22370]
- [X] Review the documentation: https://facebook.github.io/react-native
- [X] Search for existing issues: https://github.com/facebook/react-native/issues
- [X] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
React Native Environment Info:
  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 8.03 GB / 15.91 GB
  Binaries:
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.1.0.0 AI-173.4907809
```
## Description
I configure a different color for my `Switch` component with the props `trackColor` and `thumbColor`. When I press the switch to change it's value, the color on the ripple is completely different from the one configured with the props.
The bug only occurs on Android platform with the ripple and with the background color when the state is changing, After the animation ends, the background color assume the custom color I configured.

**Comment by radko93** [comment]
Can you please provide a repro for this (best would be expo snack)?

**Comment by luissmg** [comment]
Sure @radko93. Sorry for not answering in a short period.
Here it is. As I said, I am testing it on real device.
https://snack.expo.io/@luis.gouveia/wrong-switch-color

**Comment by kelset** [comment]
👋 there.

It looks like this issue still happens on RN 0.59.

I've tried looking around but the Android Switch looks correct -> https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/switchview/ReactSwitch.java

It would be great if you could take a closer look at what in this implementation doesn't set the `mTrackColorForTrue` 🤔 We'll probably only be able to take a closer look in the next few months.

**Comment by darron1217** [comment]
This issue still exists in `0.63.3`.
Is there any workaround for it?

**Comment by yum650350** [comment]
Follow the hint gave by @kelset,
adding codes below in `ReactSwitch.java` fix this issue

```diff
   public void setThumbColor(@Nullable Integer color) {
     setColor(super.getThumbDrawable(), color);
+
+    // Set the ripple color with thumb color
+    RippleDrawable ripple = (RippleDrawable) super.getBackground();
+    ColorStateList customColorState = new ColorStateList(
+      new int[][]{ new int[]{ android.R.attr.state_pressed } },
+      new int[]{color});
+
+    ripple.setColor(csl);
+    super.setBackground(drawable);
   }
```

Screenshot
![ripple_fixed](https://user-images.githubusercontent.com/48589760/103485934-ff189880-4e34-11eb-9eba-dc9e0c53f449.gif)


But I'm not sure is this a good practice.

**Comment by yum650350** [comment]
Follow the hint gave by @kelset,
adding codes below in `ReactSwitch.java` fix this issue

```diff
   public void setThumbColor(@Nullable Integer color) {
     setColor(super.getThumbDrawable(), color);
+
+    // Set the ripple color with thumb color
+    RippleDrawable ripple = (RippleDrawable) super.getBackground();
+    ColorStateList customColorState = new ColorStateList(
+      new int[][]{ new int[]{ android.R.attr.state_pressed } },
+      new int[]{color});
+
+    ripple.setColor(customColorState);
+    super.setBackground(ripple);
   }
```

Screenshot
![ripple_fixed](https://user-images.githubusercontent.com/48589760/103485934-ff189880-4e34-11eb-9eba-dc9e0c53f449.gif)


But I'm not sure is this a good practice.

**Comment by yum650350** [comment]
Follow the hint gave by @kelset,
adding codes below in `ReactSwitch.java` fix this issue

```diff
   public void setThumbColor(@Nullable Integer color) {
     setColor(super.getThumbDrawable(), color);
+
+    // Set the ripple color with thumb color
+    RippleDrawable ripple = (RippleDrawable) super.getBackground();
+    ColorStateList customColorState = new ColorStateList(
+      new int[][]{ new int[]{ android.R.attr.state_pressed } },
+      new int[]{color});
+
+    ripple.setColor(customColorState);
   }
```

Screenshot
![ripple_fixed](https://user-images.githubusercontent.com/48589760/103485934-ff189880-4e34-11eb-9eba-dc9e0c53f449.gif)


But I'm not sure is this a good practice.

**Comment by yum650350** [comment]
Follow the hint gave by @kelset,
adding codes below in `ReactSwitch.java` fixes this issue

```diff
   public void setThumbColor(@Nullable Integer color) {
     setColor(super.getThumbDrawable(), color);
+
+    // Set the ripple color with thumb color
+    RippleDrawable ripple = (RippleDrawable) super.getBackground();
+    ColorStateList customColorState = new ColorStateList(
+      new int[][]{ new int[]{ android.R.attr.state_pressed } },
+      new int[]{color});
+
+    ripple.setColor(customColorState);
   }
```

Screenshot
![ripple_fixed](https://user-images.githubusercontent.com/48589760/103485934-ff189880-4e34-11eb-9eba-dc9e0c53f449.gif)


But I'm not sure is this a good practice.

**Comment by kelset** [comment]
Thanks cool, @yum650350 - could you maybe submit a PR with the fix? I can't make promises on when it'd get merged but 🤞

**Comment by yum650350** [comment]
@kelset Here's the PR
