### ISSUE TITLE
CPU spikes to 100% in an infinite While loop

### ISSUE THREAD

**Issue by sghiassy** [facebook/react-native#2237]
I'm seeing a problem where the app locks and the CPU throttles to 100% infinitely.

#### Sample App
Here is a sample repo that you can download. The app is only 140 lines long, but reproduces the issue 100%: https://github.com/sghiassy/react-bug

![CPU Profiler](http://cl.ly/image/3d2k1j2p1L1Q/Screen%20Shot%202015-08-05%20at%202.22.25%20PM.png)

#### Cause
I'm not 100% sure what the issue is, but I've tracked it down to file `Layout.c`'s `while` loop on line 455.

**Comment by jaygarcia** [comment]
renderScene gets called twice, forcing two copies of DetailPage to get rendered.

**Comment by ide** [comment]
I believe this is a known bug :( 
I don't remember the specifics off the top of my head but search the issues for "flex cpu" and I think you'll find similar issues.

**Comment by sghiassy** [comment]
Thanks for the tip @ide . I found some similar issues:
  * https://github.com/facebook/react-native/issues/1378
  * https://github.com/facebook/react-native/issues/2221 (closed)
  * https://github.com/facebook/react-native/issues/824 (closed)

Its of interest to note that each of the issues reports 100% pegging in `Layout.c` but the cause / repo steps seem to differ.

**Comment by ide** [comment]
Interesting. Unfortunately I can't tell you when this will be fixed or whether this is a priority for Facebook but it does seem important and more data points are helpful. Thanks for your report.

**Comment by ide** [comment]
A 100% CPU bug in css-layout has been patched in 0.10 and 0.11-rc.

**Comment by browniefed** [comment]
@ide close since it's fixed.
