### ISSUE TITLE
React native picker dropdown icon doesn't change the position on rtl

### ISSUE THREAD

**Issue by sreehari95** [facebook/react-native#22389]
## Environment
React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
      Memory: 2.86 GB / 7.89 GB
    Binaries:
      npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338

## Description
on ltr the dropdown icon on the right side but on changed to rtl the label changed its position but the dropdown icon still on the right side 

## Reproducible Demo
![screenshot_1542954931](https://user-images.githubusercontent.com/35726184/48933242-98221900-ef25-11e8-8b5f-439559ede9f4.png)

**Comment by bartolkaruza** [comment]
Are both iOS and Android behaving the same with regards to the indicator? the `<Picker />` component is a wrapper for the native iOS [UIPickerView](https://developer.apple.com/documentation/uikit/uipickerview) and the native Android [Spinner](https://developer.android.com/reference/android/widget/Spinner). Neither mention RTL support or options.
