### ISSUE TITLE
Mock StatusBarManager is missing getHeight() method

### ISSUE THREAD

**Issue by marecar3** [facebook/react-native#22385]
> React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
      Memory: 110.67 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        API Levels: 23, 26, 27, 28
        Build Tools: 26.0.2, 26.0.3, 27.0.3, 28.0.2, 28.0.3
        System Images: android-27 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.1 => 16.6.1 
      react-native: 0.57.5 => 0.57.5 

`StatusBarManager`[ is missing getHeight()](https://github.com/facebook/react-native/blob/master/jest/setup.js#L228) when running `jest`, which result in failed tests.

Thanks.

**Comment by bartolkaruza** [comment]
It looks like the [Android implementation](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/modules/statusbar/StatusBarModule.java) also doesn't have this method and I can't find any references to that function being called from anywhere in the React Native code base. Are you directly calling this method in your code? If so, I suspect it will cause runtime issues on Android.

**Comment by marecar3** [comment]
Hey @bartolkaruza,

Thanks for the fast response.

> Are you directly calling this method in your code?

No, we are calling this method in `file.ios.js` and purpose of using it is to get status bar height which can be different on iPhone X devices, as `KeyboardAvoidingView` won't work good with top of keyboard components if you don't set `keyboardVerticalOffset ` with + `statusBarHeight`.

**Comment by bartolkaruza** [comment]
Ok, so maybe you can resolve this issue by simply using the `HEIGHT` constant instead of the method?
That one should work even in jest tests if you look at this old issue:
https://github.com/facebook/react-native/issues/11701

**Comment by marecar3** [comment]
Ok thanks @bartolkaruza!

**Comment by rickhanlonii** [comment]
Nice, thanks @bartolkaruza!
