### ISSUE TITLE
position:"absolute" not working in android

### ISSUE THREAD

**Issue by d12544** [facebook/react-native#22382]
the green circle needs to be above the card.
`<View style={{ marginTop: 10, flex: 1 }}>
       <View style={{ position: "absolute",zIndex:1,right:0,height:20,width:20}}>
              <View
                style={[
                  styles.circle,
                  {
                    backgroundColor: color.GREEN,
                    alignItems: "center",
                    height: 20,
                    width: 20,
                    borderRadius: 10
                  }
                ]}
              >
                <Image
                  style={{
                    width: 10,
                    height: 10,
                    resizeMode: "contain",
                    alignItems: "center",
                    marginTop: 5
                  }}
                  source={like}
                />
              </View>
            </View>
        <Card containerStyle={{ padding: 5, margin: 5, flex: 1,zIndex:0 }}>
          <Text
            style={[
              styles.title_carddetail,
              {
                color: color.BLACK,
                marginLeft: 8,
                fontWeight: "normal",
                fontSize: 13
              }
            ]}
          >
            {item.Compname}
          </Text>
          <View style={{ flexDirection: "row", marginTop: 5 }}>
            <Text style={[styles.title, { flex: 1 }]}>% Weight : </Text>
            <Text
              style={[
                styles.title_carddetail,
                {
                  color: color.BLACK,
                  marginLeft: 8,
                  fontWeight: "normal",
                  fontSize: 10,
                  flex: 1
                }
              ]}
            >
              {parseFloat(item).toFixed(2)}%
            </Text>
          </View>
          <View style={{ flexDirection: "row" }}>
            <Text style={[styles.title, { flex: 1 }]}>Value : </Text>
            <Text
              style={[
                styles.title_carddetail,
                {
                  color: color.BLACK,
                  marginLeft: 8,
                  fontWeight: "normal",
                  fontSize: 10,
                  flex: 1
                }
              ]}
            >
              {parseFloat(item/ 100).toFixed(3)} Cr
            </Text>
          </View>
        </Card>
       
      </View>`

![1542892295104](https://user-images.githubusercontent.com/43203698/48905188-de746b00-ee86-11e8-86d4-5824b712175d.JPEG)

**Comment by luissmg** [comment]
First of all, use the template.
Second, please close your tags and make sure you are positioning everything correctly. As far as one can understand what you posted, your code won't work because you are not doing it right.
