### ISSUE TITLE
[Packager] Feature request: Support for patching global apis

### ISSUE THREAD

**Issue by uber5001** [facebook/react-native#2238]
It would be convenient to be able to fill in any gaps in the JavaScriptCore environment with custom patches, so that any dependencies that expect to be running in v8 with node.js APIs can function properly.

`url` is one of the modules exposed by the Node.js APIs. `require('url')` doesn't seem to work within React Native. There's also a module on npm called `url` that is meant to be a browserify replacement for node's `url`. I want to be able to use this as a replacement for Node's `url`.

For most cases, just `npm install url` will fix the problem. This even fixes my issue directly, which is that one of my sub-dependencies is `url`. This falls apart when my dependency that depends of `url` gets de-duped by npm when the module I'm working on gets installed by someone else. (Let me know if I need to explain this in detail)

I'm not sure how this would be exposed. Perhaps something along the lines of

    require('react-native').patchModule('url', require('url'));

which would cause all `require('url')` to use the globally patched version provided.

**Comment by browniefed** [comment]
There was a proposal for the packager to read the package.json to get modules you specify for react-native specifically.

**Comment by uber5001** [comment]
@browniefed, do you have a link to the proposal? I can't seem to find it.

**Comment by browniefed** [comment]
@uber5001 my memory is failing me.
However I think it may have been #1871
Which links to this package over here https://github.com/tradle/react-native-level-fs

The concept being

```
{
    ...
    "react-native": {
       "url": "react-native-level-fs" 
    }
    ...
}
```

**Comment by browniefed** [comment]
@uber5001 found it #2208

**Comment by brentvatne** [comment]
#2208 seems to cover this nicely, great call @browniefed. @uber5001 ping me if that's not the case
