### ISSUE TITLE
device overheated by CameraRoll API with FlatList in iOS

### ISSUE THREAD

**Issue by vreality64** [facebook/react-native#22393]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
      Memory: 275.75 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.1 => 16.6.1
      react-native: 0.57.5 => 0.57.5
```

## Description
If I shows photo image using the CameraRoll API on an iOS device, there is an issue that causes excessive heat. I was profiling directly with Xcode and it was happening when I showed the `assets-library` picture through the Image component. If shows gallery view a few times, iPhone gets hot enough to notice. Is this a known bug?

If you look at the simple profiling results, the CPU is being used excessively when view renders photos. I think maybe it is the cause.

![cpu profiling with xcode](https://user-images.githubusercontent.com/886706/48934895-180daa80-ef49-11e8-9f3a-459c2a68042b.gif)

## Reproducible Demo

Here are [expo link](https://snack.expo.io/@ianpark/cameraroll-api-example) or [Github repository](https://github.com/vreality64/react-native-camera-roll-example)

**Comment by vreality64** [comment]
I updated environment information. I'm using newest version (0.57.x) 😃

**Comment by cpojer** [comment]
This issue has been moved to react-native-community/react-native-cameraroll#14.
