### ISSUE TITLE
Activity class {xxx.MainActivity} does not exist

### ISSUE THREAD

**Issue by Nocturne-FFG** [facebook/react-native#22405]
- [ ] Review the documentation: https://facebook.github.io/react-native
  - [ ] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
mac os 10.14
react native 0.57.5
npm 4.5
node 8.11.1
![image](https://user-images.githubusercontent.com/45280212/48984013-4a79fc00-f131-11e8-8279-42c814ae675c.png)

## Description
It used to work, everything started with the addition of "react-native-amap3d", and I tried many of the methods here, but it didn't change. In addition, I found that my application was successfully installed, but I can't see it in the menu, I can only see it in the application, and I can't run it.
![image](https://user-images.githubusercontent.com/45280212/48984023-5665be00-f131-11e8-9f92-637cef4286e9.png)

I just got into programming. This problem has delayed me for 4 days. I hope I can find the answer here. Thank you all.

## Reproducible Demo
1、react-native init app (0.57.5)
2、npm i react-native-amap3d --save
3、react-native run-android

**Comment by bartolkaruza** [comment]
Have you tested the reproducible demo? Does it actually cause the exact same issue?

**Comment by Nocturne-FFG** [comment]
@bartolkaruza 
Yes, I have tested this problem all the time.
And I tested different phones

**Comment by Nocturne-FFG** [comment]
@react-native-bot 
![image](https://user-images.githubusercontent.com/45280212/48994766-ddda1e00-f17f-11e8-98a7-4f36d386ff54.png)

**Comment by Nocturne-FFG** [comment]
I may have come to the wrong place. He may be related to the "amap3d" plugin.
