### ISSUE TITLE
map.reverse function is showing inconsistent behaviour between Android and IOS. container has position =' absolute'

### ISSUE THREAD

**Issue by vivek1623** [facebook/react-native#22401]
- [ ] Review the documentation: https://facebook.github.io/react-native
  - [ ] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
      Memory: 1.97 GB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.12.0 - /usr/local/opt/node@10/bin/node
      npm: 6.4.1 - /usr/local/opt/node@10/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description
 Expected behaviour: -
i am trying to create tinder like swipe animation. all card should be stack. 1st card should be on the top of stack and last card should be on bottom. 

Actual Behaviour: -
in IOS it is working fine as i describe above.
![screen shot 2018-11-25 at 11 42 58 am](https://user-images.githubusercontent.com/30700350/48976139-66d15680-f0a7-11e8-9888-d7b83a297092.png)

in Android it is showing wrong order. 1st item goes on the bottom and 2nd item is showing on the top.
![android_bud](https://user-images.githubusercontent.com/30700350/48976129-12c67200-f0a7-11e8-9157-65ff6407fb95.jpeg)

## Reproducible Demo
you can clone my project and test this issue 
https://vivek1623@bitbucket.org/my-project-1623/swipe.git

you can also see the exactly similar issue online here
`https://snack.expo.io/@cclem65/swipe`

**Comment by dulmandakh** [comment]
Hello there 👋 this issue doesn't have a repro (which means, a `react-native init`-ed project with the minimal changes that leads to creating the same issue you are reporting). Unfortunately, I have no way of helping you in a meaningful way – there is no easy way for me to recreate the situation and check that the issue reported is still there when changing the code.

Because of this, we are going to close this issue - but if a repro is shared, we are happy to reopen it 🤗
