### ISSUE TITLE
After eject from Expo AsyncStorage can't see any data

### ISSUE THREAD

**Issue by Overtorment** [facebook/react-native#22400]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Run `react-native info` in your terminal and paste its contents here.

```
  React Native Environment Info:
    System:
      OS: Linux 4.18 elementary OS 0.4.1 Loki
      CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
      Memory: 180.82 MB / 15.43 GB
      Shell: 4.3.48 - /bin/bash
    Binaries:
      Node: 11.0.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
    SDKs:
      Android SDK:
        API Levels: 25, 26, 27, 28
        Build Tools: 23.0.1, 26.0.1, 26.0.3, 27.0.3, 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom_64, android-P | Google APIs Intel x86 Atom
    npmPackages:
      react: ^16.6.3 => 16.6.3 
      react-native: ^0.57.5 => 0.57.5 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-rename: 2.3.2
```

## Description

After ejecting from Expo and doing testflight build, I install the app on device. App sees no data at all.
If I revert to previous build via testflight (build that is still on Expo) - all data is there, so I assume there are some kind of separate namespaces for pure RN and Expo RN.
I would really like it to be the same namespace, as users who update to our newest build with shiny new pure RN will have all their data lost.

**Comment by bartolkaruza** [comment]
@Overtorment can you post this on [expo](https://github.com/expo/expo) please? This looks like a specific Expo issue to me.

**Comment by Overtorment** [comment]
Yep, looks like different folders.

Pure RN: /Documents/RCTAsyncLocalStorage_V1/
Expo: /Documents/ExponentExperienceData/%40anonymous%2Fbluewallet-c4b47811-ba78-4320-96f9-1f7db4ad0523/RCTAsyncLocalStorage/

Is threre a way to 'pin' folder folder AsyncStorage works with..?

**Comment by bartolkaruza** [comment]
I've given some pointers at expo/expo#2805 , the expo developers should be able to help you along there.

@kelset close :)
