### ISSUE TITLE
ExceptionsManager.js:76 TypeError: instance.render is not a function  This error is located at:     in AppContainer (at renderApplication.js:33)

### ISSUE THREAD

**Issue by anehkumar** [facebook/react-native#22418]
- [ ] Review the documentation: https://facebook.github.io/react-native
  - [ ] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
      Memory: 33.46 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
      Android SDK:
        API Levels: 15, 22, 25, 26, 27, 28
        Build Tools: 19.1.0, 22.0.1, 26.0.3, 27.0.3, 28.0.2, 28.0.3
        System Images: android-26 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5014246
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.1 => 16.6.1 
      react-native: 0.57.5 => 0.57.5 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description
Unable to run the application on Android device get this error but the application is working in IOS

## Reproducible Demo
Here is my package.json file
{
  "name": "Sample",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "axios": "^0.18.0",
    "native-base": "^2.8.1",
    "prop-types": "^15.6.2",
    "react": "16.6.1",
    "react-native": "0.57.5",
    "react-native-custom-radio-group": "^1.0.1",
    "react-native-datepicker": "^1.7.2",
    "react-native-gesture-handler": "^1.0.9",
    "react-native-material-dropdown": "^0.11.1",
    "react-native-simple-dialogs": "^1.0.0",
    "react-native-slideshow": "^1.0.1",
    "react-native-vector-icons": "^6.1.0",
    "react-navigation": "^3.0.0"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.49.2",
    "react-test-renderer": "16.6.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by edanedison** [comment]
Also getting this issue, but with IOS. Brand new app, using react-native (0.57.8).

**Comment by dulmandakh** [comment]
Hello there 👋 this issue doesn't have a repro (which means, a `react-native init`-ed project with the minimal changes that leads to creating the same issue you are reporting). Unfortunately, I have no way of helping you in a meaningful way – there is no easy way for me to recreate the situation and check that the issue reported is still there when changing the code.

Because of this, we are going to close this issue - but if a repro is shared, we are happy
