### ISSUE TITLE
EXC_BAD_ACCESS app crash

### ISSUE THREAD

**Issue by ZLJASON** [facebook/react-native#22415]
## Environment
React Native Environment Info:
    System:
      OS: macOS Sierra 10.12.6
      CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 50.82 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.6.0 - /usr/local/bin/node
      npm: 6.2.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.2, macOS 10.13, tvOS 11.2, watchOS 4.2
      Android SDK:
        API Levels: 26, 27, 28
        Build Tools: 26.0.3, 27.0.3, 28.0.3
        System Images: android-23 | Google APIs ARM EABI v7a, android-25 | Google APIs ARM 64 v8a, android-26 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 9.2/9C40b - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1
      react-native: 0.56.0 => 0.56.0
    npmGlobalPackages:
      react-native-cli: 2.0.1
## Description
The app crash runing  on iOS 12  
shceme debug is ok,but  shceme set release ,app crash.

crash log:

Exception Type:  EXC_BAD_ACCESS (SIGBUS)
Exception Subtype: KERN_PROTECTION_FAILURE at 0x00000002370319b8
VM Region Info: 0x2370319b8 is in 0x2370304f0-0x237039968;  bytes after start: 5320  bytes before end: 32687
      REGION TYPE                      START - END             [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      unused shlib __DATA    00000002370304e8-00000002370304f0 [     8] rw-/rw- SM=COW  ... this process
--->  __DATA_DIRTY           00000002370304f0-0000000237039968 [   37K] rw-/rw- SM=COW  ...oreFoundation
      __DATA_DIRTY           0000000237039968-000000023703c438 [   11K] rw-/rw- SM=COW  ...ork/CFNetwork

Termination Signal: Bus error: 10
Termination Reason: Namespace SIGNAL, Code 0xa
Terminating Process: exc handler [1860]
Triggered by Thread:  9

Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0:
0   libdispatch.dylib             	0x00000001fd7a6618 _os_object_release$VARIANT$mp + 0
1   UIKitCore                     	0x000000022ae7a000 _afterCACommitHandler + 228
2   CoreFoundation                	0x00000001fdd5b7a8 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 32
3   CoreFoundation                	0x00000001fdd5643c __CFRunLoopDoObservers + 412
4   CoreFoundation                	0x00000001fdd569dc __CFRunLoopRun + 1264
5   CoreFoundation                	0x00000001fdd561cc CFRunLoopRunSpecific + 436
6   GraphicsServices              	0x00000001fffcd584 GSEventRunModal + 100
7   UIKitCore                     	0x000000022ae51054 UIApplicationMain + 212
8   sxgk                          	0x000000010425bd48 main + 32072 (main.m:14)
9   libdyld.dylib                 	0x00000001fd816bb4 start + 4

**Comment by ZLJASON** [comment]
## Environment
React Native Environment Info:
    System:
      OS: macOS Sierra 10.12.6
      CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 50.82 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.6.0 - /usr/local/bin/node
      npm: 6.2.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.2, macOS 10.13, tvOS 11.2, watchOS 4.2
      Android SDK:
        API Levels: 26, 27, 28
        Build Tools: 26.0.3, 27.0.3, 28.0.3
        System Images: android-23 | Google APIs ARM EABI v7a, android-25 | Google APIs ARM 64 v8a, android-26 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 9.2/9C40b - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1
      react-native: 0.56.0 => 0.56.0
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by ZLJASON** [comment]
update new version

**Comment by zeekay18** [comment]
@ZLJASON Please how did you fix this problem. Thanks
