### ISSUE TITLE
RN only applying some of the external styles

### ISSUE THREAD

**Issue by zocodia** [facebook/react-native#22438]
## Environment
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-3427U CPU @ 1.80GHz
      Memory: 69.05 MB / 4.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
    IDEs:
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.6.1 => 16.6.1
      react-native: 0.57.5 => 0.57.5
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1

## Description
I have an external StyleSheet which I import to use in my code. The problem is that one component refuses to acknowledge there's a style with a certain name. Using the imported style doesn't work but using the exact same properties on the local style={{}} for the component does work. 

-- the style headerWallet is working but contentWallet is not..

## App.js

```javascript
import { styles } from './../styles/mainStyles'
  ...

  render() {
    const { moveY, aHeight, bHeight } = this.state

    return (
      <View style={{ flex: 1, alignItems: 'center', backgroundColor: '#1F1F1F' }}>


        <View style={ [styles.contentWallet, { height: bHeight, top: moveY + (aHeight - 20) }] }>
          <Button title='Remove' color='#ff0000' onPress={() => this.deleteItem() } />
        </View>
        

        <TouchableOpacity
          style={ [styles.headerWallet, { height: aHeight, top: moveY }] }
          onPress={() => {
            this.collapse()
          }}
          >

          <Text>Go To Home</Text>
        </TouchableOpacity>


      </View>
    )
  }
  
  ...
```

## mainStyles.js
```javascript
import React, { StyleSheet } from 'react-native'

export default StyleSheet.create({
  wallet: {
    width: 330,
    height: 130,
    backgroundColor: 'skyblue',
    borderRadius: 15,
  },
  headerWallet: {
    width: 330,
    position: 'absolute',
    backgroundColor: 'skyblue',
    borderRadius: 15,
  },
  deleteButton: {
    width: 100,
    height: 130,
    borderRadius: 15,
    marginTop: 20,
  },
  contentWallet: {
    width: 320,
    borderRadius: 15,
    alignItems: 'center',
    backgroundColor: '#333333',
  },
})
```

**Comment by bartolkaruza** [comment]
Your import `import { styles } from ...` should be `import styles from ...` if you use a default export in main styles. If you want to use a named import, you should `export const styles = StyleSheet...`.

@kelset close :)

**Comment by zocodia** [comment]
> Your import `import { styles } from ...` should be `import styles from ...` if you use a default export in main styles. If you want to use a named import, you should `export const styles = StyleSheet...`.
> 

When I use `import styles from ...` I get an error saying that that specific style is undefined. And when I use a named export the that one style doesn't get applied.
