### ISSUE TITLE
SafeAreaView not working in Newer Iphones(iPhone Xs Max, iPhone XR, iPhone Xs)

### ISSUE THREAD

**Issue by siddhantjaiswal9098** [facebook/react-native#22431]
- [ ] Review the documentation: https://facebook.github.io/react-native
  - [ ] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
OS: macOS High Sierra 10.13.6
  Node: 8.11.3
  Yarn: 1.9.4
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: 10
  Android Studio: 3.2 AI-181.5540.7.32.5014246

## Description
-Also Bottom Tab navigator is also not Working.(Note: Works with the iPhone X fine)

**Comment by bartolkaruza** [comment]
Can you post the import you are using for `SafeAreaView`? I remember having issues with the pure JS version of `SafeAreaView` included in React Navigation. That one was hard coding the height of the iPhone X, which changed for the XS/... 

If you are using the RN version one `import {SafeAreaView} from 'react-native'`, you shouldn't have any issues on the latest versions of React Native.

**Comment by radko93** [comment]
@siddhantjaiswal9098 please post your which RN version you use and if you use React Navigation also post a version of this library. We cannot help you if you're not using the latest React Native version.
@bartolkaruza XS and other new models are now working also fine with JS-based solution

**Comment by siddhantjaiswal9098** [comment]
@radko93 i am using RN :- 0.55.4

**Comment by siddhantjaiswal9098** [comment]
@bartolkaruza yes i am importing SafeAreaView from react-native but issue still persist
