### ISSUE TITLE
Can't find variable: document

### ISSUE THREAD

**Issue by leoabacade** [facebook/react-native#2244]
I am trying to use react-intl-tel-input (http://patw0929.github.io/react-intl-tel-input/) in my React-Native project,
but I get the error of "Can't find variable: document"

Is there any work around or components to use this react components in react-native?

**Comment by a2** [comment]
It doesn't work because <IntlTelInput /> assumes it is running on a webpage and it renders to HTML.

**Comment by Petermuturi** [comment]
Did anyone find a solution to this?
