### ISSUE TITLE
Click and hold to select text using a text component on iOS

### ISSUE THREAD

**Issue by ArsenyYankovsky** [facebook/react-native#22458]
## Environment
```
 React Native Environment Info:
    System:
      OS: macOS 10.14.1
      CPU: x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 334.21 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.7.0 - ~/.nvm/versions/node/v10.7.0/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.3.0 - ~/.nvm/versions/node/v10.7.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.4.1 => 16.7.7 
      @types/react-native: ^0.57.14 => 0.57.14 
      react: 16.5.1 => 16.5.1 
      react-native: ^0.57.7 => 0.57.7 
```

## Description
I want click-and-hold-to-select-text using a Text component and then i searched it and i found `selectable` property.It good works but it copy the entire text field.I want to selecting a subset of the text field for copying.Actually this question is asked on stackoverflow .Here is question on stackoverflow:http://stackoverflow.com/a/37119619/4596143
### Reproduction Steps and Sample Code
I try this code block:

```
<Text
                        selectable={true}
                        style={styles.messageBody}>
                        {"text description"}
</Text>
```
This full of text ("text description") can copy not partially .I want to it like screenshot
 
**Actual behaviour:**
![image](https://cloud.githubusercontent.com/assets/5556159/25989281/277d68a6-3704-11e7-9b78-59b9590da818.png)
 
**Expected behavior:**
 
![image](https://cloud.githubusercontent.com/assets/5556159/25989290/2d178d46-3704-11e7-9415-9bf76e7d1b2a.png)
 
## Reproducible Demo
I don't have a reproducible demo but should be pretty easy to create one.

I'm creating this because #13938 was closed but it's still an issue for a lot of people. Would be really nice if bot reopened closed issues if there's an activity on them because there's a lot of them.

**Comment by fakenickels** [comment]
You can use this https://github.com/Astrocoders/react-native-selectable-text/
```js
import { SelectableText } from "react-native-selectable-text";

// Use normally, it is a drop-in replacement for react-native/Text
<SelectableText
  menuItems={["Foo", "Bar"]}
  onSelection={({ eventType, content, selectionStart, selectionEnd }) => {}}
  value="I crave star damage"
/>;
```

it is for extracting and changing the selection menu but we implemented a way for you to select a subset of it
