### ISSUE TITLE
Metro Bundler's "Looking for JS files in" not listing all linked project directories

### ISSUE THREAD

**Issue by jerinho** [facebook/react-native#22469]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment (`react-native info`)
Environment:
- OS: Windows 10
- Node: 8.11.4
- Yarn: 1.9.4
- npm: 6.4.1

Packages: (wanted => installed)
- react: 16.6.1 => 16.6.1
- react-native: 0.57.7 => 0.57.7

## Description
Metro bundler does not lists all the project directories. Latest older version this is working is 0.52.4, where it looks like this.
```
Looking for JS files in
C:\Users\USER\Desktop\test
C:\Users\USER\AppData\Local\Yarn\Data\link\react-native-mylibrary
```
The misbehave is followed by error `Unable to resolve module react-native-mylibrary` produced by the import part of js code.

## Reproducible Demo
Just follow this [instructions](https://facebook.github.io/react-native/docs/native-modules-android)

**Comment by grabbou** [comment]
Thank you for sending it. Please open this issue in https://github.com/facebook/metro repository so the dedicated team of Metro experts can look into the issue.
