### ISSUE TITLE
Memory usage when setting borderWidth style prop

### ISSUE THREAD

**Issue by FranDepascuali** [facebook/react-native#22488]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ ] Use the latest React Native release: https://github.com/facebook/react-native/releases
(Using 0.56)
## Environment
Run `react-native info` in your terminal and paste its contents here.

```
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 109.26 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.9.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.2 => 16.4.2
      react-native: neiker/react-native#3ed7bc7bce0375effbc0d4b5e18842c3b3852e4c => 0.56.0
    npmGlobalPackages:
      eslint-plugin-react-native: 3.2.1
      react-native-cli: 2.0.1
```

## Description
When using `borderWidth` prop in a view style, there is a spike in ram memory consumption. We have several components (~60) rendered with this prop. Thus crashes the app because of the suddenly high memory consumption. 

### Screencast
![memory-leak-borderwidth](https://user-images.githubusercontent.com/12101394/49391803-7423bc00-f70b-11e8-898c-c3960a6a977d.gif)

### Screenshot
<img width="978" alt="screen shot 2018-12-03 at 14 52 36" src="https://user-images.githubusercontent.com/12101394/49392006-fb712f80-f70b-11e8-8500-4c41868d484e.png">

## Reproducible Demo
This is a tricky one, try using a lot of views with `borderWidth`. https://github.com/facebook/react-native/issues/22221 related

**Comment by radeno** [comment]
@FranDepascuali is still an issue with latest RN 0.59?
If so then it should be classified as important.
