### ISSUE TITLE
[InteractionManager] What are the best practices around using InteractionManager?

### ISSUE THREAD

**Issue by paramaggarwal** [facebook/react-native#2248]
I searched the code base and no one is using `runAfterInteractions` currently. I see that the `Animated` library is setting `createInteractionHandle` correctly. I can't seem to find some proper guidance around where to smartly stop work when interaction is in progress.

Could someone please guide me or point me to some example that uses this API to ensure great performance and interactivity? Feel free to close otherwise, thanks!

**Comment by brentvatne** [comment]
This is really useful when you are pushing to a new route with `Navigator` - on the component that you are rendering you can defer rendering any expensive views by having some state like `transitionComplete` that initializes to `false` and blocks rendering of those views, then set it to `true` in the `runAfterInteractions` callback so the views can render. I've done this on an app to get much smoother animated transitions.

**Comment by paramaggarwal** [comment]
Ah I see. Any use-case regarding scrolling interaction esp. on a ListView?

**Comment by brentvatne** [comment]
@paramaggarwal - not that I know of, I don't believe that ListView creates any interaction handles, just Navigator and Animated at the moment.

**Comment by paramaggarwal** [comment]
That answers my question. Thanks @brentvatne!

**Comment by brentvatne** [comment]
Posting example repo link here so it's easy to reference: https://github.com/brentvatne/run-after-interactions-exp

**Comment by diegoddox** [comment]
@brentvatne thanks for the repo (run-after-interactions-exp) that you've made, I was wondering if it will have any good effect to call fetch inside of a `runAfterInteractions `?

Thanks in adance.

**Comment by brentvatne** [comment]
probably doesn't matter. you could put doing something in response to the fetch completing inside of it but the actual fetch is not going to make your app drop frames
