### ISSUE TITLE
[Android BUG] On real android devices execution fails

### ISSUE THREAD

**Issue by zscaiosi** [facebook/react-native#22485]
## Environment
Environment:
  OS: Windows 10
  Node: 8.11.3
  Yarn: 1.6.0
  npm: 6.4.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

 React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 2.84 GB / 7.91 GB
    Binaries:
      Yarn: 1.6.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338

## Description
When I run react-native run-android on an Android Studio's simulator (Nexus 5x Android version 6.0) it works fine as expected. When I connect my real device (Asus ZOOLD Android version 6.0.1) and try to open my app the folowing exception is thrown: 

**_"undefined is not an object (evaluating 'c.Aspect.fill')"_**

**I can't identify the module which is causing this and why it is causing this just on real devices.**
Can anyone help me out with that?
Thank you in advance.

## Images & Infos
![new_eception](https://user-images.githubusercontent.com/14954380/49373759-53953b00-f6e6-11e8-8402-f7f533e1c5b5.png)

Package.json:
    "dependencies": {
        "algoliasearch": "^3.30.0",
        "create-react-class": "^15.6.3",
        "i18n-js": "^3.0.11",
        "libphonenumber-js": "1.3.1",
        "lodash": "^4.17.10",
        "moment": "^2.22.2",
        "moment-timezone": "^0.5.21",
        "native-base": "2.7.2",
        "prop-types": "15.6.2",
        "react": "16.3.1",
        "react-instantsearch-dom": "^5.3.1",
        "react-instantsearch-native": "^5.3.1",
        "react-moment": "0.8.1",
        "react-native": "0.55.4",
        "react-native-actionsheet": "^2.4.2",
        "react-native-calendars": "^1.20.0",
        "react-native-camera-kit": "^6.2.6",
        "react-native-check-box": "^2.1.0",
        "react-native-checkbox-form": "1.1.5",
        "react-native-confirmation-code-input": "1.0.4",
        "react-native-country-picker-modal": "0.6.2",
        "react-native-datepicker": "1.7.2",
        "react-native-device-info": "0.22.2",
        "react-native-document-picker": "^2.1.0",
        "react-native-easy-grid": "0.2.0",
        "react-native-elements": "0.19.1",
        "react-native-file-type": "0.0.8",
        "react-native-file-viewer": "^1.0.5",
        "react-native-fs": "^2.11.15",
        "react-native-gifted-listview": "0.0.15",
        "react-native-image-cache-hoc": "^1.5.0",
        "react-native-image-picker": "^0.27.1",
        "react-native-iphone-x-helper": "1.0.3",
        "react-native-keyboard-aware-scroll-view": "^0.7.0",
        "react-native-keyboard-spacer": "^0.4.1",
        "react-native-languages": "^2.0.1",
        "react-native-loading-spinner-overlay": "^0.5.2",
        "react-native-modal-picker": "0.0.16",
        "react-native-modalbox": "1.6.0",
        "react-native-permissions": "^1.1.1",
        "react-native-phone-call": "^1.0.7",
        "react-native-phone-input": "0.2.1",
        "react-native-popup-menu": "^0.14.0",
        "react-native-remote-svg": "^1.3.0",
        "react-native-render-html": "^3.10.0",
        "react-native-router-flux": "4.0.0-beta.31",
        "react-native-search-bar": "^3.4.2",
        "react-native-search-box": "0.0.19",
        "react-native-splash-screen": "3.1.1",
        "react-native-touch-id": "^4.3.0",
        "react-native-user-inactivity": "git+https://github.com/Balasnest/react-native-user-inactivity.git",
        "react-native-vector-icons": "4.6.0",
        "react-native-webview-quilljs": "^0.8.34",
        "react-native-zss-rich-text-editor": "git+https://github.com/charpeni/react-native-zss-rich-text-editor.git#prs-merged",
        "react-redux": "5.0.7",
        "redux": "4.0.0",
        "redux-persist": "4.8.0",
        "redux-thunk": "2.3.0",
        "rn-fetch-blob": "^0.10.13",
        "toggle-switch-react-native": "1.0.0"
    },
    "devDependencies": {
        "babel-core": "6.26.3",
        "babel-jest": "23.2.0",
        "jest": "23.2.0",
        "react-native-debugger-open": "0.3.17",
        "react-test-renderer": "16.3.1"
    },

## Reproducible Demo
Let us know how to reproduce the issue. Include a code sample, share a project, or     share an app that reproduces the issue using https://snack.expo.io/. Please follow the guidelines for providing a MCVE: https://stackoverflow.com/help/mcve

**Comment by zscaiosi** [comment]
@react-native-bot now it throws the error: 
React Native version mismatch 
JavaScript version: 0.55.4
Native version: 0.57.7

I've looked for that Exception on other issues but none of them help me out.

**Comment by hramos** [comment]
How did you upgrade your project? It looks like there is a mismatch.

**Comment by zscaiosi** [comment]
@hramos @react-native-bot I got my project back to the point where I first asked for help, before upgrading.

Now I just tried to upgrade again as @react-native-bot suggested, that is how I did it:
I followed these instructions: https://facebook.github.io/react-native/docs/upgrading 
When running  `react-native-git-upgrade` I get the following output:

> The file will have its original line endings in your working directory
> git-upgrade info Commit old version template
> git-upgrade info Install the new version
> error Command failed.
> Exit code: 1
> Command: git
> Arguments: pull
> Directory: C:\Users\Caio\AppData\Local\Yarn\Cache\v4\.tmp\8e3ea0e4ce65ad4695e1b94666353714
> Output:
> There is no tracking information for the current branch.
> Please specify which branch you want to merge with.
> See git-pull(1) for details.
> 
>     git pull <remote> <branch>
> 
> If you wish to set tracking information for this branch you can do so with:
> 
>     git branch --set-upstream-to=<remote>/<branch> master
> git-upgrade ERR! An error occurred during upgrade:
> git-upgrade ERR! Error: Command 'yarn add react-native@0.57.7 react@16.6.1' exited with code 1:
> stderr: undefinederror Command failed.
> Exit code: 1
> Command: git
> Arguments: pull
> Directory: C:\Users\Caio\AppData\Local\Yarn\Cache\v4\.tmp\8e3ea0e4ce65ad4695e1b94666353714
> Output:
> There is no tracking information for the current branch.
> Please specify which branch you want to merge with.
> See git-pull(1) for details.
> 
>     git pull <remote> <branch>
> 
> If you wish to set tracking information for this branch you can do so with:
> 
>     git branch --set-upstream-to=<remote>/<branch> master
> 
> stdout: yarn add v1.12.3
> [1/4] Resolving packages...
> info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
> 
>     at ChildProcess.child.on.code (C:/Users/Caio/AppData/Roaming/npm/node_modules/react-native-git-upgrade/cliEntry.js:58:18)
>     at ChildProcess.emit (events.js:182:13)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
> git-upgrade ERR! Restore initial sources
> Note: checking out 'project-snapshot'.
> 
> You are in 'detached HEAD' state. You can look around, make experimental
> changes and commit them, and you can discard any commits you make in this
> state without impacting any branches by performing another checkout.
> 
> If you want to create a new branch to retain commits you create, you may
> do so (now or later) by using -b with the checkout command again. Example:
> 
>   git checkout -b <new-branch-name>
> 
> HEAD is now at 0468ca9 Project snapshot

Should not  react-native-git-upgrade itself take care of tracking the remote repository?
How do I fix it?

Thanks
