### ISSUE TITLE
text strings must be a rendered with a Text component

### ISSUE THREAD

**Issue by svipben** [facebook/react-native#22483]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
  React Native Environment Info:
    System:
      OS: macOS 10.14.1
      CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 390.35 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.14.0 - /usr/local/opt/node@8/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/opt/node@8/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5014246
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.1 => 16.6.1
      react-native: 0.57.7 => 0.57.7
```

## Description
Very weird issue. If I use `Image` or `ImageBackground` component and simply add check `if (showImage) {...}` after true/false I get text invariant error.

```js
render() {
  const imagePath = '';
  
  return (
    <View>
      {imagePath && <Image source={{ uri: imagePath }} style={{ width: 100, height: 100 }} />}
    </View>
  );
}
```

If component is destroyed which means it will not be rendered anymore if `imagePath` is empty, etc. I get this error. As I workaround I created component which renders actual `Image` component and I check if `props.path` is empty, etc. and I simply `return null`. For whole container which renders these images I change `display` to `flex` or `none` depends if I need to show or hide images. Maybe there's another solution? Before 0.57.* RN everything was okay and I never had issues with such flow.

**Comment by svipben** [comment]
Seems I can fix it by simply using ternary instead of `&&`. The issue is it returns `undefined` instead of `null` I guess.

Because if I change **from**:

`{imagePath && <Image source={{ uri: imagePath }} style={{ width: 100, height: 100 }} />}`

**To** this:

`{imagePath ? <Image source={{ uri: imagePath }} style={{ width: 100, height: 100 }} /> : null}`

Issue is gone.

**Comment by svipben** [comment]
Okay this can be closed real issue is it returns empty string if it's empty that's why I get this text invariant error, but if I simply wrap string to `Boolean` everything is OK. So there are 2 solutions. To simply change your string into boolean or use ternary which returns `null` if string is empty.

**Comment by itolimaesther** [comment]
I have the same issue here 

`{
                this.state.showInfo &&
                <View style={styles.info}>
                    <Text>Restaurant Info</Text>
                    <Image source={InfoImage}
                    style={{
                       width: 1,
                        height: 100
                    }}/>
                    resizeMode="contain"
                </View>
            }`
