### ISSUE TITLE
undefined is not a function (evaluating 'instance.render()')

### ISSUE THREAD

**Issue by LingYun** [facebook/react-native#22481]
react-native-cli: 2.0.1
react-native: 0.57.7
system：win10
running simulator:android
![_15438231954958](https://user-images.githubusercontent.com/1118261/49359951-ac7ac880-f712-11e8-8a1f-6d0916ae116b.png)

**Comment by rosebless** [comment]
@LingYun  can you solve it yet?

**Comment by cassianomon** [comment]
Using render as:
`render = () => {`

solved for me, but is it necessary? Even if I just return:

```
render() {
	return <View />
}
```

it returns me this error...
