### ISSUE TITLE
Attempted to transition from state `RESPONDER_INACTIVE_PRESS_IN` to `RESPONDER_ACTIVE_LONG_PRESS_IN`, which is not supported. 

### ISSUE THREAD

**Issue by bfrog** [facebook/react-native#22491]
## Environment
```
react-native info                                                                                           ✔  10106  14:52:17 

  React Native Environment Info:
    System:
      OS: Linux 4.14 Arch Linux undefined
      CPU: (8) x64 Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
      Memory: 12.71 GB / 31.25 GB
      Shell: 5.6.2 - /bin/zsh
    Binaries:
      Node: 8.12.0 - /usr/bin/node
      Yarn: 1.12.3 - /usr/bin/yarn
      npm: 6.4.1 - /usr/bin/npm
      Watchman: 4.9.0 - /usr/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 24.0.2, 25.0.0, 26.0.2, 27.0.3, 28.0.2, 28.0.3
        System Images: android-26 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.2
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: 0.57.2 => 0.57.2 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

## Description
This seems to be a closed issue with https://github.com/facebook/react-native/issues/5823
which was marked as resolved. But the fix of enabling auto update of time on both device and my computer still results in my device and computer being off by several seconds, probably due to different NTP sources being pulled from at different times.

Its incredibly frustrating to get this red box which results in my app no longer working as expected.

It doesn't seem like the time on my device and my computer should matter? In no other debugging environment has this been an issue.

**Comment by hramos** [comment]
Device time matters because when debugging is enabled, the JavaScript code is executed on your computer while native code is executed on the device.
