### ISSUE TITLE
Support for the experimental syntax 'optionalChaining' isn't currently enabled

### ISSUE THREAD

**Issue by nahidmbstu** [facebook/react-native#22495]
i have read the documentation  : https://facebook.github.io/react-native
  i have searched issues : https://github.com/facebook/react-native/issues
  i have latest React Native release: https://github.com/facebook/react-native/releases

## Environment
  React Native Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 16.04.4 LTS (Xenial Xerus)
      CPU: (4) x64 Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz
      Memory: 964.29 MB / 7.71 GB
      Shell: 4.3.48 - /bin/bash
    Binaries:
      Node: 8.11.3 - /usr/bin/node
      npm: 5.6.0 - /usr/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 24.0.0, 24.0.1, 24.0.3, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.0, 28.0.2
        System Images: android-24 | Google Play Intel x86 Atom
    npmPackages:
      react: ^16.6.3 => 16.6.3 
      react-native: ^0.57.7 => 0.57.7 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      react-native-rename: 2.2.2

## Description

error: bundling failed: SyntaxError: /home/ubuntu/code/truck-kothay-apps/goodOwnerTk/node_modules/react-native/Libraries/Components/Switch/Switch.js: Support for the experimental syntax 'optionalChaining' isn't currently enabled (103:41):

**Comment by the-yadu** [comment]
@nahidmbstu Did it solved for you?

**Comment by SunnySunning** [comment]
@nahidmbstu Did it solved for you?
