### ISSUE TITLE
Animated.value listener failed after scroll content changes

### ISSUE THREAD

**Issue by papmodern** [facebook/react-native#22492]
## Environment
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 8.18 GB / 15.95 GB
    Binaries:
      Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338

## Description
I'm using Animated.ScrollView and Animated.event to create an Animated customized bottom sheet that responds to user scrolling action. In some cases the content of Animated.ScrollView will change and in that case listener of animated value will not fire anymore. It seems that the event listener removes after changing content and I don't know how can I add it again!

    class MyComponent extends Component {

      componentDidMount(){
        this.scrollY.addListener((v) => console.tron.log(v))
      }

      render(){
        return(
          <View style={FULL}>
              <Animated.ScrollView
                onLayout={e => this.scrollHeight -= e.nativeEvent.layout.height}
                ref={v => this.scrollView = v}
                onContentSizeChange={(w, h) => this.scrollHeight = h}
                onScroll={Animated.event(
                  [{
                    nativeEvent: { contentOffset: { y: this.scrollY } },
                  }],
                  {
                    useNativeDriver: true,
                  },
                )}
              >
                <Screen
                  style={CONTAINER(options.length * this.optionHeight)}
                  backgroundColor={color.transparent}
                  preset="scrollStack">
                  {this.content.map((section, i) => <Text key={i} style={CONTENT}>{section}</Text>)}
               </Screen>
              </Animated.ScrollView>
          </View>
        )
      }
    }
  

All the Animation process works fine but just the listener `this.scrollY.addListener((v) => console.tron.log(v))` doesn't

**Comment by alpamys-qanybet** [comment]
I am also facing this issue
