### ISSUE TITLE
Error at init AwesomeProject

### ISSUE THREAD

**Issue by dmitruksergey** [facebook/react-native#225]
Hi there!
I have error at initialise your Awesome Project: ![screenshot 2015-03-26 20 27 13](https://cloud.githubusercontent.com/assets/4532683/6854093/b807b36c-d3f7-11e4-95d8-120dce72c775.png)
Node v0.10.35, NPM 2.1.14

**Comment by ileonovdima** [comment]
I have the same error, node 0.12

**Comment by amasad** [comment]
can you paste npm-debug.log?

**Comment by ileonovdima** [comment]
https://www.dropbox.com/s/kog4vctcz7lakja/npm-debug.log?dl=0

**Comment by dmitruksergey** [comment]
Github don't like too long comment :-) See in my Dropbox — https://www.dropbox.com/s/sts6bc2jr577kcm/npm-debug.log?dl=0

**Comment by ileonovdima** [comment]
https://www.dropbox.com/s/kog4vctcz7lakja/npm-debug.log?dl=0

**Comment by Palgrover** [comment]
http://stackoverflow.com/questions/22152162/npm-cannot-install-dependencies-attempt-to-unlock-something-which-hasnt-been#

try this

**Comment by ileonovdima** [comment]
thank you

**Comment by amasad** [comment]
Did that work?

**Comment by dmitruksergey** [comment]
Yep! Thank you!
All who have same error write in terminal this:

sudo chown -R $USER ~/.npm
sudo chown -R $USER /usr/local/lib/node_modules

**Comment by Palgrover** [comment]
:)

**Comment by amasad** [comment]
Thanks @Palgrover!
Let's keep this open if more people run into this we need to handle it. It seems fragile that we rely on the postinstall script.

**Comment by mteece** [comment]
Confirming that:

    $ sudo chown -R $USER ~/.npm
    $ sudo chown -R $USER /usr/local/lib/node_modules

Worked on my side.

**Comment by Palgrover** [comment]
Did anyone face the error 

[Error: Watcher took too long to load
Try running `watchman` from your terminal
https://facebook.github.io/watchman/docs/troubleshooting.html]
Error: Watcher took too long to load
Try running `watchman` from your terminal
https://facebook.github.io/watchman/docs/troubleshooting.html
    at null._onTimeout (/Users/WhackyApps/AwesomeProject/node_modules/react-native/packager/react-packager/src/FileWatcher/index.js:71:16)
    at Timer.listOnTimeout (timers.js:110:15)


because of this i cannot reload my simulator after changes

**Comment by amasad** [comment]
@Palgrover can you open a new issue? we'll talk about it there

**Comment by Palgrover** [comment]
Sorry for that i have new issue guys lets discuss there

**Comment by Palgrover** [comment]
@amasad sure we can keep this open for sometime so that more people can solve it easily

**Comment by misuba** [comment]
@amasad It Happened To Me. The chown fix worked great. I wonder if there is a commonality with people who have this issue maybe not having installed node with brew? (I didn't, I don't think.)

**Comment by mteece** [comment]
I needed to chown the AwesomeProject folder after it was scaffolded by init.

**Comment by ClemMakesApps** [comment]
The extra ```$ sudo chown``` helped fix my issue as well

**Comment by svenanders** [comment]
Yeah, can confirm you will run into problems when you somtimes install dependencies as root (and thus end up with mixed ownership in the /usr/local/lib/node_modules folder and sometimes other /usr/local folders). It's the first thing I look at when people come to me with npm dependency problems.

**Comment by lucamezzalira** [comment]
it works for me too :D

**Comment by amasad** [comment]
Can someone verify that this is fixed now?

**Comment by GeneralRamy** [comment]
Nice , It `s fixed
<code>
$ sudo chown -R $USER ~/.npm 
</code>
<code>
$ sudo chown -R $USER /usr/local/lib/node_modules
</code>

**Comment by san983** [comment]
:+1: worked for me

**Comment by devangpandya20** [comment]
Worked for me
