### ISSUE TITLE
App is force close in release mode: undefined is not an object (evaluating 'f(r)')

### ISSUE THREAD

**Issue by Sathiyamm** [facebook/react-native#22501]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.11.3
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.1 AI-173.4670197

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

## Description
In debug mode app is working , But app is force close in release mode.
After archive app also force close in real devices.

**Comment by Sathiyamm** [comment]
We are using 0.55.4 version for android it works well, but in IOS only not work in release mode.

**Comment by Sathiyamm** [comment]
![screenshot 2018-12-04 17 48 29](https://user-images.githubusercontent.com/30838274/49441702-52026a80-f7ed-11e8-984c-699d95005864.png)

**Comment by hramos** [comment]
The reason behind asking bug reports to use the latest version is to verify this is an issue that is not yet fixed in the latest release.
