### ISSUE TITLE
BUG: XMLHttpRequest returns json string with BOM character in the begining 

### ISSUE THREAD

**Issue by davidnum** [facebook/react-native#22507]
- [+] Review the documentation: https://facebook.github.io/react-native
  - [+] Search for existing issues: https://github.com/facebook/react-native/issues
  - [+] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz
      Memory: 1.60 GB / 7.89 GB
    Binaries:
      Node: 8.11.3 - C:\Programs\nodejs\node.EXE
      Yarn: 1.0.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Programs\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5014246

## Description
XMLHttpRequest returns json string in response with BOM character in the begining. Reproduce only on Android.
Trying:
-delete node_modules
-reinstall react-native-cli
-clean build folder

**Comment by hramos** [comment]
Can you expand on your steps to reproduce? At the very least, provide a URL.
