### ISSUE TITLE
Deep link not working if my app is in the background

### ISSUE THREAD

**Issue by nicomontanari98** [facebook/react-native#22509]
- [X] Review the documentation: https://facebook.github.io/react-native
  - [X] Search for existing issues: https://github.com/facebook/react-native/issues
  - [X] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
React Native Environment Info:
    System:
      OS: macOS 10.14.1
      CPU: x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
      Memory: 732.00 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.12.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: 16.7.8 => 16.7.8 
      @types/react-native: 0.57.15 => 0.57.15 
      react: 16.6.3 => 16.6.3 
      react-native: 0.57.7 => 0.57.7 
    npmGlobalPackages:
      create-react-native-app: 1.0.0

## Description
I use universal link, when my app is close deep link works fine....but if my app is in the background it opens but it doesn't get the url

## Reproducible Demo
    componentDidMount() {
        Linking.getInitialURL().then(url => {
            if (url !== null)
                this.navigateFromUrl(url)
        })

        if (Platform.OS === 'ios') {
            Linking.addEventListener('url', this.handleOpenURL)
        }
    }

    componentWillUnmount() {
        if (Platform.OS === 'ios')
            Linking.removeEventListener('url', this.handleOpenURL)
    }

    handleOpenURL = (event) => {
        this.navigateFromUrl(event.url)
    }

    navigateFromUrl = (url) => {
        const { navigate } = this.props.navigation
        const route = url.replace(/.*?:\/\//g, '')
        const id = parseInt(route.match(/\/([^\/]+)\/?$/)[1], 10)
        const routeName = route.split('/')[1].toString()

        switch (routeName) {
            case 'product':
                navigate({
                    routeName: 'ProductPage',
                    params: { product: id }
                })
                break
            case 'store':
                navigate({
                    routeName: 'StorePage',
                    params: { store: id }
                })
                break
            case 'order':
                navigate({
                    routeName: 'FullPageOrder',
                    params: { orderId: id }
                })
                break
        }
    }

**Comment by platonish** [comment]
@nicomontanari98 were you able to solve for this?

**Comment by nicomontanari98** [comment]
@platonish Unfortunately no

**Comment by platonish** [comment]
See [this](https://github.com/facebook/react-native/issues/24624#issuecomment-492155502)
