### ISSUE TITLE
[ListView] ScrollView inside a Listview with horizontal=true doesn't scroll.

### ISSUE THREAD

**Issue by chirag04** [facebook/react-native#2250]
I have a Listview with ``horizontal=true`` and each row having a fixed height and width. 

I have a ScrollView for each row to enable ``Vertical Scrolling`` in that particular listview row. 

Listview horizontal scroll is working but ScrollView's vertical scrolling is not working.

cc @ide

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/listview-scrollview-inside-a-listview-with-horizontaltrue-doesnt-scroll

**Comment by SudoPlz** [comment]
I've got the same problem I wonder if anyone solved it.

**Comment by phil-travelbytes** [comment]
Yep - me too (+1) on this.  Any known fixes will be helpful...
