### ISSUE TITLE
navigator.geolocation.getCurrentPosition response with PERMISSION_DENIED

### ISSUE THREAD

**Issue by gjae** [facebook/react-native#22512]
### Hello people!

navigator.geolocation.getCurrentPosition return the next error: 
![47382878_1926496210780565_3667587945465905152_n](https://user-images.githubusercontent.com/28078695/49465314-ab5da000-f7d3-11e8-8ad6-1717f14ef771.jpg)

i'am using react-native-maps, and trying on physical device.
# android/app/build.gradle code:
![screenshot at 2018-12-04 14 06 17](https://user-images.githubusercontent.com/28078695/49465351-c92b0500-f7d3-11e8-89e1-067775ae3de2.png)

# MapScreen code:
![screenshot at 2018-12-04 14 02 53](https://user-images.githubusercontent.com/28078695/49465364-d1834000-f7d3-11e8-9dff-97317cef7ad0.png)

**Comment by loubacking** [comment]
I suggest you to use a library called 'react-native-permission' to allow every component that you need (iOS and Android). Hope help you!

Cheers!

**Comment by gjae** [comment]
> Le sugiero que use una biblioteca llamada 'reaccionar-nativo-permiso' para permitir cada componente que necesite (iOS y Android) Espero que te ayude!
> 
> ¡Aclamaciones!

Hi, i go to try this library
