### ISSUE TITLE
Specific border radius corner causes visual bug on other corners 

### ISSUE THREAD

**Issue by atkinchris** [facebook/react-native#22511]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
React Native Environment Info:
  System:
    OS: macOS High Sierra 10.13.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 2.98 GB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.14.0 - ~/.nvm/versions/node/v8.14.0/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  SDKs:
    Android SDK:
      API Levels: 23, 27
      Build Tools: 27.0.3
  IDEs:
    Xcode: /undefined - /usr/bin/xcodebuild
  npmPackages:
    react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728
    react-native: 0.57.4 => 0.57.4
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

## Description
Applying a non-zero border radius value to a specific corner when all other corners are zero, causes the other corners to become slightly curved on Android.

![screenshot_20181204-162242](https://user-images.githubusercontent.com/1479528/49456973-e2d34900-f7e1-11e8-8ff9-170f82755216.jpg)

## Reproducible Demo
Code Snippet:

```jsx
<View style={{
  backgroundColor: 'red',
  width: 100,
  height: 100,
  borderWidth: 5,
  borderBottomLeftRadius: 15,
}} />
<View style={{
  backgroundColor: 'green',
  borderWidth: 5,
  width: 100,
  height: 100,
}} />
```

Expo Snack:

https://snack.expo.io/@atkinchris/border-radius-bug

**Comment by wazzupex** [comment]
Hi, although it's was not supposed to happen, have you tried to set the other corners radius to 0 ?

**Comment by atkinchris** [comment]
@wazzupex - yep! With the below, it does not change. Setting `borderRadius: 0` also does not correct it.

```js
backgroundColor: 'red',
width: 100,
height: 100,
borderWidth: 5,
borderBottomLeftRadius: 15,
borderBottomRightRadius: 0,
borderTopLeftRadius: 0,
borderTopRightRadius: 0,
```

Interestingly, this does not present in Snack's iOS preview - only on Android and real devices.

**Comment by bozhouyongqi** [comment]
I faced with this problems too,when I set the borderBottomLeftRadius attribute only,it does affect other corners slightly curved.When I set the borderWidth to 1,it display ok.

**Comment by simformsolutions** [comment]
borderBottomWidth: 5,
            borderTopWidth: 5,
            borderLeftWidth: 5,
            borderRightWidth: 5,

use this

**Comment by JigzPalillo** [comment]
is this somehow connected to my bug?
![img_0092](https://user-images.githubusercontent.com/31827190/51529931-c0ba8680-1e74-11e9-9720-0a085dd18bca.jpg)

**Comment by kelset** [comment]
👋 everyone.

I can confirm that this bug is still present on RN 0.59 - but I investigated a bit further and I noticed that it seems to be related not strictly to the borderRadius but to the borderWidth: when it's set to 0, the bug doesn't show:

<img width="343" alt="Screenshot 2019-03-19 at 16 27 17" src="https://user-images.githubusercontent.com/16104054/54623686-ed99ad00-4a63-11e9-991b-cdb1d5e10278.png">

This said, we'll look more into this issue in the next few months (hopefully) - if you have more time to dedicate to it it would surely help!

(ps: @JigzPalillo it's hard to tell - probably not)

**Comment by Nizarius** [comment]
@kelset this bug is really annoying in my project. Let's not wait a few months. I made PR for fixing it.

**Comment by atkinchris** [comment]
Succinct PR @Nizarius! I think this needs unit tests to prevent regressions.

**Comment by ThakurKarthik** [comment]
> is this somehow connected to my bug?
> ![img_0092](https://user-images.githubusercontent.com/31827190/51529931-c0ba8680-1e74-11e9-9720-0a085dd18bca.jpg)

Is this fixed?In my case i can see background color of outer view inside a view with border radius in fractional number.
