### ISSUE TITLE
[Android] Red screen (evaluating 'newPatterns')

### ISSUE THREAD

**Issue by TriPSs** [facebook/react-native#22510]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Run `react-native info` in your terminal and paste its contents here.
```
  React Native Environment Info:
    System:
      OS: macOS 10.14.1
      CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
      Memory: 122.86 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.13.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 16, 19, 21, 22, 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.1, 25.0.3, 26.0.3, 27.0.2, 27.0.3, 28.0.2, 28.0.3
        System Images: android-27 | Android TV Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Android TV Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: 0.57.7 => 0.57.7
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-ci-tools: 1.1.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      react-native: 0.55.4
```

When running my app after i upgraded everything with remote debugger enabled the app worked fine, if i disable the remote debugger i get a red screen.

**Problem only occurs on Android**
![image](https://user-images.githubusercontent.com/7668692/49455381-5fb4f180-f7e7-11e8-88fa-b44fcbcfa0f3.png)

## Reproducible Demo
Let us know how to reproduce the issue. Include a code sample, share a project, or     share an app that reproduces the issue using https://snack.expo.io/. Please follow the guidelines for providing a MCVE: https://stackoverflow.com/help/mcve
Index.js
```
import { AppRegistry } from 'react-native'
import AppRoot from './src/AppRoot'

AppRegistry.registerComponent('app', () => AppRoot)
```

My AppRoot:
```
import React from 'react'
import { YellowBox, Text } from 'react-native'

YellowBox.ignoreWarnings([
  'Warning: isMounted(...) is deprecated',
  'Remote debugger',
])

const AppRoot = () => (
  <Text>Test</Text>
)

export default AppRoot
```

If i remove YellowBox it does work

**Comment by onzedix** [comment]
I'm facing similar issues, take a look at https://github.com/facebook/react-native/issues/22573

**Comment by dulmandakh** [comment]
Hello there 👋 this issue has been reported for an old version of React Native. Ideally we'd like everyone to be using 0.59 (see the [awesome changes](https://facebook.github.io/react-native/blog/2019/03/12/releasing-react-native-059) it brought) but we know updating can be a pain. We are going to close this issue because it's from a version before 0.57, which is really old.

But please, if it's actually still an issue with 0.59 please comment below and we can reopen it. Even better, please send us a pull request with a fix 😊
