### ISSUE TITLE
[ScrollView] add onPageChange for scrollView with pagingEnabled=true.

### ISSUE THREAD

**Issue by chirag04** [facebook/react-native#2251]
Just like ``onScroll`` handle, does it makes sense to add ``onPageChange`` handler for ScrollView with ``pagingEnabled=true``?

Wondering how to get a callback when the page changes on pagingEnabled ScrollView's now.

cc @ide  @vjeux

**Comment by ide** [comment]
I think there's already a way to get this with one of the events. I forget what prop it was but I was able to detect the end of the momentum scroll a few months ago.

**Comment by vjeux** [comment]
Would be nice to get this event indeed, it's annoying to compute right now

**Comment by chirag04** [comment]
@ide I agree with @vjeux. It is annoying to compute right now. Also, i guess you are talking about ``onMomentumScrollEnd`` or something. I couldn't get that working. 


``onPageChanged`` makes sense also for anyone with pagingEnabled. 

I will go ahead and try to make a PR then.

**Comment by ide** [comment]
Yes it was onMomentumScrollEnd. We should fix that if it's not working -- the way that you'd detect a page change is to check when the momentum scroll ends anyway.

**Comment by chirag04** [comment]
Ok. I'm not 100% what when wrong with ``onMomentumScrollEnd``. 

I will post my findings here. We can discuss if we need to support onPageChanged or just use onMomentumScrollEnd then.

**Comment by chirag04** [comment]
@ide I do get ``onMomentumScrollEnd``. Not sure why it is delayed though. There is a noticeable difference between the log and scroll end.

Also ``onMomentumScrollEnd={console.log}`` prints so much on console. Is it intentional ?

**Comment by ide** [comment]
The lag is likely because you're printing out a huge component tree as part of the event object. I've hit this is other places too. Maybe the shimmed console.log should not deeply print out React components. If it's working for you now could you close this issue?

**Comment by brentvatne** [comment]
> Maybe the shimmed console.log should not deeply print out React components.

@ide - :+1: - I haven't found a case where this is useful yet

**Comment by chirag04** [comment]
@ide onMomentumScrollEnd is working. Sharing the code for anyone looking for it. Small core api is what i support so closing this for now.

We should def. document this function though.

```
onMomentumScrollEnd={this.handlePageChange}

handlePageChange: function(e) {
    var offset = e.nativeEvent.contentOffset;
    if(offset) {
      var page = Math.round(offset.x / WIDTH) + 1;
      if(this.state.page != page) {
        this.setState({page: page});
      }
    }
  },
```

**Comment by magic3584** [comment]
@chirag04 Thanks!

**Comment by jDeppen** [comment]
@chirag04, that works for me!

I see you're checking `if(offset)`; is there a time when offset would be falsy or would it be ok to leave out? Thank you
