### ISSUE TITLE
require is not defined

### ISSUE THREAD

**Issue by ramyareye** [facebook/react-native#22522]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
React Native Environment Info:
    System:
      OS: macOS 10.14.1
      CPU: (8) x64 Intel(R) Core(TM) i7-4771 CPU @ 3.50GHz
      Memory: 2.01 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.3.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
      Android SDK:
        API Levels: 23, 26, 27, 28
        Build Tools: 23.0.1, 26.0.1, 26.0.3, 27.0.3, 28.0.3
        System Images: android-26 | Google APIs Intel x86 Atom_64, android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.0/10A254a - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.1 => 16.6.1
      react-native: 0.57.7 => 0.57.7
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

## Description
First time I faced this error last week after upgrading to 0.57, then I tried some commands like `react-native start --reset-cache` and it was ok. 
Today again I faced it and nothing works to me! Simulator also went slow and laggy! 

The things that I tried :
- the command above and `pkill node`
- changing Xcode build system 
- trying node version: 8 & 11

These screenshots are from a new initialized react-native by init command :

![screen shot 2018-12-05 at 3 17 50 pm](https://user-images.githubusercontent.com/6318491/49511675-0b6e4800-f8a1-11e8-9452-d115b3b6f12a.png)
![screen shot 2018-12-05 at 3 11 44 pm](https://user-images.githubusercontent.com/6318491/49511686-1032fc00-f8a1-11e8-98eb-7fc00d1157f0.png)

## Reproducible Demo
The app is the react-native init starter and here the errors :

`Unhandled JS Exception: Can't find variable: require (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:410)` ( as the attached image )

after choosing Debug JS Remotely :

`require is not defined!`

I'm not sure if it's a bug or my environment problem! I need to upgrade our app and will be happy with any idea to solve it.

Regards

**Comment by ramyareye** [comment]
no it was both in env. I found the problem.

```
{
  "presets": ["module:metro-react-native-babel-preset"],
  "plugins": [
    ["@babel/plugin-proposal-decorators", { "legacy": true }]
  ],
  "env": {
    "development": {
      "plugins": [
        "@babel/plugin-transform-typeof-symbol"
      ]
    },
    "production": {
      "plugins": ["transform-remove-console"]
    }
  }
}
```

I removed these lines and now it's ok. I just need a way find out how to include it.

```
"env": {
    "development": {
      "plugins": [
        "@babel/plugin-transform-typeof-symbol"
      ]
    },
```

**Comment by 452MJ** [comment]
same here
