### ISSUE TITLE
Xcode 10.1 : node_modules/react-native/third-party/glog-0.3.5/src/base/mutex.h:105:10: 'config.h' file not found

### ISSUE THREAD

**Issue by lmyl** [facebook/react-native#22521]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
React Native Environment Info:
    System:
      OS: macOS 10.14.1
      CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 65.37 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.1 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5014246
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.1 => 16.6.1 
      react-native: 0.57.7 => 0.57.7 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description
When I use Xcode to build this project, I meet the error`('config.h' file not found)` .
Follow the steps below to reproduce the problem.
1.  Input `react-native init newRN` In `Terminal`.
2.  Use Xcode to build this project.
3.  Problem occurred .
4. ![image](https://user-images.githubusercontent.com/22229789/49497206-ce0aba00-f8a2-11e8-8173-1ef166790883.png)
5.  `'config.h'` file not found
6. Open `node_modules/react-native/third-party/glog-0.3.5/src/` By `Finder` 
7. ![2018-12-05 15 39 56](https://user-images.githubusercontent.com/22229789/49497790-3c03b100-f8a4-11e8-81e3-7447dda85118.png)
8.  Then I use `Terminal` in this project , input `cd node_modules/react-native/third-party/glog-0.3.5 ` 
9.  input `../../scripts/ios-configure-glog.sh` In `Terminal `
10.  we wait for the command to finish ,we will see this 
11.  ![2018-12-05 15 45 48](https://user-images.githubusercontent.com/22229789/49498148-0f9c6480-f8a5-11e8-82dd-d00c741eb224.png)
12.  Open `node_modules/react-native/third-party/glog-0.3.5/src/` By `Finder`
13.  ![2018-12-05 15 48 12](https://user-images.githubusercontent.com/22229789/49498233-57bb8700-f8a5-11e8-9855-2713315fab7d.png)
14.  Open this project By `Xcode` 
15.  ![2018-12-05 15 50 24](https://user-images.githubusercontent.com/22229789/49498353-b7b22d80-f8a5-11e8-9f0f-99eb7b55c0ca.png)
16.  It seems to have fixed this problem, but don't be happy, it will make you unexpected later.
17.  Clean Xcode and use Xcode to build this project.
18. The problem still exists.
19.  ![image](https://user-images.githubusercontent.com/22229789/49498510-41fa9180-f8a6-11e8-958a-f8994eb5612c.png)
20.  ![image](https://user-images.githubusercontent.com/22229789/49498554-65bdd780-f8a6-11e8-860e-149e4e721f14.png)
21.   Open `node_modules/react-native/third-party/glog-0.3.5/src/` By `Finder`
22.  ![2018-12-05 15 57 30](https://user-images.githubusercontent.com/22229789/49498613-97cf3980-f8a6-11e8-89a5-d81b8f0b68a7.png)
23.  I think this file will be deleted when compiling this project, but this is not what I want. I have read a lot of materials and tried many methods, but I can't solve this problem. I hope everyone can help me solve this problem. Thank you very much!
24.  When I use `react-native 0.57.4` , the problem will not happen.  I think the latest React Native release includes some bugs.

**Comment by Akash35pasupathi** [comment]
same issue ... please give any solutions ... I am using react native upgrade version like **react-native v0.57.7**

**Comment by sunnylqm** [comment]
It's weird but this may be caused by `white space` character in your path. It is a good habit to always avoid special characters like Chinese characters or white spaces in any file/folder/variable naming.

**Comment by Tom29** [comment]
Same issue, React Native is going to die because of these stupid errors.
I would say 70% of my effort to produce this app was spent scaffolding React Native, instead of doing any actual coding. It sucks!

**Comment by hramos** [comment]
@Tom29 I am sorry you're frustrated by these. The goal of these issues is to surface these problems and collaborate together on a solution. I know you are venting, and perhaps there's a better outlet for that elsewhere.

**Comment by pengcao1** [comment]
I have a resolved this issue in my side, here is the steps:

1. copy `node_modules/react-native/script` to `node_modules/react-native/glog-0.3.5` or `node_modules/react-native/glog-0.3.4`
2. go to `node_modules/react-native/glog-0.3.5` to run the `ios-install-xxxxx.sh`
3. run `ios-configure-xxxx.sh` --> this script try to build the glog and genterate some configure file(eg: `config.h`)
4. try to build again

**Comment by sunnylqm** [comment]
@pengcao1 This should already be fixed in 0.57.8. Try that version first. If the issue persists please open a new issue and give more detailed information.

**Comment by lmyl** [comment]
Thank you for your suggestion. After research, I found that I can solve this problem by the following methods.
`cd node_modules/react-native && scripts/ios-install-third-party.sh && cd third-party && cd glog-0.3.5 && ./configure && cd ../../../../`

**Comment by pengcao1** [comment]
@sunnylqm yes, maybe you're right. but, I think nobody would upgrade to 0.57.8 for resolving only this issue. that make risks...

**Comment by sunnylqm** [comment]
@pengcao1 Patch version is quite safe to update, which I think is a common sense. Otherwise how people fix things?

**Comment by ajijoyo** [comment]
Even on react native 0.57.8 this issue still appear, when successfull `./configure` then run `react-native run-ios` and that `config.h` suddenly disappear

**Comment by sunnylqm** [comment]
@ajijoyo Open a new issue with detailed information
