### ISSUE TITLE
Expected path to be relative to one of the project roots

### ISSUE THREAD

**Issue by jerinho** [facebook/react-native#22533]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Environment:
-  OS: Windows 10
-  Node: 8.11.4
-  Yarn: 1.9.4
-  npm: 6.4.1
-  Watchman: 4.9.4
-  Xcode: N/A
-  Android Studio: Not Found

Packages: (wanted => installed)
-  react: 16.6.3 => 16.6.3
-  react-native: 0.57.7 => 0.57.7

## Description
**in file** `node_modules/metro/src/node-haste/lib/toLocalPath.js`
**function** `toLocalPath(roots, absolutePath)`
**throws error** `Expected path C:/.../index.js to be relative to one of the project roots`
**because** **roots** contains symlink path of file
**whereas** **absolutePath** is path of actual file location

## Reproducible Demo
1. Setup an application project and a library project if not yet and link em all. Follow [this](https://facebook.github.io/react-native/docs/native-modules-android)
2. Delete all caches in **C:/.../AppData/Local/Temp**
3. `react-native run-android`

[_maintainer's note: edited out unnecessary language_]

**Comment by NSShentu** [comment]
emmmmm...
same problem....
what can i do...
bundling failed: Error: Expected path `/Users/stch/Desktop/.../libs/dist/index.js` to be relative to one of the project roots
    at toLocalPath (/Users/stch/Desktop/inlight-board/apps/native/node_modules/metro/src/node-haste/lib/toLocalPath.js:31:9)

**Comment by hramos** [comment]
Metro does not support symlinks at this time. This is one of the top requested features, so maybe it will change, but for now, please avoid using a symlink here.
