### ISSUE TITLE
TestIDs for view under TouchableWithoutFeedback not found even when accessible property for the touchable is set to false.

### ISSUE THREAD

**Issue by sajManzoor** [facebook/react-native#22539]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 1.64 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.11.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
    IDEs:
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1

## Description
I cannot find the test-id of the view under TouchableWithoutFeedback mapped to the accessibility identifier.

`<TouchableWithoutFeedback accessible={false}>`
`<View testID='foo'></View>`
`</TouchableWithoutFeedback>`

In this case the accessibilityID 'foo' cannot be found.

## Reproducible Demo
`<TouchableWithoutFeedback accessible={false}>`
`<View testID='foo'></View>`
`</TouchableWithoutFeedback> `

**Comment by rickhanlonii** [comment]
Hey @sajManzoor, should this be `testID` ([the D is uppercase](https://github.com/facebook/react-native/blob/ee7c702308cbf1a2a1509be51c9c5fd263a85f36/Libraries/Components/View/ViewPropTypes.js#L395))?

**Comment by sajManzoor** [comment]
HI @rickhanlonii , yeah it should be uppercase D, my bad , but the issue still persists for `testID`.

**Comment by jsdevel** [comment]
https://github.com/facebook/react-native/pull/9942
