### ISSUE TITLE
react-native-git-upgrade doesn't change template files, only react-upgrade command does

### ISSUE THREAD

**Issue by izikandrw** [facebook/react-native#22538]
- [X] Review the documentation: https://facebook.github.io/react-native
  - [X] Search for existing issues: https://github.com/facebook/react-native/issues
  - [X] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 818.50 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.7.0 - ~/.nvm/versions/node/v10.7.0/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.7.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0
      react-native: 0.57.7 => 0.57.7
    npmGlobalPackages:
      react-native-git-upgrade: 0.2.7

### Summary
* when I upgrade using `react-native-git-upgrade` many of the template files are not changed even though they seem like the should be. I think they should be getting upgraded because of the diffs on https://github.com/ncuillery/rn-diff and my own manual running of the `react-native upgrade`command in a copy of my repo and looking at the git diff. 

small example of this is in `.flowconfig`. When I run `react-native-git-upgrade` `.flowconfig` is not changed. When I run react-native upgrade these lines `esproposal.optional_chaining=enable
esproposal.nullish_coalescing=enable` are added.

another example of this is in `build.grade`.
With `react-native-git-upgrade` it doesn't touch this file. With `react-native upgrade` many lines are added including `implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules`

What could be the cause of these kinds of discrepancies?

**Comment by kelset** [comment]
👋 currently `react-native-git-upgrade` is a bit outdated / not maintained, so we are discussing it [over here](https://github.com/react-native-community/discussions-and-proposals/issues/68).

Over there you can find also alternative/temporary solutions.

But long term plan is to add a new version of the upgrade command to the new CLI.
Hope this can help 😇

**Comment by hramos** [comment]
The command line tools have their own repository and issue tracker over at https://github.com/react-native-community/react-native-cli.
