### ISSUE TITLE
[Layout] 0.8.0 flexWrap: 'wrap' yields blank screen

### ISSUE THREAD

**Issue by ppiekarczyk** [facebook/react-native#2253]
React Native: 0.8.0
My app turns completely white when using `flexWrap: 'wrap'` and `flexDirection: 'row'` together.

```
<View style={styles.row}>
   <View style={styles.item}></View>
   <View style={styles.item}></View>
   <View style={styles.item}></View>
</View>
```

```
row: {
   flex: 1,
   flexWrap: 'wrap',
   flexDirection: 'row'
}
```

**Comment by brentvatne** [comment]
@ppiekarczyk - please post an example of what the exact same thing would look like on web so we can determine if that is broken or not :) Also please post item styles

**Comment by ide** [comment]
This could be the 100% cpu bug with that combination of styles.

**Comment by ppiekarczyk** [comment]
I will update this tonight, thank you!

**Comment by ppiekarczyk** [comment]
Here is what it's supposed to look like in the browser:
https://jsfiddle.net/eoyc03du/

As you can see, `flex-wrap` lets the text wrap inside the container.

This exact code yields the blank screen. Removing `flexWrap` fixes the issue 
```javascript
row: {
    alignItems: 'center',
    backgroundColor: '#fff',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between'
  },
  item: {
    backgroundColor: '#fff',
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#3498db',
    padding: 3
  }
```

**Comment by ide** [comment]
A 100% CPU bug in css-layout has been patched in 0.10 and 0.11-rc.

**Comment by ppiekarczyk** [comment]
Thank you James! You rock!

**Comment by ide** [comment]
Credit goes to @vjeux for https://github.com/facebook/css-layout/commit/9001a3d2 and @spicyj for finally just cherry-picking it in :)

Good bug to have fixed.
