### ISSUE TITLE
AppState.addEventListener stop working after staying in background for too long

### ISSUE THREAD

**Issue by James2516** [facebook/react-native#22540]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
  React Native Environment Info:
    System:
      OS: macOS 10.12.6
      CPU: x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
      Memory: 282.63 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.12, tvOS 12.1, watchOS 5.1
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: 0.57.1 => 0.57.1 
```
## Description
```
AppState.addEventListener('change', this._handleAppStateChange)
```

I called this in a js file on global scope. It works fine initially but if the app stays in the background for too long, it will stop working even after the app resumes (not restarts, app was still in the background).

Tested on Samsung Android 8.0.

**Comment by rickhanlonii** [comment]
Hey @James2516, sorry for the delay here

This API is not supported globally, it needs to be inside a react component to make sure the app lifecycle is managed correctly, see the docs here: https://facebook.github.io/react-native/docs/appstate

**Comment by James2516** [comment]
Hi @rickhanlonii, it is not stated on the docs that the API call should be inside a React component. You might want to add that to the docs?
