### ISSUE TITLE
Undefined is not an object (evaluating 'RCTAsyncStorage.multiMerge')

### ISSUE THREAD

**Issue by boreales** [facebook/react-native#22556]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
  React Native Environment Info:
    System:
      OS: macOS 10.14.1
      CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 463.56 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 9.5.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 26, 27
        Build Tools: 27.0.3
        System Images: android-27 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1

## Description
<img src="https://imgur.com/xjR2E6N.png" alt="image" style="max-width:100%;">

## Reproducible Demo
```
// Store/configureStore.js

import { createStore } from 'redux'
import toggleFavorite from './reducers/favoriteReducer'
import setAvatar from './reducers/avatarReducer'
import { persistCombineReducers } from 'redux-persist'
import storage from 'redux-persist/lib/storage'

const rootPersistConfig = {
  key: 'root',
  storage: storage
}

export default createStore(persistCombineReducers(rootPersistConfig, {toggleFavorite, setAvatar}))
```

The problem seems to be the same as [#21948](https://github.com/facebook/react-native/issues/21948) but I have last react-native version and can't fix it anyway. Any idea ?

**Comment by bartolkaruza** [comment]
I've been going through the code in the AsyncStorage and as far as I can tell, it is not very likely that this error can occur in vanilla React Native. @ide There are some differences in how AsyncStorage is resolved between RN and Expo, right? Could this be related to that?

[This line](https://github.com/facebook/react-native/blob/7fb02889d7c328c45f8858ec9ef293373c1ec038/Libraries/Storage/AsyncStorage.js#L331) can only have RCTAsyncStorage undefined if the assignment [here](https://github.com/facebook/react-native/blob/7fb02889d7c328c45f8858ec9ef293373c1ec038/Libraries/Storage/AsyncStorage.js#L18) fails for all AsyncStorage back-ends.

**Comment by SamuelKern2020** [comment]
I have this same problem after ejecting from Expo to vanilla react native... Anyone find a solution?

**Comment by cpojer** [comment]
This issue has been moved to react-native-community/react-native-async-storage#14.
