### ISSUE TITLE
[Packager] Cannot resolve static image when name is escaped

### ISSUE THREAD

**Issue by grabbou** [facebook/react-native#2257]
Hey,

Adding `x.png` and `x@2x.png` makes it impossible to require these images. Renaming to something else solves the issue, might be the problem that images are actually saved like this on the file system:
```
	new file:   iOS/Images.xcassets/Cancel.imageset/Contents.json
	new file:   "iOS/Images.xcassets/Cancel.imageset/\303\227.png"
	new file:   "iOS/Images.xcassets/Cancel.imageset/\303\227@2x.png"
	new file:   "iOS/Images.xcassets/Cancel.imageset/\303\227@3x.png"
```

Not really sure if that's a problem, if not - worth mentioning in the docs definitely.

**Comment by brentvatne** [comment]
@grabbou - can you submit a pull request to add this clarification to the docs? :)

**Comment by grabbou** [comment]
Yep, just not sure what section fits this information best, any ideas? https://facebook.github.io/react-native/docs/getting-started.html#content

**Comment by brentvatne** [comment]
@grabbou - Image docs seem appropriate

**Comment by nicklockwood** [comment]
I'm not sure I understand the issue.

**Comment by grabbou** [comment]
I am not sure how the packager works internally, but it looks like it has issues when you use a name for static asset that's then escaped by iOS. In my case, the `x.png` was saved on the filesystem with a different name although the name in `Images.xcassets` was still `x`. React was throwing that it cannot resolve such a module. Changing the name to something else, in my case 'Close' solved the issue.

**Comment by nicklockwood** [comment]
Oh, I see. Are you using the `source={require(image!foo)}` syntax for your images? If so, using `source={{uri: 'foo'}}` is a workaround that skips the static validation. Validation of xcassets is pretty broken tbh, as it makes a lot of assumptions about the name that aren't valid.

**Comment by grabbou** [comment]
Yeah, that's what I am using, plain objects only for remote locations.

**Comment by nicklockwood** [comment]
@grabbou It's not recommended because it doesn't check that the file exists at packaging time, only at runtime. There's no other reason though. And yes, it's fine to use generated uris / paths with this approach.

**Comment by grabbou** [comment]
Awesome, thank you a lot for the explanation.

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/packager-cannot-resolve-static-image-when-name-is-escaped
