### ISSUE TITLE
Xcode Archive Error

### ISSUE THREAD

**Issue by ArtyomCommander** [facebook/react-native#22571]
ld: warning: object file (/Users/artyom/Library/Developer/Xcode/DerivedData/opishop-apdqdiouuplzcccwuvsfoqirzpug/Build/Intermediates.noindex/ArchiveIntermediates/opishop/BuildProductsPath/Release-iphoneos/libRNAccountKit.a(RNAccountKit.o)) was built for newer iOS version (9.2) than being linked (8.0)
ld: warning: object file (/Users/artyom/Library/Developer/Xcode/DerivedData/opishop-apdqdiouuplzcccwuvsfoqirzpug/Build/Intermediates.noindex/ArchiveIntermediates/opishop/BuildProductsPath/Release-iphoneos/libRNAccountKit.a(RNAccountKitViewController.o)) was built for newer iOS version (9.2) than being linked (8.0)
ld: could not reparse object file in bitcode bundle: 'Invalid bitcode version (Producer: '1000.11.45.2_0' Reader: '902.0.39.2_0')', using libLTO version 'LLVM version 9.1.0, (clang-902.0.39.2)' for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

This is the only output from the logs.

Environment:
  OS: macOS High Sierra 10.13.6
  Node: 8.11.3
  Yarn: Not Found
  npm: 6.4.1
  Watchman: 4.7.0
  Xcode: Xcode 9.4 Build version 9F1027a
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: 16.4.1 => 16.4.1
  react-native: ^0.55.4 => 0.55.4

**Comment by yongching** [comment]
im having the same issue +1

**Comment by NicWickman** [comment]
Same issue on the newest version of RN.

**Comment by hramos** [comment]
Can either of you open a new issue? Please make sure to follow the template, thanks!

**Comment by yongching** [comment]
I get rid of this by upgrading to the latest Xcode 10.1
