### ISSUE TITLE
Dependency module not mocks by jest.mock

### ISSUE THREAD

**Issue by leerman** [facebook/react-native#22574]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
React Native Environment Info:
    System:
      OS: macOS 10.14.1
      CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 260.95 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.3 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    npmPackages:
      react: 16.6.1 => 16.6.1 
      react-native: 0.57.7 => 0.57.7 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

## Description
Dependency modules not mocks by `jest.mock`

## Reproducible Demo
```
//jest config
{
    "preset": "react-native",
    "transform": {
      "^.+\\.(js)$": "<rootDir>/node_modules/react-native/jest/preprocessor.js"
    }
}

// module1.js
export default class Module1{
    testFunction(){
        return 2
    }
}

// module2.js
import Module1 from './module1';
const module1 = new Module1();
export default module1.testFunction();

// test.js
jest.mock('./module1',()=>{ });
import module2 from './module2';
describe('test',()=>{
    it('description', ()=>{
        expect(module2).toBe(2)
    })
});
```

## Expected Behavior
Test failed

## Actual Behavior
Test passed

**Comment by TJTorola** [comment]
I was able to finally fix this issue by pulling out the jest preprocessor (`cp node_modules/react-native/jest/preprocessor.js ./jest.preprocessor.js) and manually adding `[require('babel-preset-jest-hoist')],` on line 67. Also adding `{ transform: { "^.+\\.js$": "<rootDir>/jest.preprocessor.js" } }` in the jest block on package.json. Sorta related to this other issue with this version of RN and jest, https://github.com/tylergaw/RNUpgradePath#issue-4.

**Comment by stabilemobile** [comment]
@TJTorola 's solution worked for me, however I added `[require('babel-plugin-jest-hoist')]` to the preprocessor (i.e. `plugin`, not `preset`). Typo? :)

```
"react-native": "0.57.8",
...
"babel-jest": "23.6.0",
"jest": "23.6.0",
```

**Comment by TJTorola** [comment]
@stabilemobile Sure is, my bad.

**Comment by TJTorola** [comment]
This appears to be fixed after upgrading to `jest@24` & `react-native@0.58`

**Comment by bartolkaruza** [comment]
Closing 

> This appears to be fixed after upgrading to `jest@24` & `react-native@0.58` and removing the `jest.preprocessor.js` transform from the jest config.

Closing based on this, let us know if this is not fixed yet and we'll reopen.

**Comment by VitorBrangioni** [comment]
Same issue. Any solution? I'm using the jest v 25.1.0

**Comment by ivan-gil** [comment]
> This appears to be fixed after upgrading to `jest@24` & `react-native@0.58` and removing the `jest.preprocessor.js` transform from the jest config.

@TJTorola are you sure? I use react-native@0.59.9 and jest@24.9 and seems I need to apply your fix...
