### ISSUE TITLE
Loading from localhost:8081

### ISSUE THREAD

**Issue by vivekpchrome** [facebook/react-native#22588]
Hi Team I have never seen such a technology . I have installed the React for Android development and I am facing issue : It always shows me Loading from Localhost:8081 not going anywhere I have tried all the solutions which are available but not working AT ALL . I have installed and uninstalled React 50 times but I am getting this error again and again Its is wasting my time truly . If I use already created github project that is working fine like : https://github.com/react-native-material-design/react-native-material-design , If I use this it runs but If I use official document and installation according to them not working AT ALL. Can you help me out with and I need solution which is working Please don't link some un-useful links . It is such a ... experience. I am new to this please help

**Comment by fotonmoton** [comment]
Did you install watchman? If so try to run `watchman watch-del-all`

**Comment by vivekpchrome** [comment]
after this command : react-native run-android it always shows me loading from localhost:8081, the response of this  command is : watchman watch-del-all
{
    "version": "4.9.4",
    "roots": [
        "/home/user/Android_projects/react_project/testapp/demo-app"
    ]
}

**Comment by vivekpchrome** [comment]
It is the worst technology I have ever seen truly I wrote down  sudo react-native run-android it start working  but after 5 min it gives me error "com.android.builder.testing.api.DeviceException: com.android.ddmlib.AdbCommandRejectedException: device not found
" where as the device is connected and I can run my android studio project and adb devices shows that the device is connect I am using it on real device.
