### ISSUE TITLE
Exception '-[RCTCxxBridge networking]: unrecognized selector sent to instance 0x6000003c4bf0' was thrown while invoking addNetworkingHandler on target BlobModule with params

### ISSUE THREAD

**Issue by amithardikar** [facebook/react-native#22583]
In xcode i am facing this issue

version which i have use as follows 

 "native-base": "^2.4.5",
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-code-push": "5.3.4",
    "react-native-fcm": "16.2.0",
    "react-native-fs": "2.10.14",
    "react-native-image-crop-picker": "0.18.2",
       "react-navigation": "2.0.4",
    "react-redux": "5.0.7",
    "redux": "4.0.0",
    "redux-thunk": "2.3.0"

**Comment by hramos** [comment]
Hey, the Discussion template is meant for long-form discussions about React Native. This looks like a request for help. Please take a look at http://facebook.github.io/react-native/en/help.html for a list of help resources.

**Comment by diegobfernandez** [comment]
@amithardikar I recently faced the same issue. After some thoughts I realized I was unlink react-native itself from the project and linking again which kept network libraries out of project.pbxproj.
If you are unlinking dependencies check if you are unlink react-native by mistake. If you already did that and commited your changes I suggest reverting that commit.

**Comment by WebMobi59** [comment]
Same here

**Comment by WebMobi59** [comment]
@diegobfernandez can you let me know more details what you did?

**Comment by edritech93** [comment]
same for me

**Comment by diegobfernandez** [comment]
@WebMobi59 @edritech93 I just reverted the commit that unlinked react-native and nothing else.
If you don't know how to do it have a look at git documentation: https://git-scm.com/docs/git-revert

If that doesn't work you could try `react-native link react-native` but I'm not sure that will work.

**Comment by rezanouri87** [comment]
has anyone found any solution for this?

**Comment by wildkatana** [comment]
I had this issue for the longest time and nothing worked. In the end I realized that my RCTNetwork library wasn't being linked correctly. AndreL on stackoverflow posted the fix: https://stackoverflow.com/questions/47159026/xcode-librarby-not-found-for-irctnetwork

Steps to fix:

1. Drag the file, RCTNetwork.xcodeproj from node_modules/react-native/Libraries/Network/ to the libraries file in Xcode.

2. Click on Build Phases on the top right-hand corner in Xcode.

3. Click the drop down of Link Binary With Libraries, then the + sign to add the libRCTNetwork.a

4. Run the build and restart your emulator or device.
