### ISSUE TITLE
Error: uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX

### ISSUE THREAD

**Issue by cyprusglobe** [facebook/react-native#2258]
@ide @vjeux 
https://github.com/Homebrew/homebrew/issues/42553

Thought you guys might run into this issue with using brew inside travis.yml

Simple fix would be 

```
brew update; brew update # Workaround for https://github.com/Homebrew/homebrew/issues/42553
```

instead of

```
brew update
```

**Comment by brentvatne** [comment]
Thanks for pointing this out - it looks like Travis is working properly right now but if it starts to fail I'll make sure to surface this!
