### ISSUE TITLE
SectionList Performance Issue : renders All the Items each time

### ISSUE THREAD

**Issue by Rishabh-Rathod** [facebook/react-native#22584]
**SectionList Renders Each item though i have implemented ShouldComponentUpdate , also Tried using PureComponent.** 

`
this.state={
      datasource:getMenuData(),
      cartitems:[],
      isUserLoggedIn:false,
      addressAdded:false,
      totalPrice:0,
      toPay:0,
      totalItems:0,
    };
`

renderItem Implementation :
`
_renderItem = ({item, index,section:{title,data}}) =>{
  return (
  <View>
      <Item
      onAdd={this.addItemToCart.bind(this,item)}
      onRemove={this.removeItemFromCart.bind(this,item)}
      item={item}
      ></Item>
       
    </View>

  )
}`

SectionList Implementation :

`<SectionList
            showsVerticalScrollIndicator={false}
            initialNumToRender={5}
            ref={s => (this.sectionList = s)}
            renderItem={this._renderItem}                                          
            renderSectionHeader={({section:{title}})=>(<View><Text>{title}</Text></View>)}
            sections={this.state.datasource}
            keyExtractor={(item, index) => index}
            stickySectionHeadersEnabled={true}
            maxToRenderPerBatch={2}
            onEndReachedThreshold={0.5}
    
        />`

**Comment by hramos** [comment]
Hey, the Discussion template is meant for long-form discussions about React Native. This looks like a request for help. Please take a look at http://facebook.github.io/react-native/en/help.html for a list of help resources.

**Comment by Rishabh-Rathod** [comment]
Thanks. Anyways I resolved my issue

**Comment by stanislavgalin** [comment]
@Rishabh-Rathod How dod you resolve the issue with performance ?

**Comment by blaues0cke** [comment]
@Rishabh-Rathod Would be really great if you can share your learnings!

**Comment by SteFF1997** [comment]
**I found great resolve for the case where you need a list of items who switch between: with sections/without sections**
So as I understood from documentation for this task I must use one SectionList and switch that with sections/without sections using SectionList props, but its wrong as I understood from the performance what I saw
Solution: Create two lists - FlatList and SectionList for switch between with sections/without sections
**something like this:** 
`if (withSections) { return (<SectionList .... />) } return (<FlatList .... />) `

Image for good understanding of this case
<img width="277" alt="Снимок экрана 2019-08-06 в 13 18 21" src="https://user-images.githubusercontent.com/14296974/62533230-dad71780-b84e-11e9-81ff-6ec2643cc1ee.png"> <- FlatList
.
.
.
<img width="284" alt="Снимок экрана 2019-08-06 в 13 18 40" src="https://user-images.githubusercontent.com/14296974/62533233-dca0db00-b84e-11e9-861b-f80d61801634.png"> <- SectionList
