### ISSUE TITLE
Flow types erased for `fetch`

### ISSUE THREAD

**Issue by jeremywiebe** [facebook/react-native#22590]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Run `react-native info` in your terminal and paste its contents here.
`[skip envinfo]`

## Description
I spent some time trying to improve the flow typing in our codebase last week. I was stumped why functions using `fetch` couldn't properly type the return value `Promise<Response>`. Flow definitely includes proper typing. 

I traced it down to the `react-native-interface.js` which erases types for `fetch` and it's associated types (https://github.com/facebook/react-native/blob/master/Libraries/react-native/react-native-interface.js#L21). 

It looks like this was set up 4 years ago according to git blame and I suspect that was before Flow added those types as built-ins. 

## Reproducible Demo
In any React Native project that uses Flow, just run `yarn flow type-at-pos <file-that-uses-fetch.js> row col` (for a position where `fetch` is used).

You'll see the result is `any`. 

If you comment out the line in the project `.flowconfig` that includes `react-native-interface.js` (`[libs] section`) that same `flow type-at-pos` command returns the correct type (`Promise<Response>`).

**Comment by jeremywiebe** [comment]
@react-native-bot Environment is irrelevant as this is in RN 0.57 and `master`

**Comment by hramos** [comment]
cc @brentvatne (original author)

**Comment by ferrannp** [comment]
Hello there 👋 this issue seems to have a really low activity on it. This is probably because OP managed to find a solution - also, it was most likely related their precise configuration. Because of this inactivity, we are closing it - but please feel free to comment and post a repro for version 0.59 and we'll gladly re-open it 🤗
