### ISSUE TITLE
System fonts are overriding app font

### ISSUE THREAD

**Issue by ianbutler** [facebook/react-native#22591]
## Environment
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
      Memory: 751.02 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5014246
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1
      react-native: 0.56.0 => 0.56.0
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description
With the Samsung Galaxy Note 8, the user has the ability to change the device's system fonts.  This overrides the app fonts.  I would like a way to figure out how to disable the system fonts for our app or override them with our app's fonts.

This issue is similar to #17858, #12978, #12989 but both of those issues were closed without resolution.

**Comment by SABRYX** [comment]
@ianbutler did you find any workaround

**Comment by maxoux** [comment]
Having same Issue on last version, and i see it's a bug often discussed, any recommendations to prevent this ?
