### ISSUE TITLE
React Native project runs in Android Studio but not from terminal

### ISSUE THREAD

**Issue by HasnainAD** [facebook/react-native#22597]
I am new to both react-native and JS. I am facing this issue where when I run my project on device using Android Studio 'run', it works. But when I try to run it using "react-native run-android" command, it doesn't run with following error:

What went wrong: Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'. Could not create service of type AnnotationProcessorDetector using JavaGradleScopeServices.createAnnotationProcessorDetector().

This error also shows when I try to build debug Apk.

**Comment by harvey-woo** [comment]
facing same error

**Comment by jonasantonelli** [comment]
Try it using `sudo react-native run-android`.

It worked for me.
