### ISSUE TITLE
RCTAnimationManager not linked by default

### ISSUE THREAD

**Issue by JoeStanton** [facebook/react-native#226]
When using `react-native init`, you don't get to access `AnimationManager` without manually linking. Is this intentional?

**Comment by clauderic** [comment]
+1

**Comment by sahrens** [comment]
Just needs to be added to SampleApp which is what the init script uses for the template.

**Comment by jcgertig** [comment]
+1

**Comment by jcgertig** [comment]
Even with manually linking i am getting this error https://www.dropbox.com/s/r80zzgk62otaq3r/Screenshot%202015-04-01%2020.16.42.png?dl=0

**Comment by sahrens** [comment]
Just an oversight - feel free to send a PR for SampleApp.xcodeproj which is used as the template (if there isn't one already - sorry we haven't been able to keep up with PRs!)

**Comment by sherodtaylor** [comment]
+1

**Comment by brentvatne** [comment]
Discussion has moved to #613, closing, thanks!
