### ISSUE TITLE
Xcode 10 double-conversion shell script invocation issue.

### ISSUE THREAD

**Issue by ManishAhire** [facebook/react-native#22600]
How to solve the double-conversion issue. I'm adding lib double-coversion.a & third-party.a into link libraries. Clean and rebuild the project, but not working. 

Also tried to clean ~/.rnchache and run react-native run-ios but not working.

Please find the below screen shots for more help.

<img width="1436" alt="screenshot 2018-12-10 at 3 16 26 pm" src="https://user-images.githubusercontent.com/13014818/49726322-bb71f580-fc93-11e8-8dc4-e0500b66a043.png">

<img width="790" alt="screenshot 2018-12-10 at 3 16 42 pm" src="https://user-images.githubusercontent.com/13014818/49727367-16a4e780-fc96-11e8-86fb-e9b2c78a4395.png">

**Comment by thevolcanomanishere** [comment]
Try deleting the node_modules/react-native/thirdparty folder

**Comment by ManishAhire** [comment]
I tried the same but no luck :(

**Comment by opiruyan** [comment]
Do you have third-party-podspecs folder?

**Comment by ManishAhire** [comment]
Yes

> Do you have third-party-podspecs folder?

Yes

**Comment by opiruyan** [comment]
I think you just need to delete whole node_modules and run npm install

**Comment by hramos** [comment]
Hey, the Discussion template is meant for long-form discussions about React Native. This looks like a request for help. Please take a look at http://facebook.github.io/react-native/en/help.html for a list of help resources.
