### ISSUE TITLE
[AppStateIOS] undefined is not a function 'handler(appStateData.app_state)' in AppStateIOS.js

### ISSUE THREAD

**Issue by adamveld12** [facebook/react-native#2262]
[Here is the line of code referenced in the stack trace](https://github.com/facebook/react-native/blob/master/Libraries/AppStateIOS/AppStateIOS.ios.js#L96)

Here is a [react playground link](https://rnplay.org/apps/pd4FQQ) and the steps to reproduce are:

1. run the app
2. minimize via home button
3. open the app again by selecting the icon

You are greeted with the red screen of death and a stack trace.

**Comment by brentvatne** [comment]
Hi there, it looks like you're missing a d in your function name: ![](http://url.brentvatne.ca/Oqob)

**Comment by adamveld12** [comment]
Ha, well sorry about that! Thanks.
