### ISSUE TITLE
Timers are unreliable (firing too fast) when Dev Tools are open

### ISSUE THREAD

**Issue by dzek69** [facebook/react-native#22620]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (8) ia32 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
      Memory: 2.97 GB / 15.89 GB
    Binaries:
      Node: 11.2.0 - C:\nodejs\node.EXE
      Yarn: 1.12.3 - C:\Apps\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338
```

## Description
The same thing as here: https://github.com/facebook/react-native/issues/14639
Timers (both intervals and timeouts) are firing too fast, looks like they're dividing the time value by some factor.

## Reproducible Demo
```javascript
const start = Date.now();
console.log("start")
const fn = () => {
    console.log("end", Date.now() - start);
}
```
Simple `setTimeout(fn, 5000)` usually calls the function in around 1 second, but can be even faster.
Closing Dev Tools solves the issue.

#14639 seems to be wrongly closed by bot or there is an regression.

**Comment by konradkierus** [comment]
I'm having exactly the same issue but on Ubuntu and RN in version 0.57.5 - just for the info because if's different version of RN and system than the author.

**Comment by dzek69** [comment]
This is probably what causes https://github.com/facebook/react-native/issues/4944 (which is incorrectly closed or if it really was fixed then it should be reopened or something)

**Comment by ninofiliu** [comment]
I've got a similar issue [SO link](https://stackoverflow.com/questions/54534370/react-native-cant-set-timouts-properly-in-async-functions). #14639 was definitely wrongly closed. This issue needs to be resolved. Apps can't be built if basic time management functions don't work 😒
