### ISSUE TITLE
`getProjectRoot` does not work properly when using pnpm package manager

### ISSUE THREAD

**Issue by vjpr** [facebook/react-native#22623]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment

[skip envinfo]

## Description

__dirname is...

```
/xxx/node_modules/.github.com/expo/react-native/archive/sdk-31.0.0.tar.gz/react@16.5.0/node_modules/react-native/local-cli/server/server.js
```

getProjectRoot() returns...

```
/xxx/node_modules/.github.com/expo/react-native/archive/sdk-31.0.0.tar.gz/react@16.5.0
```

---

```
function getProjectRoot() {
  if (
    __dirname.match(/node_modules[\/\\]react-native[\/\\]local-cli[\/\\]util$/)
  ) {
    // Packager is running from node_modules.
    // This is the default case for all projects created using 'react-native init'.
    return path.resolve(__dirname, '../../../..');
  } else if (__dirname.match(/Pods[\/\\]React[\/\\]packager$/)) {
    // React Native was installed using CocoaPods.
    return path.resolve(__dirname, '../../../..');
  }
  return path.resolve(__dirname, '../..');
}
```

## Fix

Should add a special case for pnpm.

**Comment by aleclarson** [comment]
I already fixed this, I think: https://github.com/facebook/react-native/pull/21136

But it needs to be migrated to the new `react-native-cli` repository.

**Comment by hramos** [comment]
Thanks @aleclarson! @vjpr can you open an issue in the new https://github.com/react-native-community/react-native-cli repository to track this? Looks like all we need is to apply #21136 there.
