### ISSUE TITLE
[iOS] TextInput with similar font size and line height doesn't scroll with content

### ISSUE THREAD

**Issue by shaundon** [facebook/react-native#22637]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment

  OS: macOS 10.14.1
  Node: 8.14.0
  Yarn: 1.3.2
  npm: 6.4.1
  Watchman: 4.9.0
  Xcode: Xcode 10.0 Build version 10A255
  Android Studio: 3.2 AI-181.5540.7.32.5056338

Packages: (wanted => installed)
  react: 16.6.1 => 16.6.1
  react-native: 0.57.7 => 0.57.7

## Description
On iOS, if a `TextInput` has similar `lineHeight` and `fontSize` style props, the field doesn't scroll when the length of the value overflows its container.

I've done some experiments with trial and error and it appears that when they're within 2pt of each other, the issue happens.

![ezgif-4-8a9aed2dd12d](https://user-images.githubusercontent.com/73652/49936839-eabf7700-fecc-11e8-9f35-3e3ded9e5432.gif)

## Reproducible Demo
Here's a Snack with multiple test cases to illustrate the issue: https://snack.expo.io/B1JHzT1lE

**Comment by cpojer** [comment]
You are right, this seems like this is a real issue but unfortunately it's unlikely anyone will be able to spend time on this anytime soon. I'm going to close this issue but we are more than happy to receive a pull request with a fix for this!
