### ISSUE TITLE
Multiple NullPointerException in com.facebook.react.uimanager

### ISSUE THREAD

**Issue by GurpreetAhluwalia** [facebook/react-native#22642]
- [X] Review the documentation: https://facebook.github.io/react-native
  - [X] Search for existing issues: https://github.com/facebook/react-native/issues
  - [] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
  OS: macOS High Sierra 10.13.6
  Node: 8.11.3
  Yarn: 1.7.0
  npm: 5.6.0
  Watchman: Not Found
  Xcode: Xcode 10.1 Build version 10B61
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  react: 16.4.2 => 16.4.2
  react-native: 0.55.4 => 0.55.4

## Description
We are using RN in brown field development mode.
A RN view is instantiated in activity at runtime using ReactInstance Manager and added to the layout. We are seeing odd issues where our android mobile app is crashing in production because of NPE in uimanager.

LOCATION:  com.facebook.react.uimanager.NativeViewHierarchyOptimizer.removeNodeFromParent()
MESSAGE
Attempt to invoke interface method 'com.facebook.react.uimanager.ReactShadowNode com.facebook.react.uimanager.ReactShadowNode.getNativeParent()' on a null object reference

LOCATION:
com.facebook.react.uimanager.UIImplementation.updateViewHierarchy()
MESSAGE
Attempt to invoke interface method 'int com.facebook.react.uimanager.ReactShadowNode.getReactTag()' on a null object reference

## Reproducible Demo
We don't have a good repro step for this. We are not able to repro this locally.
Our APM tool is reporting this in production.

**Comment by hramos** [comment]
Hey @GurpreetAhluwalia, we typically do not track this type of issue here. As we do not have access to your application, contributors to React Native are not in a great position to debug the issue.

If you are able to investigate this a bit further, and are able to solidly repro, please feel free to open a new issue with details. We'd also prefer if you test this on the latest version as well. Thanks!
