### ISSUE TITLE
Updated to ReactNative 0.57 with index.[OS].js and not index.js

### ISSUE THREAD

**Issue by wmonecke** [facebook/react-native#22645]
## Environment
```
React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 579.55 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.9.4 - /usr/local/bin/node
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.2, macOS 10.13, tvOS 11.2, watchOS 4.2
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 26.0.2, 26.0.3, 27.0.2, 27.0.3, 28.0.2
        System Images: android-P | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: 9.2/9C40b - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.6.3 => 16.6.3
      react-native: ^0.57.8 => 0.57.8
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

## Description
When I started my react native project it was with `react-native init` (I am not 100% sure).
The .js entry files where `index.android.js` and also `index.ios.js`.

I recently updated from RN 0.47 to RN 0.57. And when running `./gradlew assembleRelease` I encountered the following error:

`The resource '/Users/waltermonecke/Documents/Code/React-Native/lisdoWorker/index.js' was not found.`

Which is obvious because I have no index.js. 
How do I deal with this? I dont want to mess up my project.

On iOS I was able to solve it since in the `AppDelegate.m` you can specify the js entry file like so:

`jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];`

However I have no idea how to do this on android. 

## Full Error Log

```
Error: The resource `/Users/waltermonecke/Documents/Code/React-Native/lisdoWorker/index.js` was not found.
    at /Users/waltermonecke/Documents/Code/React-Native/lisdoWorker/node_modules/metro/src/Server.js:348:15
    at Generator.next (<anonymous>)
    at step (/Users/waltermonecke/Documents/Code/React-Native/lisdoWorker/node_modules/metro/src/Server.js:70:30)
    at /Users/waltermonecke/Documents/Code/React-Native/lisdoWorker/node_modules/metro/src/Server.js:89:14
    at new Promise (<anonymous>)
    at /Users/waltermonecke/Documents/Code/React-Native/lisdoWorker/node_modules/metro/src/Server.js:67:12
    at Server._buildGraph (/Users/waltermonecke/Documents/Code/React-Native/lisdoWorker/node_modules/metro/src/Server.js:389:7)
    at /Users/waltermonecke/Documents/Code/React-Native/lisdoWorker/node_modules/metro/src/Server.js:218:38
    at Generator.next (<anonymous>)
    at step (/Users/waltermonecke/Documents/Code/React-Native/lisdoWorker/node_modules/metro/src/Server.js:70:30)
```

**Comment by sunnylqm** [comment]
https://github.com/facebook/react-native/releases/tag/v0.49.0

**Comment by sunnylqm** [comment]
Actually for a big version update, I recommend to init a new project and move your js code to that new project instead of update.

**Comment by kelset** [comment]
👋 there.

As pointed out by @sunnylqm, what you are attempting is not a small update but instead a 10 versions jump. So many has changed since that simply bumping the version in the package.json won't have your project run RN 0.57.

I **highly** recommend that you head over the releases section of the repo to learn what changed since [version 0.47](https://github.com/facebook/react-native/releases/tag/v0.47.2), and attempt a more gradual update (one version at the time) OR, as suggested by Sunny, create a fresh new project and migrate your code into it.

We are aware that upgrading is still in a rough place for React Native, and we are actively investigating how to make it [better here](https://github.com/react-native-community/discussions-and-proposals/issues/68).
