### ISSUE TITLE
Wrong order with RTL text

### ISSUE THREAD

**Issue by ahce** [facebook/react-native#22646]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
      Memory: 4.29 GB / 11.87 GB
    Binaries:
      Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.1.0.0 AI-173.4907809
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: 0.57.8 => 0.57.8
```

## Description
I was using this [service](https://randomuser.me), when I found this problem.
The emails are written in different languages, except the part @example.com
When the text are mixed, the order of the email changes:
This **مریم.رضایی@example.com** looks like this **example.com@مریم.رضایی**

## Reproducible Demo

See [RNTextBug](https://snack.expo.io/@ahce/rntextbug)

```
      <View style={{
          flex: 1,
          alignItems: 'center',
          justifyContent: 'center'
      }}>
        <View>
          <Text>
            {'مریم.رضایی@example.com'}
          </Text>
        </View>
        <View style={{ flexDirection: 'row' }}>
          <View>
            <Text>
              {'مریم.رضایی'}
            </Text>
          </View>
          <View>
            <Text>
              {'@example.com'}
            </Text>
          </View>
        </View>
      </View>
```

**Comment by hramos** [comment]
Thanks for providing a Snack! Do you mind editing your issue to make sure it describes the problem in detail as well? That will go a long way towards helping others understand the issue you are reporting, without having to first launch the app in Snack.

**Comment by ahce** [comment]
@hramos Thanks for your reply. 
I updated the description.
