### ISSUE TITLE
Unable to touch and drag an SVG Line

### ISSUE THREAD

**Issue by spyshower** [facebook/react-native#22650]
- [tick] Review the documentation: https://facebook.github.io/react-native
  - [tick] Search for existing issues: https://github.com/facebook/react-native/issues
  - [tick] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Run `react-native info` in your terminal and paste its contents here.

HERE:

React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
      Memory: 30.88 MB / 4.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.13.0 - /usr/local/bin/node
      Yarn: 1.12.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
      svg-to-react-native-cli: 0.0.3

## Description
Describe your issue in detail. Include screenshots if needed. If this is a regression, let us know.

HERE:

Hello,

I am trying to implement a clock in which a user can touch a pointer and move it. This behavior works as expected on iOS but not on Android. Specifically, when you touch the pointer the 1st time it works normally, however after that while the View is being displayed at the right point on the clock, the actual View(?) is in it’s original spot (invisible, but it’s there).

I am not sure if this is RN's bug or SVG's bug.

## Reproducible Demo
Let us know how to reproduce the issue. Include a code sample, share a project, or     share an app that reproduces the issue using https://snack.expo.io/. Please follow the guidelines for providing a MCVE: https://stackoverflow.com/help/mcve

HERE SNACKS:

- https://snack.expo.io/@spyshower/clock-svg (notice: lots of irrelevant code, you care about the onTouchEvent(…) function)

- https://snack.expo.io/@spyshower/smiling-blueberries

**Comment by kelset** [comment]
> I am not sure if this is RN's bug or SVG's bug.

It seems to me that is actually either an Expo or SVG issue, unless you can repro using only the React Native library I suggest you open an issue over the Expo repo. Not sure what they use to implement SVGs, but you should also check for `react-native-svg`s similar issues.
