### ISSUE TITLE
Simple LinearGradient component

### ISSUE THREAD

**Issue by amerllica** [facebook/react-native#22668]
Actually, I'm so confused about the linear gradient background, it's so easy to implement linear gradient background. I implement it so easy just with JavaScript but I rarely see a solution for it on the internet, the most trend library is [this library](https://github.com/react-native-community/react-native-linear-gradient), that has Native side code for Android and iOS.

But I create linear gradient very simple just with JavaScirpt and test it on both Android and iOS. Why my solution didn't implement yet?

**Comment by bosung90** [comment]
Can you share the code?

**Comment by amerllica** [comment]
@bosung90 , Yeah, Sure:

    import React, { createElement } from 'react';
    import PropTypes from 'prop-types';
    import { View, StyleSheet, Dimensions } from 'react-native';
    import { styleJoiner } from 'utils/helpers';
    import { colors } from 'utils/constants/theme';
    
    const HEIGHT = Dimensions.get('window').height;
    
    const blender = (color1, color2, percent) => {
      const generateHex = (r, g, b) => {
        let R = r.toString(16);
        let G = g.toString(16);
        let B = b.toString(16);
    
        while (R.length < 2) {
          R = `0${R}`;
        }
        while (G.length < 2) {
          G = `0${G}`;
        }
        while (B.length < 2) {
          B = `0${B}`;
        }
    
        return `#${R}${G}${B}`;
      };
    
      const mix = (start, end, prcnt) => start + prcnt * (end - start);
    
      const red1 = parseInt(color1[1] + color1[2], 16);
      const green1 = parseInt(color1[3] + color1[4], 16);
      const blue1 = parseInt(color1[5] + color1[6], 16);
    
      const red2 = parseInt(color2[1] + color2[2], 16);
      const green2 = parseInt(color2[3] + color2[4], 16);
      const blue2 = parseInt(color2[5] + color2[6], 16);
    
      const red = Math.round(mix(red1, red2, percent));
      const green = Math.round(mix(green1, green2, percent));
      const blue = Math.round(mix(blue1, blue2, percent));
    
      return generateHex(red, green, blue);
    };
    
    const gradientRows = (firstColor, secondColor) => {
      const rows = [];
    
      for (let i = 1; i <= HEIGHT; i += 1) {
        const row = createElement(
          View,
          {
            key: `row_${i}`,
            style: styleJoiner(styles.row, {
              backgroundColor: blender(firstColor, secondColor, (1 / HEIGHT) * i)
            })
          },
          null
        );
        rows.push(row);
      }
      return rows;
    };
    
    const LinearGradient = ({ children, style, firstColor, secondColor }) => (
      <View style={styles.linearGradient}>
        {gradientRows(firstColor, secondColor)}
        <View style={styleJoiner(styles.childrenWrapper, style)}>{children}</View>
      </View>
    );
    
    LinearGradient.propTypes = {
      style: PropTypes.oneOfType([PropTypes.object, PropTypes.array]),
      firstColor: PropTypes.string.isRequired,
      secondColor: PropTypes.string.isRequired,
      children: PropTypes.oneOfType([
        PropTypes.element,
        PropTypes.arrayOf(PropTypes.element)
      ]).isRequired
    };
    
    LinearGradient.defaultProps = {
      style: undefined
    };
    
    const styles = StyleSheet.create({
      linearGradient: {
        flex: 1,
        position: 'relative'
      },
      row: {
        width: '100%',
        height: 1
      },
      childrenWrapper: {
        position: 'absolute',
        top: 0,
        right: 0,
        bottom: 0,
        left: 0,
        backgroundColor: colors.transparent.invisible
      }
    });
    
    export default LinearGradient;

**Comment by amerllica** [comment]
Dear @bosung90 , Do you see my code? Is it acceptable for became a PR?

**Comment by amerllica** [comment]
Dear @kelset, You remove my `forDiscussion` tag and add `featureRequest`, Does it mean I'm on the right way? I wanna work on my code and send a PR.

**Comment by bosung90** [comment]
LinearGradient without native code sounds awesome. I don't think it should be part of official react native as we want to make sure react-native core is as thin and small as possible. You can look into creating it into your own library and possibly make it be part of https://github.com/react-native-community in the future

**Comment by bosung90** [comment]
You should definitely create a library regardless. There is react-native feature request https://react-native.canny.io/feature-requests here. Once you create the library you can twit the library link to react-native core members for them to check it out.

**Comment by amerllica** [comment]
Dear @bosung90 , Thanks for your great guide, But I see 226 PRs on `react-native` [pull request](https://github.com/facebook/react-native/pulls). Do you mean these PRs are in a wrong way? Or my case is special and I should first create a library on react-native-community and then request to use it in the react-native core?

**Comment by kelset** [comment]
👋 there.

I've tagged it as a Feature Request because this issue is a request to add a feature (Linear Gradient) into the main codebase.

That said, given that we want to make the [main codebase "smaller"](https://github.com/react-native-community/discussions-and-proposals/issues/6) I don't see this feature being merged in the main repo.

What @bosung90 has been suggesting is a potential path: similarly, I suggest you create your own library for this feature. Related to have your code hosted in the RNCommunity org, we are currently [redefining it](https://github.com/react-native-community/discussions-and-proposals/issues/63) and it will have a new application process. But for now it won't happen, so, again, it's better for now if you simply create your component as its own library.

I hope this help.

I'm closing this since it won't be merged in the main codebase. But please keep the conversation moving and feel free to ask me any extra question 😊
