### ISSUE TITLE
[TextInput] Maxlength bug in specific situations

### ISSUE THREAD

**Issue by ahce** [facebook/react-native#22669]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
      Memory: 4.29 GB / 11.87 GB
    Binaries:
      Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.1.0.0 AI-173.4907809
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: 0.57.8 => 0.57.8
```

## Description

In a specific situation maxLength don't works, when a special character is inserted between a number, a character and a letter: (maxLength: 5, value: 123-r) **123[insert here "&"]-r** the result is **123&-** 
See the demo.

## Reproducible Demo
[TextInput MaxLength Bug](https://snack.expo.io/@ahce/textinput-maxlength-bug)

**Comment by dulmandakh** [comment]
This is expected behaviors. maxLength work on characters, and doesn't distinguish between special char, number or letter.
