### ISSUE TITLE
'fishhook.h' file not found

### ISSUE THREAD

**Issue by dushaobindoudou** [facebook/react-native#22679]
- [✅] Review the documentation: https://facebook.github.io/react-native
  - [✅] Search for existing issues: https://github.com/facebook/react-native/issues
  - [✅] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Run `react-native info` in your terminal and paste its contents here.
React Native Environment Info:
    System:
      OS: macOS Sierra 10.12.6
      CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 31.63 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.1.0 - ~/.nvm/versions/node/v10.1.0/bin/node
      Yarn: 1.9.2 - ~/.nvm/versions/node/v10.1.0/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v10.1.0/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.2, macOS 10.13, tvOS 11.2, watchOS 4.2
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5014246
      Xcode: 9.2/9C40b - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.1 => 16.6.1 
      react-native: 0.57.7 => 0.57.7 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-update-cli: 0.1.0

## Description
Describe your issue in detail. Include screenshots if needed. If this is a regression, let us know.
When upgrading react native to 0.57.7, using pod to add dependency compile will report an error.
in pods/FBRetainCycleDetector/FBAssociationManager.mm report the error 

'fishhook.h' file not found

![error msg](https://oktangle.com/images/fishhook.png)

## Reproducible Demo
When upgrading to 0.57.7  not have a demo

## fixed

when i use 

#import <fishhook.h>

fix this problem

**Comment by hramos** [comment]
I have not seen any reports of this happening on 0.58. Closing.

**Comment by bigggge** [comment]
same issue
