### ISSUE TITLE
["Discussion"] react native too slow to run on Android ， How to make it faster

### ISSUE THREAD

**Issue by BigWolf286** [facebook/react-native#22686]
Use https://github.com/react-native-community/discussions-and-proposals to propose changes or discuss feature requests. This helps us ensure bug reports and regressions are given the priority they require.

You may also use https://discuss.reactjs.org/ for discussions on topics that are not necessarily served by the Bug Report template.

---

# For Discussion

**Comment by radko93** [comment]
Please read the template when posting issues.
