### ISSUE TITLE
Using fetch to obtain blob results in `ERR_FILE_NOT_FOUND` & "Network request failed", workaround gets superficial string representation

### ISSUE THREAD

**Issue by atrauzzi** [facebook/react-native#22681]
- [✔️] Review the documentation: https://facebook.github.io/react-native
  - [✔️] Search for existing issues: https://github.com/facebook/react-native/issues
  - [✔️] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
      Memory: 6.39 GB / 15.94 GB
    Binaries:
      Yarn: 1.12.1 - C:\Users\atrauzzi\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

## Description

I've been working on a new react native project which needs to work with files.  Given that the most optimal way to work with binary data in JS environments is via the [`Blob` APIs](https://developer.mozilla.org/en-US/docs/Web/API/Blob), I set out to find my best option for getting binary references to local filesystem data.

After a bit of research, I discovered that I should be using the `fetch` API with local file paths.  As a side note, it might have been nice to see official documentation about opening files [here](https://facebook.github.io/react-native/docs/network.html).  Or possibly even a page dedicated to the topic as I'm sure it's fairly nuanced. 😄 

Unfortunately when I went to open the file using `fetch`, I ended up experiencing [this issue](https://github.com/react-native-community/react-native-camera/issues/2008).

After a bit more research, it appears that this problem is generally confirmed and an in-depth analysis with a workaround has been [documented by @sjchmiela here](https://github.com/expo/expo/issues/2402#issuecomment-443726662)

```typescript
//
// This is my adaptation of the suggested workaround.

const deferred = createDeferred<Blob>();
const xhr = new XMLHttpRequest();
        
xhr.responseType = "blob";
xhr.onload = () => deferred.resolve(xhr.response);
xhr.onerror = deferred.reject;

xhr.open("GET", uri, true);
xhr.send();

const blobFromFetch = await deferred.promise;
```

---

#### Possibly Related
 - https://github.com/facebook/react-native/pull/22063
 - https://github.com/facebook/react-native/issues/19717
 - https://github.com/facebook/react-native/issues/21092
 - https://github.com/expo/expo/issues/2703
 - https://github.com/facebook/react-native/issues/16034
 - https://github.com/facebook/react-native/pull/11573

---

This seems like a regression as the standard API surface area and best practice for obtaining `Blobs` for local filesystem data is not working.

**Comment by atrauzzi** [comment]
Additionally, I'm noticing that when I get to the point of trying to send my blob across the wire, I end up only sending something like this:

```
{"_data":{"blobId":"148cc94a-55a8-432d-871e-be32d045eaec","offset":0,"size":44684}}
```

This is as opposed to the actual bytes themselves.  The routines I'm using to send this data work fine on browser and electron clients...

**Comment by atrauzzi** [comment]
So, this doesn't resolve the issue, but I think I see what's going on here:

- I obtain a "react-native blob" using the "react-native fetch" against a URI pointing to the filesystem
- If I attempt to pass this "react native blob" to the standard XMLHttpRequest that's used by axios, things break
- If I attempt to pass the "react native blob" to the "react-native fetch" to issue a request to a server, my bytes make it over, presumably because there's non-standard logic anticipating the "react native blob"

Assuming this is all correct, the problem here is that the react native project has made some compatibility-breaking alterations to the Blob implementation.  Hopefully these can be resolved so that react native can retain the performance benefits of the Blob APIs as well as compatibility with the rest of the JavaScript ecosystem.

**Comment by kerkness** [comment]
👍

**Comment by atrauzzi** [comment]
Not stale.

**Comment by ajwhite** [comment]
There's a secret key -- `FileReader`.

`fetch` uses the `FileReader` to consume the contents of the blob, as to be compliant with `fetch`:
https://github.com/github/fetch/blob/37d10362687492868548c4d70c5c12e4a671771e/fetch.js#L181-L186

React Native has a `FileReader` implementation, which takes the "JS blob pointer" and resolves it natively
https://github.com/facebook/react-native/blob/b8d6ef372663fe6d467144abfc5d2c9352dc28d6/Libraries/Blob/FileReader.js#L112

The native `FileReaderModule` take the "blob pointer" and reads its `bytes`, then resolves them down as a string
https://github.com/facebook/react-native/blob/b8d6ef372663fe6d467144abfc5d2c9352dc28d6/ReactAndroid/src/main/java/com/facebook/react/modules/blob/FileReaderModule.java#L39-L41


---

My hunch is that `axios` may not use a `FileReader` to extract the blob?

**Comment by atrauzzi** [comment]
Not sure. But whatever is going on, it's breaking compatibility with standard JS network code.

**Comment by atrauzzi** [comment]
Leave it open.

**Comment by atrauzzi** [comment]
Leave it open.

**Comment by atrauzzi** [comment]
Leave it open.

**Comment by lukeramsden** [comment]
Over 2 years since this: https://github.com/expo/expo/issues/2402#issuecomment-443726662

Is this still the recommended way?

**Comment by danieloi** [comment]
Odd that this is still a thing in 2021...

**Comment by atrauzzi** [comment]
I do too but they need to up their game.

**Comment by aliraza-noon** [comment]
When is this going to fixed for god sake?

**Comment by JustinRohweller** [comment]
> Over 2 years since this: [expo/expo#2402 (comment)](https://github.com/expo/expo/issues/2402#issuecomment-443726662)
> 
> Is this still the recommended way?

For me that solution causes a crash on the second image upload.
This one worked better:
https://github.com/expo/firebase-storage-upload-example/issues/15#issuecomment-442142654
