### ISSUE TITLE
Auto correction doesn't call onChangeText

### ISSUE THREAD

**Issue by yoman07** [facebook/react-native#22691]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
      Memory: 60.66 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.3 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.1.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: ^3.3.12 => 3.4.5 
      @types/react: ^16.0.33 => 16.3.14 
      @types/react-native: ^0.51.8 => 0.51.10 
      react: 16.6.1 => 16.6.1 
      react-native: 0.57.7 => 0.57.5 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-create-library: 3.1.2
      react-native-gesture-handler: 1.0.10
      react-native-git-upgrade: 0.2.7

```
## Description
Autocorrection for iOS doesn't call onChangeText for TextInput.

## Reproducible Demo

If I select text from autocorrection onChangeText doesn't work. 

Example: 
If I click "armed"  onChangeText won't be called.

![simulator screen shot - iphone xs max - 2018-12-18 at 16 20 59](https://user-images.githubusercontent.com/1101367/50163556-fa7df780-02e0-11e9-9858-714656a6bfdd.png)

**Comment by imnapo** [comment]
Same issue here. it only fires onChangeText() function when it automatically adds an extra space after autocorrection.
