### ISSUE TITLE
ScrollView.scrollTo not checking ScrollView dimensions

### ISSUE THREAD

**Issue by indapublic** [facebook/react-native#22701]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz
      Memory: 164.89 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.13.0 - ~/.nvm/versions/node/v8.13.0/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.13.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.2, 25.0.0, 25.0.2, 25.0.3, 27.0.3, 28.0.3
        System Images: android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.1 => 16.6.1
      react-native: 0.57.5 => 0.57.5
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

## Description
Scroll is working well in sandbox https://codesandbox.io/s/1q1lq1407

![image 2018-12-19 15 10 00](https://user-images.githubusercontent.com/856260/50200225-acc8c400-03a0-11e9-9819-afde6f99d094.jpg)
![image 2018-12-19 15 10 03](https://user-images.githubusercontent.com/856260/50200228-adf9f100-03a0-11e9-9006-265cc501640e.jpg)

But does not work in React Native. Seems like scroll does not check ScrollView dimensions

![image 2018-12-19 15 12 04](https://user-images.githubusercontent.com/856260/50200232-b4886880-03a0-11e9-8330-e1ab237a80a5.jpg)
![image 2018-12-19 15 12 02](https://user-images.githubusercontent.com/856260/50200233-b4886880-03a0-11e9-9539-bcf933b02564.jpg)

## Reproducible Demo
Working example (probably, related to react-native-web?) https://codesandbox.io/s/1q1lq1407
Repository with reproducible example: https://github.com/indapublic/scrolltest

**Comment by kelset** [comment]
👋 there!

So, I just tested your repro (thanks for submitting btw!) and on a fresh 0.59 project the scroll to button works are expected.

My understanding is that your code wants to have the item to be in the center of the screen, but you are not considering the screen dimensions when you fire the scrollTo method.

So if you change your code to 

```
  handleScrollToCenter = () => {
    if (this.containerRef && this.activeRef) {
      const { height } = Dimensions.get('window'); // THIS LINE
      const UIManager = NativeModules.UIManager;
      UIManager.measure(
        findNodeHandle(this.activeRef),
        (activeX, activeY, activeW, activeH) => {
          this.containerRef.scrollTo({
            x: 0,
            y: activeY - height / 2, // THIS LINE
            animated: true
          });
        }
      );
    }
  };
```

You should be able to have the desired effect (just tested locally).
<img width="360" alt="Screenshot 2019-03-19 at 12 14 23" src="https://user-images.githubusercontent.com/16104054/54605249-b8c82e80-4a40-11e9-92ff-9f3e15a9df1e.png">

**Comment by indapublic** [comment]
If you try to scroll by hand - scroll view is respecting dimensions (I'm sorry, English is not my native language, so probably I can't explain it). You cannot scroll view like on screen, 20th row always . should be on bottom. But `scrollTo` scrolling to center (it's not "human" behaviour)
