### ISSUE TITLE
[CLI] Publish library via NPM needs change in Header Search Paths

### ISSUE THREAD

**Issue by Purii** [facebook/react-native#2271]
If you create a library with `react-native new-library [...]` and publish it via NPM you could get an error, like `RCTViewManager.h file not found` after installing via `npm install`. This error just occurs, if you put your files in an additional subfolder, like `/lib`for example:

```
index.js
lib/[filename].xcodeproj
lib/[filename].h
...
```

To solve the error you need to add the Header Search Path `$(SRCROOT)/../../react-native/React` to the library.

I don't know if this is path should get added always automatically, since this filestructure is pretty common, or just mentioned in the docs.

**Comment by brentvatne** [comment]
Pull request welcome for this! The team at Facebook won't be working on it as they don't use this functionality internally

**Comment by Purii** [comment]
I will do this :+1:

**Comment by Purii** [comment]
I would suggest, that this is issue is more related to certain libraries than to react-native itself.

**Comment by joshuapinter** [comment]
Did anyone actually get around to do doing a PR for this?

**Comment by Purii** [comment]
@joshuapinter I pulled back [my PR #2315](https://github.com/facebook/react-native/pull/2315) for the reason I wrote above.

> this is issue is more related to certain libraries than to react-native

Adding the headers search paths to support a library structure like _/lib/_ wouldn't solve issues with a structure like _/lib/src/_ and so on.
I am of the opinion, that this depends on the author of every lib. Maybe a mention in the docs?

**Comment by joshuapinter** [comment]
@Purii I wouldn't disagree that the Headers Search Path causes every newcomer confusion. I think a blurb in the docs is warranted. I'll toss it on my list and see if I can cobble something that hints people in the right direction...
