### ISSUE TITLE
react-navigation error "invariant violation: invariant violation: scrollview child layout (["alignItems","justifyContent"]) must be applied through the contentContainerStyle prop"

### ISSUE THREAD

**Issue by Nermin-K** [facebook/react-native#22734]
I'm trying to use react-navigation but I get this error "invariant violation: invariant violation: scrollview child layout (["alignItems","justifyContent"]) must be applied through the contentContainerStyle prop"

![screenshot_2018-12-20-13-11-24-126_com project](https://user-images.githubusercontent.com/30387225/50281950-d98ce200-0459-11e9-926f-b527a8754240.png)

I googled for solutions but all issues aren't related to react-navigation at all and I don't use anything else yet. I don't even understand the error.!

- "react-native": "0.57.8"

- "react-navigation": "^3.0.9"

- "react-native-gesture-handler": "^1.0.12"

- windows 10

- android

- redmi note 4 - android version 7.0

here are my codes

> index.js

`
import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';
AppRegistry.registerComponent(appName, () => App);
`
> App.js

`import React, {Component} from 'react';
import {Platform, StyleSheet, Text, View} from 'react-native';
import {createAppContainer, createStackNavigator} from 'react-navigation';
import PostsScreen from './components/Posts';
import ToolsScreen from './components/Posts';
import FavouriteScreen from './components/Favourite';
const AppNavigator = createStackNavigator({
  Posts: { screen: PostsScreen },
  Tools: { screen: ToolsScreen },
  Favourite: { screen: FavouriteScreen }
}, {
  initialRouteName: 'Posts',  
})
const App = createAppContainer(AppNavigator);
export default App;`

> Posts.js

`import React, {Component} from 'react';
import {Platform, StyleSheet, Text, View} from 'react-native';
import { Container, Header, Content, Button } from 'native-base';
class PostsScreen extends Component {
  render() {
    const { navigate } = this.props.navigation;
    return (
      <Container>
        <Content style={styles.content}>Posts Screen</Content>
        <Button onPress= { ()=> navigate('Tools')} title="Tools"></Button>
      </Container>
    );
  }
}
export default PostsScreen;
const styles = StyleSheet.create({
  content: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
});`

> Tools.js

`import React, {Component} from 'react';
import {Platform, StyleSheet, Text, View} from 'react-native';
import { Container, Header, Content } from 'native-base';
class ToolsScreen extends Component {
  render() {
    return (
      <Container>
        <Content style={styles.content}>Tools Screen</Content>
      </Container>
    );
  }
}
export default ToolsScreen;
const styles = StyleSheet.create({
  content: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
});`

**Comment by strjoshi** [comment]
Please provide styles to the **contentContainerStyle**  instead of providing to ScrollView.

**Comment by Nermin-K** [comment]
@strjoshi sorry, but I can't understand what do you mean. can you explain it more?

**Comment by Nermin-K** [comment]
@strjoshi thanks! it works. but I still don't understand why, could you please tell me the reason?!

**Comment by stevematdavies** [comment]
> Please provide styles to the **contentContainerStyle** instead of providing to ScrollView.

A distinct lack of clear examples in the documentation, makes this statement confusing to me, please explain
