### ISSUE TITLE
XCODE 10 build issues with RCTFBSDK

### ISSUE THREAD

**Issue by RohanChawla01** [facebook/react-native#22732]
## Environment
  OS: macOS High Sierra 10.13.6
  Node: 8.11.3
  Yarn: 1.9.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 10.1 Build version 10B61
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  react: 16.4.1 => 16.4.1
  react-native: 0.54.4 => 0.54.4

## Description
I am building my app using Xcode 10. I am facing this issue with RCTFBSDK (FBSDKShareKit.h file not found) on Xcode 10 while building the app for generic Device or any particular physical device. I am able to build the app using XCODE 9. 

## Reproducible Demo
Here's the screenshot of the issue.
![image](https://user-images.githubusercontent.com/29834419/50279661-5c209c00-0470-11e9-96d8-aad904e9156c.png)

**Comment by hramos** [comment]
0.54 was released quite some time before Xcode 10 was announced. There's been a lot of work on getting Xcode 10 well supported in the past year, can you try a more recent version, ideally 0.57 or newer?

**Comment by hramos** [comment]
This also seems to be specific to [react-native-fbsdk](https://github.com/facebook/react-native-fbsdk).

**Comment by RohanChawla01** [comment]
@hramos Thanks for the reply, i have upgraded to react native version 0.57.5, but this issue persists.
The same code works well with Xcode 9 but it is causing this problem on Xcode 10. react-native-fbsdk specific issue should also have caused problems of previous Xcode but this error occurs while building with Xcode 10 only.
