### ISSUE TITLE
[TextInput] Changing TextInput.editable to false does not blur the input.

### ISSUE THREAD

**Issue by bobspace** [facebook/react-native#2274]
Seems like it should, right? I thought it wasn't getting set. It wasn't until I blurred the input explicitly that I verified that it couldn't be selected again.

**Comment by brentvatne** [comment]
@bobspace - could you try to put together a pull request to fix this? :smile:

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/textinput-changing-textinputeditable-to-false-does-not-blur-the-input
