### ISSUE TITLE
[Nested Text Android] onPress hitbox has an incorrect size.

### ISSUE THREAD

**Issue by bobsmits** [facebook/react-native#22747]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Run `react-native info` in your terminal and paste its contents here.
```
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 55.39 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.2 - /usr/local/bin/node
      Yarn: 1.3.2 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 25, 26, 27
        Build Tools: 23.0.1, 26.0.3, 27.0.3, 28.0.3
        System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.57.8 => 0.57.8 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
```

## Description
Nested Texts with an onPress do not allow you te press on the whole word. Texts nested in a View work correctly. This only happens on Android IOS seems fine.

![large gif 424x860](https://user-images.githubusercontent.com/20045348/50338055-68116a00-0513-11e9-86ec-886e20a71d79.gif)

## Reproducible Demo
Init a new react native project. Change default App component to:

```
 <View style={styles.container}>
    <Text>
        <Text onPress={ () => {console.warn('Hello!')} } style={styles.welcome}>facebook.com</Text>
    </Text>
 </View>
```

The last letter from facebook.com will not respond to the onPress. 

A Text nested directly in a View it works as expected:
```
 <View style={styles.container}>
     <Text onPress={ () => {console.warn('Hello!')} } style={styles.welcome}>facebook.com</Text>
 </View>
```

**Comment by cpojer** [comment]
You are right, this seems like this is a real issue but unfortunately it's unlikely anyone will be able to spend time on this anytime soon. Do you wanna send a PR to fix this?

**Comment by kevinavery** [comment]
@bobsmits I found that this is an issue when `Text` has padding in the style. Even if the padding is assigned to the top level `Text`, the hitbox for child `Texts` seems to break.

**Comment by caioedut** [comment]
Please pay some attention to this.

**Comment by ovy9086** [comment]
same issue here...

**Comment by ilogico** [comment]
Having a similar issue. It happens both on Android and iOS.
The hit box seems to be wrongly calculated, being offset to the left.
Text aligns and monospace fonts seem to have no effect on it. The amount of text and surrounding text seems to influence the offset.
I found no workaround for it.

**Comment by ilogico** [comment]
The issue still exists.

**Comment by ilogico** [comment]
It's not fixed.

**Comment by jsamr** [comment]
Stale bot, leave the issue open.

**Comment by AlenToma** [comment]
I hade the same issue. The fix I found is wrapping the parent with `SafeAreaView` from `react-native-safe-area-context` and it should work.
