### ISSUE TITLE
Cannot find module 'metro/src/DeltaBundler/Worker'

### ISSUE THREAD

**Issue by aafarian** [facebook/react-native#22743]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
      Memory: 47.95 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.9.4 - ~/.nvm/versions/node/v8.9.4/bin/node
      Yarn: 1.12.3 - ~/.nvm/versions/node/v8.9.4/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.9.4/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
    IDEs:
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: ^0.57.8 => 0.57.8
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description
After updating to react-native 0.57.8, I can't bundle my application. Has anyone else had this issue? I've tried rebuilding after deleting the bundler cache, removing node_modules and package-lock but nothing seems to work.

Full error message, when I run `react-native start --reset-cache`: 

warning: the transform cache was reset.
Loading dependency graph, done.
Loading dependency graph...(node:73122) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Cannot find module 'metro/src/DeltaBundler/Worker'
(node:73122) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by rickhanlonii** [comment]
Looks like a metro issue - there's an issue with a workaround [here](https://github.com/facebook/metro/issues/293#issuecomment-431849905)
