### ISSUE TITLE
Getting error when runs the react native project on IOS simulator

### ISSUE THREAD

**Issue by kanaReact** [facebook/react-native#22745]
Unhandled JS Exception: "size" is read-only
2018-12-21 12:24:54.960 [error][tid:com.facebook.react.JavaScript] Module AppRegistry is not a registered callable module (calling runApplication)
2018-12-21 12:24:54.961669+0530 freebs[25289:376180] Module AppRegistry is not a registered callable module (calling runApplication)

## Environment
React Native Environment Info:
    System:
      OS: macOS Sierra 10.12.6
      CPU: (2) x64 Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz
      Memory: 57.67 MB / 6.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.2 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 11.2, macOS 10.13, tvOS 11.2, watchOS 4.2
    IDEs:
      Xcode: 9.2/9C40b - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728 
      react-native: ^0.57.8 => 0.57.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native: 0.57.8

## Description
When running react-native project using react-native run-ios splash screen opens and then displays above error in log and screen in iphone simulator.

**Comment by kanaReact** [comment]
@rickhanlonii , It has problem with my node_modules folder. I have just updated the node modules and error is solved.

**Comment by rickhanlonii** [comment]
Cool, thanks!
