### ISSUE TITLE
TouchableHighlight changing opacity breaks inner View's style

### ISSUE THREAD

**Issue by kachnitel** [facebook/react-native#22751]
There's a warning thrown when I press a `TouchableHighlight` component enclosing a `View` that has its own style assigned by a variable. Here's a simple example:

      <TouchableHighlight onPress={() => this.props.navigation.push(
          'Detail',
          item
        )}>
          <View
            style={index % 2 == 0 ? styles.listItemWhite : styles.listItemBlack}
          />
        </TouchableHighlight>

With this code if I press TouchableHighlight, instead of applying opacity to the selected style, it appears to create an array throwing this warning:

    Warning: Failed prop type: Invalid props.style key `0` supplied to `ForwardRef`.
    Bad object: {
      "0": {
        "backgroundColor": "#fff"
      },
      "1": {
        "opacity": 0.85
      },
      "fontSize": 20.666666666666668
    }
    Valid keys: [
      "display",
      "width",
    ...
      "textTransform",
      "writingDirection"
    ]

[Here's an issue](https://github.com/kachnitel/RideTime/issues/13) in my project if it's easier to reproduce that way. I figured out how to work around it by adding another `View` between the `TouchableHighlight` and `View` with the affected style. I'm still very new to React Native and front end development but this looks to me like a bug in `TouchableHighlight`?

My react env: 
```
react-native info

  React Native Environment Info:
    System:
      OS: Linux 4.19 openSUSE Tumbleweed 20181214
      CPU: x64 Intel(R) Core(TM) i7-3610QM CPU @ 2.30GHz
      Memory: 123.01 MB / 7.68 GB
      Shell: 4.4.23 - /bin/bash
    Binaries:
      Node: 10.13.0 - /usr/bin/node
      npm: 6.4.1 - /usr/bin/npm
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

**Comment by cpojer** [comment]
I think your question is best suited on StackOverflow. If it indeed turns out to be an issue with React Native, please feel free to send us a PR with a fix.
