### ISSUE TITLE
[Cryptic Error Message] Must inject a reconcile transaction class and batching strategy?

### ISSUE THREAD

**Issue by aleclarson** [facebook/react-native#2275]
```
Error: Invariant Violation: ReactUpdates: must inject a reconcile transaction class and batching strategy
```

It only throws when not debugging in Chrome.

What can I do to fix this?

**Comment by brentvatne** [comment]
@aleclarson - check your debug console in Chrome, are you getting any errors or warnings there?

**Comment by aleclarson** [comment]
Nothing in there.

When I place a breakpoint in the Objective-C code, the call stack begins at `[RCTContextExecutor executeJSCall:method:arguments:context:callback]` throwing an error during a call to `[BatchedBridge processBatch]`. That doesn't seem useful at all. Is there anyway else to debug these kinds of errors?

**Comment by aleclarson** [comment]
Figured everything out! An error was being thrown by a dependency. Since I was importing the dependency before `require('react-native')`, the `ReactNativeDefaultInjection` was not yet imported.

This caused the error above. It also caused the error to be **silent**, because `console.reportErrorsAsExceptions` was not yet defined as `true` and the error that was thrown by my dependency only occurred when not using Chrome Dev Tools (because `window` exists when using Chrome Dev Tools).

So... if it wasn't obvious before, **NEVER** put anything before the coveted `require('react-native')`. :smile: 

Sorry for the false alarm!

**Comment by chetstone** [comment]
I found I was getting this error because I had moved an `import AuthStore from './src/stores/AuthStore'` from a subcomponent into `index.ios.js`. Removing that line got rid of the error. No idea why. It was *after* `var React = require('react-native');`

**Comment by AlastairTaft** [comment]
I doubt anyone else will get it for the reason I was. But back in the old 0.15.x versions I was using `import { render } from 'react/lib/ReactMount'` to keep my bundle sizes smaller.  In the 15.x.x code however this isn't needed so I had to change my code to `import { render } from 'react-dom'`

**Comment by piuccio** [comment]
@AlastairTaft I just got it for your same reason. Did you find another way to keep the bundle size small?

**Comment by AlastairTaft** [comment]
@piuccio Afraid not, but I think it's okay to use the normal syntax of `import React from 'react'` and `import { render } from 'react-dom'`. If I remember correctly, before, doing one of the other included everything, but I think now they only include the chunks of code that are relative to what you import.
