### ISSUE TITLE
[Docs] Clearer documentation on how to animate string properties

### ISSUE THREAD

**Issue by JedWatson** [facebook/react-native#2276]
It's possible to animate string values (e.g. `90deg` for `rotate`, `rgb(0,0,0)` for `backgroundColor`) using the `interpolate` method, e.g

```
transform: [
	{ rotate: this.state.rotationValue.interpolate({
		inputRange: [0, 360],
		outputRange: ['0deg', '360deg']
	}) }
]
```

However for a beginner, this isn't really obvious from the Animation guide.

Even though there's a comment referring to the possibility in the examples, I think it would be worth including a paragraph specifically stating that it can be done, and how - from the guide, it looks like you can only animate number values.

**Comment by JedWatson** [comment]
cc @vjeux

**Comment by vjeux** [comment]
cc @brentvatne since you wrote the guide, I think that it would be a great addition

**Comment by browniefed** [comment]
Seems like this can be easily added to the Animated docs now that they are documented https://facebook.github.io/react-native/docs/animated.html#content

**Comment by mkonicek** [comment]
Sounds good, @JedWatson mind sending a PR?

**Comment by lacker** [comment]
Since the docs are now improved on this, I'm going to close this issue. Feel free to reopen one (or ideally just a PR) if there are more improvements we should make here.
