### ISSUE TITLE
Add CI file in template

### ISSUE THREAD

**Issue by gengjiawen** [facebook/react-native#22779]
Now we have https://github.com/react-native-community/ci-sample.

I am thinking add ci file default or by some command.

With ci we can handle bug report more easily.

**Comment by gengjiawen** [comment]
Added in https://github.com/facebook/react-native/pull/23078.
Removed in https://github.com/facebook/react-native/pull/23107.

My thought is that we should more strict about bug report. Through this we can have more communicate efficiency. 

cc @kelset @hramos @cpojer

**Comment by cpojer** [comment]
Oh yeah I didn't realize. @hramos I thought @gengjiawen's addition was good but maybe I missed something and there is a reason we don't want to recommend it to users who report issues?

**Comment by hramos** [comment]
Can you clarify what you mean by adding CI to your project, and how this would improve issues?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gengjiawen** [comment]
> adding CI to your project

When user report bug j, build failure or other issue, they need to provide an repro with ci files in it. so we can see the build log and use artifact. There are a sample https://github.com/react-native-community/ci-sample. The sample contains many ci sample user can easily achieve.

> how this would improve issues?

By make this more strict, I want to improve the communicate efficiency.

**Comment by cpojer** [comment]
We are already asking people for a lot when creating an issue so I think it's best not to ask them to do more. Thanks for your work on this, and the ci-sample is definitely going to be useful to people who work on various React Native things.
