### ISSUE TITLE
Attempted to invoke `3` (method ID) on `UIManager` (NativeModule name) with an invalid bridge.

### ISSUE THREAD

**Issue by zwb474287221** [facebook/react-native#22773]
有很多警告，然后不能坐任何事，能告诉我为什么会有这警告吗
![2018-12-24 3 33 04](https://user-images.githubusercontent.com/32866552/50393473-66ed7080-0791-11e9-88bf-772a03e02429.png)

**Comment by luutruong** [comment]
I have same issues.

**Comment by nihp** [comment]
I am also facing same issues here

**Comment by mja-maia** [comment]
same issue here

**Comment by wanxsb** [comment]
same issue

**Comment by morizotter** [comment]
same here..
