### ISSUE TITLE
[Animated] Allow animation of string values without `interpolate`

### ISSUE THREAD

**Issue by JedWatson** [facebook/react-native#2277]
It seems (without knowing how the implementation works) that it would be possible to expose a simpler API for animating string values without requiring `interpolate`.

For example, this:

```
getInitialState () {
    return {
        rotationValue: new Animated.Value(0)
    }
},
runAnimation () {
    Animated.spring(
        this.state.rotationValue,
        {
            toValue: 180,
            tension: 10,
            friction: 5
        }
    ).start();
},
render () {
    return <Animated.View
        style={{
            transform: [
                { rotate: this.state.rotationValue.interpolate({
                    inputRange: [0, 360],
                    outputRange: ['0deg', '360deg']
                }) }
            ]
        }}>;
}
```

would be more intuitive like this:

```
getInitialState () {
    return {
        rotationValue: new Animated.Value('0deg')
    }
},
runAnimation () {
    Animated.spring(
        this.state.rotationValue,
        {
            toValue: '180deg',
            tension: 10,
            friction: 5
        }
    ).start();
},
render () {
    return <Animated.View
        style={{
            transform: [
                { rotate: this.state.rotationValue }
            ]
        }}>;
}
```

Interpolation could still be used as in the first example if you wanted to animate a combination of strings and numbers (e.g update size and rotation based on the same value).

**Comment by JedWatson** [comment]
cc @vjeux

**Comment by vjeux** [comment]
Very good suggestion! @sahrens, I think we can make it work right?

**Comment by chirag04** [comment]
+100. Much cleaner.

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/animated-allow-animation-of-string-values-without-interpolate
