### ISSUE TITLE
Error: Requiring unknown module "546"

### ISSUE THREAD

**Issue by MuhammadRamadiansyah** [facebook/react-native#22787]
[y] Review the documentation: https://facebook.github.io/react-native
[y] Search for existing issues: https://github.com/facebook/react-native/issues
[y] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
`React Native Environment Info:

    System:
      OS: macOS 10.14
      CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 45.21 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.3.0 - ~/.nvm/versions/node/v10.3.0/bin/node
      Yarn: 1.5.1 - /usr/local/bin/yarn
      npm: 6.1.0 - ~/.nvm/versions/node/v10.3.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 24, 25, 26, 27
        Build Tools: 23.0.1, 25.0.0, 25.0.2, 26.0.1, 26.0.3, 27.0.3
        System Images: android-23 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: 0.57.8 => 0.57.8`

## Description
I have some problem when using latest version of react-native with react-navigation, it looks like due to unsupported packages or missing depedencies between latest version of react-native and react-navigation. 

When i install react-navigation and then restart the bundler, it said `Error: Requiring unknown module "546". If you are sure the module is there, try restarting the packager or running "npm install".` on the emulator and then i try to build again but failed.

In the metro bundler terminal said `Error: ENOENT: no such file or directory, open '/my-project-root-folder/node_modules/create-react-class/node_modules/fbjs/lib/emptyObject.js'`

And here is my projects depedencies `"dependencies": {
    "react": "16.6.3",
    "react-native": "0.57.8",
    "react-navigation": "^3.0.9"
  }`

Does anyone also face up the similar problem and has already come up with solution ?

**Comment by zack12027** [comment]
closed with no answers?
