### ISSUE TITLE
Your browser does not have secure random generator. If you don’t need unpredictable IDs, you can use nanoid/non-secure.

### ISSUE THREAD

**Issue by supzeroIs** [facebook/react-native#22780]
- [y ] Review the documentation: https://facebook.github.io/react-native
  - [y ] Search for existing issues: https://github.com/facebook/react-native/issues
  - [y ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
`  
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
      Memory: 685.06 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.12.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.0, 26.0.1, 27.0.3, 28.0.3
        System Images: android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.6.1 => 16.7.0
      react-native: ^0.57.7 => 0.57.8
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
`

## Description
I get `Your browser does not have secure random generator. If you don’t need unpredictable IDs, you can use nanoid/non-secure.`
after upgrading to react version 
[Imgur](https://i.imgur.com/KhVPbKo.png)

## Reproducible Demo

upgrade react-native version from 0.55 to 0.57

**Comment by liorbraginsky92** [comment]
Same issue while upgrading

**Comment by wagng** [comment]
I am facing this issue as well.

React & React Native versions.
```
"react": "16.6.3",
"react-native": "0.57.8"
```

But it disappears once I disable redux debugger wrapper used by `remote-redux-devtools`.
You can check the details on my react-native-starter-kit repo.
https://github.com/wagng/react-native-redux-starter-kit/blob/fd36397e641e116742fc512b982dfa28a5c5018b/src/redux/store/store.js#L25
I've been using `remote-redux-devtools` for all of my react-native projects, but I've never faced this issue.
Would be great to get correct answer from react.
Thanks!

**Comment by niteshpal91** [comment]
Facing the same issue, working when i start the debugger.
Please help!

Thanks

**Comment by daogurtsov** [comment]
Facing same issue ios/android/emulator everywhere. Can it be related to chrome recent update?

**Comment by niteshpal91** [comment]
Does anyone has any hack for now for removing this error?

**Comment by emjayschoen** [comment]
Looks like it was fixed on remote-redux-devtools' end here. Upgrading to the latest release fixed it for me!  https://github.com/zalmoxisus/remote-redux-devtools/issues/130#issuecomment-450199730

**Comment by rickhanlonii** [comment]
Thanks for filing @supzeroIs!

Looks like this was an issue in remote-redux-devtools and fixed (thanks @emjayschoen)

Please update to the latest remote-redux-devtools release and confirm. If this is still an issue you may want to file a bug there 👍
