### ISSUE TITLE
Load the custom font in whole project

### ISSUE THREAD

**Issue by renishdeveloper** [facebook/react-native#22784]
>react-native link
rnpm-install info Linking assets to ios project
rnpm-install ERR! Something went wrong while linking. Error: Cannot read property 'pbxprojPath' of null

Cannot read property 'pbxprojPath' of null

TypeError: Cannot read property 'pbxprojPath' of null
    at Object.linkAssetsIOS [as copyAssets] node_modules\react-native\local-cli\lin
k\ios\copyAssets.js:24:41)
    at \node_modules\react-native\local-cli\link\link.js:104:12
    at Array.forEach (<anonymous>)
    at linkAssets (\node_modules\react-native\local-cli\link\link.js:94:28)
    at \node_modules\react-native\local-cli\link\link.js:171:30
    at <anonymous>

**Comment by AlexMachin1997** [comment]
I wish companies would stop automatically closing issues like this just because it doesn't meet the template requirements.

I'm facing this issue now and I'm not sure what to do as well you've closed it and no is likely to answer.
