### ISSUE TITLE
Error when require('react-native-xmpp') on android project

### ISSUE THREAD

**Issue by hashanchamikara** [facebook/react-native#22798]
## Environment
  React Native Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
      CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
      Memory: 700.26 MB / 15.56 GB
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 8.10.0 - /usr/bin/node
      npm: 3.5.2 - /usr/bin/npm
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: 0.57.1 => 0.57.1 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-xmpp: 1.0.3

## Description
 tried to install XMPP module in react native project [react-native-xmpp](https://www.npmjs.com/package/react-native-xmpp)

but after I use

`var XMPP = require('react-native-xmpp');`
it was return error

```
Cannot read property 'PLAIN' of undefined

Module AppRegistry is not a registered callable module (calling runApplication)
```

I didn't find where is this error occur please help

## Reproducible Demo
here is [stackoverflow](https://stackoverflow.com/questions/53925345/error-when-requirereact-native-xmpp-on-android-project) question

**Comment by rizwanatta** [comment]
after installing it! you should see if that REACT_NATIVE link command worked correctly and if not then you should do the process manually! by setting up the android MyApplication.java file

**Comment by hashanchamikara** [comment]
yes it is working correctly, 

i see there have some codes in settings.gradle, app/build.gradle and MainApplication.java files

![screenshot from 2018-12-26 15-43-48](https://user-images.githubusercontent.com/24802433/50442493-2fafc880-0925-11e9-8461-2e1c61a8936a.png)
![screenshot from 2018-12-26 15-43-34](https://user-images.githubusercontent.com/24802433/50442499-376f6d00-0925-11e9-9dd5-de175128b0af.png)
![screenshot from 2018-12-26 15-42-21](https://user-images.githubusercontent.com/24802433/50442507-3cccb780-0925-11e9-95a1-d3a978bf2f48.png)

**Comment by rizwanatta** [comment]
you have the implementation of xmpp in your build.gradle dependencies! 

> **redundant**

means its written twice first remove that

and then go to

cd android

using android gradlew clean it!

**cd ./gradlew && clean**

after that run the react-native run-android

it should get you going with that error! now next depends upon how you are configuring XMPP

**Comment by hashanchamikara** [comment]
Cannot read property 'PLAIN' of undefined

Module AppRegistry is not a registered callable module (calling runApplication)

it is same output bro

**Comment by rizwanatta** [comment]
> Cannot read property 'PLAIN' of undefined
> 
> Module AppRegistry is not a registered callable module (calling runApplication)
> 
> it is same output bro

first remove the extra line! and clean the gradle cache! and then re start the whole pacakager and project and show what comes next!

**Comment by hashanchamikara** [comment]
same output bro
