### ISSUE TITLE
Need to help with React-Native v0.56 crashes.

### ISSUE THREAD

**Issue by mohammad-goldast** [facebook/react-native#22795]
### 💯  I need to help for my project, so let me know your knowledge 
I've started a project for my new business with `React-Native`  **v0.51.0** and `React-Native-Navigation (wix)` **v1.x.x** .
After a while we need to use `React-Native-Firebase`  **v5.x**, and this package required `React-Native` **v56.0**. 
We upgraded `React-Native` **v0.51** to **v0.56**. 
### 🔢  The application crashes started from here :
I had a lot of **crash (in android)** logs from my `React-Native-Sentry` crashlytics with the below messages:
 
**1.** **JSApplicationIllegalArgumentException**
`com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter in updateShadowNodeProp`
*`Error while updating property 'width' in shadow node of type: RCTImageView`*

**2.** **JSApplicationIllegalArgumentException**
`com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter in updateShadowNodeProp`
*`Error while updating property 'stroke' of a view managed by: RNSVGPath`*

**3.** **JSApplicationIllegalArgumentException**
`com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter in updateShadowNodeProp`
*`Error while updating property 'matrix' of a view managed by: RNSVGGroup`*

...etc .

### 👎 Sad part of my story :-( 

Now, unfortunately users of my application are so dissatisfied, i searched about these logs and i didn't get any result for resolve the application **crashes**, these crashes happens in **random places** and **random time** :( .

BTW, i don't know, What i should do ? change `React-Native` version ? 
If i should to change `React-Native` version, which version of `React-Native` is more stable between **v0.57.0** to **v0.57.8** ? 

Also im using these **packages**: 
```JS
"react-native-android-sms-listener": "^0.5.0",
"react-native-camera": "^1.6.4",
"react-native-contacts": "^2.2.5",
"react-native-document-picker": "^2.2.0",
"react-native-extended-stylesheet": "^0.11.1",
"react-native-fast-image": "^5.1.1",
"react-native-firebase": "^5.1.1",
"react-native-fs": "^2.13.3",
"react-native-image-crop-picker": "^0.21.3",
"react-native-navigation": "1.x.x",
"react-native-permissions": "^1.1.1",
"react-native-qrcode": "^0.2.7",
"react-native-qrcode-scanner": "^1.1.0",
"react-native-sentry": "^0.40.2",
"react-native-shared-preferences": "^1.0.0",
"react-native-sms-android": "^0.4.1",
"react-native-star-rating": "^1.1.0",
"react-native-svg": "^8.0.10",
"react-native-timer-countdown": "^2.0.3",
"react-native-uuid": "^1.4.9",
"react-native-vector-icons": "^6.1.0",
"react-native-version-number": "^0.3.5",
"react-native-view-shot": "^2.5.0",
"react-redux": "^6.0.0",
"realm": "^2.21.1",
"redux": "^4.0.1",
"redux-thunk": "^2.3.0",
"rn-fetch-blob": "^0.10.13"
```

**Comment by kimemin** [comment]
I have a similar problem in android. 
`updateShadowNodeProp` makes errors. (not in ios)
