### ISSUE TITLE
PushNotificationIOS.abandonPermissions() doesn't work

### ISSUE THREAD

**Issue by eyaleizenberg** [facebook/react-native#2280]
After successfully getting the permissions for notifications, I've tried revoking them but it's not working. The function simply returns undefined and when I run:
```javascript
PushNotificationIOS.checkPermissions((permissions) => {
    console.log(permissions);
});
```

I still have permissions for badge sound and alert.

Running React Native 0.8 on iPad Air, iOS 8

**Comment by DannyvanderJagt** [comment]
`PushNotificationIOS.abandonPermissions()` is not meant to change permissions.

React native is using `unregisterForRemoteNotifications` in IOS. The method will send an unregister event to Apple Push Notification server to unsubscribe you. But it will not change any settings on you local device. This method is only meant for push notifications and not meant for notifications in general.

**Clear Permissions**
I have searched on the internet and in the docs but currently there is no way to accomplish this with code. The only way to change the permissions is to use the settings app manually.  

I you want to clear the notification permissions of your app Apple has a trick for that.

> #### Resetting the Push Notifications Permissions Alert on iOS
The first time a push-enabled app registers for push notifications, iOS asks the user if they wish to receive notifications for that app. Once the user has responded to this alert it is not presented again unless the device is restored or the app has been uninstalled for at least a day.

>If you want to simulate a first-time run of your app, you can leave the app uninstalled for a day. You can achieve the latter without actually waiting a day by following these steps:

>Delete your app from the device.
Turn the device off completely and turn it back on.
Go to Settings > General > Date & Time and set the date ahead a day or more.
Turn the device off completely again and turn it back on.

Source: [Apple docs](https://developer.apple.com/library/ios/technotes/tn2265/_index.html)

**Local notifications**
There are some issues and PRs for local notifications. Maybe they can accomplish a good solution for this. (https://github.com/facebook/react-native/issues/2185 , https://github.com/facebook/react-native/pull/843)

**Comment by eyaleizenberg** [comment]
@DannyvanderJagt Thanks for the info, I will try that. I just hope the 'register' listener will catch it.... ;)

**Comment by herkyl** [comment]
@eyaleizenberg did you ever get it working, even if I turn notifications off in settings `requestPermissions` wont work anymore :/.

**Comment by dwilt** [comment]
I'm having trouble with this too
