### ISSUE TITLE
Popups Do Not Appear In React Native WebView 

### ISSUE THREAD

**Issue by Shivendra30** [facebook/react-native#22802]
I've seen multiple questions regarding this on StackOverflow but unfortunately, none of them have been solved.

In my case, I'm using PayuMoney inside a WebView to execute a transaction. Payumoney by default opens up a new window while processing a transaction which is not visible inside the react native's webview but is apparently visible in mobile browsers.

According to this answer - Enable Popups in React Native WebView, I added

```
// To enable these by default
WebSettings settings = webView.getSettings();
settings.setJavaScriptCanOpenWindowsAutomatically(true);
settings.setSupportMultipleWindows(true); 
```

And also this,

```
//To add these as valid props for the WebView Component
@ReactProp(name = "javaScriptCanOpenWindowsAutomatically")
  public void setJavaScriptCanOpenWindowsAutomatically(WebView view, boolean isCan) {
    view.getSettings().setJavaScriptCanOpenWindowsAutomatically(isCan);
  }

  @ReactProp(name = "supportMultipleWindows")
  public void setSupportMultipleWindows(WebView view, boolean supports) {
    view.getSettings().setSupportMultipleWindows(supports);
  } 
```

Additionally, I have also tried multiple npm packages which provide different implementations of WebView but nothing seems to work.

What is the best way to enable this feature?

**Comment by vnlebaoduy** [comment]
@Shivendra30 Where i can add them ?
