### ISSUE TITLE
"import call expects exactly one argument" after upgrade to 0.57.8 from 0.55, remote debugging leads to "import declarations may only appear at top level of module"

### ISSUE THREAD

**Issue by Li357** [facebook/react-native#22804]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
  React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: (8) x64 Intel(R) Core(TM) i7-4790S CPU @ 3.20GHz
      Memory: 155.81 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.1.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.7.0 => 16.7.0
      react-native: ^0.57.8 => 0.57.8

## Description
After doing `yarn upgrade react-native@latest` from 0.55.4 to 0.57.8, I'm experiencing the following issue:

![screen shot 2018-12-26 at 1 03 53 pm](https://user-images.githubusercontent.com/12980971/50454724-fbc9a880-090e-11e9-8af3-81d672cd2dd8.png)

When starting the bundler with `yarn start`. If I turn on remote debugging, I get:

![screen shot 2018-12-26 at 1 08 51 pm](https://user-images.githubusercontent.com/12980971/50454784-6844a780-090f-11e9-85e6-7f83eb297f8e.png)

**Comment by Li357** [comment]
I actually hit enter. Any way to remove the label?

**Comment by defrian** [comment]
facing the same issue with version 0.57.8

```
$ react-native info

React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
      Memory: 8.03 GB / 32.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.12.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: 0.57.8 => 0.57.8
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

**Comment by Li357** [comment]
@defrian I "fixed" the issue by slowly commenting out code. First I reinstalled my dependencies, then I commented out the line where I registered my app, aka `AppRegistry`. Then I slowly reintroduced my `App` component back. Don't exactly know why but after lots of reloading the error went away.
