### ISSUE TITLE
Text numberOfLines prop is not respected in Nested Text

### ISSUE THREAD

**Issue by mloureiro** [facebook/react-native#22811]
name: 🐛 Bug Report
about: Report a reproducible bug or regression in the core React Native library.
---

  - [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment

[skip envinfo]
This is reproducible in the [expo playground](https://snack.expo.io/H1IZHzGbN)

## Description

Property `numberOfLines` is not respected when used in a child Text component:

```html
<Text>
  <Text  numberOfLines={1}>{'sometext'.repeat(1000)}</Text>
</Tex>
```

In this https://github.com/facebook/react-native/issues/4733#issuecomment-271654057 @oureta mentions that this does not work, I don't understand if it is expected behavior, or a  🐛

According to [Text doc](https://facebook.github.io/react-native/docs/text#onlayout) the styling has some limitations with inheritance/nesting, although nothing is specified (AFAICT) about the other properties.

## Reproducible Demo

https://snack.expo.io/H1IZHzGbN

**Comment by bartolkaruza** [comment]
This will be difficult to implement on Android, as the nested text is represented by a single `TextView` on which the `maxLines` and `singleLine` props are set to implement `numberOfLines` at the native level. You can check out that code [here](https://github.com/facebook/react-native/issues/22440). The nested text is represented by a span which does not have those properties. I'm not sure how hard it would be to implement on iOS, but I imagine similar issues will be there.

This should probably be added to the [*known issues*](https://github.com/facebook/react-native-website/issues/564) section of the [Text](https://facebook.github.io/react-native/docs/text#onlayout) component doc. @mloureiro do you feel up to making a PR for that on https://github.com/facebook/react-native-website using the template from [here](https://github.com/facebook/react-native-website/issues/564)?

**Comment by mloureiro** [comment]
Will do.
