### ISSUE TITLE
Android crash with length=15; index=-6

### ISSUE THREAD

**Issue by luutruong** [facebook/react-native#22816]
I have faced this issues in android

## Environment
```
React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 33.66 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.10.0 - /usr/local/bin/node
      npm: 6.5.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 25, 26, 27
        Build Tools: 27.0.3, 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: 0.57.8 => 0.57.8
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-rename: 2.3.2
```

## Description
```
length=15; index=-6
getLineTop
    StaticLayout.java:1208
onMeasure
    TextView.java:8629
measure
    View.java:23169
updateLayout
    NativeViewHierarchyManager.java:176
execute
    UIViewOperationQueue.java:175
run
    UIViewOperationQueue.java:894
flushPendingBatches
    UIViewOperationQueue.java:1001
access$2400
    UIViewOperationQueue.java:46
doFrameGuarded
    UIViewOperationQueue.java:1061
doFrame
    GuardedFrameCallback.java:29
doFrame
    ReactChoreographer.java:134
doFrame
    ChoreographerCompat.java:105
run
    Choreographer.java:947
doCallbacks
    Choreographer.java:761
doFrame
    Choreographer.java:693
run
    Choreographer.java:935
handleCallback
    Handler.java:873
dispatchMessage
    Handler.java:99
loop
    Looper.java:193
main
    ActivityThread.java:6669
invoke
    Method.java
run
    RuntimeInit.java:493
main
    ZygoteInit.java:858
```

**Comment by noahtallen** [comment]
The error usually occurs when an array index is out of bounds - in your case, the array length is 15, but it is trying to access index -6. Is there anything in your code which would point to that being an issue? The crash logs indicate it has to do with the `Text` component.

**Comment by luutruong** [comment]
Thank you @noahtallen for explain. After debug my code and I have found the issues.

```
<Text numberOfLines ={-1}>A long text here....</Text>
```
That crash on android but IOS did not.

Does it is bug?

**Comment by noahtallen** [comment]
Why would you set it to -1? You can’t have less than 0 things displayed at once :p

**Comment by luutruong** [comment]
My idea is want to render unlimited of text lines. That config maybe invalid i guess the core should throw if provide out of range?

**Comment by noahtallen** [comment]
You should be able to render unlimited lines of text just by not specifying any lines of text. That property is used for restricting the number of lines. As long as you set there to be enough height it should fill it up.

**Comment by rickhanlonii** [comment]
Hey @luutruong, thanks for filing

This looks like a question and not a bug. Since this issue tracker is not a help forum, we're going to close and recommend posting to StackOverflow. If you believe this is a bug, please update the provide a way for us to reproduce/confirm and we'll consider re-opening 👌
