### ISSUE TITLE
App.js code is not working.

### ISSUE THREAD

**Issue by renishdeveloper** [facebook/react-native#22818]
I'm created the react native project using the react-native init project name
Project created successfully and runs fine on the android device.

> Now it writes the below code in theApp.js file.

`export default class App extends React.Component {
constructor(props) {
super(props);
this.state = {
};
}

render() {
return 
}
}

const AppStackNavigator = new createStackNavigator({
Home: { screen: Home },
})

const NavStack = createAppContainer(AppStackNavigator);`

Now, still, the project displays the welcome to React Native! which is displaying at project creation time.

**Comment by rickhanlonii** [comment]
Hey @noahtallen, thanks for filing

Note that this issue tracker is not a help forum, we're going to close and recommend posting to StackOverflow. If you believe this is a bug and not a question, please update the description to use our [bug issue template](https://github.com/facebook/react-native/issues/new?template=bug_report.md) and we'll consider re-opening 👌
