### ISSUE TITLE
Gesture Responder System for sibling views?

### ISSUE THREAD

**Issue by alamothe** [facebook/react-native#22810]
I read about the Gesture Responder System and the ability to switch the responder from one view to another during the duration of a touch. This may be a noob question, but it's entirely unclear to me from reading the docs.

I have two views which are siblings (share the same parent). I would like to switch the responder from one to the other. But judging by my tests, `onMoveShouldSetResponder` will never get called on the second view - I would expect it to get called when I move my finger to it.

Is this even possible? Or the responder can only be passed up the component tree? How about down the tree?

Thanks!

**Comment by omars94** [comment]
@alamothe can you add your code please?

**Comment by alamothe** [comment]
@omars94 Here's my snack: https://snack.expo.io/@alamothe/ranting-donuts

I have two views, red and blue. If I start to touch red then move my finger from red to blue, blue will never get called. Basically, whichever view started being the responder will remain responder forever. 

I think the docs never explain this.
