### ISSUE TITLE
iOS app is packaging all asset resolutions (@1x, @2x, @3x) together

### ISSUE THREAD

**Issue by IljaDaderko** [facebook/react-native#22826]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment

```
  React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
      Memory: 865.96 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.2 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 28
        Build Tools: 28.0.3
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

## Description
SInce ios 9 and XCode 7 apple introduced concept of [App Thining](https://help.apple.com/xcode/mac/current/#/devbbdc5ce4f). Part of this is only bundling `@1x`, `@2x` and `@3x` images on per device basis i.e. iPhone X would receive bundle that only has `@3x` images and iPhone 8 would only include `@2x` images.

Per [react native documentation of images](https://facebook.github.io/react-native/docs/images#static-image-resources) we can use these suffixes (`@2x` and `@3x`) as well to use images of specific resolution on different devices.

I only had `@3x` images before and added `@2x`. Performance of my app on older devices improved due to using lower resolution images which was nice. But upon viewing my bundle sizes in App store connect portal under Activity -> All Builds -> (Latest Build) -> App Store App Sizes all of the phones had same app size and it increased after adding `@2x` images, so it seems as if react-native builds and bundles all images and is not utilising app thinning?

Judging by this point in the docs, only images that are used are packaged?
> Only the images that are actually used will be packaged into your app.

I made sure I have everything in place so that app store utilises App Thining

1. Enabled Bytecode
2. Using XCode 10
3. Min iOS target is 11.4

## Reproducible Demo

App sizes from app store connect portal, if correct images are bundled app sizes of `iPhone XS` and `iPhone 6` for example, should be different.

<img width="803" alt="screenshot 2018-12-29 at 17 30 10" src="https://user-images.githubusercontent.com/3154053/50539820-87516c80-0b8f-11e9-9bee-f4f3ec2a0815.png">

**Comment by tychota** [comment]
Hi,

thanks for reporting.

I think the docs is wrong. I think android split `@2x and @3x` correctly if you activate imageSplit in the gradle file. I think iOS does not do that, at least out of the box.

But I'm pretty sure fresco (the underlying image for android) or iOS will pick the right resolution, so it does not spend too much CPu in downscaling.

I'm subscribing to this issue to hopefully know more about it :)

**Comment by ericlewis** [comment]
@IljaDaderko as noted in the [docs](https://help.apple.com/xcode/mac/current/#/devbbdc5ce4f) you linked:

> Use asset catalogs so that the App Store can select images, GPU resources, and other data appropriate for each device variant.


React Native [supports using asset catalogs](https://facebook.github.io/react-native/docs/images#images-from-hybrid-app-s-resources), and your app should benefit from thinning if you use them. Here are docs on using asset catalogs: https://help.apple.com/xcode/mac/current/#/dev10510b1f7
