### ISSUE TITLE
Image loading from named bundles: UIImage -imageNamed:inBundle:compatibleWithTraitCollection:

### ISSUE THREAD

**Issue by fatuhoku** [facebook/react-native#2282]
I'm building a private pod called `RNUI` that contains all of my React Native UI elements in my app. This private pod is then going to be used as a dependency in a main app project, so that I can mix-and-match RN and standard UI components.

When I develop with RN, I normally load some associated static Image assets by using this syntax:

```
        <Image
          style={styles.icon}
          source={{uri: 'image-name', isStatic: true}}
        />
```

This normally works well. However, because I'm building a private pod, the `Images.xcassets` gets treated as a resource because Cocoapods embeds it into a framework when you install the pod (i.e. when `MyMainApp` declares `RNUI` as a dependency, and you run `pod install`).

This causes RN to not find the images I want, because RN just usees `UIImage`'s `-imageNamed:` (e.g. in this case, `image-name`).  For these cases you would normally use `UIImage`'s `+imageNamed:inBundle:compatibleWithTraitCollection:` method, and specify the bundle explicitly like so:

```swift
// Swift
let image = UIImage(named: "image-name", inBundle: NSBundle(forClass: self.dynamicType), compatibleWithTraitCollection:nil)`
```

How can image loading support add support for loading images from specific named bundles?

**Comment by fatuhoku** [comment]
I've tried using different syntaxes for `uri` but no avail; it's still going to look for the images in the main bundle only.

**Comment by fatuhoku** [comment]
The need to access image resources namespaced by the framework they live in is a caveat is well-documented here: http://blog.cocoapods.org/CocoaPods-0.36/

**Comment by nicklockwood** [comment]
Currently we don't support loading from asset bundles other than the main one. I don't know what the best approach for this is. The options I see are, either:

1. Scan all asset bundles until we find one containing the specified image. This would make the first load expensive and also wouldn't work correctly for if multiple bundles contain images with the same name,

2. Introduce a new syntax for specifying the bundle. We could do 'bundleName/imageName' or 'bundleName:imageName' or maybe something else.

3. Add a new parameter for the bundle, e.g `{uri: 'image-name', bundle: 'bundle-name'}`

Any preference @vjeux?

(FYI, the 'isStatic' property is no longer needed)

**Comment by vjeux** [comment]
The packager implements a better solution for this: require('./image.png') in JavaScript. Then, you don't need to link it into xcode and therefore deal with cocoapods for assets, just put them where js lives and it'll work.

It's implemented on iOS but disabled until we get it working for Android. But I think that it'll be the solution for this

**Comment by nicklockwood** [comment]
@vjeux I don't think we should assume that everyone will want to use that approach. Providing interop with Apple's xcassets system is still worthwhile for people building hybrid native/RN apps that already package images in that way.

I think providing an iOS-specific 'bundle' parameter as an optional argument to the source object is probably the way to go here. It avoids complicating the packager or Android code-paths by introducing new, nonstandard URL syntax, and won't interfere with the require('./image.png') mechanism.

**Comment by fatuhoku** [comment]
I think @nicklockwood's adding `bundle` to the image source object makes sense. Android may or may not need to heed this valu.e

**Comment by vjeux** [comment]
@nicklockwood absolutely, we should support both. The way I was thinking is that {uri: 'somename'} would use the xcasset or whatever android supports and `require('./image.png')` would use the packager/react-native asset system

**Comment by MattFoley** [comment]
@vjeux @nicklockwood I'm also in the boat of needing to load images not from the mainBundle, looking into this right now. 

However, due to how `RCTConvert UIImage:` and `RCTConvert NSURL:` work together, I'm leaning more towards solving this via react-native-fs and the uri. I'm going to attempt to add a `pathForBundleNamed:` to rn-fs, and use the `uri` value to fetch the image from the bundle.

Let you guys know how it goes.

**Comment by MattFoley** [comment]
Not sure if this is satisfactory for everyone, but I did get this to work for me. Here's the relevant pull request into `react-native-fs`. Could possible be done with `react-native-fs` without my changes even.

https://github.com/johanneslumpe/react-native-fs/pull/11

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/image-loading-from-named-bundles-uiimage-imagenamedinbundlecompatiblewithtraitcollection
