### ISSUE TITLE
Running jest in a react-native project with symlinked node_modules doesn't work

### ISSUE THREAD

**Issue by nicojs** [facebook/react-native#22823]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment

```
$ npx react-native info

  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
      Memory: 4.68 GB / 15.88 GB
    Binaries:
      Yarn: 1.12.3 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
```

## Description

Running `yarn test` in a react-native project where the node_modules are symlinked doesn't seem to work: 

```shell
$ yarn test
yarn run v1.12.3
$ node ./node_modules/jest/bin/jest.js
 FAIL  components/__tests__/StyledText-test.js
  ● Test suite failed to run

    Cannot find module 'setupDevtools' from 'setup.js'

      at Resolver.resolveModule (../node_modules/jest-resolve/build/index.js:221:17)
      at Object.<anonymous> (../node_modules/react-native/jest/setup.js:3:6)
```

We want this to work, because this is how [Stryker](https://stryker-mutator.io)'s sandboxes work. They create a temp folder inside your project, copy all source files into the sandbox dir and symlink the node_modules. Original issue here: https://github.com/stryker-mutator/stryker/issues/717

## Reproducible Demo

I've prepared a small git repository to demonstrate the problem. I've created this repository with `expo init` (choosing the more extensive "tab" setup). After that I've installed the latest version of react-native: `yarn add react-native`. After that I've created an example "sandbox" directory with a copy of all sources.
https://github.com/nicojs/jest-react-native-symlink-test

You can use these commands to reproduce the issue:

```shell
git clone https://github.com/nicojs/jest-react-native-symlink-test
cd jest-react-native-symlink-test
yarn install
yarn symlink # <-- this will symlink the node_modules under the sandbox directory
cd sandbox
yarn test
```

**Comment by rickhanlonii** [comment]
Hey @nicojs, thanks for filing!

This is being tracked in Jest in https://github.com/facebook/jest/issues/5356, there's a proposal PR in https://github.com/facebook/jest/pull/7549
