### ISSUE TITLE
"xxxx" has stopped running

### ISSUE THREAD

**Issue by Nocturne-FFG** [facebook/react-native#22832]
- [ ] Review the documentation: https://facebook.github.io/react-native
  - [ ] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Environment:
  OS: macOS 10.14.2
  Node: 8.11.1
  Yarn: 1.6.0
  npm: 4.5.0
  Watchman: 4.9.0
  Xcode: Xcode 10.1 Build version 10B61
  Android Studio: 3.2 AI-181.5540.7.32.5014246

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.2 => 0.52.2

Device：
android@4.4.2

## Description
The application cannot be opened on the Android real machine. The running "xxx" has stopped running. When I set "enableProguardInReleaseBuilds=true", it can run, but in this case, one of the plugins in the application cannot work.

-------------------------------------------------------------------------------------------------

When "enableProguardInReleaseBuilds=false"is set, "xxxx" has stopped running. The error message of android is as follows:
![image](https://user-images.githubusercontent.com/45280212/50555016-c05d1e80-0d00-11e9-9572-b831dc51370e.png)

Details:
12-31 13:47:23.034 2563-2806/? E/SubmitMessage: Submit string: submit:trigger=0,bugtype=2,modulename=com.jueyn.server,level=1,testtype=NORMAL,path=/data/log/unzip/P6-T00_V100R001C01B708_022BTF7N39037955_20181231134723_crash
12-31 13:47:23.114 2411-2447/? E/HiApp.NetworkUtil: IntentService[RepeatingTaskManager]{1069} <<< ERROR >>> isMeteredWifi NoSuchMethodException, ex: java.lang.NoSuchMethodException: getHwMeteredHint [class android.content.Context]
12-31 13:47:23.134 2563-2765/? E/FileUtils: srcFile is not a file
12-31 13:47:23.134 2563-2765/? E/LogDatabase: Could not move to uploading path.
12-31 13:47:23.524 1263-1263/? W/HwLauncher: Launcher  updateMarginLayoutParamsForView:the target view is null.

-------------------------------------------------------------------------------------------------

When "enableProguardInReleaseBuilds=true"is set, it works fine, but there is a plugin error in my application. The error message is as follows:
![image](https://user-images.githubusercontent.com/45280212/50555084-6a897600-0d02-11e9-8855-5396e2f96b01.png)

Details:

12-31 13:36:16.570 14060-14384/? E/linker: readlink('/proc/self/fd/86') failed: Permission denied [fd=86]
12-31 13:36:16.570 14060-14384/? E/linker: warning: unable to get realpath for the library "/data/app/com.jueyn.server-1/lib/arm/libAMapSDK_MAP_v6_4_0.so". Will use given name.
12-31 13:36:16.570 5402-5428/? W/PhoneInterfaceManager: shouldBlockLocation running ...
12-31 13:36:16.601 5402-5967/? W/PhoneInterfaceManager: shouldBlockLocation running ...
12-31 13:36:16.862 14060-14384/? A/art: art/runtime/thread.cc:1329] Throwing new exception 'no non-static method "Lcom/autonavi/ae/gmap/GLMapEngine;.reloadMapResource(ILjava/lang/String;I)V"' with unexpected pending exception: java.lang.NoSuchMethodError: no non-static method "Lcom/autonavi/ae/gmap/GLMapEngine;.requireMapResource(ILjava/lang/String;)[B"
12-31 13:36:16.862 14060-14384/? A/art: art/runtime/thread.cc:1329]   at void com.autonavi.ae.gmap.GLMapEngine.nativeInitParam(java.lang.String, java.lang.String, java.lang.String, java.lang.String) (GLMapEngine.java:-2)
12-31 13:36:16.862 14060-14384/? A/art: art/runtime/thread.cc:1329]   at void com.autonavi.ae.gmap.GLMapEngine.createAMapInstance(com.autonavi.ae.gmap.GLMapEngine$InitParam) (GLMapEngine.java:1326)
12-31 13:36:16.862 14060-14384/? A/art: art/runtime/thread.cc:1329]   at void com.amap.api.mapcore.util.b.a(int, javax.microedition.khronos.opengles.GL10, javax.microedition.khronos.egl.EGLConfig) (AMapDelegateImp.java:2956)
12-31 13:36:16.862 14060-14384/? A/art: art/runtime/thread.cc:1329]   at void com.amap.api.mapcore.util.b.createSurface(javax.microedition.khronos.opengles.GL10, javax.microedition.khronos.egl.EGLConfig) (AMapDelegateImp.java:5586)
12-31 13:36:16.862 14060-14384/? A/art: art/runtime/thread.cc:1329]   at void com.autonavi.ae.gmap.GLMapRender.onSurfaceCreated(javax.microedition.khronos.opengles.GL10, javax.microedition.khronos.egl.EGLConfig) (GLMapRender.java:231)
12-31 13:36:16.862 14060-14384/? A/art: art/runtime/thread.cc:1329]   at void com.amap.api.mapcore.util.n$i.l() (GLTextureView.java:1488)
12-31 13:36:16.862 14060-14384/? A/art: art/runtime/thread.cc:1329]   at void com.amap.api.mapcore.util.n$i.run() (GLTextureView.java:1201)
12-31 13:36:16.862 14060-14384/? A/art: art/runtime/thread.cc:1329] 
12-31 13:36:16.862 14060-14384/? A/art: art/runtime/runtime.cc:368] Runtime aborting...
12-31 13:36:16.862 14060-14384/? A/art: art/runtime/runtime.cc:368] 
12-31 13:36:17.481 4303-4605/? E/WifiConfigStore: updateConfiguration freq=2412 BSSID=58:6a:b1:1d:13:20 RSSI=-66 "mxxz-chinaunicom"NONE
12-31 13:36:18.056 4303-5458/? E/HsmCoreServiceImpl: onTransact in code is: 102
12-31 13:36:18.056 4303-5458/? W/MediaProcessHandler: remove target not exist, maybe the UI process: uid: 10120, pid: 13142

-------------------------------------------------------------------------------------------------

I don't know what to do now.！！！！！！！！

## Reproducible Demo
init react native@0.52.2
And run on android device 4.4.2

**Comment by radko93** [comment]
You're running old version and it's related to a third party plugin so we cannot help you in this case.
