### ISSUE TITLE
share message content via facebook and messanger

### ISSUE THREAD

**Issue by kalraneeraj24550** [facebook/react-native#22836]
## Environment
 React Native Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
      CPU: (4) x64 Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz
      Memory: 597.23 MB / 7.68 GB
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 8.10.0 - /usr/bin/node
      npm: 3.5.2 - /usr/bin/npm
    SDKs:
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 25.0.2, 26.0.2, 26.0.3, 27.0.3, 28.0.2, 28.0.3
    npmPackages:
      react: 16.6.1 => 16.6.1 
      react-native: 0.57.5 => 0.57.5 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description
i want to share text via facebook and messanger. i could have used Share.share API but i want to have single share option in my app for facebook and messanger.
![screenshot from 2018-12-13 18-20-53](https://user-images.githubusercontent.com/44640902/50573190-c6342c00-0df4-11e9-99a8-9312b71fcfcf.png)
i am able to share only link content via facebook and messanger , not pre-written text.
i just wanna share text for example "hello world". but it only send link not message.

**Comment by bartolkaruza** [comment]
Have a look at the actual [Facebook SDK](https://github.com/facebook/react-native-fbsdk) with the sharing doc [here](https://developers.facebook.com/docs/react-native/sharing). I'm not sure about Facebook Messenger, but maybe something like [this](https://www.npmjs.com/package/react-native-facebook-messenger) will help you. 
I'm closing this as not a React Native core issue. If you feel that this is a React Native issue, let me know and please also add a reproducible example with your issue.
