### ISSUE TITLE
absolutely positioned element with defined width should be centered

### ISSUE THREAD

**Issue by danieldkim** [facebook/react-native#2284]
An absolutely positioned element with a defined width and with sides set to 0 should be centered on the axis.  Current behavior, along the horizontal for example, is that the `right` value is ignored: https://rnplay.org/apps/eWRlDw/.

I want to use an absolutely positioned element for this instead of a flexbox because I want touches in the space around the element to be detected by an underlying layer -- the flexbox container of the centered element in my use case would also need to be absolutely positioned over another element.

**Comment by ide** [comment]
The current behavior appears to match CSS in that the `right` value is supposed to be ignored. If you want touches to go through to the layer below, look into the pointerEvents prop. But as it stands I believe the layout is correct.

**Comment by danieldkim** [comment]
Thanks for the quick response, @ide!  pointerEvents works nicely to solve my problem.

As for the layout issue, I'd used this technique before to center things but neglected to include the auto margins which are required to make it work.  But we don't have auto margins here so I'll close this.
