### ISSUE TITLE
Reopening closed issue on FlatList scrollToIndex

### ISSUE THREAD

**Issue by scottmas** [facebook/react-native#22845]
- [X] Review the documentation: https://facebook.github.io/react-native
  - [X] Search for existing issues: https://github.com/facebook/react-native/issues
  - [X] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
[skip envinfo]

## Description
I am posting a new issue to resurrect an closed issue that is still outstanding: https://github.com/facebook/react-native/issues/19080

Please refer to the details in that thread.

## Reproducible Demo
The reproducible demo is in the linked issue.

**Comment by scottmas** [comment]
[skip envinfo]

**Comment by TheSavior** [comment]
I reopened your source issue
