### ISSUE TITLE
Movies App redboxes when searching for `ab`

### ISSUE THREAD

**Issue by vjeux** [facebook/react-native#2285]
Repro Steps:

1) Open MoviesApp
2) Search for `ab`
3) See the redbox

```
[RCTGIFImage.m:89] Loading remote image URLs synchronously is a really bad idea. 
http://d3biamo577v4eu.cloudfront.net/static/images/redesign/poster_default_thumb.gif
```

![ios simulator screen shot aug 10 2015 1 37 12 pm](https://cloud.githubusercontent.com/assets/197597/9183581/e9de1ac4-3f64-11e5-8cae-92d701c91929.png)

**Comment by vjeux** [comment]
Also, would be nice to change the error message to add the url that's failing

**Comment by a2** [comment]
This has been fixed. Just checked in master.

**Comment by a2** [comment]
Also, the failing URL is definitely in the message.
