### ISSUE TITLE
WKWebview <input type=file> select a photo，webview will be reload when you back

### ISSUE THREAD

**Issue by lipnpn** [facebook/react-native#22851]
- [ ] Review the documentation: https://facebook.github.io/react-native
  - [ ] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Run `react-native info` in your terminal and paste its contents here.

## Description
Describe your issue in detail. Include screenshots if needed. If this is a regression, let us know.

## Reproducible Demo
Let us know how to reproduce the issue. Include a code sample, share a project, or     share an app that reproduces the issue using https://snack.expo.io/. Please follow the guidelines for providing a MCVE: https://stackoverflow.com/help/mcve

**Comment by lipnpn** [comment]
use RN ios WKwebview ，<input type=file> select a photo，webview will be reload when you back，
in RCTWKWebview.m,didMoveToWindow method will reset webview,it is a bug。 alloc webview when wkwebview is null ，it can resolve it

**Comment by lipnpn** [comment]
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 60.50 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.6.0 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.2.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.7.0 => 16.7.0 
      react-native: ^0.57.8 => 0.57.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      react-native-storage: 0.2.2

**Comment by AugustoGu** [comment]
Same problem here.

In iOS, in the input file always when selecting a photo or take a picture, the webview does reload, being impossible to complete the action. Only when "useWebKit" = true

For now I'm using "useWebKit" = false, so it works as expected.

**Comment by FrK492** [comment]
I'm having the same problem with RN 0.58.3.

I'm using WKWebView and when i try to select an image from gallery on iOS it resets my WebView.

Any update or workaround on this?

**Comment by Gemerz** [comment]
@FrK492 hey, man, Lately, I have been using react-native-community/react-native-webview independently which can avoid that situation, I think community and react native team trying to remove webview from the React Native core as independent module, so now those modules are not sync up.
