### ISSUE TITLE
react-devtools 3.5.0 breaks new project

### ISSUE THREAD

**Issue by sunnylqm** [facebook/react-native#22863]
<img width="379" alt="devtool" src="https://user-images.githubusercontent.com/615282/50672252-f573b480-1011-11e9-9ff4-565bedd997db.png">

`reactDevTools.connectToDevTools is not a function`

```bash
## Environment
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
      Memory: 833.36 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.15.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 22, 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.2, 23.0.3, 24.0.1, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.2
        System Images: android-25 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: 0.57.8 => 0.57.8
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-create-library: 3.1.2
      react-native-debugger-open: 0.3.17
      react-native-git-upgrade: 0.2.7
      react-native-update-cli: 0.1.0
```

## Reproducible Demo

Just init a new project and you'll hit this issue

## Workaround

Put the following in your `package.json` and run `yarn` (not npm, which does not support "resolutions") to force install the previous version:

```json
  "resolutions": {
    "react-devtools-core": "3.4.3"
  }
```

Then close the current packager window, run `yarn start --reset-cache`.

Since the compiled js file changed a lot and we actually got an empty object in setupDevtools.js, so I suspect that something went wrong with build configuration, maybe related to https://github.com/facebook/react-devtools/commit/28d36a228de7ff8d72665f3c6a1b8f11ad7e94b6

cc  @bvaughn  @kelset @hramos

**Comment by Flatheadman** [comment]
same problem.

**Comment by swushi** [comment]
Same issue on two different computers. Workaround without yarn on Windows?

**Comment by silencer07** [comment]
for me 3.4.1 version works but not 3.4.2 and above....

**Comment by boot-vue** [comment]
I have the same.  my os is win-10.

**Comment by Jacky9425** [comment]
same here

**Comment by trops** [comment]
still not working with the workarounds

**Comment by jamonholmgren** [comment]
Thanks for reporting! (Please don't comment with "same here" comments; just thumbs-up the issue and subscribe to updates if you want.)

**Comment by osamaq** [comment]
I decided to learn React Native today, and I struggled for ~3 hours thinking I did something wrong during the "Get Started" guide. I was about to open a new issue to get help... only to find this opened 2 hours ago. Quite the headache 😫

**Comment by ppv94** [comment]
i am also getting the same error what should i do resolve this error 
i have tried this but i am getting same error
 "resolutions": {
    "react-devtools-core": "3.4.3"
  }
what should i do to resolve this issue

**Comment by prav02** [comment]
I am facing same problems, but when I am trying to run the previous projects that I have created, they all run fine.

**Comment by MingFaiYau** [comment]
After i upgrade react native 0.54.x -> 0.57.8, i got this problem too.
It seems

**Comment by jamonholmgren** [comment]
I would recommend rolling back to react-devtools-core@3.4.3. I was able to do this and it worked.

```
yarn add --dev react-devtools-core@3.4.3
or
npm install --save-dev react-devtools-core@3.4.3
```

**Comment by aflofo** [comment]
God bless you

**Comment by chuckntaylor** [comment]
Same issues here. Reverting to react-devtools-core@3.4.3 as @jamonholmgren recommended got me back up and running. Thanks!

**Comment by minhphung210** [comment]
the solution not work for me. I use version 0.57.8

**Comment by SilajitBukaiSil** [comment]
@svjkumar how to disabled JS Dev Mode in Dev settings? can you please help me. I am new in react native.

**Comment by jordenchang55** [comment]
Shake your device and then you'll see the develop menu, the last one is Dev settings.

**Comment by minhphung210** [comment]
@ppv94  @MingFaiYau  solution is worked , you can try its

**Comment by SilajitBukaiSil** [comment]
@jamonholmgren the solution is not worked for me

**Comment by jordenchang55** [comment]
@minhphung210 Thanks. After 3 hours of struggle, finally I can see welcome text on the screen.

**Comment by timesina** [comment]
This solution does not work for 0.57.8 versions
![image](https://user-images.githubusercontent.com/20322044/50678634-95ddcf00-103a-11e9-9946-0aa8caf1ce95.png)

**Comment by ppv94** [comment]
> @ppv94. @MingFaiYau solution is worked , you can try its

its working in android but its not working in ios for me.

**Comment by jordenchang55** [comment]
You need to install the dependency in the devDependecies, i.e., use npm install with `--save-dev` argument.

**Comment by SilajitBukaiSil** [comment]
> Shake your device and then you'll see the develop menu, the last one is Dev settings. BTW, I tried in react-native@0.57.8, but not work

Thanks @jordenchang55 . Its working for me in react-native@0.57.8. Just run your project once again.

**Comment by NguyenPhatBG** [comment]
Same issue, but version 0.57.8 not work for me :(
https://github.com/facebook/react-native/issues/22865

**Comment by nvmanh** [comment]
confirmed ios/android works with rn 0.57.8 and react-devtools-core 3.4.2 ( 3.4.3 not work)
`{
  "name": "TicketScanner",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "ios": "react-native run-ios",
    "android": "react-native run-android"
  },
  "dependencies": {
    "react": "16.6.3",
    "react-native": "0.57.8",
    "react-native-gesture-handler": "^1.0.12",
    "react-navigation": "^3.0.9"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "eslint-config-rallycoding": "^3.2.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.51.1",
    "react-devtools-core": "3.4.2",
    "react-test-renderer": "16.6.3"
  },
  "jest": {
    "preset": "react-native"
  },
  "resolutions": {
    "react-devtools-core": "3.4.2"
  }
}
`

**Comment by ozanmanav** [comment]
Same here.

**Comment by inkweon7269** [comment]
Me too.

**Comment by zhima** [comment]
> done npm install --save-dev react-devtools-core@3.4.3,
> in android its working but in ios simulator its showing the same error.
> ![screenshot 2019-01-04 at 12 55 10 pm](https://user-images.githubusercontent.com/28724702/50677457-fe6b8280-101f-11e9-93bf-6aa16007ab2f.png)
> how to resolve this error

I am using 0.57.8, and I encounter the same issue.
I also fix the issue with @jamonholmgren 's command `npm install --save-dev react-devtools-core@3.4.3`

At first, it works in android, while iOS still show the error.
Then I run these two command to clean the cache, and `react-native run-ios` again, and it works.
`npm cache clean --force`
`react-native start --reset-cache`

**Comment by NguyenPhatBG** [comment]
Thanks @nvmanh, @zhima, It's  work for me now 💃 💃 💃

**Comment by priyesh321** [comment]
it doesn't work for me

**Comment by arkhan13** [comment]
not working the heck
npm install --save-dev react-devtools-core@3.4.2 isn't working

**Comment by NguyenPhatBG** [comment]
@priyesh321 => @nvmanh and @zhima 
You need to delete node_module folder, after that yarn or npm install
Check package.json file, if you not seen react-devtools-core: '3.4.2'
do this: npm install --save-dev react-devtools-core@3.4.2

**Comment by ppv94** [comment]
> > done npm install --save-dev react-devtools-core@3.4.3,
> > in android its working but in ios simulator its showing the same error.
> > ![screenshot 2019-01-04 at 12 55 10 pm](https://user-images.githubusercontent.com/28724702/50677457-fe6b8280-101f-11e9-93bf-6aa16007ab2f.png)
> > how to resolve this error
> 
> I am using 0.57.8, and I encounter the same issue.
> I also fix the issue with @jamonholmgren 's command `npm install --save-dev react-devtools-core@3.4.3`
> 
> At first, it works in android, while iOS still show the error.
> Then I run these two command to clean the cache, and `react-native run-ios` again, and it works.
> `npm cache clean --force`
> `react-native start --reset-cache`

thanks it works for me in android also.

**Comment by arkhan13** [comment]
there is one solution to this Within your app in the Android Emulator press Command + M on OSX or Ctrl + M on Linux and Windows.

then go to dev settings

uncheck JD DEV MODE

The first option worked for me

**Comment by priyesh321** [comment]
> @priyesh321 => @nvmanh and @zhima
> You need to delete node_module folder, after that yarn or npm install
> Check package.json file, if you not seen react-devtools-core: '3.4.2'
> do this: npm install --save-dev react-devtools-core@3.4.2

thanks its works for me

**Comment by SamuelVEshapogu** [comment]
@sunnylqm thanks (y)
I'm using 0.56, below workaround solved the issue.
 "resolutions": {
    "react-devtools-core": "3.4.3"
  }

**Comment by AygnYldz** [comment]
npm install --save-dev react-devtools-core@3.4.2

it works.

**Comment by arkhan13** [comment]
to get rid of this in the first place I decided to create a downgraded react-native version which is 0.55
to do so 
run this
react-native init newproject --version react-native@0.55    
0.55 is the version I chose

**Comment by SMJ93** [comment]
We are still getting the issue after downgrading `react-devtools-core` to `3.4.3` and `3.4.2`

Our environment:
- react-native: 0.57.2
- node: 10.5.0
- npm: 6.4.1
- iOS 12.1

Also tried setting `react-devtools` to `3.4.3` too.

We can't downgrade our react-native version to `0.55` as @arkhan13 as suggested above.

**Comment by joerneu** [comment]
Even after downgrading in "devDependencies" I could still find newer versions of "react-devtools-core" in other modules.

I solved it with yarn by downgrading and changing the version of "react-devtools-core" in all dependent modules:

```
  "devDependencies": {
    ...
    "react-devtools-core": "3.4.3",
    ...
  },
  "resolutions": {
    "**/react-devtools-core": "3.4.3"
  },

```
Important: The glob-pattern in "resolutions"!

After deleting the "node_modules" folder and the "yarn.lock" file and running `yarn install`, the Android app is running without issues.

(with react-native 0.57.8)

**Comment by Kouznetsov** [comment]
Does anyone have an idea of what exactly is going wrong here ? 
Why is this error appearing now ? Did something change with the RN repo ? I didn't upgrade anything but the issue appeared anyway. As the npm package cannot (they cannot, right ?) change without a version incrementation, I wonder how I came to have this error.

+ If anyone would know the exact reason of the issue (a RN contributor perhaps), it would certainly help.

**Comment by sunnylqm** [comment]
@Kouznetsov The reason I already described in title, this is, caused by the new version of `react-devtools-core`. A project will contain thousands of third-party libraries, which is why we often saw things break like a curse though we do nothing wrong.

**Comment by sameerjain** [comment]
Tried all solutions from this thread but I am still having issue with ios. Attached is my package.json. 
```
{
  "name": "MyAwesomeProject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.6.3",
    "react-native": "0.57.8",
    "react-native-gesture-handler": "^1.0.12",
    "react-navigation": "^3.0.9"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "eslint-config-rallycoding": "^3.2.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.51.1",
    "react-devtools-core": "3.4.2",
    "react-test-renderer": "16.6.3"
  },
  "jest": {
    "preset": "react-native"
  },
  "resolutions": {
    "**/react-devtools-core": "3.4.2"
  }
}

```
Any idea?

**Comment by jasonroyle** [comment]
[This](https://github.com/facebook/react-native/issues/22865#issuecomment-451457463) fixed it for me running react-native@0.57.8.

**Comment by Richi2293** [comment]
For me it worked only using yarn, otherwise with npm the error remained me.
(added in devDependencies the react-devtools-core and added the resolutions )

**Comment by bvaughn** [comment]
Hi all 👋 Sorry for the trouble 😦

I believe this was something I broke when upgrading the React DevTools project's Babel and Webpack versions in https://github.com/facebook/react-devtools/pull/1235, and we're just now encountering it because we haven't released the `react-devtools-core` package since then.

I just published `react-devtools-core` v3.5.1. Can anyone let me know if this resolves the issue? (I'm unable to repro the original reported issue so it's hard for me to verify the fix.)

**Comment by davideddr** [comment]
Now it works fine for me creating a new project. 
Thank you @bvaughn 👍

**Comment by bvaughn** [comment]
Yay! Thanks for verifying, @davideddr !

**Comment by bvaughn** [comment]
I'm going to mark this issue as closed for now then. Let's re-open if others are still experiencing problems!

**Comment by chuckntaylor** [comment]
I can also verify that the issue is gone. Thank you for the quick fix @bvaughn !

**Comment by ck3g** [comment]
@bvaughn yep works for me as well. (Didn't work before)

**Comment by kelset** [comment]
(thanks @bvaughn for the quick fix!)

**Comment by elanpang** [comment]
@bvaughn 
`npm install --save-dev react-devtools-core@3.5.1`
It still not work for me with Rn 0.57.8

**Comment by jasonroyle** [comment]
> @bvaughn
> `npm install --save-dev react-devtools-core@3.5.1`
> It still not work for me with Rn 0.57.8

You shouldn't have to do this anymore, remove `react-devtools-core` from your dependencies in `package.json` and run `rm -rf node_modules && npm install` this should reinstall the packages and bring the fix in along with them.

**Comment by elanpang** [comment]
@jasonroyle
oh,I understand, it is a depend lib of Rn, and Rn alway pull the latest version, like what @sunnylqm  said , right? 
Now it real works for me, thank you a lot !
