### ISSUE TITLE
Using `new.target` crashes the bundler

### ISSUE THREAD

**Issue by dzek69** [facebook/react-native#22862]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Run `react-native info` in your terminal and paste its contents here.
```
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (8) ia32 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
      Memory: 4.32 GB / 15.89 GB
    Binaries:
      Node: 11.2.0 - C:\nodejs\node.EXE
      Yarn: 1.12.3 - C:\Apps\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338
```

## Description
Using `new.target` causes developer bundler to fail. `Unexpected token '.'` red screen is being shown. `new.target` is part of ECMAScript 2015 (6th Edition, ECMA-262) standard according to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target

I am currently unable to use some libraries, like `whatwg-url` (while trying to work around #16434) because of this.

Production version builds just fine but app crashes with same error, just presented as android app error.

This can be taken as duplicate of #8848, but I feel this was wronly closed. Babel does support this now: https://babeljs.io/docs/en/babel-plugin-transform-new-target however I feel this should/could be fixed without transpiling [?].

## Reproducible Demo
```javascript
function() {
  if (new.target) {}
}
```

or just import `whatwg-url`.

**Comment by dzek69** [comment]
No, I just used another library. Forking a library and replacing `new.target` code (`this instanceOf Stuff`) should be possible if you MUST use any exact library. But that's annoying way to work around the issue, I know.

**Comment by assyme** [comment]
Thanks for your reply. Which library did you end up using?

**Comment by dzek69** [comment]
https://www.npmjs.com/package/parse-url
