### ISSUE TITLE
react-native run-android is giving error undefined is not a function (evaluating 'react DevTools.connect DevTools')

### ISSUE THREAD

**Issue by Yajan** [facebook/react-native#22865]
## Environment

  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz
      Memory: 1.44 GB / 7.91 GB
    Binaries:
      Yarn: 1.9.4 - C:\Users\Yajana\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
      Watchman: 4.9.0 - C:\Shortcut\watchman.EXE
    IDEs:
      Android Studio: Version  3.0.0.0 AI-171.4443003

## Description
Getting error as 
undefined is not a function (evaluating 'reactDevTools.connectToDevTools')
<unknown>
    C:\Users\Yajana\React-Native\fr-react-native\FrReactNative\node_modules\react-native\Libraries\Core\Devtools\setupDevtools.js:50:36
loadModuleImplementation
    C:\Users\Yajana\React-Native\fr-react-native\FrReactNative\node_modules\metro\src\lib\polyfills\require.js:320:6
guardedLoadModule
    C:\Users\Yajana\React-Native\fr-react-native\FrReactNative\node_modules\metro\src\lib\polyfills\require.js:214:36
metroRequire
    C:\Users\Yajana\React-Native\fr-react-native\FrReactNative\node_modules\metro\src\lib\polyfills\require.js:136:24
<unknown>
    C:\Users\Yajana\React-Native\fr-react-native\FrReactNative\node_modules\react-native\Libraries\Core\InitializeCore.js:211:13
loadModuleImplementation
    C:\Users\Yajana\React-Native\fr-react-native\FrReactNative\node_modules\metro\src\lib\polyfills\require.js:320:6
guardedLoadModule
    C:\Users\Yajana\React-Native\fr-react-native\FrReactNative\node_modules\metro\src\lib\polyfills\require.js:207:45
metroRequire
    C:\Users\Yajana\React-Native\fr-react-native\FrReactNative\node_modules\metro\src\lib\polyfills\require.js:136:24
global code
    
![Error Screenshot](https://user-images.githubusercontent.com/31155354/50677210-8fd9f500-101e-11e9-8a21-c2a34a60edcf.png)

**Comment by TheSixth** [comment]
+1

**Comment by thaopit1992** [comment]
same mistake

**Comment by bbeckk** [comment]
+1

**Comment by Xifeat** [comment]
+1

**Comment by antoniomarcosferreira** [comment]
Thanks, @aayush-dev,  #22863 This work for me!

**Comment by decisionnguyen** [comment]
+1

**Comment by Yajan** [comment]
`npm install --save-dev react-devtools-core@3.4.2` Resolved the issue

**Comment by imcodervn** [comment]
`{
  "name": "JWallet",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "i": "rm -rf node_modules yarn.lock && yarn install",
    "run:devTools": "react-devtools",
    "bundle:ios": "rm -rf ./ios/REPatient/main.jsbundle && react-native bundle --entry-file='index.js' --bundle-output='./ios/JWallet/main.jsbundle' --dev=false --platform='ios' --assets-dest='./ios'",
    "run:ios": "react-native run-ios"
  },
  "dependencies": {
    "react": "16.6.3",
    "react-native": "0.57.8"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "eslint-config-rallycoding": "^3.2.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.51.1",
    "react-devtools-core": "3.4.2",
    "react-test-renderer": "16.6.3"
  },
  "jest": {
    "preset": "react-native"
  }
}
`
Still error

**Comment by razerduy** [comment]
`{
  "name": "JWallet",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "i": "rm -rf node_modules yarn.lock && yarn install",
    "run:devTools": "react-devtools",
    "bundle:ios": "rm -rf ./ios/REPatient/main.jsbundle && react-native bundle --entry-file='index.js' --bundle-output='./ios/JWallet/main.jsbundle' --dev=false --platform='ios' --assets-dest='./ios'",
    "run:ios": "react-native run-ios"
  },
  "dependencies": {
    "react": "16.6.3",
    "react-native": "0.57.8"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "eslint-config-rallycoding": "^3.2.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.51.1",
    "react-devtools-core": "3.4.2",
    "react-test-renderer": "16.6.3"
  },
  "jest": {
    "preset": "react-native"
  }
}
`

Still error

**Comment by shravanteegala** [comment]
i resolved using below command
npm install --save-dev react-devtools-core@3.4.2 Resolved the issue

**Comment by gabryelferreira** [comment]
+1

**Comment by bhavu43** [comment]
npm install --save-dev react-devtools-core@3.4.2  → Works

**Comment by akiladevinda** [comment]
This will work
npm install --save-dev react-devtools-core@3.4.2  

or try to remove node_modules folder and re-install it using 'npm install --save'

**Comment by charlesnse** [comment]
npm install --save-dev react-devtools-core@3.4.2

then also run react-native run-android

works perfectly for me

**Comment by tomm1996** [comment]
Can anyone explain why installing react-devtools-core will fix the issue?

**Comment by sachinkodkani** [comment]
thanks @Yajan 
installation of react devtools core solved my issue!

**Comment by jasonroyle** [comment]
> Can anyone explain why installing react-devtools-core will fix the issue?

More info at #22863

**Comment by paulofdev** [comment]
> `npm install --save-dev react-devtools-core@3.4.2` Resolved the issue

Unfortunately didn't work :'(

**Comment by danielfssz** [comment]
+1

**Comment by danielfssz** [comment]
> i resolved using below command
> npm install --save-dev react-devtools-core@3.4.2 Resolved the issue

resolve for me

**Comment by paulofdev** [comment]
> I am running...
> 
> react-native: 0.57.8
> react-native-cli: 2.0.1
> yarn: 1.12.3
> 
> I needed to add a [resolution](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) to `package.json`...
> 
> ```
> {
>   ...
>   "resolutions": {
>     "react-devtools-core": "3.4.3"
>   }
> }
> ```
> Then run...
> 
> ```
> $ yarn
> $ yarn start --reset-cache
> ```

THAAANK  YOU, BUDDY
