### ISSUE TITLE
Build script finding incorrect version of shasum

### ISSUE THREAD

**Issue by ryanhomer** [facebook/react-native#22873]
# For Discussion

I'm currently building with RN 0.58.0-rc2 on macOS. I use brew and have installed the `vim` package which installs the `perl` dependency. I believe that `perl` then installs its own version of `shasum` which doesn't support the `--portable` switch.

I noticed the following output in my build output:
```
/bin/sh -c /Users/.../ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/double-conversion.build/Script-190EE32F1E6A43DE00A8543A.sh

Unknown option: p

Type shasum -h for help

Unknown option: p

Type shasum -h for help

Unknown option: p

Type shasum -h for help

Unknown option: p

Type shasum -h for help
```

I believe this is caused by the code in `./node_modules/react-native/scripts/ios-install-third-parth.sh` in which there are multiple calls to `shasum -p`. In my case, `/usr/local/bin/shasum` is being invoked instead of `/usr/bin/shasum` the latter which does support the `p` switch.

I was wondering how this might affect my build. It seems related to caching so I suspect that my build is OK but I'm just not not able to take advantage of caching. Is this the case?

Also, since it is fairly common for developers to use `brew` and many will also have `vim` installed, I was just wondering if this is something that the FB team was aware of and if there might be some suggestions on getting around this.

**Comment by itinance** [comment]
In my case i just renamed `/usr/local/bin/shasum` to another filename. Then the "right" `shasum` is used and the error is gone.
