### ISSUE TITLE
The Text component can not flat wrap.

### ISSUE THREAD

**Issue by ATShiTou** [facebook/react-native#22888]
## Environment
[skip envinfo]

## Description

I tried to show a URL by the Text component. But it wraps with huge blank on the right of the component. I have read all the doc but can not find any props to configure it.

![2019-01-07 5 42 32](https://user-images.githubusercontent.com/38748693/50763882-aa70d000-12a3-11e9-853a-4c1fcf0a923f.png)

## Reproducible Demo
It does not need any reproducible demos.

**Comment by kelset** [comment]
Duplicate of #1438

**Comment by tanqq1** [comment]
I have the same problem, so how to solve it？
