### ISSUE TITLE
Undefined symbols for architecture armv7 : YGConfig

### ISSUE THREAD

**Issue by roots-ai** [facebook/react-native#22882]
I have tried every possible solution listed here.
https://stackoverflow.com/questions/6429494/undefined-symbols-for-architecture-armv7

Getting the below error while building a React Native 0.57.5 iOS app.

```
    Undefined symbols for architecture armv7:
      "YGConfig::YGConfig(int (*)(YGConfig*, YGNode*, YGLogLevel, char const*, void*))", referenced from:
          _YGConfigNew in libyoga.a(Yoga.o)
    ld: symbol(s) not found for architecture armv7
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Please help me resolve this.

**Comment by abrantes01** [comment]
@roots-ai did you manage to fix this issue ?

**Comment by roots-ai** [comment]
Yes! it was because of removing libReact.a from the Linked libraries.

**Comment by a805883237** [comment]
@roots-ai  Hello, how to add? Where is the path to libReact. a ?
