### ISSUE TITLE
PushNotificationIOS: register device and show local notification

### ISSUE THREAD

**Issue by rodrigowpl** [facebook/react-native#22895]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
  React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
      Memory: 129.04 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.2, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.2, 28.0.3
        System Images: android-25 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-26 | Google Play Intel x86Atom, android-27 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: 0.57.8 => 0.57.8
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

## Description
Take a look on example app, in `src/index.js` file I've registered two listeners, one to listen to device register before request permissions and another one to listen when notification is received.
But for some reason don't work, any listener is called neither any notification is shown either. 
I follow and I reviewed the documentation many many times and I don't have an idea why doesn't work

Important: I'm using simulator, is that a problem?

## Reproducible Demo
I did a simple app just to study and to ask help, here:
https://github.com/rodrigowpl/rn-notifications-play

**Comment by AugustoAleGon** [comment]
I have the same error. I don't have any Push Notifications in my iPhone...

**Comment by cpojer** [comment]
This issue has been moved to react-native-community/react-native-push-notification-ios#4.
