### ISSUE TITLE
Bug: providing an array for accessiblityActions crashes app

### ISSUE THREAD

**Issue by karlsander** [facebook/react-native#22891]
## Environment
<details>
<summary> react-native info output </summary>

```
  React Native Environment Info:
    System:
      OS: macOS 10.14.1
      CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 70.77 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.6.0 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 25, 26
        Build Tools: 23.0.1, 25.0.1, 26.0.1, 27.0.3
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.57.8 => 0.57.8 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

</details>

## Description
When trying to add custom VoiceOver accessibility actions as an array of strings for `accessibilityActions` prop, as introduced in 36ad8138997c195b8728906ceb51bd31338b6a24, the  the app crashes on iOS (12.1). The error is
```
JSON value '(action1, action2)' of type NSMutableArray cannot be converted to NSString
```

## Reproducible Demo

`react-native init`, then change line 23 of `App.js` to
```
<View accessibilityActions={["action1", "action2"]} style={styles.container}>
```
and `react-native run-ios`

## Fix
I believe this can be fixed by changing the type in [this line](https://github.com/facebook/react-native/blob/8c23b1804b4be4437334145180c96bac260b6b3e/React/Views/RCTViewManager.m#L112) from `NSString` to `NSArray<NSString*>`.

I'll submit a pull request to that effect, but since I'm not familiar with testing in this repo, it might be simpler for someone else to fix than merge it.

**Comment by karlsander** [comment]
Fix https://github.com/facebook/react-native/pull/22892#event-2076182818 merged

**Comment by cpojer** [comment]
This issue has been moved to react-native-community/react-native-cameraroll#10.
