### ISSUE TITLE
react-native run-android - completes and stops

### ISSUE THREAD

**Issue by sushilbansal** [facebook/react-native#22896]
## Environment

React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
      Memory: 19.61 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.6.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.5.0-next.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-27 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: 0.57.8 => 0.57.8
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description
1) Followed all the steps in getting started: https://facebook.github.io/react-native/docs/getting-started
2) Created a new project: react-native init AwesomeProject
3) Created a Virtual Device on Android Studio and started the app: react-native run-android
4) App Server runs and **Completes**. It spews Emulator terminal which start building the app on Emulator. 
5) Emulator shows the welcome page successfully. 
6) Issue is since app server Completes there is no good way to test any changes. I need to run the app server again:  react-native run-android
7) Why it is happening on Mac. I used the same setup on Windows and there it is working as intended. Emulator reloads for any changes in the app.

## Reproducible Demo
Complete steps are specified above.

Any help will be much appreciated. I tested it on real device by USB debugging option. The same result on Android. Have not tested it yet on ios.

Output of react-native run-android: 

Starting JS server...

Building and installing the app on the device (cd android && ./gradlew installDebug)...

> Task :app:installDebug

Installing APK 'app-debug.apk' on 'Pixel_XL_API_27(AVD) - 8.1.0' for app:debug

Installed on 1 device.

BUILD SUCCESSFUL in 37s

27 actionable tasks: 27 executed

Running /Users/sushilbansal/Library/Android/sdk/platform-tools/adb -s emulator-5554 reverse tcp:8081 tcp:8081

Starting the app on emulator-5554 (/Users/sushilbansal/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am start -n com.awesomeproject/com.awesomeproject.MainActivity)...

Starting: Intent { cmp=com.awesomeproject/.MainActivity }

**Comment by a-c-sreedhar-reddy** [comment]
What was the issue?

**Comment by DucSilva** [comment]
> What was the issue?

I have a similar issue that when i run react-native run-android completed, My App has stopped
![stopped](https://user-images.githubusercontent.com/46064085/68378760-3c28c280-017f-11ea-83e6-2768bc09749c.PNG)

**Comment by a-c-sreedhar-reddy** [comment]
I don't know why but i will run js server in another terminal and install the app.

**Comment by DucSilva** [comment]
> I don't know why but i will run js server in another terminal and install the app.

I'm trying fix it longtime but i can't find out
