### ISSUE TITLE
 Something went wrong while linking. Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by rahamin1** [facebook/react-native#22890]
## Environment (I am using react-native 0.57.0):
 Output from `react-native info`:
```
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
      Memory: 1.91 GB / 7.87 GB
    Binaries:
      Yarn: 1.9.4 - C:\Users\yossi\AppData\Roaming\npm\yarn.CMD
      npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.1.0.0 AI-173.4720617
```

## Description

- My project was up and running
- I added the package `react-native-check-app-install` (using yarn)
- When I tried to run `react-native link` I got the following error:
```
rnpm-install info Linking react-native-check-app-install android dependency
rnpm-install ERR! Something went wrong while linking. Error: ENOENT: no such file or directory, open 'C:\esites-PI\mobile-ui\PriceInsight_app\android\app\src\main\java\eu\<appname>\mobileapp\MainApplication.java'
Please file an issue here: https://github.com/facebook/react-native/issues
```

The problem seems to be that my `MainApplication.java` file is in `android\app\src\main\java\trade\<appname>\mobileapp` and `android\app\src\main\java\eu` does not exist

**Comment by rahamin1** [comment]
I have - it is under 'Environment'

**Comment by saurabhkacholiya** [comment]
Solved it by below mentioned steps:-
1) deleted the project dir
2) cloned the project 
3) npm i
4) react-native link
