### ISSUE TITLE
UIScrollView decelerationRate default should be 'normal' instead of 'fast'

### ISSUE THREAD

**Issue by petekp** [facebook/react-native#22900]
## Environment
```
React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
      Memory: 6.41 GB / 32.00 GB
      Shell: 2.7.1 - /usr/local/bin/fish
    Binaries:
      Node: 8.9.4 - ~/.nvm/versions/node/v8.9.4/bin/node
      Yarn: 1.12.3 - ~/.yarn/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.9.4/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.0/10L213o - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: 0.57.7 => 0.57.7
```

## Description
The default scrollview deceleration rate for the WebView in iOS was changed from 'fast' to 'normal' in iOS 11 (prompted by the emergence of Google AMP-powered sites which used a workaround to enable 'normal' deceleration to make scrolling feel more native), but [React Native still defaults to 'fast'](https://github.com/facebook/react-native/blob/f8bc32abb0d4cb1d87d07d57b29b427c5e05378d/Libraries/Components/WebView/WebView.ios.js#L212), which is the higher-friction, less native feeling deceleration.

See [UIScrollViewDecelerationRate docs](https://developer.apple.com/documentation/uikit/uiscrollviewdecelerationrate?language=objc) and [webkit changelog](https://trac.webkit.org/changeset/211197/webkit). More info on this history of this change: https://www.macobserver.com/analysis/apple-plans-change-scrolling-safari/

Happy to submit a PR to update this if it's a welcome change.

**Comment by ericlewis** [comment]
The new repo for webview is over here: https://github.com/react-native-community/react-native-webview

**Comment by petekp** [comment]
@ericlewis Thanks! I believe this is an upstream issue in the RN scrollview component. Could be wrong.
