### ISSUE TITLE
devaultValue for text area or text input

### ISSUE THREAD

**Issue by sidhacks** [facebook/react-native#2291]
I am trying to edit a document I retrieved from the database. 

The "default value" (for eg "First Name, Last Name") for text area and text input isn't working in react-native. 

Here is the code:

<--View>
    <--TextInput style={[styles.textInput,{color:'blue'}]} defaultValue="First Name, Last Name" />
<--/View>

Is this a known issue? Are there any workarounds at present?

**Comment by ide** [comment]
Use value instead of defaultValue, since TextInput is now a controlled component.

**Comment by sidhacks** [comment]
Thanks James. It works!
