### ISSUE TITLE
DatePickerIOS Date Props issue in release build

### ISSUE THREAD

**Issue by MuhammadUzair** [facebook/react-native#22912]
## Environment

React Native Environment Info:
System:
OS: macOS High Sierra 10.13.6
CPU: (4) x64 Intel(R) Core(TM) i7-2640M CPU @ 2.80GHz
Memory: 33.43 MB / 8.00 GB
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 8.11.3 - /usr/local/bin/node
Yarn: 1.9.4 - /usr/local/bin/yarn
npm: 5.6.0 - /usr/local/bin/npm
SDKs:
iOS SDK:
Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
Android SDK:
API Levels: 23, 25, 26, 27, 28
Build Tools: 23.0.1, 26.0.3, 27.0.3, 28.0.2
System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-24 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
IDEs:
Android Studio: 3.1 AI-173.4907809
Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
npmPackages:
react: 16.6.3 => 16.6.3
react-native: 0.57.8 => 0.57.8
npmGlobalPackages:
react-native-cli: 2.0.1
react-native-git-upgrade: 0.2.7
react-native-image-picker: 0.26.10

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

## Description
Date props not show Specify (defined Initial date ) date in picker.In debug build it work fine but in release build picker show today date.
Mobile OS=IOS

## Reproducible Demo code
import {View,DatePickerIOS} from 'react-native';

 <View style={{flex: 1, justifyContent: 'center'}}>
     <DatePickerIOS
       date={new Date('12-30-1980')}
        onDateChange={this.setDate}
        mode="date"
         />
  </View>

**Comment by uzairkhan01** [comment]
Also tried with new version but facing issue.In new version, issue in debug build also

*react-native info*

  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i7-2640M CPU @ 2.80GHz
      Memory: 33.43 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.3 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 26.0.3, 27.0.3, 28.0.2
        System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-24 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.57.8 => 0.57.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      react-native-image-picker: 0.26.10

**Comment by MuhammadUzair** [comment]
Still exist in new version

**Comment by ericlewis** [comment]
@MuhammadUzair `new Date('12-30-1980')` isn't a valid date, so it returns undefined. If you would like to parse dates like this, I would suggest checking out [moment](https://momentjs.com/).

**Comment by MuhammadUzair** [comment]
![Screen Shot 2019-04-18 at 12 46 12 PM](https://user-images.githubusercontent.com/15572020/56345200-97da3100-61d8-11e9-9195-3192bdc9ee37.png)

@ericlewis It is a valid date, I tried in console. For the moment what date format is required for DatePickerIOS Date Props (like DD/MM/YYYY)?

**Comment by MuhammadUzair** [comment]
Thanks @ericlewis .I Fixed this issue by change the date formate in  YYY-MM-DD .
