### ISSUE TITLE
autoFocus not working in navBar

### ISSUE THREAD

**Issue by Aletagro** [facebook/react-native#22920]
## Environment
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz
      Memory: 409.48 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.4.0 - ~/.nvm/versions/node/v11.4.0/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 26, 28
        Build Tools: 26.0.3, 27.0.3, 28.0.2, 28.0.3
        System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-25 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: 0.57.8 => 0.57.8
    npmGlobalPackages:
      react-native-git-upgrade: 0.2.7

## Description
I use textInput in navbar with autofocus. In version 0.57.4, everything works fine. But when updating 0.57.8, there was a problem, when opening the screen, the keyboard does not appear. If you use exactly the same textInput outside the navbar, then everything works fine.

**Comment by RSNara** [comment]
Thanks for reporting this problem! 

Can you provide a minimal repro of this bug? That would help tremendously in getting to the bottom of this.

**Comment by Aletagro** [comment]
Here is such a component. When it is in navbar, autofocus does not work, and when outside of it, everything is fine. If it helps, then I use "react-navigation": "^ 3.0.9"

`class NavBarComponent extends PureComponent<Props, State> {
  state = {
    cityName: this.props.city ? this.props.city.name : ''
  }

  handleCitySearch = (cityName) => {
    this.setState({cityName: cityName})
    if (cityName.length >= charsCountForCitySearch) {
      this.props.getCity(cityName)
    }
  }

  handleBackPress = () => this.props.navigation.goBack(null)

  render () {
    return (
      <View style={Styles.container}>
        <TouchableOpacity
          onPress={this.handleBackPress}
          hitSlop={{top: 12, bottom: 12, left: 12, right: 12}}
        >
          <ArrowBack />
        </TouchableOpacity>
        <TextInput
          autoFocus
          placeholderTextColor={Colors.gray}
          value={this.state.cityName}
          onChangeText={this.handleCitySearch}
          placeholder='Поиск'
          selectionColor={Colors.blue}
          underlineColorAndroid='transparent'
        />
      </View>
    )
  }
}`
