### ISSUE TITLE
Integrating react native with existing Android app

### ISSUE THREAD

**Issue by dogganidhal** [facebook/react-native#22929]
I was following the guide from the official documentation of react native [Here](https://facebook.github.io/react-native/docs/integration-with-existing-apps.html) to integrate react native into my native Android app, it seems that the guide is outdated, since it references version 0.52 of react native, so I do get compiler errors in the following code snippet, 

    @Override
    protected void onPause() {
        super.onPause();
        if (mReactInstanceManager != null) {
            mReactInstanceManager.onHostPause(this);
        }
    }

    @Override
    protected void onResume() {
        super.onResume();
        if (mReactInstanceManager != null) {
            mReactInstanceManager.onHostResume(this, this);
        }
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        if (mReactInstanceManager != null) {
            mReactInstanceManager.onHostDestroy(this);
        }
        if (mReactRootView != null) {
            mReactRootView.unmountReactApplication();
        }
    }

The compiler doesn't recognise the methods `onHostDestroy`, `onHostResume`, `onHostPause` and `unmountReactApplication`, I ran into no deprecation message ...

**Env**

React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
      Memory: 30.74 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.2 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 24.0.2, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.1, 27.0.3, 28.0.1, 28.0.2, 28.0.3
        System Images: android-24 | Google Play Intel x86 Atom, android-26 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.7.0 => 16.7.0
      react-native: ^0.57.8 => 0.57.8
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1

**Comment by hramos** [comment]
It looks like you picked the Docs template when opening your issue. Can you use the Bug Report Issue template instead? Visit https://github.com/facebook/react-native/issues/new/choose, or edit your issue to follow https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
