### ISSUE TITLE
Question on "collapsed property"

### ISSUE THREAD

**Issue by sidhacks** [facebook/react-native#2292]
We are using react native collapse component. 
We have several collapsible elements in the navigation page we are building.

In the beginning collapsed property is set to true. When one of the navigation elements is clicked, we are setting the collapsed property to false. This opens up ALL the navigation elements on the navigation page. 

Is there any way we can restrict the opening of the sub-nav elements only to the nav elements we clicked on?

**Comment by ide** [comment]
What is the collapse component? It sounds like this could be a 3rd party component?

**Comment by sidhacks** [comment]
Yes react-native-collapsible it is a third party component. I have posted this issue on the developer's support page.
Thanks for your response James.
