### ISSUE TITLE
Release build creating stuck for ios and android

### ISSUE THREAD

**Issue by vvusts** [facebook/react-native#22928]
## Environment
  React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (4) x64 Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
      Memory: 31.72 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 9.5.0 - /usr/local/bin/node
      npm: 4.4.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27
        Build Tools: 19.1.0, 20.0.0, 21.1.2, 22.0.1, 23.0.1, 23.0.2, 23.0.3, 24.0.0, 24.0.1, 24.0.2, 24.0.3, 25.0.0, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.3
        System Images: android-25 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.57.8 => 0.57.8 

## Description
This problem started when I upgraded from 0.56.
I gone through similar issues I reinstalled watchman, clear cache, manually delete build data etc.
But when I try to create release in xcode or from terminal for android it stuck:
**for android about: 22%
for ios: last step executing scripts last forever**
```
> Task :app:bundleReleaseJsAndAssets 
warning: the transform cache was reset.
Loading dependency graph, done.
<==-----------> 22% EXECUTING [6m 37s]
> :app:bundleReleaseJsAndAssets
```

**Comment by rickhanlonii** [comment]
Hey @vvusts, thanks for filing and sorry for the delay

Unfortunately there's not enough information here for us to act on. If you are still experiencing this issue and have more information on how to reproduce I'm happy to re-open and take a look 👍
