### ISSUE TITLE
About `metro-react-native-babel-preset`, I want to know something 

### ISSUE THREAD

**Issue by relign** [facebook/react-native#22926]
Babel7 use `@babel/preset-env`  allows you to use the latest JavaScript without needing to micromanage which syntax transforms (and optionally, browser polyfills) are needed by your target environment(s), and `useBuiltIns` can handles polyfills easy. why not use in metro-react-native-babel-preset? And done it by ourself.

**Comment by kelset** [comment]
I suggest you ask this question in the Metro repository.
