### ISSUE TITLE
IOS Modal not closing using Promises or SetTimeout in setState callback

### ISSUE THREAD

**Issue by Zver64** [facebook/react-native#22922]
## Environment
      OS: macOS 10.14.2
      CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
      Memory: 29.28 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.14.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.57.8 => 0.57.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-create-library: 3.1.2

## Description
I have two modals:
Modal1: 
```
<Modal
          animationType="slide"
          transparent={false}
          visible={this.state.modal1}
          onRequestClose={() => {
            
          }}>
            <View style={styles.modal}>
              <Text>Modal1</Text>
              <Button title={'test'} onPress={()=>{
                this.setState({modal1: false, modal2: true}, ()=>{
                      new Promise(resolve => {
                        setTimeout(()=>{
                          resolve('tested')
                        }, 100) // does not work on ios. But 1000ms works well.
                      }).then(()=>{
                        this.setState({loader: false})
                      })

                    })
              }}/>
            </View>
          </Modal>
```
Modal2: 
```
<Modal
          animationType="slide"
          transparent={false}
          visible={this.state.modal2}
          onRequestClose={() => {
            
          }}>
            <View style={styles.modal}>
              <Text>Modal2</Text>    
            </View>
          </Modal>
```
 When I click the button in the first modal i want to close it, open the second Modal, do some asynchronous task and close the second Modal when the task is finished. It works well on android, but not on IOS. It only works if the task's execution time is long enough (around 600ms and above). Otherwise the second Modal Does not close, and I have to restart the app to close it. I have also tried SetTimeout instead of Promise just to test - no luck.
```
setTimeout(()=>{
                        this.setState({loader: false})
                      }, 100) // doesn't work either
```

## Reproducible Demo

Here is my demo: https://snack.expo.io/@zver64/laughing-strawberries

**Comment by Zver64** [comment]
> Can you run `react-native info` and edit your issue to include these results under the **Environment** section?
> 
> If you believe this information is irrelevant to the reported issue, you may write `[skip envinfo]` under **Environment** to let us know.

I have already attached my info.

**Comment by Zver64** [comment]
> it does not contain the necessary environment info

Why, doesn't it? I pasted react-native info output into the Enviroment section. What else do i have to do?

**Comment by dirkpostma** [comment]
@Zver64 

Just a guess: perhaps the bot is scanning for 

```
React Native Environment Info:
    System:
```

You didn't include these first two lines of `react-native info`
