### ISSUE TITLE
[Performance] Memory and CPU usage issues on idling

### ISSUE THREAD

**Issue by pistou** [facebook/react-native#22932]
## Environment
React Native Environment Info:
    System:
      OS: Windows 10
      CPU: x64 Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
      Memory: 11.62 GB / 15.90 GB
    Binaries:
      Yarn: 1.12.3 - D:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.1.0 - C:\Program Files\nodejs\npm.CMD

react 16.6.0
react-native 0.57.4

## Description
I'm having some weird issues with the memory and CPU usage, especially when the app is idling ("minimized" in background, not killed).
I'm using Android Studio's profiler and here's what I have:
![memory issues](https://user-images.githubusercontent.com/6703711/50918707-42f08700-1441-11e9-9289-925d6a8f32f3.jpg)
The vertical separator is the moment when I put my app in the background (openning another app like GMail or whatever).

Am I mistaken or the Memory usage should have go down at this point? I'm not sure about this.

What I don't understand is why do I have a peak in CPU usage and power on a regular basis?
Even if it's like 2-6%, it's still more than I would expect, as the App is currently not running?

Any clue on what is going on?

**Comment by dulmandakh** [comment]
IIRC, Android apps don't release memory when enters background mode. But you can do it voluntarily using AppState events and release some memory.
