### ISSUE TITLE
Is there any plans to add WebCrypto API to React-Native?

### ISSUE THREAD

**Issue by pedrouid** [facebook/react-native#22933]
A lot of quick hacks and libraries try to either polyfill or build their own solutions for crypto but browsers already have a good library that is super performant for cryptography.

Is there any plans to add WebCrypto API to the React-Native environment?

**Comment by newyankeecodeshop** [comment]
This might be a better question to post here:
https://github.com/react-native-community/discussions-and-proposals

It's a good question, but I think given the emphasis on keeping the core RN library "slim", I expect the best answer will be for the community to endorse a `react-native-crypto` library. This can then have its own release cycle and support multiple RN releases.

**Comment by pedrouid** [comment]
Thanks @newyankeecodeshop 👍 just did

**Comment by skiqh** [comment]
> Thanks @newyankeecodeshop 👍 just did

For anybody looking for the respective proposal by @pedrouid: 
https://github.com/react-native-community/discussions-and-proposals/issues/83
