### ISSUE TITLE
Bad scrolling on android 9

### ISSUE THREAD

**Issue by esmat-nawahda** [facebook/react-native#22938]
Environment:
  OS: Windows 10
  Node: 8.11.2
  Yarn: 1.9.4
  npm: 6.4.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.1.0.0 AI-173.4907809

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: ^0.54.0 => 0.54.4

## Description
When trying to scroll up fast, the view starts scrolling in the opposite direction. (this is happening on Android 9 only and after releasing the finger)

**Comment by esmatptr** [comment]
Updated

**Comment by felixus95** [comment]
It does exist with 0.57

**Comment by felixus95** [comment]
React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 2.32 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.13.0 - /usr/local/opt/node@10/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/opt/node@10/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 26, 27
        Build Tools: 27.0.3, 28.0.0, 28.0.2, 28.0.3
        System Images: android-23 | Intel x86 Atom, android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.1 => 16.6.1
      react-native: 0.57.5 => 0.57.5
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

**Comment by gsunsnackv** [comment]
@esmatptr  @felixus95 When I have a few images the scroll is extremely choppy (ScrollView or FlatList), are you experiencing this? Also Android 9.0 only https://github.com/facebook/react-native/issues/22744

**Comment by avalko** [comment]
I ran into the same problem on Android 9 ....
Any idea how to deal with this?

**Comment by avalko** [comment]
> @felixus95 , I switch to https://github.com/Flipkart/recyclerlistview and that helps

on my oneplus with android 9 all the components (react FlatList, ScrollView, react-native-gesture-handler FlatList, recyclerlistview...) that i tried to behave like this...

**Comment by xgAnd** [comment]
#22925 in this I see the author say upgrade the react-native version is not fixed how to deal this .some experience?

**Comment by Elf2707** [comment]
Have the same issue. I tried to use ReactScrollView.java (unfortunately can't update rn), but it didn't help.

**Comment by kabus202** [comment]
any updates on this? still exist in 59.8

**Comment by meghaptg** [comment]
any leads?

**Comment by rickhanlonii** [comment]
@kabus202 @meghaptg if you could post a reproduction repo with clear steps to reproduce it will be more likely that someone can look into it and give an update

**Comment by fangasvsass** [comment]
@kabus202 Did u fixed it  ,0.59.10 still exist

**Comment by kabus202** [comment]
@fangasvsass I'm still using 56.1 and it's working without any problems. Which android version/phone etc.. do u have?

**Comment by fangasvsass** [comment]
@kabus202  which file to 0.56.1 ? or revert react native version to 0.56.1

**Comment by fukuball** [comment]
0.60.5 still exist, Android 9 only.

**Comment by HarshitMadhav** [comment]
I am using 0.61.2 version of react-native and this issue is only occurring in OnePlus 5T device.

**Comment by r0b0t3d** [comment]
I am using nexus 6P with custom ROM android 10.
When I launch my app, list works well. But when coming back from detail screen, list lost fling/momentum

![bug scroll](https://user-images.githubusercontent.com/8109285/75089104-079f1200-5588-11ea-9254-9e97b22893b3.gif)

**Comment by piousdeer** [comment]
@r0b0t3d I've hit the same problem. Were you able to solve it?

**Comment by r0b0t3d** [comment]
@piousdeer Not yet, I don't have much time. you could try this https://github.com/facebook/react-native/issues/22925#issuecomment-471995610.

**Comment by HarshitMadhav** [comment]
I am using react native 0.62.2 v and I can confirm this bad scrolling is not resolved.

**Comment by simonxcheng** [comment]
The problem is still happening with React Native 0.61.0 on Android Pixel 2XL, Moto 4G, etc.

**Comment by kperreau** [comment]
@simonxcheng same problem on oneplus 5

**Comment by luckcoding** [comment]
same problem +1

**Comment by fabriziobertoglio1987** [comment]
https://stackoverflow.com/help/how-to-ask

**Comment by IoanaBdn** [comment]
Any update on this issue?

**Comment by devscipline** [comment]
Still having the same issue on Android 9 with RN 0.64.3

**Comment by vimal2705** [comment]
hello, community,
I faced the same issue while developing  on Motorola device android version 9
as the app starts  home screen scroll works buttery  smooth but as I navigate to  another  screen and come back to the same home screen  scroll gets stuck alternatively  and 
** then I caught something which solved my issue  **

1.  the scroll in the second screen which I navigate I make that whole screen scroll horizontal  
2. just after that I not faced it again on my home screen

**Comment by wintersprouter** [comment]
still have this issus with RN 0.64.2

**Comment by Bej-Technologies** [comment]
Same issue here, happens on a Samsung A33
