### ISSUE TITLE
Error occurred, shutting down websocket connection:  when update RN

### ISSUE THREAD

**Issue by s349856186** [facebook/react-native#22942]
when i update RN to 0.57.8
xcode show error:
2019-01-10 18:07:42.924 [info][tid:com.facebook.react.WebSocketExecutor][RCTInspectorPackagerConnection.m:304] Error occurred, shutting down websocket connection: Websocket exception Error Domain=NSPOSIXErrorDomain Code=60 "Operation timed out" UserInfo={_kCFStreamErrorCodeKey=60, _kCFStreamErrorDomainKey=1}

and node command(npm start) logcat ,
::ffff:192.168.3.12 - - [10/Jan/2019:10:10:01 +0000] "GET /assets/node_modules/antd-mobile/lib/toast/images/fail@2x.png?platform=ios&hash=68f5d8a7810b3bc63f955cfa70888516 HTTP/1.1" 200 - "-" "MyRNxx/2.5 CFNetwork/897.15 Darwin/17.5.0"
will be show fail tips when network error, but "fail@2x.png" is exist, I don't understand the log.

## Environment
Run `react-native info` in your terminal and paste its contents here.
React Native Environment Info:
    System:
      OS: macOS 10.14.1
      CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
      Memory: 30.38 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.9.0 - /usr/local/bin/node
      npm: 6.5.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 14, 15, 16, 17, 18, 19, 21, 22, 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.1, 27.0.3
        System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.0 AI-171.4408382
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.6.3 => 16.6.3 
      react-native: ^0.57.8 => 0.57.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by ziyoshams** [comment]
I get this error after the app runs for a while, and then the live reloading gets disabled.

**Comment by HaloWang** [comment]
Same issue

# Env

```
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
      Memory: 27.79 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.1.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 19, 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.3, 25.0.2, 26.0.2, 27.0.3, 28.0.3
        System Images: android-23 | Intel x86 Atom, android-23 | Intel x86 Atom_64, android-23 | Google APIs ARM EABI v7a, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-27 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: * => 16.8.6 
      react-native: * => 0.59.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

**Comment by masoodyngster** [comment]
Error occurred, shutting down websocket connection: Websocket exception Error Domain=NSPOSIXErrorDomain Code=50 "Network is down" UserInfo={_kCFStreamErrorCodeKey=50, _kCFStreamErrorDomainKey=1}

please help me to resolve the above error.
It is coming in iOS but working in android

**Comment by getavinashm** [comment]
Has anyone found a solution to this issue ? I am getting the error too....
[tid:com.facebook.react.WebSocketExecutor][RCTInspectorPackagerConnection.m:309] Error occurred, shutting down websocket connection: Websocket exception Error Domain=kCFErrorDomainCFNetwork Code=2 "(null)"
