### ISSUE TITLE
WebView's Sibling Views does not render until user interaction

### ISSUE THREAD

**Issue by Rinkuk1993** [facebook/react-native#22940]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 30.38 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - ~/Library/.nvm/versions/node/v10.15.0/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/Library/.nvm/versions/node/v10.15.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.2, macOS 10.13, tvOS 11.2, watchOS 4.2
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 21.1.2, 23.0.1, 23.0.3, 25.0.0, 25.0.1, 25.0.2, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.3, 28.0.2, 28.0.3
        System Images: a...pis | Google APIs ARM EABI v7a Syste...
    IDEs:
      Android Studio: 2.0 AI-143.2739321
      Xcode: 9.2/9C40b - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.6.3 => 16.7.0 
      react-native: ~0.57.8 => 0.57.8 

Device Tested: Android (v4.4.x, 6.x, 8.x, 9.0)

Issue found in Production build as well as in development mode.

## Description
When there is a mainContainer having headView and Webview. The headView does not appear on the screen.
Code structure : 
```
// note key is used only for understanding purpose. In real code there is no key to each component
<View key='mainContainer'>
<View key='headView'>This is heading</View>
<Webview .... />
</View>
```
To solve the issue, I have to manually add zIndex to show headView component. But adding zIndex does not help in case of complex view structure and seems hacky.

The above code hierarchy without zIndex was working perfectly in v0.55.4 until I upgraded to 0.57.8 due to https://github.com/facebook/react-native/issues/17267

Maybe there is some bug introduced while fixing https://github.com/facebook/react-native/issues/11976

## Reproducible Demo
I feel this is straight forward. Since I have to create a new sample project, I will take the time to post the same.

**Comment by cpojer** [comment]
This issue has been moved to react-native-community/react-native-webview#437.
