### ISSUE TITLE
react-native code reuse (calling a component from external function)

### ISSUE THREAD

**Issue by mekatron** [facebook/react-native#2295]
I need to invoke a second component from the component I am in. 

Using the onPress event I need to render another component in same page as in react (shown below):

	React.render(<ProductDisplay />,document.getElementById("dynamic_space"));

	
In react-native:

/**
var first = React.createClass(){ 
     render:function(){  
		 <--View>  
			 <--Text>First Component</Text>
			 <--TextInput style={{borderWidth:1,borderColor:'red'}} onPress={getData()}/>  
         <--/View>       
		 }
	})   
 function getData(){
	<--second/> 
 }   
	 var second = React.createClass(){   
	 render:function(){  
		 <--View>   
		 <--ScrollView>   
		 <--Text>Second component</Text>
		 <--/ScrollView> 
		 <--/View>  
		 }     
	 })
**/
I intend to externalize the getData function as I need to use it multiple times. If I include the code in the calling component I run into the risk of replicating the same code over and over again.

**Comment by jaygarcia** [comment]
@sidhacks , for that type of method, just setup a singleton module that is included via require().

Alternatively, you can use the Mixin pattern: https://facebook.github.io/react/docs/reusable-components.html#mixins
