### ISSUE TITLE
error: bundling failed: SyntaxError: Unexpected token in JSON at position 0 at JSON.parse (<anonymous>)

### ISSUE THREAD

**Issue by sapariya2108** [facebook/react-native#22950]
I need help for solving the react-native error. When I create a react-native project using React-native init Project-Name and run the project in a mobile phone using react-native run-android, I got an error as below. I do not change any code however I get this error.
![capture](https://user-images.githubusercontent.com/43532682/50986885-051d5c80-152e-11e9-8a74-9f4d507266f1.PNG)

**Comment by Ruanyang2015** [comment]
me too
