### ISSUE TITLE
onKeyboardWillShow is called after keyboard opens.

### ISSUE THREAD

**Issue by nandiniparimi1107** [facebook/react-native#22969]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Run `react-native info` in your terminal and paste its contents here.
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
      Memory: 79.25 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.0.0 - /usr/local/Cellar/node/11.0.0/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.3
        System Images: android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.1 => 16.6.1 
      react-native: 0.57.7 => 0.57.7 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

## Description
I have a chat screen with TextInput at the bottom of the screen. I would like to have smooth animation when keyboard opens, but the keyboard opens before the onKeyboardWillShow is called.Hence there is a glitch/delay for the flatlist resize.

## Reproducible Demo
[Untitled.zip](https://github.com/facebook/react-native/files/2751836/Untitled.zip)

**Comment by rchanaud** [comment]
I have the same issue on React Native 0.58.4 with the [example code of the Keyboard doc](https://facebook.github.io/react-native/docs/keyboard#usage) only on iOS (on the iOS simulator).

**Comment by dulmandakh** [comment]
React Native is asynchronous, and it cannot ensure that event is delivered before UI change.
