### ISSUE TITLE
[Image] Add a resizeMode named 'fit'

### ISSUE THREAD

**Issue by aleclarson** [facebook/react-native#2296]
The new `resizeMode` would work similar to `cover`, but if the raw image dimensions are ever larger than both the `Image` width and height, it shrinks the image to fit at least one edge to the expected dimensions.

```coffee
# The width/height of the raw image.
[ 1000, 1000 ]

# The width/height of the Image component.
[ 320, 200 ]

# If the resizeMode is set to 'cover', the large raw image is kept as is.
# This results in an unacceptable amount of information getting cropped off.
[ 1000, 1000 ]

# If the resizeMode is set to 'fit', the large raw image is scaled
# down to fit as much content as possible without leaving whitespace.
[ 320, 320 ]
```

**Comment by ide** [comment]
"cover" should probably do what you're saying, and needs to support scaling down. This probably isn't very hard to add if someone wants to submit a PR.

cc @nicklockwood @a2.

**Comment by nicklockwood** [comment]
Yeah, this looks like it's just a bug in the resizing logic. I'll take a look at fixing it.

**Comment by aleclarson** [comment]
:+1:

**Comment by cyprusglobe** [comment]
:+1:

**Comment by janmonschke** [comment]
:+1:

**Comment by christopherdro** [comment]
@aleclarson Maybe I'm missing something but shouldn't setting resizeMode to `contain` do what your asking?

**Comment by aleclarson** [comment]
Any updates on this?

**Comment by satya164** [comment]
Related #4031

**Comment by nicklockwood** [comment]
I don't know specifically if/when this was fixed, but nobody else has reportes it on iOS, so I assume `contain` is working correctly. Issue #4031 relates to Android, which I suspect is unrelated to this issue since it predates the Android release :-)

**Comment by satya164** [comment]
@nicklockwood Yeah, just commented because the Android issue can refer to this one. Should have done the other way around :D

**Comment by aleclarson** [comment]
We could use a `resizeMode` that:
- scales down when the image is larger than the frame
- doesn't scale up when the image is smaller than the frame

Or maybe just a `resizeMode` that uses the image dimensions and centers the image within the frame.

Either one would help with centering icons within buttons.

The current workaround is to:
- set `style.width` and `style.height` of the `Image` to the exact size of the `.png`
- wrap the `Image` in a `View` that centers its children using `justifyContent` and `alignItems`

**Comment by aleclarson** [comment]
Oh, just realized that fb8340d is already in master! I'm using 0.22.2 at the moment. 👍

**Comment by aleclarson** [comment]
Oh, it looks like that only provides Android support. I guess I'll make a pull request that adds iOS support.
