### ISSUE TITLE
Xcode 10.1 : node_modules/react-native/third-party/glog-0.3.5/src/base/mutex.h:105:10: 'config.h' file not found

### ISSUE THREAD

**Issue by ajijoyo** [facebook/react-native#22968]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
 React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 34.65 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.9.0 - /usr/local/Cellar/node/10.9.0/bin/node
      npm: 6.4.1 - ~/.npm-packages/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 25, 26, 27
        Build Tools: 23.0.1, 25.0.2, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.0
        System Images: android-23 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: 0.57.8 => 0.57.8
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description
first create project with react-init ,`config.h` on folder `glog-0.3.5` is not generated, so i `./configure` and `config.h` is appear, but when i run, `config.h` disappear again.

## Reproducible Demo
just create new project with `react-native init project` trying run `react-native run-ios` and will require `config.h` and you need `./configure` that glog-0.3.5 folder, and it generated `config.h` but when `react-native run-ios` it will disappear again.

**Comment by zcgong** [comment]
Did `./configure` success ?

**Comment by ajijoyo** [comment]
yap,and `config.h` successfull created
<img width="725" alt="screen shot 2019-01-17 at 08 56 57" src="https://user-images.githubusercontent.com/10805529/51290264-ed663c80-1a35-11e9-97b7-7216557a04e7.png">
<img width="882" alt="screen shot 2019-01-17 at 09 00 27" src="https://user-images.githubusercontent.com/10805529/51290406-5b126880-1a36-11e9-91e7-535da3b31fef.png">

but when i run react-native run-ios, that `config.h` disappear again.

**Comment by zcgong** [comment]
Did you run `make && make install` ?  Look at `https://github.com/google/glog`

**Comment by VirenMohindra** [comment]
Nothing worked for me except building on a different mac with the same model. `make && make install for `glog`, the `ios-configure-glog.sh` inside the scripts folder in react-native modules, and also manually added the lines of code from here https://github.com/facebook/react-native/blob/v0.57.0/scripts/ios-configure-glog.sh#L44-L51

Copied the entire repository over including the build. Going to diff the `third-party` folder to see what changed and report back.

```bash
❯ react-native info

  React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 493.48 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.6.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14
      Android SDK:
        API Levels: 23, 26, 27, 28
        Build Tools: 27.0.3, 28.0.0, 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.7.0 => 16.7.0 
      react-native: ^0.57.8 => 0.57.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

**Comment by ajijoyo** [comment]
> Did you run `make && make install` ? Look at `https://github.com/google/glog`

cannot complete install maybe because i had rename Xcode apps to Xcode 10.1 
<img width="725" alt="screen shot 2019-01-21 at 11 54 14" src="https://user-images.githubusercontent.com/10805529/51453673-5f5ebe80-1d73-11e9-902d-334fa8a80917.png">

we dont have mac with same model, so i decided using latest project react native i have
> Nothing worked for me except building on a different mac with the same model. `make && make install for `glog`, the `ios-configure-glog.sh` inside the scripts folder in react-native modules, and also manually added the lines of code from here https://github.com/facebook/react-native/blob/v0.57.0/scripts/ios-configure-glog.sh#L44-L51
> 
> Copied the entire repository over including the build. Going to diff the `third-party` folder to see what changed and report back.
> 
> ```shell
> ❯ react-native info
> 
>   React Native Environment Info:
>     System:
>       OS: macOS 10.14.2
>       CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
>       Memory: 493.48 MB / 16.00 GB
>       Shell: 5.3 - /bin/zsh
>     Binaries:
>       Node: 11.6.0 - /usr/local/bin/node
>       Yarn: 1.13.0 - /usr/local/bin/yarn
>       npm: 6.5.0 - /usr/local/bin/npm
>       Watchman: 4.9.0 - /usr/local/bin/watchman
>     SDKs:
>       iOS SDK:
>         Platforms: iOS 12.1, macOS 10.14
>       Android SDK:
>         API Levels: 23, 26, 27, 28
>         Build Tools: 27.0.3, 28.0.0, 28.0.3
>         System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
>     IDEs:
>       Android Studio: 3.2 AI-181.5540.7.32.5056338
>       Xcode: 10.1/10B61 - /usr/bin/xcodebuild
>     npmPackages:
>       react: ^16.7.0 => 16.7.0 
>       react-native: ^0.57.8 => 0.57.8 
>     npmGlobalPackages:
>       react-native-cli: 2.0.1
> ```
