### ISSUE TITLE
Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.

### ISSUE THREAD

**Issue by lanjinli** [facebook/react-native#22963]
Require cycle: node_modules/react-native-popup-dialog/dist/type.js -> node_modules/react-native-popup-dialog/dist/components/DialogButton.js -> node_modules/react-native-popup-dialog/dist/type.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.

React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
      Memory: 295.50 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.13.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 21, 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.2, 26.0.2, 26.0.3, 27.0.3, 28.0.3
        System Images: android-23 | Intel x86 Atom_64, android-24 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: 0.57.8 => 0.57.8
    npmGlobalPackages:
      react-native-cli: 2.0.1

"dependencies": {
    "lottie-react-native": "^2.5.10",
    "react": "16.6.3",
    "react-native": "0.57.8",
    "react-native-amap-geolocation": "^0.3.2",
    "react-native-animatable": "^1.3.0",
    "react-native-image-crop-picker": "^0.21.3",
    "react-native-modalbox": "^1.6.0",
    "react-native-picker": "^4.3.7",
    "react-native-popup-dialog": "^0.16.6",
    "react-native-root-toast": "^3.0.2",
    "react-native-scrollable-tab-view": "^0.10.0",
    "react-native-storage": "^0.2.4",
    "react-native-svg": "^8.0.10",
    "react-native-svg-uri": "^1.2.3",
    "react-native-swiper": "^1.5.14",
    "react-navigation": "^2.18.3"
  }

<img width="384" alt="f028cabf-d10d-45ad-a547-7fc40997763b" src="https://user-images.githubusercontent.com/42225063/51038712-f185fa80-15ee-11e9-8c29-300994c96741.png">

**Comment by kelset** [comment]
Closing, this is a Metro warning - there is already an open conversation in the dedicated repro about muting these warnings.

**Comment by 7772** [comment]
> Closing, this is a Metro warning - there is already an open conversation in the dedicated repro about muting these warnings.

#20841

**Comment by eddiesmag** [comment]
here is the solution https://stackoverflow.com/a/55665566

**Comment by dorelv** [comment]
in your DialogButton.js file

import {NativeModules} from 'react-native';

//import react-native-popup-dialog from '/dist/type.js';
const react-native-popup-dialog = NativeModules.react-native-popup-dialog;
