### ISSUE TITLE
Problem with navigation bar Android

### ISSUE THREAD

**Issue by Jacky9425** [facebook/react-native#22978]
Hi, i am currently developing an app using react native and i have to say the most painful part is to implement a proper fullscreen app using react-native.

In my native-android code, i had coded the app to be fullscreen, without status bar and navigation bar (modern android devices now come with a navigation bar that can be hidden or shown in some app). The native code works well but once i include some components or plug-in components, the navigation bar re-appears and wont go away, or simply appears and disappears after re-render (dropdowns or popups) but it is very irritating in terms of user experience.

So i suggest that react native provides a component to hide the navigation bar completely without overriding the native codes of hiding it. There is `StatusBar.hidden();` hence there should also be one `NavigationBar.hidden();`. Sorry for long post because solving the issue is almost impossible if you needed some components in the app. I hope to see more improvements in the future. Thank you

**Comment by n00el** [comment]
+1, I have the similar issue, and the community keep avoiding this bug..

**Comment by Jacky9425** [comment]
You can try using react-native-immersive
Or natively create the fullscreen code block for Android
