### ISSUE TITLE
ScrollView with a TextInput Transform On Android

### ISSUE THREAD

**Issue by dested** [facebook/react-native#22976]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment

  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (16) x64 Intel(R) Core(TM) i7-5960X CPU @ 3.00GHz
      Memory: 31.87 GB / 63.90 GB
    Binaries:
      Yarn: 1.3.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 5.3.0 - ~\AppData\Roaming\npm\npm.CMD
    IDEs:
      Android Studio: Version  3.1.0.0 AI-173.4907809

## Description
A ScrollView with a TextInput that uses `transform:[{translateY:value}]` causes the ScrollView to not be able to faithfully position the TextInput in the view. This would not really be a huge issue if instead of forcing the scroll back to the top, it did nothing. I have only been able to reproduce this on Android, both real device and simulator. 

## Reproducible Demo
https://snack.expo.io/By9F5Ztf4

1. Open the app
2. Tap the red input box
3. Scroll to it so it is in view
4. Type 
5. On keystroke it scrolls it back to the top (presumably trying to scroll it into view.)

**Comment by cpojer** [comment]
You are right, this seems like this is a real issue but unfortunately it's unlikely anyone will be able to spend time on this anytime soon. I'm going to close this issue but we are more than happy to receive a pull request with a fix for this!
