### ISSUE TITLE
ImageBackground does not fill width on Android only

### ISSUE THREAD

**Issue by YoruNoHikage** [facebook/react-native#22975]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] ~Use the latest React Native release: https://github.com/facebook/react-native/releases~ I'm not using the latest release since I use it with expo (see snack down below) but I've read the latest changelogs and saw nothing related to this problem (maybe I'm wrong, please point it out if so)

## Environment
I don't think it would help a lot but here it is:
```
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
      Memory: 1.39 GB / 7.88 GB
    Binaries:
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338
```

## Description
`ImageBackground` does not fill the full width on Android when the app is either reloaded or paused and resumed. When I fully close the app and reopen it, the problem disappears.

![image](https://user-images.githubusercontent.com/969003/51088875-8874c300-1765-11e9-806e-0b8195637cd6.png)
Initial state

![image](https://user-images.githubusercontent.com/969003/51088900-d8ec2080-1765-11e9-9f56-7957113713d9.png)
After pause/resume or hot reload, the first element should fill its width.

No problem on iOS.

## Reproducible Demo
https://snack.expo.io/H1o4ogtM4

**Comment by patrickkempff** [comment]
It seems somehow that the asset is not repeated anymore

**Comment by SiSa68** [comment]
I have same issue with RN@0.59.4 on android
I also have this problem when keyboard appears or when I resize my app size
