### ISSUE TITLE
react-native link stuck 

### ISSUE THREAD

**Issue by mauricioscotton** [facebook/react-native#22986]
- [YES] Review the documentation: https://facebook.github.io/react-native
  - [YES] Search for existing issues: https://github.com/facebook/react-native/issues
  - [YES] Use the latest React Native release: https://github.com/facebook/react-native/releases
  - [YES] Googled A-LOT for this bug, nothing found.

## Environment 
Run `react-native info` in your terminal and paste its contents here.
![image](https://user-images.githubusercontent.com/34411735/51128175-24aed080-181f-11e9-9a7d-6560d19ee2fe.png)
![image](https://user-images.githubusercontent.com/34411735/51129753-2c707400-1823-11e9-9ae9-d99c4dda8c15.png)
[skip envinfo]

## Description
I've just started a new project and started developing the base classes...
So, I installed react-navigation (using yarn and also npm), and got a error regarding a State, so I've figured out that I was missing a "react-native link".
When I ran this command, It got stuck...
Nothing was shown on terminal.
So, I've added the 'rnpm' assets on package.json, and then after linking the assets it just hanged after:
"rnpm-install info Assets have been successfully linked to your project"

Then, I though I was kinda crazy, and googled tons of times, but no success.
After that, I've created this project "ABACATE" fresh to check if it was something with the new project that I had created before, but unfortunately it is a problem with the new version of react-native.

![image](https://user-images.githubusercontent.com/34411735/51128894-e31f2500-1820-11e9-92d6-aa376a2de7e2.png)
![image](https://user-images.githubusercontent.com/34411735/51128954-00ec8a00-1821-11e9-9397-854d280f4612.png)

Full Log here: https://pastebin.com/jm0A4GVC

## Reproducible Demo
react-native init YourProjectThatIsGoingToHangOnLink
react-native link

Package.json:
{
  "name": "ABACATE",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.6.3",
    "react-native": "0.57.8"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.51.1",
    "react-test-renderer": "16.6.3"
  },
  "jest": {
    "preset": "react-native"
  }
}

##REQUEST:
Can you guys please add a more detailed log/verbose on the command "react-native link"?
It will make easier for all of us to trace errors...

**Comment by mauricioscotton** [comment]
> Can you run `react-native info` and edit your issue to include these results under the **Environment** section?
> 
> If you believe this information is irrelevant to the reported issue, you may write `[skip envinfo]` under **Environment** to let us know.

Dear bot.
I know you are a bot.
But what about checking for images as well?!?! XD
Just joking

**Comment by hramos** [comment]
The command line tools have their own repository and issue tracker over at https://github.com/react-native-community/react-native-cli. Can you post your issue there?

**Comment by mauricioscotton** [comment]
> The command line tools have their own repository and issue tracker over at https://github.com/react-native-community/react-native-cli. Can you post your issue there?

Thanks a million for pointing that out!
https://github.com/react-native-community/react-native-cli/issues/89
