### ISSUE TITLE
[ScrollView] How can make a 'onScrollEnd' listener on ScrollView ?

### ISSUE THREAD

**Issue by mc-zone** [facebook/react-native#2299]
I want to make a general web page style component which include some introduction on the top and a Scroll-End-Load list on the bottom. Just like this.

![a jpg 001](https://cloud.githubusercontent.com/assets/4403937/9197763/c21702c0-4069-11e5-96dd-78e96d3fe192.jpg)

How can I know the scrollView has been scrolled to the end ? Is there some props on scrollView can be use ?  

And by the way,  Is it a bad usage if I put a ListView inside to ScrollView? ( I had try to do this , but feel uncomfortable when scrolling  )
So What is the best plan to put a dynamic loading list into a scrollView?

**Comment by paramaggarwal** [comment]
[onEndReached](http://facebook.github.io/react-native/docs/listview.html#onendreached)

**Comment by browniefed** [comment]
@brentvatne answered.

**Comment by ms88privat** [comment]
I kinda have the same question right now. How to do it with a ScrollView and not a ListView?  onEndReached gets only triggered by the ListView?

**Comment by ide** [comment]
Since you control the content that goes into a ScrollView, between computing the layout of said content and listening to scroll events you should be able to determine when you've reached the end of the ScrollView.

**Comment by ms88privat** [comment]
@ide Thank you, I will try that. I read about "renderHeader" in the ListView documentation. Does the Header stay fixed or does it scrolls away? Because that is the reason I have to use the ScrollView every time instead of the ListView. I need the "Header" to scroll naturally away.

**Comment by ide** [comment]
It's not fixed -- there's nothing special about the header really.

**Comment by mc-zone** [comment]
@ms88privat I've find the way that how to know `scrollEnd` in ScrollView just like this:

```javascript
onScroll={(e)=>{
    var windowHeight = Dimensions.get('window').height,
        height = e.nativeEvent.contentSize.height,
        offset = e.nativeEvent.contentOffset.y;
    if( windowHeight + offset >= height ){
        //ScrollEnd, do sth...
    }
}}
```

But now I've turn to use `ListView` , and `renderHeader` meets my need too. :smile:
