### ISSUE TITLE
Creating Standalone JS File For Each Native Component

### ISSUE THREAD

**Issue by TheSavior** [facebook/react-native#22990]
We are going to be generating native code from flow types in JS for our native components. In order to do this we need to have an individual JS file for each native component with complete flow types.

[Step 1](https://github.com/facebook/react-native/issues/21342), [Step 2](https://github.com/facebook/react-native/issues/21485), [Step 3](https://github.com/facebook/react-native/issues/21581), and [Step 4](https://github.com/facebook/react-native/issues/22100) have all been steps towards this goal.

In a bunch of our JS files we choose a component based on platform, typically looking something like this:
```
const SwitchNativeComponent: SwitchNativeComponentType =
  Platform.OS === 'android'
    ? (requireNativeComponent('AndroidSwitch'): any)
    : (requireNativeComponent('RCTSwitch'): any);
```

we want to change this code so that each `requireNativeComponent` call lives in its own file, thus changing the above code to look like this:

```
const SwitchNativeComponent: SwitchNativeComponentType =
  Platform.OS === 'android'
    ? require('AndroidSwitchNativeComponent')
    : require('RCTSwitchNativeComponent');
```

We need your help to make this change! 

# How to help
Pick one of the native components from the list below. Comment that you are working on that file and try to choose one that nobody else has commented about already.

Search the codebase for .js files that include that name. We are specifically looking for `requireNativeComponent` calls. So if you pick the component `AndroidCheckBox` we'd be looking for [this callsite](https://github.com/facebook/react-native/blob/24f8d4d3db483dab913486b3eb0b68572274eac7/Libraries/Components/CheckBox/CheckBox.android.js#L79-L81).

Create a new js file suffixed with 'NativeComponent' right next to the file that you found. In this case we'd create a `AndroidCheckBoxNativeComponent.js` file in `Libraries/Components/CheckBox`. 

We should move the call to requireNativeComponent from `Checkbox.android.js` to this file, including the flow type if one exists, or defining one if it doesn't. 

A pastebin of what I think the changes look like for this component are here: https://pastebin.com/RFpdT76V

One thing to note is that the majority of types necessary for these files shouldn't be imported from other files. Our codegen can't yet handle importing types from other files so in most cases I'd prefer to duplicate the type in this new file if it is needed. There are some exceptions to this that the codegen *can* handle that I'd expect most of these files will need. Specifically:
```
import type {ViewProps} from 'ViewPropTypes';
import type {SyntheticEvent} from 'CoreEventTypes';
import type {NativeComponent} from 'ReactNative';
```

If you come across other types that you think are sufficiently complex that you think shouldn't be duplicated tag me on your PR. Perhaps we should be adding knowledge of that type to the codegen. 😄 

# Testing Your Changes
For the highest confidence in your change, we recommend testing your changes using the RNTester App. Instructions to install and test the app are in the readme in the [RNTester directory](https://github.com/facebook/react-native/tree/master/RNTester). If your component is an Android component you should test it on Android. If it is iOS, then test on iOS. 😄   

# The Files
- [x] AndroidCheckBox
- [x] AndroidDialogPicker
- [x] AndroidDrawerLayout
- [x] AndroidDropdownPicker
- [x] AndroidProgressBar
- [x] AndroidSwipeRefreshLayout
- [x] AndroidViewPager
- [x] RCTActivityIndicatorView
- [x] RCTDatePicker
- [x] RCTInputAccessoryView
- [x] RCTMaskedView
- [x] RCTModalHostView
- [x] RCTPicker
- [x] RCTProgressView
- [x] RCTRefreshControl
- [x] RCTSafeAreaView
- [x] RCTSegmentedControl
- [x] RCTSlider
- [x] RCTSnapshot
- [x] RCTTabBar
- [x] RCTTabBarItem
- [x] ToolbarAndroid

**Comment by nd-02110114** [comment]
I'll take `AndroidDialogPicker ` .

**Comment by Naturalclar** [comment]
I'd like to contribute! I'll work on `AndroidDropdownPicker`

**Comment by ni3t** [comment]
Hello! `RCTDatePicker`

**Comment by VisibleMarkov** [comment]
Would love to help with `AndroidViewPager`

**Comment by vickywane** [comment]
I'll take RCTTabBar

**Comment by ajstrand** [comment]
I'll take the AndroidProgressBar.

**Comment by Chi-AnTai** [comment]
I will try to help with `RCTPicker`

**Comment by OdaDaisuke** [comment]
I’ll work on RCTSlider

**Comment by Leko** [comment]
I'll work on `RCTActivityIndicatorView`

**Comment by stu60610** [comment]
I'll take the `RCTSegmentedControl`

**Comment by sasurau4** [comment]
I'll take the `ToolbarAndroid`

**Comment by Leko** [comment]
I'll take the `RCTMaskedView`

**Comment by RCiesielczuk** [comment]
I'll take the `RCTProgressView` 😄

**Comment by Leko** [comment]
I'll work on `RCTTabBarItem`.

**Comment by dulmandakh** [comment]
does this mean that native files (java and objective c) for above components will be removed in the future?

**Comment by nerandell** [comment]
I will take `RCTRefreshControl`

**Comment by zsajjad** [comment]
I will take `RCTSlider`

**Comment by arcodergh** [comment]
I will take RCTSnapshot

**Comment by doniyor2109** [comment]
Hi. I will take `RCTInputAccessoryView `

**Comment by hramos** [comment]
You're all awesome ❤ Thanks for signing up to help.

**Comment by nerandell** [comment]
I will also pick up `AndroidSwipeRefreshLayout`

**Comment by emmajam** [comment]
I will take `RCTActivityIndicatorView` 😄

**Comment by nd-02110114** [comment]
I'll take `RCTModalHostView `

**Comment by HeinrichTremblay** [comment]
I'll give `AndroidDrawerLayout` a try ✌️

**Comment by mdvacca** [comment]
> does this mean that native files (java and objective c) for above components will be removed in the future?

No, this is required to autogenerate C++ code for components in Fabric. Java components will remain the same.

**Comment by TheSavior** [comment]
You all are so amazing. These PRs have been super helpful. It looks like nobody has claimed RCTActivityIndicatorView yet.

@vickywane, do you still plan on working on RCTTabBar?

**Comment by Naturalclar** [comment]
I'll work on `RCTSnapshotNativeComponent`

**Comment by cpojer** [comment]
This is amazing. In just 8 days, all of you helped us with this migration. Talk about moving fast!

Thank you *so so much*. This is seriously awesome and will help us make the communication between JS and native modules type safe.

**Comment by doniyor2109** [comment]
@reemtariqq Unfortunately all are taken. However you can search for issues with "Good first issue" label. There are many of them

**Comment by RSNara** [comment]
Thank you guys for all the work here! We have another opportunity to contribute to an RN project: TurboModules. Please check out #24875.
