### ISSUE TITLE
How do I run the packager for a new project?

### ISSUE THREAD

**Issue by jlongster** [facebook/react-native#23]
I created a brand new project, added the required files for ReactKit, and got all that working. Now I just need to run the packager. In `packager/packager.js` I see:

``` js
if (!options.projectRoot) {
  options.projectRoot = path.resolve(__dirname, '..');
}
```

But options is parsed from the command line arguments and I don't see the `projectRoot` command line arg. How do I run it, setting the path to my new project?

I temporarily fixed it by hardcoding the `projectRoot` to my project in there. A side issue: I was surprised to find that the bundler didn't seem to load files from that `node_modules` where I ran the packager (the error was pretty obscure). I needed to copy the `node_modules` directory into my new project also.

**Comment by soyrbk** [comment]
asdfghj
