### ISSUE TITLE
Could not open index.android.bundle: Permission denied

### ISSUE THREAD

**Issue by caishi3hao** [facebook/react-native#23015]
Blackview  A7
RAM： 224.43 MB
sd： 479.99 MB
Android： 7.0
 root ： no

HUAWEI P9 lite、P8 Lite
Moto E (4) Plus、Moto E (4)、
DOOGEE S60、DOOGEE MIX、
Blackview BV6000
also crash

"react-native": "^0.57.5",

Fatal Exception: com.facebook.jni.CppException
facebook::react::Recoverable: Could not open file/storage/emulated/0/Android/data/com.xxx.android/files/.rn/index.android.bundle: Permission denied
keyboard_arrow_up
arrow_right
com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromFile (TbsSdkJava)
com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromFile (TbsSdkJava:221)
com.facebook.react.bridge.JSBundleLoader$2.loadScript (TbsSdkJava:53)
com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle (TbsSdkJava:243)
com.facebook.react.ReactInstanceManager.createReactContext (TbsSdkJava:1116)
com.facebook.react.ReactInstanceManager.access$900 (TbsSdkJava:117)
com.facebook.react.ReactInstanceManager$5.run (TbsSdkJava:916)
java.lang.Thread.run (Thread.java:761)

File f = new File(jsBundleFilePath);
if (f.exists()) {
      builder.setJSBundleFile(jsBundleFilePath);
} else {
      builder.setBundleAssetName("index.android.bundle");
}

**Comment by caishi3hao** [comment]
File f = new File(jsBundleFilePath);
        if (f.exists()) {
            builder.setJSBundleFile(jsBundleFilePath);
        } else {
            builder.setBundleAssetName("index.android.bundle");
        }

**Comment by yongching** [comment]
+1
