### ISSUE TITLE
Shadow in navigator transition?

### ISSUE THREAD

**Issue by dubert** [facebook/react-native#2301]
Anyone know how I can add a shadow to the navigator transition? Right here?
(With Navigator, not NavigatorIOS)
![shaddodooowww](https://cloud.githubusercontent.com/assets/1843672/9253798/d99971f4-41ad-11e5-867d-ee84e24558a0.jpg)

Things I've tried:
* Style on the components
* `sceneStyle` on the Navigator
* adding shadows to the NavigatorSceneConfigs

**Comment by jozan** [comment]
I tried to do this as well couple of days ago without any success. For now I've set root component's background dark to fake scene going underneath but it gives ugly borders.

![Example of my solution with ugly borders](http://i.imgur.com/kk6Dj75.png)

**Comment by dubert** [comment]
@brentvatne @ericvicenti would either of you have some insight into how to do this?

**Comment by ericvicenti** [comment]
Navigator takes a sceneStyle prop. Have you tried putting shadow styles on it?

On Aug 13, 2015, at 8:25 AM, Luke Dubert <notifications@github.com<mailto:notifications@github.com>> wrote:


@brentvatne<https://github.com/brentvatne> @ericvicenti<https://github.com/ericvicenti> would either of you have some insight into how to do this?

**Comment by jozan** [comment]
Thanks @ericvicenti. It worked but it's not dynamic like in NavigatorIOS.

Remember to set `overflow: 'visible'` otherwise shadow doesn't show.

```js
<Navigator sceneStyle={{overflow: 'visible'}} />
```

**Comment by brentvatne** [comment]
@jozan - could you explain what you mean by dynamic?

**Comment by jozan** [comment]
@brentvatne Check shadow's opacity.

![Shadow opacity](http://i.imgur.com/funRG7i.png)

**Comment by brentvatne** [comment]
@jozan - good point! it changes as you move further to the left to be darker - that would be possible to do if the view was an `Animated.View` and Navigator provided some hook into the swipe events that would allow us to update that value accordingly

**Comment by jozan** [comment]
@brentvatne Yes, I hope Navigator starts using Animated soon.

:baby_chick:

**Comment by dubert** [comment]
UNBELIEVABLE. I've been trying to figure this out for 4 days. And all I needed was an `overflow: visible` prop.

One of the first things I tried was putting the shadow on `sceneStyle` but it didn't work because I didn't have `overflow: visible`.

Yeah, next step is making it dynamic. I'll poke around in Navigator and sceneConfigs to see what I can do.

**Comment by ericvicenti** [comment]
It might be a bumpy transition, but we are working on a new Navigator which fully utilizes Animated and allows scenes to perform their own animation

**Comment by dubert** [comment]
That's really exciting @ericvicenti. Will there be a prebuilt style that mimics iOS as closely as possible?

**Comment by dubert** [comment]
@jozan I got it working using sceneConfigs:
It's not 100% perfect, but it's pretty close.

in Libraries > CustomComponents > Navigator > NavigatorSceneConfigs:

```js

var NativeFadeToTheLeft = {
  transformTranslate: {
    from: {x: 0, y: 0, z: 0},
    to: {x: -Math.round(Dimensions.get('window').width * 0.3), y: 0, z: 0},
    min: 0,
    max: 1,
    type: 'linear',
    extrapolate: true,
    round: PixelRatio.get(),
  },
  opacity: {
    from: 1,
    to: 0.3,
    min: 0,
    max: 1,
    type: 'linear',
    extrapolate: false,
    round: 100,
  },
  translateX: {
    from: 0,
    to: -Math.round(Dimensions.get('window').width * 0.3),
    min: 0,
    max: 1,
    type: 'linear',
    extrapolate: true,
    round: PixelRatio.get(),
  },
};

var NativeFromTheRight = {
  opacity: {
    value: 1.0,
    type: 'constant',
  },
  shadowColor: {
    value: '#000000',
    type: 'constant',
  },

  shadowOpacity: {
    from: 0.1,
    to: 0.5,
    min: 0,
    max: 1,
    type: 'linear',
    extrapolate: false,
    round: 100,
  },

  shadowRadius: {
    from: 2,
    to: 6,
    min: 0,
    max: 1,
    type: 'linear',
    extrapolate: true,
  },

  transformTranslate: {
    from: {x: Dimensions.get('window').width, y: 0, z: 0},
    to: {x: 0, y: 0, z: 0},
    min: 0,
    max: 1,
    type: 'linear',
    extrapolate: true,
    round: PixelRatio.get(),
  },

  translateX: {
    from: Dimensions.get('window').width,
    to: 0,
    min: 0,
    max: 1,
    type: 'linear',
    extrapolate: true,
    round: PixelRatio.get(),
  },

};

// [...omitted]

var NavigatorSceneConfigs = {
  AsCloseToNativeIOSAsPossible: {
    ...BaseConfig,
    // We will want to customize this soon
    gestures: {
      jumpBack: BaseLeftToRightGesture,
      jumpForward: BaseRightToLeftGesture,
    },
    animationInterpolators: {
      into: buildStyleInterpolator(NativeFromTheRight),
      out: buildStyleInterpolator(NativeFadeToTheLeft),
    },
  },
  // [...omitted]
}

```

**Comment by jozan** [comment]
@dubert Thank! I will try that. Maybe you could create PR of the scene config and get it integrated.

@ericvincenti Would PR for Navigator be waste when reworked version is coming?

**Comment by ericvicenti** [comment]
It will be better to not to spend time adding features to the current Navigator while we work on the new one.

I'm sure that with the community's help, we can make the new Animated Navigator have a very close resemblance to the platform navigation

**Comment by brentvatne** [comment]
Nice one @dubert!

**Comment by jozan** [comment]
@ericvicenti Any estimation when the Animated Navigator will be released?

**Comment by Obooman** [comment]
@dubert Awesome!It's really a great solution(I don't like the scale animation) and thank you so much.Besides,I wrapped <Navigator/> with <View> element whose background color is black,and set the config opacity form 1 to 0.8.It seems like we have the darkened overlay ,something like this:
![overlay](https://cloud.githubusercontent.com/assets/9863282/11911905/4e42ebb2-a661-11e5-81e4-ebcf7a0bcc04.png)

**Comment by huangbong** [comment]
@dubert I'm getting errors like this on RN 0.27.0
```
View #1176 of type RCTView has a shadow set but cannot calculate shadow efficiently. Consider setting a background color to fix this, or apply the shadow to a more specific component.
```
Any solution? Lol - sorry about reviving an old issue.

**Comment by dubert** [comment]
@huangbong does setting a background color not work?

**Comment by huangbong** [comment]
@dubert does not
