### ISSUE TITLE
[Android] Unplugging USB cable from device in Battery saving mode will restart the application

### ISSUE THREAD

**Issue by asaravi** [facebook/react-native#23024]
## Description
Hey guys,

Seems like in Android 9, when the battery saver mode is enabled, unplugging and re-plugging the USB cable will restart the app from the first screen. It doesn't matter which screen you're in. 

This does not happen in Android 8.

This requires a real device to test this on.

## Reproducible Demo
any react-native app (even those currently in production), navigate to any page other than the first, then replug the USB cable while having battery saving mode enabled.

**Comment by buoyad** [comment]
@asaravi I just ran into this bug, I believe it's because battery saver also causes a `ui_night_mode` config change. Try adding `uiMode` to `android:configChanges` in the manifest for your activity (https://developer.android.com/guide/topics/manifest/activity-element#config).

**Comment by asaravi** [comment]
@buoyad thank you for the heads up! that seems to have fixed it.
