### ISSUE TITLE
PermissionsAndroid.getPermissions immediately resolves to "never_ask_again" when asking for geolocation permissions

### ISSUE THREAD

**Issue by doronoded** [facebook/react-native#23021]
## Environment
React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
      Memory: 1.45 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.2 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-27 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.1 => 16.6.1
      react-native: 0.57.7 => 0.57.7
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description
Asking permission for geolocation for Android resolves to "never_ask_again" even before prompting the request permission dialog when asking for geolocation service permissions.

## Reproducible Demo
`import {PermissionsAndroid} from "react-native";
const granted = await PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.ACCESS_COARSE_LOCATION);
alert (granted);`

If you run this code, in an app, You'll see the alert with the text "never_ask_again" before prompting the user for permission.

**Comment by doronoded** [comment]
By the way, asking for "fine" location, works just fine.

**Comment by german970814** [comment]
Same issue v0.59.4

**Comment by german970814** [comment]
Is there any updates about this issue?

**Comment by CMontAlv** [comment]
Facing the same issue, don't have a way to wait for the user to deny or allow access since the promise returned by `PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.ACCESS_COARSE_LOCATION)` gets immediately resolved with the previous answer the user has given.

**Comment by german970814** [comment]
Doing some test this issue occurs on API 28-. API Q works well
