### ISSUE TITLE
SSL Error using Android API 19 since OkHttp upgrade

### ISSUE THREAD

**Issue by aouaki** [facebook/react-native#23023]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
  React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 358.91 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        API Levels: 23, 24, 25, 26, 27
        Build Tools: 23.0.1, 23.0.2, 24.0.0, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 27.0.3
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1
      react-native: 0.56.x => 0.56.1

Also had the issue with react-native 0.57.8

## Description
When doing a simple GET HTTPS request to our server (www.dashdoc.eu) on a 4.3 Android device, I'm facing an SSL Error:
`ssl23_get_server_hello sslv3 alert handshake failure`

It works fine with google.fr and some other domains I tried, but with our server it didn't.

However, the request to our server went fine with react-native 0.46. After a lot of investigation, I found that downgrading OkHttp to 3.9.0 fixed the issue.

To do that, I added this code to my app/build.gradle:
```gradle
    implementation ("com.squareup.okhttp3:okhttp:3.9.0") {
        force = true;
    }
    implementation ("com.squareup.okhttp3:okhttp-urlconnection:3.9.0") {
        force = true;
    }
```

 I don't know if this is an issue from react-native or OkHttp. It may be linked to the way react-native fixes a bug on Android API 16-19 there : https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/modules/network/OkHttpClientProvider.java#L71

## Reproducible Demo
Install a simple react-native app and try to fetch https://www.dashdoc.eu/ on a 4.3 Android device, you should get an SSL Error.
```javascript
fetch("https://www.dashdoc.eu").then(
    response => {
        console.warn("response", response);
    },
    error => {
        console.warn("error", error);
    }
);
```

Cheers

**Comment by dulmandakh** [comment]
I think that it's unfixable, or we don't want to degrade HTTPS secure cipher requirements. Please see https://github.com/square/okhttp/issues/3894
