### ISSUE TITLE
Weird Reversal of Font Styles / Font Styles being overridden

### ISSUE THREAD

**Issue by barnesheaton** [facebook/react-native#23026]
## Environment
```
System:
      OS: macOS 10.14.2
      CPU: x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
      Memory: 78.00 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 9.11.2 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: ^4.2.0-alpha.4 => 4.2.0-alpha.4 
      react: 16.5.2 => 16.5.2 
      react-native: 0.57.1 => 0.57.1 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

## Description
1. Applying `fontStyle: 'italic'` overrides any use `fontWeight`
2. Using a particular `fontFamily` doesn't result in that font being displayed correctly
3. Just applying `fontWeight: '${number}'` sometimes results in an italic style being applied

Here I am using the react-native Text component with the specific fontFamily listed below (called subFonts maybe?):
```
<Text
   style={{
       fontFamily: 'CentraNo2-${number}',
       fontSize: 40 
    }}
>
  CentraNo2-${number}
</Text>
```

![simulator screen shot - iphone 6 - 2019-01-16 at 12 49 28](https://user-images.githubusercontent.com/39313406/51275997-b9850b80-1990-11e9-948c-9597fa243803.png)

The issue is that all the fonts that end in `6` should be Italic whereas the fonts that end in `5` should be regular. And this is indeed the case when looking at these fonts in the the xCode project or an Application like FontBook on MacOS. But here, it seems arbitrary weather BOTH bold and and italic versions of one weight will end up being one or the other.

And here I am using the (Base / Master / Parent not sure what its called)? fontFamily name like so:
```
<Text
   style={{
       fontFamily: 'Centra No.2',
       fontSize: 40 
       fontWeight: '${some_font_weight}',
       fontStyle: {'italic' || void},
    }}
>
  CentraNo2-${number}
</Text>
```
![simulator screen shot - iphone 6 - 2019-01-16 at 13 00 13](https://user-images.githubusercontent.com/39313406/51276008-bf7aec80-1990-11e9-9a71-74304d078bdf.png)

And in this case:
 1. Applying `fontStyle: 'italic'` overrides any use `fontWeight`
... and ... 
2. Just applying `fontWeight: '${number}'` sometimes results in an italic style being applied

## xCode
<img width="518" alt="screen shot 2019-01-16 at 1 01 43 pm" src="https://user-images.githubusercontent.com/39313406/51276507-1cc36d80-1992-11e9-817b-dbd52a094d5b.png">
<img width="254" alt="screen shot 2019-01-16 at 1 02 10 pm" src="https://user-images.githubusercontent.com/39313406/51276533-31076a80-1992-11e9-9885-cd5c4d140ff5.png">
All linked properly
<img width="442" alt="screen shot 2019-01-16 at 1 04 08 pm" src="https://user-images.githubusercontent.com/39313406/51276547-3c5a9600-1992-11e9-9539-a8c24cecbd76.png">

**Comment by dulmandakh** [comment]
Hello there 👋 this issue doesn't have a repro (which means, a `react-native init`-ed project with the minimal changes that leads to creating the same issue you are reporting). Unfortunately, I have no way of helping you in a meaningful way – there is no easy way for me to recreate the situation and check that the issue reported is still there when changing the code.

Because of this, we are going to close this issue - but if a repro is shared, we are happy to reopen it 🤗
