### ISSUE TITLE
trying to #import "RCTImageLoader.h"

### ISSUE THREAD

**Issue by gre** [facebook/react-native#2304]
I'm trying to `#import "RCTImageLoader.h"` 
but it fails, is that not exposed?

I'm writing a react-native plugin and want to reuse some react-native logic.

cc @nicklockwood 

Thanks

**Comment by llanox** [comment]
Have you tried that http://facebook.github.io/react-native/docs/linking-libraries-ios.html#content?

**Comment by gre** [comment]
<img width="326" alt="screen shot 2015-08-11 at 19 32 56" src="https://cloud.githubusercontent.com/assets/211411/9213392/d349adc2-405f-11e5-9a77-efbd1841c8be.png">

I'm writing my lib in an App for now, and it already has libRCTImage as a dependency, so this should work, no?

**Comment by ide** [comment]
You also need to have the headers in your path since that's what the compiler's looking at.

**Comment by gre** [comment]
that was it!
thanks

<img width="504" alt="screen shot 2015-08-11 at 19 45 35" src="https://cloud.githubusercontent.com/assets/211411/9213537/9fc866da-4061-11e5-98c5-c496e3569de9.png">

**Comment by mehulnahar** [comment]
I Did all pod setting, Framework added, Also header search path setting, But still 'RCTImageLoader.h' file not found this issue is not getting fixed.
