### ISSUE TITLE
[Flex] flexDirection row with flexWrap does not allocate vertical space

### ISSUE THREAD

**Issue by computerjazz** [facebook/react-native#23055]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 39.95 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.5.0 - ~/.nvm/versions/node/v10.5.0/bin/node
      Yarn: 1.10.1 - ~/.nvm/versions/node/v10.5.0/bin/yarn
      npm: 6.1.0 - ~/.nvm/versions/node/v10.5.0/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 22.0.1, 23.0.1, 23.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 27.0.2, 27.0.3, 28.0.2, 28.0.3
        API Levels: 23, 25, 26, 27, 28
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: ^3.4.7 => 3.4.11 
      @types/react: ^16.4.18 => 16.4.18 
      @types/react-native: ^0.56.10 => 0.56.24 
      react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728 
      react-native: 0.57 => 0.57.4 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

## Description
I am attempting to create a 3x3 grid layout by wrapping a list of 9 items by giving each item a width of 1/3 the screen and having height flex automatically. Everything works as expected in the simulator on the Layout page: https://facebook.github.io/react-native/docs/flexbox

expected:
![screen shot 2019-01-17 at 12 32 40 pm](https://user-images.githubusercontent.com/6730148/51347216-5492e980-1a54-11e9-81cc-553ad8fc8f97.png)

But when run on device or snack, height is not being automatically allocated.
actual (same code): 
![screen shot 2019-01-17 at 12 34 42 pm](https://user-images.githubusercontent.com/6730148/51347242-670d2300-1a54-11e9-87c8-376e4c83f869.png)

## Reproducible Demo

https://snack.expo.io/@computerjazz/amused-pizza

**Comment by computerjazz** [comment]
Found a fix -- adding `alignContent: 'stretch',` to the parent container seems to result in desired outcome.

**Comment by hramos** [comment]
Closing as author found a workaround.
