### ISSUE TITLE
Webview shared cookie with fetch

### ISSUE THREAD

**Issue by JB-CHAUVIN** [facebook/react-native#23063]
- [ v] Review the documentation: https://facebook.github.io/react-native
  - [v ] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ v] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Run `react-native info` in your terminal and paste its contents here.
  React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 443.88 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.3 - /usr/local/bin/node
      Yarn: 1.9.2 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 26, 27, 28
        Build Tools: 26.0.3, 27.0.3, 28.0.1, 28.0.3
        System Images: android-26 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz => 0.57.1
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-image-base64: 0.1.3
      react-native-image-to-base64: 0.1.0
      react-native-orientation-msa: 3.1.3
      react-native-rate: 1.1.2
      react-native-scripts: 1.14.0
      react-native-sentry: 0.39.0
      react-native-video: 3.2.0

## Description
When logging on a website with react native WebView, and then making an API call to this same website, the authentification and cookies are not persistent... it look's like the fetch module does not share cookies with the webview.

**Comment by hramos** [comment]
Thanks for reporting this. The WebView component has been forked, and future contributions are being considered through the new repository at https://github.com/react-native-community/react-native-webview.

Feel free to open a new issue over there, and make sure to include sufficient details in your issue description.
