### ISSUE TITLE
TextInput on android emulator doesn't let me type text

### ISSUE THREAD

**Issue by Ezema-Ugonna-Donald** [facebook/react-native#23065]
I can't seem to get TextInput working on my android emulator. It displays properly but I can't enter text
`import React, {Component} from 'react';
import {StyleSheet, View, TextInput, TouchableOpacity, Text, StatusBar} from 'react-native';

export default class LoginForm extends Component {
    constructor () {
        super();
        this.state = {
            text: '',
            text2: ''
        }
    }

  render() {
    return(
      <View style={styles.container}>
        <StatusBar 
            barStyle="dark-content"
        />
        <TextInput 
            placeholder='Username or Email'
            onChangeText={(text) => this.setState(text)}
            returnKeyType="next"
            style={styles.input} 
            onSubmitEditing={() => this.passwordInput.focus()}
            keyboardType="email-address"
            autoCapitalize='none'
            autoCorrect={false}
        />
        <TextInput 
            placeholder='Password'
            secureTextEntry
            onChangeText={(text2) => this.setState(text2)}
            returnKeyType="go"
            style={styles.input} 
            ref={(input) => this.passwordInput = input}
        />

        <TouchableOpacity style={styles.buttonContainer}>
            <Text style={styles.buttonText}>LOGIN</Text>
        </TouchableOpacity>
      </View>
    );
  }
}

const styles = StyleSheet.create ({
    container : {
        padding: 20,
        marginTop: 423
    },
    input : {
        height: 40,
        backgroundColor: 'rgba(239, 162, 90, 0.7)',
        marginBottom: 10,
        color: '#000',
        paddingHorizontal: 10
    }, 
    buttonContainer : {
        backgroundColor: 'rgb(224, 118, 22)',
        paddingVertical: 25
    },
    buttonText : {
        textAlign: 'center',
        color: '#fff',
        fontWeight: '700'
    }
});`

**Comment by umair-khanzada** [comment]
Exactly same issue with me.

see here https://github.com/facebook/react-native/issues/23663#issuecomment-471537331
