### ISSUE TITLE
App Store Review Guideline 2.3.1 - Performance

### ISSUE THREAD

**Issue by thecachedbyte** [facebook/react-native#23062]
We have a hybrid app where few screens are in react native and other screens are native. We are using codepush for OTA updates. Recently Apple rejected our app review with reason 

> We discovered that your app contains obfuscated code, selector mangling, or features meant to subvert the App Review process by changing this app's concept after approval to the App Store.

https://developer.apple.com/app-store/review/guidelines/#accurate-metadata

Anyone else facing/faced a similar issue?

**Comment by ionfeldman** [comment]
> We have a hybrid app where few screens are in react native and other screens are native. We are using codepush for OTA updates. Recently Apple rejected our app review with reason
> 
> > We discovered that your app contains obfuscated code, selector mangling, or features meant to subvert the App Review process by changing this app's concept after approval to the App Store.
> 
> https://developer.apple.com/app-store/review/guidelines/#accurate-metadata
> 
> Anyone else facing/faced a similar issue?

Any luck with this? We are facing the same issue.

**Comment by jonatahbrazz** [comment]
@ionfeldman me too.

**Comment by davincho** [comment]
Our app just got rejected as well. We suspect our embedded WebViews being the reason for this.

**Comment by jonatahbrazz** [comment]
@ionfeldman @davincho you must appeal, I got my approval informing about WebView and about OTA Updates, they approved.

**Comment by StanislavMayorov** [comment]
@jonatahbrazz Thank you. Our app was released after we had written explanation why we use WebView.

**Comment by LeeFengHY** [comment]
Guideline 2.3.1 - Performance
