### ISSUE TITLE
react native modal doesn't behave as expected

### ISSUE THREAD

**Issue by Nermin-K** [facebook/react-native#23073]
I'm trying to use `<Modal>` to make something like this
when pressing on About label in the drawer, it should open this popup screen
![screenshot_2019-01-19-01-22-49-059_com geekytools](https://user-images.githubusercontent.com/30387225/51417966-5e6a3900-1b89-11e9-8d5c-d6285f1c397d.png)
but what I get is this
at first it doesn't render the first view and the background isn't transparent
![screenshot_2019-01-19-01-23-12-150_com growthhack](https://user-images.githubusercontent.com/30387225/51418032-ca4ca180-1b89-11e9-9044-c11bfe9b664d.png)
it takes so long before rendering the first view and the transparent background and sometimes it doesn't untill I scroll the `<WebView> ` the centered view 
![screenshot_2019-01-19-01-23-25-063_com growthhack](https://user-images.githubusercontent.com/30387225/51418043-e05a6200-1b89-11e9-8be3-8f2ec8f9fa2d.png)

### here is my code
**custom drawer**
`render() 
{
        return (
            <SafeAreaView style={{ flex: 1 }}>
                <Modal
                    animationType="slide"
                    transparent={true}
                    visible={this.state.modalVisible}
                    presentationStyle="formSheet"
                >
                    <View style={styles.modal}>
                        <View style={styles.modalTop}>
                            <Image source={require('../../assets/icons/logo.png')} style={styles.smallIcon} />
                            <Text style={styles.modalTopText} >About App</Text>
                        </View>
                        <About />
                        <View style={styles.modalBottom}>
                            <Text style={{ color: 'red' }} onPress={() => this.setModalVisible(false)}>CLOSE</Text>
                        </View>
                    </View>
                </Modal>
                <ScrollView>
                       ............................
                        <ListItem
                            leftAvatar={<Image source={require('../../assets/icons/about.png')} style={styles.icon} />}
                            title={<Text style={styles.text}>About</Text>}
                            onPress={() => {
                                this.setModalVisible(true);
                                this.props.navigation.dispatch(DrawerActions.closeDrawer());
                            }} />
                </ScrollView>
            </SafeAreaView>
        );
    }`

I tried to center it by using position but nothing change.
I also had to give it specific width and height as it renders as a full screen!! 

`modal: {
        width: '95%',
        height: '95%',
        backgroundColor: '#fff',
        position: 'absolute', 
        top: 0, left: 0, right: 0, bottom: 0,
    },
    modalTop: {
        height: 50,
        flexDirection: 'row',
        marginTop: 15,
        marginLeft: 20,
    },
    modalTopText: {
        color: '#000',
        fontSize: 20,
        fontWeight: '300',
        marginTop: 8,
    },
    modalBottom: {
        height: 50,
        marginTop: 15,
        textAlign: 'right',
    },`

**About component**
`render() {
    return (
      <WebView
        ref={(ref) => { this.webview = ref; }}
        source={{ uri: 'https://growthhacktoolkit.com/android/about.html' }}
        style={{ flex: 1 }}
        scalesPageToFit={true}
      />
    );
  }`

### Here are my questions

1. Why `Modal` takes so long to render properly(without  transparent background)?
2. Why It doesn't render properly till I scroll the `WebView`?
3. Why `Modal` doesn't slide in from the bottom as it should?! It just appear with no animation.
4. Why `Modal` doesn't render at the center? and Why center styling has no effect?
5. Why `textAlign: 'right',` has no effect?!

- "react-native": "0.57.8"
- "react": "16.6.3"
- "react-native-webview": "^3.1.2"
- android
- redmi note 4 - android version 7.0
- windows 10

**Comment by iamandiradu** [comment]
I'm also having the same issue with Modal and WebView :(. Hope to find a fix for this :).
