### ISSUE TITLE
RN 0.8.0 XHR Requests Do Not Appear in Chrome

### ISSUE THREAD

**Issue by ppiekarczyk** [facebook/react-native#2307]
I've noticed this weird issue where a XHR network request is going through but it's not showing up in Chrome Devtools.

- FETCH API
- Chrome DevTools
- XHR Requests not going through

Here is a sample of what I'm currently doing:

![image](https://cloud.githubusercontent.com/assets/1211905/9215256/b9094f36-406d-11e5-90b1-b452ded65607.png)

**Comment by ide** [comment]
This is because it's using the fetch API on the device. The Chrome debugger solely provides a JS VM and could be swapped out with Safari, Node.js, etc...

git grep for XMLHttpRequest to see where it is polyfilled and comment it out if you would like to use Chrome's XHR.

**Comment by ppiekarczyk** [comment]
Is there a change that caused that to happen? I could have sworn I was using devtools to debug requests a week ago

**Comment by ide** [comment]
I'm not sure.. I thought it was like this since the beginning but could be mistaken.

**Comment by ppiekarczyk** [comment]
In any case, it's what's happening now. :+1 can you elaborate on `git grep XMLHttpRequest`?

**Comment by ide** [comment]
I just mean to search for where XHR is polyfilled:

```
$ git grep XMLHttpRequest -- Libraries
Libraries/Fetch/fetch.js:      var xhr = new XMLHttpRequest()
Libraries/JavaScriptAppEngine/Initialization/InitializeJavaScriptAppEngine.js:  // The native XMLHttpRequest in Chrome dev tools is CORS aware and won't
Libraries/JavaScriptAppEngine/Initialization/InitializeJavaScriptAppEngine.js:  GLOBAL.XMLHttpRequest = require('XMLHttpRequest');
Libraries/Network/FormData.js: * Polyfill for XMLHttpRequest2 FormData API, allowing multipart POST requests
Libraries/Network/FormData.js: * with mixed data (string, native files) to be submitted via XMLHttpRequest.
Libraries/Network/FormData.js:      // The XMLHttpRequest spec doesn't specify it, while MDN says that
Libraries/Network/XMLHttpRequest.ios.js: * @providesModule XMLHttpRequest
Libraries/Network/XMLHttpRequest.ios.js:var XMLHttpRequestBase = require('XMLHttpRequestBase');
Libraries/Network/XMLHttpRequest.ios.js:class XMLHttpRequest extends XMLHttpRequestBase {
Libraries/Network/XMLHttpRequest.ios.js:module.exports = XMLHttpRequest;
Libraries/Network/XMLHttpRequestBase.js: * @providesModule XMLHttpRequestBase
Libraries/Network/XMLHttpRequestBase.js: * Shared base for platform-specific XMLHttpRequest implementations.
Libraries/Network/XMLHttpRequestBase.js:class XMLHttpRequestBase {
Libraries/Network/XMLHttpRequestBase.js:module.exports = XMLHttpRequestBase;
```

It's in `Libraries/JavaScriptAppEngine/Initialization/InitializeJavaScriptAppEngine.js` it looks like.

**Comment by ppiekarczyk** [comment]
Ah cool. Thank you!
