### ISSUE TITLE
Manual linking React CxxBridge 

### ISSUE THREAD

**Issue by Kielan** [facebook/react-native#23074]
Essentially a duplicate of this issue, which in my opinion should not be closed until there is documentation explaining what that podfile config looks like in manual xcode linking. Not every project does or can use cocoapods including react native modules, thank you ahead of time for response.

https://github.com/facebook/react-native/issues/14925

https://facebook.github.io/react-native/docs/integration-with-existing-apps.html

**Comment by hramos** [comment]
Hi @Kielan, thanks for reporting this. If you think #14925 should not be closed, it's alright if you want to go ahead and create a brand new issue, just make sure to pick the Bug Report template: https://github.com/facebook/react-native/issues/new?template=bug_report.md

If you'd rather have this addressed in the docs, https://github.com/facebook/react-native-website/issues/new is the right place to submit a docs issue.
