### ISSUE TITLE
Flatlist pagingEnabled issue when using horizontal option

### ISSUE THREAD

**Issue by FarzadKaramouz** [facebook/react-native#23080]
## Environment
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz
      Memory: 1.71 GB / 5.89 GB
    Binaries:
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338
[skip envinfo]

## Description
I am using FlatList with horizontal and pagingEnabled options. When I define borderWidth in renderItem container element, paging is Ok but when borderWidth is not included, if I scroll item slowely a little bit and release it there, it remains there and does not scroll to the end or back to same item!!!
Also can solve problem if just define borderColor and not borderWidth!!! 😄

Is it true? Where is my mistake?!

## Reproducible Demo
https://snack.expo.io/@farzadkaramouz/flatlist-bug

![capture](https://user-images.githubusercontent.com/25000533/51430047-8d84b700-1c2a-11e9-9c04-a342bd743208.PNG)

**Comment by sbearben** [comment]
Most likely related to issue described here: https://github.com/facebook/react-native/issues/22251#issuecomment-438524264
