### ISSUE TITLE
Linking.openUrl show "Open With" popup dialog on android

### ISSUE THREAD

**Issue by mmaschenko** [facebook/react-native#23088]
## Environment
Environment:
  OS: macOS High Sierra 10.13.6
  Node: 6.9.1
  Yarn: 1.12.3
  npm: 6.4.1
  Watchman: 4.7.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

## Description
I have app with links to website. After i have added deeplinks it shows dialog "Open With" after i user Linking.openUrl(). How can i prevent this from happening? Cause it breaks user experience when they click open with my app and choose option ALWAYS. So they will never open link in browser

## Reproducible Demo
Linking.openUrl("https://mysite.com/")

AndroidManifest
`<data android:scheme="http" android:host="mysite.com"/>
<data android:scheme="https" android:host="mysite.com"/>`

**Comment by hramos** [comment]
Closing as this bug report concerns an older version of React Native.
