### ISSUE TITLE
Object.getOwnPropertyDescriptor(arguments[i])

### ISSUE THREAD

**Issue by azcodia** [facebook/react-native#23093]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
      Memory: 52.85 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.7.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 22, 23, 24, 25, 26, 27, 28
        Build Tools: 27.0.3, 28.0.2, 28.0.3
        System Images: android-22 | Intel x86 Atom, android-22 | Google APIs Intel x86 Atom, android-23 | Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-24 | Intel x86 Atom, android-24 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-25 | Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-26 | Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-27 | Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5014246
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      react: 16.7.0 => 16.7.0 
      react-native: 0.57.8 => 0.57.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description
previously there was no problem when I made new native react and run it
but now when I make new native react and run it, an error occurs
as follows

![object getownpropertydescriptor arguments i](https://user-images.githubusercontent.com/23573321/51510280-0fddc880-1e2f-11e9-8d57-b8a25eefdae2.jpeg)

even though I didn't add any script at all,
after I created "react-native init nameAplication" I immediately ran the application I created earlier, "react-native run-android",
before it went smoothly

I run the application on my device directly

please instructions

**Comment by matheusmoreira-hotmart** [comment]
Indeed, just confirmed this info in my app

**Comment by matheusmoreira-hotmart** [comment]
Maybe if you disable delta it'll work

**Comment by azcodia** [comment]
I don't turn off delta, but it's still the same error

**Comment by azcodia** [comment]
are there any other instructions?

**Comment by azcodia** [comment]
please give me a clue, how is the solution to this problem

**Comment by minhanhnguyen2196** [comment]
Im having the same problem

**Comment by thaitrandng** [comment]
1.  Ctrl + M in emulator
2.  Click "Debug JS Remote"

Goodluck!

**Comment by eduardo-santos** [comment]
Anyone knows how to solve without the "Debug JS Remote"?

**Comment by gucx** [comment]
#22842

**Comment by estebansolisd** [comment]
> Anyone knows how to solve without the "Debug JS Remote" option?

Yes only move strong to left and right your phone and the menu will appears, there is the debug js remote option

**Comment by declanelcocks** [comment]
Using the Debug JS Remotely option didn't work for me

**Comment by chenxiubin** [comment]
Im having the same problem

**Comment by jayzyaj** [comment]
I had the same problem when I try to create a new react-native project. But this error did not happen in my previous projects.

**Comment by FrankMue** [comment]
same on Windows 10 + NodeJs 11.7
Debug JS Remotely doesn' work too

**Comment by estebansolisd** [comment]
If you are working with real device, maybe adb reverse works https://facebook.github.io/react-native/docs/running-on-device

**Comment by yll2wcf** [comment]
Im having the same problem

**Comment by mxc7609** [comment]
Im having the same problem on debug and release

**Comment by carlmagumpara** [comment]
> If you are working with real device, maybe adb reverse works https://facebook.github.io/react-native/docs/running-on-device

still not working on actual device

**Comment by omid69** [comment]
I've this problem after running `yarn install`.

**Comment by yoyo837** [comment]
babel/babel#9341

**Comment by FrankMue** [comment]
> same on Windows 10 + NodeJs 11.7
> Debug JS Remotely doesn' work too

After uninstalling Androis Studio 3.3 and installing 3.1 it's working again on my machine :)
