### ISSUE TITLE
undefined is not a function (evaluating 'Object.getOwnPropertyNames(argument[i])

### ISSUE THREAD

**Issue by radjivF** [facebook/react-native#23091]
## Environment
Environment:
  OS: macOS 10.14.2
  Node: 10.15.0
  Yarn: Not Found
  npm: 6.4.1
  Watchman: 4.9.0
  Xcode: Xcode 10.1 Build version 10B61
  Android Studio: 3.2 AI-181.5540.7.32.5056338

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: ^0.55.4 => 0.55.4

## Description
After moving my folder to one another one, clean every cache you can imagine about it, I can't build or run in development 
on Android anymore and receive this error:

![screenshot_20190122-121146](https://user-images.githubusercontent.com/5714138/51506775-0f026200-1e42-11e9-91e9-2acf9d0b1471.png)

It works fine on ios

The apk is crashing but I got an success message on android studio.
 
Any idea? this error is driving my team insane.

Cheers

**Comment by yoyo837** [comment]
babel/babel#9341

**Comment by nabeelpkl** [comment]
same issue

**Comment by hramos** [comment]
Closing as this bug report concerns an older version of React Native.

**Comment by chetnashah** [comment]
occurs on 0.61.4
