### ISSUE TITLE
Cannot read property 'setNativeProps' of undefined

### ISSUE THREAD

**Issue by jacob-israel-turner** [facebook/react-native#2310]
[Here](https://cloud.githubusercontent.com/assets/8698364/9203393/d7c7e618-404e-11e5-9f38-117386d35d4f.png) is an image with the stack trace.

I get this error when I click on a `TouchableWithoutFeedback` with a single `View`. The press sets off an animation to bring up an `Animated.View` overlay with a `PickerIOS` inside.  The error only happens about one in presses.  If I close the red box, the app continues to operate correctly.  Any idea what might be causing this?

I can try reproducing this in RN Playground if it might help.

**Comment by jacob-israel-turner** [comment]
Also, immediately after this error throws, I also get a similar error to #1693 in the console.

![error](https://cloud.githubusercontent.com/assets/8698364/9213202/0907ad88-4088-11e5-8795-23ca8582001b.png)

**Comment by browniefed** [comment]
@jacob-israel-turner is this still happening in latest .11-rc?

**Comment by brentvatne** [comment]
I haven't run into this issue before but will happily reopen this issue if it is still around!

**Comment by jacob-israel-turner** [comment]
Haven't had this for a while now.  We're currently running `0.10.1`.  I'll reopen if I run into this again.

**Comment by admmasters** [comment]
This is occurring for me on the latest master when using any of the pickers now.

**Comment by admmasters** [comment]
![simulator screen shot 15 oct 2015 15 31 40](https://cloud.githubusercontent.com/assets/335607/10516810/f1c9a19c-7351-11e5-843e-d063771a0aba.png)

**Comment by alinz** [comment]
I have got into this problem when I was using Animated api and what I found was if the component did not mount, you will get this issue. So it does sound a little bit cryptic.
