### ISSUE TITLE
Image not visible for Android in Release Mode

### ISSUE THREAD

**Issue by PrathyushaKadiri** [facebook/react-native#23114]
Environment:
  OS: macOS High Sierra 10.13.6
  Node: 8.11.1
  Yarn: 1.7.0
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 10.0 Build version 10A255
  Android Studio: 3.2 AI-181.5540.7.32.5056338

Packages: (wanted => installed)
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: 0.54.2 => 0.54.2

## Description

Images are not showing sometimes for android in release mode. 

I am showing captured photo with the default image before photo captured.

After photo captured, captured image is visible but "default" image should be visible before capture. Where in my case "default" image is not visible sometimes and the "default" image is in local.

Here is code snippet

constructor(props){
    super(props)
    this.state = {
myimage : "default"
    }
  }

<Image style={{
    width:80,
    height:80,
    borderRadius:5,
    borderColor:'gray',
    borderWidth:0.5,
  }}
      source= {this.state.myimage === "default" ?  require('../images/camera.png') : { uri: this.state.myimage }}/>

**Comment by dulmandakh** [comment]
You should use defaultSource for this case. It works on both iOS and Android since 0.56, but works only on iOS for below versions.
