### ISSUE TITLE
[Bridge] RCT_EXPORT_METHOD for instance methods, rather than class methods

### ISSUE THREAD

**Issue by fatuhoku** [facebook/react-native#2311]
I have an RN View that can tell me whenever a button is pressed. However, I want to link this information back to the current state of the `ViewController` instance.   How can this be done?

The only way I can think of is through listening out for `NSNotification`s as well as emitting them from the exported methods.

**Comment by skevy** [comment]
You can pass the reactTag into the class method, and do something like:

```objective-c
RCT_EXPORT_METHOD(reload:(NSNumber *)reactTag)
{
    [_bridge.uiManager addUIBlock:^(RCTUIManager *uiManager, RCTSparseArray *viewRegistry) {
        VRImageView *view = viewRegistry[reactTag];
        if ([view isKindOfClass:[VRImageView class]]) {
            [view reloadImage];
        }
    }];
}
```

**Comment by fatuhoku** [comment]
@skevy Hmm. Might be useful to others but I'm not working with the view specifically. I want to send a message to another object, which is stored as a a property of the ViewController.

**Comment by ide** [comment]
Agree this would be useful. I think no one's gotten around to it because using the react tag works for now. Would be nice to have though.

**Comment by paramaggarwal** [comment]
`RCT_EXPORT_METHOD` actually wraps instance methods only. Problem is that the instance is created by React. 

I am also looking for a way to expose `viewDidAppear`/`viewWillAppear` from `RCTRootView`?

**Comment by yamill** [comment]
@paramaggarwal have you figured out how to expose `viewDidAppear/viewWillAppear/viewWillDisappear` from a module?

**Comment by paramaggarwal** [comment]
@yamill I needed it for RCTRootView. Here is how I do it. It's tacky and uses a reactTag of `4` which I have seen corresponds to the first view inside first render method. So I wrap it inside a view controller and then use it.

```
- (instancetype)initWithModuleName:(NSString *)moduleName
{
    self = [super init];
    if (self) {
        _reactView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                 moduleName:moduleName
                                              launchOptions:nil];
        self.view =_reactView;
    }
    
    return self;
}

- (void)viewDidAppear:(BOOL)animated {
    [super viewDidAppear:animated];
    [_reactView.bridge.eventDispatcher sendInputEventWithName:@"topFocus" body:@{@"target": @4}];

}
- (void)viewDidDisappear:(BOOL)animated {
    [super viewDidDisappear:animated];
    [_reactView.bridge.eventDispatcher sendInputEventWithName:@"topBlur" body:@{@"target": @4}];
}
```

**Comment by yamill** [comment]
@paramaggarwal Thanks for this. Though I'm confused how I'd get this to work on my module. Would you mind helping me? I'm trying to get `viewDidDisappear` to work when the media player closes.

```javascript

#import "RNMediaPlayer.h"
#import "RCTLog.h"
#import "RCTConvert.h"
#import <AVFoundation/AVFoundation.h>
#import <AVKit/AVKit.h>

@implementation RNMediaPlayer
{
  AVPlayer *_player;
  AVPlayerViewController *_playerViewcontroller;
  
  NSString *_uri;
}


RCT_EXPORT_MODULE();


RCT_EXPORT_METHOD(open:(NSDictionary *)options)
{

  _uri = [options objectForKey:@"uri"];

  NSString *encodedString = [_uri stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding];
  NSURL *myURL = [[NSURL alloc] initWithString:encodedString];
  
  
  dispatch_async(dispatch_get_main_queue(), ^{

    AVPlayerViewController *playerViewController = [[AVPlayerViewController alloc] init];

    playerViewController.player = [AVPlayer playerWithURL: myURL];

    // autoplay
    [playerViewController.player play];

    _playerViewcontroller = playerViewController;
    

    UIViewController *ctrl = [[[[UIApplication sharedApplication] delegate] window] rootViewController];

    [ctrl presentViewController:playerViewController animated:TRUE completion: nil];

  });
}

-(void)viewDidDisappear:(BOOL)animated
{
  NSLog(@"test"); //this isn't getting called when the mediaplayer 'Done' button is pressed?
}


@end


```

**Comment by paramaggarwal** [comment]
@yamill It is straightforward for a `NativeModule`. Try adding this in your `viewDidDisappear`. Make sure your `viewDidDisappear` is called by setting a breakpoint in Objective-C first.

```
[_reactView.bridge.eventDispatcher sendInputEventWithName:@"topFocus" body:@{@"target": _reactTag}];
```

**Comment by yamill** [comment]
@paramaggarwal I added the breakpoint, but looks like it never gets called?

**Comment by alper** [comment]
I don't understand. Does RCT_EXPORT_METHOD only work on class methods or only on instance methods (and does it call the default init constructor itself)? I'm trying to create a Swift object over on the javascript side by calling init but that dies.

**Comment by paramaggarwal** [comment]
Yes, only on instance methods which it instantiates by itself. Here: [RCTBatchedBridge.m#L290](https://github.com/facebook/react-native/blob/e018aa3100d93abf0e222cd70bbcbb6ab248eced/React/Base/RCTBatchedBridge.m#L290)

**Comment by alper** [comment]
Can I add this to the docs somewhere? Where do the docs even live? I just found a bunch of empty files.

**Comment by paramaggarwal** [comment]
You can go to [Docs](http://facebook.github.io/react-native/docs/native-modules-ios.html#content) and click `Edit`.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/bridge-rctexportmethod-for-instance-methods-rather-than-class-methods

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by johndanek** [comment]
@paramaggarwal Does this functionality still exist? My subclass of RCTViewManager has self.bridge, but no self.bridge.uiManager. I need to call addUIBlock. How can this be achieved in React native 0.49.1?
