### ISSUE TITLE
Attempt to invoke virtual method 'double java.lang.Double.doubleValue()

### ISSUE THREAD

**Issue by mojtaba-hajishah** [facebook/react-native#23126]
## Environment
  System:
      OS: macOS 10.14
      CPU: (4) x64 Intel(R) Core(TM) i5-4260U CPU @ 1.40GHz
      Memory: 36.91 MB / 4.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.15.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.2, macOS 10.13, tvOS 11.2, watchOS 4.2
      Android SDK:
        API Levels: 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-27 | Intel x86 Atom_64, android-27 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom_64
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 9.2/9C40b - /usr/bin/xcodebuild
    npmPackages:
      react: 16.7.0 => 16.7.0 
      react-native: ^0.57.8 => 0.57.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description
I've built a music player app and when user taps on the next or previous buttons, a state change happens.
I get this error when user taps on these buttons rapidly.

![screenshot-2019-01-23_17 23 57 731](https://user-images.githubusercontent.com/30038691/51611277-1d30ab00-1f34-11e9-9eed-498f86891d96.png)

this error causes the app to crash in production releases. but I've received these reports only on **android** devices. no reports for iOS devices. I don't know if that's relevant.

## Reproducible Demo
I can't share my code because of NDA stuff.

**Comment by mojtaba-hajishah** [comment]
upgraded to react native 0.57.8 and react 16.7.0 but the issue still exists.

**Comment by mojtaba-hajishah** [comment]
this is the stack trace of this error:

com.facebook.react.bridge.ReadableNativeArray.getDouble ReadableNativeArray.java:114
com.facebook.react.bridge.JavaMethodWrapper$4.extractArgument JavaMethodWrapper.java:64
com.facebook.react.bridge.JavaMethodWrapper$4.extractArgument JavaMethodWrapper.java:60
com.facebook.react.bridge.JavaMethodWrapper.invoke JavaMethodWrapper.java:359
com.facebook.react.bridge.JavaModuleWrapper.invoke JavaModuleWrapper.java:160
com.facebook.react.bridge.queue.NativeRunnable.run NativeRunnable.java
android.os.Handler.handleCallback Handler.java:751
android.os.Handler.dispatchMessage Handler.java:95
com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage MessageQueueThreadHandler.java:29
android.os.Looper.loop Looper.java:154
com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run MessageQueueThreadImpl.java:192
java.lang.Thread.run Thread.java:762

**Comment by ithustle** [comment]
I'm facing this error too on android after upgrading to RN 0.58.2.
I downgraded React 16.7.0 to 16.6.3 to upgrade to new RN version.

Any help?

**Comment by grabbou** [comment]
@ithustle we have managed to reproduce it on 0.58.2 and are working on a fix. Can you try 0.58.1 as an alternative for now?

**Comment by ithustle** [comment]
If work, I'm cool... I'll try

**Comment by Titozzz** [comment]
@ithustle Can you give me the list of dependencies inside your package.json ?

**Comment by ithustle** [comment]
@grabbou , the same error on RN 0.58.1 :(

@Titozzz 

```
"dependencies": {
    "axios": "^0.18.0",
    "react": "^16.6.3",
    "react-native": "^0.58.1",
    "react-native-audio-file-streamer": "0.0.5",
    "react-native-camera": "^1.9.2",
    "react-native-device-info": "^0.24.3",
    "react-native-dialog-input": "github:ithustle/react-native-dialog-input",
    "react-native-fast-image": "^5.1.2",
    "react-native-get-music-files": "^2.1.0",
    "react-native-local-mongodb": "^2.2.4",
    "react-native-marquee": "^0.3.2",
    "react-native-music-control": "^0.9.7",
    "react-native-remote-svg": "^1.4.0",
    "react-native-vector-icons": "^6.2.0",
    "react-navigation": "^1.6.1",
    "react-navigation-redux-helpers": "^1.1.2",
    "react-redux": "^6.0.0",
    "redux": "^4.0.1",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0",
    "rn-fetch-blob": "^0.10.15"
  },
  "devDependencies": {
    "@babel/runtime": "^7.3.1",
    "babel-core": "6.26.3",
    "babel-jest": "23.6.0",
    "jest": "23.2.0",
    "metro-react-native-babel-preset": "^0.51.1",
    "react-test-renderer": "^16.6.3",
    "redux-immutable-state-invariant": "^2.1.0",
    "schedule": "^0.4.0",
    "seamless-immutable": "^7.1.4"
  },
  "jest": {
    "preset": "react-native"
  }
```

**Comment by grabbou** [comment]
Fix is on the way. Please wait for about an hour for 0.58.3 to try.

**Comment by kelset** [comment]
@mojtaba-hajishah 0.58.3 is out.

That said

> I can't share my code because of NDA stuff.

That's not a valid thing to write, you should always provide a minimal repro created with `react-native init`.

**Comment by carlPro** [comment]
```
rf -rf ./node_modules
react-native run-android 
```
work for me :)

**Comment by Fasteel** [comment]
```
rf -rf ./node_modules
react-native run-android 
```
work for me :)

**Comment by kelset** [comment]
@mojtaba-hajishah have you tried cleaning up the project as @Fasteel wrote?

**Comment by mojtaba-hajishah** [comment]
@kelset still having the issue. Could you please tell me the reason behind this error? maybe I can find a temporary workaround. it's affecting hundreds of users everyday.

**Comment by kelset** [comment]
> Could you please tell me the reason behind this error?

I have no way of helping you without a repro (which means, a `react-native init`-ed project with the minimal changes that leads to creating the same issue you are reporting), sorry. Probably it's some race condition, maybe something on a didMount or some button press getting fired before the method that it needs to run is ready. But again, there is no way to help you without a reproducible demo.

**Comment by mojtaba-hajishah** [comment]
Thank you @kelset for the follow up.
I managed to find the origin of the issue, which was [react-native-text-ticker](https://github.com/deanhet/react-native-text-ticker).
The stack trace of the issue was misleading and referenced react native library as the source of the problem, but after removing this library, everything works just fine.
I still have absolutely no idea what was going on, but since I no longer face the issue, feel free to close this.

**Comment by kelset** [comment]
Ok thanks - may be worth opening an issue in that repo then, but still glad you found the fix 👏

**Comment by likobe-mobonda-jeandenis** [comment]
![Capture d'écran 2019-09-24 02 07 04](https://user-images.githubusercontent.com/47183213/65471689-655fee80-de70-11e9-894f-3cca429395ac.png)

could someone help me ?? because I did everything but no solution

**Comment by AsiamCn** [comment]
In my case, I found there is some bugs in my Javascript code.
You can debug Android code with Android Studio and find which call cause this crash.
File: com.facebook.react.bridge.JavaMethodWrapper
![image](https://user-images.githubusercontent.com/10176630/67447560-dac50780-f646-11e9-9591-f3bc2d9f89c4.png)

My js code call measureLayout with null params:
![image](https://user-images.githubusercontent.com/10176630/67447648-1a8bef00-f647-11e9-9acb-474985e3ca8b.png)

**Comment by zuhairnaqi** [comment]
If you are using keyboardShift on somewhere in project. Do remove it and check.
This works for me

**Comment by anuj-njoshi** [comment]
Any one found exact reason of this bug i am facing same issue 
My env
` react: 16.8.3 => 16.8.3 
      react-native: 0.59.9 => 0.59.9 `

**Comment by stevenleeg** [comment]
I also ran into this issue and used @AsiamCn's suggestion to track it down to `react-native-reanimated`. Fire up Android Studio, run the app, and watch the logcat (it's a tab in the bottom of the Android Studio window) in order to get a stack trace which will hopefully lead you to the culprit.

In my case, I just needed to upgrade `react-native-reanimated` from 1.2.0 -> 1.6.0 and everything worked.

**Comment by boltware** [comment]
> I also ran into this issue and used @AsiamCn's suggestion to track it down to `react-native-reanimated`. Fire up Android Studio, run the app, and watch the logcat (it's a tab in the bottom of the Android Studio window) in order to get a stack trace which will hopefully lead you to the culprit.
> 
> In my case, I just needed to upgrade `react-native-reanimated` from 1.2.0 -> 1.6.0 and everything worked.

This worked for me!. I recently migrated to react-native 0.61 and was getting above error. I updated   `react-native-reanimated` from 1.2.0 -> 1.6.0 and it Wola!!!!!

**Comment by kishor3854** [comment]
I also face same problem with react-native version 61.2 and react version 16.9.0. I remove react-native-reanimated library and reinstall & relink it. It's work fine.Its error due to old version of react-native-reanimated, just upgrade it and run it. :)
