### ISSUE TITLE
ScrollView Component default position is wrong , in iphone X , the default distance is the height of the status bar at the top. 

### ISSUE THREAD

**Issue by xupengkun** [facebook/react-native#23121]
## Environment

react-native : 0.57.8 
platform :   ios
devices : iphoneX
devicesVersion : 12.1

npm : 6.4.1
node : 10.15.0

## Description

ScrollView Component default position is wrong , in iphone X , the default distance is the height of the status bar at the top.

![image](https://user-images.githubusercontent.com/29838791/51597038-443bac80-1f35-11e9-8ec9-305ffe8f67a0.png)

log output default position at -44

![image](https://user-images.githubusercontent.com/29838791/51646932-aa681400-1fb5-11e9-9f06-df953a6c70f5.png)

## Reproducible Demo

There was a problem upgrading from 55.4 to 57.8

**Comment by brenwell** [comment]
I am seeing this issue aswell, swapping a View to a ScrollView offsets the content by the height of the statusbar

```
info
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
      Memory: 486.80 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.15.2 - ~/.nvm/versions/node/v10.15.3/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 22, 23, 26, 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-22 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.8 => 0.59.8
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

**Comment by brenwell** [comment]
@xupengkun Did you just offset the scollview manually or was there something deeper?

**Comment by brenwell** [comment]
I am having to do something like

```ts
    const hack = {
      top: -44
    }

    const pageStyles = isIPhoneXish()
      ? [theme.Page, hack]
      : theme.Page

    return(
      <ScrollView style={pageStyles}>

```

**Comment by brenwell** [comment]
Ok so that didn't work but I found a much better solution

```ts
<ScrollView contentInsetAdjustmentBehavior="never" >
```
