### ISSUE TITLE
Warning 'Require cycle' between fetch.js & whatwg-fetch.js

### ISSUE THREAD

**Issue by damrem** [facebook/react-native#23130]
## Environment
```
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
      Memory: 14.64 GB / 31.84 GB
    Binaries:
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338
```

## Description
Working with `react-native@0.57.7`, I encounter this warning:
`Require cycle: node_modules\react-native\Libraries\Network\fetch.js -> node_modules\react-native\Libraries\vendor\core\whatwg-fetch.js -> node_modules\react-native\Libraries\Network\fetch.js`
This issue had already kind of been raised in https://github.com/facebook/react-native/issues/20841. But it has been closed without being fixed because it seemed to be in the scope of various other libraries.
But the fact is that this particular warning involves `react-native` code so I'm reopening an issue.

## Reproducible Demo
Could not get expo to show any `console` message.

**Comment by shravanteegala** [comment]
Iam facing same Warning issue.

**Comment by kelset** [comment]
Closing, please refer to this -> https://github.com/facebook/metro/issues/287
