### ISSUE TITLE
How to use React Native with openlayers

### ISSUE THREAD

**Issue by LanmeijingLucky** [facebook/react-native#23137]
First, I'm sorry for my bad English!

I am developing a mobile application in React Native requiring useing openlayers, and I found some information is about 'WebView',but I don't want to use it. Who can help me? Thanks!

**Comment by dulmandakh** [comment]
You can use RN modules if there are or you can develop UI components for it. See https://facebook.github.io/react-native/docs/native-components-ios and
https://facebook.github.io/react-native/docs/native-components-android.
