### ISSUE TITLE
Switch component not rendering correctly in Android 9.0. It's invisible!

### ISSUE THREAD

**Issue by benmcmaster** [facebook/react-native#23134]
## Environment

React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 78.09 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
      Yarn: 1.12.3 - ~/.yarn/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.13.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 27, 28
        Build Tools: 28.0.2, 28.0.3
        System Images: android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0
      react-native: 0.57.7 => 0.57.7
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description

The `Switch` component is not displaying in Android 9.0 Pie on Pixel devices or emulators when it's inside of a `ScrollView`. It is there and you can interact with the component, but it's invisible.

## Reproducible Demo

It looks like Snack is running Android 8.1. It's not showing the problem. Only with Android 9.0 will you would see the problem.
https://snack.expo.io/rJnA0c8mN

**Comment by ferrannp** [comment]
Hey,

I tried your snack on Android P and I seem to see the switch when scrolling:

![11ce23c8-dfa4-49dd-b551-c3dfbeffb308](https://user-images.githubusercontent.com/774577/51975598-ece09380-2482-11e9-9918-e4e106ac74be.jpeg)

I am on Pixel 2 running Android P. What device are you using?

**Comment by marcelkalveram** [comment]
I'm having the same issue on Android 9 on a Pixel, but haven't updated to RN 0.58 so far.

**Comment by benmcmaster** [comment]
I just updated: 
```
React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 64.91 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
      Yarn: 1.13.0 - ~/.yarn/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.13.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 27, 28
        Build Tools: 28.0.2, 28.0.3
        System Images: android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.6.3 => 16.8.3
      react-native: ^0.58.5 => 0.58.5
    npmGlobalPackages:
      react-native-cli: 2.0.1
```
Still not seeing it... Not sure what the issue in my build... I will try to isolate.

**Comment by mikaelquick** [comment]
Using react-native: 0.58.6 and Android9 on a Pixel2. 
Switch is invisible.

**Comment by engrRehan** [comment]
I have been facing similar problem when <Switch> will not render. I realized that using <ImageBackground>  or in style using background, will make the Switch not render in Android 9. Removing backgrounds, fixed the issue.

**Comment by SnoyIatK** [comment]
It is happening with latest version of RN (0.60.5), if any ancestor view has opacity property < 1, Switch component will not be rendered.
Sample with default react-init app
<img width="962" alt="switch-bug" src="https://user-images.githubusercontent.com/3056569/65625589-0da7bb80-e007-11e9-94e9-b240a2f9335b.png">

**Comment by MehmetKaplan** [comment]
> It is happening with latest version of RN (0.60.5), if any ancestor view has opacity property < 1, Switch component will not be rendered.

This is exactly as I observe. Any workaround suggestions are appreciated...
