### ISSUE TITLE
Implement onSelectionChange on <Text selectable />

### ISSUE THREAD

**Issue by jpolo** [facebook/react-native#23147]
## Environment
```
React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
      Memory: 340.95 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.3 - /var/folders/78/3_1gd4qx1gj_qtw62hhywmtm0000gn/T/yarn--1548344382256-0.8810213803473674/node
      Yarn: 1.12.3 - /var/folders/78/3_1gd4qx1gj_qtw62hhywmtm0000gn/T/yarn--1548344382256-0.8810213803473674/yarn
      npm: 6.5.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 26.0.0, 26.0.1, 26.0.3, 27.0.3, 28.0.3
        System Images: android-25 | Google APIs Intel x86 Atom, android-25 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.7.0 => 16.7.0
      react-native: 0.57.8 => 0.57.8
```

## Description

I am trying to implement a rich text view with selectable text, url links, etc. Reading the selection range is a mandatory feature too.

At the moment I need to use a workaround for the root component to make it selectable:
- `TextInput` on ios 
-  https://github.com/msand/react-native-selectable-text/ for android. 

In the end, the text can be selectable but touchable text inside a TextInput never trigger the onPress callback so links are broken.

I am using a `TextInput` only because I need the `onSelectionChange`. So a potential fix for my usecase could be for react-native team to implement `onSelectionChange` for `Text` component or to fix touchable text inside a TextInput.

## Reproducible Demo
The ios workaround
```javascript
<TextInput editable={false} selectable={true} multiline={true} onSelectionChange={() => {}}>
  <Text onPress={()=> console.debug('never called!')}></Text>
</TextInput>
```

My ideal implementation would be :
```javascript
<Text selectable={true} onSelectionChange={() => {/* this callback does not exist */}}>
  <Text onPress={()=> console.debug('it works!')}></Text>
</Text>
```

**Comment by hramos** [comment]
Thanks for submitting the issue! If I read it right, it looks like this is not so much a bug report, but an enhancement request. As it happens, we're not currently tracking those on this repository at this time.

**Comment by fakenickels** [comment]
You can use this https://github.com/Astrocoders/react-native-selectable-text/
```js
import { SelectableText } from "react-native-selectable-text";

// Use normally, it is a drop-in replacement for react-native/Text
<SelectableText
  menuItems={["Foo", "Bar"]}
  onSelection={({ eventType, content, selectionStart, selectionEnd }) => {}}
  value="I crave star damage"
/>;
```
