### ISSUE TITLE
How to preload / prefetch images for later use in ImageView?

### ISSUE THREAD

**Issue by ms88privat** [facebook/react-native#2314]
A possible solution is in this comment: https://github.com/facebook/react-native/issues/2233#issuecomment-128658761

But i don't have any Obj-C skills yet. So maybe someone could help me out with this?

Thank you guys!

Marcel

**Comment by ide** [comment]
You could render an Image component with opacity 0 or size 0x0. Not a great solution but should work.

**Comment by ms88privat** [comment]
I thought about that, but it is not really suitable in general and especially in my situation :(. 
But do you think it would be possible to write a native module for it and export it to Js? I would really like to help and contribute, but i am not able to do it by myself yet. Maybe i can put 30$ in the pot instead.

**Comment by ide** [comment]
The hard part is figuring out the API. For example, do we want to expose some kind of network cache that is shared by XHR/fetch and other networking APIs? I think the implementation will be pretty straightforward.

**Comment by hayeah** [comment]
@ms88privat Here's the prefetching NativeModule I came up with. It uses the same HTTP cache that the original Image component uses for remote images.

(BTW, to get it to work, you'll need to add `Libraries/Image` to the project's search path)

```js
ImagePreloadManager.prefetch(url,function(err,result) {
  // if(err) ...
  var {width,height,bytes} = result;
  // ...
});
```


`RCTImagePreloadManager.h`

```objc
#import <Foundation/Foundation.h>
#import "RCTBridgeModule.h"


@interface RCTImagePreloadManager : NSObject <RCTBridgeModule>

@end
```

`RCTImagePreloadManager.m`

```objectivec
#import "RCTImagePreloadManager.h"
#import "RCTImageDownloader.h"
#import "RCTUtils.h"

@implementation RCTImagePreloadManager

RCT_EXPORT_MODULE(); // actually exported as "ImagePreloadManager"


//
RCT_EXPORT_METHOD(prefetch:(NSString *) src
                onComplete:(RCTResponseSenderBlock)completeBlock) {
  NSURL *url =  [NSURL URLWithString:src];
  [[RCTImageDownloader sharedInstance] downloadDataForURL:url progressBlock:^(int64_t written, int64_t total) {
    NSLog(@"(%.2f) %@\n",((float) written)/total,url);
  } block:^(NSData *data, NSError *error) {
    if(error != nil) {
//      NSLog(@"image preload fail: %@\n (%@)",url,error);
      completeBlock(@[error.localizedDescription]);
    } else {
//      CGFloat scale = RCTScreenScale();
      UIImage *image = [UIImage imageWithData:data scale:1];
//      NSLog(@"image preload success: (%.2fx%.2f) %@\n",image.size.width,image.size.height, url);
      completeBlock(@[[NSNull null],@{
                        @"width": @(image.size.width),
                        @"height": @(image.size.height),
                        @"bytes": @(data.length),
                        }]);
    }
  }];
}

@end
```

**Comment by ms88privat** [comment]
@hayeah thank you very much. I will try it tomorrow  :+1:

**Comment by ms88privat** [comment]
What I am doing wrong? (using 0.10.0-rc)

1. I copied the files into a folder which i then added to my project through xcode.
https://db.tt/GenldugP

2. I set the Search-Path: (*it is node_modules/react-native/Libraries instead of node_modules/Libraries?)
https://db.tt/eE5d25eu

But then i get these errors.
https://db.tt/WNXFyAnk

Thank you

**Comment by hayeah** [comment]
@ms88privat Xcode is complaining that method is missing. Maybe 0.10.0rc removed the method I used? Check the header to see if that method exists.

(It looks like you've done 1 and 2 properly)

**Comment by ms88privat** [comment]
@hayeah I am lost here, did you try it with 0.10.0-rc?

**Comment by brentvatne** [comment]
The signature for `downloadDataForURL` is now:

```
- (RCTImageLoaderCancellationBlock)downloadDataForURL:(NSURL *)url
                                      progressHandler:(RCTImageLoaderProgressBlock)progressBlock
                                    completionHandler:(void (^)(NSError *error, NSData *data))completionBlock
```

So:

```
RCT_EXPORT_METHOD(prefetch:(NSString *) src
                onComplete:(RCTResponseSenderBlock)completeBlock) {
  NSURL *url =  [NSURL URLWithString:src];
  [[RCTImageDownloader sharedInstance] downloadDataForURL:url progressHandler:^(int64_t written, int64_t total) {
    NSLog(@"(%.2f) %@\n",((float) written)/total,url);
  } completionHandler:^(NSData *data, NSError *error) {
    if(error != nil) {
//      NSLog(@"image preload fail: %@\n (%@)",url,error);
      completeBlock(@[error.localizedDescription]);
    } else {
//      CGFloat scale = RCTScreenScale();
      UIImage *image = [UIImage imageWithData:data scale:1];
//      NSLog(@"image preload success: (%.2fx%.2f) %@\n",image.size.width,image.size.height, url);
      completeBlock(@[[NSNull null],@{
                        @"width": @(image.size.width),
                        @"height": @(image.size.height),
                        @"bytes": @(data.length),
                        }]);
    }
  }];
}
```

**Comment by andyyou** [comment]
BTW is any possible do this mission as follow

```
fetch(imageURL)
.then(function(response) {
  return response.blob();
})
.then(function(response) {
  /* get image blob or base64 format*/
})
.done();
```

**Comment by faurehu** [comment]
@andyyou did this work for you? My response comes with an empty body

**Comment by ms88privat** [comment]
@faurehu Andyyou's solution is not implemented I think, it was only a suggestion. You can use the solution from above (tested on RN 0.16.0):

Add these two files to your iOS project:

RCTImagePreloadManager.h
```c
#import <Foundation/Foundation.h>
#import "RCTBridgeModule.h"


@interface RCTImagePreloadManager : NSObject <RCTBridgeModule>

@end
```

RCTImagePreloadManager.m
```c
#import "RCTImagePreloadManager.h"
#import "RCTImageView.h"
#import "RCTBridge.h"
#import "RCTImageLoader.h"

@implementation RCTImagePreloadManager

RCT_EXPORT_MODULE(); // actually exported as "RCTImagePreloadManager"

@synthesize bridge = _bridge;

//
RCT_EXPORT_METHOD(prefetch:(NSString *) src
                  onComplete:(RCTResponseSenderBlock)completeBlock) {
  [self.bridge.imageLoader loadImageWithTag:src size:CGSizeMake(1, 1) scale:1 resizeMode:UIViewContentModeScaleAspectFill progressBlock:^(int64_t progress, int64_t total) {} completionBlock:^(NSError *error, UIImage *image) {
    if(error != nil) {
      completeBlock(@[error.localizedDescription]);
    } else {
      completeBlock(@[[NSNull null],@{
                        @"width": @(image.size.width),
                        @"height": @(image.size.height)
                        }]);
    }
  }];
}
@end
```

And use it like so in javascript:

```javascript
import { NativeModules } from 'react-native';
const ImagePreloadManager = NativeModules.ImagePreloadManager;
ImagePreloadManager.prefetch(url, function(err,result) {
				// if(err) ...
				// var {width,height,bytes} = result;
			});
```

Thats it. 

@nicklockwood But I think there is another solution integrated in react-native by now. But I can't remember it and I did not found it in the documentation?

**Comment by nicklockwood** [comment]
You can use Image.getSize(url) on iOS, which will do a partial preload. We don't have an official preloading solution yet.

**Comment by dcworldwide** [comment]
I'd imagine this is a common optimisation most apps make.  After testing my photography app on a medium BW network it's clear to me I need to implement image pre-fetching.

**Comment by ChristianTucker** [comment]
The `Image` component in React comes with a static method for preloading called `prefetch(url)` although based on the docs it's unclear how it's actually used. It's combined with 10+ examples and is a mess to follow.

**Comment by ronnyhartenstein** [comment]
@ChristianTucker Yes, the example (here)[https://facebook.github.io/react-native/docs/image.html#prefetch] is like a big ball of mud. But still it helps me.

In my scenario I want to prefetch a lot of really small images (~1000 of 1kB) and want to do it on start. So if the prefetch of an image URI is still finished, then `<Image ..>` should use them from store. Works well, but it **prefetches nearly every time**. If the image is still in cache, it shouldn't. My Apache log shows another reality indeed..

Maybe there are some switches to set the cache size?

Heres my litte script:
```
import React, { Component } from 'react'
import { Image } from 'react-native'
import _ from 'lodash'

// Image Prefetch: https://facebook.github.io/react-native/docs/image.html#prefetch

export default function(uris) {
    prefetch(uris, 0)
}

const prefetch = function(uris, i) {
    const uri = uris[i]
    let startTime = new Date()
    Image.prefetch(uri).then(() => {
        // console.log(`✔ Prefetch OK (+${new Date() - startTime}ms) from ${uri}`)
    }, error => {
        console.log(`✘ Prefetch failed (+${new Date() - startTime}ms) from ${uri}`)
    }).then(() => {
        if (i+2 <= uris.length) {
            prefetch(uris, i+1)
        }
    })
}
```

BTW: Why doesn't have the iOS simulator an offline mode?! To test it, I must go offline with my Mac.

**Comment by peacechen** [comment]
@ronnyhartenstein  Your example fetches the images in series (loads one, waits until it finishes, then loads the next), which slows down linearly with the number of images.  You could run all the prefetches in parallel like this:

```
var imagePrefetch = [];
for (let uri of uris) {
	imagePrefetch.push(Image.prefetch(uri));
}
Promise.all(imagePrefetch).then(results => {
	console.log("All images prefetched in parallel");
});
```

This seems to work for the most part, but I've seen it return before the images are fully prefetched if there are a high number of images, or possibly large images.  Perhaps they're overflowing the cache causing the first prefetched images to get pushed out?

**Comment by ronnyhartenstein** [comment]
@peacechen Thank you, `Promise.all` is indeed something I should try.

**Comment by mkozhukharenko** [comment]
how to check if image is already prefetched? How to clear prefetch image from a cache?
