### ISSUE TITLE
Android:Can't Signed release apk

### ISSUE THREAD

**Issue by terrytianliang** [facebook/react-native#23153]
## Environment

React Native Environment Info:
System:
OS: macOS 10.14
CPU: (8) x64 Intel(R) Core(TM) i5 CPU @ 1.60GHz
Binaries:
Node: v8.11.1
Yarn: v1.6.0
npm: v6.5.0
Watchman: v4.9.0 
SDKs:
Android SDK:
API Levels: 23, 25, 27, 28
Build Tools: 27.0.3, 28.0.3
System Images: android-28 | Google Play Intel x86 Atom
IDEs:
Android Studio: 3.2.1
npmPackages:
react: 16.6.3
react-native: 0.57.8

## Description

When I build debug apk ,It works well,But When I build and signed release  apk,It has an error:
Error: Cannot find module '/Users/silen/Desktop/Mall/packages/cbmms-android/node_modules/react-native/local-cli/cli.js',
I think it's probably because I changed the default project structure,
This is my folder architecture
![image](https://img1.crystalbeauty.cn/ok0jqndcrp.png)
As of now, any workarounds for this? Thanks
## Reproducible Demo

This is my Demo https://github.com/terrytianliang/RNDemo.git

**Comment by YarKaras** [comment]
You can edit your gradle files and it'll work
https://facebook.github.io/react-native/docs/signed-apk-android
