### ISSUE TITLE
TouchableOpacity don't call onPress callback when hitSlop is set (on some devices)

### ISSUE THREAD

**Issue by rammmukul** [facebook/react-native#23157]
## Environment
  we also built over expo.

  React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
      Memory: 40.01 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 25, 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-21 | Google APIs Intel x86 Atom_64, android-27 | Intelx86 Atom_64
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz =>0.57.1
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description
TouchableOpacity don't call onPress callback when hitSlop is set, (atleast on samsung note8).
It works on emulator.

## Reproducible Demo
https://snack.expo.io/@mukul.singraur/hitslop-bug

**Comment by ypyakymiv** [comment]
I'd like to find out more about your issue.

Just to clarify - you are using a Note 8 emulator for which the reproducible demo fails to call the onPress callback, correct? As you said both the android and iOS test emulators show correct behavior through the expo link.

**Comment by rammmukul** [comment]
It's not the note 8 emulator but the actual device, and some OPPO device too exhibit this behavior. Exact details of note 8 I don't know right now but I will post on Monday.

**Comment by anirudhbs** [comment]
The bug exists on my Samsung Galaxy S9 as well.
Device info: https://i.imgur.com/gxmMthW.jpg

**Comment by rammmukul** [comment]
So I encounter the same problem again today on samsung note8, this time hitSlop was not defined and it was calling onPressIn and then immediately calls onPressOut without calling onPress
