### ISSUE TITLE
[0.58] Inverted FlatList fast scrolling still doesn't work properly on Android P

### ISSUE THREAD

**Issue by lynrose10** [facebook/react-native#23158]
## Environment

**React Native Environment Info:**
System:
- OS: macOS High Sierra 10.13.6
- CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
- Memory: 27.94 MB / 8.00 GB
- Shell: 3.2.57 - /bin/bash

Binaries:
- Node: 8.11.2 - /usr/local/bin/node
- Yarn: 1.10.0 - /usr/local/bin/yarn
- npm: 5.6.0 - /usr/local/bin/npm
- Watchman: 4.9.0 - /usr/local/bin/watchman

Android SDK:
- API Levels: 28
- Build Tools: 28.0.3

IDEs:
- Android Studio: 3.1 AI-173.4720617

npmPackages:
- react: 16.6.3 => 16.6.3 
- react-native: 0.58.0 => 0.58.0

Test Device - Xiaomi Pocofone F1 - Android Pie - 9
![screen shot 2019-01-25 at 5 37 54 pm](https://user-images.githubusercontent.com/29659291/51740329-ada2f300-20ce-11e9-975b-8fcde5d1540a.png)

## Description

Fast scrolling will scroll back to where you start scrolling

Related to: #19434
The issue has been closed and locked but looks like the issue still exist even in 0.58 [commit b971c5b](https://github.com/facebook/react-native/commit/b971c5b)

## Reproducible Demo

1. react-native init InvertScrollTest
2. edit App.js
![screen shot 2019-01-25 at 5 42 20 pm](https://user-images.githubusercontent.com/29659291/51737849-9c56e800-20c8-11e9-8a40-02250ec8d8d7.png)

or similar from #19434
With Android P public beta installed -
https://snack.expo.io/BklXgV8Nk7

## Expected Behavior
Smooth scrolling
Fast scrolling up will not scroll down
Fast scrolling down will not scroll up

## Actual Behavior
Tested Device - Xiaomi Pocofone F1

Slow scroll up from INDEX - 0 then Fast scroll up 
![fast scroll up](https://user-images.githubusercontent.com/29659291/51740247-72a0bf80-20ce-11e9-90ab-80b1c9a1823c.gif)

Slow scroll down from INDEX - 19 then Fast scroll down 
![fast scroll down](https://user-images.githubusercontent.com/29659291/51739351-3a987d00-20cc-11e9-9485-0de9e49a9c3c.gif)

**Comment by TOTHO09** [comment]
i'm having the same issue .

**Comment by Thioby** [comment]
@TOTHO09 @lynrose10 
It seems to be fixed in 0.58.1

**Comment by godyolops** [comment]
Please fix this issue, same here.

**Comment by kelset** [comment]
Hey everyone, we are working on a new 0.58.2 which should have the fix - for some reason the commit was 'removed' from the 0.58 branch, we are now readding it. The new patch version should be out soon.

**Comment by lynrose10** [comment]
>  0.58.3 is out, can you let me know if this still happens?

Thank you very much. 😍 I will provide feedback once I tested it using the said device. Probably tomorrow. It's already late evening here. 😉

**Comment by lynrose10** [comment]
@kelset 
It now works properly with RN 0.58.3
Test Device - Xiaomi Pocofone F1 - Android 9

Fast scroll up
![fast scroll up fixed](https://user-images.githubusercontent.com/29659291/51964142-908c6c80-24a0-11e9-95df-29ebc63e53c2.gif)

Fast scroll down
![fast scroll down fixed](https://user-images.githubusercontent.com/29659291/51964147-92563000-24a0-11e9-92f7-5be00baa4ffa.gif)

**Comment by joey3060** [comment]
0.58.6 the problem still exists

**Comment by davidcort** [comment]
Same issue in the new 0.59.1 version :(

**Comment by muraterd** [comment]
I'm using version 0.59.1 with Android P and the issue is still there. The fling is not working as expected.

**Comment by ikrav4ic** [comment]
Same issue in the new 0.59.9 version

**Comment by liu-yuhuan** [comment]
i'm wondering if my situation not suitable for upgrade RN version, how can i fix this by my own?

**Comment by ha-family** [comment]
i'm wondering if my situation not suitable for upgrade RN version, how can i fix this by my own?
