### ISSUE TITLE
Fetch fails on some https in android 4

### ISSUE THREAD

**Issue by seriiix** [facebook/react-native#23151]
## Environment
React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i5 CPU         760  @ 2.80GHz
      Memory: 2.19 GB / 7.99 GB
    Binaries:
      Yarn: 1.10.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5014246

## Description
Some https URLs request fails on android 4 with no error while it's working on other androids (I've tested on some phones and it fails on 4.4.2 while successful on 5.0.2, 6.0.1, 9)

## Reproducible Demo
Create a project and paste the following code into your `App.js`. Make sure you are running on a device with android 4.4.2. It seems working on android 5+.
```
import React, {Component} from 'react';
import {Text, View} from 'react-native';

export default class App extends Component {

    componentDidMount() {
        /* this request fails on android 4 while its working on android 5+*/
        fetch('https://jsonplaceholder.typicode.com/posts/1')
            .then(resp => resp.json())
            .then(json => alert(`fail -> ${JSON.stringify(json)}`))
            .catch(err => {
                console.log(err)
            })


        /* this one is successful even on android 4 */
        fetch('https://www.json-generator.com/api/json/get/clfvuKZzOq?indent=2')
            .then(resp => resp.json())
            .then(json => alert(`success -> ${JSON.stringify(json)}`))
    }

    render() {
        return (
            <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
                <Text>https error on android 4</Text>
            </View>
        );
    }
}
```

**Comment by seriiix** [comment]
I fixed this problem based on [this](https://github.com/facebook/react-native/issues/7192) issue and this [gist](https://gist.github.com/patrickhammond/0b13ec35160af758d98c). I don't know if this issue should remain open or not. It's clearly a problem. Anyway, [Here'](https://gist.github.com/seriiix/093289bb28747e26301432a5fba6b060)s RN fix to it.

**Comment by dulmandakh** [comment]
it's fixed with https://github.com/facebook/react-native/commit/fab86ee4880f45ebfc0bd19d0e2fa1dbe15b7efc, please see commit description.
