### ISSUE TITLE
Button and Touchable onPress is not working in 0.58.0

### ISSUE THREAD

**Issue by castalonirenz** [facebook/react-native#23163]
i created a new project with version 0.58.0 and i tried to make some basic log in. but the onPress of the button is not working, and the button itself is not even touchable. but in previous version its working properly. is this a bug? thank you

**Comment by hramos** [comment]
Hey @castalonirenz, can you make sure you follow the bug report template? See https://github.com/facebook/react-native/issues/new/choose
