### ISSUE TITLE
Unexpected behavior when setting a width on PickerIOS

### ISSUE THREAD

**Issue by tylersmalley** [facebook/react-native#2316]
I have been unable to set the width of a PickerIOS element. My intention, is to have two side-by-side. I have tested this in an isolated environment with a new application (using the current version of react-native-cli), as well as in the UIExplorer example project producing two different results.

*With a new application*

Taking the PickerIOS example from UIExplorer. If you add `style={{ width: 100 }}` to either of the PickerIOS elements the actual view will not change, only the touchable area.

*In UIExporer PickerIOS example:*

If you add `style={{ width: 100 }}` to the second PickerIOS element, you will see that the width is reflected as expected. If you change the selection with the first picker, the width of the second will be reset to the full width.

**Comment by admmasters** [comment]
PickerIOS does not seem to properly respect flexbox styling, I have had this issue as well.

**Comment by shayne** [comment]
UIPicker, which PickerIOS wraps, is intended to use components for multiple segments, i.e. columns, in a Picker view. Unfortunately PickerIOS only supports a single component. The process is rather straightforward for adding multiple component capabilities for anyone willing to tackle it.

Closing
