### ISSUE TITLE
FlatList Horizontal not working but work for vertical

### ISSUE THREAD

**Issue by wahdatkashmiri33** [facebook/react-native#23178]
![image](https://user-images.githubusercontent.com/16012220/51812289-e1e90000-22d6-11e9-80d8-bd6f3e82a6b0.png)
this is what it shows when i try to  show images in  horizontal direction  in flatlist
`<View style = {{flex :1}}>
      
      <FlatList
      style ={{flex:1}}
      horizontal = {true}
      data = {this.state.trailerData}
      renderItem = {
        ({item}) =>
         <Image
        source = {{uri: "http://img.youtube.com/vi/" +item.key+"/0.jpg"}}
         style={{flex:1,height:200,resizeMode:'contain',borderColor:"#ccc",borderWidth: 2}} 
            
       />

      }
     
      keyExtractor={(item, index) => item.id}
      
      >

      </FlatList>
      
      
      </View>`

**Comment by kelset** [comment]
If you don't fill the template, we can't help you 😓
