### ISSUE TITLE
bug with react-native link in android and windows

### ISSUE THREAD

**Issue by misaku** [facebook/react-native#23176]
## Environment

 React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
      Memory: 2.66 GB / 15.89 GB
    Binaries:
      Yarn: 1.13.0 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.5.0 - C:\Program Files\nodejs\npm.CMD
      Watchman: 4.9.4 - D:\servers\watchman\watchman.EXE
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5199772
## Description

When run react-native link in windows and android
the url use \ and not /
for example:
```project(':react-native-gesture-handler').projectDir = new File(rootProject.projectDir, '..\node_modules\react-native-gesture-handler\android')```
and to fix to:
```project(':react-native-gesture-handler').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-gesture-handler/android')```
## Reproducible Demo

react-native link in windows

**Comment by kelset** [comment]
That's a good idea, but maybe it's worth working directly with https://github.com/react-native-community/react-native-cli which is the new place where the CLI will be hosted in the future 👍

**Comment by alainib** [comment]
same error for me
