### ISSUE TITLE
[Async] Use of async function throws Syntax error

### ISSUE THREAD

**Issue by NishanthShankar** [facebook/react-native#2318]
Adding code form http://www.reactnative.com/react-native-meets-async-functions/ 
<pre><code> async function fetchJSONAsync(url) { 
    let response = await fetch(url);
    let body = await response.json();
    return body;
 }</code></pre>

The above code throws a syntax error

**Comment by ide** [comment]
You need to have babel configured. There's a section in the post about how to do that.

**Comment by NishanthShankar** [comment]
Sorry my bad. Did not see the link to medium. Will look into it. thanks for the timely response
