### ISSUE TITLE
Integrate existing app with React-Native【how to pass data from objectc to js-file】

### ISSUE THREAD

**Issue by zeo112140** [facebook/react-native#2319]
Integrate existing app with React-Native【how to pass data from objectc to jsfile】

thanks a lot,everyone.
I use this method to integrate existing app with react-native.
url  :   http://facebook.github.io/react-native/docs/embedded-app-ios.html#content
but i want to pass data from objectc to js--file
for example ,tap a link in objectc-uiview jump to reactnative index-ios-js
and pass param data to it,how can i do this?

**Comment by axelg12** [comment]
+1 I am having the same question

**Comment by javache** [comment]
You can pass this data through the initialProperties dictionary of the [RCTRootView initialiser](https://github.com/facebook/react-native/blob/2f6e7336cb96bf14d47554ae0db1836075ea809e/React/Base/RCTRootView.h#L33). It will be available in your root component's props.

**Comment by zeo112140** [comment]
I have try this method,and can pass static param to js file,but if the param is a dynamic data,the react native view is first initialiser,and can't pass the dynamic data to it.
thank you very much for answer.
--------------------------------------------------------------------------------------------------------------------------------
RCT_EXPORT_METHOD can  make the static problem.
#import "RCTBridge.h"
#import "RCTEventDispatcher.h"

@implementation CalendarManager

@synthesize bridge = _bridge;

- (void)calendarEventReminderReceived:(NSNotification *)notification
{
  NSString *eventName = notification.userInfo[@"name"];
  [self.bridge.eventDispatcher sendAppEventWithName:@"EventReminder"
                                               body:@{@"name": eventName}];
}

@end

--------------------------------------------------------------------------------------------------------------------------------------
I am not have any idea about the problem
Now I save the param in memory ,and get it when component is did mounted.
