### ISSUE TITLE
pod install create libReact-4072a36b.a which results in duplicate libraries

### ISSUE THREAD

**Issue by Vakil-Parth** [facebook/react-native#23199]
## Environment

React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
      Memory: 185.16 MB / 8.00 GB
      Shell: 3.2.57 - /bin/sh
    Binaries:
      Node: 8.11.3 - /usr/local/bin/node
      Yarn: 1.9.2 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.2, 27.0.3, 28.0.1, 28.0.2
        System Images: android-25 | Google APIs ARM EABI v7a, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: 0.58.2 => 0.58.2
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
## Description

pod install commmand creates  libReact-4072a36b.a i also inserted pod install script to remove it but did not work.

**Even if i remove it manually, pod install command creates with libReact-xxxxxx.a  **

here is my pod file
```target 'new_mays_translation' do
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTText',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTSettings',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTAnimation',
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'Firebase/Core'
  pod 'Firebase/MLVision'
  pod 'Firebase/MLVisionTextModel'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'
  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  target 'new_mays_translation-tvOSTests' do
    inherit! :search_paths
    pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  end

  target 'new_mays_translationTests' do
    inherit! :search_paths
  end

end
post_install do |installer|
    installer.pods_project.targets.each do |target|
      targets_to_ignore = %w(React yoga)
      if targets_to_ignore.include? target.name
        target.remove_from_project
      end
    end
  end```

**Comment by Vakil-Parth** [comment]
> ## Environment
> React Native Environment Info:
> System:
> OS: macOS High Sierra 10.13.6
> CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
> Memory: 185.16 MB / 8.00 GB
> Shell: 3.2.57 - /bin/sh
> Binaries:
> Node: 8.11.3 - /usr/local/bin/node
> Yarn: 1.9.2 - /usr/local/bin/yarn
> npm: 5.6.0 - /usr/local/bin/npm
> Watchman: 4.9.0 - /usr/local/bin/watchman
> SDKs:
> iOS SDK:
> Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
> Android SDK:
> API Levels: 23, 25, 26, 27, 28
> Build Tools: 23.0.1, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.2, 27.0.3, 28.0.1, 28.0.2
> System Images: android-25 | Google APIs ARM EABI v7a, android-28 | Google APIs Intel x86 Atom
> IDEs:
> Android Studio: 3.1 AI-173.4819257
> Xcode: 10.1/10B61 - /usr/bin/xcodebuild
> npmPackages:
> react: 16.6.3 => 16.6.3
> react-native: 0.58.2 => 0.58.2
> npmGlobalPackages:
> create-react-native-app: 1.0.0
> react-native-cli: 2.0.1
> react-native-git-upgrade: 0.2.7
> 
> ## Description
> pod install commmand creates libReact-4072a36b.a i also inserted pod install script to remove it but did not work.
> 
> **Even if i remove it manually, pod install command creates with libReact-xxxxxx.a **
> 
> here is my pod file
> 
> ```
>   pod 'React', :path => '../node_modules/react-native', :subspecs => [
>     'Core',
>     'CxxBridge',
>     'DevSupport',
>     'RCTText',
>     'RCTActionSheet',
>     'RCTAnimation',
>     'RCTGeolocation',
>     'RCTImage',
>     'RCTLinkingIOS',
>     'RCTSettings',
>     'RCTNetwork',
>     'RCTWebSocket',
>     'RCTAnimation',
>   ]
>   pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
> 
>   pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
>   pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
>   pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
> 
>   pod 'Firebase/Core'
>   pod 'Firebase/MLVision'
>   pod 'Firebase/MLVisionTextModel'
> 
>   pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
> 
>   pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'
>   pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'
> 
>   target 'new_mays_translation-tvOSTests' do
>     inherit! :search_paths
>     pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
>   end
> 
>   target 'new_mays_translationTests' do
>     inherit! :search_paths
>   end
> 
> end
> post_install do |installer|
>     installer.pods_project.targets.each do |target|
>       targets_to_ignore = %w(React yoga)
>       if targets_to_ignore.include? target.name
>         target.remove_from_project
>       end
>     end
>   end```
> ```

**Comment by roshangm1** [comment]
Any workarounds for this ?
