### ISSUE TITLE
`axios/index` does not exist in the Haste module map

### ISSUE THREAD

**Issue by sanjaykumarbal** [facebook/react-native#23203]
I upgraded my app from 0.55.5 to 0.58.3. While running the app on ios simulator, i am getting the below error:

Loading dependency graph, done.
error: bundling failed: Error: Unable to resolve module axios/index from /Users/testuser/Documents/Work/Projects/MyApp/src/api/http_methods/environment.js: Module axios/index does not exist in the Haste module map.

Tried the following steps to resolve by referring facebook/react-native#4968

    Clear watchman watches: watchman watch-del-all.
    Delete the node_modules folder: rm -rf node_modules && npm install.
    Reset Metro Bundler cache: rm -rf /tmp/metro-bundler-cache-* or npm start -- --reset-cache.

I am still getting the same issue.

**Comment by dagenius007** [comment]
Any solution yet

**Comment by Tyldar** [comment]
Having the same trouble here
