### ISSUE TITLE
Warning:WebView has been extracted from react-native core and will be removed in a future release

### ISSUE THREAD

**Issue by Jayxiang** [facebook/react-native#23214]
## Environment

iOS SDK:
Platforms: iOS 12.1, macOS 10.14
npmPackages:
"react": "16.6.3",
 "react-native": "0.58.0",
 "react-native-gesture-handler": "^1.0.15",
 "react-navigation": "^3.0.9"
"react-native-root-toast": "^3.0.2"

## Description

I will get this warning when I add 'react-native-root-toast', but I didn't use webview with it.

## Reproducible Demo

[skip envinfo]

**Comment by dulmandakh** [comment]
this warning is from **react-native** and new to 0.58. So please use WebView from **react-native-webview** instead of **react-native**.

**Comment by Jayxiang** [comment]
Yes, I know the meaning of this warning, but my current problem is that I did not use and import webview, but this warning will appear.

**Comment by vincentbriglia** [comment]
i think what @Jayxiang is trying to say is that there is no way to disable the warning. F.ex when running some tests for a component that doesn't use webview, I get 
![image](https://user-images.githubusercontent.com/452811/52540549-f58e6f00-2d8a-11e9-83f8-4e55b234f032.png)

I am aware that the move to react-native-webview is an in-progress task, but It would be preferable if we could dismiss or suppress the error.
