### ISSUE TITLE
Text 'allowFontScaling' not adjusting font size properly when Emoticons are included in text

### ISSUE THREAD

**Issue by Simek** [facebook/react-native#23213]
## Environment
```  
React Native Environment Info:
    System:
      OS: macOS 10.14
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.8.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.7.0 => 16.7.0 
      react-native: 0.58.3 => 0.58.3
```

## Description
As you can see on the screenshot below two lines at bottom do not scales properly with `allowFontScaling` property set to `true`. It seems like emoticons are responsible for that behaviour/bug.

![img_5806](https://user-images.githubusercontent.com/719641/51969193-17772000-2474-11e9-9036-af18584741bc.PNG)

**Removing emoticon from text fixes that issue (second line):**

![img_bc18d567d6d2-1](https://user-images.githubusercontent.com/719641/51969390-93716800-2474-11e9-8046-0a6b5dfa2ff3.jpeg)

It also seems that this bug do not occur in Expo in-browser preview. Maybe iOS global font scaling messing with thing up?

**Also I would like to note, that scaling works properly if `Text` starts with emoji.** This my be related to issue #14981.

## Reproducible Demo
Run on you own device:
https://snack.expo.io/@simek/text-adjustsfontsizetofit-bug

**Comment by Simek** [comment]
Latest Expo SDK (32.0.0) includes RN 0.57 and that's the reason why I used this version in environment report. On my machine I'm using the latest RN and I can confirm that on latest version (0.58.3) problem still occurs.

**Comment by anoopmm** [comment]
'allowFontScaling' not working on nested <Text>
