### ISSUE TITLE
jsireact headers are not found during build

### ISSUE THREAD

**Issue by jantebeest** [facebook/react-native#23217]
## Environment

  React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
      Memory: 1.59 GB / 32.00 GB
      Shell: 5.7 - /usr/local/bin/zsh
    Binaries:
      Node: 11.8.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: ^0.58.3 => 0.58.3
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-create-library: 3.1.2
      react-native-wahed-onfido-sdk: 1.0.0

## Description

Building react-native fails as it cannot find the `jsireact` headers in the correct location. 
They are referenced as `jsireact/*.h`, however the directory is under `ReactCommon/jsiexecutor/jsireact` (has it been moved?). 

Copying the directory to `ReactCommon/jsireact` solves the build.

**Comment by hramos** [comment]
What steps did you follow to build React Native?

**Comment by andresmtz98** [comment]
Same issue here after upgrade to .58.3 :/

**Comment by jantebeest** [comment]
@hramos I created a new library project using `react-native-create-library`, then added the `React` libs to my Podfile and did a `pod install`. After that it doesn't build from Xcode. The error is very clear.

**Comment by xiaoyangrun** [comment]
I met the same problem

**Comment by amccarri** [comment]
There are a couple workarounds that can get you unstuck.  One is to prepend all the failing imports with `jsiexecutor/` ... the other is you can update the header search paths for the JSIExecutor to include the new folder which IMO would be the preferred approach because it doesn't require you to change source code.  After doing that just run `pod install` again and you should be good to go.

**Comment by fsfhiyg** [comment]
@hramos I created a new library project using react-native-create-library, then added the React libs to my Podfile and did a pod install. After that it doesn't build from Xcode. The error is very clear.

👍 4

**Comment by andresmtz98** [comment]
> Same issue here after upgrade to .58.3 :/
> 
> ![image](https://user-images.githubusercontent.com/18200380/51994548-02ec5500-247f-11e9-8114-0db88bb23b2c.png)

How do i fix that error? To me still happening :/, now with .58.4
