### ISSUE TITLE
how to build apk in react native version 0.58

### ISSUE THREAD

**Issue by ydv0121** [facebook/react-native#23216]
how to build apk in react native version 0.58.0 
with this command its not working

react-native bundle --dev false --platform android --entry-file index.js --bundle-output ./android/app/build/intermediates/assets/debug/index.android.bundle --assets-dest ./android/app/build/intermediates/res/merged/debug

because assets folder not generating

**Comment by rfernandotimedev** [comment]
hey, just follow this steps! it helped me.

(I'm sorry if it's not possible to share links here)
https://medium.com/@adityasingh_32512/solved-unable-to-load-script-from-assets-index-android-bundle-bdc5e3a3d5ff
