### ISSUE TITLE
LICENSE-examples file does not exist in the root of the repo, as referenced by /Libraries/Wrapper/Example/

### ISSUE THREAD

**Issue by luisapace** [facebook/react-native#23215]
Hi, my team would like to use the package react-native 0.57.3 and to approve that I've to verify all its licenses (included those of all of the modules included), and to do that I've to analyze its source code.

Now I've noted that all the modules in react-native_0.57.3-0/Libraries/Wrapper/Example/
declare:
**_Thanks a lot.This source code is licensed under the license found in the
// LICENSE-examples file in the root directory of this source tree._**

But I cannot find any LICENSE-examples file in the source of react-native 0.57.3 . 
Could you please tell me what is the license of the code in react-native_0.57.3-0/Libraries/Wrapper/Example/ directory?

Thanks for your support.

**Comment by hramos** [comment]
Thanks for the report. Can you raise this in https://github.com/react-native-community/react-native-releases/issues?

**Comment by hramos** [comment]
After looking at master, this issue is not unique to `0.57.3` and it's not matter of simply updating the 0.57 release. Reopening so we can track a fix for this in master.

**Comment by luisapace** [comment]
Hi, any news on this? Thanks.

**Comment by orta** [comment]
I shipped a PR bringing the license in-line with the rest of the Examples in this repo
