### ISSUE TITLE
How to distinguish react native compoent in native?

### ISSUE THREAD

**Issue by KeithZhang** [facebook/react-native#2321]
Actually, I want to extend native code to implement a function like ActionSheetIOS.showShareActionSheetWithOptions,the ActionSheetIOS.showShareActionSheetWithOptionsfunction only accepts a NSString, I need a common function which can pop any react native component you want.

so the question is, how to distingguish react native component in native?
if I export a function like follow:
 popComponent({
   component: ReactNativeComponent
})

in Object-C how to known ReactNativeComponent?

**Comment by grittymindy** [comment]
I think you could use the reactTag

**Comment by brentvatne** [comment]
Indeed, you need to use a reactTag -- I'd suggest searching the source or asking for more help on StackOverflow :)
