### ISSUE TITLE
Multiline TextInput Vertical Alignment Bug on iOS

### ISSUE THREAD

**Issue by vjsingh** [facebook/react-native#23222]
## Environment
Environment:
  OS: macOS 10.14.1
  Node: 10.4.0
  Yarn: 1.7.0
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: Xcode 10.1 Build version 10B61
  Android Studio: 3.2 AI-181.5540.7.32.5056338

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz => 0.55.4

## Description
The text in TextInputs are not vertically aligned on iOS when multiline is set to true. It works properly on Android.

## Reproducible Demo
https://snack.expo.io/@vjsingh/ios-multiline-textinput-vertical-alignment-bug

**Comment by cpojer** [comment]
We changed a number of formatting related things around TextInput to be part of 0.60, and I believe this will be fixed with it.

**Comment by kingdaro** [comment]
Still experiencing this: https://snack.expo.io/@kingdaro/ios-multiline-textinput-vertical-alignment-bug

**Comment by nickL** [comment]
Same, I'm still seeing this issue on 0.60. @cpojer can this be re-opened?

**Comment by dvuvne** [comment]
This issue still exists in version 0.61.2

**Comment by maxhudson** [comment]
still an issue
