### ISSUE TITLE
Got JS Exception: Unexpected keyword 'const'. Const declarations are not supported in strict mode.

### ISSUE THREAD

**Issue by GospelHW** [facebook/react-native#23223]
I want to upgrade RN to 0.57.0 from 0.38 
my step is:
1.npm install --save react-native@0.57.0
2.react-native run-android 

## Environment

React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.4
      CPU: (8) x64 Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz
      Memory: 40.00 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.6.0 - /usr/local/bin/node
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 22, 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.3, 27.0.3, 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.5.2 => 16.7.0
      react-native: ^0.57.0 => 0.57.0
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description

<img width="1376" alt="2019-01-31 10 34 31" src="https://user-images.githubusercontent.com/24928406/52026740-e49c5d00-2543-11e9-93a0-71212ef82adf.png">

and Devices show 
![device-2019-01-31-104119](https://user-images.githubusercontent.com/24928406/52027002-caaf4a00-2544-11e9-9ad0-aa89a4bc8017.png)

Do you know what is exception?Please help me.thank you.

**Comment by GospelHW** [comment]
@react-native-bot below is Env info:
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.4
      CPU: (8) x64 Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz
      Memory: 40.00 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.6.0 - /usr/local/bin/node
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 22, 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.3, 27.0.3, 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.5.2 => 16.7.0
      react-native: ^0.57.0 => 0.57.0
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by GospelHW** [comment]
I was upgrade last version is v0.58.3, but this problem show agin now ...
Please help me 
end stack is 
<img width="1351" alt="2019-02-01 3 30 54" src="https://user-images.githubusercontent.com/24928406/52109000-ef83ea00-2636-11e9-911b-78d51928c45a.png">
devices show is 
![device-2019-02-01-144247](https://user-images.githubusercontent.com/24928406/52108993-e98e0900-2636-11e9-881c-89a9b1ad8185.png)

**Comment by GospelHW** [comment]
@react-native-bot Are you there ?

**Comment by GospelHW** [comment]
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.4
      CPU: (8) x64 Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz
      Memory: 261.44 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.6.0 - /usr/local/bin/node
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 22, 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.3, 27.0.3, 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.6.3 => 16.7.0
      react-native: ^0.58.3 => 0.58.3
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by dulmandakh** [comment]
please install and use react-native-git-upgrade tool. just installing new react-native from NPM is not enough because usually it requires changes in Android and XCode projects.

**Comment by dulmandakh** [comment]
Also please make sure that RN modules are compatible with the latest version, and you're not using deprecated/remove feature.

**Comment by anarpafran** [comment]
i have this error, please help

**Comment by GospelHW** [comment]
@dulmandakh Okay ,I will try to do it.see you late

**Comment by GospelHW** [comment]
@dulmandakh I use react-native-git-upgrade tool , After the upgrade, it is still the previous version.

**Comment by anarpafran** [comment]
Return at the version 57. This funtioned for me

**Comment by dulmandakh** [comment]
quick search reveal that it's related to babel config. could you please check if removing .babelrc helps, and make sure that you have backup.

**Comment by only1chi** [comment]
Hi, I'm having the same issue, using RN 0.58.4. Don't know how to resolve this. Any ideas?

**Comment by agustin107** [comment]
I'm having the same issue now :/

**Comment by agustin107** [comment]
```
React Native Environment Info:
    System:
      OS: Linux 4.4 elementary OS 0.4.1 Loki
      CPU: (4) x64 Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
      Memory: 619.17 MB / 7.67 GB
      Shell: 5.1.1 - /usr/bin/zsh
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      Yarn: 1.13.0 - ~/.yarn/bin/yarn
      npm: 6.4.1 - ~/.config/yarn/global/node_modules/.bin/npm
    SDKs:
      Android SDK:
        API Levels: 22, 23, 26, 27, 28
        Build Tools: 23.0.3, 24.0.3, 26.0.3, 27.0.3, 28.0.2, 28.0.3
        System Images: android-26 | Google Play Intel x86 Atom, android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: ^0.58.5 => 0.58.5 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1`
```

**Comment by agustin107** [comment]
Getting back to 0.57.8 version solve this

**Comment by sdee3** [comment]
Can confirm that this is indeed the solution (for now). Thanks @agustin107!!!

**Comment by CatapultJesse** [comment]
Can you make sure you're babel rc is correct (includes:
```
"presets": [
        "module:metro-react-native-babel-preset",
]
```
and you have followed the breaking changes updates from https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md#updating-to-this-version

**Comment by luvletterldl** [comment]
I'm having the same issue now

**Comment by luvletterldl** [comment]
React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
      Memory: 31.39 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.5.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.8.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 21, 23, 26, 27, 28
        Build Tools: 21.1.2, 22.0.1, 23.0.2, 27.0.3, 28.0.2, 28.0.3
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.58.6 => 0.58.6 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

**Comment by grabbou** [comment]
Hello there 👋 this issue doesn't have a repro (which means, a react-native init-ed project with the minimal changes that leads to creating the same issue you are reporting). Unfortunately, I have no way of helping you in a meaningful way – there is no easy way for me to recreate the situation and check that the issue reported is still there when changing the code.

Because of this, we are going to close this issue - but if a repro is shared, we are happy to reopen it 🤗

**Comment by SlowDony** [comment]
React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 107.77 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.14.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 24, 26
        Build Tools: 26.0.1
        System Images: a...s_playstore | Google Play Intel x86 Atom Sys...
    IDEs:
      Android Studio: 2.3 AI-162.4069837
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.8 => 0.59.8
    npmGlobalPackages:
      react-native-cli: 2.0.1
