### ISSUE TITLE
adjustsFontSizeToFit can't handle explicit line breaks

### ISSUE THREAD

**Issue by michaelknoch** [facebook/react-native#23237]
## Description
I recently experienced an issue with the `<Text />` component, in particular with the automatic font size shrinking on iOS. When rendering Text with explicit line break and `adjustsFontSizeToFit` enabled it does not render any characters after the newline. I would expect that it takes the longest line into account and then shrinks the font size of the whole text so that the longest line fits in the container.

It renders correctly without the explicit line break. I think the view has an incorrect height and therefore only renders the first line. The second line will be visible when setting an explicit height.
If you guys have any workaround in mind or some advice where to get started fixing this, I would love to hear some feedback.

**Example:**

```js
 <Text 
    adjustsFontSizeToFit
    numberOfLines={2}
    style={styles.welcome}
>
    {"First Line\nSecond line with some more text"}
</Text>
```

<img width="529" alt="screenshot 2019-01-31 at 23 08 39" src="https://user-images.githubusercontent.com/5617793/52088787-2d3c3080-25ad-11e9-86ad-a2f25125a1d4.png">

## Reproducible Demo
I created a demo to reproduce the issue. Clone it, install npm dependencies and run on your iOS device/simulator.

https://github.com/michaelknoch/AdjustFontSizeToFitIos-Reproduction

## Environment
```
react-native info

  React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
      Memory: 139.47 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.3 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 24, 25, 26, 27
        Build Tools: 23.0.1, 23.0.2, 23.0.3, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 27.0.0, 27.0.3, 28.0.3
        System Images: android-22 | Google APIs ARM EABI v7a
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.58.3 => 0.58.3 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      react-native: 0.56.0
```

**Comment by CatapultJesse** [comment]
Looks like there's an order with with calculations are done in as the container itself can include extra spacing when not needed
Snack Repro: https://snack.expo.io/@jkcooper/rn23237---adjustsfontsizetofit-line-breaks

**Comment by CatapultJesse** [comment]
Could be related to: https://github.com/facebook/react-native/issues/19117

**Comment by kelset** [comment]
👋 there - I can confirm that on RN 0.59 this issue is still present.

We are going to look into it more over the next few months, but please feel free to work more on it if you have time / feel that you may have a good idea of a fix 🤗

**Comment by michaelknoch** [comment]
actually it's still a thing
