### ISSUE TITLE
RN v0.58.3 Unable to resolve module `Subscribable`,it path changed?

### ISSUE THREAD

**Issue by GospelHW** [facebook/react-native#23243]
In RN v0.58.3 the module `Subscribable`'s path changed ?why it not in node_modules/React-Native/Libraries/Components/?

## Environment

React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.4
      CPU: (8) x64 Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz
      Memory: 27.82 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.6.0 - /usr/local/bin/node
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 22, 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.3, 27.0.3, 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.6.3 => 16.7.0
      react-native: ^0.58.3 => 0.58.3
    npmGlobalPackages:
      react-native-cli: 2.0.1
## Description

Just upgrade RN to 0.58.3 from 0.38 to solve other problem，but now I have more problems。。。

![device-2019-02-01-140326](https://user-images.githubusercontent.com/24928406/52105925-a1b5b480-262b-11e9-9b2c-e97ecc57bb2f.png)
<img width="1434" alt="2019-02-01 2 02 53" src="https://user-images.githubusercontent.com/24928406/52105936-abd7b300-262b-11e9-8156-c79bc37ce80c.png">

**Comment by cpojer** [comment]
Yes, this module is not part of RN any longer. Please find an older release of React Native and copy the source file into your own project.
