### ISSUE TITLE
So many issues with 0.58.x release

### ISSUE THREAD

**Issue by nwaughachukwuma** [facebook/react-native#23257]
Hi awesome team,

There are just many issues with the 0.58.x versions. I was trying to upgrade from 0.57.8 but spent the whole day resolving one issue or the other, very painful really. Either one library is missing, or a require statement cannot be found. Most arose when bundling the code (Sorry I can't be any more specific). I had to return to 0.57.8, but am hoping the team resolves the issues.

**Comment by dulmandakh** [comment]
Please provide specific issues so we can investigate and resolve them.

**Comment by nwaughachukwuma** [comment]
@dulmandakh I just tried again and got:
bundling failed: Error: Unable to resolve module `react-native/Libraries/Image/ImageSourcePropType` from `~\node_modules\@merryjs\photo-viewer\index.js`: Module `react-native/Libraries/Image/ImageSourcePropType` does not exist in the Haste module map

**Comment by dulmandakh** [comment]
RN is migrating to Flow, thus most PropTypes are removed. Please ask **photo-viewer** to make it work with latest RN.
