### ISSUE TITLE
[TextInput] Does not respect border[TopLeft|BottomLeft|BottomRight|TopRight]Radius style

### ISSUE THREAD

**Issue by jaygarcia** [facebook/react-native#2325]
According to the documentation, TextInput should inherit from View Styles.
https://facebook.github.io/react-native/docs/text.html#style

However, the following borderRadius styles do not get applied and no exception or warnings (that i could see) are thrown.

```
borderTopLeftRadius
borderTopRightRadius
borderBottomLeftRadius
borderBottomRightRadius
```

**Comment by browniefed** [comment]
This still happening @jaygarcia ?

**Comment by jaygarcia** [comment]
@browniefed , negative. This must have been fixed w/out this issue being visited. 

Thanks :)
