### ISSUE TITLE
WebView Chrome issue

### ISSUE THREAD

**Issue by andrewazevedo** [facebook/react-native#23252]
## Environment

Environment:

  OS: macOS 10.14.2
  Node: 8.12.0
  Yarn: 1.12.3
  npm: 6.4.1
  Watchman: 4.9.0
  Xcode: Xcode 10.1 Build version 10B61
  Android Studio: 3.2 AI-181.5540.7.32.5056338

Packages: (wanted => installed)

  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

## Description

I've been using `WebView` for a while for android and on January 29 the Chrome upgrades to version `72.0.3626.76` and the  WebView no longer works for android with that Chrome version. I'm trying to render a plain `html` code inside the app like this:

```
<WebView
   ref={wv => this._webview = wv}
   style={{ flex: 1, backgroundColor: dark ? colors.darkReader : '#fff' }}
   source={{ html: generateHtml(this.props.title, this.props.htmlText) }}
   javaScriptEnabled
   injectedJavaScript={script}
   onMessage={this.handleMessage}
   collapsable={false}
   onNavigationStateChange={this.handleNavigationStateChange}
/>
```
Unfortunately it does not work after the chrome update, instead a white screen appears and this error appears: `Script error`.

## Reproducible Demo

My html code returned by `generateHtml` function: 

```
  <html>
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta charset="utf-8" />
    </head>
    <style id="st"></style>
    <style>
      .dark {
        color: #fff;
        background-color: ${colors.darkReader};
      }
      body {
        padding-top: ${Platform.OS === 'ios' ? '33px' : '0px'};
        font-family: Palatino;
        -webkit-overflow-scrolling: none;
      }
      #content {
        padding: 0 10px;
      }
      #title {
        margin: 25px 15px auto;
        -webkit-user-select: none;
      }
      #padder { height: 30vh; }
    </style>
    <body>
      <h1 id="title" >
        ${title}
      </h1>
      <div id="content">
        ${text}
      </div>
      <div id="padder">
      </div>
    </body>
  </html>

```

**Comment by hramos** [comment]
The WebView component was forked by the community, and the one in this repository is deprecated. You can use the new component by pulling in https://github.com/react-native-community/react-native-webview. If your issue is still reflected in the forked component, you can open a new issue in the new repo. Thanks for understanding.
