### ISSUE TITLE
Remote Debug in Prod mode after 0.58

### ISSUE THREAD

**Issue by in4core** [facebook/react-native#23250]
Remote Debug JS - works only DEV mode after 0.58 , but in 0.57 all good. 
When starts it in Prod mode we have some errors 
*Cannot read property 'Constants' of null*
*Module AppRegistry is not a registered callable module (calling runApplication)*

React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
      Memory: 1.68 GB / 7.95 GB
    Binaries:
      npm: 6.7.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5199772

Dependencies :
"dependencies": {
    "react": "16.6.3",
    "react-native": "0.58.3",
    "react-native-gesture-handler": "^1.0.15",
    "react-native-img-cache": "^1.6.0",
    "react-native-section-list-get-item-layout": "^2.2.3",
    "react-native-vector-icons": "^6.2.0",
    "react-navigation": "^3.0.9",
    "rn-fetch-blob": "^0.10.15"
  },

**Comment by axlider** [comment]
I had the same Problem running on Device Android.
In my case I had "Debug JS Remotely" activated and "JS DEV Mode" deactivated (Developer Menu).
When I activated "JS DEV Mode" the error message vanished. 
I am observing this since  RN version 0.57.

**Comment by xSmoggeRx** [comment]
I get same error here. I'm running RN version 0.59.9
