### ISSUE TITLE
Can't find simulator for "iPhoneX"

### ISSUE THREAD

**Issue by sarahtieu** [facebook/react-native#23256]
## Environment
I'm running npm inside the react-native app
Just downloaded latest npm and xcode

## Description
Reproduce: Running npm run ios, I get that it can't find simulator for "iPhoneX"
Fix / Bugs: in local-cli/runIOS/findMatchingSimulator.js:
L42 which checks that the version of the simulator is an iOS or tvOS always fails (namely, the version of the simulator is com.apple.[some other things].iOs/tvOS. Namely the following if statement checks that the version starts with iOS or tvOS when it should be checking that of the text following the latest period, the text starts with iOs or tvOS.
L55 which was supposed to fix this bug, the isAvailable field is actually boolean true instead of string 'YES'

**Comment by eric-PearSports** [comment]
change this file:

/node_modules/react-native/local-cli/runIOS/findMatchingSimulator.js

line 42, to: if (!version.startsWith('**com.apple.CoreSimulator.SimRuntime.iOS**') && !version.startsWith('tvOS')) {

**Comment by yayajacky** [comment]
That change works for me, after I have installed latest xcode beta, and removed the beta.

**Comment by sonaye** [comment]
Facing this after Xcode simulators update to 12.2 (RN 0.57.8).

**Comment by d4ins** [comment]
So it might help for the latest issue (appeared 27 March 2019) after xCode simulator update.

So this file:
`/node_modules/react-native/local-cli/runIOS/findMatchingSimulator.js`

Line 42, like above and replace `if (!version.startsWith('iOS') && !version.startsWith('tvOS')) {` with something like `if (!version.includes('iOS') && !version.includes('tvOS')) {`

**Comment by sonaye** [comment]
I would like to add that it works when building directly from Xcode.
