### ISSUE TITLE
Multiple permission dialogs coming on react native android app

### ISSUE THREAD

**Issue by manik96m** [facebook/react-native#23265]
## Environment
OS: macOS 10.14.1
  Node: 10.15.0
  Yarn: 1.12.1
  npm: 6.4.1
  Watchman: 4.9.0
  Xcode: Xcode 10.1 Build version 10B61
  Android Studio: 3.0 AI-171.4408382

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

## Description

I have come up with a problem while asking for the Location Permission on react native android app.

**Expected Flow** - If a user have not given the Location permission and the app goes to the background and when again it is opened the Permission dialog box should come.

**Issue** - The permission dialog box is coming twice if the user denies the permission again.

## Reproducible Demo
async componentDidMount() {
  await locationServices(this.setGeoLocation, this.locationServicesError); // asking for location permission
  AppState.addEventListener(commonStrings.event.change, this.handleAppStateChange); // adding a listener for listening to app state changes
}

async handleAppStateChange(nextAppState) {
  if (this.state.appState.match(/inactive|background/) && nextAppState === 'active') {
     locationServices(this.setGeoLocation, this.locationServicesError); // asking for permission again when the app becomes active
  } 
  this.setState({ appState: nextAppState }); // saving the current app state to the local state of the component
};

**Why is the issue coming?**
The Permission dialog is making the app go to background which triggers the handleAppStateChange function again.

**Comment by fredrik-jarnbrost** [comment]
I'm seeing this issue with:
react: 16.6.3,
react-native: 0.58.5
