### ISSUE TITLE
Possibble unhandled promise reaction(id:2): ReferenceError:Can't find variable: responseJson

### ISSUE THREAD

**Issue by amilabgunarathne** [facebook/react-native#23260]
I have app with PHP back end and at first it worked fine.but suddenly appears this error now.

![screenshot_1549079567](https://user-images.githubusercontent.com/24237873/52159608-ada58300-26cc-11e9-9c03-78ee44f6285e.png)

**Comment by fsfhiyg** [comment]
We are automatically closing this issue because it does not appear to follow any of the provided issue templates.

👉 Click here if you want to report a reproducible bug or regression in React Native.
