### ISSUE TITLE
App does not build in XCode 7

### ISSUE THREAD

**Issue by ecompton3** [facebook/react-native#2326]
We've been hoping to use Xcode 7 with our react native application both in preparation for the rollout of iOS9 and to get access to the UI testing functionality built in. Unfortunately when we try to compile the project we get the following error:

Null passed to a callee that requires a non-null argument in RCTDownloadTaskWrapper.m on line 65 which is this line:

NSURLSessionDownloadTask *task = [_URLSession downloadTaskWithURL:url completionHandler:nil];

Replacing it with an empty closure seems to fix it but wasn't sure if thats something you guys wanted to do:

NSURLSessionDownloadTask *task = [_URLSession downloadTaskWithURL:url completionHandler:^(NSURL *location, NSURLResponse *response,NSError *error){}];

**Comment by ide** [comment]
This has been fixed in master (and I think 0.9.0-rc).
