### ISSUE TITLE
toValue error dialog because of getValue() in ReadableNativeMap.java

### ISSUE THREAD

**Issue by sharwinbobde** [facebook/react-native#23268]
![screenshot_2019-02-02-14-41-00-553_com sharwinbobde musicstreaming](https://user-images.githubusercontent.com/31354242/52163167-57543680-2704-11e9-9993-f3b573bb4b3b.png)

Please ignore duplicate issue #23267
keep this as the issue

## Environment
React Native Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 16.04.5 LTS (Xenial Xerus)
      CPU: (4) x64 Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
      Memory: 125.41 MB / 7.70 GB
      Shell: 4.3.48 - /bin/bash
    Binaries:
      Node: 8.15.0 - /usr/bin/node
      npm: 6.4.1 - /usr/bin/npm
    SDKs:
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 27.0.3, 28.0.2, 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: ^0.57.8 => 0.57.8
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      react-native-rename: 2.4.0

## Description
Error dialog saying 'toValue' pops up.
I am aware about the potential Fix #19808 reported for issue #19793
Safely unwrapping ReadableMap by defaulting to 0 if key not present seems to be not working.

## Code Snippets
node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/ReadableNativeMap.java
```
@Override
  public boolean hasKey(String name) {
    if (mUseNativeAccessor) {
      mJniCallCounter++;
      return hasKeyNative(name);
    }
    return getLocalMap().containsKey(name);
  }

private Object getValue(String name) {
    if (hasKey(name) && !(isNull(name))) {
      return Assertions.assertNotNull(getLocalMap().get(name));
    }
    throw new NoSuchKeyException(name);
  }

  private <T> T getValue(String name, Class<T> type) {
    Object value = getValue(name);
    checkInstance(name, value, type);
    return (T) value;
  }
  @Override
  public double getDouble(String name) {
    if (mUseNativeAccessor) {
      mJniCallCounter++;
      return getDoubleNative(name);
    }
    return getValue(name, Double.class).doubleValue();
  }
  ```
  
node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/animated/FrameBasedAnimationDriver.java
```
  @Override
  public void resetConfig(ReadableMap config) {
    ReadableArray frames = config.getArray("frames");
    int numberOfFrames = frames.size();
    if (mFrames == null || mFrames.length != numberOfFrames) {
      mFrames = new double[numberOfFrames];
    }
    for (int i = 0; i < numberOfFrames; i++) {
      mFrames[i] = frames.getDouble(i);
    }
    mToValue = config.hasKey("toValue") ? config.getDouble("toValue") : 0; // hasKey() is returning true
    mIterations = config.hasKey("iterations") ? config.getInt("iterations") : 1;
    mCurrentLoop = 1;
    mHasFinished = mIterations == 0;
    mStartFrameTimeNanos = -1;
  }
```

## Reproducible Demo
Exception is very difficult to recreate

**Comment by sharwinbobde** [comment]
Please ignore duplicate issue #23267
keep this as the issue

**Comment by sharwinbobde** [comment]
The problem was persisted in v0.58.0 and due to some dependency issues I chose to revert to v0.57.8 

I have managed to suppress the exception

## Situation
I was using TextTicker from 'react-native-text-ticker' to create marquee text.
```
return(<TextTicker
            style={this.props.style}
            duration={4000}
            loop
            bounce
            repeatSpacer={50}
            marqueeDelay={2000}>{this.props.children}</TextTicker>)
```
As I was rendering multiple components with MarqueeText, I chose to use a FlatList.
```
this.viewabilityConfig = {
            minimumViewTime: 100,
            waitForInteraction: false,
            viewAreaCoveragePercentThreshold: 80
        }

...

<FlatList
            data={Queue.getOrderedPlaylist()}
            keyExtractor={(item, index) => index.toString()}
            renderItem={this._renderItem}
            viewabilityConfig={this.viewabilityConfig}
            />
...
```

possibly the conditional rendering of the FlatList renderItem did not mix well with the Animated component in TextTicker

I have replaced TextTicker with simple Text, thus compromising on the Marquee effect.

This has solved the recurring exception being fired and everything is working normally.

@deanhet 
For your consideration.

**Comment by jackychanfox** [comment]
I fixed this issue by adding setTimeout.

**Comment by mam17** [comment]
Same problem @0.59 -rn v
