### ISSUE TITLE
 Unknown error: not all success patterns were matched.   It means that "react-native run-android" command failed.   Please, check the View -> Toggle Output -> React Native,   View -> Toggle Output -> React Native: Run android output windows. (error code 712)

### ISSUE THREAD

**Issue by harryharihar** [facebook/react-native#23270]

**Comment by fsfhiyg** [comment]
i am new to React Native development please help me , i am facing this error from 2 hours but not found any helpful link . Its annoying now

**Comment by ithustle** [comment]
Did you read React Native doc? What's happens when you run react-native on command line?
