### ISSUE TITLE
SafeAreaView - option to choose only top or bottom spacing

### ISSUE THREAD

**Issue by vjsingh** [facebook/react-native#23279]
## Environment
Environment:
  OS: macOS 10.14.1
  Node: 10.4.0
  Yarn: 1.7.0
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: Xcode 10.1 Build version 10B61
  Android Studio: 3.2 AI-181.5540.7.32.5056338

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz => 0.55.4

## Description
Re-opening this issue: #18825
I need a view that respect top safe area (including iPhone X), but will stretch all the way down to the bottom.

Right now, SafeAreaView doesn't have any customisation options.

Is it possible to ignore bottom spacing using it?

## Reproducible Demo
No demo needed. SafeAreaView does not provide an option for only using top or bottom spacing

**Comment by hramos** [comment]
For now, I recommend you use https://github.com/react-community/react-native-safe-area-view.

**Comment by vjsingh** [comment]
Hi @hramos, thanks for the feedback. I did end up using that library and it solved my problem.

It does seem to me like this could still be a useful addition, and thus worth keeping open and track of, in order to have a native solution instead of a JS one?
