### ISSUE TITLE
Android app release fails to install on some devices

### ISSUE THREAD

**Issue by Bradzer** [facebook/react-native#23271]
## Environment
  React Native Environment Info:
    System:
      OS: Linux 4.15 Linux Mint 19.1 (Tessa)
      CPU: (4) x64 Intel(R) Core(TM) i5-3340M CPU @ 2.70GHz
      Memory: 3.39 GB / 7.66 GB
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 10.15.0 - ~/Documents/nodejs/bin/node
      npm: 6.7.0 - ~/Documents/nodejs/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28
        Build Tools: 27.0.3, 28.0.2, 28.0.3
        System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-24 | Google APIs Intel x86 Atom_64, android-25 | Google APIs Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom_64, android-27 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.58.3 => 0.58.3 
    npmGlobalPackages:
      apsl-react-native-button: 3.1.1
      react-native-button-component: 0.2.28
      react-native-cli: 2.0.1
      react-native-elements: 0.19.1
      react-native-vector-icons: 6.1.0

## Description
When I release my app and trying to install it on my Samsung Galaxy S5 active running Android Marshmallow version 6.0.1, the installation fails.
Some of my beta testers also experienced the same on Android 6 and Android 7.
However, the app installs and runs successfully on my Infinix Hot 5 running Android 7.
And it also works when I install and run it on an Android emulator running Android 6.
So I'm kind of confused.

Here's my package.json file
```

{
  "name": "iVoc",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "axios": "^0.18.0",
    "eslint-plugin-react-native": "^3.6.0",
    "native-base": "^2.10.0",
    "react": "16.6.3",
    "react-native": "0.57.8",
    "react-native-elements": "1.0.0",
    "react-native-firebase": "^5.2.0",
    "react-native-gesture-handler": "^1.0.12",
    "react-native-indicators": "^0.13.0",
    "react-native-loading-spinner-overlay": "^1.0.1",
    "react-native-paper": "^2.4.0",
    "react-native-popup-menu": "^0.14.2",
    "react-native-vector-icons": "^6.1.0",
    "react-navigation": "^3.0.9",
    "react-navigation-material-bottom-tabs": "^1.0.0",
    "react-redux": "^6.0.0",
    "realm": "^2.22.0",
    "redux": "^4.0.1"
  },
  "devDependencies": {
  },
  "jest": {
    "preset": "react-native"
  }
}
```

## Reproducible Demo
I just have to open Android Studio, generate the signed apk and install it on my phone running Android 6.0.1 for the installation to fail.

**Comment by bartolkaruza** [comment]
What is the output when you run ```adb install <your_apk>``` on that device? It sometimes contains more information.

**Comment by Bradzer** [comment]
@bartolkaruza indeed it contains more information.
So I found this `error Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES]` that is caused because I only signed my apk with version 2 signature.
All I had to do was to tick also the version 1 signature to support older devices.
Thank you @bartolkaruza ;)

**Comment by namedjmd** [comment]
you should re-sign your apk by using the keystore which with timestamp
