### ISSUE TITLE
[Packager] Require plain text/other files

### ISSUE THREAD

**Issue by mrspeaker** [facebook/react-native#2328]
Is there someone to load files from the project that are not js/json/jsx? My specific use case is to allow users to write glsl shaders and require (or some way include) them like `const shaderText = require('./myFragShader.frag');` - but it would also be good to be able to load other files, such as plain-text files, too.

I guess "require" is not the correct method for this, but it would be good to somehow load a file like this. Perhaps it could just be a browserify transform, but I'm just wondering if there any nice way to do it now?

**Comment by ide** [comment]
I don't believe the packager currently supports this but text support should be easy to add. In the interim you could define your shader in a JS file and use a template string:

```js
module.exports = `
void main(void) {
	for (int i = 0; i < gl_VerticesIn; i++) {
		gl_Position = gl_PositionIn[i];
		EmitVertex();
	}
}
`;
```

**Comment by gre** [comment]
now that we've released it, we can say this usecase is for **[gl-react-native](https://github.com/ProjectSeptemberInc/gl-react-native)**.

What I would love to see working is a tool called [glslify](https://github.com/stackgl/glslify) (that is browserify transformer, but there is also its webpack version) that brings CommonJS into GLSL (and glsl functions can be published via npm too!).

**We already have it working in one of gl-react example:**
- [Usage part](https://github.com/ProjectSeptemberInc/gl-react/blob/master/Examples/Blur/Blur1D.js#L7)
- [requiring a GLSL npm module](https://github.com/ProjectSeptemberInc/gl-react/blob/master/Examples/Blur/blur1D.frag#L11)

But at least, if we can have just `require("./foo.frag")`, this would be great. The problem of string interpolation is that the text editor thinks it's JavaScript and you lose coloration / completion.

Do you think this is easy to provide from the outside (like in how browserify/webpack have transformers) or does it have to be built-in in the RN packager to work?

**Comment by brentvatne** [comment]
cc @amasad

**Comment by mrspeaker** [comment]
(Also, if it's out of scope for what the packager should be doing then feel free to close this issue off)

**Comment by limscoder** [comment]
This functionality would also be useful for including html within a WebView.

**Comment by jaulz** [comment]
That would definitely be an interesting feature. Any chance to implement that?

**Comment by jsierles** [comment]
Hey @mrspeaker! Thanks for opening the issue. We are closing it because it's a feature request, and we want to focus Github issues on bugs. 

If this can't be implemented as a standalone [npm](https://npmjs.org) module free to send us a Pull Request or create an entry on [Product Pains](https://productpains.com/product/react-native). It has a voting system and if the feature gets upvoted enough it might get implemented.
