### ISSUE TITLE
 Problem is that when headerTransparent: true accessibleId/ TestID does not work

### ISSUE THREAD

**Issue by TesterAllmax** [facebook/react-native#23286]
## The problem

There’s a `header` in the app, that contains `button back`. Header has prop `headerTransparent: true`, which applies `position: absolute` to header. When `headerTransparent: true`, Appium Inspector can’t find `button back` inside `header`. When `headerTransparent: false`, Appium Inspector is able to find `header` and `button back` in it.

## Code To Reproduce Issue
Sample component code:

```
export const CloseButton = ({ onPress, testID }: { onPress: () => void, testID: string }) => (
  <TouchableOpacity style={styles.wrapper} onPress={onPress} testID={testID}>
    <Image source={images.closeButton} />
  </TouchableOpacity>
);
```

Sample screen code:
```
class UnconnectedLoginScreen extends PureComponent<Props, State> {
  static navigationOptions: (nav: Props) => StackNavigationOptions = ({ navigation }) => ({
    headerTransparent: true,
    headerStyle: { borderBottomWidth: 0 },
    headerRight: <CloseButton onPress={() => navigation.goBack()} testID="button Close" />,
    headerLeft: null,
  });
```

## Environment
React Native Environment Info:

| software         | version
 react-navigation: 3.0.5 
 react-native: 0.57.8  
npm
* Appium version: **1.10.0**
* Desktop OS/version: **macOS High Sierra v: 10.13.6**
* Node.js version: **10.15.0**
* Mobile platform/version: **iOS 12.1.2**
* **Real device** or emulator/simulator: **real device**

**Comment by dulmandakh** [comment]
Could you please file an issue to react-navigation. Thank you

**Comment by TesterAllmax** [comment]
@dulmandakh I sent an issue to react-navigation in February. They could not help
