### ISSUE TITLE
Android bundle: java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by LucasBrazi06** [facebook/react-native#23299]
## Environment
```
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
      Memory: 15.32 GB / 31.86 GB
    Binaries:
      Yarn: 1.9.4 - C:\Users\i030367\AppData\Roaming\npm\yarn.CMD
      npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD
```

## Description
I built my react-native project and build a release Android Bundle (.aab file) and got this error when starting the application:
```
java.lang.UnsatisfiedLinkError: 
  at com.facebook.soloader.SoLoader.doLoadLibraryBySoName (SoLoader.java:703)
  at com.facebook.soloader.SoLoader.loadLibraryBySoName (SoLoader.java:564)
  at com.facebook.soloader.SoLoader.loadLibrary (SoLoader.java:500)
  at com.facebook.soloader.SoLoader.loadLibrary (SoLoader.java:455)
  at com.facebook.react.bridge.ReactBridge.staticInit (ReactBridge.java:18)
  at com.facebook.react.bridge.NativeMap.<clinit> (NativeMap.java:19)
  at com.facebook.react.bridge.JSCJavaScriptExecutorFactory.create (JSCJavaScriptExecutorFactory.java:21)
  at com.facebook.react.ReactInstanceManager$5.run (ReactInstanceManager.java:917)
  at java.lang.Thread.run (Thread.java:764)
```  

It doesn't even provide the lib name!

It crashes on:
  - Samsung Galaxy S8 (dreamlte), Android 8.0
  - Huawei P20 Pro (HWCLT), Android 9

And on other devices like Galaxy S4 it works!

But when I build an apk, it works perfectly on all devices.

## Reproducible Demo

Generate a react-native empty project and build a bundle with Android studio and deploy a release version of it.
When you start the app, it immediately crashes.
I hope this will be enough for you.

**Comment by kelset** [comment]
It looks like it's related to SoLoader - there is a new version, 0.58.4, on its way which should contain the fix for this -> https://github.com/facebook/react-native/commit/e1694ee0410868603257e5bbce134d374e51c7b1

Let me know if with 0.58.4 the issue disappears, if not try to apply manually the changes from that commit on your project 💪

**Comment by vanydeasy** [comment]
@kelset I still have the same issue on RN `0.58.4`. But now it has a different error log on each android version. I do not know if it comes from the same bug or not.

On Android 8.1.0
```
Fatal Exception: java.lang.UnsatisfiedLinkError
couldn't find DSO to load: libreactnativejni.so caused by: couldn't find DSO to load: libfb.so caused by: couldn't find DSO to load: libgnustl_shared.so caused by: dlopen failed: "/data/data/com.traveloka.android/lib-0/libgnustl_shared.so" is 64-bit instead of 32-bit
```

On Android 7.0
```
Fatal Exception: java.lang.UnsatisfiedLinkError
couldn't find DSO to load: libreactnativejni.so caused by: couldn't find DSO to load: libfb.so caused by: Dynamic section string-table not found
```

On Android 5.1.1 and Android 7.1.2
```
Fatal Exception: java.lang.UnsatisfiedLinkError
couldn't find DSO to load: libreactnativejni.so
```

We use Android App Bundle for our release with `build.gradle`:
```
ndk {	
    abiFilters "armeabi-v7a", "x86", "arm64-v8a"
}
```

**Comment by kelset** [comment]
@vanydeasy by looking at those logs, it seems that your issue is related to `libreactnativejni.so` so I believe you may have missed some steps during the upgrade process.

Please open a dedicated issue with a repro.

Given that @LucasBrazi06 hasn't replied I'll close this.
