### ISSUE TITLE
[CI] Run clang-format as part of the analyze workflow

### ISSUE THREAD

**Issue by hramos** [facebook/react-native#23298]
We use Prettier to automatically format our JavaScript code. When a PR is opened, we run Prettier as part of our CI workflow. A bot, @pull-bot, will leave a comment whenever Prettier identifies an issue with the code.

This issue is a request for help to do the same with C++ code using clang-format. You'll find a .clangformat file in both React/ and ReactCommon/. To implement this change, you will need to update `.circleci/config.yml` and/or `scripts/circleci/analyze_code.sh` and make sure Circle CI can run clang-format.

**Comment by gengjiawen** [comment]
How about introduce `clang-tidy` too ?
cc @dulmandakh @empyrical @matthargett @shergin

**Comment by gengjiawen** [comment]
About the implementation, not necessarily use bash, a nodejs script might do.
We can refer to electron https://github.com/electron/electron/blob/b7afec07433b79eb942ae8d6ded10c61dcdd21bb/package.json#L47.

Also, why not just use one `.clang-format` in project root ?

**Comment by cpojer** [comment]
@gengjiawen made this happen, yay!
