### ISSUE TITLE
onBlur , back button

### ISSUE THREAD

**Issue by sm2017** [facebook/react-native#23308]
## Environment

```
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i7-3632QM CPU @ 2.20GHz
      Memory: 915.60 MB / 5.58 GB
    Binaries:
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5199772

```

## Description

When text input is focused and you press  back button in android , onBlur is not triggered 

## Reproducible Demo

https://snack.expo.io/rJnc3BuV4

Run snack and focus input , then press back button , the alert must shown

**Comment by kelset** [comment]
Which version of react native has this issue?

There was an issue in a patch version of 0.57.x, that we then rolled back. Please check the changelogs too.

**Comment by sm2017** [comment]
react-native@0.58.3

**Comment by JKCooper2** [comment]
I think given the nature of the BackAndroid button it is better for devs to choose to override/add to the the default behaviour, e.g. https://snack.expo.io/@jkcooper/rn23308-textinput-onblur-backandroid. I would expect the current behaviour is similar to pressing back in a browser.
