### ISSUE TITLE
[IOS] Error running with release scheme using pods

### ISSUE THREAD

**Issue by githubdoramon** [facebook/react-native#23300]
## Environment
 React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
      Memory: 215.41 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.15.0 - ~/.nvm/versions/node/v8.15.0/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.15.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 19, 24, 27, 28
        Build Tools: 19.1.0, 27.0.3, 28.0.1, 28.0.2, 28.0.3
        System Images: android-19 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: ^0.58.3 => 0.58.3

## Description
When using release scheme app crashes when opening a view containing React native and a native module as well. Issue is the same as https://github.com/facebook/react-native/issues/19544 - But no proper solution was provided on other ticket.

I can't remove use_frameworks as other pods needs it. What can be done to solve this?

App works normally when I run in debug mode (even with offline bundle)

## Reproducible Demo
Can't provide a reproducible demo since it is my full project and is not open source.

**Comment by githubdoramon** [comment]
@vovkasm apparently you have dealt with this before right?
@generalpiston Have you solved your similar problem?

**Comment by vovkasm** [comment]
These symptoms as always can have many causes. Most probably is that one of you frameworks and application contains duplicated symbols. Previously I seen this when people try to link React many times. For example main xcode project has React as subproject (what RN provides in default template) and also React linked with pods. Again, it is only one of many possible potential problems.

**Comment by kelset** [comment]
> Can't provide a reproducible demo since it is my full project and is not open source.

As I said times and times again, this is not an excuse. You should create a minimal repro using a fresh project via `react-native init`.

**Comment by githubdoramon** [comment]
@kelset You are right... But @vovkasm indeed solved my problem... I was adding React both on pods as well as static *.a files... removing them did the trick. Thanks a lot for helping out.
