### ISSUE TITLE
Switching to andoid P  react native app not working

### ISSUE THREAD

**Issue by uendar** [facebook/react-native#23307]
I used to develop a react native app using android 8.0 and below. Everything worked perfect till i decidet to switch to android 9.0 (Android P). I cant continue to develop  the app because when i try to reload or login in my app i get this screen. Any idea what can cause this ? 
![screenshot_1549453448](https://user-images.githubusercontent.com/13899301/52339825-71488e80-2a0e-11e9-881d-94c44a2b9a80.png)

**Comment by kelset** [comment]
👋
This issue has been reported before, here's the solution you can apply to your project -> https://github.com/facebook/react-native/issues/15388#issuecomment-437839788

A commit with a proper fix (https://github.com/facebook/react-native/pull/23105) is also already on master so newer version of RN won't have this issue.
