### ISSUE TITLE
null is not an object (evaluating 'RNGestureHandlerModule.State')

### ISSUE THREAD

**Issue by 29parthi** [facebook/react-native#23315]
i am getting the above error after installing react-navigation

below is my package.json

{
  "name": "CricWallet",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.6.3",
    "react-native": "0.58.3",
    "react-navigation": "^3.1.4",
    "react-redux": "^6.0.0",
    "redux": "^4.0.1",
    "redux-saga": "^1.0.1"
  },
  "devDependencies": {
    "babel-core": "^7.0.0-bridge.0",
    "babel-jest": "24.0.0",
    "jest": "24.0.0",
    "metro-react-native-babel-preset": "0.51.1",
    "react-test-renderer": "16.6.3"
  },
  "jest": {
    "preset": "react-native"
  }
}

Below is the full error stack trace

null is not an object (evaluating 'RNGestureHandlerModule.State')

<unknown>
    GestureHandler.js:55:37
loadModuleImplementation
    require.js:321:6
<unknown>
    Swipeable.js:11
loadModuleImplementation
    require.js:321:6
<unknown>
    index.js:1
loadModuleImplementation
    require.js:321:6
<unknown>
    StackViewLayout.js:19
loadModuleImplementation
    require.js:321:6
<unknown>
    StackView.js:4
loadModuleImplementation
    require.js:321:6
<unknown>
    createStackNavigator.js:3
loadModuleImplementation
    require.js:321:6
createStackNavigator
    index.js:9:18
createStackNavigator
    react-navigation.js:107:45
<unknown>
    AppNavigator.js:4:21
loadModuleImplementation
    require.js:321:6
<unknown>
    App.js:15
loadModuleImplementation
    require.js:321:6
<unknown>
    index.js:7
loadModuleImplementation
    require.js:321:6
guardedLoadModule
    require.js:199:45
global code
    <unknown file>:0

**Comment by kelset** [comment]
This is not the right repository to post this issue. Please refer to the official react-navigation repository.

That said, it's probably because you forgot to install RN-Gesture-Handler, which is requested, check the react-navigation installation guide
