### ISSUE TITLE
DatePickerAndroid opens both "spinner" and "calendar" on Tablet

### ISSUE THREAD

**Issue by DmytroSkrypnyk** [facebook/react-native#23325]
## 🐛 Bug Report
When I open DatePickerAndroid with mode "spinner" in API 28 phone (Android 8.0) it opens correctly.
But if I change to a tablet (Nexus 10 API 27 2560x1600 xhdpi), then both spinner and calendar open as you can see in the screenshot: https://monosnap.com/file/q94zFk9cjywdNFZ5fXX16eRHfhz4iO
I'm using react-native: 0.58.3
There was the same issue: "https://github.com/facebook/react-native/issues/21313"

## To Reproduce
  Try to run example code in any component on the tablet.

## Expected Behavior
  I would like to see only spinner component

## Code Example
```javascript
componentDidMount() {
  try {
      const {action, year, month, day} = await DatePickerAndroid.open({
        date: new Date(2020, 4, 25),
        mode: 'spinner'
      });
  }
}
```

## Environment
  React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
      Memory: 40.26 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.9.4 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.1.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 24.0.2, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.3
        System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom_64, android-26 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: 3.1 AI-173.4670197
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728 
      react-native: 0.58.3 => 0.58.3 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1

**Comment by Titozzz** [comment]
Hello, since this is not very active, I think you should try to fix it using these kinds of thing: https://stackoverflow.com/questions/28740657/datepicker-dialog-without-calendar-visualization-in-lollipop-spinner-mode and submit a pull request.

**Comment by DmytroSkrypnyk** [comment]
Thanks for your solution but nowadays I work on another project and this problem I have solved by using another library (react-native-wheel-datepicker https://www.npmjs.com/package/react-native-wheel-datepicker)
