### ISSUE TITLE
Introduce code quality tools for android. 

### ISSUE THREAD

**Issue by gengjiawen** [facebook/react-native#23332]
With the help of findbugs, PMD, we may find some problem early.

Maybe we can refer to: https://github.com/vanniktech/gradle-code-quality-tools-plugin.

cc @dulmandakh @hramos

**Comment by dulmandakh** [comment]
currently, I'm using https://developer.android.com/studio/write/lint and recent PRs to reduce errors/warnings detected by using lint.

it would be nice to start with very basic setup, and like commit must not increase error/warning count, otherwise CI fails.

**Comment by dulmandakh** [comment]
I found that there are many places where code just don't work due to use of newer APIs than 16 and crashes. I replaced some code from support library, but still having errors.

**Comment by dulmandakh** [comment]
another PR with lint error/warning fixes https://github.com/facebook/react-native/pull/23333. it's WIP.

**Comment by dulmandakh** [comment]
Note: ./gradlew :ReactAndroid:lint generates very useful report

**Comment by cpojer** [comment]
This issue was a discussion and we agreed that a PR should be sent. @gengjiawen please consider sending a PR with the fix but I'm gonna close the issue because on its own it isn't actionable.
