### ISSUE TITLE
Unsupported interpolation type: keyboard [Android]

### ISSUE THREAD

**Issue by thinklinux** [facebook/react-native#23343]
## 🐛 Bug Report
Trying to use LayoutAnimation on Android with `type: LayoutAnimation.Types['keyboard']`. On iOS everything is working fine.

## To Reproduce
```js
import {
  UIManager,
} from 'react-native';

// Run just for Android
  UIManager.setLayoutAnimationEnabledExperimental &&
    UIManager.setLayoutAnimationEnabledExperimental(true);

   LayoutAnimation.configureNext({
     duration: this.layoutAnimationKeyboardDuration,
     update: {
       type: LayoutAnimation.Types['keyboard'],
     },
   });
```

`console.log(LayoutAnimation.Types)` gives me this:

![screenshot 2019-02-08 at 12 30 10](https://user-images.githubusercontent.com/326949/52472943-480a3880-2b9d-11e9-99d2-d337c602f0aa.png)

The keyboard type is there but it is not supported for Android?

## Environment
  React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
      Memory: 46.61 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.13.0 - /usr/local/bin/node
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 26, 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.0 => 16.6.0 
      react-native: 0.57.5 => 0.57.5 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

**Comment by dulmandakh** [comment]
what is your Android version?
