### ISSUE TITLE
React switch component not working on Android

### ISSUE THREAD

**Issue by ameenmattar** [facebook/react-native#23348]
## 🐛 Bug Report
 **(Bug on Android Only)** 
Using Switch component is making this bug appear suddenly when i launch the page that contains the switch, while removing or commenting the component-

```
    // return (
    //   <Switch
    //     onTintColor={"#CE2A53"}
    //     onValueChange={this._onSwitchChange.bind(this)}
    //     tintColor={"#cccccc"}
    //     value={switchVal}
    //   />
    // );

```
  the page opens and everything is good.

The given error from the switch is : 

![screenshot_20190208-170519_blediclub](https://user-images.githubusercontent.com/32841332/52486499-f88b3300-2bc3-11e9-86e4-c764bc311400.jpg)

## Expected Behavior
**The page should  launch.** 

## Code Example
```
    return (
      <Switch
        onTintColor={"#CE2A53"}
        onValueChange={this._onSwitchChange.bind(this)}
        tintColor={"#cccccc"}
        value={switchVal}
      />
    );
```

## Environment

React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-5575R CPU @ 2.80GHz
      Memory: 45.98 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.10.0 - /usr/local/bin/node
      Yarn: 1.5.1 - /usr/local/bin/yarn
      npm: 6.6.0-next.0 - /usr/local/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Android Studio: 3.1 AI-173.4697961
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

**Comment by dulmandakh** [comment]
what is your Android version?

**Comment by ameenmattar** [comment]
Android 8.0 (Samasung S8)

**Comment by kelset** [comment]
> 0.56.0 => 0.56.0

You should upgrade to either 0.57.x or 0.58.x - we are not planning on doing patch releases for 0.56.

Please let me know if you have this same issue on 0.58, if that's the case I'll reopen this.
