### ISSUE TITLE
React.framework symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by JMozumacs** [facebook/react-native#23347]
My native iOS project has React dependency. After updating project to swift 4 and dropping support for iOS 9 and iOS 10, I have the following problem with React.framework.

After installing node_modules and installing pods with pod install, I can not build the project.
See the picture below.

![xcode error](https://i.imgur.com/v6KnQOG.png)

I have the following in pod file

![xcode error](https://i.imgur.com/L9NHMAf.png)

Package.json:

        "@expo/vector-icons": "6.2.2",
        "expo": "25.0.0",
        "native-base": "^2.10.0",
        "react": "16.3.1",
        "react-native": "^0.57.8",
        "react-native-fs": "1.5.1",
        "react-native-mall-frame-client": "^2.2.43",
        "react-native-prompt": "^1.0.0",
        "react-native-prompt-android": "^0.3.3",
        "react-native-select-input-ios": "^1.2.0",
        "react-native-vector-icons": "^5.0.0",
        "react-navigation": "1.0.0-beta.27"

**Comment by JMozumacs** [comment]
![](https://i.imgur.com/hXaQXa6.png)

**Comment by andresmtz98** [comment]
Same problem

**Comment by JMozumacs** [comment]
@andresmtz98 it turned out I had to use earlier version of cocoapods
