### ISSUE TITLE
[borderStyle='dotted'] React-Native 0.8, View's borderStyle='dotted' could not be effected.

### ISSUE THREAD

**Issue by hufeng** [facebook/react-native#2335]
Dear all,

React-Native 0.8, View's borderStyle='dotted' could not be effected. 

how to fix it?

**Comment by chirag04** [comment]
refer: github.com/chirag04/react-native-dashed-border and https://github.com/facebook/react-native/issues/840

Now that borderStyle is support for android, I would want to deprecate my module and have first class support for borderStyle in RN itself. BorderStyle in core would help coz then custom modules won't have to worry/reimplement supporting other view-border related properties.

It would make sense to add it for ios also ;)

cc @vjeux, @nicklockwood

**Comment by nicklockwood** [comment]
Absolutely. Is it something you could implement as a pull request?

**Comment by chirag04** [comment]
I just ran over the border codebase. Seem little complex for me. I'm absolute newbie to objective-c.

I just hacked my dashed-border module from stackoverflow examples. :(

**Comment by nicklockwood** [comment]
Fair enough. I'll have a go at implementing it when I get a chance, but as you say, it's quite complex, so it may take a while before we can support it.

**Comment by chirag04** [comment]
sure. Thanks. I will deprecate my module after your implementation is up.

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/borderstyledotted-react-native-08-views-borderstyledotted-could-not-be-effected

**Comment by nicklockwood** [comment]
This has actually been implemented on iOS already - we just forgot to close the issue.

**Comment by brentvatne** [comment]
Great :) I must have missed that. Marked as fixed on ProductPains!
