### ISSUE TITLE
Error · Not Supported

### ISSUE THREAD

**Issue by john1jan** [facebook/react-native#23368]
I am getting this crash report in android 4.4 devices.

Error Not Supported 
    node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:116:79 c
    node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:77:28 
    node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:398:16 value
    node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:140:16 
    node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:318:11 value
    node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:140:16 value

When occurs in this function

```
function createErrorFromErrorData(errorData: {message: string}): ExtendedError {
```

**Comment by CarterBland** [comment]
@john1jan I'm experiencing this as-well, have you found a solution?
