### ISSUE TITLE
Add Documentation Link to Current Version (Separate from development)

### ISSUE THREAD

**Issue by yemarnevets** [facebook/react-native#23363]
Coming from Django land, it would be great if this URL worked: 

https://facebook.github.io/react-native/docs/0.58/getting-started.html

Unfortunately it throws a 404 error. 

My user story: 
As someone writing a blog post I'd really like to be able to link to the version of ReactNative that I am currently working with. When I am working on the most recent version, there is no direct link to the documentation. In Django land (https://docs.djangoproject.com/en/2.2/), they take great care to clearly distinguish between "current stable version" (now 2.2) and development. When linking on StackOverflow or something, development might make sense to ensure the link ages well. However, there are times when it makes sense to link directly to 2.2, knowing that the version will change in the future to 2.3, 2.4, etc. **As it stands I am unable to link to ReactNative docs on 0.58 and I don't think that should be the case.**

**Comment by hramos** [comment]
I think that's fair. Do you mind opening your issue in https://github.com/facebook/react-native-website?
