### ISSUE TITLE
Webview not passing header with Android 9

### ISSUE THREAD

**Issue by Akanksha-Thakur** [facebook/react-native#23377]
## 🐛 Bug Report

Webview not passing header with Android 9. it is working with lower android versions.

When I run, webview's header passes to webpage. It would everything working fine with android verison < 9. but not in android version 9 (Pie).

 I wanna pass headers from android version 9 to webpage also. 

<WebView
            ref={REF => (this.WebViewRef = REF)}
            bounces
            source={{ uri: `${baseUrl.domain}${url}`, headers: { 'is_app': 'true' }}}
            onLoadStart={navState => this.onLoadStart(navState)}
            onLoadEnd={navState => this.onLoadEnd(navState)}
            onError={this.onLoadEnd}
            key={this.state.key}
            renderLoading={() => (
              <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center'}}>
                <ActivityIndicator size="large" color={colors.black} />
              </View>
            )}
            startInLoadingState
            mixedContentMode="always"
            thirdPartyCookiesEnabled
          />

Environment:
  OS: Linux 4.15
  Node: 8.11.4
  Yarn: 1.12.3
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: 3.3 AI-182.5107.16.33.5199772

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

**Comment by Akanksha-Thakur** [comment]
Ohh! yaa I updated my bug.

**Comment by hramos** [comment]
Do you mind opening the issue over at https://github.com/react-native-community/react-native-webview? The WebView component was forked to that repository, and has been deprecated in the core RN repository.

**Comment by Akanksha-Thakur** [comment]
Now I update my react-native version but still having the same issue.

Environment:
  OS: Linux 4.15
  Node: 8.11.4
  Yarn: 1.12.3
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: 3.3 AI-182.5107.16.33.5199772

Packages: (wanted => installed)
  react: 16.8 => 16.3.1
  react-native: ^0.58.4 => 0.55.4

**Comment by Akanksha-Thakur** [comment]
@hramos Actually I used https://github.com/react-native-community/react-native-webview but getting the same issue with it.

**Comment by hramos** [comment]
That's quite likely. You can report the issue over there. We'll remove WebView from the facebook/react-native repository soon.

**Comment by vijaychouhan-rails** [comment]
@hramos Actually I want a solution regarding this bug does not want to remove Webview from facebook/react-native repository otherwise it would be more problematic.

**Comment by hramos** [comment]
See the Lean Core issue pinned to the top of the issues page. WebView was the first component to be forked and transferred to the RN community. All you need to do is import the new package and you will get access to the very same component that is available in core. 

You may choose to continue using the component from core, but it’s not getting any new updates and will be removed in the next release or two. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Akanksha-Thakur** [comment]
@hramos  Thanks for answer! Actually I have solved my issue with another way now I am using query parameter except of header in Webview.
