### ISSUE TITLE
RNHTMLtoPDF is undefined

### ISSUE THREAD

**Issue by AxelPariss** [facebook/react-native#23375]
## 🐛 Bug Report
RNHTMLtoPDF is undefined when I want to use it.
[Repo 'react-native-html-to-pdf' link](https://github.com/christopherdro/react-native-html-to-pdf)

I followed the installation process, I tried `react-native link` and manual installation (through Xcode)
(see image)
[my xcode](https://i.imgur.com/444eaQQ.jpg)

```
import RNHTMLtoPDF from 'react-native-html-to-pdf'

export default class MyCompo extends Component {
  render() {
    console.log('lib pdf', RNHTMLtoPDF)
   }
}
```
and the result is `undefined`

## Environment
```
React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
      Memory: 285.63 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.2 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.1 => 16.8.1 
      react-native: 0.57.0 => 0.57.0 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

**Comment by AxelPariss** [comment]
> It looks like you are using an older version of React Native. Please update to the [latest release, v0.58](https://github.com/facebook/react-native/releases/tag/v0.58.0) and verify if the issue still exists.

If I update to 0.58.0 I have this error :/
![error](https://i.imgur.com/FrKfsPa.jpg)

**Comment by hramos** [comment]
That upgrade error appears unrelated to the issue being reported. Can you try importing the RNHTMLtoPDF module in a brand new project that uses RN 0.58?
