### ISSUE TITLE
Why can't I break Packager?

### ISSUE THREAD

**Issue by sghiassy** [facebook/react-native#2338]
When reading new code, I like to test my assumptions by trying to break it in certain ways. This process confirms my analysis, but in reading React Native's Packager code I've been thrown for a loop.

Per my understanding, Packager creates an HTTP Server using Connect. As part of the server's middleware, it creates a new `JSTransformer` object that takes in a `transformModulePath` as a parameter (which at runtime is a path that references `transformer.js`). `JSTransformer` then creates a worked farm (or 4 nodes?) and transforms the code during the `loadFileAndTransform` method.

If that's true (which I'm guessing its not??) then commenting out `transformer.js` should cause React Native to not transform the code.... but it does! I can literally comment out the entire file of `transform.js` and everything works just fine.

I can even go into `JSTransformer/index.js` and pass in `undefined` to all the method parameters 

``` javascript
return transform({
  sourceCode: undefined,
  filename: undefined,
}).then(
  function(res) {

    return new ModuleTransport({
      code: undefined,
      map: undefined,
      sourcePath: undefined,
      sourceCode: undefined,
    });
  }
);
```
and yet it still works!! ahhh!!!

Am I missing a key part of the asset pipeline? Or making a junior mistake somewhere? Any help would be appreciated.

Thx

**Comment by sghiassy** [comment]
... and just to be clear, I'm not trying to really break anything... this is just an educational excersice

**Comment by brentvatne** [comment]
@sghiassy - interesting question :) Maybe if you ping @amasad on Twitter you will have more luck getting a response: https://twitter.com/amasad - I'm cleaning out issues right now and this doesn't seem to be a bug so I'll close it, love your approach to learning new code though!
