### ISSUE TITLE
RCTSlider produces a line no matter even when all colors values match background color

### ISSUE THREAD

**Issue by bobber205** [facebook/react-native#23388]
## 🐛 Bug Report
The view that contains my Slider component is `rgb(236,245,255)`
I've set both `minimumTrackTintColor` and `maximumTrackTintColor` to `rgb(236,245,255)`  as well.

As you can see in the attached screenshot there is always a slight grey shadow or gradient or something that is visible. My intention with setting the colors this way is to make a slider that is just under or above an image that gives the user more info on the value they are selecting.

## Code Example
https://snack.expo.io/ry6ciFkS4

## Environment
 

>  React Native Environment Info:
>     System:
>       OS: macOS High Sierra 10.13.6
>       CPU: (4) x64 Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
>       Memory: 58.29 MB / 8.00 GB
>       Shell: 3.2.57 - /bin/bash
>     Binaries:
>       Node: 11.6.0 - /usr/local/bin/node
>       Yarn: 1.13.0 - /usr/local/bin/yarn
>       npm: 6.5.0 - /usr/local/bin/npm
>       Watchman: 4.9.0 - /usr/local/bin/watchman
>     SDKs:
>       iOS SDK:
>         Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
>       Android SDK:
>         API Levels: 26, 27, 28
>         Build Tools: 26.0.2, 27.0.3, 28.0.3
>         System Images: android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
>     IDEs:
>       Android Studio: 3.2 AI-181.5540.7.32.5056338
>       Xcode: 10.1/10B61 - /usr/bin/xcodebuild
>     npmPackages:
>       react: 16.6.3 => 16.6.3
>       react-native: 0.57.8 => 0.57.8

Is there anyway to prevent that VERY slight grey line?

![react native slider issue zoomed in](https://user-images.githubusercontent.com/5841107/52602128-49926580-2e16-11e9-849a-046e3fc0b72b.png)

**Comment by bobber205** [comment]
Is it possible to have that labeled removed? I don't have the time to spend a day or more upgrading and figuring out why it won't build on 58 just for this bug report. :\

I gave it a couple hours yesterday and didn't make any progress. It reproduced on the snack.expo link. Can that be enough?

**Comment by cpojer** [comment]
This issue has been moved to react-native-community/react-native-slider#10.
