### ISSUE TITLE
App name in  `react-native init app_name` can only contain valid characters for js variables 

### ISSUE THREAD

**Issue by adri** [facebook/react-native#234]
When initialising a new app using `react-native init some-folder`, the app name may not contain a `-` because the example template uses the app name as javascript variable which causes the script not to interpret.

```
var some-folder = React.createClass({
```

**Comment by amasad** [comment]
this been fixed via 5ce9ab143ae0e76a59d3f12b4419c0d5a18f7d85 but we still need to publish a new version to npm
