### ISSUE TITLE
[iOS] Vibration.vibrate not working at all

### ISSUE THREAD

**Issue by Miyaguisan** [facebook/react-native#23404]
## 🐛 Bug Report
Using Vibration.vibrate produces the following results:

`TypeError: undefined is not an object (evaluating 'RCTVibration.vibrate')`
`  in MyComponent (at ComponentWrapper.js:27)`
`  in WrappedComponent (at renderApplication.js:32)`
`  in RCTView (at View.js: 43)`
`  in RCTView (at VIew.js: 43)`
`  in AppContainer (at renderApplication.js: 31)`

[Screenshot](https://user-cdn.buckets.co/attachments/IMG_0328.PNG)

## To Reproduce
Simply add Vibration.vibrate() at convenient location then test on iOS on RN 0.56.0

## Expected Behavior
The device should vibrate

## Code Example
[Snack](https://snack.expo.io/B1ww2DgrE)

## Environment
React Native Environment Info:
    
- System:
  - OS: macOS 10.14.3
  - CPU: x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
  - Memory: 11.24 GB / 24.00 GB
  - Shell: 5.3 - /bin/zsh
- Binaries:
  - Node: 10.14.1 - ~/.nvm/versions/node/v10.14.1/bin/node
  - Yarn: 1.12.3 - /usr/local/bin/yarn
  - npm: 6.4.1 - ~/.nvm/versions/node/v10.14.1/bin/npm
  - Watchman: 4.9.0 - /usr/local/bin/watchman
- SDKs:
  - iOS SDK:
    - Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
  - Android SDK:
    - Build Tools: 27.0.3, 28.0.3
    - API Levels: 27, 28
- IDEs:
  - Android Studio: 3.3 AI-182.5107.16.33.5264788
  - Xcode: 10.1/10B61 - /usr/bin/xcodebuild
- npmPackages:
  - react: 16.6.3 => 16.6.3
  - react-native: 0.56.0 => 0.56.0
- npmGlobalPackages:
  - react-native-create-library: 3.1.2

**Comment by hramos** [comment]
You're missing a required parameter, the vibration pattern. See http://facebook.github.io/react-native/docs/vibration#vibrate

```
Vibration.vibrate(pattern: number, Array<number>, repeat: boolean)
```

**Comment by Miyaguisan** [comment]
> You're missing a required parameter, the vibration pattern. See http://facebook.github.io/react-native/docs/vibration#vibrate
> 
> ```
> Vibration.vibrate(pattern: number, Array<number>, repeat: boolean)
> ```

Using
`const DURATION = 1000`
`Vibration.vibrate(DURATION)`

or
`const PATTERN = [1000,2000,3000]`
`Vibration.vibrate(PATTERN)`

Produces the same result, I believe this is just an old version problem, since `Vibration.vibrate()` works without any parameter just fine on RN 0.58 on both iOS and Android. Just reporting the issue for documentation purposes.

**Comment by hramos** [comment]
According to https://github.com/facebook/react-native/blob/master/Libraries/Vibration/Vibration.js#L72, vibrate() should throw an error. It doesn't look like the code has changed recently.

If it works fine in 0.58 and it's only an issue in 0.56, then that's alright as we're only tracking issues that affect the latest release. 

If it's more of a docs concern, and something needs to be documented differently for 0.56, you can open an issue in the docs repo at https://github.com/facebook/react-native-website

**Comment by andres-torres-marroquin** [comment]
@hramos the code has a 400 duration by default, which is mentioned on the docs, but also is mentioned as a required parameter (which it really doesn't)
`Vibration.vibrate(400)` and `Vibration.vibrate()` have the same result on the device.

**Comment by thetwosents** [comment]
Can confirm, doesn't work on most recent react-native also. Same error.

**Comment by Jujenji** [comment]
using RN 0.60 I do not get an error thrown but the Vibration does not occur at all on IOS. Android works fine.

**Comment by baughmann** [comment]
This is still not working on iOS, though no exception is thrown for me. `Vibration.vibrate()` yields no feedback whatsoever.

**Comment by hramos** [comment]
Interesting. Reopening as I just sent a PR to update the docs to match the implementation on iOS.

**Comment by hramos** [comment]
I just tested this on RNTester, by navigating to the Vibration example. It works just fine on iOS. In fact, all variants of `Vibration.vibrate()`, including those with patterns and repetition, result in a single vibration as expected. I don't see any errors on Metro or on the Xcode console.

These are the steps I followed, in a fresh checkout of the RN repo:

```
npm install
npm start
```

```
cd RNTester
pod install
open RNTesterPods.xcworkspace
```

Then I selected RNTester as the target, and my own iOS *physical* device, an iPhone 11 Pro Max. Build and Run, then type "Vibration" into the search field in RNTester. Then tap each of the `vibrate()` examples. Each time, the device vibrated once.

I'll leave this open for a bit in case someone can provide a repro. But for now, I consider this to not be an issue on master.

**Comment by zabojad** [comment]
I'm having the same issue. It seems vibrations are broken on iOS 14...

**Comment by matias3981** [comment]
Yep, tried it on an iphone 11 pro max iOS 14.3. It's kind of weird. I try it on expo snack and it works, but in my proyect it does not. 

`<Button onPress={() => Vibration.vibrate([1000)} title="Press me" />`
It does not vibrate. My phone is with sound, maybe it's an project config?

**Comment by hb-webdev** [comment]
Whatever **BUG** this is, it seems to be affecting the `react-native-haptic-feedback` library as well. No matter what configurations I use, `onPress={() => Vibration.vibrate()}` and `onPress={() => ReactNativeHapticFeedback.trigger("selection")}` do absolutely nothing.

The funny thing is, they _both_ work just fine if placed _outside_ of an `onPress` event, like this:

```javascript
import { Vibration } from 'react-native';

const MyScreen = () => {
Vibration.vibrate();
}
```

The phone will vibrate as soon as I switch to the `.js` screen with this code. However, the `onPress` events on that exact same screen will _not_ activate the vibration/haptic feedback...even though the app just demonstrated that it is fully capable of vibrating the phone.

It is very strange...I don't know what libraries, if any, are affecting `onPress`' ability to vibrate/give haptic feedback but it sure is a thorn in the side

**Comment by hb-webdev** [comment]
Ok well I just made a brand new React Native project. It incorrectly vibrates when the page loads (odd...since I didn't even put `Vibration.vibrate` outside of all my functions like I did in my previous example), but it still _doesn't_ vibrate when I press the button; no reaction at all.

```
import React from 'react';
import {
  View,
  Button,
  Vibration
} from 'react-native';

const App = () => {

  return (
    <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}} >
    <Button
    title="Buzz!"
    onPress={Vibration.vibrate()} />
    </View>
  );
};

export default App;

```
