### ISSUE TITLE
[Android] [DialogModule] IllegalStateException on 0.56 version

### ISSUE THREAD

**Issue by jackyshek** [facebook/react-native#23417]
Base on the crashlytics, we saw that it crash on "onSaveInstanceState" after calling showAlerts. Before calling showAlerts we have fire a request to server-side to get request how ever it return 404. That's why we need show a alert to user that contact us.

## Error Log

> OS Version: 7.1.1
>  Device: TA-1003
>  RAM Free: 14.9%
>  Disk Free: 55%
> 
> 0. Crashed: main
>        at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1434)
>        at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1452)
>        at android.app.BackStackRecord.commitInternal(BackStackRecord.java:708)
>        at android.app.BackStackRecord.commit(BackStackRecord.java:672)
>        at android.app.DialogFragment.dismissInternal(DialogFragment.java:301)
>        at android.app.DialogFragment.dismiss(DialogFragment.java:267)
>        at com.facebook.react.modules.dialog.DialogModule$b.c(Unknown Source)
>        at com.facebook.react.modules.dialog.DialogModule$b.a(Unknown Source)
>        at com.facebook.react.modules.dialog.DialogModule$1.run(Unknown Source)
>        at android.os.Handler.handleCallback(Handler.java:751)
>        at android.os.Handler.dispatchMessage(Handler.java:95)
>        at android.os.Looper.loop(Looper.java:154)
>        at android.app.ActivityThread.main(ActivityThread.java:6119)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
> 
> --
> 
> Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
>        at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1434)
>        at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1452)
>        at android.app.BackStackRecord.commitInternal(BackStackRecord.java:708)
>        at android.app.BackStackRecord.commit(BackStackRecord.java:672)
>        at android.app.DialogFragment.dismissInternal(DialogFragment.java:301)
>        at android.app.DialogFragment.dismiss(DialogFragment.java:267)
>        at com.facebook.react.modules.dialog.DialogModule$b.c(Unknown Source)
>        at com.facebook.react.modules.dialog.DialogModule$b.a(Unknown Source)
>        at com.facebook.react.modules.dialog.DialogModule$1.run(Unknown Source)
>        at android.os.Handler.handleCallback(Handler.java:751)
>        at android.os.Handler.dispatchMessage(Handler.java:95)
>        at android.os.Looper.loop(Looper.java:154)
>        at android.app.ActivityThread.main(ActivityThread.java:6119)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
> 
> 0. Crashed: main
>        at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1434)
>        at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1452)
>        at android.app.BackStackRecord.commitInternal(BackStackRecord.java:708)
>        at android.app.BackStackRecord.commit(BackStackRecord.java:672)
>        at android.app.DialogFragment.dismissInternal(DialogFragment.java:301)
>        at android.app.DialogFragment.dismiss(DialogFragment.java:267)
>        at com.facebook.react.modules.dialog.DialogModule$b.c(Unknown Source)
>        at com.facebook.react.modules.dialog.DialogModule$b.a(Unknown Source)
>        at com.facebook.react.modules.dialog.DialogModule$1.run(Unknown Source)
>        at android.os.Handler.handleCallback(Handler.java:751)
>        at android.os.Handler.dispatchMessage(Handler.java:95)
>        at android.os.Looper.loop(Looper.java:154)
>        at android.app.ActivityThread.main(ActivityThread.java:6119)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
> 
> 1. RenderDrive
>        at java.lang.Thread.sleep(Thread.java)
>        at java.lang.Thread.sleep(Thread.java:371)
>        at java.lang.Thread.sleep(Thread.java:313)
>        at com.google.maps.api.android.lib6.gmm6.vector.p.run(:com.google.android.gms.dynamite_mapsdynamite@15090051@15.0.90 (040408-231259764):12)
> 
> 2. Queue
>        at java.lang.Object.wait(Object.java)
>        at java.lang.Thread.parkFor$(Thread.java:2127)
>        at sun.misc.Unsafe.park(Unsafe.java:325)
>        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:161)
>        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2035)
>        at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:519)
>        at io.a.a.a.a.c.c.a(Unknown Source)
>        at io.a.a.a.a.c.c.b(Unknown Source)
>        at io.a.a.a.a.c.c.a(Unknown Source)
>        at io.a.a.a.a.c.c.take(Unknown Source)
>        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1058)
>        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1118)
>        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
>        at java.lang.Thread.run(Thread.java:761)

## Environment
```
 React Native Environment Info:
    System:
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.2.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 21, 22, 23, 24, 25, 26, 27, 28
        Build Tools: 27.0.3, 28.0.2, 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: ^0.56.0 => 0.56.1 
    npmGlobalPackages:
      react-native-cli: 2.0.1

```
Also, I saw that the problem is already existing from 2016.
https://github.com/facebook/react-native/issues/6228
https://github.com/facebook/react-native/issues/6200

**Comment by HoaPham2711** [comment]
Hi Guy! Did you fix the crash?
