### ISSUE TITLE
AsyncStorage.multiRemove method has different behavior on Android and iOS

### ISSUE THREAD

**Issue by jhoobergs** [facebook/react-native#23412]
When calling the AsyncStorage.multiRemove method with an empty array, the behavior on Android and iOS is different:
 - Android: throw as error (https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/modules/storage/AsyncStorageModule.java#L262)
 - iOS: does nothing (https://github.com/facebook/react-native/blob/master/React/Modules/RCTAsyncLocalStorage.m)

**Comment by guhungry** [comment]
Async Storage was extracted to separate package. Should report the issue here https://github.com/react-native-community/react-native-async-storage
