### ISSUE TITLE
vector icons show error when element is created

### ISSUE THREAD

**Issue by sarveshcchauhan** [facebook/react-native#23420]
React Native Environment Info:
    System:
      OS: Windows 7
      CPU: (4) x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
      Memory: 1.69 GB / 7.96 GB
    Binaries:
      Yarn: 1.7.0 - C:\Users\Sarvesh\AppData\Roaming\npm\yarn.CMD
      npm: 6.7.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-173.4819257
```
npm install expo-cli -g
expo init MyTestApp
expo eject
npm i @babel/runtime --save-dev
npm i expo --save-dev
```
`"react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz"`
To
```
"react-native": "0.57.8"
npm install
npm i react@latest --save
```
Created index.js File

I have followed the above steps and created an app
But when I add Vector Icons Package and have created elements It showing me below Error
I have checked adding package such as expo,expo-file-syetem but none of them work also not working
react-native-touchable-scale, react-native-linear-gradient from react-native-elemenst
help me to solve this problem

![expo](https://user-images.githubusercontent.com/18181752/52702894-2812b480-2fa3-11e9-8db2-f8bccfa2c084.png)

**Comment by Titozzz** [comment]
This issue belong on the expo repo, and not here please open an issue there: https://github.com/expo/expo/issues
