### ISSUE TITLE
[META] add test case for template

### ISSUE THREAD

**Issue by gengjiawen** [facebook/react-native#23432]
Test template is working in ci system. With this the when release new version should be more confident.

I may not have time for this recently, any pr is welcome.

**Comment by gengjiawen** [comment]
Related issue: https://github.com/facebook/react-native/issues/23893.

**Comment by gengjiawen** [comment]
@grabbou Is there a mechanism we can init a project from a local template. With this feature, we can test CI in current workflow to prevent bug and regressions.

cc @dulmandakh @hramos @cpojer

**Comment by grabbou** [comment]
We already do it. Check ./scripts/test-manual-e2e.sh.

We always take default template from React Native version we init.

**Comment by gengjiawen** [comment]
I see, thanks. But it maybe a litter cumbersome since it requires run `npm pack` first.
Maybe still can work with it in ci. I will see what I can do.

**Comment by grabbou** [comment]
We could definitely allow `--template` flag to accept path to a local
folder instead of an npm package name. Something to consider for the
future. CC: @Esemesek

**Comment by cpojer** [comment]
We have this now.
