### ISSUE TITLE
Button is not working when button-style position is absolute

### ISSUE THREAD

**Issue by qurugi0347** [facebook/react-native#23448]
## My Problem
When I changed the button-style position to absolute
The top half of the button shows the button-click effect, but navigate('Login') function is not working
but the lower half of the button works without any problems.

## Expected Behavior
When button-style position is absolute,
I want the button to function normally wherever I press it.

## Code Example
```
<View style={styles.grade_view}>
  <Text style={styles.grade_text}>aaaa</Text>
  <Text style={styles.grade_num}>-</Text>
  <Button
  onPress={() => {
    navigate('Login');
  }}
  buttonStyle={{
      backgroundColor: '#AAA',
      width: 140,
      height: 40,
      position: 'absolute',
      borderRadius: 20,
      top: -45,
      right: 10
  }}
  type="solid"
  title="login"
  color="#AAA"
  />
</View>
```

```
const styles = StyleSheet.create({
  grade_view: {
    padding: 15,
    borderColor: '#999',
    borderBottomWidth: 1
  },
  grade_num: {
    marginTop: 5,
    fontSize: 26,
    fontWeight: 'bold',
  },
  grade_text: {
    fontSize: 16,
    color: '#AAA'
  }
});
```
## Environment
react-native-cli: 2.0.1
react-native: 0.58.4
node: v10.15.0
npm: 6.4.1
Test Device: iPhone X - 12.1 (XCode Virtual Device)

React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 34.14 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.6.3 => 16.6.3 
      react-native: 0.58.4 => 0.58.4 
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by JKCooper2** [comment]
Unable to reproduce with
Snack: https://snack.expo.io/@jkcooper/rn-issue#-23448---button-position

**Comment by qurugi0347** [comment]
Sorry I forget i imported button from react-native-elements
`import React, { Component } from 'react';
import { Button } from 'react-native-elements';
import { StyleSheet, Text, View } from 'react-native';`

**Comment by JKCooper2** [comment]
I would recommend raising on issue on their repo if it's not replicatable with the React Native Button
