### ISSUE TITLE
[Docs] Packaging a React Native component

### ISSUE THREAD

**Issue by paramaggarwal** [facebook/react-native#2344]
Just read http://brentvatne.ca/packaging-react-native-component/. Should we add something similar to the official docs? Will help with the quality/usability/consistency of third party libraries.

**Comment by sghiassy** [comment]
+1

**Comment by paramaggarwal** [comment]
@brentvatne what do you think?

**Comment by browniefed** [comment]
@brentvatne :) could add it as a guide. 
https://github.com/brentvatne/brentvatne.github.io/blob/master/_posts/2015-04-16-packaging-react-native-component.markdown

**Comment by mkonicek** [comment]
Sounds good, can you send a PR to do this?

**Comment by Hari70a** [comment]
@paramaggarwal  and @browniefed  
I have submitted  a pull request for adding the  #7323

**Comment by lacker** [comment]
IMO docs are nice but we could also use some tool support for this. cc @mkonicek @ericvicenti - food for thought.
