### ISSUE TITLE
Dimensions.get('window').height iPhone x The results for 667

### ISSUE THREAD

**Issue by xiaoqian9** [facebook/react-native#23447]
## 🐛 Bug Report
Dimensions.get('window').height 
Gets the height of the iphone x to be 667 ？

## Environment
react-native  0.44.0
react              16.0.0-alpha.6
mac OS
Simulator 

$ react-native -v
react-native-cli: 2.0.1
react-native: 0.44.0

**Comment by xiaoqian9** [comment]
> 您是否可以运行`react-native info`和编辑问题以在**环境**部分下包含这些结果？
> 
> 如果您认为此信息与报告的问题无关，您可以`[skip envinfo]`在**环境**下写信告诉我们。

![image](https://user-images.githubusercontent.com/20238870/52771423-d0db1580-3070-11e9-8c80-728b736f1e70.png)

**Comment by xiaoqian9** [comment]
hellp me~

**Comment by xiaoqian9** [comment]
> 您是否可以运行`react-native info`和编辑问题以在**环境**部分下包含这些结果？
> 
> 如果您认为此信息与报告的问题无关，您可以`[skip envinfo]`在**环境**下写信告诉我们。

What additional information is needed?

**Comment by xiaoqian9** [comment]
Dimensions.get('window').height
Gets the height of the iphone x to be 667

**Comment by xiaoqian9** [comment]
![image](https://user-images.githubusercontent.com/20238870/52832129-316e5f00-3112-11e9-9f21-d58c5b4972b2.png)
![image](https://user-images.githubusercontent.com/20238870/52832151-421ed500-3112-11e9-8507-647532154a96.png)

**Comment by fsfhiyg** [comment]
您是否可以运行react-native info和编辑问题以在环境部分下包含这些结果？

如果您认为此信息与报告的问题无关，您可以[skip envinfo]在环境下写信告诉我们。

What additional information is needed?
