### ISSUE TITLE
[Packager] InternalError when run the initial project created by react-native-cli

### ISSUE THREAD

**Issue by foolyoghurt** [facebook/react-native#2345]
When I used `react-native-cli` to create my first react-native project and run it in XCode. It just failed and showed some errors.

![](http://img3.tbcdn.cn/5476e8b07b923/TB137VyJXXXXXaqXVXXXXXXXXXX)

Error messages shown in terminal:
```
[01:21:41] <START> fs crawl
Error: failed to parse query: must use ["allof", expr...]
    at BunserBuf.<anonymous> (/Users/Song/tmp/Awesome/node_modules/react-native/node_modules/sane/node_modules/fb-watchman/index.js:93:23)
    at emitOne (events.js:77:13)
    at BunserBuf.emit (events.js:169:7)
    at BunserBuf.process (/Users/Song/tmp/Awesome/node_modules/react-native/node_modules/sane/node_modules/fb-watchman/bser.js:289:10)
    at /Users/Song/tmp/Awesome/node_modules/react-native/node_modules/sane/node_modules/fb-watchman/bser.js:244:12
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)
```

**Environment**
> iojs 3.0.0
Xcode Version 6.4 (6E35b)
watchman 3.3.0

**Comment by MatApple** [comment]
Having the same problem. I tried updating watchman to the HEAD version but didn't fix. When I ```brew uninstall watchman``` I get
```
<START> fs crawl
<END>   fs crawl (2903ms)
```
but with watchman installed, it hangs forever on 
```
<START> fs crawl
```
and I get the same issue as @foolyoghurt

**Comment by foolyoghurt** [comment]
If I change the react-native version to 0.6.0（now I use 0.9.0） in `package.json` and delete node_modules to rerun `npm install`, it works. However, `cmd + R` doesn't refresh as expected.

**Comment by AbrahamAlcaina** [comment]
I have the same issue. 
It seems is related with https://github.com/facebook/watchman/issues/134.

**Comment by MatApple** [comment]
Moving project out of my Dropbox folder resolves the issue for me.

**Comment by foolyoghurt** [comment]
@AbrahamAlcaina I update the latest watchman but it still doesn't, now I just use `nodemon -e js -x "npm start"` to restart the service when some javascript file changes.

**Comment by AbrahamAlcaina** [comment]
I solved It doing a downgrade of iojs from 3.0 to 2.5.

**Comment by Emibob** [comment]
Was having the same issue. I uninstalled watchman & installed it again.

**Comment by foolyoghurt** [comment]
I've downgraded iojs from 3.0 to 2.4 and reinstall the lastest watchman, but it still doesn't work. There seems to have some problem with **watchman**, but I don't know why Facebook can not fix this problem and why they use watchman(I find so many errors related to watchman when I use google)

**Comment by brentvatne** [comment]
@foolyoghurt - watchman is well suited for Facebook's needs internally but maybe not always the best for oss users :( 

If you create a new project does that work? When you install watchman, try installing from head: `brew uninstall watchman && brew install watchman --HEAD`

**Comment by dzjin** [comment]
I had this problem when trying to run a new React Native app. @brentvatne helped me on Slack.

A lot of combinations didn't work, and what I ended up doing was go to install watchman from source:
https://facebook.github.io/watchman/docs/install.html

I'm running on Node 4.1.0, NPM 2.14.3, Yosemite.

**Comment by graemeasher** [comment]
I was encountering this same issue with react-native 0.11.1 and Node 4.1.0. I tried all the solutions others mentioned in the thread to no avail, including rolling back to previously working versions of my project and previously working versions of node and dependant node modules. Attempting to reinstall watchman, react-native and other modules had no effect. It was only after I completely removed NVM and reinstalled NVM, Node 4.1.0 and then all project dependancies that I was able to run my project without getting this error. I am now good to go on react-native 0.11.1 with Node 4.1.0.

**Comment by dzjin** [comment]
@graemeasher did you perhaps reinstall xcode as well? I've tried blowing away everything node, including the versions I had in brew, and reinstalled. Still having that error.

Are you creating projects via react-native init 'name'? or do you have it cloned? What version of XCode are you using? Did you have anything to do with Python path for some of the node modules?

Sorry about the bombardment of questions.

**Comment by graemeasher** [comment]
@dzjin I did not reinstall Xcode. And yes I am creating projects via react-native init. I was running Xcode 7.0.1 on OSX 10.10 at the time of my last post. I am now running 10.11.1 with no issues. No Python involved to the best of my knowledge.

**Comment by thomasp9** [comment]
Reinstalling nvm and watchman solved it for me. Running Xcode 7.0.1 and OSX 10.11.

**Comment by knubie** [comment]
I had the same error, for me it had to do with some strange issue in OS X where a directory was capitalized but also somehow not capitalized at the same time. I solved the issue by renaming the directory.

**Comment by jsierles** [comment]
@facebook-github-bot answered

**Comment by diehardest** [comment]
> jsierles commented on Mar 20, 2016
> @facebook-github-bot answered

Hey @jsierles, I am also getting this error and can not find a way to fix it. Could you, please, pin me to the answer?
