### ISSUE TITLE
Attempt to invoke virtual method 'android.grphics.drawable' ... on a null object reference

### ISSUE THREAD

**Issue by Graymark** [facebook/react-native#23456]
Hey :)
i have this error who occurs when i click on a button who navigate to another view
![image](https://user-images.githubusercontent.com/23309661/52798756-dccad580-3078-11e9-9e91-9e75ffd4dc1b.png)
I really don't know why this issue occurs because the only things that i've changed in my project is some styling.

Any help or kind of tips or clue is welcome <3

**Comment by bigkrys** [comment]
> Hey :)
> i have this error who occurs when i click on a button who navigate to another view
> ![image](https://user-images.githubusercontent.com/23309661/52798756-dccad580-3078-11e9-9e91-9e75ffd4dc1b.png)
> I really don't know why this issue occurs because the only things that i've changed in my project is some styling.
> 
> Any help or kind of tips or clue is welcome <3

Hello, I also encountered this problem. How did you solve it
