### ISSUE TITLE
React native overflow visible not working in android even after updated to RN 0.58.4

### ISSUE THREAD

**Issue by vinayakb-pits** [facebook/react-native#23455]
## 🐛 Bug Report
According to[ this](https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md#user-content-0572) RN release , now on we can use overflow:'visible' in android . But still React Native Android clipping its Children view.  

## To Reproduce
cosider below example
https://snack.expo.io/ryZwe-mHN

output in android 
https://i.stack.imgur.com/M560e.png

output in iOS
https://i.stack.imgur.com/jsUwW.jpg

## Expected Behavior
the parent should not clip the child view 
like this https://i.stack.imgur.com/jsUwW.jpg
## Code Example
Please consider snack expo url 
https://snack.expo.io/ryZwe-mHN
or 
SO Question
https://stackoverflow.com/questions/54693030/react-native-overflow-visible-not-working-in-android-even-after-updated-to-rn-0

## Environment
React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
      Memory: 520.89 MB / 7.91 GB
    Binaries:
      Yarn: 1.7.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 4.6.1 - C:\Program Files\nodejs\npm.CMD

I am getting only this much information when I run react-native info

my package.json is

`{
  "name": "OverFlowIssue",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.6.3",
    "react-native": "0.58.4"
  },
  "devDependencies": {
    "babel-core": "7.0.0-bridge.0",
    "babel-jest": "24.1.0",
    "jest": "24.1.0",
    "metro-react-native-babel-preset": "0.51.1",
    "react-test-renderer": "16.6.3"
  },
  "jest": {
    "preset": "react-native"
  }
}
`

**Comment by cpojer** [comment]
Should be in 0.59.

**Comment by Remigar2012** [comment]
@cpojer   "react-native": "0.59.1" overflow:"visible" don't working

**Comment by cpojer** [comment]
Do you mind sending a fix for the remaining issue?

**Comment by gmajali** [comment]
should be in 0.59 but im using 0.59.3 and its still not working...

**Comment by Johncy1997** [comment]
`overflow:'visible'` is hidden on android. Please refer my screenshot. Plz tell me some possible solution.
<img width="590" alt="Screenshot 2019-06-06 at 10 58 50 AM" src="https://user-images.githubusercontent.com/25324938/59009211-44847680-884a-11e9-8913-a03535a4bbc0.png">

**Comment by Johncy1997** [comment]
I have solved this issue by creating AndroidPackage as said [here](https://github.com/facebook/react-native/issues/16951). Its perfectly working for me
<img width="547" alt="Screenshot 2019-06-06 at 12 18 43 PM" src="https://user-images.githubusercontent.com/25324938/59012503-4e5fa700-8855-11e9-8c52-706e300d2b00.png">

**Comment by Duckers** [comment]
Still not working in 0.60.5

**Comment by grantgeorge** [comment]
As per the docs:

> On Android, all views will clip their children.

https://facebook.github.io/react-native/docs/0.51/layout-props#overflow
