### ISSUE TITLE
RN 0.58 ignores JSC specified in resolutionStrategy

### ISSUE THREAD

**Issue by RevanScript** [facebook/react-native#23454]
## 🐛 Bug Report
RN 0.58 uses the built in JSC instead of the one specified in:

```
configurations.all {
  resolutionStrategy {
    force 'org.webkit:android-jsc:r224109'
  }
}
```

It works on RN 0.57, but stopped working on 0.58. It's impossible to use `mobx` because of this (production built crashes).

## To Reproduce
1. Install `jsc-android`: `npm install jsc-android@224109.x.x`
2. Add this code to gradle:

```
allprojects {
    repositories {
        ...

        configurations.all {
            resolutionStrategy {
                force 'org.webkit:android-jsc:r224109'
            }
        }
    }
}
```

3. Production built will crush, if `Symbol` will be used for example.

## Expected Behavior
JSC specified in `resolutionStrategy` should be used

## Environment
  React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 49.94 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 9.11.1 - /usr/local/bin/node
      npm: 5.6.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 26.0.1, 26.0.3, 27.0.3, 28.0.1, 28.0.2, 28.0.3
        System Images: android-P | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.6.3 => 16.6.3 
      react-native: ^0.58.4 => 0.58.4 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

**Comment by hramos** [comment]
This is all changing in 0.59, which includes a newer JSC. We're unlikely to make changes to 0.58 specifically. Can you try the 0.59 RC and let us know if this is still an issue? I'd like to make sure you're still able to bring your own JSC with 0.59.

**Comment by RevanScript** [comment]
Thanks for the answer. Can confirm that 0.59 works fine
