### ISSUE TITLE
Refresh Indicator Stops

### ISSUE THREAD

**Issue by FelipeGatti** [facebook/react-native#23458]
## 🐛 Bug Report
The Refresh Control Indicator stops right after it starts, so what i see is only a dot in a circle.

It's not easy to reproduce this bug, in the same device it works when i run react-native run-android but doesn't work when i download it from the Alfa test in the Google Play Store.

## Expected Behavior
The indicator should be circling.

## Code Example
<ScrollView refreshControl={ <RefreshControl refreshing={this.state.refreshing} onRefresh={this.onRefresh.bind(this)} colors={['#f7941e', '#f7941e', '#f7941e']} progressBackgroundColor="#fff" /> }>
  onRefresh() {
      this.setState({refreshing: true});

## Environment
react-native-cli: 2.0.1
react-native: 0.57.8
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
      Memory: 7.13 GB / 15.70 GB
    Binaries:
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338

**Comment by fuwenchun** [comment]
@FelipeGatti Hi, I have encountered the same problem. Could you tell me how you solved it
