### ISSUE TITLE
chore: cost of dependencies in react-native

### ISSUE THREAD

**Issue by nimish-gupta** [facebook/react-native#23469]
Here is the list of the dependencies along with their sizes. 
https://www.dropbox.com/s/g3hzj3q07xtrbl3/Screenshot%202019-02-15%2004.54.54.png?dl=0

We can go through this list and replace the packages which are causing the increase in the bundle size.

**Comment by nimish-gupta** [comment]
FYI, used [this](https://github.com/siddharthkp/cost-of-modules) package to determine the size of the  dependencies

**Comment by cpojer** [comment]
Thanks for doing this analysis. We'll use as a guidance to reduce some of our dependencies but I'm gonna close this issue as we have the Lean Core issue to track it already.
