### ISSUE TITLE
WebSocket onclose does not return CloseEvent

### ISSUE THREAD

**Issue by Kikketer** [facebook/react-native#23468]
## 🐛 Bug Report

Upon server disconnect or clean `close` of a WebSocket a `WebSocketEvent` is given to the `onclose` handler instead of a `CloseEvent`.  This means that `.code` and `.reason` are not present on the object as described in the docs: https://facebook.github.io/react-native/docs/network#websocket-support

Related? 
https://github.com/facebook/react-native/issues/12678
https://github.com/facebook/react-native/issues/14617

## To Reproduce

Create a socket connection to a server then close it:
```
this.socket = new WebSocket('ws://localhost:3005')

this.socket.onopen = () => {
  console.log('open!')
}
this.socket.onclose = closeEvent => {
  console.log('status: ', closeEvent)
}

this.socket.close(4001, 'Some app reason')
```

Also instead of running `this.socket.close` simply shut down the socket server as that will cause the `onclose` event to fire as well.

## Expected Behavior

For the `onclose` parameter to be an instance of CloseEvent: https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent or at least similar enough to have `.code` and `.reason` in it per what the docs state: https://facebook.github.io/react-native/docs/network#websocket-support

## Code Example

See the "reproduce" portion for the very simplified form of the code.  The socket server I'm using can be started quickly using: https://github.com/Kikketer/socket-test

## Environment

```
  React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
      Memory: 2.89 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 22, 23, 26, 27, 28
        Build Tools: 23.0.1, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.0, 28.0.2, 28.0.3
        System Images: android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react-native: 0.57.1 => 0.57.1
```

**Comment by isidornygren** [comment]
Can confirm this is still an issue running 0.58.4, neither the `reason` nor `code` field gets passed to the enclose event.

```
  React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (4) x64 Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz
      Memory: 19.71 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.5.0 - ~/.nvm/versions/node/v10.5.0/bin/node
      npm: 6.1.0 - ~/.nvm/versions/node/v10.5.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 26, 27, 28
        Build Tools: 27.0.3, 28.0.2, 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.6.1 => 16.6.1 
      react-native: ^0.58.4 => 0.58.4 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

**Comment by keshavkaul** [comment]
Issue still persists in react-native v0.59.10
