### ISSUE TITLE
[0.10] Missing breaking changes?

### ISSUE THREAD

**Issue by grabbou** [facebook/react-native#2347]
After upgrading to 0.10, getting this runtime exception:

> Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'customDirectEventTypes must return an array, but CustomModuleManager returned __NSDictionaryI

Not sure if this feature is meant to be for private internal use only, but some packages, most notably @brentvatne ones are using it (was an inspiration for my work)

**Comment by grabbou** [comment]
Another change worth (maybe) mentioning:
- `replaceAtIndex` no longer replaces a route when same component is supplied. This is obviously more idiomatic solution, but I was relaying on the previous concept quite extensively in one route.

**Comment by ms88privat** [comment]
0.10.0-rc did also break the "react-native-blur" module. It says ~ 'missing "RCTViewNodeProtocol.h"' 
https://github.com/Kureev/react-native-blur/blob/master/RNVibrancy/VibrancyView.m#L3

Somebody knows what happend here?

**Comment by brentvatne** [comment]
Thanks, great points @grabbou - I will update the release notes accordingly.

Notice that `customDirectEventTypes` is now just an array of strings: https://github.com/facebook/react-native/blob/master/React/Views/RCTViewManager.m#L88-L95, no "registrationName" required

**Comment by brentvatne** [comment]
@ms88privat - thanks for pointing that out - RCTViewNodeProtocol has been replaced with RCTComponent, can you create an issue or pull request on the react-native-blur repo? I'll add this to the release notes as well

**Comment by Kureev** [comment]
@brentvatne Would `RCTComponent` work on 0.9.0?

**Comment by brentvatne** [comment]
@Kureev - nope, just 0.10

**Comment by brentvatne** [comment]
> Another change worth (maybe) mentioning:

> replaceAtIndex no longer replaces a route when same component is supplied. This is obviously more idiomatic solution, but I was relaying on the previous concept quite extensively in one route (componentDidMount)

@ericvicenti @hedgerwang - are you aware of this? is it intentional?

**Comment by ide** [comment]
@grabbou, @brentvatne thanks for fixing the release notes

**Comment by grabbou** [comment]
This also affects pushing as well @brentvatne as far as I know as all these methods use the same private one.

**Comment by grabbou** [comment]
@brentvatne thanks for tips, already made that change yesterday in my private libraries to ensure they are 0.10 compatible when we upgrade next week.

**Comment by Kureev** [comment]
`0.6.1` should fix this
