### ISSUE TITLE
createMaterialBottomTabNavigator - outside of borderRadius color is belong to nowhere.  

### ISSUE THREAD

**Issue by SoominHan** [facebook/react-native#23471]
## 🐛 Bug Report

![image](https://user-images.githubusercontent.com/17259632/52827970-bdd94b80-312b-11e9-98e7-53fd47c55c1d.png)

Between screen background and bottom navigation tap(outside of borderRadius), I cannot set the color. 

## Code Example

export default createMaterialBottomTabNavigator({
  HomeStack,
  ProjectListStack,
  ScannerStack,
  SettingsStack,
},
  {
    initialRouteName: 'ProjectListStack',
    shifting: true,
    activeColor: '#E12A62',
    inactiveColor: '#3e2465',
    barStyle: {
      backgroundColor: 'tomato',
      paddingBottom: 10,
      paddingLeft: 20,
      paddingTop: 10,
      paddingRight: 20,
      borderTopEndRadius: 40,
      borderTopStartRadius: 40,
      overflow: 'hidden'
    },
  },
);

## Environment
react-native@0.58.4 | MIT | deps: 53 | versions: 285
A framework for building native apps using React
https://github.com/facebook/react-native#readme
bin: react-native
dist
.tarball: https://registry.npmjs.org/react-native/-/react-native-0.58.4.tgz
.shasum: bb1392727712787ba84983104c4920c0f4082677
.integrity: sha512-vJlku+vRgiip9i2/NvYHYvMnHPZftROOnHdbeFCkxNpb90oot+VrocbkXe7qhVKCBKZTQrRNb5P+m0Gtv59Zcg==
.unpackedSize: 40.4 MB
dependencies:
@babel/runtime: ^7.0.0        chalk: ^1.1.1                 create-react-class: ^15.6.3   errorhandler: ^1.5.0          fbjs: ^1.0.0                  inquirer: ^3.0.6
absolute-path: ^0.0.0         commander: ^2.9.0             debug: ^2.2.0                 escape-string-regexp: ^1.0.5  fs-extra: ^1.0.0              lodash: ^4.17.5
art: ^0.10.0                  compression: ^1.7.1           denodeify: ^1.2.1             event-target-shim: ^1.0.5     glob: ^7.1.1                  metro-babel-register: ^0.49.1
base64-js: ^1.1.2             connect: ^3.6.5               envinfo: ^5.7.0               fbjs-scripts: ^1.0.0          graceful-fs: ^4.1.3           metro: ^0.49.1
(...and 29 more.)
maintainers:
- bestander <bestander@gmail.com>
- fb <opensource+npm@fb.com>
- ide <ide+npm@jameside.com>
- react-native-bot <opensource+react-native-bot@fb.com>
- sophiebits <npm2@sophiebits.com>
dist-tags:
latest: 0.58.4     next: 0.58.0-rc.3

**Comment by joezneba** [comment]
I had the same problem what I did was add absolute position and it was fixed.
tabBarOptions: {
            style: {
                backgroundColor: 'rgba(0,0,0,1)',
                borderRadius:15,
                marginBottom:5,
                position:'absolute' 
            },
        }
