### ISSUE TITLE
SaveToCameraRoll crash app after permission is asked.

### ISSUE THREAD

**Issue by jonathangreco** [facebook/react-native#23477]
## 🐛 Bug Report
In a promise, after I download a film from an API, the film need to be saved into the camera roll.
But if this is the first time on the app, IOS will ask the permission to save the downloaded film into the camera roll.

we accept.

Then the screen have frozen. The app need to be restarted, after that the app will no longer crash since the permission has been granted.

## To Reproduce
Download a film from an API
Don't have `NSPhotoLibraryUsageDescription` nor `NSPhotoLibraryAddUsageDescription` granted into your application.
Save to Camera Roll  like this code :

```
import {CameraRoll} from "react-native";
import RNFetchBlob from 'rn-fetch-blob';

export const downloadFilm = async (uri, downloadProgress, callback) => {
  RNFetchBlob.config({
      fileCache : true,
      appendExt : 'mp4'
    }).fetch('GET', uri).progress((received, total) => {
        downloadProgress(received, total);
    }).then((res) => {
        downloadProgress(1, 1);
        CameraRoll.saveToCameraRoll(res.data).then((uri) => {
          callback(uri);
        });
    }).catch((errorMessage, statusCode) => {
      // error handling
    })
};
```

## Expected Behavior

The app should not freeze nor crash. But to save the downloaded film into the camera roll.

## Code Example
With the code already given on the previous section i give the all methods below related to the problem

```
  downloadProgress = (received, total) => {
    let percent = Math.floor((received/total) * 100) ;
    if (percent !== 100) {
       this.setState({downloadProgress : percent / 100, downloadFinish: false, downloadBegin: true});
    } else {
      this.setState({downloadProgress : percent / 100, downloadFinish: true, downloadBegin: false});
      toast(I18n.t('film_download'), 'success', 5000);
    }
  };

  download = () => {
    this.setState({downloadBegin:true});
    downloadFilm(this.state.uri.film, this.downloadProgress, this.saveCameraRollUri);
  }

  /**
   * Save the film on Camera Roll in order to be accessed whenever we want
   * @param uri
   */
  saveCameraRollUri = (uri) => {
    const {localTemplate} = this.props;
    localTemplate.uriShareFilm = uri;
    this.props.localTplAction.saveTemplateStatus(localTemplate);
    this.setState({downloaded: true, uriShareFilm: uri});
  };
```

## Environment
IOS on Iphone 8 / XR.

I use redux and redux persist.
I use rn-fetch-blob to download files.

###  React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 28.64 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.9.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728 
      react-native: 0.58.4 => 0.58.4 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native: 0.56.0

After hours to debug in order to upgrade...

## Questions
Do i do something wrong in the code ? The promise combined with the permission is maybe buggy ?
Do I have another solution ?

Can I ask the permission on IOS manually whenever I want ?

**Comment by jonathangreco** [comment]
Is missing something to this issue to have an answer ?
Is someone have a workaround ?

**Comment by jonathangreco** [comment]
The way I solved it was to fake a read access into gallery, then permission is asked and further download will not prompt & crash the app. But it's a workaround.

**Comment by cpojer** [comment]
This issue has been moved to react-native-community/react-native-cameraroll#13.
