### ISSUE TITLE
Error when using react-native run-ios

### ISSUE THREAD

**Issue by thongleduy** [facebook/react-native#23489]
I am using react-native 0.58.0 to init a project with command: react-native init <project>. After creating done, i run it use: react-native run-ios. However, i meet an error as below:

** BUILD SUCCEEDED **

The following commands produced analyzer issues:
	Analyze /Volumes/Data/ReactNative/abc/node_modules/react-native/React/Base/RCTModuleMethod.mm normal x86_64
	Analyze /Volumes/Data/ReactNative/abc/node_modules/react-native/Libraries/Image/RCTImageCache.m normal x86_64
	Analyze /Volumes/Data/ReactNative/abc/node_modules/react-native/Libraries/Network/RCTNetInfo.m normal x86_64
(3 commands with analyzer issues)

Installing build/Build/Products/Debug-iphonesimulator/abc.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/abc.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

I had tried many times but the issue stills happen.  Please help me!

**Comment by patrickkempff** [comment]
@thongleduy thank you for reaching out! Did you already try the solutions proposed in https://stackoverflow.com/questions/37461703/print-entry-cfbundleidentifier-does-not-exist? There are several possible solutions, can you try to see if those resolve your issue?

**Comment by puneet10** [comment]
**Installing POD can resolve this issue**

https://stackoverflow.com/questions/20755044/how-to-install-cocoapods
