### ISSUE TITLE
Content inside scroll view with contentInsetAdjustmentBehavior with incorrect height

### ISSUE THREAD

**Issue by 1987cr** [facebook/react-native#23480]
## 🐛 Bug Report
It seems that scroll view doesn't calculate properly the size of its container when `contentInsetAdjustmentBehavior` is set to `automatic`

## To Reproduce
Refer to this snack:
https://snack.expo.io/r1XhuwVBV

When `contentInsetAdjustmentBehavior` is set to `automatic`, the container view get's pushed from the top, but the container maintains the same height, so you have an extra scroll size that hides the bottom text.

<img width="296" alt="screen shot 2019-02-15 at 17 26 01" src="https://user-images.githubusercontent.com/4684912/52870448-27675300-3148-11e9-895b-86cab4e03f03.png">

For reference, same code with `contentInsetAdjustmentBehavior` set to `never`:

<img width="302" alt="screen shot 2019-02-15 at 17 25 47" src="https://user-images.githubusercontent.com/4684912/52870495-4534b800-3148-11e9-93da-bfc376a8e609.png">

## Expected Behavior

Content should just take the remaining space.

<img width="301" alt="screen shot 2019-02-15 at 17 45 06" src="https://user-images.githubusercontent.com/4684912/52871052-811c4d00-3149-11e9-9fed-eaa1ae6c686f.png">

## Code Example
https://snack.expo.io/r1XhuwVBV

## Environment
```
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
      Memory: 2.82 GB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.13.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 27, 28
        Build Tools: 27.0.3, 28.0.3
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5014246
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.58.4 => 0.58.4 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

**Comment by danielmartinprieto** [comment]
We're experiencing it as well and it's quite annoying, does anyone know any workaround?

**Comment by zhongwuzw** [comment]
@1987cr Hi, thanks for reporting issue, I think it may designated behavior, contentInset adjustment don't change frame of component, which means distance between top text and bottom text is constant.

**Comment by danielmartinprieto** [comment]
Sorry, @zhongwuzw, thanks for the comment. Could you clarify why do you think that's intended? Note that the intrinsic content size of the component inside is smaller than remaining space, and that's why I also think it shouldn't add the extra height. If this content were bigger, then the behaviour would be ok (and it is, I think).

From a practical point of view, it just doesn't look well. If you have some small content inside a scroll view and then a button you want to pin at the bottom, and you want the scroll view to respect the safe area, you can't get the desired behaviour, instead, the button will be pushed down more than it should.

**Comment by danielmartinprieto** [comment]
👋

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by danielmartinprieto** [comment]
👋

**Comment by danielmartinprieto** [comment]
👋

**Comment by a-eid** [comment]
having a similar issues.

**Comment by dani-mp** [comment]
Btw, this also happens when `contentInsetAdjustmentBehavior` is `always`.

**Comment by dani-mp** [comment]
Still there.

**Comment by blueberry6401** [comment]
Hello?

**Comment by burakgormek** [comment]
This is so annoying :(

**Comment by dani-mp** [comment]
@1987cr cómo está lo más bonito de Sant Cugat?

**Comment by dani-mp** [comment]
Let's try in a different way.

**This doesn't happen in Flutter.**

Kidding, I've never tried Flutter.

**Comment by ayush-goyal** [comment]
Is there any update on this? Still having this issue
