### ISSUE TITLE
BorderRadius for Horizontal FlatList 

### ISSUE THREAD

**Issue by imran1992** [facebook/react-native#23486]
# Issue
If I set `horizontal={true}` borderRadius style for `Flatlist` or its `contentContainer` doesn't take effect.
![flatlisthor](https://user-images.githubusercontent.com/14730038/52895833-a0ff4f80-31e1-11e9-917c-bfc9fec13ef2.JPG)

## Expected Behavior
  It should set Flatlist's Radius round

## Code
```
<FlatList
            style={{
              height: "100%",
              width: "86%",
              borderRadius: widthPercentageToDP(8.5),
              backgroundColor: "#B34"
            }}
            contentContainerStyle={{
              flexDirection: "row",
              alignItems: "center",
              borderRadius: widthPercentageToDP(8.5),
              backgroundColor: "#A12"
            }}
            ref={ref => {
              this.flatListRef = ref;
            }}
            data={this.NavData}
            extraData={this.state}
            ItemSeparatorComponent={this._renderSeparator}
            keyExtractor={this._keyExtractor}
            renderItem={this._renderNavItem}
            scrollEnabled={true}
            horizontal={true}
            showsHorizontalScrollIndicator={false}
          />
```

## Environment
React Native : v 0.57.8
React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz
      Memory: 2.97 GB / 7.89 GB
    Binaries:
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.1.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338

**Comment by imran1992** [comment]
> Can you run `react-native info` and edit your issue to include these results under the **Environment** section?
> 
> If you believe this information is irrelevant to the reported issue, you may write `[skip envinfo]` under **Environment** to let us know.

Added

**Comment by JKCooper2** [comment]
Unable to reproduce on snack: https://snack.expo.io/@jkcooper/rn-issue-#23486---horizontal-flatlist-border-radius

Remember that if you're using fixed widths and heights for styling that are larger than it's actually able to display then it the borders will be outside of the view. Not sure if that makes sense, but try removing the width and height from the style and doing something like putting it in a View wrapping the FlatList
