### ISSUE TITLE
The type of a default value needs to be one of

### ISSUE THREAD

**Issue by uzunF** [facebook/react-native#23498]
I'm using Remote Config and when I run project I'm getting this error on android ;

![error](https://user-images.githubusercontent.com/30953070/52914255-4ea05a80-32d7-11e9-8384-5a84bde5bcb6.jpg)
And my Android Studio Log ;

`2019-02-17 16:19:45.966 3390-3514/com.myapp E/unknown:ReactNative: Exception in native call java.lang.IllegalArgumentException: The type of a default value needs to beone of String, Long, Double, Boolean, or byte[]. at com.google.firebase.remoteconfig.FirebaseRemoteConfig.zza(Unknown Source) at com.google.firebase.remoteconfig.FirebaseRemoteConfig.setDefaults(Unknown Source) at com.google.firebase.remoteconfig.FirebaseRemoteConfig.setDefaults(Unknown Source) at io.invertase.firebase.config.RNFirebaseRemoteConfig.setDefaults(RNFirebaseRemoteConfig.java:109) at java.lang.reflect.Method.invoke(Native Method) at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372) at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160) at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) at android.os.Handler.handleCallback(Handler.java:751) at android.os.Handler.dispatchMessage(Handler.java:95) at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29) at android.os.Looper.loop(Looper.java:154) at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192) at java.lang.Thread.run(Thread.java:761)`

And versions ;
"react-native-firebase": "4.3.8",
"react-native": "0.55.4",
"com.google.firebase:firebase-config:16.1.0"

**Comment by patrickkempff** [comment]
@uzunF, thank you very much for reaching out! It looks like this issue occurs in https://github.com/invertase/react-native-firebase. Could you try and file an issue there about the problem you are facing? 

If you don't agree or think this is a bug or regression** in the **core** React Native library, please feel free to file a new issue. Make sure to include steps to reproduce the behavior.
