### ISSUE TITLE
when i run react-native run-android

### ISSUE THREAD

**Issue by glovkesh** [facebook/react-native#23516]
C:\Windows\System32\myApp>react-native run-android
JS server already running.
Building and installing the app on the device (cd android && gradlew.bat installDebug)...
> Task :app:mergeDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
  Output:  C:\Windows\System32\myApp\android\app\build\intermediates\res\merged\debug: error: directory does not exist.

  Command: C:\Users\lucky\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\c713e2313c3021b524690512ee68b028\aapt2-3.2.1-4818971-windows\aapt2.exe compile --legacy \
          -o \
          C:\Windows\System32\myApp\android\app\build\intermediates\res\merged\debug \
          C:\Windows\System32\myApp\android\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml
  Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
9 actionable tasks: 1 executed, 8 up-to-date
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

Command failed: gradlew.bat installDebug

Error: Command failed: gradlew.bat installDebug
    at checkExecSyncError (child_process.js:637:11)
    at Object.execFileSync (child_process.js:655:13)
    at runOnAllDevices (C:\Windows\System32\myApp\node_modules\react-native\local-cli\runAndroid\runAndroid.js:299:19)
    at buildAndRun (C:\Windows\System32\myApp\node_modules\react-native\local-cli\runAndroid\runAndroid.js:135:12)
    at isPackagerRunning.then.result (C:\Windows\System32\myApp\node_modules\react-native\local-cli\runAndroid\runAndroid.js:65:12)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)

C:\Windows\System32\myApp>

**Comment by wojciech-bilicki** [comment]
Similiar error happens to me but giving different info:

* Where:
Script 'E:\Projects\MyAwesomeProject\node_modules\react-native\react.gradle' line: 95

* What went wrong:
A problem occurred configuring project ':app'.
> Could not get unknown property 'mergeResourcesProvider' for object of type com.android.build.gradle.internal.api.ApplicationVariantImpl.

React Native 0.59.0-rc.1

info
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
      Memory: 4.95 GB / 15.95 GB
    Binaries:
      Node: 11.6.0 - E:\NodeJS\node.EXE
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.5.0-next.0 - E:\NodeJS\npm.CMD

**Comment by ABQJuan** [comment]
Yes, I am having the same error.
"ERROR: Could not get unknown property 'mergeResourcesProvider' for object of type com.android.build.gradle.internal.api.ApplicationVariantImpl."

I am also using React Native 0.59.0-rc.1

I am trying to implement React Hooks with React_Native. 
Also using Typescript, Win10, I5, 16GB ram, latest versions of node, android studio etc.

Breaks during build following instructions from here: https://facebook.github.io/react-native/docs/getting-started.html

using the Building Projects from Native Code variant.

Error msg reads:
"FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\johnf\Desktop\AwesomeAndroidProject\node_modules\react-native\react.gradle' line: 95

* What went wrong:
A problem occurred configuring project ':app'.
> Could not get unknown property 'mergeResourcesProvider' for object of type com.android.build.gradle.internal.api.ApplicationVariantImpl."

**Comment by alexandrius** [comment]
In gradle-wrapper.properties
change `distributionUrl` to `distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip`
and in root `build.gradle` file change gradle classpath to this: `classpath 'com.android.tools.build:gradle:3.3.0'`

**Comment by Rishabh-Rathod** [comment]
Even I am Facing issue with gradlew

` Android resource linking failed
  C:\Users\TeraBaap\.gradle\caches\transforms-1\files-1.1\appcompat-v7-28.0.0.aar\5986f3588c6f2d411bca61164fea92ca\res\values-v28\values-v28.xml:9:5-12:13: AAPT: error: resource android:attr/dialogCornerRadius not found.

  C:\Users\TeraBaap\ReactNativeProjects\foodie\android\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-v28\values-v28.xml:11: AAPT: error: resource android:attr/dialogCornerRadius not found.

  C:\Users\TeraBaap\.gradle\caches\transforms-1\files-1.1\drawee-1.10.0.aar\75a166b6228244798e8765d877ab99bf\res\values\values.xml:3:5-58:857: AAPT: error: resource android:attr/fontVariationSettings not found.

  C:\Users\TeraBaap\.gradle\caches\transforms-1\files-1.1\drawee-1.10.0.aar\75a166b6228244798e8765d877ab99bf\res\values\values.xml:3:5-58:857: AAPT: error: resource android:attr/ttcIndex not found.

  error: failed linking references.
`

App was running properly till yesterday and suddenly after adding a new libarary all messed up.
Please Help

**Comment by ABQJuan** [comment]
Thanks @alexandrius. I am not getting the gradle error anymore I am now getting the following: (Again, this happens only after I install react-native@0.59.0-rc.1)

`Error: Unable to resolve module `./index` from `C:\Users\johnf\Desktop\MyAwesomeProject\node_modules\react-native\scripts/.`: The module `./index` could not be found from `C:\Users\johnf\Desktop\MyAwesomeProject\node_modules\react-native\scripts/.`. Indeed, none of these files exist:
  * `C:\Users\johnf\Desktop\MyAwesomeProject\node_modules\react-native\scripts\index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
  * `C:\Users\johnf\Desktop\MyAwesomeProject\node_modules\react-native\scripts\index\index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
    at ModuleResolver.resolveDependency (C:\Users\johnf\Desktop\MyAwesomeProject\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (C:\Users\johnf\Desktop\MyAwesomeProject\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (C:\Users\johnf\Desktop\MyAwesomeProject\node_modules\metro\src\node-haste\DependencyGraph.js:283:16)
    at C:\Users\johnf\Desktop\MyAwesomeProject\node_modules\metro\src\lib\transformHelpers.js:261:42
    at Server.<anonymous> (C:\Users\johnf\Desktop\MyAwesomeProject\node_modules\metro\src\Server.js:1038:41)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\johnf\Desktop\MyAwesomeProject\node_modules\metro\src\Server.js:99:24)
    at _next (C:\Users\johnf\Desktop\MyAwesomeProject\node_modules\metro\src\Server.js:119:9)
127.0.0.1 - - [22/Feb/2019:17:08:41 +0000] "GET /index.delta?platform=android&dev=true&minify=false HTTP/1.1" 500 - "-" "okhttp/3.12.1"`

**Comment by timhagn** [comment]
Though this is closed, thnx @alexandrius! This did the trick for me with following `package.json`:
```
info 
  React Native Environment Info:
    System:
      OS: Linux 4.15 Linux Mint 19.1 (Tessa)
      CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
      Memory: 542.54 MB / 31.35 GB
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 11.10.0 - /usr/bin/node
      Yarn: 1.13.0 - /usr/bin/yarn
      npm: 6.8.0 - /usr/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    npmPackages:
      react: 16.8.1 => 16.8.1 
      react-native: 0.59.0-rc.2 => 0.59.0-rc.2 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
```
Can't wait for RN 0.59 (with hopefully hooks included ; )!

**Comment by webnah** [comment]
> Though this is closed, thnx @alexandrius! This did the trick for me with following Environment:

> Can't wait for RN 0.59 (with hopefully hooks included ; )!
> 
> Edit: Wrote `package.json` instead of Environment ^^.
It can build package
it's not works on ubuntu 16 dev env, although i can build it but emulator error 500, like this image
![selection_409](https://user-images.githubusercontent.com/46319124/53307958-003f1d00-38d0-11e9-8029-b972b9da04d1.jpg)

**Comment by ABQJuan** [comment]
@webnah, I'm following Ben's project too. lol. I'm on a Windows 10 machine :( and got the same screen you are showing with the same 500 error code. Frustrating to say the least

**Comment by webnah** [comment]
> @webnah, I'm following Ben's project too. lol. I'm on a Windows 10 machine :( and got the same screen you are showing with the same 500 error code. Frustrating to say the least

I change to macos (PC installed)  and the same error (benawad rnw tutorial) , the problem is they demo state in 0.59.x

**Comment by DimitryDushkin** [comment]
Same error on `run-android` with RN 0.59.0-rc.2
```
Error: Unable to resolve module `./index` from `rnapp/node_modules/react-native/.`: The module `./index` could not be found from `rnapp/node_modules/react-native/.`. Indeed, none of these files exist:
  * `rnapp/node_modules/react-native/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
  * `rnapp/node_modules/react-native/index/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
    at ModuleResolver.resolveDependency (rnapp/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (rnapp/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (rnapp/node_modules/metro/src/node-haste/DependencyGraph.js:283:16)
    at rnapp/node_modules/metro/src/lib/transformHelpers.js:261:42
    at Server.<anonymous> (rnapp/node_modules/metro/src/Server.js:1038:41)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (rnapp/node_modules/metro/src/Server.js:99:24)
    at _next (rnapp/node_modules/metro/src/Server.js:119:9)
```

**Comment by timhagn** [comment]
I got it running by following the official _Get Started_ guidelines for _Building Projects with Native Code_ Linux / Android - had to downgrade my Java Version to 8 for this to work - and applying @alexandrius "patch" to `android/gradle/wrapper/gradle-wrapper.properties` - with `com.android.tools.build:gradle:3.3.1` instead of `3.3.0` - and `android/build.gradle` respectively.
My exact `package.json` is:
```
{
  "name": "random",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.8.1",
    "react-native": "0.59.0-rc.2"
  },
  "devDependencies": {
    "@types/react": "^16.8.4",
    "@types/react-native": "^0.57.38",
    "babel-core": "^7.0.0-bridge.0",
    "babel-jest": "24.1.0",
    "jest": "24.1.0",
    "metro-react-native-babel-preset": "0.52.0",
    "react-test-renderer": "16.8.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
```
My package manager is `yarn`. Have a look at my `react-native info` in mine last [comment](https://github.com/facebook/react-native/issues/23516#issuecomment-466499476) for versions used.
Hope it helps anybody struggling : )!

**Comment by alexandrius** [comment]
There are issues with upgrading RN version. The easiest way to avoid issues is just to compare with "template" from react-native specific version branch. Here's the template from 0.59.0
https://github.com/facebook/react-native/tree/0.59-stable/template

**Comment by DimitryDushkin** [comment]
BTW I resolved issue by setting explicit (downgraded) metro version to 0.51.0: `"metro": "0.51.0",`

**Comment by marcelovicentegc** [comment]
It seems that this issue is related to the metro bundler not resolving to the right paths, thus `Unable to resolve module`...

Executing `react-native start` on one terminal at the project directory and `react-native run-android` on another terminal worked for me. 

By the way, I got metro version `0.52.0` with react-native `0.59.0-rc.2`.

Does it works for anyone else?

**Comment by ABQJuan** [comment]
@marcelovicentegc it doesn't work for me. I am still getting the `Unable to resolve module` error. I am on a Windows 10 machine.

**Comment by kimbui87** [comment]
@webnah @ABQJuan 
Copy file 'metro.config.js' in [0.59-stable/template](https://github.com/facebook/react-native/tree/0.59-stable/template) to your project.
Remove node_modules
yarn install
and run-android again.
I solved by above steps

**Comment by krrskl** [comment]
> > Though this is closed, thnx @alexandrius! This did the trick for me with following Environment:
> 
> > Can't wait for RN 0.59 (with hopefully hooks included ; )!
> > Edit: Wrote `package.json` instead of Environment ^^.
> > It can build package
> > it's not works on ubuntu 16 dev env, although i can build it but emulator error 500, like this image
> > ![selection_409](https://user-images.githubusercontent.com/46319124/53307958-003f1d00-38d0-11e9-8029-b972b9da04d1.jpg)

@webnah The same error was happening to me after applying what @alexandrius indicated. the solution after running `react-native run-android` was to stop the command after the application was already running in the emulator and then run `react-native start` and the problem went away.

**Comment by shimesami** [comment]
After spending so much time. 
Downgrading react-native version from 0.59.1 to 0.58.5 did it for me.

**Comment by supagu** [comment]
@shimesami solution works, downgrading react-native resolves the issue. 

I suspect the real problem for me is that react-native-maps needs to be upgraded to uses newer libs?

**Comment by PraAnj** [comment]
@shimesami solution works for me as well.

**Comment by carlwelchdesign** [comment]
> It seems that this issue is related to the metro bundler not resolving to the right paths, thus `Unable to resolve module`...
> 
> Executing `react-native start` on one terminal at the project directory and `react-native run-android` on another terminal worked for me.
> 
> By the way, I got metro version `0.52.0` with react-native `0.59.0-rc.2`.
> 
> Does it works for anyonete selse?

paste `/* eslint-env node */` at the top of `metro.config.js`

**Comment by giovannipds** [comment]
I was having similar issues, my antivirus was identifying things as false positive and blocking them. I've changed the antivirus. =P

**Comment by Andevelop1234** [comment]
> In gradle-wrapper.properties
> change `distributionUrl` to `distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip`
> and in root `build.gradle` file change gradle classpath to this: `classpath 'com.android.tools.build:gradle:3.3.0'`

Love ya man, thanks!
