### ISSUE TITLE
Passing "flex" as a flag to any View component causes a hard crash

### ISSUE THREAD

**Issue by rmilejcz** [facebook/react-native#23522]
## 🐛 Bug Report
Passing "flex" as a flag to a View component causes a hard crash on android:

```javascript
<View flex />
```

On iOS this behaves intuitively, with the flex flag setting flex to 1. Because of this, I am assuming this is either a bug or a property that is not meant to be exposed.

## To Reproduce

Simply create a new [snack](https://snack.expo.io/), toggle to android, and add  `<View flex />`. This seems to crash the entire expo app.

If you have a react-native android app available to test on then simply add  `<View flex />` to any component, and then render that component

## Expected Behavior

I ran into this working with [ `styled-components`](https://www.styled-components.com/). I made a small abstraction of `View` to avoid having to use JavaScript style objects too often.

I have the flex prop typed as `boolean | number`. If "flex" is passed as a flag, I expect the flex style property on the component to be set to `1`. Otherwise, I expect it to be set to the numeric value passed. A contrived example:
```javascript
const Row = styled(View)`
  flex-direction: row;
  ${({ flex }) => flex && `flex: ${flex === true ? 1 : flex}` }
`

<Row flex />
// or
<Row flex={2} />
```
Interestingly, though it is not documented, this behavior seems to be natively available on iOS. Similarly, passing a numeric flex value on android works as expected.

## Code Example

Simply create a new [snack](https://snack.expo.io/), toggle to android, and add `<View flex />`. This seems to crash the entire expo app.

## Environment
```
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (16) x64 AMD Ryzen 7 1700 Eight-Core Processor
      Memory: 3.97 GB / 15.93 GB
    Binaries:
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.5.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5199772
```

**Comment by dulmandakh** [comment]
Passing flex to View is not supported, but see below code

```jsx
<View style={{flex: 1}} />
```

Please read https://facebook.github.io/react-native/docs/flexbox

**Comment by rmilejcz** [comment]
Right but I want to support it in my own custom components and I am unable to....
