### ISSUE TITLE
Error: node_modules directory is missing. Please run `npm install` in your project directory.

### ISSUE THREAD

**Issue by mahinthan177** [facebook/react-native#23528]
C:\Users\008\Desktop>mkdir firstdb

C:\Users\008\Desktop>cd firstdb

C:\Users\008\Desktop\firstdb>npm install -g expo-cli
C:\Users\008\AppData\Roaming\npm\expo -> C:\Users\008\AppData\Roaming\npm\node_modules\expo-cli\bin\expo.js
C:\Users\008\AppData\Roaming\npm\expo-cli -> C:\Users\008\AppData\Roaming\npm\node_modules\expo-cli\bin\expo.js
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-darwin-ia32@2.2.8 (node_modules\expo-cli\node_modules\@expo\ngrok-bin-darwin-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-darwin-ia32@2.2.8: wanted {"os":"darwin","arch":"ia32"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-darwin-x64@2.2.8 (node_modules\expo-cli\node_modules\@expo\ngrok-bin-darwin-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-darwin-x64@2.2.8: wanted {"os":"darwin","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-freebsd-ia32@2.2.8 (node_modules\expo-cli\node_modules\@expo\ngrok-bin-freebsd-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-freebsd-ia32@2.2.8: wanted {"os":"freebsd","arch":"ia32"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-freebsd-x64@2.2.8 (node_modules\expo-cli\node_modules\@expo\ngrok-bin-freebsd-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-freebsd-x64@2.2.8: wanted {"os":"freebsd","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-linux-arm@2.2.8 (node_modules\expo-cli\node_modules\@expo\ngrok-bin-linux-arm):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-linux-arm@2.2.8: wanted {"os":"linux","arch":"arm"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-linux-arm64@2.2.8 (node_modules\expo-cli\node_modules\@expo\ngrok-bin-linux-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-linux-arm64@2.2.8: wanted {"os":"linux","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-linux-ia32@2.2.8 (node_modules\expo-cli\node_modules\@expo\ngrok-bin-linux-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-linux-ia32@2.2.8: wanted {"os":"linux","arch":"ia32"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-linux-x64@2.2.8 (node_modules\expo-cli\node_modules\@expo\ngrok-bin-linux-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-linux-x64@2.2.8: wanted {"os":"linux","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-sunos-x64@2.2.8 (node_modules\expo-cli\node_modules\@expo\ngrok-bin-sunos-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-sunos-x64@2.2.8: wanted {"os":"sunos","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-win32-ia32@2.2.8-beta.1 (node_modules\expo-cli\node_modules\@expo\ngrok-bin-win32-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-win32-ia32@2.2.8-beta.1: wanted {"os":"win32","arch":"ia32"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/traveling-fastlane-darwin@1.7.1 (node_modules\expo-cli\node_modules\@expo\traveling-fastlane-darwin):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/traveling-fastlane-darwin@1.7.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ expo-cli@2.10.1
updated 1 package in 111.019s

C:\Users\008\Desktop\firstdb>expo init AwesomeProject
? Choose a template: expo-template-blank
? Choose which workflow to use: managed
√ Please enter a few initial configuration values.
  Read more: https://docs.expo.io/versions/latest/workflow/configuration · 100% completed
[13:42:46] Extracting project files...
[13:42:50] Customizing project...
[13:42:51] Installing dependencies...
npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/expo/react-native-maps.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\008\AppData\Roaming\npm-cache\_logs\2019-02-19T08_13_23_010Z-debug.log
[13:43:23] Process exited with non-zero code: 1
[13:43:23] Set EXPO_DEBUG=true in your env to view the stack trace.

C:\Users\008\Desktop\firstdb>cd AwesomeProject

C:\Users\008\Desktop\firstdb\AwesomeProject>npm start

> @ start C:\Users\008\Desktop\firstdb\AwesomeProject
> expo start

[13:45:00] Starting project at C:\Users\008\Desktop\firstdb\AwesomeProject
[13:45:06] Expo DevTools is running at http://localhost:19002
[13:45:06] Opening DevTools in the browser... (press shift-d to disable)
[13:45:12] Error: node_modules directory is missing. Please run `npm install` in your project directory.
[13:45:12] Couldn't start project. Please fix the errors and restart the project.
[13:45:12] Set EXPO_DEBUG=true in your env to view the stack trace.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `expo start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\008\AppData\Roaming\npm-cache\_logs\2019-02-19T08_15_12_166Z-debug.log

C:\Users\008\Desktop\firstdb\AwesomeProject>npm install
npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/expo/react-native-maps.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\008\AppData\Roaming\npm-cache\_logs\2019-02-19T08_15_37_721Z-debug.log

**Comment by lylest** [comment]
am facing the same problem

**Comment by mahinthan177** [comment]
Hey. It's working now.
I am not install git in my PC.
download and install in your PC
Link : https://gitforwindows.org/

**Comment by JoshWhite** [comment]
I'm still seeing this issue when deploying from gitlab pipeline. Is there a reason this isn't installed as an `npm`  dep?

**Comment by CKacer** [comment]
I faced the same issue. My problem was that git was not installed on my windows environment. Installing git solved my issue.

**Comment by igoragueme** [comment]
facing the same problem and i have git installed in my windows

**Comment by xianyang27200** [comment]
me to i have this error when i try to run expo start,someone can help me.thank you

**Comment by mahinthan177** [comment]
Hello there,

I just signed the petition "Marvel Indian: We want Tony Stark's / Iron
Man's old Tamil dubbed voice" and wanted to see if you could help by adding
your name.

Our goal is to reach 10,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/6qgHybJWXG

Thanks!
Mahinthan

**Comment by keshav00001** [comment]
please help 
![image](https://user-images.githubusercontent.com/34762556/57622307-eb0e8c00-75aa-11e9-9a27-17c8cac52ff1.png)

**Comment by rudineybarbosa** [comment]
a

> please help for this problem
> ![image](https://user-images.githubusercontent.com/34762556/57622307-eb0e8c00-75aa-11e9-9a27-17c8cac52ff1.png)

Did you find how to avoid this problem?

**Comment by keshav00001** [comment]
> a
> 
> > please help for this problem
> > ![image](https://user-images.githubusercontent.com/34762556/57622307-eb0e8c00-75aa-11e9-9a27-17c8cac52ff1.png)
> 
> Did you find how to avoid this problem?

yes, i uninstall the react-native and reinstall, and change USB cable change, its work.

**Comment by rudineybarbosa** [comment]
I avoided this problem with the environment PATH variable. I added twos news paths on it. Look:

![PATH](https://user-images.githubusercontent.com/29411015/58372541-4585e180-7ef5-11e9-8f7e-1c2d45bb9e9e.PNG)
