### ISSUE TITLE
Small typo error in UIExplorer - ImageEditingExample

### ISSUE THREAD

**Issue by ms88privat** [facebook/react-native#2352]
RCTScrollViewConsts.DecelerationRate.Fast should be 'fast' instead of 'Fast'

https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/ImageEditingExample.js#L248

**Comment by browniefed** [comment]
PRs welcome :)

**Comment by brentvatne** [comment]
Submitted PR, probably not worth keeping this open because it's so small :) @ms88privat if you come across issues like this, don't hesitate to submit a PR directly! Thanks!
