### ISSUE TITLE
Image besides `stretch` & `cover` don't work at all on Android

### ISSUE THREAD

**Issue by Slapbox** [facebook/react-native#23523]
[There is already an identical issue for this, however it's been locked and marked resolved](https://github.com/facebook/react-native/issues/17684) even though it's clearly not (at least in `React-Native@0.57.1`)  which prevents discussion of that issue there.

I'm not sure whether this is a bug in React-Native or an oversight in the documentations, but `resizeModes` don't work on Android except for `stretch` and `cover`, which appear to generate identical results in most (all?) cases.

**Do we need to update the documentation [here](https://facebook.github.io/react-native/docs/image#resizemode) to state that certain modes are only supported on iOS, or are these modes supposed to work on Android?**

I've been working on this for 2 hours and any use of `contain` or `center` causes any and all images to fail to render regardless of styling/positioning of the `<Image />` and the containing `<View />`.

**Comment by dulmandakh** [comment]
could you please share sample code to reproduce the issue?

**Comment by Slapbox** [comment]
@dulmandakh thanks for your reply.

I've tried dozens and dozens of combinations of code with none working. Here's some demo code that doesn't work, but if I've gotten something wrong in the code here please don't write off the issue as simply, "wrong code," because I could produce fifty more ways that things, unfortunately, still don't work. I'm not 100% sure what the right code would look like since I've never seen this working as intended.

Thanks again for reading!

**Example:**

```js
import React from 'react';
import { Dimensions, Image, View } from 'react-native';

const example = props => (
  <View style={{ flex: 1 }}>
    <View
      style={{
        width: Dimensions.get('window').width;,
        height: 200,
        alignItems: 'center',
        justifyContent: 'center',
      }}>
      <Image
        source={require('../../assets/logo.png')}
        style={{
          alignSelf: 'center',
          flex: 1,
          resizeMode: 'contain'
        }}
      />
    </View>
  </View>
)
```

I've tried with and without `flex` on the `View` and the `Image`. I've tried with and without explicit `height` and `width` on the image. I've tried various `resizeMode`s. 

**They all result in one of two things:**

1. Image displays and far exceeds its intended bounds.
2. Image does not display at all, and instead I see an empty area where I'd expect my image to be.

**Comment by Slapbox** [comment]
It would be really great if we could re-open https://github.com/facebook/react-native/issues/17684

Being able to resize images is layout and design 101, and right now that is not possible on Android.

**Comment by dulmandakh** [comment]
Did you tried to pass resizeMode as Image prop?

**Comment by Slapbox** [comment]
@dulmandakh I did try as both a `prop` on `Image` and in the styles. I tried each way using string values for `"contain"` and `"center"` as well as  `{Image.resizeMode.center}` and `{Image.resizeMode.contain}`, which I'd seen referenced online but which are actually `undefined` 

The behavior is always identical -- works on iOS, but does not render on Android.

## iOS - "contain"
![image](https://user-images.githubusercontent.com/6835891/53190580-e81d8400-35d7-11e9-806d-a7849cf9688a.png)

## Android - "contain"
![image](https://user-images.githubusercontent.com/6835891/53190641-02eff880-35d8-11e9-95bb-6598197c6b62.png)
