### ISSUE TITLE
RNTesterSnapshotTests: Fix testScrollViewExample flakiness

### ISSUE THREAD

**Issue by hramos** [facebook/react-native#23539]
# Help Wanted: Fix `ScrollViewExample` flakiness

As part of the RNTesterSnapshotTests, the RNTester ScrollViewExample is loaded and a screenshot is saved. The snapshot test is flaky as the Facebook thumbs images might not load before the screenshot is taken. This is therefore recorded as a failing snapshot test.

Comparison: blank snapshot on the left, and proper snapshot on the right.
<img width="631" alt="testscrollviewexample_1-ios12 2x" src="https://user-images.githubusercontent.com/165856/53050067-51bd5700-344d-11e9-8278-eab4f83865c8.png">

The test is defined in JavaScript at `RNTester/js/ScrollViewExample.js`, and is invoked by `RNTesterSnapshotTests.m` in `RNTester/RNTester.xcodeproj`.

Potential solutions include delaying the recording of the snapshot long enough for images to have loaded, or simply replacing the images from ScrollViewExample with something else.

Steps to reproduce:
---

1. Run `yarn` at the repository root.
2. Open `RNTester/RNTester.xcodeproj` on Xcode 10.1.0.
3. Build RNTester.
4. Run tests (CMD+U) on an iPhone 6s simulator.

You can generate a new snapshot for comparison by editing `RNTesterSnapshotTests.m` and setting record mode to on.

**Comment by ericlewis** [comment]
I will take a look at this.

**Comment by ericlewis** [comment]
Updated in #23541, the solution was to remove the images and use a similar item style across all the examples.

**Comment by ericlewis** [comment]
@hramos we can close this now that #23541 was merged?
