### ISSUE TITLE
Upgrad vom 0.58.4 to "next" fails

### ISSUE THREAD

**Issue by filly82** [facebook/react-native#23532]
When trying to upgrade from 0.58.4 to the latest version with

`react-native-git-upgrade next`

i am getting the following error message

`git-upgrade ERR! An error occurred during upgrade:
git-upgrade ERR! Error: ENOENT: no such file or directory, stat 'D:\repositories\git\entwicklung\javascript\fapp_react_native\node_modules\react-native\local-cli\generator\copyProjectTemplateAndReplace.js'`

I've tried it several times, and found out that the above mentioned file is there before the upgrade but it's not while upgrading. I am guessting that the react-native@next package does not have it

any ideas how to upgrade to 0.59.0-rcX ?

**Comment by hramos** [comment]
`react-native-git-upgrade` has been removed from the project. Please use of the alternate upgrade methods listed at http://facebook.github.io/react-native/docs/upgrading

We'll also need to update the docs accordingly.
