### ISSUE TITLE
Centered TextInput clipped

### ISSUE THREAD

**Issue by Bardimaswift** [facebook/react-native#23549]
## 🐛 Bug Report
Focused and centered TextInput clipped on iOS when the height is greater than 54

## To Reproduce
Add centered TextInput (see example) and focus it on iOS.

## Expected Behavior
TextInput should be not clipped

## Code Example
https://snack.expo.io/@bardiaswift/centered-textinput-issue

## Environment
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
      Memory: 37.52 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.1 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 27.0.3, 28.0.2, 28.0.3
        System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-26 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.58.5 => 0.58.5 
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by JKCooper2** [comment]
Seems to be an issue relating to the height and fontsize, clipping occurs not just at that value, but seemingly any time you have the height a bit larger than the font size.

More minimal example:
https://snack.expo.io/@jkcooper/centered-textinput-issue

**Comment by michalchudziak** [comment]
NOTE: Issue is present only with the input being focused and keyboard open .
