### ISSUE TITLE
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory(). > Could not create service of type PluginResolutionStrategyInternal using BuildScopeServices.createPluginResolutionStrategy() Error In rect-native run-android

### ISSUE THREAD

**Issue by kamithL** [facebook/react-native#23554]
JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug)...

FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
> Could not create service of type PluginResolutionStrategyInternal using BuildScopeServices.createPluginResolutionStrategy().

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

Command failed: ./gradlew installDebug

Error: Command failed: ./gradlew installDebug
    at checkExecSyncError (child_process.js:616:11)
    at Object.execFileSync (child_process.js:634:13)
    at runOnAllDevices (/Users/imac2/TestPrinter/node_modules/react-native/local-cli/runAndroid/runAndroid.js:299:19)
    at buildAndRun (/Users/imac2/TestPrinter/node_modules/react-native/local-cli/runAndroid/runAndroid.js:135:12)
    at isPackagerRunning.then.result (/Users/imac2/TestPrinter/node_modules/react-native/local-cli/runAndroid/runAndroid.js:65:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by ThakurKarthik** [comment]
I have the same issue after removing the node_modules and running npm install again i can't use react-native run-android.

**Comment by ShmouG** [comment]
I am having the same issue, and I keep coming up to this resolution in stackoverflow: [https://stackoverflow.com/questions/30840526/gradle-could-not-create-service-of-type-initscripthandler-using-buildscopeservic](url)
But I don't know if I can change the gradle home variable on my Mac.

**Comment by clovisdasilvaneto** [comment]
hey guys, I was having the same error, but I solved it by changing my JAVA_HOME version, because I was using java 11, but for some reason android is not compatible with it and I change to java 8 and now it works :) 

If you do not know how to change your java version, follow this steps bellow:

1. Open your `.profile` file (if you don't have it created, you can create a new one, or use your .bash_profile)
2. Put the follow line: 
```
export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
```
3. Save and close it
4. In your terminal, you can put: `source ~/.profile`
5. Run `react-native run-android` again and it should works

**Comment by ShmouG** [comment]
Thanks @clovisdasilvaneto, this really helped me.
If anyone else is struggling with this, I found that you have to download java8 with homebrew as well.
Here's a link on how to do that: https://stackoverflow.com/questions/24342886/how-to-install-java-8-on-mac

**Comment by clovisdasilvaneto** [comment]
You're welcome! Happy in helping you :)

**Comment by AshDSh** [comment]
> I have the same issue after removing the node_modules and running npm install again i can't use react-native run-android.

Could you please elaborate on this ?

**Comment by AshDSh** [comment]
> hey guys, I was having the same error, but I solved it by changing my JAVA_HOME version, because I was using java 11, but for some reason android is not compatible with it and I change to java 8 and now it works :)
> 
> If you do not know how to change your java version, follow this steps bellow:
> 
> 1. Open your `.profile` file (if you don't have it created, you can create a new one, or use your .bash_profile)
> 2. Put the follow line:
> 
> ```
> export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
> ```
> 1. Save and close it
> 2. In your terminal, you can put: `source ~/.profile`
> 3. Run `react-native run-android` again and it should works

Could you please tell the steps do this in windows7

**Comment by shaktalles** [comment]
Ran on the same issue on linux, downgrading to java 8 solved.

**Comment by khanguslee** [comment]
Had the same issue. Android only works with Java 8, but since Java 8 isn't freely available anymore, you can't download it. You will need to download `adoptopenjdk8` to make it work from now on.
https://medium.com/solacedotcom/switching-to-adoptopenjdk-8d4a4aed16b8

**Comment by nandit123** [comment]
Hi, since i was using ubuntu. When i created a sample react-native project, the directory created could be edited only by sudo permissions. When i changed it to a normal directory (by copying it somewhere else) and ran react-native run-android, it worked now. 
Don't forget to setup your physical device for testing as mentioned here => https://facebook.github.io/react-native/docs/0.59/running-on-device
