### ISSUE TITLE
Packaging coffeescript

### ISSUE THREAD

**Issue by eyaleizenberg** [facebook/react-native#2355]
Hi,
Sorry that I am posting this here but I couldn't find an answer elsewhere:
1. Is it possible to compile coffeescript using the packager? 
2. If yes, can please give a step by step on how to do this? 
3. If not and I still want to use coffeescript, what is the recommended method of preparing the files for the packager? Should I just use grunt/gulp to compile and throw it all in 1 file? Should it be in separate files? 
4. If I throw it all in one file and I hit an error, will I see which module the error occurred from like it does when just using normal js or will I just see that it happened in the ios.js.bundle ?

Thanks a lot. :)

**Comment by browniefed** [comment]
Seems like this has already been solved here https://github.com/diegodurli/ReactNativeCoffee
@brentvatne solved by external repo
