### ISSUE TITLE
FacebookSDKStrings.bundle problem

### ISSUE THREAD

**Issue by weihuali0509** [facebook/react-native#23567]
I tried to submit the binary to App Store Connect and got the following error message back from Apple - 

> Dear Developer,
> 
> We identified one or more issues with a recent delivery for your app, "XXX". Please correct the following issues, then upload again.
> 
> This bundle is invalid - The Info.plist file for /Payload/xxx.app/FacebookSDKStrings.bundle is missing or could not be read.
> 
> Invalid Bundle - The bundle at '/Payload/xxx.app/FacebookSDKStrings.bundle' does not contain a bundle executable.
> 
> Best regards,
> 
> The App Store Team

Does anyone also experience this problem?

**Comment by HerbertLim** [comment]
This issue happens to me, too. 
I was able to submit to TestFlight until yesterday evening. This morning, I changed some codes and built with expo, and then submitted to AppStore, but failed with the same error.
I tried three times but all failed, and received same emails.

![19-02-21_invalid build appstore](https://user-images.githubusercontent.com/22055241/53147284-6f73f300-35ea-11e9-8851-ff3954cc89ca.jpg)
Note: time is in Korean Time, KST, +9

**Comment by jingping2015** [comment]
I think this should be some issue from apple and it should be fix now.

**Comment by nguyenngocnhan90** [comment]
I did submit app again without any changes an hour ago, and Apple approved my build

**Comment by raul-madrigal** [comment]
I'm facing the same issue, I ejected to expokit but Apple keeps rejecting my build uploads with the same error. Anyone with any lead?
<img width="679" alt="screen shot 2019-02-21 at 10 44 30 am" src="https://user-images.githubusercontent.com/30184031/53186145-07131a80-35c6-11e9-8adc-d36160146cdf.png">

**Comment by weihuali0509** [comment]
Confirmed - it is working as this morning :)
