### ISSUE TITLE
java.lang.RuntimeException: 

### ISSUE THREAD

**Issue by joaodematejr** [facebook/react-native#23579]
java.lang.RuntimeException: 

## To Reproduce

application closing all the time

https://ibb.co/QkD6nzF

Samsung Galaxy J7 (j7elte), Android 6.0
Relatório 1 de 1
java.lang.RuntimeException: 
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:3681)
  at android.app.ActivityThread.access$2000 (ActivityThread.java:229)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1903)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:148)
  at android.app.ActivityThread.main (ActivityThread.java:7325)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1230)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1120)
Caused by: java.lang.ClassNotFoundException: 
  at dalvik.system.BaseDexClassLoader.findClass (BaseDexClassLoader.java:56)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:511)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:469)
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:3676)

## Environment

React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
      Memory: 457.96 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.7.0 - ~/.nvm/versions/node/v10.15.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 22, 23, 25, 26, 27, 28
        Build Tools: 22.0.1, 23.0.1, 25.0.0, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.3
        System Images: android-24 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.2 => 16.8.2 
      react-native: 0.58.5 => 0.58.5 
    npmGlobalPackages:
      react-native-git-upgrade: 0.2.7

**Comment by hramos** [comment]
Tracking down individual crashes is out of scope for this issue tracker, unless you have a minimal reproduction case.

**Comment by joaodematejr** [comment]
the problem is presented in samsung models, tested on 3 different android versions 6.0, 7.0 and 8.0.

https://ibb.co/ZfdLHBW
https://ibb.co/myRfYhM
https://ibb.co/Mgwm0rb

**Comment by hramos** [comment]
What I am trying to say is that without a sample of code that can reliably reproduce these crashes, it's unlikely we will be able to help. 

There's something that stands out from your configuration, though. You're using React 16.8.2 with React Native 0.58.5. That version of React Native should be using React 16.6.3. We're not even using 16.8.2 yet in master, as I'm in the process of upgrading us from 16.8.1. to 16.8.3 in time for the 0.59 release.

**Comment by joaodematejr** [comment]
I do not know if it gets to be in any specific part of the code because the application hangs on different screens, often when it will start the application hangs, after 2 minutes it locks the times when it is browsing between screens hangs, it does not have a specific part that hangs , but by the way I can post some part of the code.

**Comment by hramos** [comment]
If you can narrow this down to a sample code that triggers the crash, that would be helpful.

**Comment by joaodematejr** [comment]
import React, { Component } from 'react';
import { Text, View, TouchableOpacity, StyleSheet, Platform } from 'react-native';
import { FlatGrid } from 'react-native-super-grid';
import Icon from 'react-native-vector-icons/MaterialIcons';

export default class SolicitarApoio extends Component {
    render() {
        return (
            <View style={{ flex: 1 }}>
                <View style={{ flex: 1 }} />
                <View style={{ flex: 2 }}>
                    <FlatGrid
                        itemDimension={320}
                        items={[
                            <TouchableOpacity onPress={() => { alert('ooi') }} style={styles.btnVermelho}>
                                <Icon size={90} name="add-alert" style={styles.btnIcon} />
                                <Text style={styles.btnTexto}>Solicitar Apoio</Text>
                            </TouchableOpacity>
                        ]}
                        renderItem={({ item }) => (<TouchableOpacity>{item}</TouchableOpacity>)}
                    />
                </View>
                <View style={{ flex: 1 }} />
            </View>
        );
    }
}

const styles = StyleSheet.create({
    btnVermelho: {
        backgroundColor: '#d32f2f',
        justifyContent: 'flex-end',
        borderRadius: 5,
        padding: 10,
        height: 150,
    },
    btnIcon: {
        color: '#ffffff',
        justifyContent: 'center',
        textAlign: 'center'
    },
    btnTexto: {
        color: '#FFF',
        fontWeight: '100',
        fontFamily: Platform.OS === 'android' ? 'sans-serif-light' : undefined,
    },
});

**Comment by joaodematejr** [comment]
`import _ from 'lodash';
import React, { Component } from 'react';
import { AsyncStorage, Platform, StatusBar, Text, TouchableOpacity, View, Image } from 'react-native';
import { GiftedChat } from 'react-native-gifted-chat';
import { Toolbar } from "react-native-material-ui";
import OneSignal from 'react-native-onesignal';
import { Button, DefaultTheme, Dialog, Paragraph, Portal, Provider as PaperProvider } from 'react-native-paper';
import { Actions } from 'react-native-router-flux';
import Icon from 'react-native-vector-icons/MaterialIcons';
import { connect } from "react-redux";
import { enviarMensagem, receberMensagem, removerMensagens } from "../actions/ChatUsuarioActions";
import CustomActions from './CustomActions';
import CustomView from './CustomView';

var Datastore = require('react-native-local-mongodb')
db = new Datastore({ filename: 'bd_agente_chat', autoload: true });

const theme = {
    ...DefaultTheme,
    roundness: 2,
    colors: {
        ...DefaultTheme.colors,
        primary: '#3C4252',
        accent: '#3C4252',
    }
};

class ChatAgente extends Component {
    state = {
        visible: false,
    };
    constructor(props) {
        super(props);
        this.renderCustomActions = this.renderCustomActions.bind(this);
        this.chatComponente = this.chatComponente.bind(this);
    }

    componentWillMount() {
        this.carregarDadosUsuario();
        this._receberMensagem();
        this.carregarMensagemLocalmente();
        OneSignal.inFocusDisplaying(1);
        OneSignal.addEventListener('received', this.onReceived);
        OneSignal.addEventListener('opened', this.onOpened);
        OneSignal.configure();
    }

    onOpened(openResult) {
        console.log('Message: ', openResult.notification.payload.body);
        console.log('Data: ', openResult.notification.payload.additionalData);
        console.log('isActive: ', openResult.notification.isAppInFocus);
        console.log('openResult: ', openResult);
    }

    async carregarDadosUsuario() {
        const usuarioLogado = await AsyncStorage.getItem('usuarioLogado');
        this.setState({ usuarioLogado: JSON.parse(usuarioLogado) })
    }

    componentWillReceiveProps(nextProps) {
        this.criaFonteDeDados(nextProps.conversas);
    }


    criaFonteDeDados(conversas) {
        mensagens = [];
        conversas.forEach(element => {
            mensagens.push(element.message);
        });
        var ultimo = mensagens.pop();

        if (ultimo !== undefined) this.tratarMensagenFirebase(ultimo);

    }

    tratarMensagenFirebase(ultimo) {
        ultimo.createdAt = new Date();
        ultimo.user.avatar = 'https://http2.mlstatic.com/moreno-do-whatsapp-chinelo-D_NQ_NP_464215-MLB25169409203_112016-F.jpg';
        this.chatComponente(ultimo);
        this.salvarMensagemLocalmente(ultimo);
    }

    async enviar(messages = []) {
        const { id, playerId } = this.props;
        const usuarioLogado = await AsyncStorage.getItem('usuarioLogado');
        let idRemetente = JSON.parse(usuarioLogado).user._id;
        let idDestinatário = id;
        messages[0].createdAt = new Date();
        messages.forEach(message => { this.props.enviarMensagem(idRemetente, idDestinatário, message) });
        this.chatComponente(messages);
        this.salvarMensagemLocalmente(messages);
        // this.enviarNotificacao(playerId);
    }


    async _receberMensagem() {
        const usuarioLogado = await AsyncStorage.getItem('usuarioLogado');
        const { id } = this.props;
        let idDestinatário = id;
        let idRemetente = JSON.parse(usuarioLogado).user._id;
        this.props.receberMensagem(idRemetente, idDestinatário);
    }

    async componentWillUnmount() {
        const usuarioLogado = await AsyncStorage.getItem('usuarioLogado');
        const { id } = this.props;
        let idDestinatário = id;
        let idRemetente = JSON.parse(usuarioLogado).user._id;
        this.props.removerMensagens(idRemetente, idDestinatário);
    }

    chatComponente(messages) {
        this.setState((previousState) => {
            return {
                messages: GiftedChat.append(previousState.messages, messages),
                loadEarlier: true,
                isLoadingEarlier: true,
            };
        });
    }
    salvarMensagemLocalmente(messages) {
        const { id } = this.props;
        var conversas = { messages, id };
        db.insert(conversas, function (err, conversas) { });
    }
    deletarMensagemLocalmente() {
        const { id } = this.props;
        db.remove({ id: id }, { multi: true }, function () { });
        Actions.pop();
    }

    async carregarMensagemLocalmente() {
        const { id } = this.props;
        var mensagens = await db.find({ id: id }).sort({ 'messages.createdAt': 1 }).exec()
            .then(
                function (messages) {
                    return messages
                },
                function (err) {
                    return err
                }
            )
        this.percorrerMensagens(mensagens);
    }
    percorrerMensagens(mensagens) {
        for (let index = 0; index < mensagens.length; index++) {
            const element = mensagens[index];
            this.chatComponente(element.messages)
        }
    }

    _showDialog = () => this.setState({ visible: true });
    _hideDialog = () => this.setState({ visible: false });

    enviarNotificacao(playerId) {
        const dados = {
            'tipoClinete ': 'COMUM'
        }
        const contents = {
            'en': 'Conteudo da notificacao'
        }
        const parametrosRestantes = {
            headings: { en: 'Notificacao' },
            small_icon: 'ic_stat_onesignal_default',
            large_icon: 'https://http2.mlstatic.com/moreno-do-whatsapp-chinelo-D_NQ_NP_464215-MLB25169409203_112016-F.jpg',

        };
        OneSignal.postNotification(contents, dados, playerId, parametrosRestantes);
    }

    render() {
        const { id, email, nome, role, playerId } = this.props;
        var user = { _id: id };
        return (
            <PaperProvider theme={theme}>
                <View style={{ flex: 1, elevation: 0 /* <= NÃO TIRAR ESSE DEMONIO */ }}>
                    <StatusBar backgroundColor="#3C4252" />
                    <Portal>
                        <Dialog
                            visible={this.state.visible}
                            onDismiss={this._hideDialog}>
                            <Dialog.Title>Aviso !!!</Dialog.Title>
                            <Dialog.Content>
                                <Paragraph>Deseja excluir todas as conversas do {nome} salvas nesse aparalho.</Paragraph>
                            </Dialog.Content>
                            <Dialog.Actions>
                                <View style={{ flexDirection: 'row' }}>
                                    <View>
                                        <Button onPress={() => this.deletarMensagemLocalmente()}>Excluir</Button>
                                    </View>
                                    <View>
                                        <Button onPress={this._hideDialog}>Cancelar</Button>
                                    </View>
                                </View>
                            </Dialog.Actions>
                        </Dialog>
                    </Portal>
                    <Toolbar
                        centerElement={
                            <View style={{ flex: 1, flexDirection: 'row', justifyContent: 'space-between' }}>
                                <View style={{ justifyContent: 'center', alignContent: 'center' }} >
                                    <Image style={{ width: 35, height: 35, borderRadius: 30, marginRight: '6%' }} small source={{ uri: 'https://facebook.github.io/react-native/docs/assets/favicon.png' }} />
                                </View>
                                <View style={{ justifyContent: 'center', alignContent: 'center' }} >
                                    <Text style={{ color: '#FFF', fontWeight: '100', fontFamily: Platform.OS === 'android' ? 'sans-serif-light' : undefined }}>{email}</Text>
                                    <Text style={{ color: '#FFF', fontWeight: '100', fontFamily: Platform.OS === 'android' ? 'sans-serif-light' : undefined }}>{role}</Text>
                                </View>
                                <View style={{ marginTop: '1%', marginBottom: '1%', width: 50, height: 50 }} >
                                </View>
                            </View>
                        }
                        searchable={{
                            autoFocus: true,
                            placeholder: 'Pesquisar...',
                            onChangeText: value => this.setState({ searchText: value }),
                            onSearchClosed: () => this.setState({ searchText: '' }),
                        }}
                        style={{ container: { backgroundColor: "#3C4252" } }}
                        rightElement={
                            <View style={{ justifyContent: 'center', alignItems: 'center', flexDirection: 'row' }}>
                                <View>
                                    <TouchableOpacity onAccessibilityTap='Acessar Perfil' onPress={() => false}>
                                        <Icon size={25} name="person" style={{
                                            color: '#ffffff',
                                            justifyContent: 'center',
                                            textAlign: 'center',
                                            margin: 12
                                        }} />
                                    </TouchableOpacity>
                                </View>
                                <View>
                                    <TouchableOpacity onAccessibilityTap='Deletar Mensagens' onPress={this._showDialog}>
                                        <Icon size={25} name="delete" style={{
                                            color: '#ffffff',
                                            justifyContent: 'center',
                                            textAlign: 'center'
                                        }} />
                                    </TouchableOpacity>
                                </View>
                            </View>
                        }
                    />
                    <GiftedChat
                        messages={this.state.messages}
                        onSend={messages => this.enviar(messages)}
                        isLoadingEarlier={true}
                        isAnimated={true}
                        locale='pt-br'
                        user={user}
                        showUserAvatar={false}
                        showAvatarForEveryMessage={true}
                        loadEarlier={false}
                        placeholder={"Digite aqui..."}
                        renderCustomView={this.renderCustomView}
                        renderActions={this.renderCustomActions}
                    />
                </View>
            </PaperProvider>
        );
    }
    pushNotificacaoPersonalizado(messages) {
        console.log('messages', messages);
        alert('notificacao');
    }
    renderCustomView(props) {
        return (
            <CustomView
                {...props}
            />
        );
    }

    renderCustomActions(props) {
        if (Platform.OS === 'ios') {
            return (
                <CustomActions
                    {...props}
                />
            );
        }
        return (
            <CustomActions
                {...props}
            />
        );
    }
}


mapStateToProps = state => {
    const conversas = _.map(state.ChatUsuarioReducer, (val, uid) => {
        return { ...val, uid };
    });

    return {
        conversas
    }

}

export default connect(mapStateToProps, { enviarMensagem, receberMensagem, removerMensagens })(ChatAgente);`

**Comment by joaodematejr** [comment]
import React, { Component } from "react";
import { ActivityIndicator, Image, Platform, Text, View } from "react-native";
import { Button, TextInput } from "react-native-paper";
import { connect } from "react-redux";
import { autenticarUsuario, modificaEmail, modificaSenha } from "../actions/AutenticacaoActions";

class Login extends Component {
  constructor(properties) {
    super(properties);
  }
  componentWillMount() {
    /*  OneSignal.init("42767e58-d8f6-4887-95ce-47dd94943539");
     OneSignal.configure();
     OneSignal.addEventListener('ids', this.onIds = this.onIds.bind(this)); */
  }
  //PLAYER ID ONE
  /* onIds(device) {
    const playerId = device.userId;
    this.setState({ playerId })
  } */

  _autenticarUsuario() {
    const { email, senha } = this.props;
    const { playerId } = 'playerIdDesativado';
    this.props.autenticarUsuario(email, senha, playerId);
  }

  renderBtnAcessar() {
    if (this.props.loading_login) {
      return <ActivityIndicator size="small" color="#FFF" />;
    }
    return (
      <Button accessible={true} accessibilityLabel="Acessar Sistema" onPress={() => this._autenticarUsuario()} style={{ backgroundColor: "#4CAF50" }} dark={true} icon="security" mode="contained"    >
        Acessar
      </Button>
    );
  }
  render() {
    return (
      <View style={{ flex: 1, backgroundColor: '#3C4252' }} >
        <View style={{ marginBottom: '5%', marginTop: '1%', flex: 1, backgroundColor: '#3C4252', justifyContent: 'flex-end', alignItems: "center" }} >
          <Image style={{ width: 100, height: 100 }} source={require("../imagens/logo_gesec.png")} />
        </View>
        <View style={{ flex: 2, margin: '2%', justifyContent: 'center' }} >
          <View style={{ justifyContent: 'center', alignItems: "center" }}>
            <Text style={{ fontSize: 18, color: "#d32f2f", fontWeight: "200", fontFamily: Platform.OS === "android" ? "sans-serif-light" : undefined }}   >
              {this.props.erroLogin}
            </Text>
          </View>
          <TextInput theme={{ colors: { placeholder: '#303030', background: '#FFF', text: '#303030', primary: '#3C4252' } }} placeholder='Email' accessible={true} accessibilityLabel="Email" style={{ marginTop: '2%', marginBottom: '2%' }} onChangeText={texto => this.props.modificaEmail(texto)} value={this.props.email} />
          <TextInput theme={{ colors: { placeholder: '#303030', background: '#FFF', text: '#303030', primary: '#3C4252' } }} placeholder='Senha' accessible={true} accessibilityLabel="Senha" style={{ marginTop: '2%', marginBottom: '2%' }} onChangeText={texto => this.props.modificaSenha(texto)} value={this.props.senha} secureTextEntry={true} />
          <View style={{ marginTop: '5%' }} >
            {this.renderBtnAcessar()}
          </View>
        </View>
        <View style={{ marginBottom: '5%', flex: 1, justifyContent: 'flex-end', alignItems: "center" }} >
          <Text accessible={true} accessibilityLabel="Desenvolvido por Gesec" style={{ color: "#fff", fontWeight: "200", fontFamily: Platform.OS === "android" ? "sans-serif-light" : undefined }}>
            Desenvolvido por Gesec </Text>
        </View>
      </View>
    );
  }
}

const mapStateToProps = state => ({
  email: state.AutenticacaoReducer.email,
  senha: state.AutenticacaoReducer.senha,
  erroLogin: state.AutenticacaoReducer.erroLogin,
  loading_login: state.AutenticacaoReducer.loading_login
});

export default connect(mapStateToProps, { modificaEmail, modificaSenha, autenticarUsuario })(Login);

**Comment by joaodematejr** [comment]
These are some screens that show in-app locking if you need any more information or code.

**Comment by hramos** [comment]
The code you provided is not something anyone can drop into a new RN app and easily reproduce the crash you're reporting. Like I said, assisting with crashes in individual apps is not something we can do in this issue tracker. I think it's best if you spend some more time troubleshooting this in your own project, then come back when you have a minimal code example that can trigger the crash.

**Comment by joaodematejr** [comment]
Okay thanks for the attention, I see if I can remove some dependencies to try to find out what's happening with the application.

**Comment by joaodematejr** [comment]
problems that were causing the crash

  "react-redux": "5.1.1",
   "redux": "4.0.0",
   "redux-thunk": "2.2.0",
