### ISSUE TITLE
[RN v0.59.0-rc.2] Live Reload does work

### ISSUE THREAD

**Issue by ltcaosj** [facebook/react-native#23589]
## 🐛 Bug Report
**Live Reload  feature does not work**, it seems that there is an issue related to networking.
## To Reproduce
1. create branch new react-native app by running: react-native init RN059 --version react-native@next
2. Run iOS project with simulator or a real device.
3. Turn on Live Reload (Cannot find the menu when running on real device)
4. Make a code change, save --> nothing happen, **the app does not reload.**

## Expected Behavior
The running app need to reload with latest code.

## More info
If I run the react-native start with this command --> the Live Reload works:
react-native start **--host 0.0.0.0**

## Environment
info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
      Memory: 1000.23 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 22, 27, 28
        Build Tools: 23.0.3, 24.0.3, 25.0.3, 26.0.3, 27.0.3, 28.0.3
        System Images: android-22 | Google APIs Intel x86 Atom, android-24 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-27 | Intel x86 Atom, android-27 | Intel x86 Atom_64, android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.1 => 16.8.1 
      react-native: 0.59.0-rc.2 => 0.59.0-rc.2 
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by thymikee** [comment]
@cpojer can you transfer this issue to https://github.com/react-native-community/react-native-cli?

**Comment by cpojer** [comment]
This issue has been moved to react-native-community/react-native-cli#187.
