### ISSUE TITLE
opacity issues when `Text` is laid over `SliderIOS`

### ISSUE THREAD

**Issue by agentS** [facebook/react-native#2358]
Hi,

I'm currently developing a custom component inspired by iOS' slide to unlock functionality (the module is named [react-native-slider-button](https://github.com/agentS/react-native-slider-button)). However, when the `Text` component is laid over the slider there is an issue with the `Text`'s opacity causing the opacity to look less bright. If I turn the `SliderIOS`' opacity to 1.0 the `Text` becomes invisible. When I hide the slider by setting its opacity to 0 the text uses as demanded.

This behaviour can be tested by using the [following sample project](https://github.com/agentS/reactNativeSliderButtonDemo).

The opacity definition is located in the following file: `node_modules/react-native-slider-button/SliderButtonStyleConstant.js`. Being capable to have opacity of both the slider and the label (at the "top" of the animation of course) is my goal.

This problem might be related to the [issue 2148](https://github.com/facebook/react-native/issues/2148).

I appreciate any help. Thanks in advance!

**Comment by brentvatne** [comment]
@agentS - @ide's solution in https://github.com/facebook/react-native/issues/2148#issuecomment-135950957 should work for you here :smile: - let me know if not in Slack (@brentvatne)
