### ISSUE TITLE
Could not find source file at /Examples

### ISSUE THREAD

**Issue by grantpowell** [facebook/react-native#2359]
XCode cannot run UIExplorer examples.  Saying there is a missing file.  Here is the exact message:

Could not find source file at Examples/UIExplorer/UIExplorerApp.ios.js

![screen shot 2015-08-17 at 8 43 58 am](https://cloud.githubusercontent.com/assets/957580/9305068/20d285ae-44bc-11e5-86ac-b8bb367975a6.png)

**Comment by grantpowell** [comment]
Terminal error details: 

{ [NotFoundError: Could not find source file at Examples/UIExplorer/UIExplorerApp.ios.js]
  message: 'Could not find source file at Examples/UIExplorer/UIExplorerApp.ios.js',
  name: 'NotFoundError',
  type: 'NotFoundError',
  status: 404,
  errors: 
   [ { description: undefined,
       filename: undefined,
       lineNumber: undefined } ] }
[08:43:46] <START> request:/Examples/UIExplorer/UIExplorerApp.ios.includeRequire.runModule.bundle?dev=true
::1 - - [Mon, 17 Aug 2015 12:50:24 GMT] "GET / HTTP/1.1" 404 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.155 Safari/537.36"
[08:50:40] <START> request:/index.ios.bundle
[08:50:40] <END>   request:/index.ios.bundle (12ms)

**Comment by geirman** [comment]
which version are you using? 
did you try `npm install` in the Examples/UIExplorer/ directory?

**Comment by robtg4** [comment]
Same issue here

![screen shot 2015-09-03 at 3 23 21 am](https://cloud.githubusercontent.com/assets/13613075/9652621/258d6636-51eb-11e5-9c96-a4440330d74c.png)

**Comment by daniel** [comment]
I have the same issue with all examples. Running `npm install` didn't help.

**Comment by aj9045** [comment]
I have the same issue with the same error.  I've tried npm install in Examples/UIExplorer, but it didn't help.

**Comment by robtg4** [comment]
@daniel  @aj9045 @grantpowell I had to shut down xcode and restart my computer then it ran fine - odd though

**Comment by JasonZ321** [comment]
same issue happened when trying to run Movies

**Comment by daniel** [comment]
@robtg4 Thanks, that solved my problem too! It was maybe the React Packager that had to be restarted.

**Comment by daniel** [comment]
Now I had to same problem with the Movies example.

![screen shot 2015-09-07 at 12 48 45](https://cloud.githubusercontent.com/assets/635/9715306/5073a53c-555f-11e5-92e4-e6065d9dd2fd.png)

Restarting Xcode or React Packager didn't help. All other examples I tried, UIExplorer and 2048 worked though.

I noted that it searched for "MoviesApp.js", but the file is called "MoviesApp.ios.js", so I tried renaming the file to "MoviesApp.js" and that fixed the problem. I have managed to start the Movies example before without renaming the file before though.

**Comment by brentvatne** [comment]
I just confirmed that this is currently working on master, so if this was an issue it has been fixed :v: 

If it persists for you on master, make sure you're running `npm start` from the root `react-native` directory, not from `/Examples/*` :smile:
