### ISSUE TITLE
Style switch accessibility labels on iOS

### ISSUE THREAD

**Issue by jochemjanssens** [facebook/react-native#23596]
## 🐛 Bug Report
  It isn't possible to style the accessibility label inside a switch on iOS

## To Reproduce
- Place a switch inside a react-native project
- Set on/off labels inside iOS settings General-Accessibility-on/off labels

## Expected Behavior
Change the color of the accessibility label inside a switch on iOS

## Code Example
<Switch
	value={item.enabled}
	trackColor={{
		true: "rgb(151, 233, 42)",
		false: "rgb(233, 236, 239)",
	}}
	onValueChange={() => this.onToggleSwitch()}
/>

## Environment
  React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
      Memory: 49.72 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.7.0 - ~/.nvm/versions/node/v8.12.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 26, 27, 28
        Build Tools: 26.0.3, 27.0.3, 28.0.2, 28.0.3
        System Images: android-24 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.7.0 => 16.7.0 
      react-native: ^0.57.8 => 0.57.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by ericlewis** [comment]
On iOS the off tintColor is transparent (and doesn't seem overridable, tested on a native project), there is a property on Switch called `ios_backgroundColor` which effectively does the same thing, since the off state is transparent, the background color will show through. This will achieve what you want on iOS & android: 
```javascript
const falseColor =  "rgb(233, 236, 239)";
...
<Switch
    value={item.enabled}
    trackColor={{
        true: "rgb(151, 233, 42)",
        false: falseColor,
    }}
    ios_backgroundColor={falseColor}
    onValueChange={() => this.onToggleSwitch()}
/>
```

**Comment by jochemjanssens** [comment]
Thank you for the response, unfortunately this isn't a solution for the problem we have. Our goal is to change the black I into a white I, and this is still not possible with your fix

![screenshot 2019-02-26 at 10 14 30](https://user-images.githubusercontent.com/14986917/53401041-5767ef00-39af-11e9-9df9-2b53f60d938c.png)
