### ISSUE TITLE
[Android] Not able to download bundle using WiFi with RN 0.59.0-rc.2

### ISSUE THREAD

**Issue by Esemesek** [facebook/react-native#23605]
## 🐛 Bug Report

Not able to download javascript bundle through WiFi with `RN 0.59.0-rc.2` on Android phone. Additionally, initializing new project with `RN 0.58.5` and setting the same dev properties works.

![52551960_353813208825419_7213896807745585152_n](https://user-images.githubusercontent.com/9092510/53269666-c4e2f980-36e9-11e9-88c5-96bf39c38191.png)

## To Reproduce
1. Initialize new project
2. Install the app on physical android device
3. Open dev settings
4. Set debug server host and port to point to your local server
5. Refresh app

Not that you don't even have to disconnect your phone from the PC.

## Expected Behavior
The new bundle will be downloaded.

## Environment
```
React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
      Memory: 564.26 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.1 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.1 => 16.8.1
      react-native: 0.59.0-rc.2 => 0.59.0-rc.2
```

I think it might be `metro` issue. cc @rafeca

**Comment by hramos** [comment]
Is Metro running? Can you load the bundle by navigating to the url on the local development machine?

**Comment by Esemesek** [comment]
Bundler is running correctly, and I can download bundle by navigating to this URL. This is more of a communication issue between device and machine.

**Comment by dulmandakh** [comment]
please edit android/app/src/debug/res/xml/react_native_config.xml and add your IP address there. it's a new config for Android for apps that target API 28 and above. We'll update documentation soon.

**Comment by Polisas** [comment]
Same thing happens with IOS side, any ideas where to update IP adress ? Previously it was in Appdelegate.

**Comment by dulmandakh** [comment]
I'm closing this issue, please reopen if the issue still persists on Android.

**Comment by pedrolopes10** [comment]
@dulmandakh I've tried your suggestion but the issue still occurs.
