### ISSUE TITLE
zIndex is broken across ScrollViews

### ISSUE THREAD

**Issue by acb** [facebook/react-native#23614]
## 🐛 Bug Report
zIndex is broken when you have a ScrollView between your two different zIndexes.  For example, given code like

```
render() {
    return <View style={styles.background}>
        <View style={styles.redBox}></View>
        <View>
            <View style={styles.greenBox}></View>
        </View>
    </View>
}

let styles = StyleSheet.create({
    background: {
        backgroundColor: "blue",
        height: "100%"
    },
    greenBox: {
        backgroundColor: "green",
        width: 100,
        height: 100,
        zIndex: 2
    },
    redBox: {
        height: 300,
        width: 300,
        backgroundColor: "red",
        position: "absolute",
        top: 0,
        left: 0,
        zIndex: 1
    },
});
```
you get a view that makes sense, blue background, then red box, then green box on top.

<img src="https://user-images.githubusercontent.com/4690898/53291934-fa8aef80-3788-11e9-8d0c-669f6068a94d.png" width=300>

However, if you just switch the container of the green box to a ScrollView, the zIndex breaks:

```
<View style={styles.background}>
   <View style={styles.redBox}></View>
   <ScrollView>
        <View style={styles.greenBox}></View>
    </ScrollView>
</View>
```

<img src="https://user-images.githubusercontent.com/4690898/53291977-ae8c7a80-3789-11e9-91b2-2b0e916bcf4a.png" width=300>

## Expected Behavior
Components inside of a ScrollView should still respect zIndex.

## Code Example
```
import React, { Component } from 'react';
import {
    View,
    ScrollView,
    StyleSheet,
 } from 'react-native';

export default class App extends Component {
    render() {
        return (
            <View style={styles.background}>
                <View style={styles.redBox}></View>
                <ScrollView>
                    <View style={styles.greenBox}></View>
                </ScrollView>
            </View>
        );
    }
}

let styles = StyleSheet.create({
    background: {
        backgroundColor: "blue",
        height: "100%"
    },
    greenBox: {
        backgroundColor: "green",
        width: 100,
        height: 100,
        zIndex: 2
    },
    redBox: {
        height: 300,
        width: 300,
        backgroundColor: "red",
        position: "absolute",
        top: 0,
        left: 0,
        zIndex: 1
    },
});
```

## Environment
Environment:
  OS: Windows 10
  Node: 9.3.0
  Yarn: 1.3.2
  npm: 4.6.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338

Packages: (wanted => installed)
  react: 16.3.2 => 16.3.2
  react-native: ^0.55.4 => 0.55.4

It's worth noting that on iOS not even the working example I give here works, it doesn't show the green box above the red one ever.

**Comment by JKCooper2** [comment]
See https://github.com/facebook/react-native/issues/23615#issuecomment-466717338

**Comment by acb** [comment]
Yeah I think the fact that green renders on top at all is the bug, unfortunately...

**Comment by tmaly1980** [comment]
@acb Why did you close this? I'm experiencing this issue too.

**Comment by Monstrik** [comment]
I'm experiencing this issue too.

**Comment by acb** [comment]
@tmaly1980 I guess this can be re-opened -- it's pretty similar to https://github.com/facebook/react-native/issues/23615, which has a snack that's an easier reproduction.

Personally I gave up on doing what I was trying to do with z-index and found another approach so I haven't been following these cases at all.

**Comment by tmaly1980** [comment]
@acb I can't speak for others still experiencing this issue, but I was able to fix my issue by applying zIndex to both sibling and shared ancestor components.

**Comment by web-mobile0308** [comment]
@tmaly1980 
Hi, you told you was able to fix zindex issue between scrollviews.
How did you fix it? 
I am appreciate if you can help me.
Thanks

**Comment by Angular-Mast** [comment]
scrollview is not working for me too on android. it works on ios.

**Comment by aditya1711** [comment]
any fixes/ alternatives or workaround for this?

**Comment by aditya1711** [comment]
for me it works in in scrollView i provide in contentContainerStyle={{flex:1}}.

**Comment by StarDev0308** [comment]
@aditya1711 
HI, Thanks for your reply.
I am not sure you tested it in 2 different ScrollViews.
I am going to implement drag/drop between two scrollviews but one directional dragging item was hiden by alternative target scrollview.
Could you verify for my actions?

**Comment by aditya1711** [comment]
> @aditya1711
> HI, Thanks for your reply.
> I am not sure you tested it in 2 different ScrollViews.
> I am going to implement drag/drop between two scrollviews but one directional dragging item was hiden by alternative target scrollview.
> Could you verify for my actions?

I am unable to completely understand what you said, but I think you can have different flex values for both scroll views. But I doubt zIndex works as expected with siblings of different parents. Please try it out and let us know. I also will be prepare a better implementation of my functionality if that works.

**Comment by fabriziobertoglio1987** [comment]
```javascript
<ScrollView style={{ zIndex: 3}} />
```
can you close? 

https://snack.expo.io/@fabrizio.bertoglio/supportive-graham-crackers

**Comment by StarDev0308** [comment]
@fabriziobertoglio1987
Hey, you tested it in only one scrollview.
I mean drag/drop between two scrollviews.

**Comment by wanxue0804** [comment]
RN 0.62.2 
also having this issue , Any solution for this issue?

**Comment by Developeranees** [comment]
same issue

**Comment by srikargunnam** [comment]
Scrollview with zIndex, and position absolute works someitmes and fails sometimes, still facing this issue.

**Comment by shanutthankachan** [comment]
same issue
