### ISSUE TITLE
Unexpected icon error message in TabBarItemIOS

### ISSUE THREAD

**Issue by mcgaffin** [facebook/react-native#2361]
I have a TabBar item that's defined like this:

```html
<TabBarIOS.Item
    title='Projects'
    icon={ require('image!projects-32' ) }
  <Main style={styles.tab} />
</TabBarIOS.Item>
```

When I run this, the icon appears in the TabBar as hoped, but I also see this error message in the Chrome debug console:

```
Warning: Failed propType: Invalid prop `icon` of type `string` supplied to `RCTTabBarItem`, expected `object`. Check the render method of `TabBarItemIOS`.
```

I took a look at `TabBarItemIOS.ios.js` and found that if I changed [line 111](https://github.com/facebook/react-native/blob/master/Libraries/Components/TabBarIOS/TabBarItemIOS.ios.js#L111) from this:
```
    var icon = this.props.systemIcon || (
       this.props.icon && this.props.icon.uri
     );
```
to this:
```
    var icon = this.props.systemIcon || this.props.icon;
```
then the error message disappears and the icon still appears. I noticed in the debugger that the expression:
```
this.props.icon && this.props.icon.uri
```
evaluates to `"projects-32"`, when it seems that `TabBarItemIOS` is really expecting to get the full object in `this.props.icon`

Is this expected? I haven't seen anyone else mentioning this error message, so I wonder if there's something up with my implementation.

Thanks.

**Comment by ranyefet** [comment]
I also have the same issue. I'm passing an object to icon property and still get this warning.
I'm using v0.9.0

**Comment by twelvearrays** [comment]
I also am experiencing the same issue. v.0.9.0

**Comment by aj9045** [comment]
I'm getting the same warning message with v0.9.0 as well.

**Comment by justinmakaila** [comment]
Seeing this on `0.10.0-rc`

**Comment by brentvatne** [comment]
Should be fixed in 0.11-rc! Ping if not and I'll reopen

**Comment by chris-erickson** [comment]
I'm seeing this on `0.11.4`.  Happens with just a simple `TabBarIOS` with this single tab (or more):

```jsx
<TabBarIOS.Item
    title='Lists'
    systemIcon="most-viewed"
    selected={this.state.selectedTab === 'lists'}
    onPress={() => {
        this.setState({
            selectedTab: 'lists',
        });
    }}>
    <Text>This is the view</Text>
</TabBarIOS.Item>
```
Doesn't seem to cause any real issue, though.

**Comment by jasonmerino** [comment]
I'm getting this message in `0.12.0` for this `TabBarIOS.Item`:

```
<TabBarIOS.Item
	systemIcon="more"
	selected={this.state.selectedTab === 'more'}
	onPress={() => {
		this.onTabPress('more', 'moreNavigator');
	}}
>
	<Navigator
		initialRoute={{
			component: MoreComponent,
			title: "More"
		}}
		ref="moreNavigator"
		renderScene={(route, navigator) => {
			if (route.component) {
				var props = Object.assign({}, route.passProps || {}, {
					navigator,
					topNavigator: this.props.topNavigator
				});
				return (<route.component {...props} />);
			}
		}}
		navigationBar={NavigatorBar}
	/>
</TabBarIOS.Item>
```

When I remove the `systemIcon="more"` line the error disappears.

**Comment by Sidnicious** [comment]
I'm also seeing this in 0.12.0.

**Comment by cancan101** [comment]
I am seeing this issue in `0.14.0` with:
```jsx
                <TabBarIOS.Item
                    title="More"
                    systemIcon={'more'}
                    selected={this.state.selectedTab === 'moreTab'}
                    onPress={() =>{
                            this.setState({selectedTab: 'moreTab'});
                        }}
                    style={{flex:1, }}
                    >
                    <MoreTab />
                </TabBarIOS.Item>
```

**Comment by hasen6** [comment]
I'm seeing it as well on 0.14.2 with systemICon

**Comment by jasonmerino** [comment]
With 0.16.0-rc this has become more of a nuisance because the warning now shows in a yellow box that covers over the tab bar, so if you want to navigate around the app via the tab bar you need to tap the warning and then tap the dismiss button.

https://dl2.pushbulletusercontent.com/3dkhmkimLNcQcenxCCJZx3DaWBds570r/IMG_5408.PNG

**Comment by christopherdro** [comment]
@jasonmerino This should now be fixed with the following PR.

**Comment by jasonmerino** [comment]
Awesome. :) @christopherdro++
