### ISSUE TITLE
Illegal node ID set as an input for Animated.DiffClamp node

### ISSUE THREAD

**Issue by Elijen** [facebook/react-native#23620]
## 🐛 Bug Report
Issue reported in #11317 seems to be still occasionally happening:
<img width="359" alt="screen shot 2019-02-24 at 13 28 01" src="https://user-images.githubusercontent.com/1304054/53299487-48f8c680-383b-11e9-8182-b20843cad147.png">

## To Reproduce
I cannot actually find a reliable way to reproduce - happens maybe once in 20 executions.

## Expected Behavior
Error does not appear.

## Code Example
```
// this.offsetY is an instance of Animated.Value
// maxOffset is an integer
const translateY = Animated.multiply(Animated.diffClamp(this._offsetY, 0, maxOffset), -1);
```

## Environment
  React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
      Memory: 859.86 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.3.0 - ~/.nvm/versions/node/v8.3.0/bin/node
      npm: 6.4.1 - ~/.nvm/versions/node/v8.3.0/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
      Android SDK:
        Build Tools: 26.0.1
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1

**Comment by UchihaVeha** [comment]
Same issue

**Comment by Elijen** [comment]
No, unfortunately issues don't fix themselves alone, Mr. Robot.
