### ISSUE TITLE
Issues with inverted props on VirtualizedList

### ISSUE THREAD

**Issue by Sharcoux** [facebook/react-native#23635]
The way the current `VirtualizedList` inverts the elements order is really hacky and generate a lot of troubles, especially when combined with `onEndReached` events.

You can see the problem [here](https://github.com/necolas/react-native-web/issues/1254) for instance. Sandbox can be found [here](https://codesandbox.io/s/p5373vlm).

I propose a [much simpler and efficient way](https://github.com/facebook/react-native/pull/23632). But I need some help to complete it. I could test my changes by editing the built file inside the node_modules of the sandboxed project provided above, but I don't know how to build the changes I made in my PR and import them to use them in a sample project...

I'm not sure what should be expected from the "Test Plan" part of the PR.

About the snapshot tests that obviously would fail, should I update them myself?

Tell me what you think.

**Comment by hramos** [comment]
You can update snapshots if the difference makes sense (it's directly related to your PR). For a test plan, we'd like to hear how you went about testing your changes, did you consider any edge cases, and so on.

**Comment by hramos** [comment]
Since there's already some discussion on your PR, I think we can close this to avoid duplicate threads.
