### ISSUE TITLE
Paste option is not working in multiline text input  

### ISSUE THREAD

**Issue by jahicDario** [facebook/react-native#23653]
## 🐛 Bug Report
 Paste option is not working on TextInput with multiline flag set to true. 

## To Reproduce
  Create TextInput with multiline flag.

## Expected Behavior
  Expected to show the paste option on long press on field.

## Code Example
<TextInput multiline style={styles.input} placeholder={"Your Message"} />

## Environment

  React Native Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 16.04.5 LTS (Xenial Xerus)
      CPU: (4) x64 Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
      Memory: 132.78 MB / 7.66 GB
      Shell: 4.3.48 - /bin/bash
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.57.8 => 0.57.8 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1

**Comment by hramos** [comment]
Which devices did you try this on?

**Comment by jahicDario** [comment]
I tried on Samsung s9+.

**Comment by hramos** [comment]
Did you verify the paste option only fails to show up only if multiline is set to true?

**Comment by jahicDario** [comment]
Yes, everything works fine when the multiline is not set to true for TextInput field.

**Comment by jahicDario** [comment]
I updated environment info, please reopen the issue.

**Comment by sdkitono** [comment]
I am using Redmi 6 with android version 8.1.0 It does not allow pasting as well when multiline is set to true

**Comment by diegolmello** [comment]
For me it doesn't work even when multiline is set to false.
iOS works fine with both multiline options.

RN: 0.58.6
Device: Moto G5 Plus and iPhone 8

**Comment by adamsythe** [comment]
Same issue on Samsung Galaxy j6

**Comment by jahicDario** [comment]
I found a workaround: https://gist.github.com/ilya-uryupov/7bc9515c6d315d4919ff56ebf4e20411

**Comment by duyenhang** [comment]
keyboardShouldPersistTaps="handled" -> Add this line to View contain TextInput, it work well.

**Comment by diegolmello** [comment]
The issue persists.
There's only a workaround.
