### ISSUE TITLE
OnLongPress is not working in Tablet device(Both in android & ios)

### ISSUE THREAD

**Issue by Yandamuri** [facebook/react-native#23655]
## 🐛 Bug Report
`OnLongPress`  is not getting initiated in Tablet device(Both in android & ios)

## To Reproduce
If  `TouchableOpacity`  component is created with `onLongPress` action, This issue can be reproduceble

## Expected Behavior
when the `Touchable`  component is hold for long time , `OnLongPress` should be initiated.
## Code Example
    <TouchableOpacity style={Styles.tabletStyle.listRowStyle} onPress={() => this.onRowClick(item)} onLongPress={(event) => this.onContextMenuOpen(event, item)}}>
           <Text>Render Something</Text>               
    </TouchableOpacity>
## Environment
    OS: Linux 4.15
    Node: 11.4.0
    npm: 6.4.1
    react-native: 0.52.2

I have implemented long press in many area in my app for testing purpose, But no where it's working. But same code is working as expected in mobile devices.

**Comment by Yandamuri** [comment]
@react-native-bot I have already included Environment info. If these details are not enough , Let me know what to mention in addition to these details

**Comment by ericlewis** [comment]
@Yandamuri as the bot said, please run `react-native info`

**Comment by Yandamuri** [comment]
@ericlewis As i had already mention in my previous comment, i had run the command and Pasted those details in the question. Could you let me what am i missing here?

**Comment by CatapultJesse** [comment]
@Yandamuri is this issue occuring while debugging, or in a production build?

**Comment by Yandamuri** [comment]
@CatapultJesse in both builds. Just now I have checked production build as well.

**Comment by Yandamuri** [comment]
I have just noticed that it's working as expected. Surprisingly it started working without doing any changes,Hence proceeding to close
