### ISSUE TITLE
Unexpected token '.' no stack

### ISSUE THREAD

**Issue by remigarcia** [facebook/react-native#23669]
## 🐛 Bug Report
When i'm running `react-native run-android` while an emulator is on, everything is fine, my app is correctly running.
But when I've got my device connected via USB and I make the same command, the app builds, installs, but I have the following error : 
![image](https://user-images.githubusercontent.com/12694476/53485002-68832f80-3a85-11e9-88da-4068be2ffb18.png)

## To Reproduce
- running `react-native run-android` on a connected device

## Expected Behavior
The app should run correctly

## Environment
```
  React Native Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
      CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
      Memory: 1.86 GB / 15.54 GB
      Shell: 5.4.2 - /usr/bin/zsh
    Binaries:
      Node: 8.15.0 - /usr/bin/node
      Yarn: 1.12.3 - /usr/bin/yarn
      npm: 6.7.0 - /usr/bin/npm
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.58.4 => 0.58.4 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

package.json :
```
{
  "name": "myApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "buffer": "^5.2.1",
    "private-dependency": "git+ssh://git@github.com:private/dependency.git",
    "isomorphic-fetch": "^2.2.1",
    "jwt-decode": "^2.2.0",
    "lodash": "^4.17.11",
    "moment": "^2.24.0",
    "object-path": "^0.11.4",
    "react": "16.6.3",
    "react-native": "0.58.4",
    "react-native-gesture-handler": "^1.0.15",
    "react-native-paper": "^2.11.1",
    "react-native-share": "^1.1.3",
    "react-native-vector-icons": "^6.3.0",
    "react-navigation": "^3.3.0",
    "react-redux": "5.0.5",
    "redux": "3.6.0",
    "redux-form": "7.3.0",
    "redux-persist": "^5.10.0",
    "universal-url": "^2.0.0"
  },
  "devDependencies": {
    "babel-core": "^7.0.0-bridge.0",
    "babel-jest": "24.1.0",
    "jest": "24.1.0",
    "metro-react-native-babel-preset": "0.52.0",
    "react-test-renderer": "16.6.3"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**Comment by kelset** [comment]
Hello there 👋 this issue doesn't have a repro (which means, a `react-native init`-ed project with the minimal changes that leads to creating the same issue you are reporting). Unfortunately, I have no way of helping you in a meaningful way – there is no easy way for me to recreate the situation and check that the issue reported is still there when changing the code.

The only suggestion that I can give is that maybe it has something to do with the bundler...? Probably upgrading to 0.59 is the best strategy to try and fix this.

Because of this, we are going to close this issue - but if a repro is shared, we are happy to reopen it 🤗

**Comment by jraleman** [comment]
I know I'm late into the conversation, but I also encountered a similar error:
```
unhandled js exception unexpected token ': ' no stack
```
The issue that I had was that I had an extra colon in one of my json files, something like:
```
"key":: "value",
```
Hopefully someone finds this useful in the future, it sucks being stuck in a silly issue for a bit :p

**Comment by mjm918** [comment]
In my case, unexpected toke '<' no stack

But surprisingly it happens only when I run on Android 9

**Comment by urska19** [comment]
It's happening the same to me as @mjm918 and only on Android 9.

**Comment by Vidyack** [comment]
I resolved this issue by turning on USB debugging in the android device.
