### ISSUE TITLE
jsi::runtime::evaluateJavaScript can not evaluate javascript with "this object"

### ISSUE THREAD

**Issue by kangkangRabbit** [facebook/react-native#23665]
In my case，i need evaluate some dynamic javascript. In react-native version before 0.58，i can get JSGlobalContextRef instance and call JSEvaluateScript with this.Now,javascript api is encapsulated into jsi. It is a good idea,but jsi::runtime::evaluateJavaScript function omit "this object" parameter. In my case , i need evaluate javascripts with specific "this object" parameter.

**Comment by cpojer** [comment]
Please note this issue tracker is not a help forum (as stated in issue template).

We recommend using [StackOverflow](https://stackoverflow.com/questions/ask) where there are community incentives to help others or our [Discord channel](https://discord.gg/Xs5Xbjr) for questions.
