### ISSUE TITLE
[ListView] Setting opacity of wrapper view to 0 still allows Touchables to trigger

### ISSUE THREAD

**Issue by aleclarson** [facebook/react-native#2366]
Imagine a `ListView` is wrapped by a plain `View` that has its `opacity` set to `0`. The children of the `ListView` have `Touchable` elements inside them. Despite the `ListView` no longer being visible, the touches are recognized by the hidden `Touchable` elements. If you the set `opacity` of the `ListView` to `0`, the problem is fixed.

No time to make an example project. But could someone else confirm this problem?

**Comment by browniefed** [comment]
Maybe use `pointerEvents="none"` here.

**Comment by ide** [comment]
^ pointerEvents is the right approach. On other platforms (DOM, Android) opacity: 0 consumes touch events so you'll want to use pointerEvents.
