### ISSUE TITLE
buid on iOS do not honor RCT_NO_LAUNCH_PACKAGER setup

### ISSUE THREAD

**Issue by kascote** [facebook/react-native#23661]
## 🐛 Bug Report

Every time a build start for iOS, Xcode try to launch metro bundler. There is a flag to disable this behavior but is not honored

The script defined here [1] is using this condition

``` [ -z \"${RCT_NO_LAUNCH_PACKAGER+xxx}\" ] ```

and that never will resolve to null (-z), I think the correct check is 

``` [ \"${RCT_NO_LAUNCH_PACKAGER+xxx}\"  = \"+xxx\" ] ```

[1] https://github.com/facebook/react-native/blob/master/React/React.xcodeproj/project.pbxproj#L4005

## To Reproduce

Under Build Settings add an User Defined variable like

```RCT_NO_LAUNCH_PACKAGER=1```

close all terminals. Start a build, when React building starts, the metro bundler script is launched.

## Expected Behavior

No terminal launched with metro bundler.

## Environment
```
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (2) x64 Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz
      Memory: 3.31 GB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.3 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.8.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: 0.58.5 => 0.58.5
    npmGlobalPackages:
      react-native-cli: 2.0.1

```

**Comment by kelset** [comment]
Hello there 👋 

By following the list of steps to reproduce, we can't actually see the reported bug on RN 0.59 so we'll close this issue. It may have something to do with your local setup, please double check that you are using the correct version of Android Studio / XCode / Android NDK / Yarn / etc.

Also, you may want to explore other ways to achieve that behaviour, like -> https://github.com/invertase/react-native-firebase/blob/master/tests/package.json#L86
