### ISSUE TITLE
iOS intermitent black screen on startup

### ISSUE THREAD

**Issue by mydesweb** [facebook/react-native#23671]
## 🐛 Bug Report

* Start RN app
* first open splash (OK)
* black screen for 1 second (THE PROBLEM HERE)
* first screen (OK)

This GIF is not mine, but describes the problem I have.
![48962445-1db9bf00-ef4e-11e8-8ec5-2b344e2c29a0](https://user-images.githubusercontent.com/5901386/53491571-6b8b1980-3a9f-11e9-8de5-d9e33d39e63e.gif)

## Environment
 React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
      Memory: 33.27 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.7.0 - ~/.nvm/versions/node/v11.7.0/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.5.0 - ~/.nvm/versions/node/v11.7.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 25, 27, 28
        Build Tools: 23.0.1, 23.0.3, 25.0.2, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.3
        System Images: android-19 | Google APIs Intel x86 Atom, android-21 | Google APIs Intel x86 Atom_64, android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.58.5 => 0.58.5 
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by ravirajn22** [comment]
Ok, the problem is they changed the default rootView.backgroundColor to black from white on iOS in one of the commits earlier https://github.com/facebook/react-native/pull/20945.

That has been reverted through this commit #23358 to white again.
For now you can manually update the file to white color to fix this. The revert commit should arrive in version 0.59.0

**Comment by radeno** [comment]
More https://github.com/facebook/react-native/blob/7da864284997109a37bbef739289c5e6e8d0514e/local-cli/templates/HelloWorld/ios/HelloWorld/AppDelegate.m#L25

@mydesweb i think this issue should be closed.
