### ISSUE TITLE
react native link is not working well

### ISSUE THREAD

**Issue by danijel2017** [facebook/react-native#23672]
Now I created new project with react native init command. After install some packages and done react-native link. Next when run react-native run-android I got this issue.

![image](https://user-images.githubusercontent.com/38466352/53503129-76b76700-3aea-11e9-826b-a159c0b9be6a.png)

Of course I can fix this issue manually. but I think this is version upgrade problem I think.
Because old version I don't get this issue.

Thanks for your reply

**Comment by grabbou** [comment]
Hey @danijel2017, thanks for submitting this. Can you repost this issue into dedicated CLI repository -> https://github.com/react-native-community/react-native-cli and then, close this one?

Our team will look into it.
