### ISSUE TITLE
[Animated] Lag while debugging in Chrome?

### ISSUE THREAD

**Issue by aleclarson** [facebook/react-native#2367]
At first, I thought the lag was solely caused by #1598. When I commented out the `RCTLogWarn` call, there were noticeable improvements (it was getting called on every frame of the animation). Yet it seems there are still problems.

Frames of the animation are skipped, but the FPS monitor reports a constant 60 FPS.

I tested on both an iPhone 5s device and its simulator version. Lag was noticeable in both.

Here's the code that couldn't run without noticeable lag:

```coffee
React = require "react-native"

{ Animated, AppRegistry } = React

Animated.View = React.createFactory Animated.View

class ReactNativeAnimatedPerf extends React.Component

  constructor: ->
    @state =
      step: 0
      top: new Animated.Value 100
      opacity: new Animated.Value 0

  componentDidMount: ->

    looped = =>
      duration = 600
      if @state.step is 0
        @state.step = 1
        toValue = 400
      else
        @state.step = 0
        toValue = 100
      Animated.timing @state.top, { toValue, duration }
      .start()

    setInterval looped, 1600

    Animated.timing @state.opacity,
      toValue: 1
      duration: 600
    .start()

  render: ->
    Animated.View
      style:
        position: "absolute"
        width: 100
        height: 100
        top: @state.top
        left: 100
        backgroundColor: "#DD69FF"
        opacity: @state.opacity

AppRegistry.registerComponent "ReactNativeAnimatedPerf", -> ReactNativeAnimatedPerf
```

Could it be as simple as the performance optimizations being disabled when `__DEV__ === true`?

Thanks for any help. :grinning:

**Comment by brentvatne** [comment]
Yeah Chrome debugging definitely runs slower than just running the app in JSC, and dev=true makes that even more exaggerated :smile:

Perhaps when these tools are available in JSC itself we can have better perf. I'd suggest just opening the debugger when you need it, and leaving it closed otherwise.

**Comment by aleclarson** [comment]
The ability to prevent the debugger websocket from talking to Chrome would be great.

- Reduced lag when using the app!
- Debugger values are kept buffered until needed!
- Can keep "Debug in Chrome" active even when not debugging!

Not sure how feasible this is. Could be detrimental to device memory?

The API could look like:

```js
// Accessible from both Chrome and device:
Debugger.pause();
Debugger.resume();

// Accessible from only Chrome:
Debugger.flush();
```

When `pause()` is called, the synchronized data would be buffered on device.

When `resume()` is called, the synchronized data will be sent to Chrome normally.

When `flush()` is called, the buffered data will be forced to synchronize.

**Comment by aleclarson** [comment]
We'll also need the ability to have multiple debugger tabs open at once, since we'll always have "Debug in Chrome" active in case an error is thrown. This would be useful for testing with both a simulator and a device at the same time; or even an iOS device and Android device together.

**Comment by brentvatne** [comment]
@aleclarson - can you create an issue on ProductPains with this description so people can vote on priority of it?

**Comment by aleclarson** [comment]
https://productpains.com/post/react-native/improve-performance-of-chrome-debugger/
