### ISSUE TITLE
[Packager] [0.10] stuck on "find dependencies"

### ISSUE THREAD

**Issue by morukutsu** [facebook/react-native#2368]
Good evening,

After updating to 0.10 from 0.9, the packager is stuck on the find dependencies step. After some time, the connection times out. I tried it with the init project (AwesomeProject) and it worked.

**Is there any step required to get it working?**
**What is the purpose of the find dependencies step?** I skimmed the source code of the packager but I could not really find what could cause this bug.

In the log below there are module resolve issues, in another attempt I fixed them but ended up with the same result.

Thanks,

```
React packager ready.

[21:10:20] <START> fs crawl
[21:10:21] <END>   fs crawl (1483ms)
[21:10:21] <START> Building in-memory fs
[21:10:22] <END>   Building in-memory fs (743ms)
[21:10:22] <START> Building in-memory fs
[21:10:23] <END>   Building in-memory fs (424ms)
[21:10:23] <START> Building Haste Map
[21:10:23] <START> Building (deprecated) Asset Map
[21:10:23] <END>   Building (deprecated) Asset Map (137ms)
[21:10:24] <END>   Building Haste Map (1389ms)
Unable to resolve module ReactNativeViewAttributes from /Users/morukutsu/Documents/mmnts2/node_modules/react-native-icons/FAKIconImage.ios.js
Unable to resolve module StyleSheetPropType from /Users/morukutsu/Documents/mmnts2/node_modules/react-native-icons/FAKIconImage.ios.js
Unable to resolve module createReactNativeComponentClass from /Users/morukutsu/Documents/mmnts2/node_modules/react-native-icons/FAKIconImage.ios.js
Unable to resolve module deepDiffer from /Users/morukutsu/Documents/mmnts2/node_modules/react-native-icons/FAKIconImage.ios.js
Unable to resolve module invariant from /Users/morukutsu/Documents/mmnts2/node_modules/react-native-icons/FAKIconImage.ios.js
Unable to resolve module merge from /Users/morukutsu/Documents/mmnts2/node_modules/react-native-icons/FAKIconImage.ios.js
Unable to resolve module RCTDeviceEventEmitter from /Users/morukutsu/Documents/mmnts2/node_modules/react-native-camera/Camera.ios.js
Unable to resolve module NativeModules from /Users/morukutsu/Documents/mmnts2/node_modules/react-native-camera/Camera.ios.js
Unable to resolve module ReactNativeViewAttributes from /Users/morukutsu/Documents/mmnts2/node_modules/react-native-camera/Camera.ios.js
Unable to resolve module StyleSheet from /Users/morukutsu/Documents/mmnts2/node_modules/react-native-camera/Camera.ios.js
Unable to resolve module createReactNativeComponentClass from /Users/morukutsu/Documents/mmnts2/node_modules/react-native-camera/Camera.ios.js
Unable to resolve module ReactPropTypes from /Users/morukutsu/Documents/mmnts2/node_modules/react-native-camera/Camera.ios.js
Unable to resolve module StyleSheetPropType from /Users/morukutsu/Documents/mmnts2/node_modules/react-native-camera/Camera.ios.js
Unable to resolve module NativeMethodsMixin from /Users/morukutsu/Documents/mmnts2/node_modules/react-native-camera/Camera.ios.js
Unable to resolve module flattenStyle from /Users/morukutsu/Documents/mmnts2/node_modules/react-native-camera/Camera.ios.js
Unable to resolve module merge from /Users/morukutsu/Documents/mmnts2/node_modules/react-native-camera/Camera.ios.js
[21:10:32] <START> request:/index.ios.bundle
[21:10:32] <START> find dependencies
```

**Comment by sghiassy** [comment]
I guess the first question is whether the `ReactNativeViewAttributes` is actually at the file path `/Users/morukutsu/Documents/mmnts2/node_modules/react-native-icons/FAKIconImage.ios.js`? 

Do you see it there? Is it in the file system?

**Comment by morukutsu** [comment]
@sghiassy: It's not, but this has been already reported there: https://github.com/corymsmith/react-native-icons/issues/59. The file you mention is this one: https://github.com/jeffreywescott/react-native-icons/blob/ffd9e757d22b91dab77f47542f5f99ed33efd0c3/FAKIconImage.ios.js#L18.

Are the two issues are related? 
Meaning an "Unable to resole module xyz" error could cause the packager to lock itself in the "find dependencies step"?

I will try to debug the packager to see exactly where it could be stuck and provide more informations to help debugging that.

**Comment by morukutsu** [comment]
Some progress on this: the function getOrderedDependencies() in the DependencyGraph returns a Promise. The caller never gets the return value of it and the lock in comes from there. 
https://github.com/facebook/react-native/blob/master/packager/react-packager/src/DependencyResolver/DependencyGraph/index.js#L229

I'm not sure why this happens but I will check if I can reproduce it on a sample project. Meanwhile I'll stick to 0.9.

**Comment by sjmueller** [comment]
I'm seeing the same problem with v0.10.0, and was able to reproduce on a sample project:
```
react-native init helloworld
cd $_
npm i --save react-native@0.10.0-rc
npm i --save socketcluster-client querystring
```
Then add the following line to `index.ios.js`:
```
var SocketCluster = require('socketcluster-client');
```
Run the project and the packager will hang at `[22:10:53] <END>   Building Haste Map (449ms)`.  I'm using socketcluster as an example of a lib that will trigger the problem, but I'm sure there are many packages that probably have the same effect.

**Comment by morukutsu** [comment]
@sjmueller +1, I'm also using socketcluster-client.

**Comment by morukutsu** [comment]
Ok, I see what causes this bug, thanks for having pointed out socketcluster-client.
In socketcluster-client, see: https://github.com/SocketCluster/socketcluster-client/blob/master/index.js

``` javascript
var pkg = require('./package.json');
```

For some reason, this line will lock the packager.
I tried to do the same thing in another package to see if requiring JSON files resulted in the same issues but it doesn't.

Any idea?

**Comment by sjmueller** [comment]
+ @jondubois, who can help further.  Coincidentally, this same line in socketcluster-client will also blow up in an application using webpack.  It's an easy fix to add the json module loader, but perhaps there's a less problematic means of grabbing the version number.

**Comment by morukutsu** [comment]
The root cause of the bug has not been clearly identified but SocketCluster has been fixed so it will work with react-native and webpack: https://github.com/SocketCluster/socketcluster-client/commit/69edacf136d2f976f15c80c7d29db0f1008366b2
