### ISSUE TITLE
React Native modules without ejecting

### ISSUE THREAD

**Issue by dalisoft** [facebook/react-native#23681]
Hello React Native community and thanks for amazing framework.
I will use React js, great library, then decided to use React Native for using as mobile app framework and stuck with problems.

As describing in many blogs as well as in official website, this platform allows use creating mobile apps with only JS, but is not as i know, but some of other tools allows it (i don't want post these here).

Let we think one case:
I want create mobile app with Push notifications feature, i need eject from create-react-native-app (aka expo/cli), then find plugin/module for it (i.e. https://github.com/react-native-community/react-native-push-notification-ios) and then i should know Java/Objective-C to make it work (which i don't know).

How to achieve Push notifications without ejecting and learning other language than JS?

Thank you
(Sorry for bad english)

**Comment by hramos** [comment]
From the template:

> ### Please note that discussions opened as issues in the core React Native repository will be closed.

May I suggest using one of the alternatives provided in https://github.com/facebook/react-native/issues/new?labels=Type%3A+Discussion&template=discussion.md?

**Comment by dalisoft** [comment]
Thanks. I didn’t knew that ejecting is core feature, as i think core features is rendering or other thing. 
I think i should look at different solutions, as my deadline soon. Thank you again. Have a nice day!
