### ISSUE TITLE
onTouchStart, onTouchEnd and onTouchMove: Undocumented Features or Deprecated Props?

### ISSUE THREAD

**Issue by gsklee** [facebook/react-native#23686]
I've come across numerous references to these supposedly present props on the View component but couldn't find any reference to them in the official doc site nor within the changelog from [here](https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md). Are these deprecated props or features waiting to be documented?

**Comment by ericlewis** [comment]
@gsklee afaik, it is simply an undocumented feature. I am not aware of them being deprecated or anything.

**Comment by empyrical** [comment]
They're from an upcoming feature in React Native's "Fabric" architecture - an implementation of W3C touch events. They don't work in stable react native.

You can have a look at the code here:

https://github.com/facebook/react-native/blob/master/ReactCommon/fabric/components/view/TouchEventEmitter.h
https://github.com/facebook/react-native/blob/master/ReactCommon/fabric/components/view/TouchEventEmitter.cpp

**Comment by bartolkaruza** [comment]
Hello there 👋 this issue is related to the documentation. There is a dedicated documentation repository where we would like to migrate this issue to. https://github.com/facebook/react-native-website/
