### ISSUE TITLE
null is not an object (evaluating 'u.onFulfilled')

### ISSUE THREAD

**Issue by Boubaker93** [facebook/react-native#23692]
## 🐛 Bug Report

Hello, I'm getting this error `com.facebook.react.common.JavascriptException: null is not an object (evaluating 'u.onFulfilled')` on my production app, specially in Galaxy S7 Edge android 7.0. It did not happen for me on my test devices so i dont know how exactly to reproduce this error :/

Here is a stacktrace of the error i'm getting : 

```
Fatal Exception: com.facebook.react.common.JavascriptException: null is not an object (evaluating 'u.onFulfilled'), stack:

  at onFulfilled (./s/promise/setimmediate/core.js:114:39)

  at apply (./s/react-native/Libraries/Core/Timers/JSTimers.js:298:17)

  at callback (./s/react-native/Libraries/Core/Timers/JSTimers.js:152:6)

  at passImmediates (./s/react-native/Libraries/Core/Timers/JSTimers.js:200:17)

  at _callImmediatesPass (./s/react-native/Libraries/Core/Timers/JSTimers.js:473:11)

  at _eventLoopStartTime (./s/react-native/Libraries/BatchedBridge/MessageQueue.js:344:9)

  at ./s/react-native/Libraries/BatchedBridge/MessageQueue.js:140:37

  at DebuggerInternal (./s/react-native/Libraries/BatchedBridge/MessageQueue.js:329:13)

  at ./s/react-native/Libraries/BatchedBridge/MessageQueue.js:140:37

  at ./s/react-native/Libraries/BatchedBridge/MessageQueue.js:118:17
```

## Expected Behavior
No crash at all.

## Environment

**React Native Environment Info:**
    **System:**
      OS: macOS 10.14.2
      CPU: (4) x64 Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz
      Memory: 1.15 GB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    **Binaries:**
      Node: 8.12.0 - /usr/local/bin/node
      Yarn: 1.3.2 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    **SDKs:**
      **iOS SDK:**
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      **Android SDK:**
        API Levels: 21, 22, 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.0, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.3, 28.0.2, 28.0.3
        System Images: android-16 | Google APIs Intel x86 Atom, android-22 | Google APIs ARM EABI v7a, android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    **IDEs:**
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    **npmPackages:**
      react: 16.6.3 => 16.6.3 
      react-native: 0.58.5 => 0.58.5 
    **npmGlobalPackages:**
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

**Comment by hramos** [comment]
Hey there, we use this repository to track bugs in React Native. Debugging individual crash logs is not typically something we handle through issues. If you can provide a minimal sample code that can trigger the crash, that would be useful. For now, I'm going to close this issue, but I encourage you to troubleshoot a little bit more and come back here if you're able to identify the particular piece of code that causes this crash to happen.
