### ISSUE TITLE
[ListView] Should `onScroll` be called when the animation ends?

### ISSUE THREAD

**Issue by aleclarson** [facebook/react-native#2369]
I know `onScrollAnimationEnd` exists, but wouldn't it make sense to call `onScroll` with the last value of the animation?

**Comment by brentvatne** [comment]
`onScroll` is supposed to indicate that the user is actively scrolling - the animation related callbacks allow you to differentiate between user interaction and native animations, so I don't think this is necessary. Closing for now but if you can ping me with a good use case for this then we can re-open and discuss :)
