### ISSUE TITLE
flushedQueue error on rapid refresh

### ISSUE THREAD

**Issue by bootstraponline** [facebook/react-native#237]
Rapidly refreshing (cmd+R) the default iOS sample will produce this error:

![reactnative_refresh_fail](https://cloud.githubusercontent.com/assets/1173057/6855066/a7c3f6d6-d3cb-11e4-8b90-1be636795e75.png)

Refreshing again will fix.

**Comment by brentvatne** [comment]
@jsierles #fridaytriage
