### ISSUE TITLE
error: resource style/Theme.AppCompat.Light.NoActionBar (aka com.gpt:style/Theme.AppCompat.Light.NoActionBar) not found.

### ISSUE THREAD

**Issue by yinka1255** [facebook/react-native#23707]
## 🐛 Bug Report
I did "react-native init projectname". And after successfull execution, I did "react-native run-android" and I get this error

Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  Output:  error: resource style/Theme.AppCompat.Light.NoActionBar (aka com.gpt:style/Theme.AppCompat.Light.NoActionBar) not found.
  error: resource style/Theme.AppCompat.Light.Dialog (aka com.gpt:style/Theme.AppCompat.Light.Dialog) not found.
  error: resource style/Theme.AppCompat.Light.Dialog (aka com.gpt:style/Theme.AppCompat.Light.Dialog) not found.
  error: resource style/Theme.AppCompat.Light.Dialog (aka com.gpt:style/Theme.AppCompat.Light.Dialog) not found.
  error: resource style/Theme.AppCompat.Light.Dialog (aka com.gpt:style/Theme.AppCompat.Light.Dialog) not found.
  error: resource style/Theme.AppCompat.Light.NoActionBar (aka com.gpt:style/Theme.AppCompat.Light.NoActionBar) not found.
  C:\react\gpt\gpt\android\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:105: error: style attribute 'attr/windowActionBar (aka com.gpt:attr/windowActionBar)' not found.
  error: failed linking references.

  Command: C:\Users\Dd\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\ffd21d5284a7af29d2ccd91cde565e5a\aapt2-3.2.1-4818971-windows\aapt2.exe link -I\
          C:\Users\Dd\AppData\Local\Android\sdk\platforms\android-28\android.jar\
          --manifest\
          C:\react\gpt\gpt\android\app\build\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml\
          -o\
          C:\react\gpt\gpt\android\app\build\intermediates\processed_res\debug\processDebugResources\out\resources-debug.ap_\
          -R\
          @C:\react\gpt\gpt\android\app\build\intermediates\incremental\processDebugResources\resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\
          --java\
          C:\react\gpt\gpt\android\app\build\generated\not_namespaced_r_class_sources\debug\processDebugResources\r\
          --custom-package\
          com.gpt\
          -0\
          apk\
          --output-text-symbols\
          C:\react\gpt\gpt\android\app\build\intermediates\symbols\debug\R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0
  Output:  error: resource style/Theme.AppCompat.Light.NoActionBar (aka com.gpt:style/Theme.AppCompat.Light.NoActionBar) not found.
  error: resource style/Theme.AppCompat.Light.Dialog (aka com.gpt:style/Theme.AppCompat.Light.Dialog) not found.
  C:\Users\Dd\.gradle\caches\transforms-1\files-1.1\react-native-0.58.6.aar\e2d2344623986e5bbdcbcb975470d700\res\values\values.xml:105:5-114:11: AAPT: error: style attribute 'attr/windowActionBar (aka com.gpt:attr/windowActionBar)' not found.

  error: failed linking references.
  Command: C:\Users\Dd\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\ffd21d5284a7af29d2ccd91cde565e5a\aapt2-3.2.1-4818971-windows\aapt2.exe link -I\
          C:\Users\Dd\AppData\Local\Android\sdk\platforms\android-28\android.jar\
          --manifest\
          C:\react\gpt\gpt\android\app\build\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml\
          -o\
          C:\react\gpt\gpt\android\app\build\intermediates\processed_res\debug\processDebugResources\out\resources-debug.ap_\
          -R\
          @C:\react\gpt\gpt\android\app\build\intermediates\incremental\processDebugResources\resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\
          --java\
          C:\react\gpt\gpt\android\app\build\generated\not_namespaced_r_class_sources\debug\processDebugResources\r\
          --custom-package\
          com.gpt\
          -0\
          apk\
          --output-text-symbols\
          C:\react\gpt\gpt\android\app\build\intermediates\symbols\debug\R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
13 actionable tasks: 1 executed, 12 up-to-date
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

Command failed: gradlew.bat installDebug

Error: Command failed: gradlew.bat installDebug
    at checkExecSyncError (child_process.js:616:11)
    at Object.execFileSync (child_process.js:634:13)
    at runOnAllDevices (C:\react\gpt\gpt\node_modules\react-native\local-cli\runAndroid\runAndroid.js:299:19)
    at buildAndRun (C:\react\gpt\gpt\node_modules\react-native\local-cli\runAndroid\runAndroid.js:135:12)
    at isPackagerRunning.then.result (C:\react\gpt\gpt\node_modules\react-native\local-cli\runAndroid\runAndroid.js:65:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)

## To Reproduce

  react-native init projectname
  react-native run-android

## Environment
React Native Environment Info:
    System:
      OS: Windows 8
      CPU: (4) x64 Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz
      Memory: 1.68 GB / 7.92 GB
    Binaries:
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5264788

**Comment by mayupat13** [comment]
I too have same problem any solution?

**Comment by yinka1255** [comment]
I had to uninstall my android studio completely and reinstall new one. I
dont know if thats a good solution though. It actually started working fine
about 2 days after I installed a new android tudio

**Comment by kelset** [comment]
yes it seems to be related to gradle or, anyway, some Android tool missbehaving. Please check your local configuration.

**Comment by rikutys** [comment]
Hi guys i have the same error and i also tried to reinstall the Android Studio but seems like it does not work for me. It still show me the error message 

`Android resource linking failed
error: resource style/Theme.AppCompat.Light.NoActionBar (aka com.myaxios5:style/Theme.AppCompat.Light.NoActionBar) not found.
error: resource style/Theme.AppCompat.Light.Dialog (aka com.myaxios5:style/Theme.AppCompat.Light.Dialog) not found.
error: resource style/Theme.AppCompat.Light.Dialog (aka com.myaxios5:style/Theme.AppCompat.Light.Dialog) not found.
error: resource style/Theme.AppCompat.Light.Dialog (aka com.myaxios5:style/Theme.AppCompat.Light.Dialog) not found.
error: resource style/Theme.AppCompat.Light.Dialog (aka com.myaxios5:style/Theme.AppCompat.Light.Dialog) not found.
error: resource style/Theme.AppCompat.Light.NoActionBar (aka com.myaxios5:style/Theme.AppCompat.Light.NoActionBar) not found.
D:\React\Sample\myaxios5\android\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:156: error: style attribute 'attr/windowActionBar (aka com.myaxios5:attr/windowActionBar)' not found.
error: failed linking references.`

**Comment by ahmad6242** [comment]
I was facing the same problem. 
I upgraded my Gradle to 5.1.1, this resolves the Issue.

**Comment by asifalikhokhar** [comment]
I am facing the same issue, any work around ?

**Comment by ashu777** [comment]
I am also  facing the same problem . Gradle version updated and reinstalled android studio and node JS but   facing the same problem. Any suggestions  appreciated.
Lower versions of react native  works . only problem in react native version  "0.59.8".

**Comment by shanukp** [comment]
try using android play resolver and resolve . That fixed the issue for me in case of fb sdk

**Comment by HarshitMadhav** [comment]
1) Go to your root project folder.
2) then, go to android folder.
3) locate the `.idea` folder. Open it and delete the `cache` and `libraries` folder.
