### ISSUE TITLE
DatePickerIOS minuteInterval does not work when choose mode='time' 

### ISSUE THREAD

**Issue by jfrolich** [facebook/react-native#23709]
minuteInterval still not working. This bug has been reported multiple times without a fix, with the issue being locked or marked stale:

https://github.com/facebook/react-native/issues/12672
https://github.com/facebook/react-native/issues/5967
https://github.com/facebook/react-native/issues/2763

**Comment by jfrolich** [comment]
Closed? The issue is still the same as referenced issues.

**Comment by eelmoni** [comment]
I have the same issue, any update on this?
