### ISSUE TITLE
Tap still captured after scrolling

### ISSUE THREAD

**Issue by urbanappetite** [facebook/react-native#2370]
Hey,

On Native iOS, if you have a scroll view with a button inside it, and you press where the button is then scroll around, the button will not fire its action.

On React Native, it does and so we have accidental actions when the user is trying to scroll.

I'd love a catch-all fix but for the moment I'd like to override the onMove so that if the touch has moved X away from the original point, then the touch on the view will be cancelled.

Can someone give me any pointers on how to get started with this?

Thanks!

Luke

**Comment by MossP** [comment]
This should also be the case in react-native. Having said that though, I have noticed on slower devices that the touch appears to get queued up and gets triggered after the scroll. Almost as if the touchup occurs singularly after the scroll (separately to the touchdown). Do you experience this on a relatively new device? What sort of CPU load are you getting at the time of the phenomenon?

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/tap-still-captured-after-scrolling
