### ISSUE TITLE
"Error Unauthorized" in the command line after enabling "Remote JS debugging"

### ISSUE THREAD

**Issue by onstash** [facebook/react-native#23719]
## 🐛 Bug Report

I am getting "Error Unauthorized" in the command line after enabling "Remote JS debugging". This is from a freshly installed react-native v0.58.6.

<img width="1196" alt="screenshot 2019-03-01 at 23 21 58" src="https://user-images.githubusercontent.com/4272832/53656561-aa74c700-3c79-11e9-95f0-251c09f4c489.png">

## To Reproduce

`react-native start`
`react-native run android`
Enable Hot Reloading
Enable Live Reload
Enable JS Debugging

## Expected Behavior

Chrome tab should open Chrome debugger
App should not display a white screen & command line should not show "Error unauthorized"

## Code Example

Default app of a freshly installed react-native v0.58.6. Not sure what I can reproduce here.

## Environment

React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 35.32 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      Yarn: 1.12.3 - ~/.yarn/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.3
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.58.5 => 0.58.5 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

**Comment by hramos** [comment]
[Can you try using Safari for debugging?](https://github.com/react-native-community/discussions-and-proposals/issues/64#issuecomment-444783475) A JSI for debugger for Chrome is currently being worked on, but for now Safari is your best bet for remote debugging.

**Comment by onstash** [comment]
Similar end result. Mobile app screen is stuck at "Connecting to remote debugger".

**Comment by opp100** [comment]
Have you try this.

https://github.com/facebook/react-native/issues/23349#issuecomment-462279623

**Comment by onstash** [comment]
Hey @opp100. I tried that comment. It is not working.

**Comment by onstash** [comment]
Not sure how this issue is going to be fixed. I downgraded to 0.57.2 and things are working. Would close this issue if it's OK with you guys.

**Comment by kelset** [comment]
Can you tried init'ing a project with the latest rc for 0.59?

**Comment by onstash** [comment]
Hi @kelset. Sure. Will do that.

**Comment by kelset** [comment]
Ok, actually I may have an idea - are you using an Emulator or device running Android 9?

Because in that case you can simply add [this line](https://github.com/kelset/test-react-nav-with-screens/commit/3b2ef06af4f4eea85ae480be5f2ba1e350c8fff5) to your manifest as workaround. A proper fix is already in place for 0.59 (refer to [this conv](https://github.com/facebook/react-native/issues/22375)).

**Comment by marlon-wiprud** [comment]
Having the same issue. Debugging works on IOS simulator, but does not work on real IOS device. React native version: 0.58.6.

Error: unauthorized.

Any ideas greatly appreciated!

**Comment by Kendysond** [comment]
For more context for anyone that would like to help look into this. 

In my case, this error only came up after I setup my phone on Xcode and ran my app on my phone. 

Whenever you run your app on your phone, your debug URL will be your system IP:8081 e.g `http://192.168.0.190:8081/debugger-ui/` as opposed to the typical localhost i.e `http://127.0.0.1:8081/debugger-ui/` that the simulator uses. 

PS: This error goes away if you disable JS debugging on the simulator iPhone. 

That being said, after I was done testing with my phone and went back to my simulator, my debugger IP was still my system IP, and I think that's the source of this Unauthorized error. 

I hope this helps someone help us with solution.  😂

**Comment by sunnylqm** [comment]
I found that some chrome extensions may [contain custom orgin in headers](https://github.com/vitvad/Access-Control-Allow-Origin/issues/45), which would trigger this error.

https://github.com/react-native-community/react-native-cli/pull/253

**Comment by Gerlison** [comment]
I was with the same error. For me worked change the url of debugger in chrome of `192.168.0.xxx:8081/debugger-ui` to `localhost:8081/debugger-ui`. This happened when i was using Live Reload to run my app in a real device. I hope this help you

**Comment by user0604** [comment]
> I found that some chrome extensions may [contain custom orgin in headers](https://github.com/vitvad/Access-Control-Allow-Origin/issues/45), which would trigger this error.
> 
> [react-native-community/react-native-cli#253](https://github.com/react-native-community/react-native-cli/pull/253)

Thank  you! I had this exact problem, then I disabled the "Allow-Control-Allow-Origin" chrome extension and that solved it!

**Comment by alittletf** [comment]
Anyone who might come across this, I also encountered the Error: Unauthorized from Metro Bundler. I just restarted my computer and everything worked perfectly.

**Comment by DrHrishi** [comment]
Disable all chrome CORS extensions, and then try
