### ISSUE TITLE
[SliderIOS] Suggestion: add support for double-handled sliders?

### ISSUE THREAD

**Issue by hmm29** [facebook/react-native#2371]
Maybe there could be a way for SliderIOS to become a range slider if necessary

**Comment by adarshmuthappa** [comment]
:+1:

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/sliderios-suggestion-add-support-for-double-handled-sliders
