### ISSUE TITLE
ios or android file cannot be recreated (dont work react-native eject)

### ISSUE THREAD

**Issue by furkancelik** [facebook/react-native#23729]
## 🐛 Bug Report

i using v0.59.0-rc.3.

I get the following error when I run the react-native eject command when I want to delete and re-create the iOS or Android file.

<img width="568" alt="ekran resmi 2019-03-01 23 18 34" src="https://user-images.githubusercontent.com/6446228/53687114-a01e0000-3d41-11e9-8789-ab9b19fb2862.png">

**Comment by kelset** [comment]
It looks like this is an issue related to the CLI - please open an issue in the dedicated https://github.com/react-native-community/react-native-cli/issues and create a series of steps to reproduce the issue, or even better provide a repro.
