### ISSUE TITLE
Cannot find module when run  'react-native init'

### ISSUE THREAD

**Issue by Amy-zsy** [facebook/react-native#23734]
## 🐛 Bug Report
I firstly use react-native, please help me. thanks!
When I run react-native init, I got an error as follow:

zhaoshuyus-MBP:demo Amymymy$ react-native init FirstApp
This will walk you through creating a new React Native project in /Users/Amymymy/react-native/demo/FirstApp
Using yarn v1.13.0
Installing react-native...
yarn add v1.13.0
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[------------------------------------------------------------------------------------------------------------------------] 0/587internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '/Users/Amymymy/react-native/demo/FirstApp/node_modules/react-native/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at checkNodeVersion (/usr/local/lib/node_modules/react-native-cli/index.js:306:21)
    at run (/usr/local/lib/node_modules/react-native-cli/index.js:300:3)
    at createProject (/usr/local/lib/node_modules/react-native-cli/index.js:249:3)
    at init (/usr/local/lib/node_modules/react-native-cli/index.js:200:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-native-cli/index.js:153:7)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
zhaoshuyus-MBP:demo Amymymy$ 

## Environment
[skip envinfo]
node: v10.15.2
yarn: 1.13.0
npm: 6.4.1
react-native-cli: 2.0.1

**Comment by Amy-zsy** [comment]
> Can you run `react-native info` and edit your issue to include these results under the **Environment** section?
> 
> If you believe this information is irrelevant to the reported issue, you may write `[skip envinfo]` under **Environment** to let us know.

I can't run react-native info since i haven't react-native project yet.

Amymymy$ react-native info
Command `info` unrecognized. Make sure that you have run `npm install` and that you are inside a react-native project.

**Comment by kelset** [comment]
What OS are you running on?

**Comment by Amy-zsy** [comment]
> What OS are you running on?

MacOS

**Comment by Amy-zsy** [comment]
> What OS are you running on?

macOS Mojave-10.14.3

**Comment by kelset** [comment]
It seems this has something to do with your machine configuration, have you followed all the necessary steps from the [Getting Started](https://facebook.github.io/react-native/docs/getting-started) guide in the Building Projects with Native Code?

I feel it may be either something with your node version, or something related to yarn. Maybe try to reinstall them?

**Comment by Amy-zsy** [comment]
Yes, I'm sure. I do all the guide want me to do.

I reinstalled node(include LTS, latest and node@8), npm(6.4.1, 6.7.0), yarn, react-native-cli, but nothing helped.

I used nvm before, and I completely removed it. Is it related to this problem?

**Comment by Amy-zsy** [comment]
When I uninstalled yarn, It worked.
Why it doesn't work with yarn?

**Comment by kelset** [comment]
Uhm, probably the way you installed yarn wasn't the correct one? etc. it doesn't have the right write/read permissions? 🤔

May be worth opening an issue on yarn? I feel that we could close this now. (but we can keep the conversation going)

**Comment by tourze** [comment]
I have the same issue.
