### ISSUE TITLE
onViewableItemsChanged with Flatlist results in TaskQueue Error with task

### ISSUE THREAD

**Issue by ln0v** [facebook/react-native#23747]
## 🐛 Bug Report

when using this.setState in the method for onViewableItemsChanged in Flatlist, get the following error
"TaskQueue: Error with task: Object is not a function(evaluating '_this.setState({displayItemIndex: vi.index})"

## Code Example
```javascript
render() {
return(
 <View style={style.tlcontent}>
                <FlatList
                    data={rtd}
                    renderItem={({item, index}) => this.showthisItem(item, index)}
                    keyExtractor={(item,index) => index.toString()}
                    horizontal={true}
                    ref={(ref) => { this._itemsList = ref;}}
                    onViewableItemsChanged={this.itemIsViewable}        
                />     
  </View>
   )
}

itemIsViewable = (v) => {
        console.log( 'view items', v)
        let { viewableItems, changed, viewabilityConfig } = v
            let vi = viewableItems[0]
            if( vi.isViewable ) {
                console.log( 'view index', vi.index)
                this.setState({displayItemIndex: vi.index})          // <---- this is where it crashes
            }
    }
```

## Environment

  System:
      OS: macOS High Sierra 10.13.3
    Binaries:
      Node: 9.8.0 - /usr/local/bin/node
      Yarn: 1.3.2 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.58.5 => 0.58.5

**Comment by CatapultJesse** [comment]
Unable to repro: https://snack.expo.io/@jkcooper/rn23747-flatlist-onviewableitemschange
Im guessing you're either calling it outside the class or another function is overwriting this.setState

**Comment by ln0v** [comment]
Thank you for your prompt response, yes I have used setState else where in the class with bad syntax that overwrote setState, the offending statement was:
~~~
this.setState = { displayItemIndex: indx}
~~~
fixing it, took care of it. Thanks for pointing it out.
