### ISSUE TITLE
Share.share iOS sms got an extra information not wanted

### ISSUE THREAD

**Issue by antoninleissen** [facebook/react-native#23746]
## 🐛 Bug Report

 When i share my content ( which is a simple text ) by choosing sms on iOS, i find an object not wanted "xxxxx.app" in my content. 

![img_0024](https://user-images.githubusercontent.com/26059244/53722153-2da64080-3e65-11e9-8632-60cb09a1aafc.jpg)

## To Reproduce

  - Import Share from react-native
 - Use it with this content : {  message: 'text',
                    title: 'text',
                    url: null }
 - Go on iOS and share using sms

## Expected Behavior

  I thought that content will just contain my text.

## Code Example

`import React, { Component } from 'react';
import {Share, View, Button} from 'react-native';

export default class Example extends Component {

    constructor(props){
        super(props);

    }

    async link(code){
        if (code !== undefined){

            try {
                const result = await Share.share({
                    message: 'Code d\'accès Seezam : '+code,
                    title: 'Partage du code d\'accès Sezaam',
                    url: null
                }, {
                    // Android only:
                    dialogTitle: 'Partager votre code',
                    subject: 'Partage d\'accès à la box Sezaam'
                });

                if (result.action === Share.sharedAction) {
                    if (result.activityType) {
                        console.log('ACTIVITY TYPE :: ',result.activityType);
                        // shared with activity type of result.activityType
                    } else {
                        // shared
                    }
                } else if (result.action === Share.dismissedAction) {
                    // do nothing
                }
            } catch (error) {
                alert(error.message);
            }

        }
    }

    render() {
        return (
            <View>
                <Button onPress={()=>{this.link(code)}}/>
            </View>
        );
    }
}`

## Environment

  React Native Environment Info:
    react-native : 0.58
    System:
      OS: Linux 4.15 Linux Mint 18.3 (Sylvia)
      CPU: x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 6.69 GB / 15.55 GB
      Shell: 4.3.48 - /bin/bash
    Binaries:
      Node: 10.8.0 - /usr/local/bin/node
      npm: 6.2.0 - /usr/local/bin/npm
    SDKs:
      Android SDK:
        Build Tools: 23.0.3, 25.0.0, 26.0.2, 26.0.3, 27.0.3, 28.0.0, 28.0.2, 28.0.3
        API Levels: 21, 23, 24, 25, 26, 27
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1

**Comment by kelset** [comment]
Which version of react-native are you using? The Env info doesn't show.

Also, I can see that you are relying on https://github.com/react-community/create-react-native-app, which has been archived. You should use Expo-CLI instead.

LMK if the issue still appears with the latest version of React Native.

**Comment by antoninleissen** [comment]
I'm using react-native 0.58.

**Comment by antoninleissen** [comment]
And i can't a way to delete this object into my content.

**Comment by kelset** [comment]
👋 there.

So, I just tried to use your code and it didn't actually work. To get it to a working state I had to change it to:

```
import * as React from 'react';
import { Button, View, StyleSheet, Share } from 'react-native';

export default class App extends React.Component {
  async link(code) {
    if (code !== undefined) {
      try {
        const result = await Share.share(
          {
            message: "Code d'accès Seezam : " + code,
            title: "Partage du code d'accès Sezaam",
            url: 'string'
          },
          {
            // Android only:
            dialogTitle: 'Partager votre code',
            subject: "Partage d'accès à la box Sezaam"
          }
        );

        if (result.action === Share.sharedAction) {
          if (result.activityType) {
            console.log('ACTIVITY TYPE :: ', result.activityType);
            // shared with activity type of result.activityType
          } else {
            // shared
          }
        } else if (result.action === Share.dismissedAction) {
          // do nothing
        }
      } catch (error) {
        alert(error.message);
      }
    }
  }

  render() {
    return (
      <View style={styles.container}>
        <Button
          title="test"
          onPress={() => {
            this.link('123123');
          }}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    paddingTop: 40,
    backgroundColor: '#ecf0f1'
  }
});

```

That said, once I got the code to work I couldn't repro your issue with version RN 0.59. I'm going to close this, please provide a new (which means, a `react-native init`-ed project with the minimal changes that leads to creating the same issue you are reporting) if this still happens to you in RN 0.59.
