### ISSUE TITLE
Possible Unhandled Promise Rejection (id: 0): Error: Permission denied (while saving the image via “CameraRoll.saveToCameraRoll()”)

### ISSUE THREAD

**Issue by aujisti-ador** [facebook/react-native#23743]
![screenshot 2019-03-04 at 12 48 35 pm](https://user-images.githubusercontent.com/25290075/53720240-6ad0f980-3e8a-11e9-9022-9f82a87f8f56.png)

I am getting Permission denied when trying to save the image to the gallery via "CameraRoll.saveToCameraRoll()" from react native. my code is below==>

`takePicture = async function() {`
    `if (this.camera) {`
      `const data = await this.camera.takePictureAsync();`
      `let saveResult = CameraRoll.saveToCameraRoll(data.uri);`
      `console.warn('takePicture ', saveResult);`
      `console.warn('picture url ', data.uri);`
    `}`
  `};`

i have taken permissions from android manifest and ios by adding required codes.
(On Android)

![screenshot 2019-03-04 at 12 50 27 pm](https://user-images.githubusercontent.com/25290075/53720322-a8ce1d80-3e8a-11e9-86f5-66a183120cc0.png)

even in ios i am getting the same permission denied error. what should i do to work it. i don't wanna try RN File system.

**Comment by ethanyuwang** [comment]
Having the same problem here. Did you figure out how to solve this?

**Comment by v0lume** [comment]
facing same problem
