### ISSUE TITLE
TouchableOpacity don't call onPress callback when hitSlop is set

### ISSUE THREAD

**Issue by KATIA0306** [facebook/react-native#23759]
## 🐛 Bug Report

`TouchableOpacity don't call onPress callback when hitSlop is set. Bug exists on iOS simulator.`

## To Reproduce

`Click TouchableOpacity => There is no callback on onPress event`

## Expected Behavior
 
 `console.log("Button pressed!")`

## Code Example

`handlePress = () => {
  console.log("Button pressed!")
}
<TouchableOpacity hitSlop={{ top: PADDING_TOP, bottom: PADDING_BOTTOM }} onPress={this.handlePress}>         
  <Text>Example</Text>
</TouchableOpacity>`

## Environment
React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
      Memory: 36.72 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.1 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.8.0 - ~/.npm-packages/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 27, 28
        Build Tools: 28.0.3
        System Images: android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: 0.58.6 => 0.58.6
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

**Comment by CatapultJesse** [comment]
It seems if you don't also pass the left and right (just set as 0) it can be a bit inconsistent as to when it counts a hit, even if its straight on the view. The docs don't indicate them as optional (https://facebook.github.io/react-native/docs/touchablewithoutfeedback#hitslop) so I think its working as expected.

Snack: https://snack.expo.io/@jkcooper/rn23759-touchableopacity-hitslop

**Comment by KATIA0306** [comment]
@CatapultJesse it worked, thank you very much!
