### ISSUE TITLE
PushNotificationIOS.getInitialNotification() returns null for Remote Notification on cold start

### ISSUE THREAD

**Issue by rliubigfoot** [facebook/react-native#23752]
## 🐛 Bug Report
Same issue as https://github.com/facebook/react-native/issues/9372, I am using the PushNotificationIOS.getInitialNotification function to check if the app is opened from a notification. This works when the app is launched from the background but not when the app has been force closed.

## To Reproduce
1. force quit the app
2. send a remote notification
3. click notification banner to open the app

## Expected Behavior
Expect a non-null notification in PushNotificationIOS.getInitialNotification and appOpenedByNotificationTap should be triggered. Instead, the notification is null.

## Code Example
in composition.js:

    function appOpenedByNotificationTap(notification) {
      AlertIOS.alert('appOpenedByNotificationTap');
    }

    PushNotificationIOS.getInitialNotification().then(function (notification) {
      if (notification != null) {
        appOpenedByNotificationTap(notification);
      } else {
        AlertIOS.alert('notification is null');
      }
    });

## Environment
Environment:
  OS: macOS High Sierra 10.13.6
  Node: 9.3.0
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

**Comment by mak12** [comment]
hi @rliubigfoot any luck with finding its solution ?
