### ISSUE TITLE
[fetch] FormData feature support detection broken

### ISSUE THREAD

**Issue by oblador** [facebook/react-native#2376]
I'm trying to post multipart files with `fetch` in RN 0.9.0 with something similar to this: 
```js
var formdata = new FormData();
formdata.append('image', this.state.image); // From camera roll or whatever
fetch('http://…', { method: 'POST', body: formdata });
```

It fails because the FormData feature detection always fails, more specifically [`'FormData' in self` on line 165 @ fetch.js](https://github.com/facebook/react-native/blob/master/Libraries/Fetch/fetch.js#L165). If I change `self` to `window` it works as expected, but somehow that feels too easy. I'm happy to send a PR or for someone to tell me why it's a bad idea.

**Comment by apolkingg8** [comment]
Same issue with that, `support.formData` and `support.blob` always false, but both `FormData`, `Blob` and `FileReader` exist in `windows`.

**Comment by ppiekarczyk** [comment]
I'm having this same issue. You are right about self.fetch being the issue

**Comment by jhau** [comment]
I am having the same issue, @oblador 's fix solved the problem.

**Comment by jim-lake** [comment]
This would be a great fix to merge

**Comment by despairblue** [comment]
:+1: definitely, at the moment I need to use template strings for the body.

One thing to consider is that fetch is pulled in from github/fetch, meaning if it's updated in the future, all changes local to this repo are lost and would have to be reapplied.

Probably better to include it there, though they seem [reluctant to include it](https://github.com/github/fetch/pull/31#issuecomment-62178920). On the other hand, maybe fetch was only initially imported and is now maintained by the react-native team.

**Comment by slooker** [comment]
I'm having the same issue as well.  @oblador's fix also worked for me.

**Comment by oblador** [comment]
My PR was recently merged, so I'm closing this issue.
