### ISSUE TITLE
How to send data to API and get the result from API React Native

### ISSUE THREAD

**Issue by ice16** [facebook/react-native#23761]
I am new to react native. I want to pass my multiple images and text to API. My problem is when I press a button to upload, I get the error "SyntaxError: JSON Parse error: Unrecognized token '<'"

Anyone can help me? Thank you

Here is my coding and I am using react-native-image-picker and RNFetchBlob:

`constructor() {
    super();

    this.state = {
      Image1: null,
      Image2: null,
      data1: null,
      data2: null,
      data3: null,
      numberOfApple: 0,
      numberOfOrange: 0,
      numberOfKiwi: 0,
    }
  }

  selectPhotoTapped1 =() =>{
            const options = {
                quality: 1.0,
                maxWidth: 500,
                maxHeight: 500,
                storageOptions: {
                    skipBackup: true
                }
            };

        ImagePicker.showImagePicker(options, (response) => {
        console.log('Response = ', response);

        if (response.didCancel) {
          console.log('User cancelled photo picker');
        }
        else if (response.error) {
          console.log('ImagePicker Error: ', response.error);
        }
        else {
          let source1 = { uri: response.uri };
          this.setState({
            Image1: source1,
            data1: response.data
          });
        }
      });
    }

        selectPhotoTapped2 =() =>{
            const options = {
                quality: 1.0,
                maxWidth: 500,
                maxHeight: 500,
                storageOptions: {
                    skipBackup: true
                }
            };

        ImagePicker.showImagePicker(options, (response) => {
        console.log('Response = ', response);

        if (response.didCancel) {
          console.log('User cancelled photo picker');
        }
        else if (response.error) {
          console.log('ImagePicker Error: ', response.error);
        }
        else {
          let source2 = { uri: response.uri };
          this.setState({
            Image2: source2,
            data2: response.data,
          });
        }
      });
    }

`uploadImageToServer` = () => {
                        RNFetchBlob.fetch('POST', 'https://xxx.xxx.xxx', {
                        Authorization: "Bearer access-token",
                        otherHeader: "foo",
                        'Content-Type': 'multipart/form-data',
                    },
                    [
                        { name: 'nApple', data: this.state.numberOfApple},
                        { name: 'nOrange', data: this.state.numberOfOrange},
                        { name: 'nKiwi', data: this.state.numberOfKiwi},
                        {name: 'apple', filename: 'image.png', type: 'image/png', data: this.state.data1},
                        {name: 'orange', filename: 'image.png', type: 'image/png', data: this.state.data2},
                    ]).then((resp) => {
                        let resObj = JSON.parse(resp.data);
                        console.error(resObj);

                    }).catch((err) => {
                        console.error(err);
                    })
                }`

**Comment by parinha** [comment]
you can checkout this lib

https://github.com/axios/axios
