### ISSUE TITLE
Webview 'injectJavascript' method not responding on iOS.

### ISSUE THREAD

**Issue by mackbrowne** [facebook/react-native#23775]
### Environment

- I'm using expo, I'm too new to know if the environment is irrelevant or not.  I'm assuming this method was in fact working at some point?

 React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
      Memory: 1.11 GB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.9.0 - ~/.nvm/versions/node/v8.9.0/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 5.5.1 - ~/.nvm/versions/node/v8.9.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 26, 28
        Build Tools: 23.0.1, 26.0.1, 26.0.3, 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 

Building for both Android and iOS.  But the problem only occurs on iOS.

### Steps to Reproduce

https://snack.expo.io/@mackbrowne.prodigy/webview-injectjavascript

1. Run this snack either in the browser on on an iOS device.  If running inside snack, make sure you pick iOS.
2. Tap the "broken" and "works" button see nothing happens.
3. Now reload snack / device in android instead and see the buttons working.

### Expected Behavior

I was hoping I could get access to globally exposed methods on the webview in both iOS and Android.

### Actual Behavior

From my investigation it seems all javascript commands are being ignored on iOS which the snack I linked also shows this behavior.  You can change the js to anything and it just doesn't respond.  Android works exactly as expected. 

Perhaps I'm doing something wrong, but the fact that it works on Android makes me think it's a bug in the Webview component itself.

### Reproducible Demo

https://snack.expo.io/@mackbrowne.prodigy/webview-injectjavascript

**Comment by mackbrowne** [comment]
This now seems to be working again in a recent update to expo.

**Comment by nickjuntilla** [comment]
@mackbrowne Which version of expo are you using. It doesn't seem to be working in expo 32.0.0 for me.
