### ISSUE TITLE
SafeAreaView padding on IOS

### ISSUE THREAD

**Issue by ScreamZ** [facebook/react-native#23774]
Hello, 

as you can see my search bar is leaving the padding.
The padding is correctly added on the left, but it overflow on the right side.

This is not occuring on Android.

We are forced to add a child view with the padding on IOS instead of styling the SafeAreaView.

https://snack.expo.io/@screamz/aW9zLW

**Comment by matt-block** [comment]
Probably related to #22211. The described issue is not exactly the same but still related to `SafeAreaView` not respecting padding properties.
