### ISSUE TITLE
"Unknown method: undefined" warning in console at the start

### ISSUE THREAD

**Issue by jozan** [facebook/react-native#2377]
I started to get this when I upgraded my app to 0.9.0. It happens with new projects as well.
![Unknown method: undefined - screenshot](http://i.imgur.com/tisbFyI.png)

**Comment by ide** [comment]
I've seen this too. Will add more details when I can repro.

cc @frantic

**Comment by chirag04** [comment]
@ide  did you see this on 0.9 or 10-RC?

**Comment by ide** [comment]
This was with 0.9.

**Comment by chirag04** [comment]
kk. Thanks. Will test more.

**Comment by ide** [comment]
This happens in master when you refresh the app while connected to the Chrome debugger. The server sends payloads like `{$open: id}` and `{$error: id}` that aren't commands and don't have a `method` name.

**Comment by jozan** [comment]
Thanks @ide!

**Comment by eyaleizenberg** [comment]
@ide I'm also experiencing this. I just wanted to say that it's really great to see how involved the collaborators are in react native. Almost every issue I faced is being monitored. Thanks for this great project!

**Comment by ide** [comment]
It's nice to hear that; thanks guys :)

**Comment by jozan** [comment]
Nice work!

/J
