### ISSUE TITLE
Hot reloading on Android "HMRClient is not a registered callable module"

### ISSUE THREAD

**Issue by AlexMachin1997** [facebook/react-native#23788]
## 🐛 Bug Report
When hot-reloading is enabled I receive the following errors (See attached image)
![screenshot_20190306_123825_com awesomeproject](https://user-images.githubusercontent.com/29917195/53883535-2885f480-4011-11e9-950a-b7ca57f4473d.jpg)

When I disable it, the app goes back to normal, but Hot-Reloading is a necessity in modern day web development. Live-reloading is fine for now, but when I start to build more complex applications, it will be required.

## To Reproduce
1) Install react-native cli
2) Install expo cli
3) expo init AwesomeProject
4) react-native run-android
5) Dev tools: Live reloading, hot reloading, dev mode set to true, use deltas
6) The error will appear on the device's screen

## Expected Behavior
The application should reload reflecting the new changes, without seeing the error provided above.

## Environment
![image](https://user-images.githubusercontent.com/29917195/53883823-0b9df100-4012-11e9-88de-6272e3d15f44.png)

 "react-native": "0.58.6"

**Comment by AlexMachin1997** [comment]
`[skip envinfo]`

**Comment by AlexMachin1997** [comment]
So I've tested this on my android studio emulator and it's fine, but on my phone, I still get the error even though they are exactly the same settings essentially.

**Comment by brentvatne** [comment]
I can't actually repro this, it worked fine for me. You might want to disable live reloading, it doesn't make much sense to use that with hot reloading (you should use one or the other and not both at the same time)

maybe make sure you run `adb reverse` on your phone? https://facebook.github.io/react-native/docs/running-on-device#method-1-using-adb-reverse-recommended

**Comment by AlexMachin1997** [comment]
Oh ok, so I ran the ADB reverse command and just enabled hot reloading. Test it twice to see if it wasn't a fluke and it wasn't it's all working now.  

Hmm, I thought you could use both together, my bad. Thanks for the assistance Brentvatne 👍 💯 

I will be sure to update my development notes to note of this.

**Comment by waheed25** [comment]
Not works for me i have upgraded my version 0.57.8 to 0.59.3 after that i am facing this issue running "adb reverse tcp:8081 tcp:8081" still not works.

**Comment by waheed25** [comment]
Ahhh this issue occurs if we uncheck "JS Dev Mode" in Dev settings and then try to enable the hot reload enabling the "JS Dev Mode" works for me.

**Comment by YajanaRao** [comment]
I am facing the same issue with react native 0.61.2

**Comment by petergaultney** [comment]
I also have this issue when enabling Hot Reloading but having JS Dev Mode unchecked. It's very difficult to discover and means that you can't do proper performance profiling while also having Hot Reload enabled.
