### ISSUE TITLE
Discussion: Add support for delaysContentTouches

### ISSUE THREAD

**Issue by gazedash** [facebook/react-native#23783]
Link to the Apple documentation https://developer.apple.com/documentation/uikit/uiscrollview/1619398-delayscontenttouches

If you want to participate in casual discussions about the use of React Native, consider participating in one of the following forums:
- Discord Community: https://discord.gg/0ZcbPKXt5bZjGY5n
- Spectrum Chat: https://spectrum.chat/react-native
- Facebook Group: https://www.facebook.com/groups/react.native.community

For a full list of community resources:
- http://facebook.github.io/react-native/help

If you'd like to discuss topics related to the future of React Native, please check out the discussions and proposals repo:
- https://github.com/react-native-community/discussions-and-proposals

**Comment by hramos** [comment]
We're using GitHub issues to track bugs. To add new features, see the [contributing guide](http://facebook.github.io/react-native/docs/contributing), specifically the section on sending a pull request. Thanks!
