### ISSUE TITLE
React Native - android App Crashes Before Launch

### ISSUE THREAD

**Issue by joohimks** [facebook/react-native#23785]
I have recently published an app on PlayStore and I had a problem with my React Native "android Only" version as follows:

A- Status in Debug Mode:

The app would gives this error in both emulator and real android device and on a different IP other than my localhost as described in my /etc/hosts:

// Objects are not valid as a React child (found: object with keys {$$typeof, type, key, ref, props, _owner})

It would only open if I:
1- Run the debugger on "http://localhost:8081/debugger-ui"
2- run "react-native run-ios" 
3- Enable "Debug JS Remotely".

I was advised that this problem would disappear on production, so I launched the app and the problem as follows:

B- Problem at Production Mode

App would install perfectly and when I launch the app I get the following error:

com.facebook.react.common.JavascriptException: Objects are not valid as a React child (found: object with keys {$$typeof, type, key, ref, props, _owner}).

Any support is extremely appreciated.

Best Regards,

**Comment by ThomasGHenry** [comment]
+1

`$ react-native info

  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (8) x64 Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz
      Memory: 740.73 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 21, 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.0, 25.0.2, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.0, 28.0.2, 28.0.3
        System Images: android-21 | ARM EABI v7a, android-21 | Google APIs ARM EABI v7a, android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728
      react-native: ^0.57.3 => 0.57.8
`
