### ISSUE TITLE
Image missing when backward still there

### ISSUE THREAD

**Issue by ice16** [facebook/react-native#23799]
## 🐛 Bug Report
  I am using react native image picker. I want to maintain the image in the second activity when I go to the main activity and back to second activity. I no need to upload the image again. The bug on image missing when backward still there.

## To Reproduce
  npm install react-native-image-picker@latest --save
  npm install --save rn-fetch-blob

## Expected Behavior
  The image is maintained until I update the new image. No need to upload the image again and again.

## Code Example
 class FirstActivity extends Component {
            static navigationOptions = {
            title: 'Main Screen'
          }

Send_Data_Function = () => { this.props.navigation.navigate('Second', { no: this.state.number, }); }

        render() {
            return (
                    <TouchableOpacity>
                        <Text style={styles.TextStyle}> NEXT </Text>
                    </TouchableOpacity>/>
        )}

//second activity
constructor() {
    super();
    this.state = {
      ImageSource: null,
      data: null,
    }
  }

  selectPhotoTapped() {
    const options = {
      quality: 1.0,
      maxWidth: 500,
      maxHeight: 500,
      storageOptions: {
        skipBackup: true
      }
    };

    ImagePicker.showImagePicker(options, (response) => {
      console.log('Response = ', response);

      if (response.didCancel) {
        console.log('User cancelled photo picker');
      }
      else if (response.error) {
        console.log('ImagePicker Error: ', response.error);
      }
      else if (response.customButton) {
        console.log('User tapped custom button: ', response.customButton);
      }
      else {
        let source = { uri: response.uri };
        this.setState({
          ImageSource: source,
          data: response.data

        });
      }
    });
  }

  uploadImageToServer = () => {

    RNFetchBlob.fetch('POST', 'http://xxx.xxx.xx.x/upload_image.php', {
      Authorization: "Bearer access-token",
      otherHeader: "foo",
      'Content-Type': 'multipart/form-data',
    }, [
        { name: 'image', filename: 'image.png', type: 'image/png', data: this.state.data },
      ]).then((resp) => {
        var tempMSG = resp.data;
        Alert.alert(tempMSG);
      }).catch((err) => {
      })
  }

  render() {
    return (
      <View style={styles.container}>

        <TouchableOpacity onPress={this.selectPhotoTapped.bind(this)}>
          <View style={styles.ImageContainer}>
            {this.state.ImageSource === null ? <Text>Select a Photo</Text> :
              <Image style={styles.ImageContainer} source={this.state.ImageSource} />
            }
          </View>
        </TouchableOpacity>

        <TouchableOpacity onPress={this.uploadImageToServer} activeOpacity={0.6} style={styles.button} >
          <Text style={styles.TextStyle}> UPLOAD IMAGE</Text>
        </TouchableOpacity>
      </View>
    );
  }

## Environment
   React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
      Memory: 3.59 GB / 7.87 GB
    Binaries:
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338

**Comment by JKCooper2** [comment]
May be related to: https://github.com/facebook/react-native/issues/9195
Try adding a key to your image component based on the source
