### ISSUE TITLE
Image Component cannot update transform props

### ISSUE THREAD

**Issue by halftrue** [facebook/react-native#23808]
## 🐛 Bug Report
Image Component has two way to set transform properties.
1. just the top level props.
```js
<Image ...some other props transform={[{rotate: '180deg'}]}>
``` 
2. in the style
```js
<Image style={{ transform: [{rotate: '180deg'}] }}>
```
when you use the first way to set transform, it will fail to setState to update transform props.
while the second works well.

After read source code, I found that in [react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js](https://github.com/facebook/react-native/blob/master/Libraries/Renderer/oss/ReactNativeRenderer-dev.js)
line 3537
```
      var shouldUpdate =
        prevProp === undefined ||
        (typeof attributeConfig.diff === "function"
          ? attributeConfig.diff(prevProp, nextProp)
          : defaultDiffer(prevProp, nextProp));
````
in Situation1: shouldUpdate is false. Situation2 : it is true.
#### Situation 1
`<Image ...someotherprops transform={[{rotate: '180deg'}]}>`
the `attributeConfig.diff ` is  [Matric Differ](https://github.com/facebook/react-native/blob/master/Libraries/Utilities/differ/matricesDiffer.js)
which in this case will return false.
#### Situation 2
`<Image style={{ transform: [{rotate: '180deg'}] }}>`
the `attributeConfig.process` has a value of  [processTransform](https://github.com/facebook/react-native/blob/master/Libraries/StyleSheet/processTransform.js), which result in below code will excute instead:(bold below)
```js
var shouldUpdate =
        prevProp === undefined ||
        (typeof attributeConfig.diff === "function"
          ? attributeConfig.diff(prevProp, nextProp)
          : **defaultDiffer(prevProp, nextProp));**
      if (shouldUpdate) {
        var _nextValue =
          typeof attributeConfig.process === "function"
            ? attributeConfig.process(nextProp)
            : nextProp;
        (updatePayload || (updatePayload = {}))[propKey] = _nextValue;
      }
```

In my sight, it is caused by the different value of `attributeConfig` which retrieves from `attributeConfig = validAttributes[propKey];`
I checked the `propKey`, both transform, but they have a different value.

I don't know much about RN, so I can't trace any more about this question.

## Expected Behavior
setState should trigger update correctly.

## To Reproduce
Just place transform in the top level and try to update it. (only one transform should be set due to the matric diff).

 ## Code Example
I made a small demo.
In this demo, only the second one cannot transform.
[DEMO](https://github.com/halftrue/react-native-image-transform-props-bug)

## Environment
  React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 713.85 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.10.1 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
    npmGlobalPackages:
      create-react-native-app: 2.0.2

**Comment by jaysbytes** [comment]
It's supposed to work on my android 9 device - Xiamo Mi Mix 2S. Is it still an issue @halftrue? Can you provide a device on which it can be reproduced? Thanks in advance 😃
