### ISSUE TITLE
ReactCommon/jsi directory is missing when NPM install

### ISSUE THREAD

**Issue by ehf5307** [facebook/react-native#23809]
## 🐛 Bug Report
installing react-native 0.57.8 via npm install the ReactCommon/jsi folder is missing and this causes build errors using "react-native run-ios"
![screen shot 2019-03-07 at 10 43 55 am](https://user-images.githubusercontent.com/9353933/53969170-495c5180-40c6-11e9-80da-9b9161e56e82.png)

![screen shot 2019-03-07 at 10 47 02 am](https://user-images.githubusercontent.com/9353933/53969208-5da04e80-40c6-11e9-8662-99303e1a1edc.png)

you can see here the folder is missing:
![screen shot 2019-03-07 at 10 50 00 am](https://user-images.githubusercontent.com/9353933/53969441-ce476b00-40c6-11e9-9262-76ba855feb49.png)

## To Reproduce
- Have  "react-native": "^0.57.8" as a dependency in package.json
- run npm install
- run react-native run-ios

## Expected Behavior
App should build and run on the simiulator

## Environment
System:
      OS: macOS 10.14.3
      CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
      Memory: 8.28 GB / 32.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.6.0 - ~/.nvm/versions/node/v8.6.0/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 5.3.0 - ~/.nvm/versions/node/v8.6.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: ^0.57.8 => 0.57.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      react-native: 0.58.6

**Comment by ehf5307** [comment]
@react-native-bot  I did that in the original post, it's all there.

**Comment by hramos** [comment]
Does this still occur in 0.58? What about the 0.59 RC?
