### ISSUE TITLE
[Image] non-animated GIFs not rendering 0.10.0rc

### ISSUE THREAD

**Issue by iamkevb** [facebook/react-native#2380]
Image with png and jpg source are displayed correctly, but nothing is displayed for gif.

````
var ImageTest = React.createClass({
  render: function() {
    return (
      <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
        <View style={{flexDirection: 'row'}}>
        <Text>gif:</Text>
        <Image source={{uri: 'http://i.annihil.us/u/prod/marvel/i/mg/c/80/4ce59eb840da5/standard_medium.gif'}}
       style={{width: 100, height: 100}} />
       </View>
       <View style={{flexDirection: 'row'}}>
        <Text>jpg:</Text>
        <Image source={{uri: 'http://i.annihil.us/u/prod/marvel/i/mg/8/80/4c0041fb5a90d/standard_medium.jpg'}}
       style={{width: 100, height: 100}} />
       </View>
       <View style={{flexDirection: 'row'}}>
        <Text>png:</Text>
        <Image source={{uri: 'http://www.mybusinessmysuccess.com/wp-content/uploads/2013/10/shrug.png'}}
       style={{width: 100, height: 100}} />
       </View>
      </View>
    );
  }
});
````

Edit: 
It has something to do with that gif specifically.

does not work: http://i.annihil.us/u/prod/marvel/i/mg/c/80/4ce59eb840da5/standard_medium.gif
works: http://i.annihil.us/u/prod/marvel/i/mg/c/80/4ce59eb840da5/landscape_incredible.gif

Both of these are part of marvel comics API. See http://developer.marvel.com/documentation/images for information on their images.

**Comment by iamkevb** [comment]
Also noticed that onLoad is never called on that image

var ImageTest = React.createClass({
  render: function() {
    return (
      <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
        <View style={{flexDirection: 'row'}}>
        <Text>gif:</Text>
        <Image 
          source={{uri: 'http://i.annihil.us/u/prod/marvel/i/mg/c/80/4ce59eb840da5/standard_medium.gif'}}
          style={{width: 100, height: 100}} 
          onLoad={(e) => this.imageOnLoad(e)}
          onLoadStart={(e) => this.imageOnLoadStart(e)}
          onLoadEnd={(e) => this.imageOnLoadEnd(e)}
          />
       </View>
      </View>
    );
  },

  imageOnLoad: function(e) {
    console.log('onLoad:');
  },
  imageOnLoadStart: function(e) {
    console.log('onLoadStart:');
  },
  imageOnProgress: function(e) {
    console.log('onProgress:');
  },
  imageOnLoadEnd: function(e) {
    console.log('onLoadEnd:');
  }
});

AppRegistry.registerComponent('ImageTest', () => ImageTest);


¯\_(ツ)_/¯ 

Is there a guide to contributing to react-native somewhere? Happy to debug further.

**Comment by iamkevb** [comment]
Also noticed that onLoad isn't called for that particular image.  ¯\_(ツ)_/¯

````
var ImageTest = React.createClass({
  render: function() {
    return (
      <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
        <View style={{flexDirection: 'row'}}>
        <Text>gif:</Text>
        <Image 
          source={{uri: 'http://i.annihil.us/u/prod/marvel/i/mg/c/80/4ce59eb840da5/standard_medium.gif'}}
          style={{width: 100, height: 100}} 
          onLoad={(e) => this.imageOnLoad(e)}
          onLoadStart={(e) => this.imageOnLoadStart(e)}
          onLoadEnd={(e) => this.imageOnLoadEnd(e)}
          />
       </View>
      </View>
    );
  },

  imageOnLoad: function(e) {
    console.log('onLoad:');
  },
  imageOnLoadStart: function(e) {
    console.log('onLoadStart:');
  },
  imageOnProgress: function(e) {
    console.log('onProgress:');
  },
  imageOnLoadEnd: function(e) {
    console.log('onLoadEnd:');
  }
});

AppRegistry.registerComponent('ImageTest', () => ImageTest);
````

Is there a contributing to react-native page anywhere? Would be helpful to know how you typically set up your work environment to debug stuff like this.

**Comment by iamkevb** [comment]
RCTGIFImageWithImageSource is failing to create an animation from the gif in question (it's not an animated gif), the imageSource is being released and an error is thrown.

````
CAKeyframeAnimation *RCTGIFImageWithData(NSData *data)
{
  if (data.length == 0) {
    return nil;
  }

  CGImageSourceRef imageSource = CGImageSourceCreateWithData((CFDataRef)data, NULL);
  CAKeyframeAnimation *animation = RCTGIFImageWithImageSource(imageSource);
  CFRelease(imageSource);
  return animation;
}
````

**Comment by iamkevb** [comment]
In RCTImageDownloader:downloadImageForURL:(NSURL *)url with a lot of arguments...
                                               
Change this:
````
    if ([url.path.lowercaseString hasSuffix:@".gif"]) {
      id image = RCTGIFImageWithData(data);
      if (!image && !error) {
        NSString *errorMessage = [NSString stringWithFormat:@"Unable to load GIF image: %@", url];
        error = RCTErrorWithMessage(errorMessage);
      }
      completionBlock(error, image);
      return;
    }
````

to this:
````
    if ([url.path.lowercaseString hasSuffix:@".gif"]) {
      //rename this function. It returns a CAKeyframeAnimation, not an RCTGIFImage.
      id image = RCTGIFImageWithData(data);
      if (image) {
        completionBlock(error, image);
        return;
      } else {
//        Keep going and assume it's a static gif.
      }
    }
````

**Comment by soliury** [comment]
using git in react-native is dangerous. React-native can't show gif well, and it will take too much memory

**Comment by browniefed** [comment]
Previous recommendations are generally for https://github.com/Flipboard/FLAnimatedImage , I haven't seen anyone create a bridge for it yet but it's your best bet.

**Comment by iamkevb** [comment]
Using gif wouldn't be my first choice, but that's what some APIs return and UIImage supports displaying them. The bug is that react-native assumes all gifs are animated and doesn't handle static gifs correctly.

**Comment by brentvatne** [comment]
Fair point @iamkevb - can you submit a PR to fix this? Seems reasonable!

**Comment by nicklockwood** [comment]
@iamkevb This should be fixed now - single-image GIFs are returned as ordinary image instead of animation sequences. Would you mind checking?

**Comment by iamkevb** [comment]
Sorry about the slow response. Been out of the country for a few days.
Tested. Everything works now. Thanks!

**Comment by jhabdas** [comment]
@browniefed thanks for the resource. I'm building an app with a tab bar and an a sliding animation. It's possible one of the tabbed scenes will be playing an animated `gif`. If so, and it's slow, I may try to roll a native module on top of `FLAnimatedImage`.

**Comment by nicklockwood** [comment]
@jhabdas the issue @soliury is referring to is that RN decompresses all the gif frames before playback, which can use a lot of RAM for huge animated gifs (e.g the kind you find on meme sites, where a full-screen gif is being used in place of a video clip). For ordinary use cases like animated icons it's fine, and there is certainly no issue with playback speed.
