### ISSUE TITLE
ScrollView Inside a KeyboardAvoidingView straight up doesn't work

### ISSUE THREAD

**Issue by bobber205** [facebook/react-native#23826]
## 🐛 Bug Report
Basically the title. No events are fired either (onScroll etc)

## To Reproduce
Put a scroll view inside a keyboardavoiding view and run on Android. Works fine on iOS!

## Expected Behavior
Should work

## Code Example
https://snack.expo.io/@bobber205/quiet-kiwi

## Environment
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
      Memory: 36.16 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.6.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 26, 27, 28
        Build Tools: 26.0.2, 27.0.3, 28.0.3
        System Images: android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: 0.58.6 => 0.58.6

**Comment by bobber205** [comment]
Update:

Using the `enabled` properly to selectively turn KeyboardAvoidingView "off and on"  doesn't fix it.

KeyboardAvoidingView seems to be capturing some set of events that ScrollView needs

**Comment by JKCooper2** [comment]
Unable to repro with minimal example: https://snack.expo.io/@jkcooper/rn23826-scrollview-inside-keyboardavoidingview

Im not sure whats going on in yours, I believe its something to do with flex and fixed heights, but couldn't figure it out. If you replace the KeyboardAvoidingView with a plain view you still cannot scroll, so in any case the issue is not with KeyboarAvoidingView and ScrollView.
