### ISSUE TITLE
React Native App is getting crashed on launch only on certain Android & IOS devices

### ISSUE THREAD

**Issue by ronyv** [facebook/react-native#23820]
## Description

My react native app is getting crashed only on specific android and ios devices and my crashlytics report says something that is not clear for me. The following is the stack trace for the android app crash i received from Crashlytics.

```
Fatal Exception: com.facebook.react.common.JavascriptException: null is not an object (evaluating 'n[1].match(/[A-Z]/g).join'), stack:
<unknown>@352:820
<unknown>@352:814
v@2:1496
d@2:949
o@2:435
<unknown>@340:277
v@2:1496
d@2:949
o@2:435
<unknown>@339:118
v@2:1496
d@2:949
o@2:435
<unknown>@11:71
v@2:1496
d@2:879
o@2:435
global code@843:4

       at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:54)
       at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:38)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
       at android.os.Looper.loop(Looper.java:164)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
       at java.lang.Thread.run(Thread.java:764)
```

## RN Configuration for this build

> react:  16.6.1
> react-native: 0.57.7

## Major Packages used in the project

> "react-native-sqlite-storage": "^3.3.4"
> "react-navigation": "^1.0.0-beta.21",
> "react-redux": "^5.1.1",
> "redux": "^4.0.1",
> "redux-thunk": "^2.3.0"
> "react-native-firebase": "^5.1.1"
> "react-native-device-info": "^0.24.3"

## Affected Devices

So far this has happened consistently in 2 devices (that too in clients device). 

1. Android 
> Brand: samsung SM-A730F
> RAM free: 2.33 GB
> Disk free: 28.83 GB
> Version: 8.0.0
> Rooted: No 

2. IOS

> Model: iPhone 7 Plus
> RAM free: 157.27 MB
> Disk free: 67.7 GB
> Version: 12.1.4 (16D57)
> Jailbroken: No

 We tried in almost 20 real devices and none of those devices are getting this crash which makes me very difficult to solve this issue.

Any help on resolving this issue will be greatly appreciated.

Thanks in advance.

**Comment by ericlewis** [comment]
@ronyv without having more information, the error is related to trying to perform `n[1].match(/[A-Z]/g).join` in javascript on some unknown object that is being explicitly set to null. Which is invalid, if it is only affecting certain devices, I would look further to see if the devices are tied to a single user or set of users, and determine if there is perhaps something about their accounts that could be null. The javascript function that is failing is not in react-native, so I am not sure this is actually a react-native issue.

**Comment by hramos** [comment]
I agree, this does not seem to be related to React Native.

**Comment by ronyv** [comment]
> I agree, this does not seem to be related to React Native.

As you can see in the stacktrace, the exception is generated from "com.facebook.react.common.JavascriptException" package which is inside the react-native module. This means that something is not working correctly with react native that too only for specific devices.   According to @ericlewis , the framework is trying to get some data from some of the device account which is having a null value causing this issue. I don't understand about which account he is talking about. Does react native has such dependancy ? Even if it is yes, the affected devices are having Google account and Itunes account in logged in state. Not sure what other account information react native is trying to get.

**Comment by ericlewis** [comment]
@ronyv I was suggesting perhaps it’s user specific data issues, and suggesting how to debug. It’s not a bug in RN, that crash is because you have a bug in your javascript.
