### ISSUE TITLE
"react-native init ~" does not progress

### ISSUE THREAD

**Issue by thesunghwan** [facebook/react-native#2382]
<img width="588" alt="2015-08-19 22 35 52" src="https://cloud.githubusercontent.com/assets/7357525/9357573/acf32f22-46c2-11e5-854c-508a32ad3ab7.png">

As the figure shows, "react-native init ~" does not progress.
To add details,
- I have initiated severals apps few days ago.
- This was the first time it showed the behavior.
- After it showed the behavior, I remove all packages related to node including node, iojs, npm, and reinstalled with this process(https://facebook.github.io/react-native/docs/getting-started.html#content).
- When I go to AwesomeProject directory, there are only node_modules and package.json
- It's been around fifteen minutes since the initiation process, it still does not end.

**Comment by mattzeunert** [comment]
I'm experiencing the same issue. Did you find a solution that fixed it for you?
