### ISSUE TITLE
no image found

### ISSUE THREAD

**Issue by ice16** [facebook/react-native#23831]
## 🐛 Bug Report
  I am using react native image picker.  At the first time, I can upload the image. When I go to the main screen and back to the second screen cannot upload the image. Even though the image is at there but I also need to upload again my image.

## To Reproduce
npm install react-native-image-picker@latest --save
npm install --save rn-fetch-blob

## Expected Behavior
No need to pick up the image again and again. Can upload the image when the image is at there.

## Code Example
class FirstActivity extends Component {
  static navigationOptions = {
    title: 'Main Screen',
  }

  constructor(props) {
    super(props)
    this.state = {
      numberOfCat: 0,
      ImageSource: null,
      data: null,
    }
  }

  handleData({ ImageSource, data }) {
    this.setState({
      ImageSource,
      data
    })
  }
  Send_Data_Function = () => {
    const { numberOfCat } = this.state;

    if (numberOfCat == '') {
      Alert.alert("Please Enter All the Values.");
    }
    else {
      this.props.navigation.navigate('Second', {
        callback: this.handleData.bind(this),
        nCat: this.state.numberOfCat,
        ImageSource: this.state.ImageSource,
        data: this.state.data,
      });
    }
    console.disableYellowBox = true;
  }

  render() {
    return (

      <View style={styles.MainContainer}>
        <View style={{ flexDirection: 'row', padding: 10 }}>
          <Text style={styles.text1}>number of cat: </Text>
          <NumericInput
            type='up-down'
            totalWidth={150}
            totalHeight={45}
            minValue={0}
            initValue={this.state.numberOfCat}//<---Add---
            value={this.state.numberOfCat}//<----changes---
            onChange={data => this.setState({ numberOfCat: data })} />
        </View>

        <View style={styles.container}>
          <TouchableOpacity activeOpacity={.4} style={styles.buttonNext} onPress={this.Send_Data_Function} >
            <Text style={styles.TextStyle}> NEXT </Text>
          </TouchableOpacity>
        </View>
      </View>
    );
  }
}

class SecondActivity extends Component {
  static navigationOptions = {
    title: "Photos Screen",
  };

  constructor(props) {
    super(props);
    this._emitter = new EventEmitter();
    this.state = {

    }
  }

  componentWillMount() {
    this.setState({
      nCat: this.props.navigation.state.params.nCat.toString(),
      ImageSource: this.props.navigation.state.params.ImageSource ? this.props.navigation.state.params.ImageSource : null,
      data: this.props.navigation.state.params.data ? this.props.navigation.state.params.data : null,
    })
  }
  componentWillUnmount() {
    this.backClicked()
  }
  // Handle back click event and execute below code:
  backClicked() {
    if (this.props.navigation.state &&
      this.props.navigation.state.params &&
      this.props.navigation.state.params.callback) {
      let object = {}
      object.ImageSource = this.state.ImageSource
      object.data = this.state.data
      this.props.navigation.state.params.callback(object);
    }
  }

  selectPhotoTapped = () => {
    const options = {
      quality: 1.0,
      maxWidth: 500,
      maxHeight: 500,
      storageOptions: {
        skipBackup: true
      }
    };

    ImagePicker.showImagePicker(options, (response) => {
      console.log('Response = ', response);

      if (response.didCancel) {
        console.log('User cancelled photo picker');
      }
      else if (response.error) {
        console.log('ImagePicker Error: ', response.error);
      }
      else {
        let source = { uri: response.uri };

        this.setState({
          ImageSource: source,
          data: response.data
        });
      }
    });
  }

  uploadImageToServer = () => {
    RNFetchBlob.fetch('POST', 'xxx.xxx.xxx', {
      Authorization: "Bearer access-token",
      otherHeader: "foo",
      'Content-Type': 'multipart/form-data',
    },
      [
        { name: 'nCat', data: this.state.nCat },
        { name: 'bathroom', filename: 'image.png', type: 'image/png', data: this.state.data },
      ]).then((resp) => {

        let resObj = JSON.parse(resp.data);
        let predict = resObj.done;
        Alert.alert(predict);
      }).catch((err) => {
        console.disableYellowBox = true;
        Alert.alert("Please Upload the Photo");
      })
  }

  render() {
    return (
      <View style={styles.MainContainer}>
        <TouchableOpacity onPress={this.selectPhotoTapped.bind(this)}>
          <View style={styles.ImageContainer1}>
            {this.state.ImageSource === null ? <Text>Insert Image</Text> :
              <Image style={styles.ImageContainer1} source={this.state.ImageSource} />
            }
          </View>
        </TouchableOpacity>

        <TouchableOpacity onPress={this.uploadImageToServer} activeOpacity={0.6} style={styles.button} >
          <Text style={styles.TextStyle}> UPLOAD </Text>
        </TouchableOpacity>
      </View>
    )
  }
}

const AppNavigator = createStackNavigator({
  First: { screen: FirstActivity },
  Second: { screen: SecondActivity }
});

export default createAppContainer(AppNavigator);

## Environment
 React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
      Memory: 2.77 GB / 7.87 GB
    Binaries:
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338

**Comment by matt-block** [comment]
This seems to be strictly related to `react-native-image-picker`, so maybe it should be moved to the [React Native Image Picker](https://github.com/react-native-community/react-native-image-picker) repo directly.
