### ISSUE TITLE
Malformed calls from JS: field sizes are different

### ISSUE THREAD

**Issue by Blutude** [facebook/react-native#23835]
## 🐛 Bug Report
Here is the bug I get.

Malformed calls from JS: field sizes are different.

[[74,24],[19,1],[[64,2000,1552169087432,false]],415]

RCTFatal
-[RCTCxxBridge handleError:]
__34-[RCTCxxBridge _initializeBridge:]_block_invoke
facebook::react::RCTMessageThread::tryFunc(std::__1::function<void ()> const&)
facebook::react::RCTMessageThread::runOnQueue(std::__1::function<void ()>&&)::$_1::operator()() const
void std::__1::__invoke_void_return_wrapper<void>::__call<facebook::react::RCTMessageThread::runOnQueue(std::__1::function<void ()>&&)::$_1&>(facebook::react::RCTMessageThread::runOnQueue(std::__1::function<void ()>&&)::$_1&&&)
std::__1::__function::__func<facebook::react::RCTMessageThread::runOnQueue(std::__1::function<void ()>&&)::$_1, std::__1::allocator<facebook::react::RCTMessageThread::runOnQueue(std::__1::function<void ()>&&)::$_1>, void ()>::operator()()
std::__1::function<void ()>::operator()() const
invocation function for block in facebook::react::RCTMessageThread::runAsync(std::__1::function<void ()>)
__CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__
__CFRunLoopDoBlocks
__CFRunLoopRun
CFRunLoopRunSpecific
+[RCTCxxBridge runRunLoop]
__NSThread__start__
_pthread_body
_pthread_body
thread_start

## To Reproduce

I was on branch master, everything was working fine. I created a new branch 'android' and ran the android simulator, fixing a few things related to android. Then I wanted to make sure things still looked good in iPhone, so I ran to iPhone simulator and that's when I got the bug. The screen does not crash immediately. It crashes as soon as I login. The android simulator runs completely fine though. I figured I would 'git checkout master' branch to pinpoint what exactly caused that error, but the error persisted on the master branch. That doesn't make much sense to me

## Expected Behavior

The iPhone simulator should run fine.

## Environment

React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
      Memory: 1.38 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.11.0 - ~/.nvm/versions/node/v11.11.0/bin/node
      npm: 6.7.0 - ~/.nvm/versions/node/v11.11.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 26.0.1, 28.0.3
        System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.7.0 => 16.7.0 
      react-native: ^0.58.4 => 0.58.4 
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by cristian1703** [comment]
I have the same issue after running react native upgrade

**Comment by Blutude** [comment]
@cristian1703 I was not. I reverted to an old commit before react-native upgrade and it started working again.

**Comment by daveols** [comment]
@Blutude @cristian1703 -- upgrading to the latest patch `0.59.1` fixed this issue for me.

**Comment by cristian1703** [comment]
@daveols as you can see in my react-nativei info, I am already using 0.59.1

**Comment by rickhanlonii** [comment]
Hey @Blutude thanks for reporting!

Currently what's posted is a crash report, not a bug report, so it's not really actionable for us 

Can you update to outline what the bug is and how to reproduce?

**Comment by agarant** [comment]
I stumbled on the same error with RN 0.59.1. I'm not sure if it is linked to react-native or the underlying libraries, but maybe it can help reproducing it.

1. When trying out [react-native-reanimated-bottom-sheet](https://github.com/osdnk/react-native-reanimated-bottom-sheet), it crashed as soon as the component rendered.

2. When trying out the new [Menu component](https://callstack.github.io/react-native-paper/menu.html) from react-native-paper, it crashed when trying to open the menu.

Both of these cases (and the error message) seem to be linked to animation. [Here](https://github.com/callstack/react-native-paper/pull/485/files) is the PR for the Menu component.

**Comment by joebernard** [comment]
I ran into this error and it turned out I was passing `NaN` into a `react-navigation` config. I had to just start stripping out code till I isolated it.

**Comment by kala888** [comment]
it look like something wrong when use  "react-navigation": "2.18.3",

**Comment by cpojer** [comment]
Seems like this is a `react-navigation` issue.

**Comment by AugustoAleGon** [comment]
@cpojer I got the same problem. But I don't have `react-navigation`. I do have `react-native-navigation`.

**Comment by wicharek** [comment]
I had a similar issue. In my case, I tracked it down to native bridge serialization problem. Basically, the problem is that some JS values are not accepted as arguments for native method calls. Most notably: **NaN** and **Infinity**, also functions.

How to diagnose:

First, look for the errors like this in your log:

```
Invariant Violation
["<<NaN>>"] is not usable as a native method argument
```

This might give you and idea what specific value causing the problem.

In order to figure out the specific method, you should look into the first 2 number array reported by RN. Those are internal ids of native module and method:

`[[74,24],[19,1] ...`

They are not very straightfoward to look up, but one place you can start is `NativeModules.js` at function `genMethod`. Once you understand which native methods might cause the error just check your code for possibly incorrect values being passed. Good luck!

(In my case this only was a problem in debug mode, when the calls are made via Websockets, in release mode everything was working - I believe because of a different serialization mechanism React Native uses in release vs debug).

**Comment by nppull** [comment]
my problem RN0.59.8 
> [1209,"RCTView",{"opacity":1,"left":"<<NaN>>","pointerEvents":"box-none"}] is not usable as a native method argument

**Comment by wicharek** [comment]
@nppull notice `"left":"<>"`. Seems like somewhere in the code an incorrect value (NaN? Infinity?) is passed as `left` of some view.

**Comment by nppull** [comment]
> @nppull notice `"left":"<<NaN>>"`. Seems like somewhere in the code an incorrect value (NaN? Infinity?) is passed as `left` of some view.

i was fixed it :) 
i use lib navigator.. have a file `NavigatorNavigationBar.js`

before:
> COMPONENT_NAMES.forEach(function (componentName) {
>       var component = this._components[componentName].get(this.props.navState.routeStack[index]);
>       var props = this._getReusableProps(componentName, index);
>       if (component && interpolate[componentName](props.style, amount)) {
>         props.pointerEvents = props.style.opacity === 0 ? "none" : "box-none";
>          component.setNativeProps(props);
>       }
>     }, this);

after:
> COMPONENT_NAMES.forEach(function (componentName) {
>       var component = this._components[componentName].get(this.props.navState.routeStack[index]);
>       var props = this._getReusableProps(componentName, index);
>       if (component && interpolate[componentName](props.style, amount)) {
>         props.pointerEvents = props.style.opacity === 0 ? 'none' : 'box-none';
>         if(isNaN(props.style.left) == false){
>           component.setNativeProps(props);
>         }
>       }
>     }, this);

**Comment by sungsong88** [comment]
I'm getting the same error message issue.... @nppull what was the change u made there? So is this such an issue that will happen when prop_types type mismatch or invalid value somehow??

**Comment by ithustle** [comment]
Same here. 0.59.10

**Comment by sajjanhubale** [comment]
I'm getting the same error for date input field

**Comment by bearbytes** [comment]
Same problem, RN 0.59.10

I traced it back to a call to `executeSql` by `"react-native-sqlite-storage"`, a library that hasn't been updated in a while. I'm thinking there might be some breaking change in the underlying JS bridge which does not show up as compile error with some native libs.

**Comment by mairi17** [comment]
Same problem, not using react-navigation. We are using animation on this transition and are seeing:
`[1635,"RCTView",41,{"flex":1,"marginTop":16,"marginLeft":64,"marginRight":64,"opacity":"<<NaN>>"}] is not usable as a native method argument`

**Comment by sajjanhubale** [comment]
@mairi17 I fixed similar issue by setting up default value and added condition to check whether value is correct. In your case, opacity value should be a number.

**Comment by steventilator** [comment]
I just upgraded to React Native 0.60.4 and am facing the same issue. It happens when trying to animate the opacity like so:

```
opacity: this.props.scrollX.interpolate({
   inputRange: [0, this.width, 2 * this.width, 3 * this.width], // where this.width is a valid number
   outputRange: [0, 0, 0, 1],
}),
```

The error message includes the following – with opacity being the important part:

```
Invariant Violation: 
[1207,"RCTView",61,{
"position":"absolute",
"top":0,
"bottom":0,
"left":0,
"right":0,
"flex":1,
"opacity":"<<NaN>>"
}] is not usable as a native method argument.
```
Seems like the AnimatedValue is not transformed correctly to a number.

**Comment by StarkAndy** [comment]
if your code inside render() return function is like as below:

 <View>
        <Text style={{fontSize:22}}>Hello World</Text>
        <Provider store={store}>
        <SafeAreaView
          style={{ flex: 1, backgroundColor: theme.SECONDARY_COLOR }}
          forceInset={{ bottom: 'never ' }}
        >
          <View style={{ flex: 1 }}>
            <AppNavigator
              ref={navigatorRef => {
                NavigationService.setTopLevelNavigator(navigatorRef);
              }}
              onNavigationStateChange={(prevState, currentState) => {
                this.setState({ prevState, currentState });
                const currentScreen = this.getActiveRouteName(currentState);
                const prevScreen = this.getActiveRouteName(prevState);
                if (prevScreen !== currentScreen) {
                  console.log('currentScreen --------> ', currentScreen);
                }
              }}
            />
          </View>
        </SafeAreaView>
      </Provider>

Please remove SafeAreaView .Hope its works !!

**Comment by Drckk** [comment]
In my case, the problem is I defined a function in native with promise, but call it by callback

**Comment by 256hz** [comment]
Thank you @nppull, @steventilator, this thread helped me track down a bad value in react-native-maps.

**Comment by stevematdavies** [comment]
I have had this issue now, and no recourse yet after digging int the code for 3 days. My errors are to do with some translateX and transform, but the strange thing is, these are not used anywhere in my code. Is it some react-native module causing the issue perhaps?

**Comment by varungupta85** [comment]
@wicharek Thanks for your insights. I am also observing same problem only in debug mode which has almost blocked my development as I see the red screen as soon as the app is loaded. How did you fix the problem with the web sockets in your case. For me also, there are no bad values as such in the fields and it is happening during `WebSocket.emit`. The fields reported are `[[24,24,34,24],[1,0,4,0],[[377],[378,45000,1571487185812,true],[379,0,1571487185822,false]],1066]`.

**Comment by winni4eva** [comment]
Mine was related to AsyncStorage and I fixed it using https://stackoverflow.com/questions/56806467/error-exception-in-hostfunction-malformed-calls-from-js-field-sizes-are-diffe?answertab=active#tab-top

**Comment by JPritchard9518** [comment]
I had a similar issue when using a Pan Responder and animated value. My issue is I was setting an Animated.ValueXY variable called position via

`position.setValue({y: gesture.dy})`

without setting the x value as well. Updated to:

`position.setValue({y: gesture.dy, x: 0})`

and the error went away.

**Comment by vahidrn98** [comment]
my case was that i was trying to show server's response with Alert .
I just removed it and the error went away.

**Comment by varungupta85** [comment]
In my case, I was providing `moment` date as the fire date to PushNotificationIOS. I guess it is certain that this is happening when some invalid parameter is provided to a native method.

**Comment by arthedza** [comment]
> my case was that i was trying to show server's response with Alert .
> I just removed it and the error went away.

I confirm it

**Comment by 256hz** [comment]
Just had another fun instance of this I'll leave here for Google's sake.  When passing a custom component to `react-native-gesture-handler`, I got this error again until I wrapped the custom component in a blank `<View>`.  Looks like RNGH can't always pass down native props to custom elements.   The error propagated from a ReAnimated component, which I haven't figured out, and probably never will.

**Comment by stoica94** [comment]
> @wicharek Thanks for your insights. I am also observing same problem only in debug mode which has almost blocked my development as I see the red screen as soon as the app is loaded. How did you fix the problem with the web sockets in your case. For me also, there are no bad values as such in the fields and it is happening during `WebSocket.emit`. The fields reported are `[[24,24,34,24],[1,0,4,0],[[377],[378,45000,1571487185812,true],[379,0,1571487185822,false]],1066]`.

I have the exact same problem. It also stopped my development. If you fixed this issue please provide some feedback

**Comment by cgdstnc** [comment]
i was having same problem with code like this. I change code to second one and it seems problem gone. But i still don't know why
`
        const style = {
            ...StyleSheet.absoluteFillObject,
            zIndex: 900,
            transform: [
                { translateX },
                { translateY },
                { rotateZ },
            ],
        };
        return (
            <PanGestureHandler {...{ onGestureEvent }}>
                <Animated.View {...style}>
                    <Card />
                </Animated.View>
            </PanGestureHandler>
        )`

`            <PanGestureHandler {...{ onGestureEvent }}>
                <Animated.View style={{
                    ...StyleSheet.absoluteFillObject,
                    zIndex: 900,
                    transform: [
                        { translateX },
                        { translateY },
                        { rotateZ },
                    ],
                }}>
                    <Card />
                </Animated.View>
            </PanGestureHandler>`

**Comment by tarunjuneja** [comment]
I was showing some alert using Alert.alert that caused it for me.
The moment i turned it to a console.log it started working
So other similar react code can also be one of the reason 
that weird ...

**Comment by benevbright** [comment]
```
    const translateY = this.translateY.interpolate({
      inputRange: [-1, 0, 1],
      outputRange: [-1000, -(this.height), 0]
    });
```
Now sure if it's the same. But I got the error message too.
My mistake was `this.height` was `undefined` at the beginning. 
Putting the default value on `this.height` resolved my issue.

RN ver: 0.61.5

**Comment by creditcoder** [comment]
In my case, I used 'react-native-simple-toast' module to notify error message in the 'catch' clause.
`import Toast from 'react-native-simple-toast';
const axios = require('axios');
axios.post(url, {})
      .then(response => {
... ... ...
      }).catch(error => {
        //Toast.show(error);
      });
`
I commented Toast, and the error was gone.

The module versions are as follows:
"axios": "0.19.1",
 "react": "16.12.0",
 "react-native": "0.61.5",
"react-native-simple-toast": "1.0.0",

**Comment by basukiwinoto** [comment]
"react-native": "0.61.5",
    "@react-native-firebase/app": "^6.3.4",

I got this same error message when writing json object to firebase database.

A hacky solution: JSON.parse(JSON.stringify(<the_json_object_causing_problem>)) works for me.

**Comment by EricWiener** [comment]
This occurred for me when I was sending an object over the JS bridge to native iOS code. I thought I was passing an array, but it turned out to be a dictionary with numeric indices `{0: 'element1', 1: 'element2'}`. Once I converted this into an array, my issue went away.
