### ISSUE TITLE
Adding semi-transparent background color to Text component causing display issue on iOS 

### ISSUE THREAD

**Issue by Simek** [facebook/react-native#23849]
## 🐛 Bug Report
![IMG_5858 (1) (1)](https://user-images.githubusercontent.com/719641/54122672-f9e78f80-43fd-11e9-8455-d0e8ad71d700.png)
Adding semi-transparent background color to Text component causing display issue on iOS. 
It seems that background color is unnecessary reapplied under text characters inside Text component.

## To Reproduce
Apply semi-transparent `backgroundColor` to Text component (ex. `"rgba(255,0,0,.5)"`).

## Expected Behavior
Background color isn't reapplied under text characters.
(There is an easy workaround by adding `View` component wrapper to `Text` and applying background color to the wrapper)

## Code Example
https://snack.expo.io/@simek/rntext-semi-transparent-background-issue-ios

## Environment
```
  React Native Environment Info:
    System:
      OS: macOS 10.14.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.10.1 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.4 => 16.8.4 
      react-native: 0.58.6 => 0.58.6 
```

**Comment by ericlewis** [comment]
this issue seems related to the line below. we apply a background color which gets doubled up on the background color applied to the frame.
https://github.com/facebook/react-native/blob/1151c096dab17e5d9a6ac05b61aacecd4305f3db/Libraries/Text/Text/RCTTextView.m#L108

**Comment by ericlewis** [comment]
@Simek as a work around for now, you could wrap the Text in a View and set the background color there.

**Comment by fsfhiyg** [comment]
this issue seems related to the line below. we apply a background color which gets doubled up on the background color applied to the frame.

react-native/Libraries/Text/Text/RCTTextView.m

Line 108 in 1151c09

[layoutManager drawBackgroundForGlyphRange:glyphRange atPoint:_contentFrame.origin];

**Comment by fsfhiyg** [comment]
React Native Environment Info: System: OS: macOS 10.14.3 Shell: 3.2.57 - /bin/bash Binaries: Node: 11.10.1 - /usr/local/bin/node Yarn: 1.13.0 - /usr/local/bin/yarn npm: 6.7.0 - /usr/local/bin/npm Watchman: 4.9.0 - /usr/local/bin/watchman SDKs: iOS SDK: Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1 IDEs: Xcode: 10.1/10B61 - /usr/bin/xcodebuild npmPackages: react: 16.8.4 => 16.8.4 react-native: 0.58.6 => 0.58.6

**Comment by wxungang** [comment]
like this is ok !
```js
<Text style={{
                        textAlign: 'center',
                        justifyContent: 'center',
                        width: 114,
                        height: 36,
                        lineHeight: 36,
                        fontSize: 14,
                        fontWeight: 'bold',
                        color: '#FFF',
                        borderRadius: 12,
                        overflow: 'hidden',
                        backgroundColor: '#ED171f4C'
                    }}><Text style={{
                        backgroundColor: 'transparent'
                    }}>button</Text></Text>
```
