### ISSUE TITLE
Dependency ws1.1.5 has security issue, should be upgraded

### ISSUE THREAD

**Issue by AmrzsZH** [facebook/react-native#23845]
## 🐛 Bug Report

 React native 0.58.6

Dependency ws1.1.5 has security issue.

Affected version of ws (0.2.6--3.3.0) are vulnerable to A specially crafted value of the Sec-WebSocket-Extensions header that used Object.prototype property names as extension or parameter names could be used to make a ws server crash.
## To Reproduce

  Yarn and check the yarn.lock file
## Expected Behavior

Should update ws to more than 3.3.1
## Code Example

react-native@0.58.6:
  version "0.58.6"
  resolved: ...
  dependencies:
    ws "^1.1.0"
    ...
## Environment

    React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 1.32 GB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.10.1 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 24, 25, 26, 27, 28
        Build Tools: 24.0.2, 26.0.2, 28.0.1, 28.0.2, 28.0.3
        System Images: android-26 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.5.1 => 16.8.4 
      react-native: 0.58.6 => 0.58.6
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

**Comment by kelset** [comment]
👋 there - version 1.1.5 is a special release that is not affected by that security issue.
