### ISSUE TITLE
Image doesn't render local source (path with no extension name)

### ISSUE THREAD

**Issue by Liqiankun** [facebook/react-native#23844]
## 🐛 Bug Report

```
// write image to local path(iOS native code)
  NSString *path = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory,NSUserDomainMask, YES).firstObject;
  NSString *filePath = [path stringByAppendingPathComponent:[NSString stringWithFormat:@"image"]];
  [UIImagePNGRepresentation(image) writeToFile:filePath atomically:YES]

// under iOS (it works great)
[UIImage imageWithContentsOfFile: filePath];

// under react native (Could not find image filePath)
<Image source={{ uri:  filePath }} />

// If the filePath with extension name it works on both
  NSString *filePath = [path stringByAppendingPathComponent:[NSString stringWithFormat:@"image.png"]];
  [UIImagePNGRepresentation(image) writeToFile:filePath atomically:YES]
```
## Reason
Reason is the file has no extension name when write to path! It doesn't master under iOS, not work under React native!
![Simulator Screen Shot - iPhone XS - 2019-03-11 at 11 38 27](https://user-images.githubusercontent.com/11532418/54099103-92781280-43f2-11e9-8037-59709b683785.png)

## Code Example & Reproduce

[Github react-native-image-no-extension](https://github.com/Liqiankun/react-native-image-no-extension)

## Why I need to render image from local source
My project is using a iOS native IM framework. The framework save image to the local path without extension. Now I build chat ui by react native, so I must be able to render the image!

## Environment
 
  React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 93.95 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.1 - /usr/local/bin/node
      Yarn: yarn install v0.22.0
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 14.56s. - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 26, 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-28 | Intel x86 Atom_64
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.4 => 16.8.4 
      react-native: 0.59.0 => 0.59.0 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

**Comment by Liqiankun** [comment]
Reason is the file has no extension name when write to path! It doesn't master under iOS, not work under React native!

**Comment by CatapultJesse** [comment]
Unable to repro: https://snack.expo.io/@jkcooper/rn23844-image-wo-extension
I would recommend checking the file path you're using is correct, and that react native has access to the folder. There may be an issue there somewhere (I remember having difficulties loading images from react-native-fs a long time ago), but I believe would be best created under a separate issue when identified

I'd recommend asking on reactiflux to see how other people did it.

**Comment by Liqiankun** [comment]
Cuz the sources are different, so  unable to reproduce!

I will try to ask for help on Reactiflux!

Thanks!

**Comment by Liqiankun** [comment]
## error
run `react-native-git-upgrade 0.59.0`

git-upgrade info Check for updates 
git-upgrade info Using yarn 0.22.0 
git-upgrade info Read package.json files 
git-upgrade info Check declared version 
git-upgrade info Check matching versions 
git-upgrade info Check React peer dependency 
git-upgrade info Check that Git is installed 
git-upgrade info Get information from NPM registry 
git-upgrade info Upgrading to React Native 0.59.0, React 16.8.3 
git-upgrade info Setup temporary working directory 
git-upgrade info Configure Git environment 
git-upgrade info Init Git repository 
git-upgrade info Add all files to commit 
git-upgrade info Commit current project sources 
git-upgrade info Create a tag before updating sources 
git-upgrade info Generate old version template 
git-upgrade info Add updated files to commit 
git-upgrade info Commit old version template 
git-upgrade info Install the new version 
git-upgrade info Generate new version template 
git-upgrade ERR! An error occurred during upgrade: 
git-upgrade ERR! Error: ENOENT: no such file or directory, stat '/Users/old_david/Documents/DavidWorkSpace/PartTime/image_local_source/node_modules/react-native/local-cli/generator/copyProjectTemplateAndReplace.js'
    at Object.fs.statSync (fs.js:948:11)
    at mtime (/usr/local/lib/node_modules/react-native-git-upgrade/node_modules/babel-register/lib/node.js:97:24)
    at compile (/usr/local/lib/node_modules/react-native-git-upgrade/node_modules/babel-register/lib/node.js:112:36)
    at loader (/usr/local/lib/node_modules/react-native-git-upgrade/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/react-native-git-upgrade/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18) 
git-upgrade ERR! Restore initial sources 
Note: checking out 'project-snapshot'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 0b39f27 Project snapshot
M       package.json
M       yarn.lock

**Comment by Liqiankun** [comment]
@react-native-bot I upgrade to the latest version! Still have the same issue!

**Comment by Liqiankun** [comment]
@zhongwuzw #23864 works!

**Comment by zhongwuzw** [comment]
@Liqiankun #23864 is being reviewed in facebook internal team, it would be merged if approved.

**Comment by Liqiankun** [comment]
@zhongwuzw Thanks! That'd be great!

**Comment by Liqiankun** [comment]
I got new issue!

Here are two local path 
1) `// file:///Users/old_david/Library/Developer/CoreSimulator/Devices/0B3F56B2-F48F-4970-A7F5-DDB8361CA2EF/data/Containers/Data/Application/80B86F95-1856-4192-B3A7-D1E5947E4B24/Documents/HyphenateSDK/appdata/aihehuo204535/aihehuo211792/1552447525991`
2) ` // file:///Users/old_david/Library/Developer/CoreSimulator/Devices/0B3F56B2-F48F-4970-A7F5-DDB8361CA2EF/data/Containers/Data/Application/80B86F95-1856-4192-B3A7-D1E5947E4B24/Documents/HyphenateSDK/appdata/aihehuo204535/aihehuo9337889/fb0cb8d0-4561-11e9-a586-dbad6fe04e5e`
The first path can be rendered, not for then second one! @zhongwuzw

**Comment by zhongwuzw** [comment]
@Liqiankun Emm, these paths typically are the same, can you check put `fb0cb8d0-4561-11e9-a586-dbad6fe04e5e` image to another directory, or just rename it to `thumb_fb0cb8d0-4561-11e9-a586-dbad6fe04e5e`, the issue still exist?

**Comment by Liqiankun** [comment]
![Simulator Screen Shot - iPhone XS - 2019-03-13 at 18 13 40](https://user-images.githubusercontent.com/11532418/54271125-e124d880-45bb-11e9-986a-b1c3dfe1a262.png)

@zhongwuzw It works! I have to upgrade the project I'm working on to 0.59.0! 
I guess this issue related with react native version!

**Comment by dulmandakh** [comment]
fixed in 
https://github.com/facebook/react-native/commit/e40a76715a11b1465c10076f975ff7335c84cf30
