### ISSUE TITLE
ActionSheetIOS.showShareActionSheetWithOptions interface is always in English

### ISSUE THREAD

**Issue by center-777** [facebook/react-native#23853]
## 🐛 Bug Report
Despite the settings of language on the phone, the cancel button is always shown in English.

## Code Example
https://snack.expo.io/@center-777/actionsheetios.showshareactionsheetwithoptions

## Environment
  React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
      Memory: 197.18 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.9.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by zhongwuzw** [comment]
@center-777 This is the designated behavior in `iOS`, you can add `CFBundleAllowMixedLocalizations` to `YES` in `info.plist`. https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/20001431-130418
