### ISSUE TITLE
[iOS] Keyboard can not dismiss after use Alert

### ISSUE THREAD

**Issue by andres-torres-marroquin** [facebook/react-native#23852]
## 🐛 Bug Report
If a `TextInput` has `blurOnSubmit={false}`, and an `Alert` gets opened when the `TextInput` is focused, after dismissing the `Alert` the keyboard reopens by itself, and you won't be able to dismiss the keyboard anymore. The Snack example is pretty clear to understand.
Relates to #17356 and #9902

## To Reproduce
Create a `TextInput` with `blurOnSubmit={false}` and being focused, open an `Alert`.

## Expected Behavior
The keyboard should dismiss after opening an `Alert`.

## Code Example
https://snack.expo.io/B1ZX4bVDE

## Environment
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
      Memory: 45.73 MB / 32.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.13.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        Build Tools: 23.0.1, 25.0.3, 26.0.2, 27.0.1, 27.0.2, 27.0.3, 28.0.0, 28.0.2, 28.0.3
        API Levels: 17, 21, 22, 23, 25, 26, 27, 28
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.4 => 16.8.4
      react-native: 0.59.1 => 0.59.1

**Comment by gwdp** [comment]
Same issue here

**Comment by zhongwuzw** [comment]
@andres-torres-marroquin Hi, can you try the latest master branch to check wether it fixed?

**Comment by zhongwuzw** [comment]
I think this has been fixed in https://github.com/facebook/react-native/pull/23240. cc @kelset @cpojer .
