### ISSUE TITLE
PushNotificationIOS.removeEventListener method signature requires unused handler Function

### ISSUE THREAD

**Issue by schumannd** [facebook/react-native#23868]
https://github.com/facebook/react-native/blob/726d0012106316a40e36286f5eba0e881ef3bbba/Libraries/PushNotificationIOS/PushNotificationIOS.js#L236

This throws unhelpful flow errors. If this is an error, I can provide a PR removing this line.

**Comment by ericlewis** [comment]
@schumannd it seems unused, you could try removing it.

**Comment by grabbou** [comment]
I think we should actually fix the code to handle multiple listeners. Right now, if you call `addEventListener` two times, the latter one will silently overwrite the former one.

I believe this is kind of behaviour you wouldn't expect. 

If the API is designed to only handle single handler, it should be `setEventListener`.

**Comment by cpojer** [comment]
This issue has been moved to react-native-community/react-native-push-notification-ios#10.
