### ISSUE TITLE
'react-native upgrade' command still remains the old version.

### ISSUE THREAD

**Issue by JYeop** [facebook/react-native#23866]
## 🐛 Bug Report
The blog(http://facebook.github.io/react-native/blog/) says that the 0.59.0 released, and announced the the new upgrade way using 'react-native upgrade'.
But when I ran the command, the older version of the command result shown.
Is it a just bug or the new way did not applied the new way to the react-native-cli server?

> JYs-MBP:0.58.6 jyk$ react-native upgradeYou should consider using the new upgrade tool based on Git. It makes upgrades easier by resolving most conflicts automatically.
To use it:- Go back to the old version of React Native- Run "npm install -g react-native-git-upgrade"
> Run "react-native-git-upgrade"See https://facebook.github.io/react-native/docs/upgrading.htmlUpgrading project to react-native v0.58.6
Check out the release notes and breaking changes: https://github.com/facebook/react-native/releases/tag/v0.58.0
Upgrading project to react-native v0.58.6
Check out the release notes and `breaking` changes: https://github.com/facebook/react-native/releases/tag/v0.58.0

## Environment
  >React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
      Memory: 8.11 GB / 32.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.10.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28
        Build Tools: 27.0.3, 28.0.2, 28.0.3
        System Images: android-26 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-26 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.58.6 => 0.58.6 
    npmGlobalPackages:
      react-native-git-upgrade: 0.2.7

**Comment by hramos** [comment]
Copying here additional details from #23867 by @pistou:

## 🐛 Bug Report
I'm trying to upgrade my projet to 0.59 as it released, but it tries to upgrade to 0.58.6, which is my current react-native version.

```
$~ > react-native info

  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
      Memory: 8.01 GB / 15.90 GB
    Binaries:
      Yarn: 1.13.0 - D:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.1.0 - C:\Program Files\nodejs\npm.CMD

$~ > react-native --version
react-native-cli: 2.0.1
react-native: 0.58.6

$~ > react-native upgrade
You should consider using the new upgrade tool based on Git. It makes upgrades easier by resolving most conflicts automatically.
To use it:
- Go back to the old version of React Native
- Run "npm install -g react-native-git-upgrade"
- Run "react-native-git-upgrade"
See https://facebook.github.io/react-native/docs/upgrading.html
Upgrading project to react-native v0.58.6
Check out the release notes and breaking changes: https://github.com/facebook/react-native/releases/tag/v0.58.0
Successfully upgraded this project to react-native v0.58.6

$~ > react-native --version
react-native-cli: 2.0.1
react-native: 0.58.6
```

I tried to uninstall and reinstall `react-native-cli` just in case but didn't change much.

**Comment by thymikee** [comment]
New upgrade is _a part_ of RN 0.59. If you upgrade from 0.58 it's not there yet.

**Comment by kelset** [comment]
👋 there - so, it's a bit of a misunderstanding happening here 😅

Basically, the new `upgrade` command is usable **from** 0.59, so when you upgrade **to** it it's still not available. We are fixing the blogpost to be more clear on it :)

To upgrade to 0.59 we recommend using the [rn-diff-purge](https://github.com/react-native-community/rn-diff-purge) repo.

**Comment by JYeop** [comment]
Thanks! 😄

**Comment by turnrye** [comment]
@JYeop @pistou thank you for submitting these issues. We're getting the blog post updated to be clearer.

**Comment by appatappa** [comment]
> 👋 there - so, it's a bit of a misunderstanding happening here 😅
> 
> Basically, the new `upgrade` command is usable **from** 0.59, so when you upgrade **to** it it's still not available. We are fixing the blogpost to be more clear on it :)
> 
> To upgrade to 0.59 we recommend using the [rn-diff-purge](https://github.com/react-native-community/rn-diff-purge) repo.

I should point out that the official upgrade documentation page (https://facebook.github.io/react-native/docs/upgrading.html#content) still shows relies pretty heavily on `react-native upgrade`, though it does seem to use `rn-diff-purge` as a reference.

**Comment by kelset** [comment]
that's because from 0.59 the CLI command `upgrade` actually uses `rn-diff-purge` under the surface AFAIK

**Comment by appatappa** [comment]
@kelset got it! TBH it's about time they started paying attention to the upgrade process.

**Comment by shubhnik** [comment]
Documentation of previous versions also shows `react-native upgrade` method only.

**Comment by hramos** [comment]
@shubhnik you can find previous versions of the upgrade guide by browsing through the source file's history at https://github.com/facebook/react-native-website/commits/master/docs/upgrading.md

Would you mind opening an issue over at https://github.com/facebook/react-native-website to request these past instructions get added to the upgrading guide? That guide is unversioned, so it will show the same content regardless of which version you select at the top. We'll need to modify the guide to account for past versions. If you can send a PR, that would be even better.

**Comment by PomegranateApps** [comment]
So how does one actually upgrade from 0.58.6?

**Comment by thymikee** [comment]
You can use the CLI as a standalone, e.g.: `npx @react-native-community/cli upgrade` will do
