### ISSUE TITLE
why do you need to use sudo to run the project?

### ISSUE THREAD

**Issue by unutoiul** [facebook/react-native#23877]
why do you need to use sudo to run the project?

**Comment by ericlewis** [comment]
You shouldn’t need to unless you installed using sudo along the line somewhere.

**Comment by unutoiul** [comment]
to install as global you need sudo npm install -g expo-cli?

is the the only things why i used sudo

the rest was 

expo init AwesomeProject

and 
yarn start

and i get

EACCES: permission denied, open '/projects/prank/frontend/.expo/settings.json.2436623622'

**Comment by ericlewis** [comment]
You could chmod the .expo folder to belong to you, and it should work. I’m not sure how this happened. Will try to reproduce.

**Comment by grabbou** [comment]
I am closing this issue because I don't think it's related to React Native. Looks like you are having issues with Expo, in that case, I'd suggest to reach out to the Expo team.
