### ISSUE TITLE
Regression: can't debug RN 0.59.0 app

### ISSUE THREAD

**Issue by jacargentina** [facebook/react-native#23873]
## 💥 Regression Report
Trying to debug my app, gives me this result.

<img width="465" alt="Captura de pantalla 2019-03-12 a la(s) 16 44 55" src="https://user-images.githubusercontent.com/517228/54230945-46a69580-44e6-11e9-9cf7-05f70ec08c81.png">

## Last working version

Worked up to version: 0.59.0-rc.3

Stopped working in version: 0.59.0

## To Reproduce

Launch app with `react-native run-ios`
Enable debugging with Command+D then `Debug JS Remotely`

## Expected Behavior

Debugger should open

## Environment
```
info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
      Memory: 1.88 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.11.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.4 => 16.8.4 
      react-native: ^0.59.0-rc.3 => 0.59.0 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
```

**Comment by lichstam** [comment]
Same problem here

**Comment by thymikee** [comment]
Fix incoming: https://github.com/react-native-community/react-native-cli/pull/226.

**Comment by lichstam** [comment]
Wow, that was quick :), thanks man

**Comment by thymikee** [comment]
Released a patch, so the fix is available for everybody 🙂

**Comment by SaraChicaD** [comment]
THANK Y'ALL SO MUCH!
