### ISSUE TITLE
How to wrap the react-native <picker /> for the lengthy item text? 

### ISSUE THREAD

**Issue by ashwithags** [facebook/react-native#23887]
## 🐛 Bug Report

I have designed a picker using react native-base, and I'm trying to style it using styles.XML BUT its not working. I want my drop down items to wrap in second line when the length of the text exceeds the width.

## Current Behavior

![image](https://user-images.githubusercontent.com/22570626/54264395-081de300-4599-11e9-885c-132168f5c01b.png)

## Expected Behavior

instead of dots text should come to next line 
![image](https://user-images.githubusercontent.com/22570626/54264613-811d3a80-4599-11e9-879a-ab12bc9483a1.png)

## Code Example
    class PickerExample extends Component {
    state = {link: ''}
    updateLink = (link) => {
      this.setState({ link: link })
    }
    render() {
      return (
         <View>
            <Picker selectedValue = {this.state.link} onValueChange = {this.updateLink}>
               <Picker.Item label = "25 best small-business apps in 2018 - nerdwallet" value = "one" />
               <Picker.Item label = "Top business apps, best apps for small business" value = "two" />
               <Picker.Item label = "Collaboration & productivity apps for business" value = "three" />
            </Picker>
            <Text style = {styles.text}>{this.state.link}</Text>
         </View>
       )
    }
    }
    export default PickerExample;

## Styles.xml

<resources>
    
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="android:spinnerItemStyle">@style/SpinnerItem</item>
        <item name="android:spinnerDropDownItemStyle">@style/SpinnerDropDownItem</item>
    </style>

    <style name="SpinnerItem" parent="Theme.AppCompat.Light.NoActionBar">>
        <item name="android:fontFamily">segoe-ui</item>
    </style>

    <style name="SpinnerDropDownItem" parent="Theme.AppCompat.Light.NoActionBar">>
        <item name="android:layout_width">fill_parent</item>
        <item name="android:layout_height">wrap_content</item>   
        <item name="android:singleLine">false</item>
    </style>

</resources>

## Environment

  Environment:
  OS: Windows 10
  Node: 11.9.0
  Yarn: 1.13.0
  npm: 6.5.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5314842

Packages: (wanted => installed)
  react: 16.3.2 => 16.3.2
  react-native: 0.59.0 => 0.59.0

**Comment by thymikee** [comment]
Since this issue is about a Native Base component, please file this issue in native-base repository: https://github.com/GeekyAnts/NativeBase/issues/new. Thanks!

**Comment by PavanKumar-sa** [comment]
React Native 0.60.3 still issue exists in android and picker text doesn't get wrapped to next line. Any fixes for this? iOS works fine.
