### ISSUE TITLE
INSTALLATION SUCCEEDED but Application is not installed on iPhone 6 plus

### ISSUE THREAD

**Issue by ananth10** [facebook/react-native#23894]
Hi , I have tried to install application using "react-native run-ios --device --udid *********************640b". i got log that says Installation INSTALLATION SUCCEEDED but application is not installed on iPhone. anyone have a idea?

**Technical details**

WebStorm: 2018.2

React:16.6.3

React-Native:0.58.3

**Log:**

** BUILD SUCCEEDED **

The following commands produced analyzer issues:
        Analyze /Users/w***/WebstormProjects/app/node_modules/react-native/React/Base/RCTModuleMethod.mm normal arm64
        Analyze /Users/w****/WebstormProjects/app/node_modules/react-native/Libraries/Image/RCTImageCache.m normal arm64
        Analyze /Users/w*****/WebstormProjects/app/node_modules/react-native/Libraries/Network/RCTNetInfo.m normal arm64
(3 commands with analyzer issues)

installing and launching your app on iPhone ...
** INSTALLATION SUCCEEDED **

**Comment by VoroshilovMax** [comment]
The same problem in iPhone 6s
iOS 12.1.4

```
{
  "name": "maya",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "immutability-helper": "^3.0.0",
    "lodash": "^4.17.11",
    "react": "16.6.3",
    "react-native": "0.58.5",
    "react-native-blur": "^3.2.2",
    "react-native-document-scanner": "^1.4.2",
    "react-native-elements": "^1.1.0",
    "react-native-fbsdk": "^0.8.0",
    "react-native-firebase": "^5.2.3",
    "react-native-gesture-handler": "^1.1.0",
    "react-native-google-signin": "^1.2.1",
    "react-native-image-picker": "^0.28.0",
    "react-native-linear-gradient": "^2.5.3",
    "react-native-vector-icons": "^6.3.0",
    "react-native-walkthrough-tooltip": "^0.5.0",
    "react-navigation": "^3.3.2",
    "react-redux": "^6.0.1",
    "redux": "^4.0.1",
    "save": "^2.3.3"
  },
  "devDependencies": {
    "babel-core": "7.0.0-bridge.0",
    "babel-jest": "24.1.0",
    "jest": "24.1.0",
    "metro-react-native-babel-preset": "0.52.0",
    "react-test-renderer": "16.6.3"
  },
  "jest": {
    "preset": "react-native"
  },
  "rnpm": {
    "assets": [
      "./assets/fonts/"
    ]
  }
}
```

```


** BUILD SUCCEEDED **



The following commands produced analyzer issues:
        Analyze /Users/macbook/Documents/freelance/react-native/maya/node_modules/react-native/React/Base/RCTModuleMethod.mm normal arm64
        Analyze /Users/macbook/Documents/freelance/react-native/maya/node_modules/react-native/Libraries/Image/RCTImageCache.m normal arm64
        Analyze /Users/macbook/Documents/freelance/react-native/maya/node_modules/react-native/Libraries/Network/RCTNetInfo.m normal arm64
(3 commands with analyzer issues)

installing and launching your app on iPhone Макс...
** INSTALLATION SUCCEEDED **
```
```

┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│  Running Metro Bundler on port 8081.                                         │
│                                                                              │
│  Keep Metro running while developing on any JS projects. Feel free to        │
│  close this tab and run your own Metro instance if you prefer.               │
│                                                                              │
│  https://github.com/facebook/react-native                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

Looking for JS files in
   /Users/macbook/Documents/freelance/react-native/maya 

Loading dependency graph, done.
```

The application opened for a few seconds and then closed.
Launched via Xcode.  The app is started but does not connect to hot reload.
And bunch of errors in console.

**Comment by MickaelNeves** [comment]
I had the same problem this morning, when i tried to send to my iPod. 
After some digging, I realized my signing process was all messed out. I had my provisioning distribution selected instead of development. 

If you're signing your ipa file using an AppStore certificate, you can't install it directly on your iPhone without passing through Apple's review or AppStore first.
You can sign your release app with an Ad-Hoc certificate and test into a limited number of devices without passing through AppStore.

Anyway, for develop just make sure you have a iOS Development Provisioning selected.

**Comment by jedashford** [comment]
Same here for us, we've tried multiple computers and mutliple iOS devices on multiple iOS OS versions and none install. We always get a 'info Installing and launching your app on devphone' at the end and indicates its been installed, but no app on the device, ever.
