### ISSUE TITLE
Attempted to invoke `1` (method ID) on `RedBox` (NativeModule name) with an invalid bridge

### ISSUE THREAD

**Issue by Steffi3rd** [facebook/react-native#23909]
I always as this warning on save file (CMD+S)

But it disappears on CMD+R.

Where does it come from ? What is RedBox ? 

<img width="498" alt="Capture d’écran 2019-03-13 à 20 34 02" src="https://user-images.githubusercontent.com/814410/54309161-e55af100-45cf-11e9-9af9-5b6a9fbfdda8.png">

<img width="498" alt="Capture d’écran 2019-03-13 à 20 38 43" src="https://user-images.githubusercontent.com/814410/54309238-07ed0a00-45d0-11e9-815c-82ab8a335a09.png">

**Comment by Steffi3rd** [comment]
This message doesn't appear anymore by **Disable Hot Reloading.**

**Comment by muganwas** [comment]
Disabling Hot reloading doesn't fix it for me.
