### ISSUE TITLE
0.59 release apk do not show Local Image Resources

### ISSUE THREAD

**Issue by Mikelulu** [facebook/react-native#23904]
React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
      Memory: 17.46 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.14.2 - ~/.nvm/versions/node/v10.14.2/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.14.2/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 22, 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.3, 25.0.3, 26.0.1, 26.0.2, 27.0.1, 27.0.3, 28.0.3
        System Images: android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.0 => 0.59.0
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by Mikelulu** [comment]
![image](https://user-images.githubusercontent.com/19161230/54293570-2ad8e780-45eb-11e9-86be-b19239d178ac.png)

**Comment by dulmandakh** [comment]
@Mikelulu could you please provide sample?

**Comment by cpojer** [comment]
Unfortunately we cannot fix an issue without a proper bug report. Happy to reopen if you provide a repository that shows the issue or even better, please send a Pull Request with the fix.
