### ISSUE TITLE
Fetch caches result even with cache: 'no-store' supplied

### ISSUE THREAD

**Issue by WithGJR** [facebook/react-native#23905]
## 🐛 Bug Report
I noticed Fetch caches data sometimes, and sometimes it doesn't.

I'm sure the data returned by server has been changed. (I've checked that fact using browser)

## To Reproduce

Copy the code in the 'Code Example' section.

## Expected Behavior

If the data returned by server has changed, and  cache: 'no-store' has been supplied, it shouldn't cache the result.

## Code Example

fetch(url, {
    method: 'GET',
    cache: 'no-store'
 });

## Environment

info 
  React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: (4) x64 Intel(R) Core(TM) i5-3427U CPU @ 1.80GHz
      Memory: 59.77 MB / 4.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.1 - /usr/local/opt/nvm/versions/node/v8.11.1/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 24, 26, 27, 28
        Build Tools: 23.0.1, 24.0.0, 26.0.3, 27.0.3, 28.0.3
        System Images: android-21 | Google APIs Intel x86 Atom_64, android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.0 => 0.59.0 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

**Comment by shufengwu5946** [comment]
Has the problem been solved? 
I also had similar problems.
This problem occurs when the version is higher than 0.57.8.
Fetch caches result even with cache: 'no-store' supplied.
Thanks.
@react-native-bot @WithGJR
