### ISSUE TITLE
Fabric: Race condition when using RCTFabricSurfaceHostingProxyRootView

### ISSUE THREAD

**Issue by ericlewis** [facebook/react-native#23910]
## 🐛 Bug Report

When attempting to use `RCTFabricSurfaceHostingProxyRootView` the application crashes when the surface is asked to start before the bridge has finished loading. Note, that I sometimes get a red screen instead, saying _fbBatchedBridge couldn't be found, it's "random". It is also pretty clear to me that the runtime pointer is null when this happens. Stack trace below:

![stack trace](https://imgur.com/dCjgQ4e.png)

## To Reproduce

- Follow the directions to run on https://github.com/facebook/react-native/pull/23803
- Comment out the code in `Swizzle_RCTFabricSurface.m` 
- remove the `RCTJavaScriptDidLoadNotification` observer in `AppDelegate.m`
- Open workspace, run app, observe error.

## Expected Behavior

`RCTFabricSurfaceHostingProxyRootView` to wait for the bridge to fully load before starting the surface.

## Code Example

https://github.com/facebook/react-native/pull/23803. Hopefully my swizzle / hack code can be of help in proper solution!

## Environment

N/A? This is RNTester.

**Comment by ericlewis** [comment]
cc @fkgozali

**Comment by fkgozali** [comment]
we’re tracking this internally and will investigate in a few weeks

**Comment by fkgozali** [comment]
These 2 commits should fix the issues:
* null `Runtime`: https://github.com/facebook/react-native/commit/b312543d3cc005dc1548775d455848f19719c57a (this is actually a workaround, not an ideal fix)
* Missing `__fbBatchedBridge`:
https://github.com/facebook/react-native/commit/6aa896896f0cf6bf3f7617d980b105c5f8770f56

**Comment by fkgozali** [comment]
Please re-open if the issue still exists.
