### ISSUE TITLE
How to create a component with customizable animation?

### ISSUE THREAD

**Issue by jozan** [facebook/react-native#2392]
Some context: I have a component which is animated when it mounts. The component's animation can be changed by giving it props `animation` and `animationStyle`. The component also has default animation. I tried `defaultProps` but it's not possible use state there.

Example component which illustrates what I'm trying to do:
```js
var React = require('react-native');

var {
  Animated,
  StyleSheet,
  Text,
  View,
} = React;

var styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center'
  }
});

class Circle extends React.Component {

  componentDidMount() {
    // Run animation immediately after mounting
    this.props.animation.bind(this)();
  }

  render() {
    return (
      <Animated.View style={[styles.container, this.props.animationStyle]}>
        
      </Animated.View>
    );
  }
};

// This is in quite strange place, outside of the component
var circleAnimation = function() {
  this.state.bounceValue.setValue(.5);
  Animated.spring(this.state.bounceValue, {
    toValue: 1,
    friction: 3,
  }).start();
}

Circle.propTypes = {
  animation: React.PropTypes.func,
  animationStyle: React.PropTypes.object
};

Circle.defaultProps = {
  animation: circleAnimation, // Animation function
  animationStyle: {transform: [{scale: this.state.bounceValue}]} // Fail...
};
```

**Comment by browniefed** [comment]
@jozan this still an issue for you?
You can't reference `this.state` in default props since defaultProps object is used for every instance of something.
If you need specific help, well let me know on slack :)

@brentvatne

**Comment by jozan** [comment]
Thanks for the answer! I wanted to know how to customize animation (f.e. easings) but I gave up on this since it was only an experiment. I'll close this for now.

:baby_chick:
