### ISSUE TITLE
Screen Recoding

### ISSUE THREAD

**Issue by KirtiN10** [facebook/react-native#23930]
## 🐛 Bug Report
I am trying to implement screen recording but NodeModules object is coming blank

## To Reproduce
import {NativeModules} from 'react-native';
const { RecorderManager } = NativeModules;

console.log(NativeModules) - object {} (i.e. blank object)

## Expected Behavior
NativeModules object should have RecorderManager.

**Comment by hramos** [comment]
^ In case you're wondering why the bot added that, it's due to the missing Environment section. Can you edit that in? You can run `react-native info` to get the information we need.

**Comment by orta** [comment]
This looks like a bug with your installation of https://github.com/ycswaves/react-native-screen-recorder
