### ISSUE TITLE
UIExample - Animated crashes on load

### ISSUE THREAD

**Issue by martco** [facebook/react-native#2393]
When I tap the Animated example I see the following crash:

![anim](https://cloud.githubusercontent.com/assets/420959/9402314/c04756ec-4790-11e5-8299-9ffedd506625.gif)

Using latest `iojs`, upgraded `watchman` and `flow`. Just pulled from master.

**Comment by ide** [comment]
Thanks for the report; cc @sahrens

**Comment by martco** [comment]
fwiw I see this error here too: http://www.reactnative.com/uiexplorer/

![animated](https://cloud.githubusercontent.com/assets/420959/9648589/1d451128-519f-11e5-8575-1ea175533d7c.gif)

**Comment by sahrens** [comment]
I saw this awhile ago but I think it's fixed - can you try updating and see
if it still repros?

**Comment by ide** [comment]
Just verified that the animation example works without issue on master.

**Comment by martco** [comment]
thanks! @ide
