### ISSUE TITLE
Missing piece in upgrade guide to 0.59

### ISSUE THREAD

**Issue by mehulmpt** [facebook/react-native#23949]
Local development builds fail with `targetSdkVersion` 28 because starting from Android 9, clearText support is disabled (https://developer.android.com/training/articles/security-config#CleartextTrafficPermitted). It is not mentioned anywhere in the docs, maybe we could include it somewhere?

To make sure the app is able to communicate with metro bundler, you need to add `android:usesCleartextTraffic="true"` to your AndroidManifest.xml file so it should finally look something like:

```xml
 <application
      android:name=".MainApplication"
      //...
      android:icon="@mipmap/ic_launcher"
	  android:usesCleartextTraffic="true" <-- add this
    // ....
>

```

If you don't add this, your app would build and launch but would fail with the following screen:

![error](https://user-images.githubusercontent.com/10388889/54428935-17419400-4745-11e9-8d8c-2031a42cb689.jpeg)

**Comment by ehsan680** [comment]
Throws the same error for me even after adding `android:usesCleartextTraffic="true"`in AndroidManifest.xml

**Comment by mehulmpt** [comment]
@ehsan680 did you rebuild the app?

**Comment by Salakar** [comment]
Hey all 👋 this was documented here: https://facebook.github.io/react-native/docs/integration-with-existing-apps#network-security-config-api-level-28 (android tab) 

I'll close this for now but I'll see if I can get this added to the release notes/upgrade guide also.
