### ISSUE TITLE
Discussion: 

### ISSUE THREAD

**Issue by PareshPatel721** [facebook/react-native#23945]
Hello Guys i just started to learn about React Native.
Mac OS Mojave (10.14)
Xcode 10.1

node --version -> v11.10.0
npm --version -> 6.7.0
react-native --version
react-native-cli: 2.0.1
react-native: 0.59.1
yarn --version -> 1.13.0
I enter below command in my terminal

react-native init reactTutorialApp
then cd reactTutorialApp
then react-native run-ios
I also tried it with run from xcode

i also did

./configure for glog-0.3.5 file
I am getting error like below.

/configure👎 in `/Users/pareshpatel/Desktop/ReactNativeDemos/reactTutorialApp/node_modules/react-native/third-party/glog-0.3.5':

/configure👎 C compiler cannot create executables

Command PhaseScriptExecution emitted errors but did not return a nonzero exit code to indicate failure

/Users/pareshpatel/Desktop/ReactNativeDemos/reactTutorialApp/node_modules/react-native/third-party/folly-2018.10.22.00/folly/detail/RangeCommon.h:22:10: 'glog/logging.h' file not found

Waiting for help.

**Comment by CatapultJesse** [comment]
inside the project folder try:
```
yarn install
cd ios
pod install
cd ..
react-native run-ios
```

Questions like this are better suited for the reactiflux discord channel (https://www.reactiflux.com/)

**Comment by PareshPatel721** [comment]
yarn install
yarn install v1.13.0
[1/4] 🔍  Resolving packages...
success Already up-to-date.
cd ios
pod install

> inside the project folder try:
> 
> ```
> yarn install
> cd ios
> pod install
> cd ..
> react-native run-ios
> ```
> Questions like this are better suited for the reactiflux discord channel (https://www.reactiflux.com/)

I did the same steps as you mentioned, but it didn't work.
yarn install
yarn install v1.13.0
[1/4] 🔍  Resolving packages...
success Already up-to-date.
cd ios
pod install
[!] No `Podfile' found in the project directory.

**Comment by ajijoyo** [comment]
hey, did u resolve this issue? I have the same issue

**Comment by talebkhah** [comment]
> Hello Guys i just started to learn about React Native.
> Mac OS Mojave (10.14)
> Xcode 10.1
> 
> node --version -> v11.10.0
> npm --version -> 6.7.0
> react-native --version
> react-native-cli: 2.0.1
> react-native: 0.59.1
> yarn --version -> 1.13.0
> I enter below command in my terminal
> 
> react-native init reactTutorialApp
> then cd reactTutorialApp
> then react-native run-ios
> I also tried it with run from xcode
> 
> i also did
> 
> ./configure for glog-0.3.5 file
> I am getting error like below.
> 
> /configure👎 in `/Users/pareshpatel/Desktop/ReactNativeDemos/reactTutorialApp/node_modules/react-native/third-party/glog-0.3.5':
> 
> /configure👎 C compiler cannot create executables
> 
> Command PhaseScriptExecution emitted errors but did not return a nonzero exit code to indicate failure
> 
> /Users/pareshpatel/Desktop/ReactNativeDemos/reactTutorialApp/node_modules/react-native/third-party/folly-2018.10.22.00/folly/detail/RangeCommon.h:22:10: 'glog/logging.h' file not found
> 
> Waiting for help.

hi 
exactly I have this problem.
did you resolve it?

**Comment by talebkhah** [comment]
> Hello Guys i just started to learn about React Native.
> Mac OS Mojave (10.14)
> Xcode 10.1
> 
> node --version -> v11.10.0
> npm --version -> 6.7.0
> react-native --version
> react-native-cli: 2.0.1
> react-native: 0.59.1
> yarn --version -> 1.13.0
> I enter below command in my terminal
> 
> react-native init reactTutorialApp
> then cd reactTutorialApp
> then react-native run-ios
> I also tried it with run from xcode
> 
> i also did
> 
> ./configure for glog-0.3.5 file
> I am getting error like below.
> 
> /configure👎 in `/Users/pareshpatel/Desktop/ReactNativeDemos/reactTutorialApp/node_modules/react-native/third-party/glog-0.3.5':
> 
> /configure👎 C compiler cannot create executables
> 
> Command PhaseScriptExecution emitted errors but did not return a nonzero exit code to indicate failure
> 
> /Users/pareshpatel/Desktop/ReactNativeDemos/reactTutorialApp/node_modules/react-native/third-party/folly-2018.10.22.00/folly/detail/RangeCommon.h:22:10: 'glog/logging.h' file not found
> 
> Waiting for help.


the solution that worked for me was:
make sure your xcode name without space you can check using xcode-select -p

nothing more just remove space.

thanks @ajijoyo
