### ISSUE TITLE
glog/logging.h' file not found

### ISSUE THREAD

**Issue by PareshPatel721** [facebook/react-native#23944]
Hello Guys i just started to learn about React Native.
Mac OS Mojave (10.14)
Xcode 10.1
-  node --version -> v11.10.0
- npm --version -> 6.7.0
- react-native --version
'react-native-cli: 2.0.1
react-native: 0.59.1
- yarn --version -> 1.13.0

I enter below command in my terminal
-  react-native init reactTutorialApp
then cd reactTutorialApp
- then react-native run-ios

I also tried it with run from xcode

i also did 
- ./configure for glog-0.3.5 file
I am getting error like below.
- /configure:-1: in `/Users/pareshpatel/Desktop/ReactNativeDemos/reactTutorialApp/node_modules/react-native/third-party/glog-0.3.5':

- /configure:-1: C compiler cannot create executables

- Command PhaseScriptExecution emitted errors but did not return a nonzero exit code to indicate failure

- /Users/pareshpatel/Desktop/ReactNativeDemos/reactTutorialApp/node_modules/react-native/third-party/folly-2018.10.22.00/folly/detail/RangeCommon.h:22:10: 'glog/logging.h' file not found

Waiting for help.

**Comment by lucianokrebs** [comment]
Same issue here. Any news?

**Comment by aklein13** [comment]
In my case it was cause by manually interrupting the first `react-native run-ios` run and then running it again.

I resolved this with `rm -rf ./node_modules && yarn && react-native run-ios`.

**Comment by ajijoyo** [comment]
> Same issue here. Any news?

did you resolve?
I have some issue


even I trying this not working too
> In my case it was cause by manually interrupting the first `react-native run-ios` run and then running it again.
> 
> I resolved this with `rm -rf ./node_modules && yarn && react-native run-ios`.

<details>
<summary>React Native Environment Info</summary>
<p>

```
React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 70.13 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.9.0 - /usr/local/Cellar/node/10.9.0/bin/node
      npm: 6.7.0 - ~/.npm-packages/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.2, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.0, 28.0.3
        System Images: android-23 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.3 => 16.8.6 
      react-native: ^0.59.9 => 0.59.9 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```
</p>
</details>

**Comment by VitorBrangioni** [comment]
Same problem, any solution?

**Comment by gurjindersinghkhalsa** [comment]
Same issue. Any Solution?

**Comment by ajijoyo** [comment]
just try `./configure && make && make install` on glog directory
and make sure your xcode name without space you can check using `xcode-select -p`
I face issue beacuse i have xcode name with space and it `make install` failure

**Comment by lucianokrebs** [comment]
hey @VitorBrangioni @ajijoyo, I've added this to my package.json scripts section:

```
"ios:start": "cd node_modules/react-native/scripts && sudo ./ios-install-third-party.sh && cd third-party/glog-0.3.5/ && sudo ./configure && sudo ../../../scripts/ios-configure-glog.sh && cd ../../../../../ && sudo react-native run-ios --simulator \"iPhone 6s\""
```

You may have to adapt to your glog version (mine is 0.3.5)

**Comment by talebkhah** [comment]
> in my case `./configure && make && make install` on glog directory
> and make sure your xcode name without space you can check using `xcode-select -p`
> I face issue beacuse i have xcode name with space and it `make install` failure

That's Right.

the solution that worked for me was: 
make sure your xcode name without space you can check using xcode-select -p

nothing more just remove space.

thanks @ajijoyo

**Comment by cinder92** [comment]
having this issue with a brand new project using Xcode 10.3, any help?

**Comment by thisisablock** [comment]
https://github.com/facebook/react-native/issues/22703#issuecomment-527234154

**Comment by loveaurellu** [comment]
This happened to me while trying out a new xcode version. I named the new xcode application "Xcode 11" and put it beside the old one. This caused the problem for me.

Naming the new one (Xcode 11) "Xcode" and removing the old one from the Application folder resolved the issue.

**Comment by bitcrumb** [comment]
Hmm... hitting the same error. I am indeed also trying to build using Xcode that is named differently.

**Comment by cotispear** [comment]
Yep @loveaurellu that's _exactly_ what I did.

**Comment by lincolnbf** [comment]
@loveaurellu thanks, it solved! o/
