### ISSUE TITLE
Discussion: How to run shell/Command Line Program/Native Executable  in My RN app？

### ISSUE THREAD

**Issue by hugetiny** [facebook/react-native#23946]
1.Can I run a background Command Line Program（binary program） for my RN app?
2.Does RN support node.js to do some background task in my app(not server)?

**Comment by cpojer** [comment]
Please note this issue tracker is not a help forum (as stated in issue template).

We recommend using [StackOverflow](https://stackoverflow.com/questions/ask) where there are community incentives to help others or our [Discord channel](https://discord.gg/Xs5Xbjr) for questions.
