### ISSUE TITLE
[fetch] how to set fetch's timeout ?

### ISSUE THREAD

**Issue by hufeng** [facebook/react-native#2394]
dear all,

how to set fetch's timeout ?

**Comment by simondelacourt** [comment]
Found this;

{
    method: 'GET'
    , headers: {}     // request header, format {a:1} or {b:[1,2,3]}
    , follow: 20      // maximum redirect count, 0 to not follow redirect
    , timeout: 0      // req/res timeout in ms, 0 to disable, timeout reset on redirect
    , compress: true  // support gzip/deflate content encoding, false to disable
    , size: 0         // maximum response body size in bytes, 0 to disable
    , body: empty     // request body, can be a string or readable stream
    , agent: null     // custom http.Agent instance
}

as options for  https://github.com/bitinn/node-fetch

Maybe worth trying, as far as I know the react native fetch is based on the default fetch api, so this might work..

**Comment by brentvatne** [comment]
dupe #2556

**Comment by adambene** [comment]
@simondelacourt RN uses whatwh-fetch runtime so there is no timeout by default. I have a workaround (whatwg-fetch-timeout package): https://github.com/facebook/react-native/issues/2556#issuecomment-282876518

I am really curious about how you enthusiast RN users out there build robust apps without having timeout and abort().

**Comment by mrbarde** [comment]
This answer was quite helpful, worked like a charm.
[Answer](https://github.com/matthew-andrews/isomorphic-fetch/issues/48#issuecomment-218841437)

**Comment by adambene** [comment]
@mrbarde It does not abort the pending HTTP request.

**Comment by mrbarde** [comment]
@adambene yh it doesn't and that's a pain in the neck, I just use it so I can update my UI for the user.

**Comment by adambene** [comment]
@mrbarde Yeah, agree.

**Comment by Tom29** [comment]
@adambene do you know what's difference between native fetch vs `node-fetch`?

**Comment by Tom29** [comment]
@simondelacourt it doesn't work with react

**Comment by WardianGames** [comment]
I would enclose my fetch requests with async functions or promises. Then set a timeout, on the parent if the promise has not returned by the time the timeout does, stop waiting for it to return and move on.

**Comment by adambene** [comment]
@WardianGames it is okay for get methods but in the case of post it would be essentisl to be able to abort the pending request after a given timeout.

**Comment by sebringj** [comment]
I'm doing a hack with XmlHTTPRequest and return it on the returned request with the "abort" method. The calling code can then assign itself there request and abort it later. Not elegant but works.
```
if (this.request) this.request.abort()
this.request = someApiCall(data)
await request
```
where **this.request** is held on to and aborted if more requests are made. Still experimenting with this but seems to work for not queuing up too many requests so far.

**Comment by sananddev** [comment]
i am still searching for the solution using fetch and timeout but..... it gets me searching all day
