### ISSUE TITLE
`trackColor.true` has no effect on Android Switch component

### ISSUE THREAD

**Issue by shaundon** [facebook/react-native#23956]
## 🐛 Bug Report

The switch component has a `trackColor` prop with `true` and `false` props within, to change the colour of the track when the switch is enabled and disabled respectively. It appears that `trackColor.true` has no effect on Android, and the track is always set to blue instead.

## To Reproduce

Use `trackColor.true` on a Switch component on Android.

## Expected Behavior

I expect the switch's track to change colour to match the props passed in.

## Code Example

```
<Switch 
    thumbColor="red" 
    trackColor={{
        true: "yellow",
        false: "purple",
    }} 
/>
```

<img width="105" alt="enabled" src="https://user-images.githubusercontent.com/73652/54446824-caa78a00-473f-11e9-804b-afbedb06b1a4.png">

Here's a test repo I made to showcase the issue: https://github.com/shaundon/switchdemo

## Environment

```
  React Native Environment Info:
    System:
      OS: macOS 10.14.1
      CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 91.06 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.13.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 21, 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.0, 26.0.1, 26.0.2, 27.0.3, 28.0.3
        System Images: android-21 | Google APIs Intel x86 Atom, android-24 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.1 => 0.59.1
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
```

**Comment by shaundon** [comment]
I can try to take a look at this myself but I'm not great with Android..

**Comment by JKCooper2** [comment]
Not reproducible in older versions of RN (https://snack.expo.io/@jkcooper/rn23962-switch-track-color) so may be a newly introduced bug

**Comment by shaundon** [comment]
It's possible that this is fixed in https://github.com/facebook/react-native/pull/23977/files - I'll try it soon and check.

**Comment by dulmandakh** [comment]
@shaundon https://github.com/facebook/react-native/commit/d6ee448e15a25a7485482a4702aadb2e396445c7 fixes trackColor persistence, please check that it also fixes this issue. And please feel free to close this issue if resolved. Thank you

**Comment by shaundon** [comment]
I think it does - thanks! 🎉
