### ISSUE TITLE
[ActionSheetIOS] showShareActionSheetWithOptions crashes on iPads for iOS 8+

### ISSUE THREAD

**Issue by isair** [facebook/react-native#2395]
Originally faced this issue in [react-native-activity-view](https://github.com/naoufal/react-native-activity-view). In the issue I created ([#12](https://github.com/naoufal/react-native-activity-view/issues/12)) @chirag04 pointed out that react-native also does not handle the popover presentation controller setup required to be done before showing an activity view controller on iPads for iOS 8+. Basically, a sourceView needs to be assigned before presenting a UIActivityViewController if it has the property popoverPresentationController and its value is not nil. This sourceView is, ideally, the view that a user has interacted with which then resulted in the presentation of the UIActivityViewController.

We can assign the root view controller's view to sourceView and calculate a frame for the sourceFrame I believe. I don't know much about the inner workings of react-native so this is the easiest solution that popped into my mind. My copied and pasted proposed solution from react-native-activity-view:

> I believe we can make the show method accept an optional parameter containing a UI element ref, calculate the screen position and size of the element using [measure](https://github.com/facebook/react-native/blob/master/Libraries/ReactIOS/NativeMethodsMixin.js#L67-L72) on the javascript side, pass those dimensions to the native code as a dictionary, then parse that into a CGRect and assign it to `popoverPresentationController.sourceFrame`. That way we can keep `popoverPresentationController.sourceView = ctrl.view` and show an accurate popover.

Edit: I created a PR for react-native-activity-view with my proposed changes ([#13](https://github.com/naoufal/react-native-activity-view/pull/13/files)).

**Comment by chirag04** [comment]
Thanks @isair for positing it here.

Also, it would be best to deprecate activity-view in favor of actionsheetios. However i see https://github.com/facebook/react-native/issues/1594 as the blocker.

cc @tadeuzagallo

**Comment by chirag04** [comment]
@tadeuzagallo can you share your thoughts on the fix and the proposed api?

**Comment by grabbou** [comment]
It also crashes on iPhone 6 iOS9. Hopefully the above works as well.

**Comment by chirag04** [comment]
@grabbou what is the error? Is it something related to threads?

**Comment by grabbou** [comment]
Generally, tapping on the button that should show the ActionSheet has no effect. When I do it 10 times really quickly and navigate to other component (Navigator), animation slows down at least 3 times.

After a couple of seconds, it finally appears but it's completely blank. When I e.g. tap on it, an icon shows. So generally, looks like a glitch, when I click in 10 times in random places, it renders OK.

**Comment by chirag04** [comment]
@grabbou would you have the crash log for this? If no would you mind replicating it once and pasting the crash log here?

**Comment by grabbou** [comment]
Sorry for false alert, it turned out it was a 3rd party library, not a native ActionSheet I was using.

**Comment by chirag04** [comment]
Ah ok. No problem. Thanks
