### ISSUE TITLE
about the use of ImageEditor.cropImage

### ISSUE THREAD

**Issue by liangguohun** [facebook/react-native#23957]
## To Reproduce

I use the react-native-camera take a photo,
and then i use ImageEditor.cropImage to crop the photo for id card part,
i just set cropData with offset size but ,i always get the target height but the width can't cut off

version: 0.52.0
phone android 9
## Expected Behavior

just  crop the target Rect .

**Comment by bartolkaruza** [comment]
Hi @liangguohun, thanks for reporting this issue. I'm closing it as you seem to have resolved your initial problem/question. You remaining question looks more suited for Stackoverflow, but let me know if I interpreted it wrong.
