### ISSUE TITLE
EXC_BAD_ACCESS RCTModuleMethod.mm

### ISSUE THREAD

**Issue by MarkAMcCorkle** [facebook/react-native#23950]
## 🐛 Bug Report
Line 456 crashes during iOS build. EXC_BAD_ACCESS 
**com.facebook.react.JavaScript (7): EXC_BAD_ACCESS (code=1, address=0x1a1e6887e00)**

## To Reproduce
Just build the project for iOS from Xcode

## Expected Behavior
No crash, app should continue building

## Code Example
```
- (const char *)JSMethodName
{
  NSString *methodName = _JSMethodName;
  if (!methodName) {
    const char *jsName = _methodInfo->jsName;
*456 HERE*    if (jsName && strlen(jsName) > 0) {
      methodName = @(jsName);
    } else {
      methodName = @(_methodInfo->objcName);
      NSRange colonRange = [methodName rangeOfString:@":"];
      if (colonRange.location != NSNotFound) {
        methodName = [methodName substringToIndex:colonRange.location];
      }
      methodName = [methodName stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceAndNewlineCharacterSet]];
      RCTAssert(methodName.length, @"%s is not a valid JS function name, please"
                " supply an alternative using RCT_REMAP_METHOD()", _methodInfo->objcName);
    }
    _JSMethodName = methodName;
  }
  return methodName.UTF8String;
}
```

## Environment
  React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
      Memory: 693.45 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.10.1 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 21, 22, 24, 25, 26, 27, 28
        Build Tools: 26.0.1, 27.0.1, 27.0.3, 28.0.3
        System Images: android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.4 => 16.8.4 
      react-native: ^0.59.1 => 0.59.1 
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by rickhanlonii** [comment]
Hey @MarkAMcCorkle thanks for filing. Unfortunately this isn't actionable without a repro case - if you can post a repo we can reopen and take a look

**Comment by OrangeFlavoredColdCoffee** [comment]
![image](https://user-images.githubusercontent.com/15223345/56861939-6df2ec80-69d8-11e9-9682-4f1793b4ca28.png)

![image](https://user-images.githubusercontent.com/15223345/56861941-7519fa80-69d8-11e9-8875-4d78e1b3c82d.png)

hi，I have the same problem，can you tell me  how you fix this？

**Comment by hpelitebook745G2** [comment]
@rickhanlonii This happened to me as well when setting up fresh project with cocoa pods. Here's my podfile:

    
    platform :ios, '9.0'

    project 'boilerplate', 'Staging' => :debug

    target 'boilerplate' do
      rn_path = '../node_modules/react-native'

      use_frameworks!

      pod 'yoga', path: "#{rn_path}/ReactCommon/yoga"
      pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
      pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"
      pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
      pod 'React', path: rn_path, subspecs: [
        'Core',
        'CxxBridge',
        'DevSupport',
        'RCTActionSheet',
        'RCTAnimation',
        'RCTGeolocation',
        'RCTImage',
        'RCTLinkingIOS',
        'RCTNetwork',
        'RCTSettings',
        'RCTText',
        'RCTVibration',
        'RCTWebSocket',
      ]

      pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
      pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

    end

While here's my Build Phase (Linked automatically):
<img width="894" alt="Screen Shot 2019-06-04 at 2 11 47 PM" src="https://user-images.githubusercontent.com/27658429/58855480-bfc31c80-86d2-11e9-856c-42d7efa523d2.png">

Version:
`React Native: 0.59.8`

I also tried to create another fresh project but without cocoapods and it worked without problems. Is there any setup done for cocoapods to work?

**Comment by FansPro** [comment]
@hpelitebook745G2 have you fix it?

**Comment by ShubhamWebdesk** [comment]
@FansPro have you fixed it? Did anyone fix it?
