### ISSUE TITLE
Regression: Debugger stacktrace shows wrong source file

### ISSUE THREAD

**Issue by hypest** [facebook/react-native#23955]
## 💥 Regression Report
Debugger stops at a `debugger` statement but the source file shown is wrong.

## Last working version

Worked up to version: `v0.58.6`

Stopped working in version: `v0.59.0`, still happening in `v0.59.1`

## To Reproduce

1. Create a new demo app via `react-native init rn059 --version react-native@0.59.1`
2. Add a `debugger` statement in the beginning of the `render()` method in `App.js`
3. Launch the app on Android `react-native run-android`
4. Enable debug mode via the in-app debug menu "Debug JS Remotely"
5. Notice the debugger coming up and stopping somewhere that doesn't look like the App.js file. In my case, the debugger stops at file:line `ReactFabric-prod.js:7030`

## Expected Behavior

In step No5 above, the debugger should stop in file `App.js`, right at the beginning of the `render()` method where the `debugger;` statement is.

## Code Example

Link to repo with example code: https://github.com/hypest/rn-059-stacktrace-mess-demo-app

## Environment

```
$ react-native info
info
  React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
      Memory: 607.81 MB / 32.00 GB
      Shell: 4.4.19 - /usr/local/bin/bash
    Binaries:
      Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
      Yarn: 1.10.1 - ~/.nvm/versions/node/v8.11.3/bin/yarn
      npm: 6.3.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
      Android SDK:
        API Levels: 23, 26, 27, 28
        Build Tools: 19.1.0, 23.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.2, 28.0.3
        System Images: android-23 | Google APIs Intel x86 Atom_64, android-26 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64
    IDEs:
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.1 => 0.59.1
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-create-library: 3.1.2
      react-native-git-upgrade: 0.2.7
```

**Comment by yurykorzun** [comment]
After updating to 0.59.1, I can't debug properly on my Windows machine, it looks like produced source maps are all messed up. Still works on my Mac though.

**Comment by yurykorzun** [comment]
Probably related #6946

**Comment by oferRounds** [comment]
Experiencing this also

**Comment by kelset** [comment]
Thanks @yurykorzun for the investigation! Copying here for relevance:

> The metro bundler is producing a wrong source map on Android in 0.59.1 and 0.59.0. At least it is consistently happening in my React Native project, but works fine on iOS. I tried to disable JS deltas, it doesn't help.

> It could be related to JSC upgrade, but because I don't know how source maps are generated and mapped to running javascript on a device, I don't know exactly what is causing it.

> Metro is using this package for generating a source map npmjs.com/package/source-map

**Comment by kelset** [comment]
It would be better to actually post this issue in the metro repository - can anyone do that? Afterwards we can close this and move the conversation there.

**Comment by yurykorzun** [comment]
> It would be better to actually post this issue in the metro repository - can anyone do that? Afterwards we can close this and move the conversation there.

Done https://github.com/facebook/metro/issues/380

**Comment by kelset** [comment]
Thanks, I've linked it to the Metro team so hopefully a fix will be out soon

**Comment by motiz88** [comment]
This will be fixed by https://github.com/react-native-community/react-native-cli/pull/279.
