### ISSUE TITLE
Disabling pull-to-refresh on FlatList causes all items to be re-created

### ISSUE THREAD

**Issue by maxschmeling** [facebook/react-native#23963]
## 🐛 Bug Report
When disabling pull-to-refresh in a `FlatList` by setting `onRefresh` to `undefined` every item in the list gets unmounted and recreated.

I looked into why this would be happening and it appears to be because of this code in `ScrollView`: https://github.com/facebook/react-native/blob/f741d338406d518c4f81fada723991b2938b8cc5/Libraries/Components/ScrollView/ScrollView.js#L1082-L1120

## To Reproduce
1. Add a `FlatList` with some data and `onRefresh` and `refreshing` set to valid values
2. Change `onRefresh` and `refreshing` to `undefined` 

## Expected Behavior
The item components already rendered should be reused

## Code Example
https://snack.expo.io/@maxschmeling/disrespectful-toffee

## Environment
```
  React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
      Memory: 8.02 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.3.0 - ~/.nvm/versions/node/v11.3.0/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v11.3.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.3 => 16.8.4 
      react-native: ^0.59.0 => 0.59.0 
    npmGlobalPackages:
      react-native-git-upgrade: 0.2.7
```

**Comment by thymikee** [comment]
Hey, we've confirmed this is an issue. I think I have an idea on how to fix it for iOS (we need to move the platform check to the inside of `ScrollViewClass` so we don't re-mount it), but it may get trickier on Android (need to investigate).

I'm gonna work on this later today, but if anyone wants to take a stab at it, please do so :)

**Comment by michalchudziak** [comment]
@thymikee Please correct me if I'm wrong, but with the current implementation of `<ScrollView />` changing any of its props will trigger re-render of the children.

**Comment by michalchudziak** [comment]
While fixing this on iOS seems like a straight-forward job, avoiding unmounting on Android might not be doable without the support of re-parenting in React https://github.com/facebook/react/issues/3965.

[SwipeRefreshLayout](https://developer.android.com/reference/android/support/v4/widget/SwipeRefreshLayout) requires us to wrap the ScrollView with it, and from the React perspective, it will always invalidate the tree.

Perhaps we could always wrap `ScrollView` with `SwipeRefreshLayout`, and conditionally disable it, but it doesn't seem like a good idea.
