### ISSUE TITLE
RNfetchBlob cannot upload video

### ISSUE THREAD

**Issue by ice16** [facebook/react-native#23983]
## 🐛 Bug Report
RNfetchBlob upload video to API failed

## To Reproduce
-> npm install --save rn-fetch-blob
-> react-native link

## Expected Behavior
Can upload video to API

## Code Example
```GaleryPicker = () => {
        ImagePicker.openPicker({
            mediaType: "video",
        }).then((video) => {
            this.setState({
                VideoSource: {uri: video['path']},
                data: video.data,
            });
        }).catch((err) => {

        })
    }
```
```
uploadToServer = () => {
        RNFetchBlob.fetch('POST', 'xxx.xxx.xxx', {
            Authorization: "Bearer access-token",
            otherHeader: "foo",
            'Content-Type': 'multipart/form-data',
        },
        [
            {name: 'video', filename: 'image.png', type: 'image/png', data: this.state.data},
        ]).then((resp) => {
            let Obj = JSON.parse(resp.data);
            let predict = Obj.success;

            Alert.alert(resObj);
        }).catch((err) => {
            console.log(err);
        })
    }
```

## Environment
React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
      Memory: 3.24 GB / 7.87 GB
    Binaries:
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338

**Comment by Titozzz** [comment]
Hello there 👋! Thanks for posting that issue, however, it seems this should be posted directly on the library issues as the code concerned is not part of this repo.

https://github.com/joltup/rn-fetch-blob/issues

I'll close this issue, but if you find something directly related to react-native, feel free to comment and it'll be opened again.
