### ISSUE TITLE
React.Image doesn't support animated GIFs on iOS

### ISSUE THREAD

**Issue by zertosh** [facebook/react-native#24]
Seems like it only shows the first frame. I'm loading http addresses, not local or static image resources - not sure if that makes a difference.

**Comment by wong2** [comment]
does `defaultSource` support GIFs? I tried and it seems not working

**Comment by nicklockwood** [comment]
No, it probably doesn't. I'll file a task to fix that.

**Comment by wong2** [comment]
@nicklockwood thanks, waiting for this

**Comment by wong2** [comment]
@nicklockwood  any updates on this? :smile:

**Comment by Selmanh** [comment]
Is GIF still supported? I am trying to display a GIF as 
```<Image style={styles.bg} source={require('image!sandglass')} />```

PNG works just fine, but I am getting the following error when I try to render animated GIF images in my view:

![screen shot 2015-05-31 at 12 57 11 am](https://cloud.githubusercontent.com/assets/3432700/7901180/00a4f9f2-0730-11e5-9617-791dbb3bf980.png)

Restarting the package manager doesn't help. Any ideas?

**Comment by ide** [comment]
AFAIK remote gifs are supported. Try a URL.

**Comment by nicklockwood** [comment]
Gifs should work for both remote and loca images, but there might be an issue using them with the require() syntax. Try just using the file name (including extension) as the uri value.

**Comment by Selmanh** [comment]
Yea, using uri worked fine, thanks.
```<Image style={styles.gif} source={{ uri: 'test.gif' }} />```

**Comment by magicismight** [comment]
This
`<Image source={{uri: 'load.gif'}} style={{height: 40, width: 40}} />`
will throw an exception in RCTGIFImage.m
`<Error>: ImageIO: CGImageSourceGetType image source parameter is nil`

**Comment by jhabdas** [comment]
Confirming the syntax @Selmanh used  to load a `gif` which is configured in the *Copy Bundle Resources* in Xcode works to load a static, non-network resource.

**Comment by miracle2k** [comment]
Gifs animated fine when read from a URL. If I load the same image locally (via Copy Bundle Resources), it is displayed, but does not animate anymore:

     <Image style={{height: 128, width: 170, marginTop: 20}}
          source={{ uri: 'alphabets-children-5-277623.gif' }} />

**Comment by sudhanshu6247** [comment]
I am having just opposite problem. In my case gif is not getting loaded from url but when I load it from local it works fine.

    <Image style={{maxWidth: deviceWidth-112, resizeMode:'contain', maxHeight: 300}} source={{uri: 'https://s3-ap-southeast-1.amazonaws.com/healthmirdev/channel/gifs/anxiety.gif'}}  />
