### ISSUE TITLE
LayoutAnimation displays black background on view with borderTopRightRadius

### ISSUE THREAD

**Issue by blitzcrank** [facebook/react-native#24004]
## 🐛 Bug Report
A parent view has style={{ overflow: 'hidden', borderTopRightRadius: 5 }}
Inside the parent a child view is rendered with a LayoutAnimation. The surface which is hidden behind the rounded corners has a black background color during the LayoutAnimation

## To Reproduce
Using LayoutAnimation to display a view inside a parent View that has style={{ overflow: 'hidden', borderTopRightRadius: 5 }} on it.
The bug is reproducable with any of the border(Top)(Bottom)(Left)(Right)Radius properties. There is no problem when using borderRadius.

## Expected Behavior
There should be no black background color during the animation.

## Code Example
https://snack.expo.io/@bugreport2/layoutanimation-bug

## Environment
React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
      Memory: 2.49 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.2.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.1 => 0.59.1
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by blitzcrank** [comment]
Bug confirmed on latest version of React Native 0.59.1

**Comment by michalchudziak** [comment]
The issue is reproducible with the latest release (0.59.5)
