### ISSUE TITLE
podspec version out of sync with package.json

### ISSUE THREAD

**Issue by philikon** [facebook/react-native#2401]
This would be pretty trivial to fix, but I'm opening this issue before throwing up a PR to make sure that this doesn't happen again. Is there some sort of automated process that updates the version numbers? Or if it's a manual process, is there a checklist to be updated?

**Comment by philikon** [comment]
cc @vjeux @ide

**Comment by ide** [comment]
It's manual and we keep it up-to-date on the release branches.

**Comment by philikon** [comment]
Oh. My bad. I only looked master. Thanks for clarifying!

**Comment by ide** [comment]
I wish there were a way to keep the version numbers in sync and also up-to-date on the master branch if you have any ideas for how to do that.
