### ISSUE TITLE
Ref creation crash the app

### ISSUE THREAD

**Issue by german970814** [facebook/react-native#24019]
## 🐛 Bug Report

I submmit this issue, because a have not idea why when I declare a ref on my code it does not work and hang the app. There is not a red screen with error traceback, just app does not respond anymore. I don't know if this behaviour is caused by any dependence, but I can bring more information about if is needed.

## To Reproduce

- Just create a ref, for me this is sufficent to crash the whole app

This is my dependencies

    "native-base": "2.11.0",
    "react": "16.6.3",
    "react-native": "0.58.4",
    "react-native-app-intro-slider": "1.0.1",
    "react-native-custom-radio-group": "1.0.1",
    "react-native-gesture-handler": "1.0.15",
    "react-native-image-picker": "0.28.0",
    "react-native-localize": "1.1.0",
    "react-native-modalbox": "1.7.1",
    "react-native-svg": "9.2.3",
    "react-native-vector-icons": "6.2.0",
    "react-navigation": "3.1.5",
    "react-navigation-redux-helpers": "3.0.0",
    "react-redux": "6.0.0",
    "redux": "4.0.1",
    "redux-persist": "5.10.0",
    "redux-thunk": "2.3.0",
    "rn-content-loader": "0.0.2"

## Expected Behavior

I expect that it works properly because sometimes I tried to copy the same way as a third-library implements this behaviour but I was can't, while in the library it works good.

## Code Example

    constructor(props) {
        super(props);
        this.viewRef = null;
    }

    doSomeAction() {
        console.warn(this.viewRef)
    }

    render() {
        return <View ref={component => this.viewRef=component}></View>
    }

## Environment

React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
      Memory: 5.44 GB / 15.88 GB
    Binaries:
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.5.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5264788

**Comment by wbercx** [comment]
Logging a ref out to the console tends to cause a crash. 

What happens when you `console.warn(Object.keys(this.viewRef))`?

**Comment by cpojer** [comment]
See the above comment.
