### ISSUE TITLE
DeviceEventEmitter.removeListener does not work as expected

### ISSUE THREAD

**Issue by vparpoil** [facebook/react-native#24013]
## 🐛 Bug Report
DeviceEventEmitter.removeListener doesn't seem to work

## To Reproduce
In your app, add a Listener and then remove it :
```
DeviceEventEmitter.addListener("event.test", (event)=>{alert("event:test")})
DeviceEventEmitter.removeListener("event.test");
setTimeout(()=>{
      DeviceEventEmitter.emit('event.test', {});
},2000);
```

## Expected Behavior
I would have excepted the "event:test" listener being removed, and hence, no alert being trigerred

## Code Example
https://snack.expo.io/ry6qrSTP4

## Environment
React Native Environment Info:
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.58.4 => 0.58.4 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-create-library: 3.1.2

If it is not a bug, please point me towards the good usage. Thanks !

**Comment by dulmandakh** [comment]
it should work like this

```javascript
let subscription = DeviceEventEmitter.addListener("event.test", (event)=>{alert("event:test")})
subscription.remove()
```

**Comment by vparpoil** [comment]
Thank you !
