### ISSUE TITLE
CameraRoll return lack of information

### ISSUE THREAD

**Issue by truongluong1314520** [facebook/react-native#24026]
## 💥 Regression Report

CameraRoll doesn't return currently taken image and video.
CameraRoll returns type only specific `image` or `video`. How can I know the extension of the file? I really need that one.

## Last working version

CameraRoll returns currently taken image and video.
CameraRoll returns type: image/png or video/mp4 instead of just image or video

Worked up to version:

Worked version is 0.57.4

Stopped working in version:

React native version 0.59.1

## To Reproduce

1/ Use `react-native-image-picker` to launch default camera and take a picture
2/ Use CameraRoll to load 1 image and it load the image from long time ago, not the currently taken

## Expected Behavior

Can you please take a look and add return extension for both images and videos just like it does before?

CameraRoll should return the currently taken image. Or if there is anyway to force it to do so?

## Code Example

    CameraRoll.getPhotos({

        first: 1,
        assetType: 'All',
        groupTypes: 'All',

    }).then((result) => {

        // DOES NOT return the currently taken image or video
        
        // The type of returned file is only 'image' ot 'video'

    }).catch((error) => {

        console.log("loadOneMedia error", error);
    });

## Environment

info 
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz
      Memory: 1.07 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.13.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 19, 21, 22, 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.2, 25.0.0, 25.0.2, 26.0.2, 26.0.3, 27.0.3, 28.0.0, 28.0.1, 28.0.2, 28.0.3
        System Images: android-18 | Google APIs Intel x86 Atom, android-19 | Google APIs Intel x86 Atom, android-21 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom, android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-24 | Google Play Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.1 => 0.59.1 
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by cpojer** [comment]
This issue has been moved to react-native-community/react-native-cameraroll#12.
