### ISSUE TITLE
Question:  /ReactCommon/yoga/yoga/YGConfig.h file not found

### ISSUE THREAD

**Issue by lutakyn** [facebook/react-native#24027]
We use GitHub Issues exclusively to track bugs in React Native. As it happens, support requests that are created as issues are likely to be closed. We want to make sure you are able to find the help you seek. Please take a look at the following resources.

## Coding Questions
I ejected from expo into a pure react native project.I have issues with the ios project
The error shown below  /ReactCommon/yoga/yoga/YGConfig.h file not found.
How do solve this issue.I have attached a file
[info.pdf](https://github.com/facebook/react-native/files/2982830/info.pdf)

**Comment by kelset** [comment]
@lutakyn also maybe open an issue here -> https://github.com/expo/expo

**Comment by lutakyn** [comment]
it's not an expo issue,I have a pure react native solution now which is working on android and not ios

**Comment by lutakyn** [comment]
It's not an expo issue,I have nothing to do with expo.Its the react native ios which is giving me errors

**Comment by kelset** [comment]
You ejected from expo, so unless you are able to provide a repro from a fresh `react-native init`-ed project it is most likely related to that.

**Comment by lutakyn** [comment]
It is not related to expo, you are just failing to help. What is yoga folder in the ios project.It is related to ios and react native. This is stressful. You should be able to tell me something better. Android works as expected
