### ISSUE TITLE
Question: How to handle heavy API response?

### ISSUE THREAD

**Issue by harleenarora** [facebook/react-native#24049]
**Issue Description::**

There are too many API data in my server. If I'm hit this API for the first time on the page, then it's working fine. But the app closes when hit API second time on same page. There is no error / crash log for this on the firebase.

I am using [axios](https://github.com/axios/axios) for hit the API on server.

**Code::**

```
componentDidMount() {
    this.getSingleUser();
}

 async getSingleUser() {
   NetInfo.isConnected.fetch().then(isConnected => {
       axios.get(`${api_URL}`)
           .then(response => {
               Toast.show("2");
               this.checkApiResponse(response.data.response);
       })
       .catch(error => {
           Toast.show(JSON.stringify(error));
       });
   });
}


checkApiResponse(response) {
   this.setState({ loading: false, refreshing: false });
   console.log(response);
}
```

Some time it's working fine, if API data is too small. This is a problem when API data is too large. Please suggest If anyone having a solution?

**Comment by cpojer** [comment]
Please note this issue tracker is not a help forum (as stated in issue template).

We recommend using [StackOverflow](https://stackoverflow.com/questions/ask) where there are community incentives to help others or our [Discord channel](https://discord.gg/Xs5Xbjr) for questions.
