### ISSUE TITLE
`fontVariant` does not work with certain fonts

### ISSUE THREAD

**Issue by cruzach** [facebook/react-native#24043]
## 🐛 Bug Report
The `fontVariant` style prop doesn't seem to work with most fonts. At first I thought this was only on custom fonts, but even commonly used "pre-packaged" fonts (Arial, Helvetica, Courier, etc.) cause the `fontVariant` prop to have no effect.

## To Reproduce
Use the `fontVariant` style prop in conjunction with a font other than the system font. See Code Example below.

## Expected Behavior
Expected the fontVariant props to have the same effect on style when used with other fonts. For example, when using `fontFamily: 'Times', fontVariant: ['small-caps']` the lower-case letters SHOULD change to be smaller versions of the upper-case letter. However, this only occurs when using the System font.

## Code Example
https://snack.expo.io/@charliecruzan/fontvarianttest 
The above Snack shows the issue just in regards to `fontVariant: ['small-caps']`, but you can also use the [React-Native Tester testExample](https://github.com/facebook/react-native/blob/e67aa427a811ab252eda175f42a518e7779ab486/RNTester/js/TextExample.ios.js#L951-L984) in a react-native app and just change the fontFamily to see the issue happen with all FontVariant options.

## Environment
React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
      Memory: 313.39 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.6.0 - ~/.nvm/versions/node/v11.6.0/bin/node
      npm: 6.9.0 - ~/.nvm/versions/node/v11.6.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.1 => 0.59.1
    npmGlobalPackages:
      react-native-cli: 2.0.1

Thanks, and let me know if there's anything else I can provide to help out!

**Comment by jacobp100** [comment]
Do the fonts in question have small caps? They're separate glyphs - not just capital letters made smaller. I think every browser fall back to small caps if they're not available, but I'm not sure native iOS does that

**Comment by cruzach** [comment]
You mean browsers fall back to scaling down capitals if the glyphs for small caps aren't available? 

`Hoefler Text` has small caps, but the same problems persists if you use that as the `font-family` in the Snack I linked.

**Comment by jacobp100** [comment]
Yeah, sorry - I phrased that badly. I just checked the macOS Hoefler Text font, and it does appear to have native small caps. It's highly likely iOS follows, so I do believe this is a bug.

One thing we should try first is if we can get this working just in a vanilla ObjC/Swift app to see if it's RN or just an iOS quirk.

**Comment by cruzach** [comment]
Yeah just tried getting this working in a Swift app...doesn't seem to work. Although it's definitely possible I'm doing something wrong. 
Code is in [this repo](https://github.com/cruzach/fontVariantBug), you can run it in Xcode that Systemfont correctly uses small caps, but Hoefler Text doesn't.

**Comment by kelset** [comment]
> One thing we should try first is if we can get this working just in a vanilla ObjC/Swift app to see if it's RN or just an iOS quirk.

yup this is the best approach, actually I believe it may have something to do with the Font itself and not strictly RN.

I'll close this for now, please let me know if you can manage to prove that it's actually a RN issue (maybe test with another font that on a native iOS app works the expected way and not in RN?).
