### ISSUE TITLE
Animated.View not firing TouchableOpacity event on Android if initially rendered off screen

### ISSUE THREAD

**Issue by CatapultJesse** [facebook/react-native#24046]
## 🐛 Bug Report
When you have an animated view initially rendered off the screen on android it seems the touchable opacity event doesn't get fired.

Works correctly on iOS

## To Reproduce
https://snack.expo.io/@jkcooper/rn-issue-animated-scroll-touchable-opacity-android

## Expected Behavior
Tapping on a touchable opacity that gets brought into view will fire

## Code Example
Snack: https://snack.expo.io/@jkcooper/rn-issue-animated-scroll-touchable-opacity-android

## Environment
  React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (4) x64 Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
      Memory: 73.95 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.13.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.4 => 16.8.4 
      react-native: 0.59.1 => 0.59.1 
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by hoomazoid** [comment]
I had the exact same issue and what fixed it for me was removing `position: 'absolute'` from TouchableOpacity

I don't think that's the problem in your case though.

**Comment by CatapultJesse** [comment]
It seems the issue is the Animated.View width doesn't extend on Android based on its contents, and the TouchableOpacity can only be hit within the parent container.

If you put a background color on the Animated.View in the snack you'll see what I mean.

This means a work around of specifically setting the width of the Animated.View (in the snack example `width: (TABS.length + 2) * (width / 3)`) will make all items touchable.

**Comment by jeffmon** [comment]
I having the same issue here, I didn't have `position: 'absolute'` anywhere. I also tried setting the width manually like you stated but that didn't work also. I have a collapsible list with `Animated.View` `overflow: 'hidden'` and a child component that couldn't fire any `onPress` only on Android.

I had to switch to `LayoutAnimation` after many attempts.

**Comment by hopewise** [comment]
any update?

**Comment by jordmccord** [comment]
Anyone know why this happens? Can't figure out a workaround without moving content out of Animated.View...

**Comment by ErnesII** [comment]
I just migrated one project from rn 0.55.4 to 0.60 and some components based on animations stopped working, after several hours I found that new Animated.Value() did not work, atleast for android... you need to use: new Animated.Value(0.01), 0.01 is required. Also If you are using some content that needs to be hidden inside of Animated.View, you will need to use a ScrollView instead of a normal View: 
```
<ScrollView
    scrollEnabled={false} 
    showsVerticalScrollIndicator={false}
    showsHorizontalScrollIndicator={false}
>
    { this.props.children }
</ScrollView>
```

Before I was using this code specifically for iOS, but it seems that rn 0.60 in Android is behaving exactly like iOS.

**Comment by tomtargosz** [comment]
Having the same issue in 0.59.10. Manually animating `TouchableOpacity` with `Animated.createAnimatedElement` doesn't work either.

**Comment by jonathandai** [comment]
Having the same issue on RN 0.60.4. Works fine on iOS, but onPress for touchables on Android do not fire.

**Comment by lakshanmamalgaha** [comment]
I also have the same issue in android touchable opacity not firing in RN version 0.60.4

**Comment by bigo104** [comment]
Seeing the same issue, animated.view doesn't like onPress event handler from touchable components <any one of them>.

**Comment by bigo104** [comment]
have any of the contributors or maintainers chimed in here? Seems like 5 months is a good amount of  time to fix this issue.

**Comment by bigo104** [comment]
Upon further investigation and using my eyes to read -- when using Animated.View we should resolve to [PanResponders](https://facebook.github.io/react-native/docs/panresponder.html)

**Comment by thibmaek** [comment]
We are experiencing the same issue here (https://github.com/thibmaek/react-components/blob/master/react-native/rn-bounce/index.js#L78).

The only effective workaround is setting a width and height on the Animated.View

**Comment by haveamission** [comment]
@bigo104 - how would one use PanResponders in a similar way to an Animated.View?
