### ISSUE TITLE
Make Web Socket Connection alive even the app is closed  

### ISSUE THREAD

**Issue by rAnAaRsl** [facebook/react-native#24061]
I want to make my connection with web Socket alive even the app is closed by user and send push notifications based on the socket message if the app is not in foreground or closed

**Comment by Salakar** [comment]
Hey @rAnAaRsl :wave:, please could you raise this question on StackOverflow. Thanks

**Comment by rAnAaRsl** [comment]
Already raised it on StackOverflow but no answer 

https://stackoverflow.com/questions/55259235/make-web-socket-connection-alive-even-the-app-is-closed
