### ISSUE TITLE
Facebook app review confirmation broken

### ISSUE THREAD

**Issue by nicoara** [facebook/react-native#24064]
## 🐛 Bug Report
I have submitted the react native app named Origin Spots (ID 455966074844636 ) for app review to Facebook for a new user_friends permission. I have passed the app verification, and moved on to signing contract documents, and sent them for approval. I have been stuck at the step 'In Document and Contract Review' for 10 business days now (maximum was 5).

I am being asked via email by a Facebook CHATBOT repeatedly to 'Confirm Your Identity' , with 'We can't help you with your request until we can confirm that this account belongs to you.'. Although I repeatedly reply with my ID and passport, the chatbot keeps responding with the same email.
I believe the chatbot has a BUG and does not understand my ID / passport, it is stuck in a loop and cannot advance forward. 

I want to finish the app approval process.

I understand this is not a React Native issue, but I am looking for someone HUMAN that can notify another HUMAN at the support. I will give back karma for this. 

I have an issue thread. 
https://www.facebook.com/help/community/question/?id=1356634731145766&added&rdrhc

How to proceed?

Thank you,
Nicoara

**Comment by Salakar** [comment]
Hey @nicoara :wave: , the documentation on app reveiw states this can take several weeks during busy periods, https://developers.facebook.com/docs/apps/review/ - having said that, the React Native GitHub repository is for issues for React Native and not general Facebook concerns. 

Please stick to the available support channels relating to app reviews.

Thanks
