### ISSUE TITLE
Discussion: /

### ISSUE THREAD

**Issue by saedaA** [facebook/react-native#24079]
If you want to participate in casual discussions about the use of React Native, consider participating in one of the following forums:
- Discord Community: https://discord.gg/0ZcbPKXt5bZjGY5n
- Spectrum Chat: https://spectrum.chat/react-native
- Facebook Group: https://www.facebook.com/groups/react.native.community

For a full list of community resources:
- http://facebook.github.io/react-native/help

If you'd like to discuss topics related to the future of React Native, please check out the discussions and proposals repo:
- https://github.com/react-native-community/discussions-and-proposals

**Comment by JKCooper2** [comment]
discord.gg link -> likely spam. please delete

**Comment by bartolkaruza** [comment]
ok
