### ISSUE TITLE
[NavigatorIOS]'navigationContext' property is not properly initialized

### ISSUE THREAD

**Issue by monyxie** [facebook/react-native#2407]
All `NavigatorIOS` instances shares the same initial `navigationContext` object, due to the nature of `React.createClass`. If one of the instances modify that `navigationContext` object, subsequent instances will be initialized with the modified object.
Example: 
  - `NavigatorIOSInstA` mounts
  - `NavigatorIOSInstA` unmounts, causes `NavigatorIOSInstA.navigationContext._eventEmitter = null`
  - `NavigatorIOSInstB` mounts, now `NavigatorIOSInstB.navigationContext._eventEmitter` is `null`

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/navigatoriosnavigationcontext-property-is-not-properly-initialized
