### ISSUE TITLE
Tapjacking Protection

### ISSUE THREAD

**Issue by kiran-mantana** [facebook/react-native#24074]
Recently we have an Infosec review of our app and they raised an issue regarding Tapjacking Protection, Is there any solution in react-native.

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for bug reports. Yours seems more a question for [StackOverflow instead](https://stackoverflow.com/questions/tagged/react-native).

Unless you can provide more information and turn this into something actionable, I am not sure we can do anything.
