### ISSUE TITLE
[Packager] from 0.8 and up, using a separate --root makes node_modules unresolvable

### ISSUE THREAD

**Issue by jsierles** [facebook/react-native#2408]
On rnplay.org we rely on the packager running in a separate directory from people apps, so we have:

```
/apps/example1/index.ios.js
/apps/exampe2/index.ios.js
```

Then we have a packager with a collection of community modules install in its root, and run it thusly:

```
node node_modules/react-native/packager/packager.js --root /apps --port 8080
```

Up to 0.6 this worked alright. At 0.8 and up, when requiring one of the modules, the packager now reports:

```
Unable to resolve module react-native-video
```

Just wanted to know if this is a bug, or if we should not be using the packager this way, and each app should have its own node_modules tree. Ideally we can just keep one node_modules per React Native version.

**Comment by jsierles** [comment]
Just an update, I found that having the node_modules at the root directory of these subdirectories works well enough for my needs. But still curious if it's possible to restore the alternate root functionality with modules.

**Comment by klvs** [comment]
I was having an issue wherein I was getting an error:  ` undefined is not an object (evaluating 'RCTWebSockerManager.connect') ` after following the [Integrating with Existing Apps tutorial](https://facebook.github.io/react-native/docs/embedded-app-ios.html). I downgraded to 0.7.1 after reading this issue and it now works fine. Seems related as the tutorial has you start to dev server with `(JS_DIR=`pwd`/ReactComponent; cd Pods/React; npm run start -- --root $JS_DIR)`

**Comment by brentvatne** [comment]
@klvs - you'll need to add the websocket lib to your project if you're using cocoapods, it's required for development.

I don't think anyone is working on this currently and seems like it's not a common problem so I'll close this for now. Thanks for the follow up @jsierles and @klvs

**Comment by klvs** [comment]
@brentvatne, got this working a little while ago but thanks for getting back to us. That was indeed the problem. 

This is my current working Podfile if anyone has this issue in the future.
```
pod 'React'
pod 'React', :subspecs => [
	'RCTText',
	'RCTImage',
	'RCTNetwork',
	'RCTWebSocket'
]
```

**Comment by brentvatne** [comment]
Awesome thank you so much for posting that @klvs! :rocket: :guitar:
