### ISSUE TITLE
react-native run-ios, can not show demo app on simulator

### ISSUE THREAD

**Issue by xgqfrms** [facebook/react-native#24089]
## 🐛 Bug Report

```sh
$ react-native run-ios,

# can not show demo app

```

> After I run `react-native run-ios` command and terminal only show unknown infos , just as below image s shows

Although  the simulator is open , but the app can not show on the simulator.

1. 
![image](https://user-images.githubusercontent.com/7291672/54762267-b9beb300-4c2e-11e9-8548-01cc13116a77.png)
2. 
![image](https://user-images.githubusercontent.com/7291672/54762353-e83c8e00-4c2e-11e9-9400-bb047f3bc990.png)
3. 
![image](https://user-images.githubusercontent.com/7291672/54760960-21273380-4c2c-11e9-9390-0223a5e285d4.png)

## Environment

```sh

$ react-native info

```

![image](https://user-images.githubusercontent.com/7291672/54761256-b7f3f000-4c2c-11e9-9050-cec20cc766c9.png)

**Comment by xgqfrms** [comment]
# need help

https://stackoverflow.com/questions/48043958/react-native-app-not-running-in-xcode-ios-simulator

https://stackoverflow.com/questions/40352453/react-native-app-is-showing-incorrect-app-in-simulator

**Comment by kelset** [comment]
@xgqfrms it looks like something in the way you created your demo app is not configured correctly, have you followed all the steps in https://facebook.github.io/react-native/docs/getting-started - section " React Native CLI Quickstart"?

Can you try to generate a new project and see if the issue persist?

I can't reproduce locally.

**Comment by xgqfrms** [comment]
# it's so weird，today  everything is Ok.

> I don't know what's going on

![image](https://user-images.githubusercontent.com/7291672/54796481-5adb5700-4c8b-11e9-82e3-5262dc09acd3.png)

**Comment by xgqfrms** [comment]
> @xgqfrms it looks like something in the way you created your demo app is not configured correctly, have you followed all the steps in https://facebook.github.io/react-native/docs/getting-started - section " React Native CLI Quickstart"?
> 
> Can you try to generate a new project and see if the issue persist?
> 
> I can't reproduce locally.

# yes, I did.

> but, the result is no I wanner.

**Comment by xgqfrms** [comment]
https://facebook.github.io/react-native/docs/troubleshooting#content

**Comment by kelset** [comment]
Uhm tbh the fact that you had to run `sudo npm` to install is a huge red flag - probably there is something missconfigured in your machine 🤔

You should never have to `sudo npm` - so maybe that's why the cache is then invalid.

**Comment by xgqfrms** [comment]
> Uhm tbh the fact that you had to run `sudo npm` to install is a huge red flag - probably there is something missconfigured in your machine 🤔
> 
> You should never have to `sudo npm` - so maybe that's why the cache is then invalid.

# why, I'm so confused with your answer.

1. The `cli` command  should be install globally.
2. I had to `sudo`, because the current user has no permit.
