### ISSUE TITLE
app can not start on some android devices

### ISSUE THREAD

**Issue by bshrram** [facebook/react-native#24097]
my app run on my device(samsung grand) and emu, but I tried it on other phone (huawei y5 2017) and it was unable to start

### adb log:

```
03-22 05:54:22.965 30915 30930 E BDLog   : BD.BaseEvent:Encrypt Exception: expected IV length of 16 but was 32
03-22 05:54:23.200  1241  2596 E Sensors : handleToDriver handle(0)
03-22 05:54:23.206  1241  2596 E Sensors : handleToDriver handle(0)
03-22 05:54:23.209  1241  2596 E Sensors : new setDelay handle(0),ns(66667000)m, error(0), index(2)
03-22 05:54:23.256  3813  3813 E MultiWindowProxy: getServiceInstance failed!
03-22 05:54:26.702  3813  3882 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x7f57ec0000 in tid 3882 (FrescoDecodeExe)
03-22 05:54:26.758  3883  3883 E AEE/AED : unexpected waitpid response: n=3882, status=0000000b
03-22 05:54:26.758  3883  3883 E AEE/AED : tid exited before attach completed: tid 3882
03-22 05:54:26.758  3883  3883 E AEE/AED : request.action: 0
03-22 05:54:26.845  1241  1255 E HsmCoreServiceImpl: onTransact in code is: 102
03-22 05:54:26.845  1241  2132 E Sensors : handleToDriver handle(0)
03-22 05:54:26.849  1241  1496 E InputDispatcher: channel '46571b6 com.contractorapp/com.contractorapp.MainActivity (server)' ~ Channel is
unrecoverably broken and will be disposed!
03-22 05:54:26.855  1241  2090 E MultiWindowProxy: getServiceInstance failed!
03-22 05:54:26.874  2116  2279 E HwLauncher: SettingsEx , no such field.
03-22 05:54:27.041  1241  9226 E Sensors : handleToDriver handle(4)
03-22 05:54:27.072  1241  9226 E Sensors : handleToDriver handle(4)
03-22 05:54:27.072  1241  9226 E Sensors : new setDelay handle(4),ns(1000000000)m, error(0), index(5)
03-22 05:54:28.078  1241  1486 E PROXIMITY: ProximitySensor: unknown event (type=3, code=0)
03-22 05:54:28.089  1241  1622 E Sensors : handleToDriver handle(4)
```

## and this is my dependencies : 

```
"@terrylinla/react-native-sketch-canvas": "^0.8.0",
    "axios": "^0.18.0",
    "firebase": "^5.8.6",
    "formik": "^1.5.1",
    "react": "16.8.3",
    "react-native": "0.59.1",
    "react-native-elements": "^1.1.0",
    "react-native-formik": "^1.7.5",
    "react-native-gesture-handler": "^1.1.0",
    "react-native-material-textfield": "^0.12.0",
    "react-native-restart": "0.0.9",
    "react-native-touchable-scale": "^2.0.0",
    "react-native-vector-icons": "^6.4.2",
    "react-navigation": "^3.3.2",
    "recompose": "^0.30.0",
    "rn-fetch-blob": "^0.10.15",
    "yup": "^0.26.10"
```

**Comment by ATShiTou** [comment]
It seems that the new fresh project with version 0.59.1 can not start on Android devices with API level P.

**Comment by ATShiTou** [comment]
Same as 0.59.2, No one got this problem?

**Comment by nethergrim** [comment]
Same problem here:
` React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
      Memory: 1.89 GB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 24, 26, 27, 28
        Build Tools: 24.0.2, 27.0.3, 28.0.3, 29.0.0
        System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.6 => 16.8.6 
      react-native: 0.59.2 => 0.59.2 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7`

**Comment by dishantwalia** [comment]
#https://github.com/facebook/react-native/issues/24261
