### ISSUE TITLE
Discussion: SwipeableFlatList

### ISSUE THREAD

**Issue by DLevai94** [facebook/react-native#24092]
Hey!

Is it safe now to use the undocumented `SwipeableFlatList`? Or is it a subject to change? Is there any info about what are the next steps to finish the API? Maybe I can contribute to it. :)

**Comment by cpojer** [comment]
We were actually going to remove this from React Native. Feel free to take the code, make it your own, publish and extend it :)

**Comment by DLevai94** [comment]
Thanks, @cpojer

**Comment by DLevai94** [comment]
Btw, what's the exact reason about it? There's some issue with the component or you just don't think that fits in the core?

**Comment by cpojer** [comment]
It was built as an experiment at FB and made it into its way to open source but it never gained any adoption here and is unlikely to receive any.

**Comment by nicastelo** [comment]
Published it here https://github.com/nicastelo/react-native-swipeable-lists. It has SwipeableFlatList and SwipeableListView
