### ISSUE TITLE
Examples not open source

### ISSUE THREAD

**Issue by bootstraponline** [facebook/react-native#241]
```
 The examples provided by Facebook are for non-commercial testing and
 evaluation purposes only.
```

Why are [the examples](https://github.com/facebook/react-native/blob/b4da77a31f2c5ac749b4f8252dd75b8793dfe493/Examples/UIExplorer/ActionSheetIOSExample.js#L2) under a proprietary license instead of the [same license as react-native](https://github.com/facebook/react-native/blob/master/LICENSE)?

**Comment by vjeux** [comment]
Duplicate of #331
