### ISSUE TITLE
Shell Script Invocation Error

### ISSUE THREAD

**Issue by lutakyn** [facebook/react-native#24102]
## 🐛 Bug Report

  I created a new project with expo and ejected,tried to build  with  XCode 10 and I keep error in the IOS build. When I run npm run ios. This is a problem with react native which is not able to see some files which are present in the project

## To Reproduce
Eject from any expo react native project 

## Expected Behavior
A complete build in XCode and with react-native  run-ios
## Error

     The following build commands failed: PhaseScriptExecution Install\ Third\ Party 
     /Users/mypc/Documents/Apps/VodafoneApp/ios/build/MyApp/Build/Intermediates.noindex/
     React.build/Debug-iphonesimulator/double-conversion.build/Script- 
     190EE32F1E6A43DE00A8543A.sh (1 failure)

       /Users/my/Documents/Apps/myapp/ios/build/MyApp/Build/Intermediates.noindex/
       React.build/Debug-iphonesimulator/double-conversion.build/Script- 
      190EE32F1E6A43DE00A8543A.sh: line 3: exec: /Users/mypc/scripts/ios-install-third- 
       party.sh: cannot execute: No such file or directory

## Environment
       React Native Environment Info:
       System:
        OS: macOS 10.14.3
       CPU: (4) x64 Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
      Memory: 24.24 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
      Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      npm: 6.5.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
      SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
        Android SDK:
        API Levels: 26, 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-27 | Google Play Intel x86 Atom
       IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
       npmPackages:
      react: ^16.8.3 => 16.8.3 
      react-native: ^0.59.1 => 0.59.1 
      npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

**Comment by kelset** [comment]
👋 there - this seems to be an Expo related issue, can you please open an issue in its repo?

Unless you can reproduce this error with a repro (which means, a `react-native init`-ed project with the minimal changes that leads to creating the same issue you are reporting). In that case I can reopen this.
