### ISSUE TITLE
App crash on build, but works very well on Simulator...

### ISSUE THREAD

**Issue by Steffi3rd** [facebook/react-native#24104]
2 days that I stuck on this... Build is SUCCESS, but when I open the app >> error 

I have this...

```
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0322 21:12:46.280941 1800777728 NativeToJsBridge.cpp:159] Attempting to call JS function on a bad application bundle: RCTLog.logIfNoNativeHook()
2019-03-22 21:12:46.284 [fatal][tid:main] Unhandled JS Exception: Unexpected token '{'. import call expects exactly one argument.
``` 

```
$ react-native info
info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.1
      CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
      Memory: 605.42 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.10.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.0 => 0.59.0 
``` 

![image0 (1)](https://user-images.githubusercontent.com/814410/54852660-c6561080-4ced-11e9-9697-995ffc370ce1.png)

<img width="573" alt="Capture d’écran 2019-03-22 à 21 49 22" src="https://user-images.githubusercontent.com/814410/54852671-cd7d1e80-4ced-11e9-823c-265cebc04037.png">

**Comment by turnrye** [comment]
Hey @steffi3rd, I suspect that there's actually an issue in your project's code. I think if you look at Metro, you'll see a build-time error.

A few tips:

1. Try resetting all of the caches with:
```bash
 watchman watch-del-all && rm -rf $TMPDIR/react-native-packager-cache-* && rm -rf $TMPDIR/metro-bundler-cache-* && rm -rf node_modules/ && npm cache clean --force && npm install && npm start -- --reset-cache
```
2. Go ahead and upgrade to 0.59.1

Without a repository of your source, it's hard to give specific advice. This seems like an environment issue, but please do follow up with more detail if my pointers above don't help.

**Comment by shohil06** [comment]
Same Issue,
i was working with Expo version 2.11.x, and it was working fine,
then i upgraded to version 2.13.0 and i tried to run my app again, The build was successful but red screen with error,

and now it is not  running, Some **tintColor** error.
The release expo-cli 2.13.0 did not work for me.
i rolled back to 2.11.3 and it started working again.

**Comment by Steffi3rd** [comment]
Same as mine, but I don't use Expo but React Native CLi

**Comment by shohil06** [comment]
@turnrye ,
Is this issue being watched ?
any updates ?

**Comment by michalchudziak** [comment]
Hello there 👋 by using the repro / the list of steps to reproduce, we can't actually see the reported bug on RN 0.59.5 so we'll close this issue. It may have something to do with your local setup, please double check that you are using the correct version of Android Studio / XCode / Android NDK / Yarn / etc.
