### ISSUE TITLE
React native fetch issue on android 

### ISSUE THREAD

**Issue by Amitmpandey** [facebook/react-native#24120]
## 🐛 Bug Report
Hi,
For call API i am using following code example which is work properly for that API which is hosted on my local machine IIS. 
But when i use my production server IP it throw error **network request failed**. 
Please give me solution.

## Code Example
fetch('http://10.0.2.2:80/api/Auth/login/', {
method: 'POST',
headers: {
'Accept': 'application/json',
'Content-Type': 'application/json'
},
body: JSON.stringify({
"UserId": "Admin",
"Password": "123"
})
})
.then((response) => {
const statusCode = response.status
const data = response.json()
return Promise.all([statusCode, data])
})
.then((res) =>{
if(res[0] == 200){
alert(res[1])
//this.props.navigation.navigate('Main')
}
else{
alert(res[1])
}
})
.catch((error) => {
console.error(error);
});

## Environment
 react-native-cli: 2.0.1 
react-native: 0.59.1 
API level 28 android pie google pixel 2 emulator. 

$ react-native info
info
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
      Memory: 2.66 GB / 5.70 GB
    Binaries:
      Yarn: 1.13.0 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.8.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5264788

**Comment by Salakar** [comment]
@Amitmpandey thanks for the issue report. 

I have a strong feeling this is related to Android 28's network security policy change, could you take a look at the steps indicated here and apply them (including adding a rule for your production IP address): https://facebook.github.io/react-native/docs/integration-with-existing-apps#network-security-config-api-level-28 (Android tab)

**Comment by Amitmpandey** [comment]
@Salakar Thanks for reply. Sure I’ll apply settings which mentioned in link and try

**Comment by Amitmpandey** [comment]
@Salakar A big big big Thank you. I Added my production IP in react_native_config.xml file which is already added in my project. This is working fine. Again thank you so much. Lots of love from India.

**Comment by Salakar** [comment]
@Amitmpandey you're welcome, good luck with your project!
