### ISSUE TITLE
Twitter widget on non-SSL reactnative.com leaks Twitter cookies due to SSL downgrade

### ISSUE THREAD

**Issue by thezedwards** [facebook/react-native#24122]
## 🐛 Bug Report
Howdy - Currently the React Native website doesn't have a SSL certificate @ http://reactnative.com

This website also has a legacy Twitter widget that allows itself to be downgraded and still connects -- but then it passes insecure cookies/user-identifying details as insecure cookies. 

There are also a variety of security controls missing, so a user can spoof/iframe the ReactNative website and then use that to identify twitter users. I did a very quick iframe test just to confirm a few things on my website @ https://victorymedium.com/pages/react-cookies

Here's showing my SSL website embedding the non-SSL reactNative.com and then still passing the Container/iframe requests to Twitter and back: https://www.evernote.com/l/AH3v8q95XfZN4Le2F5DESu8dGeamV4aWNyk

Here's a screen shot of the Twitter widget firing directly within the ReactNative.com website without downgrading: https://www.evernote.com/l/AH1fO56xllJJirBjrjksh6wN0ofUpZYXqpQ

Here's a screen shot of the Twitter cookies (including userID) that leak via this legacy widget @ https://www.evernote.com/l/AH14Hp5SnMpFrrIAt-87uo_8InZiliBcyYk

## To Reproduce
This is a relatively low-risk spoofing/anonymizing issue, but since ReactNative is used by Facebook and this impacts Twitter, I figured it was something ya'll would want to fix with a SSL on the site or by removing the legacy Twitter widget. Either of those solutions would button this up most likely. 

## Expected Behavior
No secure Twitter user cookies should pass to the parent window on ReactNative.com ((note, I understand this is also a Twitter vuln, but I can't drag a dead horse to water and get them to depreciate an entire legacy widget, so here we are))

## Code Example
Screen shots above -- pretty minor stuff but I'm happy to literally show which Twitter widget to remove or help with any SSL conflicts.

## Environment
NA

**Comment by Salakar** [comment]
@thezedwards thanks for reporting your concerns.

Unfortunately, that domain is not an official domain for React Native and is out of our control.

I'll go ahead and close this issue as there's not much we can do here sorry. 😞

**Comment by thezedwards** [comment]
Thanks @Salakar - can you clarify *who does* own it? 

That ReactNative domain controls other job domains and a bunch of react stuff... and has no information about ownership I can find anywhere... yet it's able to identify users who visit the site? And it has registration tools on a bunch of sites... and email lists it grows...

This seems like a Facebook security issue for them to ignore a bunch of "helpful developer sites" built by anonymous organizations. Do you know anyone who would know more details?

thanks for the time and helping to close this out etc. cheers~

**Comment by hramos** [comment]
@thezedwards the reactnative.com has no affiliation whatsoever with Facebook, React, or the React Native Community org. It's being squatted. We've reached out multiple times, but the owner has shown no interest in cooperating.

**Comment by thezedwards** [comment]
Thanks very much @hramos. 

Out of curiosity - do open source projects have the ability to claim a squatted domain or do anything that would normally be available for brand trademark complaints? There seems to be a bit of a loophole here...

I'll keep poking around on these domains and these folks (I'm largely trying to figure out if they can use eTags or other file identifiers as cross-domain Ids)< but may not have any updates here. 

Thanks for ya'lls work - feel free to close this out as needed! :D
