### ISSUE TITLE
[TabBarIOS] icon scale with wrong format

### ISSUE THREAD

**Issue by akecn** [facebook/react-native#2413]
#1136  support scale, but maybe with wrong format.

`{uri: "base64:xxx", scale: 2}` is unavailable, and `{uri: {uri: "base64:xxx", scale: 2}}` is available.

![image](https://cloud.githubusercontent.com/assets/352465/9427826/ad8909f4-49c2-11e5-8d7b-d4f8a322f9a9.png)

![image](https://cloud.githubusercontent.com/assets/352465/9427808/61ee9022-49c2-11e5-8954-167b8f23bdb4.png)

using 0.10.0-rc. see demo here:  https://rnplay.org/apps/QofUjw

**Comment by nicklockwood** [comment]
OK, I've added a fix for the next release. In the meantime, you can fix it with the following patch. In TabBarItemIOS.ios.js, change line 111-113 from

     var icon = this.props.systemIcon || (
      this.props.icon && this.props.icon.uri
    );

To

    var icon = this.props.systemIcon || this.props.icon;

And change line 122 from

    selectedIcon={this.props.selectedIcon && this.props.selectedIcon.uri}

To just

    selectedIcon={this.props.selectedIcon}

**Comment by akecn** [comment]
thanks,  and the issue will be closed
