### ISSUE TITLE
API data size 2MB and large, memory leak

### ISSUE THREAD

**Issue by harleenarora** [facebook/react-native#24134]
**Description::**

If my API data size is more than 2MB and can be extended. My Android/IOS app crashes on loading a page for a second time. I am hit the API so many time, app is not crash, But I am convert api response to response.json(), app is crash on second time.

**React Native Environment Info:**

    System:
      OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
      CPU: (2) x64 Intel(R) Core(TM)2 Duo CPU     E7500  @ 2.93GHz
      Memory: 1.17 GB / 7.76 GB
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 10.5.0 - /usr/local/bin/node
      npm: 6.1.0 - /usr/local/bin/npm
    npmPackages:
      react: ^16.8.5 => 16.8.5 
      react-native: ^0.59.1 => 0.59.1 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1

**Comment by darekg11** [comment]
Do you think that this can look similar to https://github.com/facebook/react-native/issues/23801?

**Comment by harleenarora** [comment]
@darekg11 I know, but there is not any solution for this problem.

**Comment by darekg11** [comment]
@harleenarora Sorry nope, I wanted to recommended trying following comment:  
https://github.com/facebook/react-native/issues/20352#issuecomment-437878216
but I see that you have already posted there so it seems like cloning the response object does not work for You.
