### ISSUE TITLE
Question: can we stick the sticky header of sectionList (or a scrollView) to a relative position to the top of the scrollview

### ISSUE THREAD

**Issue by hweister** [facebook/react-native#24130]
now when we scroll the sectionList, we can stick the sticky header at the top of the scrollview, but what I need is set a margin between the sticky header and the top of the scrollview, ie: leave a gap between the top of the scrollview,
does any one know how to handle it?

Thanks

**Comment by yzalvov** [comment]
Hi @hweister 
Have you managed to find a solution?
