### ISSUE TITLE
Typo on DatePickerAndroidTypes

### ISSUE THREAD

**Issue by eduardojunio** [facebook/react-native#24137]
## 🐛 Bug Report
```
  mode?: ?('calender' | 'spinner' | 'default'),
```

`calender` should be replaced with `calendar`

## To Reproduce
Not needed

## Expected Behavior
The word **calendar** should be spelled correctly

## Code Example
Not needed

## Environment
[skip envinfo]
Not needed, it's just a typo.

**Comment by cpojer** [comment]
Thank you for creating this issue. Do you mind sending us a pull request with a fix? :)
