### ISSUE TITLE
Regression: no such file or directory: 'react-native/React/Base/RCTJSCErrorHandling.mm'

### ISSUE THREAD

**Issue by arhmnsh** [facebook/react-native#24133]
I've upgraded my project to 0.58.0 from 57.x
Getting this error when I build the project in Xcode.

```
clang: error: no such file or directory: '/Users/myUser/myApp/node_modules/react-native/React/Base/RCTJSCErrorHandling.mm'
clang: error: no input files
```

<img width="601" alt="image" src="https://user-images.githubusercontent.com/1363724/54905333-d63e4200-4ef1-11e9-9012-f1beabf793cf.png">

**Comment by hramos** [comment]
It looks like the author hasn't updated their issue to provide the information as requested. Closing.
