### ISSUE TITLE
Impact of moving ReactNativeHost from Application level to Activity level in Android

### ISSUE THREAD

**Issue by jaslyn-siliconjungles** [facebook/react-native#24144]
I'm looking for a way for different activities to open different *.android.bundle files. 

Example:
MainActivity -> index.android.bundle
HelloWorldRNActivity -> helloworld.android.bundle

I've tried searching but I'm not able to find any documentation on how to achieve this.

So I've modified some code to move the ReactNativeHost from the Application level to the Activity level (MyReactActivity), and overwrote the ReactActivityDelegate.getReactNativeHost() function to retrieve it from MyReactActivity instead. 

    public abstract class MyReactActivity extends ReactActivity {
        private ReactNativeHost mReactNativeHost;

        @Override
        protected abstract String getMainComponentName();
    
        protected abstract ReactNativeHost createReactNativeHost(Application app);
    
        protected ReactActivityDelegate createReactActivityDelegate() {
    
            return new WeReactActivityDelegate(this, getMainComponentName()) {
                @Override
                protected ReactNativeHost getReactNativeHost() {
                    if (mReactNativeHost==null) {
                        mReactNativeHost = createReactNativeHost(getApplication());
                    }
                    return mReactNativeHost;
                }
            };
        }
    }

    public class HelloWorldRNActivity extends MyReactActivity {
    
        @Override
        protected String getMainComponentName() {
            return "Helloworld";
        }
    
        @Override
        protected ReactNativeHost createReactNativeHost(Application app) {
            return new ReactNativeHost(app) {
                @Override
                public boolean getUseDeveloperSupport() {
                    return false;
                }
    
                @Override
                protected List<ReactPackage> getPackages() {
                    return Arrays.<ReactPackage>asList(
                            new MainReactPackage()
                    );
                }
    
                @Override
                protected String getBundleAssetName() {
                    return "helloworld.android.bundle";
                }
            };
        }
    }

This implementation seems to work so far with my current testing and I'm able to successfully start two different react native activities that open two different *.android.bundle files.

Is this implementation correct? If not, what are the possible problems that may arise from this change in code?

Alternatively, are there any other ways to open multiple *.android.bundle files from the same application?

**Comment by hramos** [comment]
Closing as advised in the discussions template.
