### ISSUE TITLE
Camera Roll not returning any photos on iOS

### ISSUE THREAD

**Issue by BenJeau** [facebook/react-native#24140]
## 🐛 Bug Report
When fetching photos from the Camera Roll on **iOS** by calling `CameraRoll.getPhotos()`, it always return an empty array of edges in the data. This problem is not present when I run it on Android nor in a Snack. Tried implementing the [community version](https://github.com/react-native-community/react-native-cameraroll) of the Camera Roll, but the problem persisted. Tried running it on the iOS simulator, on an iPhone, and an iPad with no success.

## To Reproduce

1. Create a new react native project (with `react-native init`)
2. Link the RCTCameraRoll library as described [here](https://facebook.github.io/react-native/docs/cameraroll) from facebook's website
3. Add the permission keys in the Info.plist as described [here](https://facebook.github.io/react-native/docs/cameraroll#permissions) from facebook's website
4. Copy paste the [sample code](https://facebook.github.io/react-native/docs/cameraroll#example) from facebook's website
5. Run `react-native start --reset-cache` (Solved the problems I was having with metro)
5. Run `react-native run-ios`

## Expected Behavior

I would expect the Camera Roll getPhotos function to return a populated edges array in the edges with the information/URI of images in the phones camera roll.

## Code Example

Cannot replicate bug in a [Snack](https://snack.expo.io/@benjeau/react-native-camera-roll-ios-issue), the problem is not there.

But here is a [repo](https://github.com/BenJeau/reactNativeCameraRollIssue) with a code example. I also uploaded the iOS release app file to [appetize.io](https://appetize.io/app/xcva0fr6xhqtyt1yvt1jywy61g), which does have the problem.

## Environment
Output of the `react-native info` command

```
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
      Memory: 18.59 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.12.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 21, 23, 25, 26, 27, 28
        Build Tools: 21.1.2, 23.0.3, 25.0.2, 26.0.2, 27.0.3, 28.0.2, 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.1 => 0.59.1 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

**Comment by kelset** [comment]
👋 can you please open an issue over the camera-roll repo? One of the reasons for extracting the components is that this way the issues will be in their own repos and can be tackled by the maintainers of the extracted component (since that's the version you should use from now on)
