### ISSUE TITLE
Https not working in Emulator or Simulator

### ISSUE THREAD

**Issue by opolyo01** [facebook/react-native#24159]
## 🐛 Bug Report
I tried to run a fetch example in Android emulator and IOS simulator, and both fails with TypeError: Network request failed at XMLHttpRequest.xhr.onerror 

## To Reproduce
Start new react Native project, copy fetch example with https.

## Expected Behavior
It should render a list of movies.  It works with http and inside of android/ios device, but not working in simulator and emulator.

## Code Example
```
componentDidMount() {
    return fetch('https://facebook.github.io/react-native/movies.json')
      .then((response) => response.json())
      .then((responseJson) => {

        this.setState({
          isLoading: false,
          dataSource: responseJson.movies,
        }, function(){

        });

      })
      .catch((error) =>{
        //always go here
        debugger;
        console.error(error);
      });
  }
```
## Environment
info 
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.3
      CPU: (4) x64 Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
      Memory: 120.46 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.13.0 - ~/.nvm/versions/node/v8.13.0/bin/node
      Yarn: 1.2.1 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.13.0/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        API Levels: 21, 22, 23, 24, 25, 26, 27, 28
        Build Tools: 19.1.0, 20.0.0, 21.1.2, 22.0.1, 23.0.1, 23.0.2, 23.0.3, 24.0.0, 24.0.1, 24.0.2, 24.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.2, 27.0.3, 28.0.3
        System Images: a... | Android TV Intel x86 Atom Syst..., a...ear | Android Wear ARM EABI v7a Syst..., a...ndroid-wear | Android Wear Intel x86 Atom Sy..., a...google_apis | Google APIs Intel x86 Atom Sys..., a...gle_apis | Google APIs Intel x86 Atom_64 ...
    IDEs:
      Android Studio: 2.3 AI-162.3934792
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.2 => 0.59.2 
    npmGlobalPackages:
      react-native-git-upgrade: 0.2.7

**Comment by sridharrajs** [comment]
Hi @opolyo01 I'm facing the same issue. How did you resolve it?

   npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.1 => 0.59.1
