### ISSUE TITLE
APK file is larger with react-native 0.59

### ISSUE THREAD

**Issue by Thebarda** [facebook/react-native#24154]
## 🐛 Bug Report
After building my arm APK, I noted that APK file increased by about 3 MB.
With Android Studio, I analyzed that APK I found two unstripped .so files, libjsc.so and libc++_shared.so, they respectively size 12.7MB and 5.7MB.

## To Reproduce
`npm install`
then
`unzip -l node_modules/react-native/android/com/facebook/react/react-native/0.59.2/react-native-0.59.2.aar`

## Expected Behavior
These two files must be stripped to reduce their size and, so, to reduce APK file size.

## Code Example
![Screenshot from 2019-03-26 16-45-12](https://user-images.githubusercontent.com/12515407/55011694-91480780-4fe6-11e9-93bf-4acccc4c3ef5.png)

## Environment
```
React Native Environment Info:
    System:
      OS: Linux 4.18 Ubuntu 18.10 (Cosmic Cuttlefish)
      CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
      Memory: 160.84 MB / 15.39 GB
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 8.11.4 - /usr/bin/node
      Yarn: 1.12.3 - /usr/bin/yarn
      npm: 6.9.0 - ~/.npm-global/bin/npm
    SDKs:
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.3, 27.0.3, 28.0.3
        System Images: android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
    npmPackages:
      react: ^16.4.1 => 16.8.5 
      react-native: ^0.59.2 => 0.59.2 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      react-native-rename: 2.2.2
```

**Comment by cpojer** [comment]
This is expected. With 0.59 we shipped a new version of JSC which is both a ton faster and 64-bit compatible. Unfortunately for now we have to live with the size increase but we are working on removing several modules from React Native at the moment: #23313.

**Comment by Thebarda** [comment]
I completly understand that the addition of JSC make APK file larger than before but is it normal that both libjsc.so and libc++_shared.so are huge compare to the other '.so' in the APK ?

**Comment by nes123** [comment]
did you find information about that? the increase in size does not seem reasonable. BTW in my case it is 9.6MB and 4.6MB respectively.

**Comment by sridhar-vadlamani-ck** [comment]
Our app size increased by about 7MB. If the increase is similar for others, I see a lot of people sticking with `0.58`.

**Comment by Thebarda** [comment]
@sridhar-vadlamani-ck Do you splits your application into multiple APK ? Splitting you app into an APK for each architecture could reduce that increase. 
The big advantage of the new 0.59 is that you can generate an APK for 64-bit architectures

**Comment by kaiwen-zhang-ck** [comment]
@Thebarda good point, i will do a comparison and see how much increase we are getting

**Comment by mannodermaus** [comment]
We are seeing a similar size increase (around 4 MB for us) after upgrading from React Native 0.57.8 to 0.59.5. Comparing, for instance, `lib/x86/libjsc.so` in both versions yields the same observations that @Thebarda made; the newer version seems to not be stripped.

*0.57.8 (File size: 4614240 bytes):*
<img width="1393" alt="Screen Shot 2019-05-10 at 13 03 16" src="https://user-images.githubusercontent.com/3897705/57523063-40853780-7324-11e9-8edd-316b433a807f.png">

*0.59.5 (File size: 12704300 bytes):*
<img width="1395" alt="Screen Shot 2019-05-10 at 13 02 52" src="https://user-images.githubusercontent.com/3897705/57523076-4a0e9f80-7324-11e9-90e0-0070b7ab4c62.png">

**Comment by arnavzoman** [comment]
How can we strip these ourselves if we build from source ?
