### ISSUE TITLE
Android app crashing in background 

### ISSUE THREAD

**Issue by thiagoferolla** [facebook/react-native#24153]
## 🐛 Bug Report

I'm getting the following error in the android app reported on our bug reporting tool :

`TypeError: r is not a function. (In 'r()', 'r' is an instance of _)`. It traces down to the ReactNativeRenderer-prod.js line 5232

I cannot confirm as I'm not a 100% sure but it seems it happens when the app is in background and there's no indicator that crash has happened.

## Environment

React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 84.17 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.5.0 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.1, 25.0.2, 26.0.1, 26.0.2, 27.0.3, 28.0.0, 28.0.1, 28.0.2, 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.4 => 16.8.5 
      react-native: ^0.59.2 => 0.59.1 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

**Comment by thiagoferolla** [comment]
I tried upgrading to react native 0.59.2. The number of crashes due to this issue reduced a lot but it still happens on some devices

**Comment by dulmandakh** [comment]
It looks like an issue with your code, or you're trying to call an object that is not a function. Please check your code.
