### ISSUE TITLE
Discussion: react-native-create-library is not maintained now

### ISSUE THREAD

**Issue by januswel** [facebook/react-native#24158]
I am not sure this repo is correct place to post this problem, but there is no other channels to discuss the topic.

[react-native-create-library](https://facebook.github.io/react-native/docs/native-modules-setup) is recommended in [the public documents](https://facebook.github.io/react-native/docs/native-modules-setup). And it seems the repo is not maintained.

https://github.com/frostney/react-native-create-library/issues/106

There are some differences between latest sources in master branch and [published package](https://www.npmjs.com/package/react-native-create-library). Options written in README is not available with cli. It's truly confusing.

On the other hand, there are discussions about next generation of native modules.

https://github.com/react-native-community/discussions-and-proposals/issues/96

1. Tell me a correct place to discuss this topic if you know
2. I can send a PR to change docs with workaround: cloning the repo and run `/cli.js` directly, is this needed ?
3. Consider to maintain the repo by  react native community

Thanks

**Comment by cpojer** [comment]
For now that package should work for you but in the future we are planning on providing a new library scaffold.

**Comment by januswel** [comment]
@cpojer 
> in the future we are planning on providing a new library scaffold.

Where is wrote the plan??
I think it's a problem that ways to scaffold new libraries is not maintained *now*
Do you think about this?

**Comment by cpojer** [comment]
@januswel we do not have a proper plan yet. The best place to stay up to date is the discussions-and-proposals repository, specifically the discussion about TurboModules: https://github.com/react-native-community/discussions-and-proposals/issues/40

**Comment by januswel** [comment]
Thx, @cpojer

**Comment by yozman** [comment]
@cpojer 

> For now that package should work for you

it doesn't work with v0.60-rc.3
