### ISSUE TITLE
[AppStateIOS] Suggestion: adding event support of UIApplicationWillResignActiveNotification

### ISSUE THREAD

**Issue by chengs** [facebook/react-native#2416]
Currently the AppStateIOS can bind event to let the app act to the state change.

Yet I notice that sometimes it is necessary for the app to react to opening the notification center or control center. For example, the animation or video should stop in this case, possibly linking to some UI changes.

The AppStateIOS can not deal with such a condition, which only triggers an event after the state changes. But the state actually does not change to "background" or "inactive".

SO I suggest to add a support of UIApplicationWillResignActiveNotification in AppStateIOS,
or other methods, in order to let the app be aware of calling Notification Center or Control Center.

In https://github.com/facebook/react-native/blob/master/React/Modules/RCTAppState.m

```objective-c
    for (NSString *name in @[UIApplicationDidBecomeActiveNotification,
                             UIApplicationDidEnterBackgroundNotification,
                             UIApplicationDidFinishLaunchingNotification]) {
      [[NSNotificationCenter defaultCenter] addObserver:self
                                               selector:@selector(handleAppStateDidChange)
                                                   name:name
                                                 object:nil];
```
The observer function can not be called when Notification Center or Control Center is fired.

```
UIApplicationWillResignActiveNotification >> This notification is fired when the Notification Center or Control Center is brought up.

UIApplicationWillEnterForegroundNotification >> This notification is fired when the Notification Center or Control Center is dismissed.
```
according to 
http://stackoverflow.com/questions/24291897/pausing-ios-game-when-notification-center-control-center-is-launched

**Comment by ide** [comment]
Yep would be good to have better support for AppStateIOS. It's not super comprehensive or fully working right now.

**Comment by chengs** [comment]
@ide, Do you have a plan to improve AppStateIOS?

**Comment by ide** [comment]
I don't know what the state of it is but, no, I'm not working on it.

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/appstateios-suggestion-adding-event-support-of-uiapplicationwillresignactivenotification
