### ISSUE TITLE
Touches has octagone form on Android 9

### ISSUE THREAD

**Issue by olehmartynets** [facebook/react-native#24168]
## 🐛 Bug Report
if click on TouchableOpacity with Image touches has octagone form
![Знімок екрана  о 16 40 42](https://user-images.githubusercontent.com/35766696/55086455-14359480-50b1-11e9-9fc0-9c6a8a814aad.png)

## Expected Behavior
  Touches has circle form

## Code Example

```
 <TouchableOpacity
              onPress={() => Actions.repayments({onClose: Actions.pop})}
              style={styles.buttonBlock}
              disabled={isBlocked}
            >
              <View style={[styles.circleButton, isBlocked && styles.blockedButton]}>
                <Image source={require('icons/repayments.png')} style={styles.icon}/>
              </View>
              <Text style={styles.buttonText}>{constants.REPAYMENTS}</Text>
            </TouchableOpacity>
```
## Environment
Android 9

**Comment by rickhanlonii** [comment]
Hey @olehmartynets thanks for filing, can you post a reproduction with the styles you're using?

**Comment by Shchepotin** [comment]
@rickhanlonii Hi, it happens when nested <View> has styles shadow and borderRadius.
