### ISSUE TITLE
[TextInput] Crash when refreshing app in simulator if TextInput is focused

### ISSUE THREAD

**Issue by mfkp** [facebook/react-native#2418]
Seems consistent to reproduce.

Click inside a TextInput, and hit cmd+R to reload the app.

You will get a `EXC_BAD_ACCESS` on [line 178](https://github.com/facebook/react-native/blob/master/Libraries/Text/RCTTextField.m#L178) of `RCTTextField.m`

Tested on 0.10.0-rc

**Comment by dsibiski** [comment]
I've tested this on the latest master and it's not crashing.

**Comment by MattFoley** [comment]
Can confirm that I've seen this with other RCT objects. I will follow up with a stack trace when I can.

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/textinput-crash-when-refreshing-app-in-simulator-if-textinput-is-focused
