### ISSUE TITLE
SHA-1 for file (......./empty-module.js) is not computed

### ISSUE THREAD

**Issue by danielgindi** [facebook/react-native#24188]
## 🐛 Bug Report
Trying to generate sourcemaps, for either iOS or Android platform, always fails.

## To Reproduce
1. Generate a new RN project using react-native-cli
2. Remove `react-native-cli` and install `@react-native-community/cli` (old cli knows how to create new projects, new cli does not)
3. Go to its folder, and run `react-native bundle --platform ios --dev false --entry-file index.js --bundle-output ios-release.bundle --sourcemap-output ios-release.bundle.map`
4. Wait a second or two

## Expected Behavior
A sourcemap should be generated

## Code Example
Any project. I tested on a fresh new project from `react-native-cli`.

## Environment
```
  React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (4) x64 Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
      Memory: 142.78 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.3, 25.0.3, 26.0.1, 27.0.3, 28.0.1, 28.0.2, 28.0.3
        System Images: android-23 | Google APIs Intel x86 Atom_64, android-25 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.1 => 0.59.1
```

**Comment by kelset** [comment]
There was an issue with the bundler, the issue was reported here -> https://github.com/facebook/metro/issues/380

I think it's the same one reported? It is actually a CLI issue anyway, so if it still happens please open an issue there
