### ISSUE TITLE
IOS11.3 Linking can't open web URL 

### ISSUE THREAD

**Issue by s349856186** [facebook/react-native#24180]
## 🐛 Bug Report
<--
-canOpenURL: failed for URL: "https://www.facebook.com" - error: "This app is not allowed to query for scheme https"

-canOpenURL: failed for URL: "http://www.myweb.com" - error: "This app is not allowed to query for scheme http"

-->

## To Reproduce
<--
  Linking.canOpenURL(type+string).then(supported => {
        if (!supported) {
            console.log('Can\'t handle url: ' + string);
        } else {
            return Linking.openURL(type+string);
        }
    }).catch(err => console.error('An error occurred', err));
-->

## Expected Behavior
<--
  open web url
  IOS12 is normal, but IOS11 can't work, how can I solve it?
-->

## Code Example
<--
 Linking.canOpenURL(type+string).then(supported => {
        if (!supported) {
            console.log('Can\'t handle url: ' + string);
        } else {
            return Linking.openURL(type+string);
        }
    }).catch(err => console.error('An error occurred', err));
-->

## Environment
<--
  React Native Environment Info:
    System:
      OS: macOS 10.14.1
      CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
      Memory: 53.71 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.9.0 - /usr/local/bin/node
      npm: 6.5.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.3, macOS 10.14, 
      Android SDK:
        API Levels: 14, 15, 16, 17, 18, 19, 21, 22, 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.1, 27.0.3, 28.0.3
        System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.0 AI-171.4408382
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.6.3 => 16.6.3 
      react-native: ^0.57.8 => 0.57.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1
-->

**Comment by rickhanlonii** [comment]
Hey @s349856186, thanks for filing!

This doesn't appear to be a bug, you'll need to enable the scheme as documented [here](https://facebook.github.io/react-native/docs/linking#canopenurl). You may want to check out this [StackOverflow question](https://stackoverflow.com/questions/32870393/canopenurl-this-app-is-not-allowed-to-query-for-scheme-instragram) or ask for help over there as this issue tracker is not a help forum.

**Comment by s349856186** [comment]
@rickhanlonii Thanks for your reply.
How to enable the scheme?
I have added scheme to the info.plist.
![image](https://user-images.githubusercontent.com/2498958/55201434-f590e400-51fd-11e9-94ef-c4646fe5ceea.png)
