### ISSUE TITLE
componentDidUnmount not getting called

### ISSUE THREAD

**Issue by mehtanishant2010** [facebook/react-native#24199]

**Comment by AntoineDoubovetzky** [comment]
@mehtanishant2010 `componentDidUnmount` is not part of the component lifecycle methods.
You have to use [componentWillUnmount](https://reactjs.org/docs/react-component.html#componentwillunmount)

**Comment by Salakar** [comment]
Hey @mehtanishant2010 please could you add more information on any further issues; it's helpful for maintainers and helps triage issues quicker.

Also please see @AntoineDoubovetzky response.

Thanks
