### ISSUE TITLE
'folly/Portability.h' file not found

### ISSUE THREAD

**Issue by ankitgauravapporio** [facebook/react-native#24192]
![Screenshot 2019-03-29 at 11 54 51 AM](https://user-images.githubusercontent.com/44156688/55213535-9ccf4480-5219-11e9-83b8-9620685a046b.png)

**Comment by gunduzcihat** [comment]
same problem still goin for me.
'folly/Portability.h' file not found

**Comment by khachik** [comment]
```info 
  React Native Environment Info:
    System:
      OS: macOS Sierra 10.12.6
      CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
      Memory: 162.34 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
      npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 11.2, macOS 10.13, tvOS 11.2, watchOS 4.2
      Android SDK:
        API Levels: 28
        Build Tools: 28.0.3
        System Images: android-23 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 9.2/9C40b - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.1 => 0.59.1 
    npmGlobalPackages:
      react-native-cli: 2.0.1```
The same problem.

**Comment by buicong20** [comment]
React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (8) x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
      Memory: 3.37 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.12.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 22, 23, 25, 26, 27, 28
        Build Tools: 27.0.3, 28.0.0, 28.0.2, 28.0.3
        System Images: android-27 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.2 => 0.59.2 
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by gabrieletondi** [comment]
same here:

`React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 45.75 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.13.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 25, 26, 27
        Build Tools: 23.0.1, 25.0.2, 26.0.1, 26.0.2, 27.0.3, 28.0.3
        System Images: android-22 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.6 => 16.8.6
      react-native: 0.59.2 => 0.59.2
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
      react-native: 0.55.2`

**Comment by kelset** [comment]
Hello there 👋 this issue seems to be related to your experience upgrading between versions. We know this has been a [long lasting pain for the community](https://github.com/react-native-community/discussions-and-proposals/issues/68) so starting v0.59 we have introduced a new flow via the [new CLI](https://facebook.github.io/react-native/blog/#cli-improvements).

To upgrade to that version, you may still need to do some manual steps – we suggest you use [rn-diff-repo](https://github.com/pvinis/rn-diff-purge) to accomplish this.

Given that this is not strictly a bug with the library itself I'll close this, but if someone can create a repro that has this issue with a freshly created `react-native init` project we can reopen it and discuss it further 🤗

**Comment by khachik** [comment]
Hi Lorenzo,

thanks for the information provided.
The project has been freshly set up with 0.59, I haven't done any version
upgrades since then.
Can you please be more specific about what made you think it is an upgrade
problem or what should we if it is not an upgrade problem but occurs on a
fresh new setup?

**Comment by gunduzcihat** [comment]
I changed react-native to previous version and this error went away.

**Comment by gabrieletondi** [comment]
I resolved (on both 0.59.2 and 0.59.3) my removing from the Podfile:

pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"

Now I have only:

rn_path = '../node_modules/react-native'

  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

and my other custom dependencies.

**Comment by khachik** [comment]
@gabrieletondi I don't have any of those. Added podspec for Folly, didn't help. Tried react-native 0.59.2, 0.59.3, no luck.

**Comment by bartolkaruza** [comment]
I have a reliable Repro for this, it is not (only?) related to upgrading:

https://github.com/bartolkaruza/issue-24192-repro

Steps:
1. react-native init
2. Add Podfile & pod install
3. Open workspace in Xcode & build

```
    "react": "16.8.3",
    "react-native": "0.59.3",
```

Podfile
```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'test' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Flexbox Layout Manager Used By React Native
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # React Native
  pod 'React', path: '../node_modules/react-native', subspecs: [
    # Comment out any unneeded subspecs to reduce bundle size.
    'Core',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTBlob',
    'RCTCameraRoll',
    'RCTGeolocation',
    'RCTImage',
    'RCTNetwork',
    'RCTPushNotification',
    'RCTSettings',
    'RCTTest',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'RCTLinkingIOS'
  ]

end

```

Adding or removing this section in the Podfile had no effect
```
# Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
```

**Comment by gabrieletondi** [comment]
This is my current podfile

```
platform :ios, '9.0'

target 'MyCoolProj' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  rn_path = '../node_modules/react-native'

  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
  end

end

```

**Comment by bartolkaruza** [comment]
Adding the post_install is a confirmed workaround:

```
post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
  end
```
Leaving the issue open until we resolve the root cause (or update the doc to recommend this workaround 😄  ).


Thanks @gabrieletondi !

**Comment by gabrieletondi** [comment]
That's interesting. I've got this working without the post_install.
I had to add it because archiving was not working...  😮

**Comment by amphithere** [comment]
I had this issue and it seemed to resolve when I added 'CxxBridge' to the React subspecs. I then removed my Podfile.lock and Pods folder and pod installed. I hope maybe this helps?

**Comment by khachik** [comment]
@amphithere when I do it, it starts complaining about a missing "folly" pod.

**Comment by amphithere** [comment]
Sorry if this is a bit messy but this is my react native pod setup and it seems to be building successfully. 

` # Pods for KidengaRN
  pod 'React', :path => '../node_modules/react-native', subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTAnimation',
    'RCTActionSheet',
    'RCTBlob',
    'RCTCameraRoll',
    'RCTGeolocation',
    'RCTImage',
    'RCTPushNotification',
    'RCTSettings',
    'RCTTest',
    'RCTVibration',
    'RCTLinkingIOS'
  ]

  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'`

**Comment by khachik** [comment]
Thanks @amphithere, will try it if encounter this again. For now, just confirming that the solution by @gabrieletondi worked for me as well.
Thanks!

**Comment by issacnitin** [comment]
Encountered when I upgraded to 0.59.3
` ``
 post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
  end
```

This worked! Thanks @gabrieletondi

**Comment by jacobkrahn** [comment]
@issacnitin Where did you place this code

**Comment by dokutoshi** [comment]
> I had this issue and it seemed to resolve when I added 'CxxBridge' to the React subspecs. I then removed my Podfile.lock and Pods folder and pod installed. I hope maybe this helps?

I was able to eliminate the React post install script after adding the CXXBridge to the subspec.  

Good find @amphithere 

If others are looking for a solution to the duplicate UUID messages as a consequence of the post install script removing React, remove the post install script and CXXBridge to the subspec.

[!] [Xcodeproj] Generated duplicate UUIDs:

XCBuildConfiguration -- 
XCBuildConfiguration -- 
XCBuildConfiguration -- 
PBXBuildFile -- 
PBXBuildFile -- 
PBXBuildFile --

**Comment by cristianPerez** [comment]
Hey guys, I got the same issue, but I'm not sure what's wrong, I'm using RN + RNFirebase.

I've already tried the @gabrieletondi solution and is not working using RN 0.59.3 or 0.59.6 the same result.

this is my config:
```  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
      Memory: 165.95 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.15.0 - ~/.nvm/versions/node/v8.15.0/bin/node
      Yarn: 1.13.0 - ~/.nvm/versions/node/v8.15.0/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.15.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 22, 24, 25, 26, 27, 28
        Build Tools: 25.0.0, 27.0.3, 28.0.2, 28.0.3
        System Images: android-22 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.6 => 16.8.6 
      react-native: ^0.59.3 => 0.59.3 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```


When run `react-native run-ios` this is the output.

``` 
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening goingTubeApp.xcworkspace
```

Also using the @amphithere solution is not working.


PODFILE
```project 'goingTubeApp.xcodeproj/'
platform :ios, '9.0'
target 'gtApp' do

pod 'React', :path => '../node_modules/react-native', subspecs: [
  'Core',
  'CxxBridge',
  'DevSupport',
  'RCTText',
  'RCTNetwork',
  'RCTWebSocket',
  'RCTAnimation',
  'RCTActionSheet',
  'RCTBlob',
  'RCTCameraRoll',
  'RCTGeolocation',
  'RCTImage',
  'RCTPushNotification',
  'RCTSettings',
  'RCTTest',
  'RCTVibration',
  'RCTLinkingIOS'
]

pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'Firebase/Core', '~> 5.20.1'
  pod 'Firebase/Firestore', '~> 5.20.1'
  pod 'Firebase/Messaging', '~> 5.20.1'
  pod 'Firebase/Analytics', '~> 5.20.1'
  pod 'GoogleAppMeasurement', '~> 5.8.0'
  pod 'GoogleSignIn'

  pod 'Fabric', '~> 1.9.0'
  pod 'Crashlytics', '~> 3.12.0'

  target 'goingTubeApp-tvOSTests' do
    inherit! :search_paths
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  end

  target 'goingTubeAppTests' do
    inherit! :search_paths
  end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
  end

end
```


I've already updated my Xcode, to 10.2.1 and now is not working, my last RN was 0.57.7, so I need to fix this problem.

The problem starts when I've installed Crashlytics on IOS because on Android is on production.

```# Crashlytics
  pod 'Fabric', '~> 1.9.0'
  pod 'Crashlytics', '~> 3.12.0' 
```

Please let me know if anyone knows what can I do?

**Comment by amphithere** [comment]
@cristianPerez I had an issue with iOS too when I upgraded to 0.59.3 and I essentially had to completely regenerate my iOS project by using the `react-native eject` command.

It's not very fun, but after doing that my project worked well with pods. I'm currently using React Native Firebase and it's running with Crashlytics. Here's my podfile just in case that helps. 

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KidengaRN' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
   # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
    'RCTBlob',
    'RCTGeolocation',
    'RCTImage',
    'RCTPushNotification',
    'RCTVibration',
    'RCTSettings'
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'


  # Pods for KidengaRN

  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Auth', '~> 5.15.0'
  pod 'Firebase/Firestore', '~> 5.15.0'
  pod 'Firebase/Functions', '~> 5.15.0'
  pod 'Firebase/Messaging', '~> 5.15.0'
  pod 'Firebase/DynamicLinks', '~> 5.15.0'
  pod 'Firebase/RemoteConfig', '~> 5.15.0'
  pod 'Fabric', '~> 1.7.13'
  pod 'Crashlytics', '~> 3.10.7'
  pod 'Firebase/Performance', '~> 5.15.0'

  pod 'FBSDKCoreKit',  '~> 4.42.0'
  pod 'FBSDKLoginKit',  '~> 4.42.0'
  pod 'FBSDKShareKit' , '~> 4.42.0'
  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'


  target 'KidengaRNTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'KidengaRN-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KidengaRN-tvOS

  target 'KidengaRN-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end

    if target.name == "yoga"
      target.remove_from_project
    end
  end
end

**Comment by SwiftyWang** [comment]
> Adding the post_install is a confirmed workaround:
> 
> ```
> post_install do |installer|
>     installer.pods_project.targets.each do |target|
>       if target.name == "React"
>         target.remove_from_project
>       end
>     end
>   end
> ```
> Leaving the issue open until we resolve the root cause (or update the doc to recommend this workaround 😄 ).
> 
> Thanks @gabrieletondi !

Still waiting for an official solution.

**Comment by KumariShalini** [comment]
i have cleaned by :- 
watchman watch-del-all && rm -rf ~/.rncache/* && rm -rf /tmp/metro-bundler-cache-* && rm -rf /tmp/haste-map-react-native-packager-* && rm -rf node_modules/ && npm install

still i am getting error in xcode 10  'folly/Portability.h' file not found, also cleaned the folder in xcode...

can anyone help for this... thanx

**Comment by santiblanko** [comment]
same error here :( in iOS.

**Comment by londonoliver** [comment]
Try repeatedly running the project in Xcode until it succeeds (seriously)

**Comment by londonoliver** [comment]
Try repeatedly running the project in Xcode until it succeeds

**Comment by londonoliver** [comment]
Try repeatedly running the project in Xcode until the build succeeds

**Comment by londonoliver** [comment]
Try repeatedly running the project in Xcode until it builds successfully

**Comment by marlosirapuan** [comment]
Worked for me like this:

In Xcode -> File -> Workspaces settings -> Build System changed to "Legacy Build System" (both, shared and per-user)

and following what they have already put:

```ruby
  rn_path = '../node_modules/react-native'

  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]
  pod 'Folly', podspec: "#{rn_path}/third-party-podspecs/Folly.podspec"  
  
  # Project libs
  # pod 'RNCAsyncStorage', path: '../node_modules/@react-native-community/async-storage'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
  end  
```

**Comment by gurkamal-io** [comment]
So far using the workaround. This fixed the podfile issue on react native 0.59.8 allowing me to consume @mapbox/react-native-mapbox-gl

I am curious about the difference between
```  
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == "React"
            target.remove_from_project
        end
    end
end  
```
and 
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end

    if target.name == "yoga"
      target.remove_from_project
    end
  end
end
```

Should yoga be included for the workaround?

Also after the workaround I am getting an error regarding duplicate UUIDs in the xcodeproject:
```
[!] [Xcodeproj] Generated duplicate UUIDs:

XCBuildConfiguration -- 
XCBuildConfiguration -- 
PBXBuildFile -- 
PBXBuildFile -- 
PBXBuildFile -- 
PBXBuildFile -- 
```
Is this anything to be worried about?
The projects runs perfectly on android and ios, but just want to take precautions going forward.

**Comment by hopewise** [comment]
In my case the problem occurred when I tried to link `@react-native-community/async-storage` in Podfile it was installing react 0.11.0 version, then I tried to keep the current version of react by:

```
  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
```
and that was the start of the issue, wasted two days.

I've deleted `Pods` folder and `pod install`
and
`rm -rf node_modules` 
`npm start -- --reset-cache`

and then I can work again.. for the meantime, I decided not to use that library

**Comment by mhadam** [comment]
I found these answers only worked for me if I enabled the legacy build system.
After that I just needed the `post_install` bit for `React`.

**Comment by mi-mazouz** [comment]
I tried all of the solutions mentioned here but still not working for me

**Comment by alanfagner** [comment]
me too

**Comment by ruslanzharkov** [comment]
> This is my current podfile
> 
> ```
> platform :ios, '9.0'
> 
> target 'MyCoolProj' do
>   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
>   # use_frameworks!
> 
>   rn_path = '../node_modules/react-native'
> 
>   pod 'yoga', path: "#{rn_path}/ReactCommon/yoga"
>   pod 'React', path: rn_path, subspecs: [
>     'Core',
>     'CxxBridge',
>     'DevSupport',
>     'RCTActionSheet',
>     'RCTAnimation',
>     'RCTGeolocation',
>     'RCTImage',
>     'RCTLinkingIOS',
>     'RCTNetwork',
>     'RCTSettings',
>     'RCTText',
>     'RCTVibration',
>     'RCTWebSocket',
>   ]
>   pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"
> 
>   post_install do |installer|
>     installer.pods_project.targets.each do |target|
>       if target.name == "React"
>         target.remove_from_project
>       end
>     end
>   end
> 
> end
> ```

Awesome! This helped me, thanks a lot!

**Comment by yuanfux** [comment]
Do confirm a fix without the post install script by adding CxxBridge to subspecs.
Using RN0.59.8.

```
target 'app' do
  # use_frameworks!
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge'
  ]

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

end
```
