### ISSUE TITLE
CameraRoll.getPhotos need groupTypes

### ISSUE THREAD

**Issue by scarlac** [facebook/react-native#24208]
## 💥 Regression Report
In RN v0.58 `CameraRoll.getPhotos` without specifying `groupTypes` would return photos on iOS 12.2. After upgrading to RN v0.59, `getPhotos` no longer returns photos. The breaking change was not documented in the release notes and generates no warnings.

## Last working version

Worked up to version:
React Native v0.58.6

Stopped working in version:
React Native v0.59.0

## To Reproduce
**On iOS (12.2)**
```
import { CameraRoll } from 'react-native';
// ...
CameraRoll.getPhotos({
  first: 20,
  assetType: 'Photos',
//  groupTypes: 'All',
}).then(r => r.edges.length === 0)
```

## Expected Behavior
`r.edges.length` should be non-zero when there are photos in the camera roll.

## Code Example
See above section "To Reproduce". I cannot provide an expo snack as it does not support RN v0.59 (I think?).

## Environment
```
⚡️ react-native info
info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
      Memory: 188.93 MB / 32.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.2.0 - ~/.nvm/versions/node/v11.2.0/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v11.2.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 27.0.3, 28.0.2, 28.0.3
        System Images: android-25 | Google Play Intel x86 Atom, android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: ^0.59.2 => 0.59.2 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

Related community ticket:
https://github.com/react-native-community/react-native-cameraroll/issues/18#issuecomment-478175321

**Comment by JoshuaGross** [comment]
Can we take care of this in the community repo? CameraRoll was pulled out of core. See here as well: https://github.com/facebook/react-native/issues/24140

**Comment by scarlac** [comment]
@JoshuaGross Will documentation in RN also be updated if we update the community repo? Current docs are incorrect on the official site, which is what this is pointing out.
