### ISSUE TITLE
borderRadius style prop not working on FlatLists

### ISSUE THREAD

**Issue by mickael-h** [facebook/react-native#24207]
## 🐛 Bug Report
The FlatList content ignores the borderRadius style, and the content container stays perfectly rectangular.
Using RN v0.59.2

## To Reproduce
Create a FlatList component, use the borderRadius style prop in contentContainerStyle, or style, or the parent view's style. Insert elements with a background color. See that the list still has sharp angles.

## Expected Behavior
A list with round edges. Something like that:
![image](https://user-images.githubusercontent.com/7953005/55259401-d5950b00-5265-11e9-956c-bef9a23bf62a.png)

## Code Example
https://snack.expo.io/H1ZcOl3OV

## Environment
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 4.45 GB / 15.86 GB
    Binaries:
      Yarn: 1.7.0 - C:\Users\Mickael-AccoPilot\AppData\Roaming\npm\yarn.CMD
      npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5264788

**Comment by murtraja** [comment]
Fixed https://snack.expo.io/@mmrxyz/vengeful-donut---fixed
You forgot to add overflow: 'hidden'

**Comment by JKCooper2** [comment]
It does look like a border radius on the contentContainerStyle doesn't apply correctly, or at least I couldn't figure out how to make it work.

I've been able to get the behaviour I think you are looking for by using the list indexes and listview style:
https://snack.expo.io/@jkcooper/rn24207---flatlist-border-radius.

It's probably worth keeping this issue open but clarifying the contentContainerStyles borderRadius doesn't get applied

**Comment by mickael-h** [comment]
Apparently the border radius won't apply unless overflow:hidden is specified.
Maybe it's the expected behavior, but it's not trivial at all.
They should either update the documentation, or trigger a warning when the programmer uses "borderRadius" on the contentContainerStyle.
