### ISSUE TITLE
Question: Integration with existing app without pods

### ISSUE THREAD

**Issue by zinoviev** [facebook/react-native#24205]
Hi everyone. Docs guide https://facebook.github.io/react-native/docs/integration-with-existing-apps.html works really well for pods integration case.

But in the real world app we face what not all libs from npm works with podfile.

I've try to link pure existing swift project with RN from node_modules to mimic react-native init project template(ie - drag React.xcproject and buddies), but getting third-party(glog etc) libs compilation errors.

Potentially we can use init template and put big swift app into ios folder of rn project subfolder, but it will be real wiered as RN is a little subset of bigger project.

**Comment by kelset** [comment]
(there are some discussion related to this here https://github.com/react-native-community/discussions-and-proposals/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc )
