### ISSUE TITLE
npm install  not working

### ISSUE THREAD

**Issue by yehoan** [facebook/react-native#24203]
## 🐛 Bug Report

D:\code\RN>npm install
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\fbemitter-6f296f8a\package.json'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\fbemitter-6f296f8a\README.md'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\create-react-context-7f6b785d\package.json'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\create-react-context-7f6b785d\LICENSE'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\fbemitter-6f296f8a\LICENSE'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\create-react-context-7f6b785d\README.md'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\cross-spawn-bc7655f2\lib\enoent.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\fbemitter-6f296f8a\index.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\which-b7654bfc\bin\which'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\cross-spawn-bc7655f2\lib\parse.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\fbemitter-6f296f8a\PATENTS'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\react-navigation-e0aae966\src\navigators\__tests__\__snapshots__\.DS_Store'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\react-navigation-e0aae966\src\navigators\__tests__\__snapshots__\SwitchNavigator-test.js.snap'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\react-navigation-e0aae966\src\navigators\__tests__\__snapshots__\TabNavigator-test.js.snap'
npm WARN tar ENOENT: no such file or directory, lstat 'D:\code\RN\node_modules\.staging\react-navigation-e0aae966\src'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\react-native-sentry-4a354d62\android\src\main\java\io\sentry\ArrayUtil.java'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\react-native-sentry-4a354d62\android\src\main\java\io\sentry\MapUtil.java'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\react-native-sentry-4a354d62\android\src\main\java\io\sentry\RNSentryEventEmitter.java'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\react-native-sentry-4a354d62\android\src\main\java\io\sentry\RNSentryModule.java'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\metro-361132b0\src\DeltaBundler\Serializers\deltaJSBundle.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\react-native-sentry-4a354d62\android\src\main\java\io\sentry\RNSentryPackage.java'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\metro-361132b0\src\DeltaBundler\Serializers\deltaJSBundle.js.flow'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\metro-361132b0\src\DeltaBundler\Serializers\getAllFiles.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\metro-361132b0\src\DeltaBundler\Serializers\getAllFiles.js.flow'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\metro-361132b0\src\DeltaBundler\Serializers\getAssets.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\metro-361132b0\src\DeltaBundler\Serializers\getAssets.js.flow'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\metro-361132b0\src\DeltaBundler\Serializers\getRamBundleInfo.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\metro-361132b0\src\DeltaBundler\Serializers\getRamBundleInfo.js.flow'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\node-notifier-968f599b\vendor\notifu\notifu.exe'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\react-redux-1eb0b0d0\lib\utils\isPlainObject.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\react-redux-1eb0b0d0\lib\utils\PropTypes.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\react-redux-1eb0b0d0\lib\utils\shallowEqual.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\react-redux-1eb0b0d0\lib\utils\Subscription.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\react-redux-1eb0b0d0\lib\utils\verifyPlainObject.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\react-redux-1eb0b0d0\lib\utils\warning.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\react-redux-1eb0b0d0\lib\utils\wrapActionCreators.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\metro-361132b0\src\integration_tests\basic_bundle\AssetRegistry.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\metro-361132b0\src\integration_tests\basic_bundle\AssetRegistry.js.flow'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\metro-361132b0\src\integration_tests\basic_bundle\Bar.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\metro-361132b0\src\integration_tests\basic_bundle\Bar.js.flow'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\metro-361132b0\src\integration_tests\basic_bundle\ErrorBundle.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\metro-361132b0\src\integration_tests\basic_bundle\ErrorBundle.js.flow'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\metro-361132b0\src\integration_tests\basic_bundle\Foo.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\metro-361132b0\src\integration_tests\basic_bundle\Foo.js.flow'
npm WARN tar ENOENT: no such file or directory, lstat 'D:\code\RN\node_modules\.staging\metro-361132b0\src'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\fbjs-9ec54ac2\lib\__mocks__\ErrorUtils.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\fbjs-9ec54ac2\lib\__mocks__\base62.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\fbjs-9ec54ac2\lib\__mocks__\crc32.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\fbjs-9ec54ac2\lib\__mocks__\fetch.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\fbjs-9ec54ac2\lib\__mocks__\fetchWithRetries.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\fbjs-9ec54ac2\lib\__mocks__\nullthrows.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\fbjs-9ec54ac2\lib\getActiveElement.js.flow'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\fbjs-9ec54ac2\lib\ErrorUtils.js.flow'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\fbjs-9ec54ac2\lib\getDocumentScrollElement.js.flow'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\fbjs-9ec54ac2\lib\_shouldPolyfillES6Collection.js.flow'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\fbjs-9ec54ac2\lib\getElementPosition.js.flow'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\fbjs-9ec54ac2\lib\Style.js.flow'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\fbjs-9ec54ac2\lib\getElementRect.js.flow'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\fbjs-9ec54ac2\lib\areEqual.js.flow'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\fbjs-9ec54ac2\lib\getMarkupWrap.js.flow'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\fbjs-9ec54ac2\lib\Map.js.flow'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\fbjs-9ec54ac2\lib\getScrollPosition.js.flow'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\fbjs-9ec54ac2\lib\base62.js.flow'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\fbjs-9ec54ac2\lib\getStyleProperty.js.flow'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\fbjs-9ec54ac2\lib\TokenizeUtil.js.flow'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\fbjs-9ec54ac2\lib\getUnboundedScrollPosition.js.flow'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\fbjs-9ec54ac2\lib\camelize.js.flow'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\fbjs-9ec54ac2\lib\getViewportDimensions.js.flow'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\fbjs-9ec54ac2\lib\xhrSimpleDataSerializer.js.flow'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\fbjs-9ec54ac2\lib\groupArray.js.flow'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\fbjs-9ec54ac2\lib\camelizeStyleName.js.flow'
npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\fbjs-9ec54ac2\lib\hyphenate.js.flow'

npm WARN tar ENOENT: no such file or directory, open 'D:\code\RN\node_modules\.staging\@ant-design\react-native-76e5cdb6\es\search-bar\style\index.js'
npm ERR! code ENOGIT
npm ERR! Error while executing:
npm ERR! undefined ls-remote -h -t ssh://git@github.com/expo/vector-icons.git
npm ERR!
npm ERR! undefined
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administration\AppData\Roaming\npm-cache\_logs\2019-03-29T15_24_09_378Z-debug.log

D:\code\RN>

This is package.json
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject"
  },
  "dependencies": {
    "@ant-design/react-native": "3.0.6",
    "dva-core": "^1.4.0",
    "expo": "^32.0.0",
    "js-combinatorics": "^0.5.4",
    "lodash.clonedeep": "^4.5.0",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-native-calendar-select": "^0.1.2",
    "react-native-iphone-x-helper": "^1.2.0",
    "react-native-render-html": "^3.10.0",
    "react-native-ultimate-listview": "^3.3.0",
    "react-navigation": "^2.12.1",
    "react-navigation-redux-helpers": "2.0.5",
    "react-redux": "^5.0.7",
    "rn-event-emitter": "^1.1.0",
    "sentry-expo": "^1.11.2"
  },
  "devDependencies": {
    "babel-preset-expo": "^5.0.0"
  },
  "private": true
}

## Environment

node: v10.15.3
npm: 6.4.1
system:windows 10 
once  i  use  it is okay   but  this time  i  change  my  computer  and  i not know  the  reason  so...

**Comment by yehoan** [comment]
once  i  just  use  npm  install or  yarn  add   it is okay   it  is  due to version?

**Comment by yehoan** [comment]
D:\code\RN>npm run react-native info
npm ERR! missing script: react-native

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administration\AppData\Roaming\npm-cache\_logs\2019-03-29T15_41_05_358Z-debug.log

**Comment by Salakar** [comment]
Hey @yehoan 👋 

Thanks for making this issue - it should however probably be created on the expo repo please, it's located here: https://github.com/expo/expo

Thanks, and good luck!
