### ISSUE TITLE
Question: I have been trying to get permission to access the geolocation in emulator using the documentation but it always directly goes to  permission denied by deafult.

### ISSUE THREAD

**Issue by shasanka** [facebook/react-native#24212]
```
export async function request_location_runtime_permission() {
  try {
    console.log("test");
    const granted = await PermissionsAndroid.request(
      PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION,
      {
        title: "permission for location",
        message:
          "permit location",
        buttonNeutral: "Ask Me Later",
        buttonNegative: "Cancel",
        buttonPositive: "OK"
      }
    );
      if (granted === PermissionsAndroid.RESULTS.GRANTED) {
          console.log('permission granted');
        } else {
          console.log('permission denied');
        }
      } catch (err) {
        console.warn(err);
      }
}

export default class App extends Component {
   async componentDidMount() {
     await request_location_runtime_permission();
   }

  getUserLocationHandler = () => {
    navigator.geolocation.getCurrentPosition(
      position => {
        console.log(position.coords);
      },
      error => {
        console.log(error);
      }
    );
  };
  render() {
    return (
      <View style={styles.container}>
        {/* <Text>it works</Text> */}
        <Text>React Native Runtime Permission Request</Text>
        <FetchUserLocation onGetLocation={this.getUserLocationHandler} />
      </View>
    );
  }
}
```

![Screenshot (111)](https://user-images.githubusercontent.com/8522473/55276078-054f1c00-5315-11e9-973e-c693808893b5.png)

I have tried everything but nothing solves the issue.
It doesn't prompts any dialogue box to grant or deny permission.
As the app starts it shows permission denied.

buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"

Even i have added : <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
in AndroidManifest.xml , still nothing `works.```

**Comment by jake41** [comment]
@shasanka Can you please update the question with correct issue templates. I am also facing the same.

**Comment by jake41** [comment]
@shasanka I am also facing the same issue. Can you repost the issue with correct issue template?

**Comment by shasanka** [comment]
> @shasanka I am also facing the same issue. Can you repost the issue with correct issue template?

@jake41 i solved the issue , not  big one , you just need to uninstall the app from the emulator , then run this command in your project folder ide terminal : react-native start --reset-cache
this will reset cache and install the app again on the emulator , try this it will fix your problem , if not then comment again :)

**Comment by jake41** [comment]
@shasanka  thats great! . Unfortunately I am getting the same error after trying out the steps you have mentioned. I uninstalled the app from real-device , then shutdown and restarted with react-native start --reset-cache. After that ran the app again in the real device. But stiil getting the same access denied. On checking the value of granted I am getting never_ask_again as the value.
