### ISSUE TITLE
react-native run-android: Error::app:transformDexArchiveWithExternalLibsDexMergerForDebug

### ISSUE THREAD

**Issue by ChenJunhan** [facebook/react-native#24225]
react-native run-android
warn JS server not recognized, continuing with build...
info Building and installing the app on the device (cd android && gradlew.bat app:installDebug)...
Starting a Gradle Daemon, 1 stopped Daemon could not be reused, use --status for details
> Task :app:preBuild UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :app:compileDebugAidl NO-SOURCE
> Task :app:compileDebugRenderscript UP-TO-DATE
> Task :app:checkDebugManifest UP-TO-DATE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :app:prepareLintJar UP-TO-DATE
> Task :app:generateDebugSources UP-TO-DATE
> Task :app:javaPreCompileDebug UP-TO-DATE
> Task :app:mainApkListPersistenceDebug UP-TO-DATE
> Task :app:bundleDebugJsAndAssets SKIPPED
> Task :app:generateDebugResValues UP-TO-DATE
> Task :app:generateDebugResources UP-TO-DATE
> Task :app:mergeDebugResources UP-TO-DATE
> Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
> Task :app:processDebugManifest UP-TO-DATE
> Task :app:processDebugResources UP-TO-DATE
> Task :app:compileDebugJavaWithJavac UP-TO-DATE
> Task :app:mergeDebugShaders UP-TO-DATE
> Task :app:compileDebugShaders UP-TO-DATE
> Task :app:generateDebugAssets UP-TO-DATE
> Task :app:mergeDebugAssets UP-TO-DATE
> Task :app:copyDebugBundledJs SKIPPED
> Task :app:validateSigningDebug UP-TO-DATE
> Task :app:signingConfigWriterDebug UP-TO-DATE
> Task :app:transformClassesWithDexBuilderForDebug UP-TO-DATE
> Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 1 column 29 path $[0].name

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 30s
20 actionable tasks: 1 executed, 19 up-to-date
error Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
error Command failed: gradlew.bat app:installDebug

Environment：
* node: 10.15.3
* python: 2.7
* jdk: 1.8
* OS: Windows 10
* CPU: (4) x64 Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz
* Memory: 7.18 GB / 11.95 GB
* Yarn: 1.13.0 - D:\Program Files\nodejs\node_global\yarn.CMD
* npm: 6.4.1 - D:\Program Files\nodejs\npm.CMD

It is reporting an error when I create a new project.

**Comment by ChenJunhan** [comment]
@react-native-bot Hi, I have updated.

**Comment by UnboundGodz** [comment]
Im running into the exact same issue, thoughts?
`  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (16) x64 AMD Ryzen 7 1700X Eight-Core Processor
      Memory: 6.32 GB / 15.95 GB
    Binaries:
      Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.7.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5314842`

**Comment by UnboundGodz** [comment]
Also ive updated variables for both user and system and it still gives that error.

**Comment by ChenJunhan** [comment]
@UnboundGodz I havn't also solve the issue,but it can run normal when I toggle the version of 58.0.0.
