### ISSUE TITLE
Android can't load web in React-native 0.57

### ISSUE THREAD

**Issue by CocoaZX** [facebook/react-native#24222]

**Comment by CocoaZX** [comment]
Everything without web in Android is good.


> class MyWeb extends BaseComponent {
      render() {
    const { url, title = '网页' } = this.props.navigation.state.params;
    return (
      <SafeAreaView>
        <WebView
          source={{ url }}
          style={{
            marginTop: 20, width: 200, height: 300, backgroundColor: '#333',
          }}
          onLoad={() => console.log(`${url}`)}
          onLoadEnd={() => console.log('onLoadEnd')}
          onLoadStart={() => console.log('onLoadStart')}
onError={e => console.log(e)}
          mixedContentMode="always"
        />
      </SafeAreaView>
    );
  }
}

console.log 'onLoadStart' and ‘onLoadEnd’ ，NO error log, and the url is correct.iOS can load it.

react-native info:

`  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
      Memory: 8.73 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.11.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 27, 28
        Build Tools: 28.0.3
        System Images: android-Q | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.57.8 => 0.57.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1`

**Comment by CocoaZX** [comment]
Fix this.
wrong code "source={{ url }}" , should be "source={{ uri:url }}". But iOS Always use url ,and it's work in iOS. Advice to unified them

**Comment by dulmandakh** [comment]
please use https://github.com/react-native-community/react-native-webview, because WebView in React Native is deprecated and will be removed in the future. Thank you

**Comment by CocoaZX** [comment]
> please use https://github.com/react-native-community/react-native-webview, because WebView in React Native is deprecated and will be removed in the future. Thank you

While,I use react-native-webview, the error say
RNCWKWebView not found,
Look like NativeComponect not link to project. I use react-native link commond

**Comment by dulmandakh** [comment]
Could you please open an issue, and let developer know about it. Thank you

**Comment by CocoaZX** [comment]
I can't reopen because not me close this issues

**Comment by CocoaZX** [comment]
Where can I open the  react-native-webview, issus

**Comment by dulmandakh** [comment]
Sorry, please open an issue at https://github.com/react-native-community/react-native-webview
