### ISSUE TITLE
[iOS] Opacity prop of Text applies double times.

### ISSUE THREAD

**Issue by PaxLyj** [facebook/react-native#24229]
## 🐛 Bug Report
On iOS, `Text` component with style prop `opacity` applies twice.
It seems the base class of `RCTTextView` is `RCTView`, and it causes the style prop `opacity` applies double times to `RCTTevtView`.

Roughly, delete[ this line](https://github.com/facebook/react-native/blob/0b62ff0b948e16819ae4f074a743b5de2f482268/Libraries/Text/BaseText/RCTBaseTextViewManager.m#L31) in `RCTBaseTextViewManager.m` fix this issue.
## To Reproduce
<img src="https://user-images.githubusercontent.com/15841604/55310661-fe064a80-549b-11e9-8e67-1435409ea944.png" width="250"/> <img src="https://user-images.githubusercontent.com/15841604/55310689-10808400-549c-11e9-8127-a8001fe755d3.png" width="250"/> 
```js
//Please check the example code below.
const styles = StyleSheet.create({
  rgba: {
    fontSize: 20,
    marginBottom: 10,
    color: 'rgba(0, 0, 0, 0.25)'
  },
  opacity_50: {
    fontSize: 20,
    marginBottom: 10,
    color: '#000',
    opacity: 0.5
  },
  opacity_25: {
    fontSize: 20,
    marginBottom: 10,
    color: '#000',
    opacity: 0.25
  },
  hexa: {
    fontSize: 20,
    color: '#00000040' //rrggbbaa
  }
}
```
## Expected Behavior
It should be rendered as same as Android (right image above).

## Code Example
https://snack.expo.io/Hy8RhMkYN

In iOS environment, compare the rendered colors of Text component with style `{ opacity: 0.5 }` and `{ color: 'rgba(0, 0, 0, 0.25)' }` - those are seems same.
## Environment
```
React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
      Memory: 225.85 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.5.0 - ~/.nvm/versions/node/v11.5.0/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v11.5.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.2, 23.0.3, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.2, 28.0.3
        System Images: android-19 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-26 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.2 => 0.59.2 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-create-library: 3.1.2
```

**Comment by shergin** [comment]
cc @ericlewis

**Comment by lukewalczak** [comment]
I think the problem exists in [text attributes file](https://github.com/facebook/react-native/blob/master/Libraries/Text/RCTTextAttributes.m#L47) where `opacity` value is multiplied by `textAttributes->_opacity`. Removing that multiplication should fix the problem.

**Comment by michalchudziak** [comment]
@lukewalczak Perhaps you're right. Would you mind sending a PR with your proposal?

**Comment by ericlewis** [comment]
Another angle to look at this would be how we solved semi-transparent backgrounds here: https://github.com/facebook/react-native/pull/23872

It’s likely we can apply a similar solution for opacities.

**Comment by lukewalczak** [comment]
Hmm, but what can be the reason to keep that `multiplication` in `opacity` value?

**Comment by ericlewis** [comment]
@lukewalczak indeed, the multiplication does seem like a mistake that probably needs to be fixed. If it addresses the issue at hand then cool. I can open a PR if you like, it’s a relatively simple thing to test.

**Comment by ericlewis** [comment]
Seems like the * was meant to be a comment like the rest, just bad copy paste or something.

**Comment by lukewalczak** [comment]
I've also tested your approach and setting the initial value for `  self.textAttributes.opacity = 1.0` is fixing the issue.

**Comment by PaxLyj** [comment]
@lukewalczak Nice, both solutions solve the problem. Thanks for work.
It seems simpler and clearer to remove ` * textAttributes->_opacity` from the line that you mentioned.

**Comment by shergin** [comment]
Let's discuss that in a PR!

**Comment by lukewalczak** [comment]
Unfortunately, the solution above is fixing the problem only for `text` without `backgroundColor`. I've spent some time debugging the issue, but cannot find a solution which will fix it completely.

**Comment by shergin** [comment]
I reread everything one more time, and now I actually think that iOS behavior is correct, and Android one is not.

@PaxLyj From the code example in the description is not clear which kind of nesting of components we have, can you improve the example?

@ericlewis, @lukewalczak What makes you think that we should NOT multiply `opacity`? That's how opacity works in layers, right? What should render this example: `<div opacity=0.5><div opacity=1>hello world<div></div>`?

**Comment by shergin** [comment]
cc @rigdern

**Comment by shergin** [comment]
Oh, I see now, the issue is not about nested text components at all!

So, the solution should be pretty simple, we should just add
`self.textAttributes.opacity = NAN;` similarly to what we did in #23872.

**Comment by lukewalczak** [comment]
Hey, I've checked your PR and it's fixing the problem with a `text` but unfortunately, once you add a `backgroundColor` it seems to be broken again.

<img width="1272" alt="Screenshot 2019-04-13 at 12 37 40" src="https://user-images.githubusercontent.com/22746080/56078521-6e409480-5de9-11e9-9c2e-a18a26b28ed1.png">

**Comment by PaxLyj** [comment]
@lukewalczak Well, you may thought that text with `OPACITY BG` is not rendered as translucent, right?
The conbined style of that text component is -
```js
  color: '#000000',
  backgroundColor: '#ff0000',
  opacity: 0.5,
```
and I think it's reasonable that applying opacity to `Text`component once, make both color of text and background as 50% of translucency. (Which is as shown in the image you attached.)

On the other hand, the text components of both `RGBA BG` and `HEXA BG` has 50% of translucency, so the colors of texts are mixed with each color of background.
