### ISSUE TITLE
Discussion: NO way to set Accessibility Focus Order

### ISSUE THREAD

**Issue by Leogio360** [facebook/react-native#24239]
I would like to define my own focus order for the screen readers, but currently there seems to be no way to do so.
It's a critical feature, particularly for those who wants to implement accessibile drag and drop gestures in their apps. 
Am I missing something or this problem was not taken into account when the Accessibily APIs was developed?

**Comment by hramos** [comment]
As the discussion template says, issues posted as Discussions will be closed. We're only tracking bug reports in this repository.
