### ISSUE TITLE
Can't run a fresh new project (unable to resolve module ./index) and bla bla bla

### ISSUE THREAD

**Issue by syedamirali14** [facebook/react-native#24231]
i heard that this issue has been resolved but it is not this error is appearing in a new fresh project

Environment:
  OS: Windows 10
  Node: 10.15.3
  Yarn: Not Found
  npm: 6.4.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5314842

Packages: (wanted => installed)
  react: 16.8.3 => 16.8.3
  react-native: ^0.55.4 => 0.55.4

**Comment by syedamirali14** [comment]
i was using react native 0.59.2 when it give me above error i downgraded it then

**Comment by affanhashone** [comment]
Inside : node_modules\react-native\scripts
open: launchPackager.bat
replace and add : node "%~dp0..\cli.js" --reactNativePath ../ --projectRoot ../../../ start

**Comment by syedamirali14** [comment]
i have downgraded to react native 55.4 to make my project run :@

**Comment by affanhashone** [comment]
@syedamirali14  Please try that with 59.2 , it will get fixed.

**Comment by danielgindi** [comment]
Didn't for me. 0.59.3 didn't also.

**Comment by Kida007** [comment]
I also had the issue , have to delete the ios builds folder every time to run a bundler. 
```rm -rf ios/build```
