### ISSUE TITLE
[TextView] borders being added on iphone 6 + 

### ISSUE THREAD

**Issue by jawadrehman** [facebook/react-native#2424]
For some reason, borders are being added on iPhone 6+ on the text. Any known fix for this ? 
We are using react-native v0.8
Thanks.
![ios simulator screen shot 24-aug-2015 11 27 19 am](https://cloud.githubusercontent.com/assets/1839153/9438107/46fa2560-4a53-11e5-9bfa-f6958e30a5be.png)

**Comment by ssssssssssss** [comment]
Duplicate #2018

**Comment by grabbou** [comment]
Might be related to #1870 issue

**Comment by brentvatne** [comment]
Indeed dup of #2018
