### ISSUE TITLE
Discussion: Add animation speed and/or type control to InputAccessoryView

### ISSUE THREAD

**Issue by pribeh** [facebook/react-native#24241]
Currently, when dismissing a screen which houses InputAccessoryView, the InputAccessoryView slides down at a set (slow) speed. If the screen's transition is faster than the transition of the InputAccessoryView (usually the case) then the InputAccessoryView appears to float on the screen until its own transition completes. If the animations are different then the result is just bad UX.

The InputAccessoryView should support some sort of transition handling such as speed and type to help match different screen transitions. Fade, slide left, right, top, bottom and duration would be optimal options to support for wide use cases.

```
<InputAccessoryView 
     duration={200}
     animation={slideDown}
/>
```

**Comment by hramos** [comment]
Closing as advised in the discussion template. We're only tracking bug reports in this repository.
