### ISSUE TITLE
Async/Await does not work out of the box on iOS/Android with a modern babel config

### ISSUE THREAD

**Issue by karanjthakkar** [facebook/react-native#24244]
## 🐛 Bug Report

With the new JSC for Android, apps with minimum iOS 10 support [can work with a modern babel config](https://twitter.com/geekykaran/status/1082218546799755266) that [removes unnecessary babel plugins from the metro RN babel preset](https://gist.github.com/karanjthakkar/3241808022a75d8068f35a33b57e90c5). This also means that async/await, which is supported in both those base versions, should work out of the box. However, on both platform, async calls only seem to be "flushed" if a user does a tap gesture.

This might be similar to an issue reported before: https://github.com/facebook/react-native/issues/19572 But the cause in that issue doesn't seem to be the case.

Here's a gif explaining the behaviour on ios and android:

<p>
	<img src="https://user-images.githubusercontent.com/1824298/55348815-02d4f980-54b0-11e9-8382-dfe8946b595b.gif" width="300">
	<img src="https://user-images.githubusercontent.com/1824298/55348816-02d4f980-54b0-11e9-96bb-8912c65c729e.gif" width="300">
<p>

## To Reproduce

- Clone: `git@github.com:karanjthakkar/ModernBabelConfigIssue.git`
- Run `npm install`
- Run the following for each platform to see the broken build:
	- iOS: `RCT_NO_LAUNCH_PACKAGER=1 FORCE_BUNDLING=1 react-native run-ios`
	- Android: `react-native run-android --no-packager`
- You can then checkout the branch named `working` and that will work. 

The [only difference between both](https://github.com/karanjthakkar/ModernBabelConfigIssue/compare/working...master) is the babel config.

The culprit here seems to be the absence of `@babel/plugin-transform-regenerator` which compiles async/await code.

## Expected Behavior

Multiple async/await calls should work the same without compilation via babel.

## Code Example

Repo with code: https://github.com/karanjthakkar/ModernBabelConfigIssue
Repro steps mentioned above.

## Environment

```
  React Native Environment Info:
    System:
      OS: macOS 10.14.1
      CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 26.45 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      npm: 6.9.0 - ~/.nvm/versions/node/v10.15.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.0, 25.0.2, 26.0.2, 26.0.3, 27.0.3, 28.0.3
        System Images: android-26 | Google APIs Intel x86 Atom_64, android-26 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.2 => 0.59.2
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

**Comment by newyankeecodeshop** [comment]
Have you tried removing the `Promise` polyfill? That may be causing issues too, since it might conflict with the `Promise` type built into the JSC and (potentially) used by async/await.

**Comment by dulmandakh** [comment]
It's not recommended to change babel config unless you know what you're doing. we're working on to reduce babel plugins and polyfills used. Thank you

**Comment by karanjthakkar** [comment]
@newyankeecodeshop Hey! I tried removing the polyfill from here: https://github.com/facebook/react-native/blob/4148976a83ab96029de1b26b515ff95d3cb58c10/Libraries/Core/InitializeCore.js#L35 But I still face the same issue with a fresh metro cache.

@dulmandakh Do you have any links to conversations around this? I'd love to keep an eye out. 

Using `rn-snoopy` I can see that the message describing the new UI is sent to the native side:

```
04-02 10:20:00.790  5264  5297 D ReactNative: ReactInstanceManager.attachRootViewToInstance()
04-02 10:20:01.184  5264  5296 I ReactNativeJS: Running application "ModernBabelConfigIssue" with appParams: {"rootTag":1}. __DEV__ === false, development-level warning are OFF, performance optimizations are ON
04-02 10:20:01.196  5264  5296 I ReactNativeJS: JS->N : 6.2([3,"RCTRawText",1,{"text":"Loading...."}]) *
04-02 10:20:01.198  5264  5296 I ReactNativeJS: JS->N : 6.2([5,"RCTText",1,{"fontSize":20,"textAlign":"center","margin":10,"accessible":true,"allowFontScaling":true,"ellipsizeMode":"tail"}]) *
04-02 10:20:01.199  5264  5296 I ReactNativeJS: JS->N : 6.18([5,[3]]) *
04-02 10:20:01.206  5264  5296 I ReactNativeJS: JS->N : 6.2([7,"RCTView",1,{"flex":1,"justifyContent":"center","alignItems":"center","backgroundColor":-656129}]) *
04-02 10:20:01.206  5264  5296 I ReactNativeJS: JS->N : 6.18([7,[5]]) *
04-02 10:20:01.206  5264  5296 I ReactNativeJS: JS->N : 6.2([9,"RCTView",1,{"collapsable":true,"pointerEvents":"box-none","flex":1}]) *
04-02 10:20:01.206  5264  5296 I ReactNativeJS: JS->N : 6.18([9,[7]]) *
04-02 10:20:01.206  5264  5296 I ReactNativeJS: JS->N : 6.2([13,"RCTView",1,{"flex":1,"pointerEvents":"box-none"}]) *
04-02 10:20:01.206  5264  5296 I ReactNativeJS: JS->N : 6.18([13,[9]]) *
04-02 10:20:01.211  5264  5296 I ReactNativeJS: JS->N : 6.18([1,[13]]) *
04-02 10:20:01.213  5264  5296 I ReactNativeJS: JS->N : 30.0([1,0,1554196801213,false]) *
04-02 10:20:01.221  5264  5296 I ReactNativeJS: JS->N : 30.0([2,1,1554196801221,false]) *
04-02 10:20:01.253  5264  5296 I ReactNativeJS: JS->N : 6.22([3,"RCTRawText",{"text":"Welcome to React Native mate!"}]) *
```

Its just not getting flushed from what I can imagine. Do you have any ideas on why this could be happening?

**Comment by dulmandakh** [comment]
FYI, https://github.com/facebook/react-native/commit/06cf7face24d0f06e7b690dfc30912ec1e3e1bfb commit removing various polyfills that are no longer required.

**Comment by karanjthakkar** [comment]
@dulmandakh This is unrelated to whether the polyfills are present or not and still exists on the latest master where the mentioned change has landed. Can you please reopen this?

**Comment by dulmandakh** [comment]
It's not recommended to change babel config unless you know what you're doing, so if the issue is caused by babel config change we cannot fix it. Please use babel config RN provides.
