### ISSUE TITLE
libgnustl_shared.so not present in 0.59.3

### ISSUE THREAD

**Issue by M1K3Yio** [facebook/react-native#24247]
## 🐛 Bug Report

```React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
      Memory: 4.52 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.3 => 0.59.3 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-create-library-full: 3.1.2
      react-native-create-library: 3.1.2
      react-native: 0.59.3
```

![image](https://user-images.githubusercontent.com/3988634/55359613-dc0ac900-5497-11e9-9cab-cd4be6ffb203.png)

Image on the left is version 0.58.6 and right is the latest 0.59.3.

I've gone through the upgrade process (manually).  Application runs fine on iOS.

Is the removal of this file intentional if so what's the appropriate solution?

**Comment by dulmandakh** [comment]
libgnustl is deprecated in Android NDK, so React Native switched to libc++ in 0.59.

**Comment by M1K3Yio** [comment]
@dulmandakh Thanks for the info.  I went through the React Native 0.59 release notes multiple times and I don't see anything related to this.  Do you happen to have anymore info on what I may need to change to use the libc++?  I am struggling identifying what is depending on libgnustl_shared.so.

**Comment by dulmandakh** [comment]
Sorry that it's not mentioned in the release notes. I think that there is
nothing to do to use libc++, because React Native already uses it. I think
that you are using some native module that depends on it, so it's best to
ask a developer about it. I don't have much experience with Android NDK,
and I cannot give you good advice on it, sorry.

**Comment by M1K3Yio** [comment]
I think you are right, thank you for the information.
