### ISSUE TITLE
android <Text> not working writingDirection:"rtl"

### ISSUE THREAD

**Issue by poison8** [facebook/react-native#24246]

**Comment by poison8** [comment]
react-native 0.59.1   android:8.0
  ios <Text style={{writingDrirection:"rtl"}> normal 
android not working

**Comment by poison8** [comment]
<Text style={{color:"white", textAlign:"justify", writingDirection: "rtl"}}>
                 {txt}
             </Text>

**Comment by khalidahmada** [comment]
I have the issue on Android
