### ISSUE TITLE
WebView doesn't load local html file correctly

### ISSUE THREAD

**Issue by WebMobi59** [facebook/react-native#24251]
## 🐛 Bug Report
I am using webview to load local html file which shows the variety of tiles on google maps.
it works on native project, but two tiles doesn't load in react native project with same html file.

React Native screenshot.

![MqNYQ](https://user-images.githubusercontent.com/20356023/55369043-7a923b00-5527-11e9-9ded-198c66823f38.png)

Native screenshot.

![gDW3M](https://user-images.githubusercontent.com/20356023/55369086-a4e3f880-5527-11e9-8dc2-93e274e9cec6.png)

## Expected Behavior
Need to show all tiles correctly like as native.

## Code Example
Here is codechip for webview.
```
<WebView
          originWhitelist={['*']}
          onLoad={this.onLoad}
          source={Platform.OS === 'android' ? { uri: 'file:///android_asset/index.html' } : {uri: './index.html'}}
          dataDetectorTypes={'none'}
          ref='webview'
          onMessage={e => this.onMessage(JSON.parse(e.nativeEvent.data))}
          onShouldStartLoadWithRequest={this.onShouldStartLoadWithRequest}
          onNavigationStateChange={this.onShouldStartLoadWithRequest}
          injectedJavaScript={patchPostMessageJsCode}
          useWebKit={true}
          />
```

I am not sure why this file doesn't work on react native.
Any help are appreciated.

**Comment by WebMobi59** [comment]
It works on Android correctly, this problem come from only iOS platform

**Comment by dulmandakh** [comment]
Please use https://github.com/react-native-community/react-native-webview, because WebView in React Native is deprecated and will be removed in the future.

**Comment by WebMobi59** [comment]
@dulmandakh, so we can't resolve this issue?
It give me HTTP load failed 999 error when I run project with Xcode

**Comment by dulmandakh** [comment]
@WebMobi59 WebView in React Native will not receive any updates and will be removed soon. Please use react-native-webview, which is actively maintained fork.
