### ISSUE TITLE
[UIExplorer] THUMB_URLS is unavailable

### ISSUE THREAD

**Issue by PPSong** [facebook/react-native#2425]
THUMB_URLS = ['https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-ash3/t39.1997/p128x128/851549_767334479959628_274486868_n.png', 'https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-prn1/t39.1997/p128x128/851561_767334496626293_1958532586_n.png', 'https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-ash3/t39.1997/p128x128/851579_767334503292959_179092627_n.png', 'https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-prn1/t39.1997/p128x128/851589_767334513292958_1747022277_n.png', 'https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-prn1/t39.1997/p128x128/851563_767334559959620_1193692107_n.png', 'https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-prn1/t39.1997/p128x128/851593_767334566626286_1953955109_n.png', 'https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-prn1/t39.1997/p128x128/851591_767334523292957_797560749_n.png', 'https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-prn1/t39.1997/p128x128/851567_767334529959623_843148472_n.png', 'https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-prn1/t39.1997/p128x128/851548_767334489959627_794462220_n.png', 'https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-prn1/t39.1997/p128x128/851575_767334539959622_441598241_n.png', 'https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-ash3/t39.1997/p128x128/851573_767334549959621_534583464_n.png', 'https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-prn1/t39.1997/p128x128/851583_767334573292952_1519550680_n.png'];
<img width="528" alt="screen shot 2015-08-24 at 9 54 33 pm" src="https://cloud.githubusercontent.com/assets/12009179/9441836/ebaab85c-4aaa-11e5-979a-c56b64f4b072.png">

**Comment by simar7** [comment]
@brentvatne In order to fix them, are we pointing them to another URL or is there another way to fix this? I'm willing to look into this and contribute a PR!

**Comment by grabbou** [comment]
@brentvatne we need to figure out where to serve these assets from. Shall we just add them in to `gh-pages` to ensure they are always available? (without cross-linking to either fb or s3 servers)

**Comment by mrcasals** [comment]
Solved by https://github.com/facebook/react-native/commit/6e01c514d2ca7e1ab10e94c04822c183825ba5e3, this can be closed :)
