### ISSUE TITLE
TypeError: Requested keys of a value that is not an object

### ISSUE THREAD

**Issue by puvi034** [facebook/react-native#24269]
Getting 'TypeError: Requested keys of a value that is not an object.'  only on Android. This issue won't happen when I activate 'Debug JS Remotely'

React Native Version: 0.55.4
Device: Any android device.

**Comment by Rramandeep** [comment]
puvi034 have you find solution for this issue?

**Comment by puvi034** [comment]
@Rramandeep In my case, it was breaking at one of my dependencies, which got released 12 days ago.

I have filed issue against the library redux-form
https://github.com/erikras/redux-form/issues/4423
As temporary fix, I just downgraded the version

**Comment by Rramandeep** [comment]
@puvi034 in my case when I'am navigate to other screen then this error arises, i don't know which thing is causing this error. will you help me to solve this error.
