### ISSUE TITLE
Long press not registered if second press is too far from first

### ISSUE THREAD

**Issue by Kida007** [facebook/react-native#24268]
## 🐛 Bug Report

As the title says, Long press not registered if second press is too far from first in a React Native 0.59.1 app. This issues is an extension of #24001 

It only affects certain devices ( OnePlus 5t , Samsung Galaxy A5 , Samsung Galaxy S9+ )

![FILE 2019-04-03 00_18_13](https://user-images.githubusercontent.com/22558035/55428258-59246400-55a6-11e9-98e1-008b42b94b1c.gif)

## To Reproduce

1) Test on a broken device as mentioned above.
2) Multiple and Random Long press Interaction on a TouchableNativeFeedback Component .( make sure successive Interaction is far from the previous. )
## Expected Behavior

Long pressing the TouchableNativeFeedback triggers the onLongPress handler Consistently.

## Code Example

![bug-rn](https://user-images.githubusercontent.com/22558035/55429216-9689f100-55a8-11e9-8b5a-9aa466d9bdb4.png)

## Environment

```
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
      Memory: 223.68 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.0.0 - /usr/local/bin/node
      Yarn: 1.15.2 - ~/.yarn/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28
        Build Tools: 22.0.1, 23.0.1, 23.0.2, 24.0.0, 24.0.2, 24.0.3, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.3, 27.0.2, 27.0.3, 28.0.1, 28.0.3
        System Images: android-23 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.1 => 0.59.1 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

```

**Comment by rickhanlonii** [comment]
Great find, should be closed by #24238
