### ISSUE TITLE
letterSpacing in TextInput not works on iOS

### ISSUE THREAD

**Issue by Bardiamist** [facebook/react-native#24263]
## 🐛 Bug Report
`letterSpacing` in TextInput not works on iOS. It works on Android.

## To Reproduce
Set a `letterSpacing` property style to TextInput and see result on iOS.

## Expected Behavior
`letterSpacing` should be applied on iOS same as on Android.

## Code Example
https://snack.expo.io/@bardiamist/letterspacing-ios

## Environment
React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (2) x64 Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
      Memory: 2.90 GB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.13.0 - /var/folders/pd/f5zx6fp16xsdz40l4l8z13z00000gn/T/yarn--1554214860533-0.8348633037813469/node
      Yarn: 1.15.2 - /var/folders/pd/f5zx6fp16xsdz40l4l8z13z00000gn/T/yarn--1554214860533-0.8348633037813469/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.3 => 0.59.3 
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by Kida007** [comment]
Fixed by https://github.com/facebook/react-native/pull/23760.

**Comment by Kida007** [comment]
Fixed by https://github.com/facebook/react-native/pull/23738

**Comment by vijaykosuri** [comment]
But for secureTextEntry={true} spacing doesnot work when we input a value.
