### ISSUE TITLE
App Icon Not Showing on Android Pie Devices

### ISSUE THREAD

**Issue by sagargulati** [facebook/react-native#24265]
## 🐛 Bug Report
After I have updated react native to 0.59.0 from 0.57.1 (Not using expo) The app somehow stopped showing App Icon in the Android Pie (Android SDK 28) 
**Package.json Dependencies:**
```
  "dependencies": {
    "@babel/core": "^7.3.4",
    "@react-native-community/async-storage": "^1.2.1",
    "@react-native-community/netinfo": "^1.3.0",
    "axios": "^0.18.0",
    "prop-types": "^15.7.2",
    "pusher-js": "^4.4.0",
    "react": "16.8.3",
    "react-native": "0.59.0",
    "react-native-android-open-settings": "^1.3.0",
    "react-native-animatable": "^1.3.2",
    "react-native-app-intro-slider": "^1.0.1",
    "react-native-device-info": "^0.26.4",
    "react-native-fbads": "^6.0.2",
    "react-native-fbsdk": "^0.8.0",
    "react-native-firebase": "^5.2.3",
    "react-native-gesture-handler": "^1.1.0",
    "react-native-indicators": "^0.13.0",
    "react-native-linear-gradient": "^2.5.3",
    "react-native-magic-move": "^0.6.1",
    "react-native-paper": "^2.12.0",
    "react-native-reanimated": "^1.0.0-alpha.12",
    "react-native-shimmer-placeholder": "^1.0.30",
    "react-native-status-bar-height": "^2.2.0",
    "react-native-vector-icons": "^6.3.0",
    "react-navigation": "^3.5.1"
  },
  "devDependencies": {
    "babel-core": "7.0.0-bridge.0",
    "babel-jest": "24.3.1",
    "jest": "24.3.1",
    "metro-react-native-babel-preset": "0.53.0",
    "react-devtools": "^3.6.1",
    "react-native-rename": "^2.4.1",
    "react-native-screens": "^1.0.0-alpha.22",
    "react-test-renderer": "16.6.3"
  },

```

## To Reproduce
- After app install, Icon is not being shown on Android Pie but shows on lower version of Android devices.
- However, a fresh install of react native shows Android Icon. I'm not sure which package or thing is causing this simple error. Already reinstalled app many times, all the res folder are there, regenerated bundle as well.

## Expected Behavior
- App icon should be shown on Android devices.  It does show on devices lower than Android P but not on Android P.

## Code Example
- Basic Sample Code. P.S (Updated the app icon inside res/minmap)

## Environment
```
C:\Users\Sagar\Apps\gattle>react-native info
info
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
      Memory: 3.97 GB / 11.88 GB
    Binaries:
      Yarn: 1.15.2 - C:\src\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5314842
```

**Comment by dulmandakh** [comment]
i couldn't reproduce it on a new project using 0.59.3, or app has app icon. Maybe you should be using adaptive icons https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive. Please feel free to comment if the issue persists after you adopt adaptive icons.
