### ISSUE TITLE
Requiring unknow module "rebound"

### ISSUE THREAD

**Issue by dotMastaz** [facebook/react-native#2427]
Hello,

In the tutorial, there are some examples with rebound.
But when i run, i had the Red Screen with : 
Requiring unkno module "rebound"....

Any ideas ?
Thank you !!

**Comment by llanox** [comment]
I think you could try use  
```javascript
var {
rebound
} = React;  
```
 instead of   
```javascript
 var rebound = require('rebound');
```
I was having that issue with Dimensions as well.

**Comment by dotMastaz** [comment]
Hi, thank you...

I have this now : 
undefined is not an object (evaluating 'new rebound.SpringSystem') ....?

Is rebound is included with react-native because i can't find rebound.js in any directory ?

**Comment by browniefed** [comment]
Rebound has been removed, it was used in the Animated API but was removed.

**Comment by dotMastaz** [comment]
Ok thank you.

But in the eventuality i need to use this library, where can i find a tutorial to include an library like rebound ?

Thank you Browniefed !

**Comment by llanox** [comment]
Well, @dotMastaz  you can add rebound as a dependency (npm i rebound --save ). However, you should replace it with Animated library as @browniefed  said.

**Comment by dotMastaz** [comment]
Thank you !!
