### ISSUE TITLE
How to disable react native dev mode in debug build configuration for iOS?

### ISSUE THREAD

**Issue by ccorcos** [facebook/react-native#24272]
I'm trying to debug the application bootup and i want to skip the websocket server that downloads the react native bundler.

Everything I've read on the internet just says to use release build configuration, but I need the debug configuration in order to debug my app.

I found this little bit that prevents the bundle from re-building but it still connects to the websocket server to download the bundle instead of building it in.

https://facebook.github.io/react-native/docs/running-on-device.html#pro-tips

I also tried setting `#define RCT_DEV 0` in RTCDefines.h but that caused other build errors importing RCTReconnectingWebsocket...

Any ideas how to do this?

**Comment by ntnamag** [comment]
<img width="717" alt="Screen Shot 2019-05-10 at 14 10 36" src="https://user-images.githubusercontent.com/10351096/57509194-cce82800-732d-11e9-970a-badc6ee74bf9.png">
