### ISSUE TITLE
Modal/Modal.js : requireNativeComponent is not defined

### ISSUE THREAD

**Issue by martiano9** [facebook/react-native#24277]
## 🐛 Bug Report
**Requiring module "node_modules/react-native/Libraries/Modal/Modal.js", which threw an exception: ReferenceError: requireNativeComponent is not defined**

**Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.**

## To Reproduce
Create and empty project with react-native init
Import Modal from react-native

## Expected Behavior
App can run normally

## Code Example
import { Modal } from 'react-native'

render() {
   return <Modal visible={false} />
}

## Environment
React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 1.95 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.12.0 - /usr/local/bin/node
      Yarn: 1.13.0 - ~/.yarn/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.0, 25.0.2, 26.0.1, 26.0.2, 27.0.3, 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.4 => 16.8.6 
      react-native: ^0.59.3 => 0.59.3 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      react-native: 0.57.3

**Comment by dulmandakh** [comment]
please provide workable demo code

**Comment by GenericJam** [comment]
This seems to be a bug in yarn or react-native's build system or something. I tried clearing the yarn cache and it still persists so I suspect it is something on rn's side.

The online source is correct and if I copy/paste it into node_modules/react-native/Libraries/Modal/Modal.js it works fine but if I use yarn at any version > 0.59, it gives the wrong code which doesn't include the right import so it fails. (line 23)

`const RCTModalHostView = Platform.OS === 'ios' ? requireNativeComponent('RCTModalHostView') : requireNativeComponent('TranslucentModalHostView');`

should be:

`const RCTModalHostView = require('RCTModalHostViewNativeComponent');`

or even works.

`const requireNativeComponent = require('requireNativeComponent');
const RCTModalHostView = Platform.OS === 'ios' ? requireNativeComponent('RCTModalHostView') : requireNativeComponent('TranslucentModalHostView');`


I gave more detail here: https://github.com/facebook/react-native/issues/24161#issuecomment-487142031

I think this is the same issue.
https://github.com/react-native-community/react-native-modal/issues/276

Please fix this. It's currently preventing us from being able to upgrade our version of RN.

**Comment by Iskander508** [comment]
> RCTModalHostView

In my case this was caused by the react-native-modal-translucent library. You can try to upgrade/remove it.
