### ISSUE TITLE
After update  to MIUI 10.2.3, app crashes on one screen.

### ISSUE THREAD

**Issue by PayalDinc** [facebook/react-native#24278]
## Environment
React Native Environment Info:
    System:
      OS: Windows 8.1
      CPU: (4) x64 Intel( R) Core(TM) i5-4460  CPU @ 3.20GHz
      Memory: 11.43 GB / 15.90 GB
    Binaries:
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5199772

**Comment by dulmandakh** [comment]
Could you please provide environment information and reproducible demo code. I'm closing this issue until then. Thank you
