### ISSUE TITLE
FlatList pagingEnabled don't work all the time on Android

### ISSUE THREAD

**Issue by PsyWolf** [facebook/react-native#24297]
## 🐛 Bug Report

So i have an horizontal flatlist where each items use the entire width of the screen.
I can swipe between the items. When i do a normal swipe, it works perfectly, the previous item slides out while the next slides in, just as expected
The issue is, when i'm dragging the item and leaving the items in a state where both items are visible, the items neither go back to previous item nor to the next and just stuck in between.
The pagingEnabled doesn't work and my screen is stuck in between 2 items.

## Expected Behavior

 when the dragging is stopped and the user has no longer touching the screen, 
depends on the viewAreaCoveragePercentThreshold that has been declared or by default 50%
for example: if viewAreaCoveragePercentThreshold = 50 then if 50% or more of the next item is visible it should animate to the next item otherwise to the previous item

## Code Example

 ```
<FlatList
	viewabilityConfig={this.viewabilityConfig}
	ref={(flatList) => (this.flatList = flatList)}
	getItemLayout={(data, index) => ({
		length : this.state.width,
		offset : this.state.width * index,
		index
	})}
	onLayout={this.onLayout}
	data={this.props.data}
	renderItem={this.renderItem}
	keyExtractor={this.keyExtractor}
	horizontal
	pagingEnabled
/>
```

## Environment
info
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
      Memory: 2.97 GB / 7.85 GB
    Binaries:
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5264788

"dependencies": {
    "react": "16.8.3",
    "react-native": "0.59.3"
  }

**Comment by AntoineDoubovetzky** [comment]
@PsyWolf I tried to reproduce the bug but can't. Can you provide all the code, like the viewabilityConfig and renderItem you are using, and how you get this.state.width ?

**Comment by PsyWolf** [comment]
```
`
renderItem = ({ item }) => {
    return (
        <Image
		style={[
		        { width: this.state.width, height: this.state.height },
			styles.imageStyle
		]}
		source={{
			uri : item.source
		}}
		resizeMethod="auto"
		key={item.id}
	/>
    );
}

onLayout = (e) => {
	this.setState({
		width  : e.nativeEvent.layout.width,
		height : e.nativeEvent.layout.height
	});
};

this.viewabilityConfig = { viewAreaCoveragePercentThreshold: 2 };
`
```

the  viewAreaCoveragePercentThreshold set to 2 because i try to achieve the page change on the smallest viewability of the next page

**Comment by AntoineDoubovetzky** [comment]
@PsyWolf I can't reproduce the bug on iOS. Does it happen on Android only? The documentation states the pagingEnabled is not supported on Android (https://facebook.github.io/react-native/docs/scrollview#pagingenabled)

**Comment by PsyWolf** [comment]
@AntoineDoubovetzky I didn't have the opportunity to test on IOS so can't say.
So yes, as far as I know, this happens only on Android.

**Comment by gongdao123** [comment]
Same thing happens to me too.

I can confirm that this only happens on Android.

And if I put tracking code like following:

`      <FlatList
        {...this.props}
        ref={this.handleInfListRef}
        data={data}
        getItemLayout={getItemLayout}
        initialScrollIndex={initialScrollIndex}
        pagingEnabled
        renderItem={renderItem}
        onScroll={this.onScroll}
        onTouchStart={() => console.log('onTouchStart')}
        onTouchMove={() => console.log('onTouchMove')}
        onTouchEnd={() => console.log('onTouchEnd')}
        onScrollBeginDrag={() => console.log('onScrollBeginDrag')}
        onScrollEndDrag={() => console.log('onScrollEndDrag')}
        onMomentumScrollBegin={() => console.log('onMomentumScrollBegin')}
        onMomentumScrollEnd={() => console.log('onMomentumScrollEnd')}
        showsHorizontalScrollIndicator={showsHorizontalScrollIndicator}
      />
`

In normal case (move finger quickly), when I stop dragging the event fires in this order:

`
onTouchEnd
onScrollEndDrag
onMomentumScrollEnd
`
But when I move finger slowly only `onTouchEnd` will be triggered.

**Comment by PsyWolf** [comment]
@gongdao123 Indeed I can confirm that only those events fire and none other.
Which is also strange, I would appreciate if someone who has dealt with this before will share a solution or an alternative to mimic the functionality of a horizontal flat list with paging enabled.

**Comment by wandrzejczak** [comment]
hej @gongdao123, @PsyWolf 

did you check on Android with debug mode?
If yes, then I'd recommend to compile the app to production mode and then test it.
Problem with Andoird in Debug mode is that events sync does not work correctly at all, this is known issue.

Just add Text area and try to add there your fired events.

Let me know if it helped.

Wojtek.

**Comment by ThakurKarthik** [comment]
@PsyWolf any update regarding this? Were you able to solve this?

**Comment by PsyWolf** [comment]
Well regarding @wandrzejczak answer I did not try to compile it to production mode will check that later.
I did manage to half fix it by using some workarounds basically I used onViewableItemsChanged, onMomentumScrollEnd and onTouchEnd to check which elements are viewable right now and scroll to one of them, it's messy code and not really the best way but that's what I came up with.
as far as I can tell it works most of the time but it's not perfect and sometimes it's not predictable 
if anyone has a better solution I'll be glad to hear it
```
constructor (props) {
		super(props);
		this.state = {
			width         : null,
			height        : null,
			currentIndex  : 0,
			viewableItems : [ 0 ]
		};

		this.onViewableItemsChanged = this.onViewableItemsChanged.bind(this);
		this.viewabilityConfig = { viewAreaCoveragePercentThreshold: 2 };
	}

        getItemLayout = (data, index) => ({
		length : this.state.width,
		offset : this.state.width * index,
		index
	});

	animateNextPage = () => {
		let currentIndex = this.state.currentIndex;
		if (currentIndex < this.props.data.length - 1) {
			currentIndex += 1;
			this.scrollToIndex(currentIndex);
		}
	};

	scrollToIndex = (index) => {
		this.flatList.scrollToIndex({
			    animated     : true,
			    index        : index,
			    viewOffset   : 0,
			    viewPosition : 0
		});
		this.setState({ currentIndex: index });
	};

	animatePreviousPage = () => {
		let currentIndex = this.state.currentIndex;
		if (currentIndex > 0) {
			currentIndex -= 1;
			this.scrollToIndex(currentIndex);
		}
	};

	onLayout = (e) => {
		this.setState({
			width  : e.nativeEvent.layout.width,
			height : e.nativeEvent.layout.height
		});
	};

	onViewableItemsChanged = ({ viewableItems }) => {
		let index = [];
		viewableItems.forEach((el) => {
			index.push(el.index);
		});
		this.setState({ viewableItems: index });
	};

	onMomentumScrollEnd = (event) => {
		let index = Math.floor(event.nativeEvent.contentOffset.x / 300);
		this.setState({ currentIndex: index });
	};

	onTouchEnd = (event) => {
		const { currentIndex, viewableItems } = this.state;
		if (viewableItems.length > 1) {
			viewableItems.forEach((el) => {
				if (el != currentIndex) {
					this.scrollToIndex(el);
				}
			});
		}
	};

        <FlatList
		onTouchEnd={(e) => this.props.onTouchEnd(e)}
		onViewableItemsChanged={this.props.onViewableItemsChanged}
		viewabilityConfig={this.state.viewabilityConfig}
		onMomentumScrollEnd={(e) =>
			this.onMomentumScrollEnd(e)}
		getItemLayout={(data, index) =>
			this.getItemLayout(data, index)}
		onLayout={this.onLayout}
		data={this.props.data}
		renderItem={({ item }) => this.renderItem({ item })}
		keyExtractor={this.keyExtractor}
		ref={(flatList) => (this.flatList = flatList)}
		initialScrollIndex={this.currentIndex}
		horizontal
		pagingEnabled
	/>
```

**Comment by ThakurKarthik** [comment]
Hey @PsyWolf Thanks for the answer.I was able to solve my issue like this.On the wrapper container for each view add `backgroundColor: 'transparent'` . I followed this issue [here](https://github.com/facebook/react-native/issues/22251#issuecomment-438524264)

**Comment by ThakurKarthik** [comment]
Here is a expo link for the above comment [Expo Link](https://snack.expo.io/@karthik.01/4471ef)

**Comment by PsyWolf** [comment]
> Here is a expo link for the above comment [Expo Link](https://snack.expo.io/@karthik.01/4471ef)

@ThakurKarthik i tried your app and the paggination did work but on swipe gesture it jumps over unexpected number on elements instead of only one
