### ISSUE TITLE
library not found for -ljschelpers

### ISSUE THREAD

**Issue by vvusts** [facebook/react-native#24298]
## 🐛 Bug Report
I upgraded from rn 56 to rn 58.6.
I removed react and reac-native folders from node modules change package.json versions and npm install.
I can't build xcode project I am getting error from title and this is the end of build log:
```
/Users/myname/Library/Developer/Xcode/DerivedData/MyApp-bahhewkdpujtqjghatczibeqkigt/Build/Products/Release-iphoneos/libRCTText.a /Users/myname/Library/Developer/Xcode/DerivedData/MyApp-bahhewkdpujtqjghatczibeqkigt/Build/Products/Release-iphoneos/libRCTVibration.a /Users/myname/Library/Developer/Xcode/DerivedData/MyApp-bahhewkdpujtqjghatczibeqkigt/Build/Products/Release-iphoneos/libRCTWebSocket.a -lReact -lyoga -lcxxreact -ljschelpers -lReactNativeConfig -lRNFS -lRNImagePicker -lRNFetchBlob /Users/myname/Library/Developer/Xcode/DerivedData/MyApp-bahhewkdpujtqjghatczibeqkigt/Build/Products/Release-iphoneos/libAirMaps.a -lRNBackgroundTimer -lBVLinearGradient -lSMXCrashlytics -lPods-MyApp -lRNDeviceInfo -lRCTLocale -lRNGestureHandler -lReact\ Native\ Open\ Settings -lRNHeicConverter -lRNFirebase -Xlinker -dependency_info -Xlinker /Users/myname/Library/Developer/Xcode/DerivedData/MyApp-bahhewkdpujtqjghatczibeqkigt/Build/Intermediates.noindex/MyApp.build/Release-iphoneos/MyApp.build/Objects-normal/armv7/MyApp_dependency_info.dat -o /Users/myname/Library/Developer/Xcode/DerivedData/MyApp-bahhewkdpujtqjghatczibeqkigt/Build/Intermediates.noindex/MyApp.build/Release-iphoneos/MyApp.build/Objects-normal/armv7/MyApp

ld: library not found for -ljschelpers
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

## Expected Behavior
I can build project in xcode.

## Environment
 React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (4) x64 Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
      Memory: 57.41 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 9.5.0 - /usr/local/bin/node
      npm: 4.4.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27
        Build Tools: 19.1.0, 20.0.0, 21.1.2, 22.0.1, 23.0.1, 23.0.2, 23.0.3, 24.0.0, 24.0.1, 24.0.2, 24.0.3, 25.0.0, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.3
        System Images: android-25 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.58.6 => 0.58.6

**Comment by JKCooper2** [comment]
Unfortunately upgrading (atm) isn't as simple as that. Please check https://facebook.github.io/react-native/docs/upgrading, and potentially https://github.com/react-native-community/rn-diff-purge for guides on how to upgrade versions

The upgrade process is being looked at, and I believe v0.59 laid a lot of the groundwork for it being more automated, but for the versions you are looking at there will be some manual things to be done

**Comment by Taylor123** [comment]
Try removing the `jschelpers` library from the `Linked Frameworks and Libraries` section of your app.

Seems like an updated javascript core framework clashes with having this lib

**Comment by dorthwein** [comment]
@Taylor123 solution seemed to have worked for me.  Easiest thing was to go to <code>Build Phases</code> in my project and use the filter to search of <code>jschelpers</code> and remove it.

Thank you!

**Comment by omarkhaled11** [comment]
Thank you @Taylor123  and @dorthwein the fix worked for me but I had to add JavaScriptCore.framework after removing jschelpers from the binaries, or else I had multiple errors in Xcode build, leaving this here incase someone else runs into the same problem
