### ISSUE TITLE
Question: Why is the FlatList getItemLayout method giving an index of -1 when I set initialScrollIndex to be greater than 0?

### ISSUE THREAD

**Issue by mitchdowney** [facebook/react-native#24299]
Sorry I'm not sure if this is a bug or just a lack of knowledge on my part. Why am I getting an index value of -1 in the FlatList getItemLayout method when I set initialScrollIndex to be anything greater than 0?

I would have expected it to be impossible to get an index of -1 in getItemLayout. Any ideas what could be happening?

**Comment by joebernard** [comment]
I'm seeing the same issue. Did you find a solution?
