### ISSUE TITLE
[DevTools] Can't inspect element on RN 0.9

### ISSUE THREAD

**Issue by eyaleizenberg** [facebook/react-native#2429]
Ever since upgrading to RN 0.9, when I try to inspect an element I get the following:

![screen shot 2015-08-25 at 09 37 39](https://cloud.githubusercontent.com/assets/1061345/9460257/f7b9263a-4b0c-11e5-847f-9aff05018d47.png)

**Comment by nktpro** [comment]
Same in 0.10.0-rc as well. A quick hack just to get going until it's fixed:

```javascript
const hook = window.__REACT_DEVTOOLS_GLOBAL_HOOK__;
if (typeof hook != 'undefined') {
  if (!hook.on) {
    hook.on = () => {}
  }
  if (!hook.off) {
    hook.off = () => {}
  }
}

Just throw it somewhere in your index.ios.js and it should be working as usual.

**Comment by eyaleizenberg** [comment]
I am not sure what changed but it works for me now on RN 0.9. However when inspect an element I don't see it's properties like before (how much padding, margin, etc...)

**Comment by despairblue** [comment]
same here with 0.10.0

**Comment by brentvatne** [comment]
iirc this is plumbing for a new version of React Devtools that is still in beta: https://github.com/facebook/react-devtools/releases/tag/v2-beta2

What version of React Devtools do you have installed? Do you have Chrome debugging enabled?

**Comment by brentvatne** [comment]
Haven't heard back so closing

**Comment by despairblue** [comment]
@brentvatne oh, haven't seen your comment actually. The issue is gone with the new react devtools.

**Comment by brentvatne** [comment]
@despairblue - oh! I figured that might be the case
