### ISSUE TITLE
Docs: Nesting of <View> within <Text> is not currently supported. 

### ISSUE THREAD

**Issue by fucukur** [facebook/react-native#24307]
The React Native website is hosted on a separate repository. You may let the
team know about any issues with the documentation by opening an issue there:
- https://github.com/facebook/react-native-website
- https://github.com/facebook/react-native-website/issues

### Please do not open a documentation issue in the core React Native repository.
###View
       ###     View
              ###  Text>{data.title}</Text
            View
        ###View
My Code. Error Docs: Nesting of <View> within <Text> is not currently supported. For android emulator.###<View> etiketindeki <Text> etiketi bir hata döndürür.

**Comment by charpeni** [comment]
Nesting of `<View>` within `<Text>` is not currently supported, the documentation has been recently updated to reflect that change on iOS (before the warning was only on Android).

Closing this issue, if you find any issues within the documentation, please open an issue here instead: https://github.com/facebook/react-native-website.
