### ISSUE TITLE
iOS Crash At launch    probability 0.3%

### ISSUE THREAD

**Issue by Gengpp** [facebook/react-native#24301]
## 🐛 Bug Report
iOS :   Crash ! at launch !
stack : 
`
0 libsystem_kernel.dylib | __pthread_kill + 8
-- | --
1 libsystem_pthread.dylib | _pthread_kill$VARIANT$mp + 380
2 libsystem_c.dylib | abort + 140
3 libc++abi.dylib | __cxa_bad_cast + 0
4 libc++abi.dylib | default_terminate_handler() + 280
5 libobjc.A.dylib | _objc_terminate() + 140
6 libc++abi.dylib | std::__terminate(void (*)()) + 16
7 libc++abi.dylib | __cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*)
8 libc++.1.dylib | std::__1::__throw_system_error(int, char const*) + 88
9 libc++.1.dylib | std::__1::mutex::try_lock() + 0
_10 ECLite | facebook::react::contextForGlobalContextRef(OpaqueJSContext*) (RCTCxxUtils.mm:53)
11 ECLite | (anonymous namespace)::nativeLoggingHook(OpaqueJSContext const*, OpaqueJSValue*, OpaqueJSValue*, unsigned long, OpaqueJSValue const* const*, OpaqueJSValue const**) (RCTJSCHelpers.mm:0)
12 JavaScriptCore | long long JSC::APICallbackFunction::call<JSC::JSCallbackFunction>(JSC::ExecState*) + 348_
13 JavaScriptCore | _llint_entry + 32992
14 JavaScriptCore | _llint_entry + 29908
15 JavaScriptCore | _llint_entry + 30012
16 JavaScriptCore | _llint_entry + 30012
17 JavaScriptCore | _llint_entry + 30012
18 JavaScriptCore | _llint_entry + 30012
19 JavaScriptCore | _llint_entry + 29908
20 JavaScriptCore | _llint_entry + 30012
21 JavaScriptCore | _llint_entry + 29908
22 JavaScriptCore | _llint_entry + 30012
23 JavaScriptCore | _llint_entry + 30012
24 JavaScriptCore | _llint_entry + 30012
25 JavaScriptCore | _llint_entry + 30012
26 JavaScriptCore | _llint_entry + 29908
27 JavaScriptCore | _llint_entry + 29908
28 JavaScriptCore | _llint_entry + 29908
29 JavaScriptCore | _llint_entry + 29908
30 JavaScriptCore | _llint_entry + 30012
31 JavaScriptCore | _llint_entry + 29908
32 JavaScriptCore | _vmEntryToJavaScript + 308
33 JavaScriptCore | JSC::Interpreter::executeCall(JSC::ExecState*, JSC::JSObject*, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) + 424
34 JavaScriptCore | JSC::boundThisNoArgsFunctionCall(JSC::ExecState*) + 452
35 JavaScriptCore | _llint_entry + 32692
36 JavaScriptCore | _vmEntryToJavaScript + 308
37 JavaScriptCore | JSC::Interpreter::executeCall(JSC::ExecState*, JSC::JSObject*, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) + 424
38 JavaScriptCore | JSC::boundThisNoArgsFunctionCall(JSC::ExecState*) + 452
39 JavaScriptCore | _vmEntryToNative + 316
40 JavaScriptCore | JSC::Interpreter::executeCall(JSC::ExecState*, JSC::JSObject*, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) + 516
41 JavaScriptCore | JSC::profiledCall(JSC::ExecState*, JSC::ProfilingReason, JSC::JSValue, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) + 188
42 JavaScriptCore | JSObjectCallAsFunction + 368
43 ECLite | facebook::react::Object::callAsFunction(OpaqueJSValue*, int, OpaqueJSValue const* const*) const (Value.cpp:217)
44 ECLite | facebook::react::JSCExecutor::invokeCallback(double, folly::dynamic const&) (JSCExecutor.cpp:572)
45 ECLite | std::__1::function<void (facebook::react::JSExecutor*)>::operator()(facebook::react::JSExecutor*) const (functional:1913)
46 ECLite | facebook::react::tryAndReturnError(std::__1::function<void ()> const&) (RCTCxxUtils.mm:0)
47 ECLite | facebook::react::RCTMessageThread::tryFunc(std::__1::function<void ()> const&) (RCTMessageThread.mm:0)
48 CoreFoundation | ___CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 20
49 CoreFoundation | ___CFRunLoopDoBlocks + 272
50 CoreFoundation | ___CFRunLoopRun + 2376
51 CoreFoundation | CFRunLoopRunSpecific + 436
52 ECLite | +[RCTCxxBridge runRunLoop] (RCTCxxBridge.mm:249)
53 Foundation | ___NSThread__start__ + 1040
54 libsystem_pthread.dylib | __pthread_body + 128
55 libsystem_pthread.dylib | _pthread_start + 48

`

## Environment
RN : 0.51.0

**Comment by Gengpp** [comment]
Environment:
  OS: macOS 10.14.3
  Node: 10.15.1
  Yarn: 1.3.2
  npm: 6.4.1
  Watchman: 4.9.0
  Xcode: Xcode 10.1 Build version 10B61
  Android Studio: 3.2 AI-181.5540.7.32.5056338

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: git+ssh://git@git.workec.com:ios/frameworks/react-native.git => 0.51.0

**Comment by Gengpp** [comment]
> Can you run `react-native info` and edit your issue to include these results under the **Environment** section?
> 
> If you believe this information is irrelevant to the reported issue, you may write `[skip envinfo]` alongside an explanation in your Environment: section.



Environment:
OS: macOS 10.14.3
Node: 10.15.1
Yarn: 1.3.2
npm: 6.4.1
Watchman: 4.9.0
Xcode: Xcode 10.1 Build version 10B61
Android Studio: 3.2 AI-181.5540.7.32.5056338

Packages: (wanted => installed)
react: 16.0.0 => 16.0.0
react-native: git+ssh://git@git.workec.com:ios/frameworks/react-native.git => 0.51.0

**Comment by JKCooper2** [comment]
You're using an outdated version of react-native, and not from the main repo. I doubt there's going to be much to be able to resolve this.

You'll basically need to update to v0.59 from the main library (so people can know there's no custom code that's causing the issue), confirm the behaviour is still occurring, and then a fix could be investigated. Without a way to reproduce this I'm not sure what else you are hoping for.

**Comment by Gengpp** [comment]
> You're using an outdated version of react-native, and not from the main repo. I doubt there's going to be much to be able to resolve this.
> 
> You'll basically need to update to v0.59 from the main library (so people can know there's no custom code that's causing the issue), confirm the behaviour is still occurring, and then a fix could be investigated. Without a way to reproduce this I'm not sure what else you are hoping for.


Thanks !   Update to v0.59 and observe crash .
