### ISSUE TITLE
How to detect the app is killed

### ISSUE THREAD

**Issue by denizbas92** [facebook/react-native#24311]
## 🐛 Bug Report
I need to detect that the app is killed. How can I understand it ? AppState does not work in Android.

## Expected Behavior
I am expecting to detect that the app is killed.

handleAppStateChange = (nextAppState: any) => {
        console.log(nextAppState)
    }

    componentWillUnmount = () => {
        AppState.removeEventListener('memoryWarning', this.handleAppStateChange)
    }

    componentDidMount() {
        AppState.addEventListener('memoryWarning', this.handleAppStateChange)
}

 Environment:
  OS: macOS 10.14
  Node: 10.13.0
  Yarn: 1.13.0
  npm: 6.4.1
  Watchman: 4.9.0
  Xcode: Xcode 10.1 Build version 10B61
  Android Studio: 3.2 AI-181.5540.7.32.5056338

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.48.4 => 0.48.4

**Comment by dulmandakh** [comment]
I think you can do it only in native code, because these callbacks won't be called anyway, or there is no way to make sure that they're executed.

**Comment by scarlac** [comment]
@dulmandakh You can use the following snippet to detect memory warnings. There is no guarantee it will be triggered in time, before you app is killed, though:
```
import { AppState } from 'react-native';

AppState.addEventListener('memoryWarning', () => {
  console.log('Device running out of memory!');
});
```

**Comment by dulmandakh** [comment]
There is no way of knowing if app is killed in JS.

**Comment by dulmandakh** [comment]
There is no way of knowing if app is killed in JS, because app is killed and JS engine is gone.

What do you want to do or achieve with this?

**Comment by waheed25** [comment]
@dulmandakh so how we can know that reason behind the killing of app at least it should throw a proper red screen or log somewhere.

**Comment by dulmandakh** [comment]
You can use crash reporting tools like crashlytics to collect crash or
error reports about your app.

>

**Comment by waheed25** [comment]
Actually i want to ask if the app is crashing in dev mode without throwing error then what are options we have?

**Comment by dulmandakh** [comment]
You can look into application log and see traces. For my current project I have native code, so I keep Android Studio open and use Logcat for reading logs.
