### ISSUE TITLE
Will there ever be an alternative to pressing Double R to refresh on Android when developing?

### ISSUE THREAD

**Issue by bobber205** [facebook/react-native#24324]
## 🐛 Bug Report
I know this is probably brought up alot but I feel I need to speak my mind.

It feels almost embarrassing as a developer how much I personally struggle with developing a React Native android app. I have lots of text fields in my apps and I spend so much time every day struggling with trying to trigger a refresh while in development mode and the keyboard coming up. All of my text fields have dozens and dozens of `rrrrrrrr` in it.

Why can't we support Command/Ctrl R like on the iOS simulator? Is there another way to trigger a refresh I'm not aware of? Surely having to resort to force quitting my simulator and rebuilding the app isn't the only other alternative.

**Comment by dulmandakh** [comment]
You can use cmd+M or ctrl+M to show developer menu, then reload from there.
