### ISSUE TITLE
Npm Run Ios does not work clearly

### ISSUE THREAD

**Issue by alicancelik** [facebook/react-native#24329]
## 🐛 Bug Report
Im using Expo . After i update my macOs and xCode to latest versions. I can not run my project with npm run ios.

## To Reproduce
  Open my project in terminal. Write ```npm run ios```

## Expected Behavior
Before update latest versions. When i write npm run ios in terminal , simulator open quickly now i got error; 
Simulator is installed but is identified as 'com.apple.CoreSimulator.SimulatorTrampoline'; don't know what that is.
 Simulator is not installed.  If you already have the latest version of Xcode installed, you may have to run the command `sudo xcode-select -s /Applications/Xcode.app`.

## Code Example
I do not have any code to share for this issue 

## Environment
info
React Native Environment Info:
      OS: macOS 10.14.4
      npm: 6.8.0 - /usr/local/opt/node/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 26, 28
        Build Tools: 28.0.3
        System Images: android-26 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
      react-native-create-library: 3.1.2

**Comment by dulmandakh** [comment]
It might be related to expo, please report it to them. For my plain React Native project, I don't see any issue after macOS and XCode update.
