### ISSUE TITLE
Calling blur method on TextInput does not trigger the onBlur handler

### ISSUE THREAD

**Issue by Nosherwan** [facebook/react-native#2432]
I am calling the blur method on a TextInput component on the componentDidMount event like so:
``` 
componentDidMount() {
        this.refs.txtInput.blur();
    }
 ```
However the onBlur handler that is assigned to this textinput component is not triggered as a result.
Do I have the correct expectation or this is not the case.

I have tried calling blur from other methods as well still it does not trigger the handler.

**Comment by ide** [comment]
If the text field already doesn't have focus (which it probably doesn't when first mounted) then blur does nothing.

**Comment by Nosherwan** [comment]
I have tried calling it on componentWillUnmount as well without success. The intent is for a couple of TextInputs to be validated as soon as the navigator back button is pressed. Can you suggest another way.

**Comment by brentvatne** [comment]
@Nosherwan - organize your component so that you can just call a function to run the validations - make it callable on blur but also just available for manual invocation as well.

**Comment by be-codified** [comment]
@Nosherwan did you find a solution for this?

**Comment by Nosherwan** [comment]
No I had a workaround for validation of all fields on a page where a
separate  button would trigger validation and would take the user to
previous page.
