### ISSUE TITLE
error: unknown option '--template'

### ISSUE THREAD

**Issue by ajohnston1219** [facebook/react-native#24328]
## 🐛 Bug Report
  When running react-native init App --template typescript I get "error: unknown option --template"

## To Reproduce
  react-native init App --template typescript

## Expected Behavior
  All the documentation I've seen implies this should work out of the box. Every example I've seen only mentions installing react-native-cli, which I have.

## Code Example
  react-native init App --template typescript

  OUTPUT:
Scanning folders for symlinks in C:\Users\ajohn\Desktop\node_dev\hippo\client\node_modules (75ms)
error: unknown option `--template'

## Environment
  Environment:
  OS: Windows 10
  Node: 10.12.0
  Yarn: 1.15.2
  npm: 6.9.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: ^16.8.6 => 16.8.6
  react-native: ^0.55.4 => 0.55.4

**Comment by JKCooper2** [comment]
This may be better raised in https://github.com/react-native-community/react-native-cli
I would recommend checking you have the latest version of the cli installed as well: https://blog.callstack.io/the-react-native-cli-has-a-new-home-79b63838f0e6
