### ISSUE TITLE
Android: Task bundleReleaseJsAndAssets is not cached

### ISSUE THREAD

**Issue by SimonSimya** [facebook/react-native#24330]
## 🐛 Bug Report
The Android task `bundleReleaseJsAndAssets` is executed every time when running a release build, even though it should be cached by gradle.

When I run the release build of the app the first time, `bundleReleaseJsAndAssets` is executed as expected.

But when I run the release build a second time without any changes, `bundleReleaseJsAndAssets` is again executed.

Reason is that the folders are deleted before the tasks as seen here (the comment actually describes the correct behavior but the code seems to be wrong): https://github.com/facebook/react-native/blob/master/react.gradle#L44

## To Reproduce
1. Run an app in Release build via `./gradlew assembleRelease`
2. Run the app in Release build again via `./gradlew assembleRelease` with no changes

## Expected Behavior
Expected: The task `bundleReleaseJsAndAssets` should be UP-TO-DATE and not be run again. 

Actual: The task `bundleReleaseJsAndAssets` is run again 

## Environment
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (8) x64 Intel(R) Core(TM) i7-2675QM CPU @ 2.20GHz
      Memory: 28.91 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.12.0 - /usr/local/opt/node@8/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/opt/node@8/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 25, 26, 27, 28
        Build Tools: 25.0.2, 25.0.3, 27.0.3, 28.0.2, 28.0.3
        System Images: android-25 | Google APIs ARM 64 v8a, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.1 => 16.6.1 
      react-native: 0.57.7 => 0.57.7 
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by dulmandakh** [comment]
thank you for the PR, so closing the issue.
