### ISSUE TITLE
[RFC] Declarative navigator routeStack API

### ISSUE THREAD

**Issue by tgriesser** [facebook/react-native#2436]
The `Navigator` component stores quite a bit of information internally in `this.state`, which makes sense given the complexity of scene transitions. However, the imperative APIs needed to work with the `Navigator` component (`pop, push, replaceAtIndex`, etc.) are unfamiliar when coming from other traditionally declarative React core components.

I'd like to propose adding a new (optional) declarative API:

```js
<Navigator routeStack={routes} />
```

The `routeStack` prop would be an `Array` acting as both the `initialRouteStack` during `getInitialState` as well as diff'ed against the current `state.routeStack` in `componentWillReceiveProps`. When the `routeStack` entries differ, the component would make its best guess at how to transition, mount/unmount scenes, etc. This would allow for more complex manipulation of a scene route stack outside of the component, while also simplifying the API surface area of the Navigator.

If this seems like a reasonable proposal, I'd be happy to take a shot at implementing - haven't explored enough to see if there are any blockers that would prevent this from being possible, I'd imagine there are some complexities with gestures, etc.

I searched a bit for other issues and didn't happen upon any related tickets, but let me know if I missed one!

**Comment by brentvatne** [comment]
This is an interesting idea... I think that having some way to store the stack outside of the Navigator would extremely useful -- I'd like to be able to store it within a Redux store, for example, so I can save my entire app state in Redux and reload from there.

cc @hedgerwang @ericvicenti @ide

**Comment by tgriesser** [comment]
Yep, serializing with redux is precisely what I'm doing now and it's really convenient but extremely awkward with current apis.

I'll take a shot at it and see where I get.

**Comment by ide** [comment]
I believe a declarative API is in the works (or is at least being considered, even if the next version of Navigator doesn't end up declarative). Regarding route serialization you may want to consider using URLs and react-router, which would then make it possible to deeplink into parts of your app. Currently there isn't a good story around this in RN land and we need more people exploring how to do this.

**Comment by brentvatne** [comment]
Awesome @tgriesser!

**Comment by hedgerwang** [comment]
@tgriesser 

Internally, we have built the low-level component that renders a stack of route reactively.
For now, the code look like this:

```

class Playground extends React.Component {
  constructor(props, context) {
    super(props, context);

    this.state = {
      stack: new NavigationRouteStack(0, [0]),
    };

    this.pop = this.pop.bind(this);
    this.push = this.push.bind(this);
  }

  render() {
    return (
      <View style={styles.main}>
        <NavigationUICardStack
          renderScene={renderScene}
          stack={this.state.stack}
          style={styles.stackView}
        />
        <Button onPress={this.pop} text="Pop" />
        <Button onPress={this.push} text="Push" />
      </View>
    );
  }

  push() {
    this.setState({
      stack: this.state.stack.push(this.state.stack.index + 1),
    });
  }

  pop() {
    if (this.state.stack.size > 1) {
      this.setState({
        stack: this.state.stack.pop(),
      });
    }
  }
}
```

**Comment by bleonard** [comment]
I've been using the URL as a declarative way. More or less every piece of the path (between slashes) is a component on the stack.

I found it very a nice pattern to never actually push or pop to the navigator, but rather always set the whole stack via the URL.

Then in `componentDidUpdate`, I check to see how the stack being pushed is different than the current one. If it's completely different, I just `immediatelyResetRouteStack`, but if it's one added or removed from the current one, I used `push`/`pop`.

This space is all still very early, so I've been meaning to put up a sample app about the patterns that we've been using. Let me know if you're interested in hearing more about this routing technique.

**Comment by danscan** [comment]
@bleonard I'd love to see a sample implementation.  Working on something similar to this right now in my RN app with declarative routing.

**Comment by bleonard** [comment]
Hey everyone, I just published a blog post and sample app with our URL-driven routing.
http://tech.taskrabbit.com/blog/2015/09/21/react-native-example-app/

**Comment by danscan** [comment]
@bleonard– this is a great post.  I'm doing something similar now for declarative navigation with multiple route histories, as our app's primary nav is a tab bar, and each tab has its own history.

**Comment by ide** [comment]
@ericvicenti put up an experimental declarative Navigator here: https://github.com/ericvicenti/navigation-rfc. Closing this issue here so that discussion moves to that repo.
