### ISSUE TITLE
FlatList performance with Animated values

### ISSUE THREAD

**Issue by markbrown4** [facebook/react-native#24364]
## 🐛 Bug Report

There's a performance issue when Animated values are used with FlatList, the same issue is not present with SectionList which seems odd as they're both using the same virtual list under the covers.  It's as if the animated values are not using the native driver and frame rates are limited to the `scrollEventThrottle` value.

Have tested the issue in 0.58 and 0.59 and it's still an issue.  We've had to migrate all FlatList's to a SectionList with a single section as a work-around.

## To Reproduce

Scroll the two example apps and compare the performance.

## Expected Behavior

The Flat list example should run smoothly and not be rate limited by the value of `scrollEventThrottle`

## Code Example

SectionList: https://snack.expo.io/@levibuzolic/animated-section-list-jank
FlatList: https://snack.expo.io/@markbrown4/YW5pbW

## Environment

```
React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
      Memory: 144.36 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.0 - /var/folders/m1/rmnzr0353db5kcy2vscdw5mh0000gn/T/yarn--1554774193518-0.1654295845698759/node
      Yarn: 1.12.1 - /var/folders/m1/rmnzr0353db5kcy2vscdw5mh0000gn/T/yarn--1554774193518-0.1654295845698759/yarn
      npm: 6.4.1 - ~/.nodenv/versions/10.15.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 21, 22, 23, 25, 26, 27, 28
        Build Tools: 26.0.1, 26.0.2, 28.0.2, 28.0.3, 29.0.0
        System Images: android-19 | Google APIs ARM EABI v7a, android-19 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-26 | Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom_64, android-27 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
```

**Comment by janicduplessis** [comment]
`scrollEventThrottle` is implemented natively and does also affect events with `useNativeDriver`. I suggest setting `scrollEventThrottle={1}` whenever you use native animations to avoid the throttling. It does work with SectionList because it sets `scrollEventThrottle={1}` internally since it uses NativeAnimated to implement sticky section headers.

This is "working as intended" although I agree it might not be ideal.

**Comment by markbrown4** [comment]
Ah, thanks @janicduplessis.  That helps explain the difference between the two components.  I was under the impression that `scrollEventThrottle={16}` would be enough to achieve 60fps but it doesn't seem to.
