### ISSUE TITLE
Xcode 10.2 build failed 

### ISSUE THREAD

**Issue by mhpyzzy** [facebook/react-native#24376]
## 🐛 Bug Report

/configure:-1: in `/Users/zhangzhenyang/Documents/practice/test/node_modules/react-native/third-party/glog-0.3.4':
/configure:-1: C compiler cannot create executables

## To Reproduce

 1. react-native init test --version 0.51.0
2. Double-click the test.xcodeproj
3. Click the run button on Xcode

## Actual Behavior
![image](https://user-images.githubusercontent.com/20610455/55816343-a6fc1780-5b24-11e9-99d8-d9cf39b6a550.png)

## Environment

Environment:
  OS: macOS 10.14.3
  Node: 11.13.0
  Yarn: 1.15.2
  npm: 6.7.0
  Watchman: 4.9.0
  Xcode: Xcode 10.2 Build version 10E125
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.51.0 => 0.51.0

**Comment by mhpyzzy** [comment]
i del old project, and react-native init newtest:
## Environment
  React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
      Memory: 9.07 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.13.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.4 => 0.59.4 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Actual Behavior
![image](https://user-images.githubusercontent.com/20610455/55817024-29390b80-5b26-11e9-9dc7-9904d0a649a2.png)

**Comment by colin-kudos** [comment]
What about on macOS 10.14.4? You are listed as macOS 10.14.3

**Comment by hramos** [comment]
Are you using the legacy build system? See https://github.com/facebook/react-native/issues/20774

**Comment by rkabita** [comment]
I'm having almost the same issue after upgrading the latest Xcode.. " error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening RNFirebaseStarter.xcworkspace " That's what my error said when running  "react-native run-ios " 
`{
  "name": "RNFirebaseStarter",
  "version": "5.3.0",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios --simulator=\"iPhone X\"",
    "apk": "cd android && ./gradlew assembleRelease",
    "rename": "node ./bin/rename.js",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.8.3",
    "react-native": "0.59.3",
    "react-native-firebase": "5.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.4.3",
    "@babel/runtime": "^7.4.3",
    "babel-jest": "^24.7.1",
    "jest": "^24.7.1",
    "metro-react-native-babel-preset": "^0.53.1",
    "react-test-renderer": "16.8.3"
  },
  "jest": {
    "preset": "react-native"
  }
}` 
this is my package.json file.. Please help :(

**Comment by MaheshNandam** [comment]
RN 0.57.7 and XCode 10.2

if I'm trying to run the app into 12.2 version simulators or devices, then app got crashed with
Thread 1: signal SIGABRT

ISSUE LINE -> 0x102eda2f8<+8>: b.lo 0x102eda310 ; <+32>

if I'm trying to run into 12.1 version simulators or devices, it works fine.

With this (RN 0.57.1 and XCode 10.2) configuration, if I generate IPA, it's only working in 12.1 devices and when it comes to 12.2 devices, app getting the crash on the launch screen with Thread 1: signal SIGABRT.

Any suggestions or workarounds to solve this issue?

Thanks for that savior.

**Comment by vikasdosi** [comment]
you can try my purposes and installed the fix within the node_modules/react-native package. Normally I would prefer not to modify a node_module directly, but under this circumsance, I felt that it was worth it and allowed us to add a simple script in our yarn start script and we get a clean run from a fresh clone.

npm install or yarn - install packages
cd node_modules/react-native - go to node modules directory
scripts/ios-install-third-party.sh- install @ node_modules/react-native/third-party
cd third-party - go to newly created third party directory
cd glog-0.3.x - ls -la to find your directory version number or just use tab to auto-complete)
./configure - run setup
cd ../../../../- change back to your project directory
react-native run-ios or react-native run-android - deploy

**Comment by hramos** [comment]
@MaheshNandam in your case, I'd try updating to RN 0.59 or newer. In general, when building your app using a newer Xcode or against a newer iOS SDK, you'll want to upgrade your RN version as well in order to get the latest fixes, especially when downgrading to the iOS 12.1 SDK seems to help.

**Comment by MaheshNandam** [comment]
@hramos, you are right, there is a compatibility issue's with newer 10.2 with RN and I solved it by replacing RCTBridegModule.h file with the latest version of RN.
