### ISSUE TITLE
Error: Activity class {com.deneme.visiontracker/com.deneme.visiontracker.MainActivity} does not exist.

### ISSUE THREAD

**Issue by denizbas92** [facebook/react-native#24370]
## 🐛 Bug Report
When I want to install my app to real device in android, I am getting the error as shown above.

## To Reproduce
I am using react-native run-android to launch the application. In this application I am using react-native-firebase. When I use react-native link, it may be occured.

## Expected Behavior
I am expecting that the application will be launched.

## Environment
React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: (4) x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
      Memory: 27.49 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.13.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 18, 21, 22, 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.2, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.0, 28.0.2, 28.0.3
        System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.6 => 16.8.6 
      react-native: 0.58.5 => 0.58.5 
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by denizbas92** [comment]
I tried everyhing but nothing worked.

**Comment by shreyasb07** [comment]
I'm facing this same issue. However, this issue came up only after i installed the RN-fingerprint-sensor package from NPM.

I've followed all the steps from [](https://github.com/facebook/react-native/issues/14952), but they don't seem to help.

- package (usually line 2) in /android/app/src/main/AndroidManifest.xml
- 
- applicationId (usually line 90) in defaultConfig section of /android/app/build.gradle
- 
- Line 1 of /android/app/src/main/java/com/paysack/MainApplication.java
- 
- Line 1 of /android/app/src/main/java/com/paysack/MainActivity.java

I'm using RN version 0.59.4
Would really appreciate some help on this.

**Comment by eliaslecomte** [comment]
I am having the same issue and pinpointed it to changing the package id in Android via gradle.

So if you change the package id in android/app/build.gradle:

`android {

    defaultConfig {

        applicationId 'be.createweb.test'

    }
}`

and then use react-native run-android, the intent used to open/start the app is wrong. It tries to launch the MainActivity with the package specified in the AndroidManifest file:

`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="be.createweb">`

**Comment by shrutiagrawal-cb** [comment]
@react-native-bot i am facing the same issue on react-native version 0.61 please reopen this issue

**Comment by SamilMehdiyev** [comment]
I tried package react-native-rename
[link](https://stackoverflow.com/a/58216364/2837960)

I renamed project and bundle ID 

`$ npx react-native-rename "App2" -b com.japp2
`

then again 

`$ npx react-native-rename "App" -b com.app
`

it works for me, hope help you too
