### ISSUE TITLE
TabBarIOS on v0.5.9

### ISSUE THREAD

**Issue by captain-xu** [facebook/react-native#24406]
## 🐛 Bug Report
undefined is not an object (evaluating '_reactNative.TabBarIOS.Item'')

![image](https://user-images.githubusercontent.com/20409806/55947839-d8d6c080-5c81-11e9-8d69-c9e842983c4f.png)

**Comment by captain-xu** [comment]
@axe-fb

**Comment by xtlog** [comment]
i also have this problem, need help.

**Comment by xtlog** [comment]
My project had import "ant-mobile-rn V2.2.1", when upgrad 0.59.4, the same issua happened.
remove "ant-mobile-rn 2.2.1" at your package.json,  replace with "@ant-design/react-native": "^3.1.5" , then it worked.

**Comment by PravsReddy** [comment]
#I removed antd-mobile-rn and installed @ant-design/react-native. Eventhough getting @captain-xu  the same error

**Comment by uahmed8** [comment]
Have anyone got any solution for this issue?
