### ISSUE TITLE
WebView Navigation url is not getting updated 

### ISSUE THREAD

**Issue by harryharihar** [facebook/react-native#24415]
I am using webview to navigate next webpage but whenever i clicked on link of webview , the Navigation url remains same 

i have some logic like want to show and hide my view  on webview clicked 

react native info :
React Native version: react-native-cli: 2.0.1
react-native: 0.57.8

code:

<WebView
              ref={webView => { this.refWeb = webView; }}
              style={{
                height:320,
                justifyContent: 'center',
                alignItems: 'center',

              }}
             scrollEnabled={true}
              //Loading URL
              source={
                {
                 
                  uri: initialUrl.DOMAIN_URL,
                  headers: {
                    Authorization: "Basic YmV0YTp2ZWVuYXdvcmxkMTIz",
                    client: "APP"
                  }
                }
              }
              //Enable Javascript support
              javaScriptEnabled={true}
              //For the Cache
              domStorageEnabled={true}
              //View to show while loading the webpage
              renderLoading={()=>this.DotIndicatorLoadingView()}
              //Want to show the view or not
              injectedJavaScript={injectScript} 
              automaticallyAdjustContentInsets = {true}
              startInLoadingState={true}
              onNavigationStateChange={this.onNavigationStateChange}
              
            />  

onNavigationStateChange = (navState) => {
    console.log(navState);
    if(navState.url===initialUrl.DOMAIN_URL){
      this.setState({
        canGoBack: navState.canGoBack,
        canGoForward: navState.canGoForward,
        changedUrl:false
      })
    }else{
      this.setState({
        canGoBack: navState.canGoBack,
        canGoForward: navState.canGoForward,
        changedUrl : true
  
      })
    }
    
  }

## Environment
VSCode version: 1.30.2(user)
OS platform and version: Windows 10
NodeJS version: 8.9.3
skip envinfo

**Comment by hey99xx** [comment]
There's no webview component in react-native in the latest releases, it's extracted out to https://github.com/react-native-community/react-native-webview please open your issues there.
