### ISSUE TITLE
Flatlist - Pull to refresh not working when horizontal

### ISSUE THREAD

**Issue by andreshsingh** [facebook/react-native#24412]
## 🐛 Bug Report
I am trying to implement a pull to refresh in a horizontal FlatList in react-native version 0.57.7.
```
        <FlatList
          horizontal
          refreshing={requesting}
          onRefresh={() => console.log('Refresh')}
          data={cardsList}
          renderItem={({ item }) =>
            <EachCard
              {...item}
            />
        />
```
So at first when requesting is true, it shows the loader. But when i try to pull down to refresh, it doesn't pull down and the onRefresh is also not triggered. 

I also tried to each version from v057.7 to the latest 0.59.4. It also didn't work.

## Environment
- react-native: v0.57.7 to v0.59.4
- react: v16.6.3

## react-native info
 React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 713.56 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.3.0 - ~/.nvm/versions/node/v11.3.0/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v11.3.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 25, 26, 27, 28
        Build Tools: 27.0.3, 28.0.2, 28.0.3
        System Images: android-27 | Android TV Intel x86 Atom, android-27 | Intel x86 Atom, android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.4 => 0.59.4 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

**Comment by karanpratapsingh** [comment]
Yes, I and I thought I was going crazy 😆
possible solution?? wrap it within a scroll view 👍

**Comment by andreshsingh** [comment]
> Can you run `react-native info` and edit your issue to include these results under the **Environment** section?

done!

**Comment by andreshsingh** [comment]
@karanpratapsingh it didn't work for me...Did it work for you?

**Comment by karanpratapsingh** [comment]
@andreshsingh 

Give this a try

```js

<ScrollView
                    refreshControl={
                        <RefreshControl
                            tintColor={textColors.black}
                            refreshing={isSyncing}
                            onRefresh={this._onRefresh}
                        />
                    }
                    showsVerticalScrollIndicator={false}
                    contentContainerStyle={{ flexGrow: 1, alignSelf: 'center' }}>
                 

            // your horizontal list here

</ScrollView>
```

**Comment by andreshsingh** [comment]
@karanpratapsingh  hack works :D but this bug needs to be fixed.

**Comment by karanpratapsingh** [comment]
@andreshsingh Yeah man, I agree 😭

**Comment by AntoineDoubovetzky** [comment]
@andreshsingh @karanpratapsingh The documentation actually states that the refresh control only works for vertical ScrollView. I guess it is a feature request more than a bug report :)

**Comment by andreshsingh** [comment]
@AntoineDoubovetzky 
yes, refresh control only works for vertical scrollView but it works for horizontal flatlist too. Try it in expo. It works there.

**Comment by ashotosipyan** [comment]
@andreshsingh hello,
about the hack with scrollview - did this work on iOS? I can't do anything, onRefresh function doesn't work at all.

**Comment by andreshsingh** [comment]
@ashotosipyan  yes it works, try the code above.
