### ISSUE TITLE
Discussion: The scrollview does not have a callback method to know scrolling completely

### ISSUE THREAD

**Issue by s949492225** [facebook/react-native#24413]
It wants a unique method to know scrolling over when the finger leaves or when the speed is accelerated,it means i need know the time of scrollview stop scrolling.

onScroollEnd and onMomentumScrollEnd ，They don't fit the bill。

**Comment by JKCooper2** [comment]
ScrollView does inherit from View. Is https://facebook.github.io/react-native/docs/view#onresponderrelease what you are looking for?

**Comment by s949492225** [comment]
I need a scrooll end callback,but now ,this is no has it
