### ISSUE TITLE
[Packager] npm start ERROR listen EAFNOSUPPORT :::8081

### ISSUE THREAD

**Issue by fsp1990** [facebook/react-native#2441]
I run react-native on centos64 , it will be error when npm start:

ERROR listen EAFNOSUPPORT :::8081
{"code":"EAFNOSUPPORT","errno":"EAFNOSUPPORT","syscall":"listen","address":"::","port":8081}
Error: listen EAFNOSUPPORT :::8081
at Object.exports._errnoException (util.js:837:11)
at exports._exceptionWithHostPort (util.js:860:20)
at Server._listen2 (net.js:1218:19)
at listen (net.js:1267:10)
at net.js:1370:9
at doNTCallback3 (node.js:440:9)
at process._tickCallback (node.js:346:17)
at Function.Module.runMain (module.js:473:11)
at startup (node.js:117:18)
at node.js:951:3

See http://facebook.github.io/react-native/docs/troubleshooting.html
for common problems and solutions.

npm ERR! Linux 2.6.32-431.23.3.el6.x86_64
npm ERR! argv "/root/.nvm/versions/io.js/v3.2.0/bin/iojs" "/root/.nvm/versions/io.js/v3.2.0/bin/npm" "start"
npm ERR! node v3.2.0
npm ERR! npm v2.13.3
npm ERR! code ELIFECYCLE
npm ERR! BTYAppIos3React@0.3.0 start: node_modules/react-native/packager/packager.sh
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the BTYAppIos3React@0.3.0 start script 'node_modules/react-native/packager/packager.sh'.
npm ERR! This is most likely a problem with the BTYAppIos3React package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node_modules/react-native/packager/packager.sh
npm ERR! You can get their info via:
npm ERR! npm owner ls BTYAppIos3React
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! /usr/local/src/bty_nodeJs/npm-debug.log

**Comment by ide** [comment]
Try io.js 2.x. If that doesn't work for you then I think you might need OS X.

**Comment by cheyueyong** [comment]
@ide what's the reason?  i try io.js 2.5.0 and 2.4.0, but it does't work (:

**Comment by brentvatne** [comment]
Any ideas @amasad?

**Comment by amasad** [comment]
Never seen this before. Can your machine listen on any other http port?

**Comment by cheyueyong** [comment]
@amasad  yes.  it was my apache server.

**Comment by ide** [comment]
@cheyueyong can you try io.js 2.5.0?

**Comment by cheyueyong** [comment]
@ide  io.js 2.2.0 ~2.5.0 is not ok     i run  'nvm install v2.x.0'  to install.

**Comment by ide** [comment]
Maybe your computer / environment doesn't support IPv6? That error means "address family not supported". Could try binding to 127.0.0.1 instead of ::.

**Comment by cheyueyong** [comment]
how  to  bind 127.0.0.1 ?   @ide

**Comment by ide** [comment]
You'll have to read the packager code under packager/react-packager and figure it out.

**Comment by LunaGao** [comment]
using the ipv6

**Comment by brentvatne** [comment]
Closing this issue, please create a new issue with some more details if possible @LunaGao :)

**Comment by tdzl2003** [comment]
In [this file](https://github.com/facebook/react-native/blob/51d8ed92d5c491b1be945f4d86c6e583a77abe38/local-cli/server/runServer.js)， binds uses ipv6 address '::', which is not supported by some machine.
