### ISSUE TITLE
docs: getting started says to run nonfree google android studio binary

### ISSUE THREAD

**Issue by ian-kelling** [facebook/react-native#24423]
## 🐛 Bug Report

https://facebook.github.io/react-native/docs/getting-started#1-install-android-studio

Says I need to download nonfree android studio:

<a href="https://developer.android.com/studio/index.html">Download and install Android Studio</a>

Which leads to "Android Software Development Kit License Agreement", a nonfree
license.

I assume the expo tool downloads android studio from google too.

Android studio apparently can be downloaded as free software in source code form? Please provide alternate documentation.

**Comment by dulmandakh** [comment]
Android SDK is required and we cannot do anything about it, especially license.

**Comment by ian-kelling** [comment]
@dulmandakh, "we cannot do anything about it, especially license", did you read what I wrote? I suggested something you CAN DO. Here is a more explicit way to put it. Android SDK is free software if you download the source code, but not the binary from google. So, you can provide instructions or a link for how to build from source, or you can build it yourselves and provide the binary as free software. In fact, since filing the bug, I've found there are other people working on this https://android-rebuilds.beuc.net/

**Comment by ian-kelling** [comment]
And to be explicit, since what I wrote got ignored: please reopen this.

**Comment by dulmandakh** [comment]
Could you please create a PR to the documentation to add alternatives to
Google, but RN developers use and test with Android SDK by Google and we
can't fix issues if alternatives used. Sorry and please understand that we
have limited time and resources, and we cannot support every possible
options.
