### ISSUE TITLE
URL incorrectly adds trailing slash

### ISSUE THREAD

**Issue by leethree** [facebook/react-native#24428]
## 🐛 Bug Report

`URL` polyfill in `React Native` 0.59 is broken because it's not compliant to WHATWG URL Standard. And it's broken even for the simplest use cases.

## To Reproduce

```js
const url = new URL('https://facebook.github.io/react-native/img/header_logo.png');
console.log(url);
```

## Expected Behavior

```
https://facebook.github.io/react-native/img/header_logo.png
```

## Actual Behavior

```
https://facebook.github.io/react-native/img/header_logo.png/
```

Note the trailing slash causes the URL points to a 404 page.

## Environment
```
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
      Memory: 823.64 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0
      Yarn: 1.15.2
      npm: 6.5.0
      Watchman: 4.9.0
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 28
        Build Tools: 28.0.3
        System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.4 => 0.59.4 
```

## Possible Cause

https://github.com/facebook/react-native/blob/65033d7078654bae2a87e4791dbb725110ae6bad/Libraries/Blob/URL.js#L146-L149

This code was introduced in https://github.com/facebook/react-native/pull/22901 .

**Comment by leethree** [comment]
PR #22901 also caused issue #23922

**Comment by matthargett** [comment]
Hi @leethree ! Thanks for taking the time to report an issue and give a reproduction case.

I'll submit a PR that fixes this issue along with a test in the next day or two.

With regard to #23922 , the URLSearchParams wasn't even more barebones and the polyfill wouldn't interact with React Native's custom URL that supports blobs in a performant way. Before #22901, using something like apollo-server would crap out much earlier with a different error.

**Comment by leethree** [comment]
hey bot, the issue is not resolved. leave us alone

**Comment by redreceipt** [comment]
I'll second this issue, having to add a goofy workaround

![Screen Shot 2019-10-28 at 12 15 59 PM](https://user-images.githubusercontent.com/2659478/67696162-c0f42f00-f97c-11e9-807e-a30baf527189.png)

**Comment by charpeni** [comment]
👋 You should check this out: https://github.com/charpeni/react-native-url-polyfill.

**Comment by redreceipt** [comment]
Still here

**Comment by leethree** [comment]
Hi bot, I don't think it's fixed.

**Comment by charpeni** [comment]
This issue will probably never be fixed, and if it does, it will be with a goofy workaround which is probably adding more issues behind it. See: https://github.com/facebook/react-native/pull/25719#issuecomment-521286173.

In a near future, I plan to deprecated RN's URL in favor of https://github.com/charpeni/react-native-url-polyfill, so I would suggest doing the jump right away.
