### ISSUE TITLE
React Native does not bundle files with --projectRoot

### ISSUE THREAD

**Issue by alexmbp** [facebook/react-native#24432]
## 🐛 Bug Report
I want to move my `index.tsx` file to the `src` dir, instead of root directory. I tried to set project root as cli param:
`"start": "node node_modules/react-native/local-cli/cli.js start --projectRoot src"`

And when bundle runs I see:

> error: bundling failed: Error: Unable to resolve module `@babel/runtime/helpers/interopRequireDefault` from `/Users/alexm/Documents/Projects/Stuzo/Investigations/PayomaticMobile/src/index.tsx`: Module `@babel/runtime/helpers/interopRequireDefault` does not exist in the Haste module map

## To Reproduce
1. react-native init
2. move source code files to the `./src` folder
3. add config to the metro.config.js
>   resolver: {
    sourceExts: ['js', 'ts', 'tsx'],
  },

## Expected Behavior
Code should bundle correctly

## Environment
[skip envinfo]
I think this info is enough
    npmPackages:
      react: 16.8.6 => 16.8.6 
      react-native: 0.59.4 => 0.59.4 
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by radex** [comment]
This is a regression after a packager fix in 0.59.3.

You can work around it by using watchFolders option in metro.config.js instead

**Comment by Niryo** [comment]
why is this closed? 
a workaround is not a solution, it is still an issue.
