### ISSUE TITLE
JSTimers.callTimers error with 0.59.4 on Android

### ISSUE THREAD

**Issue by ndejesus1227** [facebook/react-native#24433]
## 🐛 Bug Report
I upgraded to the most recent react native version (0.59.4) and react-native-accordion seems to no longer work on Android when expanding the accordion.

## To Reproduce
You can prob reproduce by using the react-native-accordion library on Android

## Expected Behavior
Just need the accordion to show inner content

Here's a gif of the error:

https://i.imgur.com/6EQhX0F.gif

## Environment
```
  React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
      Memory: 695.91 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.5.0 - ~/.nvm/versions/node/v10.5.0/bin/node
      Yarn: 1.10.1 - ~/.nvm/versions/node/v10.5.0/bin/yarn
      npm: 6.8.0 - ~/.nvm/versions/node/v10.5.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.2, 23.0.3, 25.0.2, 26.0.2, 26.0.3, 27.0.3, 28.0.3
        System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.6 => 16.8.6 
      react-native: 0.59.4 => 0.59.4 
    npmGlobalPackages:
      react-native-git-upgrade: 0.2.7
      react-native-rename: 2.2.2
```

**Comment by Salakar** [comment]
Hey @ndejesus1227 (or shall I say t7-🐔?  :) ), we meet again 👋 

Thanks for taking the time to fill out this issue, I believe this issue may be down to the React Native Accordion package itself as it's quite out of date.

I'd like to suggest making an issue over on the GitHub repo for that package; however that package has not been updated in over 3 years so it might be best to look for an alternative and swap it out if possible; e.g. [react-native-collapsible](https://github.com/oblador/react-native-collapsible)

Best of luck!

**Comment by ndejesus1227** [comment]
@Salakar Hello, again!

react-native-collapsible is actually pretty great :)

**Comment by josecarlosrz** [comment]
This issue happens sometimes when we use Easing.[function] instead of Easing.[property]

It happent with something like this:

```
Animated.timing(this.pressed, {
      toValue: 1,
      duration: 150,
      easing: Easing.back,
    });
```

Notice that Easing.back is a function but it's being used as a property.

It won't happen if we use Easing.back(10), Easing.quad or Easing.cubic, for example.
