### ISSUE TITLE
undefined is not an object.... = AdSupport.getAdvertisingId

### ISSUE THREAD

**Issue by olitomas** [facebook/react-native#2444]
I am using this npm package:
https://github.com/lwansbrough/react-native-google-analytics

And when  

```javascript
GATracking.getClientId(....
```
 gets called it triggers this:

```javascript
AdSupportIOS.getAdvertisingId(...
```
But it returns "undefined is not an object (evaluating 'AdSupport.getAdvertsingId')

Here is the stack trace:
<img width="307" alt="screen shot 2015-08-26 at 13 23 07" src="https://cloud.githubusercontent.com/assets/6918659/9494486/a22534b8-4bf5-11e5-8b4a-afcda722b2cd.png">

This problem is in the React code right ?

**Comment by scottgrubhub** [comment]
I'm getting the same error after upgrading from 0.9.0 to 0.10.0.

**Comment by olitomas** [comment]
Hi @scottgrubhub. It was enough to install RCTAdSupport.m in Xcode to get things working again.

**Comment by scottgrubhub** [comment]
Great, thanks

**Comment by disaacs** [comment]
I am having this problem, and I already have the RCTAddSupport.xcodeproj files installed under Libraries.

**Comment by scottgrubhub** [comment]
Disaacs, in Xcode did you go to Libraries->React.xcodeproj->React->Base then go to File->Add Files and add a reference to RCTAdSupport.h and RCTAdSupport.m? That's what did the trick for me

**Comment by disaacs** [comment]
Not quite. I went to Right clicked on Libraries and choose Add Files, and then added RCTAdSupport.xcodeproj (which contains the .h and .m files).

**Comment by disaacs** [comment]
OK, I did it your way, and it works now! Thanks! :+1:

**Comment by willatthewindow** [comment]
Is there a reason RCTAdSupport isn't included in the main React.xcodeproj?

**Comment by ide** [comment]
@willatthewindow 
- Apple will reject apps that don't use it 
- It's modest extra baggage for the majority of apps, which don't use the ad ID
- In general separate modules make the React Native ecosystem healthier
