### ISSUE TITLE
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports. Check the render method of `App`.

### ISSUE THREAD

**Issue by akisplays** [facebook/react-native#24444]
## 🐛 Bug Report

Where's the problem?

**Error**
> variant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports. Check the render method of `App`.

****
<img width="1680" alt="Ekran Resmi 2019-04-10 15 27 12" src="https://user-images.githubusercontent.com/47142807/55878501-3e08b400-5ba5-11e9-8ac7-b57fbfab31c8.png">

****
Project Files
[https://github.com/spencercarli/getting-started-react-navigation](url)
****
## Code Example
**router.js - Update React-Navigation v3**

```
import React from 'react';
import { createBottomTabNavigator, createStackNavigator } from 'react-navigation';
import { Icon } from 'react-native-elements';

import Feed from '../screens/Feed';
import Settings from '../screens/Settings';
import UserDetail from '../screens/UserDetail';
import Me from '../screens/Me';

const FeedStack = createStackNavigator({
Feed: {
screen: Feed,
navigationOptions: {
title: 'Feed',
},
},
Details: {
screen: UserDetail,
navigationOptions: ({ navigation }) => ({
title: ${navigation.state.params.name.first.toUpperCase()} ${navigation.state.params.name.last.toUpperCase()},
}),
},
});

export const Tabs = createBottomTabNavigator({
Feed: {
screen: FeedStack,
navigationOptions: {
tabBarLabel: 'Feed',
tabBarIcon: ({ tintColor }) => ,
},
},
Me: {
screen: Me,
navigationOptions: {
tabBarLabel: 'Me',
tabBarIcon: ({ tintColor }) => 
},
},
});

const SettingsStack = createStackNavigator({
Settings: {
screen: Settings,
navigationOptions: {
title: 'Settings',
},
},
});

const Root = createStackNavigator({
Tabs: {
screen: Tabs,
},
Settings: {
screen: SettingsStack,
},
}, {
mode: 'modal',
headerMode: 'none',
});
```
****
**index.js**
```
import React, { Component } from 'react';
import { Root, Tabs } from './config/router';

export class App extends Component {
  render() {
    return <Root />;
  }
}

export default App;

```

## Environment
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 1.47 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 26, 28
        Build Tools: 26.0.3, 28.0.3
        System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.3 => 0.59.3 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1

**Comment by AntoineDoubovetzky** [comment]
@akisplays The error says that you are trying to call  a component in the render method of `App`, but it is actually undefined. And that you likely forgot to export your component.
Here the only component called in the render method of `App` is `Root`. And it is indeed not exported from your router.js file.

**Comment by akisplays** [comment]
@AntoineDoubovetzky Can you write a sample code?

**Comment by AntoineDoubovetzky** [comment]
@akisplays You need to add `export` before `const Root = createStackNavigator({` if you want to import it in another file. You might want to check the documentation about javascript import/export.

**Comment by satya164** [comment]
Closing because this seems to be an issue in the your code and not in React Native.
