### ISSUE TITLE
Flatlist on scroll the app cloese suddenly

### ISSUE THREAD

**Issue by Sadhr** [facebook/react-native#24446]
## 🐛 Bug Report

  I'm fetching data from an external API and for the Home, I used Flatlist and everything work well, but for my detail screen I used a horizontal Flatlist inside a ScrollView but when I tried to scroll in the Flatlist the app closed without any error or log.

## Code Example
this is my list component:
`const renderItem = ({ item }) => {
    console.log(item);
    return <ProfileCard {...item} />;
  };
  return (
    <FlatList
      renderItem={renderItem}
      data={props.cast}
      keyExtractor={keyExtractor}
      horizontal
      showsHorizontalScrollIndicator={false}
      removeClippedSubviews
    />
  );`

and the details screen look like that:
`<ScrollView showsVerticalScrollIndicator={false}>
   <Text>Cast</Text>
   <ProfileList cast={this._castLimit(cast)} />
   </ScrollView>`

## Environment
 React Native Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
      CPU: (4) x64 Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
      Memory: 759.29 MB / 7.68 GB
      Shell: 4.4.19
    Binaries:
      Node: 10.15.3 
      Yarn: 1.12.3
      npm: 6.9.0 
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

**Comment by saxenanickk** [comment]
@Sadhr Try to see some logs in Logcat.

**Comment by Sadhr** [comment]
@saxenanickk Nothing showing in Logcat

**Comment by ptrocki** [comment]
Can you provide example repo ?

**Comment by Krizzu** [comment]
@Sadhr What filters do you use for `Logcat`? 

Your code is incomplete, but in your Detail screen snippet you're firing `this._castLimit` immediately when passing it to `cast` prop - maybe that's the issue?
