### ISSUE TITLE
Unable to run AwesomeProject sample app successfully with error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65.

### ISSUE THREAD

**Issue by jerrychong25** [facebook/react-native#24450]
## To Reproduce
1) Open [Getting Started for macOS iOS](https://facebook.github.io/react-native/docs/getting-started).
2) Follow all dependencies installation steps
3) Create a new application via command: 
`react-native init AwesomeProject`
4) Run **AwesomeProject** via command:
```
cd AwesomeProject
react-native run-ios
```
5) Error occured when running project:
```
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your a
pp with Xcode.app, by opening AwesomeProject.xcodeproj
```
6) Run sample app failed.

## Expected Behavior
Run sample app successfully.

## Code Example
Run new project named **AwesomeProject** as mentioned in [Getting Started for macOS iOS](https://facebook.github.io/react-native/docs/getting-started).

## Environment
```
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
      Memory: 190.08 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.14.0 - /usr/local/bin/node
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-23 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, andr
oid-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.4 => 0.59.4 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

## Debug Log
```
macusers-MacBook:AwesomeProject HighSierra$ react-native run-ios
info Found Xcode project AwesomeProject.xcodeproj
info Launching iPhone X (iOS 12.2)...
info Building using "xcodebuild -project AwesomeProject.xcodeproj -configuration Debug -scheme AwesomeProject -destination id=274D552C-C67B-4EFA-A90C-
AF559D0954F0 -derivedDataPath build/AwesomeProject"
info User defaults from command line:

info     IDEDerivedDataPathOverride = /Users/HighSierra/Documents/GitHub/AwesomeProject/ios/build/AwesomeProject


info Build Preparation

info Couldn't create workspace arena folder '/Users/HighSierra/Documents/GitHub/AwesomeProject/ios/build/AwesomeProject': Unable to write to info file
 '<DVTFilePath:0x7f9358f7b8d0:'/Users/HighSierra/Documents/GitHub/AwesomeProject/ios/build/AwesomeProject/info.plist'>'.

info 

error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your a
pp with Xcode.app, by opening AwesomeProject.xcodeproj

2019-04-15 11:50:32.423 xcodebuild[30913:229065] Error saving log: Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied" UserInfo={NSFilePath=/U
sers/HighSierra/Documents/GitHub/AwesomeProject/ios/build/AwesomeProject/Logs/Build/09631BCB-251C-4C0A-8A81-7451C031D0B5.xcactivitylog, NSLocalizedDes
cription=Permission denied} | User info: {
    NSFilePath = "/Users/HighSierra/Documents/GitHub/AwesomeProject/ios/build/AwesomeProject/Logs/Build/09631BCB-251C-4C0A-8A81-7451C031D0B5.xcactivit
ylog";
    NSLocalizedDescription = "Permission denied";
}
** BUILD FAILED **

. Run CLI with --verbose flag for more details.
```

Could anyone assist on this issue?

Thanks.

**Comment by kamilzamerski** [comment]
The same after update xcode ...

**Comment by saxenanickk** [comment]
@jerrychong25 Hey! I can provide a temporary workaround for your problem. Follow these steps:

> File -> Workspace Settings -> Build System -> Legacy Build System

**Comment by alvin-toffler** [comment]
> The same after update xcode ...
> Solution for me was to delete 2 "gray" elements problem from Libraries and rebuild project.

@kamilzamerski Can you elaborate?

**Comment by kamilzamerski** [comment]
@alvin-toffler 
After update XCode i've got that problem with build project. I've discovered that in XCode project in Libraries directory i have 2 bad linked libs (gray icon against blue and without posibility to extend arrow).
I deleted it from the project and once again do a react-native link. And now it's work properly.

![Zrzut ekranu 2019-04-17 o 11 02 06](https://user-images.githubusercontent.com/3854410/56275254-aa813700-6100-11e9-8e58-c748fd154ca6.png)

**Comment by nolan12345** [comment]
File -> Shared Project Settings -> Build System -> Legacy Build System

**Comment by Piero87** [comment]
Yesterday react-native run-ios works with no problem and today I get the error of this issue and haven't change or update anything, any solution?

**Comment by carlosbonilla** [comment]
@Piero87 I had exactly the same problem, I just delete the `build` folder inside `/ios` then just run again `react-native run-ios` and the error disappear.

**Comment by niclin** [comment]
I just try `sudo react-native run-ios` the error disappear.

**Comment by HughBerriez** [comment]
I was getting this same error with regards to the Info.plist.

**Comment by wannyphy** [comment]
I found a solution if someone has a problem and you have to create a new folder in document on the command line and it works the reason remains a mystery but after a while I tried everything well that one logically if  not at the end of the chips I would never have tested it...

**Comment by levelingup** [comment]
> @Piero87 I had exactly the same problem, I just delete the `build` folder inside `/ios` then just run again `react-native run-ios` and the error disappear.

This should be the answer

**Comment by titoleru** [comment]
@Piero87 I had exactly the same problem, I just delete the `build` folder inside `/ios` then just run again `react-native run-ios` and the error disappear.

I tried this and it worked... Thanks!

**Comment by fatWill** [comment]
> 我只是尝试`sudo react-native run-ios`错误消失。

I make it work, Thanks...

**Comment by raphaelpinel** [comment]
> > @Piero87 I had exactly the same problem, I just delete the `build` folder inside `/ios` then just run again `react-native run-ios` and the error disappear.
> 
> This should be the answer

This was the answer for me too!

**Comment by hramos** [comment]
The original author hasn't commented recently, and the template is already tested as part of our CI system, so this shouldn't be a problem on `master` right now. If anyone runs into a similar problem, please submit a new issue.

**Comment by RameshSain** [comment]
in my case 'react-native run-ios' works :)

**Comment by akashrauniyar35** [comment]
> in my case 'react-native run-ios' works :)

Why you came here then?

**Comment by jerrychong25** [comment]
> The original author hasn't commented recently, and the template is already tested as part of our CI system, so this shouldn't be a problem on `master` right now. If anyone runs into a similar problem, please submit a new issue.

Noted and thanks.

**Comment by wembomulumba** [comment]
I deleted the build folder inside the ios and run the react-native run-ios, It Worked

**Comment by BobsonTheFirst** [comment]
This error occurred when I opened my project for the first time in XCode cuz i needed to add a library. Deleting the build folder in the ios folder alone didn't work for me. 

What worked for me:
- In XCode set "Build System" to "Legacy Build System"  (File -> Project Settings -> Build System -> Legacy Build System)
- Delete the "build" folder in the "ios" folder
- npm install (I also deleted my node_modules, cuz was installing a new library)
- react-native run-ios

**Comment by genegr88** [comment]
None of mentioned above has worked for me. I just created new project and can not run it...

**Comment by veller** [comment]
None of these is working for me either. Why is this even closed?

**Comment by vatsalyaagarwal** [comment]
> None of these is working for me either. Why is this even closed?

downgrade to react-native@0.59.5, only thing that worked for me.

**Comment by ilyasKerbal** [comment]
Same issue
`error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening TestProject.xcworkspace. Run CLI with --verbose flag for more details.
User defaults from command line:
    IDEDerivedDataPathOverride`

**Comment by claudiolcastro** [comment]
**Same issue here.**

react-native-cli: 2.0.1
react-native: 0.60.0
xcode: 10.2.1 

`
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening MyApp.xcworkspace. Run CLI with --verbose flag for more details
`

**Comment by claudiolcastro** [comment]
With those configs above, the only thing that worked for me was creating a **new projet with react-native version 0.59.5**

`react-native init MyApp --version 0.59.5`

**Comment by HayTran94** [comment]
> @Piero87 I had exactly the same problem, I just delete the `build` folder inside `/ios` then just run again `react-native run-ios` and the error disappear.

It work for me. Thank you very much!

**Comment by sbvijay** [comment]
Same issue
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening TestProject.xcworkspace. Run CLI with --verbose flag for more details. User defaults from command line: IDEDerivedDataPathOverride

**Comment by HayTran94** [comment]
> Same issue
> error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening TestProject.xcworkspace. Run CLI with --verbose flag for more details. User defaults from command line: IDEDerivedDataPathOverride


Please read the solution above again carefully.

**Comment by NandoSantana** [comment]
> Same issue
> `error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening TestProject.xcworkspace. Run CLI with --verbose flag for more details. User defaults from command line: IDEDerivedDataPathOverride`

Same to me too.

**Comment by dezudas** [comment]
non of above works for me :(

**Comment by ebongso** [comment]
> so far... with those configs above, the only thing that worked for me was creating a **new projet with react-native version 0.59.5** (and reset cache `react-native start --reset-cache`)
> 
> `react-native init MyApp --version 0.59.5`

I am on react-native 0.60.4.
The project didn't run at first. So, had to downgrade to react-native 0.59.5 per the suggestion. Now, the project runs when I execute `react-native run-ios`.

**Comment by ar2zee** [comment]
Not sure that I can help someone, but I got exactly the same error and the problem was with pods or better to say with lack of pods so I went to `/ios` and run `pods install`and it resolve my issue.

**Comment by qodehub-nanadjei** [comment]
1. cd /ios
2. run `pod install`
3. cd ..
4. delete *build* folder
5. run `react-native run-ios`

if error persists, 
1. delete build folder again 
2. open the `/ios` folder in x-code
3. navigate File -> Project Settings -> Build System -> change (Shared workspace settings and Per-User workspace settings): Build System ->  Legacy Build System

**Comment by AmmiWang** [comment]
I Have equally problem, if your has good idea, please @Me.

**Comment by AmmiWang** [comment]
I have equally problem, if your has good idea, please @Me.

**Comment by Rizaldinurm** [comment]
> 1. cd /ios
> 2. run `pod install`
> 3. cd ..
> 4. delete _build_ folder
> 5. run `react-native run-ios`
> 
> if error persists,
> 
> 1. delete build folder again
> 2. open the `/ios` folder in x-code
> 3. navigate File -> Project Settings -> Build System -> change (Shared workspace settings and Per-User workspace settings): Build System ->  Legacy Build System

I hope it will work, install pods ongoing

**Comment by qodehub-nanadjei** [comment]
> I have equally problem, if your has good idea, please @me.

Have you tried the above instructions?

**Comment by Rizaldinurm** [comment]
> > 1. cd /ios
> > 2. run `pod install`
> > 3. cd ..
> > 4. delete _build_ folder
> > 5. run `react-native run-ios`
> > 
> > if error persists,
> > 
> > 1. delete build folder again
> > 2. open the `/ios` folder in x-code
> > 3. navigate File -> Project Settings -> Build System -> change (Shared workspace settings and Per-User workspace settings): Build System ->  Legacy Build System
> 
> I hope it will work, install pods ongoing

yes!! it works. Your cocoapods not installed, maybe its the problem.
I follow this instruction and run well. thanks!!

**Comment by Powaup** [comment]
I've tried all the above and still, nothing works. Everything was fine until I updated my OS earlier today (30 min update)

**Comment by AmmiWang** [comment]
@qodehub-nanadjei Your method doesn't work for me. I've tried it. My phenomenon is that Xcode works, but use run-ios not work.

**Comment by AmmiWang** [comment]
My problem was that I forgot to add startup parameters. I used "react-native run-ios --help" to see some options, and finally I use "react-native run-ios -- secheme XXXX" to start my project.

**Comment by gaozm0509** [comment]
> @Piero87 I had exactly the same problem, I just delete the `build` folder inside `/ios` then just run again `react-native run-ios` and the error disappear.

It worked for me

**Comment by vsfountain** [comment]
I followed @Rizaldinurm 's instructions.  cocoapods was not installed for me.  Worked just fine after that.

**Comment by Gregory-Canonne** [comment]
if you have this error : 

-> remove your folder build in forlder ios
-> rm -rf node_modules
-> yarn install
-> react-native run-ios

enjoys !

**Comment by NivediB** [comment]
Tried this and it worked... 
create native react project  using  this  react-native init MyApp --version 0.59.
Build the app with Xcode.app

**Comment by quangduz** [comment]
> so far... with those configs above, the only thing that worked for me was creating a **new projet with react-native version 0.59.5** (and reset cache `react-native start --reset-cache`)
> 
> `react-native init MyApp --version 0.59.5`

always works :))

**Comment by ruihuasui** [comment]
> If you don't have cocoa pods installed you need to `sudo gem install cocoapods`
> 
> 1. cd /ios
> 2. run `pod install`
> 3. cd ..
> 4. delete _build_ folder
> 5. run `react-native run-ios`
> 
> if error persists,
> 
> 1. delete build folder again
> 2. open the `/ios` folder in x-code
> 3. navigate File -> Project Settings -> Build System -> change (Shared workspace settings and Per-User workspace settings): Build System ->  Legacy Build System

Thank you SO MUCH. It's the only solution works to me!

**Comment by xgqfrms-GitHub** [comment]
# iOS bug

> pod install failed

![image](https://user-images.githubusercontent.com/18028768/64489016-1ebfa100-d281-11e9-8423-82925c2c0a6f.png)

**Comment by xgqfrms-GitHub** [comment]
> if error persists,
> 
> 1. delete build folder again
> 2. open the `/ios` folder in x-code
> 3. navigate File -> Project Settings -> Build System -> change (Shared workspace settings and Per-User workspace settings): Build System ->  Legacy Build System

![image](https://user-images.githubusercontent.com/18028768/64489811-eff9f880-d289-11e9-903e-13859568d560.png)

**Comment by diazevedo** [comment]
> If you don't have cocoa pods installed you need to `sudo gem install cocoapods`
> 
> 1. cd /ios
> 2. run `pod install`
> 3. cd ..
> 4. delete _build_ folder
> 5. run `react-native run-ios`
> 
> if error persists,
> 
> 1. delete build folder again
> 2. open the `/ios` folder in x-code
> 3. navigate File -> Project Settings -> Build System -> change (Shared workspace settings and Per-User workspace settings): Build System ->  Legacy Build System

I have no words to describe how useful it was.

**Comment by vgb0332** [comment]
Not gonna lie. RN should post this on its tutorial section to make sure older version user has to spend hours to find what's been wrong with the settings...Not everyone knows how to use xcode properly. Isn't it the whole purpose of using RN?

**Comment by devdigitalappteam** [comment]
> > @Piero87 I had exactly the same problem, I just delete the `build` folder inside `/ios` then just run again `react-native run-ios` and the error disappear.
> 
> This should be the answer

Work fine after deleting build folder and re-run

**Comment by devohno** [comment]
> If you don't have cocoa pods installed you need to `sudo gem install cocoapods`
> 
> 1. cd /ios
> 2. run `pod install`
> 3. cd ..
> 4. delete _build_ folder
> 5. run `react-native run-ios`
> 
> if error persists,
> 
> 1. delete build folder again
> 2. open the `/ios` folder in x-code
> 3. navigate File -> Project Settings -> Build System -> change (Shared workspace settings and Per-User workspace settings): Build System ->  Legacy Build System

Thanks. it works goooooooood.

**Comment by wandevseat** [comment]
> Eu tentei todas as opções acima e ainda assim, nada funciona. Tudo estava bem até que eu atualizei meu sistema operacional hoje (atualização de 30 min).
> 
> Atualização: excluí o arquivo AwesomeProject e inicializei um novo e a compilação foi bem-sucedida. No entanto, agora recebo uma mensagem no simulador dizendo "não foi possível conectar ao servidor de desenvolvimento"
> ![Captura de tela 2019-07-31 em 1 48 36 PM](https://user-images.githubusercontent.com/15273149/62247755-5a6e6d80-b39b-11e9-9bb0-b6399957a84f.png)
> 
> Atualização [2](https://github.com/facebook/react-native/issues/2) : excluir a pasta de compilação funcionada, voltando a ver a tela "Bem-vindo ao reagir no simulador do iPhone"

Comigo foi assim também, mas e so dar um ( command + R ) pra resetar a conexão

**Comment by Henry23** [comment]
> @Piero87 I had exactly the same problem, I just delete the `build` folder inside `/ios` then just run again `react-native run-ios` and the error disappear.

Thanks

**Comment by mohmdalfaha** [comment]
Literally, not even a single one could fix the issue. I tried all the suggestions. The only solution I might need to do is formatting my whole mac with a clean installation of all tools.

**Comment by phuongthuan** [comment]
> If you don't have cocoa pods installed you need to `sudo gem install cocoapods`
> 
> 1. cd /ios
> 2. run `pod install`
> 3. cd ..
> 4. delete _build_ folder
> 5. run `react-native run-ios`
> 
> if error persists,
> 
> 1. delete build folder again
> 2. open the `/ios` folder in x-code
> 3. navigate File -> Project Settings -> Build System -> change (Shared workspace settings and Per-User workspace settings): Build System ->  Legacy Build System

It's working. Thank you

**Comment by garshen** [comment]
> This error occurred when I opened my project for the first time in XCode cuz i needed to add a library. Deleting the build folder in the ios folder alone didn't work for me.
> 
> What worked for me:
> 
> * In XCode set "Build System" to "Legacy Build System"  (File -> Project Settings -> Build System -> Legacy Build System)
> * Delete the "build" folder in the "ios" folder
> * npm install (I also deleted my node_modules, cuz was installing a new library)
> * react-native run-ios

Perfect it worked for me,,Thanks

**Comment by PatelAshish1** [comment]
Already solved At [Here](https://icetutor.com/question/error-running-react-native-app-from-terminal-ios/)

**Comment by zeusnayan** [comment]
You may need to install or set the location of the Xcode Command Line Tools.

Via command line
If you have Xcode downloaded you can run the following to set the path:

sudo xcode-select -s /Applications/Xcode.app
If the command line tools haven’t been installed yet, you may need to run this first:

xcode-select --install
You may need to accept the Xcode license before installing command line tools:

sudo xcodebuild -license accept
Via Xcode
Or adjust the Command Line Tools setting via Xcode (Xcode > Preferences > Locations):

Source With Example Available [Here](https://icetutor.com/question/error-running-react-native-app-from-terminal-ios/)

**Comment by anandaneesh** [comment]
This worked for me!
```
     react-native start --reset-cache
     rm -rf node_modules/
     rm -rf package-lock.json 
     cd ios
     pod deintegrate
     cd ..
     rm -rf ios/Podfile.lock 
     npm install
     npm audit fix
     react-native link
     cd ios
     pod install
     cd ..
     react-native run-ios
```

**Comment by nihp** [comment]
@phuongthuan  @garshen Your solution not worked for me

**Comment by nihp** [comment]
Fixed by the following step

1. rm -rf Podfile.lock
2. pod install

**Comment by thiagosrib** [comment]
Nothing above worked for me. Only worked when I include --scheme param in react-native run-ios

> react-native run-ios --scheme "xxxx"

**Comment by nihp** [comment]
@thiagosrib How can you set the scheme param. I also facing the same error.

Can you brief me about scheme param?

**Comment by thiagosrib** [comment]
@nihp in my case, the project that I work has two schemes in Xcode (Dev and Prod).

So, I used the command below and it worked for me

`react-native run-ios --scheme "Dev"` or `react-native run-ios --scheme "Prod"`

**Comment by Asrover** [comment]
1. `sudo gem install cocoapods`
2. `cd ios` (Folder in your react-native project)
3. `pod install`
4. Restart XCode
5. `react-native run-ios `

**Comment by qodehub-nanadjei** [comment]
https://github.com/facebook/react-native/issues/24450#issuecomment-516760157

Solution here 👆

**Comment by thiagosrib** [comment]
@nihp to create schemes, on Xcode goes to `Product -> Schemes -> Manage Schemes... -> (Plus icon to create new scheme)`.

After create a new scheme, you can manage the configurations chosing Edit option.

Sorry for the delay in my answer.

**Comment by ravics09** [comment]
You can try

**Comment by nihp** [comment]
Can anyone of you confirm after upgrading how your Header Seach Paths are? Is it like (${PODS_ROOT}/Headers/Public/BugsnagReactNative")  **Or** ($RCTROOT/filename).

What is the correct one after upgrade to 0.60.0 or 0.61.5

**Comment by LAITONEN** [comment]
Ok, I got it. Had issues setting-up a new project after not using React-Native for a lot of time.

My system:

macOS High Sierra 10.13.6
XCode 9.4
Had to reinstall the project in order to use the installation guide from version 0.59.0, because the installation guide from 0.61 uses approach with npx react-native ..., which disallows the usage of react-native below 0.60 (quite totalitarian). 0.59.0 was still using the global version of react-native installed through npm.

In other words:
Reinstall the project by removing the old one and use the steps mentioned in the "Getting Started" guide of React-Native 0.59.0 (or any other version compatible with your version of OS and XCode) to install your project again. No need to delete any build or node_modules or installing pods again and so forth, just pick the version of React-Native compatible with your macOS and Xcode (by downgrading and reinstalling the project until you get it) and no need to upgrade to the latest versions, they are developed for the latest systems, if you don't want to buy the latest devices to support the latest software (OS) or you can't afford them, just stay with the old ones - it's totally fine :)

**Comment by congtrieu112** [comment]
should be remove build folder in folder ios and run again, I work good

**Comment by anastely** [comment]
I did every single thing above but still the issues, I can't build my ios app :(

**Comment by Khushboo-gupta-123** [comment]
when i run my react-native project on terminal for ios i faced this issue??is there any solution i tried everything  but i can't run my app and my xcode not working when i open my project.
"Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening demo.xcworkspace"

**Comment by DeadDuck83** [comment]
@Khushboo-gupta-123 I got the same result. I know this is not the solution you are looking for, but what worked for me was deleting my Node Modules and then Yarn them back and if-so fact-o, it worked. Not a fix, but it worked for me.

1. Delete **node_modules**
2. **Yarn** to re-install them.

**Comment by GuilhermeTrivilin** [comment]
What worked for me was to rename the project by removing the special characters.

Example: "project_marketplace" to "projectmarketplace"

In this case, I redid the project with react-native init and copied the src and package.json folder.

**Comment by pereligins** [comment]
Hi All!
I have updated Xcode to 11.4.
It solves this problem for me.

**Comment by meetajhu** [comment]
This happens when you terminate the metro bundler terminal window. So make sure you start the metro bundler again by running

`npx react-native start`

then open your iOS project in Xcode Goto -> Product -> Clean build folder. Then goto your terminal project path start again

`npm react-native run-ios`

Hope it helps
