### ISSUE TITLE
PanResponder is not working in android

### ISSUE THREAD

**Issue by hanbitkim** [facebook/react-native#24451]
## 🐛 Bug Report
I wanted to make overlapped card views like android multitasking screen. So i used negative marginTop in flatlist item and added panresponder only the top view. But panresponder is not working in overlapped area. The touch event passed to the first view(the deepest view)
IOS is working as I expected.

## Environment
React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 194.99 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.1 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.3 => 16.8.6 
      react-native: ^0.59.3 => 0.59.3 
    npmGlobalPackages:
      react-native-create-library: 3.1.2
      react-native-git-upgrade: 0.2.7

**Comment by tominou** [comment]
Please share some code

**Comment by hanbitkim** [comment]
I will share the test code
And in addition, button also has same issue. when i press the button in top view, the event is passed to the first view.
