### ISSUE TITLE
[Animated] using AnimatedValue on shadowOffset will throw 

### ISSUE THREAD

**Issue by arypurnomoz** [facebook/react-native#2445]
```
// Will throw `NSDictionary cannot be converted to a number`.
shadowOffset: {
  width: animatedValue
}
```
`transform` properties has AnimatedTransform class, maybe shadowOffset should have their Animated class too.

**Comment by browniefed** [comment]
@brentvatne @vjeux This is the same issue with array props issue and animated. The Animated doesn't seem to traverse style properties w/ Objects.

Repro - https://rnplay.org/apps/fMXbXw

**Comment by brentvatne** [comment]
#2211 dup
