### ISSUE TITLE
[Testing] Creating integration tests

### ISSUE THREAD

**Issue by besarthoxhaj** [facebook/react-native#2446]
Hi guys!

We are trying to create some basic integration/snapshot tests for our app.

Here is the repo: https://github.com/Danwhy/learn-react-native/tree/master/testing

Our tests are just hanging or always passing. However in general we would like to know how to write basic integration tests for components.

Any suggestions are more than welcome!:)

**Comment by NataliaLKB** [comment]
:+1:

**Comment by nofootnotes** [comment]
:+1:

**Comment by izaakrogan** [comment]
:+1:

**Comment by brentvatne** [comment]
Check out: https://github.com/kif-framework/KIF for acceptance testing - I've had good success using this on a React Native app. Alternatively, like you have attempted here, you could use the integration testing harness built into React Native. Sorry there is not currently a lot of documentation around this. @tadeuzagallo may be able to help you out. If you figure it out we would love to add a section on this to the docs!

**Comment by browniefed** [comment]
@brentvatne you suggested, also https://github.com/facebook/webdriveragent .
Close?

**Comment by besarthoxhaj** [comment]
Happy to close it guys! Thanks for the feedbacks!

**Comment by brentvatne** [comment]
:smile: :rocket:
