### ISSUE TITLE
ios RCTView出现崩溃崩溃 

### ISSUE THREAD

**Issue by fangbo111** [facebook/react-native#24462]
崩溃在for (UIView *subview in self.subviews) {
    [subview react_updateClippedSubviewsWithClipRect:clipRect relativeToView:clipView];
  }  这里

**Comment by fangbo111** [comment]
-[UIView(RCTViewUnmounting) react_updateClippedSubviewsWithClipRect:relativeToView:]  这是崩溃原因  下面这张图 是崩溃的位置
![屏幕快照 2019-04-16 下午8 28 33](https://user-images.githubusercontent.com/16485276/56209497-4d489f80-6086-11e9-9427-6aea9cdff001.png)

**Comment by zhongwuzw** [comment]
@fangbo111 Can you provide Exception type and entire crash log?

**Comment by satya164** [comment]
Closing due to incomplete issue template
