### ISSUE TITLE
Metro bundler has encountered an internal error

### ISSUE THREAD

**Issue by Sulesh43** [facebook/react-native#24469]
Actually I am very beginner, and started react-native development just a couple of days ago,

I have been facing **'Metro bundler has encountered an internal error'** since morning

here is my complete app.js  code

import React from 'react';
import {StyleSheet,Button,View,Text,Image,TouchableHighlight,Linking,ScrollView, ActivityIndicator} from 'react-native';
import { createStackNavigator, createAppContainer } from 'react-navigation'; 

class HomeScreen extends React.Component 
{
   static navigationOptions= 
  {
    title: 'Home Screen',
  }; 
  
  render() 
  {
    return (
     
    <View style={styles.header}>
      
      <ImageBackground style={styles.cart}
          source={require('C:\Users\Aris\Documents\ReactWork\ARIS\app\img\logo.png')}>
      </ImageBackground>
      
        <Text style={styles.logo}>ARIS</Text>

        <ScrollView style={styles.container}>        
          
        <Button>
          title = "Next Screen"
          onPress={()=>this.props.navigation.navigate('Related')} 
        </Button>
    
        </ScrollView>
    </View>
     
    
      
    )
  }
 
}

export default class App extends Component {
  render()
  {
    return <AppContainer/>
  }    
}

const RootStack = createStackNavigator(
  {
      Home: {screen: HomeScreen},
      Related :{ screen:RelatedItems},
  });
  
const AppContainer = createAppContainer(RootStack);
  

const styles = StyleSheet.create({
  container:{
    flex:1,
    backgroundColor:'#fff',
  },
  header:{
    height:80,
    marginTop:20,
    backgroundColor:'#fff',
    flexDirection:'row',
    alignItems:'center',
    justifyContent:'center',
    padding:20,
    borderBottomWidth:4,
    borderBottomColor:'#ccc'
  },
  cart:{
    width:40,
    height:40,
  },
  logo:{
    fontSize:28,
    fontFamily:'algerian',
    marginLeft:10,
    fontStyle:'italic',
    color:'#006400',
    fontWeight:'bold'
  }
});

![image](https://user-images.githubusercontent.com/48822183/56208549-d9e56480-606a-11e9-9e08-7c35b8badbcc.png)
![image](https://user-images.githubusercontent.com/48822183/56208729-3d6f9200-606b-11e9-9ae2-655130d62f9a.png)

and here is screenshot of error I am facing, can anyone help me about this problem?

**Comment by kelset** [comment]
👋 there - it seems that your issue is actually that the bundler can't find the `img` folder. So maybe you tried to write an import wrongly?

This line seems to be the culprit:

`'C:\Users\Aris\Documents\ReactWork\ARIS\app\img\logo.png'`

Closing as not really an issue with React Native itself
