### ISSUE TITLE
How to copy text from <Text> component

### ISSUE THREAD

**Issue by dmitruksergey** [facebook/react-native#2447]
Hi, guys. How to copy text from <Text> component? Any idea?

**Comment by smartdemocracy** [comment]
Use `onChangeText`

![image](https://cloud.githubusercontent.com/assets/6221799/9498351/be25b99a-4bef-11e5-8880-30ae2f2959cf.png)

**Comment by dmitruksergey** [comment]
And then? I want to copy text from <Text/> component

**Comment by smartdemocracy** [comment]
onChangeText: Callback that is called when the text input's text changes. Changed text is passed as an argument to the callback handler.

https://facebook.github.io/react-native/docs/textinput.html#onchangetext

**Comment by dmitruksergey** [comment]
But I want to copy text to clipboard. Sorry for my bad english.

**Comment by smartdemocracy** [comment]
My English is not good. I speak Portuguese. 😅

Try using it in the callback:
https://www.npmjs.com/package/react-native-clipboard

**Comment by dmitruksergey** [comment]
Cool, it works! But maybe you know react-native component with tooltip?
Like this:
![img_0198](https://cloud.githubusercontent.com/assets/4532683/9499514/98bdf2ce-4c28-11e5-8a9e-331c3f53f681.PNG)

**Comment by smartdemocracy** [comment]
I've never seen 😕
The Facebook app Groups, made with react-native also does not have it, it displays an ugly popup.

**Comment by dmitruksergey** [comment]
Well, react-native, challenge accepted!

**Comment by smartdemocracy** [comment]
In fact, the popup is to select <Text> elements. For the TextInput, the selection usually works here.

![image](https://cloud.githubusercontent.com/assets/6221799/9499835/3507249c-4bf8-11e5-8e71-d81a2eb3aac5.png)

**Comment by dmitruksergey** [comment]
Yep, but only in <TextInput/>.

**Comment by chirag04** [comment]
if you need custom actions with custom tooltip: https://github.com/chirag04/react-native-tooltip

**Comment by brentvatne** [comment]
Nice one @chirag04 :)

**Comment by Traviskn** [comment]
Is it possible to show the default iOS tooltip with the copy option on a text component?  Or do we need to always use a custom tooltip?

**Comment by satya164** [comment]
@Traviskn You could have a read-only text-input I guess.

**Comment by joonhocho** [comment]
has anyone found a solution to this?
On iOS, if you hold any text long enough, it should show the tooltip for copying.
I don't know how it works on Android, though.

**Comment by danielbh** [comment]
Any plans for making this work with iOS without add in?

**Comment by shahchaitanya** [comment]
Try it :)
import {Clipboard} from 'react-native';
<Text selectable={true} onPress={()=>this.setClipboardContent(message)} />

setClipboardContent = (email) => {
        Clipboard.setString(email);
    };

**Comment by starchand** [comment]
@shahchaitanya is this android only?

**Comment by jfilter** [comment]
For most people, this is enough:

`<Text selectable>TEXT</Text>`

**Comment by kholiavko-roman** [comment]
@jfilter, it works perfectly on android, but on iOS - it whows only 'Copy' dialog, without selecting range. 
Did you know how enable opportunity to select text before copy ?

**Comment by skyl** [comment]
`selectable` doesn't yet work for react-native-macos but there is a workaround: https://github.com/ptmt/react-native-macos/issues/157
