### ISSUE TITLE
Android release builds fail when requiring images

### ISSUE THREAD

**Issue by kodayashi** [facebook/react-native#24474]
## 🐛 Bug Report

#16906 is still an issue

## To Reproduce
Require an image in your app

```javascript
import myImage from '../myImage.png'

<Image source={myImage} />
```

## Expected Behavior
Android release build should work. Instead only simulator builds work. Same issue as #16906

## Environment
```
info
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
      Memory: 32.96 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.2 - ~/.nvm/versions/node/v10.14.2/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.14.2/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.4 => 0.59.4
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

**Comment by kodayashi** [comment]
Found this, stating that there's an issue with Gradle when it comes to large files: https://stackoverflow.com/questions/52712063/build-failing-during-merge-resources-with-android-gradle-plugin-3-3-0

Indeed my file was 10MB and when I resized it to 2.2MB everything worked. So there's something off here, just not sure why a 10MB file would fail and a 2.2MB file works fine.

**Comment by dulmandakh** [comment]
So it's related to Gradle, but it's unreasonable to bundle 10MB image in APK because Play Store have size restrictions.
