### ISSUE TITLE
InputAccessoryView does not go full width in landscape view

### ISSUE THREAD

**Issue by beaur** [facebook/react-native#24473]
## 🐛 Bug Report
When InputAccessoryView is used in landscape, the view does not go full width.
Screenshot: http://beaur.us/hntuI5

## To Reproduce
Expo snack is available here: https://snack.expo.io/B1Ba-l454
Note you will need to run it on a real device, and rotate the device to landscape.

## Expected Behavior
View should go full width.

## Code Example
Expo snack is available here: https://snack.expo.io/B1Ba-l454

## Environment
Expo SDK 32 so React Native 57?
Edit Jan 2020: Have also test Expo 36 (React Native 0.61)

**Comment by beaurushton** [comment]
It’s still an issue

**Comment by beaurushton** [comment]
It’s still an issue

**Comment by hramos** [comment]
Can you make sure the entire issue template is filled out?

**Comment by beaurushton** [comment]
What exactly am I missing?  I've just tried the snack under Expo SDK 36 (react native version 0.61) and it is still an issue.

**Comment by hramos** [comment]
@beaurushton looks like a formatting error in your post resulted in the hiding of the rest of the template (there's a stray comment). Specifically, I am looking for the Environment portion of the issue template and what you expected to happen.

**Comment by beaurushton** [comment]
@hramos I have removed the stray comment from original post.

**Comment by cristianoccazinsp** [comment]
Still an issue.
