### ISSUE TITLE
Regression: Invalid Swift Support - The expected dylibs are missing from the app’s Framework location, such as /Payload/Golfstiks.app/Frameworks.

### ISSUE THREAD

**Issue by arshidkv12** [facebook/react-native#24487]
## 💥 Regression Report
 Invalid Swift Support - The expected dylibs are missing from the app’s Framework location, such as /Payload/Golfstiks.app/Frameworks.

## Last working version

Worked up to version:

Stopped working in version:

## To Reproduce
Upload to ios appstore

 

## Environment
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
      Memory: 66.57 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.3, 25.0.2, 25.0.3, 26.0.1, 26.0.3, 27.0.3, 28.0.2, 28.0.3
        System Images: android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5014246
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1
      react-native: 0.56.0 => 0.56.0
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

**Comment by ericlewis** [comment]
Hm. is this happening when you upload to the app store? Are you using fastlane or something? have you tried setting the flag in build settings to always embed swift?

**Comment by arshidkv12** [comment]
I didn't added expo or fastlane. I added always embed swift is yes. When I get error after uploafed to app store.

**Comment by ericlewis** [comment]
What version of swift are you using? Make sure to put some sort of empty swift file in your project so it will compile properly.

**Comment by arshidkv12** [comment]
Swift version 4.2.1
xcode : 10.1

I am not seeing 'Swift Compiler - Languages' in build settings.

**Comment by michalchudziak** [comment]
Hello there 👋 this issue doesn't have a repro (which means, a `react-native init`-ed project with the minimal changes that leads to creating the same issue you are reporting). Unfortunately, I have no way of helping you in a meaningful way – there is no easy way for me to recreate the situation and check that the issue reported is still there when changing the code.

Because of this, we are going to close this issue - but if a repro is shared, we are happy to reopen it 🤗
