### ISSUE TITLE
How to reload in android?

### ISSUE THREAD

**Issue by YuanWenHai** [facebook/react-native#24482]
## 🐛 Bug Report
  I was use react-native 0.55.4 to develop android app,in that version I can press double R to reload the js file from server,and now I'm starting a new project that with version 0.59.4,double R is not working,is there something changed?

## Code Example
public class ReactActivity extends AppCompatActivity implements DefaultHardwareBackBtnHandler {

    private ReactRootView mReactRootView;
    private ReactInstanceManager mReactInstanceManager;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        mReactRootView = new ReactRootView(this);
        mReactInstanceManager = ReactInstanceManager.builder()
                .setApplication(getApplication())
                .setCurrentActivity(this)
                .setBundleAssetName("index.android.bundle")
                .setUseDeveloperSupport(true)
                .setJSMainModulePath("index")
                .addPackage(new MainReactPackage())
                .setUseDeveloperSupport(BuildConfig.DEBUG)
                .setInitialLifecycleState(LifecycleState.RESUMED)
                .build();
        // The string here (e.g. "MyReactNativeApp") has to match
        // the string in AppRegistry.registerComponent() in index.js
        mReactRootView.startReactApplication(mReactInstanceManager, "HelloWorld", null);
        setContentView(mReactRootView);
    }

    @Override
    public void invokeDefaultOnBackPressed() {
        this.onBackPressed();
    }

    @Override
    protected void onResume() {
        super.onResume();
        if(mReactInstanceManager != null) {
            mReactInstanceManager.onHostResume(this, this);
        }
    }

    @Override
    protected void onPause() {
        super.onPause();
        if (mReactInstanceManager != null) {
            mReactInstanceManager.onHostPause(this);
        }
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        if (mReactInstanceManager != null) {
            mReactInstanceManager.onHostDestroy(this);
        }
        if (mReactRootView != null) {
            mReactRootView.unmountReactApplication();
        }
    }

    @Override
    public boolean onKeyUp(int keyCode, KeyEvent event) {
        if (keyCode == KeyEvent.KEYCODE_MENU  && mReactInstanceManager != null) {
            mReactInstanceManager.showDevOptionsDialog();
            return true;
        }
        return super.onKeyUp(keyCode, event);
    }

}

## Environment
 React Native Environment Info:
   System:
     OS: Windows 7
     CPU: (8) x64 Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz
     Memory: 4.84 GB / 15.70 GB
   Binaries:
     Node: 8.11.3 - E:\nodejs\node.EXE
     Yarn: 1.9.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
     npm: 6.8.0 - E:\nodejs\npm.CMD

**Comment by JKCooper2** [comment]
Make sure you are not running a release build as the reload/dev menu aren't enabled on them AFAIK. Are you able to run Ctrl+M or Cmd+M to access the dev menu on Android?
