### ISSUE TITLE
`Undefined symbols for architecture x86_64:

### ISSUE THREAD

**Issue by ifgyong** [facebook/react-native#24483]
I got a progrem.
`Undefined symbols for architecture x86_64:
  "_JSClassCreate", referenced from:
      facebook::jsc::JSCRuntime::createObject(std::__1::shared_ptr<facebook::jsi::HostObject>)::$_0::operator()() const in libReact.a(JSCRuntime.o)
      facebook::jsc::JSCRuntime::createFunctionFromHostFunction(facebook::jsi::PropNameID const&, unsigned int, std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)>)::$_1::operator()() const in libReact.a(JSCRuntime.o)
      `

someone help me.
`"dependencies": {
		"eslint": "^5.16.0",
		"npm-watch": "^0.6.0",
		"react": "16.0.0",
		"react-native": "^0.59.4",
		"react-native-gesture-handler": "^1.1.0",
		"react-navigation": "^3.8.1"
	},
	"devDependencies": {
		"babel-jest": "24.7.1",
		"babel-preset-react-native": "4.0.1",
		"jest": "24.7.1",
		"react-test-renderer": "16.0.0"
	},
	"jest": {
		"preset": "react-native"
	}`

**Comment by cuibeihong** [comment]
Make sure JavaScriptCore.framework is added to "Link Binary With Libraries"
[https://stackoverflow.com/questions/54515175/undefined-symbols-for-architecture-arm64-jsclasscreate](url)
