### ISSUE TITLE
Android borderRadius antiAliasing / jagged edges

### ISSUE THREAD

**Issue by danilobuerger** [facebook/react-native#24486]
## 🐛 Bug Report

Drawing nested Views with borderRadius results in a jagged edge:

![Screenshot_1555492388](https://user-images.githubusercontent.com/996231/56275864-cfc27500-6101-11e9-90f8-ba1bbb285613.png)

## To Reproduce

```
<View style={{ height: 100, width: 100, borderRadius: 50, backgroundColor: "red" }}>
  <View style={{ height: 100, width: 100, borderRadius: 50, backgroundColor: "yellow" }} />
</View>
```

or

```
<View style={{ height: 100, width: 100, borderRadius: 50, backgroundColor: "red", overflow: "hidden" }}>
  <View style={{ height: 100, width: 100, backgroundColor: "yellow" }} />
</View>
```

## Expected Behavior

Only a circle with the color yellow should be visible, no red.

## Code Example

https://snack.expo.io/By7LJu49E

## Environment

```
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
      Memory: 34.91 MB / 16.00 GB
      Shell: 5.7.1 - /usr/local/bin/zsh
    Binaries:
      Node: 11.13.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.1, 25.0.2, 25.0.3, 26.0.2, 26.0.3, 27.0.3, 28.0.3
        System Images: android-16 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.4 => 16.8.4 
      react-native: 0.59.4 => 0.59.4 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

**Comment by farwayer** [comment]
I can confirm. And view is not so ideal round as it should be. More ellipse than circle. This issue prevents from using `borderRadius` for generating circle views.
![2019-04-30-180044_176x150_scrot](https://user-images.githubusercontent.com/2343101/56971442-e4772200-6b71-11e9-96cd-acf1626a705b.png)

**Comment by punksta** [comment]
https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewBackgroundDrawable.java  - this class draws view backgrounds. It might be working wrong with antiAliasing.

**Comment by ThinkSalat** [comment]
I have the same issue on iPhone XR on RN 0.59.9.

**Comment by Linoa65** [comment]
Someone knows if there is a workaround ?

**Comment by BrodaNoel** [comment]
I'm using the last version of Expo (which uses RN 59.9), and I have some similar problem or even worst. I can say that there is a regression of this one: https://github.com/facebook/react-native/issues/17267

**Comment by rkdavidson** [comment]
Seeing this on RN 0.59.9 only on Android.

**Snack to show what I'm seeing:** https://snack.expo.io/rJqV_WTWS

In my case, I have a button with dynamic border changing on certain UI states.
I want the border to be same color as background by default, which on iOS creates illusion of seamless borderless element.

ex:
```javascript
const jaggedBorderStyle = {
  padding: 16,
  backgroundColor: '#1291D9', // Same color
  borderColor: '#1291D9',     // Same color
  borderRadius: 32,
  borderWidth: 2,
},
```

I wouldn't run into this issue if the border placement inside/outside box model of `View` was consistent between iOS and Android.

**Screenshots**
(easier to see when opened in separate tab/zoomed in)
![CleanShot 2019-07-17 at 16 38 19@2x](https://user-images.githubusercontent.com/1812955/61410227-e9668a80-a8b1-11e9-9b0c-03264ae6f1f0.png)
<img width="400" alt="CleanShot 2019-07-17 at 16 40 55@2x" src="https://user-images.githubusercontent.com/1812955/61410228-e9ff2100-a8b1-11e9-881e-ce55107eba9c.png">

**Comment by farwayer** [comment]
Issue is still exists in the latest (v0.61.2) React Native build.

**Comment by dave05974** [comment]
+1 still an issue

**Comment by dave05974** [comment]
confirming issue on `0.59.9`

My env:
```
  React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 949.63 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - ~/.asdf/shims/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.asdf/shims/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5900203
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.9 => 0.59.9
```

**Comment by dave05974** [comment]
I reviewed https://github.com/react-native-community/releases/blob/master/CHANGELOG.md and it doesn't seem like the issue has been resolved yet.

**Comment by mohsinriaz17** [comment]
+1 
"react-native": "0.61.5"

no need to even zoom, 
<img width="165" alt="Screenshot 2020-02-13 at 12 11 06 AM" src="https://user-images.githubusercontent.com/6935470/74368389-5d8bf100-4df5-11ea-9be9-375c35c70830.png">

**Comment by codecog** [comment]
Using border radius with v5 of styled-components seems to give a smooth edge.
