### ISSUE TITLE
Discussion: Numeric font-weight support

### ISSUE THREAD

**Issue by infinnie** [facebook/react-native#24499]
CSS module 4 has introduced support for numeric font-weight values, which can be custom interpolated values in variable fonts. Perhaps React Native needs support for that too.

**Comment by dulmandakh** [comment]
You can use numeric fontWeight but you need to provide it as string or with quotes like '400'.

**Comment by infinnie** [comment]
Yes but what about “123.4”?

**Comment by dulmandakh** [comment]
IIRC, there are only from 100 to 700 and it's in hundreds like 700 for bold
etc.
