### ISSUE TITLE
Discussion: Sharing file using Bluetooth 

### ISSUE THREAD

**Issue by RamashishTomar** [facebook/react-native#24490]
I am facing an issue while sharing file, i can share the file using  library react-native-share over many social media platforms .  But did not found a single way to share a file over bluetooth. 
when used Share (React-native) component
https://facebook.github.io/react-native/docs/share#share
the file path is converted into an html document having file path but not able to share the path.
is there any way possible??

**Comment by dulmandakh** [comment]
I don't think that RN will support it in the near future, so I would suggest to use third-party modules to do it or developer your own native module. Thank you.
