### ISSUE TITLE
[Docs] Components roadmap?

### ISSUE THREAD

**Issue by bootstraponline** [facebook/react-native#245]
Is there a list of [components that are planned](https://github.com/facebook/react-native/issues/121#issuecomment-82738356) for react-native on iOS?

It'd be nice to have:

-  [UIButton](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIButton_Class/)
- SecureTextInput (I think this is done via secureTextEntry and [UITextField](https://developer.apple.com/library/prerelease/ios/documentation/UIKit/Reference/UITextField_Class/index.html))

**Comment by ide** [comment]
I just published [react-native-button](https://github.com/ide/react-native-button) if you want to give it a try. It's very simple and primarily makes it more convenient to create iOS-style buttons with the correct opacity constant.

**Comment by bootstraponline** [comment]
Cool! I think for the secure text field, there needs to be a way to enable the [secureTextEntry
  trait](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UITextInputTraits_Protocol/) on the existing react-native TextInput component.

**Comment by ide** [comment]
You're totally right. I added a bunch of TextInput properties in https://github.com/facebook/react-native/pull/109. It wouldn't be too hard to expose `secureTextEntry` (especially since it's just a boolean) in a similar way.

**Comment by bootstraponline** [comment]
My use case is having a user type in their password to the secure textinput (regular textinput isn't desirable for this) as part of logging into the app. I see `secureTextEntry` in that PR, it's just not exported as a view property. It'd be great if this feature was added.

**Comment by jlmitch5** [comment]
+1 on a roadmap

**Comment by brentvatne** [comment]
@vjeux - any plans to publicize a project roadmap?

**Comment by vjeux** [comment]
For the components, we open sourced all the ones that we have that do not depend on fb infra and are in a good shape.

As for publishing a roadmap, we first need to figure one out :))

More seriously, one idea that was thrown around was to add a "What are we working on" section in the rc changelogs every two weeks. This way we can give people some visibility into what's coming next.

**Comment by brentvatne** [comment]
@vjeux - "What are we working on" would be nice to see!

**Comment by bootstraponline** [comment]
:+1: for "What are we working on"

**Comment by holoed** [comment]
:+1: for "What are we working on"

**Comment by evanmrose** [comment]
+1 for "What are we working on"

**Comment by alexdunae** [comment]
+1 for "What are we working on" -- I bet it's amazing.

**Comment by apolkingg8** [comment]
+1 for "What are we working on". That's avoid to work hard on breaking changes.

**Comment by jaygarcia** [comment]
This issue should be closed as the FB dev team agrees that this is a great idea, but needs to get around to doing it eventually :)  /cc @brentvatne

**Comment by bootstraponline** [comment]
Usually you'd wait to actually fix the issue before closing?

**Comment by brentvatne** [comment]
@bootstraponline - agreed, but this issue isn't doing much good just lingering open in its current state among several hundred others.

This would require a time commitment from the team at Facebook to 1) do the initial write up 2) maintain and 3) it would potentially frustrate people if they do not stick with what they proposed as the roadmap. It's not something that I or other external contributors could really take on. So I don't know what a good solution here is. cc @vjeux

**Comment by brentvatne** [comment]
@bootstraponline - here you go, components roadmap for Android!

**Comment by bootstraponline** [comment]
Thanks!

**Comment by brentvatne** [comment]
:)

**Comment by chirag04** [comment]
Informal without any promises "What are we working on" section would be amazing. Community support could help reduce the maintenance of it. We can use github issue with locked conversation or official docs or with every RC release notes we can add this section.

cc @vjeux
