### ISSUE TITLE
Discussion: SetTimeout not work in Constructor 

### ISSUE THREAD

**Issue by Karanp13** [facebook/react-native#24500]
## 🐛 Bug Report
  I trying set timeout in constructor calling function. 

## To Reproduce and Code Example
  constructor(props) {
    super(props);
    const { navigate } = this.props.navigation;
    this.state = {
      country: '',
      timePassed:false,
    };
    //this.imagechange;
    this.trackDetail();
 }

 trackDetail(){
let distance = 0;
 while(distance<5){
setTimeout(() => {this.setState({timePassed: true})}, 1000)
console.log("timer!");
distance = distance + 1;
}
}
##Output I received 
Test[43464:2994258] timer!
2019-04-19 09:55:06.807 [info][tid:com.facebook.react.JavaScript] timer!
2019-04-19 09:55:06.807263+0530 Test[43464:2994258] timer!

## Expected Behavior
1 min hold to print distance 

## Environment
$ react-native info
info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (2) x64 Intel(R) Pentium(R) CPU 2127U @ 1.90GHz
      Memory: 1.05 GB / 8 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.1 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: ^0.59.4 => 0.59.4 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1

**Comment by Karanp13** [comment]
> Can you run `react-native info` and edit your issue to include these results under the **Environment** section?
> 
> If you believe this information is irrelevant to the reported issue, you may write `[skip envinfo]` alongside an explanation in your Environment: section.

Details added in issue Environment.

**Comment by jeremy-deutsch** [comment]
It looks like there were some typos/errors in the code you posted. For example, the `let` in `let distance = 0` shouldn't work in a class declaration, and the `while (this.distance < 0.95)` loop currently runs forever, since you never change `distance`. Do you think you could fix those problems and then update this issue with your new results?

**Comment by Karanp13** [comment]
> ## 🐛 Bug Report
> I trying set timeout in constructor calling function.
> 
> ## To Reproduce and Code Example
> constructor(props) {
> super(props);
> const { navigate } = this.props.navigation;
> this.state = {
> country: '',
> timePassed:false,
> };
> //this.imagechange;
> this.trackDetail();
> }
> let distance = 0;
> trackDetail(){
> while(this.distance<0.95){
> setTimeout(() => {this.setState({timePassed: true})}, 1000)
> console.log('Updated distance is ' + distance);
> }
> }
> 
> ## Expected Behavior
> 1 min hold to print distance
> 
> ## Environment
> $ react-native info
> info
> React Native Environment Info:
> System:
> OS: macOS 10.14.4
> CPU: (2) x64 Intel(R) Pentium(R) CPU 2127U @ 1.90GHz
> Memory: 1.05 GB / 8 GB
> Shell: 3.2.57 - /bin/bash
> Binaries:
> Node: 10.14.1 - /usr/local/bin/node
> npm: 6.4.1 - /usr/local/bin/npm
> SDKs:
> iOS SDK:
> Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
> IDEs:
> Xcode: 10.2/10E125 - /usr/bin/xcodebuild
> npmPackages:
> react: 16.8.3 => 16.8.3
> react-native: ^0.59.4 => 0.59.4
> npmGlobalPackages:
> create-react-native-app: 2.0.2
> react-native-cli: 2.0.1



> It looks like there were some typos/errors in the code you posted. For example, the `let` in `let distance = 0` shouldn't work in a class declaration, and the `while (this.distance < 0.95)` loop currently runs forever, since you never change `distance`. Do you think you could fix those problems and then update this issue with your new results?

@jeremy-deutsch - I updated code and also received same one and I attached output log.

**Comment by jeremy-deutsch** [comment]
Sorry, but it looks like the code has the same error, since it only adds 1 to `distance` when the timeout callback function runs, but the callback never runs since the constructor runs forever. Try putting another print statement inside the `while` loop, but before the `setTimeout`?

**Comment by Karanp13** [comment]
> Sorry, but it looks like the code has the same error, since it only adds 1 to `distance` when the timeout callback function runs, but the callback never runs since the constructor runs forever. Try putting another print statement inside the `while` loop, but before the `setTimeout`?
>
Changed Details -
while(distance<5){
console.log("Timer Before!");
setTimeout(() => {this.setState({timePassed: true})}, 1000)
console.log("Timer After!");
distance = distance + 1;
}

Test[43888:3011390] Timer Before!
2019-04-19 11:02:40.093 [info][tid:com.facebook.react.JavaScript] Timer After!
2019-04-19 11:02:40.093541+0530 Test[43888:3011390] Timer After!
2019-04-19 11:02:40.094 [info][tid:com.facebook.react.JavaScript] Timer Before!
2019-04-19 11:02:40.093975+0530 Test[43888:3011390] Timer Before!
2019-04-19 11:02:40.097 [info][tid:com.facebook.react.JavaScript] Timer After!
2019-04-19 11:02:40.097320+0530 Test[43888:3011390] Timer After!
2019-04-19 11:02:40.098

**Comment by Karanp13** [comment]
@jeremy-deutsch Can you please tell me how I can resolve this issue?

**Comment by JKCooper2** [comment]
@Karanp13 does the issue exist in development mode or only in release mode? When you're debugging (particularly on a real device) there can be issues with computer/device times not being in sync.

Can you try with the timeout in the componentDidMount as well as see if that makes a difference, the constructor isn't really the right spot for that kind of functionality.

**Comment by Karanp13** [comment]
> @Karanp13 does the issue exist in development mode or only in release mode? When you're debugging (particularly on a real device) there can be issues with computer/device times not being in sync.
> 
> Can you try with the timeout in the componentDidMount as well as see if that makes a difference, the constructor isn't really the right spot for that kind of functionality.

Actually I tried in both. Output was same. I changed and make call from componentDidMount() and gives me same output. 

Same Output - 
Test[45218:3084881] Timer Before!
2019-04-19 15:45:55.591 [info][tid:com.facebook.react.JavaScript] Timer After!
2019-04-19 15:45:55.591815+0530 Test[45218:3084881] Timer After!
2019-04-19 15:45:55.593

**Comment by JKCooper2** [comment]
I'm guessing this is what you're going for...
https://snack.expo.io/@jkcooper/rn24500---constructor-settimeout.

Your while statement is off:
```
while(distance<5){
console.log("Timer Before!");
setTimeout(() => {this.setState({timePassed: true})}, 1000)
console.log("Timer After!");
distance = distance + 1;
}
```
It will just run 5 times straight away, call both the console logs each time and lining up a setTimeout (all 5 of which will be run after 1 second. (Run trackDetail2 function to see)

These types of questions are best asked on https://www.reactiflux.com/ as its not a react-native issue.

**Comment by Karanp13** [comment]
> I'm guessing this is what you're going for...
> https://snack.expo.io/@jkcooper/rn24500---constructor-settimeout.
> 
> Your while statement is off:
> 
> ```
> while(distance<5){
> console.log("Timer Before!");
> setTimeout(() => {this.setState({timePassed: true})}, 1000)
> console.log("Timer After!");
> distance = distance + 1;
> }
> ```
> It will just run 5 times straight away, call both the console logs each time and lining up a setTimeout (all 5 of which will be run after 1 second. (Run trackDetail2 function to see)
> 
> These types of questions are best asked on https://www.reactiflux.com/ as its not a react-native issue.

I think not due to while loop, I need multiple interval in each loop.

Test[45218:3084881] Timer Before!
2019-04-19 15:45:55.591 [info][tid:com.facebook.react.JavaScript] Timer After!
2019-04-19 15:45:55.591815+0530 Test[45218:3084881] Timer After!
2019-04-19 15:45:55.593

SetTimeOut consider any timezone?

**Comment by dulmandakh** [comment]
Closing the issue because it's not related to RN but your code. Thank you

**Comment by Karanp13** [comment]
> Closing the issue because it's not related to RN but your code. Thank you

@dulmandakh - Can you please share your solution when call set timeout on while using constructor? I need several interval while print/display.

**Comment by dulmandakh** [comment]
I think you should do it in componentDidMount rather than constructor.
