### ISSUE TITLE
Using focus throws "Illegal number of arguments for 'updateHotspot' command

### ISSUE THREAD

**Issue by canyavall** [facebook/react-native#24503]
## 🐛 Bug Report
We are working right now with Android TV. We have one small app to reproduce streamings and we wanted to create an error overlay in case the stream fails.
Creating the error overlay is working fine on mobile but on TV when the error appears it is not focusing the retry button so the user get stuck

## Expected Behavior
The component with the this.retry would be focused

## Code Example
```
export class StreamErrorOverlay extends React.Component {

    componentDidMount() {
        this.retry.focus();
    }

    render() {
        Logger.info("StreamErrorOverlayRender")

        const {t} = this.props
        const onPress = () => this.props.onPress && this.props.onPress()

        return (
            <View style={styles.overlay} accessibilityLabel="streamErrorOverlay">
                <View style={styles.boxMiddle}>

                    <Text style={styles.headerText}>
                        {t('mobile.Alert.Message.StreamUrlUnavailable')}
                    </Text>

                    <Text style={styles.text}>
                        {t('mobile.Alert.Description.StreamFailed')}
                    </Text>

                    <TouchableHighlight
                        accessibilityLabel="retryButton"
                        onPress={onPress}
                        style={styles.buttonStyle}
                        underlayColor={'#004faa'}
                        ref={(ref) => this.retry = ref}
                    >
                        <Text style={styles.buttonText}>
                            {t('shared.Retry')}
                        </Text>
                    </TouchableHighlight>
                </View>
            </View>
        )
    }
}
```
## Environment
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz
      Memory: 6.44 GB / 15.88 GB
    Binaries:
      Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5264788

**Comment by canyavall** [comment]
After some investigation, we could find out that the issue was not related to the focus, it was related to the keyhandle of the remote control

**Comment by EyMaddis** [comment]
@canyavall Can you be more specific on what caused the isse? I get the same exception.

**Comment by canyavall** [comment]
you can try
hasTVPreferredFocus={true}

**Comment by mrcatman** [comment]
That does not solve the problem if you need to focus on component manually, not on componentDidMount.
