### ISSUE TITLE
Unable to resolve modules from paths set in `tsconfig.json`

### ISSUE THREAD

**Issue by top-master** [facebook/react-native#24509]
## 🐛 Bug Report
The problem which I am facing is `Unable to resolve module '@app/main.view' from 'path/to/project/App.tsx': Module '@app/main.view' does not exist in the Haste module map ...`
## To Reproduce
1. I have created an empty `react-native` project but using type-script (like `react-native init --template typescript`)
2. then I added below to `tsconfig.json` file, which will make "@app" a shortcut to "./src/app" :
```json
{
  "compilerOptions": {
    ...
    "baseUrl": "./src",
    "paths": {
      "@app/*": ["app/*"]
    }
  },
}
```

## Expected Behavior
Exactly like the IDE (e.g. `VS Code`) the packager should handle the `compilerOptions` of `tsconfig.json` file

### `./App.tsx`
```ts
import React, {Component} from 'react';

import MainView from '@app/main.view';

interface Props {}
export default class App extends Component<Props> {
  render() {
    return (
      <MainView />
    );
  }
}
```
### `./src/app/main.view.tsx` file which is not found for some reason:
```ts

import React from "react";
import { View, Text } from "react-native";

export default class LoginView extends React.Component {
  render() {
    return (
      <View style={{ flex: 1, alignItems: "center", justifyContent: "center" }}>
        <Text>Home Screen</Text>
      </View>
    );
  }
}
```
## Environment
```
  React Native Environment Info:
    System:
      OS: Windows 7
      CPU: (4) x64 Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
      Memory: 1.02 GB / 7.70 GB
    Binaries:
      Yarn: 1.15.2 - C:\Users\Admin\AppData\Roaming\npm\yarn.CMD
      npm: 6.9.0 - C:\Users\Admin\AppData\Roaming\npm\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338
```
___
I think this does not count as a duplicate of #21804, since the typescript template should be ready to use by default, without need for any manual hacks.

I am happy with anything, but the #21804 issue, and how he did fix it in the end is really unclear to me, I mean, where is even the `rn-cli.config.js` file and how does changing it like below make the packager find the file:
```js
var path = require("path");
const metroBundler = require('metro-bundler');

var config = {
  extraNodeModules: {
    "react-native": path.resolve(__dirname, "node_modules/react-native"),
    "react": path.resolve(__dirname, "node_modules/react"),
  },
  getProjectRoots() {
    return [
      // Keep your project directory.
      path.resolve(__dirname),
      path.resolve(__dirname, "../native"), // path to the external module you want to import
    ];
  }
}
module.exports = config;
```

**Comment by top-master** [comment]
Just removed all build files, closed the packager and did run `react-native run-android` again;
sorry my mistake, the typescript template seems to work great ;-)

**Comment by juztinlazaro** [comment]
@top-master can i ask where i can see the build files? thanks
