### ISSUE TITLE
Migrating from 0.59.4 to 0.59.6, getting scheduler.development.js:107 Uncaught TypeError: callback is not a function

### ISSUE THREAD

**Issue by jacargentina** [facebook/react-native#24512]
## 🐛 Bug Report
Simple did as the caption says. Getting this.

<img width="656" alt="Captura de Pantalla 2019-04-18 a la(s) 11 05 24" src="https://user-images.githubusercontent.com/517228/56366653-006de180-61ca-11e9-8875-3583bf678a8e.png">

## To Reproduce
Upgrade app from 0.59.4 to 0.59.6

## Expected Behavior
Run without errors on console
## Environment
info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
      Memory: 517.48 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.14.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 26, 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.6 => 16.8.6 
      react-native: ^0.59.6 => 0.59.6 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-localize: 1.1.1

**Comment by IljaDaderko** [comment]
Same case for me `0.59.2` -> `0.59.6`

<img width="375" alt="Screenshot 2019-04-18 at 17 37 34" src="https://user-images.githubusercontent.com/3154053/56368714-accaba80-6200-11e9-8099-438210636ad3.png">

**Comment by minhtc** [comment]
upgrade react-native to 0.59.6 required "react": "16.8.6" ~ "scheduler": 0.13.6 caused this issue.

"callback" could be null here:
https://github.com/facebook/react/blob/487f4bf2ee7c86176637544c5473328f96ca0ba2/packages/scheduler/src/Scheduler.js#L97

**Comment by grabbou** [comment]
This is a bug that is caused by React sync script (we should investigate it later). I've already labelled `0.59.5` as `latest`. `0.59.6` is going to be removed. Apologies for the short inconvenience.

**Comment by grabbou** [comment]
CC: @TheSavior - do you want to keep this issue open to track the fix? Or close?

**Comment by IljaDaderko** [comment]
> upgrade react-native to 0.59.6 required "react": "16.8.6" ~ "scheduler": 0.13.6 caused this issue.
> 
> "callback" could be null here:
> https://github.com/facebook/react/blob/487f4bf2ee7c86176637544c5473328f96ca0ba2/packages/scheduler/src/Scheduler.js#L97

Unless rn 0.59.5 is resolving to a different version of react I am not sure its related. My project is on rn 0.59.5 and using react 16.8.6 without issues.

**Comment by grabbou** [comment]
Yes, it had a different React version. It's been unpublished in the
meantime.

**Comment by TheSavior** [comment]
Scheduler needs to be at 0.14.0. I don't see the scheduler in a package.json. Does anyone know where that is being set to 0.13.6?

**Comment by wouterds** [comment]
OMG. Why do I always find out after wasting hours it's _just a big in React Native itself_.

**Comment by wouterds** [comment]
@TheSavior It's a peer dependency, see `yarn.lock` or `package-lock.json`.

**Comment by TheSavior** [comment]
Looks like the published version of React 16.8.6 has a dependency of scheduler@^0.13.6: https://unpkg.com/react@16.8.6/package.json. That needs to be scheduler@^0.14.0. This has been updated on master but not published: https://github.com/facebook/react/blob/master/packages/react/package.json#L32

We probably need to get a new version of React published before the next cut of React Native.

**Comment by sunnylqm** [comment]
This also effects 0.60rc
