### ISSUE TITLE
How to fix the error Value for title cannot be cast from ReadableNativeMap to String

### ISSUE THREAD

**Issue by ashu777** [facebook/react-native#24522]
i am using:
 "axios": "^0.18.0",
    "native-base": "^2.12.1",
    "react": "16.8.3",
    "react-native": "0.59.5",
    "react-native-gesture-handler": "^1.1.0",
    "react-navigation": "^3.8.1"
 Android Studio 3.3.1
Build #AI-182.5107.16.33.5264788
JRE: 1.8.0_152-release-1248-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
i am new to react native app development and while running the app in android emulator i got the error "Value for title cannot be cast from ReadableNativeMap to String".
![Screenshot_1555654821](https://user-images.githubusercontent.com/39656382/56410083-78570d00-6299-11e9-8ef3-1ca6335653e5.png)
![Screenshot_1555654852](https://user-images.githubusercontent.com/39656382/56410086-7b51fd80-6299-11e9-85ae-eb63d2f73264.png)
![Screenshot_1555654858](https://user-images.githubusercontent.com/39656382/56410089-7ee58480-6299-11e9-877c-2deb7f03bb76.png)

**Comment by Rutheniceye92** [comment]
Did you find any solution?

**Comment by ashu777** [comment]
No, i just downgrade the react-native version and the error disappeared.

**Comment by berksafran** [comment]
I have same issue in RN 0.60. How can i fix it ?

**Comment by menarayanzshrestha** [comment]
Try by not using :

    Alert.alert(responseJson);

I solved my issue by this .

**Comment by lucaspiressimao** [comment]
> Try by not using :
> 
> ```
> Alert.alert(responseJson);
> ```
> 
> I solved my issue by this .

Same with me !! TKS
