### ISSUE TITLE
On android the app is reloaded when i disable one of the permissions 

### ISSUE THREAD

**Issue by invyctus92** [facebook/react-native#24526]
On android the app is reloaded when i disable one of the permissions 

If I have an app, made with React Native 0.59.4 and above, opened in the background, if I go into the app settings and disabled one of the active permissions such as gps or memory access, as soon as I reopen the app, it is reloaded. 

React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (4) x64 Intel(R) Core(TM) i5-3470S CPU @ 2.90GHz
      Memory: 135.41 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.15.0 - /usr/local/opt/node@8/bin/node
      npm: 6.4.1 - /usr/local/opt/node@8/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.5 => 0.59.5 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

**Comment by JKCooper2** [comment]
Does this happen in both development and release mode?

**Comment by invyctus92** [comment]
With 0.59.4 it doesn't work in debug version, with 0.53 the version of my project doesn't work in debug and release version. With 0.59.4 I have to try if it doesn't work in release version.
