### ISSUE TITLE
Can't connect to remote debugger from physical iOS device

### ISSUE THREAD

**Issue by EgidioCaprino** [facebook/react-native#24524]
## 🐛 Bug Report
When enabling the remote debugger on the application, a Chrome tab opens to `localhost:8081/debugger-ui` but it fails with a CORS error.

![image](https://user-images.githubusercontent.com/5156120/56417793-53609b00-6295-11e9-9e30-23438c68daff.png)

## To Reproduce
- `npm start -- --reset-cache`
- `react-native run-ios --device`
- Shake the device
- Tap `Debug JS Remotely`

## Expected Behavior
It should just work 🙂

## Code Example
_None_

## Environment
```
info
  React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 209.06 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.14.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 27, 28
        Build Tools: 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.6 => 16.8.6
      react-native: ^0.59.4 => 0.59.4
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

**Comment by JKCooper2** [comment]
Potentially it's trying to connect using the wrong IP address. Can you do:

Open the in-app Developer menu.
Go to Dev Settings → Debug server host & port for device.
Type in your machine's IP address and the port of the local dev server (e.g. 10.0.1.1:8081).
Go back to the Developer menu and select Reload JS

Try both localhost:8081 and your dev machine local ip:8081

**Comment by Aoqin** [comment]
On iOS devices, open the file RCTWebSocketExecutor.m and change "localhost" to the IP address of your computer, then select "Debug JS Remotely" from the Developer Menu.
i find this in https://facebook.github.io/react-native/docs/debugging，but  not solved

**Comment by gorvinsky** [comment]
I'm also having this issue with React Native version 0.59.5 on Mac and iPhone. Is there a proper solution already?

**Comment by gabrielperales** [comment]
I think this is duplicated and is related to this issue https://github.com/facebook/react-native/issues/24002

**Comment by code-matt** [comment]
Installing a Chrome extension that allows CORS works in the meantime. This showed up in 59 it seems
