### ISSUE TITLE
RCT_EXPORT_METHOD and UIView methods

### ISSUE THREAD

**Issue by bnookala** [facebook/react-native#2453]
I'm working on an app that's primarily objective-c based, but I've been adding RN views for some (simpler) things while using React Native 0.8.0. I noticed an issue today that seems to only occur in exported methods that work on the main thread: I can't seem to make UIView methods respond properly.

I have a RN view that's within the view hierarchy. It has a TouchableOpacity view with an onPress that calls an exported method like so:

```
    onPress: function () {
        React.NativeModules.MyModule.dismissMyView();
    },
```

the exported method is simple:

```
RCT_EXPORT_METHOD(dismissMyView){
    self.myReactNativeView.hidden = YES;
}
```

The module exported by `RCT_EXPORT_MODULE` implements `- (dispatch_queue_t)methodQueue` to return the main queue. 

I've confirmed that the method exported by `RCT_EXPORT_METHOD` is actually called by dropping a breakpoint and playing around in lldb, but the view being hidden doesn't appear to actually be hidden. After the function returns, the view still appears to be shown. I've also confirmed that it isn't just the `hidden`property by playing around with opacity, and some other UIView functions.

The funky part: there are some (objective-c) controls within the application that I've added breakpoints to in their delegate functions. Running `po self.myReactNativeView.hidden = YES` in lldb at these points does appear to hide the react view properly. 

Anybody know what's up here?

**Comment by dsibiski** [comment]
You'll probably need to include a little more of an example. Would it be possible to push a repo of the scenario that we'd be able to run?

**Comment by bnookala** [comment]
@dsibiski Thanks for looking into this! I created a simple demo of the behavior here: https://github.com/bnookala/ReactNativeExportMethod

After running `pod install`, you should be run the demo and see the behavior I'm describing above. The files that are relevant here are `ViewController.m` (which has the exported method) and `ReactComponents/ReactView/view.js`, which contains the react native view.

**Comment by bnookala** [comment]
I tried the project with 0.10.0 - no dice. This is what it appears to look like: 

![react-native](https://cloud.githubusercontent.com/assets/87996/9530137/e06ed8ce-4cb2-11e5-950b-85b8f8da8b0e.gif)

Trying the 0.11.0 rc next!

**Comment by dsibiski** [comment]
@bnookala I'm pretty sure it has to do with your setup here.

If you log out `self.description` for each button method, you find that it is 2 different instances.

![log_output](https://i.imgur.com/JR5Dwh9.png)

The problem is that you are creating your RCTRootView (MyReactView) from inside the Bridge Module...React Native will create a new instance of `ViewController` when it loads the JavaScript because it is a bridge module...

If you create your RCTRootView outside of this bridge module, I think you should be fine.

**Comment by dsibiski** [comment]
See my PR here for a possible solution: https://github.com/bnookala/ReactNativeExportMethod/pull/1

**Comment by bnookala** [comment]
@dsibiski Very curious! I didn't realize the RCT_EXPORT_MODULE macro would automatically instantiate an instance of the bridge. This does seem to work as expected, and I've got ideas on how to incorporate this into our project; thanks so much!

**Comment by dsibiski** [comment]
@bnookala No problem man! I'm always very interested in how others use RN in hybrid apps (as I also have a large hybrid app). I like your approach to creating the rootView, very cool. Please let me know how everything works out and what you settle on. :+1:

**Comment by mndewitt** [comment]
I found this pattern very helpful in bridging my existing class - here's an update of the pattern for more recent versions of React Native (0.36 in my case).  The RCTBridge class has been updated, so you'd need to change:

```objective-c
 _reactView = [[ReactView alloc] initWithFrame:CGRectMake(0, 10, 320, 480)];
[(ReactViewCloser *)_reactView.rootView.bridge.modules[@"MyModule"] setViewController:self];
```
To:

```objective-c
 _reactView = [[ReactView alloc] initWithFrame:CGRectMake(0, 10, 320, 480)];
ReactViewCloser = [_reactView.rootView.bridge moduleForName:@"MyModule"];
[bridge setViewController:self];
```

...You'd just have to use the `moduleForName` method instead of `bridge.modules`.
