### ISSUE TITLE
Unable to upgrade from 0.59.4 to 0.59.5 [error Failed to fetch diff for react-native@0.59.5. Maybe it's not released yet?]

### ISSUE THREAD

**Issue by saifali96** [facebook/react-native#24534]
## 🐛 Bug Report
Unable to upgrade from 0.59.4 to 0.59.5 [error Failed to fetch diff for react-native@0.59.5. Maybe it's not released yet?]

```
PS > react-native upgrade
info No version passed. Fetching latest...
info Fetching diff between v0.59.4 and v0.59.5...
error Failed to fetch diff for react-native@0.59.5. Maybe it's not released yet?
info For available releases to diff see: https://github.com/react-native-community/rn-diff-purge#version-changes
```

## To Reproduce
`react-native upgrade`
OR 
`react-native upgrade react-native@0.59.5`

## Expected Behavior
Upgrade to to `0.59.5` or `latest`

## Code Example
`react-native upgrade`
OR 
`react-native upgrade react-native@0.59.5`

## Environment
```info
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
      Memory: 6.27 GB / 15.93 GB
    Binaries:
      Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.7.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.5429.30.34.5452501
```

**Comment by JKCooper2** [comment]
This issue is probably better raised in https://github.com/react-native-community/cli

Issues like https://github.com/react-native-community/cli/issues/189 may be relevant to what you're looking for

**Comment by Frekansapp** [comment]
I have same problem too

**Comment by wbercx** [comment]
While the command does fail, I just want to point out it is easy to [upgrade this particular version manually](https://github.com/react-native-community/rn-diff-purge/compare/release/0.59.4..release/0.59.5).

**Comment by saifali96** [comment]
@wbercx thanks for the workaround. Manually updating from `package.json` is not recommended, but the last resort.
I would like to close this ticket down but would like the maintainers to explain what's causing the error. The error itself explains nothing.

**Comment by dulmandakh** [comment]
It should be ok by now, so closing this issue. Please comment if it's still not working.

**Comment by saifali96** [comment]
@dulmandakh yes it works but only with the above workaround // changing the `package.json` file - the `react-native upgrade` command failed.

Tested a moment ago.

**Comment by theharness** [comment]
Running `react-native upgrade` command without any modifications does not work for me as of a couple seconds ago.

**Comment by jvandenaardweg** [comment]
Indeed, does not work

```
react-native upgrade 0.59.5
info Fetching diff between v0.59.2 and v0.59.5...
error Failed to fetch diff for react-native@0.59.5. Maybe it's not released yet?
info For available releases to diff see: https://github.com/react-native-community/rn-diff-purge#version-changes
```

**Comment by saifali96** [comment]
@dulmandakh could this be the issue causing this unexpected behavior?
![image](https://user-images.githubusercontent.com/6160857/56608011-2223fa00-660a-11e9-85af-9b00d0e9ef32.png)

Hint: The release tag is `0.59.5` but the version in the commit message is `0.59.6`.

Sound crazy that a commit message can trigger this but maybe the code also reflects this?

**Comment by RenatoMartinsFerreira** [comment]
I had the same issue and solved it deleting `node_modules` path and `package-lock.json` file, than updating react-native in the `package.json` from "react-native": "0.59.4" to "react-native": "0.59.5", to apply changes `npm install`, I believe that isn't the bast way to go, but worked form me, remember to test if all dependencies stay working.

**Comment by dulmandakh** [comment]
Please use 0.59.9. Thank you

**Comment by MAsoomehmierfany1972** [comment]
Masoomeh.Daneshvar.

**Comment by josemigallas** [comment]
I've encountered this issue now, it happens with `0.59.9` and `0.60.0-rc3`. However works when first upgrading to `0.59.8` and then to `0.59.9`.
