### ISSUE TITLE
Question: bundling failed: Error: The resource `index.js` was not found

### ISSUE THREAD

**Issue by codeshaker** [facebook/react-native#24532]
Hi I am new to React-Native. I tried to create project using commands in sequences

    expo-cli (to start project)
    npm start
    npm run eject (to create android and ios folder)
    npm run android (to run app natively)

However not at any stage of development i got to see file "RootDirectory/Index.js" and "index.android.js" or "index.ios.js" ??

I have seen other issue but mostly people have worked around these file which i never saw on my repo.

Folder Structure
![image](https://user-images.githubusercontent.com/10116398/56437193-1976af80-62fc-11e9-98a5-2dd4b533acfe.png)

**Comment by DataGreed** [comment]
@codeshaker did you manage to solve it?
