### ISSUE TITLE
Issue encounter on only OnePlus6t Device

### ISSUE THREAD

**Issue by URvesh109** [facebook/react-native#24544]
I have one application on PLAY and APP store. It is working fine on most of the device, but it's UI and other functionality is breaking on OnePlus6t Device only. So I started debugging and found this issue

This line won't works on OnePlus6t Device, when you use fontWeight
<Text style={{fontSize: 20, color: 'red', fontWeight: 'bold'}}>From Home</Text>
**Note**: Closing Tag is not appearing, although I have added

This line will works on OnePlus6t, when you use fontWeight with space around the text '**From Home'**
<Text style={{fontSize: 20, color: 'red', fontWeight: 'bold'}}> From Home </Text>
**Note**: Closing Tag is not appearing, although I have added

I have used inline, StyleSheet and ExtendedStyleSheet styles, but space around the text only works. Other issue are also there with OnePlus6T device only.

For more details kindly see ScreenShot

React Native Info

info 
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
      Memory: 346.11 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.3, 26.0.1, 26.0.3, 27.0.3, 28.0.1, 28.0.2, 28.0.3
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.4 => 0.59.4 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
![Screen Shot 2019-04-20 at 21 20 19](https://user-images.githubusercontent.com/26654227/56459498-2b1a8e80-63b2-11e9-8228-e5348697d88b.png)

![NotWorking](https://user-images.githubusercontent.com/26654227/56459338-adee1a00-63af-11e9-9e11-a4f6d751d100.jpg)
![Working](https://user-images.githubusercontent.com/26654227/56459339-adee1a00-63af-11e9-8934-dabfc643e572.jpg)
![Expected](https://user-images.githubusercontent.com/26654227/56459347-c100ea00-63af-11e9-8b57-fee59fecb798.png)
![OnePlus6T](https://user-images.githubusercontent.com/26654227/56459348-c65e3480-63af-11e9-93a3-ba3f9949b35f.png)

**Comment by Kida007** [comment]
Duplicate of https://github.com/facebook/react-native/issues/15114

Possible Solution: 
1) Appending Space ( as you said )
2) Mentioning a fontFamily.

**Comment by URvesh109** [comment]
Thanks for feedback, just thought to inform but there are other issue also
