### ISSUE TITLE
runAfterInteractions() is not fired on react native 0.59.4

### ISSUE THREAD

**Issue by AlexandreMaistret** [facebook/react-native#24563]
## 🐛 Bug Report
Since an update of react native (0.55.4 to 0.59.4) and all the packages, the function InteractionManager.runAfterInteractions() is not fired anymore.

Moreover, the getItemLayout() which seems using InteractionManager.runAfterInteractions() 
[#15734](https://github.com/facebook/react-native/issues/15734) doesn't work properly and only render initialNumToRender() of items.

Before this update, everything was working fine.

## Expected Behavior

I am expecting that all my InteractionManager.runAfterInteractions() functions are fired and getItemLayout works.

## Code Example

```
renderItem = ({ item }) => {
   return (
     <Item
       item={item}
     />
   );
 }

 renderSeparator = () => {
   return (<ListSeparator />);
 }

 getItemLayout = (data, index) => {
   return { length: ListItemHeight + 1, offset: (ListItemHeight + 1) * index, index };
 }

 keyExtractor = (item) => {
   return item.id;
 }

render() {
  return (
     <View style={styles.ContainerStyle}>
       <FlatList
         data={this.state.phone_number_prefixes}
         renderItem={this.renderItem}
         ItemSeparatorComponent={this.renderSeparator}
         getItemLayout={this.getItemLayout}
         ListHeaderComponent={this.renderHeader}
         keyExtractor={this.keyExtractor}
         removeClippedSubviews
         initialNumToRender={20}
         keyboardShouldPersistTaps='always'
       />
     </View>
  );
}
```

## Environment

react-native -v: 0.59.4
node -v: v10.8.0
npm -v: 6.9.0
yarn: 1.2.1
OS: Android
Device: REAL
Android Studio: 3.1.0.0

**Comment by dulmandakh** [comment]
couldn't find InteractionManager.runAfterInteractions() use in your code

**Comment by AlexandreMaistret** [comment]
Ok I found the bug, I had a new animation on a previous screen which was continuing to be animated, and so InteractionManager.runAfterInteractions() was able to run because of this animation.

So now I have a bug on why this screen doesn't unmount, but that's a react-navigation bug.
