### ISSUE TITLE
[0.59.4][ANDROID] Signed release do not show local assets images

### ISSUE THREAD

**Issue by hariegnify** [facebook/react-native#24565]
## 🐛 Bug Report
Local images are not showing in release mode they are working fine in dev mode.

## To Reproduce
react-native run-android --variant=release

## Environment
React Native Environment Info:
System:
OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
CPU: (4) x64 Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
Memory: 1.34 GB / 15.37 GB
Shell: 5.4.2 - /bin/zsh
Binaries:
Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
Yarn: 1.7.0 - /usr/bin/yarn
npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
SDKs:
Android SDK:
API Levels: 23, 25, 26, 27, 28
Build Tools: 26.0.2, 26.0.3, 27.0.3, 28.0.3
System Images: android-28 | Google APIs Intel x86 Atom
npmPackages:
react: 16.8.3 => 16.8.3
react-native: 0.59.4 => 0.59.4

**Comment by romreed** [comment]
i have same issue!

**Comment by HarshitMadhav** [comment]
did you update the react native bundle?

**Comment by hariegnify** [comment]
react-native bundle command hangs at loading dependency graph so I couldn't update that.

I tried to fetch the latest bundle through this following command
curl "http://localhost:8081/index.android.bundle?platform=android" -o "android/app/src/main/assets/index.android.bundle"

**Comment by HarshitMadhav** [comment]
let it stay at loading dependency graph for minutes (have patience it will complete)

**Comment by hariegnify** [comment]
I have waited for around 7-8 hours but no response even after that.

**Comment by hariegnify** [comment]
Done nothing, now it's working fine. Bundling is done in just 30 sec.
