### ISSUE TITLE
undefined is not a function (evaluating 'Uint8Array.from(this._hash)')

### ISSUE THREAD

**Issue by yangjun** [facebook/react-native#24568]
## 🐛 Bug Report

```
04-23 15:01:42.781 17632 17720 E AndroidRuntime: com.facebook.react.common.JavascriptException: undefined is not a function (evaluating 'Uint8Array.from(this._hash)'), stack:
04-23 15:01:42.781 17632 17720 E AndroidRuntime: bytes@695:666
04-23 15:01:42.781 17632 17720 E AndroidRuntime: encodeDestinationSetupFrame@702:862
04-23 15:01:42.781 17632 17720 E AndroidRuntime: encodeFrame@699:276
04-23 15:01:42.781 17632 17720 E AndroidRuntime: create@629:4198
04-23 15:01:42.781 17632 17720 E AndroidRuntime: <unknown>@627:123
04-23 15:01:42.781 17632 17720 E AndroidRuntime: _@2:1514
04-23 15:01:42.781 17632 17720 E AndroidRuntime: d@2:967
04-23 15:01:42.781 17632 17720 E AndroidRuntime: o@2:435
04-23 15:01:42.781 17632 17720 E AndroidRuntime: <unknown>@623:550
04-23 15:01:42.781 17632 17720 E AndroidRuntime: _@2:1514
04-23 15:01:42.781 17632 17720 E AndroidRuntime: d@2:967
04-23 15:01:42.781 17632 17720 E AndroidRuntime: o@2:435
04-23 15:01:42.781 17632 17720 E AndroidRuntime: <unknown>@359:293
04-23 15:01:42.781 17632 17720 E AndroidRuntime: _@2:1514
04-23 15:01:42.781 17632 17720 E AndroidRuntime: d@2:967
04-23 15:01:42.781 17632 17720 E AndroidRuntime: o@2:435
04-23 15:01:42.781 17632 17720 E AndroidRuntime: <unknown>@11:78
04-23 15:01:42.781 17632 17720 E AndroidRuntime: _@2:1514
04-23 15:01:42.781 17632 17720 E AndroidRuntime: d@2:897
04-23 15:01:42.781 17632 17720 E AndroidRuntime: o@2:435
04-23 15:01:42.781 17632 17720 E AndroidRuntime: global code@1270:4
04-23 15:01:42.781 17632 17720 E AndroidRuntime:
04-23 15:01:42.781 17632 17720 E AndroidRuntime:        at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:54)
04-23 15:01:42.781 17632 17720 E AndroidRuntime:        at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:38)
04-23 15:01:42.781 17632 17720 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-23 15:01:42.781 17632 17720 E AndroidRuntime:        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
04-23 15:01:42.781 17632 17720 E AndroidRuntime:        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
04-23 15:01:42.781 17632 17720 E AndroidRuntime:        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
04-23 15:01:42.781 17632 17720 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:891)
04-23 15:01:42.781 17632 17720 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
04-23 15:01:42.781 17632 17720 E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
04-23 15:01:42.781 17632 17720 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:207)
04-23 15:01:42.781 17632 17720 E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
04-23 15:01:42.781 17632 17720 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:784)

```

## Environment

React Native 0.58

**Comment by JonBerglund** [comment]
Hello, I have the same problem for some reason Uint8Array dont have the function from (undefined).

Bug report:

TypeError: TypeError: TypeError: undefined is not a function (evaluating 'Uint8Array.from((0, _base.decode)(validFor), function (c) {
          return c.charCodeAt(0);
        })')

This error is located at:
    in List (at ProductsTabScreen.js:26)
    in RCTView (at View.js:43)
    in ProductsTabScreen (created by Connect(ProductsTabScreen))
    in Connect(ProductsTabScreen) (at SceneView.js:9)
    in SceneView (at createTabNavigator.js:39)
    in RCTView (at View.js:43)
    in RCTView (at View.js:43)
    in ResourceSavingScene (at createBottomTabNavigator.js:108)
    in RCTView (at View.js:43)
    in ScreenContainer (at createBottomTabNavigator.js:98)
    in RCTView (at View.js:43)
    in TabNavigationView (at createTabNavigator.js:178)
    in NavigationView (at createNavigator.js:57)
    in Navigator (at createNavigationContainer.js:376)
    in NavigationContainer (at SceneView.js:9)
    in SceneView (at StackViewLayout.js:478)
    in RCTView (at View.js:43)
    in RCTView (at View.js:43)
    in RCTView (at View.js:43)
    in AnimatedComponent (at screens.native.js:59)
    in Screen (at StackViewCard.js:42)
    in Card (at createPointerEventsContainer.js:26)
    in Container (at StackViewLayout.js:507)
    in RCTView (at View.js:43)
    in ScreenContainer (at StackViewLayout.js:401)
    in RCTView (at View.js:43)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.js:49)
    in RCTView (at View.js:43)
    in Transitioner (at StackView.js:19)
    in StackView (at createNavigator.js:57)
    in Navigator (at createKeyboardAwareNavigator.js:11)
    in KeyboardAwareNavigator (at createNavigationContainer.js:376)
    in NavigationContainer (at AuthNavigation.js:93)
    in Unknown (created by Connect(Component))
    in Connect(Component) (at app.js:60)
    in RCTView (at View.js:43)
    in PersistGate (at app.js:56)
    in Provider (at app.js:55)
    in App (at renderApplication.js:32)
    in RCTView (at View.js:43)
    in RCTView (at View.js:43)
    in AppContainer (at renderApplication.js:31)

This error is located at:
    in NavigationContainer (at SceneView.js:9)
    in SceneView (at StackViewLayout.js:478)
    in RCTView (at View.js:43)
    in RCTView (at View.js:43)
    in RCTView (at View.js:43)
    in AnimatedComponent (at screens.native.js:59)
    in Screen (at StackViewCard.js:42)
    in Card (at createPointerEventsContainer.js:26)
    in Container (at StackViewLayout.js:507)
    in RCTView (at View.js:43)
    in ScreenContainer (at StackViewLayout.js:401)
    in RCTView (at View.js:43)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.js:49)
    in RCTView (at View.js:43)
    in Transitioner (at StackView.js:19)
    in StackView (at createNavigator.js:57)
    in Navigator (at createKeyboardAwareNavigator.js:11)
    in KeyboardAwareNavigator (at createNavigationContainer.js:376)
    in NavigationContainer (at AuthNavigation.js:93)
    in Unknown (created by Connect(Component))
    in Connect(Component) (at app.js:60)
    in RCTView (at View.js:43)
    in PersistGate (at app.js:56)
    in Provider (at app.js:55)
    in App (at renderApplication.js:32)
    in RCTView (at View.js:43)
    in RCTView (at View.js:43)
    in AppContainer (at renderApplication.js:31)

This error is located at:
    in NavigationContainer (at AuthNavigation.js:93)
    in Unknown (created by Connect(Component))
    in Connect(Component) (at app.js:60)
    in RCTView (at View.js:43)
    in PersistGate (at app.js:56)
    in Provider (at app.js:55)
    in App (at renderApplication.js:32)
    in RCTView (at View.js:43)
    in RCTView (at View.js:43)
    in AppContainer (at renderApplication.js:31)
<unknown>
    ProductList.js:72:59
map
    [native code]
List
    ProductList.js:72:20
List
    [native code]
<unknown>
    createClassProxy.js:98:23
instantiate
    createClassProxy.js:96:6
constructClassInstance
    ReactNativeRenderer-dev.js:7577:26
updateClassComponent
    ReactNativeRenderer-dev.js:9868:8
beginWork
    ReactNativeRenderer-dev.js:10727:8
performUnitOfWork
    ReactNativeRenderer-dev.js:13126:21
workLoop
    ReactNativeRenderer-dev.js:13165:41
renderRoot
    ReactNativeRenderer-dev.js:13218:15
performWorkOnRoot
    ReactNativeRenderer-dev.js:13941:17
performWork
    ReactNativeRenderer-dev.js:13854:24
performSyncWork
    ReactNativeRenderer-dev.js:13814:14
batchedUpdates$1
    ReactNativeRenderer-dev.js:14045:6
batchedUpdates
    ReactNativeRenderer-dev.js:2525:27
_receiveRootNodeIDEvent
    ReactNativeRenderer-dev.js:2619:17
receiveTouches
    ReactNativeRenderer-dev.js:2695:28
__callFunction
    MessageQueue.js:344:47
<unknown>
    MessageQueue.js:107:26
__guard
    MessageQueue.js:291:8
callFunctionReturnFlushedQueue
    MessageQueue.js:106:17
callFunctionReturnFlushedQueue
    [native code]



  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
      Memory: 56.76 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.13.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 21, 22, 23, 24, 25, 26, 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-27 | Android TV Intel x86 Atom, android-27 | Intel x86 Atom, android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.1 => 0.56.1 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
