### ISSUE TITLE
Loading dependency graph...jest-haste-map: Watchman crawl failed.

### ISSUE THREAD

**Issue by hariegnify** [facebook/react-native#24569]
## 🐛 Bug Report
Loading dependency graph...jest-haste-map: Watchman crawl failed. Retrying once with node crawler.
  Usually this happens when watchman isn't running. Create an empty `.watchmanconfig` file in your project's root folder or initialize a git or hg repository in your project.
  Error: Watchman error: unable to resolve root /: cannot watch "/". Make sure watchman is running for this project. See https://facebook.github.io/watchman/docs/troubleshooting.html.

## To Reproduce

react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/

## Environment
React Native Environment Info:
System:
OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
CPU: (4) x64 Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
Memory: 1.34 GB / 15.37 GB
Shell: 5.4.2 - /bin/zsh
Binaries:
Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
Yarn: 1.7.0 - /usr/bin/yarn
npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
SDKs:
Android SDK:
API Levels: 23, 25, 26, 27, 28
Build Tools: 26.0.2, 26.0.3, 27.0.3, 28.0.3
System Images: android-28 | Google APIs Intel x86 Atom
npmPackages:
react: 16.8.3 => 16.8.3
react-native: 0.59.4 => 0.59.4

**Comment by thymikee** [comment]
There's 30 similar issues to this one, please use search: https://github.com/facebook/react-native/issues?q=is%3Aissue+sort%3Aupdated-desc+Watchman+crawl+failed+is%3Aclosed
