### ISSUE TITLE
[Text] How to change the textContent of a TextView with setNativeProps?

### ISSUE THREAD

**Issue by ms88privat** [facebook/react-native#2457]
Is this even possible? 

I need to realise a CounterView wich updates every 1 millisecond. 

I could style the TextInputView accordingly and prevent user input and do it that way, but even there i noticed a delay. 

I tried to update nativeProps within an interval of 1, 10 and 100ms. Only when i make the interval to 1000ms i think it updates the Counter correct to one real second, all other values are much too slow (15 sec  = 22 +-2 real sec). The same is true for the standard setState() version which surprised me.

Any idea how to do it in react native? I think the setInterval function is the culprit? Any alternatives?

thank you guys.

**Comment by ide** [comment]
Use `<TextInput value={count} />` instead of `setNativeProps`. Also you can't render faster than 16ms on most devices anyway.

**Comment by ms88privat** [comment]
@ide I'm not sure what are you telling me. If i don't have to use setNativeProps, why i should still use TextInput over a normal TextView?

**Comment by ide** [comment]
I'm confused... Do you mean the TextInput component which creates UITextViews or the Text component?

**Comment by ms88privat** [comment]
@ide Sorry, I don't get it. 

I need to know the fastest possible way to update a text/number on the screen. 

So i read about setNativeProps for the <TextInput /> component. But I did not need the user-input, so i thought about setting nativeProps on a <Text></Text> component, which is not working. 

But anyways, setting nativeProps on <TextInput /> archived the same performance as a <TextInput> or <Text> with setState, which surprised me.

**Comment by brentvatne** [comment]
I don't believe this is possible at the moment because the text content actually belongs to an underlying RCTRawText node.

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/text-how-to-change-the-textcontent-of-a-textview-with-setnativeprops

**Comment by grundmanise** [comment]
Same here. Currently need to use [this 'hack'](http://stackoverflow.com/a/38401121/4541800) to change text with `setNativeProps`. Any plans or thoughts on implementing `text` prop for the `Text` component? Is it even possible?
