### ISSUE TITLE
react-native link and react-native info commands unrecognized after installing @react-native-community/netinfo

### ISSUE THREAD

**Issue by ThinkSalat** [facebook/react-native#24575]
## 🐛 Bug Report
After installing @React-native-community/netinfo, react-native link doesn't work anymore

## To Reproduce
Upgrade from 0.57.5 => 0.59.0
Get warning about netinfo moving to react-native-community
Install react-native-community/netinfo
run `react-native link`

Get: "Command `link` unrecognized. Make sure that you have run `npm install` and that you are inside a react-native project."

## Expected Behavior
Library is linked 

## Code Example

Too complicated for that

## Environment
[skip evinfo]
react-native info is also giving me the command not recognized error
"@react-native-community/netinfo": "^2.0.4",
    "prop-types": "^15.6.2",
    "react": "^16.6.3",
    "react-addons-shallow-compare": "^15.6.2",
    "react-moment": "^0.7.9",
    "react-native": "^0.59.5",
    "react-native-android-open-settings": "^1.2.0",
    "react-native-banner-carousel": "^1.0.3",
    "react-native-checkbox": "^2.0.0",
    "react-native-circular-progress": "^1.1.0",
    "react-native-device-info": "^0.13.0",
    "react-native-elements": "^0.19.1",
    "react-native-exception-handler": "^2.8.9",
    "react-native-image-picker": "^0.26.4",
    "react-native-immediate-phone-call": "^1.0.0",
    "react-native-keyboard-aware-scroll-view": "^0.3.0",
    "react-native-linear-gradient": "^2.4.0",
    "react-native-mail": "^3.0.6",
    "react-native-mixpanel": "^1.1.1",
    "react-native-modal-dropdown": "^0.6.2",
    "react-native-popup-dialog": "^0.10.46",
    "react-native-push-notification": "^3.1.1",
    "react-native-restart": "0.0.4",
    "react-native-search-box": "0.0.18",
    "react-native-sensitive-info": "github:mCodex/react-native-sensitive-info#keystore",
    "react-native-sms-linking": "^1.0.2",
    "react-native-svg": "^9.3.3",
    "react-native-svg-icon": "^0.8.0",
    "react-native-swipeout": "^2.3.3",
    "react-native-swiper": "^1.5.13",
    "react-native-vector-icons": "^4.6.0",
    "react-navigation": "^1.0.0-beta.27",
    "react-redux": "^5.0.7",
    "redux": "^3.6.0",
    "redux-persist": "5.4.0",
    "redux-persist-sensitive-storage": "^1.0.0",
    "redux-persist-transform-encrypt": "^2.0.1",
    "redux-saga": "^0.14.7",

**Comment by travega** [comment]
I have the same issue. Was there any solution found for this?
