### ISSUE TITLE
textAlign right and left are reverse for android O+ (api level >=26)

### ISSUE THREAD

**Issue by AE0011** [facebook/react-native#24584]
## 🐛 Bug Report

Attribute textAlign works reverse for android O+ for rtl languages in react native 0.59.5, if it set 'right' text  would go to left side! however in IOS and lower android device it works properly.

## To Reproduce
```
1- <Text style={{width: '100%', textAlign: 'right'}}>{'سلام'}</Text>
2- <Text style={{width: '100%', textAlign: 'left'}}>{'سلام'}</Text>
```

## Expected Behavior

 Text 1 should be on right side of screen but it goes to left side 
 Text 2 should be on left side but it goes to right side

 

## Environment

```
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 8
        Build Tools: 23.0.1, 23.0.2, 23.0.3, 24.0.0, 24.0.1, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.3, 28.0.3
...
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.5 => 0.59.5 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

**Comment by MujtabaFR** [comment]
I had the same issue [asked here](https://stackoverflow.com/questions/55833602/textalign-working-differently-after-upgrade-to-rn-0-59-3)
I guess it's related to [this change](https://github.com/facebook/react-native/commit/871290f)

**Comment by thymikee** [comment]
Thanks @MujtabaFR. This commit was recently reverted: https://github.com/facebook/react-native/commit/8d3e16831a93079fc5a855a7b0f8b4be508c6942

@grabbou are there plans to include it in 0.59 branch?

**Comment by qasimalbaqali** [comment]
Facing this issue as well. Hope something is done soon regarding it.

**Comment by idanlo** [comment]
I am still facing this issue with react-native version `0.60.3`

**Comment by idanlo** [comment]
Not stale

**Comment by idanlo** [comment]
.
