### ISSUE TITLE
Discussion: React-Native iOS language

### ISSUE THREAD

**Issue by carlosroberto555** [facebook/react-native#24588]
Why React-Native for iOS use Objective-C on AppDelegate?

**Comment by thymikee** [comment]
Swift wasn't that popular at the time React Native was built, so I guess that's the main reason.

Anyway, there's a special repository for discussions and proposals like this: https://github.com/react-native-community/discussions-and-proposals/issues/

Please open an issue there if you feel like this should change or you are just curious :)
