### ISSUE TITLE
Upgrade to 0.9 causes EMFILE errors

### ISSUE THREAD

**Issue by jaulz** [facebook/react-native#2458]
Hi there,

since the upgrade to 0.9 I get the following error as soon as the application starts in the simulator:
```
React packager ready.

[08:01:24] <START> fs crawl
[08:01:29] <END>   fs crawl (4732ms)
Error: EMFILE: too many open files, open '/Users/Julian/Documents/dev/aroundable-app/node_modules/react-native/Libraries/Utilities/deepFreezeAndThrowOnMutationInDev.js'
    at Error (native)
```

Though I checked the `ulimit -n` (which is at 10000) and also updated `/etc/launchd.conf`accordingly it does not work as expected. Is this a problem of watchman or react itself? Unfortunately I couldn't find anything else to solve the issue.

Thanks!

**Comment by ide** [comment]
Try installing watchman. I believe you are using the node file watcher which doesn't scale.

**Comment by brentvatne** [comment]
@ide's advice as usual is :+1: :100:
