### ISSUE TITLE
React-Native application behind proxy

### ISSUE THREAD

**Issue by andreaCremisini** [facebook/react-native#24582]
## 🐛 Bug Report

![Simulator Screen Shot - iPhone X - 2019-04-24 at 10 49 08](https://user-images.githubusercontent.com/5129147/56649122-d4000c80-6684-11e9-8065-7d15e7fb5385.png)

## To Reproduce
I'm developing an application with React-Native, but I have a problem with the proxy: I set Node with "npm config proxy / https-proxy ..." and I can install the application without problems, but when Metro Bundler starts for debugging and downloading dependencies, I have this "No Bundle URL present" screen (when I work in tethering this thing does not happen and everything works correctly). How do I solve it? What should I set?

## Environment
  React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 204.08 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.9.4 - /usr/local/bin/node
      Yarn: 1.15.2 - ~/.npm-global/bin/yarn
      npm: 6.4.1 - ~/.npm-global/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 26, 28
        Build Tools: 26.0.1, 26.0.2, 27.0.3, 28.0.2, 28.0.3
        System Images: android-26 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.4 => 0.59.4 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1

**Comment by thymikee** [comment]
I don't think Metro supports custom proxies out of the box. @cpojer could you confirm that?
As a workaround, have you tried setting up custom registry instead of the proxy (https://stackoverflow.com/questions/25660936/using-npm-behind-corporate-proxy-pac)?

**Comment by joebochill** [comment]
Any movement or further information about this? @thymikee @cpojer

**Comment by joebochill** [comment]
Still an issue

**Comment by phanhoangloc** [comment]
run this command inside the project to generate `main.jsbundle`:

```sh
react-native bundle --entry-file='index.js' --bundle-output='./ios/main.jsbundle' --dev=false --platform='ios'
```

Open the Xcode -> Select project target -> add main.jsbundle to Copy Bundle Resource in Build Phases.

You may get an error when connecting to Metro bundler because localhost is unreachable, change Metro Bundler configuration from localhost to your IP address.

Use cmd + D (iOS) or command `adb shell input keyevent 82` (Android) to open React Native Debug Menu, select Configure Bundler, then input your IP address.
