### ISSUE TITLE
Horizontal FlatList onReachEnd on RTL called infinitely

### ISSUE THREAD

**Issue by blitzcrank** [facebook/react-native#24597]
## 🐛 Bug Report
A horizontal flatlist will keep calling the 'onReachEnd' method infinitely when RTL (Right to Left) is on. The flatlist has more than enough items to not trigger the onReachEnd from the start (tested this on LTR). 

## To Reproduce
1. Put device in RTL language such as 'Arabic'
2. Run this snack: https://snack.expo.io/@bugreport2/horizontal-flatlist-rtl

## Expected Behavior
The flatlist should behave like on LTR and only call onReachEnd when the end of the horizontal flatlist is reached. In this case on RTL onReachedEnd should be called when the user has scrolled to the left end of the flatlist.

## Code Example
https://snack.expo.io/@bugreport2/horizontal-flatlist-rtl

## Environment
React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
      Memory: 178.79 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.2.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 18, 23, 26, 27, 28
        Build Tools: 27.0.1, 27.0.3, 28.0.1, 28.0.3
        System Images: android-18 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-27 | Intel x86 Atom, android-27 | Intel x86 Atom_64, android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.5 => 0.59.5
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by FadiAboMsalam** [comment]
I am facing same issue with horizontal flatList in RTL there also another couple issues opened for horizontal flatlist RTL for example #19150 and # but there seem no fix yet .
