### ISSUE TITLE
react-native init error cannot find module package.json

### ISSUE THREAD

**Issue by abhishekchatrath** [facebook/react-native#24594]
## 🐛 Bug Report
On setting up a new project using the **react-native-cli**, I found an error stating that the module `package.json` could not be found in the ``../ProjectName/node_modules/react-native`.

I am setting up a React Native project according to the instructions provided by **ViroReact** getting started documentation [click here](https://docs.viromedia.com/docs/quick-start-windows).

The interesting thing to note is that I have spun up several React Native projects like this for ViroReact over the past few weeks with ease and no such issue ever. So, this unexpected behaviour comes during a period of time crunch, obviously.

## To Reproduce
`react-native init <ProjectName>`
**OR**
`react-native init <ProjectName> --version=0.59.3`

## Terminal Logs
```$ react-native init ViroSample --version=0.59.3
This will walk you through creating a new React Native project in C:\...\ProjectName
Using yarn v1.5.1
Installing react-native@0.59.3...
yarn add v1.5.1
(node:13760) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
info No lockfile found.
[1/4] Resolving packages...
warning react-native > create-react-class > fbjs > core-js@1.2.7: core-js@<2.6.5 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
[2/4] Fetching packages...
[########################################################] 597/600internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'C:\...\<ProjectName>\node_modules\react-native\package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at checkNodeVersion (C:\Users\Abhishek\AppData\Roaming\npm\node_modules\react-native-cli\index.js:306:21)
    at run (C:\Users\Abhishek\AppData\Roaming\npm\node_modules\react-native-cli\index.js:300:3)
    at createProject (C:\Users\Abhishek\AppData\Roaming\npm\node_modules\react-native-cli\index.js:249:3)
    at init (C:\Users\Abhishek\AppData\Roaming\npm\node_modules\react-native-cli\index.js:200:5)
    at Object.<anonymous> (C:\Users\Abhishek\AppData\Roaming\npm\node_modules\react-native-cli\index.js:153:7)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
```

## Environment
**Note:** I can't run `react-native info` because the issue is about setting up the project itself, and this command requires a React Native project to exist first. `[skip envinfo]`

- Windows 10 
- Git Bash 
- `node -v`: v10.15.1
- `npm -v`: 6.4.1
- `react-native -v`: 
```
react-native-cli: 2.0.1
react-native: n/a - not inside a React Native project directory
```

**Comment by abhishekchatrath** [comment]
> Can you run `react-native info` and edit your issue to include these results under the **Environment** section?

Done.

**Comment by abhishekchatrath** [comment]
Running the command `npm init` elsewhere, I created a separate test environment and saved react-native `npm i react-native`.  Then I ran `react-native info` to get the following result:

```
info
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
      Memory: 2.26 GB / 7.92 GB
    Binaries:
      Yarn: 1.5.1 - ~\scoop\apps\yarn\current\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5314842
```

In case this information is important/relevant?

**Comment by thymikee** [comment]
This is not an issue with React Native itself. Looks like Yarn installs react-native in different directory (maybe you're inside yarn workspace?). 

I also couldn't reproduce this on my machine (macOS), and based on that it's ~12h since this issue was created and nobody else complained, I'd say it's something very specific to your environment.

I'd suggest installing latest Yarn (1.15) and see if init works in other directories. 

The code that throws the error was not changed in 2 years btw.

**Comment by abhishekchatrath** [comment]
> This is not an issue with React Native itself. Looks like Yarn installs react-native in different directory (maybe you're inside yarn workspace?).
> 
> I also couldn't reproduce this on my machine (macOS), and based on that it's ~12h since this issue was created and nobody else complained, I'd say it's something very specific to your environment.
> 
> I'd suggest installing latest Yarn (1.15) and see if init works in other directories.
> 
> The code that throws the error was not changed in 2 years btw.

---

ooof

But you're right though. I took another look, updated Yarn to 1.15, ran `npm config set registry "http://registry.npmjs.org"` and all bueno it works again!

Thanks for your time @thymikee !
