### ISSUE TITLE
[Packager] Cannot Redirect Dependency Like `"xmlhttprequest": "./lib/xmlhttprequest-browser.js"`

### ISSUE THREAD

**Issue by Hybrid-Force** [facebook/react-native#2459]
The packager cannot handle redirection from a dependent module to a local module, for [example](https://github.com/leancloud/javascript-sdk/blob/master/package.json#L41):
```
"browser": {
    ...
    "xmlhttprequest": "./lib/browserify-wrapper/xmlhttprequest-browser.js",
    "localStorage": "./lib/browserify-wrapper/localstorage-browser.js",
    ...
  },
```

When generating search path for the redirected module, it is [expects that the module is in `node_module` directory](https://github.com/facebook/react-native/blob/master/packager/react-packager/src/DependencyResolver/DependencyGraph/index.js#L352) which cannot work with redirection like: `"xmlhttprequest": "./lib/xmlhttprequest-browser.js"`

**Comment by browniefed** [comment]
@brentvatne consolidate to https://github.com/facebook/react-native/pull/2499 ? Also with the packager splitting off not sure how we want to handle migrating packager issues.

**Comment by brentvatne** [comment]
Indeed, #2499 seems to cover this, thanks for the report @Hybrid-Force!
