### ISSUE TITLE
Create a "Build from Source" command

### ISSUE THREAD

**Issue by cpojer** [facebook/react-native#24590]
This task is about building a command like `yarn init-from-source` (or a better name) that will create a project from React Native source to make it easy to end-to-end test the new project creation flow as well as it makes it easy to create projects from source.

Right now the manual steps for this process are: https://gist.github.com/cpojer/38a91f90614f35769e88410e3a387b48

Vision:
* The idea is for all of this to be wrapped up neatly into a single command line, using the version of RN cli that is shipped with RN on master (instead of npx).
* After we added this command, a follow-up should be to add this to our end-to-end tests and make sure it doesn't regress.
* Ideally this command will also run `yarn link` inside of `react-native` and then `yarn link react-native` after creating the new project. That will allow developers to modify the source version of RN and build a new app from it.

cc @lucasbento

**Comment by grabbou** [comment]
FYI you can run `./scripts/test-manual-e2e.sh` right now and it will build RN from source and make a test project for you automatically.

I believe we could start from there.

This script also has a command to run RNTester before creating a new project - we should probably comment this part out and move to a separate file.

So we could split `test-manual-e2e.sh` into:
- `build-from-source.sh`
- `test-manual-rn-tester.sh`
- `test-manual-rn-init.sh`
and make `test-manual-e2e.sh` compose these 3 together.

**Comment by grabbou** [comment]
Note: Your guide @cpojer for Android is running from source. 

We could also provide an alternative guide (which is what `./scripts/test-manual-e2e.sh` does at the moment) - building React Native from source and running it. 

The difference is Android is already compiled and we don't have to perform Gradle changes as presented in your guide.

Depending on the use-case, this may or may not be desired.

**Comment by cpojer** [comment]
I would like this command to build RN from source, yes.

**Comment by lucasbento** [comment]
@grabbou: how exactly does `test-manual-e2e.sh` should work? I tried it here and I get questioned twice about which version to use:

![image](https://user-images.githubusercontent.com/6207220/56721983-63b9bf80-6746-11e9-8ce3-47746a50bb93.png)

And in the end I get `Incorrect version number in /tmp/RNTestProject/package.json`.

**Comment by pvinis** [comment]
Just for one more data point, I did:
- install android ndk (https://developer.android.com/ndk/guides).
- clone `react-native` repo.
- change the react-native field in `react-native/template/package.json` to the absolute path of the react native repo, for example: `"react-native": "file:///Users/username/react-native"`.
- run `yarn install`
- run `npx @react-native-community/cli@next init TestApp --template file:///Users/username/react-native`.
- run `pod install`.
- run `yarn start` and press play on xcode.
then I got
```

Failed to construct transformer:  { Error: Cannot find module '/Users/pvinis/Source/contrib/react-native/RNTestProject/jest/hasteImpl'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at new HasteMap (/Users/pvinis/Source/contrib/react-native/RNTestProject/node_modules/metro/node_modules/jest-haste-map/build/index.js:366:25)
    at Function._createHaste (/Users/pvinis/Source/contrib/react-native/RNTestProject/node_modules/metro/src/node-haste/DependencyGraph.js:122:12)
    at /Users/pvinis/Source/contrib/react-native/RNTestProject/node_modules/metro/src/node-haste/DependencyGraph.js:154:37
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/pvinis/Source/contrib/react-native/RNTestProject/node_modules/metro/src/node-haste/DependencyGraph.js:14:24)
    at _next (/Users/pvinis/Source/contrib/react-native/RNTestProject/node_modules/metro/src/node-haste/DependencyGraph.js:34:9) code: 'MODULE_NOT_FOUND' }
(node:39936) UnhandledPromiseRejectionWarning: Error: Cannot find module '/Users/pvinis/Source/contrib/react-native/RNTestProject/jest/hasteImpl'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at new HasteMap (/Users/pvinis/Source/contrib/react-native/RNTestProject/node_modules/metro/node_modules/jest-haste-map/build/index.js:366:25)
    at Function._createHaste (/Users/pvinis/Source/contrib/react-native/RNTestProject/node_modules/metro/src/node-haste/DependencyGraph.js:122:12)
    at /Users/pvinis/Source/contrib/react-native/RNTestProject/node_modules/metro/src/node-haste/DependencyGraph.js:154:37
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/pvinis/Source/contrib/react-native/RNTestProject/node_modules/metro/src/node-haste/DependencyGraph.js:14:24)
    at _next (/Users/pvinis/Source/contrib/react-native/RNTestProject/node_modules/metro/src/node-haste/DependencyGraph.js:34:9)
(node:39936) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:39936) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I also tried running `./scripts/test-manual-e2e.sh` but I got
```
Preparing version 1000.0.0

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/Users/pvinis/Source/contrib/react-native/ReactAndroid/build.gradle' line: 190

* What went wrong:
A problem occurred evaluating project ':ReactAndroid'.
> Cannot get property 'absolutePath' on null object

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':ReactAndroid'.
> compileSdkVersion is not specified.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Couldn't generate artifacts
```

(I find it weird that some scripts in RN use npm and npm when most other things are done with yarn..)

**Comment by grabbou** [comment]
@lucasbento this script doesn't work on master right now. Please run it or copy from `0.60-stable` where I am doing some fixes to adopt it to the new CLI.

**Comment by grabbou** [comment]
@cpojer just to be clear, to build from source, not to run from source? That's a small difference - only for Android.

**Comment by cpojer** [comment]
@grabbou I think ideally the command should set up a new project, and then patch the gradle files to build from source when running. If I change a java file in RN source, it should be reflected in the app.

**Comment by pvinis** [comment]
I just want to try out iOS with cocoapods 😢.

About the difference `running` and `building`.. aren't we doing a build of the source, and make the rn library/package, and then create a new project that uses that package? Am I misunderstanding here?

**Comment by lucasbento** [comment]
I'm slightly confused on this as well and I can't really run the Android version here, it's failing on the build with Android NDK.

Will it be enough to add [these steps](https://gist.github.com/cpojer/38a91f90614f35769e88410e3a387b48#switch-into-the-new-project-cd-testapp) here: https://github.com/facebook/react-native/blob/0.60-stable/scripts/test-manual-e2e.sh#L74-L92?

On this branch it's already using the local CLI.

When we complete this I would say it would be nice to work on docs for building from source.

**Comment by cortinico** [comment]
Closing as now we have a page to describe those steps:
https://reactnative.dev/contributing/how-to-build-from-source
