### ISSUE TITLE
canvas / drawing

### ISSUE THREAD

**Issue by forresto** [facebook/react-native#246]
In the f8 presentation, Tom Occhino noted that the animated header of the f8 app was driven by js. Are there any canvas examples?

**Comment by diegolaciar** [comment]
https://www.youtube.com/watch?v=OPFf53fdUmQ

On Thu, Mar 26, 2015 at 5:05 PM, Forrest Oliphant <notifications@github.com>
wrote:

> In the f8 presentation, Tom Occhino noted that the animated header of the
> f8 app was driven by js. Are there any canvas examples?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/react-native/issues/246>.
>

-- 


The information contained in this e-mail may be confidential. It has been 
sent for the sole use of the intended recipient(s). If the reader of this 
message is not an intended recipient, you are hereby notified that any 
unauthorized review, use, disclosure, dissemination, distribution or 
copying of this communication, or any of its contents, 
is strictly prohibited. If you have received it by mistake please let us 
know by e-mail immediately and delete it from your system. Many thanks.

 

La información contenida en este mensaje puede ser confidencial. Ha sido 
enviada para el uso exclusivo del destinatario(s) previsto. Si el lector de 
este mensaje no fuera el destinatario previsto, por el presente queda Ud. 
notificado que cualquier lectura, uso, publicación, diseminación, 
distribución o copiado de esta comunicación o su contenido está 
estrictamente prohibido. En caso de que Ud. hubiera recibido este mensaje 
por error le agradeceremos notificarnos por e-mail inmediatamente y 
eliminarlo de su sistema. Muchas gracias.

**Comment by forresto** [comment]
Specifically, thinking about [my dataflow editor paths](http://facebook.github.io/react/blog/2014/02/24/community-roundup-17.html#svg-based-graphical-node-editor):

!(the-graph)[http://facebook.github.io/react/img/blog/react-svg-fbp.png]

**Comment by vjeux** [comment]
It is using React Art. We want to open source the obj-c backend that we have in the future

**Comment by simonlast** [comment]
I'd love to see that open sourced!

**Comment by volkanunsal** [comment]
@simonlast 

I believe [it already is](https://github.com/reactjs/react-art).

**Comment by KendallPark** [comment]
+1 I'd like to see this as well.

**Comment by zoomclub** [comment]
I just got the gitbook Beginning React-Native and the first chapter that caught my eye was "Drawing Canvas on React-Native". I abruptly found out that it was the shortest chapter in the book, only a few lines! It basically says that I'm S*** out of luck except for using the internal Webview to render canvas calls.

Is there any thing more direct in the works? It would seem that something as essential as drawing could be directly mapped over to iOS? I just need the raw HTML5 canvas not a scenegraph like React-Art.

**Comment by skevy** [comment]
It's not documented yet...but here is what @vjeux mentioned above: https://github.com/facebook/react-native/tree/d20a6e9d2d92bfc6bc81cc828c4008af1c7a7760/Libraries/ART

**Comment by zoomclub** [comment]
Thanks and great! A straight canvas still works out best for me as I just need to render lines and glyphs and have no need for a graphic scene graph. Will it be possible to use Opentype.js in React-Native?

http://nodebox.github.io/opentype.js

**Comment by zoomclub** [comment]
Looking further at React-ART it looks like it handles paths, etc. Maybe it is just the essentials and not to much extra now, like a full blown scene graph. Still very much interested in if Opentype.js can be supported.

**Comment by brentvatne** [comment]
@zoomclub - give it a try and let us know :smile:

I don't see why not, it looks like it just parses OpenType and TrueType files.

Closing this issue because React ART solves the original question.
