### ISSUE TITLE
Discussion: Debugging

### ISSUE THREAD

**Issue by zaguiini** [facebook/react-native#24604]
It's not an issue since I've been able to fix my problem, but... React Native JS debugging overall experience is very poor. 

Consider this code:

![image](https://user-images.githubusercontent.com/26530524/56740037-7c29da00-6746-11e9-8ca3-2305afadf919.png)

That's some bad code and, of course, it throws an error. So far, so good. But that's the error:

![image](https://user-images.githubusercontent.com/26530524/56740061-8b108c80-6746-11e9-989d-84dd3a248014.png)

And I solved it by using the following snippet:

![image](https://user-images.githubusercontent.com/26530524/56740135-b72c0d80-6746-11e9-9691-97750cb691d8.png)

Point is: `.sort` actually mutates the array instead of return a new copy. Ok, my mistake, I shouldn't be doing that way. But what useful message does the debugger returns for me? It says there's the specified error in `Requests` (assuming it is the component in question).

But what else? In which line? Which statement is causing the error? That stacktrace is not very specific. That was very hard to find out, turned out to be something very simple to fix but it cost me at least an hour.

That's just a "contrived" example, but that actually happens everywhere. Debugging in the JS core is a nightmare, in both iOS and Android. I literally have to comment code, do the trial-and-error method to find out what is going wrong and then fix it. What can be done to address this?

**Comment by kelset** [comment]
👋 there - we are aware of the problem and, in fact, there is already a discussion open in the dedicated repo: https://github.com/react-native-community/discussions-and-proposals/issues/69
