### ISSUE TITLE
StatusBar.currentHeight should be dynamic on orientation change

### ISSUE THREAD

**Issue by bryankang** [facebook/react-native#24603]
On android devices, `StatusBar.currentHeight` returns the value of the status bar height for the orientation that the app was opened.

For devices like the Pixel 3 XL, it has two different status bar heights depending on orientation. The portrait uses a notch, so it's taller than the landscape counterpart. 

When you launch the app on landscape, `StatusBar.currentHeight` returns 28. Launching it on portrait returns 40 something. Since these values are static, rotating the device results in the wrong status bar height for that orientation.

**Comment by michalchudziak** [comment]
Hello there 👋 this issue doesn't have a repro (which means, a `react-native init`-ed project with the minimal changes that leads to creating the same issue you are reporting). Unfortunately, I have no way of helping you in a meaningful way – there is no easy way for me to recreate the situation and check that the issue reported is still there when changing the code.

**Comment by bryankang** [comment]
@michalchudziak Sorry about that, I was in a rush this morning.

The reproduce the problem (Android):

1. `react-native init <ProjectName>`
2. Log `StatusBar.currentHeight` in the render method
3. Start up an emulator to get the correct status bar height
4. Rotate the emulator and observe that the height does not change. Due to the growing number of devices with a notch, this will be problematic in the long run

**Comment by matt-oakes** [comment]
@BryanJBryce You are correct that this is an issue. The `StatusBar` component has actually been moved out of this repository and into [a community one](https://github.com/react-native-community/react-native-statusbar). Can you open an issue there please.
