### ISSUE TITLE
iOS Modal blocks UI after app enters background then returns to foreground

### ISSUE THREAD

**Issue by thomasarogers** [facebook/react-native#24609]
## 🐛 Bug Report
(only iOS) When displaying a modal to the user and pressing the home button the application enters background when re-opening the application the modal is not visible but any button press which should cause the modal to be displayed does not function and no modal can be displayed without the parent view being unmounted an mounted again. (Present in RN 0.57.4 also)

## Expected Behavior
Either modal should remain visible on reopen or buttons to display modal should function 

## Environment
info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (4) x64 Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz
      Memory: 70.09 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.15.0 - /usr/local/opt/node@8/bin/node
      npm: 6.4.1 - /usr/local/opt/node@8/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 26, 27, 28
        Build Tools: 23.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.2, 28.0.3
        System Images: android-26 | Google APIs Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.1 => 0.59.1 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-git-upgrade: 0.2.7

**Comment by thomasarogers** [comment]
Worked around by listening for AppState change and hiding modals before app is entering background

**Comment by majd-asab** [comment]
@thomasarogers can you provide a small code example, i'd like to work on this issue

**Comment by thomasarogers** [comment]
Sorry I only have production code

**Comment by bicibg** [comment]
I can confirm the same issue on Android with the latest version of RN. same issue during live reload or normal reload when modal is visible
