### ISSUE TITLE
 'config.h' file not found because of low version of cocoapod

### ISSUE THREAD

**Issue by hite** [facebook/react-native#24601]
- [x] Review the documentation: https://facebook.github.io/react-native
- [x] Search for existing issues: https://github.com/facebook/react-native/issues
- [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## 🐛 Bug Report
There are two bugs which one is resolved finally, and another is unresolved.
1.  src/base/mutex.h:105:10: 'config.h' file not found. It look like a duplicate bug with [ #14382](https://github.com/facebook/react-native/issues/14382), but it is worse.
2. After fix the first bug , run `react-native run-ios`.It produce errors.
```
debug Error: Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 70. To debug build logs further, consider building your app with Xcode.app, by opening AppHostDemo.xcworkspace

xcodebuild: error: Unable to find a destination matching the provided destination specifier:
```
![xcodebuild: error](https://user-images.githubusercontent.com/381900/56728279-009b4d80-6785-11e9-9397-35a42cd176c1.png)

## To Reproduce
I follow the guide step from [integration-with-existing-apps](https://facebook.github.io/react-native/docs/integration-with-existing-apps)

1. Create a folder `AppHostDemo-React`
1. Create a package.json which content is same as the sample codes. 
2. `yarn add react-native`, then ` yarn add react@version_printed_above`.The file content of package.json is 
```json
{
"dependencies": {
    "react": "16.8.3",
    "react-native": "^0.59.5"
  }
}
```
2. Skip  `brew install cocoapods` because I already have cocoapod to build my app.(Cocoapod version is 1.1.1. THAT is the point)
3. Add sample code to `Podfile`, and run `pod install`

When pod install complete, go to Xcode,  run your scheme. The 
>src/base/mutex.h:105:10: 'config.h' file not found

error happens.

I search around and find a right way in issue.

Then install the third-party
$ cd node_modules/react-native/
$ scripts/ios-install-third-party.sh

After do it, `./configure` executed, so run `./configure` explicitly is not needed. There is a file 'config.h' in src folder.
But Not Found error is steady.

I spent two days to search the right way which can truly solve my problem.
Everybody say that `./configure` solve their problems, but not mine.

Until today I realize that the project  created from `react-native init myRN` works.
So i decide to look for the difference between `myRN` which is a .xcodeproj and `AppHostDemo` which is a .xcworkspace project.

Finally, I see code from `React.podspec`
```ruby
s.cocoapods_version       = ">= 1.2.0"
```
I spend about a hour to upgrade cocoapod to 1.6.1.
Run AppHostDemo scheme, BUILD SUCCESS.

The first bug is resolved. 
to run `react-native`, the second error happens which is still not resolved.

## Expected Behavior
1. Following  [integration-with-existing-apps](https://facebook.github.io/react-native/docs/integration-with-existing-apps),  `'config.h' file not found` should not happen.

2. `react-native info` should include cocoapod info.
3.   `react-native` works well.

## Environment

```bash
% react-native info                            
info
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (4) x64 Intel(R) Core(TM) i5-6287U CPU @ 3.10GHz
      Memory: 528.77 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      Yarn: 1.15.2 - ~/.yarn/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: ^0.59.5 => 0.59.5
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

**Comment by matt-oakes** [comment]
👋

Issue #1 is a non-issue to my mind as Cocoapods 1.2.0 is over 2 years old at this point. It should likely be noted in the documentation though.

Issue #2 needs a bit more information. It suggests that the simulator ID does not exist. Can you try running the app through Xcode and see if that works. Also, if you have overriden the default simulator type then it might no longer be valid.

**Comment by hite** [comment]
About: Issue 2.
Yes, I can run the app through Xcode. Maybe It is a my case-by-case
