### ISSUE TITLE
Error: Unable to resolve module `./utils/batch` 

### ISSUE THREAD

**Issue by alainib** [facebook/react-native#24602]
## 🐛 Bug Report
after erasing  node_modules  folder i cannot compile anymore

	 error: bundling failed: Error: Unable to resolve module `./utils/batch` 
	 from `...node_modules\react-redux\lib\index.js`: 
	 The module `./utils/batch` could not be found from `...node_modules\react-redux\lib\index.js`.
	 
## Environment
"react": "^16.8.6",
"react-native": "^0.59.5",
"react-redux" : "6.0.1"

i tryed to 
`npm install`
`npm start --clear-cache`
`npm cache clean --force`

**Comment by alainib** [comment]
react-native info : 

	info
	  React Native Environment Info:
		System:
		  OS: Windows 10
		  CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
		  Memory: 10.32 GB / 15.79 GB
		Binaries:
		  Node: 10.15.2 - D:\work\nodejs\node.EXE
		  Yarn: 1.13.0 - C:\work\Yarn\bin\yarn.CMD
		  npm: 6.9.0 - D:\work\nodejs\npm.CMD

**Comment by zeinabawadaSaugo** [comment]
same issue here 
 React Native Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 16.04.5 LTS (Xenial Xerus)
      CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
      Memory: 1.46 GB / 15.53 GB
      Shell: 4.3.48 - /bin/bash
    Binaries:
      Node: 11.10.0 - /usr/local/bin/node
      npm: 6.7.0 - /usr/local/bin/npm
    SDKs:
      Android SDK:
        API Levels: 24, 26, 27, 28
        Build Tools: 26.0.2, 27.0.3, 28.0.3
        System Images: android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.57.8 => 0.57.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by thymikee** [comment]
@alainib this needs a reproduction. Can you provide a minimal example showing the issue? Otherwise it's not actionable on our side.

**Comment by alainib** [comment]
> 
> 
> @alainib this needs a reproduction. Can you provide a minimal example showing the issue? Otherwise it's not actionable on our side.

thank you for help , what did you need ? can i send you the package.json file ?

**Comment by thymikee** [comment]
I need a full project where I can run commands, etc to investigate. You can also send me a zip through email (it's pretty easy to find) if you cannot share it publicly.

**Comment by Ejyption** [comment]
This is a huge issue. I cannot use react-redux ^7.0.0 as expo doesn't support the new hook dependencies.
I cannot use ^6.0.0 as it always gives me the error 
```
Unable to resolve module ./utils/batch 
 from ...node_modules\react-redux\lib\index.js: 
```

**Comment by Ejyption** [comment]
Reproduce the error:

1. Start a new React Native app (empty)
2. add to package.json
 `"react-navigation": "^3.3.2",`
 `"react-redux": "^6.0.0",`
 `"redux": "^4.0.1",`
 `"redux-thunk": "^2.3.0"`

3. npm install
4. expo start
5. open app in expo mobile application.
6. error shows up. Unable to resolve it.

**Comment by Ejyption** [comment]
@alainib I have found the solution.
Problem:
This happens when you install react-redux ^7.0.0 and then downgrade to ^6.0.0.
People do this as expo doesn't have dependencies for hook featured in ^7.0.0
Now that you have downgraded, it won't find './utils/batch'. This batch file is only found in ^7.0.0 which means expo is caching libraries with the directory names you are in. Even if you delete the entire project directory and recreate it spelled the same, the cache still brings this error up.

Solution
instead of `expo start` or `npm start`
use `expo r -c`
this removes the cache associated with the build in that directory.

**Comment by alainib** [comment]
> 
> 
> @alainib I have found the solution.
> Problem:
> This happens when you install react-redux ^7.0.0 and then downgrade to ^6.0.0.
> People do this as expo doesn't have dependencies for hook features in ^7.0.0
> Now that you have downgraded, it won't find './utils/batch'. This batch file is only found in ^7.0.0 which means expo is caching libraries with the directory names you are in. Even if you delete the entire project directory and recreate it spelled the same, the cache still brings this error up.
> 
> Solution:
> instead of `expo start` or `npm start`
> use `expo r -c`
> this removes the cache associated with the build in that directory.

i never used or installed expo :(

**Comment by thymikee** [comment]
@alainib expo uses Metro as a bundler, and this bundler has a cache that lives in a OS's tmp directory, so the effect may be similar.

Have you tried purging your node_modules directory, installing everything all over again and then running `yarn react-native start --reset-cache`? This command will start Metro server with cache being cleared.

**Comment by alainib** [comment]
> 
> 
> @alainib expo uses Metro as a bundler, and this bundler has a cache that lives in a OS's tmp directory, so the effect may be similar.
> 
> Have you tried purging your node_modules directory, installing everything all over again and then running `yarn react-native start --reset-cache`? This command will start Metro server with cache being cleared.

i removed node_modules multiple times, as doing `npm cache clean --force ` and `npm start --clear-cache` and `gradlew clean` 

Ps : i get this error on windows  + android

**Comment by alainib** [comment]
it finally worked thank you 

- delete node_modules folder
- package.json  : `"react": "16.8.3", "react-native": "0.59.2", "react-redux": "6.0.1"`
- npm install 
- live the `node_modules\react-native\scripts\launchPackager.bat` as it with `node "%~dp0..\cli.js" start`
- change  `@react-native-community\cli\build\commands\runAndroid\runAndroid.js ` : 

  `const procConfig = {   cwd: process.cwd()   } `

- `npm cache clean --force`
- `npm start --clear-cache`
- `react-native start --reset-cache`
AND THIS STEP I DIDNT DONE BEFORE
-  delete `C:\Users\YOURUSERNAME\AppData\Local\Temp\metro-cache`

**Comment by thymikee** [comment]
I'm pretty sure this wouldn't happen (didn't happen to me at least) if you used Yarn instead of npm, it's just way more reliable :). Anyway, glad you sorted it out! I feel we're good to close it now then.

**Comment by craigcosmo** [comment]
> @alainib I have found the solution.
> Problem:
> This happens when you install react-redux ^7.0.0 and then downgrade to ^6.0.0.
> People do this as expo doesn't have dependencies for hook features in ^7.0.0
> Now that you have downgraded, it won't find './utils/batch'. This batch file is only found in ^7.0.0 which means expo is caching libraries with the directory names you are in. Even if you delete the entire project directory and recreate it spelled the same, the cache still brings this error up.
> 
> Solution:
> instead of `expo start` or `npm start`
> use `expo r -c`
> this removes the cache associated with the build in that directory.

saved my life, thank you

**Comment by relaxomatic** [comment]
@thymikee I can confirm using yarn instead solved the issue for me

**Comment by craigcosmo** [comment]
> @thymikee I can confirm using yarn instead solved the issue for me

yarn and that solution of alainib

**Comment by pengdongliang** [comment]
> 它终于工作了谢谢你
> 
> * 删除node_modules文件夹
> * package.json： `"react": "16.8.3", "react-native": "0.59.2", "react-redux": "6.0.1"`
> * npm安装
> * `node_modules\react-native\scripts\launchPackager.bat`和它一样生活`node "%~dp0..\cli.js" start`
> * 改变   `@react-native-community\cli\build\commands\runAndroid\runAndroid.js `：
>   `const procConfig = {   cwd: process.cwd()   } `
> * `npm cache clean --force`
> * `npm start --clear-cache`
> * `react-native start --reset-cache`
>   以及我之前完成的这一步
> * 删除 `C:\Users\YOURUSERNAME\AppData\Local\Temp\metro-cache`



> 它终于工作了谢谢你
> 
> * 删除node_modules文件夹
> * package.json： `"react": "16.8.3", "react-native": "0.59.2", "react-redux": "6.0.1"`
> * npm安装
> * `node_modules\react-native\scripts\launchPackager.bat`和它一样生活`node "%~dp0..\cli.js" start`
> * 改变   `@react-native-community\cli\build\commands\runAndroid\runAndroid.js `：
>   `const procConfig = {   cwd: process.cwd()   } `
> * `npm cache clean --force`
> * `npm start --clear-cache`
> * `react-native start --reset-cache`
>   以及我之前完成的这一步
> * 删除 `C:\Users\YOURUSERNAME\AppData\Local\Temp\metro-cache`

This method is really useful. Thank you.
