### ISSUE TITLE
Using borderLeftWidth and borderLeftColor display bug on iPhone6 plus

### ISSUE THREAD

**Issue by HaloWang** [facebook/react-native#24611]
## 🐛 Bug Report

Using borderLeftWidth and borderLeftColor display bug on iPhone6 plus. But iPhone 8 is well.

![IMG_0423](https://user-images.githubusercontent.com/7344724/56780995-0a1fc680-6814-11e9-9bf6-a533bf7ca9e4.png)
![IMG_0421](https://user-images.githubusercontent.com/7344724/56780996-0ab85d00-6814-11e9-9ad3-19c8c0d7a4db.png)

## To Reproduce

```jsx
<View
  style={{
    height: 100,
    width: 100,
    marginTop: 200,
    marginLeft: 100,
    backgroundColor: 'rgba(0,0,0,0.1)',
    borderLeftColor: 'red',
    borderLeftWidth: 5,
    borderRadius: 5,
  }}
/>
```
If borderLeftWidth >= borderRadius, bug appear.
If borderLeftWidth < borderRadius, nothing wrong.

## Environment
```
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
      Memory: 270.01 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.14.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 19, 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.3, 25.0.2, 26.0.2, 27.0.3, 28.0.3
        System Images: android-23 | Intel x86 Atom, android-23 | Intel x86 Atom_64, android-23 | Google APIs ARM EABI v7a, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-27 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.6 => 16.8.6 
      react-native: ^0.59.4 => 0.59.4 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-create-library: 3.1.2
      react-native-git-upgrade: 0.2.7

```

**Comment by lukewalczak** [comment]
Hey @HaloWang, I was trying to reproduce it on iPhone 6 Plus and iPhone 8 (RN v. 0.59.4, iOS 12.2), but everything works fine. Could you please provider a snack for the bug or create a demo repository with the bug?

**Comment by HaloWang** [comment]
@lukewalczak I create [this repo](https://github.com/HaloWang/bugshowcase)

**Comment by lukewalczak** [comment]
I was able to reproduce it only on physical devices (iPhone 6 Plus and iPad Mini 4) and it seems like the issue is related to bigger iOS devices (Plus or iPad).

**Comment by HaloWang** [comment]
Yes, I can only reproduce it on iPhone 6 Plus, physical device, not simulator.
