### ISSUE TITLE
Bypass touch events for transparent view to underlying view

### ISSUE THREAD

**Issue by aksonov** [facebook/react-native#2461]
I have several views with absolute full-screen layout (because of issue #2260) and i want to have onPress functionality for some of them, how i could do it? For now only latest added view is receiving all touch events.

**Comment by aksonov** [comment]
I've resolved issue #2260, so bypassing touch events could be useful, but not critical...

**Comment by ide** [comment]
Check out the pointerEvents prop which lets you control this.
