### ISSUE TITLE
React native deep linking not working when app is in background state

### ISSUE THREAD

**Issue by DalbirKaur** [facebook/react-native#24624]
## 🐛 Bug Report

When the app is closed, I am able to get deep link url that is clicked by Linking.getInitialURL(). When the app is in the background state, then nothing is mounted. So, I am not able to get the url even by the Linking.addEventListener('url', method_name).

What is the way to achieve this?

## Code Example

componentDidMount() {
  Linking.addEventListener('url', this._handleOpenURL);
},
componentWillUnmount() {
  Linking.removeEventListener('url', this._handleOpenURL);
},
_handleOpenURL(event) {
  console.log(event.url);
}
I have added this code in app.js
## Environment

  React Native Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
      CPU: (4) x64 Intel(R) Core(TM) i3-6098P CPU @ 3.60GHz
      Memory: 1.73 GB / 15.57 GB
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 10.11.0 - /usr/bin/node
      npm: 6.7.0 - /usr/bin/npm
    npmPackages:
      react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728 
      react-native: ^0.58.5 => 0.58.5 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
      react-native-rename: 2.4.0
      react-native-slideshow: 1.0.1

**Comment by maleking** [comment]
are you added
```
<activity
  android:name=".MainActivity"
  android:launchMode="singleTask">
```
in AndroidManifest.xml ?
(https://facebook.github.io/react-native/docs/linking)

**Comment by DalbirKaur** [comment]
@amalChandran 
Yes, I have already added this in 'my_project/android/app/src/main/AndroidManifest.xml.

<activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
          android:screenOrientation="portrait"
        android:windowSoftInputMode="adjustResize"
          android:launchMode="singleTask">

**Comment by DalbirKaur** [comment]
Yes, I have already added this in
'my_project/android/app/src/main/AndroidManifest.xml. Example of code:

<activity
android:name=".MainActivity"
android:label="@string/app_name"
android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
android:screenOrientation="portrait"
android:windowSoftInputMode="adjustResize"
android:launchMode="singleTask">


Thanks and Regards
Dalbir Kaur
Software Engineer - Webner Solutions pvt. ltd.

**Comment by platonish** [comment]
Any updates on this?

**Comment by platonish** [comment]
@DalbirKaur were you able to solve for this?

**Comment by DalbirKaur** [comment]
@platonish, I am not able to get any lead yet.

**Comment by janet-rivas** [comment]
I'm having the same issue in android I'm not able to get the URL to make any action 
"react": "^16.8.3",
"react-native": "^0.59.2",

**Comment by maleking** [comment]
@DalbirKaur can you attach AndroidManifest.xml file ?

**Comment by DalbirKaur** [comment]
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.turndoctor">
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" /> 
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.DOWNLOAD_WITHOUT_NOTIFICATION" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.USE_FINGERPRINT"/>
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <permission
        android:name="${applicationId}.permission.C2D_MESSAGE"
        android:protectionLevel="signature" />
    <uses-permission android:name="${applicationId}.permission.C2D_MESSAGE" />
    

    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
          android:screenOrientation="portrait"
        android:windowSoftInputMode="adjustResize"
          android:launchMode="singleTask">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
                <action android:name="android.intent.action.DOWNLOAD_COMPLETE"/>
            </intent-filter>
          <intent-filter>
              <data android:scheme="http" android:host="MY_HOST_NAME" />
              <action android:name="android.intent.action.VIEW" />
              <category android:name="android.intent.category.BROWSABLE"/>
              <category android:name="android.intent.category.DEFAULT"/>
          </intent-filter>
          <intent-filter android:label="@filter_view_http_gizmos">
              <action android:name="android.intent.action.VIEW" />
              <category android:name="android.intent.category.DEFAULT" />
              <category android:name="android.intent.category.BROWSABLE" />
              
              <data android:scheme="http"
                  android:host="www.tdemo.com"
                  android:pathPrefix="/td" />
              
          </intent-filter>
          <intent-filter android:label="Turn Doctor">
              <action android:name="android.intent.action.VIEW" />
              <category android:name="android.intent.category.DEFAULT" />
              <category android:name="android.intent.category.BROWSABLE" />
              
              <data android:scheme="example"
                  android:host="gizmos" />
          </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_name"
            android:value="YOUR NOTIFICATION CHANNEL NAME"/>
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_description"
            android:value="YOUR NOTIFICATION CHANNEL DESCRIPTION"/>
        
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_color"
            android:resource="@android:color/white"/>

        
        <receiver
            android:name="com.google.android.gms.gcm.GcmReceiver"
            android:exported="true"
            android:permission="com.google.android.c2dm.permission.SEND" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <category android:name="${applicationId}" />
            </intent-filter>
        </receiver>
        

        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
            </intent-filter>
        </receiver>
        <service android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService"/>

        
        <service
            android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerServiceGcm"
            android:exported="false" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
            </intent-filter>
        </service>
        

        
        <service
            android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
            android:exported="false" >
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>


        <service android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationActionService" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationActionHandlerReceiver"
            android:exported="true">
            <intent-filter>
                <action android:name="${applicationId}.firstAction" />
                <action android:name="${applicationId}.secondAction" />
            </intent-filter>
        </receiver>
    </application>

</manifest>

@maleking, I have pasted the content of AndroidManifest.xml file of my project. Because I was unable to attach the .xml file.

**Comment by platonish** [comment]
For me, the issue was that although the app would come to the foreground on clicking on the app link (say from an SMS), the callback passed to `Linking.addEventListener` never got fired. 

So what I ended up doing is this: add an `AppState` listener to check the url from `Linking.getInitialURL`, and if it is a valid URL, redirect accordingly.

```javascript
componentDidMount() {
  // triggered when react native boots
  this._checkInitialUrl()

  AppState.addEventListener('change', this._handleAppStateChange)
  // never gets fired on Android, hence useless to me
  // Linking.addEventListener('url', url => console.log('url received: ', url))
}

componentWillUnmount() {
  AppState.removeEventListener('change', this._handleAppStateChange)
}

_handleAppStateChange = async (nextAppState) => {
  if (
    this.state.appState.match(/inactive|background/) &&
    nextAppState === 'active'
  ) {
    this._checkInitialUrl()
  }
  this.setState({ appState: nextAppState })
}

_checkInitialUrl = async () => {
  const url = await this._getInitialUrl()
  this._handleUrl(url)
}

_getInitialUrl = async () => {
  const url = await Linking.getInitialURL()
  return url
}

_handleUrl = (url) => {
  // write your url handling logic here, such as navigation
  console.log('received URL: ', url)
}
```

**Comment by jwaldrip** [comment]
Same issue here on 59.8.

**Comment by tranthienhao** [comment]
Does any one have a work around on this? I'm facing the same issue for Android devices.
And @glocore 's solution is not work for me. It will fire the _checkInitialUrl even if I don't click on any link

**Comment by apamphilon** [comment]
@tranthienhao I am also wondering this. Does anyone have any light to shed on this? Is this a bug, or  does `Linking.addEventListener('url', method_name).` not work on Android?

**Comment by DalbirKaur** [comment]
@apamphilon try the below code. 
 componentDidMount(){
           this._checkInitialUrl()
           AppState.addEventListener('change', this._handleAppStateChange)
           Linking.getInitialURL().then(async (url) => {
               if (url) {
                   console.log('Initial url is: ' + url);
               }
           }).catch(err => console.error('An error occurred', err));
       }
       componentWillUnmount() {
         AppState.removeEventListener('change', this._handleAppStateChange)
       }

       _handleAppStateChange = async (nextAppState) => {
         if (
           this.state.appState.match(/inactive|background/) &&
           nextAppState === 'active'
         ) {
           this._checkInitialUrl()
         }
         this.setState({ appState: nextAppState })
       }

       _checkInitialUrl = async () => {
         const url = await this._getInitialUrl()
         this._handleUrl(url)
       }

       _getInitialUrl = async () => {
         const url = await Linking.getInitialURL()
         return url
       }
this is working if the app is in background state too.

**Comment by apamphilon** [comment]
@DalbirKaur Thanks for the suggestion. I did try and do it this way but found that if the deep link has already been navigated to and then you switch screens and put the app back into the background and then relaunch, the event listener will fire again and navigate to that screen again.

Any thoughts?

**Comment by SirCameron** [comment]
for me, the issue with using appState as a workaround is that on iOS Linking.addEventListener('url') will get the latest url sent to the app - this is helpful if the app is used to share URLs. So each time a URL is sent to the app, it receives the correct one. Using appState and getInitialURL you only ever get the first url the app was launched with. 

Is there any update on getting Linking.addEventListener('url') working properly on Android?

**Comment by ppv94** [comment]
I am also facing same issue Linking.addEventListener('url') returns the initial url only, or Linking.getInitialURL() returns null. Linking.removeEventListener('url') doesnt work, how can we remove the existing url and get the latest url.

**Comment by varunon9** [comment]
For Android, this is working for me-
```
    if (Platform.OS === 'android') {
      Linking.getInitialURL().then(url => {
        if (url) {
          this.deepLinkingNavigate(url);
        }
      });
    }
    Linking.addEventListener('url', this.handleOpenURL);
```
`getInitialURL` will take care of app closed/killed state and `addEventListener` will work when app is in background/foreground.

**Comment by Kingsace** [comment]
Does anyone can solve keep getting the old url instead of latest url issue?

**Comment by cvarley100** [comment]
Also facing this issue. The event listener fails to fire if the app is not already open.

**Comment by itcurves** [comment]
facing the same issue. it is working fine for iOS for me by the way.

**Comment by joaocac** [comment]
Facing the same issue. Not working for iOS. Cannot get the url (always null) when the app is closed when the link happens.

**Comment by srichallamalla935** [comment]
When the app is in background getinitialurl method returns null it is not working in android any one find the solution for it..even though i used the app state it is not working for me

**Comment by srichallamalla935** [comment]
These Listeners calls when app is in background

componentDidMount() {
  Linking.addEventListener('url', this._handleOpenURL);
},
componentWillUnmount() {
  Linking.removeEventListener('url', this._handleOpenURL);
},
_handleOpenURL(event) {
  console.log(event.url);
}

**Comment by JulianKingman** [comment]
Not sure if others are having this problem, but for me the event listener doesn't work (`Linking.addEventListener('url', link => ({ link }));`)
Also, as has been mentioned, Linking.getInitialUrl only works on cold start, not from background.

**Comment by JulianKingman** [comment]
The event listener doesn't fire for me on iOS

**Comment by joaocac** [comment]
Found that while running with the debugger in iOS simulator it will work through the event listener but not with  `Linking.getInitialURL()`.

Also, my team found that without the debugger it works fine.

Doing a trace, it correctly sets the bridge values/info correctly but when calling the method `getInitialURL`, the bridge no longer holds those values. 

It seems that there is a reset between both moments when the Debugger is present.

I hope this can be a hint to investigate the issue and for the solution.
I will post more info if I find something more.

**Comment by perry-mitchell** [comment]
@joaocac Found mostly the same on my first run through this, but now after using a combination of `Linking.addEventListener`**and** `Linking.getInitialURL()` I only don't see a URL during cold-start. All other initiations work fine and I see the deep-linked URL. On RN 0.59, iOS.

**Comment by aathapa** [comment]
If using firebase dynamic links then you can use onLink() event listener for latest url. Also make sure you call getInitialLink() when component mounts.

**Comment by ryanoconnor7** [comment]
For those that are still facing the issue of not getting an event when a url is opened when the app is in background, I have a workaround for iOS. 

in `openURL` in AppDelegate, add this line: 
`[[NSUserDefaults standardUserDefaults] setObject:url.absoluteString forKey:@"deepLinkURL"];`

In your component in JS, add this:
```
Settings.watchKeys(["deepLinkURL"], () => {
      const url = Settings.get("deepLinkURL");
});
```

Make sure you add "RCTSettings" as a sub-pod in your podfile.

**Comment by krishnakumarrk** [comment]
Pls try this. 
    componentDidMount() {
        Linking.addEventListener("url", this.handleOpenURL);
        this.handleDeepLinkingRequests();
    }
handleDeepLinkingRequests = () => {
            Linking.getInitialURL()
                .then(url => {
                    if (url) {
                        this.handleOpenURL(url);
                    }
                })
                .catch(error => { // Error handling });
        }
    };

handleOpenURL = (url) => {
   // your navigation logic goes here 
}

Notes: 
-> Linking.getInitialURL() method should only be called for the first time when the app is launched via app-swap
-> For subsequent app-swap calls, handleOpenURL() method will be called as it is configured with linking event listener. 
-> remember to unsubscribe linking events in componentwillunmount()

**Comment by RZulfikri** [comment]
after investigation, I found the solution, add this code in your AppDelegate.m

```
#import "RCTLinkingManager.h"
...
- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
            options:(NSDictionary<NSString *, id> *)options {
  return [RCTLinkingManager application:application openURL:url options:options];
}
```

reference: https://v5.rnfirebase.io/docs/v5.x.x/links/ios

**Comment by rsmelo92** [comment]
@joaocac Have you figured it out? I'm having the same problem!

**Comment by devanshu23598** [comment]
Facing the same issue on android.

**Comment by RZulfikri** [comment]
@devanshu23598 

try to add this code below in you `MainActivity.java`
```java
  import android.content.Intent;
  import android.net.Uri;
  import com.facebook.react.bridge.Arguments;
  import com.facebook.react.bridge.WritableMap;
  import com.facebook.react.modules.core.DeviceEventManagerModule;
  ...
  @Override
  public void onNewIntent(Intent intent) {
      if (intent.getData() != null) {
        Uri deepLinkURL = intent.getData();
        // note deeplink_identifier means the identity that you register in the manifest.
        if (deepLinkURL.toString().contains("deeplink_identifier")) {
            // Create map for params
            WritableMap event = Arguments.createMap();
            // Put data to map
            event.putString("url", deepLinkURL.toString());
            // Get EventEmitter from context and send event thanks to it
            getReactInstanceManager().getCurrentReactContext()
                    .getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter.class)
                    .emit("url", event);
        }
      }
  }

```

**Comment by devanshu23598** [comment]
@RZulfikri Thank you for your response!!
I added the code in MainActivity.java and it works fine when running through terminal. I want to open the app through web browser. That not work.

**Comment by rsmelo92** [comment]
In case anyone is still having problems fixed it here:
https://github.com/facebook/react-native/issues/25675#issuecomment-618690451

**Comment by nHiRanZ** [comment]
> after investigation, I found the solution, add this code in your AppDelegate.m
> 
> ```
> #import "RCTLinkingManager.h"
> ...
> - (BOOL)application:(UIApplication *)application
>             openURL:(NSURL *)url
>             options:(NSDictionary<NSString *, id> *)options {
>   return [RCTLinkingManager application:application openURL:url options:options];
> }
> ```
> 
> reference: https://v5.rnfirebase.io/docs/v5.x.x/links/ios

Thanks, this worked on RN 0.62.2. Can someone explain what this code bit did?

**Comment by lyudad** [comment]
I have same issue with react native 0.61

**Comment by AmmiWang** [comment]
> Pls try this.
> componentDidMount() {
> Linking.addEventListener("url", this.handleOpenURL);
> this.handleDeepLinkingRequests();
> }
> handleDeepLinkingRequests = () => {
> Linking.getInitialURL()
> .then(url => {
> if (url) {
> this.handleOpenURL(url);
> }
> })
> .catch(error => { // Error handling });
> }
> };
> 
> handleOpenURL = (url) => {
> // your navigation logic goes here
> }
> 
> Notes:
> -> Linking.getInitialURL() method should only be called for the first time when the app is launched via app-swap
> -> For subsequent app-swap calls, handleOpenURL() method will be called as it is configured with linking event listener.
> -> remember to unsubscribe linking events in componentwillunmount()

However this didn't work for me.

**Comment by shubhamt2** [comment]
Facing same issue 0.62.0

**Comment by CoryWritesCode** [comment]
Same issue, seems like `Linking.getInitalURL()` works if the app is not yet launched, and `Linking.addEventListener('url' callback)` works if the app is in foreground but neither seem to work for apps in background state.

**Comment by mhavid** [comment]
//Add Listener to catch a state

componentDidMount() {
  Linking.addEventListener('url', this._handleOpenURL);
},
componentWillUnmount() {
  Linking.removeEventListener('url', this._handleOpenURL);
},
_handleOpenURL(event) {
  console.log(event.url);
}

**Comment by Ovidiu-S** [comment]
Is there an update on this issue ? Deep linking is an important feature, and this issue makes it pretty much unusable

**Comment by Ovidiu-S** [comment]
So, apparently, it works just fine if you turn off the debugger

**Comment by eduinlight** [comment]
I give you my hook that works grate on android and IOS for both Andoid and IOS.

`import {useEffect, useCallback} from 'react';
import {Linking} from 'react-native';
import useAppState from './useAppState';

const useDeepLink = (callback: (url: string) => void) => {
  const appState = useAppState();

  const handleDeepLink = useCallback(
    link => {
      if (link) {
        const url = typeof link === 'string' ? link : link.url;
        console.log({deeplink: url});

        callback(url);
      }
    },
    [callback],
  );

  useEffect(() => {
    if (appState === 'background') {
      Linking.getInitialURL().then(handleDeepLink);
    }
  }, [appState, handleDeepLink]);

  useEffect(() => {
    Linking.getInitialURL().then(handleDeepLink);

    Linking.addListener('url', handleDeepLink);

    return () => {
      Linking.removeEventListener('url', handleDeepLink);
    };
  }, [handleDeepLink]);
};

export default useDeepLink;
`

**Comment by brianmak3** [comment]
This worked for me for both background and foreground
`import React, { useEffect, useCallback, useRef, Fragment } from 'react';
import { Linking, AppState } from 'react-native';

const useDeepLink = (props) => {
    const appState = useRef(AppState.currentState),
        { callback } = props,
        handleDeepLink = useCallback(
            link => {
                if (link) {
                    const url = typeof link === 'string' ? link : link.url;
                    callback(url);
                }
            },
            [],
        );

    useEffect(() => {
        if (appState === 'background') {
            Linking.getInitialURL().then(handleDeepLink);
        }
    }, [appState, handleDeepLink]);

    useEffect(() => {
        Linking.getInitialURL().then(handleDeepLink);

        Linking.addListener('url', handleDeepLink);

        return () => {
            Linking.removeEventListener('url', handleDeepLink);
        };
    }, [handleDeepLink]);
    return (
        <Fragment />
    )
};

export default useDeepLink;`

**Comment by i-sbaral** [comment]
> Does anyone can solve keep getting the old url instead of latest url issue?

Hi @Kingsace Were you able to solve this issue by any chance? I am facing the same issue where Linking.getInitialUrl() gets a older url on some samsung devices.

**Comment by eduinlight** [comment]
I suggest you that follow the rn-firebase guide to do it right. I do that and my hook ends as follow:
const useDeepLink = (callback: (url: string) => void) => {
  const handleDynamicLink = useCallback(
    (link: any) => {
      console.log({link});
      if (link && link.url) {
        callback(link.url);
      }
    },
    [callback],
  );

  useEffect(() => {
    dynamicLinks()
      .getInitialLink()
      .then(handleDynamicLink);

    const unsubscribe = dynamicLinks().onLink(handleDynamicLink);

    return () => unsubscribe();
  }, [handleDynamicLink]);
};

**Comment by eduinlight** [comment]
Look again I post my end solution that work's greate. you need to follow
the guide trust in me when you do it right it works.

**Comment by Invertisment** [comment]
> are you added
> 
> ```
> <activity
>   android:name=".MainActivity"
>   android:launchMode="singleTask">
> ```
> 
> in AndroidManifest.xml ?
> (https://facebook.github.io/react-native/docs/linking)

Even if I'd add this to my Manifest, they say that this is only needed if I want to have only one activity instance. It's fine to have multiple activity instances in some cases. So it's not the issue, I think.

**Comment by anastely** [comment]
> I give you my hook that works grate on Android and IOS.
> 
> ```
> import {useEffect, useCallback} from 'react';
> import {Linking} from 'react-native';
> import useAppState from './useAppState';
> 
> const useDeepLink = (callback: (url: string) => void) => {
>   const appState = useAppState();
> 
>   const handleDeepLink = useCallback(
>     link => {
>       if (link) {
>         const url = typeof link === 'string' ? link : link.url;
>         console.log({deeplink: url});
> 
>         callback(url);
>       }
>     },
>     [callback],
>   );
> 
>   useEffect(() => {
>     if (appState === 'background') {
>       Linking.getInitialURL().then(handleDeepLink);
>     }
>   }, [appState, handleDeepLink]);
> 
>   useEffect(() => {
>     Linking.getInitialURL().then(handleDeepLink);
> 
>     Linking.addListener('url', handleDeepLink);
> 
>     return () => {
>       Linking.removeEventListener('url', handleDeepLink);
>     };
>   }, [handleDeepLink]);
> };
> 
> export default useDeepLink;
> ```



> I give you my hook that works grate on Android and IOS.
> 
> ```
> import {useEffect, useCallback} from 'react';
> import {Linking} from 'react-native';
> import useAppState from './useAppState';
> 
> const useDeepLink = (callback: (url: string) => void) => {
>   const appState = useAppState();
> 
>   const handleDeepLink = useCallback(
>     link => {
>       if (link) {
>         const url = typeof link === 'string' ? link : link.url;
>         console.log({deeplink: url});
> 
>         callback(url);
>       }
>     },
>     [callback],
>   );
> 
>   useEffect(() => {
>     if (appState === 'background') {
>       Linking.getInitialURL().then(handleDeepLink);
>     }
>   }, [appState, handleDeepLink]);
> 
>   useEffect(() => {
>     Linking.getInitialURL().then(handleDeepLink);
> 
>     Linking.addListener('url', handleDeepLink);
> 
>     return () => {
>       Linking.removeEventListener('url', handleDeepLink);
>     };
>   }, [handleDeepLink]);
> };
> 
> export default useDeepLink;
> ```

This hook works well in iOS but in android, i have some wired issue,
it returns the prev deep link!

when I run `npx uri-scheme open mydomainapp://products/76 --android` at the first time
it logs  `../76` 
if I change it to `npx uri-scheme open mydomainapp://products/77 --android`
it logs first `../76` then `../77` 
so in my case will get the product id `76` Not the expected `77`

iOS works as expected 
```
../76 => ../76 
../77 => ../77
```
Do u have any explanation for this issue? thanks

**Comment by anastely** [comment]
> I give you my hook that works grate on Android and IOS.
> 
> ```
> import {useEffect, useCallback} from 'react';
> import {Linking} from 'react-native';
> import useAppState from './useAppState';
> 
> const useDeepLink = (callback: (url: string) => void) => {
>   const appState = useAppState();
> 
>   const handleDeepLink = useCallback(
>     link => {
>       if (link) {
>         const url = typeof link === 'string' ? link : link.url;
>         console.log({deeplink: url});
> 
>         callback(url);
>       }
>     },
>     [callback],
>   );
> 
>   useEffect(() => {
>     if (appState === 'background') {
>       Linking.getInitialURL().then(handleDeepLink);
>     }
>   }, [appState, handleDeepLink]);
> 
>   useEffect(() => {
>     Linking.getInitialURL().then(handleDeepLink);
> 
>     Linking.addListener('url', handleDeepLink);
> 
>     return () => {
>       Linking.removeEventListener('url', handleDeepLink);
>     };
>   }, [handleDeepLink]);
> };
> 
> export default useDeepLink;
> ```

Can you please explain why this hook works?

**Comment by Amol-B-Patil** [comment]
Hello Everyone! 

The deep linking is working as expected for me even the app is in `background`. Please check the below specifications.

> Node Version : v12.18.x **OR Greater**
> NPM Version : v6.14.x **OR Greater**
> react-native-cli : 2.0.1 
> react-native : 0.63.x **OR Greater**

Please check if you have added below code in your `AppDelegate.m` which is responsible for deep linking.

> \- (BOOL)application:(UIApplication *)application
> openURL:(NSURL *)url
> options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
>    {
> return [RCTLinkingManager application:application openURL:url options:options];
> }

It will work for app cold boot, but it will not work if your app is in `background`. For this, you need to add below code in your `AppDelegate.m`

> \- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(nonnull void (^)(NSArray<id<UIUserActivityRestoring>> *_Nullable))restorationHandler {
>   return [RCTLinkingManager application:application
>                    continueUserActivity:userActivity
>                      restorationHandler:restorationHandler];
> }

This should work irrespective of your AppState: `active **OR** background`.

This worked for me as expected! Give it a try. This is should definitely work.

Thanks in advance!

**Comment by saranya20-t** [comment]
> @devanshu23598
> 
> try to add this code below in you `MainActivity.java`
> 
> ```java
>   import android.content.Intent;
>   import android.net.Uri;
>   import com.facebook.react.bridge.Arguments;
>   import com.facebook.react.bridge.WritableMap;
>   import com.facebook.react.modules.core.DeviceEventManagerModule;
>   ...
>   @Override
>   public void onNewIntent(Intent intent) {
>       if (intent.getData() != null) {
>         Uri deepLinkURL = intent.getData();
>         // note deeplink_identifier means the identity that you register in the manifest.
>         if (deepLinkURL.toString().contains("deeplink_identifier")) {
>             // Create map for params
>             WritableMap event = Arguments.createMap();
>             // Put data to map
>             event.putString("url", deepLinkURL.toString());
>             // Get EventEmitter from context and send event thanks to it
>             getReactInstanceManager().getCurrentReactContext()
>                     .getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter.class)
>                     .emit("url", event);
>         } else {
>            // to handle other deeplink that not related to the defined deeplink identifier such as notification
>            setIntent(intent);
>         }
>       } 
>   }
> ```

I get an error as "Cannot resolve method getReactInstanceManager". Can you please help me to fix this issue?

**Comment by rviteri** [comment]
For the ones that have this problem in iOS when the app is in the background (so not a cold start), my problem was that Firebase was overriding the continueUserActivity call with its own inside the GLUAppDelegateSwizzler.m. The way I fixed it was by adding this to the info.plist file:
```
<key>FirebaseAppDelegateProxyEnabled</key>
<false/>
```

**Comment by SamanthaChhoeu** [comment]
> > Does anyone can solve keep getting the old url instead of latest url issue?
> 
> Hi @Kingsace Were you able to solve this issue by any chance? I am facing the same issue where Linking.getInitialUrl() gets a older url on some samsung devices.

We are experiencing this issue on `react-native 0.63.4`

**Comment by zainwebhr** [comment]
Turning off the debugger worked for me.

**Comment by xilin** [comment]
> For the ones that have this problem in iOS when the app is in the background (so not a cold start), my problem was that Firebase was overriding the continueUserActivity call with its own inside the GLUAppDelegateSwizzler.m. The way I fixed it was by adding this to the info.plist file:
> 
> ```
> <key>FirebaseAppDelegateProxyEnabled</key>
> <false/>
> ```

For anyone who is interested in the swizzler, its correct filename is `GULAppDelegateSwizzler.m`

**Comment by H4mxa** [comment]
Facing the same issue only on android 12, any updates?

**Comment by git-sparrow** [comment]
Facing the same issue on Android.
The disabling debugger doesn't help.
The suggestion to access the URL with AppState & Linking.getInitialURL() doesn't help either.

**Comment by velancio** [comment]
Piggy backing on @RZulfikri suggestion for android I just had to add:
```
 @Override
  public void onNewIntent(Intent intent) {
    setIntent(intent);
  }

```

in the MainActivity.java

And handle deep linking in the app's root component:

```
import React, { useState, useEffect } from 'react';
import { AppState, Linking } from 'react-native';

const DeepLinkHandler = () => {
  const [appState, setAppState] = useState(AppState.currentState);

  const handleAppStateChange = nextAppState => {
    if (
      appState.match(/inactive|background/) &&
      nextAppState === 'active'
    ) {
      // app has come to the foreground
      Linking.getInitialURL().then(url => {
        // handle the deep link
      });
    }
    setAppState(nextAppState);
  };

  useEffect(() => {
    AppState.addEventListener('change', handleAppStateChange);

    return () => {
      AppState.removeEventListener('change', handleAppStateChange);
    };
  }, []);

  return null;
};

export default DeepLinkHandler;

```
This worked for me!!

**Comment by neel-turbo** [comment]
=======>>>Method to catch Deep link when App opens <<<=======
useEffect(() => {
    // Get the deep link used to open the app 
    const getUrl = async () => {
      const universalLink = await Linking.getInitialURL();

      if (universalLink === null) {
        return;
      }
      //handle universal link
      if (universalLink.includes('loginsuccess')) {
        console.log('INSIDE-------loginsuccess--useEffect---One');
        Alert.alert(initialUrl);
      }
    };

    getUrl();
  },[]);

=======>>>Method to catch Deep link  when App is In Background <<<=======

  useEffect(() => {

    const urlListener = Linking.addEventListener('url', (url: object) => {
      // console.log('this is the url---2: ', url.url);

      let urlString = JSON.stringify(url.url);

      if (urlString === null) {
        return;
      }

      if (urlString.includes('loginsuccess')) {
        Alert.alert(urlString);
        
      }
      // Alert.alert(JSON.stringify(url));
      console.log('INSIDE-------loginsuccess----useEffect---Two');
    });

    return () => {
      urlListener.remove();
    };
  }, []);

**Comment by abreuthrj-coclub** [comment]
> @devanshu23598
> 
> try to add this code below in you `MainActivity.java`
> 
> ```java
>   import android.content.Intent;
>   import android.net.Uri;
>   import com.facebook.react.bridge.Arguments;
>   import com.facebook.react.bridge.WritableMap;
>   import com.facebook.react.modules.core.DeviceEventManagerModule;
>   ...
>   @Override
>   public void onNewIntent(Intent intent) {
>       if (intent.getData() != null) {
>         Uri deepLinkURL = intent.getData();
>         // note deeplink_identifier means the identity that you register in the manifest.
>         if (deepLinkURL.toString().contains("deeplink_identifier")) {
>             // Create map for params
>             WritableMap event = Arguments.createMap();
>             // Put data to map
>             event.putString("url", deepLinkURL.toString());
>             // Get EventEmitter from context and send event thanks to it
>             getReactInstanceManager().getCurrentReactContext()
>                     .getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter.class)
>                     .emit("url", event);
>         } else {
>            // to handle other deeplink that not related to the defined deeplink identifier such as notification
>            setIntent(intent);
>         }
>       } 
>   }
> ```

This saved me! Thx
