### ISSUE TITLE
☂️ Fix annoying Android and iOS issues

### ISSUE THREAD

**Issue by cpojer** [facebook/react-native#24626]
## 🐛 Bug Report

Through https://github.com/react-native-community/discussions-and-proposals/issues/104 and https://github.com/react-native-community/discussions-and-proposals/issues/69 we learned about a lot of issues that people pointed out about React Native (cc @slorber @noahtallen @alburdette619). While we addressed many, there are still many issues remaining that need to be validated and if they still persist, fixed.

If you'd like to work on any of these, please comment here to sign up for one of them and send a Pull Request with a fix!

* [x] Using `style={{width: "100"}}` and forgetting the %
* [x] Toggling secureTextEntry has been broken for years
* [x] https://twitter.com/estevao_lucas/status/1117572702083190785?s=215 
* [ ] On Android, you cannot name a property flex or the app will crash
* [ ] Animated translate errors: https://github.com/react-native-community/discussions-and-proposals/issues/69#issuecomment-450532964
* [ ] Issues with Animated.View: https://github.com/react-native-community/discussions-and-proposals/issues/69#issuecomment-482885975
* [ ] Unhelpful error message with ScrollViews. See https://twitter.com/jlongster/status/1123225841075392514

Thank you :)

**Comment by guhungry** [comment]
One of the toggle secureTextEntry issue(s) was addressed in https://github.com/facebook/react-native/pull/23524

**Comment by sasurau4** [comment]
I want to work on `style={{ width: "100" }}` and forgetting the % issue.
I have a plan that fix the issue by translate `style={{ width: "100"}}` to `style={{ width: "100%" }}` automatically with warning rather than error.
Is the plan good? If not, please tell me other plans :pray:

**Comment by cpojer** [comment]
@sasurau4: give it a try! I’ll wait for your pull request. I think just making sure the app doesn’t crash and shows a useful error message is a good start!

**Comment by ahmedu007** [comment]
I can give the 3rd issue a go. *On Android, you cannot name a property flex or the app will crash*

Can I get a bit of context, and then I can start digging into it

**Comment by matheusmonte** [comment]
Can work in "On Android, you cannot name a property flex or the app will crash" ?

@cpojer

**Comment by cpojer** [comment]
Hey @matheusmonte, give it a try! Unfortunately I don't have more context myself but maybe @alburdette619 (who mentioned this initially) can provide a repro?

**Comment by zhongwuzw** [comment]
> https://twitter.com/estevao_lucas/status/1117572702083190785?s=215

@cpojer I'll enhance the compatible for this error.

**Comment by bryankang** [comment]
@sasurau4 @cpojer I don't know how I feel about automatically converting `width: "100"` to `width: "100%"` automatically. I think that it adds a bit of unwanted magic and potentially lead to hard to find bugs. 

I personally make sure to always wrap the percentage values in quotes, as do most people, so I think this feature is unnecessary.

**Comment by cpojer** [comment]
@zhongwuzw thank you!

@bryankang I agree with you. We shouldn't automatically convert, but we should make sure that the app doesn't crash and instead make sure we show a redbox error or something. The initial report said that the app crashes. If it already shows an error, we can make sure that it is more useful and if it already shows a proper redbox error we don't need to make a change.

**Comment by elucaswork** [comment]
> @bryankang I agree with you. We shouldn't automatically convert, but we should make sure that the app doesn't crash and instead make sure we show a redbox error or something. The initial report said that the app crashes. If it already shows an error, we can make sure that it is more useful and if it already shows a proper redbox error we don't need to make a change.

@cpojer @bryankang I just made a PR for it, https://github.com/facebook/react-native/pull/24659. The propose is just to ignore any unexpected value. No error will show up. (AFAIK any error will cause the app to crash in release mode). Let me know what you guys think. 

@sasurau4 sorry, I noticed just after I submitted this PR that you volunteered to fix it. My bad. :-(

**Comment by sasurau4** [comment]
@elucaswork Never mind! :+1: 

@bryankang  @cpojer I agree with you about automatically convert may cause something confusing. 
According to the #24659, the way to fix this issue is invoke yellow box warning and ignore the invalid value like `100`. I think it's better solution rather than my proposal of auto conversion.

**Comment by cpojer** [comment]
I just added a new item by @jlongster which is about fixing an annoying crash, see https://twitter.com/jlongster/status/1123225841075392514 Feel free to sign up for it and propose a PR with a fix!

**Comment by matheusmonte** [comment]
Can I try "Unhelpful error message with ScrollViews. See " @cpojer

**Comment by cpojer** [comment]
Go for it!

________________________________
