### ISSUE TITLE
Images Component need HTTPS for render image

### ISSUE THREAD

**Issue by xgqfrms** [facebook/react-native#24621]
## 🐛 Bug Report

> Images Component need HTTPS for render image

https://github.com/facebook/react-native/edit/0.51-stable/docs/MoviesExample.json

```json
{
      "posters": {
        "thumbnail": "http://resizing.flixster.com/DeLpPTAwX3O2LszOpeaMHjbzuAw=/53x77/dkpu1ddg7pbsk.cloudfront.net/movie/11/16/47/11164719_ori.jpg",
        "profile": "http://resizing.flixster.com/DeLpPTAwX3O2LszOpeaMHjbzuAw=/53x77/dkpu1ddg7pbsk.cloudfront.net/movie/11/16/47/11164719_ori.jpg",
        "detailed": "http://resizing.flixster.com/DeLpPTAwX3O2LszOpeaMHjbzuAw=/53x77/dkpu1ddg7pbsk.cloudfront.net/movie/11/16/47/11164719_ori.jpg",
        "original": "http://resizing.flixster.com/DeLpPTAwX3O2LszOpeaMHjbzuAw=/53x77/dkpu1ddg7pbsk.cloudfront.net/movie/11/16/47/11164719_ori.jpg"
      }
}
```

> wanted

https://cdn.xgqfrms.xyz/json/react-native/MoviesExample.json

![image](https://user-images.githubusercontent.com/7291672/56799319-4b7f9880-684b-11e9-93eb-15344f32b91b.png)

**Comment by hey99xx** [comment]
Movies example is deleted from RN. You're looking at an old version. It was removed sometime between 0.51 and 0.52: https://github.com/facebook/react-native/compare/0.51-stable...0.52-stable#diff-a73a14d647d5132e0074c9e4474cc5a8

**Comment by xgqfrms** [comment]
@hey99xx Anyway, Thanks a lot!
