### ISSUE TITLE
accessibility API bug 

### ISSUE THREAD

**Issue by adil-s** [facebook/react-native#24632]
Hi there,
when I set the accessibilityRole ={"button"} to any button, talk back says "button submit". but that is not expected behavior.
instead of, talk back should say, "submit button, double tap to activate" 
to make things worse, talk back doesn't recognized unless I set the accessibilityRole={"button"}.
however, I could just set the accessibilityLabel ={"submit button, double tap to activate"}. but it is not elegant solution because screen reader hints differs from one screen reader to another, I mean, it is not cross platform solution. 
the another issue that I have come across is, the talkback doesn't read the accessiblityHints. 
I. E. 
<Button accessibilityHints ={"double tap to activate"}
  accessibilityRole={"button"}
  title ={"submit"}
  />
for above example, talkback would announce, "button submit".
leaving out the accessibility hints and announcing the control in nonstandard manner. 

there are no accessibilityRole for drop down (combobox), spin editor etc. could you please add some more accessibilityRoles?

while creating material bottum tabBar,
every tab is being announced as selected, but they are not. 

here is the code:
import React, { Component } from 'react';
import {Alert, AppRegistry,StyleSheet, TextInput, View, Text} from 'react-native';
import { Button } from 'react-native-elements';
import Icon from 'react-native-vector-icons/MaterialIcons';
import { createMaterialBottomTabNavigator } from "react-navigation-material-bottom-tabs";
import { createAppContainer, createStackNavigator } from 'react-navigation';

class Album extends Component {
  render (){
    return(
    <View> 
      <Text accessibilityRole ={"text"}> album here </Text>
      <Button 
      onPress={() => this.props.navigation.navigate("Library")}
      title={"go to library"}
      accessibilityLabel={"go to library, button"}
      
     />
    </View>
    )
  }
}

class Library extends Component{
  render () {
    return(
    <View> 
      <Text accessibilityRole={"text"}> your library here </Text>
    </View>
    )
  }
}

class Cart extends Component{
  render () {
    return (
      <View>
        <Text accessibilityRole={"text"}> your carts here </Text>
      </View>
    )
  }
}

class History extends Component{
  render(){
    return (
      <View> 
        <Text accessibilityRole={"text"}> history here </Text>
      </View>
    )
  }
}

const Tabs =  createMaterialBottomTabNavigator({
  Album: { screen: Album },
  Library: { screen: Library },
  History: { screen: History },
  Cart: { screen: Cart },
}, {
  initialRouteName: 'Album',
  activeColor: '#f0edf6',
  inactiveColor: '#3e2465',
  barStyle: { backgroundColor: '#694fad' },
});

const AppNavigator = createStackNavigator({
  Album: {
    screen: Album
  },
  Library:{
    screen:Library
  }
});

const App = createAppContainer(Tabs);
export default App;

**Comment by jaysbytes** [comment]
Can you please improve code formatting in the issue. It's very hard to read. Find a reference [here](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting)
