### ISSUE TITLE
[DevMenu] 'Debug in Safari' crashes

### ISSUE THREAD

**Issue by gauravmc** [facebook/react-native#2464]
This happens every time I try to build:

![image](https://cloud.githubusercontent.com/assets/1014540/9524107/272c3fca-4cab-11e5-9531-1cf3b7934e51.png)
)

Last thing I did on the simulator was 'Debug in Safari', and now this won't go away even if I restart everything from scratch. Looks like Safari debugging is borked in 0.10.0.

Note: As a temporary fix I deleted the app from simulator and rebuilt it.

**Comment by brentvatne** [comment]
Is this working in 0.11-rc? cc @tadeuzagallo

**Comment by tadeuzagallo** [comment]
No, it's broken :(

I created a diff internally, should be on master soon.

**Comment by phatmann** [comment]
:+1:

**Comment by antigirl** [comment]
+1 what the hell
