### ISSUE TITLE
autoCorrect={false} bug

### ISSUE THREAD

**Issue by alex-ta** [facebook/react-native#24651]
## 🐛 Bug Report
Suggestions and Autocorrect is showing

## To Reproduce

style.Text:{
	  padding: 10,
	  width:'22%',
	  height:50,
	  marginTop: 30,
          marginLeft: 15,
	  fontSize: 25,
	  backgroundColor: 'transparent',
	  borderColor: 'transparent',
          borderWidth: 1
  }

<TextInput style = {styles.Text}
				   placeholder = "_ _ _"
				   autoCorrect={false}
				   placeholderTextColor = "#9a73ef"
				   autoCapitalize = {"characters"}
				   maxLength={3}
				   />

## Expected Behavior
Suggestions should not show

## Environment
    "react-native": "^0.59.5",

**Comment by dulmandakh** [comment]
what is your platform? iOS or Android?

**Comment by alex-ta** [comment]
Platform = Android

react-native info
info
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: x64 Intel(R) Core(TM) 
      Memory: 1.09 GB / 8 GB
    Binaries:
      Yarn: 1.15.2
      npm: 6.4.1
