### ISSUE TITLE
Convert Blob to turbomodules and remove the collector hack

### ISSUE THREAD

**Issue by janicduplessis** [facebook/react-native#24654]
https://github.com/facebook/react-native/pull/24405 implements a temporary workaround to fix blob deallocation memory leaks. We access the `jsi::Runtime` in an unsafe way. When turbomodules are ready we should be able to implement this cleanly and leverage `jsi::HostObject` lifecycles.

There are also a lot of opportunities for code sharing in c++ for this module.

We can discuss the implementation here

**Comment by ide** [comment]
TM would be great for the Blob API. I think a pretty clean way to do this is to add TypedArray support to JSI+TM and then build the Blob API in JS on top of TypedArrays as a nice way to share data between JS and native without serializing large byte arrays.
