### ISSUE TITLE
Text style not applied @ios when not alphabet characters are connected.

### ISSUE THREAD

**Issue by ken0x0a** [facebook/react-native#24667]
## 🐛 Bug Report

Text style not applied @ios when not alphabet characters are connected.
And also, it seem not working only `{ fontWeight: "500" }.
It works fine with `{ fontWeight: "600" } & `{ fontWeight: "900" } ( both example is in snack )

https://snack.expo.io/@plusuno/text-bug

Works as expected @android.

![Uploading IMG_0420.jpg…]()
![Simulator Screen Shot - iPhone 8 - 2019-05-01 at 07 01 51](https://user-images.githubusercontent.com/2770219/56996827-c3014f00-6be0-11e9-9fdc-67f0bd2d4342.png)
![IMG_0417](https://user-images.githubusercontent.com/2770219/56996828-c3014f00-6be0-11e9-93a3-62d928aceed9.PNG)

## To Reproduce
```sh
expo init
# select `blank`
```

Add following lines into `App.js`

```jsx
<Text>
  あ<Text style={{ fontWeight: '500' }}>あ</Text>
  あ<Text style={{ fontWeight: '500' }}>N</Text>
</Text>
```

### case 1
```jsx
<Text>
  あ<Text style={{ fontWeight: '500' }}>あ</Text>
  あ<Text style={{ fontWeight: '500' }}>N</Text>
</Text>
```
Should be 

あ**あ**あ**N**

but result is

あああN

### case 2

```jsx
<Text>
  あ<Text style={{ fontWeight: '500' }}> あ</Text>
  あ<Text style={{ fontWeight: '500' }}>N</Text>
</Text>
```
Should be 

あ **あ**あ**N**

but result is

あ **ああ**N

## Code Example
- https://snack.expo.io/@plusuno/text-bug
- https://github.com/ken0x0a/text-bug

## Environment
```
React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
      Memory: 1.01 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.7.0 - /var/folders/qb/k3d1vcb15zg8xwpysry3chwc0000gn/T/yarn--1556662254677-0.7769849723695972/node
      Yarn: 1.15.2 - /var/folders/qb/k3d1vcb15zg8xwpysry3chwc0000gn/T/yarn--1556662254677-0.7769849723695972/yarn
      npm: 6.5.0 - ~/.nvm/versions/node/v11.7.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 25, 26, 27
        Build Tools: 23.0.1, 25.0.1, 25.0.2, 26.0.2, 27.0.2, 27.0.3
        System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
```

**Comment by kelset** [comment]
👋 there - this seems to be an issue with Expo, so I'd suggest you open an issue over their repository: https://github.com/expo/expo

that said, in my experience this kind of issue is mostly related to the Font Family and how the platform "process" it. So it could be also a limitation of the font.
