### ISSUE TITLE
Discussion: react-devtools dependency still has PATENTS file

### ISSUE THREAD

**Issue by jwhitley** [facebook/react-native#24669]
The `react-devtools-core` dependency in package.json still has the PATENTS file, effectively meaning that React Native is still impacted by that.

## To Reproduce
Inspect the [react-devtools repo](https://github.com/facebook/react-devtools) and observe that it's still under the BSD 3-clause LICENSE and critically, still has the PATENTS file.

I've also scanned all Facebook dependencies of a clean React Native CLI install:

1. Install a sample React Native project via the current CLI: `react-native init TodoLicense`
2. Install license-checker: `npm i -h license-checker`
3. `license-checker --json > rn-licenses.json`
4. Install [`jq`](https://stedolan.github.io/jq/)
5. Run `jq '[.[] | select(.repository | tostring | contains("facebook")) | { (.repository): .licenses } ] | unique | add' rn-licenses.json`
6. Manually inspect the resulting repos.  I did this, and all are in the clear re: PATENTS except react-devtools.

## Expected Behavior

React Native is no longer (transitively!) affected by the PATENTS file clause.  I believe this was an oversight from the previous switch of React Native's own license.

The corresponding issue has been also been filed as facebook/react-devtools#1342

**Comment by cpojer** [comment]
Please bring this up on the react-devtools repo. We should be able to get it removed.
