### ISSUE TITLE
[compile error] No visible @interface for 'RCTRootView' declares... after upgrading to 11.0-rc

### ISSUE THREAD

**Issue by ms88privat** [facebook/react-native#2467]
AppDelegate.m:48:48: No visible @interface for 'RCTRootView' declares the selector 'initWithBundleURL:moduleName:launchOptions:'

I tried to clean my project and rebuild without success. I was on 10.0-rc before. Whats going on?

**Comment by ide** [comment]
The method signature changed.

**Comment by ms88privat** [comment]
@ide thx, but how to fix it? (yes, I started to learn objective-c already... :D)

**Comment by bnookala** [comment]
@ms88privat if you used the command line generator (running `react-native init MyProject` in a terminal), you can go into `AppDelegate.m`, and change the line that looks like:

```
  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"MyProject"
                                                   launchOptions:launchOptions];
```

to:

```
  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"MyProject"
                                                initialProperties:nil
                                                    launchOptions:launchOptions];
```

Same process if you didn't use the generator: find the .m file in which you create your `RCTRootView` and change the method signature.

**Comment by ms88privat** [comment]
@bnookala Thx, I figured this out right now :), but now i have two other errors:

AppnameTests.m:50:31: No known class method for selector 'sharedInstance'
and
AppnanameTests.m:50:47: No known instance method for selector 'currentErrorMessage'

**Comment by ms88privat** [comment]
So i comment the method out and it is working fine now

**Comment by oblador** [comment]
@ms88privat: Just remove the test target if you're not using it anyway.
