### ISSUE TITLE
Build failed. When i try to link react-native-maps to react-native app

### ISSUE THREAD

**Issue by zainshabir00** [facebook/react-native#24675]
When i install react-native-maps and link react-native-maps to my app, then i try to run app after linking it, my app stopped working, It's not running now, It's giving me the error in cmd. And when i un-linked react-native-maps then my app runs fine.

**Here is the code that I've implemented on my app to link react-native-maps:**

**android/app/build.gradle**

```
dependencies {
   ....
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation project(':react-native-maps')
}
```
**android/build.gradle**

```
buildscript {
    ext {
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.1'
    }
}
```
**android/settings.gradle**

```
ootProject.name = 'ComparePrices'
include ':react-native-maps'
project(':react-native-maps').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-maps/lib/android')

include ':app'
```
**android/app/src/main/java/com/compareprices**

```
import com.airbnb.android.react.maps.MapsPackage;
...
@Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
            new MainReactPackage(),
            new LinearGradientPackage(),
            new RNGestureHandlerPackage(),
            new VectorIconsPackage(),
            new MapsPackage()
      );
    }
```
**android/gradle/wrapper/gradle-wrapper.properties**

```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip
```
**android/app/src/main/AndroidManifest.xml**

```
<application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <meta-data
     android:name="com.google.android.geo.API_KEY" />
    </application>
```

here is the error with screenshot:

![image](https://user-images.githubusercontent.com/48385304/57016481-ceca3100-6c33-11e9-9d8b-134b031f63c2.png)

```
> Task :app:transformClassesWithDexBuilderForDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\Users\zains\.gradle\caches\transforms-1\files-1.1\firebase-analytics-impl-11.8.0.aar\5f122df5deada8f908914f5bd04e05ad\jars\classes.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 38s
117 actionable tasks: 1 executed, 116 up-to-date
error Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
error Command failed: gradlew.bat app:installDebug. Run CLI with --verbose flag for more details.
```

and here is the react-native info:

```
info
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i5-3340M CPU @ 2.70GHz
      Memory: 853.02 MB / 7.87 GB
    Binaries:
      npm: 6.7.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5314842
```

Can you help me with this?

**Comment by zainshabir00** [comment]
> Can you run `react-native info` and edit your issue to include these results under the **Environment** section?
> 
> If you believe this information is irrelevant to the reported issue, you may write `[skip envinfo]` alongside an explanation in your Environment: section.

Yes sir, I have updated issue with the results of `react-native info`

**Comment by zainshabir00** [comment]
> Can you run `react-native info` and edit your issue to include these results under the **Environment** section?

Sir can you help me with this? It's been 2 days i didn't get any solution from any person.

**Comment by VladyslavKochetkov** [comment]
Shouldn't you be running `react-native link react-native-maps` instead? Also `react-native-maps` does have some other configuration you may have to do depending on your platform and use cases

**Comment by zainshabir00** [comment]
> Shouldn't you be running `react-native link react-native-maps` instead? Also `react-native-maps` does have some other configuration you may have to do depending on your platform and use cases

`react-native link react-native-maps`, It's also not working, So there was method to link manually so i linked it manually but still getting error, If i unlink react-native-maps then my app runs fine, otherwise app is not running, Build failed, I am updating issue with the code that i have implemented manually. you can check

**Comment by matt-oakes** [comment]
@zainshabir00 You have only posted the bottom half of the error message. Can you post the full stack track above the error you reported?

Also, this is likely to be an issue with the way you have linked React Native Maps, not an issue with React Native itself. You should take a look at the issues over there:

https://github.com/react-native-community/react-native-maps/issues

**Comment by satya164** [comment]
Closing because of no response.

**Comment by elijahmurray** [comment]
You need to upgrade your minSDKVersion to bee 26 if you want to use multidex

Change your build.gradle from this

```
buildscript {
    ext {
        minSdkVersion = 16
…
          }
}
```
to this: 

```
buildscript {
    ext {
        minSdkVersion = 26
…
          }
}
```
