### ISSUE TITLE
Image is not rendering on some 

### ISSUE THREAD

**Issue by radjivF** [facebook/react-native#24670]
## 🐛 Bug Report
the image component doesn't render the image on all version of ios 11 and 12

## To Reproduce
Render a list of images thought https 

this way: 

```js
<Image
   resizeMode="contain"
   style={{ width: '100%', height: 250 }}
   source={{ uri: `https://{image}` }}
/>
```

I have added the subdomain to info.plist, it also appears to work on the simulator iphone 8 but not iphoneX and on real devices too

## Expected Behavior
it should render the images

## Code Example

```js
<Image
   resizeMode="contain"
   style={{ width: '100%', height: 250 }}
   source={{ uri: `${getSite()}${image}` }}
/>
```

## Environment

Environment:
  OS: macOS 10.14.3
  Node: 10.15.0
  Yarn: Not Found
  npm: 6.4.1
  Watchman: 4.9.0
  Xcode: Xcode 10.1 Build version 10B61
  Android Studio: 3.2 AI-181.5540.7.32.5056338

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

I think its a bug but if someone has a solution I will be happy to take it.

![image](https://user-images.githubusercontent.com/5714138/57005814-2f8e4500-6c05-11e9-825f-0ce86e2922fa.png)

**Comment by zhigang1992** [comment]
Is it working in Safari opening the image? Is the allowarbitraryload enabled in info.plist?
