### ISSUE TITLE
[Image & Borders] borderRadius image

### ISSUE THREAD

**Issue by RWOverdijk** [facebook/react-native#2468]
~~Image components appear to ignore of the borderBottomRightRadius and such properties whenever a borderRadius gets set. It will use the value of borderRadius over the specific ones.~~

Image components ignore specific style properties for borderRadius, such as borderBottomRightRadius. borderRadius itself __does__ work.

**Comment by RWOverdijk** [comment]
Sorry for not giving this the right title.. :)

**Comment by brentvatne** [comment]
no problem @RWOverdijk - I probably would have changed it anyways because I'm weird like that

**Comment by ErikPettersson** [comment]
Is there any known workaround for this? (seeing how Views with overflow: 'hidden' doesn't take border radius into consideration)

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/image-borders-borderradius-image

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is focused on performance.

**Comment by nabn** [comment]
Managed to work around this by containing the image inside a `View`, giving the `View` the specific radii and writing `overflow: 'hidden'` for the enclosing `View`

**Comment by viix** [comment]
@nabn seemed better to set borderRadius to both View and Image will work, on my android device, but still not perfect

**Comment by BabuinGH** [comment]
followed @nabn and additionally set borderRadius as parameter instead of style.
          <Image
            source={{uri: Url}}
            resizeMode='cover'
            borderRadius={5}
            style={styles.organizationImage}
          >

**Comment by joshuapinter** [comment]
@BabuinGH  What do you mean by `parameter`? Do you mean a prop on the `Image` component like: 

`<Image borderRadius={5} ... />`

**Comment by joshuapinter** [comment]
@BabuinGH Holy crap, you're right. That works. Whereas setting `borderRadius` in the `style` doesn't do anything. Why would that make a difference? How are they handled differently? That should be logged as a bug for sure.

**Comment by joshuapinter** [comment]
Okay, quick update. I have confirmed that the specific border radius attributes work as props as well, like `borderTopLeftRadius`, `borderTopRightRadius`, etc.

I have also found that if you set a `backgroundColor` style on the Image (maybe before the image is fully loaded) the backgroundColor does not respect the `borderRadius` when set on the props of the `<Image .../>` component. However, when you set the `borderRadius` as a style on the `<Image .../>` component, it works great. 

So, in summation: 

* `backgroundColor` respects the `borderRadius` _style_, but not the _prop_. 

* The actual image respects the `borderRadius` _prop_, but not the _style_.

Strange.

**Comment by paalex** [comment]
On Android RN0.35 none of the methods work. `backgroundColor` doesn't respect `borderRadius` style nor prop.
Anyone managed to make it work?

**Comment by paalex** [comment]
Managed to make it work on Android if I switch to `resizeMode={'cover'}`

**Comment by pwcremin** [comment]
None of these options are working on 0.42 ios

**Comment by gp3gp3gp3** [comment]
None of these are working for me in RN.042.  Just trying to get `borderTopRightRadius` and `BorderTopLeftRadius` on an image.  Wrapping in a View component with `border{x}Radius: y, overflow: 'hidden'` doesn't work, and neither does passing the image a `border{x}Radius` prop directly, although giving a `borderRadius` prop does.  This is just in iOS, not even approaching android yet.

**Comment by pwcremin** [comment]
@gp3gp3gp3  I have something like this:

```
<View style={{
            overflow: 'hidden',
            borderRadius: 10,
        }}>

 <.. your crap with a rounded border from the parent view />

</View>
```

Is that not working?

**Comment by pwcremin** [comment]
@gp3gp3gp3 
I just test and this is working for me:

```
<View
                        style={{
                            borderTopLeftRadius: 10,
                            borderTopRightRadius: 10,
                            overflow: 'hidden',
                            height: 205,
                        }}
                    >
     < your image crap with a rounded edge from the parent view />
</View>
```

This View is from shoutem/ui but I don't think it should matter

**Comment by MergimU** [comment]
For me overflow works only if I don't use any components inside the the <Image> component so basically
`<Image>
       <Text>Overflow won't work in this Image component, so the borderRadius does not take effect</Text>
</Image>`

`<View>
     <Image />
     <Text>This works Perfect</Text>
</View>`

**Comment by emrehayirci** [comment]
I have the same bug with @MergimU ? So how can i set a view that contains text with rounded background image

**Comment by MergimU** [comment]
@emrehayirci - Here's an example on android http://prntscr.com/f47wxt

**Comment by emrehayirci** [comment]
@MergimU thank you that is a nice work around !

**Comment by rborn** [comment]
I'm late to the party, but I found this way to have independent border radius on both platforms 😄 
https://snack.expo.io/BJfN38eXW

![screen shot 2017-06-15 at 21 14 41](https://user-images.githubusercontent.com/406409/27197770-ca54866a-520f-11e7-931b-caffd3eb665f.png)
![screen shot 2017-06-15 at 21 15 05](https://user-images.githubusercontent.com/406409/27197771-ca59dcfa-520f-11e7-9626-56a8037ec003.png)

**Comment by Liqiankun** [comment]
It works very well written like `<Image borderRadius={5} ... />`.
