### ISSUE TITLE
Wrong 'margin' behavior on iOS RN 0.59

### ISSUE THREAD

**Issue by serjiogunit** [facebook/react-native#24685]
## 🐛 Bug Report
Empty screen if some of component contains 'margin' value. Reproduces on simulator and real iPhone.
![Screen Shot 2019-05-02 at 12 36 56](https://user-images.githubusercontent.com/19323683/57067202-01793580-6cd7-11e9-8fd4-5c45b70fdbe4.png)

## To Reproduce
Add 'margin' to component

## Expected Behavior
Correct layout

## Code Example
```
import React, {Component} from 'react';
import {AppRegistry, Text, View} from 'react-native';

class TestApp extends Component {
  render() {
    return (
      <View style={{ flex: 1, justifyContent: "center", alignItems: "center" }}>
        <Text style={{marginTop: 50}}>Hello, world!</Text>
      </View>
    );
  }
}

AppRegistry.registerComponent('TestApp', () => TestApp);
```

## Environment
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (4) x64 Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz
      Memory: 33.70 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 9.8.0 - ~/.nvm/versions/node/v10.2.1/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.1.0 - ~/.nvm/versions/node/v10.2.1/bin/npm
      Watchman: 4.4.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.3, 27.0.0, 27.0.3, 28.0.1, 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.3 => 16.8.6
      react-native: ^0.59.6 => 0.59.6
    npmGlobalPackages:
      react-native-cookies: 3.3.0

**Comment by bobber205** [comment]
can you add a expo example?

**Comment by serjiogunit** [comment]
Here is my AppDelegate.m file
0.58.6 version works fine. 
0.59.0 has the same bug.

`/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"TestApp"
                                            initialProperties:nil];

  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end
`

**Comment by bobber205** [comment]
Can you try upgrading to the latest RN version?

**Comment by serjiogunit** [comment]
> Can you try upgrading to the latest RN version?

@bobber205 hello, yes. I tried all 0.59.X versions.

**Comment by passerbyloo** [comment]
I tried 0.59.8 version, iOS 12.1, iPhone XS, can not reproduce

**Comment by serjiogunit** [comment]
0.59.8 still contains this bug for me
