### ISSUE TITLE
Discussion: State doesnt change on then.. catch

### ISSUE THREAD

**Issue by Talkwondo** [facebook/react-native#24681]
When getting into callback function and I want to change the state, it does not happen, but if I console.log I see the changed state.

I tried to put the setState in the then and the catch. when I do that getting the same result.

the code:

axios({
   method: 'post',
   url: url,
   headers: {
     "Content-Type": "application/json"
   },
   timeout: 30000, // Wait for 30 seconds
   data: data
}).then((response) => {
    console.log(response);
    this.paymentSuccess()
}).catch(function(error) {
    console.log(error)
}).then( () =>{
    this.setState({
    pickerDisplayed: false,
    loading: false
    }, function() {
        console.log(this.state.loading)
        console.log(this.state.pickerDisplayed)
   })
});

**Comment by kelset** [comment]
👋 there - this issue seems more a question for [StackOverflow](https://stackoverflow.com/questions/tagged/react-native), as it's not really related to React Native the library in itself. If you think it is, can you provide a full repro? I'll happily reopen then!
