### ISSUE TITLE
Image disappeared and expo reboots when set borderRadious

### ISSUE THREAD

**Issue by caesar4321** [facebook/react-native#24696]
## 🐛 Bug Report

When I set borderRadious for an Image Component, the image disappears and the whole image is colored black. And Expo reboots automatically soon after. I was able to get around the error by making a wrap View for the image. The source is like below:

```
<View style={styles.avatarWrap}>
    <Image
        source={require('../../assets/flags/profileImage.png')}
        style={styles.avatar}
    />
</View>

const styles = StyleSheet.create({
  avatarWrap: {
    width: 200,
    height: 200,
    borderRadius: 100,
    overflow: 'hidden',
  },
  avatar: {
    flex: 1,
    width: undefined,
    height: undefined,
    resizeMode: 'cover',
  },
```
It works, but I have no idea why it does not work when I apply borderRadious directly to an Image component. It has to have a wrap View component to not make an error. I tried borderRadious: 40 and they started to appear again. But again, Image components disappear and Expo reboots when I render more than 7 Image components.

## Expected Behavior

An <Image> component shouldn't disappear (blackout) and expo shouldn't reboot suddenly.

## Environment

"dependencies": {
    "expo": "^32.0.0",
    "react": "16.5.0",
    "react-native": "0.57.1",
    "axios": "^0.18.0",
    "react-navigation": "^3.9.0"
  },

**Comment by caesar4321** [comment]
@react-native-bot  I did. The react version is "react-native": "0.57.1"

**Comment by zhigang1992** [comment]
Maybe it's a expo issue? Also you have a typo it's uri and not url

**Comment by caesar4321** [comment]
@zhigang1992 It turned out that it is because of borderRadious. I managed to work around it, but do not know the root cause... Let me edit the text.
