### ISSUE TITLE
PanResponder not working properly on Android when Animated.View has an Animated.ScrollView as a child

### ISSUE THREAD

**Issue by VanHoutte** [facebook/react-native#24691]
## 🐛 Bug Report
I have a an issue on Android with my pangesture.

I have an Animated.ScrollView inside my Animated.View. Whenever I drag my Animated.View slowly, it works perfectly but whenever I flick really quick, the Animated.View stops after a couple of pixels.

The bug doesn't happen when I disable the scroll on the Animated.ScrollView. My guess is that the Animated.ScrollView takes over when swiping too fast.

Anyone has an idea why this happens? This does not happen on iOS.

## To Reproduce
See the github project

## Expected Behavior
That the animation would not stop when swiping too fast

## Code Example
https://github.com/VanHoutte/ReactNativeAndroidPanGestureBug/tree/master

## Environment
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 34.73 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.16.0 - ~/.nvm/versions/node/v8.16.0/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.16.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 26.0.0, 26.0.3, 27.0.3, 28.0.3
        System Images: android-27 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: ^0.59.5 => 0.59.5 
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by smadey** [comment]
only android happen +1

**Comment by scottwio** [comment]
Same thing +1

**Comment by VanHoutte** [comment]
I was able to get it working with https://kmagiera.github.io/react-native-gesture-handler. I did had to rewrite the whole modal.
