### ISSUE TITLE
React-Native : Android versions to fetch HTTPS queries

### ISSUE THREAD

**Issue by NicolasSmit** [facebook/react-native#24698]
After upgrading RN to 0.58.6, I have some Android users reporting that the application keeps loading on 1st screen with the production apk. They have to wait for 2 minutes to see the 1st results.

With the development apk, no issue. The only difference between those is the backend url : on production we're using a SSL certificate, not on dev. So I tried to use HTTP queries instead of HTTPS, and it's working for those users, but some other now have the same issue. I've also tried to setup network_security_config or to add www in the backend url, and no success.

On Android 8.0 and 9.0, it seems that https queries are working, but not on Android 8.3
We also noticed that those https queries may fetch correctly on certain network wifi, but otherwise it takes ages to load. 

I'm not sure this is the issue, but here's the network_security_config
```<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <domain-config cleartextTrafficPermitted="true">
        <!-- For React Native Hot-reloading system -->
        <!-- If you are running on a device insert your computer IP -->
        <domain includeSubdomains="true">localhost</domain>
        <domain includeSubdomains="true">backendURL.com</domain>
        <domain includeSubdomains="true">dev.back.end.IP</domain>
        <domain includeSubdomains="true">prod.back.end.IP</domain>
        <trust-anchors>
            <certificates src="system" />
            <certificates src="user" />
        </trust-anchors>
    </domain-config>

    <base-config cleartextTrafficPermitted="false" />
</network-security-config>```

I don't want to implement the backend url depending on Android versions as I'm not sure at all this will be ok for all users. Anyone has an idea ?

**Comment by NicolasSmit** [comment]
It was an issue with DNS configuration : on some wifis, IPv6 is enabled, and the DNS wasn't responding correctly.

**Comment by ashokkumar88** [comment]
@NicolasSmit How did you solve it? I m facing same issue
