### ISSUE TITLE
Asset not found

### ISSUE THREAD

**Issue by akrasyuk** [facebook/react-native#24700]
## 🐛 Bug Report
  Image not seen when we have spaces in file name.
  Detailed error:
  ```
  Error: Asset not found: C:\projects\AwesomeProject\Images\img%20test.png for platform: 
  android
     at C:\projects\AwesomeProject\node_modules\metro\src\Assets.js:147:13
     at Generator.next (<anonymous>)
     at step (C:\projects\AwesomeProject\node_modules\metro\src\Assets.js:326:347)
     at C:\projects\AwesomeProject\node_modules\metro\src\Assets.js:326:507
  ```

## To Reproduce
Just render Image component with source for an image with spaces in name.

## Expected Behavior
Image should be rendered without errors.

## Code Example

link to github [example](https://github.com/akrasyuk/RNIssue)

## Environment

React Native Environment Info:
  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
    Memory: 4.18 GB / 23.88 GB
  Binaries:
    Yarn: 1.7.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

**Comment by kelset** [comment]
👋there
This seems to be an issue with Metro, which has a dedicated repo: https://github.com/facebook/metro/ so can you please open an issue there?

That said - in general, if possible, I'd suggest you to not have spaces (and other special simbols) in file names when it comes to development in general. That can lead to weird behaviours in the most incredible ways (of which, this is just one).

**Comment by Benzer1406** [comment]
Putting out the space of the file name fixed the issue for me. Thanks
