### ISSUE TITLE
Android Picker's onValueChange is not fired sometimes

### ISSUE THREAD

**Issue by renishdeveloper** [facebook/react-native#24708]
I am using the Picker.
All is working fine, but when I select the same value that I selected previously, the alert is not fired.
-->

## To Reproduce
 <Picker
            selectedValue={this.props.currentState.selectedValue}    //Selected value
              mode='dialog'
            prompt="Select language"
            style={styles.picker}
            enabled={true}
            onValueChange={(itemValue) =>
              this.onSelect(itemValue)
            }>

            <Picker.Item label="Java" value="Java" />
            <Picker.Item label="JavaScript" value="JavaScript" />
            <Picker.Item label="Python" value="Python" />
          </Picker>

  onSelect(value) {
    alert('Selected value are : ' + value);
    this.props.onSelect(value);
  }
-->

## Expected Behavior
I expect that the function must be called everytime I select the item, but not in my case.

## Code Example

 <Picker
            selectedValue={this.props.currentState.selectedValue}    //Selected value
              mode='dialog'
            prompt="Select language"
            style={styles.picker}
            enabled={true}
            onValueChange={(itemValue) =>
              this.onSelect(itemValue)
            }>

            <Picker.Item label="Java" value="Java" />
            <Picker.Item label="JavaScript" value="JavaScript" />
            <Picker.Item label="Python" value="Python" />
          </Picker>

  onSelect(value) {
    alert('Selected value are : ' + value);
    this.props.onSelect(value);
  }
-->

## Environment

    System:
      OS: Linux 4.15 Ubuntu 18.04.2 LTS
      CPU: (6) x64 AMD FX(tm)-6300 Six-Core Processor
      Memory: 121.82 MB / 3.59 GB
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 8.16.0
      npm: 6.4.1
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.58.3 => 0.58.3 
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by JKCooper2** [comment]
I believe the onValueChange is designed to only fire when the value is different, but it would definitely be good to have a standard onSelect or something that fires every time. The docs do say `Callback for when an item is selected`, but whether that includes already selected items I'm not sure

**Comment by Arley68** [comment]
Hey how are you doing

**Comment by saxenanickk** [comment]
@renishdeveloper As per the implementation, onValueChange event only fires when the selected value is different from the previous value.
As it is not an issue, I am closing it.

**Comment by saxenanickk** [comment]
@renishdeveloper As per the implementation of Picker, onValueChange only fires if the current value is different from previous value.
I think this issue can be closed now.

**Comment by renishdeveloper** [comment]
onValueChange is only fires if the selected value is different from the previously selected value.
