### ISSUE TITLE
GMUStyleMap.h file not found in GMUKMLParser.h

### ISSUE THREAD

**Issue by iamkallolpratim** [facebook/react-native#24709]
Unable to build the app . Error shows GMUStyleMap.h file not found in GMUKMLParser.h

![Screenshot 2019-05-06 at 11 27 48 AM](https://user-images.githubusercontent.com/4623728/57208564-1238ec80-6ff2-11e9-872d-be6c430ac4b2.png)
![Screenshot 2019-05-06 at 11 28 13 AM](https://user-images.githubusercontent.com/4623728/57208566-1238ec80-6ff2-11e9-9e24-687ea09a5d44.png)

**Comment by matthargett** [comment]
This file doesn't exist in React Native.  Maybe it should be reported to https://github.com/react-native-community/react-native-maps or the native component you're using?
