### ISSUE TITLE
How to force use ipv4 when I use react native function `fetch(resource, init)` in Android device

### ISSUE THREAD

**Issue by DonaldGuo** [facebook/react-native#24710]
DNS parsing IP address can resolve IPv6 and IPv4 at the same time, but IPv6 priority is higher when using 4G network, but using IPv6 will lead to continuous failure of network access when my application starts up.

On Android native, okhttp3 was used to solve the problem of failure of access to 4G network by override okhttp3.Dev.lookup().

`  new Dns() {
        @Override
        @NonNull
        public List<InetAddress> lookup(@Nullable String hostname) throws UnknownHostException {
            if (hostname == null) {
                throw new UnknownHostException("hostname == null");
            }
            try {
                List<InetAddress> mInetAddressesList = new ArrayList<>();
                InetAddress[] mInetAddresses = InetAddress.getAllByName(hostname);
                for (InetAddress address : mInetAddresses) {
                    if (address instanceof Inet4Address) {
                        mInetAddressesList.add(0, address);
                    } else {
                        mInetAddressesList.add(address);
                    }
                }
                return mInetAddressesList;
            } catch (NullPointerException e) {
                UnknownHostException unknownHostException =
                        new UnknownHostException("Broken system behaviour for dns lookup of " + hostname);
                unknownHostException.initCause(e);
                throw unknownHostException;
            }
        }
    };`

My react-native network access code is as follows
`Promise.race([
        fetch(url, init),
        new Promise(function(resolve,reject){
            setTimeout(()=> reject(new Error('request timeout')),30*1000)
        })])
        .then((response) => {
            return response.json();
        })
        ...`

How can I change DNS resolving setting in react-native fetch method?

**Comment by yoyo0427** [comment]
@DonaldGuo I also have the same needs. Has your problem been solved?

**Comment by DonaldGuo** [comment]
Unresolved, I now call okhttp3 using @ReactMethod

**Comment by DonaldGuo** [comment]
> @DonaldGuo I also have the same needs. Has your problem been solved?

Unresolved, I now call okhttp3 using @ReactMethod

**Comment by DonaldGuo** [comment]
@yoyo0427 Unresolved, I now call okhttp3 using @ReactMethod
