### ISSUE TITLE
Source uri ImagebackGround is not loading on released apk in some devices.

### ISSUE THREAD

**Issue by tauhidalmahfuz** [facebook/react-native#24711]
-> My source uri ImagebackGround is not loading in released apk on some latest devices(Notched, Curved). 
-> Running absolutely fine when i build it on device. I am using ImagebackGround inside a card of native-base. 
-> My source uri is a coming from REST API JSON.

Please help. 
Thank you.

![Screenshot (87)](https://user-images.githubusercontent.com/31836718/57195210-de1de700-6f71-11e9-9ad7-ca0e04e01a86.png)
![Screenshot (89)](https://user-images.githubusercontent.com/31836718/57195215-ed9d3000-6f71-11e9-9116-c95df3d17f81.png)

**Comment by ashish2309** [comment]
Any solution for this ?

**Comment by shercoder** [comment]
@tauhidalmahfuz @ashish2309 I am running into a similar issue. Have you guys figured out what's wrong with it or a workaround?
