### ISSUE TITLE
Discussion: RN Should not be prompting users to switch over to the community slider version of the package until it's more stable

### ISSUE THREAD

**Issue by bobber205** [facebook/react-native#24719]
Good day RN community.

I have appreciated greatly the suggestions on "hey this package is getting removed in an upcoming RN version, using this extracted version instead". I totally get what RN is doing this.

However I'm come across an instance of advice that I don't think should be presented to developers (just yet)

https://github.com/react-native-community/react-native-slider

When using the react-native version of the Slider component you get the typical use the above version instead. Unfortunately this version is largely broken at the moment. Using the latest and greatest of CLI tools and RN I am not able to easily run `react-native link @react-native-community/slider` and have it work. Sure the command runs fine but then you're basically guaranteed to run into this: https://github.com/react-native-community/react-native-slider/issues/41

I think until that package is more stable/fixed that warning shouldn't come up. There are surely many devs out there making the same mistakes as me and wasting precious man hours trying to debug what they did wrong.

:)

**Comment by hramos** [comment]
While I am not familiar with the specific case of react-native-slider, in theory what is being extracted to the community package is the same component that already existed in React Native core. All that is changing is that you're now importing the package from the community-managed repository. In fact, exporting the package into its own repository will allow the community to move faster and fix the issues you bring up here. I'm not sure that leaving the package in core would help in this case.

In any case, this seems like a more appropriate discussion for the existing Lean Core thread: https://github.com/facebook/react-native/issues/23313
