### ISSUE TITLE
[showcase] improvements

### ISSUE THREAD

**Issue by chirag04** [facebook/react-native#2471]
As per the comments on IRC:

- [x] vertical-align: top for each showcase item.
- [x] make the app icons link to the app store link
- [x] center the h1 tag 
- [x] 4 items per line if possible.

Apps to be added:
- [x] https://itunes.apple.com/us/app/start-medication-manager-for/id1012099928?mt=8
- [x] https://itunes.apple.com/us/app/discovery-vr/id1030815031?mt=8
- [x] https://itunes.apple.com/cn/app/tong-xing-wang/id914254459?mt=8

**Comment by jaygarcia** [comment]
One thing that I noticed with the Discovery VR app, i noticed with other business apps i'm working on; rendering images blocks animation.

Was this resolved in versions > 9.0?

**Comment by brentvatne** [comment]
@jaygarcia - hmm not sure, can you create a separate issue with some more details?

**Comment by chirag04** [comment]
looks awesome @brentvatne :+1:
