### ISSUE TITLE
Natively started activity is closed when launching rn app from desktop icon on Android.

### ISSUE THREAD

**Issue by SpertsyanKM** [facebook/react-native#24727]
## 🐛 Bug Report
On some screen of react-native application I call native method (@ReactMethod), which launches new activity. Then when I navigate to the Android home screen and reopen my app from the background using app icon (not application dispatcher), the app opens on the last screen, from which I'd called my native method. In other words, it opens `MainActivity` when I expect seeing natively started `MyActivity`. 

`MainActivity`-s `launchMode` is set to `singleTask`. Debugging shows, that after clicking launch icon, `MyActivity` is destroyed before `MainActivity.onNewIntent` is called.

## To Reproduce
1. From the screen `A` in react-native call native method `myNativeMethod` marked as `@ReactMethod` (for example, when clicking some button). 
2. In that `myNativeMethod` launch a new activity `MyActivity` using `reactApplicationContext`.
3. Hide the application using Android home button.
4. Reopen background app using launch icon from desktop or application list (not from application dispatcher).

## Expected Behavior
Expect seeing `MyActivity` but seeing `MainActivity` on the last react-native screen (screen `A`), from which I called `myNativeMethod`.

## Code Example
```
@ReactMethod
fun myNativeMethod() {
    val intent = Intent(reactApplicationContext, MyActivity::class.java)
    reactApplicationContext.startActivity(intent)
}
```

## Environment
```
info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
      Memory: 60.40 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.13.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28
        Build Tools: 25.0.2, 26.0.1, 26.0.2, 27.0.2, 27.0.3, 28.0.0, 28.0.2, 28.0.3
        System Images: android-16 | ARM EABI v7a, android-16 | Google APIs Intel x86 Atom, android-17 | Google APIs Intel x86 Atom, android-19 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-P | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.2 => 0.59.2 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-create-library: 3.1.2
```

**Comment by dulmandakh** [comment]
maybe you should remove launchMode=singleTask, and try.

**Comment by SpertsyanKM** [comment]
@dulmandakh - remove and run into multiple instances for each launch from icon or push notification?
It's not a solution.

I've thought that probably I'd described as a bug the normal way Android handles singleTask activities. Now I see the only solution in creating another launcher activity without `singleTask` launch mode which will proxy intents to `MainActivity` ignoring launch intents from application icon, when the app is already launched.
