### ISSUE TITLE
Unknown failure cmd: Can't find service: package

### ISSUE THREAD

**Issue by hidayatridwan** [facebook/react-native#24725]
> Task :app:installDebug
09:08:07 V/ddms: execute: running am get-config
09:08:07 V/ddms: execute 'am get-config' on 'emulator-5554' : EOF hit. Read: -1
09:08:07 V/ddms: execute: returning
Installing APK 'app-debug.apk' on 'Nexus_5X_API_28_x86(AVD) - 9' for app:debug
09:08:07 D/app-debug.apk: Uploading app-debug.apk onto device 'emulator-5554'
09:08:07 D/Device: Uploading file onto device 'emulator-5554'
09:08:07 D/ddms: Reading file permision of D:\react-native\Kemenkop\android\app\build\outputs\apk\debug\app-debug.apk as: rwx------
09:08:08 V/ddms: execute: running pm install -r -t "/data/local/tmp/app-debug.apk"
09:08:08 V/ddms: execute 'pm install -r -t "/data/local/tmp/app-debug.apk"' on 'emulator-5554' : EOF hit. Read: -1
09:08:08 V/ddms: execute: returning
Unable to install D:\react-native\Kemenkop\android\app\build\outputs\apk\debug\app-debug.apk
com.android.ddmlib.InstallException: Unknown failure (cmd: Can't find service: package)
.
.
.
> Task :app:installDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:installDebug'.
> com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: Unknown failure (cmd: Can't find service: package)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 1s
62 actionable tasks: 1 executed, 61 up-to-date
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

Command failed: gradlew.bat installDebug

Error: Command failed: gradlew.bat installDebug
    at checkExecSyncError (child_process.js:637:11)
    at Object.execFileSync (child_process.js:655:13)
    at runOnAllDevices (D:\react-native\Kemenkop\node_modules\react-native\local-cli\runAndroid\runAndroid.js:299:19)
    at buildAndRun (D:\react-native\Kemenkop\node_modules\react-native\local-cli\runAndroid\runAndroid.js:135:12)
    at isPackagerRunning.then.result (D:\react-native\Kemenkop\node_modules\react-native\local-cli\runAndroid\runAndroid.js:65:12)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)

**Comment by andreialecu** [comment]
I've ran into the same issue after wiping out an emulator's data via Android Studio. Presumably something that was installed which was needed by the android build system was lost.

After re-creating the emulator it started working again.

**Comment by andreialecu** [comment]
I just ran into the same error. In my case the emulator was frozen. I had to go to AVD Manager in Android Studio and run "Cold Boot Now" on the specific emulator to get it back up, then this error went away.

**Comment by hidayatridwan** [comment]
> I just ran into the same error. In my case the emulator was frozen. I had to go to AVD Manager in Android Studio and run "Cold Boot Now" on the specific emulator to get it back up, then this error went away.

it works thankyou so muchhh!!!

**Comment by marcosbarbosa031** [comment]
> I just ran into the same error. In my case the emulator was frozen. I had to go to AVD Manager in Android Studio and run "Cold Boot Now" on the specific emulator to get it back up, then this error went away.

Is there a Wait to make it coldboot by default?

**Comment by satty82** [comment]
> I just ran into the same error. In my case the emulator was frozen. I had to go to AVD Manager in Android Studio and run "Cold Boot Now" on the specific emulator to get it back up, then this error went away.

Thanks Man  it worked for me

**Comment by LiGoTo** [comment]
The application may be doing too much work on its main thread.

**Comment by LiGoTo** [comment]
It worked for me THANKS!

**Comment by JeyaNandhana** [comment]
Thank you. It worked for me.

**Comment by sunnylnct007** [comment]
Works with cold boot. But is this a bug?

**Comment by kdhiren** [comment]
@andreialecu is correct by selecting Cold boot it works fine, but again change it to Quick boot it wont works. Can it be consider as bug ?

**Comment by purushottam-cyber** [comment]
> I just ran into the same error. In my case the emulator was frozen. I had to go to AVD Manager in Android Studio and run "Cold Boot Now" on the specific emulator to get it back up, then this error went away.
thanks bro it did really helped me out

**Comment by viky293** [comment]
> 
> 
> I just ran into the same error. In my case the emulator was frozen. I had to go to AVD Manager in Android Studio and run "Cold Boot Now" on the specific emulator to get it back up, then this error went away.

I just wonder how do we reach to such solutions, is it just experience with hit and try methods or there are useful error messages that are ignored by most of us. This is such a time waste for developers.

**Comment by shubi100** [comment]
Thanks bro it is working well and solid.

**Comment by Mohammed-deve** [comment]
I just ran into the same error. In my case the emulator was frozen. I had to go to AVD Manager in Android Studio and run "Cold Boot Now" on the specific emulator to get it back up, then this error went away.

Thanks Man it worked for me

**Comment by Mohammed-deve** [comment]
I just ran into the same error. In my case the emulator was frozen. I had to go to AVD Manager in Android Studio and run "Cold Boot Now" on the specific emulator to get it back up, then this error went away.

Thanks Man it worked for me
