### ISSUE TITLE
Inspector is broken in RTL

### ISSUE THREAD

**Issue by iamandiradu** [facebook/react-native#24731]
React Native's Inspector is mirrored in RTL.
(both iOS & Android)

## Steps to Reproduce

1. Use a RTL language or enforce RTL layout
2. Toggle Inspector
3. Try to inspect an element

## Expected Behavior

The highlighted bounding box should overlay the selected element.

## Actual Behavior

The highlighted bounding box is aligned to the opposite side (mirrored).
![Simulator Screen Shot - iPhone X - 2019-05-07 at 13 25 57](https://user-images.githubusercontent.com/24257156/57292869-b773c380-70cb-11e9-8cb6-50dc0d405da8.png)

## Environment

React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
      Memory: 94.29 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.10.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 26, 28
        Build Tools: 26.0.2, 28.0.2, 28.0.3
        System Images: android-24 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.4 => 0.59.4
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Related issues

#15530

**Comment by matthargett** [comment]
Can you create a snack that reproduces this issue? https://snack.expo.io/

**Comment by iamandiradu** [comment]
@matthargett, I would, but I don't know how to integrate the debugger.
