### ISSUE TITLE
我在Android使用Image组件调用外链图片无法正常显示，而IOS可以

### ISSUE THREAD

**Issue by steelegg** [facebook/react-native#24740]
## 🐛 Bug Report

我在页面上这样使用：
```
<Image style={styles.itemImage} onLoadStart={this._onLoadEnd} source={{uri: 'https://ss3.bdstatic.com/70cFv8Sh_Q1YnxGkpoWK1HF6hhy/it/u=1846931186,3702313373&fm=26&gp=0.jpg'}}/>
```
在Android上不能正常显示，在IOS上是可以的

## Environment

info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.1
      CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 92.88 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.1 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.8.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 26, 28
        Build Tools: 28.0.3
        System Images: android-25 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom_64
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: react-native info => 0.59.5 
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by steelegg** [comment]
> 您是否可以运行`react-native info`和编辑问题以在**环境**部分下包含这些结果？
> 
> 如果您认为此信息与报告的问题无关，您可以在“环境：”部分中写下“[skip envinfo]”和解释。
非常感谢你的回复
info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.1
      CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 92.88 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.1 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.8.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 26, 28
        Build Tools: 28.0.3
        System Images: android-25 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom_64
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: react-native info => 0.59.5 
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by steelegg** [comment]
在android上不是所有的图片都无效,如果换成https://facebook.github.io/react-native/docs/assets/favicon.png，它是可以正常显示的
```
                <Image style={{height: 100, width: 100}} source={{uri: 'https://facebook.github.io/react-native/docs/assets/favicon.png'}}/>
```

**Comment by EyreGe** [comment]
@steelegg I tried to use this image. It's ok.

**Comment by dulmandakh** [comment]
@steelegg could you please provide description in english. I'll re-open the issue then. Thank you.

**Comment by steelegg** [comment]
@dulmandakh I restarted my computer this morning. It's OK now. I'm sorry.

**Comment by dulmandakh** [comment]
Could you please close the issue

**Comment by jsbsdbd1025** [comment]
How can i skip the https authorization？
 I think it's the reason of image can't load~
