### ISSUE TITLE
Build Android faile

### ISSUE THREAD

**Issue by mhpyzzy** [facebook/react-native#24759]
## 🐛 Bug Report
[drawable-xhdpi-v4/src_assets_img_default_default_img] /Users/zhangzhenyang/Documents/work/okai/android/app/build/generated/res/react/release/drawable-xhdpi/src_assets_img_default_default_img.png	[drawable-xhdpi-v4/src_assets_img_default_default_img] /Users/zhangzhenyang/Documents/work/okai/android/app/src/main/res/drawable-xhdpi/src_assets_img_default_default_img.png: Error: Duplicate resources
[drawable-xxhdpi-v4/src_assets_img_default_default_img] /Users/zhangzhenyang/Documents/work/okai/android/app/src/main/res/drawable-xxhdpi/src_assets_img_default_default_img.png	[drawable-xxhdpi-v4/src_assets_img_default_default_img] /Users/zhangzhenyang/Documents/work/okai/android/app/build/generated/res/react/release/drawable-xxhdpi/src_assets_img_default_default_img.png: Error: Duplicate resources

## To Reproduce
i use command “react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/”  build jsbundle for android
and build release by AndroidStudio ,failed

is use this way to build success by RN0.51.0

## Expected Behavior
i want to build success,please help

## Environment
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
      Memory: 484.92 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.14.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 23, 26, 27, 28
        Build Tools: 23.0.1, 27.0.3, 28.0.3
        System Images: android-23 | Intel x86 Atom, android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.5 => 0.59.5 
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by cpojer** [comment]
PR is landing with a fix.
