### ISSUE TITLE
FlatList caches items below current scrolling index

### ISSUE THREAD

**Issue by JohannesKlauss** [facebook/react-native#24756]
## 🐛 Bug Report
When setting `windowSize` to 1, I expect a paginated FlatList to only render the current visible item and get rid of all other items. But FlatList caches all the items whose index is below the currently visible index.

## To Reproduce
[Github repo to reproduce bug](https://github.com/JohannesKlauss/rn-flatlist-caching-bug)
You can see this in the attached repo (check it out and build it on emulator or device), when scrolling back and forth. If you scroll forth, there is a noticeable blank screen, so FlatList is freshly rendering the next item. But when you scroll back the image appears immediately, so it is cached and there is no fresh render.

## Expected Behavior
I expect that FlatList doesn't cache any rendered item when the windowSize is set to 1.

## Code Example
[Github repo to reproduce bug](https://github.com/JohannesKlauss/rn-flatlist-caching-bug)

## Environment
```
info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 157.72 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.15.1 - ~/.nvm/versions/node/v8.15.1/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.15.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 24, 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-24 | Intel x86 Atom_64, android-24 | Google APIs Intel x86 Atom_64, android-24 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.5 => 0.59.5 
```

**Comment by JohannesKlauss** [comment]
I also created a gif, to illustrate the issue:

![Bug Showcase](https://media.giphy.com/media/loj6bQxPHHJgI3VWsR/giphy.gif)

**Comment by zhongwuzw** [comment]
@JohannesKlauss By default, lists would do some cache and preload, we have some default value and they are configurable, please see https://github.com/facebook/react-native/blob/master/Libraries/Lists/VirtualizedList.js#L219 for details.
