### ISSUE TITLE
New App Screen

### ISSUE THREAD

**Issue by cpojer** [facebook/react-native#24760]
This is the list of remaining things to do before we can ship the new app screen (see https://github.com/react-native-community/discussions-and-proposals/issues/122). The initial version of the code was landed via https://github.com/facebook/react-native/pull/24737:

- [x] Fix up the styling and color names a bit more.
- [x] Split up the components the way @orta proposed so we'll have some good sample code in the App.js template.
- [x] Make it so that links tapped will send an open-in-browser command via Metro on the host instead of in the emulator. See https://github.com/react-native-community/cli/blob/885f2c28d4e8ed66e334fd7bd0174173b2a394e1/packages/cli/src/commands/server/middleware/openStackFrameInEditorMiddleware.js for how we are doing this in the cli/metro (this may need some changes to the CLI and Metro) and https://github.com/facebook/react-native/blob/1151c096dab17e5d9a6ac05b61aacecd4305f3db/Libraries/Core/Devtools/openFileInEditor.js (@lucasbento)
- [x] Add a "Follow us on Twitter" button 😄
- [x] Actually put this all in the template so it can be shipped as part of 0.61.

cc @eliperkins @lucasbento would be awesome if you could help out! :)

**Comment by lucasbento** [comment]
I would love to help on this, specially the opening links on the browser part.

Would this be targeting 0.61? I'm currently busy with some stuff for the CLI but I would probably be able to do some stuff for this next week.

**Comment by cpojer** [comment]
Yep, 0.61. Ideally we'll wrap this work up by the end of the month.

**Comment by cpojer** [comment]
@eliperkins do you wanna take care of adding a follow on twitter link + putting it into the actual template? :)

**Comment by eliperkins** [comment]
@cpojer sure thing. I'll tackle the moving to the template part now that the polish PR has landed.

As for the Twitter link, do you expect that to be a link to https://twitter.com/reactnative or is there another, more follow-specific link that we can put in there?

**Comment by cpojer** [comment]
Yep, that links is good :)

**Comment by eliperkins** [comment]
#24805 and #24806 are up now! 

I think there's still some work to do to rearrange components and tuck some complexity away before I'd call this template ready to ship, so I'd love some feedback.

**Comment by lucasbento** [comment]
@ericlewis opened a PR for the open in browser functionality on CLI: react-native-community/cli#383.

**Comment by cpojer** [comment]
Alright, so the main remaining thing is to hook up @ericlewis's new feature with the buttons in the new app screen. @lucasbento could you make that happen? Ideally if you could add a video in the test plan to show that it works that would be best :D

**Comment by cpojer** [comment]
Thank you everyone for making this happen. This was a super awesome collaboration between so many people. @rickhanlonii and I made a brief video to show off the new screen: https://www.youtube.com/watch?v=ImlAqMZxveg&feature=youtu.be

**Comment by gamingumar** [comment]
@cpojer Can we upgrade typescript template to support this? Typescript template is still using old screen..

**Comment by orta** [comment]
Give it a shot at updating yourself @gamingumar - I think it's this one: https://github.com/react-native-community/react-native-template-typescript

**Comment by gamingumar** [comment]
Hi @orta Sure, I can create a PR for it, just need an input where should that typescript template live? As this one lives in react-native/Libraries
