### ISSUE TITLE
babelHelpers is not defined, after updating react-native from 0.59.2 to 0.59.8

### ISSUE THREAD

**Issue by alainib** [facebook/react-native#24779]
I'm trying to  updating react-native from 0.59.2 to 0.59.8. 

## error : babelHelpers is not defined

![Screenshot_2019-05-09-15-48-03](https://user-images.githubusercontent.com/7910081/57459357-61da1b00-7273-11e9-9334-b3389d2dfc73.png)

I cannot run on android device anymore (not tested on Ios or emulator yet )
 
React Native version: 

	 React Native Environment Info:
		System:
		  OS: Windows 10
		  CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
		  Memory: 6.33 GB / 15.79 GB
		Binaries:
		  Node: 10.15.2 - D:\work\nodejs\node.EXE
		  Yarn: 1.13.0 - C:\work\Yarn\bin\yarn.CMD
		  npm: 6.9.0 - D:\work\nodejs\npm.CMD
	 
-  this was my previous `package.json`

		{
			"name": "myApp",
			"version": "0.0.1",
			"private": true,
			"scripts": {
				"start": "node node_modules/react-native/local-cli/cli.js start",
				"test": "jest"
			}, 
			"dependencies": {
				"@react-native-community/async-storage": "^1.3.0",
				"@react-native-community/netinfo": "^1.4.0",
				"react": "16.8.6",
				"react-native": "0.59.2",
				...		 
			},
			"devDependencies": {
				"babel-core": "7.0.0-bridge.0",
				"babel-jest": "24.4.0",
				"babel-plugin-transform-remove-console": "^6.9.4",
				"jest": "24.4.0",
				"metro": "^0.53.1",
				"metro-react-native-babel-preset": "0.53.0",
				"react-test-renderer": "16.6.3"
			},
			"jest": {
				"preset": "react-native"
			}
		}

- previous `.babelrc`

		{
		  "env": {
			"production": {
			  "plugins": ["transform-remove-console"]
			}
		  }
		}

- previous `index.android.js`

		import { AppRegistry } from 'react-native';
		import App from './src/App'
		AppRegistry.registerComponent('PlantNet', () => App);

- i updated ` package.json `

		{
			"name": "myApp",
			"version": "0.0.1",
			"private": true,
			"scripts": {
				"start": "node node_modules/react-native/local-cli/cli.js start",
				"test": "jest"
			},
		 
			"dependencies": {
				"@babel/plugin-proposal-decorators": "^7.0.0-beta.47",
				"@babel/runtime": "7.0.0-beta.47",
				"@react-native-community/async-storage": "^1.3.0",
				"@react-native-community/netinfo": "^1.4.0",
				"react": "16.8.6",
				"react-native": "0.59.8",
				...	 
			},
			"devDependencies": {
				"babel-core": "7.0.0-bridge.0",
				"babel-jest": "24.8.0",
				"babel-plugin-transform-remove-console": "^6.9.4",
				"babel-preset-react-native": "^4.0.1",
				"jest": "^24.8.0",
				"metro": "^0.53.1",
				"metro-react-native-babel-preset": "0.53.0",
				"react-test-renderer": "16.6.3"
			},
			"jest": {
				"preset": "react-native"
			}
		}

- i updated `.babelrc`

		{
			"env": {
				"production": {
					"plugins": ["transform-remove-console"]
				}
			},
			"presets": ["module:metro-react-native-babel-preset"],
			"plugins": [
				["@babel/plugin-transform-react-jsx-source"],
				[
					"@babel/plugin-proposal-decorators",
					{
						"legacy": true
					}
				]
			]
		}

- i update `index.android.js` : 

		import {AppRegistry} from 'react-native'

		import applyDecoratedDescriptor from '@babel/runtime/helpers/es6/applyDecoratedDescriptor'
		import initializerDefineProperty from '@babel/runtime/helpers/es6/initializerDefineProperty'

		Object.assign(babelHelpers, {applyDecoratedDescriptor, initializerDefineProperty})

		AppRegistry.registerComponent('PlantNet', () => require('./src/App').default)

## Steps To Reproduce

 
update react-native from 0.59.2 to 0.59.8
 

I'm lost between pre processing, babel, jest, metro etc. Not sure about anything i do her. 
Any tips or working config are welcomed. Thanks

**Comment by kelset** [comment]
Hello there 👋 this issue seems to be related to your experience upgrading between versions. We know this has been a [long lasting pain for the community](https://github.com/react-native-community/discussions-and-proposals/issues/68) so starting v0.59 we have introduced a new flow via the [new CLI](https://facebook.github.io/react-native/blog/#cli-improvements).

I'd suggest you use [rn-diff-repo](https://github.com/pvinis/rn-diff-purge) to double check that you did all the necessary steps/changes while upgrading.

Also, maybe it's just a matter of some cache not being cleaned properly? Try running:

```
rm -rf node_modules;
rm -rf $TMPDIR/react-native-packager-cache-*;
rm -rf $TMPDIR/metro-*;
rm -rf $TMPDIR/react-*;
rm -rf $TMPDIR/haste-*;
watchman watch-del-all;
yarn;
yarn start --reset-cache; (for starting the bundler)
```

Given that this is not strictly a bug with the library itself I'll close this, but if you can create a repro that has this issue with a freshly created `react-native init` project we can reopen it and investigate it further 🤗

**Comment by DiegoMac95** [comment]
@alainib did you find a solution for this?

**Comment by njacob1001** [comment]
try to use `@babel/plugin-transform-runtime`
