### ISSUE TITLE
[AsyncStorage] should not always create a RCTAsyncLocalStorage_V1 directory under NSDocumentDirectory

### ISSUE THREAD

**Issue by zmxv** [facebook/react-native#2477]
RCTAsyncLocalStorage._ensureSetup currently creates a RCTAsyncLocalStorage_V1 directory under NSDocumentDirectory, even if the app does not use AsyncStorage at all. This adds noise to the Documents folder when the app enables file sharing with iTunes.

The RCTAsyncLocalStorage_V1 directory should be lazily created under NSLibraryDirectory by default. To ensure backward compatibility, app developers should be given an API to specify the storage location.

**Comment by ide** [comment]
@zmxv for the time being I think you could unlink RCTAsyncStorage and just not include it in your app. I agree that control over the directory is important since apps are sometimes rejected if they don't use the right directory.

@vjeux could you assign this to the appropriate owner?

**Comment by vjeux** [comment]
@sahrens is the appropriate owner

**Comment by sahrens** [comment]
_ensureSetup should only be called if you invoke an AsyncStorage method through the bridge - are you sure you're not actually using it somewhere?

**Comment by sahrens** [comment]
AsyncStorage shouldn't do anything if you don't use it - if that's not the case, some debugging is in order.

**Comment by zmxv** [comment]
@sahrens I'm not using AsyncLocalStorage in my code. Neither does any of my dependency modules. This bug can be reproduced by simply launching an empty RN app and inspecting the Documents folder.

I've noticed that Libraries/ReactIOS/WarningBox.js calls AsyncStorage.getItem('__DEV_WARNINGS_IGNORED', ...) in the initialization logic which triggers the _ensureSetup function through the bridge, which in turn creates the RCTAsyncLocalStorage_V1 directory under NSDocumentDirectory. So, there're actually three bugs involved here:
1. WarningBox should stop polluting AsyncStorage. At the minimum, don't use AsyncStorage during module initialization.
2. AsyncStorage should stop creating the RCTAsyncLocalStorage_V1 directory in getters.
3. AsyncStorage should create the directory under NSLibraryDirectory (or a user-specified folder) rather than NSDocumentDirectory.

**Comment by sahrens** [comment]
Those sound like good changes.

I'm not super familiar with ios conventions - why Library dir instead of
Document?

**Comment by ide** [comment]
@sahrens the different directories have their own backup semantics. I know that Documents are backed up to iCloud but Library files might not be. The Documents are more user-facing in some of the backup and sharing tools. In fact Apple has reportedly rejected apps for writing non-user-created data to Documents.

> - Put user data in Documents/. User data generally includes any files you might want to expose to the user—anything you might want the user to create, import, delete or edit. For a drawing app, user data includes any graphic files the user might create. For a text editor, it includes the text files. Video and audio apps may even include files that the user has downloaded to watch or listen to later.
>
> - Put app-created support files in the Library/Application support/ directory. In general, this directory includes files that the app uses to run but that should remain hidden from the user. This directory can also include data files, configuration files, templates and modified versions of resources loaded from the app bundle.
>
> - Remember that files in Documents/ and Application Support/ are backed up by default. You can exclude files from the backup by calling -[NSURL setResourceValue:forKey:error:] using the NSURLIsExcludedFromBackupKey key. Any file that can be re-created or downloaded must be excluded from the backup. This is particularly important for large media files. If your application downloads video or audio files, make sure they are not included in the backup.
>
> - Put temporary data in the tmp/ directory. Temporary data comprises any data that you do not need to persist for an extended period of time. Remember to delete those files when you are done with them so that they do not continue to consume space on the user’s device. The system will periodically purge these files when your app is not running; therefore, you cannot rely on these files persisting after your app terminates.
>
> - Put data cache files in the Library/Caches/ directory. Cache data can be used for any data that needs to persist longer than temporary data, but not as long as a support file. Generally speaking, the application does not require cache data to operate properly, but it can use cache data to improve performance. Examples of cache data include (but are not limited to) database cache files and transient, downloadable content. Note that the system may delete the Caches/ directory to free up disk space, so your app must be able to re-create or download these files as needed.

https://developer.apple.com/library/ios/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html#//apple_ref/doc/uid/TP40010672-CH2-SW28

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/asyncstorage-should-not-always-create-a-rctasynclocalstoragev1-directory-under-nsdocumentdirectory

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is heavily focused working on performance.
