### ISSUE TITLE
Build fails in every case.

### ISSUE THREAD

**Issue by gauravr-dev** [facebook/react-native#24799]
I have tried to create new App using `react-native-cli`. Then tried to run for iOS using `run-ios`, but it does not worked. I have googled for the issues, some say it is problem of XCode 10, so I changed the command line tools to 9.4 version. It still does not work.

Below is my package.json content.

'Last login: Fri May 10 18:24:31 on ttys001
➜  ~ react-native run-ioscd
➜  ~ cd myapptest 
➜  myapptest ls
App.js          app.json        ios             package.json
__tests__       babel.config.js metro.config.js yarn.lock
android         index.js        node_modules
➜  myapptest vi package.json 

{
  "name": "myapptest",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.8.3",
    "react-native": "0.59.8"
  },
  "devDependencies": {
    "@babel/core": "^7.4.4",
    "@babel/runtime": "^7.4.4",
    "babel-jest": "^24.8.0",
    "jest": "^24.8.0",
    "metro-react-native-babel-preset": "^0.54.0",
    "react-test-renderer": "16.8.3"
  },
  "jest": {
    "preset": "react-native"
  }

React Nativ info is as below.

` React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 78.98 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.1 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        API Levels: 27
        Build Tools: 26.0.2, 27.0.3, 28.0.0
        System Images: android-26 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.8 => 0.59.8 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      reactotron-react-native: 1.14.0
`

Erros I got are following - 

❌  /Users/gaurav.rajput/myapptest/node_modules/react-native/Libraries/Network/RCTNetworkTask.m:8:9: 'React/RCTLog.h' file not found

#import <React/RCTLog.h>
        ^~~~~~~~~~~~~~~~

❌  /Users/gaurav.rajput/myapptest/node_modules/react-native/Libraries/Network/RCTFileRequestHandler.h:8:9: 'React/RCTInvalidating.h' file not found

#import <React/RCTInvalidating.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~

❌  /Users/gaurav.rajput/myapptest/node_modules/react-native/Libraries/Network/RCTDataRequestHandler.h:8:9: 'React/RCTInvalidating.h' file not found

#import <React/RCTInvalidating.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~

Most importantly, every time got different issues.

**Comment by kelset** [comment]
Hello there 👋 by using the repro / the list of steps to reproduce, we can't actually see the reported bug on RN 0.59 so we'll close this issue.

It may have something to do with your local setup, please double check that you are using the correct version of Android Studio / XCode / Android NDK / Yarn / etc.

In particular, two things that I can see from your info that I suggest you do:
1) update Node, you are currently still using 8 but I suggest you to at least move to Node 10.15
2) remove `create-react-native-app`

>  I have googled for the issues, some say it is problem of XCode 10, so I changed the command line tools to 9.4 version.
Also, when trying a simply `react-native init`-ed project (without changes) you should not need to change this.
