### ISSUE TITLE
react-native-cli init new Project error

### ISSUE THREAD

**Issue by jsu93** [facebook/react-native#24791]
React Native version: latest

## Steps To Reproduce

1. `react-native init newRnProject`

`error Couldn't find package "@react-native-community/cli@^1.2.1" required by "react-native" on the "npm" registry.

![image](https://user-images.githubusercontent.com/32606956/57499417-2e020280-7312-11e9-8558-de8139d8c0d9.png)`

**Comment by alainib** [comment]
i think you need to install cli before init 

           npm install -g react-native-cli

**Comment by jsu93** [comment]
because of npm server shutdown

**Comment by jayrajkachariya** [comment]
I am facing, the same issue. I have also installed **react-native-cli** globally. But, still no luck. Was the npm server down exact issue??

**Comment by jayrajkachariya** [comment]
In my case npm server shutdown wasn't the issue, I resolved issue by setting npm registry to **default**!
To get current registry: **npm config get registry**
set to default by: **npmrc default**

**Comment by zora-yue** [comment]
Couldn't find package "react-native" on the "npm" registry
