### ISSUE TITLE
One line ES6 imports

### ISSUE THREAD

**Issue by alvaromb** [facebook/react-native#2479]
This is working

```javascript
import React, { Component, View, Text, PropTypes } from 'react-native'
```

However, this is throwing an error

```javascript
import React, { 
  Component, 
  View, 
  Text, 
  PropTypes 
} from 'react-native'
```
<img width="487" alt="screen shot 2015-08-28 at 15 07 39" src="https://cloud.githubusercontent.com/assets/289640/9546871/8e54a8cc-4d96-11e5-8f9d-19fb6a2c8674.png">

Any ideas why? I'm not an ES6 expert but, shouldn't that work?

**Comment by ms88privat** [comment]
it's a bug, see https://github.com/facebook/react-native/pull/1940#issuecomment-134680479

**Comment by alvaromb** [comment]
Oh! didn't found that one. Thanks @ms88privat!
