### ISSUE TITLE
Navigator component uses rebound for animations

### ISSUE THREAD

**Issue by almost** [facebook/react-native#2480]
I'm finding they often stutter in my app. Animations done with the Animated module don't tend to. Any plans to port Navigator over to use Animated?

**Comment by PhilippKrone** [comment]
This would definitely be awesome!

**Comment by ide** [comment]
I believe this is underway but not sure of the time schedule. Maybe slated for 0.12 or 0.13? cc @ericvicenti @hedgerwang

**Comment by brentvatne** [comment]
This is indeed in progress -- going to close the issue as it's known and underway :)

**Comment by PhilippKrone** [comment]
@brentvatne any idea when it's gonna make it into master?

**Comment by brentvatne** [comment]
Personally no, @hedgerwang and @ericvicenti are the people who might have some idea of that :)

That said, this won't completely fix the issue of stuttering - another comment that goes into more detail here: https://github.com/facebook/react-native/issues/2490#issuecomment-136249185
