### ISSUE TITLE
[iOS and Android] Large images appear downsampled, and resize mode not working properly.

### ISSUE THREAD

**Issue by a9udn9u** [facebook/react-native#24819]
React Native version:

```
info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
      Memory: 2.83 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.2, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.3
        System Images: android-23 | Google APIs Intel x86 Atom
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: * => 16.6.3 
      react-native: * => 0.59.6 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

## Steps To Reproduce

1. Add a `<Image>` component, load a large image. The one I used is a 435 x 7225, 286kb png file.

**Problem on Android**
Set `resizeMode` to `cover`, image appears to be heavily downsampled, becomes unviewable.

**Problem on iOS**
Set `resizeMode` to `center`, image is cropped.

Describe what you expected to happen:
I expect the image to be clear on Android.
I expect the image to be displayed in full on iOS.

Snack, code example, or link to a repository:
https://snack.expo.io/ryp-QWI3V

I also created this SO question with some screenshots: https://stackoverflow.com/questions/56035427/why-large-images-are-blur-or-downsampled-using-react-native-image

**Comment by joahjoah** [comment]
Experiencing the same issue here. High resolution png with same filesize being downsampled beyond recognition. Same happens with both a remote URL or a local file.
