### ISSUE TITLE
touchableOpacity does not work properly when absolute position is applied to it

### ISSUE THREAD

**Issue by abdellah-el-mennani** [facebook/react-native#24823]
my problem is similar to the one found here: https://stackoverflow.com/questions/55923077/react-native-floating-action-button-touchable-not-working

Any recommendation will be helpful.

**Comment by abdellah-el-mennani** [comment]
as the guy in stackoverflow noticed. it works on ios but not on android

**Comment by wbinWang** [comment]
> my problem is similar to the one found here: https://stackoverflow.com/questions/55923077/react-native-floating-action-button-touchable-not-working
> 
> Any recommendation will be helpful.

How did you solve this problem? I also met this problem.

**Comment by code-by** [comment]
same problem

**Comment by abdellah-el-mennani** [comment]
the thing to understand is in Android if the absolute positioned button is outside its parent it will not catch events. You can verify this hypothesis by making a square view and float the button in such a way that half of it is outside that view, and the other half is inside the view. when u click on the half that is inside the parent view, the event will trigger; but if u click on the half outside the parent view it will not work.
so the conclusion is to always make sure that the button is inside the parent view. in the case  of floating action button, if u want it to work u need to hook it up to the root view of the screen, or in other words it should be a direct child of the root view of the screen. sure u will make it last child also to not be hidden. this way u will be sure it always inside the parent view. 
another things to look to is if u create a project in android studio say to make native app, and  u select the option with floating action button, u will see that the FAB is a direct child of the constraintlayout container which validate what I'm saying here.
