### ISSUE TITLE
RefreshControl does not work correctly on state change

### ISSUE THREAD

**Issue by gzzo** [facebook/react-native#24855]
React Native version:
0.59.8

## Steps To Reproduce

1. Pull down on list, refresh control appears (as it should)
2. Press button on top of list to load data, refresh control does not appear even though refreshing is true. You can also this is true by pressing the button first, the pulling down, then finally pressing the button again.

Describe what you expected to happen: The refresh control should appear whenever `refreshing` is true

Snack, code example, or link to a repository: https://snack.expo.io/ByZXxOuhV

**Comment by gzzo** [comment]
This is still an issue

**Comment by danieloprado** [comment]
Problem stills on 0.60.4

**Comment by gbalduzzi** [comment]
Can confirm, it is really annoying because there are no actual workarounds if you need to:

- Keep pull to refresh functionality
- Show the loading indicator when the refresh is triggered programmatically (e.g. the user searched something)

**Comment by xfyre** [comment]
+1 

Android works properly, while iOS does not. Somehow refreshing state doesn't keep on the screen while app is reloading and resets immediately.

**Comment by ilkka-yli** [comment]
+1

I have this issue too. RN version 0.59.8.

**Comment by SergioCastro15** [comment]
+1
0.60.4, it happens only in iOS with the controlled prop

**Comment by patrickleemsantos** [comment]
+1 I also experience in RN 0.59.8

**Comment by zyc67** [comment]
+1  ios
when I use react-navigation to customize the header, the problem appear, if I remove the header it's  ok.

**Comment by plimerence** [comment]
same issue ,why so much bugs in basic component🙃🙃🙃🙃🙃🙃🙃🙃🙃🙃🙃🙃🙃🙃🙃🙃🙃🙃🙃🙃🙃🙃🙃🙃

**Comment by sirjmkitavi** [comment]
+1 
RN 0.60.4, Same issue.
Doesn't work on iOS but works perfectly on Android.

**Comment by sirjmkitavi** [comment]
https://github.com/facebook/react-native/issues/24530

**Comment by jlariza** [comment]
+1
RN 0.61.2 failing as well. It doesn't work on iOS but works perfectly on Android.

**Comment by daysv** [comment]
+1
RN 0.61.2, Same issue.
thanks @gbalduzzi

**Comment by smolster** [comment]
+1
Still seeing this issue!

**Comment by ragamufin** [comment]
See [my comment here](https://github.com/facebook/react-native/issues/25898#issuecomment-554107989) for a possible workaround

**Comment by IgnorancePulls** [comment]
Opened Pr ^

**Comment by rdinizz** [comment]
If anyone is still having problems with this:

I found a workaround that is just enabling the bounce.

I had bounces={false} and after removing it, it's working on iOS now(Android was already working)

But in my case, the loading didn't appear not even once.

**Comment by obiwankenoobi** [comment]
still an issue with v0.61.4

**Comment by emagnier** [comment]
still an issue on v0.62.2 when `<RefreshControl />` is enabled (with local state) from a `useEffect` function.

**Comment by hackrx** [comment]
Hey, guys, I am facing the same issue with android, please have a look at this code, don't know why it is not working
`class Home extends Component {
  constructor(props) {
    super(props);
    this.state = {
      loading: false,
      lastLoadDate: null,
      onPullRefresh: false,
      postArray: [],
      allLoadDone: false,
      limit: 5,
      refreshing: false,
    };
    this.onEndReachedCalledDuringMomentum = false;
  }
`

`componentDidMount() {
    console.log(
      'Component did mount Home.js retrieve data called',
      this.state.postArray,
    );
    this.retrieveData();
  }`

` <View style={styles.listView}>
          <FlatList
            //data

            style={{width: '100%'}}
            data={this.state.postArray}
            extraData={this.state}
            //renderItems
            renderItem={({item}) => (
              <Post
                userName={item.userName}
                userPhoto={item.userPhotoURL}
                imageData={item.postImageURL}
                likes={item.likes}
                // id={item.}
                title={item.title}
                hashtags={item.hashtags}
                resizeMode={item.style}
                timeStamp={item.createdAt}
                navigation={this.props.navigation}
              />
            )}
            //Item Key
            keyExtractor={(item, index) => String(index)}
            //Footer loader
            ListFooterComponent={this.renderFooter}
            //on end reached

            onEndReached={() => {
              if (!this.onEndReachedCalledDuringMomentum) {
                // if (allLoadDone) {
                //   noRetrieve();
                // } else {
                this.retrieveMore();
                // }
              }
            }}
            onMomentumScrollBegin={() => {
              this.onEndReachedCalledDuringMomentum = false;
            }}
            refreshControl={
              <RefreshControl
                refreshing={this.state.onPullRefresh}
                colors={[PrimaryColor, SecondaryColor, 'white']}
                progressBackgroundColor="pink"
                onRefresh={this.retrieveData}
                enabled={true}
                
              />
            }
            // How Close To The End Of List Until Next Data Request Is Made
            onEndReachedThreshold={0.1}
            showsVerticalScrollIndicator={false} //hides the vertical scroll
            refreshing={this.state.refreshing}
          />`

**Comment by fukemy** [comment]
same problem here, refreshControl does not show first time in useEffect even i set showState to true
```
refreshControl={
          <RefreshControl
            tintColor={theme.mainOrangeColor}
            refreshing={isRefreshing}
            onRefresh={() => {
              console.log('onrefresh')
              skip = 0
              _getRoomList()
            }}
          /> 
        }
```

**Comment by madebyrogal** [comment]
The issue is still there in iOS.
RN ver: 0.71.8

**Comment by fukemy** [comment]
I am trying to implement release to refresh, not pull to refresh but not working

**Comment by fswienty** [comment]
The issue still persists for me on Android with RN 0.72.6. When I set data={[]} in my flatlist, the refresh control works as it should, but when attempting to show data fetched via tanstack query, the refresh control will not show anymore after the list is populated.

**Comment by dcdavidheisnam** [comment]
It's still happening on iOS

**Comment by thianphat** [comment]
Happening to me as well

**Comment by alimohsinz** [comment]
i have fixed it using below workaround but i dont even know why its working.
Please also explain me if you got it.

Add ListEmptyComponent and pass loading prop to it
` <FlatList
        style={{flex: 1}}
        data={artistList}
        renderItem={({item}) => <ArtistCard item={item} />}
        refreshing={loading}
        refreshControl={
          <RefreshControl
            colors={['black']}
            tintColor="white"
            refreshing={loading}
            onRefresh={getArtistsList}
          />
        }
        ListEmptyComponent={<ListEmptyCompnent loader={loading} />}
        keyExtractor={item => `${item._id}`}
        contentContainerStyle={{
          paddingTop: 20,
        }}
      />`
      
      
      in ListEmptyCompnent if loading is true show a string with spaces inside <Text>
      `const ListEmptyCompnent = ({loader}: {loader: boolean}) => {
  const {colors, fontFamily, fontSize} = useTheme() as any;

  return (
    <View style={{justifyContent: 'center', alignItems: 'center'}}>
      {loader ? (
        // to fix loader not showing on first render
        <Text
          style={{
            color: colors.bodyText,
            fontSize: fontSize.bodyTextFont,
            fontFamily: fontFamily.mainheading,
          }}>
          {'           '}
        </Text>
      ) : (
        <Text
          style={{
            color: colors.bodyText,
            fontSize: fontSize.bodyTextFont,
            fontFamily: fontFamily.mainheading,
          }}>
          No Item to Display
        </Text>
      )}
    </View>
  );
};`
