### ISSUE TITLE
[iOS] Changing List Data during onRefresh

### ISSUE THREAD

**Issue by MCAxiaz** [facebook/react-native#24857]
Changing the data of a FlatList or SectionList while it's refreshing causes the first press after refresh to not register. Originally encountered while using SectionList and occurred in 100% of refreshes, reproduced using Flatlist in the snack below, but the issue does not occur consistently anymore.

**React Native version:**
react: 16.8.3 => 16.8.3 
react-native: 0.59.8 => 0.59.8 

## Steps To Reproduce
Refer to snack below
1. Perform a pull-down refresh on the list.
2. Attempt to press on one of the list items or the button at the bottom of the screen.
3. The first press sometimes does not register.
You may need to do several refreshes before you encounter this issue.

Now remove line 26 `data=[]`, repeat the above steps. The issue no longer occurs.

**Describe what you expected to happen:**
Presses should not be dropped.

**Snack, code example, or link to a repository:**
https://snack.expo.io/BkobJ0P2N

**Comment by kelset** [comment]
Can you reproduce this in a react-native init'd project? Expo Snack still uses RN 57, while we are currently on 0.59.x

**Comment by MCAxiaz** [comment]
Yes. Using a fresh react-native init'd project on 0.59.8, with the same code as the snack, the issue still occurs. Also noting this seems to be an iOS issue only as I cannot reproduce it on Android.

**Comment by ptrocki** [comment]
On ip 7 v.11.4 this bug does not occur.
