### ISSUE TITLE
FlatList : After loading 100 items my bottom navigation bar event working very slow

### ISSUE THREAD

**Issue by jackryu** [facebook/react-native#24874]
Hello Team,

I am new with react native I am trying to create an application but I am facing some delay issue in bottom nave bar after adding "FlatList" in my project.

Issue: after loading 100 items in my FlatList my bottom navigation bar buttons working very slow. If I am clicking on my bottom navigation bar button next screen displaying in 3-4 sec or more.

React Native version:
 

> React Native Environment Info:
>     System:
>       OS: macOS 10.14.3
>       CPU: (4) x64 Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz
>       Memory: 32.26 MB / 4.00 GB
>       Shell: 3.2.57 - /bin/bash
>     Binaries:
>       Node: 10.15.3 - /usr/local/bin/node
>       npm: 6.4.1 - /usr/local/bin/npm
>       Watchman: 4.9.0 - /usr/local/bin/watchman
>     SDKs:
>       iOS SDK:
>         Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
>     IDEs:
>       Android Studio: 3.3 AI-182.5107.16.33.5199772
>       Xcode: 10.1/10B61 - /usr/bin/xcodebuild
>     npmPackages:
>       react: 16.5.0 => 16.5.0 
>       react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
>     npmGlobalPackages:
>       react-native-cli: 2.0.1

## Steps To Reproduce

1. create FlatList using my code 
2. add bottom nav in your application
3. load data in FlatList
4. try to switch on other screen using bottom nav

```
import React, { Component } from 'react';
import { View, Text, FlatList, ActivityIndicator, TouchableOpacity } from 'react-native';
import { ListItem, SearchBar } from 'react-native-elements';

class MyList1 extends Component {
	constructor(props) {
		super(props);
		this.state = {
			loading: false,
			data: [],
			error: null
		};
		this.arrayholder = [];
	}

	async componentDidMount() {
		await this.makeRemoteRequest();
	}

	async makeRemoteRequest() {
		const url = `https://randomuser.me/api/?&results=1000`;
		this.setState({ loading: true });

		await fetch(url)
			.then((res) => res.json())
			.then((res) => {
				this.setState({
					data: res.results,
					error: res.error || null,
					loading: false
				});
				this.arrayholder = res.results;
			})
			.catch((error) => {
				this.setState({ error, loading: false });
			});
	}

	renderSeparator = () => {
		return (
			<View
				style={{
					height: 1,
					width: '86%',
					backgroundColor: '#CED0CE',
					marginLeft: '14%'
				}}
			/>
		);
	};

	searchFilterFunction = (text) => {
		this.setState({
			value: text
		});

		const newData = this.arrayholder.filter((item) => {
			const itemData = `${item.name.title.toUpperCase()} ${item.name.first.toUpperCase()} ${item.name.last.toUpperCase()}`;
			const textData = text.toUpperCase();

			return itemData.indexOf(textData) > -1;
		});
		this.setState({
			data: newData
		});
	};

	renderHeader = () => {
		return (
			<SearchBar
				placeholder="Type Here..."
				lightTheme
				round
				onChangeText={(text) => this.searchFilterFunction(text)}
				autoCorrect={false}
				value={this.state.value}
			/>
		);
	};

	render() {
		if (this.state.loading) {
			return (
				<View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
					<ActivityIndicator />
				</View>
			);
		}
		return (
			<View style={{ flex: 1 }}>
				<FlatList
					data={this.state.data}
					renderItem={({ item }) => (
						<TouchableOpacity>
							<ListItem
								onPress={() => alert(item.name.first)}
								leftAvatar={{ source: { uri: item.picture.thumbnail } }}
								title={`${item.name.first} ${item.name.last}`}
								subtitle={item.email}
							/>
						</TouchableOpacity>
					)}
					keyExtractor={(item) => item.email}
					ItemSeparatorComponent={this.renderSeparator}
					ListHeaderComponent={this.renderHeader}
					initialNumToRender={15}
					maxToRenderPerBatch={2}
					removeClippedSubviews={true}
					onEndReachedThreshold={0.5}
					onEndReached={() => alert('data end')}
				/>
			</View>
		);
	}
}
export default MyList1;

```

Describe what you expected to happen: If I click on bottom nave button for switching between screen I don't want any delay

Snack, code example, or link to a repository:
https://snack.expo.io/@abhi.tomar/flatlist-loading-issue

## Application Images

![WhatsApp Image 2019-05-16 at 7 53 29 AM](https://user-images.githubusercontent.com/6933841/57816998-ff6fa600-77af-11e9-873f-1abceb4f9346.jpeg)
![WhatsApp Image 2019-05-16 at 7 53 49 AM](https://user-images.githubusercontent.com/6933841/57817000-01396980-77b0-11e9-86d3-d8924c7c4a32.jpeg)

##If am toggle between home and mentor screen its takes more then 3 sec

**Comment by kelset** [comment]
👋 there - it seems that your issue here is not really caused by a bug but by your code; in any case, there are already quite a few issues open on this subject, in particular, I'd suggest you take a look at https://github.com/facebook/react-native/issues/13413#issuecomment-438664082

Also, this could help you https://facebook.github.io/react-native/docs/performance
and this too, since you are using react-navigation: https://github.com/kmagiera/react-native-screens
