### ISSUE TITLE
👻 Flow Typing NativeModules

### ISSUE THREAD

**Issue by RSNara** [facebook/react-native#24875]
# Flow Typing NativeModules

The TurboModule system is nearly feature-complete on both Android and iOS. Before we rollout the system, we'd like to migrate all our OSS NativeModules to use it. As a prerequisite for this migration, all the the NativeModules must have spec files. There are currently 41 NativeModules in total, so there is a bunch of work to do. We'd love to use this as an opportunity to help get more people involved by contributing to React Native.

## Instructions

1. Pick an unclaimed module and comment that you're working on it.
2. Create a Spec file called `NativeXYZ.js`, where `XYZ` is the name of the NativeModule.
3. Define flow types based on the NativeModule's native methods.
4. Change call-sites from `NativeModules.XYZ` to `NativeXYZ`
5. Make sure flow passes
6. Do one module per PR

## What is a Spec file?

A Spec file looks like this:

### NativeAnalytics.js

```typescript
/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @flow strict-local
 * @format
 */

'use strict';

import type {TurboModule} from 'RCTExport';
import * as TurboModuleRegistry from 'TurboModuleRegistry';

export interface Spec extends TurboModule {
  +getConstants: () => {|
    constant1: string,
    constant2: boolean,
  |};
  +logCounter: (key: string, value: number) => void;
  +logEvent: (eventName: string, data: Object, analyticsModule: ?string) => void;
  +logRealtimeEvent: (
    eventName: string,
    data: Object,
    analyticsModule: ?string,
  ) => void;
}

export default TurboModuleRegistry.getEnforcing<Spec>(
  'Analytics',
);
```

### Observations

* **We use `TurboModuleRegistry.getEnforcing<Spec>('Analytics')` as opposed to `NativeModules.Analytics` to require the NativeModule.** `TurboModuleRegistry.getEnforcing` is an indirection that allows us to require both NativeModules and TurboModules. It throws if the NativeModule isn't there. In the case that a NativeModule is platform-specific, please use Platform.OS and conditionally call `TurboModuleRegistry.getEnforcing`.
* **Each Spec file exports an `interface` called `Spec` that extends `TurboModule`.** This interface contains typings for methods exposed by the NativeModule/TurboModule.
* **NativeModule constants are declared in the return type of the `getConstants()` method.** The old way of accessing constants as properties on NativeModule objects is deprecated and unsupported by the TurboModule system. On iOS, these constants map to the return type of `constantsToExport` in iOS and `getConstants` in Android.
* **Each Spec file is named `Native*.js`.** The filename matters because our codegen uses it to name the generated Java interfaces, ObjC protocols, and C++ TurboModule subclasses. `NativeAnalytics.js`, for instance, will generate a Java interface and ObjC protocol called `NativeAnalyticsSpec`, and a C++ TurboModule class called `NativeAnalyticsSpecJSI`. After these Spec files are typed, we'll generate and check in the codegen output into this repository. Then, after we open source our codegen, we'll delete the generated interfaces, protocols, and C++ classes from this repository.
    * Note that the naming convention used here is not finalized, but stable enough for the time being.
* **This isn't a ViewManager**. We're currently not focusing on ViewManagers. Therefore, there's no need to write spec files for them.
* **We're not using imported types.** Our codegen doesn't support imported types. So, for the time being, all types used by the spec must be declared in the same file. 

### Supported Types

* Methods with simple args:
    * `string`
    * `boolean`
    * `number`
    * `Object`
    * `Array<*>*`
* `Function` and typed function:
    * Methods with nullable args
    * `?string`
    * `?Object`
    * `?Array<*>*`
    *  `?Function` and nullable typed function
    * `number` and `boolean` are **not** supported
* Methods with **inline** complex Object typed args
    * e.g. `(x: {|foo: string, ... |}) => void`
* Methods that return a `Promise<*>*` 
* Synchronous methods that return simple **non-nullable** types
    * `string`
    * `number`
    * `boolean`
    * `Object`
    * `Array<*>*` 
* Optional methods with all variants above
* Typed exported constants
* **Note:** Flow unions aren't supported

## How do you type NativeModules?

You have to deduce the types by looking at the NativeModule implementations on iOS and Android. Some NativeModules already have JS wrappers, so you could also look at those for writing the Spec files.

### Guidelines

* How do you know which methods are exported to JS? 
    * On Android: Look for NativeModule non-inherited class methods annotated with `@ReactMethod`.
    * On iOS: Look for NativeModule non-inherited and inherited class methods wrapped in `RCT_EXPORT_*_METHOD` macros . 

* How do you know when a method should have a `Promise` return type?
    * On Android: The last argument of the method is the `Promise` object.
    * On iOS: The last two arguments are a `RCTPromiseResolveBlock` and `RCTPromiseRejectBlock`

* What should the JS method name be?
    * On Android: It's the name of the Java method.
    * On iOS: It's the part of the selector before the first argument/color.
* `NSDictionary` on iOS, and `ReadableMap` and `WritableMap` on Android translate to object literals in JS.
* `RCTResponseSenderBlock` and `RCTResponseErrorBlock` on iOS, and `Callback` on Android translate to function literals in JS.
* Try to avoid using `Function` and `Object` whenever possible. 
* In the case that a method or constant is unavailable on one platform, make it optional. 
* In the case that a NativeModule is unavailable on one platform, make it optional.
* Where do you put the Spec file?
    * Most NativeModules belong to a Library (see the JS section of the table below), so you could write the Spec in the library. For the other NativeModules, write the spec inside `react-native-github/Libraries/NativeModules/specs`.

## Platform-specific NativeModules

For platform-specific NativeModules, use `Platform.OS` to conditionally call `TurboModuleRegistry.getEnforcing<Spec>`. When changing the call-sites of these NativeModules, you may have to guard them with null checks to please flow.

### Call-site Before

```typescript
const NativeModules = require('NativeModules');
const IntentAndroid = NativeModules.IntentAndroid;

function foo() {
  if (Platform.OS === 'android') {
    IntentAndroid.method();
  }
}
```

### Call-site After

```typescript
const NativeIntentAndroid = require('NativeIntentAndroid');
const {Platform} = require('react-native');

function foo() {
  if (Platform.OS === 'android') {
    if (NativeIntentAndroid != null) {
      NativeIntentAndroid.method();
    }
  }
}
```

## NativeModule List

Please claim a NativeModule from the list below. 

⬜️ - Unclaimed
🚧 - Claimed / PR in progress
✅ - PR Merged

|Status |JS Name  |JS NativeModule Wrappers |iOS  |Android  |
|---  |---  |---  |---  |---  |
| ✅ |AccessibilityInfo  |[react-native-github](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/)/[Libraries](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/)/[Components](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/Components/)/[AccessibilityInfo](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/Components/AccessibilityInfo/)/AccessibilityInfo.android.js  | |AccessibilityInfoModule.java |
| ✅ |AccessibilityManager |[react-native-github](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/)/[Libraries](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/)/[Components](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/Components/)/[AccessibilityInfo](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/Components/AccessibilityInfo/)/AccessibilityInfo.ios.js  |RCTAccessibilityManager.m  | |
| ✅ |AlertManager |[react-native-github](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/)/[Libraries](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/)/[Alert](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/Alert/)/Alert.js  |RCTAlertManager.m  | |
| ✅ |AnimationDebugModule | | |AnimationsDebugModule.java |
| ✅ |AppState |[react-native-github](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/)/[Libraries](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/)/[AppState](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/AppState/)/AppState.js |RCTAppState.m  |AppStateModule.java  |
| ✅ |BlobModule |[react-native-github](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/)/[Libraries](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/)/[Blob](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/Blob/)/BlobManager.js  |RCTBlobManager.mm  |BlobModule.java  |
| ✅ |DatePickerAndroid  |[react-native-github](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/)/[Libraries](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/)/[Components](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/Components/)/[DatePickerAndroid](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/Components/DatePickerAndroid/)/DatePickerAndroid.android.js  | |DatePickerDialogModule.java  |
| ✅ |DevLoadingView |[react-native-github](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/)/[Libraries](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/)/[Utilities](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/Utilities/)/HMRLoadingView.ios.js |RCTDevLoadingView.m  | |
| ✅ |DevSettings  |N/A  |RCTDevSettings.mm  |DevSettingsModule.java |
| ✅ |DeviceEventManager |N/A  | |DeviceEventManagerModule.java  |
| ✅ |DeviceInfo |[react-native-github](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/)/[Libraries](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/)/[Utilities](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/Utilities/)/DeviceInfo.js |RCTDeviceInfo.m  |DeviceInfoModule.java  |
| ✅ |DialogManagerAndroid |N/A  | |DialogModule.java  |
| ✅ |ExceptionsManager  |[react-native-github](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/)/[Libraries](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/)/[Core](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/Core/)/ExceptionsManager.js  |RCTExceptionsManager.m |ExceptionsManagerModule.java |
| ✅ |FileReaderModule |N/A  |RCTFileReaderModule.m  |FileReaderModule.java  |
| ✅ |HeadlessJsTaskSupport  |N/A  | |HeadlessJsTaskSupportModule.java |
| ✅ |I18nManager  |[react-native-github](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/)/[Libraries](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/)/[ReactNative](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/ReactNative/)/I18nManager.js  |RCTI18nManager.m |I18nManagerModule.java |
| ✅ |ImageEditor  |N/A  |RCTImageEditingManager.m |ImageEditingModule.java |
| ✅ |ImageStore |N/A  |RCTImageStoreManager.m | ImageStoreManager.java |
| ✅ |IntentAndroid  |[react-native-github](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/)/[Libraries](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/)/[Linking](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/Linking/)/Linking.js  | |IntentModule.java  |
| ✅ |JSCHeapCapture |[react-native-github](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/)/[Libraries](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/)/[Utilities](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/Utilities/)/HeapCapture.js  | |JSCHeapCapture.java  |
| ✅ |JSCSamplingProfiler  |[react-native-github](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/)/[Libraries](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/)/[Performance](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/Performance/)/SamplingProfiler.js | |JSCSamplingProfiler.java |
| ✅ |JSDevSupport |[react-native-github](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/)/[Libraries](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/)/[Utilities](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/Utilities/)/JSDevSupportModule.js | |JSDevSupport.java  |
| ✅ |KeyboardObserver |[react-native-github](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/)/[Libraries](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/)/[Components](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/Components/)/[Keyboard](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/Components/Keyboard/)/Keyboard.js (NativeEventEmitter)  |RCTKeyboardObserver.m  | |
| ✅ |LinkingManager |[react-native-github](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/)/[Libraries](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/)/[Linking](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/Linking/)/Linking.js  |RCTLinkingManager.m  | |
| ✅ |ModalManager |N/A  |RCTModalManager.m  | |
| ✅ |NativeAnimatedModule |[react-native-github](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/)/[Libraries](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/)/[Animated](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/Animated/)/[src](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/Animated/src/)/NativeAnimatedHelper.js |RCTNativeAnimatedModule.m  |NativeAnimatedModule.java  |
| ✅ |Networking |[react-native-github](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/)/[Libraries](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/)/[Network](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/Network/)/RCTNetworking.android.js  |RCTNetworking.mm |NetworkingModule.java  |
| ✅ |[react-native-github](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/)/[Libraries](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/)/[Network](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/Network/)/RCTNetworking.ios.js  |
| ✅ |PermissionsAndroid |[react-native-github](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/)/[Libraries](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/)/[PermissionsAndroid](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/PermissionsAndroid/)/PermissionsAndroid.js | |PermissionsModule.java |
| ✅ |PlatformConstants  |[react-native-github](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/)/[Libraries](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/)/[Utilities](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/Utilities/)/Platform.android.js |RCTPlatform.m  |AndroidInfoModule.java |
| ✅ |[react-native-github](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/)/[Libraries](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/)/[Utilities](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/Utilities/)/Platform.ios.js |
| ✅ |RedBox |N/A  |RCTRedBox.m  | |
| ✅ |SettingsManager  |[react-native-github](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/)/[Libraries](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/)/[Settings](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/Settings/)/Settings.ios.js |RCTSettingsManager | |
| ✅ |SourceCode |[react-native-github](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/)/[Libraries](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/)/[Share](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/Share/)/Share.js  |RCTSourceCode.m  |SourceCodeModule.java  |
| ✅ |TVNavigationEventEmitter |[react-native-github](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/)/[Libraries](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/)/[Components](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/Components/)/[AppleTV](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/Components/AppleTV/)/TVEventHandler.js |RCTTVNavigationEventEmitter.m  | |
| ✅ |TimePickerAndroid  |[react-native-github](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/)/[Libraries](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/)/[Components](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/Components/)/[TimePickerAndroid](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/Components/TimePickerAndroid/)/TimePickerAndroid.android.js  | |TimePickerDialogModule.java  |
| ✅ |[react-native-github](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/)/[Libraries](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/)/[Components](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/Components/)/[TimePickerAndroid](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/Components/TimePickerAndroid/)/TimePickerAndroid.ios.js  |
| ✅ |Timing |[react-native-github](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/)/[Libraries](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/)/[Core](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/Core/)/[Timers](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/Core/Timers/)/JSTimers.js |RCTTiming.m  |Timing.java  |
| ✅ |ToastAndroid |[react-native-github](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/)/[Libraries](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/)/[Components](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/Components/)/[ToastAndroid](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/Components/ToastAndroid/)/ToastAndroid.android.js | |ToastModule.java |
| ✅ |UIManager  | |RCTUIManager.m |UIManagerModule.java |
| ✅ |WebSocketModule  |[react-native-github](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/)/[Libraries](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/)/[WebSocket](https://phabricator.internmc.facebook.com/diffusion/FBS/browse/master/xplat/js/react-native-github/Libraries/WebSocket/)/WebSocket.js  |RCTWebSocketModule.m |WebSocketModule.java |

**Comment by ericlewis** [comment]
@RSNara any examples on how to handle event emitter classes?

**Comment by fkgozali** [comment]
> any examples on how to handle event emitter classes?

```
export interface Spec extends TurboModule {
  +getConstants: () => {|
    // any constants it exports
  |};

  // add any exported methods

  // Then add these 2 methods:

  // RCTEventEmitter
  +addListener: (eventName: string) => void;
  +removeListeners: (count: number) => void;
}
```

**Comment by ericlewis** [comment]
Also worth noting: there are some places in the code base that directly access constants in JS, they need to be changed to be grabbed from getConstants. Example:
```javascript
const DeviceInfo = require('./DeviceInfo');
dims = DeviceInfo.Dimensions;
```
becomes:
```javascript
const DeviceInfo = require('./DeviceInfo');
dims = DeviceInfo.getConstants().Dimensions;
```

luckily, flow will complain about these if you do your typing right! So, just update the callsites.

**Comment by michalchudziak** [comment]
Hey! I'd like to help with `Linking` module.

**Comment by Krizzu** [comment]
Hi, I can help with `PermissionsAndroid`

**Comment by gedeagas** [comment]
Hi, I would like to help with `DeviceInfo `

**Comment by fkgozali** [comment]
@michalchudziak, @gedeagas both were done by &ericlewis’ PRs

**Comment by Krizzu** [comment]
@fkgozali I see, what about `TimePickerAndroid ` ? If it's free, I'd take it

**Comment by fkgozali** [comment]
PermissionAndroid/TimePickerAndroid are still open I think

**Comment by Krizzu** [comment]
I'll go with `PermissionsAndroid` then

**Comment by michalchudziak** [comment]
Sure, no problem! Is it possible to work on `ExceptionsManager `?

**Comment by michalchudziak** [comment]
Sure, no problem! Is it possible to work on `AccessibilityManager `?

**Comment by lukewalczak** [comment]
I can go with `AlertManager`

**Comment by wojteg1337** [comment]
I work on `ToastAndroid`

**Comment by thymikee** [comment]
Taking `Networking`

**Comment by jeanregisser** [comment]
Working on `Timing`

**Comment by jeanregisser** [comment]
Working on `WebSocketModule`

**Comment by chakrihacker** [comment]
Taking `ToastAndroid`

**Comment by wojteg1337** [comment]
Working on HeapCapture

**Comment by chakrihacker** [comment]
Working on `IntentAndroid`

**Comment by abhiin1947** [comment]
Working on `ModalManager`

**Comment by jeanregisser** [comment]
@RSNara what about the case where the native method definition differs on iOS and Android?

This is what I did sofar for the `close` method of [WebSocketModule](https://github.com/facebook/react-native/pull/24893/files#diff-e556a43ea770a609461bcd916e6c24cc):

```js
// Native close method definition on Android
declare function close(code: number, reason: string, socketID: number): void;
// Native close method definition on iOS
declare function close(socketID: number): void;

export interface Spec extends TurboModule {
  +connect: (
    url: string,
    protocols: ?Array<string>,
    options: ?{headers?: {origin?: string}},
    socketID: number,
  ) => void;
  +send: (message: string, socketID: number) => void;
  +sendBinary: (base64String: string, socketID: number) => void;
  +ping: (socketID: number) => void;
  +close: typeof close;

  // RCTEventEmitter
  +addListener: (eventName: string) => void;
  +removeListeners: (count: number) => void;
}
```

**Comment by thymikee** [comment]
@jeanregisser I had similar issue with Networking module: https://github.com/facebook/react-native/pull/24892 and after consulting ideas with @rickhanlonii we decided to create two native modules for now: `NativeNetworkingIOS` and `NativeNetworkingAndroid` as even when using `Platform.OS` check, Flow mixed 2 definitions resulting in errors of wrong signature being used.

**Comment by jeanregisser** [comment]
Working on `TimePickerAndroid`

**Comment by jeanregisser** [comment]
Working on `TVNavigationEventEmitter`

**Comment by jeanregisser** [comment]
Working on `SourceCode`

**Comment by uqmessias** [comment]
Working on `NativeAnimatedModule` \o/

**Comment by zhongwuzw** [comment]
Taking `ExceptionsManager`.

**Comment by ericlewis** [comment]
Taking UIManager

**Comment by sasurau4** [comment]
Working on AlertManager

**Comment by yjose** [comment]
Taking `ImageLoader `

**Comment by raphaeleidus** [comment]
can I take `DevSettings`?

**Comment by sattaman** [comment]
I'll take Platform.android.js

**Comment by ericlewis** [comment]
I will take JSCSamplingProfiler

**Comment by ericlewis** [comment]
Will take FileReaderModule

**Comment by glenna** [comment]
i'll take `DevLoadingView`

**Comment by ericlewis** [comment]
I will take JSDevSupport

**Comment by thymikee** [comment]
Taking NativeAnimatedModule

**Comment by fkgozali** [comment]
Thank you all for doing the work! We're halfway there :)

**Comment by ericlewis** [comment]
Taking HeadlessJsTaskSupport

**Comment by ericlewis** [comment]
Will take I18nManagerModule

**Comment by ericlewis** [comment]
taking BlobModule

**Comment by uqmessias** [comment]
Working on `DialogManagerAndroid`

**Comment by pedpess** [comment]
taking `DatePickerAndroid`

**Comment by uqmessias** [comment]
Taking `DeviceEventManager`

**Comment by uqmessias** [comment]
Taking `ImageViewManager`

**Comment by ericlewis** [comment]
taking AnimationDebugModule

**Comment by fkgozali** [comment]
@uqmessias:

Actually viewmanagers shouldn’t be typed, re: ImageViewManager

**Comment by uqmessias** [comment]
@fkgozali 
I was almost finishing, but I'll stop it and keep the current code in a separated branch.

**Comment by ericlewis** [comment]
ImageViewManager & RedBox remaining.

**Comment by yjose** [comment]
@fkgozali  can you check the `ImageLoader` mapping ios and android files in the table: `RCTImageEditingManager.m` and `ImageLoaderModule.java` look like something wrong?

**Comment by uqmessias** [comment]
@yjose,
I [was working](https://github.com/facebook/react-native/compare/master...uqmessias:feat/spec-image-view-manager?expand=1) on something related to this one

**Comment by yjose** [comment]
@uqmessias hmm ok 

>  Actually` viewmanagers shouldn’t be typed, re: ImageViewManager
in this case, I think they mean `ImageEditor` which have the correct ios and android files `RCTImageEditingManager.m` and `ImageEditingManager.java`?

**Comment by ericlewis** [comment]
@yjose i think you are correct

**Comment by yjose** [comment]
working on `ImageEditor`

**Comment by ericlewis** [comment]
We got 'em all i think

**Comment by jarvisluong** [comment]
Taking Platform.ios.js

**Comment by mitulsavani** [comment]
I would like to help with ` AppState` . Let's get started right away.

**Comment by thymikee** [comment]
@mitulsavani AppState is already done and merged. Please have a look at "NativeModule List" section of the original post. Looks like the only one left is "TimePickerAndroid.ios.js" – feel free to grab it while it's free! (and please check https://github.com/facebook/react-native/pull/24897/files because it may overlap, so it may be better to cooperate with the author, @jeanregisser, on this one)

**Comment by mitulsavani** [comment]
I would certainly like to claim that. Although i have no clue how and what needs to change/add, but I want to at least give a shot!  @thymikee

**Comment by jeanregisser** [comment]
@mitulsavani @thymikee indeed https://github.com/facebook/react-native/pull/24897 addresses `TimePickerAndroid.ios.js` as well.

**Comment by mitulsavani** [comment]
@jeanregisser I see that your PR addresses the `TimePickerAndroid.ios.js`, but should I still go ahead and work on the iOS specific platform? I think I am bit confused here, sorry.

**Comment by fkgozali** [comment]
Thanks all for the PRs, we're going through them one by one to ensure nothing else breaks in FB internal infra. Stay tuned!

**Comment by fkgozali** [comment]
It looks like `ImageStore` got left out. For anyone interested, feel free to claim it.

**Comment by mitulsavani** [comment]
I hereby claim for it.

**Comment by fkgozali** [comment]
`DevSettings` was also left out, feel free to claim.

**Comment by jarvisluong** [comment]
I will claim the ‘DevSetting’

**Comment by fkgozali** [comment]
As of https://github.com/facebook/react-native/commit/18fededae085b53b01e54a7ed27e32c2318e7cae, [all 42 PRs](https://github.com/facebook/react-native/issues?q=label%3A%22Native+Module%22+is%3Aclosed) have now been merged! Thank you for all the contributions to this effort!

I'll close this issue for now.

**Comment by fkgozali** [comment]
In order to get a sense of how the codegen output looks like, https://github.com/facebook/react-native/commit/b1bf133d69cf06629fb1beeeaf23ccd418bec242 checked them in, based on all the Flow types you all have added. This is not used yet, and we're working on migrating each module to use it gradually.

**Comment by patrice4github** [comment]
Hi,

In the instructions, we can read:

> Create a Spec file called NativeXYZ.js, where XYZ is the name of the NativeModule.

How strict is this rule?

There's no `NativePlatformConstants.js` anywhere, rather there I see both  `NativePlatformConstantsIOS.js` and `NativePlatformConstantsAndroid.js`. Is that going to through a wrench in the cogs?

[https://github.com/react-native-community/discussions-and-proposals/issues/40#issuecomment-537056284](https://github.com/react-native-community/discussions-and-proposals/issues/40#issuecomment-537056284)
