### ISSUE TITLE
Allow configuration of bundler port via env or project level config

### ISSUE THREAD

**Issue by atrauzzi** [facebook/react-native#24895]
It appears as though right now the only way to change the metro bundler port is by manually starting the bundler, passing in a different setting and then manually changing it in the running app.  Based on what I'm reading in the documentation, all this has to be done by hand.  Per machine, per checkout, per emulator, per app install.

It goes without saying, but this is a considerable inconvenience.

For people using a local development environment, ports in the `808*` range tend to be already allocated.  We manage a local development environment and each service that we have in our stack is allocated a port according to a convention.

The current option for configuring the bundler port is insufficient.  It needs to be configurable in such a way that I can either commit the configuration to source control, or maintain some value in my environment that gets passed during builds.  Most importantly, it has to require zero manual steps so that someone checking out our projects for the first time has minimal to no manual gotchas.

**Comment by atrauzzi** [comment]
I just want to add that I think it's incredibly poor form to suggest to people that they modify files in `node_modules`, as per [the official troubleshooting doc](https://facebook.github.io/react-native/docs/troubleshooting.html#port-already-in-use).

A project such as react native shouldn't be playing it fast and loose with advice that might also cause people to misuse their vendor dependencies.

**Comment by atrauzzi** [comment]
I don't think the template is applicable in this scenario.

**Comment by atrauzzi** [comment]
Yeah, still needs attention.

**Comment by atrauzzi** [comment]
Still requires attention.

**Comment by hramos** [comment]
Just saw this issue. In cases where the issue template is not applicable, it might be worth considering using the discussions repo instead: https://github.com/react-native-community/discussions-and-proposals

**Comment by atrauzzi** [comment]
But it's not a discussion?

**Comment by atrauzzi** [comment]
Not stale.

**Comment by atrauzzi** [comment]
Not stale.

**Comment by atrauzzi** [comment]
Not stale.
