### ISSUE TITLE
Loading RN App from Url, Auto-Update JS.  

### ISSUE THREAD

**Issue by doronaviguy** [facebook/react-native#2489]
My idea , is to load my RN app from url ,
to achieve auto-update capabilities to my app.
My quesiton in StackOverflow [here](http://stackoverflow.com/questions/31900094/react-native-auto-update-js-files/32283859) 

In the beginning i thought there two ways to solve it.
- New Require2 fn , inside the v8 engine, the function, will have **Require2(jsUrl, staticFallbackJs)** this way i could load js files remotely, in case of no conectivty it will load a static resource. 
- Native module , that updates  the js bundle on every load. 

After i played with the environment, my conclusion was different, 

changing jsCodeLocation variable in AppDelegate.m , to my own compiled js.

    //Point RN to my complied js file  
    jsCodeLocation = [NSURL URLWithString:@"http://s3-bucket.com/index.ios.bundle.js"];

**index.ios.bundle.js** content is the minified dev version of RN webpack server ,
*http://localhost:8081/index.ios.bundle?dev=false&minify=true*

Pointing  jsCodeLocation variable to my **bundle.js** url  gives the following:  
 - Auto update app , js can be updated to end users , without releasing a new app
 - Dynamic npm modules as long as they are pure js.
- I still have to handle a static version , and to check connectivity , on load time .

I be happy to hear thoughts ,and ideas about this solution.

**Comment by brentvatne** [comment]
Hi there, this is discussion is better suited for http://discuss.reactjs.org/, StackOverflow, IRC or Slack.

Also check out:

- https://github.com/reployapp/react-native-versions
- https://apphub.io/
