### ISSUE TITLE
[Animated] Listen on interpolated value

### ISSUE THREAD

**Issue by browniefed** [facebook/react-native#2493]
Edit: Is the idea to move towards CoreAnimation so the values don't actually live in the JS world?

Animated is great but to do some interactions especially with `getAnimatedValue` privatized it's getting a little hard to do things.
You can't add a listener to interpolated values, so that makes it hard to derive another state from an interpolated value in an event listener.

An animation I was attempting to make was the youtube video animation. Meaning scale of the video is interpolated from the y, however the X needs to be calculated from the state of the Y, scale, and calculate the video width to determine the offset needed. But without listening on the scale I can't get the current scale value without calling `getAnimatedValue` in the listener on y.

Some example code

```
  getScalePosition: function() {
    var scale = this.state.position.y.interpolate({
      inputRange: [0, deviceHeight + (videoHeight * 5) ], //THIS IS WEIRD
      outputRange: [1, .2],
      extrapolate: 'clamp'
    });

    var translateY = this.state.position.y.interpolate({
      inputRange: [0, deviceHeight],
      outputRange: [0, deviceHeight + 20],
      extrapolate: 'clamp'
    });


    this.state.position.y.addListener((value) => {
      var scaleValue = scale.getAnimatedValue(); // I need this but have no way but getAnimatedValue
      var x = scaleValue * deviceWidth;
      var buffer = ((deviceWidth - x)/2);

      this.state.position.x.setValue(buffer);
    })

    return {
      transform: [
        {scale: scale},
        {translateX: this.state.position.x},
        {translateY: translateY}
      ]
    }
  },
```

![http://i.imgur.com/llVGstz.gif](http://i.imgur.com/llVGstz.gif)

**Comment by brentvatne** [comment]
@browniefed - what if you interpolate on the scale interpolation?

    var scale = this.state.position.y.interpolate({
      inputRange: [0, deviceHeight + (videoHeight * 5) ], //THIS IS WEIRD
      outputRange: [1, .2],
      extrapolate: 'clamp'
    });

    var translateX = scale.interpolate({
      inputRange: [1, .2],
      outputRange: [ ---- ], // Fill in whatever here
    });

**Comment by browniefed** [comment]
Oh for some reason didn't realize you could interpolate on an interpolate. I'll give it a shot. Thanks.

Although being able to add a listener on an interpolated value would be beneficial.

**Comment by brentvatne** [comment]
yeah that could be useful cc @sahrens @vjeux
