### ISSUE TITLE
How to Disable Display Size/Zoom on Android/iOS

### ISSUE THREAD

**Issue by mazenchami** [facebook/react-native#24933]
I am looking to disable Display Size scaling on Android. I have been able to sort out text size scaling by using allowFontScaling={false} but I cannot find a way to do the same for display size. When display size is increased, all my Views get mashed together making the app impossible to use.

React Native version:
info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
      Memory: 906.21 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.4.1 - ~/.nvm/versions/node/v10.4.1/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.4.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.0, 25.0.2, 25.0.3, 26.0.2, 27.0.3, 28.0.3
        System Images: android-25 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.4 => 0.59.4 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-create-library: 3.1.2
      react-native-git-upgrade: 0.2.7

## Steps To Reproduce

1. (Android) - Settings > Display > Display Size > Grow or Shrink and see how app adjusts
2. (iOS) - Settings > Display & Brightness > View > Zoomed - see how app adjusts

**Comment by ptrocki** [comment]
https://stackoverflow.com/questions/28395842/iphone6-display-zoom-functionality-disturbs-the-whole-view 

On native side, this is done by autolayout. Probably it should be handled by yoga somehow ?

**Comment by renishghetia** [comment]
any update on this ? facing same issue.

**Comment by Bardiamist** [comment]
I have facing with this, any solution?

**Comment by decodedmrq** [comment]
+1

**Comment by decodedmrq** [comment]
I think we should use flex layout for app, just try facebook app also cannot disable for screen zoom.

**Comment by glburgess** [comment]
has there been any solution or work around for this aside from instructing the app user to adjust their device?

**Comment by RubenPonce** [comment]
I also have this problem

**Comment by ranggabadrus** [comment]
any update?

**Comment by Deboracgs** [comment]
any update?

**Comment by RubenPonce** [comment]
Unfortunately I do not believe there is a way to disable zoomed mode. I just calculated the zoom of the screen and changed some styling. If you do start an app, make sure to incorporate some dynamic widths so that this issue doesn't come up in production. With this code you could theoretically just show an alert with instructions to change their zoomed settings if it's that direly needed. 

```js
  const { height } = Dimensions.get("window");
    const is_zoomed = height < heightOfDeviceYouWantToTarget

    if (is_zoomed) {
      // change your styles to match zoomed mode
    }
```

**Comment by Deboracgs** [comment]
I did make this code, to for replace the original fontsize, you can use in this mode

 fontSize: getFontSize(18)

this is works for me in scale mode, font size large mode, and differents dpi, you can use this for height too.

```
getFontSize: (originalSize) => {
        if(PixelRatio.get() < 1.5) {
            return (originalSize * 0.5 ) / PixelRatio.get() 
        }else if(PixelRatio.get() >= 1.5 && PixelRatio.get() < 2.5) {
            return (originalSize * 1.5 ) / PixelRatio.get() 
        }else if(PixelRatio.get() >= 2.5){
            return (originalSize * 2.5 ) / PixelRatio.get() 
        }else{
            return originalSize
        }
    }
```
