### ISSUE TITLE
Docs: Missing info in the Pull Requests page about how to build and run project

### ISSUE THREAD

**Issue by dmkato** [facebook/react-native#24942]
In the [Pull Request wiki](https://github.com/facebook/react-native/wiki/Pull-Requests#getting-ready-to-submit-your-first-pull-request), the section on Implementing your changes has no mention on how to run or build the project. Someone new to NPM may not know that they need to run npm install to gather dependencies, and that they are able to sue the commands in the package.json.

**Comment by muneebsajjad** [comment]
@dmkato I agree with you, I am looking for my first PR, I can take this up. however  do this issue need any **acknowledgment** or **approval** before, I made any PR for this!!

**Comment by Nikunkanani** [comment]
માં પુલ વિનંતી વિકિ , તમારા ફેરફારો અમલીકરણ પર કલમ કેવી રીતે ચલાવી શકો છો અથવા પ્રોજેક્ટ બિલ્ડ કરવા માટે કોઈ ઉલ્લેખ છે. એનપીએમમાં ​​કોઈ નવું ન જાણતું હોત કે નિર્ભરતાને એકત્રિત કરવા માટે તેમને એનપીએમ ઇન્સ્ટોલ કરવાની જરૂર છે, અને તેઓ પેકેજ.જેએસએસમાં આદેશો સુનાવણી કરી શકે છે.
