### ISSUE TITLE
Native Component (Android) not show nothing

### ISSUE THREAD

**Issue by Navidhp** [facebook/react-native#24946]
React Native version:59.8

## Steps To Reproduce

1.write native component step by step like react native documentation but return nothing (white screen)

VideoPlayerPackage.java

package com.videoPlayer;
import com.facebook.react.ReactPackage;
import com.facebook.react.bridge.NativeModule;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.uimanager.ViewManager;
import com.videoPlayer.VideoPlayerManager;
import java.util.Collections;
import java.util.List;

public class VideoPlayerPackage implements ReactPackage {

@Override
public List<NativeModule> createNativeModules(ReactApplicationContext reactContext) {
    return Collections.emptyList();
}

@Override
public List<ViewManager> createViewManagers(ReactApplicationContext reactContext) {
    return Collections.<ViewManager>singletonList(new VideoPlayerManager());
}
}
------------------------
VideoPlayerManager.java
import android.os.Build;
import android.support.annotation.Nullable;
import android.support.annotation.RequiresApi;
import android.view.View;

import com.facebook.react.bridge.ReadableMap;
import com.facebook.react.uimanager.SimpleViewManager;
import com.facebook.react.uimanager.ThemedReactContext;
import com.facebook.react.uimanager.annotations.ReactProp;

public class VideoPlayerManager extends SimpleViewManager {

private static final String VIDEO_SOURCE = "src";
private static final String PROP_URI = "uri";

@Override
public String getName() {
    return "VideoPlayer";
}

@Override
public VideoPlayerView createViewInstance(ThemedReactContext themedReactContext) {
            return new VideoPlayerView(themedReactContext);
}

@ReactProp(name = VIDEO_SOURCE)
public void setSource(final View videoTest, @Nullable ReadableMap src) {

}
}
---------------------
VideoPlayerView.java
import android.content.Context;
import android.net.Uri;
import android.util.AttributeSet;
import android.widget.FrameLayout;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;

import com.facebook.react.uimanager.ThemedReactContext;
import com.novincinema.cinemamarket.R;

public class VideoPlayerView extends RelativeLayout {

public VideoPlayerView(Context context) {
    super(context);
    init();
}

public VideoPlayerView(Context context, AttributeSet attrs) {
    super(context, attrs);
    init();
}

public VideoPlayerView(Context context, AttributeSet attrs, int defStyleAttr) {
    super(context, attrs, defStyleAttr);
    init();
}

private void init() {
    inflate(getContext(), R.layout.video_test, this);
}
}

**Comment by Esemesek** [comment]
Can you format you message correctly (wrap code in \`\`\`), add results of `react-native info` command and provide repository with reproduction of this issue?

**Comment by Navidhp** [comment]
React Native info : 
`React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
      Memory: 3.78 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.12.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 26.0.0, 27.0.3, 28.0.2, 28.0.3
        System Images: android-23 | Intel x86 Atom, android-23 | Intel x86 Atom_64, android-23 | Google APIs ARM EABI v7a, android-23 | Google API
s Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-25 | Android TV Intel x86 Atom, android-25 | Intel x86 Atom, android-25 | In
tel x86 Atom_64, android-28 | Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.8 => 0.59.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1`

VideoPlayerPackage.java : 

`package com.videoPlayer;
import com.facebook.react.ReactPackage;
import com.facebook.react.bridge.NativeModule;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.uimanager.ViewManager;
import com.videoPlayer.VideoPlayerManager;
import java.util.Collections;
import java.util.List;

public class VideoPlayerPackage implements ReactPackage {

@override
public List createNativeModules(ReactApplicationContext reactContext) {
return Collections.emptyList();
}

@override
public List createViewManagers(ReactApplicationContext reactContext) {
return Collections.singletonList(new VideoPlayerManager());
}
}`

videoPlayerManagerr.java : 
`import android.os.Build;
import android.support.annotation.Nullable;
import android.support.annotation.RequiresApi;
import android.view.View;

import com.facebook.react.bridge.ReadableMap;
import com.facebook.react.uimanager.SimpleViewManager;
import com.facebook.react.uimanager.ThemedReactContext;
import com.facebook.react.uimanager.annotations.ReactProp;

public class VideoPlayerManager extends SimpleViewManager {

private static final String VIDEO_SOURCE = "src";
private static final String PROP_URI = "uri";

@override
public String getName() {
return "VideoPlayer";
}

@override
public VideoPlayerView createViewInstance(ThemedReactContext themedReactContext) {
return new VideoPlayerView(themedReactContext);
}

@ReactProp(name = VIDEO_SOURCE)
public void setSource(final View videoTest, @nullable ReadableMap src) {

}
}`

VideoPlayerView.java
`import android.content.Context;
import android.net.Uri;
import android.util.AttributeSet;
import android.widget.FrameLayout;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;

import com.facebook.react.uimanager.ThemedReactContext;
import com.novincinema.cinemamarket.R;

public class VideoPlayerView extends RelativeLayout {

public VideoPlayerView(Context context) {
super(context);
init();
}

public VideoPlayerView(Context context, AttributeSet attrs) {
super(context, attrs);
init();
}

public VideoPlayerView(Context context, AttributeSet attrs, int defStyleAttr) {
super(context, attrs, defStyleAttr);
init();
}

private void init() {
inflate(getContext(), R.layout.video_test, this);
}
}`

**Comment by Navidhp** [comment]
@Esemesek i solved this problem with inflate to addView this is my mistake :)
