### ISSUE TITLE
IOS: I encountered "Allocation failed - JavaScript heap out of memory" error when archive in Xcode

### ISSUE THREAD

**Issue by PhuongNguyenETIT** [facebook/react-native#24958]
React Native version:

## Steps To Reproduce

1.
2.

Describe what you expected to happen:

Snack, code example, or link to a repository:

**Comment by ericlewis** [comment]
@PhuongNguyenETIT this can happen when metro is bundling extremely large javascript / JSON files. If you perhaps have a giant (1-3mb or so) JSON or JS file & not enough available memory on your machine, this will fail.

**Comment by PhuongNguyenETIT** [comment]
Thanks @ericlewis. Can you guide me to handle this error?

**Comment by ericlewis** [comment]
The best guide I have is to make sure you don’t have any large JSON or JS files. Otherwise, do you have reproduction steps or an example you can provide?

Sent via Superhuman iOS ( https://sprh.mn/?vip=ericlewis777@gmail.com )
