### ISSUE TITLE
[CLI] `react-native bundle` creates offline bundle in wrong location

### ISSUE THREAD

**Issue by frantic** [facebook/react-native#2495]
Xcode project references `main.jsbundle` at `iOS/AwesomeProject/main.jsbundle` now, but `react-native bundle` still creates `iOS/main.jsbundle` file. I guess it will be easier to update sample project template to point to `iOS/main.jsbundle`

**Comment by jadsonlourenco** [comment]
same here!

**Comment by rcchen** [comment]
I'm trying to run my react-native app on my device and keep running into this issue after following the instructions on the website. Is the incorrect location causing this issue?

> Error: Invariant Violation: Application Reactor has not been registered. This is either due to a require() > error during initialization or failure to call AppRegistry.registerComponent.

**Comment by nsimmons** [comment]
This appears to be fixed in latest master. I just tested it out.

The yeoman-generator for the default project puts `main.jsbundle` in the iOS folder, and the default xcode project is configured to grab `main.jsbundle` from that location properly now.

**Comment by ide** [comment]
@nsimmons thanks for the update!
