### ISSUE TITLE
Is cmd+r refreshing working?

### ISSUE THREAD

**Issue by Desintegrator** [facebook/react-native#24969]
React Native version: 0.59.8

## Steps To Reproduce

1. run project at Xcode 10.1
2. press CMD+R to refresh 

what expected to happen: app refresh
what actually happen: nothing

**Comment by Desintegrator** [comment]
So no i also can't type anything from keyboard into emulator (only with native ios keyboard)

**Comment by MoOx** [comment]
Be sure to have the keyboard connected (the line below the one highlighted).

<img width="865" alt="image" src="https://user-images.githubusercontent.com/157534/58039700-ca5aaf00-7b33-11e9-9a06-179c9e7c7e92.png">

**Comment by Desintegrator** [comment]
My mistake - i can type into fields.
But cmd+r still doesn't work.
Keyboard connected
![image](https://user-images.githubusercontent.com/17068034/58041391-6cd55b00-7b51-11e9-8a8d-7db1ed078cb5.png)

**Comment by Desintegrator** [comment]
It was ok before updating from 0.57.7 to 0.59.8

**Comment by zhongwuzw** [comment]
@Desintegrator Strange, I think we don't change this feature a long time, can you please restart simulator and Xcode to retry? 

BTW, shake gesture also can trigger reload.

<img width="396" alt="image" src="https://user-images.githubusercontent.com/5061845/58080585-136b3b80-7be6-11e9-980b-e318f50fbeb3.png">

**Comment by Desintegrator** [comment]
> shake gesture

Yeah, shake gesture works but its longer than hotkeys
restart doesn't affect :(

**Comment by zhongwuzw** [comment]
@Desintegrator Strange, because we just override `keyCommands` of `UIResponder`, UIKit call `RCT_keyCommands` to return commands, https://github.com/facebook/react-native/blob/06c6c7c673682629073dbcb3811b6a6806253a74/React/Base/RCTKeyCommands.m#L104, can you help us to debug wether UIKit call it?
