### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by rafalgiemza** [facebook/react-native#24978]
## Steps To Reproduce

1. Go to page https://facebook.github.io/react-native/docs/javascript-environment
2. Click on 'navigator.geolocation' 

Expected behaviour:

Change href from 
`href="geolocation.md#content"`
to 
`href="geolocation"`

![image](https://user-images.githubusercontent.com/11310249/58091898-13aa0d80-7bcb-11e9-9b2b-4d5409e10a6d.png)

**Comment by Taym95** [comment]
This issue should be opened in [react-native-website](https://github.com/facebook/react-native-website) repo.

**Comment by hramos** [comment]
As @Taym95 said, please open an issue in the docs repo or send a PR. Thanks!
