### ISSUE TITLE
Modal is not transparent on Android

### ISSUE THREAD

**Issue by nes123** [facebook/react-native#24976]
Modal behaves well on IOS and is transparent while on android it shows with white background

React Native version:

   System:
      OS: macOS 10.14.4
      CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
      Memory: 13.21 GB / 32.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.6 => 16.8.6 
      react-native: ^0.59.8 => 0.59.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Steps To Reproduce

run the following rendering:
`render() {return(<Modal visible={true} transparent={true}/>)}` 

Describe what you expected to happen:

Show transparent modal

**Comment by Hermanyo** [comment]
Can you provide a minimal reproduce? Because it worked for me, I tested it in my android with code below:
> https://facebook.github.io/react-native/docs/modal

 I just doing 
```
render() {
    return (
      <View style={{ alignItems: 'center', justifyContent: 'center', marginTop: 22, height: '100%', backgroundColor: 'white' }}>
       
        <Modal
          animationType="slide"
          transparent={false}
          visible={this.state.modalVisible}
          onRequestClose={() => {
            Alert.alert('Modal has been closed.');
          }}>
          <View style={{ marginTop: 22, alignItems: 'center', }}>
            <View>
              <Text style={{color:'black'}}>Hello World!</Text>

              <TouchableHighlight
                onPress={() => {
                  this.setModalVisible(!this.state.modalVisible);
                }}>
                <Text style={{ color:'black' }}>Hide Modal</Text>
              </TouchableHighlight>
            </View>
          </View>
        </Modal> 
        <TouchableHighlight
          onPress={() => {
            this.setModalVisible(true);
          }}>
          <Text style={{ color:'black' }}>Show Modal</Text>
        </TouchableHighlight>
      </View>
    );
  } 
```
with `transparent` `true`/`false`

**Comment by dulmandakh** [comment]
Please provide reproducible demo code. I'll re-open the issue once we have demo code. Thank you
