### ISSUE TITLE
undefined is not a function (evaluating 'Uint8Array.from ...

### ISSUE THREAD

**Issue by JonBerglund** [facebook/react-native#24971]
Hello,
I seem to have a problem with Uint8Array.
The app crushes when Uin8Array.from is called (undefined for some reason).
It only happens on android environment and when debug mode is disabled.

- code line:
`let array = Uint8Array.from(atob(validFor), c => c.charCodeAt(0))`

- Bug report:
TypeError: undefined is not a function (evaluating 'Uint8Array.from((0, _base.decode)(validFor), function (c) {
          return c.charCodeAt(0);
        })')

- React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
      Memory: 42.56 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.13.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 21, 22, 23, 24, 25, 26, 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-27 | Android TV Intel x86 Atom, android-27 | Intel x86 Atom, android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.1 => 0.56.1 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

<img width="431" alt="Screen Shot 2019-05-20 at 18 08 52" src="https://user-images.githubusercontent.com/26069883/58033362-01799200-7b2d-11e9-8255-2797e2293d96.png">

**Comment by guhungry** [comment]
It is due to the old JavaScript Core. Please update React Native to 0.59.8 or try to update [android-jsc](https://github.com/react-native-community/jsc-android-buildscripts).
