### ISSUE TITLE
[Packager] Transform Error when upgrading to 0.10.0

### ISSUE THREAD

**Issue by coderdave** [facebook/react-native#2498]
I have no idea how to debug this error that I get when go to 0.10.0:

"TransformError: /Users/xxx/Documents/apps/xxx/node_modules/react-native/packager/react-packager/src/DependencyResolver/polyfills/prelude_dev.js: Unknown transformer es6.parameters specified in whitelist"

The only thing I can think of is that it's pointing to something in connection with Babel?

**Comment by brentvatne** [comment]
Try deleting your `node_modules` directory, running `npm cache clean`, and then `npm i` again

**Comment by kit2000usa** [comment]
Get the same error,

**Comment by kit2000usa** [comment]
Still get the same error, seem not really stable ~
TransformError: /Users/App/node_modules/react-native/packager/react-packager/src/DependencyResolver/polyfills/prelude_dev.js: ENOENT, open '/Users/App/node_modules/react-native/packager/react-packager/src/DependencyResolver/polyfills/prelude_dev.js'}

**Comment by kit2000usa** [comment]
npm i, 
...
npm http GET https://registry.npmjs.org/arr-diff/-/arr-diff-1.1.0.tgz
ld: library not found for -ldylib1.10.5.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Kit/Documents/PROJECTS/AJW/Shoppy/shoppy-react/Shoppy/node_modules/react-native/node_modules/babel/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v0.10.17
gyp ERR! node-gyp -v v0.10.9
gyp ERR! not ok 

....
npm http GET https://registry.npmjs.org/async-each/-/async-each-0.1.6.tgz
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/bufferutil.node
ld: library not found for -ldylib1.10.5.o
ld: library not found for -ldylib1.10.5.o
clang: clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/bufferutil.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! make: System*** [Release/validation.node] Error 1
 Darwin 14.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! gyp ERR! build error 
cwd /Users/Kit/Documents/PROJECTS/AJW/Shoppy/shoppy-react/Shoppy/node_modules/react-native/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v0.10.17
gyp ERR! node-gyp -v v0.10.9
gyp ERR! not ok 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Kit/Documents/PROJECTS/AJW/Shoppy/shoppy-react/Shoppy/node_modules/react-native/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v0.10.17
gyp ERR! node-gyp -v v0.10.9
gyp ERR! not ok

**Comment by coderdave** [comment]
hm, deleting `node_modules`, running `npm cache clean` and `npm i` worked for me.

Although I get this error quite often and is annoying.

**Comment by marklarr** [comment]
I'm getting this after upgrading from `0.9.0` to `0.10.0`. Tried `rm -rf node_modules ; npm cache clean ; npm i`, reset content and setting in the simulator, and did a clean & build. Still getting it :(

**Comment by marklarr** [comment]
Doh! I needed to restart the package manager. All is good now.

**Comment by browniefed** [comment]
@brentvatne pre-sunday-issue-close

**Comment by brentvatne** [comment]
@browniefed - :smile: :100:
