### ISSUE TITLE
Unable to connect to remote debugger, stuck at Launching Dev Tools

### ISSUE THREAD

**Issue by kieran-alh** [facebook/react-native#24986]
Using the remote debugger causes the react-native application not load. From the output of the `react-native-cli` it shows Launching Dev Tools (0/1) and it never moves. The remote debugger tab automatically launches in chrome, but localhost:8081/debugger-ui can't be reached. 

Both the iOS and Android simulators shows:

```
Runtime is not ready for debugging.
- Make sure package server is running.
- Make sure the Javascript debugger is running and not paused on a breakpoint or exception and try reloading again. 
```
### iOS Simulator
![ios-simulator](https://i.imgur.com/5h5sV9S.png)
### Chrome localhost:8081/debugger-ui
![chrome-localhost](https://i.imgur.com/o6SEKhp.png)
### react-native-cli output
![react-native-cli](https://i.imgur.com/BYdoQeo.png)
React Native version:
```info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (4) x64 Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz
      Memory: 419.88 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.15.0 - ~/.nvm/versions/node/v8.15.0/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.15.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 24, 27, 28
        Build Tools: 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.5 => 0.59.5 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

Describe what you expected to happen:
The remote debugger launches and the app loads.

This issue is occurring in both freshly created projects and in development projects, the info above is from a freshly created project.

**Comment by hamzawaleed0102** [comment]
**Workaround:** Keep dev tools open in chrome and then press "Debug JS Remotely" on device/simulator.
_If doesn't work then try restarting packager and repeating the same._

**Comment by Conviley** [comment]
I've never had sucess connecting to 
`localhost:8081/debugger-ui`
Now that i'm using expo i connect to 
`localIPv4:8081/debugger-ui` (on windows u can use `ipconfig` to find your ipv4)
and back when i wasn't using expo i connected to
`10.0.2.2:8081/debugger-ui`

I've only worked with android simulators but maybe it's worth a try?

**Comment by code-matt** [comment]
I never had to do this before but after upgrading to 59.8 I noticed CORS errors in the chrome debugger tab, even though the packager says 100%.

Installed a chrome extension to allow CORS and then it loaded fine after reconnecting the app to debugger.
