### ISSUE TITLE
Error with `http` node module

### ISSUE THREAD

**Issue by ilanolkies** [facebook/react-native#24998]
Error when trying to use `web3` with React Native. 

```
error: bundling failed: Error: Unable to resolve module `http` from `/Users/ilan/Code/react-native/rns/node_modules/web3-providers/dist/web3-providers.umd.js`: Module `http` does not exist in the Haste module map
```

I think it is related with this https://docs.expo.io/versions/latest/introduction/faq/#can-i-use-nodejs-packages-with-expo

Steps to reproduce:

1. Create blank app
 ```
create-react-native-app sample
cd sample
yarn add web3
```
2. Import `web3` in `App.js`
```js
import Web3 from 'web3';
```
3. Run
```
react-native run-ios
```

**Comment by janicduplessis** [comment]
React Native does not implement node apis, this is why you cannot use the `http` module. RN does implement `XMLHttpRequest` and `fetch` for networking instead. You'll have to open an issue for the `web3` package to see if they can support RN.

**Comment by ilanolkies** [comment]
Thanks!
