### ISSUE TITLE
Expo init is not working

### ISSUE THREAD

**Issue by Jaisai123** [facebook/react-native#24993]
verbose stack Error: Command failed: git clone --depth=1 -q -b v0.22.1-exp.0 git://github.com/expo/react-native-maps.git /home/exa4/.npm/_cacache/tmp/git-clone-706a8668

***Command :: expo init <foldername> ***
After the name specified, it will run and install the npm dependencies normally but in my case, it just shows the following error:
npm ERR! code 1
npm ERR! Command failed: git clone --depth=1 -q -b v0.22.1-exp.0 git://github.com/expo/react-native-maps.git /home/exa4/.npm/_cacache/tmp/git-clone-706a8668
npm ERR! /home/exa4/.npm/_cacache/tmp/git-clone-706a8668/.git: Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/exa4/.npm/_logs/2019-05-22T10_41_33_271Z-debug.log
npm exited with non-zero code: 1
Set EXPO_DEBUG=true in your env to view the stack trace.

Thanks in advance, please post the solution.

**Comment by ericlewis** [comment]
@Jaisai123 i presume you are referring to trying to use: https://github.com/expo/expo-cli, in which case, you should file a bug there. This doesn't seem like a failure of react-native, but rather incorrect permissions on your machine. Perhaps you npm installed using sudo? In any case, I recommend filing this issue with expo.
