### ISSUE TITLE
[Orientation] Re-Layout on orientation change

### ISSUE THREAD

**Issue by nick** [facebook/react-native#25]
How should I re-layout the page when the orientation of the device changes? I noticed none of the demo apps seem to support this yet. If I refresh the app in a different orientation it lays out fine though.

**Comment by joewood** [comment]
I think it would be more generic to handle resize events, with an orientation hint. Some devices are likely to support side-by-side apps now or in the near future. Adaptive layout is key, and the flex system is good at supporting it.

**Comment by sahrens** [comment]
The UIExplorer example does handle rotation now - it's simplistic, but a
start :)

**Comment by GertjanReynaert** [comment]
@sahrens Where in the UIExplorer example do you handle rotation? It seems like I can't find it. As I'm trying to add rotation detection support to my [npm module] (https://github.com/GertjanReynaert/react-native-device) this could be really usefull. 

PS: maybe the inline [documentation] (https://github.com/facebook/react-native/blob/master/Libraries/Utilities/Dimensions.js#L53-L57) in the Dimensions.js utility should be changed, because the width and height don't change on device rotation (Probably because they are set as constants [here] (https://github.com/facebook/react-native/blob/62b90cfcc5c254076541ed8dc6372e16444b41ba/React/Modules/RCTUIManager.m#L1338-L1340) on application start?)

**Comment by sahrens** [comment]
The docs say the values *may* change, but they currently don't because we never implemented that :(

I'm not sure exactly how the UIExplorer rotation works, but I think there is a riot VC that rotates and whenever the root view bounds changes it triggers a layout update, which works (if you don't use Dimensions, which you shouldn't for 99% of layout - use flex/stretch instead).

I think @nicklockwood has more details on existing rotation support.

**Comment by christopherdro** [comment]
@nick Did you get a chance to resolve this issue?

This might help get the job done.

https://github.com/kkjdaniel/react-native-device-display

**Comment by nicklockwood** [comment]
The original issue was resolved a couple of months ago - if the root view is resized (e.g by an orientation change) then it triggers a re-layout of the react view tree.

**Comment by jeffreywescott** [comment]
@nicklockwood In which react-native version is this fixed? As of 0.8.0, my app does not seem to re-layout subviews on rotation change.

**Comment by nicklockwood** [comment]
It was definitely implemented prior to version 0.8.0. What happens when you rotate the screen? Do the example projects rotate correctly when you try them?

**Comment by jeffreywescott** [comment]
Sorry -- my mistake. As it turns out, all of the layout changes seem to get swallowed by the JS-based `Navigator` component. :-(

**Comment by unknownexception** [comment]
Same here on 0.11.0-rc. View inside renderScene doesn't react on orientation change.

**Comment by gudmundurmar** [comment]
@jeffreywescott Did you find out how to get past the layout changes getting swallowed by the Navigator component?

**Comment by jeffreywescott** [comment]
Nope. I gave up. Sorry, @gudmundurmar

**Comment by andrewljohnson** [comment]
@gudmundurmar, did you make progress on this? Is autorotation broken for Navigator for you?

**Comment by gudmundurmar** [comment]
Rotation works fine for me now. It was a {flex:1} issue on the View that held my NavBar. 
Was using {width: deviceWidth, height: deviceHeight}

**Comment by ericmasiello** [comment]
@gudmundurmar can you provide some sample code of how you are detecting a change in the devices orientation?

**Comment by grittathh** [comment]
Looks like this is related to https://github.com/facebook/react-native/issues/2111

**Comment by stereodenis** [comment]
When I try to change orientation for `<View style={{flex: 1, backgroundColor: 'green'}} />` I got this
![simulator screen shot 1 2016 11 20 55](https://cloud.githubusercontent.com/assets/1406461/18160500/7409fddc-7036-11e6-8c61-5a2e7bcf4850.png)

It resizes to fullscreen when I open Inspector
How to fix it?

**Comment by sahrens** [comment]
@stereodenis: what platform (iOS, android, ?)? Can you provide more context and code? @andreic is looking at this in Android right now but it should work in iOS.

**Comment by sahrens** [comment]
@stereodenis: what platform (iOS, android, ?)? Can you provide more context and code? @andreicoman11  is looking at this in Android right now but it should work in iOS.

**Comment by stereodenis** [comment]
@sahrens iOS (simulator and device), RN 0.32.0,
simple application with only `<View style={{flex: 1, backgroundColor: 'green'}} />`

**Comment by jamieathans** [comment]
I can confirm this behaviour as well.

iOS (simulator and device), RN 0.32.0, `<View style={{flex: 1}} />`

Tapping a `TouchableOpacity` will cause the layout to resize.

**Comment by javache** [comment]
It sounds like the view controller hosting your RCTRootView is not setup correctly. Can you verify on the native side that on rotation this methods gets invoked? https://github.com/facebook/react-native/blob/master/React/Base/RCTRootView.m#L368

**Comment by jamieathans** [comment]
> It sounds like the view controller hosting your RCTRootView is not setup correctly. Can you verify on the native side that on rotation this methods gets invoked? https://github.com/facebook/react-native/blob/master/React/Base/RCTRootView.m#L368

Just checked via the Xcode debugger, I can confirm the above method gets invoked on rotation.

**Comment by javache** [comment]
My fix here could be related: https://github.com/facebook/react-native/commit/f35b372883a76b5666b016131d59268b42f3c40d and will be out in v33.

@bestander: if we do another release of v32 could you patch it in?

**Comment by bestander** [comment]
Pieter, no problem

**Comment by alexprice91** [comment]
On Android I am seeing something similar. When I first "present" a modal, the layout is 100% wrong. Then if I rotate the device the layout corrects itself. This is the same no matter if I start in landscape or portrait.

I used the React Modal example:
https://facebook.github.io/react-native/docs/modal.html

**Comment by mmmulani** [comment]
what version of React Native are you using? I just landed a change that affects Modal and orientation but it should only affect iOS

On 3 Sep 2016, at 20:06, Alexander Price <notifications@github.com<mailto:notifications@github.com>> wrote:


On Android I am seeing something similar. When I first "present" a modal, the layout is 100% wrong. Then if I rotate the device the layout corrects itself. This is the same no matter if I start in landscape or portrait.

I used the React Modal example:
https://facebook.github.io/react-native/docs/modal.html<https://urldefense.proofpoint.com/v2/url?u=https-3A__facebook.github.io_react-2Dnative_docs_modal.html&d=DQMFaQ&c=5VD0RTtNlTh3ycd41b3MUw&r=1plvBtGQksv83Ssn0KCALw&m=L30Xg7Xsj0o3F5KawQdBTCqPDsuVM83XRTP0ySnog-Y&s=6VEVTX2lL74wcSoEtSypkl1dK6rpJJ98G2pYunn_at4&e=>

-

**Comment by alexprice91** [comment]
I am on version 0.32.

**Comment by jsdevel** [comment]
this is also affecting me on android.

**Comment by bestander** [comment]
I'll make a patch for 0.32 then, should be out in an hour

**Comment by alexprice91** [comment]
Thanks @bestander!!

**Comment by jsdevel** [comment]
@bestander this still occurs on android with `0.32.1`.

**Comment by andreicoman11** [comment]
@jsdevel I'm looking into it

**Comment by emilioaray** [comment]
On Android When I try to change orientation the Modal dont resizes to fullscreen. this still occurs on android with react-native 0.33.0.

**Comment by alexprice91** [comment]
Any update on this? Wanting to get an initial release out and this is blocking my app.

**Comment by ksloan** [comment]
upgraded to 0.33.0 and seeing it on iOS

**Comment by mmmulani** [comment]
the UIExplorer app handles orientation changes by calling setState from onLayout, I believe

**Comment by linonetwo** [comment]
Seems OnLayout is working, but some component from npm depends on Dimensions can't get right windowWidth or windowHeight properly, they won't change after orientation change.

**Comment by linonetwo** [comment]
This is blocking some package likes [react-native-menu-button](https://github.com/KenHky/react-native-menu-button) working properly. https://github.com/KenHky/react-native-menu-button/issues/4

**Comment by andreicoman11** [comment]
Android supports orientation changes since https://github.com/facebook/react-native/commit/f07ca31303fba7dc633881c8a97b1779083c86d4 through `namedOrientationDidChange`, and Dimensions gets updated accordingly since https://github.com/facebook/react-native/commit/8451585f3861776a1d8f67b8b0dfd1e9cc705ed6.

**Comment by mvayngrib** [comment]
idk if this will help anyone, but i extracted the higher-order-component i use internally in my project to wrap components that want to be orientation-aware: https://github.com/mvayngrib/react-native-orient

**Comment by air-ii** [comment]
I don't get updates to Dimensions on orientation change either. I'm on Android, RN 0.33.

**Comment by uc-hus** [comment]
Can you please help for native app's orientation issue for both android and ios
![image](https://cloud.githubusercontent.com/assets/12196308/19956571/117884ea-a1b4-11e6-87e9-0dba2d9a70ff.png)

**Comment by uc-hus** [comment]
Very bad for UI

**Comment by uc-hus** [comment]
I dont like react native

**Comment by uc-hus** [comment]
this bug coming from previous 5 weeks

**Comment by nihgwu** [comment]
@uc-hus You can just disable the landscape orientation via configuration, and if you don't like RN you can just drop it

**Comment by uc-hus** [comment]
Why? It's required.


Thanks & Regards
*Mohammed HUSAIN*
Senior Apps Developer, uCertify
+91 9919475253

**Comment by mmmulani** [comment]
@uc-hus are you handling onLayout events to setState or otherwise cause a re-render()? Compare your app to the UIExplorer which isn't having any of these issues

**Comment by linonetwo** [comment]
@uc-hus AFAIK  react-native-menu-button solve its orientation problem by some workaround, you may take a look.

**Comment by uc-hus** [comment]
No, I'm not agree with you because I have resolved this issue without setState
and re-render().


[image: Inline image 1]
[image: Inline image 2]


Thanks & Regards
*Mohammed HUSAIN*
Senior Apps Developer, uCertify
+91 9919475253

**Comment by jayshah123** [comment]
If you have fixed height and/or fixed width for your view,
chances are onlayout won't be called for that particular view after rotation, 
but onLayout for views with flex:1 does get called when checking as of 0.35 (on android atleast)

**Comment by ThaJay** [comment]
> uc-hus commented on 8 Nov 2016
> 
> No, I'm not agree with you because I have resolved this issue without setState
> and re-render().

What was your fix? (the images you posted do not work)

I will try and listen for `onLayout` or `namedOrientationDidChange` now. My components seem to be good apart from my navbar then reverts to its initial state instead of remaining in the state I gave it (with custom text and / or custom button icon + handler) so it needs to re-render.

**Comment by mkoo21** [comment]
We had this issue on iOS because we were setting height/width using Dimensions.get in a StyleSheet. Switching to inline styles fixed the problem.

**Comment by uc-hus** [comment]
Can you pease provide a example


Thanks & Regards
*Mohammed HUSAIN*
Senior Apps Developer, uCertify
+91 9919475253

**Comment by mkoo21** [comment]
`flex:1` makes a component resize to take up all available space within its container, so if you set it on your root component it will resize to take up the whole screen on rotation. If you need to resize child views according to the new dimensions you can set `onLayout` for that view to capture that event and trigger a rerendering. 
If you use something like redux you can easily write those dimensions to your app state and use them as props for any components that need to be responsive (I personally prefer this over Dimensions.get).
Here is an example that draws a red rectangle that fills the top-left quarter of the screen:
```
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  AppRegistry,
  Dimensions,
  StyleSheet,
  View
} from 'react-native';

var app = React.createClass({
  getInitialState() {
    return {
      pageHeight: Dimensions.get('window').height,
      pageWidth: Dimensions.get('window').width
    }
  },
  getNewDimensions(event){
    this.setState({
      pageHeight: event.nativeEvent.layout.height,
      pageWidth: event.nativeEvent.layout.width
    })
  },
  render() {
    return (
      <View
        style={styles.page}
        onLayout={this.getNewDimensions}>
        <View style={[styles.rectangle, {
          height: this.state.pageHeight / 2,
          width: this.state.pageWidth / 2
        }]}/>
      </View>
    );
  }
});

const styles = StyleSheet.create({
  page:{
    backgroundColor: 'blue',
    flex:1
  },
  rectangle:{
    backgroundColor: 'red'
  }
});

AppRegistry.registerComponent('app', () => app);

```
Of course, if you try to set `onLayout` on a view with fixed dimensions nothing interesting will happen. Dimensions.get('window') seems to return fixed numbers and set them, so if you use that you will need to force the component to rerender on rotation.

**Comment by vspedr** [comment]
@uc-hus I'm having the same issue that you reported [here](https://github.com/facebook/react-native/issues/25#issuecomment-258066776), but it's  not clear what you did to solve it. The images in your other comment don't show up. Could you please share your solution?

**Comment by ababba15** [comment]
@mkoo21 we can also define width and height outside of class and change them `onLayout` to have access to that values in styles.

**Comment by Tiendq** [comment]
@mkoo21 I got screen width changed in the onLayout event but view isn't re-rendered with new `this.state.pageWidth` :(

**Comment by mkoo21** [comment]
@ababba15 If you mean access them from `StyleSheet.create()`, you could access them but unless it has changed recently, the point of a stylesheet is that it's calculated once and reused, so you wouldn't be able to change the values dynamically. I think it's just easier to use state since changing state automatically triggers a rerender.

@Tiendq Is this an issue you had with my example? Are you setting style through `this.state`, or are you using a stylesheet?

**Comment by ababba15** [comment]
@mkoo21 maybe it not too cool, but I can define width and height outside the class like this:

``` javascript

let { width, height } = Dimensions.get('screen');

class Peace extends Component {
    constructor() {
        super();
        this.state = { width, height };
    }

    _handleLayout = event => {
        this.setState({
            width: event.nativeEvent.layout.width,
            height: event.nativeEvent.layout.height
        }, () => {
            width = event.nativeEvent.layout.width;
            height = event.nativeEvent.layout.height;
        });
    }

    render() {
        return <View style={styles.container} onLayout={this._handleLayout}> ... </View>;
    }
}

const styles = StyleSheet.create({
    container: { width, height }
});

```

Anyway it will work (if here is no any typo). Why like this? Because I prefer to avoid mixing inline and StyleSheet style. As for me, `style={[styles.container, { width, height }]}` looks more ugly..

But I can be wrong, I'm not too experienced, so let me know.. 
Peace, guys : )

**Comment by mkoo21** [comment]
I added `backgroundColor = 'red'` in styles to test your code. It does not respond to rotations for me. 

![screenshot at 2017-05-22 18 25 55](https://cloud.githubusercontent.com/assets/12832801/26330881/26df647e-3f1c-11e7-92c7-6d4ac9921ef4.png)
![screenshot at 2017-05-22 18 26 03](https://cloud.githubusercontent.com/assets/12832801/26330887/28fbccb6-3f1c-11e7-8b53-1d7f3e7ccd94.png)

**Comment by Tiendq** [comment]
@mkoo21 I used inline style e.g. {{ width: this.state.width }} but it doesn't work.

**Comment by ababba15** [comment]
@mkoo21 ok, I will check it today. I made it working somehow, just need to try again.

**Comment by mkoo21** [comment]
@Tiendq can you upload code or reproduce the issue with a minimal example so we can see what's wrong?

**Comment by Tiendq** [comment]
@mkoo21 Never mind, sample code works now, I think it's my app's issue with nested views and FlatList view. Thanks.

**Comment by rsp8055** [comment]
UI is perfect when it is in PORTRAIT mode no need to scroll even. But as you get to change it to the LANDSCAPE mode UI is ok here but need to use <ScrollView /> now!? So, if I use scroll view here then UI is in this mode but now UI gets affected in another mode. What should do for making the UI working properly in both the mode?

I as worked so far and got to know that when I use any background image and flex it then only orientation problem arrives.

Here is the code for this production :

` <View     style={{ flex: 1, justifyContent: 'space-between' }}
                  onLayout={this.getNewDimensions}>

                <HeadImage />

                <View style={inputContainerStyle} >
                    <TextInput />
                     <View>
                            <Image source={*****} style={searchStyle} />
                     </View>
                </View>

                <View style={buttonContainer}>
                    <ButtonContainer />
                </View>

                <FootImage />

</View>`

Thanks in ADV.
