### ISSUE TITLE
Question: Numeric Keyboard returnKeyType Label

### ISSUE THREAD

**Issue by ermantepe** [facebook/react-native#25009]
Hello,

I try to add "done" button to iOS keyboard on my react native application.
When it is standard keyboard, "Done" label will change by language of the phone.
But when I use numeric keyboard, "Done" label not changing. 

How can I change label of "Done" text on iOS?

**Comment by orteidni** [comment]
I can confirm this issue shows up also with decimal-pad keyboardType. Even though my phone is in Finnish, the keyboard's label is "Done" as in English.

**Comment by orteidni** [comment]
**Found a solution:** You can change the "Done" button label according to the user's language by using the InputAccessoryView.
