### ISSUE TITLE
nativeStackAndroid only contains up to 10 stack traces

### ISSUE THREAD

**Issue by dhk5** [facebook/react-native#25000]
nativeStackAndroid only contains up to 10 stack traces. This is due to the "ERROR_STACK_FRAME_LIMIT" set to 10 on https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/bridge/PromiseImpl.java. 

![2019-05-22_10-33-23](https://user-images.githubusercontent.com/5590665/58205971-9ba81a00-7c94-11e9-8552-209190891104.png)

nativeStackAndroid should contain all the native stack traces like nativeStackIOS. another improvement could be adding the "declaringClass" on top of the "methodName", "LineNumber", and "file" on the stack trace frameMap.

![2019-05-22_13-38-43](https://user-images.githubusercontent.com/5590665/58207295-428db580-7c97-11e9-88a2-8163563c7738.png)

nativeStackIOS contains all 28 stack traces. 

![2019-05-22_09-55-47](https://user-images.githubusercontent.com/5590665/58206184-11ac8100-7c95-11e9-8290-95eba40e4aab.png)

React Native version:

info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
      Memory: 57.51 MB / 32.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      Yarn: 1.12.1 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        Build Tools: 27.0.2, 27.0.3, 28.0.0, 28.0.3
        API Levels: 19, 23, 24, 25, 26, 27, 28
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.4.14 => 16.8.17 
      @types/react-native: ^0.57.4 => 0.57.58 
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.8 => 0.59.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Steps To Reproduce

1. Promise.reject with an Throwble object on the native side.
2. Check the error object on react-native side.

Describe what you expected to happen:
nativeStackAndroid should contain all the native stack traces like nativeStackIOS.

Snack, code example, or link to a repository:

**Comment by hey99xx** [comment]
not a bug, as the behavior matches what the author has intended. still it could be consistent among iOS/Android.

@Salakar in your PR https://github.com/facebook/react-native/commit/794d2264f93b6eaeab4eb53c7d2eaf7880b89649 do you remember why you limited Android stacktrace to 10 items? Is there an issue with stacktraces too long?

**Comment by Salakar** [comment]
Not a bug as @hey99xx pointed out,

I implemented it with a limit as the output is structured to match the JS StackFrames format RN uses (Array of Maps) compared to iOS which just gives you an unparsed array of strings, the plan was implement a follow up PR to do the same format for iOS if possible, that way they can be merged into a single nativeStack property.

I wasn't entirely sure on the performance implications of this given that I've seen some very long stack traces before in Android and that it'd need to construct a ReadableMap for each frame.

If you like, I'd suggest submitting a PR with a higher limit, such as 30 and tag me in it for review.
