### ISSUE TITLE
Error while trying to upgrade to 59.0

### ISSUE THREAD

**Issue by Luckygirlllll** [facebook/react-native#25003]
React Native version:

 React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (8) x64 Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
      Memory: 42.14 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 27.0.1, 27.0.3, 28.0.3
        System Images: android-23 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: 0.57.1 => 0.57.1 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-device-info: 2.0.0
      react-native-git-upgrade: 0.2.7

## Steps To Reproduce

1. run react-native-git-upgrade
2. See an error: " ```
An error occurred during upgrade: 
git-upgrade ERR! Error: Need a project name
    at copyProjectTemplateAndReplace
``` " 

P.S: this is `ExpoKit` project

<!--
 Issues without reproduction steps or code are likely to stall.
-->

Describe what you expected to happen:

I expected that version of react native will be upgraded

Snack, code example, or link to a repository:


<!--
  Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or
  provide a minimal code example that reproduces the problem.
  Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve.
-->

**Comment by Luckygirlllll** [comment]
@react-native-bot That's why I opened this issue

**Comment by guhungry** [comment]
`react-native-git-upgrade` was deprecated for some time now. Please try https://github.com/react-native-community/rn-diff-purge instead.

**Comment by HarshitMadhav** [comment]
@Luckygirlllll checkout the answer to this question https://stackoverflow.com/questions/53378354/upgrading-react-native-to-latest-version/54849799#54849799

**Comment by RichardLindhout** [comment]
If above does not work, your best bet is to init a new project and copy all things in from your old project.

**Comment by thymikee** [comment]
Closing per @guhungry comment.

**Comment by Luckygirlllll** [comment]
@thymikee Please open the issue, ExpoKit and Expo still don't support  react-native 59.0, so if expo or ExpoKit project will be upgraded to 59.0, it will break an app.

**Comment by thymikee** [comment]
@Luckygirlllll if you use Expo managed project, you'll need to wait for them to ship official support for 0.59 or eject. Your issue is still about `react-native-git-upgrade` which is not actively maintained and deprecated.
