### ISSUE TITLE
[Modal] Add documentation + examples

### ISSUE THREAD

**Issue by yelled3** [facebook/react-native#2500]
it can be based on `UIExplorer/ModalExample.js`:
https://github.com/facebook/react-native/blob/2f6e7336cb96bf14d47554ae0db1836075ea809e/Examples/UIExplorer/ModalExample.js

**Comment by sahrens** [comment]
We should definitely add docs.  What more do you want to see in examples?

**Comment by yelled3** [comment]
@sahrens the `Modal` it self is fairly simple component - so just a basic usage example will do.

the thing that remains unclear to me is how to design my app around this;
that's the reason I probed around on working with `Portal` at https://github.com/facebook/react-native/issues/2501

I was trying to figure out where to render the `<Modal>` it self.
should each **screen** render it's own modal?

say I want to be able to open the same modal from multiple endpoints in my app;
should it sit in the root app component and be loaded dynamically with a different component?

also,
from my understanding, the exact render location is somewhat meaningless, since internally it's covering the root app:
```obj-c
[self.reactViewController presentViewController:_modalViewController animated:self.animated completion:nil];
```
https://github.com/facebook/react-native/blob/master/React/Views/RCTModalHostView.m#L78

so in a way, it would seems to me that the `Portal` interface, where you can call:
```js
Portal.showModal(<MyModalView {...} />);
```
is more correlated with the current implementation.

thoughts?

**Comment by sahrens** [comment]
> say I want to be able to open the same modal from multiple endpoints in my app;

What you really want is to render the same *view* into a modal from different points in the app.  It's fine for those different points in the app to have their own <Modal> components (under the hood it will do something similar to Portal.showModal, but in native-land).  So anywhere you want to show MyModalView, just wrap it in another modal component.  You're right, it doesn't matter where the <Modal> is actually rendered, so you can just put it wherever is convenient to control the `visible` prop and render the contents.  If you render multiple modals, they should just stack on top of each other, so you can event nest them.

Does that answer the question?

> just a basic usage example will do.

So `UIExplorer/ModalExample.js` is sufficient then, yeah?

**Comment by yelled3** [comment]
> Does that answer the question?

yes, thank you.

> So UIExplorer/ModalExample.js is sufficient then, yeah?

I think it's worth covering the above use case (i.e `open the same modal from multiple endpoints`) in either the official docs or/and in another `UIExplorer` example.
and also mentioning that `it doesn't matter where the modal is actually rendered`.

**Comment by christopherdro** [comment]
@ide @brentvatne
 Issue can be closed.
Docs added with PR #2507

**Comment by yelled3** [comment]
@christopherdro @ide @brentvatne @sahrens 
forgive me, maybe I'm missing something - but why are you closing this?
I don't see how https://github.com/facebook/react-native/pull/2507 solves any of what we discussed above.

**Comment by brentvatne** [comment]
@yelled3 - some basic API docs are in place for it and https://github.com/facebook/react-native/pull/2663 explains that you probably should not be using Modal very often in pure JS apps. If you have time and would like to add some more documentation to Modal to explain your findings above then please submit a PR and we'd be happy to accept!
