### ISSUE TITLE
Android App crash on start after upgrading to 0.59.8

### ISSUE THREAD

**Issue by BasilJohn** [facebook/react-native#25024]
I upgraded react native from 0.56 to 0.59.8 using the rn diff tool.
The code builds successfully however the app crashes immediately after launch.

React Native version:
React Native : 0.59.8

## Steps To Reproduce

1.Upgrade to RN 0.59.8 using RN DIFF tool
2.Run command "react-native run-android"

I get the below error when i do a logcat from Android Studio.

 **java.lang.RuntimeException: Unable to start activity ComponentInfo{com.libertyhk.eClaim/com.libertyhk.eClaim.MainActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity**.

Though the android:theme is using AppCompat i still see the same issue.

---Below ins my styles.xml file 

<resources>

    
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        
    </style>

    
        
    

    <style name="SplashTheme" parent="AppTheme">
        <item name="android:windowBackground">@drawable/background_splash</item>
    </style>

</resources>

Describe what you expected to happen:
Expected behaviour to get the app running on android.

**Comment by ferrannp** [comment]
@BasilJohn can you show me how you use `SplashTheme` and `AppTheme` in your `AndroidManifest.xml` ?

**Comment by BasilJohn** [comment]
<application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">

**Comment by BasilJohn** [comment]
application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme"

**Comment by guhungry** [comment]
Did you try clean android build cache after upgrade?

**Comment by ferrannp** [comment]
@BasilJohn remove `android:theme` from `<application>` tag and add it inside the `<activity>` tag. Let me know if it works.

**Comment by BasilJohn** [comment]
> @BasilJohn remove `android:theme` from `<application>` tag and add it inside the `<activity>` tag. Let me know if it works.

@ferrannp  this works !!!! Thanks a lot for the support.

**Comment by ferrannp** [comment]
No problem :)
