### ISSUE TITLE
Run `react-native info` in your terminal and copy the results here.

### ISSUE THREAD

**Issue by zjchxl** [facebook/react-native#25022]
React Native version:

React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 82.46 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.14.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 21, 22, 23, 24, 25, 26, 27, 28
        Build Tools: 27.0.3, 28.0.2, 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5014246
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: ^0.59.6 => 0.59.6 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Steps To Reproduce

1.
2.

Describe what you expected to happen:

Snack, code example, or link to a repository:

**Comment by zjchxl** [comment]
The new React Native project found that the Android R file was lost, so I couldn't write some Native activities

**Comment by ptrocki** [comment]
Did you build the App ? How did you create app ? Can you provide repo or more info ?

**Comment by zjchxl** [comment]
Yes I tried to create a new application on Windows and macOs. Unfortunately there are no R files in the android folder.

**Comment by satya164** [comment]
Closing the issue since the issue template was not followed. Please open a new issue with a repro and description of the issue if you are still having a problem
