### ISSUE TITLE
Debug a real device doesn't work, boots the app and freezes iOS 12.3 

### ISSUE THREAD

**Issue by ThomasLarge** [facebook/react-native#25026]
**Boot to a real device in debug mode doesn't work, app freezes iOS 12.3** 

I have also tested this on a fresh install of react native and the issue still happens. When you build in **Xcode 10.2.1** with the scheme set to the following (default)

**Build Configuration: Debug 
Debug executable: ticked** 

The app will boot on to the device but not connect to the metro bundler. Then Metro bundler is there and boots up don't change from this 

![Screenshot 2019-05-24 at 1 39 00 pm](https://user-images.githubusercontent.com/15890942/58328196-6bde4b00-7e29-11e9-803c-c58e8f238417.png)

When the app is installed on the device the splash screen shows and freezes. After about 3 / 5mins it will show you the first screen of the app it's then frozen again. Finally, it crashes the app. 

I have also built the app in Release and this is fine. Not really sure where to go from here?
```
React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
      Memory: 60.91 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 26, 27, 28
        Build Tools: 28.0.3
        System Images: android-26 | Intel x86 Atom_64, android-27 | Intel x86 Atom_64, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.8 => 0.59.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

**Comment by ptrocki** [comment]
Related https://github.com/facebook/react-native/issues/24986

**Comment by ThomasLarge** [comment]
Looks like it's the new macOS update, works on macOS 10.14.4 but not macOS 10.14.5

Hope this helps!

**Comment by legshampoo** [comment]
also having this issue, on macOS 10.13.6
iOS v12.1.4

disabling wifi doesn't help

**Comment by legshampoo** [comment]
seems the issue was because my laptop was hardwired via ethernet cable to the router, while the device on wifi.  

Fixed issue by putting both devices on wifi

incidentally updated software in the process:
macOS 10.14.5
iOS 12.3.1
Xcode 10.2.1

**Comment by ThomasLarge** [comment]
@legshampoo thanks for the update, I have got mine now working but I have to turn the wifi off on both devices to work. Also the debug has to be runing on a IP and not localhost. 

Still very weird not sure whats going on!

**Comment by JimBTek** [comment]
this is how we handle this in AppDelegate.m

`- (void)setupRootViewController
{
    NSURL *jsCodeLocation;
  
    #ifdef DEBUG
      #if TARGET_IPHONE_SIMULATOR
        jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.bundle?platform=ios&dev=true"];
      #else
        jsCodeLocation = [NSURL URLWithString:@"http://YOURCOMPUTERIP:8081/index.bundle?platform=ios&dev=true"];`

**Comment by ThomasLarge** [comment]
Seems to be an issue with my internet as it's custom
