### ISSUE TITLE
[android] Inspecting nested text element throws "Expected to find at least one React renderer."

### ISSUE THREAD

**Issue by sjchmiela** [facebook/react-native#25023]
React Native version:
```
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
      Memory: 67.12 MB / 16.00 GB
      Shell: 5.6.2 - /usr/local/bin/zsh
    Binaries:
      Node: 10.11.0 - ~/.nvm/versions/node/v10.11.0/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.11.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 21, 22, 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 26.0.1, 26.0.3, 27.0.3, 28.0.2, 28.0.3
        System Images: android-19 | Google APIs Intel x86 Atom, android-21 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.8 => 0.59.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-create-library: 3.1.2
```
## Steps To Reproduce

1. Run a React Native application on Android
2. Toggle Inspector
3. Tap on a nested text
4. Error is shown ⬇️ 

![Screenshot_20190524-104711](https://user-images.githubusercontent.com/1151041/58315842-940e7f80-7e12-11e9-93e1-1ac4bf9c8372.png)

### Describe what you expected to happen

Nested text is being inspected. No error is thrown. 

### Snack, code example, or link to a repository

A basic RN application with nested text: https://github.com/sjchmiela/nested-text-inspector 

### Possibly related issues

https://github.com/facebook/react-devtools/issues/1032, https://github.com/facebook/react-native/issues/19782

### Short investigation

`InspectorOverlay`, when tapped, finds the view tag of the tapped element using `UIManager.findSubviewIn`. This method finds native view tag for native `ReactTextView` properly and then `TouchTargetHelper` uses `public int reactTagForTouch` (from `ReactCompoundView` interface) to find a React tag for that specific touch (it finds it successfully).

https://github.com/facebook/react-native/blob/01abcf0e83fe58757661dcf6cfc0c2843fed570d/Libraries/Inspector/InspectorOverlay.js#L35-L48

Then, this tag is fed into `NativeViewHierarchyManager.measure`, which cannot find view for this tag, since this tag represents a `ReactVirtualTextShadowNode`, which is a virtual view and thus can't be found in `mTagsForViews` of `NVHM`.

https://github.com/facebook/react-native/blob/01abcf0e83fe58757661dcf6cfc0c2843fed570d/ReactAndroid/src/main/java/com/facebook/react/uimanager/UIViewOperationQueue.java#L484-L496

`NoSuchNativeViewException` is thrown, `FindTargetForTouchOperation` catches it, calls the original callback with `undefined`, with which `Inspector.onTouchViewTag` is called.

https://github.com/facebook/react-native/blob/01abcf0e83fe58757661dcf6cfc0c2843fed570d/Libraries/Inspector/Inspector.js#L179-L185

This function in turn calls `getInspectorDataForViewTag(tag)`, i. e. `getInspectorDataForViewTag(undefined)`, which throws an error since it can't find inspector data for `undefined` tag.

https://github.com/facebook/react-native/blob/01abcf0e83fe58757661dcf6cfc0c2843fed570d/Libraries/Inspector/Inspector.js#L47-L63

**Comment by nerdaliciousCH** [comment]
Same issue. Also related to a View containing a Text. Very frustrating.
