### ISSUE TITLE
Size of clean apk with no dependencies or assets is 28MB

### ISSUE THREAD

**Issue by Anshuman71** [facebook/react-native#25020]
Size of clean apk with no dependencies or assets is 28MB
React Native version:  0.59.8 

React Native Environment Info:
    System:
      OS: Linux 5.0 Ubuntu 19.04 (Disco Dingo)
      CPU: (4) x64 Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz
      Memory: 413.98 MB / 7.69 GB
      Shell: 5.0.3 - /bin/bash
    Binaries:
      Node: 10.15.2 - /usr/bin/node
      Yarn: 1.16.0 - /usr/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.8 => 0.59.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Steps To Reproduce

1. Perform `react-native init`
2. cd android &&  `./gradlew assembleRelease`

Describe what you expected to happen:
APK size somewhere around 8MB

Snack, code example, or link to a repository:
No custom code only default `react-native init` repo

**Comment by guhungry** [comment]
Duplicate with #24988.
