### ISSUE TITLE
Xcode painfully slow when loading react native projects

### ISSUE THREAD

**Issue by subhashchandrujobop** [facebook/react-native#25030]
I have created a react native  project ,and i have manually opened xcode project in ios folder but after that , Xcode open the project after 20 min ,but when i create a new project manually in Xcode it builds well , i dont whom to blame wheather is it xcode /react native  ,and even sucks when i try to open with **CLI**,but xcode run well with its native projects

My specs are:

Macbook pro 2017 15 inch
2.9 ghz intel core i7
16 GB 2133 MHz LPDDR3
Intel HD Graphics 630 1536 MB

react native 0.59.8
xCode - 10.2.1

**Comment by subhashchandrujobop** [comment]
> Thanks for submitting your issue. Can you take another look at your description and make sure the issue template has been filled in its entirety?
> 
> 👉 [Click here if you want to take another look at the Bug Report issue template.](https://github.com/facebook/react-native/issues/new?template=bug_report.md)

**Comment by subhashchandrujobop** [comment]
the issue was perfectly stated

**Comment by yennhan** [comment]
Did you found the solution for this?

**Comment by subhashchandrujobop** [comment]
> Did you found the solution for this?

no

**Comment by ptrocki** [comment]
Can you provide example project ?
