### ISSUE TITLE
RN接入现有项目时，内存泄露问题 

### ISSUE THREAD

**Issue by absss** [facebook/react-native#25046]
为现有iOS项目接入RN的时候，我遇到一个关于内存的问题，我写了一个简单的添加了RNRootView的控制器，当我进入页面、然后退出页面的时候，我发现内存没有减少，然后打印deinit方法(我的项目是swift项目)的时候，我发现控制器已经销毁了，重复进入页面、退出页面，我发现内存会一直增加，这个问题该如何解决？

React Native version:
0.59

**Comment by chenhuaxian** [comment]
i have the same issue
version: 0.57.8
phone: ios12.2

**Comment by absss** [comment]
我已经解决该问题。
解决方案：
```
   deinit {
        if let rootView = self.rootView {
            rootView.bridge.invalidate()
        }
    }
```
在deinit方法中调用该方法，注意，如果你rn的公用父类，不要在父类的deinit方法中调用上述方法，要在子类的方法中调用该方法

**Comment by chenhuaxian** [comment]
> 在swift中，如果你有rn的公用父类控制器，不要在父类的deinit方法中调用上述方法，要在子类的方法中调用该方法，

这是个单例呀。invalidate以后，再次打开其他rn页就白屏了。。。

**Comment by absss** [comment]
我已解决该问题
