### ISSUE TITLE
The external link to Android's Image does not show up

### ISSUE THREAD

**Issue by huangxiaojieCoder** [facebook/react-native#25049]
It is this connection https://oss.yi-ai.cc/yiai_img/purOrder/64_1558944809903_0.jpg that cannot be displayed on the Android machine. The simulator can be displayed.

<Image style={{width: 130,height:130,marginLeft:30,marginBottom:30}}
source={{uri: "https://oss.yi-ai.cc/yiai_img/purOrder/64_1558944809903_0.jpg"}}

      />

React Native version:

 "react": "^16.6.3",
   "react-moment": "^0.8.4",
   "react-native": "0.58.5",

## Steps To Reproduce
External links
https://oss.yi-ai.cc/yiai_img/purOrder/64_1558944809903_0.jpg

**Comment by guhungry** [comment]
Might be due to `This server's certificate chain is incomplete. Grade capped to B.`

https://www.ssllabs.com/ssltest/analyze.html?d=oss.yi-ai.cc&s=120.77.166.170

**Comment by huangxiaojieCoder** [comment]
thanks,Yes due to This server's certificate chain is incomplete. Grade capped to B.
