### ISSUE TITLE
Flatlist onRefresh does not work within nested Scrollview

### ISSUE THREAD

**Issue by lxylinki** [facebook/react-native#25059]
React Native version:
0.59.5

 CourseView is a FlatList with onRefresh function located at bottom half of the page, nested inside a horizontal Scrollview(onRefresh works fine), and a portrait Scrollview(onRefresh does not work after this layer of nesting) contains the entire page except search bar. 

The page scrolls as the screenshot displays, I have to put Flatlist inside ScrollView to achieve this. Could anyone share some ideas on how to resolve this issue? I have read relevant issues but find little help.

Describe what you expected to happen:
When scroll down the course list when it is at the top, the list should start refreshing. 

Snack, code example, or link to a repository:
![Screenrecorder-2019-05-28-09-42-33-406](https://user-images.githubusercontent.com/4198567/58445768-8a498c80-8130-11e9-9747-978178f5d772.gif)

				<ScrollView 
					style={[styles.bottomView]}
					onScroll={this.scrollPage}>
					<View style={styles.searchBadges}>
						<Text>热搜</Text>
						<BadgeBtn
							style={{width: 70}}
							text={'测试课程1'} 
							action={()=>{
								this.props.navigation.navigate('CourseDetail', {id: '41'});
							}}/>
						<BadgeBtn 
							style={{width: 120}}
							text={'课程虚拟仿真实验'}
							action={()=>{
								this.props.navigation.navigate('CourseDetail', {id: 'B3'});
							}}
						/>
					</View>
					<HomeSwiper style={styles.swiper}/>
					<ScrollView
						style={styles.bottomScroll}
						pagingEnabled={true}
						horizontal={true}
						ref={'pageScroll'}
						onMomentumScrollEnd={this.scrollEnd}
					>
						<CourseView 
							hasSkeleton={true}
							navigation={this.props.navigation}
							data={this.state.courseData} 
							onEndReached={()=>{
								if(this.state.courseData.length>=this.pageSize) {
									if(this.page < this.totalPage) {
										this.page += 1;										
										this.getCourseData();
									}
								}
							}} 
							onRefresh={(callback)=>{
								this.page = 1;
								this.stopRefresh = callback;
								this.getCourseData();
							}}
						/>
						<CatagView 
							data={this.state.catagData}
							navigation={this.props.navigation}
						/>
					</ScrollView>
				</ScrollView>

**Comment by MayoudP** [comment]
Same over here I'm using a FlatList inside a ScrollView (to make a collapsible header) and the `onRefresh` for the FlatList only work if it's only nested inside a View. Did you succeed to manage it ? 

**OnRefresh don't work :** 
```
<ScrollView>
          <FlatList onRefresh={doOnRefresh} />
</ScrollView>
```

**OnRefresh don't work :** 
```
<ScrollView>
       <View>
          <FlatList onRefresh={doOnRefresh} />
       </View>
</ScrollView>
```

**OnRefresh WORK :** 
```
<View>
      <FlatList  onRefresh={doOnRefresh}/>
</View>
```

**Comment by soumyamishra89** [comment]
Having the same issue when using SectionList inside a horizontal ScrollView. The issue appears only on iphone XS max. the pull to refresh does not work from initial position. But it works when u scroll a bit and then pull down.

**Comment by soumyamishra89** [comment]
The issue was solved. there was some alignment issues.
