### ISSUE TITLE
React native Android Scrollview slow down after some redirections in app: 

### ISSUE THREAD

**Issue by bharatidudhjiya** [facebook/react-native#25051]
I have react native app like instagram,
My problem is first time app is load scrollview working very smoothly in home page with large data, but after some redirection in app, back to home page, scrollview stuck at some points.

here is my code

                   <ScrollView
    					ref={ref => this.scrollView = ref}
    				 	scrollEventThrottle={400}
    				 	onScroll={({nativeEvent}) => {
    				      this.handleScroll(nativeEvent)
    				    }}
    				    keyboardShouldPersistTaps='handled'
    				    showsVerticalScrollIndicator={false}
    				    refreshControl={
    						<RefreshControl
    							refreshing={this.state.refreshing}
    							onRefresh={this._onRefresh}
    						/>
    			        }
    				    >
    					<View style={[this.state.isSubscribingTab ? this.tabHeight() : style.mianContainer]}>
    						<AuctionPosts ref={instance => { this.AuctionPostsChild = instance; }} _onRefreshEnd={this._onRefreshEnd} />
    						<View style={style.mainContent}>
    							<Tabs ref={component => this._tabs = component} locked={true} tabBarUnderlineStyle={style.tabUnderLine} onChangeTab={({ i }) => this.tabChange(i)}>
    								<Tab activeTabStyle={{ backgroundColor: colors.white }} tabStyle={{ backgroundColor: colors.white }} heading={this.state.labels.following ? this.state.labels.following : "Following"} textStyle={style.tabTextStyle} activeTextStyle={style.activeTextTab}>
    									<FollowingPosts  ref={instance => { this.FollowingPostsChild = instance; }} _onRefreshEnd={this._onRefreshEnd} />
    								</Tab>
    								<Tab activeTabStyle={{ backgroundColor: colors.white }} tabStyle={{ backgroundColor: colors.white }} heading={this.state.labels.subscribing ? this.state.labels.subscribing : "Subscribing"} textStyle={style.tabTextStyle} activeTextStyle={style.activeTextTab}>
    									<SubscribingPosts ref={instance => { this.SubscribingPostsChild = instance; }} subscribingPostCount={this.subscribingPostCount} />
    								</Tab>
    							</Tabs>
    						</View>
    					</View>
    				</ScrollView>

it is working fine in IOS but issue in Android

Thanks!

**Comment by nicolasdet** [comment]
i got the exact same problem. 
First lauch the scrollview scroll the large amont of data with no problemes. Very Quick and fluid. 
then i navigate in my app or reload it and the scrollView have big big lags and stop to scroll. 

- i experience the problem only on old Android phones. 
- when i strongly press the screen and make a slow big swipe the app scroll normaly, it seems that the scrollView doesn't responds to quick/little swipes.
Like it was not a problem with the large amont of data in the scrollView but a problem with  the Gesture,Swipe listener.

**Comment by kyunkakata** [comment]
I got the same issue as @nicolasdet described above. 
It happens only with the above Android 8.0. It can scroll smoothly without issue in Android 7.0 below.
The first stack navigator doesn't have any issue when swipe, But the third or more stack navigator causes scroll view scroll slow down and laggy. I used ScrollView of react-native
