### ISSUE TITLE
Fetch error in Android https GET

### ISSUE THREAD

**Issue by djschilling** [facebook/react-native#25054]
When i call the url `https://www.cchd.de/ct/api/info` with the `fetch` api on Android i always get the error: `Network request failed`. On iOS it works fine.

I use an android simulator for my tests:

* Nexus_5X_API_27

This is the code is use to test it:

```
        fetch('https://www.cchd.de/ct/api/info')
            .then(response => {
                console.log('Fetch success', response);
            })
            .catch(error => {
                console.log('Fetch error', error);
            });
```

I also read some other issues about similar issues but none of them solved my issue.
Other urls like this one work fine: https://testdavid.church.tools/api/info

For me it seems like that is an issue with certificates but i cannot figure out what is wrong here.

React Native version:
```
info
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (4) x64 Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
      Memory: 589.11 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.1, 26.0.2, 27.0.3, 28.0.0, 28.0.3
        System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.8 => 0.59.8
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

**Comment by ptrocki** [comment]
https://github.com/facebook/react-native/issues/10404

https://github.com/facebook/react-native/issues/24120 

Maybe this will help you ?

**Comment by djschilling** [comment]
I already read these issues, but i couldn't find a solution there.

**Comment by RobertLib** [comment]
Any progress? I have the same problem. HTTP works, HTTPS doesn't work.

**Comment by Krizzu** [comment]
I can fetch from that endpoint just fine (API 28, API 24). Can anyone provide repro repo (`react-native init` + minimal changes to achieve bug)?


thanks.

**Comment by djschilling** [comment]
@Krizzu which URL did you try?

**Comment by Krizzu** [comment]
@djschilling `https://www.cchd.de/ct/api/info` and `testdavid.church.tools/api/info`, both did not throw any error
