### ISSUE TITLE
[RN 0.59.3, iOS] After upgrading from 0.51, RN wouldn't work in RN debug mode, getting a 404 from the bundler.

### ISSUE THREAD

**Issue by nadav2051** [facebook/react-native#25052]
**Issue description:**
After upgrading React and going through the motions, I've manage to get Android to work properly, but when trying to load iOS I've encountered some failure, when trying to debug the failures, I've noticed that the bundler/debugger-ui won't behave properly.

Running the bundler in --verbose mode, when the bundler is being queried, I see this:

```
 BUNDLE  [ios, dev] ./index.ios.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (1/1), done.

::1 - - [27/May/2019:12:45:42 +0000] "GET **/index.ios.delta&revisionId=dcebb881488c2fbc** HTTP/1.1" 404 186 "http://localhost:8081/debugger-ui/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
```
That URL returns a 404 which causes the debugging process to hang.

Once I refresh the localhost:8081/debugger-ui/ page, it will work for one time, but the next time the debugger asks for a bundle the same error returns.

**React Native version:**

> info 
>   React Native Environment Info:
>     System:
>       OS: macOS 10.14.4
>       CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
>       Memory: 949.80 MB / 16.00 GB
>       Shell: 3.2.57 - /bin/bash
>     Binaries:
>       Node: 11.6.0 - /usr/local/bin/node
>       Yarn: 1.12.3 - /usr/local/bin/yarn
>       npm: 6.5.0 - /usr/local/bin/npm
>     SDKs:
>       iOS SDK:
>         Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
>     IDEs:
>       Android Studio: 3.4 AI-183.6156.11.34.5522156
>       Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
>     npmPackages:
>       react: ^16.5.2 => 16.8.6 
>       react-native: 0.59.3 => 0.59.3

 
**Reproducability** 
This is pretty hard to provide a reproduction example, since this is a project that includes RN manually in its native code.

**Describe what you expected to happen:**
I expect the debugger to load so I can enjoy the wonders of debugging :)

**Comment by eyalabadi98** [comment]
Hello,

How did you solve this? I'm having the same issue @nadav2051

**Comment by nadav2051** [comment]
Hey! 

What solved the problem for me was changing the URL path I was accessing to download the bundle.
From:
jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.ios.bundle"];
To:
jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.bundle?platform=ios&dev=true"];

Let me know if that worked for you.
