### ISSUE TITLE
NumberOfLines of text has bug in Ios && Android

### ISSUE THREAD

**Issue by chenhuaxian** [facebook/react-native#25050]
NumberOfLines Bug:

1、Show not accurate in IOS

2、 Truncation not accurate in Android

React Native version:
"react": "16.6.3",
"react-native": "0.57.8",

## Steps To Reproduce

1. Create a sample Text in your code.
2. set numberOfLines

Actual Result:
（1）Ellipsis is inaccurate in IOS：
          [https://i9.taou.com/maimai/p/20086/5907_53_EM8DiV48lQc2XL](url)
          [https://i9.taou.com/maimai/p/20086/5933_53_6epBOLhKXLhtw9](url)
（2）When the ending is an emoji, the truncation is inaccurate in Android： 
         [https://i9.taou.com/maimai/p/20088/4125_53_8Q6ILN9AIyj5yZ](url)

Expected Result:
       Display the text normal

**Comment by ptrocki** [comment]
https://github.com/facebook/react-native/pull/24975 probably it is related.

**Comment by chenhuaxian** [comment]
![image](https://user-images.githubusercontent.com/14290626/58421113-c42f7a00-80c1-11e9-9add-2ca3c80ed6a1.png)

![image](https://user-images.githubusercontent.com/14290626/58421127-cc87b500-80c1-11e9-8fdf-2d79201c27d7.png)

**Comment by chenhuaxian** [comment]
![image](https://user-images.githubusercontent.com/14290626/58421163-ddd0c180-80c1-11e9-9f1c-0130fee3b586.png)

**Truncation not accurate in Android**

**Comment by chenhuaxian** [comment]
![image](https://user-images.githubusercontent.com/14290626/58421240-0bb60600-80c2-11e9-8ebd-9a0efb480c50.png)

**Truncation not accurate in Android**

**Comment by zhongwuzw** [comment]
@chenhuaxian Hi, please separate issues of iOS and Android, and fill in the template issue. After that, we can try to investigate.
