### ISSUE TITLE
[Android-RN 0.59.8] Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xee0f0434 in tid 16493 (mqt_js)

### ISSUE THREAD

**Issue by ducNgbk** [facebook/react-native#25060]
Hi I want to build my project on **RN 0.59.8**. MY app use **react-native-webgl**
Building process is fine, but **app crashes right after it starts.**

> A: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xee0f0434 in tid 16493 (mqt_js), pid 16138 (com.testthree)

However, **everything works fine on RN 0.57.8**

React Native version:
```
System:
      OS: macOS 10.14.4
      CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 408.59 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
Binaries:
      Node: 12.1.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.0, 26.0.1, 27.0.3, 28.0.2, 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom
IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.8 => 0.59.8
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      react-native-rename: 2.2.1
```

## Steps To Reproduce

1. Init new RN prj with RN 0.59.8
2. Add react-native-web-gl module
3. Download NDK 18
4. Build and run project with `react-native run-android`

Describe what you expected to happen:

Snack, code example, or link to a repository:

**Comment by mstiggle** [comment]
Check out #24261. There are alternate jsc builds that have been posted that you can switch to which has solved it for us and others.

**Comment by RomanovYurii** [comment]
Magical part of code saved my life. add this to `app/build.gradle`:
`        ndk {  
            abiFilters "armeabi-v7a", "x86"  
        } 
`

**Comment by j-wang** [comment]
Cutting out the 64 bit builds with ndk filters (which is what that code does) only fixes it for certain phones unfortunately. For our app, we though it fixed it but found other phones crashing without a full JSC switchout to get rid of the JIT.

**Comment by dishantwalia** [comment]
@RomanovYurii When we removed 64 bit ndk filters "arm64-v8a", "x86_64" from ndk abiFilters in defaultConfig block of build.gradle by provide only 32 bit support. The crash has gone but as per [Google 64 bit support mandate](https://developer.android.com/distribute/best-practices/develop/64-bit) this needs to be fixed with 64 bit ndk support .

**Comment by verticelo** [comment]
@ducNgbk could you please test with 59.10 since it contains an updated jsc, and if it works then close this ticket?

**Comment by nik910** [comment]
Check your native-lib.cpp, the syntax has changed.

**Comment by taleankit** [comment]
This issue still occurred in React Native Version 0.60. I am using realm for offline storage, normal query worked properly but when filtered are applied the app crash suddenly and got this message in Logcat.
`    --------- beginning of crash
2019-09-20 10:09:33.323 8264-8337/com.rippleeffect A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x28 in tid 8337 (mqt_js), pid 8264 (com.projectape)`
