### ISSUE TITLE
fbsdk IOS - framework not found CoreServices for architecture i386

### ISSUE THREAD

**Issue by nirvo** [facebook/react-native#25063]
I am using FBSDK with RNN2, I get this issue when I compile IOS xcode project 

ld: framework not found CoreServices for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

React Native Environment Info:
    System:
      OS: macOS Sierra 10.12.6
    Binaries:
      Node: 11.13.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.2, macOS 10.13, tvOS 11.2, watchOS 4.2
      Android SDK:
        API Levels: 26, 28
        Build Tools: 27.0.2, 27.0.3, 28.0.3
        System Images: android-27 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 9.2/9C40b - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.8 => 0.59.8 
    npmGlobalPackages:
      create-react-native-web-app: 0.1.14
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

I set with Xcode : 
Architecture : $(ARCHS_STANDARD)
Base SDK : 11.2
Build Active architecture Only : NO
Valid Architecture : arm64 armv7 armv7s i386

Can you give me help ?

**Comment by risingworld777** [comment]
https://github.com/facebook/react-native/issues/21768#issuecomment-429644983

**Comment by nirvo** [comment]
I have : 
#define FBSDK_VERSION_STRING **@"4.39.1"**
#define FBSDK_TARGET_PLATFORM_VERSION @"v3.2"

package.json
"dependencies": {
    "react": "16.8.3",
    "react-native": "0.59.8",
    "react-native-fbsdk": "^0.8.0",
    "react-native-navigation": "^2.20.2"
  },

Which SDK should I install ?

**Comment by risingworld777** [comment]
You should use lower version of fbsdk.

So
"react-native-fbsdk": "^0.6.0",
FB iOS SDK: <4.33.0

or You can upgrade xcode version to 10.x

**Comment by nirvo** [comment]
It is ok using react-native-fbsdk ^0.6.0 + FacebookSDKs-iOS-4.32.0 + Build Active architecture Only 

but when I set Build Active architecture Only : NO, I get this error :
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_RCTBridge", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_RCTBundleURLProvider", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_RCTRootView", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by dulmandakh** [comment]
It means that fbsdk doesn't include i386 binary. Closing this issue because it's not related to React Native.
