### ISSUE TITLE
Docs: background position

### ISSUE THREAD

**Issue by unutoiul** [facebook/react-native#25062]
I'm using ImageBackground and I have a 
```
height:100% ;
resizeMode: 'contain';
```

the image is in the middle how can I position it at the top..in css you could do : background-position: top;
 
Thanks,
Lucas

**Comment by ecreeth** [comment]
@unutoiul You can try eliminating the height and putting `flex: 1`.
Also, this is not the best place to ask these things, you should consult forums or pages specialized in solving this type of problems

**Comment by unutoiul** [comment]
```flex:1``` doesn't change the background position....

**Comment by kelset** [comment]
👋 there -this seems more a question for [StackOverflow](https://stackoverflow.com/questions/tagged/react-native) instead of a bug of the repo.

For this reason I'm going to close this.

**Comment by unutoiul** [comment]
there is a bug/feature, you can't change the background position..

**Comment by kelset** [comment]
Then I suggest you open an actual issue following the template, and providing a repro.
