### ISSUE TITLE
AlertIOS--onPress of OK does not close the alert half of the time, also freezes the app. 

### ISSUE THREAD

**Issue by thekennysong** [facebook/react-native#2506]
Hello, 

So I have gotten the alertIOS to work within my app, however, I am unable to get the alert to close when I click on OK 100% of the time. Also, when it does close, the app freezes and I am unable to do anymore clicks with the app.

**Comment by brentvatne** [comment]
Can you post a reproducible example? I have never seen this happen.

**Comment by thekennysong** [comment]
Here is the code: 

    if((this.state.wine + this.state.beer + this.state.shot - this.state.hour) >= this.state.limit){
        AlertIOS.alert('STOP!',
              'You have exceeded your limit. Please stop.',
            [
              {text: 'Okay', onPress: () => console.log('Button Pressed!')},
            ]);
    }

**Comment by thekennysong** [comment]
@brentvatne My bad! Had slow animations down and it made it buggy looking. My bad again!

**Comment by brentvatne** [comment]
:) cool, glad you resolved it!
