### ISSUE TITLE
Unexpected token function,cliEntry.js Document error reporting

### ISSUE THREAD

**Issue by DamonIOS** [facebook/react-native#25073]
React Native version:

## Steps To Reproduce
Scheme--->Run(Info---release)
3.product--->build
-->

**Comment by ecreeth** [comment]
@DamonIOS this needs more information see [this](https://github.com/facebook/react-native/issues/new/choose)

**Comment by kelset** [comment]
Closing since there has been no follow up nor the needed info - btw thanks @ecreeth 	for helping out triaging 🤗

**Comment by madeeha96** [comment]
This issue still exists in 0.61.1 :/
