### ISSUE TITLE
How to send request to wifi when wifi and mobile data both are connected?

### ISSUE THREAD

**Issue by Pankajmalhan** [facebook/react-native#25070]
I am working on a project in which we connect to a  Raspberry PI device. This PI device makes a hotspot and we make a connection to PI using WIFI.  If Mobile data is off then all APIs request are sent to WIFI but if mobile data is on then APIs request doesn't redirect to wifi instead request are send to Mobile data.
How can I force to send all API request to WIFI instead of Mobile data or there is any way to Turn on/off mobile data programmatically.

React Native version: 0.57.8

**Comment by ecreeth** [comment]
@Pankajmalhan I think this is not the best place to ask for information about it. You should consult this information in forums or stackoverflow
