### ISSUE TITLE
org.gradle.initialization.ReportedException: org.gradle.internal.exceptions.LocationAwareException: Script '[PATH_TO_PRIOJECT]node_modules/react-native/react.gradle' line: 95

### ISSUE THREAD

**Issue by AmitHanoch** [facebook/react-native#25072]
Im running my react native project using react-native run-android
(not for the first time, I recently deleted my node modules and after I did npm install)

I searched several issues and nothing helped for me
such as this:
https://github.com/facebook/react-native/issues/24022

package json:
```
{
  "name": "boxofdreams",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "android-linux": "react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res && react-native run-android",
    "fix-adb": "adb reverse tcp:8081 tcp:8081",
    "emulator": "emulator -avd Nexus_5X_API_28_x86"
  },
  "dependencies": {
    "frisbee": "^2.0.5",
    "react": "16.6.0-alpha.8af6728",
    "react-native": "^0.59.8",
    "react-native-firebase": "4.2.0",
    "react-native-gesture-handler": "^1.0.9",
    "react-native-google-signin": "git+https://github.com/invertase/react-native-google-signin.git#v0.12.1",
    "react-native-tab-view": "^1.2.0",
    "react-native-vector-icons": "^6.1.0",
    "react-navigation": "^3.0.0"
  },
  "devDependencies": {
    "babel-jest": "^24.8.0",
    "jest": "^24.8.0",
    "metro-react-native-babel-preset": "0.48.2",
    "react-test-renderer": "16.6.0-alpha.8af6728"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

React Native Environment Info:
    

> System:
>       OS: macOS 10.14.5
>       CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
>       Memory: 1.96 GB / 16.00 GB
>       Shell: 3.2.57 - /bin/bash
>     Binaries:
>       Node: 10.14.2 - /usr/local/bin/node
>       npm: 6.4.1 - /usr/local/bin/npm
>       Watchman: 4.9.0 - /usr/local/bin/watchman
>     SDKs:
>       iOS SDK:
>         Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
>       Android SDK:
>         API Levels: 23, 25, 27, 28
>         Build Tools: 27.0.3, 28.0.3
>         System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
>     IDEs:
>       Android Studio: 3.3 AI-182.5107.16.33.5264788
>       Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
>     npmPackages:
>       react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728 
>       react-native: ^0.59.8 => 0.59.8 
>     npmGlobalPackages:
>       react-native-cli: 2.0.1
>       react-native-git-upgrade: 0.2.7

**Comment by ecreeth** [comment]
@AmitHanoch You can show some information about the error, if possible a screenshot or Snack, code example, or link to a repository

**Comment by AmitHanoch** [comment]
@ecreeth sorry about the delay - here is a screenshot of the error
<img width="1351" alt="error" src="https://user-images.githubusercontent.com/16944568/59264565-0ae9ac00-8c4c-11e9-81c1-b8c6c4f41f15.png">
