### ISSUE TITLE
[Packager] Disable progress bar when not connected to a TTY

### ISSUE THREAD

**Issue by ide** [facebook/react-native#2508]
The bar shows up in the Travis logs like this:

```1% 5/383ing [] 2% 6/383ing [] 2% 7/383ing [] 2% 8/383ing [] 2% 9/383ing [] 3% 10/383ing [] 3% 11/383ing [] 3% 12/383ing [] 3% 13/383ing [] 4% 14/383ing [] 4% 15/383ing [] 4% 16/383ing [] 4% 17/383ing [] 5% 18/383ing [] 5% 19/383ing [] 5% 20/383ing [] 5% 21/383ing [] 6% 22/383ing [] 6% 23/383ing [] 6% 24/383ing [] 7% 25/383ing [] 7% 26/383ing [] 7% 27/383ing [] 7% 28/383ing [] 8% 29/383ing [] 8% 30/383ing [] 8% 31/383ing [] 8% 32/383ing [] 9% 33/383ing [] 9% 34/383ing [] 9% 35/383ing []```

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/packager-disable-progress-bar-when-not-connected-to-a-tty
