### ISSUE TITLE
NativeModules is empty when debug off

### ISSUE THREAD

**Issue by navata** [facebook/react-native#25086]
I have use NativeModules from react native when I upgrade RN 0.59.8. But this value is usually empty, but I open debug mode, which working normal.
```

import {
      Platform,
      StyleSheet,
      Text,
      View,
      NativeModules
} from 'react-native';


export default class App extends Component<Props> {
  constructor(props) {
         super(props);
         console.log('NativeModules', NativeModules);
  }
  render() {
        return (
              <View style={styles.container}/>
         );
  }
}
```

Please help me about this issue.

**Comment by satya164** [comment]
Can you provide a GitHub repo with runnable code?

**Comment by navata** [comment]
![Simulator Screen Shot - iPhone X - 2019-05-31 at 10 08 30](https://user-images.githubusercontent.com/16706514/58679078-2d4a1280-838c-11e9-850d-bd8bab8fbbd1.png)

This is error.

**Comment by satya164** [comment]
Please provide the repro in a GitHub repo. It's not possible to repro the issue from what you posted.

**Comment by navata** [comment]
> Please provide the repro in a GitHub repo. It's not possible to repro the issue from what you posted.

You can run the code between RN version 0.55.4 and 0.59.8 as below (turn off mode debug):
- RN 0.55.4: working normal
- RN 0.59.8: error
I think error from core RN.

```
import React, { Component } from "react";
import {
    NativeModules
} from "react-native";
console.log("NativeModules", NativeModules.hasOwnProperty("abc"));
export default class App extends Component {
...
}
```

**Comment by satya164** [comment]
It takes a work to create a new project, copy the code you provided and try to repro it. You are facing this issue in an Open Source project, you should at least put the effort providing a runnable repro if you expect someone to spend the effort debugging it.

**Comment by navata** [comment]
@satya164 You can test this issue at repo https://github.com/navata/RNTest
