### ISSUE TITLE
Improve build failure diagnostics when NDK is missing or incorrectly set up

### ISSUE THREAD

**Issue by petterh** [facebook/react-native#25087]
If you (try to) build React Native for Android without having the NDK properly installed, you get the following error:

>A problem occurred evaluating project ':ReactAndroid'.
\> Cannot get property 'absolutePath' on null object

This is not an overly helpful diagnostic; what's wanted is this one:

>ndk-build binary cannot be found, check if you've set $ANDROID_NDK environment variable correctly or if ndk.dir is setup in local.properties

I have a one-line fix and will submit a PR shortly.

React Native version: **0.59.8**
>System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
    Memory: 1.83 GB / 15.93 GB
  Binaries:
    Node: 10.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5522156

## Steps To Reproduce

1. Clone react-native
2. Run yarn
3. Import into Android Studio (no NDK installed)
4. Build

Describe what you expected to happen:

I would like the build failure to properly diagnose the missing NDK rather than throwing an NRE

**Comment by petterh** [comment]
[Link to PR that fixes this issue](https://github.com/facebook/react-native/pull/25088)

**Comment by kelset** [comment]
omg yes pls! This is going to help so much 🙇‍♂️ Thanks :)
