### ISSUE TITLE
WebView example doesn't work: automaticallyAdjustContentInsets error

### ISSUE THREAD

**Issue by cmcewen** [facebook/react-native#251]
Steps to reproduce:
* clone repo
* run UIExplorer demo
* click on WebView in the list

Error:
`[RCTLog][tid:0x7fe1bbc40410][RCTConvert.m:149]>Expected NSArray or NSDictionary for UIEdgeInsets, received __NSCFBoolean: 0`

Fix (temporarily):
- delete `automaticallyAdjustContentInsets={false}`

**Comment by lwansbrough** [comment]
+1

Use `contentInset`'s value in place of `automaticallyAdjustContentInsets`'s value for now. Obvious this will break once this is fixed though, only use this if you need to adjust the content inset right now.
