### ISSUE TITLE
Documentation: Links to components need show 404

### ISSUE THREAD

**Issue by inferate** [facebook/react-native#25104]
React Native version:

## Steps To Reproduce

1.Access the url: https://facebook.github.io/react-native/docs/components-and-apis
2.Try to open any component

Describe what you expected to happen:

Snack, code example, or link to a repository:

**Comment by ecreeth** [comment]
@inferate this error is related to the documentation, please close this issue and open a new one [here](https://github.com/facebook/react-native-website/issues)

**Comment by hramos** [comment]
Looks like it was broken in https://github.com/facebook/react-native-website/pull/933 which itself attempted to fix some broken links.
