### ISSUE TITLE
TabBar Navigation

### ISSUE THREAD

**Issue by cmhsu** [facebook/react-native#2510]
Is there a way to navigate to a different tab from another tab without actually clicking on the tab? I have a map in one tab, and when I click on a marker, it should redirect to another tab item and pass in the coordinate information to the new tab. Is this possible? Thank you.

**Comment by ide** [comment]
You should be able to set the `selected` prop of the tab to true: https://facebook.github.io/react-native/docs/tabbarios-item.html#selected
