### ISSUE TITLE
IOS Archive -> Distribute Content Instead Distribute App

### ISSUE THREAD

**Issue by sm-hejazi** [facebook/react-native#25113]
## Description
react-native run-ios ok, in Xcode build&run ok but when **_Archive_** App 
 I see **Distribute Content** _instead_ **Distribute App**
 
I removed ios folder and run **react-native eject** but The problem is still there.

![Screen Shot 2019-06-01 at 16 44 54](https://user-images.githubusercontent.com/12386385/58748673-92d3f700-8491-11e9-80bd-eb5693c86027.png)

##  React Native Environment Info:
    
- System:

      OS: macOS 10.14.3
      CPU: (4) x64 Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz
      Memory: 916.72 MB / 10.85 GB
      Shell: 3.2.57 - /bin/bash
    

- Binaries:

      Node: 12.1.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    

- SDKs:

      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    

- IDEs:

      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    

- npmPackages:

      react: 16.8.3 => 16.8.3 
      react-native: 0.59.8 => 0.59.8 
    

- npmGlobalPackages:

      react-native-cli: 2.0.1

________________________________________
package.json
```json
{
  "name": "montaman",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "accounting": "^0.4.1",
    "jsc-android": "^241213.1.0",
    "lodash": "^4.17.11",
    "mobx": "^5.9.4",
    "mobx-persist": "^0.4.1",
    "mobx-react": "^5.4.4",
    "moment-jalaali": "^0.8.3",
    "react": "16.8.3",
    "react-native": "0.59.8",
    "react-native-check-box": "^2.1.7",
    "react-native-communications": "^2.2.1",
    "react-native-fast-image": "^6.0.1",
    "react-native-firebase": "^5.3.1",
    "react-native-gesture-handler": "^1.2.1",
    "react-native-global-props": "^1.1.5",
    "react-native-image-progress": "^1.1.1",
    "react-native-keyboard-aware-scroll-view": "^0.8.0",
    "react-native-keyboard-spacer": "^0.4.1",
    "react-native-linear-gradient": "^2.5.4",
    "react-native-material-dialog": "^0.7.6",
    "react-native-material-kit": "^0.5.1",
    "react-native-modal-datetime-picker": "^7.4.2",
    "react-native-persian-calendar-picker": "^3.0.0",
    "react-native-photo-upload": "^1.3.0",
    "react-native-progress": "^3.6.0",
    "react-native-restart": "^0.0.10",
    "react-native-simple-radio-button": "^2.7.3",
    "react-native-simple-toast": "^0.0.8",
    "react-native-swipeout-rtl": "https://github.com/sm-hejazi/react-native-swipeout-rtl",
    "react-navigation": "^3.11.0",
    "react-side-effect": "^1.1.5"
  },
  "devDependencies": {
    "@babel/core": "^7.4.5",
    "@babel/plugin-proposal-decorators": "^7.4.4",
    "@babel/runtime": "^7.4.5",
    "babel-jest": "^24.8.0",
    "jest": "^24.8.0",
    "metro-react-native-babel-preset": "^0.54.1",
    "react-test-renderer": "16.8.3"
  },
  "jest": {
    "preset": "react-native"
  },
  "rnpm": {
    "assets": [
      "./assets/fonts"
    ]
  }
}
```

**Comment by sm-hejazi** [comment]
### Solved
**react-native-fast-image** latest **version(6)**
_

> finally downgrade to 5.4.2 works for me.

_

[rnFastImage-6](https://github.com/DylanVann/react-native-fast-image/issues/468)

**Comment by hanishcodebrew** [comment]
Thanks a lot @sm-hejazi :)
