### ISSUE TITLE
installation problems

### ISSUE THREAD

**Issue by savva-shishak** [facebook/react-native#25111]
when you start the command reak-nativ rune-android error appears, somebody please me:

info Starting JS server.
info Building and installing the app on the device (cd android && gradlew.bat ap
p: install Debug>.
Task : app: installDebug FAILED
FAILURE: Build failed with an exception.
What went wrong:
Execution failed for task app: install Debug' .
com. android. builder. testing. api.DeviceException: No connected devices!
Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
sorption to get more log output. Run with --scan to get full insights.
Get more help at https://help.gradle.org
BUILD FAILED in ?safe
26 actionable tasks: 1 executed, 25 up-to-date
idle
WAITING
error Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https: //facebook.github.io/react-native/docs/getting-started. html
error Command failed: gradlew.bat app:installDebug. Run CLI with --verbose flag
for more details.

**Comment by zusinShinpei** [comment]
adb reverse tcp:8081 tcp:8081 at android sdk platform-tools folder

**Comment by savva-shishak** [comment]
can you give more details?
