### ISSUE TITLE
In windows react-native run-android not starts node

### ISSUE THREAD

**Issue by Warmachine13** [facebook/react-native#25118]
React Native version:0.60.rc

## Steps To Reproduce

1.react-native init RN060
2.react-native run-android

Describe what you expected to happen:

Open node and install aplication in emulator

**Comment by jobpaardekooper** [comment]
You need to have the emulator open before you run `react-native run-android`

**Comment by kelset** [comment]
Uhm, so you are not seeing any error?

Also, this seems to be related to the CLI, which now lives in its own repo, can you post this issue there?

https://github.com/react-native-community/cli

**Comment by Warmachine13** [comment]
Same problem in this vesion and crash node after start build gradlew 

he open node app but close after start build gradlew  and I need run 'react-native start'

![crash react native android](https://user-images.githubusercontent.com/36778572/60695926-fc448c80-9eb9-11e9-8959-9f0791bd4c7f.png)

react-native-cli: 2.0.1
react-native: 0.60.0
