### ISSUE TITLE
Archive crashing with main.jsbundle does not exist (after upgrade to xcode 10.2)

### ISSUE THREAD

**Issue by arminas5** [facebook/react-native#25124]
Hi there, 

I'm trying to make app archive with command line and got this error:

````
Loading dependency graph, done.
error SHA-1 for file /Users/Admin/Projects/app/node_modules/metro/src/lib/polyfills/require.js (/Users/Admin/Projects/app/node_modules/metro/src/lib/polyfills/require.js) is not computed. Run CLI with --verbose flag for more details.
+ [[ false != true ]]
+ [[ ! -f /Users/Admin/Library/Developer/Xcode/DerivedData/app-erjlbyzectedrjajiphwvhbfwswh/Build/Intermediates.noindex/ArchiveIntermediates/app/BuildProductsPath/Release-iphoneos/app.app/main.jsbundle ]]
+ echo 'error: File /Users/Admin/Library/Developer/Xcode/DerivedData/app-erjlbyzectedrjajiphwvhbfwswh/Build/Intermediates.noindex/ArchiveIntermediates/app/BuildProductsPath/Release-iphoneos/app.app/main.jsbundle does not exist. This must be a bug with'
error: File /Users/Admin/Library/Developer/Xcode/DerivedData/app-erjlbyzectedrjajiphwvhbfwswh/Build/Intermediates.noindex/ArchiveIntermediates/app/BuildProductsPath/Release-iphoneos/app.app/main.jsbundle does not exist. This must be a bug with + echo 'React Native, please report it here: https://github.com/facebook/react-native/issues'
````
React Native version:
```
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 18.16 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.15.1 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.8 => 0.59.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

## Steps To Reproduce

```
xcodebuild -workspace app.xcworkspace -scheme app -sdk iphoneos -configuration AppStoreDistribution archive -archivePath $PWD/build/app.xcarchive
```

**Comment by suretarget** [comment]
I have the same issue after upgrade to xCode Version 10.2.1 (10E1001)

RN 0.59.9.
Debug mode OK.
Release mode ( main.jsbundle does not exist ).

RN 0.60.0 RC2.
Both working fine.

**Comment by dvukman** [comment]
Same issue but with Xcode 10.1. (RN 0.59.9)

**Comment by dyihoon90** [comment]
Same issue with XCode  10.3 (RN 0.59.2)

**Comment by dvukman** [comment]
It turned out I had the **Current** node installed instead of the **LTS** version. Now it's working.

**Comment by esutton** [comment]
Same problem, after upgrading from 0.59 to 0.60.  Cannot find main.jsbundle when archive building in both xcode and command line.

````
"react": "^16.8.6",
"react-native": "^0.60.4",
   
node v10.15.1
xcode 10.3
````

`find . -name main.jsbundle` finds nothing.

**Comment by sirpeas** [comment]
Same here after update from 0.59.5 to 0.60.5 xcode 10.3

**Comment by sirpeas** [comment]
I had the same issue. It turns out that it wasn't fault of ReactNative. I forget to provide env variables that I required in a project.

I recommend you to run:
```
react-native bundle --entry-file='index.js' --bundle-output='./ios/main.jsbundle' --dev=false --platform='ios'
```
It may output what you have wrong and dont forget to remove generated bundle `rm ./ios/main.jsbundle`  Good luck 😃

**Comment by timrc** [comment]
> It turned out I had the **Current** node installed instead of the **LTS** version. Now it's working.

It doesn't work with node 12 for me either, node 11.9 works fine.

**Comment by zrbaihld** [comment]
your react-native has error.please check.

**Comment by cvvspb** [comment]
I use nvm for node version management.
Tried to upgrade node, got the same issue.

Seems like I forgot to reinstall global packages:
Migrating from 8.12.0 to 13.1.0:

```
nvm install 13.1.0 --reinstall-packages-from=8.12.0
nvm use 13.1.0
nvm alias default 13.1.0
```

That fixed the issue

**Comment by mobitar** [comment]
In my case the React Native CLI was running with my system node installation (which was on v6), rather than my nvm installation (v13.5). I noticed this in the fail message provided by Xcode: `/usr/local/bin/node cli.js bundle --entry-file...`.

Deleting `/usr/local/bin/node` fixed the issue.

**Comment by jenskuhrjorgensen** [comment]
> > It turned out I had the **Current** node installed instead of the **LTS** version. Now it's working.
> 
> It doesn't work with node 12 for me either, node 11.9 works fine.

Thanks for the hint @dvukman and @timrc. I had version 13.xx installed on our build server and downgraded to 10.xx (worked on my local machine) and it solved the problem. Didn't bother to try with 11.9. I downgraded using [this](https://apple.stackexchange.com/a/207883) approach.

**Comment by spsaucier-bakkt** [comment]
This also happens if your app is not in running order. Make sure that it is building properly on your virtual device as well.
