### ISSUE TITLE
[MapView] Draggable annotations

### ISSUE THREAD

**Issue by Intellicode** [facebook/react-native#2512]
For our app it would be nice if the user has the ability to drag a marker on the map. Currently, it doesn't [look supported](https://facebook.github.io/react-native/docs/mapview.html#annotations), but I imagine an implementation would have the properties ```draggable``` and ```onDrop```. If it sounds interesting to add, I can work on this feature and create a PR.

**Comment by nicklockwood** [comment]
That sound great!

**Comment by phongyewtong** [comment]
+1

**Comment by alexisohayon** [comment]
+1

**Comment by brentvatne** [comment]
:+1: any progress @Intellicode?

**Comment by Intellicode** [comment]
@brentvatne sorry, I didn't see your @mention, I guess I'm too late :P We worked around it by using Google Maps

**Comment by af7** [comment]
@Intellicode Is it easy to integrate google maps (or leaflet) within react native? Can we do everything that is supported by Google Maps? Or are we constrained? Thanks.
