### ISSUE TITLE
Horizontal reversed view inverts the paddings right & left

### ISSUE THREAD

**Issue by yairopro** [facebook/react-native#25128]
A `View` (flexbox) with a `flexDirection: "row-reverse"` as style makes the two horizontal paddings, left and right, inverted.
For instance, setting `paddingLeft: 10` will display a padding at the right of the view.

React Native version:
```
info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 28.87 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
      Yarn: 1.16.0 - ~/.nvm/versions/node/v10.13.0/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.13.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.2, 26.0.2, 26.0.3, 27.0.0, 27.0.3, 28.0.2, 28.0.3
        System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.6 => 16.8.6 
      react-native: ^0.59.8 => 0.59.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

## Steps To Reproduce

1. Create a `<View />` with a `flexDirection: "row-reverse"` and a `paddingRight: 10` as style.
2. That's it.

Describe what you expected to happen:
I expect the padding to be on the right side (the good one, not necessarily right) like in CSS flexbox ([see demo here](https://jsfiddle.net/b2sw80qu/)).

Snack: https://snack.expo.io/BJMQhiM0V

**Comment by dblachut-adb** [comment]
Can you check on 0.60.0? This may have something to do with yoga library that was updated in the meantime.
