### ISSUE TITLE
Custom Header is parsed to lowercase.

### ISSUE THREAD

**Issue by Renanmacedo** [facebook/react-native#25131]
Because why i put a custom header it is send as  lowecase. As fixed this issue? 

React Native version: 0.59.8

  Run `react-native info` in your terminal and copy the results here.
React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 36.98 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 19, 20, 21, 22, 23, 24, 25, 26, 27, 28
        Build Tools: 19.1.0, 26.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.1, 28.0.3
        System Images: android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.8 => 0.59.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1

-- my code 
export const api = axios.create({
    baseURL: enviroments.BASE_URL
    ,headers: {
        "Authorization": enviroments.TOKEN
        ,"SellerId": enviroments.ID
        ,"SellerPass": enviroments.PASS
        ,"Content-Type": "application/json"
    }
    ,validateStatus: status => status <= 500
});
--- my header in server after the print
["sellerid"]=> "xxxxxxxxxxx" // -> custom header
["Authorization"]=> "xxxxxxxxxxxxxxxx"  // -> header the http
["sellerpass"]=> "xxxxxxxxx" // -> custom header

**Comment by a-c-sreedhar-reddy** [comment]
Is not this related to axios?

**Comment by Renanmacedo** [comment]
@a-c-sreedhar-reddy I use the axios, but in fetch the same problem occurs. I did a search and this occurs in the XMLHttpRequestBase.js which is part of the react. I also saw that it has an http specification, stating that headers are case-insensitive. But can not you get around that? Only on the same server?

**Comment by a-c-sreedhar-reddy** [comment]
yeah headers are case insensitive.

**Comment by Renanmacedo** [comment]
Yes. I agree with you, but for the headers that are part of http, there is a conversion (I do not know how), that arrives on the server equal to what was sent by the client. That is my main question ... I respect RFCs a lot. Probably, if I do not get a plausible answer, I will deal with it on the server.
