### ISSUE TITLE
Support Project Catalyst (running iPad apps on macOS)

### ISSUE THREAD

**Issue by brunolemos** [facebook/react-native#25133]
Apple has just announced Project Catalyst on WWDC 2019, which allows iOS/iPads to run on macOS without modification. This is AWESOME.

Of course it's still beta, but it's already available today for developers to test.

We need to make sure React Native iPaf apps builds and works perfectly on macOS.

**Comment by brunolemos** [comment]
@hramos @cpojer Can we leave this open? People are coming looking for this info and we can centralize here.

**Comment by ide** [comment]
Someone got this working last year pretty quickly. It should be easier to support Catalyst than tvOS, for example.

**Comment by brunolemos** [comment]
> Someone got this working last year pretty quickly. It should be easier to support Catalyst than tvOS, for example.

True! I believe it was @wbroek @steventroughtonsmith

**Comment by fungilation** [comment]
Ya I'm looking for docs and experience on this. How automatic is such "porting" from iPad to Mac?

My notes/links researching this:
* https://github.com/facebook/react-native/issues/16152
* https://developer.apple.com/design/human-interface-guidelines/ios/overview/ipad-apps-for-mac/
* https://github.com/wix/react-native-navigation/blob/master/docs/docs/layout-types.md#splitview-ios-only

**Comment by brunolemos** [comment]
Let's keep the discussion here: https://github.com/react-native-community/discussions-and-proposals/issues/131
