### ISSUE TITLE
Picker child with condition

### ISSUE THREAD

**Issue by aliazizi** [facebook/react-native#25141]
React Native version: 0.57
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
      Memory: 1.46 GB / 7.92 GB
    Binaries:
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
      Watchman: 4.9.4 - D:\watchman\watchman.EXE
    IDEs:

## Steps To Reproduce

1. go to https://snack.expo.io/@cooper47/mad-waffle
2. change picker and see the error

I want to add an `Picket.Item` with condtion
Also I ask a question in https://stackoverflow.com/q/56439734/1827594 and I think it's a bug

Snack, code example, or link to a repository:
https://snack.expo.io/@cooper47/mad-waffle

**Comment by a-c-sreedhar-reddy** [comment]
#23748 #23884 These two solve the issue for android. Currently they are in master not yet released.

**Comment by aliazizi** [comment]
still no luck, after condition changed ( for example I have 3 child and on condition changed I got 2 ) I get error 

error message : `length=1; index=3`
