### ISSUE TITLE
TypeError: global.pokeSamplingProfiler is not a function when trying to open debugger

### ISSUE THREAD

**Issue by range-of-motion** [facebook/react-native#25142]
React Native version:

```
  React Native Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
      CPU: (4) x64 Intel(R) Core(TM) i5-6500T CPU @ 2.50GHz
      Memory: 443.54 MB / 15.53 GB
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 8.10.0 - /usr/bin/node
      Yarn: 1.16.0 - /usr/bin/yarn
      npm: 3.5.2 - /usr/bin/npm
    SDKs:
      Android SDK:
        API Levels: 22, 23, 26, 27, 28
        Build Tools: 28.0.3
        System Images: android-27 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.1 => 0.59.1 
```

## Steps To Reproduce

1. Run my app
2. Try to use remote debugger

Describe what you expected to happen:

Debugger should have opened. This happened instead.

![Screenshot from 2019-06-04 14-27-47](https://user-images.githubusercontent.com/9268822/58879014-f306ab00-86d4-11e9-989b-c9feef91c18c.png)

**Comment by range-of-motion** [comment]
FYI if anyone runs into this, clear your cache and try again.

**Comment by kaitlynbrown** [comment]
Clearing cache doesn't resolve the issue.

Also, even if clearing your cache were a workaround, this is still a major bug that needs to be addressed, so why is this issue closed?

**Comment by range-of-motion** [comment]
Fuck do I know? I opened this issue, and then closed it because my issue got resolved. If it doesn't work for you, just re-open it and continue? I'm not stopping you 🤷‍♂

**Comment by range-of-motion** [comment]
Yeah this isn't an issue for me. As I said––clear cache, reinstall, and try again.
