### ISSUE TITLE
[PickerIOS] cannot control the height of the PickerIOS element

### ISSUE THREAD

**Issue by joeyvandijk** [facebook/react-native#2514]
At default the PickerIOS element has a minimum height, but when I want to change that (to get a smaller form) I have issues while the element disappears.

![bug](https://cloud.githubusercontent.com/assets/3379812/9605977/18442094-50c1-11e5-844f-dc239de16623.png)

Please see https://rnplay.org/apps/KbmuvQ for a demo of the issue. 

I would like to see more documentation/information/examples how to use the PickerIOS, because I was expecting that "test1" would be visible and that "test2" would be hidden. Like you see above they are moved (&visible) because the element has a certain default height, which I want to control.

Hope this is my wrong (so a documentation issue), but am not seeing other examples of PickerIOS and/or issues. Only an [orientation](https://github.com/facebook/react-native/issues/1294) issue with PickerIOS that perhaps has a connection with this issue.

**Comment by MikaelCarpenter** [comment]
I altered your demo [here](https://rnplay.org/apps/bBODdw/) with the workaround that I use to control the height of the picker. 

One problem though is that the picker is only hidden, but it's still touchable, which can cause problems.
