### ISSUE TITLE
XCode 11 Beta App Launch Crash

### ISSUE THREAD

**Issue by pramodsharma403** [facebook/react-native#25154]
React Native version: 
"react": "16.8.3",
"react-native": "0.59.8"

No other dependency added.

## Steps To Reproduce

1. Create a fresh project with **react-native init ProjectName**
2. Open iOS project in **XCode 11 beta** & run your project.
3. npm start
4. App crash with - 

> Unknown argument type '__attribute__' in method -[RCTAppState getCurrentAppState:error:]. Extend RCTConvert to support this type.

Error Log from XCode -

> Exception '*** -[__NSArrayM objectAtIndexedSubscript:]: index 1 beyond bounds [0 .. 0]' was thrown while invoking getCurrentAppState on target AppState with params (
>     2,
>     3
> )

Describe what you expected to happen:
App should not get crash.

Snack, code example, or link to a repository:

Adding a screenshot for more clarification below.
<img width="350" alt="Screenshot 2019-06-05 at 5 22 00 PM" src="https://user-images.githubusercontent.com/5866845/58954815-d2fbe800-87b7-11e9-9054-f970261cdce3.png">

**Comment by zhongwuzw** [comment]
@pramodsharma403 Hi, thanks for reporting, we already fixed it, please see https://github.com/facebook/react-native/issues/25138. We may cherry-pick it in next release.

**Comment by Base29** [comment]
Hello ... I am running RN version 0.57.0 ... recently updated xcode to version 11.0 ... and I am facing this issue ... how can I resolve this ? Don't want to upgrade to RN 0.60.x ...

**Comment by dpecha777** [comment]
i have same problem 
![Simulator Screen Shot - iPhone 11 Pro Max - 2019-09-23 at 10 19 53](https://user-images.githubusercontent.com/12663388/65410859-b1b51b00-ddeb-11e9-9421-ee5f5f0271f1.png)

**Comment by elinahovakimyan** [comment]
I am also encountering the same problem.

**Comment by saudahmed** [comment]
I am also encountring the same problem on iOS, after Xcode update. I do not want to update to react-native 0.60

Version is react-native 0.59.3

**Comment by elinahovakimyan** [comment]
I solved the issue by upgrading react-native to 0.59.9 version.

**Comment by saudahmed** [comment]
in your project directory, open file in myproject/node_modules/react-native/React/Base/RCTModuleMethod.mm. Then correct as below: https://github.com/facebook/react-native/pull/25146/files#diff-263fc157dfce55895cdc16495b55d190

**Comment by Base29** [comment]
resolved using this method https://github.com/facebook/react-native/pull/25146#issuecomment-533995604

**Comment by mdgoodrum** [comment]
react-native upgrade 0.59.9, yarn , yarn pods seemed to do the trick for me

**Comment by iranu** [comment]
Not working on Xcode 11 GM seed

**Comment by Subway19** [comment]
Encountered this issue in Xcode 11. :(

**Comment by Base29** [comment]
please try this solution ... https://github.com/facebook/react-native/pull/25146#issuecomment-533995604

**Comment by decodedmrq** [comment]
open file in yourproject /node_modules/react-native/React/Base/RCTModuleMethod.mm. Then correct as quote below: 

> static BOOL RCTParseUnused(const char **input)
{
          return RCTReadString(input, "__attribute__((unused))") ||	  
                RCTReadString(input, "__attribute__((__unused__))") || .   // ----- Add this
                RCTReadString(input, "__unused");
}

link [here](https://github.com/facebook/react-native/pull/25146/files#diff-263fc157dfce55895cdc16495b55d190)

**Comment by harkirat1892** [comment]
0.59.9 has solved this.

If for some reason you can't upgrade right now, do this as suggested by @saudahmed 


> in your project directory, open file in myproject/node_modules/react-native/React/Base/RCTModuleMethod.mm. Then correct as below: https://github.com/facebook/react-native/pull/25146/files#diff-263fc157dfce55895cdc16495b55d190

**Comment by MichalKrakow** [comment]
@decodedmrq this actually works.
But what happend? The only updated thing is IDE, no libraries were updated and moreover it was compilng fine even after XCode updated. Just run into it after weekend.

**Comment by Sbphillips19** [comment]
I just downloaded Xcode 11 and am experiencing the same thing.  I have tried the changes above, but still get the same problem.  I have cleaned the build folder and reran, but still have the same issue.  Anything else I need to be doing?

Here were the changes I made:

```
static BOOL RCTParseUnused(const char **input)
{
  return RCTReadString(input, "__attribute__((unused))") ||
         RCTReadString(input, "__attribute__((__unused__))") ||
         RCTReadString(input, "__unused");
}
```

**Comment by feifeimonghuan3** [comment]
upgrade Xcode Version 11.1 (11A1027)

**Comment by Biplovkumar** [comment]
> react-native upgrade 0.59.9, yarn , yarn pods seemed to do the trick for me

thanks, saved my day.

**Comment by adc91** [comment]
> in your project directory, open file in myproject/node_modules/react-native/React/Base/RCTModuleMethod.mm. Then correct as below: https://github.com/facebook/react-native/pull/25146/files#diff-263fc157dfce55895cdc16495b55d190

You saved my day, this works for me.

**Comment by x5engine** [comment]
### 0.59.9 has solved this.

T**H**aNkS

**Comment by alfandy10011** [comment]
> in your project directory, open file in myproject/node_modules/react-native/React/Base/RCTModuleMethod.mm. Then correct as below: https://github.com/facebook/react-native/pull/25146/files#diff-263fc157dfce55895cdc16495b55d190

thank You

**Comment by Rubi91** [comment]
clean build folder

**Comment by rezasazesh** [comment]
> > in your project directory, open file in myproject/node_modules/react-native/React/Base/RCTModuleMethod.mm. Then correct as below: https://github.com/facebook/react-native/pull/25146/files#diff-263fc157dfce55895cdc16495b55d190
> 
> thank You

This approach makes all my text input colors white and I can no longer change it in style={{ color }} how can I fix this?

**Comment by schumannd** [comment]
https://stackoverflow.com/a/58061998/1175081

**Comment by Dhanush623** [comment]
> in your project directory, open file in myproject/node_modules/react-native/React/Base/RCTModuleMethod.mm. Then correct as below: https://github.com/facebook/react-native/pull/25146/files#diff-263fc157dfce55895cdc16495b55d190

This worked for me

**Comment by kabhimanyu** [comment]
As I still did not see any thing that works here. Adding what worked for me.

Source https://stackoverflow.com/questions/58336836/react-native-crash-after-update-to-xcode-11-0

To fix this issue, open file in

yourproject/node_modules/react-native/React/Base/RCTModuleMethod.mm.

Then correct as below:

https://github.com/facebook/react-native/pull/25146/files#diff-263fc157dfce55895cdc16495b55d190

**Comment by nikitph** [comment]
> in your project directory, open file in myproject/node_modules/react-native/React/Base/RCTModuleMethod.mm. Then correct as below: https://github.com/facebook/react-native/pull/25146/files#diff-263fc157dfce55895cdc16495b55d190

this works
