### ISSUE TITLE
[RCTStatusBarManager] How do I get the initial status bar frame?

### ISSUE THREAD

**Issue by jedlau** [facebook/react-native#2515]
v0.11.0-rc introduces status bar change events through the DeviceEventEmitter. How should I be getting the initial dimensions of the status bar (i.e., before any events fire)? The use case is so that I can size my view appropriately when it first mounts, and the status bar is not the normal 20 pts. in height (e.g., hotspot or maps navigation is on).

**Comment by brentvatne** [comment]
@jedlinlau - good question! It doesn't look like this is possible right now. Could you try modifying https://github.com/facebook/react-native/blob/b998e5a7b74905b30b1137a02e14cd5e6f97fccc/React/Modules/RCTStatusBarManager.m to add an exported function that grabs the current state? cc @a2

**Comment by brentvatne** [comment]
@jedlinlau - I've implemented this before here: https://github.com/brentvatne/react-native-status-bar-size/blob/master/RNStatusBarSize/RNStatusBarSize.m - so you should be able to base your implementation off of that. This would be a great way to get a first contribution in :smile:

**Comment by grabbou** [comment]
@brentvatne could you assign me so I don't forget about this one?

**Comment by ide** [comment]
Looks like we can assign only to accounts marked as Collaborators.

@vjeux could you get @grabbou added to the GitHub group with the React Conf attendees who were in the react-native preview? I think that should get him collab status.

**Comment by vjeux** [comment]
This group is long gone unfortunately :( Everyone there had push access to the repo :x

**Comment by ide** [comment]
@vjeux mm ok. @grabbou looks like github doesn't let me assign this to you 😕

**Comment by brentvatne** [comment]
@grabbou I hereby dub this issue assigned to you

**Comment by jedlinlau** [comment]
@brentvatne : Thanks! Looks like I wasn't quick enough to grab this one, though. I'll look for another "Good first task" issue to tackle.

**Comment by christopherdro** [comment]
@jedlau Care to give this a shot?

**Comment by joshuagutierrez** [comment]
Should this issue be closed now?

**Comment by jedlau** [comment]
Yes, closing.
