### ISSUE TITLE
Dynamic sticky headers crash natively (Android only)

### ISSUE THREAD

**Issue by yairopro** [facebook/react-native#25157]
**The FlatList crash natively when updating the `stickyHeaderIndices` prop.**
The purpose of my component is to fetch items, and display them inside a flatlist. Some of the loaded items need to be sticky. It's possible to know which ones only once they are loaded.
The problem is that it crashes when `stickyHeaderIndices` is updated at the same render the new data is added to the flatlist.

[See screenshot](https://user-images.githubusercontent.com/8110568/58966655-59fe8f80-87bb-11e9-96c0-d04f4c2d863d.png)

Demo: https://snack.expo.io/SkfE8USRN

React Native version:
````
React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 410.81 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
      Yarn: 1.16.0 - ~/.nvm/versions/node/v10.13.0/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.13.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.2, 26.0.2, 26.0.3, 27.0.0, 27.0.3, 28.0.2, 28.0.3
        System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.6 => 16.8.6 
      react-native: ^0.59.8 => 0.59.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1
````
## Steps To Reproduce

1. Render a flat list with empty data array.
2. Load your datas (or wait some seconds), and update your array state with the items you loaded.
3. Compute headers indices for chosen items.

Describe what you expected to happen: 
No crash.

**Comment by changLiuUNSW** [comment]
I have the same issue after upgrade to RN 59

**Comment by yairopro** [comment]
@changLiuUNSW The problem wasn't in a previous version ? Do you know since version it appeared ?

**Comment by changLiuUNSW** [comment]
@yairopro I may only know which version is working fine, because the issue happened after upgrade from Expo 32 to Expo 33. Expo 32 is based on RN0.57.1.
So it works fine in RN0.57 and break in RN0.59

**Comment by changLiuUNSW** [comment]
I just did some research, I believe the stickyHeaderIndices is totally not working for FlatList in Android. You can simply reproduce by creating a FlatList and set stickyHeaderIndices to any value

**Comment by yeswanth** [comment]
I was trying to debug this and here are my observations:
1) Issue was only reproducible only on Android phones and with RN version 0.59.* 
2) Tested on iOS with RN 0.59.9 and tested on Android with RN 0.58.* and the `ScrollView` stickyHeader works fine. 

Let me take a look into source of `RNAndroid` to find more on what could have caused it. 

For anyone else encountering this issue, they can avoid using RN 59, if it is possible.

**Comment by JohannesKlauss** [comment]
I can back up the observations @yeswanth did share.

**Comment by yeswanth** [comment]
I found a temporary fix for this problem. You can set [`removeClippedSubviews`](removeClippedSubviews) to `false` value and it should work properly.

**Comment by trucnd** [comment]
@yeswanth: I stuck on this bug for 2 weeks, you've saved my life!!! Thanks

**Comment by changLiuUNSW** [comment]
Thanks @yeswanth . Not sure why set removeClippedSubviews to false can fix this issue.

@trucnd do you find any performance issue when removeClippedSubviews to false?

**Comment by trucnd** [comment]
@changLiuUNSW, I don't see any performance issue still now, it looks faster on long FlatList.

**Comment by yeswanth** [comment]
@changLiuUNSW I should have mentioned it, you can set `removeClippedSubviews` to either `true` or `false` and this issue doesn't occur. I think the recommended value is `true` for Android platform (As commented [here](https://github.com/facebook/react-native/blob/942de5718236ddbd1a112a2ce7adf20591949672/Libraries/Lists/FlatList.js#L249))

**Comment by changLiuUNSW** [comment]
> you can set removeClippedSubviews to either true or false and this issue doesn't occur.

This is very strange, because the default value has been set to true already in this PR:
https://github.com/facebook/react-native/commit/1a499f43b2d03cc27dd6c25c8f13a767862afba1

**Comment by yeswanth** [comment]
If you look at `ScrollView` [code](https://github.com/facebook/react-native/blob/99ece27897f72263bfd1c657a46f626f5b203039/Libraries/Components/ScrollView/ScrollView.js#L1012)... You will see the following
```
const hasStickyHeaders =
      Array.isArray(stickyHeaderIndices) && stickyHeaderIndices.length > 0;

<ScrollView
 {...otherProps}           
  removeClippedSubviews={
          // Subview clipping causes issues with sticky headers on Android and
          // would be hard to fix properly in a performant way.
          Platform.OS === 'android' && hasStickyHeaders
            ? false
            : this.props.removeClippedSubviews
        }
/>
```

The problem (as I have observed) is occurring when `removeClippedSubviews` is determined by dynamic value of `hasStickyHeaders`, when it is not overridden by the prop set in the component `removeClippedSubviews`

I couldn't debug further beyond this as to why this is a problem. 

Do note that, in this example, value of `hasStickyHeaders` changes as the component loads 
1. When component is loading, there are no `stickyHeaderIndices` (as it is empty) `hasStickyHeaders` is set to `false`
2. When component is loaded, there are some `stickyHeaderIndices` and `hasStickyHeaders` is set to `true`
I believe it is the nature of dynamic `stickyHeaderIndices` in the component that is causing the crash. Hence, my workaround of overriding `removeClippedSubviews`(thereby keeping the value static) avoids the issue.

**Comment by changLiuUNSW** [comment]
@yeswanth I think you pretty much find the cause and can create a PR for them :)

**Comment by changLiuUNSW** [comment]
@yeswanth  Also I just tried set ```removeClippedSubviews``` to ```true```, the issue still exists. Have to set it to ```false```

**Comment by minhchienwikipedia** [comment]
Any solution for it? Because I don't want to set `removeClippedSubviews` to `false`.

**Comment by PavanKumar-sa** [comment]
Facing same issue after upgrading to react native **0.60.3**. App works fine on iOS but **crashes on android** when having **huge data** in **flatlist**. 

 @yeswanth Thank you for the workaround. its working !!!

https://facebook.github.io/react-native/docs/flatlist#removeclippedsubviews
But documentation states both saying "use for scroll performance" and at same time has a note stating "use at your own risk"

Any other solution ? considering performance.

**Comment by Bardiamist** [comment]
Faced with this.

**Comment by changLiuUNSW** [comment]
It is still not working

**Comment by Yassiremt** [comment]
> 
> 
> I found a temporary workaround for this issue. You can set [`removeClippedSubviews`](removeClippedSubviews) to `false` and it should work as intended.

Maaaan Thaanks

**Comment by yairopro** [comment]
no stale

**Comment by yairopro** [comment]
no stale

**Comment by whalemare** [comment]
Still reproduced

**Comment by Bardiamist** [comment]
Still actual

**Comment by matapo** [comment]
still an issue, however, setting removeClippedSubviews={false} helped as a hotfix

**Comment by ameenmattar** [comment]
still facing same issue

**Comment by debabrata100** [comment]
Worked for me!
I made the list render when stickyHeaderIndices.length > 0

**Comment by SundyGuo** [comment]
still facing same issue

**Comment by marsk6** [comment]
Strangely, it works when I set `removeClippedSubviews` to `true`

**Comment by evgeniy-skakun** [comment]
still facing same issue

**Comment by deflexable** [comment]
please any fix for this aside from setting removeClippedSubviews={false}

this issue has be open 3 years ago and still no fix for it

**Comment by VictorioMolina** [comment]
Same problem here

**Comment by vetal04075** [comment]
removeClippedSubviews={false} doesn't work for me. But I found another workaround that works well for me.
You can try mutate state of stickyHeaderIndices and update data list. This implementation allows you to rerender the list and at the same time simulate a dynamic sticky header in fact having it static, thanks to which the desired result is achieved without crashing the app.
Here is an example:
```
  const [listData, setListData] = useState([])
  const [stickyHeaderIndex] = useState([0])

  const updateList = (updatedList, stickyIndex) => {
    setListData(updatedList)

    // Here's a workaround
    // mutate state instead setStickyHeaderIndex(stickyIndex)
    stickyHeaderIndex[0] = stickyIndex
  }

  return (
    <FlatList
      data={listData}
      keyExtractor={item => item.name}
      stickyHeaderIndices={stickyHeaderIndex}
      renderItem={({item, index}) => this.renderItem(item, index)}
    />
  )
```

**Comment by bryanltobing** [comment]
not sure why this issue get closed, when the issue still exist

**Comment by dkulakov** [comment]
Face this issue on Android 13 using `"react-native": "0.73.6"`

**Comment by ChromeQ** [comment]
> removeClippedSubviews={false} doesn't work for me. But I found another workaround that works well for me. You can try mutate state of stickyHeaderIndices and update data list. This implementation allows you to rerender the list and at the same time simulate a dynamic sticky header in fact having it static, thanks to which the desired result is achieved without crashing the app. Here is an example:
> 
> ```
>   const [listData, setListData] = useState([])
>   const [stickyHeaderIndex] = useState([0])
> 
>   const updateList = (updatedList, stickyIndex) => {
>     setListData(updatedList)
> 
>     // Here's a workaround
>     // mutate state instead setStickyHeaderIndex(stickyIndex)
>     stickyHeaderIndex[0] = stickyIndex
>   }
> 
>   return (
>     <FlatList
>       data={listData}
>       keyExtractor={item => item.name}
>       stickyHeaderIndices={stickyHeaderIndex}
>       renderItem={({item, index}) => this.renderItem(item, index)}
>     />
>   )
> ```

Can't try this as in my case I want multiple sticky indices, so setting the `stickyHeaderIndex[0] = stickyIndex` will only replace the first, and I can't always know there will be a set number, depends on the data.

**Comment by JuanRdBO** [comment]
bumo

**Comment by bwesen** [comment]
I'm unsure if this is the same bug but I just tried to add stickyHeaderIndices{} to a very simple FlatList on Android and it immediately starts crashing, with the red bar with index=<something> count=<something>, addInArray etc. I have verified the indices and they match the array sent into the data prop, everything is fine. It doesn't work even if I set a permanent [ 0 ].

It crashes when one of the indices that are supposed to be sticky comes near the view.

```
    console.log('FlatList with ' + timelineDateIndices.length + ' sticky indices and ' + timelineData.length + ' timeline items');
    
    return (<FlatList
	    data={ timelineData }
	    stickyHeaderIndices={ timelineDateIndices }
	    renderItem={ renderTimelineItem }
	    keyExtractor={ (item, index) => item.uuid }
            />);
```

So one thing that might be related is that while the timeline is loading from a SQLite db I have, both the timelineData and timelineDateIndices arrays will have 0 length and pass by here. Then when it's loaded, both will have > 0 length *at the same time* so there is no <FlatList> render with for example only the sticky array > 0 and the data length 0.

```
 (NOBRIDGE) LOG  Database setup completed successfully.
 (NOBRIDGE) LOG  FlatList with 0 sticky indices and 0 timeline items
 (NOBRIDGE) LOG  Done loading timeline from DB, updating timelinedata
 (NOBRIDGE) LOG  FlatList with 85 sticky indices and 400 timeline items
````

react version 0.76.6
Android Emulator API 35

**Comment by hassanAwanAlvi** [comment]
Faced the issue on react-native 0.80.1. This took my entire day to figure out why is this not working on android and why is it working on IOS. 
This issue should be fixed

**Comment by NickButnar** [comment]
This issue affects “react-native” version “0.83.6”, and the fix using `removeClippedSubviews={false}` works
