### ISSUE TITLE
scrollview does not work on android

### ISSUE THREAD

**Issue by craigcosmo** [facebook/react-native#25168]
React Native version:

  React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (12) x64 Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz
      Memory: 586.93 MB / 24.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.6.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 28
        Build Tools: 28.0.3
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Steps To Reproduce

just run those code

```js

import React from 'react';
import {
	ScrollView,
	StyleSheet,
	Text,
	View,
} from 'react-native';
export default class HomeScreen extends React.Component {
	render() {
		return (		
			<ScrollView style={css.outside} contentContainerStyle={css.contentContainer}>
				<Text>some text</Text>
				<Text>some text</Text>
				<Text>some text</Text>
				<Text>some text</Text>
				<Text>some text</Text>
				<Text>some text</Text>
				<Text>some text</Text>
				<Text>some text</Text>
				<Text>some text</Text>
				<Text>some text</Text>
				<Text>some text</Text>
				<Text>some text</Text>
				<Text>some text</Text>
			</ScrollView>		
		)
	}	
}
 
const css = StyleSheet.create({
	outside :{

		flex:1,
	},
	contentContainer: {
		paddingTop: 30,
	},
});

```
Describe what you expected to happen:

when scroll it should scroll on both ios and android

Snack, code example, or link to a repository:

https://snack.expo.io/@cosmo/simple-scroll

**Comment by Kida007** [comment]
As I can see, the Total Content Height inside ScrollView  is not large enough . Therefore there is nothing to scroll . Try adding more Text Components (4 times the current) in your example .

Should be Closed !
