### ISSUE TITLE
oppo手机android版本6.0或者以下 textinput键盘显示问题

### ISSUE THREAD

**Issue by bojianyin** [facebook/react-native#25163]
rn版本:0.57.X||最新版本
机型：oppo
android version:<=6.0
问题定位：textInput
先从一个页面打开有input 然后点击跳转至第二个页面这个页面也有input  然后再返回来 第一个页面的input点了之后手机键盘就弹不出来了 ，亲测有效 问题绝对存在，最新版的rn目录问题仍旧存在，还望大佬关注修复下这个问题 谢谢大佬了!

**Comment by bojianyin** [comment]
我认为我的描述已经很明确了 还麻烦大佬帮忙看看吧 问题复现率：100%

**Comment by zhongwuzw** [comment]
@bojianyin Hi :) please translate your descriptions to English, and fill in the template issue.

**Comment by bojianyin** [comment]
> @bojianyin Hi :) please translate your descriptions to English, and fill in the template issue.

RN version: 0.57.X | | latest version

Model: oppo

Android version:<=6.0

Problem Location: TextInput

Input is opened from a page and then clicked to jump to the second page. Input is also on this page and then returned to the input point of the first page. After that, the keyboard of the mobile phone will not pop up. There is absolutely a problem of the validity of personal testing. The problem of the latest version of the RN directory still exists. Thank you, sir.

**Comment by bojianyin** [comment]
I think my description is very clear and I'd like to ask the big guys to help me see the problem recurrence rate: 100%.

**Comment by bojianyin** [comment]
问题并没有解决 为什么关闭？

**Comment by bojianyin** [comment]
oppo存在的软键盘问题不解决了吗这是？为什么关闭我的问题，问题绝对存在  能不能正确面对一下------------------ 原始邮件 ------------------
发件人: "Bot"<notifications@github.com>
发送时间: 2019年6月8日(星期六) 中午12:48
收件人: "facebook/react-native"<react-native@noreply.github.com>;
抄送: "bojianyin"<2316744840@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [facebook/react-native] oppo手机android版本6.0或者以下 textinput键盘显示问题 (#25163)



Closed #25163.
 
&mdash;

**Comment by Lylleny** [comment]
same with oppo phone
