### ISSUE TITLE
main.jsbundle doesn't create in the release mode.

### ISSUE THREAD

**Issue by kiritm-nimblechapps** [facebook/react-native#25172]
Hi,

I have react native app and run with debug mode. it's working fine. 

But when I run app in release mode or create archive for build, There is an issue of main.jsbundle. There is not automatically creating the file main main.jsbundle,

I don't want to create  main.jsbundle using command.

```
/Library/Developer/Xcode/DerivedData/Champions-grhmsnmvoqiloadrqohbojayrslc/Build/Products/Release-iphoneos/Champions.app/main.jsbundle --assets-dest /Users//Library/Developer/Xcode/DerivedData/Champions-grhmsnmvoqiloadrqohbojayrslc/Build/Products/Release-iphoneos/Champions.app
warning: the transform cache was reset.
(node:44779) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): SyntaxError: Unexpected token )
(node:44779) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:44779) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): SyntaxError: Unexpected token )
error Unexpected token ). Run CLI with --verbose flag for more details.
+ [[ false != true ]]
+ [[ ! -f /Users//Library/Developer/Xcode/DerivedData/-grhmsnmvoqiloadrqohbojayrslc/Build/Products/Release-iphoneos/.app/main.jsbundle ]]
+ echo 'error: File /Users//Library/Developer/Xcode/DerivedData/-grhmsnmvoqiloadrqohbojayrslc/Build/Products/Release-iphoneos/.app/main.jsbundle does not exist. This must be a bug with'
error: File /Users/
```

**The same react native project run to my friend mac, There is automatically creating main.jsbundle file inside the DerivedData which is check. Also run release and archive.**

Can you help me where is problem.

**Comment by esutton** [comment]
@kiritnim my release builds fail on my build server macOs 10.13.6

Release builds work fine on my dev machine and a second machine I setup running Mojave macOS 10.14.5

Same versions of xcode, yarn, node, watchman, react-native-cli.
````
node: 10.15.1
react-native-cli: 2.0.1
react-native: 0.59.9
yarn: 1.16.0
````

I am running out of things to check?

````
warning: the transform cache was reset.
(node:81327) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): SyntaxError: Unexpected token )
(node:81327) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:81327) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): SyntaxError: Unexpected token )
error Unexpected token ). Run CLI with --verbose flag for more details.
+ [[ false != true ]]
````

**Comment by mayurssoni2456** [comment]
@esutton I am facing the same error - were you able to fix this?

**Comment by kiritnim** [comment]
There is system issue after update xcode and system, There is not created main.jsbundle file inside the release folder in derived data, So it's happen.

You are remove Xcode and again Installed. May be Work. 

Last time I have format Mac and installed so now the problem gone.

You can release build on other Mac, it's work if there is generate main.jsbundle.

Thanks.

**Comment by kiritnim** [comment]
> @esutton I am facing the same error - were you able to fix this?

There is system issue after update xcode and system, There is not created main.jsbundle file inside the release folder in derived data, So it's happen.

You are remove Xcode and again Installed. May be Work.

Last time I have format Mac and installed so now the problem gone.

You can release build on other Mac, it's work if there is generate main.jsbundle.

Thanks.

**Comment by mayurssoni2456** [comment]
Thanks for reply. Thats helps.
Will reinstall xcode

**Comment by esutton** [comment]
@mayurssoni2456 I forget what solved the issue.  With react native there are so many issues to solve.

I ** *think* ** I solved it by commenting-out a blacklist resolver in metro.config.js ( formerly rn-cli.config.js).  I do not remember what the original problem the blacklist was meant to solve.

````
/**
 * Metro configuration for React Native
 * https://github.com/facebook/react-native
 *
 * @format
 */

const blacklist = require('metro-config/src/defaults/blacklist');

module.exports = {
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: false,
      },
    }),
  },

  // resolver: {
  //   blacklistRE: blacklist([
  //     /nodejs-assets\/.*/,
  //     /android\/.*/,
  //     /ios\/.*/,
  //   ]),
  // },

};
````

**Comment by kirti00sharma** [comment]
@mayurssoni2456 Where you able to resolve the issue. Facing the same issue.
@esutton Not having blacklist in my metro.config.js
