### ISSUE TITLE
App crashes only on iOS release build

### ISSUE THREAD

**Issue by iAmShakil** [facebook/react-native#25177]
Our App works fine on iOS debug mode, but when we make a release build or an IPA file, it crashes right after showing the splash screen. We have tried the commonly suggested removing 'View.propTypes' code, but that did not work. 

This is our Podfile:
<pre>
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'demoapp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
 

  # Pods for demoapp

  pod 'Firebase/Core'
  pod 'FBSDKCoreKit', '4.38'
  pod 'FBSDKLoginKit', '4.38'
  pod 'FBSDKShareKit', '4.38'

  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga/'
  pod 'React', path: '../node_modules/react-native/', :subspecs => [
    'Core',
    'ART',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTLinkingIOS',
    'RCTGeolocation',
    'RCTImage',
    'RCTNetwork',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'DevSupport',
    'CxxBridge',
    ]

  pod 'RNFileViewer', :path => '../node_modules/react-native-file-viewer/ios'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'RNCharts', :path => '../node_modules/react-native-charts-wrapper'
  pod 'SwiftyJSON', '4.0'

  pod 'react-native-async-storage', :path => '../node_modules/@react-native-community/async-storage'

  pre_install do |installer|
        installer.analysis_result.specifications.each do |s|
            s.swift_version = '4.2' unless s.swift_version
        end
  end

  target 'demoapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'demoapp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

end
</pre>
React Native version:  0.59.4 

React Native Environment Info:
System:
OS: macOS High Sierra 10.13.6
CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
Memory: 11.16 GB / 16.00 GB
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 8.11.1 - /usr/local/bin/node
npm: 5.6.0 - /usr/local/bin/npm
SDKs:
iOS SDK:
Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
IDEs:
Xcode: 10.1/10B61 - /usr/bin/xcodebuild
npmPackages:
react: 16.8.3 => 16.8.3 
react-native: 0.59.4 => 0.59.4 
npmGlobalPackages:
react-native-cli: 2.0.1

## Steps To Reproduce

1.
2.

Describe what you expected to happen:
The app should open without crashing

# Below are the errors we get on the Xcode console when we try to launch the release build on simulator:
Jun  3 11:58:26 alans-ipad-air demoapp[11868] <Error>: objc[11868]: Class RCTSRWebSocket is implemented in both /Users/demouser/Library/Developer/CoreSimulator/Devices/D3B1AE11-0A56-4DD1-B66C-F4B92C36986C/data/Containers/Bundle/Application/9D4D1BDA-0901-4AF6-8CC9-2CB0C6BF0F99/demoapp.app/Frameworks/React.framework/React (0x10d5a2c38) and /Users/demouser/Library/Developer/CoreSimulator/Devices/D3B1AE11-0A56-4DD1-B66C-F4B92C36986C/data/Containers/Bundle/Application/9D4D1BDA-0901-4AF6-8CC9-2CB0C6BF0F99/demoapp.app/demoapp (0x10b6b2e60). One of the two will be used. Which one is undefined.
Jun  3 11:58:26 alans-ipad-air demoapp[11868] <Error>: objc[11868]: Class RCTSRIOConsumer is implemented in both /Users/demouser/Library/Developer/CoreSimulator/Devices/D3B1AE11-0A56-4DD1-B66C-F4B92C36986C/data/Containers/Bundle/Application/9D4D1BDA-0901-4AF6-8CC9-2CB0C6BF0F99/demoapp.app/Frameworks/React.framework/React (0x10d5a2cd8) and /Users/demouser/Library/Developer/CoreSimulator/Devices/D3B1AE11-0A56-4DD1-B66C-F4B92C36986C/data/Containers/Bundle/Application/9D4D1BDA-0901-4AF6-8CC9-2CB0C6BF0F99/demoapp.app/demoapp (0x10b6b2f00). One of the two will be used. Which one is undefined.
Jun  3 11:58:26 alans-ipad-air demoapp[11868] <Error>: objc[11868]: Class RCTSRIOConsumerPool is implemented in both /Users/demouser/Library/Developer/CoreSimulator/Devices/D3B1AE11-0A56-4DD1-B66C-F4B92C36986C/data/Containers/Bundle/Application/9D4D1BDA-0901-4AF6-8CC9-2CB0C6BF0F99/demoapp.app/Frameworks/React.framework/React (0x10d5a2c60) and /Users/demouser/Library/Developer/CoreSimulator/Devices/D3B1AE11-0A56-4DD1-B66C-F4B92C36986C/data/Containers/Bundle/Application/9D4D1BDA-0901-4AF6-8CC9-2CB0C6BF0F99/demoapp.app/demoapp (0x10b6b2e88). One of the two will be used. Which one is undefined.
Jun  3 11:58:26 alans-ipad-air demoapp[11868] <Error>: objc[11868]: Class _RCTSRRunLoopThread is implemented in both /Users/demouser/Library/Developer/CoreSimulator/Devices/D3B1AE11-0A56-4DD1-B66C-F4B92C36986C/data/Containers/Bundle/Application/9D4D1BDA-0901-4AF6-8CC9-2CB0C6BF0F99/demoapp.app/Frameworks/React.framework/React (0x10d5a2d28) and /Users/demouser/Library/Developer/CoreSimulator/Devices/D3B1AE11-0A56-4DD1-B66C-F4B92C36986C/data/Containers/Bundle/Application/9D4D1BDA-0901-4AF6-8CC9-2CB0C6BF0F99/demoapp.app/demoapp (0x10b6b2f50). One of the two will be used. Which one is undefined.
Jun  3 11:58:26 alans-ipad-air demoapp[11868] <Error>: objc[11868]: Class RCTWebSocketModule is implemented in both /Users/demouser/Library/Developer/CoreSimulator/Devices/D3B1AE11-0A56-4DD1-B66C-F4B92C36986C/data/Containers/Bundle/Application/9D4D1BDA-0901-4AF6-8CC9-2CB0C6BF0F99/demoapp.app/Frameworks/React.framework/React (0x10d5a37f0) and /Users/demouser/Library/Developer/CoreSimulator/Devices/D3B1AE11-0A56-4DD1-B66C-F4B92C36986C/data/Containers/Bundle/Application/9D4D1BDA-0901-4AF6-8CC9-2CB0C6BF0F99/demoapp.app/demoapp (0x10b6b2fc8). One of the two will be used. Which one is undefined.
Jun  3 11:58:26 alans-ipad-air com.apple.CoreSimulator.SimDevice.D3B1AE11-0A56-4DD1-B66C-F4B92C36986C[11758] (com.apple.AnnotationKit.MigratorService) <Warning>: Unknown key for Boolean: EnableTransactions
Jun  3 11:58:26 alans-ipad-air com.apple.CoreSimulator.SimDevice.D3B1AE11-0A56-4DD1-B66C-F4B92C36986C[11758] (com.apple.AnnotationKit.MigratorService) <Warning>: Unknown key for Boolean: EnablePressuredExit
Jun  3 11:58:26 alans-ipad-air com.apple.CoreSimulator.SimDevice.D3B1AE11-0A56-4DD1-B66C-F4B92C36986C[11758] (com.apple.AssetCacheLocatorService) <Warning>: Unknown key for Boolean: EnableTransactions
Jun  3 11:58:26 alans-ipad-air com.apple.CoreSimulator.SimDevice.D3B1AE11-0A56-4DD1-B66C-F4B92C36986C[11758] (com.apple.AssetCacheLocatorService) <Warning>: Unknown key for Boolean: EnablePressuredExit
Jun  3 11:58:26 alans-ipad-air com.apple.CoreSimulator.SimDevice.D3B1AE11-0A56-4DD1-B66C-F4B92C36986C[11758] (com.apple.CallKit.CallDirectory) <Warning>: Unknown key for Boolean: EnableTransactions
Jun  3 11:58:26 alans-ipad-air com.apple.CoreSimulator.SimDevice.D3B1AE11-0A56-4DD1-B66C-F4B92C36986C[11758] (com.apple.CallKit.CallDirectory) <Warning>: Unknown key for Boolean: EnablePressuredExit
Jun  3 11:58:26 alans-ipad-air com.apple.CoreSimulator.SimDevice.D3B1AE11-0A56-4DD1-B66C-F4B92C36986C[11758] (com.apple.CallKit.CallDirectoryMaintenance) <Warning>: Unknown key for Boolean: EnableTransactions
Jun  3 11:58:26 alans-ipad-air com.apple.CoreSimulator.SimDevice.D3B1AE11-0A56-4DD1-B66C-F4B92C36986C[11758] (com.apple.CallKit.CallDirectoryMaintenance) <Warning>: Unknown key for Boolean: EnablePressuredExit
Jun  3 11:58:26 alans-ipad-air com.apple.CoreSimulator.SimDevice.D3B1AE11-0A56-4DD1-B66C-F4B92C36986C[11758] (com.apple.MediaPlayer.RemotePlayerService) <Warning>: Unknown key for Boolean: EnableTransactions
Jun  3 11:58:26 alans-ipad-air com.apple.CoreSimulator.SimDevice.D3B1AE11-0A56-4DD1-B66C-F4B92C36986C[11758] (com.apple.MediaPlayer.RemotePlayerService) <Warning>: Unknown key for Boolean: EnablePressuredExit
Jun  3 11:58:26 alans-ipad-air com.apple.CoreSimulator.SimDevice.D3B1AE11-0A56-4DD1-B66C-F4B92C36986C[11758] (com.apple.Photos.CPLDiagnose) <Warning>: Unknown key for Boolean: EnableTransactions
Jun  3 11:58:26 alans-ipad-air com.apple.CoreSimulator.SimDevice.D3B1AE11-0A56-4DD1-B66C-F4B92C36986C[11758] (com.apple.Photos.CPLDiagnose) <Warning>: Unknown key for Boolean: EnablePressuredExit
Jun  3 11:58:26 alans-ipad-air com.apple.CoreSimulator.SimDevice.D3B1AE11-0A56-4DD1-B66C-F4B92C36986C[11758] (com.apple.Safari.History) <Warning>: Unknown key for Boolean: EnableTransactions
Jun  3 11:58:26 alans-ipad-air com.apple.CoreSimulator.SimDevice.D3B1AE11-0A56-4DD1-B66C-F4B92C36986C[11758] (com.apple.Safari.History) <Warning>: Unknown key for Boolean: EnablePressuredExit
Jun  3 11:58:26 alans-ipad-air com.apple.CoreSimulator.SimDevice.D3B1AE11-0A56-4DD1-B66C-F4B92C36986C[11758] (com.apple.Safari.ImageDecoder) <Warning>: Unknown key for Boolean: EnableTransactions
Jun  3 11:58:26 alans-ipad-air com.apple.CoreSimulator.SimDevice.D3B1AE11-0A56-4DD1-B66C-F4B92C36986C[11758] (com.apple.Safari.ImageDecoder) <Warning>: Unknown key for Boolean: EnablePressuredExit
Jun  3 11:58:26 alans-ipad-air com.apple.CoreSimulator.SimDevice.D3B1AE11-0A56-4DD1-B66C-F4B92C36986C[11758] (com.apple.SafariFoundation.AutoFillHelper) <Warning>: Unknown key for Boolean: EnableTransactions
Jun  3 11:58:26 alans-ipad-air com.apple.CoreSimulator.SimDevice.D3B1AE11-0A56-4DD1-B66C-F4B92C36986C[11758] (com.apple.SafariFoundation.AutoFillHelper) <Warning>: Unknown key for Boolean: EnablePressuredExit
Jun  3 11:58:26 alans-ipad-air com.apple.CoreSimulator.SimDevice.D3B1AE11-0A56-4DD1-B66C-F4B92C36986C[11758] (com.apple.SafariFoundation.CredentialProviderExtensionHelper) <Warning>: Unknown key for Boolean: EnableTransactions
Jun  3 11:58:26 alans-ipad-air com.apple.CoreSimulator.SimDevice.D3B1AE11-0A56-4DD1-B66C-F4B92C36986C[11758] (com.apple.SafariFoundation.CredentialProviderExtensionHelper) <Warning>: Unknown key for Boolean: EnablePressuredExit
Jun  3 11:58:26 alans-ipad-air com.apple.CoreSimulator.SimDevice.D3B1AE11-0A56-4DD1-B66C-F4B92C36986C[11758] (com.apple.SafariServices.ContentBlockerLoader) <Warning>: Unknown key for Boolean: EnableTransactions
Jun  3 11:58:26 alans-ipad-air com.apple.CoreSimulator.SimDevice.D3B1AE11-0A56-4DD1-B66C-F4B92C36986C[11758] (com.apple.SafariServices.ContentBlockerLoader) <Warning>: Unknown key for Boolean: EnablePressuredExit
Jun  3 11:58:26 alans-ipad-air com.apple.CoreSimulator.SimDevice.D3B1AE11-0A56-4DD1-B66C-F4B92C36986C[11758] (com.apple.StreamingUnzipService) <Warning>: Unknown key for Boolean: EnableTransactions
Jun  3 11:58:26 alans-ipad-air com.apple.CoreSimulator.SimDevice.D3B1AE11-0A56-4DD1-B66C-F4B92C36986C[11758] (com.apple.StreamingUnzipService) <Warning>: Unknown key for Boolean: EnablePressuredExit
Jun  3 11:58:26 alans-ipad-air com.apple.CoreSimulator.SimDevice.D3B1AE11-0A56-4DD1-B66C-F4B92C36986C[11758] (com.apple.WebKit.Networking) <Warning>: Unknown key for Boolean: EnableTransactions
Jun  3 11:58:26 alans-ipad-air com.apple.CoreSimulator.SimDevice.D3B1AE11-0A56-4DD1-B66C-F4B92C36986C[11758] (com.apple.WebKit.Networking) <Warning>: Unknown key for Boolean: EnablePressuredExit
Jun  3 11:58:26 alans-ipad-air com.apple.CoreSimulator.SimDevice.D3B1AE11-0A56-4DD1-B66C-F4B92C36986C[11758] (com.apple.WebKit.Storage) <Warning>: Unknown key for Boolean: EnableTransactions
Jun  3 11:58:26 alans-ipad-air com.apple.CoreSimulator.SimDevice.D3B1AE11-0A56-4DD1-B66C-F4B92C36986C[11758] (com.apple.WebKit.Storage) <Warning>: Unknown key for Boolean: EnablePressuredExit
Jun  3 11:58:26 alans-ipad-air com.apple.CoreSimulator.SimDevice.D3B1AE11-0A56-4DD1-B66C-F4B92C36986C[11758] (com.apple.WebKit.WebContent) <Warning>: Unknown key for Boolean: EnableTransactions
Jun  3 11:58:26 alans-ipad-air com.apple.CoreSimulator.SimDevice.D3B1AE11-0A56-4DD1-B66C-F4B92C36986C[11758] (com.apple.WebKit.WebContent) <Warning>: Unknown key for Boolean: EnablePressuredExit
Jun  3 11:58:26 alans-ipad-air com.apple.CoreSimulator.SimDevice.D3B1AE11-0A56-4DD1-B66C-F4B92C36986C[11758] (com.apple.avkit.SharedPreferences) <Warning>: Unknown key for Boolean: EnableTransactions
Jun  3 11:58:26 alans-ipad-air com.apple.CoreSimulator.SimDevice.D3B1AE11-0A56-4DD1-B66C-F4B92C36986C[11758] (com.apple.avkit.SharedPreferences) <Warning>: Unknown key for Boolean: EnablePressuredExit
Jun  3 11:58:26 alans-ipad-air com.apple.CoreSimulator.SimDevice.D3B1AE11-0A56-4DD1-B66C-F4B92C36986C[11758] (com.apple.backboard.display.archive) <Warning>: Unknown key for Boolean: EnableTransactions
Jun  3 11:58:26 alans-ipad-air com.apple.CoreSimulator.SimDevice.D3B1AE11-0A56-4DD1-B66C-F4B92C36986C[11758] (com.apple.backboard.display.archive) <Warning>: Unknown key for Boolean: EnablePressuredExit
Jun  3 11:58:26 alans-ipad-air com.apple.CoreSimulator.SimDevice.D3B1AE11-0A56-4DD1-B66C-F4B92C36986C[11758] (com.apple.ctcategories.service) <Warning>: Unknown key for Boolean: EnableTransactions
Jun  3 11:58:26 alans-ipad-air com.apple.CoreSimulator.SimDevice.D3B1AE11-0A56-4DD1-B66C-F4B92C36986C[11758] (com.apple.ctcategories.service) <Warning>: Unknown key for Boolean: EnablePressuredExit
Jun  3 11:58:26 alans-ipad-air com.apple.CoreSimulator.SimDevice.D3B1AE11-0A56-4DD1-B66C-F4B92C36986C[11758] (com.apple.imfoundation.IMRemoteURLConnectionAgent) <Warning>: Unknown key for Boolean: EnableTransactions
Jun  3 11:58:26 alans-ipad-air com.apple.CoreSimulator.SimDevice.D3B1AE11-0A56-4DD1-B66C-F4B92C36986C[11758] (com.apple.imfoundation.IMRemoteURLConnectionAgent) <Warning>: Unknown key for integer: _DirtyJetsamMemoryLimit
Jun  3 11:58:26 alans-ipad-air com.apple.CoreSimulator.SimDevice.D3B1AE11-0A56-4DD1-B66C-F4B92C36986C[11758] (com.apple.imfoundation.IMRemoteURLConnectionAgent) <Warning>: Unknown key for Boolean: EnablePressuredExit
Jun  3 11:58:26 alans-ipad-air com.apple.CoreSimulator.SimDevice.D3B1AE11-0A56-4DD1-B66C-F4B92C36986C[11758] (com.apple.intents.intents-helper) <Warning>: Unknown key for Boolean: EnableTransactions
Jun  3 11:58:26 alans-ipad-air com.apple.CoreSimulator.SimDevice.D3B1AE11-0A56-4DD1-B66C-F4B92C36986C[11758] (com.apple.intents.intents-helper) <Warning>: Unknown key for Boolean: EnablePressuredExit
Jun  3 11:58:26 alans-ipad-air com.apple.CoreSimulator.SimDevice.D3B1AE11-0A56-4DD1-B66C-F4B92C36986C[11758] (com.apple.uifoundation-bundle-helper) <Warning>: Unknown key for Boolean: EnableTransactions
Jun  3 11:58:26 alans-ipad-air com.apple.CoreSimulator.SimDevice.D3B1AE11-0A56-4DD1-B66C-F4B92C36986C[11758] (com.apple.uifoundation-bundle-helper) <Warning>: Unknown key for Boolean: EnablePressuredExit
Jun  3 11:58:26 alans-ipad-air demoapp[11868] <Error>: assertion failed: 17G65 16B91: libxpc.dylib + 79599 [F7D4B188-D5C2-3E5E-BB76

**Comment by NestedLooper** [comment]
@iAmShakil did you find a workaround for this? I'm having the same issue with react-native@0.64.4. It builds fine in debug but crashes right after the splash screen when set to release.

**Comment by yannickoo** [comment]
@NestedLooper I have also experienced this and in the end it was an CocoaPods issue, the fix was to remove duplicate frameworks in `OTHER_LDFLAGS` which lives in `ios/Pods/Target Support Files/Pods-XXX/Pods-XXX.debug.xcconfig` file.

It looks like that now:

``` 
OTHER_LDFLAGS = $(inherited) -framework "CocoaLumberjack" -framework "DoubleConversion" -framework "folly" -framework "glog" -framework "yoga"
```

**Comment by iAmShakil** [comment]
@NestedLooper a fix similar to @yannickoo's worked for me as well. I just removed the "-framework React" from release.xcconfig file. You can find it on XCode through yourprojectname>Pods>pods-projectname.release.xcconfig. It gets rewritten every time you install pods.

**Comment by M1seRy** [comment]
same issue here, everything works fine in simulator, but after export the ipa file the app crashes in real devices.

**Comment by sm2017** [comment]
I have same issue , but there is no  duplicate frameworks in ```OTHER_LDFLAGS```
