### ISSUE TITLE
[iOS] [ReactNative] React Native layout is inversed in an XCode project generated by Unity

### ISSUE THREAD

**Issue by yurykorzun** [facebook/react-native#25179]
# Report

XCode project that is exported with Unity >2017 breaks React Native rendering. It works as expected in an Android project and in an XCode project for a Simulator.  

I understand that this issue might be out of scope for React Native, but I would appreciate any clues or suggestions. There is something different in a particular XCode project that prevents Yoga from rendering correctly.

React Native version:
 ```
Unity 2019.1.4f1
React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
      Memory: 3.73 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.3.1 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 22, 23, 24, 25, 26, 27, 28
        Build Tools: 25.0.3, 26.0.2, 26.0.3, 27.0.3, 28.0.2, 28.0.3
        System Images: android-22 | Intel x86 Atom_64, android-23 | Intel x86 Atom_64, android-25 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom_64, android-26 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5014246
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.9 => 0.59.9 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

This is a simple React Native view that I am trying to render:
```js
  <View style={{flex: 1}}>
    <View style={{flex:0.3, justifyContent: 'center', alignItems: 'center', borderWidth: 2, borderColor: 'red'}}>
      <Text>Top</Text>
    </View>
    <View  style={{flex:1, justifyContent: 'center', alignItems: 'center', borderWidth: 2, borderColor: 'green'}}>
      <Text>Second</Text>
    </View>
    <View  style={{flex:1, justifyContent: 'center', alignItems: 'center', borderWidth: 2, borderColor: 'grey'}}>
      <Text>Thrid</Text>
    </View>
    <View  style={{flex:0.2, justifyContent: 'center', alignItems: 'center', borderWidth: 2, borderColor: 'blue'}}>
      <Text>Bottom</Text>
    </View>
  </View>)
```

Detailed description of this issue is here https://github.com/yurykorzun/unity-react-native-demo/blob/master/README.md

# Issues and Steps to Reproduce
1. Clone https://github.com/yurykorzun/unity-react-native-demo
2. Navigate to folder ReactNative
3. Run yarn install
4. Open XCode project iosUnity and run on a device

# Expected Behavior
Child views should render from top to bottom.

<div><img src="https://github.com/yurykorzun/unity-react-native-demo/blob/master/Screenshots/Screenshot_unity_ios_rn_simulator.png?raw=true" width="250"/></div>

# Actual Behavior
Child views are inversed. 

<div><img src="https://github.com/yurykorzun/unity-react-native-demo/blob/master/Screenshots/Screenshot_unity_ios_rn_device.png?raw=true" width="250"/></div>

# Link to Code
https://github.com/yurykorzun/unity-react-native-demo/tree/master/ReactNative/iosUnity

**Comment by yurykorzun** [comment]
Update: the issue is solved by moving React Native to an xcode .framework project and precompiling everything, instead of installing pods or referencing RN projects directly in a Unity project.

**Comment by ioslcf** [comment]
@yurykorzun Can you tell me the details
