### ISSUE TITLE
I can't search on documentation's page

### ISSUE THREAD

**Issue by hnrqsss** [facebook/react-native#25188]
On the react-native's page the input in right top of the page doesn't works.
[https://facebook.github.io/react-native/](https://facebook.github.io/react-native/)

React Native version: 0.59
Mac OS  10.14.5 Mojave

Before this bug when i'm  write something correponding with i wrote shows at the bottom of the input. Today nothing appears even when i press enter. 

## Steps To Reproduce

1. [bug's image](https://drive.google.com/file/d/1i3jLV8xZfsTwg4jXZszfIlbarGXpmOey/view)

**Comment by hramos** [comment]
Thanks for the report. Can you file the issue at https://github.com/facebook/react-native-website?
