### ISSUE TITLE
[iOS] RCTRootView.cancelTouches() does not immediately dispatch cancellation to JS

### ISSUE THREAD

**Issue by iain-merrick-fanduel** [facebook/react-native#25191]
The [`RCTRootView.cancelTouches()`](https://github.com/iain-merrick-fanduel/react-native/blob/2b262ec78b48a7aaa164125cadc4f0593b71fdf3/React/Base/RCTRootView.h#L129) function is provided to handle cases such as a React view embedded in a native `UIScrollView`, where React gestures should be cancelled during scrolling.

This correctly prevents in-flight React gestures from completing. However, it does not cancel in-flight gestures immediately (on the JS side, [`View.props.onResponderTerminate()`](https://facebook.github.io/react-native/docs/view#onresponderterminate) is not invoked immediately). The cancellation doesn't take effect until all touches have ended.

React Native version:

```
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
      Memory: 18.11 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.15.0 - ~/.nvm/versions/node/v8.15.0/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v8.15.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        Build Tools: 23.0.1, 26.0.3, 27.0.3, 28.0.1, 28.0.2, 28.0.3, 29.0.0
        API Levels: 21, 22, 23, 24, 25, 26, 27, 28
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react: ~5.0.0 => 5.0.11 
      @types/react: ^16.8.2 => 16.8.2 
      react: ^16.8.1 => 16.8.1 
      react-native: 0.59.0 => 0.59.0 
```

## Steps To Reproduce

1. Create a RN `View` with an `onResponderTerminate` callback.
2. Embed it in a native `UIScrollView`.
3. Add on `onScroll` delegate that calls `RCTRootView.cancelTouches()`.

Describe what you expected to happen:
- When not scrolling, the `View` should accept touches as normal.
- When scrolling, `onResponderTerminate` should be called immediately.

**Comment by shergin** [comment]
`RCTRootView.cancelTouches()` is deprecated.
See the PR for more details.

**Comment by iain-merrick-fanduel** [comment]
There's a comment on the declaration reading `This is a reason why this API may be soon removed in favor of a better solution.`

Is that intended to be the deprecation warning?
