### ISSUE TITLE
The keyPrefix reduxPersist: is already in use. Multiple clients cannot share the same keyPrefix. Provide a different keyPrefix in the offlineConfig object

### ISSUE THREAD

**Issue by prasanthyejje** [facebook/react-native#25198]
Hi All,
i'm not able to resolve this error. and i don't know the cause of the error also.
i'm not using reduxPersist in the application.

## Steps To Reproduce
I'm getting this issue when i run the app. directly it is appearing with out any action.

React Native version:   "react-native": "0.59.2",

This is error description what i'm getting:

handleException | @ | ReactNativeRenderer-dev.js:2290
-- | -- | --
  | handleError | @ | ReactNativeRenderer-dev.js:2204
  | reportFatalError | @ | error-guard.js:42
  | guardedLoadModule | @ | require.js:199
  | metroRequire | @ | require.js:125
  | (anonymous) | @ | taggedTemplateLiteralLoose.js:10
  | executeApplicationScript | @ | debuggerWorker.js:40
  | (anonymous) | @ | debuggerWorker.js:72

this is my complete package.json file.

{
  "name": "****************",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "@mapbox/polyline": "^1.0.0",
    "add": "^2.0.6",
    "amazon-cognito-identity-js": "^3.0.11",
    "apollo-boost": "^0.3.1",
    "aws-amplify": "^1.1.26",
    "aws-amplify-react-native": "^2.1.9",
    "aws-appsync": "^1.7.2",
    "axios": "^0.18.0",
    "geolib": "^2.0.24",
    "graphql": "^14.2.1",
    "graphql-tag": "^2.10.1",
    "moment": "^2.24.0",
    "react": "16.8.3",
    "react-apollo": "^2.5.4",
    "react-native": "0.59.2",
    "react-native-firebase": "^5.2.3",
    "react-native-geo-fencing": "^0.1.0",
    "react-native-gesture-handler": "^1.1.0",
    "react-native-location": "^2.2.0",
    "react-native-maps": "git://github.com/react-native-community/react-native-maps.git#master",
    "react-native-modal-datetime-picker": "^6.1.0",
    "react-native-paper": "^2.14.0",
    "react-native-picker-dropdown": "^0.1.2",
    "react-native-vector-icons": "^6.4.2",
    "react-navigation": "^3.5.1",
    "robust-point-in-polygon": "^1.0.3"
  },
  "devDependencies": {
    "@babel/core": "7.4.0",
    "@babel/runtime": "7.4.2",
    "babel-jest": "24.5.0",
    "jest": "24.5.0",
    "metro-react-native-babel-preset": "0.53.1",
    "react-test-renderer": "16.8.3",
    "react-native-autocomplete-input": "^3.6.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
Thanks in advance.

**Comment by hussain-t** [comment]
Hey dev,

I'm having the same issue after upgrading Expo SDK 33. However, I don't think it's related to Expo. 

<img width="358" alt="Screen Shot 2019-06-10 at 1 02 22 PM" src="https://user-images.githubusercontent.com/24408261/59183890-94d14080-8b8a-11e9-9392-efbbc5f09934.png">

**Comment by hussain-t** [comment]
Hey @prasanthyejje,

Locking the AWS packages version to a lower version number fixed it for me.

Versions were:
```"aws-amplify": "^1.1.19",
    "aws-amplify-react-native": "^2.1.8",
    "aws-appsync": "^1.7.2",
    "aws-appsync-react": "^1.2.7",
```

Downgraded to:
```"aws-amplify": "1.1.10",
    "aws-amplify-react-native": "^2.1.8",
    "aws-appsync": "1.7.1",
    "aws-appsync-react": "1.2.6",
```

You could also remove ^ and lock `aws-amplify-react-native`

I hope this helps :)

**Comment by prasanthyejje** [comment]
@hussain-t  thank you so much. its working.
