### ISSUE TITLE
Cannot measure nested Text component

### ISSUE THREAD

**Issue by KakarN** [facebook/react-native#25192]
## Description

I am trying to get the cursor/caret position of a TextInput, so that I can display a modal above the cursor/caret or below it, depending on the available space between 

1. The cursor and top screen, vs  
2. The cursor to the keyboard.

I have managed to work it out on a react web app from the [medium post](https://medium.com/@jh3y/how-to-where-s-the-caret-getting-the-xy-position-of-the-caret-a24ba372990a). So this is the basic concept:

1. Create a replica element of our TextInput with near identical styling.
2. Generate a substring of the TextInput text content up to the point of the caret.
3. Populate the replica element with that substring.
4. Append a span element that contains the rest of the content.

Since, in order to add a span element, I have to place a child Text component inside a parent Text component, and get the position of the child Text component when necessary.

**React Native version:**
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
      Memory: 796.68 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.1 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 26, 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Steps To Reproduce

1. Add a parent Text component (_parent ref) to the render method.
2. Place a nested child Text component (_child ref) inside the parent Text component.
3. Try to measure the `_child` ref component with the [measure method](https://facebook.github.io/react-native/docs/direct-manipulation#measurecallback).

## Describe what you expected to happen:

I expected to get the measurement details of the child/nested Text component (_child ref).

## Actual Behaviour

But instead, the all the returned properties of the child ref measurement are undefined.
Eg:
```
_parent position Object {
  "height": 61.5,
  "pageX": 0,
  "pageY": 24,
  "width": 360,
  "x": 0,
  "y": 0,
}
_child position Object {
  "height": undefined,
  "pageX": undefined,
  "pageY": undefined,
  "width": undefined,
  "x": undefined,
  "y": undefined,
}
```

Snack, code example, or link to a repository:

Link to [Snack](https://snack.expo.io/@kakarn/nested-text-measure).

**Comment by vonovak** [comment]
afaik, nesting <Text> into another <Text> will not create two Text nodes, but it will create just one, and if the nested text has some styling, it will be applied via NSAttributedString or Spans. Check out https://medium.com/@p9alisand/how-to-get-textinput-cursor-position-in-react-native-0-49-1845aee40e9b for answer to your question.
