### ISSUE TITLE
assetRoots is not being set properly

### ISSUE THREAD

**Issue by vishnevskiy** [facebook/react-native#252]
I might be doing something wrong.

But when I tried to include an image it doesn't find it so I looked through the code and the start command does not provide an assetRoots option to send to the packager and the packager defaults to

`options.assetRoots = [path.resolve(__dirname, '..')];`

Which basically makes it equal to the react-native node_module folder.

**Comment by frantic** [comment]
Looks like we need to do the same thing `projectRoots` does - detect if packager is running from node_modules of another project.

**Comment by amasad** [comment]
fixed in v0.2.1
