### ISSUE TITLE
NativeModules.RNDeviceInfo can not read deviceName correctly.

### ISSUE THREAD

**Issue by panda8z** [facebook/react-native#25209]
NativeModules.RNDeviceInfo can not read deviceName correctly.

In this picture, the **deviceName**   is "Unknown"
![image](https://user-images.githubusercontent.com/24646937/59193986-0eccee00-8bba-11e9-818d-a275886cbda6.png)

React Native version:

   React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
      Memory: 33.51 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28
        Build Tools: 19.1.0, 20.0.0, 21.1.2, 22.0.1, 23.0.1, 23.0.2, 23.0.3, 24.0.0, 24.0.1, 24.0.2, 24.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 27.0.0, 27.0.2, 27.0.3, 28.0.3
        System Images: android-28 | Intel x86 Atom_64, android-Q | Intel x86 Atom_64
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.5 => 0.59.5 
    npmGlobalPackages:
      react-native-cli: 2.1.9

## Steps To Reproduce

only print a  console of **NativeModules.RNDeviceInfo**.

**Comment by dulmandakh** [comment]
Please use https://github.com/react-native-community/react-native-device-info
