### ISSUE TITLE
Error on AnimatedValue.js file when it tries to call flush

### ISSUE THREAD

**Issue by iagormoraes** [facebook/react-native#25210]
The AnimatedValue.js throws an error on line `58` when `node.__getChildren().forEach(findAnimatedStyles);` is called on `_flush` function sometimes.

React Native version: 0.58.3

## Steps To Reproduce
1 - create variable with Animated.Value
2 - update the value

Describe what you expected to happen:
Animations work properly.

Snack, code example, or link to a repository:

The error happens in **node_modules/react-native/Libraries/Animated/src/nodes/AnimatedValue.js in findAnimatedStyles at line 58:28**:

```JS
function _flush(rootNode: AnimatedValue): void {
  const animatedStyles = new Set();
  function findAnimatedStyles(node) {
    /* $FlowFixMe(>=0.68.0 site=react_native_fb) This comment suppresses an
     * error found when Flow v0.68 was deployed. To see the error delete this
     * comment and run Flow. */
    if (typeof node.update === 'function') {
      animatedStyles.add(node);
    } else {
      node.__getChildren().forEach(findAnimatedStyles);
    }
  }
  findAnimatedStyles(rootNode);
  /* $FlowFixMe */
  animatedStyles.forEach(animatedStyle => animatedStyle.update());
}
```

Throws TypeError: ```s.__getChildren().forEach is not a function. (In 's.__getChildren().forEach(t)', 's.__getChildren().forEach' is undefined)```

Error screenshot:

<img width="1087" alt="Screen Shot 2019-06-10 at 09 21 26" src="https://user-images.githubusercontent.com/13892132/59195012-3348ac00-8b61-11e9-8d01-55c0221750ab.png">

**Comment by radik** [comment]
I have the same issue. I could not say exactly how to reproduce it. I got an issue report from Crashlytics. Some of my users faced it.
Android 7
Phone Samsung Galaxy S7 edge

**Comment by haorh** [comment]
Faced same issue with user of Samsung's Galaxy S7 SM-G930F. Reported by Bugsnag
React-native 0.59.9.
Unable to reproduce. Error occurred after Splash Activity.

**Comment by sam1463** [comment]
Also seeing this, occurring on Samsung SM-G930F on Android 7.0 on react-native 0.61.5
