### ISSUE TITLE
Compile error on Xcode 11 beta

### ISSUE THREAD

**Issue by RishabhTayal** [facebook/react-native#25214]
React Native version: 0.59.9

Describe what you expected to happen:

Expected the iOS project to compile without error. Getting compile time error with file `RCTWKWebView.h`.

**Screenshot**

![Screen Shot 2019-06-10 at 3 30 26 PM](https://user-images.githubusercontent.com/2100166/59224952-2e055480-8b95-11e9-90ca-8bdbe0184838.png)

Snack, code example, or link to a repository:

**Comment by chrisspankroy** [comment]
Can you post steps to reproduce this and post the output of `react-native info`?
