### ISSUE TITLE
Error while updating property 'pointerEvents' of a view managed by: RCTView

### ISSUE THREAD

**Issue by mykhailo-melnyk** [facebook/react-native#25237]
React Native version:
0.59.1

Application is working on iOS but have problem on Android.
I get error: 
Error while updating property 'pointerEvents' of a view managed by: RCTView
![Screenshot_20190612-153100_HelloGuest Staging](https://user-images.githubusercontent.com/14886932/59351658-95530e00-8d27-11e9-8c7e-f1d7f778d5d7.jpg)

Any suggestion why can it happens? I can't find any info 
thanks for help

**Comment by mykhailo-melnyk** [comment]
I updated project to RN 0.59.9 and error was gone.
Strange =)

any idea why can it happens?

**Comment by panwar67** [comment]
any update on this
