### ISSUE TITLE
react-native link does not add the dependencies from subspec to the xcode project for ios

### ISSUE THREAD

**Issue by sandsuma** [facebook/react-native#25230]
I have created a react-native native module ```RNSecureKeystoreWrapper``` ios which is dummy layer and dependent on another native module for ios ```secure-keystore``` which include RCT_EXPORT_MODULE() and export methods to be consumed by JS.
```secure-keystore``` generates a static lib ```libRNSecureKeystore.a``` which is linked to 
 ```RNSecureKeystoreWrapper```  through link libraries in Build phases. 
```libRNSecureKeystore.a``` are dependent on React-native libraries and actually importing ```RCTBridgeModule.h``` and exporting method using RCT_EXPORT_METHOD.

When I run react-native link for this project , it shows pbx project file is updated but it is unable to find React libraries from my static library ```libRNSecureKeystore.a``` linked to native module.

1. Proving the structure I used for my native module
sandhya$ tree react-sample/

react-sample/
├── secure-keystore
│   ├── Frameworks
│   │   ├── IBMMobileFirstPlatformFoundation.framework
│   │   │   ├── Headers
│   │   │   │   ├── AccessToken.h
│   │   │   │   ├── BaseChallengeHandler.h
│   │   │   │   ├── GatewayChallengeHandler.h
│   │   │   │   ├── IBMMobileFirstPlatformFoundation.h
│   │   │   │   ├── OCLogger+Constants.h
│   │   │   │   ├── OCLogger.h
│   │   │   │   ├── SecurityCheckChallengeHandler.h
│   │   │   │   ├── WLAFURLSessionManager.h
│   │   │   │   ├── WLAnalytics.h
│   │   │   │   ├── WLAuthorizationManager.h
│   │   │   │   ├── WLClient.h
│   │   │   │   ├── WLCookieExtractor.h
│   │   │   │   ├── WLDelegate.h
│   │   │   │   ├── WLDeviceAuthManager.h
│   │   │   │   ├── WLFailResponse.h
│   │   │   │   ├── WLProcedureInvocationData.h
│   │   │   │   ├── WLProcedureInvocationResult.h
│   │   │   │   ├── WLResourceRequest.h
│   │   │   │   ├── WLResponse.h
│   │   │   │   ├── WLResponseListener.h
│   │   │   │   ├── WLSecurityCommonUtils.h
│   │   │   │   ├── WLSecurityConstants.h
│   │   │   │   ├── WLSecurityUtils.h
│   │   │   │   └── WLSimpleDataSharing.h
│   │   │   ├── IBMMobileFirstPlatformFoundation
│   │   │   ├── Info.plist
│   │   │   └── Modules
│   │   │       └── module.modulemap
│   │   ├── include
│   │   │   ├── React
│   │   │   │   ├── RCTAccessibilityManager.h
│   │   │   │   ├── RCTActivityIndicatorView.h
│   │   │   │   ├── RCTActivityIndicatorViewManager.h
│   │   │   │   ├── RCTAlertManager.h
│   │   │   │   ├── RCTAnimationType.h
│   │   │   │   ├── RCTAppState.h
│   │   │   │   ├── RCTAssert.h
│   │   │   │   ├── RCTAsyncLocalStorage.h
│   │   │   │   ├── RCTAutoInsetsProtocol.h
│   │   │   │   ├── RCTBorderDrawing.h
│   │   │   │   ├── RCTBorderStyle.h
│   │   │   │   ├── RCTBridge+Private.h
│   │   │   │   ├── RCTBridge.h
│   │   │   │   ├── RCTBridgeDelegate.h
│   │   │   │   ├── RCTBridgeMethod.h
│   │   │   │   ├── RCTBridgeModule.h
│   │   │   │   ├── RCTBundleURLProvider.h
│   │   │   │   ├── RCTClipboard.h
│   │   │   │   ├── RCTComponent.h
│   │   │   │   ├── RCTComponentData.h
│   │   │   │   ├── RCTConvert+CoreLocation.h
│   │   │   │   ├── RCTConvert.h
│   │   │   │   ├── RCTDefines.h
│   │   │   │   ├── RCTDevLoadingView.h
│   │   │   │   ├── RCTDevMenu.h
│   │   │   │   ├── RCTDevSettings.h
│   │   │   │   ├── RCTDisplayLink.h
│   │   │   │   ├── RCTErrorCustomizer.h
│   │   │   │   ├── RCTErrorInfo.h
│   │   │   │   ├── RCTEventDispatcher.h
│   │   │   │   ├── RCTEventEmitter.h
│   │   │   │   ├── RCTExceptionsManager.h
│   │   │   │   ├── RCTFPSGraph.h
│   │   │   │   ├── RCTFont.h
│   │   │   │   ├── RCTFrameUpdate.h
│   │   │   │   ├── RCTI18nManager.h
│   │   │   │   ├── RCTI18nUtil.h
│   │   │   │   ├── RCTImageLoader.h
│   │   │   │   ├── RCTImageSource.h
│   │   │   │   ├── RCTImageStoreManager.h
│   │   │   │   ├── RCTInvalidating.h
│   │   │   │   ├── RCTJSCSamplingProfiler.h
│   │   │   │   ├── RCTJSStackFrame.h
│   │   │   │   ├── RCTJavaScriptExecutor.h
│   │   │   │   ├── RCTJavaScriptLoader.h
│   │   │   │   ├── RCTKeyCommands.h
│   │   │   │   ├── RCTKeyboardObserver.h
│   │   │   │   ├── RCTLayout.h
│   │   │   │   ├── RCTLayoutAnimation.h
│   │   │   │   ├── RCTLayoutAnimationGroup.h
│   │   │   │   ├── RCTLinkingManager.h
│   │   │   │   ├── RCTLog.h
│   │   │   │   ├── RCTMacros.h
│   │   │   │   ├── RCTModalHostView.h
│   │   │   │   ├── RCTModalHostViewController.h
│   │   │   │   ├── RCTModalHostViewManager.h
│   │   │   │   ├── RCTModuleData.h
│   │   │   │   ├── RCTModuleMethod.h
│   │   │   │   ├── RCTMultipartDataTask.h
│   │   │   │   ├── RCTMultipartStreamReader.h
│   │   │   │   ├── RCTNavItem.h
│   │   │   │   ├── RCTNavItemManager.h
│   │   │   │   ├── RCTNavigator.h
│   │   │   │   ├── RCTNavigatorManager.h
│   │   │   │   ├── RCTNetworkTask.h
│   │   │   │   ├── RCTNetworking.h
│   │   │   │   ├── RCTNullability.h
│   │   │   │   ├── RCTPackagerClient.h
│   │   │   │   ├── RCTParserUtils.h
│   │   │   │   ├── RCTPerformanceLogger.h
│   │   │   │   ├── RCTPicker.h
│   │   │   │   ├── RCTPickerManager.h
│   │   │   │   ├── RCTPlatform.h
│   │   │   │   ├── RCTPointerEvents.h
│   │   │   │   ├── RCTProfile.h
│   │   │   │   ├── RCTProgressViewManager.h
│   │   │   │   ├── RCTPushNotificationManager.h
│   │   │   │   ├── RCTRedBox.h
│   │   │   │   ├── RCTRefreshControl.h
│   │   │   │   ├── RCTRefreshControlManager.h
│   │   │   │   ├── RCTResizeMode.h
│   │   │   │   ├── RCTRootShadowView.h
│   │   │   │   ├── RCTRootView.h
│   │   │   │   ├── RCTRootViewDelegate.h
│   │   │   │   ├── RCTScrollContentView.h
│   │   │   │   ├── RCTScrollView.h
│   │   │   │   ├── RCTScrollViewManager.h
│   │   │   │   ├── RCTScrollableProtocol.h
│   │   │   │   ├── RCTSegmentedControl.h
│   │   │   │   ├── RCTSegmentedControlManager.h
│   │   │   │   ├── RCTShadowView+Layout.h
│   │   │   │   ├── RCTShadowView.h
│   │   │   │   ├── RCTSlider.h
│   │   │   │   ├── RCTSliderManager.h
│   │   │   │   ├── RCTSourceCode.h
│   │   │   │   ├── RCTStatusBarManager.h
│   │   │   │   ├── RCTSurface.h
│   │   │   │   ├── RCTSurfaceDelegate.h
│   │   │   │   ├── RCTSurfaceHostingView.h
│   │   │   │   ├── RCTSurfaceRootShadowView.h
│   │   │   │   ├── RCTSurfaceRootShadowViewDelegate.h
│   │   │   │   ├── RCTSurfaceRootView.h
│   │   │   │   ├── RCTSurfaceSizeMeasureMode.h
│   │   │   │   ├── RCTSurfaceStage.h
│   │   │   │   ├── RCTSurfaceView.h
│   │   │   │   ├── RCTSwitch.h
│   │   │   │   ├── RCTSwitchManager.h
│   │   │   │   ├── RCTTabBar.h
│   │   │   │   ├── RCTTabBarItem.h
│   │   │   │   ├── RCTTabBarItemManager.h
│   │   │   │   ├── RCTTabBarManager.h
│   │   │   │   ├── RCTTextDecorationLineType.h
│   │   │   │   ├── RCTTiming.h
│   │   │   │   ├── RCTTouchEvent.h
│   │   │   │   ├── RCTTouchHandler.h
│   │   │   │   ├── RCTUIManager.h
│   │   │   │   ├── RCTUIManagerObserverCoordinator.h
│   │   │   │   ├── RCTUIManagerUtils.h
│   │   │   │   ├── RCTURLRequestDelegate.h
│   │   │   │   ├── RCTURLRequestHandler.h
│   │   │   │   ├── RCTUtils.h
│   │   │   │   ├── RCTVersion.h
│   │   │   │   ├── RCTView.h
│   │   │   │   ├── RCTViewManager.h
│   │   │   │   ├── RCTWebSocketModule.h
│   │   │   │   ├── RCTWebView.h
│   │   │   │   ├── RCTWebViewManager.h
│   │   │   │   ├── RCTWrapperViewController.h
│   │   │   │   └── UIView+React.h
│   │   │   ├── cxxreact
│   │   │   │   ├── CxxModule.h
│   │   │   │   ├── CxxNativeModule.h
│   │   │   │   ├── Instance.h
│   │   │   │   ├── JSBigString.h
│   │   │   │   ├── JSBundleType.h
│   │   │   │   ├── JSCExecutor.h
│   │   │   │   ├── JSCLegacyTracing.h
│   │   │   │   ├── JSCMemory.h
│   │   │   │   ├── JSCNativeModules.h
│   │   │   │   ├── JSCPerfStats.h
│   │   │   │   ├── JSCSamplingProfiler.h
│   │   │   │   ├── JSCUtils.h
│   │   │   │   ├── JSExecutor.h
│   │   │   │   ├── JSIndexedRAMBundle.h
│   │   │   │   ├── JSModulesUnbundle.h
│   │   │   │   ├── JsArgumentHelpers-inl.h
│   │   │   │   ├── JsArgumentHelpers.h
│   │   │   │   ├── MessageQueueThread.h
│   │   │   │   ├── MethodCall.h
│   │   │   │   ├── ModuleRegistry.h
│   │   │   │   ├── NativeModule.h
│   │   │   │   ├── NativeToJsBridge.h
│   │   │   │   ├── Platform.h
│   │   │   │   ├── RAMBundleRegistry.h
│   │   │   │   ├── ReactMarker.h
│   │   │   │   ├── RecoverableError.h
│   │   │   │   ├── SampleCxxModule.h
│   │   │   │   └── SystraceSection.h
│   │   │   ├── double-conversion
│   │   │   │   ├── bignum-dtoa.h
│   │   │   │   ├── bignum.h
│   │   │   │   ├── cached-powers.h
│   │   │   │   ├── diy-fp.h
│   │   │   │   ├── double-conversion.h
│   │   │   │   ├── fast-dtoa.h
│   │   │   │   ├── fixed-dtoa.h
│   │   │   │   ├── ieee.h
│   │   │   │   ├── strtod.h
│   │   │   │   └── utils.h
│   │   │   ├── jschelpers
│   │   │   │   ├── JSCHelpers.h
│   │   │   │   ├── JSCWrapper.h
│   │   │   │   ├── JavaScriptCore.h
│   │   │   │   ├── Unicode.h
│   │   │   │   ├── Value.h
│   │   │   │   └── noncopyable.h
│   │   │   ├── jsinspector
│   │   │   │   └── InspectorInterfaces.h
│   │   │   ├── privatedata
│   │   │   │   └── PrivateDataBase.h
│   │   │   └── yoga
│   │   │       ├── YGEnums.h
│   │   │       ├── YGMacros.h
│   │   │       └── Yoga.h
│   │   ├── libReact.a
│   │   ├── libcxxreact.a
│   │   ├── libdouble-conversion.a
│   │   ├── libjschelpers.a
│   │   ├── libjsinspector.a
│   │   ├── libprivatedata.a
│   │   ├── libthird-party.a
│   │   └── libyoga.a
│   ├── RNSecureKeystore.h
│   ├── RNSecureKeystore.m
│   └── RNSecureKeystore.xcodeproj
│       ├── project.pbxproj
│       ├── project.xcworkspace
│       │   ├── contents.xcworkspacedata
│       │   ├── xcshareddata
│       │   │   └── IDEWorkspaceChecks.plist
│       │   └── xcuserdata
│       │       └── sandhya.xcuserdatad
│       │           └── UserInterfaceState.xcuserstate
│       └── xcuserdata
│           └── sandhya.xcuserdatad
│               └── xcschemes
│                   └── xcschememanagement.plist
└── secure-keystore-wrapper
    ├── README.md
    ├── RNSecureKeystoreWrapper.podspec
    ├── android
    │   ├── build.gradle
    │   └── src
    │       └── main
    │           ├── AndroidManifest.xml
    │           └── java
    │               └── com
    │                   └── shellmonger
    │                       └── reactnative
    │                           ├── RNSecureKeystoreWrapperModule.java
    │                           └── RNSecureKeystoreWrapperPackage.java
    ├── index.js
    ├── ios
    │   ├── RNSecureKeystoreWrapper.h
    │   ├── RNSecureKeystoreWrapper.m
    │   ├── RNSecureKeystoreWrapper.podspec
    │   ├── RNSecureKeystoreWrapper.xcodeproj
    │   │   ├── project.pbxproj
    │   │   ├── project.xcworkspace
    │   │   │   ├── contents.xcworkspacedata
    │   │   │   ├── xcshareddata
    │   │   │   │   └── IDEWorkspaceChecks.plist
    │   │   │   └── xcuserdata
    │   │   │       └── sandhya.xcuserdatad
    │   │   │           └── UserInterfaceState.xcuserstate
    │   │   └── xcuserdata
    │   │       └── sandhya.xcuserdatad
    │   │           └── xcschemes
    │   │               └── xcschememanagement.plist
    │   ├── RNSecureKeystoreWrapper.xcworkspace
    │   │   └── contents.xcworkspacedata
    │   ├── include
    │   │   └── RNSecureKeystore.h
    │   └── lib
    │       └── libRNSecureKeystore.a
    └── package.json

The reason of the above code structure  is that , we wanted to keep source ode of native module proprietary at present.

React Native version:
0.59.

## Steps To Reproduce
1. react-native init sample,
cd sample/
2. react-native install --save <path to my wrapper plugin>
3. react-native link secure-keystore-wrapper
4. react-native run ios

Throws error unable to find EvenEmitter ( which is part of react-native library)  from RNSecureKeystore.h .

Link to sample code
github.ibm.com:sandsuma/RNSecureKeystoreWrapper.git

My Podspec file looks like below
```Pod::Spec.new do |s|
  s.name         = "RNSecureKeystoreWrapper"
  s.version      = "1.0.0"
  s.summary      = "RNSecureKeystoreWrapper"
  s.description  = <<-DESC
                  RNSecureKeystoreWrapper
                   DESC
  s.homepage     = ""
  s.license      = "MIT"
  # s.license      = { :type => "MIT", :file => "FILE_LICENSE" }
  s.author             = { "author" => "author@domain.cn" }

  #s.source_files  = "RNSecureKeystoreWrapper/**/*.{h,m}"
  s.source        = { :git => 'git@github.ibm.com:sandsuma/RNSecureKeystoreWrapper.git' }
  s.source_files  = "ios/*.{h,m}"
  s.platform      = :ios, '9.0'

  s.requires_arc = true

  s.dependency      'React'
  s.dependency "IBMMobileFirstPlatformFoundation"

  s.subspec 'core' do |ss|
    ss.preserve_paths = 'ios/include/*.h'
    ss.vendored_libraries = 'ios/lib/libRNSecureKeystore.a'
  end
end ```

**Comment by sibelius** [comment]
did you figure it out?
