### ISSUE TITLE
App Icons getting blur when I installed the debug builds react native.(Android only)

### ISSUE THREAD

**Issue by harikrishna1213** [facebook/react-native#25232]
Hi All,
I am facing issue that when I am run my project in mobile with debug connection the app icons visible clearly. No issues in this case. But when I take debug build using ./gradlew assembleDebug after installing this apk into my mobile device the actual icons are not visible clearly. It getting blur. What is the issue here ?

Please help me on this ..
Thanks in advance.
React Native version: 0.56.0
 
## Steps To Reproduce

1.
2.

Describe what you expected to happen:

Snack, code example, or link to a repository:

**Comment by dulmandakh** [comment]
It's not really related to RN, but your Android setup. Please see https://developer.android.com/studio/write/image-asset-studio.
