### ISSUE TITLE
Module 'stream' does not exist in the Haste module map?

### ISSUE THREAD

**Issue by lelup** [facebook/react-native#25231]
This issue appear then I have updated on new react native version 0.59.9. How can I fix this issue? I stuck a day and can not find exact solution.
![Screen Shot 2019-06-12 at 1 19 11 PM](https://user-images.githubusercontent.com/19283388/59327911-28367d00-8d15-11e9-8b8d-7e1ca1cae2c9.png)
Infomation when I run react-native info:
 Binaries:
      Node: 11.4.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.2, 23.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.3, 27.0.3, 28.0.1, 28.0.3
        System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-25 | Intel x86 Atom_64, android-25 | Google APIs Intel x86 Atom, android-26 | Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom, android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.9 => 0.59.9 
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by lelup** [comment]
I fixed this issue by removed lib not use.

**Comment by mbrehme** [comment]
I have some kind of the same issue. Can you be more clear how you resolved this @lelup ?

Thanks :-)

**Comment by mohammedSlimani** [comment]
@mbrehme  If you have just installed a module and you are getting errors try and manually link this module.
