### ISSUE TITLE
[iOS] Render native component managed by Auto Layout on React Native

### ISSUE THREAD

**Issue by adrianha** [facebook/react-native#25234]
Hi,
I'm facing an issue when i tried to render iOS native component that managed by Auto Layout on React Native. What i want to achieve is we don't need to specify component size on RN side because its already defined using Auto Layout. But it seems there's conflict between Yoga and Auto Layout on layouting component. I also managed to render Android component on RN and its working fine using `LayoutShadowNode`.
It also introduce inconsistency when rendering the component like this:

<img src="https://user-images.githubusercontent.com/5382429/59335894-b0258280-8d27-11e9-94e5-14ac9e557781.gif" width="250" />

React Native version:
```
info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
      Memory: 995.57 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.15.2 - ~/.yarn/bin/yarn
      npm: 6.9.0 - ~/.config/yarn/global/node_modules/.bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.3, 28.0.2, 28.0.3
        System Images: android-21 | Google APIs ARM EABI v7a, android-21 | Google APIs Intel x86 Atom_64, android-24 | Google APIs ARM 64 v8a, android-24 | Google Play Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-P | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.9 => 0.59.9 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-create-library: 3.1.2
```

Describe what you expected to happen:
Native component that using Auto Layout should be rendered correctly on RN without specifying any size. It should be rendered like this:
<img src="https://user-images.githubusercontent.com/5382429/59336206-540f2e00-8d28-11e9-8182-33ce0fba997e.png"  width="250" />

Snack, code example, or link to a repository:
[Example without ShadowView](https://github.com/adrianha/RNRenderNativeComp/tree/new-al)

I also try to create custom `RCTShadowView` instance and invoke `setIntrinsicContentSize` method to re-measure layout. It solves the layout problem but still introduce inconsistency when rendering component.
[Example with ShadowView](https://github.com/adrianha/RNRenderNativeComp/tree/new-al-shadow-view)
Result:
<img src="https://user-images.githubusercontent.com/5382429/59336814-7b1a2f80-8d29-11e9-8b5d-e69e82d745b8.gif" width="250" />

**Comment by ferryhinardi** [comment]
Same issue... any idea?
