### ISSUE TITLE
can not open developer menu , iOS  

### ISSUE THREAD

**Issue by KingAmo** [facebook/react-native#25246]
cannot open developer menu in anyway，`react-native: 0.59.8`，i have `use_frameworks!` in Podfile, hardware keyboard is already connected, happens either in iOS simulator or device.( in android everything is fine )

React Native version:

- react native info
```
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (6) x64 Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
      Memory: 47.24 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.3.1 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 28
        Build Tools: 28.0.3
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.8 => 0.59.8
    npmGlobalPackages:
      react-native-cli: 2.0.1
```
- Podfile
```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactNativeAppDemo' do
  # Pods for ReactNativeAppDemo
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'Core',
  'CxxBridge',
  'DevSupport',
  'RCTText',
  'RCTNetwork',
  'RCTWebSocket',
  'RCTAnimation'
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  
  pod 'react-native-baidu-map', :podspec => '../node_modules/react-native-baidu-map/ios/react-native-baidu-map.podspec'
  
  pod 'AppCenter/Crashes', '~> 2.0.1'
  pod 'AppCenter/Analytics', '~> 2.0.1'
  pod 'AppCenterReactNativeShared', '~> 2.0.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  
  

  platform :ios, '9.0'
  target 'ReactNativeAppDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ReactNativeAppDemo-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReactNativeAppDemo-tvOS

  target 'ReactNativeAppDemo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

```
## Steps To Reproduce

1. install app in iOS simulator or device
2. `command + d` or `command + r` or shake device or `hardware -- shake gesture`

Describe what you expected to happen:

- the developer menu show up

**Comment by CatapultJesse** [comment]
Can you check you're scheme is running in Debug mode, if you're in Release mode you won't be able to access the dev menu

**Comment by KingAmo** [comment]
@CatapultJesse yes, I am sure it is in `debug` mode

**Comment by edward-101D** [comment]
I have the same issue, developer menu is not showing in iOS.

I can only fix it by removing `use_frameworks` in pods

**Comment by KingAmo** [comment]
> I have the same issue, developer menu is not showing in iOS.
> 
> I can only fix it by removing `use_frameworks` in pods

me too, i finally removed  `use_frameworks!` and the library that need `use_frameworks!`, then the developer menu come back

**Comment by dkfl1995** [comment]
@KingAmo 
and others!
Guys, its not good to fix dev menu accessibility this hardcore and unreliable way!
I anyway need to use_frameworks as so other ones need as! So please anyone help to decide how to fix this WITHOUT removing use_frameworks keyword from pods

**Comment by carmelocatalfamo** [comment]
Hi, same issue here

This is my Podfile, I'm sure app is running in **Debug** mode
```podfile
platform :ios, '9.0'

target 'easypol' do
  use_frameworks!

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    'RCTImage',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
  ]

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  
  # My dependencies
  pod 'Nexi_XPay', '1.1.6'
end
```

**Comment by yannicklaclau** [comment]
same problem here. podfile:

`# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'glimpsy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for glimpsy

  # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    # 'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
    'RCTImage',
  ]

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'
  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'
  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'

end

# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     if target.name == "React"
#       target.remove_from_project
#     end
#   end
# end`

**Comment by yannicklaclau** [comment]
sam problem here. code:

```
platform :ios, '9.0'

target 'testapp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for testapp
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    # 'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
    'RCTImage',
  ]

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'
  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'

end
```

**Comment by EskelCz** [comment]
I have similar issue, sometimes the menu won't open (on real device) when debugger is running. So I have no way to disable the debugger.

**Comment by andidev** [comment]
I had a similar issue though the shake gesture worked for me. Not sure this is the reason but it happened after upgrading xcode. And the reason seemed to be that the hardware keyboard was disconnected. When pressing SHIFT + COMMAND + K to connect the hardware keyboard the developer menu was reachable with COMMAND + D again.

or in menu:
![image](https://user-images.githubusercontent.com/571389/62301334-b5c25d80-b478-11e9-8c99-3d7055ba7c0c.png)

**Comment by PvanHengel** [comment]
Hi any update on this issue?

**Comment by lucianomlima** [comment]
How to reproduce:
1. `react-native init Example --version 0.59.8`
2. `cd Example/ios`
3. `pod init`
4. Change Podfile to the following:
```rb
platform :ios, '9.0'

target 'Example' do
  # I can't run with the following uncommented, get "ld: symbol(s) not found for architecture x86_64" error
  # use_frameworks!

  # Pods for Example
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTBlob',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

end
```
5. `pod install`
6. `cd ../ && react-native run-ios`

Dev menu shows with shake gesture but not with keyboard shortcut.

<details>
  <summary>react-native info</summary>
  <pre>
  React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
      Memory: 869.09 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.17.3 - ~/.nvm/versions/node/v10.15.3/bin/yarn
      npm: 6.11.2 - ~/.nvm/versions/node/v10.15.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
      Android SDK:
        API Levels: 25, 26, 27, 28
        Build Tools: 25.0.3, 26.0.3, 27.0.3, 28.0.3, 29.0.0
        System Images: android-25 | Google Play Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.8 => 0.59.8
    npmGlobalPackages:
      react-native-cli: 2.0.1
  </pre>
</details>

**Comment by filiptdz** [comment]
Selecting `Hardware > Keyboard > Send Keyboard Shortcuts to Device` fixed this issue for me

**Comment by idanhaviv** [comment]
XCode 11.2 has no Hardware menu item. anyone experiences that? 
![image](https://user-images.githubusercontent.com/8762573/73529931-33632800-4420-11ea-9d3e-e1ddf27ba092.png)

**Comment by gurol** [comment]
Control + Cmd + Z (Menu: `Device | Shake ^⌘Z`)

**Comment by lucasmatsui** [comment]
I fixed mine by clicking in **I/O > input** and **Send Keyboard input to Device**

**Comment by aforty** [comment]
> Control + Cmd + Z (Menu: `Device | Shake ^⌘Z`)

Jesus effing christ this took me way too long to find. It used to me Cmd+D on IOS was it not?! The devil in this whole thing is that Cmd+D still works sometimes and it's just so incredibly frustrating but Ctrl+Cmd+Z works every time. Thank you!

**Comment by JulesPatry** [comment]
> I had a similar issue though the shake gesture worked for me. Not sure this is the reason but it happened after upgrading xcode. And the reason seemed to be that the hardware keyboard was disconnected. When pressing SHIFT + COMMAND + K to connect the hardware keyboard the developer menu was reachable with COMMAND + D again.
> 
> or in menu:
> ![image](https://user-images.githubusercontent.com/571389/62301334-b5c25d80-b478-11e9-8c99-3d7055ba7c0c.png)

This resolved my issue.

**Comment by AlanSl** [comment]
> Can you check your scheme is running in Debug mode, if you're in Release mode you won't be able to access the dev menu

For anyone not sure how to check this: see https://stackoverflow.com/a/28059831 - as of xcode 12.4 go to **Product** > **Scheme** > **Edit Scheme**, then in the **Run** vertical tab, **Info** horizontal tab, check **Build configuration**

**Comment by KrisLau** [comment]
> Control + Cmd + Z (Menu: `Device | Shake ^⌘Z`)

This worked, I was trying to do `Cmd + D` before. Although weirdly enough I noticed that if I do a screenshot first using `Cmd + S`  then I can do `Cmd + D` after that to open the dev menu

**Comment by Dmitry1983** [comment]
Simulator => Device => Restart
