### ISSUE TITLE
[Touchable] All touchable components call onPress on render if rendered using a map loop

### ISSUE THREAD

**Issue by isair** [facebook/react-native#2524]
Sample app: https://rnplay.org/apps/0Mawew

Also, they seem to stop calling their onPress handlers after the initial call.

**Comment by ide** [comment]
You're calling `this.onTitlePress(title)` when rendering your components... Use a thunk like `() => this.onTitlePress(title)` instead.

**Comment by isair** [comment]
Thanks, my bad. Still getting used to JS.

**Comment by ide** [comment]
np :)
