### ISSUE TITLE
[Android] Text missing on Android Q

### ISSUE THREAD

**Issue by mbaaij** [facebook/react-native#25258]
For an article page we render multiple paragraphs as Text components. Only some paragraphs don't show the last line on Android Q. We couldn't find any logic in which case the paragraph will fail to render everything.

React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
      Memory: 3.45 GB / 32.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.13.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 21, 23, 25, 26, 27, 28
        Build Tools: 25.0.2, 27.0.3, 28.0.3
        System Images: android-23 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.9 => 0.59.9 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

## Steps To Reproduce

1. react-native init androidBug
2. Add script below to App.js
```import React, {Component} from 'react';
import {Platform, StyleSheet, Text, View, FlatList} from 'react-native';
import { LoremIpsum } from "lorem-ipsum";

const lorem = new LoremIpsum({
  sentencesPerParagraph: {
    max: 8,
    min: 4
  },
  wordsPerSentence: {
    max: 16,
    min: 4
  }
});

lorem.generateWords(1);
lorem.generateSentences(5);
lorem.generateParagraphs(7);

const instructions = Platform.select({
  ios: 'Press Cmd+R to reload,\n' + 'Cmd+D or shake for dev menu',
  android:
    'Double tap R on your keyboard to reload,\n' +
    'Shake or press menu button for dev menu',
});

type Props = {};
export default class App extends Component<Props> {
  render() {
    return (
      <View style={styles.container}>
        <FlatList
          data={[
            {key: lorem.generateParagraphs(7)},
            {key: lorem.generateParagraphs(7)},
            {key: lorem.generateParagraphs(7)},
            {key: lorem.generateParagraphs(7)},
            {key: lorem.generateParagraphs(7)},
            {key: lorem.generateParagraphs(7)},
            {key: lorem.generateParagraphs(7)},
            {key: lorem.generateParagraphs(7)},
            {key: lorem.generateParagraphs(7)},
            {key: lorem.generateParagraphs(7)},
            {key: lorem.generateParagraphs(7)},
            {key: lorem.generateParagraphs(7)},
            ]}
          renderItem={({item}) => {
            console.log(item.key);
           return <Text style={{marginBottom:50, fontSize:18}}>{item.key}</Text>}
          }
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
})
```
3. open Pixel_2_XL_API_29 in emulator
4. react-native run-android

I would expect to see all text rendered completely, but some are cut off at the end (see images).

<img width="420" alt="Screen Shot 2019-06-13 at 17 06 39" src="https://user-images.githubusercontent.com/975780/59444156-a2dac780-8dfd-11e9-8a6d-c0fb78293f57.png">

<img width="975" alt="Screen Shot 2019-06-13 at 15 43 01" src="https://user-images.githubusercontent.com/975780/59438681-42935800-8df4-11e9-9c43-13f1bdf066cb.png">

**Comment by seomaz** [comment]
Same here, only happens when use api 29 and android 9, with some device for example pixel 2 XL.

Pixel 2 XL with android 8.1 and api 27 works fine.

**Comment by tbress89** [comment]
Same issue here, it seems to be related to the default `textBreakStrategy` of a `TextView` that changed from `highQuality` into `simple` since Android Q.

In this screenshot I have Pixel 3, API 28 (Android O) on the left and Pixel 3, API 29 (Android Q) on the right, same textual input.
On the left the word "elektriciteitsfactuur" get's split while on the right that's not the case anymore, this causes an extra newline in the paragraph but the height measurement of the TextView seems to respond wrongly to this behaviour.

![Picture 30](https://user-images.githubusercontent.com/34320861/63942892-e349f900-ca6e-11e9-8cf1-12bf9029b298.jpg)

**Comment by enahum** [comment]
Same here for us

See screenshot: from left to right Oreo, Pie, Q and the three of them are rendering the same code

```js
import * as React from 'react';
import { Text, View, StyleSheet } from 'react-native';
import DeviceInfo from 'react-native-device-info';

export default class App extends React.Component {
    render() {
        return (
            <View style={styles.container}>
                <Text style={styles.paragraph}>
                    {`Android ${DeviceInfo.getAPILevel()}`}
                </Text>
                <View style={{marginRight: 10}}>
                    <Text style={styles.paragraph}>
                        {'aaa aaa aaaaa aaa aaa aaaaaaaa aaa aaa aaaa aa a aaaa-aaaaaa, aaa aaa aaaaaaa aaaaa aaaaa aaaaaaaa-aaaa-aaaa-aaaaaa, aaaaaaaa-aa-aaaaaaa-aaaaa-aa-aaa aaa. aaa aaaaa. aaa aaaaa aaaaaaa a aaa\'a aaaa aa aaaaaaaaaaaa aaaa.'}
                    </Text>
                </View>
            </View>
        );
    }
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        paddingTop: 20,
        backgroundColor: '#ecf0f1',
        padding: 8,
    },
    paragraph: {
        fontSize: 15,
        textAlign: 'center',
    },
});
```

![image](https://community-daily.mattermost.com/files/reqqkutogi89xnzq3uzfeisy8h/public?h=xTrtpryj1pzONjY2lAgy9Bw_YtppveBPVZSX7o8Ag6Y)

**Comment by christianbach** [comment]
@enahum @tbress89 setting the `textBreakStrategy` prop for Text to `simple` solves the problem for us on Android 10

**Comment by ripzery** [comment]
> @enahum @tbress89 setting the `textBreakStrategy` prop for Text to `simple` solves the problem for us on Android 10

This works for me

**Comment by seomaz** [comment]
> @enahum @tbress89 setting the `textBreakStrategy` prop for Text to `simple` solves the problem for us on Android 10

how to use with react-native-render-html: [https://github.com/archriss/react-native-render-html](url)

**Comment by anirudh-eka** [comment]
> Same here, only happens when use api 29 and android 9+ (Q), with some device for example pixel 2 XL.
> 
> Pixel 2 XL with android 8.1 and api 27 works fine.

What we've noticed is the words get cut off on a Pixel 2 android 10 device, but not on the emulator. Even with the text-break set to simple. Has anyone else seen this?

**Comment by lvanhala** [comment]
We have the same problem. Does anybody know if this has been fixed in the latest react native version?

**Comment by abelyeupear** [comment]
Same issue. Is this a breaking change in Android 10? I cannot see anything related to this change on the release notes: https://source.android.com/setup/start/android-10-release

**Comment by duchuecntt** [comment]
> > @enahum @tbress89 setting the `textBreakStrategy` prop for Text to `simple` solves the problem for us on Android 10
> 
> how to use with react-native-render-html: [https://github.com/archriss/react-native-render-html](url)??

You go to 'node_modules/react-native-render-html/src/HTML.js' then edit this file.

Change

```
if (Wrapper === Text) {
  renderersProps.allowFontScaling = allowFontScaling;
  renderersProps.selectable = textSelectable;
}
```
To
```
if (Wrapper === Text) {
  renderersProps.allowFontScaling = allowFontScaling;
  renderersProps.selectable = textSelectable;
  renderersProps.textBreakStrategy = "simple"; // Add this line
}
```
You should request to owner of this react-native-render-html to make a pull request

**Comment by jjhampton** [comment]
Any updates on this? It would be useful if there was a solution within React Native (or a way to patch RN), so that developers wouldn't have to manually set every single `<Text>` component to have the prop `textBreakStrategy={'simple'}` .

**Comment by MoOx** [comment]
Doc is saying it's `highQuality` https://reactnative.dev/docs/text#textbreakstrategy

**Comment by fachryansyah** [comment]
same problem here.. i don't know why if i wrote some text, it will be missing 1 word, if i type "New Series" the word "Series" is wil be gone, i've tried with `textBreakStrategy`
```
<View style={styles.left}>
    <Text style={styles.textSection} textBreakStrategy="simple">New Series</Text>
</View>
```
and the result is : 
![https://i.ibb.co/vLVfYXD/Screenshot-20201019-203600-1.jpg](https://i.ibb.co/vLVfYXD/Screenshot-20201019-203600-1.jpg)

is'nt working any more, but i've tried with `adjustsFontSizeToFit={true}` and `numberOfLines={1}` props :
```
<View style={styles.left}>
    <Text style={styles.textSection} numberOfLines={1} adjustsFontSizeToFit>New Series</Text>
</View>
```
result : 
![https://i.ibb.co/1fFm9J9/Screenshot-20201023-200231.jpg](https://i.ibb.co/1fFm9J9/Screenshot-20201023-200231.jpg)

its work perfectly, but i don't know is that best practice or not

**Comment by MoOx** [comment]
Is this somehow related to https://github.com/facebook/react-native/issues/25481 ?

**Comment by fabriziobertoglio1987** [comment]
unluckily can not reproduce in our latest master branch using example https://github.com/facebook/react-native/issues/25258#issuecomment-536457183

**<details><summary>CLICK TO OPEN TESTS RESULTS</summary>**
<p>

| **api 29** | 
|:-------------------------:|
| <img src="https://user-images.githubusercontent.com/24992535/107203238-7a083c80-69fb-11eb-8363-d4227ceb2e1f.png" width="300" height="" /> | 

</p>
</details>
