### ISSUE TITLE
error on release build "parsing google-services.json file"

### ISSUE THREAD

**Issue by rahultatvasoft** [facebook/react-native#25254]
@react-native-bot 
Issue:
> Task :app:processReleaseGoogleServices
Parsing json file: D:\Projects\wamp\www\Reactnative-projects\Hobiz\Hobiz_Git\android\app\google-services.json

> Task :app:mergeReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeReleaseResources'.
> java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: AAPT error: check logs for details

React Native version:
"react-native": "0.58.5"
"react-native-firebase": "^5.3.1",

Working with debug but gives error while creating release build

**Comment by rahultatvasoft** [comment]
@react-native-bot  thanks for the suggestion.

**Comment by tuskemx** [comment]
any solution?

**Comment by aperomingo** [comment]
+1 with your problem, the same @rahultatvasoft 
Did you find any solution?
