### ISSUE TITLE
Cannot find Info.plist under build/<appname>/Build/...

### ISSUE THREAD

**Issue by armaneker** [facebook/react-native#25259]
I upgraded my React-Native project from react-native 0.58.6 to 0.59.9 using rn-diff-purge. I encountered a lot of problems and solved all except one. The project builds successfully in XCode 10.2.1 and runs on iPhone X simulator. When I run react-native run-ios it builds successfully BUT doesn't run on simulator becuase it indicates that it can't find Info.plist under build/appname/Build/... .

Info.plist DOES exist under build/Build/... but somehow it searches it under the wrong folder.

I manually copied the 'Build' folder under 'build/appname/' and the app started to run on the simulator without any problem.

But I don't think copying these files manually is a correct solution so I want to understand why my project is checking the wrong folder and how can I fix this.

React Native version: 0.59.9

**Comment by zhongwuzw** [comment]
@armaneker Thanks for reports. I met this before and also can reproduce 100%.
Can you try to add these lines like below in cli package? I'll make a PR to cli.
![image](https://user-images.githubusercontent.com/5061845/59481895-da4a8200-8e98-11e9-8713-45e8e54b2096.png)

![image](https://user-images.githubusercontent.com/5061845/59481968-4af19e80-8e99-11e9-8dfa-dc13f571ab0d.png)

**Comment by armaneker** [comment]
Thanks @zhongwuzw !

This worked after I replaced 'DerivedData' with 'build'.
