### ISSUE TITLE
TextInput focused but not visible on keyboard change

### ISSUE THREAD

**Issue by smrpr** [facebook/react-native#25268]
When in a ScrollView with multiple TextInputs, each of them using a different type of keyboard which has different height (e.g. iOS default keyboard and iOS numeric keyboard with `Done` button), switching between fields by using `focus()` while changing the keyboard at the same time makes some TextInputs not visible (although focused), as `focus()` doesn't take into account the difference in height between keyboards thus making the field not visible without manually scrolling.

![keyboardheightbug](https://user-images.githubusercontent.com/3258900/59517354-b8b2c000-8ec3-11e9-931e-81367fd719a2.gif)

React Native version: 0.59.0

## Steps To Reproduce

1. Have a KeyboardAvoidingView inside a ScrollView with multiple TextInputs, each of them using different keyboard types (e.g. `keyboardType={'default'} autoCorrect={false} returnKeyType = { 'next' }` and `keyboardType={'numeric'} returnKeyType = { 'done' }`
2. Change focus between fields by pressing 'Next' in the keyboard.

Describe what you expected to happen: All fields are completely visible regardless of the type of keyboard being used.

Snack, code example, or link to a repository: https://snack.expo.io/@smrpr/05cf08

**Comment by smrpr** [comment]
Any updates on this?

**Comment by c316** [comment]
This is still a problem
