### ISSUE TITLE
Question:  Why am I receiving the "React/RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by OluAgunloye** [facebook/react-native#25262]
The problem is as you see below, with my react native environment as follows:

`react-native-cli: 2.0.1
react-native: 0.55.2
`
![image](https://user-images.githubusercontent.com/6617770/59477350-66699480-8e1a-11e9-93b0-6861d038c8ad.png)

**Comment by adithyareddyZ** [comment]
@OluAgunloye Were you able to get through this? Am facing the same issue here, please let me know.
