### ISSUE TITLE
Release build crash on android

### ISSUE THREAD

**Issue by Mubashir1044** [facebook/react-native#25269]
I have created the react native app by react native init. The size of release apk is very large but it works fine. For reducing size of apk i hav enabled  `def enableSeparateBuildPerCPUArchitecture = true` i have created released apk for android. It creates 4 different apks. By installing the corresponding apk on Nexus 6p it shows me the following error
![image](https://user-images.githubusercontent.com/15061529/59534964-1fa69800-8f09-11e9-9bae-820ef1362f2f.png)
The package.json for my app is:
` "@react-native-community/netinfo": "^2.0.10",
    "axios": "^0.18.0",
    "dateformat": "^3.0.3",
    "react": "16.8.3",
    "react-native": "0.59.5",
    "react-native-autocomplete-input": "^4.0.0",
    "react-native-collapse-view": "^1.0.0",
    "react-native-collapsible": "^1.4.0",
    "react-native-elements": "^1.1.0",
    "react-native-firebase": "^5.3.1",
    "react-native-gesture-handler": "^1.2.1",
    "react-native-htmlview": "^0.14.0",
    "react-native-image-zoom-viewer": "^2.2.25",
    "react-native-material-dropdown": "^0.11.1",
    "react-native-searchable-dropdown": "^1.0.6",
    "react-native-share": "^1.1.3",
    "react-native-vector-icons": "^6.4.2",
    "react-navigation": "^3.9.1",
    "react-redux": "^7.0.3",
    "redux": "^4.0.1",
    "redux-thunk": "^2.3.0",
    "rn-fetch-blob": "^0.10.15"`

React native info is:

>  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz
      Memory: 1.28 GB / 7.93 GB
    Binaries:
      Yarn: 1.9.4 - C:\Users\Mubashir\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5522156

>

**Comment by dulmandakh** [comment]
Please use app bundles instead, see https://developer.android.com/platform/technology/app-bundle. Also I think that the error is caused by JS code, so please debug your code.
