### ISSUE TITLE
RN 0.59.8: postMessage result from iOS WebView is double-encoded

### ISSUE THREAD

**Issue by aldistel** [facebook/react-native#25266]
The data returned to onMessage WebView callback on iOS is double-percent-encoded.

React Native version: 0.59.8

## Steps To Reproduce

1. Inject a JS into WebView that calls e.g. `window.postMessage('https://test.com')`
2. The onMessage handler will receive double-encoded value:
```
<WebView onMessage={onMessage} ... />

function onMessage(event) {
   console.log(event.nativeEvent.data);  // "https%253A%252F%252Ftest.com"
}
```

This was introduced in https://github.com/facebook/react-native/commit/61ca11965046f75e7500e5152c5f2b60df2a2cd5#diff-17ddfccc3e39071c0aa51f82677e6d68 :

![image](https://user-images.githubusercontent.com/51444791/59513755-ca906500-8ebb-11e9-81d4-1f069455d0e5.png)

Correct method to use instead of `stringByReplacingPercentEscapesUsingEncoding` is `stringByRemovingPercentEncoding`.

cc @pvinis

**Comment by guhungry** [comment]
React Native's WebView was deprecated please migrate to [Community](https://github.com/react-native-community/react-native-webview) version

**Comment by Ruanyang2015** [comment]
me too

**Comment by Atanatous** [comment]
I had the same error with Expo SDK 33 and iOS.
So I have tried to use react-native-webview from community, and it works to me!
In this change, if you use `postMessage` function, you should change `windows.postMessage()` to `window.ReactNativeWebView.postMessage()`.

However, it shows error message as belows when I inject this code
`Error evaluating injectedJavaScript: This is possibly due to an unsupported return type. Try adding true to the end of your injectedJavaScript string.`.

If you try this and solve, please notice me, too!

**Comment by yurnery** [comment]
me too

**Comment by Ruanyang2015** [comment]
> me too

改 OC原生可以避免它

**Comment by aijason** [comment]
Platform.OS === 'ios' ? decodeURIComponent(decodeURIComponent(event.nativeEvent.data))
 : event.nativeEvent.data

**Comment by Ruanyang2015** [comment]
> `Platform.OS === 'ios' ? decodeURIComponent(decodeURIComponent(event.nativeEvent.data)) : event.nativeEvent.data`

I tried your method, but it still went wrong.

**Comment by hyper750** [comment]
I solve it with
```javascript
let string_data = m.nativeEvent.data;
if(Platform.OS === "ios"){
	// IOS returns the data url encoded/percent-encoding twice
	// unescape('%257B') -> %7B
	// unescape(%7B) -> {
	string_data = unescape(unescape(string_data));
}
```

**Comment by t-benze** [comment]
somehow adding `useWebKit={true}` fix the issue

**Comment by bauerlaci** [comment]
> 

it's working for me, thanks a lot!
(using expo sdk 33 on iOS)
