### ISSUE TITLE
Changing TextInput selection after setting text crash

### ISSUE THREAD

**Issue by Vaintti** [facebook/react-native#25265]
When TextInput selection is updated after changing the text (using InteractionManager.runAfterInteractions to wait for the change to apply) RN crashes. You get error like "setSpan(4 ... 4) ends beyond length" which indicates that the text field text has not changed like you would expect when using runAfterInteractions.
React Native version:

info
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 34.23 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.0, 25.0.2, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.3
        System Images: android-25 | Google Play Intel x86 Atom, android-26 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.9 => 0.59.9
## Steps To Reproduce

1. Change controlled TextInput value in code
2. Change TextInput selection to be after the inserted text using InteractionManager.runAfterInteractions

or just run the example in repo I linked and press the button.

Describe what you expected to happen:
Selection changes to place after inserted text

Snack, code example, or link to a repository:
[https://github.com/Vaintti/RNTextInputBug](url)

**Comment by blohamen** [comment]
Have similar issue on RN 0.60.4

**Comment by blohamen** [comment]
Issue still reproduced on React Native 0.61.2

**Comment by callcter** [comment]
same issue in 0.61.2

**Comment by cayodonatti** [comment]
I also still got the issue in React Native 0.61.1, seems to only happen on Android

**Comment by anilios** [comment]
I am also having same issue.. don't know how to fix..

**Comment by jsamr** [comment]
This issue has not been fixed.

**Comment by jsamr** [comment]
Someone has been able to reproduce on latest versions?

**Comment by jsamr** [comment]
Someone has been able to reproduce on latest versions?

**Comment by jsamr** [comment]
I believe this is still relevant.

**Comment by SonuToor** [comment]
Still having this on `0.63.3`

**Comment by jsamr** [comment]
I just reproduced this bug on 0.63.4

**Comment by fabriziobertoglio1987** [comment]
> Please, is it possible to merge this PR in the next version ?

To answer the question of when the pr https://github.com/facebook/react-native/pull/29070 which fixes this issue will be released in the next version of React Native, I suggest you to follow the discussions at https://github.com/react-native-community/releases/issues by subscribing to those threads. The process of releasing a new version with a bug fix is the following:

- an Issue is opened in facebook/react-native
- a contributor writes a Pull Request to fix/close the react-native Issue
- The Pull Request is merged in Master
- For each realease (the upcoming one is 0.64.1) there will be a separate discussion on https://github.com/react-native-community/releases/issues where anyone can request a commit to be cherrypicked from master. The link need to be from the a **commit** from master (for ex. https://github.com/facebook/react-native/pull/29157#issuecomment-651430945) and not a Pull Request not yet merged in master :peace_symbol: :pray:
