### ISSUE TITLE
☂️ Supporting Android Q Beta

### ISSUE THREAD

**Issue by hramos** [facebook/react-native#25270]
This task tracks issues with Android Q. It is currently in [Beta](https://developer.android.com/preview), with an expected release date sometime in Q3 2019.

## Known Issues

- [ ] #25258 Text missing on Android Q

**Fixed Issues**

- [X] #23112 Migrate to AndroidX

**Comment by bhollander-root** [comment]
Hello @hramos and other maintainers,

In Android Q, users will now have the option to prevent apps from accessing location in the background.

Is there a plan to support the changes to location permissions? There is currently no way to request or check background location access.

[Android Q location permission changes](https://developer.android.com/preview/privacy/device-location)

**Comment by kelset** [comment]
I think we can close this off now :D
