### ISSUE TITLE
Question: How to change adb 5037 default port when react-native run-android

### ISSUE THREAD

**Issue by Girum** [facebook/react-native#25272]
Hi!

I'm using a Splashtop Xdisplay to Extend my monitor, but apparently it uses the 5037 adb port. Well.. I create another adb -R 5039 start-server to start another adb server to not conflict with 5037 one. But, when I run react-native run-android, it always run on adb 5037 port. How can I change this, for example, to port 5039?

**Comment by tuantvk** [comment]
You try:
`react-native start --port 5039`
