### ISSUE TITLE
Network breaks after compile to APK

### ISSUE THREAD

**Issue by RowanHall** [facebook/react-native#25288]
React Native version:
```
info
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
      Memory: 5.83 GB / 15.90 GB
    Binaries:
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5522156
```
---

Code snippet:
```
<Button title="Login" onPress={() => {
  this.setState({myText: "Logging In...."})
  console.log("SUBMIT LOGIN")
  console.log(texts)
  fetch(global.endpoint + "/api/login?data=" + JSON.stringify(texts)).then(data => {
    return data.json()
  }).then(data => {
    if(data.loggedin) {
      global.token = data.token
      navigate('loggedin')
    } else {
      this.setState({myText: data.err})
    }
  })
}}></Button>
```

When clicking the Button after running `react-native run-android`, it works perfectly fine

but after building with `gradlew assembleRelease`, it never sends the request (the server doesn't receive any data)

*i'm new to React-Native, this is my second day working with it, so pre-emptive sorry if there's anything i'm missing or incorrectly naming*

**Comment by dulmandakh** [comment]
Network requests must be over HTTPS, it's Android requirement, please check. It will work in debug mode because we disable the requirements for development purposes.
