### ISSUE TITLE
Images not rendered in certain android devices

### ISSUE THREAD

**Issue by subhashchandrujobop** [facebook/react-native#25291]
[https://drive.google.com/open?id=1vQ-Wb6Yk-LYmu7VcYVL_YoCFI7q7N5rG](url)

In this image , you see navigation button in top left rendered with image, but when i try to load on certain one specific device it the image is not rendered but i can able to click the button and any images are not rendered any where in the app

enviroiment

"react": "16.8.3",
"react-native": "0.59.8" 
 Nokia 7 plus
build number :00WW_3_51F_SP02
android  version :9

**Comment by dulmandakh** [comment]
Could you please provide reproducible demo code. Also please note Android requires HTTPS for all network requests, and make sure you have HTTPS for network images. I'll re-open once demo code is available.

**Comment by subhashchandrujobop** [comment]
```
  <View style={{flexDirection:'column',width:this.state.windowwidth/3}}>
                      <Text style={{alignSelf:'center',position:'absolute',fontWeight:'bold',fontSize:20}}>Image</Text>
                        <Image style={{left:0,height:'100%',width:'100%',alignSelf:'center',marginLeft:'6%',marginTop:'6%'}}
                            source={require("./Drawbles/large.png")}
                            resizeMode='contain'/>
                            </View>

```
