### ISSUE TITLE
[Android] Images are not showing using local assets or remote image.

### ISSUE THREAD

**Issue by abhagsain** [facebook/react-native#25290]
React Native version:
React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
      Memory: 7.54 GB / 15.85 GB
    Binaries:
      Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338

## Steps To Reproduce

Here's the code 
```Poster.js```
```
const Poster = ({ imageURL }) => {
  const { width } = Dimensions.get("window");
  console.log(imageURL);
  return (
    <View style={{ padding: 5 }}>
      <Image
        source={imageURL}
        style={{
          width: Math.floor(width / 2 - 30),
          height: 300,
          flex: 1,
          borderRadius: 10,
        }}
      />
    </View>
  );
};
```

It's being called from here. 
```MovieGrid.js```
```
....
     <View style={movieGrid}>
          <Poster imageURL={require("../images/image.jpg")} />
          <Poster imageURL={require("../images/1.jpg")} />
          <Poster imageURL={require("../images/2.jpg")} />
        </View>
      </View>
....
```

1.
When I run the same app in the browser using Expo it works fine but when I run it on an emulator or a physical device it doesn't show the images. 
In the Web Browser

![Screenshot (79)](https://user-images.githubusercontent.com/36589645/59653685-bb0d6680-91b0-11e9-88c9-b3bd45983599.png)

On Emulator 

![Capture_](https://user-images.githubusercontent.com/36589645/59653838-733b0f00-91b1-11e9-9ef2-afa9e5859d38.PNG)

Also ```require('../images/image.jpg')``` returns a number

![Capture](https://user-images.githubusercontent.com/36589645/59653892-98c81880-91b1-11e9-9dcc-e48f3d72dd9f.PNG)

Working with images is such a pain 😥
Thank you for your time.

**Comment by karltaylor** [comment]
I currently have this issue too. My images appear fine on a fresh `react-native init` app when running on android in debug and release mode.

However in my current application, images and assets appear fine in debug but do not appear in release.

```
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (8) x64 Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
      Memory: 1.28 GB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.2.1 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.3 => 16.8.6
      react-native: ^0.59.8 => 0.59.9
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

**Comment by rochapablo** [comment]
I'm having quite the same here. On emulator works but on real device there's no image (android only).

```
return (<Image style={styles.image} resizeMode={'contain'} source={require('../../assets/images/logo.png')} />);
```

```
"react": "16.8.3",
"react-native": "0.59.5",
```

**Comment by karltaylor** [comment]
Might not be related, but in my release build configs, I had minify and Shrink Resources, which made all files turn black:

```gradle
buildTypes {
  release {
    singingConfig signingConfigs.release
  
    // commenting out below because they break assets on android release

    // minifyEnabled true
    // shrinkResources true
  }
}

**Comment by rochapablo** [comment]
Crazy!

I'm in another project right now, with a different RN version, but the images are called in the same way.

Turns out when I had to build a new version I got the error about duplicate drawable images, so I though "I'll delete them and my build will not show my images". But no, it is all working.

```
"react": "16.8.3",
"react-native": "0.59.9",
```

**Comment by srivatsav** [comment]
Looks like shrinkResources true is messing up with assets. However, minifyEnabled can still be true. Keeping that true and building a release apk didn't affect my assets. Any step to skip the assets when shrinkResources is enabled ??
```
buildTypes {
  release {
    singingConfig signingConfigs.release
  
    // commenting out below because they break assets on android release

    minifyEnabled true
    // shrinkResources true
  }
}
```

**Comment by rochapablo** [comment]
It still need attention.

**Comment by wincod75** [comment]
Same thing, none of my emulators are showing images, regardless if they are local or remote. All of my images in both dev and prod are sent via HTTPS. They are not showing in my debug APKs or my release APKs. I have tried various Android emulators: 7, 8 and 9. iOS is working just fine, as usual.

"react": "16.6.3",
"react-native": "0.59.10"

**Comment by marcelschulze** [comment]
I had something similar, until I found out, that I had "url" instead of
"uri" as the source object passed to the image. It was working fine on ios,
so I didn't even think about it. Hope that helps somebody else!

**Comment by yusufbadurohman** [comment]
@wincod75 works for me, thanks 👍

**Comment by DavidAPears** [comment]
I am having something similar, ReactNative/Expo - both images *and* some line graphs rendering perfectly in iOS but not showing in Android. There are no error messages.

[I have tried adding ```resizeMode={'contain'} ``` as suggested elsewhere]

iOS:  
![image](https://user-images.githubusercontent.com/36195948/71905426-05abfb80-3160-11ea-98f6-6c18a4743617.png)
Android:
![image](https://user-images.githubusercontent.com/36195948/71905440-0ba1dc80-3160-11ea-9176-4e7124332b38.png)

**Comment by DavidAPears** [comment]
FYI: I down-graded my `react-native-svg`  package from '10.0.0' to  `"react-native-svg": "9.5.3"` & that seemed to clear it. Images coming through now.  I _know_ this is slightly diff from other situations on here, but this may help someone 🤟🏻

**Comment by choudharyjji** [comment]
Facing Same problem.. Images showing in emulator but not after assemblerelease. Any Help :(

**Comment by AyoubXwire** [comment]
I had the same problem, found out that internet was not working on my Android device.. I restarted the device and the image showed up normally.. I hope that helps someone along the way.

**Comment by jasonbodily** [comment]
Same problem here, although I find that if I put the app in the background and then re-open it, the images show. Anyone else find that?

**Comment by fourstring** [comment]
> Same thing, none of my emulators are showing images, regardless if they are local or remote. All of my images in both dev and prod are sent via HTTPS. They are not showing in my debug APKs or my release APKs. I have tried various Android emulators: 7, 8 and 9. iOS is working just fine, as usual.
> 
> "react": "16.6.3",
> "react-native": "0.59.10"
> 
> **Update**
> 
> After running Android Studio and reviewing the logcat output I discovered a warning:
> "Dependency ':native-imagetranscoder'"
> 
> This lead me to: https://github.com/facebook/fresco
> 
> And in my android/app/build.gradle file I added...
> 
> **This:** "implementation 'com.facebook.fresco:fresco:2.0.0'"
> 
> If you are using GIF's you will also need need...
> 
> **This:** "implementation 'com.facebook.fresco:animated-gif:2.0.0'"
> 
> And just like that my images are back...

Thanks a lot. It works for me. Maybe project template should be updated to include that dependency by default, at least in typescript one there is no such dependency.

**Comment by kisakyegordon** [comment]
In my case - the images were showing in IOS but not on Android.

- I later realised, i had applied the elevator which hid the image on android

**Comment by marcustut** [comment]
Same issues here, but realised that it was the Android Emulator not getting any internet connection. Tried wiping data and restarting, both doesn't work until I came across this [post](https://medium.com/@cafonsomota/android-emulator-when-theres-no-connection-to-the-internet-129e8b63b7ce).

What I do is,
1. Close the running Android Emulator.
2. Run `emulator @<your_emulator_name> -dns-server 8.8.8.8` in a terminal.
3. Woola! Now the internet works and all remote images loaded correctly.

PS: You can use `emulator -list-avds` to check the emulator's name.

**Comment by sheltonkertich** [comment]
i had the same issue. turns out i had import image component from react-native-elements instead of rect-native

**Comment by eltongonc** [comment]
I had the same issue and in my case, the solution was giving the image a default styling and resize mode.

```jsx
 <Image resizeMode="cover" style={styles.image} />


const styles = Stylesheet.create({
  image: {
     width: '100%',
     height: '100%'
  }
})
```

**Comment by theartificialguy** [comment]
This is still an issue, none of my local image assets are visible, but every image is visible on iOS, this is really weird.

**Comment by muditsen** [comment]
Android:
http://172.16.119.37:8081/assets/src/assets/my_orders.png?platform=android&hash=1741d26e319a1f4e934f651d1955c818



IOS:
http://localhost:8081/assets/../../libs/forex/src/ForexListing/assets/my_orders.png?platform=ios&hash=1741d26e319a1f4e934f651d1955c818


For both of the Platforms the url generated for local images is different. I am unable to find the actual url which will work for android.


Also :

Iimages kept apps/ folder are loading but image outside apps (libs folder) are not being loaded.

http://172.16.119.37:8081/assets/src/app/assets/ic_bmf_logo.png?platform=android&hash=3dd2be38e2726be6a24584f4c5464d90

**Comment by vinamrahalgar** [comment]
Any update on this? I have a similar issue. 
I am passing a remote uri to the Image and it is visible in iOS regardless of debug or release mode. But not loading in andorid in release mode. 
BoardLogo is fetched from some other function whose value is - https://*************/Clients/3e474bef-6392-4ff8-aa44-b4304b1d8537/Images/logo1.png.
If I hardcode this uri in the source prop it works perfectly fine but when passing like below, it doesn't render. I have tired adding key prop as well. 
Code - 

     <Image
              style={styles.imageStyle}
              source={boardLogo ? { uri: boardLogo } : Bitmap}
            />
