### ISSUE TITLE
Cannot build on android after google services update on June 17, 2019

### ISSUE THREAD

**Issue by aujisti-ador** [facebook/react-native#25299]
Since June 18, 2019 react-native android build is failing. The following error is given during gradle build:

```
AGPBI: {"kind":"error","text":"Program type already present: android.support.v4.app.INotificationSideChannel","sources":[{}],"tool":"D8"}
> Task :app:mergeExtDexDebug FAILED
java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.

```
React Native version:
react-native": "^0.57.3

Some of the libraries we use:
   ```
    "react-native": "^0.57.3",
    "react-native-base64": "0.0.2",
    "react-native-camera": "^2.9.0",
    "react-native-contacts": "^3.1.5",
    "react-native-date-ranges": "^2.3.1",
    "react-native-device-info": "^2.1.2",
    "react-native-firebase": "^5.2.1",
    "react-native-keyboard-aware-scroll-view": "^0.8.0",
    "react-native-maps": "^0.23.0",
    "react-native-modal-datetime-picker": "^6.0.0",
    "react-native-modal-dropdown": "^0.6.2",
    "react-native-nfc-manager": "^1.2.2",
    "react-native-phone-input": "^0.2.1",
    "react-native-router-flux": "^4.0.6",
    "react-native-splash-screen": "^3.1.1",
    "react-native-svg": "^9.2.2",
    "react-native-svg-uri": "^1.2.3",
    "react-native-user-inactivity": "^0.1.3-next",
    "react-native-vector-icons": "^6.2.0",
    "react-navigation": "^2.18.2",
```

Our sdk versions in project level build.gradle:
```
buildscript {
    ext {
        buildToolsVersion = "27.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "27.1.1"
        googlePlayServicesVersion = "11.8.0"         
        androidMapsUtilsVersion = "0.5+"
    }
  ......
}
```

Dependencies in App level build.gradle:
```
dependencies {
    implementation(project(':react-native-firebase')) {
        transitive = false
    }
    implementation project(':react-native-device-info')
    implementation project(':react-native-svg')
    implementation(project(':react-native-maps')) {
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation 'com.facebook.react:react-native:+'
    implementation 'com.google.firebase:firebase-core:+'
    implementation 'com.google.firebase:firebase-messaging:17.0.0'
    implementation 'com.google.android.gms:play-services-base:16.0.0'
    implementation 'com.google.android.gms:play-services-maps:+'
    implementation 'com.google.android.gms:play-services-gcm:16.0.0'
    implementation project(':react-native-camera')
}
```

Please suggest how to resolve this issue. We are aware that this maybe caused by google services update, but it's not viable for us to migrate to AndroidX.

**Comment by kelset** [comment]
Please refer to: https://github.com/facebook/react-native/issues/25293#issuecomment-503045776

**Comment by hrachqyutukyan** [comment]
dependencies {
    implementation "com.google.firebase:firebase-messaging:17.0.0"
    implementation("com.google.android.gms:play-services-gcm:16.0.0") {
        exclude group: "com.google.android.gms"
    }
    implementation project(':react-native-device-info'),  {
        exclude group: "com.google.android.gms"
    }
    implementation project(':react-native-exception-handler')
    implementation project(':react-native-image-picker')
    implementation project(':react-native-image-crop-picker')
    implementation project(':react-native-android-location-enabler')
    implementation project(':react-native-svg')
    implementation project(':react-native-push-notification'), {
        exclude group: "com.google.android.gms"
        exclude group: "com.google.firebase"
    }
    implementation project(':@react-native-community_async-storage')
    implementation project(':react-native-vector-icons')
    implementation project(':react-native-maps')
    implementation project(':react-native-gesture-handler')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation project(':react-native-navigation')
    implementation project(':react-native-contacts')
    implementation project(':react-native-linear-gradient')
    implementation project(':react-native-geocoder')
    implementation(project(':react-native-maps')){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
    implementation 'com.facebook.fresco:animated-gif:1.10.0'
    implementation project(':react-native-image-picker')
}
my dependencies and still have this issue
