### ISSUE TITLE
autoGenerateWrapperClass error caused by ReactNavigator in new project

### ISSUE THREAD

**Issue by lwansbrough** [facebook/react-native#253]
Steps to reproduce:

1. Generate new project with RN CLI
2. Replace rendered view in `index.ios.js` with the example in the [`ReactNavigator` docs](https://facebook.github.io/react-native/docs/navigator.html#content)
3. Add `ReactNavigator` to the destructured `React` object at the top of the file.
4. Replace `MySceneComponent` with `View`
5. Run the app

**Comment by vjeux** [comment]
This error happens when you try to render a component that's actually undefined.

```
var Component = undefined;
return <Component />;
```

The error message is terrible, we need to fix it. Cc @balpert

**Comment by lwansbrough** [comment]
So is the expected behaviour or a bug? I can't seem to get a project working with the provided code for `ReactNavigator`.

**Comment by lwansbrough** [comment]
Ah, found it. The docs are wrong - the component name is `Navigator` not `ReactNavigator`.

**Comment by tadeuzagallo** [comment]
Oh, I'll fix these docs right now!

**Comment by lwansbrough** [comment]
Gracias.

**Comment by simechiang** [comment]
Good job! I get a problem, I don't know how to use `NavigatorIOS` and `Navigator`, It's not working... 

```javascript```
'use strict';

var React = require('react-native');
var {
  NavigatorIOS,
  AppRegistry,
  StyleSheet,
  ScrollView,
  TextInput,
  Navigator,
  SwitchIOS,
  SliderIOS,
  DatePickerIOS,
  TouchableHighlight,
  View,
  Text
} = React;

var HelloWorldView = React.createClass({
  render: function() {
    return (
      <ScrollView>
        <Text style={ styles.instructions }> Hello world... </Text>
      </ScrollView>
    );
  }
});

var HomePage = React.createClass({
  getInitialState: function () {
    return {
      input: '',
      seleted: false
    };
  },

  render: function() {
    return (<View>
              <NavigatorIOS initialRoute={{
                'title': 'hello index',
                'component': HelloWorldView
              }}></NavigatorIOS>
            </View>);
  }
});

var styles = StyleSheet.create({
  emptyPage: {
    color: 'red'
  },
  container: {
    paddingTop: 30,
    paddingLeft: 20,
    paddingRight: 20,
    backgroundColor: '#FFF'
  },
  welcome: {
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    fontSize: 100,
    color: '#000'
  },
});

AppRegistry.registerComponent('HomePage', () => HomePage);
```

![11bf1891-92ed-4710-855f-2e1365fd5090](https://cloud.githubusercontent.com/assets/5195218/6977101/0d8a45d8-d9e9-11e4-905a-83aec25882d3.png)
