### ISSUE TITLE
Type error: undefined is not an object(evaluating 'this_.callListeners.bind')

### ISSUE THREAD

**Issue by Kaushik36** [facebook/react-native#25305]
![Screenshot_20190618-183801](https://user-images.githubusercontent.com/18187688/59742546-989c4b80-928b-11e9-9119-36edeb177b97.png)

My Package.json is as follows.

{
"name": "Demo",
"version": "0.0.1",
"private": true,
"scripts": {
"start": "node node_modules/react-native/local-cli/cli.js start",
"test": "jest"
},
"dependencies": {
"@react-native-community/async-storage": "^1.4.2",
"lodash": "^4.17.11",
"mobx": "^5.10.1",
"mobx-react": "^5.4.4",
"native-base": "^2.12.1",
"react": "16.8.3",
"react-native": "0.59.8",
"react-native-fetch-polyfill": "^1.1.3",
"react-native-fs": "^2.13.3",
"react-native-gesture-handler": "^1.2.1",
"react-native-icon-badge": "^1.1.3",
"react-native-image-base64": "^0.1.3",
"react-native-image-picker": "^0.28.1",
"react-native-image-resizer": "^1.0.1",
"react-native-reanimated": "^1.0.1",
"react-native-simple-toast": "0.0.8",
"react-native-tab-view": "^2.5.0",
"react-navigation": "^3.11.0",
"recyclerlistview": "^1.3.4"
},
"devDependencies": {
"@babel/core": "7.4.5",
"@babel/plugin-proposal-class-properties": "^7.4.4",
"@babel/plugin-proposal-decorators": "^7.4.4",
"@babel/runtime": "7.4.5",
"babel-jest": "24.8.0",
"jest": "24.8.0",
"metro-react-native-babel-preset": "0.54.1",
"react-test-renderer": "16.8.3"
},
"jest": {
"preset": "react-native"
},
"rnpm": {
"assets": [
"./assets/fonts/"
]
}
}

My bable.config.js is as follows.

module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    ["@babel/plugin-proposal-class-properties", { "loose": true }]
  ],
};

**Comment by Kaushik36** [comment]
I am facing this issue whenever install a new library using npm install.

**Comment by altick** [comment]
I have faced the same issue and for me deleting metro-cache did the job. I'm using Windows where the solution is to delete metro-cache folder in AppData/Local/Temp.

`RMDIR /Q/S %LOCALAPPDATA%\Temp\metro-cache`
