### ISSUE TITLE
Android app crash on launch for OS 8 and above after Google Update

### ISSUE THREAD

**Issue by kohchenggee** [facebook/react-native#25308]
After Google update release and updated react-native-device-info. The app is running on mobile os 7 and below.

Mobile OS 8 crashes on launch after react-native run-android, 
error message: 
A/libc: Fatal signal 7 (SIGBUS), code 1, fault addr 0x37bf3a90253f5 in tid 6474 (mqt_js)

Mobile OS 9 unable to load script,
error message: 
E/unknown:ReactNative: Exception in native call
    java.lang.RuntimeException: Unable to load script. Make sure you're either running a Metro server (run 'react-native start') or that your bundle 'index.android.bundle' is packaged correctly for release.

"react": "^16.8.3",
 "react-native": "^0.59.9",
"react-native-device-info": "^2.1.2",

## Steps To Reproduce

1. 
2.

Describe what you expected to happen:

Snack, code example, or link to a repository:

**Comment by rakibhasan48** [comment]
I got the same error and resolved it by setting: 
`targetSdkVersion = 27`
in project level build.gradle. Then perform a gradle clean and try to run again.

**Comment by umerbaig** [comment]
I'm getting same error
