### ISSUE TITLE
Invalid bitcode version

### ISSUE THREAD

**Issue by vgm8** [facebook/react-native#25315]
I'm trying to archive an ios project and I'm getting this error:

`id: could not reparse object file in bitcode bundle: 'Invalid bitcode version (Producer: '902.0.39.2_0' Reader: '900.0.39.2_0')', using libLTO version 'LLVM version 9.0.0, (clang-900.0.39.2)' for architecture armv7
`

It was working fine before and I didn't add or remove any library. I've downloaded 9.2 xcode version and the error is still happening. Also i've tried to remove build and derivedData folders but nothing is working. Any help please.

**React Native version:**
    System:
      OS: macOS Sierra 10.12.6
    Binaries:
      Node: 11.11.0 - ~/.nvm/versions/node/v11.11.0/bin/node
    SDKs:
      iOS SDK:
        Platforms: iOS 11.2, macOS 10.13, tvOS 11.2, watchOS 4.2
      Xcode: 9.2/9C40b - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.9 => 0.59.9

**Comment by vgm8** [comment]
I finally fixed it after update xcode to 10.2.

**Comment by ecreeth** [comment]
@vgm8 If the problem was solved, you can close this issue. Thanks!
