### ISSUE TITLE
Is it impossible to return a StackNavigator without an App Container

### ISSUE THREAD

**Issue by vikramkh** [facebook/react-native#25316]
I want to create a stack navigator from dynamic information, but in order to do so, it either has to take in props or be embedded in a class. Either way, I cannot just return the navigator as "Functions are not valid as react children". Is it impossible to create a stack navigator from dynamic data?

**Comment by vikramkh** [comment]
I did not mean to label this as a Bug

**Comment by dulmandakh** [comment]
Sorry, React Native has no navigation feature and you issue might be related to some other navigation library. Please file an issue to your navigation library.
