### ISSUE TITLE
error fetch in use react-native

### ISSUE THREAD

**Issue by jamaljaj4826** [facebook/react-native#25328]
(node:4224) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 55)
Error: connect ECONNREFUSED 127.0.0.1:34712
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
::ffff:127.0.0.1 - - [20/Jun/2019:11:13:01 +0000] "POST /symbolicate HTTP/1.1" 500 - "-" "okhttp/3.12.1"
(node:4224) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:34712
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
(node:4224) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 56)
(node:4224) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:34712
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
(node:4224) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 57)

**Comment by dulmandakh** [comment]
Please provide more description and reproducible demo code so we can investigate further. I'll re-open it once we have enough information. Thank you
