### ISSUE TITLE
Supporting iOS 13 Dark Mode

### ISSUE THREAD

**Issue by ZengyiMa** [facebook/react-native#25322]
iOS13 supports Dark Mode, is there any plan to support this feature?

**Comment by noahbrandyberry** [comment]
I know this doesn’t follow a template, but an answer to this would be appreciated.

**Comment by vemundeldegard** [comment]
Also interested to know if this will be supported.

**Comment by forsen** [comment]
This is copied from the issue template that was ignored when creating this issue: 

> If you'd like to discuss topics related to the future of React Native, or would like to propose a new feature or change before sending a pull request, please check out the discussions and proposals repo:
> - https://github.com/react-native-community/discussions-and-proposals

As it happens, "Dark Mode support" is already discussed in the mentioned repository. 

If you head over to https://github.com/react-native-community/discussions-and-proposals/issues/126 you will find the discussion and suggested strategies on how to support dark/light mode themes on the supported platforms 👍
