### ISSUE TITLE
unable to build android project --- Task :react-native-sqlcipher-storage:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by aravindkomandla** [facebook/react-native#25330]
Suddenly android project is failing to build showing error related to react-native-sqlcipher-storage.

Giving out a commet as : 

 error: method does not override or implement a method from a supertype
    @Override
    ^
Note:  ...\node_modules\react-native-sqlcipher-storage\src\android\src\main\java\org\pgsqlite\SQLitePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

React Native version:
React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
      Memory: 5.97 GB / 15.89 GB
    Binaries:
      Yarn: 1.6.0 - C:\Users\aravind.komandla\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5522156

## Steps To Reproduce

1. npm install react-native-sqlcipher-storage
2. react-native link react-native-sqlcipher-storage
3. after successful linking of libraries then try to run-android we are facing issue.

Describe what you expected to happen:
I was expecting to build the project successfully

**Comment by dulmandakh** [comment]
It looks like react-native-sqlcipher-storage issue, because error is saying that it's trying to override or implement method that doesn't exists. Please file an issue to react-native-sqlcipher-storage. Thank you
