### ISSUE TITLE
Context not working in 0.60.0-rc.2

### ISSUE THREAD

**Issue by JonnyBurger** [facebook/react-native#25337]
React Native version:

0.60.0-rc.2

## Steps To Reproduce

```
react-native init rncrash --version 0.60.0-rc.2
yarn add react-navigation react-navigation-gesture-handler
react-native link
```

## Describe what you expected to happen:

I used react-navigation's `withNavigation` which utilises context.
This worked before, now it throws at this exact location:

https://github.com/react-navigation/core/blob/master/src/views/withNavigation.js#L22

Snack, code example, or link to a repository:

https://github.com/JonnyBurger/rn-60-rc2-crash

App.js:

```
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * Generated with the TypeScript template
 * https://github.com/emin93/react-native-template-typescript
 *
 * @format
 */

import React, { Component, useEffect } from "react";
import { Platform, StyleSheet, Text, View } from "react-native";
import { createAppContainer, withNavigation } from "react-navigation";

const instructions = Platform.select({
  ios: "Press Cmd+R to reload,\n" + "Cmd+D or shake for dev menu",
  android:
    "Double tap R on your keyboard to reload,\n" +
    "Shake or press menu button for dev menu",
});

const Inside = () => {
  return <View />;
};

const InsideWithNavigation = withNavigation(Inside);

const Root = () => {
  return (
    <View style={styles.container}>
      <InsideWithNavigation />
    </View>
  );
};

const RootWrapped = createAppContainer(Root);

interface Props {}
export default function App() {
  useEffect(() => {}, []);
  return (
    <View style={styles.container}>
      <Root />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F5FCFF",
  },
  welcome: {
    fontSize: 20,
    textAlign: "center",
    margin: 10,
  },
  instructions: {
    textAlign: "center",
    color: "#333333",
    marginBottom: 5,
  },
});
```

**Comment by satya164** [comment]
Hmm weird. The error message seems reasonable though? There's no navigator in your example.

**Comment by JonnyBurger** [comment]
Fair enough.

Just tried to make another reproducible example for the last 2 hours but failed, although this problem still exists in my project (it is inside a navigator and worked in RN59).

Because I have not much time over the next few 7-10 days to debug this I'm gonna close this. Sorry 😕

Could just be that I did not cleanly upgrade RN, for example I did not switch to Cocoapods.

**Comment by JonnyBurger** [comment]
Aaand the problem was as simple that `react` was not up to date.
Sorry everyone for wasting their time and it is not a bug.
