### ISSUE TITLE
Cannot open date picker Exception in HostFunction:Malformed calls from JS:field sizes are different

### ISSUE THREAD

**Issue by aflahkp** [facebook/react-native#25331]
While calling  DatePickerAndroid.open from onPress event of a TouchableOpacity,
A console warning with message 'Cannot open date picker Exception in HostFunction:Malformed calls from JS:field sizes are different ...' is shown instead of date picker. In the release build the same couses a crashe.

React Native version: 0.59.9

## Steps To Reproduce

1. While calling  DatePickerAndroid.open from onPress event of a TouchableOpacity
2. Then it shows a console warning with message 'Cannot open date picker Exception in HostFunction:Malformed calls from JS:field sizes are different ...'

Describe what you expected to happen:
DatePickerAndroid.open(..) should show DatePicker instead of warning

Snack, code example, or link to a repository:

   const { action, year, month, day } = await DatePickerAndroid.open({
        // Use `new Date()` for current date.
        // May 25 2020. Month 0 is January.
        date: new Date(),
        minDate: new Date(),
        maxDate: new Date(this.state.maxDate)
      });

**Comment by goskan93** [comment]
I have the same issue, but in my case I use `react-native-datepicker` package, which use `DatePickerAndroid`. I thought it might be their problem but it looks like the problem is with `DatePickerAndroid`.
![Screenshot_20190703-165714](https://user-images.githubusercontent.com/39600021/60669882-c796ed80-9e45-11e9-978d-1c0014a1238b.png)

**Comment by vgvishal538** [comment]
@aflahkp did you find any solution for this issue?

**Comment by vgvishal538** [comment]
if I am using datepicker after activating debug mode it is working fine but in normal condition, it shows above mentioned error.

**Comment by aflahkp** [comment]
The maxDate field i have given was null at some point. Giving a nonnull maxDate fixed my issue.

**Comment by SudoPlz** [comment]
I just posted a long answer here about what's happening and how to troubleshoot that: https://stackoverflow.com/a/67100389/1658268
