### ISSUE TITLE
Text Strings must be rendered 

### ISSUE THREAD

**Issue by Tacoholic** [facebook/react-native#25335]
Hi all,

I am learning React Native and I am currently following a tutorial on building a calculator. After adding my code in the Calc.js folder, I got the error message that you see above. From research, I saw that it could possible by something in my JSX, but i played around with it and I keep getting the same error. I have provided a screenshot of my code as well as an Expo link below. I did notice that when imported "TextInput", "Text" when to a darker shade of color at the top.  Does that have anything to do with it?  Any help is appreciated.

https://snack.expo.io/@tacoholic/c9e4f2

 React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (6) x64 Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
      Memory: 36.93 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.9 => 0.59.9 
    npmGlobalPackages:
      react-native-cli: 2.0.1

![Snip20190620_16](https://user-images.githubusercontent.com/46233361/59871298-d9b06080-935c-11e9-9f04-0a7bd0609324.png)
![Snip20190620_20](https://user-images.githubusercontent.com/46233361/59871441-390e7080-935d-11e9-8b32-78298e5d7866.png)
![Snip20190620_21](https://user-images.githubusercontent.com/46233361/59871531-6b1fd280-935d-11e9-8215-3965599a1b35.png)

![Snip20190620_17](https://user-images.githubusercontent.com/46233361/59871307-e03ed800-935c-11e9-9190-0fd5c3227fee.png)

**Comment by justDanielMata** [comment]
Line 15 on Calc, you have this `/>>`, the framework is interpretting the second > as a string and trying to render text without `<Text />` breaks the app, removing it should fix it, and this is probably a question for stackOverflow, just something to keep in mind on the future.
