### ISSUE TITLE
[iOS] Inconsistent behaviour when converting homogeneous arrays as native call arguments

### ISSUE THREAD

**Issue by gavrix** [facebook/react-native#25339]
On iOS, when calling native method that accepts array as argument, automatic conversion of values inside array is different in Release and Debug configuration. What works in Debug crashes in Release

React Native version:
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
      Memory: 663.40 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.11.0 - ~/.nvm/versions/node/v10.11.0/bin/node
      Yarn: 1.13.0 - ~/.dev/yarn/1.13.0/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.11.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.8 => 0.59.8 

## Steps To Reproduce

Call `AsyncStorage.set('key', 123)`
Above works in Debug and crashes in Release

## Describe what you expected to happen:

Above works in debug as `number` (although types suggest it explicitly expects `string`) gets automatically converted to string via sequence of calls ending with `RCTConvertArrayValue` which converts converts anything to expected type (which is `NSString`) https://github.com/facebook/react-native/blob/ffa3b0d4d601fe6788319a7cfd4185b8e4bf462f/React/Base/RCTConvert.m#L558

in Release sequence of macro calls is different though, never reaching `RCTConvertArrayValue` as can be seen here https://github.com/facebook/react-native/blob/ffa3b0d4d601fe6788319a7cfd4185b8e4bf462f/React/Base/RCTConvert.m#L591-L596

What I think is expected behaviour is that in Debug it should log error descriptions of types mismatches but never convert anything to NSString automatically.

Were there any considerations as to why automatic conversion to string was added that I am missing?

**Comment by cpojer** [comment]
Please report issues in AsyncStorage in this repo: https://github.com/react-native-community/async-storage – it was extracted from RN and will soon be removed from React Native. Please use the community package from now on.

**Comment by gavrix** [comment]
@cpojer, please, read carefully. The issue is in React Native RUNTIME. I only used AsyncStorage to illustrate it. It could have been any other native module with method that accepts array of strings as parameter.

**Comment by sammy-SC** [comment]
@gavrix this should resolved in https://github.com/facebook/react-native/commit/df17ebfcfaaf2cf5984e836bdb70ccf8d9f66307

**Comment by gavrix** [comment]
Awesome, Thanks!
