### ISSUE TITLE
unable to load script make sure you are either running a metro server or that your bundle "index.android.bundle" is packaged correctly for release

### ISSUE THREAD

**Issue by anandnidgundi** [facebook/react-native#25348]
This error coming after generating release apk, Please Help
![react-native-error](https://user-images.githubusercontent.com/5674956/59913382-ab528400-9435-11e9-9215-77fcbd5b9b98.jpeg)

**Comment by nahcnats** [comment]
what the fuck is this? i had to run the following command to make it work for a bare bone app for android.

react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res

hopefully i remember if i ever pull it from my git. this is fucking stupid. no docs whatsoever about the update to gradle 5 > above. all my dependencies don't work. my app just go kaput? plus stupid google play forces u to go to API28, anything less, they'll reply something like 'fuck off'.

**Comment by ivanfranchi** [comment]
android:usesCleartextTraffic="true" following  
THIS https://stackoverflow.com/questions/55441230/unable-to-load-script-make-sure-you-are-either-running-a-metro-server-or-that-yo  
and THIS https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted/50834600#50834600  
did the job (was having the same error)

**Comment by imAliAzhar** [comment]
To resolve try the following:
1. Clear watchman watches: `watchman watch-del-all`.
2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.

The files mentioned in step 3 and 4 may not exactly have the same name (e.g. `metro-cache` or `haste-map-metro`). To make sure you delete the temp files, navigate to /tmp directory and delete anything with `metro` or `haste` in it files yourself.

**Comment by dipo1** [comment]
In my case, the emulator was on airplane mode.
Make sure your emulator or mobile phone can communicate with the Metro server.

**Comment by TadjerouniMohamedAdel** [comment]
me too

**Comment by YahiaJabeur** [comment]
I m facing again this issue when I upgraded to react native 0.62.0
Any idea how to resolve it ?

**Comment by Taynan-Vieira** [comment]
Pessoal, essa solução funcionou para mim:

Não foi possível carregar o script dos ativos 'index.android.bundle'. Certifique-se de que ...
Esse erro geralmente ocorre porque o sistema não conseguiu criar o pacote inicial que contém todo o código Javascript da aplicação.

1- Para resolver, comece a criar uma pasta de ativos dentro da pasta android / app / src / main.

2- Logo após, execute o comando:

npx react-native bundle --plataforma android --dev false --entry-file index.js - android-app de saída de pacotes / app / src / main / assets / index.android.bundle --assets-dest android / app / src / main / res /

3- Agora, feche o terminal e execute novamente o comando:

npx react-nativo run-android
ou fio executar react -nativo run-android
ou fio android

Fonte: https://react-native.rocketseat.dev/erros/android/

**Comment by HassanShojaei** [comment]
I had same error, with a wipe data for emulator on AVD problem solved

**Comment by TalitaLira** [comment]
> In my case, the emulator was on airplane mode.
> Make sure your emulator or mobile phone can communicate with the Metro server.

Man, so simple! Mine had the network disconnected... Thanks a lot!

**Comment by alexeystrakh** [comment]
> what the fuck is this? i had to run the following command to make it work for a bare bone app for android.
> 
> react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
> 
> hopefully i remember if i ever pull it from my git. this is fucking stupid. no docs whatsoever about the update to gradle 5 > above. all my dependencies don't work. my app just go kaput? plus stupid google play forces u to go to API28, anything less, they'll reply something like 'fuck off'.

And even this won't work if you manually do not create the `assets` subfolder in the `android/app/src/main` folder. Thanks for the command!
