### ISSUE TITLE
ld: Library not found for -lgcc_s.10.5

### ISSUE THREAD

**Issue by isikfsc** [facebook/react-native#2534]
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/bufferutil.node] Error 1

Upon invoking react-native init ProjectName to create one I get those errors. But command completes stating at the and that:
Open iOS//Users/isik/Dev/sample-apps/app4d-react-native-breadcrumbnavbar/BreadcrumbNavBar/BreadcrumbNavBar.xcodeproj in Xcode
   Hit Run button

When I do that I get the red screen on the iOS simulator.

**Comment by ide** [comment]
Try restarting your computer.

**Comment by isikfsc** [comment]
Really? :)

**Comment by isikfsc** [comment]
Ok, It is solved when II have restarted packager I think. Thanks.

**Comment by bawn** [comment]
@ide It's worked for me
