### ISSUE TITLE
Error: failed linking references.

### ISSUE THREAD

**Issue by duarte-evocorp** [facebook/react-native#25356]
error: failed linking references.

* /root/.gradle/caches/transforms-1/files-1.1/appcompat-v7-26.0.2.aar/0f74942fbe38b2fcc7212cf929c7e3d9/res/values/values.xml:246:5-69: AAPT: er
ror: resource android:attr/fontVariationSettings not found.

* /root/.gradle/caches/transforms-1/files-1.1/appcompat-v7-26.0.2.aar/0f74942fbe38b2fcc7212cf929c7e3d9/res/values/values.xml:246:5-69: AAPT: er
ror: resource android:attr/ttcIndex not found.

React Native Environment Info:
    System:
      OS: Linux 4.9 Debian GNU/Linux 9 (stretch) 9 (stretch)
      CPU: (6) x64 Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
      Memory: 256.10 MB / 7.60 GB
      Shell: 4.4.12 - /bin/bash
    Binaries:
      Node: 8.16.0 - /usr/bin/node
      Yarn: 1.16.0 - /usr/bin/yarn
      npm: 6.9.0 - /usr/bin/npm
    SDKs:
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 26.0.1, 26.0.2, 27.0.3, 28.0.0, 28.0.2, 28.0.3
        System Images: android-25 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-Q | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: ^0.58.5 => 0.58.5 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

**Comment by rakibhasan48** [comment]
Set your compileSdkVersion to at least 28.

**Comment by msaifa** [comment]
is there a solution for fixing this problem ?

**Comment by jojonarte** [comment]
is there specific fix for this? :(

**Comment by vivek-aecor** [comment]
Please Provide Solution.

same issue.
Please check enclosed image.

![image](https://user-images.githubusercontent.com/50658820/64072949-08c84400-ccb5-11e9-9268-0b74af168c69.png)

**Comment by pvanny1124** [comment]
above solution does not work^^

**Comment by danieltov** [comment]
I'm also having this issue.

```bash
* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  /path/to/project/android/app/build/intermediates/merged_manifests/debug/AndroidManifest.xml:87: AAPT: error: resource xml/provider_paths (aka com.zoowho.android:xml/provider_paths) not found.

  error: failed processing manifest.
```

Any insight would be much appreciated.
