### ISSUE TITLE
user defined x-header doesnt send to api problem

### ISSUE THREAD

**Issue by 3mpe** [facebook/react-native#25372]
Hi all,

user defined x-header doesnt send to api problem

We have a rest api configured with cors. We can access it with ajax, swift etc.

But when we try to send request from android with react-native application x-header doesnt sent in request header. Our parameters added as miscellaneous header and not sent to server.

We try to request with axios and fetch and xmlHttpRequest

By the way when we try the same request with react it works.

My environment:

android,
react-native,
axios,
fetch
xmlHttpRequest

![request](https://user-images.githubusercontent.com/19467099/60013738-e0561500-9687-11e9-9416-20a66414cb50.PNG)

![error](https://user-images.githubusercontent.com/19467099/60013746-e64bf600-9687-11e9-8cf3-dab61e4043e3.PNG)

**Comment by dulmandakh** [comment]
what is your RN version? Does it work on iOS?

**Comment by 3mpe** [comment]
Nope it doesnt work even on ios 

![image](https://user-images.githubusercontent.com/19467099/60156105-67c09700-97f4-11e9-99d8-29c6b341bc69.png)

**Comment by 3mpe** [comment]
Ok. We found the solution.  the point of the problem RN converts headers to lowercase.  Uppercase headers doesnt sent to server.
