### ISSUE TITLE
Cannot create styled-component for component: [object Object]

### ISSUE THREAD

**Issue by ldco2016** [facebook/react-native#25375]
My app continues to crash upon splash screen and when I look at the MacOS Console I get two of the following errors:

`Cannot create styled-component for component: [object Object]` and `Module AppRegistry is not a registered callable module (calling runApplication)`

React Native version:

```
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 4.05 GB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.10.1 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 26.0.2, 27.0.3, 28.0.3
        System Images: android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.9 => 0.59.9
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

## Steps To Reproduce

1. download the app
2. Run npm install
3. Run `react-native run-ios`

Describe what you expected to happen:
I expect for the application to boot up and instead it crashes on splash screen at the native level.

Snack, code example, or link to a repository:

https://www.dropbox.com/s/ygyrhnno8aou4jg/RNsampleApp.zip?dl=0

**Comment by dulmandakh** [comment]
Could you please make demo code available on GitHub so it's easy to check it out and test.

**Comment by ldco2016** [comment]
@dulmandakh , please use this link to obtain the demo code and thank you.

**Comment by dulmandakh** [comment]
I would like to view the code online without downloading it. I assume that
many others will ask you the same. Sorry

**Comment by ldco2016** [comment]
@dulmandakh https://github.com/ldco2016/rn_crashing/invitations

**Comment by Sharcoux** [comment]
Is the repo private? I get a 404 following your link...

**Comment by ldco2016** [comment]
@Sharcoux , I am sorry yes, I thought only @dulmandakh  was going to be looking at it. I have added you as well: https://github.com/ldco2016/rn_crashing/invitations

**Comment by Sharcoux** [comment]
Man... You want help. Make it public.... If you're afraid to share private data, create a minimal self-contained example, it will be even easier to debug.

**Comment by Sharcoux** [comment]
Looks like a cache problem. Have you ever added styled-component within this project?

**Comment by ldco2016** [comment]
@Sharcoux , I have never added styled-components, but it looks like styled-components is inside of `package-lock.json` file and also exists as a dependency of `react-native-material-tabs`.

**Comment by Sharcoux** [comment]
Then isn't the problem coming from `react-native-material-tabs` and shouldn't it be resolved there?

**Comment by ldco2016** [comment]
@Sharcoux , okay, I will close this issue then.
