### ISSUE TITLE
IOS : ScrollView does not extend to the status bar area in Iphone X

### ISSUE THREAD

**Issue by akhan118** [facebook/react-native#25384]
Hi All, 

I'm having trouble setting my ScrollView to extend to the status bar area and I'm not sure if that's a bug or current functionality . 

React Native version:
0.59.9

For example

```
  return (
      <View  style={{flex:1}}>
      <ScrollView style={{flex:1}}>
      <Text>Random Text</Text>
      </ScrollView>
      </View>
    );

```

returns this for me , which bascially set the text right below the status bar area .

<img width="382" alt="Screen Shot 2019-06-22 at 4 16 03 PM" src="https://user-images.githubusercontent.com/4065374/60063738-2bd5e680-96bb-11e9-8071-1ea682c28aee.png">

I was hopping to actually have it look like this.

<img width="378" alt="Screen Shot 2019-06-22 at 4 16 48 PM" src="https://user-images.githubusercontent.com/4065374/60063748-342e2180-96bb-11e9-901f-654360c97d11.png">

How can I go about achieving this while using ScrollView ? 

it almost feels as if ScrollView has it's own save-view-area and the same also apply to FlatList.
Because whenever I take the <Text>Random Text</Text> out of Scroll view it seems extends to the status bar . 

thank you in advance

**Comment by zcgit** [comment]
make sure you are using the ScrollView in "react-native" , not in "react-navigation", and if you really want a full screen ScrollView, you can use a style like StyleSheets.absoluteFill. 
I also confused why it's like SafeAreaView as you showed above.

**Comment by akhan118** [comment]
@zcgit Thank you.  I did try absoluteFill and it didn't do anything, I placed it on the View and nothing happen and then I placed it on the ScrollView and nothing happen as well.

Also I made sure that ScrollView is imported from react-native .

Here is the entire component.
```

import {
  View,
  Text,
  StyleSheet,
  ScrollView
} from "react-native";
import React, {Component} from "react";



export default class ModalScreen extends React.Component {



  render() {
    return (
        <View  style={{...StyleSheet.absoluteFill,flex:1}}>
        <ScrollView style={{...StyleSheet.absoluteFill,}}>
        <Text>Random Text</Text>
        </ScrollView>
        </View>
      );


  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },

});
```

**Comment by akhan118** [comment]
Ok figured out , it seems to be a React Native Navigation thingy.

to fix it, just add  

contentInsetAdjustmentBehavior="never"

 to the ScrollView. 

[RNN Issue 3821 ](https://github.com/wix/react-native-navigation/issues/3821)
