### ISSUE TITLE
bundling failed: Error: Unable to resolve module `_wrapObjectFreezeAndFriends` from ` /node_modules/react-native/Libraries/Core/polyfillES6Collections.js`: Module `_wrapObjectFreezeAndFriends` does not exist in the Haste module map

### ISSUE THREAD

**Issue by HananeAlSamrout** [facebook/react-native#25389]
i tried to do all these step and nothing worked
 1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.

React Native version:
  info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 46.55 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 9.5.0 - ~/.nvm/versions/node/v9.5.0/bin/node
      Yarn: 1.6.0 - ~/.nvm/versions/node/v9.5.0/bin/yarn
      npm: 4.6.1 - ~/.nvm/versions/node/v9.5.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 21, 22, 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.0, 23.0.1, 23.0.2, 23.0.3, 24.0.0, 24.0.1, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.0, 28.0.1, 28.0.2, 28.0.3
        System Images: a...google_apis | Google APIs Intel x86 Atom Sys..., a...gle_apis | Google APIs Intel x86 Atom_64 ..., a... | Android TV Intel x86 Atom Syst..., a...ndroid-wear | Android Wear Intel x86 Atom Sy..., a...google_apis | Google APIs Intel x86 Atom Sys..., a... | Android TV Intel x86 Atom Syst..., a... | Android TV Intel x86 Atom Syst..., a...ndroid-wear | Wear OS Intel x86 Atom System ..., a...-28 | Intel x86 Atom, a... | Intel x86 Atom_64, a...gle_apis | Google APIs Intel x86 Atom_64 ..., a...s_playstore | Google Play Intel x86 Atom Sys..., a...laystore | Google Play Intel x86 Atom_64 ...
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.3 => 16.8.6 
      react-native: ^0.59.9 => 0.59.9 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-create-library: 3.1.2

## Steps To Reproduce

1.upgrade from react-native 0.59.5 to react-native 0.59.9

**Comment by joalcapa** [comment]
I present the same error, RN 0.59.2

**Comment by weinchester** [comment]
I encoutered this too when I run npm update using RN 0.59.6

**Comment by HananeAlSamrout** [comment]
problem fixed after restarting my laptop :thinking_face:

**Comment by katekate902** [comment]
have just met the same error when updating to RN 0.59.10

**Comment by chathuraSupun** [comment]
same issue when updating to RN 0.59.10 and even after restarting not working

**Comment by MIFind** [comment]
problem fixed after restarting my laptop, too 😀....

but , why

**Comment by kongyuyu** [comment]
Restart worked.

**Comment by IkeyBenz** [comment]
RN@0.59.9 Restarting my computer fixed the problem. No idea why, pretty upset about it

**Comment by mmustafaozdemir** [comment]
Restart worked :)

**Comment by wincod75** [comment]
Restart worked for me as well...

**Comment by frederickjjoubert** [comment]
I tried all 4 steps at the top, restarting **didn't** work for me :(

**Comment by veeramani-arthanari** [comment]
@frederickjjoubert , Install `react-native-clean-project` and try.

```
yarn add -D react-native-clean-project

react-native clean-project-auto
```

**Comment by camilo86** [comment]
Restarting my mac worked fam! 🔥😆

**Comment by danielsotopino** [comment]
leaving and reentering my house worked perfectly !!

**Comment by gsmith77** [comment]
Restarting my computer worked perfectly.

**Comment by mmmoussa** [comment]
In case anyone ends up here and doesn't want to restart their laptop, running `rm -rf $TMPDIR/metro-*` and `watchman watch-del-all` were sufficient for me

**Comment by nathanaelmbale** [comment]
For me i did not import properly .Refer from examples on their [npm](https://www.npmjs.com/package/react-native-heroicons) page
Here is what gave an error
`import { SearchIcon } from 'react-native-heroicons'
`
Here is what works
`import { SearchIcon } from 'react-native-heroicons/outline'
`

**Comment by GMhafeez** [comment]
restart still worked in 2023
