### ISSUE TITLE
Image styling props breaks image

### ISSUE THREAD

**Issue by SamuelTrew** [facebook/react-native#25391]
React Native version:

React Native Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
      CPU: (8) x64 Intel(R) Core(TM) i7-8705G CPU @ 3.10GHz
      Memory: 6.99 GB / 15.42 GB
      Shell: 5.4.2 - /usr/bin/zsh
    Binaries:
      Node: 8.16.0 - /usr/bin/node
      npm: 6.9.0 - /usr/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

## Steps To Reproduce

1. Create a standard react native screen with an Image and give it a style
2. However, this is not consistent so may not be easily reproducible

Describe what you expected to happen:
I expected my image to be at a good size without any cropping or anything just as is with most of the rest of the project

Snack, code example, or link to a repository:

import React from "react";
import {
   Image,
   StyleSheet,
   View,
   Text
} from "react-native";

export default class Entry extends React.Component {
   static navigationOptions = {
      title: 'Entry'
   };

   render() {
      const {navigate} = this.props.navigation;
      return(
         <>
            <View style={styles.centre}>
               <Image style={styles.title} source={require('../assets/Page_1.png')} />
            </View>
         </>
      )
   }

}

styles = StyleSheet.create({
   title: {
      justifyContent: 'center',
      alignItems: 'center',
      height: undefined,
      width: undefined,
      resizeMode: 'contain',
      flex: 1,
   },
   centre: {
      justifyContent: 'center',
      alignItems: 'center',
   },

});

Essentially what happens is that when I give my image a style it breaks and cuts off the top and bottom of the image while not sizing it correctly.
What's even weirder is that even if I remove all styling from the "title" style the styling remains constant (while still having style={styles.title}), I can even remove the styling from the view above and the same happens.

However, if I remove the style as a props then it is all okay and the image sizes up fine.
e.g.
<Image source={require('../assets/Page_1.png')} />

**Comment by ecreeth** [comment]
@SamuelTrew You can not use **`undefined`** as a value in the **width** and **height** properties. You can not use the **`flex`** property in the Image component either. See [here](https://facebook.github.io/react-native/docs/image-style-props#props), the Image style props

**Comment by SamuelTrew** [comment]
> @SamuelTrew You can not use **`undefined`** as a value in the **width** and **height** properties. You can not use the **`flex`** property in the Image component either. See [here](https://facebook.github.io/react-native/docs/image-style-props#props), the Image style props

I've been using it fine throughout the rest of the project fine to help dynamically style my images.

And anyway, it still doesn't matter as when I remove all styling from the stylesheet style it still causes the image issues

**Comment by kelset** [comment]
It seems that you are using Expo and an old version of React Native, can you provide a repro with 0.60 rc?
