### ISSUE TITLE
process.env.NODE_ENV is undefined

### ISSUE THREAD

**Issue by FunkyLambda** [facebook/react-native#25398]
Sorry but have lost enough work hours thanks to this, to follow the repro process. The existing issue was closed: https://github.com/facebook/react-native/issues/13005

Re-open it, I'm having the same problem. Am using `babel-plugin-transform-inline-environment-variables` as was suggested in one of the comments.

**Issue**
Doing an `export NODE_ENV=development` from my Mac terminal followed by a `react-native run-ios` results in an undefined `process.env.NODE_ENV` when the app runs; verified via Chrome debugger.

**Relevant package versions:**
react-native": "0.58.6"
babel-cli": "^6.26.0"
babel-core": "^7.0.0-bridge.0"
babel-plugin-transform-inline-environment-variables": "^6.8.0" 

**babel.config.js**
```
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  env: {
    production: {
      plugins: ['transform-remove-console']
    }
  },
  plugins: [
    [
      'transform-inline-environment-variables',
      {
        include: ['NODE_ENV']
      }
    ]
  ]
}
```

**Environment:**
`[skip envinfo]`. Easily inferred from info already provided. Inclusion of this will make the issue unnecessarily long.

**Comment by JohnTheo13** [comment]
I know it's wrong, but it works:
`
const { envVar } = process.env; 
if (envVar.NODE_ENV === "development") // do something
`
