### ISSUE TITLE
Chopping null when sending data using websocket in react-native.

### ISSUE THREAD

**Issue by Michal16511** [facebook/react-native#25394]
In my application I'm using stomp protocol to communicate with other devices. Stomp require to put null sign on the end of each message, which we want to send. The issue in react-native is when I send stomp message in production mode, then react-native removes null sign from the message and because of that I can't communicate using stomp. Everything works fine in debug mode, but the issue is in release mode. I know from react-native documentation that react-native in debug use v8 engine, but in release mode use javaScriptCore. Is the issue placed in js engine or react-native implementation? Can I do something on my own to solve this issue? So far I did a lot of work to implement my app using react-native and now moving from react-native to another framework or language will be a big disappointment for me.

React Native Environment Info:
System:
OS: macOS 10.14 Mojave
react: 16.8.3
react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 59.0
expo: 33.0.3
stompjs:  2.3.3

**Comment by dulmandakh** [comment]
Only remote debug run your JS code in V8 in Chrome, otherwise it'll use JSC. If it work in debug (not remote) mode then it's not JSC problem.

**Comment by ericschaal** [comment]
More info here: https://stomp-js.github.io/workaround/stompjs/rx-stomp/ng2-stompjs/2019/06/10/react-native-null-chopping-issue.html

**Comment by Michal16511** [comment]
@ericschaal Unfortunately this issue is placed in react-native :(
