### ISSUE TITLE
Fixing inverted FLatList

### ISSUE THREAD

**Issue by Sharcoux** [facebook/react-native#25390]
I'm creating an issue because I tried everything else without success.

I'm ready to fix the known issue about the inverted flatList and I made a PR: https://github.com/facebook/react-native/pull/23632

I was locked because things needed to be fixed in Yoga. I think that I successfully fixed things there, and I am now trying to continue the PR.

In order to do so, I rebased my changes onto the head of master, but I don't succeed to build such a version. I have these errors:

```
/flatlist/android/app/src/main/java/com/flatlist/MainApplication.java:5: error: cannot find symbol
import com.facebook.react.ReactApplication;
flatlist/android/app/src/main/java/com/flatlist/MainApplication.java:6: error: cannot find symbol
import com.facebook.react.ReactNativeHost;
flatlist/MainApplication.java:14: error: cannot find symbol
public class MainApplication extends Application implements ReactApplication {
flatlist/android/app/src/main/java/com/flatlist/MainApplication.java:16: error: cannot find symbol
  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
flatlist/android/app/src/main/java/com/flatlist/MainApplication.java:36: error: cannot find symbol
  public ReactNativeHost getReactNativeHost() {
flatlist/android/app/src/main/java/com/flatlist/MainApplication.java:16: error: cannot find symbol
  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
flatlist/android/app/src/main/java/com/flatlist/MainApplication.java:35: error: method does not override or implement a method from a supertype
flatlist/android/app/src/main/java/com/flatlist/MainActivity.java:5: error: MainActivity is not abstract and does not override abstract method getPackages() in ReactActivity
public class MainActivity extends ReactActivity {
```

I tried to ask about it on react-native on discord, I tried to ask in the PR, but apparently, nobody seems to understand how react-native is built and how to test some changes made in the repo into a dummy project.

If someone that ever participated to react-native could help me finish that PR it would be really great for the project I think.

## React Native version:

info Fetching system and libraries information...
System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz
    Memory: 513.59 MB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.12.0 - ~/.nvm/versions/node/v10.12.0/bin/node
    Yarn: 1.15.2 - ~/.yarn/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.12.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 23.0.3, 25.0.2, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.3, 28.0.3
      System Images: android-27 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.0 AI-171.4443003
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.3 => 16.8.3 
    react-native: git+ssh://git@github.com:Sharcoux/react-native => 1000.0.0 
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Steps To Reproduce

1. Create a dummy project (with `create-react-native-app` or other) using the master branch of react-native as react-native dependency:
`"react-native": "facebook/react-native"`
2. yarn install
3. yarn start
4. react-native run-android

```
error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
/Users/francoisbillioud/Documents/Tests/flatlist/android/app/src/main/java/com/flatlist/MainApplication.java:5: error: cannot find symbol
import com.facebook.react.ReactApplication;
                         ^
  symbol:   class ReactApplication
  location: package com.facebook.react
/Users/francoisbillioud/Documents/Tests/flatlist/android/app/src/main/java/com/flatlist/MainApplication.java:6: error: cannot find symbol
import com.facebook.react.ReactNativeHost;
                         ^
  symbol:   class ReactNativeHost
  location: package com.facebook.react
/Users/francoisbillioud/Documents/Tests/flatlist/android/app/src/main/java/com/flatlist/MainApplication.java:14: error: cannot find symbol
public class MainApplication extends Application implements ReactApplication {
                                                            ^
  symbol: class ReactApplication
/Users/francoisbillioud/Documents/Tests/flatlist/android/app/src/main/java/com/flatlist/MainApplication.java:16: error: cannot find symbol
  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
                ^
  symbol:   class ReactNativeHost
  location: class MainApplication
/Users/francoisbillioud/Documents/Tests/flatlist/android/app/src/main/java/com/flatlist/MainApplication.java:36: error: cannot find symbol
  public ReactNativeHost getReactNativeHost() {
         ^
  symbol:   class ReactNativeHost
  location: class MainApplication
/Users/francoisbillioud/Documents/Tests/flatlist/android/app/src/main/java/com/flatlist/MainApplication.java:16: error: cannot find symbol
  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
                                                       ^
  symbol:   class ReactNativeHost
  location: class MainApplication
/Users/francoisbillioud/Documents/Tests/flatlist/android/app/src/main/java/com/flatlist/MainApplication.java:35: error: method does not override or implement a method from a supertype
  @Override
  ^
/Users/francoisbillioud/Documents/Tests/flatlist/android/app/src/main/java/com/flatlist/MainActivity.java:5: error: MainActivity is not abstract and does not override abstract method getPackages() in ReactActivity
public class MainActivity extends ReactActivity {
       ^
8 errors
```

## Describe what you expected to happen:

Expected to build without error

## Snack, code example, or link to a repository:

https://github.com/Sharcoux/flatlist

**Comment by Sharcoux** [comment]
How can I get the "Resolution: Needs More Information" label removed?

**Comment by dblachut-adb** [comment]
Looks like you have missed some information from their template (at least that is what react-native-bot have written).

Did you try at first build from react-native sources instead of your repo? Did you follow this guide: https://github.com/facebook/react-native/wiki/Building-from-source ?
