### ISSUE TITLE
TextInput can't be focused when 2 Text inputs in the same row.

### ISSUE THREAD

**Issue by sarykemmoun** [facebook/react-native#25396]
Hello.
I'm trying to have 2 text inputs with flexDirection:'row' but the second field cannot be focused.
Please see the incoming screenshot. The 'Last Name' field can't be focused on.

![Screenshot from 2019-06-25 21-58-38](https://user-images.githubusercontent.com/28590349/60126153-0964cb80-9796-11e9-95b2-8648c28c618c.png)

React Native version:
59.9

## Steps To Reproduce
See the coming code.

Snack, code example, or link to a repository:

this is my render
```
    render() {
        const { inputStyle } = styles;
        const { fName, lName, phone, setLname, setPhone } = this.props.loginStore;

        return <View style={{ alignItems: 'center', marginVertical: 80 }}>
            <View style={{ flexDirection: 'row', justifyContent: 'space-between', marginHorizontal: 20, width: DEVICE_WIDTH - 40 }}>
                <TextInput value={fName} onChangeText={this.setFname.bind(this)} placeholder={I18n.t('Fname')} placeholderTextColor={lightGray} style={inputStyle} />
                <TextInput value={lName} onChangeText={txt => setLname(txt)} placeholder={I18n.t('Lname')} placeholderTextColor={lightGray}  style={inputStyle} />
            </View>
            <TextInput value={phone} onChangeText={txt => setPhone(txt)} placeholder={I18n.t('phone')} placeholderTextColor={lightGray} style={{ ...inputStyle, width: DEVICE_WIDTH - 40 }} />
        </View>
    }
```
When I removed the `flexDirection: 'row'` it worked. 

And here is the style object:
```
    inputStyle: {
        elevation: 1,
        borderRadius: 15,
        borderColor: 'transparent',
        width: (DEVICE_WIDTH - 60) / 2,
        height: 52,
        marginBottom: 20,
        paddingLeft: 15,
        fontSize: 17,
        backgroundColor: white
    }
```
Any help will be appreciated.

**Comment by Khlyl** [comment]
هذا فيس بوك لي وانتم من دخل خلسة للأمير الرجاء الخروج انا لا اريد احد معي انا لم اشترك مع أحد في ايميل

الحصول على Outlook for Android<https://aka.ms/ghei36>

________________________________
