### ISSUE TITLE
FlatList can't pull-to-refresh with alwaysBounceVertical={false}

### ISSUE THREAD

**Issue by jenskuhrjorgensen** [facebook/react-native#25408]
When setting `alwaysBounceVertical={false}` and the list contains so few items that it is unscrollable (content is smaller than the list/scroll view itself), it is not possible to pull-to-refresh even though `onRefresh` and `refreshing` are set according to [documentation](https://facebook.github.io/react-native/docs/0.59/flatlist). If `alwaysBounceVertical={true}` is set pull-to-refresh works as expected. 

(`alwaysBounceVertical` is an iOS-only prop, so it is only tested on iOS)

The following code produces the behaviour:

```
import * as React from 'react';
import {Component} from 'react';
import {FlatList, Text} from "react-native"

export class MyListView extends Component {
    render() {
        return (
            <FlatList
                data={[{key: 'a'}, {key: 'b'}]}
                renderItem={({item}) => <Text>{item.key}</Text>}
                alwaysBounceVertical={false}
                onRefresh={() => console.log("onRefresh")}
                refreshing={false}
            />
        )
    }
}
```

React Native version:

```
info
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
      Memory: 328.56 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 19, 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.3, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.3, 27.0.3, 28.0.0, 28.0.0, 28.0.2, 28.0.3
        System Images: android-19 | Google APIs ARM EABI v7a, android-19 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.9 => 0.59.9
    npmGlobalPackages:
      react-native-cli: 2.0.1
```
## Steps To Reproduce

1. Run above code or open below Expo Snack.
2. Pull to refresh
3. You can't

Describe what you expected to happen:
It should be possible to pull-to-refresh, even though `alwaysBounceVertical={false}`.

Snack, code example, or link to a repository:
https://snack.expo.io/@jenskuhr/787a8a

**Comment by AntoineDoubovetzky** [comment]
I guess that makes sense.
I don't know if we should update documentation to make clear that `alwaysBounce*` prop needs to be true in order for the pull to refresh to work or if we should force the `alwasBounce*` value to true when there is a `onRefresh` prop.

**Comment by jenskuhrjorgensen** [comment]
@AntoineDoubovetzky Thanks for your answer. Both suggested approaches are reasonable. Personally, I prefer the second approach (forcing `alwaysBounce` to true when there is an `onRefresh` prop).

**Comment by AntoineDoubovetzky** [comment]
I can't really take the decision myself. What do you think @cpojer @hramos ?

**Comment by AntoineDoubovetzky** [comment]
Ping @cpojer @hramos
What are your thoughts on this ? Maybe there is another solution that's better ?
