### ISSUE TITLE
Half black curve screen on startup - before splash screen

### ISSUE THREAD

**Issue by ImAbhishekTomar** [facebook/react-native#25405]
Hi Team,

overtime on startup my app is showing this black screen and after this my app is stack

React Native version:

> 
>   info 
>   React Native Environment Info:
>     System:
>       OS: macOS 10.14.5
>       CPU: (4) x64 Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz
>       Memory: 159.13 MB / 4.00 GB
>       Shell: 3.2.57 - /bin/bash
>     Binaries:
>       Node: 10.15.3 - /usr/local/bin/node
>       npm: 6.9.0 - /usr/local/bin/npm
>       Watchman: 4.9.0 - /usr/local/bin/watchman
>     IDEs:
>       Xcode: /undefined - /usr/bin/xcodebuild
>     npmPackages:
>       react: 16.8.3 => 16.8.3 
>       react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
>     npmGlobalPackages:
>       react-native-cli: 2.0.1
> 
> 

Device : Iphone 10 IOS 13 Beta

## Steps To Reproduce

I don't know ho to reproduce... I tried but I have not understand why this is happing..  

Describe what you expected to happen:

Snack, code example, or link to a repository:
![WhatsApp Image 2019-06-26 at 7 16 33 PM](https://user-images.githubusercontent.com/6933841/60175901-72584c00-9847-11e9-9f4b-3e874d69a6c2.jpeg)
![WhatsApp Image 2019-06-26 at 7 16 34 PM (1)](https://user-images.githubusercontent.com/6933841/60175903-72584c00-9847-11e9-85b1-d29027f3ba18.jpeg)
![WhatsApp Image 2019-06-26 at 7 16 34 PM](https://user-images.githubusercontent.com/6933841/60175905-72f0e280-9847-11e9-9e6b-967267e6ddb6.jpeg)

**Comment by IAmAbhishekTomar** [comment]
After refreshing my app multipal time using Expo app.... error has been changed... and after hitting  OK button now my app is woking..... but I am worried becuae I din't k now why this is happing.  

![WhatsApp Image 2019-06-26 at 7 37 25 PM](https://user-images.githubusercontent.com/6933841/60176869-1a6f1480-984a-11e9-866f-3b63575edb37.jpeg)
![WhatsApp Image 2019-06-26 at 7 37 26 PM](https://user-images.githubusercontent.com/6933841/60176870-1a6f1480-984a-11e9-9c63-2926b431e831.jpeg)
