### ISSUE TITLE
Undefined is not an object (evaluating 'f.Modal.propTypes.animationType')

### ISSUE THREAD

**Issue by adikshirsagar** [facebook/react-native#25402]
I have upgraded my project from 0.55.4 to 0.59.9 after upgrading I get this red screen on installing debug apk, please help!

here is my package.json:

{
  "name": "Vistabee",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "@babel/preset-env": "^7.4.5",
    "axios": "^0.18.0",
    "babel-preset-flow": "^6.23.0",
    "fetch-intercept": "^2.2.3",
    "firebase": "^5.0.2",
    "react": "16.6.3",
    "react-native": "^0.59.3",
    "react-native-background-timer": "^2.0.1",
    "react-native-collapsible": "^0.11.3",
    "react-native-datepicker": "^1.7.2",
    "react-native-drawer": "^2.5.0",
    "react-native-elements": "^0.19.1",
    "react-native-fcm": "15.0.2",
    "react-native-google-places-autocomplete": "^1.3.9",
    "react-native-interactive-image-gallery": "^0.1.2",
    "react-native-maps": "git://github.com/react-native-community/react-native-maps.git#master",
    "react-native-maps-directions": "^1.6.0",
    "react-native-modal-selector": "0.0.27",
    "react-native-router-flux": "^4.0.0-beta.31",
    "react-native-stripe-api": "^0.1.0",
    "react-native-toaster": "^1.2.2",
    "react-native-vector-icons": "^4.6.0",
    "react-native-video": "^2.2.0",
    "react-native-video-controls": "^2.2.1",
    "react-navigation": "^2.0.0-rc.9",
    "react-redux": "^5.0.7",
    "redux": "^3.7.2",
    "redux-thunk": "^2.3.0",
    "relative-date": "^1.1.3",
    "toggle-switch-react-native": "^2.0.2"
  },
  "devDependencies": {
    "@babel/core": "^7.4.0",
    "@babel/runtime": "^7.4.2",
    "@react-native-community/eslint-config": "^0.0.3",
    "babel-jest": "^24.5.0",
    "babel-plugin-module-resolver": "3.1.1",
    "babel-preset-react-native": "^4.0.1",
    "eslint": "^5.16.0",
    "jest": "^24.5.0",
    "metro-react-native-babel-preset": "^0.53.1",
    "react-test-renderer": "16.8.3"
  },
  "jest": {
    "preset": "react-native"
  }
}

![error](https://user-images.githubusercontent.com/8086876/60169033-8ab66f80-9823-11e9-83d4-e6c2309769d3.jpeg)

React Native Environment Info:
    System:
      OS: Linux 4.13 Fedora 25 (Twenty Five) 25 (Twenty Five)
      CPU: (4) x64 Intel(R) Core(TM) i5 CPU       M 520  @ 2.40GHz
      Memory: 118.55 MB / 5.62 GB
      Shell: 4.3.43 - /bin/bash
    Binaries:
      Node: 10.6.0 - /usr/local/bin/node
      Yarn: 1.9.2 - /usr/local/bin/yarn
      npm: 6.2.0 - /usr/local/bin/npm
    SDKs:
      Android SDK:
        API Levels: 23, 25, 26, 27
        Build Tools: 23.0.1, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.1, 28.0.3
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: ^0.59.3 => 0.59.9 
    npmGlobalPackages:
      react-native-rename: 2.2.2

![error2](https://user-images.githubusercontent.com/8086876/60174308-644a0180-982e-11e9-900c-207998ad4e10.jpeg)

**Comment by adikshirsagar** [comment]
app crashes when install apk.

**Comment by adikshirsagar** [comment]
"react-native-modal-selector": "0.0.27" 
this package causing this problem after upgrading to RN 0.59.3 from RN 0.55.4

**Comment by duannhqb** [comment]
hi, i also had issue similar. help me !!!

**Comment by ferryhinardi** [comment]
I got the same thing. any update for this? this case only show in android variant=release.

**Comment by adikshirsagar** [comment]
this issue is related to modal, modal version should compatible to react native version here.
In my case the package react-native-modal-selector was not compatible with new react native version.

**Comment by yusuf987** [comment]
updating my react-native-simple-dialogs to latest worked for me

**Comment by NarendraSingh88** [comment]
> "react-native-modal-selector": "0.0.27"
> this package causing this problem after upgrading to RN 0.59.3 from RN 0.55.4

Along with this, I had to update other related dependencies, which were using react-native-modal internally.
