### ISSUE TITLE
secureTextEntry= false cause text to disappear on iOS 

### ISSUE THREAD

**Issue by evansherry** [facebook/react-native#25419]
React Native version:
0.59.9

## Steps To Reproduce
The description is as follows, the content has been entered in TextInput, switch secureTextEntry = {false}, then cancel the keyboard, open the keyboard input again will lose the initial input, when you input, the onChangeText method callback an empty string ("" ), this happens on iOS.

Describe what you expected to happen:
I hope that like android, typing again will not overwrite the current text.

Snack, code example, or link to a repository:

code
``````
<TextInput
                    style={styles.pwdTextInput}
                    selectionColor= '#05A799'
                    autoCapitalize = 'none'
                    keyboardType = 'numeric'
                    maxLength = {6}
                    placeholder = {getString('pls_enter_unlock_password')}
                    placeholderTextColor = '#8F9393'
                    onChangeText={(text) => {
                        print("InputPwdView  setState", text, this.state.text);
                        this.setState({text});
                        this.props.onChangeText(text);
                    }}
                    numberOfLines={1}
                    clearTextOnFocus = {false}
                    secureTextEntry={!this.state.showPwd}
                    // secureTextEntry={true}
                    value={this.state.text}
                    underlineColorAndroid = 'transparent'
                />
``````
style
``````
 pwdTextInput: {
        flex: 1,
        height: 50,
        fontSize: FontSizeConst.FontOf16,
        paddingHorizontal: 26,
        // backgroundColor: 'blue'
    },
``````

I tried some dirty methods, the effect is not good, can you help me?

**Comment by mdstaff** [comment]
I noticed a similar issue was opened and closed which might be related to this: https://github.com/facebook/react-native/issues/12939

**Comment by evansherry** [comment]
I think that the problem should not be closed in a state that has not yet been resolved. In fact, there are still many people who have encountered this problem. On the native ios, the security password will not cause the current password to be cleared.
