### ISSUE TITLE
App security test reports Insecure API for React Native iOS App -  Binary Analysis (IPA)

### ISSUE THREAD

**Issue by kamalyzl** [facebook/react-native#25414]
after a static analysis performed on the ipa obtained from the compilation from native react,
<img width="1034" alt="Captura de pantalla 2019-06-27 a la(s) 11 04 38 a  m" src="https://user-images.githubusercontent.com/32285958/60282004-96f60780-98cb-11e9-8fb8-28320a1838b0.png">

- Prohibited binary API (s)
The binary may contain the following prohibited APIs
_strcpy, _strncat, _strlen, _alloca, _printf, _sscanf, _stat, _memcpy, _fopen, _vsnprintf, _gets.

- Binary makes use of the following weak HASH APIs
The binary can use the following weak hash APIs CC_SHA1, CC_MD5.

- Binary make use of the insecure Random Function(s)
The binary can use the following unsafe random functions _random.

- Binary make use of malloc Function
The binary can use the malloc function instead of calloc.

This is the result of a static analysis of the IPA file of an iOS-based application

Version react info
info 
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
      Memory: 82.13 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.3 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.2, 28.0.3
        System Images: android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.8 => 0.59.8

Versions of current libraries.
    "react-native-android-sms-listener": "^0.7.0",
    "react-native-calendars": "^1.115.0",
    "react-native-camera": "^2.7.0",
    "react-native-contacts": "^4.0.2",
    "react-native-dotenv": "^0.2.0",
    "react-native-firebase": "5.3.1",
    "react-native-gesture-handler": "^1.2.1",
    "react-native-languages": "^3.0.2",
    "react-native-maps": "0.24.2",
    "react-native-qrcode": "^0.2.7",
    "react-native-share": "^1.1.3",
    "react-native-snap-carousel": "^3.7.5",
    "react-native-svg": "^9.4.0",
    "react-native-swipeout": "^2.3.6",
    "react-native-view-shot": "^2.6.0",
    "react-navigation": "3.9.1",
    "react-redux": "^7.0.3",
    "readdirp": "^3.0.1",
    "redux": "^4.0.1",
    "redux-actions": "^2.6.5",
    "rn-sliding-up-panel": "^2.2.0",
    "simple-grep": "0.0.1",
    "yup": "^0.27.0"
 
How could you change the variables found by those suggested by apple from react native?
https://developer.apple.com/library/archive/documentation/Security/Conceptual/SecureCodingGuide/Articles/BufferOverflows.html#//apple_ref/doc/uid/TP40002577-SW1

Thanks

**Comment by kamalyzl** [comment]
@react-native-bot ready

**Comment by Zahikusa** [comment]
I have a very similar problem after running a scan on my .ipa file.
Below is my 'react-native info' output:

![image](https://user-images.githubusercontent.com/32354342/62463762-23c59800-b78b-11e9-89a3-376389fe03f1.png)

**Comment by mayurssoni2456** [comment]
Same issue .. any thoughts?

**Comment by DevAndroidIOS** [comment]
Same this issue, but I used swift -> any thoughts?

**Comment by ebiba-dp** [comment]
Any update for this?

**Comment by ManigandanRaamanathan** [comment]
@kamalyzl any update?

**Comment by dlowder-salesforce** [comment]
A quick scan indicates that a lot of the `strcpy()` usage comes from Boost.

```sh
$ egrep -r strcpy third-party
third-party/boost_1_63_0/boost/compatibility/cpp_c_headers/cstring:  using ::strcpy;
third-party/boost_1_63_0/boost/config/stdlib/stlport.hpp:// and strcmp/strcpy don't get imported either ('cos they are macros)
third-party/boost_1_63_0/boost/config/stdlib/stlport.hpp:#ifdef strcpy
third-party/boost_1_63_0/boost/config/stdlib/stlport.hpp:#  undef strcpy
third-party/boost_1_63_0/boost/config/stdlib/stlport.hpp:namespace std{ using _STLP_VENDOR_CSTD::strcmp; using _STLP_VENDOR_CSTD::strcpy; }
third-party/boost_1_63_0/boost/interprocess/detail/xsi_shared_memory_device.hpp:      std::strcpy(info->names[target_entry].buf, shmname);
third-party/boost_1_63_0/boost/interprocess/detail/xsi_shared_memory_device.hpp:            std::strcpy(info->names[target_entry].buf, shmname);
third-party/boost_1_63_0/boost/interprocess/detail/xsi_shared_memory_device.hpp:               std::strcpy(info->names[target_entry].buf, shmname);
third-party/boost_1_63_0/boost/interprocess/detail/os_file_functions.hpp:      std::strcpy(buffer, "/tmp");
third-party/boost_1_63_0/boost/asio/ssl/impl/context.ipp:    strcpy_s(buf, size, passwd.c_str());
third-party/boost_1_63_0/boost/asio/detail/impl/socket_ops.ipp:          strcpy_s(name, namelen, raw_name.c_str());
third-party/boost_1_63_0/boost/asio/detail/impl/socket_ops.ipp:inline void gai_strcpy(char* target, const char* source, std::size_t max_size)
third-party/boost_1_63_0/boost/asio/detail/impl/socket_ops.ipp:  strcpy_s(target, max_size, source);
third-party/boost_1_63_0/boost/asio/detail/impl/socket_ops.ipp:      gai_strcpy(canon, hptr->h_name, canon_len);
third-party/boost_1_63_0/boost/asio/detail/impl/socket_ops.ipp:      gai_strcpy(aihead->ai_canonname, search[0].host, canonname_len);
third-party/boost_1_63_0/boost/asio/detail/impl/socket_ops.ipp:        gai_strcpy(host, hptr->h_name, hostlen);
third-party/boost_1_63_0/boost/asio/detail/impl/socket_ops.ipp:        gai_strcpy(serv, sptr->s_name, servlen);
...
```

**Comment by pratikg711** [comment]
Any update?

**Comment by ganesh-sankey** [comment]
@pratikg711 Any update? facing same issue

**Comment by annkiitagrawaal-gep** [comment]
Any updates on this?

**Comment by sambheaduplabs** [comment]
I've also had this issue.

**Comment by yogendrajs** [comment]
Hey everyone, any updates on this?

**Comment by AmorimRob** [comment]
Any update? Same problem here

Reported by MobSF tool

**Comment by cemocanon** [comment]
Hey everyone, any updates on this?

**Comment by thitoo-yf** [comment]
any update on this? we have faced this issue after scanning with MOBSF.

**Comment by tkud04** [comment]
Any update on this? We are facing a similar issue on React Native 0.70.5

**Comment by sebastianpenamatrix** [comment]
Hi @yogendrajs can you share how did you use Appdome to solved this issue please?

**Comment by yogendrajs** [comment]
Yeah, you’ll have to buy a plan from Appdome and rest are the steps on
their portal to get your app wrapped up with their security features.

**Comment by HannahCarney** [comment]
Has this been fixed?

**Comment by tajinder-06** [comment]
same issue version 0.73.3
