### ISSUE TITLE
Modal does not close when setting state to false IOS

### ISSUE THREAD

**Issue by DarkAlbania** [facebook/react-native#25410]
Modal does not close when its visible state is set to false inside an async function.
this only happerns in IOS, in Android there are not problems

## Steps To Reproduce

1.Set state to loading = true in async method
2.Set state to loading = false in try if request succeeds of fails

sync _www(walletId){
        this.walletModal.setVisibleState(false);
        this.setState({loading: true});

        const {fature} = this.state;
        const requestObj = {
            walletId: walletId,
        }

        try {
            let response = await this.api.asdf(requestObj);
            
            await this._updateComponent();
            this.setState({loading: false});
            ShowSuccesToast("Fatura u pagua me sukses !");
            this.props.navigation.push('TransactionSuccessful', {vlera: fature.totalAmt, sherbimi: 'asdfasdf'});
            //TODO show transaction details
        } catch (error) {
            this.setState({loading: false});
            this.props.navigation.push('TransactionFailed', {error: error});
            console.log('error' + JSON.stringify(error));

        }
    }

**Comment by lzj1995822** [comment]
same issue
