### ISSUE TITLE
WebView can load local htmlfile ,But can't load local script file

### ISSUE THREAD

**Issue by Ruanyang2015** [facebook/react-native#25413]
### WebView can load local htmlfile ,But can't load local script file

![image](https://user-images.githubusercontent.com/13889247/60261877-76e83780-990f-11e9-89a6-e2e39b58fa7b.png)

- **React Native Code**

![image](https://user-images.githubusercontent.com/13889247/60262098-fa098d80-990f-11e9-855f-393187f50fa1.png)

### React Native version:
     "react": "16.8.3",
    "react-native": "0.59.9",
    "react-native-webview": "^5.12.0"

## Steps To Reproduce

1. 

I want to load local html file that include js src like this---<script type="text/javascript" src="test.js"></script>

2. 
But it can't load the contents of js that content is "alert("郭跃");"

**Comment by dulmandakh** [comment]
Please file an issue at https://github.com/react-native-community/react-native-webview

**Comment by Ruanyang2015** [comment]
**I use the WebView from react-native to be exactly the same error.**

**Comment by dulmandakh** [comment]
WebView is been deprecated for a while, and removed in 0.60. Please use react-native-webview, and file an issue there.
