### ISSUE TITLE
iOS ends TCP connection after receiving response

### ISSUE THREAD

**Issue by Charminz** [facebook/react-native#25422]
We have an external device to which our app sends a PUT request. On specific conditions the device sends successful response with data requesting for additional information. After the external device does that, it should stay waiting for the response (TCP connection should not be ended).

On android device/emulator it works as expected. But on iOS device/simulator the connection is ended after the external device sends a response to our first request. While debugging with Wireshark we noticed that after the external device sends a response to our first request, the iOS app sends a FIN ACK packet to the device to end the connection. This doesn’t happen on android though.

We have tried to use axios, fetch and XMLHttpRequest for sending the requests to the device. Even tried adding keep-alive header.

What could we try to get it working as it should or what would be the source of the problem?

### Environment
React Native version 0.59.5
Axios version 0.18.1
Simulator’s iOS version 12.0

### React Native version
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
      Memory: 275.53 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/homebrew/bin/yarn
      npm: 6.7.0 - /usr/local/homebrew/bin/npm
      Watchman: 4.9.0 - /usr/local/homebrew/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.5 => 0.59.5
    npmGlobalPackages:
      react-native-cli: 2.0.1

### Steps to Reproduce
Unfortunately I can’t give specific example to reproduce it. You can look at “Expected Behavior” for the flow example how it should work.

### Expected Behavior
1. React Native’s app sends a http request to external device or server
2. Device sends back a response requesting for additional information and waits for an answer
3. App receives the response
4. App checks if the device is requesting for some additional info, if so then sends it to the device
5. Device processes the data that was sent by the app and sends a response to the app
6. App receives the final response
7. The connection is ended

### Actual Behavior
1. React Native’s app sends a http request to external device or server
2. Device sends back a response requesting for additional information and waits for an answer
3. App receives the response
4. App ends the connection with FIN ACK
5. Device stops the waiting process and goes into "default" mode

**Comment by dulmandakh** [comment]
I think this is expected behavior, or every connection must end with a response. Or you might consider using WebSocket, which doesn't close connection automatically after a response.
