### ISSUE TITLE
componentDidCatch doesn`t work 

### ISSUE THREAD

**Issue by UncleWang8898** [facebook/react-native#25420]
the componentDidCatch function doesn`t work.

React Native version:
"react": "16.8.3",
"react-native": "0.59.5"

## Steps To Reproduce

1.
2.

Describe what you expected to happen:
the componentDidCatch function doesn`t work.

**Comment by dulmandakh** [comment]
This issue is not really related to RN. Please read https://reactjs.org/docs/react-component.html#error-handling
