### ISSUE TITLE
[0.60.0-rc.3] react-native init stucked at installing required CocoaPods dependencies

### ISSUE THREAD

**Issue by isaaclem** [facebook/react-native#25435]
React Native version:
```
System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 365.26 MB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.4.0 - /usr/local/bin/node
    Yarn: 1.17.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      API Levels: 22, 23, 25, 26, 27, 28
      Build Tools: 25.0.2, 27.0.3, 28.0.3
      System Images: android-22 | ARM EABI v7a, android-22 | Intel x86 Atom, android-22 | Intel x86 Atom_64, android-22 | Google APIs ARM EABI v7a, android-22 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-Q | Google Play Intel x86 Atom
      Android NDK: 19.2.5345600
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.0-rc.3 => 0.60.0-rc.3
  npmGlobalPackages:
    react-native-cli: 2.0.1
```
## Steps To Reproduce

1. `rn init CodePush --version react-native@next`

Describe what you expected to happen:

Should show project init completion if it's completed, or show progress bar if it's installing?

**Comment by kelset** [comment]
Sorry, I don't understand - what is the issue?

If I run `react-native init RN060 --version react-native@next` it works. Have you installed [cocoapods](https://cocoapods.org/)?

**Comment by isaaclem** [comment]
![image](https://user-images.githubusercontent.com/32945572/60435149-60a5e880-9c3b-11e9-9306-8e21e6f84d71.png)

It keep stucked at this step

**Comment by kelset** [comment]
Ok, this seems to suggest that your issue is related to the CLI, so I suggest you open an issue there -> https://github.com/react-native-community/cli

**Comment by ivanignacio** [comment]
![Screen Shot 2019-07-03 at 2 28 28 PM](https://user-images.githubusercontent.com/9794886/60616231-0160e900-9d9f-11e9-8078-6a037235d8ee.png)

I just created a new project and I thought I had the same problem, but the reality is that you just have to wait. Once it finishes installing the required dependencies with that project, all of the next projects will be faster.

**Comment by Maskedheroe** [comment]
> ![Screen Shot 2019-07-03 at 2 28 28 PM](https://user-images.githubusercontent.com/9794886/60616231-0160e900-9d9f-11e9-8078-6a037235d8ee.png)
> 
> I just created a new project and I thought I had the same problem, but the reality is that you just have to wait. Once it finishes installing the required dependencies with that project, all of the next projects will be faster.

How long have you waited?????

**Comment by huqiliang** [comment]
@Maskedheroe But I waited until to time out.

**Comment by ivanignacio** [comment]
@Maskedheroe, the very first time I did it I canceled after 5 min. Next time I tried, I had to wait around 10 min (My computer is working slow lately) After those 10 min I waited, I haven't had any problem, every new project takes less than 2 min to setup.

**Comment by doKill** [comment]
this step i know , it's up to your net status , today i init project faster in company than my home.
