### ISSUE TITLE
TouchableOpacity not clickable with negative margin on Android

### ISSUE THREAD

**Issue by franciscop-sc** [facebook/react-native#25441]
When clicking on a `<TouchableOpacity />` element that a child of `<View />` but is rendered outside of this view, if and only if this parent view has a `backgroundColor` then the TouchableOpacity will not be clickable **in Android** ([see Snack](https://snack.expo.io/SJfRhWPlH)):

<table>
  <tr><th>Snack Reproduction</th><th>Android Simulator</th></tr>
  <tr>
    <td>
      <img width="600" src="https://user-images.githubusercontent.com/47550791/60411547-41419800-9c08-11e9-99a2-71a67ae968f9.gif" />
    </td>
    <td>
      <img width="600" src="https://user-images.githubusercontent.com/47550791/60411546-40a90180-9c08-11e9-8f75-bc07d8059124.gif" />
    </td>
  </tr>
</table>

```js
// Works - can click the circles
<View style={{ marginHorizontal: 50 }}>
  <Circle works style={{ marginLeft: -50 }} />
  <Circle works style={{ transform: [{ translateX: -50 }] }} />
  <Circle works style={{ position: 'relative', left: -50 }} />
</View>

// Broken - cannot click these circles
<View style={{ marginHorizontal: 50, backgroundColor: '#aaa' }}>
  <Circle style={{ marginLeft: -50 }} />
  <Circle style={{ transform: [{ translateX: -50 }] }} />
  <Circle style={{ position: 'relative', left: -50 }} />
</View>
```

React Native version:

react-native-cli: 2.0.1
react-native: 0.59.9

## Steps To Reproduce

1. Create a `<View>` with a backgroundColor.
2. Add a TouchableOpacity with some sort of displacement, so that it falls outside this parent View (but still within the screen).
3. Try to press it. There's no feedback and no event triggered.

Describe what you expected to happen:

You can click any `<TouchableOpacity />` element rendered within the screen.

Snack, code example, or link to a repository:

https://snack.expo.io/SJfRhWPlH

**Comment by Volksfeld** [comment]
All buttons worked fine on Snack, android.

**Comment by idocme** [comment]
Having the same issue. is there a way to solve it? or it's a bug and we need to wait for a fix?

**Comment by sungsong88** [comment]
I have the same issue... In my case, the button underneath the negative-margin-top button gets clicked. The click event just passes through...

**Comment by MamyChow** [comment]
+1 i have same issue on Android (IOS is working well), React-native: 0.61

**Comment by nohharri** [comment]
+1 Same issue Android (IOS also working fine), React-native 0.58

**Comment by basha777** [comment]
+1 Same issue android react-native 0.60.5

**Comment by antonKalinin** [comment]
+1 same issue on Android, React-Native: 0.61.3

**Comment by RobertBiberovic** [comment]
+1 same issue on Android when margin is negative, on iOS it works fine, React Native 0.59 (older version because of expo)

**Comment by franciscop-sc** [comment]
Hey thanks for the follow-up stale-bot, testing the above snack **in Android** still yields the same issue unfortunately, so this is pretty much not dead.

**Comment by CyrusZei** [comment]
well, the default value on `View` is `overflow: hidden;` so what I did was just overwrite it with `overflow: visible;` and it works

**Comment by artemkhalygov** [comment]
+1 same issue on Android, React-Native: 0.61.3

**Comment by TheMrZZ** [comment]
Still a problem today. Works also when a component has a margin big enough to be rendered outside its parent component, then the part of the view outside the parent component cannot be touched.

**Comment by yigithanyucedag** [comment]
+1

**Comment by PiperGuy** [comment]
+1

**Comment by rmrfmichael** [comment]
+1 This is also an issue when adding padding. It's pretty remarkable actually. It's like ... for no reason at all.

Good to know that this has been an open issue for nearly 1 year.

**Comment by fabriziobertoglio1987** [comment]
https://stackoverflow.com/a/10673572/11452286

![image](https://user-images.githubusercontent.com/24992535/83228584-dc2f5300-a186-11ea-916e-53f75a6f46e7.png)

this issue will not be fixed. Negative margin is not supported on Android. Use absolute layout.

**Comment by vigneshwaran-sh** [comment]
on absolute also not working

**Comment by franciscop-sc** [comment]
The documentation says [we can use CSS with React Native](https://reactnative.dev/docs/style) (except for the names changing to cammelCase).

So either the documentation is wrong and CSS is not supported, or this issue is valid and negative margins should be supported as in CSS. In any case I found this issue after many hours of debugging following the documentation so others will find this issue as well unless something is changed.

**Comment by fabriziobertoglio1987** [comment]
https://github.com/facebook/react-native/issues/27333#issuecomment-657566412

**Comment by franciscop-sc** [comment]
Still an issue stalebot :)

**Comment by velidan** [comment]
I have the same issue but even when I'm using the absolute positioning the button isn't clickable as well. It's really strange

**Comment by JeminiBo** [comment]
Just use translateY instead margin

**Comment by ZComwiz** [comment]
The correct way to do this is to wrap the TouchableOpacity in a parent view that does the offsetting work. It makes sense when you think about how React Native works. Touchable Opacity would be doing some touchable rectangle on the screen where it's positioned. It doesn't understand the styles. Encapsulating it in a <View style={margin: -50}>  or whatever you're trying to do will first nest the touchable object in a view that is correctly positioned.

**Comment by lagofvc** [comment]
Thanks @Velidan!   This was very helpful.  
I solved similarly by increasing parent height for Android!
Much appreciated!

**Comment by AishwaryaSurana** [comment]
Got a hack
Try Giving zIndex, It worked for me
```

 emailWrapper: {
    backgroundColor: 'red',
    marginBottom: -28,
    zIndex: 1,
  },
```

**Comment by marsk6** [comment]
I used `hitSlop` which solved my issue
```
<TouchableOpacity style={{ marginBottom: -4 }} hitSlop={{ bottom: 4 }}>
...
</TouchableOpacity>
```

**Comment by ahmad-amani** [comment]
+1

**Comment by alexander01202** [comment]
It's still an issue stalebot. Up to two years now not yet solved

**Comment by y471n** [comment]
Still an issue :(

**Comment by SaadBinWaheed-empglabs** [comment]
Still an issue

**Comment by mbordia-eightfold** [comment]
Did you guys tried importing TouchableOpacity from 'react-native-gesture-handler' instead ?
It did work for me.
