### ISSUE TITLE
Image component not rendering image from url properly

### ISSUE THREAD

**Issue by mbackermann** [facebook/react-native#25448]
The Image component is not rendering the image properly from the URL
`https://mav-fb.imgix.net/https%3A%2F%2Fcdn.hiremav.com%2F404.png?ixlib=rb-3.0.0&w=100&h=100&mask=ellipse&fit=focalpoint&fm=png32&s=e4ef2680df3f5f8e54548a827c5f0c44`

From the onError I got the message `Failed to load`
![Simulator Screen Shot - iPhone X - 2019-06-28 at 15 47 54](https://user-images.githubusercontent.com/5454847/60446755-675f3c00-9bf8-11e9-9a9b-e048f210e49f.png)

React Native version:
```
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 53.52 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.3.1 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 26, 28
        Build Tools: 28.0.3
        System Images: android-26 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5014246
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.9 => 0.59.9
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

## Steps To Reproduce
Add the following component:
```
<Image  resizeMode="contain" source={{uri: 'https://mav-fb.imgix.net/https%3A%2F%2Fcdn.hiremav.com%2F404.png?ixlib=rb-3.0.0&w=100&h=100&mask=ellipse&fit=focalpoint&fm=png32&s=e4ef2680df3f5f8e54548a827c5f0c44'}} />
```

Describe what you expected to happen:
Render the image properly without errors

Snack, code example, or link to a repository:
[https://snack.expo.io/@mbackermann/image-error](https://snack.expo.io/@mbackermann/image-error)

**Comment by ecreeth** [comment]
@mbackermann You need to provide a cleaner url. No weird symbols :1234:

**Comment by mbackermann** [comment]
Actually this is not the problem. I realized that although the URL is showing the image, it returns HTTP Status 403. This is probably the problem.

**Comment by ecreeth** [comment]
@mbackermann If you load the image, you will notice that the problem is that the server is returning an http 403 state.

![image](https://user-images.githubusercontent.com/20761166/60450022-f23f3700-9bf6-11e9-981e-355551b5989b.png)

**Comment by mbackermann** [comment]
It was the status code from the HTTP request that was returning 403.
