### ISSUE TITLE
Fetch in setInterval memory leak

### ISSUE THREAD

**Issue by nielsmadan** [facebook/react-native#25450]
React Native version: 0.59.9 (confirmed also exists in 0.60.0)

```
 System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 71.41 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.16.0 - ~/.nvm/versions/node/v10.16.0/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    Watchman: 4.7.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28
      Build Tools: 23.0.1, 23.0.2, 25.0.0, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.1, 28.0.3
      System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom, android-26 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.1 AI-173.4907809
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.0 => 0.60.0
```

## Steps To Reproduce

1. Call `setInterval` in a `componentDidMount`.
2. In the called function, make a fetch request.

Describe what you expected to happen:

Memory footprint stays constant.

What actually happens:

Memory keeps increasing. Tested on iOS simulator with release build. The reason I noticed this is that the app I'm building eventually runs out of memory in app store builds on device. The setup in the app is obviously more complicated (actually using `apollo-client` to make the request), but it seems to happen with this really simple case as well.

`App.js` code to use with the default app created by `react-native init`:

```
import React, {Component} from 'react';
import {Platform, StyleSheet, Text, View} from 'react-native';

type Props = {};
export default class App extends Component<Props> {
  timeout = null;

  componentDidMount() {
    this.timeout = setInterval(this.makeQuery, 2000); 
  }

  makeQuery = () => {
    fetch('https://ghibliapi.herokuapp.com/films/');
    fetch('https://ghibliapi.herokuapp.com/people/');
    fetch('https://ghibliapi.herokuapp.com/species/');
    fetch('https://ghibliapi.herokuapp.com/locations/');
    fetch('https://ghibliapi.herokuapp.com/vehicles/');
  }

  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.title}>Test setInterval memory issue.</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  title: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
});
```

Possible duplicate: https://github.com/facebook/react-native/issues/25216

I've also tried recursive `setTimeout`, which shows the same problem.

**Comment by dulmandakh** [comment]
Usually it takes some time before memory objects are garbage collected. 

What is the purpose of doing fetch every 2 seconds?

**Comment by nielsmadan** [comment]
I let this run for an hour, and the memory keeps increasing.

2 seconds is just for the reproduction. In the real app, we fetch every 20 seconds to always get the latest data. Eventually the app crashes, because it's out of memory.

**Comment by nielsmadan** [comment]
Here memory view on iOS at the start of the app (Release build configuration):

<img width="1135" alt="Screenshot 2019-07-02 15 37 21" src="https://user-images.githubusercontent.com/701154/60517883-ba142300-9ce0-11e9-85eb-d8037ca43b43.png">

And here after ~10 Minutes. You can see it goes to slightly every once in a while, but not even close to the starting level.

<img width="1137" alt="Screenshot 2019-07-02 15 46 50" src="https://user-images.githubusercontent.com/701154/60517890-bd0f1380-9ce0-11e9-9e8e-2148fbbc57ff.png">

**Comment by nielsmadan** [comment]
I also tried setting the interval to 10 seconds in the repo to make sure that this is not happening because the javascript engine is so busy doing fetch requests that it never has time to GC. If you do that, there are more GCs happening, but ultimately it still goes up.

**Comment by mrkacan** [comment]
I am still facing this issue on RN 60.
Platform: IOS and Android.

When i use 3 setInterval, application is crashing.

**Comment by majirosstefan** [comment]
wonderful !

**Comment by majirosstefan** [comment]
yes, bot, it seems that it is still problem

**Comment by christophermark** [comment]
For what it's worth, I experienced this and was able to reliably reproduce on a fresh React Native iOS app.

The issue seems to be with something underlying in JavaScriptCore where any `setInterval` or rerender leaks memory. On Android, you can switch your JavaScript engine to V8 and see a difference in memory consumption.

It all comes down to *garbage collection*, which seems to be the true issue. Garbage collection is done fairly infrequently using the JavaScriptCore bundled with iOS, and depending on how you set up your test app, it may never trigger. This ends up looking like a continual memory increase.

**Comment by FreddyPoly** [comment]
Is there any update on this ? Did you find a solution @nielsmadan ?

**Comment by nielsmadan** [comment]
@FreddyPoly No real solution, no.

**Comment by nielsmadan** [comment]
@christophermark I don't think the frequency of garbage collection is the issue. If that were the case, the memory consumption would go down to the starting level when garbage collection does happen. But as you can see in the graphs, that's not the case. This looks like an actual leak to me.
