### ISSUE TITLE
Use DrawerLayoutAndroid programmaticaly

### ISSUE THREAD

**Issue by stephane-r** [facebook/react-native#25458]
Hi community,

I would like use `DrawerLayoutAndroid` module on React-Native app. For use `openDrawer` programmaticaly, i use `useRef` hook.

On run this method, my Drawer isn't show, nothing is happening.

I use React Native v0.59.4.

## Steps To Reproduce

Use with Layout component : 

```
const Layout = ({ children }) => {
  let drawler = useRef(null);

  return (
    <DrawerLayoutAndroid
      drawerWidth={300}
      drawerPosition={DrawerLayoutAndroid.positions.Left}
      ref={drawler}
      renderNavigationView={() => (
          <View>
            <Text>Player render</Text>
            <Button onPress={() => drawler.current.closeDrawer()}>Close</Button>
          </View>
        )}>
     <View style={{ flex: 1 }}>
        <ScrollView>
          <View style={styles.container}>
            {children}
          </View>
        </ScrollView>
      </View>
    </DrawerLayoutAndroid>
  );
};
```

Is this module is deprecated ?

Thank you community !

**Comment by ecreeth** [comment]
@stephane-r `DrawerLayoutAndroid` is not deprecated. You can see an example [here](https://snack.expo.io/ByFPE-FxB)

**Comment by stephane-r** [comment]
Hi @ecreeth yes, that work but without use method for open/close Drawer ^^

**Comment by brunocrpontes** [comment]
Are you using [`react-native-screens`](https://github.com/kmagiera/react-native-screens) @stephane-r ?
