### ISSUE TITLE
React Native Picker shows ghost picked value

### ISSUE THREAD

**Issue by Aiiros** [facebook/react-native#25456]
I'm using the default react native picker on Android, and some values's color are randomly changed as i scroll. 

Note that this bug is only visual, selected values are working fine.

React Native version:

```
System:
    OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
    Memory: 1.11 GB / 7.67 GB
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 8.10.0 - /usr/bin/node
    npm: 3.5.2 - /usr/bin/npm
  SDKs:
    Android SDK:
      API Levels: 22, 23, 26, 27, 28
      Build Tools: 23.0.1, 27.0.3, 28.0.3
      System Images: android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.0 => 0.60.0 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-debugger: 1.1.0
    react-native: 0.59.3
```

## Steps To Reproduce
use the `Picker` component from react native on android,
put more items in it than your screen can contain,
scroll back and forth a few times and some values should be greyed out

Describe what you expected to happen:

I need the component not to randomly change some colors as i scroll

Snack, code example, or link to a repository:

Gif demo: https://i.imgur.com/bDQov0K.gif
Snack exemple: https://snack.expo.io/rJNN1JKeB
Stack issue: https://stackoverflow.com/questions/56853193/react-native-picker-show-ghost-picked-value

**Comment by cabelitos** [comment]
Hello @Aiiros I submitted a fix for this problem. You and others are welcome to take a look and add comments/suggestions.

Please see it in here: https://github.com/facebook/react-native/pull/25750
