### ISSUE TITLE
Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml is also present at [androidx.core:core:1.0.0] AndroidManifest.xml: value=(androidx.core.app.CoreComponentFactory).

### ISSUE THREAD

**Issue by NitishAgrawal** [facebook/react-native#25469]
I am not using expo project and try to find the solution and found [here](https://github.com/material-components/material-components-android/issues/193) and [here](https://stackoverflow.com/questions/51793345/android-material-and-appcompat-manifest-merger-failed/53202089).
But these solutions not working because I have multiple modules in my react-native project but I just update react-native version from 0.57.8 to 0.59.9 and after resolving all issue I am facing the issue with android support and androidx library. Most modules are using android support but react-native-video using androidx and it's creating issue (Because we can use only one either androidx or android support library) but I need to use react-native-video with latest version 4.x (which is on androidx). I have tried with many research and try to check with different version of react-native-video but no luck.

Can any one assist me that how can I use both andriodx and android support libraries with different modules simultaneously in a project?
Or any other solution of this issue.

React Native version:

## Steps To Reproduce

1. Just use any react-native module using android support version with react-native-video version 4.x.
2. Try to run android project.

**Comment by kelset** [comment]
Please refer to this issue https://github.com/facebook/react-native/issues/25293
