### ISSUE TITLE
bugs on Windows with v0.60

### ISSUE THREAD

**Issue by zenz** [facebook/react-native#25476]
react-native run-android failed on Windows

React Native version:
```
info Fetching system and libraries information...
System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 1.71 GB / 7.91 GB
  Binaries:
    Node: 10.15.3 - C:\Users\zenz\scoop\apps\nodejs-lts\current\node.EXE
    Yarn: 1.16.0 - C:\Users\zenz\scoop\apps\yarn\current\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Users\zenz\scoop\apps\nodejs-lts\current\npm.CMD
  SDKs:
    Android SDK:
      Android NDK: 20.0.5594570
```

## Steps To Reproduce

1. react-native init test_app
2. cd test_app
3. react-native run-android

Error message as below:
```
FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\zenz\programs\test_app\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' line: 182

* What went wrong:
A problem occurred evaluating settings 'test_app'.
> Text must not be null or empty

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

```

manually modify the file 'node_modules\@react-native-community\cli-platform-android\native_modules.gradle' and change 
`def command = "node ./node_modules/.bin/react-native config"`
to
`def command = "./node_modules/.bin/react-native config"`
can temporary fix the problem.

**Comment by yjqz86** [comment]
I tried to apply that solution, but It doesn´t work for me

**Comment by yjqz86** [comment]
I hope this capture can help

![bugReactive](https://user-images.githubusercontent.com/8808566/60619177-14c38280-9da6-11e9-846d-ea596416f650.png)

**Comment by zenz** [comment]
@yjqz86 in app's root path, run ./node_modules/.bin/react-native config
what can you get?

**Comment by lumyjuwon** [comment]
Hi, I solved this bug in my way.

![tre](https://user-images.githubusercontent.com/32597561/60640810-ec01c280-9e63-11e9-8985-19cc90e36539.PNG)

execute android studio and click configure then click "AVD Manager"

![ywyew](https://user-images.githubusercontent.com/32597561/60640902-4569f180-9e64-11e9-99dd-07baaf3d0b88.PNG)

Click the "Wipe data"

this helped me.

I guess the virtual device have something like index android.js
in the virtual device is so completed. so the way to solve this phenomenon is wipe it.

**Comment by zenz** [comment]
@lumyjuwon are we talking about the same issue?
I think they are not relative?

**Comment by lumyjuwon** [comment]
@zenz 
same issue.
I don't know why this way is helpful for me. but I solved the Text must not be null or empty by this way.

**Comment by neilerua72** [comment]
@zenz  
For me, in the file 'node_modules@react-native-community\cli-platform-android\native_modules.gradle, there is already `def command = "./node_modules/.bin/react-native config"` and I still have the problem... 

@lumyjuwon 
We can't do that if we want to run the app on a real phone ? :'( 

If anyone have the solution...

**Comment by zenz** [comment]
@neilerua72  you need to start an other console to run
./node_modules/.bin/react-native.cmd start
to start up the Metro bundler.

**Comment by neilerua72** [comment]
@zenz I don't really understand :') 

I'm working with React Native for 2 month and I've never used this kind of technologies... 
So if you can explain a little bit more the proccedure I will be grateful.

**Comment by yjqz86** [comment]
@lumyjuwon Your answer doesn't work for me. I put my trouble here for that. It's not bad to quest

**Comment by zenz** [comment]
> @zenz I don't really understand :')
> 
> I'm working with React Native for 2 month and I've never used this kind of technologies...
> So if you can explain a little bit more the proccedure I will be grateful.

This is a bug, with previous version, these things should be handle together by just one command. But now, since this bug, you have to make it work by manually modify something and run it by your self.
Indeed from v0.56, each release version have problems on Windows platform. :(

**Comment by neilerua72** [comment]
Thank you for your answer It help me to understand. 

But how I can make it work ? I just have to run the JS server by execute an other command ?

**Comment by zenz** [comment]
@neilerua72 yes, do this:
open a command window or powershell window.
`react-native start`
open another command window or powershell window.
`react-native run-android`
That's it for debugging.

**Comment by neilerua72** [comment]
Thank you really much ! I will test this tommorow !

**Comment by Andersonfrfilho** [comment]
The problem for at least min still continues and I'm having to run it manually = \. windows10.

**Comment by thymikee** [comment]
We handle this in the CLI repo: https://github.com/react-native-community/cli/issues/470. Please chime in if you're able to help :)
