### ISSUE TITLE
App Crash on Android OS 6 Meizu M5s M612H A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x7f5de40000 in tid 23649 (FrescoDecodeExe)

### ISSUE THREAD

**Issue by IvanStrelcov** [facebook/react-native#25473]
App crashes when I move between same screens with error
```A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x7f5b700000 in tid 31749 (FrescoDecodeExe)```

## **React Native version:**
```
React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 238.37 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.13.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.0, 25.0.2, 26.0.1, 26.0.3, 27.0.3, 28.0.3
        System Images: android-23 | Google APIs Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.10 => 0.59.10 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-rename: 2.4.1
```
**Device** Meizu M5s M612H Android 6.0

Describe what you expected to happen:
Just works

**Comment by IvanStrelcov** [comment]
adb logcat | ndk-stack -sym jni/arm64-v8a/libjsc.so
********** Crash dump: **********
Build fingerprint: 'Meizu/meizu_M5s/M5s:6.0/MRA58K/1495063419:user/release-keys'
#00 0x0000000000009228 /system/lib64/libminikin.so (_ZNK7android10FontFamily15getClosestMatchENS_9FontStyleE+12)
Crash dump is completed

**Comment by jacquesdev** [comment]
@kelset and @Kudo 

Could you please give any guidance on this issue?

If there is at least some way of keeping this alive that would be great, for example, if this was fixed in react-native 0.60.x that would be great to know, right now I have no idea how to track where such fixes are taking place.

**Comment by Kudo** [comment]
@jacquesdev You may able to upgrade RN 0.60.4 and turn on [Hermes](https://facebook.github.io/react-native/docs/hermes).
Hopefully that will fix your problem.

**Comment by vardaan** [comment]
React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
      Memory: 1.17 GB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.6.0 - /usr/local/bin/node
      npm: 6.5.0-next.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.3, 25.0.2, 26.0.2, 26.0.3, 27.0.2, 27.0.3, 28.0.2, 28.0.3
        System Images: android-19 | Google APIs Intel x86 Atom, android-21 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild

Fatal signal 11 (SIGSEGV), code 1, fault addr 0x96169c8ff6053b in tid 16606 (FrescoDecodeExe)

Still happening in 0.59.10 any solution ?

**Comment by IvanStrelcov** [comment]
For me still happening in 0.59.10, any solutions yet :(

**Comment by vardaan** [comment]
@IvanStrelcov  for me it was happening because I was using <Image inside <ImageBackground /> strangely but fixed when I removed it that too on a particular device

**Comment by brunsy** [comment]
Getting this on Meizu devices with RN 0.60.4 + Hermes enabled

**Comment by YoranRoels** [comment]
We are using React-Native 0.60.5 + Hermes + 64-bit enabled and we are experiencing this error on HUAWEI MYA-L41.
Turning off 64-bit seems to avoid these issues, which is obviously not a solution since it's now mandatory to have 64-bit support when releasing an app.
Has anybody made any progress regarding this issue or is it a different issue for each device?

**Comment by joshuapinter** [comment]
In our case, it was because we were using `null` in an `Image` Component's `source` `uri` prop, like this: 

```js
<Image source={ uri: null } />
```

It was causing this crash.

We found the solution [here](https://github.com/facebook/react-native/issues/24261#issuecomment-525443006).
