### ISSUE TITLE
Not able to integrate firebase in ios

### ISSUE THREAD

**Issue by kethu2403** [facebook/react-native#25489]
<img width="436" alt="Screen Shot 2019-07-04 at 2 29 49 PM" src="https://user-images.githubusercontent.com/32518181/60654105-f7a3b800-9e68-11e9-881c-c24952d6b453.png">

**Comment by kethu2403** [comment]
After linking the libraries and installing the pods related to the firebase also. I am not able to build the project in xcode.

**Comment by thymikee** [comment]
Please file this issue in Firebase  repository. Cc @Salakar
