### ISSUE TITLE
react-native-gesture-handler isn't working on Android

### ISSUE THREAD

**Issue by matheus3301** [facebook/react-native#25483]
React Native version:

## Steps To Reproduce

1. react-native init Project --template rocketseat-basic
2. cd Project
2. react-native run-android

Describe what you expected to happen: I expect that the build works

**Comment by ryohlan** [comment]
react-native-gesture-handler does not support for AndroidX yet if you use v0.60.0.
Wait for merging https://github.com/kmagiera/react-native-gesture-handler/pull/664

**Comment by rszalski** [comment]
@matheus3301 In the meantime, you can work around this by using the Jetifier.

If your RN project is configured to use AndroidX, but some of your deps are not (like `react-native-gesture-handler`) follow these steps:

1. Install Jetifier `npm install --save-dev jetifier` or `yarn add -D jetifier`
1. Edit your `package.json` and add a postinstall script: `"postinstall": "npx jetify`, like so:
    ```
    "scripts": {
        "postinstall": "npx jetify"
       ...
    }    
    ```
1. Run `npm install` or `yarn`

This way `jetfier` will "upgrade" all deps to use AndroidX. This step has to be repeated after each installation, hence the `"postinstall"` step.

See: https://github.com/mikehardy/jetifier

**Comment by JuliyaShirokova** [comment]
rszalski, thank's Very-y MUTH! it is work!

**Comment by gomdolkim** [comment]
thank you so much. it works.

**Comment by kunal7898** [comment]
Thanks you so much.

**Comment by Jasper-zzq** [comment]
> @ matheus3301在此期间，您可以使用Jetifier来解决这个问题。
> 
> 如果您的RN项目配置为使用AndroidX，但某些deps不是（如`react-native-gesture-handler`），请按照下列步骤操作：
> 
> 1. 安装Jetifier `npm install --save-dev jetifier`或`yarn add -D jetifier`
> 2. 编辑`package.json`并添加一个postinstall脚本：`"postinstall": "npx jetify"`如下所示：
>    ```
>    "scripts": {
>        "postinstall": "npx jetify"
>       ...
>    }    
>    ```
> 3. 跑`npm install`或`yarn`
> 4. 在安装结束时，你应该看到类似的东西：
>    ```
>    $ npx jetify
>    Jetifier found N file(s) to forward-jetify. Using X workers...`. 
>    ```
>    
>    
>    这意味着它正在运作。该项目现在应该编译好。
> 
> 这种方式`jetfier`将“升级”所有deps以使用AndroidX。每次安装后都必须重复此步骤，因此执行该`"postinstall"`步骤。
> 
> 请参阅：[https](https://github.com/mikehardy/jetifier)：[//github.com/mikehardy/jetifier](https://github.com/mikehardy/jetifier)

thanks

**Comment by HarshitMadhav** [comment]
@rszalski Pretty awesome solution! Thanks it worked for me too. I do have a question though, 
Is it a feasible solution?

**Comment by rszalski** [comment]
@HarshitMadhav what do you mean by sayin "feasable"? This is a solution that will not be needed once every dep upgrades to AndroidX. For now, I don't see any downside to running the jetifier.

Also, thank @mikehardy for the jetifier, and not me :)

**Comment by mikehardy** [comment]
And thanks to the general community making contributions jetifier is fast and stable and integrated by default when you run react-native start so it's not just feasible it is almost unavoidable 😁

**Comment by HarshitMadhav** [comment]
@mikehardy thank you for the jetifier 🤗

**Comment by HarshitMadhav** [comment]
@rszalski By feasible I meant that jetifier is converting the code for androidx support means it is converting the native code I was worried about whether it will produce crashes from native code in various android devices.

**Comment by arjunghimire** [comment]
> @matheus3301 In the meantime, you can work around this by using the Jetifier.
> 
> If your RN project is configured to use AndroidX, but some of your deps are not (like `react-native-gesture-handler`) follow these steps:
> 
> 1. Install Jetifier `npm install --save-dev jetifier` or `yarn add -D jetifier`
> 2. Edit your `package.json` and add a postinstall script: `"postinstall": "npx jetify"`, like so:
>    ```
>    "scripts": {
>        "postinstall": "npx jetify"
>       ...
>    }    
>    ```
> 3. Run `npm install` or `yarn`
> 4. At the end of install you should see something like:
>    ```
>    $ npx jetify
>    Jetifier found N file(s) to forward-jetify. Using X workers...`. 
>    ```
>    
>    
>    This means it's working. The project should compile fine now.
> 
> This way `jetfier` will "upgrade" all deps to use AndroidX. This step has to be repeated after each installation, hence the `"postinstall"` step.
> 
> See: https://github.com/mikehardy/jetifier

You save my life. Thanks a lot @rszalski

**Comment by pentolbakso** [comment]
I solve the problem by following this guide => https://kmagiera.github.io/react-native-gesture-handler/docs/getting-started.html#android

No need to add jetifier. I'm using RN 0.60.4

**Comment by mikehardy** [comment]
@pentolbakso you are the lucky recipient of community work which integrated jetifier directly into the react-native-cli :-) - so no need to add jetifier because it is auto-added and auto-run now, as mentioned in the docs for the package you mention

https://github.com/kmagiera/react-native-gesture-handler/pull/687/files#diff-a39c9f7aa728d5fa3b973bc6ba49228aR99

**Comment by rajscet** [comment]
![image](https://user-images.githubusercontent.com/6961313/64903615-fd741000-d6d9-11e9-8942-384f9cb92a77.png)

I fixed it without jet

**Comment by malikperang** [comment]
> I solve the problem by following this guide => https://kmagiera.github.io/react-native-gesture-handler/docs/getting-started.html#android
> 
> No need to add jetifier. I'm using RN 0.60.4

Thanks this solved my problem which having the issue where it can't be close when tapping outside of the sidebar element.

react-native-cli: 2.0.1
react-native: 0.59.5

**Comment by brayanL** [comment]
> @matheus3301 In the meantime, you can work around this by using the Jetifier.
> 
> If your RN project is configured to use AndroidX, but some of your deps are not (like `react-native-gesture-handler`) follow these steps:
> 
> 1. Install Jetifier `npm install --save-dev jetifier` or `yarn add -D jetifier`
> 2. Edit your `package.json` and add a postinstall script: `"postinstall": "npx jetify"`, like so:
>    ```
>    "scripts": {
>        "postinstall": "npx jetify"
>       ...
>    }    
>    ```
> 3. Run `npm install` or `yarn`
> 4. At the end of install you should see something like:
>    ```
>    $ npx jetify
>    Jetifier found N file(s) to forward-jetify. Using X workers...`. 
>    ```
>    
>    
>    This means it's working. The project should compile fine now.
> 
> This way `jetfier` will "upgrade" all deps to use AndroidX. This step has to be repeated after each installation, hence the `"postinstall"` step.
> 
> See: https://github.com/mikehardy/jetifier

if you use **react-native: 0.59.10** version also is necessary to add: 
```
android.useAndroidX=true
android.enableJetifier=true
```
to your gradle.properties file.

**Comment by milesmeow** [comment]
@arjunghimire.  Thank you! That totally worked for me!

**Comment by MuhammadMattiullah** [comment]
@rszalski I am using PinchGestureHandler to achieve pinch to zoom functionality but it's working perfectly in IOS but its not working on Android ?
Can anyone please tell me whats the issue?
Thanks in Advance

**Comment by lucaspiressimao** [comment]
> @rszalski @arjunghimire @brayanL I am using PinchGestureHandler to achieve pinch to zoom functionality but it's working perfectly in IOS but its not working on Android ?
> Can anyone please tell me whats the issue?
> Thanks in Advance

Hi,

I can't put the Pinch to work in Android, it is not firing the event... I do not know why yet...

**Comment by sandipbiswasbehala** [comment]
@lucaspiressimao
read this and change MainActivity.java
https://docs.swmansion.com/react-native-gesture-handler/docs/#android

read complete page.

**Comment by lfoliveir4** [comment]
> ![image](https://user-images.githubusercontent.com/6961313/64903615-fd741000-d6d9-11e9-8942-384f9cb92a77.png)
> 
> I fixed it without jet

it's work for me in expo SDK 44 in react native bare workflow!

**Comment by tnyy007** [comment]
Hi everybody 
I am a new developer and i am following a "project" 
And i am following the instructions step by step but i am getting this Warning 
[react native gesture handler]Seems like you are using and old Api with gesture components, chrck out new gestures system! 
Im using PanGestureHandler for the swipe on this TinderClone project that im doing but as i said i followed every instruction and i dont get any movement in my card
Thanks for replying! 






![image](https://user-images.githubusercontent.com/39332441/161656520-ab3c1e1d-8245-46e0-8714-a99d4a9b11db.jpeg)

**Comment by gokul1099** [comment]
gesture handler not triggering event in react native 0.68.2. I tried to modify the MainActivity.java file but in this version of react native MainActivity.java Looks like 
![image](https://user-images.githubusercontent.com/42144106/168043313-6aa91aa6-e880-4f73-b8bb-806bdfd92ad8.png)
how can i fix this? package.json file
![image](https://user-images.githubusercontent.com/42144106/168043484-2af730b8-6a25-45c1-bc74-370d299c3e62.png)
my gesture component
![image](https://user-images.githubusercontent.com/42144106/168043570-862e9328-e278-4cc5-87e4-1b4f3c6316ff.png)

**Comment by adgao** [comment]
@gokul1099 Since you are using react-native-gesture-handler v2, you should be able to migrate off `RNGestureHandlerEnabledRootView` in favor of `GestureHandlerRootView ` according to https://docs.swmansion.com/react-native-gesture-handler/docs/guides/migrating-off-rnghenabledroot.

I'm in similar situation where i have to upgrade to RN 0.68, but the new changes introduced in MainActivity.java doesn't allow you to use `RNGestureHandlerEnabledRootView`.

haven't validated this but hopefully it helps
