### ISSUE TITLE
CreateProcess error=2, The system cannot find the file specified

### ISSUE THREAD

**Issue by tmtung144** [facebook/react-native#25488]
```
$ react-native run-android
info Starting JS server...
info Installing the app...
:ReactNative:Cannot run program "./node_modules/.bin/react-native" (in directory "C:\Users\manht\Desktop\santimviec\android\.."): CreateProcess error=2, The system cannot find the file specified
:ReactNative:Automatic import of native modules failed.

> Configure project :app
:ReactNative:Cannot run program "./node_modules/.bin/react-native" (in directory "C:\Users\manht\Desktop\santimviec\android\.."): CreateProcess error=2, The system cannot find the file specified
:ReactNative:Automatic import of native modules failed.

> Task :app:installDebug
03:13:53 V/ddms: execute: running am get-config
03:13:53 V/ddms: execute 'am get-config' on 'emulator-5554' : EOF hit. Read: -1
03:13:53 V/ddms: execute: returning
Installing APK 'app-debug.apk' on 'Pixel_2_API_28(AVD) - 9' for app:debug
03:13:53 D/app-debug.apk: Uploading app-debug.apk onto device 'emulator-5554'
03:13:53 D/Device: Uploading file onto device 'emulator-5554'
03:13:53 D/ddms: Reading file permision of C:\Users\manht\Desktop\santimviec\android\app\build\outputs\apk\debug\app-debug.apk as: rwx------
03:13:54 V/ddms: execute: running pm install -r -t "/data/local/tmp/app-debug.apk"
03:13:54 V/ddms: execute 'pm install -r -t "/data/local/tmp/app-debug.apk"' on 'emulator-5554' : EOF hit. Read: -1
03:13:54 V/ddms: execute: returning
03:13:54 V/ddms: execute: running rm "/data/local/tmp/app-debug.apk"
03:13:54 V/ddms: execute 'rm "/data/local/tmp/app-debug.apk"' on 'emulator-5554' : EOF hit. Read: -1
03:13:54 V/ddms: execute: returning
Installed on 1 device.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 2s
27 actionable tasks: 2 executed, 25 up-to-date
info Connecting to the development server...
info Starting the app on "emulator-5554"...
Starting: Intent { cmp=com.santimviec/.MainActivity }
```

React Native version:

> System:
>     OS: Windows 10
>     CPU: (4) x64 Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
>     Memory: 2.44 GB / 7.95 GB
>   Binaries:
>     Node: 12.5.0 - C:\Program Files\nodejs\node.EXE
>     Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
>     npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
>   IDEs:
>     Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5522156

## Steps To Reproduce

1. react-native init ABC
2. react-native run-android

Describe what you expected to happen:
Build successful apps in android emulator or real device

!!! I have searched for more than half a day for this problem but I have not resolved it, I tried to go back to version 0.59.9 to install and use, no problem occurred.

**Comment by gdoudeng** [comment]
me too!!!

**Comment by haddad-yacine** [comment]
Same problem

**Comment by Sine99** [comment]
Same problem here .... this is probably with the new version of react-native-0.60.0

_info Starting JS server...
info Installing the app..._
**:ReactNative:Cannot run program "./node_modules/.bin/react-native"** (in directory "E:\ReactNative\Examples\Ex_animation\android\.."): CreateProcess error=2, **The system cannot find the file specified**
:ReactNative:Automatic import of native modules failed.

> Configure project :app
**:ReactNative:Cannot run program "**./node_modules/.bin/react-native" (in directory "E:\ReactNative\Examples\Ex_animation\android\.."): CreateProcess error=2, **The system cannot find the file specified**
:ReactNative:Automatic import of native modules failed.

**FAILURE:** Build failed with an exception.

**Comment by vishesh3006** [comment]
Same problem. Even after using version 0.59.9 the "ERROR: Build failed with an exception" is being displayed.

**Comment by kelset** [comment]
👋 there, can you check that you are using the cli version 2.0.2? There was an issue with windows that was related to that -> https://github.com/react-native-community/cli/pull/464

to make sure you will install it, you should check in your yarn.lock which version got installed - it should say something like
```
"@react-native-community/cli@^2.0.1":
  version "2.0.2"
```
if instead the version is 2.0.1, you should remove that portion from the yarn lock and your yarn again

**Comment by vishesh3006** [comment]
> 👋 there, can you check that you are using the cli version 2.0.2? There was an issue with windows that was related to that -> [react-native-community/cli#464](https://github.com/react-native-community/cli/pull/464)
> 
> to make sure you will install it, you should check in your yarn.lock which version got installed - it should say something like
> 
> ```
> "@react-native-community/cli@^2.0.1":
>   version "2.0.2"
> ```
> 
> if instead the version is 2.0.1, you should remove that portion from the yarn lock and your yarn again.
> 
> If it still happens, please open a dedicated issue in that repo -> https://github.com/react-native-community/cli

still not working

**Comment by victorwpbastos** [comment]
Why this issue has been closed? The error still persists.

**Comment by kelset** [comment]
As I mentioned, this is an issue with the CLI and since it's in a dedicated repo now, the issue should be opened there.

**Comment by haddad-yacine** [comment]
> 👋 there, can you check that you are using the cli version 2.0.2? There was an issue with windows that was related to that -> [react-native-community/cli#464](https://github.com/react-native-community/cli/pull/464)
> 
> to make sure you will install it, you should check in your yarn.lock which version got installed - it should say something like
> 
> ```
> "@react-native-community/cli@^2.0.1":
>   version "2.0.2"
> ```
> 
> if instead the version is 2.0.1, you should remove that portion from the yarn lock and your yarn again.
> 
> If it still happens, please open a dedicated issue in that repo -> https://github.com/react-native-community/cli

Still the same probleme

**Comment by debaosuidecl** [comment]
this is so disheartening. I still have the same problem..
I hope a solution comes out soon

**Comment by hamza251** [comment]
this issue is not from the react-native's version. It usually occurs when you have a wrong jdk path in your android studio project settings. Change it with the jdk path.
