### ISSUE TITLE
Question:  init problem 

### ISSUE THREAD

**Issue by Maskedheroe** [facebook/react-native#25485]
info Installing required CocoaPods dependencies

![image](https://user-images.githubusercontent.com/29685985/60638509-34fc4b80-9e51-11e9-8307-0b83fdf4a07e.png)

**Comment by huqiliang** [comment]
same issue.Do you have any solutions?

**Comment by murrayee** [comment]
+1

**Comment by murrayee** [comment]
- brew insatll cocoapods
- cd project/ios & pod install

**Comment by Maskedheroe** [comment]
just wait。。。
