### ISSUE TITLE
loading from pre-bundled file after change bundle identifier

### ISSUE THREAD

**Issue by panda919** [facebook/react-native#25491]
I changed bundle identifier on react native ios.
But, when I try react-native run-ios, I got "loading from pre-bundled file " always.
So I can not execute new bundle id 's engine.
What should i do fit it?

**Comment by dmytro-dish** [comment]
@panda919 Have you resolved this? I am experiencing the same issue and the only way to load source from packager is to delete derived data. However, it helps only once, so I have to delete derived data and wait for a new build for every single change.
