### ISSUE TITLE
when is Android support coming?

### ISSUE THREAD

**Issue by whatsdis** [facebook/react-native#255]
'coming soon', exactly in days? months?

**Comment by rudimk** [comment]
Hate to sound pushy, but I'd ask the same thing, seeing that we'd probably plan some of our experiments with React Native accordingly. Atleast, I would.

**Comment by Timopheym** [comment]
:+1: me too.
may be there can be a branch to follow, and contribute?)

**Comment by calvinlai** [comment]
I would love to find out more about the timeline too. Will be interested to see a branch to follow and contribute. Thanks!

**Comment by dowsanjack** [comment]
I would like to know the same please.

**Comment by richardsabow** [comment]
+1

**Comment by vuhung** [comment]
(y) +1

**Comment by Rudolph-Miller** [comment]
+1

**Comment by stefalda** [comment]
+1

**Comment by shochdoerfer** [comment]
+1

**Comment by madlotus** [comment]
:+1:

**Comment by bltnico** [comment]
:+1:

**Comment by haoqoo** [comment]
+1

**Comment by christianstrang** [comment]
:+1:

**Comment by xorxor** [comment]
:+1:

**Comment by manV** [comment]
+1

**Comment by ElijahLynn** [comment]
"later this year" -> https://github.com/facebook/react-native/issues/309#issuecomment-86879861

**Comment by vjeux** [comment]
Give us 6 months. http://facebook.github.io/react/blog/#when-is-react-native-android-coming

**Comment by fbm-static** [comment]
:+1:

**Comment by whatsdis** [comment]
so another 3 months?

**Comment by brentvatne** [comment]
@whatsdis - 2 months, 1 week, 3 days, 2 hours, 23 minutes and 38 seconds at the time of writing this

[source](http://www.reactnativeandroid.com/) :stuck_out_tongue_closed_eyes:

**Comment by ElijahLynn** [comment]
Gotta love SPAs with shitty path managment. source has moved to 'page2'. 

http://facebook.github.io/react/blog/page2/#when-is-react-native-android-coming

**Comment by iamdustan** [comment]
Except it’s not an SPA. That was an inline link to an element that is part of a specific blog post. Source has always been at http://facebook.github.io/react/blog/2015/03/30/community-roundup-26.html#when-is-react-native-android-coming.

**Comment by ElijahLynn** [comment]
@iamdustan Cool, thanks for the permalink!

**Comment by jagandecapri** [comment]
:+1:

**Comment by whatsdis** [comment]
6 weeks remaining!

**Comment by fbm-static** [comment]
@whatsdis We know. 

There's no need to disturb us through our mailboxes with your countdowns and +1's.

**Comment by cking24343** [comment]
haha :+1:

**Comment by dortzur** [comment]
@fbm-static :+1: 
people should really stop spamming :)
