### ISSUE TITLE
org.gradle.process.internal.ExecException: Process 'command '/Users/lzj/Library/Android/sdk/ndk-bundle/ndk-build'' finished with non-zero exit value 2

### ISSUE THREAD

**Issue by Eafy** [facebook/react-native#25505]
* I have reviewed the [documentation](https://github.com/facebook/react-native/issues)

* I have searched existing [issues](https://github.com/facebook/react-native/issues)

* I am using React Native version: [0.58.6](https://github.com/facebook/react-native/releases/tag/v0.58.6)

I imported ReactAndroid project the source code to android demo. But, The tips are as follows:
<img width="782" alt="图片" src="https://user-images.githubusercontent.com/12604160/60694840-22961680-9f12-11e9-81af-eb62d8dc6969.png">

## React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 1.16 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.10.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.9.2 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.58.6 => 0.58.6 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-scanner-kit: 0.1.0
    Android SDK: 29，API: 28.0.3
    Android Studio: 3.2.1
    gradle: 4.6

## Steps To  Reproduce

1. Config SDK & NDK path to .bash_profile;
![图片](https://user-images.githubusercontent.com/12604160/60695237-9f75c000-9f13-11e9-9627-baa1cbb39a8d.png)

2.  imported ReactAndroid, Config build.gradle、settings.gradle；

Describe what you expected to happen:
Because my project can't use the latest version, but must use version 0.58.6, what is the cause?

Snack, code example, or link to a repository:
<https://github.com/facebook/react-native/releases/tag/v0.58.6>

## Minimal code example：
- setting.gradle
`include ':app', ':ReactAndroid'`
`project(':ReactAndroid').projectDir = new File(rootProject.projectDir, '../node_modules/react-native/ReactAndroid')`
- build.gradle
`dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
        classpath 'de.undercouch:gradle-download-task:3.4.3'

    }`
- app/build.gradle
` dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'

    implementation project(':ReactAndroid')
}`

Please, help?

**Comment by thymikee** [comment]
Unfortunately v0.58 is quite dated and we don't provide support for it. Please try RN 0.59 and if that works, we highly encourage to upgrade to the just released 0.60.
