### ISSUE TITLE
Auto link issue

### ISSUE THREAD

**Issue by lehang123** [facebook/react-native#25506]
When I follow the instruction by the react-navigation website : https://reactnavigation.org/docs/en/getting-started.html.

react-native link react-native-gesture-handler

and then change the MainActivity.java like it asks.

Then run react-native run-android, and error pop up :
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually:

react-native-gesture-handler (to unlink run: "react-native unlink react-native-gesture-handler")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink " and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.

React Native version:
    info Fetching system and libraries information...
System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 6.32 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.5.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      API Levels: 21, 22, 23, 24, 25, 26, 27, 28
      Build Tools: 21.1.2, 22.0.1, 23.0.2, 23.0.3, 24.0.0, 24.0.1, 24.0.2, 25.0.0, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 27.0.0, 27.0.2, 27.0.3, 28.0.3
      System Images: android-23 | Google APIs ARM EABI v7a, android-28 | Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
      Android NDK: 15.2.4203891
  IDEs:
    Android Studio: 3.0 AI-171.4443003
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: ^0.60.0 => 0.60.0 
  npmGlobalPackages:
    react-native-cli: 2.0.1

However, when I follow the instruction, to unlink the library
use : react-native unlink react-native-gesture-handler

The app successfully built, but now it pops up another error in the app :
null is not an object (evaluating 'rngesturehandlermodule.direction')
I tried a lot of solution in a lot of websites, like
#494
https://stackoverflow.com/questions/52861437/undefined-is-not-an-object-evaluating-rngesturehandlermodule-state

non of them is working for me

**Comment by superoo7** [comment]
Read this https://facebook.github.io/react-native/blog/2019/07/03/version-60#native-modules-are-now-autolinked

You don't need to run `react-native link` anymore in most scenario.

**Comment by lehang123** [comment]
I un-linked it, but then another error pop up :
   
<img width="311" alt="Screenshot 2019-07-05 at 12 04 41 PM" src="https://user-images.githubusercontent.com/34762807/60697490-28ddc000-9f1d-11e9-8488-01c6023868e3.png">

**Comment by thymikee** [comment]
React Native Gesture Handler is not compatible with autolinking yet. Please send this issue over there to them. The error says explicitly: 

>If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.

So please do so, here's the link to the repo: https://github.com/kmagiera/react-native-gesture-handler

**Comment by smooJitter** [comment]
So if it isn't compatible does that mean it can't be used?

**Comment by thymikee** [comment]
@smooJitter it is compatible and can be used with newest RN. If linked manually, it needs to be unlinked with `yarn react-native unlink react-native-gesture-handler`. If it's not linked yet, install it and follow https://kmagiera.github.io/react-native-gesture-handler/docs/getting-started.html#android on Android (this is the only change that needs to be done manually for this package), then run `cd ios && pod install` to make it work on iOS.

Also make sure to [update the `@react-native-community/cli`](https://github.com/react-native-community/cli#updating-the-cli) to the latest version.
