### ISSUE TITLE
undefined is not a function(evaluation 'object.getOwnPropertyDescriptors(arguments[i])')

### ISSUE THREAD

**Issue by gsklee** [facebook/react-native#25508]
https://github.com/facebook/react-native/issues/23092

Unfortunately this exact same issue strikes again with the release of Babel v7.5.0.

These are the Babel related dependencies I am having:

```
    "@babel/core": "7.4.5",
    "@babel/plugin-proposal-class-properties": "7.4.4",
    "@babel/plugin-proposal-decorators": "7.4.4",
    "@babel/plugin-transform-flow-strip-types": "7.4.4",
    "@babel/preset-flow": "7.0.0",
    "babel-eslint": "10.0.2",
    "babel-jest": "24.8.0",
    "metro-react-native-babel-preset": "0.54.1",
```

With the `package-lock.json` I generated a few days ago everything's fine with `npm install`, but if I try to do it without the lockfile the error appears. Judging from my lockfile's diff I can say that a few secondary Babel dependencies were updated to v7.5.0 without the lockfile (eg. `@babel/generator`, `@babel/helper-create-class-features-plugin`) so am pretty sure this is a Babel issue again.

**Comment by Udbhav12** [comment]
Same issue. This is really frustrating

**Comment by eyousefifar** [comment]
I'm having the same problem. in react native typescript template re-export feature is removed from the output. its a typescript transformer plugin issue in my case

**Comment by PahmCuogn** [comment]
Same issue :(

**Comment by akhileshagrhari** [comment]
Same issue. Please fix the issue ASAP.

**Comment by Rodrigo77777** [comment]
Old fix does not seem to work this time unfortunately

**Comment by kbarralon** [comment]
Exact same problem with Typescript. Named re-export are undefined.

**Comment by tasosxak** [comment]
I have the same issue:

```
tasosxak@tasosxak:~/ReactNativeProjects/jar$ react-native --version
react-native-cli: 2.0.1
react-native: 0.58.6
```

**Comment by Udbhav12** [comment]
[More info here](https://github.com/babel/babel/issues/10166)

**Comment by mtr1012** [comment]
Anyone can fix this issue?

**Comment by Fischaela** [comment]
With [this](https://github.com/babel/babel/issues/10166) issue closed, does it fix the issue here?

**Comment by mtr1012** [comment]
> With [this](https://github.com/babel/babel/issues/10166) issue closed, does it fix the issue here?

nope

"@babel/helpers" : "7.5.1",
"@babel/plugin-proposal-object-rest-spread" : "7.5.1",
"@babel/plugin-transform-typescript": "7.5.1"
upgrade everything to latest version. still have issue.......

**Comment by mtr1012** [comment]
Insert to package.json to hotfix:

`"resolutions": {
    "@babel/plugin-proposal-object-rest-spread": "7.4.4"
 }`

**Comment by devanshsadhotra25** [comment]
> "resolutions": { "@babel/plugin-proposal-object-rest-spread": "7.4.4" }

for those who are using PropTypes, from prop-types. this will not work

**Comment by Matrixbirds** [comment]
add below into package.json is work for me.
```javascript
  "@babel/core": "7.4.5",
  "@babel/runtime": "7.4.5",
  "metro-react-native-babel-preset": "0.54.1"
```

**Comment by ivanguimam** [comment]
If you are using Redux, put the fixed version 4.0.1, otherwise the application will break on Android: https://github.com/facebook/react-native/issues/25563

The Babel team corrected this problem in the version 7.5.4: https://github.com/babel/babel/issues/10166

**Comment by AkioUnity** [comment]
Hello.

Yet ,I have same issue.

```
    "@babel/core": "^7.5.5",
    "@babel/helpers": "^7.5.5",
    "@babel/runtime": "^7.5.5",
    "metro-react-native-babel-preset": "^0.55.0",
    "babel-eslint": "10.0.2",
```

Please help this

**Comment by Fischaela** [comment]
For me the updates fixed the issue :)

**Comment by gsklee** [comment]
Think this has been fixed in Babel:
https://github.com/babel/babel/issues/10166#issuecomment-510529488

**Comment by AkioUnity** [comment]
yes. it is working fine now.
thank you !!
