### ISSUE TITLE
Build does not start with the 'react-native run-android' command in version 0.60 of React Native

### ISSUE THREAD

**Issue by brunowbbs** [facebook/react-native#25516]
It has a BUG in version 0.60 of React Native that does not allow to start the builder with the command 'react-native run-android', with iOS I did not test. So, to start the builder you have to first run the 'react-native start' command. I tried to create a project with the previous version and it worked normally, the builder started with the command 'react-native run-android'.

![Screenshot_1562338985](https://user-images.githubusercontent.com/35561464/60731544-35aee380-9f1e-11e9-8e3a-ef7069b3be61.png)

**Comment by anoop-ananthan** [comment]
@brunowbbs did u manage to work it up, somehow?

**Comment by manjeets12** [comment]
+1
