### ISSUE TITLE
Can't turn on debugger.

### ISSUE THREAD

**Issue by bachlongkocanh** [facebook/react-native#25513]
# Can't open debugger remote JS.

React Native version:
```
    "react": "16.8.6",
    "react-native": "0.60.0"
```

## Steps To Error

1. Init project with React-native
2. Turn on Debug JS Remotely

#### AND

![Screen Shot 2019-07-05 at 3 44 03 PM](https://user-images.githubusercontent.com/28125294/60709951-c811b000-9f3b-11e9-9c8c-6635492b793f.png)

![Simulator Screen Shot - iPhone X - 2019-07-05 at 15 45 48](https://user-images.githubusercontent.com/28125294/60710035-f7c0b800-9f3b-11e9-8aa0-634b5ea1beb3.png)

**Comment by thymikee** [comment]
Can you send more details about it, your environment, etc?
