### ISSUE TITLE
Add ReactRootView in RelativeLayout will cause endless loop

### ISSUE THREAD

**Issue by codyi96** [facebook/react-native#25515]
I created a ReactRootView instance in [this way](https://facebook.github.io/react-native/docs/integration-with-existing-apps#the-magic-reactrootview) and added it in a FrameLayout which wrapped by RelativeLayout.
Run the app, we can see the method called onMeasure in ReactRootView cause endless loop.
see [DEMO](https://github.com/codyi96/Demo/tree/master/bugfix/bugReactRootViewV60)

React Native version: 0.60.0

info Fetching system and libraries information...
System:
    OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz
    Memory: 1.63 GB / 7.68 GB
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 21, 22, 23, 24, 25, 26, 27, 28
      Build Tools: 23.0.1, 23.0.2, 23.0.3, 24.0.2, 26.0.1, 26.0.2, 27.0.3, 28.0.3
      Android NDK: 16.1.4479499
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.0 => 0.60.0 
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Steps To Reproduce

1. Download [DEMO](https://github.com/codyi96/Demo/tree/master/bugfix/bugReactRootViewV60)
2. Run the app
3. Set a breakpoint at ReactRootView.onMeasure
4. The app stop at ReactRootView.onMeasure

Describe what you expected to happen:
The app is running.

Snack, code example, or link to a repository:
[DEMO](https://github.com/codyi96/Demo/tree/master/bugfix/bugReactRootViewV60)

**Comment by codyi96** [comment]
There is a similar problem which is closed.
see [#19403](https://github.com/facebook/react-native/issues/19403)

**Comment by codyi96** [comment]
Are you solving this problem?

**Comment by codyi96** [comment]
Anyone is dealing with this problem?

**Comment by codyi96** [comment]
This is a serious problem should be solved immediately i think. @cpojer

**Comment by codyi96** [comment]
Help!

**Comment by codyi96** [comment]
😢

**Comment by codyi96** [comment]
😢

**Comment by SuddenH4X** [comment]
Maybe this will help somebody:

We've encountered a similiar issue, but we are using a FrameLayout wrapped by a ConstraintLayout. We fixed the problem by setting all four constraints to all layouts within the ConstraintLayout (even if not needed by Android): `app:layout_constraintBottom_to...`, `app:layout_constraintEnd_to...`, `app:layout_constraintStart_to...` and `app:layout_constraintTop_to...`

**Comment by codyi96** [comment]
> Maybe this will help somebody:
> 
> We've encountered a similiar issue, but we are using a FrameLayout wrapped by a ConstraintLayout. We fixed the problem by setting all four constraints to all layouts within the ConstraintLayout (even if not needed by Android): `app:layout_constraintBottom_to...`, `app:layout_constraintEnd_to...`, `app:layout_constraintStart_to...` and `app:layout_constraintTop_to...`

I agree with u. [This answer](https://github.com/facebook/react-native/issues/19403#issuecomment-410958679) may be more detailed.
