### ISSUE TITLE
[Image] Loading images from home directory

### ISSUE THREAD

**Issue by mattds** [facebook/react-native#2551]
Hi, it seems that loading an image from a relative path e.g. "~/Documents/profileImages/ie5dipcn.png"  no longer works. By the looks of it, RCTConvert.m is no longer using the expanded url path.

**Comment by brentvatne** [comment]
cc @nicklockwood

**Comment by nicklockwood** [comment]
Yes, sorry about that. @a2 has already added a fix for this, which should land in the next update.

**Comment by mattds** [comment]
Thanks, will close the issue then.
