### ISSUE TITLE
build failed on iOS when use ART

### ISSUE THREAD

**Issue by Symous** [facebook/react-native#25523]
If we use ART in our code, we need to drag ART.xcodeproj to the Libraries and add libART.a , but after that the app build failed due to a yoga error:
`The left expression of the compound assignment is an uninitialized value. The computed value will also be garbage`, 
React Native version: 0.59.8

## Steps To Reproduce

1. use ART in code
2. add ART.xcodeproj and libART.a to iOS native project.
3. build the app

Describe what you expected to happen:
build success

**Comment by Symous** [comment]
sorry, just found that I have use the wrong ART.xcodeproj. close this.

**Comment by supwjm** [comment]
excuse me, how did you solve this problem , add ART.xcodeproj and libART.a to iOS native project too and come across the same problem with you

**Comment by Symous** [comment]
@supwjm make sure you have add the correct ART.xcodeproj(in node_modules) and libART.a to the project, and launch .xcworkspace  if you use pods.
