### ISSUE TITLE
error Unrecognized command "eject".

### ISSUE THREAD

**Issue by zaporozhetsAnton** [facebook/react-native#25526]
React Native version:
react-native info:
System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 2.99 GB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.2.0 - ~/.nvm/versions/node/v12.2.0/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.2.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
  IDEs:
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.0 => 0.60.0

## Steps To Reproduce
1 install new project "react-native init newProject"
2 run "react-native eject"
http://prntscr.com/obf753

**Comment by JonnyBurger** [comment]
React Native has no 'eject' command. It already exposes the Xcode project etc.

Maybe you meant 'expo eject', which turns an Expo Project into a React Native project?

**Comment by zaporozhetsAnton** [comment]
> React Native has no 'eject' command. It already exposes the Xcode project etc.
> 
> Maybe you meant 'expo eject', which turns an Expo Project into a React Native project?

No, react-native had this command in the previous version. Running this command will check if the ios and android directories exist and then rebuild whichever one is missing.

**Comment by rishabhmathur1693** [comment]
I'm also facing the same issue. I had to delete both the Android and iOS folder due to some error. Now I'm unable to re-create those folders

**Comment by joe-pellegrino** [comment]
I thought I was going mad, glad it's not just me.

**Comment by PTR-Bushi** [comment]
Same thing in 0.60.0. How am I to create a project whose folder's name is kebab-case? :/

**Comment by r1ckyrockz** [comment]
Same issue here. Any workaround?

**Comment by ithustle** [comment]
+1

**Comment by dannydanzka** [comment]
Hello community, I just found myself with this problem too, but I just solved it.

Surely when running the "**react-native upgrade**" command, it gave them the message that it was not necessary to update or with the command "**react-native eject**" that the command is not recognized.

Now you should use the "**### react-native upgrade --legacy true**" command to back up your android folders or ios as the case may be as this command will replace your files.

Now it's just telling you not to replace your **package.json**

Greetings.

**Comment by zaporozhetsAnton** [comment]
@dannydanzka thanks man, it is not obvious that I should use this command, you helped me a lot, thanks.

**Comment by souenzzo** [comment]
`react-native eject` used do generate just `android` and `ios` stuff
Now `react-native upgrade --legacy true` generates a lot of `.eslint.js` and non-related stuff.
https://github.com/souenzzo/cljs-rn-tutorial/commit/58f4d4850211a21195af15a87d9aebd75f3300fd

**Comment by feliciah6** [comment]
I am also experiencing the same issue when i try to rename my app.Can anyone help?

**Comment by ithustle** [comment]
> I am also experiencing the same issue when i try to rename my app.Can anyone help?

@feliciah6 , try `react-native upgrade --legacy`

**Comment by ramyareye** [comment]
@ithustle any way to handle it on a fresh 0.60.x one?

**Comment by ithustle** [comment]
> @ithustle any way to handle it on a fresh 0.60.x one?

I used this command in a copple days on RN 0.60.4.

**Comment by feliciah6** [comment]
The way I did this for android (hacky, but it works) is just changed the string app_name field in

android/app/src/main/res/values/strings.xml

It will change the name of your installed android app to whatever you put as the value.
@ithustle  i did that today and it worked fine for me

**Comment by feliciah6** [comment]
i hope it helps @ithustle

**Comment by ramyareye** [comment]
[It's gone](https://github.com/react-native-community/cli/pull/275) 
RIP

**Comment by dulmandakh** [comment]
Please file an issue and request a feature at https://github.com/react-native-community/cli.

**Comment by bigo104** [comment]
React Native is an absolute mess, goes against everything I learned through the years about coding and product management, fragmented community, compilation and configuration.

**Comment by mxmzb** [comment]
> React Native is an absolute mess, goes against everything I learned through the years about coding and product management, fragmented community, compilation and configuration.

Good, constructive critique. Well done!

**Comment by geocfu** [comment]
So i stumbled upon that issue. The solution for me, delete (if not already) the old ios and android folders. Then create a new project with the same name as the project with the just deleted folders. Copy over the new androdi and ios folders. Then run ./gradlew clean and go on woth your development again.

**Comment by frederickjjoubert** [comment]
any solutions for this yet? I borked my android folder and now my project is broken, I just want to regenerate the android and iOS folders

**Comment by ramyareye** [comment]
@frederickjjoubert I copied the removed code and made a small package : https://www.npmjs.com/package/react-native-eject

**Comment by AugustoCalaca** [comment]
`react-native upgrade --legacy true`
`error: unknown option --legacy`

react-native: 0.61.4

**Comment by mostasim** [comment]
> `react-native upgrade --legacy true`
> `error: unknown option --legacy`
> 
> react-native: 0.61.4

is there any alternative solution?

**Comment by eng-osman** [comment]
hi Geeks ! 
It no longer works like previously `react-native upgrade --legacy true`
The solution to that problem is to use that library
react-native-eject link : ([www.npmjs.com/package/react-native-eject])

**Comment by Ouadie** [comment]
> hi Geeks !
> It no longer works like previously `react-native upgrade --legacy true`
> The solution to that problem is to use that library
> react-native-eject link : [react-native-eject](www.npmjs.com/package/react-native-eject)

404 link. Here is a working one https://github.com/ramyareye/react-native-eject

**Comment by aqeebimtiaz** [comment]
> hi Geeks !
> It no longer works like previously `react-native upgrade --legacy true`
> The solution to that problem is to use that library
> react-native-eject link : [react-native-eject](www.npmjs.com/package/react-native-eject)

Hi! The **eject** command didn't work for me, I've already posted an issue there. Hope it get's solved. 

I was trying to rename my project... if any of you still considering to change the name of the app, consider using [react-native-rename](https://github.com/junedomingo/react-native-rename)

**Comment by rahul6991** [comment]
npm i react-native-eject
npm i @react-native-community/cli
react-native eject
will generate the both android and ios folder

**Comment by edrisaturay** [comment]
> 
> 
> npm i react-native-eject
> npm i @react-native-community/cli
> react-native eject
> will generate the both android and ios folder

this saved me

**Comment by samcomkishan** [comment]
npm i react-native-eject
npm i @react-native-community/cli
npx react-native eject

This does the job
