### ISSUE TITLE
TypeScript Template 0.60

### ISSUE THREAD

**Issue by ashapir0** [facebook/react-native#25539]
```
error Error: Cannot find module '/tmp/rncli-init-template-LrZBvL/node_modules/react-native-template-typescript/template.config'
```

React Native version: 0.60

System:
    OS: Linux 4.19 Manjaro Linux undefined
    CPU: (16) x64 AMD Ryzen 7 1800X Eight-Core Processor
    Memory: 16.51 GB / 31.40 GB
    Shell: 5.0.7 - /bin/bash
  Binaries:
    Node: 10.0.0 - ~/.nvm/versions/node/v10.0.0/bin/node
    npm: 6.9.0 - ~/.nvm/versions/node/v10.0.0/bin/npm
  SDKs:
    Android SDK:
      API Levels: 23, 24, 28
      Build Tools: 28.0.3
      System Images: android-28 | Google Play Intel x86 Atom
      Android NDK: 15.2.4203891
  npmGlobalPackages:
    react-native: 0.60.0

## Steps To Reproduce

1. react-native init app --template typescript

Describe what you expected to happen:

Initialize a new project with TypeScript.

**Comment by TartagliaEG** [comment]
You have installed the react-native package globally. Replace it with the react-native-cli and try the command again.

**Comment by dulmandakh** [comment]
starting with 0.59 you can use typescript without any special setup or template. create a project and add @types/react @types/react-native and typescript to you devDependencies, then feel free to use TypeScript.
