### ISSUE TITLE
Docs:react-native run-ios getting error

### ISSUE THREAD

**Issue by shamim96** [facebook/react-native#25531]
I jus created a new project and setup all required installation. now while I run react-native run-ios from my visual studio, The app do not going to open in my ios simulator and giving me the bellow errors. Anyone please give me a solution.

info Found Xcode project "rncourse.xcodeproj"
info Launching iPhone X (iOS 12.2)
info Building
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening rncourse.xcodeproj. Run CLI with --verbose flag for more details.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rncourse@0.0.1 ios: react-native run-ios
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rncourse@0.0.1 ios script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /Users/shamim/.npm/_logs/2019-07-06T23_29_22_128Z-debug.log

**Comment by FastestMolasses** [comment]
Update your XCode

https://stackoverflow.com/questions/55235825/error-failed-to-build-ios-project-we-ran-xcodebuild-command-but-it-exited-wit

Ran into this problem a while ago, that fixed it for me.

**Comment by shamim96** [comment]
@FastestMolasses Yesterday, I just installed the xcode. So it supposed to be the updated version. In my app store, xcode not showing for update. Could you tell me how could I update it or any other solution.

**Comment by jsaraiva** [comment]
Maybe try launching the iOS Simulator manually (instead of letting visual studio do it), and _after that_ run the build script.
More details here: [https://circleci.com/blog/circleci-hacks-validate-circleci-config-on-every-commit-with-a-git-hook/](url)

**Comment by iayan316** [comment]
Run npm build script. Open the iOS project in xcode and then run the project from there. This always works for me.
