### ISSUE TITLE
Android debug app crashes silently

### ISSUE THREAD

**Issue by edgarogh** [facebook/react-native#25538]
## Definition
_**Silent crash:** the app crashes without a dialog box or this dialog box disapears as soon as it appears_

## Problem
After a small change to the JS code related to [React Native Navigation](https://wix.github.io/react-native-navigation/#/), the Android app began crashing "silently" as soon as I opened it. The problem is **not related to RNN** since the code I changed couldn't have been executed when the app just started.

Because the error didn't make sense when it started appearing, I thought of some kind of corrupted cache and:
 * Restarted Metro
 * Cleared the app data
 * Re-built and re-installed the app
 * Uninstalled the app, rebooted android, rebuilt and reinstalled it
_...nothing worked_

As a last resort, I installed the app on another phone that never had the app installed on it before and everything magically worked. My own phone is still unable to run my app.

After a little `adb logcat | grep my.package.name`, here's what I got when the app crashes:
```
07-07 17:15:38.076 21958 21958 D SoLoader: Preparing SO source: com.facebook.soloader.ApkSoSource[root = /data/data/my.package.name/lib-main flags = 1]
07-07 17:15:38.079 21958 21958 V fb-UnpackingSoSource: locked dso store /data/user/0/my.package.name/lib-main
07-07 17:15:38.082 21958 21958 I fb-UnpackingSoSource: dso store is up-to-date: /data/user/0/my.package.name/lib-main
07-07 17:15:38.082 21958 21958 V fb-UnpackingSoSource: releasing dso store lock for /data/user/0/my.package.name/lib-main
07-07 17:15:38.147 21958 21982 I FA      :   adb shell setprop debug.firebase.analytics.app my.package.name
07-07 17:15:38.181 21958 21997 E AndroidRuntime: Process: my.package.name, PID: 21958
07-07 17:15:38.182 21958 21996 E AndroidRuntime: Process: my.package.name, PID: 21958
07-07 17:15:38.195  3855  5223 I ActivityManager: Process my.package.name (pid 21958) has died: fore TOP 
07-07 17:15:38.209  3855  5223 I ActivityManager: Start proc 22002:my.package.name/u0a367 for activity my.package.name/.MainActivity
07-07 17:15:38.408 22002 22002 D SoLoader: adding application source: com.facebook.soloader.DirectorySoSource[root = /data/app/my.package.name-FkwuY8sK8vetr99xNOCwZw==/lib/arm64 flags = 0]
07-07 17:15:38.408 22002 22002 D SoLoader: adding backup source from : com.facebook.soloader.ApkSoSource[root = /data/data/my.package.name/lib-main flags = 1]
07-07 17:15:38.409 22002 22002 D SoLoader: Preparing SO source: com.facebook.soloader.DirectorySoSource[root = /data/app/my.package.name-FkwuY8sK8vetr99xNOCwZw==/lib/arm64 flags = 0]
07-07 17:15:38.409 22002 22002 D SoLoader: Preparing SO source: com.facebook.soloader.ApkSoSource[root = /data/data/my.package.name/lib-main flags = 1]
07-07 17:15:38.410 22002 22002 V fb-UnpackingSoSource: locked dso store /data/user/0/my.package.name/lib-main
07-07 17:15:38.414 22002 22002 I fb-UnpackingSoSource: dso store is up-to-date: /data/user/0/my.package.name/lib-main
07-07 17:15:38.414 22002 22002 V fb-UnpackingSoSource: releasing dso store lock for /data/user/0/my.package.name/lib-main
07-07 17:15:38.484 22002 22027 I FA      :   adb shell setprop debug.firebase.analytics.app my.package.name
07-07 17:15:38.504 22002 22039 E AndroidRuntime: Process: my.package.name, PID: 22002
07-07 17:15:38.509 22002 22041 E AndroidRuntime: Process: my.package.name, PID: 22002
07-07 17:15:38.524  3855  5223 I ActivityManager: Process my.package.name (pid 22002) has died: fore TOP 
07-07 17:15:38.536  3855  5223 I ActivityManager: Start proc 22044:my.package.name/u0a367 for activity my.package.name/.MainActivity
07-07 17:15:38.730 22044 22044 D SoLoader: adding application source: com.facebook.soloader.DirectorySoSource[root = /data/app/my.package.name-FkwuY8sK8vetr99xNOCwZw==/lib/arm64 flags = 0]
07-07 17:15:38.730 22044 22044 D SoLoader: adding backup source from : com.facebook.soloader.ApkSoSource[root = /data/data/my.package.name/lib-main flags = 1]
07-07 17:15:38.731 22044 22044 D SoLoader: Preparing SO source: com.facebook.soloader.DirectorySoSource[root = /data/app/my.package.name-FkwuY8sK8vetr99xNOCwZw==/lib/arm64 flags = 0]
07-07 17:15:38.731 22044 22044 D SoLoader: Preparing SO source: com.facebook.soloader.ApkSoSource[root = /data/data/my.package.name/lib-main flags = 1]
07-07 17:15:38.733 22044 22044 V fb-UnpackingSoSource: locked dso store /data/user/0/my.package.name/lib-main
07-07 17:15:38.736 22044 22044 I fb-UnpackingSoSource: dso store is up-to-date: /data/user/0/my.package.name/lib-main
07-07 17:15:38.736 22044 22044 V fb-UnpackingSoSource: releasing dso store lock for /data/user/0/my.package.name/lib-main
07-07 17:15:38.793 22044 22069 I FA      :   adb shell setprop debug.firebase.analytics.app my.package.name
07-07 17:15:38.835 22044 22083 E AndroidRuntime: Process: my.package.name, PID: 22044
07-07 17:15:38.836 22044 22082 E AndroidRuntime: Process: my.package.name, PID: 22044
07-07 17:15:38.848  3855  5223 I ActivityManager: Process my.package.name (pid 22044) has died: fore TOP 
07-07 17:15:38.860  3855  5223 I ActivityManager: Start proc 22088:my.package.name/u0a367 for activity my.package.name/.MainActivity
07-07 17:15:39.074 22088 22088 D SoLoader: adding application source: com.facebook.soloader.DirectorySoSource[root = /data/app/my.package.name-FkwuY8sK8vetr99xNOCwZw==/lib/arm64 flags = 0]
07-07 17:15:39.075 22088 22088 D SoLoader: adding backup source from : com.facebook.soloader.ApkSoSource[root = /data/data/my.package.name/lib-main flags = 1]
07-07 17:15:39.076 22088 22088 D SoLoader: Preparing SO source: com.facebook.soloader.DirectorySoSource[root = /data/app/my.package.name-FkwuY8sK8vetr99xNOCwZw==/lib/arm64 flags = 0]
07-07 17:15:39.076 22088 22088 D SoLoader: Preparing SO source: com.facebook.soloader.ApkSoSource[root = /data/data/my.package.name/lib-main flags = 1]
07-07 17:15:39.077 22088 22088 V fb-UnpackingSoSource: locked dso store /data/user/0/my.package.name/lib-main
07-07 17:15:39.083 22088 22088 I fb-UnpackingSoSource: dso store is up-to-date: /data/user/0/my.package.name/lib-main
07-07 17:15:39.083 22088 22088 V fb-UnpackingSoSource: releasing dso store lock for /data/user/0/my.package.name/lib-main
07-07 17:15:39.175 22088 22125 E AndroidRuntime: Process: my.package.name, PID: 22088
07-07 17:15:39.175 22088 22126 E AndroidRuntime: Process: my.package.name, PID: 22088
07-07 17:15:39.179 22088 22112 I FA      :   adb shell setprop debug.firebase.analytics.app my.package.name
07-07 17:15:39.187  3855  5223 W ActivityManager:   Force finishing activity my.package.name/.MainActivity
07-07 17:15:39.198  3855  3870 I ActivityManager: Showing crash dialog for package my.package.name u0
07-07 17:15:39.211  3855  4675 W ActivityManager: Process my.package.name has crashed too many times: killing!
07-07 17:15:39.218  3855  4675 E ActivityManager: Found activity ActivityRecord{b3116d u0 my.package.name/.MainActivity t-1 f} in proc activity list using null instead of expected ProcessRecord{be5514d 22088:my.package.name/u0a367}
07-07 17:15:39.223 22088 22088 I zygote64: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/my.package.name-FkwuY8sK8vetr99xNOCwZw==/base.apk"],nativeLibraryDirectories=[/data/app/my.package.name-FkwuY8sK8vetr99xNOCwZw==/lib/arm64, /data/app/my.package.name-FkwuY8sK8vetr99xNOCwZw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
07-07 17:15:39.225 22088 22088 I zygote64: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/my.package.name-FkwuY8sK8vetr99xNOCwZw==/base.apk"],nativeLibraryDirectories=[/data/app/my.package.name-FkwuY8sK8vetr99xNOCwZw==/lib/arm64, /data/app/my.package.name-FkwuY8sK8vetr99xNOCwZw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
07-07 17:15:39.226 22088 22088 I zygote64: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/my.package.name-FkwuY8sK8vetr99xNOCwZw==/base.apk"],nativeLibraryDirectories=[/data/app/my.package.name-FkwuY8sK8vetr99xNOCwZw==/lib/arm64, /data/app/my.package.name-FkwuY8sK8vetr99xNOCwZw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
07-07 17:15:39.266  3855  4675 I ActivityManager: Killing 22088:my.package.name/u0a367 (adj 199): crash
07-07 17:15:39.279  3855  5223 W ActivityManager: Ignoring remove of inactive process: ProcessRecord{be5514d 0:my.package.name/u0a367}
```
Basically, the app crashes a few times (I've stripped the beggining) and android kills it.
_I have quite a bit of native android development knowledge, but this seems to be too much in React Native's territory for me._

## Summary
The debug build of my app crashes only on my phone after no real change in the code. The logcat isn't really meaningful and I didn't find any workaround.

I'm also not 100% percent sure that the problem _only_ comes from React Native.

**Edit:** I completeley removed RNFirebase as well as the Google Play Services gradle plugin and the native Firebase dependency, and I still had the crash.  I'll continue removing dependencies, but RNN has so much setup involved that I'll probably start a new project.

## Versions
| Native module                         | Version |
|---------------------------------------|---------|
| React Native                          | 0.59.8  |
| react-native-firebase                 | ^5.3.1  |
| react-native-navigation               | ^2.21.0 |
| react-native-vector-icons             | ^6.4.2  |
| @react-native-community/async-storage | ^1.4.2  |

```
info Fetching system and libraries information...
  System:
    OS: Linux 4.15 Linux Mint 19 (Tara)
    CPU: (4) x64 Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz
    Memory: 133.50 MB / 7.71 GB
    Shell: 2.7.1 - /usr/bin/fish
  Binaries:
    Node: 8.10.0 - /usr/bin/node
    npm: 6.9.2 - /usr/local/bin/npm
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.0 => 0.60.0 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

## Steps To Reproduce
Unfortunately, the problem doesn't look reproductible as my experiments have shown. If the logcat isn't sufficient, you might not be able to help me, which is understandable. If you need more data however, I'll be happy to provide it.

## :warning: Important update
I created a completely new development environment after a failed upgrade ([requested by the bot](https://github.com/facebook/react-native/issues/25538#issuecomment-509157387)).

I reinstalled the librairies slowly, testing every time I added a few of them. When all the librairies where installed (and automatically linked, thanks to v0.60) and I hadn't copied all my JS code yet, I started the metro server (with still the `react-native init` template's JS).

I started the app, my phone being unplugged and entered my local IP address and port in the dev settings of the app, as I always did. I pressed OK on the dialog box, pressed the back button of the dev settings Activity and it crashed instantly.

Now, I am back at the start, even though I'm in another environment. **The only things that are the same are the librairies & the package name**. I'll try to remove librairies one by one to see if something works again, but the whole problem is probably not related to react-native as I initially thought. I'll edit as soon as I have more info.

**Comment by edgarogh** [comment]
I don't know what I did wrong in the first experiment, but the problem definitely comes from [RNFirebase](https://rnfirebase.io/), and removing it solves everything.

[It is not available](https://github.com/invertase/react-native-firebase/issues/2320) for [v0.60](https://github.com/facebook/react-native/releases/tag/v0.60.0) however, so I'll have to forget about notifications for now... I probably shouldn't have updated my project in the first place, but it's too late.

I'll post any updates here in case I'm not the only one having this issue.

**Comment by MrHazimAli** [comment]
any update @edgarogh ? I'm having same issue after init the project and just link with RNFirebase

**Comment by edgarogh** [comment]
Well, I updated RN to 0.60 and AFAIK RNFirebase is still not available for this version due to the changes in the linking system, so I can't even try. The commit related to that has been merged but I don't think it was published. I started patching it with `patch-package` but went in vacation before I finished.

Regarding the older version of RN, where I had this problem, I haven't found a fix and will probably not go back anyways. If you haven't done it, you could open an issue on RNFirebase's Github project, maybe linking to this one (and I'll do it myself), this might be more useful.

From my research, the bug is not really common and it doesn't look like it happens on the official Firebase lib in native Android development, so it must be linked with RNFirebase. Ideally we should try to isolate the part of the library that causes the crash by slowly adding and removing compilation steps from the complex setup, but I can't do that right now.

Hope you'll find your answers, and I hope everything will work for me in React Native 0.60

**Comment by wilkuintheair** [comment]
I had the same situation, the crash came out of nowhere and I couldn't get rid of it. What finally helped was this:
`(cd android && ./gradlew clean)`
Maybe it will save someone's time in the future

**Comment by GIRIRAJNAGAR768** [comment]
two easy steps solved my problem...
1. open android studio and remove offline bundle from src/main/assest..(** if any)
2. open MainApplication.java and remove the following import..
import com.facebook.react.BuildConfig

**Comment by mogol23** [comment]
@GIRIRAJNAGAR768 thanks, you save my life

**Comment by Manitej66** [comment]
> two easy steps solved my problem...
> 
> 1. open android studio and remove offline bundle from src/main/assest..(** if any)
> 2. open MainApplication.java and remove the following import..
>    import com.facebook.react.BuildConfig

Thank you soooooooooooo much

**Comment by Muhammadkaleem** [comment]
@GIRIRAJNAGAR768 Thank you really helpfull bro

**Comment by adumat** [comment]
@GIRIRAJNAGAR768 thank you man, i love you ❤️

**Comment by Tony0205** [comment]
@GIRIRAJNAGAR768 Thank you man, you save my time!! 🔥
