### ISSUE TITLE
RCTUIManager.configureNextLayoutAnimation must not be null

### ISSUE THREAD

**Issue by exentrich** [facebook/react-native#2553]
When i try to run app in not dev mode i have this bug:
![eee](https://cloud.githubusercontent.com/assets/1203812/9680225/f61f5698-52fd-11e5-8d7c-1d76832f24c2.png)

I am using LayoutAnimation
React Native 0.11

**Comment by twelvearrays** [comment]
I have the same error. Did you find a solution?

**Comment by nicklockwood** [comment]
I believe I've fixed this with: https://github.com/sahrens/react-native/commit/bb5522582d47fa22a7cf5d34c3069340ba495863 - can you try adding that and see if it solves the problem?

**Comment by nicklockwood** [comment]
Actually, I'm not 100% sure it's the same issue. You may just have a stale copy of the JS.

**Comment by brentvatne** [comment]
```
npm cache clean
npm install
```

Next:
- Open your AppDelegate and make sure you're pointing to the packager and not a compiled bundle.
- Then open up Xcode and press ⌘+k to clean the build. Then run it again.

That should fix the issue for you!

**Comment by SudoPlz** [comment]
I'm using an `Animated.View` and this error appears when I unmount the View before the object stops animating.. No idea what to do.. I call `stop()` on the animation on `componentWillUnmount` but that doesn't seem to be working.
