### ISSUE TITLE
Unexpected token "{". Import call expects exactly one argument

### ISSUE THREAD

**Issue by canyavall** [facebook/react-native#25545]
One week ago everything was working perfectly fine. I came back from holidays and pulled all new code from my coleagues. Executed yarn run-android and I got this message:

Unexpected token "{". Import call expects exactly one argument

I thought, ok, maybe some code from my coleagues broke it so I create a branch from the last working state and nothing, same issue...

Since then (2days) I've been trying everything that came to my mind (gradlew clear, clean cache from yarn and npm, remove node_modules (a lot of times)... and nothing works...

One thing that's strange is the metro bundler path:
![image](https://user-images.githubusercontent.com/11173569/60793064-338b9580-a167-11e9-8a94-37334bc24765.png)

React Native version:
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz
      Memory: 5.85 GB / 15.88 GB
    Binaries:
      Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5264788

## Steps To Reproduce

1.Just run react-native run-android and done...

Snack, code example, or link to a repository: I really don't know which code paste as it really breaks before bundling...

**Comment by canyavall** [comment]
I kept investigating and, incredibly, if in the index.js between the imports I write a console.log

```
import {AppRegistry} from 'react-native';
console.log("Yeaaaaahhhh")
import AppNative from './native/App.native';
```

Then it works.....

If I remove it, then it stops working....

**Comment by canyavall** [comment]
So, for what I can see, the babel.config.js file is not being loaded on time in windows10, so the transpile is not taking place...

**Comment by canyavall** [comment]
Doing wha tthis link say: https://medium.com/@abhisheknalwaya/how-to-clear-react-native-cache-c435c258834e and deleting the yarn.lock fixed it

**Comment by wuweijian1997** [comment]
nice。
I solved the problem with this line of code.
`
cd android &&

./gradlew cleanBuildCache
`
## windows & android

**Comment by arjndr** [comment]
for anyone that's stuck `yarn start --reset-cache` will do the trick
