### ISSUE TITLE
lineHeight style has no effect on multiline TextInput

### ISSUE THREAD

**Issue by njdancer** [facebook/react-native#25543]
This appears to be the same issue reported in #14232.

When lineHeight is added to multiline TextInput's the height of the TextInput is initially effected however this disappears on first input at which point this appears to be ignored.

```javascript
import * as React from 'react';
import { View, TextInput } from 'react-native';

export default class App extends React.Component {
  render() {
    return (
      <View>
        <TextInput
          multiline
          style={{
            margin: 30,
            lineHeight: 100,
            borderColor: 'black',
            borderWidth: 1,
          }}
        />
      </View>
    );
  }
}
```

![image](https://user-images.githubusercontent.com/666810/60787754-28a02780-a19e-11e9-8b6a-9633700db7c2.png)

![image](https://user-images.githubusercontent.com/666810/60787810-5c7b4d00-a19e-11e9-8a3f-650e407ba9f2.png)

React Native version:
expo SDK 33.0 => RN 0.59.8

## Steps To Reproduce
1.Render TextInput with ```multiline=true``` and ```style={ lineHeight: <Number> }```

Describe what you expected to happen:
```lineHeight``` should be applied to TextInput contents effectively allowing space to be applied between lines of text.

Snack, code example, or link to a repository:
https://snack.expo.io/@njdancer/b91e88

**Comment by holden-caulfield** [comment]
This is happening to me as well on iOS with RN 0.59.2

**Comment by likern** [comment]
Can confirm on RN version 60.

**Comment by AfrazHussain** [comment]
Still exists in RN v0.61. I have tried fixing this on my fork, but to no avail. Is anyone else willing to discuss this issue?
