### ISSUE TITLE
localhost stuck loading from localhost:8081 on windows

### ISSUE THREAD

**Issue by SergeyMelnyk** [facebook/react-native#25551]
localhost stuck loading from localhost:8081 on **windows10**

after "react-native run-android" I have this:

![94bf49f8ec](https://user-images.githubusercontent.com/39995312/60840809-f95adc00-a1d8-11e9-97fa-7fef45589a65.jpg)
![f1c0dfdfd2](https://user-images.githubusercontent.com/39995312/60840810-f95adc00-a1d8-11e9-8cae-c54da98afd02.jpg)
![Screenshot_2019-07-08-23-31-51-101_com neact](https://user-images.githubusercontent.com/39995312/60840811-f9f37280-a1d8-11e9-9da0-cff568101de8.png)

and after nothing happend

**Comment by hasannizamani** [comment]
Facing the same issue here, using RN 0.60.0 clean new app. Takes a really long time to build and run.

**Comment by SergeyMelnyk** [comment]
> Facing the same issue here, using RN 0.60.0 clean new app. Takes a really long time to build and run.

what happened at the end, did you wait for the successful end? how long it took?

**Comment by hasannizamani** [comment]
> > Facing the same issue here, using RN 0.60.0 clean new app. Takes a really long time to build and run.
> 
> what happened at the end, did you wait for the successful end? how long it took?

Haven't been able to fix the issue yet, switched back to the older version for now.

**Comment by mcoeur** [comment]
I had the exact same issue on OSX 10.14.
The terminal seemed stuck on "Loading dependency graph..." and the node process was using more than 12Gb of RAM.
After waiting ~5 minutes, it finally completed and I was able to reload the app on the simulator.

**Comment by Osamasomy** [comment]
Node v 12.5. > take alot of memory
Node v 12.4  works for me. its works fine now and i think i found only this solution after spending alot of time on this problem.
