### ISSUE TITLE
CheckBox deprecation warning should be removed

### ISSUE THREAD

**Issue by mjmasn** [facebook/react-native#25558]
Upgrading to React Native 0.60.0 gives the following yellow box warning when running the app:

```
ExceptionsManager.js:94 Warning: CheckBox has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from '@react-native-community/checkbox' instead of 'react-native'. See https://github.com/react-native-community/react-native-checkbox
```

That would be great, except that `@react-native-community/checkbox` has never been published, and it looks like that's been an issue since March (https://github.com/react-native-community/react-native-checkbox/issues/3)

Either the package should be published or the yellow box temporarily removed, to avoid confusion.

React Native version:
```
System:
    OS: Linux 4.15 Ubuntu 16.04.6 LTS (Xenial Xerus)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Memory: 899.83 MB / 15.54 GB
    Shell: 4.3.48 - /bin/bash
  Binaries:
    Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
    Yarn: 1.16.0 - /usr/bin/yarn
    npm: 5.6.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 22, 24, 26, 27, 28, 29
      Build Tools: 23.0.1, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.3, 28.0.2, 28.0.3, 29.0.0
      System Images: android-22 | Google APIs Intel x86 Atom_64, android-24 | Google APIs ARM 64 v8a, android-24 | Google APIs Intel x86 Atom, android-24 | Google APIs Intel x86 Atom_64, android-24 | Google Play Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64
      Android NDK: 17.1.4828580
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.0 => 0.60.0 
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-cli: 2.0.1
    react-native-create-library: 3.1.2
    react-native-git-upgrade: 0.2.7
```

## Steps To Reproduce

1. Create a new RN 0.60.0 app
2. Import and use `CheckBox` from 'react-native'
3. See deprecation warning
4. Try to run `yarn add @react-native-community/checkbox`
5. See that `@react-native-community/checkbox` has not yet been published

Describe what you expected to happen: 
The 'new' extracted CheckBox package to install correctly

Snack, code example, or link to a repository:
n/a

**Comment by nicholaslee119** [comment]
thanks for your report, I will publish it as soon as possible

**Comment by nicholaslee119** [comment]
https://www.npmjs.com/package/@react-native-community/checkbox
v0.1.0 is published. Please check it, if there is any problem, please let me know

**Comment by mjmasn** [comment]
@nicholaslee119 awesome, thank you! :tada:
