### ISSUE TITLE
Red Screen error on new initialized react-native app

### ISSUE THREAD

**Issue by ho-dor** [facebook/react-native#25563]
I initialized a new app using react-native and without making any changes, I got a red screen error "Properties must be an object"

Screenshot: - [https://drive.google.com/file/d/1-erzk1O-mZy6q-EuFBjE3qjhPgqmaMNA/view?usp=sharing](url)

React Native version:

  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
      Memory: 3.24 GB / 7.85 GB
    Binaries:
      Yarn: 1.16.0 - C:\Users\hp\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5522156

Java version - 8 
node - 10.15.3 
react-native - 0.57.3

## Steps To Reproduce

1.Create a new app with react-native  0.57.3
2. react-native run-android

Describe what you expected to happen:

App to run successfully

Snack, code example, or link to a repository:

 [https://stackoverflow.com/questions/56958587/property-description-must-be-an-object-red-screen-error-on-new-react-native-app](url)

**Comment by sabarinathen** [comment]
I am also having the same issue faced event creating a sample project error shown as property description must be an object on red screen error.

**Comment by develgooapps** [comment]
I am also having the same problem, the weirdest thing is that if i turn on debug mode it works fine.

**Comment by geekazoid-at** [comment]
I am getting the same error on an already established project, just by running yarn install, having a few minor dependency upgrades. Not sure which one causes the issue yet...

**Comment by fdwcomune** [comment]
I'm getting the same issue, only on android and only while the debugger is not open. Seems to be happening in `redux.js` line 569:
```

**Comment by develgooapps** [comment]
> I'm getting the same issue, only on android and only while the debugger is not open. Seems to be happening in `redux.js` line 569 for me:
> 
> ```js
> Object.defineProperty(target, key, Object.getOwnPropertyDescriptor(arguments[i], key));
> ```
> 
> I assume it's something to do with the JS environment on Android. I don't think its specifically a Redux issue.

I tried fixing the redux version to  "redux": "4.0.1", and in my project now works fine!  Hope your one does too, thank you for everything.

**Comment by fdwcomune** [comment]
> I tried fixing the redux version to "redux": "4.0.1", and in my project now works fine! Hope your one does too, thank you for everything.

Yes, reverting to `v4.0.1` of `Redux` resolved it for me as well, seems to be some issue with `v4.0.2` and/or `v4.0.3`.

**Comment by evandrogrm** [comment]
I think it because Android Q version, i will try Android Pie version to make sure

**Comment by fdwcomune** [comment]
Seems like there was an issue with Babel when v4.0.2 and v4.0.3 of Redux was built, causing the issue. A new version of Redux is out (v4.0.4) which should fix this, haven't tested it myself yet.

See [Redux issue 3468](https://github.com/reduxjs/redux/issues/3468)

**Comment by evandrogrm** [comment]
I solved it deleting node_modules and installing it again with npm instead of yarn because my docker project use npm on the executables.
Don't make sense, should do the same, but yeah :)
