### ISSUE TITLE
RN 0.60 & Windows 10 Memory leak

### ISSUE THREAD

**Issue by MAKARD** [facebook/react-native#25568]
ReactNative 0.60 didn't start the server on Windows 10. After a long time, all RAM has been used.

![picturemessage_0vc553nw hii](https://user-images.githubusercontent.com/25794983/60961469-e9e0ad80-a314-11e9-8105-63e5a03cbc4c.png)

React Native version:
System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 5.98 GB / 15.85 GB
  Binaries:
    Node: 12.5.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5522156
react-native: 0.60.0

## Steps To Reproduce

1. Get Windows 10.
2. react-native init Project.
3. cd /Project && npm start.

Describe what you expected to happen:
Project starts normally

Actual behavior:
Huge memory leak, unexpected termination

Related to [Issue 25551](https://github.com/facebook/react-native/issues/25551)

**Comment by louisch** [comment]
Can confirm this is also happening on Linux with a freshly created project.

React Native version:
System:
    OS: Linux 5.2 Arch Linux undefined
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 11.20 GB / 15.58 GB
    Shell: 5.7.1 - /usr/bin/zsh
  Binaries:
    Node: 12.5.0 - ~/.nvm/versions/node/v12.5.0/bin/node
    Yarn: 1.16.0 - /usr/bin/yarn
    npm: 6.10.0 - ~/.nvm/versions/node/v12.5.0/bin/npm
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.0 => 0.60.0

## Steps To Reproduce

1. Create fresh project using `npx react-native init <project-name>`
2. Start the bundler with `npm start`

[louisch/TestMemoryLeak](https://github.com/louisch/TestMemoryLeak)

![Screenshot_2019-07-11_10-25-46](https://user-images.githubusercontent.com/772346/61017927-8f545980-a3c7-11e9-92e0-7edd29d2b0d4.png)

**Comment by CarlosX4vier** [comment]
Same problem here, the computer crashes.

![aa](https://user-images.githubusercontent.com/5119506/61144569-8f2d8a00-a4ab-11e9-89ca-d25be6e67f6e.png)


    OS: Linux 4.15 elementary OS 5.0 Juno
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 5.89 GB / 7.58 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.6.0 - /usr/bin/node
    Yarn: 1.15.2 - ~/.yarn/bin/yarn
    npm: 6.9.0 - /usr/bin/npm
  SDKs:
    Android SDK:
      API Levels: 28
      Build Tools: 28.0.3
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.3 => 0.60.3 
  npmGlobalPackages:
    react-native-cli: 2.0.1

**Comment by hedikasmanto** [comment]
Same here
![image](https://user-images.githubusercontent.com/9128724/61195069-02bfd900-a6f0-11e9-86d3-49c25df523b6.png)

System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Memory: 1.44 GB / 8.00 GB
    Shell: 3.0.2 - /usr/local/bin/fish
  Binaries:
    Node: 12.6.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      API Levels: 28
      Build Tools: 28.0.3
      Android NDK: 17.1.4828580
  IDEs:
    Xcode: 10.2/10E125 - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.8.6 => 16.8.6 
    react-native: 0.60.3 => 0.60.3 
  npmGlobalPackages:
    react-native-cli: 2.0.1

**Comment by MAKARD** [comment]
@hedikasmanto No problems with macOS 10.14.5, seems something with system setup
![image](https://user-images.githubusercontent.com/25794983/61198879-7cea6080-a6e4-11e9-81f9-25183ae4e016.png)

System:
    OS: macOS 10.14.5
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 19.38 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3
      System Images: android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.0 => 0.60.0 
  npmGlobalPackages:
    react-native-cli: 2.0.1

**Comment by hedikasmanto** [comment]
Hmm. Confused. But if i downgrade to 0.59.x. It back to normal and no memory leak occurs

**Comment by hreinhardt** [comment]
Seems to be dependent on the node version. I'm getting memory leaks with node v12.6, but not node v10.16.

**Comment by MAKARD** [comment]
> Seems to be dependent on the node version. I'm getting memory leaks with node v12.6, but not node v10.16.

I tried to reproduce the issue with node 10 and 12 (via nvm) on Mac 10.14.5. Still no leaks.

![image](https://user-images.githubusercontent.com/25794983/61274238-0c127980-a7b4-11e9-9db7-783422c0875f.png)

![image](https://user-images.githubusercontent.com/25794983/61274332-49770700-a7b4-11e9-925c-350d53f599d2.png)

**Comment by louisch** [comment]
Maybe a watchman issue? I notice all the reports here except @hedikasmanto don't have watchman installed.

**Comment by thymikee** [comment]
This is a Node >=12.5 issue, see: https://github.com/react-native-community/cli/issues/485#issuecomment-509210382. Feel free to send these report to the Node.js team
