### ISSUE TITLE
get BackAndroid() function deprecation issue RN 0.59.10

### ISSUE THREAD

**Issue by nadirHomeFriend** [facebook/react-native#25579]
React Native version:

## Steps To Reproduce

1. using RN 0.59.10 , launch the app on Android/iOS simulator and can see the issue

shown error: BackAndroid is deprecated and has been removed from this package. Use BackHandler instead, stack:

**Comment by ecreeth** [comment]
@nadirHomeFriend It is not an error. `BackAndroid()` has been removed and you must use [`BackHandler`](https://facebook.github.io/react-native/docs/backhandler) instead

**Comment by kelset** [comment]
thanks @ecreeth 	👍
