### ISSUE TITLE
[DevTools] In-place edit in Chrome DevTools for React-Native?

### ISSUE THREAD

**Issue by SidBala** [facebook/react-native#2557]
![screen shot 2015-09-04 at 1 12 16 pm](https://cloud.githubusercontent.com/assets/174933/9693624/aaad1462-5306-11e5-82b6-2462e245094a.png)

Trying out the Chrome Dev Tools for React-Native. Does in-line editing of the properties supported? In the above screenshot, can I change the "Welcome to ReactNative!" Text in devtools itself?

If I double click on the text beside "children:", it seems to allow me to edit, but the text goes right back to original once that box loses focus.

The style parameters seem to stick, however they don't actually change the UI in the simulator. What am I doing wrong?

**Comment by brentvatne** [comment]
@SidBala - this is a bit confusing at the moment, you'll need to actually select the underlying component, eg `RCTView` and `RCTText` and edit the style on those

cc @jaredly

**Comment by spicyj** [comment]
@brentvatne Do you know why display names aren't getting added? (See https://github.com/facebook/react-devtools/issues/177 too.)

**Comment by ide** [comment]
We may need to enable Babel's "react.displayName" option cc @amasad

**Comment by spicyj** [comment]
Oh, it looks like it is indeed missing. I remembered us enabling it but I guess that was on www, not here. I'll send a diff to fix.

(cc @udfalkso)

**Comment by udfalkso** [comment]
@spicyj Thanks!!

**Comment by brentvatne** [comment]
Created an issue here to track this: https://github.com/facebook/react-devtools/issues/206

**Comment by spicyj** [comment]
(Done in 93b9329b758cde3e921b26e11ba91d9700d2a06d.)
