### ISSUE TITLE
React native doesn't work in android wear

### ISSUE THREAD

**Issue by Vijay-mRoads** [facebook/react-native#25580]
React Native version:

React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
      Memory: 251.11 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      Yarn: 1.3.2 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 22, 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.1, 27.0.3, 28.0.2, 28.0.3
        System Images: android-23 | Google APIs Intel x86 Atom, android-24 | Google APIs Intel x86 Atom, android-25 | Android Wear Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-P | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.1 => 16.6.1 
      react-native: 0.57.5 => 0.57.5 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-component-generator: 1.1.5
      react-native-webrtc: 1.58.3

Describe what you expected to happen:

Created a react native app using `react-native init`

Added necessary android watch manifest changes. App keeps crashing with below error

`Inspector doesn't work in open source yet
    java.lang.UnsatisfiedLinkError: No implementation found for com.facebook.react.bridge.Inspector com.facebook.react.bridge.Inspector.instance() (tried Java_com_facebook_react_bridge_Inspector_instance and Java_com_facebook_react_bridge_Inspector_instance__)`

**Comment by mhrpatel12** [comment]
@Vijay-mRoads don't upgrade to 0.60. Things might get even worse!

**Comment by Vijay-mRoads** [comment]
Tried running in react-native v60 and it failed with same error. Downgraded to 57.5 and still no luck

**Comment by Vijay-mRoads** [comment]
I am able to get it working. Unfortunately, the app doesn't load in debug mode and works in release mode. I am getting below error in debug mode


```
2019-08-07 04:31:42.441 7649-7844/com.onedinewearrn E/unknown:ReactNative: Exception in native call
    java.lang.UnsupportedOperationException
        at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:241)
```

I understand that android wear doesn't have webviews. Is there any other way to connect to bundler without webview?
