### ISSUE TITLE
Can't get most elevated app state from dictionary 

### ISSUE THREAD

**Issue by liuhaiqing12** [facebook/react-native#25587]
Hi. My app in debug mode works and when I release the app, it crashes. I tried to check certificates, remove logs and some other suggestions. I update my XCODE to version 10.2.1 and still the issue is same.

When I click on the app I am seeing 2 error in XCODE logs.

HW kbd: Failed to set (null) as keyboard focus

Can't get most elevated app state from dictionary {
BKSApplicationStateExtensionKey = 0;
SBApplicationStateDisplayIDKey = "com. {// name of the app was here}";
SBApplicationStateKey = 0;
SBApplicationStateProcessIDKey = 343;
SBApplicationStateRunningReasonsKey = (
{
SBApplicationStateRunningReasonAssertionIdentifierKey = UIApplicationLaunch;
SBApplicationStateRunningReasonAssertionReasonKey = 10000;
},
{
SBApplicationStateRunningReasonAssertionIdentifierKey = Resume;
SBApplicationStateRunningReasonAssertionReasonKey = 10000;
}
);
}

I read a lot of posts and test the suggestions but nothing worked until now.
How can I solve this problem?
Please help me.
Thanks

**Comment by J-rodrigues** [comment]
@liuhaiqing12, did you get any solution to the problem?

**Comment by franzejr** [comment]
@liuhaiqing12 , did you get it fixed?

**Comment by NicoBru31** [comment]
Hi @liuhaiqing12 did you solve this issue ?

**Comment by orther** [comment]
Bump, did you find the problem and/or a solution? I am running into same issue.
