### ISSUE TITLE
react-native upgrade command thinks 0.59.10 < 0.59.8

### ISSUE THREAD

**Issue by sourabhv** [facebook/react-native#25588]
Running `$ react-native upgrade 0.59.10` on version `0.59.8` gives the error:

```
error Trying to upgrade from newer version "0.59.8" to older "0.59.10"
```
React Native version:

```
info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 1.47 GB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.14.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.10.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 27, 28
        Build Tools: 28.0.3
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.8 => 0.59.8 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-android-in-app-update: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      react-native: 0.59.5
```

**Comment by trickeyd** [comment]
Haha! react-native-bot sure showed you! 🤣 

I'm about to upgrade to 59.10 too so guess I'll do it manually. Thx for the heads up.

**Comment by sourabhv** [comment]
@facebook you bot sucks. :-1:

**Comment by faustoct** [comment]
Impossible to update react-native package at medium large size projects.

**Comment by sourabhv** [comment]
@faustoct You can use https://react-native-community.github.io/upgrade-helper/ to upgrade manually.

**Comment by owlstack** [comment]
This is still an issue: 
error Trying to upgrade from newer version "0.59.8" to older "0.59.10"

React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
      Memory: 184.16 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.9.1 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.10.2 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.8 => 0.59.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

I don't want to upgrade to 0.60.0 yet

**Comment by sourabhv** [comment]
@owlstack thankfully the change is not huge and can be done easily using upgrade helper

**Comment by faustoct** [comment]
@sourabhv just got here after months
I followed the link and upgraded from 0.58 to 0.61
at least stopped bundle js automatically on android debug/dev
