### ISSUE TITLE
ScrollView, method scrollTo, parameter duration doesn't working

### ISSUE THREAD

**Issue by ivan-kolesov** [facebook/react-native#25589]
Method scrollTo ( https://github.com/facebook/react-native-website/blob/master/docs/scrollview.md ) has parameter duration, that can be applied to android devices. But source codes don't have any realization https://github.com/facebook/react-native/blob/0.59-stable/Libraries/Components/ScrollView/ScrollView.js#L744-L748

React Native version:
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 1.62 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.6.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 28
        Build Tools: 26.0.3, 28.0.3
        System Images: android-23 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.9 => 0.59.9 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

## Steps To Reproduce

1. open sources at https://github.com/facebook/react-native/blob/0.59-stable/Libraries/Components/ScrollView/ScrollView.js#L744-L748 and there are no `duration` parameter

I want to customize scroll speed.

**Comment by ivan-kolesov** [comment]
> It looks like you are using an older version of React Native. Please update to the [latest release, v0.60](https://github.com/facebook/react-native/releases/tag/v0.60.0) and verify if the issue still exists.
> 
> The "Resolution: Old Version" label will be removed automatically once you edit your original post with the results of running `react-native info` on a project using the latest release.

Sources 0.60 doesn't contain `duration` parameter also: https://github.com/facebook/react-native/blob/0.60-stable/Libraries/Components/ScrollView/ScrollView.js#L756-L760

**Comment by ecreeth** [comment]
@ivan-kolesov the `duration` prop was deleted. See the [PR](https://github.com/facebook/react-native/commit/4c69ccd0fb55e994bd4604e5194206e442ec5958) here. I'm going to make a PR to eliminate that property right now.

**Comment by ecreeth** [comment]
@kelset this issue is a candidate to be closed!
