### ISSUE TITLE
[tvOS] No longer able to explicitly set focus using `hasTVPreferredFocus` since RN 0.59

### ISSUE THREAD

**Issue by pamtaro** [facebook/react-native#25584]
This PR made a change to fix a Cocoapods build issue - https://github.com/facebook/react-native/pull/21596
which removed the line `[(RCTRootView *)rootview setReactPreferredFocusedView:self];` from the `setHasTVPreferredFocus` method in `RCTTVView.m`, but it ended up breaking the feature that allowed programmatically setting focus for tvOS.

The assumption in the earlier PR about the function  being removed from the `RCTRootViewInternal.h` is incorrect, it's still there and hasn't been touched since it was added - https://github.com/facebook/react-native/blame/45b0907f619f455825f459838615a5a7cc59a204/React/Base/RCTRootViewInternal.h#L29

It was wrapped in an `#if TARGET_OS_TV` preprocessor directive, so it wouldn't have been compiled for non **tvOS** builds. The issue referenced in the earlier PR should have removed the `RCTTVView.m` as a target for non-tvOS builds in the Podfile instead.

React Native version: 0.59.0+

## Steps To Reproduce

1. In a RN (older than 0.59) tvOS app, add a bunch of `TouchableOpacity` components and apply the `hasTVPreferredFocus` property to one of them (preferably not the first one since it would be the default focused element anyway).
2. Setting explicit focus works in older RN.
3. Upgrade RN to 0.59+ and run app again.
4. Setting explicit focus no longer works.
5. In Xcode, open up the `RCTTVView.m` file from the React Library in your app's xcode project.
6. Add back in the line that was removed to call `setReactPreferredFocusedView` again.
7. Rebuild and run app.
8. Setting explicit focus will work again.

Describe what you expected to happen:
Setting the  `hasTVPreferredFocus` property should allow for programmatic focus of Touchable components.

Snack, code example, or link to a repository:

**Comment by pamtaro** [comment]
This is still an issue and should be kept open

**Comment by dlowder-salesforce** [comment]
@pamtaro sorry for not seeing this issue in the main RN repo.  This is fixed in the new react-native-tvos repo: https://github.com/react-native-community/react-native-tvos/commit/d9870778e9b8c0178ed34abd916f7250f8270c06#diff-8b97b9ce9e5bf7053b14a0d6f354c175
