### ISSUE TITLE
<FlastList /> overflow visible is not working in Android

### ISSUE THREAD

**Issue by pixelize** [facebook/react-native#25592]
React Native version:
0.59.8
## Steps To Reproduce

1. Create a flatlist
2. Add an elevation to the item & overflow: "hidden" on the `<FlatList />`

Describe what you expected to happen:
The overflow seems working fine on iOS because we can see the card shadows but on Android, elevation is not visible because `overflow: hidden` seems not working on the `<FlatList />`

![ios](https://user-images.githubusercontent.com/2931627/61056497-bd4f9300-a3f3-11e9-82c2-ff71934c0ad6.png)
![android](https://user-images.githubusercontent.com/2931627/61056710-20d9c080-a3f4-11e9-9ea5-1832556cd8b0.png)

Snack, code example, or link to a repository:
https://snack.expo.io/@pixelize_/flatlist-overflow-bug

**Comment by RageBill** [comment]
I think this is the design of the Android platform.

I have tried doing overflow with Image and FlatList, and neither of them work on Android - it seems this is not supported by Android at all.

You can find more insight (and a workaround) in https://github.com/facebook/react-native/issues/6802.

**Comment by pixelize** [comment]
@RageBill thanks for the insight ;)
