### ISSUE TITLE
[0.60.0] Regression in border radius rendering

### ISSUE THREAD

**Issue by mjmasn** [facebook/react-native#25591]
Edit: This is on Android, I haven't tested iOS.

Border radius rendering is broken in 0.60.0 when the border radius is less than or equal to the border width.

See screenshots:

| 0.59.10 | 0.60.0 |
|---|---|
| ![Screenshot_20190711-113401_BorderRadius59](https://user-images.githubusercontent.com/2977095/61044261-26251400-a3d0-11e9-84fd-ec398ab022ad.jpg) | ![Screenshot_20190711-113316_BorderRadius60](https://user-images.githubusercontent.com/2977095/61044262-26251400-a3d0-11e9-9135-23e5050859a7.jpg) |

React Native version:
```
System:
    OS: Linux 4.15 Ubuntu 16.04.6 LTS (Xenial Xerus)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Memory: 674.33 MB / 15.54 GB
    Shell: 4.3.48 - /bin/bash
  Binaries:
    Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
    Yarn: 1.16.0 - /usr/bin/yarn
    npm: 5.6.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 22, 24, 26, 27, 28, 29
      Build Tools: 23.0.1, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.3, 28.0.2, 28.0.3, 29.0.0
      System Images: android-22 | Google APIs Intel x86 Atom_64, android-24 | Google APIs ARM 64 v8a, android-24 | Google APIs Intel x86 Atom, android-24 | Google APIs Intel x86 Atom_64, android-24 | Google Play Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64
      Android NDK: 17.1.4828580
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.0 => 0.60.0 
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-cli: 2.0.1
    react-native-create-library: 3.1.2
    react-native-git-upgrade: 0.2.7
```

## Steps To Reproduce

1. Create a react-native 0.60.0 app
2. Create a view with a border width of `x` and a border radius <= `x`
3. Rounded corners are not rendered :sob:  

Describe what you expected to happen:
Rendering to be the same as in 0.59.10, where rounded corners are rendered correctly.

Snack, code example, or link to a repository:
https://github.com/mjmasn/BorderRadius59 (working)
https://github.com/mjmasn/BorderRadius60 (regression)

**Comment by ecreeth** [comment]
@mjmasn I have copied your code in `snack` and it has worked well. See in [snack](https://snack.expo.io/rJlqL24bB)
![image](https://user-images.githubusercontent.com/20761166/61053904-6c707800-a3bc-11e9-8f39-38a0735f02c1.png)

**Comment by JonnyBurger** [comment]
@ecreeth Expo SDK33 is still on React Native 0.59.0.

**Comment by cabelitos** [comment]
Hello @JonnyBurger and @mjmasn I submitted a fix for this problem. Comments and suggestions are appreciated.

https://github.com/facebook/react-native/pull/25626

thank you very much.
