### ISSUE TITLE
Percentage doesn't work with flatlist when horizontal is true

### ISSUE THREAD

**Issue by junaiid-khattak** [facebook/react-native#25602]
Specifying item width in percentages doesn't work when using flatlist with horizontal set to true. I was wondering if it is a bug or am i missing something. This was reported earlier #17796
 in 0.52 too but got closed without resolution. 
 
react: 16.8.6
react-native: 0.60.0
Ubuntu 16.04.6 LTS

platform:
android (haven't tried on iOS)

**Comment by AntoineDoubovetzky** [comment]
@junaiid-khattak
I think that when you specify item width in percentage, it takes percentage of the parent width, not the screen width.
When your `FlatList` is horizontal, there is no parent width so it can't work.
If you want to get the screen width, you need to use `Dimensions` (https://facebook.github.io/react-native/docs/dimensions)
