### ISSUE TITLE
Android:Could not open developer menu at an android device(A920)

### ISSUE THREAD

**Issue by ouxuwen** [facebook/react-native#25604]
We are going to develop an android app for an android device( called A920 ), But we can not open the developer in real machine:
1. Using `Ctrl + M`  does not appearing anything.
2. Using the `adb shell input keyevent 82` command does not do anything. I tried going into adb shell and running the command input` keyevent 82`.
3. Shaking the device  r does not bring up the menu by shaking the device.
4. This device does not have `menu button`.

Is there any other way for this device to show developer menu??

### Environment 
Windows7 
"react": "16.8.6",
"react-native": "0.60.3",
### Device 
Andoird 5.1.1

![image](https://user-images.githubusercontent.com/24316216/61110586-226dbc00-a4ba-11e9-94a6-825e2d3126df.png)

**Comment by shamyyl** [comment]
I have the same issue on Android with the same environment

**Comment by calebeoliveira** [comment]
Same issue here with a similar device with no accelerometer.

**Comment by calebeoliveira** [comment]
I created an Native Module with this code inside:

```java
    @ReactMethod
    public void openDevMenu() {
        ((ReactApplication) this.reactContext.getApplicationContext())
                .getReactNativeHost().getReactInstanceManager().getDevSupportManager()
                .showDevOptionsDialog();
    }
```

It still crashes the app in some options but is functional. I didn't found a better way to open that menu.
