### ISSUE TITLE
Xcode Crash on while installing node_modules 

### ISSUE THREAD

**Issue by waheed25** [facebook/react-native#25600]
I was working on app and it was working fine but certainly i noticed my Xcode got crashed then i tried to open my .xcodeproj file again but i was getting this message.
Every time i try to open .xcodeproj i got these messages
<img width="444" alt="Screenshot 2019-07-11 at 10 53 06 PM" src="https://user-images.githubusercontent.com/25927790/61074599-80a28c80-a431-11e9-8e64-b5092b1ad879.png">
<img width="429" alt="Screenshot 2019-07-11 at 11 18 12 PM" src="https://user-images.githubusercontent.com/25927790/61074898-3968cb80-a432-11e9-8550-90459522e94e.png">

Then i searched about the this crash issue and found most of the solution by deleting derivedData and xcuserdata i did this but no luck and tried many things but no luck.
After 4 days of searching and trying i decided clone new fresh copy from repository.
and when i opens it in Xocde i got surprised that it opened successfully then i try to install node_modules and while installing node-modules i observed that it got crashed again then for confirmation i did three to four times when there is no node_modules folder i can open my project but when i start installing node_modules Xcode got crashed every time i also tried with npm and yarn too but same behaviour.  
React Native version:
info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
      Memory: 71.00 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.3 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        API Levels: 22, 23, 24, 25, 26, 27, 28, 29
        Build Tools: 23.0.1, 26.0.2, 27.0.3, 28.0.3
        System Images: android-18 | Google APIs ARM EABI v7a, android-21 | Google APIs ARM EABI v7a, android-21 | Google APIs Intel x86 Atom, android-21 | Google APIs Intel x86 Atom_64, android-22 | Google APIs ARM EABI v7a, android-22 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom_64, android-23 | Google APIs ARM EABI v7a, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-24 | Google APIs ARM EABI v7a, android-24 | Google APIs Intel x86 Atom, android-24 | Google APIs Intel x86 Atom_64, android-25 | Google APIs ARM 64 v8a, android-25 | Google APIs ARM EABI v7a, android-25 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom_64, android-25 | Google Play Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.0 => 16.6.0 
      react-native: ^0.59.8 => 0.59.10 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

## Steps To Reproduce

1. open project inside Xcode without node-modules folder.
2. then start installing node-module.
3. Xcode will crash automatically.

run project without installing node_modules.

Describe what you expected to happen:
Open .xcodeproj file and install node-modules normally.

Snack, code example, or link to a repository:

https://stackoverflow.com/questions/56978784/xcode-crash-on-opening-xcodeproj-file

**Comment by chrisspankroy** [comment]
This isn't really a fix, but why don't you do `npm install` before you open Xcode? Xcode needs a bunch of things in `node_modules' so I wouldn't be surprised if it crashes when you do `npm install`. Xcode definitely shouldn't crash, but this seems like more of a problem with Xcode itself than React Native

**Comment by waheed25** [comment]
@chrisspankroy Actually the problem was when i opens xcode with having node modules folder app crashes on start but when i open without node modules then i can open project.

**Comment by chrisspankroy** [comment]
Ah OK. I'd change the description to word that a little better then

**Comment by iamtb** [comment]
the same :(( how to fix ??? please

**Comment by waheed25** [comment]
@iamtb can you please explain what you already tried and may be i can help you more if you show me your Packege.json.

**Comment by okarlsson** [comment]
I had this exact problem which was caused by a specific package in my node_modules folder. After upgrading [react-native-fast-image](https://github.com/DylanVann/react-native-fast-image) from `^5.1.2` -> `^7.0.2` xcode just crashed when opening the workspace. I then tried to downgrade to `^6.0.3` and that solved the problem.

Seems to be a known issue: DylanVann/react-native-fast-image#527

**Comment by waheed25** [comment]
Yeah @okarlsson you are right. After lots of version change i found this problem with "react-native-fast-image" version so i move back to previous version and it works fine.

**Comment by obsidianart** [comment]
2 hours trying to figure out what was going on. Unfortunately it happened after I formatted my mac so I didn't have a full understanding of where to look for :D

**Comment by Desintegrator** [comment]
same issue, downgrade to <7.0 is not a solution because of AndroidX support
