### ISSUE TITLE
We need better handling of multiple inputs with secureTextEntry on iOS 12+

### ISSUE THREAD

**Issue by d3vhound** [facebook/react-native#25603]
So before iOS 12 we were able to have multiple inputs with `secureTextEntry` and the auto suggestions were correct or not there unless specified in props. It seems now with iOS 12 and above that if you render 3 inputs: 1 without secureTextEntry first, then the other 2 with secureTextEntry last, that no matter what, iOS 12> will always think the input before the first secureTextEntry input is an email field and will show email suggestions. iOS will also think that the second secureTextEntry input is also an email field and will show email suggestions. There's no way to hide it except for only have 1 secureTextEntry input.  Even then the suggestions are determined by iOS and props are almost useless. This wasn't the case with iOS 11. 

Reproduction:
https://snack.expo.io/BkxZysBZB

As you can see, when the iOS version is less than 12, this works as intended. We can have multiple inputs with the secureTextEntry prop and it will not show email suggestions on them.

Now, run that same snack on a physical device on the expo app that is on iOS 12+

Ignoring the autofill feature, you can see that by default, iOS will show auto suggestions for email on the second secureTextEntry input. 

My questions to the react-native core team is: How do you handle multiple secureTextEntry inputs in iOS 12? It seems that we have to put up with the wrong auto suggestions types and just deal with it.

(Pictures for clarity)

iOS 11 first input:
<img width="330" alt="Screen Shot 2019-07-12 at 1 03 18 AM" src="https://user-images.githubusercontent.com/17565159/61105931-0b3eb800-a441-11e9-8813-d519bf84c9e6.png">

iOS 12 first input:
<img width="330" alt="Screen Shot 2019-07-12 at 1 03 18 AM" src="https://user-images.githubusercontent.com/17565159/61105961-2b6e7700-a441-11e9-91a4-7a04cc4db471.PNG">

iOS 11 third input:
<img width="339" alt="Screen Shot 2019-07-12 at 1 02 55 AM" src="https://user-images.githubusercontent.com/17565159/61105986-4345fb00-a441-11e9-91b1-fdf18edf9749.png">

iOS 12 third input:
<img width="339" alt="Screen Shot 2019-07-12 at 1 02 55 AM" src="https://user-images.githubusercontent.com/17565159/61106046-78524d80-a441-11e9-8211-4af9622e745c.PNG">

**Comment by janicduplessis** [comment]
You can use https://facebook.github.io/react-native/docs/textinput#textcontenttype to hint the OS about the type of input

**Comment by d3vhound** [comment]
That’s the thing, on iOS 12 that prop and the autoCorrect one don’t work in regards to not showing the email suggestions on the 2nd secureTextEntry input.

**Comment by janicduplessis** [comment]
Strange, maybe it is a bug in UIKit, not sure if we can do anything about it :(

**Comment by hbarylskyi** [comment]
Yeah, in the app I'm working on currently this problem appears even if I have just two inputs: email and password. Sometimes if I move focus from email to password and back, the password suggestion tooltip appears when email field is focused, and email suggestion tooltip appears when password is focused. 

I'm using 0.60.4

**Comment by diamont1001** [comment]
I have the same issue :(

**Comment by hbarylskyi** [comment]
Still an issue. iOS 13.2

**Comment by hbarylskyi** [comment]
@hramos what does 'Needs author feedback' tag mean?

**Comment by hramos** [comment]
Fixed the label - this issue does not make use of the template, and it's missing necessary information. @hbarylskyi feel free to open a new issue that makes use of the issue template, as this one might get closed if it's not edited soon.
