### ISSUE TITLE
[Navigator.NavigationBar] as a custom component

### ISSUE THREAD

**Issue by julianocomg** [facebook/react-native#2560]
I'm trying to use a custom component for Navigator.NavigationBar, but it's not transitioning to the next route...

I'm passing `{...this.props}`, the custom component is updating normally with the new props, but the NavigationBar itself doesn't. The navbar stays the same, with the first route data....

I'm using React Native v0.10.1

Working:
```
<Navigator
  renderScene={this.renderScene.bind(this)}
  navigationBar={
    <Navigator.NavigationBar routeMapper={this.getRouteMapper()} />
  }
/>
```
![working](http://i.imgur.com/dWUGNRh.gif)

<br>
Not working :(
```
class Navbar extends React.Component {
  render() {
    return <Navigator.NavigationBar {...this.props} />
  }
}

<Navigator
  renderScene={this.renderScene.bind(this)}
  navigationBar={
    <Navbar routeMapper={this.getRouteMapper()} />
  }
/>
```
![notWorking](http://i.imgur.com/ZViNhZ8.gif)

**Comment by alvaromb** [comment]
Same here! :+1:

**Comment by alvaromb** [comment]
This is my navigation bar component

```javascript
import React, { Component, Navigator, TouchableOpacity, Text, PropTypes, StyleSheet } from 'react-native'

class SBNavBar extends Component {
  render () {
    const routeMapper = {
      LeftButton: (route, navigator, index, navState) => {
        if (index === 0) {
          return null
        }
        const previousRoute = navState.routeStack[index - 1]
        return (
          <TouchableOpacity
            onPress={() => navigator.pop()}>
            <Text style={styles.navText}>
              {previousRoute.title}
            </Text>
          </TouchableOpacity>
        )
      },
      RightButton: (route, navigator, index, navState) => {
        if (route.rightElement) {
          return route.rightElement
        }
      },
      Title: (route, navigator, index, navState) => {
        return (
          <Text style={styles.navText}>{route.title}</Text>
        )
      }
    }
    return (
      <Navigator.NavigationBar
        style={styles.navBar}
        routeMapper={routeMapper}
        {...this.props}
      />
    )
  }
}

SBNavBar.propTypes = {
  ...Navigator.NavigationBar.propTypes
}

const styles = StyleSheet.create({
  navBar: { ... },
  navText: { ... },
})

export default SBNavBar
```

**Comment by julianocomg** [comment]
Yeah, It's definitely a bug :smile:

**Comment by alvaromb** [comment]
Is it confirmed @julianocomg?

**Comment by julianocomg** [comment]
@alvaromb No, but I've tried everything... I also checked the `NavigatorNavigationBar.js` and everything seems to be correct. It's an objective-c component bug, maybe...

**Comment by brentvatne** [comment]
@julianocomg @alvaromb - is this broken on the UIExplorer NavigationBar example?

**Comment by julianocomg** [comment]
@brentvatne the UIExplorer example don't use a wrapped navbar :/

**Comment by brentvatne** [comment]
Ah I see. I think the problem is that you need to make sure that you pass along function calls through to the underlying component.

For example, notice here how `updateProgress` is called on the navbar: https://github.com/brentvatne/react-native/blob/uiexplorer-image-editing-typo/Libraries/CustomComponents/Navigator/Navigator.js#L834-L841

So your custom component code:

```javascript
class Navbar extends React.Component {
  updateProgress(progress, fromIndex, toIndex) {
    this._nav.updateProgress(progress, fromIndex, toIndex);
  }

  render() {
    return <Navigator.NavigationBar {...this.props} ref={(nav) => { this._nav = nav; }} />
  }
}

<Navigator
  renderScene={this.renderScene.bind(this)}
  navigationBar={
    <Navbar routeMapper={this.getRouteMapper()} />
  }
/>
```

that should solve your problem. Let me know if it doesn't and I'll reopen

**Comment by julianocomg** [comment]
@brentvatne Thank you Brent, it works!!! :raised_hands:

**Comment by alvaromb** [comment]
Awesome @brentvatne :trophy: !

**Comment by steveleec** [comment]
@julianocomg would you mind post the entire example of that new abstraction of NavBar?

**Comment by Charca** [comment]
If you just want to have your custom NavBar in a separate module, you don't need to wrap it in a new component, and you don't need to proxy all methods of the original component. Unless you really need to wrap the NavigationBar in a React component, I recommend modularize it like this:

```javascript
// CustomNavBar.js

var styles = { ... };
var NavigationBarRouteMapper = { ... };

module.exports = (
  <Navigator.NavigationBar
    style={styles.navBar}
    routeMapper={NavigationBarRouteMapper} />
);
```

And use it in your component like:

```javascript
// MyComponent.js

CustomNavBar = require('./CustomNavBar');

class MyComponent extends React.Component {
  render() {
    return(
      <Navigator
        initialRoute={ ... }
        renderScene={ ... }
        navigationBar={NavBar} />
    )
  }
}
```

**Comment by badboytherock** [comment]
@Charca , Thx man! It works like a charm.

**Comment by jackdweber** [comment]
Do you have your styles for this navbar? I've been trying to style mine but it is not listening.
