### ISSUE TITLE
Is navigator.geolocation supported in version 0.60?

### ISSUE THREAD

**Issue by MajkellVZ** [facebook/react-native#25606]
When I am using the navigator.geolocation.watchPosition on RN version 0.60 i shows a TypeError: Undefined is not an object (evaluating 'navigator.geolocation.watchPosition')
Meanwhile in version 0.57 it works just fine.

React Native version:
System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
    Memory: 2.55 GB / 7.90 GB
  Binaries:
    Node: 12.4.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - C:\Users\Scorpion\AppData\Roaming\npm\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5522156

I expect it get me latitude and longitude but instead it shows me the error.

```
handleLocation = () => {
        this.watchID = navigator.geolocation.watchPosition(
            (position) => {
                this.setState({
                    latitude: position.coords.latitude,
                    longitude: position.coords.longitude,
                    error: null,
                });
            },
            (error) => this.setState({ error: error.message }),
            { enableHighAccuracy: false, timeout: 2000, maximumAge: 100, distanceFilter: 10 },
        );
```

**Comment by jsaraiva** [comment]
Since RN 0.60, the Geolocation module was migrated out of RN Core.
You can find it at [https://github.com/react-native-community/react-native-geolocation](url)

Cheers!

**Comment by cpojer** [comment]
See the comment above ^

**Comment by plaa** [comment]
The documentation is then out-of-date, as it still says you don't need to import anything to use geolocation in 0.61:
https://facebook.github.io/react-native/docs/geolocation

**Comment by fabriziobertoglio1987** [comment]
https://github.com/react-native-community/react-native-geolocation/issues/56

**Comment by fabriziobertoglio1987** [comment]
#https://github.com/react-native-community/react-native-geolocation/issues/56

**Comment by Amir-Abbasy-k** [comment]
> 
> 
> Hello.
> 
> Since RN 0.60, the Geolocation module was migrated out of RN Core.
> You can find it at https://github.com/react-native-community/react-native-geolocation
> 
> Cheers!

It worked me, after after react-native run-android
