### ISSUE TITLE
Can't upgrade from 0.59.9 to 0.60.0 with `react-native upgrade`

### ISSUE THREAD

**Issue by maximedupre** [facebook/react-native#25614]
React Native version:

    System:
      OS: macOS 10.14.5
      CPU: (8) x64 Intel(R) Core(TM) i7-3820QM CPU @ 2.70GHz
      Memory: 2.94 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.6.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.9 => 0.59.9 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Steps To Reproduce

`react-native upgrade 0.60.0 --verbose`

	info Fetching diff between v0.59.9 and v0.60.0...
	error Cannot read property 'toLowerCase' of undefined
	debug TypeError: Cannot read property 'toLowerCase' of undefined
		at getPatch (/Users/maximedupre/Desktop/Dropbox/Programming/iphone-app/fe/node_modules/@react-native-community/cli/build/commands/upgrade/upgrade.js:108:121)
		at process.internalTickCallback (internal/process/next_tick.js:77:7)

**Comment by kelset** [comment]
👋

it seems that this is an issue connected to the CLI - but from the [docs](https://github.com/react-native-community/cli/blob/master/docs/commands.md#upgrade) I think it may be because you can't pass the verbose flag.
Moreover, you should upgrade to 0.60.3 instead.

**Comment by maximedupre** [comment]
`react-native upgrade 0.60.3` does not work. I will open a ticket on the https://github.com/react-native-community/cli repo. Thanks!
