### ISSUE TITLE
--projectDir is not supported any more

### ISSUE THREAD

**Issue by taoqf** [facebook/react-native#25628]
When upgrade to 0.60, I got this error when I run `react-native link`:

```sh
error: unknown option `--projectRoot'
```

React Native version:

0.60.0 0.60.1 0.60.2 0.60.3

## Steps To Reproduce

Just link any package with --projectRoot flag

```sh
react-native link --projectRoot ./ react-native-webview
```

Describe what you expected to happen:

I with --projectRoot flag back, it's useful to me.

Snack, code example, or link to a repository:

```sh
react-native link --projectRoot ./ react-native-webview
```

```sh
react-native link --projectRoot ./ react-native-webview
```

**Comment by RobinCsl** [comment]
Hi @taoqf,

It seems that the behaviour for linking native dependencies has changed in RN 0.60. See the blog post announcing its release: https://facebook.github.io/react-native/blog/2019/07/03/version-60#native-modules-are-now-autolinked

Running `react-native link --help` yields the following:
```
react-native link [packageName]

links assets and optionally native modules

Options:
  --platforms [list]  Scope linking to specified platforms
  --all [boolean]     Link all native modules and assets
  -h, --help 
```

so it does look like option `projectRoot` was removed from the CLI.

I believe this is the relevant documentation you need: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md

Hope that helps!
