### ISSUE TITLE
Why 0.60 is buggy as hell?

### ISSUE THREAD

**Issue by Mikecoon** [facebook/react-native#25620]
What's wrong with you? Why do you release something that can barely work? 
This version is nightmare, I spent two days updating from 0.59 to 0.60 and it still doesn't work so far.

Upgrade tool doesn't work, it just brakes my project, 
Autolinking is terrible, I can't unlink anything.

Custom fonts don't work, solid part of projects can't be installed with `pod install`

Thanks for merge tool, I could get rid of android version, but solving ios isn't possible, i'm done.

Please at least fix autolinking or just make it optional.

Sorry for that, I'm done.

**Comment by radex** [comment]
> What's wrong with you? Why do you release something that can barely work?

This is an open-source project, provided for you for free. You aren't owed anything. Instead of blaming the world, the question you should be asking yourself is "what can _I_ do to help the project?".

If you have issues with upgrading to 0.60, I highly encourage you to post concrete issues with as much information as possible — or better yet, contribute to fixing those issues

**Comment by kelset** [comment]
I'm sorry you are having a bad experience, we have worked a lot to make upgrading better - we wrote it in the [blogpost](https://facebook.github.io/react-native/blog/2019/07/03/version-60) and we published even a [web tool](https://react-native-community.github.io/upgrade-helper/) to ensure a good experience.

That said, this version is not buggy as hell. We test it extensively and unless you can produce a repro detailing the precise issue you are facing, I can only assume that it's something not related to the main repo.

**Comment by hramos** [comment]
@Mikecoon any chance you might be using Swift in your iOS project? We're aware of an issue introduced in 0.60 as part of the move towards using CocoaPods which specifically affects projects using 0.60. If you use Swift in your project, I would advise holding off on 0.60 for now.

Whatever the case, I look forward to your active participation during the 0.61 release candidate phase.

**Comment by wenq1** [comment]
Although I’m not a fan of @Mikecoon’s style of issue reporting either, I have similar experience upgrading to RN60. One point in particular I’ll agree with him is making auto linking optional. Despite RN teams hard work on extensive testing I’m afraid real life project contain many “corner packages” that are useful but unmaintained, and making the upgrade a nightmare.

**Comment by Mikecoon** [comment]
> This is an open-source project, provided for you for free. You aren't owed anything. Instead of blaming the world, the question you should be asking yourself is "what can _I_ do to help the project?".

Sure, I'm just a user, but I've got a project and my users rely on it, so I have to maintain it. And I in turn essentially rely on you, that's it. 

>@Mikecoon any chance you might be using Swift in your iOS project?

Yes, I do, looks like it was the problem. Probably I've missed that part with caution? Where is it now? 
Can you make it little more obvious please? 

I'd like to contribute, sure, but I don't know obj-c, only swift. 

Also, there is a plugin named [https://github.com/react-native-community/react-native-text-input-mask](react-native-text-input-mask) which is in Swift. So, any guide how to figure it out? 

Btw, Objective-C has been retired for like... 5 years? Why Swift is still a problem? 
Anyway, just tell me how to make it work with 0.60 and I'll do that.

**Comment by kelset** [comment]
> Sure, I'm just a user, but I've got a project and my users rely on it, so I have to maintain it. And I in turn essentially rely on you, that's it.

That's **not** how open source works.

Also, you are being *really* unhelpful and aggressive - so I'd recommend that you open a new issue **following** the template.

**Comment by Mikecoon** [comment]
Oh cool, but why do you speak about my personality? I didnt say anything bad about developers, why do you think you can? 

And no, I dont get money for that project. 

About Swift, I dont care about RN's core, the question was "why 0.59 worked with swift, but 0.60 is not".

**Comment by kelset** [comment]
Ok, this is clearly going nowhere.

If you can't understand that writing things like

> What's wrong with you? Why do you release something that can barely work?

is indeed

> bad about developers

Clearly we have different views on many things.

You seem to keep refusing to collaborate, so I see no point in keeping this open.
Again, I'd recommend that you open a new issue following the template; you'll need to create a repro to prove that the bug or issue that you are facing is actually caused by the main repo.
