### ISSUE TITLE
Can't upgrade to 0.60.3

### ISSUE THREAD

**Issue by ranjeev75** [facebook/react-native#25635]
Using the react-native cli I ran the `react-native upgrade` command and I get this error:

`error Failed to fetch diff for react-native@0.60.3. Maybe it's not released yet?`

I've also tried upgrading for other 0.60.x versions with no success either.

Current RN version is: 0.59.8

Please advise...

**Comment by ecreeth** [comment]
@ranjeev75 Maybe the [Upgrade Helper](https://react-native-community.github.io/upgrade-helper/?from=0.59.8&to=0.60.3) can be helpful

**Comment by RageBill** [comment]
It seems that `react-native upgrade` supports upgrade up to `0.60.0` only for now. If you need to upgrade to most recent `0.60.3`, you might check out the upgrade helper mentioned above by @ecreeth. I also did manually upgrade my app using the helper.
