### ISSUE TITLE
tranparent borderColor broken when using borderRadius

### ISSUE THREAD

**Issue by ahmadi-akbar** [facebook/react-native#25643]
header: {
    alignItems: "center",
    borderWidth: 1,
    borderColor:'red',
    borderTopColor: "transparent",
    borderBottomLeftRadius: 15,
    borderBottomRightRadius: 15,
    paddingVertical: 10,
    margin:10,
    marginBottom: 20,
  }

this style make =>
![image](https://user-images.githubusercontent.com/48069695/61183686-56331800-a659-11e9-8b4c-51e70d68ec09.png)

header: {
    alignItems: "center",
    borderWidth: 1,
    borderColor:'red',
    borderTopColor: "transparent",
    //  borderBottomLeftRadius: 15,   //commented
    //  borderBottomRightRadius: 15,   //commented
    paddingVertical: 10,
    margin:10,
    marginBottom: 20,
  }

and this style make =>
![image](https://user-images.githubusercontent.com/48069695/61183691-6b0fab80-a659-11e9-950a-b55babf9c03e.png)

this occur only on Android 

React Native version:

System:
  OS: Windows 10
  CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
  Memory: 5.71 GB / 15.87 GB
  Binaries:
     Node: 10.16.0 - E:\Install\nodejs\node.EXE
      Yarn: 1.16.0 - E:\Install\yarnCache\global\Data\node_modules\.bin\yarn.CMD
      npm: 6.9.0 - E:\Install\nodejs\npm.CMD

https://snack.expo.io/@ahmadi-akbar/android-bordercolor-overriding-issue

**Comment by RobinCsl** [comment]
Hi @ahmadi-akbar,

This behaviour is indeed strange.

As a workaround, you can replace `borderTopColor: "transparent"` by `borderTopWidth: 0`, and you will get the same consistent output on both iOS and Android:
![canvas](https://user-images.githubusercontent.com/22741774/61184678-f9cbfa80-a650-11e9-89c1-533719307d60.png)

Hope that helps!

**Comment by ahmadi-akbar** [comment]
> Hi @ahmadi-akbar,
> 
> This behaviour is indeed strange.
> 
> As a workaround, you can replace `borderTopColor: "transparent"` by `borderTopWidth: 0`, and you will get the same consistent output on both iOS and Android:
> ![canvas](https://user-images.githubusercontent.com/22741774/61184678-f9cbfa80-a650-11e9-89c1-533719307d60.png)
> 
> Hope that helps!

It's work  and make sense 
thank for your answer 🙏

**Comment by cabelitos** [comment]
Hello @ahmadi-akbar and @RobinCsl I submitted a fix for this problem. Comments and suggestions are appreciated.

Here's the PR: https://github.com/facebook/react-native/pull/25649

Thank you.

**Comment by ahmadi-akbar** [comment]
hello there @cabelitos 
thank to you and your great effort
i hope they accept your pull request
