### ISSUE TITLE
TypeError: Cannot read property getCurrentPosition of undefined

### ISSUE THREAD

**Issue by BrightonNgema** [facebook/react-native#25648]
I have tried everything I can and I can't seem to find a solution. when I'm trying to get current location, I get this error.
![Simulator Screen Shot - iPhone X - 2019-07-14 at 22 33 59](https://user-images.githubusercontent.com/25287756/61189053-d7a19f00-a687-11e9-9f4a-9f9daa4e7c9c.png)

Below is my code for getting the current location.
<img width="449" alt="Screenshot 2019-07-14 at 22 34 10" src="https://user-images.githubusercontent.com/25287756/61189059-e8521500-a687-11e9-88b5-e22759637058.png">

my package JSON looks like this:
  "dependencies": {
    "jetifier": "^1.6.2",
    "react": "16.8.6",
    "react-native": "0.60.0",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-google-places-autocomplete": "^1.3.9",
    "react-native-maps": "^0.25.0",
    "react-native-onboarding-swiper": "^1.1.0",
    "react-navigation": "^3.11.0"
  },
Any solution?

**Comment by arnoldc** [comment]
you need to use
https://github.com/react-native-community/react-native-geolocation
geolocation has been pulled out in latest react native 0.60
