### ISSUE TITLE
React Native native module works very slow (Android)

### ISSUE THREAD

**Issue by Nahani** [facebook/react-native#25658]
Hello,

I created a Native module on Android and iOS to support Here Map premium mobile sdk (https://developer.here.com/develop/mobile-sdks)

There are no troubles when I use this sdk in a iOS native module.

But we are facing to big performance issue on Android.

It seems the issue come from the react native android bridge. 
The sdk works well in an android native java app and in react native iOS native module.

After search solution I found that I'm not the only one to have this issue:

- https://github.com/facebook/react-native/issues/18066

- https://stackoverflow.com/questions/54705159/slow-performance-after-switching-to-heremap-premium-sdk

But none give a solution on this issue.

Do you have any idea where this problem may come from?

React Native version: 0.60.3

System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 3.35 GB / 15.88 GB
  Binaries:
    Node: 8.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      Android NDK: 19.2.5345600
  IDEs:
    Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5522156

## Steps To Reproduce

1. Install the package to a react native project (from the dev branch: https://github.com/Weopt/react-native-here-maps/tree/dev)
2. Call the package in react native :

```
import HereMapsAndroid from 'react-native-heremaps';

 <HereMapsAndroid
          style={{ flex: 1, backgroundColor: '#FFF' }}
          center={`43.7274885,7.4283188`}
          markersList={[{ latitude: 43.7274885, longitude: 7.4283188, title: 'Test', description: 'Une description'}]}
          mapType="normal"
          initialZoom={10}
        />
```

Describe what you expected to happen:

I expect the same behavior than  react native iOS app.

Snack, code example, or link to a repository:
 
Native Module repository: 
https://github.com/Weopt/react-native-here-maps

Thanks a lot !

**Comment by dulmandakh** [comment]
Please file an issue to https://github.com/Weopt/react-native-here-maps, as it's not related to core RN components.
