### ISSUE TITLE
(Android) Problems passing props from native code to javascript

### ISSUE THREAD

**Issue by niedem** [facebook/react-native#25659]
I tried passing a prop from android native code to react-native, on the startup. However, even after copying the exact code from the docs it failed to work.

React Native version: 0.60.3

## Steps To Reproduce

1. Running the code (below)

Describe what you expected to happen:
A text should appear in the app, however all i got was a blank space.

In my MainActivity.java, under my ReactActivityDelegate:

`
            @Override
            protected Bundle getLaunchOptions() {
                Bundle initialProperties = new Bundle();
                initialProperties.putString("testString", "This should be displayed now");
                return initialProperties;
            }
`

In the render method of my app.js:

`<Text>{this.props.testString}</Text>`

**Comment by fonov** [comment]
see https://stackoverflow.com/a/57606851/7957435

**Comment by ken0x0a** [comment]
There is an official document.

see https://facebook.github.io/react-native/docs/communication-android
