### ISSUE TITLE
FlatList onEndReached can not be called!

### ISSUE THREAD

**Issue by luoyushouchai** [facebook/react-native#25656]
React Native version: 0.59.9

## Steps To Reproduce

I console log in VirtualizedLIst.   The function _maybeCallOnEndReached() called.  
```
_maybeCallOnEndReached() {
 const {
   data,
   getItemCount,
   onEndReached,
   onEndReachedThreshold,
 } = this.props;
 const {contentLength, visibleLength, offset} = this._scrollMetrics;
 const distanceFromEnd = contentLength - visibleLength - offset;
 if (
   onEndReached &&
   this.state.last === getItemCount(data) - 1 &&
   /* $FlowFixMe(>=0.63.0 site=react_native_fb) This comment suppresses an
    * error found when Flow v0.63 was deployed. To see the error delete this
    * comment and run Flow. */
   distanceFromEnd < onEndReachedThreshold * visibleLength &&
   (this._hasDataChangedSinceEndReached ||
     this._scrollMetrics.contentLength !== this._sentEndForContentLength)
 ) {
   // Only call onEndReached once for a given dataset + content length.
   this._hasDataChangedSinceEndReached = false;
   this._sentEndForContentLength = this._scrollMetrics.contentLength;
   onEndReached({distanceFromEnd});
 }
}
```
console result: this.state.last = 0;  getItemCount(data) = 2;
this.state.last !== getItemCount(data) -1 ,   so can not trigger onEndReached!

But for FlatList,  it has reach end!

**Comment by JerakRus** [comment]
I have inverted flatlist in my chat app , and now it worked very strange... onEndReached and refreshing   work in 1 direction!   React-native version 0.60.3

**Comment by e1016** [comment]
can we see your JSX?

**Comment by luoyushouchai** [comment]
@e1016 
This is render function!
I can not reproduce using FlatList.  
```
render() {
 const { selectable, dataList, onEndReached } = this.props;
 const extraData = Object.assign({}, { selectable });
 return (
   <React.Fragment>
     <FlatList
       testID='result-list'
       ref={ref => this.list = ref}
       keyExtractor={this._keyExtractor}
       data={dataList}
       extraData={extraData}
       onScroll={this._handleOnScroll}
       scrollEventThrottle={0}
       renderItem={this._renderItem}
       onViewableItemsChanged={this._onViewableItemsChanged}
       style={styles.list}
       inverted
       removeClippedSubviews
       initialNumToRender={30}
       onScrollToIndexFailed={this.onScrollToIndexFailed}
       onEndReached={onEndReached}
       onEndReachedThreshold={0.5}
       maxToRenderPerBatch={20}
       windowSize={20}
       ListFooterComponent={this.renderFooter}
       ListHeaderComponent={this.renderHeader}
       {...scrollPersistTaps}
       onScrollBeginDrag={this.handleScrollBeginDrag}
       scrollsToTop={false}
       viewabilityConfig={VIEW_ABLITY_CONFIG}
       refreshControl={this._renderRefreshControl()}
     />
   </React.Fragment>
 );
}
```

**Comment by JerakRus** [comment]
may be you need use 'this.onEndReached' ? )

**Comment by JerakRus** [comment]
My list is simpler 
`  <FlatList style={{backgroundColor: redesignColors.backgroundCommonColor, flex: 1}}
                          data={this.props.messages}
                          renderItem={this.messageItem}
                          inverted
                          keyExtractor={this._keyExtractor}
                          onRefresh={this.onRefresh}
                          refreshing={this.props.pendingChat}
                          onEndReached={this.nextPage}
                          onEndReachedThreshold={0.3}
                />`


But it does not work correctly. The onEndReach and refresh functions work in the same direction when I try to move to the end of the list (up)

**Comment by luoyushouchai** [comment]
> may be you need use 'this.onEndReached' ? )

I pass onEndReached by props. The func onEndReached **sometimes** can not trigger!

**Comment by JerakRus** [comment]
oh sorry, I did not look carefully

**Comment by ssancheza227** [comment]
@JerakRus Hi guy, could you correct it?

**Comment by JerakRus** [comment]
@ssancheza227 
In my case, I had to remove the refresh props and use the component without it. But in the dialogue it is not very critical, so for now I have left it that way. And onEndReached in 0.60.3 works fine

**Comment by ssancheza227** [comment]
@JerakRus i did too :/ 
`<FlatList
        data={transactions}
        keyExtractor={(item, index) => index.toString()}
        onEndReachedThreshold={0}
        onEndReached={({distanceFromEnd}) => {
          console.log('distanceFromEnd', distanceFromEnd);
          this.handleLoadMore();
        }}
        ListFooterComponent={() => (isLoading ? <ActivityIndicator animating /> : null)}
        renderItem={({item, index}) => this.renderTransaction(item, index)}
        style={{
          flex: 1,
        }}
        contentContainerStyle={{flex: 1}}
      />`

**Comment by ssancheza227** [comment]
**@JerakRus @luoyushouchai @e1016** Hi guys :) good news, well the solution was envolved flatList into View and set height (**const {height} = Dimensions.get('window');**) to view, percent not work: 

```javascript
<View style={{flex: 1, height: height}}>
   <FlatList
       data={data}
       keyExtractor={(item, index) => index.toString()}
       onEndReached={this.handleLoadMore} 
       onEndReachedThreshold={0.01}
       ListFooterComponent={() => this.state.loading ? <ActivityIndicator/> : null}
       renderItem={({item, index}) => this.renderTransaction(item, index)}
   />
</View>
```

**Comment by wpeng** [comment]
I met a similar issue. onEndReached not called after a momentum scroll. In my case ,this.state.last is 69 while itemCount is 79

**Comment by ifsnow** [comment]
https://github.com/ifsnow/react-native-infinite-flatlist-patch

I made a patch library to help with this issue. I hope this helps.

**Comment by hotaryuzaki** [comment]
> > may be you need use 'this.onEndReached' ? )
> 
> I pass onEndReached by props. The func onEndReached **sometimes** can not trigger!

same issue.
so.. after i pull to refresh, sometimes onEndReached not trigger.

**Comment by ggdegreat** [comment]
0.61.3 still happening ..

**Comment by JackClown** [comment]
same problem.  RN 0.59.10

**Comment by greendream1216** [comment]
<FlatList
              style={{ width: '100%' }}
              keyExtractor={(item, index) => index.toString()}
              data={this.state.serverData}

              onEndReached={() => this.onLoadMoreData()}
              onEndReachedThreshold={.5}
              
              renderItem={({ item, index }) => (
                this.renderFeedItem(item, index)
              )}

              ItemSeparatorComponent={() => <View style={styles.separator} />}
              ListHeaderComponent = {this.renderHeader()}
              ListFooterComponent={this.renderFooter()}
            />


 onLoadMoreData(){

    this.setState({isLoadMoreData : true});
    this.page = this.page + 1;

    this.fetchData(this.page).then(() => {
      this.setState({isLoadMoreData : false});
    })
  };
I worked on React Native 0.61 and onEndReached function works good.

**Comment by mtahir08** [comment]
any update. ?

**Comment by erald14** [comment]
Guys please make sure its Falt list is not inside a scrollview or maybe has auto a width parent!

**Comment by DenisDovganiuc** [comment]
same problem. RN 0.62.2.

**Comment by dgreen-dev** [comment]
same problem facing in RN 0.63.2

**Comment by msmtr14** [comment]
Same problem RN 0.63.2

**Comment by ehizokhai** [comment]
> https://github.com/ifsnow/react-native-infinite-flatlist-patch

This worked for me. Thanks man

**Comment by shadow-boy** [comment]
Same problem RN 0.63.3！ 。any update ?

**Comment by SameeraMadushan** [comment]
> **@JerakRus @luoyushouchai @e1016** Hi guys :) good news, well the solution was envolved flatList into View and set height (**const {height} = Dimensions.get('window');**) to view, percent not work:
> 
> ```js
> <View style={{flex: 1, height: height}}>
>    <FlatList
>        data={data}
>        keyExtractor={(item, index) => index.toString()}
>        onEndReached={this.handleLoadMore} 
>        onEndReachedThreshold={0.01}
>        ListFooterComponent={() => this.state.loading ? <ActivityIndicator/> : null}
>        renderItem={({item, index}) => this.renderTransaction(item, index)}
>    />
> </View>
> ```
> 
> And **if this not scroll** envolved into ScrollView: ScrollView -> View (height) -> FlatList

This worked for me..!! 💯

**Comment by juliendevleeschauwer** [comment]
> ```
>    <FlatList
>           style={{ width: '100%' }}
>           keyExtractor={(item, index) => index.toString()}
>           data={this.state.serverData}
> 
>           onEndReached={() => this.onLoadMoreData()}
>           onEndReachedThreshold={.5}
>           
>           renderItem={({ item, index }) => (
>             this.renderFeedItem(item, index)
>           )}
> 
>           ItemSeparatorComponent={() => <View style={styles.separator} />}
>           ListHeaderComponent = {this.renderHeader()}
>           ListFooterComponent={this.renderFooter()}
>         />
> ```
> 
> onLoadMoreData(){
> 
> ```
> this.setState({isLoadMoreData : true});
> this.page = this.page + 1;
> 
> this.fetchData(this.page).then(() => {
>   this.setState({isLoadMoreData : false});
> })
> ```
> 
> };
> I worked on React Native 0.61 and onEndReached function works good.

You don't have inverted flatlist

**Comment by vobear** [comment]
<ScrollView
                style={{ flex: 1 }}
                onScrollBeginDrag={() => {
                    if (!isEndReached) {
                        isEndReached = true;
                        setIsEndReached(isEndReached);
                        onEndReached();
                    }
                }}
                refreshControl={
                    <RefreshControl
                        refreshing={refreshing}
                        enabled={true}
                        title={'松手刷新'}
                        onRefresh={refresPage}
                    />
                }
            >
                <View></View>
                <FlatList
                    data={listState}
                    style={{ flex: 1 }}
                    renderItem={({ item, index }) => {}}
                    ListFooterComponent={ListFooterComponent()}
                    ListEmptyComponent={ListEmptyComponent()}
                    keyExtractor={({ index }) => { `key_${index}` }}
                    onEndReached={onEndReached}
                    onEndReachedThreshold={0.01}
                />
            </ScrollView>

**Comment by vobear** [comment]
`<ScrollView
                style={{ flex: 1 }}
                onScrollBeginDrag={() => {
                    if (!isEndReached) {
                        isEndReached = true;
                        setIsEndReached(isEndReached);
                        onEndReached();
                    }
                }}
                refreshControl={
                    <RefreshControl
                        refreshing={refreshing}
                        enabled={true}
                        title={'松手刷新'}
                        onRefresh={refresPage}
                    />
                }
            >
                <View></View>
                <FlatList
                    data={listState}
                    style={{ flex: 1 }}
                    renderItem={({ item, index }) => {}}
                    ListFooterComponent={ListFooterComponent()}
                    ListEmptyComponent={ListEmptyComponent()}
                    keyExtractor={({ index }) => { `key_${index}` }}
                    onEndReached={onEndReached}
                    onEndReachedThreshold={0.01}
                />
            </ScrollView>`

**Comment by vobear** [comment]
`
<ScrollView
                style={{ flex: 1 }}
                onScrollBeginDrag={() => {
                    if (!isEndReached) {
                        isEndReached = true;
                        setIsEndReached(isEndReached);
                        onEndReached();
                    }
                }}
                refreshControl={
                    <RefreshControl
                        refreshing={refreshing}
                        enabled={true}
                        title={'松手刷新'}
                        onRefresh={refresPage}
                    />
                }
            >
                <View></View>
                <FlatList
                    data={listState}
                    style={{ flex: 1 }}
                    renderItem={({ item, index }) => {}}
                    ListFooterComponent={ListFooterComponent()}
                    ListEmptyComponent={ListEmptyComponent()}
                    keyExtractor={({ index }) => { `key_${index}` }}
                    onEndReached={onEndReached}
                    onEndReachedThreshold={0.01}
                />
            </ScrollView>
`

**Comment by vobear** [comment]
<ScrollView
                style={{ flex: 1 }}
                onScrollBeginDrag={() => {
                    if (!isEndReached) {
                        isEndReached = true;
                        setIsEndReached(isEndReached);
                        onEndReached();
                    }
                }}
                refreshControl={
                    <RefreshControl
                        refreshing={refreshing}
                        enabled={true}
                        title={'松手刷新'}
                        onRefresh={refresPage}
                    />
                }
            >
                <View></View>
                <FlatList
                    data={listState}
                    style={{ flex: 1 }}
                    renderItem={({ item, index }) => {}}
                    ListFooterComponent={ListFooterComponent()}
                    ListEmptyComponent={ListEmptyComponent()}
                    keyExtractor={({ index }) => { `key_${index}` }}
                    onEndReached={onEndReached}
                    onEndReachedThreshold={0.01}
                />
            </ScrollView>

**Comment by rigalpatel001** [comment]
Hello,
There is an issue with the flat list. when page load "onEndReached" called two times.

```
   <FlatList
        data={data.productlist.edges}
        keyExtractor={(products) => products.node.id.toString()}
        onEndReachedThreshold={0.5}
        onEndReached={() => {
          console.log("Next Product Click");
          if (pageInfo.hasNextPage) {
            fetchMore({
              variables: {
                after: pageInfo.endCursor,
              },
            });
          }
        }}
        renderItem={({ item }) => (
          <ProductCard
            title={item.node.title}
            price={item.node.price}
            image={item.node.image}
            ProductId={item.node.id}
            onPress={() => console.log("On Press")}
          />
        )}
      />
```

**Comment by alirezapiran7** [comment]
just add  onEndReachedThreshold={0.3} or number between [0,1] worked for me. usage for message list

**Comment by fewoy** [comment]
you need set a min height to FlatList.

**Comment by fabOnReact** [comment]
https://github.com/ifsnow/react-native-infinite-flatlist-patch/tree/master/patches does not support rn versions > 0.68.
Do you still experience this issue? Should I work on this? Thanks

**Comment by kuldip-trentium** [comment]
> Guys please make sure FaltList is not inside a scrollview or maybe has auto a width parent!

true

**Comment by nikola166** [comment]
> just add onEndReachedThreshold={0.3} or number between [0,1] worked for me. usage for message list

OR onEndReachedThreshold={0.5}

**Comment by Parmar-Bansi** [comment]
> > just add onEndReachedThreshold={0.3} or number between [0,1] worked for me. usage for message list
> 
> OR onEndReachedThreshold={0.5}

not working in my side guide me
