### ISSUE TITLE
"Loading dependency graph, done." Stuck

### ISSUE THREAD

**Issue by anandhuraj1001** [facebook/react-native#25650]
Metro Bundler ready.
Loading dependency graph, done.
than stuck nothing happens.

react-native info:
info Fetching system and libraries information...
System:
OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
CPU: (2) x64 Intel(R) Pentium(R) CPU G3240 @ 3.10GHz
Memory: 2.55 GB / 7.69 GB
Shell: 4.4.20 - /bin/bash
Binaries:
Node: 12.6.0 - /usr/local/bin/node
npm: 6.9.0 - /usr/local/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
SDKs:
Android SDK:
API Levels: 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 7, 8, 9
Build Tools: 26.0.2, 27.0.3, 28.0.3
System Images: android-22 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom
npmPackages:
react: 16.8.6 => 16.8.6
react-native: 0.60.3 => 0.60.3
npmGlobalPackages:
react-native-cli: 2.0.1

**Comment by murtraja** [comment]
@anandhuraj1001 this is a very common issue that I faced regularly when I was beginning react-native. What worked for me was to set the watcher limits
https://github.com/facebook/watchman/issues/163#issuecomment-224263937

**Comment by anandhuraj1001** [comment]
**

> Steps To Reproduce:

**
1)react-native init testApp
2)npm install
3)react-native start
Loading dependency graph, done. but stuck.

**

> react-native info:

**

info Fetching system and libraries information...
System:
OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
CPU: (2) x64 Intel(R) Pentium(R) CPU G3240 @ 3.10GHz
Memory: 2.55 GB / 7.69 GB
Shell: 4.4.20 - /bin/bash
Binaries:
Node: 12.6.0 - /usr/local/bin/node
npm: 6.9.0 - /usr/local/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
SDKs:
Android SDK:
API Levels: 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 7, 8, 9
Build Tools: 26.0.2, 27.0.3, 28.0.3
System Images: android-22 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom
npmPackages:
react: 16.8.6 => 16.8.6
react-native: 0.60.3 => 0.60.3
npmGlobalPackages:
react-native-cli: 2.0.1

**

> App.js code:

**

import React, { Component } from 'react';
import { Text, View } from 'react-native';

export default class HelloWorldApp extends Component {
  render() {
    return (
      <View style={{ flex: 1, justifyContent: "center", alignItems: "center" }}>
        <Text>Hello, world!</Text>
      </View>
    );
  }
}

**Comment by valery-lavrik** [comment]
I have a similar problem. Solutions already looking for 2 days, but nothing.

**Comment by chrisspankroy** [comment]
If it says 
```bash
Loading dependency graph, done.
```
then you're good, that's all it is supposed to do. You leave it running, then when you launch a RN app, you can see it start to bundle.

But, if you see something like
```bash
Loading dependency graph...
```
and you never see ```done```, then apps won't be able to bundle yet

**Comment by anandhuraj1001** [comment]
> I have a similar problem. Solutions already looking for 2 days, but nothing. But it happened to me on windows 10

same here but i'm using Linux.

**Comment by valery-lavrik** [comment]
> and you never see done, then apps won't be able to bundle yet

really, I have a message

`Loading dependency graph ...`

and nothing happens.
That's where everything stopped at me. I do not know what to do...
![Screenshot_1](https://user-images.githubusercontent.com/8047999/61272137-11b99080-a7af-11e9-86fb-3fa91aef3459.png)

**Comment by thymikee** [comment]
It's because of Node >=12.5 issues with memory. See: https://github.com/react-native-community/cli/issues/485#issuecomment-509210382
Please downgrade to Node 12.4 or lower for now.

**Comment by valery-lavrik** [comment]
> It's because of Node >=12.5 issues with memory. See: [react-native-community/cli#485 (comment)](https://github.com/react-native-community/cli/issues/485#issuecomment-509210382)
> Please downgrade to Node 12.4 or lower for now.

thanks, it worked!

**Comment by valery-lavrik** [comment]
![image](https://user-images.githubusercontent.com/8047999/61354862-b99c9000-a87b-11e9-9ede-6881aabaee17.png)
Maybe I'm not writing here, but after turning on Hermes, I get this error (in the picture).

Searching in node_modules I found this in _./node_modules/react-refresh/cjs/react-refresh-babel.development_

I updated all the packages to the latest version, but it did not help.
 What should I do?

**Comment by valery-lavrik** [comment]
![image](https://user-images.githubusercontent.com/8047999/61355284-b6ee6a80-a87c-11e9-8233-10b057ec0530.png)
if you disable debug mode, there will be such a message

**Comment by ebnerdeath** [comment]
Thanks @thymikee fix for mee!

**Comment by mr-moon** [comment]
v12.4, nor v12.10 do not work for me.

**Comment by alexandre9865** [comment]
> v12.4, nor v12.10 do not work for me.

it's equal to me

**Comment by Robiullah2244** [comment]
> > and you never see done, then apps won't be able to bundle yet
> 
> really, I have a message
> 
> `Loading dependency graph ...`
> 
> and nothing happens.
> That's where everything stopped at me. I do not know what to do...
> ![Screenshot_1](https://user-images.githubusercontent.com/8047999/61272137-11b99080-a7af-11e9-86fb-3fa91aef3459.png)

Try to run with a different device. I have faced the same problem. After change the virtual device it works fine for me. :)

**Comment by Robiullah2244** [comment]
Try to run with a different device. I have faced the same problem. And I also changed my node version but didn't work. After change the virtual device it works fine for me. :)

**Comment by Robiullah2244** [comment]
> v12.4, nor v12.10 do not work for me.

Try to run with a different device. I have faced the same problem. And I also changed my node version but didn't work. After change the virtual device it works fine for me. :)

**Comment by mr-moon** [comment]
Yes, it kinda with some devices, @Robiullah2244 , but plain browser-based dev doesn't work either.
![image](https://user-images.githubusercontent.com/933164/65862912-d96e2b00-e377-11e9-9544-45458757fa66.png)
Here's `react-native start`
![image](https://user-images.githubusercontent.com/933164/65862959-f60a6300-e377-11e9-95f2-e3479cf004f6.png)

1 thing I noticed is these 3 lines:
```
debug Current version: 0.60.5
debug Cached release version: 0.60.0
...
debug Latest release: 0.60.0
```
Why versions are different?

Also, I did cleared watchman cache, platform cache as suggested [here](https://medium.com/@abhisheknalwaya/how-to-clear-react-native-cache-c435c258834e). But still, nothing helps and react-native versions remained the same. 

![image](https://user-images.githubusercontent.com/933164/65863417-c3149f00-e378-11e9-824f-2ced094a1df6.png)

**Comment by bobzhen** [comment]
> It's because of Node >=12.5 issues with memory. See: [react-native-community/cli#485 (comment)](https://github.com/react-native-community/cli/issues/485#issuecomment-509210382)
> Please downgrade to Node 12.4 or lower for now.

Downgrade to 12.4 is a magic... Thanks.

**Comment by jasuno** [comment]
If you are using expo, just run `expo start` instead

**Comment by denzilgupta** [comment]
Hi
Can someone help me out?

![Screenshot from 2019-11-07 16-38-23](https://user-images.githubusercontent.com/50393543/68384204-1ef2f480-017d-11ea-83f5-e0a4cfae550b.png)


Nothing happens after this.
I get the below error on my phone:

![Screenshot_20191107-163941](https://user-images.githubusercontent.com/50393543/68384276-4b0e7580-017d-11ea-8385-d59f24ea94c0.jpg)

I am using react native for the first time ever. Please help me out with this.
Thanks!

**Comment by denzilgupta** [comment]
> Hi
> Can someone help me out?
> 
> ![Screenshot from 2019-11-07 16-38-23](https://user-images.githubusercontent.com/50393543/68384204-1ef2f480-017d-11ea-83f5-e0a4cfae550b.png)
> 
> Nothing happens after this.
> I get the below error on my phone:
> 
> ![Screenshot_20191107-163941](https://user-images.githubusercontent.com/50393543/68384276-4b0e7580-017d-11ea-8385-d59f24ea94c0.jpg)
> 
> I am using react native for the first time ever. Please help me out with this.
> Thanks!

I found the solution for this.
I ran the command "react-native start" and then ran "react-native run-android"

This worked out for me! :)

**Comment by toeurtenh** [comment]
@thymikee you might be right about memory but my node is v10.15.1 and I have a same problem.

**Comment by YehudaKremer** [comment]
in my case - select "No Proxy" in your virtual device settings.

**Comment by fxbayuanggara** [comment]
my solution is restart your mac/pc then run react-native run-android again.

**Comment by interfaith** [comment]
using node 13.3.0 1. yarn start 2. react-native run-android works !

**Comment by igetitapps** [comment]
What worked for me on iOS was delete de app from simulator or device then run the npx react-native run-ios again

**Comment by MusabAkram** [comment]
I tried all the solutions sometimes they worked and sometimes didn't. 
The best solution I found out and that worked better than the others is to kill the port 8081 on which the debugger runs. 
The issue here is that your port 8081 established a connection from a previous build and it was not closed.
Try these commands:
"netstat -ano | findstr :yourPortNumber"
and then
"taskkill /PID typeyourPIDhere /F

**Comment by fralyx** [comment]
> > Hi
> > Can someone help me out?
> > ![Screenshot from 2019-11-07 16-38-23](https://user-images.githubusercontent.com/50393543/68384204-1ef2f480-017d-11ea-83f5-e0a4cfae550b.png)
> > Nothing happens after this.
> > I get the below error on my phone:
> > ![Screenshot_20191107-163941](https://user-images.githubusercontent.com/50393543/68384276-4b0e7580-017d-11ea-8385-d59f24ea94c0.jpg)
> > I am using react native for the first time ever. Please help me out with this.
> > Thanks!
> 
> I found the solution for this.
> I ran the command "react-native start" and then ran "react-native run-android"
> 
> This worked out for me! :)

This is quite an old post, but better late than never
Try `adb reverse tcp:8081 tcp:8081`, then reload the app

**Comment by Abakanmeister** [comment]
3d time i got this error. "Loading dependency graph, done" just stuck. And bundle doesn't start loading... Every time it solving by itself after 3-4 weeks. U can do everything like reinstall watchman, clean project, install different node versions, watchman shutdown-server, watchman watch-del-all, restart xcode, pc, go sleep, nothing help u with that. I don't know how to solve it like all who face this problem. No answer in google, stackoverflow, here, no one knows what to do. And only way to continue developing is take android device which are the worst thing in react native developing! I hate android because of poor js support. Issues like that is demand everyone to start think about migrating to native mobile app developing. I didn't do anything wrong it's just happening again and again on ios, and android is something that u don't wanna think about when u develop on react-native.

**Comment by musabnumu** [comment]
> 3d time i got this error. "Loading dependency graph, done" just stuck. And bundle doesn't start loading... Every time it solving by itself after 3-4 weeks. U can do everything like reinstall watchman, clean project, install different node versions, watchman shutdown-server, watchman watch-del-all, restart xcode, pc, go sleep, nothing help u with that. I don't know how to solve it like all who face this problem. No answer in google, stackoverflow, here, no one knows what to do. And only way to continue developing is take android device which are the worst thing in react native developing! I hate android because of poor js support. Issues like that is demand everyone to start think about migrating to native mobile app developing. I didn't do anything wrong it's just happening again and again on ios, and android is something that u don't wanna think about when u develop on react-native.
Try closing the debugger port `80801` 
This is the command for windows:
netstat -ano|findstr "PID :8081"
taskkill /pid <your_pid_number>/f

**Comment by J-Krush** [comment]
I solved this by removing the app from the device/simulator and re-installing, not sure if that will help anyone.

**Comment by oferRounds** [comment]
Did someone found a fix for this? I’m on v0.60.6, trying to run it on my Pixel

**Comment by usman147** [comment]
> > Hi
> > Can someone help me out?
> > ![Screenshot from 2019-11-07 16-38-23](https://user-images.githubusercontent.com/50393543/68384204-1ef2f480-017d-11ea-83f5-e0a4cfae550b.png)
> > Nothing happens after this.
> > I get the below error on my phone:
> > ![Screenshot_20191107-163941](https://user-images.githubusercontent.com/50393543/68384276-4b0e7580-017d-11ea-8385-d59f24ea94c0.jpg)
> > I am using react native for the first time ever. Please help me out with this.
> > Thanks!
> 
> I found the solution for this.
> I ran the command "react-native start" and then ran "react-native run-android"
> 
> This worked out for me! :)

This worked out for me. Thanks :)

**Comment by developerantoniosousa** [comment]
> Please downgrade to Node 12.4 or lower for now.

It worked for me! @thymikee  Thanks!
