### ISSUE TITLE
Running RN 0.60.3 on android with vscode gives ENOENT error

### ISSUE THREAD

**Issue by CrackyStudio** [facebook/react-native#25665]
After setting up a new project with RN 0.60.3 and running `react-native run-android` with vscode I got the error :

`Error: spawn vscode ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)`

To solve it I've to open my terminal at the project location and run the command `react-native start`. After that, I come back to the vscode and run the command `react-native run-android` again. This time the error is gone and I'm able to run the project successfully. 

This never happened in previous version of RN.

**Comment by zeroidentidad** [comment]
hello I made a post with considerations or possible solutions with this issue with v 0.60.x, here: https://awebytes.wordpress.com/2019/07/15/react-native-fix-for-unable-to-load-script-make-sure-youre-either-running-a-metro-server/

in conlusion is about VS code integrated terminal behavior, we need a external terminal

**Comment by thymikee** [comment]
Already tracked in #25667
