### ISSUE TITLE
new project with RN 0.60.3 returns ENOENT

### ISSUE THREAD

**Issue by kempoo** [facebook/react-native#25667]
Clean install with `react-native init AwesomeApp` results with ENONET error on `react-native run-android`

React Native version: 0.60.3
IDE: Visual Studio Code

System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 2.47 GB / 7.95 GB
  Binaries:
    Node: 10.3.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.1.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5692245

## Steps To Reproduce

1. run `react-native init AwesomeApp` 
2. run `react-native run-android`

## Describe what you expected to happen:

Command to execute successfully.

## Error:
`
error Failed to run jetifier.
Error: spawnSync E:\DEV\AwesomeApp\node_modules\jetifier\bin\jetify ENOENT
    at Object.spawnSync (internal/child_process.js:981:20)
    at spawnSync (child_process.js:588:24)
    at execFileSync (child_process.js:616:13)
    at Object.runAndroid [as func] (E:\DEV\AwesomeApp\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:101:41)
    at Command.handleAction (E:\DEV\AwesomeApp\node_modules\react-native\node_modules\@react-native-community\cli\build\cliEntry.js:160:21)   
    at Command.listener (E:\DEV\AwesomeApp\node_modules\commander\index.js:315:8)
    at Command.emit (events.js:182:13)
    at Command.parseArgs (E:\DEV\AwesomeApp\node_modules\commander\index.js:651:12)
    at Command.parse (E:\DEV\AwesomeApp\node_modules\commander\index.js:474:21)
    at setupAndRun (E:\DEV\AwesomeApp\node_modules\react-native\node_modules\@react-native-community\cli\build\cliEntry.js:210:24)
`

**Comment by HamitEnes** [comment]
There is an info when running

react-native run-android command

like that _info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag._

With 

react-native run-android --no-jetifier

command, project opens correctly but I dont know what happens if jetifier stopped.

**Comment by yang200258** [comment]
You can run react-native run-android --no-jetifier

**Comment by HamitEnes** [comment]
[https://github.com/facebook/react-native/issues/25669] Connected topics.

**Comment by HamitEnes** [comment]
#25669 
issue related that

**Comment by niedem** [comment]
> You can run react-native run-android --no-jetifier

Yeah, but some libs require jetifier

**Comment by kempoo** [comment]
> You can run react-native run-android --no-jetifier

Yes, but my real scenario is that I have a bunch of libs that fail without jetifier. I've found some workarounds like [this](https://medium.com/@yathousen/the-day-google-decided-to-shake-the-react-native-community-4ba5cdd33388), but I find them inconsistent as it may cause other problems on further RN upgrades.

**Comment by Inovassist-dev** [comment]
Hey guys, nothing working here yet!
For some reason, I receive the following error: "Failed to run jetifier. Run"

**My environment is the following:**
- Node: 12.6.0
- NPM: 6.9.0
- React Native CLI:  2.0.1
- React Native: 0.60.1
- OS: Windows 10

Can someone please help me? I need Jetifier in my project!

**Comment by jaycobbs** [comment]
maybe it will help someone

1. npm i jetifier -D
2. add script "jetify": "jetify"
3. npm run jetify
4. react-native run-android --no-jetifier

**Comment by thymikee** [comment]
This is an issue with the CLI. Looks like `jetifier/bin/jetify` is not found on Windows. Can somebody with Windows machine investigate? Here's the code responsible: https://github.com/react-native-community/cli/blob/672986873848e15f29d60cc0daa1c7b5d795d390/packages/platform-android/src/commands/runAndroid/index.js#L71

**Comment by Inovassist-dev** [comment]
@jaycobbs I tried it and, with some changes, it worked!
I just had to run:
`npx jetify`
Followed by:
`react-native run-android --no-jetifier`
And it compiled successfully!

But, I have some updates here: I downgraded React Native to 0.59.8 and it worked like a charm as it doesn't uses Jetifier to migrate plugins to AndroidX, so, it's clearly that the problem is with Jetifier... I just can't understand why the script runs on `npx` and not with directly with the compiler...

I'll check the code and try to find something...
But anyway, thank you guys for helping!

**Comment by thymikee** [comment]
I kindly request reviewing and testing a proposal to fix this: https://github.com/react-native-community/cli/pull/541 as I don't have Windows machine set up currently.

**Comment by pavlo-o-savchuk** [comment]
How come the new version of such a library is not tested before you release it?

**Comment by sambestsolutions** [comment]
Why the issue is closed?  the suggested fix not going to work if the project requires  jetifier required libraries right ??

**Comment by thymikee** [comment]
It's closed because cli published a fix, so next time you init a fresh project or regenerate the lock file (to use cli v2.6.2 or newer), jetifier should be executed properly.

**Comment by sambestsolutions** [comment]
> It's closed because cli published a fix, so next time you init a fresh project or regenerate the lock file (to use cli v2.6.2 or newer), jetifier should be executed properly.

Thanks Got it to work...

**Comment by wkwyatt** [comment]
> maybe it will help someone
> 
> 1. npm i jetifier -D
> 2. add script "jetify": "jetify"
> 3. npm run jetify
> 4. react-native run-android --no-jetifier

Getting the error `unknown option --no-jetifier`
