### ISSUE TITLE
children not working properly

### ISSUE THREAD

**Issue by sajera** [facebook/react-native#25676]
React Native version:
info Fetching system and libraries information...
System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 18.92 GB / 31.87 GB
  Binaries:
    Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.8.0 - C:\Users\UserName\AppData\Roaming\npm\npm.CMD
  IDEs:
    Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5692245

## Steps To Reproduce
Just try to replace cheldren than bring it back

```javascript
class Preloader extends PureComponent {
    render () {
        const { children, active } = this.props;
        if (!active) {
            return children;
        }
        return <View> <ActivityIndicator size="large" /> </View>;
    }
}
class Test2 extends PureComponent {
  constructor (...args) {
        super(...args);
        this.state = { test: false };
    }
    render () {
        return (<View>
                <Button title="test" onPress={() => this.setState({test: !this.state.test })} />
                <Preloader active={this.state.test}>
                        <Text> Content text</Text>
                </Preloader>
       </View>);
    }
}
```
Error
Invariant Violation: Text strings must be rendered within a <Text> component

**Comment by thymikee** [comment]
Can you provide a repro we can download? I have troubles understanding what's wrong.
