### ISSUE TITLE
Hermes AndroidUnicodeUtils ClassNotFoundException

### ISSUE THREAD

**Issue by mllrmat** [facebook/react-native#25679]
Using 0.60.3 with Hermes enabled crashes with the following exception: 

`terminating with uncaught exception of type facebook::jni::JniException: java.lang.ClassNotFoundException: Didn't find class "com.facebook.hermes.unicode.AndroidUnicodeUtils"`

This only happens in release builds on real devices.

**Comment by ericlewis** [comment]
can you please post a repro?

**Comment by mllrmat** [comment]
I have enableProguardInReleaseBuilds enabled. So adding a line to my proguard-rules.pro config did the trick for me. 

`-keep class com.facebook.hermes.unicode.** { *; }`

From what I found out this is caused by some code in the "share" module. I am using https://github.com/react-native-community/react-native-share/ but it seams to happen with the react native build in one as well. 

Would be helpful if this proguard rule could be added somewhere. Where is the place this should go hermes/rn/react-native-share?
