### ISSUE TITLE
[ScrollView] Horizontal Scroll View scrolls up and down.

### ISSUE THREAD

**Issue by cmhsu** [facebook/react-native#2567]
I'm trying to do a horizontal scroll view with images. However, the user can scroll up the row of images. This happens in the sample Scroll View horizontal example too. Is there an easy fix? I'm tried setting a set height to the scroll view, the images, and the contentcontainer, but nothing is working. Thanks in advance.

**Comment by jeanregisser** [comment]
Set `alwaysBounceHorizontal={false}` to prevent that.

**Comment by brentvatne** [comment]
I wonder if we should make `alwaysBounceVertical` when `horizontal` is true, unless `alwaysBounceVertical` is otherwise explicitly specified. What do you think @jeanregisser?

**Comment by ide** [comment]
@brentvatne that's what the comments seemed to suggest and make sense. We should fix it if it's not behaving that way though I think in this case that logic might be right and instead the content and content insets of the scroll view are actually taller than its height.

**Comment by cmhsu** [comment]
Hi I tried alwaysBounceVertical={false}, but it didn't work. I eventually fixed it by setting automaticallyAdjustContentInsets={false}. Thank you for the responses though!

**Comment by mkonicek** [comment]
@facebook-github-bot stack-overflow
