### ISSUE TITLE
Scrollview on Android does not call onMomentumScrollEnd when scrolled programmatically

### ISSUE THREAD

**Issue by akshit5230** [facebook/react-native#25672]
I'm using a button to scroll a pagingEnabled horizontal scrollview to scroll to next page. I update some things on the screen in callback of the scrollview's onMomentumScrollEnd prop. In iOS the scrollview scrolls and the callback fires and things are updated when i press the button. But in android, the scrollview scrolls to next page but it does not trigger onMomentumScrollEnd callback. It does only when i manually scroll by gesture. I used 
`this._scrollviewReference.scrollto({ x: something, y: something, animated: true})`

React Native version:

React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (4) x64 Intel(R) Core(TM) i5-4570R CPU @ 2.70GHz
      Memory: 60.66 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.2.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.58.3 => 0.58.3 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

## Steps To Reproduce

1. i manually called the method by checking the platform if it is android

Describe what you expected to happen:

Snack, code example, or link to a repository:

**Comment by djhr** [comment]
same happening on react-native 0.59.5
