### ISSUE TITLE
TouchableOpacity is not working in Android

### ISSUE THREAD

**Issue by athma2409** [facebook/react-native#25678]
TouchableOpacity is working fine in IOS but its not at all working in Android with overlapped components.

I didn't use any position for that and I tried by removing Margin Negative also.

Can you please help with that.
Ex-: 
 <TouchableOpacity onPress={this.props.OnLiveChatClick} >
            <Image source={(this.state.isClicked) ? live_chat : null} />
   </TouchableOpacity>

**Comment by DivakarPM** [comment]
I am also facing same issue. Can somebody help

**Comment by wbinWang** [comment]
I am also facing same issue. Can somebody help
