### ISSUE TITLE
Haste module 'nodemailer' does not exist in haste module map

### ISSUE THREAD

**Issue by Blubagoo** [facebook/react-native#25681]
React Native version:
React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
      Memory: 158.68 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.5.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.6 => 16.8.6 
      react-native: 0.59.8 => 0.59.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Steps To Reproduce

1.npm install nodemailer
2.react-native run-ios

Describe what you expected to happen:
I expect metro-bundler to build correctly using a new nodemailer package instead I receive the following error
```Failed to load bundle(http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false) with error:(Unable to resolve module `net` from `/Users/lam/Desktop/beonews-pro/node_modules/nodemailer/lib/mailer/index.js`: Module `net` does not exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`. (null))

__38-[RCTCxxBridge loadSource:onProgress:]_block_invoke.213
    RCTCxxBridge.mm:414
___ZL36attemptAsynchronousLoadOfBundleAtURLP5NSURLU13block_pointerFvP18RCTLoadingProgressEU13block_pointerFvP7NSErrorP9RCTSourceE_block_invoke.118
__80-[RCTMultipartDataTask URLSession:streamTask:didBecomeInputStream:outputStream:]_block_invoke
-[RCTMultipartStreamReader emitChunk:headers:callback:done:]
-[RCTMultipartStreamReader readAllPartsWithCompletionCallback:progressCallback:]
-[RCTMultipartDataTask URLSession:streamTask:didBecomeInputStream:outputStream:]
__88-[NSURLSession delegate_streamTask:didBecomeInputStream:outputStream:completionHandler:]_block_invoke
__NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__
-[NSBlockOperation main]
-[__NSOperationInternal _start:]
__NSOQSchedule_f
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_continuation_pop
_dispatch_async_redirect_invoke
_dispatch_root_queue_drain
_dispatch_worker_thread2
_pthread_wqthread
start_wqthread
```
Snack, code example, or link to a repository:
import React, { PureComponent } from 'react'
import PropTypes from 'prop-types'
import { View, Text, ScrollView, TextInput, Button, Image, Animated } from 'react-native'
import wp from '@services/WPAPI'
import WebView from '@components/WebView/WebView'
import AnimatedButton from '@components/AnimatedButton/index'
import { Toolbar } from '@components'
import styles from './styles'


import nodemailer from 'nodemailer';


export default class CustomPage extends PureComponent {
  static propTypes = {
    id: PropTypes.any,
  }

  constructor(props) {
    super(props)
    this.state = {
      newsletterFName: '',
      newsletterLName: '',
      newsletterEmail: '',
      contactFName: '',
      contactLName: '',
      contactEmail: '',
      contactMessage: '',
      loading: false,
      success: false
    }
  }
  onSubmitNewsletter() {
    console.log('the form has been submitted');
    this.setState({
      loading: true
    })
    fetch('https://us18.api.mailchimp.com/3.0/lists/dad57ba7fe/members', {
      method: 'POST', // *GET, POST, PUT, DELETE, etc.
      mode: 'cors', // no-cors, cors, *same-origin
      cache: 'no-cache', // *default, no-cache, reload, force-cache, only-if-cached
      credentials: 'same-origin', // include, *same-origin, omit
      headers: {
          'Content-Type': 'application/json',
          'Authorization': 'Bearer ' + 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
          // 'Content-Type': 'application/x-www-form-urlencoded',
      },
      redirect: 'follow', // manual, *follow, error
      referrer: 'no-referrer', // no-referrer, *client
      body: JSON.stringify({
        "email_address": this.state.newsletterEmail,
        "status": "subscribed",
        "merge_fields": {
          "FNAME": this.state.newsletterFName,
          "LNAME": this.state.newsletterLName
        }
      }), // body data type must match "Content-Type" header
    })
    .then(response => {
      console.log('response before timeout', response);
      setTimeout(() => {
        console.log('inside timout')
        if(response.status !== 200) {
          this.setState({
            loading: false,
          })
        } else {
          this.setState({
            loading: false,
            newsletterEmail: '',
            newsletterFName: '',
            newsletterLName: '',
            success: true
          })
        }
      }, 2000);
    });
  }
  onSubmitContactForm() {
    console.log('contact form submitted');
    let email = this.state.contactEmail;
    let first = this.state.contactFName;
    let last = this.state.contactLName;
    let msg = this.state.contactMessage;

    // async..await is not allowed in global scope, must use a wrapper
    async function main(){


      // create reusable transporter object using the default SMTP transport
      let transporter = nodemailer.createTransport({
        host: "smtp.office365.com",
        port: 587,
        secure: false, // true for 465, false for other ports
        auth: {
          user: 'xxx', // generated ethereal user
          pass: 'xxx' // generated ethereal password
        }
      });

      // send mail with defined transport object
      let info = await transporter.sendMail({
        from: '"Fred foos" <foo@example.com>', // sender address
        to: this.state.contactEmail, // list of receivers
        subject: 'News.Law Mobile Contact Form', // Subject line
        text: this.state.contactMessage, // plain text body
        html: this.state.contactMessage // html body
      });

      console.log("Message sent: %s", info.messageId);
      // Message sent: <b658f8ca-6296-ccf4-8306-87d57a0b4321@example.com>

      // Preview only available when sending through an Ethereal account
      console.log("Preview URL: %s", nodemailer.getTestMessageUrl(info));
      // Preview URL: https://ethereal.email/message/WaQKMgKddxQDoou...
    }

    main().catch(console.error);
  }
}

**Comment by dulmandakh** [comment]
nodemailer is a nodejs module, so it cannot be used in React Native
