### ISSUE TITLE
ReactNativeJS ▶︎ Property '$RefreshReg$' doesn't exist

### ISSUE THREAD

**Issue by YajanaRao** [facebook/react-native#25684]
When I run `react-native start` I am getting error in the application as 
`'Failed to print error: ', 'Property \'$RefreshReg$\' doesn\'t exis
t'`

![screenshot-2019-07-17_10 21 02 356](https://user-images.githubusercontent.com/38914337/61348024-c8377700-a87c-11e9-97b3-cf584de812d4.png)

React Native version:

```
System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz
    Memory: 1.71 GB / 7.91 GB
  Binaries:
    Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: 4.9.0 - C:\Shortcut\watchman.EXE
  SDKs:
    Android SDK:
      Android NDK: 15.2.4203891
  IDEs:
    Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5522156
```

react-native 0.60.3

**Comment by valery-lavrik** [comment]
I have the same error.
Error due to **react-refresh** package which is used in **metro-react-native-babel-preset**. 
So it's probably not the point.

**Comment by AndrewJack** [comment]
Duplicate of #25622

**Comment by YajanaRao** [comment]
Walk around for this was to delete all the node modules and install them again.
