### ISSUE TITLE
[0.60.3] --sourcemap-output | enableHermes: false | gradle file | wrong output path

### ISSUE THREAD

**Issue by HazAT** [facebook/react-native#25693]
React Native version: `0.60.3`

## Steps To Reproduce

1. `react-native init test`
2. `cd test/android`
3. Make sure you have these default settings:
```
project.ext.react = [
    entryFile: "index.js",
    enableHermes: false,  // clean and rebuild if changing
]
```
4. `./gradlew assembleRelease --stacktrace`
5. Check content of `android/app/build/generated/assets/react/release/index.android.bundle`
6. Check last line, content is: `//# sourceMappingURL=index.android.bundle.packager.map`

**Expected:**

`//# sourceMappingURL=index.android.bundle.map`

---

So the problem with this is at least twofold.
First I think if `hermes` is not enabled it shouldn't mess with the `--sourcemap-output` parameter at all. Reason why this came up is this: https://github.com/getsentry/sentry-react-native/issues/612#issuecomment-511899296
Hermes apparently needs an intermediate path and messes with this arg which breaks our setup.

At Sentry we try to pick up on this arg to determine the location but, this is not the real location since you move the file there later, see: https://github.com/facebook/react-native/blob/0190c9c97b598b782d677e748d211437b4b85dd1/react.gradle#L172-L175
(Same for bundle)

And also, if the reference on the bottom of the file is not correct we cannot load it correctly.

I am not sure how to solve this since just copying instead of moving really doesn't.
If hermes is enabled it seems to work correctly, I am not sure why the source maps and bundle need to go in the intermediate folder tho.

If you know a way how to fix it, I would provide a PR for it.

**Comment by motiz88** [comment]
Hey, @HazAT, I'm sorry that this broke your workflow! Let's see what we can do.

>  if hermes is not enabled it shouldn't mess with the --sourcemap-output parameter at all.

This was a conscious choice, intended to keep things consistent for users of the two JS engines. The idea is that you will always find the source map at the same location, relative to the bundle file, whether you're using JSC or Hermes. (For context: Previously the Android build did not generate source maps at all.)

> If you know a way how to fix it, I would provide a PR for it.

This would be *massively* appreciated - thank you!

My suggestion is to change `react.gradle` to pass a different source map output path to the bundling command, depending on whether Hermes is enabled:
* For Hermes, pass `jsPackagerSourceMapFile` as we do now.
* For JSC, pass `jsOutputSourceMapFile` and don't do any moving/renaming afterwards.

That should result in the correct source map path being written to the JS bundle. Would that help your use case?

Note that Hermes support isn't on `master` yet, so if you do start working on a PR you should base it on the `0.60-stable` branch until https://github.com/facebook/react-native/pull/25613 lands.

Please let me know whether I can help with anything else.

**Comment by HazAT** [comment]
@motiz88 Thanks for the explanation, I will try to fix this in a PR, will reference you.

**Comment by vyshakh** [comment]
Workaround for blank screen. Set enableHermes: true
Version RN 60.0.3. 
OS Mac.
Thank you @HazAT

**Comment by HazAT** [comment]
@motiz88 I've created this PR https://github.com/facebook/react-native/pull/25700 tested it locally and it works.
In terms of:
> >if hermes is not enabled it shouldn't mess with the --sourcemap-output parameter at all.

> This was a conscious choice, intended to keep things consistent for users of the two JS engines. The idea is that you will always find the source map at the same location, relative to the bundle file, whether you're using JSC or Hermes. (For context: Previously the Android build did not generate source maps at all.)

One thing you should consider is that this forcefully now creates a source map for all builds and if ppl don't delete the source map before creating the APK, the source map will be shipped with it.
This will significantly increase the APK size.

In our SDK we cleanup the source map afterward so it will not be bundled:
https://github.com/getsentry/sentry-react-native/blob/ba01716f45fe40185f7785e064dcd0ed685fe417/sentry.gradle#L116-L121
but for those ppl who don't use Sentry, it will be bundled.

So, if you reconsider your choice of doing that, I can change the PR to not forcefully set the `--sourcemap-output` parameter.

**Comment by motiz88** [comment]
The intention was never to bundle the source map into the APK; if that's what we're doing, it's a bug. We might need to put the source map in a different directory to avoid this.

**Comment by motiz88** [comment]
@HazAT, could you take a look at #25710? Is this a viable setup for your use case?

**Comment by HazAT** [comment]
@motiz88 Will try to run it an let you know!

**Comment by HazAT** [comment]
@motiz88 confirmed, it works! Thx!

**Comment by motiz88** [comment]
Thanks again for surfacing this. Feel free to tag me on any further issues/requests related to source maps or crash logging.
