### ISSUE TITLE
EXC_BAD_ACCESS__cxa_throw Attempted to dereference garbage pointer 0x12da1002e

### ISSUE THREAD

**Issue by Kiran0791** [facebook/react-native#25690]
Hi
the above issue is happening on the production version of our app which crashes the and below is the stack-trace from bugsnag

EXC_BAD_ACCESS Attempted to dereference garbage pointer 0x12da1002e. 
    /usr/lib/system/libsystem_platform.dylib _os_unfair_lock_lock$VARIANT$armv81
    Frameworks/Foundation.framework/Foundation -[NSOperationQueue setMaxConcurrentOperationCount:]
    /Users/kiran/workspace/avibra_new/node_modules/react-native-fetch-blob/ios/RNFetchBlobNetwork.m:110:19 -[RNFetchBlobNetwork init]
    /Users/kiran/workspace/avibra_new/node_modules/react-native-fetch-blob/ios/RNFetchBlob/RNFetchBlob.m:131:50 __65-[RNFetchBlob fetchBlob:taskId:method:url:headers:body:callback:]_block_invoke
    /Users/kiran/workspace/avibra_new/node_modules/react-native-fetch-blob/ios/RNFetchBlobReqBuilder.m:177:9 __85+[RNFetchBlobReqBuilder buildOctetRequest:taskId:method:url:headers:body:onComplete:]_block_invoke
    /usr/lib/system/libdispatch.dylib __dispatch_call_block_and_release
    /usr/lib/system/libdispatch.dylib __dispatch_client_callout
    /usr/lib/system/libdispatch.dylib __dispatch_queue_override_invoke
    /usr/lib/system/libdispatch.dylib __dispatch_root_queue_drain
    /usr/lib/system/libdispatch.dylib __dispatch_worker_thread2
    /usr/lib/system/libsystem_pthread.dylib __pthread_wqthread

Kindly help to fix this

Regards
Kiran

**Comment by EskelCz** [comment]
I'm seeing the same issue with react native's `fetch` method.
