### ISSUE TITLE
Box-Shadow not working in OnePlus 6T

### ISSUE THREAD

**Issue by Sandeep023** [facebook/react-native#25715]
React Native version: 0.59.9

## Steps To Reproduce

1.  Simple  BoxShadow styling for View.

Describe what you expected to happen: 
  -> Instead of shadow around the View the border is getting elongated.

The link to the screenshot on my phone is :
https://user-images.githubusercontent.com/14028306/60788321-0a283500-a17a-11e9-841d-5604982783ac.jpg

Snack, code example, or link to a repository:
````
import * as React from 'react';
import { Text, View, StyleSheet } from 'react-native';

export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <View style={{
            borderRadius: 20,
            borderBottomWidth: 0,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 0 },
            shadowOpacity: 0.8,
            shadowRadius: 20,
            elevation: 3,
            justifyContent: 'center',
            alignItems: 'center',
            overflow: this.props.overflow ? this.props.overflow : 'hidden',
            width: 120,
            height: 150}}>
              <Text>Mine</Text>
        </View>
      </View>
    );
  }
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#ecf0f1',
    },
});
```
`

**Comment by rszalski** [comment]
@Sandeep023 try adding a `backgroundColor` to make the view opaque: https://snack.expo.io/@rszalski/4b7454. Does it look as expected now on your device? (Looks good on my OP6).

**Comment by Sandeep023** [comment]
Thanks for the help,

It's working fine now. But why is it working in other phones before and not in mine?
Anyway, I am closing the issue now Thanks for the help again.
