### ISSUE TITLE
Error Flatlist scrolling

### ISSUE THREAD

**Issue by JoynerPerez1987** [facebook/react-native#25714]
React Native version: 0.59.8

## Steps To Reproduce

1.After update, Flatlist scrolling in landscape screen on Android
2. In Dev mode is is correct but compile apk no work.

Is Dev mode:
![Screenshot_1563162157](https://user-images.githubusercontent.com/10671527/61459232-e7dca700-a931-11e9-9f8f-63aecff51c8d.png)

And is Apk compile:
![photo_2019-07-14 10 46 22 p  m](https://user-images.githubusercontent.com/10671527/61459283-0478df00-a932-11e9-9f20-9a1e413821de.jpeg)

**Comment by kiranjd** [comment]
Could you elaborate on what is not working? Also, post code snippet.

**Comment by JoynerPerez1987** [comment]
I have a horizontal screen with a FlatList inside but after updating native react in development mode it looks correct when creating the apk it is not seen correctly, as I show in the images
My code is verey simple:
`<View style={styles.container}>

        <Loading
          loading={this.props.loading}
        />

        <Columnas
          valores={this.props.informes.columnas === undefined ? [] : this.props.informes.columnas}
        />
        <View
          style={{
            flex: 1,
            borderColor: 'red',
            borderWidth: 3,
            backgroundColor: 'white',
          }}
        >
          <FlatList
            data={this.props.informes.filas}
            keyExtractor={(item, index) => index.toString()}
            renderItem={({ item }) => (
              <FilasSaldos
                valores={item}
              />
            )
}
          />
        </View>
      </View>`
