### ISSUE TITLE
FAILURE: Build failed with an exception.  * What went wrong: Could not determine java version from '12.0.1'.

### ISSUE THREAD

**Issue by iOSUser110** [facebook/react-native#25712]
## Description
* What went wrong:
Could not determine java version from '12.0.1'.
![Screenshot 2019-07-18 at 4 40 21 PM](https://user-images.githubusercontent.com/2657399/61453035-c2c05680-a97a-11e9-8170-c0cd25bb71ad.png)

##  React Native version:

System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Memory: 24.39 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.14.0 - /usr/local/bin/node
    npm: 6.7.0 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
  IDEs:
    Android Studio: 3.1 AI-173.4907809
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.8.6 => 16.8.6 
    react-native: ^0.60.3 => 0.60.3 
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Steps To Reproduce

1. react-native run-android --no-packager

How to run the project successfully.

**Comment by dulmandakh** [comment]
The issue is related to Gradle, not RN. RN 0.60 uses Gradle 5.4.1, and release notes says it supports JDK 12, see https://docs.gradle.org/5.4.1/release-notes.html. Maybe you should consider downgrading JDK. Thank you
