### ISSUE TITLE
Unexpected performance when using ItemSeparatorComponent in SectionList

### ISSUE THREAD

**Issue by xiongyuk** [facebook/react-native#25727]
When using ItemSeparatorComponent in SectionList, the last item of the previous page will render again when using onEndReached to fetch next page data, which causes image blinking beacause I use Image component of react-native-elements. 
 For example, the length of each page is defined as 10, and the render number will be 11 when the second page data is retrieved.  However, when I remove ItemSeparatorComponent, the render number of next page will be 10 as expected. And the render number will be always 10 as expected in FlatList whether I use ItemSeparatorComponent or not.

React Native version:
React Native Environment Info:
    System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 45.38 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.10.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      API Levels: 28
      Build Tools: 28.0.3
      System Images: android-25 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7

## Expected

Remove extra rendering when using ItemSeparatorComponent in SectionList

## Code Example

https://snack.expo.io/@xiongyu/sectionlist-test

**Comment by xiongyuk** [comment]
It still exists when i upgrade react-native to 0.60.4

**Comment by kiranjd** [comment]
Could you create a snack with the above code and share the link here. Also, verify if the problem persists.

**Comment by xiongyuk** [comment]
I have created the snack, the link is in the original post, and the problem still persists.
