### ISSUE TITLE
[0.60.4] Generating the release APK when enabling Hermes

### ISSUE THREAD

**Issue by MX8CLUB** [facebook/react-native#25726]
* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> A problem occurred starting process 'command '..\..\node_modules\hermesvm\win64-bin\hermes''

React Native version:
System:
    OS: Windows 10
    CPU: (12) x64 Intel(R) Xeon(R) CPU           X5675  @ 3.07GHz
    Memory: 6.54 GB / 15.99 GB
  Binaries:
    Node: 10.15.3 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.13.0 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
    npm: 6.4.1 - D:\Program Files\nodejs\npm.CMD

  },
  "dependencies": {
    "@ant-design/react-native": "^3.1.10",
    "react": "^16.8.6",
    "react-native": "^0.60.4",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-splash-screen": "^3.2.0",
    "react-navigation": "^3.11.1",
    "react-redux": "^7.1.0",
    "redux": "^4.0.4",
    "redux-saga": "^1.0.5",
    "rn-fetch-blob": "^0.10.16"
  },
  "devDependencies": {
    "@babel/core": "^7.5.5",
    "@babel/runtime": "^7.5.5",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.8.0",
    "eslint": "^6.0.1",
    "jest": "^24.8.0",
    "metro-react-native-babel-preset": "^0.55.0",
    "react-test-renderer": "16.8.6"
  },
  "jest": {
    "preset": "react-native"
  }

## Steps To Reproduce

1.react-native run-android --variant release

Describe what you expected to happen:

Generating the release APK

**Comment by LuckyLuke19** [comment]
Check this out: https://github.com/facebook/react-native/issues/25609#issuecomment-511119449

**Comment by leoxiaoping** [comment]
I have same bug

**Comment by hemmedo** [comment]
> Check this out: [#25609 (comment)](https://github.com/facebook/react-native/issues/25609#issuecomment-511119449)

that solution didn't work for me.
