### ISSUE TITLE
Linking.canOpenURL should return 'NO' when custom scheme isn't found in LSApplicationQueriesSchemes.  Behavior changed in commit 35b6f86 to throw instead of return 'NO' when scheme not found.  Throwing error here contradicts the methods purpose to answer 'YES/NO' if scheme can be opened. Method should resolve 'NO' (not reject) for schemes that are not supported.

### ISSUE THREAD

**Issue by garmire** [facebook/react-native#25722]
Linking.canOpenURL now throws an exception when passed a URL with scheme that is not found in LSApplicationQueriesSchemes.  This is a change in behavior that was introduced [here](https://github.com/facebook/react-native/commit/35b6f866f18f8c7e2085b44005aca3e63809c8d2) v60 with the intention of improving error messages. It seems instead the method should continue to resolve to false as it used to, not reject/throw.

React Native version:
System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
    Memory: 26.89 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.6.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4

## Steps To Reproduce

1. Call Linking.canOpenURL('cannotbeopened://example')
2. Observe thrown exception

Describe what you expected to happen:

Expect promise to resolve to 'false'

Snack, code example, or link to a repository:

`Linking.canOpenURL('cannotbeopened://example').then(supported => {
      if (!supported) {
        //seems still valid use case to end up here!
      } else {
        return Linking.openURL(appUrl);
      }
    }).catch(err => console.error('An error occurred', err));`

**Comment by garmire** [comment]
For reference, [UIApplication.canOpenURL](https://developer.apple.com/documentation/uikit/uiapplication/1622952-canopenurl) behaves as expected in that it can answer false. It returns a Boolean value indicating whether an app is available to handle a URL scheme.  The return value is documented as:

> false if no app installed on the device is registered to handle the URL’s scheme, or if you have not declared the URL’s scheme in your Info.plist file; otherwise, true.

Similarly, Linking.canOpenURL should resolve to false even when scheme isn't found in LSApplicationQueriesSchemes, not throw.

**Comment by albertogasparin** [comment]
I also hit this bug in react-native 0.60.5. Basically in 0.60.3 this code was valid:

```js
const gmaps = `comgooglemaps://q={q}&center=${latitude},${longitude}`;
if (await Linking.canOpenURL(gmaps)) {
  await Linking.openURL(gmaps);
} else {
  const amaps = `http://maps.apple.com/?q=${q}&sll=${latitude},${longitude}`;
  await Linking.openURL(amaps);
}
```

Now that code is no longer working as `Linking.canOpenURL` throws, making `canOpenURL` quite useless.
I've changed my code to be: 

```js
try {
  const gmaps = `comgooglemaps://q={q}&center=${latitude},${longitude}`;
  await Linking.openURL(gmaps);
} catch {
  const amaps = `http://maps.apple.com/?q=${q}&sll=${latitude},${longitude}`;
  await Linking.openURL(amaps);
}
```
Basically having `openURL` throw and catching the error to have the fallback behaviour.
