### ISSUE TITLE
Question: react-native run-android not working on Android Pie

### ISSUE THREAD

**Issue by chudaotrucnhan** [facebook/react-native#25724]
Hello, i have an issues when run-android on Android 9 like this image.
<img width="907" alt="Screen Shot 2019-07-19 at 09 26 03" src="https://user-images.githubusercontent.com/13350829/61505129-f4cbca00-aa07-11e9-962c-60c64a13dd02.png">

Everything is ok on Android 8 or Android 7.

I already try add "android:name="android.permission.INTERACT_ACROSS_USERS_FULL" android:protectionLevel="signature" but it not working.

**Comment by gluons** [comment]
Any solution for this issue?
