### ISSUE TITLE
After Upgrading to React native 0.59 Ios Picker is not selectable and became transparent In Ios 10.3.2 version

### ISSUE THREAD

**Issue by mzeeshansikander** [facebook/react-native#25731]
![Ukskog](https://user-images.githubusercontent.com/16585991/61513543-e76a0c00-aa16-11e9-8a62-7ff9e538be50.png)
![ecXKxs](https://user-images.githubusercontent.com/16585991/61513546-e9cc6600-aa16-11e9-9541-c8f36739ecea.png)

Recently I have updated react native from 0.57.2 to 0.59.3 and I have noticed that In Iphone 6 (Ios 10.3.2) Picker is not selectable.

**Comment by mzeeshansikander** [comment]
> Thanks for submitting your issue. Can you take another look at your description and make sure the issue template has been filled in its entirety?
> 
> 👉 [Click here if you want to take another look at the Bug Report issue template.](https://github.com/facebook/react-native/issues/new?template=bug_report.md)

I have already provided enough information

**Comment by dulmandakh** [comment]
Please use https://github.com/react-native-community/react-native-picker and report issues there.
