### ISSUE TITLE
instance.render is undefined

### ISSUE THREAD

**Issue by rabiaasif** [facebook/react-native#25733]
React Native version:
0.59.1

## Steps To Reproduce

1. update from 0.55.4 -> 0.59.1 
2. react-native run-android
<img width="319" alt="Screen Shot 2019-07-19 at 6 22 29 AM" src="https://user-images.githubusercontent.com/16907370/61528808-bb866080-a9ed-11e9-87b4-52c6521248ec.png">

followed all the steps to upgrade a few different times (i tried a few times to make sure this wasnt a user error)  i get the issue above... any suggestions on how i can fix this?
Describe what you expected to happen:

Snack, code example, or link to a repository:

**Comment by jordangrant** [comment]
@rabiaasif Poor band-aid solution to unblock you, replacing `render() {` with `render = () => {`
as per: https://github.com/facebook/react-native/issues/22378

**Comment by sunilju** [comment]
Same Issue I am getting. Help if some one have any idea about it.

**Comment by sunilju** [comment]
Have you solved It?

**Comment by DavidRafanan** [comment]
Is there a solution to this? I have tried render = () => { , but no difference.
