### ISSUE TITLE
framework not found React,inker command failed with exit code 1

### ISSUE THREAD

**Issue by lutakyn** [facebook/react-native#25735]
I get am error on one of the libraries,all builds are failing,I'm using CocoaPods to manage dependencies.
 ld: framework not found React
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`Ld /Users/mypc/Library/Developer/Xcode/DerivedData/projectx-agmovfcichistxhkaamivrarvpqp/Build/Products/Debug-iphonesimulator/RNReanimated/RNReanimated.framework/RNReanimated normal x86_64`

React Native version:
 React native info output:

      React Native Environment Info:
     System:
      OS: macOS 10.14.5
      CPU: (4) x64 Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
      Memory: 23.73 MB / 8.00 GB
     Shell: 3.2.57 - /bin/bash
      Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      npm: 6.5.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
     SDKs:
      iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
        Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28
        Build Tools: 26.0.2, 27.0.3, 28.0.3
      System Images: android-27 | Google Play Intel x86 Atom
      IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
     npmPackages:
      react: ^16.8.3 => 16.8.6 
     react-native: ^0.59.10 => 0.59.10 
      npmGlobalPackages:
      create-react-native-app: 2.0.2
     react-native-cli: 2.0.1
     react-native-git-upgrade: 0.2.7
   
   

## Steps To Reproduce

     1. npm i
    2. react-native link
    3. all libraries were linked
    4. cd ios
    5. pod install

    platform :ios, '9.0'

     use_frameworks!

     target 'projectx' do
 
     pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

     pod 'react-native-config', :path => '../node_modules/react-native-config'

    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

    pod 'react-native-maps', :path => '../node_modules/react-native-maps'

     pod 'React', :path => '../node_modules/react-native',:subspecs => [
      'Core',
      'CxxBridge'
     ]
     pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

     # Third party deps podspec link
     pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
     target 'VFGReactMVA10Tests' do
      inherit! :search_paths
       # Pods for testing
    end
     post_install do |installer|
      installer.pods_project.targets.each do |target|
       if target.name == "React"
        target.remove_from_project
       end
      end
      end
       end

Describe what you expected to happen:
Successful build on iOS

**Comment by iOSUser110** [comment]
I am also getting this issue even after upgrading to latest react-native version 


Unable to resolve module `../NativeAnimatedHelper` from `MyProject/node_modules/react-native/Libraries/Animated/src/nodes/AnimatedInterpolation.js`: The module `../NativeAnimatedHelper` could not be found from `MyProject/node_modules/react-native/Libraries/Animated/src/nodes/AnimatedInterpolation.js`. Indeed, none of these files exist:


#Versions : 
info Fetching system and libraries information...
System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Memory: 41.89 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.14.0 - /usr/local/bin/node
    npm: 6.7.0 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
  IDEs:
    Android Studio: 3.1 AI-173.4907809
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: ^0.60.4 => 0.60.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1

**Comment by waheedakhter** [comment]
I am having the same issue but I don't want to upgrade to react native to the latest. and I want the fix for the version of react-native that I am using. i.e 0.57.7

**Comment by arthedza** [comment]
Same issue

**Comment by rahamin1** [comment]
@waheedakhter @arthedza I am using 0.59.9 and I don;t want to upgrade right now because upgrades are painful :(
Have you found a solution in an RN version that is older than 0.60?
