### ISSUE TITLE
Check the render method of 'Flatlistdemo'

### ISSUE THREAD

**Issue by keshav00001** [facebook/react-native#25741]
![image](https://user-images.githubusercontent.com/34762556/61555323-be7c6200-aa7c-11e9-915d-b13cc0318794.png)
 **app.js**
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow
 */
import React, { Component } from "react";
import { List, ListItem } from "react-native-elements";
import {
  SafeAreaView,
  StyleSheet,
  ScrollView,
  View,
  Text,
  FlatList ,
  StatusBar,
} from 'react-native'

class FlatListDemo extends Component {
  constructor(props) {
    super(props);

    this.state = {
      loading: false,
      data: [],
      page: 1,
      seed: 1,
      error: null,
      refreshing: false,
    };
  }

  componentDidMount() {
    this.makeRemoteRequest();
  }

  makeRemoteRequest = () => {
    const { page, seed } = this.state;
    const url = `https://randomuser.me/api/?seed=${seed}&page=${page}&results=20`;
    this.setState({ loading: true });
    fetch(url)
      .then(res => res.json())
      .then(res => {
        this.setState({
          data: page === 1 ? res.results : [...this.state.data, ...res.results],
          error: res.error || null,
          loading: false,
          refreshing: false
        });
      })
      .catch(error => {
        this.setState({ error, loading: false });
      });
  };

  render() {
    return (
      <List>
      <FlatList
        data={this.state.data}
        renderItem={({ item }) => (
          <ListItem
            roundAvatar
            title={`${item.name.first} ${item.name.last}`}
            subtitle={item.email}
            avatar={{ uri: item.picture.thumbnail }}
          />
        )}
      />
    </List>

    );
  }
}

const styles = StyleSheet.create({
  scrollView: {
    backgroundColor: Colors.lighter,
  }
});

export default FlatListDemo;

//export default App;

please help...............................................................

**Comment by kiranjd** [comment]
Refer to [this snack](https://snack.expo.io/HkgwsK1fB). I tried to reproduce the problem but it seems something is wrong with your environment. It worked in the snack without making any changes.
