### ISSUE TITLE
Adding package starting with react-native to dev dependency breaks android build

### ISSUE THREAD

**Issue by Pita** [facebook/react-native#25743]
React Native version: 0.60.4

System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Memory: 1.04 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.14.1 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
  IDEs:
    Android Studio: 3.2 AI-181.5540.7.32.5056338
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.4 => 0.60.4
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7

## Steps To Reproduce

```
react-native init test2
cd test2
yarn add -D react-native-clean-project
yarn react-native run-android
yarn run v1.17.3
$ /private/tmp/test2/node_modules/.bin/react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 855 file(s) to forward-jetify. Using 8 workers...
info JS server already running.
info Installing the app...
Starting a Gradle Daemon, 1 busy and 3 stopped Daemons could not be reused, use --status for details
<-------------> 0% INITIALIZING [6s]
> Evaluating settings <-- IT GETS STUCK HERE
```

Describe what you expected to happen:

To see android app getting built

See https://github.com/pmadruga/react-native-clean-project/issues/22

**Comment by Pita** [comment]
If you remove the line ```
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
```
from settings.gradle, it gets to 50% at least

**Comment by Pita** [comment]
The bug is probably in the CLI package

**Comment by thymikee** [comment]
Yup, it's a CLI issue, let's resolve it there :)
