### ISSUE TITLE
AlertIOS broken in react-native v0.60.x

### ISSUE THREAD

**Issue by jordangrant** [facebook/react-native#25744]
![Simulator Screen Shot - iPhone 8 - 2019-07-20 at 04 11 24](https://user-images.githubusercontent.com/7986493/61576190-b33d2c80-aaa4-11e9-8270-60a0a9c00633.png)

React Native version:
0.60.4

## Steps To Reproduce

1. Call AlertIOS.prompt() or AlertIOS.alert()

## Was working before in 0.59.x

**Comment by jordangrant** [comment]
As mentioned in https://github.com/shimohq/react-native-prompt-android/issues/45, the resolution is to use Alert instead of AlertIOS. Alert.prompt() is working. Some documentation on this would be great

**Comment by dulmandakh** [comment]
Please use Alert. Thank you
