### ISSUE TITLE
RN 0.60 Hermes: Property 'Proxy' doesn't exist.

### ISSUE THREAD

**Issue by arivanandan** [facebook/react-native#25740]
RN: v0.60.4

Been upgrading this project from 0.53. Please let me know what could be causing this so I could follow up with code snippets of relevant files.

It goes away when I turn off hermes.

I also see this when the app is loading:
`couldn't find DSO to load: libjscexecutor.so`

![Screenshot_1563537223](https://user-images.githubusercontent.com/22584085/61550757-f8476b80-aa70-11e9-9300-80b2b9d385e9.png)

**Comment by ecreeth** [comment]
@arivanandan Please, make sure that the update of your project has been correct in the following [link](https://react-native-community.github.io/upgrade-helper/?from=0.53.3&to=0.60.4)

**Comment by guhungry** [comment]
I think it's because Hermes engine doesn't support Proxy https://github.com/facebook/hermes/issues/28

**Comment by arivanandan** [comment]
I have been using the rn-upgrade-helper and it's been very helpful!

So, if Proxy isn't present should I add a polyfill?

**Comment by guhungry** [comment]
I would suggest turn hermes off.
Proxy is low level API which can't be polyfilled completely and efficiently. But you can try https://github.com/GoogleChrome/proxy-polyfill

**Comment by arivanandan** [comment]
I tried it and it doesn't seem to work. Seems like we have to wait for hermes to support it (if at all).

**Comment by jp928** [comment]
@arivanandan 

Add 

```
project.ext.react = [
        root           : "../../../",
        entryFile      : "index.js",
        bundleAssetName: "index.bundle",
        enableHermes   : true,
        bundleInAlpha  : true,
        bundleInBeta   : true,
        hermesFlagsDebug:['-Xes6-proxy'],
        hermesFlagsRelease:['-Xes6-proxy']
]
```
in build.gradle

here is an example:
https://github.com/wix/react-native-notifications/blob/master/example/android/myapplication/build.gradle
