### ISSUE TITLE
Invariant Violation error

### ISSUE THREAD

**Issue by keshav00001** [facebook/react-native#25742]
React Native version:

## Steps To Reproduce

1 .     **app.js**
      export default class FlatListDemo extends Component {
  constructor(props) {
    super(props);

    this.state = {
      loading: false,
      data: [],
      page: 1,
      seed: 1,
      error: null,
      refreshing: false,
    };
  }

  componentDidMount() {
    this.makeRemoteRequest();
  }

  makeRemoteRequest = () => {
    const { page, seed } = this.state;
    const url = `https://randomuser.me/api/?seed=${seed}&page=${page}&results=20`;
    this.setState({ loading: true });
    fetch(url)
      .then(res => res.json())
      .then(res => {
        this.setState({
          data: page === 1 ? res.results : [...this.state.data, ...res.results],
          error: res.error || null,
          loading: false,
          refreshing: false
        });
      })
      .catch(error => {
        this.setState({ error, loading: false });
      });
  };

  render() {
    return (
      <List>
      <FlatList
        data={this.state.data}
        renderItem={({ item }) => (
          <ListItem
            roundAvatar
            title={`${item.name.first} ${item.name.last}`}
            subtitle={item.email}
            avatar={{ uri: item.picture.thumbnail }}
          />
        )}
      />
    </List>

    );
  }
}

2.  **index.js**

![image](https://user-images.githubusercontent.com/34762556/61557034-ce964080-aa80-11e9-961d-3fca0ad372e4.png)

Please help ....i am new in ReactNative.......

**Comment by kiranjd** [comment]
@keshav00001 This does not seem like a bug. Please post your questions on StackOverflow and feel free to open an issue if you decide it is an issue
