### ISSUE TITLE
 Couldn't connect to "ws://localhost:8081/message?device=Mi%20A1%20-%209%20-%20API%2028&app=com.satoshisoup&clientid=DevSupportManagerImpl", will silently retry

### ISSUE THREAD

**Issue by dominicg666** [facebook/react-native#25759]
I just created index.android.bundle using "react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res" command .
After that when I try to navigate several times, I'm getting this error message.

"Couldn't connect to "ws://localhost:8081/message?device=Mi%20A1%20-%209%20-%20API%2028&app=com.satoshisoup&clientid=DevSupportManagerImpl", will silently retry"

I've used Android native intent service to call API.Don't know if this is making the issue.

**Comment by RPeast** [comment]
Hello! I have the same problem. Have you solved it?
