### ISSUE TITLE
'React/RCTBridgeDelegate.h' file not found

### ISSUE THREAD

**Issue by Vibing** [facebook/react-native#25758]
**I follow the official website steps to create a react-native app, but it always fails:**

![20190722144357](https://user-images.githubusercontent.com/10387532/61611779-46d25100-ac8f-11e9-8b39-b65c5153a58c.jpg)

**react-native: v0.59.0
react: v16.8.3**

How should I solve it?

**Comment by evabhivyas** [comment]
![Screen Shot 2019-07-23 at 10 39 04 AM](https://user-images.githubusercontent.com/32292607/61684179-21e4e900-ad36-11e9-9a44-dc0c8ea2f970.png)


having the same issue

**Comment by zano5** [comment]
I have the same issue and react-native team are not helpful

**Comment by JLWalsh** [comment]
A temporary solution would be to run `pod install` in the `ios` directory, which will install the missing dependencies.

**Comment by leanhforevo** [comment]
I have same this proplem.
My slution is uninstall pod and re-Install pod. After that you need cd ios and run pod install 

Good luck :v

**Comment by klinskyc** [comment]
I'm having the same issue

**Comment by hbarylskyi** [comment]
I'm also having this issue. Trying to upgrade from 0.58.4 to 0.60.4. `pod install` didn't help.

**Comment by hbarylskyi** [comment]
I've encountered this issue while upgrading from 0.58.4 to new react-native version 0.60.4. Nothing from what i found on the internet helped me, but I managed to get it working:

**Go to build settings, search for 'Header search paths', select the entry, press DELETE button.**

I had these values overriden, and looks like they fell back to defaults after deletion. Also Cocoapods was complaining about it with messages in Terminal after `pod install`:

    [!] The `app [Release]` target overrides the `HEADER_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-app/Pods-app.release.xcconfig'. This can lead to problems with the CocoaPods installation

**Comment by BooYeu** [comment]
I have the same problem

**Comment by dbarkleyjr** [comment]
Had the same problem. Issue for me was that `pod install` was never run in the iOS directory. Issue was fixed after running that (took a very long time).

**Comment by ldco2016** [comment]
Has a solution been found for this? I am getting the same error, despite the fact that I do have that file in my `Pods/Headers/` directory.

**Comment by Saroopashree** [comment]
This worked for me.
In the shell do the following commands.
1. Navigate to your working directory.
2. `cd ios`
3. `pod deintegrate`
4. `pod install`
5. `cd ..`
6. `react-native run-ios`

Hope this helps!

**Comment by ldco2016** [comment]
Thanks @Saroopashree , I think I did end up doing something like this.

**Comment by ilkerdogan** [comment]
pod update is worked for me!

cd ios/
pod update
cd ..
react-native run-ios

**Comment by xclidongbo** [comment]
the same error.

**Comment by Renathesco** [comment]
I'm facing the same problem

**Comment by Saroopashree** [comment]
@Renathesco and @xclidongbo Did you do `pod deintegrate` and `pod install` or `pod update` ?
Either one of them will most probably solve the error.

**Comment by Renathesco** [comment]
> @Renathesco e @xclidongbo Você fez `pod deintegrate`e `pod install`ou `pod update`?
> Qualquer um deles provavelmente resolverá o erro.

Yes I did, I'm upgrading my xcode to version 11 to see if that solves the problem

**Comment by Cael00** [comment]
Hi, I got Xcode version 11.4.1 and React-native version 2.0.1, when a run `pod update` or `pod install` got this error at the end:

`xcrun: error: unable to lookup item 'Path' in SDK 'iphoneos'
/Users/cael/Library/Caches/CocoaPods/Pods/Release/Flipper-Glog/0.3.6-1dfd6/missing: Unknown `--is-lightweight' option
Try `/Users/cael/Library/Caches/CocoaPods/Pods/Release/Flipper-Glog/0.3.6-1dfd6/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: in `/Users/cael/Library/Caches/CocoaPods/Pods/Release/Flipper-Glog/0.3.6-1dfd6':
configure: error: C compiler cannot create executables
See `config.log' for more details`

**Comment by Cael00** [comment]
I made it!  Use @YuryKorovko, in this post [https://github.com/facebook/react-native/issues/18408](url)

Now it is working.
