### ISSUE TITLE
[NavigatorIOS] how to catch the moment that view switch event done

### ISSUE THREAD

**Issue by nosensezzz** [facebook/react-native#2575]
I ran into a issue when I use the NavigatorIOS component.

after user click a button, it start a ajax call, during the ajax call, user could click the button but it won't do anything because I set a loading parameter to prevent it, after ajax call done, I switch the view by push new viewmodel into NavigatorIOS array, and the page will switch to the new page, issue happens here, because I set loading to false after I the navigatorios.push function, there is a very short moment pages are switch but the loading parameter already been set to false, so if user click the button during the page switch animation happening, it will push two page to the NavigatorIOS array.

I am thinking use settimeout to handle this issue, but I feel it very unprofessional, do you guys have any good method to handle this situation?

**Comment by brentvatne** [comment]
Please read this documentation: https://facebook.github.io/react-native/docs/navigator-comparison.html#content

I highly recommend using Navigator instead. This functionality is not built into NavigatorIOS and that component is not maintained by the team at Facebook or any core contributors :(

**Comment by mkonicek** [comment]
@facebook-github-bot answered
