### ISSUE TITLE
Question: getPropertyAsObject: property '__fbRequireBatchedBridge' is not an Object

### ISSUE THREAD

**Issue by saeedkargosha** [facebook/react-native#25757]
when I run react-native run-ios
```Unhandled JS Exception: getPropertyAsObject: property '__fbRequireBatchedBridge' is not an Object no stack```
![Simulator Screen Shot - iPhone X - 2019-07-22 at 10 10 49](https://user-images.githubusercontent.com/24919918/61608743-111a7180-ac69-11e9-82b4-fb832baeddd6.png)

React Native version:
``` 
"react-native": "^0.59.6"
"react": "16.8.3"
"macOS": "Mojave version 10.14.5"

```

**Comment by t-gao** [comment]
any update on this?
