### ISSUE TITLE
no type or protocol named 'RCTTurboModuleLookupDelegate'

### ISSUE THREAD

**Issue by kalpesh9896** [facebook/react-native#25766]
![image](https://user-images.githubusercontent.com/50480112/61630991-c7507c00-aca6-11e9-8421-5b662c5930b5.png)

I am facing this issue in iOS when I create build with CircleCI.

'RCTTurboModuleLookupDelegate' was added in react-native's 0.59.0 version.

React Native Environment Info:
System:
OS: macOS 10.14.5
CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
Memory: 229.88 MB / 8.00 GB
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 10.16.0 - /usr/local/bin/node
Yarn: 1.15.2 - /usr/local/bin/yarn
npm: 6.9.0 - /usr/local/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
SDKs:
iOS SDK:
Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
Android SDK:
API Levels: 22, 23, 24, 25, 26, 27, 28
Build Tools: 23.0.1, 23.0.2, 23.0.3, 24.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.0
, 27.0.1, 27.0.2, 27.0.3, 28.0.2, 28.0.3, 29.0.1
System Images: android-22 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-26
| Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
IDEs:
Android Studio: 3.4 AI-183.6156.11.34.5692245
Xcode: 10.1/10B61 - /usr/bin/xcodebuild
npmPackages:
react: 16.8.3 => 16.8.3
react-native: 0.59.4 => 0.59.4
npmGlobalPackages:
react-native-cli: 2.0.1
react-native-scripts: 2.0.1

any one can help me?

Thak you.

**Comment by kalpesh9896** [comment]
React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
      Memory: 229.88 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 22, 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.2, 23.0.3, 24.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.0
, 27.0.1, 27.0.2, 27.0.3, 28.0.2, 28.0.3, 29.0.1
        System Images: android-22 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-26
 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.4 => 0.59.4 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-scripts: 2.0.1

**Comment by kalpesh9896** [comment]
![Screenshot 2019-07-22 at 6 28 57 PM](https://user-images.githubusercontent.com/50480112/61634270-996f3580-acae-11e9-8973-cff5b2dedd55.png)

I checked code in the latest version's repository(0.60.4), but there is the same code available. So this issue will be not solved by updating react-native version.

**Comment by kalpesh9896** [comment]
I resolved this issue 

I replace `.circleci/RCTBridgeModule.h` with `node_modules/react-native/React/Base/RCTBridgeModule.h`.

**Comment by prayuditb** [comment]
Hi @kalpesh9896, can you tell me a bit more detail about what you are doing to solve this issue?
I encountered the same issue too. thanks in advance

**Comment by kalpesh9896** [comment]
I used circleci for generating release build. In .circleci folder that I use RCTBridgeModule.h file who is same as this file node_modules/react-native/React/Base/RCTBridgeModule.h.

so for solving this issue I replaced that file.
