### ISSUE TITLE
Modal not show inside network request on iOS

### ISSUE THREAD

**Issue by sophister** [facebook/react-native#25765]
React Native version:

info
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 925.04 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.1 - ~/.nvm/versions/node/v10.14.1/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.14.1/bin/npm
      Watchman: 4.4.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 24, 28
        Build Tools: 23.0.1, 24.0.0, 24.0.1, 24.0.2, 24.0.3, 26.0.2, 27.0.3, 28.0.3
        System Images: android-24 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.3 => 0.59.3
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-tinker-cli: 1.7.0

## Steps To Reproduce

1. I have two `Modal` in my component, modalA and modalB
2. click a button to show modalA, at the same time, `fetch` some API, and in the response handler, close modalA and show modalB
3. modalA hide, but modalB does not show

Describe what you expected to happen:

modalA hide, and modalB show

In addition, in step 2, if I use a `setTimeout` to close modalA and show modalB, it works. 
It seems like something goes wrong when changing multiple `Modal` visible in the handler of network request.

[Snack demo](https://snack.expo.io/@sophister/modal-test)

**Comment by zhongwuzw** [comment]
Suggest to dismiss one Modal firstly, after dismissed, present another.

`UIKit` can't present and dismiss concurrently for one VC correctly. So it may happened that Modal may not appear.

**Comment by sophister** [comment]
@zhongwuzw But, if I change the visibility inside `setTimeout`, it works perfectly. The problem only occurs when `setState` is inside of the network handler

**Comment by zhongwuzw** [comment]
@sophister Looks like it works using `setTimeout`, but actually it's not, you can try decrease the timeout `delay` param to a more little value like 100ms.

```
  showWithTimeout = () => {
    this.setState({
      visibleOne: true,
    }, () => {
      setTimeout(() => {
        this.setState({
          visibleOne: false,
          visibleTwo: true,
        });
      }, 100);
    });
  };
```

**Comment by sophister** [comment]
@zhongwuzw you're right, changing the `delay` of `setTimeout` also results in the missing modal. I don't get it since actually, we are changing the visibility of two modals concurrently, why the `delay` can affect the rendering of the modal. 
In my case, I just want to show a loading dialog, and when the response received, close the loading and show another dialog. So I write like this

```javascript
function onSubmit() {
    setLoading(true);
    fetch(xxx).then(function(res){
        setLoading(false);
        // update some state and show the result dialog
        setResultDialogVisible(true);
    } );
}
```
If I have to wait for the loading's dismiss event, it will be a little complex, because many other user actions will also show the loading dialog.
Do you have any suggestions for such situations?

**Comment by zhongwuzw** [comment]
I think you may need to implement [onDismiss](https://facebook.github.io/react-native/docs/modal.html#ondismiss) function of Loading Modal, after its `onDismiss` be called, we can present another Modal safely.

**Comment by sophister** [comment]
@zhongwuzw  thx for your advice. I decide to change the loading dialog from `Modal` to a custom `View` component, to get rid of the two `Modal` concurrent problem 😅
