### ISSUE TITLE
React native init with 0.60.4 fails to build on tvOS 

### ISSUE THREAD

**Issue by godwin-codeprism** [facebook/react-native#25764]
React native init with 0.60.4 fails to build on TV OS 

React Native version:
System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 380.02 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.10.1 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Steps To Reproduce
1. react-native init appName
2. Open appName.xcworkspace
3. Change target to appName-tvOS
4. Hit Run

Build Fails with the following error:
`library not found for -lPods-appName-tvOS`

**Comment by baleo-it** [comment]
Exact same problem here!

**Comment by slavikdenis** [comment]
Maybe this should help? https://github.com/facebook/react-native/issues/25820#issuecomment-515742426

**Comment by DrankoLQ** [comment]
In my case, running `pod install` in the project folder didn't fix the problem

**Comment by FPerellocano** [comment]
Same problem here, did you guys find another solution?

**Comment by kubatyi** [comment]
@FPerellocano it works with 0.59

**Comment by morgondag** [comment]
```0.59``` works with this https://github.com/facebook/react-native/issues/21168#issuecomment-423113070 on ```Xcode 10+``` but we want that good ```0.60.4``` stuff.

**Comment by godwin-codeprism** [comment]
Was anyone able to solve this with 0.60.5?

**Comment by changerrs** [comment]
also have the same issue.

**Comment by 3DEsprit** [comment]
Same issue when using 61.5. 

I also came across the [RN community tvos repo](https://github.com/react-native-community/react-native-tvos). Is tvOS support being dropped from the main project officially?
