### ISSUE TITLE
[Navigator.NavigationBar] How to navigate to different states using navigationBar buttons

### ISSUE THREAD

**Issue by alvaromb** [facebook/react-native#2576]
I have a navigation graph that looks like this:

```
            +---+           
            | A |           
            +---+           
            |  |            
            |  |            
     +---+  |  |  +---+     
     | B | <+  +> | B'|     
     +---+        +---+     
       |            |       
+---+  |            |  +---+
| C | <+            +> | C'|
+---+                  +---+
```

And the navigation stack at ``B`` would be ``[A, B]``. If I'm at ``B'``, the stack would be ``[A, B']``. The states ``B`` and ``B'`` transition to different states, ``C`` and ``C'``, and that transition is done with the right element of the navigation bar (a button in this case).

Is it possible to define the right button element of the navigation bar in each state ``B`` and ``B'`` or I have to code the condition in the route mapper object provided in the ``A`` state? How this case should be managed? If it was a unique navigation path I could use the index, but in this case I have to set the button conditionally depending on the props of the route, is it the right way to do it?

**Comment by alvaromb** [comment]
While writing this I came up with a solution. You can pass whatever you want inside the ``route`` object and catch it inside the route mapper:

```javascript
RightButton: (route, navigator, index, navState) => {
  if (route.rightElement) {
    return route.rightElement
  }
},
```

When pushing the state:
```javascript
this.props.navigator.push({
  component: <Component />,
  passProps: {
    // Your props
  },
  title: 'Title',
  rightElement:
    <NavBarRightComponent />
})
```

**Comment by ide** [comment]
Exactly. Navigator prescribes very little so you can put whatever you want in your route, whether you choose to use an object or a string.

**Comment by alvaromb** [comment]
So if I want to define a custom button I have to do it always when pushing the component, right?

Enviado desde mi iPhone

**Comment by ide** [comment]
Yes, and that custom button can do whatever you want. The navigator routes are super flexible this way.

**Comment by alvaromb** [comment]
Sorry to bother @ide, but I'm wrapping my head around about how can I define a ``NavigationBar`` button that opens a ``<Modal />`` in the pushed component. As we've said before, the button must be defined when pushing, so the press event will not be visible in the pushed component. The only solution I came with so far is to use Flux or Redux to manage the open/closed modal state, but it seems a bit overkill.

Let me know if the question is too broad and I'll open a SO question.

**Comment by ide** [comment]
Create and EventEmitter and pass it into the the button and the scene component to let them communicate. Or you can use Flux or a global variable, etc. Really up to you.
