### ISSUE TITLE
[TextInput]  set maxLength={10}  iOS crash

### ISSUE THREAD

**Issue by walkerzhy** [facebook/react-native#25761]
React Native version:

## Steps To Reproduce

1.set TextInput maxLength={10}
2.input  'kekoukeleeeeeeeeefff'
3.ios crash

Describe what you expected to happen:

1.set TextInput maxLength={10}
2.input  'kekoukeleeeeeeeeefff'
3.ios crash
Snack, code example, screenshot, or link to a repository:
![企业微信截图_4bb3fed5-5b93-42aa-ae6c-f5cc59eb6370](https://user-images.githubusercontent.com/30283053/61617150-b438ae80-ac9c-11e9-9050-ded1cf4c333d.png)

**Comment by zhongwuzw** [comment]
@walkerzhy Hi, I think we already fixed it in `master` branch but not released. Can you check that?

**Comment by walkerzhy** [comment]
@zhongwuzw sorry my english poor.But I'm chinese,we can talk with chinese.  what do u mean "Can you check that?".  Do u mean i can get a develop version to check it  corrected or not?  if that ,i can.
