### ISSUE TITLE
Opacity with Text issue in Android

### ISSUE THREAD

**Issue by prabhjodhOYO** [facebook/react-native#25762]
- If set some opacity to text and some backgroundColor to the View containing the Text component, the Text component renders buggy (as shown in screenshots) in Android only (working fine on Android).
- Code example: 

```
<View style={{ height: 27, backgroundColor: "red" }}>
    <Text numberOfLines={1} style={{ fontSize: 12, color: "rgba(255,255,255,0)", textAlign: "center", padding: 2 }}>
        {percentage}
    </Text>
</View>

```

React Native version: 0.57.4

## Steps To Reproduce

1. Create the View (with a backgroundColor) containing a Text component setting opacity of Text color to 0. (as shown in code above)
2. Run both iOS and Android emulators to see the difference

Describe what you expected to happen: Expected behavior of Text as it happens in iOS.

Snack, code example, screenshot, or link to a repository:

See the percentage text inside the bar on both platforms.

Android: 
<img width="383" alt="Screen Shot 2019-07-22 at 3 52 07 PM" src="https://user-images.githubusercontent.com/46446002/61625588-b7ca3680-ac98-11e9-9401-e405b53e1191.png">

iOS:
<img width="302" alt="Screen Shot 2019-07-22 at 3 52 15 PM" src="https://user-images.githubusercontent.com/46446002/61625589-b862cd00-ac98-11e9-8591-a5a8533c5143.png">

**Comment by vinicarra** [comment]
Have you tried setting the opacity as a style property and not along with text color? For example:
```
<View style={{ height: 27, backgroundColor: "red" }}>
    <Text numberOfLines={1} style={{ fontSize: 12, color: "rgba(255,255,255)", textAlign: "center", padding: 2, opacity: 0 }}>
        {percentage}
    </Text>
</View>
```

**Comment by prabhjodhOYO** [comment]
> Have you tried setting the opacity as a style property and not along with text color? For example:
> 
> ```
> <View style={{ height: 27, backgroundColor: "red" }}>
>     <Text numberOfLines={1} style={{ fontSize: 12, color: "rgba(255,255,255)", textAlign: "center", padding: 2, opacity: 0 }}>
>         {percentage}
>     </Text>
> </View>
> ```

Yes I tried that too, leads to same result.
