### ISSUE TITLE
How to show minimum number of characters in a text followed with dot(..)

### ISSUE THREAD

**Issue by nihp** [facebook/react-native#25779]
I need to show a text with 10 characters. Remaining characters need to hide and it will be followed by a double dot (Eg: Fantastic fu..)

**Comment by nihp** [comment]
This is my clarification question

**Comment by zcgit** [comment]
I think you could do it buy yourself, maybe you should use (text + ".") or (text + "........")

**Comment by nihp** [comment]
Yeah I tried with myself. It worked
