### ISSUE TITLE
Line appears on iPhone6 plus without LaunchScreen.xib

### ISSUE THREAD

**Issue by list000001** [facebook/react-native#2577]
Line appears on iPhone6 plus without LaunchScreen.xib. When I remove launch screen file in my project,there are some lines around the text,only appear on iPhone6 plus.

![ios simulator screen shot 2015 9 7 4 21 44](https://cloud.githubusercontent.com/assets/3348326/9712351/9c57ab02-557c-11e5-9134-dcb08487d457.png)
![2015-09-07 4 22 32](https://cloud.githubusercontent.com/assets/3348326/9712361/af26ca7e-557c-11e5-95b0-5fe01836764e.png)

**Comment by list000001** [comment]
@brentvatne @nicklockwood

**Comment by browniefed** [comment]
Duplicate https://github.com/facebook/react-native/issues/2018

**Comment by brentvatne** [comment]
Thanks for the report @list000001! I've pinged Nick on #2018, but if you have time to investigate this yourself and try to fix it, that would be fantastic.
