### ISSUE TITLE
Changing bundler location with dev menu broken when changing port

### ISSUE THREAD

**Issue by TheSavior** [facebook/react-native#25772]
When changing the port of the bundler by using the devmenu, ios tries to connect to an invalid URL.

This functionality was added in https://github.com/facebook/react-native/pull/21970 and never worked for changing ports.

When paused in the debugger, this is the url of metro that it is trying to connect to: 

![Screen Shot 2019-07-22 at 2 54 29 PM](https://user-images.githubusercontent.com/249164/61669390-c282cc80-ac94-11e9-8f02-6a50dfd9c873.png)

Set with this:
![Simulator Screen Shot - iPhone X - 2019-07-22 at 15 24 48](https://user-images.githubusercontent.com/249164/61669415-db8b7d80-ac94-11e9-95ba-e209eb046950.png)

React Native version:
```
System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Memory: 1.46 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.7.0 - ~/.yarn/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    Watchman: 4.9.4 - /opt/facebook/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28
      Build Tools: 23.0.1, 25.0.0, 25.0.2, 27.0.3, 28.0.2, 28.0.3, 29.0.0
      System Images: android-24 | Intel x86 Atom, android-24 | Google APIs Intel x86 Atom_64, android-25 | Google APIs Intel x86 Atom, android-25 | Google Play Intel x86 Atom
      Android NDK: 15.2.4203891
  IDEs:
    Android Studio: 3.3 AI-182.5107.16.33.5314842
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4
```

**Comment by TheSavior** [comment]
@chubakueno, would you be able to help dig in and fix this?

**Comment by dratwas** [comment]
@TheSavior I tried it with and without remote debugger connected on fresh RN `0.60.4` project and it seems to work. I'm able to start 2 packagers on different ports and switch between them. However it never stops when i set the breakpoint in `RCTReconnectingWebSocket.m:109`

Do i need to do something to reproduce it?

**Comment by TheSavior** [comment]
@dratwas, can you try rebasing on top of this PR? https://github.com/facebook/react-native/pull/25803 It should allow it to pause at the breakpoint.

**Comment by chubakueno** [comment]
Hi @TheSavior , i cant reproduce the error you are describing. Just downloaded a fresh 0.60.4 and tested it both in emulator (using localhost) and in physical (using my computer private IP), both using remote debugging and not, both using hot reloading and not. May you please tell me which specific commit are you in?

**Comment by chubakueno** [comment]
Found a tiny(separate) issue during testing though: If you don't write the host, it correctly loads the js from the bundler but it fails to connect to the debugger if debugging is enabled (it searches for https://:8081, for example). I would prefer to debug the issue you refer to before landing this minor fix on a pull request on master.

**Comment by TheSavior** [comment]
Thanks for investigating. I don’t think the PR I mentioned shipped in a release yet so I’d recommend making this one line change locally in order to test: https://github.com/facebook/react-native/commit/4ab9da134c988db832b1a2daa90ce38bf8c419eb

Hopefully that works! 🤞😀
