### ISSUE TITLE
Picker doesn't show all values until scrolled on Android

### ISSUE THREAD

**Issue by subramanyaRB** [facebook/react-native#25778]
I have a react-native picker that shows dynamically mapped picker items, the picker basically shows time slots (picker items) from 9:00 am to 12:00 am, the array from which the picker items are mapped contains slots such that the first slot is always 30 mins ahead of the current time of today. when I change the date from today to another the picker array will receive all the slots from 9:00 am to 12:00 am, even though the array containing new picker items changes the picker's bar still shows that the value is the old value of the slot (i.e a slot ahead of 30 mins from now) but if I log the value of the picker it seems to point to the proper value (i.e 9:00 am), I can only see all the picker items when I scroll up.

React Native version:
 React Native Environment Info:
    System:
      OS: Linux 4.18 Ubuntu 18.04.2 LTS (Bionic Beaver)
      CPU: (4) x64 Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz
      Memory: 102.14 MB / 3.73 GB
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 8.10.0 - /usr/bin/node
      npm: 3.5.2 - /usr/bin/npm
    npmPackages:
      react: ^16.8.6 => 16.8.6 
      react-native: ^0.60.4 => 0.60.4 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Steps To Reproduce

1. Try using a react-native picker that gets its picker items from a map function of a dynamic array.

Describe what you expected to happen:
The picker's bar should automatically slide over to the top value of the array

**Comment by maximilianoforlenza** [comment]
@subramanyaRB Could you fix this problem?

**Comment by subramanyaRB** [comment]
@maximilianoforlenza , no I haven't been able to fix it, since I think the issue is with the picker itself and not the way I've used it. It works fine on iOS though.
