### ISSUE TITLE
java.lang.UnsatisfiedLinkError:    at com.facebook.soloader.SoLoader.doLoadLibraryBySoName (SoLoader.java:738)

### ISSUE THREAD

**Issue by john1jan** [facebook/react-native#25782]
App crashes after android app bundle.

React Native version:
React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
      Memory: 36.11 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.6.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
    SDKs:
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 26.0.2, 28.0.3
        System Images: android-19 | Intel x86 Atom, android-19 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.5 => 16.8.5
      react-native: 0.59.5 => 0.59.5
    npmGlobalPackages:
      generator-react-native-ignite: 1.13.0
      react-native-cli: 2.0.1
      react-native-ignite: 1.13.0

## Steps To Reproduce

1. Not able to reproduce, app crashes are increasing 

Describe what you expected to happen: No crash

<img width="1141" alt="Screenshot 2019-07-23 at 6 13 54 PM" src="https://user-images.githubusercontent.com/4264813/61713226-aacf4500-ad75-11e9-91fe-2c555a86af2e.png">

**Comment by adnkh** [comment]
Still happening with 0.60.5

**Comment by john1jan** [comment]
@react-native-bot 
![what](https://user-images.githubusercontent.com/4264813/63668039-82fb5300-c7f3-11e9-9004-090b395924db.jpeg)

**Comment by marcorm** [comment]
Hi @john1jan we're experiencing this kind of issue too. Did you find any solution?

**Comment by aashirMIQ** [comment]
> Hi @john1jan we're experiencing this kind of issue too. Did you find any solution?

I am also ran into the same issue.

**Comment by kubraturan** [comment]
Hi, I have the same problem. Did you find a solution?

**Comment by TranHuuTrung** [comment]
Has anyone found a solution to this problem yet?

**Comment by john1jan** [comment]
@react-native-bot the issue is still not resolved we are getting the same crash more and more

**Comment by SMKH-PRO** [comment]
```
02-01 19:00:28.632  4467  4506 E AndroidRuntime: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libreactnativejni.so
02-01 19:00:28.632  4467  4506 E AndroidRuntime:        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:738)
02-01 19:00:28.632  4467  4506 E AndroidRuntime:        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591)
02-01 19:00:28.632  4467  4506 E AndroidRuntime:        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:529)
02-01 19:00:28.632  4467  4506 E AndroidRuntime:        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:484)
02-01 19:00:28.632  4467  4506 E AndroidRuntime:        at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:31)
02-01 19:00:28.632  4467  4506 E AndroidRuntime:        at com.facebook.react.bridge.Inspector.<clinit>(Inspector.java:19)
02-01 19:00:28.632  4467  4506 E AndroidRuntime:        at com.facebook.react.bridge.Inspector.getPages(Inspector.java:26)
02-01 19:00:28.632  4467  4506 E AndroidRuntime:        at com.facebook.react.devsupport.InspectorPackagerConnection.getPages(InspectorPackagerConnection.java:147)
02-01 19:00:28.632  4467  4506 E AndroidRuntime:        at com.facebook.react.devsupport.InspectorPackagerConnection.handleProxyMessage(InspectorPackagerConnection.java:64)
```

APP CRASHES ON LAUNCH, This is what i found in `catlog`

**Comment by andreslargo** [comment]
Issue persist?

**Comment by taschik** [comment]
unfortunately yes :(

**Comment by gvsakhil** [comment]
Issue persists still for today

**Comment by ArvindNikam76** [comment]
yes

**Comment by devdeepakrathod** [comment]
I upgraded my react native from 59.10 to 62.0, so I got the same issue the following answer is copied from StackOverflow that helped me.
--------------------------------------------------------------------------------------------------
I solved this problem by this steps

install hermesvm : npm i hermesvm
install jsc-android : npm i jsc-android
3.add this lines to app/build.gradle

project.ext.react = [
   entryFile: "index.js" ,
   enableHermes: false
]

def jscFlavor = 'org.webkit:android-jsc:+'
def enableHermes = project.ext.react.get("enableHermes", false);


dependencies {
   if (enableHermes) {
       def hermesPath = "../../node_modules/hermesvm/android/";
       debugImplementation files(hermesPath + "hermes-debug.aar")
       releaseImplementation files(hermesPath + "hermes-release.aar")
    }
   else { implementation jscFlavor }
add this jsc-android block to your android/build.gradle:

allprojects {
   repositories {
     maven {
       url("$rootDir/../node_modules/react-native/android")
     }
     maven {
        url "$rootDir/../node_modules/jsc-android/dist"
     }
     google()
     jcenter()
   }
 }
-----------------------------------------------------------------------------
cd android && gradlew clean has also helped my developers
-----------------------------------------------------------------------------
If you are upgrading your react-native then, it's possible that upgrade my
not be successful every time so check following link to review changes 
https://react-native-community.github.io/upgrade-helper/?from=0.59.10&to=0.62.0
https://react-native-community.github.io/upgrade-helper/?from=version_from&to=version_to
-----------------------------------------------------------------------------------------------

Hope it helps

**Comment by john1jan** [comment]
So you meant to say, after enabling hermes engine this crash got solved ?

**Comment by slonv23** [comment]
> So you meant to say, after enabling hermes engine this crash got solved ?

For me no.

**Comment by jimmyceroneii** [comment]
Just as an fyi, the following issue in React Native has many more solutions for the same problem: https://github.com/facebook/react-native/issues/23764

**Comment by seleziomar** [comment]
solution? I have same problem

**Comment by snehalm-iprogrammer** [comment]
I am facing same issue. any solution?

**Comment by seleziomar** [comment]
I chose to use the apk, I couldn't solve the bundle problem

**Comment by VittoriDavide** [comment]
I am having this error with 0.64 version using hermes and creating app bundle

**Comment by aleppos** [comment]
I am getting the same issue on 0.64

![image](https://user-images.githubusercontent.com/3524824/114391204-93e60d00-9b6d-11eb-9b46-fa4ba1fa9b15.png)

**Comment by maxpill** [comment]
Getting the same issue on 0.64.0

<img width="1156" alt="Screenshot 2021-04-29 at 14 33 27" src="https://user-images.githubusercontent.com/43760021/116551113-e0647300-a8f7-11eb-80bb-4f517bf50c27.png">

**Comment by Andriiklymiuk** [comment]
Is someone found how to solve it?

**Comment by ahtokca** [comment]
Why the issue is closed if there are so many people experience it?

**Comment by aleppos** [comment]
werid, still having the same issue.

**Comment by workpebojot** [comment]
It is so weird that this issue is closed. I think they need to reopen it.

**Comment by trickeyd** [comment]
I having this too - it's causing so many android crashes on prod! 😭

**Comment by vish2595** [comment]
I have this too - it's causing so many androids crashes on prod! 😭

**Comment by omarkhaled11** [comment]
same here, still happening with .aab builds

**Comment by roots-ai** [comment]
Any updates?
