### ISSUE TITLE
Xcode can't archive project, but build without any problems: "library not found for -lDoubleConversion"

### ISSUE THREAD

**Issue by rnnyrk** [facebook/react-native#25788]
Hi there,

I'm stuck for quite some time now. I can't seem to _Archive_ my project via Xcode. When I do I get the following errors:
<img width="843" alt="Screenshot 2019-07-23 at 16 56 13" src="https://user-images.githubusercontent.com/4519142/61723830-106b0380-ad6d-11e9-82e7-fd8f23d8c658.png">

The strange thing is that running a _Build_ of the project doesn't give any errors or problems. 
I've already tried almost everything I can find on the internet, but like I said; I'm stuck. :(

I'm using react native with a Podfile which looks as following:

```
platform :ios, '11.0'

target 'Project' do
  pod 'React', :path => '../node_modules/react-native/'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      targets_to_ignore = %w(React yoga)

      if targets_to_ignore.include? target.name
        target.remove_from_project
      end
    end
  end

  target 'ProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
``` 

And this are the linked libraries via Xcode:
<img width="532" alt="Screenshot 2019-07-23 at 17 28 32" src="https://user-images.githubusercontent.com/4519142/61725035-588b2580-ad6f-11e9-8e33-23ee8f57d2b2.png">

The problem seems to be there since I've added the Podfile. I didn't archive for a while, but before I used the Podfile and all Libraries where linked via Xcode there was no problem archiving (but then I experienced issues with adding custom libraries). 

**React Native version:**
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 51.95 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.11.0 - ~/.nvm/versions/node/v10.11.0/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.11.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 26, 28, 29
        Build Tools: 28.0.3, 29.0.0
        System Images: android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.9 => 0.59.9
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Steps To Reproduce

1. `cd ios` & `pod clean` & `pod install`
2. open `.xcworkspace`
3. Select TEST scheme (with `react-native-scheme-manager`)
4. Clean build folder with `cmd + shift + k`
5. Run project on iPhone 8, connected device (no errors)
6. Archive project (error as above)

Furthermore I've also tried different solutions like deleting all libraries via Xcode "Linked Framework and Libraries" and manually adding them via Pods like in this issue: https://github.com/facebook/react-native/issues/20492

Because it is only on Archiving I'm thinking it has something to do with minifying. Is this even possible? Or any other suggestions? Thanks in advance for the help!

**Comment by jose-verissimo** [comment]
I have the same issue, I was using version 0.57.0, and after upgrading to version 0.60.4, I get this problem "library not found for -lDoubleConversion".

Already wasted 2 days trying to solve it, building an app from scratch results in the same exact issue... Any ideas?

**Comment by rnnyrk** [comment]
My project was being build by using Cocoapods 1.7.3. The issue is resolved by upgrading to 1.7.5!

**Comment by jose-verissimo** [comment]
My solution was to remove the DoubleConversion library that was being added from node_modules and instead use Cocoapods if anyone wondering. 

DM for more details.

**Comment by gunnartorfis** [comment]
I had tried literally everything suggested by the awesome community. I had been emailing with @jose-verissimo and he was extremely helpful.

The solution for me was to create an empty Swift file through Xcode and let Xcode create a Bridging-header.h file. The key was to **not delete** the Swift file after Xcode creating the bridging header file.
