### ISSUE TITLE
How to show a text as mandatory field in react-native-text without touchable opacity

### ISSUE THREAD

**Issue by nihp** [facebook/react-native#25781]
I need to show an error message while clicking on the Save button if the fields are not filled. Need to change the Header title to another title(mandatory). Refer the attached image. How to change this. I have used Text and TextInput component to add this field.

![AwesomeScreenshot-Screenshot-2019-07-23-at-11-32-57-AM-2019-07-23-11-07-54](https://user-images.githubusercontent.com/36992338/61705933-7901b280-ad64-11e9-8847-81beaada5ef3.png)

After click on save I need to change the title of the field

**Comment by nihp** [comment]
I am using react-native Text component to show the Text Name

Here I need to show the text as mandatory after a click on the Save button. If the user not enters the name and click on the Save then I need to show the Mandatory text as red color.

How can I change this?

**Comment by dulmandakh** [comment]
I think that it's best to show indicator that a field is mandatory, instead of trial and error.

I find that it's not a React Native issue, but your implementation detail, so closing.
