### ISSUE TITLE
Button cannot be clicked for SectionList on modal

### ISSUE THREAD

**Issue by Amos729** [facebook/react-native#25780]
### Codes

```
import React, {Component} from 'react';
import {
    View,
    Modal,
    TouchableOpacity,
    Text,
    StyleSheet,
    SectionList
} from 'react-native';
import PropTypes from 'prop-types';

export default class TestModal extends Component {

    static propTypes = {
        visible: PropTypes.bool.isRequired
    };

    static defaultProps = {
        visible: false
    };

    renderItem = ({item, index, section}) => {
        return (<TouchableOpacity
            onPress={() => console.warn('click')}  // Here. Cannot be triggered when clicking
        >
            <Text style={{color: 'red', margin: 10, backgroundColor: 'blue'}}> {section.title + " " + index}</Text>
        </TouchableOpacity>);
    };

    render() {
        const {visible} = this.props;
        let data = [];
        let obj = {
            title: 'First month'
        };
        let temArr = [];
        for (let i = 0; i < 30; i++) {
            temArr.push({index: i})
        }
        obj.data = temArr;
        data.push(obj);
        return (
            <View style={styles.container}>
                <Modal
                    presentationStyle={'overFullScreen'}
                    transparent={false}
                    visible={visible}
                    animationType={'slide'}
                    onRequestClose={() => {
                    }}
                >
                    <View style={styles.cover}>
                        <SectionList
                            sections={data}
                            renderItem={this.renderItem}
                            keyExtractor={(item, index) => index.toString()}
                        />
                    </View>
                </Modal>
            </View>
        );
    }
}

const styles = StyleSheet.create({
    container: {
        position: 'absolute'
    },
    cover: {
        width: __SCREEN_WIDTH__,
        height: __SCREEN_HEIGHT__,
        backgroundColor: Colors.white
    }
});
```

### React Native version:

```
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (4) x64 Intel(R) Core(TM) i3-8100B CPU @ 3.60GHz
      Memory: 60.43 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.5.0 - /usr/local/bin/node
      Yarn: 1.17.3 - ~/.yarn/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 26, 27, 28
        Build Tools: 23.0.1, 26.0.1, 27.0.3, 28.0.2, 28.0.3
        System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.9 => 0.59.9
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-update-cli: 0.1.0
```

### Steps To Reproduce

1. Present the modal, click the button item on SectionList
2. 

- Expected behavior

**Click the button item and console warning**

- In fact, the button item doesn't respond until scrolling to the bottom of SectionList.

### Screenshot（gif）

![gif](https://user-images.githubusercontent.com/22851821/61695459-190c0b80-ad66-11e9-927d-f0f13def3933.gif)

Anybody did try that? Or Do I miss something?  

I tried many times but all failed. Thanks for help.

**Comment by Amos729** [comment]
> It looks like you are using an older version of React Native. Please update to the [latest release, v0.60](https://github.com/facebook/react-native/releases/tag/v0.60.4) and verify if the issue still exists.
> 
> The "Resolution: Old Version" label will be removed automatically once you edit your original post with the results of running `react-native info` on a project using the latest release.

Okay. Thanks for quick reply. I'll have a try.

**Comment by shtengel** [comment]
i have the same issues on RN 0.59.10 , onPress events are not fired inside a Modal..
tried all the Touchable variants..
bug caused after upgrading from 0.51 to 0.59

**Comment by fabriziobertoglio1987** [comment]
I am experiencing the same issue on 0.59

**Comment by lydonchandra** [comment]
Got same issue on 0.59, workaround is to inline renderItem (instead of calling separate function)

eg. 

`<SectionList
                  sections={this.state.secListData}
                  keyExtractor={ (item, index) => item + index }
                  // calling <Item> causes onPress not working
                  // renderItem={ ({item}) => <Item title={item}/> }
                  renderItem={ ({item}) => (
                      <View style={stylesBooksList.item}>
                          <TouchableOpacity onPress={(ev) => {
                              Alert.alert(item);
                          }}>
                              <Text style={stylesBooksList.title}>{item}</Text>
                          </TouchableOpacity>
                      </View>
                  )}
                  renderSectionHeader={
                  ( {section: {title}} ) => (
                      <Text style={stylesBooksList.header}>
                          {title}
                      </Text>
                  )}
              />`
