### ISSUE TITLE
Crash when calling a @ReactMethod with 3 Callback parameters

### ISSUE THREAD

**Issue by dmaksimovic** [facebook/react-native#25784]
I have a function with the following signature in Java:
 `
    @ReactMethod
    public void showPlacement(String placementName, Callback onError, Callback onShown, Callback onDismissed) { /* ... */ }
`

When I run it from within JavaScript, it causes a crash with the following message:

> com.facebook.jni.CppException: JS Functions are not convertible to dynamic

**When I delete the 3rd callback parameter (Callback onDismissed), the crash disappears and the breakpoint is hit inside the function, which can then run normally.**

React Native version:
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 446.24 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.10.0 - /usr/local/bin/node
      Yarn: 1.17.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.2 => 16.8.2
      react-native: 0.59.9 => 0.59.9
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-create-bridge: 2.0.1
      react-native-create-library: 3.1.2
      react-native: 0.59.9

## Steps To Reproduce

1. See below the link to the react-native-tapjoy-indi package on GitLab. It is a fairly trivial wrapper around the Tapjoy SDK at an early stage, and you can see the function showPlacement.
2. Add the library to any React Native project and run ReactNativeTapjoyIndo.showPlacement
3. A crash happens before even entering the function

Describe what you expected to happen:
I expect to be able to run a function and hit a breakpoint in debug mode. All other functions of this module are runnable, except for this one with 3 callback params.

Snack, code example, screenshot, or link to a repository:

https://gitlab.com/coldevel/react-native-tapjoy-indi (commit 45a12f46eb78630c)

or install directly from:

https://www.npmjs.com/package/react-native-tapjoy-indi @ 1.0.13

**Comment by nicol-ograve** [comment]
It happens even in the latest version (0.60.5)

**Comment by rodperottoni** [comment]
I'm getting a lot of these errors on RN 0.59.10. What's weird about is that this error is defined inside of this class in the Hermes project: [JSIDynamic.cpp](https://github.com/facebook/hermes/blob/master/API/jsi/jsi/JSIDynamic.cpp). As you may guess, I'm not using Hermes at all.
Getting around ~70 crashes per week on a >100k active users app.

**Comment by saghul** [comment]
Same here, can we please get it reopened?

**Comment by dmaksimovic** [comment]
I open a ticket, provide all tech info and give an exact way how to reproduce it, and they kick me around saying I should try it on the new versions. For a responsible team which loves their project and wants to make it better it's 5 minutes to try it out with all given instructions.

**Comment by zidniryi** [comment]
Yes, same here again. LOL

**Comment by SamCosta1** [comment]
I'm also seeing this issue on version 0.63.0

**Comment by shukerullah** [comment]
Crashing on `v0.62.0`
