### ISSUE TITLE
'openURL:options:completionHandler:' is unavailable: not available on iOS (App Extension)

### ISSUE THREAD

**Issue by mahmoudfelfel** [facebook/react-native#25792]
I'm getting this error whenever i try to build the app, it was working fine on 0.57.3, but after upgrading to the latest version (0.60.4), I started getting this error.
![image](https://user-images.githubusercontent.com/3989750/61743959-43ca8400-ada7-11e9-8117-dadaf9f60338.png)

This is my podfile:
```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Analytics'
pod 'Firebase/DynamicLinks'
pod 'Firebase/RemoteConfig'
pod 'Firebase/Storage'
pod 'Firebase/Performance'
pod 'Firebase/Messaging'
pod 'Fabric', '~> 1.7.5'
pod 'Crashlytics', '~> 3.10.1'
pod 'TwitterKit'
pod 'TwitterCore', '~> 3.0.2'
# pod 'FBSDKCoreKit'
pod 'GoogleSignIn'

target 'myapp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mayapp
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/React'
  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
  pod 'React-fishhook', :path => '../node_modules/react-native/Libraries/fishhook'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'

  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  platform :ios, '9.0'
  # pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'


  pod 'TextToSpeech', :path => '../node_modules/react-native-tts'

  # pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'Flurry-iOS-SDK/FlurrySDK'
  pod 'react-native-mixpanel', :path => '../node_modules/react-native-mixpanel'
  pod 'Mixpanel'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  pod 'SentryReactNative', :path => '../node_modules/react-native-sentry'

  pod 'react-native-intercom', :path => '../node_modules/react-native-intercom'

end

target 'MyShareExt' do
  platform :ios, '9.0'
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'react-native-mixpanel', :path => '../node_modules/react-native-mixpanel'
  pod 'Mixpanel'
  inherit! :search_paths
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "yoga"
      target.remove_from_project
    end
  end

  installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
    configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
  end
end


```

React Native version:
```
System:
    OS: macOS 10.14
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Memory: 44.29 MB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.15.0 - /usr/local/bin/node
    Yarn: 1.15.0-20190126.1635 - ~/.yarn/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    Android SDK:
      API Levels: 22, 23, 24, 25, 26, 27, 28
      Build Tools: 23.0.3, 28.0.2
  IDEs:
    Android Studio: 3.1 AI-173.4907809
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.4 => 0.60.4
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
```

## Steps To Reproduce

1. Add a share extension to the app.
2. build.

**Comment by mahmoudfelfel** [comment]
Is there any update here? I want to upgrade to the latest version but not able to do so due to this issue, can anyone help with that please? any workaround?

**Comment by sebastian-sanchez-variv** [comment]
I am facing the same issue... any fix yet?

**Comment by diegolmello** [comment]
`RCTSharedApplication` is disabled when in App Extension:
https://github.com/facebook/react-native/blob/master/React/Base/RCTUtils.m#L486

I've tried to remove Linking from Pods, but I had no luck.
Here's my current Podfile.

```rb
platform :ios, '10.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

target 'RocketChatRN' do
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/React'
  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
  pod 'React-fishhook', :path => '../node_modules/react-native/Libraries/fishhook'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  use_native_modules!
  use_unimodules!
end

target 'ShareRocketChatRN' do
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/React'
  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
  pod 'React-fishhook', :path => '../node_modules/react-native/Libraries/fishhook'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
#  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
end
```

**Comment by sebastian-sanchez-variv** [comment]
@diegolmello are you getting any warning after running pod install? I was getting following warning:

`[!] The `<project name> [Release]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `<.xcconfig location>'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.` 

Solved it by adding:

`post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = '$(inherited)'
        end
    end
  end`

to my podfile just before

`use_native_modules!`

**Comment by djorkaeffalexandre** [comment]
Hi!
You are need to add `use_native_modules!` to both targets (App & Share Extension) and add it to your podfile:
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
    end
  end
end
```

**Comment by jvandenaardweg** [comment]
> `RCTSharedApplication` is disabled when in App Extension:
> https://github.com/facebook/react-native/blob/master/React/Base/RCTUtils.m#L486
> 
> I've tried to remove Linking from Pods, but I had no luck.
> Here's my current Podfile.
> 
> ```ruby
> platform :ios, '10.0'
> require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
> require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
> 
> target 'RocketChatRN' do
>   pod 'React', :path => '../node_modules/react-native/'
>   pod 'React-Core', :path => '../node_modules/react-native/React'
>   pod 'React-DevSupport', :path => '../node_modules/react-native/React'
>   pod 'React-fishhook', :path => '../node_modules/react-native/Libraries/fishhook'
>   pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
>   pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
>   pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
>   pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
>   pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
>   pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
>   pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
>   pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
>   pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
>   pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'
> 
>   pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
>   pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
>   pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
>   pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
>   pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
> 
>   pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
>   pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
>   pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
> 
>   use_native_modules!
>   use_unimodules!
> end
> 
> target 'ShareRocketChatRN' do
>   pod 'React', :path => '../node_modules/react-native/'
>   pod 'React-Core', :path => '../node_modules/react-native/React'
>   pod 'React-DevSupport', :path => '../node_modules/react-native/React'
>   pod 'React-fishhook', :path => '../node_modules/react-native/Libraries/fishhook'
>   pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
>   pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
>   pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
>   pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
> #  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
>   pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
>   pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
>   pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
>   pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
>   pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'
> 
>   pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
>   pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
>   pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
>   pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
>   pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
> 
>   pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
>   pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
>   pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
> end
> ```

Below should also work with share extensions. So you don't have to copy/paste  the react pods twice:

```
target 'RocketChatRN' do
  // react pods

  use_native_modules!

  target 'ShareRocketChatRN' do
    use_native_modules!
    inherit! :complete
  end
end

**Comment by Jnlbr** [comment]
> Hi @mahmoudfelfel and @sebastian-sanchez-variv !
> You need to add `use_native_modules!` to both targets (App & Share Extension) and add it to your podfile:
> 
> ```
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     target.build_configurations.each do |config|
>       config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
>     end
>   end
> end
> ```

Can you explain this? Plsss

**Comment by ericlewis** [comment]
One workaround is to set this flag to false in your extension's build settings.

<img width="508" alt="Screen Shot 2019-10-18 at 7 21 30 PM" src="https://user-images.githubusercontent.com/674503/67133801-85b76a80-f1dc-11e9-8e16-2373ba669773.png">

**Comment by djorkaeffalexandre** [comment]
@Jnlbr this code set `Require Only App-Extension-Safe API` to `false` on all Pod dependencies.

**Comment by batai278** [comment]
@djorkaeffalexandre  It does not work for me. I am trying to use OneSignalNotificationServiceExtension set up according to manual https://documentation.onesignal.com/docs/ios-sdk-setup.
When I use your solution I get another pack of errors (200+) about Mach-O Linker
<img width="1436" alt="Screenshot 2019-10-30 at 13 24 45" src="https://user-images.githubusercontent.com/9902697/67854321-c25a5e80-fb18-11e9-9633-59cdc50c04d3.png">

**Comment by fancydevpro** [comment]
@batai278 I got same errors when I used react-native-share-extension. Did you solved it?
I'm using react-native 0.61.2.
