### ISSUE TITLE
the development server returned response error code 500,  Duplicated files or mocks. Please check the console for more info

### ISSUE THREAD

**Issue by lutianxiong** [facebook/react-native#25795]
Hey guys, I have a problem right now.

I get an error after using the command react-native run-android:

![QQ截图20190724100947](https://user-images.githubusercontent.com/42662202/61759489-30e19f00-adfb-11e9-9e74-2894d03cc4bd.png)

![QQ截图20190724101236](https://user-images.githubusercontent.com/42662202/61759680-9afa4400-adfb-11e9-8e20-330a61d5bc94.png)
![QQ截图20190724101244](https://user-images.githubusercontent.com/42662202/61759681-9afa4400-adfb-11e9-801d-416b42ed7602.png)

please help me...

**Comment by OsvaldoCabral** [comment]
I tried this and it worked
https://github.com/razorpay/react-native-razorpay/issues/129#issuecomment-428579390

**Comment by doituyetdep** [comment]
I deleted template folder in path [root]/node_modules/react-native/template and run: react-native run-android again. It will success.
