### ISSUE TITLE
react-native 0.59.10 in Back off at Android 4.1.2

### ISSUE THREAD

**Issue by GoodCloudRepair** [facebook/react-native#25806]
React Native version:0.59.10

## Steps To Reproduce

1.

Describe what you expected to happen:

Snack, code example, screenshot, or link to a repository:

I pulled the react-native version 0.59.10
Executing react-native run-android is OK
But Android 4.1.2 will crash
Flash back.

![image](https://user-images.githubusercontent.com/30991526/61787576-a45acf00-ae42-11e9-8dac-82fcc375950b.png)
This is the case in the  Android studio logcat log.

![image](https://user-images.githubusercontent.com/30991526/61787653-d3714080-ae42-11e9-8ccb-87a84eb6be94.png)

2.
I tried all versions larger than 0.58.6 and this happened.

React Native version: 0.59.10

**Comment by GoodCloudRepair** [comment]
Help!

**Comment by GoodCloudRepair** [comment]
Is anyone here?

**Comment by kbrandwijk** [comment]
I was actually surprised to read that RN still supposedly supports API 16+, even though Google Play has dropped everything lower than 26 (28 a week from now). Curious to see how long that will be feasible...

**Comment by GoodCloudRepair** [comment]
Are there big guys?

**Comment by j-wang** [comment]
See this issue here:

https://github.com/facebook/react-native/issues/25494
