### ISSUE TITLE
IOS library not found for -lDoubleConversion 

### ISSUE THREAD

**Issue by KiranreddySrDev** [facebook/react-native#25804]
"react": "16.8.6",
   react-native: 0.60.4,
 "react-native-webview": "^5.12.1"

## Steps To Reproduce

1. I have created a new project and it has only one package that is react-native-webview
2. When I build in the IOS emulator then I got some with the Xcode.
3. I got to link the webview also even it's not working I have tried many time still got the same issue

<img width="1010" alt="Screenshot 2019-07-24 at 3 31 53 PM" src="https://user-images.githubusercontent.com/40351491/61784993-6b156580-ae28-11e9-95a9-891b76522442.png">

**Comment by getinfyKiranreddy** [comment]
Yes. I mentioned what I got just error with IOS but Android is working fine. Why I don't know.
My Xcode 10.2.
Just let me what Can I do?

**Comment by Dellybro** [comment]
So i was having this issue too. If you are updating from 0.59, ensure that you have deleted your Pods and reinstalled. 

cd ios
rm -rf Pods
pod install

**Comment by gunnartorfis** [comment]
I had tried literally everything suggested by the awesome community. 

The solution for me was to create an empty Swift file through Xcode and let Xcode create a Bridging-header.h file. The key was to not delete the Swift file after Xcode creating the bridging header file.

**Comment by paruckerr** [comment]
Same issue here, react-native run-ios works fine, when I try on simulator or device => ```Library not found for -lDoubleConversion``` =/

**Comment by paruckerr** [comment]
the problem was open and build project in wrong place...

```=> open ios/{Project}.xcodeproj``` instead ```=> open ios/{Project}.xcworkspace```

**Comment by getinfyKiranreddy** [comment]
I did the same thing but still, I am getting the same error. I have tried with 0.59 again then it was working fine.
 If I create new a project run on Xcode I was getting the same iBundile error.

**Comment by slavikdenis** [comment]
Can you try this please? https://github.com/facebook/react-native/issues/25820#issuecomment-515742426

**Comment by pmadruga** [comment]
Have the same problem, tried https://github.com/facebook/react-native/issues/25820#issuecomment-515742426 but still nothing.

**Comment by vvni** [comment]
I also encountered this problem.

**Comment by jimhill** [comment]
This is a problem that I have been trying to work out all day too.

**Comment by pmadruga** [comment]
I had this problem and manage to solve it somehow, but ran into a different problem and forgot how I solve this one in the first place. So please apologize if this doesn't work for you. To give a bit of context, I was coming from version 0.59 and was trying to upgrade to 0.60.4

I'll leave first what I think it's the main cause of the problem followed by other steps that hopefully will help you.

**What I think the problem is**
When upgrading, I had a lot of leftovers from previous RN versions, regarding linked binaries. But because RN 0.60 handles everything with pods, now my linked binaries look link this instead:

![Screenshot 2019-08-09 at 23 01 45](https://user-images.githubusercontent.com/3617636/62808905-c10d2d00-baf9-11e9-8ce2-0440b8ff3814.png)

** Steps I took to overcome this problem **
Again, this is if my memory is correct. And please branch out before you try this so that you don't screw your existing setup.

1. Check the differences from versions. 
I've used https://react-native-community.github.io/rn-diff-purge/ to check and implement any changes between versions

2. Cleaned the linked libraries

3. Ran
```
echo 'remove cache'
rm -rf $TMPDIR/react-*
rm -rf $TMPDIR/metro-*
watchman watch-del-all
npm cache verify

# echo 'removing derived data'
rm -rf ~/Library/Developer/Xcode/DerivedData

echo 'removing pods and node modules'
cd ios
pod deintegrate
pod cache clean --all
cd ../

rm -rf ios/Pods 
rm -rf ios/Podfile.lock
rm -rf ios/build
rm -rf node_modules
rm -rf package-lock.json

echo 'cocoapods install'
gem install cocoapods

echo 'brew'
brew update && brew upgrade

echo 'installing node modules'
npm i 

# mostly for any legacy stuff
echo 'react-native link'
react-native link

echo 'installing pods'
cd ios 
pod update
pod install

```

Hope it helps.

**Comment by jimhill** [comment]
Thanks @pmadruga but frustratingly that didn't work. For reference, it's only when archiving that the issue occurs for me.

**Comment by jimhill** [comment]
The issue in more detail is that if I look in `MYBUILD/BuildProductsPath/Release-iphoneos/` the files in there are like `libReact.a`, `libdouble-conversion.a` etc. But the build failure is looking for the 
 target support paths (I assume) like `MYBUILD/BuildProductsPath/Release-iphoneos/DoubleConversion`, `MYBUILD/BuildProductsPath/Release-iphoneos/Folly`

**Comment by raghavyadavm** [comment]
> the problem was open and build project in wrong place...
> 
> `=> open ios/{Project}.xcodeproj` instead `=> open ios/{Project}.xcworkspace`

use this command to open the workspace
`cd ios && xed .`

**Comment by jimhill** [comment]
Just to point out that my issue was not related to forgetting to open the workspace. Before upgrading I was already using cocoapods. I now have a fully working version so will diff the configs to see what I can uncover.

**Comment by webMasterMrBin** [comment]
still not found when pod install
RN: 0.60.0

**Comment by diamont1001** [comment]
I got the same issue.

`react-native run-ios` and `react-native run-android`  works fine, 
but got error in Xcode => `library not found for -lDoubleConversion`

Any solution here?

**Comment by diamont1001** [comment]
> the problem was open and build project in wrong place...
> 
> `=> open ios/{Project}.xcodeproj` instead `=> open ios/{Project}.xcworkspace`

It works.

Step 1: quit Xcode completely
Step 2: open `ios/{Project}.xcworkspace` (PS: not `ios/{Project}.xcodeproj`)

Cheers!

**Comment by geekazoid-at** [comment]
> > the problem was open and build project in wrong place...
> > `=> open ios/{Project}.xcodeproj` instead `=> open ios/{Project}.xcworkspace`
> 
> It works.
> 
> Step 1: quit Xcode completely
> Step 2: open `ios/{Project}.xcworkspace` (PS: not `ios/{Project}.xcodeproj`)
> 
> Cheers!

Can you do a release build? Mine fails as soon as I use a release scheme. 😞 Debug works fine for me too...

**Comment by diamont1001** [comment]
@geekazoid-at 

Yes, it works for me at debug/release/archive mode.

**Comment by ldco2016** [comment]
@paruckerr , that worked for me, but then I ran **Archive** and that succeeded, but no Organizer opened for me to **export** to generate `.ipa`.

**Comment by Ebeldev** [comment]
I do get this bug of -lDoubleConversion library not found. 

react-native-cli: 2.0.1
react-native: 0.60.5

When I do a clean react-native init, then try to build it I do get this error.

**Comment by diamont1001** [comment]
@Ebeldev Make sure the project file you open is xxx. xcworkspace (not xxx. xcodeproj)

**Comment by Ebeldev** [comment]
@diamont1001  If I build it with xcworkspace: I get this error : error: Build input file cannot be found: '/Users/etiennebelanger/Documents/apps/react-native-apps/InfosLaurentides/node_modules/react-native/ReactCommon/yoga/yoga/YGMarker.cpp'

**Comment by Ebeldev** [comment]
@diamont1001 I was able to build a new project using npx react-native init and then build it with Xcode. 

Using npx instead of npm does it make a difference?

**Comment by realripley00** [comment]
> So when archiving, the error is due to not finding the folders (which appear to be the target support folders) e.g.
> 
> `MYBUILD/BuildProductsPath/Release-iphoneos/DoubleConversion`
> `MYBUILD/BuildProductsPath/Release-iphoneos/Folly` etc
> 
> And when I go to look in the `MYBUILD/BuildProductsPath/Release-iphoneos` directory there are only files such as:
> 
> `libReact.a`,
> `libdouble-conversion.a` etc.
> 
> --
> 
> Update - the fastest fix? to simply rebuild from scratch. Worked first time.

@jimhill do you mean the fastest way was to start a new react native project and pull all the files into a fresh install? I've been stuck on this issue for days now and I'm running out of ideas.

**Comment by jimhill** [comment]
@realripley00 yep. I just ran a fresh install and migrated everything. It actually didn’t take very long in the end. I’d spent days too trying to fix it.

**Comment by craftmusic** [comment]
on 0.60 experience the same errors with Library not found / directory not found, 
I can't launch my app because of this 

Release build works but Building Archive is failing

**Comment by realripley00** [comment]
> on 0.60 I'm experiencing the same errors with Library not found / directory not found,
> I can't launch my app because of this
> 
> Release build works but Building Archive is failing

@craftmusic I wound up following @jimhill 's advice and starting a fresh new react native app and then moving everything over. I made sure to use all the newest versions of every package. It's kind of tedious, but it's worth it if you consider that our team had spent probably twenty hours collectively over a few days trying to figure out this bug. Starting a new project and pulling in all the files took maybe 3 or 4 hours total. I wish we'd have decided to that sooner.

**Comment by craftmusic** [comment]
I created a fresh react native app 0.61.2 and moved my code over but i'm still receiving the same errors of Library not found / directories not found.

Xcode Debug builds and react-native run-ios work fine but building release still doesn't work. I've spent a ridiculous amount of hours on this.

**Comment by craftmusic** [comment]
@realripley00 @jimhill @ldco2016 @Ebeldev @diamont1001 @geekazoid-at

Honestly Facebook should provide some kind of human support, I know it’s “open source” but they still create the platform and manage it. Anyways, I started a petition about this just now, because it’s a much larger issue. Our app launch has been delayed by months due to issues with React Native. I wish we would have built everything in Native but we no longer have the funds Or the time to rebuild. Very frustrating.

Here’s the petition if you would please sign and pass it along: http://chng.it/dJJmXtJ6bz

**Comment by IvanCaceres** [comment]
I also can't make it past this issue, I keep getting Directory not found errors and i've tried everything / clearing node_modules + pods and caches + xcode derived data, build folders etc

Have tried everything now including starting multiple fresh apps for different react native versions 0.59, 0.60, 0.61 and cannot build Xcode release/archive

Development debug builds work fine.

`
Users/ivancaceres/Library/Developer/Xcode/DerivedData/{project name}/Build/Products/Release-iphonesimulator/DoubleConversion'



```

**Comment by nathantaal** [comment]
Did anyone find a solution yet? Regenerating the work space with cocoa pods obviously doesn't work. This is an blocking issue for releasing apps.

**Comment by fallen158** [comment]
https://stackoverflow.com/questions/50562596/library-not-found-for-ldoubleconversion/55776414#55776414

**Comment by nathantaal** [comment]
> https://stackoverflow.com/questions/50562596/library-not-found-for-ldoubleconversion/55776414#55776414

Does not work in my case

**Comment by IvanCaceres** [comment]
@nathantaal make sure you're Xcode build settings look alright:

- Link Binary With Libraries:
should have your libPods-*projectName*.a
- Target Dependencies should have React listed
<img width="1138" alt="Screen Shot 2019-11-07 at 6 05 43 AM" src="https://user-images.githubusercontent.com/3813655/68384010-b546fc00-0124-11ea-9ccb-e4af20d68b2c.png">
- And finally make sure your Library search paths look right, you should be able to see the DoubleConversion library name in the paths:
![image](https://user-images.githubusercontent.com/3813655/68384167-048d2c80-0125-11ea-880c-ac0e03df9745.png)

**Comment by realripley00** [comment]
> > https://stackoverflow.com/questions/50562596/library-not-found-for-ldoubleconversion/55776414#55776414
> 
> Does not work in my case



> Did anyone find a solution yet? Regenerating the work space with cocoa pods obviously doesn't work. This is an blocking issue for releasing apps.

This is a really frustrating bug, and I don't think the React team is interested in fixing on past versions of react. The only way that I've consistently been able to resolve it is to start a complete new project using the latest version of RN and as new packages as you can otherwise and then import all the files from the old project. It's a bit hacky, but after spending the better part of a week trying to resolve it, the four or five hours that it took to rebuild the project using the old files was worth it. It seems to me once this issue comes up on a project, it's "burned." Your only option is to restart it.

**Comment by henrymoulton** [comment]
Experiencing this issue too when initialising adding Cocoapods to an old React Native project, 0.59.10.

**Comment by henrymoulton** [comment]
@jimhill sounds like you had a good experience migrating everything.

**Comment by buddhikajay** [comment]
Hi All,

I'm also facing the same issue. Even if I create a new RN project from scratch, it cannot be archived. Development build works fine. Any proper solution ?

**Comment by buddhikajay** [comment]
This worked for me

```bash
rm -rf node_modules
cd ios
pod deintegrate
pod install
pod update
```

**Comment by nathantaal** [comment]
> @nathantaal make sure your Xcode build settings look alright:
> 
> * Link Binary With Libraries:
>   should have your libPods-_projectName_.a
> * Target Dependencies should have React listed
> 
> <img alt="Screen Shot 2019-11-07 at 6 05 43 AM" width="1138" src="https://user-images.githubusercontent.com/3813655/68384010-b546fc00-0124-11ea-9ccb-e4af20d68b2c.png">
> 
> - And finally make sure your Library search paths look right, you should be able to see the DoubleConversion library name in the paths:
> <img alt="Screen Shot 2019-11-07 at 6 07 49 AM" width="1148" src="https://user-images.githubusercontent.com/3813655/68384212-225a9180-0125-11ea-9f24-78bbb2277720.png">

You might be on to something here, but I wonder how to add React as a dependency since the .xworkspace file is removed since react-native 0.60?
+

**Comment by nathantaal** [comment]
For everyone the solution is different. For me, none of all worked. Because of React 0.60, React shouldn't be a Target dependency. The only thing I had to do was opening the xcodeworkspace and setting the recommended settings to my pods. Now I can archive apps like I always could.

**Comment by spohner** [comment]
Had this exact error when archiving. Degrading the ios target platform in the Podfile from 11.0 to 9.0 solved it for us. Had raised this previous when including a third-party library which did not support version 9.0. Remember to run 'pod deintegrate' and remove Podfile.lock before 'pod install' after changing this parameter. Took a long time to figure this out.

**Comment by emmanuele-villa** [comment]
I also have this issue with react native 0.61, but only when building from command line..
Opening the xcodeworkspace and building or archiving the app works good, but calling xcodebuild form the terminal result in the same error

**Comment by JakeHadley** [comment]
I'm getting the same as @emmanuele-villa. I get an error `<projectName>Tests.m:11:9: fatal error: 'React/RCTLog.h' file not found`, and other times I get this library not found error. I tried adding React to the product -> manage schemes -> project area, but react is not listed.

**Comment by tapz** [comment]
I'm getting this:

ld: library not found for -lFolly

**Comment by tapz** [comment]
The problem is that some of the pods are not built and have no files in DerivedData.

What is different in these pods compared to the others?
Folly
React-Core
React-cxxreact
React-jsi
React-jsiexecutor

I created a new RN app and it does not have this build error.

**Comment by tapz** [comment]
The newly created RN project includes the libraries/frameworks differently. For example the JavaScriptCore framework. It only has it under the Frameworks folder not in Link Binary With Libraries. This is really confusing, as I have used to adding libraries to the Build phases and they are automatically added to the frameworks. How does RN create the initial project to end up to this kind of project structure and how is it possible that this even works when the JavaScriptCore is not in the linked libraries?

<img width="878" alt="Screenshot 2019-12-18 at 18 58 04" src="https://user-images.githubusercontent.com/11726387/71106672-6c28a400-21c8-11ea-9fb0-29eb61326266.png">
<img width="240" alt="Screenshot 2019-12-18 at 18 58 00" src="https://user-images.githubusercontent.com/11726387/71106673-6c28a400-21c8-11ea-8bf3-1db5be32d6e8.png">

**Comment by tapz** [comment]
Fixed the issue by commenting out `use_modular_headers! `and adding `use_frameworks! `This is because my project contains Swift files.

I also removed `HEADER_SEARCH_PATHS` and `LIBRARY_SEARCH_PATHS` lines from the Xcode project file.

**Comment by Billmike** [comment]
I spent the last five days stuck on this, trying out everything suggested on the internet. This is what finally worked for me. (Before proceeding, make sure 
```pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'``` is included in your podfiles
```
1. Delete Podfile.lock
2. cd ios
3. pod deintegrate
4. pod install
5. cd ..
6. rm -rf node_modules && yarn
7. Add use_frameworks! to your Podfile
```
Run react-native-run-ios or Build with Xcode by opening the xcworkspace file in your ios directory. Hope this helps someone!

**Comment by Desintegrator** [comment]
same, none of solutions worked for me

**Comment by betko** [comment]
I had the same problem. When I used the `react-native run-ios` command everything worked fine, but if I passed the `--configuration Release` I received the same error message. After a few hours I realised that the platform version in the Podfile was 11.0 but in the Xcode Project was 9.0. 

After I corrected the version mismatch  everything work fine.

**Comment by redexp** [comment]
My solution was also sync target ios version in Podfile `platform :ios, '11.0'` and in Xcode `General > Deployment Info > Target > iOS > 11.0` after close Xcode and run in cli `cd ios && pod deintegrate && rm Podfile.lock && pod install`

**Comment by Mitdd9707** [comment]
I  get this bug of -lDoubleConversion library not found. 
please help! @react-native-bot 

react-native :- 0.62.2
react:- 16.11.0


<img width="1440" alt="Screenshot 2020-07-27 at 11 37 39 PM" src="https://user-images.githubusercontent.com/64424107/88576272-cc3acf00-d062-11ea-94df-04787a36eb2f.png">

**Comment by ffurkAn** [comment]
By changing platform :ios, '11.0' to '10.0' is worked for me

**Comment by FaisalKhawaj** [comment]
I was facing the same issue while running the project. 
What I was doing is I was running Project.xcodeproj, :P
When i chose workspace , this was  working fine for me .

**Comment by FaisalKhawaj** [comment]
I was facing the same issue while running the project. 
What I was doing is I was running Project.xcodeproj, :P
When i chose workspace , this was  working fine for me .

**Comment by saykharng** [comment]
> I had the same problem. When I used the `react-native run-ios` command everything worked fine, but if I passed the `--configuration Release` I received the same error message. After a few hours I realised that the platform version in the Podfile was 11.0 but in the Xcode Project was 9.0.
> 
> After I corrected the version mismatch everything work fine.

Saved a lot of time for me. Thank you 👍

**Comment by mppvgithub** [comment]
> Have the same problem, tried [#25820 (comment)](https://github.com/facebook/react-native/issues/25820#issuecomment-515742426) but still nothing.
> 
> Also working fine with 0.59.

Have got the solution?
