### ISSUE TITLE
Tap on YellowBox TypeError with Hermes enabled and remote debugger disabled

### ISSUE THREAD

**Issue by nicovak** [facebook/react-native#25801]
React Native version:

```
System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 31.68 MB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.10.0 - ~/.nvm/versions/node/v8.10.0/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 5.6.0 - ~/.nvm/versions/node/v8.10.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28
      Build Tools: 23.0.1, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.3
      System Images: android-16 | Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
      Android NDK: 20.0.5594570
  IDEs:
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.4 => 0.60.4
  npmGlobalPackages:
    eslint-plugin-react-native: 3.6.0
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
    react-native: 0.60.4
```

## Steps To Reproduce

1. Enable **Hermes**.
2. Disable remote debugger.
3. Create a deprecated  warning or trigger a YellowBox, for example with `componentWillMount` inside a component.
4. Click on the YellowBox.

Describe what you expected to happen:

We should have the detail of the YellowBox, actually It trigger an error.
It happens on Android, with **Hermes** enabled only and without `Debug JS Remotely`

Snack, code example, screenshot, or link to a repository:

![Image](https://i.imgur.com/XZ8RARB.jpg)

**Comment by charlesluo2014** [comment]
same as screen

**Comment by AkuSilvenius** [comment]
I have just had this same issue with exact same setup. Trying out 0.60 for the first time with Hermes, have not had this issue with for example with 0.58,  in the same machine, development OS and target OS 🤔

**Comment by vanydeasy** [comment]
Is there any update on this?
