### ISSUE TITLE
Error "Thread 1: signal SIGABRT" after updating to RN 0.60.4

### ISSUE THREAD

**Issue by rnnyrk** [facebook/react-native#25802]
I've just updated my project to React Native 0.60.4, but I can't seem to build my project. I get the error `Thread 1: signal SIGABRT`, which is a general error (according to this post: https://learnappmaking.com/sigabrt-xcode-swift/).

To project builds without error via Xcode. I see the splash screen and then nothing happens and the app breaks. What to do? Can't find anything related to this on the internet. 

React Native version:
System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 278.52 MB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.11.0 - ~/.nvm/versions/node/v10.11.0/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.11.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      API Levels: 23, 26, 28, 29
      Build Tools: 28.0.3, 29.0.0
      System Images: android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.4 => 0.60.4
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Steps To Reproduce
1. Updated my project to `react-native: 0.60.4`
2. Remove all old pod files `cd ios && rm -rf Pods`
3. Install Pods `pod install`
4. Open `Project.xcworkspace`
5. Clean build folder `cmd + shift + k`
6. Run on simulator (iPhone X)

This is my Podfile:
```
platform :ios, '11.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'Project' do
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/React'
  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
  pod 'React-fishhook', :path => '../node_modules/react-native/Libraries/fishhook'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  target 'ProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
end
```

and those are my JS dependencies:
```
  "dependencies": {
    "@babel/polyfill": "7.4.4",
    "@react-native-community/async-storage": "1.5.1",
    "cross-fetch": "3.0.4",
    "prop-types": "15.7.2",
    "qs": "6.7.0",
    "react": "16.8.6",
    "react-native": "0.60.4",
    "react-native-gesture-handler": "1.3.0",
    "react-native-svg": "9.5.1",
    "react-navigation": "3.11.0",
    "react-navigation-redux-helpers": "3.0.2",
    "react-redux": "7.1.0",
    "redux": "4.0.1",
    "redux-devtools-extension": "2.13.8",
    "redux-thunk": "2.3.0",
    "styled-components": "4.3.2"
  },
```

**Comment by kalistara** [comment]
I faced the same issue in the release build.
This is my Podfile:

`platform :ios, '12.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'ProjectApp' do
  # Pods for ProjectApp
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/React'
  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
  pod 'React-fishhook', :path => '../node_modules/react-native/Libraries/fishhook'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'


  target 'ProjectAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-config'
      phase = target.project.new(Xcodeproj::Project::Object::PBXShellScriptBuildPhase)
      phase.shell_script = "cd ../../"\
                           " && RNC_ROOT=./node_modules/react-native-config/"\
                           " && export SYMROOT=$RNC_ROOT/ios/ReactNativeConfig"\
                           " && export BUILD_DIR=$RNC_ROOT/ios/ReactNativeConfig"\
                           " && ruby $RNC_ROOT/ios/ReactNativeConfig/BuildDotenvConfig.ruby"

      target.build_phases << phase
      target.build_phases.move(phase,0)
    end
  end
end
`

**Comment by heyproject** [comment]
I get the same issue on RN 0.60.5

**Comment by eran-pinhas** [comment]
Same here - RN 0.60.5.

Started after I added some native code written in swift

**Comment by eran-pinhas** [comment]
**UPDATE:** 

Issue fixed when specified `s.swift_version = "4.2"` in the podspec of the module I'm writing 😄

**Comment by prabhjodhOYO** [comment]
> **UPDATE:**
> 
> Issue fixed when specified `s.swift_version = "4.2"` in the podspec of the module I'm writing 😄

Hey!

Can you please elaborate how to do this?

**Comment by eran-pinhas** [comment]
https://github.com/eran-pinhas/react-native-bubble-picker/blob/master/RNBubblePicker.podspec

Denote that this is a package and not an app. An app may have different podspec file

**Comment by prabhjodhOYO** [comment]
> https://github.com/eran-pinhas/react-native-bubble-picker/blob/master/RNBubblePicker.podspec
> 
> Denote that this is a package and not an app. An app may have different podspec file

I updated the ".podspec" files the ones used in "podfile" file and still getting the error. Can you help me with debugging the issue? I mean, how can I debug the issue in Xcode?
