### ISSUE TITLE
Responsive Background Images with Static Resources ?

### ISSUE THREAD

**Issue by BerndWessels** [facebook/react-native#2580]
Hi
I can't figure this out, even though it seems a very common use case.

I want a full screen background image in all pages of my app.
This should be from a static resource.
And it should be the best quality for each device display size, iPhone 4 / 5 / 6 / ...
Also a nice to have would be a landscape alternative when the user changes the orientation of the device.

What is the right way of doing this?

Thank you very much
Bernd

**Comment by PhilippKrone** [comment]
I have several static images for that - one for each resolution / orientation. Issue for me was that I have a little bit of text on the image (our URL) and thus scaling did not work for me. Sure one could work with dynamic cropping / scaling, but it was easier for me to create several individual static images in photoshop and add them as static images to the app.

**Comment by ide** [comment]
You can get the device dimensions (in points, not pixels) from `Dimensions.get('window')` and the screen scale with `PixelRatio.get()`. With that info you could either write a handful of `if-else` statements to compute the right `source` and `style` props for your Image, or include that info in your image URL and have the server/CDN send back the appropriately sized image. One thing that's good about the server approach is that it lets you add Android support where there are a ton more device profiles.

**Comment by BerndWessels** [comment]
@PhilippKrone Thanks, yes I want to use static resource images. And I don't mind having multiple images, one for each resolution. But can you please give me an example on how you actually configure and render. I know that we can have static resources with 1x 2x 3x, but I doubt that there is an automatic way of choosing the right picture. Do I need a switch and (require(image!iPhoneXX)) for each device?
Do you have an example or code snipped how you cover different devices and orientation please?
Thank you
Bernd

**Comment by nicklockwood** [comment]
If you use XCAssets, or have an @2x, @3x, etc suffix on your image files then it should select the correct one automatically.

**Comment by nicklockwood** [comment]
A good solution might be to create a component that wraps <Image> and encapsulates the file selection logic. So for example, you could create a naming convention for iPhone 4/5/6 images, and then have your component automatically append the correct suffix to the name before passing it to the underlying <Image>, by looking at the screen size returned by Dimensions.get('window'), e.g.

    <BackgroundImage name="foo"/>

Would map to

    <Image source={{uri: 'foo-iPhone4.png'}}/>

**Comment by BerndWessels** [comment]
@nicklockwood Thank you.
I am actually confused about the 2x 3x in XCAssets and how that relates to (require(!image|...).

Do you think such a component has to be written in ObjectiveC or can be done in JavaScript only?

**Comment by nicklockwood** [comment]
If you say `source={require('image!foo')}` and there is a foo@2x.png and foo@3x.png in your app bundle, it should automarically find and open the correct one for the device. If that isn't working, try `source={{uri: 'foo.png'}}` instead.

The component I described above can be built entirely in JS.

**Comment by BerndWessels** [comment]
@nicklockwood Thank you, I will give it a try.

**Comment by brentvatne** [comment]
@BerndWessels - let me know if you're still stuck and I'll reopen this issue, looks like the question has been answered though :smile:
