### ISSUE TITLE
react native 0.59) https not working

### ISSUE THREAD

**Issue by pyeonjaesik** [facebook/react-native#25815]
http is ok but https is not working in android.
my device is galaxy S9+  and OS is pie.

**Comment by guhungry** [comment]
Can you check server's ssl certificate using https://www.ssllabs.com/ssltest/

**Comment by pyeonjaesik** [comment]
@guhungry which feature can make https networking not to work?
My domain is www.yomencity.com

**Comment by ecreeth** [comment]
You can provide a little more information about the error? Snack, code example, screenshot, or link to a repository

**Comment by guhungry** [comment]
It because of incomplete certificate chain (This server's certificate chain is incomplete. Grade capped to B.)
![Capture](https://user-images.githubusercontent.com/4032276/61921592-d590e780-af87-11e9-8939-2823bcda6766.PNG)

**Comment by Daretotry** [comment]
I've shared an item with you:

Apple_Transparency_Report-1.zip
https://drive.google.com/file/d/1ZtpDt78VvWnQ9jO0hxGIQnDM9vCzg1F4/view?usp=sharing&invite=CJy37t8C&ts=5d448539

It's not an attachment -- it's stored online. To open this item, just click  
the link above.

**Comment by Daretotry** [comment]
[image: Zip Archive]
SwiftShotCreatingAGameForAugm…
<https://drive.google.com/file/d/1kkvE-GzPz9pNX6WXxtJbPIN37BmBV9z3/view?usp=drivesdk>

**Comment by Daretotry** [comment]
I've shared an item with you:

Copy of Safari - Jan 10, 2019 at 1:28 PM.pdf
https://drive.google.com/file/d/1arj-vdEtUyobMnh8YVcAPWp5_8IFQdcH/view?usp=sharing&invite=CNux5yE&ts=5d958b36

It's not an attachment -- it's stored online. To open this item, just click  
the link above.

**Comment by Daretotry** [comment]
https://support.google.com/mail/answer/6596?hl=en

-- 
null

**Comment by Daretotry** [comment]
-- Please reply above this line --


            Hi James, 

Thanks for writing and I'm so sorry for the trouble. Could you provide
me with some more details about what issues you are having? Also, if
you're getting an error message, could you send a screenshot of it?

Thanks so much for your patience and for any additional information
you can provide!
Shelley
Follow us on Instagram @MarcoPoloApp [1] for tips, updates, stories
and inspiration on how to live joyfully! [2]

Links:
------
[1] https://www.instagram.com/marcopoloapp/
[2] https://marco-polo.typeform.com/to/a9y27C

**Comment by Daretotry** [comment]
---------- Forwarded message ---------
From: Apple <noreply@email.apple.com>
Date: Fri, Oct 11, 2019 at 11:56 PM
Subject: Your Apple ID was used to sign in to iCloud via a web browser.
To: <jlhansendare7718@gmail.com>


Dear James Hansen,
Your Apple ID (*jlhansendare7718@gmail.com* <jlhansendare7718@gmail.com>)
was used to sign in to iCloud via a web browser.

Date and Time: October 11, 2019, 11:55 PM PDT
If the information above looks familiar, you can ignore this message.
If you have not signed in to iCloud recently and believe someone may have
accessed your account, go to Apple ID (https://appleid.apple.com) and
change your password as soon as possible.
Apple Support
Apple ID <https://appleid.apple.com/choose-your-country/> | Support
<https://www.apple.com/support/country/> | Privacy Policy
<https://www.apple.com/legal/internet-services/privacy/>
Copyright © 2019 Apple Inc. One Apple Park Way, Cupertino, CA 95014 USA.
<#m_-8739698526660495176_address> All rights reserved.

**Comment by Daretotry** [comment]
[image: PDF file]
Copy of Safari - Jan 10, 2019…
<https://drive.google.com/file/d/1arj-vdEtUyobMnh8YVcAPWp5_8IFQdcH/view?usp=drivesdk>

**Comment by Daretotry** [comment]
I've shared an item with you:

Apple_Transparency_Report.zip
https://drive.google.com/file/d/1BJUmRYP9nlARHCIe_dVIOe5bVkzHWB3J/view?usp=sharing&invite=CIX3uLsH&ts=5da80e04

It's not an attachment -- it's stored online. To open this item, just click  
the link above.

**Comment by Daretotry** [comment]
I've shared an item with you:

Apple_Transparency_Report.zip
https://drive.google.com/file/d/1BJUmRYP9nlARHCIe_dVIOe5bVkzHWB3J/view?usp=sharing&invite=CIX3uLsH&ts=5daa3f48

It's not an attachment -- it's stored online. To open this item, just click  
the link above.

**Comment by Daretotry** [comment]
I've shared an item with you:

C00FE6F0-72B2-4194-9C51-64B2AB344BE5_SafariViewService - Jan 2 2019 at 730  
PM.pdf
https://drive.google.com/file/d/1H8Vgu80IVzFXmEMGqZnn1EiBpuNednqB/view?usp=sharing&invite=CKfpsdkF&ts=5db5f1e6

It's not an attachment -- it's stored online. To open this item, just click  
the link above.

**Comment by Daretotry** [comment]
https://myaccount.google.com/?utm_source=OGB&tab=kk&utm_medium=act

**Comment by Daretotry** [comment]
https://www.youtube.com/playlist?list=PLGpUTzdP61-iwrmdBAp1G7FbCwXYuruio
