### ISSUE TITLE
Computer freezes on v0.60

### ISSUE THREAD

**Issue by PacoCoca** [facebook/react-native#25819]
On v0.60 my entire computer freezes when i try to run any project (even just created project with react-native init).
If I run a project on v0.59 everything works fine.
The app doesn't even launch, the entire computer freezes before launching the app, it happens in both real device and simulator.

## React Native 
- System:
    - OS: Linux 4.15 Linux Mint 19.1 (Tessa)
    - CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
    - Memory: 5.98 GB / 7.69 GB
    - Shell: 4.4.20 - /bin/bash
- Binaries:
    - Node: 12.6.0 - /usr/bin/node
    - npm: 6.9.0 - /usr/bin/npm
    - Watchman: 4.9.0 - /usr/local/bin/watchman
- npmPackages:
  - react: 16.8.6 => 16.8.6 
  - react-native: 0.60.4 => 0.60.4

## Steps To Reproduce
1. `react-native init <project-name>`
2. `react-native run-android`

Describe what you expected to happen:
The app should run

Snack, code example, screenshot, or link to a repository:

**Comment by plouh** [comment]
Downgrade to node 12.4 to fix the issue

**Comment by PacoCoca** [comment]
> Downgrade to node 12.4 to fix the issue

Thanks, this solved the issue

**Comment by cpmech** [comment]
Wow! Really?! Downgrade node is the solution?!

**Comment by cpmech** [comment]
Nope, 12.4 does NOT fix the problem...
