### ISSUE TITLE
[WebSocket] WebSocket polyfill does not implement EventTarget interface

### ISSUE THREAD

**Issue by leeyeh** [facebook/react-native#2583]
```
Error: ws.addEventListener is not a function
```
specs: https://developer.mozilla.org/en-US/docs/Web/API/WebSocket

**Comment by ide** [comment]
@vjeux - the websocket polyfill was added by @hharnisc awhile ago. can you guys figure out ownership of this module (Community Responsibility being an option)?

**Comment by vjeux** [comment]
We're not using it, so "Community Responsibility" is likely the answer here
