### ISSUE TITLE
will reload clean the AsyncStorage?

### ISSUE THREAD

**Issue by hanai** [facebook/react-native#2584]
I save some data use `AsyncStorage.setItem`, after I reload in Simulator, I got `null` using `AsyncStorage.getItem`.

**Comment by ide** [comment]
Reload should not clean AsyncStorage, which writes to disk.

**Comment by claytongulick** [comment]
@hanai I've run into the same issue - were you able to resolve it? I write to AsyncStorage in the simulator, I can grep the value on disk and see it. When I hit Command-R to reload, the value is cleared.
