### ISSUE TITLE
SafeAreaView with transparent background color not work

### ISSUE THREAD

**Issue by seomaz** [facebook/react-native#25843]
When a set a backgroundcolor with transparent, not working

```
<SafeAreaView style={{flex: 1, backgroundColor: 'rgb(0, 0, 0)'}}>
  <View style={{flex: 1}}>
    <Text>Hello World!</Text>
  </View>
</SafeAreaView>
```

**Comment by cabelitos** [comment]
Not sure what you meant, but rgb(0,0,0) is black and not transparent.

**Comment by seomaz** [comment]
@cabelitos sorry with this: rgba(0,0,0,0). my app.js code:

`<Fragment>
        <SafeAreaView style={styles.safeArea}/>
        <SafeAreaView style={{ flex: 1, backgroundColor: 'rgba(0,0,0,0)',}}>
        <View style={styles.container}>
          {Platform.OS === 'ios' && <StatusBar barStyle="light-content" />}
          <AppNavigator />
          <OfflineNotice/>
          <Ultimahora navigation={this.props.navigation}/>
        </View>
        </SafeAreaView>
        </Fragment>`

the result:
![IMG_4345](https://user-images.githubusercontent.com/5072690/61992016-d5ace800-b058-11e9-91b6-b1b619b33f0b.PNG)

look at the bottom the white bar, i need this transparent.

**Comment by cabelitos** [comment]
@seomaz you have a safeareaview inside another safeareaview probably you're setting the bg color to black only in one of them apparently. I tried to set the safeareaview bg color and it worked like a charm. Maybe if you could create a snack what clearly show the problem, it will be much easier to know what's happening and identify the problem.

https://snack.expo.io/@cabelitos/safe-area-view (safe-area-view with a bg color)

**Comment by seomaz** [comment]
i have 2 safeareaview, because i use 2 colors, top in blue and bottom in transparent, if i change the second safeareaview to a solid color works, but if i put the rgba(0,0,0,0) (transparent) dont work.

**Comment by gguidotti** [comment]
I'm having the same issue. I tried both 'rgba(0, 0, 0, 0)' and 'transparent' but none of them is working.

**Comment by donni106** [comment]
same for me. not being able to set the bottom part of the `SafeAreaView` to transparent.

**Comment by Brouilles** [comment]
Same here.

**Comment by kevinL5** [comment]
same for me +1

**Comment by kgirma** [comment]
No answer I guess. 😄

**Comment by kot-ezhva** [comment]
Any solutions?

**Comment by hramos** [comment]
Please make sure to fill in the issue template if you decide to file a new issue.

**Comment by VirtualDOMinic** [comment]
One thing to try is to give the `SafeAreaView` that you want to be `transparent` a `position: "absolute"`, too, so that it doesn't push down the child/other `SafeAreaView`

**Comment by NioxyBrown** [comment]
Just in case for those who are still looking for it. 
I solved it by setting the property **`flex`** of the **`SafeAreaView`** component to 0.
For me it did the work :)

**Comment by fabriziobertoglio1987** [comment]
the issue here is the position 

you think it is not transparent, but reality is just no positioned on top of another view

you need to use `position: 'absolute'` and `top: 0, bottom: 0, left: 0, right: 0, height: '100%', width: '100%'` to make sure that 2nd view is positioned over the 1st view...
