### ISSUE TITLE
Cant load project due a memory overload

### ISSUE THREAD

**Issue by emanuelebevegni** [facebook/react-native#25841]
Hello everyone, im new with React Native in these days im trying to set up my pc tu run react native project but im having some problem during the run. I follow the getting started guide for windows, all the installation goes well, no error i compare my result to some online tutorial but when i try to run "react-native run-android" the system is trying to loead the dependency graph or some other stuff and overload my pc memory so i got a error message from win7 and this shut down the react procces. i already tried to follow some guid online like this one but nothing changed https://medium.com/@adityasingh_32512/solved-unable-to-load-script-from-assets-index-android-bundle-bdc5e3a3d5ff. Even if i unistall and reinstall everythings i cant load the simple AwesomeProject (virtual or phy device). 

React Native version:

**Comment by nickdbush** [comment]
Confirming this as well, running ```react-native-cli: 2.0.1``` and ```react-native: 0.59.8```. I've attached a photo of the memory usage drop after bailing out of the process (apologies for not using a screenshot, but the computer was unresponsive).

Metro hangs on ```Loading dependency graph...```, never reaching the "done" state. This is a completely fresh react-native project running on 8GB of memory without much else happening. Using Windows 10 with latest updates.

![Seemingly excessive memory usage](https://user-images.githubusercontent.com/10998201/62014875-63462000-b19e-11e9-9cda-051f3834c02e.jpg)

**Comment by nikilarigela** [comment]
Just downgrade the Node.js version to 10. It worked for me.

**Comment by nickdbush** [comment]
Confirming that downgrading to Node 10.16.0 prevents this memory expansion, allowing the project to build

**Comment by cbedoy** [comment]
The same issue with me at https://github.com/facebook/react-native/issues/25893

**Comment by cbedoy** [comment]
@nickdbush it works!

**Comment by philippludwig** [comment]
This happend to me as well, with the newest Node 12.x from the official repository. However, debian users can just install the node 10.15 version from the debian repo and it works fine.

**Comment by cbedoy** [comment]
Just run
```
sudo npm install -g n
sudo n 10.16.0
```
