### ISSUE TITLE
fetch api not working in ios but working in android

### ISSUE THREAD

**Issue by ansarikhurshid786** [facebook/react-native#25857]
I am using react native.
react native info : 
```
React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (16) x64 Intel(R) Xeon(R) CPU E5-1680 v2 @ 3.00GHz
      Memory: 2.15 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.10.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 19, 20, 21, 22, 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.3, 25.0.1, 25.0.2, 26.0.1, 27.0.1, 27.0.3, 28.0.2, 28.0.3, 29.0.0
        System Images: android-22 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom_64, android-23 | Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-Q | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.6 => 16.8.6 
      react-native: ^0.59.9 => 0.59.9 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

I am call web service as below : 

```
let endpoint = "https://service-url"; //it is secured service(http). 
fetch(endpoint).then(res=>res.json()).then((res)=>{
console.log(res); 
}); 

```
Success method get called in both platform but in ios not getting result.

I tried a lot but can't find solution. can anyone help me ? 

same services working fine in chrome and safari browsers(android and ios mobile also)

**Comment by vinicarra** [comment]
Could you provide more info? Does it print any error messages on console? By default iOs will not complete any requests to insecure sources, thus, make sure the requested endpoint has HTTPS.

**Comment by ansarikhurshid786** [comment]
Thanks for response. i have provided all required information. yes web service secured i have mentioned in my question.

**Comment by ansarikhurshid786** [comment]
Actually I am not getting data in ios (react native) but getting data in ios safari browser in android.

**Comment by vinicarra** [comment]
Could you provide the URL you are requesting the data so I can try reproduce the issue here?

**Comment by ansarikhurshid786** [comment]
sorry i can't provide that web service here.

**Comment by ansarikhurshid786** [comment]
I am not getting data in ios(device) but getting in browser. can you tell me possibility so i will check.

**Comment by ansarikhurshid786** [comment]
i check constructed url. json.stringify not working in ios.

**Comment by perfectAlways1028** [comment]
I used react-native 0.59.3 and react 16.8.3 fetch function does not working on ios, it does not reply any message
