### ISSUE TITLE
Forced indexed ram-bunding is broken again for Android

### ISSUE THREAD

**Issue by noomorph** [facebook/react-native#25856]
The original issue (https://github.com/facebook/react-native/issues/21282) was solved by PR https://github.com/facebook/react-native/pull/24967 in commit https://github.com/facebook/react-native/commit/2b0e11c  .

I indeed confirm it works for `react-native@~0.59.9`.

However, it does not work for `0.60.x` — an app crashes in the very beginning.

[adb logcat dump is attached here](https://github.com/facebook/react-native/files/3440487/logcat.txt)

React Native version:
```
System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 34.89 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.6.0 - ~/.nvm/versions/node/v12.6.0/bin/node
    npm: 6.9.0 - ~/.nvm/versions/node/v12.6.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 25, 26, 27, 28
      Build Tools: 27.0.3, 28.0.3
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64
      Android NDK: 19.1.5304403
  IDEs:
    Android Studio: 3.2 AI-181.5540.7.32.5056338
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

## Steps To Reproduce

0. Get an Android emulator running (for example, I was using a standard AVD, `Nexus_5X_API_28` for x86_64)
1. `git clone git@github.com:noomorph/IndexedRamBundleBug_60_4.git`
2. `cd IndexedRamBundleBug_60_4 `
3. `npm install`
3. `cd android`
4. `./gradlew installRelease`
5. Run the app.

Describe what you expected to happen:

App should run **without** crashes, like it used to in RN 0.59.9 and later.

Snack, code example, screenshot, or link to a repository: https://github.com/noomorph/IndexedRamBundleBug_60_4

---

Kind regards,
Yaroslav.

**Comment by skizzo** [comment]
+1, would be nice if this feature that's widely praised by Facebook / React Native would actually work.

**Comment by padlock98** [comment]
Do refer to #25859 .  The workaround works!  Thanks to @noomorph

**Comment by thymikee** [comment]
@skizzo since [Hermes](https://facebook.github.io/react-native/docs/hermes) came out, indexed RAM bundles on Android are pretty much useless (the same idea behind loading modules is built-in into Hermes-generated bytecode). If you can, please give it a try in release mode.

cc @zamotany does it happen with Haul in 0.60 as well? The attached logcat suggests the bundle hasn't been found, which may be Metro config error:

```

07-29 09:20:06.463  4730  4748 E ReactNativeJS: Exception in HostObject::get(propName:SourceCode): java.lang.AssertionError
--------- beginning of crash
07-29 09:20:06.473  4730  4753 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
07-29 09:20:06.473  4730  4753 E AndroidRuntime: Process: com.indexedrambundlebug_60_4, PID: 4730
07-29 09:20:06.473  4730  4753 E AndroidRuntime: com.facebook.react.common.JavascriptException: Exception in HostObject::get(propName:SourceCode): java.lang.AssertionError
```
