### ISSUE TITLE
HotReload not working

### ISSUE THREAD

**Issue by asalhallak** [facebook/react-native#25851]
HotReload not working, changing in reader method not reflecting changes to UI

React Native version:
react-native: 0.60.4
System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
    Memory: 145.45 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.17.3
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.0
      System Images: android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1
## Steps To Reproduce

1. react-native init MyAwesomeProject --template typescript
2. enable hot reload
3. change any text

**Comment by ceydamehves** [comment]
same here on windows 10.

React Native Version:
```
react-native-cli: 2.0.1
react-native: 0.60.4
```

**Comment by YouriT** [comment]
Neither does it work without TypeScript template.

Some additional repro steps:
```
System: Mac 10.14.3
react-native-cli: 2.0.1
react-native: 0.60.5

$ brew install watchman
$ brew tap AdoptOpenJDK/openjdk
$ brew cask install adoptopenjdk8
$ yarn global add react-native-cli
$ react-native-cli init AwesomeProject
$ cd AwesomeProject
$ yarn start
$ react-native run-ios # iPhone X 12.4 gets launched and gets the app installed
```

- CMD+D => Enable Hot Reloading
- Edited App.js and changed App.js *in* App
- Saved
- "Hot Reloading" gray popover appears but "App.js" stayed "App.js" where I was expecting "App"

So only difference is that NodeJS is install through nvm and is therefore located at `$HOME/.nvm/versions/node/v10.15.3/bin/node` but is available in `$PATH`.

Live Reloading works fine but is painful.

**Comment by toly19** [comment]
video sample
[youtube link](https://youtu.be/U_Ckn_N_94g)

my info

```
react-native info
info Fetching system and libraries information...
System:
    OS: macOS 10.14.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.27 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.8.0 - /usr/local/bin/node
    npm: 6.11.2 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom_64
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

**Comment by gaearon** [comment]
React Native 0.61 includes a complete reimplementation of this mechanism called Fast Refresh. It's not out yet as stable, but you can already try [React Native 0.61 RC 3](https://twitter.com/grabbou/status/1171472333313175552).

I'll close and lock this because the implementation is completely different. So if there are still problems after you upgrade to 0.61, please file a new issue with full reproducing instructions (and preferably, a project). Thanks!
