### ISSUE TITLE
[Animations] react-native seems don't perfectly support slow animation

### ISSUE THREAD

**Issue by zzz6519003** [facebook/react-native#2586]
When I'm using the react-native-modal module, when i select slow animation(which the simulator provides), it don't give me a slow animation in the simulator.

**Comment by nicklockwood** [comment]
We're not currently using native iOS animations for the Animated API, so it's not affected by the slow animations feature. It would be neat it if could detect that state and reacted accordingly, but I'm not sure there's any simple way to detect in code when that feature is toggled in the simulator.

**Comment by zzz6519003** [comment]
:beer:
Maybe I can check that out!

**Comment by jeanregisser** [comment]
The slow animation toggle of the simulator only works for UIView animations (i.e. NOT for CA Animations). And obviously only works in the simulator ;)

However it is possible to have a working slow animation debugging feature on both the simulator and device by setting the main window (or any other view) layer speed property:

```objc
view.window.layer.speed = 0.1f; // 0.1f for 10x slower, 1.f for normal speed
```

So if we wanted to have a "Slow Animation" feature for React Native, we could probably base it on this property as well.
And as you said @nicklockwood, it would be great if we could detect the simulator slow animation state.

**Comment by mkonicek** [comment]
@facebook-github-bot answered
