### ISSUE TITLE
RN 0.60.4 android app crashes after splash screen when Hermes is enabled

### ISSUE THREAD

**Issue by tarasvakulka** [facebook/react-native#25864]
React Native version:
0.60.4
Enabled Hermes

Crash on release android build after splash screen
07-29 14:06:59.334 21833 21833 F DEBUG   :     #00 pc 000000000001a170  /data/app/app.theMovieExpert-wKzSD-OkiRBPXzh7GD8Acw==/lib/arm64/libhermes.so (facebook::hermes::detail::hermesFatalErrorHandler(void*, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&, bool)+28)

**Comment by phorensic** [comment]
I'm anxiously awaiting Hermes support to be fixed, but I do see activity on it. There is one commit that looks like it should fix things and Issue #25599 is alive with progress as well. I'm expecting the next release to contain all the fixes.

**Comment by affanhashone** [comment]
@phorensic  Any Idea When The Next Version Will be Releasing ? I added hermes library. but still the app crash in release apk

**Comment by glauberfc** [comment]
@tarasvakulka do you executed `cd android && ./gradlew clean` after you'd active Hermes?

**Comment by tarasvakulka** [comment]
@glauberfc yes of course, I executed cd android && ./gradlew clean

**Comment by phorensic** [comment]
> @phorensic Any Idea When The Next Version Will be Releasing ? I added hermes library. but still the app crash in release apk

Hard to tell. There are lots of commits, but there is no release schedule. It is ready when it is ready type of thing.

**Comment by liganghui** [comment]
A similar problem, I tried to upgrade the application from 0.59.9 to 0.60.4 and I copied the code into a new project. When I enable Hermes, the Android app can start, but it doesn't run smoothly. If I disable Hermes, the app will crash after the splash screen.

**Comment by affanhashone** [comment]
@liganghui RUn in debugging mode, it is super fast

**Comment by taschik** [comment]
@tarasvakulka did you solve the problem?

**Comment by tarasvakulka** [comment]
@taschik,  yes, problem was not in hermes, my method array sort worked incorrect and hermesvm throw error, I refactor my code and now my problem solved
