### ISSUE TITLE
Picker component is inconsistent between iOS and Android

### ISSUE THREAD

**Issue by dkniffin** [facebook/react-native#25866]
I am confused about the intended usage of the [Picker](https://facebook.github.io/react-native/docs/picker#prompt) component. As it is now, it is _very_ inconsistent in behavior between iOS and Android. 

To illustrate this, I've created a small component:

```js
const PickerDummyPage = () => {
  return (
    <>
      <Text style={{ color: 'black' }}>Pick your item...</Text>
      <Picker prompt="Picker" selectedValue="Foo" style={{ backgroundColor: 'gray' }} >
        <Picker.Item value="Foo" label="Foo" />
        <Picker.Item value="Bar" label="Bar" />
      </Picker>
    </>
  )
}
```

Here is how it renders on iOS:

![Screen Shot 2019-07-29 at 1 30 35 PM](https://user-images.githubusercontent.com/1680080/62068883-10538380-b205-11e9-957e-e78482df9e32.png)

and here it is on Android:

![Screen Shot 2019-07-29 at 1 30 59 PM](https://user-images.githubusercontent.com/1680080/62068908-206b6300-b205-11e9-98d1-ee3e5d6a0a05.png)

Ignoring my atrocious styling here, the point I'm trying to get across is that the picker is very different between the two. 

What I'm looking for is an easy way to have a dropdown-like field (similar to [select](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select) on web), that behaves in a way that feels native to each platform. For Android, that seems to be the case, but for iOS, I would expect that it would render as an empty field, and when the field is clicked, it would open up a keyboard-like dialog prompt with the picker rendered inside it.

For reference, here's what a `select` field renders like in Safari (rendering [this page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select)), which is exactly the behavior I'm expecting:

![Screen Shot 2019-07-29 at 1 37 05 PM](https://user-images.githubusercontent.com/1680080/62069343-126a1200-b206-11e9-8100-3ccfc56e38b3.png)

![Screen Shot 2019-07-29 at 1 39 28 PM](https://user-images.githubusercontent.com/1680080/62069464-51986300-b206-11e9-8db6-6eef01767307.png)

For now, my workaround is going to be to use [a 3rd party library](https://github.com/lawnstarter/react-native-picker-select), but this definitely feels like something that should work out of the box in react-native.

React Native version:
```
info
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 64.58 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.14.0 - ~/.asdf/installs/nodejs/11.14.0/bin/node
      Yarn: 1.15.2 - ~/.asdf/installs/nodejs/11.14.0/.npm/bin/yarn
      npm: 6.7.0 - ~/.asdf/installs/nodejs/11.14.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
      Android SDK:
        API Levels: 26, 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-24 | Google Play Intel x86 Atom, android-27 | Intel x86 Atom_64, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.6.3 => 16.8.6
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

**Comment by ecexplorer** [comment]
The date pickers also have quite different behaviors. At least in this case, they are separate components.

**Comment by dkniffin** [comment]
@react-native-bot updated to include RN version. Not sure what else I need to include

**Comment by dkniffin** [comment]
I don't know how to implement this, nor do I have time to, but it looks like I'm not the only one with this opinion, so I'd like to hear from someone from the RN team about whether this is something they would accept. If so, I'd recommend someone create a PR in order to get it moving forward.

**Comment by safaiyeh** [comment]
hi @dkniffin we need some more information.

Could you do a few things:
• verify this happens on the latest version.
• Create a snack or reproducible demo that displays the bug
• follow the issue template

**Comment by dkniffin** [comment]
@safaiyeh I'm not actually working on any RN projects anymore. If anyone else following this thread wants to take this over for me, that would be awesome! I know this would make development of basic forms a bit easier. Essentially what I'm asking for is for something like https://github.com/lawnstarter/react-native-picker-select to become part of the standard RN library.
