### ISSUE TITLE
undefined is not an object Netinfo.isconnected

### ISSUE THREAD

**Issue by ZainaliSyed** [facebook/react-native#25875]
React Native version:
**"react-native": "0.60.4",**

## Steps To Reproduce

1. Using `NetInfo` from react-native in version `0.60.4` giving a run time error of undefined on `isconnected` method whereas same methods are working on `"react-native": "0.59.5"`.

## pod file
`pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'`

**NETWORK INFO CLASS** 

![Simulator Screen Shot - iPhone 7 Plus - 2019-07-30 at 11 39 09](https://user-images.githubusercontent.com/24393023/62106725-6422a300-b2bf-11e9-96dc-e8bd8fee8935.png)

```
import { NetInfo } from "react-native";

class NetworkInfo {
  networkInfoListener(dispatch, networkInfoAction) {
    NetInfo.isConnected.fetch().then(isNetworkConnected => {
      dispatch(networkInfoAction(isNetworkConnected));
    });

    NetInfo.isConnected.addEventListener(
      "connectionChange",
      isNetworkConnected => {
        dispatch(networkInfoAction(isNetworkConnected));
      }
    );
  }

  removeNetworkInfoListener(dispatch, networkInfoAction) {
    NetInfo.isConnected.removeEventListener(
      "connectionChange",
      isNetworkConnected => {
        dispatch(networkInfoAction(isNetworkConnected));
      }
    );
  }
}

export default new NetworkInfo();

```

**Comment by dulmandakh** [comment]
It's removed in RN 0.60, please use https://github.com/react-native-community/react-native-netinfo. Thank you

**Comment by wandhi** [comment]
you must change
const {
    View,
    ImageBackground,
    ActivityIndicator,
    NetInfo,
    Platform,
    StyleSheet,
} = ReactNative;

to

const {
    View,
    ImageBackground,
    ActivityIndicator,
    Platform,
    StyleSheet,
} = ReactNative;

const NetInfo = require('@react-native-community/netinfo');
 in node-module/react-native-cached-image/CachedImage.js

**Comment by evanb2** [comment]
Currently getting this same error after upgrading from `0.59 -> 0.60`, however I'm not importing NetInfo in any of my project files. Just to be safe I installed the new community package, yet still getting the error.

Any help is appreciated!

**Comment by evanb2** [comment]
Ah turns out it was another dependency that needed to be updated. `pusher-js` was the culprit in my case.

**Comment by cdevelopers6** [comment]
const [isConnected,setIsConnected] = useState(false)

        useEffect(()=>{
            NetInfo.addEventListener(handleConnectivityChange);
            NetInfo.fetch().then(state => {
                setIsConnected(state.isConnected)
              });

            return () => {
                NetInfo.addEventListener(state => {
                    setIsConnected(state.isConnected)
                 });
            }
        },[NetInfo])


        function handleConnectivityChange (state)  {
            if (state.isConnected) {
                setIsConnected(true)
              } else {
                setIsConnected(false)
              }
        }

        function MiniOfflineSign() {
            return (
            <View style={styles.offlineContainer}>
                <Text style={styles.offlineText}>No Internet Connection</Text>
            </View>
            );
        }

    
    if(!isConnected){
        return (
            <View style={{height:30}}>
                <MiniOfflineSign />
            </View>
        )
    }
    return null;
    
    

}
