### ISSUE TITLE
React native init with 0.60.4 fails to build in xcode

### ISSUE THREAD

**Issue by ethanzway** [facebook/react-native#25870]
React native init with 0.60.4 fails to build in xcode but react-native run-ios can work.

**React Native version:**
System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 1.63 GB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.6.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
  IDEs:
    Android Studio: 3.3 AI-182.5107.16.33.5314842
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.4 => 0.60.4
  npmGlobalPackages:
    create-react-native-app: 1.0.0
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7

**Steps To Reproduce**
react-native init appName
Open appName.xcworkspace
Change target to appName
Hit Run
Build Fails with the following error:
library not found for -lBase64

**Comment by slavikdenis** [comment]
Duplicate https://github.com/facebook/react-native/issues/25707 ?

**Comment by radko93** [comment]
Please try https://github.com/facebook/react-native/issues/25820#issuecomment-515742426 and I will reopen if this still occurs. Thanks @slavikdenis

**Comment by TheRusskiy** [comment]
@radko93 doesn't solve it unfortunately

**Comment by radko93** [comment]
@TheRusskiy Any more info you can provide on the issue?

**Comment by TheRusskiy** [comment]
@radko93 actually I was able to solve this issue, the project has to be opened another way to include pods.
Thank you!

**Comment by awaistariq** [comment]
I am having same issue. Can anyone help?
