### ISSUE TITLE
TypeScript template doesn't pass type-check by default

### ISSUE THREAD

**Issue by orta** [facebook/react-native#25882]
I know there is another repo for the template but I also have the fix in here. However, I'd like someone with a bigger 0.60 TypeScript project to test the fix (and ideally figure out how to deploy it to React Native) and make sure  the global definition doesn't break anything

We introduced a better launch screen which doesn't have any type definitions to TypeScript, as well as a new Hermes global variable.

These compiler errors can be suppressed by adding:

```ts
export const Header: any
export const LearnMoreLinks: any
export const Colors: any
export const DebugInstructions: any
export const ReloadInstructions: any

declare global {
  const global: { HermesInternal: boolean }
}
```

at `/react-native/Libraries/NewAppScreen/index.d.ts`

/cc @alloy who might know if it's feasible to move this into definitely typed instead?
 
React Native version:

## Steps To Reproduce

1. react-native init MyAwesomeProject --template typescript
2. cd MyAwesomeProject && yarn tsc

**Comment by janicduplessis** [comment]
Global should probably be more like `{ HermesInternal?: {} }` since hermes in undefined with jsc.

I assume the component typedefs are needed because of strict mode? I think it could live inside definitely typed by doing something like `declare module 'react-native/Libraries/NewAppScreen' {...}`.

**Comment by orta** [comment]
haha, machines!

**Comment by orta** [comment]
Sent some PRs for it

**Comment by PeterKow** [comment]
Basically for now you can do this -> https://github.com/react-native-community/react-native-template-typescript/pull/78/files

**Comment by ArturLinhart** [comment]
> Basically for now you can do this -> https://github.com/react-native-community/react-native-template-typescript/pull/78/files

Is it enough? should not be there also the export in 
react-native/index.d.ts? Somehting like

export const HermesInternal: global.HermesInternal;

?

**Comment by ArturLinhart** [comment]
> Basically for now you can do this -> https://github.com/react-native-community/react-native-template-typescript/pull/78/files



> > Basically for now you can do this -> https://github.com/react-native-community/react-native-template-typescript/pull/78/files
> 
> Is it enough? should not be there also the export in
> react-native/index.d.ts? Somehting like
> 
> export const HermesInternal: global.HermesInternal;
> 
> ?

And also the import in App.tsx

import {HermesInternal} from 'react-native/index';

?
