### ISSUE TITLE
(Android) Alert layout is broken on React Native 0.60.4

### ISSUE THREAD

**Issue by thomasonweb** [facebook/react-native#25881]
(Android) Alert layout is broken on React Native 0.60.4.
Android only issue. iOS is looking fine.

![Screenshot_20190730-112746_Ablo Debug](https://user-images.githubusercontent.com/41863161/62118134-74398300-b2bd-11e9-8496-03e7b7ace393.jpg)

React Native version:
0.60.4

## Steps To Reproduce

Run the following example code:
`Alert.alert(
'Title',
			'Description goes here',
			[{
				text: 'buttonOne',
				onPress: (): void => { /* */ },
			}, {
				text: 'buttonTwo',
				onPress: (): void => { /* */ },
			}],
			{
				onDismiss: (): void => { /* */ },
			},
		)`

Describe what you expected to happen:

Alerts should look like this: https://facebook.github.io/react-native/docs/alert
Paddings are missing.

**Comment by kristianhasselknippe** [comment]
I'm also having trouble with Alert on android. My problem is that all the buttons are invisible.

```
Alert.alert('Test title', 'Test description', [{
	text: 'Ok',
	onPress: () => {}
}, {
	text: 'Cancel',
	style: 'cancel'
}])
```
<img width="356" alt="Android_Emulator_-_Pixel_2_API_29_5554" src="https://user-images.githubusercontent.com/1510999/62454919-890e8e80-b775-11e9-90be-196fb67ff71e.png">

iOS works fine.

**Comment by kristianhasselknippe** [comment]
Was able to fix it by changing the primary_light color in android/app/src/main/res/values/colors.xml,
but i'm not sure what has changed since the previous version.
