### ISSUE TITLE
TextInput onChange event adds new value to previous value

### ISSUE THREAD

**Issue by Aequitas737** [facebook/react-native#25887]
This was not an issue in RN 0.55 but after upgrading to RN 0.59 this issue presented itself.

I have a TextInput with:
```
onChange={event => {
    console.log(event.nativeEvent.text;
    this.props.onChange(event.nativeEvent.text)
}}
```

the this.props.onChange is a redux action that sets the value:
`value={this.props.value}`

My issue is that after typing the letter 'A' it works fine but then I type the letter 'B' and the `event.nativeEvent.text` value in the onChange fires 'AAB'.

Describe what you expected to happen:
The 2nd console.log should only log 'AB' not 'AAB'

React Native version:
```
info
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
      Memory: 799.40 MB / 7.91 GB
    Binaries:
      Yarn: 1.5.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338
```

**Comment by 452MJ** [comment]
Try to use [onChangeText](https://facebook.github.io/react-native/docs/textinput#onchangetext).

**Comment by knro** [comment]
I am getting the exact same behavior (randomly) with onChangeText.
