### ISSUE TITLE
[Documentation] Style prop of View lost link to flexbox/transform docs

### ISSUE THREAD

**Issue by browniefed** [facebook/react-native#2588]
As the title states, the links to the Flexbox and Transform documentation seems to be gone with the new doc updates.

**Comment by brentvatne** [comment]
@browniefed - want to PR this? :smile:

**Comment by browniefed** [comment]
@brentvatne :+1: I'll take a look at it.

**Comment by browniefed** [comment]
Looked into this looks like the upgrade of `react-docgen` from 1.1.0 => 2.0.1 and or possibly one of the dependencies that got updated in that time span stopped parsing `compose` flow types correctly.
So the `ViewStylePropTypes.js` which composes Layout/Transforms into `ViewStylePropTypes` via a spread operator isn't being processed correctly. Something along those lines.

Filed an issue here https://github.com/reactjs/react-docgen/issues/23

**Comment by browniefed** [comment]
PR here, closing issue now https://github.com/facebook/react-native/pull/2654
