### ISSUE TITLE
Loading dependency graph... Frozen

### ISSUE THREAD

**Issue by cbedoy** [facebook/react-native#25893]
Hi everyone I'm having stuck terminal and worst case frozen computer when I ran:
```react-native start```
I want to run my android application but I'm blocked by.

React Native version:

```
System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-4570R CPU @ 2.70GHz
    Memory: 1.74 GB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.6.0 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 25, 26, 27, 28
      Build Tools: 28.0.3, 29.0.1
      System Images: android-27 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: /undefined - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4 
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-cli: 2.0.1
```
## Steps To Reproduce

Follow: https://facebook.github.io/react-native/docs/getting-started
Run in terminal

```react-native start```

Describe what you expected to happen:

**Run my app!**

Snack, code example, screenshot, or link to a repository:

![Screen Shot 2019-07-31 at 10 26 46](https://user-images.githubusercontent.com/5570799/62225280-bfb36600-b37d-11e9-9960-eb73a02adc8b.png)

**Comment by cbedoy** [comment]
I found the solution maybe you need to specify a version of node over here:

https://facebook.github.io/react-native/docs/getting-started#node-watchman-jdk

I just did:

```
sudo npm install -g n
sudo n 10.16.0
```

Then works.

**Comment by GuillaumeAmat** [comment]
Indeed, calling `react-native start` with RN 0.60.4 and Node.js 12.6 eats several gigs of RAM and takes ages to display _done_.

But with Node.js 10.16 it works like a charm!

Thanks @cbedoy for the hint 👌

**Comment by victorlevasseur** [comment]
It did once on my computer when I updated from 0.59 to 0.60. Since then, it runs quickly as it seems only the first launch after the upgrade has more work.

**Comment by GuillaumeAmat** [comment]
@victorlevasseur It's because the first run generates a cache, which is used for the next runs.

Try `react-native start --reset-cache` and you'll see the difference.
