### ISSUE TITLE
Question:  cant found SwipeableFlatList in react native 0.6+，how can i use it?

### ISSUE THREAD

**Issue by tfeng-use** [facebook/react-native#25892]
1. code
```
import {
  SwipeableFlatList,
} from 'react-native'
```
2. error
![error](https://user-images.githubusercontent.com/36724381/62224743-bd86f100-b3e9-11e9-985c-1b108c6c09fe.png)

**Comment by Pangyuyu** [comment]
我也遇到了这个问题

**Comment by ikimiler** [comment]
I also found this problem

**Comment by yangke687** [comment]
the component has been removed
