### ISSUE TITLE
btoa' doesn't exist, js engine: hermes

### ISSUE THREAD

**Issue by tamirrab** [facebook/react-native#25895]
React Native version: 0.60.4

## Steps To Reproduce

Describe what you expected to happen:
On Android:
btoa(“test”) crush when Hermes is on.

**Comment by ide** [comment]
btoa is part of the web spec (https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/btoa) but isn't part of JavaScript. I'd just implement it in userspace if needed.

**Comment by Ludus-Team** [comment]
I think it will be good
I'm using now this instead: https://github.com/mathiasbynens/base64

**Comment by tamirrab** [comment]
I think it will be good
I'm using now this instead: https://github.com/mathiasbynens/base64
