### ISSUE TITLE
Can't read fetch.then(response.text()) text content?

### ISSUE THREAD

**Issue by That-Intern** [facebook/react-native#25896]
I'm trying to use fetch() to ping an API which returns a response as text/HTML, I'm attempting to read the response and can't seem to read the actual text content of the response 

## Environment 
    OS: Linux 4.19
    Node: 12.4.0
    Yarn: 1.17.3 
    npm: 6.9.0 
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4

## Steps To Reproduce
1. Start a new React Native project
2. Install `react-native-image-picker` 
3. Add the necessary file permission for `react-native-image-picker`
4. Save the code [Here](https://gist.github.com/That-Intern/a1eca2b402542745b08fda8e548e4a66) in your React Native project 
5. Run the React Native Project

Additionally, you could run lines 9-26 in a browser with CORS disabled and `Alert.alert()` changed to `alert()` [As shown in this JS fiddle that produces the correct output](https://jsfiddle.net/7o8jgq0p/)   

##  Expected Output
An alert with the string "Now loading..." followed by an alert with the string "text should have been posted" Followed by an alert with the string **"No request type given."**
## Actual output 
An alert with the string "Now loading..." followed by an alert with the string "text should have been posted" Followed by an alert with the string **"[object Blob]"**, this seems like it's failing to parse the text as a string? 

Snack: https://snack.expo.io/rk4IvIJ7S

**Comment by aaayushsingh** [comment]
+1

I tried doing a simple 
```
const dashboard = await fetch("https://www.google.com/?gws_rd=ssl", {
    method: "GET"
  });
  const dashboardPage = await dashboard.json();
  console.log(dashboardPage);
```
and this gives me undefined. hitting the same url with xhr returns vaild html

```
"dependencies": {
    "react": "16.8.6",
    "react-native": "0.60.3"
  },
```

**Comment by That-Intern** [comment]
What information am I missing from the template? I found a work around using `axios.post()` that produces the correct output, you can view the code [Here](https://gist.github.com/That-Intern/91fc6ac7d2c383073a9b5ef64ea0c6ac) this leads me to believe it's a bug caused by how `fetch() `and React Native interact? 

I'm not a fan of installing whole modules for a very simple request so I'll rewriting the code to work with plain old  `XMLHttpRequest()`

**Comment by guaiguaimao** [comment]
I has  the same issue

**Comment by kaiRuTo** [comment]
I has same issue when upgrade from 0.57 to 0.59
