### ISSUE TITLE
Keyboard functionality for ListView

### ISSUE THREAD

**Issue by gudmundurmar** [facebook/react-native#2589]
Why aren't the ScrollView functionalities
- keyboardShouldPersistTaps
- keyboardDismissMode

available for ListView?

Is there a reason why they aren't available? (or are they simply not done yet?)

**Comment by ide** [comment]
They should be... Have you tried them?

**Comment by gudmundurmar** [comment]
I'm using React-native 0.8.0. Did it come after that?

**Comment by ide** [comment]
I don't think so.. but we support only the latest code so you may want to try that.

**Comment by gudmundurmar** [comment]
I can't seem to get it working. 
Love it if someone could confirm that it works or doesn't work.

1. ***If it works for someone else*** then updating (the ListView documentation accodordingly)[https://facebook.github.io/react-native/docs/listview.html#content] would be a solid move.

2. ***If it doesn't work*** then fixing/adding this feature would be wildly appreciated

**Comment by gudmundurmar** [comment]
My bad. I got it all working (was getting pretty tired yesterday and didn't notice I was using the main.jsbundle :< )
Adding this to the ListView documentation would be nice though. Thanks for the help @ide

**Comment by AndrewHenderson** [comment]
@gudmundurmar @ide I've added `keyboardShouldPersistTaps="always"` to my `ListView`. However, I'm experiencing the need for the user to tap twice when selecting an item in the list – one to close the keyboard and one to press the `ListView` row which houses a `TouchableHighlight`.

I'm using a `TextInput` for the search box and the `ListView` houses the results. I'd like the user to be able to choose an item in the list without having to close the keyboard first.

I must be missing something 😐
