### ISSUE TITLE
TextInput have a different size depending on platform

### ISSUE THREAD

**Issue by yairopro** [facebook/react-native#25891]
TextInput have a different height depending on platform.
On iOS it's smaller, and on Android, it's bigger.

React Native version:
info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 177.69 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
      Yarn: 1.17.3 - ~/.nvm/versions/node/v10.13.0/bin/yarn
      npm: 6.10.2 - ~/.nvm/versions/node/v10.13.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.2, 26.0.2, 26.0.3, 27.0.0, 27.0.3, 28.0.2, 28.0.3
        System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.6 => 16.8.6 
      react-native: ^0.60.0 => 0.60.4 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Steps To Reproduce

1. Place a `<TextInput />`

**Describe what you expected to happen:**

The `<TextInput />` should have the same height on any platform. I would even say same height as a `<Text />` component (when it has the same content inside of course).

**Describe what happens:**

The `<TextInput />` is bigger than a `<Text />` on Android, smaller on iOS, and equals on React-Native-Web.

**Snack, code example, screenshot, or link to a repository:**

https://snack.expo.io/@yairopro/textinput-height-difference-demo

![Issue text input](https://user-images.githubusercontent.com/8110568/62228308-1775bf80-b3c6-11e9-8e77-91125373c95a.png)

**Comment by zcgit** [comment]
same problem +1
