### ISSUE TITLE
How to fix the error for "value for uri cannot be cast from readablenativemap to string"

### ISSUE THREAD

**Issue by abhishekGauravOmnist** [facebook/react-native#25907]
![53158923-04f4-436c-a172-65217f6bcd38](https://user-images.githubusercontent.com/53034466/62295702-49048e80-b48b-11e9-8d4a-c0e2b6cdd174.jpg)

Description:-
When i call the api using fetch method for post the image (in base64 format),  i get following issue:
"value for uri cannot be cast from readablenativemap to string".
using react-native-customized-image-picker for image picker.

React Native version:

React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i5-4310U CPU @ 2.00GHz
      Memory: 1.11 GB / 7.90 GB
    Binaries:
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5692245

What could this be caused by?
Thanks in advance.

**Comment by theweavrs** [comment]
@abhishekGauravOmnist You are using `Image` component I think? It seems you set the `source` prop to a JSON object. The correct implementation would be like this:
```
<Image source={{uri: your image source URL here}}/>
```

**Comment by abhishekGauravOmnist** [comment]
@theweavrs, thanks for reply but I'm getting this issue when posting the data. my code is below.


for (let i = 0; i < this.props.navigation.state.params.imageArray.length; i++) {
         let source = { uri: 'data:image/jpeg;base64,' + this.props.navigation.state.params.imageArray[i].imageData };
         formdata.append("image[]", { uri: source, name: 'post.jpg', type: 'multipart/form-data' })
    }

fetch('http://omnisttechhubsolutions.com/fashionApp/public/api/v1/addPost', {
      method: 'post',
      headers: {
        'Content-Type': 'multipart/form-data',
      },
      body: formdata
    }).then(response => response.json())
      .then(response => {
       // Alert.alert(JSON.stringify(response))

        this.setState({ isLoading: false });

          if (response.response_code == "200") {
             // Alert.alert(""+response.postID)
              Alert.alert(
                '',
              response.message,
              [
               {text: 'OK', onPress: () => this.backToHome()},
              ],
              { cancelable: false }
             )

          } else {
               Alert.alert("Error", response.message)
          }
      }).catch(err => {
        Alert.alert("Error" + err)
        console.log(err)
      })
  }
