### ISSUE TITLE
[ART] ARTBrush.m complains about "-init" not being defined

### ISSUE THREAD

**Issue by ide** [facebook/react-native#2590]
cc @nicklockwood this is one of those warnings that can be fixed with `RCT_NOT_DEFINED` but it seems like ART might be its own project separate from RN so not sure what you want to do here.

**Comment by nicklockwood** [comment]
ART's is fully dependent on RN, so it's fine to use RCT_NOT_DEFINED there.

**Comment by ide** [comment]
:+1: will send a PR in a bit

**Comment by browniefed** [comment]
@ide merge the PR and close the issue?

**Comment by ide** [comment]
@browniefed the PR needs to be merged on the fb side. When that happens and the bot syncs the change back out to github it'll autoclose this task too.

**Comment by browniefed** [comment]
@ide neat, I didn't know that! Good to know.
