### ISSUE TITLE
Question: How to apply conditional css based on data get in asyncstorage.

### ISSUE THREAD

**Issue by rshaikhcornerstone** [facebook/react-native#25906]
React Native version:

0.60.04

## Steps To Reproduce

1. Create one css file called style.js and write custom css there
2. Get one flag in asyncstorage and apply this flag for conditional css

Describe what you expected to happen:

I am trying to apply conditional css based on data we get in asyncstorage. I want to apply light and dark theme. I am not getting how to do it as we can not write inside promise object.

Snack, code example, screenshot, or link to a repository:

**Comment by theweavrs** [comment]
@rshaikhcornerstone This is not a bug. Please ask this question on StackOverflow.

**Comment by realPrimoh** [comment]
This is not a bug. However, an idea that you can try is having a default theme, such as 'white', and storing that in your state (such as theme: 'white'). Then, your 'white' CSS will render, and if the AsyncStorage promise resolves into 'dark', then update the state with your 'dark' (this.setState({theme: 'dark'}).

In your rendering, depending on the theme, grab the corresponding StyleSheet and store it in your render function as a constant. Use that constant throughout your render() returned code, and therefore, the theme will be updated depending on the Asyncstorage response. Let me know if you have any questions.
