### ISSUE TITLE
Failed to install the app. Please accept all necessary SDK licenses using SDK Manager: "$ANDROID_HOME/tools/bin/sdkmanager --licenses". Run CLI with --verbose

### ISSUE THREAD

**Issue by wojtek2313** [facebook/react-native#25900]
React Native version:

## Steps To Reproduce

1.
2.

Describe what you expected to happen:

Snack, code example, screenshot, or link to a repository:

**Comment by theweavrs** [comment]
@wojtek2313 This doesn't seem to be a bug with RN. Please ask this over at StackOverflow.
