### ISSUE TITLE
Animated.timing,RangeError: Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by charlesluo2014** [facebook/react-native#25915]
When use Animated.timing,throw exceptions of "RangeError: Maximum call stack size exceeded." in iOS,but android platform is ok.
 
React Native version:
 
 System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
    Memory: 193.54 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 16, 19, 20, 21, 22, 23, 25, 27, 28
      Build Tools: 20.0.0, 21.1.2, 22.0.1, 23.0.1, 23.0.2, 23.0.3, 24.0.0, 24.0.0, 24.0.3, 25.0.1, 27.0.3, 28.0.1, 28.0.3
      System Images: a...google_apis | Google APIs Intel x86 Atom Sys..., a...gle_apis | Google APIs Intel x86 Atom_64 ...
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4

## Steps To Reproduce

componentDidMount() {
        this.scannerLineMove();
    }

    scannerLineMove() {
        this.state.animatedValue.setValue(0);  //Rest Rotate Value to 0
        Animated.timing(this.state.animatedValue, {
            toValue: this.props.rectHeight,
            duration: this.props.scanBarAnimateTime*100,
            easing: Easing.linear,
            sInteraction: false,
        }).start(() => this.scannerLineMove());
    }

**Comment by charlesluo2014** [comment]
call stack:
This error is located at:
    in QRScannerRectView (at view/index.js:81)
    in RCTView (at View.js:35)
    in View (at RNCamera.js:737)
    in Camera (at view/index.js:68)
    in RCTView (at View.js:35)
    in View (at view/index.js:67)
    in QRScannerView (at scan/index.js:70)
    in ScanScreen (at SceneView.js:9)
    in SceneView (at StackViewLayout.tsx:899)
    in RCTView (at View.js:35)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at StackViewCard.tsx:93)
    in RCTView (at View.js:35)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at screens.native.js:71)
    in Screen (at StackViewCard.tsx:80)
    in Card (at createPointerEventsContainer.tsx:95)
    in Container (at StackViewLayout.tsx:971)
    in RCTView (at View.js:35)
    in View (at screens.native.js:101)
    in ScreenContainer (at StackViewLayout.tsx:383)
    in RCTView (at View.js:35)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at StackViewLayout.tsx:379)
    in PanGestureHandler (at StackViewLayout.tsx:372)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.tsx:103)
    in RCTView (at View.js:35)
    in View (at Transitioner.tsx:267)
    in Transitioner (at StackView.tsx:40)
    in StackView (at createNavigator.js:61)
    in Navigator (at createKeyboardAwareNavigator.js:12)
    in KeyboardAwareNavigator (at SceneView.js:9)
    in SceneView (at DrawerView.js:149)
    in RCTView (at View.js:35)
    in View (at ResourceSavingScene.js:20)
    in RCTView (at View.js:35)
    in View (at ResourceSavingScene.js:16)
    in ResourceSavingScene (at DrawerView.js:148)
    in RCTView (at View.js:35)
    in View (at screens.native.js:101)
    in ScreenContainer (at DrawerView.js:138)
    in RCTView (at View.js:35)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at DrawerLayout.js:446)
    in RCTView (at View.js:35)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at DrawerLayout.js:445)
    in PanGestureHandler (at DrawerLayout.js:501)
    in DrawerLayout (at DrawerView.js:165)
    in DrawerView (at createNavigator.js:61)
    in Navigator (at createAppContainer.js:429)
    in NavigationContainer (at App.js:277)
    in RCTView (at View.js:35)
    in View (at App.js:275)
    in MainScreen (at renderApplication.js:40)
    in RCTView (at View.js:35)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:35)
    in View (at react-native-root-siblings/index.js:34)
    in RootSiblingsWrapper (at AppContainer.js:112)
    in RCTView (at View.js:35)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:39)

This error is located at:
    in NavigationContainer (at App.js:277)
    in RCTView (at View.js:35)
    in View (at App.js:275)
    in MainScreen (at renderApplication.js:40)
    in RCTView (at View.js:35)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:35)
    in View (at react-native-root-siblings/index.js:34)
    in RootSiblingsWrapper (at AppContainer.js:112)
    in RCTView (at View.js:35)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:39)

**Comment by connorwaslo** [comment]
I'm not able to recreate this error running it on iOS. Check this snack, does this look like a close recreation?

https://snack.expo.io/@connorwaslo/3333f3

**Comment by charlesluo2014** [comment]
> I'm not able to recreate this error running it on iOS. Check this snack, does this look like a close recreation?
> 
> https://snack.expo.io/@connorwaslo/3333f3
I found the error because of this 'react-native-wechat' dependency
yarn add react-native-wechat

**Comment by dulmandakh** [comment]
Closing this issue because it's not related to React Native, but maybe react-native-wechat. Please file an issue to react-native-wechat.
