### ISSUE TITLE
[Picker] onChange is broken

### ISSUE THREAD

**Issue by ide** [facebook/react-native#2591]
@brentvatne noticed that change events were no longer getting fired in master. https://github.com/facebook/react-native/commit/848839858b4f4e03b83e625304af21aa8dd8ff05 is possibly related. KP?

cc @vjeux @nicklockwood

**Comment by nicklockwood** [comment]
Looks like I forgot to add `RCT_EXPORT_VIEW_PROPERTY(onChange, RCTBubblingEventBlock)` to `RCTPickerManager.m`. I'll fix it.

**Comment by ide** [comment]
I have a fix if you don't get to it first.

**Comment by nicklockwood** [comment]
I've already submitted internally, but thanks.
