### ISSUE TITLE
Release apk not working on latest phone 

### ISSUE THREAD

**Issue by Sajid-Ali** [facebook/react-native#25929]
release build not working on latest build, i have test on S6-Edge its working as expected also i have tested S9, debug-apk working fine on latest phone having issue in release apk, the app is not crashing its not even sent network request in release apk.    

React Native Environment Info:
      Node: 10.15.0 
      npm: 6.9.0 
      Watchman: 4.9.0 

    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.8 => 0.59.8 

    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-rename: 2.4.1

**Comment by 452MJ** [comment]
Maybe you should provide some Android log details.
