### ISSUE TITLE
Error to run react-native run-android - info Starting JS server... Loop / Erro ao rodar react-native run-android - info Starting JS server... Loop

### ISSUE THREAD

**Issue by lucasz-si** [facebook/react-native#25935]
Galera de um tempo pra cá ficou dificil programar em React Native.. pq nem o run-android eu to conseguindo fazer mais ... ele fica nisso:

$ react-native run-android              
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 897 file(s) to forward-jetify. Using 4 workers...
info Starting JS server...

Ele fica nesse Info Starting JS server infinitamente... e msm eu n tendo nada no meu projeto apenas um react-native init... ele n consegue sair desse Starting JS server..

-----------------------------------------------------------------------------------------------------------------------

Guys for a while here it was difficult to program in React Native .. because not even run-android I can do more ... he gets it:

$ react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 897 file (s) to forward-jetify. Using 4 workers ...
info Starting JS server ...

It stays in this Info Starting JS server infinitely ... and msm I have nothing in my project just a react-native init ... he can't get out of this Starting JS server ..

**Comment by ogiansouza** [comment]
@lucasZduality resolveu o problema? Estou passando por isso também.

**Comment by cassioalmeidas** [comment]
I have the same problem

**Comment by cassioalmeidas** [comment]
@ogiansouza @lucasZduality https://stackoverflow.com/a/57314677

**Comment by cardimajs** [comment]
i have same problem

**Comment by BrenoMazieiro** [comment]
**Linux:**
Go to the terminal and type:
` react-native start`

and then in **OTHER** terminal, inside your project folder:
`yarn android`
or
`npm run android`
