### ISSUE TITLE
use hermes in win10

### ISSUE THREAD

**Issue by lihxhit** [facebook/react-native#25930]
I generate a new project with react-native 0.60.4 and follow the steps in
[https://facebook.github.io/react-native/docs/hermes](url)
but i  type the code const isHermes = () => global.HermesInternal != null;
run isHermes()
and i got false

React Native version:
System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
    Memory: 7.64 GB / 15.92 GB
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.5.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      Android NDK: 16.1.4479499
![8D8CBD87-2C9D-4b84-A606-852BB6417478](https://user-images.githubusercontent.com/10525459/62411475-e4ca0200-b625-11e9-8223-aeb5cb9e4971.png)
![A13B1737-0C91-43a7-B907-710250238685](https://user-images.githubusercontent.com/10525459/62411476-e5629880-b625-11e9-8ef3-b7283d2cb7b2.png)

**Comment by 452MJ** [comment]
Have you modify `android/app/build.gradle` file by following [Using Hermes](https://facebook.github.io/react-native/docs/hermes)?

**Comment by gogoku** [comment]
is hermes not available in windows 10 or anything like that ????
Cant get it to work  global.HermesInternal is always undefined
