### ISSUE TITLE
Persist Keyboard OnPress TouchableOpacity

### ISSUE THREAD

**Issue by daniyal-intellicel** [facebook/react-native#25931]
I have made chat application and whenever I press send button on the right of TextInput, the keyboard closes. I want to persist the keyboard on send button (check button) press. Couldn't find anyway to do it. How can I do this?

![V5K6C](https://user-images.githubusercontent.com/43338645/62413135-a0d6fd00-b625-11e9-9477-d006f150c358.jpg)

**Comment by giscafer** [comment]
any solutions?
