### ISSUE TITLE
Anybody facing slow debugging?

### ISSUE THREAD

**Issue by ErHarinderSingh** [facebook/react-native#25937]
Hello everyone. 
I am facing slow debugging. It is bit slow and when try to click on button within app, it fires after 2-3 seconds. Sometimes takes 7-10 seconds. What is the problem? These following are my package dependencies.

 ```
"hermes-engine": "^0.1.1",
    "native-base": "^2.13.4",
    "react": "16.8.6",
    "react-native": "0.60.4",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-reanimated": "^1.1.0",
    "react-native-sqlite-storage": "^3.3.11",
    "react-native-swipe-list-view": "^2.0.0",
    "react-navigation": "^3.11.1"
```

**Comment by karvulf** [comment]
disable your hermes, then it will be faster, weird problem @ErHarinderSingh
