### ISSUE TITLE
react-native run-android não funciona... | react-native run-android not work..

### ISSUE THREAD

**Issue by lucasz-si** [facebook/react-native#25939]
ao rodar o comando em um projeto recem criado:
$ react-native run-android

info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 855 file(s) to forward-jetify. Using 4 workers...
info Starting JS server...

Fica nisso infinitamente... e não sai disso dai... algum bug?

---

when running the command on a newly created project:
$ react-native run-android

info Running the jetifier to migrate libraries to AndroidX. You can disable it using the "--no-jetifier" flag.
Jetifier found 855 file (s) to forward-jetify. Using 4 workers ...
info Starting the JS server ...

It's in this infinitely ... and it doesn't come out of there ... any bugs?

**Comment by Sohaib76** [comment]
I Have exactly the same problem.
Did someone find any solution?

**Comment by lucasz-si** [comment]
> I Have exactly the same problem.
> Did someone find any solution?

no bro, seems to be a bug of react-native msm because if you go to my git and clone my project there it the same thing but if you run yarn install it runs normal ... I still don't know why this damn bug .. I'm almost 2 days without programming React Native..

**Comment by lucasz-si** [comment]
> I Have exactly the same problem.
> Did someone find any solution?

Solution: https://stackoverflow.com/questions/57313661/stuck-on-info-starting-js-server
