### ISSUE TITLE
TextInput with TextAlign on iOS does not add ellipsis 

### ISSUE THREAD

**Issue by malashkevich** [facebook/react-native#25944]
When using TextInput with `textAlign:left` and if the string is more than the width of the input it just crops the text instead of adding ellipsis.

![image](https://user-images.githubusercontent.com/1452064/62467372-43b18780-b79c-11e9-8b7f-70ad6763fc4f.png)

React Native version:
System:
    OS: macOS 10.14.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 45.38 MB / 32.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
  IDEs:
    Android Studio: 3.4 AI-183.5429.30.34.5452501
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.4 => 0.60.4

## Steps To Reproduce

1. Init new application
2. Put following code:
```
import React from 'react';
import {Text, TextInput, View} from 'react-native';

import {Colors} from 'react-native/Libraries/NewAppScreen';

const App = () => {
  return (
    <View style={{flex: 1, justifyContent: 'center'}}>
      <View>
        <Text>Text without alignment</Text>
        <TextInput style={{padding: 10, margin: 20, borderColor: Colors.lighter, borderWidth: 1}}/>
        <Text>Text with alignment:left</Text>
        <TextInput style={{padding: 10, margin: 20, borderColor: Colors.lighter, borderWidth: 1, textAlign: 'left'}}/>
      </View>
      <TextInput/>
    </View>);
};

export default App;
```
3. Write some long text into the first field with spaces. 
4. Write similar text into the second field.
5. Unfocus second input

Expected: both fields will have ellipsis at the end
Actual: second input with `textAlign` doesn't have ellipsis.

----------------------

Android app works in a different way:
It never shows ellipsis but if you type a long string it always shows the end of it and never beginning. I guess it should move to begin when unfocused.

**Comment by malashkevich** [comment]
It's not fixed

**Comment by safaiyeh** [comment]
Backlog

**Comment by safaiyeh** [comment]
I'll check this out tomorrow!
