### ISSUE TITLE
全面屏手机modal 存在问题

### ISSUE THREAD

**Issue by gyfgyf** [facebook/react-native#25942]
React Native version:

## Steps To Reproduce

1.
2.

Describe what you expected to happen:

Snack, code example, screenshot, or link to a repository:

**Comment by gyfgyf** [comment]
在modal 中放入ScrollView 后,modal 不能全部覆盖手机屏幕，会露出一部分，例如oppoR15

**Comment by dulmandakh** [comment]
Please provide demo code. I'll re-open it once we have demo. Thank you
