### ISSUE TITLE
No FBLoginManager found in NativeModules

### ISSUE THREAD

**Issue by dsgithub2018** [facebook/react-native#25943]
Description:
I am using react-native 0.60.4 and in my package.json I have mentioned, "react-native-fbsdk": "git+https://github.com/facebook/react-native-fbsdk.git" and my pod file is like,

pod 'FBSDKCoreKit', '~> 5.0'

pod 'FBSDKLoginKit', '~> 5.0'

pod 'FBSDKShareKit', '~> 5.0'

In **IOS** I have found the following line in react-native-fbsdk->js->FBLoginManager.js,
**const LoginManager = require('react-native').NativeModules.FBLoginManager;**

But when I console the require('react-native'), I saw there is no FBLoginManager in NativeModules. But in android FBLoginManager is available in NativeModules. I think that's why I am always getting the error in **IOS** like,
**TypeError: LoginManager.logInWithPermissions is not a function**

React Native version:
info Fetching system and libraries information...

System:

    OS: macOS 10.14.5

    CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz

    Memory: 60.68 MB / 8.00 GB

    Shell: 3.2.57 - /bin/bash

  Binaries:

    Node: 10.15.3 - /usr/local/bin/node

    Yarn: 1.17.3 - /usr/local/bin/yarn

    npm: 6.4.1 - /usr/local/bin/npm

  SDKs:

    iOS SDK:

      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2

  IDEs:

    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild

  npmPackages:

    react: 16.8.6 => 16.8.6 

    react-native: 0.60.4 => 0.60.4 

  npmGlobalPackages:

    react-native-cli: 2.0.1

    react-native-create-library: 3.1.2

Can anybody fix this issue?

**Comment by dsgithub2018** [comment]
> Thanks for submitting your issue. Can you take another look at your description and make sure the issue template has been filled in its entirety?
> 
>  [Click here if you want to take another look at the Bug Report issue template.](https://github.com/facebook/react-native/issues/new?template=bug_report.md)

Details submitted.

**Comment by dsgithub2018** [comment]
Waiting for the fix.

**Comment by dulmandakh** [comment]
I looks like you didn't followed instructions or forgot to link the native module. Please file an issue to https://github.com/facebook/react-native-fbsdk if issue persists. Thank you
