### ISSUE TITLE
Linking.openURL for phone call adds +1 to phone number by default (iOS)

### ISSUE THREAD

**Issue by pamelaschuldiner** [facebook/react-native#25949]
Linking.openURL for phone call adds +1 to phone number by default in iOS platform

React Native version:
0.59.10

## Steps To Reproduce

Just press a button with Linking.openURL('tel://231323312')

## Since

This happens after my upgrade from RN 0.56 to RN 0.59.10

Any clue??

Thanks

**Comment by jeswinsimon** [comment]
Could you provide more information regarding this. I created a new project using RN 0.59.10 and I am unable to recreate this issue.
![IMG_6431](https://user-images.githubusercontent.com/6000369/62800554-49db9700-bb01-11e9-8f32-0f927a0b3376.PNG)

**Comment by saadsaleem187** [comment]
@pamelaschuldiner Check this with new copy of RN 0.59.10. I think this happens to you after upgrade from RN 0.56 to RN 0.59.10 because i don't face any issue with new project like @jeswinsimon
