### ISSUE TITLE
When using 'position' behavior on iOS, text inputs in WebViews have a long delay in showing text

### ISSUE THREAD

**Issue by connor-odoherty** [facebook/react-native#25958]
![Webview text input bug](https://user-images.githubusercontent.com/10620559/62548917-6daa8e80-b81c-11e9-9eb5-e51ba687e127.gif)

Description:

When wrapping a React Native WebView in KeyboardAvoidingView with 'position' behavior, the text inputs on the rendered webpage behave oddly. As you can see, the text does not appear until I stop typing. This happens both in the simulator AND on an actual device.

If I change the 'behavior' to 'padding', the text inputs work normally.

In the case above, my text input has 'absolute' positioning. Might this impact it?

React Native version:
0.59.8

## Steps To Reproduce

1. On a RN page, wrap a WebView component in a KeyboardAvoidingView component
2. Set the KeyboardAvoidingView component to use 'position' as its `behavior` prop on iOS
3. On an iOS device, navigate to a page with a text input from within the WebView
4. When you type in the text input, the text you are typing will not appear until you pause for a second
5. If you set the `behavior` prop to 'padding' instead of 'position', the text input works fine

Describe what you expected to happen:

The `behavior` prop should not have any impact on the usability or behavior of text inputs on a webpage in a WebView

Snack, code example, screenshot, or link to a repository:

```
      <KeyboardAvoidingView
        behavior={Platform.select({ ios: "position", android: null })}
        enabled
        contentContainerStyle={{ flex: 1 }}
        keyboardVerticalOffset={Platform.select({ ios: offset, android: 20 })}
        style={{ flexGrow: 1 }}
      >
```

Another thing to note: In the simulator, if I turn off the Keyboard popup (and therefore not triggering KeyboardAvoidingView), the text input also works as expected. 

There are certain configurations that would show my actual active text input towards the top of the page, and a shifted, inactive 'shadow' (I don't know how else to describe it) underneath. Maybe that has something to do with it?

![Show working without keyboard](https://user-images.githubusercontent.com/10620559/62551422-d3007e80-b820-11e9-96ae-4fb46b61a965.gif)

**Comment by dulmandakh** [comment]
Please use https://github.com/react-native-community/react-native-webview.

**Comment by connor-odoherty** [comment]
@dulmandakh Is this repo not responsible for maintaining KeyboardAvoidingView?

**Comment by dulmandakh** [comment]
Yes, but please check if issue persists with new webview. I'll re-open it.
