### ISSUE TITLE
if currentActivity is null, ReactModalHostView should throw an error

### ISSUE THREAD

**Issue by seanfreiburg** [facebook/react-native#25950]
React Native version:
React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
      Memory: 2.59 GB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.6.0 - /usr/local/bin/node
      Yarn: 1.15.2 - ~/.yarn/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 26, 28, 29
        Build Tools: 23.0.1, 26.0.3, 27.0.3, 28.0.1, 28.0.2, 28.0.3, 29.0.1
        System Images: android-21 | Google APIs Intel x86 Atom_64, android-23 | Intel x86 Atom, android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-28 | Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.3 => 16.8.6
      react-native: 0.60.4 => 0.60.4
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

## Steps To Reproduce

1. Preloading the RN bridge with LifeCycleState.RESUMED will cause modals to think getCurrentActivity is null
2. Workaround is to use LifeCycleState.BEFORE_RESUMED, but it should throw for better debugging on whats happening.

Describe what you expected to happen:
The modal code should throw an error if getCurrentActivity is null.

Snack, code example, screenshot, or link to a repository:

https://medium.com/@william.liu/preloading-react-native-bridge-2d9c109440a4

Here is an example of what happens. I was implementing something similar, and it took forever to debug why the modal wouldn't appear. A simple error if getCurrentActivity == null would save a lot of time and effort.

**Comment by seanfreiburg** [comment]
code is the same on HEAD https://github.com/facebook/react-native/blob/3b6f6ca4d5fcee6f1bc6d6242e3e2ef136e4d546/ReactAndroid/src/main/java/com/facebook/react/views/modal/ReactModalHostView.java

**Comment by dulmandakh** [comment]
Could you please create a PR to fix the issue, I would be happy to review it
