### ISSUE TITLE
Picker text color change only in android 9

### ISSUE THREAD

**Issue by nameer94** [facebook/react-native#25955]
Picker text color only work in android 9
other android versions the text is black
"react-native": "0.60.4"

```
<Picker
  selectedValue={"java"}
  style={{height: 50, width: 100, color: '#f00', backgroundColor: '#aaa'}}
  onValueChange={(itemValue, itemIndex) =>
    this.setState({language: itemValue})
  }>
  <Picker.Item label="Java" value="java" />
  <Picker.Item label="JavaScript" value="js" />
</Picker>
```

**Comment by nameer94** [comment]
by the way `react-native info` does not show React Native version: section
It only show this:
```
System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz
    Memory: 1.06 GB / 7.90 GB
  Binaries:
    Node: 11.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.7.0 - C:\Program Files\nodejs\npm.CMD
```

**Comment by bhaskarGyan** [comment]
@nameer94 Picker is deprecated and moved to https://www.npmjs.com/package/@react-native-community/picker

Check this out https://github.com/facebook/react-native/pull/25899

I was also facing the same issue after upgrade to RN v0.60 with Picker. Using @react-native-community/picker solved the issue

**Comment by danieljgp2** [comment]
@bhaskarGyan Im getting an error when i try to use @react-native-community/picker.

The error says, Tried to register two views with the same name AndroidDropdownPicker.
