### ISSUE TITLE
AsyncStorage and Facebook SDK conflicts

### ISSUE THREAD

**Issue by mingxin-yang** [facebook/react-native#25951]
```
_bootstrapAsync = async () => {
    const userId = await AsyncStorage.getItem('userId');
    console.log(userId);
    // This will switch to the App screen or Auth screen and this loading
    // screen will be unmounted and thrown away.
    this.props.navigation.navigate(userId ? 'App' : 'Auth');
  };
```
On Android, I can't got the useId value after add Facebook SDK into my project, I guess that because the Facebook SDK initialization slower in china. 
React Native version:

v0.59.10
## Steps To Reproduce

1.
2.

Describe what you expected to happen:
I can get the local value

Snack, code example, screenshot, or link to a repository:

**Comment by dulmandakh** [comment]
Please use https://github.com/react-native-community/async-storage, and please provide demo code if issue persists. Thank you
