### ISSUE TITLE
RN.Linking.openURL does not pre-populate SMS message body 

### ISSUE THREAD

**Issue by pawlowskim** [facebook/react-native#25952]
This is re-opened bug from https://github.com/facebook/react-native/issues/23992. The same behaviour, but on Motorola g(6) play, android 9. It works or second test device with android 8 (honor).

React Native version:
```
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
      Memory: 1.41 GB / 32.00 GB
      Shell: 3.2.57
    Binaries:
      Node: 10.15.3
      npm: 6.4.1
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 25, 26, 28
        Build Tools: 27.0.3, 28.0.3
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.10 => 0.59.10
```

## Steps To Reproduce

1. Linking.openUrl(`sms:${phone}?sms_body=${body}`);

Describe what you expected to happen:
It should pre populate SMS body content.

Investigation:
Quick look for Linking library and I saw it uses "ACTION_VIEW" intent for each intent. It might be the case, since android doc says it should be one of: ACTION_SENDTO, ACTION_SEND or ACTION_SEND_MULTIPLE. Manually triggered intent from adb with ACTION_SENDTO works as expected. Maybe it was different for older android version and that why it sometimes works and sometimes doesn't.

**Comment by GabrielCoding98** [comment]
Been working on this same issue seems to not pre-populate via Google Messenger. It only worked when I specified the phone number.

**Comment by pawlowskim** [comment]
Don't listen the bot, update to v 0.60 is not that trivial if you use custom libraries. But from this version you can use sendIntent directly from Linking library, and this should work as expected: https://facebook.github.io/react-native/docs/linking#sendintent (not tested). For iOS keep sms link:
```
sms:phoneNumber&body=message
```

**Comment by soledaddiez** [comment]
Still happening in RN v0.60.4

**Comment by pawlowskim** [comment]
> Still happening in RN v0.60.4

Use sendIntent for android with 
```ACTION_SENDTO```
and
```sms_body```
as extra param. It should work as expected.

https://developer.android.com/guide/components/intents-common#SendMessage

**Comment by soledaddiez** [comment]
Hi @pawlowskim, 
Thanks for your help.
I don't seem to get it to work. Lost in how to send all the params to the Linking.sendIntent.
sms: _phone-number_
sms_body: _message_

Could you help me here?.

**Comment by pawlowskim** [comment]
Try this (not tested)
```
Linking.sendIntent("ACTION_SENDTO", [{key:"sms_body", value:"message"}]);
```

You can also try without "ACTION" prefix, idk what is the implementation of it under the hood. Guys could provide at least one example for usage and it would be clear.

**Comment by sshmyg** [comment]
Try to open link `Linking.openUrl('sms:0971234567&body=Test')` and get 
![image](https://user-images.githubusercontent.com/1410608/65027211-9b6a1380-d942-11e9-8b24-5d43eb58efd3.png)

Linking open not exact message but just list of messages.

React native version `0.61.0-rc.0`

**Comment by namvoeh** [comment]
you can use `Linking.openUrl(smsto:${phone}?sms_body=${body})` instead of `Linking.openUrl(sms:${phone}?sms_body=${body})`

**Comment by zPhong** [comment]
try this : sms://${number}/${Platform.OS === 'ios' ? '&' : '?'}body=${encodeURIComponent(body)}
