### ISSUE TITLE
Flex wrapped items act unexpectedly ONLY in web view

### ISSUE THREAD

**Issue by dnorth** [facebook/react-native#25965]
React Native version:
Expo version `34.0.1` which uses react-native `0.59.8`

## Steps To Reproduce

1. See related snack - https://snack.expo.io/B13SVavQH

Describe what you expected to happen:

Items that are wrapped should be grouped closely together based on layout.
If you run the "Android" or "iOS" version you can see that what is shown there is the expected behavior. So this seems to only happen in the web version of the application.

**Comment by dulmandakh** [comment]
React Native doesn't support Web, please report the issue to expo or react-native-web.
