### ISSUE TITLE
Filtering a list item breaks rendering

### ISSUE THREAD

**Issue by mulholio** [facebook/react-native#25962]
#### Versions
expo: 33.3
react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz

## Steps To Reproduce

1. Render a list of components
2. Filter one of them out and re-render
3. The height on the array of rendered components then collapses

This is the code which renders the list:
```javascript
{articles.filter(filterRead).map(article => (
  <GuideItem
    article={article}
    key={article.pageProperties.id}
    onPress={() => {
      navigation.navigate('Guide', { article })
    }}
  />
))}
```

https://www.loom.com/share/ecbaed9a273f4fcc8decf0b682ce5322

## Describe what you expected to happen:
The item is simply removed and all items retain their prior height

---

https://github.com/facebook/react-native/issues/16183 seems to also reference this issue, although I am not using a FlatList; the problem seems more general than that. I managed to follow the workaround suggested there and manually add a height to fix the issue. However, I wanted to post this issue for any other users who needed items of differing height.

Apologies for not providing a reproduction; my setup is fairly involved atm.

**Comment by dulmandakh** [comment]
Please use FlatList https://facebook.github.io/react-native/docs/flatlist
