### ISSUE TITLE
Unhandled JS Exception: Module AppRegistry is not a registered callable module (calling runApplication)

### ISSUE THREAD

**Issue by guaiguaimao** [facebook/react-native#25966]
### the project can work when React Native version is 0.57.8. But when I update React Native To 0.60.4,the project can not work

Expected a constructor.
RCTLog.js:47 Running application SmartClubRNProject ({
    initialProps =     {
    };
    rootTag = 71;
})
ExceptionsManager.js:94 Unhandled JS Exception: Module AppRegistry is not a registered callable module (calling runApplication)

### package.json
     "dependencies": {
        "@babel/plugin-proposal-decorators": "^7.4.4",
       "babel-preset-react-app": "^9.0.0",
       "dva-core": "^1.3.0",
       "dva-loading": "^2.0.6",
       "react": "16.8.6",
       "react-native": "0.60.4",
       "react-native-gesture-handler": "^1.3.0",
       "react-navigation": "^3.11.1",
       "react-navigation-redux-helpers": "^3.0.2",
        "react-redux": "^7.1.0"
     },
      "devDependencies": {
         "@babel/core": "^7.5.5",
         "@babel/runtime": "^7.5.5",
         "@react-native-community/eslint-config": "^0.0.5",
         "babel-eslint": "^10.0.1",
         "babel-jest": "^24.8.0",
         "babel-plugin-transform-decorators-legacy": "^1.3.5",
         "babel-preset-react-native": "^4.0.1",
         "eslint": "5.1.0",
         "eslint-config-fb-strict": "22.1.0",
         "eslint-config-fbjs": "2.0.1",
         "eslint-plugin-eslint-comments": "^3.0.1",
         "eslint-plugin-flowtype": "2.43.0",
         "eslint-plugin-jest": "21.8.0",
         "eslint-plugin-prettier": "2.6.0",
         "eslint-plugin-react": "7.8.2",
         "eslint-plugin-react-native": "3.5.0",
         "jest": "^24.8.0",
          "metro-react-native-babel-preset": "^0.55.0",
         "react-test-renderer": "16.8.6"
        },
###  .babelrc

> 

        {
        "plugins": [
         [
          "@babel/plugin-proposal-decorators",
          {
           "legacy": true
        }
        ],
       [
         "@babel/plugin-proposal-class-properties",
        {
          "loose": true
        }
        ]
       ],
        "presets": [
         "react-app"
       ]
    }
### entry index.js
      import React from "react";
      import { AppRegistry } from "react-native";
      import dva from "./utils/dva";
      import Router, { routerMiddleware, routerReducer } from "./test";
      import appModel from "./models/index";
       const app = dva({
        initialState: {},
        models: appModel,
        extraReducers: { router: routerReducer },
        onAction: [routerMiddleware],
        onError(e) {
        console.log("onError", e);
       }
     });
       const store = app.getStore();
       global.dvaStore = store;

       const App = app.start(<Router />);
       AppRegistry.registerComponent("HelloProject", () => App);
### dva.js
        import React from "react";
        import { create } from "dva-core";
        import { Provider, connect } from "react-redux";
        import createLoading from "dva-loading";
        export { connect };

        export default function(options) {
          const app = create(options);
          app.use(createLoading({}));
 
           if (!global.registered) {
          options.models.forEach(model => app.model(model));
          }
            global.registered = true;

           app.start();
          const store = app._store;

            app.start = container => () => <Provider store={store}>{container}</Provider>;
           app.getStore = () => store;
          return app;
          }
### test.js
       import React, { PureComponent, Component } from "react";
      import { connect } from "react-redux";
      import AppNavigator from "./navigation/AppNavigator";
       import {
           reduxifyNavigator,
             createReactNavigationReduxMiddleware,
            createNavigationReducer
         } from "react-navigation-redux-helpers";

       export const routerReducer = createNavigationReducer(AppNavigator);

         export const routerMiddleware = createReactNavigationReduxMiddleware(
          "root",
           state => state.router
          );

            const App = reduxifyNavigator(AppNavigator, "root");

          @connect(({ app, router }) => ({ app, router }))
          class Router extends (PureComponent || Component) {
             state = {};
             componentDidMount() {}
              componentWillUnmount() {}

            render() {
              const { dispatch, router } = this.props;
               return <App dispatch={dispatch} state={router} />;
          }
        }

          export default Router;

**Comment by guaiguaimao** [comment]
@ connect(({ myscore, loading }) => ({
        ...myscore,
       isLoad: loading.effects['myscore/getScoreTransaction'] || false
     }))
       class MyScoreSceen extends React.Component{
           ...
       }
       export default class MyScoreScreen
 ### Write above in a different way.Then this project can work
          class MyScoreSceen extends React.Component{
           ...
         }
        export default connect(({ myscore, loading }) => ({
            ...myscore,
             isLoad: loading.effects['myscore/getScoreTransaction'] || false
       }))(MyScoreScreen)

**Comment by dalaoque** [comment]
I have the same problem.

This is the way I want to write it.
```
import React from "react";
import { connect } from "react-redux";

@connect(({ global }) => ({
  name: global.name
}))
export default class extends React.PureComponent {...}
```

It looks like`export dafault` not supported by @babel/plugin-proposal-decorators.
Error reporting information:
```
Expected a constructor.
Module AppRegistry is not a registered callable module (calling runApplication).
Requiring module "index.js", which threw an exception: Error: Expected a constructor.
Unhandled JS Exception: Expected a constructor.
Unhandled JS Exception: Module AppRegistry is not a registered callable module (calling runApplication).
Unhandled JS Exception: Requiring module "index.js", which threw an exception: Error: Expected a constructor.
```
---
It works, but it's not the way I want it to work.
```
import React from "react";
import { connect } from "react-redux";

class Com extends React.PureComponent {...}

export default connect(({ global }) => ({
  name: global.name
}))(Com);
```

**Comment by yejing2017** [comment]
+1

**Comment by hubertngo** [comment]
+1
