### ISSUE TITLE
resolveAssetSource generates URLs that cannot be loaded after being normalized

### ISSUE THREAD

**Issue by mmerickel** [facebook/react-native#25961]
I'm using react-native-video and it's failing to load video files that are in a sibling folder to the app. The reason is that the path contains a `..` in it, which the Java-based Exoplayer is normalizing before issuing the HTTP request. You could argue this is an issue in the Exoplayer, but I think it's a larger issue with how react-native is generating the URLs in debug mode.

React Native version: 0.60.4

```
System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
    Memory: 486.23 MB / 32.00 GB
    Shell: 5.7.1 - /usr/local/bin/zsh
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.17.3 - ~/.nvm/versions/node/v10.16.0/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 23.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 27.0.0, 27.0.3, 28.0.3
      System Images: android-19 | Google APIs Intel x86 Atom, android-21 | Google APIs Intel
x86 Atom, android-23 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.4 => 0.60.4
```

## Steps To Reproduce

1. Define a monorepo with packages linked from sibling folders to the main app. For example:

```
repo
|- app1
   |- metro.config.js
   |- react-native.config.js
   |- index.js
|- app2
|- packages
   |- reusable-pkg
      |- index.js
      |- asset.mp4
      |- package.json
```

2. Generate a dev server asset via `const asset = require('reusable-pkg/asset.mp4')`.

3. Resolve the asset to a URL:

```
import resolveAssetSource from 'react-native/Libraries/Image/resolveAssetSource';
const src = resolveAssetSource(src)
```

4. Note `src.uri` contains a path with a `..` in it. For example: `http://10.0.2.2:8081/assets/../packages/reusable-pkg/asset.mp4?platform=android&hash=716f86674af0561aae7298e2f0c18de0`.

5. Pass the URI across the bridge to Java and normalize it via `java.net.URI(uri).normalize()` and note that the new url is `http://10.0.2.2:8081/packages/reusable-pkg/asset.mp4?platform=android&hash=716f86674af0561aae7298e2f0c18de0` without the `assets/..` included.

6. Load the URL using OkHTTP. Dev server returns a 404.

Describe what you expected to happen:

The asset URL should survive standard URL normalization so that it may be loaded reliably by the dev server.

Suggested fix:

Put the path in the URL as a query parameter instead of as part of the URL path. For example `http://10.0.2.2:8081/assets?path=../packages/reusable-pkg/asset.mp4&platform=android&hash=716f86674af0561aae7298e2f0c18de0`.

Without doing something like this, not all filesystem paths can be properly encoded into the structure of the URL path.

It should be noted that if you use a client that doesn't normalize the URL, the dev server does load it successfully:

```
$ curl -I --path-as-is 'http://localhost:8081/assets/../packages/reusable-pkg/asset.mp4'
HTTP/1.1 200 OK
X-Content-Type-Options: nosniff
Date: Tue, 06 Aug 2019 17:40:06 GMT
Connection: keep-alive
```

**Comment by foxnewsnetwork** [comment]
How are you serving your storybook app1? If you're serving from the project root, you'll need to do something like:

```zsh
node node_modules/react-native/local-cli/cli.js start --projectRoot='$PWD/app1' --watchFolders='$PWD'
```

or else metro gets confused with asset paths

**Comment by mmerickel** [comment]
I am serving from the app1 folder actually, to avoid sharing workspaces with both app1 and app2. This is why the '..' is in the URLs. The actual config is pasted below.

```js
const path = require('path');

module.exports = {
  // Ensure any imports inside the shared folders resolve to the local
  // node_modules folder
  resolver: {
    extraNodeModules: new Proxy({}, {
      get: (target, name) => path.resolve(__dirname, 'node_modules', name),
    }),
  },
  // Add our workspace roots so that react native can find the source code
  // for the included packages in the monorepo
  projectRoot: path.resolve(__dirname),
  watchFolders: [
    path.resolve(__dirname, '../packages'),
  ],
};
```

**Comment by mmerickel** [comment]
The below patch to metro fixes the issue for me, which I'm applying using patch-package.

```diff
diff --git a/node_modules/metro/src/Assets.js b/node_modules/metro/src/Assets.js
index d052449..730225a 100644
--- a/node_modules/metro/src/Assets.js
+++ b/node_modules/metro/src/Assets.js
@@ -249,7 +249,7 @@ function _getAssetData() {
     // use `path.join` since this will generate an incorrect URL path. In that
     // case we just concatenate the publicPath with the relative path.
     let assetUrlPath = localPath.startsWith("..")
-      ? publicPath.replace(/\/$/, "") + "/" + path.dirname(localPath)
+      ? publicPath.replace(/\/$/, "") + "/" + path.dirname(localPath).replace(/\.\./g, '@@')
       : path.join(publicPath, path.dirname(localPath)); // On Windows, change backslashes to slashes to get proper URL path from file path.
 
     if (path.sep === "\\") {
@@ -346,6 +346,7 @@ function _getAsset() {
     let platform =
       arguments.length > 3 && arguments[3] !== undefined ? arguments[3] : null;
     let assetExts = arguments.length > 4 ? arguments[4] : undefined;
+    relativePath = relativePath.replace(/@@/g, '..');
     const assetData = AssetPaths.parse(
       relativePath,
       new Set(platform != null ? [platform] : [])
```
