### ISSUE TITLE
Windows 10 build release apk with hermes

### ISSUE THREAD

**Issue by mezalejandro** [facebook/react-native#25975]
I can't build release apk with hermes enabled on windows 10

React Native version:

System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
    Memory: 5.61 GB / 15.94 GB
  Binaries:
    Node: 10.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.4.1 - C:\Users\ameza\AppData\Roaming\npm\npm.CMD
  SDKs:
    Android SDK:
      Android NDK: 18.1.5063045

## Steps To Reproduce

1. cd android
2. ./gradlew assembleRelease or bundleRelease

Describe what you expected to happen:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> A problem occurred starting process 'command '..\..\node_modules\hermesvm\win64-bin\hermes''

Snack, code example, screenshot, or link to a repository:

**Comment by AfrazHussain** [comment]
This issue is already been discussed in https://github.com/facebook/react-native/issues/25599. Please follow it up there. :)

**Comment by usmansbk** [comment]
Still not fixed in the latest release. Have to go back to manually updating `react.gradle` and using `hermes-engine`. 🙁😟

**Comment by mezalejandro** [comment]
with version 0.61.4 it is solved!
