### ISSUE TITLE
App freezes after invoking simple arm64 native library built with Gomobile 

### ISSUE THREAD

**Issue by pombeiro** [facebook/react-native#25970]
React Native version:
```
System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 345.02 MB / 15.42 GB
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 8.16.0 - ~/.nvm/versions/node/v8.16.0/bin/node
    Yarn: 1.13.0 - ~/.nvm/versions/node/v8.16.0/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.16.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

Initially reproduced with RN 0.59.10.

## Steps To Reproduce

1. Clone the sample repo at https://github.com/PombeirP/arm64-hang-repro-app;
  - The tip of the repo is based on 0.60.4. The previous commits use 0.59.10.
2. Set the `enableHang` boolean to `true` in https://github.com/PombeirP/arm64-hang-repro-app/blob/master/android/app/build.gradle#L122 and ensure you're not targetting Hermes;
3. Build and run the app (`yarn install --frozen-lockfile && react-native run-android`)
3.1. When the app is run in release mode, the hang may occur before the welcome screen has a chance to appear, and the app will display a blank screen;
3.2. Same thing in debug mode, but in that case you have an additional chance to reproduce the issue, by shaking the device and asking to reload the bundle. In that case the bundle will not reload as the app is frozen;

Describe what you expected to happen:

I'd expect that the app would behave the same way when deployed on a 64-bit device as on a 32-bit device (or using armeabi-v7a on a 64-bit device). The hang does not occur when Hermes is enabled, which leads me to believe that there is some bug in JSC or some interaction with the Gomobile-generated arm64 library (which is a simple 1-method library).

Snack, code example, screenshot, or link to a repository:

Repro app link: https://github.com/PombeirP/arm64-hang-repro-app

**Comment by dulmandakh** [comment]
What is your purpose of filtering architectures? App will hang because you filtered out required files.

**Comment by PombeirP** [comment]
This is only for ensuring that we don't include 32-bit binaries in an apk that will be run on a 64-bit phone. Granted, it's superfluous as Android will pick the 64-bit library. Have you tested and confirmed that it stops hanging if the architectures aren't filtered? In our production app we include everything except x86 and it still hangs, so I doubt that is the problem.

**Comment by dulmandakh** [comment]
Please use App Bundling if app size is your concern, works much better than
APK splitting and ABI filters.

>

**Comment by PombeirP** [comment]
Thanks for the tip @dulmandakh. Just to be clear, it seems unrelated to this issue, as it is not solved by removing ABI filters.

**Comment by dulmandakh** [comment]
Should I re-open the issue?

**Comment by PombeirP** [comment]
The issue wasn't closed.

**Comment by dulmandakh** [comment]
Sorry, I've been closing a lot of issues lately, and confused.

**Comment by sergioabril** [comment]
I'm experiencing what I think is a similar issue, but I have not been able to narrow down the cause / scenario. 

Project running on react 0.59.9, with a gomobile aar module loaded, hangs at a random time (if module is invoked, otherwise app keeps running, which led me to think it was caused by the module).

No apparent log message, no clear error, just freezes and stops logging ReactNativeJs messages to console. Sometimes I'm able to see some “worker/Job” related messages At the time of the freeze, but not sure if related.

**Comment by PombeirP** [comment]
I've been able to sidestep this issue by upgrading to RN 0.60 and enabling the Hermes engine.

**Comment by sergioabril** [comment]
I confirm that installing `React-Native-v8` (https://github.com/Kudo/react-native-v8) fixes the issue as well, probably in the same way than RN0.6.0+Hermes, but without upgrading RN.

I just did it, and problem no longer shows up. 
Still, feels like a bittersweet solution/workaround though.
