### ISSUE TITLE
OnPress triggers twice on Android TV.

### ISSUE THREAD

**Issue by NickAVolpe** [facebook/react-native#25979]
React Native version:
System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 376.00 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.3.1 - ~/.nvm/versions/node/v12.3.1/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.3.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      API Levels: 23, 24, 26, 28
      Build Tools: 28.0.2, 28.0.3
      System Images: android-23 | Google APIs ARM EABI v7a, android-Q | Android TV Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-create-library: 3.1.2

## Steps To Reproduce

1. Create a new app 'out of the box' with React Native CLI.
2. Add a TouchableOpacity, or Button element with an OnPress method to log to console.
3. Deploy to Android TV (I am using a physical Amazon FireStick device)
4. Observe the console log message happens twice.  

Describe what you expected to happen:
The OnPress method should only happen once. It should not have a duplicate event on Android TV Devices.  

Here is the code for the App I have replaced in the App.js:

```const App = () => {
  function handlePress() {
    console.log('TouchableOpacity press');
  }
  function handleBtnPress() {
    console.log('Button press');
  }
  return (
    <Fragment>
      <StatusBar barStyle="dark-content" />
      <SafeAreaView>
        <ScrollView
          contentInsetAdjustmentBehavior="automatic"
          style={styles.scrollView}
        >
          <Header />
          {global.HermesInternal == null ? null : (
            <View style={styles.engine}>
              <Text style={styles.footer}>Engine: Hermes</Text>
            </View>
          )}
          <View style={styles.body}>
            <TouchableOpacity activeOpacity={0.4} onPress={handlePress}>
              <View>
                <Text>Test Regular</Text>
              </View>
            </TouchableOpacity>
          </View>
          <Button title="button" onPress={handleBtnPress}>Button</Button>
        </ScrollView>
      </SafeAreaView>
    </Fragment>
  );
};```

**Comment by Rob2k9** [comment]
Your issue is with your on press it is being called when the component is rendered change your on press to 

`onPress={() => {handlePress}}`

and change your function to async to avoid any other issues

**Comment by fekajin** [comment]
i solve this issue with very simple way. there so many options to solve this but if you want, you can try mine.

```
state = { disabled: false };

logIn = () => {
    this.setState({
      disabled: true,
    });
    Actions.survey();
    setTimeout(() => {
      this.setState({
        disabled: false,
      });
    }, 200);
  };

<Button onPress={this.logIn} buttonStyle={styles.button} disabled={this.state.disabled}>
            Giriş Yap
          </Button>
```

**Comment by mtkopone** [comment]
@fekajin That's a terribly hackish way to fix the problem. See the referenced issue for a better way, or check the type property of the event object passed to the callback.

**Comment by dbarr33** [comment]
@NickAVolpe I am also seeing onPress get called twice on FireTv devices. Here is pr that just got approved that fixes the issue I was having. https://github.com/facebook/react-native/pull/26474

**Comment by DanielLe232** [comment]
In latest version is 0.61.2 is not source code from @dbarr33 
So i have added @dbarr33 code in my source with path "node_modules⁩ ▸ ⁨react-native⁩ ▸ ⁨Libraries⁩ ▸ ⁨Components⁩ ▸ ⁨Touchable⁩.js"
and I also implement some code to work around:
`this._tvEventHandler.enable(this, function (cmp, evt) {
      if (cmp.state.isDisable) {
        cmp.setState({ isDisable: false })
        return
      } else {
        cmp.setState({ isDisable: true })
      }

    });`

**Comment by euroclydon37** [comment]
I worked around it like this. I wanted to use a functional component with hooks, but `enable()` required a `this` argument, which makes me think it's expecting to be a part of a class.

```js
import React from 'react';
import { TouchableWithoutFeedback, View, TVEventHandler } from 'react-native';
import PropTypes from 'prop-types';

export default class Button extends React.Component {
  static propTypes = {
    ...TouchableWithoutFeedback.propTypes,
    activeStyle: PropTypes.object,
  };

  _tvEventHandler = null;

  _enableTVEventHandler = () => {
    this._tvEventHandler = new TVEventHandler();
    this._tvEventHandler.enable(this, (_, { eventType, eventKeyAction }) => {
      if (eventType === 'select' && !!eventKeyAction) {
        this.props.onPress();
      }
    });
  };

  _disableTVEventHandler = () => {
    if (this._tvEventHandler) {
      this._tvEventHandler.disable();
      delete this._tvEventHandler;
    }
  };

  state = { active: false };

  onFocus = () => this.setState({ active: true });
  onBlur = () => this.setState({ active: false });

  componentDidUpdate(_, prevState) {
    if (this.state.active && !prevState.active) {
      this._enableTVEventHandler();
    }

    if (!this.state.active && prevState.active) {
      this._disableTVEventHandler();
    }
  }

  componentWillUnmount() {
    this._disableTVEventHandler();
  }

  render() {
    const { onFocus, onBlur } = this;
    const { style, activeStyle, children, onPress: _, ...props } = this.props;
    const { active } = this.state;

    const containerStyle = active ? [style, activeStyle] : style;

    return (
      <TouchableWithoutFeedback onFocus={onFocus} onBlur={onBlur} {...props}>
        <View style={containerStyle}>{children}</View>
      </TouchableWithoutFeedback>
    );
  }
}

```

**Comment by DanielLe232** [comment]
@euroclydon37 In my idea, i will do
`if (eventType === 'select' && !!eventKeyAction) {
        this.props.onPress();
 }` ===>
`if (eventType === 'select' && eventKeyAction === 0) {
       // Just check key down
        this.props.onPress();
  }`
Remove this code
`componentDidUpdate(_, prevState) {
    if (this.state.active && !prevState.active) {
      this._enableTVEventHandler();
    }

    if (!this.state.active && prevState.active) {
      this._disableTVEventHandler();
    }
  }`

**Comment by tvanlaerhoven** [comment]
Alternatively, instead of using state changes, wrap TouchableOpacity or other touchables with a functional component and filter presses:

`import React from 'react';
import { Platform, TouchableOpacity } from 'react-native';
let TouchableOpacityTV = TouchableOpacity;

if (Platform.OS === 'android' && Platform.isTV) {
  const TouchableOpacityAndroidTV = props => {
    /** Make sure presses on AndroidTV are sent only once */
    onPressFilter = e => {
      const { onPress } = props;
      const { eventKeyAction } = e;
      if (onPress && eventKeyAction === 1 /*up trigger*/) {
        onPress(e);
      }
    }
    return <TouchableOpacity {...props} onPress={onPressFilter} clickable={false} />
  }
  TouchableOpacityTV = TouchableOpacityAndroidTV;
} 

export default TouchableOpacityTV;
`
