### ISSUE TITLE
Application really slow on simulator

### ISSUE THREAD

**Issue by justinhj** [facebook/react-native#2597]
When running react native on the iOS simulator (for example the Movies app) the frame rate is really slow. So slow that when I bring up the debug menu it takes about 5 seconds to come up and then none of the buttons can be clicked. Anyway else experiencing this issue? I updated to the latest react-native today as I noticed my own app was no longer possible to debug on the simulator and wondered if it was something I had done.

**Comment by ide** [comment]
You probably have Slow Animations turned on in the simulator.

**Comment by justinhj** [comment]
Yeah that was it thanks! (Command T toggles it)
