### ISSUE TITLE
value for fontSize cannot be cast from String to Double

### ISSUE THREAD

**Issue by Milankorangi** [facebook/react-native#25971]
value for fontSize cannot be cast from String to Double

React Native version: "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz"

Describe what you expected to happen:
i have defined fontSize by
fontSize: 17

**Comment by dulmandakh** [comment]
Please provide reproducible demo code. I'll re-open the issue once I receive demo code. Thank you
