### ISSUE TITLE
Android app crashes immediately on requesting permissions on Android Oreo (8)

### ISSUE THREAD

**Issue by javascripter** [facebook/react-native#25981]
On  some Android 8 devices, any permission request, not just location permission, immediately crashes the app, preventing apps requesting permissions on startup from being usable at all.

The crash happens on emulators with lower resolutions on Android 8, and some real devices with Android 8, including Huawei P20 Lite, Android 8. 

This issue from react-native-permissions may be a similar problem, in which no solution was provided:
https://github.com/react-native-community/react-native-permissions/issues/213

React Native version:
System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Memory: 1.62 GB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.0 - /usr/local/opt/node@10/bin/node
    Yarn: 1.12.3 - ~/.yarn/bin/yarn
    npm: 6.9.0 - /usr/local/opt/node@10/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 23, 26, 27, 28
      Build Tools: 26.0.3, 27.0.3, 28.0.2, 28.0.3
      System Images: android-26 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7

## Steps To Reproduce

1.
In Android Studio, create a virtual device with the following:

Name:
3.7 WVGA (Nexus One) API 28
Resolution: 480 x 800: hdpi
API:
26
Target:
Android 8.0 (Google APIs)
CPU/ABI
x86_64

<img width="1216" alt="Screen Shot 2019-08-08 at 12 32 18" src="https://user-images.githubusercontent.com/13040/62673237-9ecfbe00-b9d8-11e9-8197-4e1c369679b9.png">

2.
react-native run-android and run the app. The app crashes immediately on requesting the permission. Increasing the resolution in the emulator seems to prevent the crash from happening, but this crash happens on real devices too so increasing the resolution is not an option.

<img width="597" alt="Screen Shot 2019-08-08 at 12 24 12" src="https://user-images.githubusercontent.com/13040/62672943-76938f80-b9d7-11e9-84f7-dffd8589c385.png">

Describe what you expected to happen:
Permission Dialog will appear without crashing the app.

Snack, code example, screenshot, or link to a repository:

```typescript
import React, { useEffect } from 'react';
import {
  Text,
  PermissionsAndroid
} from 'react-native';
const App = () => {
  useEffect(() => {
    PermissionsAndroid.request(
      PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION
    )
      .then(granted => {
        console.log(granted);
      })
      .catch(err => {
        console.log('error requesting a location permission');
        console.log(err);
      });
  }, []);

  return (
    <Text>
      App crashes on some Android 8 devices when requesting permissions
    </Text>
  );
};

export default App;
```

```AndroidManifest.xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.permissionbugandroid">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>
```

**Comment by piRstone** [comment]
This happens to me too.
I discovered that when I remove the `async / await`, the prompt works and I can accept or deny the permission request. But when I set my method asynchronous again, the prompt appears but the app crashes immediately.
I however declared the `ACCESS_FINE_LOCATION` and `ACCESS_COARSE_LOCATION` permissions to the AndroidManifest.xml file.

I tried to delay the permission request to let the app load but it seems that the simple fact that the request is asynchronous crashes the app...

**Comment by javascripter** [comment]
> This happens to me too.
> I discovered that when I remove the `async / await`, the prompt works and I can accept or deny the permission request. But when I set my method asynchronous again, the prompt appears but the app crashes immediately.
> I however declared the `ACCESS_FINE_LOCATION` and `ACCESS_COARSE_LOCATION` permissions to the AndroidManifest.xml file.
> 
> I tried to delay the permission request to let the app load but it seems that the simple fact that the request is asynchronous crashes the app...

I tried removing the `catch` method call so that it only calls the `request` method, but the app still crashed.

**Comment by piRstone** [comment]
I will test https://github.com/react-native-community/react-native-permissions when I'll come back on with feature. I could say here if it changes something or not.
If you try this before me and it fixes your problem, tell it me!

**Comment by javascripter** [comment]
> I will test https://github.com/react-native-community/react-native-permissions when I'll come back on with feature. I could say here if it changes something or not.
> If you try this before me and it fixes your problem, tell it me!

We are using this module in our app. Unfortunately the same crash problem occurred, and it seems this module uses ReactNative's PermissionsAndroid internally for Android... Thanks for the suggestion, though.

This is the version we are using for our app (latest).
```
    "react-native-permissions": "^1.2.0",
```
