### ISSUE TITLE
PushNotificationIOS.checkPermissions() does not return partial permissions for "alert"

### ISSUE THREAD

**Issue by sorinns** [facebook/react-native#25980]
## Description
PushNotificationIOS.checkPermissions() returns "alert: false" 
even when iOS notifications alerts are partially enabled

There are three options under notifications->alerts in iOS settings
1. "Lock Screen"
2. "Notification Center"
3. "Banners"

.checkPermissions() returns "alert: true" or "alert: false" only based on the status of 3.
1. and 2. are ignored and returns "alert: false" no matter what if 3. is unchecked

React Native version: 0.59.1

## Steps To Reproduce

1. call PushNotificationIOS.checkPermissions() in your code
2. go to iOS settings and uncheck "Alert" -> "Banners" but leave "Lock Screen" and/or "Notification Center" checked

## Expected Behavior

PushNotificationIOS.checkPermissions() 
v1. 
return more infos, for example an object like 
{
alertLockScreen: bool, 
alertNotificationCenter: bool, 
alertBanners: bool, 
sound: bool, 
badge: bool, 
}

v2.
just return one bool value which is true if any of the above are true

**Comment by sorinns** [comment]
After some more research i did the following modifications to RTCPushNotificationManager.m in the PushNotificationIOS libray in order to also get the authorization status.

Not sure if this is the right way to do it though.

modified this 

`RCT_EXPORT_METHOD(checkPermissions:(RCTResponseSenderBlock)callback)
{
  if (RCTRunningInAppExtension()) {
    callback(@[@{@"alert": @NO, @"badge": @NO, @"sound": @NO}]);
    return;
  }

  NSUInteger types = [RCTSharedApplication() currentUserNotificationSettings].types;
  
  callback(@[@{
    @"alert": @((types & UIUserNotificationTypeAlert) > 0),
    @"badge": @((types & UIUserNotificationTypeBadge) > 0),
    @"sound": @((types & UIUserNotificationTypeSound) > 0),
  }]);
}`

with this

`RCT_EXPORT_METHOD(checkPermissions:(RCTResponseSenderBlock)callback)
{
  if (RCTRunningInAppExtension()) {
    callback(@[@{@"status": @NO,@"alert": @NO, @"badge": @NO, @"sound": @NO}]);
    return;
  }

  NSUInteger types = [RCTSharedApplication() currentUserNotificationSettings].types;
  
  __block bool status = YES;
  UNUserNotificationCenter *center = [UNUserNotificationCenter currentNotificationCenter];
  [center getNotificationSettingsWithCompletionHandler:^(UNNotificationSettings * _Nonnull settings) {
    if (settings.authorizationStatus != UNAuthorizationStatusAuthorized) {
      status = NO;
    } else {
      status = YES;
    }
    callback(@[@{
      @"status": @((status)),
      @"alert": @((types & UIUserNotificationTypeAlert) > 0),
      @"badge": @((types & UIUserNotificationTypeBadge) > 0),
      @"sound": @((types & UIUserNotificationTypeSound) > 0),
    }]);
  }];
}`

**Comment by dulmandakh** [comment]
Please create a PR to with the fix
