### ISSUE TITLE
[Bridge] View controller instances passed to RCTBridgeModuleProviderBlock in RCTBridge won't get deallocated

### ISSUE THREAD

**Issue by grittymindy** [facebook/react-native#2598]
I have a view controller, say TestViewController. It has a RCTRootView as the subview of 'self.view'. Since I need to communicate between my react-native views in JS and my TestViewController instance(0x001) in OC, I  passed the TestViewController instance(0x0001) to the RCTBridgeModuleProviderBlock when setting  up the RCTBridge for RCTRootView.

Everything works fine when I pushed a TestViewController instance. However, that instance won't get deallocated when it's been poped. 

What's the problem?

**Comment by grittymindy** [comment]
Also, the bridge backing up the RCTRootView in that view controller instance won't get deallocated either.

**Comment by brentvatne** [comment]
Thanks for the description! Can you post a small project to reproduce this? Or the code that you're describing?

**Comment by grittymindy** [comment]
I created a repository [here](https://github.com/grittymindy/VCAndRCTBridgeLeakDemo) to reproduce this problem.

**Comment by tadeuzagallo** [comment]
The array retains the controller reference, then you have a retain cycle.

You really shouldn't create the bridge from within a bridge module.

**Comment by grittymindy** [comment]
@tadeuzagallo    
* I returned a weak reference to the controller,  so I don't know why there's a retain cycle. Can you make this clear?
* If I shouldn't create the bridge from within a bridge module,  what should I do if I want to pass a specific controller instance to the bridge while exporting some native methods of the controller to JS side?   
Thanks.

**Comment by tadeuzagallo** [comment]
Okay, to the first question:
```objc
__weak typeof(self) weakSelf = self; // This doesn't increment the retainCount
NSArray *foo = @[weakSelf]; // This will call retain on the object, no matter if the previous reference was weak.
```

For the second problem, you can move whatever module logic you have in your controller to a separate module, if you need to access the controller, the module can have a weak reference to it. Alternatively you can store a reference to the bridge, and call `-[bridge invalidate]` on `viewDidDisappear`.

**Comment by grittymindy** [comment]
@tadeuzagallo You're right. I tried `[bridge invalidate]` and the controller can get deallocated. Thanks.
