### ISSUE TITLE
the app can't load from the metro bundler. 

### ISSUE THREAD

**Issue by samad324** [facebook/react-native#25993]
React Native and React version:
  "react": "16.8.6",
  "react-native": "0.60.4",

Environment Info:
  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i7-3540M CPU @ 3.00GHz
    Memory: 1.85 GB / 7.82 GB
  Binaries:
    Node: 12.7.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - C:\Users\abdul.samad\AppData\Roaming\npm\yarn.CMD
    npm: 6.10.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5692245
## Steps To Reproduce

1. react-native init myApp
2. cd myApp
3. react-native run-android

the app can't load from the metro bundler. 
stuck on this:

![image](https://user-images.githubusercontent.com/37283797/62763216-76ad9100-baa4-11e9-8183-22141302ff59.png)

**Comment by saxenanickk** [comment]
Any updates on this ? @samad324

**Comment by saxenanickk** [comment]
@samad324 I just removed the cli and installed it again.

`npm uninstall -g react-native-cli`
`npm install -g react-native-cli@latest`

It's a hack for now. I'll dig into it for sure.

**Comment by Mchtira** [comment]
Hi same issue here, the app build successfully but nothing happens in the metro bundler. 

react-native info :
```
System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 91.21 MB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.14.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.10.0 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
  IDEs:
    Android Studio: 3.3 AI-182.5107.16.33.5314842
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4
```


that happens after an upgrade of react-native from `59.10` to `60.4`

**Comment by samad324** [comment]
> @samad324 I just removed the cli and installed it again.
> 
> `npm uninstall -g react-native-cli`
> `npm install -g react-native-cli@latest`
> 
> It's a hack for now. I'll dig into it for sure.

still not working @saxenanickk

**Comment by samad324** [comment]
I found a work-around, open developer tool URL in your browser will start your bundler! just open `http://localhost:8081/debugger-ui/` in your browser

**Comment by saxenanickk** [comment]
@samad324 Check for AndroidManifest.xml in android/app/src/debug folder.
