### ISSUE TITLE
Task 'installDebug' not found in project ':app'. Some candidates are: 'installDevDebug', 'installQaDebug', 'installUaDebug'.

### ISSUE THREAD

**Issue by ldco2016** [facebook/react-native#25992]
React Native version:

```
System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 195.18 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.10.1 - /usr/local/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.7.0 - /usr/local/bin/npm
    Watchman: 4.7.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 26.0.2, 27.0.3, 28.0.3
      System Images: android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.5429.30.34.5452501
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.4 => 0.60.4
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
```

## Steps To Reproduce

1. git clone from repo: https://github.com/ldco2016/NFIBEngage
2. `npm install`
3. `react-native run-android`

Describe what you expected to happen:

For the `android` version of the app to continue to build as before when running `react-native run-android`

Snack, code example, screenshot, or link to a repository:

https://github.com/ldco2016/NFIBEngage

**Comment by dulmandakh** [comment]
I cloned the repo, and it builds just fine. It looks like you defined variants in build.gradle. Please check your config.

**Comment by ldco2016** [comment]
How did you run the build? `npm run build`? `cd android && gradle assembleRelease`?

**Comment by dulmandakh** [comment]
as you described: react-native run-android. It's app/build.gradle

**Comment by ldco2016** [comment]
I did have to add some `productFlavors` and I believe I did it according to https://developer.android.com/studio/build/build-variants#build-types:

```
apply plugin: "com.android.application"

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // https://facebook.github.io/react-native/docs/performance#enable-the-ram-format
 *   bundleCommand: "ram-bundle",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
    entryFile: "index.js",
    enableHermes: false,  // clean and rebuild if changing
]

apply from: "../../node_modules/react-native/react.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

/**
 * The preferred build flavor of JavaScriptCore.
 *
 * For example, to use the international variant, you can use:
 * `def jscFlavor = 'org.webkit:android-jsc-intl:+'`
 *
 * The international variant includes ICU i18n library and necessary data
 * allowing to use e.g. `Date.toLocaleString` and `String.localeCompare` that
 * give correct results when using with locales other than en-US.  Note that
 * this variant is about 6MiB larger per architecture than default.
 */
def jscFlavor = 'org.webkit:android-jsc:+'

/**
 * Whether to enable the Hermes VM.
 *
 * This should be set on project.ext.react and mirrored here.  If it is not set
 * on project.ext.react, JavaScript will not be compiled to Hermes Bytecode
 * and the benefits of using Hermes will therefore be sharply reduced.
 */
def enableHermes = project.ext.react.get("enableHermes", false);

def appName = "Engage";

/**
 * Get the version name from command line param
 *
 * @return int If the param -PversionName is present then return int value or -1
 */
def getAppName = { env ->
  return (env ? appName + " ("+ env + ")" : appName);
}

/**
 * Get the version name from command line param
 *
 * @return int If the param -PversionName is present then return int value or -1
 */
def getLauncher = { env ->
    return (env ? "engage-" + env + ".nfib.org" : "engage.nfib.org");
}

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "com.nfibengage"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://facebook.github.io/react-native/docs/signed-apk-android.
            signingConfig signingConfigs.debug
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    flavorDimensions "nfibengage"
    productFlavors {
      dev {
        dimension 'nfibengage'
        resValue "string", "app_name", getAppName("INT")
        resValue "string", "link_launcher", getLauncher("dv")
        applicationIdSuffix ".dv"
        manifestPlaceholders = [onesignal_app_id: "b78285eb-f1ec-46f3-9ad0-c7efe691a401",
                                onesignal_google_project_number: "584236827312"]
      }
      qa {
        dimension 'nfibengage'
        resValue "string", "app_name", getAppName("QA")
        resValue "string", "link_launcher", getLauncher("qa")
        applicationIdSuffix ".qa"
        manifestPlaceholders = [onesignal_app_id: "e4280f5e-62ec-41a4-bd86-f5b94e471a36",
                                onesignal_google_project_number: "162802054510"]
      }
      ua {
        dimension 'nfibengage'
        resValue "string", "app_name", getAppName("UA")
        resValue "string", "link_launcher", getLauncher("ua")
        applicationIdSuffix ".ua"
        manifestPlaceholders = [onesignal_app_id: "2ffd8dc0-9c6b-4035-999d-fc694194725a",
                                onesignal_google_project_number: "594905904045"]
      }
      prod {
        dimension 'nfibengage'
        resValue "string", "app_name", getAppName("")
        resValue "string", "link_launcher", getLauncher("prod")
        manifestPlaceholders = [onesignal_app_id: "82dcb42f-1d35-4b79-bc28-2d1d02dbda36",
                                onesignal_google_project_number: "601125149914"]
      }
    }

    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // https://developer.android.com/studio/build/configure-apk-splits.html
            def versionCodes = ["armeabi-v7a": 1, "x86": 2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }

        }
    }

    packagingOptions {
        pickFirst '**/armeabi-v7a/libc++_shared.so'
        pickFirst '**/x86/libc++_shared.so'
        pickFirst '**/arm64-v8a/libc++_shared.so'
        pickFirst '**/x86_64/libc++_shared.so'
        pickFirst '**/x86/libjsc.so'
        pickFirst '**/armeabi-v7a/libjsc.so'
    }
}

dependencies {
    implementation project(':react-native-device-info')
    implementation project(':appcenter-crashes')
    implementation project(':appcenter-analytics')
    implementation project(':appcenter')
    implementation project(':react-native-webview')
    implementation project(':react-native-immediate-phone-call')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.facebook.react:react-native:+"  // From node_modules

    if (enableHermes) {
      def hermesPath = "../../node_modules/hermesvm/android/";
      debugImplementation files(hermesPath + "hermes-debug.aar")
      releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
      implementation jscFlavor
    }
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)

```

**Comment by dulmandakh** [comment]
Yes, that why there is no installDebug but installDevDebug. Good luck

**Comment by ldco2016** [comment]
Well, to be clear I am not running `installDebug`, I just run `react-native run-android` same as you did when that error appears.

**Comment by dulmandakh** [comment]
react-native run-android runs installDebug in the background.

**Comment by ldco2016** [comment]
Ahh, so is there a flag I need to add so that it runs `installDevDebug` or one of the other flavors?

By the way I just did a `./gradlew installDevDebug` and that built successfully.

**Comment by SkariDamm** [comment]
Running ```./gradlew tasks``` before running ```react-native run-android``` again seemed to do the trick for me, for some reason.

**Comment by aaronyamil** [comment]
> Running `./gradlew tasks` before running `react-native run-android` again seemed to do the trick for me, for some reason.

Thanks @SkariDamm  my project is running

**Comment by mgoral2** [comment]
Hi guys.  I'm getting the same issue.  When I run "./gradlew tasks" I get a "./gradlew no such file or directory error.  Can you please provide more detail on how you run this?

**Comment by aaronyamil** [comment]
> Hi guys. I'm getting the same issue. When I run "./gradlew tasks" I get a "./gradlew no such file or directory error. Can you please provide more detail on how you run this?

Hi @mgoral2. I opened the **android folder** in AndroidStudio and to run the project. After that, you can use the **react-native CLI** without this errors.

**Comment by piatkiewicz** [comment]
@aaronyamil not work in my case

How do you run `./gradlew tasks`? Just pasting it in cmd causing error from @mgoral2 comment

**Comment by SkariDamm** [comment]
> Hi guys.  I'm getting the same issue.  When I run "./gradlew tasks" I get a "./gradlew no such file or directory error.  Can you please provide more detail on how you run this?

You might need to navigate to the android folder within your project.

**Comment by adhyrizaldy** [comment]
Nothing is worked, I am finished with that problem after I synced the gradle version that worked earlier in my system with the project gradle-wrapper-properties version.

**Comment by piatkiewicz** [comment]
I did everything from beginning  from this tutorial and it works now: https://reactnative.dev/docs/environment-setup

Earlier I was setting up with some YT tutorial which doesn't mention some steps

**Comment by raikk** [comment]
i had the same issue in fresh react-native project (`react-native init projectname`) after running `react-native start` then `react-native run-android` in VS code.
It is in `RN "0.62.1"`

Solution:-
i open Android Studio, then clean and rebuild.

I am not sure would it work after clean and rebuild.

i also did and gave the sdk path in root project
```
export ANDROID_HOME=/home/mycomputer/Android/Sdk/
export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
```
 
Then it work.

My npm version **6.7.0**
My Node version **v11.10.1**
**react-native-cli: 2.0.1
react-native: 0.62.1**

**Comment by aaronyamil** [comment]
Don't use the react-native cli, it doesn't work for now.
In the react native official page says: 

> Uninstall the react-native cli.

You have to use npx: **"npx react-native init name-project".**

Now my environment is working very well without android studio builds or cleans. Only with **npx react-native**

**Comment by nguyenhose** [comment]
I used `npx react-native init name-project`, but it still got error. Steps below worked for me.
Open Android Studio / Build / Make Project 
Run `px react-native run-android` again

**Comment by mundane140** [comment]
I was facing the same issue. 
Adding `ANDROID_HOME` environment variable and adding 'platform-tools' directory to `PATH` fixed the issue for me.

**Comment by hkthea** [comment]
when ./gradlew tasks only uninstallAll found, 
![WhatsApp Image 2020-04-10 at 09 22 25](https://user-images.githubusercontent.com/5879298/78965753-1e91c780-7b28-11ea-9b87-b6dbbd5fe110.jpeg)

**Comment by ajengrf** [comment]
@hkthea hi, i got the same issue. Have you solve the problem?

**Comment by hkthea** [comment]
yes @ajengrf it missed some api in API 28, so just reinstalled all SDK 28 make it solved.

**Comment by UsmanRana77** [comment]
Hey there!

I have solved this problem You just need to make 1 file in Android Folder so 

cd android 

Make file local.properties 

then just add this code in local.properties file:-

If MacBook then sdk.dir=/Users/username/Library/android/sdk

if Windows then sdk.dir=C:\\Users\\UserName\\AppData\\Local\\Android\\sdk

if Linux then sdk.dir = /home/USERNAME/Android/sdk

if you want to know what is your system USERNAME then just use command for Mac  whoami 

and then just rerun command react-native run-android

Thanks :)

**Comment by shubhamkakkar** [comment]
do ensure there exists a local.properties file in yout android foler ( MAC nd LINUX users only ) which contains the information regarding ur sdk location
sdk.dir = /home/shubham/Android/Sdk

**Comment by ViTess** [comment]
@UsmanRana77 @shubhamkakkar thanks! It works now

**Comment by jbdevelop** [comment]
The same problem here.
I put local.properties in ~/Android/Sdk and inside that 
sdk.dir = /home/julio/Android/Sdk.
I've restarted terminal and run:
npx react-native run-android
It doesn't work :(

**Comment by ajengrf** [comment]
I tried this:
1. Open android studio
2. Choose **open an existing android studio project**
3. Then open your project -> android folder
4. Click the AVD Manager on the top right screen
![Screen Shot 2020-04-24 at 10 45 10](https://user-images.githubusercontent.com/30023314/80173018-c1623f80-8618-11ea-8dc9-d662c90a6638.png)
5. Launch your virtual device
6. Run npx react-native run-android

**Comment by kaelsilva** [comment]
I'm actually using Ubuntu and I've acessed the _[Setting up the development environment](https://reactnative.dev/docs/environment-setup)_ and figured out that my environment variables were configured in my `.bashrc` file, but I switched to `.zshrc` recently and I had to write all the exports again inside the `.zshrc` file.
So if this problem happened recently and also you've changed from bash to zsh or something like that, check out the setup page of react-native and make sure that you do all the steps. Hope it helps someone.

**Comment by dineshpithiya1993** [comment]
thanks

**Comment by thijs-qv** [comment]
@kaelsilva Thanks! I just updated my Macbook a few days ago and the default shell was switched from bash to zshell. You definitely saved me some time.

**Comment by KrishnaraoDokka** [comment]
Hi Team,

Im getiing 'installDebug' issue while executing "react-native run-android". Please help me out.

**Comment by TheoGit** [comment]
I've tried all the above suggestions - still not working.

**Comment by YesSkyscrapers** [comment]
for me 
create file local.properties in /android/ folder
with sdk.dir=/Users/yes.skyscrapers/Library/Android/sdk
path to ur sdk

**Comment by tsanjoto** [comment]
can confirm @YesSkyscrapers's solution works for me.

**Comment by beevatsyu** [comment]
`export ANDROID_SDK_ROOT=~/Android/Sdk`
Solved the problem for me on Linux.

**Comment by joaopedromago** [comment]
Worked for me on Windows:

Using / instead of \ on sdk.dir. 

 `android/local.properties`
`sdk.dir=D:/Android/Sdk`

**Comment by NowApoca** [comment]
Working for me with writting local.properties file inside 'android' folder. 

Instead  /home/USERNAME/Android/sdk (Linux version), I put  /home/USERNAME/Android/Sdk

**Comment by Tang-xun** [comment]
I know ,  An  init project has different with opened AndroidStuido project is  **local.properties**
 
you only need create  local.properties 

**# touch android/local.properties**   & # **echo 'sdk.dir=/Users/*/Library/Android/sdk' >> android/local.properties** , 

**note**  : replace  android sdk with youself android  sdk path

**Comment by rdraisinghani** [comment]
I ran into same problem today. I had followed all the instructions on react native's [environment-setup](https://reactnative.dev/docs/environment-setup ) page. Turns out it that running the chocolatey command to install node, java and python2 had installed latest node js version (14) which is not supported by npm. I re-installed version 12 and created a new app using "npx react-native init MyApp". Thereafter on building using "npx react-native run-android" it built successfully and I was able to open it on an emulator.

**Comment by zjfresh** [comment]
For me, Task 'installDebug' not found happened when I use VSCode **NPM SCRIPTS** `android`, but it runs ok when I use a terminal with `npm run android` or `npx react-native run-android`.

The way mentioned  by @UsmanRana77 that create a file named **local.properties** with `sdk.dir=/Users/meitu/Library/android/sdk` helps the running in VSCode NPM SCRIPTS.

**Comment by EhsanSarshar** [comment]
`npx react-native doctor`
spot the issues and fix them

**Comment by anandchakru** [comment]
In my case I had to 

- add `C:\Users\myusername\AppData\Local\Android\Sdk\platform-tools` to my `PATH` in environment variables
- install jdk8 (`choco install jdk8`)
- change `JAVA_HOME` to point from 11 to 8
- accept licenses (`C:\Users\myusername\AppData\Local\Android\Sdk\tools\bin\sdkmanager --licenses` and y,enter few times)

and then _happy ending climax_ on `react-native run-android` command

**Comment by ajaymarathe9** [comment]
> Hey there!
> 
> I have solved this problem You just need to make 1 file in Android Folder so
> 
> Go android folder
> 
> Make file local.properties
> 
> then just add this code in local.properties file:-
> 
> If MacBook then sdk.dir=/Users/username/Library/android/sdk
> 
> if Windows then sdk.dir=C:\Users\UserName\AppData\Local\Android\sdk
> 
> if Linux then sdk.dir = /home/USERNAME/Android/sdk
> 
> if you want to know what is your system USERNAME then just use command for Mac whoami
> 
> and then just rerun command react-native run-android
> 
> Thanks :)

Very Helpful thanks :)

**Comment by engeslamadell** [comment]
I just opened the project on android studio and then ran react-native run-android and it works fine

**Comment by kaopath** [comment]
I fixed mine by running this command below.

react-native run-android --variant PRODUCTFLAVORDebug --appIdSuffix PRODUCTFLAVOR

**Comment by WebandMobileMaster** [comment]
After `gradlew app:installDebug` or `gradlew app:installDevDebug`, I got this same error.
help me.

**Comment by WebandMobileMaster** [comment]
> Ahh, so is there a flag I need to add so that it runs `installDevDebug` or one of the other flavors?
> 
> By the way I just did a `./gradlew installDevDebug` and that built successfully.
> 
> Ha! I just ran `react-native run-android --variant=DevDebug` and it also built successfully!
> 
> @dulmandakh , thank you for walking me through this. You shed light on some details I was not aware of.

I tried this but still, the same error has occurred.

**Comment by tuanpnUET** [comment]
@maletiger0404 
sorry I got some trouble. I did a cd android then ./gradlew installDevDebug and that built failed. 
**> Task :app:compileDevDebugJavaWithJavac FAILED
/Users/tuanpham/Documents/Amela/DemoApp/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:93: error: cannot find symbol
      new CodePush(getResources().getString(com.demoapp.R.string.CodePushDeploymentKey), getApplicationContext(), com.demoapp.BuildConfig.DEBUG),
                                                                ^
  symbol:   variable CodePushDeploymentKey
  location: class string
Note: /Users/tuanpham/Documents/Amela/DemoApp/android/app/src/debug/java/com/demoapp/ReactNativeFlipper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDevDebugJavaWithJavac'.**
what should I do? help me, please !
