### ISSUE TITLE
react-native 0.60.3 run on android9 is very slow

### ISSUE THREAD

**Issue by zxf107** [facebook/react-native#25995]
React Native version:

## Steps To Reproduce

1.
2.

Describe what you expected to happen:

Snack, code example, screenshot, or link to a repository:

**Comment by zxf107** [comment]
问题主要出现在华为和小米的android9.0版本的手机

**Comment by dulmandakh** [comment]
Please provide reproducible demo code. I'll re-open the issue once we have enough information. Thank you

**Comment by zxf107** [comment]
I found that the react naitve 0.60+ version of FlatList responded very slowly on android9. There is no such problem on android8. I have optimized it according to the optimization suggestions of FlatList, but the effect is limited. The packaged FlatList code is as follows:
import React from 'react';
import PropTypes from 'prop-types';
import {
  FlatList,
  Text,
  Image,
  StyleSheet,
  RefreshControl,
  ActivityIndicator,
  View
} from 'react-native';

import Theme from '../resource/Theme';

//issue: sometimes display blank before scroll
// https://github.com/facebook/react-native/issues/13316
const DEFAULT_THRESHOLD = 0.1;
const LOADING = Theme.colors.LOADING;
const { WINDOW_WIDTH, WINDOW_HEIGHT } = Theme.layoutSize;

export default class RefreshListView extends React.Component{
    constructor(props) {
        super(props);
        this.renderRefreshControl = this.renderRefreshControl.bind(this);
        this._onRefresh = this._onRefresh.bind(this);
        this._onEndReached = this._onEndReached.bind(this);
        this._renderItem = this._renderItem.bind(this);
        this._renderFooter = this._renderFooter.bind(this);
        this._renderHeader = this._renderHeader.bind(this);
        this._renderSeparator = this._renderSeparator.bind(this);
        this._renderHolder = this._renderHolder.bind(this);
        // this._getItemLayout = this._getItemLayout.bind(this);
    }
    componentWillMount() {

    }

    componentDidMount() {

    }
    _onRefresh() {
        this.props.onRefresh && this.props.onRefresh();
    }
    _onEndReached() {
        if (!this.onEndReachedCalledDuringMomentum) {
            this.props.onEndReached && this.props.onEndReached();
            this.onEndReachedCalledDuringMomentum = true;
        }
    }
    _scrolled = () => {
        if(this.props.onScroll){
            this.props.onScroll();
        }else{
            this.setState({scrolled:true});
        }
    }
    renderRefreshControl() {
        return (
            <RefreshControl
              refreshing={this.props.refreshing}
              onRefresh={this._onRefresh}
              tintColor={LOADING}
              title="Loading..."
              titleColor={LOADING}
              colors={[LOADING,'white']}
              progressBackgroundColor={'white'}
            />
        );
    }
    _renderSeparator = () => {
        if (this.props.renderSeparator) {
            return this.props.renderSeparator();
        } else {
            return null;
        }
        // return <View style={{width:WINDOW_WIDTH,height:CommonStyle.layoutSize.HAIRLINE,backgroundColor:'grey'}}/>;
    }
    _renderHeader = () => {
        if (this.props.renderHeader) {
            return this.props.renderHeader();
        } else {
            return null;
        }
    }
    _renderFooter = () => {
        if (this.props.renderFooter) {
            return this.props.renderFooter();
        } else {
            if (!this.props.data.length && !this.props.noHolder) {
                return this._renderHolder();
            } else {
                return null;
            }
        }
    }
    _renderHolder = () => {
        if (this.props.renderHolder) {
            return this.props.renderHolder();
        } else {
            return (
                <View style={styles.holder}>
                    <Image source={require('../resource/images/page_default.png')} style={styles.holderImg}/>
                </View>
            );
        }
    }

    _renderItem = (item) => {
        if (this.props.renderItem) {
            return this.props.renderItem(item);
        }else{
            return null;
        }
    }

    /**
     * length: 是被渲染 item 的高度。
     * offset(偏移量)
     * 注意如果你指定了ItemSeparatorComponent，请把分隔线的尺寸也考虑到 offset 的计算之中。
     */     
    _getItemLayout = (data, index) => (
        {length: this.props.item_height, offset: this.props.item_height * index, index}
    )

    render(){
        return(
            <FlatList
                onScroll={this.props.onScroll}
                style={[this.props.style,{width:WINDOW_WIDTH}]}
                onEndReachedThreshold={DEFAULT_THRESHOLD}
                removeClippedSubviews={true}
                getItemLayout={this._getItemLayout}
                showsVerticalScrollIndicator={false}
                showsHorizontalScrollIndicator={false}
                data={this.props.data}
                refreshControl={this.renderRefreshControl()}
                keyExtractor={(item, index) => 'listview' + index}
                ItemSeparatorComponent={this._renderSeparator}
                ListHeaderComponent={this._renderHeader}
                ListFooterComponent={this._renderFooter}
                renderItem={this.props.renderItem}
                onEndReached={this._onEndReached}
                onMomentumScrollBegin={() => { this.onEndReachedCalledDuringMomentum = false; }}
                maxToRenderPerBatch={5}
                maxToRenderPerBatch={20}
                windowSize={10}
                />
        );
    }
}
