### ISSUE TITLE
PushNotificationIOS 'register' fired every time the App is launched

### ISSUE THREAD

**Issue by edo1493** [facebook/react-native#2600]
The Doc says: 

" Fired when the user registers for remote notifications. The handler will be invoked with a hex string representing the deviceToken."

but this event is fired every time the Notifications are turned on in iPhone>Settings>App and the app is launched. This shouldn't be the case. 

Has anyone stumbled across this issue? 

I was thinking to make a call to check permissions inside the 'register' handler, but this is just a turnaround.

**Comment by ide** [comment]
This sounds like the docs are wrong. Apple says the app should be re-registering every time it is started so you get the freshest device token.

**Comment by edo1493** [comment]
I thought the device token would change for every install?

**Comment by ide** [comment]
Not necessarily:

> Device tokens can change, so your app needs to reregister every time it is launched.

> Moreover, never cache a device token and give that to your provider; always get the token from the system whenever you need it.

https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/IPhoneOSClientImp.html#//apple_ref/doc/uid/TP40008194-CH103-SW2

**Comment by brentvatne** [comment]
@edo1493 - let me know if this is not solved to your satisfaction and we can reopen the issue :smile:

**Comment by niftylettuce** [comment]
thanks for this!
