### ISSUE TITLE
Rename TextInput prop "autoCompleteType" to "autoComplete"

### ISSUE THREAD

**Issue by necolas** [facebook/react-native#26003]
PR https://github.com/facebook/react-native/pull/21575 added support for "autoComplete", based on the web standard, but implemented it under the prop name "autoCompleteType". We should rename this prop to "autoComplete"

**Comment by dulmandakh** [comment]
@cassiozen could you please answer the question

**Comment by necolas** [comment]
The issue has not been fixed yet

**Comment by RWOverdijk** [comment]
Bump. What's the status of this, will it be aligned?

**Comment by simon-abbott** [comment]
It looks like this was implemented in 27fec9569e08a04e0dbdbd5de063a599ad0416fa, and can be closed.

**Comment by OrkhanAlikhanov** [comment]
This should be closed as stated by @simon-abbott

**Comment by necolas** [comment]
Thanks!
