### ISSUE TITLE
URL with base is always used, even when absolute URL is provided

### ISSUE THREAD

**Issue by phallguy** [facebook/react-native#26006]
MDN [documentation for URL](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL) states that the `base` should only be used when `url` is a relative url. However the [current implementation of URL](https://github.com/facebook/react-native/blob/0ccedf3964b1ebff43e4631d1e60b3e733096e56/Libraries/Blob/URL.js#L131) (as of 0.60.4) in react-native _always_ prepends the base if given.

React Native version:

System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 447.55 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.6.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.9.0 => 16.9.0
    react-native: 0.60.4 => 0.60.4
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Steps To Reproduce

```javascript
const url = new URL("http://github.com", "http://google.com")
console.log(url.toString()) // => "http://google.comhttp://github.com"
```

Describe what you expected to happen:

```javascript
const url = new URL("http://github.com", "http://google.com")
console.log(url.toString()) // => "http://github.com"
```

Snack, code example, screenshot, or link to a repository:

https://snack.expo.io/@phallguy/url-bug-report

Notice that if you view the snack with the "Web" preview, it is handled correctly.

**Comment by phallguy** [comment]
Related to https://github.com/facebook/react-native/issues/16434

**Comment by jeswinsimon** [comment]
Would [this](https://github.com/jeswinsimon/react-native/blob/update_url_impl/Libraries/Blob/URL.js) be a valid fix for this?

**Comment by phallguy** [comment]
Yes that looks like it would probably do the trick.

**Comment by jeswinsimon** [comment]
Ok. I will open a PR then.

**Comment by phallguy** [comment]
Unfortunately, I think the proposed change is going to break access to localhost. See #26019

**Comment by jeswinsimon** [comment]
> Unfortunately, I think the proposed change is going to break access to localhost. See #26019

This is because the current [validateBaseUrl](https://github.com/facebook/react-native/blob/0ccedf3964b1ebff43e4631d1e60b3e733096e56/Libraries/Blob/URL.js#L108) expects a base url to be of the format `domain-name.extension`. I have proposed a [fix](https://github.com/facebook/react-native/issues/26019#issuecomment-520201075) in #26019
