### ISSUE TITLE
'unsupported BodyInit type' when Enable JS Debugging RN 5.9.1

### ISSUE THREAD

**Issue by eikhunter** [facebook/react-native#26000]
I recently upgraded to RN 5.9.1 with no issue running builds on both android or ios, but when selecting Remote JS Debugging the whatwg-fetch.js errs with all requests made in the app so I can't load any of the content from my api

Uncaught Error: unsupported BodyInit type
    at Response.Body._initBody (whatwg-fetch.js:279)
    at new Response (whatwg-fetch.js:450)
    at XMLHttpRequest.xhr.onload (whatwg-fetch.js:500)
    at XMLHttpRequest.wrapped (raven.js:377)

  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
      Memory: 140.25 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.2 - ~/.nvm/versions/node/v10.16.2/bin/node
      Yarn: 1.16.0 - ~/.yarn/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.2/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        Build Tools: 28.0.2, 28.0.3, 29.0.2
        API Levels: 28
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: 16.4.1 => 16.4.1
      @types/react-native: ^0.56.14 => 0.56.24
      react: 16.8.3 => 16.8.3
      react-native: 0.59.1 => 0.59.1

## Steps To Reproduce
1. Load up the application
2. Open developer tools
3. Select Enable Remote JS Debugging
4. Make a request to the api
The bundler works correctly and the app loads up on the phone but hangs on any fetch results.
The request has successfully been complete in the network tab, but the app doesn't proceed further because of the error.

Describe what you expected to happen:
The fetch request is completed and the console doesn't err so I can debug in inspect.

**Comment by dulmandakh** [comment]
Please provide reproducible demo code.

**Comment by eikhunter** [comment]
I can't reproduce a working example, but I think it's related to - https://github.com/facebook/react-native/issues/18818, I just recently upgraded to 59.1, which was never fixed and seems a few other people are having issues as well - https://github.com/jhen0409/react-native-debugger/issues/209
