### ISSUE TITLE
TextInput repeats/duplicates output to onChangeText, ignores autoCompleteType attribute [have included workaround]

### ISSUE THREAD

**Issue by fightwithcrayon** [facebook/react-native#26013]
On Android, the TextInput field's autocomplete cannot be disabled and the suggested input conflicts with the onChangeText event, resulting in duplicated input.

This is verified on Pixel3 and Samsung Galaxy S7 Edge.

WORKAROUND: Adding the `keyboardType="visible-password"` attribute will forcibly disable autocomplete. `onChangeText` output will be accurate.

React Native version:
``    OS: macOS 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 74.07 MB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4``

## Steps To Reproduce

1. Create a TextInput field, set `value` to a state variable, onChangeText to a setter for that variable. Set `autoCompleteType` to "off".
2. On an Android device, input text. You will notice unwanted input occurs. Search suggestions are still appearing.
3. Add `keyboardType="visible-password"` attribute to TextInput field. Search suggestions are disabled and onChangeText output is accurate.

Unfortunately do not currently have time to provide a full code sample, but wanted to share as have seen similar bug reports on here and have discovered a functional workaround for the time being.

Thanks

**Comment by ruthmckeever** [comment]
Is there any update on this?
I am having the same issue but the workaround breaks it for iOS.

**Comment by gogoku** [comment]
@ruthmckeever  I was having a similar issue in Android.
below was the setup

Container Screen => Login Screen => Input Component => React native's TextInput

as  user types i saved the data into a reducer, The problem was Container Screen and Login Screen were connected to same reducer because of which Container Screen was re-rendering and was causing this issue,
I decoupled it and issue was resolved
