### ISSUE TITLE
Bug: Can't  get merchant ID  on IOS simulator after Updating Xcode

### ISSUE THREAD

**Issue by Alekseyideas** [facebook/react-native#26011]
React Native version: 0.59.8

## Steps To Reproduce

1. After updating Xcode to 10.3 can't get a merchant id on IOS simulator, but on real device it works well. I tried to work with react-native-payments and tipsi-stripe but I had the same Error:  Possible Unhandled Promise Rejection (id: 0). It's happened when I try to pay

Snack, code example, screenshot, or link to a repository:
<img width="950" alt="Screenshot at Aug 10 11-45-37" src="https://user-images.githubusercontent.com/20225006/62819893-69f07200-bb64-11e9-81f1-24464496a99b.png">

**Comment by dulmandakh** [comment]
It looks like an issues related to react-native-payments or tipsi-stripe. Please file an issue there.
