### ISSUE TITLE
URL cannot handle "localhost" domain for base url

### ISSUE THREAD

**Issue by phallguy** [facebook/react-native#26019]
URL constructor raises a TypeError when using `localhost` as the base url.

React Native version:

System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 4.55 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.6.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.9.0 => 16.9.0
    react-native: 0.60.4 => 0.60.4
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Steps To Reproduce

```javascript
new URL("/home", "http://localhost:3000").toString() // TypeError invalid base URL
```

Describe what you expected to happen:

```javascript
new URL("/home", "http://localhost:3000").toString() // "http://localhost:3000/home"
```

Snack, code example, screenshot, or link to a repository:

https://snack.expo.io/@phallguy/e6bc36

**Comment by jeswinsimon** [comment]
The current regex in [validateBaseUrl](https://github.com/facebook/react-native/blob/0ccedf3964b1ebff43e4631d1e60b3e733096e56/Libraries/Blob/URL.js#L108) expects a base url to be of the format `domain-name.extension`.

I am not sure if the right solution is to accept all domains without domain extension or simply grant an exception for `localhost`. If it is the later then updating the regex to below will work.

`/^(?:(?:(?:https?|ftp):)?\/\/)(?:(?:[1-9]\d?|1\d\d|2[01]\d|22[0-3])(?:\.(?:1?\d{1,2}|2[0-4]\d|25[0-5])){2}(?:\.(?:[1-9]\d?|1\d\d|2[0-4]\d|25[0-4]))|(?:(?:[a-z\u00a1-\uffff0-9]-*)*[a-z\u00a1-\uffff0-9]+)(?:\.(?:[a-z\u00a1-\uffff0-9]-*)*[a-z\u00a1-\uffff0-9]+)*(?:\.(?:[a-z\u00a1-\uffff]{2,}))|(?:localhost))(?::\d{2,5})?(?:[/?#]\S*)?$/i`

**Comment by phallguy** [comment]
Bare hosts are certainly valid URLs and accepted by URL in the browser.

```javascript
new URL("/home", "http://phallguy").toString() // => http://phallguy/home
```

I don't really know why there's a custom-built URL for react-native so don't know if there are other issues to consider. Personally, I would expect feature parity with browser URL.

**Comment by jeswinsimon** [comment]
> Bare hosts are certainly valid URLs and accepted by URL in the browser.

If that is the case then I think the below will be a better solution

`^(?:(?:(?:https?|ftp):)?\/\/)(?:(?:[1-9]\d?|1\d\d|2[01]\d|22[0-3])(?:\.(?:1?\d{1,2}|2[0-4]\d|25[0-5])){2}(?:\.(?:[1-9]\d?|1\d\d|2[0-4]\d|25[0-4]))|(?:(?:[a-z\u00a1-\uffff0-9]-*)*[a-z\u00a1-\uffff0-9]+)(?:\.(?:[a-z\u00a1-\uffff0-9]-*)*[a-z\u00a1-\uffff0-9]+)*(?:\.(?:[a-z\u00a1-\uffff]{2,}))?)(?::\d{2,5})?(?:[/?#]\S*)?$`

**Comment by AntonioErdeljac** [comment]
Bare hosts are accepted in WHATWG URL API as well, so I think it would make sense to allow it in React Native's URL constructor. https://nodejs.org/api/url.html#url_the_whatwg_url_api

If someone is having problems finding a workaround **url-parse** package can be of help: https://www.npmjs.com/package/url-parse

**Comment by charpeni** [comment]
Y'all probably want to check this https://github.com/facebook/react-native/pull/25719.

**Comment by jeswinsimon** [comment]
@charpeni Thanks! This clears up a lot of my queries about why and how `URL` is implemented in React Native. I will close the PR #26050 once #25719 is resolved. Leaving it open just in case.

**Comment by charpeni** [comment]
👋 You should check this out: https://github.com/charpeni/react-native-url-polyfill.
