### ISSUE TITLE
loadImageWithURLRequest fails when using share extension

### ISSUE THREAD

**Issue by ramon90** [facebook/react-native#26014]
```
_bridge.imageLoader loadImageWithURLRequest:imageRequest
```
fails when calling it from a share extension for images captured by camera. I noticed it works for downloaded images.

React Native version:
System:
    OS: macOS 10.14.4
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 808.39 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 26.0.3, 27.0.3, 28.0.2, 28.0.3
      System Images: android-27 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.2/10E125 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.3 => 16.8.3 
    react-native: ^0.60.4 => 0.60.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1
## Steps To Reproduce

1. From a share extension on ios, call any method that calls the above code, for example `ImageEditor.cropImage()` calls `_bridge.imageLoader loadImageWithURLRequest:imageRequest` during cropping, or `ImageResizer.createResizedImage()` (react-native-image-resizer) also calls that code. 

Describe what you expected to happen:
`_bridge.imageLoader loadImageWithURLRequest:imageRequest` should not fail

For days, I have been trying to find what could be the problem without any success. I tried copying the image to a path on the app group directory, but still did not work.

Any help is appreciated.

**Comment by ramon90** [comment]
I updated to the latest version, and the issue still exists

**Comment by jeswinsimon** [comment]
@ramon90 Could you post a more detailed code snippet for this issue?

**Comment by Lichwa** [comment]
In my case the issue is that loadImageWithURLRequest is using absurd amount of memory, even for small images, thus exceeding share extension 120MB memory limit and throwing an out of memory exception.
