### ISSUE TITLE
Font weight on Android

### ISSUE THREAD

**Issue by PierreCapo** [facebook/react-native#26029]
Hello everyone,
I'd like to contribute and open a pull request for fixing an issue we have. Could I have your help about how to fix it?

Right now there is an inconsistency between iOS and Android for setting font weights (except for bold):
- On iOS, you can use `fontWeight: "black"`;
- On Android, you need to do `fontFamily: "MyFontFamily-Black"`;

We are currently investigating what would be the good way to fix this inconsistency in our codebase: 
- Should we tackle that by working on the native side, and implementing a getFontFamily function in [ReactBaseTextNode.java](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/text/ReactBaseTextShadowNode.java) file ? 
- Or should we work on the JavaScript side and change the font family according to the font weight for Android ?

What is the solution you would recommend ?
Thanks in advance

**Comment by mcuelenaere** [comment]
FYI: what we ended up doing, is creating a custom font XML and registering it with the ReactFontManager. See https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/text/ReactFontManager.java#L88 for more info

**Comment by Amirh24** [comment]
Hi,

right now I  see that fontWeight: "800" for example works on IOS and not on Android.
Is there a fix for this?

Thanks

**Comment by sourcecode911** [comment]
+1
