### ISSUE TITLE
LayoutAnimation causes crash on Android

### ISSUE THREAD

**Issue by mcrowe** [facebook/react-native#26020]
LayoutAnimation was causing our app to crash frequently on Android. I have created a very simple "Snack" which reproduces the crash reliably. I have confirmed the issue on 0.59.5, 0.60.4, and in Snack v33.0.0.

React Native version:
System:
    OS: macOS 10.14.3
    CPU: (4) x64 Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz
    Memory: 2.12 GB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.15.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      API Levels: 21, 22, 23, 25, 26, 27, 28
      Build Tools: 21.1.2, 22.0.1, 23.0.1, 25.0.1, 25.0.2, 26.0.1, 26.0.3, 27.0.3, 28.0.3
      System Images: android-19 | Google APIs Intel x86 Atom, android-21 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom, android-23 | Intel x86 Atom, android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.5429.30.34.5452501
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.4 => 0.60.4
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-fs: 2.5.1
    react-native-git-upgrade: 0.2.7

## Steps To Reproduce

1. Load the Snack at https://snack.expo.io/HyS1502QS
2. Choose "Android" and "Tap to Play"
3. Tap items "1", then "3", then "5".
4. Tap "CLEAR"

**Expected result:** 
I should see items "2", "4", "6", "7" slid to the top of the screen.

**Actual result:** 
I see only items "6" and "7" with empty space above them.

Now, continuing

5. Tap items "6" and "7"
6. Tap "CLEAR"

**Expected result:** 
I should see all items cleared.

**Actual result:** 
The app crashes.

This example code emulates a "todo" app, where items can be marked as complete, and then completed items are cleared. It seems that LayoutAnimation may get confused when multiple views are removed at the same time? Note that the example works as expected on iOS, and on Android without using LayoutAnimation.

Snack, code example, screenshot, or link to a repository:

Snack, as provided above: https://snack.expo.io/HyS1502QS

Here is a video demonstrating the expected behaviour (on iOS):
[ios-layout-example.mov.zip](https://github.com/facebook/react-native/files/3489498/ios-layout-example.mov.zip)

and the incorrect behaviour on Android:
[android-layout-example.mov.zip](https://github.com/facebook/react-native/files/3489499/android-layout-example.mov.zip)

**Comment by ouoru** [comment]
I am currently working around this bug by pushing the removal animations into a queue and doing them one by one. This isn't applicable to every scenario, but it's working for mine.

**Comment by chakrihacker** [comment]
@ouoru can you share the code??

**Comment by ouoru** [comment]
@chakrihacker  sorry if I'm a bit late, the code is hard to remove from it's current context but I'll try my best

in the constructor
```
this.queue = []
this.queueTimer = undefined
this.queueIsActive = false

this.state = {
  items: []
}
```

when the list of items is updated
```
update(items) {
  this.queue.push(items)
  if (!this.queueIsActive) this.animateQueue
}
```

animateQueue should then setState as well as call LayoutAnimation, with a setTimeout delay of the LayoutAnimation duration to make sure that the animations are not overlapping. Then you can remove the update from the queue. At the end of the animation, check if there are still updates in the queue, and run animateQueue() again if there are. If there are no updates left, just set queueIsActive to false.

**Comment by chakrihacker** [comment]
Thanks a lot will try this @ouoru
