### ISSUE TITLE
@react-native-community/eslint-config#overrides[2]: Environment key "jest/globals" is unknown

### ISSUE THREAD

**Issue by scarcoco** [facebook/react-native#26021]
### Problem

i create a new project, use `npx react-native init  Demo` from  https://github.com/react-native-community/cli/blob/master/docs/init.md, and open js file, vs code show a tip as below.

ESLint: Demo/.eslintrc.js » @react-native-community/eslint-config#overrides[2]: Environment key "jest/globals" is unknown . Please see the 'ESLint' output channel for details.

I want to upgrade eslint-plugin-config, but @react-native-community/eslint-config locked it.

### React Native version:
```
react-info
System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 3.31 GB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.7.0 - ~/.nvm/versions/node/v12.7.0/bin/node
    Yarn: 1.17.3 - ~/.nvm/versions/node/v12.7.0/bin/yarn
    npm: 6.10.0 - ~/.nvm/versions/node/v12.7.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    Android SDK:
      API Levels: 25, 26, 27, 28
      Build Tools: 25.0.2, 26.0.2, 27.0.3, 28.0.1, 28.0.3
      System Images: android-19 | ARM EABI v7a, android-19 | Intel x86 Atom, android-19 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
      Android NDK: 19.2.5345600
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.4 => 0.60.4
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

**Comment by scarcoco** [comment]
issue of eslint-plugin-jest : https://github.com/jest-community/eslint-plugin-jest/issues/338

**Comment by scarcoco** [comment]
my problem, i open project from parent directory, not project directory

**Comment by iamchathu** [comment]
This issue keeps poping out in VSCode for every keystrock. When we create new project with `react-native init AppName` it generate eslint file extending the @react-native-community/eslint-config

https://github.com/facebook/react-native/tree/master/packages/eslint-config-react-native-community This package seems to have the issue.

**Comment by smboy86** [comment]
same issue..

**Comment by tstanton99** [comment]
same issue...

**Comment by technoplato** [comment]
I just deleted ESLint and went with prettier. Too lazy to research benefits
of linter vs opinionated formatter and haven’t run into any issues.

**Comment by iamchathu** [comment]
@technoplato They are two different things at you can use both at same time. Which I do. Only this issue makes it hard to setup eslint rules.

**Comment by ManAnRuck** [comment]
i want to use it in a monorepo and have the same issue :/

**Comment by alveshelio** [comment]
Hi guys
Any progress on this issue? I'm using a monorepo with a web and mobile app and I'm having the same issue.
