### ISSUE TITLE
Flatlist nesting is not working properly Scroll

### ISSUE THREAD

**Issue by wangfpp** [facebook/react-native#26025]
## Info
  React Native Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
      CPU: (8) x64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
      Memory: 474.79 MB / 15.55 GB
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 8.10.0 - /usr/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 3.5.2 - /usr/bin/npm
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.9 => 0.59.9 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Example Code
``` javascript
              <FlatList
                        data={this.state.grouplist}
                        style={styles.leftflatlist}
                        // contentContainerStyle={{height: 200}}
                            numColumns={4}
                            extraData={this.state}
                            horizontal={false}
                            renderItem={({item, index}) => {
                                let list = item;
                                let _index = index;
                                return (
                                        <FlatList 
                                             listKey={_index}
                                            data={list}
                                            extraData={this.state}
					   horizontal={false}
					style={styles.scroll}
					numColumns={4}
					renderItem={({item, index}) => {
					return (
                                                    <TouchableHighlight 
                                                    underlayColor="rgba(0,0,0,0)"
                                                    key={item.index} 
                                                    onPress={this.editorGroup.bind(this, _index, index, item)}>
                                                        <Avatar 
                                                        shake={this.state.rotateList[_index]}
                                                        icon={{uri: item.face_image}}
                                                        name={item.name}>
                                                    </Avatar> 
                                                    </TouchableHighlight>
												)
	                      </FlatList>
            </FaltList>
```
Inner layer cannot be scrolled

**Comment by vinicarra** [comment]
I might be wrong but seems you don't actually need 2 FlatLists to produce the results you're looking for. Perhaps a [SectionList](https://facebook.github.io/react-native/docs/sectionlist) would better fit your needs as it can separate its content in groups while using only 1 scrollable area. Nested FlatLists will mostly likely not work as you are expecting as one might end stealing the scrollEvent from the other. A good example for nested FlatLists is when their direction diverges (e.g the main FlatList using vertical scrolling while its children using horizontal scrolling).
