### ISSUE TITLE
ReactAndroid:buildReactNdkLib FAILED on react-native V0.59.10

### ISSUE THREAD

**Issue by Jimslu** [facebook/react-native#26027]
**Description**
   Instruction for building from source not working: https://facebook.github.io/react-native/docs/building-from-source. The error I got as below:

```
error: unable to open output file 'C:\SVNcode\APP\RNFiveNine\testndk\node_modules\react-native\ReactAndroid\build\tmp\buildReactNdkLib/local/armeabi-v7a/objs/jscexecutor/C_/SVNcode/APP/RNFiveNine/testndk/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/jscexecutor/OnLoad.o': 'No such file or directory'
1 error generated.
[armeabi-v7a] Compile++ thumb: fb <= ByteBuffer.cpp
make: *** [C:\SVNcode\APP\RNFiveNine\testndk\node_modules\react-native\ReactAndroid\build\tmp\buildReactNdkLib/local/armeabi-v7a/objs/jscexecutor/C_/SVNcode/APP/RNFiveNine/testndk/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/jscexecutor/OnLoad.o] Error 1
make: *** Waiting for unfinished jobs....
make: Leaving directory `C:/SVNcode/APP/RNFiveNine/testndk/node_modules/react-native/ReactAndroid/src/main/jni/react/jni'

> Task :ReactAndroid:buildReactNdkLib FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ReactAndroid:buildReactNdkLib'.
> Process 'command 'C:\Users\E0508417\Downloads\android-ndk-r17c-windows-x86_64\android-ndk-r17c\ndk-build.cmd'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 5m 31s
23 actionable tasks: 23 executed
error Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
error Command failed: gradlew.bat app:installDebug. Run CLI with --verbose flag for more details.
```

**To Reproduce**
1.Complete instruction: https://facebook.github.io/react-native/docs/building-from-source
2.react-native run-android

**Expected Behavior**
Everything should work after completing all instruction steps.

**React Native version**
**System:**
      OS: Windows _10
      CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
      Memory: 5.29 GB / 15.79 GB
**Binaries:**
      Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.16.0 - C:\Users\E0508417\AppData\Roaming\npm\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
**IDEs:**
      Android Studio: Version  3.1.0.0 AI-173.4907809
**npmPackages:**
     react: "16.8.3",
     react-native: "0.59.10"
     android-ndk : android-ndk-r17c

**Comment by Jimslu** [comment]
> Can you run `react-native info` and edit your issue to include these results under the **React Native version:** section?

Yes,I have run it

**Comment by QingWinter** [comment]
> > Can you run `react-native info` and edit your issue to include these results under the **React Native version:** section?
> 
> Yes,I have run it
Hey, do you solve this problem, I got same one.
