### ISSUE TITLE
IOS release scheme crash while in splash screen, after a certain normally usage time (weeks) 

### ISSUE THREAD

**Issue by khanhforjob** [facebook/react-native#26039]
## React Native version:
>     System:
>       OS: macOS 10.14.5
>       CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
>       Memory: 305.17 MB / 8.00 GB
>       Shell: 3.2.57 - /bin/bash
>     Binaries:
>       Node: 10.16.0 - /usr/local/bin/node
>       npm: 6.9.0 - /usr/local/bin/npm
>       Watchman: 4.9.0 - /usr/local/bin/watchman
>     SDKs:
>       iOS SDK:
>         Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
>     IDEs:
>       Android Studio: 3.4 AI-183.6156.11.34.5522156
>       Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
>     npmPackages:
>       react: 16.8.3 => 16.8.3 
>       react-native: 0.59.10 => 0.59.10 
>     npmGlobalPackages:
>       react-native-cli: 2.0.1

## Steps To Reproduce

1. Everythings is fine: debug / build in release scheme in android / ios
2. After certain time (hours/week) app in ios auto close while in splash screen.
3. To fix: have to build app again using Xcode. Then above problem appear again.

## Describe what you expected to happen:
NO crash when using.

## Error log
1. [org.reactjs.native.example.xxx-xxxx] Bootstrap failed with error: <NSError: 0x28049c570; domain: BKSProcessErrorDomain; code: 1 (bootstrap-failed); reason: "Failed to start job">
2. Bootstrapping failed for <FBApplicationProcess: 0x10ccd7fb0; org.reactjs.native.example.xxx-xxxx; pid: -1> with error: Error Domain=BKSProcessErrorDomain Code=1 "Unable to bootstrap process with bundleID org.reactjs.native.example.xxx-xxxx" UserInfo={NSLocalizedDescription=Unable to bootstrap process with bundleID org.reactjs.native.example.xxx-xxxx, BKSProcessExitReason=0, NSLocalizedFailureReason=Failed to start job, NSUnderlyingError=0x28049e040 {Error Domain=NSPOSIXErrorDomain Code=3 "No such process" UserInfo={NSLocalizedFailureReason=The process failed to exec, NSLocalizedRecoverySuggestion=Consult /var/log/com.apple.xpc.launchd/launchd.log for more information, NSLocalizedDescription=Unable to get valid task name port right for pid 14595}}, BSErrorCodeDescription=bootstrap-failed}

**Comment by radko93** [comment]
Please try using the latest version and report after that.
