### ISSUE TITLE
React-native 0.60.4 android release build issue - package is not a valid resource name

### ISSUE THREAD

**Issue by mailyokesh** [facebook/react-native#26034]
React Native version:

"dependencies": {
    "@react-native-community/async-storage": "^1.6.1",
    "@react-native-community/push-notification-ios": "^1.0.2",
    "apollo-cache-inmemory": "^1.6.3",
    "apollo-client": "^2.6.4",
    "apollo-link": "^1.2.12",
    "apollo-link-context": "^1.0.18",
    "apollo-link-dedup": "^1.0.19",
    "apollo-link-error": "^1.1.11",
    "apollo-link-http": "^1.5.15",
    "apollo-link-ws": "^1.0.18",
    "apollo-utilities": "^1.3.2",
    "bugsnag-react-native": "^2.22.5",
    "emoji-utils": "^1.0.1",
    "graphql": "^14.4.2",
    "graphql-tag": "^2.10.1",
    "just-debounce": "^1.0.0",
    "just-throttle": "^1.1.0",
    "lodash": "^4.17.15",
    "lottie-ios": "^3.0.3",
    "lottie-react-native": "^3.1.0",
    "moment": "^2.24.0",
    "moment-timezone": "^0.5.26",
    "prop-types": "^15.7.2",
    "react": "16.8.6",
    "react-apollo": "2.1.9",
    "react-countdown-now": "^2.1.1",
    "react-moment": "^0.9.2",
    "react-native": "0.60.4",
    "react-native-android-keyboard-adjust": "^1.2.0",
    "react-native-clear-app-cache": "^1.0.4",
    "react-native-device-info": "^2.3.2",
    "react-native-fast-image": "^7.0.2",
    "react-native-firebase": "^5.5.6",
    "react-native-gifted-chat": "^0.9.11",
    "react-native-googleanalytics": "^1.0.0",
    "react-native-image-picker": "^1.0.2",
    "react-native-iphone-x-helper": "^1.2.1",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-markdown-renderer": "^3.2.8",
    "react-native-orientation-locker": "^1.1.6",
    "react-native-permissions": "^1.2.0",
    "react-native-phone-call": "^1.0.9",
    "react-native-progress-bar-animated": "^1.0.6",
    "react-native-push-notification": "^3.1.8",
    "react-native-snap-carousel": "3.7.4",
    "react-native-sound": "^0.11.0",
    "react-native-table-component": "^1.2.0",
    "react-native-uuid-generator": "^6.0.0",
    "react-native-vector-icons": "^6.6.0",
    "react-native-video": "^5.0.0",
    "react-native-view-overflow": "^0.0.4",
    "react-native-webview": "^6.9.0",
    "react-navigation": "2.18.3",
    "react-redux": "5.0.7",
    "redux": "4.0.0",
    "subscriptions-transport-ws": "^0.9.16",
    "uniqueid": "^1.0.0",
    "universal-cookie": "^4.0.2",

## Steps To Reproduce
 Issue while building android release version. react-native run-android --variant=release. IOS build works fine and so is android debug build
1.FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeReleaseResources'.
> ~/rn60-new/git/MyApp/android/app/build/generated/res/react/release/raw/package.json: Error: package is not a valid resource name (reserved Java keyword)

Describe what you expected to happen:
Expect the android release to succeed.

**Comment by IntelliJAbhishek** [comment]
@mailyokesh Its not a problem with react-native 0.60.4. Its because of some of your dependencies. Close this issue.
