### ISSUE TITLE
React native 0.60.2 InteractionManager not working as expected

### ISSUE THREAD

**Issue by shubhang93** [facebook/react-native#26040]
React Native version:
  System:
    OS: macOS 10.14.3
    CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
    Memory: 333.23 MB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.9.4 - ~/.nvm/versions/node/v8.9.4/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.5.0 - ~/.nvm/versions/node/v8.9.4/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28
      Build Tools: 23.0.1, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.2, 28.0.3
      System Images: android-21 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom_64, android-23 | Google APIs ARM EABI v7a, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-25 | Google Play Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.1 AI-173.4907809
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.2 => 0.60.2
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Steps To Reproduce

1. Add an InteractionManager.runAfterInteractions in componentDidMount.
2. Try to navigate to a screen OR perform animations.
3. A slight jerk/stutter/lag is felt.

Describe what you expected to happen:
Wait for the animations/Navigator transitions to complete and run the handler, but there is a slight jerk/lag/stutter that is experienced, however the alternative solution is to replace it with a setTimeout call, which works perfectly.

code sample
 ```javascript
 class ExpensiveComponent extends React.Component {
      state = {
          isTransitionComplete:false
      }
       componentDidMount(){
            InteractionManager.runAfterInteractions(()=> {
                  /*Load some data from local db*/
                 this.setState({isTransitionComplete:true})
            })
        }
       render(){
          if(!this.state.isTransitionComplete) return <CheapLoadingComponent/>
          else return <ExpensiveComponent/>
      }
}
```

**Comment by dulmandakh** [comment]
InteractionManager doesn't know about navigation transitions. So it might be better to use APIs provided by navigation library you use.

**Comment by shubhang93** [comment]
Yes, I understand that but it was working on react native 0.55.4 with react native router flux.

**Comment by dulmandakh** [comment]
did you changed navigation library?

**Comment by shubhang93** [comment]
Nope I haven't changed the library, I'm using react native router flux.

**Comment by blackbing** [comment]
I have the same question. 
@dulmandakh 
What do you mean by this?
> InteractionManager doesn't know about navigation transitions. 
This is definition by doc :
> InteractionManager allows long-running work to be scheduled after any interactions/animations have completed.
