### ISSUE TITLE
Android4.4: error while updating preoperty 'overflow' in shadow node of type:RCTView

### ISSUE THREAD

**Issue by sjpeter** [facebook/react-native#26058]
React Native version:0.60.4

## Steps To Reproduce

1.error while updating preoperty 'overflow' in shadow node of type:RCTView
2.null
3.invalid value for overflow:auto

Describe what you expected to happen:
error

Snack, code example, screenshot, or link to a repository:
https://snack.expo.io/@sjpeter/133e39

**Comment by 452MJ** [comment]
It is 2019 now. Is there really have any 4.4 device?😂

**Comment by sjpeter** [comment]
Yes, those TV is 4.0 device.
