### ISSUE TITLE
react-native Integrated into the Swift project, cannot use use_frameworks! in Podfile

### ISSUE THREAD

**Issue by Ramonfan** [facebook/react-native#26056]
<img width="845" alt="image" src="https://user-images.githubusercontent.com/8336766/62988486-30c34500-be77-11e9-8f5b-bdaf08341121.png">

**Comment by Ramonfan** [comment]
<img width="832" alt="image" src="https://user-images.githubusercontent.com/8336766/63011813-a9e48b80-bebb-11e9-91af-e38c2f97bb9f.png">

**Comment by genuinezack** [comment]
@Ramonfan could you post a link in addition to that screenshot? I'd like to see the rest of the discussion.

**Comment by Ramonfan** [comment]
@genuinezack this is this link of post [https://github.com/facebook/react-native/issues/25349](url)

**Comment by genuinezack** [comment]
Ok great - thanks @Ramonfan. I see there that we can (hopefully) expect to see this fixed in 0.61.0. Fingers crossed!
