### ISSUE TITLE
Module `HMRClient` does not exist in the Haste module map

### ISSUE THREAD

**Issue by palanikphp** [facebook/react-native#26062]
Error: bundling failed: Error: Unable to resolve module `metro/src/lib/bundle-modules/HMRClient` from `/test/ui-gdp-mobile-demo-app/node_modules/react-native/Libraries/Utilities/HMRClient.js`: Module `metro/src/lib/bundle-modules/HMRClient` does not exist in the Haste module map

  React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 98.24 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.0.0 - ~/.nvm/versions/node/v11.0.0/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v11.0.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.5 => 0.59.5 
      

## Steps To Reproduce

1. I have created my own simple NPM package (name: react-native-base-material-ui-themes) to export "native-base" theme variable, which is published in our company private npm registry. 

Below are the dependency that i have included in my new package's package.json (react-native-base-material-ui-themes)

  "dependencies": {
    "native-base": "^2.12.1",
    "react": "16.8.3",
    "react-native": "0.59.5"
  },

2.  Created a project using  `create-react-native-app`, included the same dependency that i used in my theme package
 "dependencies": {
    "native-base": "^2.12.1",
    "react": "16.8.3",
    "react-native": "0.59.5"
  },

3. Start the bundler in one terminal using `react-native start`

4. Start the project in IOS emulator using 'react-native run-ios`
 
Now getting following error:

error: bundling failed: Error: Unable to resolve module `metro/src/lib/bundle-modules/HMRClient` from `/Users/p0k008f/Projects/ui-gdp-mobile/test/ui-gdp-mobile-demo-app/node_modules/react-native/Libraries/Utilities/HMRClient.js`: Module `metro/src/lib/bundle-modules/HMRClient` does not exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.

**Comment by dgoecke2** [comment]
I ran `npm i metro` and it resolved the error.
