### ISSUE TITLE
Bubble onPressOut event

### ISSUE THREAD

**Issue by olivierlesnicki** [facebook/react-native#2607]
![ios simulator screen shot 8 sept 2015 22 15 59](https://cloud.githubusercontent.com/assets/1705944/9747719/5d7837f2-5677-11e5-869f-bfa901e8bd94.png)

I'm implementing a camera view. Once the user clicks on REC I want to trigger a start recording action (using onPressIn), only when the user completely remove its finger from the screen do I want to stop recording (through a onPressOut action).

I'm unsure how I would implement that as it seems actions do not bubble up between to Touchable views and it seems only one element at a time can have touch handlers.

**Comment by ppiekarczyk** [comment]
Hey, 

Have you thought about using https://github.com/omergul123/LLSimpleCamera and using a React Native bridge to make this work?

**Comment by ide** [comment]
Rather than using Touchable you may want to look into handling the touch events in your outer view yourself. The reason for this is that the REC button fires onPressOut when you keep your finger down but move it out of the press-retention bounds of the button (and similarly fires onPressIn when you move your finger back). Similar set up you'd do in UIKit with a UIButton and another gesture recognizer / touch event handler on the superview.

**Comment by olivierlesnicki** [comment]
@ppiekarczyk I've been using https://github.com/piemonte/PBJVision

**Comment by olivierlesnicki** [comment]
@ide fair enough - was looking for an "easy" way

**Comment by olivierlesnicki** [comment]
@ide does it mean using PanGesture?

**Comment by ide** [comment]
I mean this stuff here: https://facebook.github.io/react-native/docs/gesture-responder-system.html#content. I haven't actually tried it so it might not work but that's the direction I'd investigate.

**Comment by olivierlesnicki** [comment]
Yeah, the PanResponder is a wrapper around the GestureResponder (to avoid having to deal with multi-touches complexity). I'll post my findings tonight.

**Comment by olivierlesnicki** [comment]
While we have onStartShouldSetResponder and onMoveShouldSetResponder, I think we're missing a onReleaseShouldSetResponder event in order to accomplish the mentioned behavior

**Comment by brentvatne** [comment]
@olivierlesnicki - I believe `onPanResponderRelease` should do what you want. Either way, I don't think that this is a bug or missing feature, it should be very possible based off my interpretation of what you described. This type of question is best suited for StackOverflow, so feel free to repost there if you're still stuck and then ping us here if it turns out that it is not possible after all! :smile:

**Comment by olivierlesnicki** [comment]
The thing is `onPanResponderRelease` is never called if the view is not the responder. The only way a view can become a responder is on start touch (via `onStartShouldSetPanResponder` callback) or on move (via `onMoveShouldSetPanResponder`). 

When the user starts touch on the RECORD button, I need it to be the responder. Therefore I can't set the view to become the responder on start touch. My only option is to make the view the responder on touch move. This works fine if the user press the record button and then move out of it and release the screen. However, if the user doesn't move his finger, the view is never set as the responder.

See this example:

```
var React = require('react-native');

module.exports = React.createClass({

  componentWillMount() {

    this.viewPanResponder = React.PanResponder.create({
      onMoveShouldSetPanResponder: (evt, gestureState) => true,
      onPanResponderRelease: (evt, gestureState) => {
        this.stop();
      }
    });

    this.buttonPanResponder = React.PanResponder.create({
      onStartShouldSetPanResponder: (evt, gestureState) => true,
      onPanResponderStart: (evt, gestureState) => {
        this.start();
      }
    });

  },

  start() {
    console.log('start recording');
  },

  stop() {
    console.log('stop recording');
  },

  onPressInRecordButton() {
    this.start();
    this.isRecordButtonPressed = true;
  },

  onPressOutRecordButton() {
    this.isRecordButtonPressed = false;
  },

  render() {
    return (
      <React.View
        {...this.viewPanResponder.panHandlers}
        style={{
          flex: 1,
        }}
      >
        <React.View
          style={{
            position: 'absolute',
            bottom: 20,
            left: 0,
            right: 0,
            alignItems: 'center'
          }}
        >
          <React.View
            {...this.buttonPanResponder.panHandlers}
            style={{
              backgroundColor: 'rgba(0,0,0,1)',
              height: 80,
              width: 80,
              alignItems: 'center',
              justifyContent: 'center',
              borderRadius: 40,
            }}
          >
            <React.Text
              style={{
                color: '#fff',
                fontSize: 16,
                letterSpacing: 3,
              }}
            >
              REC
            </React.Text>
          </React.View>
        </React.View>
      </React.View>
    );
  }
});

```

**Comment by olivierlesnicki** [comment]
on paper I still think PanResponder is missing a `onReleaseShouldSetResponder ` callback @brentvatne

**Comment by olivierlesnicki** [comment]
@brentvatne managed to solve it:

```
var React = require('react-native');

module.exports = React.createClass({

  getInitialState() {
    return {
      started: false,
    }
  },

  componentWillMount() {

    this.viewPanResponder = React.PanResponder.create({
      onStartShouldSetPanResponder: (evt, gestureState) => {
        return true;
      },
      onPanResponderTerminate: (evt, gestureState) => {
        this.stop();
      },
      onPanResponderRelease: (evt, gestureState) => {
        this.stop();
      }
    });

    this.buttonPanResponder = React.PanResponder.create({
      onStartShouldSetPanResponder: (evt, gestureState) => {
        this.start();
        return false;
      },
    });

  },

  start() {
    this.setState({
      started: true,
    });
  },

  stop() {
    this.setState({
      started: false,
    });
  },

  onPressInRecordButton() {
    this.start();
    this.isRecordButtonPressed = true;
  },

  onPressOutRecordButton() {
    this.isRecordButtonPressed = false;
  },

  render() {
    return (
      <React.View
        style={{
          flex: 1,
        }}
      >
        <React.View
          {...this.viewPanResponder.panHandlers}
          style={{
            position: 'absolute',
            bottom: 20,
            left: 0,
            right: 0,
            alignItems: 'center'
          }}
        >
          <React.View
            {...this.buttonPanResponder.panHandlers}
            style={{
              backgroundColor: this.state.started ? 'red' : 'black',
              height: 80,
              width: 80,
              alignItems: 'center',
              justifyContent: 'center',
              borderRadius: 40,
            }}
          >
            <React.Text
              style={{
                color: '#fff',
                fontSize: 16,
                letterSpacing: 3,
              }}
            >
              REC
            </React.Text>
          </React.View>
        </React.View>
      </React.View>
    );
  }
});
```

@brentvatne @ide thanks for your patience guys

**Comment by iMagdy** [comment]
Did you get it working when setting state inside start/stop?
