### ISSUE TITLE
A problem occurred starting process 'command '..\..\node_modules\hermesvm\win64-bin\hermes''

### ISSUE THREAD

**Issue by valery-lavrik** [facebook/react-native#26072]
React Native version:
System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 2.00 GB / 7.49 GB
  Binaries:
    Node: 12.4.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.7.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5692245

## Steps To Reproduce

_1. cd android
2. ./gradlew clean
3. ./gradlew assembleRelease_

**> Configure project :react-native-webview
:react-native-webview:reactNativeAndroidRoot E:\RN\st-react-native\node_modules\reactative\android

> Task :app:bundleReleaseJsAndAssets
warn The following packages use deprecated "rnpm" config that will stop working from xt release:
  - rn-fetch-blob: https://github.com/joltup/rn-fetch-blob#readme
Please notify their maintainers about it. You can find more details at https://githubom/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.     
 release:
  - rn-fetch-blob: https://github.com/joltup/rn-fetch-blob#readme
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.     
Loading dependency graph, done.
info Writing bundle output to:, E:\RN\st-react-native\android\app\build\generated\assets\react\release\index.android.bundle
info Writing sourcemap output to:, E:\RN\st-react-native\android\app\build\intermediates\sourcemaps\react\release\index.android.bundle.packager.map
info Done writing sourcemap output
info Done writing bundle output
info Copying 23 asset files
info Done copying assets

> Task :app:bundleReleaseJsAndAssets FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> A problem occurred starting process 'command '..\..\node_modules\hermesvm\win64-bin\hermes''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2m 14s
65 actionable tasks: 59 executed, 6 up-to-date**

**********************************
this happens with the latest updates:
![image](https://user-images.githubusercontent.com/8047999/63090779-018b0180-bf65-11e9-8585-1171b30b3e3b.png)

and **enableHermes: true**

What should I do?

**Comment by radko93** [comment]
Not sure if it's related, but React Native does not support React 16.9 yet

**Comment by valery-lavrik** [comment]
@radko93 It's not related. The problem at the time of the operation of hermes. Therefore, I think the reaction itself is not to blame

**Comment by radko93** [comment]
> This should be set on project.ext.react and mirrored here.  If it is not set
 * on project.ext.react, JavaScript will not be compiled to Hermes Bytecode
 * and the benefits of using Hermes will therefore be sharply reduced.

Did enable it as it's described here?

**Comment by valery-lavrik** [comment]
@radko93 Yes of course
![image](https://user-images.githubusercontent.com/8047999/63096642-1a041780-bf77-11e9-8d33-5c0bdf2647c1.png)

**Comment by sasclau** [comment]
Same problem on windows 10

**Comment by seriiix** [comment]
It's fine on mac but i have the same problem on win10

**Comment by PrimeObjects** [comment]
Got the same issue here

**Comment by hemmedo** [comment]
Same here...isn't there any temporary workaround?

**Comment by gpawlik** [comment]
@hemmedo please check where `hermesvm` has been installed within `node_modules` directory. 

The default location is `../../node_modules/react-native/node_modules/hermesvm/%OS-BIN%/hermes` but in my case it has been installed in the root of `node_modules` so I needed to reflect it in the `gradle` file like this:

```
project.ext.react = [
    ...some options...
    enableHermes: true,
    hermesCommand: "../../node_modules/hermesvm/%OS-BIN%/hermes"
]
```

**Comment by hemmedo** [comment]
@gpawlik Although you were right about the path, it still didn't change anything. Still getting the exact same error. Is this the only thing I have to do to make it work?

**Comment by gpawlik** [comment]
@hemmedo Can you confirm that you have the same path when implementing hermes later on?
```
    if (enableHermes) {
        def hermesPath = "../../node_modules/hermesvm/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }
```

**Comment by andreasbergqvist** [comment]
My fix:
https://github.com/facebook/react-native/issues/25599#issuecomment-524537342

**Comment by hemmedo** [comment]
@gpawlik Fixed it. Turns out problem was really the execution of Hermes in windows so I just used that modified react.gradle for it.
