### ISSUE TITLE
Init of 0.59.10 and bundleRelease fails on 64-bit devices on Firebase Test Lab

### ISSUE THREAD

**Issue by lukebaker** [facebook/react-native#26074]
New 0.59.10 application fails to run on at least several Pixel devices in Firebase Test Lab when uploading the Android Application Bundle. Failed on:
* Pixel, API Level 26
* Pixel 2, API Level 26
* Pixel 2, API Level 27
* Pixel 2 XL, API Level 26
* Pixel 2 XL, API Level 27

React Native version:
```
info 
  React Native Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
      CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
      Memory: 784.85 MB / 15.43 GB
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 10.14.2 - ~/.nodenv/versions/10.14.2/bin/node
      Yarn: 1.17.3 - /usr/bin/yarn
      npm: 6.4.1 - ~/.nodenv/versions/10.14.2/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-19 | Intel x86 Atom, android-22 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-27 | Intel x86 Atom, android-27 | Intel x86 Atom_64, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.10 => 0.59.10 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

## Steps To Reproduce

1. react-native init AwesomeProject --version 0.59.10
2. cd AwesomeProject
3. touch .watchmanconfig
4. cd android && ./gradlew bundleRelease
4. Upload app.aab to Firebase Test Lab and run Robo test on Pixel, Pixel 2, or Pixel 2 XL.

Describe what you expected to happen:

Expected successful test

Snack, code example, screenshot, or link to a repository:

All five failed with:
```
java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libreactnativejni.so caused by: couldn't find DSO to load: libfb.so caused by: couldn't find DSO to load: libc++_shared.so caused by: dlopen failed: "/data/data/com.awesomeproject/lib-4/libc++_shared.so" is 32-bit instead of 64-bit

FATAL EXCEPTION: create_react_context
Process: com.awesomeproject, PID: 15754
java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libreactnativejni.so caused by: couldn't find DSO to load: libfb.so caused by: couldn't find DSO to load: libc++_shared.so caused by: dlopen failed: "/data/data/com.awesomeproject/lib-4/libc++_shared.so" is 32-bit instead of 64-bit
	at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:738)
	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591)
	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:529)
	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:484)
	at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:31)
	at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:19)
	at com.facebook.react.jscexecutor.JSCExecutorFactory.create(JSCExecutorFactory.java:25)
	at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:944)
	at java.lang.Thread.run(Thread.java:764)
```
Sample logcat:
[web-build_2019-08-15T13:02:43.203Z_w71r_taimen-26-en_US-portrait_logcat.log](https://github.com/facebook/react-native/files/3505790/web-build_2019-08-15T13.02.43.203Z_w71r_taimen-26-en_US-portrait_logcat.log)

AAB:
[app.aab.gz](https://github.com/facebook/react-native/files/3505796/app.aab.gz)

**Comment by MriduDixit15** [comment]
+1 are You able to resolve

**Comment by shaktimoyal** [comment]
> New 0.59.10 application fails to run on at least several Pixel devices in Firebase Test Lab when uploading the Android Application Bundle. Failed on:
> 
> * Pixel, API Level 26
> * Pixel 2, API Level 26
> * Pixel 2, API Level 27
> * Pixel 2 XL, API Level 26
> * Pixel 2 XL, API Level 27
> 
> React Native version:
> 
> ```
> info 
>   React Native Environment Info:
>     System:
>       OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
>       CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
>       Memory: 784.85 MB / 15.43 GB
>       Shell: 4.4.20 - /bin/bash
>     Binaries:
>       Node: 10.14.2 - ~/.nodenv/versions/10.14.2/bin/node
>       Yarn: 1.17.3 - /usr/bin/yarn
>       npm: 6.4.1 - ~/.nodenv/versions/10.14.2/bin/npm
>       Watchman: 4.9.0 - /usr/local/bin/watchman
>     SDKs:
>       Android SDK:
>         API Levels: 23, 25, 26, 27, 28
>         Build Tools: 27.0.3, 28.0.3
>         System Images: android-19 | Intel x86 Atom, android-22 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-27 | Intel x86 Atom, android-27 | Intel x86 Atom_64, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
>     npmPackages:
>       react: 16.8.3 => 16.8.3 
>       react-native: 0.59.10 => 0.59.10 
>     npmGlobalPackages:
>       react-native-cli: 2.0.1
> ```
> 
> ## Steps To Reproduce
> 1. react-native init AwesomeProject --version 0.59.10
> 2. cd AwesomeProject
> 3. touch .watchmanconfig
> 4. cd android && ./gradlew bundleRelease
> 5. Upload app.aab to Firebase Test Lab and run Robo test on Pixel, Pixel 2, or Pixel 2 XL.
> 
> Describe what you expected to happen:
> 
> Expected successful test
> 
> Snack, code example, screenshot, or link to a repository:
> 
> All five failed with:
> 
> ```
> java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libreactnativejni.so caused by: couldn't find DSO to load: libfb.so caused by: couldn't find DSO to load: libc++_shared.so caused by: dlopen failed: "/data/data/com.awesomeproject/lib-4/libc++_shared.so" is 32-bit instead of 64-bit
> 
> FATAL EXCEPTION: create_react_context
> Process: com.awesomeproject, PID: 15754
> java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libreactnativejni.so caused by: couldn't find DSO to load: libfb.so caused by: couldn't find DSO to load: libc++_shared.so caused by: dlopen failed: "/data/data/com.awesomeproject/lib-4/libc++_shared.so" is 32-bit instead of 64-bit
> 	at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:738)
> 	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591)
> 	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:529)
> 	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:484)
> 	at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:31)
> 	at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:19)
> 	at com.facebook.react.jscexecutor.JSCExecutorFactory.create(JSCExecutorFactory.java:25)
> 	at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:944)
> 	at java.lang.Thread.run(Thread.java:764)
> ```
> 
> Sample logcat:
> [web-build_2019-08-15T13:02:43.203Z_w71r_taimen-26-en_US-portrait_logcat.log](https://github.com/facebook/react-native/files/3505790/web-build_2019-08-15T13.02.43.203Z_w71r_taimen-26-en_US-portrait_logcat.log)
> 
> AAB:
> [app.aab.gz](https://github.com/facebook/react-native/files/3505796/app.aab.gz)

Same is happening with me.
Did u find any solution or the same issue happens when it is uploaded on play store ?
