### ISSUE TITLE
New 0.60.5 app fails to run in Firebase Test Lab Pixel, API Level 26

### ISSUE THREAD

**Issue by lukebaker** [facebook/react-native#26075]
New 0.60.5 app created via init fails Robo test when using Android Application Bundle in Firebase Test Lab on Pixel, API Level 26 (and more).

React Native version:
```
System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Memory: 1.50 GB / 15.43 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 10.14.2 - ~/.nodenv/versions/10.14.2/bin/node
    Yarn: 1.17.3 - /usr/bin/yarn
    npm: 6.4.1 - ~/.nodenv/versions/10.14.2/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 27.0.3, 28.0.3
      System Images: android-19 | Intel x86 Atom, android-22 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-27 | Intel x86 Atom, android-27 | Intel x86 Atom_64, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

## Steps To Reproduce

1. react-native init AwesomeProject2
2. cd AwesomeProject2/android && ./gradlew bundleRelease
3. Upload app.aab to Firebase Test Lab and run Robo test on Pixel, API Level 26

Describe what you expected to happen:

A successful test.

```
java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so

FATAL EXCEPTION: create_react_context
Process: com.awesomeproject2, PID: 13159
java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so
	at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:738)
	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591)
	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:529)
	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:484)
	at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:20)
	at com.facebook.hermes.reactexecutor.HermesExecutorFactory.create(HermesExecutorFactory.java:27)
	at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:949)
	at java.lang.Thread.run(Thread.java:764)
```

[web-build_2019-08-15T13:49:10.847Z_lej5_sailfish-26-en_US-portrait_logcat.log](https://github.com/facebook/react-native/files/3505933/web-build_2019-08-15T13.49.10.847Z_lej5_sailfish-26-en_US-portrait_logcat.log)
[app.aab.gz](https://github.com/facebook/react-native/files/3505934/app.aab.gz)

**Comment by emrebicer** [comment]
Having the same problem here, uploaded my app to the google play store, it works fine on emulator(both downloading it from the play store and directly react-native run-android).Should i be concerned about an unhandled error?

**Comment by cmcleese** [comment]
I've been in contact with Firebase team in regards to this.
I too was having the same similar issue being reported by Firebase Crashlytics.

From Firebase support:
> Upon investigation, our Test Lab engineers observed a known bug in which matrices that were intended to complete successfully were being marked "ERROR" and stuck in "PENDING".
> 
> They have worked on a fix for this, but we're still yet to confirm if it's been rolled out in public.

After this supposed update to Test Lab, after uploading a new build to Google Console, I am no longer receiving this previously reported crash.

To note: My crash was being reported on a Nexus 5X.

This maybe be very much related to the issue you mentioned and might be worth trying to upload a new build to test and see if it triggers a crash being reported.

**Comment by minhnhattonthat** [comment]
Hi, I am still having the same issue with that Nexus 5X. It just happened today, is the bug fixed or is there any update about this bug?
Thanks!
