### ISSUE TITLE
Fetch api resolves with Network request failed on ios

### ISSUE THREAD

**Issue by soumyamishra89** [facebook/react-native#26071]
The fetch api does not always resolve and ends with network request failed.
To test if this issue is related to something wrong in my project or in react-native i created a new project with RN 0.60.4.

I used to call an api 100 times in a loop to try to simulate the issue. 
It resolves well the first time. 
If i do not perform any action for some time and try to fetch again, it does not resolve and then throws network request failed.

The issue might be related to network connectivity but the issue does not happen on my android version. It happens on ios version only though connected to the same network. 

React Native version:
System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 62.34 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.12.0 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.10.2 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28
      Build Tools: 27.0.3, 28.0.2, 28.0.3
      System Images: android-16 | Google APIs Intel x86 Atom, android-17 | Google APIs Intel x86 Atom, android-18 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
    react-native: 0.60.4

## Steps To Reproduce

1. Create a new project
2. Call multiple apis for loading data
3. do not perform any action for some time and then try to fetch again.

Describe what you expected to happen: The fetch api should resolve always and not hang and throw error

Snack, code example, screenshot, or link to a repository:

https://snack.expo.io/@ssmishra/fetch-issue-on-ios

i have the CFNetwork diagnostic logs of when the fetch failed. Maybe it helps to understand the problem. 
[error log.txt](https://github.com/facebook/react-native/files/3505224/error.log.txt)

**Comment by phamlap228** [comment]
same issue

**Comment by soumyamishra89** [comment]
There are multiple issues related to fetch api. 
[https://github.com/facebook/react-native/issues/20405](#20405)
[https://github.com/facebook/react-native/issues/19709](#19709)
[https://github.com/facebook/react-native/issues/21862](#21862)

Its time someone put more effort into solving this issue.

**Comment by soumyamishra89** [comment]
@phamlap228 did you find any solution?

**Comment by bockc** [comment]
There are just so many issues with fetch since RN0.60...

**Comment by lazaronixon** [comment]
I realized that fetch on IOS is getting `Network request failed` with redirect response on react-native 0.61. No problems with android.
```javascript
        fetch('someurl', { method: 'put', body: body() }).then(res => console.log(res) )

        function body() {
          const data = new FormData()
          data.append('article[photo]', { uri: photo.uri, type: photo.type, name: photo.fileName })
          return data
        }
```
