### ISSUE TITLE
Include sourcesContent in composed Hermes source map

### ISSUE THREAD

**Issue by motiz88** [facebook/react-native#26086]
React Native version: >= 0.60.2

## Steps To Reproduce
1. Build a new RN app in release mode with Hermes.
2. The source map under `generated/sourcemaps/react/` does not contain the `sourcesContent` field.

Describe what you expected to happen:

The source map should contain a fully-populated `sourcesContent` field.

More context: https://github.com/facebook/hermes/issues/85 opened by @bengourley

**Comment by bengourley** [comment]
As far as I know nothing has changed, can anybody else shed any light?

**Comment by safaiyeh** [comment]
Should this issue be on the Hermes repo?

**Comment by motiz88** [comment]
No, the relevant build script is part of the RN+Hermes integration which lives in this repo.

**Comment by motiz88** [comment]
This issue still exists.

**Comment by motiz88** [comment]
https://github.com/facebook/metro/pull/574 will fix this. Apologies for the long delay.
