### ISSUE TITLE
useEffect not being called in phone, but indeed in web and AVD

### ISSUE THREAD

**Issue by libasoles** [facebook/react-native#26098]
I'm created a project using **react-native-cli**, and I'm running **React Native 0.60.5** and React 16.8.6

React Native version:
System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Memory: 5.48 GB / 15.92 GB
  Binaries:
    Node: 10.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

## Steps To Reproduce (actually, just see the code snippet below)

1. Create a view with a button
2. Create a custom hook, which declares a boolean state, an effect, and an onClick method (created within useCallback)
3. When the button is clicked, the useCallback fn updates state, triggering a re-render

The expected behaviour is to call the effect after re-rendering. And that's working on web, snack, and AVD but not on a real mobile phone. In my phone, it does re-render but the effect is not being called (it eventually triggers when the phone dims to save energy). 

Snack code example: 
https://snack.expo.io/SkuxEfPNr

(as I said, it works on snack but it doesn't on a real phone)

Any clue?

**Comment by jamsch** [comment]
```
  const onSaveCapture = useCallback(() => {
    console.log('-----------------');
    console.log('button clicked...');

    setShouldCheckPermissionFlag(true);
  }, [setShouldCheckPermissionFlag]);
```
I think you mistyped the dependency? It should be `[shouldCheckPermission]`, not `[setShouldCheckPermissionFlag]`

**Comment by dulmandakh** [comment]
Please debug your custom hook, because I don't think RN has issues supporting custom hooks. https://reactjs.org/docs/hooks-custom.html

I think that you don't need to use useCallback, just export a function instead.
