### ISSUE TITLE
A problem occurred configuring project ':app'

### ISSUE THREAD

**Issue by renishdeveloper** [facebook/react-native#26096]
I have created a project using react-native run-android, now when i clean the gradle files using .\gradlew sclean command i'm getting the error as below in the image. 

I have tried the command on the terminal as a administrator.

![image](https://user-images.githubusercontent.com/40269099/63222779-c9382d00-c1c9-11e9-9109-f0b3aa92a3a1.png)

Versions : 
react-native-cli: 2.0.1
react-native: 0.60.4
npm: 6.9.0
OS: Windows 10

**Comment by momennemrat** [comment]
I'm getting the exact same issue
here my `react-native info` results:

> System:
>     OS: macOS High Sierra 10.13.6
>     CPU: (4) x64 Intel(R) Core(TM) i5-2435M CPU @ 2.40GHz
>     Memory: 759.85 MB / 8.00 GB
>     Shell: 3.2.57 - /bin/bash
>   Binaries:
>     Node: 8.11.4 - /usr/local/bin/node
>     npm: 5.10.0 - /usr/local/bin/npm
>     Watchman: 4.9.0 - /usr/local/bin/watchman
>   SDKs:
>     iOS SDK:
>       Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
>     Android SDK:
>       API Levels: 17, 21, 22, 23, 25, 28
>       Build Tools: 21.1.2, 22.0.1, 23.0.0, 23.0.1, 23.0.2, 23.0.3, 25.0.0, 25.0.2, 28.0.3, 29.0.2
>       System Images: android-21 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
>   IDEs:
>     Android Studio: 3.3 AI-182.5107.16.33.5314842
>     Xcode: 10.1/10B61 - /usr/bin/xcodebuild
>   npmPackages:
>     react: 16.8.6 => 16.8.6 
>     react-native: 0.60.5 => 0.60.5 
>   npmGlobalPackages:
>     create-react-native-app: 1.0.0
>     react-native-cli: 2.0.1

**Comment by momennemrat** [comment]
I came back just to tell how I solve the issue:
- download and install the latest node.js version from their site
- make sure to have the latest JDK (or at least version 8)

this link is helpful:
https://facebook.github.io/react-native/docs/getting-started
(click on "React Native CLI Quickstart")
