### ISSUE TITLE
[iOS Xcode] React-Native build failed in Xcode with library not found in RN 0.60.5

### ISSUE THREAD

**Issue by M1seRy** [facebook/react-native#26106]
## Steps To Reproduce

Using `react-native run-ios` is successfully, when I use Xcode to build and run the project, produce this error:

` ld: warning: directory not found for option ‘-L/Users/misery/Library/Developer/Xcode/DerivedData/example-gxstsmzrnmryezfjrdscgixueydb/Build/Products/Release-iphonesimulator/DoubleConversion’
ld: warning: directory not found for option ‘-L/Users/misery/Library/Developer/Xcode/DerivedData/example-gxstsmzrnmryezfjrdscgixueydb/Build/Products/Release-iphonesimulator/Folly’
ld: warning: directory not found for option ‘-L/Users/misery/Library/Developer/Xcode/DerivedData/example-gxstsmzrnmryezfjrdscgixueydb/Build/Products/Release-iphonesimulator/RCTWeChat’
ld: warning: directory not found for option ‘-L/Users/misery/Library/Developer/Xcode/DerivedData/example-gxstsmzrnmryezfjrdscgixueydb/Build/Products/Release-iphonesimulator/RNGestureHandler’
ld: warning: directory not found for option ‘-L/Users/misery/Library/Developer/Xcode/DerivedData/example-gxstsmzrnmryezfjrdscgixueydb/Build/Products/Release-iphonesimulator/RNReanimated’
ld: warning: directory not found for option ‘-L/Users/misery/Library/Developer/Xcode/DerivedData/example-gxstsmzrnmryezfjrdscgixueydb/Build/Products/Release-iphonesimulator/RNSVG’
ld: warning: directory not found for option ‘-L/Users/misery/Library/Developer/Xcode/DerivedData/example-gxstsmzrnmryezfjrdscgixueydb/Build/Products/Release-iphonesimulator/React-Core’
ld: warning: directory not found for option ‘-L/Users/misery/Library/Developer/Xcode/DerivedData/example-gxstsmzrnmryezfjrdscgixueydb/Build/Products/Release-iphonesimulator/React-DevSupport’
ld: warning: directory not found for option ‘-L/Users/misery/Library/Developer/Xcode/DerivedData/example-gxstsmzrnmryezfjrdscgixueydb/Build/Products/Release-iphonesimulator/React-RCTActionSheet’
ld: warning: directory not found for option ‘-L/Users/misery/Library/Developer/Xcode/DerivedData/example-gxstsmzrnmryezfjrdscgixueydb/Build/Products/Release-iphonesimulator/React-RCTAnimation’
ld: warning: directory not found for option ‘-L/Users/misery/Library/Developer/Xcode/DerivedData/example-gxstsmzrnmryezfjrdscgixueydb/Build/Products/Release-iphonesimulator/React-RCTBlob’
ld: warning: directory not found for option ‘-L/Users/misery/Library/Developer/Xcode/DerivedData/example-gxstsmzrnmryezfjrdscgixueydb/Build/Products/Release-iphonesimulator/React-RCTImage’
ld: warning: directory not found for option ‘-L/Users/misery/Library/Developer/Xcode/DerivedData/example-gxstsmzrnmryezfjrdscgixueydb/Build/Products/Release-iphonesimulator/React-RCTLinking’
ld: warning: directory not found for option ‘-L/Users/misery/Library/Developer/Xcode/DerivedData/example-gxstsmzrnmryezfjrdscgixueydb/Build/Products/Release-iphonesimulator/React-RCTNetwork’
ld: warning: directory not found for option ‘-L/Users/misery/Library/Developer/Xcode/DerivedData/example-gxstsmzrnmryezfjrdscgixueydb/Build/Products/Release-iphonesimulator/React-RCTSettings’
ld: warning: directory not found for option ‘-L/Users/misery/Library/Developer/Xcode/DerivedData/example-gxstsmzrnmryezfjrdscgixueydb/Build/Products/Release-iphonesimulator/React-RCTText’
ld: warning: directory not found for option ‘-L/Users/misery/Library/Developer/Xcode/DerivedData/example-gxstsmzrnmryezfjrdscgixueydb/Build/Products/Release-iphonesimulator/React-RCTVibration’
ld: warning: directory not found for option ‘-L/Users/misery/Library/Developer/Xcode/DerivedData/example-gxstsmzrnmryezfjrdscgixueydb/Build/Products/Release-iphonesimulator/React-RCTWebSocket’
ld: warning: directory not found for option ‘-L/Users/misery/Library/Developer/Xcode/DerivedData/example-gxstsmzrnmryezfjrdscgixueydb/Build/Products/Release-iphonesimulator/React-cxxreact’
ld: warning: directory not found for option ‘-L/Users/misery/Library/Developer/Xcode/DerivedData/example-gxstsmzrnmryezfjrdscgixueydb/Build/Products/Release-iphonesimulator/React-jsi’
ld: warning: directory not found for option ‘-L/Users/misery/Library/Developer/Xcode/DerivedData/example-gxstsmzrnmryezfjrdscgixueydb/Build/Products/Release-iphonesimulator/React-jsiexecutor’
ld: warning: directory not found for option ‘-L/Users/misery/Library/Developer/Xcode/DerivedData/example-gxstsmzrnmryezfjrdscgixueydb/Build/Products/Release-iphonesimulator/React-jsinspector’
ld: warning: directory not found for option ‘-L/Users/misery/Library/Developer/Xcode/DerivedData/example-gxstsmzrnmryezfjrdscgixueydb/Build/Products/Release-iphonesimulator/glog’
ld: warning: directory not found for option ‘-L/Users/misery/Library/Developer/Xcode/DerivedData/example-gxstsmzrnmryezfjrdscgixueydb/Build/Products/Release-iphonesimulator/react-native-splash-screen’
ld: warning: directory not found for option ‘-L/Users/misery/Library/Developer/Xcode/DerivedData/example-gxstsmzrnmryezfjrdscgixueydb/Build/Products/Release-iphonesimulator/react-native-webview’
ld: warning: directory not found for option ‘-L/Users/misery/Library/Developer/Xcode/DerivedData/example-gxstsmzrnmryezfjrdscgixueydb/Build/Products/Release-iphonesimulator/yoga’
ld: library not found for -lDoubleConversion

clang: error: linker command failed with exit code 1 (use -v to see invocation) `

## My Environment:

`React Native version`:
v 0.60.5

`Xcode version` :
Version 10.0 (10A255)

`Podfile`:

`platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'example' do
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/React'
  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'
  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  target 'exampleTests' do
    inherit! :search_paths
  end

  use_native_modules!
end

target 'example-tvOS' do
  target 'example-tvOSTests' do
    inherit! :search_paths
  end

end`

## Describe what you expected to happen:

 1. run `react-native run-ios`and `react-native run-android` was both successfully.  
 2.but use Xcode build button failed.

**Comment by JslinSir** [comment]
the same

**Comment by M1seRy** [comment]
any suggestion or solution ？

**Comment by JslinSir** [comment]
error:library not found for -lDoubleConversion

Seek help as well.

**Comment by JslinSir** [comment]
> any suggestion or solution ？

both react-native run-ios   and  in xcode the same error

**Comment by JslinSir** [comment]
> any suggestion or solution ？

Do the below steps

go to ios/
run 'pod install' or 'pod update'
open ios/newproject.xcworkspace

**Comment by sunweiyang** [comment]
I have no idea if this would help, but sometimes for my own app, attempting to build in Xcode multiple times in a row *may* result in a successful build. For example, I would try building ~5 times (each with a different 'file not found' error), and on the 6th time the build would succeed.

**Comment by bruno-trindade** [comment]
Same thing here – on both Xcode and `react-native run-ios`.  None of these suggestions have helped.  This is a project that is being upgraded from RN 0.59 to 0.60.5.

**Comment by denforlatte** [comment]
This may not help everyone but regarding the -IDoubleConversion library specifically, I noticed that my copy was incorrect so it might be worth checking. 

I used this copy instead to get past the missing -IDoubleConversion: https://github.com/facebook/react-native/blob/master/third-party-podspecs/DoubleConversion.podspec

**Comment by M1seRy** [comment]
Hi guys, in fact, I don't know the real cause of this problem and how to fixed this issue.but

I JUST UPDATE MY Xcode VERSION FROM 10.0 (10A255) TO 10.3 (10G8), REOPEN AND REBUILD 

IT WORKS . 😢

**Comment by geekazoid-at** [comment]
Having the a similar problem with my midsized project after upgrading to 0.60.5. It actually fails at finding CocoaLumberjack, but I expect this to be the case because of dependency and sorting. I am not 100% sure, but release builds seem to be rather the problem than debug builds?!

I use AppCenter as my CI. I created this minimalist project (just `react-native init`) which also fails building there (this one actually fails at finding DoubleConversion).
(Bitbucket Repo)[https://bitbucket.org/geekazoid_at/rn60test/]

I currently expect a problem with the generated .xcworkspace file, but that's a part I didn't dig into yet.

Here are the logs of the minimalist iOS build that fails.
[logs_2.zip](https://github.com/facebook/react-native/files/3546480/logs_2.zip)

**Comment by longnk-1447** [comment]
> Having the a similar problem with my midsized project after upgrading to 0.60.5. It actually fails at finding CocoaLumberjack, but I expect this to be the case because of dependency and sorting. I am not 100% sure, but release builds seem to be rather the problem than debug builds?!
> 
> I use AppCenter as my CI. I created this minimalist project (just `react-native init`) which also fails building there (this one actually fails at finding DoubleConversion).
> [Bitbucket Repo](https://bitbucket.org/geekazoid_at/rn60test/)
> 
> I currently expect a problem with the generated .xcworkspace file, but that's a part I didn't dig into yet.
> 
> Here are the logs of the minimalist iOS build that fails.
> [logs_2.zip](https://github.com/facebook/react-native/files/3546480/logs_2.zip)

the same

**Comment by giniedp** [comment]
same Problem
Upgraded to react-native `0.60.5`
XCode Version `10.3`

**Comment by bruno-trindade** [comment]
It appears we got through our issue upgrading from 0.59 to 0.60.  Maybe this will be helpful to you:

Many of the libraries we were linking to in the "Link Binary with Libraries" build step in Xcode were now present in Cocoapods.  By removing all of the libraries from that build step **except for** `libPods-Qeepsake`, we were able to get past the DoubleConversion error and the build now works.

**Comment by franckboudraa** [comment]
Same issue for me when building for device from Xcode.

I tried many answers listed above but none works.

`ld: library not found for -lDoubleConversion clang: error: linker command failed with exit code 1 (use -v to see invocation)`

Xcode 11.0
react-native 0.60.5

When building to iOS simulator from Xcode I don't have the problem.

**Comment by V1sk** [comment]
same Problem
react-native version `0.61.4`
XCode Version `11.2`

**Comment by idkraf** [comment]
same here. 
react-native Version 0.61.4
XCode Version 11.1

**Comment by giniedp** [comment]
if i recall correctly, the fix for me was the following change in the Fastfile

```diff
platform :ios do
  xcodeproj = './ios/MyApp.xcodeproj'
+ xcworkspace = './ios/MyApp.xcworkspace'

  ...

  desc 'Build the iOS app'
  lane :build do
    certificates
-   gym(scheme: 'MyApp', project: xcodeproj)
+   gym(scheme: 'MyApp', workspace: xcworkspace)
  end

  ...
```

**Comment by EugeneYiminYan** [comment]
I had the same problem.
I followed the suggestions on [Stackoverflow](https://stackoverflow.com/questions/24050012/error-library-not-found-for)

My environment:
react-native: 0.61
Xcode:  11.2.1

My steps to fix the issue:
1. $ `cd ios`
2. $ `pod install`
3. open `YourProject.xcworkspace` instead of `YourProject.xcodeproj`
4. Build and run the selected target

Voila, it works for me. Hope this helps.

**Comment by rahulbhankar786** [comment]
thanks @EugeneYiminYan 
this is perfect answer you can close this issue now

**Comment by M1seRy** [comment]
@rahulbhankar786   closed  : )

**Comment by Jaroswaldo** [comment]
@rahulbhankar786 Well, it definitelly is not perfect answer. I saw in discussion people, who did not resolve issue by opening "xcworkspace" instead of  "xcodeproj". I for instance am allways openning "workspace" file.

**Comment by Desintegrator** [comment]
same

**Comment by MrAlekhin** [comment]
thats definitely not the perfect answer. @M1seRy  did you read @EugeneYiminYan suggestion? more "perfect" would be "try to reopen xcode"

**Comment by M1seRy** [comment]
> thats definitely not the perfect answer. @M1seRy did you read @EugeneYiminYan suggestion? more "perfect" would be "try to reopen xcode"

I have reopen this issues.

**Comment by celwell** [comment]
After much frustration, this 'fix' worked for me: 
**Delete the `[YourApp]Tests` target.** 
I don't _think_ that be needed by most developers anyways.

**Comment by aydinmemis** [comment]
https://github.com/facebook/react-native/issues/20774#issuecomment-424745903

**Comment by anmlkh** [comment]
same issue. updated `react-native` to `0.61.5` but it doesn't help
code of failing lane
```
lane :staging do
    app_identifier = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)

    cocoapods(
      podfile: "ios/"
    )
    download_certificates(
      app_identifier: app_identifier,
      skip_development: true
    )
    get_push_certificate(app_identifier: app_identifier)
    version_bump(
      bump_type: "major"
    )
    build_app(workspace: "ios/project.xcworkspace", scheme: "project")
    upload_to_testflight(
      app_identifier: app_identifier,
    )
    clear_derived_data
    clean_build_artifacts
  end
```
fastlane version 2.142.0

**Comment by jaltin** [comment]
> After much frustration, this 'fix' worked for me:
> **Delete the `[YourApp]Tests` target.**
> I don't _think_ that be needed by most developers anyways.

Thank's @celwell! This fix worked for me too.

**Comment by anmlkh** [comment]
I put 10th version of iOS everywhere where it was `9` or `11` (actually fastfile had `11`) and now it works. So maybe it's just versions conflict

**Comment by hroland** [comment]
I had the same issue, I updated my podfile with `platform :ios, '11.0'`, but I forgot to set the target iOS version from 9 to 11 🙃

**Comment by merielleimpreso** [comment]
Usually running `pod install` solves the problem on my side.

**Comment by KiGi** [comment]
Same problem here as described originally, for us we get this issue when trying to do an archive (release) build only - builds work fine for simulator and device in debug.

I am running in a workspace, and tried deleting all targets except for the main one.

Quitting and resuming Xcode does nothing.

Deleting derived data, reinstalling cocopods, redoing pod install after deleting the Pods directory and Podfile.lock does nothing.

Any ideas?  The repo we are trying to get a successful archive build for is in this directory of our repo:

https://github.com/namiml/react-native-nami-sdk/tree/master/examples/Basic

**Comment by hussainimdad004** [comment]
@celwell Thank you. It worked for me

> After much frustration, this 'fix' worked for me:
> **Delete the `[YourApp]Tests` target.**
> I don't _think_ that be needed by most developers anyways.

**Comment by haelbouhad** [comment]
@hroland Thank you. It worked for me

**Comment by tusharmutreja200** [comment]
Hey guys, Any update for this issue, I am also facing this issue after upgrading from 0.57.8 to 0.62.
Any help will be really appricated

**Comment by aesthytik** [comment]
I changed the build to new build system from legacy.

it worked 🤩👌🏻

**Comment by lifenautjoe** [comment]
Still having this issue... none of these solutions helped..

**Comment by DeadKuriel** [comment]
> After much frustration, this 'fix' worked for me: 
> **Delete the `[YourApp]Tests` target.** 
> I don't _think_ that be needed by most developers anyways.

 It works for me. Thanks.

**Comment by safaiyeh** [comment]
Hey all! Closing this issue as it is an old version of RN. If this occurs with the latest version feel free to open a new issue.

**Comment by thphuc** [comment]
In my case, I had to change the Deployment Info to iOS 11.0

![image](https://user-images.githubusercontent.com/4323410/101977970-04465580-3c84-11eb-85d5-7a445849ed05.png)

**Comment by DanielGumbletonWood** [comment]
yarn upgrade-interactive --latest # update all dependancies
cd ios
pod update or pod install
cd ..
npx react-native run-ios

or also try 

cd ios 
pod deintegrate
pod install 
cd .. 
npx react-native run-ios 

Also try deleting and reinstalling node modules before building the app
