### ISSUE TITLE
FlatList refreshing animation not displaying on initial load when using SafeAreaView

### ISSUE THREAD

**Issue by Blickhan** [facebook/react-native#26108]
## Description

When fetching data on initial mount of the component, the FlatList refreshing animation is not displaying when there is a header that is using SafeAreaView. If I add a setTimeout to the fetchData in componentDidMount then the animation shows up but that feels a bit hacky and shouldn't be necessary. I'm using iPhone X simulator. Sidenote: This also appears to be happening with the SectionList refreshing animation as well.

## Environment

```
React Native version: 0.60.5
System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 423.18 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.8.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.10.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
  IDEs:
    Android Studio: 3.4 AI-183.5429.30.34.5452501
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
```

## Steps To Reproduce

1. https://snack.expo.io/B17r3SdES
2. Using iOS, changing the SafeAreaView to a View shows that the FlatList's refreshing animation will display on initial load.
3. Changing the header back to a SafeAreaView shows that the refreshing animation is absent on initial load (unless using the `setTimeout( this.fetchData, 250 )` hack in componentDidMount that I mentioned in the description).

Describe what you expected to happen:
I expected the SafeAreaView to have the same behavior as the View component in the way it interacts with other components on initial render.

Snack, code example, screenshot, or link to a repository:
https://snack.expo.io/B17r3SdES

**Comment by gbalduzzi** [comment]
It also happens with react-native `0.60.4`

**Comment by mauriziocarella** [comment]
`0.60.5` same bug here
