### ISSUE TITLE
After Updating to 0.60.4 react native app gets stuck on splash screen on react-native run-android

### ISSUE THREAD

**Issue by ParthShrivastav** [facebook/react-native#26101]
The application was working fine until rn version 0.59.9. After upgrading to version 0.60.4, the app started getting stuck on the splash screen. On changing the initial route of the application some screens tend to run but some screen doesn't work.
React Native version:0.60.4 I also tried with 0.60.5

 OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-4670S CPU @ 3.10GHz
    Memory: 909.61 MB / 7.91 GB
  Binaries:
    Node: 10.16.2 - C:\Program Files\nodejs\node.EXE
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5522156
## Steps To Reproduce

1. The application isn't working after the splash screen and gets stuck on the splash screen.
2. The reload also doesn't works for the application.

Describe what you expected to happen:
The application should work fine and inflow.

Snack, code example, screenshot, or link to a repository:

adb logcat -s MyApplication
--------- beginning of system
--------- beginning of crash
08-17 10:43:12.702 12642 12642 E AndroidRuntime: Process: com.MyApplication, PID: 12642
08-17 10:43:12.702 12642 12642 E AndroidRuntime: java.lang.RuntimeException: Unable to pause activity {com.MyApplication/com.MyApplication.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.facebook.marketing.ViewIndexer.unschedule()' on a null object reference
08-17 10:43:12.702 12642 12642 E AndroidRuntime:        at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4031)
08-17 10:43:12.702 12642 12642 E AndroidRuntime:        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3986)
08-17 10:43:12.702 12642 12642 E AndroidRuntime:        at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3938)
08-17 10:43:12.702 12642 12642 E AndroidRuntime:        at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:45)
08-17 10:43:12.702 12642 12642 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
08-17 10:43:12.702 12642 12642 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
08-17 10:43:12.702 12642 12642 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
08-17 10:43:12.702 12642 12642 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
08-17 10:43:12.702 12642 12642 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
08-17 10:43:12.702 12642 12642 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6669)
08-17 10:43:12.702 12642 12642 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-17 10:43:12.702 12642 12642 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
08-17 10:43:12.702 12642 12642 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
08-17 10:43:12.702 12642 12642 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.facebook.marketing.ViewIndexer.unschedule()' on a null object reference
08-17 10:43:12.702 12642 12642 E AndroidRuntime:        at com.facebook.marketing.CodelessActivityLifecycleTracker$1.onActivityPaused(CodelessActivityLifecycleTracker.java:129)
08-17 10:43:12.702 12642 12642 E AndroidRuntime:        at android.app.Application.dispatchActivityPaused(Application.java:248)
08-17 10:43:12.702 12642 12642 E AndroidRuntime:        at android.app.Activity.onPause(Activity.java:1731)
08-17 10:43:12.702 12642 12642 E AndroidRuntime:        at androidx.fragment.app.FragmentActivity.onPause(FragmentActivity.java:470)
08-17 10:43:12.702 12642 12642 E AndroidRuntime:        at com.facebook.react.ReactActivity.onPause(ReactActivity.java:57)
08-17 10:43:12.702 12642 12642 E AndroidRuntime:        at android.app.Activity.performPause(Activity.java:7329)
08-17 10:43:12.702 12642 12642 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1465)
08-17 10:43:12.702 12642 12642 E AndroidRuntime:        at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4021)
08-17 10:43:12.702 12642 12642 E AndroidRuntime:        ... 12 more
--------- beginning of main

**Comment by philipwhiuk** [comment]
This is https://github.com/underscopeio/react-native-facebook-account-kit/issues/181 I think.

**Comment by ParthShrivastav** [comment]
> This is [underscopeio/react-native-facebook-account-kit#181](https://github.com/underscopeio/react-native-facebook-account-kit/issues/181) I think.
This doesn't seem to help me.
As my application doesn't use the react-native-facebook-account-kit library. I am using react-native-fbsdk.

**Comment by ParthShrivastav** [comment]
I think the problem is with Async Storage.

adb logcat AndroidRuntime:E *:S
--------- beginning of main
--------- beginning of system
--------- beginning of crash
08-19 15:20:50.417  2133  2305 E AndroidRuntime: FATAL EXCEPTION: SysUiBg
08-19 15:20:50.417  2133  2305 E AndroidRuntime: Process: com.android.systemui, PID: 2133
08-19 15:20:50.417  2133  2305 E AndroidRuntime: java.util.ConcurrentModificationException
08-19 15:20:50.417  2133  2305 E AndroidRuntime:        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
08-19 15:20:50.417  2133  2305 E AndroidRuntime:        at java.util.HashMap$KeyIterator.next(HashMap.java:1465)
08-19 15:20:50.417  2133  2305 E AndroidRuntime:        at com.android.systemui.tuner.TunerServiceImpl.clearAllFromUser(TunerServiceImpl.java:250)
08-19 15:20:50.417  2133  2305 E AndroidRuntime:        at com.android.systemui.tuner.TunerServiceImpl.lambda$upgradeTuner$0$TunerServiceImpl(TunerServiceImpl.java:138)
08-19 15:20:50.417  2133  2305 E AndroidRuntime:        at com.android.systemui.tuner.-$$Lambda$TunerServiceImpl$SZ83wU1GcnmYXjZCH1hfw7pCVvY.run(Unknown Source:4)
08-19 15:20:50.417  2133  2305 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:883)
08-19 15:20:50.417  2133  2305 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)
08-19 15:20:50.417  2133  2305 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
08-19 15:20:50.417  2133  2305 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:67)
08-19 15:21:12.829  2554  2605 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
08-19 15:21:12.829  2554  2605 E AndroidRuntime: Process: com.google.android.euicc, PID: 2554
08-19 15:21:12.829  2554  2605 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
08-19 15:21:12.829  2554  2605 E AndroidRuntime:        at android.os.AsyncTask$4.done(AsyncTask.java:399)
08-19 15:21:12.829  2554  2605 E AndroidRuntime:        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
08-19 15:21:12.829  2554  2605 E AndroidRuntime:        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
08-19 15:21:12.829  2554  2605 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
08-19 15:21:12.829  2554  2605 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-19 15:21:12.829  2554  2605 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-19 15:21:12.829  2554  2605 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:919)
08-19 15:21:12.829  2554  2605 E AndroidRuntime: Caused by: java.lang.RuntimeException: Cannot find SIM slot mapping for device: generic_x86
08-19 15:21:12.829  2554  2605 E AndroidRuntime:        at com.google.android.euicc.a.k.d(SourceFile:1098)
08-19 15:21:12.829  2554  2605 E AndroidRuntime:        at com.google.android.euicc.a.B(SourceFile:205)
08-19 15:21:12.829  2554  2605 E AndroidRuntime:        at com.android.euicc.k.n.a(SourceFile:114)
08-19 15:21:12.829  2554  2605 E AndroidRuntime:        at com.google.android.euicc.e.d.a(SourceFile:106)
08-19 15:21:12.829  2554  2605 E AndroidRuntime:        at com.android.euicc.receiver.RestoreUiccSlotSettingsOnBootReceiver$1.a(SourceFile:58)
08-19 15:21:12.829  2554  2605 E AndroidRuntime:        at com.android.euicc.receiver.RestoreUiccSlotSettingsOnBootReceiver$1.doInBackground(SourceFile:51)
08-19 15:21:12.829  2554  2605 E AndroidRuntime:        at android.os.AsyncTask$3.call(AsyncTask.java:378)
08-19 15:21:12.829  2554  2605 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-19 15:21:12.829  2554  2605 E AndroidRuntime:        ... 3 more

**Comment by philipwhiuk** [comment]
That's a completely different issue.

In the first instance you have a NPE in 

```
08-17 10:43:12.702 12642 12642 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.facebook.marketing.ViewIndexer.unschedule()' on a null object reference
08-17 10:43:12.702 12642 12642 E AndroidRuntime: at com.facebook.marketing.CodelessActivityLifecycleTracker$1.onActivityPaused(CodelessActivityLifecycleTracker.java:129)
```

which clearly points to a problem with `com.facebook.marketing`'s API.

The second stacktrace is about "Cannot find SIM slot mapping for device: generic_x86" in some bit of Android's carrier SIM API handling library. That's not even remote related to your app. Not everything in the Android log is related to your app.

**Comment by ParthShrivastav** [comment]
> This is [underscopeio/react-native-facebook-account-kit#181](https://github.com/underscopeio/react-native-facebook-account-kit/issues/181) I think.
Removing the entire react-native-fbsdk library which I used in my project, also doesn't work for me.

**Comment by ParthShrivastav** [comment]
Solved Issue by removing the react-native-fbsdk library.
There was some problem with my Facebook integration code.
Thanks, @philipwhiuk for the help!!!
