### ISSUE TITLE
Question: unable to use react-native-calendars

### ISSUE THREAD

**Issue by ramanasak** [facebook/react-native#26103]
I have tried deleting node_modules and reinstalled npm but not resolved .

error: bundling failed: Error: Unable to resolve module `hoist-non-react-statics
` from `E:\DEVELOPMENTWORKSPACE\test\node_modules\react-native-calendars\src\exp
andableCalendar\asCalendarConsumer.js`: Module `hoist-non-react-statics` does no
t exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm star
t -- --reset-cache`.
  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
    at ModuleResolver.resolveDependency (E:\DEVELOPMENTWORKSPACE\test\node_modul
es\metro\src\node-haste\DependencyGraph\ModuleResolution.js:183:15)
    at ResolutionRequest.resolveDependency (E:\DEVELOPMENTWORKSPACE\test\node_mo
dules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (E:\DEVELOPMENTWORKSPACE\test\node_modu
les\metro\src\node-haste\DependencyGraph.js:283:16)
    at Object.resolve (E:\DEVELOPMENTWORKSPACE\test\node_modules\metro\src\lib\t
ransformHelpers.js:264:42)
    at dependencies.map.result (E:\DEVELOPMENTWORKSPACE\test\node_modules\metro\
src\DeltaBundler\traverseDependencies.js:399:31)
    at Array.map (<anonymous>)
    at resolveDependencies (E:\DEVELOPMENTWORKSPACE\test\node_modules\metro\src\
DeltaBundler\traverseDependencies.js:396:18)
    at E:\DEVELOPMENTWORKSPACE\test\node_modules\metro\src\DeltaBundler\traverse
Dependencies.js:269:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (E:\DEVELOPMENTWORKSPACE\test\node_modules\metro\src\D
eltaBundler\traverseDependencies.js:87:24)
 DELTA  [android, dev] ./index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1), failed.

**Comment by XEmAX32** [comment]
0

The problem is that src/expandableCalendar/asCalendarConsumer.js is trying to import 'hoist-non-react-statics' which is not declared as a dependency in package.json So the solution is to add it in package.json as this:

```
"dependencies": {
"lodash": "^4.0.0",
"prop-types": "^15.5.10",
"xdate": "^0.8.0",
"hoist-non-react-statics": "*"},
```
than run `npm install`, run `react-native run-ios` and you're up to go!

**Comment by ramanasak** [comment]
thank you @XEmAX32 ,  this solution worked for me .
