### ISSUE TITLE
ReferenceError: Can't find variable: state

### ISSUE THREAD

**Issue by King2231** [facebook/react-native#26104]
Using React-native: 0.60.4. I am getting the above error when I redirect from my newpassword screen to login screen. The login screen works fine if loaded normally or when directed post logout. But whenever user uses forgotpassword and changes password using OTP and he is redirected to login the above error is thrown and the app crashes.

fixed: http://facebook.github.io/react-native/docs/upgrading.html
![image](https://user-images.githubusercontent.com/22017215/63264198-1f7b9d80-c2a8-11e9-93f0-daede38ada39.png)

React Native version: 0.60.4

Describe what you expected to happen:
The login page should have worked the way it works normally.

I am not very sure if this is an issue with RN so i have also posted on Stackoverflow.

https://stackoverflow.com/questions/57553509/referenceerror-cant-find-variable-state-in-react-native-0-60-4

**Comment by dulmandakh** [comment]
Please look for variable **state** and make sure it's declared before use.
