### ISSUE TITLE
Proposal: improved box and text shadows

### ISSUE THREAD

**Issue by necolas** [facebook/react-native#26110]
This is a proposal to improve the box and text shadows in React Native by adopting the W3C `box-shadow` and `text-shadow`. This has several benefits over the current style props:

1. Supports multiple shadows
2. Supports `spreadRadius` for box shadows
3. Supports inset shadows

## boxShadow

https://developer.mozilla.org/en-US/docs/Web/CSS/box-shadow

Also worth noting that (unlike React Native's `shadow*` style props) `boxShadow` _does not_ apply a shadow to semi-transparent images instead of their bounding box. That is done via filters: https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/drop-shadow

```
// style.boxShadow

type BoxShadowStyle = BoxShadow | Array<BoxShadow>;

type BoxShadow = {
  color?: ?Color;
  spreadRadius?: ?number|string;
  blurRadius?: ?number|string;
  x?: ?number|string;
  y?: ?number|string
  inset?: ?boolean
};
```

## textShadow

https://developer.mozilla.org/en-US/docs/Web/CSS/text-shadow

```
// style.textShadow

type TextShadowStyle = BoxShadow | Array<BoxShadow>;

type TextShadow = {
  color?: ?Color;
  blurRadius?: ?number|string;
  x?: ?number|string;
  y?: ?number|string
  inset?: ?boolean
};
```

**Comment by IjzerenHein** [comment]
This would be nice, but this is likely unfeasible. The RN implements relies on the OS implementation of shadow rendering, which is quite different on Android vs iOS. These implementations are heavily optimized and hardware accelerated, but come with their own set of restrictions for each platform.

**Comment by necolas** [comment]
You can already express the existing shadow API in terms of the boxShadow syntax. Platforms like web would also be able to express their shadows with the additional features

**Comment by IjzerenHein** [comment]
Yes that's true. Still that would only work for iOS and web, but not Android. Also not sure whether drawing multiple shadows is feasible on iOS.
