### ISSUE TITLE
[ListView] Section Header not on top of list?

### ISSUE THREAD

**Issue by BerndWessels** [facebook/react-native#2611]
Hello
It seems that the section header of a list view does not stick at the very top of the list view, but rather about 20 pixels lower.
When you scroll the list it looks very ugly that the rows scroll up higher than the sticky section header.

Is there a fix, a workaround or anything I can do to fix that?

Thank you
Bernd

**Comment by christopherdro** [comment]
Try adding `automaticallyAdjustContentInsets={false}`

**Comment by BerndWessels** [comment]
@christopherdro Thank you sooooo much. That fixed it. Can you explain what that is about?

Thanks again
Bernd
