### ISSUE TITLE
Android crashing when Remote Debug is enabled

### ISSUE THREAD

**Issue by RyanMitchellWilson** [facebook/react-native#26126]
## Summary
I'm trying to get an app up and running on an android emulator. I've tried both Genymotion and the Android Studio Emulator with the same results for both. I've also tried Android API 26, 27 and 28 both 32 and 64 bit versions, same exact behavior. I can get the app running and showing me the default page with the info about React-Native. As soon as I enable Remote JS Debugging it opens the new window in chrome for me but then the app crashes. And there is no way to get back into the app, I've tried rerunning `react-native run-android` which succeeds but then the app instantly fails. Trying to just open the app through the Android menu gives the same result. The only way to get the app back up and running is to wipe the data from my emulator and restart it, that way remote debug is then disabled again. 

So long story short the app runs perfectly fine on android until I enable Remote JS Debugging then it constantly crashes as soon as I try to start the app up.

## System Info
```
System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 814.70 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.10.0 - ~/.nvm/versions/node/v8.10.0/bin/node
    npm: 5.6.0 - ~/.nvm/versions/node/v8.10.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28, 29
      Build Tools: 26.0.2, 28.0.3, 29.0.1, 29.0.2
      System Images: android-24 | Google Play Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-26 | Intel x86 Atom, android-26 | Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-26 | Google Play Intel x86 Atom, android-27 | Intel x86 Atom, android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native: 0.60.5
```
React Native version: 0.60.5

## Steps To Reproduce

1. `npm i -g react-native-cli`
2.  `react-native init testApp`
3. `cd testapp`
4. `npm i`
5. `react-native start`
6. `react-native run-android`

At this point the app is up and running with no problem.

7. Enable Remote JS Debugging
8. Watch the app consistently crash every time it opens

Describe what you expected to happen:
I expect the app to not crash and start giving me debug info in the new window opened in chrome.

Snack, code example, screenshot, or link to a repository:

Please let me know if more info is needed

**Comment by phillipkey** [comment]
I am experiencing the same for iOS, but physical device only.

**Comment by RyanMitchellWilson** [comment]
Turns out Firebase was half installed on my project and not fully linked. Didn't cause a problem until turning on debugging for some reason but once I fully linked Firebase I am able to properly use the debugger without anything crashing. I'll close this issue.

For anyone interested, you can use `adb logcat | grep <your-application-name>` to get the logs from your emulator about your app specifically. I was able to find the exact error causing the crash using this and pretty quickly fixed it.

**Comment by williamgoodhew** [comment]
I am having the same issue with my React-Native Android build - the app opens on a screen and then just freezes. It works fine until I activate debugging.

RN v"0.62.2"

**Comment by ludgerey** [comment]
> I am having the same issue with my React-Native Android build - the app opens on a screen and then just freezes. It works fine until I activate debugging.
> 
> RN v"0.62.2"

I am experiencing this issue too, lately. I'm using Expo SDK 37 (which should use RN v0.61).

Did you get it running somehow?

**Comment by williamgoodhew** [comment]
no still not working - the logs show up in the terminal but they are much harder to read like that.

**Comment by JPI22** [comment]
Hi. im experiencing also this type of crashes. any chance that in the meantime you managed to overcome this?

**Comment by messenja** [comment]
Same here. RN 0.63.4

**Comment by robertwt7** [comment]
Hey peeps, is there any issue that's still open for this? I'm still having the same issue specifically for android when pressing debug, it crashes

**Comment by relativelyrehan** [comment]
Is this resolve yet? If yes, can someone mention the solution/workaround?

**Comment by madflu9er** [comment]
The same problem, but only for one specific project, for all the others looks fine and i can debug android
