### ISSUE TITLE
Network pictures cannot be displayed on Samsung galaxy note8 

### ISSUE THREAD

**Issue by jack-team** [facebook/react-native#26120]
OS: macOS 10.14
    CPU: (4) x64 Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
    Memory: 6.30 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.1 - /usr/local/bin/node
    Yarn: 1.5.1 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.7.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
  IDEs:
    Android Studio: 3.3 AI-182.5107.16.33.5314842
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native: 0.55.4

import React,{
    PureComponent
} from 'react';

import {
    Image
} from 'react-native';

const uri = `http://static.yutao2012.com/596bf3a0-c22b-11e9-84d5-1952b91ec70e.jpeg`

class App extends PureComponent{

    state = {
        uri:null
    }

    componentDidMount() {
       
    }

    render() {
       return (
           <Image source={{uri:uri}} style={{width:300,height:300}}/>
       )
    }
}

export default App;

**Comment by dulmandakh** [comment]
Plain HTTP is restricted per Android security policy, so please use HTTPS.
