### ISSUE TITLE
Remote image not showing on Android

### ISSUE THREAD

**Issue by isaaclem** [facebook/react-native#26121]
Remote image not showing on Android. The screenshot sharing below is captured from official docs at https://facebook.github.io/react-native/docs/image.html

![image](https://user-images.githubusercontent.com/32945572/63326701-5cef3200-c35f-11e9-9439-194baa78a314.png)

React Native version:
React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 26.82 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.6.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.10.2 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 22, 23, 25, 26, 27, 28
        Build Tools: 25.0.2, 27.0.3, 28.0.3
        System Images: android-22 | ARM EABI v7a, android-22 | Intel x86 Atom, android-22 | Intel x86 Atom_64, android-22 | Google APIs ARM EABI v7a, android-22 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-Q | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.10 => 0.59.10
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Steps To Reproduce

1. Just load `Image` component with remote url

**Comment by haveamission** [comment]
Did you find any solution to this?

**Comment by jsbsdbd1025** [comment]
I can't load https image in Android enviroment. My react-naitve version is 0.59.2 . What can i do to solve it!

**Comment by rezvalari** [comment]
If your images are in `http` you might want to check this solution
https://stackoverflow.com/a/53630194/11966191
