### ISSUE TITLE
[Android] RefreshControl indicators flicker when they are outside of the parent view

### ISSUE THREAD

**Issue by BSoD38** [facebook/react-native#26125]
React Native version: 0.60.5

Android's RefreshControl indicator (the white circle with an arrow in it when you pull down to refresh) flickers when you offset it outside of its containing view, such as a ScrollView or FlatList. It tends to appear when you are moving your finger, and tends to disappear when you stop moving.

## Steps To Reproduce

1. Create a FlatList with a `refreshControl` prop, then offset the FlatList from the top of the screen by using a view, for example.
2. Put a negative value to the `progressViewOffset` prop on the RefreshControl component.
3. Pull down to refresh, you should see the indicator flickering when it is outside the FlatList.

The RefreshControl indicator should simply overlay the screen without flickering.

Snack showing the issue : https://snack.expo.io/Sy_PNs54B

**Comment by Goazil** [comment]
I'm dealing with that same problem, UP.
