### ISSUE TITLE
[Android TV] Navigating large ScrollView with D-pad scrolls the ScrollView instead of focusing on next item

### ISSUE THREAD

**Issue by satellink** [facebook/react-native#26133]
When clicking RIGHT D-pad -button while focusing on first element of ScrollView, the ScrollView scrolls instead of focusing to the second item in the ScrollView. The same issue happens also when being focused on the last item, and clicking LEFT on D-pad. 

We manage to reliably reproduce this issue on emulators and few real devices, that run Android 7.0, 8.0 and 8.1. There was no issue on Android 6 or 9.

This issue only appears when ScrollView have large-enough amount of items. The amount of items also depends of the size of the item. With large items you need less items for this bug to be reproduced.  

The test code below have three different sample item counts, and assigning each of the value with relevant value for `horizontal`-prop of ScrollView will behave differently when using it with D-pad.

## System info

System:
    OS: macOS 10.14.5
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.5 => 0.60.5

React Native version: 0.60.5

Also reproduced with react-native version 0.59.8

## Steps To Reproduce

1. Run the sample code on Android TV emulators (7.0, 8.0, 8.1) or real devices (tested on Xiaomi Mi Box and TCL tv running Android 8.0 and 8.1)
2. Click D-pad arrows to focus on **Item 1**
3. Click D-pad RIGHT
4. Observe the ScrollView scrolling instead of changing focus to **Item 2**
5. Click D-pad RIGHT a few times, until you notice that the focus starts to eventually behave correctly.
6. Click D-pad LEFT until focusing on **Item 1**
7. Click D-pad RIGHT and observe the scroll view still scrolling instead of changing focus.
 
  Repeat the steps 1-7 by changing the amount of items rendered, and ScrollView prop horizontal={true|false} depending on constant.

## Expected result
  I expect that clicking on D-pad RIGHT would always focus on the item on the right, and clicking D-pad LEFT always to move focus to the item on the left.

Specifically, on steps 4 and 7. the ScrollView should not scroll - only change focus to **Item 2**.

## Sample code
```
import React from "react"
import { StyleSheet, ScrollView, TouchableOpacity, View, Text } from "react-native"

const s = StyleSheet.create({
  item: {
    width: 200,
    height: 50,
    backgroundColor: 'red',
    opacity: 0.2
  },
})

const worksItemCount = 30
const worksOnVerticalOnlyItemCount = 120
const doesNotWorkItemCount = 150

const items = []
for (let id = 1; id <= doesNotWorkItemCount; id++) {
  items.push({ id, name: `Item ${id}` })
}

const Item = ({ name }) => (
  <TouchableOpacity activeOpacity={1.0} style={s.item}>
    <View>
      <Text>{name}</Text>
    </View>
  </TouchableOpacity>
)

const App = () => {
  return (
    <ScrollView horizontal={false}>
      {items.map(c => <Item key={c.id} name={c.name} />)}
    </ScrollView>
  )
}

export default App
```

## Related issue
#20099 looks like being the same issue; however, it is already closed.

**Comment by spakanati123** [comment]
The same issue is observed on Amazon fireStick  V 2.0  but how ever the issue is not observed on Android Tv emulator.

**react-native info:**
```
npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-actionsheet: 2.4.2
    react-native-asset: 2.0.0
    react-native-cli: 2.0.1
    react-native-create-library: 3.1.2
    react-native-gesture-handler: 1.3.0
```
**Pre-condition: Your Horizontal scrollview must contain the each item of different width**

**Comment by spakanati123** [comment]
#20099 it is already closed but the issue can be reproduced if the width is different for each item for horizontal scrollview.
