### ISSUE TITLE
react-native run-android opens the app and exits.

### ISSUE THREAD

**Issue by a-c-sreedhar-reddy** [facebook/react-native#26135]
React Native version:
System:
    OS: Linux 5.0 Ubuntu 19.04 (Disco Dingo)
    CPU: (4) x64 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
    Memory: 798.66 MB / 7.71 GB
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 10.15.2 - /usr/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.5.0 - /usr/local/bin/npm
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-create-library: 3.1.2
    react-native-git-upgrade: 0.2.7

## Steps To Reproduce

1.Created a new app 
2.react-native run-andriod
![Screenshot from 2019-08-24 04-12-20](https://user-images.githubusercontent.com/16081083/63627811-fb60e900-c626-11e9-9e62-4a09efd2b7d3.png)

It opens and the app and exits.
When I set debug server host it works only when debug js remotely is enabled.

**Comment by albullington** [comment]
This is happening for me as well.

**Comment by a-c-sreedhar-reddy** [comment]
@albullington can you +1 the issue?

**Comment by AyushG3112** [comment]
+1

**Comment by a-c-sreedhar-reddy** [comment]
Guys I solved this issue by running `react-native start`  in one terminal and `react-native run-android` in other terminal.
