### ISSUE TITLE
The react native app isn't the latest page when it was packaged

### ISSUE THREAD

**Issue by bigkrys** [facebook/react-native#26130]
Once the application is developed, I want to package it for release. Install it on my phone and it's not the latest code
React Native version:

 System:
      OS: Windows 10
      CPU: (20) x64 Intel(R) Xeon(R) CPU E5-2660 v2 @ 2.20GHz
      Memory: 8.70 GB / 15.93 GB
    Binaries:
      Yarn: 1.16.0 - C:\Users\windows10\AppData\Roaming\npm\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD

## Steps To Reproduce

1.
2.

Describe what you expected to happen:
show the latest code page

Snack, code example, screenshot, or link to a repository:

**Comment by anthowm** [comment]
What RN version? 
I fix this problem with follow this guide
https://medium.com/@impaachu/react-native-android-release-build-crash-on-device-14f2c9eacf18

**Comment by radko93** [comment]
Please provide more info.
