### ISSUE TITLE
0.60.5 hot reload not working 

### ISSUE THREAD

**Issue by callmejm** [facebook/react-native#26131]
React Native version: `0.60.5`

## Steps To Reproduce

1. react-native init myApp
2. react-native run-android
3. enabled JS Debugging & Hot Reloading
4. modify the react-native get started content
5. hot reload toast came up
6. nothing change

Describe what you expected to happen:
content should be change when hot reload is enable.

**Comment by QutfulloOchilov** [comment]
Same here!!!!

**Comment by Jarrio** [comment]
+1
