### ISSUE TITLE
How to communicate between javascript and react-native?

### ISSUE THREAD

**Issue by AishuVaid** [facebook/react-native#26132]
I'm setting up a WebView in react-native within which I read an index.html file. The file displays in ios but not in android. I need a communication link which reads in android as well.

I have tried javascriptenabled={true}. Doesn't work. react-native-webview version: 5.0.1

                source={{ uri: 'file://' + '../../ICFPackage/index.html' }}
                originWhitelist={["*"]}
                domStorageEnabled={true}
                startInLoadingState={true}
                javaScriptEnabled={true}
                allowFileAccess={true} />

React native version
 React Native Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
      CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
      Memory: 211.80 MB / 15.56 GB
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 11.15.0 - /usr/bin/node
      npm: 6.7.0 - /usr/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29
        Build Tools: 27.0.3, 28.0.2, 28.0.3, 29.0.0, 29.0.1
        System Images: android-24 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.9 => 0.59.9 
    npmGlobalPackages:
      react-native-webview: 6.9.0

**Comment by AishuVaid** [comment]
> Can you run `react-native info` and edit your issue to include these results under the **React Native version:** section?
> 
> If you believe this information is irrelevant to the reported issue, you may write `[skip envinfo]` alongside an explanation in your Environment: section.
 React Native Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
      CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
      Memory: 211.80 MB / 15.56 GB
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 11.15.0 - /usr/bin/node
      npm: 6.7.0 - /usr/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29
        Build Tools: 27.0.3, 28.0.2, 28.0.3, 29.0.0, 29.0.1
        System Images: android-24 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.9 => 0.59.9 
    npmGlobalPackages:
      react-native-webview: 6.9.0

**Comment by sunnylqm** [comment]
https://github.com/react-native-community/react-native-webview/issues/746#issuecomment-523721015

**Comment by dulmandakh** [comment]
Closing this because it's been reported to react-native-webview.
