### ISSUE TITLE
Invalid Podfile 

### ISSUE THREAD

**Issue by danilowoz** [facebook/react-native#26149]
## I'm taking the following error on `pod install`:
```
[!] Invalid `Podfile` file: cannot load such file -- /Users/danilowoznica/projects/significa/Vertbase/node_modules/@react-native-community/cli-platform-ios/native_modules.

 #  from /Users/danilowoznica/projects/significa/Vertbase/ios/Podfile:2
 #  -------------------------------------------
 #  platform :ios, '9.0'
 >  require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
 #  
```

## React Native version:

System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 275.30 MB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmGlobalPackages:
    react-native-cli: 2.0.1

**Comment by lumberman** [comment]
Same problem.

**Comment by danilowoz** [comment]
Nevermind, I've set Appcenter wrong. 
Instead of choosing the React Native config I choose Object C and Swift 🤦‍♂

**Comment by RishavKumar-3796** [comment]
Answering anything and closing the issue wont help!

**Comment by danilowoz** [comment]
For me, it is clear enough that it wasn't a React Native bug, but a mistake of mine. 

So if you got this error on Appcenter, make sure you've configured right the settings, in my case I choose Object C and Swift, which is obviously wrong.

**Comment by danilowoz** [comment]
If you're getting this error in another context, please open another issue. 
Because I haven't faced this error again.

**Comment by sohailshe** [comment]
install yarn in terminall

**Comment by canercak** [comment]
I face it

**Comment by JBaczuk** [comment]
I had the same error, and it was because I had not installed node dependencies and it was not able to find them at line:

`require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'`

I just ran `npm i` in project root and the error went away.

**Comment by tonydung2011** [comment]
The issue usually appears when missing the `react-native` dependency. So ensure that you don't mistakenly delete `react-native` in your `package.json`

**Comment by shamprasadrh** [comment]
I am also facing this issue but `npm i` did not solve the issue. This issue happens only on App Center and local build just works fine. 

```
[command]/usr/local/lib/ruby/gems/2.6.0/bin/pod --version
1.8.4
[command]/usr/local/lib/ruby/gems/2.6.0/bin/pod install --repo-update

[!] Invalid `Podfile` file: cannot load such file -- /Users/runner/runners/2.165.0/work/1/s/storybookApp/node_modules/@react-native-community/cli-platform-ios/native_modules.

 #  from /Users/runner/runners/2.165.0/work/1/s/storybookApp/ios/Podfile:2
 #  -------------------------------------------
 #  platform :ios, '9.0'
 >  require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
 #  
 #  -------------------------------------------
##[error]The process '/usr/local/lib/ruby/gems/2.6.0/bin/pod' failed with exit code 1
##[error]The 'pod' command failed with error: The process '/usr/local/lib/ruby/gems/2.6.0/bin/pod' failed with exit code 1
##[section]Finishing: Pod install
##[section]Starting: Xcode build (signed)
```

Any one else is also facing the issue

**Comment by Daavidaviid** [comment]
Same problem on AppCenter. That's how I found this issue.

**Comment by Daavidaviid** [comment]
I found a solution to my problem.
I have a monorepo architecture. And the `yarn.lock` file is located at the root.
So when I was selecting `mobile/package.json` in the AppCenter UI, the bot was looking for `yarn.lock` that didn't exist. So I created an empty `yarn.lock` file in the `mobile/` folder

**Comment by samthuang** [comment]
Hello @Daavidaviid, I'm using a monorepo architecture as well. `repo-name/react-native-mobile`. I solved the "can not load such file" issue by modifying the `require_relative` path in `ios/Podfile` to 

```ruby
# it was "../node_modeuls/@react-native-community/... before"
require_relative "../../node_modules/@react-native-community/cli-platform-ios/native_modules"
```

**Comment by gauravsbagul** [comment]
Do 
1: npm i
2: react-native link (if any)
3: cs ios && pod install && cd ..

**Comment by ZeeshanAhmadKhalil** [comment]
@samthuang  for me there is no `native_modules` folder at `../../node_modules/@react-native-community/cli-platform-ios/`

**Comment by ZeeshanAhmadKhalil** [comment]
Looks like I faced this problem cuz I switched my internet during `npm install` was preforming its job as it didn't installed some packages properly. 

So deleting the `node_modules` folder and then using `npm install` in root to create it again worked for me.

**Comment by Wright-Media** [comment]
I am seeing this error but none of the above mentioned methods are helping
<img width="1305" alt="Screen Shot 2021-08-09 at 11 28 37 AM" src="https://user-images.githubusercontent.com/29211994/128740647-ebbe6184-6ac4-4dbc-870c-8885981f0403.png">

**Comment by dev-blinov** [comment]
Hi! if you using `workspaces` in `yarn`, don't forget added `@react-native-community` and all pod dependecies to **nohoist** section in your main package.json 

![image](https://user-images.githubusercontent.com/1014551/132393808-26525e4f-86f4-4303-a610-39ac0b73e87f.png)
