### ISSUE TITLE
Question: Absolutely positioned elements are invalid for clicks that are outside the range of the parent element

### ISSUE THREAD

**Issue by zero9527** [facebook/react-native#26147]
React Native version: 0.60.4

## Steps To Reproduce

1. Absolutely positioned elements are beyond the parent element
2. Add an event to any child element within the scope of an absolutely positioned element

Describe what you expected to happen:
Absolutely positioned elements are invalid for clicks that are outside the range of the parent element; they can be clicked within the parent element range, but outside the scope is visible but the click is invalid; however, zIndex is smaller than this absolutely positioned element and can be clicked and scrolled. By the way, it work on [codepen](https://codepen.io/pen?template=OJLbYKV), but invalid in Android emulator on Mac

Snack, code example, screenshot, or link to a repository:
This is a demo of working on [codepen](https://codepen.io/pen?template=OJLbYKV) and it work on chrome, but the Android emulator on mac does not work.

**Comment by zwenza** [comment]
Maybe this helps you: https://stackoverflow.com/questions/36938742/touchablehighlight-not-clickable-if-position-absolute

**Comment by kuzkokov** [comment]
No, it will not
