### ISSUE TITLE
Unable to launch app in real device with no errors(ios)

### ISSUE THREAD

**Issue by sogangCSmaster** [facebook/react-native#26152]
Hello, I have an issue with running app on real device.

Building app on simulator seems to work fine
react-native run-ios and building from .xcworkspace has no problem.

HOWEVER

running on real device (iPhone 8+) has problem.
Every time I try to build inside on my real device either through Xcode or terminal, build succeeded, but then app launches in the device, it crashes just after splash screen.

Through Xcode, It throws only "unable to launch {bundle identifier}" with no errors.

Here is what I did to fix the problem
1. I tried to fix this problem by rebooting both of my laptop and phone.
2. I unchecked Debug executable in Product -> Scheme -> Edit Scheme.
3. I did all my signings (Provisioning Profile and Signing Certificate) again.
4. I changed Build System to Legacy..
5. I tried to build app with Release mode

Please help!!

React Native version:
```
System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 457.54 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.0 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
  IDEs:
    Android Studio: 3.3 AI-182.5107.16.33.5314842
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
```
![buildsucceed](https://user-images.githubusercontent.com/32369381/63514029-9d4add80-c522-11e9-9123-dfea751c0cbd.jpeg)

![unabletolaunch](https://user-images.githubusercontent.com/32369381/63514018-97ed9300-c522-11e9-874e-9caa1ea77f43.jpeg)

**Comment by sogangCSmaster** [comment]
Also my Xcode version is 10.3

**Comment by innocces** [comment]
I have the same issue！everything is ok in debug, but archive for ipa is crash after splash

**Comment by ChrisC2** [comment]
I'm running into the same exact issue as well. Build succeeds and crashes right after the splash screen without errors on my device. Runs fine on the simulator.

**Comment by alexandrecanuto** [comment]
Same here... Sometimes I'll reach the **Downloading JavaScript bundle** part, but it takes forever or hangs at around 40%.

**Comment by sogangCSmaster** [comment]
Hi guys...
I was able to fix this, but not sure the real reason..
I fix it by creating a new project with react-native 0.60.5
Copied my codes and modules...
I think version 0.60.5 has no problem.

**Comment by schoenbl** [comment]
I just started to have the same issue.

**Comment by schoenbl** [comment]
I'm still having this issue
