### ISSUE TITLE
<TextInput secureTextEntry /> username autoFill to the previous page's TextInput

### ISSUE THREAD

**Issue by bmxklYzj** [facebook/react-native#26159]
snack link: https://snack.expo.io/@bmxklyzj/input-autocorrect-passord
There is two pages:

1. the first page has a TextInput:
```js
<TextInput
  // textContentType="password"
/>
```
and a button navigate to the second page
2. the second page  has a TextInput with property secureTextEntry
```js
<TextInput secureTextEntry />
```
in second page if i use ios password autoFill, the result is: password is filled in the second page's TextInput, but username is filled in the first page's TextInput.

what i expected is that the username shoud not autoFilled in the first page's TextInput

## React Native version:
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
      Memory: 2.09 GB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.9.4 - ~/.nvm/versions/node/v8.9.4/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.9.4/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.3 => 0.59.3

## Steps To Reproduce

1. open the snack link: https://snack.expo.io/@bmxklyzj/input-autocorrect-passord to see the code. And to use ios password autofill, you must preview the demo on physical devices
2. in the first page click the button to navigate to the second page
3. in the second page click password autofill in keyboard accessory
4. back to the first page to see username is utofilled in TextInput

## what i've tried

1. [TextInput textcontenttype](https://facebook.github.io/react-native/docs/textinput#textcontenttype)  set textContentType to 'none' in second page not work, i can not disable password autoFill

## Describe what you expected to happen:

two result acceptable:
1. can disable the password autoFill in ios keyboard accessory
2. the username not autoFilled in the first page's TextInput

## Snack, code example, screenshot, or link to a repository:

Gif:

![TextInput 2019-08-23 14_45_25](https://user-images.githubusercontent.com/14893159/63572146-bac88780-c5b4-11e9-9316-2efff8d81f51.gif)

**Comment by declanelcocks** [comment]
Still happens to me, really no idea how to resolve it ether.

**Comment by declanelcocks** [comment]
![image](https://user-images.githubusercontent.com/2836593/63916876-e42d5b80-ca6b-11e9-9e17-ed1000492b55.png)

For reference, these are 3 pages created using `react-navigation`. You can see that by clicking the password in the current page, it will autofill with a strong password....but also autofill the password in the bottom page of the stack.

**Comment by bmxklYzj** [comment]
> Still happens to me, really no idea how to resolve it ether.

yes, I think it's a bug. Althouth you can add an unvisible TextInput in the current page, but it's too ugly

**Comment by declanelcocks** [comment]
@bmxklYzj This caused more problems than it was worth for me. I had a semi-working solution with several hidden `TextInput`s, but still ran into bugs on other pages for the same reason. In the end I had to disable the `TextInput` when navigating away from the page, or replace that screen in the stack entirely. Really a pain.

**Comment by declanelcocks** [comment]
Still exists
