### ISSUE TITLE
Unable to autolink Appcenter for RN v60.4

### ISSUE THREAD

**Issue by ldco2016** [facebook/react-native#26153]
https://github.com/microsoft/appcenter-sdk-react-native/issues/666#issuecomment-523775811

After upgrading to React Native 60.4 which was done by creating a brand new application and bringing all the relevant folders and files over I attempted to install packages such as Appcenter. On `android` when I click on login for my application, it breaks with the following error:

`TypeError: null is not an object (evaluating 'AppCenterReactNativeAnalytics.trackEvent')`

I have uninstalled and re-installed appcenter many times now, it always complains that it was not autolinked, but manually linked. I have not manually linked it. It is supposed to generate all the configuration files now, but it does not. I have tried many things which are documented here:

https://github.com/microsoft/appcenter-sdk-react-native/issues/666

I was told by appcenter technician that it is a migration problem with RN 60.4. I do not know if this is the case, but I have been dealing with this problem for over a week now.

React Native version:

 ```
 SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 26.0.2, 27.0.3, 28.0.3
      System Images: android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.5429.30.34.5452501
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.4 => 0.60.4
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
```

## Steps To Reproduce

1. clone the repo
2. npm install
3. Add Appcenter following this guide:
https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native

Describe what you expected to happen:

Should successfully install appcenter and work without throwing the appcenter error when user clicks on login via android platform.

https://github.com/ldco2016/NFIBEngage

**Comment by annakocheshkova** [comment]
Hi folks, I looked at the application myself. It was manually linked pre 0.60, but then after migration to 0.60, deleting the content from gradle files and `MainApplication.java` (`getPackages`) and re-installing the modules it still doesn't autolink. 
Could you help with this? That concerns not only our module but the others as well. What is the right way to migrate?

**Comment by ldco2016** [comment]
Any update on this?
