### ISSUE TITLE
ReactAndroid:buildReactNdkLib fatal error: 'hermes/hermes.h' file not found

### ISSUE THREAD

**Issue by sohutek** [facebook/react-native#26160]
React Native version:
Master branch (23/08/2019)

## Steps To Reproduce

1. Download folder ReactAndroid and ReactCommon from master branch
2. Put it in my Android project. Add ReactAndroid as module
3. In settings.gradle:
include ':ReactAndroid'
4. In app/build.gradlew:
implementation project(':ReactAndroid')
5. Build debug (all tasks like prepareJSC, prepareHermes, prepareBoost, prepareDoubleConversion, prepareFolly, prepareGlog, they work perfectly)

But i got this bugs:
Executing tasks: [:app:assembleDebug]

> Configure project :ReactAndroid
/Users/qts/Downloads/RNCORE/ReactNative/ReactAndroid/build/third-party-ndk/hermes

> Task :app:preBuild UP-TO-DATE
> Task :ReactAndroid:preBuild UP-TO-DATE
> Task :ReactAndroid:preDebugBuild UP-TO-DATE
> Task :ReactAndroid:checkDebugManifest UP-TO-DATE
> Task :ReactAndroid:processDebugManifest UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :ReactAndroid:packageDebugRenderscript NO-SOURCE
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:checkDebugManifest UP-TO-DATE
> Task :ReactAndroid:compileDebugAidl NO-SOURCE
> Task :app:compileDebugAidl NO-SOURCE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :app:prepareLintJar UP-TO-DATE
> Task :app:generateDebugSources UP-TO-DATE
> Task :ReactAndroid:generateDebugBuildConfig UP-TO-DATE
> Task :ReactAndroid:compileDebugRenderscript NO-SOURCE
> Task :ReactAndroid:generateDebugResValues UP-TO-DATE
> Task :ReactAndroid:generateDebugResources UP-TO-DATE
> Task :ReactAndroid:prepareLintJar UP-TO-DATE
> Task :ReactAndroid:generateDebugSources UP-TO-DATE
> Task :ReactAndroid:javaPreCompileDebug UP-TO-DATE
> Task :ReactAndroid:createNativeDepsDirectories UP-TO-DATE
Download https://github.com/react-native-community/boost-for-react-native/releases/download/v1.63.0-0/boost_1_63_0.tar.gz

> Task :ReactAndroid:downloadBoost
Invalid cookie header: "Set-Cookie: has_recent_activity=1; path=/; expires=Fri, 23 Aug 2019 08:14:23 -0000". Invalid 'expires' attribute: Fri, 23 Aug 2019 08:14:23 -0000
Invalid cookie header: "Set-Cookie: logged_in=no; domain=.github.com; path=/; expires=Tue, 23 Aug 2039 07:14:23 -0000; secure; HttpOnly". Invalid 'expires' attribute: Tue, 23 Aug 2039 07:14:23 -0000

> Task :ReactAndroid:packageDebugResources UP-TO-DATE
> Task :ReactAndroid:generateDebugRFile UP-TO-DATE
> Task :ReactAndroid:prepareBoost UP-TO-DATE
Download https://github.com/google/double-conversion/archive/v1.1.6.tar.gz

> Task :ReactAndroid:downloadDoubleConversion
Invalid cookie header: "Set-Cookie: has_recent_activity=1; path=/; expires=Fri, 23 Aug 2019 08:14:56 -0000". Invalid 'expires' attribute: Fri, 23 Aug 2019 08:14:56 -0000
Invalid cookie header: "Set-Cookie: logged_in=no; domain=.github.com; path=/; expires=Tue, 23 Aug 2039 07:14:56 -0000; secure; HttpOnly". Invalid 'expires' attribute: Tue, 23 Aug 2039 07:14:56 -0000

> Task :ReactAndroid:prepareDoubleConversion UP-TO-DATE
Download https://github.com/facebook/folly/archive/v2018.10.22.00.tar.gz

> Task :ReactAndroid:downloadFolly
Invalid cookie header: "Set-Cookie: has_recent_activity=1; path=/; expires=Fri, 23 Aug 2019 08:15:00 -0000". Invalid 'expires' attribute: Fri, 23 Aug 2019 08:15:00 -0000
Invalid cookie header: "Set-Cookie: logged_in=no; domain=.github.com; path=/; expires=Tue, 23 Aug 2039 07:15:00 -0000; secure; HttpOnly". Invalid 'expires' attribute: Tue, 23 Aug 2039 07:15:00 -0000

> Task :ReactAndroid:prepareFolly UP-TO-DATE
Download https://github.com/google/glog/archive/v0.3.5.tar.gz

> Task :ReactAndroid:downloadGlog
Invalid cookie header: "Set-Cookie: has_recent_activity=1; path=/; expires=Fri, 23 Aug 2019 08:15:18 -0000". Invalid 'expires' attribute: Fri, 23 Aug 2019 08:15:18 -0000
Invalid cookie header: "Set-Cookie: logged_in=no; domain=.github.com; path=/; expires=Tue, 23 Aug 2039 07:15:18 -0000; secure; HttpOnly". Invalid 'expires' attribute: Tue, 23 Aug 2039 07:15:18 -0000

> Task :ReactAndroid:prepareGlog UP-TO-DATE
> Task :ReactAndroid:prepareHermes UP-TO-DATE
> Task :ReactAndroid:prepareJSC

> Task :ReactAndroid:buildReactNdkLib
make: Entering directory `/Users/qts/Downloads/RNCORE/ReactNative/ReactAndroid/src/main/jni/react/jni'
[armeabi-v7a] Compile++ thumb: hermes-inspector <= Inspector.cpp
[armeabi-v7a] Compile++ thumb: hermes-executor-debug <= HermesExecutorFactory.cpp
[armeabi-v7a] Compile++ thumb: hermes-executor-debug <= OnLoad.cpp
[armeabi-v7a] Compile++ thumb: hermes-inspector <= InspectorState.cpp
In file included from /Users/qts/Downloads/RNCORE/ReactNative/ReactAndroid/src/main/java/com/facebook/react/../hermes/reactexecutor/HermesExecutorFactory.cpp:3:
/Users/qts/Downloads/RNCORE/ReactNative/ReactAndroid/src/main/java/com/facebook/react/../hermes/reactexecutor/HermesExecutorFactory.h:5:10: fatal error: 'hermes/hermes.h' file not found
#include <hermes/hermes.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
make: *** [/Users/qts/Downloads/RNCORE/ReactNative/ReactAndroid/build/tmp/buildReactNdkLib/local/armeabi-v7a/objs/hermes-executor-debug//Users/qts/Downloads/RNCORE/ReactNative/ReactAndroid/src/main/java/com/facebook/react/__/hermes/reactexecutor/HermesExecutorFactory.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from /Users/qts/Downloads/RNCORE/ReactNative/ReactAndroid/src/main/java/com/facebook/react/../hermes/reactexecutor/OnLoad.cpp:8:
/Users/qts/Downloads/RNCORE/ReactNative/ReactAndroid/src/main/java/com/facebook/react/../hermes/reactexecutor/HermesExecutorFactory.h:5:10: fatal error: 'hermes/hermes.h' file not found
#include <hermes/hermes.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
make: *** [/Users/qts/Downloads/RNCORE/ReactNative/ReactAndroid/build/tmp/buildReactNdkLib/local/armeabi-v7a/objs/hermes-executor-debug//Users/qts/Downloads/RNCORE/ReactNative/ReactAndroid/src/main/java/com/facebook/react/__/hermes/reactexecutor/OnLoad.o] Error 1
In file included from /Users/qts/Downloads/RNCORE/ReactNative/ReactAndroid/../ReactCommon/hermes/inspector/InspectorState.cpp:1:
In file included from /Users/qts/Downloads/RNCORE/ReactNative/ReactAndroid/../ReactCommon/hermes/inspector/InspectorState.h:14:
/Users/qts/Downloads/RNCORE/ReactNative/ReactAndroid/../ReactCommon/hermes/inspector/../../hermes/inspector/Inspector.h:12:10: fatal error: 'hermes/DebuggerAPI.h' file not found
#include <hermes/DebuggerAPI.h>
         ^~~~~~~~~~~~~~~~~~~~~~
In file included from /Users/qts/Downloads/RNCORE/ReactNative/ReactAndroid/../ReactCommon/hermes/inspector/Inspector.cpp:3:
/Users/qts/Downloads/RNCORE/ReactNative/ReactAndroid/../ReactCommon/hermes/inspector/Inspector.h:12:10: fatal error: 'hermes/DebuggerAPI.h' file not found
#include <hermes/DebuggerAPI.h>
         ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
1 error generated.
make: *** [/Users/qts/Downloads/RNCORE/ReactNative/ReactAndroid/build/tmp/buildReactNdkLib/local/armeabi-v7a/objs/hermes-inspector//Users/qts/Downloads/RNCORE/ReactNative/ReactAndroid/__/ReactCommon/hermes/inspector/Inspector.o] Error 1
make: *** [/Users/qts/Downloads/RNCORE/ReactNative/ReactAndroid/build/tmp/buildReactNdkLib/local/armeabi-v7a/objs/hermes-inspector//Users/qts/Downloads/RNCORE/ReactNative/ReactAndroid/__/ReactCommon/hermes/inspector/InspectorState.o] Error 1
make: Leaving directory `/Users/qts/Downloads/RNCORE/ReactNative/ReactAndroid/src/main/jni/react/jni'

> Task :ReactAndroid:buildReactNdkLib FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ReactAndroid:buildReactNdkLib'.
> Process 'command '/Users/qts/Library/Android/sdk/ndk-bundle/ndk-build'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 52s
22 actionable tasks: 6 executed, 16 up-to-date

**Comment by TMomemt** [comment]
Try `cd /node_modules/react-native & npm install` before.

**Comment by sohutek** [comment]
Thanks TMoment so much.
