### ISSUE TITLE
getPropertyAsObject: property '__fbRequireBatchedBridge' is not an Object -> Error

### ISSUE THREAD

**Issue by Floridus** [facebook/react-native#26165]
I want to develop a react native app, which is developed for android/ios app and web also. So I use the "react-native-web" and "react-native" package. I created a project by tutorial, the web version is working without errors, but if I execute the app for my device or on android emulator, then the error "getPropertyAsObject: property '__fbRequireBatchedBridge' is not an Object" pops up.

Need some help please.

React Native version:
^0.60.5

## Steps To Reproduce

1. Make the tutorial of [https://scotch.io/tutorials/build-mobile-friendly-web-apps-with-react-native-web](url)
2. Execute "npm run start-web"
3. Install "@babel/plugin-proposal-object-rest-spread" as dev package instead of "babel-plugin-transform-object-rest-spread"!!! Replace the plugin in .babelrc
4. Plugin your device or open your android emulator.
5. Execute "npm run android" to install the right expo client version on device
6. Execute "npm run start-native".
7. Open the app.

Describe what you expected to happen:
If I want to start the app, then this error pops up.
![image](https://user-images.githubusercontent.com/21052305/63588193-366f0800-c5a6-11e9-96c4-235d60458acd.png)

Snack, code example, screenshot, or link to a repository:

This is the repository of the tutorial:
[https://github.com/christiannwamba/react-native-web-example](url)
Keep in mind, that at the repo, are older versions!

package.json
```
{
  "name": "react-web-mobile-test",
  "version": "0.1.0",
  "private": true,
  "main": "./App.js",
  "dependencies": {
    "expo": "^34.0.4",
    "react": "^16.9.0",
    "react-art": "^16.9.0",
    "react-dom": "^16.9.0",
    "react-native": "^0.60.5",
    "react-native-web": "^0.11.7",
    "react-scripts": "3.1.1"
  },
  "scripts": {
    "start-web": "react-scripts start",
    "build-web": "react-scripts build",
    "test-web": "react-scripts test",
    "eject-web": "react-scripts eject",
    "start-native": "expo start",
    "android": "expo android",
    "ios": "expo ios",
    "build:ios": "expo build:ios",
    "build:android": "expo build:android"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@babel/plugin-proposal-object-rest-spread": "^7.5.5",
    "babel-plugin-module-resolver": "^3.2.0",
    "babel-plugin-transform-react-jsx-source": "^6.22.0",
    "babel-preset-expo": "^5.2.0",
    "react-native-scripts": "^2.0.1"
  }
}
```

app.json
```
{
  "expo": {
    "sdkVersion": "34.0.0",
    "name": "react-web-mobile-test",
    "slug": "react-web-mobile-test",
    "version": "0.1.0",
    "description": "An application for app test",
    "primaryColor": "#ff8179",
    "android": {
      "package": "react.web.mobile.test"
    }
  }
}
```

If you need more informationen, you can asks me.

**Comment by Floridus** [comment]
Ok I deactived the web developer logging and now it is working.

**Comment by macroswang** [comment]
> Ok I deactived the web developer logging and now it is working.

hi Floridus ：
I same error . can you help me??

**Comment by dmartinezenfocado** [comment]
same error here, help me please???!!!

**Comment by Smanchanda2** [comment]
I'm also getting the same error. Please help me

**Comment by Smanchanda2** [comment]
Please help me as soon as possible.

**Comment by shrimallamanoj** [comment]
i am getting same here, any luck on solution?

**Comment by Smanchanda2** [comment]
uninstall node modules and then try to install it again will fix the issue.
