### ISSUE TITLE
React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports

### ISSUE THREAD

**Issue by gyfeng1003** [facebook/react-native#26161]
React Native version:

## Steps To Reproduce

1.
2.

Describe what you expected to happen:

Snack, code example, screenshot, or link to a repository:

**Comment by gyfeng1003** [comment]
"private": true,
  "scripts": {
    "start": "react-native start --port=9900",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "16.8.6",
    "react-native": "0.60.5"
  },
  "devDependencies": {
    "@babel/core": "7.5.5",
    "@babel/runtime": "7.5.5",
    "@react-native-community/eslint-config": "0.0.3",
    "babel-jest": "24.9.0",
    "eslint": "6.2.0",
    "jest": "24.9.0",
    "metro-react-native-babel-preset": "0.54.1",
    "react-native-tab-navigator": "^0.3.4",
    "react-redux": "^7.1.0",
    "react-test-renderer": "16.8.6",
    "redux": "^4.0.4",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0"
  },
  "jest": {
    "preset": "react-native"
  }

**Comment by radko93** [comment]
Please add more info using template
