### ISSUE TITLE
Execution failed for task ':app:processReleaseResources'.

### ISSUE THREAD

**Issue by moahammadalt** [facebook/react-native#26179]
after upgrading to react-native version 0.60.5, the application works fine in debug mode but when i try to create release files i am getting several errors, i was able to solve many till i face this error `Execution failed for task ':app:processReleaseResources'.` and cant proceed from it.

error details:

```
Execution failed for task ':app:processReleaseResources'
> Android resource linking failed
  /Users/some-user/Desktop/some-project-name/android/app/build/intermediates/merged_manifests/release/arm64-v8a/AndroidManifest.xml:29: AAPT: error: resource mipmap/ic_launcher (aka some.app.name:mipmap/ic_launcher) not found
  error: failed processing manifest.
```

wonder if it is related to 64 bit new support (arm64-v8a) !

React Native version:
0.60.5

## Steps To Reproduce

1.upgrade to react-native version 0.60.5
2.run `react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res`
3.then run `react-native run-android --variant=release`

Describe what you expected to happen:
i would like to extract release files (apks) of my application.

note: i tried all the similar issues none of them worked.

**Comment by M1seRy** [comment]
From the logs, It looks like you need add some mipmap launch icon resource :
`mipmap/ic_launcher (aka some.app.name:mipmap/ic_launcher) not found`

**Comment by moahammadalt** [comment]
i added mipmap folder in this path: `android/app/src/main/res/` with the ic_launcher.png image inside of it and the error is gone.
