### ISSUE TITLE
Failed to install the app. Make sure you have the Android development environment set up

### ISSUE THREAD

**Issue by zera272** [facebook/react-native#26174]
![Screenshot from 2019-08-24 08-30-11](https://user-images.githubusercontent.com/10398370/63631517-e8640e00-c652-11e9-9219-b1249eb4d25f.png)

I have followed all the steps here: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment

but still, got the same error.

**Comment by tsheringdendu** [comment]
I've the same issues as well. Did anyone figured out why is it so? Any help would be much appreciated. Thank you.
