### ISSUE TITLE
Scrollview horizontal crushing my app

### ISSUE THREAD

**Issue by lylest** [facebook/react-native#26177]
React Native version:

## Steps To Reproduce

1.
2.

Describe what you expected to happen:

Snack, code example, screenshot, or link to a repository:

**Comment by lylest** [comment]
I was expecting my views to be arranged in horizontal here is my package.json file
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "^34.0.1",
    "expo-file-system": "~6.0.0",
    "expo-image-picker": "~6.0.0",
    "expo-permissions": "~6.0.0",
    "expo-sharing": "~6.0.0",
    "firebase": "^6.3.5",
    "react": "16.8.3",
    "react-dom": "^16.8.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz",
    "react-native-dialog": "^5.6.0",
    "react-native-gesture-handler": "~1.3.0",
    "react-native-paper": "^2.16.0",
    "react-native-reanimated": "~1.1.0",
    "react-native-uuid-generator": "^6.0.0",
    "react-native-web": "^0.11.4",
    "react-navigation": "^3.11.1",
    "react-navigation-material-bottom-tabs": "^1.0.0",
    "uuid": "^3.3.3"
  },
  "devDependencies": {
    "babel-preset-expo": "^6.0.0"
  },
  "private": true
}

**Comment by dulmandakh** [comment]
Please provide reproducible demo code.
