### ISSUE TITLE
React Native Forgot password crash

### ISSUE THREAD

**Issue by srgurra** [facebook/react-native#26185]
@bartolkaruza  
@CptFabulouso
I'm developing a react-native app. It has "forgot password" on the login screen that resets the password if the user forgets it. It sends a code to email. when we enter that code on one screen., it prompts for a new password. It works fine till here. But when I entered a new password and clicked on submit, the app crashes and no password changes were made. Below is the code and error code:
<Button style={styles.button} onPress={this.onSubmitResetPassword}>
            <Text>Submit</Text>
</Button>
  onSubmitResetPassword = () => {
    let { password } = this.state;

    if (!password) {
      return Toast.show({
        text: "Please enter your new password.",
        type: "danger",
        buttonText: "x",
        duration: 5000,
        position: "top"
      });
    }

    this.props.userStore.onSubmitResetPassword(password).then(reponse => {
      console.log(reponse);
      if (reponse.change) {
        Toast.show({
          text: "Password was reset successfully.",
          type: "success",
          buttonText: "x",
          duration: 5000,
          position: "top"
        });
        const { navigate } = this.props.navigation;
        navigate("Login");
      }
    });
  };

This is the error in xcode:
[error][tid:com.facebook.react.JavaScript] undefined is not an object (evaluating 't.User.reset.reset_code')
2019-08-25 14:28:18.528 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: undefined is not an object (evaluating 't.User.reset.reset_code')
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by dulmandakh** [comment]
it looks like you're trying to access undefined as an object, please check your code and make sure you're not trying to access undefined.

**Comment by srgurra** [comment]
I'm not trying to access undefined anywhere in my code. please reopen the issue

**Comment by dulmandakh** [comment]
Sorry, it's an issue in your code. Please make sure that User, User.reset are not undefined when your trying to access t.User.reset.reset_code.
