### ISSUE TITLE
android release hangs forever at app:transformClassesAndResourcesWithR8ForRelease

### ISSUE THREAD

**Issue by moahammadalt** [facebook/react-native#26182]
after upgrading my react-native app to version 0.60.5, the application works just fine in debugging mode but when i try to get the android release files of my app by running this command:

`react-native run-android --variant=release`

the progress gets stuck at this line:

`> :app:transformClassesAndResourcesWithR8ForRelease`

and hangs on forever

React Native version:
0.60.5

## Steps To Reproduce
1.upgrade to react-native version 0.60.5
2.run react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
3.then run react-native run-android --variant=release

Describe what you expected to happen:
i would like to extract release files (apks) of my application.

note: i tried to delete the build and gradle folders and run `./gradlew clean` but didn't work either

**Comment by ChaeWonKong** [comment]
I got the same issue. Any possible solutions?

**Comment by marekpiechut** [comment]
Hi.

Try adding more memory to gradle:
edit `gradle.properties` file and add
```
org.gradle.jvmargs=-Xmx4096m
```

**Comment by FrenchMajesty** [comment]
I get a different problem. Running in Emulator is fine but as soon as I generate an APK and try to run the app on a real device then the initial load hangs forever.

This behavior has made it practically impossible to troubleshoot where my problem is coming from.

**Comment by mic7010** [comment]
@FrenchMajesty - did you ever resolve this?

**Comment by brvhprince** [comment]
anyone with a solution? really getting messy 😢

**Comment by malvinder** [comment]
facing same issue
RN: 62.2
React: 16.11.0

iOS builds fine
Android: debug version runs fine on Emulator / Device

Configured the signing configs and stuff for Android
The build starts and hangs at this, like forever, without any error

**Comment by moahammadalt** [comment]
i solved the problem by leaving react native, thanks guys.

**Comment by anasgit95** [comment]
org.gradle.jvmargs=-Xmx4096m

Works for me  .
