### ISSUE TITLE
[Android] Regression after 0.59: FlatList in inverted mode on Android doesn't invert pull-to-refresh gesture.

### ISSUE THREAD

**Issue by avinidiktov** [facebook/react-native#26181]
## Description:
When inverted prop is set to true for FlatList on Android pulling from bottom to top does nothing. But pulling from top to bottom causing refresh indicator to show up on top and calling onRefresh.

iOS works as expected.

The problem doesn't exist for React Native 0.59.8.

## React Native version:
System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 1.80 GB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.0 - /usr/local/opt/node@10/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/opt/node@10/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 27, 28
      Build Tools: 27.0.3, 28.0.3
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.5 => 0.60.5
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Steps To Reproduce

1. Use FlatList on Android;
2. Set inverted prop;
2. Pull the list up. The indicator will not be displayed;
3. Pull the list down. The indicator will be displayed at the top of the screen.

## Describe what you expected to happen:
The indicator must be displayed at the bottom of the screen.

## Snack, code example, screenshot, or link to a repository:
**The same code works differently.**

Wrong behavior demo (react-native: 0.60.5):
![wrong](https://user-images.githubusercontent.com/15199362/63640273-4e3ead00-c6c8-11e9-87a1-bc2e4dd08dc0.gif)
https://github.com/avinidiktov/flatlist-bug

Expected behavior demo (react-native: 0.59.8):
![expected](https://user-images.githubusercontent.com/15199362/63640282-63b3d700-c6c8-11e9-9a75-2c2b69d0ab4a.gif)
https://snack.expo.io/@doktorwin/flatlist-bug

**Comment by AurangzaibRamzan** [comment]
Same issue
