### ISSUE TITLE
With Hermes engine, certain date formats crash on production but works in debug

### ISSUE THREAD

**Issue by roydipti23** [facebook/react-native#26187]
React Native version: RN60

new Date('Jul 18, 2018') is not supported on RN
new Date('18-07-2018 12:00') is not supported on RN

## Steps To Reproduce

1. add date: const reproduce = new Date('Jul 18, 2018');
2. It will crash in production

Describe what you expected to happen:
It should return the expected date.

Snack, code example, screenshot, or link to a repository:

export function getDateFormat(date = 'Jul 18, 2018' ) {
  const newDate = new Date(date);
  return newDate;
}

export function getDateFormat(date = '18-07-2018 12:00' ) {
  const newDate = new Date(date);
  return newDate;
}

**Comment by radko93** [comment]
Are you testing on debug without remote debugging enabled? Because then you are using Chrome to run JS code.

**Comment by roydipti23** [comment]
@radko93 debug JS remotely is enabled. And this same format was working previously in production before Hermes.

export function getDateFormat(date = 'Jul 18, 2018' ) {
const newDate = new Date(date);
return newDate;
}

**Comment by henrymoulton** [comment]
I'd recommend looking at using Moment.js. JavaScript engines differ in how they treat Date objects: https://www.freecodecamp.org/news/get-to-know-different-javascript-environments-in-react-native-4951c15d61f5/

**Comment by radko93** [comment]
@roydipti23 Chrome treats dates differently than Hermes. If you want to test in debug mode turn off remote Chrome debugging.

**Comment by HarshitMadhav** [comment]
@roydipti23 try using moment js for the same

**Comment by jmeistrich** [comment]
I'm seeing this also. A date in ISO format like `Fri, 06 Sep 2019 18:45:29 +0000 (UTC)` parses as an Invalid Date in Hermes. It works on iOS and was working in Android in 0.59. I am now using Moment as a workaround but this should be supported natively.
