### ISSUE TITLE
react-native init fails with "RangeError: Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by redaphid** [facebook/react-native#26188]
I'm not doing anything fancy, just:
`react-native init PleaseWork`
After waiting a bit, the command exits with:
`error RangeError: Maximum call stack size exceeded`

React Native version:
```
info Fetching system and libraries information...
System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) M-5Y71 CPU @ 1.20GHz
    Memory: 361.93 MB / 8.00 GB
    Shell: 3.0.2 - /usr/local/bin/fish
  Binaries:
    Node: 12.9.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.11.2 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild

```

## Steps To Reproduce

1. run ```react-native init PleaseWork```
2. Watch it ignore my pleas.

Describe what you expected to happen:
I expected it to not crash while initializing a project.

I imagine this isn't affecting many other people, it's just strange that it crashes repeatedly when doing the literal first step in the process of creating an app.

**Comment by redaphid** [comment]
...and yes, I uninstalled and reinstalled via ```yarn global remove/add react-native``` Is yarn ok for installing this?

**Comment by dulmandakh** [comment]
It looks like you're doing recursion, and it might lack exit check, which causes this kind of issues. Please check your code.

**Comment by e-r-w** [comment]
This is happening to me as well for `react-native` v0.60.0, v0.60.4 & v0.60.5

```
info Fetching system and libraries information...
System:
    OS: macOS 10.14.3
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 1.99 GB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
  IDEs:
    Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
```

@redaphid I fixed this by removing `react-native` as a global install and replacing it with `react-native-cli` instead!
