### ISSUE TITLE
Unable to run `react-native log-android` in windows

### ISSUE THREAD

**Issue by reidkersey** [facebook/react-native#26198]
When I attempt to run `react-native log-android` in windows I get the following error:
`info Starting logkitty
The filename, directory name, or volume label syntax is incorrect.
error Command failed: 'C:\Users\reidk\AppData\Local\Android\sdk/platform-tools/adb' logcat -c
The filename, directory name, or volume label syntax is incorrect.
. Run CLI with --verbose flag for more details.
Error: Command failed: 'C:\Users\reidk\AppData\Local\Android\sdk/platform-tools/adb' logcat -c
The filename, directory name, or volume label syntax is incorrect.`

It appears as though some of the slashes are facing the wrong direction in the command.

React Native version:
0.60.5

## Steps To Reproduce

1. Fresh install of a project running 0.60.5
2. run `react-native log-android`

Describe what you expected to happen:
To open the logcat

**Comment by Deepak-merahkee** [comment]
Yeah removing a single quotes in line number 34 worked for me.
The line number 34 should be (0, _child_process.execSync)(`${adbPath} logcat -c`);

**Comment by talaikis** [comment]
Will be fixed when merged: https://github.com/zamotany/logkitty/pull/6 or use https://www.npmjs.com/package/@talaikis/logkitty as temp lib.

**Comment by andrew-koster-** [comment]
I just get "info Starting logkitty" and nothing else. Completely broken tool, for an essential part of React-Native development.

**Comment by dnbr2002** [comment]
Help here if anyone needs it.  
https://stackoverflow.com/questions/57557765/error-when-trying-to-start-logkitty-for-react-native-android-project
