### ISSUE TITLE
PushNotificationIOS conflicting docs AND localNotification event is not firing after remote notif SDK integration

### ISSUE THREAD

**Issue by rgomezp** [facebook/react-native#26199]
React Native version:
```React Native Environment Info:
    System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 453.62 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.15.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 24, 26, 27, 28, 29
      Build Tools: 26.0.2, 27.0.3, 28.0.3, 29.0.0
      System Images: android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom
      Android NDK: 14.1.3816874
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.60.5 => 0.60.5
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-cli: 2.0.1
```

## Steps To Reproduce

1. `git clone git@github.com:geektimecoil/react-native-onesignal`
2. `cd react-native-onesignal/examples/RNOneSignal/`
3. `git checkout reproduce-local-notif-conflict` (branch with local notif repro code)
4. `yarn`
5. Build and run the example app by:
   - Open the RNOneSignal project in XCode
   - Change the Signing Team and Bundle Identifier for both the RNOneSignal target as well as the OneSignalNotificationServiceExtension 
      - The Service Extension bundle id should be `<main-target-bunde-id>.OneSignalNotificationServiceExtension`

Your `AppDelegate.m` should look like [this](https://gist.github.com/rgomezp/d3f0451fecadb754d13a2a5a595e0209) after following the OneSignal (remote notifications) setup instructions **and** the PushNotificationIOS (local notifications) setup [instructions](https://facebook.github.io/react-native/docs/pushnotificationios). 

One thing to note is that it seems like the PushNotificationIOS docs have conflicting instructions...which brings me to the first issue:

**Part 1:** 
The code in those [docs](https://facebook.github.io/react-native/docs/pushnotificationios) says to add this to your AppDelegate.m:
```
 // Required for the localNotification event.
 - (void)application:(UIApplication *)application didReceiveLocalNotification:(UILocalNotification *)notification
 {
  [RCTPushNotificationManager didReceiveLocalNotification:notification];
 }
```

However, it also says to add
```
// Define UNUserNotificationCenter
  UNUserNotificationCenter *center = [UNUserNotificationCenter currentNotificationCenter];
  center.delegate = self;
```
which in theory should break the former. It would be nice to clarify this discrepancy. 

**Part 2:**
After adding the OneSignal SDK (remote notifications), the [event listener](https://facebook.github.io/react-native/docs/pushnotificationios#addeventlistener) for `localNotification` no longer is triggered.

In the OneSignal example app you built in the reproduction steps, tap "Send Local Notifs". You will see in the console that the `console.log` in the `localNotification` handler is never fired after tapping on the local notification.

This may be an issue on our side (OneSignal). However, it isn't clear to us why this is happening and the documentation isn't clear on how to properly handle both the [old (deprecated) ](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1622930-application?language=objc)and [new ways](https://developer.apple.com/documentation/usernotifications/unusernotificationcenterdelegate/1649518-usernotificationcenter?language=objc) of handling local notifications. 

A better local notification click handler would use `userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler` so we would love to see this used in a future RN version ([Apple docs](https://developer.apple.com/documentation/usernotifications/unusernotificationcenterdelegate/1649501-usernotificationcenter?language=objc)). This would be the only way to solve the compatibility issue between plugins for the click handler for iOS 10+ devices.

**Comment by rgomezp** [comment]
This issue still hasn't been fixed

**Comment by rgomezp** [comment]
Still not fixed

**Comment by rgomezp** [comment]
Any update on this?

**Comment by garydevenay** [comment]
Also still looking for an update on this.

**Comment by rgomezp** [comment]
Any update from the React Native team?

**Comment by maddy16** [comment]
Still not fixed. Any update from React Native???

**Comment by carloscuesta** [comment]
The docs for the `AppDelegate.m` part are confusing, as @rgomezp says  `didReceiveLocalNotification` method should not be pointed anymore in the docs since its deprecated and should be be replaced by this, right ?

![Screenshot 2020-09-17 at 13 09 41](https://user-images.githubusercontent.com/7629661/93462773-1f086880-f8e7-11ea-81bb-52b8600bcc6f.png)

**Comment by safaiyeh** [comment]
@carloscuesta thanks for the investigation. Could you make this change in the docs? https://github.com/facebook/react-native-website. They merge updates in fairly quickly. 

Is this just a docs issue or is there actual buggy code that needs to be addressed?

**Comment by carloscuesta** [comment]
Sure I can make the PR! However I'm not 100% sure that my assumption is correct. 

According to iOS docs -> https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1622930-application?language=objc

The following method `application:didReceiveLocalNotification` is deprecated and this one should be used:

> Use userNotificationCenter:willPresentNotification:withCompletionHandler: instead.

The first part of this issue is related to documentation but seems that there's a second part which involves a bug on code as @rgomezp says

**Comment by safaiyeh** [comment]
@carloscuesta yeah that looks right. React Native targets iOS 11 so that should be changed. Would be nice to confirm it works locally by providing a repo with your react-native-website PR.

Make sure to tag this issue as well with the docs change!

**Comment by Simek** [comment]
@safaiyeh React Native `didReceiveLocalNotification` method is still present [in the code](https://github.com/facebook/react-native/blob/master/Libraries/PushNotificationIOS/RCTPushNotificationManager.mm#L215), can we remove it from the library first before removing it from the docs? 🙂 

Also it looks like that `RNTester` is also using that handler (I'm not sure if there is a test related to that):
* https://github.com/facebook/react-native/blob/master/packages/rn-tester/RNTester/AppDelegate.mm#L252

**Comment by rgomezp** [comment]
This issue shouldn't be closed I don't think. There needs to be a code change and then a documentation change. What is this status of this effort?
