### ISSUE TITLE
unable to show mathematical equations with hindi text in react native in android

### ISSUE THREAD

**Issue by ashu777** [facebook/react-native#26204]
i am showing mathematical equations which have some hindi text ,not supported android versions less than 7.0 i am using the below:
"react-native": "0.58.6",
"react-native-mathjax": "^2.0.0",
"react": "16.6.3"
my code:
 <MathJax
 html={'$\sum_{i=0}^n i^2 = \frac{(n^2+n)(2n+1)}{6}$<br><p>This is an equation यह एक हिंदी शब्द  है </p>'}

  mathJaxOptions={{
    messageStyle: 'none',
    extensions: [ 'tex2jax.js' ],
    jax: [ 'input/TeX', 'output/HTML-CSS' ],
    tex2jax: {
      inlineMath: [ ['$','$'], ['\\(','\\)'] ],
      displayMath: [ ['$$','$$'], ['\\[','\\]'] ],
      processEscapes: true,
    },
    TeX: {
      extensions: ['AMSmath.js','AMSsymbols.js','noErrors.js','noUndefined.js']
    }
  }}
  
/>

**Comment by ashu777** [comment]
it is working on android devices 7.0 and up but not in lower than 7.0 
Devices below 7.0 android version  does not showing  hindi text.

**Comment by dulmandakh** [comment]
It looks like an issue related to react-native-mathjax.
