### ISSUE TITLE
Network error in axios and react-native after bundle release

### ISSUE THREAD

**Issue by yang200258** [facebook/react-native#26201]
I'm using react-native and axios to request,in debug model,everything is fine,but when bundle release,it occurs to the 'Network error' in my phone.
React Native version:0.60.4

System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
    Memory: 2.70 GB / 7.89 GB
  Binaries:
    Node: 10.15.3 - D:\node\node.EXE
    Yarn: 1.16.0 - D:\node\yarn.CMD
    npm: 6.4.1 - D:\node\npm.CMD
## Steps To Reproduce

1.  cd android
2.  ./gradlew assembleRelease
3.  and install the bundle apk file in my phone
4. when i request use axios，the error just happended
5. but when i run react-native run-android，everything is fine.

![image](https://user-images.githubusercontent.com/38518538/63732749-43427300-c8a8-11e9-872f-f35d621c30d7.png)

Describe what you expected to happen:

it is normal in bundle release.

Snack, code example, screenshot, or link to a repository:
![image](https://user-images.githubusercontent.com/38518538/63732707-1ee69680-c8a8-11e9-975a-1223a80122b8.png)
![image](https://user-images.githubusercontent.com/38518538/63732731-34f45700-c8a8-11e9-9e9a-f6a9bb97bfae.png)

**Comment by shalevmo** [comment]
I'm having the same issue

**Comment by habil** [comment]
Same here. "react-native": "0.59.3"

**Comment by shalevmo** [comment]
> Same here. "react-native": "0.59.3"
> 
> I found the solution : #24039

I was just about to post the same, Thanks!

**Comment by yang200258** [comment]
> > Same here. "react-native": "0.59.3"
> > I found the solution : #24039
> 
> I was just about to post the same, Thanks!

bro,thanks a lot!!

**Comment by yang200258** [comment]
> > Same here. "react-native": "0.59.3"
> > I found the solution : #24039
> 
> I was just about to post the same, Thanks!

Thank you very much!

**Comment by waleedarshad** [comment]
Try
`"Content-Type": "application/x-www-form-urlencoded",`
      `Accept: "application/json"`

**Comment by AvichalSrivastava** [comment]
Im getting the same  Error: Network Error in the catch when i was trying to call axios api with socket url : http://127.0.0.1:3000. but when i connected to the live socket url it's working fine.

**Comment by gustavoInventdigital** [comment]
O mesmo aqui. "reagir nativo": "0,59,3"

Encontrei a solução: # 24039
