### ISSUE TITLE
"Getting Started" instructions make no AwesomeProject.xcodeproj

### ISSUE THREAD

**Issue by JonathanHayward** [facebook/react-native#2620]
https://facebook.github.io/react-native/docs/getting-started.html#content states:

>  - npm install -g react-native-cli
>  - react-native init AwesomeProject
> 
> **In the newly created folder AwesomeProject/**
> 
> Open AwesomeProject.xcodeproj and hit run in Xcode.

In my shell history I have:

    npm install -g react-native-cli
    react-native init AncientClock
    ls AncientClock/

This listed several files, but no *.xcodeproj:

iOS		index.ios.js	node_modules	package.json

Is this a defect in the system, or do I need to be doing something differently?

**Comment by dsibiski** [comment]
@JonathanHayward  The `AwesomeProject.xcodeproj` has been moved inside the `iOS` folder.
