### ISSUE TITLE
StrictMode policy violation in Play store prelaunch report

### ISSUE THREAD

**Issue by axebelk** [facebook/react-native#26209]
I submitted the App to Google Play store and got "StrictMode policy violation" in pre launch report.  
Check the screenshot below.
![Screenshot at Aug 27 13-50-31](https://user-images.githubusercontent.com/47109263/63753965-ae546f80-c8d1-11e9-8879-334e5e876ff9.png)

React Native version:
System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Memory: 562.54 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.5.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.10.1 - /usr/local/bin/npm
    Watchman: 4.7.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    Android SDK:
      API Levels: 16, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 22.0.1, 23.0.1, 23.0.2, 23.0.3, 24.0.0, 24.0.1, 24.0.2, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.2, 26.0.3, 27.0.3, 28.0.0, 28.0.2, 28.0.3
      System Images: android-16 | Google APIs Intel x86 Atom, android-19 | ARM EABI v7a, android-22 | Intel x86 Atom, android-22 | Google APIs ARM EABI v7a, android-22 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom_64, android-24 | Google Play Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-P | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Steps To Reproduce

1. build bundleRelease
2. Upload to google play store
3. Check prelaunch report

Describe what you expected to happen:

I expected without any warnings and errors. But I have got the above warnings, So I am concerned about this. 

Snack, code example, screenshot, or link to a repository:

The issue is coming from core.

**Comment by NikitaPFE** [comment]
I have the same issue
