### ISSUE TITLE
Components translated into view are not tappable on Android

### ISSUE THREAD

**Issue by lehresman** [facebook/react-native#26219]
__React Native version:__
```
  React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
      Memory: 86.03 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.6.0 - ~/.ndenv/versions/12.6/bin/node
      Yarn: 1.17.3 - ~/.ndenv/versions/12.6/bin/yarn
      npm: 6.10.2 - ~/.ndenv/versions/12.6/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
      Android SDK:
        API Levels: 19, 23, 25, 26, 28
        Build Tools: 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
```
## Steps To Reproduce

1. Create a View that is wider than the screen
2. Use `{transform: [{translateX: #}]}` to show parts of the view that were rendered off screen
3. Notice that on Android, nothing that was translated into view is tappable/touchable.

__Describe what you expected to happen:__

I expected consistent behavior between Android and iOS -- mainly, the parts that were translated into view should be tappable on Android.

__Snack, code example, screenshot, or link to a repository:__

Here is an example I created using an Expo Snack, but I don't believe it is an Expo-related issue:  https://snack.expo.io/@lehresman/android-translation-example

Notice the button on the 2nd page (the green one) isn't tappable on Android, but works fine on iOS.

**Comment by badarshahzad** [comment]
Hi @lehresman, I have tested your code. I want to answer your problem but I have qusetion. 

- Can you tell me why you gave the `transform: [{translateX: -200}]`?

If you remove the `transform: [{translateX: -200}]` and gave the `flex:1` in page style then both button views are working. Have look on the [code](https://snack.expo.io/@badarshahzad/android-translation-example).

 *I have concluded that the view wasn't at its correct position*. You didn't give the `innerContainer`width,height or flex which I think can be given. If you don't want to give width,height or flex to `innnerContainer` then at least give it to parent. I noticed `outerContainer` also doesn't have any property which may be causing a issue for 2nd button.

**Comment by badarshahzad** [comment]
Welcome 👋 if you going to make yours then have a look on this how they created a component. It is very good library https://github.com/archriss/react-native-snap-carousel.

**Comment by badarshahzad** [comment]
Dude customize it fork the library make changes in component and import it into your project 👍.

**Comment by badarshahzad** [comment]
> react-native-snap-carousel is very very good. my unique use case is I needed infinite scrolling in both directions, and that library doesn't work well with that. :(

Have a look https://github.com/phil-r/react-native-looped-carousel
