### ISSUE TITLE
[Modal] refs not available in modal

### ISSUE THREAD

**Issue by ortutay** [facebook/react-native#2623]
I have a `TextInput` with a `ref` set, and it is not available in `this.refs`:

The code is:

        <Modal
          animated={true}
          transparent={true}
          visible={this.state.workHerePromptVisible}>
              //...snip...
              <TextInput
                style={someStyle}
                ref="username"
              />
              //...snip...
        </Modal>

I am trying to access `this.refs.username` in a handler

**Comment by alvaromb** [comment]
Which React Native version are you using? I have modals with refs and I can access them.

```javascript
<Modal animated={true}
  transparent={false}
  visible={this.props.visible}>
  <View style={styles.modal}>
    <ElementForm ref='elementForm' />
    <Button onPress={() => {
      // Accessible ref with nested refs
      const elementForm = this.refs.elementForm.refs.form.getValue()
    }}>
      Save
    </Button>
  </View>
</Modal>
```

**Comment by MossP** [comment]
No response from OP, one to close? @brentvatne

**Comment by grabbou** [comment]
Works for me as well.

**Comment by mkonicek** [comment]
Looks like others couldn't repro this one, closing.

**Comment by mkonicek** [comment]
Thanks for checking @grabbou!

**Comment by traviskochel** [comment]
I ran across this as well in 0.11.0. Accessing refs directly from within the modal works, but you can't access them from the outside.

Using the above example as a starting point: 
```
render: function(){

console.log(this.refs) 
// outputs: Object {theModal: Modal}

console.log(this.refs.theModal.refs) 
// outputs: Object {}


return (
<Modal 
  ref='theModal'
  animated={true}
  transparent={false}
  visible={this.props.visible}>

  <View 
    ref='theView' 
    style={styles.modal}>
    
    <ElementForm ref='elementForm' />
    <Button onPress={() => {
      const elementForm = this.refs.elementForm.refs.form.getValue()
     // this works
    }}>
      Save
    </Button>
  </View>
</Modal>
)

}

**Comment by JulianKingman** [comment]
I'm having this issue (using 0.40.0), any idea on what's causing this and how to fix? I also notice re-renders of the modal content ever time the modal is set to visible. Code:
````jsx
<View style={style.wrapper}>
        <Modal
          visible={this.state.singleTaskVisible}
          style={style.singleTaskModal}
          animationType="slide"
        >
          <Swiper
            ref={(component) => {
              this.swiper = component;
            }}
            index={tasks.indexOf(activeTaskId) > -1 ? tasks.indexOf(activeTaskId) : 0}
          >
// ...etc
````
The ref is only available *after* the modal is set to visible.

**Comment by santhosh77h** [comment]
same here 

```
 <Modal
          visible={this.state.singleTaskVisible}
          style={style.singleTaskModal}
          animationType="slide"
        >
          <TextInput
            ref={(component) => {
              this.swiper = component;
            }}
            index={tasks.indexOf(activeTaskId) > -1 ? tasks.indexOf(activeTaskId) : 0}
          /></Model>
<View><TouchableOpacity onPress></View>
..etc
```

I was not able to get the focus of the textinput from `onPress `event.

**Comment by santhosh77h** [comment]
@mkonicek can you check this out.

**Comment by santhosh77h** [comment]
Sorry i solved this by using `onshow `prop inside react-native and added focus to the `textinput`. since the ref for `textinput `is not available outside the `modal`. 

**this solution is only for my use case..**
