### ISSUE TITLE
FlatList scrollToEnd ignores contentContainerStyle bottom padding

### ISSUE THREAD

**Issue by mjmasn** [facebook/react-native#26246]
If you have a `<FlatList />` (and possibly other scrolling views) with a `contentContainerStyle` of `{paddingBottom: 200}`, when `scrollToEnd` is called it scrolls to the bottom of the content, not to the bottom of the entire FlatList. So if you already scrolled to the very end (including padding), the FlatList will actually scroll back up to the bottom of the last item in the list.

React Native version:
```
System:
    OS: Linux 4.15 Ubuntu 16.04.6 LTS (Xenial Xerus)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Memory: 585.51 MB / 15.54 GB
    Shell: 4.3.48 - /bin/bash
  Binaries:
    Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
    Yarn: 1.17.3 - /usr/bin/yarn
    npm: 5.6.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 22, 24, 26, 27, 28, 29
      Build Tools: 23.0.1, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.3, 28.0.2, 28.0.3, 29.0.0
      System Images: android-22 | Google APIs Intel x86 Atom_64, android-24 | Google APIs ARM 64 v8a, android-24 | Google APIs Intel x86 Atom, android-24 | Google APIs Intel x86 Atom_64, android-24 | Google Play Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64
      Android NDK: 17.1.4828580
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-cli: 2.0.1
    react-native-create-library: 3.1.2
    react-native-git-upgrade: 0.2.7
```

## Steps To Reproduce

See https://github.com/mjmasn/FlatListScrollIssue

1. Run the app on android
2. When the app loads, scroll to the very bottom of the flat list so you can see the 200px bottom padding
3. Now whenever scrollToEnd is called, the FlatList will scroll back up, ignoring the padding.

Describe what you expected to happen:

FlatList scrolls fully to the bottom, including the padding height.

Snack, code example, screenshot, or link to a repository:

https://github.com/mjmasn/FlatListScrollIssue

**Comment by mjmasn** [comment]
BTW An easy workaround is to remove the padding and use a `ListFooterComponent` with height equivalent to the padding.

**Comment by mjmasn** [comment]
Looks like same issue with SectionList when there is a list empty component and a list footer, `scrollToEnd` just scrolls to the top instead of the bottom :thinking: (Though admittedly this isn't technically supported - calling scrollToEnd via `_wrapperListRef._listRef.scrollToEnd()`)

**Comment by sundayz** [comment]
When you call scrollToEnd it also ignores height added on by fontSize in `ListFooterComponent. Im trying different things out, but it looks like the only way to make scrollToEnd take it into account is to explicitly set the `height`

**Comment by mjmasn** [comment]
Not stale

**Comment by dody87** [comment]
This is still an issue, but @mjmasn 's solution works.

**Comment by mjmasn** [comment]
Not stale

**Comment by fabriziobertoglio1987** [comment]
when you write `not stale`, I and others receive notification, we un-subscribe and the issue becomes stale

**Comment by mjmasn** [comment]
🤷‍♂️ What can I say, my good friend stale bot disagrees with you...
> **stale** bot removed the `Stale` label yesterday

But in all seriousness this is still a valid issue so it needs to be kept open. The RN maintainers can decide what to do with it next time they do a triage. It's probably a good first issue if someone wants to contribute.

I'm not in a rush to write a PR because I have other commitments and in most cases there's an easy workaround.

**Comment by Yashpk789987** [comment]
This Issue Is Still there with RN version 0.63.0
Please resolve this.

**Comment by junhoyeo** [comment]
This occurs in iOS too; I just met this when I was using horizontal FlatList.
@mjmasn's hack works, but I don't want to spoil my types 😢
