### ISSUE TITLE
Timeout XMLHttpRequest not working in Android

### ISSUE THREAD

**Issue by navata** [facebook/react-native#26240]
Hi All,

I have use XMLHttpRequest for request to server. I have set timeout = 90000ms and my request about 14000ms. But It usually have error. 

```
var xhr = new XMLHttpRequest();
xhr.onreadystatechange = e => {
    if (xhr.readyState !== 4) {
        return;
    }

    if (xhr.status === 200) {
        console.log("success", xhr.responseText);
    } else {
        console.warn("error");
    }
};
xhr.open(
    "POST",
    "http://125.234.136.71/index.php?route=apiv4/post_timeout"
);
xhr.setRequestHeader("Content-type", "application/json; charset=utf-8");
xhr.timeout = 90000; // Set timeout to 90 seconds (90000 milliseconds)
xhr.ontimeout = function() {
    alert("Timed out!!!");
};
xhr.send();
```
My request is working on IOS and Postman, but it don't work on Android.
And more, I try set timeout = 0 (Infinite timer ) => it don't work -_-

**Comment by dulmandakh** [comment]
Android requires HTTPS connections, please use HTTPS or disable HTTPS requirements for your app. Please see https://developer.android.com/training/articles/security-config

**Comment by navata** [comment]
I use test https but timeout not working in Android. I try to set any value. (0, 1000, 90000 ...)
In Android, it will waiting to until receive response or timeout from server.
You can test with my code and use https

**Comment by dulmandakh** [comment]
HTTP timeout might not work properly due to historic reasons, so please use HTTPS from the beginning.

**Comment by navata** [comment]
I use https but timeout don’t working.

**Comment by dsolimando** [comment]
Have same issue... and with HTTPS requests :/
