### ISSUE TITLE
Hermes is failing in react native 0.60.5 when run as  release variant

### ISSUE THREAD

**Issue by YajanaRao** [facebook/react-native#26251]
I am getting error as 
```
> Task :app:bundleReleaseJsAndAssets FAILED

FAILURE: Build failed with an exception.

* Where:
Script '\node_modules\react-native\react.gradle' line: 142

* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command '..\node_modules\hermesvm\win64-bin\hermes'' 
finished with non-zero exit value -1073741515

```

Full exception is attached here
[Exception.txt](https://github.com/facebook/react-native/files/3555647/Exception.txt)

Complete log from Visual Studio App Center's Build
[logs_22.zip](https://github.com/facebook/react-native/files/3555659/logs_22.zip)

React Native version:
```
System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz
    Memory: 1.19 GB / 7.91 GB
  Binaries:
    Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: 4.9.0 - C:\Shortcut\watchman.EXE
  SDKs:
    Android SDK:
      Android NDK: 15.2.4203891
  IDEs:
    Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5692245
```
react-native -v 

```
 react-native-cli: 2.0.1
 react-native: 0.60.5
```

## Steps To Reproduce

1. Create react native project or clone my [github repo ](https://github.com/YajanaRao/Serenity/tree/update)
2. run `react-native run-android --variant=release`

## Github repo link
https://github.com/YajanaRao/Serenity/tree/update

**Comment by phillipkey** [comment]
Also encountering this issue. Is there a fix or a workaround?

**Comment by pistou** [comment]
It seems like there is a [PR#26556](https://github.com/facebook/react-native/pull/26556) to fix this, but I didn't tried it myself.
