### ISSUE TITLE
jsbundle size is about 500k, how to make it smaller?

### ISSUE THREAD

**Issue by heyanyanchina123** [facebook/react-native#2625]
I use curl http://localhost:8081/index.ios.bundle\?dev\=0\&minify\=1 -o main.jsbundle to generate a document,but it is about 500k+, how can I make it smaller?

**Comment by ide** [comment]
gzip?

**Comment by brentvatne** [comment]
Hey there! It's probably best to post this kind of question in StackOverflow, you're more likely to get a good response. Issues are for bugs or feature requests. 

At the moment there is some work being done on allowing for splitting the bundle into separate files, which would not decrease the overall size but could allow you to, for example, update only one part of the bundle if you need to.

**Comment by dongtong** [comment]
Hi brentvatne, do you know how to split bundle file

**Comment by cnsnake11** [comment]
@brentvatne , Hi brentvatne, do you know how to split bundle file
