### ISSUE TITLE
Hermes behaviour different than JSC when using different date libraries.

### ISSUE THREAD

**Issue by tankpower1** [facebook/react-native#26253]
Using some moment.js methods and date-fns functions returns nothing instead of the desired result when developing under hermes engine.

**React Native version:**

System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 183.05 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.4.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 23, 26, 27, 28
      Build Tools: 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.0, 28.0.3, 29.0.0, 29.0.0
      System Images: android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.8.6 => 16.9.0 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

**Steps To Reproduce**

1. ['2019-06-06', '2019-06-07].filter(d => moment(d).isBetween('2019-06-05'. '2019-06-08', null, '[]'));

**Describe what you expected to happen:**

Expected: returns both dates in the array
Result: returns an empty array

**Comment by rikur** [comment]
FYI You have a `.` instead of a `,` between the dates.

**Comment by tankpower1** [comment]
^ Yea my bad i misspelled that but theres still a problem.

**Comment by mhorowitz** [comment]
We're unable to repro this with moment 2.24.0.  Debugging moment is out of our wheelhouse, but Hermes does support this date format with both versions which have been released.
```
$ ./node_modules/hermesvm/osx-bin/hermes-repl
>> new Date('2019-06-06')
[Date 2019-06-06T00:00:00.000Z]
```
If you can reproduce using Date and not moment, or post a standalone JS file which reproduces the problem with the `hermes` or `hermes-repl` tools, that would help us narrow down the problem.
