### ISSUE TITLE
Android Play Store  mandatory to support 64 bit, cannot publish React-native App to Play Store

### ISSUE THREAD

**Issue by sriram-cg-xelp** [facebook/react-native#26268]
<img width="1120" alt="Screenshot 2019-08-30 at 3 23 19 PM" src="https://user-images.githubusercontent.com/22447343/64011914-376ddf80-cb3a-11e9-9ec3-04d174b6934f.png">

<img width="609" alt="Screenshot 2019-08-30 at 3 23 32 PM" src="https://user-images.githubusercontent.com/22447343/64011920-3a68d000-cb3a-11e9-95f0-330454ef8011.png">

https://developer.android.com/distribute/best-practices/develop/64-bit

build.gradle :
// Your app's build.gradle
apply plugin: 'com.android.app'

```
android {
   compileSdkVersion 27
   defaultConfig {
       appId "com.google.example.64bit"
       minSdkVersion 15
       targetSdkVersion 28
       versionCode 1
       versionName "1.0"
       ndk.abiFilters 'armeabi-v7a','arm64-v8a','x86','x86_64'
// ...
```

React Native version:
 "react-native": "^0.55.3"

## Steps To Reproduce

1. Generate signed APK 
2. Install the release APK in a device and check, App crashes.

The React-native app doesn't support 64 bit
Need to check all third party libraries one by one manually
Still couldn't able to run an app.

**Comment by mattmcdonald-uk** [comment]
As of 0.59 React Native supports 64-bit on Android.
