### ISSUE TITLE
[0.61.0-rc.0] No redbox is triggered when a file has errors

### ISSUE THREAD

**Issue by JonnyBurger** [facebook/react-native#26260]
## React Native version: 0.61.0-rc.0

<details>
<pre>
System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Memory: 131.25 MB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.1 - /usr/local/bin/node
    Yarn: 1.15.2 - ~/.yarn/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 23.0.2, 23.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.3, 27.0.2, 27.0.3, 28.0.3
      System Images: android-25 | Google APIs Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.0-rc.0 => 0.61.0-rc.0
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.4
</pre>
</details>

## Steps To Reproduce

1. Create a new app with TypeScript template
```
react-native init RnSixtyOne --version react-native@0.61.0-rc.0 --template typescript
```
2. `cd RnSixtyOne && xed ios`
3. Build and run on a physical device that is connected to Xcode wirelessly
4. Make sure Fast Refresh is turned on
5. Trigger a syntax error in the file:

```diff
- <Text style={styles.sectionTitle}>Step One</Text>
+ <Text style={styles.sectionTitle}Step One</Text>
```

### Describe what you expected to happen:

A redbox should appear, according to @gaearon on Twitter this is the expected behavior

### Snack, code example, screenshot, or link to a repository:

Just a vanilla RN repo, but maybe it's faster to clone it that to create from scratch: https://github.com/JonnyBurger/rn-26260-repro

**Comment by IljaDaderko** [comment]
Happened to me as well, even with fast refresh turned off. Could be a case where turning it on / off changes something that blocks redbox

**Comment by gaearon** [comment]
Is this specific to TypeScript?

**Comment by gaearon** [comment]
Seems like it's neither about TS nor about compile time errors per se.
It's that redbox seems completely broken.

**Comment by gaearon** [comment]
Looks like here's why it's broken:

https://github.com/facebook/react-native/blob/26a8d2e03ab4bba2dbdaae8d49397743c6a72859/Libraries/Core/NativeExceptionsManager.js#L91-L92

https://github.com/facebook/react-native/blame/26a8d2e03ab4bba2dbdaae8d49397743c6a72859/React/CoreModules/RCTExceptionsManager.mm#L92

**Comment by gaearon** [comment]
I'm landing a fix for this.
