### ISSUE TITLE
Text in FlatList is not selectable on Android

### ISSUE THREAD

**Issue by maltoze** [facebook/react-native#26264]
## React Native version: 0.60.5
<details>

```
System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 317.94 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.3.1 - /usr/local/opt/nvm/versions/node/v12.3.1/bin/node
    Yarn: 1.16.0 - ~/.yarn/bin/yarn
    npm: 6.9.0 - /usr/local/opt/nvm/versions/node/v12.3.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 28.0.3, 29.0.1
      System Images: android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.5 => 0.60.5
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

</details>

## Steps To Reproduce
```javascript
export default class App extends React.Component {
  _renderItem = ({item}) => {
    return (
      <View>
        <Text selectable>{item}</Text>
      </View>
    )
  }

  _keyExtractor = (item, index) => index.toString();

  render() {
    return (
      <View style={styles.container}>
        <Text selectable>This is selectable Text...</Text>
        <FlatList
          data={['not selectable text', 'not selectable text']}
          renderItem={this._renderItem}
          keyExtractor={this._keyExtractor}
        />
      </View>
    );
  }
}
```

## Describe what you expected to happen:
Need to be able to select Text in FlatList.

## Snack, code example, screenshot, or link to a repository:
Snack: https://snack.expo.io/@maltoze/selectable-bug-in-flatlist

**Comment by maltoze** [comment]
@react-native-bot updated

**Comment by baldursson** [comment]
Also noticed this. I just upgraded my app from React Native 0.57.4 to 0.60.5 and now I can't select text on Android.

**Comment by chathuraSupun** [comment]
text component selectable feature not working when rendered as a Flatlist item

**Comment by baldursson** [comment]
I curse the day I let React Native into my life

**Comment by tryvin** [comment]
Confirmed in 0.59.8 too, spent a good 30 minutes trying to figure out why this wasn't working on an Android 9.

**Comment by Kiryhas** [comment]
Can confirm, the Text component is selectable, but when rendered as a FlatList element, it is not selectable regardless of the 'selectable' prop.

**Comment by tryvin** [comment]
In my case I could remove the flat list, and use just a scroll view, but this isn't the ideal.

I even did a if for the platform.OS, ios uses flat list, Android uses scroll view

**Comment by ezranbayantemur** [comment]
I have this problem too. Text component can't selectable on FlatList..

**Comment by Ericky14** [comment]
Same problem here

**Comment by fenglu09** [comment]
Same problem in 0.59.10

**Comment by kangsu-dev** [comment]
`key={Math.random()}` not works for me.(rn 0.61.2)
Instead, adding `removeClippedSubviews={false}` for Flatlist solved it.

**Comment by Rohansi** [comment]
Expo SDK 35.0.0 also has this problem. RN 0.59.8.

`removeClippedSubviews={false}` does work around it for me.

**Comment by khorark** [comment]
Added `pointerEvents={'box-none'}` for wrapper View solved this problem.

**Comment by Rohansi** [comment]
I'm on Expo SDK 37 now (RN 0.61.4). Still need `removeClippedSubviews={false}` to select text.

**Comment by fabriziobertoglio1987** [comment]
>Added pointerEvents={'box-none'} for wrapper View solved this problem.
>removeClippedSubviews={false} does work around it for me.

None of this solutions fixed the attached example for me, I tested on the `react-native` master branch head https://github.com/facebook/react-native/commit/63099c40e69f7439dace594bb95b5e87734b946c

Related to https://github.com/facebook/react-native/issues/13938 I'll investigate and I would appreciate any help/input. Thanks

**Comment by fabriziobertoglio1987** [comment]
as displayed in the [following Stack](https://snack.expo.io/@fabrizio.bertoglio/selectable-bug-in-flatlist) adding `removeClippedSubviews={false}` to the `FlatList` fixes the issue. @maltoze would you consider closing this issue? React-Native has currently 744 open issues. :smiley: :peace_symbol:  Thanks Fabrizio

<p align="center">
  <img src="https://user-images.githubusercontent.com/24992535/82231369-595bfc00-992d-11ea-8eed-cf2603cab3dd.png" width="300" />
</p>

**Comment by Rohansi** [comment]
> as displayed in the [following Snack](https://snack.expo.io/@fabrizio.bertoglio/selectable-bug-in-flatlist) adding `removeClippedSubviews={false}` to the `FlatList` fixes the issue. @maltoze would you consider closing this issue? React-Native has currently 744 open issues. 😃 ☮️ Thanks Fabrizio

That's not a fix -- it's a workaround. It sacrifices `FlatList` performance to be able to select text.

**Comment by fabriziobertoglio1987** [comment]
https://github.com/facebook/react-native/blob/aee88b6843cea63d6aa0b5879ad6ef9da4701846/ReactAndroid/src/main/java/com/facebook/react/uimanager/ReactClippingViewGroup.java#L13-L23

The issue https://github.com/facebook/react-native/issues/23870 and pull request https://github.com/facebook/react-native/pull/26334 include many information on `removeClippedSubviews`.

**Comment by fabriziobertoglio1987** [comment]
I solved this. I'm preparing a PR, applying the same solution from https://github.com/facebook/react-native/pull/28852 adding `super.setTextIsSelectable(true);` to [`ReactTextView`](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/text/ReactTextView.java#L434)

```java
  @Override
  public void onAttachedToWindow() {
    super.onAttachedToWindow();
    if (mContainsImages && getText() instanceof Spanned) {
      Spanned text = (Spanned) getText();
      TextInlineImageSpan[] spans = text.getSpans(0, text.length(), TextInlineImageSpan.class);
      for (TextInlineImageSpan span : spans) {
        span.onAttachedToWindow();
      }
    }
    super.setTextIsSelectable(true);
  }
```
I am preparing the PR. Thanks :smiley: 

<p align="left">
  <img src="https://user-images.githubusercontent.com/24992535/82334426-422e1480-99e8-11ea-82a5-6088ef57052d.png)" width="300" />
</p>

**Comment by zoolyka** [comment]
Actually there is another workaround which does not require to disable removeClippedSubviews. Example:

```
export default class SelectableText extends React.Component {

  constructor ( props ) {

    super(props);

    this.state = {
      selectableFix: false
    };

    this.selectableFixTimeout = null;

  }

  shouldComponentUpdate ( nextProps, nextState ) {
    return(
      this.props.text !== nextProps.text ||
      this.state.selectableFix !== nextState.selectableFix
    );
  }

  componentDidMount () {
    this.selectableFixTimeout = setTimeout(() => {
      this.setState({
        selectableFix: true
      });
    }, 100);
  }

  componentWillUnmount () {
    clearTimeout(this.selectableFixTimeout);
  }

  render () {
    return(
      <Text
        selectable={this.state.selectableFix}
      >
        {this.props.text}
      </Text>
    );
  }

}
```

**Comment by fabriziobertoglio1987** [comment]
This issue should not been closed. My pr https://github.com/facebook/react-native/pull/28952 was written to fix this issue, I can improve the pr but please don't close the issue. It is bad.

**Comment by douglasjunior** [comment]
The problem still exists on React Native `0.64.2` 10 months later after being reported.

Settings `removeClippedSubviews={false}` on `FlatList` temporarily solves the issue.
