### ISSUE TITLE
[0.60.5] When relaunching app in debug, stay on white screen forever

### ISSUE THREAD

**Issue by RioFiveJack** [facebook/react-native#26267]
React Native version:

0.60.5
## Steps To Reproduce

1. run react-native run-android
2. apps installed
3. close apps.
4. open it again

Describe what you expected to happen:
apps can relaunch normally, when debug is on , now not even our splash screen appear, 
this still working normally when i'm still using 0.59.5, but this issue doesn't appear when i'm on release version

Snack, code example, screenshot, or link to a repository:
![image](https://user-images.githubusercontent.com/41901530/64006577-d267b900-cb3c-11e9-844a-e10a31244f5e.png)

here's the log on android studio.
![image](https://user-images.githubusercontent.com/41901530/64006651-f4613b80-cb3c-11e9-997f-55e94ce85e3e.png)

**Comment by andrelind** [comment]
I get this in production now, all my 10k+ users need to delete and reinstall the app between sessions on Android.
Such a great experience for them

**Comment by quin0234** [comment]
I have this on iOS and Android, when I CMD+D and enable Debugger the app gets stuck on the loading screen, no errors are reported. I've rebuilt the project but to no joy. AAAARRRGGGHHHH

**Comment by Amit-khatkar** [comment]
this is the issue for the first time run on android after generating bundle, but once you close the app from the task and then reopen it will work as expected

**Comment by RioFiveJack** [comment]
okay i'm using gradle 3.5.0 and the issue is gone.

**Comment by spinus** [comment]
the same issue happened to me when upgrading from 60.5 to 61.5.
@Amit-khatkar your tip is live saver, thank you.
