### ISSUE TITLE
Unable to run 'react-native log-android' on Windows 10

### ISSUE THREAD

**Issue by NicolasNewman** [facebook/react-native#26277]
I just started a project with the following [boilerplate](https://github.com/thecodingmachine/react-native-boilerplate) with the only difference being react-natives version is 0.60.5 and I added native-base. When I ran 'react-native log-android', I received a different error but issue #26198 fixed it. After making the changes described in that issue, I re-ran the command but am now presented with:

```sh
error Command failed: C:\Users\FirstName LastName\AppData\Local\Android\Sdk/platform-tools/adb logcat -c
'C:\Users\FirstName' is not recognized as an internal or external command,
operable program or batch file.
```

I'm assuming it's an issue with the space in the user name?

React Native version:
System:
    OS: Windows 10
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 19.47 GB / 31.55 GB
  Binaries:
    Node: 12.4.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5791312

## Steps To Reproduce

1. A fresh copy of the following [boilerplate](https://github.com/thecodingmachine/react-native-boilerplate) (I use a fork with native on 0.60.5 and native-base)
2. Make the single change described in #26198 inside of node_modules
2. Run `react-native log-android`

Describe what you expected to happen:
Logcat opens and I can see what console.log outputs

**Comment by inf3rnus** [comment]
I'm having this problem as well. The reason the issue is occuring is because of the space in your user directory. I don't know how to edit the CLI tools files, but the solution would be to feed the working directory string into the program as "C:\Users\FirstName LastName\AppData\Local\Android\Sdk/platform-tools/adb logcat -c" 

Basically, Windows is parsing the space between FirstName LastName

**Comment by inf3rnus** [comment]
@NicolasNewman What version of react-native-cli are you using? I'm using that (3.0) and RN 0.61.2

**Comment by NicolasNewman** [comment]
@inf3rnus Unfortunately it's been a while since I've worked on my project or with react-native so I was unable to find the version of react-native-cli. However, RN was 0.60.8.
