### ISSUE TITLE
Why can't StyleSheet. create use constants

### ISSUE THREAD

**Issue by liukefu2050** [facebook/react-native#26271]
Why can't StyleSheet. create use constants

React Native version: "react-native": "0.59.8"

info
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
      Memory: 2.56 GB / 7.84 GB
    Binaries:
      Yarn: 1.16.0 - D:\Program Files\nodejs\yarn.CMD
      npm: 6.9.0 - D:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5692245

## Steps To Reproduce
I want to advance the color attributes to the public JS file, code as follows：

import * as CommonUtils from '../../common/CommonUtils';
//in CommonUtils.js file
export const theme = {
btnColor:'#5bc0de',
};
//Using Constants in CommonUtils
export default class LoginPage extends Component{
...
}
const styles = StyleSheet.create({
loginBtn: {
margin: 10,
backgroundColor: CommonUtils.theme.btnColor,
justifyContent: 'center'
}
});

but this line :**backgroundColor: CommonUtils.theme.btnColor**

report a error :**CommonUtils.theme is undefined**

1. Code as above
2.  react-native run-android

What's the reason?
How to solve this problem

Thank you.

**Comment by JKCooper2** [comment]
Trying consoling out CommonUtils earlier in the file, the issue is probably to do with not importing correctly
