### ISSUE TITLE
[Modal] PickerIOS component not rendering inside Modal

### ISSUE THREAD

**Issue by alvaromb** [facebook/react-native#2628]
When putting a ``<PickerIOS />`` component inside a ``<Modal />`` one, the picker is not rendered. You can reproduce this bug with this example: https://rnplay.org/apps/qZJMHA/edit

**Comment by christopherdro** [comment]
After a bit of debugging, it looks like the shadow view for the Picker doesn't get created when included inside a Modal component.

@ide @brentvatne Any ideas if this is a easy fix?

**Comment by brentvatne** [comment]
As @ide suggests here: https://github.com/facebook/react-native/issues/2322#issuecomment-139917855 - you're probably better off using a top level Navigator if possible. That said, this is still a bug, I don't have the time to look into it right now, but I know that this works on react-native-modal, so you can try that out alternatively, if you like.

**Comment by alvaromb** [comment]
@brentvatne I have a ``Navigator`` as a top level component and I can open a modal with ``FloatFromBottom``. The transition works great but the ``Navigator.NavigationBar`` I have in my navigation performs a push/segue-like animation and that's kinda weird for a modal. This is why I used ``Modal`` component, because it overlaps the navigation bar. I've searched in the docs and in the source code if it's possible to modify the navigation bar animation for that transition (or at least hide the nav bar when floating from bottom) but I couldn't find the solution. I'll try to dig deep this week if I find some time. Thanks Brent!

**Comment by ide** [comment]
@alvaromb Wrap your app in another top-level Modal.

**Comment by alvaromb** [comment]
I see what you mean @ide. Two ``Navigator`` components, always push from the nested one, open modal with the root one, am I right?

**Comment by ide** [comment]
Yeah, it's quite flexible. In practice I've found most non-trivial apps will have more than one Navigator.

**Comment by christopherdro** [comment]
@alvaromb 
Although this was for another issue, it might help understand how you can wrap your app in a top level Navigator component. 

The example shows how you can push a view over a TabBar component. 
https://rnplay.org/apps/-P8G_w

**Comment by alvaromb** [comment]
This approach is working great, thanks @ide & @christopherdro!

**Comment by jacob-israel-turner** [comment]
I ran into this same problem.  `DatePickerIOS` renders inside the modal while `PickerIOS` does not.

**Comment by jacob-israel-turner** [comment]
@brentvatne Looks like this doesn't work with `react-native-modal` either.

**Comment by insraq** [comment]
I can confirm this issue with React 0.11.0

**Comment by mhollweck** [comment]
+1

**Comment by mhollweck** [comment]
Update: I solved my problem with setting the width of the picker and it showed up.

example

  <PickerIOS
    selectedValue={this.state.end}
    onValueChange={this._onEndChange}
    style={{width: 300}}
    >
      {values.map((val) => (
          <PickerItemIOS
             value={val}
              key={val}
              label={val.toString()}
            />
       ))}
  </PickerIOS>

**Comment by machard** [comment]
before 0.17, style is not passed to RCTPickerIOS.
you need to edit the pickerIOS Stylesheet adding the width.

```
var styles = StyleSheet.create({
  pickerIOS: {
    // The picker will conform to whatever width is given, but we do
    // have to set the component's height explicitly on the
    // surrounding view to ensure it gets rendered.
    height: RCTPickerIOSConsts.ComponentHeight,
   // FIX : add witdh
    width: RCTPickerIOSConsts.ComponentWidth,
  },
});
```

**Comment by brentvatne** [comment]
Thanks for the update folks! Looks like this is solved now
