### ISSUE TITLE
Release notes 0.61.0-rc.0: the command line for React Native next version does not work 

### ISSUE THREAD

**Issue by ngothanhtai** [facebook/react-native#26288]
I tried the command line`react-native init RN061 --version next` in [Release note](https://github.com/facebook/react-native/releases/tag/v0.61.0-rc.0) for the React native version but it does not work.
After searching on the internet, the command line should be `react-native init RN061 --version react-native@next`.
I hope someone has permission to update it so other people won't have the same problem as me.

Thank you!

**Comment by jpgarcia** [comment]
Was facing same issue here, maybe @grabbou, @kelset or @cpojer can perform the update, should be an easy and important one 😃

**Comment by kelset** [comment]
thanks for the headsup, it was an error caused by copypasting an old release note 😅 I've fixed it now :)
