### ISSUE TITLE
Cannot expand ZIP ".../hermes-debug.aar"

### ISSUE THREAD

**Issue by swapkids** [facebook/react-native#26285]
Android build is failing with

 `Cannot expand ZIP '/../node_modules/react-native/node_modules/hermesvm/android/hermes-debug.aar' as it does not exist.`

React Native version:
System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 1.06 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.9.0 - ~/.nvm/versions/node/v12.9.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.10.2 - ~/.nvm/versions/node/v12.9.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    Android SDK:
      API Levels: 26, 27, 28
      Build Tools: 27.0.2, 27.0.3, 28.0.2, 28.0.3
      System Images: android-24 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
      Android NDK: 17.2.4988734
  IDEs:
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.5 => 0.60.5
## Steps To Reproduce

1. run 'react-native run android'

Describe what you expected to happen:
A build of my app (it worked with 0.59)

**Comment by sertony** [comment]
Same issue here, have you solved it?

It seems like **hermesvm** folder appears to be created not inside of `../node_modules/react-native/node_modules/hermesvm` but on the top level, aka `../node_modules/hermesvm`

**Comment by xiaosenlin** [comment]
Same issue here,  0.59.0 is ok.

**Comment by d4vidi** [comment]
Indeed - [here](https://github.com/facebook/react-native/blob/0.60-stable/ReactAndroid/build.gradle#L92) an assumption is made of that hermes is installed under react-native's `node_modules` :-/
I'm inclined to try to getting this fixed, will post a workaround here if found.

**Comment by d4vidi** [comment]
I hate myself for this, but here's a new addition to my app's `postinstall` script:

```js
const rnVersion = function() {
  const rnPackageJson = require('react-native/package.json');
  return rnPackageJson.version;
}();

function patchHermesLocationForRN60Android() {
  const semver = require('semver');
  const fs = require('fs-extra');

  if (semver.minor(rnVersion) === 60) {
    const HERMES_PATH_ROOT = './node_modules/hermesvm';
    const HERMES_PATH_RN = './node_modules/react-native/node_modules/hermesvm';

    const hermesIsInRoot = fs.existsSync(HERMES_PATH_ROOT);
    const hermesIsInRN = fs.existsSync(HERMES_PATH_RN);

    if (hermesIsInRoot && !hermesIsInRN) {
      fs.ensureDirSync(`${HERMES_PATH_RN}/android/`);
      fs.copySync(`${HERMES_PATH_ROOT}/android`, `${HERMES_PATH_RN}/android`);
    }
  }
}
patchHermesLocationForRN60Android();
```
