### ISSUE TITLE
console.dir behaviour

### ISSUE THREAD

**Issue by happylolonly** [facebook/react-native#26281]
Why `console.dir` working fine in development mode, but not working and break code in production?

We spent half of the day to debug this.

Source code: https://github.com/facebook/react-native/blob/0.60-stable/Libraries/polyfills/console.js#L579

**Comment by happylolonly** [comment]
In project I fixed it this way

![image](https://user-images.githubusercontent.com/18665326/64063698-44550680-cc00-11e9-8f26-b97984614bbe.png)

**Comment by happylolonly** [comment]
@react-native-bot I think it is enough information to understand the problem.

**Comment by luatnd** [comment]
Hey unintelligent BOT,
Please open it! it's strange behavior and we need to fix it.
