### ISSUE TITLE
Multiple 'Set-Cookie' header values in HTTP response are not respected on Android RN 0.60.5

### ISSUE THREAD

**Issue by pinstripe-potatohead** [facebook/react-native#26280]
Multiple 'Set-Cookie' header values in HTTP response are not respected on Android RN 0.60.4 - only the last one shows up in JS. Multiple 'Set-Cookie' headers are concatenated into a string (correctly) on iOS.
 
React Native version: 0.60.5

**Comment by chenyanfei-m** [comment]
Same problem in v0.59.8

**Comment by ronyv** [comment]
any updates on this ? is this a bug with react native or is it not a good practice to set multiple 'Set-Cookie' headers ?

**Comment by pinstripe-potatohead** [comment]
@ronyv Please look at #23005 and ##21795 . AFAIK, multiple `Set-Cookie` headers with is allowed by the spec. This is a bug with React Native Android. Downgrading to v0.59 will allow you to use the `userNativeAccessor` workaround

**Comment by ronyv** [comment]
@chenyanfei-m : what you suggested is just a workaround for RN versions < 0.60. . I am using 0.60.5 and this is not working. I just don't want to downgrade my RN version for resolving this issue. Rather i will consider some other efficient alternative. Hope RN will fix this fundamental issue in the upcoming releases.

**Comment by ozican** [comment]
@ronyv Hello brother. Did you solve the issue? I still fighting with it, and any help would be great.
