### ISSUE TITLE
flatMap is not a function on iOS 10

### ISSUE THREAD

**Issue by gazedash** [facebook/react-native#26283]
React Native version:

0.59.10

## Steps To Reproduce

1. Run your app on iOS 10
2. Use Array.prototype.flatMap, e.g. [].flatMap(item => item)

Describe what you expected to happen:
Should work like on other OS and platforms

Probably other new ES features don't work too

Snack, code example, screenshot, or link to a repository:

**Comment by fontesrp** [comment]
This is happening in RN version 0.60.4 too

**Comment by frankyjuang** [comment]
Still seeing this on react native 0.61.5 iOS 11

**Comment by vijayst** [comment]
I am seeing this on iOS 11.3 and Expo 36 version of React native.

**Comment by manjuy124** [comment]
Seems flatMap will work iOS 12 and above only.

Safari iOS added support from iOS 12 onwards - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap

**Comment by anka-213** [comment]
How would you configure react-native to use a polyfill for flatMap on systems that don't support it?

**Comment by jd20** [comment]
To support iOS 11 and below, you can add `array-flat-polyfill` to your project, then add to your `App.js`:

```js
`import 'array-flat-polyfill'
```

It will only add the polyfill, if it doesn't already exist.
