### ISSUE TITLE
RNTester, Unable to Run.  'Unrecognized color scheme. did you mean dark or light ?'

### ISSUE THREAD

**Issue by 29er** [facebook/react-native#26286]
Followed the Running on IOS preciseley as described at https://github.com/facebook/react-native/tree/master/RNTester.
Build Succeeds but does not run.

React Native version:
@react-native-community/cli-platform-ios@^3.0.0-alpha.1

## Steps To Reproduce
As descibed here https://github.com/facebook/react-native/tree/master/RNTester

1. git clone https://github.com/facebook/react-native.git
2. cd react-native
3. npm install
3. brew install cocoapods
4. cd RNTester; pod install
5. Open the generated RNTesterPods.xcworkspace in Xcode
6. Click Build and Run
7) Build is successfull. Run fails

Describe what you expected to happen:
App to  run successfully.

![Screen Shot 2019-08-31 at 1 06 44 PM](https://user-images.githubusercontent.com/796719/64068338-f33f1580-cbf3-11e9-9f5e-1f231d95a7b6.png)

**Comment by bartolkaruza** [comment]
Hi there, could you help out by posting your Xcode version and Cocoapods version? I wasn't able to reproduce this issue on my side.

**Comment by 29er** [comment]
Xcode 10.3
cocoa pods 1.5.3

thanks for looking into this @bartolkaruza
